### ISSUE TITLE
Argument parsing errors ignored? `--saveDev`

### ISSUE THREAD

**Issue by mprobst** [npm/npm#10006]
I ran:

```npm i --saveDev google-closure-compiler```

Which should have been `--save-dev`. I got no complaints, but silent failure, it just didn't save the dep.

**Comment by KenanY** [comment]
@mprobst Yeah, `nopt` does not fail on unknown arguments. https://github.com/npm/nopt/issues/41

**Comment by KenanY** [comment]
Closing in light of https://github.com/npm/npm/issues/10047#issuecomment-172124969.
