### ISSUE TITLE
Problem while installing open-edx ; at vagrant up

### ISSUE THREAD

**Issue by gobn888** [npm/npm#10005]
at command I entered vagrant up; and now it stucked at this stage
![problem](https://cloud.githubusercontent.com/assets/8865705/10548829/aafe2782-743d-11e5-954f-6feeb4aaf9a2.jpg)
any idea? :(

**Comment by KenanY** [comment]
@gobn888 Have you tried using the [`--no-bin-links`](https://docs.npmjs.com/misc/config#bin-links) flag?

**Comment by gobn888** [comment]
may i know how to use it? just type --no-bin-links in command line?

**Comment by gobn888** [comment]
![problem2](https://cloud.githubusercontent.com/assets/8865705/10552993/f01e91b6-7457-11e5-8e29-720e910b3496.jpg)

**Comment by KenanY** [comment]
@gobn888 Looks like you are not running `npm install` in a directory that contains a `package.json`. Don't you want to `cd` into that `edx-platform` directory that I see in your original screenshot?

**Comment by gobn888** [comment]
i have put in the package.json inside the folder i am running 'vagrant up' and 'vagrant provision' with;
this is the latest result with package.json in that folder.
i wasn't running 'npm install', do i need to do that?
![problem3](https://cloud.githubusercontent.com/assets/8865705/10559115/a7b7f91c-74e8-11e5-8a5b-32e34b6a2354.jpg)
