### ISSUE TITLE
Postinstall Failure - Autoreconf

### ISSUE THREAD

**Issue by gravidThoughts** [npm/npm#10002]
Node 4.1.2
npm 3.3.4
Windows 7 Enterprise

I just recently installed npm 3 and have seen an issue I don't remember happening. Running [Jon Papa's yeoman angular hottowel](https://github.com/johnpapa/generator-hottowel) I encounter the following error.

```
> gifsicle@3.0.1 postinstall C:\dev\Angular Testing\node_modules\gifsicle
> node lib/install.js

  ‼ Redirected 10 times. Aborting.
  ‼ gifsicle pre-build test failed
  i compiling from source
  x Error: autoreconf -ivf && ./configure --disable-gifview --disable-gifdiff --
prefix="C:\dev\Angular Testing\node_modules\gifsicle\vendor" --bindir="C:\dev\An
gular Testing\node_modules\gifsicle\vendor" && make install
Command failed: C:\WINDOWS\system32\cmd.exe /s /c "autoreconf -ivf"
'autoreconf' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:203:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

After a Google search, `Autoreconf` appears to be a *nix tool.
Should this postinstall task be firing on a Windows box?

**Comment by KenanY** [comment]
@gravidThoughts `npm ` runs `postinstall` runs regardless of architecture. You should open an issue with gifsicle if you think they are doing something incorrectly.

**Comment by gravidThoughts** [comment]
@KenanY It is happening for 3 packages contained in this yeoman generator. Is it possible that this is a misleading error message from `npm`? When I open a node.js command prompt (Windows), it doesn't recognize `autoreconf`. I am assuming, from what you are saying, that some packages that use `postinstall` depend on `autoreconf` being available regardless of the host OS.

**Comment by KenanY** [comment]
@gravidThoughts `npm` is not throwing this error (or, at least, is not the source of the error). `gifsicle` / `bin-build` are trying to exec the `autoreconf` binary which your system does not have, hence an error is thrown.

**Comment by gravidThoughts** [comment]
@KenanY To be clear, I am looking at the line `!!Redirected 10 times. Aborted.` I am wondering if this is causing `install.js` to fail, but it is throwing an unrelated error.... Maybe `install.js` is attempting to download and configure `autoreconf`?

**Comment by KenanY** [comment]
@gravidThoughts Yeah looks like `gifsicle` first tries to download a pre-compiled binary but upon failure will attempt to simply build the binary from source. That error is coming from [here](https://github.com/sindresorhus/got/blob/e2ee4ab645bfec87b948251ad09415e103f83ae3/index.js#L350-L355) (which then goes to `download` then `bin-wrapper` then `gifsicle`).

**Comment by gravidThoughts** [comment]
@KenanY Wow! Thanks. You are teaching me how to fish :). So the build process is depending on `autoreconf`. Funny thing is, I finally got packages using `node-gyp` to work (a couple of hours of pain).  From searching, it does not look like `auotreconf` can be installed on Windows natively(must use cygwin). Do you know the build method `gifsicle` uses?

**Comment by KenanY** [comment]
@gravidThoughts Hmm, no, it does not look like `gifsicle` uses `node-gyp`. `node-gyp` is for building [native addons](https://nodejs.org/api/addons.html), which are C/C++ code that can be compiled to provide a JavaScript API. `gifsicle` (the [actual project](https://github.com/kohler/gifsicle), not the module) is just a C program for doing things with GIFs. The `gifsicle` module just builds/downloads the `gifsicle` C program for you, and exports only the path to the resulting binary.

**Comment by gravidThoughts** [comment]
@KenanY Thanks again!!!!

 Posted an issue on gifsicle and he said it was an npm problem. My hunch is that gifsicle's build process, if it fails to download the binary, will not work on Windows without installing/configuring something else. Still waiting on an answer there.

I will close this for the time being, unless I find definitive evidence it is an npm issue.
