### ISSUE TITLE
installing express-generator

### ISSUE THREAD

**Issue by ghost** [npm/npm#10009]
Android not rooted + GNURoot Debian
Sponsored by:

 _____                   _
|_   _| ___  ___  ___  _| | _ _  ___  ___
  | |  | -_||  _|| . || . || | ||   || -_|
  |_|  |___||_|  |__,||___||_  ||_|_||___|
                           |___|

root@localhost:/# npm install -g express-generator
npm ERR! Error: EFAULT, mkdir '/tmp/npm-13199-URgpu2ei/registry.npmjs.org/express-generator/-'
npm ERR! If you need help, you may report this *entire* log,npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.10.49-gb86829a
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "express-generator"
npm ERR! cwd /
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! path /tmp/npm-13199-URgpu2ei/registry.npmjs.org/express-generator/-
npm ERR! code EFAULT
npm ERR! errno 15
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /npm-debug.log
npm ERR! not ok code 0
root@localhost:/# cat /npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'express-generator' ]
2 info using npm@1.4.21
3 info using node@v0.10.29
4 verbose cache add [ 'express-generator', null ]
5 verbose cache add name=undefined spec="express-generator" args=["express-generator",null]
6 verbose parsed url { protocol: null,
6 verbose parsed url   slashes: null,
6 verbose parsed url   auth: null,
6 verbose parsed url   host: null,
6 verbose parsed url   port: null,
6 verbose parsed url   hostname: null,
6 verbose parsed url   hash: null,
6 verbose parsed url   search: null,
6 verbose parsed url   query: null,
6 verbose parsed url   pathname: 'express-generator',
6 verbose parsed url   path: 'express-generator',
6 verbose parsed url   href: 'express-generator' }
7 silly lockFile 198a68d8-express-generator express-generator
8 verbose lock express-generator /home/.npm/198a68d8-express-generator.lock
9 silly lockFile 198a68d8-express-generator express-generator
10 silly lockFile 198a68d8-express-generator express-generator
11 verbose addNamed [ 'express-generator', '' ]
12 verbose addNamed [ null, '*' ]
13 silly lockFile bd41e3d3-express-generator express-generator@
14 verbose lock express-generator@ /home/.npm/bd41e3d3-express-generator.lock
15 silly addNameRange { name: 'express-generator', range: '*', hasData: false }
16 verbose request where is /express-generator
17 verbose request registry https://registry.npmjs.org/
18 verbose request id 3abc0e71bfcf94f1
19 verbose url raw /express-generator
20 verbose url resolving [ 'https://registry.npmjs.org/', './express-generator' ]
21 verbose url resolved https://registry.npmjs.org/express-generator
22 verbose request where is https://registry.npmjs.org/express-generator
23 info trying registry request attempt 1 at 22:51:27
24 http GET https://registry.npmjs.org/express-generator
25 http 200 https://registry.npmjs.org/express-generator
26 silly registry.get cb [ 200,
26 silly registry.get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
26 silly registry.get     etag: '"DC6D0QBZ1P150ODW8Y6TKATYF"',
26 silly registry.get     'content-type': 'application/json',
26 silly registry.get     'cache-control': 'max-age=60',
26 silly registry.get     'content-length': '31823',
26 silly registry.get     'accept-ranges': 'bytes',
26 silly registry.get     date: 'Fri, 16 Oct 2015 22:51:34 GMT',
26 silly registry.get     via: '1.1 varnish',
26 silly registry.get     age: '0',
26 silly registry.get     connection: 'keep-alive',
26 silly registry.get     'x-served-by': 'cache-iad2124-IAD',
26 silly registry.get     'x-cache': 'HIT',
26 silly registry.get     'x-cache-hits': '1',
26 silly registry.get     'x-timer': 'S1445035894.851157,VS0,VE60',
26 silly registry.get     vary: 'Accept' } ]
27 silly addNameRange number 2 { name: 'express-generator', range: '*', hasData: true }
28 silly addNameRange versions [ 'express-generator',
28 silly addNameRange   [ '1.0.0',
28 silly addNameRange     '3.0.0',
28 silly addNameRange     '4.0.0',
28 silly addNameRange     '4.2.0',
28 silly addNameRange     '4.8.0',
28 silly addNameRange     '4.9.0',
28 silly addNameRange     '4.10.0',
28 silly addNameRange     '4.11.0',
28 silly addNameRange     '4.11.1',
28 silly addNameRange     '4.11.2',
28 silly addNameRange     '4.12.0',
28 silly addNameRange     '4.12.1',
28 silly addNameRange     '4.12.4',
28 silly addNameRange     '4.13.0',
28 silly addNameRange     '4.13.1' ] ]
29 verbose addNamed [ 'express-generator', '4.13.1' ]
30 verbose addNamed [ '4.13.1', '4.13.1' ]
31 silly lockFile 9dc5f3d4-express-generator-4-13-1 express-generator@4.13.1
32 verbose lock express-generator@4.13.1 /home/.npm/9dc5f3d4-express-generator-4-13-1.lock
33 silly lockFile c83a1f7b-tor-express-generator-4-13-1-tgz https://registry.npmjs.org/express-generator/-/express-generator-4.13.1.tgz
34 verbose lock https://registry.npmjs.org/express-generator/-/express-generator-4.13.1.tgz /home/.npm/c83a1f7b-tor-express-generator-4-13-1-tgz.lock
35 verbose addRemoteTarball [ 'https://registry.npmjs.org/express-generator/-/express-generator-4.13.1.tgz',
35 verbose addRemoteTarball   '58351b31f0c7da770c2872bf2a50b9e9359f9968' ]
36 silly lockFile c83a1f7b-tor-express-generator-4-13-1-tgz https://registry.npmjs.org/express-generator/-/express-generator-4.13.1.tgz
37 silly lockFile c83a1f7b-tor-express-generator-4-13-1-tgz https://registry.npmjs.org/express-generator/-/express-generator-4.13.1.tgz
38 silly lockFile 9dc5f3d4-express-generator-4-13-1 express-generator@4.13.1
39 silly lockFile 9dc5f3d4-express-generator-4-13-1 express-generator@4.13.1
40 silly lockFile bd41e3d3-express-generator express-generator@
41 silly lockFile bd41e3d3-express-generator express-generator@
42 error Error: EFAULT, mkdir '/tmp/npm-13199-URgpu2ei/registry.npmjs.org/express-generator/-'
43 error If you need help, you may report this *entire* log,43 error including the npm and node versions, at:
43 error     <http://github.com/npm/npm/issues>
44 error System Linux 3.10.49-gb86829a
45 error command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "express-generator"
46 error cwd /
47 error node -v v0.10.29
48 error npm -v 1.4.21
49 error path /tmp/npm-13199-URgpu2ei/registry.npmjs.org/express-generator/-
50 error code EFAULT
51 error errno 15
52 verbose exit [ 15, true ]
root@localhost:/#

**Comment by KenanY** [comment]
@guiguithub I have never seen `EFAULT` here before, but since there is no JavaScript stack trace I believe your filesystem might be throwing this error and not `npm` (although, again, I admit that I do not know what this error is). Does this also occur if you [upgrade](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) to the latest stable release of `npm`?

**Comment by guiguithub** [comment]
Sponsored by:

 _____                   _
|_   _| ___  ___  ___  _| | _ _  ___  ___
  | |  | -_||  _|| . || . || | ||   || -_|
  |_|  |___||_|  |__,||___||_  ||_|_||___|
                           |___|

root@localhost:/# npm install -g npm
npm ERR! Linux 3.10.49-gb86829a
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "npm"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! path /tmp/npm-26261-41ec33b5/registry.npmjs.org/npm/-
npm ERR! code EFAULT
npm ERR! errno -14

npm ERR! EFAULT, mkdir '/tmp/npm-26261-41ec33b5/registry.npmjs.org/npm/-'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log
root@localhost:/# cat /npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'install', '-g', 'npm' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose node symlink /usr/bin/node
5 verbose install initial load of /usr/lib/package.json
6 verbose readDependencies loading dependencies from /usr/lib/package.json
7 silly cache add args [ 'npm', null ]
8 verbose cache add spec npm
9 silly cache add parsed spec { raw: 'npm',
9 silly cache add   scope: null,
9 silly cache add   name: 'npm',
9 silly cache add   rawSpec: '',
9 silly cache add   spec: '*',
9 silly cache add   type: 'range' }
10 silly addNamed npm@*
11 verbose addNamed "*" is a valid semver range for npm
12 silly addNameRange { name: 'npm', range: '*', hasData: false }
13 silly mapToRegistry name npm
14 silly mapToRegistry using default registry
15 silly mapToRegistry registry https://registry.npmjs.org/
16 silly mapToRegistry uri https://registry.npmjs.org/npm
17 verbose addNameRange registry:https://registry.npmjs.org/npm not in flight; fetching
18 verbose request uri https://registry.npmjs.org/npm
19 verbose request no auth needed
20 info attempt registry request try #1 at 01:27:43
21 verbose request id 6c3fc69e270b6cf0
22 http request GET https://registry.npmjs.org/npm
23 http 200 https://registry.npmjs.org/npm
24 silly get cb [ 200,
24 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
24 silly get     etag: '"59IAKSC0JL44WSJA9NFBI72KL"',
24 silly get     'content-type': 'application/json',
24 silly get     'cache-control': 'max-age=60',
24 silly get     'content-length': '3496107',
24 silly get     'accept-ranges': 'bytes',
24 silly get     date: 'Sat, 17 Oct 2015 01:27:50 GMT',
24 silly get     via: '1.1 varnish',
24 silly get     age: '31',
24 silly get     connection: 'keep-alive',
24 silly get     'x-served-by': 'cache-lax1426-LAX',
24 silly get     'x-cache': 'HIT',
24 silly get     'x-cache-hits': '1',
24 silly get     'x-timer': 'S1445045270.325431,VS0,VE18',
24 silly get     vary: 'Accept' } ]
25 verbose get saving npm to /home/.npm/registry.npmjs.org/npm/.cache.json
26 silly addNameRange number 2 { name: 'npm', range: '*', hasData: true }
27 silly addNameRange versions [ 'npm',
27 silly addNameRange   [ '1.1.25',
27 silly addNameRange     '1.2.32',
27 silly addNameRange     '1.3.2',
27 silly addNameRange     '1.3.4',
27 silly addNameRange     '1.2.20',
27 silly addNameRange     '1.2.21',
27 silly addNameRange     '1.2.22',
27 silly addNameRange     '1.2.23',
27 silly addNameRange     '1.2.24',
27 silly addNameRange     '1.2.25',
27 silly addNameRange     '1.2.27',
27 silly addNameRange     '1.2.28',
27 silly addNameRange     '1.2.30',
27 silly addNameRange     '1.2.31',
27 silly addNameRange     '1.3.0',
27 silly addNameRange     '1.3.1',
27 silly addNameRange     '1.2.19',
27 silly addNameRange     '1.1.70',
27 silly addNameRange     '1.1.71',
27 silly addNameRange     '1.3.5',
27 silly addNameRange     '1.3.6',
27 silly addNameRange     '1.3.7',
27 silly addNameRange     '1.3.8',
27 silly addNameRange     '1.3.9',
27 silly addNameRange     '1.3.10',
27 silly addNameRange     '1.3.11',
27 silly addNameRange     '1.3.12',
27 silly addNameRange     '1.3.13',
27 silly addNameRange     '1.3.14',
27 silly addNameRange     '1.3.15',
27 silly addNameRange     '1.3.16',
27 silly addNameRange     '1.3.17',
27 silly addNameRange     '1.3.18',
27 silly addNameRange     '1.3.20',
27 silly addNameRange     '1.3.21',
27 silly addNameRange     '1.3.22',
27 silly addNameRange     '1.3.23',
27 silly addNameRange     '1.3.24',
27 silly addNameRange     '1.3.25',
27 silly addNameRange     '1.3.26',
27 silly addNameRange     '1.4.0',
27 silly addNameRange     '1.4.1',
27 silly addNameRange     '1.4.2',
27 silly addNameRange     '1.4.3',
27 silly addNameRange     '1.4.4',
27 silly addNameRange     '1.4.5',
27 silly addNameRange     '1.4.6',
27 silly addNameRange     '1.4.7',
27 silly addNameRange     '1.4.8',
27 silly addNameRange     '1.4.9',
27 silly addNameRange     '1.4.10',
27 silly addNameRange     '1.4.11',
27 silly addNameRange     '1.4.12',
27 silly addNameRange     '1.4.13',
27 silly addNameRange     '1.4.14',
27 silly addNameRange     '1.4.15',
27 silly addNameRange     '1.4.16',
27 silly addNameRange     '1.2.8000',
27 silly addNameRange     '1.4.17',
27 silly addNameRange     '1.4.18',
27 silly addNameRange     '1.4.19',
27 silly addNameRange     '1.5.0-alpha-0',
27 silly addNameRange     '1.5.0-alpha-1',
27 silly addNameRange     '1.4.20',
27 silly addNameRange     '1.5.0-alpha-2',
27 silly addNameRange     '1.4.21',
27 silly addNameRange     '1.5.0-alpha-3',
27 silly addNameRange     '1.5.0-alpha-4',
27 silly addNameRange     '2.0.0-alpha-5',
27 silly addNameRange     '1.4.22',
27 silly addNameRange     '1.4.23',
27 silly addNameRange     '2.0.0-alpha.6.0',
27 silly addNameRange     '1.4.24',
27 silly addNameRange     '2.0.0-alpha.6',
27 silly addNameRange     '2.0.0-alpha.7',
27 silly addNameRange     '2.0.0-beta.0',
27 silly addNameRange     '1.4.25',
27 silly addNameRange     '2.0.0-beta.1',
27 silly addNameRange     '1.4.26',
27 silly addNameRange     '2.0.0-beta.2',
27 silly addNameRange     '1.4.27',
27 silly addNameRange     '2.0.0-beta.3',
27 silly addNameRange     '1.4.28',
27 silly addNameRange     '2.0.0',
27 silly addNameRange     '2.0.1',
27 silly addNameRange     '2.0.2',
27 silly addNameRange     '2.1.0',
27 silly addNameRange     '2.1.1',
27 silly addNameRange     '2.1.2',
27 silly addNameRange     '2.1.3',
27 silly addNameRange     '2.1.4',
27 silly addNameRange     '2.1.5',
27 silly addNameRange     '2.1.6',
27 silly addNameRange     '2.1.7',
27 silly addNameRange     '2.1.8',
27 silly addNameRange     '2.1.9',
27 silly addNameRange     '2.1.10',
27 silly addNameRange     '2.1.11',
27 silly addNameRange     '2.1.12',
27 silly addNameRange     '2.1.13',
27 silly addNameRange     '2.1.14',
27 silly addNameRange     '2.1.15',
27 silly addNameRange     '2.1.16',
27 silly addNameRange     '2.1.17',
27 silly addNameRange     '2.1.18',
27 silly addNameRange     '2.2.0',
27 silly addNameRange     '2.3.0',
27 silly addNameRange     '2.4.0',
27 silly addNameRange     '2.4.1',
27 silly addNameRange     '2.5.0',
27 silly addNameRange     '2.5.1',
27 silly addNameRange     '2.6.0',
27 silly addNameRange     '2.6.1',
27 silly addNameRange     '2.7.0',
27 silly addNameRange     '2.7.1',
27 silly addNameRange     '2.7.2',
27 silly addNameRange     '2.7.3',
27 silly addNameRange     '2.7.4',
27 silly addNameRange     '2.7.5',
27 silly addNameRange     '2.7.6',
27 silly addNameRange     '2.8.0',
27 silly addNameRange     '2.8.1',
27 silly addNameRange     '2.8.2',
27 silly addNameRange     '2.8.3',
27 silly addNameRange     '2.8.4',
27 silly addNameRange     '2.9.0',
27 silly addNameRange     '2.9.1',
27 silly addNameRange     '2.10.0',
27 silly addNameRange     '2.10.1',
27 silly addNameRange     '2.11.0',
27 silly addNameRange     '2.11.1',
27 silly addNameRange     '2.11.2',
27 silly addNameRange     '2.11.3',
27 silly addNameRange     '2.12.0',
27 silly addNameRange     '3.0.0',
27 silly addNameRange     '2.12.1',
27 silly addNameRange     '2.13.0',
27 silly addNameRange     '3.1.0',
27 silly addNameRange     '2.13.1',
27 silly addNameRange     '3.1.1',
27 silly addNameRange     '3.1.2',
27 silly addNameRange     '2.13.2',
27 silly addNameRange     '3.1.3',
27 silly addNameRange     '2.13.3',
27 silly addNameRange     '3.2.0',
27 silly addNameRange     '2.13.4',
27 silly addNameRange     '3.2.1',
27 silly addNameRange     '2.13.5',
27 silly addNameRange     '3.2.2',
27 silly addNameRange     '2.14.0',
27 silly addNameRange     '3.3.0',
27 silly addNameRange     '2.14.1',
27 silly addNameRange     '2.14.2',
27 silly addNameRange     '3.3.1',
27 silly addNameRange     '2.14.3',
27 silly addNameRange     '3.3.2',
27 silly addNameRange     '2.14.4',
27 silly addNameRange     '3.3.3',
27 silly addNameRange     '2.14.5',
27 silly addNameRange     '3.3.4',
27 silly addNameRange     '2.14.6',
27 silly addNameRange     '3.3.5',
27 silly addNameRange     '3.3.6',
27 silly addNameRange     '2.14.7',
27 silly addNameRange     '2.14.8',
27 silly addNameRange     '3.3.7',
27 silly addNameRange     '3.3.8',
27 silly addNameRange     '3.3.9' ] ]
28 silly addNamed npm@3.3.8
29 verbose addNamed "3.3.8" is a plain semver version for npm
30 silly mapToRegistry name npm
31 silly mapToRegistry using default registry
32 silly mapToRegistry registry https://registry.npmjs.org/
33 silly mapToRegistry uri https://registry.npmjs.org/npm
34 verbose addRemoteTarball https://registry.npmjs.org/npm/-/npm-3.3.8.tgz not in flight; adding
35 verbose addRemoteTarball [ 'https://registry.npmjs.org/npm/-/npm-3.3.8.tgz',
35 verbose addRemoteTarball   '7bbcc33b2921b7abe677bb1966773158cf47ea9e' ]
36 verbose stack Error: EFAULT, mkdir '/tmp/npm-26261-41ec33b5/registry.npmjs.org/npm/-'
36 verbose stack     at Error (native)
37 verbose cwd /
38 error Linux 3.10.49-gb86829a
39 error argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "npm"
40 error node v0.12.7
41 error npm  v2.11.3
42 error path /tmp/npm-26261-41ec33b5/registry.npmjs.org/npm/-
43 error code EFAULT
44 error errno -14
45 error EFAULT, mkdir '/tmp/npm-26261-41ec33b5/registry.npmjs.org/npm/-'
46 error If you need help, you may report this error at:
46 error     <https://github.com/npm/npm/issues>
47 verbose exit [ -14, true ]
root@localhost:/#

**Comment by KenanY** [comment]
Hmm

> `EFAULT` It happen if the memory address of some argument passed to `sendto` (or more generally to any system call) is invalid. Think of it as a sort of `SIGSEGV` in kernel land regarding your syscall. For instance, if you pass a null or invalid buffer pointer (for reading, writing, sending, recieving...), you get that

http://stackoverflow.com/a/9261028

**Comment by KenanY** [comment]
Closing since reporter's GitHub account has since been deleted. Can reopen if this is still an issue.
