### ISSUE TITLE
`npm install` failing on 1gb ram vps

### ISSUE THREAD

**Issue by Gavrisimo** [npm/npm#10003]
So I have `Linode 1GB` vps with `Ubuntu 14.04.3 LTS` over at linode.com and I was trying to run `npm install` in wordpress theme based on Sage, here is the `package.json`:

https://github.com/roots/sage/blob/master/package.json

These are the commands I used to get latest `node` and `npm` versions:

```
curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
sudo apt-get install -y nodejs

$ node -v
v4.2.1
$ npm -v
2.14.7
```

First I was getting this:
```
$ sudo /usr/bin/npm install
npm WARN optional dep failed, continuing fsevents@1.0.2
npm WARN cannot run in wd gifsicle@3.0.1 node lib/install.js (wd=/home/forge/default/public/oshinstudio.com/baron-vr/wp-content/themes/baron-vr-theme/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle)

optipng-bin@3.0.2 postinstall /home/forge/default/public/oshinstudio.com/baron-vr/wp-content/themes/baron-vr-theme/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin
node lib/install.js


/
```

And then it just stops.

Then I used https://docs.npmjs.com/getting-started/fixing-npm-permissions to try and fix that `sudo` thing,  but same result with `/usr/bin/npm install` and `npm install`.

Then I took the names of all packages and run then like this: `npm install package-1 package-2 ...` but it failed as well.

Then I took half of those packages and ran them the same way, this time it worked. After that I took remaining half of packages and ran them the same way. Success. I was finally able to run `gulp --production`.

Funny thing is, this is same type of server in same datacenter, deployed in the same way as the one I had previously, where of course I never got any error regarding these kinda things, which I presume is memory related.

Any thoughts or suggestions on this are more then welcomed!

**Comment by thephilip** [comment]
I don't know if it's wrong for me to say this, but I've always had issues using the nodejs binary installers for the various distributions.  I would try from source.  If you need it to be installed with root (e.g. production) access, just substitute the `make install` below with `sudo make install`.

`$ mkdir node-install && cd node-install`
`$ wget http://nodejs.org/dist/node-latest.tar.gz`
`$ tar xzvf node-latest.tar.gz && cd node-*`
`$ ./configure`
`$ make`
`$ make test`
`$ make install`

Alternatively, you can use NVM (my preferred method), but I don't know if I'm crossing any lines there either, lol.

**Comment by Gavrisimo** [comment]
Ok, I created a new vps with 512gb ram on digitalocean and followed your instructions to install node.

It ended up being installed in `/usr/local/` which is amazing, so finally I could fix permissions by following https://docs.npmjs.com/getting-started/fixing-npm-permissions like so:

```
sudo chown -R `whoami` /usr/local/lib/node_modules
sudo chown -R `whoami` /usr/local/bin
sudo chown -R `whoami` /usr/local/share
```
