### ISSUE TITLE
shasum check failed while installing cordova

### ISSUE THREAD

**Issue by chetan1oct93** [npm/npm#10017]
40 http fetch GET http://registry.npmjs.org/cordova/-/cordova-5.3.3.tgz
41 http fetch 200 http://registry.npmjs.org/cordova/-/cordova-5.3.3.tgz
42 info retry will retry, error on last attempt: Error: read ECONNRESET
43 info retry will retry, error on last attempt: Error: read ECONNRESET
44 silly fetchAndShaCheck shasum d8933ea57cf4d390a1c86d0b43def76f61fb4d76
45 verbose stack Error: shasum check failed for C:\Users\CHETAN~1\AppData\Local\Temp\npm-9928-9dd9d7df\registry.npmjs.org\cordova\-\cordova-5.3.3.tgz
45 verbose stack Expected: d8933ea57cf4d390a1c86d0b43def76f61fb4d76
45 verbose stack Actual:   fc700bf010b57f76c105fd68c9233a7b18ba2008
45 verbose stack From:     http://registry.npmjs.org/cordova/-/cordova-5.3.3.tgz
45 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:25:8
45 verbose stack     at ReadStream.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:72:7)
45 verbose stack     at emitNone (events.js:72:20)
45 verbose stack     at ReadStream.emit (events.js:166:7)
45 verbose stack     at endReadableNT (_stream_readable.js:903:12)
45 verbose stack     at doNTCallback2 (node.js:439:9)
45 verbose stack     at process._tickCallback (node.js:353:17)
46 verbose cwd C:\WINDOWS\system32
<b>47 error Windows_NT 10.0.10240</b>
48 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova"
49 error node v4.2.1
50 error npm  v2.14.7
<b>51 error shasum check failed for C:\Users\CHETAN~1\AppData\Local\Temp\npm-9928-9dd9d7df\registry.npmjs.org\cordova\-\cordova-5.3.3.tgz
51 error Expected: d8933ea57cf4d390a1c86d0b43def76f61fb4d76
51 error Actual:   fc700bf010b57f76c105fd68c9233a7b18ba2008</b>
51 error From:     http://registry.npmjs.org/cordova/-/cordova-5.3.3.tgz
52 error If you need help, you may report this error at:
52 error     <https://github.com/npm/npm/issues>
53 verbose exit [ 1, true ]

<b>NOTE: I have tried npm cache clear, setting registry to "http://registry.npmjs.org/", run all this with administrator rights and without. I have set all the paths correctly. Also using latest node version 4.2.1.
Also i have read somewhere Kaspersky tries to block .tgz files. so tried all this by disabling the ANTIVIRUS</b>

**Comment by busches** [comment]
Is this still an issue for you? Attempting to install `cordova` now works correctly.

**Comment by KenanY** [comment]
Closing as abandoned.

**Comment by chetan1oct93** [comment]
Its working now thanks.
