### ISSUE TITLE
warning message :npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: { "node":"4.2.1","npm":"2.14.7"})

### ISSUE THREAD

**Issue by misterraj7** [npm/npm#10019]
I get this warning message when I ran :+1: 
npm install -g phonegap

npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {
"node":"4.2.1","npm":"2.14.7"})

can I ignore this ?

**Comment by chetan1oct93** [comment]
Even i got the same message followed by error SHA checksum. Still not got a solution to it..

**Comment by nkccaomus** [comment]
Yes. I got the same message.
