### ISSUE TITLE
Error with npm after installing MAC OS X El Capitan

### ISSUE THREAD

**Issue by KevinRaimbaud** [npm/npm#10010]
Hi,
I have NodeJS installing on my computer.
```
$ node -v
v4.2.1
```

I'm trying to install bower. Here is the result:
```
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "bower"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! path /usr/local/lib/node_modules/bower
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall rmdir

npm ERR! Error: EACCES: permission denied, rmdir '/usr/local/lib/node_modules/bower'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, rmdir '/usr/local/lib/node_modules/bower']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'rmdir',
npm ERR!   path: '/usr/local/lib/node_modules/bower' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.
npm ERR! error rolling back Error: EACCES: permission denied, rmdir '/usr/local/lib/node_modules/bower'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  { [Error: EACCES: permission denied, rmdir '/usr/local/lib/node_modules/bower']
npm ERR! error rolling back   errno: -13,
npm ERR! error rolling back   code: 'EACCES',
npm ERR! error rolling back   syscall: 'rmdir',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/bower' }

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Kevin/Sites/npm-debug.log
```

I tried to do:
```
$ sudo chown -R $(whoami) ~/.npm
chown: /Users/Kevin/.npm/_locks: Operation not permitted
chown: /Users/Kevin/.npm/bower/1.6.3/package/package.json: Operation not permitted
chown: /Users/Kevin/.npm/bower/1.6.3/package: Operation not permitted
chown: /Users/Kevin/.npm/bower/1.6.3/package.tgz: Operation not permitted
chown: /Users/Kevin/.npm/bower/1.6.3: Operation not permitted
chown: /Users/Kevin/.npm/bower: Operation not permitted
chown: /Users/Kevin/.npm/n: Operation not permitted
```

Is seems like I don't have permission at all.
And can not install anything.

How can I fix that?

**Comment by KenanY** [comment]
@KevinRaimbaud Have you tried using `sudo` in your `npm install -g` command? Looks like you do not have permission to write to `/usr/local`, but that's where your global modules are going,

**Comment by KevinRaimbaud** [comment]
Yes I did all my commands with sudo.

**Comment by dawsonbotsford** [comment]
@KevinRaimbaud, it's very unlikely that sudo is the best option for **all** of your commands. Although El Capitan may have created issues, it sounds like you are being faced with a permissions issue. See [fixing npm permissions](https://docs.npmjs.com/getting-started/fixing-npm-permissions) and report back.

**Comment by KevinRaimbaud** [comment]
The problem was not about nodejs. It was a permission problem in my MAC OS X. I just reinstall it to fix it.

**Comment by Lors** [comment]
Hi @KevinRaimbaud I'm curious to know about that issue, can you please point or give me info to the solution? Appreciate your help!

**Comment by KevinRaimbaud** [comment]
I won't be very helpful. I had this problem after updating my MAC OS X to El Capitan. And I figured out having a permission issue with every command line I was typing. Not just with npm.
So I have preferred reinstalling the OS to start over with a clean system.
I'm know using docker to do not have this kind of problem anymore.

**Comment by Lors** [comment]
@KevinRaimbaud thanks man! :) no problem

**Comment by creepycheese** [comment]
`sudo chown -R $(whoami) `~/ solved the problem for me. Had the same issue after upgrading to El Capitan.

**Comment by mycardiopad** [comment]
I have the same problem
How can I fix it without reinstalling my OS ?

**Comment by KenanY** [comment]
@mycardiopad Have you seen [this](https://docs.npmjs.com/getting-started/fixing-npm-permissions)?

**Comment by ssdr** [comment]
same problem...

**Comment by ssdr** [comment]
@KenanY big help!

**Comment by samridhigupta** [comment]
Is there a fix to this problem without reinstalling or using docker?

**Comment by ayaz6171** [comment]
**Ayaz Khan**
you have no permissions to write, use the sudo command

sudo npm install -g cordova ios-deploy
then enter your password

**Comment by surajdubey** [comment]
I had the same issue. 
Tried with sudo.
It worked.

**Comment by fantagaro** [comment]
sudo npm install -g xxxxx 
is the solution, of course with correct admin password.

**Comment by jianlongoxf8** [comment]
I had the same issue. 

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-d" "lodash"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3

Tried with sudo.
It don't worked.

**Comment by Elijahhh** [comment]
sudo npm install -g   XXXXXX    works for me!   10.11.5

**Comment by sk559486** [comment]
sudo chown -R $(whoami) ~/           this command worked for me as well.Thanks

**Comment by vonschbo** [comment]
Same issue here, solved just by typing: sudo chown -R $(whoami) /usr/local/bin/node_modules, to change root into my user name

**Comment by JRD19** [comment]
I tried it on OSX, had no choice but to use sudo npm install because chown didnt work for me.

**Comment by eliasfaical** [comment]
Hey, I solved this way https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by ajitbubu** [comment]
Type the below line in command line it will work, its work for me

sudo chown -R $USER /usr/local

**Comment by qifei** [comment]
I tried this https://docs.npmjs.com/getting-started/fixing-npm-permissions

BUT:

npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "uglify-js" "-g"
npm ERR! node v6.10.0
npm ERR! npm  v4.2.0
npm ERR! path ../lib/node_modules/uglify-js/bin/uglifyjs
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall symlink

npm ERR! Error: EACCES: permission denied, symlink '../lib/node_modules/uglify-js/bin/uglifyjs' -> '/usr/local/bin/uglifyjs'
npm ERR!     at Error (native)
npm ERR!  { Error: EACCES: permission denied, symlink '../lib/node_modules/uglify-js/bin/uglifyjs' -> '/usr/local/bin/uglifyjs'
npm ERR!     at Error (native)
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'symlink',
npm ERR!   path: '../lib/node_modules/uglify-js/bin/uglifyjs',
npm ERR!   dest: '/usr/local/bin/uglifyjs' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mike/.npm/_logs/2017-02-23T09_13_50_423Z-debug.log

**Comment by maxpou** [comment]
> I tried this https://docs.npmjs.com/getting-started/fixing-npm-permissions
> 
> BUT:
> 
> npm ERR! Darwin 16.4.0
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "uglify-js" "-g"
> npm ERR! node v6.10.0
> npm ERR! npm v4.2.0
> npm ERR! path ../lib/node_modules/uglify-js/bin/uglifyjs
> npm ERR! code EACCES
> npm ERR! errno -13
> npm ERR! syscall symlink

I see symlink... so add [`--no-bin-links`](https://docs.npmjs.com/misc/config#bin-links) flag

**Comment by poonia** [comment]
try this `npm update npm -g `

**Comment by lzricardo** [comment]
Thanks @eliasfaical
