### ISSUE TITLE
 jade index.jade : character "d" not allowed in prolog

### ISSUE THREAD

**Issue by 1303110335** [npm/npm#10027]
root@vagrant-ubuntu-trusty-64:/vagrant/www/nodejs/imoc/views# jade index.jade
jade:index.jade:1:0:E: character "d" not allowed in prolog
jade:index.jade:6:24:E: end of document in prolog
jade:E: cannot find "index.dsl"; tried "index.dsl", "/usr/local/share/sgml/index.dsl", "/usr/share/sgml/index.dsl"
jade:E: specification document does not have the DSSSL architecture as a base architecture

**Comment by KenanY** [comment]
Hi @1303110335! I don't think the issue you are seeing is an issue with `npm`. I think you would have better luck finding a solution for this over at [`jade`'s issue tracker](https://github.com/jadejs/jade).
