### ISSUE TITLE
friendli-ize the tone in the FAQ

### ISSUE THREAD

**Issue by AndSheCodes2** [npm/npm#10022]
wording here is a little bit... rude? let's try to improve the tone of the language to be a little bit more inclusive and a little less aggressive!

https://docs.npmjs.com/misc/faq

e.g.

Why didn't it work?

I don't know yet.

Read the error output, and if you can't figure out what it means, do what it says and post a bug with all the information it asks for.
=>

Why didn't it work?

With no context, it's impossible to know!

A good place to start is to focus on the error output. First, try to follow the instructions it give

**Comment by KenanY** [comment]
The FAQ page was removed by https://github.com/npm/npm/pull/10547 so this is no longer needed.
