### ISSUE TITLE
npm ERR! missing script: gulp on Ubuntu 14.04 with node v5.0.0-pre and npm v2.14.7

### ISSUE THREAD

**Issue by zodthepossum** [npm/npm#10034]
Hello I've been trying for over a week now to install npm and other dependencies - elixir and gulp

I am not able to run gulp, here is my npm-debug.log

````
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'gulp' ]
2 info using npm@2.14.7
3 info using node@v5.0.0-pre
4 verbose stack Error: missing script: gulp
4 verbose stack     at run (/usr/local/lib/node_modules/npm/lib/run-script.js:142:19)
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/run-script.js:58:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:345:5
4 verbose stack     at checkBinReferences_ (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:309:45)
4 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:343:3)
4 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:113:5)
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:232:12
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:76:16
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
5 verbose cwd /home/susana/public_html/zod2
6 error Linux 3.13.0-32-generic
7 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "gulp"
8 error node v5.0.0-pre
9 error npm  v2.14.7
10 error missing script: gulp
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@zodthepossum 

```
4 verbose stack Error: missing script: gulp
```

Do you have a `"gulp"` [script](https://docs.npmjs.com/misc/scripts) defined in your [`package.json`](https://docs.npmjs.com/files/package.json)? If not, `npm` will have no idea what you want it to do when you do [`npm run gulp`](https://docs.npmjs.com/cli/run-script). Perhaps you'd like to just run `gulp`? Maybe `gulp`'s [getting started](https://github.com/gulpjs/gulp/blob/v3.9.0/docs/getting-started.md) guide can help you?

**Comment by zodthepossum** [comment]
@KenanY
I have the following in my gulp.js
var elixir = require('laravel-elixir');

/*
 |--------------------------------------------------------------------------
 | Elixir Asset Management
 |--------------------------------------------------------------------------
 |
 | Elixir provides a clean, fluent API for defining some basic Gulp tasks
 | for your Laravel application. By default, we are compiling the Less
 | file for our application, as well as publishing vendor resources.
 |
 */

elixir(function(mix) {
    mix.less('app.less');
});

and the following in my package.json
{
  "private": true,
  "devDependencies": {
    "gulp": "^3.9.0",
    "laravel-elixir": "^1.0.0"
  }
}

**Comment by KenanY** [comment]
@zodthepossum If you need help with `laravel`/`elixir`/`laravel-elixir` then you should contact the authors of those modules.

**Comment by KenanY** [comment]
@zodthepossum Is this still an issue for you? It has been several months since your last response.

**Comment by KenanY** [comment]
Closing as abandoned and not an issue with `npm`.
