### ISSUE TITLE
npm installation error

### ISSUE THREAD

**Issue by Kannan3400** [npm/npm#10038]
![error](https://cloud.githubusercontent.com/assets/15213597/10607317/67beff3e-7756-11e5-8492-27b80cb9af61.PNG)

if i type npm install command in cmd it is throing me this error.Please help me with this.

**Comment by othiym23** [comment]
What happens if you run `npm cache clean` and then run the install again?

**Comment by Kannan3400** [comment]
I tried it,but it still throwing me the same error
