### ISSUE TITLE
Failed to connect to github.com port 443: connection refused

### ISSUE THREAD

**Issue by kunalgithub** [npm/npm#10037]
Error fatal : unable to access 'https://github.com/joshuafcole/async-node-events.git' : Failed to connect to  gitHub.com port 443 : Connection Refused.

**Comment by KenanY** [comment]
@kunalgithub Seems like an issue with your internet connection. Are you behind a proxy or firewall that might be disrupting requests to `github.com`?

**Comment by kunalgithub** [comment]
yes - i am behind proxy

**Comment by KenanY** [comment]
@kunalgithub Be sure to configure `npm` to use your proxy then. Here are the relevant configuration variables:

  - [`proxy`](https://docs.npmjs.com/misc/config#proxy)
  - [`https-proxy`](https://docs.npmjs.com/misc/config#https-proxy)
  - [`cafile`](https://docs.npmjs.com/misc/config#cafile)

I think you might have to configure `git` to use the proxy as well.

**Comment by kunalgithub** [comment]
these all are configured properly .. fine and dandy except  --  cafile ? -  
GIT config 
http.sslcainfo=C:/program files/git/mingw64/ssl/certs/ca-bundle.crt

**Comment by othiym23** [comment]
Is the proxy configured for npm, or just for git?

**Comment by SauravDas90** [comment]
I am using it on my home computer with no proxy configured, what to do?

**Comment by KenanY** [comment]
@SauravDas90 Maybe you have a firewall?

**Comment by ubuntuvim** [comment]
What a strange question, I put my `/etc/hosts` in github.com commented out, no problem!!!!

**Comment by KenanY** [comment]
@kunalgithub Is this still an issue for you?

**Comment by KenanY** [comment]
Closing as abandoned.

**Comment by sabarivasagan** [comment]
i had this same error

**Comment by ducpt1012** [comment]
I had same this, my network not behind proxy.

**Comment by pawanline** [comment]
i have same error . please help me

**Comment by BhuvaneshwaranK** [comment]
I have same error. I configured proxy settings also. still it's coming for me.

**Comment by legodude17** [comment]
Try the solution that @ubuntuvim proposed.

**Comment by alvirtuoso** [comment]
Same problem here

**Comment by legodude17** [comment]
Did you try the solution @ubuntuvim mentioned?

**Comment by ssaguiar** [comment]
I was using iTerm and got the same error.
Switched to normal Terminal and it worked.

**Comment by LiYaHX** [comment]
@ubuntuvim Thank you, it works for me.

**Comment by ubuntuvim** [comment]
@LiYaHX You are welcome......

**Comment by meiryanne** [comment]
I use windows and i have same error. Someone help?

**Comment by legodude17** [comment]
Does the solution from @ubuntuvim work for you? What is `npm -v` and `node -v`?

**Comment by legodude17** [comment]
Does the solution from @ubuntuvim work for you? What is your `npm -v` and `node -v`?

**Comment by kunalgithub** [comment]
I am back - This issue persists. Here is log 
npm -v ==> 3.3.8 
node -v ==> 6.11.3
BEHIND PROXY - PROXY is set in NPMRC and GIT 
-------------LOGS
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
npm info resetRemote resetting C:\Users\ME\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-joshuafcole-async-node-events-git-d32411f1f4-c1010c71660940b2a2eaab4c0f326afb for git+https
//github.com/joshuafcole/async-node-events.git#d32411f1f4
npm verb gentlyRm don't care about contents; nuking C:\Users\ME\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-joshuafcole-async-node-events-git-d32411f1f4-c1010c71660940b2a2eaab4c0
326afb
npm info git [ 'clone',
npm info git   '--template=C:\\Users\\ME\\AppData\\Roaming\\npm-cache\\_git-remotes\\_templates',
npm info git   '--mirror',
npm info git   'https://github.com/joshuafcole/async-node-events.git',
npm info git   'C:\\Users\\ME\\AppData\\Roaming\\npm-cache\\_git-remotes\\git-https-github-com-joshuafcole-async-node-events-git-d32411f1f4-c1010c71660940b2a2eaab4c0f326afb' ]
npm ERR! git clone --template=C:\Users\ME\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/joshuafcole/async-node-events.git C:\Users\ME\AppData\Roaming\npm-cac
e\_git-remotes\git-https-github-com-joshuafcole-async-node-events-git-d32411f1f4-c1010c71660940b2a2eaab4c0f326afb: Cloning into bare repository 'C:\Users\ME\AppData\Roaming\npm-cache\_git-remote
\git-https-github-com-joshuafcole-async-node-events-git-d32411f1f4-c1010c71660940b2a2eaab4c0f326afb'...
npm ERR! git clone --template=C:\Users\ME\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/joshuafcole/async-node-events.git C:\Users\ME\AppData\Roaming\npm-cac
e\_git-remotes\git-https-github-com-joshuafcole-async-node-events-git-d32411f1f4-c1010c71660940b2a2eaab4c0f326afb: fatal: unable to access 'https://github.com/joshuafcole/async-node-events.git/': Fai
ed to connect to github.com port 443: Connection refused
npm verb stack Error: Command failed: git -c core.longpaths=true clone --template=C:\Users\ME\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/joshuafcole/async-node
events.git C:\Users\ME\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-joshuafcole-async-node-events-git-d32411f1f4-c1010c71660940b2a2eaab4c0f326afb
npm verb stack Cloning into bare repository 'C:\Users\ME\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-joshuafcole-async-node-events-git-d32411f1f4-c1010c71660940b2a2eaab4c0f326afb
...
npm verb stack fatal: unable to access 'https://github.com/joshuafcole/async-node-events.git/': Failed to connect to github.com port 443: Connection refused
npm verb stack
npm verb stack     at ChildProcess.exithandler (child_process.js:198:12)
npm verb stack     at emitTwo (events.js:106:13)
npm verb stack     at ChildProcess.emit (events.js:191:7)
npm verb stack     at maybeClose (internal/child_process.js:920:16)
npm verb stack     at Socket.<anonymous> (internal/child_process.js:351:11)
npm verb stack     at emitOne (events.js:96:13)
npm verb stack     at Socket.emit (events.js:188:7)
npm verb stack     at Pipe._handle.close [as _onclose] (net.js:497:12)
npm verb cwd C:\Bla\app
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\ME\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "--verbose" "install"
npm ERR! node v6.11.3
npm ERR! npm  v3.3.8
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\ME\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/joshuafcole/async-node-events.git C
\Users\ME\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-joshuafcole-async-node-events-git-d32411f1f4-c1010c71660940b2a2eaab4c0f326afb
npm ERR! Cloning into bare repository 'C:\Users\ME\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-joshuafcole-async-node-events-git-d32411f1f4-c1010c71660940b2a2eaab4c0f326afb'...
npm ERR! fatal: unable to access 'https://github.com/joshuafcole/async-node-events.git/': Failed to connect to github.com port 443: Connection refused
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm verb exit [ 1, true ]

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Bla\app\npm-debug.log

**Comment by prashant569** [comment]
failed to connect to github
unknown host: api.github.com?? this error is coming in my android studio

**Comment by prashant569** [comment]
how to resolve??

**Comment by ZhengHei** [comment]
Same problem here

**Comment by Thrianadh** [comment]
Use a proxy to connect to the internet.
Use the Package **httr**
library("httr")
set_config(use_proxy("abcd.com",port = 8080, username = "*******", password="********"))
its worked for me

**Comment by finagep** [comment]
{"failed":"cURL error 7: Failed to connect to api.github.com port 443: Connection timed out"}


i have this problem in my WordPress website http://www.technicalstock.in how to remove this error

**Comment by colinrg** [comment]
I also get "Failed to connect to hithub.com port 443" when trying git clone command, after I updated to version git-gui verrsion 0.21.GITGUI, git version 2.16.2.windows.1, Tcl/Tk version 8.6.8.
Previously git-gui was showing error, hence the update, but now git command line is not working.
I've also disabled anti-virus and firewall and tried the same command with the same error, so it's not causing the problem.

Git-gui is working though for push, so something is working at least.

**Comment by eugkhp** [comment]
Well, i fixed that problem by using **vpn**. I guess my provider blocked some server that sdkman uses(i live in Russia).

**Comment by finagep** [comment]
The solution to this error 
{"failed":"cURL error 7: Failed to connect to api.github.com port 443: Connection timed out"} my website http://www.technicalstock.in I was a problem for most of the time 

![capture2](https://user-images.githubusercontent.com/29147633/42614481-c4b221ca-85c3-11e8-9280-b060728d333e.PNG)
![capture3](https://user-images.githubusercontent.com/29147633/42614482-c4e14306-85c3-11e8-93d9-c05fc80e0b0f.PNG)


This error showing for some security virus in our home directory ( Step 1) 

![capture](https://user-images.githubusercontent.com/29147633/42614351-25d185f0-85c3-11e8-96ea-2859bc2323f8.PNG)

1.  if you have Hostgator hosting account first scan virus for home directory and after scan repair those files  


![capture 7](https://user-images.githubusercontent.com/29147633/42615193-ab25e1bc-85c6-11e8-93cd-f5ac86b6e79b.PNG)
![capture 6](https://user-images.githubusercontent.com/29147633/42615203-b076b2f4-85c6-11e8-98ee-51193d613d3d.PNG)

2.  step go to Port 80 option  in Hostgator penal unblock port 


problam solve 


![capture 8](https://user-images.githubusercontent.com/29147633/42615946-f8bc3018-85c9-11e8-9d9d-9af78f576a4e.PNG)
