### ISSUE TITLE
error while using yo express to scaffold

### ISSUE THREAD

**Issue by kennybright** [npm/npm#10030]
```
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! shasum check failed for C:\Users\kenny\AppData\Local\Temp\npm-6376-be2708e7\registry.npmjs.org\caniuse-db\-\caniuse-db-1.0.30000347.tgz
npm ERR! Expected: 4cec7d85ac9d066dc536814ae02996ae1ae815fa
npm ERR! Actual:   42fe4f9ad754e00d291aeef7886f2e7304ced390
npm ERR! From:     https://registry.npmjs.org/caniuse-db/-/caniuse-db-1.0.30000347.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     c:\dev\stockDog\npm-debug.log
```

**Comment by KenanY** [comment]
@kennybright Have you tried running `npm cache clean`?

**Comment by kennybright** [comment]
Thanks  for getting back to me.I did run cache clean. Even with that i end up with the following:
Running "clean:server" (clean) task>> 0 paths cleaned.
Running "wiredep:app" (wiredep) task
Running "wiredep:test" (wiredep) task
Running "wiredep:sass" (wiredep) task
Running "concurrent:server" (concurrent) task    Warning:jit-grunt: Plugin for the "compass" task not found.If you have installed the plugin already, please setting the static mapping.See https://github.com/shootaroo/jit-grunt#static-mappings
Warning: Task "compass:server" failed. Use --force to continue.
Aborted due to warnings.
Date: Mon, 19 Oct 2015 08:01:06 -0700

**Comment by KenanY** [comment]
@kennybright That does not look like an error with `npm` to me. I recommend contacting the author of the module that is giving you trouble.

**Comment by kennybright** [comment]
thanks.

Date: Mon, 19 Oct 2015 11:03:04 -0700

**Comment by othiym23** [comment]
Closing as (the npm bits of this being) resolved. Thanks as always, @KenanY!
