### ISSUE TITLE
error when running npm install with grunt-mocha

### ISSUE THREAD

**Issue by andy663** [npm/npm#10040]
I'm having issues when running npm install on a linux build box. Can you please assist?

```
grunt-mocha@0.4.1 node_modules/grunt-mocha
├── mocha@1.12.1 (growl@1.7.0, commander@0.6.1, mkdirp@0.3.5, debug@2.2.0, diff@1.0.2, glob@3.2.1, jade@0.26.3)
└── grunt-lib-phantomjs@0.3.1 (eventemitter2@0.4.14, semver@1.0.14, temporary@0.0.8, phantomjs@1.9.18)
npm ERR! Error: Callback called more than once.
npm ERR!     at errorHandler (/usr/lib/node_modules/npm/lib/utils/error-handler.js:80:16)
npm ERR!     at save (/usr/lib/node_modules/npm/lib/install.js:329:12)
npm ERR!     at /usr/lib/node_modules/npm/lib/install.js:98:7
npm ERR!     at /usr/lib/node_modules/npm/lib/install.js:188:5
npm ERR!     at /usr/lib/node_modules/read-installed/read-installed.js:119:5
npm ERR!     at /usr/lib/node_modules/read-installed/read-installed.js:233:14
npm ERR!     at cb (/usr/lib/node_modules/slide/lib/async-map.js:48:11)
npm ERR!     at /usr/lib/node_modules/read-installed/read-installed.js:233:14
npm ERR!     at cb (/usr/lib/node_modules/slide/lib/async-map.js:48:11)
npm ERR!     at /usr/lib/node_modules/read-installed/read-installed.js:233:14
```

**Comment by KenanY** [comment]
@andy663 What version of `npm` and Node.js are you using (you can run `npm --version` and
`node --version` to check)? Is there any chance that you can upload the resulting `npm-debug.log` as a [gist](https://gist.github.com/)?

**Comment by KenanY** [comment]
@andy663 I don't know why I never responded to this earlier, but `npm@1.3` has not been supported for a long time now. Please try [updating](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm). Let me know if this solves your issue or if you are no longer having this issue.

**Comment by KenanY** [comment]
@andy663 Are you still seeing this issue with `npm@2` or `npm@3`?

**Comment by KenanY** [comment]
Closing as abandoned.
