### ISSUE TITLE
Error when adding user

### ISSUE THREAD

**Issue by brogers7** [npm/npm#10041]
0 info it worked if it ends with ok
1 verbose cli [ 'c:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'adduser' ]
2 info using npm@1.4.3
3 info using node@v0.10.26
4 verbose adduser before first PUT { name: 'brogers7',
4 verbose adduser   salt: 'XXXXX',
4 verbose adduser   password_sha: 'XXXXX',
4 verbose adduser   email: 'brogers7@gmail.com',
4 verbose adduser   _id: 'org.couchdb.user:brogers7',
4 verbose adduser   type: 'user',
4 verbose adduser   roles: [],
4 verbose adduser   date: '2015-10-20T16:33:58.894Z' }
5 verbose url raw /-/user/org.couchdb.user:brogers7
6 verbose url resolving [ 'http://npm-dev.uit.tla.uprr.com:5985/',
6 verbose url resolving   './-/user/org.couchdb.user:brogers7' ]
7 verbose url resolved http://npm-dev.uit.tla.uprr.com:5985/-/user/org.couchdb.user:brogers7
8 info trying registry request attempt 1 at 11:33:58
9 http PUT http://npm-dev.uit.tla.uprr.com:5985/-/user/org.couchdb.user:brogers7
10 http 401 http://npm-dev.uit.tla.uprr.com:5985/-/user/org.couchdb.user:brogers7
11 error TypeError: Cannot call method 'match' of undefined
11 error     at RegClient.<anonymous> (c:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:98:29)
11 error     at cb (c:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:124:9)
11 error     at RegClient.<anonymous> (c:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:217:14)
11 error     at Request.self.callback (c:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:123:22)
11 error     at Request.EventEmitter.emit (events.js:98:17)
11 error     at Request.<anonymous> (c:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:893:14)
11 error     at Request.EventEmitter.emit (events.js:117:20)
11 error     at IncomingMessage.<anonymous> (c:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:844:12)
11 error     at IncomingMessage.EventEmitter.emit (events.js:117:20)
11 error     at _stream_readable.js:920:16
12 error If you need help, you may report this *entire* log,
12 error including the npm and node versions, at:
12 error     <http://github.com/npm/npm/issues>
13 error System Windows_NT 6.1.7601
14 error command "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "adduser"
15 error cwd c:\Users\igen033\Eclipse_Projects\Directives\eams-navigation-bar
16 error node -v v0.10.26
17 error npm -v 1.4.3
18 error type non_object_property_call
19 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@brogers7 Please try [updating `npm`](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows) first.

**Comment by brogers7** [comment]
Thanks, I just figured out that the underlying issue is that my company has a group that does the publishing for us in a designated GitLab.
