### ISSUE TITLE
warn on invalid option names

### ISSUE THREAD

**Issue by othiym23** [npm/npm#10047]
It would be tremendously helpful to users if the CLI were to warn them when it was given an option that npm didn't know about.

**Comment by othiym23** [comment]
This would be very nice to have, and would be a great project for someone who wanted to make a self-contained improvement to npm that would help a bunch of people, but the CLI team isn't going to have time to get to it in the next year, and so I'm going to close it.

**Comment by legodude17** [comment]
This looks like this would actually be a change to `nopt`, not `npm`. Is there an issue on that repo?
