### ISSUE TITLE
ECONNRESET on install

### ISSUE THREAD

**Issue by omkadiri** [npm/npm#10042]
<img width="223" alt="git" src="https://cloud.githubusercontent.com/assets/10691627/10614922/8332e6e2-7722-11e5-8a59-4b93137e844e.png">

Am getting this error every time i try to install a module. any help on this?

**Comment by KenanY** [comment]
@omkadiri Looks like an issue with your internet connection. Are you behind a proxy or firewall by any chance?

**Comment by omkadiri** [comment]
have always install from this network, maybe they setup a firewall since it my company`s network. i will try again when i get home

**Comment by gyandeeps** [comment]
Facing same issue: https://github.com/npm/npm/issues/8196#issuecomment-158268945

**Comment by gyandeeps** [comment]
Solution: changed npm registry link from `https` to `http`.

**Comment by super-coder** [comment]
changing npm registry link from https to http didn't work

**Comment by alundiak** [comment]
Solution, which helped me:

```
npm config set registry http://registry.npmjs.org/
```
