### ISSUE TITLE
--prefix option ignored in some cases

### ISSUE THREAD

**Issue by Densaugeo** [npm/npm#10048]
When I run `npm --prefix=http install font-awesome` from a hook in package.json or from a project's root directory, the prefix option is ignored and the package installed in /node_modules

When I change to the http subfolder and run `npm install font-awesome`, it is still installed in /node_modules

When I change to the http subfolder and run `npm --prefix=http install font-awesome`, it creates another subfolder and installs in /http/http/node_moduls

How do I install something into /http/node_modules, other than manually moving copying it there?

...And it looks like Fedora only has node 0.10/npm 1.3 in their repos. I'll try this with a newer version when I get a chance.

**Comment by othiym23** [comment]
I'm closing this for now. If you replicate this inconsistency with `npm@2.14.7` or `npm@3.3.8`, let me know, and we can reopen / further discuss this issue.

**Comment by Densaugeo** [comment]
Seems to work fine in 2.14.7. Guess I need to quit using the repos.
