### ISSUE TITLE
problem to install global pageres to windows 10

### ISSUE THREAD

**Issue by rtlp** [npm/npm#10065]
Hello everybody.
I can't install npm, i have always a code error.

Microsoft Windows [version 10.0.10240](c) 2015 Microsoft Corporation. Tous droits réservés.

C:\Users\x>npm install --global pageres-cli
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "--global" "pageres-cli"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code SELF_SIGNED_CERT_IN_CHAIN

npm ERR! self signed certificate in certificate chain
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\x\npm-debug.log

C:\Users\blast>npm install --global pageres-cli
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "--global" "pageres-cli"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code SELF_SIGNED_CERT_IN_CHAIN

npm ERR! self signed certificate in certificate chain
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\x\npm-debug.log

---

0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli   'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--global',
1 verbose cli   'pageres-cli' ]
2 info using npm@2.14.7
3 info using node@v4.2.1
4 verbose install initial load of C:\Users\x\AppData\Roaming\npm\package.json
5 verbose readDependencies loading dependencies from C:\Users\x\AppData\Roaming\npm\package.json
6 silly cache add args [ 'pageres-cli', null ]
7 verbose cache add spec pageres-cli
8 silly cache add parsed spec Result {
8 silly cache add   raw: 'pageres-cli',
8 silly cache add   scope: null,
8 silly cache add   name: 'pageres-cli',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '_',
8 silly cache add   type: 'range' }
9 silly addNamed pageres-cli@_
10 verbose addNamed "_" is a valid semver range for pageres-cli
11 silly addNameRange { name: 'pageres-cli', range: '_', hasData: false }
12 silly mapToRegistry name pageres-cli
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/pageres-cli
16 verbose addNameRange registry:https://registry.npmjs.org/pageres-cli not in flight; fetching
17 verbose request uri https://registry.npmjs.org/pageres-cli
18 verbose request no auth needed
19 info attempt registry request try #1 at 23:11:56
20 verbose request id f01c6091926b298f
21 http request GET https://registry.npmjs.org/pageres-cli
22 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
23 info attempt registry request try #2 at 23:12:06
24 http request GET https://registry.npmjs.org/pageres-cli
25 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
26 info attempt registry request try #3 at 23:13:06
27 http request GET https://registry.npmjs.org/pageres-cli
28 verbose stack Error: self signed certificate in certificate chain
28 verbose stack     at Error (native)
28 verbose stack     at TLSSocket.<anonymous> (_tls_wrap.js:1000:38)
28 verbose stack     at emitNone (events.js:67:13)
28 verbose stack     at TLSSocket.emit (events.js:166:7)
28 verbose stack     at TLSSocket._finishInit (_tls_wrap.js:567:8)
29 verbose cwd C:\Users\blast
30 error Windows_NT 10.0.10240
31 error argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "--global" "pageres-cli"
32 error node v4.2.1
33 error npm  v2.14.7
34 error code SELF_SIGNED_CERT_IN_CHAIN
35 error self signed certificate in certificate chain
36 error If you need help, you may report this error at:
36 error     https://github.com/npm/npm/issues
37 verbose exit [ 1, true ]

Thank you by advance for you help.
Good day.

**Comment by smartmouse** [comment]
hi Have you looked at this link yet? Not sure if it is applicable to you.
http://blog.npmjs.org/post/78165272245/more-help-with-selfsignedcertinchain-and-npm

**Comment by rohitahireweb** [comment]
**How To Resolved following issue Same above issue  :-**

E:\DEVELOPER_SERVER\htdocs\PROJECTS\Survelytics> npm install gulp
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "gulp"
npm ERR! node v4.6.0
npm ERR! npm v2.15.9
npm ERR! code SELF_SIGNED_CERT_IN_CHAIN

npm ERR! self signed certificate in certificate chain
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR! https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR! E:\DEVELOPER_SERVER\htdocs\PROJECTS\Survelytics\npm-debug.log

**Comment by ayachama** [comment]
I was on Node 4.x.x version and npm 2.1.x version, I resolved it by upgrading to node v6.9.1 and npm 3.10.9.
I tried to do from CMD, it didn't fix the issue. 
Download and upgrade to latest node and npm by downloading [prebuilt-installer](https://nodejs.org/en/download/).

**Comment by legodude17** [comment]
Does @ayachama's solution work for you @rtlp and @rohitahireweb?

**Comment by rohitahireweb** [comment]
Hello ayachama,

I have already upgrading Node v6.9.1 and npm 3.10.9. but not working same error show me.


Thanks

**Comment by legodude17** [comment]
You could try `npm cache clean` if you haven't already @rohitahireweb.

**Comment by legodude17** [comment]
Also try `npm config set ca=""`.

**Comment by rohitahireweb** [comment]
**No working... :(** 

please I request you share me screen shot setup by setup how to resolved...
![screen](https://cloud.githubusercontent.com/assets/22934037/20067968/0d52891a-a53d-11e6-95b2-8daa709b737c.jpg)

**Comment by KenanY** [comment]
@rohitahireweb You cannot run `npm start` without having a `package.json` in your current directory which defines a `"start"` script. As it stands, `npm` has no idea what you want it to do. You can create a `package.json` with `npm init`, and then check out <https://docs.npmjs.com/misc/scripts> for how to create npm scripts.

(Also, the log indicates that you are using Node.js v4 and `npm@2`, which are not the versions you said you have...)

**Comment by rohitahireweb** [comment]
Hello Friends,

**I have find simplify solution for install npm issue** 

**first download :** Git-2.10.2-64-bit
https://git-scm.com/downloads 

**after install open GIT CMD then start following setups**

C:\Users>git config --global user.name "Your User Name"

C:\Users>git config --global user.email "YOUR EMAIL ADDRESS"

C:\Users>D:

D:\>cd an*

D:\angular-projects>git clone https://github.com/start-angular/SB-Admin-BS4-Angular-2.git

D:\angular-projects>cd MyApp

D:\angular-projects>MyApp>npm install

D:\angular-projects>MyApp>npm start

**Done!**

![11](https://cloud.githubusercontent.com/assets/22934037/20177717/2a994818-a774-11e6-8741-52d694af5f45.jpg)


Thanks
Rohit Ahire

Select thumbs up if this reply helps you!
