### ISSUE TITLE
npm install <tarball url> and basic auth

### ISSUE THREAD

**Issue by vbogdanov** [npm/npm#10060]
I'm trying to download a tarball from a location that has basic auth. I don't want to keep user and pass for the site in package.json `"my-dependency": "https://user:pass@host/path/to/tarball"`. Is there a way (using .npmrc) to configure user and pass to use in this case.

**Comment by sommestad** [comment]
Having the same issue. It has worked up until recently; it seems like Github has changed how it works on their end.

**Comment by sommestad** [comment]
I [found a solution at SO](http://stackoverflow.com/a/13353408/572693 ) (where else) that works for me!

```json
"dependencies" : {
    "my-module" : "git+https://<token>:x-oauth-basic@github.com/my_github_account/my_repo.git"
}
```

**Comment by pcssi** [comment]
@sommestad, does the solution [you mentioned](https://github.com/npm/npm/issues/10060#issuecomment-152283496) still work for you?

I am running into an issue where it does not honor the _git+https://<token>:x-oauth-basic/..._ and always tries _ssh://git@github.com/..._
