### ISSUE TITLE
documentation references topics without linking

### ISSUE THREAD

**Issue by spikegrobstein** [npm/npm#10067]
Consistently in the docs.npmjs.com site, the documentation references another page or topic without actually linking to it. In some cases, this is referencing something that is immediately visible in the sidebar, while other times it appears as though there is no page that it's referencing.

This is especially frustrating when it suggests looking at `npm-config (1)` vs `npm-config (7)`, with no explanation as to what the difference between either of those links are.

Some example pages that have this problem are the "see also" sections (at the bottom) of:

 * https://docs.npmjs.com/cli/config
 * https://docs.npmjs.com/cli/tag

**Comment by ehsalazar** [comment]
@spikegrobstein Thanks for creating the issue. Would you mind closing this one and resubmit it in the [docs issues tracker](https://github.com/npm/docs/issues)?

**Comment by KenanY** [comment]
https://github.com/npm/docs/issues/106?

**Comment by ehsalazar** [comment]
Thanks @KenanY. Closing as dup.
