### ISSUE TITLE
many npm options are not listed anywhere in documentation

### ISSUE THREAD

**Issue by spikegrobstein** [npm/npm#10069]
Many times, in the documentation for the NPM actions, an exhaustive list of available options are not shown. I've had trouble finding documentation on options that I *know* exist as well as have had trouble finding out whether options that *should* exist are real or actually do what I expect.

The best example is the `install` page (https://docs.npmjs.com/cli/install) doesn't list the `--deployment` flag anywhere, and only passively mentions `--production` down the page, hidden in a paragraph.

It would be really great if there was a table of the available options and what they do in one place.

**Comment by KenanY** [comment]
@spikegrobstein Is `--deployment` even a thing? Aren't all flags already documented over at https://docs.npmjs.com/misc/config?

**Comment by spikegrobstein** [comment]
It was used all over the place in build scripts at my last job and the guy who set it up told me that it was an undocumented feature. At the time --production and --save, etc were not documented either, so I believed him. Maybe it's not a thing and he totally lied to me?

anyway, I"m moving this stuff over to the docs repo, if you want to continue the convo there.
