### ISSUE TITLE
documentation does not list aliased commands in sidebar

### ISSUE THREAD

**Issue by spikegrobstein** [npm/npm#10068]
frequently I see examples online or people using actions that are unfamiliar to me, and when I go to the npm docs site, I am unable to find them because the are actually aliases of existing commands.

For example, `ln` which is really `link` or `login` which is really `adduser`. This can get very frustrating when I'm trying to troubleshoot priority-zero bugs and trying to figure out what the engineer is trying to accomplish with their command, when they frequently don't even know that these commands are aliases.

I propose doing wiki-style linking, where the aliases are still shown in the sidebar, but just load up the page to the canonical command. for example, clicking on the `ln` link just takes you to the `link` page.

**Comment by ehsalazar** [comment]
@spikegrobstein Thanks again! Would you mind closing this one and resubmit it in the [docs issues tracker](https://github.com/npm/docs/issues)?

**Comment by spikegrobstein** [comment]
gah. sorry.

**Comment by ehsalazar** [comment]
@spikegrobstein thanks! : )

**Comment by spikegrobstein** [comment]
it's been a really long day. you have no idea.
