### ISSUE TITLE
npm documentation is not versioned

### ISSUE THREAD

**Issue by spikegrobstein** [npm/npm#10070]
Because of incompatibilities with npm 3.x, my organization is still using releases from the 2.x series. The documentation online doesn't differentiate between versions and only shows the latest version. Because the online help (via the commandline) is so difficult to use, it's impossible to figure out whether the options/actions/configuration is compatible with our current version or if it's a new feature.

If there could be documentation on the website for each version, and if it were easy to switch between versions (either via a popup menu, a list (like postgresql's docs) or just changing the URL) that would be dope.

**Comment by ehsalazar** [comment]
@spikegrobstein This is a good idea and something we'd like to explore. Would you mind closing this one and resubmit it in the [docs issues tracker](https://github.com/npm/docs/issues)?
