### ISSUE TITLE
npm online documentation is incomplete for npmrc file format

### ISSUE THREAD

**Issue by spikegrobstein** [npm/npm#10071]
the documentation for the `.npmrc` file format is incomplete in several ways.
1. It doesn't define what character(s) to use for commenting out a line
2. it doesn't describe special, per-registry configuration options.

Solving 1 seems pretty easy, so no need to describe.

Number 2, above, needs an explanation. I currently have several npm registries configured, each with different authentication requirements (some with `always-auth` to true, others with a different username, for example). It _appears_ that there is a way to do something like the following, but I haven't been able to find any documentation around it, nor am I even sure that this is working as expected, since it's pretty difficult to test and the `--verbose` flag doesn't report enough information...

```
registry=myregistry.example.com
always-auth=true
//some-other-npm.example.com:always-auth=false
```

where the `//` line is defining a config for the registry with that particular hostname. I've seen this format in my local `~/.npmrc` but I have no idea where it came from. Is this even valid? Initially I thought it was commented out lines with a description of what config it came from, but after removing the lines and watching something break, I think it just means any protocol (ie: `http` or `https`).

**Comment by spikegrobstein** [comment]
moved to npm/docs

**Comment by rob3c** [comment]
Specifically, here's the issue at npm/docs: https://github.com/npm/docs/issues/392

**Comment by ashleygwilliams** [comment]
this should be here, not in the docs repo, as the `.npmrc` doc lives here.
