### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by YugendraBharat** [npm/npm#10077]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'help',
1 verbose cli   'config' ]
2 info using npm@2.14.7
3 info using node@v4.2.1
4 verbose config Skipping project config: USER/.npmrc. (matches userconfig)
5 verbose stack Error: spawn cmd ENOENT
5 verbose stack     at exports._errnoException (util.js:874:11)
5 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
5 verbose stack     at onErrorNT (internal/child_process.js:344:16)
5 verbose stack     at doNTCallback2 (node.js:439:9)
5 verbose stack     at process._tickCallback (node.js:353:17)
6 verbose cwd C:\Users\User
7 error Windows_NT 6.1.7601
8 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "help" "config"
9 error node v4.2.1
10 error npm  v2.14.7
11 error path cmd
12 error code ENOENT
13 error errno ENOENT
14 error syscall spawn cmd
15 error enoent spawn cmd ENOENT
15 error enoent This is most likely not a problem with npm itself
15 error enoent and is related to npm not being able to find a file.
16 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@YugendraBharat Are you still facing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
