### ISSUE TITLE
npm@3.3.8 fails due to missing spdx module

### ISSUE THREAD

**Issue by ThisIsMissEm** [npm/npm#10078]
I get this after updating to npm@3.3.8, I'm on node.js v0.12.7 (haven't been able to update to v4 yet)

```
$ npm show npm
Error: Cannot find module 'spdx'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/validate-npm-package-license/index.js:1:74)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "show" "npm"
npm ERR! node v0.12.7
npm ERR! npm  v3.1.2
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'spdx'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

**Comment by aredridel** [comment]
Aw geez. Your install didn't complete successfully and left you with a missing module in the tree, possibly.

But it looks like you're running 3.1.2, not 3.3.8 there. Did it install somewhere else?

**Comment by miksago** [comment]
odd.. no, I don't think so. And it didn't actually error, looked like everything went fine.

I have recently had some severe oddness with NPM occasionally acting like it has installed everything, and then when I start my code, it's like "can't find anything", I look in node_modules, and the files exist, but are empty.

**Comment by miksago** [comment]
Haven't been able to reliably reproduce though.

**Comment by aredridel** [comment]
Oof! That's no good! 

Out of curiosity, what OS and filesystem are you on?

**Comment by miksago** [comment]
OS X 10.9.5; SSD with Encrypted Logical Partition

**Comment by miksago** [comment]
Reinstalling node.js @ 0.12.7 and then upgrading npm to 3.3.8 worked, will try to update if I have further issues.

**Comment by aredridel** [comment]
Awesome. I both hope we do and don't hear from you :)

**Comment by ibasoni** [comment]
Had the same problem (on osx).
node.js @6.2.1
npm @3.9.3
`sudo npm install -g npm` fixed it.
thanks!

**Comment by chenfengyanyu** [comment]
I've had the same problem.Tried a lot of programs.But i think the most effective solution is try to install node again.
As a matter of fact, I succeeded.
