### ISSUE TITLE
Please reply soon npm-debug.log

### ISSUE THREAD

**Issue by tarandeepsingh009** [npm/npm#10075]
![screenshot 109](https://cloud.githubusercontent.com/assets/13820265/10658237/83ddc986-78b2-11e5-80c8-51fe888c362f.png)

**Comment by tarandeepsingh009** [comment]
Whenever i try to install cordova 
it shows this error

**Comment by KenanY** [comment]
@tarandeepsingh009 Are you behind a proxy or firewall?

**Comment by tarandeepsingh009** [comment]
No Sir

**Comment by KenanY** [comment]
@tarandeepsingh009 Sorry I never responded with a solution. Are you still facing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
