### ISSUE TITLE
UX: error when a dependency is both in dependencies and devDependencies

### ISSUE THREAD

**Issue by jonathanong** [npm/npm#10081]
i frequently mistype `--save` vs. `--save-dev` and end up with a dep in both places. whenever `npm` accesses `package.json`, can it show an warning that there are duplicates? if you point me to where this would happen, i can make a PR

**Comment by othiym23** [comment]
This warning already exists on `npm install`. Do you want it to show up more frequently?

**Comment by jonathanong** [comment]
@othiym23 oh i guess so. i think the problem with `npm install` is that i see 10000 lines of text displayed, so i never actually notice it.

np then!
