### ISSUE TITLE
Invalid Protocol

### ISSUE THREAD

**Issue by venkatgirit** [npm/npm#10088]
Hi,
I installed node.js without any issues on my laptop. and then i tried to install a module using 'npm' - then i get the following error message.

C:\mongodb\week_1_introduction.3bdb40b3af70\introduction_to_npm\intro_to_npm\intro_to_npm>npm config set proxy localhost:8080

C:\mongodb\week_1_introduction.3bdb40b3af70\introduction_to_npm\intro_to_npm\intro_to_npm>npm config set registry http://registry.npmjs.org

C:\mongodb\week_1_introduction.3bdb40b3af70\introduction_to_npm\intro_to_npm\intro_to_npm>npm install express
npm WARN package.json intro_to_npm@0.0.0 No repository field.
npm WARN package.json intro_to_npm@0.0.0 No README data
npm WARN package.json intro_to_npm@0.0.0 license should be a valid SPDX license expression
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "express"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7

npm ERR! Invalid protocol: localhost:
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     C:\mongodb\week_1_introduction.3bdb40b3af70\introduction_to_npm\intro_to_npm\intro_to_npm\npm-debug.log

C:\mongodb\week_1_introduction.3bdb40b3af70\introduction_to_npm\intro_to_npm\intro_to_npm>

npm-debug.log:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli   'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'express' ]
2 info using npm@2.14.7
3 info using node@v4.2.1
4 verbose install initial load of C:\mongodb\week_1_introduction.3bdb40b3af70\introduction_to_npm\intro_to_npm\intro_to_npm\package.json
5 warn package.json intro_to_npm@0.0.0 No repository field.
6 warn package.json intro_to_npm@0.0.0 No README data
7 warn package.json intro_to_npm@0.0.0 license should be a valid SPDX license expression
8 verbose readDependencies loading dependencies from C:\mongodb\week_1_introduction.3bdb40b3af70\introduction_to_npm\intro_to_npm\intro_to_npm\package.json
9 silly cache add args [ 'express@3.x', null ]
10 verbose cache add spec express@3.x
11 silly cache add parsed spec Result {
11 silly cache add   raw: 'express@3.x',
11 silly cache add   scope: null,
11 silly cache add   name: 'express',
11 silly cache add   rawSpec: '3.x',
11 silly cache add   spec: '>=3.0.0 <4.0.0',
11 silly cache add   type: 'range' }
12 silly addNamed express@>=3.0.0 <4.0.0
13 verbose addNamed ">=3.0.0 <4.0.0" is a valid semver range for express
14 silly addNameRange { name: 'express', range: '>=3.0.0 <4.0.0', hasData: false }
15 silly mapToRegistry name express
16 silly mapToRegistry using default registry
17 silly mapToRegistry registry http://registry.npmjs.org/
18 silly mapToRegistry uri http://registry.npmjs.org/express
19 verbose addNameRange registry:http://registry.npmjs.org/express not in flight; fetching
20 verbose request uri http://registry.npmjs.org/express
21 verbose request no auth needed
22 info attempt registry request try #1 at 2:53:33 AM
23 verbose request id 78ee10ad9f59acbd
24 http request GET http://registry.npmjs.org/express
25 info retry will retry, error on last attempt: Error: Invalid protocol: localhost:
26 info attempt registry request try #2 at 2:53:43 AM
27 http request GET http://registry.npmjs.org/express
28 info retry will retry, error on last attempt: Error: Invalid protocol: localhost:
29 info attempt registry request try #3 at 2:54:43 AM
30 http request GET http://registry.npmjs.org/express
31 verbose stack Error: Invalid protocol: localhost:
31 verbose stack     at Request.init (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:461:31)
31 verbose stack     at new Request (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:140:8)
31 verbose stack     at request (C:\Program Files\nodejs\node_modules\npm\node_modules\request\index.js:55:10)
31 verbose stack     at CachingRegistryClient.makeRequest (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:149:13)
31 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:66:17
31 verbose stack     at RetryOperation._fn (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\attempt.js:18:5)
31 verbose stack     at null._onTimeout (C:\Program Files\nodejs\node_modules\npm\node_modules\retry\lib\retry_operation.js:49:10)
31 verbose stack     at Timer.listOnTimeout (timers.js:92:15)
32 verbose cwd C:\mongodb\week_1_introduction.3bdb40b3af70\introduction_to_npm\intro_to_npm\intro_to_npm
33 error Windows_NT 6.3.9600
34 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "express"
35 error node v4.2.1
36 error npm  v2.14.7
37 error Invalid protocol: localhost:
38 error If you need help, you may report this error at:
38 error     <https://github.com/npm/npm/issues>
39 verbose exit [ 1, true ]

**Comment by LupDre** [comment]
Hi there! 

It looks like you are trying to install MongoDB; is that correct? Have you had any success installing any other modules using npm?
