### ISSUE TITLE
can't publish non-scoped package

### ISSUE THREAD

**Issue by Sanske** [npm/npm#10089]
can't publish non-scoped package

**Comment by KenanY** [comment]
@Sanske Not enough information provided. Is there a `npm-debug.log` file that you can upload to [gist.github.com](https://gist.github.com/)?

**Comment by aredridel** [comment]
Are you using cnpmjs?

**Comment by KenanY** [comment]
@Sanske It has been several months now without a reply from you... are you still experiencing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
