### ISSUE TITLE
npm silently skipping git project

### ISSUE THREAD

**Issue by cdhouk** [npm/npm#10096]
When I updated npm from 2.14.x to 3.3.9 a dependency stopped installing. The project url is
git@github.com:mpelikan/postal-standardization.git
while the package name is postal.standardization

Updating the package name to postal-standardization allows the package to install.

**Comment by KenanY** [comment]
@cdhouk Could you provide example steps to reproduce this issue? Maybe the `dependencies`/`devDependencies` portion of your `package.json`?

I cannot reproduce with this:

``` json
{
  "dependencies": {
    "postal.standardization": "mpelikan/postal-standardization"
  }
}
```

``` sh
$ npm --version
3.3.10
$ npm install
$ npm ls
/home/kenan/Code/npm-10096
└── postal.standardization@0.1.0 (git://github.com/mpelikan/postal-standardization.git#d65b11a0660420cfc600dd1174731d84ad44dc94)
```

**Comment by cdhouk** [comment]
I have a sample project at
git@github.com:cdhouk/sample.git

The dependency is added to ~/.npm but not added to node_modules.  The
dependencies for postal.standardization are also not added.



[image: Path2Response Logo] <http://www.path2response.com>*Carroll Houk*
*Software Developer*
chouk@path2response.com
mobile: 720-217-9372*Path2Response LLC*
1805 Hwy 42, 2nd Floor
Louisville, CO 80027
office: 303-927-7733www.path2response.com

**Comment by KenanY** [comment]
@cdhouk Hmm, in your original post you say it silently fails with the period but succeeds with the hyphen. For me it is the opposite. Since the module name has a period in it, you should use the period like so:

``` json
{
  "dependencies": {
    "postal.standardization": "git@github.com:mpelikan/postal-standardization.git"
  },
}
```

I guess `npm` _should_ print some kind of warning when this happens.

> dependencies for postal.standardization are also not added

`postal.standardization` has no dependencies defined.

**Comment by cdhouk** [comment]
You are of course correct. Sorry I misunderstood the root issue.

When I was using an earlier version of npm 2.14.7 the dependency
postal.standardization would be copied into node_modules even though the
name of the dependency was incorrect in package.json.

When a team member using a newer version of npm 3.3.6 ran "npm install"
they did not see a message that there was a problem. They were then
confused when the code requiring the correctly named dependency failed for
them.

Sorry I was looking at devDependencies and not dependencies and misstated
that they were missing.

[image: Path2Response Logo] <http://www.path2response.com>*Carroll Houk*
*Software Developer*
chouk@path2response.com
mobile: 720-217-9372*Path2Response LLC*
1805 Hwy 42, 2nd Floor
Louisville, CO 80027
office: 303-927-7733www.path2response.com
