### ISSUE TITLE
Provider packages.

### ISSUE THREAD

**Issue by trusktr** [npm/npm#10099]
Arch Linux' package manager has the concept of provider packages. For example, suppose package A depends on B. Another package C can "provide" B, which means that if I install C, pacman will ask to first remove B in order to replace it with C, and the dependency of B for A will still be satisfied.

I think it'd be nice to have this in the NPM ecosystem. It'd make it really really easy to write libraries where users can specify certain components that satisfy certain requirements for a library.

For example, suppose a user installs a library called "engine", and that library depends on a library called "engine-webglrenderer", but the "engine-webglrenderer" is a replaceable piece of the library. Now suppose that a third package called "engine-threejsrenderer" is released by someone, and that it exposes the same class needed by "engine". A user could `npm install engine-threejsrenderer` and NPM would ask if the user wants to replace `engine-webglrenderer` with `engine-threejsrenderer`.

That would be nice!

**Comment by othiym23** [comment]
If you rummage around in the really old npm issues, you'll see that this has been proposed in the past. It is useful for distribution-level package managers, but it brings with it a host of really complicated edge cases (who determines the API? In a system where anybody can publish, how do you safely version and track an API that a package provides?) and also interacts very badly with semver. It's a powerful concept, but not one that's compatible with npm's design or philosophy, so it's something I'd like to see npm steer clear of. Thanks for suggesting the idea, though!

**Comment by trusktr** [comment]
For sure. I'm just wondering what's the best way to let users specify
alternative implementations of something without it happening at run time
(because in that case all the options must be available at runtime, which
is bad for performance due to having a large bundle, etc). I was thinking
maybe i can give the user some type of build options (provider packages
being one such possibility).

For example, what we (those of us working on infamous.io) might like is for
the user to be able to specify alternate renderers for the engine we're
making, the default is our Engine, but with Three.js and Babylon.js
alternatives, etc.

Any ideas?

/#!/JoePea

**Comment by othiym23** [comment]
The tricky thing is that JavaScript is dynamic, and npm doesn't define APIs, just dependencies between packages.

I can't speak to pacman, but I know that the `Provides:` functionality of Debian's APT requires careful and ongoing negotiation between package managers working in a given ecosystem to prevent breaking things. Doing that in an environment as loose and fast-moving as the npm community seems really hard.

This might sound completely off the wall to you, but have you looked at TypeScript? Part of its appeal is that it allows you to define formal interfaces between components, and I know that it has a package manager that helps deal with those interfaces. I think it might offer tools that would be very useful for what you're trying to do.

**Comment by trusktr** [comment]
> npm doesn't define APIs

But JavaScript authors can define them. I understand that if there are packages meant to be replacements for other packages, that they will obviously not work if they don't satisfy APIs. I see what you mean about semver though. How would we version something alternate? Meteor has an addition to semver using underscores, so f.e. `foo_for_meteor@1.2.3_4` can be used to represent package `foo_for_meter` that packages some library `foo` for Meteor that is compatible with `foo@1.2.3` (from NPM for example).

> have you looked at TypeScript

I have, but I much prefer plain JavaScript. The APIs in my library will be well documented, so provider packages would work in that regard (the documentation will make it clear which APIs need to be implemented). The only real problem I see (IMHO) is versioning.

Maybe I can set something up [like this](https://gemfury.com/help/npm-registry#npm-proxy) so users can choose alternate hybrid registries for alternative packages, where the alternative packages are named the same, but contain different things? Maybe that in combination with scoped packages?

Anyways, thanks for the input. :)
