### ISSUE TITLE
 shasum check failed

### ISSUE THREAD

**Issue by deveshigate** [npm/npm#10090]
Hi, 

While installing a node module using npm, getting below error. 

D:\Tutorials\karma>npm install basic-auth
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\node\\node.exe" "C:\\Program Files\\node\\node_modules\\npm\\bin\\npm-cli.js" "install" "basic-auth"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4

npm ERR! shasum check failed for C:\Users\dm825120\AppData\Local\Temp\npm-7768-805a27c5\registry.npmjs.org\basic-auth\-\basic-auth-1.0.3.tgz
npm ERR! Expected: 41f55523e589405038ee3567958c62a5ed70551a
npm ERR! Actual:   136ea8d7329fc2a80860c1ad487f94e2efc29f38
npm ERR! From:     http://registry.npmjs.org/basic-auth/-/basic-auth-1.0.3.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Tutorials\karma\npm-debug.log

I am unable to get what's the issue. Please help me.

**Comment by deveshigate** [comment]
npm set registry https://registry.npmjs.org/

worked for me :)

**Comment by ehsalazar** [comment]
@deveshigate It sounds like the issue resolved. Is that correct? I'll close this for now as we’re trying to clean up some solved issues. We’ll be happy to reopen if necessary.

**Comment by deveshigate** [comment]
Yes. Please close it.

---
Thanks & Regards,
Devesh Mishra
+91-8097032750

Sent from my Windows Phone

-----Original Message-----
