### ISSUE TITLE
get issue with Bean node

### ISSUE THREAD

**Issue by ATHZHANG** [npm/npm#10108]
I can trying to install light blue bean node into node-red, then i get these

npm WARN locking Error: EACCES, open '/Users/zhangtianhan/.npm/_locks/node-red-contrib-bean-33e4086ab5e97ff8.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/zhangtianhan/.npm/_locks/node-red-contrib-bean-33e4086ab5e97ff8.lock failed { [Error: EACCES, open '/Users/zhangtianhan/.npm/_locks/node-red-contrib-bean-33e4086ab5e97ff8.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/zhangtianhan/.npm/_locks/node-red-contrib-bean-33e4086ab5e97ff8.lock' }
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "--prefix" "/Users/zhangtianhan/.node-red" "node-red-contrib-bean"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! Attempt to unlock /Users/zhangtianhan/.node-red/node_modules/node-red-contrib-bean, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/zhangtianhan/npm-debug.log
 

anyone can help?  thank you so much!!! kind of urgent!

**Comment by KenanY** [comment]
@ATHZHANG Looks like you do not have permission to write to `npm`'s cache directory. Could you try running the following?:

``` sh
sudo chown -R $(whoami) "$HOME/.npm"
```

**Comment by ATHZHANG** [comment]
@KenanY  it asked for my password and said "-bash: az: command not found"

**Comment by KenanY** [comment]
@ATHZHANG I don't understand why `bash` thinks you ran the `az` command.

**Comment by ATHZHANG** [comment]
@KenanY cause it ask for my password after your command

**Comment by ATHZHANG** [comment]
@KenanY Last login: Sun Oct 25 23:25:34 on ttys000
zhangs-mbp:~ zhangtianhan$ sudo chown -R $(whoami) "$HOME/.npm"
Password:

zhangs-mbp:~ zhangtianhan$ 
zhangs-mbp:~ zhangtianhan$ sudo chown -R $(whoami) "$HOME/.npm"
zhangs-mbp:~ zhangtianhan$ 
zhangs-mbp:~ zhangtianhan$ sudo chown -R $(whoami) "$HOME/.npm"
zhangs-mbp:~ zhangtianhan$ 


this is what happened this morning

**Comment by KenanY** [comment]
@ATHZHANG So has your issue been resolved? It is expected that `chown` will not print anything to stdout.

**Comment by ATHZHANG** [comment]
@KenanY yes! thanks! can you tell me why it works?

**Comment by KenanY** [comment]
@ATHZHANG From the log I can see that your user does not have permission to modify `npm`'s cache directory (`~/.npm`). So, you can use `chown` to claim ownership of the directory and thus reclaim permission to modify it.

**Comment by othiym23** [comment]
Closing as resolved.
