### ISSUE TITLE
ionic installation problem

### ISSUE THREAD

**Issue by sumitrajora** [npm/npm#10106]
Hi, 
   I am facing problem while installing ionic through npm. 
"Uncaught, Unspecified "error" event".
node v0.12.2
npm v2.7.4
no npm-debug.log generated

Please help

**Comment by KenanY** [comment]
@sumitrajora 

> no npm-debug.log generated

That's very odd. Maybe trying piping the output to a file yourself?

You could also try [updating `npm`](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) to see if it helps at all.

**Comment by sumitrajora** [comment]
updating to npm@latest worked for me.. Thanks

**Comment by othiym23** [comment]
Closing as resolved.
