### ISSUE TITLE
npm install timeseries-analysis - undefined is not a function

### ISSUE THREAD

**Issue by maeishoj** [npm/npm#10104]
Trying to install timeseries-analysis, and fails. This is the log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'timeseries-analysis' ]
2 info using npm@2.14.4
3 info using node@v0.12.7
4 verbose install initial load of /Users/manuelmaestrini/Dropbox/Programming/My Software/package.json
5 verbose installManyTop reading scoped package data from /Users/manuelmaestrini/Dropbox/Programming/My Software/node_modules/async/package.json
6 verbose installManyTop reading scoped package data from /Users/manuelmaestrini/Dropbox/Programming/My Software/node_modules/bcrypt-nodejs/package.json
7 verbose installManyTop reading scoped package data from /Users/manuelmaestrini/Dropbox/Programming/My Software/node_modules/better-stack-traces/package.json
8 verbose installManyTop reading scoped package data from /Users/manuelmaestrini/Dropbox/Programming/My Software/node_modules/bin/package.json
9 verbose installManyTop reading scoped package data from /Users/manuelmaestrini/Dropbox/Programming/My Software/node_modules/bit-mask/package.json
10 verbose installManyTop reading scoped package data from /Users/manuelmaestrini/Dropbox/Programming/My Software/node_modules/body-parser/package.json
11 verbose installManyTop reading scoped package data from /Users/manuelmaestrini/Dropbox/Programming/My Software/node_modules/chance/package.json
12 verbose installManyTop reading scoped package data from /Users/manuelmaestrini/Dropbox/Programming/My Software/node_modules/colors/package.json
13 verbose installManyTop reading scoped package data from /Users/manuelmaestrini/Dropbox/Programming/My Software/node_modules/cookie-parser/package.json
14 verbose installManyTop reading scoped package data from /Users/manuelmaestrini/Dropbox/Programming/My Software/node_modules/deasync/package.json
15 verbose installManyTop reading scoped package data from /Users/manuelmaestrini/Dropbox/Programming/My Software/node_modules/debug/package.json
16 verbose installManyTop reading scoped package data from /Users/manuelmaestrini/Dropbox/Programming/My Software/node_modules/express/package.json
17 verbose installManyTop reading scoped package data from /Users/manuelmaestrini/Dropbox/Programming/My Software/node_modules/extend/package.json
18 verbose installManyTop reading scoped package data from /Users/manuelmaestrini/Dropbox/Programming/My Software/node_modules/faker-js/package.json
19 verbose installManyTop reading scoped package data from /Users/manuelmaestrini/Dropbox/Programming/My Software/node_modules/geolib/package.json
20 verbose installManyTop reading scoped package data from /Users/manuelmaestrini/Dropbox/Programming/My Software/node_modules/inherits/package.json
21 verbose installManyTop reading scoped package data from /Users/manuelmaestrini/Dropbox/Programming/My Software/node_modules/joi/package.json
22 verbose installManyTop reading scoped package data from /Users/manuelmaestrini/Dropbox/Programming/My Software/node_modules/json-query/package.json
23 verbose installManyTop reading scoped package data from /Users/manuelmaestrini/Dropbox/Programming/My Software/node_modules/mysql/package.json
24 verbose installManyTop reading scoped package data from /Users/manuelmaestrini/Dropbox/Programming/My Software/node_modules/node.extend/package.json
25 verbose installManyTop reading scoped package data from /Users/manuelmaestrini/Dropbox/Programming/My Software/node_modules/nodemailer/package.json
26 verbose installManyTop reading scoped package data from /Users/manuelmaestrini/Dropbox/Programming/My Software/node_modules/ns/package.json
27 verbose installManyTop reading scoped package data from /Users/manuelmaestrini/Dropbox/Programming/My Software/node_modules/optional/package.json
28 verbose installManyTop reading scoped package data from /Users/manuelmaestrini/Dropbox/Programming/My Software/node_modules/prettyjson/package.json
29 verbose installManyTop reading scoped package data from /Users/manuelmaestrini/Dropbox/Programming/My Software/node_modules/readline-sync/package.json
30 verbose installManyTop reading scoped package data from /Users/manuelmaestrini/Dropbox/Programming/My Software/node_modules/request/package.json
31 verbose installManyTop reading scoped package data from /Users/manuelmaestrini/Dropbox/Programming/My Software/node_modules/should/package.json
32 verbose installManyTop reading scoped package data from /Users/manuelmaestrini/Dropbox/Programming/My Software/node_modules/smtp-connection/package.json
33 verbose installManyTop reading scoped package data from /Users/manuelmaestrini/Dropbox/Programming/My Software/node_modules/sugar/package.json
34 verbose installManyTop reading scoped package data from /Users/manuelmaestrini/Dropbox/Programming/My Software/node_modules/supertest/package.json
35 verbose installManyTop reading scoped package data from /Users/manuelmaestrini/Dropbox/Programming/My Software/node_modules/swig/package.json
36 verbose installManyTop reading scoped package data from /Users/manuelmaestrini/Dropbox/Programming/My Software/node_modules/twilio/package.json
37 verbose installManyTop reading scoped package data from /Users/manuelmaestrini/Dropbox/Programming/My Software/node_modules/validator/package.json
38 info package.json ns@1.0.0 No repository field.
39 info package.json ns@1.0.0 No README data
40 verbose readDependencies loading dependencies from /Users/manuelmaestrini/Dropbox/Programming/My Software/package.json
41 silly cache add args [ 'timeseries-analysis', null ]
42 verbose cache add spec timeseries-analysis
43 silly cache add parsed spec { raw: 'timeseries-analysis',
43 silly cache add   scope: null,
43 silly cache add   name: 'timeseries-analysis',
43 silly cache add   rawSpec: '',
43 silly cache add   spec: '_',
43 silly cache add   type: 'range' }
44 silly addNamed timeseries-analysis@_
45 verbose addNamed "_" is a valid semver range for timeseries-analysis
46 silly addNameRange { name: 'timeseries-analysis', range: '_', hasData: false }
47 silly mapToRegistry name timeseries-analysis
48 silly mapToRegistry using default registry
49 silly mapToRegistry registry https://registry.npmjs.org/
50 silly mapToRegistry uri https://registry.npmjs.org/timeseries-analysis
51 verbose addNameRange registry:https://registry.npmjs.org/timeseries-analysis not in flight; fetching
52 verbose request uri https://registry.npmjs.org/timeseries-analysis
53 verbose request no auth needed
54 info attempt registry request try #1 at 17:50:25
55 verbose request id da2cb1418013c1a1
56 http request GET https://registry.npmjs.org/timeseries-analysis
57 verbose stack TypeError: undefined is not a function
57 verbose stack     at Request.init (/usr/local/lib/node_modules/npm/node_modules/request/request.js:162:33)
57 verbose stack     at new Request (/usr/local/lib/node_modules/npm/node_modules/request/request.js:140:8)
57 verbose stack     at request (/usr/local/lib/node_modules/npm/node_modules/request/index.js:55:10)
57 verbose stack     at CachingRegistryClient.makeRequest (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:148:13)
57 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:66:17
57 verbose stack     at RetryOperation._fn (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/attempt.js:18:5)
57 verbose stack     at RetryOperation.attempt (/usr/local/lib/node_modules/npm/node_modules/retry/lib/retry_operation.js:56:8)
57 verbose stack     at CachingRegistryClient.attempt (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/attempt.js:11:13)
57 verbose stack     at CachingRegistryClient.regRequest [as _request](/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:65:8)
57 verbose stack     at CachingRegistryClient._invalidatingRequest (/usr/local/lib/node_modules/npm/lib/cache/caching-client.js:33:17)
58 verbose cwd /Users/manuelmaestrini/Dropbox/Programming/My Software
59 error Darwin 14.5.0
60 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "timeseries-analysis"
61 error node v0.12.7
62 error npm  v2.14.4
63 error undefined is not a function
64 error If you need help, you may report this error at:
64 error     https://github.com/npm/npm/issues
65 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@maeishoj Does this also occur if you [update](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) to the latest stable release of `npm`?

**Comment by maeishoj** [comment]
something must be wrong with my npm :( 

I tried npm install npm -g  and I get the same error.. :/ 
Still get 

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "npm" "-g"
npm ERR! node v0.12.7
npm ERR! npm  v2.14.4

What can I do?
