### ISSUE TITLE
Integration of github organization teams as npm owners

### ISSUE THREAD

**Issue by martinheidegger** [npm/npm#10100]
At many collaborative projects I work we use github to collaborate. In the project it is easy to specify what persons are allowed to push to a repository but once pushed it often takes one of the original maintainers to then actually publish the npm package. An ideal workflow that I could imagine was that I would be able to do something like `npm owners add github:nodeschool:core` to add a github team as owners to the repository. Every person that is part of this team would be able then to own this npm repository.

**Comment by othiym23** [comment]
This is something that would be super useful, but this isn't a feature for the CLI. Could I persuade you to reopen this over on npm/newww? Thanks for putting it together!

**Comment by martinheidegger** [comment]
It should be available in the CLI as well as online imho.

**Comment by othiym23** [comment]
That's true, and to work properly, there would need to be a persistent link between the npm owners list or org and the GH owners list, and that ultimately needs to happen at the registry level, to which the web site is much closer than the CLI. In other words, the CLI would be able to control the feature, but wouldn't be implementing the core logic.
