### ISSUE TITLE
Mac OS local install failed

### ISSUE THREAD

**Issue by smithsv** [npm/npm#10110]
Steps:
1. just install node js ()
2. make dir in docs
3. Try to install modules localy and without "admin" rights (npm install --save cordova ionic)
See foloving output:
npm WARN locking Error: EACCES: permission denied, open '/Users/smithsv/.npm/_locks/cordova-10e08f6e3d31e1ab.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/smithsv/.npm/_locks/cordova-10e08f6e3d31e1ab.lock failed { [Error: EACCES: permission denied, open '/Users/smithsv/.npm/_locks/cordova-10e08f6e3d31e1ab.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   syscall: 'open',
npm WARN locking   path: '/Users/smithsv/.npm/_locks/cordova-10e08f6e3d31e1ab.lock' }
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "cordova" "ionic"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7

Simple Solution for me:
rm -R /Users/smithsv/.npm under Admin privileges

**Comment by KenanY** [comment]
@smithsv Yeah, looks like you don't have permission to access some files in `npm`'s cache directory. In the future you can try running:

``` sh
sudo chown -R $(whoami) "$HOME/.npm"
```

**Comment by KenanY** [comment]
@smithsv It has been several months now with no reply from you... are you still seeing this issue?

**Comment by KenanY** [comment]
Closing as abandoned and very likely to be an issue with directory permissions and not with `npm` itself.
