### ISSUE TITLE
npm link --global

### ISSUE THREAD

**Issue by dsernst** [npm/npm#10113]
Is there a way to use `npm link` for a module that is meant to be installed globally?

Trying this:

```
npm link -g npm-run-help
```

throws this error:

```
npm ERR! link should never be --global.
npm ERR! Please re-run this command with --local
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

But what if the `--global` flag was intentional? Why is this not allowed? This line from the [`npm link` man page](https://docs.npmjs.com/cli/link) still applies:

> This is handy for installing your own stuff, so that you can work on it and test it iteratively without having to continually rebuild.

**Comment by kumavis** [comment]
Yes, I am also curious why this is forbidden

**Comment by legodude17** [comment]
`npm link` will always link the bin of the current project to the `npm.prefix`. See: #13702. I think it errors because npm link will always do that.

**Comment by legodude17** [comment]
Though I think it should just ignore the global mode.
