### ISSUE TITLE
pomelo$ sh npm-install.sh

### ISSUE THREAD

**Issue by lin-123** [npm/npm#10112]
helloworld@0.0.1 /vagrant/chat/helloworld/game-server
└── UNMET PEER DEPENDENCY pomelo-logger@0.1.7

npm WARN EPACKAGEJSON helloworld@0.0.1 No description
npm WARN EPACKAGEJSON helloworld@0.0.1 No repository field.
npm WARN EPACKAGEJSON helloworld@0.0.1 No license field.
npm ERR! Linux 3.19.0-15-generic
npm ERR! argv "node" "/home/vagrant/.nvm/v0.10.40/bin/npm" "install"
npm ERR! node v0.10.40
npm ERR! npm  v3.3.4
npm ERR! path ../semver/bin/semver
npm ERR! code UNKNOWN
npm ERR! errno -1

npm ERR! UNKNOWN, symlink '../semver/bin/semver'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /vagrant/chat/helloworld/game-server/npm-debug.log

**Comment by KenanY** [comment]
@lin-123 Is this Vagrant on top of Windows?

**Comment by lin-123** [comment]
on mac mini

**Comment by lin-123** [comment]
@KenanY this vagrant on mac mini

**Comment by KenanY** [comment]
@lin-123 Have you tried using the [`--no-bin-links`](https://docs.npmjs.com/misc/config#bin-links) flag?

**Comment by lin-123** [comment]
@KenanY  Yes, it worked when  i used `npm install --no-bin-links`. thanks for your help
