### ISSUE TITLE
getting this issue. Not sure what really is !!

### ISSUE THREAD

**Issue by SuryaJD** [npm/npm#10115]
![screenshot 101](https://cloud.githubusercontent.com/assets/13571823/10725522/a2876804-7bf2-11e5-9770-700b694aa0c9.png)

**Comment by KenanY** [comment]
Might be best to close this in favor of https://github.com/npm/npm/issues/10107, which was previously opened by @SuryaJD as well and also involves a shasum mismatch.

**Comment by othiym23** [comment]
Closing as duplicate of #10107.
