### ISSUE TITLE
Npm test swallows stream to process.stdout

### ISSUE THREAD

**Issue by adius** [npm/npm#10114]
This is by far the weirdest bug I have ever encountered.

When you pipe to `process.stdout` during execution of `npm test` the output will only be displayed in the shell when the streamed string has a certain length. (except the string contains a `\n`. Then it will always get printed).

I couldn't figure out, however, an exact value for the length. It seems to depend on the width of the terminal window, but no idea what the exact relation is.

I use Mac OS X 10.11.1 and it's replicatable both in the iTerm and Terminal app.

Minimal example:

Make a directory `test` including two files `test.js` and `package.json`

File `test.js`:

``` es6
var stream = require('stream')
var hasRead = false

new stream.Readable({
        read: function (n) {
            if (!hasRead){
                this.push('test')
                hasRead = true
            }
        }
    })
    .pipe(new stream.Transform({
        transform: function (chunk, encoding, done) {
            done(null, 'abcde')
        }
    }))
    .pipe(process.stdout)
```

File: `package.json`

``` json
{
  "name": "test",
  "scripts": {
    "test": "node ./test.js "
  }
}
```

When you now run `npm test` in the `test` directory, nothing gets printed to stdout:

``` sh
~/test$ npm test

> test@ test /Users/adrian/Desktop/test
> node ./test.js

~/test$
```

If you keep increasing the length of the `abcde` String, it will start to print to stdout at some point:

``` sh
adrians-mac:~/Desktop/test$ npm test

> test@ test /Users/adrian/Desktop/test
> node ./test.js

abcde abcde abcde abcde abcde abcde abcde abcde abcde abcde abcde abcde abcde abcde abcde abcde abcde abcde abcde abcde abcde abcde abcde adrians-mac:~/Desktop/test$
```

This only happens during execution of the script with `npm test` and not when it's executed directly with `node test.js`

Any ideas?

**Comment by alexanderGugel** [comment]
I'm running into the same issue.

Something is overriding it it seems. If you setTimeout before exiting, the text briefly shows up:
```js
setTimeout(function () {}, 1000)
```
https://www.youtube.com/watch?v=ItWml7SEbjc&feature=youtu.be

**Comment by alexanderGugel** [comment]
Found the bug. There is a bug in the `cooked` end event listener

**Comment by othiym23** [comment]
The first question to answer is why this started breaking now. What version of Node are those of you encountering this problem running? That chunk of the code has been that way for a pretty long time, and I'm also on OS X and haven't been seeing this behavior.

**Comment by adius** [comment]
Well, I guess the use case is very specific:

- logging during npm test
- without newline character
- with a certain window size

I haven't seen it before either =P

**Comment by dancoates** [comment]
+1 for experiencing this, but with `npm run-script` not `npm test` specifically. Adding a `\n` does seem to fix it. So does replacing `process.exit(1)` with `process.stderr.write('\n') && process.exit(1);`.

Here's a reduced test case: https://github.com/dancoates/npmstdoutbug that shows the issue in npm 3.4.0.
