### ISSUE TITLE
Linter-csslint Failed To Install

### ISSUE THREAD

**Issue by inspiredmac** [npm/npm#10123]
The following installation warning was provided. All other Atom Community linters installed without error:

Installing “linter-csslint@1.1.0” failed.Hide output…

npm WARN addRemoteGit git+https://github.com/AtomLinter/csslint.git resetting remote /Users/danielleavey/.atom/.apm/_git-remotes/https-github-com-AtomLinter-csslint-git-d9ec64d1 because of error: Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.
npm ERR! git clone --template=/Users/danielleavey/.atom/.apm/_git-remotes/_templates --mirror https://github.com/AtomLinter/csslint.git /Users/danielleavey/.atom/.apm/_git-remotes/https-github-com-AtomLinter-csslint-git-d9ec64d1: Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.
npm ERR! Darwin 14.5.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/danielleavey/.atom/.apm/.apmrc" "--userconfig" "/Users/danielleavey/.atom/.apmrc" "install" "/private/var/folders/1f/9b14rgys0fx4bn0tjxbfm_vc0000gn/T/d-115926-2011-1qcifey/package.tgz" "--target=0.30.7" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code 69

npm ERR! Command failed: 
npm ERR! 
npm ERR! Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.
npm ERR! 
npm ERR! 
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/1f/9b14rgys0fx4bn0tjxbfm_vc0000gn/T/apm-install-dir-115926-2011-1idnm2k/npm-debug.log

**Comment by KenanY** [comment]
@inspiredmac Is this still an issue for you?

**Comment by inspiredmac** [comment]
No, I haven't seen any further warnings in Atom.  Thanks.

**Comment by KenanY** [comment]
@inspiredmac Thanks for following up :)
