### ISSUE TITLE
Let me install a module as a devDependency of itself

### ISSUE THREAD

**Issue by callumlocke** [npm/npm#10128]
Currently npm says "Refusing to install foo as a dependency of itself".

I see why it's necessary to refuse to install a module as its own production dependency, as that would be circular.

But this isn't the case for devDependencies, which are installed without their own devDeps (so no circle would occur).

**Comment by KenanY** [comment]
@callumlocke Do you know of a use-case for this?

**Comment by callumlocke** [comment]
I have a TDD tool with a stable v1 API, and I want to use this to help me develop version 2 of the same tool.

Lots of tools use themselves to build or test themselves. Grunt [has a gruntfile](https://github.com/gruntjs/grunt/blob/master/Gruntfile.js), and mocha [tests itself with mocha](https://github.com/mochajs/mocha/blob/master/test/suite.js), and CoffeeScript builds itself with CoffeeScript.

But because of the unnecessary npm restriction on installing a dev dependency of the same name as the parent,  the usual approach is to relative-require the main file from right inside the same project that is under development. For example, mocha does `var mocha = require('../')` at the top of its tests. This has the huge downside that you are developing using a tool that is itself constantly changing under your feet because it is the very thing you are developing :) If you break it, you have to get it working again 'in the dark' with no TDD guidance. Much better to just stick to using the stable v1 API to help you develop v2 (then maybe update to use v2 for your self-tests once it's actually finished).

Another workaround is to use a proxy module – for example CoffeeScript actually dev-depends on Cake (which itself depends on CoffeeScript). This circumvents the unnecessary npm restriction. But I don't want to create a dummy proxy module just for this purpose, as it feels like a misuse of npm.

**Comment by markstos** [comment]
@callumlocke This seems like something of an edge case. What about the alternative of using an explicit `npm install module-name` for these cases?

**Comment by callumlocke** [comment]
> This seems like something of an edge case.

I don't think it's an edge case. It's pretty common for build tools to use their own code as part of their own build – I checked 4 projects I guessed might do this, and I was right about 3 of them (grunt, mocha, coffeescript).

> What about the alternative of using an explicit npm install module-name for these cases?

Not sure what you mean... that's exactly what doesn't work

**Comment by estliberitas** [comment]
Well, other edge case would be benchmarking of older module version and throwing an error in some prepublish script. So it would prevent publishing of newer version if there is performance regression. Something like that might work for modules in private repos. :wink:

**Comment by hagaiak** [comment]
I also think this would be useful. Essentially all tools that are meant to be installed as devDependencies would benefit from devDepending on themselves.

**Comment by dominictarr** [comment]
:+1: I agree this definitely makes sense for a dev dependency.

**Comment by danShumway** [comment]
This would also be useful for me. I have a testing library (Distilled) that uses its own unit tests as example code to demonstrate how the library works. In that instance I'm requiring the library by manually linking to itself, which (while annoying) doesn't bother me too much because the tests are just for show - my actual unit tests are written against an unaffiliated 3rd-party to help guard against self-hiding errors.

However, I'm also working on a documentation library that would like to document itself. To further complicate matters, the tool is split into multiple modules, and each of those module would like to use the full library to document themselves. This means that I can't just manually link to a relative directory.
