### ISSUE TITLE
UNABLE_TO_GET_ISSUER_CERT_LOCALLY

### ISSUE THREAD

**Issue by kilgarenone** [npm/npm#10125]
I can't install anything with npm install..Please help..

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'learnyounode' ]
2 info using npm@2.14.7
3 info using node@v4.2.1
4 verbose install initial load of C:\Users\bkheoh\AppData\Roaming\npm\package.json
5 verbose readDependencies loading dependencies from C:\Users\bkheoh\AppData\Roaming\npm\package.json
6 silly cache add args [ 'learnyounode', null ]
7 verbose cache add spec learnyounode
8 silly cache add parsed spec Result {
8 silly cache add   raw: 'learnyounode',
8 silly cache add   scope: null,
8 silly cache add   name: 'learnyounode',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 silly addNamed learnyounode@*
10 verbose addNamed "*" is a valid semver range for learnyounode
11 silly addNameRange { name: 'learnyounode', range: '*', hasData: false }
12 silly mapToRegistry name learnyounode
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/learnyounode
16 verbose addNameRange registry:https://registry.npmjs.org/learnyounode not in flight; fetching
17 verbose request uri https://registry.npmjs.org/learnyounode
18 verbose request no auth needed
19 info attempt registry request try #1 at 2:03:41 PM
20 verbose request id f204cbce459313d1
21 http request GET https://registry.npmjs.org/learnyounode
22 info retry will retry, error on last attempt: Error: unable to get local issuer certificate
23 info attempt registry request try #2 at 2:03:51 PM
24 http request GET https://registry.npmjs.org/learnyounode
25 info retry will retry, error on last attempt: Error: unable to get local issuer certificate
26 info attempt registry request try #3 at 2:04:51 PM
27 http request GET https://registry.npmjs.org/learnyounode
28 verbose stack Error: unable to get local issuer certificate
28 verbose stack     at Error (native)
28 verbose stack     at TLSSocket.<anonymous> (_tls_wrap.js:1000:38)
28 verbose stack     at emitNone (events.js:67:13)
28 verbose stack     at TLSSocket.emit (events.js:166:7)
28 verbose stack     at TLSSocket._finishInit (_tls_wrap.js:567:8)
29 verbose cwd C:\Users\bkheoh
30 error Windows_NT 6.1.7601
31 error argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "learnyounode"
32 error node v4.2.1
33 error npm  v2.14.7
34 error code UNABLE_TO_GET_ISSUER_CERT_LOCALLY
35 error unable to get local issuer certificate
36 error If you need help, you may report this error at:
36 error     <https://github.com/npm/npm/issues>
37 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@kilgarenone Are you still experiencing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
