### ISSUE TITLE
114369 error Error: ENOENT, open '/root/tmp/npm-11528

### ISSUE THREAD

**Issue by Ninjapro68** [npm/npm#10120]
Im trying to install butter project i logged in as root cd into dir and then did ./make_butter.sh

then i get this: 
114367 silly lockFile 92057bb9-ansi-styles-1-0-0 ansi-styles@1.0.0
114368 silly lockFile 92057bb9-ansi-styles-1-0-0 ansi-styles@1.0.0
114369 error Error: ENOENT, open '/root/tmp/npm-11528-PLwp63o_/1445883066526-0.5550515430513769/package/test/deferred.js'
114370 error If you need help, you may report this log at:
114370 error     <http://github.com/isaacs/npm/issues>
114370 error or email it to:
114370 error     <npm-@googlegroups.com>
114371 error System Linux 3.19.0-31-generic
114372 error command "/usr/bin/nodejs" "/usr/bin/npm" "install"
114373 error cwd /home/ninjapro68/Desktop/butter-master/butter
114374 error node -v v0.10.25
114375 error npm -v 1.3.10
114376 error path /root/tmp/npm-11528-PLwp63o_/1445883066526-0.5550515430513769/package/test/deferred.js
114377 error code ENOENT
114378 error errno 34
114379 verbose exit [ 34, true ]

**Comment by KenanY** [comment]
@Ninjapro68 `npm@1.3` had not been supported for quite a while now. Please try [updating](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) first.

**Comment by Ninjapro68** [comment]
@KenanY I just did and now when i do ./make_butter.sh

this comes up 

![screenshot from 2015-10-26 18 29 55](https://cloud.githubusercontent.com/assets/15329590/10738516/ab738bce-7c0f-11e5-9c35-b3133ac4b46c.png)

**Comment by Ninjapro68** [comment]
@KenanY Look now it says :

![image](https://cloud.githubusercontent.com/assets/15329590/10738827/22545358-7c11-11e5-9f3b-fe0098a2ecc9.png)

**Comment by KenanY** [comment]
@Ninjapro68 Oh, your Node.js binary is called `nodejs` instead of the conventional `node`. Maybe try symlinking the two?:

```
ln -s /usr/bin/nodejs /usr/bin/node
```

You could also try installing the "nodejs-legacy" package from the Debian repo, or install Node.js through [NodeSource's distribution](https://github.com/nodejs/node-v0.x-archive/wiki/Installing-Node.js-via-package-manager#debian-and-ubuntu-based-linux-distributions).

**Comment by Ninjapro68** [comment]
@KenanY I did then it comes up with this 

![image](https://cloud.githubusercontent.com/assets/15329590/10739290/6fd0e6f8-7c13-11e5-8410-08698f95c5c4.png)

**Comment by Ninjapro68** [comment]
@KenanY Do i run it as sudo?

**Comment by KenanY** [comment]
@Ninjapro68 Hmm you don't have permission to modify `~/.config`... could you try using `chown` to fix the permissions?:

``` sh
sudo chown -R $(whoami) "$HOME/.config"
```

**Comment by Ninjapro68** [comment]
@KenanY I tried using sudo it came up with this 

![image](https://cloud.githubusercontent.com/assets/15329590/10739506/b87ec202-7c14-11e5-9b8b-a39b4a5f17ca.png)

**Comment by KenanY** [comment]
@Ninjapro68 Hmm I didn't suggest running that with `sudo`... just the `chown` command.

**Comment by Ninjapro68** [comment]
@KenanY Yeah i did sudo chown -R $(whoami) "$HOME/.config" and then sudo rm -rf butter then i did ./make_butter.sh Its still installing it :/

**Comment by Ninjapro68** [comment]
@KenanY It comes up with loads of error like these 
![image](https://cloud.githubusercontent.com/assets/15329590/10739583/31e5fef8-7c15-11e5-8d42-180e1659c463.png)

**Comment by KenanY** [comment]
@Ninjapro68 Meh those are warnings not errors. Generally those "engine" ones can be ignored.

**Comment by Ninjapro68** [comment]
@KenanY btw after this does it mean the butter project is installed?

**Comment by KenanY** [comment]
@Ninjapro68 I don't know enough about the project to say. I would ask the developer(s) or other users.

**Comment by Ninjapro68** [comment]
@KenanY why does this process take so long

**Comment by Ninjapro68** [comment]
oh nvm

**Comment by Ninjapro68** [comment]
now this comes up 

![image](https://cloud.githubusercontent.com/assets/15329590/10739857/e5764b7a-7c16-11e5-9d10-a825733c6fbf.png)

**Comment by Ninjapro68** [comment]
@KenanY

**Comment by Ninjapro68** [comment]
Its fine i fixed it @KenanY
