### ISSUE TITLE
Protocol error sym link during vagrant installation

### ISSUE THREAD

**Issue by sunnytham** [npm/npm#10121]
Hello,
I encounter the following error while installing lumify via Vagrant to VirtualBox. Kindly guide me to the necessary steps so to continue installing..
Thanks!

==> demo:  lumify@0.1.0 license should be a valid SPDX license expression
==> demo: [4mRunning "bower:install" (bower) task[24m
==> demo: [32m>> [39mInstalled bower packages
==> demo: 
==> demo: [4mRunning "bower:prune" (bower) task[24m
==> demo: [32m>> [39mInstalled bower packages
==> demo: 
==> demo: [4mRunning "exec:buildOpenlayers" (exec) task[24m
==> demo: 
==> demo: [4mRunning "exec:buildCytoscape" (exec) task[24m
==> demo: [31m>> [39mPicked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
==> demo: [31m>> [39mPicked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
==> demo: [31m>> [39mPicked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
==> demo: [31m>> [39mPicked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
==> demo: [31m>> [39mPicked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
==> demo: [31m>> [39mPicked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
==> demo: [31m>> [39mPicked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
==> demo: [31m>> [39mPicked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
==> demo: [31m>> [39mPicked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
==> demo: [31m>> [39mPicked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
==> demo: [31m>> [39mPicked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
==> demo: [31m>> [39mPicked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
==> demo: [31m>> [39mPicked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
==> demo: 
==> demo: [4mRunning "exec:buildPathFinding" (exec) task[24m
==> demo: [31m>> [39mnpm
==> demo: [31m>> [39mWARN engine mocha@1.0.3: wanted: {"node":">= 0.4.x < 0.8.0"} (current: {"node":"4.2.1","npm":"3.3.9"})
==> demo: [31m>> [39mnpm
==> demo: [31m>> [39mWARN deprecated buffer-browserify@0.1.0: Package not maintained. Recent browserify uses https://github.com/feross/buffer
==> demo: [31m>> [39mnpm
==> demo: [31m>> [39m
==> demo: [31m>> [39mWARN excluding symbolic link lib/index.js -> jade.js
==> demo: [31m>> [39mnpm
==> demo: [31m>> [39mWARN EPACKAGEJSON pathfinding@0.4.10 No license field.
==> demo: [31m>> [39mnpm
==> demo: [31m>> [39mERR! Linux 2.6.32-573.7.1.el6.x86_64[31m
==> demo: >> [39mnpm ERR! argv "/usr/local/bin/node" "/usr/bin/npm" "install" "-q"[31m
==> demo: >> [39mnpm ERR! node v4.2.1[31m
==> demo: >> [39mnpm ERR! npm
==> demo: [31m>> [39mv3.3.9[31m
==> demo: >> [39mnpm ERR! path ../esprima/bin/esparse.js[31m
==> demo: >> [39mnpm ERR! code EPROTO[31m
==> demo: >> [39mnpm ERR!
==> demo: [31m>> [39merrno -71[31m
==> demo: >> [39mnpm ERR! syscall symlink[31m
==> demo: >> [39m[31m
==> demo: >> [39mnpm ERR! EPROTO: protocol error, symlink '../esprima/bin/esparse.js' -> '/vagrant/web/war/src/main/webapp/libs/PathFinding.js/node_modules/.bin/esparse'
==> demo: [31m>> [39mnpm ERR!
==> demo: [31m>> [39mnpm ERR! If you need help, you may report this error at:[31m
==> demo: >> [39mnpm ERR!     <https://github.com/npm/npm/issues>
==> demo: [31m>> [39mnpm
==> demo: [31m>> [39mERR! Linux 2.6.32-573.7.1.el6.x86_64[31m
==> demo: >> [39mnpm ERR! argv "/usr/local/bin/node" "/usr/bin/npm" "install" "-q"[31m
==> demo: >> [39mnpm ERR! node v4.2.1[31m
==> demo: >> [39mnpm ERR! npm  v3.3.9[31m
==> demo: >> [39mnpm
==> demo: [31m>> [39mERR! path npm-debug.log.92cb5c502c5cc7dea5fd32a8eafd6a97[31m
==> demo: >> [39mnpm ERR! code ETXTBSY[31m
==> demo: >> [39mnpm ERR! errno -26[31m
==> demo: >> [39mnpm ERR! syscall
==> demo: [31m>> [39mrename
==> demo: [31m>> [39mnpm ERR! ETXTBSY: text file is busy, rename 'npm-debug.log.92cb5c502c5cc7dea5fd32a8eafd6a97' -> 'npm-debug.log'
==> demo: [31m>> [39mnpm
==> demo: [31m>> [39mERR! [31m
==> demo: >> [39mnpm
==> demo: [31m>> [39mERR! If you need help, you may report this error at:[31m
==> demo: >> [39mnpm ERR!     <https://github.com/npm/npm/issues>
==> demo: [31m>> [39mnpm
==> demo: [31m>> [39mERR! Please include the following file with any support request:[31m
==> demo: >> [39mnpm ERR!     /vagrant/web/war/src/main/webapp/libs/PathFinding.js/npm-debug.log
==> demo: [31m>> [39mExited with code: 185.
==> demo: [33mWarning: Task "exec:buildPathFinding" failed. Use --force to continue.[39m
==> demo: [31mAborted due to warnings.[39m
==> demo: [INFO] ------------------------------------------------------------------------

**Comment by KenanY** [comment]
@sunnytham Is this still an issue for you?

**Comment by KenanY** [comment]
Closing as abandoned.
