### ISSUE TITLE
Errors installing grunt package

### ISSUE THREAD

**Issue by rachaedwards** [npm/npm#10127]
Hi, I'm having trouble installing the package grunticon. I'll include what I saw in the command window below. Let me know if you'd also like to see the npm-debug file.

I've tried installing grunticon with the lines "npm install grunt-grunticon --save-dev", "npm install grunt-grunticon", and by adding the package as a dependency to the package.json file and running the line "npm install".

Our other web designer also tried to install the package and got errors. Please let me know if you have any ideas about what's going wrong.

<h4>Error Message in Console</h4>

<pre><code>
C:\Users\J1082\Desktop\grunt test project&gt;npm install grunt-grunticon
npm WARN package.json my-project-name@0.1.0 No description
npm WARN package.json my-project-name@0.1.0 No repository field.
npm WARN package.json my-project-name@0.1.0 No README data
\
&gt; phantomjs@1.9.18 install C:\Users\J1082\Desktop\grunt test project\node_module
s\grunt-grunticon\node_modules\grunticon-lib\node_modules\svg-to-png\node_module
s\phantomjs
&gt; node install.js

Download already available at C:\Users\J1082\AppData\Local\Temp\phantomjs\phanto
mjs-1.9.8-windows.zip
Extracting zip contents
Removing C:\Users\J1082\Desktop\grunt test project\node_modules\grunt-grunticon\
node_modules\grunticon-lib\node_modules\svg-to-png\node_modules\phantomjs\lib\ph
antom
Copying extracted folder C:\Users\J1082\AppData\Local\Temp\phantomjs\phantomjs-1
.9.8-windows.zip-extract-1445896052595\phantomjs-1.9.8-windows -&gt; C:\Users\J1082
\Desktop\grunt test project\node_modules\grunt-grunticon\node_modules\grunticon-
lib\node_modules\svg-to-png\node_modules\phantomjs\lib\phantom
Writing location.js file
Done. Phantomjs binary available at C:\Users\J1082\Desktop\grunt test project\no
de_modules\grunt-grunticon\node_modules\grunticon-lib\node_modules\svg-to-png\no
de_modules\phantomjs\lib\phantom\phantomjs.exe

&gt; jpegtran-bin@3.0.5 postinstall C:\Users\J1082\Desktop\grunt test project\node_
modules\grunt-grunticon\node_modules\grunticon-lib\node_modules\svg-to-png\node_
modules\imagemin\node_modules\imagemin-jpegtran\node_modules\jpegtran-bin
&gt; node lib/install.js

  v jpegtran pre-build test passed successfully

&gt; gifsicle@3.0.1 postinstall C:\Users\J1082\Desktop\grunt test project\node_modu
les\grunt-grunticon\node_modules\grunticon-lib\node_modules\svg-to-png\node_modu
les\imagemin\node_modules\imagemin-gifsicle\node_modules\gifsicle
&gt; node lib/install.js

  v gifsicle pre-build test passed successfully

&gt; pngquant-bin@3.0.0 postinstall C:\Users\J1082\Desktop\grunt test project\node_
modules\grunt-grunticon\node_modules\grunticon-lib\node_modules\svg-to-png\node_
modules\imagemin\node_modules\imagemin-pngquant\node_modules\pngquant-bin
&gt; node lib/install.js

  v pngquant pre-build test passed successfully

&gt; optipng-bin@3.0.2 postinstall C:\Users\J1082\Desktop\grunt test project\node_m
odules\grunt-grunticon\node_modules\grunticon-lib\node_modules\svg-to-png\node_m
odules\imagemin\node_modules\imagemin-optipng\node_modules\optipng-bin
&gt; node lib/install.js

  ? Command failed: C:\Windows\system32\cmd.exe /s /c "C:\Users\J1082\Desktop\gr
unt test project\node_modules\grunt-grunticon\node_modules\grunticon-lib\node_mo
dules\svg-to-png\node_modules\imagemin\node_modules\imagemin-optipng\node_module
s\optipng-bin\vendor\optipng.exe --version"
'C:\Users\J1082\Desktop\grunt' is not recognized as an internal or external comm
and,
operable program or batch file.

  ? optipng pre-build test failed
  i compiling from source
  x Error: ./configure --with-system-zlib --prefix="C:\Users\J1082\Desktop\grunt
 test project\node_modules\grunt-grunticon\node_modules\grunticon-lib\node_modul
es\svg-to-png\node_modules\imagemin\node_modules\imagemin-optipng\node_modules\o
ptipng-bin\vendor" --bindir="C:\Users\J1082\Desktop\grunt test project\node_modu
les\grunt-grunticon\node_modules\grunticon-lib\node_modules\svg-to-png\node_modu
les\imagemin\node_modules\imagemin-optipng\node_modules\optipng-bin\vendor" &amp;&amp; m
ake install
Command failed: C:\Windows\system32\cmd.exe /s /c "./configure --with-system-zli
b --prefix="C:\Users\J1082\Desktop\grunt test project\node_modules\grunt-gruntic
on\node_modules\grunticon-lib\node_modules\svg-to-png\node_modules\imagemin\node
_modules\imagemin-optipng\node_modules\optipng-bin\vendor" --bindir="C:\Users\J1
082\Desktop\grunt test project\node_modules\grunt-grunticon\node_modules\gruntic
on-lib\node_modules\svg-to-png\node_modules\imagemin\node_modules\imagemin-optip
ng\node_modules\optipng-bin\vendor""
'.' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:751:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "grunt-grunticon"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! Invalid name: "@filamentgroup/worker-farm"
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     
</code></pre>

**Comment by KenanY** [comment]
@rachaedwards Is this still an issue for you?

**Comment by KenanY** [comment]
Closing as abandoned.
