### ISSUE TITLE
verbose stack Error

### ISSUE THREAD

**Issue by Jesn** [npm/npm#10139]
114162 info postinstall htmlescape@1.1.0
114163 info install constants-browserify@0.0.1
114164 info postinstall path-browserify@0.0.0
114165 verbose stack Error: read ECONNRESET
114165 verbose stack     at exports._errnoException (util.js:874:11)
114165 verbose stack     at TLSWrap.onread (net.js:544:26)
114166 verbose cwd G:\workspace\app\IonicDemo\Demo1
114167 error Windows_NT 10.0.10240
114168 error argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ionic"
114169 error node v4.2.1
114170 error npm  v2.14.7
114171 error code ECONNRESET
114172 error errno ECONNRESET
114173 error syscall read
114174 error network read ECONNRESET
114174 error network This is most likely not a problem with npm itself
114174 error network and is related to network connectivity.
114174 error network In most cases you are behind a proxy or have bad network settings.
114174 error network
114174 error network If you are behind a proxy, please make sure that the
114174 error network 'proxy' config is set properly.  See: 'npm help config'
114175 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@Jesn So, I'm basically going to reiterate what the error messages says, but this looks like an issue with your internet connection rather than `npm` (unless proven otherwise). Perhaps you are behind a proxy or firewall that is messing with `npm`'s requests to the registry?

**Comment by KenanY** [comment]
@Jesn Are you still seeing this issue?

**Comment by Jesn** [comment]
@KenanY  thank you very much for your answer, it's because i open  the Shadowsocks,when I close the Shadowsocks and then try again is ok!
