### ISSUE TITLE
Unable to run any npm command

### ISSUE THREAD

**Issue by ghost** [npm/npm#10135]
I am unable to run any npm commands despite having it installed on my computer.  I keep running into the error message:

Error: EACCES: permission denied, mkdir '/Users/your_user'
    at Error (native)

I've tried all the suggestions mentioned in related issues but to no avail. I was also prompted to consult the npm-debug log which displayed the following:

0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'link' ]
2 info using npm@2.12.1
3 info using node@v0.12.7
4 verbose node symlink /usr/local/bin/node
5 verbose stack Error: EACCES, mkdir '/Users/your_user'
5 verbose stack     at Error (native)
6 verbose cwd /Users/Andrew
7 error Darwin 14.5.0
8 error argv "node" "/usr/local/bin/npm" "link"
9 error node v0.12.7
10 error npm  v2.12.1
11 error path /Users/your_user
12 error code EACCES
13 error errno -13
14 error Error: EACCES, mkdir '/Users/your_user'
14 error     at Error (native)
14 error  { [Error: EACCES, mkdir '/Users/your_user'] errno: -13, code: 'EACCES', path: '/Users/your_user' }
15 error Please try running this command again as root/Administrator.
16 verbose exit [ -13, true ]

Any help would be much appreciated.

**Comment by boyney123** [comment]
Have you tried running it as sudo, or making sure you have the correct permissions?

**Comment by KenanY** [comment]
Closing since the original poster seems to have since deleted their GitHub account.
