### ISSUE TITLE
npm install stuck at spinner

### ISSUE THREAD

**Issue by PeideAmonNg** [npm/npm#10133]
Hi, I am trying to install bower but can't seem to go past this point: 

C:\Users\pc>npm install bower -g -d
npm info it worked if it ends with ok
npm info using npm@2.14.7
npm info using node@v4.2.1
npm info attempt registry request try #1 at 10:45:26 AM
npm http request GET https://registry.npmjs.org/bower
npm http 200 https://registry.npmjs.org/bower
/ 

The spinner is still spinning after 30 mins, also with the same result installing other modules.
Please advise.

Config: 
node v4.2.1
npm v2.14.7
Windows 7 64bit
Admin rights

Cheers

**Comment by johanbove** [comment]
Having the same issue.

I'm on Windows 10 64 bit in Cmder
Node v 4.3.2
npm 2.14.12

**Comment by PeideAmonNg** [comment]
Solved it when I switched to 32bit nodejs

**Comment by PeideAmonNg** [comment]
Thanks for the page
