### ISSUE TITLE
npm ERR! fetch fails when cURL works fine 

### ISSUE THREAD

**Issue by dzuluaga** [npm/npm#10134]
I'm trying to run the following command, but it fails:

``` bash
npm install "https://npmrepouser:passw0rd@testmyapi-test.apigee.net/npm-private-repo-proxy/npm-package1-1.0.0.tgz" --save --verbose
```

cURL seems to work fine:

``` bash
curl -X GET https://npmrepouser:passw0rd@testmyapi-test.apigee.net/npm-private-repo-proxy/npm-package1-1.0.0.tgz
```

Any clue?

**Comment by KenanY** [comment]
@dzuluaga `npm --version`? Is there a `npm-debug.log` that you can upload to [gist.github.com](https://gist.github.com/)? Not enough information right now to say anything.

**Comment by dzuluaga** [comment]
Sure. Here it is @KenanY. https://gist.github.com/dzuluaga/1b95b3ab5f5c60ab53f5
npm version: 3.3.9

Also, notice that I'm using basic authentication in the url, which used to work in the past. Thanks in advance!
