### ISSUE TITLE
Maybe shorter progress bar?

### ISSUE THREAD

**Issue by pronvit** [npm/npm#10132]
And more space for the package names. It's not really important what it shows there but that long and precise progress bar is even less useful.

![screen shot 2015-10-28 at 8 50 58 am](https://cloud.githubusercontent.com/assets/7973649/10770658/550545b4-7d51-11e5-806d-3d113566f7b3.png)

**Comment by nyteshade** [comment]
+1 insofar as I like the progress bar but the size considerations need to be swapped from a ux perspective. Event 10 characters for the progress bar giving you 10% for each block would leave 60-70 for informational text on the left which would help a lot.

**Comment by iarna** [comment]
We did this as of v3.10.0!
