### ISSUE TITLE
npm doesn't authenticate with npm repository that requires Kerberos authentication

### ISSUE THREAD

**Issue by baderbuddy** [npm/npm#10131]
I have a npm repository that requires authentication, it can work with either Kerberos or NTLM, npm seems to just throw an error with the 401 and I don't see any kind of configuration to allow Kerberos.

**Comment by othiym23** [comment]
Out of the box, npm doesn't support Kerberos or NTLM. I'm not aware of any npm registry software that offers those as authentication options, either. Are you working with a private registry with some kind of authenticating proxy in front of it?

A number of npm Windows users have had good luck with [`cntlm`](http://blog.talles.me/git-and-npm-behind-a-ntlm-proxy.html) as a local proxy that can help with NTLM authentication, so you might want to give that a try.

**Comment by baderbuddy** [comment]
Thanks for the quick response.

I am working with a private registry that has a reverse proxy in front of it to handle authentication. The reverse proxy is a simple .net application.

cntlm only works with a Proxy (407 responses) not a reverse proxy (401 responses).

Could this be a feature that's added to npm to support Kerberos authentication? I think it'd be useful to many users of a private registry that want to in some way restrict what's accessible.

**Comment by othiym23** [comment]
The short answer is, "probably not," and here's why. npm is a cross-platform tool, so any new feature added to it needs to work under Windows, OS X, and Linux (at least). Also, as the package manager bundled with Node, that's also available for download and installa
