### ISSUE TITLE
Error at installing npm

### ISSUE THREAD

**Issue by guschaves** [npm/npm#10143]
npm ERR! tar pack Error reading /root/tmp/npm-3503/1446047239779-0.6033884985372424/package
npm ERR! TypeError: Cannot call method 'filter' of undefined
npm ERR!     at Packer.IgnoreReader.addIgnoreRules (/usr/local/lib/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore/ignore.js:148:13)
npm ERR!     at Packer.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore/ignore.js:133:10)
npm ERR!     at fs.js:241:14
npm ERR!     at Object.oncomplete (fs.js:93:15)
npm ERR!     at process._makeCallback (node.js:318:24)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.16.0-4-686-pae
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "npm" "-g"
npm ERR! cwd /home/gustavo/node
npm ERR! node -v v0.9.9
npm ERR! npm -v 1.2.10
npm ERR! addLocalDirectory Could not pack "/root/tmp/npm-3503/1446047239779-0.6033884985372424/package" to "/root/.npm/npm/3.3.9/package.tgz"
npm ERR! SyntaxError: Unexpected end of input
npm ERR!     at Object.parse (native)
npm ERR!     at Packer.readRules (/usr/local/lib/node_modules/npm/node_modules/fstream-npm/fstream-npm.js:189:33)
npm ERR!     at Packer.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore/ignore.js:132:22)
npm ERR!     at fs.js:241:14
npm ERR!     at Object.oncomplete (fs.js:93:15)
npm ERR!     at process._makeCallback (node.js:318:24)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.16.0-4-686-pae
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "npm" "-g"
npm ERR! cwd /home/gustavo/node
npm ERR! node -v v0.9.9
npm ERR! npm -v 1.2.10
npm ERR! file /root/tmp/npm-3503/1446047239779-0.6033884985372424/package/node_modules/read-package-tree/test/fixtures/bad/package.json
npm ERR! path /root/tmp/npm-3503/1446047239779-0.6033884985372424/package/node_modules/read-package-tree/test/fixtures/bad
npm ERR! fstream_path /root/tmp/npm-3503/1446047239779-0.6033884985372424/package/node_modules/read-package-tree/test/fixtures/bad
npm ERR! fstream_type Directory
npm ERR! fstream_class Packer
npm ERR! fstream_stack Packer.readRules (/usr/local/lib/node_modules/npm/node_modules/fstream-npm/fstream-npm.js:192:10)
npm ERR! fstream_stack Packer.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore/ignore.js:132:22)
npm ERR! fstream_stack fs.js:241:14
npm ERR! fstream_stack Object.oncomplete (fs.js:93:15)
npm ERR! fstream_stack process._makeCallback (node.js:318:24)
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/gustavo/node/npm-debug.log
npm ERR! not ok code 0

I'm having trouble to install and use it, don't know how to fix it

**Comment by KenanY** [comment]
@guschaves Please update both [Node.js](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-node) and [`npm`](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm).

**Comment by guschaves** [comment]
Yeah, saw that right now. Thanks.
