### ISSUE TITLE
NPM require ignoring links

### ISSUE THREAD

**Issue by cadement** [npm/npm#10148]
The logic for resolution of a `require`'d module seems to be breaking when a library has been attached via an `npm link`.  Specifically, it appears that when `require` attempts to defer up to the parent directory of the requesting module, it does so with complete disregard for the link and instead crawls up the parent directories of the native location of the linked library on the file system.

This, as you might expect, results in `require` failing to locate any modules not explicitly included as dependencies of the library itself.  FWIW - there is a library available that was created to patch this hole (`parent-require`), but this seems to clearly be a bug in the behavior of `require` and not something that developers should have to work around.

To illustrate, given two libraries:
- /opt/MyNodeApp
  - depends on MyNodeLibrary
  - depends on SomeOtherLibrary
- /opt/MyNodeLibrary

Under normal circumstances, where MyNodeLibrary is loaded by npm install from a repository, MyNodeLibrary is able to execute a `require('SomeOtherLibrary')` and `require`'s behavior will look first in MyNodeLibrary's directory in `node_modules` of MyNodeApp, then step up the directory hierarchy from that point eventually locating the library in the `node_modules` directory of MyNodeApp.

However, if you use `npm link` to attach MyNodeLibrary to MyNodeApp (for development purposes), any attempt to `require('SomeOtherLibrary')` in MyNodeLibrary will now fail as unable to locate SomeOtherLibrary.  My assumption is this means that even though executing within the context of MyNodeApp with a linked library, `require` is searching the following path when attempting to load a dependency:
- /opt/MyNodeLibrary/node_modules
- /opt/MyNodeLibrary
- /opt/node_modules
- /opt
- /node_modules
- /

Which of course will never locate the library which is actually at /opt/MyNodeApp/node_modules.

**Comment by fenduru** [comment]
:+1: just ran into this
