### ISSUE TITLE
npm install does not update dependency in local file system

### ISSUE THREAD

**Issue by palortoff** [npm/npm#10159]
I have a package in the local file system listed as a dev-dependency.

```
"devDependencies": {
  "my-private-package": "file:private_modules/my-private-package"
}
```

`npm install` will install the package just fine.

When I change the version of `my-private-package`, npm 2.14.7 will update the dev-dependency, installing the new version of `my-private-package`.

npm 3.3.9 does not.

**Comment by InfiniteStyles** [comment]
Can this issue be closed? I have no idea what this is. It's been over 1 year, without a reply.

**Comment by legodude17** [comment]
I think it can. @KenanY?

**Comment by KenanY** [comment]
@palortoff Is this still an issue with newer versions of `npm`?

**Comment by palortoff** [comment]
Behavior is still the same with 3.10.3

**Comment by legodude17** [comment]
If it isn't fixed, I don't think we should close it. @othiym23 or @zkat, what are your thoughts?

**Comment by palortoff** [comment]
documentation does not state the behavior on a version mismatch. Therefore it is not a bug, it's just inconsistent to the previous major version.
With currently 2463 open issues there is no way all of them will ever be fixed. A lot of unimportant issues like this have to be closed as they only waste time and hide the important issues.

When filing this I hoped it would be relatively easy to fix and would not stay in the backlog this log. Otherwise I never would have filed it.

**Comment by legodude17** [comment]
You can close it if you want.

**Comment by palortoff** [comment]
OK then...
