### ISSUE TITLE
npm@3 on case-insensitive systems

### ISSUE THREAD

**Issue by cebor** [npm/npm#10157]
As in https://github.com/strongloop/strongloop/issues/268 described with npm@3, dependencies will not correctly installed, if there a more than one dependencies with a sub-dependency's name differs in case-sensitivity.

For example one dep adds this:
https://www.npmjs.com/package/jsonstream

And another this one:
https://www.npmjs.com/package/JSONStream

**Comment by boneskull** [comment]
Fwiw I've found if I keep my projects on a case-sensitive FS (a `.dmg` or partition) my life is easier
