### ISSUE TITLE
Cannot npm install pivot: expected find but found component-find

### ISSUE THREAD

**Issue by mcpatrick** [npm/npm#10161]
419 verbose stack Error: Invalid Package: expected find but found component-find
419 verbose stack     at /usr/local/lib/node_modules/npm/lib/cache/add-local-tarball.js:127:21
419 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:345:5
419 verbose stack     at checkBinReferences_ (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:309:45)
419 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:343:3)
419 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:113:5)
419 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:232:12
419 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:76:16
419 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
420 verbose cwd /Users/curt/projects/svn/shn-pivot/trunk
421 error Darwin 14.5.0
422 error argv "/usr/local/Cellar/node/4.2.0/bin/node" "/usr/local/bin/npm" "install" "pivot@0.1.0"
423 error node v4.2.0
424 error npm  v2.14.7
425 error Invalid Package: expected find but found component-find
426 error If you need help, you may report this error at:
426 error     <https://github.com/npm/npm/issues>

**Comment by KenanY** [comment]
Hmm is the source code to that module available anywhere? I couldn't find it anywhere so I guess I'll have to download and unpack the tarball myself when I find the time because I have a small hunch that it is the fault of the module and not `npm`.

**Comment by mcpatrick** [comment]
Thanks for the quick response.  I am a build/release guy and setting this up at the request of a developer.  Let me get some feedback from him because I am finding conflicting info online about which sources are current.  I may be working with the wrong project.

**Comment by mcpatrick** [comment]
My bad completely.  I should have been installing imply-pivot.  I have no idea what project pivot really is.  Thanks again.

**Comment by othiym23** [comment]
Closing as resolved.
