### ISSUE TITLE
`npm install` has different effect depending on order of installation

### ISSUE THREAD

**Issue by andy-hanson** [npm/npm#10168]
Here's my package.json:

```
{
    "scripts": {
        "lint": "eslint src test"
    },
    "devDependencies": {
        "eslint": "1.7.3",
        "escodegen": "latest"
    },
    "eslintConfig": {
        "ecmaFeatures": {"modules": true}
    }
}
```

If I have no `node_modules` and then run `npm install`, I get a `node_modules` directory with `espree` installed.

If I run `npm install eslint@1.7.3` and then `npm install`, I get a `node_modules` directory with `esprima` installed instead.

(Linting will only work in the latter case.)

Here's the relevant part of a diff:

```
Only in node_modules_one_then_other/: espree
Only in node_modules_both_at_once/: esprima
```

My `npm --version` is 3.3.6.

**Comment by busches** [comment]
I'm not able to reproduce this issue using the latest npm of `3.10.8`, can you retry with that version? Installing `eslint@1.7.3` first and then running `npm install` or just running `npm install` result in the same trees. Neither have `espree` in them and shouldn't, since that's a `devDependencie` of `eslint@1.7.3`.

cc\ @KenanY

**Comment by andy-hanson** [comment]
I shouldn't have used "latest" in a bug report since that can change. Here's an updated repro.

```bash
npm --version # 3.10.8
mkdir repro && cd repro

echo '{ "devDependencies": { "eslint": "1.7.3", "escodegen": "1.7.0" } }' > package.json
npm install
ls node_modules > a.txt

rm -r node_modules
npm install eslint@1.7.3
npm install
ls node_modules > b.txt

diff a.txt b.txt
```

Result:
```diff
37c37
< esprima
---
> espree
```

**Comment by busches** [comment]
That is reproducible. @KenanY
