### ISSUE TITLE
Errors installing global packages

### ISSUE THREAD

**Issue by jtsom** [npm/npm#10171]
I'm seeing tons of errors when installing packages globally. This with Node v5 / npm v3.3.10:

https://gist.github.com/jtsom/560080e7d1b1f7e7eef7

I've removed my /usr/local/lib/node_packages and reinstalled but it didn't help.

**Comment by othiym23** [comment]
Those errors are coming from `node-gyp`, which is the program bundled with npm that handles building packages with native (C++) dependencies. Whenever a new major release of Node comes out, with a new version of V8 included, it takes a little while for native module maintainers to get their code caught up. If you need those packages to work, I suggest you switch back to Node.js 4.2.1, which is an LTS (long-term support) release which should work with more native modules. In a month or so, most of the popular native modules should be upgraded to work with Node 5's V8. Thanks for reaching out, and good luck!
