### ISSUE TITLE
error missing script: start

### ISSUE THREAD

**Issue by zhrren** [npm/npm#10177]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/5.0.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'start' ]
2 info using npm@3.3.9
3 info using node@v5.0.0
4 verbose stack Error: missing script: start
4 verbose stack     at run (/usr/local/lib/node_modules/npm/lib/run-script.js:148:19)
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/run-script.js:58:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:345:5
4 verbose stack     at checkBinReferences_ (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:309:45)
4 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:343:3)
4 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:113:5)
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:300:12
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:76:16
4 verbose stack     at tryToString (fs.js:414:3)
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
5 verbose cwd /Users/Ren/Workspace/Documents/Pages
6 error Darwin 14.4.0
7 error argv "/usr/local/Cellar/node/5.0.0/bin/node" "/usr/local/bin/npm" "start"
8 error node v5.0.0
9 error npm  v3.3.9
10 error missing script: start
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
Hello @zhrren :), this error is almost always indicative of, well, not having a `"start"` script defined in your `package.json`. Is there a `package.json` in your present working directory? Are you sure that you have a `"start"` script defined in that `package.json`? What are you _expecting_ to happen when you run `npm start`, so that I can help you reach the desired result?

**Comment by KenanY** [comment]
@zhrren Are you still seeing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
