### ISSUE TITLE
error on installing karma

### ISSUE THREAD

**Issue by LokiMasterMind** [npm/npm#10170]
I am new in unit testing. Right now i install Node.js in my machine and create empty dir.
and using cmd i go to that dir and use command :" npm install -g karma --save-dev" I think, I am on wrong path.help me 

Thanks,

and got error in file npm-debug.log :

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@2.14.7
3 info using node@v4.2.1
4 verbose readDependencies loading dependencies from C:\wamp\www\TestAngularJs\package.json
5 error install Couldn't read dependencies
6 verbose stack Error: ENOENT: no such file or directory, open 'C:\wamp\www\TestAngularJs\package.json'
6 verbose stack     at Error (native)
7 verbose cwd C:\wamp\www\TestAngularJs
8 error Windows_NT 6.1.7601
9 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
10 error node v4.2.1
11 error npm  v2.14.7
12 error path C:\wamp\www\TestAngularJs\package.json
13 error code ENOPACKAGEJSON
14 error errno -4058
15 error syscall open
16 error package.json ENOENT: no such file or directory, open 'C:\wamp\www\TestAngularJs\package.json'
16 error package.json This is most likely not a problem with npm itself.
16 error package.json npm can't find a package.json file in your current directory.
17 verbose exit [ -4058, true ]

**Comment by mapmeld** [comment]
Without a package.json file, you can't run the ```--save-dev``` part of the command which adds karma to your developer dependencies

If you want to save your list of dependencies, use ```npm init``` to create your own package.json file. Or run ```npm install -g karma``` without any ```--save-dev```

**Comment by LokiMasterMind** [comment]
Hi mapmeld,
 As you suggest i created package.json file using npm init but still I got errors. what is the problem and also told me entire process for unit testing using karma in step by step.

Thank you,

Package.json :
{
  "name": "gitfolder",
  "version": "1.0.0",
  "description": "first testing in angular",
  "main": "index.html",
  "scripts": {
    "test": "echo \\\"Error: no test specified\\\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/LokiMasterMind/AngularjsDemo.git"
  },
  "author": "lokesh",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/LokiMasterMind/AngularjsDemo/issues"
  },
  "homepage": "https://github.com/LokiMasterMind/AngularjsDemo", 
}

Error file :
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'karma' ]
2 info using npm@2.14.7
3 info using node@v4.2.1
4 verbose install initial load of C:\Users\lokesh.chandawar\AppData\Roaming\npm\package.json
5 verbose readDependencies loading dependencies from C:\Users\lokesh.chandawar\AppData\Roaming\npm\package.json
6 silly cache add args [ 'karma', null ]
7 verbose cache add spec karma
8 silly cache add parsed spec Result {
8 silly cache add   raw: 'karma',
8 silly cache add   scope: null,
8 silly cache add   name: 'karma',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 silly addNamed karma@*
10 verbose addNamed "*" is a valid semver range for karma
11 silly addNameRange { name: 'karma', range: '*', hasData: false }
12 silly mapToRegistry name karma
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/karma
16 verbose addNameRange registry:https://registry.npmjs.org/karma not in flight; fetching
17 verbose request uri https://registry.npmjs.org/karma
18 verbose request no auth needed
19 info attempt registry request try #1 at 10:32:03 AM
20 verbose request id eaa5445db90de04e
21 http request GET https://registry.npmjs.org/karma
22 info retry will retry, error on last attempt: Error: write EPROTO
23 info attempt registry request try #2 at 10:32:17 AM
24 http request GET https://registry.npmjs.org/karma
25 info retry will retry, error on last attempt: Error: write EPROTO
26 info attempt registry request try #3 at 10:33:20 AM
27 http request GET https://registry.npmjs.org/karma
28 verbose stack Error: write EPROTO
28 verbose stack     at Object.exports._errnoException (util.js:874:11)
28 verbose stack     at exports._exceptionWithHostPort (util.js:897:20)
28 verbose stack     at WriteWrap.afterWrite (net.js:763:14)
29 verbose cwd D:\PROJECT WORK\AngularJS\GitFolder
30 error Windows_NT 6.1.7601
31 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "karma"
32 error node v4.2.1
33 error npm  v2.14.7
34 error code EPROTO
35 error errno EPROTO
36 error syscall write
37 error write EPROTO
38 error If you need help, you may report this error at:
38 error     <https://github.com/npm/npm/issues>
39 verbose exit [ 1, true ]

**Comment by mapmeld** [comment]
npm is trying to GET https://registry.npmjs.org/karma but it cannot, due to Error: write EPROTO

When I looked up that error, it looks like you cannot install because you are behind a proxy and/or it does not like HTTPS. This issue has some different ideas, including this comment about removing HTTPS from the registry: https://github.com/npm/npm/issues/8976#issuecomment-123748215

**Comment by LokiMasterMind** [comment]
Hi @mapmeld ,
 I understand your solution and resolve this problem but getting another one issue.
Thank for your efforts.

**Comment by KenanY** [comment]
@LokiMasterMind Has this issue since been resolved for you?

**Comment by KenanY** [comment]
Closing as abandoned.

**Comment by LokiMasterMind** [comment]
@KenanY 
sorry for late reply.
I had already mention above issue is resolved..
issue was my machine connected with proxy server after changing network this issue is resolved.
my proxy server block access to https://registry.npmjs.org/karma.

I hope this details help you.
