### ISSUE TITLE
error Cannot read property 'localeCompare' of undefined

### ISSUE THREAD

**Issue by hansneil** [npm/npm#10172]
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\learning\\nodejs\\node.exe',
1 verbose cli   'D:\\learning\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'express' ]
2 info using npm@3.3.6
3 info using node@v5.0.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData express
8 silly fetchDirectoryPackageData express
9 silly install normalizeTree
10 silly loadCurrentTree Finishing
11 silly loadIdealTree Starting
12 silly install loadIdealTree
13 silly cloneCurrentTree Starting
14 silly install cloneCurrentTreeToIdealTree
15 silly cloneCurrentTree Finishing
16 silly loadShrinkwrap Starting
17 silly install loadShrinkwrap
18 silly loadShrinkwrap Finishing
19 silly loadAllDepsIntoIdealTree Starting
20 silly install loadAllDepsIntoIdealTree
21 verbose stack TypeError: Cannot read property 'localeCompare' of undefined
21 verbose stack     at installOrder (D:\learning\nodejs\node_modules\npm\lib\install\deps.js:241:32)
21 verbose stack     at Array.sort (native)
21 verbose stack     at D:\learning\nodejs\node_modules\npm\lib\install\deps.js:240:27
21 verbose stack     at cb (D:\learning\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:47:24)
21 verbose stack     at resolveWithExistingModule (D:\learning\nodejs\node_modules\npm\lib\install\deps.js:377:3)
21 verbose stack     at D:\learning\nodejs\node_modules\npm\lib\install\deps.js:347:5
21 verbose stack     at D:\learning\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
21 verbose stack     at Array.forEach (native)
21 verbose stack     at D:\learning\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
21 verbose stack     at Array.forEach (native)
22 verbose cwd D:\learning\nodejs\node_modules
23 error Windows_NT 6.3.9600
24 error argv "D:\\learning\\nodejs\\node.exe" "D:\\learning\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "express"
25 error node v5.0.0
26 error npm  v3.3.6
27 error Cannot read property 'localeCompare' of undefined
28 error If you need help, you may report this error at:
28 error     <https://github.com/npm/npm/issues>
29 verbose exit [ 1, true ]

**Comment by fizker** [comment]
This is a weird error. I get it on Mac for a private project, but a colleague installs fine on Windows.

We have two things checked into `node_modules` without `package.json`, and if I delete `node_modules` first, I can install just fine. With a `npm-shrinkwrap.json` present, there are also no problems.

**Comment by KenanY** [comment]
@hansneil Please try [upgrading](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) to at least [`npm@3.3.7`](https://github.com/npm/npm/releases/tag/v3.3.7), which contained a fix for `localCompare` errors.

> Refactor all attempts to read the module name or package name to go via a single function, with appropriate guards unusual circumstances where they aren't where we expect them. This ultimately will ensure we don't see any more recurrences of the `localeCompare` error and related crashers.

**Comment by rayliao** [comment]
I try upgrading npm to latest, but failed.
npm install -g npm@latest
````
usr/local/lib
└── npm@3.3.10 

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/Cellar/node/0.12.2_1/bin/node" "/usr/local/bin/npm" "install" "-g" "npm@latest"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! path /usr/local/lib/node_modules/npm/node_modules/ansi-styles
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules/npm/node_modules/ansi-styles'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, access '/usr/local/lib/node_modules/npm/node_modules/ansi-styles']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules/npm/node_modules/ansi-styles' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/LiaoYingRay/npm-debug.log
````

**Comment by KenanY** [comment]
@hansneil Have you tried using `sudo`? Your global modules are being installed to `/usr/local/` which you do not have permission to write to.

**Comment by skitsanos** [comment]
same thing even with sudo, npm is still broken...

**Comment by rayliao** [comment]
I knew  the reason with my problem, Because I have used homebrew install node.

**Comment by airatkh** [comment]
I use homebrew install node too
I did.
$npm install -g npm@v3.3.7
It's help me fix issue.

**Comment by tempico** [comment]
@airatkh 
Not working for me

**Comment by razvan-tudosa** [comment]
I'm having the same issue, I'm using Mac OS X 10.11, Node v5.0.0, npm v3.3.6.
I'm just trying to install `gulp-rename` and I'm getting this error: `npm ERR! Cannot read property 'localeCompare' of undefined`

**Comment by KenanY** [comment]
@razvan-tudosa Could you try [my suggestion](https://github.com/npm/npm/issues/10172#issuecomment-152565694)?

**Comment by razvan-tudosa** [comment]
@KenanY already tried that with no luck.

**Comment by KenanY** [comment]
@razvan-tudosa Even with the latest version of `npm`? :scream: Is there a `npm-debug.log` file you can upload to [gist.github.com](https://gist.github.com/) and link here?

**Comment by razvan-tudosa** [comment]
@KenanY [here](https://gist.github.com/razvan-tudosa/7f2084072e6526febcd9) is the `npm-debug.log` file.

**Comment by KenanY** [comment]
@razvan-tudosa That log shows you are still running `npm@3.3.6`....

**Comment by razvan-tudosa** [comment]
Regarding the latest version of `npm` solution, I'm having another issue with that. I'm running `npm install npm@3.3.7 -g` everything goes ok with the installation except when I run `npm -v` turns out I still have `3.3.6`.

You are saying that If I manage to update my `npm` somehow I should get rid of the `localeCompare` problem?

**Comment by KenanY** [comment]
@razvan-tudosa Hmm, usually that indicates that you somehow have two versions of `npm` installed but I rarely see that happen to people on OSX. Are you using `sudo` (you probably have to since your global modules are going to `/usr/local/`)?

And yes, I have not seen anyone report any `localeCompare` issues with `npm@>=3.3.7`. I believe that the bug was sufficiently fixed in `npm@3.3.7`

**Comment by razvan-tudosa** [comment]
@KenanY You are totally right. That was the case, somehow I had 2 versions of `npm` I managed to unlink my old `npm` and re-link it to `3.3.7` from `/Users/razvan/npm/bin/npm` and everything works great now.

Have a fantastic day!

**Comment by KenanY** [comment]
I'm gonna close this issue because I am 95% positive that no one should be seeing this specific issue as of [`npm@3.3.7`](https://github.com/npm/npm/releases/tag/v3.3.7). If anyone experiences this issue with `npm@>=3.3.7`, feel free to open a new issue.

**Comment by SanjanaTailor** [comment]
I am facing the same issue and  having the same problem;
npm -v
5.4.2
node -v
v8.7.0 

facing the same issue error Cannot read property 'localeCompare' of undefined
@KenanY  : needs to open this issue again

**Comment by kenany** [comment]
@SanjanaTailor Please feel free to open a new issue 👍
