### ISSUE TITLE
progress in the terminal

### ISSUE THREAD

**Issue by tosone** [npm/npm#10182]
NodeJs 5.0 with new npm, This new version is very cool. But the progress in the terminal is so terrible.  i think it can be like the linux install some software. Hope a new npm. So cool.

**Comment by denji** [comment]
[yapm](https://github.com/rlidwka/yapm) better progress

![68747470733a2f2f7261772e6769746875622e636f6d2f726c6964776b612f7961706d2f6d61737465722f6368616e6765732f696d616765732f6d61696e2e706e67](https://cloud.githubusercontent.com/assets/3759759/11195081/91e1c34c-8cb8-11e5-84b6-fc26368a9739.png)

**Comment by KenanY** [comment]
@tosone Do you still think there is room for improvement here? If so, could you be more specific?

**Comment by KenanY** [comment]
Closing as abandoned.
