### ISSUE TITLE
mechanism to pass run-script arguments to pre/post hooks

### ISSUE THREAD

**Issue by jasonkarns** [npm/npm#10183]
It's currently possible to pass arguments to a run-script by separating them from npm's arguments with `--`. This is great, and allows an npm script to accept args and flags. However, if the script in question has a pre or post hook, those scripts do not receive any extra arguments/flags. Indeed, this 'feature' was considered a bug and was fixed with 9e4d632c0142ba55df07d624667738b8727336fc

I think there are reasonable expectations to both behaviors. One could reasonably expect pre/post scripts to_not_ receive the additional arguments; or one _could_ expect pre/post scripts to receive the additional arguments. Since there isn't one clearly obvious behavior, and the presence of the extra args could be harmful to pre/post scripts, I definitely agree the current behavior is correct. But has there been any discussion about other possible mechanisms for exposing this data to the pre/post scripts? Perhaps through `lifecycleData` or some env vars or something? Something that could be picked up by the pre/post scripts (opt-in) and not blindly tacked on as extra args.

I've had other scenarios before where I _wished_ the pre/post scripts had access to the extra args, but I can't remember all of them. My current use case is around a version script. I would like to have a `postversion` script that does some extra work (let's say, git-push and open a PR against another repo). However, I don't _always_want this extra behavior to occur. In fact, I'd prefer it to _not_ run by default, and to only run the `postversion` script when npm-version is given a `--publish` flag or something.

Thoughts?

**Comment by flinn** [comment]
It doesn't look like there has been any discussion around this yet, but I agree that there'd be a use in allowing for something like this... I also agree that it'd be best implemented as an _optional_ mechanism that's turned off by default :+1: 

In a project I'm currently working on, I pass a `--spec` argument (like, `npm test --spec=api` or `npm test --spec=db`) when targeting specific sections of my unit tests, and it'd be really useful if the `pretest` and `posttest` npm-scripts also had access to that argument... As an example, this would allow me to ensure that the code coverage report generated by my test run is limited to only include the files/directories relating to each `spec`... 

@jasonkarns -- Did you find another avenue to allow for this type of behavior? It feels like I'd probably be better off just moving this project's build/test/deployment scripts into `gulp` (or another equivalent) at this point, but I figured I'd ask just in case... :grin:
