### ISSUE TITLE
`npm install` froze my server

### ISSUE THREAD

**Issue by omnidan** [npm/npm#10186]
I just tried installing dependencies for a project, at first I tried with npm 3, which resulted in an issue: https://github.com/npm/npm/issues/9204

Then I downgraded to npm 2, removed the `node_modules` folder and re-ran `npm install`, which printed out the following and then froze my server completely - I had to power cycle it.

```
> react-router@1.0.0-rc3 postinstall /home/dan/trello/client/node_modules/react-router
> node -e "require('fs').stat('lib', function (e, s) { process.exit(e || !s.isDirectory() ? 1 : 0) })" || npm run build


\
<--- Last few GCs --->

   33580 ms: Scavenge 198.3 (240.3) -> 187.4 (242.3) MB, 20.0 / 0 ms [allocation failure].
   33816 ms: Scavenge 201.0 (242.3) -> 188.0 (244.3) MB, 16.9 / 0 ms [allocation failure].
   35317 ms: Scavenge 203.7 (245.3) -> 191.4 (245.3) MB, 55.6 / 0 ms [allocation failure].
   36854 ms: Scavenge 204.8 (245.3) -> 192.2 (247.3) MB, 123.9 / 100 ms [allocation failure].
   39465 ms: Scavenge 207.6 (248.3) -> 193.8 (249.3) MB, 42.7 / 0 ms [allocation failure].


<--- JS stacktrace --->

==== JS stack trace =========================================

    2: arguments adaptor frame: 1->2
Security context: 0xa5414a44a49 <JS Object>
    3: OD [/usr/local/lib/node_modules/npm/lib/utils/tar.js:220] [pc=0x34776d810ee6] (this=0x3e067fbe7761 <a ReadStream with map 0x1a5472d75f91>,c=0x3e067fd980a1 <an Uint8Array with map 0x1a5472d1ff89>)
    4: emit [events.js:~117] [pc=0x34776e266d43] (this=0x3e067fbe7761 <a ReadStream with map 0x1a5472d75f91>,type=0xa5414ab61e9 <String[4]: data>)
    5: argu...

FATAL ERROR: Malloced operator new Allocation failed - process out of memory
```

EDIT: I ran `npm install` again after rebooting and now it just writes `Killed` and stops installing after a while. (on npm 2 and 3)

Also I'm using node 5.0.0

**Comment by jsonnull** [comment]
Same issue as https://github.com/npm/npm/issues/9005?

This seems to be affecting me as well when trying to install several dependencies at once on a low memory server.

**Comment by omnidan** [comment]
@jsonnull yep, this seems to be a duplicate of #9005

**Comment by omnidan** [comment]
BTW: The fix is setting `npm config set jobs 1` - npm uses much less ram after setting jobs to 1, so it doesn't get killed/freeze anymore.

**Comment by omnidan** [comment]
BTW: Since this is a memory issue this can be easily fixed by creating swap space or a swap file: https://www.digitalocean.com/community/tutorials/how-to-add-swap-on-ubuntu-12-04
