### ISSUE TITLE
Unable to view global modules

### ISSUE THREAD

**Issue by camabeh** [npm/npm#10196]
Hello,

`npm ls -g depth=0`
I am unable to list global modules in npm 3.3.10 & node 4.1.1. It all works in node 4.2.1.

![image](https://cloud.githubusercontent.com/assets/4454502/10861662/e8cf41b2-7f88-11e5-868a-23e5f2c3cdd4.png)

`npm outdated -g`
https://gist.github.com/camabeh/a1bfff32441ef7431b2d

**Comment by mzgol** [comment]
Node 4.1.1 is not supported by upstream, just upgrade to 4.2.1. You should always use the latest 4.x.y release.

**Comment by NerdDiffer** [comment]
Good to know about 4.1.1, thanks.

**Comment by camabeh** [comment]
Now when it's both Node Latest and LTS? Are they both supported?

**Comment by othiym23** [comment]
This is a duplicate of #10607, and I believe the workaround is the same: see if any of the entries in your global `node_modules` are dangling symlinks. If you could, please follow up there. Thanks for filing this!
