### ISSUE TITLE
Trying to install the latest npm

### ISSUE THREAD

**Issue by dmauro** [npm/npm#10195]
Using `npm install -g npm`, I'm currently on 1.1.61

```
npm http GET https://registry.npmjs.org/npm
npm http 304 https://registry.npmjs.org/npm
npm http GET https://registry.npmjs.org/npm/-/npm-3.3.10.tgz
npm http 200 https://registry.npmjs.org/npm/-/npm-3.3.10.tgz
npm ERR! cb() never called!
npm ERR! not ok code 0
```

**Comment by othiym23** [comment]
You're probably going to have to upgrade to a newer version of npm / Node just to get everything working with the current registry. How do you have such an old version of npm?

**Comment by dmauro** [comment]
I just haven't messed with node/npm in a while. I just wanted to register a module at the request of some of my users. How do I upgrade npm manually, everywhere I searched just tells me to install npm with npm. I updated to the latest node, but it doesn't seem to have updated npm with it.

**Comment by perfetti** [comment]
+1

**Comment by KenanY** [comment]
@dmauro Are you still seeing this issue? We have a guide for updating `npm` over [here](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm).

**Comment by KenanY** [comment]
Closing as abandoned.
