### ISSUE TITLE
not able to install ionic framework

### ISSUE THREAD

**Issue by Sabinash** [npm/npm#10197]
npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm ERR! tar.unpack unzip error C:\Users\TechN1\AppData\Local\Temp\npm-208-a735f
137\registry.npmjs.org\node-sass-\node-sass-3.3.3.tgz
npm ERR! tar.unpack untar error C:\Users\TechN1\AppData\Local\Temp\npm-208-a735f
137\registry.npmjs.org\node-sass-\node-sass-3.3.3.tgz
npm ERR! tar.unpack unzip error C:\Users\TechN1\AppData\Local\Temp\npm-208-a735f
137\registry.npmjs.org\winston-\winston-1.1.1.tgz
npm ERR! tar.unpack unzip error C:\Users\TechN1\AppData\Local\Temp\npm-208-a735f
137\registry.npmjs.org\ionic-cordova-lib-\ionic-cordova-lib-5.1.10.tgz
npm ERR! tar.unpack untar error C:\Users\TechN1\AppData\Local\Temp\npm-208-a735f
137\registry.npmjs.org\ionic-cordova-lib-\ionic-cordova-lib-5.1.10.tgz
npm ERR! Windows_NT 6.1.7600
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\
node_modules\npm\bin\npm-cli.js" "install" "-g" "ionic"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code Z_BUF_ERROR
npm ERR! errno -5

npm ERR! unexpected end of file
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     E:\IonicProject\npm-debug.log

**Comment by Jayasagar** [comment]
Facing the same issue in Windows 32 bit. Having node 5 installed and cordova installed successfuly.  Problem with ionic installation.

npm ERR! tar.unpack unzip error C:\Windows\TEMP\npm-1232-0ddf2e97\registry.npmjs
.org\npm\-\npm-2.1.3.tgz
npm ERR! tar.unpack untar error C:\Windows\TEMP\npm-1232-0ddf2e97\registry.npmjs
.org\npm\-\npm-2.1.3.tgz
npm ERR! tar.unpack unzip error C:\Windows\TEMP\npm-1232-0ddf2e97\registry.npmjs
.org\cordova-js\-\cordova-js-4.0.0.tgz
loadRequestedDeps → netwo ▐ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadRequestedDeps → netwo ▄ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
npm ERR! tar.unpack unzip error C:\Windows\TEMP\npm-1232-0ddf2e97\registry.npmjs
.org\moment\-\moment-2.10.6.tgz
loadRequestedDeps → netwo ▄ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟

**Comment by saha6984** [comment]
## npm install -g ionic

Problem with ionic installation. same issues i am getting it was already in my system i just started update with npm install -g ionic and getting this issue i have done with npm cache clear but still not resolved.


C:\WINDOWS\system32>npm install ionic
▀ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadRequestedDeps → netwo ▄ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
npm ERR! tar.unpack unzip error C:\Users\Priyanka\AppData\Local\Temp\npm-2328-6e5d4ec0\registry.npmjs.org\winston\-\winston-1.1.1.tgz
npm ERR! tar.unpack unzip error C:\Users\Priyanka\AppData\Local\Temp\npm-2328-6e5d4ec0\registry.npmjs.org\node-sass\-\node-sass-3.3.3.tgz
loadRequestedDeps → netwo ▐ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadRequestedDeps → netwo ▄ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░

**Comment by piyushcse29** [comment]
I also faced the same issue. Please help me.

C:\Windows\System32>npm install ionic
npm ERR! tar.unpack unzip error C:\Users\piymitta\AppData\Local\Temp\npm-8044-48
d687d5\registry.npmjs.org\cordova-app-hello-world\-\cordova-app-hello-world-3.9.
0.tgz
npm ERR! tar.unpack untar error C:\Users\piymitta\AppData\Local\Temp\npm-8044-48
d687d5\registry.npmjs.org\cordova-app-hello-world\-\cordova-app-hello-world-3.9.
0.tgz
loadRequestedDeps → netwo ▌ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
^CTerminate batch job (Y/N)? ^C

**Comment by Sabinash** [comment]
it's due to node. js version ,not compatible to ionic framework.Please go through bellow steps ,it works for me.

1. Install all necessary dependencies.
http://ionicframework.com/docs/guide/installation.html
2. Uninstall node.js from PC if already installed
3. Restart PC
4. Download and Install node.js (MSI Installer) from http://nodejs.org/dist/v0.10.38/ for x86 or http://nodejs.org/dist/v0.10.38/x64/ for x64
5. Right-click Command prompt, and then click Run as administrator.
6. Install Cordova using the command: npm install -g cordova
7. Finally install Ionic Framework using the command: npm install -g ionic

**Comment by saha6984** [comment]
# it is working for you ?

**Comment by Sabinash** [comment]
Yes...

**Comment by saha6984** [comment]
Taking too much time to install cordova only

**Comment by Sabinash** [comment]
ya it ll take some time...

**Comment by piyushcse29** [comment]
Hey, I have tried with the version that you have shared, however I am getting below error:

C:\windows\system32>npm install -g cordova
npm WARN engine cordova-serve@0.1.3: wanted: {"node":">= 0.12.0","npm":">= 2.5.
"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm ERR! fetch failed https://registry.npmjs.org/glob/-/glob-4.

**Comment by saha6984** [comment]
# same error

Hey, I have tried with the version that you have shared, however I am getting below error:

C:\windows\system32>npm install -g cordova
npm WARN engine cordova-serve@0.1.3: wanted: {"node":">= 0.12.0","npm":">= 2.5.
"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm ERR! fetch failed https://registry.npmjs.org/glob/-/glob-4.

**Comment by melzoghbi** [comment]
I have the same error message on my MacBook Pro on OSX ElCapitan 10.11.1. any resolution yet ?

**Comment by Jayasagar** [comment]
Did following and its fixed for us!

-- Installed Unbuntu
-- Installed latest version of Node

and then able to install cordova and ionic

npm install -g cordova ionic


On Mon, Nov 2, 2015 at 10:32 PM, Mostafa Elzoghbi [MSFT] <
notifications@github.com> wrote:

> I have the same error message on my MacBook Pro on OSX ElCapitan 10.11.1.
> any resolution yet ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/npm/npm/issues/10197#issuecomment-153083485>.
>



-- 
Regards,
Jayasagar

**Comment by roberto081194** [comment]
If you have NodeJS 5.x, it won't install Ionic, install the LTS NodeJS (4.x).
I was figuring that the my machine have a lot of junk there, but is the NodeJS version.

Greetings.

**Comment by sidharth016** [comment]
http fetch 200 https://registry.npmjs.org/ionic/-/ionic-2.2.3.tgz 
hangs here..!!
