### ISSUE TITLE
Travis CI build error?

### ISSUE THREAD

**Issue by littlee** [npm/npm#10209]
I notice this:
![qq 20151101202344](https://cloud.githubusercontent.com/assets/7534668/10868844/7731a258-80d6-11e5-8c8f-073651c83ac7.png)

Is npm currently breaking down? :flushed:

**Comment by smikes** [comment]
If you click through, you can see that what's failing is node 0.8 -- https://travis-ci.org/npm/npm/jobs/89366933

/cc @othiym23
