### ISSUE TITLE
 UNABLE_TO_VERIFY_LEAF_SIGNATURE

### ISSUE THREAD

**Issue by asifiqbal1989** [npm/npm#10219]
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "cordova"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code UNABLE_TO_VERIFY_LEAF_SIGNATURE

npm ERR! unable to verify the first certificate
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\cris\npm-debug.log

I am getting above  error while trying to install apache cordove using "npm install -g cordova" command on command prompt.
could you please help me to resolve this .

**Comment by snopeks** [comment]
Hello @asifiqbal1989, this looks like a proxy configuration issue. Are you working behind a corporate proxy? If so, could you give this article a read and try to configure the proxy for npm? http://wil.boayue.com/blog/2013/06/14/using-npm-behind-a-proxy/
Let me know how it goes, or if I'm misunderstanding the issue. Thanks!

**Comment by snopeks** [comment]
@asifiqbal1989 closing since we haven't heard back from you. Let me know if this is still an issue!
