### ISSUE TITLE
Cannot downgrade to NPM 2 from NPM 3

### ISSUE THREAD

**Issue by msartintarm** [npm/npm#10214]
Our project is not compatible with npm 3, so we need to get people using new machines to downgrade to npm 2. We're running Yosemite and using Homebrew.
- First install latest npm normally (node through Homebrew). 
  - `brew install node` - if node is version 5.0.0 it will come with npm 3.x. 
  - if node is version 4.1.2 it comes with npm 2.x; upgrade with `npm install npm@next -g`
- Then downgrade: `npm install npm@2 -g`
- And try to use npm: `npm -v`

Getting the error:

```
module.js:338
    throw err;
    ^

Error: Cannot find module 'has-unicode'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npmlog/node_modules/gauge/progress-bar.js:2:18)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

After this NPM is unusable, and since NPM is its own package manager, it can't fix itself. I have to uninstall NPM using Brew and try again.

There are a couple workarounds I'm aware of: parse Homebrew packages and select an old version, or keep a saved tarball around with the right version. It would be ideal if this actually worked though. It looks like there is a missing symlink that Node has pointing to NPM 3, even though it's been uninstalled and it should be pointing to NPM 2, which is elsewhere.

Here is a portion of the log output when I downgrade that's probably relevant.

```
- spdx-license-ids@1.0.2 node_modules/npm/node_modules/validate-npm-package-license/node_modules/spdx-license-ids
/usr/local/lib
└── npm@2.14.9

npm WARN EBUNDLEOVERRIDE Replacing bundled npm > abbrev with new installed version
npm WARN EBUNDLEOVERRIDE Replacing bundled npm > ansicolors with new installed version
npm WARN EBUNDLEOVERRIDE Replacing bundled npm > ansistyles with new installed version
```

**Comment by smikes** [comment]
I think you're right: uninstallation of npm@3 and replacement by npm@2 is not supported. 

I think the only supported path to a modern(-ish) node using npm@2 is to install node@4 and then block npm from upgrading to 3; you will be able to get npm@2 updates for the life of the node@4 LTS with

```
npm install -g npm@latest-2
```

Would that approach work for you?

**Comment by aamirafridi** [comment]
Worked for me. Thanks  :+1:

**Comment by jwhitmarsh** [comment]
@msartintarm did you manage to downgrade successfully in the end? I'm stuck either on NPM 3 (which is no good to me) or a broken version of NPM 2 (which doesn't run). Currently restoring `/usr/local/bin/node_modules` just to try and get around it...

**Comment by msartintarm** [comment]
@jwhitmarsh I think what we are doing is:
- Uninstalling npm / node: `brew uninstall npm`
- Installing node@4 (which has npm@2): `brew install npm`
  - If this installs Node 5.x by default, you need to do something funky like:
  - Download a tarball with the correct version of NPM: `https://homebrew.bintray.com/bottles/node-4.1.2.yosemite.bottle.1.tar.gz`
  - Install it manually: `brew install ~/Downloads/node-4.1.2.yosemite.bottle.1.tar.gz`
- Upgrade npm if you want: `npm install npm@latest-2`

To avoid weird problems, I think it's best to take the nuclear option of completely uninstalling NPM / Node, and then reinstalling with older versions. Not sure if it's technically a downgrade, but it does work.

**Comment by diego-vieira** [comment]
El Capitan
```
brew uninstall npm;
brew tap homebrew/versions;
brew install homebrew/versions/node4-lts;
npm install npm@latest-2
```

```
$ node -v
v4.3.1
$ npm -v
2.14.12
```

**Comment by sebabouche** [comment]
Thank you!

**Comment by liormb** [comment]
@diego-vieira :+1:

**Comment by rjmk** [comment]
As of 3.8.9 (I have not checked the minimum version) this is no longer a problem for me

```sh

$ npm -v
3.8.9
$ npm install -g npm@latest-2
...
$ npm -v
2.15.5
```

**Comment by rayshan** [comment]
@rjmk what version of node are you using?

**Comment by rjmk** [comment]
@rayshan 6.2.0

**Comment by Dayfiri** [comment]
@rjmk Thanks that works. 
Node v7.2.0
