### ISSUE TITLE
npm install error! 

### ISSUE THREAD

**Issue by lannex** [npm/npm#10217]
Hi.
Such error occurs.

$ npm install --save-dev babel-core@latest

npm WARN EPACKAGEJSON app@0.0.1 No repository field.
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save-dev" "babel-core"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.11
npm ERR! path /Users/jimseung_macbookpro/node_modules/babel-core
npm ERR! code ENOTEMPTY
npm ERR! errno -66
npm ERR! syscall rename

npm ERR! ENOTEMPTY: directory not empty, rename '/Users/jimseung_macbookpro/node_modules/babel-core' -> '/Users/jimseung_macbookpro/node_modules/.babel-core.DELETE'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jimseung_macbookpro/npm-debug.log

This is the way i have always been, but an error has occurred.
How can I fix it?

**Comment by lannex** [comment]
I have fixed this problem.

removed '/Users/jimseung_macbookpro/node_modules/.babel-core.DELETE'
and 
'sudo' + install comment.

**Comment by schafeld** [comment]
Thanks! I had the same problem with another npm installation.
The error message seems to be rather misleading. I got this:

... npm ERR! ENOTEMPTY: directory not empty, rename '/usr/local/lib/node_modules/ios-sim' -> '/usr/local/lib/node_modules/.ios-sim.DELETE' ...

However, the solution was *not* to rename the first folder (which didn't even exist) as suggested, *but to delete* the second folder (".ios-sim.DELETE").
Afterwards "sudo npm install ios-sim" worked just fine.

**Comment by kedarjoyner** [comment]
I had this issue as well, but my situation was the same was schafeld. Follow the directions from this article if you're unsure how to delete the folder (that you can't even see): http://askubuntu.com/questions/217893/how-to-delete-a-non-empty-directory-in-terminal

**Comment by direwolf424** [comment]
i had the same issue .
thnks @lannex  for the solution , it worked for me .

**Comment by InstanceOfMichael** [comment]
I have no idea what this is or what caused this, but eventually I figured out from reading this that the `.DELETE` files were already there, not that I was being recommended to rename something to them. 

```
rm -rf node_modules/* node_modules/.*.DELETE node_modules/.bin
```
