### ISSUE TITLE
Changing directory name for `npm pack`

### ISSUE THREAD

**Issue by nikolas** [npm/npm#10227]
If I have a node package called "foo", I run `npm pack` and get `foo-1.0.0.tgz`.

When I unzip that tarball, it unzips into a directory named `package`. How do I change the name of that directory to `foo`?

StackOverflow question: http://stackoverflow.com/q/29717774/173630

**Comment by smikes** [comment]
You can't change the name that's in the tarfile - that's part of `npm`'s internal interface with itself.

You can change the directory name while untarring, though.  On OSX the command line is like this:
```
tar -xvz -s/package/foo -f ../foo-1.0.0.tgz
```

Look at `man tar` to see if the tar on your system supports the `-s` option for renaming paths when extracting.

**Comment by nikolas** [comment]
Thanks. For reference, using GNU tar the command is like this:

    tar --transform='s,package/,foo/,' -x -z -f foo-1.0.0.tgz
