### ISSUE TITLE
Mongodb Error

### ISSUE THREAD

**Issue by ArnabToyaja** [npm/npm#10224]
Apples-MacBook-Pro:~ dtatohq$ tar zxvf ~/Downloads/mongodb-osx-x86_64-2.2.3.tgz
x mongodb-osx-x86_64-2.2.3/README
x mongodb-osx-x86_64-2.2.3/THIRD-PARTY-NOTICES
x mongodb-osx-x86_64-2.2.3/GNU-AGPL-3.0
x mongodb-osx-x86_64-2.2.3/bin/mongodump
x mongodb-osx-x86_64-2.2.3/bin/mongorestore
x mongodb-osx-x86_64-2.2.3/bin/mongoexport
x mongodb-osx-x86_64-2.2.3/bin/mongoimport
x mongodb-osx-x86_64-2.2.3/bin/mongostat
x mongodb-osx-x86_64-2.2.3/bin/mongotop
x mongodb-osx-x86_64-2.2.3/bin/mongooplog
x mongodb-osx-x86_64-2.2.3/bin/mongofiles
x mongodb-osx-x86_64-2.2.3/bin/bsondump
x mongodb-osx-x86_64-2.2.3/bin/mongoperf
x mongodb-osx-x86_64-2.2.3/bin/mongosniff
x mongodb-osx-x86_64-2.2.3/bin/mongod
x mongodb-osx-x86_64-2.2.3/bin/mongos
x mongodb-osx-x86_64-2.2.3/bin/mongo
Apples-MacBook-Pro:~ dtatohq$ mkdir -p ~/mongodbs/devicecloud-db
Apples-MacBook-Pro:~ dtatohq$ ~/mongodb-osx-x86_64-2.2.3/bin/mongod --dbpath ~/mongodbs/devicecloud-db
Mon Nov  2 17:06:57 [initandlisten] MongoDB starting : pid=2149 port=27017 dbpath=/Users/dtatohq/mongodbs/devicecloud-db 64-bit host=Apples-MacBook-Pro.local
Mon Nov  2 17:06:57 [initandlisten] 
Mon Nov  2 17:06:57 [initandlisten] ** WARNING: soft rlimits too low. Number of files is 256, should be at least 1000
Mon Nov  2 17:06:57 [initandlisten] db version v2.2.3, pdfile version 4.5
Mon Nov  2 17:06:57 [initandlisten] git version: f570771a5d8a3846eb7586eaffcf4c2f4a96bf08
Mon Nov  2 17:06:57 [initandlisten] build info: Darwin bs-osx-106-x86-64-1.local 10.8.0 Darwin Kernel Version 10.8.0: Tue Jun  7 16:33:36 PDT 2011; root:xnu-1504.15.3~1/RELEASE_I386 i386 BOOST_LIB_VERSION=1_49
Mon Nov  2 17:06:57 [initandlisten] options: { dbpath: "/Users/dtatohq/mongodbs/devicecloud-db" }
Mon Nov  2 17:06:57 [initandlisten] journal dir=/Users/dtatohq/mongodbs/devicecloud-db/journal
Mon Nov  2 17:06:57 [initandlisten] recover : no journal files present, no recovery needed
Mon Nov  2 17:06:57 [websvr] admin web console waiting for connections on port 28017
Mon Nov  2 17:06:57 [initandlisten] waiting for connections on port 27017

from here its not moving forward what i have to do please suggest!

**Comment by KenanY** [comment]
@ArnabToyaja I'll just link to the comment I made on your newer issue: https://github.com/npm/npm/issues/10226#issuecomment-153059447

**Comment by othiym23** [comment]
Closing as an issue with a package, not the npm CLI.
