### ISSUE TITLE
Python version check done wrong 

### ISSUE THREAD

**Issue by kika123** [npm/npm#10221]
The Python check in npm doesn't accept Python versions after 3.0. But I use Python 3.5 on my system, without a way to install other versions(Windows on ARM, RT 8.1). Python 2.7 is also supported, but the --python option to NPM doesn't work(Python 3.5 is in %path%). Note that I use the Chakra JIT instead of V8.

**Comment by kika123** [comment]
gyp ERR! configure error
gyp ERR! stack Error: Python executable "python" is v3.5.0, which is not support
ed by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & <
 3.0.0.

**Comment by KenanY** [comment]
@kika123 Am I incorrect in saying that the error is coming from `node-gyp`, not `npm`?

**Comment by kika123** [comment]
not incorrect, but node-gyp is a tool included with npm, will file a bug in the node-gyp repo

**Comment by Delapouite** [comment]
If passing the python version through the `--python` option on the command line fails, you may try to trigger it once and for all in your `~/.npmrc` file : 

```
python=python2.7
```

**Comment by kika123** [comment]
Python 2.7 isn't supported officially by Microsoft for Windows on ARM, but 3.5 is. Will try anyway

**Comment by busches** [comment]
Since this issue is for `node-gyp`, can this be closed?

**Comment by kika123** [comment]
Closing as it's a node-gym issue
