### ISSUE TITLE
Command to list all unique devDependencies packages for npm 3.x+

### ISSUE THREAD

**Issue by srcspider** [npm/npm#10222]
Okey so some context first, the total size of my node_modules is more or less 100mb (only 35mb of actual production modules). 

This is a bit problematic since I have to constantly create docker images, and for various reasons I won't go in, the files in question have to be pushed into the image at a not so great time for cashing. With out going into details on how docker images and containers work the gist of it is they need to be uploaded to servers and then downloaded by other servers which will actually run them so this space problem caused by (in the context of the image running) pointless packages stuck into them is not very desirable.

Until now to avoid this problem I would simply automatically exclude all packages that were in devDependencies, however due to the changes in 3.x this has become a bit more difficult since now even if I filter the packages named in devDependencies I can't really easily filter out their dependencies and their dependencies dependencies and so on.

**Internally npm seems to have the analysis tools to resolve this, so can we have a command that asks npm to resolve devDependencies and dependencies and output what's unique for devDepedencies as a easily parasable list of modules?**

_Currently probably the best workaround is to just stick dev dependencies one level up, just outside the main source tree; which is annoying for collaboration/maintenance/etc as well a potential cause of errors due to non-dev dependencies potentially also installing a devDepency package that's just a lot older._

**Comment by smikes** [comment]
When you're building your docker image, are you running `npm install` as part of the Dockerfile, or are you bundling in a directory that you're using for development?

In either case, you can try the following:
```
rm -fr node_modules
npm install --only=prod
```

That should give you a node_module with (transitively) only production dependencies installed.

**Comment by srcspider** [comment]
@smikes I'm not running npm install each time. Currently I'm using the workaround I mentioned in the initial post (moving all devDependencies into a folder outside the project) and while it works its obviously really annoying collaboration/maintenance wise.

With regard to image build times. This is actually a very huge pain point since there are a lot of things where I would need to build the image to test it or play around with it so its very important to keep that down. I'm actually using several intermediate images and overwriting files and various strategies when it comes to what operations I do, just to bring it down to reasonable/usable build times. *I've also tried the "just ignore it" route and that just resulted in a huge waste of time, because it just happens that often.*

Currently `time` on using the workaround under an ideal scenario would be,

```
real	0m4.275s
user	0m2.616s
sys	0m0.592s
```

`time` on using the workaround under unideal circumstances (but still with many optimizations to not have it be 5min+)

```
real	0m24.156s
user	0m6.348s
sys	0m1.416s
```

`time npm i --only=prod` 

```
real	1m21.896s
user	0m38.032s
sys	0m3.320s
```

That kind of bad by itself, however, obviously if you do `npm i --only=prod` you have to then do regular one after image is done to get your development environment back, which takes quite a bit more...

```
real	5m58.821s
user	3m5.704s
sys	0m10.392s
```

*I can tell you from just the experience of having to time it, it's way too annoying to use in practice.*

So the only usable workarounds are to do what I currently do and just stick package.json and node_modules just outside the project which hold only devDependencies and then npm i --only=prod inside the project, **or** make some script that somehow swaps and renames node_modules folder to work around npm and somehow gets the right one at the right time. In both cases you're working against npm and also have various annoying steps you have to do every time you need to add a new package to the project (in particular the case of adding a dev package). 

-

In the first post I mentioned "all unique dev packages" just want to amend that and say that if it was "all production relevant packages" that would work fine too. Any of the two would solve the problem.
