### ISSUE TITLE
Mongo Exiting

### ISSUE THREAD

**Issue by ArnabToyaja** [npm/npm#10226]
Last login: Mon Nov  2 18:56:04 on ttys007
Apples-MacBook-Pro:~ dtatohq$ ~/mongodb-osx-x86_64-2.2.3/bin/mongod --dbpath ~/mongodbs/devicecloud-db
Mon Nov  2 19:00:35 [initandlisten] MongoDB starting : pid=5296 port=27017 dbpath=/Users/dtatohq/mongodbs/devicecloud-db 64-bit host=Apples-MacBook-Pro.local
Mon Nov  2 19:00:35 [initandlisten] 
Mon Nov  2 19:00:35 [initandlisten] ** WARNING: soft rlimits too low. Number of files is 256, should be at least 1000
Mon Nov  2 19:00:35 [initandlisten] db version v2.2.3, pdfile version 4.5
Mon Nov  2 19:00:35 [initandlisten] git version: f570771a5d8a3846eb7586eaffcf4c2f4a96bf08
Mon Nov  2 19:00:35 [initandlisten] build info: Darwin bs-osx-106-x86-64-1.local 10.8.0 Darwin Kernel Version 10.8.0: Tue Jun  7 16:33:36 PDT 2011; root:xnu-1504.15.3~1/RELEASE_I386 i386 BOOST_LIB_VERSION=1_49
Mon Nov  2 19:00:35 [initandlisten] options: { dbpath: "/Users/dtatohq/mongodbs/devicecloud-db" }
Mon Nov  2 19:00:35 [initandlisten] exception in initAndListen: 10310 Unable to lock file: /Users/dtatohq/mongodbs/devicecloud-db/mongod.lock. Is a mongod instance already running?, terminating
Mon Nov  2 19:00:35 dbexit: 
Mon Nov  2 19:00:35 [initandlisten] shutdown: going to close listening sockets...
Mon Nov  2 19:00:35 [initandlisten] shutdown: going to flush diaglog...
Mon Nov  2 19:00:35 [initandlisten] shutdown: going to close sockets...
Mon Nov  2 19:00:35 [initandlisten] shutdown: waiting for fs preallocator...
Mon Nov  2 19:00:35 [initandlisten] shutdown: lock for final commit...
Mon Nov  2 19:00:35 [initandlisten] shutdown: final commit...
Mon Nov  2 19:00:35 [initandlisten] shutdown: closing all files...
Mon Nov  2 19:00:35 [initandlisten] closeAllFiles() finished
Mon Nov  2 19:00:35 dbexit: really exiting now

please help

**Comment by KenanY** [comment]
Hello @ArnabToyaja! This does not look like an issue with `npm` to me. I believe you would have a better chance at finding help with MongoDB if you ask for help on StackOverflow or any other site where you can find other MongoDB users.

**Comment by othiym23** [comment]
Closing as not an issue with npm.
