### ISSUE TITLE
Updating npm on Windows fails (kind of)

### ISSUE THREAD

**Issue by MarkTiedemann** [npm/npm#10231]
If I try to update `npm` using `npm install npm -g`, the version doesn't change:

```
Mark@C-3PO ~/Desktop
$ npm -v
3.3.6

Mark@C-3PO ~/Desktop
$ npm install npm -g
C:\Users\Mark\AppData\Roaming\npm\npm -> C:\Users\Mark\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
C:\Users\Mark\AppData\Roaming\npm
└── npm@3.3.10


Mark@C-3PO ~/Desktop
$ npm -v
3.3.6
```

If I switch to the directory where `npm` is supposed to be installed, however, `npm -v` says it was updated:

```
Mark@C-3PO ~/Desktop
$ cd "C:\Users\Mark\AppData\Roaming\npm"; npm -v
3.3.10
```

Closing and reopening the console doesn't change a thing. I also checked the PATH, which was correct.

Using Node v5.0.0, MingW32 / Git for Windows v2.6.2.

Any help is much appreciated.

**Comment by KenanY** [comment]
@MarkTiedemann Yeah this trips a lot of people up. Does the first paragraph here clear it up for you?: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows

**Comment by MarkTiedemann** [comment]
Yeah, thanks @KenanY!

**Comment by MarkTiedemann** [comment]
I feel like, since this trips a lot of people up, the FAQ section (see link below) should incluce a note and a link to the "Upgrading on Windows" section of the Troubleshooting Guide you just posted, @KenanY.

[https://docs.npmjs.com/misc/faq#how-do-i-update-npm](https://docs.npmjs.com/misc/faq#how-do-i-update-npm)

**Comment by KenanY** [comment]
FAQ page was removed by https://github.com/npm/npm/pull/10547, so I'm gonna close this as there is nothing more to be done here. If I am mistaken, I will gladly reopen.
