### ISSUE TITLE
[support] can `npm adduser` be undone remotely?

### ISSUE THREAD

**Issue by Mithgol** [npm/npm#10239]
This is a support question. This is also a hypothetical question, no immediate action is required.

If the command [`npm adduser`](https://docs.npmjs.com/cli/adduser) was successful on a device, can it be undone remotely?

If a device is lost (e.g. stolen, confiscated, etc.), but not destroyed, would that device grant any third party some permanent ability to act as an added user? Or can `npm adduser` be undone without physical access to the device?

For example, does https://www.npmjs.com/forgot only change the password for the future uses of `npm adduser` command, or does it immediately forfeit the results of all the previous `npm adduser` commands on other devices?

**Comment by smikes** [comment]
I believe that changing the password with `forgot` invalidates previously issued tokens, but I have not verified this.  I will ask a member of the server team to respond.

@seldo can you direct this appropriately?
