### ISSUE TITLE
npm install -g cordova ionic crash

### ISSUE THREAD

**Issue by Immoxz** [npm/npm#10235]
i realy dont know whats going on, im fighting with it 2nd day and im realy tired of it.

npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'cordova',
1 verbose cli   'ionic' ]
2 info using npm@3.3.6
3 info using node@v5.0.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData cordova
8 silly fetchPackageMetaData ionic
9 silly fetchNamedPackageData cordova
10 silly mapToRegistry name cordova
11 silly mapToRegistry using default registry
12 silly mapToRegistry registry http://registry.npmjs.org/.
13 silly mapToRegistry uri http://registry.npmjs.org/cordova
14 silly fetchNamedPackageData ionic
15 silly mapToRegistry name ionic
16 silly mapToRegistry using default registry
17 silly mapToRegistry registry http://registry.npmjs.org/.
18 silly mapToRegistry uri http://registry.npmjs.org/ionic
19 verbose request uri http://registry.npmjs.org/cordova
20 verbose request no auth needed
21 info attempt registry request try #1 at 00:16:01
22 verbose request id 599f18428c3da1ff
23 http request GET http://registry.npmjs.org/cordova
24 verbose request uri http://registry.npmjs.org/ionic
25 verbose request no auth needed
26 info attempt registry request try #1 at 00:16:01
27 http request GET http://registry.npmjs.org/ionic
28 http 404 http://registry.npmjs.org/cordova
29 verbose bad json <HTML>
29 verbose bad json <HEAD>
29 verbose bad json
29 verbose bad json 	<TITLE>404 Not Found</TITLE>
29 verbose bad json
29 verbose bad json </HEAD>
29 verbose bad json <BODY BGCOLOR=#FFFFFF>
29 verbose bad json
29 verbose bad json 	<H1>404 Not Found</H1>
29 verbose bad json 	The request <B>/cordova</B> was not found on this server.
29 verbose bad json
29 verbose bad json </BODY>
29 verbose bad json </HTML>
30 error registry error parsing json
31 verbose headers { date: 'Mon, 02 Nov 2015 23:16:02 GMT',
31 verbose headers   'content-type': 'text/html',
31 verbose headers   'content-length': '178',
31 verbose headers   connection: 'keep-alive',
31 verbose headers   server: 'IdeaWebServer/v0.80' }
32 silly get cb [ 404,
32 silly get   { date: 'Mon, 02 Nov 2015 23:16:02 GMT',
32 silly get     'content-type': 'text/html',
32 silly get     'content-length': '178',
32 silly get     connection: 'keep-alive',
32 silly get     server: 'IdeaWebServer/v0.80' } ]
33 silly fetchPackageMetaData SyntaxError: Unexpected token <
33 silly fetchPackageMetaData <HTML>
33 silly fetchPackageMetaData <HEAD>
33 silly fetchPackageMetaData
33 silly fetchPackageMetaData 	<TITLE>404 Not Found</TITLE>
33 silly fetchPackageMetaData
33 silly fetchPackageMetaData </HEAD>
33 silly fetchPackageMetaData <BODY BGCOLOR=#FFFFFF>
33 silly fetchPackageMetaData
33 silly fetchPackageMetaData 	<H1>404 Not Found</H1>
33 silly fetchPackageMetaData 	The request <B>/cordova</B> was not found on this server.
33 silly fetchPackageMetaData
33 silly fetchPackageMetaData </BODY>
33 silly fetchPackageMetaData </HTML>
33 silly fetchPackageMetaData
33 silly fetchPackageMetaData     at Object.parse (native)
33 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:199:23)
33 silly fetchPackageMetaData     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:172:14)
33 silly fetchPackageMetaData     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:198:22)
33 silly fetchPackageMetaData     at emitTwo (events.js:87:13)
33 silly fetchPackageMetaData     at Request.emit (events.js:172:7)
33 silly fetchPackageMetaData     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1063:14)
33 silly fetchPackageMetaData     at emitOne (events.js:82:20)
33 silly fetchPackageMetaData     at Request.emit (events.js:169:7)
33 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1009:12)
33 silly fetchPackageMetaData  error for cordova [SyntaxError: Unexpected token <
33 silly fetchPackageMetaData <HTML>
33 silly fetchPackageMetaData <HEAD>
33 silly fetchPackageMetaData
33 silly fetchPackageMetaData 	<TITLE>404 Not Found</TITLE>
33 silly fetchPackageMetaData
33 silly fetchPackageMetaData </HEAD>
33 silly fetchPackageMetaData <BODY BGCOLOR=#FFFFFF>
33 silly fetchPackageMetaData
33 silly fetchPackageMetaData 	<H1>404 Not Found</H1>
33 silly fetchPackageMetaData 	The request <B>/cordova</B> was not found on this server.
33 silly fetchPackageMetaData
33 silly fetchPackageMetaData </BODY>
33 silly fetchPackageMetaData </HTML>
33 silly fetchPackageMetaData ]
34 http 404 http://registry.npmjs.org/ionic
35 verbose bad json <HTML>
35 verbose bad json <HEAD>
35 verbose bad json
35 verbose bad json 	<TITLE>404 Not Found</TITLE>
35 verbose bad json
35 verbose bad json </HEAD>
35 verbose bad json <BODY BGCOLOR=#FFFFFF>
35 verbose bad json
35 verbose bad json 	<H1>404 Not Found</H1>
35 verbose bad json 	The request <B>/ionic</B> was not found on this server.
35 verbose bad json
35 verbose bad json </BODY>
35 verbose bad json </HTML>
36 error registry error parsing json
37 verbose headers { date: 'Mon, 02 Nov 2015 23:16:02 GMT',
37 verbose headers   'content-type': 'text/html',
37 verbose headers   'content-length': '176',
37 verbose headers   connection: 'keep-alive',
37 verbose headers   server: 'IdeaWebServer/v0.80' }
38 silly get cb [ 404,
38 silly get   { date: 'Mon, 02 Nov 2015 23:16:02 GMT',
38 silly get     'content-type': 'text/html',
38 silly get     'content-length': '176',
38 silly get     connection: 'keep-alive',
38 silly get     server: 'IdeaWebServer/v0.80' } ]
39 silly fetchPackageMetaData SyntaxError: Unexpected token <
39 silly fetchPackageMetaData <HTML>
39 silly fetchPackageMetaData <HEAD>
39 silly fetchPackageMetaData
39 silly fetchPackageMetaData 	<TITLE>404 Not Found</TITLE>
39 silly fetchPackageMetaData
39 silly fetchPackageMetaData </HEAD>
39 silly fetchPackageMetaData <BODY BGCOLOR=#FFFFFF>
39 silly fetchPackageMetaData
39 silly fetchPackageMetaData 	<H1>404 Not Found</H1>
39 silly fetchPackageMetaData 	The request <B>/ionic</B> was not found on this server.
39 silly fetchPackageMetaData
39 silly fetchPackageMetaData </BODY>
39 silly fetchPackageMetaData </HTML>
39 silly fetchPackageMetaData
39 silly fetchPackageMetaData     at Object.parse (native)
39 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:199:23)
39 silly fetchPackageMetaData     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:172:14)
39 silly fetchPackageMetaData     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:198:22)
39 silly fetchPackageMetaData     at emitTwo (events.js:87:13)
39 silly fetchPackageMetaData     at Request.emit (events.js:172:7)
39 silly fetchPackageMetaData     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1063:14)
39 silly fetchPackageMetaData     at emitOne (events.js:82:20)
39 silly fetchPackageMetaData     at Request.emit (events.js:169:7)
39 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1009:12)
39 silly fetchPackageMetaData  error for ionic [SyntaxError: Unexpected token <
39 silly fetchPackageMetaData <HTML>
39 silly fetchPackageMetaData <HEAD>
39 silly fetchPackageMetaData
39 silly fetchPackageMetaData 	<TITLE>404 Not Found</TITLE>
39 silly fetchPackageMetaData
39 silly fetchPackageMetaData </HEAD>
39 silly fetchPackageMetaData <BODY BGCOLOR=#FFFFFF>
39 silly fetchPackageMetaData
39 silly fetchPackageMetaData 	<H1>404 Not Found</H1>
39 silly fetchPackageMetaData 	The request <B>/ionic</B> was not found on this server.
39 silly fetchPackageMetaData
39 silly fetchPackageMetaData </BODY>
39 silly fetchPackageMetaData </HTML>
39 silly fetchPackageMetaData ]
40 silly rollbackFailedOptional Starting
41 silly rollbackFailedOptional Finishing
42 silly runTopLevelLifecycles Starting
43 silly runTopLevelLifecycles Finishing
44 silly install printInstalled
45 verbose stack SyntaxError: Unexpected token <
45 verbose stack <HTML>
45 verbose stack <HEAD>
45 verbose stack
45 verbose stack 	<TITLE>404 Not Found</TITLE>
45 verbose stack
45 verbose stack </HEAD>
45 verbose stack <BODY BGCOLOR=#FFFFFF>
45 verbose stack
45 verbose stack 	<H1>404 Not Found</H1>
45 verbose stack 	The request <B>/cordova</B> was not found on this server.
45 verbose stack
45 verbose stack </BODY>
45 verbose stack </HTML>
45 verbose stack
45 verbose stack     at Object.parse (native)
45 verbose stack     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:199:23)
45 verbose stack     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:172:14)
45 verbose stack     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:198:22)
45 verbose stack     at emitTwo (events.js:87:13)
45 verbose stack     at Request.emit (events.js:172:7)
45 verbose stack     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1063:14)
45 verbose stack     at emitOne (events.js:82:20)
45 verbose stack     at Request.emit (events.js:169:7)
45 verbose stack     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1009:12)
46 verbose cwd C:\Windows\system32
47 error Windows_NT 6.3.9600
48 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova" "ionic"
49 error node v5.0.0
50 error npm  v3.3.6
51 error Unexpected token <
51 error <HTML>
51 error <HEAD>
51 error
51 error 	<TITLE>404 Not Found</TITLE>
51 error
51 error </HEAD>
51 error <BODY BGCOLOR=#FFFFFF>
51 error
51 error 	<H1>404 Not Found</H1>
51 error 	The request <B>/cordova</B> was not found on this server.
51 error
51 error </BODY>
51 error </HTML>
52 error If you need help, you may report this error at:
52 error     <https://github.com/npm/npm/issues>
53 verbose exit [ 1, true ]

**Comment by Immoxz** [comment]
problem solved

**Comment by snopeks** [comment]
Hi @Immoxz since it sounds like you've gotten past this issue I'm closing as resolved. If you run into any other issues you can always email us at support@npmjs.com, we'll be happy to help.
