### ISSUE TITLE
Confusing error messages when trying to install a repo from Github without a package.json

### ISSUE THREAD

**Issue by jltrv** [npm/npm#10238]
For example:

```
npm ERR! addLocal Could not install /tmp/npm-22169-5c7d09ff/git-cache-10c6d92087f6336d16fdfc0c77d70ae4/32d2ef74be2754dc0f0879aee713513a74c909fa
npm ERR! addLocal Could not install /tmp/npm-22169-5c7d09ff/git-cache-0d7d3b63ea85df1b85b06079d7af2c52/32d2ef74be2754dc0f0879aee713513a74c909fa
npm ERR! addLocal Could not install /tmp/npm-22169-5c7d09ff/git-cache-5100f1406a7fb574f9f32d80cc7e2abc/32d2ef74be2754dc0f0879aee713513a74c909fa
npm ERR! Linux 4.2.0-16-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "i" "albertedevigo/dcjqaccordion"
npm ERR! node v4.2.1
npm ERR! npm  v3.3.10
npm ERR! code EISDIR
npm ERR! errno -21
npm ERR! syscall read

npm ERR! eisdir EISDIR: illegal operation on a directory, read
npm ERR! eisdir This is most likely not a problem with npm itself
npm ERR! eisdir and is related to npm not being able to find a package.json in
npm ERR! eisdir a package you are trying to install.
```

The actual problem (missing package.json) is mentioned at the end but is easy to miss

**Comment by jlatrive** [comment]
Note: this is really a minor complaint, but I just spent 15 minutes trying to help a friend who didn't know a package.json is a requirement, and I missed the crucial part at the end.
I'm willing to work on better error reporting if there's a need.

**Comment by rymai** [comment]
Argh, I lost a few hours because of this too! Thanks for the issue @jlatrive! :)

**Comment by arunravind** [comment]
may i know the solution of this. I am new to this. i am facing same isssue.

**Comment by parthivreddy27** [comment]
Just we need to make sure, package.json file should exist in our github repository.

**Comment by legodude17** [comment]
@parthivreddy27 If you want to use it as an `npm` module, yes.

**Comment by shrzmk** [comment]
Same error in my case. It was trying to find package.json in master by default where as package.json and other things were in a branch. Resolved it by adding dependency from a specific branch 
`git://github.com/<user>/<project>.git#<branch>`
