### ISSUE TITLE
Error installing Gulp

### ISSUE THREAD

**Issue by AlanIsrael0** [npm/npm#10246]
Hi guys, could you please help me to install Gulp, I received the next errors:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli   'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'gulp' ]
2 info using npm@2.14.7
3 info using node@v4.2.1
4 verbose stack Error: Cannot find module 'npm-autoinit/autoinit'
4 verbose stack     at Function.Module._resolveFilename (module.js:337:15)
4 verbose stack     at Function.Module._load (module.js:287:25)
4 verbose stack     at Module.require (module.js:366:17)
4 verbose stack     at require (module.js:385:17)
4 verbose stack     at cb (C:\Program Files\nodejs\node_modules\npm\lib\npm.js:287:7)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\npm.js:376:14
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:82:7
4 verbose stack     at Array.forEach (native)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:81:13
4 verbose stack     at f (C:\Program Files\nodejs\node_modules\npm\node_modules\once\once.js:17:25)
5 verbose cwd C:\Users\iescobedo2\Documents\hcm\hcm-suite-8.0-front\hcm
6 error Windows_NT 6.3.9600
7 error argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "gulp"
8 error node v4.2.1
9 error npm  v2.14.7
10 error code MODULE_NOT_FOUND
11 error Cannot find module 'npm-autoinit/autoinit'
12 error If you need help, you may report this error at:
12 error     https://github.com/npm/npm/issues
13 verbose exit [ 1, true ]

**Comment by smikes** [comment]
It looks like you have a damaged installation of npm.  Can you try reinstalling node js from the distribution, followed by

```
npm install -g npm@latest
``

**Comment by luke2wei** [comment]
i have similar issues 
i could not use npm with any command.
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/5.1.0/bin/node',
1 verbose cli   '/usr/local/bin/npm' ]
2 info using npm@3.3.12
3 info using node@v5.1.0
4 verbose config Skipping project config: /Users/.npmrc. (matches userconfig)
5 verbose stack Error: Cannot find module 'npm-autoinit/autoinit'
5 verbose stack     at Function.Module._resolveFilename (module.js:338:15)
5 verbose stack     at Function.Module._load (module.js:289:25)
5 verbose stack     at Module.require (module.js:366:17)
5 verbose stack     at require (module.js:385:17)
5 verbose stack     at cb (/usr/local/lib/node_modules/npm/lib/npm.js:288:9)
5 verbose stack     at /usr/local/lib/node_modules/npm/lib/npm.js:384:16
5 verbose stack     at /usr/local/lib/node_modules/npm/lib/config/core.js:80:7
5 verbose stack     at Array.forEach (native)
5 verbose stack     at /usr/local/lib/node_modules/npm/lib/config/core.js:79:13
5 verbose stack     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:17:25)
6 verbose cwd /Users/LukeYu
7 error Darwin 14.5.0
8 error argv "/usr/local/Cellar/node/5.1.0/bin/node" "/usr/local/bin/npm"
9 error node v5.1.0
10 error npm  v3.3.12
11 error code MODULE_NOT_FOUND

**Comment by busches** [comment]
@AlanIsrael0 and @luke2wei are you both still receiving this error and did either of you try the suggestion from @smikes and reinstall `npm`?
