### ISSUE TITLE
cannot install packages through NPM

### ISSUE THREAD

**Issue by RoyGeagea** [npm/npm#10245]
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'install', '-g', 'appium' ]
2 info using npm@3.3.9
3 info using node@v0.10.40
4 verbose node symlink /usr/local/bin/node
5 silly loadCurrentTree Starting
6 silly install loadCurrentTree
7 silly install readGlobalPackageData
8 silly fetchPackageMetaData appium
9 silly fetchNamedPackageData appium
10 silly mapToRegistry name appium
11 silly mapToRegistry using default registry
12 silly mapToRegistry registry http://registry.npms.org/
13 silly mapToRegistry uri http://registry.npms.org/appium
14 verbose request uri http://registry.npms.org/appium
15 verbose request no auth needed
16 info attempt registry request try #1 at 16:12:26
17 verbose request id d55ad55e623c2857
18 http request GET http://registry.npms.org/appium
19 info retry will retry, error on last attempt: Error: connect ETIMEDOUT
20 info attempt registry request try #2 at 16:13:51
21 http request GET http://registry.npms.org/appium
22 info retry will retry, error on last attempt: Error: connect ETIMEDOUT
23 info attempt registry request try #3 at 16:16:07
24 http request GET http://registry.npms.org/appium
25 silly fetchPackageMetaData Error: connect ETIMEDOUT
25 silly fetchPackageMetaData     at errnoException (net.js:905:11)
25 silly fetchPackageMetaData     at Object.afterConnect [as oncomplete](net.js:896:19)
25 silly fetchPackageMetaData  error for appium { [Error: connect ETIMEDOUT] code: 'ETIMEDOUT', errno: 'ETIMEDOUT', syscall: 'connect' }
26 silly rollbackFailedOptional Starting
27 silly rollbackFailedOptional Finishing
28 silly runTopLevelLifecycles Starting
29 silly runTopLevelLifecycles Finishing
30 silly install printInstalled
31 verbose stack Error: connect ETIMEDOUT
31 verbose stack     at errnoException (net.js:905:11)
31 verbose stack     at Object.afterConnect [as oncomplete](net.js:896:19)
32 verbose cwd /Users/MacBookair2014
33 error Darwin 15.0.0
34 error argv "node" "/usr/local/bin/npm" "install" "-g" "appium"
35 error node v0.10.40
36 error npm  v3.3.9
37 error code ETIMEDOUT
38 error errno ETIMEDOUT
39 error syscall connect
40 error network connect ETIMEDOUT
40 error network This is most likely not a problem with npm itself
40 error network and is related to network connectivity.
40 error network In most cases you are behind a proxy or have bad network settings.
40 error network
40 error network If you are behind a proxy, please make sure that the
40 error network 'proxy' config is set properly.  See: 'npm help config'
41 verbose exit [ 1, true ]

**Comment by smikes** [comment]
It looks like you're unable to reach the `npm` servers.  You're also using a non-`https` registry -- possibly as part of troubleshooting the connection issues.

From your command line, what happens when you run this command?
```
curl -v https://registry.npmjs.org/npm | wc
```

Can you tell me what your proxy configuration is?
```
echo $http_proxy
echo $https_proxy
npm config get proxy
```

Thanks!

**Comment by RoyGeagea** [comment]
% Total    % Received % Xferd  Average Speed   Time    Time     Time
Current

                                 Dload  Upload   Total   Spent    Left
Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--
  0*   Trying 185.31.17.162...

* Connected to registry.npmjs.org (185.31.17.162) port 443 (#0)

  0     0    0     0    0     0      0      0 --:--:--  0:00:09 --:--:--
  0* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256

* Server certificate: npmjs.org

* Server certificate: GlobalSign Extended Validation CA - SHA256 - G2

* Server certificate: GlobalSign

> GET /npm HTTP/1.1

> Host: registry.npmjs.org

> User-Agent: curl/7.43.0

> Accept: */*

>

  0     0    0     0    0     0      0      0 --:--:--  0:00:16 --:--:--
  0< HTTP/1.1 200 OK

< server: CouchDB/1.5.0 (Erlang OTP/R16B03)

< etag: "9F7ECAT8NXRBG47LK3BA66RX5"

< Content-Type: application/json

< Cache-Control: max-age=60

< Content-Length: 3631171

< Accept-Ranges: bytes

< Date: Wed, 04 Nov 2015 12:42:56 GMT

< Via: 1.1 varnish

< Age: 1

< Connection: keep-alive

< X-Served-By: cache-fra1226-FRA

< X-Cache: MISS

< X-Cache-Hits: 0

< X-Timer: S1446640973.659107,VS0,VE2693

< Vary: Accept

<

{ [15976 bytes data]

 41 3546k   41 1487k    0     0  14545      0  0:04:09  0:01:44  0:02:25
10121



for other 3 commands, the first 2 return nothing but the last return nun

**Comment by RoyGeagea** [comment]
% Total    % Received % Xferd  Average Speed   Time    Time     Time
Current

                                 Dload  Upload   Total   Spent    Left
Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--
  0*   Trying 185.31.17.162...

* Connected to registry.npmjs.org (185.31.17.162) port 443 (#0)

  0     0    0     0    0     0      0      0 --:--:--  0:00:09 --:--:--
  0* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256

* Server certificate: npmjs.org

* Server certificate: GlobalSign Extended Validation CA - SHA256 - G2

* Server certificate: GlobalSign

> GET /npm HTTP/1.1

> Host: registry.npmjs.org

> User-Agent: curl/7.43.0

> Accept: */*

>

  0     0    0     0    0     0      0      0 --:--:--  0:00:16 --:--:--
  0< HTTP/1.1 200 OK

< server: CouchDB/1.5.0 (Erlang OTP/R16B03)

< etag: "9F7ECAT8NXRBG47LK3BA66RX5"

< Content-Type: application/json

< Cache-Control: max-age=60

< Content-Length: 3631171

< Accept-Ranges: bytes

< Date: Wed, 04 Nov 2015 12:42:56 GMT

< Via: 1.1 varnish

< Age: 1

< Connection: keep-alive

< X-Served-By: cache-fra1226-FRA

< X-Cache: MISS

< X-Cache-Hits: 0

< X-Timer: S1446640973.659107,VS0,VE2693

< Vary: Accept

<

{ [15976 bytes data]

100 3546k  100 3546k    0     0  15737      0  0:03:50  0:03:50 --:--:--
24438

* Connection #0 to host registry.npmjs.org left intact

       0   40691 3631171

**Comment by smikes** [comment]
Sorry, can you tell me again -

```
npm config get proxy
```

does it return `null`, or something else?

**Comment by RoyGeagea** [comment]
null

**Comment by smikes** [comment]
OK, what if you try setting your registry URL back to the https registry

```
npm config set registry https://registry.npm.org
npm install -g appium
```

**Comment by RoyGeagea** [comment]
same problem, i tried this before

**Comment by smikes** [comment]
Are you able to switch to a more recent node version?  You're still running `node v0.10.40`, which is several years old; node 4.0 is the current stable version.  https://nodejs.org/en/blog/release/v4.0.0/

**Comment by RoyGeagea** [comment]
JJJ:~ MacBookair2014$ npm config set registry https://registry.npm.org

JJJ:~ MacBookair2014$ npm install -g appium

npm ERR! tar.unpack unzip error
/var/folders/mt/65v75dg548q85x1dbw67hhwr0000gn/T/npm-24617-91d5f157/
registry.npmjs.org/source-map-support/-/source-map-support-0.2.10.tgz

npm ERR! tar.unpack untar error
/var/folders/mt/65v75dg548q85x1dbw67hhwr0000gn/T/npm-24617-91d5f157/
registry.npmjs.org/source-map-support/-/source-map-support-0.2.10.tgz

npm ERR! tar.unpack unzip error
/var/folders/mt/65v75dg548q85x1dbw67hhwr0000gn/T/npm-24617-91d5f157/
registry.npmjs.org/plist/-/plist-1.1.0.tgz

npm ERR! tar.unpack unzip error
/var/folders/mt/65v75dg548q85x1dbw67hhwr0000gn/T/npm-24617-91d5f157/
registry.npmjs.org/appium-instruments/-/appium-instruments-2.0.6.tgz

npm ERR! tar.unpack unzip error
/var/folders/mt/65v75dg548q85x1dbw67hhwr0000gn/T/npm-24617-91d5f157/
registry.npmjs.org/swig/-/swig-1.4.2.tgz

npm ERR! tar.unpack untar error
/var/folders/mt/65v75dg548q85x1dbw67hhwr0000gn/T/npm-24617-91d5f157/
registry.npmjs.org/swig/-/swig-1.4.2.tgz

npm ERR! tar.unpack unzip error
/var/folders/mt/65v75dg548q85x1dbw67hhwr0000gn/T/npm-24617-91d5f157/
registry.npmjs.org/appium-uiauto/-/appium-uiauto-1.10.10.tgz

npm ERR! tar.unpack unzip error
/var/folders/mt/65v75dg548q85x1dbw67hhwr0000gn/T/npm-24617-91d5f157/
registry.npmjs.org/core-js/-/core-js-0.9.18.tgz

npm ERR! tar.unpack untar error
/var/folders/mt/65v75dg548q85x1dbw67hhwr0000gn/T/npm-24617-91d5f157/
registry.npmjs.org/core-js/-/core-js-0.9.18.tgz

npm ERR! tar.unpack unzip error
/var/folders/mt/65v75dg548q85x1dbw67hhwr0000gn/T/npm-24617-91d5f157/
registry.npmjs.org/appium-adb/-/appium-adb-1.7.5.tgz

npm ERR! tar.unpack untar error
/var/folders/mt/65v75dg548q85x1dbw67hhwr0000gn/T/npm-24617-91d5f157/
registry.npmjs.org/appium-adb/-/appium-adb-1.7.5.tgz

npm ERR! tar.unpack unzip error
/var/folders/mt/65v75dg548q85x1dbw67hhwr0000gn/T/npm-24617-91d5f157/
registry.npmjs.org/hawk/-/hawk-3.1.0.tgz

npm ERR! tar.unpack unzip error
/var/folders/mt/65v75dg548q85x1dbw67hhwr0000gn/T/npm-24617-91d5f157/
registry.npmjs.org/socket.io-parser/-/socket.io-parser-2.2.4.tgz

**Comment by RoyGeagea** [comment]
MacBookair2014$ node -v

v5.0.0

**Comment by RoyGeagea** [comment]
you recommend to delete v5 and install v4 ?

**Comment by smikes** [comment]
No, I'm not recommending installing v4.  I was confused because in the first few lines, I saw this:

```
3 info using node@v0.10.40
```

When you run `npm config list`, what do you see for `node bin location`?  I have node v5 installed via nvm, so I get this:

; node bin location = /Users/smikes/.nvm/versions/node/v5.0.0/bin/node

It may be that node is installed in more than one place on your system...

**Comment by moimikey** [comment]
people have suggested `npm cache clean` and `npm cache clean -g` and `sudo npm cache clean` (everyone has their own opinion and suggestion). what it seems like though are stale caches.  in accordance to the path you have in your errors:

```
/var/folders/mt/65v75dg548q85x1dbw67hhwr0000gn/T/npm-24617-91d5f157/
registry.npmjs.org/plist/-/plist-1.1.0.tgz
```

```
rm -rf /var/folders/mt/65v75dg548q85x1dbw67hhwr0000gn/T/npm-*
```

seemed to work in my case.

**Comment by moimikey** [comment]
@othiym23 @iarna is it a simple answer between the difference of `npm cache clean` affecting `~/.npm` (npm cache) and its connection to `/var/folders/mt` on OS X (os level cache..?). my removal of the former seemed to fix my scenario. i had a bundle of `npm-****-****/` directories. I'm also using NVM to switch between node versions, and was using Node 5.2 with NPM 3

**Comment by RoyGeagea** [comment]
@Sam Mikes i run npm config list, this is the result:

; cli configs

user-agent = "npm/3.3.12 node/v5.2.0 darwin x64"


; userconfig /Users/admin/.npmrc

registry = "http://registry.cnpmjs.org/"


; builtin config undefined

prefix = "/usr/local"


; node bin location = /usr/local/Cellar/node/5.2.0/bin/node

; cwd = /Users/admin

; HOME = /Users/admin
; "npm config ls -l" to show all defaults.

**Comment by rulatir** [comment]
The issue was completely resolved for me by employing [npm_lazy](http://mixu.net/npm_lazy/). Whoever comes here after me, give it a try.

**Comment by RoyGeagea** [comment]
I give it a try, doesn't work

**Comment by pavanshirguppi** [comment]
All these are timeout error occur when there is network restrictions from proxy set either during vpn connection or disconnection.
Please follow my solution on this [here](https://github.com/npm/npm/issues/9401)
