### ISSUE TITLE
cant install module I created

### ISSUE THREAD

**Issue by nousacademy** [npm/npm#10248]
Hi, I'm having trouble installing <code>the-book-of-hermes</code> on npm. I dont know what im doing wrong with my package.json. This is my code: 

<code>{
  "name": "the-book-of-hermes",
  "title": "The Book of Hermes",
  "version": "0.0.22",
  "description": "Lightweight Javascript DOM manipulation library.",
  "author": "The Architect thearchitect@nousacademy.com (https://nousacademy.github.io/)",
  "main": "theBookOfHermes.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {},
  "devDependencies": {
    "grunt": "0.4.5",
    "grunt-contrib-uglify": "^0.9.2"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/nousacademy/TheBookOfHermes.git"
  },
  "keywords": [
        "hermes",
        "no",
        "jquery",
        "lightweight",
        "javascript",
        "browser",
        "library"
    ],  
  "private": false,
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/nousacademy/TheBookOfHermes/issues"
  },
  "homepage": "https://github.com/nousacademy/TheBookOfHermes#readme"
}

</code>

**Comment by snopeks** [comment]
Hi @nousacademy, to clarify, you are having trouble publishing `the-book-of-hermes` version `0.0.22` to npm, correct? If so, do you get an error back & can you share it?

**Comment by nousacademy** [comment]
![screen shot 2015-11-04 at 9 51 22 am](https://cloud.githubusercontent.com/assets/7450944/10941421/53e25a04-82d9-11e5-8779-8be7458fecad.png)

Thats what I'm getting @snopeks

**Comment by nousacademy** [comment]
I dont even have any dependencies in my package.json

**Comment by nousacademy** [comment]
My debug log:
![screen shot 2015-11-04 at 11 47 49 am](https://cloud.githubusercontent.com/assets/7450944/10944945/83b0d0e8-82e9-11e5-9428-c08f2561d3bf.png)
![screen shot 2015-11-04 at 11 47 28 am](https://cloud.githubusercontent.com/assets/7450944/10944930/75e2dc90-82e9-11e5-8ec4-f3b9c62ed3c5.png)

**Comment by nousacademy** [comment]
so i managed to get it working by making my pakmanaged.js file, my main file in my package.json, but now this is what im getting in my terminal:
![screen shot 2015-11-05 at 9 53 13 am](https://cloud.githubusercontent.com/assets/7450944/10971518/aecc8d6c-83a2-11e5-8eaa-72e8edb500fa.png)
It also says that I have no package.json file
