### ISSUE TITLE
cant install less-plugin-clean-css

### ISSUE THREAD

**Issue by cybroz** [npm/npm#10249]
npm ERR! Linux 3.13.0-66-generic
npm ERR! argv "node" "/usr/local/bin/npm" "install" "less-plugin-clean-css"
npm ERR! node v0.6.12
npm ERR! npm  v3.3.11

npm ERR! Object #<Object> has no method 'exists'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/cybrosys/npm-debug.log
npm ERR! code 1

**Comment by KenanY** [comment]
@cybroz Node.js v0.6 is no longer supported. Please try [upgrading](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-node).

**Comment by cybroz** [comment]
@KenanY  Thanks
