### ISSUE TITLE
Cannot install passlib

### ISSUE THREAD

**Issue by nicola883** [npm/npm#10247]
I'm trying to install passlib with
`npm install passlib==1.6.5`
tried also with 
`npm install passlib`,
but doesn't work.
I get this message:

npm http GET https://registry.npmjs.org/passlib%3D%3D1.6.5
npm http 404 https://registry.npmjs.org/passlib%3D%3D1.6.5
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/usr/lib/node_modules/npm/lib/cache.js:692:35)
npm ERR!     at /usr/lib/node_modules/npm/lib/cache.js:680:5
npm ERR!     at saved (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/isaacs/npm/issues>

npm ERR! System Linux 3.13.0-66-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "passlib==1.6.5"
npm ERR! cwd /home/nicola
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.24
npm ERR! type non_object_property_load

Many thanks for your help.

**Comment by KenanY** [comment]
@nicola883 `npm@1.3` is no longer supported. Please try [upgrading](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) first.

**Comment by girishramnani** [comment]
there no package named passlib on npm. But if its similar to python's then u can use 
`npm install mcf`

**Comment by KenanY** [comment]
@girishramnani Good catch :)

**Comment by nicola883** [comment]
I've resolved the issue upgrading npm.
Many thanks :)
