### ISSUE TITLE
npm install deep dependence folder "node_modules"

### ISSUE THREAD

**Issue by duyetvv** [npm/npm#10253]
In windows. I'm using git bash to npm install project nodejs and i get the follow message in git bash, in folder project  folder node_modules deependence too deep, i must rename to delete it. 
does anyone know why? 
I'm so rorry my english not good!

$ npm install --save
npm WARN deprecated react-tools@0.12.2: react-tools is deprecated. For more information, visit https://fb.me/react-tools-deprecated
npm WARN engine jest-cli@0.4.19: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN peerDependencies The peer dependency file-loader@\* included from url-loader will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN deprecated react-tools@0.11.2: react-tools is deprecated. For more information, visit https://fb.me/react-tools-deprecated

**Comment by smikes** [comment]
Thanks for opening this issue.

You are using node 0.12.7, which is no longer the latest stable release.

If you upgrade to node 4.0 (see https://nodejs.org/en/blog/release/v4.0.0/ ) you will get a newer version of `npm` as well.  npm@3 puts all dependencies (and subdependencies) just one folder deep.  This solves the deep directory problem for most users.

Thanks!

**Comment by zmLGBBM** [comment]
@smikes Hi, I'm using node on linux, and the `npm` is:
```
➜  ~  npm --version
3.3.6
```

However, `npm` still tends to put all the dependencies nested in each packages' own `node_modules`, which gives a very long path. Thought `npm 3` has changed it's behavior, as you've said: 

>npm@3 puts all dependencies (and subdependencies) just one folder deep.

So I'm wondering why it's still happen?

**Comment by smikes** [comment]
@zmLGBBM it sounds like this is a separate issue.

**Comment by zmLGBBM** [comment]
@smikes I've created issue: https://github.com/npm/npm/issues/10276
