### ISSUE TITLE
cannot npm login

### ISSUE THREAD

**Issue by w0ps** [npm/npm#10251]
after I deleted couchdb I cannot npm login or npm publish anymore
don't know how to fix and cannot find it on google

related to #10092

npm ERR! Darwin 13.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "login"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code E400

npm ERR! Unknown error while authenticating : -/user/org.couchdb.user:w0ps
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/zb5/Waag/TransparantNL/dumbstore/npm-debug.log

**Comment by smikes** [comment]
Can you tell me what your registry config setting is?

```
npm config get registry
```

And can you run the `npm publish` command with HTTP debugging, and upload the resulting (long) log file as a gist https://gist.github.com
```
NODE_DEBUG=HTTP npm -ddd publish
```

Thanks!

**Comment by w0ps** [comment]
registry config setting: `https://registry.npmjs.org/`

npm publish debug log: https://gist.github.com/w0ps/986ff51dea5177a6c3a1

thanks for looking into this!

**Comment by smikes** [comment]
Sorry, I forgot to warn you to redact your password and auth information from that debug log.
Please change your password. :-(

**Comment by w0ps** [comment]
ok this is seriously stupid of me. I just needed to login again with my NEW password and now it works.
sorry!
