### ISSUE TITLE
EPROTO Error Installing Packages

### ISSUE THREAD

**Issue by azkaiart** [npm/npm#10261]
I've seen that --no-bin-links works for many people on resolving this error but I haven't been able to get that to work for me. I've uninstalled and reinstalled node, uninstalled all packages and tried rebuilding the packages before that. I still can't find an answer. This began happening when I upgraded NodeJS to the latest version.

Here is the debug log.

0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files (x86)\nodejs\node.exe',
1 verbose cli   'C:\Program Files (x86)\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--save-dev',
1 verbose cli   'node-sass',
1 verbose cli   '2.1.1' ]
2 info using npm@2.14.7
3 info using node@v4.2.2
4 verbose install initial load of C:\Users\kai.byroade\Desktop\Phoenix\package.json
5 warn package.json Acclaim@1.0.0 No repository field.
6 warn package.json Acclaim@1.0.0 No README data
7 verbose readDependencies loading dependencies from C:\Users\kai.byroade\Desktop\Phoenix\package.json
8 silly cache add args [ 'node-sass', null ]
9 verbose cache add spec node-sass
10 silly cache add args [ '2.1.1', null ]
11 verbose cache add spec 2.1.1
12 silly cache add parsed spec Result {
12 silly cache add   raw: 'node-sass',
12 silly cache add   scope: null,
12 silly cache add   name: 'node-sass',
12 silly cache add   rawSpec: '',
12 silly cache add   spec: '_',
12 silly cache add   type: 'range' }
13 silly addNamed node-sass@_
14 verbose addNamed "_" is a valid semver range for node-sass
15 silly addNameRange { name: 'node-sass', range: '_', hasData: false }
16 silly mapToRegistry name node-sass
17 silly mapToRegistry using default registry
18 silly mapToRegistry registry https://registry.npmjs.org/
19 silly mapToRegistry uri https://registry.npmjs.org/node-sass
20 verbose addNameRange registry:https://registry.npmjs.org/node-sass not in flight; fetching
21 silly cache add parsed spec Result {
21 silly cache add   raw: '2.1.1',
21 silly cache add   scope: null,
21 silly cache add   name: '2.1.1',
21 silly cache add   rawSpec: '',
21 silly cache add   spec: '_',
21 silly cache add   type: 'range' }
22 silly addNamed 2.1.1@_
23 verbose addNamed "_" is a valid semver range for 2.1.1
24 silly addNameRange { name: '2.1.1', range: '_', hasData: false }
25 silly mapToRegistry name 2.1.1
26 silly mapToRegistry using default registry
27 silly mapToRegistry registry https://registry.npmjs.org/
28 silly mapToRegistry uri https://registry.npmjs.org/2.1.1
29 verbose addNameRange registry:https://registry.npmjs.org/2.1.1 not in flight; fetching
30 verbose request uri https://registry.npmjs.org/node-sass
31 verbose request no auth needed
32 info attempt registry request try #1 at 1:25:30 PM
33 verbose request id f1afeba09606aace
34 http request GET https://registry.npmjs.org/node-sass
35 verbose request uri https://registry.npmjs.org/2.1.1
36 verbose request no auth needed
37 info attempt registry request try #1 at 1:25:30 PM
38 http request GET https://registry.npmjs.org/2.1.1
39 info retry will retry, error on last attempt: Error: write EPROTO
40 info retry will retry, error on last attempt: Error: write EPROTO
41 info attempt registry request try #2 at 1:25:41 PM
42 http request GET https://registry.npmjs.org/2.1.1
43 info attempt registry request try #2 at 1:25:41 PM
44 http request GET https://registry.npmjs.org/node-sass
45 info retry will retry, error on last attempt: Error: write EPROTO
46 info retry will retry, error on last attempt: Error: write EPROTO
47 info attempt registry request try #3 at 1:26:41 PM
48 http request GET https://registry.npmjs.org/2.1.1
49 info attempt registry request try #3 at 1:26:41 PM
50 http request GET https://registry.npmjs.org/node-sass
51 verbose stack Error: write EPROTO
51 verbose stack     at Object.exports._errnoException (util.js:874:11)
51 verbose stack     at exports._exceptionWithHostPort (util.js:897:20)
51 verbose stack     at WriteWrap.afterWrite (net.js:763:14)
52 verbose cwd C:\Users\kai.byroade\Desktop\Phoenix
53 error Windows_NT 6.1.7601
54 error argv "C:\Program Files (x86)\nodejs\node.exe" "C:\Program Files (x86)\nodejs\node_modules\npm\bin\npm-cli.js" "install" "--save-dev" "node-sass" "2.1.1"
55 error node v4.2.2
56 error npm  v2.14.7
57 error code EPROTO
58 error errno EPROTO
59 error syscall write
60 error write EPROTO
61 error If you need help, you may report this error at:
61 error     https://github.com/npm/npm/issues
62 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
Hello @azkaiart! Are you running?:

``` sh
npm install --save-dev node-sass 2.1.1
```

I think you should actually be running:

``` sh
npm install --save-dev node-sass@2.1.1
```

If you want to install a specific version. Do you agree?

**Comment by azkaiart** [comment]
Hi @KenanY thanks for the response! I don't mind which version I actually just did that to see if that worked instead of just defaulting to the most updated version. (Not sure which version that is.) I did try with that, but I'm still getting the same error. Here is the new debug log:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--save-dev',
1 verbose cli   'node-sass@2.1.1' ]
2 info using npm@2.14.7
3 info using node@v4.2.2
4 verbose install initial load of C:\Users\kai.byroade\Desktop\Phoenix\package.json
5 warn package.json Acclaim@1.0.0 No repository field.
6 warn package.json Acclaim@1.0.0 No README data
7 verbose readDependencies loading dependencies from C:\Users\kai.byroade\Desktop\Phoenix\package.json
8 silly cache add args [ 'node-sass@2.1.1', null ]
9 verbose cache add spec node-sass@2.1.1
10 silly cache add parsed spec Result {
10 silly cache add   raw: 'node-sass@2.1.1',
10 silly cache add   scope: null,
10 silly cache add   name: 'node-sass',
10 silly cache add   rawSpec: '2.1.1',
10 silly cache add   spec: '2.1.1',
10 silly cache add   type: 'version' }
11 silly addNamed node-sass@2.1.1
12 verbose addNamed "2.1.1" is a plain semver version for node-sass
13 silly mapToRegistry name node-sass
14 silly mapToRegistry using default registry
15 silly mapToRegistry registry https://registry.npmjs.org/
16 silly mapToRegistry uri https://registry.npmjs.org/node-sass
17 verbose addNameVersion registry:https://registry.npmjs.org/node-sass not in flight; fetching
18 verbose request uri https://registry.npmjs.org/node-sass
19 verbose request no auth needed
20 info attempt registry request try #1 at 2:01:03 PM
21 verbose request id 65c7dacdc35d6732
22 http request GET https://registry.npmjs.org/node-sass
23 info retry will retry, error on last attempt: Error: write EPROTO
24 info attempt registry request try #2 at 2:01:13 PM
25 http request GET https://registry.npmjs.org/node-sass
26 info retry will retry, error on last attempt: Error: write EPROTO
27 info attempt registry request try #3 at 2:02:14 PM
28 http request GET https://registry.npmjs.org/node-sass
29 verbose stack Error: write EPROTO
29 verbose stack     at Object.exports._errnoException (util.js:874:11)
29 verbose stack     at exports._exceptionWithHostPort (util.js:897:20)
29 verbose stack     at WriteWrap.afterWrite (net.js:763:14)
30 verbose cwd C:\Users\kai.byroade\Desktop\Phoenix
31 error Windows_NT 6.1.7601
32 error argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save-dev" "node-sass@2.1.1"
33 error node v4.2.2
34 error npm  v2.14.7
35 error code EPROTO
36 error errno EPROTO
37 error syscall write
38 error write EPROTO
39 error If you need help, you may report this error at:
39 error     <https://github.com/npm/npm/issues>
40 verbose exit [ 1, true ]
