### ISSUE TITLE
npm-shrinkwrap.json being ignored for a dependency of a dependency (2.14.9, 3.3.10)

### ISSUE THREAD

**Issue by maxkorp** [npm/npm#10262]
Using npm shrinkwrap in my project, and just now having an issue. 
My package uses https://github.com/atom/atom-keymap, which uses https://github.com/atom/node-pathwatcher. 
I'm locked down in my npm-shrinkwrap.json to atom-keymap@6.1.0, and under that pathwatcher@6.2.5.

I get atom-keymap@6.1.0 (but this is the latest version), and pathwatcher@6.3.0 (published last night, which breaks for me). I've found the problem in pathwatcher, but that doesn't explain why the shrinkwrap is being ignored.  
This happens if i try `npm install` or `npm install atom-keymap`. 

Tried rolling back to 2.14.7, as well as up to 3.3.10, and same error.

**Comment by seldo** [comment]
I tried to repo this with the following package.json:

```
{
  "name": "sw",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "atom-keymap": "^6.1.0"
  }
}
```

I manually edited my shrinkwrap to use pathwatcher@6.2.5, blew away node_modules, installed, and got 6.2.5 as expected. This was all with npm 3.3.12.

**Comment by maxkorp** [comment]
Hrm interestingly, when I pare it down to just the base case, it works, but not with the full package of modules. I can include my entire shrinkwrap in a bit.
