### ISSUE TITLE
Am trying to install Mosaico and am getting this fail repeatedly.

### ISSUE THREAD

**Issue by mherbold** [npm/npm#10275]
npm ERR! git clone git://github.com/SevInf/node-byline.git Initialized empty Git repository in /home/usked/.npm/_git-remotes/git-github-com-SevInf-node-byline-git-d6518a15/
npm ERR! git clone git://github.com/SevInf/node-byline.git
npm ERR! git clone git://github.com/SevInf/node-byline.git github.com[0: 192.30.252.130]: errno=Connection timed out
npm ERR! git clone git://github.com/SevInf/node-byline.git fatal: unable to connect a socket (Connection timed out)
npm ERR! Error: Command failed: github.com[0: 192.30.252.130]: errno=Connection timed out
npm ERR! fatal: unable to connect a socket (Connection timed out)
npm ERR!
npm ERR!     at ChildProcess.exithandler (child_process.js:658:15)
npm ERR!     at ChildProcess.emit (events.js:98:17)
npm ERR!     at maybeClose (child_process.js:766:16)
npm ERR!     at Socket.<anonymous> (child_process.js:979:11)
npm ERR!     at Socket.emit (events.js:95:17)
npm ERR!     at Pipe.close (net.js:466:12)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 2.6.32-504.16.2.el6.x86_64
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "update"
npm ERR! cwd /home/usked/subdomains/alpha/public/mosaico
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! code 128
npm ERR! not ok code 0

I can ping 192.30.252.130 OK and this is the only part it's failing on - NPM installed everything else.

**Comment by KenanY** [comment]
@mherbold Maybe you are behind a proxy or firewall that is blocking the `git://` protocol?

**Comment by mherbold** [comment]
That was it - firewall wasn't allowing outbound tcp to 9418.

**Comment by ehsalazar** [comment]
@mherbold It sounds like you got things figured out. I'll close this for now as we’re trying to clean up some solved issues. We’ll be happy to reopen if necessary.
