### ISSUE TITLE
npm config ERR prefix

### ISSUE THREAD

**Issue by kbariotis** [npm/npm#10274]
I found this at the `npm config` command.

![screen shot 2015-11-05 at 11 35 48](https://cloud.githubusercontent.com/assets/605742/10964704/67f9a8f2-83b1-11e5-8dc9-7da712e097d7.png)

**Comment by KenanY** [comment]
@kbariotis What seems to be a problem? I think not giving `npm config` any arguments should error out like it does (and it seems quite helpful that it takes the time to display correct usage). What are you _expecting_ to happen? For `npm config` to _not_ throw an error when it is used syntactically incorrectly?

**Comment by kbariotis** [comment]
@KenanY No, there isn't no problem, I thought the layout of the output to be incorrect though. Other commands are displaying the `npm ERR!` once in the top or at the bottom of the output. Indeed, it's quite useful the way it works but it can be confusing.

Also, there is no explanation of the error. It's just a bunch of lines where all of them problem have an error. 

So, it could be an `npm ERR!` on the top of the output. Then, an explanation, that this commands needs arguments. At last, the npm config usage.

Thank you

**Comment by KenanY** [comment]
@kbariotis Ohhh the layout! :) Yeah that could be improved!

**Comment by kbariotis** [comment]
@KenanY May I open a PR for that. It would be my pleasure!

**Comment by KenanY** [comment]
@kbariotis Unfortunately it is not up to me whether or not a PR will get merged, but since the "fix" would be as easy as expanding on [this](https://github.com/npm/npm/blob/v3.3.12/lib/config.js#L4-L10), I would say go for it anyways!

Also, AFAICT other multi-line errors prefix each line with `npm ERR!` like we see here. For example,

```
npm ERR! Failed to parse json
npm ERR! Unexpected token 'n' at 25:6
npm ERR!     "nugget": "^1.6.0",
npm ERR!      ^
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse
```

so I think we should keep that part?

**Comment by kbariotis** [comment]
@KenanY Indeed it seems like all of the commands throwing an error follow this layout. Haven't noticed that.
