### ISSUE TITLE
npm edit seems to be broken for an EDITOR with spaces

### ISSUE THREAD

**Issue by martinheidegger** [npm/npm#10280]
According to the documentation the `EDITOR` variable refers to the editor that is opened with `npm edit` However in my case that editor `Sublime Text` has a space in the path and it seems like npm doesn't accept that.

```
pm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "edit" "coffee-script" "-g"
npm ERR! node v4.2.1
npm ERR! npm  v3.3.10
npm ERR! path "/Applications/Sublime\
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn "/Applications/Sublime\

npm ERR! enoent spawn "/Applications/Sublime\ ENOENT
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
```

**Comment by emkay** [comment]
Hi @martinheidegger. It looks like the `editor` module that `npm` is using to determine `EDITOR` splits on whitespace characters to determine arguments. https://github.com/substack/node-editor/blob/master/index.js#L12

**Comment by martinheidegger** [comment]
So: how would someone be supposed to enter a path with spaces?

**Comment by watilde** [comment]
Simple solution: Create a symlink and use no special characters, like the following
```
ln -s "/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl" /usr/local/bin/sublime
```
then, you can use it by updating the value of the `EDITOR` variable to `sublime`.

Also, I tried to create a PR to the module. https://github.com/substack/node-editor/pull/12
