### ISSUE TITLE
allow exclusion of packages when installing

### ISSUE THREAD

**Issue by creynders** [npm/npm#10288]
It would be _really_ useful if you could exclude direct dependencies from installation on the CLI.

E.g. something like:

```sh
$ npm install --exclude babel
```

Which would install all dependencies as declared in the CWD's `package.json` except for `babel`.

The concrete use case would be to be able to exclude modules you'll be `npm link`ing to.
E.g. I'm working on module `baz@2.0` which has a v1.0 in the npm registry. To ensure it works properly in module `foo` (which has a direct dependency on `baz`), I download/clone `foo` and run `npm install`, however it'll install `baz@1.0`. Not a problem if it's a small module, but if it's a mean mofo with tons of dependencies and build scripts and whatnot, it would be really nice to be able to say `npm install --exclude baz`, since I'll be running `npm link baz` next anyway.

**Comment by othiym23** [comment]
Would it be useful to you if there were some way of saying at the outset that there are certain dependencies that you'd like `npm linked` into the project rather than installed from source in `package.json`? The use case as described is awfully narrowly defined.

**Comment by creynders** [comment]
Yeah, sure!

**Comment by othiym23** [comment]
Could you open a new issue describing how you would like that linking behavior to work? I'm going to close this feature request, as it doesn't really capture the desired behavior as written, and because we're trying to trim the list of outstanding feature requests. Thanks for your time!
