### ISSUE TITLE
npm2 bundledDependencies not respected when installing with npm3

### ISSUE THREAD

**Issue by patocallaghan** [npm/npm#10283]
The [Ember CLI package](https://www.npmjs.com/package/ember-cli) is published with a number of `bundledDependencies`. One of its `bundledDependencies` is `testem` which has some deeply nested native optional dependencies. To prevent these native optional dependencies from ever being installed by users, just prior to publishing a release, the `package.json` of the [offending packages are rewritten to remove the native libraries](https://github.com/ember-cli/ember-cli/blob/master/patches/patch-ws.js#L13). Ember CLI is then `pack`'d and `publish`'d with its bundled dependencies using npm@2.

Running `npm install ember-cli` with npm@2 correctly respects the `bundledDependencies` in the `.tgz` and doesn't install the native optional dependencies. But when installing Ember CLI using npm@3 it seems to just ignore the package.json of the offending libraries, retrieving them from the registry instead, and installing the native optional dependencies.

You can easily reproduce this by simply running `npm install ember-cli` with both npm 2 and 3. You will see when using npm@3 the `bufferutil` and `utf-8-validate` native libraries are installed where they aren't with npm@2.

If you pull down and extract http://registry.npmjs.org/ember-cli/-/ember-cli-1.13.8.tgz you will see that 

```
package/node_modules/testem/node_modules/socket.io/node_modules/engine.io/node_modules/ws/package.json
```

has no `optionalDependencies`. Yet, they are still installed, implying that this package.json is being completely ignored and instead pulled from the registry where it has [the optional dependencies](https://github.com/websockets/ws/blob/master/package.json#L27)

**Comment by iarna** [comment]
This is interesting, because the behavior you expect is what I thought npm@3 was already doing. I'm looking forward to figuring out exactly why npm@3's behavior is the way it is here…

**Comment by brphelps** [comment]
Hmm, is this being monitored at all? Should the NPM docs be updated to indicate that bundledDependencies is no longer functional?

**Comment by monolithed** [comment]
There's a [similar](https://github.com/npm/npm/issues/14641) problem with `npm@3`
