### ISSUE TITLE
npm ERR! shasum check failed for registry.npmjs.org\tar\-\tar-2.2.1.tgz

### ISSUE THREAD

**Issue by timtroup** [npm/npm#10294]
npm install on my project has just started failing with this error:

<code>
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7

npm ERR! shasum check failed for c:\TEMP\npm-2896-f110ac04\registry.npmjs.org\tar\-\tar-2.2.1.tgz
npm ERR! Expected: 8e4d2a256c0e2185c6b18ad694aec968b83cb1d1
npm ERR! Actual:   d75de1bc5dc6eea64fb8eece6a8fcf1498543ece
npm ERR! From:     http://registry.npmjs.org/tar/-/tar-2.2.1.tgz
</code>

I had been running an older version of node/npm and upgrade to this version in the hope it would fix things but that didn't help. Same error.

**Comment by timtroup** [comment]
Looks like this is a corrupt file:

http://registry.npmjs.org/tar/-/tar-2.2.1.tgz

**Comment by KenanY** [comment]
@timtroup Does `npm cache clean` help at all? Just to make sure it isn't just a corrupt file in your cache.

**Comment by timtroup** [comment]
@KenanY I tried <code>npm cache clean</code> prior to posting and sadly it made no difference. 

I then changed to a different npm mirror and my build passed successfully.

Earlier when I went to http://registry.npmjs.org/tar/-/tar-2.2.1.tgz from my browser it downloaded a 2kb file. Now when I go to that same URL I get a 50kb file so maybe someone has fixed something now.

**Comment by KenanY** [comment]
@timtroup Are you still seeing this issue?

**Comment by busches** [comment]
@KenanY 2 months of silence, what's the policy on keeping the issue open/closing it?

**Comment by KenanY** [comment]
@busches I close after a week with no response. Looks like this slipped through. Feel free to ping me on any others if you'd like. Closing as abandoned.

**Comment by FredMurphy** [comment]
This has been bugging me recently. It's still an issue and I found a solution so thought I'd post it here. The problem seems to be when hitting the registry over http rather than https. Whilst having proxy issues I'd done "npm config set registry=http://registry.npmjs.org" and removing this fixed the problem.

As to quite why a different file seems to be served up whether it's using SSL or not... who knows.

**Comment by gordanvij** [comment]
Thank you @FredMurphy .. saved my day..
