### ISSUE TITLE
Facing err while installing express by typeing: npm install -g express

### ISSUE THREAD

**Issue by RohitLuthra19** [npm/npm#10290]
npm ERR! registry error parsing json
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "express"
npm ERR! node v4.1.2
npm ERR! npm  v2.14.4

npm ERR! Unexpected token <
npm ERR! <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
npm ERR! <HTML dir=ltr><HEAD><TITLE>The page cannot be displayed</TITLE>
npm ERR! <STYLE>A:link {
npm ERR!        FONT: 8pt/11pt verdana; COLOR: #ff0000
npm ERR! }
npm ERR! A:visited {
npm ERR!        FONT: 8pt/11pt verdana; COLOR: #4e4e4e
npm ERR! }
npm ERR! </STYLE>
npm ERR!
npm ERR! <META content=NOINDEX name=ROBOTS>
npm ERR! <META http-equiv=Content-Type content="text-html; charset=Windows-1252"
>
npm ERR!
npm ERR! <META content="MSHTML 5.50.4522.1800" name=GENERATOR></HEAD>
npm ERR! <BODY bgColor=#ffffff>
npm ERR! <TABLE cellSpacing=5 cellPadding=3 width=410>
npm ERR!   <TBODY>
npm ERR!   <TR>
npm ERR!     <TD vAlign=center align=left width=360>
npm ERR!       <H1 style="FONT: 13pt/15pt verdana; COLOR: #000000"><!--Problem--
>The page
npm ERR!       cannot be displayed</H1></TD></TR>
npm ERR!   <TR>
npm ERR!     <TD width=400 colSpan=2><FONT
npm ERR!       style="FONT: 8pt/11pt verdana; COLOR: #000000">There is a problem
 with the
npm ERR!       page you are trying to reach and it cannot be displayed.</FONT></
TD></TR>
npm ERR!   <TR>
npm ERR!     <TD width=400 colSpan=2><FONT
npm ERR!       style="FONT: 8pt/11pt verdana; COLOR: #000000">
npm ERR!       <HR color=#c0c0c0 noShade>
npm ERR!
npm ERR!       <P>Please try the following:</P>
npm ERR!       <UL>
npm ERR!         <LI>Click the Refresh button,
npm ERR!         or try again later.<BR>
npm ERR!         <LI>Open the Web site
npm ERR!          home page, and then look for links to the information you want
.
npm ERR!         <LI>If you typed the page address in the Address bar, make sure
 that it
npm ERR!         is spelled correctly.<BR>
npm ERR!         <LI>Verify that the Internet access policy on your network allo
ws you
npm ERR!         to view this this page.</LI>
npm ERR!         <LI>If you believe you should be able to view this directory or
 page,
npm ERR!         please contact the Web site administrator by using the e-mail a
ddress or
npm ERR!         phone number listed on the Web site
npm ERR!          home page. </LI></UL>
npm ERR!       <H2 style="FONT: 8pt/11pt verdana; COLOR: #000000">HTTP 407 Proxy
 Authentication Required - The ISA Server requires authorization to fulfill the
request. Access to the Web Proxy service is denied. (12209)<BR>Internet Security
 and Acceleration Server</H2>
npm ERR!       <HR color=#c0c0c0 noShade>
npm ERR!
npm ERR!       <P>Technical Information (for support personnel)</P>
npm ERR!       <UL>
npm ERR!         <LI>Background:<BR>The gateway could not retrieve the requested
 page.<P></P></LI>
npm ERR!         <LI>ISA Server: proxy.company.com<BR>
npm ERR!         Via: <BR><BR>Time: 11/6/2015 11:49:12 AM GMT
npm ERR!         </LI></UL></FONT></TD></TR></TBODY></TABLE></BODY></HTML>
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\rkumar\Desktop\myapp\npm-debug.log

C:\Users\rkumar\Desktop\myapp>npm install -g express

**Comment by KenanY** [comment]
@RohitLuthra19 Well from the error log it looks like you need to authenticate with your proxy.

**Comment by RohitLuthra19** [comment]
Yeah it was due to proxy . I found the solution ...

**Comment by KenanY** [comment]
Closing as resolved then.
