### ISSUE TITLE
'npm ls -g' not working on Windows 7

### ISSUE THREAD

**Issue by giboorman** [npm/npm#10307]
I do a npm ls -g and get errors. I want to see what global modules are installed, am I doing it wrong?
Thanks. (log pasted below)
-----------
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\nodejs\\node.exe',
1 verbose cli   'C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'ls',
1 verbose cli   '-g' ]
2 info using npm@2.14.7
3 info using node@v4.2.2
4 verbose stack Error: write EIO
4 verbose stack     at exports._errnoException (util.js:874:11)
4 verbose stack     at WriteStream.Socket._writeGeneric (net.js:675:26)
4 verbose stack     at WriteStream.Socket._write (net.js:694:8)
4 verbose stack     at doWrite (_stream_writable.js:292:12)
4 verbose stack     at writeOrBuffer (_stream_writable.js:278:5)
4 verbose stack     at WriteStream.Writable.write (_stream_writable.js:207:11)
4 verbose stack     at WriteStream.Socket.write (net.js:618:40)
4 verbose stack     at Console.log (console.js:36:16)
4 verbose stack     at C:\nodejs\node_modules\npm\lib\ls.js:68:13
4 verbose stack     at C:\nodejs\node_modules\npm\node_modules\read-installed\read-installed.js:142:5
5 verbose cwd C:\Users\Andrew\Desktop
6 error Windows_NT 6.1.7601
7 error argv "C:\\nodejs\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "ls" "-g"
8 error node v4.2.2
9 error npm  v2.14.7
10 error code EIO
11 error errno EIO
12 error syscall write
13 error write EIO
14 error If you need help, you may report this error at:
14 error     <https://github.com/npm/npm/issues>
15 verbose exit [ 1, true ]

**Comment by smartmouse** [comment]
Can you please try npm config get prefix?
Have this ever work on your system before?
The command is correct, could be your environment.

Also please echo %PATH%

This is what I get since I have no global install
c:\Users\IBM_ADMIN>npm -v
2.14.7
c:\Users\IBM_ADMIN>node -v
v4.2.1

c:\Users\IBM_ADMIN>npm ls -g
c:\Users\IBM_ADMIN\test421\npmglobal
└── (empty)

**Comment by giboorman** [comment]
Fix found: problem had to do with current code page (see http://stackoverflow.com/questions/17035399/why-this-error-happend-nodejs-error-write-eio )
Output below shows how problem is solved by setting codepage to 850:
---------
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "ls" "-g"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code EIO
npm ERR! errno EIO
npm ERR! syscall write

npm ERR! write EIO
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Andrew\Desktop\npm-debug.log

C:\Users\Andrew\Desktop>chcp 850
Active code page: 850

C:\Users\Andrew\Desktop>npm ls -g
C:\Users\Andrew\AppData\Roaming\npm
└── (empty)
