### ISSUE TITLE
Easy way to list available scripts 

### ISSUE THREAD

**Issue by rafaelrinaldi** [npm/npm#10319]
Lately I've been using `npm` to handle all my tasks and it works really well. One thing I miss though is a way to list all the scripts available on the project through the command line. Of course I could simply `require('./package.json').scripts` but I think we could have a command for that. Both Gulp and Grunt have a bultin command to achieve that.

It doesn't need to be anything fancy. Here's a simple draft:

```js
// scripts.js
var scripts = require('./package.json').scripts;
var keys = Object.keys(scripts);
var size = keys.length;
var divisor = '\n' + new Array(20).join('=') + '\n'
var output = divisor + size + ' tasks available:' + divisor + '\n';

Object.keys(scripts).forEach(function(script) {
  output += script + '\n';
});

process.stdout.write(output);
```

```sh
$ node scripts.js

===================
9 tasks available:
===================

build:css
build:js
server
watch:css
watch:js
postcss
start
build
deploy
```

Before I even attempted a pull request I wanted to hear opinions on this.

Thanks.

**Comment by KenanY** [comment]
@rafaelrinaldi This is already supported, no? For example (running within `npm` repository):

``` sh
$ npm run-script
Lifecycle scripts included in npm:
  prepublish
    node bin/npm-cli.js prune --prefix=. --no-global && rimraf test/*/*/node_modules && make -j4 doc
  preversion
    bash scripts/update-authors.sh && git add AUTHORS && git commit -m "update AUTHORS" || true
  test
    standard && npm run test-tap

available via `npm run-script`:
  dumpconf
    env | grep npm | sort | uniq
  tap
    tap --timeout 240
  test-all
    standard && npm run test-legacy && npm run test-tap
  test-legacy
    node ./test/run.js
  test-tap
    npm run tap -- "test/tap/*.js"
  test-node
    "$NODE" ./test/run.js && "$NODE" "node_modules/.bin/tap" --timeout 240 "test/tap/*.js"
```

https://docs.npmjs.com/cli/run-script

> If no `"command"` is provided, it will list the available scripts.

**Comment by rafaelrinaldi** [comment]
@KenanY Whoa, I never knew this! Maybe it should be highlighted on the docs or something.

Thanks a lot for your help. Learned a new trick today!
