### ISSUE TITLE
npm run with `&` - one process dies, npm dies, but other scripts keep running

### ISSUE THREAD

**Issue by cjohansen** [npm/npm#10316]
If you run multiple background processes in an npm script using `&`, and one of them dies, then npm dies as well. However, the other scripts keep running in the background. Confirmed on both npm 2 and 3.

Reproduce:

``` js
// run.js

setInterval(function () {
  console.log('I\´m alive');
}, 1000);
```

``` js
// die.js
setTimeout(function () {
  throw new Error('Oh my');
}, 2000);
```

``` js
// package.json
{
  "name": "test-npm-run",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "node run.js & node die.js"
  },
  "author": "",
  "license": "ISC"
}
```

Reproducing gist: https://gist.github.com/cjohansen/a087748f3ab9aa78aafd

**Comment by tnunes** [comment]
Any update on this?

**Comment by ineghi** [comment]
Very annoying when dealing with server ports

**Comment by legodude17** [comment]
What is the output?
