### ISSUE TITLE
[support] can `npm adduser` be undone locally?

### ISSUE THREAD

**Issue by Mithgol** [npm/npm#10310]
This is a support question.

If the command `npm adduser` was successful on a device, can it be undone locally?

If a device is voluntarily given to a third party (e.g. sold, leased, donated, etc.), but without wiping its entire file system, would that device inevitably grant such third party some permanent ability to act as an added user? Or can `npm adduser` be undone beforehand from the command line?

I've read https://docs.npmjs.com/cli/adduser and then https://github.com/npm/npm/issues?q=adduser but I coundn't find any command or parameter that seems like it undoes `npm adduser` (e.g. there is no `npm removeuser`, no `npm rmuser`, no `npm adduser --undo`, etc.).

If there's no such command, what should be done?

Would it be enough to delete (and wipe) the `~/.npmrc` file, for example?

Would `npm logout` remove the user added by `npm adduser` (after all, `npm login` means `npm adduser`, and `npm logout` looks like it should undo `npm login`)? Or would it just invalidate that user's current token?

**Comment by smikes** [comment]
Historically `npm adduser` and `npm login` have done the same thing, which is:

1. add the userid to the database if it doesn't yet exist
2. store a login token (in older versions: store the password, obfuscated)

`npm logout` reverses step 2.  Reversing step 1 would require manual intervention at the registry level.

**Comment by Mithgol** [comment]
Is the `_auth=...` part in `~/.npmrc` a login token? Or obfuscated password?

**Comment by ChALkeR** [comment]
@Mithgol `_auth` is login:password, `_authToken` is a login token.
Also, I would not call base64 as «obfuscated».

**Comment by Mithgol** [comment]
Okay, I've deleted `~/.npmrc` and I hope that's enough.
