### ISSUE TITLE
`npm install` does nothing, leaves no output or debug log

### ISSUE THREAD

**Issue by jsdevel** [npm/npm#10325]
I installed `npm` via `npm`, using node version `v0.12`.  `npm --version` yeilds `2.11.3`.

When I run `npm install` I literall get nothing.  No npm log file, not console output, nothing.  The command exits with code `0` though as appending `&& echo success` prints success afterwards.

I _am_ able to install packages with `-g`, which is really strange to me.

Here is my `package.json`:

```
{
  "name": "kogosoftwarellc.github.io",
  "version": "1.0.0",
  "description": "The source code for kogo.io.",
  "private": true,
  "repository": {
    "type": "git",
    "url": "git+https://github.com/kogosoftwarellc/kogosoftwarellc.github.io.git"
  },
  "author": "Joseph Spencer",
  "bugs": {
    "url": "https://github.com/kogosoftwarellc/kogosoftwarellc.github.io/issues"
  },
  "homepage": "https://github.com/kogosoftwarellc/kogosoftwarellc.github.io#readme",
  "devDependencies": {
    "bootstrap-material-design": "^0.3.0",
    "browser-sync": "^2.9.12",
    "del": "^2.0.2",
    "google-form": "^1.0.2",
    "gulp": "^3.9.0",
    "gulp-autoprefixer": "^3.1.0",
    "gulp-concat": "^2.6.0",
    "gulp-cssimport": "^2.1.1",
    "gulp-jade": "^1.1.0",
    "gulp-less": "^3.0.3",
    "gulp-sourcemaps": "^1.6.0",
    "less": "^2.5.3",
    "run-sequence": "^1.1.4"
  }
}
```

**Comment by lxe** [comment]
What is your `NODE_ENV` env variable set to? Maybe it's `production`? In this case, `devDependencies` won't be installed. See https://docs.npmjs.com/misc/config#production.

**Comment by jsdevel** [comment]
Thanks @lxe !  That was the issue.

**Comment by ranietots32** [comment]
@lxe how do I change it to development or disable it on my windows machine, I want it to **never** be in production

**Comment by pvorona** [comment]
@lxe thanks!
