### ISSUE TITLE
NPM issue when doing NPM INSTALL

### ISSUE THREAD

**Issue by williamhgough** [npm/npm#10320]
Keep getting this error when I use any YO generators or NPM INSTALL:

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE

npm ERR! v8-debug@0.4.6 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v8-debug@0.4.6 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls v8-debug
npm ERR! There is likely additional logging output above.

As far as i'm aware, Node & npm are installed correctly and i've set the permissions for the necessary directories properly.

**Comment by joelgriffith** [comment]
`npm ERR! node v5.0.0`... does `node-gyp` support `node@5.x.x`?

**Comment by williamhgough** [comment]
I got the same result with node 4.2.2

**Comment by LuigiFrattolillo** [comment]
Hi, when i run "npm install" locally i get many dependencies i don't need, even though i have just one in my package.json file.

Any idea about that? I'm desperate! :(

**Comment by BlueSialia** [comment]
I just resolved this problem with [this](https://github.com/node-inspector/node-inspector/issues/662#issuecomment-109256462) workaround.

**Comment by KenanY** [comment]
@LuigiFrattolillo Your issue does not sound like that of @williamhgough... could you open a new issue instead and add more information?

**Comment by cutdekprod** [comment]
Seems as if the v8-debug build has been failing for a while https://www.npmjs.com/package/v8-debug

**Comment by mrjohnskelton** [comment]
See node-inspector/v8-debug#7 for a suggested fix by @stephen-cernota and @surprisetalk - worked for me on a shiny new version set

**Comment by KenanY** [comment]
Judging by https://github.com/node-inspector/v8-debug/issues/7#issuecomment-154450807 it looks to me like this is not a bug in `npm`, so I'm gonna close.
