### ISSUE TITLE
NPM v - 3.3.6. "npm install" downloads modules not present in package.json file!

### ISSUE THREAD

**Issue by LuigiFrattolillo** [npm/npm#10324]
Hi, when i run "npm install" locally i get many dependencies i don't need, even though i have just one dependency in my package.json file.

Any idea about that? I'm desperate! :(

**Comment by othiym23** [comment]
The `npm@3` installer installs dependency trees [maximally flat](https://github.com/npm/npm/blob/master/CHANGELOG.md#flat-flat-flat), so the behavior you're seeing is the intended behavior. It's a little surprising seeing your nested dependencies all showing up in `node_modules` like this, but it reduces the disk space used overall and greatly reduces the difficulties encountered by npm users on Windows.

**Comment by LuigiFrattolillo** [comment]
Are you saying that "grunt": "^0.4.1" which generates other 29 folders is normal?

**Comment by othiym23** [comment]
Yep:
```
% npm install -S 'grunt@^0.4.1'
test-install-grunt@1.0.0 /Users/ogd/Documents/projects/test-install-grunt
└─┬ grunt@0.4.5
  ├── async@0.1.22
  ├── coffee-script@1.3.3
  ├── colors@0.6.2
  ├── dateformat@1.0.2-1.2.3
  ├── eventemitter2@0.4.14
  ├── exit@0.1.2
  ├─┬ findup-sync@0.1.3
  │ ├─┬ glob@3.2.11
  │ │ ├── inherits@2.0.1
  │ │ └── minimatch@0.3.0
  │ └── lodash@2.4.2
  ├── getobject@0.1.0
  ├─┬ glob@3.1.21
  │ ├── graceful-fs@1.2.3
  │ └── inherits@1.0.2
  ├─┬ grunt-legacy-log@0.1.2
  │ ├─┬ grunt-legacy-log-utils@0.1.1
  │ │ ├── lodash@2.4.2
  │ │ └── underscore.string@2.3.3
  │ ├── lodash@2.4.2
  │ └── underscore.string@2.3.3
  ├── grunt-legacy-util@0.2.0
  ├── hooker@0.2.3
  ├── iconv-lite@0.2.11
  ├─┬ js-yaml@2.0.5
  │ ├─┬ argparse@0.1.16
  │ │ ├── underscore@1.7.0
  │ │ └── underscore.string@2.4.0
  │ └── esprima@1.0.4
  ├── lodash@0.9.2
  ├─┬ minimatch@0.2.14
  │ ├── lru-cache@2.7.0
  │ └── sigmund@1.0.1
  ├─┬ nopt@1.0.10
  │ └── abbrev@1.0.7
  ├── rimraf@2.2.8
  ├── underscore.string@2.2.1
  └── which@1.0.9
```
Each one of those dependencies needs to go somewhere. The tree printed out by `npm ls` (and which is used here by the installer) is a _logical view_, which shows the dependencies between packages, but the  _physical view_ of how the packages are stored in `node_modules` is very different:
```
bauchelain% COLUMNS=76 ls node_modules
abbrev			getobject		js-yaml
argparse		glob			lodash
async			graceful-fs		lru-cache
coffee-script		grunt			minimatch
colors			grunt-legacy-log	nopt
dateformat		grunt-legacy-log-utils	rimraf
esprima			grunt-legacy-util	sigmund
eventemitter2		hooker			underscore
exit			iconv-lite		underscore.string
findup-sync		inherits		which
```

Read that chunk of the CHANGELOG that I linked to in my first response; it lays out pretty clearly what's changed, and why.

**Comment by LuigiFrattolillo** [comment]
Ok, understood now. I thought to have a kind of bug or whatever on my laptop... thanks for your support!

**Comment by LuigiFrattolillo** [comment]
Only It seems slower than before
