### ISSUE TITLE
module.js 339 throw err

### ISSUE THREAD

**Issue by littlus** [npm/npm#10328]
![przechwytywanie](https://cloud.githubusercontent.com/assets/15776523/11061640/c71deb72-87a8-11e5-9a6a-2f3945fbac9f.PNG)

i got this error when i try add platform

**Comment by OmgImAlexis** [comment]
Next time please post your actual log and not a screenshot.

This should be reported to ionic, not npm.

**Comment by aredridel** [comment]
This may be a bug in npm, which version of npm was used to install this would be useful information.
