### ISSUE TITLE
"logo" field in package.json

### ISSUE THREAD

**Issue by patrick-steele-idem** [npm/npm#10323]
It would be great if the project's logo could be provided in a "standard" way inside a package's [package.json](https://docs.npmjs.com/files/package.json) file. This would allow, among other things, a project's logo to be shown in package search results.

Also, the homepage for [npmjs.com](https://www.npmjs.com/) shows the "top" packages with their logos. I'm not sure what logic was used to associate those packages with a logo, but it definitely didn't come from the `package.json` file. Is there another source that I am not aware of?

Here's one possible proposal to allow a logo to come from either a remote URL or from a local package file:

## Logo from URL

```json
{
  "name": "foo",
  "logo": {
    "url": "https://raw.githubusercontent.com/marko-js/branding/master/marko-logo-small.png"
  }
}
```

## Logo from package file

```json
{
  "name": "foo",
  "logo": {
    "file": "./logo.png"
  }
}
```

-------

Any other ideas?

## Open questions

- Should we allow different size logos to be provided?
- Should the logo field be normalized using [normalize-package-data](https://github.com/npm/normalize-package-data)?

**Comment by othiym23** [comment]
Adding the field to `package.json` (and standardizing the name) is fine, but most of the questions about sizing, display, and search results should be directed to the [web team](https://github.com/npm/newww/issues), rather than the CLI team.

> Should the logo field be normalized using normalize-package-data?

No. `normalize-package-data` is kind of a clusterfluff right now, and one of the outstanding architectural projects for the team is to figure out how to clean up the relationship between `normalize-package-data`, `read-package-json`, `read-installed`, `read-package-tree`, `npm-package-arg`, and the other constellation of packages that take a `package.json` on disk and turn it into the annotated version used by the CLI. Either way, I'm not really in favor of adding anything that requires a lot of special ceremony around things like aspect ratios and formats and the like. If we just mandated that it be something that would work as a `favicon.ico`, that would be handy, but that's actually its own can of worms.

**Comment by patrick-steele-idem** [comment]
Hey @othiym23, thanks for sharing your thoughts. I do think there is value in standardizing a `logo` field and I agree with you that we should keep it simple (single image). Here's an attempt at providing the text to be added to the [package.json](https://docs.npmjs.com/files/package.json) docs page :

-------

## logo

An image logo can be associated with a project using the "logo" property. The value of this property should be an object with either a "url" property or a "file" property as shown below:

```json
"logo": { "url": "https://www.npmjs.com/static/images/npm-logo.svg" }
"logo": { "file": "./npm-logo.svg" }
```

If the "file" property is provided then the referenced image file should be included in the package. If the "url" property is provided then the value should be the URL for an externally hosted image file.

-------

If that looks good to you then I will submit a PR to https://github.com/npm/npm/blob/master/doc/files/package.json.md. Thanks again.

**Comment by othiym23** [comment]
@patrick-steele-idem I'd like to see some consensus from the web team that this is something they're willing to add to their road map before adding anything to `package.json`. Their opinions on this are more pertinent than mine. :wink:

**Comment by patrick-steele-idem** [comment]
Thanks @othiym23. 

Hey @rockbot, @aredridel, @jefflembeck (anyone else?), do you guys have any thoughts on standardizing a `"logo"` field in the `package.json` file? I think the npm web UI could benefit from this information, as well as any other external tool. I'm building an internal product portal and need a standardized way to associate a logo with a project (in addition to other project metadata) and feel a `"logo"` field is needed. I am curious to get your thoughts on the usefulness and format of this field. Thanks!

**Comment by othiym23** [comment]
There's enough of a consensus that the name of this field should be `"logo"`, so developers can start using that in their packages now. Also, for now there are no functional changes required from the CLI to support this. Once the web team figures out how they want to consume this (and commits to adding support for this to npm/newww), the CLI docs can be patched to describe that process. I'm going to close this as I think we've wrung all of the immediately actionable detail out of it. Thanks for getting the ball rolling with this, and thanks for your time!

**Comment by patrick-steele-idem** [comment]
Glad to hear @othiym23. Thanks for following up and thanks for your time as well! Cheers

**Comment by ArmorDarks** [comment]
So, did it result in anything?
