### ISSUE TITLE
Error with `npm update --global`

### ISSUE THREAD

**Issue by molovo** [npm/npm#10327]
Node version: 5.0.0
NPM version: 3.3.9

I get this error at the top of my stdout every time I run any update/install command globally.

```
npm ERR! addLocal Could not install /private/tmp/node20151029-31522-4xn2z9/node-v5.0.0/npm_install
```

The rest of the install/update *seems* to go ahead without issue, but not sure what's causing the error message above.

Let me know what logs/command output you'd like to see and I'll happily post.

**Comment by othiym23** [comment]
Are you using Homebrew to manage your Node.js installation?

**Comment by mledu** [comment]
I get the same error and I'm using Homebrew

**Comment by dbpolito** [comment]
me too, using homebrew

**Comment by quinncomendant** [comment]
me too (also installed via homebrew)

**Comment by molovo** [comment]
Yep, using homebrew

**Comment by lan2720** [comment]
I got the same error too, using homebrew

**Comment by cheets** [comment]
Same here (homebrew). Tried removing all npm packages and uninstalling node and npm through brew and then reinstalling through brew. Still getting same message.

**Comment by teknikqa** [comment]
A solution was mentioned in this issue[#10165] (https://github.com/npm/npm/issues/10165#issuecomment-152451743)

**Comment by molovo** [comment]
Confirmed, upgrading npm to latest (3.4.0) resolved the issue for me. Thanks @teknikqa.
