### ISSUE TITLE
i got error when i install PASSPORT ! somebody please help me out

### ISSUE THREAD

**Issue by toanthree** [npm/npm#10339]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'passport' ]
2 info using npm@3.3.6
3 info using node@v5.0.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData passport
8 silly fetchNamedPackageData passport
9 silly mapToRegistry name passport
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/passport
13 verbose request uri https://registry.npmjs.org/passport
14 verbose request no auth needed
15 info attempt registry request try #1 at 3:07:03 PM
16 verbose request id a2ae65b885fd7afe
17 verbose etag "C8IM8WTB9IZ8PMNMYPAKL88WP"
18 http request GET https://registry.npmjs.org/passport
19 http 304 https://registry.npmjs.org/passport
20 verbose headers { date: 'Wed, 11 Nov 2015 08:07:01 GMT',
20 verbose headers   via: '1.1 varnish',
20 verbose headers   'cache-control': 'max-age=60',
20 verbose headers   etag: '"C8IM8WTB9IZ8PMNMYPAKL88WP"',
20 verbose headers   age: '0',
20 verbose headers   connection: 'keep-alive',
20 verbose headers   'x-served-by': 'cache-hkg6821-HKG',
20 verbose headers   'x-cache': 'HIT',
20 verbose headers   'x-cache-hits': '1',
20 verbose headers   'x-timer': 'S1447229221.175715,VS0,VE949',
20 verbose headers   vary: 'Accept' }
21 silly get cb [ 304,
21 silly get   { date: 'Wed, 11 Nov 2015 08:07:01 GMT',
21 silly get     via: '1.1 varnish',
21 silly get     'cache-control': 'max-age=60',
21 silly get     etag: '"C8IM8WTB9IZ8PMNMYPAKL88WP"',
21 silly get     age: '0',
21 silly get     connection: 'keep-alive',
21 silly get     'x-served-by': 'cache-hkg6821-HKG',
21 silly get     'x-cache': 'HIT',
21 silly get     'x-cache-hits': '1',
21 silly get     'x-timer': 'S1447229221.175715,VS0,VE949',
21 silly get     vary: 'Accept' } ]
22 verbose etag https://registry.npmjs.org/passport from cache
23 verbose get saving passport to C:\Users\TAM\AppData\Roaming\npm-cache\registry.npmjs.org\passport\.cache.json
24 silly install normalizeTree
25 silly loadCurrentTree Finishing
26 silly loadIdealTree Starting
27 silly install loadIdealTree
28 silly cloneCurrentTree Starting
29 silly install cloneCurrentTreeToIdealTree
30 silly cloneCurrentTree Finishing
31 silly loadShrinkwrap Starting
32 silly install loadShrinkwrap
33 silly loadShrinkwrap Finishing
34 silly loadAllDepsIntoIdealTree Starting
35 silly install loadAllDepsIntoIdealTree
36 silly rollbackFailedOptional Starting
37 silly rollbackFailedOptional Finishing
38 silly runTopLevelLifecycles Starting
39 silly runTopLevelLifecycles Finishing
40 silly install printInstalled
41 verbose stack Error: Refusing to install passport as a dependency of itself
41 verbose stack     at checkSelf (C:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:40:14)
41 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
41 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
41 verbose stack     at chain (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
41 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:15:5
41 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
41 verbose stack     at Array.forEach (native)
41 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
41 verbose stack     at Array.forEach (native)
41 verbose stack     at asyncMap (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
42 verbose cwd C:\Users\TAM\Desktop\NodeJS\passport
43 error Windows_NT 10.0.10240
44 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "passport"
45 error node v5.0.0
46 error npm  v3.3.6
47 error code ENOSELF
48 error Refusing to install passport as a dependency of itself
49 error If you need help, you may report this error at:
49 error     <https://github.com/npm/npm/issues>
50 verbose exit [ 1, true ]

**Comment by johannestroeger** [comment]
`41 verbose stack Error: Refusing to install passport as a dependency of itself`
`C:\Users\TAM\Desktop\NodeJS\passport`

**rename your local folder** to something different than passport

**Comment by gbisaga** [comment]
And, more to the point, rename your project (according to package.json) to something different than "passport."

**Comment by KenanY** [comment]
Closing as resolved. The suggestions made already _should_ resolve the issue. If that is not the case, then I can easily reopen this.

**Comment by johannestroeger** [comment]
@KenanY IMO it is not only a windows issue :)

**Comment by KenanY** [comment]
@johannestroeger True, I just did that since that's what the OP had.
