### ISSUE TITLE
cant't get homebridge to start

### ISSUE THREAD

**Issue by Slepperpon** [npm/npm#10334]
Had working till power surge took out rpi replaced but now just cant get it to work here is what i have
pi@raspberrypi ~/homebridge $ npm run start
npm ERR! Linux 4.1.7-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.12

npm ERR! missing script: start
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/homebridge/npm-debug.log
pi@raspberrypi ~/homebridge $ node -v
v5.0.0
pi@raspberrypi ~/homebridge $ npm -v
u3.3.12
pi@raspberrypi ~/homebridge $ uname -a
Linux raspberrypi 4.1.7-v7+ #817 SMP PREEMPT Sat Sep 19 15:32:00 BST 2015 armv7l GNU/Linux
pi@raspberrypi ~/homebridge $ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/arm-linux-gnueabihf/4.9/lto-wrapper
Target: arm-linux-gnueabihf
Configured with: ../src/configure -v --with-pkgversion='Raspbian 4.9.2-10' --with-bugurl=file:///usr/share/doc/gcc-4.9/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.9 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.9 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libitm --disable-libquadmath --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.9-armhf/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.9-armhf --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.9-armhf --with-arch-directory=arm --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-sjlj-exceptions --with-arch=armv6 --with-fpu=vfp --with-float=hard --enable-checking=release --build=arm-linux-gnueabihf --host=arm-linux-gnueabihf --target=arm-linux-gnueabihf
Thread model: posix
gcc version 4.9.2 (Raspbian 4.9.2-10)

**Comment by Slepperpon** [comment]
here is npm debug
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'start' ]
2 info using npm@3.3.12
3 info using node@v5.0.0
4 verbose stack Error: missing script: start
4 verbose stack     at run (/usr/local/lib/node_modules/npm/lib/run-script.js:147:19)
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/run-script.js:57:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:345:5
4 verbose stack     at handleExists (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:318:20)
4 verbose stack     at FSReqWrap.cb [as oncomplete] (fs.js:216:19)
5 verbose cwd /home/pi/homebridge
6 error Linux 4.1.7-v7+
7 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
8 error node v5.0.0
9 error npm  v3.3.12
10 error missing script: start
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
```
10 error missing script: start
```

@Slepperpon So, I must ask, do you have a `"start"` script defined in your `package.json`? If not, then what are you _expecting_ `npm` to do when you run `npm start`? Are you sure that you are following [homebridge's installation instructions](https://github.com/nfarina/homebridge#installation) correctly?

**Comment by deennoo** [comment]
Got the same probleme, using this wiki how to install : https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi

thanks for your help

Uname - a : 
Linux localhost 3.4.67 #1 SMP PREEMPT Sun Jun 22 14:08:15 CST 2014 armv7l GNU/Linux

gcc --version : 
gcc (Debian 4.8.4-1) 4.8.4

node -v : 
v4.2.1

npm -v : 
2.14.7

**Comment by KenanY** [comment]
@Slepperpon It has been several months now with no reply from you. Are you still seeing this issue?

**Comment by Slepperpon** [comment]
After removing Harmony works just fine. 

Adam Hoffman
Aamco Transmission
Lee's Summit

**Comment by KenanY** [comment]
Closing as resolved, also not an issue with `npm`.
