### ISSUE TITLE
cordova@4.0.0 (cordova-lib) now fails to install since npm v3.3.10

### ISSUE THREAD

**Issue by freed00m** [npm/npm#10340]
I am now currently on nodejs lts argon 4.2.2 and the npm is v3.3.12
There is debug log http://pastebin.com/1b1WbXcR

Installing was OK before, now it can't do it.

```
npm install
```

Even npm install cordova@4.0.0 fails

package.json

```
{
  "author": "eMan s.r.o.",
  "name": "com.eman.dontpanic",
  "version": "0.0.1",
  "homepage": "https://github.com/ngbp/ngbp",
  "description": "Lost and found application",
  "licenses": {
    "type": "MIT",
    "url": "https://raw.github.com/ngbp/ngbp/master/LICENSE"
  },
  "bugs": "https://github.com/ngbp/ngbp/issues",
  "repository": {
    "type": "git",
    "url": "git@github.com:ngbp/ngbp.git"
  },
  "dependencies": {
    "bower": "^1.3.12",
    "cordova": "4.0.0"
  },
  "devDependencies": {
    "clone": "0.2.0",
    "clone-stats": "0.0.1",
    "gulp": "3.8.11",
    "gulp-angular-filesort": "1.0.4",
    "gulp-coffee": "2.2.0",
    "gulp-inject": "1.1.1",
    "gulp-jshint": "1.9.0",
    "gulp-less": "2.0.1",
    "gulp-plumber": "0.6.6",
    "gulp-template": "2.0.0",
    "gulp-util": "3.0.2",
    "http-server": "0.7.4",
    "jshint-stylish": "1.0.0",
    "less": "2.2.0",
    "main-bower-files": "2.5.0",
    "orchestrator": "0.3.7"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "http-server -a 0.0.0.0 -p 8000"
  }
}

```

The file it complaints about is there with OK permissions.

**Comment by freed00m** [comment]
I have downgraded to npm v3.3.8 and it installs all my deps, so there must be a bug

**Comment by BBosman** [comment]
I'm seeing the same behaviour (and downgrading fixed it for me as well).

It's not the `cordova` package itself that triggers this, but it's dependency `cordova-lib`. I see the same behaviour when installing other packages which have a dependency on that.

**Comment by BBosman** [comment]
Just did a quick test after upgrading to `npm` 3.5.2 and I don't see the issue anymore.

**Comment by freed00m** [comment]
@BBosman Thanks, do you use Node 5 and if so, does Ioinc / cordova works  with this version? I don't want to go through hassel to downgrade again, since compiling it takes hour.

**Comment by BBosman** [comment]
@freed00m Sorry for the late reply. Was out of the office for a few days due to the holidays.

`node --version`: v5.0.0
`npm --version`: 3.5.2
`cordova --version`: 5.4.1

We've been using this setup for about a week now without issues. I can't comment on Ionic as we don't use that.
