### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by ehajredini** [npm/npm#10359]
ekrem@ekrem-300E5EV-300E4EV-270E5EV-270E4EV:~/Desktop/bitshares-2-ui/web$ npm install
npm ERR! git fetch -a origin (http://github.com/valzav/react-foundation-apps.git) fatal: unable to access 'http://github.com/valzav/react-foundation-apps.git/': Recv failure: Connection reset by peer
npm ERR! Linux 3.19.0-33-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.2
npm ERR! npm  v3.3.12
npm ERR! code 128

npm ERR! Command failed: git fetch -a origin
npm ERR! fatal: unable to access 'http://github.com/valzav/react-foundation-apps.git/': Recv failure: Connection reset by peer
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ekrem/Desktop/bitshares-2-ui/web/npm-debug.log

**Comment by neilstuartcraig** [comment]
Hey @ehajredini - looks like a network error on the github side. Does the problem persist? Either way, it doesn't seem like a problem with npm.

**Comment by KenanY** [comment]
@ehajredini Are you still experiencing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
