### ISSUE TITLE
npm update --all

### ISSUE THREAD

**Issue by baelter** [npm/npm#10355]
I would love an ```update --all``` that traverses npm linked modules and updates them as well. Per now the workflow for a npm linked development environment is something like:

Go into all leaf modules.
```npm update```

Manually traverse up link tree.
```npm update```

Top node
```npm update```

Usually something doesn't work, so
```rm -rf node_modules```

Start clean.

Thoughts?

**Comment by othiym23** [comment]
Thanks for the suggestion! This is ultimately a workflow issue, I think. There are multiple competing workflows for doing simultaneous development of interrelated sets of packages, and right now there doesn't seem to be one clear pattern that everyone can or should follow.

We're going to work on fixing some of the rough edges of working with linked packages, to make sure that that piece of the CLI works as expected, but this is a whole, large area of functionality that we're not in a good place to spec out from first principles, and we're not likely to be in that place for a while. This sounds like something that could be done well as a third-party tool, and that's what we recommend people do. So, I'm going to close this feature request, but I think there's a good idea here!
