### ISSUE TITLE
Install has errors due to long path

### ISSUE THREAD

**Issue by Download** [npm/npm#10362]
Im installing a library with a lot of (nested) dependencies using this command:

`C:\Users\Frank\Documents\GitHub\morearty-react-router>npm install`

The I get a _lot_ of logging so I moved it to [pastebin/jQxMY32X](http://pastebin.com/jQxMY32X), but at some point it gets to this error message:

```
C:\Users\Frank\Documents\GitHub\morearty-react-router\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\utf-8-validate>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.targets(301,5): error MSB3491: Could not write lines to file "Release\obj\validation\validation.tlog\validation.lastbuildstate". Het opgegeven pad, de bestandsnaam of beide zijn te lang. De volledig gekwalificeerde bestandsnaam moet minder dan 260 tekens bevatten en de mapnaam minder dan 248 tekens. [C:\Users\Frank\Documents\GitHub\morearty-
react-router\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\utf-8
-validate\build\validation.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Frank\Documents\GitHub\morearty-react-router\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\utf-8-validate
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
```

I considered reporting it to `utf-8-validate`, but really it isn't their fault that their package is required so deep in the dependency hierarchy.

What am I to do?

EDIT: Forgot to mention. This dutch message:

`Het opgegeven pad, de bestandsnaam of beide zijn te lang. De volledig gekwalificeerde bestandsnaam moet minder dan 260 tekens bevatten en de mapnaam minder dan 248 tekens.`

means:

`The specified folder, filename or both are too long. The fully qualified filename should contain less than 12 characters and the folder name less than 248 characters`

**Comment by Download** [comment]
I found these issues:

 * [Too many dependencies break the Windows file system #3697](https://github.com/npm/npm/issues/3697)
 * [Node's nested node_modules approach is basically incompatible with Windows #6960](https://github.com/nodejs/node-v0.x-archive/issues/6960)

But they are both closed. I'm on NPM v3 so this should be fixed apparently?

**Comment by haggholm** [comment]
> But they are both closed. I'm on NPM v3 so this should be fixed apparently?

`npm@3` tends not to nest packages as deeply as older versions—it flattens the directory structure as much as possible—which means that extremely long paths are *less likely*. However, some in some scenarios “as much as possible” may not be flat enough, if you end up with dependency trees with incompatible versions.

I’m neither an npm developer nor a habitual Windows user, so if there is a solution, I don’t know it, except to check out the package at a less-deeply-nested path (e.g. not `C:\Users\Frank\Documents\GitHub\`) and hope for the best. It seems Microsoft still haven’t fixed it.

> Github and NPM are now the leading repositories for code - but as a Windows developer these are now a minefield. Workarounds with subst and UNC paths do not even come close to matching the hassles associated with this issue. The year is 2015 and Windows 10 still fails. 

[https://msdn.microsoft.com/en-ca/library/windows/desktop/aa365]

**Comment by Download** [comment]
@haggholm Thanks for your response. Do you know if there is a way to change the default module folder name from `node_modules` to something shorter? It seems to me to be the biggest win. 
Even if I check out in the root I only save 29 characters... And I really don't want to have all my Node projects in the root...

**Comment by haggholm** [comment]
Alas, [you can’t change it to anything other than `node_modules`](https://docs.npmjs.com/misc/faq#node-modules-is-the-name-of-my-deity-s-arch-rival-and-a-forbidden-word-in-my-religion-can-i-configure-npm-to-use-a-different-folder).

I can only guess that ultimately, npm was never designed with this weird limitation of Windows in mind.

**Comment by Download** [comment]
Well I have been ignoring the error and so far I don't seem to get bitten by it... But it's a bit disconcerting I have to say. Thanks for your help.

**Comment by refack** [comment]
Have you tried the "symlink" trick:
1. create a short path (less than 40 chars, like `c:\lpn_fix`) directory to keep short links to long paths
2. move your project to to `c:\lpn_fix\mrr`
3. `cd /d c:\lpn_fix\mrr & npm i`
3. run `mklink /D c:\lpn_fix\mrr "C:\Users\Frank\Documents\GitHub\morearty-react-router"`
