### ISSUE TITLE
can't install bower

### ISSUE THREAD

**Issue by Makadas** [npm/npm#10360]
I keep getting this error log when trying to install bower.
I used the command prompt "npm install -g bower"
Is there anybody than can shed some light?

0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files (x86)\nodejs\node.exe',
1 verbose cli   'C:\Program Files (x86)\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'bower' ]
2 info using npm@2.14.7
3 info using node@v4.2.2
4 verbose install initial load of C:\Users\Mitzi\AppData\Roaming\npm\package.json
5 verbose readDependencies loading dependencies from C:\Users\Mitzi\AppData\Roaming\npm\package.json
6 silly cache add args [ 'bower', null ]
7 verbose cache add spec bower
8 silly cache add parsed spec Result {
8 silly cache add   raw: 'bower',
8 silly cache add   scope: null,
8 silly cache add   name: 'bower',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '_',
8 silly cache add   type: 'range' }
9 silly addNamed bower@_
10 verbose addNamed "_" is a valid semver range for bower
11 silly addNameRange { name: 'bower', range: '_', hasData: false }
12 silly mapToRegistry name bower
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/bower
16 verbose addNameRange registry:https://registry.npmjs.org/bower not in flight; fetching
17 verbose request uri https://registry.npmjs.org/bower
18 verbose request no auth needed
19 info attempt registry request try #1 at 3:12:22 PM
20 verbose request id a315fd54d1c4786a
21 http request GET https://registry.npmjs.org/bower
22 info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND proxy.company.com proxy.company.com:8080
23 info attempt registry request try #2 at 3:12:32 PM
24 http request GET https://registry.npmjs.org/bower
25 info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND proxy.company.com proxy.company.com:8080
26 info attempt registry request try #3 at 3:13:32 PM
27 http request GET https://registry.npmjs.org/bower
28 verbose stack Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND proxy.company.com proxy.company.com:8080
28 verbose stack     at ClientRequest.onError (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:174:17)
28 verbose stack     at ClientRequest.g (events.js:260:16)
28 verbose stack     at emitOne (events.js:77:13)
28 verbose stack     at ClientRequest.emit (events.js:169:7)
28 verbose stack     at Socket.socketErrorListener (_http_client.js:259:9)
28 verbose stack     at emitOne (events.js:77:13)
28 verbose stack     at Socket.emit (events.js:169:7)
28 verbose stack     at connectErrorNT (net.js:996:8)
28 verbose stack     at doNTCallback2 (node.js:441:9)
28 verbose stack     at process._tickCallback (node.js:355:17)
29 verbose cwd C:\Users\Mitzi\Documents\web\conFusion
30 error Windows_NT 6.3.9600
31 error argv "C:\Program Files (x86)\nodejs\node.exe" "C:\Program Files (x86)\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "bower"
32 error node v4.2.2
33 error npm  v2.14.7
34 error code ECONNRESET
35 error network tunneling socket could not be established, cause=getaddrinfo ENOTFOUND proxy.company.com proxy.company.com:8080
35 error network This is most likely not a problem with npm itself
35 error network and is related to network connectivity.
35 error network In most cases you are behind a proxy or have bad network settings.
35 error network
35 error network If you are behind a proxy, please make sure that the
35 error network 'proxy' config is set properly.  See: 'npm help config'
36 verbose exit [ 1, true ]

**Comment by avindra** [comment]
Looks like you have a proxy issue. Are you on a company machine behind a firewall?

**Comment by Makadas** [comment]
I am not working for a company but private network from home. I checked the proxy settings and it returns null.
I checked with the internet provider and nothing wrong there. I switched firewall off and still not working. I downgraded to previous version of Node and even tried installing bower@1.2.6...still getting the same error.
I have no idea where to look anymore

**Comment by neilstuartcraig** [comment]
@Makadas It certainly does look like you have proxy configured in Windows - check you network settings.

If the above doesn't work, it looks like you can pass a `--no-proxy` argument when you `npm install` e.g. `npm install bower --no-proxy`. Does that work?
