### ISSUE TITLE
win 7 self signed certificate error

### ISSUE THREAD

**Issue by chrisbean33** [npm/npm#10364]
debug.log here:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli   'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'node-sass' ]
2 info using npm@2.14.7
3 info using node@v4.2.2
4 verbose install initial load of C:\Users\CHRIS960\AppData\Roaming\npm\package.json
5 verbose readDependencies loading dependencies from C:\Users\CHRIS960\AppData\Roaming\npm\package.json
6 silly cache add args [ 'node-sass', null ]
7 verbose cache add spec node-sass
8 silly cache add parsed spec Result {
8 silly cache add   raw: 'node-sass',
8 silly cache add   scope: null,
8 silly cache add   name: 'node-sass',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '_',
8 silly cache add   type: 'range' }
9 silly addNamed node-sass@_
10 verbose addNamed "_" is a valid semver range for node-sass
11 silly addNameRange { name: 'node-sass', range: '_', hasData: false }
12 silly mapToRegistry name node-sass
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/node-sass
16 verbose addNameRange registry:https://registry.npmjs.org/node-sass not in flight; fetching
17 verbose request uri https://registry.npmjs.org/node-sass
18 verbose request no auth needed
19 info attempt registry request try #1 at 4:01:22 PM
20 verbose request id c4fbbad73babc1bd
21 http request GET https://registry.npmjs.org/node-sass
22 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
23 info attempt registry request try #2 at 4:01:32 PM
24 http request GET https://registry.npmjs.org/node-sass
25 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
26 info attempt registry request try #3 at 4:02:32 PM
27 http request GET https://registry.npmjs.org/node-sass
28 verbose stack Error: self signed certificate in certificate chain
28 verbose stack     at Error (native)
28 verbose stack     at TLSSocket.<anonymous> (_tls_wrap.js:1003:38)
28 verbose stack     at emitNone (events.js:67:13)
28 verbose stack     at TLSSocket.emit (events.js:166:7)
28 verbose stack     at TLSSocket._finishInit (_tls_wrap.js:570:8)
29 verbose cwd C:\Users\CHRIS960
30 error Windows_NT 6.1.7601
31 error argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "node-sass"
32 error node v4.2.2
33 error npm  v2.14.7
34 error code SELF_SIGNED_CERT_IN_CHAIN
35 error self signed certificate in certificate chain
36 error If you need help, you may report this error at:
36 error     https://github.com/npm/npm/issues
37 verbose exit [ 1, true ]

**Comment by brumleygap** [comment]
Same issue on Windows 7 trying to install protractor:
npm-debug.log here:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'protractor' ]
2 info using npm@2.14.7
3 info using node@v4.2.2
4 verbose install initial load of C:\Users\ebraganz\AppData\Roaming\npm\package.json
5 verbose readDependencies loading dependencies from C:\Users\ebraganz\AppData\Roaming\npm\package.json
6 silly cache add args [ 'protractor', null ]
7 verbose cache add spec protractor
8 silly cache add parsed spec Result {
8 silly cache add   raw: 'protractor',
8 silly cache add   scope: null,
8 silly cache add   name: 'protractor',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 silly addNamed protractor@*
10 verbose addNamed "*" is a valid semver range for protractor
11 silly addNameRange { name: 'protractor', range: '*', hasData: false }
12 silly mapToRegistry name protractor
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/protractor
16 verbose addNameRange registry:https://registry.npmjs.org/protractor not in flight; fetching
17 verbose request uri https://registry.npmjs.org/protractor
18 verbose request no auth needed
19 info attempt registry request try #1 at 12:14:33 PM
20 verbose request id d3404a01e7237dea
21 http request GET https://registry.npmjs.org/protractor
22 http 200 https://registry.npmjs.org/protractor
23 verbose headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
23 verbose headers   etag: '"1RY0CAZ28IFOOC8KXZF5STXCU"',
23 verbose headers   'content-type': 'application/json',
23 verbose headers   'cache-control': 'max-age=60',
23 verbose headers   'content-length': '97194',
23 verbose headers   'accept-ranges': 'bytes',
23 verbose headers   date: 'Fri, 13 Nov 2015 17:14:34 GMT',
23 verbose headers   via: '1.1 varnish',
23 verbose headers   age: '23',
23 verbose headers   connection: 'keep-alive',
23 verbose headers   'x-served-by': 'cache-jfk1023-JFK',
23 verbose headers   'x-cache': 'HIT',
23 verbose headers   'x-cache-hits': '1',
23 verbose headers   'x-timer': 'S1447434874.129828,VS0,VE1',
23 verbose headers   vary: 'Accept' }
24 silly get cb [ 200,
24 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
24 silly get     etag: '"1RY0CAZ28IFOOC8KXZF5STXCU"',
24 silly get     'content-type': 'application/json',
24 silly get     'cache-control': 'max-age=60',
24 silly get     'content-length': '97194',
24 silly get     'accept-ranges': 'bytes',
24 silly get     date: 'Fri, 13 Nov 2015 17:14:34 GMT',
24 silly get     via: '1.1 varnish',
24 silly get     age: '23',
24 silly get     connection: 'keep-alive',
24 silly get     'x-served-by': 'cache-jfk1023-JFK',
24 silly get     'x-cache': 'HIT',
24 silly get     'x-cache-hits': '1',
24 silly get     'x-timer': 'S1447434874.129828,VS0,VE1',
24 silly get     vary: 'Accept' } ]
25 verbose get saving protractor to C:\Users\ebraganz\AppData\Roaming\npm-cache\registry.npmjs.org\protractor\.cache.json
26 verbose makeDirectory C:\Users\ebraganz\AppData\Roaming\npm-cache creation not in flight; initializing
27 verbose makeCacheDir UID & GID are irrelevant on win32
28 silly addNameRange number 2 { name: 'protractor', range: '*', hasData: true }
29 silly addNameRange versions [ 'protractor',
29 silly addNameRange   [ '0.1.0',
29 silly addNameRange     '0.1.1',
29 silly addNameRange     '0.1.2',
29 silly addNameRange     '0.1.3',
29 silly addNameRange     '0.2.0',
29 silly addNameRange     '0.2.1',
29 silly addNameRange     '0.3.0',
29 silly addNameRange     '0.4.0',
29 silly addNameRange     '0.4.1',
29 silly addNameRange     '0.5.0',
29 silly addNameRange     '0.6.1',
29 silly addNameRange     '0.7.0',
29 silly addNameRange     '0.8.0',
29 silly addNameRange     '0.9.0',
29 silly addNameRange     '0.10.0',
29 silly addNameRange     '0.11.0',
29 silly addNameRange     '0.12.0',
29 silly addNameRange     '0.12.1',
29 silly addNameRange     '0.13.0',
29 silly addNameRange     '0.14.0',
29 silly addNameRange     '0.15.0',
29 silly addNameRange     '0.16.0',
29 silly addNameRange     '0.16.1',
29 silly addNameRange     '0.17.0',
29 silly addNameRange     '0.18.0',
29 silly addNameRange     '0.18.1',
29 silly addNameRange     '0.19.0',
29 silly addNameRange     '0.20.0',
29 silly addNameRange     '0.20.1',
29 silly addNameRange     '0.21.0',
29 silly addNameRange     '0.22.0',
29 silly addNameRange     '0.23.0',
29 silly addNameRange     '0.23.1',
29 silly addNameRange     '0.24.0',
29 silly addNameRange     '0.24.1',
29 silly addNameRange     '0.24.2',
29 silly addNameRange     '1.0.0-rc1',
29 silly addNameRange     '1.0.0-rc2',
29 silly addNameRange     '1.0.0-rc3',
29 silly addNameRange     '1.0.0-rc4',
29 silly addNameRange     '1.0.0-rc5',
29 silly addNameRange     '1.0.0-rc6',
29 silly addNameRange     '1.0.0',
29 silly addNameRange     '1.1.0',
29 silly addNameRange     '1.1.1',
29 silly addNameRange     '1.2.0-beta1',
29 silly addNameRange     '1.2.0',
29 silly addNameRange     '1.3.0',
29 silly addNameRange     '1.3.1',
29 silly addNameRange     '1.4.0',
29 silly addNameRange     '1.5.0',
29 silly addNameRange     '1.6.0',
29 silly addNameRange     '1.6.1',
29 silly addNameRange     '1.7.0',
29 silly addNameRange     '1.8.0',
29 silly addNameRange     '2.0.0',
29 silly addNameRange     '2.1.0',
29 silly addNameRange     '2.2.0',
29 silly addNameRange     '2.3.0',
29 silly addNameRange     '2.4.0',
29 silly addNameRange     '2.5.0',
29 silly addNameRange     '2.5.1' ] ]
30 silly addNamed protractor@2.5.1
31 verbose addNamed "2.5.1" is a plain semver version for protractor
32 silly mapToRegistry name protractor
33 silly mapToRegistry using default registry
34 silly mapToRegistry registry https://registry.npmjs.org/
35 silly mapToRegistry uri https://registry.npmjs.org/protractor
36 verbose addRemoteTarball https://registry.npmjs.org/protractor/-/protractor-2.5.1.tgz not in flight; adding
37 verbose addRemoteTarball [ 'https://registry.npmjs.org/protractor/-/protractor-2.5.1.tgz',
37 verbose addRemoteTarball   '03d6c93cd7c268f4250177d55a2fec8a198372cd' ]
38 info retry fetch attempt 1 at 12:14:35 PM
39 info attempt registry request try #1 at 12:14:35 PM
40 http fetch GET https://registry.npmjs.org/protractor/-/protractor-2.5.1.tgz
41 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
42 info attempt registry request try #2 at 12:14:46 PM
43 http fetch GET https://registry.npmjs.org/protractor/-/protractor-2.5.1.tgz
44 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
45 info attempt registry request try #3 at 12:15:46 PM
46 http fetch GET https://registry.npmjs.org/protractor/-/protractor-2.5.1.tgz
47 error fetch failed https://registry.npmjs.org/protractor/-/protractor-2.5.1.tgz
48 warn retry will retry, error on last attempt: Error: self signed certificate in certificate chain
49 info retry fetch attempt 2 at 12:15:57 PM
50 info attempt registry request try #1 at 12:15:57 PM
51 http fetch GET https://registry.npmjs.org/protractor/-/protractor-2.5.1.tgz
52 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
53 info attempt registry request try #2 at 12:16:07 PM
54 http fetch GET https://registry.npmjs.org/protractor/-/protractor-2.5.1.tgz
55 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
56 info attempt registry request try #3 at 12:17:16 PM
57 http fetch GET https://registry.npmjs.org/protractor/-/protractor-2.5.1.tgz
58 error fetch failed https://registry.npmjs.org/protractor/-/protractor-2.5.1.tgz
59 warn retry will retry, error on last attempt: Error: self signed certificate in certificate chain
60 info retry fetch attempt 3 at 12:18:17 PM
61 info attempt registry request try #1 at 12:18:17 PM
62 http fetch GET https://registry.npmjs.org/protractor/-/protractor-2.5.1.tgz
63 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
64 info attempt registry request try #2 at 12:18:27 PM
65 http fetch GET https://registry.npmjs.org/protractor/-/protractor-2.5.1.tgz
66 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
67 info attempt registry request try #3 at 12:19:28 PM
68 http fetch GET https://registry.npmjs.org/protractor/-/protractor-2.5.1.tgz
69 error fetch failed https://registry.npmjs.org/protractor/-/protractor-2.5.1.tgz
70 verbose stack Error: self signed certificate in certificate chain
70 verbose stack     at Error (native)
70 verbose stack     at TLSSocket.<anonymous> (_tls_wrap.js:1003:38)
70 verbose stack     at emitNone (events.js:67:13)
70 verbose stack     at TLSSocket.emit (events.js:166:7)
70 verbose stack     at TLSSocket._finishInit (_tls_wrap.js:570:8)
71 verbose cwd C:\
72 error Windows_NT 6.1.7601
73 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "protractor"
74 error node v4.2.2
75 error npm  v2.14.7
76 error code SELF_SIGNED_CERT_IN_CHAIN
77 error self signed certificate in certificate chain
78 error If you need help, you may report this error at:
78 error     <https://github.com/npm/npm/issues>
79 verbose exit [ 1, true ]

**Comment by brumleygap** [comment]
My issue was fixed by running "npm config set strict-ssl false" because I am behind a firewall. If you are also using a proxy other configuration may be needed.

**Comment by JerinJ** [comment]
Even i faced same issue while doing any "npm install -g XXX" command, it was resolved by "npm config set strict-ssl false"

Thanks @brumleygap.
