### ISSUE TITLE
Get sizes of installed packages

### ISSUE THREAD

**Issue by davej** [npm/npm#10361]
With npm 2.x, I could do easily go into the node-modules folder and inspect a folder to find out the modules' size on disk. With npm 3 and flat deps this isn't possible (it's not that unusual for the node_modules dir of a large project to have 1,000+ directories).

This isn't a big problem for most node applications but when using something like Electron it's important to have a handle on the size of modules so that you can keep the final binary size as small as possible. 

Possible API:

```
> npm size
└── standard@3.13.2     1.54MB
└── fix-path@1.1.0      2.34MB
└── mkdirp@0.5.1        0.43MB
└── node-uuid@1.4.3     1.11MB
```

```
> npm size --depth=1
└─┬ standard@3.13.2     1.54MB
│ ├── deglob@1.0.1      0.33MB
│ ├── dezalgo@1.0.3     0.82MB
│ └── ...               x.xxMB
└─┬ fix-path@1.1.0      2.31MB
  ├── ...               x.xxMB
  └── ...               x.xxMB
```

```
> npm size standard
└─┬ standard@4.5.4           1.54MB
  ├─┬ deglob@1.0.1           0.33MB
  │ ├─┬ glob@5.0.15          0.11MB
  │ │ ├─┬ inflight@1.0.4     0.04MB
  │ │ │ └── wrappy@1.0.1     0.03MB
  │ │ ├── inherits@2.0.1     0.07MB
```

**Comment by davej** [comment]
Related to #4638, although the scope of this issue is larger.

Another thought on this... it would be best to right-align the module size. That would make it much easier to read and compare sizes. For example.

```
└── standard@3.13.2       1.54MB
└── fix-path@1.1.0      112.34MB
```

**Comment by KenanY** [comment]
Well this is in the works: https://github.com/npm/npm/pull/9920

**Comment by davej** [comment]
Thanks @KenanY, after looking at #9920 it looks like `npm ls --with-sizes` is probably better than adding a new `size` sub-command. It looks like that PR only supports `npm install` though (not `npm ls`).

**Comment by mikermcneil** [comment]
I put together https://github.com/mikermcneil/kit#kit-deps as a stopgap for this in case it's helpful for anyone (cc @davej)

**Comment by mikermcneil** [comment]
(see also @siddharthkp's [`cost-of-modules`](https://www.npmjs.com/package/cost-of-modules)!  If you're interested in a rich, deliberate report rather than incidental estimation, his is way better than mine.  Also, mine only works on NPM 2... so yeah.  There's that.)

**Comment by siddharthkp** [comment]
@mikermcneil Thanks for the mention! ❤

**Comment by pastelsky** [comment]
Also, if you're more interested in the size impact of a module post bundling and minifying, rather than its size on disk, I wrote a small online utility that can tell you that-
https://cost-of-modules.herokuapp.com (not related to @siddharthkp 's awesome package)

EDIT: It's now moved to https://bundlephobia.com

**Comment by blockscoped** [comment]
Could you not just use `du -sh node_modules`  or `du -sh node_modules/<pkg-name>` ?
Assume there's a Window equivalent too.

**Comment by pastelsky** [comment]
@blockscoped That will only give you the size of the package pulled from npm. It's actual size once it goes into your bundle can be very different. This can be because of several factors like -  npm packages shipping with long README's, uniminified files, test cases, or multiple module types of the same package (AMD/ES6 etc.)

**Comment by siddharthkp** [comment]
@blockspeed

From [cost-of-modules readme](https://github.com/siddharthkp/cost-of-modules):

> With npm 2.x, it was easy to find how much space is each of your dependencies taking. You could just look at the size of each directory in node_modules

Exactly what you suggested. But,

> With npm 3, the packages are installed in flat manner, so it isn't so straightforward.

You will not get the next level dependencies, because it's all flat.

**Comment by arve0** [comment]
For those interested, I've created [npm-download-size](https://arve0.github.io/npm-download-size/) which resolves dependencies and calculates size for tarballs without downloading any packages. The total size of all tarballs gives you a good estimate if a given package is bloated.

The [cli tool](https://github.com/arve0/npm-download-size-cli) can be used [like this](https://asciinema.org/a/GqCnDlllrI0YtJgc7BkxisCla):

```
$ download-size request
request@2.83.0: 1.08 MiB
```
