### ISSUE TITLE
I don't know what happened, however,i install cordova but here many error

### ISSUE THREAD

**Issue by Doralvor** [npm/npm#10374]
<img width="572" alt="2015-11-13 10 43 05" src="https://cloud.githubusercontent.com/assets/12453529/11137519/63e305c2-89f3-11e5-9ded-b052f2bf98b8.png">

**Comment by OmgImAlexis** [comment]
Please replace the image with the output of the command and make sure to wrap your code like [this](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks).
