### ISSUE TITLE
Feature Request: testDependencies, buildDependencies

### ISSUE THREAD

**Issue by preflight** [npm/npm#10375]
With packages becoming more modular (e.g., Babel, React, Karma, Webpack), it may be beneficial to have two additional options for separating dependencies in `package.json` besides the ones already available: `testDependencies` and `buildDependencies`.

The primary benefit is simply organization: seeing your test and build dependencies in their own dedicated sections vs. scanning a list of 40+ installed packages. It may also be useful for configuring bundling tools such as Webpack and Browserify.

I'm probably not the first person to think of this, although I don't see it discussed in the Issue archive. I also realize there are some cons:
* opens a "can of worms" leading to more requests for new sections
* dev dependencies are usually either test or build deps, so having both may be overkill
* some dependencies may cross over between build and test

**Comment by jacobrask** [comment]
Why did you close this?

My issue is that our build takes a very long time. We only need babel and webpack to build, but npm install also installs eslint with plugins, and all testing utilities, development server, etc.

**Comment by itsthatguy** [comment]
@jacobrask I created a package exactly for this: https://github.com/itsthatguy/group-dependencies
