### ISSUE TITLE
npm install algolia search

### ISSUE THREAD

**Issue by peddirajukondaveeti** [npm/npm#10377]
I have done like this 

D:\Peddi\algoliasearch-client-js>npm install algoliasearch

But  i have got error like this

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Pro
node_modules\\npm\\bin\\npm-cli.js" "install" "algoliasearch
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ENOSELF

npm ERR! Refusing to install algoliasearch as a dependency o
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support
npm ERR!     D:\Peddi\algoliasearch-client-js\npm-debug.log

Please suggest me how to solve this issue.

**Comment by bobylito** [comment]
Given the name of your folder, it seems that you are trying to install `algoliasearch` as a dependency of `algoliasearch` project (this package is algoliasearch-client-js on github and given the name of the folder it seems like a clone of it). This does not make sense. If you want to use algolia search in one of your project, then you should `npm install algoliasearch` in your own project.

**Comment by peddirajukondaveeti** [comment]
D:\Peddi\algoliasearch-client-js-master>npm install algoliasearch --save

I have done like this But we are getting same error as mentioned in previous error

Please suggest me.How to resolve this issue.

**Comment by KenanY** [comment]
@peddirajukondaveeti I don't understand, why are you trying to install `algoliasearch` in a directory which contains the source code for `algoliasearch`? I can suggest solutions only if you explain what you are trying to accomplish, otherwise my advice would be: don't install `algoliasearch` in that directory.

**Comment by peddirajukondaveeti** [comment]
![js1](https://cloud.githubusercontent.com/assets/15833392/11175459/78394114-8c58-11e5-9e0a-e9cf51c494ba.png)

I have Download code as shown in Above screenshot
and add apikey and applicationId inNode.js

When i run Autocomplete.html page is displays following error as shown in below screenshot

![js2](https://cloud.githubusercontent.com/assets/15833392/11175508/fadb52ba-8c58-11e5-93db-e630b7b88c45.png)


 Please suggest me how to resolve this issue

**Comment by KenanY** [comment]
@peddirajukondaveeti So, this isn't a `npm` issue then. You can't really just open that file in your web browser. You have to spin up an HTTP server (which that algolia project has a `npm` script for):

```
cd algoliasearch-client-js
npm install
npm run examples
```

Works for me at least.

**Comment by KenanY** [comment]
Closing as not an issue with `npm`. If you are still seeing this issue, @peddirajukondaveeti, feel free to let me know and I can reopen this.
