### ISSUE TITLE
preinstall execution order in npm@3.x

### ISSUE THREAD

**Issue by brianc** [npm/npm#10379]
Sorry if this has been brought up before, but it looks like the preinstall step for my local repo now runs _after_ dependent modules have been installed with `npm@3.x`?

With `npm@2.x` we used the preinstall hook to delete our `node_modules` folder & clone it from a git repo...so then the `install` step would execute, see that everything was already installed, and do nothing.  With `npm@3.x` we have the same `preinstall` hook, but first npm does an install into the `node_modules` folder itself _then_ it runs the `preinstall` hook.  Is this a bug?  It seems like its not really a "pre-install" step anymore if it actually fires _after_ the install...

**Comment by thepont** [comment]
I'm also seeing this issue. I'm attempting to uninstall a local module, so a fresh version of the module is installed on each install.

The result is that the module is not installed at all after running an `npm install` 

I'm running npm@3.3.6

**Comment by gbisset** [comment]
I've also just come across this issue on npm v3.4.0.

We were also deleting the node_modules folder in the preinstall step.  As it now runs after the packages have been installed, they are being deleted immediately after install which was causing our postinstall to fail as it depends on the installed packages

**Comment by awestroke** [comment]
I am affected by this too. I am very, very curious as to why this change was made. It seems completely nonsensical and unnecessary.

**Comment by ErisDS** [comment]
Also facing this issue. We're using a preinstall hook (following advice of @othiym23) to check for a compatible node version before install. Otherwise, the install fails on incompatible dependencies, and our users end up reporting issues on the dependency repos rather than realising they have an unsupported version.

**Comment by alexflorisca** [comment]
Same issue. We are trying to run a script before `npm install` runs (which sets up an auth token) in order to install a package from a private repository. This is screwing our heroku deployment!

**Comment by wookiehangover** [comment]
I'm also running into some pain with this bug... `preinstall` is a really useful hook and this makes it way less useful!

**Comment by iarna** [comment]
I would like to return this to npm@2 style behavior, running `npm install` much earlier.

Running this before we figure out what we would do (that is, before we produce the idealized tree) is pretty easy and supports most of the use cases. Slightly more awkward is supporting the "preinstall mutates the tree in ways install should account for" use case, but it should still be doable.

**Comment by ErisDS** [comment]
@iarna Did you mean running `preinstall` earlier?

**Comment by holm** [comment]
Any update on getting this back to how it worked in npm@2? Doesn't make much since to me that preinstall is run after install, and this is also breaking backwards compability. 

Any reason why this was changed in the first place?

**Comment by kevireilly** [comment]
While this doesn't solve the order of operations issue, this might be an option for those looking to verify the node version and throw an error at least at some point in the installation routine. By all means open to better suggestions.

package.json
````
{
  "scripts": {
    "preinstall": "npm install check-node-version && check-node-version --node '~4'"
  }
}
````

**Comment by iarna** [comment]
@ErisDS Yes =D

**Comment by jhicken** [comment]
I have an issue with this aswell. We and using a private scoped version of npm. Aswell as the public npm repo. We are trying to set something like this `npm config set @awesomScope:registry https://aswesomerepo.com/repo` as a preinstall script. The purpose of this would be when the install is run the scope is setup without having to run extra commands.

It currently fails on npm 3.5.3

It looks like the packages are not exactly installed before the preinstall but they are parsed and checked somehow. During the parse and check phase it fails due to the scope not being defined. That makes me :(

Any help here would be great.

**Comment by awestroke** [comment]
@jhicken I solved this by having a .npmrc checked in in the project directory (same level as package.json), where I specify the registry config line:

```
registry = "http://internal-server.company.com:3333"
```

Verify using `npm config get registry`

**Comment by jhicken** [comment]
@awestroke Thanks man. That did the trick. That said I still think this should be fixed.

**Comment by toddtarsi** [comment]
+1 For this issue needing a fix. I have private git dependencies in Azure web apps, and I used this hook to clear these out before the install itself ran.

**Comment by ahmadnassri** [comment]
confirmed this issue today, easy to repeat:

```json
"scripts": {
    "preinstall": "rm -rf node_modules"
}
```

**Comment by peter-mouland** [comment]
Have we managed to get agreement yet as which is the desired behaviour from the core contributors,  v2 or v3?

It would be nice to know if there is a desire to change this or not so that our current 'workarounds' need to be made permanent or not.

**Comment by jhicken** [comment]
@peter-mouland That ^

**Comment by seriema** [comment]
@peter-mouland (and @jhicken) I think they did agree that this wasn't the intended behaviour:

> iarna added the bug label on Dec 9, 2015

**Comment by othiym23** [comment]
There are a few conflated concerns in this thread so far, so let me see if I can make things a little clearer.

> We are trying to set something like this `npm config set @awesomScope:registry https://aswesomerepo.com/repo` as a preinstall script.

This is something that's probably not going to be supported by npm – npm's configuration should be considered immutable for the duration of an install or lifecycle script execution. I'd be interested to know why the existing registry management settings / using a package-specific `.npmrc` won't work here, but that should be opened as a separate issue.

> Any reason why this was changed in the first place?

Yes – to get the scripts out of `package.json` requires a call to `read-package-json`, which is expensive, and in many cases has been replaced with the even more expensive `read-installed`, which scans the entire installed package tree. For performance reasons, npm makes as few calls to those packages as possible. However, it seems like this is a case in which we'll need to make an exception.

> Have we managed to get agreement yet as which is the desired behaviour from the core contributors, v2 or v3?

As @iarna said up-thread:

> I would like to return this to npm@2 style behavior, running ~~`npm install`~~`preinstall` much earlier.
> 
> Running this before we figure out what we would do (that is, before we produce the idealized tree) is pretty easy and supports most of the use cases. Slightly more awkward is supporting the "preinstall mutates the tree in ways install should account for" use case, but it should still be doable.

The CLI team is in the middle of a project to fix its test suite right now, and afterwards will be getting back to addressing high-priority bugs in npm. Since this isn't a crasher, it's not a `big-bug`, so it may be a little while until we get to it, but a patch that deals with the considerations raised by @iarna would be very helpful.

**Comment by VictorBjelkholm** [comment]
This is breaking some smaller projects for me, I would be happy to try creating a patch for it.

Since it's my first deep-dive into the codebase, could someone give some guidance on where I could start to try and fix it?

**Comment by VictorBjelkholm** [comment]
So I did my best to try and fix this but I couldn't. With no guidance, the codebase was too hard for me to understand... 

But in hope that someone else is knowledgeable enough to be able to fix it, I've posted a bounty on bountysource for this issue.

https://www.bountysource.com/issues/28223555-preinstall-execution-order-in-npm-3-x

**Comment by kazazor** [comment]
+1 on fixing this one.
We're also dealing with this issue and would love to see it fixed so we could use npm@3 without the need to change the current way we're working.

@othiym23 - do you have any estimation when you'll finish with the ```big-bugs``` and something like this one could be resolved?

**Comment by danielgefen** [comment]
+1 also on fixing it.
It took me a while to understand it was the npm version which was causing this preinstall issue. Eventually, I had to go back to using npm@2.

**Comment by OmriAharon** [comment]
+1

**Comment by gregra81** [comment]
+1

**Comment by incrediapp** [comment]
+1

**Comment by brauliodiez** [comment]
+1

**Comment by ArnaudRinquin** [comment]
I have [written a test](https://github.com/npm/npm/compare/master...ArnaudRinquin:fix10379/preinstall-execution-order?expand=1) that is currently failing but should be passing once this is fixed.

I tried a few things but couldn't make it pass. Help welcome!

**Comment by creative-eye** [comment]
+1

**Comment by DenianArthurShades** [comment]
> Yes – to get the scripts out of package.json requires a call to read-package-json, which is expensive, and in many cases has been replaced with the even more expensive read-installed, which scans the entire installed package tree. For performance reasons, npm makes as few calls to those packages as possible.

I really don't get your logic, here. You obviously _do_ read the file, otherwise the preinstall script wouldn't be run at all. Just run the scripts in the right order - it can't be _that_ complicated!

> Since this isn't a crasher, it's not a big-bug, so it may be a little while until we get to it

It's been three more months. This bug is _obvious_ - I mean, the script is even labelled "preinstall", as in "runs before install"! Are you finally going to fix it, now?

**Comment by VictorBjelkholm** [comment]
@DenianArthurShades hey, I've tried to fix this issue but with no guidance and code being kind of complicated, I gave up. At least it was too complicated for me.

But since it seems simple, please try to fix it, I'll help out however I can.

**Comment by ArnaudRinquin** [comment]
@DenianArthurShades 

> it can't be that complicated!

Given the related code, yes it can. Like @VictorBjelkholm, I tried to fix it without success.

Also I don't think this _imperative_ tone helps.

**Comment by DenianArthurShades** [comment]
> Given the related code, yes it can. Like @VictorBjelkholm, I tried to fix it without success.

I'm not saying it's a matter of a few minutes - or even the few hours to several days both of you probably spent on it, if one doesn't know the code - but it's been half a year. There has to be _someone_ who knows the code well enough to find this error in such a timeframe.

> Also I don't think this imperative tone helps.

While I do apologize for my tone, I think you'll probably agree that you'd be annoyed (and, maybe, as abrasive as me - depending on your personality) if a faulty upgrade of a package manager, of all things, breaks your toolchain just before a deadline. Reading the entry by @othiym23 basically calling this a non-priority when there are people who might just rely on such a tool working correctly didn't do much to cool my temper, either.

The question still remains, is somebody actually working on this or is it still "not a big-bug" because, hey, order of code execution doesn't matter?

**Comment by holm** [comment]
We are also getting increasingly frustrated with the many bugs in npm-cli. While we are extremely grateful for the service, and pay for private packages, we are questioning the long-term feasibility of using npm. When very critical issues like https://github.com/npm/npm/issues/5082, a myriad of shrinkwrap bugs and issues like this, are left open for months and months, I am worried for the future of npm. Even with a very broad communitiy of developers, no one has yet been able to fix this issue, which from the outside seems like something that should be relatively trivial to fix.

While there can be many reasons for ending up in a situation like this, I wonder if it might be time for npm to shed a significant portion of it's bagage, drop support for a lot of edge-cases, rarely used features and backwards compability, and try to return to a more predictable and maintanable system.

**Comment by CodeJjang** [comment]
Come on, such an important feature... it's a shame it hasn't been fixed yet :(

**Comment by danielsantiago** [comment]
Having the same problem :/

**Comment by palmerj3** [comment]
Hi all - please see the referenced PR. If you have some time I would love for you to test it out. Locally I wrote a small preinstall task which would fail if the "node_modules" folder was there. Then I would rm -rf the folder and run npm install. On master this task failed but with my PR it passes. There could be edge cases I haven't thought of or handled so please test it out and provide some feedback. ping @CodeJjang @danielsantiago @holm @ArnaudRinquin

**Comment by VictorBjelkholm** [comment]
@othiym23 any updates on how feasible @palmerj3's PR is to be merged? Seems like people here in the PR are not alone in hitting this problem.

**Comment by VictorBjelkholm** [comment]
Seems like this can be closed now! Judging by @iarna's comment in PR #13259 

<img width="733" alt="image" src="https://cloud.githubusercontent.com/assets/459764/17634101/340262de-60d1-11e6-8785-be858f451af8.png">

https://github.com/npm/npm/pull/13259#issuecomment-239255539

**Comment by plurch** [comment]
@VictorBjelkholm I just tested this with npm@3.10.7 which includes #13259 and it looks like the 'preinstall' step is still happening after module dependencies have been installed. So, this issue doesn't appear to be resolved yet.

**Comment by palmerj3** [comment]
@plurch do me a favor and set a preinstall task in your top level app to throw if the node_modules folder exists. Then remove the node_modules folder and reinstall.

**Comment by plurch** [comment]
@palmerj3 I am trying to create a preinstall hook that will remove a local dependency so that 'npm install' will pull in the current version of local dependency. This is an attempt at working around #7426 .

I have tried these and neither seems to work:

```
"preinstall": "rm -rf ./node_modules/my-module",

"preinstall": "npm uninstall my-module",
```

**Comment by palmerj3** [comment]
@plurch yeah any operations that modify the tree preinstall are not supported right now because, while preinstall still does run BEFORE modules are installed (correct), it does not run before the tree is calculated from disk. So, in your case, npm thinks the module is already there and up-to-date, so when you remove it it won't attempt to reinstall.  Honestly your use case is one that is not very common.. I would suggest using `npm link my-module` in order for you to achieve what you're after.

**Comment by plurch** [comment]
@palmerj3 Thanks for the information. I will try `npm link my-module`

**Comment by tomyf** [comment]
@plurch I just encountered the same problem as yours (and the `npm link` command has a strange behaviour....). Instead, I made : 
```
"postinstall": "npm uninstall my-module && npm install my-module"
```

This hack is ugly since it may download twice the package, yet, as it is a problem being investigated since a while and since it will be eventually patched, it is acceptable as it does not break the CI chain I have.

Hope it helps :)

**Comment by serut** [comment]
Same issue with `npm 3.10.5`. My install process is now : 
````
npm run preinstall
npm install
```
+1 for fix :goat:

**Comment by jishi** [comment]
This is still an issue, if you have a preinstall step that does an `uninstall` or removes files, the files will still be removed after the installation is done, even in 3.10.9. I guess this only affect npm install for the current application, and preinstall works as expected when installing an npm module? Because otherwise I'm surprised that this hook exist at all.

**Comment by tomyf** [comment]
@jishi I forgot to mention that this workaround brings an other problem : the package _common-module_ will not follow the declared version within your package.json . For standard use cases, it should be good, but be careful when you need a certain version of your common module when you build.

Cheers !

**Comment by monolithed** [comment]
`preinstall`  should be marked as broken. `preinstall`, `prebuplish` what else? I really don't understand why is not fixed.

**Comment by STRML** [comment]
This was fixed in 3.10.8 via https://github.com/npm/npm/pull/13259

**Comment by monolithed** [comment]
@STRML, have you tested yourself? I see this issue with 3.10.8

**Comment by STRML** [comment]
Yes, I have tested it, and there is a test in the repo confirming the behavior. https://github.com/npm/npm/blob/v3.10.8/test/tap/lifecycle-order.js

**Comment by monolithed** [comment]
I can confirm that. 

### supporting information:

 - `npm -v` prints: 3.10.8
 - `node -v` prints: v7.0.0
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?: Darwin

**Comment by STRML** [comment]
Could you post what you're running that exhibits the issue?

**Comment by monolithed** [comment]
```js
{
	"name": "@qa/npm-cache",
	"version": "0.0.4",
	"description": "Provides a caching service for npm packages",
	"author": "Mail.Ru Group Limited",
	"license": "UNLICENSED",

	"maintainers": [
		{
			"name": "Alexander Abashkin",
			"email": "<a.abashkin@corp.mail.ru>"
		}
	],

	"repository": {
		"type": "git",
		"url": "ssh://git@stash.mail.ru:2222/qa/npm-cache.git"
	},

	"engines": {
		"node": ">=6.2",
		"npm": ">=3.8"
	},

	"bin": {
		"npm-cache": "hooks/install.js"
	},

	"scripts": {
		"test": "mocha --full-trace --ui tdd index.js tests/index.js",
		"preinstall": "echo 1"
	},

	"dependencies": {
		"git-info-sync": "^0.0.3",
		"debug": "^2.2.0",
		"fs-extra": "^1.0.0",
		"http-status": "^0.2.3",
		"request": "^2.76.0",
		"json-stable-stringify": "1.0.1",
		"minimist": "^1.2.0",
		"tar-fs": "^1.5.2",
		"url-join": "^1.1.0"
	},

	"devDependencies": {
		"mocha": "3.1.2"
	}
}
```

```
npm i
```

```
installing ...
echo 1
```

**Comment by STRML** [comment]
Hmm - so preinstall is now running before `node_modules` is created, but not before the initial http fetches happen. I'm not sure if this is intended or not, but it's arguably not that useful.

**Comment by monolithed** [comment]
> Hmm - so preinstall is now running before node_modules is created, but not before the initial http fetches happen. I'm not sure if this is intended or not, but it's arguably not that useful.

OMG. It's not expected for me. I'd like to call `process.exit()` before `node_modules` will be installed. It's really important for many custom npm-cache servers.

**Comment by jishi** [comment]
Just tested 3.10.8, this still leaves an empty node_modules folder if you run `npm install`

```
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "preinstall": "rm -rf node_modules/lodash"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "lodash": "^4.17.2"
  }
}
```

**Comment by palmerj3** [comment]
Yes if you look at the actual [PR](https://github.com/npm/npm/pull/13259) it's pretty clear it doesn't handle those cases. And also IMO it shouldn't. But if NPM feels differently then they'll eventually fix.

**Comment by monolithed** [comment]
> Yes if you look at the actual PR it's pretty clear it doesn't handle those cases. 

Are you kidding? `prepublish` [is not](https://github.com/npm/npm/issues/3059) prepublsh, `preinstall` is not `preinstall`, `--prefix` [is not](https://github.com/npm/npm/issues/14661) `--prefix`, `bundledDependencies` [is  not](https://github.com/npm/npm/issues/14641) `bundledDependencies ` what else? 
`preinstall` should install dependencies before, not after.

**Comment by palmerj3** [comment]
What I mean when I say to read the PR is that preinstall does not currently allow you to manipulate the tree before install like it did in NPM 2.x. It still executes before any modules are moved to node_modules. And it's my personal opinion that that is how it should be and, given that NPMs documentation says preinstall should only be used for compilation, I think they tend to agree as well. No disrespect - I understand you have different use cases.

**Comment by legodude17** [comment]
@monolithed, it is a little misleading that you are referencing

1. A 3 year old issue that was resolved.
2. An issue that was resolved, and shown how it was correct
3. An issue you opened 3 days ago that you haven't responded on

**Comment by peter-mouland** [comment]
@monolithed My use case was to log into a private repo, which _must_ happen before the tree is even analysed, but as mentioned in previous comments, this can be achieved more appropriately with other methods (i.e. `.npmrc`).

Perhaps your use case is like this, where another solution is better, are you able to provide move details of your frustration?

**Comment by monolithed** [comment]
> Perhaps your use case is like this, where another solution is better, are you able to provide move details of your frustration?

@peter-mouland, @legodude17, @palmerj3

Well, I'll try to explain my workaround:

**prerequisite**

```
npm install @qa/npm-cache --global
```

**.npmrc**

```
registry = http://private.registry
```

**package.json**

```json
{
   "scripts": {
      "preinstall": "npm-cache"
   }
}
```

**usage**

```
npm install
```

**scheme**

![map](https://cloud.githubusercontent.com/assets/803674/20463001/05783de0-af3b-11e6-9431-9ab432f9b6f3.png)

**Actual usage**

```
npm run npm-cache -- --type=production
```

**Expected usage**

```
npm install --type=production
```

So, the current behavior is not expected for me. I'd like to call `process.exit()` before `node_modules` will be installed. It's needed to download the remote cache and prevent the current local installation.

**Comment by palmerj3** [comment]
@monolithed this is very helpful thank you! I would definitely recommend opening a PR and trying to fix this yourself. If I get some time I'll take another look. At the time I submitted the original PR it was not trivial to do the preinstall actions before the tree was analyzed.

**Comment by hendrul** [comment]
NPM v3 has been a horrible shit since it came out, I mean why the fuck this change in preinstall, is nonsense, retrograde, time waster!.

**Comment by mmc41** [comment]
I can confirm that pre-install is still not a pre-install as of npm v4.0.5 where it runs AFTER install. Very surprising to me + curious why an old bug like this still exist. Never wanted to consider moving to Yarn before I found this key yet unresolved bug. Does anyone know if Yarn actually works as documented unlike npm in this regard ?

**Comment by noherczeg** [comment]
@mmc41 preinstall worked for us with yarn.

**Comment by palmerj3** [comment]
As you can see here https://github.com/npm/npm/blob/latest/test/tap/lifecycle-order.js#L18

If preinstall was executed AFTER install then that test would be failing for every single PR and that's not happening..

We need to make a very clear distinction between if preinstall is called AFTER install or if it's called after you'd like it to be called.

There are definitely people on this list who want to be able to manipulate the dependency tree before NPM even begins to process how to proceed. This would be what NPM 2 did and that does seem like a very nice feature but it's not what is available in 3.x or 4.x at this point.

There are some people who think preinstall should be called before any packages are actually downloaded. That's a bit more understandable if you want to bail early. But yarn currently does not do that either with the top level package or transitive deps. They are downloaded first and then lifecycle scripts are run.

**Comment by mmc41** [comment]
@palmerj3 It is pretty simple. If the code below does not work, than preinstall does not work (i.e. called after install instead of before).

"scripts": {
    "preinstall": "rm -rf node_modules/myStuffThatIWantInstallToReinstall"
}

**Comment by noherczeg** [comment]
@mmc41 Yeah that's exactly what we wanted to achieve as well, and it worked with yarn.

**Comment by DenianArthurShades** [comment]
Exactly what @mmc41 said. It's a really simple use case: _I want to remove **everything** that was installed by a previous "npm install" **before** anything else is done._

I don't know if this is somehow hard to understand. It's a simple, logical usecase for which _some_ kind of logic should exist. I don't even really care whether it's called preinstall, totallyAwesomePreNpmInstallCleanupScript or even James, _as long as I can execute a script before anything else happens._ If there's any valid reason why this _shouldn't be done_, as opposed to excuses why it _doesn't currently work_, I have yet to hear them.

**Comment by palmerj3** [comment]
All of those examples you just provided are wanting to manipulate the tree before NPM calculates the tree. That is my point. Preinstall DOES happen before install it just does not happen before the tree is calculated.

**Comment by mmc41** [comment]
@palmerj3 Are we trying to fix problems here or pretend they don't exist? Playing with semantics of words does not address the issue - it only make people disappointed, angry and/or interested in leaving npm for competing projects where their concerns might be taken more serious.

**Comment by monolithed** [comment]
>Preinstall DOES happen before install it just does not happen before the tree is calculated.

So, how to calculate a hash sum of `node_modules` before? In my use case, it's needed to prevent installation.

**Comment by palmerj3** [comment]
@mmc41 I don't work for NPM I just contribute. If another technology does a better job for you then by all means leave. I think it's more important that we file a bug that is accurate. "Preinstall fires after install" is not accurate. "Preinstall fires after the tree is calculated" is accurate, however..

I took a lot of my personal time to "fix" the preinstall issue because I was frustrated by it too. So I understand your pain even though I don't share your exact use case. Preinstall now fires BEFORE install.

However I wasn't able to figure out how to make NPM fire preinstall before the tree is calculated. That is massively complex with NPM 3 and probably why the maintainers haven't done it yet themselves.

So perhaps instead of complaining on an old issue thread, open a new one that more accurately describes your bug, or... try contributing a fix for it yourselves.

**Comment by mekwall** [comment]
This issue exists in latest npm v4.1.2. Please update the title to reflect it.

**Comment by csvan** [comment]
If this is not going to be fixed, the docs should probably be updated to make it clear that "preinstall" does not at all mean what it intuitively seems to mean - especially if you are coming from npm2.

Also, why not introduce an additional hook that do exactly what users expect preinstall to do? Perhaps `prerun`?

**Comment by hendrul** [comment]
some suggestions precheck, postcheck, postdependencycheck

**Comment by kcauchy** [comment]
One year later, still not fixed...

**Comment by csvan** [comment]
@kcauchy I don't think it will be "fixed" since, technically, it is not an error. This is simply how the NPM install flow works, and "preinstall" is where it's supposed to be in an NPM context. 

It's of course completely counter-intuitive to almost anybody who has used almost any other package manager (including me), so it would be nice if extra hooks were added without modifying this one.

**Comment by palmerj3** [comment]
I have a PR (referenced above) which is a work in progress but appears, from my testing, to handle the use cases in this thread. I don't have a huge amount of test cases to run this against so if you could help test it out and/or provide me with some github projects I could try it out on that would be excellent. ping @csvan @kcauchy @monolithed @mmc41

**Comment by palmerj3** [comment]
One additional ping to @csvan @kcauchy @monolithed @mmc41 - I believe my PR does fix this issue completely and I would love some additional feedback and testing. I wrote a test in the NPM suite which should verify the behavior but your feedback is crucial in order to close this ticket once it's merged. https://github.com/npm/npm/pull/16013

**Comment by csvan** [comment]
@palmerj3 thank you for your work on this, but I doubt I can be useful here since I have moved all my personal and most of our companys' projects to Yarn.

**Comment by mmc41** [comment]
@palmerj3 Unfortunately, I do not have public code that you can test at this time. But your solution satisfies my use case if it always reinstall the module myStuffThatIWantInstallToReinstall when doing a "npm install" with the below script in package.json.

"scripts": {
"preinstall": "rm -rf node_modules/myStuffThatIWantInstallToReinstall"
}

**Comment by palmerj3** [comment]
@mmc41 yes it does

**Comment by monolithed** [comment]
@palmerj3, thanks for your PR!

**Comment by bobrosoft** [comment]
OMFG, just faced that issue as well ... I know we live in not ideal world but issue like that looks very essential and should be one of the high priority. Sad :(

**Comment by zkat** [comment]
Fixed in `npm@5.0.0`.

**Comment by csvan** [comment]
@zkat can you briefly elaborate on how npm5 solves this? Is for example `postinstall` now run after the files have actually been written to `node_modules`?

**Comment by victorb** [comment]
@csvan seems like `postinstall` is finally after the install step. I have this small package.json to reproduce the issue. npm < 5.0.3 are not working correctly while at least npm 5.0.3 is doing stuff all right here.

```
{
  "name": "npm-order-bug",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "preinstall": "ls node_modules || true",
    "postinstall": "ls node_modules || true"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "lodash": "^4.17.4"
  }
}
```

Output:

```
➜  npm-order-bug npm install       

> npm-order-bug@1.0.0 preinstall /data/projects/victorbjelkholm/npm-order-bug
> ls node_modules || true

ls: cannot access 'node_modules': No such file or directory

> npm-order-bug@1.0.0 postinstall /data/projects/victorbjelkholm/npm-order-bug
> ls node_modules || true

lodash
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN npm-order-bug@1.0.0 No description
npm WARN npm-order-bug@1.0.0 No repository field.

added 1 package in 1.509s
```

Versions before 5.0.3 would show this:

```
➜  npm-order-bug npm install      

> npm-order-bug@1.0.0 preinstall /data/projects/victorbjelkholm/npm-order-bug
> ls node_modules || true


> npm-order-bug@1.0.0 postinstall /data/projects/victorbjelkholm/npm-order-bug
> ls node_modules || true

npm WARN npm-order-bug@1.0.0 No description
npm WARN npm-order-bug@1.0.0 No repository field.
```

Many thanks for fixing this long-standing bug npm team! 👍

**Comment by csvan** [comment]
Sweet!
