### ISSUE TITLE
EISGIT refusing to remove, when there's no need to remove

### ISSUE THREAD

**Issue by haggholm** [npm/npm#10372]
My root package has a direct dependency which is linked from another repository (actually a Docker volume). When running `npm install gulp`, it refuses to run, on the basis that it refuses to delete the Git repository. However, there’s no need to delete it, and in fact it seems to appear in the same place in the current and ideal dep trees! I appreciate that it won’t delete Git checkouts, but the error only ought to occur when a deletion or move is planned.

Relevant snippets:

```
1532 silly idealTree:prePrune @client/root@1.0.5
1532 silly idealTree:prePrune +-- @client/base-component@1.0.10
1532 silly idealTree:prePrune +-- @client/base@1.0.46
...
1534 silly currentTree @client/root@1.0.5
1534 silly currentTree +-- @client/base-component@1.0.10
1534 silly currentTree +-- @client/base@1.0.46
...
1535 silly idealTree @client/root@1.0.5
1535 silly idealTree +-- @client/base-component@1.0.10
1535 silly idealTree +-- @client/base@1.0.46
...
1536 silly generateActionsToTake Starting
1537 silly install generateActionsToTake
1538 silly install printInstalled
1539 verbose stack Error: Appears to be a git repo or submodule.
1539 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/npm-install-checks/index.js:138:15
1539 verbose stack     at FSReqWrap.oncomplete (fs.js:82:15)
1540 verbose cwd /opt/client-root
1541 error Linux 3.13.0-37-generic
1542 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "--dry-run" "gulp"
1543 error node v4.2.2
1544 error npm  v3.4.0
1545 error path /opt/client-root/node_modules/@client/base
1546 error code EISGIT
1547 error git Appears to be a git repo or submodule.
1547 error git     /opt/client-root/node_modules/@client/base
1547 error git Refusing to remove it. Update manually,
1547 error git or move it out of the way first.
1548 verbose exit [ 1, true ]
```

Full [npm-debug.log](https://github.com/npm/npm/files/33522/npm-debug.log.txt)

**Comment by ericclemmons** [comment]
Just ran into the same thing after doing:

1. `npm link some-project-im-working-on`.
2. `npm install`.

````
npm ERR! git Appears to be a git repo or submodule.
npm ERR! git     /path/to/node_modules/some-project-im-working-on
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.
```

**Comment by geloescht** [comment]
+1

**Comment by dypsilon** [comment]
Isn't it a crucial blocker for any development workflow? Why is this issue still not fixed? Is there a workaround?

**Comment by redben** [comment]
This used to work in previous versions. A real blocker

**Comment by dypsilon** [comment]
I just stopped using npm for my unpublished packages because of this. Apparently node_modules is a directory which is reserved exclusively to npm now and you can't hold your own modules there, without managing them through npm.

Managing them through npm is a pain in the neck, so I just use npm to pull third party modules and don't touch node_modules dir ever since. A huge step back for the node community, if you ask me.

**Comment by whitecolor** [comment]
> This used to work in previous versions. A real blocker

in which version did it work?

**Comment by dypsilon** [comment]
@whitecolor it worked in npm2.

**Comment by whitecolor** [comment]
everything worked in v2)

**Comment by whitecolor** [comment]
docker did a great job with flexible mounting of volumes and npm f** up everything :skull:.

**Comment by redben** [comment]
@whitecolor 2.x I think (the version that goes with node 0.12)

**Comment by jcollum** [comment]
I installed a library and wanted to make some small changes to it (because it was doing dumb things with config files inside the library). I made some changes to it. Didn't want to lose them, so I made a git repo in that dir. Now I can't install _anything_. 

Seems like a warning would be more appropriate here...

**Comment by DVLP** [comment]
Same problem, I'm using a forked repo with changes as a dependency and it gets in way of installing anything...not even related to the package.

**Comment by osadan** [comment]
You have a .git directory inside the module . that is making trouble to npm . just remove the .git folder and ... should work

**Comment by DVLP** [comment]
@osadan that's what I noticed too. Renaming .git temporarily to _git, then doing all your npm installs/uninstalls and then renaming that _git back .git is a workaround I'm using now.

**Comment by legodude17** [comment]
Are you working inside of a `node_modules`?

**Comment by cangzhen** [comment]
I wonder why added this check to npm ,really inconvenient！

**Comment by DVLP** [comment]
@legodude17 Yes. I have a fork of a big library in node_modules which I keep modifying simultaneously with my main app. Once the results are satisfactory I commit both repos.

**Comment by legodude17** [comment]
I think that is the problem. `npm` is getting confused because you are developing inside of a `node_modules`, and that leads it to want to remove `.git`, for some reason... I would suggest using `npm link`.

**Comment by lucascaro** [comment]
https://docs.npmjs.com/cli/link

**Comment by storjarn** [comment]
If you use the documented dependency format of "packageName": "gitRepoUrl#branchName", this still happens.  Fail.

**Comment by legodude17** [comment]
@storjarn What do you mean by "`npm link` does not apply"? What is your use case?

**Comment by storjarn** [comment]
@legodude17 , as stated in my previous comment, using the documented dependency format of "packageName": "git+ssh://gitRepoUrl#branchName" in package.json will cause this error and fail an npm install/update.  So the only non-janky way to get around this is to rm -rf node_modules and then re-run npm install/update.

**Comment by storjarn** [comment]
Also, I can't remember where I saw it, but on possibly another npm issue thread about this same thing, it was recommended to put a `preinstall` npm script that was essentially `rm -rf node_modules`, which is a bad hack, and the problem there is when you do run `npm link` for the global reference (say, in /usr/lib or wherever), that preinstall kicks in and wipes out node_modules in that global reference, so another manual `npm install` is still required afterwards.

Symlinks are relative to the OS, and doing this inside a VM means `npm link` needs to be run inside that VM for the link to work.  I miss the simplicity of the git repo url in a package.json file, is my point.

**Comment by storjarn** [comment]
I just noticed something..... when it's a git+ssh package in dependencies, it doesn't create the .git folder.  If it's in devDependencies, it does, and that's where this check kicks in and fails.....

**Comment by legodude17** [comment]
@storjarn That is really strange.

**Comment by emreavsar** [comment]
i had the same issue while i was developing a npm module and i didn't want to publish it until it worked in my project using the node module, thanks to comment of @legodude17 here (https://github.com/npm/npm/issues/10372#issuecomment-259491931) I found out that the .git directory came from the copying around (since not published local changes) of the whole npm module i've been working on, including the .git directory.. 🥇

**Comment by lucaswxp** [comment]
Still getting this.

**Comment by strathausen** [comment]
For me, having `.git` in the `.npmignore` helped.
