### ISSUE TITLE
Request path contains unescaped characters

### ISSUE THREAD

**Issue by firebat** [npm/npm#10376]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   'url-loader',
1 verbose cli   '--save-dev' ]
2 info using npm@1.4.21
3 info using node@v4.2.2
4 verbose readDependencies using package.json deps
5 verbose cache add [ 'url-loader', null ]
6 verbose cache add name=undefined spec="url-loader" args=["url-loader",null]
7 verbose parsed url Url {
7 verbose parsed url   protocol: null,
7 verbose parsed url   slashes: null,
7 verbose parsed url   auth: null,
7 verbose parsed url   host: null,
7 verbose parsed url   port: null,
7 verbose parsed url   hostname: null,
7 verbose parsed url   hash: null,
7 verbose parsed url   search: null,
7 verbose parsed url   query: null,
7 verbose parsed url   pathname: 'url-loader',
7 verbose parsed url   path: 'url-loader',
7 verbose parsed url   href: 'url-loader' }
8 silly lockFile 814094bd-url-loader url-loader
9 verbose lock url-loader /home/tom/.npm/814094bd-url-loader.lock
10 silly lockFile 814094bd-url-loader url-loader
11 silly lockFile 814094bd-url-loader url-loader
12 verbose addNamed [ 'url-loader', '' ]
13 verbose addNamed [ null, '*' ]
14 silly lockFile 8d1ca3f7-url-loader url-loader@
15 verbose lock url-loader@ /home/tom/.npm/8d1ca3f7-url-loader.lock
16 silly addNameRange { name: 'url-loader', range: '*', hasData: false }
17 verbose request where is /url-loader
18 verbose request registry https://registry.npmjs.org/
19 verbose request id 76e02163a3e30aca
20 verbose url raw /url-loader
21 verbose url resolving [ 'https://registry.npmjs.org/', './url-loader' ]
22 verbose url resolved https://registry.npmjs.org/url-loader
23 verbose request where is https://registry.npmjs.org/url-loader
24 info trying registry request attempt 1 at 下午2:03:11
25 http GET https://registry.npmjs.org/url-loader
26 error TypeError: Request path contains unescaped characters.
26 error     at new ClientRequest (_http_client.js:51:11)
26 error     at TunnelingAgent.exports.request (http.js:31:10)
26 error     at TunnelingAgent.createSocket (/usr/lib/nodejs/tunnel-agent/index.js:117:25)
26 error     at TunnelingAgent.createSecureSocket [as createSocket] (/usr/lib/nodejs/tunnel-agent/index.js:184:41)
26 error     at TunnelingAgent.addRequest (/usr/lib/nodejs/tunnel-agent/index.js:80:8)
26 error     at new ClientRequest (_http_client.js:133:16)
26 error     at Object.exports.request (http.js:31:10)
26 error     at Object.exports.request (https.js:163:15)
26 error     at Request.start (/usr/lib/nodejs/request/index.js:607:30)
26 error     at Request.end (/usr/lib/nodejs/request/index.js:1235:28)
27 error If you need help, you may report this *entire* log,
27 error including the npm and node versions, at:
27 error     <http://github.com/npm/npm/issues>
28 error System Linux 4.2.0-1-amd64
29 error command "/usr/bin/nodejs" "/usr/bin/npm" "install" "url-loader" "--save-dev"
30 error cwd /home/tom/workspace/qae/console
31 error node -v v4.2.2
32 error npm -v 1.4.21
33 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@firebat Please let me know if [updating `npm`](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) doesn't solve this issue.

**Comment by KenanY** [comment]
@firebat It has been several months now with no response from you; are you still seeing this issue after updating to `npm@2` or `npm@3`?

**Comment by KenanY** [comment]
Closing as abandoned.
