### ISSUE TITLE
Refusing to install express as a dependency of itself

### ISSUE THREAD

**Issue by iCityWork** [npm/npm#10387]
Trying to install Express and I get this error, any help would be awesome.  Mac, running sudo npm install express

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'express',
1 verbose cli   '--save' ]
2 info using npm@3.3.6
3 info using node@v5.0.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData express
8 silly fetchNamedPackageData express
9 silly mapToRegistry name express
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/express
13 verbose request uri https://registry.npmjs.org/express
14 verbose request no auth needed
15 info attempt registry request try #1 at 3:35:38 PM
16 verbose request id 2d9d96082d94639a
17 verbose etag "9HUJ4LVN30GUC142OLH6FLDUB"
18 http request GET https://registry.npmjs.org/express
19 http 304 https://registry.npmjs.org/express
20 verbose headers { date: 'Fri, 13 Nov 2015 23:35:38 GMT',
20 verbose headers   via: '1.1 varnish',
20 verbose headers   'cache-control': 'max-age=60',
20 verbose headers   etag: '"9HUJ4LVN30GUC142OLH6FLDUB"',
20 verbose headers   age: '37',
20 verbose headers   connection: 'keep-alive',
20 verbose headers   'x-served-by': 'cache-lax1422-LAX',
20 verbose headers   'x-cache': 'HIT',
20 verbose headers   'x-cache-hits': '435',
20 verbose headers   'x-timer': 'S1447457738.978677,VS0,VE0',
20 verbose headers   vary: 'Accept' }
21 silly get cb [ 304,
21 silly get   { date: 'Fri, 13 Nov 2015 23:35:38 GMT',
21 silly get     via: '1.1 varnish',
21 silly get     'cache-control': 'max-age=60',
21 silly get     etag: '"9HUJ4LVN30GUC142OLH6FLDUB"',
21 silly get     age: '37',
21 silly get     connection: 'keep-alive',
21 silly get     'x-served-by': 'cache-lax1422-LAX',
21 silly get     'x-cache': 'HIT',
21 silly get     'x-cache-hits': '435',
21 silly get     'x-timer': 'S1447457738.978677,VS0,VE0',
21 silly get     vary: 'Accept' } ]
22 verbose etag https://registry.npmjs.org/express from cache
23 verbose get saving express to /Users/user/.npm/registry.npmjs.org/express/.cache.json
24 silly install normalizeTree
25 silly loadCurrentTree Finishing
26 silly loadIdealTree Starting
27 silly install loadIdealTree
28 silly cloneCurrentTree Starting
29 silly install cloneCurrentTreeToIdealTree
30 silly cloneCurrentTree Finishing
31 silly loadShrinkwrap Starting
32 silly install loadShrinkwrap
33 silly loadShrinkwrap Finishing
34 silly loadAllDepsIntoIdealTree Starting
35 silly install loadAllDepsIntoIdealTree
36 silly rollbackFailedOptional Starting
37 silly rollbackFailedOptional Finishing
38 silly runTopLevelLifecycles Starting
39 silly runTopLevelLifecycles Finishing
40 silly install printInstalled
41 verbose stack Error: Refusing to install express as a dependency of itself
41 verbose stack     at checkSelf (/usr/local/lib/node_modules/npm/lib/install/validate-args.js:40:14)
41 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
41 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
41 verbose stack     at chain (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
41 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/validate-args.js:15:5
41 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
41 verbose stack     at Array.forEach (native)
41 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
41 verbose stack     at Array.forEach (native)
41 verbose stack     at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
42 verbose cwd /Users/user/Development/NodeJS/express
43 error Darwin 15.0.0
44 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "express" "--save"
45 error node v5.0.0
46 error npm  v3.3.6
47 error code ENOSELF
48 error Refusing to install express as a dependency of itself
49 error If you need help, you may report this error at:
49 error     <https://github.com/npm/npm/issues>
50 verbose exit [ 1, true ]

**Comment by iCityWork** [comment]
Never mind, the directory was the same name so it wouldn't work. I renamed the directory and it was fine.
Sorry about that.  OK TO DELETE

**Comment by JohnnyFun** [comment]
No, keep this here, haha--did the same thing...

**Comment by samChannnnnn** [comment]
thx

**Comment by NotoriousWebmaster** [comment]
It's not the name of the directory, it's the name in the package.json which cannot be the same.

**Comment by clark-stevenson** [comment]
thanks @NotoriousWebmaster !

**Comment by aimenbatool** [comment]
Thanks @NotoriousWebmaster !!

**Comment by davidheis** [comment]
i made the same mistake

**Comment by EddieYT** [comment]
Did the same thing as well, thanks @NotoriousWebmaster

**Comment by ChrisCooney** [comment]
Joining the conga line of devs who have been bitten by this. Thanks for keeping this up!

**Comment by Hoseinkangavarnazari** [comment]
did the same thing :))) TNX

**Comment by asad-ullah-khan1** [comment]
Same issue , How stupid we are :)

**Comment by fadsel** [comment]
Its **2017** and I did the same thing :)

**Comment by Jagdeep-Sing** [comment]
thanks!! I did same thing in **2018** :-D

**Comment by jay51** [comment]
stupid mistake

**Comment by reigelgallarde** [comment]
it's ok to just change the name on your package.json... no need to rename the folder..
