### ISSUE TITLE
npm install misses lodash 0.9.2 if lodash is a devDependencies and grunt is a dependency

### ISSUE THREAD

**Issue by daddykotex** [npm/npm#10381]
I don't know if this is an issue with `npm` or `grunt` but I'm opening it here since `npm` is responsible for fetching dependencies!

With this simple `package.json`, you can replicate: 
```
{
  "name": "issue",
  "version": "0.0.1",
  "dependencies": {
    "grunt": "^0.4.5"
  },
  "devDependencies": {
    "lodash": "^3.10.0"
  },
  "engines": {
    "node": ">=5.0.0"
  },
  "private": true
}
```
Run `npm install` and then `npm list` and you should see an error for missing packages. 
```
npm ERR! missing: lodash@~0.9.2, required by grunt@0.4.5
npm ERR! missing: lodash@~0.9.2, required by grunt-legacy-util@0.2.0
```
Moving grunt into the `devDependencies` works. Eg, this works : 
```
{
  "name": "issue",
  "version": "0.0.1",
  "dependencies": {
  },
  "devDependencies": {
    "grunt": "^0.4.5",
    "lodash": "^3.10.0"
  },
  "engines": {
    "node": ">=5.0.0"
  },
  "private": true
}
```

I on Mac OSX with node `v5.0.0` and npm at `3.4.0`.

Thanks

**Comment by daddykotex** [comment]
Also, running `npm install` a second time will fetch the missing dependencies and solve the problem.

**Comment by lxe** [comment]
@daddykotex this is a dupe of https://github.com/npm/npm/issues/10119 I think

**Comment by lxe** [comment]
and https://github.com/npm/npm/issues/10277

**Comment by daddykotex** [comment]
I'll close this MR, fixes are already in the works and we have updated our `package.json` with a better understanding of the difference between `dependencies` and `devDependencies` and now, everything seems fine.
