### ISSUE TITLE
Semantic versions and GitHub URLs

### ISSUE THREAD

**Issue by paulyoung** [npm/npm#10386]
I'd like to be able to depend on a project with a GitHub URL while having the benefit of semantic versioning.

Something like:

```json
{
  "dependencies": {
    "user/repo": "^1.0.0"
  }
}
```

Or perhaps something like this:
```json
{
  "dependencies": {
    "name": "user/repo^1.0.0"
  }
}
```

I couldn't see anything in the documentation about how to do this already.

**Comment by KenanY** [comment]
This is on [the roadmap](https://github.com/npm/npm/wiki/Roadmap-area-of-focus:-git) and is a duplicate of several other tickets (which are linked in the roadmap).

**Comment by paulyoung** [comment]
Great! Thanks. Sorry for the dupe but I couldn't find anything when searching.

**Comment by KenanY** [comment]
Closing since this is on the roadmap.
