### ISSUE TITLE
Support wildcard at npm uninstall

### ISSUE THREAD

**Issue by watilde** [npm/npm#10385]
I think supporting wildcard at `npm uninstall` may be nicer when I'd like to do the following cases.

e.g.
Remove all plugins:

```
$ npm uninstall 'gulp-*'
```

Remove all packages:

```
$ npm uninstall '*'
```

**Comment by qw3rtman** [comment]
While I love this idea, `npm` allows published package names to contain the `*` character. Adding this could confuse someone trying to remove the package [`a*`](https://www.npmjs.com/package/a*) by also uninstalling [`angular`](https://www.npmjs.com/package/angular).
