### ISSUE TITLE
error while installing npm install arpjs

### ISSUE THREAD

**Issue by milangroshev** [npm/npm#10392]
i try to install arpjs wiht npm install arpjs and i get this error... please help

:~$ sudo npm install arpjs
npm http GET https://registry.npmjs.org/ip
npm http GET https://registry.npmjs.org/pcap
npm http GET https://registry.npmjs.org/getmac
npm http 304 https://registry.npmjs.org/getmac
npm http 304 https://registry.npmjs.org/ip
npm http 304 https://registry.npmjs.org/pcap
npm http GET https://registry.npmjs.org/extract-opts
npm http GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/extract-opts
npm http GET https://registry.npmjs.org/typechecker
npm http 304 https://registry.npmjs.org/typechecker

> typechecker@2.0.8 preinstall /home/groshev/node_modules/arpjs/node_modules/getmac/node_modules/extract-opts/node_modules/typechecker
> node ./cyclic.js

npm ERR! git clone git://github.com/zerouid/node-socketwatcher.git Cloning into bare repository '/home/groshev/.npm/_git-remotes/git-github-com-zerouid-node-socketwatcher-git-a1e57e3d'...
npm ERR! git clone git://github.com/zerouid/node-socketwatcher.git fatal: unable to connect to github.com:
npm ERR! git clone git://github.com/zerouid/node-socketwatcher.git github.com[0: 192.30.252.128]: errno=Connection timed out
npm ERR! Error: Command failed: Cloning into bare repository '/home/groshev/.npm/_git-remotes/git-github-com-zerouid-node-socketwatcher-git-a1e57e3d'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.128]: errno=Connection timed out
npm ERR! 
npm ERR! 
npm ERR!     at ChildProcess.exithandler (child_process.js:637:15)
npm ERR!     at ChildProcess.EventEmitter.emit (events.js:98:17)
npm ERR!     at maybeClose (child_process.js:743:16)
npm ERR!     at Process.ChildProcess._handle.onexit (child_process.js:810:5)
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Linux 3.16.0-52-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "arpjs"
npm ERR! cwd /home/groshev
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! code 128
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/groshev/npm-debug.log
npm ERR! not ok code 0

**Comment by KenanY** [comment]
@milangroshev Please try [updating `npm`](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) first.

**Comment by milangroshev** [comment]
i try that but i still get the same error just in a different way:

npm ERR! git clone --template=/home/groshev/.npm/_git-remotes/_templates --mirror git://github.com/zerouid/node-socketwatcher.git /home/groshev/.npm/_git-remotes/git-github-com-zerouid-node-socketwatcher-git-1a1c9a71a6b40910312ea5611316a228: Cloning into bare repository '/home/groshev/.npm/_git-remotes/git-github-com-zerouid-node-socketwatcher-git-1a1c9a71a6b40910312ea5611316a228'...
npm ERR! git clone --template=/home/groshev/.npm/_git-remotes/_templates --mirror git://github.com/zerouid/node-socketwatcher.git /home/groshev/.npm/_git-remotes/git-github-com-zerouid-node-socketwatcher-git-1a1c9a71a6b40910312ea5611316a228: fatal: unable to connect to github.com:
npm ERR! git clone --template=/home/groshev/.npm/_git-remotes/_templates --mirror git://github.com/zerouid/node-socketwatcher.git /home/groshev/.npm/_git-remotes/git-github-com-zerouid-node-socketwatcher-git-1a1c9a71a6b40910312ea5611316a228: github.com[0: 192.30.252.128]: errno=Connection timed out
npm WARN install Couldn't install optional dependency: Command failed: Cloning into bare repository '/home/groshev/.npm/_git-remotes/git-github-com-zerouid-node-socketwatcher-git-1a1c9a71a6b40910312ea5611316a228'...
npm WARN install fatal: unable to connect to github.com:
npm WARN install github.com[0: 192.30.252.128]: errno=Connection timed out
npm WARN install 
npm WARN install 
npm WARN ENOENT ENOENT, open '/home/package.json'
npm WARN EPACKAGEJSON home No description
npm WARN EPACKAGEJSON home No repository field.
npm WARN EPACKAGEJSON home No README data
npm WARN EPACKAGEJSON home No license field.

**Comment by KenanY** [comment]
@milangroshev 

```
npm WARN install github.com[0: 192.30.252.128]: errno=Connection timed out
```

Looks like an issue with your internet connection with regards to connecting to `github.com`. Are you behind a proxy or firewall by any chance?

**Comment by milangroshev** [comment]
@Kenan i solve that problem with this command:

git config --global url.https://github.com/.insteadOf git://github.com/

but now i have new error :+1: 

groshev@groshev:~$ sudo npm install arpjs

> socketwatcher@0.2.1 install /home/node_modules/socketwatcher
> node-gyp rebuild

Usage: gyp_main.py [options ...] [build_file ...]

gyp_main.py: error: no such option: --no-parallel
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.16.0-52-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/node_modules/socketwatcher
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN install:socketwatcher@0.2.1 socketwatcher@0.2.1 install: `node-gyp rebuild`
npm WARN install:socketwatcher@0.2.1 Exit status 1
npm WARN ENOENT ENOENT: no such file or directory, open '/home/package.json'
npm WARN EPACKAGEJSON home No description
npm WARN EPACKAGEJSON home No repository field.
npm WARN EPACKAGEJSON home No README data
npm WARN EPACKAGEJSON home No license field.

please help :D

**Comment by milangroshev** [comment]
@KenanY  i even went a step forward ... i solve this porblem now i get this ....

groshev@groshev:/usr/local/lib$ sudo npm -g install arpjs
[sudo] password for groshev: 
npm WARN lifecycle typechecker@2.0.8~preinstall: cannot run in wd %s %s (wd=%s) typechecker@2.0.8 node ./cyclic.js /usr/lib/node_modules/.staging/typechecker-8e5299d6dc600530516e3f6be254ad7d

> socketwatcher@0.2.1 install /usr/lib/node_modules/arpjs/node_modules/socketwatcher
> node-gyp rebuild

make: Entering directory `/usr/lib/node_modules/arpjs/node_modules/socketwatcher/build'
  CXX(target) Release/obj.target/socketwatcher/socket_watcher.o
In file included from ../node_modules/nan/nan_new.h:190:0,
                 from ../node_modules/nan/nan.h:80,
                 from ../socket_watcher.hpp:8,
                 from ../socket_watcher.cpp:5:
../node_modules/nan/nan_implementation_12_inl.h: In static member function ‘static NanIntern::FactoryBase<v8::Signature>::return_t NanIntern::Factory<v8::Signature>::New(NanIntern::Factory<v8::Signature>::FTH, int, NanIntern::Factory<v8::Signature>::FTH*)’:
../node_modules/nan/nan_implementation_12_inl.h:181:76: error: no matching function for call to ‘v8::Signature::New(v8::Isolate*, NanIntern::Factory<v8::Signature>::FTH&, int&, NanIntern::Factory<v8::Signature>::FTH*&)’
   return v8::Signature::New(v8::Isolate::GetCurrent(), receiver, argc, argv);
                                                                            ^
../node_modules/nan/nan_implementation_12_inl.h:181:76: note: candidate is:
In file included from /home/groshev/.node-gyp/5.0.0/include/node/node.h:42:0,
                 from ../node_modules/nan/nan.h:24,
                 from ../socket_watcher.hpp:8,
                 from ../socket_watcher.cpp:5:
/home/groshev/.node-gyp/5.0.0/include/node/v8.h:4674:27: note: static v8::Local<v8::Signature> v8::Signature::New(v8::Isolate*, v8::Local<v8::FunctionTemplate>)
   static Local<Signature> New(
                           ^
/home/groshev/.node-gyp/5.0.0/include/node/v8.h:4674:27: note:   candidate expects 2 arguments, 4 provided
In file included from ../socket_watcher.hpp:8:0,
                 from ../socket_watcher.cpp:5:
../node_modules/nan/nan.h: At global scope:
../node_modules/nan/nan.h:171:25: error: redefinition of ‘template<class T> v8::Local<T> _NanEnsureLocal(v8::Local<T>)’
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                         ^
../node_modules/nan/nan.h:166:25: error: ‘template<class T> v8::Local<T> _NanEnsureLocal(v8::Handle<T>)’ previously declared here
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                         ^
../node_modules/nan/nan.h:564:13: error: ‘node::smalloc’ has not been declared
     , node::smalloc::FreeCallback callback
             ^
../node_modules/nan/nan.h:564:35: error: expected ‘,’ or ‘...’ before ‘callback’
     , node::smalloc::FreeCallback callback
                                   ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)’:
../node_modules/nan/nan.h:568:50: error: ‘callback’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                  ^
../node_modules/nan/nan.h:568:60: error: ‘hint’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                            ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)’:
../node_modules/nan/nan.h:575:67: error: call of overloaded ‘New(v8::Isolate*, const char*&, uint32_t&)’ is ambiguous
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
../node_modules/nan/nan.h:575:67: note: candidates are:
In file included from ../node_modules/nan/nan.h:25:0,
                 from ../socket_watcher.hpp:8,
                 from ../socket_watcher.cpp:5:
/home/groshev/.node-gyp/5.0.0/include/node/node_buffer.h:31:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/groshev/.node-gyp/5.0.0/include/node/node_buffer.h:31:40: note:   no known conversion for argument 3 from ‘uint32_t {aka unsigned int}’ to ‘node::encoding’
/home/groshev/.node-gyp/5.0.0/include/node/node_buffer.h:43:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/groshev/.node-gyp/5.0.0/include/node/node_buffer.h:43:40: note:   no known conversion for argument 2 from ‘const char*’ to ‘char*’
In file included from ../socket_watcher.hpp:8:0,
                 from ../socket_watcher.cpp:5:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(uint32_t)’:
../node_modules/nan/nan.h:579:61: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent(), size)’ from ‘v8::MaybeLocal<v8::Object>’ to ‘v8::Local<v8::Object>’
     return node::Buffer::New(v8::Isolate::GetCurrent(), size);
                                                             ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uint32_t)’:
../node_modules/nan/nan.h:586:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^
make: *** [Release/obj.target/socketwatcher/socket_watcher.o] Error 1
make: Leaving directory `/usr/lib/node_modules/arpjs/node_modules/socketwatcher/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.16.0-52-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/arpjs/node_modules/socketwatcher
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN install:socketwatcher@0.2.1 socketwatcher@0.2.1 install: `node-gyp rebuild`
npm WARN install:socketwatcher@0.2.1 Exit status 1
/usr/lib
└── (empty)

npm ERR! code 1


please help
