### ISSUE TITLE
Custom Dependency Lists and Directories

### ISSUE THREAD

**Issue by pitaj** [npm/npm#10395]
Currently, the `package.json` only allows for certain pre-defined dep lists (`dependencies`, `devDependencies`). I propose enabling users to separate their dependencies by allowing them to create custom lists, and even have those lists install dependencies in those lists to separate directories, like `vendor` for front-end packages.

A major reason that many developers are not switching over from bower is because they see no separation between their front-end packages and back-end packages; everything is installed into `node_modules` and defined in `package.json` in the same field.

**How it could be done**

1. Add new `package.json` top-level hash field `dependencyLists` 
  Keys are the list name, values are the list install directory (`""` for `node_modules` ?)
  Names can not be any reserved field of `package.json` with the exception of overwriting the output directories of built in dependency lists, nor can they start with an underscore

2. Dependency lists defined in that field are then looked up in the top level of the `package.json` by their defined name, they are defined like the other dependency lists

3. These custom lists can be installed exclusively via `npm install --target`, where `target` is the dependency list name
  `npm install` installs all lists
  `npm install --production` installs all lists except `devDependencies, `
  There can be multiple lists listed like `npm install --frontend --css`

Example:

    {
      ...
      "dependencyLists": {
        "frontEndDependencies": "public/src/vendor"
      },
      "frontEndDependencies": {
        "jquery": "^2.3.0"
      }
      ...
    }

    npm install --frontEndDependencies

I think this proposal can make dealing with packages over contexts much easier, although it might allow for more duplication. 

EDIT: Added ability to `npm install --target`; Added ability to overwrite built in dep lists

**Comment by Martinspire** [comment]
Seems like a great idea to me. +1
Like you said, it doesn't have the separation from Bower. I could opy over what files i need for my front-end but that would still require me to write grunt/gulp commands. Would be easier to automate it via package.json indeed.

**Comment by replete** [comment]
i++;

**Comment by snlacks** [comment]
I like this idea as well: alternative syntax suggestion for consistency: 
`npm install package-name --save-frontend`

Defaults to `/public/node_modules/`

**Comment by donaldpipowitch** [comment]
> A major reason that many developers are not switching over from bower is because they see no separation between their front-end packages and back-end packages; 

This is indeed a concern for us. For example we have a generic Karma configuration file which automatically loads all _frontend_ dependencies _and_ dev dependencies with wiredep, because they are nicely separated from any Node modules. Without `bower.json` Karma would load itself as a dev dependency, because my modules needed for frontend testing (like angular-mocks) are in the same `devDependencies` array as my Node modules like Karma.

**Comment by ljharb** [comment]
You can define whatever keys you want in `package.json` - couldn't you make your own custom lists, and have your own tooling read them, without any involvement from `npm`?

**Comment by TCMiranda** [comment]
+1 
Also, I don't know if it would make sense without npm, @ljharb 
Wouldn't it be odd to use some other tool for custom dependencies when npm already controls them?

**Comment by ljharb** [comment]
I think it's odd to put files anywhere but in `node_modules` when you want npm to control them :-)

**Comment by TCMiranda** [comment]
Thanks @ljharb 
Thats is definitely a point, but the custom target directory is not the only point proposed, for example, custom dependencies could be installed exclusively, and as snlacks said, default would be /node_modules.

**Comment by othiym23** [comment]
This looks like a variant of the proposal in #9354. As @zkat says there, this is something that the CLI team does care about getting right. This proposal is in the same lines, but it’s significantly more complex than what we have in mind, and also the team isn’t yet in a position to work on this, so I’m going to close this feature request.

We intend to land support for static assets and add more tooling to make the lives of front-end developers simpler. We're very interested in providing solutions that make it easy and familiar for users of tools like Bower to move their work to npm, but this is something that requires a certain amount of care and up-front specification. There are many edge cases and lots of opportunities to create incidental complexity that will end up making things more complicated for developers.

Stay tuned to what the team is doing! This is [on the CLI team’s road map](https://github.com/npm/npm/labels/front-end). Sometime soon I’ll post a more detailed proposal of how we're going to address this set of use cases. Thanks for the discussion!

**Comment by whitecolor** [comment]
yarn has a like proposaal https://github.com/yarnpkg/rfcs/issues/13

**Comment by oprogramador** [comment]
I also need such a feature. IMO all libraries should be in node_modules but I need a separation of dependencies into more than two groups.

```json
{
  "dependencies": [
    "moment": "*"
  ],
  "buildDependencies": [
    "babel-cli": "*",
    "babel-core": "*",
    "webpack": "*"
  ],
  "devDependencies": [
    "mocha": "*",
    "chai": "*"
  ]
}
```

**Comment by Mouvedia** [comment]
@whitecolor yarnpkg/yarn#2782?
