### ISSUE TITLE
window.requestFileSystem Support  for 	WIndows 10 

### ISSUE THREAD

**Issue by shoibmohamad** [npm/npm#10390]
Hi ,
I have been using requestFileSystem  and filetransfer in our hybrid html app and it supports both widows 8.1 and ios but I also need it to work in Windows 10 store app. It seems like it cannot download file in windows 10 please suggest some alternative plugin to download files from server or if we got this work in windows 10 

sample code below

window.requestFileSystem(
    LocalFileSystem.PERSISTENT, 0,
    function onFileSystemSuccess(fileSystem) {
        var fileTransfer = new FileTransfer();
        fileTransfer.onprogress = function(progressEvent) {
            try {
                fileTransfer.download(uri, fileName,
                    function(entry) {
                        console.log("file download success");
                    },
                    function(error) {
                        console.log("file download failure");
                    },
                    false, {
                        headers: {
                            "Authorization": auth,
                            "action": "getFiles"                         
                        }
                    });
                console.log("success");
            }
        }
    },
    function(error) {
        console.log("failure");
    });

**Comment by KenanY** [comment]
Hello @shoibmohamad! This does not look like an issue with `npm`, so I suggest to take this question to somewhere like StackOverflow.

**Comment by shoibmohamad** [comment]
Thanks for the response I will do that ...

On Sun, Nov 15, 2015 at 1:00 AM, Kenan Yildirim <notifications@github.com>
wrote:

> Hello @shoibmohamad <https://github.com/shoibmohamad>! This does not look
> like an issue with npm, so I suggest to take this question to somewhere
> like StackOverflow.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/npm/npm/issues/10390#issuecomment-156738623>.
>



-- 
Thanks,

Shoib

*Durlabh Computers Pvt. Ltd.*
*India*: +91-120-4167004 x 3 <%2B91-120-4167004%20x%20308>13
*US*:  +1-571-766-6072,
        +1-571-612-5506,
*Emergency*: +1-571-346-7306
*Ext*: 313
*http://www.durlabhcomputers.com <http://www.durlabhcomputers.com/>*

This message contains information that may be privileged or confidential
and is the property of the Durlabh Computers Pvt. Ltd. It is intended only
for the person to whom it is addressed. If you are not the intended
recipient, you are not authorized to read, print, retain copy, disseminate,
distribute, or use this message or any part thereof. If you receive this
message in error, please notify the sender immediately and delete all
copies of this message. Durlabh Computers Pvt. Ltd. does not accept any
liability for virus infected mails.

**Comment by snopeks** [comment]
Hello @shoibmohamad, since there are no npm-related issues here I am closing this. If you run into any npm issues later you can always email support@npmjs.com, we'll be happy to help!
