### ISSUE TITLE
feature request - install exact

### ISSUE THREAD

**Issue by sramam** [npm/npm#10396]
I'd like to freeze the versions of all dependencies and downstream dependencies in my package.json. 
The problem with `shrinkwrap` is that devDependencies are not frozen nor is the resulting package OS portable (What can I say? we have organizational OCD!).

Ideally, I'd like an option to force all versions to specified dependencies, with _no_ automatic approximations.

Looking at the options, it seemed that a npm cli option to `npm install-exact` (`npm install --exact`?) would be something that fits the bill. If I understand the code right, it'll conditionally force an exact match instead of the current approximation in `fetch-package-metadata`.

This would allow user control when installing without forcing package maintainers to do anything.
It'll also maintain current and future flexible versions when that is most appropriate.

Figured I am missing something that this does not already exist nor any github issue that proposes
such a solution. Anyone care to comment or educate me?

**Comment by ekristen** [comment]
+1
