### ISSUE TITLE
Error install npm

### ISSUE THREAD

**Issue by cr4m05** [npm/npm#10391]
12726 info installOne yargs@3.10.0
12727 error Error: ENOENT, lstat '/home/usuario/WebClient-master/node_modules/phantomjs/node_modules/request/node_modules/form-data/node_modules/combined-stream/Readme.md'
12728 error If you need help, you may report this log at:
12728 error     <http://github.com/isaacs/npm/issues>
12728 error or email it to:
12728 error     <npm-@googlegroups.com>
12729 error System Linux 3.13.0-37-generic
12730 error command "/usr/bin/nodejs" "/usr/bin/npm" "install"
12731 error cwd /home/cramos/WebClient-master
12732 error node -v v0.10.25
12733 error npm -v 1.3.10
12734 error path /home/usuario/WebClient-master/node_modules/phantomjs/node_modules/request/node_modules/form-data/node_modules/combined-stream/Readme.md
12735 error fstream_path /home/usuario/WebClient-master/node_modules/phantomjs/node_modules/request/node_modules/form-data/node_modules/combined-stream/Readme.md
12736 error fstream_type File
12737 error fstream_class FileWriter
12738 error code ENOENT
12739 error errno 34
12740 error fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
12740 error fstream_stack Object.oncomplete (fs.js:107:15)
12741 verbose exit [ 34, true ]

**Comment by KenanY** [comment]
@cr4m05 Please try [updating `npm`](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) first.

**Comment by KenanY** [comment]
@cr4m05 It has been several months now with no response from you... are you still experiencing this issue after updating to `npm@2` or `npm@3`?

**Comment by KenanY** [comment]
Closing as abandoned (just as `npm@1.3` is).
