### ISSUE TITLE
[feature request] Need to make 'npm install --ignore-scripts' reproducible

### ISSUE THREAD

**Issue by yurivict** [npm/npm#10403]
When I run this command again with the same source tree after a while, it downloads different versions of dependencies.

There should be the key (for example the date) that would make it always download the same snapshot of all dependencies.

This is very useful for packaging of NodeJS-based project on the systems that require source fingerprinting.

**Comment by othiym23** [comment]
See the documentation for [`npm shrinkwrap`](https://docs.npmjs.com/cli/shrinkwrap), which does exactly this.

**Comment by yurivict** [comment]
With shrinkwrap there are also the differences in package.json files in subsequent downloads:

```
diff -r distro1/etherpad-lite-1.5.7/node_modules/ep_etherpad-lite/node_modules/socket.io/node_modules/socket.io-adapter/node_modules/socket.io-parser/node_modules/benchmark/package.json distro2/etherpad-lite-1.5.7/node_modules/ep_etherpad-lite/node_modules/socket.io/node_modules/socket.io-adapter/node_modules/socket.io-parser/node_modules/benchmark/package.json
59c59,60
<   "_from": "https://registry.npmjs.org/benchmark/-/benchmark-1.0.0.tgz"
---
>   "_from": "https://registry.npmjs.org/benchmark/-/benchmark-1.0.0.tgz",
>   "scripts": {}
```
