### ISSUE TITLE
`npm i -D pkg1@latest pkg2@latest` produces a broken tree

### ISSUE THREAD

**Issue by othiym23** [npm/npm#10408]
1. `git clone https://github.com/othiym23/only-shallow.git`
2. `cd only-shallow && git checkout 11e73050a8ed8e28fd6d6616b9af590db506c83b`
3. `npm install && echo ok` _(woo 'ok')_
4. `npm ls && echo ok` _(woo 'ok')_
5. `npm test && echo ok` _(woo 'ok')_
6. `npm --save-dev install standard@latest tap@latest && echo ok` _(woo 'ok')_
7. `npm ls && echo ok` _(woo 'o—WHOOPS:)_
   
   ```
   npm ERR! missing: foreground-child@1.3.0, required by nyc@3.2.2
   npm ERR! missing: spawn-wrap@^1.0.1, required by nyc@3.2.2
   ```
8. `npm install && echo ok` _(better:)_
   
   ```
   only-shallow@1.2.0 /Users/ogd/Documents/projects/only-shallow
   └─┬ tap@2.2.1
     └─┬ nyc@3.2.2
       ├── foreground-child@1.3.0
       └── spawn-wrap@1.0.1
   
   ok
   ```

The fact that the install of the updates works and lists an apparently correct tree, but one that's in fact missing packages, concerns me.

**Comment by iarna** [comment]
This does not reproduce under 3.5.2 and I suspect was fixed by the 3.5.0 release.
