### ISSUE TITLE
change to `latest` behavior causes strangeness in npm's own repo:

### ISSUE THREAD

**Issue by othiym23** [npm/npm#10409]
`npm ls` in the npm repo yields

```
npm ERR! missing: npmlog@, required by npm-registry-client@7.0.7
```

at the end, because the `package.json` in `npm-registry-client` contains `"npmlog": ""` in its `dependencies`. Not sure why the tests still pass, probably because most of the time we're using the repo version of npm to run `npm install` before running the tests.

**Comment by othiym23** [comment]
Indeed, running `node bin/npm-cli.js install` fixes the tree.

**Comment by marcbachmann** [comment]
To be more specific, this is broken since v3.4.1.
v3.4.0 still works

**Comment by vieraleonel** [comment]
I've noticed the same. I'm sticking to previous version for now

**Comment by prolink007** [comment]
Having the same issue here. When doing `npm ls --depth=0 -g"

Seeing `npm ERR! missing: npmlog@, required by npm-registry-client@7.0.7` 3 times.

**Comment by salah-saleh** [comment]
I installed node 4.2.2 via nvm. I have the same problem.

**Comment by Gheoan** [comment]
npm 3.4.1
node v4.2.2

`npm -g ls --depth=0`
```
├── babel-eslint@4.1.5
├── bower@1.6.5
├── browser-sync@2.10.0
├── eslint@1.10.1
├── eslint-config-airbnb@1.0.0
├── generator-aurelia@0.6.3
├── generator-gulp-webapp@1.0.3
├── gulp@3.9.0
├── jspm@0.16.15
├── mocha@2.3.4
├── node-gyp@3.1.0
├── npm@3.4.1
└── yo@1.5.0

npm ERR! missing: npmlog@, required by npm-registry-client@7.0.7
```

**Comment by natorojr** [comment]
FWIW, upgrading to npm@3.5.0 fixed this issue for. I was seeing the same issue mentioned above w/ npm 3.4.1 and node v4.2.2.

**Comment by sanjaykarki** [comment]
I'm also getting the same error while using ` npm ls -g --depth=0 ` in  npm 3.4.1

**Comment by prolink007** [comment]
Node version 5.1.0 and npm version 3.5.0.

Still seeing the issue.

**Comment by SerbanC** [comment]
@prolink007 where did you get npm@3.5.0 from? I came here because of the `missing npmlog@` bug, saw you have a newer version, ran `npm i -g npm@latest` on my 3.4.1 and crashed it like says in #10394

**Comment by Gheoan** [comment]
@SerbanC 3.4.1 is `latest` if you want 3.5.0, `npm i -g npm@3.5.0` should do it

**Comment by SerbanC** [comment]
@Gheoan thanks, unfortunately not anymore. My NPM is broken as per #10394 so I can't use any npm commands anymore (FYI). I'll stop here, I don't want to go offtopic.

**Comment by prolink007** [comment]
@SerbanC I had the same issue when trying to upgrade. I had to completely uninstall node and npm and reinstall. I used the node installer to install.

You need to completely uninstall though. Follow these steps: http://stackoverflow.com/q/20711240/427763

**Comment by kagha** [comment]
I have the same issue. Please let me know if any debugging info is needed.

**Comment by etsuo** [comment]
For what it's worth, I have the same issue with 3.5.3:

```bash
[17:01:31][0] test/$ npm list -g --depth=0
/usr/local/lib
├── cordova@5.4.1
├── generator-generator@1.0.1
├── generator-hybrid@0.0.1
├── grunt-cli@0.1.13
├── gulp@3.9.0
├── ionic@1.7.12
├── ios-deploy@1.8.3
├── ios-sim@5.0.4
├── npm@3.5.3
└── yo@1.5.1

npm ERR! missing: npmlog@, required by npm-registry-client@7.0.8
npm ERR! missing: npmlog@, required by npm-registry-client@3.2.2
```
My npm was installed via homebrew's `node` formula, version 5.4.0.

**Comment by derwaldgeist** [comment]
Same problem with 3.8.5, installed by the Node.js installer on MacOS

**Comment by jeantsai** [comment]
I tried with following commands, succeed!
npm -g install npm-registry-client
npm -g update
npm -g uninstall npm-registry-client

**Comment by yannicklerestif** [comment]
@jeantsai that worked for me too ! Thanks

**Comment by VladimirAmiorkov** [comment]
@jeantsai Your approach could be a solution but what if you do not want to update all global npm packages. I hope there is another solution to this err without the need to call `npm -g update`.

**Comment by mbrookson** [comment]
On Windows using Node v4.6.1 and npm 3.10.8 this is still an issue today!

**Comment by oussaka** [comment]
@jeantsai that worked for me too ! Thanks

**Comment by J-tt** [comment]
@othiym23 

It looks like this issue has been resolved 🎉 

If it has, could you please close it 👍

**Comment by Carlosps** [comment]
@jeantsai 
Just one fix, please mention you should use 
npm -g update npm-registry-client
It will make sure people don't update everything :)
