### ISSUE TITLE
`install` silently prunes misnamed git dependencies

### ISSUE THREAD

**Issue by olizilla** [npm/npm#10401]
Adding a dependency on a git url fails silently if the name given doesn't match the name property of the remote package.json

This is an error on the users part, but the result is the remote dep is resolved correctly, but then pruned:

``` sh
npm sill install loadAllDepsIntoIdealTree
npm sill fetchOtherPackageData x@github:select2/select2#6be96cfaa175448ef70b978648de7d6cb5822

...

verb addRemoteGit data._resolved: git://github.com/select2/select2.git#6be96cfaa175448ef70b978648de7d6cb5822e89
npm sill cache afterAdd Select2@4.0.0
npm verb afterAdd /Users/oli/.npm/Select2/4.0.0/package/package.json not in flight; writing
npm verb afterAdd /Users/oli/.npm/Select2/4.0.0/package/package.json written
npm sill resolveWithNewModule Select2@4.0.0 checking installable status
npm sill loadAllDepsIntoIdealTree Finishing
npm sill idealTree:prePrune some-whizzy-app-built-with-npm3@1.0.0
npm sill idealTree:prePrune └── Select2@4.0.0
npm sill loadIdealTree Finishing
npm sill currentTree some-whizzy-app-built-with-npm3@1.0.0
npm sill idealTree some-whizzy-app-built-with-npm3@1.0.0

...

npm verb exit [ 0, true ]
npm info ok
```

**The user gets no warning of their mistake, and the dep is not installed.**

This is most noticeable when coupled with casing issues. Given a dependency declaration like:

``` json
"dependencies": {
  "select2": "select2/select2#6be96cf"
}
```

...where we've accidentally lowercased the dep name to `"select2"` (_in savant-like readiness for the new way_) but the remote is actually uppity cased as [`"Select2"`](https://github.com/select2/select2/blob/7e2ade09652f66f3a70787f6f0e2918d171a6dcb/package.json#L2);
in `npm@2` the dep is installed regardless. 

In `npm@3` the dep is silently pruned as if you never declared it, which is surprising when transitioning an old project.

Digging around, I can see that it's because the resolved dep name doesn't match any listed deps, and is correctly pruned, so I reckon this sort of error should be caught earlier, in a similar way to [how tarballs are verified](https://github.com/npm/npm/blob/65a64c9277184b1a0665d78fce0a9b00f930d9bc/lib/cache/add-local-tarball.js#L124)

**Comment by olizilla** [comment]
The problem is this sort of thing: https://github.com/olizilla/app-with-typod-github-dependency/blob/92a9dfdb311a6872c152308302515de979cfa1ee/package.json#L6

**Comment by olizilla** [comment]
Minimal fix here: https://github.com/npm/npm/pull/10410

**Comment by iarna** [comment]
See also: https://github.com/npm/npm/issues/8588
