### ISSUE TITLE
Large leftover directories in /tmp

### ISSUE THREAD

**Issue by yurivict** [npm/npm#10405]
After running npm many times, I have a lot of directories like this: /tmp/npm-68586-2fe7cca3

Many of them are as large as 85MB (!)
npm shoud not leave such garbage in /tmp because this increases the risk of running out of disk space there.

npm-2.14.7
FreeBSD-10.2

**Comment by KenanY** [comment]
@yurivict Duplicate of https://github.com/npm/npm/issues/6855? This is on [the roadmap](https://github.com/npm/npm/wiki/Roadmap-area-of-focus%3A-big-bugs).

**Comment by yurivict** [comment]
Yes, it looks like this.

**Comment by KenanY** [comment]
@yurivict Could you close this issue in favor of https://github.com/npm/npm/issues/6855? Helps keep the issue tracker a little leaner.

**Comment by yurivict** [comment]
Ok
