### ISSUE TITLE
"npm install -g phonegap" not working

### ISSUE THREAD

**Issue by araujohs** [npm/npm#10412]
Please, help, what should I do to solve this problem:
# 

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\
node_modules\npm\bin\npm-cli.js" "install" "-g" "phonegap"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code Z_DATA_ERROR
npm ERR! errno -3

npm ERR! incorrect data check
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues
npm ERR! error rolling back Error: EPERM: operation not permitted, unlink 'D:\US
ERS\haraujo\AppData\Roaming\npm\node_modules\phonegap\node_modules\prompt\node_m
odules\winston\node_modules\async\lib\async.js'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  { [Error: EPERM: operation not permitted, unlink 'D
:\USERS\haraujo\AppData\Roaming\npm\node_modules\phonegap\node_modules\prompt\no
de_modules\winston\node_modules\async\lib\async.js']
npm ERR! error rolling back   errno: -4048,
npm ERR! error rolling back   code: 'EPERM',
npm ERR! error rolling back   syscall: 'unlink',
npm ERR! error rolling back   path: 'D:\USERS\haraujo\AppData\Roaming\npm\
node_modules\phonegap\node_modules\prompt\node_modules\winston\node_module
# s\async\lib\async.js' }

**Comment by OmgImAlexis** [comment]
Please wrap your log output like [this](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks).
