### ISSUE TITLE
Windows: npm install doesn't work

### ISSUE THREAD

**Issue by coldauthor** [npm/npm#10411]
Hello there,

on various projects "npm install" doesn't work. It breaks with errors. For example :

```
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\Marcus\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.0.0
npm ERR! npm  v2.7.5
npm ERR! path q:\kd\projekte\xxxxx.de\themes\xxxxx.de\src\components\owl-carousel2\node_modules\grunt-sass\node_modules\node-sass\node_modules\node-gyp\node_modules\glob\node_modules\once\node_modules\wrappy\package.json
npm ERR! code EBUSY
npm ERR! errno -4082
npm ERR! syscall open

npm ERR! EBUSY: resource busy or locked, open 'q:\kd\projekte\xxxxx.de\themes\xxxxx.de\src\components\owl-carousel2\node_modules\grunt-sass\node_modules\node-sass\node_modules\node-gyp\node_modules\glob\node_modules\once\node_modules\wrappy\package.json'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\Marcus\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.0.0
npm ERR! npm  v2.7.5

npm ERR! Cannot read property 'del' of undefined
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     q:\kd\projekte\xxxxx.de\themes\xxxxx.de\src\components\owl-carousel2\npm-debug.log
```

This issues are coming up installing the following packages:

```
"dependencies": {
    "jquery": ">=1.8.3"
  },
  "devDependencies": {
    "assemble": "~0.4.37",
    "blanket": "^1.1.7",
    "foundation-sites": "~5.5.2",
    "grunt": "^0.4.5",
    "grunt-autoprefixer": "^3.0.3",
    "grunt-banner": "^0.4.0",
    "grunt-blanket-qunit": "^0.2.0",
    "grunt-contrib-clean": "~0.6.0",
    "grunt-contrib-compress": "~0.13.0",
    "grunt-contrib-concat": "~0.5.1",
    "grunt-contrib-connect": "~0.10.1",
    "grunt-contrib-copy": "~0.8.0",
    "grunt-contrib-cssmin": "^0.12.3",
    "grunt-contrib-jshint": "^0.11.2",
    "grunt-contrib-qunit": ">=0.2.1",
    "grunt-contrib-uglify": "^0.9.1",
    "grunt-contrib-watch": "^0.6.1",
    "grunt-gh-pages": "^0.10.0",
    "grunt-jscs": "~1.8.0",
    "grunt-sass": "^1.0.0",
    "load-grunt-tasks": "^3.2.0",
    "pretty": "^1.0.0",
    "qunitjs": "^1.18.0"
  },
```

Installing those package one after another works like a charm!

Is this a known bug with npm on windows?

Regards,
M.

**Comment by zhaowenjian** [comment]
E:\ipTrafficMonitoring>npm install raw-socket
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "raw-socket"
me too !! what is the matter ?

npm ERR! node v4.2.2
npm ERR! npm  v2.14.7

npm ERR! Invalid name: "ip traffic monitoring"
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     E:\ipTrafficMonitoring\npm-debug.log

**Comment by smartmouse** [comment]
@coldauthor , are you using npm v2.14.7 with node 5.0.0? I thought that npm 3.x.x comes with node 5.0.0.

**Comment by coldauthor** [comment]
@smartmouse, fascinating, you're absolutely right. Haven't noticed this yet. 

Trying updating npm (using various for windows recommended workflows) I end up with the same error (short: ERR! Cannot read property 'del' of undefined):

```
Error:
Error:  ERR!
Error:   Windows_NT 10.0.10240

Error:  npm
Error:   ERR! argv
Error:   "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\Marcus\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "npm@3.4.1"

Error:  npm
Error:   ERR! node v5.0.0

Error:  npm
Error:  ERR! npm  v2.7.5

Error:

Error:  npm
Error:   ERR! Cannot read property 'del' of undefined

Error:  npm
Error:   ERR!

Error:  npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

Upgrading... \Error:

Error:  npm
Error:  ERR!
Error:   Please include the following file with any support request:

Error:  npm
Error:
Error:  ERR!
Error:       C:\Users\Marcus\AppData\Roaming\npm\npm-debug.log
```

Sadly I have to use Windows here at work. :(

Anyone any tips?

**Comment by KenanY** [comment]
@zhaowenjian Your issue does not look similar to that of @coldauthor. Please open a new issue next time. Note that package names may not contain spaces, hence why you are receiving an "invalid name" error. If you need any further help, let's take it to a new issue rather than adding more noise to this one.

**Comment by smartmouse** [comment]
@coldauthor , can you export %PATH%? windows is very different and always have different issues due to the config files settings. npm config get prefix, or npm config ls -l   does it work for you?
If not , most likely need to clean up manually and reinstall node with the default npm.

**Comment by coldauthor** [comment]
@smartmouse, here you are:

**echo %PATH%**
```
C:\Users\Marcus\Desktop\cmder\bin;C:\Program Files (x86)\Git\bin;C:\Program Files (x86)\Git\share\vim\vim74;C:\Users\Marcus\Desktop\cmder\vendor\conemu-maximus5;C:\Users\Marcus\Desktop\cmder\vendor\conemu-maximus5\ConEmu;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Calibre2\;C:\Program Files (x86)\Git\cmd;C:\Program Files\Microsoft Windows Performance Toolkit\;C:\Program Files (x86)\RadView\WebLOAD\bin;C:\Program Files (x86)\RadView\WebLOAD\bin\jre\bin;C:\Program Files (x86)\Skype\Phone\;C:\xampp\php;C:\ProgramData\ComposerSetup\bin;C:\Program Files (x86)\GNU\GnuPG\pub;C:\Program Files (x86)\nodejs\;C:\Ruby22-x64\bin;C:\Program Files (x86)\GnuWin32\bin;C:\Program Files\gs\gs9.15\bin;C:\Program Files\gs\gs9.15\lib;C:\Users\Marcus\AppData\Local\atom\bin;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\Marcus\AppData\Roaming\npm;C:\Users\Marcus\Desktop\cmder
```

**npm config get prefix**
```
C:\Program Files (x86)\nodejs
```

**npm config ls -l**
```
; cli configs
long = true
user-agent = "npm/2.7.5 node/v5.0.0 win32 x64"

; default values
access = null
always-auth = false
bin-links = true
browser = null
ca = null
cache = "C:\\Users\\Marcus\\AppData\\Roaming\\npm-cache"
cache-lock-retries = 10
cache-lock-stale = 60000
cache-lock-wait = 10000
cache-max = null
cache-min = 10
cafile = undefined
cert = null
color = true
depth = null
description = true
dev = false
editor = "notepad.exe"
engine-strict = false
fetch-retries = 2
fetch-retry-factor = 10
fetch-retry-maxtimeout = 60000
fetch-retry-mintimeout = 10000
force = false
git = "git"
git-tag-version = true
global = false
globalconfig = "C:\\Program Files (x86)\\nodejs\\etc\\npmrc"
globalignorefile = "C:\\Program Files (x86)\\nodejs\\etc\\npmignore"
group = 0
heading = "npm"
https-proxy = null
if-present = false
ignore-scripts = false
init-author-email = ""
init-author-name = ""
init-author-url = ""
init-license = "ISC"
init-module = "C:\\Users\\Marcus\\.npm-init.js"
init-version = "1.0.0"
json = false
key = null
link = false
local-address = undefined
loglevel = "warn"
; long = false (overridden)
message = "%s"
node-version = "5.0.0"
npat = false
onload-script = null
optional = true
parseable = false
prefix = "C:\\Program Files (x86)\\nodejs"
production = false
proprietary-attribs = true
proxy = null
rebuild-bundle = true
registry = "https://registry.npmjs.org/"
rollback = true
save = false
save-bundle = false
save-dev = false
save-exact = false
save-optional = false
save-prefix = "^"
scope = ""
searchexclude = null
searchopts = ""
searchsort = "name"
shell = "C:\\WINDOWS\\system32\\cmd.exe"
shrinkwrap = true
sign-git-tag = false
spin = true
strict-ssl = true
tag = "latest"
tmp = "C:\\Users\\Marcus\\AppData\\Local\\Temp"
umask = 0
unicode = true
unsafe-perm = true
usage = false
user = 0
; user-agent = "npm/{npm-version} node/{node-version} {platform} {arch}" (overridden)
userconfig = "C:\\Users\\Marcus\\.npmrc"
version = false
versions = false
viewer = "browser"
```

Those are working... But I think I will reinstall node - that's possibly the fastest way... ;)

Thanks for your help!

**Comment by coldauthor** [comment]
I've purged nodejs completely and then reinstalled it new. Now everything works fine! It was the wrong npm version that caused the problems mentioned above.

Thank you all!

**Comment by krushnachandra** [comment]
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\                                                                                                                node_modules\\npm\\bin\\npm-cli.js" "install" "grunt"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package grunt@1.0.1 does not satisfy its siblings' peer                                                                                                                Dependencies requirements!
npm ERR! peerinvalid Peer jit-grunt@0.9.1 wants grunt@~0.4.0
npm ERR! peerinvalid Peer grunt-contrib-clean@0.6.0 wants grunt@~0.4.0
npm ERR! peerinvalid Peer grunt-ng-constant@2.0.1 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer grunt-contrib-concat@0.5.1 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer grunt-contrib-copy@0.7.0 wants grunt@~0.4.0
npm ERR! peerinvalid Peer grunt-filerev@2.3.1 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer grunt-ng-annotate@0.9.2 wants grunt@~0.4.1
npm ERR! peerinvalid Peer grunt-postcss@0.5.5 wants grunt@^0.4.5
npm ERR! peerinvalid Peer grunt-usemin@3.1.1 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer grunt-contrib-watch@0.6.1 wants grunt@~0.4.0
npm ERR! peerinvalid Peer grunt-contrib-connect@0.9.0 wants grunt@~0.4.0
npm ERR! peerinvalid Peer grunt-contrib-jshint@0.11.3 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer grunt-newer@1.2.0 wants grunt@>=0.4.1
npm ERR! peerinvalid Peer grunt-wiredep@2.0.0 wants grunt@~0.4.0
npm ERR! peerinvalid Peer grunt-jscs@1.8.0 wants grunt@~0.4.2
npm ERR! peerinvalid Peer grunt-contrib-htmlmin@0.4.0 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer grunt-contrib-cssmin@0.12.3 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer grunt-contrib-uglify@0.7.0 wants grunt@~0.4.0

npm ERR! Please include the following file with any support request:
npm ERR!     E:\Chat\client\npm-debug.log




What the fuck error its really a big issue npm team plz help
