### ISSUE TITLE
Issue when build 

### ISSUE THREAD

**Issue by sunnytham** [npm/npm#10415]
=> demo: [INFO] 
==> demo: [INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ lumify-web-war ---
==> demo: [INFO] Deleting /vagrant/web/war/target
==> demo: [INFO] 
==> demo: [INFO] --- buildnumber-maven-plugin:1.2:create (create-build-number) @ lumify-web-war ---
==> demo: [INFO] Checking for local modifications: skipped.
==> demo: [INFO] Updating project files from SCM: skipped.
==> demo: [INFO] Executing: /bin/sh -c cd /vagrant/web/war && git rev-parse --verify HEAD
==> demo: [INFO] Working directory: /vagrant/web/war
==> demo: [INFO] Storing buildNumber: 12342611cc9566e84fe4175bf8eadbd749ce885c at timestamp: 1445873956473
==> demo: [INFO] Executing: /bin/sh -c cd /vagrant/web/war && git rev-parse --verify HEAD
==> demo: [INFO] Working directory: /vagrant/web/war
==> demo: [INFO] Storing buildScmBranch: UNKNOWN
==> demo: [INFO] 
==> demo: [INFO] --- buildnumber-maven-plugin:1.2:create-timestamp (create-formatted-timestamp) @ lumify-web-war ---
==> demo: [INFO] 
==> demo: [INFO] --- maven-dependency-plugin:2.8:build-classpath (build-classpath) @ lumify-web-war ---
==> demo: [INFO] Wrote classpath file '/vagrant/web/war/target/.classpath.vagrant'.
==> demo: [INFO] 
==> demo: 
==> demo: [INFO] --- template-resgen-maven-plugin:0.11:generate-resource (gen-build-properties) @ lumify-web-war ---
==> demo: [INFO] 
==> demo: [INFO] --- exec-maven-plugin:1.2.1:exec (WebApp Dependencies and Minification) @ lumify-web-war ---
==> demo: npm WARN install Couldn't install optional dependency: Unsupported
==> demo: npm 
==> demo: WARN
==> demo:  EPEERINVALID mocha-as-promised@2.0.0 requires a peer of mocha@>= 1.8.0 <2 but none was installed.
==> demo: npm WARN EPACKAGEJSON
==> demo:  lumify@0.1.0 license should be a valid SPDX license expression
==> demo: [4mRunning "bower:install" (bower) task[24m
==> demo: [32m>> [39mInstalled bower packages
==> demo: 
==> demo: [4mRunning "bower:prune" (bower) task[24m
==> demo: [32m>> [39mInstalled bower packages
==> demo: 
==> demo: [4mRunning "exec:buildOpenlayers" (exec) task[24m
==> demo: 
==> demo: [4mRunning "exec:buildCytoscape" (exec) task[24m
==> demo: [31m>> [39mPicked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
==> demo: [31m>> [39mPicked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
==> demo: [31m>> [39mPicked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
==> demo: [31m>> [39mPicked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
==> demo: [31m>> [39mPicked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
==> demo: [31m>> [39mPicked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
==> demo: [31m>> [39mPicked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
==> demo: [31m>> [39mPicked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
==> demo: [31m>> [39mPicked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
==> demo: [31m>> [39mPicked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
==> demo: [31m>> [39mPicked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
==> demo: [31m>> [39mPicked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
==> demo: [31m>> [39mPicked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
==> demo: 
==> demo: [4mRunning "exec:buildPathFinding" (exec) task[24m
==> demo: [31m>> [39mnpm
==> demo: [31m>> [39mWARN engine mocha@1.0.3: wanted: {"node":">= 0.4.x < 0.8.0"} (current: {"node":"4.2.1","npm":"3.3.9"})
==> demo: [31m>> [39mnpm
==> demo: [31m>> [39mWARN deprecated buffer-browserify@0.1.0: Package not maintained. Recent browserify uses https://github.com/feross/buffer
==> demo: [31m>> [39mnpm
==> demo: [31m>> [39m
==> demo: [31m>> [39mWARN excluding symbolic link lib/index.js -> jade.js
==> demo: [31m>> [39mnpm
==> demo: [31m>> [39mWARN EPACKAGEJSON pathfinding@0.4.10 No license field.
==> demo: [31m>> [39mnpm
==> demo: [31m>> [39mERR! Linux 2.6.32-573.7.1.el6.x86_64[31m
==> demo: >> [39mnpm ERR! argv "/usr/local/bin/node" "/usr/bin/npm" "install" "-q"[31m
==> demo: >> [39mnpm ERR! node v4.2.1[31m
==> demo: >> [39mnpm ERR! npm
==> demo: [31m>> [39mv3.3.9[31m
==> demo: >> [39mnpm ERR! path ../esprima/bin/esparse.js[31m
==> demo: >> [39mnpm ERR! code EPROTO[31m
==> demo: >> [39mnpm ERR!
==> demo: [31m>> [39merrno -71[31m
==> demo: >> [39mnpm ERR! syscall symlink[31m
==> demo: >> [39m[31m
==> demo: >> [39mnpm ERR! EPROTO: protocol error, symlink '../esprima/bin/esparse.js' -> '/vagrant/web/war/src/main/webapp/libs/PathFinding.js/node_modules/.bin/esparse'
==> demo: [31m>> [39mnpm ERR!
==> demo: [31m>> [39mnpm ERR! If you need help, you may report this error at:[31m
==> demo: >> [39mnpm ERR!     <https://github.com/npm/npm/issues>
==> demo: [31m>> [39mnpm
==> demo: [31m>> [39mERR! Linux 2.6.32-573.7.1.el6.x86_64[31m
==> demo: >> [39mnpm ERR! argv "/usr/local/bin/node" "/usr/bin/npm" "install" "-q"[31m
==> demo: >> [39mnpm ERR! node v4.2.1[31m
==> demo: >> [39mnpm ERR! npm  v3.3.9[31m
==> demo: >> [39mnpm
==> demo: [31m>> [39mERR! path npm-debug.log.92cb5c502c5cc7dea5fd32a8eafd6a97[31m
==> demo: >> [39mnpm ERR! code ETXTBSY[31m
==> demo: >> [39mnpm ERR! errno -26[31m
==> demo: >> [39mnpm ERR! syscall
==> demo: [31m>> [39mrename
==> demo: [31m>> [39mnpm ERR! ETXTBSY: text file is busy, rename 'npm-debug.log.92cb5c502c5cc7dea5fd32a8eafd6a97' -> 'npm-debug.log'
==> demo: [31m>> [39mnpm
==> demo: [31m>> [39mERR! [31m
==> demo: >> [39mnpm
==> demo: [31m>> [39mERR! If you need help, you may report this error at:[31m
==> demo: >> [39mnpm ERR!     <https://github.com/npm/npm/issues>
==> demo: [31m>> [39mnpm
==> demo: [31m>> [39mERR! Please include the following file with any support request:[31m
==> demo: >> [39mnpm ERR!     /vagrant/web/war/src/main/webapp/libs/PathFinding.js/npm-debug.log
==> demo: [31m>> [39mExited with code: 185.
==> demo: [33mWarning: Task "exec:buildPathFinding" failed. Use --force to continue.[39m
==> demo: [31mAborted due to warnings.[39m
==> demo: [INFO] ------------------------------------------------------------------------
==> demo: [INFO] Reactor Summary:
==> demo: [INFO] 
==> demo: [INFO] Lumify: Web: War ................................... FAILURE [23:52 min]
==> demo: [INFO] Lumify: Web: Plugin: Social Authentication ......... SKIPPED
==> demo: [INFO] Lumify: Web: Plugin: Username/Password Authentication SKIPPED
==> demo: [INFO] Lumify: Web: Plugin: X509 Authentication ........... SKIPPED
==> demo: [INFO] Lumify: Web: Plugin: x509/LDAP Authentication ...... SKIPPED
==> demo: [INFO] Lumify: Web: Plugin: Geo-coder: Bing ............... SKIPPED
==> demo: [INFO] Lumify: Web: Plugin: Google Analytics .............. SKIPPED
==> demo: [INFO] Lumify: Web: Plugin: Change Password ............... SKIPPED
==> demo: [INFO] Lumify: Web: Client API: Code Generator ............ SKIPPED
==> demo: [INFO] Lumify: Dev ........................................ SKIPPED
==> demo: [INFO] Lumify: Dev: Jetty Server .......................... SKIPPED
==> demo: [INFO] Lumify: Dev: GraphPropertyWorker: Local ............ SKIPPED
==> demo: 
==> demo: [INFO] Lumify: Dev: Tomcat Server ......................... SKIPPED
==> demo: [INFO] Lumify: Dev: Import ................................ SKIPPED
==> demo: [INFO] Lumify: Integration Test ........................... SKIPPED
==> demo: [INFO] Lumify: Benchmarks ................................. SKIPPED
==> demo: [INFO] Lumify: Migrations ................................. SKIPPED
==> demo: [INFO] ------------------------------------------------------------------------
==> demo: [INFO] BUILD FAILURE
==> demo: [INFO] ------------------------------------------------------------------------
==> demo: [INFO] Total time: 24:24 min
==> demo: [INFO] Finished at: 2015-10-26T15:54:15+00:00
==> demo: [INFO] Final Memory: 55M/114M
==> demo: [INFO] ------------------------------------------------------------------------
==> demo: [ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (WebApp Dependencies and Minification) on project lumify-web-war: Command execution failed. Process exited with an error: 3 (Exit value: 3) -> [Help 1]
==> demo: [ERROR] 
==> demo: [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
==> demo: 
==> demo: [ERROR] Re-run Maven using the -X switch to enable full debug logging.
==> demo: [ERROR] 
==> demo: 
==> demo: [ERROR] For more information about the errors and possible solutions, please read the following articles:
==> demo: [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by KenanY** [comment]
@sunnytham So this log is pretty messy but I take it your system does not support symlinks? Have you tried using the [`--no-bin-links`](https://docs.npmjs.com/misc/config#bin-links) flag?

**Comment by sunnytham** [comment]
Sorry for this dummy question. How to do that?
This error happened in the mvn used in vagrant . The command to used in vagrant as followed. I have the full log file attached. Kindly help as i have been trying to make the program lumify work for weeks and finally reach this step.
[setup3.txt](https://github.com/npm/npm/files/35679/setup3.txt)

    config.vm.provision "shell", inline: "cd /vagrant && mvn -P \"grunt unix\",web-war,web-war-with-gpw,web-war-with-ui-plugins clean package -DskipTests -rf :lumify-web-war", privileged: false

**Comment by KenanY** [comment]
@sunnytham Sorry, I have never used mvn :/, but surely there must be somewhere to configure what flags mvn runs `npm install` with.

**Comment by sunnytham** [comment]
Thanks! Ends up I use the solution from the following link and it works!
http://blog.rudylee.com/2014/10/27/symbolic-links-with-vagrant-windows/

On Tue, Nov 17, 2015 at 12:07 AM, Kenan Yildirim <notifications@github.com>
wrote:

> @sunnytham <https://github.com/sunnytham> Sorry, I have never used mvn
> :/, but surely there must be somewhere to configure what flags mvn runs npm
> install with.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/npm/npm/issues/10415#issuecomment-157082361>.
>



-- 
Thanks and Best Regards,
Sunny Tham

**Comment by KenanY** [comment]
Closing as resolved then.
