### ISSUE TITLE
npm conf file?

### ISSUE THREAD

**Issue by Fabio-Ottaviani-Dev** [npm/npm#10429]
npm config get prefix
Error: EEXIST: file already exists, mkdir '/usr/local/bin/npm'
    at Error (native)

npm config ls -l
Error: EEXIST: file already exists, mkdir '/usr/local/bin/npm'
    at Error (native)

I don't know what is wrong but I can't access to the npm utility for read o set the conf, where is located the conf file in osx?
thanks.

**Comment by saywow** [comment]
The default user config file should be should be /Users/name/.npmrc
Did you see it  ? ls -a 
Also check ls -a /usr/local/bin/  
which version of node and which version of npm?

**Comment by Fabio-Ottaviani-Dev** [comment]
node -v && npm -v
v5.0.0
3.3.6

The content of .npmrc is:
prefix=/usr/local/bin/npm
is correct?

**Comment by Fabio-Ottaviani-Dev** [comment]
I erase /Users/name/.npmrc and reinstall
node now it work :)
