### ISSUE TITLE
Can't install modules with npm 3.3.6

### ISSUE THREAD

**Issue by Huaci** [npm/npm#10427]
npm http 200 https://registry.npmjs.org/yo
▀ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
loadRequestedDeps → addRe ▄ ╢██████████████████░░░░░░
░░░░░░░░░░░░░░░░░░░╟

**Comment by anton-ovinnikov** [comment]
The same is for me. Running Windows 7, using 64-bit version of the node. Trying o install bower, installation hangs.

![image](https://cloud.githubusercontent.com/assets/6938974/11214857/84638f74-8d54-11e5-9dcf-c5222507aa7c.png)

**Comment by BhaskarNewase** [comment]
Same issues, Can any one have solutions.
