### ISSUE TITLE
"c:\Microsoft.Cpp.Default.props" was not found.

### ISSUE THREAD

**Issue by christian4423** [npm/npm#10421]
I have been dealing with this issue for awhile now. 

I went to this page: https://github.com/AlexeyKupershtokh/node-v8-clone/issues/7

But it did not help me. I also made sure everything for node-gyp is installed from reading this post 
http://stackoverflow.com/questions/21365714/nodejs-error-installing-with-npm

I did the following as well:

Install python(2.x.x)
Install Microsoft Visual Studio C++ 2012 Express version
Install node-gyp: npm install -g node-gyp

I am still getting this in my console:

c:\projects\misc\affilate\node_modules\iconv\build\libiconv.vcxproj(20,3): erro
r MSB4019: The imported project "c:\Microsoft.Cpp.Default.props" was not found.
 Confirm that the path in the <Import> declaration is correct, and that the fil
e exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\NB91870\AppData\Roaming\npm\
node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Users\NB91870\AppD
ata\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js"
"rebuild"
gyp ERR! cwd c:\projects\misc\affilate\node_modules\iconv
gyp ERR! node -v v4.2.2
gyp ERR! node-gyp -v v3.0.3

**Comment by No9** [comment]
Hi 
The recommended config for native builds is documented here https://github.com/nodejs/node-gyp
I would advise against Visual studio 2012 unless you have a specific  usecase

**Comment by busches** [comment]
@christian4423 are you still facing issues installing `node-gyp`?

**Comment by Prussia** [comment]
https://github.com/Microsoft/nodejs-guidelines/blob/master/windows-environment.md#compiling-native-addon-modules
https://github.com/AlexeyKupershtokh/node-v8-clone/issues/7
Add or modify the environment variable VCTargetsPath top point at the C++ build tools path. This should be something like C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\v140 (where 140 corresponds to Visual Studio 2015)

**Comment by wzup** [comment]
@Prussia 

What you say is wrong. There is no any `Microsoft.Cpp\v4.0\v140` directories.

FYI, here is what `C:\Program Files (x86)\MSBuild` looks like

![c__program files x86 _msbuild 2016-11-16 20 16 44](https://cloud.githubusercontent.com/assets/3880497/20346953/cc5b000a-ac39-11e6-8739-5bb95af42723.png)

**Comment by KenanY** [comment]
Doesn't look like a `npm` issue to me.

**Comment by metalogix** [comment]
I had the same issue and solved it using Windows option 1 on https://github.com/nodejs/node-gyp.
First comment from No9 did it for me.

**Comment by sauravpandit** [comment]
"Installing Standalone Build Tools solved this for me"
-- @nightwolfz  I had visual studio community edition 2017 install but I am still seeing this message when I am trying to install oracledb

npm install -g  oracledb


C:\Users\Sauravp\AppData\Roaming\npm\node_modules\oracledb>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Users\Sauravp\AppData\Roaming\npm\node_modules\oracledb\build\oracledb.vcxproj(20,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not f
ound. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Sauravp\AppData\Roaming\npm\node_modules\oracledb
gyp ERR! node -v v7.8.0
gyp ERR! node-gyp -v v3.6.0
gyp ERR! not ok
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "oracledb"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

**Comment by timbophillips** [comment]
after thrashing around for a while with various google searches, github, stackoverflow etc i've made a .bat file which does it all 

https://gist.github.com/timbophillips/6e1c57b66e4cf51e4d6f94fc086f4c32

**Comment by wayofthefuture** [comment]
npm install --global --production windows-build-tools

**Comment by smesdaghi** [comment]
Note that you have to run `npm install --global --production windows-build-tools` as administrator. In my case there were no errors on install of the dev tools but still got the c:\Microsoft.Cpp.Default.props error. uninstall, open shell as admin, re install solved it for me.

**Comment by stephen-last** [comment]
I'm still getting this when trying to `npm install sharp`.

Done these as admin:

-` npm install -g --production windows-build-tools`
- `npm install -g node-gyp`

Set env var `PYTHON` to `C:\Users\stephen.last\.windows-build-tools\python27\python.exe`

Still getting:

> error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

The file `C:\Microsoft.Cpp.Default.props` is not there. 

What should I try next..?

**Comment by weeco** [comment]
@stephen-last Have you tried installing the CPP tools: http://landinghub.visualstudio.com/visual-cpp-build-tools ? I had the exact same error message and that fixed it for me.

**Comment by konstantint** [comment]
I came here from a completely different place (was trying to build CLANG via CMake in fact), but I think the problem is the same, and this issue comes up in search results higher.

Namely, Visual Studio 2017 [ships with broken VS2015 build tools](https://developercommunity.visualstudio.com/content/problem/22031/unusable-vc-build-tools-2015-installed-with-vs2017.html).

The fixes which eventually seemed to do the job were the following:
 - Comment out line 10 (`if not exist "%~dp0..\common7\IDE\wdexpress.exe" goto setup_buildsku`) in `C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat`.
 - Set the proper environment variables before building:
      - Set up the build environment variables by running `"c:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64 8.1`
      - Set an additional variable by running `set VCTargetsPath=c:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\v140`

**Comment by anand4252** [comment]
Working for me now. I ran the following command with Admin rights
`npm install -g --production windows-build-tools`

**Comment by Nauss** [comment]
`npm install -g --production windows-build-tools` worked for me too but I had to do it again after messing with the Visual Studio installation

**Comment by charce36** [comment]
npm install -g --production windows-build-tools
and
http://landinghub.visualstudio.com/visual-cpp-build-tools
Works for me, I had some problemas compiling node-sass library on Ionic rroject.

**Comment by van0303** [comment]
npm install --global --production windows-build-tools
set VCTargetsPath=%programfiles(x86)%\MSBuild\Microsoft.Cpp\v4.0\V140

**Comment by flyher** [comment]
```shell
npm install -g --production windows-build-tools
npm install -g node-gyp
```
The command work for me.
Thank you very much!
