### ISSUE TITLE
Problem with npm@3.3.12 and bundled native modules

### ISSUE THREAD

**Issue by ralphtheninja** [npm/npm#10428]
@julien-f reported an issue in the leveldown repository, see https://github.com/Level/leveldown/issues/236 which relates to installing modules with leveldown as a bundled dependency. I suspect this might be a problem for any bundled native dependency, but I'm not sure.

Anyway, Julien was very kind to setup a test case for it in this repo https://github.com/julien-f/issue-bundled-leveldown and I wrote [this script](https://github.com/Level/leveldown/issues/236#issuecomment-157233948) based on that.

For some reason it works well to install the test app the first time, i.e. with a clean `node_modules` folder. But the second time the install process is different. The first time the app is installed, the install script is run for `leveldown`, but the second time npm does unbuild but never calls the install script.

Verbose logs from both installs can be found here: https://github.com/julien-f/issue-bundled-leveldown/issues/2

cc @No9

**Comment by julien-f** [comment]
Kind of an major issue for me because it prevents me from from upgrading my package on my customers' systems…

**Comment by julien-f** [comment]
It seems to be working when (and only when):
- the module is packaged with npm 3.5.0
- the package has been initially installed with npm 3.5.0
- the package is being reinstalled by npm 3.5.0

**Comment by ralphtheninja** [comment]
@julien-f I'm not sure how you are deploying this but a workaround could be to always do clean installs, e.g. wipe `node_modules` folder every time when you deploy.

**Comment by julien-f** [comment]
That's what we are going to do but it feels like a dirty hack :/

**Comment by julien-f** [comment]
@othiym23 I am sorry to ping you directly here but I don't see any moves about this issue…

**Comment by ralphtheninja** [comment]
> That's what we are going to do but it feels like a dirty hack :/

Agree. But at least you should be able to deploy and are not blocked by npm.
