### ISSUE TITLE
Odd behaviour of `npm install <package_name>`

### ISSUE THREAD

**Issue by dvLden** [npm/npm#10436]
I am not sure if this is issue or I may need some help, but I used `npm` before and I haven't seen something like this yet in my projects.

So in the past, not sure what version it was (but it was like 15-20 days ago for sure) when I run those commands:

```
npm install -g gulp
cd ~/Sites/project_name
npm install gulp --save-dev
```

It takes some time then I get `node_modules` in my project folder which contains `gulp` folder inside.

---

But now when I do the same thing it inserts a lot of modules, not only gulp.

<img width="227" alt="screen shot 2015-11-17 at 2 28 26 pm" src="https://cloud.githubusercontent.com/assets/3460368/11212803/703986b4-8d38-11e5-95e5-b8f449e19eec.png">
<img width="226" alt="screen shot 2015-11-17 at 2 28 47 pm" src="https://cloud.githubusercontent.com/assets/3460368/11212831/92422090-8d38-11e5-9d60-90665a3ac12b.png">

---

I thought I may done something wrong, or it may be gulp issue. But whatever package I install for a project as dependency, it does the same thing... 

Is this normal acceptable behaviour in latest version or I am missing something?

### Extra details:
*OS X El Capitan 10.11.1*
*node v5.0.0*
*npm v3.4.0*

### I tried multiple npm versions, just to see what version seems to be working.
- 3.3.6 - not working
- 3.3.0 - not working
- 2.14.11 - WORKING

When I say not working I mean the issue where it adds all those extra modules/dependencies when installing single package.

I believe that those dependencies are package dependencies that should go within their package folder. At least that was behaviour in older versions...
For example:
```
– node_modules
| – package_name
| –– node_modules
| – another_package_name
| –– node_modules
```

Now I am unsure if this is new npm's feature to put package dependencies outside to main node_modules folder so that it does not download same modules for other packages that depends on them multiple times?

It's confusing... But it's ugly this way for sure.

**Comment by KenanY** [comment]
@dvLden This is basically _the_ defining feature of `npm@3`. From [the changelog](https://github.com/npm/npm/releases/tag/v3.0.0):

> Your dependencies will now be installed _maximally flat_. Insofar as is possible, all of your dependencies, and their dependencies, and THEIR dependencies will be installed in your project's `node_modules` folder with no nesting. You'll only see modules nested underneath one another when two (or more) modules have conflicting dependencies.

**Comment by dvLden** [comment]
Ah alright. I did not pay attention at changelog at all. My bad...

However, couldn't this be solved differently somehow? For example by default if all dependencies could go into single folder inside of node_modules... Or at least is there an option to make it work like that?

– node_modules
| – .bin
| – .dep => to be used for all package dependencies
| – package_name
| – another_package_name

Would be much cleaner in my opinion :satisfied:

**Comment by KenanY** [comment]
@dvLden I do not think that the Node.js module resolution algorithm would be able to pick up the dependencies in that hypothetical `.dep/` directory. The Node.js module system is locked so anything that's not related to security, performance, or bug-fixing will be swiftly rejected. So really this isn't something that `npm` can implement by itself.

(someone with greater knowledge of the module system can correct me if I am wrong)

**Comment by dvLden** [comment]
I see... Well if it has to be – it has to be. 
Although it seem much slower when I compare same task (installation of package) both globally and inside of project of version 2.14.11 and 3.4.0. 

Older version finish much faster. Anything speed related mentioned in logs where I can take a look?

**Comment by bengl** [comment]
There's a pretty good thread here on npm@3's performance: https://github.com/npm/npm/issues/10380

**Comment by dvLden** [comment]
@bengl – Thank you very much for that thread.
