### ISSUE TITLE
npm behaving very strange and inconsistent on 'npm install'.  

### ISSUE THREAD

**Issue by dtaberer** [npm/npm#10437]
Originally filed bug with gifsicle, but it was determined that npm packages were broken.

Please refer to:
https://github.com/kohler/gifsicle/issues/52#issuecomment-157243443 

gifsicle and phantomJS have been causing intermittent issues.  
Yeoman no longer works with npm.

bufferutil@1.2.1 install /
​xxx/​xxx/​xxx/bufferutil

node-gyp rebuild
make: Entering directory `/

​xxx/​xxx/​xxx/bufferutil/build'
CXX(target) Release/obj.target/bufferutil/src/bufferutil.o

SOLINK_MODULE(target) Release/obj.target/bufferutil.node

COPY Release/bufferutil.node

make: Leaving directory `/

​xxx/​xxx/​xxx/bufferutil/build'

gifsicle@3.0.3 postinstall /
​xxx/​xxx/​xxx/gifsicle

node lib/install.js
/

​xxx/​xxx/​xxx/readable-stream/lib/_stream_transform.js:151
var ts = this._transformState;

SyntaxError: Unexpected token ILLEGAL
npm-debug.log.txt
npm-debug.log.txt

at exports.runInThisContext (vm.js:53:16)
at Module._compile (module.js:404:25)
at Object.Module._extensions..js (module.js:432:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:311:12)
at Module.require (module.js:366:17)
at require (module.js:385:17)

at Object.<anonymous> (/
​xxx/​xxx/node_modules/readable-stream/lib/_stream_passthrough.js:9:17)
at Module._compile (module.js:425:26)

at Object.Module._extensions..js (module.js:432:10)
npm ERR! Linux 3.2.0-4-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.0.0
npm ERR! npm v3.3.6
npm ERR! code ELIFECYCLE
npm ERR! gifsicle@3.0.3 postinstall: node lib/install.js
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gifsicle@3.0.3 postinstall script 'node lib/install.js'.
npm ERR! This is most likely a problem with the gifsicle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! node lib/install.js
npm ERR! You can get their info via:
npm ERR! npm owner ls gifsicle
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR! /

​xxx/​xxx/npm-debug.log
bower chai#\* cached git://github.com/chaijs/chai.git#3.4.2
bower chai#\* validate 3.4.2 against git://github.com/chaijs/chai.git#*
bower mocha#\* cached git://github.com/mochajs/mocha.git#2.3.4
bower mocha#\* validate 2.3.4 against git://github.com/mochajs/mocha.git#*
[npm-debug.log.txt](https://github.com/npm/npm/files/36933/npm-debug.log.txt)

**Comment by dtaberer** [comment]
Originally filed bug with gifsicle.

https://github.com/kohler/gifsicle/issues/52#issuecomment-157243443

Got marked invalid as it was determined that this is a NPM issue.

**Comment by shidhincr** [comment]
Any solution to this ?

**Comment by airtonix** [comment]
@dtaberer gifsicle author didn't say it was a bug with npm, but the node package consuming gifsicle.

**Comment by legodude17** [comment]
@airtonix is right, file this with imagemin/gifsicle-bin. Sorry for the inconvenience!
