### ISSUE TITLE
npm ERR! code 1   Please help……

### ISSUE THREAD

**Issue by lulutia** [npm/npm#10431]
npm -v : 3.3.6
node -v: 5.0.0
I don't know why suddenly all the global modules are dispeared……then i tried to install them.
However it always showed: 
**npm ERR! code 1**
for example:

```
npm WARN install:graceful-fs ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/json-server/node_modules/configstore/node_modules/graceful-fs' -> '/usr/local/lib/node_modules/json-server/node_modules/configstore/node_modules/graceful-fs'
graceful-fs@4.1.2 node_modules/json-server/node_modules/configstore/node_modules/graceful-fs -> node_modules/json-server/node_modules/configstore/node_modules/graceful-fs
- /usr/local/lib/node_modules/json-server/node_modules/configstore node_modules/json-server/node_modules/configstore
/usr/local/lib
└── (empty)

npm ERR! code 1
```

Anybody knows how to deal with it?

**Comment by andymcfee** [comment]
Same issue.  
node v5.0.0
npm 3.4.0

**Comment by nickdbush** [comment]
I can confirm that I have the same problem reported here however it does not only effect installing modules globally. This is the output I get when running any ```npm i --save _____``` command:

    promeropidae@1.0.0 C:\Users\nickd_000\Documents\Code\Promeropidae
    └── (empty)

    npm ERR! code 1

First noticed when I switched my IDE to Atom (although this is highly relevant most likely). Using node v5.0.0 and NPM v3.4.1. The modules install successfully.

**Comment by Download** [comment]
Having the same issue:

```sh
[bridalappnode-catwalk.rhcloud.com 56df43ac7628e12f56000272]\> cd app-root/repo
[bridalappnode-catwalk.rhcloud.com repo]\> node -v
v5.7.1
[bridalappnode-catwalk.rhcloud.com repo]\> npm -v
3.8.0
[bridalappnode-catwalk.rhcloud.com repo]\> npm install history
bridalapp-ui@1.0.0 /var/lib/openshift/56df43ac7628e12f56000272/app-root/runtime/repo
└── (empty)

npm ERR! code 1
```

I think I can reproduce it on OpenShift... Let me try to see if I can workup some repro steps.

In the meantime, if anyone found a workaround, please leave a message here. I'm stuck because of this issue. I cannot deploy my work to OpenShift atm :(

**Comment by enapupe** [comment]
I'm facing the same issue. #13218

**Comment by xinde** [comment]
same issue :(

**Comment by legodude17** [comment]
Try running `npm cache clean` and then try running `npm install -g npm@latest`.

**Comment by fablife** [comment]
Same problem here, after trying to update ionic:

npm install -g ionic

I get the same:
```
- async-some@1.0.2 node_modules/ionic/node_modules/npm/node_modules/async-some
- write-file-atomic@1.1.4 node_modules/ionic/node_modules/npm/node_modules/write-file-atomic
/home/fabio/.nvm/versions/node/v5.1.0/lib
└── (empty)

npm ERR! code 
```1

And I am close to delivery....:((((

**Comment by fablife** [comment]
I "solved" it by installing a new version of node with nvm and installing ionic again....

**Comment by amogower** [comment]
I'm not sure why I had to do this again but ended up fixing this issue on my system with: 
`source ~/.bash_profile`

**Comment by benag** [comment]
same here
