### ISSUE TITLE
More info about warnings

### ISSUE THREAD

**Issue by monolithed** [npm/npm#10438]
```
➜ npm install
npm WARN engine puml-link@0.0.1: wanted: {"node":"0.10"} (current: {"node":"0.12.7","npm":"3.3.3"})
npm WARN deprecated exec@0.2.1: deprecated in favor of builtin child_process.execFile
npm WARN deprecated node.extend@1.0.0: 0.0.1
npm WARN deprecated static-favicon@1.0.0: use serve-favicon module
npm WARN prefer global node-gyp@3.1.0 should be installed with -g
```

Could you show more info about warnings?

For example:

```
npm WARN deprecated exec@0.2.1: deprecated in favor of builtin child_process.execFile
```

How to find who uses the deprecated module? `grep`, `npm ls`? It's not so convenient way

**Comment by KenanY** [comment]
@monolithed `npm ls exec`?

**Comment by monolithed** [comment]
@KenanY, I've very many warnings.

**Comment by mshenfield** [comment]
@monolithed From what I understand you want to know what modules depend on the modules listing the `WARNINGS` ?

The previous poster is correct, `npm ls <pkg>` will, according to the documentation
>    print to stdout all the versions of packages that are installed, as well as their dependencies, in a tree-structure.

You can have multiple packages in the arguments list if you want to list them all at once.

For example, if I install `foundation-cli`, which has `exec` as a dependency and run `npm ls exec`, I get the following output:

```
place-to-install-npm-stuff@1.0.0 /Users/me/workspace/place-to-install-npm-stuff
└─┬ foundation-cli@2.0.0
  └── exec@0.1.4
```

Do you have any other questions about the `WARNINGS` you received?

**Comment by monolithed** [comment]
@mshenfield, thanks for your answer. I see what you mean. 

{code}
➜ npm install

npm WARN deprecated exec@0.2.1: deprecated in favor of builtin child_process.execFile
└─ foundation-cli@2.0.0
  └── exec@0.1.4
...
{code}

That's what I expect.

**Comment by callumlocke** [comment]
:+1: I get lots of this:

```
npm WARN deprecated lodash@2.4.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0.
```

I don't even have lodash as a dependency, so what action am I supposed to take when I see this? Either npm shouldn't give me warnings about deps of deps, or it should tell me the dep chain to the deprecated module so I can do something about it

**Comment by adambuczynski** [comment]
+1

I agree that it would be handy to immediately see (in the deprecation warnings at least) which package actually triggered that error, so that I can go to their repository and complain about it :)
