### ISSUE TITLE
Error with npm trying to install cordova

### ISSUE THREAD

**Issue by avinoandrea** [npm/npm#10433]
that's my error log:

npm ERR! Error: No compatible version found: ansi@'^0.3.0'
npm ERR! Valid install targets:
npm ERR! ["0.0.1","0.0.2","0.0.3","0.0.4","0.1.0","0.1.1","0.1.2","0.2.0","0.2.1","0.3.0"]
npm ERR!     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:682:10)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:597:10
npm ERR!     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:93:15)

npm debug: https://drive.google.com/file/d/0B4osTCsSH20XSDlJaUtzV0dydE0/view?usp=sharing

**Comment by OmgImAlexis** [comment]
I have a feeling you need to update your node and npm version.
Node at at v5 and npm is at v3.

````
65 error node -v v0.10.0
366 error npm -v 1.2.14
````

Ansi installs fine for me on the latest node and npm.
````
── ansi@0.3.0 
├─┬ brunch@2.0.1
│ └─┬ chokidar@1.3.0
│   └─┬ fsevents@1.0.5
│     └─┬ node-pre-gyp@0.6.15
│       ├─┬ npmlog@1.2.1
│       │ └── ansi@0.3.0 
│       ├─┬ rimraf@2.4.3
│       │ └─┬ glob@5.0.15
│       │   └── minimatch@3.0.0 
│       └─┬ tar-pack@3.1.0
│         └─┬ fstream-ignore@1.0.3
│           └── minimatch@3.0.0 
├── minimatch@3.0.0 
└── requirejs@2.1.22  extraneous
````
