### ISSUE TITLE
npm 3 broken when installed from official OS X Node.js installer

### ISSUE THREAD

**Issue by cedx** [npm/npm#10434]
> This issue is clearly related to OS X installer of Node.js, not npm. The main solution given by the users (e.g. `sudo rm -rf /usr/local/bin/node_modules/npm` and reinstall Node.js) is sufficient to make npm works as expected.
> See nodejs/node#3606 issue for a follow-up.

Whatever NPM command I try (`npm login`, `npm install`, `npm --help`, etc.), I always have the same error message:

```
npm login
Error: Cannot find module './lib'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/index.js:1:80)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "login"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module './lib'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

Tried to remove and reinstall Node.js, but the problem is still here :(
Here is my `npm-debug.log` file:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'login' ]
2 info using npm@3.3.6
3 info using node@v5.0.0
4 verbose stack Error: Cannot find module './lib'
4 verbose stack     at Function.Module._resolveFilename (module.js:337:15)
4 verbose stack     at Function.Module._load (module.js:287:25)
4 verbose stack     at Module.require (module.js:366:17)
4 verbose stack     at require (module.js:385:17)
4 verbose stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/index.js:1:80)
4 verbose stack     at Module._compile (module.js:425:26)
4 verbose stack     at Object.Module._extensions..js (module.js:432:10)
4 verbose stack     at Module.load (module.js:356:32)
4 verbose stack     at Function.Module._load (module.js:311:12)
4 verbose stack     at Module.require (module.js:366:17)
4 verbose stack     at require (module.js:385:17)
5 verbose cwd /repo/mustache.yii
6 error Darwin 14.5.0
7 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "login"
8 error node v5.0.0
9 error npm  v3.3.6
10 error code MODULE_NOT_FOUND
11 error Cannot find module './lib'
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]
```

The only command that not fails is `npm --version`.
Other Node.js modules work as expected (so it seems that this issue is not related to Node.js v5).

EDIT : tested on Ubuntu 15.04 with the same config (e.g. Node.js 5.0.0 and NPM 3.3.6). No issue on Linux.

**Comment by cedx** [comment]
Upgraded to Node.js 5.1.0 and NPM 3.3.12: the error message is different but the issue is still here.
Here is the new output:

$ npm --help
module.js:340
    throw err;
    ^

Error: Cannot find module 'minimatch'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/rimraf/node_modules/glob/glob.js:44:17)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
```

The output is the same whatever NPM command I try. Everything is working fine on Linux.

**Comment by othiym23** [comment]
It sounds like this is still an issue with the OS X installer, which we thought / hoped was going to be a one-off issue with Node 5.0.0. @cedx, if you run `sudo rm -rf /user/local/lib/node_modules/npm` and rerun the Node installer, does that fix the problem? Either way, the underlying issue is with that installer, not with npm, so you're going to want to take this issue over to nodejs/node.

**Comment by imyejin** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

dufma555@naver.com 님께 보내신 메일 <Re: [npm] NPM 3.3.x not working on OS X Yosemite (#10434)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by MatrixV01** [comment]
I got the exact same error when I upgraded to Node 5.1.0. I was able to clear it by doing a full Node/NPM uninstall by hunting down all associated files, deleting them completely and reinstalling Node 5 from the standard link on Nodejs.org front page. I used this link to for full uninstall http://benznext.com/completely-uninstall-node-js-from-mac-os-x/

**Comment by smartmouse** [comment]
me 2, got same issue on mac-Cannot find module 'minimatch'

**Comment by yannickl** [comment]
I completely uninstall my node.js and npm modules following @othiym23 and @MatrixV01 advices and then reinstall everything using the Node v5.1.0 installer but the problem is still there...

I'm under OSX 10.11.1.

**Comment by yannickl** [comment]
After uninstalling my node.js and npm, I re-run `sudo rm -rf /user/local/lib/node_modules/npm` and then re-install everything the Node v5.1.0 installer and it seems to work!

**Comment by MatrixV01** [comment]
Glad it worked for someone else!

**Comment by othiym23** [comment]
For those coming in after the fact, this is open mostly as a convenience for npm users – the actual bug is in the Node installer for OS X, and the Node.js team is going to be where the fix for that bug comes from. The npm CLI team isn't in a position to fix the issue within npm itself.

**Comment by MatrixV01** [comment]
Agreed, this is completely a Node installer, not NPM issue. This is the first hit that comes up in Google search is why I think everyone is coming here. The NodeJS issues Github doesn't come up at all. I'll try to add the content of this to a new issue on the NodeJS Issues Github.

**Comment by MatrixV01** [comment]
https://github.com/nodejs/node/issues/3922

**Comment by MatrixV01** [comment]
Related to previous Node issue.
https://github.com/nodejs/node/issues/3606

**Comment by aviris** [comment]
Not sure if you can change the title at this point, but the behavior is the same on El Capitan as well. Macbook Pro with El Capitan did this with 5.0. Then 5.1 did the same on my Yosemite Mac Pro. 

Fortunately it does work if you manually clean up all the old Node/npm installs. If you aren't sure what that means, just follow the instructions in the link posted by MatrixV01 above.*


*I know most people here won't have this trouble, but a co-worker who should know better was a bit careless with his  use of the ```sudo rm -rf``` command & just wiped out his ```/usr/local``` directory.

**Comment by othiym23** [comment]
Good point, @aviris. I've updated the issue title to more accurately reflect what's happening. @cedx, would you mind dropping an update into your original post pointing at nodejs/node#3606?

**Comment by cedx** [comment]
Sorry, very busy these last days.
Done the same thing than others, and now npm works as expected :)
I've updated my initial post. I think we can close this issue.

**Comment by jorgecasariego** [comment]
Finally after 2 days, it worked for me! I followed  @othiym23 and @MatrixV01 advices and then I reinstalling everything using the Node v5.1.0 installer

**Comment by mattblang** [comment]
Followed @MatrixV01 's advice, uninstalled with the article he linked, reinstalled using the installer from the website, and everything is working great!

**Comment by Keyamoon** [comment]
Removing **/usr/local/lib/node_modules/npm** alone and reinstalling node using the OS X installer fixed it for me.

**Comment by fov42550564** [comment]
Keyamoon +1

**Comment by baharudinafif** [comment]
Thanks you very much, solve my problem  
Keyamoon +1

**Comment by yfain** [comment]
Tried sudo rm -rf /user/local/lib/node_modules/npm, and reinstalled node. Still have the same error: 

npm --version
module.js:329
    throw err;
    ^

Error: Cannot find module 'minimatch'
    at Function.Module._resolveFilename (module.js:327:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/rimraf/node_modules/glob/glob.js:44:17)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17)

**Comment by tqwhite** [comment]
Based on the suggestions above to track down the node and npm files, I was successful with a standard OS X nodejs installation dmg after executing these commands

sudo rm -rf /usr/local/bin/node
sudo rm /usr/local/bin/npm
sudo rm -rf /usr/local/lib/node_modules/npm

So, don't bother tracking things down. You can safely delete those and then reinstall. npm will work again.

**Comment by bglaz** [comment]
I tried the commands suggested by @tqwhite but I'm still receiving the error. Tried to install using the v5.2 installer from nodejs.org.

**Comment by rodrigobb** [comment]
http://stackoverflow.com/a/11178106/2711062 

This and reinstall v5.x worked for me

**Comment by ccharlton** [comment]
Keyamoon +1 (https://github.com/npm/npm/issues/10434#issuecomment-162381248)

**Comment by awhitford** [comment]
@tqwhite +1

**Comment by nesiri** [comment]
@tqwhite +1. Worked for me.

**Comment by aamerio** [comment]
Keyamoon +1 I've OSX 10.11.2 and your suggest it's ok! 
```
Last login: Wed Jan 13 07:39:41 on ttys000
➜  ~  npm -v
3.3.12
```

**Comment by zorglub76** [comment]
I have the same error on Windows 8.1.
When I uninstalled Node (trying to fix the error), npm folder was not removed. I removed it manually and reinstalled Node.
It works now.

**Comment by FFLAB** [comment]
the Keyamoon solution worked for me, thank you. (Mac Osx El Capitan).

**Comment by jackw** [comment]
I've just hit this issue with the node-v5.5.0 installer for OS X. @othiym23 had the answer with his original post but the command has a typo in the path.
> if you run `sudo rm -rf /user/local/lib/node_modules/npm` and rerun the Node installer, does that fix the problem?

`sudo rm -rf /usr/local/lib/node_modules/npm` followed by rerunning the Node installer worked a treat.

**Comment by pietgk** [comment]
@tqwhite +1 worked for me

**Comment by backspaces** [comment]
Yup, removing /usr/local/lib/node_modules then installing node/npm with the 5.10.1 stable worked fine.

**Comment by skylerzhang** [comment]
Keyamoon +1

**Comment by skylerzhang** [comment]
Keyamoon +1

**Comment by skylerzhang** [comment]
Keyamoon +1

**Comment by joliva-ob** [comment]
+1

**Comment by ixcamper** [comment]
Keyamoon 👍
