### ISSUE TITLE
Dependencies shared by dependencies

### ISSUE THREAD

**Issue by henit** [npm/npm#10446]
On npm 3.3.12 (node 4.2.2), the following thing happen:

I run `npm install` in a project where one of the dependencies in my project is also a dependency of one of the other dependencies. For instance:

- My project depend on PackageA and PackageB
- PackageA also depend on PackageB
- Both My project and PackageA depend on the same verison of PackageB

Then, I run `npm update` in my prroject. The NPM output lists:

    PackageB@x.x.x node_modules/PackageB -> node_modules/PackageA/node_modules/PackageB

So then suddenly PackageB is not in node_modules of my project (only in node_modules under PackageA) and require("PackageB") in the files of the project fails.

What is causing this, and how can I best avoid the issue?

**Comment by henit** [comment]
I have now upgraded to NPM 3.4.0, still the same issue.

**Comment by othiym23** [comment]
Does this problem continue if you upgrade to `npm@next`? I believe this may have been fixed by a patch that @iarna landed in `npm@3.4.1`, which is currently the next release (in testing).

**Comment by henit** [comment]
That fixed the issue. Thanks!
