### ISSUE TITLE
Running `npm prune` isn't removing package that `npm list` marks as extraneous

### ISSUE THREAD

**Issue by lexi-lambda** [npm/npm#10442]
I currently seem to have npm in a state where `npm list --depth=0` marks a package as extraneous, but it isn't removed by `npm prune`. Here's some output about my environment:

```
$ npm version
{ npm: '3.4.1',
  ares: '1.10.1-DEV',
  http_parser: '2.5.0',
  icu: '56.1',
  modules: '47',
  node: '5.0.0',
  openssl: '1.0.2d',
  uv: '1.7.5',
  v8: '4.6.85.28',
  zlib: '1.2.8' }

$ npm list --depth=0
some-project-of-mine@0.0.0 /Users/alexis/some-project-of-mine
├── babel-core@5.8.34
├── babel-jest@5.3.0
├── babelify@6.4.0
├── browserify@8.1.3
├── del@2.1.0
├── es6-promise@3.0.2
├── eslint@1.9.0
├── eslint-plugin-react@3.8.0
├── gulp@3.9.0
├── gulp-autoprefixer@3.1.0
├── gulp-bower@0.0.11
├── gulp-cache@0.4.0
├── gulp-eslint@1.1.0
├── gulp-imagemin@2.4.0
├── gulp-load-plugins@1.1.0
├── gulp-minify-css@1.2.1
├── gulp-ruby-sass@2.0.5
├── gulp-scss-lint@0.3.8
├── gulp-size@2.0.0
├── gulp-sync@0.1.4
├── gulp-uglify@1.5.1
├── gulp-useref@1.3.0
├── gulp-util@3.0.7
├── history@1.13.1
├── immutable@3.7.5
├── isomorphic-fetch@2.2.0
├── jest-cli@0.7.1
├── lodash@3.10.1
├── ramda@0.18.0
├── react@0.14.2
├── react-addons-test-utils@0.14.2
├── react-dom@0.14.2
├── react-redux@4.0.0
├── react-router@1.0.0
├── redux@3.0.4 extraneous
├── redux-actions@0.8.0
├── redux-promise@0.5.0
├── redux-router@1.0.0-beta4
├── superstatic@2.2.2
├── vinyl-source-stream@1.1.0
└── watchify@2.6.2
```

Specifically, the `redux` package is marked as extraneous. Running `npm prune` does not change the above output in any way. Note that if I install another package that nothing at all depends on, it will also (correctly) be marked as extraneous, and `npm prune` will successfully remove it.

My uneducated guess would be that since `redux` is a dependency of some of my other dependencies, it isn't being pruned, which is correct. If this is the case, though, it shouldn't show up when running `npm list --depth=0`. I think what happened is that I installed `redux` locally, then removed it from my package.json, so NPM "thinks" it's still a root, extraneous dependency, but it can't be pruned because it's needed by other packages.

If this is the case, it could be argued that this isn't a bug, _per se_, but a feature request: I would like `npm prune` to "fix" this state so that `redux` doesn't show up in the package list. Of course, I could also be completely off-base about what's going on here with my rather cursory understanding of how NPM 3 actually operates.

**Comment by iarna** [comment]
`npm prune` in npm@3 is largely untouched from npm@2, so I'm not totally surprised that it sometimes has discrepancies. =/ It needs to be rewritten in terms of npm@3 plumbing. It should be a pretty easy rewrite though!

**Comment by iarna** [comment]
@lexi-lambda Can you post the dependencies/devDependencies/optionalDependencies sections of your package.json here? Ideally I'd like the rewrite to include a test for this case you found, and that'd make it a lot easier to isolate.

**Comment by lexi-lambda** [comment]
Sure. Here's a minimal test case:

```json
{
  "name": "npm-bug-sample",
  "version": "0.0.0",
  "scripts": {},
  "dependencies": {
    "react": "^0.14.2",
    "react-redux": "^4.0.0"
  }
}
```

That alone won't cause the problem. Here are the steps to reproduce:

1. Stick that package.json somewhere (obviously).
2. Run `npm install`.
3. Run `npm install redux`.
4. Run `npm list --depth=0`.

The interesting part is that doing the process actually reveals part of what is likely causing this. After step 2 but prior to step 3, `npm list` will complain loudly about an unmet peer dependency:

```
npm-bug-sample@0.0.0 /private/tmp/sample-npm-bug
├── react@0.14.2
├── react-redux@4.0.0
└── UNMET PEER DEPENDENCY redux@^2.0.0 || ^3.0.0
```

So it's sort of correct to not prune `redux`, but it's *also* correct to mark that package as extraneous, given that it isn't in my package.json. The behavior from `npm prune` is still unintuitive, though, given that it claims to "remove all extraneous packages", but it doesn't remove them if other packages have them as peer dependencies.

Personally, I think I'd be okay if `npm prune` just removed peer dependencies and broke things. That would at least be sort of clear about how to fix the issue. A *really* awesome solution would be to have something like this:

```
$ npm prune
npm WARN extraneous peer dep: redux@3.0.4 is a peer dependency of react-redux@4.0.0, so it was not removed
```

A flag to prune extraneous peer dependencies would be the icing on the cake. But I digress: this has wandered well into "feature request" territory. :wink: I'd be satisfied by any solution that just removes the discrepancy behind `npm prune` mysteriously not pruning certain extraneous packages.

**Comment by alan-agius4** [comment]
Still nothing after a year?

**Comment by skipjack** [comment]
As @lexi-lambda pointed out, it seems the issue is when you have something in specified in `peerDependencies` it won't be pruned. I guess the real question is - is this the intended behavior or a bug?

It seems to any deps marked extraneous (which `npm ls` does mark them as), should be removed on `npm prune`. I would expect `npm prune` to entirely ignore `peerDependencies` as they shouldn't be installed under that package, though I may be missing something.

**Comment by binki** [comment]
> it seems the issue is when you have something in specified in `peerDependencies` it won't be pruned. I guess the real question is - is this the intended behavior or a bug?

This is a bug. The [top answer](https://stackoverflow.com/a/21122629/429091) for [“How to clean node_modules folder of packages that are not in package.json?”](https://stackoverflow.com/q/21122342/429091) says to run `npm prune`. Therefore, `npm prune` should actually remove anything that would not be present after running `rm -rf node_modules && npm install`.

**Comment by eudaimos** [comment]
agreed - I get 2 different results when running `npm install && npm prune --production` vs `npm install --only=production`
In my current context running `ls -l node_modules` I noticed that `fsevents` sticks around after a `prune` in a docker image

**Comment by kristopolous** [comment]
I'm so glad that buggy bots come by and close issues on the buggy code so they don't have to address their buggy documentation or acknowledge they have a buggy system. What awesome software ...
