### ISSUE TITLE
Command Prompt: npm start ERR!

### ISSUE THREAD

**Issue by Kiekeboef** [npm/npm#10441]
C:Users\Daniel>npm start
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\node.js\\node.exe" "C:\\Program Files\\node.js\\node-modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v5.0.0
npm ERR! npm v3.3.6

npm ERR! missing script: start

This is inside the npm-debug.log:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.3.6
3 info using node@v5.0.0
4 verbose config Skipping project config: C:\Users\Daniel/.npmrc. (matches userconfig)
5 verbose stack Error: missing script: start
5 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:148:19)
5 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:58:5
5 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:345:5
5 verbose stack     at handleExists (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:318:20)
5 verbose stack     at FSReqWrap.cb [as oncomplete] (fs.js:216:19)
6 verbose cwd C:\Users\Daniel
7 error Windows_NT 6.3.9600
8 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
9 error node v5.0.0
10 error npm  v3.3.6
11 error missing script: start
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]

Please help :)

**Comment by KenanY** [comment]
@Kiekeboef So, I must ask, _do_ you have a `"start"` script defined in your current working directory? Are you sure that you are in the directory that you want to be in (the log says you are in your home directory)? What are you _expecting_ `npm start` to do if you do not define what it should do?

**Comment by KenanY** [comment]
@Kiekeboef It has been several months now with no response from you... are you still seeing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
