### ISSUE TITLE
NPM install with prefix include in package.json

### ISSUE THREAD

**Issue by henit** [npm/npm#10448]
Normal installation:

```
npm install --save <module>
```

adds the module to default directory, project/node_modules and adds it to package.json.

With prefix:

```
npm install --save --prefix public <module>
```

adds the module to public/node_modules, but does not add it to package.json.

Probably supposed to work that way, but the question is, what is the best way to have one or more modules installed to a specific directory like under public (to be available as binary/static assets in this case)? I was hoping package.json could be configured to include the specific path for the given modules, so `npm install` will install all modules, including the one under the public directory.

I know I can use bower for this, but it seems a little overkill to install bower in addition to npm just to have one module in a different directory.

**Comment by shinichy** [comment]
It works as expected on Mac. I think this is a bug on Windows.

**Comment by wesleyboar** [comment]
**I had this problem also with `--prefix`, and now I do not.**

I also could not successfully use the CLI argument `--prefix` to define a local directory for `npm install`. **I was running `npm` at version `2.14.x`**. I upgraded my `npm` by running

```
npm install npm -g
```

Afterwards, **I was running `npm` at version `3.10.7`**. Now, I can use the CLI argument `--prefix` to define a local directory for `npm install`.

_**Notice:** This solution is for the CLI argument `--prefix`. I am still unable to successfully use the `prefix` configuration via any of [the other methods available](https://docs.npmjs.com/misc/config). **See [issue #13933](https://github.com/npm/npm/issues/13933).**_

**Comment by rendmath** [comment]
This bug is still occurring on Windows.

`npm install bootstrap@next --save --prefix ./public`

It installs the bootstrap module as expected, but nothing is saved in the public/package.json file. Instead, an empty etc folder is created in the public folder.

Node.js version: v6.10.3
NPM version: 5.5.1

**Comment by xPaw** [comment]
Yeah this is still a bug on npm 5.6.0. Thanks to the useless bot that closed the issue for no reason.
