### ISSUE TITLE
Alias to `npm list [-g] --depth=0`

### ISSUE THREAD

**Issue by mapaiva** [npm/npm#10443]
Hi everyone,

Exploring a litlle npm I didn't find any most simple way to list just the first tree of the packages, globally or not, than `npm list [-g] --depth=0`. I know it's already very short but programmers are lazy (at least me) and it can be a more intuitive way to tell the same thing.

I imagine that create a alias to this could be interesting. In my opinion `npm list [-g]  -s` and `npm list [-g] --short` are good options.

What do you think about that?

**Comment by btecu** [comment]
Perhaps should default to `--depth=0` and actually list the entire tree when required by a parameter.

**Comment by mapaiva** [comment]
Keep `--depth=0` as default seems a good option too :smile:

**Comment by herrmannplatz** [comment]
:+1:
