### ISSUE TITLE
Build of npm attempts to connect to the network

### ISSUE THREAD

**Issue by yurivict** [npm/npm#10452]
I just verified: on disconnected Linux virtual machine 'make' for npm hangs for a while in 'network' phase. On BSD systems build of the package isn't allowed to connect to the network. Once the project is downloaded, it should have all necessary files there.

How to prevent the build process from using the network?

We can't install npm on FreeBSD in a regular way because of this problem.

(I created similar report for node-gyp https://github.com/nodejs/node-gyp/issues/812, but they recommended to ask here.)

**Comment by iarna** [comment]
npm doesn't have a build step per se. If you're working from our git repo, you could build the documentation with `make doc`, which won't require network, but otherwise there are no build steps to do.

Alternatively you could use the tarball from our registry which looks like `http://registry.npmjs.org/npm/-/npm-3.4.0.tgz` and already has man pages & html generated.

**Comment by yurivict** [comment]
'make install' connects to network. No, I can't just take npm-3.4.0.tgz, because I am talking about the package build, and they prefer to use sources.

There should be no need to connect just to build documentation.

**Comment by yurivict** [comment]
http://registry.npmjs.org/npm/-/npm-3.4.1.tgz also attempts to connect during 'make install', and prints errors without network:

```
npm ERR! fetch failed https://registry.npmjs.org/npmlog/-/npmlog-2.0.0.tgz
npm WARN retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
loadDep:npmlog network
```

Why can't you ship npm with all necessary modules included? Then you won't need to run CachingClient at all. It should only run 'node' with JavaScript, no npm stuff during 'make install'.

I tried my best to troubleshoot this, but FreeBSD just can't build the npm package the usual way, because it keeps connecting all the time.
