### ISSUE TITLE
show progress bar when stdout is not a tty

### ISSUE THREAD

**Issue by dickeyxxx** [npm/npm#10459]
If I run this I get the progress bar on stderr:

```
$ npm install lodash
```

But if I redirect stdout, the progress bar will not display:

```
$ npm install lodash > /dev/null
```

Ultimately what I want to do is display the spinner but not the package version output from `npm install`.

**Comment by zkat** [comment]
idk why this isn't already happening ¯\_(ツ)_/¯

marked as bug. Thanks for the submission!
