### ISSUE TITLE
npm ERR! tar.unpack untar error /home/vagrant/.npm/bower/1.6.5/package.tgz

### ISSUE THREAD

**Issue by gregoryderner** [npm/npm#10455]
npm install

``` json
{
  "name": "instagram-firebase-web",
  "version": "1.0.0",
  "description": "",
  "main": "gruntfile.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/andrebaltieri/instagram-firebase-web.git"
  },
  "author": "",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/andrebaltieri/instagram-firebase-web/issues"
  },
  "homepage": "https://github.com/andrebaltieri/instagram-firebase-web#readme",
  "dependencies": {
    "bower": "^1.4.1",
    "grunt-cli": "^0.1.13",
    "grunt-contrib-copy": "^0.8.1",
    "grunt-contrib-cssmin": "^0.13.0",
    "grunt-contrib-htmlmin": "^0.4.0",
    "grunt-contrib-uglify": "^0.9.1"
  }
}
```

This error often occurs
[npm-debug.txt](https://github.com/bower/bower/files/37953/npm-debug.txt)

**Comment by imyejin** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

dufma555@naver.com 님께 보내신 메일 <[npm] npm ERR! tar.unpack untar error /home/vagrant/.npm/bower/1.6.5/package.tgz #1999 (#10455)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by KenanY** [comment]
@gregoryderner Some things you could try:

1. `npm cache clean`
2. use the [`--no-bin-links`](https://docs.npmjs.com/misc/config#bin-links) flag
3. update to the [latest stable release of `npm`](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm)

Let me know if anything helps. Keeping my fingers crossed :)

**Comment by imyejin** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

dufma555@naver.com 님께 보내신 메일 <Re: [npm] npm ERR! tar.unpack untar error /home/vagrant/.npm/bower/1.6.5/package.tgz (#10455)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by gregoryderner** [comment]
@KenanY 

Thanks for help
unfortunately not with crossed fingers or pray.

-- npm cache clean
![image](https://cloud.githubusercontent.com/assets/7066018/11246543/41a6e1a8-8dff-11e5-89d9-04ec5bc8baa1.png)

-- npm version
![image](https://cloud.githubusercontent.com/assets/7066018/11246663/c0c1039c-8dff-11e5-8895-50cb1e9e3e53.png)

-- npm install --no-bin-links
![image](https://cloud.githubusercontent.com/assets/7066018/11246723/053ff8ac-8e00-11e5-9746-ae560bc37299.png)

-- same erro
![image](https://cloud.githubusercontent.com/assets/7066018/11246767/3b58b762-8e00-11e5-8441-8454e0c39100.png)

**Comment by othiym23** [comment]
What happens if you completely remove `node_modules` and run `npm install` again?

**Comment by gregoryderner** [comment]
@othiym23  
Thanks for u time.

same error =s

I already tried it with other vms.

If I install directly in Windows (10) works normally.

**Comment by othiym23** [comment]
It looks like you're running into a long path issue, which should only be happening if there are semver conflicts in your install or if Bower ships with its dependencies bundled. If you do some googling, there are ways to tweak how Vagrant deals with long paths on Windows that may help you get past this error.

**Comment by gilhanan** [comment]
+1

**Comment by kenma9123** [comment]
I had the same problem with 3.x.x npm version. Try to downgrade it to 2.x.x version. This will solve tar.unpack problems. At least in my case.

**Comment by felipegruoso** [comment]
I had the same problem...

I solved it by adding the following line on scripts section of package.json

"postinstall": "npm install bower -g && bower install"

I hope it helps you too :)

**Comment by gregoryderner** [comment]
none of it solved. And I could not get the windows path scheme with the vagrant.
I do not like the idea of working on windows
Someone using Vagrant on windows could give a hand?

**Comment by felipegruoso** [comment]
I'm using Vagrant on Windows too..

You may try to follow this:

http://clubmate.fi/install-node-and-npm-to-a-ubuntu-box/

It is about use NVM instead of NPM. I did it before the "postinstall".
