### ISSUE TITLE
Error which creating project using yoaman

### ISSUE THREAD

**Issue by karanbisht** [npm/npm#10466]
Please check this-:

M:\Angular Study>cd EVS

M:\Angular Study\EVS>npm install -g yo
npm WARN peerDependencies The peer dependency sshpk@^1.4.6 included from http-si
gnature will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerD
ependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it
explicitly.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "yo"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! path C:\Users\samsung\AppData\Roaming\npm\node_modules\yo\node_modules\
configstore\node_modules\write-file-atomic\package.json
npm ERR! code EBUSY
npm ERR! errno -4082

npm ERR! EBUSY, open 'C:\Users\samsung\AppData\Roaming\npm\node_modules\yo\node_
modules\configstore\node_modules\write-file-atomic\package.json'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     M:\Angular Study\EVS\npm-debug.log

M:\Angular Study\EVS>

**Comment by OmgImAlexis** [comment]
Please wrap your log output like [this](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks).

I'd suggest you update your node and npm install.
````
npm ERR! node v0.12.2
npm ERR! npm v2.7.4
````
Node is currently at v5 and npm is at v3.

**Comment by KenanY** [comment]
@karanbisht Are you still seeing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
