### ISSUE TITLE
Why does npm install print junk characters to the console?

### ISSUE THREAD

**Issue by fresheneesz** [npm/npm#10469]
I'm seeing a lot of junk being written to the console on my Centos 6.5 machine with npm v3.3.12 . Stuff like this:

```
â¢ââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ
```

What is that? Here's some full output I'm getting:

```
[vagrant@localhost temp]$ npm install proto
â
extract â gunzTarPerm     â â¢ââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ
runTopLevelLifecycles     â
/home/vagrant/temp
âââ proto@1.0.19

runTopLevelLifecycles     â
npm WARN ENOENT ENOENT: no such file or directory, open '/home/vagrant/temp/package.json'
npm WARN EPACKAGEJSON temp No description
npm WARN EPACKAGEJSON temp No repository field.
npm WARN EPACKAGEJSON temp No README data
runTopLevelLifecycles     â
npm WARN EPACKAGEJSON temp No license field.
```

It looks like there are some display items, but I can't tell if information is being cut off. It looks like something is broken. Sidenote: why is it complaining about the current directory not having a package.json?

**Comment by fresheneesz** [comment]
I'm also seeing this kind of thing in areas where its listing depedencies:

```
âââ¬ chokidar@1.2.0
â âââ¬ readdirp@2.0.0
â   âââ¬ readable-stream@2.0.2
â     âââ core-util-is@1.0.1
â     âââ inherits@2.0.1
â     âââ isarray@0.0.1
â     âââ string_decoder@0.10.31
âââ¬ cpr@0.4.2
â âââ¬ rimraf@2.4.3
â   âââ¬ glob@5.0.15
â     âââ inherits@2.0.1
âââ UNMET PEER DEPENDENCY file-loader@*
âââ¬ forever@0.14.1
â âââ¬ flatiron@0.4.3
â â âââ¬ prompt@0.2.14
â â   âââ¬ utile@0.2.1
â â     âââ¬ rimraf@2.3.2
â â       âââ¬ glob@4.5.3
â â         âââ inherits@2.0.1
â âââ¬ utile@0.2.1
â   âââ¬ rimraf@2.3.2
â     âââ¬ glob@4.5.3
â       âââ inherits@2.0.1
```

**Comment by othiym23** [comment]
If you're on Linux or OS X, do you have your terminal configured to display UTF-8 with ANSI sequences? If you're on Windows, is your system using the default (UTF-8 compliant) code page?

**Comment by fresheneesz** [comment]
Ah, I'm using PuTTY and it wasn't configured to display UTF-8. I used this to improve it: http://serverfault.com/questions/378352/can-putty-be-configured-to-display-the-following-utf-8-characters . 

So it looks like those characters are attempting to display some kind of progress bar? There are still artifacts being left over and text that looks obscured. Eg installing my package.json has lots of information that looks cut off:

```
[vagrant@localhost temp]$ npm install
npm WARN install Couldn't install optional dependency: Unsupported
loadDep:micromatch → netw ▀ ╢█████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
loadDep:micromatch → get  ▀ ╢█████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
loadDep:micromatch → fetc ▄ ╢█████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
loadDep:micromatch → fetc ▌ ╢█████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
loadDep:micromatch → afte ▐ ╢█████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
loadDep:extglob → mapToRe ▀ ╢█████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
loadDep:regex-cache → req ▄ ╢█████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
loadDep:regex-cache → 200 ▌ ╢█████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
loadDep:regex-cache → net ▌ ╢█████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
loadDep:regex-cache → 200 ▀ ╢█████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
loadDep:regex-cache → 200 ▐ ╢█████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
loadDep:regex-cache → res ▐ ╢█████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
loadDep:regex-cache → get ▐ ╢█████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
loadDep:regex-cache → add ▌ ╢█████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
loadDep:regex-cache → fet ▄ ╢█████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
loadDep:regex-cache → 200 ▌ ╢█████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
loadDep:regex-cache → aft ▐ ╢█████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
loadDep:regex-cache → net ▌ ╢█████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
loadDep:regex-cache → fet ▌ ╢█████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
loadDep:array-slice → req ▀ ╢█████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
loadDep:array-slice → 200 ▐ ╢█████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
loadDep:repeat-element →  ▀ ╢█████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
loadDep:repeat-element →  ▌ ╢█████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
loadDep:repeat-element →  ▀ ╢█████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
loadDep:repeat-element →  ▀ ╢█████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
loadDep:repeat-element →  ▐ ╢█████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
loadDep:repeat-element →  ▄ ╢█████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
loadDep:fill-range → requ ▐ ╢█████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
loadDep:fill-range → 200  ▄ ╢█████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
```

And installing with my npm-shrinkwrap leaves broken looking artifacts still:

```
npm WARN install Couldn't install optional dependency: Unsupported
npm WARN EPACKAGEJSON prm@0.1.0 No repository field.
npm WARN EPACKAGEJSON prm@0.1.0 No license field.
Installing: mongodb@2 at /home/vagrant/backend/
Installing: kerberos@~0.0 at /home/vagrant/backend/
Installing: hashmap@2 at /home/vagrant/backend/
▌ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:nan → afterAdd    ▀ ╢███████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
npm WARN install Couldn't install optional dependency: Unsupported
loadDep:inflight          ▐ ╢███████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
npm WARN install Couldn't install optional dependency: Unsupported
```

Why not just use an incrementing percent rather than some fancy bar? Also If you're going to use text-based visuals for things like the dependency tree, would it be possible to use characters less likely to be misunderstood by tools that don't expect utf-8?

**Comment by jakub-g** [comment]
I've noticed junk characters in our Jenkins build in "Console output" HTML page which is at URLs like
`http://jenkins.localhost/job/.../official/1234/consoleFull`

In "raw" TXT mode they are displayed correctly
`http://jenkins.localhost/job/.../official/1234/consoleText`

It seems Jenkins improperly transforms those Unicode characters when rendering HTML view

```
22:08:56 [INFO] [INFO] 
22:08:56 [INFO] [INFO] bower@1.5.3 node_modules\bower
22:08:56 [INFO] [INFO] â”œâ”€â”€ is-root@1.0.0
22:08:56 [INFO] [INFO] â”œâ”€â”€ stringify-object@1.0.1
22:08:56 [INFO] [INFO] â”œâ”€â”€ junk@1.0.2
22:08:56 [INFO] [INFO] â”œâ”€â”€ chmodr@0.1.0
22:08:56 [INFO] [INFO] â”œâ”€â”€ user-home@1.1.1
22:08:56 [INFO] [INFO] â”œâ”€â”€ abbrev@1.0.7
22:08:56 [INFO] [INFO] â”œâ”€â”€ archy@1.0.0
22:08:56 [INFO] [INFO] â”œâ”€â”€ opn@1.0.2
22:08:56 [INFO] [INFO] â”œâ”€â”€ graceful-fs@3.0.8
22:08:56 [INFO] [INFO] â”œâ”€â”€ bower-endpoint-parser@0.2.2
```

Jenkins ver. 1.532.2

Seems a bug on Jenkins side, will open a bug for Jenkins later - unless someone knows a workaround?

**Comment by Sri55** [comment]
Hi there,

Reopening the issue:

I've noticed junk characters in our Jenkins build in "Console output" HTML page which is at URLs like
http://jenkins.localhost/job/1234/console

In "raw" TXT mode they are displayed correctly
http://jenkins.localhost/job/1234/consoleText

It seems Jenkins improperly transforms those Unicode characters when rendering HTML view

â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”�
â”‚                         â”‚ executed â”‚   failed â”‚
â”œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¤
â”‚              iterations â”‚        1 â”‚        0 â”‚
â”œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¤
â”‚                requests â”‚        3 â”‚        0 â”‚
â”œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¤
â”‚            test-scripts â”‚        3 â”‚        0 â”‚
â”œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¤
â”‚      prerequest-scripts â”‚        0 â”‚        0 â”‚
â”œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¤
â”‚              assertions â”‚        8 â”‚        0 â”‚
â”œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¤
â”‚ total run duration: 819ms                     â”‚
â”œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¤
â”‚ total data received: 12.08KB (approx)         â”‚
â”œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¤
â”‚ average response time: 188ms                  â”‚
â””â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”˜

I'm on Windows, and my system is using the default (UTF-8 compliant) code page.

using Jenkins  2.1.0.0
