### ISSUE TITLE
`npm install` complains if I have folders in a node_modules folder that don't have a package.json

### ISSUE THREAD

**Issue by fresheneesz** [npm/npm#10471]
When I run `npm install`, I'm still seeing warnings that seem to expect a package.json in every sub-directory in my node_modules folders. For example:

```
npm WARN ENOENT ENOENT: no such file or directory, open '/home/vagrant/backend/git/node_modules/db/package.json'
npm WARN ENOENT ENOENT: no such file or directory, open '/home/vagrant/backend/git/node_modules/external/package.json'
npm WARN ENOENT ENOENT: no such file or directory, open '/home/vagrant/backend/git/node_modules/integrations/package.json'
```

I'm using node_modules folders to make it easier for me to load modules when using node. Why should npm care if some directories it isn't using don't have package.json files?

**Comment by smartmouse** [comment]
when you do npm install  <package>  , npm will create the node_modules  and place the <package> there; i.e. node_modules/package/   and then there will be a package.json for that package  I think NPM think that db , external and integrations are packages.     So if you do the following:   /home/vagrant/backend/git/db and /home/vagant/backend/git/external and /home/vagrant/backend/git/integrations , that will be okay and then you can do npm install in there.

**Comment by fresheneesz** [comment]
Yes, I could create package.json files inside those directories, if that's what you're suggesting, but I don't want to. More importantly `node_modules` has a special meaning for `node.js`, and I'm using that special meaning appropriately. Npm shouldn't complain about me using node_modules files in the way they were designed to be used for node.js

**Comment by smartmouse** [comment]
no , I do not mean to create package.json in each directories., 
You are right node_modules has special meanings to both npm and node.js 
 How did you get the warning? executing  npm ls? 
I suspect that  npm treats anything inside node_modules folder as modules/package, 
that could be why it give such warning.    But it is just a warning and not error.   

I tried your scenario: by creating db, external and internal folder under my test project.
If I do npm ls , I do not see your issue. I only see the dependencies for express
Which version of node and npm are you using?

https://gist.github.com/smartmouse/38d2836fcdf89b3e3bed

**Comment by fresheneesz** [comment]
Ohh, I see I didn't make it clear I was talking about `npm install`.
