### ISSUE TITLE
npm dedupe should not be a forkbomb

### ISSUE THREAD

**Issue by georgir** [npm/npm#10475]
When I ran npm dedupe on my project, it started nicely but after a while slowed down my computer considerably. When I tried to see 'top' in a different console, it was barely updating and full of npm processes and load average was high - the last couple of updates were at 55 and then after a few minutes 80, and then the system completely stopped responding.

I checked with `find . -follow -printf ""` and I do not have symlink loops in the directory structure, and can't think of any other thing that could put the reason for this behavior in my project and not npm code.

if it is relevant, my root package.json dependencies 
```
  "dependencies": {
    "async": "^1.5.0",
    "mongodb": "^2.0.48",
    "node-expat": "^2.3.11",
    "path-to-regexp": "^1.2.1",
    "promise": "^7.0.4",
    "riot": "^2.3.1",
    "watch": "^0.16.0"
  }
```
and I have also installed a few things without --save: pm2, forever, soap, sax, express

**Comment by KenanY** [comment]
@georgir `npm --version`?

**Comment by othiym23** [comment]
`npm dedupe` itself will always run as a single process, but it runs an `npm install` (in the same process) first, to ensure all dependencies are installed before deducing. This sounds, to me, like a rogue `install` / `postinstall` / `prepublish` (at the top level) script. Check those?

**Comment by georgir** [comment]
```
npm --version
2.11.2
```
and none of those scripts at the top level.

**Comment by georgir** [comment]
Ok, I apparently had a `watch` running on the directory and it was running some other npm scripts on file change. Sorry for wasting your time, guys.
