### ISSUE TITLE
NPM install failed on powershell

### ISSUE THREAD

**Issue by ssuhat** [npm/npm#10472]
I've just reinstall my windows to windows 10. I've installed node 5.0. 
But the problem is when everytime I try to do "npm install" it got me like that. I waited for it to finish and I can't use the gulp.

![untitled](https://cloud.githubusercontent.com/assets/10653041/11264141/cf823e40-8ec3-11e5-9a3b-b2a915ee44fe.png)

What should I do to make it working again?

**Comment by GAP68** [comment]
I have windows 7.
I updated to version 5.0 NODE and then died NPM.

**Comment by ssuhat** [comment]
yes. apparently node 5.0 breaks that. need to revert the old one.
