### ISSUE TITLE
The requested URL /protractor was not found on this server

### ISSUE THREAD

**Issue by v758771** [npm/npm#10477]
Hi

I am new to angularJS trying to use protractor . when I try npm install -g protractor I am getting below error.
npm ERR! registry error parsing json
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "protractor"
npm ERR! node v5.1.0
npm ERR! npm  v3.3.12

npm ERR! Unexpected token <
npm ERR! <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
npm ERR! <html><head>
npm ERR! <title>404 Not Found</title>
npm ERR! </head><body>
npm ERR! <h1>Not Found</h1>
npm ERR! <p>The requested URL /protractor was not found on this server.</p>
npm ERR! </body></html>
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\v758771\npm-debug.log

**Comment by KenanY** [comment]
@v758771 Are you behind a proxy by any chance?

**Comment by v758771** [comment]
Yes, But I did set proxy using npm config set proxy <my proxy> but still the same issue

**Comment by KenanY** [comment]
@v758771 Sorry I haven't found any solutions to this. Are you still having this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
