### ISSUE TITLE
`npm run script` file glob not respecting `**`

### ISSUE THREAD

**Issue by fyockm** [npm/npm#10481]
Why does running the same command through npm result in different files being parsed?

``` bash
$ node node_modules/.bin/js-beautify -rn *.js lib/**/*.js
beautified index.js - unchanged
beautified lib/index2.js - unchanged
beautified lib/sub/index3.js - unchanged

$ npm run beautify

> npmglob@1.0.0 beautify /Users/drew/Projects/self/npmglob
> js-beautify -rn *.js lib/**/*.js

beautified index.js - unchanged
beautified lib/sub/index3.js - unchanged
```

for full example, please see https://github.com/fyockm/npmglob

_NOTE: This is NOT a problem with `js-beautify`. I tried with other modules as well, with the same result._

**Comment by KenanY** [comment]
Smaller test-case (well, smaller script :smiley:, same repository):

``` json
{
  "scripts": {
    "echo": "echo lib/**/*.js"
  }
}
```

``` bash
$ echo lib/**/*.js
lib/index2.js lib/sub/index3.js

$ npm run echo

> npmglob@1.0.0 echo /tmp/npmglob
> echo lib/**/*.js

lib/sub/index3.js
```

Not my area of expertise so hopefully someone else can chime in :)

**Comment by KenanY** [comment]
Hmm, not `npm`/Node.js's fault?

``` bash
$ sh -c 'echo lib/**/*.js'
lib/sub/index3.js

$ bash -c 'echo lib/**/*.js'
lib/sub/index3.js

```

**Comment by fyockm** [comment]
I still think this is an issue that needs to be fixed with `npm`.

http://stackoverflow.com/questions/21108637/glob-pattern-in-bash-dont-recognize

Your example works fine with Z shell:
```zsh
$ zsh -c 'echo lib/**/*.js'
lib/index2.js lib/sub/index3.js
```

**Comment by peter-mouland** [comment]
We have also found this error with NPM while trying to run our tests.

Our npm script for tests is `mocha test/**/*.spec.js`

When running through npm : 
`npm run test` returns `14 passing`

while running on the command line :
`mocha test/**/*.spec.js` returns `28 passing`

This is because some of our tests are in sub-directories and the glob when using npm isn't being parsed correctly.

**Comment by KenanY** [comment]
> I still think this is an issue that needs to be fixed with `npm`.

Forgive my ignorance, but how would this be done? If I am reading [the code](https://github.com/npm/npm/blob/v3.5.3/lib/utils/lifecycle.js#L209-L224) correctly, `npm` just runs your scripts using `sh`. The only solution suggested so far is to switch to `zsh`, but I do not think that making all `npm run-script` users install `zsh` is a viable solution. Maybe all that is needed is to add the
`-O extglob` flag from that StackOverflow answer?

**Comment by peter-mouland** [comment]
I've found the reason for the error i was having. Nothing to do with npm, I had to use single quotes for mocha. i.e. my package.json is now:
```json
"test": "mocha 'src/**/*.spec.js'"
```

**Comment by fyockm** [comment]
From what I read in these links, it appears that the `**` special glob pattern is only supported with bash 4. I was running 3.x. With that said, this still doesn't work for me. It appears that `sh` still runs the old version of `bash` instead of the new. Any help?

http://www.admon.org/applications/new-features-in-bash-4-0/
http://mywiki.wooledge.org/glob
http://clubmate.fi/upgrade-to-bash-4-in-mac-os-x/

**Comment by boneskull** [comment]
This isn't an npm bug and should be closed.

It's probably userland's responsibility to accept *quoted* globs on the CLI and parse them--many tools do this--since we can't rely on shells to do it consistently.  

Baking glob support into the `node` executable is probably a non-starter. 😝

**Comment by legodude17** [comment]
I agree with @boneskull. What are your thoughts @KenanY?

**Comment by KenanY** [comment]
Agreed, since I'm still not convinced that there's an issue with `npm` here.
