### ISSUE TITLE
Cannot find module 'has-unicode'

### ISSUE THREAD

**Issue by Heartnett** [npm/npm#10490]
I'm getting this error - Cannot find module 'has-unicode', literally every time I want to install a module either locally or globally.

Here is the console output:

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "nan"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'has-unicode'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\test\npm-debug.log

Here is the log file:
[npm-debug.pdf](https://github.com/npm/npm/files/39787/npm-debug.pdf)

**Comment by Heartnett** [comment]
It seems that uninstalling and then reinstalling node v0.12.2 solved it.

**Comment by Marshevskyy** [comment]
hey all. I have same issue

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "node-inspector"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'has-unicode'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/marshevskyy/work/git/npm-debug.log

in this case I am trying "npm install -g node-inspector" but it happens for all npm install ...
I already tried different node versions, but nothing helping.

Any idea what can solve this issue? and what can cause it?

**Comment by Marshevskyy** [comment]
hey all.
COMPLETELY UNINSTALL NODE.JS FROM MAC OS X fixed this issue.
http://benznext.com/completely-uninstall-node-js-from-mac-os-x/
and then download node https://nodejs.org/en/download/ and install.
