### ISSUE TITLE
npm install : specify package.json ?

### ISSUE THREAD

**Issue by gbaumgart** [npm/npm#10495]
How can i tell npm to use another package.json when running "npm install" ? All I need is "npm install -f packages-win32.json". Or is there a trick or another approach to achieve the same? Because not all npm modules are cross-platform and I'd like to use other packages per platform.

I am surprised there is no such option like in any other tool-chain...

**Comment by OmgImAlexis** [comment]
Either you need to use cross platform packages or have two separate projects, one being for Windows and one for *NIX systems.
https://docs.npmjs.com/files/package.json#os

**Comment by gbaumgart** [comment]
hi, but you are aware that any other build-chain tool from the last 25 years has the -f option? ...but ok, with hundreds of thousands files messing my project files nowadays it shouldn't matter any more.... so, thanks :-)
