### ISSUE TITLE
Unhelpful warning message: npm WARN install Couldn't install optional dependency: Unsupported

### ISSUE THREAD

**Issue by unbornchikken** [npm/npm#10494]
I get:

```
npm WARN install Couldn't install optional dependency: Unsupported
```

Which is not a very helpful warning message, ain't it? Exactly which module does it mentions?

(npm@3.3.12)

**Comment by othiym23** [comment]
This is fixed by b726a0e81abd3d3d1b415a7d8526af5dc3301b85, which is part of `npm@3.5.0`, which is currently `npm@next`.

**Comment by gildniy** [comment]
To update npm please for Windows user don't use `Git` (for me it didn't work) but instead `Composer terminal or just Windows cmd` !

**Comment by wbbhacker** [comment]
@gildniy  you are right，thx

**Comment by eljun** [comment]
It's been (2) two straight hours of finding a solution with this issue using (git bash) but of no avail. The only solution I have for now is use cmd and run 'npm install' again for this specific project.:(
