### ISSUE TITLE
npm-debug.log should contain lifecycle script stdout and stderr

### ISSUE THREAD

**Issue by saper** [npm/npm#10491]
We are getting hardly actionable bug reports at node-sass from people who post their `npm-debug.log` files but the stdout, stderr from the lifecycle scripts are missing.

Examples:

https://github.com/sass/node-sass/issues/1276

npm-debug.txt file:

https://github.com/sass/node-sass/files/39528/npm-debug.txt

https://github.com/sass/node-sass/issues/1275

npm-debug.txt file:

https://gist.github.com/superpig/801c8860c5c9893ccd0d

we can only get a messages from the system or the scripts if the users logs it separately

**Comment by zkat** [comment]
Yes please. We're leaving this open but we would _really really_ like patches. hint hint. nudge nudge.

**Comment by saper** [comment]
I love you guys, but looking at what happened to https://github.com/npm/npm/pull/9227 (a limited version landed in https://github.com/npm/npm/commit/d088b7df7a6d620d0adac53a339c0108fe5f9685, see my comments), I'd rather wait for your move first. Thanks.

**Comment by othiym23** [comment]
One way or another, this will get addressed within the next year, so if nobody else feels like poking at it, the CLI team will. (Things we'd like to see include the basic change itself, as well as only displaying run-script output in cases where there are errors during script execution, but still keeping that in the debug log output.)

Thanks for the feedback, @saper. Your contribution there _was_ useful and welcome, and I understand your hesitancy.
