### ISSUE TITLE
Not good. A lot of mistakes.

### ISSUE THREAD

**Issue by GAP68** [npm/npm#10503]
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\John\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'v' ]
2 info using npm@3.4.0
3 info using node@v5.1.0
4 verbose stack Error: Invalid package.json
4 verbose stack     at C:\Users\John\AppData\Roaming\npm\node_modules\npm\lib\view.js:81:30
4 verbose stack     at ReadFileContext.<anonymous> (C:\Users\John\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:79:21)
4 verbose stack     at ReadFileContext.callback (C:\Users\John\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:76:16)
4 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:324:13)
5 verbose cwd C:\
6 error Windows_NT 6.1.7601
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\John\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "v"
8 error node v5.1.0
9 error npm  v3.4.0
10 error Invalid package.json
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```

**Comment by othiym23** [comment]
```
4 verbose stack Error: Invalid package.json
```

Typically, this means that `package.json` has a syntax error in it (i.e. it isn't valid JSON). If you paste it here, maybe I can tell you what's missing or malformed.

**Comment by GAP68** [comment]
I do not have package.json in the root directory C: \
I'm here start his NPM v.
I tried to run the NPM and also from the home directory, and the path above it, to the root, there were no files package.json.
Before installation of version 5.0, I worked with NODE normally one year.

**Comment by othiym23** [comment]
What are you trying to do? `npm v` is short for `npm view`, and it either needs a `package.json` file (to read for information to display / fetch), or it needs an argument so that it knows what package's metadata you want to view. Were you trying to run `npm -v` instead?

**Comment by GAP68** [comment]
Ok, you're right, here I lost argument.
Thank You othiym23.
I tried to see npm information (aliases: info, show, v);
To get information - which is not the case.

Because that I can not fix the other error, or even to determine the place of its origin.
I've got a global update is not working.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\John\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "update" "-g"
npm ERR! node v5.1.0
npm ERR! npm  v3.4.0
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at module.exports (C:\Users\John\AppData\Roaming\npm\node_modules\npm\lib\install\mutate-into-logical-tree.js:12:3)
npm ERR! typeerror     at C:\Users\John\AppData\Roaming\npm\node_modules\npm\lib\outdated.js:78:5
npm ERR! typeerror     at C:\Users\John\AppData\Roaming\npm\node_modules\npm\lib\outdated.js:62:20
npm ERR! typeerror     at C:\Users\John\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-tree\rpt.js:186:9
npm ERR! typeerror     at f (C:\Users\John\AppData\Roaming\npm\node_modules\npm\node_modules\once\once.js:17:25)
npm ERR! typeerror     at C:\Users\John\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-tree\rpt.js:152:20
npm ERR! typeerror     at f (C:\Users\John\AppData\Roaming\npm\node_modules\npm\node_modules\once\once.js:17:25)
npm ERR! typeerror     at then (C:\Users\John\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-tree\rpt.js:121:22)
npm ERR! typeerror     at C:\Users\John\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-tree\rpt.js:81:20
npm ERR! typeerror     at fs.js:1657:23
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\John\npm-debug.log

**Comment by othiym23** [comment]
This looks like a simple bug, and I've changed the labels accordingly. It may be a bit before we get to it, but can you tell me what the output of `npm ls -g --depth=0` is? I want to know if there's something specific about your globally installed packages that might help us track the bug down.

**Comment by GAP68** [comment]
Well if that's the case.
Then, in order not to waste time, it is easier to remove and reinstall everything from scratch. I have been set more than 400 packages at 0 level.
If it does not fix it, I will write to you more, you are very clearly explain, 
in contrast to the verbose NPM

**Comment by othiym23** [comment]
400 packages in the global package root sounds like something did go very wrong at some point. Were you every using beta versions of `npm@3`? Starting over from scratch sounds like a good idea. Let me know if you continue to have problems.

**Comment by GAP68** [comment]
Done, all right  - v5.1.0
http://stackoverflow.com/questions/20711240/how-to-completely-remove-node-js-from-windows

**Comment by othiym23** [comment]
Did you get your problems with npm sorted out? Can we close this issue?

**Comment by GAP68** [comment]
Yes, of course, I understood.
v5.0.1 I put both at home and at work.
Thanks for the support.
There is a small compatibility issue, such as Karma does not support v5, but in general we can already work.
