### ISSUE TITLE
Problem when installing Cordova and ionic

### ISSUE THREAD

**Issue by mftafa** [npm/npm#10504]
Hi there, I'm trying to install ionic and cordova on my windows. But I receive this message below. I installed node.js v5 and npm v3. what is the problem and what can I do?
C:\Users\Mostafa>npm install -g ionic
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "ionic"
npm ERR! node v5.1.0
npm ERR! npm  v3.5.0

npm ERR! error:0906D06C:PEM routines:PEM_read_bio:no start line
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

**Comment by freed00m** [comment]
I have same issue, the problem is dependency on cordova-lib, downgrade to npm 3.3.8 to restore downoad ability. NEED FIX!
Duplicite of #10340
