### ISSUE TITLE
npm silently not installing at least one of the declared dependencies

### ISSUE THREAD

**Issue by shawninder** [npm/npm#10500]
Running `npm install` inside the [vigour-io/vigour-example](https://github.com/vigour-io/vigour-example.git) repo doesn't install all of its dependencies ([vigour-element](https://www.npmjs.com/package/vigour-element) is not installed). It's not the first time I observe behaviour like this, but of course it doesn't happen all the time either.

**Info:**

```
$ npm -v
3.3.10
$ node -v
v4.2.2
```

**Repro:**

- `git clone git@github.com:vigour-io/vigour-example.git`
- `cd vigour-example`
- `cat package.json | grep -A 5 dependencies`
```
  "dependencies": {
    "vigour-element": "^0.0.3",
    "vigour-env": "^1.0.1",
    "vigour-status-bar": "^1.0.4",
    "vigour-uikit": "^0.0.1"
  },
```
- Notice the presence of `"vigour-element": "^0.0.3"`
- Notice the existence of `vigour-element@^0.0.3` in the npm registry: https://www.npmjs.com/package/vigour-element
- `npm install`
- `cat node_modules/vigour-element/package.json | grep version`
- EXPECT: `  "version": "0.0.3",`
- OBSERVE: `cat: node_modules/vigour-element/package.json: No such file or directory`

**Resolution:**
`npm install vigour-element`

**Questions:**

- Can anyone reproduce this for this repo?
- What else can I check which could affect this?

**Comment by othiym23** [comment]
(added `needs-repro` because we need to see if `npm@3.5.0` still has this problem; @shawninder if you want to confirm yourself and let us know, that would be great!)

**Comment by shawninder** [comment]
*facepalm* I hadn't thought there would be a new version so soon. It works in `npm@3.5.0`. I'll re-open the issue if I ever run into this again. Thanks @othiym23
