### ISSUE TITLE
Deployment ERROR

### ISSUE THREAD

**Issue by sahilpaudel** [npm/npm#10507]
Installing packages from /package.json
npm ERR! Linux 3.13.0-66-generic
npm ERR! argv "/mnt/home/.nvm/versions/node/v5.1.0/bin/node" "/mnt/home/.nvm/versions/node
/v5.1.0/bin/npm" "install" "--production" "--quiet"
npm ERR! node v5.1.0
npm ERR! npm  v3.4.1

npm ERR! No compatible version found: main@server.js
npm ERR! Valid install targets:
npm ERR! 1.0.1, 1.0.0, 0.0.25, 0.0.24, 0.0.23, 0.0.22, 0.0.21, 0.0.20, 0.0.19, 0.0.18, 0.0
.17, 0.0.16, 0.0.15, 0.0.14, 0.0.12, 0.0.11, 0.0.10, 0.0.8, 0.0.7, 0.0.6, 0.0.5, 0.0.4, 0.
0.3, 0.0.2, 0.0.1, 0.0.0
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/input/npm-debug.log
npm install failed, trying again
npm ERR! Linux 3.13.0-66-generic
npm ERR! argv "/mnt/home/.nvm/versions/node/v5.1.0/bin/node" "/mnt/home/.nvm/versions/node
/v5.1.0/bin/npm" "install" "--production" "--quiet"
npm ERR! node v5.1.0
npm ERR! npm  v3.4.1

npm ERR! No compatible version found: main@server.js
npm ERR! Valid install targets:
npm ERR! 1.0.1, 1.0.0, 0.0.25, 0.0.24, 0.0.23, 0.0.22, 0.0.21, 0.0.20, 0.0.19, 0.0.18, 0.0
.17, 0.0.16, 0.0.15, 0.0.14, 0.0.12, 0.0.11, 0.0.10, 0.0.8, 0.0.7, 0.0.6, 0.0.5, 0.0.4, 0.
0.3, 0.0.2, 0.0.1, 0.0.0
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/input/npm-debug.log
npm install failed, trying again
npm ERR! Linux 3.13.0-66-generic
npm ERR! argv "/mnt/home/.nvm/versions/node/v5.1.0/bin/node" "/mnt/home/.nvm/versions/node
/v5.1.0/bin/npm" "install" "--production" "--quiet"
npm ERR! node v5.1.0
npm ERR! npm  v3.4.1

**Comment by KenanY** [comment]
@sahilpaudel Are you sure this is not an issue with your `package.json`?

**Comment by KenanY** [comment]
@sahilpaudel It has been several months now with no response from you. Are you still having this issue?

**Comment by KenanY** [comment]
Closing as abandoned and very likely to not be an issue with `npm` anyways.
