### ISSUE TITLE
npm ERR! network getaddrinfo ENOTFOUND registry.npms.org registry.npms.org:80

### ISSUE THREAD

**Issue by swapnesh** [npm/npm#10512]
Getting ENOTFOUND error in Ubuntu 14.04 while doing ionic installation. 

I tried removing http-proxy, proxy, https-proxy from npm config but no luck.

Let me know how could I resolve this npm error.

Details are in screenshot or if some other info required ....let me know.. I will readily do the things to resolve this error. BTW I am using my home network so no proxies to my best of knowledge.

![image](https://cloud.githubusercontent.com/assets/555540/11322638/580c5e04-911b-11e5-97f5-d262b28b1130.png)

**Comment by swapnesh** [comment]
More info - 

I checked my Ubuntu network proxy setting which sets to `none`.

Let me know what else I can do to resolve the issue ?

I am happy to provide more details to resolve the issue.

Screenshot -

![image](https://cloud.githubusercontent.com/assets/555540/11322678/d16fd5cc-911c-11e5-948c-27e7b88370a6.png)

**Comment by ehsalazar** [comment]
@swapnesh It looks like there is a small typo in the registry you set. Try updating it to `http://registry.npmjs.org/` Let me know if that helps.

**Comment by swapnesh** [comment]
@ehsalazar no luck, it halts upto this point and after a minute or two it throws ECONNRESET error as shown in screenshot.

BTW - in the mean time I did - 
>sudo apt-get update && sudo apt-get upgrade
> Restarted my system
> npm cache clean -f

and then again in new terminal prompt from `su` , I tried -

![image](https://cloud.githubusercontent.com/assets/555540/11325658/38173070-9179-11e5-8bba-8f5426614eb8.png)

and then serial of this error screen -

![image](https://cloud.githubusercontent.com/assets/555540/11325665/5e804364-9179-11e5-8f3a-74c2dae6b28f.png)

**Comment by swapnesh** [comment]
I resolved the issue by fixing permission from root to a user to my node_modules path, I am using personal computer and not on server so tried this and it fixes the network issue.

FYI - Please don't try the hack try at production server otherwise you may face other issues.

**Comment by ehsalazar** [comment]
@swapnesh I'm glad you were able to resolve the issue. I'll close this for now. Users will still be able to add their fixes to the thread. Thanks so much.
