### ISSUE TITLE
npm warning and nothing installs somebody help me 

### ISSUE THREAD

**Issue by Nueb** [npm/npm#10518]
System : 

Windows 7 Ultimate Fresh Install. (64 bit )
Python 2.7
Visual Studio Express 2013 for Windows Desktop
Git
Node.js latest version 5.1.0 ( 64 bit )

I am trying to install these two packages 

1] jx  https://www.npmjs.com/package/jx
2] ws https://www.npmjs.com/package/ws

but for some reason nothing installs ... i get bunch of warnings 

When i tried to install jx I got these warnings 

Your environment has been set up for using Node.js 5.1.0 (x64) and npm.

C:\Users\agario>npm install jx
C:\Users\agario
└── jx@0.1.3

npm WARN ENOENT ENOENT: no such file or directory, open 'C:\Users\agario\package
.json'
npm WARN EPACKAGEJSON agario No description
npm WARN EPACKAGEJSON agario No repository field.
npm WARN EPACKAGEJSON agario No README data
npm WARN EPACKAGEJSON agario No license field.

C:\Users\agario>

and when I tried ws I got following warnings

Your environment has been set up for using Node.js 5.1.0 (x64) and npm.

C:\Users\agario>npm install --save ws
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\agario\pack
age.json'
C:\Users\agario
└── ws@0.8.0

npm WARN ENOENT ENOENT: no such file or directory, open 'C:\Users\agario\package
.json'
npm WARN EPACKAGEJSON agario No description
npm WARN EPACKAGEJSON agario No repository field.
npm WARN EPACKAGEJSON agario No README data
npm WARN EPACKAGEJSON agario No license field.

C:\Users\agario>

Please Somebody help me !

**Comment by OmgImAlexis** [comment]
Please wrap your log output like [this](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks).

You don't have a `package.json`, run `npm init` and fill in all of the details. After that your install commands should work.

**Comment by KenanY** [comment]
@Nueb Are you still having this issue?

**Comment by Nueb** [comment]
@ KenanY  Yes I still have this issue. But It looks like I can use required modules like socket.io , etc etc .

**Comment by HyosokaPoipo** [comment]
How do you solove this error @Nueb ...?? I'm facing the same error now and still don't know what to do about package.json... :'(

**Comment by asthagaur3** [comment]
i am also getting the same problem . please let me know how to solve it

**Comment by stanwmusic** [comment]
Thanks OmgImAlexis  " npm init "was what I was needing!  I wonder why they don't bother to write that on the install page?  I meant that such a short amount of text to have to write to save newbies  days of   frustration ...

**Comment by mervenurergul** [comment]
How exactly do you fill the npm init variables?  please help me :(

**Comment by ghettifish** [comment]
@mervenurergul have you seen [this](https://docs.npmjs.com/getting-started/using-a-package.json)?

It does a decent job of explaining each variable of package.json.

**Comment by someguycodingstuff** [comment]
Same issue.  Following a simple example at the start of book by Brad Dayley.  I've used init to create the package.json.  Also copied and pasted from the book.  When I publish, there's no description, date, author etc in npm.   Trying to install it locally to another module, I get "ENOENT: no such file or directory, open 'c:\Program Files\nodejs\package.json'".  My package.json file isn't even there.  Why is it looking there?  Why doesn't it retrieve it from the tgz package?

**Comment by Rajulapatinavya** [comment]
i am also having the same problem
