### ISSUE TITLE
Package inherited timestamps from another "life".

### ISSUE THREAD

**Issue by gibatronic** [npm/npm#10528]
Olá!
I'm the owner of the `census` package and it seems npm had a package with the same name last year.

I was going to publish the `2.0.0` version when I got the `you cannot publish over the previously published` error.

```json
$ npm view census time
{ "modified": "2015-11-19T20:36:24.184Z",
   "created": "2014-04-05T15:44:38.627Z",
     "2.0.0": "2014-04-05T15:44:38.627Z",
     "0.0.0": "2015-11-12T17:07:57.045Z",
     "1.0.0": "2015-11-19T20:36:24.184Z" }

$ npm view census versions
[ "0.0.0", "1.0.0" ]
```

Is it normal for npm to keep those timestamps, even after the package was unpublished and then the name taken by another user?

Sorry if this is a know issue or expected behavior, I could not find any information about it.

**Comment by gibatronic** [comment]
Additional information:
```shell
$ node --version
v4.2.2

$ npm --version
2.14.7
```

**Comment by KenanY** [comment]
Yeah, you cannot publish over any version that has previously existed. I believe this is [completely intentional](http://blog.npmjs.org/post/77758351673/no-more-npm-publish-f).

**Comment by gibatronic** [comment]
Um... thanks @KenanY, there's an interesting reasoning about it.
I'll publish a patch or something that doesn't colide then!
