### ISSUE TITLE
npm hangs during installation of babel-* packages

### ISSUE THREAD

**Issue by sunabozu** [npm/npm#10523]
It started today. First I thought it's a network issue, but the verbose regime shows that it always hangs after writing a `package.json` file of random packages. It simply keeps blinking as if it's doing something, but I waited for hours and nothing happened.

I cleaned `~/.npm` folder, upgraded node and npm. I went to an empty folder and tried again - nothing helps. I have no problems with other packages though.

Here's an example of final output (packages can vary):

```
...
npm http fetch 200 http://registry.npm.taobao.org/babel-generator/download/babel-generator-6.2.0.tgz
npm sill fetchAndShaCheck shasum 94c36bb6729a94f8d54e823eb31fafa25fc96f61
npm verb addTmpTarball /var/folders/vh/__4hz5ws16539vm9txg93h7r0000gn/T/npm-58055-15c69e4d/registry.npm.taobao.org/babel-generator/download/babel-generator-6.2.0.tgz not in flight; adding
npm verb addTmpTarball already have metadata; skipping unpack for babel-generator@6.2.0
npm sill cache afterAdd babel-generator@6.2.0
npm verb afterAdd /Users/troorl/.npm/babel-generator/6.2.0/package/package.json not in flight; writing
npm verb afterAdd /Users/troorl/.npm/babel-generator/6.2.0/package/package.json written
```

**Comment by sunabozu** [comment]
Ok, I've figured it out. For some reason my npm installation used `http://registry.npm.taobao.org/` as a registry. I have no idea how it happened. Please, close the issue. Sorry.

**Comment by KenanY** [comment]
Closing as resolved then.
