### ISSUE TITLE
not allowing to install any libraries

### ISSUE THREAD

**Issue by navjotkaur1991** [npm/npm#10521]
I installed npm but its not downloading any libraries whenever I hit any command. Do I need to make any configs?

[npm-debug.txt](https://github.com/npm/npm/files/41401/npm-debug.txt)

**Comment by Nueb** [comment]
run node cmd from different directory other than Program files/nodejs/...

"silly cache"

**Comment by KenanY** [comment]
@navjotkaur1991 Are you still seeing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
