### ISSUE TITLE
while giving command "npm install" getting follwing error

### ISSUE THREAD

**Issue by santhoshi-viriventi** [npm/npm#10520]
npm WARN package.json todomvc@0.1.1 No repository field.
npm WARN package.json todomvc@0.1.1 No license field.
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit 
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:203:12)
npm WARN addRemoteGit     at emitTwo (events.js:87:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:172:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:818:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:319:11)
npm WARN addRemoteGit     at emitOne (events.js:77:13)
npm WARN addRemoteGit     at Socket.emit (events.js:169:7)
npm WARN addRemoteGit     at Pipe._onclose (net.js:469:12)
npm WARN addRemoteGit  git://github.com/azakus/dom-serializer.git#self-closing-svg resetting remote C:\Users\sviriven\AppData\Roaming\npm-cache\_git-remotes\git-github-com-azakus-dom-serializer-git-955b44a3 because of error: { [Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit ]
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
npm ERR! git clone --template=C:\Users\sviriven\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/azakus/dom-serializer.git C:\Users\sviriven\AppData\Roaming\npm-cache\_git-remotes\git-github-com-azakus-dom-serializer-git-955b44a3: Cloning into bare repository 'C:\Users\sviriven\AppData\Roaming\npm-cache\_git-remotes\git-github-com-azakus-dom-serializer-git-955b44a3'...
npm ERR! git clone --template=C:\Users\sviriven\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/azakus/dom-serializer.git C:\Users\sviriven\AppData\Roaming\npm-cache\_git-remotes\git-github-com-azakus-dom-serializer-git-955b44a3: fatal: unable to connect to github.com:
npm ERR! git clone --template=C:\Users\sviriven\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/azakus/dom-serializer.git C:\Users\sviriven\AppData\Roaming\npm-cache\_git-remotes\git-github-com-azakus-dom-serializer-git-955b44a3: github.com[0: 192.30.252.130]: errno=No error
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\sviriven\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/azakus/dom-serializer.git C:\Users\sviriven\AppData\Roaming\npm-cache\_git-remotes\git-github-com-azakus-dom-serializer-git-955b44a3
npm ERR! Cloning into bare repository 'C:\Users\sviriven\AppData\Roaming\npm-cache\_git-remotes\git-github-com-azakus-dom-serializer-git-955b44a3'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.130]: errno=No error
npm ERR! 
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Users\sviriven\.jenkins\jobs\asdf\workspace\npm-debug.log
Build step 'Execute Windows batch command' marked build as failure
Finished: FAILURE

**Comment by KenanY** [comment]
```
npm ERR! fatal: unable to connect to github.com:
```

Looks like an internet connection issue. If you are behind a proxy or firewall you'll need to configure `git`/`npm` appropriately.

**Comment by KenanY** [comment]
@santhoshi-viriventi It has been several months now with no reply from you. Are you still having this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
