### ISSUE TITLE
`npm update --save` duplicates devDependencies as dependencies

### ISSUE THREAD

**Issue by jdhiro** [npm/npm#10531]
`npm update --save` duplicates updated devDependencies into the dependency sections, and leaves the old version is devDependencies. It seems like --save should update all dependencies in their appropriate section (preferred) or skip devDependencies.

It seems that running `npm update --save-dev` before `npm update --save` keeps everything in order though.

```
npm --version                                                                                                                                          
3.3.9
```

Before `npm update --save`

``` json
  "dependencies": {
  },
  "devDependencies": {
    "babel-core": "^6.1.18"
  }
```

After `npm update --save`

``` json
  "dependencies": {
    "babel-core": "^6.2.1"
  },
  "devDependencies": {
    "babel-core": "^6.1.18"
  }
```

**Comment by lfdoherty** [comment]
Just happened to me in 3.10.3. Maybe it's time to add a warning to the docs about using this feature?

**Comment by broofa** [comment]
For anyone stumbling across this, you can use https://github.com/tjunnone/npm-check-updates as an interim solution until this is fixed. 

(Found this via https://github.com/npm/npm/issues/3417#issuecomment-107376643)

**Comment by cozmy** [comment]
It's still present in npm 4.4.4.
