### ISSUE TITLE
npm fails: install Refusing to install phonegap as a dependency of itself

### ISSUE THREAD

**Issue by ppetree** [npm/npm#10534]
Run as Administrator:

npm ERR! node v4.2.2
npm ERR! npm v2.14.7

------------------------- npm-debug.log -------------------------
0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli 'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli 'install',
1 verbose cli '–g',
1 verbose cli 'phonegap' ]
2 info using npm@2.14.7
3 info using node@v4.2.2
4 verbose install initial load of C:\Domains\wwwroot\mobile\workspace\phonegap\phonegap-cli\package.json
5 verbose readDependencies loading dependencies from C:\Domains\wwwroot\mobile\workspace\phonegap\phonegap-cli\package.json
6 silly cache add args [ '–g', null ]
7 verbose cache add spec –g
8 warn install Refusing to install phonegap as a dependency of itself
9 silly cache add parsed spec Result {
9 silly cache add raw: '–g',
9 silly cache add scope: null,
9 silly cache add name: null,
9 silly cache add rawSpec: '–g',
9 silly cache add spec: 'C:\Domains\wwwroot\mobile\workspace\phonegap\phonegap-cli\–g',
9 silly cache add type: 'local' }
10 error addLocal Could not install C:\Domains\wwwroot\mobile\workspace\phonegap\phonegap-cli\–g
11 verbose stack Error: ENOENT: no such file or directory, open 'C:\Domains\wwwroot\mobile\workspace\phonegap\phonegap-cli\–g'
11 verbose stack at Error (native)
12 verbose cwd C:\Domains\wwwroot\mobile\workspace\phonegap\phonegap-cli
13 error Windows_NT 6.0.6002
14 error argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "–g" "phonegap"
15 error node v4.2.2
16 error npm v2.14.7
17 error path C:\Domains\wwwroot\mobile\workspace\phonegap\phonegap-cli\–g
18 error code ENOENT
19 error errno -4058
20 error syscall open
21 error enoent ENOENT: no such file or directory, open 'C:\Domains\wwwroot\mobile\workspace\phonegap\phonegap-cli\–g'
21 error enoent This is most likely not a problem with npm itself
21 error enoent and is related to npm not being able to find a file.
22 verbose exit [ -4058, true ]

**Comment by KenanY** [comment]
@ppetree It looks like you are using a hyphen-minus in `–g` instead of just a regular hyphen. Why? Do you think hyphen-minuses should be supported? As far as I know, no program supports using them to set flags.

**Comment by ppetree** [comment]
I retyped the command as npm install phonegap -g and that seems to be working... not sure where (or what) a hyphen-minus is or came from... but I did get further before it crapped out...

It ran for quite a while and then barfed up an ECONNRESET error... 

Short version here (long version attached):

[npm-debug.txt](https://github.com/npm/npm/files/42142/npm-debug.txt)

**Comment by KenanY** [comment]
@ppetree Are you still seeing this issue? `ECONNRESET` is indicative of an issue with your internet connection (i.e. proxy or firewall).

**Comment by ppetree** [comment]
I abandoned that whole npm/phonegap  boondoggle and moved over to Intel XDK. And, after using it for 5 months, I can't for the life of me figure out why anyone is still doing  things the hard way! lOL

Thanks for checking up on me though... I really do appreciate it!

**Comment by KenanY** [comment]
Alright, closing then :)
