### ISSUE TITLE
case-aware dedupe

### ISSUE THREAD

**Issue by stefanpenner** [npm/npm#10537]
I searched existing issues, and was unable to find something similar (although maybe I missed it)

Anyways, it appears the following packages, base64 Base64 are considered the same when deduping. 
I believe no additional case related conflicts are allowed on npm, but existing ones can still cause grief.

Some thoughts on solving:
- warn when encountering such a scenario
- consider the case sensitivity when deduping to prevent an issue

**Comment by iarna** [comment]
We need to put together a reproducer for this.
