### ISSUE TITLE
Peerinvalid error, but no info about which peer dependency was violated

### ISSUE THREAD

**Issue by super-cache-money** [npm/npm#10538]
I'm using 2.14.7, and running into a problem trying to figure out how to resolve a peerinvalid error.

Here's the relevant output from `npm install`:

```
npm ERR! Linux 3.19.0-33-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react-dom@0.14.0 does not satisfy its siblings' peerDependencies requirements!

npm ERR! Please include the following file with any support request:
npm ERR!     /path/to/my/project/npm-debug.log
```

As you can see, there's no suggestion of which peer wants a different version of `react-dom` here, so I'm not sure how to start resolving this. I've also attached my npm-debug, in case it's of any use.

If necessary I can upload npm-debug.log.

**Comment by OmgImAlexis** [comment]
`npm ls` should give you the output you're looking for so you can drill down and find which package is needing what.

**Comment by guncha** [comment]
It most certainly should be a part of the error message as it has been for previous versions.
