### ISSUE TITLE
[MEAN.js] v8-debug@0.4.6 install: `node-pre-gyp install --fallback-to-build`

### ISSUE THREAD

**Issue by jackoxmas** [npm/npm#10543]
I keep getting errors with `sudo npm install` on MEAN.js yo generated stacks.  I've tried it on two separate stacks and am receiving the same (or very similar) errors both times.  Any and all help is appreciated as I've put in ~15 hours trying to research and fix this issue already.

On the first (newly yo meanjs generated):

	$ sudo npm install
	npm WARN install Couldn't install optional dependency: Unsupported
	npm WARN lifecycle v8-debug@0.5.4~preinstall: cannot run in wd %s %s (wd=%s) v8-debug@0.5.4   /home/jack/Desktop/newTestTwo/mean/node_modules/.staging/v8-debug-375cffe27ed703d52b9be741925d3254
	npm WARN prefer global node-inspector@0.12.3 should be installed with -g

	> bufferutil@1.2.1 install /home/jack/Desktop/newTestTwo/mean/node_modules/bufferutil
	> node-gyp rebuild

	make: Entering directory `/home/jack/Desktop/newTestTwo/mean/node_modules/bufferutil/build'
	  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
	/home/jack/Desktop/newTestTwo/mean/node_modules/.bin/touch: 1: /home/jack/Desktop/newTestTwo/mean/node_modules/.bin/touch: Syntax error: "(" unexpected
	make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 2
	make: Leaving directory `/home/jack/Desktop/newTestTwo/mean/node_modules/bufferutil/build'
	gyp ERR! build error 
	gyp ERR! stack Error: `make` failed with exit code: 2
	gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
	gyp ERR! stack     at emitTwo (events.js:87:13)
	gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
	gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
	gyp ERR! System Linux 3.19.0-33-generic
	gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
	gyp ERR! cwd /home/jack/Desktop/newTestTwo/mean/node_modules/bufferutil
	gyp ERR! node -v v5.0.0
	gyp ERR! node-gyp -v v3.0.3
	gyp ERR! not ok 
	npm WARN install:bufferutil bufferutil@1.2.1 install: `node-gyp rebuild`
	npm WARN install:bufferutil Exit status 1

	> utf-8-validate@1.2.1 install /home/jack/Desktop/newTestTwo/mean/node_modules/utf-8-validate
	> node-gyp rebuild

	make: Entering directory `/home/jack/Desktop/newTestTwo/mean/node_modules/utf-8-validate/build'
	  CXX(target) Release/obj.target/validation/src/validation.o
	/home/jack/Desktop/newTestTwo/mean/node_modules/.bin/touch: 1: /home/jack/Desktop/newTestTwo/mean/node_modules/.bin/touch: Syntax error: "(" unexpected
	make: *** [Release/obj.target/validation/src/validation.o] Error 2
	make: Leaving directory `/home/jack/Desktop/newTestTwo/mean/node_modules/utf-8-validate/build'
	gyp ERR! build error 
	gyp ERR! stack Error: `make` failed with exit code: 2
	gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
	gyp ERR! stack     at emitTwo (events.js:87:13)
	gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
	gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
	gyp ERR! System Linux 3.19.0-33-generic
	gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
	gyp ERR! cwd /home/jack/Desktop/newTestTwo/mean/node_modules/utf-8-validate
	gyp ERR! node -v v5.0.0
	gyp ERR! node-gyp -v v3.0.3
	gyp ERR! not ok 
	npm WARN install:utf-8-validate utf-8-validate@1.2.1 install: `node-gyp rebuild`
	npm WARN install:utf-8-validate Exit status 1

	> v8-debug@0.5.4 install /home/jack/Desktop/newTestTwo/mean/node_modules/v8-debug
	> node-pre-gyp install --fallback-to-build

	make: Entering directory `/home/jack/Desktop/newTestTwo/mean/node_modules/v8-debug/build'
	  CXX(target) Release/obj.target/debug/src/debug.o
	/home/jack/Desktop/newTestTwo/mean/node_modules/.bin/touch: 1: /home/jack/Desktop/newTestTwo/mean/node_modules/.bin/touch: Syntax error: "(" unexpected
	make: *** [Release/obj.target/debug/src/debug.o] Error 2
	make: Leaving directory `/home/jack/Desktop/newTestTwo/mean/node_modules/v8-debug/build'
	gyp ERR! build error 
	gyp ERR! stack Error: `make` failed with exit code: 2
	gyp ERR! stack     at ChildProcess.onExit (/home/jack/Desktop/newTestTwo/mean/node_modules/node-gyp/lib/build.js:270:23)
	gyp ERR! stack     at emitTwo (events.js:87:13)
	gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
	gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
	gyp ERR! System Linux 3.19.0-33-generic
	gyp ERR! command "/usr/local/bin/node" "/home/jack/Desktop/newTestTwo/mean/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/jack/Desktop/newTestTwo/mean/node_modules/v8-debug/build/debug/v0.5.4/node-v47-linux-x64/debug.node" "--module_name=debug" "--module_path=/home/jack/Desktop/newTestTwo/mean/node_modules/v8-debug/build/debug/v0.5.4/node-v47-linux-x64"
	gyp ERR! cwd /home/jack/Desktop/newTestTwo/mean/node_modules/v8-debug
	gyp ERR! node -v v5.0.0
	gyp ERR! node-gyp -v v3.1.0
	gyp ERR! not ok 
	node-pre-gyp ERR! build error 
	node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /home/jack/Desktop/newTestTwo/mean/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/jack/Desktop/newTestTwo/mean/node_modules/v8-debug/build/debug/v0.5.4/node-v47-linux-x64/debug.node --module_name=debug --module_path=/home/jack/Desktop/newTestTwo/mean/node_modules/v8-debug/build/debug/v0.5.4/node-v47-linux-x64' (1)
	node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/jack/Desktop/newTestTwo/mean/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
	node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
	node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
	node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
	node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
	node-pre-gyp ERR! System Linux 3.19.0-33-generic
	node-pre-gyp ERR! command "/usr/local/bin/node" "/home/jack/Desktop/newTestTwo/mean/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
	node-pre-gyp ERR! cwd /home/jack/Desktop/newTestTwo/mean/node_modules/v8-debug
	node-pre-gyp ERR! node -v v5.0.0
	node-pre-gyp ERR! node-pre-gyp -v v0.6.15
	node-pre-gyp ERR! not ok 
	Failed to execute '/usr/local/bin/node /home/jack/Desktop/newTestTwo/mean/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/jack/Desktop/newTestTwo/mean/node_modules/v8-debug/build/debug/v0.5.4/node-v47-linux-x64/debug.node --module_name=debug --module_path=/home/jack/Desktop/newTestTwo/mean/node_modules/v8-debug/build/debug/v0.5.4/node-v47-linux-x64' (1)
	meanjs@0.4.2 /home/jack/Desktop/newTestTwo/mean
	├─┬ bower@1.6.5
	│ ├─┬ request@2.53.0
	│ │ └─┬ form-data@0.2.0
	│ │   └── async@0.9.2 
	│ └── which@1.2.0 
	├─┬ coveralls@2.11.4
	│ └─┬ request@2.40.0
	│   └─┬ form-data@0.1.4
	│     └── async@0.9.2 
	├─┬ grunt-contrib-less@1.1.0
	│ └── async@0.9.2 
	├─┬ grunt-contrib-sass@0.9.2
	│ └── async@0.9.2 
	├─┬ grunt-protractor-coverage@0.2.15
	│ └─┬ coverage-collector@0.0.4
	│   └─┬ istanbul@0.2.16
	│     └── async@0.9.2 
	├─┬ grunt-protractor-runner@2.1.0
	│ └─┬ protractor@2.5.1
	│   └─┬ request@2.57.0
	│     └─┬ form-data@0.2.0
	│       └── async@0.9.2 
	├─┬ gulp-protractor@1.0.0
	│ └── async@0.9.2 
	├─┬ gulp-sass@2.1.0
	│ └─┬ node-sass@3.4.2
	│   ├─┬ cross-spawn@2.0.0
	│   │ └─┬ cross-spawn-async@2.0.0
	│   │   └── which@1.2.0 
	│   └─┬ sass-graph@2.0.1
	│     └─┬ yargs@3.30.0 
	│       ├── cliui@3.0.3 
	│       └── window-size@0.1.4 
	├─┬ karma-coverage@0.4.2
	│ └─┬ istanbul@0.3.22
	│   └── which@1.2.0 
	└─┬ supertest@1.1.0
	  └─┬ superagent@1.3.0
	    └─┬ form-data@0.2.0
	      └── async@0.9.2 

	npm WARN EPEERINVALID mongodb-core@1.2.24 requires a peer of kerberos@~0.0 but none was installed.
	npm ERR! Linux 3.19.0-33-generic
	npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
	npm ERR! node v5.0.0
	npm ERR! npm  v3.3.6
	npm ERR! code ELIFECYCLE

	npm ERR! v8-debug@0.5.4 install: `node-pre-gyp install --fallback-to-build`
	npm ERR! Exit status 1
	npm ERR! 
	npm ERR! Failed at the v8-debug@0.5.4 install script 'node-pre-gyp install --fallback-to-build'.
	npm ERR! This is most likely a problem with the v8-debug package,
	npm ERR! not with npm itself.
	npm ERR! Tell the author that this fails on your system:
	npm ERR!     node-pre-gyp install --fallback-to-build
	npm ERR! You can get their info via:
	npm ERR!     npm owner ls v8-debug
	npm ERR! There is likely additional logging output above.

	npm ERR! Please include the following file with any support request:
	npm ERR!     /home/jack/Desktop/newTestTwo/mean/npm-debug.log

With the debug log mentioned in the last line attached.

[npm-debug.txt](https://github.com/npm/npm/files/43027/npm-debug.txt)

Second build (an old build) ends with:

	npm WARN EPEERINVALID grunt-nodemon@0.3.0 requires a peer of grunt@~0.4.1 but none was installed.
	npm WARN EPACKAGEJSON bandwagon@0.0.1 No repository field.
	npm WARN EPACKAGEJSON bandwagon@0.0.1 No license field.
	npm ERR! Linux 3.19.0-33-generic
	npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
	npm ERR! node v5.0.0
	npm ERR! npm  v3.3.6
	npm ERR! code ELIFECYCLE

	npm ERR! v8-debug@0.4.6 install: `node-pre-gyp install --fallback-to-build`
	npm ERR! Exit status 1
	npm ERR! 
	npm ERR! Failed at the v8-debug@0.4.6 install script 'node-pre-gyp install --fallback-to-build'.
	npm ERR! This is most likely a problem with the v8-debug package,
	npm ERR! not with npm itself.
	npm ERR! Tell the author that this fails on your system:
	npm ERR!     node-pre-gyp install --fallback-to-build
	npm ERR! You can get their info via:
	npm ERR!     npm owner ls v8-debug
	npm ERR! There is likely additional logging output above.

	npm ERR! Please include the following file with any support request:
	npm ERR!     /home/jack/Desktop/ntt/bandwagon/npm-debug.log

With that log attached too.

[npm-debug2.txt](https://github.com/npm/npm/files/43026/npm-debug2.txt)

Any and all help is seriously appreciated, even if just pointing me to the right people to ask the question to!

**Comment by simonh1000** [comment]
I am seeing something similar with NPM v3
```
 npm install -save mongodb
eu-transparency-register@1.1.0 /home/simon/code/btsync/Elm/euregister
└─┬ mongodb@2.0.49 
  ├── es6-promise@2.1.1 
  ├── UNMET PEER DEPENDENCY kerberos@~0.0
  ├─┬ mongodb-core@1.2.24 
  │ └── bson@0.4.19 
  └─┬ readable-stream@1.0.31 
    ├── core-util-is@1.0.2 
    ├── inherits@2.0.1 
    ├── isarray@0.0.1 
    └── string_decoder@0.10.31 

npm WARN EPEERINVALID mongodb-core@1.2.24 requires a peer of kerberos@~0.0 but none was installed.
```

**Comment by darfux** [comment]
```
/home/jack/Desktop/newTestTwo/mean/node_modules/.bin/touch: 1: 
/home/jack/Desktop/newTestTwo/mean/node_modules/.bin/touch: Syntax error: "(" unexpected
```
The npm's **touch** script hides the binary **touch** in */usr/bin/touch* which causes make failed. My temporarily solution is  renaming the .../node_modules/.bin/touch to .../node_modules/.bin/touch.bak and then do the compile. After that you can recover the npm's touch to it's original name:)

**Comment by jackoxmas** [comment]
I had two issues:
#1 node-gyp-pre wasn't installed, just node-gyp.
#2 I had to revert to an older version of node/npm to get it to work (v4.4.2 and v2.14.7 respectively).

**Comment by mayankkalbhor** [comment]
Upgrade your compilers
