### ISSUE TITLE
need to get rid of cli's faq doc

### ISSUE THREAD

**Issue by ashleygwilliams** [npm/npm#10546]
it is hostile, not helpful, and in some instances straight up incorrect.

pr incoming

**Comment by ashleygwilliams** [comment]
in the meantime, i'm striking it from the docs page.

**Comment by othiym23** [comment]
There's useful content in that page I'd like to keep elsewhere, so I'm going to wait on merging this until the whole CLI team and @ashleygwilliams have a chance to go over it (probably with @isaacs in the room, too, as he and I have similar feelings about some of the more opinionated content in there).

**Comment by othiym23** [comment]
Reworded the commit message (for style, and to add a little bit of context for the removal) and landed for `npm@3` as b88c37c1cced40e9e41402cc54a5efc3c33cd13e. Will do the same for `npm@2` shortly.

**Comment by othiym23** [comment]
I think what would be a good replacement for the FAQ would be a short document (or maybe a reworking of the developer's guide) that lays out the areas where npm is opinionated, and why. If done properly, it won't feel as confrontational as the FAQ, and might get better traction that way anyway. Cherry-picked for `npm@2` as 1fc7f2b523ea760e08adb9b861b28e3ba450e565.
