### ISSUE TITLE
Error: Cannot find module 'mongodb'

### ISSUE THREAD

**Issue by saharravanbakhsh** [npm/npm#10544]
Y:\Desktop\Node.js\test2>npm start

> test2@0.0.0 start Y:\Desktop\Node.js\test2
> node ./bin/www

module.js:339
    throw err;
    ^

Error: Cannot find module 'mongodb'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (Y:\Desktop\Node.js\test2\app.js:8:13)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\localcache\\SaRavanbakhsh\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! test2@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the test2@0.0.0 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the test2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get their info via:
npm ERR!     npm owner ls test2
npm ERR! There is likely additional logging output above.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\localcache\\SaRavanbakhsh\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.12
npm ERR! path Y:\Desktop\Node.js\test2\npm-debug.log.79ca8ba86aa92935fa3f09e5ad74cc0b
npm ERR! code EBUSY
npm ERR! errno -4082
npm ERR! syscall rename

npm ERR! EBUSY: resource busy or locked, rename 'Y:\Desktop\Node.js\test2\npm-debug.log.79ca8ba86aa92935fa3f09e5ad74cc0b' -> 'Y:\Desktop\Node.js\test2\npm-debug.log'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     Y:\Desktop\Node.js\test2\npm-debug.log

Y:\Desktop\Node.js\test2>

**Comment by watilde** [comment]
Have you already tried `npm install mongodb`? Also you may can see dependencies of your app on the dependencies field in your `package.json`. More details can be found here: https://docs.npmjs.com/files/package.json#dependencies

**Comment by KenanY** [comment]
@saharravanbakhsh Are you still experiencing this issue by any chance?

**Comment by KenanY** [comment]
Closing as abandoned.
