### ISSUE TITLE
Binary from deep dependency exposed to .bin folder wrongly

### ISSUE THREAD

**Issue by lijunle** [npm/npm#10541]
Here is the `package.json` file:

``` json
{
  "dependencies": {
    "express-react-views": "0.9.0"
  },
  "devDependencies": {
    "babel-cli": "^6.2.0"
  }
}
```
- `express-react-views` depends on babel 5.x, which expose `babel-node` binary.
- `babel-cli` exposes `babel-node` binary too, which I expect to use.

Run `npm i` to install the dependencies. The `./node_modules/.bin/babel-node` is exposed by `babel` package wrongly, expected to be exposed by `babel-cli` package.

---

Here is the details:

``` sh
$ cat ./node_modules/.bin/babel-node
#!/bin/sh
basedir=`dirname "$0"`

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  "$basedir/node"  "$basedir/../babel/bin/babel-node.js" "$@" // <---------- check this line
  ret=$?
else
  node  "$basedir/../babel/bin/babel-node.js" "$@"
  ret=$?
fi
exit $ret
```

``` sh
$ head -n 10 ./node_modules/babel/package.json // <------ babel is on the root folder!!!
{
  "_args": [
    [
      "babel@^5.8.23",
      "/path/to/tmp/node_modules/express-react-views" // <------ installed by express-react-views package
    ]
  ],
  "_from": "babel@>=5.8.23 <6.0.0",
  "_id": "babel@5.8.34",
  "_inCache": true,
```

Environment:

``` sh
$ node --version
v5.1.0
$ npm --version
3.3.12
```

Finally, [here](https://travis-ci.org/lijunle/depcheck-www/builds/92948121) is a live build affected by this bug. Node 4 with npm 2.x is passed, however node 5 with npm 3 fails.

**Comment by sheerun** [comment]
It is related to #10095

**Comment by lijunle** [comment]
Your issue is closed, is it fixed?

**Comment by sheerun** [comment]
No, I'm waiting for an answer there for 2 weeks

**Comment by jkrems** [comment]
Running into (almost) the same problem. The `babel` CLI command installed via `babel-cli@6.x` gets randomly overwritten if any sub-sub-sub-dependency has a dependency on `babel@5.x`. This makes it almost impossible to use `node_modules/.bin` with any degree of certainty. :(

**Comment by jkrems** [comment]
For other people finding this issue - I worked around it by adding a `postinstall` script to my `package.json`:

```js
{
  "scripts": {
    "postinstall": "npm rebuild babel-cli"
  }
}
```

**Comment by jkrems** [comment]
The fix could be to have a deterministic order of building the packages where it's guaranteed that top-level dependencies build last. That wouldn't handle the case where someone runs `npm install package-with-dep-that-would-cause-problems` but it would at least fix the `npm install` case.
