### ISSUE TITLE
ionic installation error

### ISSUE THREAD

**Issue by munishgautam** [npm/npm#10549]
Failed at the node-sass@3.4.2 postinstall script `node scripts/build.js`.

**Comment by KenanY** [comment]
@munishgautam I do not think that enough information has been provided to even determine if this is an issue with `npm`. Could you please upload the `npm-debug.log` as a [gist](https://gist.github.com/)?

**Comment by munishgautam** [comment]
C:\Program Files\nodejs>npm install -g ionic
C:\Documents and Settings\mdi\Application Data\npm\ionic -> C:\Documents and Set
tings\mdi\Application Data\npm\node_modules\ionic\bin\ionic

> node-sass@3.4.2 install C:\Documents and Settings\mdi\Application Data\npm\nod
e_modules\ionic\node_modules\ionic-app-lib\node_modules\node-sass
> node scripts/install.js

Binary downloaded and installed at C:\Documents and Settings\mdi\Application Dat
a\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\node-sass\vendo
r\win32-ia32-47\binding.node

> spawn-sync@1.0.14 postinstall C:\Documents and Settings\mdi\Application Data\n
pm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\cross-spawn\node_m
odules\spawn-sync
> node postinstall


> node-sass@3.4.2 postinstall C:\Documents and Settings\mdi\Application Data\npm
\node_modules\ionic\node_modules\ionic-app-lib\node_modules\node-sass
> node scripts/build.js

` C:\Documents and Settings\mdi\Application Data\npm\node_modules\ionic\node_mod
ules\ionic-app-lib\node_modules\node-sass\vendor\win32-ia32-47\binding.node ` ex
ists.
 testing binary.
npm WARN install:node-sass@3.4.2 node-sass@3.4.2 postinstall: `node scripts/buil
d.js`
npm WARN install:node-sass@3.4.2 Exit status 3221225477
C:\Documents and Settings\mdi\Application Data\npm
└── (empty)

npm ERR! code 1

C:\Program Files\nodejs>

**Comment by kumar269** [comment]
i am also facing this problem can u find any solution for this problem,and 
![error](https://cloud.githubusercontent.com/assets/6340047/12073660/dadc33be-b14f-11e5-9ad5-5da93e5066e7.JPG)
module.js 340 throw error
