### ISSUE TITLE
missing devDependencies of local dependencies 

### ISSUE THREAD

**Issue by jbach** [npm/npm#10545]
Neither npm@2 nor npm@3 install `devDependencies` of local dependencies (`"localModule": "file:./localModule"`).

**package.json**
```json
{
  "name": "parentModule",
  "version": "1.0.0",
  "dependencies": {
  	"localModule": "file:./localModule"
  }
}
```

**localModule/package.json**
```json
{
  "name": "localModule",
  "version": "1.0.0",
  "dependencies": {
  	"wrappy": "^1.0.1"
  },
  "devDependencies": {
  	"ncp": "^2.0.0"
  }
}
```

**Result**
Only `wrappy` is installed to `node_modules`. 

Is this intended behaviour?

**Comment by watilde** [comment]
In devDependencies description:
https://docs.npmjs.com/files/package.json#devdependencies
> they probably don't want or need to download and build the external test or documentation framework that you use.

I think that's intended behaviour. You could put the `ncp` to devDependencies on your parent package.json(not localModule) if you'd like to use only for development.

Thanks.

**Comment by jbach** [comment]
I guess you are right, local dependencies are therefore treated like remote dependencies.
