### ISSUE TITLE
ERR! on any npm install command

### ISSUE THREAD

**Issue by a-farhat** [npm/npm#10542]
![image](https://cloud.githubusercontent.com/assets/5553585/11373819/d0e4a980-92a1-11e5-8c07-dc6d0715e6ad.png)

**Comment by KRob21** [comment]
I am having the same issue  

![screen shot 2015-11-24 at 17 12 34](https://cloud.githubusercontent.com/assets/4922725/11385536/9968318e-92ce-11e5-952c-ffe0d86377c0.jpg)

**Comment by watilde** [comment]
These seems install failures. Could you try update npm by the following command?
https://github.com/npm/npm#fancy-install-unix
```
$ curl -L https://www.npmjs.com/install.sh | sh
```

after that, you can also specify a version to install if you need to use specific version.
```
$ npm install -g npm@2.14.7
```

Thanks.

**Comment by KenanY** [comment]
@a-farhat Are you still experiencing this issue after reinstalling `npm`?

**Comment by KenanY** [comment]
Closing as abandoned.
