### ISSUE TITLE
404 error for gulp-selenium

### ISSUE THREAD

**Issue by bbideep** [npm/npm#10554]
I am seeing 404 error when downloading gulp-selenium. But, I can see the json response with 0.0.3 version on the registry.

Here are the commands that I am trying to execute:

npm -v
node -v
npm cache clean
npm set registry https://registry.npmjs.org/
npm install
npm install grunt
npm install rimraf

Error log:

1710 http 404 https://registry.npmjs.org/gulp-selenium
1711 verbose headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
1711 verbose headers   etag: '"C4S6JND9076OYEKVCMG0WXYYW"',
1711 verbose headers   'content-type': 'application/json',
1711 verbose headers   'cache-control': 'max-age=0',
1711 verbose headers   'content-length': '495',
1711 verbose headers   'accept-ranges': 'bytes',
1711 verbose headers   date: 'Wed, 25 Nov 2015 18:13:27 GMT',
1711 verbose headers   via: '1.1 varnish',
1711 verbose headers   age: '0',
1711 verbose headers   connection: 'close',
1711 verbose headers   'x-served-by': 'cache-jfk1034-JFK',
1711 verbose headers   'x-cache': 'MISS',
1711 verbose headers   'x-cache-hits': '0',
1711 verbose headers   'x-timer': 'S1448475207.404703,VS0,VE92',
1711 verbose headers   vary: 'Accept' }

**Comment by williamscs** [comment]
It looks like it may have been pulled. If you type 'gulp-selenium' on npmjs.com it starts to come up in the auto-complete, but when you try and actually [navigate to the site](https://www.npmjs.com/npm/gulp-selenium), it comes up as 404.
![image](https://cloud.githubusercontent.com/assets/1476137/11427836/c3421c5a-942b-11e5-8c91-604de8c417cd.png)

**Comment by KenanY** [comment]
@bbideep Is this still an issue for you by any chance?

**Comment by KenanY** [comment]
Closing as abandoned.
