### ISSUE TITLE
npm ERR! git clone --template

### ISSUE THREAD

**Issue by stephen-ying** [npm/npm#10559]
react-native init HelloWorld
This will walk you through creating a new React Native project in /Users/yingxiaoyun/HelloWorld
Installing react-native package from npm...

npm ERR! git clone --template=/Users/yingxiaoyun/.npm/_git-remotes/_templates --mirror https://github.com/facebook/react.git /Users/yingxiaoyun/.npm/_git-remotes/git-https-github-com-facebook-react-git-b4e74e3-7ac9f0e64c0248b5a8c1d179336b39d8: Cloning into bare repository '/Users/yingxiaoyun/.npm/_git-remotes/git-https-github-com-facebook-react-git-b4e74e3-7ac9f0e64c0248b5a8c1d179336b39d8'...
npm ERR! git clone --template=/Users/yingxiaoyun/.npm/_git-remotes/_templates --mirror https://github.com/facebook/react.git /Users/yingxiaoyun/.npm/_git-remotes/git-https-github-com-facebook-react-git-b4e74e3-7ac9f0e64c0248b5a8c1d179336b39d8: error: RPC failed; result=56, HTTP code = 200
npm ERR! git clone --template=/Users/yingxiaoyun/.npm/_git-remotes/_templates --mirror https://github.com/facebook/react.git /Users/yingxiaoyun/.npm/_git-remotes/git-https-github-com-facebook-react-git-b4e74e3-7ac9f0e64c0248b5a8c1d179336b39d8: fatal: The remote end hung up unexpectedly
npm ERR! git clone --template=/Users/yingxiaoyun/.npm/_git-remotes/_templates --mirror https://github.com/facebook/react.git /Users/yingxiaoyun/.npm/_git-remotes/git-https-github-com-facebook-react-git-b4e74e3-7ac9f0e64c0248b5a8c1d179336b39d8: fatal: early EOF
npm ERR! git clone --template=/Users/yingxiaoyun/.npm/_git-remotes/_templates --mirror https://github.com/facebook/react.git /Users/yingxiaoyun/.npm/_git-remotes/git-https-github-com-facebook-react-git-b4e74e3-7ac9f0e64c0248b5a8c1d179336b39d8: fatal: index-pack failed
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/Cellar/node/5.1.0/bin/node" "/usr/local/bin/npm" "install" "--save" "react-native"
npm ERR! node v5.1.0
npm ERR! npm  v3.3.12
npm ERR! code 128

npm ERR! Command failed: git clone --template=/Users/yingxiaoyun/.npm/_git-remotes/_templates --mirror https://github.com/facebook/react.git /Users/yingxiaoyun/.npm/_git-remotes/git-https-github-com-facebook-react-git-b4e74e3-7ac9f0e64c0248b5a8c1d179336b39d8
npm ERR! Cloning into bare repository '/Users/yingxiaoyun/.npm/_git-remotes/git-https-github-com-facebook-react-git-b4e74e3-7ac9f0e64c0248b5a8c1d179336b39d8'...
npm ERR! error: RPC failed; result=56, HTTP code = 200
npm ERR! fatal: The remote end hung up unexpectedly
npm ERR! fatal: early EOF
npm ERR! fatal: index-pack failed
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/yingxiaoyun/HelloWorld/npm-debug.log

`npm install --save react-native` failed

**Comment by OmgImAlexis** [comment]
Please wrap your log output like [this](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks).

**Comment by KenanY** [comment]
I'm gonna close this in favor of https://github.com/npm/npm/issues/10560, which is the same issue by the same user but it contains the full error log.
