### ISSUE TITLE
npm ERR! Error: Cannot find module 'npm-autoinit/autoinit' (Windows 7)

### ISSUE THREAD

**Issue by ababba15** [npm/npm#10557]
Few hour were spent to find decision, no success.

[npm-debug.txt](https://github.com/npm/npm/files/44597/npm-debug.txt)
Here is the debug file.

[log.txt](https://github.com/npm/npm/files/44598/log.txt)
Also log comes here.

And maybe screenshot will be useful.
What should I do to make my node.js work propertly on Windows 7?
![image](https://cloud.githubusercontent.com/assets/13153161/11414637/6fc820d6-9400-11e5-968e-509da6d305d6.png)

Thanks in advance =)

**Comment by KenanY** [comment]
@ababba15 Please try [updating `npm`](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows) first.

**Comment by ababba15** [comment]
@KenanY I tried but still have no result..

**Comment by stod0021** [comment]
npm config delete onload-script npm-autoinit/autoinit
This worked out for me.

**Comment by juank52009** [comment]
Hi everyone...

I had the same problem... For solving, you need to download the latest version of NPM (I have Windows X64).

In the following FTP Site you Should to search a file like: "npm-1.4.9.zip". https://nodejs.org/download/release/npm/

For the next step is unzip the folder and replace the files in your System. Search the route: "C:\Program Files\nodejs" and "C:\Program Files\nodejs\node_modules"...

![image](https://cloud.githubusercontent.com/assets/18407942/14958474/9673bf16-1050-11e6-8b8a-7a7f7fe2f1ce.png)


For finishing, you need to open a Windows Console and confirm that npm was installed ok...

![image](https://cloud.githubusercontent.com/assets/18407942/14958421/5b3ae186-1050-11e6-9d05-45b96427067d.png)

**Comment by juank52009** [comment]
https://github.com/npm/npm/issues/11522#issuecomment-217491742

**Comment by netsrotr** [comment]
This issue still exists and @juank52009 solution did not solve it.
node -v: v8.9.3 (x64)
npm -v: 5.5.1 (is installed with node above).

npm -v command complete output:
`:\Users\Me>npm -v
npm WARN onload-script failed to require onload script npm-autoinit/autoinit
npm WARN onload-script Error: Cannot find module 'npm-autoinit/autoinit'
npm WARN onload-script     at Function.Module._resolveFilename (module.js:536:15)
npm WARN onload-script     at Function.Module._load (module.js:466:25)
npm WARN onload-script     at Module.require (module.js:579:17)
npm WARN onload-script     at require (internal/module.js:11:18)
npm WARN onload-script     at cb (C:\Program Files\nodejs\node_modules\npm\lib\npm.js:224:11)
npm WARN onload-script     at C:\Program Files\nodejs\node_modules\npm\lib\npm.js:355:16
npm WARN onload-script     at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:81:7
npm WARN onload-script     at Array.forEach (<anonymous>)
npm WARN onload-script     at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:80:13
npm WARN onload-script     at f (C:\Program Files\nodejs\node_modules\npm\node_modules\once\once.js:25:25)
npm WARN onload-script  { Error: Cannot find module 'npm-autoinit/autoinit'
npm WARN onload-script     at Function.Module._resolveFilename (module.js:536:15)
npm WARN onload-script     at Function.Module._load (module.js:466:25)
npm WARN onload-script     at Module.require (module.js:579:17)
npm WARN onload-script     at require (internal/module.js:11:18)
npm WARN onload-script     at cb (C:\Program Files\nodejs\node_modules\npm\lib\npm.js:224:11)
npm WARN onload-script     at C:\Program Files\nodejs\node_modules\npm\lib\npm.js:355:16
npm WARN onload-script     at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:81:7
npm WARN onload-script     at Array.forEach (<anonymous>)
npm WARN onload-script     at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:80:13
npm WARN onload-script     at f (C:\Program Files\nodejs\node_modules\npm\node_modules\once\once.js:25:25)
npm WARN onload-script   stack: 'Error: Cannot find module \'npm-autoinit/autoinit\'\n    at Function.Module._resolveFilename (module.js:536:15)\n    at Function.Module._load (module.js:466:25)\n    at Module.require (module.js:579:17)\n
 at require (internal/module.js:11:18)\n    at cb (C:\\Program Files\\nodejs\\node_modules\\npm\\lib\\npm.js:224:11)\n    at C:\\Program Files\\nodejs\\node_modules\\npm\\lib\\npm.js:355:16\n    at C:\\Program Files\\nodejs\\node_modules\\npm\\lib\\config\\core.js:81:7\n    at Array.forEach (<anonymous>)\n    at C:\\Program Files\\nodejs\\node_modules\\npm\\lib\\config\\core.js:80:13\n    at f (C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\once\\once.js:25:25)',
npm WARN onload-script   code: 'MODULE_NOT_FOUND' }
5.5.1`
