### ISSUE TITLE
sudo npm install -g meanio@latest fails

### ISSUE THREAD

**Issue by kthomas80** [npm/npm#10553]
I set up a new ubuntu vm and ran through the settings. I even tried to:

sudo chown -R $(whoami) .npm

Here is the error stack.

npm ERR! Error: Attempt to unlock ., which hasn't been locked
npm ERR!     at unlock (/usr/lib/node_modules/npm/lib/utils/locker.js:44:11)
npm ERR!     at cb (/usr/lib/node_modules/npm/lib/cache/add-local.js:30:5)
npm ERR!     at /usr/lib/node_modules/npm/lib/cache/add-local.js:47:20
npm ERR!     at /usr/lib/node_modules/npm/lib/utils/locker.js:30:7
npm ERR!     at cb (/usr/lib/node_modules/npm/node_modules/lockfile/lockfile.js:149:38)
npm ERR!     at /usr/lib/node_modules/npm/node_modules/lockfile/lockfile.js:177:38
npm ERR!     at Object.oncomplete (fs.js:108:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.11.0-15-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /usr/lib/node_modules/meanio/lib/core_modules/server
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /usr/lib/node_modules/meanio/lib/core_modules/server/npm-debug.log
npm ERR! not ok code 0

npm ERR! meanio@0.8.83 postinstall: `cd ./lib/core_modules/server && npm install && cd ../../..`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the meanio@0.8.83 postinstall script.
npm ERR! This is most likely a problem with the meanio package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd ./lib/core_modules/server && npm install && cd ../../..
npm ERR! You can get their info via:
npm ERR!     npm owner ls meanio
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.11.0-15-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "-g" "meanio@latest"
npm ERR! cwd /home/osboxes
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

**Comment by OmgImAlexis** [comment]
Please wrap your log output like [this](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks).

Looks like it's just a permission issue, have you tried the commands listed [here](https://stackoverflow.com/questions/22152162/npm-cannot-install-dependencies-attempt-to-unlock-something-which-hasnt-been)?

**Comment by KenanY** [comment]
@kthomas80 Are you still seeing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
