### ISSUE TITLE
npm error Windows_NT 6.1.7601

### ISSUE THREAD

**Issue by wanqiaoyufu** [npm/npm#10552]
npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "install" "-g" "ionic"
npm ERR! node v5.1.0
npm ERR! npm  v3.5.0
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read

**Comment by ashleygwilliams** [comment]
hi! i just reproduced this error on my Windows 10 machine as well. 

`ECONNRESET`usually refers to a connection error (such as bad/slow wifi, etc.) so i'm not exactly sure what is going on here.

i *can* install express. could you confirm that you can as well? `npm install express`
i think this may be specific to ionic

**Comment by ashleygwilliams** [comment]
also this issue seems to be helping people with the same problem: https://github.com/npm/npm/issues/10197#issuecomment-152747078

**Comment by wanqiaoyufu** [comment]
@ashleygwilliams Thank you very much for your answer.when i npm install -g ionic,it error that at the end:
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ionic"
npm ERR! node v5.1.0
npm ERR! npm  v3.5.0
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.4.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.4.2 postinstall script 'node scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Administrator\npm-debug.log
npm ERR! code 1

**Comment by tpanhorst** [comment]
This happens to me as well @wanqiaoyufu .  Were you able to resolve it?

**Comment by wanqiaoyufu** [comment]
@tpanhorst Have you solved it?

**Comment by wanqiaoyufu** [comment]
@tpanhorst I solved the problem, because I am in China, so they need over the wall

**Comment by nelsonBlack** [comment]
make sure you are not running another instance of "ionic serve", i.e no other ionic app is running
