### ISSUE TITLE
Refusing to install testnpmrepo as a dependency of itself

### ISSUE THREAD

**Issue by anilprabhu04** [npm/npm#10564]
When I try to create a package.json in node js I am getting this error "Refusing to install testnpmrepo as a dependency of itself"
The package details is 
{
  "name": "testnpmrepo",
  "version": "1.0.0",
  "description": "test",
  "main": "index.js",
  "dependencies": {
    "npm": "^3.3.12"
  },
  "devDependencies": {},
  "scripts": {
    "test": "test"
  },
  "repository": {
    "type": "git",
    "url": "(\"https://github.com/anilprabhu04/npmrepo\")"
  },
  "keywords": [
    "npm"
  ],
  "author": "anil",
  "license": "ISC"
}

**Comment by KenanY** [comment]
@anilprabhu04 Could you expand on how I would go about reproducing this? I do not understand how simply creating a file could cause `npm` to throw such an error, so I do not think you have provided all the necessary details.

**Comment by KenanY** [comment]
@anilprabhu04 Are you still experiencing this issue?
