### ISSUE TITLE
Bower Issues

### ISSUE THREAD

**Issue by Adedeji92** [npm/npm#10568]
Please Help me with this, how can i correct this as soon as possible
![capture](https://cloud.githubusercontent.com/assets/8332170/11424969/b52ae6e4-9451-11e5-863a-a41719b41639.PNG)

**Comment by KenanY** [comment]
@Adedeji92 Have you tried running `npm cache clean`?

**Comment by Adedeji92** [comment]
Have tried that

Sent from my BlackBerry® smartphone, powered by Easyblaze

-----Original Message-----

**Comment by KenanY** [comment]
@Adedeji92 Sorry I haven't provided any other solutions. Are you still having this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
