### ISSUE TITLE
while giving command "npm install" getting following error..

### ISSUE THREAD

**Issue by giovannidv** [npm/npm#10569]
…
npm http 304 https://registry.npmjs.org/time-grunt
npm ERR! Error: No compatible version found: time-grunt@'^1.2.1'
npm ERR! Valid install targets:
npm ERR! ["0.1.0","0.1.1","0.1.2","0.2.0","0.2.1","0.2.2","0.2.3","0.2.4","0.2.5","0.2.6","0.2.7","0.2.8","0.2.9","0.2.10","0.3.1","0.3.2","0.4.0","1.0.0","1.1.0","1.1.1","1.2.0","1.2.1","1.2.2"]
npm ERR!     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:682:10)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:597:10
npm ERR!     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:297:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 11.4.2
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/giovannidionsi-vici/Desktop/Download_Librerie/bootstrap-3.3.6
npm ERR! node -v v0.8.22
npm ERR! npm -v 1.2.14
npm http 304 https://registry.npmjs.org/grunt-contrib-cssmin
npm http 304 https://registry.npmjs.org/npm-shrinkwrap
npm http 304 https://registry.npmjs.org/markdown-it
npm http 304 https://registry.npmjs.org/grunt-contrib-connect
npm http 304 https://registry.npmjs.org/grunt-saucelabs
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/giovannidionsi-vici/Desktop/Download_Librerie/bootstrap-3.3.6/npm-debug.log
npm ERR! not ok code 0
…
Bootstrap source code installation troubleshooting
Should you encounter problems with installing dependencies or running Grunt commands, first delete the /node_modules/ directory generated by npm. Then, rerun npm install.
…
but the error continuing

**Comment by KenanY** [comment]
@giovannidv Please [upgrade `npm`](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm).

**Comment by giovannidv** [comment]
Thanks for the advice, now works. Giovanni----- Original Message ----- From: Kenan Yildirim [mailto:Kenan Yildirim] To: npm@noreply.github.com Cc: admin@giovannidionisivici.com Sent: Thu, 26 Nov 2015 09:25:38 -0800 Subject: 
@giovannidv Please upgrade npm.

**Comment by KenanY** [comment]
Closing as resolved.
