### ISSUE TITLE
Installing shrinkwrap hangs forever on "cloneCurrentTree → networ"

### ISSUE THREAD

**Issue by AgentME** [npm/npm#10579]
I have a specific project that uses a shrinkwrap which npm gets stuck on. However, if I delete the shrinkwrap, it installs fine (not the exact versions obviously). I thought the issue might have to do with the shrinkwrap being generated on a different computer, but If I generate a new shrinkwrap after successfully installing from just package.json, delete the node_modules directory, and try to install using the shrinkwrap (of the setup that just worked moments before), then npm gets stuck again.

It gets stuck like this. There's a spinner to the right of "networ" that's still spinning, but once it's stuck it never changes its rate and the progress bar never moves and the text never changes.
```
cloneCurrentTree → networ ▄ ╢███████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
```

Here's the [package.json](https://gist.github.com/AgentME/61f33277e2982a905e85), and here's the [npm-shrinkwrap.json](https://gist.github.com/AgentME/e46b89fc0b600d4b09a2) (though you can generate your own and probably see the issue just the same).

I've had this issue on a computer with npm 3.5.0 on Ubuntu 15.10, and another computer with npm 3.4.0 on Ubuntu 15.04.

**Comment by AgentME** [comment]
I can't reproduce this now. Maybe my internet or the npm repos were having an issue with a specific dependency downloading?

**Comment by AgentME** [comment]
No, I can reproduce it again. I think I just got lucky in having it work earlier. When it worked, it finished in much less than a minute, but right now I've had it spinning for 10 minutes.  Maybe there's some race condition.

**Comment by AgentME** [comment]
Make it "spinning on this step for 6 hours" now. Even if it were a network issue, it should have cleanly timed out by now. (And I've already installed these packages before, so shouldn't they all be cached in `~/.npm`?)

**Comment by piotrpalek** [comment]
@AgentME I have a similiar issue.. did you resolve this anyhow?

**Comment by wangcheng714** [comment]
same question， how to fix it ？

**Comment by wangcheng714** [comment]
@AgentME @piotrpalek   i have same question，did you resolve this ?

**Comment by piotrpalek** [comment]
@wangcheng714 No, it seems I just had a bad day with npm, the next they everything worked again 
¯\_(ツ)_/¯

**Comment by mateusfccp** [comment]
I had this same issue when trying to install Ghost blogging platform. I solved this by deleting *npm-shrinkwrap.json*.

**Comment by mapreal19** [comment]
@mateusfccp deleting `npm-shrinkwrap.json` worked for me too

**Comment by villesau** [comment]
i have the same problem

```
npm verb tar unpacking to /var/folders/vb/971x9tmd35jg98kfzlq4kmqm0000gn/T/npm-13106-4842de6f/unpack-b7509951
npm verb gentlyRm don't care about contents; nuking /var/folders/vb/971x9tmd35jg98kfzlq4kmqm0000gn/T/npm-13106-4842de6f/unpack-b7509951
npm verb afterAdd /Users/villesaukkonen/.npm/negotiator/0.5.3/package/package.json not in flight; writing
npm verb afterAdd /Users/me/.npm/negotiator/0.5.3/package/package.json written
cloneCurrentTree -> netwo / |###################-------------------------------------------------------------------------------------------|

```

the install does not basically proceed from that step. i'm installing node modules from scratch after rm -rf node_modules

**Comment by kahboom** [comment]
In my case, the shrinkwrap was outdated and npm didn't handle the error. For those of you that need to keep your `npm-shrinkwrap.json` file for production (like I did), just rewrite it with `$ npm shrinkwrap` and don't forget to commit it.

**Comment by kahboom** [comment]
@AgentME - Btw, I know that wasn't your specific case, but I ran into a bunch of other people with the same problem and they had different causes/fixes. A few things I picked up:

- Using `$ npm install -dd` can also be helpful for additional logging. i.e. one person was getting a symlink error they couldn't see without this.
- Are you installing behind a VPN? Try deleting ~/.npm, ~/.npmrc, node_modules, etc. (actually do that *each time* before any of these tests) and reinstalling while disconnected from the VPN.
- Try setting the following before running `$ npm install`:
  - `$ npm config set registry http://registry.npmjs.org/`
  - `$ npm config set strict-ssl false`
- Try running with `--debug` enabled. i.e. `$ npm install --debug`
- Other things that could be the cause: OS (maybe test with CentOS if running Debian or Ubuntu), Docker containers, method used to install Node + NPM (mostly applies to OS X users using Homebrew to install both)

**Comment by lucke84** [comment]
Thanks @kahboom your comments helped me a lot!

**Comment by mjtko** [comment]
Using HTTP rather than HTTPS (via the `npm config set registry http://registry.npmjs.org/` mentioned by @kahboom) got it working for me!  Very odd - it was working earlier, then stopped; must be some very odd bug in the HTTPS stack somewhere.

Anyway, many thanks, I was close to putting my fist through the screen! :grin:

**Comment by mjtko** [comment]
Further to this, after a further run through, it seems I also needed to update NPM to the latest release (3.8.2 worked for me).

I now also have `strict-ssl` set `false` for good measure, because I've lost long enough to this problem now. :-(

HTH others with similar problems.

**Comment by J-Katzen** [comment]
+1 - My build is also hanging with npm-shrinkwrap.json file included.  Deleting it fixes it, but we need it for production.

**Comment by arsnl** [comment]
Still have the same problem here when we use the `npm-shrinkwrap.json` file. Remove `https` and setting strict-ssl to false doesnt work on our case and we still stuck at `cloneCurrentTree -> netwo`

**Comment by herby** [comment]
Same for me, happened after upgrade Win 7 -> Win 10. @kahboom advices did not help. Using `--registry https://registry.nodejitsu.com` helped, though. From what I saw, main registry has, sometimes, bad mood, and is not giving 304 replies immediately, but after long, long time.

**Comment by herby** [comment]
Same here. nothing helps. Happened after upgrade from Win7 to Win10. Reinstalled node as well as git for windows, switched off firewall, ... nothing. Still hangs.

**Comment by jkhustler** [comment]
What version of node you guys running? I was having this problem on node v5.x.x but when I upgraded to v6.x.x I was able to install perfectly fine with a new `shrinkwrap.json` that I generated. I made sure, by blowing away my node_modules multiple times and reinstalling again.

**Comment by herby** [comment]
Another day it went fine. So npm registries are just a bit moody (or there is some nasty bug that changes behaviour based on time and day; there are those kind of bugs, for example when timezones are taken into account and negative/positive is screwed, I remember I saw one such bug in a code I inherited in a project).

**Comment by AgentME** [comment]
Tried using the computer I had this problem on again. I was still running into it, but then updating from node v5.6.0 to node v6.2.1 has fixed it.

**Comment by hwfwalton** [comment]
Had the same issues with node v5.8.0. Updating to v6.2.2 fixed it for me.

**Comment by wolfgang42** [comment]
I had this same issue on Ubuntu Xenial, npm@3.5.2 nodejs@4.2.6. Deleting the npm-shrinkwrap file made the problem go away, and I could recreate a new shrinkwrap afterwards and it would still work. I have the old and new shrinkwrap files and can try delta-debugging them to identify the section that had the error.

**Comment by AgentME** [comment]
I'm going to close this because it seemed like in my case and some others' that it had to do with node <6's ssl support. If anyone else is still running into this, you might want to open a new issue.
