### ISSUE TITLE
NPM engines check

### ISSUE THREAD

**Issue by nicbell** [npm/npm#10572]
This is a feature request not a bug. 
There are a lot of polyglot modules on NPM that fail if you don't have a depend language installed (usually Ruby or Python). Often these types of failures are obscure.

Would it be a good idea to specify these languages in the `package.json` under engines.

``` json
{
 "engines": {
    "node": ">=4.0.0",
    "ruby": "^2.2.0"
  }
}
```

Then have NPM check for these languages on path and provide the user with proper feedback.

**Comment by mrmartineau** [comment]
:+1:

**Comment by busches** [comment]
@othiym23 is this something `npm` would consider adding in the future with a PR?
