### ISSUE TITLE
npm , node js

### ISSUE THREAD

**Issue by honeyjn15** [npm/npm#10576]
![error](https://cloud.githubusercontent.com/assets/4899817/11435771/182acb44-9504-11e5-92e0-b7dfb71a9e66.png)

// I'm getting an error when i'm installing a node . i've reinstalled node but still getting a error
Kindly Please help !!...

**Comment by OmgImAlexis** [comment]
Please replace the image with the output of cmd and provide the log file as it explains in the error.

**Comment by honeyjn15** [comment]
@OmgImAlexis : Thanks for reply!  i have resolved the error . I have a doubt if i update a nodeto latest version through cmd prompt then will it create any problem in my previous or ongoing project .

**Comment by KenanY** [comment]
Closing as resolved then.
