### ISSUE TITLE
error on 'npm install -g generator-aspnet'

### ISSUE THREAD

**Issue by KantJoe** [npm/npm#10573]
npm WARN deprecated lodash@2.4.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0.
/usr/local/lib
└── generator-aspnet@0.0.91

then i tried 'npm install lodash' failed tips:no this pkg or file or folder
change to bower:'bower install lodash',tips:success and 
use 'npm ls'
shows another loadash@3.0.1 bellow grunt-cli,in the folder of grunt-cli still has a pkg loadash@2.4.1.
it seen update lodash failed .
then i tried 'sudo npm update -g grunt-cli' with no response.
help me please!!it seens 'npm update' is useless to every pkg.

**Comment by skmezanul** [comment]
I also had the same issue when installing a few npm packages. I started digging and found the homepage of [lodash](https://lodash.com/)

I used the following command:
`npm install -g lodash`

That solved the issue for me.

**Comment by iqbalmalik89** [comment]
@skmezanul Thanks. It solved my problem.

**Comment by skutondo** [comment]
@skmezanul Thank you, this resolved my issue as well.

**Comment by KantJoe** [comment]
@skmezanul "npm install -g lodash" or "sudo npm install -g lodash" can not solve this issue for me ...is that my npm occure some problems?

**Comment by skmezanul** [comment]
@KantJoe You can try the following commands as shown on its [website](https://lodash.com/):
`$ {sudo -H} npm i -g npm`
`$ npm i --save lodash`

**Comment by KeeganAriel** [comment]
thanks! this fixed it for me too!

**Comment by KantJoe** [comment]
@skmezanul thank u even though that deprecate message still exists,and i realize it most relation to software dependency libraries and it's not blocking my installation, it's simply warning msg only.

**Comment by dirface** [comment]
@skmezanul thanks!
