### ISSUE TITLE
Pass environment variables to lifecycle scripts in a cross-platform compatible manner

### ISSUE THREAD

**Issue by dukedougal** [npm/npm#10575]
Many npm packages don't run on Windows because they contain commands that are prefixed with environment variables.  Unfortunately this approach is not cross platform, so those commands fail on Windows.

The only practical solution I can think of for this is that npm detects when environment variables are being set and transforms the set command such that it is compatible with the operating system environment that it is running on.

Here's an example of the problem:

```json
"scripts": {
    "test": "NODE_ENV=test mocha --compilers js:babel/register --recursive --require ./test/setup.js $(find test -name '*.spec.js')",
    "test-watch": "npm test -- --watch",
    "test-e2e:crdv": "chromedriver",
    "test-e2e": "NODE_ENV=test mocha --compilers js:babel/register --require ./test/setup.js --require co-mocha ./test/e2e.js",
    "lint": "eslint .",
    "hot-server": "node server.js",
    "build": "NODE_ENV=production webpack --config webpack.config.production.js --progress --profile --colors",
    "start": "electron .",
    "start-hot": "HOT=1 NODE_ENV=development electron .",
    "package": "NODE_ENV=production node package.js",
    "package-all": "npm run package -- --all"
  }
```

**Comment by sheerun** [comment]
I've searched like whole Internet for an answer how to set env variables in cross-platform way, and currently probably the only sensible way is to use https://github.com/ForbesLindesay/win-spawn

BUT it won't work for example for preinstall scripts, because win-spawn is not loaded yet

**Comment by sheerun** [comment]
Actually never mind, win-spawn is not cross-platform: https://github.com/ForbesLindesay/win-spawn/issues/13

**Comment by sheerun** [comment]
So there's another solution I've found: http://npm.im/cross-env

**Comment by dukedougal** [comment]
@sheerun somehow this needs to be built in to npm.  npm is basically broken wherever it needs to be used across platforms because of environment variables.

**Comment by sheerun** [comment]
I agree

**Comment by dukedougal** [comment]
One of the key problems is that IMO developers tend to package for their primary development environment and aren't interested or don't have the resources to work out the correct way to implement cross platforms environment variables.  So Linux folks for example will implement with Linux environment variables but won't be bothered working out how to do it for Windows.  They probably shouldn't need to either.  Ideally the tool could be given the name of the environment variable and the value to set it to and the platform specific npm implementation should know how to set that variable.  There will be a less than optimal outcome where it is left to the developers to work out how to properly set environment variables across all platforms including platforms that possibly they can't test on.

**Comment by iarna** [comment]
I would love to see something that evaluates lifecycle strings with a subset of `sh`, and is cross-platform compatible. I would love to _write_ this myself. But I don't see our team having the resources to spend on it any time in the next year, as such I'm going to close this. If someone were to give a go at this, we would be very interested in a PR, however.
