### ISSUE TITLE
nam init failed with nodes 5.1.0 and nam 3.3.12 in Mac

### ISSUE THREAD

**Issue by arthurlee** [npm/npm#10589]
/Users/arthur/study/nodejs/generator-example> npm init
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "init"
npm ERR! node v5.1.0
npm ERR! npm  v3.3.12
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'github-url-from-git'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/arthur/study/nodejs/generator-example/npm-debug.log

[npm-debug.log.txt](https://github.com/npm/npm/files/46255/npm-debug.log.txt)

**Comment by arthurlee** [comment]
node v4.2.2 is ok

**Comment by arthurlee** [comment]
I find that the path /usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules includes module normalize-package-data which is not used in node 5.x, so I just delete it and everything is ok. Thanks.

**Comment by mindcat** [comment]
@arthurlee Thanks, I follow your instruction, I fixed the problem, same happened on me.
