### ISSUE TITLE
Please help me

### ISSUE THREAD

**Issue by Adedeji92** [npm/npm#10583]
Please help me on how to correct this error
![capture](https://cloud.githubusercontent.com/assets/8332170/11442940/978087a2-9519-11e5-89c1-94a7b72a8a49.PNG)

**Comment by XGHeaven** [comment]
please run
```
npm install async --save
```

you can post this question to stackoverflow, not here

**Comment by KenanY** [comment]
@Adedeji92 Are you still seeing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
