### ISSUE TITLE
When installing express generator on Windows 7 get this error - error:0906D06C:PEM routines:PEM_read_bio:no start line

### ISSUE THREAD

**Issue by shamtab** [npm/npm#10588]
C:\Node>npm install express-generator -g
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\
node_modules\npm\bin\npm-cli.js" "install" "express-generator" "-g"
npm ERR! node v5.1.0
npm ERR! npm  v3.3.12

npm ERR! error:0906D06C:PEM routines:PEM_read_bio:no start line
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

**Comment by StevenMcD** [comment]
Just a few questions:

1. Are you able to install any other npm packages or does this only happen with express-generator?
2. Are you working off a network with very strict proxy/firewall rules?

Could you try running this command with strict-ssl disabled and see if you still get an error?
`npm set strict-ssl false`

**Comment by shamtab** [comment]
Thanks for your inputs SteveMcD

1. yes i also tried install express and got the same error message.
2. i have two networks, initially when i was installing on a proxy enabled network, i got an error saying your proxy is enabled and you need to run command like, npm config set/get/delete/list, which i did,

i used the command - npm config set value

and tried to install and i start to get this error message.
C:\Node>npm install express-generator -g
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\
node_modules\npm\bin\npm-cli.js" "install" "express-generator" "-g"
npm ERR! node v5.1.0
npm ERR! npm v3.3.12

npm ERR! error:0906D06C:PEM routines:PEM_read_bio:no start line
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR! https://github.com/npm/npm/issues

3. i tried using the command you gave - npm set strict-ssl false

and still get the same error.

Please let me know. i even uninstalled node.js and reinstalled it again and still getting this error when installing npm express-generator.

Thanks.

**Comment by StevenMcD** [comment]
Did you have NPM working before this happened? Maybe their is an NPM cache folder someone that needs to be removed and rebuilt.

**Comment by shamtab** [comment]
C:\Node>npm install --verbose
npm info it worked if it ends with ok
npm verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'install',
npm verb cli   '--verbose' ]
npm info using npm@3.3.12
npm info using node@v5.1.0
npm verb lock using C:\Users\stabrez\AppData\Roaming\npm-cache\_locks\staging-54
3c97476c0c1861.lock for C:\Node\node_modules\.staging
npm verb unlock done using C:\Users\stabrez\AppData\Roaming\npm-cache\_locks\sta
ging-543c97476c0c1861.lock for C:\Node\node_modules\.staging
npm info lifecycle test@1.0.0~preinstall: test@1.0.0
npm info linkStuff test@1.0.0
npm verb linkBins test@1.0.0
npm verb linkMans test@1.0.0
npm info lifecycle test@1.0.0~install: test@1.0.0
npm info lifecycle test@1.0.0~postinstall: test@1.0.0
npm info lifecycle test@1.0.0~prepublish: test@1.0.0
npm WARN EPACKAGEJSON test@1.0.0 No repository field.
npm verb exit [ 0, true ]
npm info ok

**Comment by StevenMcD** [comment]
Apologies, what I meant was running the following:

`npm install express-generator -g`

**Comment by shamtab** [comment]
no problem Steve, appreciate your help. 
still the same error message:

C:\Node>npm install express-generator -g
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\
node_modules\npm\bin\npm-cli.js" "install" "express-generator" "-g"
npm ERR! node v5.1.0
npm ERR! npm v3.3.12

npm ERR! error:0906D06C:PEM routines:PEM_read_bio:no start line
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR! https://github.com/npm/npm/issues

**Comment by StevenMcD** [comment]
hehe, I think my edit wasn't quick enough. You need to add the `--verbose` to the end of the install statement for the logging.

Try `npm install express-generator -g --verbose` that should give us an idea of where the install is getting blocked.

**Comment by shamtab** [comment]
C:\Node>npm install express-generator -g --verbose
npm info it worked if it ends with ok
npm verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'install',
npm verb cli   'express-generator',
npm verb cli   '-g',
npm verb cli   '--verbose' ]
npm info using npm@3.3.12
npm info using node@v5.1.0
npm verb request uri https://registry.npmjs.org/express-generator
npm verb request no auth needed
npm info attempt registry request try #1 at 4:11:55 PM
npm verb request id 9ceb574c7698a514
npm http request GET https://registry.npmjs.org/express-generator
npm verb stack Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
npm verb stack     at Error (native)
npm verb stack     at Object.createSecureContext (_tls_common.js:87:19)
npm verb stack     at Object.exports.connect (_tls_wrap.js:999:21)
npm verb stack     at Agent.createConnection (https.js:80:22)
npm verb stack     at Agent.createSocket (_http_agent.js:174:16)
npm verb stack     at Agent.addRequest (_http_agent.js:143:23)
npm verb stack     at new ClientRequest (_http_client.js:139:16)
npm verb stack     at Object.exports.request (http.js:31:10)
npm verb stack     at Object.exports.request (https.js:173:15)
npm verb stack     at Request.start (C:\Program Files\nodejs\node_modules\npm\no
de_modules\request\request.js:793:30)
npm verb cwd C:\Node
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "express-generator" "-g" "--verbos
e"
npm ERR! node v5.1.0
npm ERR! npm  v3.3.12

npm ERR! error:0906D06C:PEM routines:PEM_read_bio:no start line
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm verb exit [ 1, true ]

**Comment by StevenMcD** [comment]
I'm now out of my depth, sorry :cry: 

maybe check out this thread since it seems similar, maybe you're running into the same problem. Sorry that I could not be of more help: https://github.com/npm/npm/issues/7672

**Comment by rathisoft** [comment]
Even I am also facing such issue and looking for a solution

**Comment by legodude17** [comment]
This is a known `node` issue, please update your node version.

**Comment by rkumar2667** [comment]
@legodude17  I am facing the same problem even with the latest node version 7.4.0. 

Someone please help out ..

**Comment by legodude17** [comment]
There was another issue in here where @othiym23 says that the problem is with your `npm.ca` and `npm.key` or something... What is the result of `npm config ls`?
