### ISSUE TITLE
Bash completion for globally installed executables

### ISSUE THREAD

**Issue by someone-unknown** [npm/npm#10587]
I think it would be very useful if NPM allows to attach to a package an autocompletion script and places it to _**/etc/bash_completion.d/$EXECUTABLE**_ or _**/usr/share/bash-completion/completions/$EXECUTABLE**_ path after succesful installation.

**Comment by zkat** [comment]
We consider this out of scope for the npm project itself. Something like this is something that could be provided by a 3rd party package which can then be run to install such scripts.

**Comment by someone-unknown** [comment]
Okay. Thank you!
