### ISSUE TITLE
prepatch does not bump pre version?

### ISSUE THREAD

**Issue by jasonkuhrt** [npm/npm#10585]
I had my application at version `1.0.6-0` after running `npm version prepatch`. I fixed something and went to release another prerelease using again `npm version prepatch` but the result was a version of `1.0.7-0` but I expected `1.0.6-1`. Is this a bug with `npm`?

**Comment by KenanY** [comment]
@jasonkuhrt But, bumping `prepatch` should bump the `patch` bit of the version, right? That's my understanding after reading the [`node-semver docs](https://github.com/npm/node-semver).

``` sh
$ semver -i prepatch 1.0.6-0
1.0.7-0
```

I think you might want to bump `prerelease`:

``` bash
$ semver -i prerelease 1.0.6-0
1.0.6-1
```

**Comment by jasonkuhrt** [comment]
@KenanY Ah thank-you! Yes.

**Comment by ViggoV** [comment]
That would be very helpful to have a note on in the docs.
