### ISSUE TITLE
Cannot set property 'fs-extra' of undefind

### ISSUE THREAD

**Issue by d7p** [npm/npm#10592]
HI

After updating to npm 3 then seem to be unable to install packages. I receive the following error:
```
npm ERR! Darwin 14.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "lodash"
npm ERR! node v4.2.1
npm ERR! npm  v3.5.0

npm ERR! Cannot set property 'fs-extra' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```
[npm-debug.log.txt](https://github.com/npm/npm/files/46436/npm-debug.log.txt)
 I changed the file ending so git would allow me to attach it and changed my username.

**Comment by othiym23** [comment]
Can you try uninstalling and reinstalling Node.js and npm? We had a bad version for a little bit there that caused npm to break itself on upgrade. `npm@latest` does not have that problem, nor do the versions of npm bundled with Node.js.

**Comment by d7p** [comment]
Thanks @othiym23 that worked for me.

For anyone with the same issue:
I uninstalled and maid sure to remove all files relating to node and npm and then reinstall node 4.2.3 LTS. Npm then worked fine. I also updated to 3.5.1.
