### ISSUE TITLE
npm install git+ssh://... --save

### ISSUE THREAD

**Issue by lc60005457** [npm/npm#10594]
When I use `npm install git+ssh://... --save`, the `package.json`

```
"dependencies": {
    "...": "ssh://...",
}
```

then, `npm install`, will error:

```
npm ERR! Unsupported URL Type: ssh://...
```

and, I need edit the `package.json`

```
"dependencies": {
    "...": "git+ssh://...",
}
```

**Comment by KenanY** [comment]
@lc60005457 Is this a duplicate of https://github.com/npm/npm/issues/9679?

**Comment by lc60005457** [comment]
@KenanY Yeah, it is. And I update npm to `v3.5.0` with mac. It also.

**Comment by KenanY** [comment]
@lc60005457 Could you close this issue in favor of https://github.com/npm/npm/issues/9679 then? This way we can keep the issue tracker just a little cleaner :)
