### ISSUE TITLE
npm install : npm err!Windows_NT 6.3..9600

### ISSUE THREAD

**Issue by karkranikhil** [npm/npm#10605]
![image](https://cloud.githubusercontent.com/assets/11937732/11459432/7a7ed5ac-96fc-11e5-8b68-b7474a3153b4.png)

**Comment by karkranikhil** [comment]
every time i am running npm install it showing the error shown in above image

**Comment by KenanY** [comment]
@karkranikhil Are you still experiencing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
