### ISSUE TITLE
npm install -g --save

### ISSUE THREAD

**Issue by bdageryd** [npm/npm#10608]
C:\Users\Birger>npm install -g --save
npm ERR! tar pack Error reading C:\Users\Birger
npm ERR! addLocalDirectory Could not pack C:\Users\Birger to C:\Users\Birger\AppData\Roaming\npm-cache\Birger\1.0.0\package.tgz
npm ERR! addLocal Could not install C:\Users\Birger
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "--save"
npm ERR! node v5.1.0
npm ERR! npm  v3.3.12
npm ERR! path C:\Users\Birger\AppData\Local\Comms\UnistoreDB\USS.log
npm ERR! code EBUSY
npm ERR! errno -4082
npm ERR! syscall open

npm ERR! EBUSY: resource busy or locked, open 'C:\Users\Birger\AppData\Local\Comms\UnistoreDB\USS.log'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Birger\npm-debug.log

[npm_debug_log.docx](https://github.com/npm/npm/files/46745/npm_debug_log.docx)

**Comment by ben-page** [comment]
You didn't include any information about what you are trying to do, so I can only guess at what you intended. Your command is not valid. Most likely you either need to specify the package you are trying to install or remove the -g argument. I suggest reading the docs to understand how to use NPM. https://docs.npmjs.com/

**Comment by KenanY** [comment]
@bdageryd Are you still experiencing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
