### ISSUE TITLE
error with npm trying to install cordova (ionic framework purpose)

### ISSUE THREAD

**Issue by avinoandrea** [npm/npm#10609]
that's my error log:

MacBook-Pro-di-Andrea-Avino:~ Andrea$ npm install -g cordova

npm http GET https://registry.npmjs.org/cordova

npm http 200 https://registry.npmjs.org/cordova

npm http GET https://registry.npmjs.org/cordova/-/cordova-5.4.1.tgz

npm http 200 https://registry.npmjs.org/cordova/-/cordova-5.4.1.tgz

npm http GET https://registry.npmjs.org/q/1.0.1

npm http GET https://registry.npmjs.org/nopt/3.0.1

npm http GET https://registry.npmjs.org/underscore/1.7.0

npm http GET https://registry.npmjs.org/cordova-lib/5.4.1

npm http GET https://registry.npmjs.org/update-notifier

npm http GET https://registry.npmjs.org/ansi

npm http 200 https://registry.npmjs.org/update-notifier

npm ERR! Error: No compatible version found: update-notifier@'^0.5.0'

npm ERR! Valid install targets:

npm ERR! ["0.1.0","0.1.1","0.1.2","0.1.3","0.1.4","0.1.5","0.1.6","0.1.7","0.1.8","0.1.9","0.1.10","0.2.0","0.2.1","0.2.2","0.3.0","0.3.1","0.3.2","0.4.0","0.5.0"]

npm ERR!     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:682:10)

npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:597:10

npm ERR!     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)

npm ERR!     at Object.oncomplete (fs.js:93:15)

npm ERR! If you need help, you may report this log at:

npm ERR!     <http://github.com/isaacs/npm/issues>

npm ERR! or email it to:

npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 15.0.0

npm ERR! command "node" "/usr/local/bin/npm" "install" "-g" "cordova"

npm ERR! cwd /Users/Andrea

npm ERR! node -v v0.10.0

npm ERR! npm -v 1.2.14

npm http 200 https://registry.npmjs.org/cordova-lib/5.4.1

npm http 304 https://registry.npmjs.org/ansi

npm http GET https://registry.npmjs.org/cordova-lib/-/cordova-lib-5.4.1.tgz

npm http 200 https://registry.npmjs.org/nopt/3.0.1

npm http 200 https://registry.npmjs.org/q/1.0.1

npm http GET https://registry.npmjs.org/q/-/q-1.0.1.tgz

npm http GET https://registry.npmjs.org/nopt/-/nopt-3.0.1.tgz

npm http 200 https://registry.npmjs.org/cordova-lib/-/cordova-lib-5.4.1.tgz

npm http 200 https://registry.npmjs.org/underscore/1.7.0

npm http GET https://registry.npmjs.org/underscore/-/underscore-1.7.0.tgz

npm http 200 https://registry.npmjs.org/nopt/-/nopt-3.0.1.tgz

npm http 200 https://registry.npmjs.org/q/-/q-1.0.1.tgz

npm http 200 https://registry.npmjs.org/underscore/-/underscore-1.7.0.tgz

npm ERR! 

npm ERR! Additional logging details can be found in:

npm ERR!     /Users/Andrea/npm-debug.log

npm ERR! not ok code 0

MacBook-Pro-di-Andrea-Avino:~ Andrea$ 

npm debug: https://drive.google.com/file/d/0B4osTCsSH20XSDlJaUtzV0dydE0/view?usp=sharing

**Comment by KenanY** [comment]
@avinoandrea Please try updating both [Node.js](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-node) and [`npm`](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm).

**Comment by KenanY** [comment]
@avinoandrea Are you still seeing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
