### ISSUE TITLE
list global packages is not working

### ISSUE THREAD

**Issue by iamstarkov** [npm/npm#10607]
```
➜  ~  npm ls -gV
/Users/iamstarkov
└── (empty)

➜  ~  npm i -g chnpm
/usr/local/bin/chnpm -> /usr/local/lib/node_modules/chnpm/cli.js

> spawn-sync@1.0.14 postinstall /usr/local/lib/node_modules/chnpm/node_modules/spawn-sync
> node postinstall

/usr/local/lib
└─┬ chnpm@1.1.4
  ├─┬ chalk@1.1.1
  ├─┬ cp-file@2.3.0
  ├── ini@1.3.4
  ├─┬ meow@3.6.0
  ├─┬ passwd-user@1.2.1
  └── username@1.0.1 # much more here but its not relevant

➜  ~  npm ls -g


➜  ~  npm -v
3.4.1
```

originally reported in twitter https://twitter.com/iamstarkov/status/671063318472298496

**Comment by othiym23** [comment]
Why did you include that `V` in `npm ls -gV`? (The code tells me that `V` isn't a recognized npm parameter, and in that first call to `npm ls` seems to be causing npm to just run with the prefix set to your current working directory.)

What does `npm -g prefix` return? What about `npm ls -g -ddd`?

**Comment by iamstarkov** [comment]
i was thinking that `-v` is for version and `-V` is verbose. I will try `-ddd` when I will be back to my computer in 8 hours

**Comment by iamstarkov** [comment]
I was thinking that -V is for verbose mode

**Comment by iamstarkov** [comment]
here is `-ddd log`

```
➜  iamstarkov.github.io git:(premaster) ✗ npm -g prefix
/usr/local
➜  iamstarkov.github.io git:(premaster) ✗ npm ls -g -ddd
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'ls', '-g', '-ddd' ]
npm info using npm@3.4.1
npm info using node@v5.1.0


npm verb exit [ 0, true ]
npm info ok

**Comment by othiym23** [comment]
I think this is a bug (and I think it's known already, but there are a lot of issues and they're hard to search). If you run `ls -l $(npm -g prefix)/node_modules`, are any of the entries in that listing dangling symlinks? Those have been known to cause `npm ls` to bail out. Thanks for following up!

**Comment by hassankhan** [comment]
Got the same issue here, I did have some dangling symlinks, but removing them didn't help

**Comment by branb** [comment]
Just for proper reference, here is the issue that's related to dangling symlinks: https://github.com/npm/npm/issues/9564
