### ISSUE TITLE
formidable certificate expired/untrusted

### ISSUE THREAD

**Issue by apiereder** [npm/npm#10600]
Log follows:

20 verbose url raw formidable
21 verbose url resolving [ 'https://registry.npmjs.org/', './formidable' ]
22 verbose url resolved https://registry.npmjs.org/formidable
23 info retry registry request attempt 1 at 07:08:43
24 http GET https://registry.npmjs.org/formidable
25 info retry will retry, error on last attempt: Error: SSL Error: CERT_UNTRUSTED
26 info retry registry request attempt 2 at 07:08:54
27 http GET https://registry.npmjs.org/formidable
28 info retry will retry, error on last attempt: Error: SSL Error: CERT_UNTRUSTED
29 info retry registry request attempt 3 at 07:09:54
30 http GET https://registry.npmjs.org/formidable
31 silly lockFile fedfde19-formidable formidable@
32 error Error: SSL Error: CERT_UNTRUSTED
32 error     at ClientRequest.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/main.js:440:26)
32 error     at ClientRequest.g (events.js:185:14)
32 error     at ClientRequest.EventEmitter.emit (events.js:88:17)
32 error     at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1445:7)
32 error     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:111:23)
32 error     at CleartextStream.socketOnData [as ondata] (http.js:1356:20)
32 error     at CleartextStream.CryptoStream._push (tls.js:396:27)
32 error     at SecurePair.cycle (tls.js:750:20)
32 error     at EncryptedStream.CryptoStream.write (tls.js:131:13)
32 error     at Socket.ondata (stream.js:38:26)
32 error  [Error: SSL Error: CERT_UNTRUSTED]
33 error You may report this log at:
33 error     <http://github.com/isaacs/npm/issues>
33 error or email it to:
33 error     <npm-@googlegroups.com>
34 error System Darwin 15.0.0
35 error command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "formidable"
36 error cwd /Users/***/node
37 error node -v v0.8.2
38 error npm -v 1.1.36
39 error message SSL Error: CERT_UNTRUSTED
40 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@apiereder Please try upgrading [Node.js](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-node) and [`npm`](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm).

**Comment by KenanY** [comment]
Closing since `npm@1.1` is extremely old and no longer supported. If you are still seeing this issue with `npm@2` or `npm@3`, @apiereder, feel free to open a new issue.
