### ISSUE TITLE
Add support for github installs with versions

### ISSUE THREAD

**Issue by joshrtay** [npm/npm#10614]
Add support for `npm install <githubname>/<githubrepo>@<version range>`

It shouldn't be too hard to resolve the right tag based on the version range using [github's tags api](https://developer.github.com/v3/repos/#list-tags).

**Comment by KenanY** [comment]
So basically https://github.com/npm/npm/issues/3328?

**Comment by joshrtay** [comment]
Op yep. Some how I didn't come across that when searching.
