### ISSUE TITLE
A cross-platform way to run a shell in the run-scripts environment?

### ISSUE THREAD

**Issue by pygy** [npm/npm#10610]
Is there a cross platform way to run a shell that has access to the `node_modules/.bin` binaries?

I have built a `npm run-script` command that does that (a glorified `{scripts: {shell: "zsh"}}`, built with `child_process.spawnSync(process.env.SHELL, ...)`, but I'd like to know if there's something like that that already exists before publishing it.

An option would be to add `node_modules/.bin` to the path when using `npm explore`? 

Would it be reasonable? If yes, I can work on a PR.

Edit: I went ahead and publised it as `npm-run-shell`.

https://github.com/pygy/npm-run-shell
https://www.npmjs.com/package/npm-run-shell

**Comment by pygy** [comment]
While toying with the above-mentioned package, I realized two issues to that approach:

1) If the startup scripts play with the `PATH` variable, the local `.bin` directory ends up in the middle of the list rather than at the start, and local binaries are shadowed by others, notably by global NPM ones.

2) `child_process.spawnSync("cmd.exe")` launches a non-interactive shell, like #8932.

https://www.npmjs.com/package/npm-run is a better solution to my problem.

**Comment by pygy** [comment]
Well, three problems, actually, I edited the post above...

Maybe a `npm run-bin` command, inspired by the above, could be merged in? Or maybe nothing at all, the status quo isn't bad.

**Comment by othiym23** [comment]
There is a command that does some of this already, which is [`npm explore`](https://docs.npmjs.com/cli/explore). Mostly, it just opens up a subshell within the package directory and allows commands to be run within that context. Unfortunately, it doesn't do the really useful thing that a package script has when run under `npm run-script`, which is setting up all the bin paths. We'd be happy to accept a patch that applies the `run-script` path setup logic to `npm explore`, and there would be brownie points involved if that logic were abstracted out into a utility module. Unfortunately, the team isn't going to have the cycles to do this themselves anytime soon, so I'm going to close this issue, but I do encourage anyone who's interested in seeing this change take a stab at putting together a pull request doing something like the above. Thanks for your time putting this together!
