### ISSUE TITLE
certificate error! need support to close

### ISSUE THREAD

**Issue by jeekiran** [npm/npm#10616]
https://gist.github.com/219a2fad44c9203fc797.git

**Comment by OmgImAlexis** [comment]
@jeekiran if you remove the `.git` from the link it'll work otherwise you get a 404. Looks like either `registry.npmjs.org` was updating/changing their SSL cert or you've got a problem with a CA installed on your computer. Can you confirm this is still an issue?

**Comment by KenanY** [comment]
@jeekiran Is this still an issue for you?

**Comment by KenanY** [comment]
Closing as abandoned.

**Comment by jeekiran** [comment]
Hi,
Thanks for  your kind support .
I was not in the system for past few days . Thats why delayed to replay.
You are right kenan.
The issue was solved
