### ISSUE TITLE
can not install ember-cli and when i put npm install node/debug i get this:

### ISSUE THREAD

**Issue by Nensika** [npm/npm#10619]
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config -                                                                                                                                                                                               -get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:203:12)
npm WARN addRemoteGit     at emitTwo (events.js:87:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:172:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:818:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:319:1                                                                                                                                                                                               1)
npm WARN addRemoteGit     at emitOne (events.js:77:13)
npm WARN addRemoteGit     at Socket.emit (events.js:169:7)
npm WARN addRemoteGit     at Pipe._onclose (net.js:469:12)
npm WARN addRemoteGit  node/debug resetting remote C:\Users\HP\AppData\Roaming\n                                                                                                                                                                                               pm-cache_git-remotes\git-github-com-node-debug-git-478d0138 because of error: {                                                                                                                                                                                                [Error: Command failed: git -c core.longpaths=true config --get remote.origin.u                                                                                                                                                                                               rl
npm WARN addRemoteGit ]
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.ori                                                                                                                                                                                               gin.url' }
npm ERR! git clone --template=C:\Users\HP\AppData\Roaming\npm-cache_git-remotes                                                                                                                                                                                               _templates --mirror git://github.com/node/debug.git C:\Users\HP\AppData\Roaming                                                                                                                                                                                               \npm-cache_git-remotes\git-github-com-node-debug-git-478d0138: Cloning into bar                                                                                                                                                                                               e repository 'C:\Users\HP\AppData\Roaming\npm-cache_git-remotes\git-github-com-                                                                                                                                                                                               node-debug-git-478d0138'...
npm ERR! git clone --template=C:\Users\HP\AppData\Roaming\npm-cache_git-remotes                                                                                                                                                                                               _templates --mirror git://github.com/node/debug.git C:\Users\HP\AppData\Roaming                                                                                                                                                                                               \npm-cache_git-remotes\git-github-com-node-debug-git-478d0138: fatal: remote er                                                                                                                                                                                               ror:
npm ERR! git clone --template=C:\Users\HP\AppData\Roaming\npm-cache_git-remotes                                                                                                                                                                                               _templates --mirror git://github.com/node/debug.git C:\Users\HP\AppData\Roaming                                                                                                                                                                                               \npm-cache_git-remotes\git-github-com-node-debug-git-478d0138:   Repository not                                                                                                                                                                                                found.
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config -                                                                                                                                                                                               -get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:203:12)
npm WARN addRemoteGit     at emitTwo (events.js:87:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:172:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:818:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child                                                                                                                                                                                               _process.js:211:5)
npm WARN addRemoteGit  node/debug resetting remote C:\Users\HP\AppData\Roaming\n                                                                                                                                                                                               pm-cache_git-remotes\https-github-com-node-debug-git-8543cb86 because of error:                                                                                                                                                                                                { [Error: Command failed: git -c core.longpaths=true config --get remote.origin                                                                                                                                                                                               .url
npm WARN addRemoteGit ]
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.ori                                                                                                                                                                                               gin.url' }
npm ERR! git clone --template=C:\Users\HP\AppData\Roaming\npm-cache_git-remotes_templates --mirror https://github.com/node/debug.git C:\Users\HP\AppData\Roaming\npm-cache_git-remotes\https-github-com-node-debug-git-8543cb86: Cloning into bare repository 'C:\Users\HP\AppData\Roaming\npm-cache_git-remotes\https-github-com-node-debug-git-8543cb86'...
npm ERR! git clone --template=C:\Users\HP\AppData\Roaming\npm-cache_git-remotes_templates --mirror https://github.com/node/debug.git C:\Users\HP\AppData\Roaming\npm-cache_git-remotes\https-github-com-node-debug-git-8543cb86: remote: Invalid username or password.
npm ERR! git clone --template=C:\Users\HP\AppData\Roaming\npm-cache_git-remotes_templates --mirror https://github.com/node/debug.git C:\Users\HP\AppData\Roaming\npm-cache_git-remotes\https-github-com-node-debug-git-8543cb86: fatal: Authentication failed for 'https://github.com/node/debug.git/'
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:203:12)
npm WARN addRemoteGit     at emitTwo (events.js:87:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:172:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:818:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
npm WARN addRemoteGit  node/debug resetting remote C:\Users\HP\AppData\Roaming\npm-cache_git-remotes\git-github-com-node-debug-git-0ebfc5a6 because of error: { [Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit ]
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
npm ERR! git clone --template=C:\Users\HP\AppData\Roaming\npm-cache_git-remotes_templates --mirror git@github.com:node/debug.git C:\Users\HP\AppData\Roaming\npm-cache_git-remotes\git-github-com-node-debug-git-0ebfc5a6: Cloning into bare repository 'C:\Users\HP\AppData\Roaming\npm-cache_git-remotes\git-github-com-node-debug-git-0ebfc5a6'...
npm ERR! git clone --template=C:\Users\HP\AppData\Roaming\npm-cache_git-remotes_templates --mirror git@github.com:node/debug.git C:\Users\HP\AppData\Roaming\npm-cache_git-remotes\git-github-com-node-debug-git-0ebfc5a6: Warning: Permanently added 'github.com,192.30.252.130' (RSA) to the list of known hosts.
npm ERR! git clone --template=C:\Users\HP\AppData\Roaming\npm-cache_git-remotes_templates --mirror git@github.com:node/debug.git C:\Users\HP\AppData\Roaming\npm-cache_git-remotes\git-github-com-node-debug-git-0ebfc5a6: Permission denied (publickey).
npm ERR! git clone --template=C:\Users\HP\AppData\Roaming\npm-cache_git-remotes_templates --mirror git@github.com:node/debug.git C:\Users\HP\AppData\Roaming\npm-cache_git-remotes\git-github-com-node-debug-git-0ebfc5a6: fatal: Could not read from remote repository.
npm ERR! git clone --template=C:\Users\HP\AppData\Roaming\npm-cache_git-remotes_templates --mirror git@github.com:node/debug.git C:\Users\HP\AppData\Roaming\npm-cache_git-remotes\git-github-com-node-debug-git-0ebfc5a6:
npm ERR! git clone --template=C:\Users\HP\AppData\Roaming\npm-cache_git-remotes_templates --mirror git@github.com:node/debug.git C:\Users\HP\AppData\Roaming\npm-cache_git-remotes\git-github-com-node-debug-git-0ebfc5a6: Please make sure you have the correct access rights
npm ERR! git clone --template=C:\Users\HP\AppData\Roaming\npm-cache_git-remotes_templates --mirror git@github.com:node/debug.git C:\Users\HP\AppData\Roaming\npm-cache_git-remotes\git-github-com-node-debug-git-0ebfc5a6: and the repository exists.
npm ERR! Windows_NT 6.1.7600
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "node/debug"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\HP\AppData\Roaming\npm-cache_git-remotes_templates --mirror git@github.com:node/debug.git C:\Users\HP\AppData\Roaming\npm-cache_git-remotes\git-github-com-node-debug-git-0ebfc5a6
npm ERR! Cloning into bare repository 'C:\Users\HP\AppData\Roaming\npm-cache_git-remotes\git-github-com-node-debug-git-0ebfc5a6'...
npm ERR! Warning: Permanently added 'github.com,192.30.252.130' (RSA) to the list of known hosts.
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\HP\npm-debug.log

**Comment by KenanY** [comment]
@Nensika There is no `node/debug` repository on GitHub at the moment. What specifically are you trying to install?

**Comment by Nensika** [comment]
@KenanY I try to install ember-cli, but npm cant do that, somethimes nothing happened, somethimes i get warms npm in line 27.... I was trying few days to install and dont know what to do....

**Comment by KenanY** [comment]
@Nensika Sorry I never responded to this. Are you still experiencing this issue?

**Comment by SamAI-Software** [comment]
@KenanY, I have this problem when trying to install some of the packages. For example, `expressworks`

```
user@PC MINGW64 /d/exp
$ npm install -g expressworks
/c/Program Files/nodejs/npm: line 34:  9592 Illegal instruction     "$NODE_EXE"
"$NPM_CLI_JS" "$@"
```
ref: #12816

**Comment by LizzieZhao** [comment]
@SamAI-Software Do you solve this problem? I have this problem too

**Comment by SamAI-Software** [comment]
@LizzieZhao yes, I did. But not in the Windows :smile: I've installed Linux and it all worked out.

**Comment by LizzieZhao** [comment]
@SamAI-Software  soga, Thanks a lot

**Comment by Nensika** [comment]
I had to reinstall my comp

**Comment by legodude17** [comment]
Ok so who is still having this issue?

**Comment by KenanY** [comment]
Closing due to no response
