### ISSUE TITLE
when i'm running,  npm install --no-bin-links  .then getting the ERROR....can any body help me for solve this issue

### ISSUE THREAD

**Issue by rocky-2790** [npm/npm#10617]
[npm-debug.txt](https://github.com/npm/npm/files/47016/npm-debug.txt)
40212 error Error: UNKNOWN, mkdir '/opt/dockerprojects/analytics/dawn/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/node_modules/fs-extra/node_modules/rimraf/node_modules/glob/node_modules/minimatch/node_modules/brace-expansion'
40213 error If you need help, you may report this log at:
40213 error     <http://github.com/isaacs/npm/issues>
40213 error or email it to:
40213 error     <npm-@googlegroups.com>
40214 error System Linux 3.18.5-tinycore64
40215 error command "/usr/bin/nodejs" "/usr/bin/npm" "install" "--no-bin-links"
40216 error cwd /opt/dockerprojects/analytics/dawn
40217 error node -v v0.10.25
40218 error npm -v 1.3.10
40219 error path /opt/dockerprojects/analytics/dawn/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/node_modules/fs-extra/node_modules/rimraf/node_modules/glob/node_modules/minimatch/node_modules/brace-expansion
40220 error fstream_path /opt/dockerprojects/analytics/dawn/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/node_modules/fs-extra/node_modules/rimraf/node_modules/glob/node_modules/minimatch/node_modules/brace-expansion
40221 error fstream_type Directory
40222 error fstream_class DirWriter
40223 error code UNKNOWN
40224 error errno -1
40225 error fstream_stack /usr/lib/nodejs/fstream/lib/dir-writer.js:36:23
40225 error fstream_stack /usr/lib/nodejs/mkdirp/index.js:37:53
40225 error fstream_stack Object.oncomplete (fs.js:107:15)
40226 verbose exit [ -1, true ]

**Comment by KenanY** [comment]
@rocky-2790 `npm@1.3` is no longer supported. Try [upgrading](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm).

**Comment by KenanY** [comment]
Closing since this version of `npm` has not been supported for quite some time now. If you are still seeing this issue with `npm@2` or `npm@3`, feel free to open a new issue.
