### ISSUE TITLE
Error while installing MobileAngularUI

### ISSUE THREAD

**Issue by deadmann** [npm/npm#10620]
i follow this toturial...
and i run this command:
npm install -g bower yo gulp generator-mobileangularui

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x8
6)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "bower" "yo" "gul
p" "generator-mobileangularui"
npm ERR! node v5.1.0
npm ERR! npm  v3.3.12

npm ERR! Callback called more than once.
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     F:\AngularMobile\npm-debug.log
npm ERR! code 1

[npm-debug.txt](https://github.com/npm/npm/files/47085/npm-debug.txt)

**Comment by KenanY** [comment]
@deadmann Does this also happen if you [upgrade](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows) `npm`?

**Comment by deadmann** [comment]
i just install node js, so shouldn't it be the last version? and how can i do that? i'm new to many stuff i require to create my first HTML based mobile app :| all i did till now was to worked with full featured IDE, being unaware of all these stuff

**Comment by KenanY** [comment]
@deadmann Sorry I never responded. Are you still seeing this issue?

**Comment by deadmann** [comment]
i'm not working on that project from long ago, so i'm not sure

**Comment by KenanY** [comment]
I'm gonna close this then. If you ever run into this again feel free to open a new issue.
