### ISSUE TITLE
What kind of license should I put for a closed source projects?

### ISSUE THREAD

**Issue by lipis** [npm/npm#10621]
If I don't have a license field I'm getting:

```
npm WARN EPACKAGEJSON my-project@1.0.0 No license field.
```

and I can't find anything suitable without getting the following error:

```
npm WARN EPACKAGEJSON my-project@1.0.0 license should be a valid SPDX license expression
```

From the https://spdx.org/licenses/:

> The SPDX License List is a list of commonly found open source licenses and exceptions for the purposes...

So my question is, if I have a closed source project and I want to get rid of the `WARN` what do I do?

**Comment by KenanY** [comment]
@lipis Is this what you are looking for?:

> Finally, if you do not wish to grant others the right to use a private or unpublished package under any terms:
>
> ```
> { "license": "UNLICENSED"}
> ```

https://docs.npmjs.com/files/package.json#license

**Comment by lipis** [comment]
RTFM :)

thanks
