### ISSUE TITLE
stuck on older version

### ISSUE THREAD

**Issue by atomikolex** [npm/npm#10626]
When I npm install -g npm on Linux, I have no errors, but get

/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
npm@3.5.0 /usr/local/lib/node_modules/npm

npm --v gives me 2.14.3, but npm list -g --depth=0 is:

/usr/local/lib
├── bower@1.6.8
├── gulp@3.9.0
├── n@2.0.2
├── npm@3.5.0
└── typescript@1.6.2

/usr/local/bin/npm and /usr/local/lib/node_modules/ are both writeable. 

How can I change to the newer version?

**Comment by Martii** [comment]
Have you tried `$ sudo npm install npm -g` to make sure it gets put in the Linux tree properly? You may have to go axe it from all `node_modules` folders manually if you didn't have appropriate permissions with that version.

Also `$ sudo npm uninstall npm -g` may work for you.

There is a known issue in #10492 and you may have to uinstall *node* and reinstall *node* to get rid of that issue. *npm*@3.5.0 was stuck on our production and development as well which could affect how older versions interoperate depending on install permissions.

**Comment by atomikolex** [comment]
Yes, #10492 is what I was coming from.
I tried to uninstall again with sudo npm uninstall npm -g and I tried sudo make uninstal as well, but could only deleted the newer version. 

So I uninstalled node with sudo rm -r bin/node bin/npm include/node lib/node_modules share/man/man/node.1 on /usr/local, and finally reinstalled from source.

Now I have node 5.1 again, but npm --v still shows 2.14.3, while  npm list -g --depth=0 finds
/usr/local/lib
└── npm@3.3.12

Could you give me a hint, which other folders need to be deleted first?

**Comment by Martii** [comment]
I know some Linux distros package *npm* you might check that too. Mine however does not.

Where it stores it globally can be different depending on what happened but mine is sitting at the global home of `/usr/lib/node_modules` ... `/usr/local/lib` indicates that it's a local library instead of a global library for you... perhaps you have both.

**Comment by Martii** [comment]
Also did you set a `--prefix=/usr` with `./configure` or just use the stock for *node* ?? This could affect where it got installed too... a `make uninstall` will only remove it from where it was configured from.

**Comment by atomikolex** [comment]
Forgot a possible prefix of the original installation, I'm afraid. 
But after uninstalling node 5.1 again, I still have a .npm-packages folder at my home directory, and an npm folder at lib/node_modules inside it. 
Also, I have a .node-gyp folder with directories for the node versions I had until now.
So, can I just delet .npm-packages and node-gyp, and I'm good to go for a clean install?

**Comment by Martii** [comment]
Early on with some testing I flat out "axed" everything manually with a `rm` and that was over a year ago and my dev stations have been doing well. You may want to capture your shell session and see where a "normal" install puts things and do a `locate` *(corresponding `updatedb`)* and see if there are any artifacts *(stragglers)* hanging around to get rid of.

Linux typically doesn't store information in a registry hive like windows *(thankfully)* so you should be okay to manually `rm` everything related to all versions. In the future you may want to stick to a common install/uninstall method to handle the critical bugs introduced by *node* and *npm*. We all make mistakes, some projects more, it's just a matter of finding a way to fix it. :)

**Comment by atomikolex** [comment]
So I went for it and have a clean install now, everything running as expected! Just now I have sticky note for the next uninstall ;-) 
Thank you so much for supporting!

**Comment by Martii** [comment]
No problem... good luck. :)
