### ISSUE TITLE
`npm publish --no-tag` publishes with "false" dist-tag

### ISSUE THREAD

**Issue by boennemann** [npm/npm#10625]
I was trying to publish a new version of a package and explicitly have no dist-tag attached to it. Following nopt's argument conventions I was trying to achieve this behavior by using `npm publish --no-tag`, which to my suprise didn't end in either no tag (yay), "latest" being used, or an error, but in "false" being used as the dist-tag.

I understand how this is happening under the hood, but I think it is a very confusing and unexpected behavior, which should be changed, depending on how you want to support this, to an error or no tag being used.

If you tell me in which direction you want this to go, and whether that's supported by the registry at all, I'm happy to give it a shot.

Best,
Stephan

**Comment by othiym23** [comment]
Every publish _must_ be associated with a dist-tag, by design. `validate-and-store` (a registry microservice) won't allow packages without associated tags. Fixing this is going to be a pain in the butt, btw, because of how `nopt`'s coercion rules work. But yeah, this is a footgun for sure.
