### ISSUE TITLE
I cannot install underscore. 

### ISSUE THREAD

**Issue by Mangulomx** [npm/npm#10623]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'install' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose config Skipping project config: /home/miguel/.npmrc. (matches userconfig)
5 verbose readDependencies loading dependencies from /home/miguel/package.json
6 warn package.json @ No description
7 warn package.json @ No repository field.
8 warn package.json @ No README data
9 warn package.json @ No license field.
10 verbose install where, deps [ '/home/miguel', [ 'underscore' ] ]
11 verbose install where, peers [ '/home/miguel', [] ]
12 verbose installManyTop reading for lifecycle /home/miguel/package.json
13 info preinstall @
14 verbose readDependencies loading dependencies from /home/miguel/package.json
15 silly cache add args [ 'underscore@1.5.2', null ]
16 verbose cache add spec underscore@1.5.2
17 silly cache add parsed spec { raw: 'underscore@1.5.2',
17 silly cache add   scope: null,
17 silly cache add   name: 'underscore',
17 silly cache add   rawSpec: '1.5.2',
17 silly cache add   spec: '1.5.2',
17 silly cache add   type: 'version' }
18 silly addNamed underscore@1.5.2
19 verbose addNamed "1.5.2" is a plain semver version for underscore
20 silly mapToRegistry name underscore
21 silly mapToRegistry using default registry
22 silly mapToRegistry registry https://registry.npmjs.org/
23 silly mapToRegistry uri https://registry.npmjs.org/underscore
24 verbose addNameVersion registry:https://registry.npmjs.org/underscore not in flight; fetching
25 verbose request uri https://registry.npmjs.org/underscore
26 verbose request no auth needed
27 info attempt registry request try #1 at 10:27:41
28 verbose request id 2972f24105cf3fe4
29 http request GET https://registry.npmjs.org/underscore
30 http 200 https://registry.npmjs.org/underscore
31 silly get cb [ 200,
31 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
31 silly get     etag: '"86N4VTQ6LWF71TWEBEBXJB5NV"',
31 silly get     'content-type': 'application/json',
31 silly get     'cache-control': 'max-age=60',
31 silly get     'content-length': '41786',
31 silly get     'accept-ranges': 'bytes',
31 silly get     date: 'Mon, 30 Nov 2015 09:27:43 GMT',
31 silly get     via: '1.1 varnish',
31 silly get     age: '5',
31 silly get     connection: 'keep-alive',
31 silly get     'x-served-by': 'cache-lhr6328-LHR',
31 silly get     'x-cache': 'HIT',
31 silly get     'x-cache-hits': '2',
31 silly get     'x-timer': 'S1448875663.349030,VS0,VE0',
31 silly get     vary: 'Accept' } ]
32 verbose get saving underscore to /home/miguel/.npm/registry.npmjs.org/underscore/.cache.json
33 silly mapToRegistry name underscore
34 silly mapToRegistry using default registry
35 silly mapToRegistry registry https://registry.npmjs.org/
36 silly mapToRegistry uri https://registry.npmjs.org/underscore
37 verbose addRemoteTarball https://registry.npmjs.org/underscore/-/underscore-1.5.2.tgz not in flight; adding
38 verbose addRemoteTarball [ 'https://registry.npmjs.org/underscore/-/underscore-1.5.2.tgz',
38 verbose addRemoteTarball   '1335c5e4f5e6d33bbb4b006ba8c86a00f556de08' ]
39 info retry fetch attempt 1 at 10:27:43
40 info attempt registry request try #1 at 10:27:43
41 http fetch GET https://registry.npmjs.org/underscore/-/underscore-1.5.2.tgz
42 http fetch 200 https://registry.npmjs.org/underscore/-/underscore-1.5.2.tgz
43 silly fetchAndShaCheck shasum 1335c5e4f5e6d33bbb4b006ba8c86a00f556de08
44 verbose addTmpTarball /tmp/npm-2577-cbbe9ded/registry.npmjs.org/underscore/-/underscore-1.5.2.tgz not in flight; adding
45 verbose addTmpTarball already have metadata; skipping unpack for underscore@1.5.2
46 silly cache afterAdd underscore@1.5.2
47 verbose afterAdd /home/miguel/.npm/underscore/1.5.2/package/package.json not in flight; writing
48 verbose afterAdd /home/miguel/.npm/underscore/1.5.2/package/package.json written
49 silly install resolved [ { name: 'underscore',
49 silly install resolved     description: 'JavaScript\'s functional programming helper library.',
49 silly install resolved     homepage: 'http://underscorejs.org',
49 silly install resolved     keywords: [ 'util', 'functional', 'server', 'client', 'browser' ],
49 silly install resolved     author: { name: 'Jeremy Ashkenas', email: 'jeremy@documentcloud.org' },
49 silly install resolved     repository:
49 silly install resolved      { type: 'git',
49 silly install resolved        url: 'git://github.com/jashkenas/underscore.git' },
49 silly install resolved     main: 'underscore.js',
49 silly install resolved     version: '1.5.2',
49 silly install resolved     devDependencies: { phantomjs: '1.9.0-1' },
49 silly install resolved     scripts: { test: 'phantomjs test/vendor/runner.js test/index.html?noglobals=true' },
49 silly install resolved     licenses: [ [Object] ],
49 silly install resolved     files: [ 'underscore.js', 'underscore-min.js', 'LICENSE' ],
49 silly install resolved     bugs: { url: 'https://github.com/jashkenas/underscore/issues' },
49 silly install resolved     _id: 'underscore@1.5.2',
49 silly install resolved     dist:
49 silly install resolved      { shasum: '1335c5e4f5e6d33bbb4b006ba8c86a00f556de08',
49 silly install resolved        tarball: 'http://registry.npmjs.org/underscore/-/underscore-1.5.2.tgz' },
49 silly install resolved     _from: 'underscore@1.5.2',
49 silly install resolved     _npmVersion: '1.3.5',
49 silly install resolved     _npmUser: { name: 'jashkenas', email: 'jashkenas@gmail.com' },
49 silly install resolved     maintainers: [ [Object] ],
49 silly install resolved     directories: {},
49 silly install resolved     _shasum: '1335c5e4f5e6d33bbb4b006ba8c86a00f556de08',
49 silly install resolved     _resolved: 'https://registry.npmjs.org/underscore/-/underscore-1.5.2.tgz' } ]
50 info install underscore@1.5.2 into /home/miguel
51 info installOne underscore@1.5.2
52 verbose installOne of underscore to /home/miguel not in flight; installing
53 warn locking Error: EACCES, open '/home/miguel/.npm/_locks/underscore-9eac46d14df2c94b.lock'
53 warn locking     at Error (native)
53 warn locking  /home/miguel/.npm/_locks/underscore-9eac46d14df2c94b.lock failed { [Error: EACCES, open '/home/miguel/.npm/_locks/underscore-9eac46d14df2c94b.lock']
53 warn locking   errno: -13,
53 warn locking   code: 'EACCES',
53 warn locking   path: '/home/miguel/.npm/_locks/underscore-9eac46d14df2c94b.lock' }
54 verbose stack Error: Attempt to unlock /home/miguel/node_modules/underscore, which hasn't been locked
54 verbose stack     at unlock (/usr/local/lib/node_modules/npm/lib/utils/locker.js:66:11)
54 verbose stack     at cb (/usr/local/lib/node_modules/npm/lib/install.js:1017:5)
54 verbose stack     at /usr/local/lib/node_modules/npm/lib/install.js:1021:20
54 verbose stack     at /usr/local/lib/node_modules/npm/lib/utils/locker.js:40:9
54 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:149:38)
54 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:177:38
54 verbose stack     at FSReqWrap.oncomplete (fs.js:95:15)
55 verbose cwd /home/miguel
56 error Linux 3.13.0-55-generic
57 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
58 error node v0.12.7
59 error npm  v2.11.3
60 error Attempt to unlock /home/miguel/node_modules/underscore, which hasn't been locked
61 error If you need help, you may report this error at:
61 error     <https://github.com/npm/npm/issues>
62 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@Mangulomx Try fixing the permissions of your cache directory with

``` sh
sudo chown -R $(whoami) "$HOME/.npm"
```

**Comment by KenanY** [comment]
Closing as not an issue with `npm`. If you don't have the user permissions necessary to modify `npm`'s cache directory then `npm` is gonna throw these kinds of errors when you attempt to run it.
