### ISSUE TITLE
Node FIPS support/npm

### ISSUE THREAD

**Issue by mhdawson** [npm/npm#10629]
Support for building Node in a FIPS capable mode was added a while back.  

More recently effort has gone into making sure the test suite can run/pass when Node is built in FIPS capable mode.  See https://github.com/nodejs/node/issues/3760 opened by @stefanmb for more details.

Tests are now running in the CI in FIPS capable more as part of the regression tests (see here:  https://ci.nodejs.org/job/node-test-commit-linux-fips/)

As part of this work (as rasied by @lordjabez) along with other issues it has been discovered that npm does not work when FIPS is built in FIPS capable mode (some discussion is in https://github.com/nodejs/node/issues/3760)

The issue seems to be that MD5 is used by some sub-modules to generate unique values. MD5 is dis-allowed in FIPS mode.  Looking at the cases were MD5 is being used it does not look like it needs to be MD5, only that it was an easy way to generate a semi-unique value.   PRs have been opened to change to different algorithms. The dependent modules look to be owned by people who are part of the npm organization which is why I'm opening the issue here.  The modules are:

+ https://github.com/iarna/write-file-atomic/pull/7 
+ https://github.com/iarna/unique-slug/pull/1 
+ https://github.com/npm/fs-write-stream-atomic/pull/6 

I'm opening this issue to explain the importance of pulling these changes in and to provide a place where any necessary discussion can take place.

**Comment by mhdawson** [comment]
@zkat is this something you can help out with ?

**Comment by othiym23** [comment]
I've landed npm/fs-write-stream-atomic@dfaac1bef2db9473d276b0ee3cf077d1fadd88ff, which takes care of that. @iarna, can you either merge iarna/write-file-atomic#7 and iarna/unique-slug#1 and put out new versions of those, or move them into the npm organization so I can fix them? If we can get those out tomorrow, we can have a FIPS-compliant `npm@3.5.1`.

**Comment by mhdawson** [comment]
Were you also planning to put then into the 2.X line ?

**Comment by othiym23** [comment]
Yes. For now, npm LTS is taking dependency upgrades as a matter of course.

**Comment by othiym23** [comment]
The close came from the relevant commits landing on `master` (which will be `npm@3.5.2`), and I'm in the process of releasing `npm@2.14.14`, which has the same changes, so both `npm@2` and `npm@3` will work with FIPS-restricted builds of Node.js once their respective versions have become `latest`.

**Comment by mhdawson** [comment]
Stefan mentioned that  npm/fs-write-stream-atomic@dfaac1b, landed but not the other 2

**Comment by mhdawson** [comment]
Hmm, looking at a few I think it looks like there were commits so I'll follow up with Stefan

**Comment by stefanmb** [comment]
@mhdawson Looks like the relevant changes have actually made it in, for reference:

https://github.com/npm/fs-write-stream-atomic/commit/dfaac1bef2db9473d276b0ee3cf077d1fadd88ff
https://github.com/npm/unique-slug/commit/f1cd16d1aa46794efa1be6083f5c909bb684d894
https://github.com/npm/write-file-atomic/commit/22dd8759076fc8d0327d50693283060e479afafc

I believe this issue is fixed. Thanks @mhdawson and @othiym23 for your help!

**Comment by othiym23** [comment]
Yes, as far as I know the only thing in the npm dependency tree that uses MD5 at this point is `request`, and npm never uses the functionality in `request` that would cause it to execute that code. `npm@3.5.2` and higher should work fine with FIPS Node.js builds.
