### ISSUE TITLE
npm 3: package not installed on the initial install

### ISSUE THREAD

**Issue by darrinholst** [npm/npm#10637]
I've found a combination of dependencies where a top level package isn't installed on the first try. Subsequent installs will install it. I've narrowed it down to [these dependencies](https://github.com/darrinholst/npm-example/blob/master/package.json#L11-L17). The first install to an empty `node_modules` results in `glob` not being installed. The debug output for the first install is [here](https://gist.github.com/darrinholst/cd576a038baba0d1da8f). The output for the second install is [here](https://gist.github.com/darrinholst/ff40bf5f43a43b4867d5)

**Comment by wcandillon** [comment]
@darrinholst I am also affected by the exact same issue.

**Comment by darrinholst** [comment]
This is working correctly in `npm@3.5.0`, just not the version that comes bundled with `node@5.1.0`.
