### ISSUE TITLE
missing script: eslint

### ISSUE THREAD

**Issue by wqbs369** [npm/npm#10638]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run-script',
1 verbose cli   'eslint' ]
2 info using npm@2.14.12
3 info using node@v5.0.0
4 verbose stack Error: missing script: eslint
4 verbose stack     at run (/usr/local/lib/node_modules/npm/lib/run-script.js:142:19)
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/run-script.js:58:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:345:5
4 verbose stack     at checkBinReferences_ (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:309:45)
4 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:343:3)
4 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:113:5)
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:232:12
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:76:16
4 verbose stack     at tryToString (fs.js:414:3)
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
5 verbose cwd /Users/lx/PAProject/master/react_native
6 error Darwin 14.5.0
7 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run-script" "eslint"
8 error node v5.0.0
9 error npm  v2.14.12
10 error missing script: eslint
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@wqbs369 Do you have an `"eslint"` script defined in your `package.json`?

**Comment by KenanY** [comment]
Closing as resolved; if one does not define a `"eslint"` script in the `"scripts"` section of their `package.json`, then `npm` is going to report this error appropriately when one tries to execute
`npm run eslint`. If you are still seeing this issue, @wqbs369, feel free to let me know and I will reopen.
