### ISSUE TITLE
npm3 incorrectly issues warnings when installing valid module

### ISSUE THREAD

**Issue by yortus** [npm/npm#10636]
npm3 incorrectly issues warnings on `npm install`. E.g. when installing [`asyncx`](https://www.npmjs.com/package/asyncx):

```
npm WARN enoent ENOENT: no such file or directory, open '[redacted]/asyncx/node_modules/asyncx.js/package.json'
```

In this case `asyncx.js` is a file put there by [`require-self`](https://www.npmjs.com/package/require-self) on prepublish. It is valid to have files in `node_modules`. This should not raise any error or warning.

npm3 issues a similar warning if `node_modules` contains a subdirectory which has an `index.js` but not a `package.json`. Again, that is perfectly valid and should not generate a warning.

npm is using a subset of the [module loading spec](https://nodejs.org/api/modules.html#modules_loading_from_node_modules_folders), and that's fine, but it is incorrect to issue warnings for things outside its usage that are nevertheless spec compliant, such as the above case. By doing so, it doesn't play well with the wider ecosystem.

**Comment by othiym23** [comment]
With which version of npm did you encounter this bug?

**Comment by yortus** [comment]
v3.5.1 (i.e. latest) does this. And also all other versions of 3.x that I have checked.

**Comment by yortus** [comment]
@othiym23 it looks like this bug may have been fixed, can you confirm?
