### ISSUE TITLE
scoped npm config env vars not consistent with unscoped env vars

### ISSUE THREAD

**Issue by rmg** [npm/npm#10631]
From the docs, you do this to specify a registry to use for a given scope:

```
npm config set @myco:registry http://reg.example.com
```

Doing so results in an environment variable being set when npm runs:

```
npm_config__myco_registry=http://reg.example.com
```

Unlike unscoped npm configurations, this env var is not _read_ by npm:

```
$ npm_config__myco_registry=http://something/else npm config get @myco:registry
http://reg.example.com
$ npm_config_registry=http://foobar npm config get registry
http://foobar/
```

These env vars are particularly useful when doing things like running `npm install` inside a docker container or any other scenario where you can't or don't want to use a config file.

**Comment by zkat** [comment]
This seems more like a bug than a feature request -- having this kind of weird inconsistency is unpleasant, and we more than welcome patches for it. We may also eventually get to it ourselves but it's not in the horizon right now.

Thanks for reporting this, and we'll keep it open for the time being.
