### ISSUE TITLE
Cannot find module 'npm-autoinit/autoinit'

### ISSUE THREAD

**Issue by luke2wei** [npm/npm#10642]
```
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm"
npm ERR! node v5.1.0
npm ERR! npm  v3.3.12
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'npm-autoinit/autoinit'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

Can not use any npm command

npm -v
3.3.12
node -v
v5.1.0

**Comment by tastomy** [comment]
same with me

**Comment by LouisonGitzinger** [comment]
Same problem, even after a total clean install of Node and npm …

**Comment by MaximizedAction** [comment]
Same. Happens in case of a Homebrew install too.

**Comment by LouisonGitzinger** [comment]
Found à solution : 
There was a hidden folder in my user folder, try a clean install, and delete this hidden folder containing nom files

**Comment by MaximizedAction** [comment]
After trying out all possible permutations of uninstalling, hunting down leftover hidden folders and reinstalling different packages, it finally worked with brew's node.
Thanks @LouisonGitzinger !

**Comment by sepisoad** [comment]
it's easy to fix:
1) go to c:\users\<YourUserName>\
2) find a file named ".npmrc"
3) remove this line =>   onload-script=npm-autoinit/autoinit
and your'e done

**Comment by xusai2014** [comment]
@sepisoad  Thank you very much ! The answer is perfect but I met the another questions as below:

jerrydeMacBook-Pro:~ jerry$ npm ls
jerry@1.0.0 /Users/jerry
├── UNMET DEPENDENCY eslint@undefined2.8.0
└── UNMET DEPENDENCY eslint-plugin-meteor@undefined3.5.2

npm ERR! missing: eslint@undefined2.8.0, required by jerry@1.0.0
npm ERR! missing: eslint-plugin-meteor@undefined3.5.2, required by jerry@1.0.0
npm ERR! not ok code 0 

Two package were installed but I have re-install the node and nvm.Could you give me help ?

**Comment by TigerBui** [comment]
Thanks @sepisoad!
