### ISSUE TITLE
npm update is not reflecting in git bash

### ISSUE THREAD

**Issue by harshjulka** [npm/npm#10646]
npm version: 1.4.28
after npm install -g npm
npm@3.5.0

however npm -v is still showing 1.4.28

**Comment by KenanY** [comment]
@harshjulka Windows? Have you read [this](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows)?

**Comment by dpwolfe** [comment]
To me this is the biggest pain point in setting up a new windows machine, just installing node and trying to install npm. *I recommend taking a look at node version manager (nvm) for windows: https://github.com/coreybutler/nvm-windows*. Node and npm should make nvm a first class feature that comes in the install to save all of us from this. Hope this helps others who land here.

**Comment by harshjulka** [comment]
@KenanY  Thanks done

**Comment by KenanY** [comment]
Closing as resolved.
