### ISSUE TITLE
npm output garbage characters into windows cmd in some code page

### ISSUE THREAD

**Issue by NijiharaTsubasa** [npm/npm#10648]
I got this garbled output every time I run npm install since I updated node to 4.x
But some of my friends say it's a progress bar
Until I figured out it only output garbage characters in Chinese code page (and maybe japanese one, I didn't test)

Garabge output in Chinese code page
![qq 20151201200235](https://cloud.githubusercontent.com/assets/7794838/11500245/e28f5836-9866-11e5-93fa-f7e360e8952b.png)

In English code page everything works well
![qq 20151201200207](https://cloud.githubusercontent.com/assets/7794838/11500244/e28e0b2a-9866-11e5-9bbf-f6099ee48b34.png)

(Note that if you want to reproduce this, you can ONLY chcp 936 when non-unicode locale is set to Chinese in the control panel, or you will get Invalid code page error)

**Comment by othiym23** [comment]
This looks like a consequence of the glyphs we chose to use for the spinner and progress bar doing strange things in CJKV codepages on Windows. See iarna/gauge#5 for further discussion, and it would be good to get the input of Japanese and / or Chinese users there.

**Comment by kenbod** [comment]
This is happening on OS X El Capitan as well in an English environment. I'm not seeing any spinners or progress bars just lots of garbled text like this:

runTopLevelLifecycles     ▌ ╢████████████████████████

**Comment by iarna** [comment]
@kenbod That is the progress bar– For example see this early version of it:

https://dl.dropboxusercontent.com/u/567198/Documents/progress-bar.m4v

That said, we're pretty set on moving it to just be ascii and having folks opt into unicode versions.

**Comment by kenbod** [comment]
@iarna Thanks for that. That looks really cool! Unfortunately, it doesn't look the same on my machine:

https://dl.dropboxusercontent.com/u/7106195/npm_install.mov

Hope this helps!

**Comment by iarna** [comment]
@kenbod Thanks, that's helpful! You can work around this issue for now by:

If you're using Terminal.app:

Make sure the following checkbox is unchecked:

Preferences -> Profiles -> Advanced -> Unicode East Asian Ambiguous Characters are wide

(It's at the very bottom of the pane.)

Or in iTerm2:

Preferences -> Profiles -> Text -> Treat ambiguous-width characters as double width

(It's in the middle at the top of the Unicode section.)

**Comment by kenbod** [comment]
@iarna Thank you! That did the trick. I appreciate the help.

**Comment by lwr** [comment]
@iarna Thank you! It helps.

**Comment by xuwenkeke** [comment]
@iarna Thansk for your help! :smile:

**Comment by NijiharaTsubasa** [comment]
I think I found out the reason of this issue
I thought about how the progress bar works, Seems that the character count is calculated to fill in **just one line**, then when the next line is outputed, last line is erased so the viewer see a growing progress bar
But in Chinese code pages, the characters used by the bar are **full width** (regular ascii characters are "half width") , which means they **take up the space of 2 characters**, and as a result the progress bar output to 2 lines, and broke itself, and result in the picture I posted here.

**Comment by b-long** [comment]
Is this issue related to https://github.com/npm/npm/issues/9670 ?
