### ISSUE TITLE
 "sudo npm install -g cordova ionic" command execution issue on MAC

### ISSUE THREAD

**Issue by pratapshaik** [npm/npm#10645]
233:~ eshan$ sudo npm install -g cordova ionic
npm ERR! tar.unpack unzip error /tmp/npm-485-8da7667d/registry.npmjs.org/unzip2/-/unzip2-0.2.5.tgz
npm ERR! tar.unpack untar error /tmp/npm-485-8da7667d/registry.npmjs.org/unzip2/-/unzip2-0.2.5.tgz
npm ERR! tar.unpack unzip error /tmp/npm-485-8da7667d/registry.npmjs.org/nan/-/nan-2.1.0.tgz
npm ERR! tar.unpack untar error /tmp/npm-485-8da7667d/registry.npmjs.org/nan/-/nan-2.1.0.tgz
loadRequestedDeps → after ▄ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟

**Comment by KenanY** [comment]
@pratapshaik `npm --version`?

**Comment by kenma9123** [comment]
I got the same errors. tar.unpack. I'm using npm version `3.5.1` with node version `5.1.0`

**Comment by pratapshaik** [comment]
map/-/source-map-0.5.3.tgz
npm ERR! tar.unpack untar error /tmp/npm-452-054a0c9f/registry.npmjs.org/source-map/-/source-map-0.5.3.tgz
npm ERR! tar.unpack unzip error /tmp/npm-452-054a0c9f/registry.npmjs.org/hawk/-/hawk-1.1.1.tgz
npm ERR! tar.unpack untar error /tmp/npm-452-054a0c9f/registry.npmjs.org/hawk/-/hawk-1.1.1.tgz
npm ERR! tar.unpack unzip error /tmp/npm-452-054a0c9f/registry.npmjs.org/tar/-/tar-1.0.2.tgz
npm ERR! tar.unpack unzip error /tmp/npm-452-054a0c9f/registry.npmjs.org/npm/-/npm-2.14.13.tgz
npm ERR! Darwin 14.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "cordova" "ionic"
npm ERR! node v5.1.0
npm ERR! npm  v3.5.0
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read

npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm ERR! Darwin 14.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "cordova" "ionic"
npm ERR! node v5.1.0
npm ERR! npm  v3.5.0
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! syscall read

npm ERR! network read ETIMEDOUT
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm ERR! Darwin 14.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "cordova" "ionic"
npm ERR! node v5.1.0
npm ERR! npm  v3.5.0
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! syscall read

npm ERR! network read ETIMEDOUT
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

**Comment by pratapshaik** [comment]
could you please help out here getting different errors while installing ionic framework .

**Comment by kenma9123** [comment]
@pratapshaik there seem to be a problem when installing ionic and cordova via npm3. Try downgrading to 2.x. It works from there.
