### ISSUE TITLE
Feature : add --only=files argument to npm install

### ISSUE THREAD

**Issue by Alphapage** [npm/npm#10644]
Hello,

It would be great to only install files from a package during development.
For now, I use --only=dev as a workaround, but npm checks modules which are up to date and it takes a lot of time even if checking from cache.

So is there a way to install only updated files without checking dependencies or devdependencies ?

Thanks in advance and I hope it could help others.

**Comment by othiym23** [comment]
What does "install only updated files" mean when installing?

**Comment by othiym23** [comment]
The primary purpose of the installer is to make sure that the dependency tree is up to date, so what you're asking for doesn't really make sense. As such, this isn't a feature that we're going to add. That said, you might want to take a look at `npm link`, as the odds are good that it will give you the behavior you want – you can run `npm link <package>`, and then changes in `<package>` will be picked up instantly in the app you're working on.

Thanks for filing this issue and answering my question!
