### ISSUE TITLE
Old README data in registry (babylon)

### ISSUE THREAD

**Issue by jmm** [npm/npm#10652]
For at least one package, [babylon](https://www.npmjs.com/package/babylon), the `README` data in the registry is out of sync with the package. I believe it's been this way for quite some time for this package.

```sh
$ npm i babylon && wc -m node_modules/babylon/README.md
1962

$ npm show babylon readme | wc -m
666
```

(There's no `readme` prop in the [`package.json`](https://github.com/babel/babel/blob/2f5b95306676c16ad85c88cffb33b9ef61bfd35a/packages/babylon/package.json) that's published.)

As you can see, the character count of the errant `README` data (for ***Babylon***) is the mark of the beast :expressionless:

The discrepancy also shows up on the website (for some time), so it's not a local issue.

On another note, after a package is installed, why is `package.json` populated with a `readme` prop containing?:

```
ERROR: No README data found!
```

Not sure if it even matters for anything -- just seems odd (and maybe unintentional?).

Also, for at least this package the website appears to be displaying an incorrect repository URL: `https://github.com/babel/babel/tree/master/packages`. `package.json` has `https://github.com/babel/babel/tree/master/packages/babylon`. In this case the registry is showing the correct value, so I'll follow up about that on the website repo.

Possibly related: https://github.com/npm/npm/issues/6050

**Comment by jmm** [comment]
The repo URL part is from [github-url-to-object](https://github.com/zeke/github-url-to-object/pull/15).

**Comment by othiym23** [comment]
The CLI doesn't choose what gets displayed for the README – this is either the consequence of a bad publish, or an issue with the registry. The best way to get registry issues dealt with is to email support@npmjs.com. As this isn't an issue with the CLI, I'm going to close it, but I do encourage you to get in touch with support (and include a link to this issue!) so that it gets cleaned up. Thanks for your time!

**Comment by jmm** [comment]
Thanks @othiym23! I poked around a bit before filing here and couldn't tell if there was somewhere else for registry issues. There could've been a bad publish at some point, but the content in the registry doesn't match the `README` that's in the package currently, so while I don't know exactly what that means or how it could get that way, something is still out of whack after successful publishes. I'll follow up as you directed.
