### ISSUE TITLE
npm install -g parse error code HPE_INVALID_CONSTANT

### ISSUE THREAD

**Issue by kienntk** [npm/npm#10659]
I am a newbie and I want to use IONIC framework to develop application.
I am follow this tutorial:
https://github.com/Microsoft/cordova-docs/blob/master/articles/getting-started/create-first-app-using-vs-tools-apache-cordova.md
to develop with ionic.
But when I run command:
`npm install -g cordova` or `npm install -g ionic`
I got the error:
![image](https://cloud.githubusercontent.com/assets/13272329/11522192/4ebe5446-98e7-11e5-92f3-6e278bd59626.png)

Thanks for any help!!

**Comment by HankLeo** [comment]
I meet the same problem and it caused by HPE company network. I can use npm 'install' when using other network.
