### ISSUE TITLE
Error in running sudo npm install express

### ISSUE THREAD

**Issue by kakoli** [npm/npm#10651]
sudo npm install express in Ubuntu 14.04 giving error:

```
npm ERR! Error: UNKNOWN, symlink '../mime/cli.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-68-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "express"
npm ERR! cwd /vagrant/testProject
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path ../mime/cli.js
npm ERR! code UNKNOWN
npm ERR! errno -1
npm http 200 https://registry.npmjs.org/mime-db
npm http 200 https://registry.npmjs.org/inherits
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /vagrant/testProject/npm-debug.log
npm ERR! not ok code 0
```

npm -v : 2.14.7
node -v : 4.2.2
But in debug.log the versions are different
Attaching the npm-debug.log :
[npm-debug.txt](https://github.com/npm/npm/files/48758/npm-debug.txt)

**Comment by KenanY** [comment]
@kakoli `npm@1.3` is no longer supported so be sure to [update](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) at your earliest convenience. Also if your system does not support symlinks then try using the [`--no-bin-links`](https://docs.npmjs.com/misc/config#bin-links) flag

**Comment by kakoli** [comment]
--no-bin-links worked

**Comment by othiym23** [comment]
Closing as resolved. @kakoli Be sure to switch to a newer, supported version of npm! The [NodeSource distribution](https://github.com/nodesource/distributions) is a great way to do that for Linux distribution.
