### ISSUE TITLE
Change the flat behaviour

### ISSUE THREAD

**Issue by martinheidegger** [npm/npm#10668]
As mentioned in #10562 the new flat behaviour in npm@3 is not really 100% comfortable. However, I would like to see a slightly different implementation: 

How about having 3 modes for storage:
1.*The "old" way*: `--mode=hierarchy` that adheres strictly to the hierarchy of dependencies
2.*The "new" way*: `--mode=flat` that tries flatten out things as good as possible
3. A middle-way: `--mode=adaptive` that adhere's to the hierarchy but breaks them if:
  - installing it in the same level would break the "windows-path-limit" 
  - two subpackages could share the same child package it installs it in the parent package.

i.e.

```
a: [b, c]
b: [d, e]
c: [d, f, i]
f: [g, h@1]
i: [g, h@2]
```
could turn into:

```
a
-- b
   -- e
-- c
   -- f
     -- h@1
   -- i
     -- h@2 
   -- g   // f & i both share it so it is stored in c
-- d    // b & c both share it so it is stored above  
```

**Comment by othiym23** [comment]
As we discussed on #10562, this is the new default behavior for npm, and I don't think we're going to think about changing it until it's been in the wild for at least two or three major versions. See my comments on #10562 for the whys and wherefores of this decision.
