### ISSUE TITLE
"sudo npm install -g yo" failed, but solved with "rm -rf ~/.npm"

### ISSUE THREAD

**Issue by yglin** [npm/npm#10666]
Actually I was going to upgrade yeoman, have been using it for a while.
Run `sudo npm install -g yo` on Mac OSX 10.11.1 gives me error messages below.

    npm ERR! Darwin 15.0.0
    npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "yo"
    npm ERR! node v0.12.6
    npm ERR! npm  v3.5.0
    npm ERR! path          /usr/local/lib/node_modules/yo/node_modules/got/node_modules/duplexify/node_modules/readable-   stream/node_modules/util-deprecate
    npm ERR! code ENOENT
    npm ERR! errno -2
    
    npm ERR! enoent ENOENT, rename '/usr/local/lib/node_modules/yo/node_modules/got/node_modules/duplexify/node_modules/readable-stream/node_modules/util-deprecate'
    npm ERR! enoent ENOENT, rename '/usr/local/lib/node_modules/yo/node_modules/got/node_modules/duplexify/node_modules/readable-stream/node_modules/util-deprecate'
    npm ERR! enoent This is most likely not a problem with npm itself
    npm ERR! enoent and is related to npm not being able to find a file.
    npm ERR! enoent 

    npm ERR! Please include the following file with any support request:
    npm ERR!     /private/tmp/npm-debug.log
    npm ERR! code 1

Googled it and found that `rm -rf ~/.npm` solved this problem.
Just to inform you of this issue.

--
Yeoman is very helpful, I used it to generate my first angular app, THANK YOU~

**Comment by eddiemonge** [comment]
Did you upgrade to npm@3 before running this? Seems like after upgrading, its best to remove and reinstall global/local things so the tree gets fixed.

Removing your local `.npm` folder "fixed" it because it cleared npms cache forcing it to redo stuff in the new version.

**Comment by yglin** [comment]
@eddiemonge Yes, I think I did.
Some days ago I ran `npm update` first time of my life.
Thanx for point it out~

**Comment by eddiemonge** [comment]
@yglin can this be closed then?

**Comment by yglin** [comment]
Oh, right, sorry
