### ISSUE TITLE
[Discussion] let "npm install --save" save commitish dependency for git repo in package.json

### ISSUE THREAD

**Issue by thynson** [npm/npm#10663]
e.g.
```
npm install --save git+ssh://private.repo/private-project
```
will result into
```
{
    ...
    "dependencies": {
        ...
        "private-project": "git+ssh://private.repo/private-project#0123456789abcdeffedc"
        ...
    },
    ...
}
```
And, we should prevent npm fetch the repository again from remote if commitish hash(arguably full sha1 hash) is present. 
In this way `npm install` won't fetch the repository from remote again and again, except explicitly installing such repos again.

**Comment by thynson** [comment]
I just found full-sha1 commitish git dependency is present, npm(2.14.6) won't refetch the remote, already. Just let npm save with full-sha1commitish dependency for git repo tagged should be ok.

**Comment by tomekwi** [comment]
Doesn’t `--save --save-exact` do this already?

**Comment by thynson** [comment]
Oh, you're right. I didn't see `--save-exact` option.
