### ISSUE TITLE
npm install command inside repo project returns unbuild , Node ERR!! and warning issues. Pls support!

### ISSUE THREAD

**Issue by DeepikaGopala** [npm/npm#10660]
[npm-debug_log.pdf](https://github.com/npm/npm/files/49456/npm-debug_log.pdf)

i have attached the npm debug log file.  pls suggest whats the cause for the npm not installing properly. i had event tried to remove the existing node_modules in the repo and did npm cache clean and reinstall it.. but same error persists.

**Comment by othiym23** [comment]
Please upload a [gist](https://help.github.com/articles/creating-gists/) containing either the contents of `npm-debug.log`, or whatever you can cut and paste from your terminal session. With the information you've provided thus far, I don't have enough information to tell you what's wrong.

**Comment by DeepikaGopala** [comment]
Yeah, sorry abt that.. i was continuing it and it got submitted with accidental enter button click., Im updating it
