### ISSUE TITLE
different packages sets based on deployment environment

### ISSUE THREAD

**Issue by perzy** [npm/npm#10661]
Our project catch a problem when development,production workflow.

I config a package private host on private git repo. like this:
```
"dependencies": {
    "xxx-common": "git+ssh://git@git.xxx.com/node/common-modules.git"
}
```
And ours git repo is inner network.

So on production env , the package.json will hope like this:
```
"dependencies": {
    "xxx-common": "git+ssh://git@localhost:8999/node/common-modules.git"
}
```

Ours inner git repo setup a long connection to production env server on port 8999.
So on production env through 

```
git clone ssh://git@localhost:8999/node/common-modules.git
```

can pull ours inner network sources.

We user pm2 deploy pm2.json production/test to deploy ours project to production/test server 
automatic.

So we have face a problem now , How to switch npm priave package automatic according to 
diff env like production/test.

We hope package.json can config some packge like this:
```
"dependencies": {
    "we-common":{ 
          "development": "git+ssh://git@git.xxx.com/node/common-modules.git",
          "test": "git+ssh://git@localhost:8998/node/common-modules.git",
          "production":"git+ssh://git@localhost:8999/node/common-modules.git"
    } ,
    //...
}
```

Is npm already can do this or will be add this feature later ? 

Thanks!

**Comment by othiym23** [comment]
If I understand your description of the problem correctly, you would like some way to choose which dependencies get installed based on your environmental configuration. While there are package managers, like rubygems or Maven, that support this kind of conditional, environment-based installation, npm isn't one of them, and I don't think the complexity required is justified by the benefits this functionality would provide. (Also, from an operational point of view, what you're requesting sounds a little iffy, because it means that you're deploying different code than you developed / tested against.) This isn't something we're going to add to npm, but thanks for your time!

**Comment by sergiolc** [comment]
It would be very useful when one has private packages with continuous changes, especially when there are multiple collaborators. Also, the npm link issue(it does not install dependencies on root folder) would be solved. I don't see much complexity in adding "proDependencies" in package.json and then run npm with some parameter like "--override=pro/dev", where all "dependencies" would be installed plus "proDependencies" or "devDependencies".

**Comment by sercanov** [comment]
Would not be so bad. 

For example I have worker and app environment, both using the same code base but I'm not using some modules in worker such as analytics. Which some are pretty big packages and i cant install these on small instances with low memories. 

I know there are a lot of workarounds but still would be great to have install packages based on a environment flag.

**Comment by jjzazuet** [comment]
Chiming in here for support of this feature. In my case, my application applies the `hard-source-webpack-plugin` while in development to reduce our iteration code packaging time. However our CI box doesn't need it, so it would make sense to have to be able to exclude it. Thanks!

**Comment by winescout** [comment]
I have a case for it as well,  react-native-sentry is needed when targeting IOS, but nowhere else.  It has some linking that gets done as part of its install scripts which fails everywhere else.  optionalDependencies almost handles this, but not quite.
