### ISSUE TITLE
npm install error "Cannot extract .../grunt-htmlhint/0.9.9/package.tgz" 

### ISSUE THREAD

**Issue by ardenhuang** [npm/npm#10671]
"npm install" had the error of extracting .../grunt-htmlhint/0.9.9/package.tgz". What is there is ".../grunt-htmlhint/0.9.12/package.tgz".

[npm-debug.log.txt](https://github.com/npm/npm/files/49962/npm-debug.log.txt)

**Comment by eddiemonge** [comment]
`npm cache clean` and try again?

**Comment by ardenhuang** [comment]
Hi, Eddie,

Thank you for your offer. But unfortunately what you suggested didn't work.
"npm cache clean" removed the ".npm" folder in my home directory. But when
I do "npm install". The ".npm" folder is re-created with
"~/.npm/grunt-htmlhint/0.9.12".
The folder "0.9.9" was looked after by "npm install".


Yiteng (Arden) Huang | Research Scientist | ardenhuang@google.com |
 1-347-638-4998
*Google* | 111 8th Avenue | New York, NY 10011 | USA
