### ISSUE TITLE
cannot find modules npm-autoinit

### ISSUE THREAD

**Issue by luke2wei** [npm/npm#10676]
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/5.1.0/bin/node',
1 verbose cli   '/usr/local/bin/npm' ]
2 info using npm@3.3.12
3 info using node@v5.1.0
4 verbose stack Error: Cannot find module 'npm-autoinit/autoinit'
4 verbose stack     at Function.Module._resolveFilename (module.js:338:15)
4 verbose stack     at Function.Module._load (module.js:289:25)
4 verbose stack     at Module.require (module.js:366:17)
4 verbose stack     at require (module.js:385:17)
4 verbose stack     at cb (/usr/local/lib/node_modules/npm/lib/npm.js:288:9)
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/npm.js:384:16
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/config/core.js:80:7
4 verbose stack     at Array.forEach (native)
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/config/core.js:79:13
4 verbose stack     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:17:25)
5 verbose cwd /usr/local/lib/node_modules/npm
6 error Darwin 14.5.0
7 error argv "/usr/local/Cellar/node/5.1.0/bin/node" "/usr/local/bin/npm"
8 error node v5.1.0
9 error npm  v3.3.12
10 error code MODULE_NOT_FOUND
11 error Cannot find module 'npm-autoinit/autoinit'
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true
```

**Comment by israeleis** [comment]
I have the exact same problem.

I tried uninstalling and reinstalling again for maybe dozens of times.

can't find a solution on the web
please help..

os: windows 8.1 X64

npm-debug.log
--------------------------------------------------------------------------------
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\LOCAL_USER\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'express' ]
2 info using npm@3.5.2
3 info using node@v5.3.0
4 verbose stack Error: Cannot find module 'npm-autoinit/autoinit'
4 verbose stack     at Function.Module._resolveFilename (module.js:326:15)
4 verbose stack     at Function.Module._load (module.js:277:25)
4 verbose stack     at Module.require (module.js:354:17)
4 verbose stack     at require (internal/module.js:12:17)
4 verbose stack     at cb (C:\Users\LOCAL_USER\AppData\Roaming\npm\node_modules\npm\lib\npm.js:290:9)
4 verbose stack     at C:\Users\LOCAL_USER\AppData\Roaming\npm\node_modules\npm\lib\npm.js:386:16
4 verbose stack     at C:\Users\LOCAL_USER\AppData\Roaming\npm\node_modules\npm\lib\config\core.js:80:7
4 verbose stack     at Array.forEach (native)
4 verbose stack     at C:\Users\LOCAL_USER\AppData\Roaming\npm\node_modules\npm\lib\config\core.js:79:13
4 verbose stack     at f (C:\Users\LOCAL_USER\AppData\Roaming\npm\node_modules\npm\node_modules\once\once.js:17:25)
5 verbose cwd C:\Users\LOCAL_USER\WebstormProjects\firstapp
6 error Windows_NT 6.3.9600
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\LOCAL_USER\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "express"
8 error node v5.3.0
9 error npm  v3.5.2
10 error code MODULE_NOT_FOUND
11 error Cannot find module 'npm-autoinit/autoinit'
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]
