### ISSUE TITLE
2.14.14: npm install doesn't respect npm-shrinkwrap.json at 100%

### ISSUE THREAD

**Issue by xaka** [npm/npm#10673]
I thought `npm-shrinkwrap.json` was meant to be way to take a snapshot of node_modules and being able to restore its shape at 100% at any time regardless of `package.json` (unless you specify a flag). As it turned out, it's not the case.

Here is `package.json`:

```
  "dependencies": {
    "express": "~4.13.3"
  },
  "devDependencies": {
    "serve-static": "~1.10.0"
  },
```

And `npm-shrinkwrap.json`:

```
    "express": {
      "version": "4.13.3",
      "from": "express@4.13.3",
      "resolved": "https://registry.npmjs.org/express/-/express-4.13.3.tgz",
      "dependencies": {
        "serve-static": {
          "version": "1.10.0",
          "from": "serve-static@>=1.10.0 <1.11.0",
          "resolved": "https://registry.npmjs.org/serve-static/-/serve-static-1.10.0.tgz"
        },
      }
    },
```

And after running `npm install` we're getting:

```
$ ls node_modules/
serve-static

ls node_modules/express/node_modules/serve-static
ls: node_modules/express/node_modules/serve-static: No such file or directory
```

As we can see, `serve-static` didn't get installed as local copy for `express` though it's in `npm-shrinkwrap.json`. It simply doesn't produce deterministic results as expected.

**Comment by iarna** [comment]
As you point out, this is easily reproducible in npm@2. (With https://gist.github.com/iarna/05649e5efb3029a2772f)

You'll find that this is fixed in npm@3.

**Comment by xaka** [comment]
@iarna Unfortunately we're not planning to switch over to npm@3 yet. Would it be possible to backport the fix to npm@2?

**Comment by aush** [comment]
The same issue for me, npm@3.3.12

npm-shrinkwrap.json:
{
  "name": "react-tfractal",
  "version": "0.0.1",
  "dependencies": {
    "fabric": {
      "version": "1.6.0-rc.1",
      "from": "fabric@1.6.0-rc1",
      "dependencies": {
        "canvas": {
          "version": "1.3.5",
          "from": "canvas@1.3.5"
        }
      }
    }
  }
}
