### ISSUE TITLE
npm publish ignores semver metadata

### ISSUE THREAD

**Issue by mstade** [npm/npm#10677]
I'm not sure if this is a bug, or intended behavior. If you have a published version – let's say `1.0.0` – and you try to publish a new version with metadata – let's say `1.0.0+meta` – then `npm publish` will complain and say `You cannot publish over the previously published version 1.0.0.`

Semver does say that in deciding version precedence, metadata *should* be ignored. That said, it's not a *must*... Anyway, just found it curious and figured I'd ask – what is npm's stance on this?

**Comment by othiym23** [comment]
That's exactly what the semver spec says should be done with build metadata – everything after the `+` is ignored for the purposes of semver comparisons. That metadata is purely for your use as a developer.

So yes, everything is behaving properly here. If you want to publish e.g. snapshots, you might look at using prerelease versions, although those have their own complications when it comes to semver. Semver really just wants you to use major, minor, patch triples!

**Comment by mstade** [comment]
Thanks for the clarification @othiym23, much obliged!
