### ISSUE TITLE
npm fails to install Cordova

### ISSUE THREAD

**Issue by Sudarshan021** [npm/npm#10688]
```
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\ node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova"
npm ERR! node v5.1.1
npm ERR! npm  v3.3.12
```

**Comment by KenanY** [comment]
@Sudarshan021 I have no idea what the actual error is here. Could you upload the `npm-debug.log` as a [gist](https://gist.github.com/)?

**Comment by kvamshi19** [comment]
am also encountering the same issuee... wat is the solution for thsi issue.. ?? please help me..

**Comment by KenanY** [comment]
@kvamshi19 Please see my comment above.

**Comment by KenanY** [comment]
@Sudarshan021 Are you still having any issues with `npm`? If so, could you provide the `npm-debug.log` file I requested a few months ago?

@kvamshi19 If you are still encountering an issue with `npm` feel free to open a new issue with a `npm-debug.log` file.

**Comment by KenanY** [comment]
Closing as abandoned.
