### ISSUE TITLE
bug in install soket.io in linux npm ERR! TypeError: Cannot read property 'latest' of undefined

### ISSUE THREAD

**Issue by julio899** [npm/npm#10694]
$ npm install soket.io
npm WARN package.json app-node@0.0.1 No repository field.
npm WARN package.json app-node@0.0.1 No README data
npm http GET https://registry.npmjs.org/soket.io
npm http 404 https://registry.npmjs.org/soket.io
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/usr/share/npm/lib/cache.js:687:35)
npm ERR!     at /usr/share/npm/lib/cache.js:675:5
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-66-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "soket.io"
npm ERR! cwd /home/julio899/NODE/express
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type non_object_property_load
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/julio899/NODE/express/npm-debug.log
npm ERR! not ok code 0

**Comment by KenanY** [comment]
@julio899 `npm@1.3` is no longer supported. Please try [updating](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm).

**Comment by julio899** [comment]
very thanks KenanY
