### ISSUE TITLE
Any idea for specifying git url directly on package.json and running `npm prepublish` before installing?

### ISSUE THREAD

**Issue by qsona** [npm/npm#10698]
Hello. I have a question.

I want to use a project (I call it `project-a` this time) at the newest commit of it's github, not published to npm. So I described my `package.json` as follows.

```
"dependencies": {
  "project-a": "user/project-a"
}
```

But, project-a has a `.npmignore` file and `prepublish` script on `package.json`. In particular, it's about as follows.

```
# .npmignore
src/

# package.json
"scripts": {
  "prepublish": "babel src/ --out-dir lib/"
}
```

And when I run `npm install` on my project, project-a is installed but it doesn't have neither `src/` nor `lib/`. 
`src/` is ignored because of `.npmignore`, and `lib/` is not created because it's not published.

If `lib/` exists, it's everything okay for me. If `src/` exists, I can build it by writing `prepublish` script on my `package.json`. But I cannot do anything because both don't exist...

Of course I know it's not a bug or fault of npm, but... do you have any ideas to resolve it? (Ideas for `project-a` are also welcome.)

Thanks.

**Comment by KenanY** [comment]
The `"prepublish"` script not running for git repositories is https://github.com/npm/npm/issues/3055 and `.npmignore` + git repositories is https://github.com/npm/npm/issues/7262 I believe. Haven't tried thinking of a workaround though.

**Comment by qsona** [comment]
@KenanY Thank you for pointing it out. I'm sorry it was definitely a duplicate question. Some ideas are shown on #3055 so I'll try them. Since discussion seems to be ongoing on #3055 , I'd like to close this issue.
Thank you for the fast reply!
