### ISSUE TITLE
npm can't list globally installed packages

### ISSUE THREAD

**Issue by riyadhalnur** [npm/npm#10708]
`npm ls -g --depth=0` can't list the installed packages.

NPM version 3.5.1 on 0.10.40 on OSX El Capitan

**Comment by riyadhalnur** [comment]
Issue still persists in 3.5.2. Downgraded to 2.x for it to work

**Comment by othiym23** [comment]
When you say "can't list the installed packages", do you mean that npm exits without producing a package listing? Or do you mean that the CLI crashes?

**Comment by riyadhalnur** [comment]
@othiym23 it exits without producing a package listing

**Comment by gcoupelant** [comment]
+1

**Comment by chrisleck** [comment]
Issue persisting in 3.5.3.  This is painful for skipping install of global native packages.

**Comment by peter-mouland** [comment]
I have got this when i have manually removed local packages that were made global using `npm link`.
The sym-links `npm link` create confuse npm if they don't point to an existing directory.  Removing those invalid symlinks, or using the `unlink` command before removing the directories fixes the issue.

Could this be your problem?

**Comment by riyadhalnur** [comment]
I have never made a local package global manually.

**Comment by peter-mouland** [comment]
I also had the problem earlier this week (before i started using `npm link`), but i just removed all global packages (apart from `npm`) and reinstalled the couple I now use (i.e. I had grunt, gulp and many others that i forgot about since local packages are preferred).
I assume one of them must have something invalid going on...

**Comment by riyadhalnur** [comment]
The issue was seen on v3 but not on v2, so I don't think any packages had anything to do with it.

**Comment by mbellerose** [comment]
I ran into this issue on Windows 7. I delete the ~\AppData\Roaming\npm folder and the problem went away. I did have to reinstall all my global packages.
