### ISSUE TITLE
npm install fails on node-gyp but doesn't report anything

### ISSUE THREAD

**Issue by Greg15153** [npm/npm#10701]
When installing my package.json with npm install, it will get to something that requires node-gyp and attempt to run the command but stops directly after the node-gyp command was issued. it doesnt output anything with verbose or debug flags. If I install the package it failed at by itself (npm install lwip) it correctly runs the node-gyp command and builds it. 

Running npm install a second time right after the previous failure, will also allow it to build correctly. Seems to be something conflicting but I can't narrow it down.

This is what im seeing during an npm install

```
npm info lifecycle async@0.9.2~install: async@0.9.2
npm info lifecycle nan@2.0.9~install: nan@2.0.9
npm info lifecycle lwip@0.0.8~install: lwip@0.0.8

> lwip@0.0.8 install /home/ubuntu/jenkins/workspace/GE-Build-AppMachine/Web/node_modules/lwip
> node-gyp rebuild
```

This is occuring on Ubuntu 14.04 with node 5.0.0 and npm 3.6.6. This works completely fine on Windows.

Just tried CentOS 7. Same issue.

**Comment by Greg15153** [comment]
So i've done more investigating and it seems a specific package combination is doing it. lwip, Sprity and PhantomJS specifcally. I've attached our dependencies and dev-dependencies below (removed all the fluff). Even if its a bug in one of the packages npm install still gives no warnings or errors and just stops at a build stage like mentioned above only on linux. All packages build on their own and I can get the node-gyp rebuild jobs to run when certain jobs are removed from the package.json. 

I've just tried 5.1 and 5.2 also same issue. Here goes my step-by-step on a new centos machine laucnhed from AWS:

```
sudo yum groupinstall -y 'Development Tools'
sudo yum install -y java-1.6.0-openjdk-devel
sudo yum install -y git

curl -O https://nodejs.org/dist/v5.0.0/node-v5.0.0-linux-x64.tar.gz
mkdir /usr/local/node
tar --strip-components 1 -xzvf node-v* -C /usr/local/node
export PATH=$PATH:/usr/local/node/bin
npm install -g gulp
#clone repository, CD
npm install 
```

```
{
"dependencies": {
    "babel": "6.1.5",
    "babel-preset-es2015": "6.1.4",
    "babelify": "7.2.0",
    "browserify": "12.0.1",
    "gulp": "3.9.0",
    "gulp-angular-templatecache": "1.8.0",
    "gulp-autoprefixer": "3.1.0",
    "gulp-changed": "1.3.0",
    "gulp-flatten": "0.2.0",
    "gulp-if": "2.0.0",
    "gulp-jshint": "1.12.0",
    "gulp-minify-html": "1.0.4",
    "gulp-ng-annotate": "1.1.0",
    "gulp-replace-task": "0.11.0",
    "gulp-sass": "2.1.0",
    "gulp-strip-debug": "1.0.2",
    "gulp-uglify": "1.4.2",
    "gulp-util": "3.0.7",
    "jshint-stylish": "2.0.1",
    "lwip": "0.0.8",
    "moment": "2.10.6",
    "require-dir": "0.3.0",
    "run-sequence": "1.1.4",
    "sprity": "1.0.7",
    "sprity-sass": "1.0.4",
    "tinycolor2": "1.1.2",
    "vinyl-buffer": "1.0.0",
    "vinyl-source-stream": "1.1.0",
    "vinyl-transform": "1.0.0",
    "yargs": "3.29.0"
  },
  "devDependencies": {
    "browser-sync": "2.10.0",
    "jasmine-core": "2.3.4",
    "jasmine-reporters": "2.0.7",
    "karma": "0.13.15",
    "karma-browserify": "4.4.0",
    "karma-chrome-launcher": "0.2.1",
    "karma-jasmine": "0.3.6",
    "karma-junit-reporter": "0.3.8",
    "karma-phantomjs-launcher": "0.2.1",
    "lodash": "3.10.1",
    "phantomjs": "1.9.18"
  }
 }
```

**Comment by mareeb** [comment]
Please run "sudo /opt/node/bin/npm install  (Instead of npm install)"

Where /opt/node/bin/npm is the complete path of binary. This will resolved your issue.
