### ISSUE TITLE
npm3, some dependencies don't get installed on first npm install

### ISSUE THREAD

**Issue by stevengill** [npm/npm#10707]
Using npm 3.4.1
node V5.0.0
```git clone https://github.com/apache/cordova-lib &&
cd cordova-lib/cordova-lib &&
npm install```

This installs a bunch of modules and then I finally get these two warnings at the end
`npm WARN EPACKAGEJSON cordova-lib@6.0.0-dev No license field.`
`npm WARN EBUNDLEOVERRIDE Replacing bundled npm > npm-registry-client with new installed version`

Thing is, it doesn't install/replace `npm-registry-client`. I have to run `npm install` again and then it will install it. 

I am going to look into updating the version of npm we are using in cordova-lib eventually here.

First run of npm install:

```
├─┬ aliasify@1.8.0
│ └─┬ browserify-transform-tools@1.3.3
│   ├─┬ falafel@1.0.1
│   │ └── acorn@0.11.0
│   └── through@2.3.8
├── cordova-app-hello-world@3.10.0
├─┬ cordova-common@1.0.0
│ ├─┬ bplist-parser@0.1.1
│ │ └── big-integer@1.6.8
│ ├─┬ osenv@0.1.3
│ │ ├── os-homedir@1.0.1
│ │ └── os-tmpdir@1.0.1
│ ├── q@1.4.1
│ ├── semver@5.1.0
│ ├── shelljs@0.5.3
│ └── underscore@1.8.3
├─┬ cordova-js@4.1.2
│ └─┬ browserify@10.1.3
│   ├── assert@1.3.0
│   ├─┬ browser-pack@4.0.4
│   │ ├─┬ combine-source-map@0.3.0
│   │ │ ├── convert-source-map@0.3.5
│   │ │ ├─┬ inline-source-map@0.3.1
│   │ │ │ └── source-map@0.3.0
│   │ │ └── source-map@0.1.43
│   │ ├── defined@1.0.0
│   │ ├─┬ through2@0.5.1
│   │ │ ├── readable-stream@1.0.33
│   │ │ └── xtend@3.0.0
│   │ └── umd@3.0.1
│   ├── browser-resolve@1.10.1
│   ├─┬ browserify-zlib@0.1.4
│   │ └── pako@0.2.8
│   ├─┬ buffer@3.5.3
│   │ ├── ieee754@1.1.6
│   │ └── is-array@1.0.1
│   ├── builtins@0.0.7
│   ├── commondir@0.0.1
│   ├─┬ concat-stream@1.4.10
│   │ └── typedarray@0.0.6
│   ├── constants-browserify@0.0.1
│   ├─┬ crypto-browserify@3.11.0
│   │ ├─┬ browserify-cipher@1.0.0
│   │ │ ├─┬ browserify-aes@1.0.5
│   │ │ │ └── buffer-xor@1.0.3
│   │ │ ├─┬ browserify-des@1.0.0
│   │ │ │ └─┬ des.js@1.0.0
│   │ │ │   └── minimalistic-assert@1.0.0
│   │ │ └── evp_bytestokey@1.0.0
│   │ ├─┬ browserify-sign@4.0.0
│   │ │ ├── bn.js@4.5.0
│   │ │ ├── browserify-rsa@4.0.0
│   │ │ ├─┬ elliptic@6.0.2
│   │ │ │ ├── brorand@1.0.5
│   │ │ │ └── hash.js@1.0.3
│   │ │ └─┬ parse-asn1@5.0.0
│   │ │   └── asn1.js@4.2.1
│   │ ├── create-ecdh@4.0.0
│   │ ├─┬ create-hash@1.1.2
│   │ │ ├── cipher-base@1.0.2
│   │ │ └── ripemd160@1.0.1
│   │ ├── create-hmac@1.1.4
│   │ ├─┬ diffie-hellman@5.0.0
│   │ │ └── miller-rabin@4.0.0
│   │ ├── pbkdf2@3.0.4
│   │ ├── public-encrypt@4.0.0
│   │ └── randombytes@2.0.1
│   ├── deep-equal@1.0.1
│   ├── defined@1.0.0
│   ├── deps-sort@1.3.9
│   ├── domain-browser@1.1.4
│   ├── duplexer2@0.0.2
│   ├── events@1.0.2
│   ├─┬ glob@4.5.3
│   │ └── minimatch@2.0.10
│   ├─┬ has@1.0.1
│   │ └── function-bind@1.0.2
│   ├── htmlescape@1.1.0
│   ├─┬ http-browserify@1.7.0
│   │ └── Base64@0.2.1
│   ├── https-browserify@0.0.1
│   ├─┬ insert-module-globals@6.6.3
│   │ ├─┬ combine-source-map@0.6.1
│   │ │ ├── convert-source-map@1.1.2
│   │ │ ├── inline-source-map@0.5.0
│   │ │ ├── lodash.memoize@3.0.4
│   │ │ └── source-map@0.4.4
│   │ ├── is-buffer@1.1.0
│   │ └─┬ lexical-scope@1.2.0
│   │   └─┬ astw@2.0.0
│   │     └── acorn@1.2.2
│   ├── isarray@0.0.1
│   ├─┬ JSONStream@1.0.7
│   │ └── jsonparse@1.2.0
│   ├─┬ labeled-stream-splicer@1.0.2
│   │ └── stream-splicer@1.3.2
│   ├─┬ module-deps@3.9.1
│   │ ├── defined@1.0.0
│   │ ├─┬ detective@4.3.1
│   │ │ ├── acorn@1.2.2
│   │ │ └── defined@1.0.0
│   │ └─┬ stream-combiner2@1.0.2
│   │   └─┬ through2@0.5.1
│   │     ├── readable-stream@1.0.33
│   │     └── xtend@3.0.0
│   ├── os-browserify@0.1.2
│   ├─┬ parents@1.0.1
│   │ └── path-platform@0.11.15
│   ├── path-browserify@0.0.0
│   ├── process@0.11.2
│   ├── punycode@1.3.2
│   ├── querystring-es3@0.2.1
│   ├─┬ read-only-stream@1.1.1
│   │ └── readable-wrap@1.0.0
│   ├─┬ readable-stream@1.1.13
│   │ └── core-util-is@1.0.2
│   ├── shallow-copy@0.0.1
│   ├─┬ shasum@1.0.2
│   │ ├─┬ json-stable-stringify@0.0.1
│   │ │ └── jsonify@0.0.0
│   │ └── sha.js@2.4.4
│   ├── shell-quote@0.0.1
│   ├── stream-browserify@1.0.0
│   ├── string_decoder@0.10.31
│   ├─┬ subarg@1.0.0
│   │ └── minimist@1.2.0
│   ├─┬ syntax-error@1.1.4
│   │ └── acorn@1.2.2
│   ├── through2@1.1.1
│   ├── timers-browserify@1.4.1
│   ├── tty-browserify@0.0.0
│   ├─┬ url@0.10.3
│   │ └── querystring@0.2.0
│   ├── util@0.10.3
│   ├─┬ vm-browserify@0.0.4
│   │ └── indexof@0.0.1
│   └── xtend@4.0.1
├─┬ cordova-registry-mapper@1.1.13
│ └─┬ tape@3.5.0
│   ├── deep-equal@0.2.2
│   ├── defined@0.0.0
│   ├─┬ glob@3.2.11
│   │ └── minimatch@0.3.0
│   ├── object-inspect@0.4.0
│   └── resumer@0.0.0
├─┬ cordova-serve@1.0.0
│ ├─┬ chalk@1.1.1
│ │ ├── ansi-styles@2.1.0
│ │ ├── escape-string-regexp@1.0.3
│ │ ├─┬ has-ansi@2.0.0
│ │ │ └── ansi-regex@2.0.0
│ │ ├── strip-ansi@3.0.0
│ │ └── supports-color@2.0.0
│ ├─┬ compression@1.6.0
│ │ ├─┬ accepts@1.3.0
│ │ │ ├── mime-types@2.1.8
│ │ │ └── negotiator@0.6.0
│ │ ├── bytes@2.1.0
│ │ ├─┬ compressible@2.0.6
│ │ │ └── mime-db@1.20.0
│ │ ├─┬ debug@2.2.0
│ │ │ └── ms@0.7.1
│ │ ├── on-headers@1.0.1
│ │ └── vary@1.1.0
│ ├─┬ express@4.13.3
│ │ ├─┬ accepts@1.2.13
│ │ │ └── negotiator@0.5.3
│ │ ├── array-flatten@1.1.1
│ │ ├── content-disposition@0.5.0
│ │ ├── content-type@1.0.1
│ │ ├── cookie@0.1.3
│ │ ├── cookie-signature@1.0.6
│ │ ├── depd@1.0.1
│ │ ├── escape-html@1.0.2
│ │ ├── etag@1.7.0
│ │ ├─┬ finalhandler@0.4.0
│ │ │ └── unpipe@1.0.0
│ │ ├── fresh@0.3.0
│ │ ├── merge-descriptors@1.0.0
│ │ ├── methods@1.1.1
│ │ ├─┬ on-finished@2.3.0
│ │ │ └── ee-first@1.1.1
│ │ ├── parseurl@1.3.0
│ │ ├── path-to-regexp@0.1.7
│ │ ├─┬ proxy-addr@1.0.9
│ │ │ ├── forwarded@0.1.0
│ │ │ └── ipaddr.js@1.0.4
│ │ ├── qs@4.0.0
│ │ ├── range-parser@1.0.3
│ │ ├─┬ send@0.13.0
│ │ │ ├── destroy@1.0.3
│ │ │ ├── http-errors@1.3.1
│ │ │ ├── mime@1.3.4
│ │ │ └── statuses@1.2.1
│ │ ├── serve-static@1.10.0
│ │ ├─┬ type-is@1.6.10
│ │ │ └── media-typer@0.3.0
│ │ ├── utils-merge@1.0.0
│ │ └── vary@1.0.1
│ └── q@1.4.1
├─┬ dep-graph@1.1.0
│ └── underscore@1.2.1
├─┬ elementtree@0.1.6
│ └── sax@0.3.5
├─┬ glob@5.0.15
│ ├─┬ inflight@1.0.4
│ │ └── wrappy@1.0.1
│ ├── inherits@2.0.1
│ ├─┬ minimatch@3.0.0
│ │ └─┬ brace-expansion@1.1.2
│ │   ├── balanced-match@0.3.0
│ │   └── concat-map@0.0.1
│ ├── once@1.3.3
│ └── path-is-absolute@1.0.0
├─┬ init-package-json@1.9.1
│ ├─┬ npm-package-arg@4.1.0
│ │ └── hosted-git-info@2.1.4
│ ├── promzard@0.3.0
│ ├─┬ read@1.0.7
│ │ └── mute-stream@0.0.5
│ ├─┬ read-package-json@2.0.2
│ │ ├── graceful-fs@4.1.2
│ │ ├─┬ json-parse-helpfulerror@1.0.3
│ │ │ └── jju@1.2.1
│ │ └─┬ normalize-package-data@2.3.5
│ │   └─┬ is-builtin-module@1.0.0
│ │     └── builtin-modules@1.1.0
│ ├─┬ validate-npm-package-license@3.0.1
│ │ ├─┬ spdx-correct@1.0.2
│ │ │ └── spdx-license-ids@1.1.0
│ │ └─┬ spdx-expression-parse@1.0.2
│ │   └── spdx-exceptions@1.0.4
│ └── validate-npm-package-name@2.2.2
├─┬ istanbul@0.3.22
│ ├── abbrev@1.0.7
│ ├── async@1.5.0
│ ├─┬ escodegen@1.7.1
│ │ ├── esprima@1.2.5
│ │ ├── estraverse@1.9.3
│ │ ├── esutils@2.0.2
│ │ ├─┬ optionator@0.5.0
│ │ │ ├── deep-is@0.1.3
│ │ │ ├── fast-levenshtein@1.0.7
│ │ │ ├── levn@0.2.5
│ │ │ ├── prelude-ls@1.1.2
│ │ │ ├── type-check@0.3.1
│ │ │ └── wordwrap@0.0.3
│ │ └─┬ source-map@0.2.0
│ │   └── amdefine@1.0.0
│ ├── esprima@2.5.0
│ ├─┬ fileset@0.2.1
│ │ └── minimatch@2.0.10
│ ├─┬ handlebars@4.0.5
│ │ ├── async@1.5.0
│ │ ├─┬ optimist@0.6.1
│ │ │ ├── minimist@0.0.10
│ │ │ └── wordwrap@0.0.3
│ │ ├── source-map@0.4.4
│ │ └─┬ uglify-js@2.6.1
│ │   ├── async@0.2.10
│ │   ├── source-map@0.5.3
│ │   ├── uglify-to-browserify@1.0.2
│ │   └─┬ yargs@3.10.0
│ │     ├── camelcase@1.2.1
│ │     ├─┬ cliui@2.1.0
│ │     │ ├─┬ center-align@0.1.2
│ │     │ │ ├─┬ align-text@0.1.3
│ │     │ │ │ ├── kind-of@2.0.1
│ │     │ │ │ ├── longest@1.0.1
│ │     │ │ │ └── repeat-string@1.5.2
│ │     │ │ └── lazy-cache@0.2.4
│ │     │ ├── right-align@0.1.3
│ │     │ └── wordwrap@0.0.2
│ │     ├── decamelize@1.1.1
│ │     └── window-size@0.1.0
│ ├─┬ js-yaml@3.4.6
│ │ ├─┬ argparse@1.0.3
│ │ │ └── sprintf-js@1.0.3
│ │ ├── esprima@2.7.0
│ │ └── inherit@2.2.2
│ ├─┬ mkdirp@0.5.1
│ │ └── minimist@0.0.8
│ ├── resolve@1.1.6
│ ├─┬ supports-color@3.1.2
│ │ └── has-flag@1.0.0
│ ├─┬ which@1.2.0
│ │ └─┬ is-absolute@0.1.7
│ │   └── is-relative@0.1.3
│ └── wordwrap@1.0.0
├─┬ jasmine-node@1.14.5
│ ├── coffee-script@1.10.0
│ ├─┬ gaze@0.3.4
│ │ ├─┬ fileset@0.1.8
│ │ │ └─┬ glob@3.2.11
│ │ │   └── minimatch@0.3.0
│ │ └── minimatch@0.2.14
│ ├─┬ jasmine-growl-reporter@0.0.3
│ │ └── growl@1.7.0
│ ├─┬ jasmine-reporters@1.0.2
│ │ └── mkdirp@0.3.5
│ ├── mkdirp@0.3.5
│ ├── requirejs@2.1.22
│ └── walkdir@0.0.11
├─┬ jshint@2.5.8
│ ├─┬ cli@0.6.6
│ │ └── glob@3.2.11
│ ├─┬ console-browserify@1.1.0
│ │ └── date-now@0.1.4
│ ├── exit@0.1.2
│ ├─┬ htmlparser2@3.8.3
│ │ ├── domelementtype@1.3.0
│ │ ├── domhandler@2.3.0
│ │ ├─┬ domutils@1.5.1
│ │ │ └─┬ dom-serializer@0.1.0
│ │ │   ├── domelementtype@1.1.3
│ │ │   └── entities@1.1.1
│ │ └── entities@1.0.0
│ ├─┬ minimatch@1.0.0
│ │ ├── lru-cache@2.7.3
│ │ └── sigmund@1.0.1
│ ├── strip-json-comments@1.0.4
│ └── underscore@1.6.0
├── nopt@3.0.6
├─┬ npm@2.14.14
│ ├── abbrev@1.0.7
│ ├── ansi@0.3.0
│ ├── ansi-regex@2.0.0
│ ├── block-stream@0.0.8
│ ├─┬ config-chain@1.1.9
│ │ └── proto-list@1.2.4
│ ├── fstream@1.0.8
│ ├─┬ glob@5.0.15
│ │ └── path-is-absolute@1.0.0
│ ├── graceful-fs@4.1.2
│ ├── hosted-git-info@2.1.4
│ ├── inflight@1.0.4
│ ├── inherits@2.0.1
│ ├── ini@1.3.4
│ ├─┬ init-package-json@1.9.1
│ │ └── promzard@0.3.0
│ ├─┬ minimatch@3.0.0
│ │ └─┬ brace-expansion@1.1.1
│ │   └── concat-map@0.0.1
│ ├─┬ mkdirp@0.5.1
│ │ └── minimist@0.0.8
│ ├─┬ node-gyp@3.2.1
│ │ ├─┬ glob@4.5.3
│ │ │ └─┬ minimatch@2.0.10
│ │ │   └─┬ brace-expansion@1.1.2
│ │ │     ├── balanced-match@0.3.0
│ │ │     └── concat-map@0.0.1
│ │ ├─┬ minimatch@1.0.0
│ │ │ └── sigmund@1.0.1
│ │ ├─┬ npmlog@1.2.1
│ │ │ ├─┬ are-we-there-yet@1.0.4
│ │ │ │ └── delegates@0.1.0
│ │ │ └─┬ gauge@1.2.2
│ │ │   ├── has-unicode@1.0.1
│ │ │   ├─┬ lodash.pad@3.1.1
│ │ │   │ ├── lodash._basetostring@3.0.1
│ │ │   │ └─┬ lodash._createpadding@3.6.1
│ │ │   │   └── lodash.repeat@3.0.1
│ │ │   ├─┬ lodash.padleft@3.1.1
│ │ │   │ ├── lodash._basetostring@3.0.1
│ │ │   │ └─┬ lodash._createpadding@3.6.1
│ │ │   │   └── lodash.repeat@3.0.1
│ │ │   └─┬ lodash.padright@3.1.1
│ │ │     ├── lodash._basetostring@3.0.1
│ │ │     └─┬ lodash._createpadding@3.6.1
│ │ │       └── lodash.repeat@3.0.1
│ │ └─┬ path-array@1.0.0
│ │   └─┬ array-index@0.1.1
│ │     └─┬ debug@2.2.0
│ │       └── ms@0.7.1
│ ├── nopt@3.0.6
│ ├─┬ normalize-package-data@2.3.5
│ │ └─┬ is-builtin-module@1.0.0
│ │   └── builtin-modules@1.1.0
│ ├─┬ npm-install-checks@1.0.6
│ │ └─┬ npmlog@1.2.1
│ │   ├─┬ are-we-there-yet@1.0.4
│ │   │ └── delegates@0.1.0
│ │   └─┬ gauge@1.2.2
│ │     ├── has-unicode@1.0.1
│ │     ├─┬ lodash.pad@3.1.1
│ │     │ ├── lodash._basetostring@3.0.1
│ │     │ └─┬ lodash._createpadding@3.6.1
│ │     │   └── lodash.repeat@3.0.1
│ │     ├─┬ lodash.padleft@3.1.1
│ │     │ ├── lodash._basetostring@3.0.1
│ │     │ └─┬ lodash._createpadding@3.6.1
│ │     │   └── lodash.repeat@3.0.1
│ │     └─┬ lodash.padright@3.1.1
│ │       ├── lodash._basetostring@3.0.1
│ │       └─┬ lodash._createpadding@3.6.1
│ │         └── lodash.repeat@3.0.1
│ ├── npm-package-arg@4.1.0
│ ├─┬ npm-registry-client@7.0.8
│ │ ├─┬ concat-stream@1.5.1
│ │ │ ├─┬ readable-stream@2.0.4
│ │ │ │ ├── isarray@0.0.1
│ │ │ │ ├── string_decoder@0.10.31
│ │ │ │ └── util-deprecate@1.0.2
│ │ │ └── typedarray@0.0.6
│ │ └─┬ npmlog@2.0.0
│ │   ├─┬ are-we-there-yet@1.0.4
│ │   │ └── delegates@0.1.0
│ │   └─┬ gauge@1.2.2
│ │     ├── ansi@0.3.0
│ │     ├── has-unicode@1.0.1
│ │     ├─┬ lodash.pad@3.1.1
│ │     │ ├── lodash._basetostring@3.0.1
│ │     │ └─┬ lodash._createpadding@3.6.1
│ │     │   └── lodash.repeat@3.0.1
│ │     ├── lodash.padleft@3.1.1
│ │     └── lodash.padright@3.1.1
│ ├─┬ npmlog@2.0.0
│ │ ├─┬ are-we-there-yet@1.0.4
│ │ │ └── delegates@0.1.0
│ │ └─┬ gauge@1.2.2
│ │   ├── has-unicode@1.0.1
│ │   ├─┬ lodash.pad@3.1.1
│ │   │ ├── lodash._basetostring@3.0.1
│ │   │ └─┬ lodash._createpadding@3.6.1
│ │   │   └── lodash.repeat@3.0.1
│ │   ├─┬ lodash.padleft@3.1.1
│ │   │ ├── lodash._basetostring@3.0.1
│ │   │ └─┬ lodash._createpadding@3.6.1
│ │   │   └── lodash.repeat@3.0.1
│ │   └─┬ lodash.padright@3.1.1
│ │     ├── lodash._basetostring@3.0.1
│ │     └─┬ lodash._createpadding@3.6.1
│ │       └── lodash.repeat@3.0.1
│ ├── opener@1.4.1
│ ├─┬ osenv@0.1.3
│ │ └── os-tmpdir@1.0.1
│ ├─┬ read@1.0.7
│ │ └── mute-stream@0.0.5
│ ├─┬ read-package-json@2.0.2
│ │ └─┬ json-parse-helpfulerror@1.0.3
│ │   └── jju@1.2.1
│ ├─┬ readable-stream@1.1.13
│ │ ├── isarray@0.0.1
│ │ └── string_decoder@0.10.31
│ ├─┬ request@2.65.0
│ │ ├─┬ bl@1.0.0
│ │ │ └─┬ readable-stream@2.0.3
│ │ │   ├── isarray@0.0.1
│ │ │   ├── string_decoder@0.10.31
│ │ │   └── util-deprecate@1.0.2
│ │ ├─┬ form-data@1.0.0-rc3
│ │ │ └── async@1.5.0
│ │ ├─┬ har-validator@2.0.2
│ │ │ └─┬ chalk@1.1.1
│ │ │   ├── ansi-styles@2.1.0
│ │ │   ├── escape-string-regexp@1.0.3
│ │ │   ├── has-ansi@2.0.0
│ │ │   └── supports-color@2.0.0
│ │ ├─┬ http-signature@0.11.0
│ │ │ ├── asn1@0.1.11
│ │ │ ├── assert-plus@0.1.5
│ │ │ └── ctype@0.5.3
│ │ ├── json-stringify-safe@5.0.1
│ │ ├── stringstream@0.0.5
│ │ └── tunnel-agent@0.4.1
│ ├─┬ sha@2.0.1
│ │ └─┬ readable-stream@2.0.2
│ │   ├── isarray@0.0.1
│ │   └── string_decoder@0.10.31
│ ├── spdx-license-ids@1.1.0
│ ├── strip-ansi@3.0.0
│ ├─┬ validate-npm-package-license@3.0.1
│ │ ├── spdx-correct@1.0.2
│ │ └─┬ spdx-expression-parse@1.0.2
│ │   └── spdx-exceptions@1.0.4
│ ├─┬ validate-npm-package-name@2.2.2
│ │ └── builtins@0.0.7
│ ├─┬ which@1.2.0
│ │ └─┬ is-absolute@0.1.7
│ │   └── is-relative@0.1.3
│ └── wrappy@1.0.1
├─┬ npmconf@2.1.2
│ ├─┬ config-chain@1.1.9
│ │ └── proto-list@1.2.4
│ ├── ini@1.3.4
│ └── uid-number@0.0.5
├── opener@1.4.1
├─┬ plist@1.2.0
│ ├── base64-js@0.0.8
│ ├── util-deprecate@1.0.2
│ ├─┬ xmlbuilder@4.0.0
│ │ └── lodash@3.10.1
│ └── xmldom@0.1.19
├── properties-parser@0.2.3
├── q@1.0.1
├─┬ request@2.47.0
│ ├── aws-sign2@0.5.0
│ ├─┬ bl@0.9.4
│ │ └── readable-stream@1.0.33
│ ├── caseless@0.6.0
│ ├─┬ combined-stream@0.0.7
│ │ └── delayed-stream@0.0.5
│ ├── forever-agent@0.5.2
│ ├─┬ form-data@0.1.4
│ │ ├── async@0.9.2
│ │ └── mime@1.2.11
│ ├─┬ hawk@1.1.1
│ │ ├── boom@0.4.2
│ │ ├── cryptiles@0.2.2
│ │ ├── hoek@0.9.1
│ │ └── sntp@0.2.4
│ ├─┬ http-signature@0.10.1
│ │ ├── asn1@0.1.11
│ │ ├── assert-plus@0.1.5
│ │ └── ctype@0.5.3
│ ├── json-stringify-safe@5.0.1
│ ├── mime-types@1.0.2
│ ├── node-uuid@1.4.7
│ ├── oauth-sign@0.4.0
│ ├── qs@2.3.3
│ ├── stringstream@0.0.5
│ ├── tough-cookie@2.2.1
│ └── tunnel-agent@0.4.1
├── rewire@2.1.3
├── semver@4.3.6
├── shelljs@0.3.0
├─┬ tar@1.0.2
│ ├── block-stream@0.0.8
│ └─┬ fstream@1.0.8
│   └── rimraf@2.4.4
├── underscore@1.7.0
├── unorm@1.3.3
├── valid-identifier@0.0.1
└─┬ xcode@0.8.0
  ├── node-uuid@1.3.3
  └── pegjs@0.6.2
```

Second run of `npm install`
```
- ansi@0.3.0 node_modules/ansi
- are-we-there-yet@1.0.4 node_modules/are-we-there-yet
- delegates@0.1.0 node_modules/delegates
- gauge@1.2.2 node_modules/gauge
- has-unicode@1.0.1 node_modules/has-unicode
- lodash._basetostring@3.0.1 node_modules/lodash._basetostring
- lodash._createpadding@3.6.1 node_modules/lodash._createpadding
- lodash.pad@3.1.1 node_modules/lodash.pad
- lodash.padleft@3.1.1 node_modules/lodash.padleft
- lodash.padright@3.1.1 node_modules/lodash.padright
- lodash.repeat@3.0.1 node_modules/lodash.repeat
- npmlog@2.0.0 node_modules/npm/node_modules/npm-registry-client/node_modules/npmlog
cordova-lib@6.0.0-dev /Users/steveng/repo/cordova/cordova-lib/cordova-lib
└─┬ npm@2.14.14
  └── npm-registry-client@7.0.9
```

**Comment by othiym23** [comment]
You have a really unfortunate version of `npm@3.4.1`! You want to get onto `npm@latest` or `npm@next` as soon as possible, because `npm@3.4.1` will sometimes break npm instead of installing itself. Also, I think we may have fixed this in `npm@next`. Give it a shot and let us know how it goes!

**Comment by stevengill** [comment]
haha good to know. Updating to npm@3.5.1 fixed it! Thanks Forrest!
