### ISSUE TITLE
un-deprecating errors.

### ISSUE THREAD

**Issue by jdalton** [npm/npm#10702]
I've tried to [un-deprecate](https://docs.npmjs.com/cli/deprecate) lodash versions because [it may be causing build fails for folks](https://github.com/lodash/lodash/issues/1686)
but I'm running into an error:
```bash
npm deprecate lodash@"<3.0.0||0.5.0-rc.1||<=1.0.0-rc.3" ""
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "deprecate" "lodash@<3.0.0||0.5.0-rc.1||<=1.0.0-rc.3" ""
npm ERR! node v5.1.0
npm ERR! npm  v2.14.11
npm ERR! code E403

npm ERR! "You cannot publish over the previously published version 0.1.0." : lodash
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

This happens in npm@^2.0.0 and npm@^3.0.0.
So I'm stuck at the moment with no way to un-deprecate.

**Comment by jdalton** [comment]
This happens in npm@^2.0.0 and npm@^3.0.0.

**Comment by othiym23** [comment]
Hmm... either my memory is failing me and we never actually fixed this, or there's been. a regression in one of the CLI or the registry. I'm away from a laptop for the moment, but I'll take a look at this once I'm back at a real keyboard.

**Comment by jdalton** [comment]
Cool cool. No worries, I don't want to start a :fire: on a Friday :D

**Comment by jdalton** [comment]
@othiym23 Any updates?

**Comment by soldair** [comment]
i am testing the fix on stage and preparing to release. soon =)

**Comment by KenanY** [comment]
Previously: https://github.com/npm/npm/issues/6867#issuecomment-113275288

**Comment by jdalton** [comment]
@soldair  rock!

**Comment by jdalton** [comment]
secrets!

**Comment by soldair** [comment]
@jdalton please test. my comment in the pr closed this issue early.

**Comment by jdalton** [comment]
@soldair Does this require an npm upgrade?

**Comment by soldair** [comment]
no this fix is on the registry side.

**Comment by jdalton** [comment]
Woot! The command no longer errors and removes the deprecation warnings.

**Comment by jdalton** [comment]
@soldair  I'm getting [the error again](https://github.com/npm/npm/issues/10702#issue-120474244) when I try to undeprecate something.

**Comment by soldair** [comment]
Oh no! ill check what happened in the morning and update. Must need some better tests around this. :)

**Comment by jdalton** [comment]
What's odd it is was working for some but on repeat invocations to clear it thats when I started getting the error. I did repeat invocations to clear it because I noticed an old (from nov) deprecation message showing up. I must have overloaded it with a newer one and when I removed the newer one the old one started showing up.

**Comment by jdalton** [comment]
I've temporarily overloaded it with another until the issue is resolved.
