### ISSUE TITLE
npm ERR! Windows_NT 10.0.10586

### ISSUE THREAD

**Issue by jonathansampson** [npm/npm#10713]
I purchased a new Surface Book, and immediately upgraded to Build 10586 of Windows 10. Afterwards, I downloaded and installed Node.js v5.1.1, and npm v3.3.12. I forked a project, and proceeded to run `npm install`:

```
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.1.1
npm ERR! npm  v3.3.12
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read

npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
```

I'm on my home network (so no proxy), and my connection is strong (170d/20u). I've looked online, and others have reported similar issues, however none of their suggested "solutions" work. Such ideas include changing `registry` to HTTP rather than HTTPS, for instance.

Is this a known issue with 10586? Any additional information I can provide to assist in understanding the root cause?

**Comment by jonathansampson** [comment]
I uninstalled v5.1.1, and installed v4.2.3. The issue persists.

**Comment by bcarroll** [comment]
I am running into this same exact issue with Node.js v5.2.0 and npm v3.5.2

**Comment by raisedadead** [comment]
:+1: 

I am on Node.js v4.2.3 and npm v3.5.2

**Comment by CalvinDale** [comment]
I'm experiencing the same issue with [isomorphic-react-example](https://github.com/DavidWells/isomorphic-react-example).

```
E:\VS\isomorphic-react-example [master]> npm install
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Calvin\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
pm-cli.js" "install"
npm ERR! node v5.3.0
npm ERR! npm  v3.5.2
npm ERR! code E404
...
```

**Comment by ditransler** [comment]
I've the same issue (it was printed right after the [node-sass@3.3.3](https://github.com/sass/node-sass) installation):
```
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
```

**Comment by forl** [comment]
Same issue.

```
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build:webpack"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! react-webpack-node@1.3.3 build:webpack: `NODE_ENV=production webpack --progress --colors --config ./webpack/webpack.config.prod.js`
npm ERR! Exit status 1
```

**Comment by Sophiai** [comment]
I've the same issue 

    npm ERR! Windows_NT 10.0.10586
    npm ERR! argv "H:\\2015nodejs\\node.exe" "H:\\2015nodejs\\node_modules\\npm\\bin\\npm-cli.js"      "install" "-g" "ionic"
    npm ERR! node v5.1.1
    npm ERR! npm  v3.3.12

**Comment by amy6liu** [comment]
I solve it by update nodejs version to v5.4.1

**Comment by Sophiai** [comment]
I solve it by update nodejs version to v5.4.1

**Comment by Sophiai** [comment]
I solve it by update nodejs version to v5.4.1

**Comment by amy6liu** [comment]
update nodejs version to v5.4.1, and change my proxy settings, everything go fine.

**Comment by chirsen** [comment]
with node v5.5.0, npm 3.3.12, vs 2013, from Visual Studio Tools -> Compatible comment prompt, worked.

**Comment by gregoryderner** [comment]
I had the same problem in Windows 10. Resolved using the CMD instead of bash git (MINGW64).
`Node -v [4.4.3]`
`NPM -v [2.15.1]`
It seems to me that the error occurs when we must choose the version of some pkg.

**Comment by ththlisa** [comment]
I have the same issue on my Win 10 with CMD.
but after I updated npm there is a Node,js cdm and it writes:
Your environment has been set up for using Node.js 4.4.4 (x64) and npm.
on the top.
is it means that I already started npm?
just confused with it.

**Comment by bgrayburn** [comment]
same problem when running `npm install` in a repo I made that successfully works on osx and linux machines, node v6.2.0, npm v3.8.9, in a fresh windows10 install in virtualbox. I'm using CMD (NPM wasn't available in MINGW64 (the console that came with the node install)

**Comment by aatifbandey** [comment]
My node js version is 4.4.5 and npm is 2.14.1
i tried in git bash and cmd it throws and error but works fine in Node terminal

**Comment by eyal670** [comment]
I had the same issue
`npm cache clean`  fix it 

link: https://github.com/npm/npm/issues/10826

**Comment by iAmber** [comment]
I uninstalled v5.1.1, and installed v5.8.0. The issue persists.

**Comment by aatifbandey** [comment]
Did u set the environment variable ?

**Comment by huaizhong0095** [comment]
![image](https://cloud.githubusercontent.com/assets/16522701/17882648/47ad53f8-6940-11e6-9fe3-54d96d1be8b7.png)

 the cmd  npm cache clean  still cannot work

**Comment by Santosh-Lodhi** [comment]
I have same issue while installing grunt 

```
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "grunt-cli"
npm ERR! node v5.2.0
npm ERR! npm  v3.3.12
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! syscall connect

npm ERR! network connect ETIMEDOUT 151.101.32.162:443
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Angular\Angular2\Apps\sim-connect\npm-debug.log 
```

**Comment by jatasya** [comment]
for windows : navigate to the node installed folder

D:\Program Files\nodejs>npm cache clean

D:\Program Files\nodejs>npm update
-\|/-\|\|
npm@3.10.6 node_modules\npm|/-\|/\|/-\|/-\/-\|/-\|-\|/\/-/

D:\Program Files\nodejs>npm -v
3.10.6

This solved the issue for me

**Comment by Iuryisalto** [comment]
no windows resolvi assim 
c:\pasta\pasta do arquivo > npm cache clean
[......................................]  (aguarde terminar) 
c:\pasta\pasta do arquivo > npm update 
[......................................] (aguarde terminar)
c:\pasta\pasta do arquivo > npm update -v
veja se esta na ultima versão.
depois tente novamente  a executar o comoando no meu caso era 
c:\pasta\pasta do arquivo > npm install gulp --save-dev

**Comment by zagorodnik** [comment]
```
C:\Users\Alex\WebstormProjects\Angular2>npm start
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! path C:\Users\Alex\WebstormProjects\Angular2\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\Alex\WebstormProjects\Angular2\package.json'
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\Alex\WebstormProjects\Angular2\package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Alex\WebstormProjects\Angular2\npm-debug.log

```

**Comment by KenanY** [comment]
@zagorodnik Your issue looks unrelated to that of the OP. Could you open a new issue instead?

@jonathansampson Is this still an issue for you on the latest stable release of `npm`?

**Comment by adroits** [comment]
Getting the below error while building the Angular 2 application , using angular-cli

steps tried to resolve the issue but still i couldn't resolve the issue :(

npm cache clean - didn't work
disabling firewall - didn't work
uninstall node and install new version - didn't work
upgrade npm to npm3- didn't work
restarted the system - didn't work
now im getting the below error for most of the npm related commands
======================================ERROR=====================
PS C:\xampp\htdocs\angular2> npm start
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "st
rt"
npm ERR! node v6.7.0
npm ERR! npm v3.10.3
npm ERR! path C:\xampp\htdocs\angular2\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\angular2\package.json'
npm ERR! enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\angular2\package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR! C:\xampp\htdocs\angular2\npm-debug.log
PS C:\xampp\htdocs\angular2>
======================================ERROR=====================

Error Log : content of C:\xampp\htdocs\angular2\npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli 'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli 'start' ]
2 info using npm@3.10.3
3 info using node@v6.7.0
4 verbose stack Error: ENOENT: no such file or directory, open 'C:\xampp\htdocs\angular2\package.json'
4 verbose stack at Error (native)
5 verbose cwd C:\xampp\htdocs\angular2
6 error Windows_NT 10.0.10586
7 error argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "start"
8 error node v6.7.0
9 error npm v3.10.3
10 error path C:\xampp\htdocs\angular2\package.json
11 error code ENOENT
12 error errno -4058
13 error syscall open
14 error enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\angular2\package.json'
15 error enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\angular2\package.json'
15 error enoent This is most likely not a problem with npm itself
15 error enoent and is related to npm not being able to find a file.
16 verbose exit [ -4058, true ]

**Comment by KenanY** [comment]
Closing as abandoned. @adroits, ensure that you have a `package.json` in your current directory _before_ running `npm start`. If you have any further issues, please open a new ticket.

**Comment by Prashantneed** [comment]
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\IBM\\node\\node.exe" "C:\\Users\\omadmin\\AppD
ata\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "apiconnec
t"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.8

npm ERR! Callback called more than once.
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\omadmin\npm-debug.log
npm ERR! code 1


Please help me with same. I am trying to install NPM in windows7 but facing with this issue.

Help urgent. My project got stuck.

**Comment by KenanY** [comment]
@Prashantneed Please open a new ticket instead of commenting on one which deals with an issue that is different than your own.

**Comment by ThaiQuocTuan2016** [comment]
ohn, thank you for reporting this issue.
What shell environment are you using (native windows command shell, mingw, cygwin)?
Can you please provide the output of the following two commands:
$ patch -v
$ snyk protect -d # please run it in project folder


We managed to reproduce the issue locally. Please uninstall old version of gnu patch, and use official git tools instead (https://git-scm.com/download/win). Make sure to add the bin folder (C:\Program Files\Git\usr\bin\) to the PATH.
running patch -v should have the following output:

GNU patch 2.7.5
Copyright (C) 2003, 2009-2012 Free Software Foundation, Inc.
Copyright (C) 1988 Larry Wall

License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Larry Wall and Paul Eggert

solver:



C:\Users\Tuan_Pro\Desktop\TTTN\TST\myApp>patch -v
GNU patch 2.7.5
Copyright (C) 2003, 2009-2012 Free Software Foundation, Inc.
Copyright (C) 1988 Larry Wall

License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Larry Wall and Paul Eggert

C:\Users\Tuan_Pro\Desktop\TTTN\TST\myApp>npm install

> mean@0.7.0 postinstall C:\Users\Tuan_Pro\Desktop\TTTN\TST\myApp
> node tools/scripts/postinstall.js

Auto installing package dependencies
bower web-bootstrap#*             copy C:\Users\Tuan_Pro\Desktop\TTTN\TST\myApp\node_modules\meanio\resources\web-bootstrap.js
bower jquery#*                  cached https://github.com/jquery/jquery-dist.git#3.1.1
bower jquery#*                validate 3.1.1 against https://github.com/jquery/jquery-dist.git#*
bower angular#*                 cached https://github.com/angular/bower-angular.git#1.5.8
bower angular#*               validate 1.5.8 against https://github.com/angular/bower-angular.git#*
bower angular-resource#*        cached https://github.com/angular/bower-angular-resource.git#1.5.8
bower angular-resource#*      validate 1.5.8 against https://github.com/angular/bower-angular-resource.git#*
bower angular-cookies#*         cached https://github.com/angular/bower-angular-cookies.git#1.5.8
bower angular-cookies#*       validate 1.5.8 against https://github.com/angular/bower-angular-cookies.git#*
bower angular-route#*           cached https://github.com/angular/bower-angular-route.git#1.5.8
bower angular-route#*         validate 1.5.8 against https://github.com/angular/bower-angular-route.git#*
bower angular-mocks#*           cached https://github.com/angular/bower-angular-mocks.git#1.5.8
bower angular-mocks#*         validate 1.5.8 against https://github.com/angular/bower-angular-mocks.git#*
bower bootstrap#*               cached https://github.com/twbs/bootstrap.git#3.3.7
bower bootstrap#*             validate 3.3.7 against https://github.com/twbs/bootstrap.git#*
bower angular-ui-select#*       cached https://github.com/angular-ui/ui-select.git#0.19.6
bower angular-ui-select#*     validate 0.19.6 against https://github.com/angular-ui/ui-select.git#*
bower angular-ui-router#*       cached https://github.com/angular-ui/angular-ui-router-bower.git#0.3.1
bower angular-ui-router#*     validate 0.3.1 against https://github.com/angular-ui/angular-ui-router-bower.git#*
bower angular-bootstrap#*       cached https://github.com/angular-ui/bootstrap-bower.git#2.2.0
bower angular-bootstrap#*     validate 2.2.0 against https://github.com/angular-ui/bootstrap-bower.git#*
bower angular-sanitize#*        cached https://github.com/angular/bower-angular-sanitize.git#1.5.8
bower angular-sanitize#*      validate 1.5.8 against https://github.com/angular/bower-angular-sanitize.git#*
bower web-bootstrap#*         resolved C:\Users\Tuan_Pro\Desktop\TTTN\TST\myApp\node_modules\meanio\resources\web-bootstrap.js
    Updating Bower dependenciesadata: sill mapToRegistry uri https://registry.npmjs.org/libbase64
mean@0.7.0 C:\Users\Tuan_Pro\Desktop\TTTN\TST\myApp
+-- meanio-admin@0.1.7  (git://github.com/linnovate/meanio-admin.git#0e9d428c67789aadf5615f7d1a109716d3375ad4)
+-- meanio-circles@0.1.1  (git://github.com/linnovate/meanio-circles.git#3fd8e32af3374dcfc34026b7f86e9d332df2b3a6)
+-- meanio-system@0.1.3  (git://github.com/linnovate/meanio-system.git#a1b1b2b35eec858493d3a308e56d1e2014627ed5)
`-- meanio-users@0.1.4  (git://github.com/linnovate/meanio-users.git#b1084c608bbf17e879668e1392a664919151fa42)

    Dependencies installed for package meanStarter

> mean@0.7.0 prepublish C:\Users\Tuan_Pro\Desktop\TTTN\TST\myApp
> npm run snyk-protect


> mean@0.7.0 snyk-protect C:\Users\Tuan_Pro\Desktop\TTTN\TST\myApp
> snyk protect

Successfully applied Snyk patches
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

C:\Users\Tuan_Pro\Desktop\TTTN\TST\myApp>

**Comment by swinn77** [comment]
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\no
nstall" "nativescript"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'internal/fs'
npm ERR!
npm ERR! If you need help, you may report th
npm ERR!     <https://github.com/npm/npm/iss

npm ERR! Please include the following file w
npm ERR!     C:\Users\User\npm-debug.log

**Comment by legodude17** [comment]
@swinn77, please search for you problem on the issue tracker. There have already been issues reported with that problem. 😄

**Comment by Mery4m** [comment]
you will never believe what was the isue for me :p i just forgot to turn on my wamp server (cuz my app is connected to a mysql database :p ). just an advice try to read what is before this line of error..in the CMD console

**Comment by marinhoOliv** [comment]
Hi, take a look here...
https://github.com/npm/npm/issues/14098

**Comment by erdemgunenc** [comment]
I got this issue right now and figured out with 2 way.
1- i added the view at the view folder to package.json start :"index ./bin/www"
2- And i m using mongoose ,i forgot to start mongodb

**Comment by dragon306** [comment]
D:\test\react>npm install react --save
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "react" "--save"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ENOSELF

npm ERR! Refusing to install react as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\test\react\npm-debug.log

I have the same issue.

**Comment by KenanY** [comment]
@dragon306 Your issue looks completely different than that of the original poster. Please open a new issue instead next time.

**Comment by dragon306** [comment]
I reinstall node 4.4.5.
And it worked.

**Comment by dragon306** [comment]
I had the same issue once in the past.
At that time, I used node v6.9.2 but I didn't solve it.
Thanks, @aatifbandey.

**Comment by dragon306** [comment]
Hello, everybody.
I think node v4.4.5 is very comfortable.
Please use it.
Thank you.

**Comment by jahnaviK64** [comment]
I used npm install command to get rid of this issue.

**Comment by chiranjeevisaride** [comment]
Same Issue please help
**node -v v7.5.0
npm -v 4.1.2
NOTE: tried doing "npm cache clean" didn't work**

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v7.5.0
npm ERR! npm v4.1.2
npm ERR! path C:\Users\Chiranjeevi\Desktop\angularJS\ang2\angular2-seed\node_modules.staging\base64id-47d544ab\package.json.1971791659
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\Chiranjeevi\Desktop\angularJS\ang2\angular2-seed\node_modules.staging\base64id-47d544ab\package.json.1971791659' -> 'C:\Users\Chiranjeevi\Desktop\angularJS\ang2\angular2-seed\node_modules.staging\base64id-47d544ab\package.json'
npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\Chiranjeevi\Desktop\angularJS\ang2\angular2-seed\node_modules.staging\base64id-47d544ab\package.json.1971791659' -> 'C:\Users\Chiranjeevi\Desktop\angularJS\ang2\angular2-seed\node_modules.staging\base64id-47d544ab\package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent
npm ERR! Please include the following file with any support request:
npm ERR! C:\Users\Chiranjeevi\Desktop\angularJS\ang2\angular2-seed\npm-debug.log

**Comment by jahnaviK64** [comment]
Make sure you install all the project dependencies through the node commands. Then run "npm install". Then check your package.json file whether it has a list of your dependencies included in it.  Probably your package.json might miss some project dependencies. If you did not have all of them included, try to add it manually.  Then it should work.
Eg of package.json file which has project dependencies: 
"devDependencies": {
    "babel-core": "^6.22.1",
    "babel-eslint": "^6.0.4",
    "babel-plugin-transform-object-rest-spread": "^6.3.13",
    "babel-preset-es2015": "^6.3.13",
    "babel-register": "^6.22.0",
    "babelify": "^7.2.0",
    "browser-sync": "^2.18.7",
    "browserify": "^12.0.1",
    "bulma":"0.3.1",
    "change-case": "^2.3.1",
    "debowerify": "^1.5.0",
    "del": "^2.2.0",
    "gulp": "^3.9.1",
}

**Comment by davodaslanifakor** [comment]
i have similar err ,
i unistall nodejs and inistall agein fix this err

**Comment by shahidkarimi** [comment]
![image](https://cloud.githubusercontent.com/assets/4100920/23182411/44c59cb0-f89a-11e6-9ac1-090b5b6a9252.png)

**Comment by legodude17** [comment]
@shahidkarimi that is a different issue.

**Comment by khalkhaloud** [comment]
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "-g" "nativescript"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! syscall getaddrinfo

npm ERR! network getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     C:\npm-debug.log

i have similar err :(

**Comment by amolbhandari52** [comment]
This issue is fixed when i did npm install -g npm

**Comment by khalkhaloud** [comment]
@amolbhandari52 thnks :)

**Comment by cherndong** [comment]
Brilliant @amolbhandari52 , you saved me! :+1: 

I was struggling with the mentioned issue for 2 days, tried npm upgrade, re-install npm packages, re-install nodejs, solving the proxy, etc until I read your your comment that you made on 26 Apr 2017.

Thank you everyone for spending time sharing the solutions here, thank you for the generosity helping those stuck at work.

**Comment by jaychokshi** [comment]
Bravo @amolbhandari52
