### ISSUE TITLE
Node/npm V5 will not install modules behind proxy. I reverted back to 0.12

### ISSUE THREAD

**Issue by wyattbiker** [npm/npm#10712]
I am behind corporate proxy. I ve tried everything under the sun with flags and configs. (yes i set up the --proxy and --https-proxy). I reverted back to **_0.12**_ and everything works fine.
== **_UPDATE Also works with V4**_ ===
Any ideas?

Here is the message:

Enter node package to install: ws
Enter -g for global install:

```
> bufferutil@1.1.0 install /mnt/mydir/mytest/node_modules/bufferutil
> node-gyp rebuild


gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: unable to verify the first certificate
gyp ERR! stack     at Error (native)
gyp ERR! stack     at TLSSocket.<anonymous> (_tls_wrap.js:1057:38)
gyp ERR! stack     at emitNone (events.js:67:13)
gyp ERR! stack     at TLSSocket.emit (events.js:166:7)
gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:596:8)
gyp ERR! System Linux 2.6.32-573.1.1.el6.x86_64
gyp ERR! command "/mnt/node/bin/node" "/mnt/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /mnt/mydir/mytest/node_modules/bufferutil
gyp ERR! node -v v5.1.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN install:bufferutil@1.1.0 bufferutil@1.1.0 install: `node-gyp rebuild`
npm WARN install:bufferutil@1.1.0 Exit status 1
```

**Comment by Mischi** [comment]
Hi,

does your proxy do SSL inspection? I had a similar looking issue and i temporarily solved it by setting strict-ssl to false. See https://docs.npmjs.com/misc/config#strict-ssl.

Cheer,
Fabian

**Comment by wyattbiker** [comment]
I've tried that too. Same error. I don't know what else to try, Why would it work with 0.12 but not with 5.2.0?

**Comment by othiym23** [comment]
Note that the error message is coming from `node-gyp` and not npm itself. It uses a lot of the same proxy code, because it also uses `request`, but if you can install other than native modules building, then the problem is probably figuring out the right combination of environment variables necessary to make both npm and `node-gyp` work at the same time. Good luck!

**Comment by wyattbiker** [comment]
What are the environment variables I should play with? Could you provide me with a list? Thanks!

**Comment by Bigous** [comment]
Same problem here... all npm versions prior to v5 works behind proxy if you set the variables `http_proxy` and `https_proxy` with the format `http://<user>:<password>@<proxy-server>:<proxy-port>`

v5 gives me the message that `Authentication is needed`:
![image](https://cloud.githubusercontent.com/assets/6886560/26643891/3c9b0fcc-4609-11e7-90d3-f8bb5276acfe.png)
