### ISSUE TITLE
An interface for "embedding" npm

### ISSUE THREAD

**Issue by smikes** [npm/npm#10728]
Several projects (atom, Cordova, ionic) ship a fixed version of npm which is hard for users to upgrade; but when their end users run into known, now-fixed bugs they are directed to this issue tracker, creating a frustrating experience for everyone. 

Proposal: some approved way to override the issue tracker URL and help message in a bundled npm distribution. 

Eg npm tries to require a file called "overrides.js" that is a json file overriding certain strings.  Failing to find the file is not an error. 

Once this is supported I could create PRs for the projects that use a bundled npm, so that when they (eventually) update their npm, this will mitigate the frustration.

**Comment by zkat** [comment]
This seems like it would be pretty neat for one of the consumers of such a feature to implement and submit patches for, but we don't have this anywhere in our radar for the next year, so I'll be closing this.

But seriously. Patches would be great <3
