### ISSUE TITLE
npm install - error

### ISSUE THREAD

**Issue by VitorSousaCode** [npm/npm#10722]
I'm getting this error when trying to fix dependencies using npm install:

```
npm ERR! Linux 3.16.0-50-generic
npm ERR! argv "/home/vitorcode/local/bin/node" "/home/vitorcode/local/bin/npm" "install"
npm ERR! node v4.1.1
npm ERR! npm  v3.3.4

npm ERR! shasum check failed for /tmp/npm-27320-bcdba85d/registry.npmjs.org/cloudant/-/cloudant-1.4.0.tgz
npm ERR! Expected: c32ce2eab4b2c2454171494e607f79ef77922247
npm ERR! Actual:   68ff19768e89bacc7d70b056e0f7a2d0c04749f9
npm ERR! From:     https://registry.npmjs.org/cloudant/-/cloudant-1.4.0.tgz
```

**Comment by KenanY** [comment]
@VitorSousaCode Have you tried running `npm cache clean`?

**Comment by othiym23** [comment]
I would also suggest upgrading to a newer version of npm – the latest stable version is `npm@3.5.2`, and there have been a number of important fixes made to it since `npm@3.3.4`.

**Comment by KenanY** [comment]
@VitorSousaCode Are you still seeing this issue?

**Comment by VitorSousaCode** [comment]
Thanks for helping,that´s solved now.
Best regards...

**Comment by KenanY** [comment]
Closing as resolved :)
