### ISSUE TITLE
npm@3 progress indicator is not... visually pleasing

### ISSUE THREAD

**Issue by shellscape** [npm/npm#10726]
Taking into consideration that we all have preferences on what is pleasing to the eye, I don't want to call it one thing or another, but simply say that I find myself among several peers that agree that it's not the most pleasing presentation to hit the eye.

I've no doubt that they current UX for this feature was carefully considered and chosen. However, it would be grand to be able to instruct npm to use a different format or character set for the progress indicator. While this may not be a critical issue by any means, oodles of popular modules out there have gorgeous output - it's not unreasonable to ask that the flagship module be the leader there. This would also allow Windows users that have the perpetual unicode issue to reassign characters to non-unicode, when there is no hope of resolution.

If this would be a welcomed change, I'd be happy to lend a hand with a PR

**Comment by Martinspire** [comment]
Agreed. Doesn't really look that great. I think that using color would also help a bit. But especially the loading-animation itself (not the progressbar) is pretty useless

**Comment by zkat** [comment]
There's not much here that's actionable -- You can submit pull requests over at https://github.com/iarna/gauge or check the issues there. You could even just submit mockups of something that would look better. Thanks for your time!

**Comment by shellscape** [comment]
@zkat closing this ticket was premature. you pointed us to the module that npm is now using, and that's fantastic, but npm allows no means of customization of that module's use, out of the box. this issue should be reopened to address that. I covered that request in the OP. Please use more caution before closing tickets, and kindly reopen this one.

**Comment by othiym23** [comment]
@shellscape, @zkat closed this issue at my request, and for the reasons she stated. `gauge` is the package npm uses for its scrollbar, and there's a decent discussion happening there on how to improve it. This issue, as it was written, was neither a bug nor a feature request, and evaluations of the progress bar's attractiveness are subjective.

> but npm allows no means of customization of that module's use 

I know of relatively few tools that allow you to customize the look or feel of progress bars, and I don't feel that adding that functionality is the best use of the CLI team's time. If there are specific changes you'd like to see happen, patches are always welcome, but also keep in mind that @iarna is in the process of figuring out what the next version of gauge will look like, so participating in the discussion over there would be an excellent prelude to proposing patches to npm itself.

**Comment by yiakwy** [comment]
@zkat Hi, how can I set theme for my own usage?
