### ISSUE TITLE
ENOENT Error

### ISSUE THREAD

**Issue by underfrog** [npm/npm#10723]
Hi, I get these errors on running tests.
When I try and create
`C:\Data\Repo\trunk\XXX\src\Core\Ux\test\node_modules\phantomjs2\lib\phantomjs\bin\phantomjs`
it just gets deleted.

`Running tests for debugging (no junit / coverage reports)

npm WARN package.json test@0.0.1 No repository field.
npm WARN package.json test@0.0.1 No README data
npm WARN package.json policyfile@0.0.4 'repositories' (plural) Not supported. Pl
ease pick one as the 'repository' field
npm ERR! Error: ENOENT: no such file or directory, chmod 'C:\Data\Repo\trunk\XXX\src\Core\Ux\test\node_modules\phantomjs2\lib\phantomjs\bin\phantomjs'
npm ERR!     at Error (native)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\ProgramData\\chocola
tey\\lib\\npm\\tools\\node_modules\\npm\\bin\\npm-cli.js" "install" "--msvs_vers
ion=2013"
npm ERR! cwd C:\Data\Repo\trunk\XXX\src\Core\Ux\test
npm ERR! node -v v5.1.1
npm ERR! npm -v 1.4.9
npm ERR! path C:\Data\Repo\trunk\XXX\src\Core\Ux\test\node_modules\phantom
js2\lib\phantomjs\bin\phantomjs
npm ERR! syscall chmod
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Data\Repo\trunk\XXX\src\Core\Ux\test\npm-debug.log
npm ERR! not ok code 0
'C:\Data\Repo\trunk\XXX\src\Core\Ux\test\node_modules\.bin\karma' is not r
ecognized as an internal or external command,
operable program or batch file.`

**Comment by KenanY** [comment]
@underfrog Does this also occur on [newer versions](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows) of npm?

**Comment by underfrog** [comment]
I've updated to the latest. Now getting:

which@1.0.9 node_modules\karma-phantomjs-launcher\node_modules\phantomjs\node_mo
dules\which -> node_modules\phantomjs2\node_modules\which
progress@1.1.8 node_modules\karma-phantomjs-launcher\node_modules\phantomjs\node
_modules\progress -> node_modules\progress
throttleit@0.0.2 node_modules\karma-phantomjs-launcher\node_modules\phantomjs\no
de_modules\request-progress\node_modules\throttleit -> node_modules\throttleit
request-progress@0.3.1 node_modules\karma-phantomjs-launcher\node_modules\phanto
mjs\node_modules\request-progress -> node_modules\request-progress
- phantomjs node_modules\karma-phantomjs-launcher\node_modules\phantomjs
test@0.0.1 C:\Data\Repo\trunk\XXX\src\Core\Ux\test
├── fs-extra@0.23.1  extraneous
├─┬ karma@0.12.37
│ ├─┬ chokidar@1.4.0
│ │ └─┬ readdirp@2.0.0
│ │   └── graceful-fs@4.1.2
│ ├─┬ glob@5.0.15
│ │ └── inflight@1.0.4
│ └─┬ log4js@0.6.29
│   └─┬ readable-stream@1.0.33
│     ├── isarray@0.0.1
│     └── string_decoder@0.10.31
├─┬ karma-js-coverage@0.2.3
│ └─┬ dateformat@1.0.12
│   └─┬ meow@3.6.0
│     └─┬ read-pkg-up@1.0.1
│       └─┬ read-pkg@1.1.0
│         ├─┬ load-json-file@1.1.0
│         │ └── graceful-fs@4.1.2
│         └─┬ path-type@1.1.0
│           └── graceful-fs@4.1.2
├── npmconf@2.1.1  extraneous
├── UNMET PEER DEPENDENCY phantomjs@>=1.9
└── request@2.42.0  extraneous

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fseve
nts@1.0.5
npm WARN enoent ENOENT: no such file or directory, open 'C:\Data\Repo\trunk\XXX\src\Core\Ux\test\node_modules\New folder\package.json'
npm WARN karma-phantomjs-launcher@0.2.1 requires a peer of phantomjs@>=1.9 but n
one was installed.
npm WARN test@0.0.1 No repository field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "--msvs_version=2013"
npm ERR! node v5.1.1
npm ERR! npm  v3.5.2
npm ERR! path C:\Data\Repo\trunk\XXX\src\Core\Ux\test\node_modules\karma-p
hantomjs-launcher\node_modules\phantomjs\node_modules\.bin\which.cmd
npm ERR! code EEXIST

npm ERR! Refusing to delete C:\Data\Repo\trunk\XXX\src\Core\Ux\test\node_m
odules\karma-phantomjs-launcher\node_modules\phantomjs\node_modules\.bin\which.c
md: ..\which\bin\which symlink target is not controlled by npm C:\Data\Repo\trun
k\XXX\src\Core\Ux\test\node_modules\karma-phantomjs-launcher\node_modules\
phantomjs\node_modules\which
npm ERR! File exists: C:\Data\Repo\trunk\XXX\src\Core\Ux\test\node_modules
\karma-phantomjs-launcher\node_modules\phantomjs\node_modules\.bin\which.cmd
npm ERR! Move it away, and try again.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Data\Repo\trunk\XXX\src\Core\Ux\test\npm-debug.log
'C:\Data\Repo\trunk\XXX\src\Core\Ux\test\node_modules\.bin\karma' is not r
ecognized as an internal or external command,
operable program or batch file.

**Comment by underfrog** [comment]
I've spent hours on this, installed, uninstalled and reinstalled node etc until I found out my version of node was too recent for my setup. I had to downgrade to a much older node to get it working.
Thanks
