### ISSUE TITLE
Add option to hide summary output from npm install

### ISSUE THREAD

**Issue by ChrisPearce** [npm/npm#10732]
When executing npm install or npm uninstalll, the commands output a summary of all the package dependencies that were installed/uninstalled.

This seems to occur even if the log level is explicitly set to --silent.

This output can be quite verbose. When dealing with large build flows, this output can quickly become unwieldy - making important warnings/errors harder to find quickly.

It would be very helpful to have an option where this summary output could be disable.

A suggestion made as part of recent discussions in #2040 was to provide a --no-summary flag (or something similar). I've created this issue so that the suggestion can be tracked/discussed separately.

**Comment by zarko-tg** [comment]
You're the man @ChrisPearce!

**Comment by xtoddx** [comment]
Making `--silent` work as expected would be preferable to adding yet another flag.

It seems that currently `--silent` is only a proxy for `--loglevel silent`, but making silent also set progress=false and disabling the summary output would be fan-tastic!

**Comment by uglow** [comment]
+1
I'm running tests on TravisCI and 800 lines of my 900-line log are the summary info. I'm using Node 5.4.0. I'd prefer that `--verbose` turns on the tree-summary.

**Comment by zkat** [comment]
Leaving this open for now as we very much intend to change this output of `npm install`, but we don't know what that looks like yet or when we'll do it.

**Comment by stevage** [comment]
Ok, since my other issue was closed, I just want to make clear that I don't think the solution is "add an option to hide summary output", but to never show that spam. I suggested:

> `900 packages installed. Run 'npm list' for details.`

IMHO, the current situation is pretty badly broken: 900 lines of output for me, with no way to disable it, and shown even when `--loglevel silent` is enabled.

**Comment by othiym23** [comment]
I've gone back and forth on this a number of times due to the historical legacy of this command and its output being part of the "CLI API contract", but recently we've been more in a mode of "set fire to the past and all who sailed it" and I think that especially given the complexity of the average install, it no longer makes sense for us to be printing the full logical tree or set of changes on install. Instead, we'd like to have a simple summary line like `apt-get`'s where we provide statistics like the number of packages added and removed, the size change of the install, and the duration of the install (even though that's probably just going to make people yell at us until we get more work done on `npm@3`'s performance).

So! The npm CLI team will take this on sometime within the next year, but if somebody wants to take a stab at patching this before we get to it, start the PR _early_, because the team are likely to have strong opinions about the user experience.

**Comment by billinghamj** [comment]
Okay, so until this issue is actually fixed, how can we disable all non-essential output? (Essential meaning warnings and errors.)

Given how long it has been since this issue was first raised, some kind of stopgap solution seems appropriate...

**Comment by arei** [comment]
I know it's super hacky but as a work around to this if you are using npm programmatically (like `npmbox` does) here's how to get around this since there is no other way to suppress this output...

```
var cl = console.log;
console.log = function() {};
npm.commands.install(source,function() {
	console.log = cl;
	callback.apply(this,arguments);
});
```

YMMV.

**Comment by billinghamj** [comment]
I have posted this in the PR too, but I think it's worth repeating here:

Is this going to be resolved in npm@4? I think it's really important to get this fixed **before** npm@4 is released, so this doesn't have to wait until npm@5...

**Comment by matgardon** [comment]
@billinghamj  late answer but in the meantime, you can reduce the level of the dependency tree in the output by using [--depth](https://github.com/npm/npm/issues/2040#issuecomment-166425140), this enables you to keep only first level dependencies displayed. 

Also in the ticket I refer too, some people suggest redirecting everything to dev/ null, but that means also hidding essential error & warn messages if any, so I don't recommend this workaround.

**Comment by lethom** [comment]
As for myself, I do not understand the logic of npm regarding stdout and stderr. From my understanding, npm just prints everything in stderr, which is strange as stderr is supposed to be used for, well, error reporting.

In fact, I think `npm install > /dev/null` should only print error and warning. No?

**Comment by sanmai-NL** [comment]
@lethom: ‘error’ is a bit of a misnomer. Standard error is best used for any human-readable _diagnostics_, i.e. output not meant to be consumed by programs through e.g. a pipe. This [Wikipedia] descriptions sheds some light (https://en.wikipedia.org/wiki/Standard_streams#Standard_error_.28stderr.29) .

**Comment by joeyparrish** [comment]
This seems to still be an issue with npm 4.0.2.  My build server needs to install deps, and if that fails, I want to see it in the logs and know why.  If it works, I really don't need to see a giant tree of dependencies.

There doesn't seem to be any way to separate the two.  I can redirect all output to /dev/null and have no way to diagnose a failure, or I can have my build log flooded with a deps tree so I have to scroll a bunch to find any real test failures.

I'm considering writing a silly amount of bash script to work around this in my build bot, but that should really not be necessary.

**Comment by RobinKnipe** [comment]
@joeyparrish - I've had to do something like the following:
```bash
npm i > ./build.log 2>&1 || ( EC=$?; cat ./build.log; exit $EC )
```

**Comment by joeyparrish** [comment]
If there are no objections, I will create a pull request to silence the tree when using `--loglevel error` or `--loglevel silent`.  I think it's fair to say anyone using those two settings does not want to see the tree at the end.

**Comment by billinghamj** [comment]
I'm pretty certain that PR would not be accepted. They consider it to be part of the NPM "contract" (lol)

**Comment by joeyparrish** [comment]
I would argue that `--loglevel` is a stronger contract.  If we can agree that there should be no output with `--loglevel silent` and only errors output with `--loglevel error`, we can keep the default behavior (show the tree, since the default level is `warn`), keep the CLI output contract, and satisfy everyone using `npm install` in automation (where `--loglevel error` makes a lot of sense).

**Comment by billinghamj** [comment]
I completely agree with you - I think npm's stance on this is incredibly stupid. But ultimately that's what they'll say. The npm "CLI API contract" is very strictly managed and they won't break it with any existing flag. See here: https://github.com/npm/npm/issues/10732#issuecomment-173386056

**Comment by mbana** [comment]
for anyone who wants `npm` to do the *right* thing, run the below.
it's very strange that this is the default. it's enforcing the special case - printout the debug out, at least the way i see it - when one only wants to do an install.
maybe an alternative is to only do verbose output when as `PROD`.

anywho, very strange...

---
backup old files, then set defaults, then bring new settings into terminal:
```sh
( \
  (touch $HOME/.npmrc) && \
  (touch $HOME/.bash_profile) && \
  (cp $HOME/.npmrc .npmrc_old) && \
  (cp $HOME/.bash_profile .bash_profile) && \
  (echo -e \
"loglevel=warn"\
"\n"\
"progress=false" \
    >> $HOME/.npmrc) && \
  (echo 'alias npm="npm -s"' >> $HOME/.bash_profile) \
) && source ~/.bash_profile . && type npm
```

**Comment by caseyallenshobe** [comment]
So why not do the same as similar package managing systems such as Gentoo's `emerge` utility?  Output interactive, colorized output with spinning characters, progress bars, and whatnot when executed by a human in a terminal window, and output plain, non-interactive lines (or lack thereof entirely when using an appropriate argument) when called from a script?  Also allow for a manual override either way via an argument.  Moreover, using `--silent` is NOT advisable, as it suppresses errors.  Redirection of `stderr` to `/dev/null` should always be enough to suppress **ALL OUTPUT** except errors, and likewise, I'd expect the same of `--quiet` (which thankfully, does not suppress errors).

I need to be able to `npm install` something, without seeing anything at all unless the installation is unsuccessful.  `npm` is in a minuscule group of "special" applications that don't honor this standard, and alone in the realm of package managers in this regard.

**Comment by rex** [comment]
You know those times you scroll down through a big thread trying to get to the epic solution at the bottom where everyone lives happily ever after and there **is no solution**? 

Yeah, this is one of those times.

Just another strong argument to go to Yarn. 

Yarn
---

**9 lines, 320 characters** 
![screenshot 2017-03-07 15 42 04](https://cloud.githubusercontent.com/assets/4247754/23679285/12c69b8e-034d-11e7-9f9a-24910ddf3a92.png)


```yarn install v0.21.3
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning electron > electron-download > nugget > progress-stream > through2 > xtend > object-keys@0.4.0:
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
✨  Done in 3.25s.
```


NPM
---


**450 lines, 13317 characters**
![screenshot 2017-03-07 15 41 46](https://cloud.githubusercontent.com/assets/4247754/23679249/ee49d686-034c-11e7-9706-e0e739462be3.png)

```/usr/local/bin/build -> /usr/local/lib/node_modules/electron-builder/out/cli/build-cli.js
/usr/local/bin/install-app-deps -> /usr/local/lib/node_modules/electron-builder/out/cli/install-app-deps.js
/usr/local/bin/node-gyp-rebuild -> /usr/local/lib/node_modules/electron-builder/out/cli/node-gyp-rebuild.js
/usr/local/bin/electron-packager -> /usr/local/lib/node_modules/electron-packager/cli.js
/usr/local/lib
├─┬ electron-builder@15.1.1
│ ├─┬ 7zip-bin@2.0.4
│ │ └── 7zip-bin-linux@1.0.3
│ ├─┬ ajv@5.0.3-beta.0
│ │ ├── co@4.6.0
│ │ └─┬ json-stable-stringify@1.0.1
│ │   └── jsonify@0.0.0
│ ├── ajv-keywords@2.0.1-beta.1
│ ├─┬ bluebird-lst@1.0.1
│ │ └── bluebird@3.5.0
│ ├─┬ chalk@1.1.3
│ │ ├── ansi-styles@2.2.1
│ │ ├── escape-string-regexp@1.0.5
│ │ ├─┬ has-ansi@2.0.0
│ │ │ └── ansi-regex@2.1.1
│ │ ├── strip-ansi@3.0.1
│ │ └── supports-color@2.0.0
│ ├── chromium-pickle-js@0.2.0
│ ├── cuint@0.2.2
│ ├── electron-builder-core@13.6.0
│ ├─┬ electron-builder-http@15.0.1
│ │ └─┬ debug@2.6.1
│ │   └── ms@0.7.2
│ ├─┬ electron-builder-util@15.0.1
│ │ ├── ini@1.3.4
│ │ ├─┬ node-emoji@1.5.1
│ │ │ └── string.prototype.codepointat@0.2.0
│ │ ├─┬ source-map-support@0.4.11
│ │ │ └── source-map@0.5.6
│ │ ├── stat-mode@0.2.2
│ │ └─┬ tunnel-agent@0.6.0
│ │   └── safe-buffer@5.0.1
│ ├─┬ electron-download-tf@4.0.0
│ │ ├─┬ fs-extra@2.0.0
│ │ │ ├── graceful-fs@4.1.11
│ │ │ └── jsonfile@2.4.0
│ │ ├── minimist@1.2.0
│ │ ├─┬ nugget@2.0.1
│ │ │ ├─┬ pretty-bytes@1.0.4
│ │ │ │ ├── get-stdin@4.0.1
│ │ │ │ └─┬ meow@3.7.0
│ │ │ │   ├─┬ camelcase-keys@2.1.0
│ │ │ │   │ └── camelcase@2.1.1
│ │ │ │   ├─┬ loud-rejection@1.6.0
│ │ │ │   │ ├─┬ currently-unhandled@0.4.1
│ │ │ │   │ │ └── array-find-index@1.0.2
│ │ │ │   │ └── signal-exit@3.0.2
│ │ │ │   ├── map-obj@1.0.1
│ │ │ │   ├── object-assign@4.1.1
│ │ │ │   ├─┬ redent@1.0.0
│ │ │ │   │ ├─┬ indent-string@2.1.0
│ │ │ │   │ │ └─┬ repeating@2.0.1
│ │ │ │   │ │   └── is-finite@1.0.2
│ │ │ │   │ └── strip-indent@1.0.1
│ │ │ │   └── trim-newlines@1.0.0
│ │ │ ├─┬ progress-stream@1.2.0
│ │ │ │ ├── speedometer@0.1.4
│ │ │ │ └─┬ through2@0.2.3
│ │ │ │   ├─┬ readable-stream@1.1.14
│ │ │ │   │ ├── core-util-is@1.0.2
│ │ │ │   │ ├── inherits@2.0.3
│ │ │ │   │ ├── isarray@0.0.1
│ │ │ │   │ └── string_decoder@0.10.31
│ │ │ │   └─┬ xtend@2.1.2
│ │ │ │     └── object-keys@0.4.0
│ │ │ ├─┬ request@2.80.0

###----    379 Lines Clipped    ----###
```

**Comment by legodude17** [comment]
This should be fixed soon with #15914.

**Comment by the1mills** [comment]
Omg yes

**Comment by MitchK** [comment]
Bump, same. I don't even see a good reason of printing the whole tree

**Comment by legodude17** [comment]
That PR was merged in with `npm@5`. Update there to get the brand new install message.
