### ISSUE TITLE
My bot is offline help!

### ISSUE THREAD

**Issue by csgohero** [npm/npm#10745]
help me, i suck at programming. 

add me on steam! http://steamcommunity.com/id/botdanni/inventory/

**Comment by KenanY** [comment]
Hello @csgohero! Is the issue specific to `npm`? If not, then I think you will have a slightly higher chance of finding help elsewhere, such as on StackOverflow (although, if you provide someone else as little information as you have provided here, it will be virtually impossible for them to help you). Good luck with the bot :)

**Comment by othiym23** [comment]
Closing as not an npm issue. Good luck getting things sorted out with your bot, @csgohero!
