### ISSUE TITLE
Broken link in docs

### ISSUE THREAD

**Issue by neilstuartcraig** [npm/npm#10749]
Hi all

Just noticed a broken link in docs on the [prune](https://docs.npmjs.com/cli/prune) (in the "See also" list) page - the [rm](https://docs.npmjs.com/cli/rm) link is broken (404). Can't see an obvious problem but i'm sure you'll know what needs doing.

Cheers

**Comment by KenanY** [comment]
This should have been fixed by https://github.com/npm/npm/pull/10419; just needs to be deployed I guess.

**Comment by othiym23** [comment]
Hmm... it should be live by now; we may have skipped the CLI docs deploy last week. I'll take a look. Thanks for the nudge, @KenanY!

**Comment by KenanY** [comment]
Looks fixed now :smiley:

**Comment by bigtone1284** [comment]
Has this been fixed, if so, can it be closed?

**Comment by othiym23** [comment]
Closing as resolved.
