### ISSUE TITLE
npm install fills up terminal a lot

### ISSUE THREAD

**Issue by aayushkapoor206** [npm/npm#10748]
A lot of information about the ongoing process gets shown and becomes very noisy. Is there a way to turn it off?

**Comment by KenanY** [comment]
@aayushkapoor206 Have you tried configuring the [`loglevel`](https://docs.npmjs.com/misc/config#loglevel)?

**Comment by aayushkapoor206** [comment]
Even without any warnings and errors. Printing the complete tree of dependencies and showing the output for node-gyp.

**Comment by KenanY** [comment]
@aayushkapoor206 If you want to hide the dependency tree, you can pipe the output elsewhere like so (assuming *nix):

``` bash
$ npm install &>/dev/null
```

(from https://github.com/npm/npm/issues/2040)

or ask that a new flag be added to specifically hide it: https://github.com/npm/npm/issues/10732.

**Comment by codename-** [comment]
@KenanY - but that redirection could hide a real error output, so it's a really bad idea :-1:

**Comment by KenanY** [comment]
@codename- Right! That's why I personally don't do things like that and in fact I even have `loglevel` set to `http` so I get way more output than most people are getting by default nowadays. It lets me know that `npm` is working :)

**Comment by legodude17** [comment]
This should be fixed soon with #15914.
