### ISSUE TITLE
npm ERR!

### ISSUE THREAD

**Issue by ifgyong** [npm/npm#10740]
```
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.1.1
npm ERR! npm  v3.3.12
npm ERR! path /Users/Jerry/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/Users/Jerry/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Jerry/npm-debug.log
```

this is log

wait onlien ..
who can help me??

**Comment by KenanY** [comment]
Hello @ifgyong! You do not have a `package.json` in your current directory, but one is necessary for `npm start` to work. Perhaps the [`npm start` documentation](https://docs.npmjs.com/cli/start) and the general `npm` [scripts documentation](https://docs.npmjs.com/misc/scripts) could help you out?

**Comment by othiym23** [comment]
I believe that @KenanY has provided enough information to resolve this issue. @ifgyong, let us know if you're still having issues and we can reopen it, or otherwise answer your questions.
