### ISSUE TITLE
npm ERR! version not found: mongodb@3.0.7

### ISSUE THREAD

**Issue by Srini2** [npm/npm#10755]
I have installed mongo DB version 3.0.7 and I am trying to connect through my node JS script.
I have created package.json file  as ..

``` json
{
  "dependencies": {
    "mongodb": "3.0.7"
  }
}
```

I have a index.js file for connecting to mongodb.
when I run npm install...I am getting the following error.

```
npm ERR! version not found: mongodb@3.0.7
```

npm install

```
npm WARN package.json @ No description
npm WARN package.json @ No repository field.
npm WARN package.json @ No README data
npm WARN package.json @ No license field.
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.1.2
npm ERR! npm  v2.14.4
npm ERR! version not found: mongodb@3.0.7
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

Appreciate any help on this..

Thx

**Comment by TylerL-uxai** [comment]
Having this same issue

**Comment by cobranacho** [comment]
You might be confusing the version of the mongodb databse 3.0.7 with the npm mongodb driver that is used by node.js to communicate with the actual database.  If you look at https://www.npmjs.com/package/mongodb , you will see that the last version is 2.1.7, so npm will complain that 3.0.7 is not found.  Change to 2.1.7 in your dependency.
