### ISSUE TITLE
npm3 can't handle a symlink to `..` at the root of node_modules

### ISSUE THREAD

**Issue by davidbanham** [npm/npm#10752]
On our nodeJS projects we often like to have a symlink called `root` in the `node_modules` folder.

This is a neat trick, since when you're requiring files from elsewhere in your project, you never need to `require('../../../foo.js');`. Instead, you just `require('root/libs/foo.js');`

This works because node looks first in the node_modules folder for a dir called `root`. It finds it! So it looks within for the files it's after.

We find this really useful as it allows you to move files around the project without needing to change their relative paths. If you're nested deep you don't need to count how many folders you need to traverse up, etc.

Sadly, npm3 totally breaks this behaviour. I've set up a repro here:

[https://github.com/davidbanham/rooted_symlinks](https://github.com/davidbanham/rooted_symlinks)

And it's running on Travis so you can see the behaviour against different versions:

[https://travis-ci.org/davidbanham/rooted_symlinks](https://travis-ci.org/davidbanham/rooted_symlinks)

It seems to ignore any module which can be reached through a symlink as part of it's de-duping process. In a project where someone has run `ln -s .. node_modules/root` that's every single module. Oh dear!

**Comment by FluffyJack** [comment]
:+1:

**Comment by moll** [comment]
Any news on this? Still an issue?

**Comment by moll** [comment]
I'm certainly still interested in this. @davidbanham, have you tried the latest NPM ver?

**Comment by davidbanham** [comment]
It looks like it was actually fixed with node versions 6 and 7, then broken in a new and exciting way with node 8.

https://travis-ci.org/davidbanham/rooted_symlinks/builds/244734697

It looks like yarn behaves correctly across all versions:

https://travis-ci.org/davidbanham/rooted_symlinks/builds/244736034

**Comment by davidbanham** [comment]
Issue reopened as #17330
