### ISSUE TITLE
NPM publish not working

### ISSUE THREAD

**Issue by TMonika** [npm/npm#10756]
#npm publish

npm ERR! publish Failed PUT 403
npm ERR! Linux 3.16.0-30-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "publish"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code E403

npm ERR! You do not have permission to publish 'replace'. Are you logged in as the correct user? : replace
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/monika/Documents/Monika/Node_Practice/gitNode/node-practice/npm-debug.log

npm-debug.log:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'publish' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose publish [ '.' ]
5 silly cache add args [ '.', null ]
6 verbose cache add spec .
7 silly cache add parsed spec { raw: '.',
7 silly cache add   scope: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: '.',
7 silly cache add   spec: '/home/monika/Documents/Monika/Node_Practice/gitNode/node-practice',
7 silly cache add   type: 'directory' }
8 verbose addLocalDirectory /root/.npm/replace/1.1.1/package.tgz not in flight; packing
9 verbose tar pack [ '/root/.npm/replace/1.1.1/package.tgz',
9 verbose tar pack   '/home/monika/Documents/Monika/Node_Practice/gitNode/node-practice' ]
10 verbose tarball /root/.npm/replace/1.1.1/package.tgz
11 verbose folder /home/monika/Documents/Monika/Node_Practice/gitNode/node-practice
12 info prepublish replace@1.1.1
13 verbose addLocalTarball adding from inside cache /root/.npm/replace/1.1.1/package.tgz
14 silly cache afterAdd replace@1.1.1
15 verbose afterAdd /root/.npm/replace/1.1.1/package/package.json not in flight; writing
16 verbose afterAdd /root/.npm/replace/1.1.1/package/package.json written
17 silly publish { author: { name: 'Monika' },
17 silly publish   name: 'replace',
17 silly publish   version: '1.1.1',
17 silly publish   description: 'Replaces words from string',
17 silly publish   main: 'replacestring',
17 silly publish   dependencies: {},
17 silly publish   repository: { type: 'git', url: 'https://github.com/TMonika/node-practice' },
17 silly publish   keywords: [ 'censor', 'words' ],
17 silly publish   engines: { node: '*' },
17 silly publish   readme: '# node-practice\nMy first repository for practising node\n',
17 silly publish   readmeFilename: 'README.md',
17 silly publish   gitHead: '76d840b87e201088cd8724fcabe77e404cbf338c',
17 silly publish   bugs: { url: 'https://github.com/TMonika/node-practice/issues' },
17 silly publish   homepage: 'https://github.com/TMonika/node-practice',
17 silly publish   _id: 'replace@1.1.1',
17 silly publish   scripts: {},
17 silly publish   _shasum: '0c965f96f2fb5730327fecca97e0832a3fe9f24f',
17 silly publish   _from: '.' }
18 silly mapToRegistry name replace
19 silly mapToRegistry using default registry
20 silly mapToRegistry registry https://registry.npmjs.org/
21 silly mapToRegistry uri https://registry.npmjs.org/replace
22 verbose publish registryBase https://registry.npmjs.org/
23 silly publish uploading /root/.npm/replace/1.1.1/package.tgz
24 verbose request uri https://registry.npmjs.org/replace
25 verbose request sending authorization for write operation
26 info attempt registry request try #1 at 10:37:30 AM
27 verbose request using bearer token for auth
28 verbose request id 42cf3d3e5c1eaf2d
29 http request PUT https://registry.npmjs.org/replace
30 http 403 https://registry.npmjs.org/replace
31 verbose headers { 'content-type': 'application/json',
31 verbose headers   'cache-control': 'max-age=60',
31 verbose headers   'content-length': '99',
31 verbose headers   'accept-ranges': 'bytes',
31 verbose headers   date: 'Wed, 09 Dec 2015 05:07:31 GMT',
31 verbose headers   via: '1.1 varnish',
31 verbose headers   connection: 'keep-alive',
31 verbose headers   'x-served-by': 'cache-sin6921-SIN',
31 verbose headers   'x-cache': 'MISS',
31 verbose headers   'x-cache-hits': '0',
31 verbose headers   'x-timer': 'S1449637651.157324,VS0,VE805' }
32 verbose request invalidating /root/.npm/registry.npmjs.org/replace on PUT
33 error publish Failed PUT 403
34 verbose stack Error: You do not have permission to publish 'replace'. Are you logged in as the correct user? : replace
34 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:247:14)
34 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:170:14)
34 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:344:22)
34 verbose stack     at Request.emit (events.js:110:17)
34 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1239:14)
34 verbose stack     at Request.emit (events.js:129:20)
34 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1187:12)
34 verbose stack     at IncomingMessage.emit (events.js:129:20)
34 verbose stack     at _stream_readable.js:908:16
34 verbose stack     at process._tickCallback (node.js:355:11)
35 verbose statusCode 403
36 verbose pkgid replace
37 verbose cwd /home/monika/Documents/Monika/Node_Practice/gitNode/node-practice
38 error Linux 3.16.0-30-generic
39 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "publish"
40 error node v0.12.2
41 error npm  v2.7.4
42 error code E403
43 error You do not have permission to publish 'replace'. Are you logged in as the correct user? : replace
44 error If you need help, you may report this error at:
44 error     <https://github.com/npm/npm/issues>
45 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@TMonika The package name "replace" is [already taken](https://www.npmjs.com/package/replace) :)

**Comment by TMonika** [comment]
Thank you... Changing the package name worked fine. :)
