### ISSUE TITLE
npm installs 102 packages when I'm trying to install only one

### ISSUE THREAD

**Issue by zgabievi** [npm/npm#10760]
`npm install --save <package>` installs 102 packages locally in my node_modules directory.

**I've tried two things to solve the problem:**
 1. Installing packages globally and then installing one of them locally
 2. Writing "dependencies" in `package.json` and then running `npm update`

None of them helped me.

It's not showing an error so npm-debug.log isn't created.

`node -v` - v5.2.0
`npm -v` - 3.5.1

I know that in old versions of npm it's working fine. I have problem in this version

**Comment by KenanY** [comment]
@zgabievi This is intended behavior, `npm@3` tries to installs your dependencies as _flat_ as possible, so many dependencies of your own dependencies get moved up to your project's `node_modules/` directory. [Here](https://github.com/npm/npm/blob/v3.0.0/CHANGELOG.md#flat-flat-flat) is the relevant update in `npm@3.0.0`'s changelog.

**Comment by zgabievi** [comment]
@KenanY Thanks!
