### ISSUE TITLE
npm global install does nothing

### ISSUE THREAD

**Issue by davidrhoderick** [npm/npm#10772]
Hello community,

I had no issues with npm from last year until a couple months ago.  At some point, I ran into an issue where none of my previously globally installed packages such as bower and grunt worked.  I did a full reinstall of node and npm and tried installing with homebrew as well as from downloads from the site.  After banging my head against a wall trying to fix it twice in a row, this third time I need to know how to get around this.  I know there have been updates to npm but my reinstalls should have fixed this.  What could be going wrong.  Sorry for the lack of information, just let me know what you need to know and I can provide it.  Has anyone else had this problem?  How can I go about fixing this?

**Comment by othiym23** [comment]
What version of npm are you running? What does `npm -g prefix` return?

**Comment by davidrhoderick** [comment]
I re-installed grunt with `npm install -g grunt-cli`, which fixed it, so I marked this closed.  I'll see if it persists and well reopen if necessary.  Thanks for the response!
