### ISSUE TITLE
UX: Add login success message

### ISSUE THREAD

**Issue by kevinSuttle** [npm/npm#10775]
There's a failure message, but no success message. Would be nice to have confirmation.

**Comment by zkat** [comment]
This seems like a pretty nice thing -- for example, we could print out something including the username, the scope (if they used a scope when logging in), and the registry URL just to make everything clear. We'd accept a PR for this if someone were to cook one up, but I'll close this particular issue for now until such a thing comes along.

**Comment by kevinSuttle** [comment]
Woot! https://github.com/npm/npm/pull/10903
