### ISSUE TITLE
npm error on 'install' command

### ISSUE THREAD

**Issue by ssjogus** [npm/npm#10786]
hi,

i am getting some error when i hit the command 'install' . Attached is the screenshot file..

![image](https://cloud.githubusercontent.com/assets/8896732/11742163/acf4979e-a023-11e5-8076-09fa11d0b1c0.png)

**Comment by thephilip** [comment]
Do you, by chance, have a copy of the debug log (d:\projects\p7\01-start\npm-debug.log)?
