### ISSUE TITLE
`npm install` modifies package.json even without --save

### ISSUE THREAD

**Issue by kylehg** [npm/npm#10780]
npm version: v2.14.14
Steps to reproduce:
```bash
$ npm --version
2.14.14
$ mkdir test
$ cd test
$ npm init
# init an empty project
$ cat package.json 
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}
$ npm install express
$ cat package.json 
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "express": "4.13.3"
  }
}
```

**Comment by KenanY** [comment]
@kylehg So just to make sure, what does `npm config get save` return?

**Comment by kylehg** [comment]
Oh wow I feel dumb—returns `true`, which I see means "Save installed packages to a package.json file as dependencies." Idk how that got set but removing fixes it, thank you!

**Comment by seamlik** [comment]
Now this is weird, `save` is turned off [by default](https://docs.npmjs.com/misc/config#save) but my (and your) NPM turned it on. Is this behavior changed by NodeSource's distribution?

**Comment by kenany** [comment]
@seamlik The default is now `true`, but the website has not been updated to reflect the current docs: <https://github.com/npm/npm/blob/ee147fbbca6f2707d3b16f4fa78f4c4606b2d9b1/doc/misc/npm-config.md#save>

**Comment by seamlik** [comment]
Oh! Although I don't totally agree with this change, thank you for the info.
