### ISSUE TITLE
npmrc environment variable expansion 

### ISSUE THREAD

**Issue by kevinSuttle** [npm/npm#10782]
After logging into NPMO, I noticed that the token is updated in my npmrc, but I had things like `${NPM_REGISTRY_URL}` in there, `export`ed in `~/.profile`, which were now expanded to their actual values. 

Is there a safer way to preserve these?

**Comment by othiym23** [comment]
This is a longstanding bug – the variable expansion is done at load time, and when there's an npm command that changes the config file (like `npm login`), the code that saves the config values writes out all the non-default values back into `.npmrc`, which writes out the expanded values from the environment rather than the placeholders. It should definitely not be doing that, so a patch that preserves the variables would be very welcome.

**Comment by kevinSuttle** [comment]
Aha. The solution seems to be setting the values to read only. Only the auth token set in .npmrc would need to be written. 

See: https://github.com/gitster/git/commit/21cf32279120799a766d22416be7d82d9ecfbd04 and https://github.com/npm/npm/issues/6675

The problem is that npm doesn't like read-only constants.

**~.profile**
Given either declaration:  

```bash
declare -r MY_NAME="Kevin Suttle"
readonly MY_NAME="Kevin Suttle"
```

**.npmrc**
```bash
init.author.name=${MY_NAME}
```

**bash**
```bash
❯ source ~/.profile
bash: declare: MY_NAME: readonly variable

❯ npm whoami
Error: Failed to replace env in config: ${MY_NAME}
```

**Comment by kevinSuttle** [comment]
Actually, if you just reference the values in the .npmrc without the `{ }`, it works. 

`init.author.name=$MY_NAME`

**Comment by kevinSuttle** [comment]
Hm, it seems `scope` and `registry` can't be set in ~/.npmrc, even though `npm config list` shows them as set. 

Example:
```bash
❯ npmconfig list
; cli configs
user-agent = "npm/3.3.12 node/v5.2.0 darwin x64"

; userconfig /Users/kevinSuttle/.npmrc

init.author.email = "$MY_EMAIL_ADDRESS"
init.author.name = "$MY_NAME"
init.registry = "$MY_NPM_REGISTRY"
init.scope = "$MY_ORG"

; builtin config undefined
prefix = "/usr/local"

; node bin location = /usr/local/Cellar/node/5.2.0/bin/node
; cwd = /Users/kevinSuttle/Code/temp
; HOME = /Users/kevinSuttle
; "npm config ls -l" to show all defaults.
```

```bash
# in the shell
❯ npminit --yes
Wrote to /Users/kevinSuttle/Code/temp/package.json:
{
  "name": "temp",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "Kevin Suttle" <kevin@myemail.biz>,
  "license": "ISC",
  "keywords": [],
  "description": ""
}
```
No `scope`, no `registry`. Is this because of [`publishConfig`](https://docs.npmjs.com/files/package.json#publishconfig)?

**Comment by kevinSuttle** [comment]
@isaacs @othiym23 Any ideas?
