### ISSUE TITLE
npm global installation on Windows

### ISSUE THREAD

**Issue by thaddeusd** [npm/npm#10797]
Does npm need to use %appdata% to install packages in Windows? Is there a way to create a 'true' global installation?

**Comment by felixfbecker** [comment]
I already left some comments here: https://github.com/nodejs/node/issues/4603#issuecomment-171423910

This is really confusing. When you install NodeJS globally in `C:\Program Files`, npm global modules still only get installed locally. And the PATH entry is only done for the user installing. And all just to avoid UAC. On Mac and Linux everyone is fine with using `sudo`, but on Windows everyone tries to avoid UAC. 

If NodeJS is installed to `C:\Program Files\NodeJS`, then NPM should be installed to `C:\Program Files\NPM` too (with the local equivalent `%USERPROFILE%\AppData\Local`) or `C:\ProgramData\NPM` (with the local equivalent `%USERPROFILE%\AppData\Roaming`). The NodeJS install dir should not include any npm code so upgrading can be done like on any other OS with `npm install -g npm`.
