### ISSUE TITLE
Proposal: Replace "node_modules" path segment by ".n"

### ISSUE THREAD

**Issue by SetTrend** [npm/npm#10802]
Windows systems suffer from a [maximum path length of 260 characters](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247%28v=vs.85%29.aspx#maxpath).

Although Microsoft created a workaround syntax for allowing a longer path, I don't know of any program, incl. File Explorer, which doesn't lack the ability to handle paths longer than 260 characters.

NPM repositories with a subtly deep dependency tree (7+) cannot be used on Windows because tools like Visual Studio 2015 and Windows 10 File Explorer fail to create/access/modify/delete them:

```
D:\Documents\Visual Studio-Projekte\Visual Studio 2015\Projects\IdentitySamples
invalid path '\\?\D:\Documents\Visual Studio-Projekte\Visual Studio 2015\Projects\IdentitySamples\samples\Multiple Projects Sample\Clients\AngularClient\node_modules\gulp-less\node_modules\accord\node_modules\uglify-js\node_modules\yargs\node_modules\cliui\node_modules\center-align' (path too long)
invalid path '\\?\D:\Documents\Visual Studio-Projekte\Visual Studio 2015\Projects\IdentitySamples\samples\Multiple Projects Sample\Clients\AngularClient\node_modules\gulp-less\node_modules\accord\node_modules\uglify-js\node_modules\yargs\node_modules\cliui\node_modules\center-align' (path too long)
invalid path '\\?\D:\Documents\Visual Studio-Projekte\Visual Studio 2015\Projects\IdentitySamples\samples\Multiple Projects Sample\Clients\AngularClient\node_modules\gulp-less\node_modules\accord\node_modules\uglify-js\node_modules\yargs\node_modules\cliui\node_modules\center-align' (path too long)
invalid path '\\?\D:\Documents\Visual Studio-Projekte\Visual Studio 2015\Projects\IdentitySamples\samples\Multiple Projects Sample\Clients\AngularClient\node_modules\gulp-less\node_modules\accord\node_modules\uglify-js\node_modules\yargs\node_modules\cliui\node_modules\center-align' (path too long)
```
(taken from Visual Studio 2015 Git Extension output window)

So I'd like to suggest to shorten the [paths created by **NPM**](https://github.com/npm/npm/blob/835ae5a2c55164c111ac142ce50ff2dfad88799c/lib/utils/child-path.js#L9) drastically by renaming path segment `"node_modules\"` to a shorter version, like for instance `".n\"`.
<br/>
/cc github/VisualStudio#163

**Comment by SetTrend** [comment]
github/VisualStudio#163

**Comment by seekshiva** [comment]
@SetTrend Use npm3.

npm3 tries to install the node_modules dependencies in a flat structure, so all the inner dependencies will all be installed directly in the top-most node_modules folder. So, all these 'long file name' issues won't be there if you use npm3 to install packages.

**Comment by SetTrend** [comment]
Excellent. Thanks for the clarification.

**Comment by SetTrend** [comment]
It looks like the update didn't show the desired effect. NPM 3++ still applies a reverse directory structure (see referenced issue, at the bottom of the thread).

Is there some global configuration I need to amend to have NPM use a flat directory structure?

**Comment by seekshiva** [comment]
If had already run npm install using npm2, npm2 would've installed all packages In a nested structure.. And when you run npm install using npm3, it won't affect the package structure. 

You need to delete the node_modules folder in your project directory, and then do npm install.

**Comment by seekshiva** [comment]
npm3 doesn't force a flat directory structure. If node_modules folder is already present, it will just try to use that, and only when new packages are being installed it will try to do it in a flat way.

**Comment by SetTrend** [comment]
I just received a comment at the referenced issue that Visual Studio uses its own copy of Node which is not getting updated when I update Node on my machine.

We are currently investigating on how to update the Visual Studio copy.

Nonetheless, I had been succeeding creating a flat structure using Node via the command line.

Thanks for helping! :+1:
