### ISSUE TITLE
failed to fetch from registry: express/3.3.4

### ISSUE THREAD

**Issue by patelvishal1401** [npm/npm#10818]
GET https://registry.npmjs.org/express/3.3.4
npm ERR! Error: failed to fetch from registry: express/3.3.4
npm ERR!     at /usr/local/lib/node_modules/npm/lib/utils/npm-registry-client/get.js:139:12
npm ERR!     at cb (/usr/local/lib/node_modules/npm/lib/utils/npm-registry-client/request.js:32:9)
npm ERR!     at Request._callback (/usr/local/lib/node_modules/npm/lib/utils/npm-registry-client/request.js:137:18)
npm ERR!     at Request.callback (/usr/local/lib/node_modules/npm/node_modules/request/main.js:104:22)
npm ERR!     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/main.js:181:58)
npm ERR!     at Request.emit (events.js:88:20)
npm ERR!     at ClientRequest.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/main.js:329:14)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at HTTPParser.onIncoming (http.js:1238:11)
npm ERR!     at HTTPParser.onHeadersComplete (http.js:102:31)
npm ERR! Report this *entire* log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
npm ERR!

**Comment by KenanY** [comment]
@patelvishal1401 Please try updating `npm` first. If you continue to face any issues please upload the `npm-debug.log` as a [gist](https://gist.github.com/) and link it here instead of cutting off the log.

**Comment by patelvishal1401** [comment]
Thanks.. KenanY. Issue solved..
