### ISSUE TITLE
No compatible version found: node@5.2.0

### ISSUE THREAD

**Issue by chrisvelevitch** [npm/npm#10810]
What does this mean and how can I fix this?

    npm install
    npm ERR! Darwin 13.4.0
    npm ERR! argv "/usr/local/Cellar/node/5.2.0/bin/node" "/Users/chris/.node/bin/npm" "i"
    npm ERR! node v5.2.0
    npm ERR! npm  v3.5.1
    
    npm ERR! No compatible version found: node@5.2.0
    npm ERR! Valid install targets:
    npm ERR! 0.0.0

In my `package.json` contains:

    "dependencies": {
        "angular2": "2.0.0-alpha.44",
        "node": "5.2.0",
        "systemjs": "0.19.2"
      }

I've node v5.2.0 installed, so why is `npm` complaining?

**Comment by KenanY** [comment]
@chrisvelevitch This [`node`](https://www.npmjs.com/package/node) npm package is not the same as Node.js. I believe you should remove that from your `"dependencies"`.

**Comment by othiym23** [comment]
You may also want to investigate the [`engines`](https://docs.npmjs.com/files/package.json#engines) field of `package.json`, which I think does what you want. Closing as resolved!
