### ISSUE TITLE
Can't use accent marks in package.json

### ISSUE THREAD

**Issue by auermi** [npm/npm#10817]
For example, can't set package name to "Écrivez"

[npm-debug.txt](https://github.com/npm/npm/files/62069/npm-debug.txt)

Using npm v3.3.5

**Comment by othiym23** [comment]
Capitalized letters are not allowed in package names. For now, only basic ASCII letters and numbers, and a [few other characters](https://docs.npmjs.com/files/package.json#name) are supported. We've discussed allowing non-ASCII characters, but the restriction that characters must be URL safe complicates things.

**Comment by seldo** [comment]
Testing of non-ascii characters in our infrastructure happened accidentally one time and revealed only a couple of points where things broke, but things definitely broke, so it's not just a matter of fixing the validation. The primary choke-point has historically been vanilla couchDB, which handled non-ascii URLs very poorly. Even if we fix the points in our own infrastructure where we fail at non-ASCII URLs, making this change risks breaking the many thousands of down-stream npm mirrors, many of which lag years behind the current version of couch.

Given the high uncertainty and medium risk of breaking things for our community that we cannot undo or fix once broken, this is not likely to happen in the near term, but it's obviously something we're going to have to resolve eventually.

**Comment by zkat** [comment]
@seldo answered this as well as we'll be able to for the time being -- we'll come back to this when the necessary changes have been made to the registry, so I'll close this for now.

**Comment by dotnetCarpenter** [comment]
As [@dholth said](https://github.com/npm/npm/issues/4424#issuecomment-234642511) - [**punycode!**](https://www.punycoder.com/java-script/)

**Comment by ccorcos** [comment]
is this moving forward anywhere?
