### ISSUE TITLE
Error while iistalling protractor - npm ERR! getaddrinfo EAI_AGAIN registry.npmjs.org:443

### ISSUE THREAD

**Issue by swapten** [npm/npm#10821]
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\
node_modules\npm\bin\npm-cli.js" "install" "-g" "protractor"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.7
npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! syscall getaddrinfo

npm ERR! getaddrinfo EAI_AGAIN registry.npmjs.org:443
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\1100171\npm-debug.log

**Comment by Ckarlin** [comment]
logo is solved ??

**Comment by jinnia** [comment]
same error for me also.Please help me to solve.
