### ISSUE TITLE
Show similarly-named orgs when creating a new org, team, and package

### ISSUE THREAD

**Issue by kevinSuttle** [npm/npm#10834]
See also: https://github.com/kevinSuttle/github/issues/11

**Comment by othiym23** [comment]
How would this work in the CLI?

**Comment by kevinSuttle** [comment]
It would do a fuzzy search essentially, like it does if you search for a package.

<img width="1440" alt="screen shot 2015-12-16 at 3 52 09 pm" src="https://cloud.githubusercontent.com/assets/95672/11853613/144043d4-a40d-11e5-86e2-1d38318fc2ee.png">

**Comment by zkat** [comment]
this is an interesting idea, but it seems like a fairly small use-case that can be easily fulfilled by the `npm org ls` and `npm team ls` commands (possibly combined with grep).

Thanks for the time putting together this request submission!
