### ISSUE TITLE
github dependencies don't match (causing ERR!) after shrinkwrap

### ISSUE THREAD

**Issue by pugsley** [npm/npm#10839]
Seems like github dependancy strings aren't being normalised when comparing during `npm shrinkwrap` or `npm ls`. 

Replicate:
- Create package.json in empty directory

```
{
  "engines": {
    "node": "4.2.3",
    "npm": "3.5.2"
  },
  "dependencies": {
    "dargs": "christian-bromann/dargs"
  }
}
```
- `npm install`
- `npm shrinkwrap` (no errors, `npm-shrinkwrap.json` created successfully)
- `rm -rf node_modules` (remove installed modules)
- `npm install` (install from shrinkwrap)
- `npm ls` > error: `dargs@4.0.1 invalid` (or npm shrinkwrap)

If it's repeated again with the following `package.json` file (full github path):

```
{
  "engines": {
    "node": "4.2.3",
    "npm": "3.5.2"
  },
  "dependencies": {
    "dargs": "git://github.com/christian-bromann/dargs"
  }
}
```

Then the `npm ls` in the final step produces no errors.

**Comment by smikes** [comment]
Thanks for reporting this!

**Comment by pornel** [comment]
I think I have the same problem:

```js
 "dependencies": {
    "circular": "git+ssh://private/circular.git#v1.0.2",
```

npm shrinkwrap fails with:

```
npm ERR! invalid: have circular@1.0.2 (expected: git+ssh://private/circular.git#v1.0.2) /ft-app/node_modules/circular
…
npm ERR! extraneous: circular@1.0.2 /ft-app/node_modules/circular
```

It repeats this error for every git dependency. It used to barely work with npm2, but npm3 is unusable.
