### ISSUE TITLE
Import orgs/collaborators from GitHub into npm orgs

### ISSUE THREAD

**Issue by kevinSuttle** [npm/npm#10835]
Example from CodeShip: 
![image](https://cloud.githubusercontent.com/assets/95672/11817235/09fcd5ea-a322-11e5-986c-73d9b094cafd.png)

This would also apply to npmo.

**Comment by othiym23** [comment]
This belongs on `npm/newww` rather than the CLI, because the primary interface for that is going to require a web site, due to things like OAuth handshaking. I don't know whether it's on the web team's road map or not, but this does seem like it would be a useful thing!

**Comment by kevinSuttle** [comment]
Oh right. Sorry about that. Good point.

However, I think when I brought this up initially, I was thinking that the UI pull from `npm team` and that `npm org` could pull from GitHub Orgs. Cyclical depency, though. Still, even if GitHub wasn't involved at all, it would be nice to pull from teams. 

https://docs.npmjs.com/getting-started/working-with-orgs
https://docs.npmjs.com/cli/team

**Comment by kevinSuttle** [comment]
This may be an issue for @ceejbot over in https://github.com/npm/npmo-registry.
