### ISSUE TITLE
package.json alphabetical ordering re-orders arrays

### ISSUE THREAD

**Issue by aplikesbikes** [npm/npm#10831]
I have a transform array inside of browserify and with npm v2.14.2 an npm install will produce the transform array in the initial order, but with npm v3.3.6 an npm install will re-order the transform array.

**Comment by KenanY** [comment]
Duplicate of https://github.com/npm/npm/issues/10063. PR is https://github.com/npm/npm/pull/10185.

**Comment by aplikesbikes** [comment]
Thanks
