### ISSUE TITLE
Document list of reserved names

### ISSUE THREAD

**Issue by kevinSuttle** [npm/npm#10833]
See also: https://github.com/kevinSuttle/github/issues/3

Should probably be linked to, or published here: https://www.npmjs.com/policies/disputes

**Comment by othiym23** [comment]
This should also be filed as an issue on `npm/newww`, `npm/docs`, or maybe directly on `npm/policies`, which is where https://www.npmjs.com/policies/disputes originates. The CLI is not going to be the first place most people are going to look for this information, and I'm not even sure where it would fit in the current documentation without being distracting to most users most of the time. It would be a useful thing to have documented, though! I'm not sure I could tell you the list of reserved user / package / org names without doing some time-consuming research.

**Comment by kevinSuttle** [comment]
Right, I keep putting these in the wrong repo. Sorry about that. :/

**Comment by kevinSuttle** [comment]
https://github.com/npm/policies/issues/36
