### ISSUE TITLE
npm not working in windows

### ISSUE THREAD

**Issue by RushabhJoshi** [npm/npm#10849]
I think I did every thing which was suggested
Stopped firewall
npm uninstall -g npm
npm install -g npm
npm cache clear
Install whole new visual studio.

This is my npm-debug.txt when I command npm start
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose stack Error: missing script: start
4 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:138:19)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:81:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:51:40
4 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:349:17)
4 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:126:33)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:331:40
4 verbose stack     at evalmachine.<anonymous>:336:14
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:102:5
4 verbose stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:99:15)
5 verbose cwd E:\work\videodeck
6 error Windows_NT 6.1.7601
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
8 error node v0.12.0
9 error npm  v2.5.1
10 error missing script: start
11 error If you need help, you may report this error at:
11 error     <http://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@RushabhJoshi So, do you have a `"start"` script defined in your `package.json`?

**Comment by RushabhJoshi** [comment]
Actually I don't have start script in my working project but wait it started with 

`npm install`
(may be for all package install e.g. npm install -g strongloop)
which shows the error

MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 20 05 or 3) add the location of the component to the system path if it is installed elsewhere.  [C:\Users\alfanso\AppData\Roaming\npm\node_modules\strongloop\node_modules\s trong-supervisor\node_modules\strong-agent\build\binding.sln]

I already install the whole Visual Studio now.

Suggested solution was to use

`npm install -g strongloop --msvs_version=2013`

after this previous error solved but new error occured

C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(57,5): error MSB8020: The build tools for v120 (Platform Toolset = 'v120') cannot b e found. To build using the v120 build tools, please install v120 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Projec t menu or right-click the solution, and then selecting "Retarget solution". [E:\work\vidiodek\node_modules\laravel-elixir\node_modules\browser-sync\node_modules\socket.i o\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\utf-8-validate\build\validation.vcxproj]

**Comment by RushabhJoshi** [comment]
One other thing. Do I have to always write `npm install --msvs_version=2013`? why `npm install` is not working?

**Comment by smikes** [comment]
You will always need to tell `npm` which version of the visual studio compiler tools to use, if more than one is installed, yes.  But you can set the `msvs_version` option in your `npm` config --

```
npm config set msvs_version 2013
```

And then you will not have to supply it on every `npm install` command line.

Other than that, is this still a problem for you?

You may have better results if you upgrade to a newer Node and npm --

To update npm on Windows, you can use this command-line tool from Microsoft: https://github.com/felixrieseberg/npm-windows-upgrade
or follow the manual instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by RushabhJoshi** [comment]
I will try updating node and npm.

**Comment by RushabhJoshi** [comment]
Sorry if its a silly question but I don't understand what's wrong.

I updated node and npm.
And I ran 
`npm install perspective-transform --save -msvs_version=2013`

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\alfanso\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'perspective-transform',
1 verbose cli   '--save',
1 verbose cli   '-msvs_version=2013' ]
2 info using npm@3.5.2
3 info using node@v4.2.3
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData perspective-transform
8 silly fetchNamedPackageData perspective-transform
9 silly mapToRegistry name perspective-transform
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/perspective-transform
13 verbose request uri https://registry.npmjs.org/perspective-transform
14 verbose request no auth needed
15 info attempt registry request try #1 at 3:24:42 PM
16 verbose request id 10a6ad9c14ad57f9
17 verbose etag "Q4EWQHXH133V79I528SC6Q18"
18 http request GET https://registry.npmjs.org/perspective-transform
19 http 304 https://registry.npmjs.org/perspective-transform
20 verbose headers { date: 'Thu, 24 Dec 2015 09:54:40 GMT',
20 verbose headers   via: '1.1 varnish',
20 verbose headers   'cache-control': 'max-age=300',
20 verbose headers   etag: '"Q4EWQHXH133V79I528SC6Q18"',
20 verbose headers   age: '105',
20 verbose headers   connection: 'keep-alive',
20 verbose headers   'x-served-by': 'cache-sin6927-SIN',
20 verbose headers   'x-cache': 'HIT',
20 verbose headers   'x-cache-hits': '1',
20 verbose headers   'x-timer': 'S1450950880.574843,VS0,VE0',
20 verbose headers   vary: 'Accept' }
21 silly get cb [ 304,
21 silly get   { date: 'Thu, 24 Dec 2015 09:54:40 GMT',
21 silly get     via: '1.1 varnish',
21 silly get     'cache-control': 'max-age=300',
21 silly get     etag: '"Q4EWQHXH133V79I528SC6Q18"',
21 silly get     age: '105',
21 silly get     connection: 'keep-alive',
21 silly get     'x-served-by': 'cache-sin6927-SIN',
21 silly get     'x-cache': 'HIT',
21 silly get     'x-cache-hits': '1',
21 silly get     'x-timer': 'S1450950880.574843,VS0,VE0',
21 silly get     vary: 'Accept' } ]
22 verbose etag https://registry.npmjs.org/perspective-transform from cache
23 verbose get saving perspective-transform to C:\Users\alfanso\AppData\Roaming\npm-cache\registry.npmjs.org\perspective-transform\.cache.json
24 silly install normalizeTree
25 silly loadCurrentTree Finishing
26 silly loadIdealTree Starting
27 silly install loadIdealTree
28 silly cloneCurrentTree Starting
29 silly install cloneCurrentTreeToIdealTree
30 silly cloneCurrentTree Finishing
31 silly loadShrinkwrap Starting
32 silly install loadShrinkwrap
33 silly loadShrinkwrap Finishing
34 silly loadAllDepsIntoIdealTree Starting
35 silly install loadAllDepsIntoIdealTree
36 silly rollbackFailedOptional Starting
37 silly rollbackFailedOptional Finishing
38 silly runTopLevelLifecycles Starting
39 silly runTopLevelLifecycles Finishing
40 silly install printInstalled
41 verbose stack Error: Refusing to install perspective-transform as a dependency of itself
41 verbose stack     at checkSelf (C:\Users\alfanso\AppData\Roaming\npm\node_modules\npm\lib\install\validate-args.js:40:14)
41 verbose stack     at Array.<anonymous> (C:\Users\alfanso\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
41 verbose stack     at LOOP (C:\Users\alfanso\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
41 verbose stack     at chain (C:\Users\alfanso\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
41 verbose stack     at C:\Users\alfanso\AppData\Roaming\npm\node_modules\npm\lib\install\validate-args.js:15:5
41 verbose stack     at C:\Users\alfanso\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
41 verbose stack     at Array.forEach (native)
41 verbose stack     at C:\Users\alfanso\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
41 verbose stack     at Array.forEach (native)
41 verbose stack     at asyncMap (C:\Users\alfanso\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
42 verbose cwd E:\node\perspective-transform
43 error Windows_NT 6.1.7601
44 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\alfanso\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "perspective-transform" "--save" "-msvs_version=2013"
45 error node v4.2.3
46 error npm  v3.5.2
47 error code ENOSELF
48 error Refusing to install perspective-transform as a dependency of itself
49 error If you need help, you may report this error at:
49 error     <https://github.com/npm/npm/issues>
50 verbose exit [ 1, true ]

**Comment by RushabhJoshi** [comment]
I updated node to 5.3.0 and npm to 3.5.3
still not working I don't know why? then I gave up and tried another day
above command worked (Still don't know how?)

but their is a error which suggest me to rebuild the package(`npm rebuild node-sass`).

This show me the error 

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\alfanso\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'rebuild',
1 verbose cli   'node-sass' ]
2 info using npm@3.5.3
3 info using node@v5.3.0
4 info readInstalled object
5 verbose rebuild path, id [ 'E:\\work\\letsmock\\node_modules\\laravel-elixir\\node_modules\\gulp-sass\\node_modules\\node-sass',
5 verbose rebuild   'node-sass@3.3.3' ]
6 verbose rebuild path, id [ 'E:\\work\\letsmock\\node_modules\\node-sass',
6 verbose rebuild   'node-sass@3.4.2' ]
7 silly rebuild set [ 'E:\\work\\letsmock\\node_modules\\laravel-elixir\\node_modules\\gulp-sass\\node_modules\\node-sass',
7 silly rebuild set   'E:\\work\\letsmock\\node_modules\\node-sass' ]
8 info build E:\work\letsmock\node_modules\laravel-elixir\node_modules\gulp-sass\node_modules\node-sass
9 info lifecycle node-sass@3.3.3~preinstall: node-sass@3.3.3
10 silly lifecycle node-sass@3.3.3~preinstall: no script for preinstall, continuing
11 info linkStuff node-sass@3.3.3
12 silly linkStuff node-sass@3.3.3 has E:\work\letsmock\node_modules\laravel-elixir\node_modules\gulp-sass\node_modules as its parent node_modules
13 verbose linkBins node-sass@3.3.3
14 verbose link bins [ { 'node-sass': 'bin/node-sass' },
14 verbose link bins   'E:\\work\\letsmock\\node_modules\\laravel-elixir\\node_modules\\gulp-sass\\node_modules\\.bin',
14 verbose link bins   false ]
15 verbose linkMans node-sass@3.3.3
16 verbose rebuildBundles node-sass@3.3.3
17 verbose rebuildBundles [ '.bin',
17 verbose rebuildBundles   'async-foreach',
17 verbose rebuildBundles   'chalk',
17 verbose rebuildBundles   'cross-spawn',
17 verbose rebuildBundles   'gaze',
17 verbose rebuildBundles   'get-stdin',
17 verbose rebuildBundles   'meow',
17 verbose rebuildBundles   'mkdirp',
17 verbose rebuildBundles   'nan',
17 verbose rebuildBundles   'node-gyp',
17 verbose rebuildBundles   'npmconf',
17 verbose rebuildBundles   'request',
17 verbose rebuildBundles   'sass-graph' ]
18 info lifecycle node-sass@3.3.3~install: node-sass@3.3.3
19 verbose lifecycle node-sass@3.3.3~install: unsafe-perm in lifecycle true
20 verbose lifecycle node-sass@3.3.3~install: PATH: C:\Users\alfanso\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;E:\work\letsmock\node_modules\laravel-elixir\node_modules\gulp-sass\node_modules\node-sass\node_modules\.bin;E:\work\letsmock\node_modules\laravel-elixir\node_modules\gulp-sass\node_modules\.bin;E:\work\letsmock\node_modules\laravel-elixir\node_modules\.bin;E:\work\letsmock\node_modules\.bin;C:\Program Files\ConEmu;C:\Program Files\ConEmu\ConEmu;C:\ProgramData\Oracle\Java\javapath;C:\ImageMagick;C:\imagick;C:\ImageMagick-6.9.2-Q16;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Vagrant\bin;C:\Program Files (x86)\OpenSSH\bin;C:\xampp\php;C:\ProgramData\ComposerSetup\bin;C:\Program Files (x86)\Git\cmd;C:\Users\alfanso\AppData\Roaming\Composer\vendor\bin;C:\Python27;C:\Program Files (x86)\Python3;;C:\server\bin\perl\c\bin;C:\server\bin\perl\perl\site\bin;C:\server\bin\perl\perl\bin;C:\Users\alfanso\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\nodejs\;C:\Ruby22-x64\bin;D:\xampp\php\php.exe;C:\Windows\System32\curl;C:\Windows\System32\curl-ca-bundle;C:\Users\alfanso\AppData\Local\.meteor\;C:\xampp\mysql\bin;D:\ffmpeg\bin;C:\xampp\apache\bin;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Program Files (x86)\Diffuse;C:\Users\alfanso\AppData\Roaming\npm
21 verbose lifecycle node-sass@3.3.3~install: CWD: E:\work\letsmock\node_modules\laravel-elixir\node_modules\gulp-sass\node_modules\node-sass
22 silly lifecycle node-sass@3.3.3~install: Args: [ '/d /s /c', 'node scripts/install.js' ]
23 silly lifecycle node-sass@3.3.3~install: Returned: code: 0  signal: null
24 info lifecycle node-sass@3.3.3~postinstall: node-sass@3.3.3
25 verbose lifecycle node-sass@3.3.3~postinstall: unsafe-perm in lifecycle true
26 verbose lifecycle node-sass@3.3.3~postinstall: PATH: C:\Users\alfanso\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;E:\work\letsmock\node_modules\laravel-elixir\node_modules\gulp-sass\node_modules\node-sass\node_modules\.bin;E:\work\letsmock\node_modules\laravel-elixir\node_modules\gulp-sass\node_modules\.bin;E:\work\letsmock\node_modules\laravel-elixir\node_modules\.bin;E:\work\letsmock\node_modules\.bin;C:\Program Files\ConEmu;C:\Program Files\ConEmu\ConEmu;C:\ProgramData\Oracle\Java\javapath;C:\ImageMagick;C:\imagick;C:\ImageMagick-6.9.2-Q16;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Vagrant\bin;C:\Program Files (x86)\OpenSSH\bin;C:\xampp\php;C:\ProgramData\ComposerSetup\bin;C:\Program Files (x86)\Git\cmd;C:\Users\alfanso\AppData\Roaming\Composer\vendor\bin;C:\Python27;C:\Program Files (x86)\Python3;;C:\server\bin\perl\c\bin;C:\server\bin\perl\perl\site\bin;C:\server\bin\perl\perl\bin;C:\Users\alfanso\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\nodejs\;C:\Ruby22-x64\bin;D:\xampp\php\php.exe;C:\Windows\System32\curl;C:\Windows\System32\curl-ca-bundle;C:\Users\alfanso\AppData\Local\.meteor\;C:\xampp\mysql\bin;D:\ffmpeg\bin;C:\xampp\apache\bin;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Program Files (x86)\Diffuse;C:\Users\alfanso\AppData\Roaming\npm
27 verbose lifecycle node-sass@3.3.3~postinstall: CWD: E:\work\letsmock\node_modules\laravel-elixir\node_modules\gulp-sass\node_modules\node-sass
28 silly lifecycle node-sass@3.3.3~postinstall: Args: [ '/d /s /c', 'node scripts/build.js' ]
29 silly lifecycle node-sass@3.3.3~postinstall: Returned: code: 1  signal: null
30 info lifecycle node-sass@3.3.3~postinstall: Failed to exec postinstall script
31 verbose stack Error: node-sass@3.3.3 postinstall: `node scripts/build.js`
31 verbose stack Exit status 1
31 verbose stack     at EventEmitter.<anonymous> (C:\Users\alfanso\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:232:16)
31 verbose stack     at emitTwo (events.js:87:13)
31 verbose stack     at EventEmitter.emit (events.js:172:7)
31 verbose stack     at ChildProcess.<anonymous> (C:\Users\alfanso\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:24:14)
31 verbose stack     at emitTwo (events.js:87:13)
31 verbose stack     at ChildProcess.emit (events.js:172:7)
31 verbose stack     at maybeClose (internal/child_process.js:818:16)
31 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
32 verbose pkgid node-sass@3.3.3
33 verbose cwd E:\work\letsmock
34 error Windows_NT 6.1.7601
35 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\alfanso\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "rebuild" "node-sass"
36 error node v5.3.0
37 error npm  v3.5.3
38 error code ELIFECYCLE
39 error node-sass@3.3.3 postinstall: `node scripts/build.js`
39 error Exit status 1
40 error Failed at the node-sass@3.3.3 postinstall script 'node scripts/build.js'.
40 error Make sure you have the latest version of node.js and npm installed.
40 error If you do, this is most likely a problem with the node-sass package,
40 error not with npm itself.
40 error Tell the author that this fails on your system:
40 error     node scripts/build.js
40 error You can get information on how to open an issue for this project with:
40 error     npm bugs node-sass
40 error Or if that isn't available, you can get their info via:
40 error     npm owner ls node-sass
40 error There is likely additional logging output above.
41 verbose exit [ 1, true ]

**Comment by afarazit** [comment]
Had the following problem trying to install `laravel-elixir`.

> C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.Cpp.Platform.targets(44,5): error MSB8020: The builds
> tools for v140 (Platform Toolset = 'v140') cannot be found. To build using the v140 build tools, either click the Proje
> ct menu or right-click the solution, and then select "Update VC++ Projects...". Install v140 to build using the v140 bu
> ild tools. [L:\Development\platform-api\node_modules\laravel-elixir\node_modules\browser-sync\node_modules\socket.io\no
> de_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\utf-8-validate\build\validation.
> vcxproj]

 Running `npm install --msvs_version=2015` solved it

**Comment by RushabhJoshi** [comment]
In my case I don't need to specify the msvs version but sometime It will work with `npm install --no-bin-links`

anyways this is no longer issue for me now. so I close this issue
