### ISSUE TITLE
npm test error log

### ISSUE THREAD

**Issue by Revo86** [npm/npm#10853]
Hello guys,

I'm completely unfamiliar with linux and wanted to ask, what I've done wrong with installing npm / node on my machine. I'm not even sure, if this is the right area to post this stuff. Any hint would be much appreciated though!

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'test' ]
2 info using npm@1.4.14
3 info using node@v0.10.29
4 error Error: ENOENT, open '/home/openstreetmap/package.json'
5 error If you need help, you may report this *entire* log,
5 error including the npm and node versions, at:
5 error     <http://github.com/npm/npm/issues>
6 error System Linux 3.13.0-63-generic
7 error command "/usr/local/bin/node" "/usr/local/bin/npm" "test"
8 error cwd /home/openstreetmap
9 error node -v v0.10.29
10 error npm -v 1.4.14
11 error path /home/openstreetmap/package.json
12 error code ENOENT
13 error errno 34
14 verbose exit [ 34, true ]
```

**Comment by KenanY** [comment]
@Revo86 To me it looks like you are running `npm test` in a directory that does not contain a `package.json`. First of all, are you sure that you are in the correct directory? Secondly, what are you _expecting_ to happen when you run `npm test`?

(I also feel the strong need to let you know that support for `npm@1.4` is nearly gone at this point so I definitely recommend [updating](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) when it is most convenient)

**Comment by KenanY** [comment]
Closing as resolved/abandoned. `npm` is functioning as expected here; without a `package.json` in your current directory, `npm` will have no idea what `"test"` script you would like it to run. If you are still seeing this issue with `npm@2` or `npm@3`, feel free to open a new issue.
