### ISSUE TITLE
node-gyp rebuild fails in VS2015 due to wrong path

### ISSUE THREAD

**Issue by thomas-darling** [npm/npm#10850]
Package restore in Visual Studio 2015 fails with the following:

```
> utf-8-validate@1.2.1 install C:\MyProject\node_modules\browser-sync\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\utf-8-validate
> node-gyp rebuild
C:\MyProject\node_modules\browser-sync\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\utf-8-validate>node "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild 
npm http 200 https://registry.npmjs.org/adm-zip
npm http 200
module.js:340
    throw err;
          ^
Error: Cannot find module 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

Looks like the file path to `node-gyp.js` is wrong - the nearest instance of that file appears to be:
`C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External\npm\node_modules\node-gyp\bin\node-gyp.js`

This issue may be a result of installing the lates Node.js Tools for Visual Studio, although I'm not sure this is the cause. I suspect it might have something to do with the flatter package folder heirachy created by the newer version of npm - maybe something have moved around in there, causing a path somewhere to now be invalid?

I'm not sure whether this is an issue in the NPM, Node.js Tools, or somewhere else - but it's consistently failing during package restore in Visual Studio. Manually running `npm install` in the console works perfectly though, so it appears to be specific to Visual Studio.

**Comment by smikes** [comment]
Thanks for bringing this up.

I'm not familiar with the Microsoft install here - have you checked with their support channels (Knowledge Base, etc...?)

As you say, this doesn't look like a npm issue *per se* though it may have been triggered by a change in how npm lays out dependency paths, if there was a hardcoded path to node-gyp.js somewhere in another module...

**Comment by thomas-darling** [comment]
Just want to let you know that this is being fixed :-)
https://github.com/Microsoft/nodejstools/issues/649
