### ISSUE TITLE
No Compatible Version Found

### ISSUE THREAD

**Issue by rawcreative** [npm/npm#10858]
Recently updated node & npm to their current versions and had to remove the node_modules dir in a current project and re-install. Now I'm getting a 'No compatible version found' error for one of the packages. 

```
npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/Tim/.nvm/versions/node/v5.2.0/bin/node" "/Users/Tim/.nvm/versions/node/v5.2.0/bin/npm" "install"
npm ERR! node v5.2.0
npm ERR! npm  v3.5.2

npm ERR! No compatible version found: scrollreveal@^2.2.0
npm ERR! Valid install targets:
npm ERR! 3.0.0
npm ERR!
```

applicable line in package.json
```"scrollreveal": "^2.2.0",```

**Comment by KenanY** [comment]
@rawcreative I believe all versions of `scrollreveal` except `3.0.0` have been unpublished from the registry, so `npm` is doing the right thing here by telling you that the only existing version is `3.0.0`.

**Comment by othiym23** [comment]
@KenanY is correct, so this isn't an issue with npm (although it may be worth enquiring over at [`scrollreveal.js`'.s repo](https://github.com/jlmakes/scrollreveal.js) why they deleted it). I'm going to close this now as a result. Good luck getting things sorted out!
