### ISSUE TITLE
`npm install` doesn't use Git LFS filters

### ISSUE THREAD

**Issue by bmahsman** [npm/npm#10857]
When I run `npm install --save git+ssh://git@github.com:bmahsman/bubblegum.git`, `npm` checks out the text files that `git lfs` puts in place of the actual assets. It appears `npm` isn't using my local user account's `~/.gitconfig`, i.e. the `lfs` filters aren't being used and `git-lfs` is not being called to download the actual files. I think this may be a bug with npm, unless there is something I can do to get it to use my `~/.gitconfig`.

I'm on Windows 7 using npm 2.14.7 and git version 2.6.2.windows.1. I wrote a detailed question over on [superuser](http://superuser.com/questions/999556/how-do-you-setup-npm-to-install-from-a-github-repository-that-uses-git-lfs) that hasn't been answered yet. Thanks for your help!

edit: On second thought, it might not be that `~/.gitconfig` is not being used by npm, but that `.gitattributes` in the repository root is not being read. I don't know how npm gets files without actually appearing to clone the repository, but when you normally do a `git clone` git reads the `.gitattributes` before attempting to get any files and then it knows to call `git-lfs` to get the actual files that match the patterns.

**Comment by bmahsman** [comment]
After poring over the output from `git` and `npm` with `export GIT_TRACE=1` and `npm config loglevel verbose`, I believe I have figured out how to get this to work, at least with GitLab (I have since moved from GitHub to GitLab, which also supports Git LFS).

Step 1. Inside of your repository, run the following command (replace `bubblegum` with the name of your repo) and then commit the resulting `.gitconfig` and push:
```
$ git config -f .gitconfig lfs.url https://gitlab.com/brynn.mahsman/bubblegum.git/info/lfs
```

Step 2. In the directory in which you want to `npm install` your project, run for example:
```
$ npm install -S https://gitlab.com/brynn.mahsman/bubblegum.git
```

The `.gitconfig` you commit to the repository allows the git commands used by `npm install` to know what `lfs.url` to use. I'm not sure if this solution only masks the fact that `npm install` can't figure out the `lfs.url` without you explicitly specifying it in `.gitconfig`. In other words, when I run the command `git clone https://gitlab.com/brynn.mahsman/bubblegum.git`, `git` somehow knows the `lfs.url` even if I don't have the `.gitconfig` in the repository. Would someone please enlighten me as to whether this is something `npm install` should be able to do without having to write this `.gitconfig`?

note: For this to work with GitHub, it would appear that the `lfs.url` to use is: `https://api.github.com/lfs/<user or organization>/<repository name>`, e.g.
```
$ git config -f .gitconfig lfs.url https://api.github.com/lfs/brynn.mahsman/bubblegum
```

**Comment by iarna** [comment]
I'm going to close this in preference to #11151 as we really would like to actually explicitly support git lfs. Thanks for putting together both of these extremely detailed descriptions of the problem space. It should make doing the right thing a lot easier when we start work on it.
