### ISSUE TITLE
Failure to create shrinkwrap file after installing from shrinkwrap

### ISSUE THREAD

**Issue by alistairjcbrown** [npm/npm#10852]
**Steps to recreate:**
1. Have only `package.json` file (no `npm-shrinkwrap.json`)
2. Run `npm install`
3. Run `npm shrinkwrap --dev`
4. Remove `node_modules` (`rm -rf node_modules`)
5. Run `npm install`
6. Run `npm shrinkwrap --dev`

**Expected outcome:**
Shrinkwrap file generated.
Ideally file does not differ from existing shrinkwrap file, but from experience with generating shrinkwrap files with npm v2, this may not be the case with changing "from" values.

**Actual outcome:**
Sub-dependency module is flagged as 'invalid' and 'extraneous'. Module in question is [`nsp`](https://www.npmjs.com/package/nsp).

**Note:** Removing the `nsp` module from the package.json and repeating the steps above were successful - so it looks like it's something to do with the structure of the `nsp` module?

```
> $ npm shrinkwrap --dev
npm ERR! Darwin 13.4.0
npm ERR! argv "/Users/alistairbrown/.nvm/versions/node/v5.2.0/bin/node" "/Users/alistairbrown/.nvm/versions/node/v5.2.0/bin/npm" "shrinkwrap" "--dev"
npm ERR! node v5.2.0
npm ERR! npm  v3.5.2

npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! invalid: have npmlog@2.0.0 (expected: ) /Users/alistairbrown/Documents/project/node_modules/nsp/node_modules/npm-registry-client/node_modules/npmlog
npm ERR! extraneous: npmlog@2.0.0 /Users/alistairbrown/Documents/project/node_modules/nsp/node_modules/npm-registry-client/node_modules/npmlog
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/alistairbrown/Documents/project/npm-debug.log
```

**Comment by pugsley** [comment]
I'm having the same issues: https://github.com/npm/npm/issues/10839

**Comment by sminnee** [comment]
Can you please post a small sample `package.json` where you are seeing this error?
