### ISSUE TITLE
"-bash: protractor: command not found" Issue

### ISSUE THREAD

**Issue by grushler** [npm/npm#10855]
I had all my global packages installed in `/usr/local/lib/node_modules` before, when i had npm v2.14.x. After updating to the latest version of npm v3.3.12, they are being installed in the directory `/Users/xxx/.node/lib` due to which i am getting the following error when i run command for global packages -

```
xxxx-macbook:~ xxx$ protractor conf.js
-bash: protractor: command not found
```

I want the node_modules to get installed in `/usr/local/lib/node_modules` directory. Is there something i can do to fix it? Any help would be appreciated. Thanks

**Comment by girishsortur** [comment]
I updated my npm to latest version (v3.5.2) and issue still persists with all global node_modules that i install. They still are getting installed in `/Users/xxx/.node/lib/node_modules` folder and i get `command not found` issue in my terminal.

However, i was able to fix it temporarily by running command `export PATH="$HOME/.node/bin:$PATH"` in my terminal. But this fix isn't permanent and it vanishes when i close my terminal. I have to run it every time i open a new session of my terminal. Is there a permanent fix for this? Thanks

**Comment by ddykstra** [comment]
Adding this to your .bash_profile will resolve the issue: PATH="$HOME/.node/bin:$PATH"  If you don't have a .bash_profile, see here: https://discussions.apple.com/thread/4149170?start=0&  Hope that helps.
