### ISSUE TITLE
npm install -g mdns2 Error: certificate is not yet valid

### ISSUE THREAD

**Issue by sea35** [npm/npm#10861]
# npm install -g mdns2

> mdns2@2.1.4 install /usr/nodejs/node-v4.2.3-linux-x64/lib/node_modules/mdns2
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: certificate is not yet valid
gyp ERR! stack     at Error (native)
gyp ERR! stack     at TLSSocket.<anonymous> (_tls_wrap.js:1003:38)
gyp ERR! stack     at emitNone (events.js:67:13)
gyp ERR! stack     at TLSSocket.emit (events.js:166:7)
gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:570:8)
gyp ERR! System Linux 3.10.0-229.el7.x86_64
gyp ERR! command "/usr/nodejs/node-v4.2.3-linux-x64/bin/node" "/usr/nodejs/node-v4.2.3-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/nodejs/node-v4.2.3-linux-x64/lib/node_modules/mdns2
gyp ERR! node -v v4.2.3
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Linux 3.10.0-229.el7.x86_64
npm ERR! argv "/usr/nodejs/node-v4.2.3-linux-x64/bin/node" "/usr/nodejs/node-v4.2.3-linux-x64/bin/npm" "install" "-g" "mdns2"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

**Comment by KenanY** [comment]
@sea35 Is your system time correct? Usually that is what I have noticed to be the cause of this issue for other users.

**Comment by sea35** [comment]
@KenanY Thank you, the system time is wrong
