### ISSUE TITLE
install production deps from shrinkwrap and dev deps from package.json?

### ISSUE THREAD

**Issue by creynders** [npm/npm#10863]
Is it possible to install the production deps from npm-shrinkwrap.json and the dev deps from package.json?

The use case is the following: I want to shrinkwrap my production deps, to ensure all my production app instances use the exact same versions. However at the front of my deployment flow I run integration tests and these need the development deps.
It seems to me I could `npm shrinkwrap --dev` but in this case my dev deps will be included on my production envs as well. Or I can `rm npm-shrinkwrap.json` on my test env, but then it won't be using the exact same versions of the production deps as will be installed in the production envs.

**Comment by joanniclaborde** [comment]
Try with `NODE_ENV="" npm install` in your test environment, `NODE_ENV` is probably set to `production`.
