### ISSUE TITLE
Path problems on Windows in cygwin

### ISSUE THREAD

**Issue by vcernomschi** [npm/npm#10866]
[ Since I can't request a reopening of #2465, I'm submitting a duplicate. ]

When attempting to use the npm script under Cygwin in Windows, I receive the following error:

```code
module.js:339
    throw err;
    ^
Error: Cannot find module '/cygdrive/c/ProgramData/npm/isparta'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Function.Module.runMain (module.js:467:10)
    at Object.<anonymous> (C:\ProgramData\npm\node_modules\babel\lib\_babel-node.js:144:25)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)

```

I use node v4.2.2 with npm 2.14.7.

I ran the following command: 
```shell
 babel-node `which isparta` cover --include 'lib/**/*.js' _mocha -- 'test/**/*.spec.js' --reporter spec --ui tdd --recursive
``` 

I have installed successfully isparta, babel-node:

Sparta from cygwin terminal:
```shell
$ which isparta
/cygdrive/c/ProgramData/npm/isparta
```
Sparta from windows cmd:
```shell
C:\Users>where isparta
C:\ProgramData\npm\isparta
C:\ProgramData\npm\isparta.cmd
```

babel-node from cygwin terminal:
```shell
$ which babel-node
/cygdrive/c/ProgramData/npm/babel-node
```
babel-node from windows cmd:
```shell
C:\Users>where babel-node
C:\ProgramData\npm\babel-node
C:\ProgramData\npm\babel-node.cmd
```

**Comment by ddimitrioglo** [comment]
I have the same issue when I want to use any global module on my W7 machine.
But it also exists and can be tested by using `which` command.

**Comment by Lourenc** [comment]
I'm having the same issue

**Comment by eistrati** [comment]
+1 this problem gets replicated on my computer as well

**Comment by othiym23** [comment]
Nothing has changed in the last three years, and if anything supporting Cygwin along with the other ways of using Node.js and npm on Windows has only gotten more difficult, due to changes to the Cygwin build of Git.

To quote @isaacs:
> Cygwin is not supported. Please use the windows native build with cmd, powershell, or msys git bash.
