### ISSUE TITLE
shashum check failed

### ISSUE THREAD

**Issue by Abhinav2510** [npm/npm#10865]
I am trying to install ionic framework using command
**npm install -g ionic**
but I am getting below errors

C:\Users\765071>npm install -g ionic
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ionic"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.7

npm ERR! shasum check failed for C:\Users\765071\AppData\Local\Temp\npm-3992-813
71b3c\registry.npmjs.org\ionic\-\ionic-1.7.12.tgz
npm ERR! Expected: 87cdf5b9ff748009182a10c61bbc3a39a000fe59
npm ERR! Actual:   d268ba013637c3b552f40e818bb1f43134b0770c
npm ERR! From:     https://registry.npmjs.org/ionic/-/ionic-1.7.12.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\765071\npm-debug.log

**Comment by KenanY** [comment]
@Abhinav2510 Have you tried running `npm cache clean`?

**Comment by Abhinav2510** [comment]
@KenanY 
Thanks alot that solved my problem.

**Comment by shiva2492** [comment]
I am still having the issues after using "npm cache clean"?

**Comment by Abhinav2510** [comment]
@shiva2492
Try setting hhtp n https proxy using 

**npm set config http-proxy http://proxy.compony.com:8080**

**npm set config https-proxy http://proxy.compony.com:8080**

Notr there is no https in url for https-proxy

**Comment by shiva2492** [comment]
what will go in this url that you have given here?
I think I have some other issues Maybe I have installed npm from nvm and n both that is why its causing it to look in wrong path.maybe i should try uninstalling all and go for a fresh install..
do you know a way to completely uninstall npm ,nvm ,n ionic if any traces of it , same for cordova complete uninstall from ubuntu 12.04.

**Comment by Abhinav2510** [comment]
That depends if your network is using any kind of proxy..
If its corporate proxy then you may have to use above commands.

I am not sure abt fresh installation in ubuntu env but if u wanna remove trace of npm there will be .npmrc in ur local home directory. You can delete that one n try installing node npm ionic cordova again...

If this doesnt solve your problem plese post new issue with npm-debug generated as an attachment to new issue

**Comment by shiva2492** [comment]
[npm-debug.txt](https://github.com/npm/npm/files/72228/npm-debug.txt)
see its here...
