### ISSUE TITLE
showing npm ERR! in windows command line

### ISSUE THREAD

**Issue by kishangpatel** [npm/npm#10860]
i am trying to run existing angular 2 project demo from 
https://github.com/Microsoft/ngconf2015demo
Unfortunately, getting npm ERR!
Can anybody explain what's going on !!
I am attaching npm-debug.log file here

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'go' ]
2 info using npm@2.14.7
3 info using node@v4.2.3
4 verbose stack Error: missing script: go
4 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:142:19)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:58:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:345:5
4 verbose stack     at checkBinReferences_ (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:309:45)
4 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:343:3)
4 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:113:5)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:300:12
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:76:16
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
5 verbose cwd C:\Users\Kishan\iCloudDrive\angular2\ngconf2015demo
6 error Windows_NT 10.0.10240
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "go"
8 error node v4.2.3
9 error npm  v2.14.7
10 error missing script: go
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@kishangpatel Why run `npm run go`? Shouldn't you simply follow the instructions in that repository's `README` file? For what it is worth, `npm` is giving you that error because you are trying to run the `"go"` script but such a script does not exist in [that `package.json`](https://github.com/Microsoft/ngconf2015demo/blob/d18400a4c78b5c4793a652c52284f4e4c5ca7257/package.json). Perhaps the documentation on [`npm run`](https://docs.npmjs.com/cli/run-script) and [scripts](https://docs.npmjs.com/misc/scripts) can clear things up as well?

**Comment by kishangpatel** [comment]
@KenanY Thank you so much for clarification , i'm able to start now

**Comment by kishangpatel** [comment]
Hi..
Now I'm able to run Todo app on my computer.
but how should I run that online just like on my own website, I'm trying to see that if I start my own my app and try to run my own website then what's procedure for that
I simply copy "ngconf2015demo" this folder and paste it to my root website and when I opened "index.html" it simply shows "Loading..." on web page.
Appreciate any help,
Thanks.

**Comment by KenanY** [comment]
Closing since the original issue has been resolved. A webpage not loading is not the fault of `npm` so if you are still seeing that issue I would suggest finding other users who have done the same todo app and asking them for help.
