### ISSUE TITLE
npm logout leaves private packages in cache

### ISSUE THREAD

**Issue by seangarner** [npm/npm#10877]
When using `npm logout` it leaves behind all the cached responses for the registry and tarballs.  This can  lead to confusion if then installing a private module after having logged out:
- UX side; mild panic because unauthenticated users can install my private packages.  
- There's the possibility that a user might forget that they've logged out and continue installing packages which use the cache (therefore could actually be out of date, since it's using the cached registry call).  
- Finally a mild security issue because npm is leaving behind private data once logged out.

Ideally I'd expect the cache to be cleared of any private data as you log out.  But a warning that private data may exist and the user may want to run `npm cache clear` on logout would also be an acceptable solution to me.

**Comment by Niffy** [comment]
I concur I had a heart attack when I was able to still do this after logging out!
Thankfully you provided the solution of npm cache clear.
