### ISSUE TITLE
Unable to install eslint on windows 7 using >>>npm install -g eslint 

### ISSUE THREAD

**Issue by surajhp** [npm/npm#10873]
npm version installed is 2.14.7

I am using following command for installing ESLint

> > > npm install -g eslint

![untitled](https://cloud.githubusercontent.com/assets/6647542/11889987/442367b6-a575-11e5-99f8-baf954139467.png)

The installation starts but does not proceed. It runs indefinitely. It shows no error.

Is there any other alternative for installing eslint ???

**Comment by frontendthug** [comment]
I have same troubles, but on Linux and with other packages. I think, it is not our problem
