### ISSUE TITLE
package `@2.0.0-pre` does not satisfy peerDep! Wants `@*`

### ISSUE THREAD

**Issue by erikmueller** [npm/npm#10876]
I do not know if this is a bug or intended behaviour but I thought that `*` should satisfy everything (just be there).

The Story: I have `unexpected-sinon` installed which has `unexpected@10` and `sinon@*` as a peerDependency. My project has `sinon` listed `@2.0.0-pre` which seems not so satisfy `unexpected-sinon`. Using `sinonjs/sinon#master` yields the same result. Anyway setting `sinon@1.17.2` works (at least for `npm i`).

```sh
npm ERR! Darwin 15.2.0
npm ERR! argv "/Users/emueller/.nvm/versions/node/v4.2.3/bin/node" "/Users/emueller/.nvm/versions/node/v4.2.3/bin/npm" "i"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.7
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package sinon@2.0.0-pre does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer unexpected-sinon@9.0.4 wants sinon@*
```

Should be reproducible via 
`npm i --save-dev --save-exact sinon@2.0.0-pre unexpected unexpected-sinon`

Anyone any clue if I'm doing sth wrong?
Thanks in advance.

**Comment by KenanY** [comment]
@erikmueller I believe this is intended behavior. `*` does not match prereleases (unless the package in question _only_ has prereleases) because it does not have a prerelease tag, which is necessary if you want to explicitly tell `node-semver` that you want to allow prereleases.

> If a version has a prerelease tag (for example, `1.2.3-alpha.3`) then it will only be allowed to satisfy comparator sets if at least one comparator with the same `[major, minor, patch]` tuple also has a prerelease tag.

https://github.com/npm/node-semver#prerelease-tags

A few months ago when this was not the case, it was considered a bug: https://github.com/npm/node-semver/issues/123

**Comment by erikmueller** [comment]
Yeah, I found that in the changelog after posting that issue (and here I thought I investigated this before doing so, sry). So does this mean there's no possibility to say "I don't care what version you install even if it's a pre-release"? Like `sinon@^*` or sth.

Thanks for the fast reply btw.

**Comment by KenanY** [comment]
@erikmueller 

> So does this mean there's no possibility to say "I don't care what version you install even if it's a pre-release"?

I think that is correct.
