### ISSUE TITLE
plz let me knw the solution on this

### ISSUE THREAD

**Issue by AmitGolhar** [npm/npm#10878]
mint@mint ~ $ npm install -g adapt-cli
npm ERR! git clone --template=/home/mint/.npm/_git-remotes/_templates --mirror git://github.com/adaptlearning/download.git /home/mint/.npm/_git-remotes/git-github-com-adaptlearning-download-git-d0f0f50f: Cloning into bare repository '/home/mint/.npm/_git-remotes/git-github-com-adaptlearning-download-git-d0f0f50f'...
npm ERR! git clone --template=/home/mint/.npm/_git-remotes/_templates --mirror git://github.com/adaptlearning/download.git /home/mint/.npm/_git-remotes/git-github-com-adaptlearning-download-git-d0f0f50f: 
npm ERR! git clone --template=/home/mint/.npm/_git-remotes/_templates --mirror git://github.com/adaptlearning/download.git /home/mint/.npm/_git-remotes/git-github-com-adaptlearning-download-git-d0f0f50f: fatal: unable to connect to github.com:
npm ERR! git clone --template=/home/mint/.npm/_git-remotes/_templates --mirror git://github.com/adaptlearning/download.git /home/mint/.npm/_git-remotes/git-github-com-adaptlearning-download-git-d0f0f50f: github.com[0: 192.30.252.128]: errno=Connection refused
npm ERR! Linux 3.2.0-23-generic
npm ERR! argv "node" "/home/mint/.nvm/v0.10.33/bin/npm" "install" "-g" "adapt-cli"
npm ERR! node v0.10.33
npm ERR! npm  v3.5.2
npm ERR! code 128

npm ERR! Command failed: fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.128]: errno=Connection refused
npm ERR! 
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mint/npm-debug.log

**Comment by deestan** [comment]
This is a network issue on your end. You may have a firewall blocking the `git` protocol.  Check with your network administrator.

**Comment by AmitGolhar** [comment]
Thnx deestan

**Comment by KenanY** [comment]
Closing as resolved.
