### ISSUE TITLE
Cannot install RethinkDB from latest sources on OS X Yosemite

### ISSUE THREAD

**Issue by sreekaranugu** [npm/npm#10870]
I'm keep getting this error while trying to install on OS X Yosemite. I can't get rid of this, as there isn't much information related to it. 

1. git clone URL
2. ./configure --allow-fetch
3. make

The error is:

npm ERR! argv "/usr/local/Cellar/node/5.3.0/bin/node" "/usr/local/bin/npm" "--userconfig" "/Users/sreekar/github/rethinkdb/rethinkdb/mk/support/config/npm.conf" "--cache" "/Users/sreekar/github/rethinkdb/rethinkdb/external/npm_cache-SeFruCOS" "--no-registry" "install" "/Users/sreekar/github/rethinkdb/rethinkdb/external/admin-deps_2.0.3"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12

npm ERR! registry URL is required
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/node/5.3.0/bin/node" "/usr/local/bin/npm" "--userconfig" "/Users/sreekar/github/rethinkdb/rethinkdb/mk/support/config/npm.conf" "--cache" "/Users/sreekar/github/rethinkdb/rethinkdb/external/npm_cache-SeFruCOS" "--no-registry" "install" "/Users/sreekar/github/rethinkdb/rethinkdb/external/admin-deps_2.0.3"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12

npm ERR! registry URL is required
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/sreekar/github/rethinkdb/rethinkdb/build/external/admin-deps_2.0.3/npm-debug.log

Full error log: ./build/external/admin-deps_2.0.3_install.log
make[1]: *** [build/external/admin-deps_2.0.3/bin/gulp] Error 1
make: *** [make] Error 2

Thanks

**Comment by KenanY** [comment]
Hmm, has running [`npm install --no-registry`](https://github.com/rethinkdb/rethinkdb/blob/0ec7cc90061bb7cd4f38b52cfea9bc9767a78d5f/mk/support/pkg/npm-pkg.inc#L52) ever worked? I can't imagine `npm` working without a registry.

**Comment by sreekaranugu** [comment]
I'm new to npm and node. I'm trying desparately to "REMOVE" that no registry argument from 2 hours without luck :(

**Comment by sreekaranugu** [comment]
This is being invoked by "make" and I cannot find where to modify it

**Comment by williamstein** [comment]
I'm getting this when building the current v2.2.x branch on Ubuntu 15.10.  My workaround was to edit this file `mk/support/pkg/npm-pkg.inc` and just remove `--no-registry`.   Editing this file WORKED.

It's possible that this problem was caused by something funny about my nodejs install.  I'm using these versions of things:
```
salvus@compute6-us:/tmp/rethinkdb$ cat /etc/issue
Ubuntu 15.10 \n \l
salvus@compute6-us:/tmp/rethinkdb$ uname -a
Linux compute6-us 4.2.0-22-generic #27-Ubuntu SMP Thu Dec 17 22:57:08 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
salvus@compute6-us:/tmp/rethinkdb$ node -v
v5.3.0
salvus@compute6-us:/tmp/rethinkdb$ npm -v
3.3.12
```
