### ISSUE TITLE
Very slow loading the dependencies

### ISSUE THREAD

**Issue by frontendthug** [npm/npm#10879]
I don't know, what is wrong, but today I found 'npm install' command very slow.
Is this problems with  a server or what is this?
I use node 5.3.0 and npm 3.5.1
The download speed is reduced when it comes to word "network", 
you can see this at the screenshot below.
p.s. sorry for my English.

![npm](https://cloud.githubusercontent.com/assets/16205687/11896217/656ea9a4-a5a6-11e5-84f0-0b0c39aa6d35.png)

Linux: Ubuntu i386 (Debian, not ok), Manjaro i686 (Arch, not ok);
Windows: 7(not ok);

**Comment by ivan-kolmychek** [comment]
Yeah, got the same problem here.
```
$ node -v
v5.3.0

$ npm -v
3.5.2
```

**Comment by metz0r** [comment]
I am also experiencing up to 3-4x longer install times than normal. Any info on this?

**Comment by brunolanevik** [comment]
^

**Comment by metz0r** [comment]
If I set the log level to info, I see these timeout errors throughout npm install:

npm info retry will retry, error on last attempt: Error: connect ETIMEDOUT 185.31.17.162:443

**Comment by gritzko** [comment]
same here

**Comment by ZoRDoK** [comment]
me too

**Comment by ppascher** [comment]
same here

**Comment by vilhelmjosander** [comment]
Same for me as well. Connection timeouts all the way through...

**Comment by fleetster** [comment]
Same here

**Comment by metz0r** [comment]
Works now

**Comment by frontendthug** [comment]
Yep, I confirm

**Comment by fleetster** [comment]
Confirmed

**Comment by actorius** [comment]
Have the same problem, the download speed is reduced when it comes to word "network".
curl working fine, speed same as say provider.

>Linux 3.19.0-32-generic #37~14.04.1-Ubuntu SMP Thu Oct 22 09:41:40 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Can't install ember-cli more 2 hours, lol

**Comment by igorzg** [comment]
+1

**Comment by hamzazar** [comment]
same here after updating npm and node on ubuntu 14.04 64bit
npm -v
3.3.12
node -v
v5.4.0

**Comment by koloboid** [comment]
expecting same troubles now:

>npm info retry will retry, error on last attempt: Error: connect ETIMEDOUT 185.31.17.162:443

tried from different networks (cities) - the same:

>wget  185.31.17.162:443
>--2016-01-10 12:05:14--  http://185.31.17.162:443/
>Connecting to 185.31.17.162:443... connected.
>HTTP request sent, awaiting response... No data received.
>Retrying.

**Comment by keffidesign** [comment]
The same for me

>npm info retry will retry, error on last attempt: Error: connect ETIMEDOUT 185.31.17.162:443
 
```sh
uname -a
```

> MINGW64_NT-10.0 DESKTOP-30Q35JH 2.4.0(0.292/5/3) 2016-01-05 14:13 x86_64 Msys

```sh
$ npm -v
```

> 3.3.12

```sh
$ node -v
```

> v5.4.0

**Comment by kacpersaw** [comment]
Add `registry = https://skimdb.npmjs.com/registry` to .npmrc and try again :)

**Comment by naltatis** [comment]
Adding this made a huge difference. No strange hangers any more.

**Comment by jt3k** [comment]
i run following command in root of my project and it fix problem with slow loading deps. 
```
echo "registry = https://skimdb.npmjs.com/registry" >>  .npmrc
```
but how to fix this problem globaly ?
