### ISSUE TITLE
warning and errors messages from semantic-ui installation from NPM package

### ISSUE THREAD

**Issue by bidie** [npm/npm#10889]
npm install semantic-ui command generates errors and warnings messages connected to proxy settings on my system.Even though i used default settings. please 
[npm-debug.pdf](https://github.com/npm/npm/files/67235/npm-debug.pdf)
how can i fix this

**Comment by busches** [comment]
As you mentioned, you need to set your proxy. You can find a lot of instructions on how to do this online. Here's a sample one: https://jjasonclark.com/how-to-setup-node-behind-web-proxy

cc\ @KenanY
