### ISSUE TITLE
npm install fails on npm when invoked by a module that is already installed

### ISSUE THREAD

**Issue by rmg** [npm/npm#10888]
Here's my usage:
1. `git clone $module`
2. `cd $module`
3. `npm install my-ci-builder`
4. `./node_modules/.bin/my-ci-bulder`
   1. tool does sanity checks and other stuff
   2. tool runs `npm install` to install $module's deps
      1. npm fails when it tries to move `node_modules/my-ci-builder`

I haven't looked at the npm code yet, but I'm guessing it is either trying to prune or dedupe the previously installed non-dependency modules. This isn't causing any problems on non-Windows platforms, but that is likely due to POSIX fs access semantics which allow for removing files that are in use.

This problems is specific to npm-v3 on Windows.

**Comment by busches** [comment]
Can you provide the version of `npm` you're using and a debug-log?
