### ISSUE TITLE
3rd party dependencies are not installing in npm 2.14.7 properly

### ISSUE THREAD

**Issue by toddw** [npm/npm#10893]
I'm running on OS X. With npm 2.14.7, if you run `npm install gluestick -g`and look in `/usr/local/lib/node_modules/gluestick/node_modules/history/` you will see that `node_modules` is missing.

However, if you clone our repo https://github.com/TrueCar/gluestick and run `npm install . -g` and then go to `/usr/local/lib/node_modules/gluestick/node_modules/history/` you will see that the `node_modules` is not missing.

Any idea why this is happening? This causes a bunch of errors when trying to run our CLI. Currently, the solution is to tell people to run `cd /usr/local/lib/node_modules/gluestick/node_modules/history && sudo npm install`.

Is this a bug with NPM or are we doing something wrong with our project? Anyone know of any work arounds?

**Comment by KenanY** [comment]
@toddw Does this also occur with newer versions of `npm` (specifically I'm curious about `>=2.14.10`)?

**Comment by toddw** [comment]
When using the version of npm that ships with node 5+ it doesn't seem to be a problem. In my tests it seems to be npm that ships with node 4.x.x that is a problem
