### ISSUE TITLE
err while trying to solve 5 min quick start on angular.io

### ISSUE THREAD

**Issue by kishangpatel** [npm/npm#10891]
i am just starting to learn and come across 5 min quick start on angular.io https://angular.io/docs/ts/latest/quickstart.html# 
this is first example 
i saved this on plunker here
http://plnkr.co/edit/iy7BX5?p=info

now i am doing everything what it says in tutorial and at last at "compile and run!" it says type "npm start" in command line
when i do that it gives me npm ERR! with this npm-debug.log file i am attaching here
=====
0 info it worked if it ends with ok
1 verbose cli [ 'c:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.14.7
3 info using node@v4.2.3
4 verbose stack Error: missing script: start
4 verbose stack     at run (c:\Program Files\nodejs\node_modules\npm\lib\run-script.js:142:19)
4 verbose stack     at c:\Program Files\nodejs\node_modules\npm\lib\run-script.js:58:5
4 verbose stack     at c:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:345:5
4 verbose stack     at checkBinReferences_ (c:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:309:45)
4 verbose stack     at final (c:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:343:3)
4 verbose stack     at then (c:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:113:5)
4 verbose stack     at ReadFileContext.<anonymous> (c:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:284:20)
4 verbose stack     at ReadFileContext.callback (c:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:76:16)
4 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:303:13)
5 verbose cwd C:\Users\Kishan\iCloudDrive\angular2\angular2-quickstart
6 error Windows_NT 10.0.10240
7 error argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
8 error node v4.2.3
9 error npm  v2.14.7
10 error missing script: start
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
=======
anybody Please help...

**Comment by KenanY** [comment]
@kishangpatel Did you add the `package.json` as specified in that tutorial?

**Comment by kishangpatel** [comment]
yes i did add package.json
here's its content, same as tutorial
====
{
  "name": "angular2-quickstart",
  "version": "1.0.0",
  "scripts": {
    "tsc": "tsc",
    "tsc:w": "tsc -w",
    "lite": "lite-server",
    "go": "concurrent \"npm run tsc:w\" \"npm run lite\" "
  },
  "license": "ISC",
  "dependencies": {
    "angular2": "2.0.0-beta.0",
    "systemjs": "0.19.6",
    "es6-promise": "^3.0.2",
    "es6-shim": "^0.33.3",
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-beta.0",
    "zone.js": "0.5.10"
  },
  "devDependencies": {
    "concurrently": "^1.0.0",
    "lite-server": "^1.3.1",
    "typescript": "^1.7.3"
  }
}

**Comment by KenanY** [comment]
@kishangpatel When I look at the page, I see the script called `"start"` not `"go"` as you have it.

![](https://i.imgur.com/mP527A3.png)

**Comment by kishangpatel** [comment]
@KenanY Thank you, Solved!
@KenanY Can you help me on this issue
https://github.com/npm/npm/issues/10860
I opened this again,
if you have any documentation or link on how to run on hosting server for angularJS2 project !
Thanks.

**Comment by othiym23** [comment]
Closing as resolved.
