### ISSUE TITLE
npm ERR! Failed to parse json

### ISSUE THREAD

**Issue by ismael-rivera** [npm/npm#10896]
Trying to get some simple demos done for my projects portfolio. All was going well. I've done this a million times (true, last time I did this was about a month ago). I created a package.json to get my gruntjs plugins rolling. Did the npm install. Nothing seems to work. I can't figure it out? Am I doing something wrong?

This is my package.json:

{
  "name": "scroll2bottomScrollupNanimate",
  "version": "0.1.0",
  "devDependencies": {
    "grunt": "~0.4.5",
    "grunt-contrib-jshint": "~0.10.0",
    "grunt-contrib-watch": "~0.4.3",
  }
}

and this is my output:

npm ERR! Failed to parse json
npm ERR! Unexpected token }
npm ERR! File: /Users/ismaelrivera/Sites/demos.speggo/Scroll2bottomScrollupNanimate/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! System Darwin 10.8.0
npm ERR! command "/usr/local/Cellar/node/0.10.26/bin/node" "/usr/local/bin/npm" "install" "grunt" "--save-dev"
npm ERR! cwd /Users/ismaelrivera/Sites/demos.speggo/Scroll2bottomScrollupNanimate
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! file /Users/ismaelrivera/Sites/demos.speggo/Scroll2bottomScrollupNanimate/package.json
npm ERR! code EJSONPARSE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/ismaelrivera/Sites/demos.speggo/Scroll2bottomScrollupNanimate/npm-debug.log
npm ERR! not ok code 0

Here is my log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/0.10.26/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install' ]
2 info using npm@1.4.3
3 info using node@v0.10.26
4 error install Couldn't read dependencies
5 error Failed to parse json
5 error Unexpected token }
6 error File: /Users/ismaelrivera/Sites/demos.speggo/Scroll2bottomScrollupNanimate/package.json
7 error Failed to parse package.json data.
7 error package.json must be actual JSON, not just JavaScript.
7 error
7 error This is not a bug in npm.
7 error Tell the package author to fix their package.json file. JSON.parse
8 error System Darwin 10.8.0
9 error command "/usr/local/Cellar/node/0.10.26/bin/node" "/usr/local/bin/npm" "install"
10 error cwd /Users/ismaelrivera/Sites/demos.speggo/Scroll2bottomScrollupNanimate
11 error node -v v0.10.26
12 error npm -v 1.4.3
13 error file /Users/ismaelrivera/Sites/demos.speggo/Scroll2bottomScrollupNanimate/package.json
14 error code EJSONPARSE
15 verbose exit [ 1, true ]

Please someone, let me know what I am doing wrong here? Thanks.

**Comment by bramdevries** [comment]
You need to remove the `,` on the last line of your dependencies (`"grunt-contrib-watch": "~0.4.3",`) JSON doesn't allow trailing commas

**Comment by themicmac** [comment]
Yup! That was it. I can't believe I didn't see it. Clearly that's a bad habit I gotta drop. Much thanks.

**Comment by Deepakdubey90** [comment]
Great, It works for me . Thanks

**Comment by abigaleypc** [comment]
Great, It works for me . Thanks

**Comment by KenanY** [comment]
Closing as resolved.
