### ISSUE TITLE
npm ERR! registry error parsing json, npm ERR! Unexpected end of input windows 10

### ISSUE THREAD

**Issue by magiccreater** [npm/npm#10895]
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Dell\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.2.3
npm ERR! npm  v3.5.2

npm ERR! Unexpected end of input

**Comment by KenanY** [comment]
@magiccreater Are you still seeing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
