### ISSUE TITLE
npm ERR! error:0906D06C:PEM routines:PEM_read_bio:no start line

### ISSUE THREAD

**Issue by gr33nc0d3** [npm/npm#10897]
C:>npm install -g cordova ionic
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Users\Effendi\AppData
\Roaming\npm\node_modules\npm\bin\npm-cli.js" "install" "-g" "cordova" "io
nic"
npm ERR! node v4.2.3
npm ERR! npm  v3.5.2

npm ERR! error:0906D06C:PEM routines:PEM_read_bio:no start line
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Users\Effendi\AppData
\Roaming\npm\node_modules\npm\bin\npm-cli.js" "install" "-g" "cordova" "io
nic"
npm ERR! node v4.2.3
npm ERR! npm  v3.5.2

npm ERR! error:0906D06C:PEM routines:PEM_read_bio:no start line
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

**Comment by Berg-it** [comment]
type this line  npm set registry `http://registry.npmjs.org/ `  and after that try again with 
`npm install -g cordova ionic`

I assume that your certificate is expired

**Comment by Ganesan786** [comment]
Thank you @Berg-it Berg-it . It's really fixed my issue.

**Comment by chakrihacker** [comment]
#16071

**Comment by aquibyatoo** [comment]
npm set registry http://registry.npmjs.org/ worked for me thx a lot

**Comment by KonstantinVictorovichChervonyj** [comment]
Hello, my is Kostya. Im learning Angular. I tryed install angular/cli, but i got error. I dont know what to do. Help me please..... Im beginner developer.

C:\Users\Костя>npm install -g @angular/cli
npm ERR! Windows_NT 10.0.17134
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10

npm ERR! error:0906D06C:PEM routines:PEM_read_bio:no start line
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Костя\npm-debug.log
