### ISSUE TITLE
Install local dependencies from remote package - broken

### ISSUE THREAD

**Issue by walea3** [npm/npm#10909]
This issue is related to #9205.

I'm currently able to reproduce the 'install from registry' issue with `@3.3.1` and `@3.5.2` - using @timoxley's example, run `npm install https://github.com/timoxley/npm3-localdeps-issue.git` or `npm install npm3-localdeps-issue`

However, it's not an issue if you clone the repo and then `npm install ../npm3-localdeps-issue`, for example.

It looks as though the local dependencies aren't being resolved from the [temp directory](https://github.com/npm/npm/blob/master/lib/cache/add-remote-git.js#L302) _(the repo is cloned into)_ but from the destination directory _(`node_modules/npm3-localdeps-issue`)_ which hasn't been created yet.

---

`node@5.0.0`
`npm@3.5.2`

**Comment by caod123** [comment]
I'm also having issues with this. Any updates? @othiym23 @iarna

**Comment by SteveFenn** [comment]
I'm having an issue with this at the moment, has there been any updates?

**Comment by fardream** [comment]
Running into same issue; node@5.0.0 npm@3.3.6
