### ISSUE TITLE
Using npm 3 with nodejs 4

### ISSUE THREAD

**Issue by dennisjac** [npm/npm#10900]
It seems nodejs and npm are strongly coupled (at least the latest blog entry text "node 5 has shipped with npm 3" suggests this). Is there a way around this?
I'd like keep using nodejs 4 for now for stability reasons but I'm fine using a more experimental approach when it comes to tooling and I want to make use of the new features of npm 3.
So why does this strong coupling exist and is there an official way to use any npm version X with any node version?

**Comment by KenanY** [comment]
>  is there an official way to use any npm version X with any node version

```
npm install -g npm@X
```

**Comment by dennisjac** [comment]
Doesn't that clash with the npm that is shipped with node?

**Comment by KenanY** [comment]
@dennisjac Well, yeah it would overwrite it. I think that is better than having two different versions of `npm` installed, no?

**Comment by dennisjac** [comment]
Overwriting npm2 sounds like a really ugly workaround. I guess the question I'm really asking is why is npm included with nodejs at all? I see no technical reason for this and it creates problems when you want to pair different releases of nodejs and npm.

**Comment by aredridel** [comment]
Because node is not very useful without, and npm needs npm to install itself unless you want to make completely out of band installers.

But it's not overwriting: It's upgrading npm. That's supported and encouraged.

**Comment by dennisjac** [comment]
If overwriting npm is explicitly encouraged then that's fine.

I usually consume nodejs via rpm and in my distribution of choice Fedora npm is also included in the nodejs package which is more of a problem because there overwriting is not an option.
I'm going to take this up with the maintainers there and see if they are willing to separate npm from nodejs and then pull in npm via virtual dependeny.
