### ISSUE TITLE
Error: Attempt to unlock which hasn't been locked

### ISSUE THREAD

**Issue by MurrayBakerWebDeveloper** [npm/npm#10905]
```
npm ERR! Please include the following file with any support request:
npm ERR!     /Users/MurrayBaker89/npm-debug.log

.LOG not transferrable:
Listed command line errors include:

npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7"

npm WARN locking Error: EACCES: permission denied, open '/Users/MurrayBaker89/.npm/_locks/loopback-connector-mongo-f597f88e8782a26b.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/MurrayBaker89/.npm/_locks/loopback-connector-mongo-f597f88e8782a26b.lock failed { [Error: EACCES: permission denied, open '/Users/MurrayBaker89/.npm/_locks/loopback-connector-mongo-f597f88e8782a26b.lock']

Last login: Sun Dec 20 17:50:05 on ttys001
Murrays-MacBook-Pro:~ MurrayBaker89$ npm install
npm ERR! install Couldn't read dependencies
npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! path /Users/MurrayBaker89/package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno -2
npm ERR! syscall open

npm ERR! package.json ENOENT: no such file or directory, open '/Users/MurrayBaker89/package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/MurrayBaker89/npm-debug.log
```

**Comment by KenanY** [comment]
@nuku89 Does `/Users/MurrayBaker89/package.json` exist? Also you might want to try

``` sh
sudo chown -R $(whoami) "$HOME/.npm"
```

**Comment by nuku89** [comment]
Yes, I have the JSON file, tried the command you recommended and it wasn’t rejected..
npm install now results with: 

.pm WARN deprecated gulp-webpack@1.5.0: Renamed to https://www.npmjs.com/package/webpack-stream
pm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what’

> history@1.17.0 postinstall /Users/MurrayBaker89/Documents/grandparent/parent/FreeCodeCamp/node_modules/history
> node ./npm-scripts/postinstall.js

npm WARN peerDependencies The peer dependency kerberos@~0.0 included from mongodb-core will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.

> history@1.12.3 postinstall /Users/MurrayBaker89/Documents/grandparent/parent/FreeCodeCamp/node_modules/react-router/node_modules/history
> node -e "require('fs').stat('lib', function (e, s) { process.exit(e || !s.isDirectory() ? 1 : 0) })" || npm run build

**Comment by KenanY** [comment]
@nuku89 Looks like no more errors :) just a few warnings.

You can find what modules are using those deprecated modules by running `npm ls gulp-webpack`, for example.

The `peerDependencies` warning is a bit better in that it explains the situation and how to solve it :)

**Comment by othiym23** [comment]
Closing as resolved / abandoned. @MurrayBakerWebDeveloper, please open new issues if you encounter further problems with npm. Thanks to you for your time and @KenanY, as always, for pitching in!
