### ISSUE TITLE
Express cannot initialize a project with 'é' as special characters in the name of the project.

### ISSUE THREAD

**Issue by Fr33Radical** [npm/npm#10918]
Removing that character resolve the problem but the name is no more significative.
I used eclipse IDE for C/C++ Developers with node.js plugins installed.
Version: Mars.1 Release (4.5.1)
Build id: 20150924-1200

Plus npm won't be able to install the express module in the repository neither because of the name of the project but will work fine if it is not generated by eclipse.

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose node symlink C:\Program Files (x86)\nodejs\\node.exe
5 error install Couldn't read dependencies
6 verbose stack Error: Invalid name: "D�_website"
6 verbose stack     at ensureValidName (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\normalize-package-data\lib\fixer.js:322:15)
6 verbose stack     at Object.module.exports.fixNameField (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\normalize-package-data\lib\fixer.js:211:5)
6 verbose stack     at C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\normalize-package-data\lib\normalize.js:30:38
6 verbose stack     at Array.forEach (native)
6 verbose stack     at normalize (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\normalize-package-data\lib\normalize.js:29:15)
6 verbose stack     at final (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:368:33)
6 verbose stack     at then (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:127:33)
6 verbose stack     at C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:267:40
6 verbose stack     at evalmachine.<anonymous>:334:14
6 verbose stack     at C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:102:5
7 verbose cwd C:\Users\DÉ\Documents\DÉ_website
8 error Windows_NT 6.1.7601
9 error argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
10 error node v0.12.2
11 error npm  v2.7.4
12 error Invalid name: "D�_website"
13 error If you need help, you may report this error at:
13 error     <https://github.com/npm/npm/issues>
14 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
relevant: https://github.com/npm/npm/issues/10817

**Comment by KenanY** [comment]
@Fr33Radical It has been a few months; are you still seeing this issue? The issue I linked to back in December has some details on why non-ASCII characters are not allowed in packages names (in addition to capital letters).

**Comment by Fr33Radical** [comment]
I've not upgraded node since a while. I've not been coding in node.js thought. I've change my path so it  does not contain any non-ASCII characters. I'm on a stand by for this thread now.
