### ISSUE TITLE
Unable to install ionic and cordova on Windows 7

### ISSUE THREAD

**Issue by bob1457** [npm/npm#10913]
I have problems to install ionic and cordova on my Windows 7 machine.

I have visual studio 2015 installed with cordova tools, but when I was trying to install ionic through npm, I got error and asked me to re-run the command as root/Administrator. I runbot  Windows command prompt and GitBash as Administrator, and the issue still exists, and I have been strugggling with it for two days, and unable to get it work.
My node version: 4.23, npm:2.14.7
The error says:

C:\windows\system32>npm install -g ionic
npm ERR! tar.unpack untar error C:\Users\Bob\AppData\Roaming\npm-cache\ionic\1.
.12\package.tgz
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\
node_modules\npm\bin\npm-cli.js" "install" "-g" "ionic"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.7
npm ERR! path C:\Users\Bob\npm\node_modules\ionic\node_modules\ionic-app-lib\no
e_modules\ionic-cordova-lib\node_modules\cordova-js\node_modules\browserify\nod
_modules\browser-pack\node_modules\combine-source-map\node_modules\source-map\l
b\source-map\binary-search.js
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall open

npm ERR! Error: EPERM: operation not permitted, open 'C:\Users\Bob\npm\node_mod
les\ionic\node_modules\ionic-app-lib\node_modules\ionic-cordova-lib\node_module
\cordova-js\node_modules\browserify\node_modules\browser-pack\node_modules\comb
ne-source-map\node_modules\source-map\lib\source-map\binary-search.js'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM: operation not permitted, open 'C:\Users\Bob\npm\node
modules\ionic\node_modules\ionic-app-lib\node_modules\ionic-cordova-lib\node_mo
ules\cordova-js\node_modules\browserify\node_modules\browser-pack\node_modules\
ombine-source-map\node_modules\source-map\lib\source-map\binary-search.js']
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'open',
npm ERR!   path: 'C:\Users\Bob\npm\node_modules\ionic\node_modules\ionic
app-lib\node_modules\ionic-cordova-lib\node_modules\cordova-js\node_module
\browserify\node_modules\browser-pack\node_modules\combine-source-map\nod
_modules\source-map\lib\source-map\binary-search.js' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\windows\system32\npm-debug.log

I am attaching the npm-debug.log.

I desperately need help!!!

I have tried npm cache clean, check permissions on all related folders, search the web, no luck.

**Comment by furnaceX** [comment]
Hi Bob, I'm having the exact same problem and have been googling for days, trying everything.  

Did you get it working?  What did you do?
