### ISSUE TITLE
npm error: bower install

### ISSUE THREAD

**Issue by MurrayBakerWebDeveloper** [npm/npm#10917]
npm ERR! tar.unpack untar error /Users/MurrayBaker89/.npm/bower/1.7.1/package.tgz
npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "bower"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! path /usr/local/lib/node_modules/bower
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall mkdir

npm ERR! Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/bower'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/bower']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/usr/local/lib/node_modules/bower',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/usr/local/lib/node_modules/bower',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack:
npm ERR!    [ '/usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:35:25',
npm ERR!      '/usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:47:53',
npm ERR!      'FSReqWrap.oncomplete (fs.js:82:15)' ] }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/MurrayBaker89/Documents/grandparent/parent/FreeCodeCamp/npm-debug.log
Murrays-MacBook-Pro:freecodecamp MurrayBaker89$

**Comment by KenanY** [comment]
@nuku89 Have you tried using `sudo`? Looks like you do not have permission to write to `/usr/local/`.

**Comment by KenanY** [comment]
@MurrayBakerWebDeveloper Are you still having this issue?

**Comment by MurrayBakerWebDeveloper** [comment]
No
