### ISSUE TITLE
npm install hangs at madeDirectory Program creation not in flight; initializing

### ISSUE THREAD

**Issue by Ochea** [npm/npm#10915]
Been stuck trying to install protractor (for brevity, leaving out in descriptions below) for a couple weeks. Read and tried various pointers, flags posted here and other forums (as Administrator), updating PATH so C:\Users\username\AppData\Roaming\npm precedes C:\Program Files\nodejs\ reinstalling NodeJS, removing node_modules, reinstating node_modules, installing remotely / tarball. Running latest mature NodeJS v4.2.3 Any pointers? Thanks in advance!

"npm install -g" freezes at first line
"npm install -global"
"npm install --no-optional"
"npm install -ddd"

C:\Program Files\cygwin64\home\username>npm install --global -ddd protractor-3.0.0
.tar.gz
npm info it worked if it ends with ok
npm verb cli [ 'C:\Program Files\nodejs\node.exe',
npm verb cli 'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
npm verb cli 'install',
npm verb cli '--global',
npm verb cli '-ddd',
npm verb cli 'protractor-3.0.0.tar.gz' ]
npm info using npm@2.14.7
npm info using node@v4.2.3
npm verb install initial load of C:\Users\username\AppData\Roaming\npm\package.jso
n
npm verb readDependencies loading dependencies from C:\Users\username\AppData\Roam
ing\npm\package.json
npm sill cache add args [ 'protractor-3.0.0.tar.gz', null ]
npm verb cache add spec protractor-3.0.0.tar.gz
npm sill cache add parsed spec Result {
npm sill cache add raw: 'protractor-3.0.0.tar.gz',
npm sill cache add scope: null,
npm sill cache add name: null,
npm sill cache add rawSpec: 'protractor-3.0.0.tar.gz',
npm sill cache add spec: 'C:\Program Files\cygwin64\home\username\protracto
r-3.0.0.tar.gz',
npm sill cache add type: 'local' }
npm sill addLocalTarball shasum (computed) 9533f069b8c8a5a21c77b23175aeb719f7690
14b
npm verb addTmpTarball C:\Program Files\cygwin64\home\username\protractor-3.0.0.ta
r.gz not in flight; adding
npm verb makeDirectory C:\"Program creation not in flight; initializing

**Comment by Ochea** [comment]
Win 7 / node 4.2.3 (npm 2.14.7). I've been mostly working in Command Prompt (C:\Program Files\nodejs --remote install-- and C:\Program Files\cygwin64\home\username --tarball install) except for the couple tries using cygwin terminal. Searching in Windows, there are npm directories in:

C:\Users\username\AppData\Roaming\npm\ (protractor directory was created here when there used to be advancement in progress bar, but protractor command was not found) 
C:\Program Files\nodejs
C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Micro
soft\Web Tools\External\npm\

"npm config get prefix -g" nets C:\Users\username\AppData\Roaming\npm

For exhaustive testing, I did try Node 4.2.3 (x86 though system is 64-bit and using Node 64-bit all other times) and separately, Node 5.3.0 (NPM 3.3.12):

C:\Program Files\nodejs>npm install -g --verbose protractor
npm info it worked if it ends with ok
npm verb cli [ 'C:\Program Files\nodejs\node.exe',
npm verb cli 'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
npm verb cli 'install',
npm verb cli '-g',
npm verb cli '--verbose',
npm verb cli 'protractor' ]
npm info using npm@3.3.12
npm info using node@v5.3.0
npm verb request uri http://registry.npmjs.org/protractor
npm verb request no auth needed
npm info attempt registry request try #1 at 7:05:12 AM
npm verb request id 4e041ac3e7572cdd
npm http request GET http://registry.npmjs.org/protractor
npm http 200 http://registry.npmjs.org/protractor
npm verb headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
npm verb headers etag: '"DT7SXMTALQVBFZYVZKLHEPHK5"',
npm verb headers 'content-type': 'application/json',
npm verb headers 'cache-control': 'max-age=300',
npm verb headers 'content-length': '98965',
npm verb headers 'accept-ranges': 'bytes',
npm verb headers date: 'Mon, 21 Dec 2015 15:05:12 GMT',
npm verb headers via: '1.1 varnish',
npm verb headers age: '41',
npm verb headers connection: 'keep-alive',
npm verb headers 'x-served-by': 'cache-sjc3121-SJC',
npm verb headers 'x-cache': 'HIT',
npm verb headers 'x-cache-hits': '1',
npm verb headers 'x-timer': 'S1450710312.301664,VS0,VE0',
npm verb headers vary: 'Accept' }
npm verb get saving protractor to C:\"Program\registry.npmjs.org\protractor.cac
he.json
npm verb makeDirectory C:\"Program creation not in flight; initializing
▌ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟

In previous attempts, the progress bar actually advanced, no progress now.

**Comment by Ochea** [comment]
Still stuck. Any pointers please?

**Comment by bsclifton** [comment]
Can you try installing node.js to a directory which doesn't have a space in it? For example, C:\nodejs\
