### ISSUE TITLE
npm Error: Cannot find module 'asn1'

### ISSUE THREAD

**Issue by hosnimed** [npm/npm#10916]
After updating npm version  li, I wasn't abel to execute any command even npm -v
here is the stack : 
Error: Cannot find module 'asn1'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/lib/util.js:6:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
npm ERR! Darwin 15.2.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "npm" "-g"
npm ERR! node v0.12.7
npm ERR! npm  v3.5.1
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'asn1'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

any help please??? :disappointed:

**Comment by smartmouse** [comment]
using the default npm that comes with node 0.12.x works for me on linux.

strong@pln:~/test> npm -v
2.14.7
strong@pln:~/test> npm install asn1
npm WARN package.json ivytest@1.0.0 No description
npm WARN package.json ivytest@1.0.0 No repository field.
npm WARN package.json ivytest@1.0.0 No README data
asn1@0.2.3 node_modules/asn1

**Comment by KenanY** [comment]
@smartmouse Looks like you tried to install `ans1` instead of `asn1`?

**Comment by smartmouse** [comment]
Yes, KenanY,  but I modify my first answer since it is not really addressing the issue.

**Comment by smartmouse** [comment]
I got  similar issues after upgrading to npm 3.5.1 as well .

even npm -v does not work .

uest/node_modules/http-signature/node_modules> npm install -g npm@3.5.1
/home/shared/IBMSVT64_12/bin/npm -> /home/shared/IBMSVT64_12/lib/node_modules/npm/bin/npm-cli.js
npm@3.5.1 /home/shared/IBMSVT64_12/lib/node_modules/npm
strongbot@plnx131:/home/shared/IBMSVT64_12/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules> npm -v
node.js:720
    var cwd = process.cwd();
                      ^
Error: ENOENT, no such file or directory
    at Error (native)
    at Function.startup.resolveArgv0 (node.js:720:23)
    at startup (node.js:63:13)
    at node.js:814:3
strong@plnx:/home/shared/SVT64_12/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules>
strong@plnx:/home/shared/SVT64_12/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules> ls
strong@plnx:/home/shared/SVT64_12/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules> cd ..
strongbot@plnx:/home/shared/SVT64_12/lib/node_modules/npm/node_modules/request/node_modules/http-signature> ls
http_signing.md  lib  LICENSE  node_modules  package.json  README.md
strong@plnx:/home/shared/SVT64_12/lib/node_modules/npm/node_modules/request/node_modules/http-signature> cd node_modules/

strong@plnx:/home/shared/SVT64_12/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules> ls
asn1  assert-plus  ctype
strongt@plnx:/home/shared/SVT64_12/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules>

**Comment by smartmouse** [comment]
After  I  did npm cache clear,  npm -v works again,  strong@plnx:/home/shared/SVT64_12/bin> npm -v
3.5.1

**Comment by hosnimed** [comment]
thanks, but the error persist ,I checked the module 'asn1' but I didn't found it, and even I try to execute "npm cache clear" didn' t work with me : 

hosni-mac:node_modules hosni$ pwd
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules
hosni-mac:node_modules hosni$ ls
assert-plus
hosni-mac:node_modules hosni$ sudo npm cache clear
Error: Cannot find module 'asn1'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/lib/util.js:6:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
npm ERR! Darwin 15.2.0
npm ERR! argv "node" "/usr/local/bin/npm" "cache" "clear"
npm ERR! node v0.12.7
npm ERR! npm  v3.5.1
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'asn1'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

Is there any solution to remove all node packages and do a clean install ???

**Comment by hosnimed** [comment]
Finally I found the solution. I follow [this](https://gist.github.com/DanHerbert/9520689) guide and it works for me .
