### ISSUE TITLE
npm update keeps deleting certain modules

### ISSUE THREAD

**Issue by dominicbarnes** [npm/npm#10927]
If I run `npm update`, and a particular dependency updates, the dependencies of the updated module are deleted. In my situation, this is happening in CI pretty regularly. (re-running `npm update` seems to fix the issue)

For example, I have [mako-output](https://www.npmjs.com/package/mako-output), which depends on `debug` and `defaults`. When I recently ran a build, I had updated [mako](https://www.npmjs.com/package/mako) to `^0.5.0`. After `npm update` had finished running, `debug` and `defaults` were deleted.

I have noticed that this seems to happen consistently when `mako` itself is being updated. I'm beginning to suspect that this could be related to my usage of `peerDependencies`. (`mako-output` has `mako` as one of it's peer dependencies)

**Comment by iarna** [comment]
What version of npm? There were a slew of bugs fixed around this kind of thing recently, and I bet if you try 3.5.2 / 3.5.3 you won't see it again.

**Comment by dominicbarnes** [comment]
I'm simply using the latest stable (5.x) of node, which appears to include npm 3.3.12.

I'll close this issue for now, but I'll re-open if the later versions you've specified fix the issue. (once they land in stable, of course)
