### ISSUE TITLE
Unable to install ionic on Windows 7

### ISSUE THREAD

**Issue by bob1457** [npm/npm#10928]
Hi there,

I got a problem to install ionic on my Windows 7 Home Premium edition.

I got an error saying:

npm ERR! tar.unpack untar error C:\Users\Bob\AppData\Roaming\npm-cache\ionic\1.7
.12\package.tgz
npm ERR! tar.unpack untar error C:\Users\Bob\AppData\Roaming\npm-cache\core-util
-is\1.0.2\package.tgz
npm ERR! tar.unpack untar error C:\Users\Bob\AppData\Roaming\npm-cache\source-ma
p\0.3.0\package.tgz
npm ERR! tar.unpack untar error C:\Users\Bob\AppData\Roaming\npm-cache\cipher-ba
se\1.0.2\package.tgz
npm ERR! tar.unpack untar error C:\Users\Bob\AppData\Roaming\npm-cache\cipher-ba
se\1.0.2\package.tgz
npm ERR! tar.unpack untar error C:\Users\Bob\AppData\Roaming\npm-cache\buffer-xo
r\1.0.3\package.tgz
npm ERR! tar.unpack untar error C:\Users\Bob\AppData\Roaming\npm-cache\buffer-xo
r\1.0.3\package.tgz
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\
node_modules\npm\bin\npm-cli.js" "install" "-g" "cordova" "ionic"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.7
npm ERR! path C:\Users\Bob\npm\node_modules\ionic\node_modules\ionic-app-lib\nod
e_modules\ionic-cordova-lib\node_modules\cordova-js\node_modules\browserify\node
_modules\browser-pack\node_modules\combine-source-map\node_modules\source-map\li
b\source-map\binary-search.js
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall open

npm ERR! Error: EPERM: operation not permitted, open 'C:\Users\Bob\npm\node_modu
les\ionic\node_modules\ionic-app-lib\node_modules\ionic-cordova-lib\node_modules
\cordova-js\node_modules\browserify\node_modules\browser-pack\node_modules\combi
ne-source-map\node_modules\source-map\lib\source-map\binary-search.js'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM: operation not permitted, open 'C:\Users\Bob\npm\node_
modules\ionic\node_modules\ionic-app-lib\node_modules\ionic-cordova-lib\node_mod
ules\cordova-js\node_modules\browserify\node_modules\browser-pack\node_modules\c
ombine-source-map\node_modules\source-map\lib\source-map\binary-search.js']
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'open',
npm ERR!   path: 'C:\Users\Bob\npm\node_modules\ionic\node_modules\ionic-
app-lib\node_modules\ionic-cordova-lib\node_modules\cordova-js\node_modules
\browserify\node_modules\browser-pack\node_modules\combine-source-map\node
_modules\source-map\lib\source-map\binary-search.js' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\windows\system32\npm-debug.log

My node.js version: 4.2.3, npm 2.14.7
OS: Windows 7 Home Premium, service pack 1

I did clean cache, run command prompt as Administrator, check all folder permissions(it seems like permission issue, but...) etc., no luck, frustrated in the past couple of day. I desperately need help. By the way, I successfully installed ionic on the other Windows 7 enterprise without any problems. Not sure what are the difference here. 

More information: I have Visual Studio 2015 enterprise installed with Cordova Tools (the one I successfully installed ionic was with Visual Studio 2015 Community edition with Cordova tools installed)

Thanks.

Bob

**Comment by VivekAnand23** [comment]
I am also experiencing similar issue.

```
npm ERR! tar.unpack untar error C:\Users\484492\AppData\Roaming\npm-cache\ionic\1.7.12\package.tgz
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\username\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\n
pm-cli.js" "install" "-g" "ionic"
npm ERR! node v4.2.4
npm ERR! npm  v3.5.3
npm ERR! path C:\Users\username\AppData\Local\Temp\npm-12308-2b4ff5eb\unpack-853e3c31\node_modules\ionic-app-lib\node_modu
les\archiver\node_modules\file-utils\node_modules\isbinaryfile\tests\fixtures\04_HelloWorld.pdf
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall open

npm ERR! Error: EPERM: operation not permitted, open 'C:\Users\username\AppData\Local\Temp\npm-12308-2b4ff5eb\unpack-853e3
c31\node_modules\ionic-app-lib\node_modules\archiver\node_modules\file-utils\node_modules\isbinaryfile\tests\fixtures\04
_HelloWorld.pdf'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM: operation not permitted, open 'C:\Users\username\AppData\Local\Temp\npm-12308-2b4ff5eb\unpack-8
53e3c31\node_modules\ionic-app-lib\node_modules\archiver\node_modules\file-utils\node_modules\isbinaryfile\tests\fixture
s\04_HelloWorld.pdf']
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'open',
npm ERR!   path: 'C:\\Users\\username\\AppData\\Local\\Temp\\npm-12308-2b4ff5eb\\unpack-853e3c31\\node_modules\\ionic-app-
lib\\node_modules\\archiver\\node_modules\\file-utils\\node_modules\\isbinaryfile\\tests\\fixtures\\04_HelloWorld.pdf' }

npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Ionic\Test\npm-debug.log
```
