### ISSUE TITLE
`files` field docs confusing

### ISSUE THREAD

**Issue by mightyiam** [npm/npm#10924]
Hey, what is the `files` field for? I never used it and stuff always worked.

[The doc](https://docs.npmjs.com/files/package.json#files) says it is for specifying files to include but it doesn't say what happens when you don't specify this field.

**Comment by mightyiam** [comment]
Quote from IRC:
``` irc
<Aria> Then it includes everything.
<Aria> (subject to a .gitignore or .npmignore)
<Aria> And doesn't include a few things that might have tokens in them
```

Thank you @aredridel.

**Comment by mightyiam** [comment]
Another question docs may answer is whether pattern matching is available there.

**Comment by mightyiam** [comment]
So, if I do specify even a single file there, do I have to specify all of the files that are required in development? All the configuration files? All the test files? That doesn't sound right.

**Comment by aredridel** [comment]
Yes. If you specify any, you specify all. Wildcards are allowed.

**Comment by mightyiam** [comment]
Thank you, @aredridel.

What I would like is only to unignore the contents of the `dist` directory, because I have that in my `.gitignore`. I imagine that this is a common use case.

Should I use the `files` field for that? Something like:

``` json
{
  "files": [
    "**/*"
  ]
}
```

Perhaps?

But, would I then have to add some obvious things to `.npmignore`, like `node_modules`?

**Comment by mightyiam** [comment]
Also, docs don't mention the relationship with `.gitignore` (priority).

**Comment by mightyiam** [comment]
According to [these docs](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package), I should create an empty `.npmignore` file.

It also answers all my other questions. So, perhaps there should be a link from the `files` field doc to there.
