### ISSUE TITLE
Support passing username/password on CLI.

### ISSUE THREAD

**Issue by mitchdenny** [npm/npm#10920]
Hi there,
I'm trying to do an `npm publish` from a build server. And I'm wondering why I'm having to jump through hoops to make that work by doing an `npm adduser`, including a bunch of hacks for piping inputs to the interactive prompt when it would probably make more sense to simply just have a `--username` and `--password` switch on many of the commands.

Many modern build platforms are now shared infrastructure so the whole system is blown away from build to build, and they have secure ways of storing credentials and passing them into scripts. Is there any particular reason that we could have either `--username` and `--password` arguments on all commands, or at least just on the `npm adduser` command? Or is there a better way to pass in args.

I understand that you can use the `.npmrc` file, but on some build platforms its just easier to invoke a command than have to write another random script file which then goes and writes that file.

**Comment by KenanY** [comment]
https://github.com/npm/npm/issues/9325?

**Comment by mitchdenny** [comment]
Responded on #9325. I'm using ```.npmrc``` - thanks for the pointer. Perhaps I can offer some assistance around documentation for the project? I was thinking it would be great to have a page dedicated to those folks using NPM on a build server. The page would cut to the chase on what the ```.npmrc``` file is, and where you should put it in your repository, and then provide walk throughs for common CI solutions.

Thoughts?

**Comment by busches** [comment]
@mitchdenny any interest in still updating the docs for this? Otherwise the root issue itself has been fixed.

**Comment by mitchdenny** [comment]
Hi there, I was just having a look to see what has been fixed? Are there now arguments on the adduser command? Looking through the source I couldn't see anything.

**Comment by busches** [comment]
Maybe saying the root issue has been fixed is misleading. I should have said they don't plan to fix it and the correct way to do it was mentioned in the issue you linked and your comment, so there's no further action on this issue, unless you plan to update the docs.

**Comment by KenanY** [comment]
Closing; this functionality intentionally (https://github.com/npm/npm/issues/12111#issuecomment-202497588) does not exist.
