### ISSUE TITLE
EISGIT error blocking desired workflow

### ISSUE THREAD

**Issue by kmalakoff** [npm/npm#10933]
I find myself switching to npm 2 to update modules because npm 3 is IMHO a little too strict on its handling of git repos.

Here's our workflow:

(1) npm install a project / application

(2) when doing heavy refactoring on a module or modules, remove the installed module and git clone the module source into node_modules to reduce the iteration loop.

(3) check in changes and push up, delete the git module, and run `npm install {updatedModule}` to replace with the refactored module.  

This all works fine except when any module us in git form and let's say we decide to add another module `npm install {anotherModule}`, we get the EISGIT error (`Appears to be a git repo or submodule. Refusing to remove it. Update manually...`). This happens even when the module is unrelated to the module in git form.

I've seen other people have raised this for different reasons (for example, [related to Docker](https://github.com/npm/npm/issues/10372)) and I've seen the argument made that npm wants to own the node_modules folder, but...

In practice, on my teams our workflows have always involved a certain amount of coding within the node_modules folder (eg. investigating bugs, refactoring with a more realistic integration use case then unit tests alone can catch, verifying changes work in a complex system, etc). We have developed workflows / tooling around this that we'd like to continue using in npm 3.

Is there a way to change the git error to a warning so it skips rather than fails?  If the default behavior needs to be so strict, could an optional flag be introduced to downgrade the errors to warnings (or some other good workaround)? 

Just wondering if there is any flexibility on this to keep our productivity up with npm 3...

**Comment by IonicaBizau** [comment]
Similar workflow here: I `git clone` one dependency in `node_modules`, but when I `npm i --save anotherDependency` (in the root project) it ends with this error.

Any solution to this?

**Comment by dypsilon** [comment]
I am affected by the same issue in relation to Docker. The aforementioned workflow (working on a module directly in a project) gets increasingly frustrating year after year. I was hoping things changed to the better in npm 3 but they actually made npm unusable at all. Seriously, I'm thinking about writing an installer myself.

My desired workflow is: work inside a docker container on a module directly inside the project directory. Npm Link would be perfect for this, except it doesn't work inside a docker container. The workaround was to write a script which clones the git repos for me, but even this doesn't work anymore!

**Comment by IonicaBizau** [comment]
I just `nvm alias default 4.0.0` for now... I feel like npm 2.x.x works smoother than the latest releases.

**Comment by IonicaBizau** [comment]
@iarna This is still happening in the latest version. Is there any hope to fix it?

**Comment by strathausen** [comment]
Try this:
- clone the repository somewhere else, not in `node_modules` and use it via `npm link` instead
- make sure it contains the `.npmignore` file with `.git` in it it, otherwise npm will complain again
