### ISSUE TITLE
npm install error for meanjs package in windows 7 32 bit

### ISSUE THREAD

**Issue by thenaughtychild** [npm/npm#10936]
this is the error that shows while doing npm install for meanjs package in windows 7 32 bit
https://gist.github.com/thenaughtychild/8cd967812ebe607a56ed

**Comment by KenanY** [comment]
@thenaughtychild Do you think this is an issue with `npm`? `node-gyp` is throwing the error, and it is regarding your version of Python. Please see [the requirements](https://github.com/nodejs/node-gyp) for `node-gyp`, which include you having Python 2.

**Comment by othiym23** [comment]
Closing as resolved by @KenanY. Thanks, Kenan!
