### ISSUE TITLE
Empty .bin directories are not removed and result in ENOENT errors

### ISSUE THREAD

**Issue by SystemParadox** [npm/npm#10938]
With npm@3 I am regularly getting ENOENT errors.

When doing `npm remove` and seemingly also when doing `npm install` (perhaps because npm is moving things around in the tree?), I end up with empty `.bin` directories like this:

```
node_modules/foobar/node_modules/.bin
```

Where foobar and everything under it is empty, but the .bin wasn't removed. Any other `npm install` then reports ENOENT for `node_modules/foobar/package.json` (as per #10471).

Removing all the empty directories fixes it:

```
rmdir node_modules/foobar/node_modules/.bin
rmdir node_modules/foobar/node_modules/
rmdir node_modules/foobar
```

Expected behaviour: npm should have removed these directories already.

npm version 3.5.3

Thanks.

**Comment by chrisirhc** [comment]
Likely related/same as #10887
