### ISSUE TITLE
Backoff strategy

### ISSUE THREAD

**Issue by mattfysh** [npm/npm#10946]
Every now and again when we have an outage of our internal npm registry, bringing it back online again results in a flood of retry requests from waiting npm clients. Would it be possible to update client and server to support a server-imposed backoff strategy ie. the registry can tell the client how long to wait until the next retry?

**Comment by othiym23** [comment]
This isn't a bad idea, and in fact might be considered a best practice for a tool that generates lots of network requests like npm. Fortunately, `npm-registry-client` uses a package, [`retry`](http://npm.im/retry) that already supports backoff, with a random fuzz factor. Unfortunately, the randomization has to be enabled, and the CLI team doesn't have the bandwidth to make this change. It should be relatively simple at the code level, but it needs a good test, and I think this is a good-sized project for somebody who wants to pick it up outside our team. So, I'm going to close this feature request, but if you send it to us as a patch against `npm-registry-client` (with a test and a note in the docs that backoff is now randomized), we'll get it in pretty quickly. Thanks for writing this up!
