### ISSUE TITLE
npm run only_once npm ERR! Darwin 15.2.0 npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "only_once" npm ERR! node v4.2.2 npm ERR! npm  v2.14.7 npm ERR! path /Users/MurrayBaker89/Documents/grandparent/parent/package.json npm ERR! code ENOENT npm ERR! errno -2 npm ERR! syscall open  npm ERR! enoent ENOENT: no such file or directory, open '/Users/MurrayBaker89/Documents/grandparent/parent/package.json' npm ERR! enoent This is most likely not a problem with npm itself npm ERR! enoent and is related to npm not being able to find a file. npm ERR! enoent  npm ERR! Please include the following file with any support request: npm ERR!     /Users/MurrayBaker89/Documents/grandparent/parent/npm-debug.lo

### ISSUE THREAD

**Issue by nuku89** [npm/npm#10941]
ERR! Darwin 15.2.0 npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "only_once" npm ERR! node v4.2.2 npm ERR! npm  v2.14.7 npm ERR! path /Users/MurrayBaker89/Documents/grandparent/parent/package.json npm ERR! code ENOENT npm ERR! errno -2 npm ERR! syscall open  npm ERR! enoent ENOENT: no such file or directory, open '/Users/MurrayBaker89/Documents/grandparent/parent/package.json' npm ERR! enoent This is most likely not a problem with npm itself npm ERR! enoent and is related to npm not being able to find a file. npm ERR! enoent  npm ERR! Please include the following file with any support request: npm ERR!     /Users/MurrayBaker89/Documents/grandparent/parent/npm-debug.lo

**Comment by oucart** [comment]
hello ,
How to solve？？

**Comment by nuku89** [comment]
The npm run first-time command was attempted to seed the mongo db w/ freecodecamp and I received this error message. It is instructed to be ran only once, tried it most recently and got:

"npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "first-time"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7

npm ERR! missing script: first-time
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/MurrayBaker89/Documents/grandparent/parent/FreeCodeCamp/npm-debug.log”

Thank you,
Murray Baker
