### ISSUE TITLE
Allow alternative prefixes to "npm_package_config" for accessing config variables from package.json

### ISSUE THREAD

**Issue by ChrisPearce** [npm/npm#10960]
Many common styling checkers and linters, check if identifiers are camelCased or UPPERCASE_WITH_UNDERSCORES.

Currently NPM sets config values to the node environment variables with the lowercase prefix "npm_package_config". This often results in linters' default rules raising warnings.

It would be very helpful if an uppercase version of this prefix was also supported, or if the prefix could be set via the .npmrc configuration file.

**Comment by othiym23** [comment]
This is a useful for fairly narrowly applicable feature, and it's not worth the complexity cost to make that prefix configurable. Thanks for the suggestion, though!

**Comment by iarna** [comment]
(And remember, you can just do `process.env['npm_package_config']` to get values w/o your linter knowing)
