### ISSUE TITLE
Building from VS 2015: exited with code -4058

### ISSUE THREAD

**Issue by dimfil11** [npm/npm#10969]
```
Error   1   The command "
      IF EXIST "%VS110COMNTOOLS%VsDevCmd.bat" (
      call "%VS110COMNTOOLS%VsDevCmd.bat"
      ) ELSE (
      echo VS 11 Common Tools not found
      )
      IF EXIST "%VS120COMNTOOLS%VsDevCmd.bat" (
      call "%VS120COMNTOOLS%VsDevCmd.bat"
      ) ELSE (
      echo VS 12 Common Tools not found
      )
      set PATH=E:\VSProjects\Dimfil\eBebefits\eBenefits_Ongoing\packages\Npm.js.2.13.1.0\build\..\tools\;%PATH%
      "E:\VSProjects\Dimfil\eBebefits\eBenefits_Ongoing\packages\Npm.js.2.13.1.0\build\..\tools\npm" install
      " exited with code -4058. eBenefits
```

**Comment by dimfil11** [comment]
More details:
The file package.json is located in: E:\VSProjects\Dimfil\eBebefits\eBenefits_Ongoing\packages\Npm.js.2.13.1.0\tools
While npm is looking in: E:\VSProjects\Dimfil\eBebefits\eBenefits_Ongoing\eBenefits

Detailed output: 
1>Using "Exec" task from assembly "Microsoft.Build.Tasks.v12.0, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
1>Task "Exec" (TaskId:16)
1>  Task Parameter:Command=
1>        IF EXIST "%VS110COMNTOOLS%VsDevCmd.bat" (
1>        call "%VS110COMNTOOLS%VsDevCmd.bat"
1>        ) ELSE (
1>        echo VS 11 Common Tools not found
1>        )
1>        IF EXIST "%VS120COMNTOOLS%VsDevCmd.bat" (
1>        call "%VS120COMNTOOLS%VsDevCmd.bat"
1>        ) ELSE (
1>        echo VS 12 Common Tools not found
1>        )
1>        set PATH=E:\VSProjects\Dimfil\eBebefits\eBenefits_Ongoing\packages\Npm.js.2.13.1.0\build\..\tools\;%PATH%
1>        "E:\VSProjects\Dimfil\eBebefits\eBenefits_Ongoing\packages\Npm.js.2.13.1.0\build\..\tools\npm" install
1>         (TaskId:16)
1>  
1>        IF EXIST "%VS110COMNTOOLS%VsDevCmd.bat" (
1>        call "%VS110COMNTOOLS%VsDevCmd.bat"
1>        ) ELSE (
1>        echo VS 11 Common Tools not found
1>        )
1>        IF EXIST "%VS120COMNTOOLS%VsDevCmd.bat" (
1>        call "%VS120COMNTOOLS%VsDevCmd.bat"
1>        ) ELSE (
1>        echo VS 12 Common Tools not found
1>        )
1>        set PATH=E:\VSProjects\Dimfil\eBebefits\eBenefits_Ongoing\packages\Npm.js.2.13.1.0\build\..\tools\;%PATH%
1>        "E:\VSProjects\Dimfil\eBebefits\eBenefits_Ongoing\packages\Npm.js.2.13.1.0\build\..\tools\npm" install
1>         (TaskId:16)
1>  npm ERR! install Couldn't read dependencies (TaskId:16)
1>  npm ERR! Windows_NT 6.3.9600 (TaskId:16)
1>  npm ERR! argv "E:\\VSProjects\\Dimfil\\eBebefits\\eBenefits_Ongoing\\packages\\Npm.js.2.13.1.0\\tools\\..\\..\\Node.js.0.12.7\\node.exe" "E:\\VSProjects\\Dimfil\\eBebefits\\eBenefits_Ongoing\\packages\\Npm.js.2.13.1.0\\tools\\node_modules\\npm\\bin\\npm-cli.js" "install" (TaskId:16)
1>  npm ERR! node v0.12.7 (TaskId:16)
1>  npm ERR! npm  v2.13.1 (TaskId:16)
1>  npm ERR! path E:\VSProjects\Dimfil\eBebefits\eBenefits_Ongoing\eBenefits\package.json (TaskId:16)
1>  npm ERR! code ENOPACKAGEJSON (TaskId:16)
1>  npm ERR! errno -4058 (TaskId:16)
1>   (TaskId:16)
1>  npm ERR! package.json ENOENT, open 'E:\VSProjects\Dimfil\eBebefits\eBenefits_Ongoing\eBenefits\package.json' (TaskId:16)
1>  npm ERR! package.json This is most likely not a problem with npm itself. (TaskId:16)
1>  npm ERR! package.json npm can't find a package.json file in your current directory. (TaskId:16)
1>   (TaskId:16)
1>  npm ERR! Please include the following file with any support request: (TaskId:16)
1>  npm ERR!     E:\VSProjects\Dimfil\eBebefits\eBenefits_Ongoing\eBenefits\npm-debug.log (TaskId:16)
1>E:\VSProjects\Dimfil\eBebefits\eBenefits_Ongoing\packages\Npm.js.2.13.1.0\build\npm.js.targets(27,5): error MSB3073: The command "
1>E:\VSProjects\Dimfil\eBebefits\eBenefits_Ongoing\packages\Npm.js.2.13.1.0\build\npm.js.targets(27,5): error MSB3073:       IF EXIST "%VS110COMNTOOLS%VsDevCmd.bat" (
1>E:\VSProjects\Dimfil\eBebefits\eBenefits_Ongoing\packages\Npm.js.2.13.1.0\build\npm.js.targets(27,5): error MSB3073:       call "%VS110COMNTOOLS%VsDevCmd.bat"
1>E:\VSProjects\Dimfil\eBebefits\eBenefits_Ongoing\packages\Npm.js.2.13.1.0\build\npm.js.targets(27,5): error MSB3073:       ) ELSE (
1>E:\VSProjects\Dimfil\eBebefits\eBenefits_Ongoing\packages\Npm.js.2.13.1.0\build\npm.js.targets(27,5): error MSB3073:       echo VS 11 Common Tools not found
1>E:\VSProjects\Dimfil\eBebefits\eBenefits_Ongoing\packages\Npm.js.2.13.1.0\build\npm.js.targets(27,5): error MSB3073:       )
1>E:\VSProjects\Dimfil\eBebefits\eBenefits_Ongoing\packages\Npm.js.2.13.1.0\build\npm.js.targets(27,5): error MSB3073:       IF EXIST "%VS120COMNTOOLS%VsDevCmd.bat" (
1>E:\VSProjects\Dimfil\eBebefits\eBenefits_Ongoing\packages\Npm.js.2.13.1.0\build\npm.js.targets(27,5): error MSB3073:       call "%VS120COMNTOOLS%VsDevCmd.bat"
1>E:\VSProjects\Dimfil\eBebefits\eBenefits_Ongoing\packages\Npm.js.2.13.1.0\build\npm.js.targets(27,5): error MSB3073:       ) ELSE (
1>E:\VSProjects\Dimfil\eBebefits\eBenefits_Ongoing\packages\Npm.js.2.13.1.0\build\npm.js.targets(27,5): error MSB3073:       echo VS 12 Common Tools not found
1>E:\VSProjects\Dimfil\eBebefits\eBenefits_Ongoing\packages\Npm.js.2.13.1.0\build\npm.js.targets(27,5): error MSB3073:       )
1>E:\VSProjects\Dimfil\eBebefits\eBenefits_Ongoing\packages\Npm.js.2.13.1.0\build\npm.js.targets(27,5): error MSB3073:       set PATH=E:\VSProjects\Dimfil\eBebefits\eBenefits_Ongoing\packages\Npm.js.2.13.1.0\build\..\tools\;%PATH%
1>E:\VSProjects\Dimfil\eBebefits\eBenefits_Ongoing\packages\Npm.js.2.13.1.0\build\npm.js.targets(27,5): error MSB3073:       "E:\VSProjects\Dimfil\eBebefits\eBenefits_Ongoing\packages\Npm.js.2.13.1.0\build\..\tools\npm" install
1>E:\VSProjects\Dimfil\eBebefits\eBenefits_Ongoing\packages\Npm.js.2.13.1.0\build\npm.js.targets(27,5): error MSB3073:       " exited with code -4058.
1>Done executing task "Exec" -- FAILED. (TaskId:16)

**Comment by scottaddie** [comment]
You may have better luck creating an issue in this repo: https://github.com/aspnet/Tooling

**Comment by zimcoder** [comment]
Got the the same Issue dimfil11, how did you resolve it?
