### ISSUE TITLE
gulp install error: "No compatible version found: archy@'^1.0.0" 

### ISSUE THREAD

**Issue by jpimienta-datasix** [npm/npm#10964]
Hi! 

I'm new about this environment. I try to install gulp to learn to use it and I obtain the error that I attach: [npm-debug.log.txt](https://github.com/npm/npm/files/73165/npm-debug.log.txt)
 
The OS is Windows 7 Professional and I haven't any error with node installation. 

Thanks a lot for your help! 

Kind regards,

Javier

```
309 error Error: No compatible version found: archy@'^1.0.0'
309 error Valid install targets:
309 error ["0.0.0","0.0.1","0.0.2","1.0.0"]
309 error     at installTargetsError (C:\Program Files\nodejs\node_modules\npm\lib\cache.js:684:10)
309 error     at C:\Program Files\nodejs\node_modules\npm\lib\cache.js:606:10
309 error     at saved (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\get.js:138:7)
309 error     at Object.oncomplete (fs.js:107:15)
310 error If you need help, you may report this log at:
310 error     <http://github.com/isaacs/npm/issues>
310 error or email it to:
310 error     <npm-@googlegroups.com>
311 error System Windows_NT 6.1.7601
312 error command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-save" "-g" "gulp"
313 error cwd C:\_Clientes\Coprocafe\D6DEC\www
314 error node -v v0.10.1
315 error npm -v 1.2.15
316 verbose exit [ 1, true ]
```

**Comment by timoxley** [comment]
@jpimienta-datasix try updating your npm: `npm install npm -g`

**Comment by jpimienta-datasix** [comment]
Thanks Tim!!! 

I try this but I have had other error message... It seems that `npm` try to install using self and it doesn't work. Then I reinstalled node from the `msi` file [v4.2.4 LTS](https://nodejs.org/dist/v4.2.4/node-v4.2.4-x64.msi) and it works! I do not know what could have happened.

**Comment by othiym23** [comment]
Closing as resolved.
