### ISSUE TITLE
doc: please update "npm i --help" with options

### ISSUE THREAD

**Issue by ashleygwilliams** [npm/npm#10967]
from https://github.com/npm/docs/issues/460 cc/@robey @iarna 

"I just found out about "npm i --no-progress" through an anecdote. I had assumed the feature didn't exist because it wasn't documented in "--help". It would be helpful (hee!) to update the help page with the new options."

at the bare minimum we might try to link pages that have config options to the config page that lists them.

happy to help once we decide how we want to fix this. can also help decide. just lemme know.

**Comment by othiym23** [comment]
Similarly, here's the present output from `npm install --help`:

```
npm install (with no args, in package dir)
npm install [<@scope>/]<pkg>
npm install [<@scope>/]<pkg>@<tag>
npm install [<@scope>/]<pkg>@<version>
npm install [<@scope>/]<pkg>@<version range>
npm install <folder>
npm install <tarball file>
npm install <tarball url>
npm install <git:// url>
npm install <github username>/<github project>

alias: npm i
common options: [--save|--save-dev|--save-optional] [--save-exact]
```

Note the "common options" line at the end. I would argue that those are the common options for install, and it's pretty uncommon that people need to use `--no-progress`, and it's definitely not widely used enough to merit inclusion in the short help. @iarna suggests that:

1. The short help pointing to, say, `npm help install` would be helpful.
2. And the applicability of `--no-progress` is narrow enough that it is an option that it might make sense to put in the manpages for the commands to which it applies.

So, like the last issue, I'm going to close this, but thanks (again) for bringing this issue up for discussion, and if somebody comes across this and wants to send us patches for 1 or 2 above, that would be fantastic.
