### ISSUE TITLE
 npm ERR! Windows_NT 6.1.7601

### ISSUE THREAD

**Issue by vinodgs** [npm/npm#10973]
error npm

 npm ERR! Windows_NT 6.1.7601
 npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\xyz\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "bower" "-g"
1>  npm ERR! node v4.2.3
1>  npm ERR! npm  v2.12.0
1>  
1>  npm ERR! process.getuid is not a function
1>  npm ERR! 
1>EXEC : npm ERR! If you need help, you may report this error at: 
1>  npm ERR!     <https://github.com/npm/npm/issues>
1>  
1>  npm ERR! Please include the following file with any support request:

the log file has 

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\xyz\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'npm',
1 verbose cli   '-g' ]
2 info using npm@2.12.0
3 info using node@v4.2.3
4 verbose install initial load of C:\Users\xyz\AppData\Roaming\npm\package.json
5 verbose readDependencies loading dependencies from C:\Users\xyz\AppData\Roaming\npm\package.json
6 silly cache add args [ 'npm', null ]
7 verbose cache add spec npm
8 silly cache add parsed spec Result {
8 silly cache add   raw: 'npm',
8 silly cache add   scope: null,
8 silly cache add   name: 'npm',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 silly addNamed npm@*
10 verbose addNamed "*" is a valid semver range for npm
11 silly addNameRange { name: 'npm', range: '*', hasData: false }
12 silly mapToRegistry name npm
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/npm
16 verbose addNameRange registry:https://registry.npmjs.org/npm not in flight; fetching
17 verbose request uri https://registry.npmjs.org/npm
18 verbose request no auth needed
19 info attempt registry request try #1 at 1:05:48 PM
20 verbose request id 9531dfb3fdc8add8
21 verbose etag "5AKOYGAXQI1FA35ZEA3763W0P"
22 http request GET https://registry.npmjs.org/npm
23 http 200 https://registry.npmjs.org/npm
24 silly get cb [ 200,
24 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
24 silly get     etag: '"BNMEDMY7I61PZLZDSPPL2QFDQ"',
24 silly get     'content-type': 'application/json',
24 silly get     'cache-control': 'max-age=300',
24 silly get     'content-length': '3979851',
24 silly get     'accept-ranges': 'bytes',
24 silly get     date: 'Mon, 28 Dec 2015 19:05:48 GMT',
24 silly get     via: '1.1 varnish',
24 silly get     age: '252',
24 silly get     connection: 'keep-alive',
24 silly get     'x-served-by': 'cache-ord1728-ORD',
24 silly get     'x-cache': 'HIT',
24 silly get     'x-cache-hits': '1',
24 silly get     'x-timer': 'S1451329548.154160,VS0,VE9',
24 silly get     vary: 'Accept' } ]
25 verbose get saving npm to C:\Users\xyz\AppData\Roaming\npm-cache\registry.npmjs.org\npm\.cache.json
26 verbose stack TypeError: process.getuid is not a function
26 verbose stack     at calculateOwner (C:\Users\xyz\AppData\Roaming\npm\node_modules\npm\lib\utils\correct-mkdir.js:37:24)
26 verbose stack     at C:\Users\xyz\AppData\Roaming\npm\node_modules\npm\lib\utils\correct-mkdir.js:23:22
26 verbose stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:82:15)
27 verbose cwd C:\Users\xyz
28 error Windows_NT 6.1.7601
29 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\xyz\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "npm" "-g"
30 error node v4.2.3
31 error npm  v2.12.0
32 error process.getuid is not a function
33 error If you need help, you may report this error at:
33 error     <https://github.com/npm/npm/issues>
34 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@vinodgs Does this also occur if you [upgrade](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows) to the latest stable release of `npm`? `npm@2.12.0` was dead-on-arrival for Windows a few months ago, and the fix for this issue was released with `npm@2.12.1`.

**Comment by vinodgs** [comment]
Reinstalled completely and deleted the npm folder /cache works now
