### ISSUE TITLE
doc: holes in scripts docs

### ISSUE THREAD

**Issue by ashleygwilliams** [npm/npm#10971]
from https://github.com/npm/docs/issues/408 cc/@seldo

"How run scripts work are documented here:
https://docs.npmjs.com/misc/scripts#package-json-vars

But these are only barely connected to the "run" command docs here:
https://docs.npmjs.com/cli/run-script

These two should be better cross-referenced or possibly combined."

**Comment by doug-wade** [comment]
afaict, this has been resolved already -- https://docs.npmjs.com/misc/scripts now contains the following line: "Additionally, arbitrary scripts can be executed by running npm run-script <pkg> <stage>. Pre and post commands with matching names will be run for those as well (e.g. premyscript, myscript, postmyscript)." @seldo do you think we need further cross referencing?
