### ISSUE TITLE
Cannot run npm install agsh/onvif in Ubuntu 14.04

### ISSUE THREAD

**Issue by crogerjack** [npm/npm#10975]
ubuntu@ubuntu:~$ npm install agsh/onvif
npm ERR! addLocal Could not install agsh/onvif
npm ERR! Error: ENOENT, stat 'agsh/onvif'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.16.0-30-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "agsh/onvif"
npm ERR! cwd /home/ubuntu
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path agsh/onvif
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/ubuntu/npm-debug.log
npm ERR! not ok code 0

**Comment by KenanY** [comment]
@crogerjack `npm@1.3` is no longer supported. Could you please try [upgrading](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm)?

**Comment by crogerjack** [comment]
@KenanY Thanks! It's works after I upgrade npm to latest version.
