### ISSUE TITLE
doc: bundleddependencies needs more

### ISSUE THREAD

**Issue by ashleygwilliams** [npm/npm#10972]
from: https://github.com/npm/docs/issues/372 cc/@seldo

need to elaborate the docs for bundleddependencies.

**Comment by gnerkus** [comment]
Added documentation on #11483

**Comment by seldo** [comment]
:tada:

**Comment by gnerkus** [comment]
I would like to request this issue be closed since the patch has been merged.

**Comment by KenanY** [comment]
Patch has been merged but the changes do not appear to be live yet (https://docs.npmjs.com/files/package.json#bundleddependencies). I'll keep this open as a reminder that someone needs to deploy the updated docs.

**Comment by busches** [comment]
@kenany it's been eight months and they're still not deployed, any ideas when they will be?

**Comment by KenanY** [comment]
@busches No idea, I don't have access to this kind of thing.

**Comment by busches** [comment]
@othiym23 @KenanY any ideas on who does?

**Comment by KenanY** [comment]
Maybe @ashleygwilliams :)
