### ISSUE TITLE
npm@3 EXDEV: cross-device link not permitted with linked package

### ISSUE THREAD

**Issue by whitecolor** [npm/npm#10989]
I have a linked package in may app:

`npm install mongoose -g` (install globally)
then `npm link mongoose` (in app folder)

Then I try to do `npm install` in app folder, and got an error:

```
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\nodejs\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\npm-cl
i.js" "install"
npm ERR! node v4.2.3
npm ERR! npm  v3.5.2
npm ERR! path ...\app\node_modules\mongoose\node_modules\
core-util-is
npm ERR! code EXDEV
npm ERR! errno -4037
npm ERR! syscall rename

npm ERR! EXDEV: cross-device link not permitted, rename '...app\reader2\node_modules\mongoose\node_modules\core-util-is' -> '...app\node_modules\core-util-is'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
```

So it tried to do something with linked package how this can be resolved?

**Comment by whitecolor** [comment]
I think that referece to this one https://github.com/npm/npm/issues/10343

**Comment by xer0x** [comment]
What does this even mean? Sorry, but I have a module that silently fails to install via `npm install` and when I `npm install that-module` it pops up the error above. The directory is supposed to be clean without any links or oddities.
