### ISSUE TITLE
Installed node.js and npm together but having issues with npm

### ISSUE THREAD

**Issue by francisngo** [npm/npm#10983]
When I type in `npm -v`

I get this:

```
path.js:424
    var path = (i >= 0) ? arguments[i] : process.cwd();
                                                 ^

Error: ENOENT: no such file or directory, uv_cwd
    at Error (native)
    at Object.posix.resolve (path.js:424:50)
    at Function.Module._resolveLookupPaths (module.js:250:17)
    at Function.Module._resolveFilename (module.js:317:31)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:26:13
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:76:3)
    at Module._compile (module.js:398:26)
```

I am trying to install and start npm on a project but I do not now what is wrong. Can someone help please?

**Comment by inradius** [comment]
I was getting this just now too. I just did a 'make uninstall' in the node folder I ran 'make install' in and then ran 'yum install npm' (CentOS 6.5) and it works now.

**Comment by annaship** [comment]
That happened with me when I removed the directory on one terminal, but was in it on another. Just cd out of it and then back helped.

**Comment by DJDaveMark** [comment]
### Solution
cd out of the folder then back in (as annaship mentioned which I missed 1st time round)

### Long Explanation
I happened across this bug as well. I opened two terminals did an "npm install" in one and "bower install" in another.
Everything appeared fine, lots of logs, no errors (both terminals).
Tried a "grunt" to build the project, and the error above appeared.
I realised that neither "node_modules" nor "bower_components" had been created.
No matter what npm command I used (even "npm -v"), they all produced the same error above.
I cd-ed into another project to check grunt/npm was working, which it was, and when I cd-ed back and redid "npm install", lots of logs, no errors again, but this time the "node_modules" appeared. Then "bower install" produced it's folder, the projects grunt succeeded and all was well in the world.

Strange bug that one!

**Comment by davidjeddy** [comment]
Using node 4.x on a amazonlinux machine, had this issue. Hope its fixed in the newer releases 'cause thats kind of a big deal.

**Comment by damody** [comment]
Using node 4.x on a amazonlinux machine, had this issue. Hope its fixed in the newer releases 'cause thats kind of a big deal. +1

**Comment by AkashBabu** [comment]
like @annaship explained,  cd out of the current folder and back in works :) +1:

**Comment by srinireddy** [comment]
Thanks Akash. It worked

**Comment by Swapnilchavan18** [comment]
I also got same issue, Thanks Aakash it worked with cd out and back in to the folder.

**Comment by marypreethi12** [comment]
cd out of the direcory and into again , then npm i worked for me
