### ISSUE TITLE
Missing packages after first npm install

### ISSUE THREAD

**Issue by benoitvallon** [npm/npm#10985]
After the first `npm install` on my project, some packages are missing. After the second run, all the packages are here. The project is this one [react-native-nw-react-calculator](https://github.com/benoitvallon/react-native-nw-react-calculator)

node: v5.3.0
npm: ok with 3.3.9, nok with 3.3.10, still nok with 3.5.3

Here is a sample of the package tree after install, with npm 3.3.9 I got the slash and shebang-regex packages which I don't get with 3.3.10 or the last version (3.5.3)

```
npm 3.3.9
├-┬ babel-core@6.3.26 
 :  : 
│├── private@0.1.6 
│├── shebang-regex@1.0.0 
│├── slash@1.0.0 
│└── source-map@0.5.3
```

```
npm 3.3.10 or 3.5.3
├-┬ babel-core@6.3.26 
 :  :
│├── private@0.1.6 
│└── source-map@0.5.3
```

I managed to find the commit introducing the bug [deps: When we replace/upgrade a dep, remove all its deps too](https://github.com/npm/npm/commit/971fd47ac9b48cd7aa61d869082c6950639ac366?diff=split) but I am a little stuck to go further and fix the bug.

If anyone could help me with this, I would be happy to fix it.

**Comment by benoitvallon** [comment]
Here are the logs in travis for different version of npm and node https://travis-ci.org/benoitvallon/react-native-nw-react-calculator

We can see that it works great with npm 3.3.6 for example. The behavior appears in 3.3.10 but there is no errors at install, only packages are missing.

**Comment by Hikingyo** [comment]
I have the same problem with npm 3.3.12 on travis and on my own computer.
On my computer, I should to execute several times npm install to have all the packages install.

**Comment by benoitvallon** [comment]
Still having the issue with npm v3.6.0
