### ISSUE TITLE
npm install express error

### ISSUE THREAD

**Issue by El-amine** [npm/npm#10982]
i have some errors installing express module.

this is what i get in my consol:---)
>npm install express
npm ERR! registry error parsing json
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "express"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6

npm ERR! Cannot read property 'localeCompare' of undefined
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\NodeJS\NodeAppTest-0\npm-debug.log

**Comment by KenanY** [comment]
@El-amine Does this also occur if you [upgrade](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows) to the latest stable release of `npm`? I am pretty sure that this `localeCompare` issue was fixed at least a month ago by `npm@3.3.7`.

**Comment by El-amine** [comment]
@KenanY  you rigth... after updating npm by executing "npm install-g npm@latest" everything is good... thanks for all !

Best regards
