### ISSUE TITLE
`npm install` and `npm ls` do not reliably show secondary+ pkg deps

### ISSUE THREAD

**Issue by ashleygwilliams** [npm/npm#10984]
code => https://github.com/ashleygwilliams/npm-sandbox/tree/non-det/npm3/example3
`npm v3.5.2`

let's say we have an app that depends on 2 modules `mod-c` and `mod-d`.
`mod-c` depends on `mod-b@v2` and `mod-d` depends on `mod-b@v2`.

i `npm install`.
as a developer, i now want to add `mod-a`. `mod-a` depends on `mod-b@v1`.

i `npm install mod-a --save`.

it looks like this:
![screenshot 2015-12-29 at 5 34 27 pm](https://cloud.githubusercontent.com/assets/1163554/12043633/e2d4a02c-ae54-11e5-8839-43b305439097.png)
## why does neither `npm install` nor `npm ls` show that `mod-b@v2` is a dep of `mod-d` ?

now let's say that my coworker clones my project after i push my changes. now the `package.json` file lists `mod-a`, `mod-c`, and `mod-d`. it is in alphabetic order, changing the install order, and thus changing the `node_modules` tree.

both `npm install` and `npm ls` show `mod-b@v2` as a dep of `mod-d`:

![screenshot 2015-12-29 at 5 35 01 pm](https://cloud.githubusercontent.com/assets/1163554/12043672/32b5ff28-ae55-11e5-9dfc-7feed9d8b224.png)

**Comment by iarna** [comment]
So, this was explicitly added as a feature (see `bfsify` in `lib/ls.js`) a very long time ago, and I don't know _why_. I've found this confusing too, but I think we need to better understand why it was added in the first place. It was added back in 7fb6734.

@ashleygwilliams Can you get with @isaacs and figure out what the reasoning was and if or if not it still stands? Making this display the tree as it is, is as simple as removing the call to the above function, in both 2.x and 3.x.

**Comment by iarna** [comment]
(One could also argue that we still want `bfsify`'s pruning and the latter case is a bug in it.)

**Comment by ashleygwilliams** [comment]
will schedule something with @isaacs (and perhaps @seldo?) sometime today for this week.
relevant: https://twitter.com/rem/status/689462039937466368 from @remy

**Comment by ashleygwilliams** [comment]
pinging @othiym23 --

i think it was decided that we want to fix what we now (in npm3) identify as a bug in `bfsify`. confirm/deny/elaborate? thanks :smile:
