### ISSUE TITLE
Trying to install node-red-contrib-gpio

### ISSUE THREAD

**Issue by ejaigom** [npm/npm#10988]
# npm install node-red-contrib-gpio
npm ERR! Error: CERT_NOT_YET_VALID
npm ERR!     at SecurePair.<anonymous> (tls.js:1381:32)
npm ERR!     at SecurePair.emit (events.js:92:17)
npm ERR!     at SecurePair.maybeInitFinished (tls.js:980:10)
npm ERR!     at CleartextStream.read [as _read] (tls.js:472:13)
npm ERR!     at CleartextStream.Readable.read (_stream_readable.js:341:10)
npm ERR!     at EncryptedStream.write [as _write] (tls.js:369:25)
npm ERR!     at doWrite (_stream_writable.js:226:10)
npm ERR!     at writeOrBuffer (_stream_writable.js:216:5)
npm ERR!     at EncryptedStream.Writable.write (_stream_writable.js:183:11)
npm ERR!     at write (_stream_readable.js:602:24)
npm ERR!     at flow (_stream_readable.js:611:7)
npm ERR!     at Socket.pipeOnReadable (_stream_readable.js:643:5)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.18.11-v7+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "node-red-contrib-gpio"
npm ERR! cwd /root
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /root/npm-debug.log
npm ERR! not ok code 0

**Comment by KenanY** [comment]
@ejaigom Usually when I see users have this issue it is because their system time is not correct. Could you check and make sure that your system has the correct time configured?

**Comment by ejaigom** [comment]
@KenanY the problem was related with node.js version that is coming within TheThingBox solution.
