### ISSUE TITLE
v3 question: non-deterministic directory structure

### ISSUE THREAD

**Issue by boneskull** [npm/npm#10991]
After reading [this doc](https://docs.npmjs.com/how-npm-works/npm3-nondet), I'm a little bit concerned about using tools such as [Karma](http://karma-runner.github.io).  Often you may need to include a module which was installed via npm to be loaded in the browser.  If I cannot guarantee that a module exists at `node_modules/foo`, this will make things more difficult.

- Is it correct that if you install `angular@1.2` as a top-level dependency, and some other thing has installed `angular@1.3` in the tree, my v1.2 doesn't *necessarily* live at `node_modules/angular`?  Meaning that if before I was including `node_modules/angular/angular.js`, this wouldn't *necessarily* point to v1.2?
- If not, are top-level dependencies guaranteed to be at the top level?
- If so, how am I supposed to go about hunting down the correct version to use in my Karma tests?

I hope I have misunderstood this.  Can someone clear this up?

**Comment by ashleygwilliams** [comment]
hi!

1. if angular@1.2 is a primary dep (i.e. listed in your `package.json`) it will always be at the top-level of `node_modules`, i.e. `node_modules/angular` 

^^ this is a great example and i will add it to the docs!! issue here: https://github.com/npm/docs/issues/526

2. yes, :100: 
3. no worries, no hunting.

hope this helps! thanks for the suggestion for the docs :)

**Comment by boneskull** [comment]
thanks :relieved:
