### ISSUE TITLE
npm directories structure when compiling to dist folder

### ISSUE THREAD

**Issue by jonaskello** [npm/npm#10996]
I'm trying to understand how to structure my npm package directories. I have the following scenario, which I think would be rather common:
1. Using typescript, the source is in a "src" directory
2. The typescript source is compiled to a "dist" directory.
3. Using ES6 imports/exports.
4. Dependent packages are using a git (or file) dependency.
5. The package has several modules that other packages will import (so there is not a single "main" entry point).

So for example, for package "foo", I have the final result in "foo/dist" directory, with exported modules in "foo/dist/module1" and "foo/dist/module2". Now another package wants to import module1 like this:

``` js
import { myclass } from 'foo/module1'
```

However this does not work, instead I have to do:

``` js
import { myclass } from 'foo/dist/module1'
```

However, having everyone including /dist/ in the imports seems like an ugly way to solve the scenario. I hope there is some way to avoid the /dist/ part in the imports. I've read [this](http://blog.izs.me/post/44149270867/why-no-directorieslib-in-node-the-less-snarky) but I cannot see how that applies to comple-to-js langauges like typescript and ES6 import/exports. In particular when you compile you will always end up with your result in a separate directory (unless you somehow compile to the root of the repo?). Also ES6 import/exports encourages having several modules rather than just one "main" module. In particular you cannot easily emulate "require('foo').module1" with ES6 imports.

**Comment by busches** [comment]
@jonaskello were you able to find a solution?

**Comment by nmaro** [comment]
Same here, any recommended practice?

**Comment by jonashartwig** [comment]
I have the same issue and as this is 9 months old I guess there is nothing one can do about it? I am looking through nom docs for hours now.

**Comment by bradennapier** [comment]
Sucks this cant be fixed

**Comment by maximkott** [comment]
Any tips on how to solve this?

**Comment by adospace** [comment]
Reporting here a possible solution:
https://davidwells.io/blog/publishing-flat-npm-packages-for-easier-import-paths-smaller-consumer-bundle-sizes/

In short publishing directly from 'dist' folder solve the problem. Following is my scripts part of package.json that essentially copy the package.json in dist folder and run 'npm publish' from there:
```javascript
"scripts": {
    "build": "tsc",
    "test": "mocha -r jsdom-global/register -r ts-node/register lib/**/*.spec.ts",
    "link" : "tsc && copy /Y package.json dist && copy /Y readme.md dist && cd dist && npm link",
    "dist": "tsc && copy /Y package.json dist && copy /Y readme.md dist && cd dist && npm publish"
  }
```
This works also great with npm link if you want to publish locally.
