### ISSUE TITLE
Proposal: easy hotfix deploys

### ISSUE THREAD

**Issue by jamestalmage** [npm/npm#11001]
Currently it is a bit cumbersome to deploy a hotfix for a package you are not the owner of. 

If the deployed package does not have a build step, it is often possible to just link to a git commit, but Windows users seem to find that problematic (it is git ssh authentication issues I believe, but I am not super clear on the details). 

For packages that **do** contain a build step, a alternative to the first option is to create a second branch (in addition to the original PR branch) and push up build artifacts to that. I typically suffix these branches with `-deploy`, so I end up with my PR branch (`fix-foo`), and a second for deploying my hot-fix while I wait for it to be merged (`fix-foo-deploy`). This is cumbersome, and dependents are easily broken if I forgetfully delete that second branch.

The final option is to redeploy a scoped version under your own user name. This last one seems the most preferable, but it's also the most cumbersome. You need to update `package.json` to reflect a scoped package. You need to decide what version you should use for the deploy (match existing, or do a patch/minor/major bump?). Finally, you need to remember to set `--access=public` when publishing the first time so that you can actually refer to it from other open source projects.

I propose that `npm` be updated to accommodate this last approach in an easy fashion. I think it could be as simple as adding a `--hotfix` flag, that takes a tag name for easy reference:

Assuming I'm working with `awesome-module` (which is not under my control), and I run the following:

```
$ npm publish --hotfix=fix-foo
```

The publish process should proceed as normal, and installing my hotfix should be as simple as:

```
$ npm install @jamestalmage/awesome-module@hot-fix
```

I should just be able to leave `name` and `version` as is in `package.json`. The name should be manipulated on the fly when the `--hotfix` flag is present. I am not sure how best to handle version numbers, but I know I don't want to have to mess them when publishing a hot-fix for someone else's module - I am not really concerned with semver at that point, just getting things working.

I will happily work on a PR if people like this idea.

**Comment by othiym23** [comment]
This sounds like a great opportunity to write a tool to wrap up the workflow you describe. The sense of the CLI team is that the value of this is limited enough that it doesn't justify the complexity cost of adding it to the main codebase ourselves, so I'm going to close this issue, but thank you for the thorough writeup, and let us know if you do decide to turn this into a tool, and we'll let everybody know about it!
