### ISSUE TITLE
help should not show aliases

### ISSUE THREAD

**Issue by SetTrend** [npm/npm#11003]
I believe it's quite confusing to get a list of all the aliases, intermingled with true commands, when entering `npm -?` on the command line.

This is particularly true for mistyped aliases like `verison` appearing in the list of commands.

Moreover, the list of commands becomes overwhelmingly long due to the high amount of feign commands, making the programmer believe a oversized long learning curve is required to handle `NPM`.

So I suggest to only list true commands on `npm help` and omit the aliases. I believe it's sufficient to have aliases quoted along with the description of the command in the manual.

**Comment by iarna** [comment]
We would definitely take a PR to correct typo-aliases. Those aren't supposed to show up.

**Comment by othiym23** [comment]
The only errant alias I see in `npm@3.5.4` is for `verison`, and that's a bug. It'd be great to get a patch to pull that from the help output. Good eye, and thanks!

**Comment by SetTrend** [comment]
There are a number of other confusing aliases [here](https://github.com/npm/npm/blob/08716db30b4c7587a91930007bbf5a70e15204af/lib/npm.js#l60-l95).

Not all of them are displayed with `npm -?`. Yet, many are: `dist-tags`: `dist-tag`. There are even four synonyms displayed for `ls`.

I feel showing these aliases along with the original commands is confusing and unnecessary. It makes you wondering: "When should I use `ll` and when should I use `ls`? What's the difference? Or should I even better use `la`?"

I would believe it's easier to read the *real* commands in one paragraph and the aliases separately in a second one.
