### ISSUE TITLE
npm dist-tag allows tagging invalid/non-existent versions

### ISSUE THREAD

**Issue by sandfox** [npm/npm#11002]
npm version `3.4.1`
node version `0.10.40`
platform: darwin/OSX 15

npm module: `agent-jones`
latest published version: 0.0.11 (with tag `beta`), 0.0.3 (with tag `latest`)

I then ran the commands below (accidentally missing out a decimal in the semver)

```
$ npm dist-tag add agent-jones@0.011 latest
+latest: agent-jones@0.011
 $ npm dist-tag ls
beta: 0.0.11
latest: 0.011
$ npm dist-tag rm agent-jones beta
-beta: agent-jones@0.0.11
```

Then end result being that npm website shows mostly blank info and running `npm info agent-jones` returns nothing... (runs but exits cleanly with zero output)

I could be wrong but I feel that the registry probably shouldn't let me tag no-existent versions (at least for `latest`), or at least throw some more errors/notices on other commands when things get into this invalid state?

Let me know if you need any more info.

**Comment by othiym23** [comment]
I deleted the attachment because

a. I'm assuming it got included by mistake and
b. it was in violation of npm's [Code of Conduct](https://www.npmjs.com/policies/conduct)

**Comment by sandfox** [comment]
@othiym23 :grimacing:  the attachment should have been been a screenshot of the npm website??? (at least thats what I intended to upload)
