### ISSUE TITLE
npm install --prefix: still available?

### ISSUE THREAD

**Issue by SetTrend** [npm/npm#11007]
For my web application project I want to install javascript libraries to dedicated sub directories of the project, e. g.:

```
| my_project\
| -- scripts\
| -- | -- angular\
| -- | -- | -- angular.min.js
| -- | -- | -- angular-animate.min.js
| -- | -- | -- angular-route.min.js
| -- | -- require\
| -- | -- | -- require.min.js
```

In similar question at [Stack Exchange](https://www.google.de/search?q=npm+link+windows) I found answers that there is supposed to be a `--prefix` option for the `npm install` command, e.g.:

```
npm install angular --prefix .\scripts\angular
npm install angular-animate --prefix .\scripts\angular
npm install angular-route --prefix .\scripts\angular
npm install require --prefix .\scripts\require
```

In the documentation of the `npm install` command, however, I can't find anything about the `--prefix` option. Is it still supported? What's its exact behaviour?

**Comment by smikes** [comment]
The `--prefix` command line option is still supported.  It has the effect of changing the `prefix` configuration variable, as documented here : https://docs.npmjs.com/misc/config#prefix

However, I'm not confident that you can use the prefix setting to construct a directory structure as you have shown above.  Can you tell me more about what you're trying to do and why the standard npm directory structure won't work for you?

**Comment by SetTrend** [comment]
Thanks, smikes, for helping me on this.

I'm sharing a concern [with some other developers](https://www.google.de/search?q=npm+install+different+directory):

We all want to be able to group correlated JavaScript packages into their respective sub folders for web deployment.

One reason is that it eases administration when it comes to maintaining a web site on the web server. Another reason is that we can make sure to avoid naming conflicts as different packages' file names may collide.

**Comment by wesleyboar** [comment]
**I had this problem also with `--prefix`, and now I do not.**

I also could not successfully use the CLI argument `--prefix` to define a local directory for `npm install`. **I was running `npm` at version `2.14.x`**. I upgraded my `npm` by running

```
npm install npm -g
```

Afterwards, **I was running `npm` at version `3.10.7`**. Now, I can use the CLI argument `--prefix` to define a local directory for `npm install`.

_**Notice:** This solution is for the CLI argument `--prefix`. I am still unable to successfully use the `prefix` configuration via any of [the other methods available](https://docs.npmjs.com/misc/config). **See [issue #13933](https://github.com/npm/npm/issues/13933).**_

**Comment by monolithed** [comment]
Maybe a similar issue https://github.com/npm/npm/issues/14633
