### ISSUE TITLE
Cannot install npm install mysql

### ISSUE THREAD

**Issue by ridxvin** [npm/npm#11018]
this is npm-debug.log

> > > 0 info it worked if it ends with ok
> > > 1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
> > > 1 verbose cli   'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
> > > 1 verbose cli   'install',
> > > 1 verbose cli   '-g',
> > > 1 verbose cli   'felixge/node-mysql' ]
> > > 2 info using npm@3.3.12
> > > 3 info using node@v5.3.0
> > > 4 silly loadCurrentTree Starting
> > > 5 silly install loadCurrentTree
> > > 6 silly install readGlobalPackageData
> > > 7 silly fetchPackageMetaData felixge/node-mysql
> > > 8 silly fetchOtherPackageData felixge/node-mysql
> > > 9 silly cache add args [ 'felixge/node-mysql', null ]
> > > 10 verbose cache add spec felixge/node-mysql
> > > 11 silly cache add parsed spec Result {
> > > 11 silly cache add   raw: 'felixge/node-mysql',
> > > 11 silly cache add   scope: null,
> > > 11 silly cache add   name: null,
> > > 11 silly cache add   rawSpec: 'felixge/node-mysql',
> > > 11 silly cache add   spec: 'github:felixge/node-mysql',
> > > 11 silly cache add   type: 'hosted',
> > > 11 silly cache add   hosted:
> > > 11 silly cache add    { type: 'github',
> > > 11 silly cache add      ssh: 'git@github.com:felixge/node-mysql.git',
> > > 11 silly cache add      sshUrl: 'git+ssh://git@github.com/felixge/node-mysql.git',
> > > 11 silly cache add      httpsUrl: 'git+https://github.com/felixge/node-mysql.git',
> > > 11 silly cache add      gitUrl: 'git://github.com/felixge/node-mysql.git',
> > > 11 silly cache add      shortcut: 'github:felixge/node-mysql',
> > > 11 silly cache add      directUrl: 'https://raw.githubusercontent.com/felixge/node-mysql/master/package.json' } }
> > > 12 verbose addRemoteGit caching felixge/node-mysql
> > > 13 verbose addRemoteGit felixge/node-mysql is a repository hosted by github
> > > 14 silly tryGitProto attempting to clone git://github.com/felixge/node-mysql.git
> > > 15 silly tryClone cloning felixge/node-mysql via git://github.com/felixge/node-mysql.git
> > > 16 verbose tryClone git-github-com-felixge-node-mysql-git-dc9531aca6015a01e3869408854fa39a not in flight; caching
> > > 17 info git [ 'config', '--get', 'remote.origin.url' ]
> > > 18 warn addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
> > > 18 warn addRemoteGit
> > > 18 warn addRemoteGit     at ChildProcess.exithandler (child_process.js:213:12)
> > > 18 warn addRemoteGit     at emitTwo (events.js:87:13)
> > > 18 warn addRemoteGit     at ChildProcess.emit (events.js:172:7)
> > > 18 warn addRemoteGit     at maybeClose (internal/child_process.js:818:16)
> > > 18 warn addRemoteGit     at Socket.<anonymous> (internal/child_process.js:319:11)
> > > 18 warn addRemoteGit     at emitOne (events.js:77:13)
> > > 18 warn addRemoteGit     at Socket.emit (events.js:169:7)
> > > 18 warn addRemoteGit     at Pipe._onclose (net.js:469:12)
> > > 18 warn addRemoteGit  felixge/node-mysql resetting remote C:\Users\user\AppData\Roaming\npm-cache_git-remotes\git-github-com-felixge-node-mysql-git-dc9531aca6015a01e3869408854fa39a because of error: { [Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
> > > 18 warn addRemoteGit ]
> > > 18 warn addRemoteGit   killed: false,
> > > 18 warn addRemoteGit   code: 1,
> > > 18 warn addRemoteGit   signal: null,
> > > 18 warn addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
> > > 19 info resetRemote resetting C:\Users\user\AppData\Roaming\npm-cache_git-remotes\git-github-com-felixge-node-mysql-git-dc9531aca6015a01e3869408854fa39a for felixge/node-mysql
> > > 20 silly gentlyRm C:\Users\user\AppData\Roaming\npm-cache_git-remotes\git-github-com-felixge-node-mysql-git-dc9531aca6015a01e3869408854fa39a is being purged
> > > 21 verbose gentlyRm don't care about contents; nuking C:\Users\user\AppData\Roaming\npm-cache_git-remotes\git-github-com-felixge-node-mysql-git-dc9531aca6015a01e3869408854fa39a
> > > 22 silly vacuum-fs purging C:\Users\user\AppData\Roaming\npm-cache_git-remotes\git-github-com-felixge-node-mysql-git-dc9531aca6015a01e3869408854fa39a
> > > 23 silly vacuum-fs quitting because other entries in C:\Users\user\AppData\Roaming\npm-cache_git-remotes
> > > 24 info git [ 'clone',
> > > 24 info git   '--template=C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\_templates',
> > > 24 info git   '--mirror',
> > > 24 info git   'git://github.com/felixge/node-mysql.git',
> > > 24 info git   'C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\git-github-com-felixge-node-mysql-git-dc9531aca6015a01e3869408854fa39a' ]
> > > 25 error git clone --template=C:\Users\user\AppData\Roaming\npm-cache_git-remotes_templates --mirror git://github.com/felixge/node-mysql.git C:\Users\user\AppData\Roaming\npm-cache_git-remotes\git-github-com-felixge-node-mysql-git-dc9531aca6015a01e3869408854fa39a: Cloning into bare repository 'C:\Users\user\AppData\Roaming\npm-cache_git-remotes\git-github-com-felixge-node-mysql-git-dc9531aca6015a01e3869408854fa39a'...
> > > 25 error git clone --template=C:\Users\user\AppData\Roaming\npm-cache_git-remotes_templates --mirror git://github.com/felixge/node-mysql.git C:\Users\user\AppData\Roaming\npm-cache_git-remotes\git-github-com-felixge-node-mysql-git-dc9531aca6015a01e3869408854fa39a: fatal: unable to access 'HTTP://https:////github.com/felixge/node-mysql.git/': Couldn't resolve host 'https'
> > > 26 silly tryHTTPS attempting to clone git+https://github.com/felixge/node-mysql.git
> > > 27 silly tryClone cloning felixge/node-mysql via git+https://github.com/felixge/node-mysql.git
> > > 28 verbose tryClone git-https-github-com-felixge-node-mysql-git-5a906e292078d71ad9a1857d26078bef not in flight; caching
> > > 29 info git [ 'config', '--get', 'remote.origin.url' ]
> > > 30 warn addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
> > > 30 warn addRemoteGit
> > > 30 warn addRemoteGit     at ChildProcess.exithandler (child_process.js:213:12)
> > > 30 warn addRemoteGit     at emitTwo (events.js:87:13)
> > > 30 warn addRemoteGit     at ChildProcess.emit (events.js:172:7)
> > > 30 warn addRemoteGit     at maybeClose (internal/child_process.js:818:16)
> > > 30 warn addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
> > > 30 warn addRemoteGit  felixge/node-mysql resetting remote C:\Users\user\AppData\Roaming\npm-cache_git-remotes\git-https-github-com-felixge-node-mysql-git-5a906e292078d71ad9a1857d26078bef because of error: { [Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
> > > 30 warn addRemoteGit ]
> > > 30 warn addRemoteGit   killed: false,
> > > 30 warn addRemoteGit   code: 1,
> > > 30 warn addRemoteGit   signal: null,
> > > 30 warn addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
> > > 31 info resetRemote resetting C:\Users\user\AppData\Roaming\npm-cache_git-remotes\git-https-github-com-felixge-node-mysql-git-5a906e292078d71ad9a1857d26078bef for felixge/node-mysql
> > > 32 silly gentlyRm C:\Users\user\AppData\Roaming\npm-cache_git-remotes\git-https-github-com-felixge-node-mysql-git-5a906e292078d71ad9a1857d26078bef is being purged
> > > 33 verbose gentlyRm don't care about contents; nuking C:\Users\user\AppData\Roaming\npm-cache_git-remotes\git-https-github-com-felixge-node-mysql-git-5a906e292078d71ad9a1857d26078bef
> > > 34 silly vacuum-fs purging C:\Users\user\AppData\Roaming\npm-cache_git-remotes\git-https-github-com-felixge-node-mysql-git-5a906e292078d71ad9a1857d26078bef
> > > 35 silly vacuum-fs quitting because other entries in C:\Users\user\AppData\Roaming\npm-cache_git-remotes
> > > 36 info git [ 'clone',
> > > 36 info git   '--template=C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\_templates',
> > > 36 info git   '--mirror',
> > > 36 info git   'https://github.com/felixge/node-mysql.git',
> > > 36 info git   'C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-felixge-node-mysql-git-5a906e292078d71ad9a1857d26078bef' ]
> > > 37 error git clone --template=C:\Users\user\AppData\Roaming\npm-cache_git-remotes_templates --mirror https://github.com/felixge/node-mysql.git C:\Users\user\AppData\Roaming\npm-cache_git-remotes\git-https-github-com-felixge-node-mysql-git-5a906e292078d71ad9a1857d26078bef: Cloning into bare repository 'C:\Users\user\AppData\Roaming\npm-cache_git-remotes\git-https-github-com-felixge-node-mysql-git-5a906e292078d71ad9a1857d26078bef'...
> > > 37 error git clone --template=C:\Users\user\AppData\Roaming\npm-cache_git-remotes_templates --mirror https://github.com/felixge/node-mysql.git C:\Users\user\AppData\Roaming\npm-cache_git-remotes\git-https-github-com-felixge-node-mysql-git-5a906e292078d71ad9a1857d26078bef: fatal: unable to access 'https://github.com/felixge/node-mysql.git/': error setting certificate verify locations:
> > > 37 error git clone --template=C:\Users\user\AppData\Roaming\npm-cache_git-remotes_templates --mirror https://github.com/felixge/node-mysql.git C:\Users\user\AppData\Roaming\npm-cache_git-remotes\git-https-github-com-felixge-node-mysql-git-5a906e292078d71ad9a1857d26078bef:   CAfile: C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
> > > 37 error git clone --template=C:\Users\user\AppData\Roaming\npm-cache_git-remotes_templates --mirror https://github.com/felixge/node-mysql.git C:\Users\user\AppData\Roaming\npm-cache_git-remotes\git-https-github-com-felixge-node-mysql-git-5a906e292078d71ad9a1857d26078bef:   CApath: none
> > > 38 silly trySSH attempting to clone git@github.com:felixge/node-mysql.git
> > > 39 silly tryClone cloning felixge/node-mysql via git@github.com:felixge/node-mysql.git
> > > 40 verbose tryClone git-github-com-felixge-node-mysql-git-d02c1571a0428c4d7486dcb5c45dba72 not in flight; caching
> > > 41 info git [ 'config', '--get', 'remote.origin.url' ]
> > > 42 warn addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
> > > 42 warn addRemoteGit
> > > 42 warn addRemoteGit     at ChildProcess.exithandler (child_process.js:213:12)
> > > 42 warn addRemoteGit     at emitTwo (events.js:87:13)
> > > 42 warn addRemoteGit     at ChildProcess.emit (events.js:172:7)
> > > 42 warn addRemoteGit     at maybeClose (internal/child_process.js:818:16)
> > > 42 warn addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
> > > 42 warn addRemoteGit  felixge/node-mysql resetting remote C:\Users\user\AppData\Roaming\npm-cache_git-remotes\git-github-com-felixge-node-mysql-git-d02c1571a0428c4d7486dcb5c45dba72 because of error: { [Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
> > > 42 warn addRemoteGit ]
> > > 42 warn addRemoteGit   killed: false,
> > > 42 warn addRemoteGit   code: 1,
> > > 42 warn addRemoteGit   signal: null,
> > > 42 warn addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
> > > 43 info resetRemote resetting C:\Users\user\AppData\Roaming\npm-cache_git-remotes\git-github-com-felixge-node-mysql-git-d02c1571a0428c4d7486dcb5c45dba72 for felixge/node-mysql
> > > 44 silly gentlyRm C:\Users\user\AppData\Roaming\npm-cache_git-remotes\git-github-com-felixge-node-mysql-git-d02c1571a0428c4d7486dcb5c45dba72 is being purged
> > > 45 verbose gentlyRm don't care about contents; nuking C:\Users\user\AppData\Roaming\npm-cache_git-remotes\git-github-com-felixge-node-mysql-git-d02c1571a0428c4d7486dcb5c45dba72
> > > 46 silly vacuum-fs purging C:\Users\user\AppData\Roaming\npm-cache_git-remotes\git-github-com-felixge-node-mysql-git-d02c1571a0428c4d7486dcb5c45dba72
> > > 47 silly vacuum-fs quitting because other entries in C:\Users\user\AppData\Roaming\npm-cache_git-remotes
> > > 48 info git [ 'clone',
> > > 48 info git   '--template=C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\_templates',
> > > 48 info git   '--mirror',
> > > 48 info git   'git@github.com:felixge/node-mysql.git',
> > > 48 info git   'C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\git-github-com-felixge-node-mysql-git-d02c1571a0428c4d7486dcb5c45dba72' ]
> > > 49 error git clone --template=C:\Users\user\AppData\Roaming\npm-cache_git-remotes_templates --mirror git@github.com:felixge/node-mysql.git C:\Users\user\AppData\Roaming\npm-cache_git-remotes\git-github-com-felixge-node-mysql-git-d02c1571a0428c4d7486dcb5c45dba72: Cloning into bare repository 'C:\Users\user\AppData\Roaming\npm-cache_git-remotes\git-github-com-felixge-node-mysql-git-d02c1571a0428c4d7486dcb5c45dba72'...
> > > 49 error git clone --template=C:\Users\user\AppData\Roaming\npm-cache_git-remotes_templates --mirror git@github.com:felixge/node-mysql.git C:\Users\user\AppData\Roaming\npm-cache_git-remotes\git-github-com-felixge-node-mysql-git-d02c1571a0428c4d7486dcb5c45dba72: Host key verification failed.
> > > 49 error git clone --template=C:\Users\user\AppData\Roaming\npm-cache_git-remotes_templates --mirror git@github.com:felixge/node-mysql.git C:\Users\user\AppData\Roaming\npm-cache_git-remotes\git-github-com-felixge-node-mysql-git-d02c1571a0428c4d7486dcb5c45dba72: fatal: Could not read from remote repository.
> > > 49 error git clone --template=C:\Users\user\AppData\Roaming\npm-cache_git-remotes_templates --mirror git@github.com:felixge/node-mysql.git C:\Users\user\AppData\Roaming\npm-cache_git-remotes\git-github-com-felixge-node-mysql-git-d02c1571a0428c4d7486dcb5c45dba72:
> > > 49 error git clone --template=C:\Users\user\AppData\Roaming\npm-cache_git-remotes_templates --mirror git@github.com:felixge/node-mysql.git C:\Users\user\AppData\Roaming\npm-cache_git-remotes\git-github-com-felixge-node-mysql-git-d02c1571a0428c4d7486dcb5c45dba72: Please make sure you have the correct access rights
> > > 49 error git clone --template=C:\Users\user\AppData\Roaming\npm-cache_git-remotes_templates --mirror git@github.com:felixge/node-mysql.git C:\Users\user\AppData\Roaming\npm-cache_git-remotes\git-github-com-felixge-node-mysql-git-d02c1571a0428c4d7486dcb5c45dba72: and the repository exists.
> > > 50 silly fetchPackageMetaData Error: Command failed: git -c core.longpaths=true clone --template=C:\Users\user\AppData\Roaming\npm-cache_git-remotes_templates --mirror git@github.com:felixge/node-mysql.git C:\Users\user\AppData\Roaming\npm-cache_git-remotes\git-github-com-felixge-node-mysql-git-d02c1571a0428c4d7486dcb5c45dba72
> > > 50 silly fetchPackageMetaData Cloning into bare repository 'C:\Users\user\AppData\Roaming\npm-cache_git-remotes\git-github-com-felixge-node-mysql-git-d02c1571a0428c4d7486dcb5c45dba72'...
> > > 50 silly fetchPackageMetaData Host key verification failed.
> > > 50 silly fetchPackageMetaData fatal: Could not read from remote repository.
> > > 50 silly fetchPackageMetaData
> > > 50 silly fetchPackageMetaData Please make sure you have the correct access rights
> > > 50 silly fetchPackageMetaData and the repository exists.
> > > 50 silly fetchPackageMetaData
> > > 50 silly fetchPackageMetaData     at ChildProcess.exithandler (child_process.js:213:12)
> > > 50 silly fetchPackageMetaData     at emitTwo (events.js:87:13)
> > > 50 silly fetchPackageMetaData     at ChildProcess.emit (events.js:172:7)
> > > 50 silly fetchPackageMetaData     at maybeClose (internal/child_process.js:818:16)
> > > 50 silly fetchPackageMetaData     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
> > > 50 silly fetchPackageMetaData  error for felixge/node-mysql { [Error: Command failed: git -c core.longpaths=true clone --template=C:\Users\user\AppData\Roaming\npm-cache_git-remotes_templates --mirror git@github.com:felixge/node-mysql.git C:\Users\user\AppData\Roaming\npm-cache_git-remotes\git-github-com-felixge-node-mysql-git-d02c1571a0428c4d7486dcb5c45dba72
> > > 50 silly fetchPackageMetaData Cloning into bare repository 'C:\Users\user\AppData\Roaming\npm-cache_git-remotes\git-github-com-felixge-node-mysql-git-d02c1571a0428c4d7486dcb5c45dba72'...
> > > 50 silly fetchPackageMetaData Host key verification failed.
> > > 50 silly fetchPackageMetaData fatal: Could not read from remote repository.
> > > 50 silly fetchPackageMetaData
> > > 50 silly fetchPackageMetaData Please make sure you have the correct access rights
> > > 50 silly fetchPackageMetaData and the repository exists.
> > > 50 silly fetchPackageMetaData ]
> > > 50 silly fetchPackageMetaData   killed: false,
> > > 50 silly fetchPackageMetaData   code: 128,
> > > 50 silly fetchPackageMetaData   signal: null,
> > > 50 silly fetchPackageMetaData   cmd: 'git -c core.longpaths=true clone --template=C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:felixge/node-mysql.git C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\git-github-com-felixge-node-mysql-git-d02c1571a0428c4d7486dcb5c45dba72' }
> > > 51 silly rollbackFailedOptional Starting
> > > 52 silly rollbackFailedOptional Finishing
> > > 53 silly runTopLevelLifecycles Starting
> > > 54 silly runTopLevelLifecycles Finishing
> > > 55 silly install printInstalled
> > > 56 verbose stack Error: Command failed: git -c core.longpaths=true clone --template=C:\Users\user\AppData\Roaming\npm-cache_git-remotes_templates --mirror git@github.com:felixge/node-mysql.git C:\Users\user\AppData\Roaming\npm-cache_git-remotes\git-github-com-felixge-node-mysql-git-d02c1571a0428c4d7486dcb5c45dba72
> > > 56 verbose stack Cloning into bare repository 'C:\Users\user\AppData\Roaming\npm-cache_git-remotes\git-github-com-felixge-node-mysql-git-d02c1571a0428c4d7486dcb5c45dba72'...
> > > 56 verbose stack Host key verification failed.
> > > 56 verbose stack fatal: Could not read from remote repository.
> > > 56 verbose stack
> > > 56 verbose stack Please make sure you have the correct access rights
> > > 56 verbose stack and the repository exists.
> > > 56 verbose stack
> > > 56 verbose stack     at ChildProcess.exithandler (child_process.js:213:12)
> > > 56 verbose stack     at emitTwo (events.js:87:13)
> > > 56 verbose stack     at ChildProcess.emit (events.js:172:7)
> > > 56 verbose stack     at maybeClose (internal/child_process.js:818:16)
> > > 56 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
> > > 57 verbose cwd C:\AppServ\www\mrfm\assets\nodejs
> > > 58 error Windows_NT 6.1.7601
> > > 59 error argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "felixge/node-mysql"
> > > 60 error node v5.3.0
> > > 61 error npm  v3.3.12
> > > 62 error code 128
> > > 63 error Command failed: git -c core.longpaths=true clone --template=C:\Users\user\AppData\Roaming\npm-cache_git-remotes_templates --mirror git@github.com:felixge/node-mysql.git C:\Users\user\AppData\Roaming\npm-cache_git-remotes\git-github-com-felixge-node-mysql-git-d02c1571a0428c4d7486dcb5c45dba72
> > > 63 error Cloning into bare repository 'C:\Users\user\AppData\Roaming\npm-cache_git-remotes\git-github-com-felixge-node-mysql-git-d02c1571a0428c4d7486dcb5c45dba72'...
> > > 63 error Host key verification failed.
> > > 63 error fatal: Could not read from remote repository.
> > > 63 error
> > > 63 error Please make sure you have the correct access rights
> > > 63 error and the repository exists.
> > > 64 error If you need help, you may report this error at:
> > > 64 error     https://github.com/npm/npm/issues
> > > 65 verbose exit [ 1, true ]

**Comment by ridxvin** [comment]
Sorry, im new in npm , node and etc. the truth is im quite clueless

**Comment by smartmouse** [comment]
did u define a package.json in your project? or you just do npm install mysql?  Can you install other packages at all?  e.g. npm install color? looks like your environment specific issue.


C:\Users\ADMIN\test1>npm install mysql
C:\Users\ADMIN\test1
└─┬ mysql@2.10.0
  ├── bignumber.js@2.1.2
  └─┬ readable-stream@1.1.13
    ├── core-util-is@1.0.2
    ├── inherits@2.0.1
    ├── isarray@0.0.1
    └── string_decoder@0.10.31

**Comment by Klortho** [comment]
I had this same issue, and discovered that it was (I'm pretty sure) because my package.json was pointing to a non-existent commit -- I had rebased the target repository.

Reverse engineering your error message, @ridxvin , I notice that https://github.com/felixge/node-mysql/commit/d02c1571a0428c4d gives a 404 -- so maybe you should update your package.json to point to another commit, or use a branch name.
