### ISSUE TITLE
"error: ENOENT" after uninstalling global package

### ISSUE THREAD

**Issue by pawelgrzybek** [npm/npm#11015]
Hello.

After uninstalling globally installed package and listing all globbal packages, I have an error: "error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/speed-test/package.json". I didn't have this problem before. Probably it occurs after recent npm update. Any ideas how to fix it and correctly uninstall global packages?

![screen shot 2016-01-03 at 15 09 58](https://cloud.githubusercontent.com/assets/3697104/12079331/a408435e-b22c-11e5-9a50-d56de192cea6.png)

**Comment by FuzzOli87** [comment]
I'm getting the same error as well

**Comment by shaungrady** [comment]
Same with
```
Node: v5.4.1
NPM: 3.5.3
```

**Comment by kpes** [comment]
same here, both local and global uninstalls.
Node: v4.2.4
NPM: v3.5.3

For now, I'm doing a list after uninstall and manually removing directory mentioned in the error to clear it up.  That at least seems to do the trick for me, not sure if it's good or bad.  Also finding it's not with all uninstalls, but I haven't found a clear pattern yet.

**Comment by davidvgalbraith** [comment]
Definitely happens with the speed-test package. I tried it with async, bluebird, checker, underscore, clean, mimimist, mkdirp, and optimist, and none of them had this problem. So, think there's something about speed-test specifically that doesn't play nice with latest NPM.

**Comment by pawelgrzybek** [comment]
Thats true it works fine with packages that you just listed. I tested it with few more and it really happens for so many plugins not only speed-test :(

Here is an example with npm-check-updates
![screen shot 2016-01-18 at 11 14 05](https://cloud.githubusercontent.com/assets/3697104/12390054/d7e56162-bdd4-11e5-893e-fd3f70e1d77b.png)

Maybe we can try to list plugins that we have this issue with and then we will find a common problem for all these packages? Please provide your list whenever you come across this bug.

**Comment by ilikebits** [comment]
`browserify` and `pulp` at least both experience this. I think this might be happening in general when a global package is installed.

**Comment by nicknikolov** [comment]
I got it with browserify and bower.

**Comment by labithiotis** [comment]
Was happening to me too.

A fix (solution):

- Go to global node_module folder, for me that is `/usr/local/lib/node_modules`.
- Remove errorsome module folders `rm -rf XXX`
- `npm -g cache clean`
- Then run `npm -g list -depth 0`

**Comment by raphinesse** [comment]
Why was this closed? I experienced the same faulty behavior just now.

Packages: `yo`, `generator-angular`, `generator-karma` 
npm 4.6.1 @ Ubuntu 16.10
