### ISSUE TITLE
Republishing with New Version Number

### ISSUE THREAD

**Issue by lukejanicke** [npm/npm#11012]
If you unpublished a package, you should be able to re-publish it if you increment the version number. I unpublished a package. At the time I thought I could republish v1.0.0. Now I am trying to republish it as version 2.0.0. But I get this error message.

````
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/trifecta
npm ERR! 404 
npm ERR! 404 'trifecta' is not in the npm registry.
````

Of course the package isn't in the registry. I unpublished it.

How can I (re)publish the package? Please don't tell me to increment the version number :) I've been trying that already. I must be missing something else.

**Comment by smartmouse** [comment]
When you unpublish your package, did you specify a specific version to unpublish?
