### ISSUE TITLE
Can I depend on a package on my local filesystem?

### ISSUE THREAD

**Issue by jkroso** [npm/npm#11017]
I noticed that `npm-package-arg` parses them correctly but then the installation process fails. Is that something that is supposed to be supported but just isn't working or something else.

To be clear when I say depend on a local package I mean:

```json
{
  "dependencies": {
    "/a/local/directory": "*"
  }
}
```

**Comment by KenanY** [comment]
@jkroso Like [this](https://docs.npmjs.com/files/package.json#local-paths)?

**Comment by jkroso** [comment]
Yea exactly like that except it doesn't work as advertised or in any other way. As far as I can tell it just ignores local deps

**Comment by jkroso** [comment]
Actually it turned out I had used the wrong name. It did work when used the same name that was in its package.json
