### ISSUE TITLE
doc: clarify error when adding a tag that is valid semver

### ISSUE THREAD

**Issue by ashleygwilliams** [npm/npm#11025]
from https://github.com/npm/docs/issues/531 cc @M-Zuber

Per https://docs.npmjs.com/cli/dist-tag#caveats the value provided to the `--tag` flag can not be valid semver.
But when I run `npm publish --tag v0.0.3-pre` for example the output is:
`Tag name must not be a valid SemVer range: v0.0.4-0`

This is confusing as `must` can also be understood as: it seems to not be valid, so change it to a valid semver value.

`Tag name can not be a valid SemVer range: v0.0.4-0` would be much clearer

**Comment by M-Zuber** [comment]
Thank you for moving this for me :)

**Comment by M-Zuber** [comment]
I'll toss in some more feedback on the topic of tags:
No where is it mentioned that if you specify `--tag`, then the release does not show up on the npm site, and you have to use the cli or ask a maintainer about it's existence.

**Comment by tyleranton** [comment]
I can take care of this!

**Comment by Hywan** [comment]
Can be closed I guess?

**Comment by alundiak** [comment]
MacOS Sierra 

```
➜  feby git:(master) npm publish . --tag 1.0.1
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "publish" "." "--tag" "1.0.1"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10

npm ERR! Tag name must not be a valid SemVer range: 1.0.1
```

```
➜  feby git:(master) ✗ npm publish . --tag v1.0.2
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "publish" "." "--tag" "v1.0.2"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2

npm ERR! Tag name must not be a valid SemVer range: v1.0.2
```

FYI:
```
➜  feby git:(master) npm whoami --registry https://registry.npmjs.org/
alundiak
```

And BTW, if I omit `--tag` assuming npm takes `latest` publish goes through.

```
feby git:(master) npm publish . --access public
+ feby@1.0.3
```
Yes, `v1.0.3` is latest git tag, but version value in package.json is `1.0.3` (no `v` prefix.)

Not sure if this is my local env related or still official bug remaining not fixed?
I realize, that `1.0.1` is valid SemVer, but I see people having issue even with `v-` like tags. Also tried with `v1.0.2`

cc/ @Hywan  @tyleranton @M-Zuber @ashleygwilliams
