### ISSUE TITLE
Exit status 3221225477 trying to run lifecycle scripts on Windows

### ISSUE THREAD

**Issue by saper** [npm/npm#11024]
There are few reports that custom lifecycle scripts do get executed of Windows with a similar pattern:

```
17938 error node v5.0.0
17939 error npm v3.3.6
17940 error code ELIFECYCLE
17941 error node-sass@3.4.2 postinstall: node scripts/build.js
17941 error Exit status 3221225477
```

node-sass report for the `postinstall` script: https://github.com/sass/node-sass/issues/1283
node-sass report for the `install` script: https://github.com/sass/node-sass/issues/1326

There was also an unconclusive report https://github.com/npm/npm/issues/10549

Exit code 3221225477 is `C0000005` or `ACCESS_VIOLATION`. 

This is probably some environmental issue but I think it should be tracked down in a matter similar to https://github.com/npm/npm/issues/8751 we've had before.

**Comment by aredridel** [comment]
Antivirus, perhaps?

**Comment by tbenbrahim** [comment]
Same error with webpack -w on Windows 7:
````
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program     Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! epsr@1.0.0 start: `webpack -w --config webpack.dev.config.js
npm ERR! Exit status 3221225477
````
and the stack from npm_debug.log
````
9 verbose stack Error: epsr@1.0.0 start: `webpack -w --config webpack.dev.config.js`
9 verbose stack Exit status 3221225477
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1015:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
10 verbose pkgid epsr@1.0.0
````

**Comment by saper** [comment]
My initial analysis says it looks like it is a deeper problem concerning Windows ABI compatibility. We might need to change the way we build node modules on Windows. 

@tbenbrahim thank you for this - this just basically means this is a crash. If the reason is the same, it would be a confirmation that not only XP is involved (which supports my theory about general ABI problems). 

Can you give me a step by step guide to reproduce this problem? Assume I have nothing installed except for node + npm

**Comment by jpsfs** [comment]
Hi!

I'm facing the same issue. Windows Server 2012 R2, building a Typescript project.
Any update on this?

Best,

**Comment by legodude17** [comment]
It seems like this is a problem with `node-sass`.

**Comment by mriehema** [comment]
Please check https://github.com/sass/node-sass/issues/1863

**Comment by saper** [comment]
@jpsfs you need  to post more details - the exact steps to reproduce (so I can see it on my own machine) and your detailed logs i.e. the actual error messages.

@legodude17 this particular problem has been fixed in node-sass long time ago.

**Comment by joecfan** [comment]
I'm facing the same issue too, when I  do npm run build,below error occurred, some times do npm run build several times , it'll be OK. 
env:  
win 7 , npm version:5.3.0 , node version: 4.2.2, vc++ 2015 Redistributable(x64), vs .NET Framework 4.5.2

404s will fallback to /index.html
 67% 1394/1461 build modulesnpm ERR! code ELIFECYCLE
npm ERR! errno 3221225477
npm ERR! personal@4.1.0 watch: `webpack-dev-server --hot --inline --progress --c
olors --port 5000`
npm ERR! Exit status 3221225477
npm ERR!
npm ERR! Failed at the personal@4.1.0 watch script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Program Files\nodejs\node_cache\_logs\2017-08-31T08_58_25_594Z-d
ebug.log

**Comment by corydeppen** [comment]
I'm seeing this same `Command failed with exit code 3221225477` error when running both `npm run test` and `yarn test` on a Win 10 machine. It's a corporate dev machine loaded to the gills with virus scanning software, but this same set of tests that are kicked off by a Bash script run without a problem when using `cross-env`, so I'm really at a loss where the problem lies. I'd really just like to have an idea what the culprit might be and if there's a fix or workaround for it.

**Comment by edant92** [comment]
I've having this same error too, but only when I run `npm run build` . `npm start` and `npm run test` work fine.
