### ISSUE TITLE
running light weight npm dedupe after npm install

### ISSUE THREAD

**Issue by sunnyrjuneja** [npm/npm#11027]
@ashleygwilliams tweeted an article explaining how to use npm dedupe (https://docs.npmjs.com/how-npm-works/npm3-dupe). I tweeted her asking why npm dedupe doesn't run after every npm install. She recommended I file it as an issue (https://twitter.com/ag_dubs/status/682294607032528896 + https://github.com/npm/docs/issues/524).

After filing the issue, she responded that @iarna agrees and I should refile this as a feature request on this repo.

**Comment by othiym23** [comment]
This is a solution for a small subset of the much larger problem of ensuring that every install from a given `package.json` (perhaps with `npm install --save`) produces a dependency tree with the same shape. While it would clear up some instances of this, to really solve the problem of different installs producing different trees, the install algorithm would need to be changed to take this into account. This is a relatively simple change for the team to make, but it doesn't solve that _much_ of the problem, and so it's not the best use of our resources.

That said, if you feel like figuring out the relevant code in the installer and dedup and submitting this change as a patch, we'd be happy to land it. Thank you for your time and for writing this up!

**Comment by sunnyrjuneja** [comment]
@othiym23 No promises but I already started looking around to do so. Do you have a suggestion of how to get started with the npm codebase? Perhaps relevant docs that might point me in the right direction. I checked out https://github.com/npm/npm/blob/master/CONTRIBUTING.md.
