### ISSUE TITLE
Error occurred during the execution of command npm install mysql

### ISSUE THREAD

**Issue by RReji** [npm/npm#11031]
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x8
6)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "mysql"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
npm ERR! code SELF_SIGNED_CERT_IN_CHAIN

npm ERR! self signed certificate in certificate chain

![npm-debug-log](https://cloud.githubusercontent.com/assets/16514495/12108721/d174f6be-b3a0-11e5-800f-3f0bde0170c3.png)
![npm-debug-log1](https://cloud.githubusercontent.com/assets/16514495/12108726/dfe4d0fc-b3a0-11e5-9d32-2743cb2cfb85.png)

**Comment by ederkley** [comment]
have you made sure strict-ssl=false in npm config?
check: npm config get strict-ssl
set: npm config set strict-ssl=false

**Comment by RReji** [comment]
@ederkley Thanks. Problem solved.
