### ISSUE TITLE
Nested modules are missing

### ISSUE THREAD

**Issue by TerenceZ** [npm/npm#11043]
The npm version is v3.5.2, Here is the package dependencies:

``` json
  "devDependencies": {
    "babel": "^6.3.26",
    "babel-cli": "^6.3.17",
    "babel-core": "^6.3.26",
    "babel-preset-es2015": "^6.3.13",
    "babel-preset-stage-0": "^6.3.13",
    "rimraf": "^2.4.4"
  },
  "dependencies": {
    "babel-eslint": "^4.1.6",
    "eslint": "^1.10.3",
    "eslint-plugin-html": "^1.1.0",
    "glob": "^6.0.1",
    "parse5": "^2.1.0",
    "stylelint": "^3.1.3"
  }
```

It's worth noting that the `babel-eslint^4.1.6` requires `babel-core^5.8.33` as dependency.

After `npm install`, we can find that the `babel-core^5.8.33` hasn't been installed as nested node module in `babel-eslint`. If we type `npm ls --depth=0`, a warning **"missing: babel-core@^5.8.33, required by babel-eslint@4.1.6"** is raised up.

**Comment by benoitvallon** [comment]
Same problem here issue: https://github.com/npm/npm/issues/10985

```shell
npm ERR! missing: shebang-regex@^1.0.0, required by babel-core@6.3.26
npm ERR! missing: slash@^1.0.0, required by babel-core@6.3.26
npm ERR! missing: babel@^5.4.7, required by fbjs-scripts@0.4.0
```

**Comment by AgentME** [comment]
Just realized it's the same problem here too: https://github.com/npm/npm/issues/11200

**Comment by marcj** [comment]
Same here. Any ideas?

**Comment by AnimiVulpis** [comment]
I created a [minimal example repo](https://github.com/AnimiVulpis/npm-bug) on which a sub-dependency is missing on every clean install.

The missing dependency only occurs if `redux` is in **dependencies** and an incompatible version of `lodash` in **devDependencies**.

(no, a `npm cache clean` does not help 😉 )

Maybe this helps someone figure out why this is happening.

**Comment by pwalczyszyn** [comment]
I have similar problem.
Two solutions that worked for me:

1. Moved all `devDependencies` to `dependencies`.
2. Instead of running `npm install` I run `npm update`.

**Comment by schmod** [comment]
I've reproduced this on NPM v3.8.7.  It appears to have the same cause as #10727.

**Comment by zkat** [comment]
This is quite probably fixed as of npm@4.0.5 thanks to #12811. Cheers!

**Comment by benurb** [comment]
Thanks for the fix! Are you planning to backport it to npm 3 for node LTS?

**Comment by zkat** [comment]
@benurb we're very unlikely to bother backporting patches. Our LTS is meant to be a "good enough" thing that Node.js can distribute. I recommend just upgrading if you're attentive enough to care about your npm version. Breaking changes in `npm@4` are relatively low-impact.
