### ISSUE TITLE
npm binary removed when upgrade interrupted.

### ISSUE THREAD

**Issue by ruckuus** [npm/npm#11046]
I'd like to cancel npm upgrade after realizing that I needed different version of npm (not 3.0.0).

Expected: Interrupted upgrade should rollback to previous version.
```
ubuntu@ip-10-0-254-58:~$ npm -v
2.14.7
ubuntu@ip-10-0-254-58:~$ which npm
/home/ubuntu/.nvm/versions/node/v4.2.0/bin/npm
ubuntu@ip-10-0-254-58:~$ npm install -g npm@3.0.0
^C
ubuntu@ip-10-0-254-58:~$ npm -v
-bash: /home/ubuntu/.nvm/versions/node/v4.2.0/bin/npm: No such file or directory
ubuntu@ip-10-0-254-58:~$ nvm list
         v4.1.2
->       v4.2.0
         v4.2.2
node -> stable (-> v4.2.2) (default)
stable -> 4.2 (-> v4.2.2) (default)
iojs -> N/A (default)
```

**Comment by othiym23** [comment]
The team agrees that this would be a nice improvement, but we're not going to have time to work on it ourselves in the next 6-12 months, so I'm closing this. That said, if you want to implement this, you have our support.
