### ISSUE TITLE
Proposal: Allow for global packages in package.json

### ISSUE THREAD

**Issue by SetTrend** [npm/npm#11050]
The `package.json` definition currently seems to lack an option for storing the global packages required for developing the package.

I noticed this when I was forking the Microsoft/TypeScript#6342 package. I wasn't able to run a build because I was missing a global installation of `jakejs`.

So I propose to introduce a `globalDependencies` property. `npm install` may then install the packages globally listed in that property, if they have not been installed already.

**Comment by watilde** [comment]
Hi SetTrend,
I think it can fix by adding `"scripts": { "jake": "jake" }` in your `package.json` and run `npm run jake`.

See also: https://github.com/npm/npm/issues/8866

**Comment by SetTrend** [comment]
Unfortunately no: Because `"scripts": { "jake": "jake" }` doesn't actually *install* `jake`.

**Comment by watilde** [comment]
That's correct. You also need to install the package `npm install jake` then you can run it. I try to make an example: https://github.com/watilde/example-npm-11050

**Comment by SetTrend** [comment]
I comprehend.

Yet the issue actually focusses in having packages getting installed *globally* by `package.json`, not locally. That's because packages supposed to be globally installed are generally not `node` modules.

People at Microsoft/Typescript are probably going to argue that adding a task runner locally would be sub optimal.

And I'd like to add that the above example is only an example. Perhaps not the best one to visualize the use case.

**Comment by KenanY** [comment]
Is there a specific example of how `"globalDependencies"` would be better than the current practice of having `"devDependencies"` be added to `PATH` for execution via `"scripts"`?

**Comment by SetTrend** [comment]
One reason is that VS Code (and presumably Atom/Electron, too) [doesn't support to run scripts](https://github.com/Microsoft/vscode/issues/1771).

Another reason is that *node* projects often require the presence of globally installed packages (see Microsoft/TypeScript), and there is currently no way for these projects to define a requirement for these global packages in `package.json` enabling a collaborator to run/develop/deploy these projects without providing him with external information (e.g. README.md or GitHub Issues).

**Comment by watilde** [comment]
I just tried VS Code now and understood your use case now.

So In your use case, how about to add this `"command": "node_modules/.bin/jake"` in your tasks.json to use local command in `node_modules`? It worked and using command in your local modules is very nice to use same version with others and it can easy to sync the version when it need to update the version. If install globally is absolutely necessary, it also can do it with adding  `"preinstall": "npm i -g jake"` in your `package.json`. (Additionally, Atom can support npm run-script/gulp/etc with an apm package actually.)

**Comment by SetTrend** [comment]
Yes, yet these are both steps to do manually, requiring the collaborator to *know* that something like `jake` is required for the project.

I believe there is a requirement for the package to be self-contained. A package - as I see it - is supposed to give all the information that's necessary to run/build/deploy it. And `npm install` is supposed to resolve all these dependencies automatically - even the global ones.

I propose global install requirements to be contained in the `package.json` file and automatically be resolved with `npm install`. No `script` to execute. No manual intervention required.

**Comment by Delapouite** [comment]
Somehow related issue : https://github.com/npm/npm/issues/8177

**Comment by gpbl** [comment]
I don't like the idea of a package.json messing up with my globals. A package is self contained so it doesn't need global dependencies. Also, what should happen if another app requires a different version of the global package?

**Comment by othiym23** [comment]
@gpbl For those reasons, among others, this is a feature that, while periodically requested, doesn't make sense for npm. If a package needs a dependency, it should be depended upon and used locally, preferably via lifecycle of package scripts. Because this isn't something we're going to add, I'm going to close this feature request now, but @SetTrend, thanks for writing this up and making a case for it!

**Comment by SetTrend** [comment]
@gpbl As you write: That's a problem pertaining with packages in general. *If* a package *requires* a global package then it doen't make any difference on the machine whether the global package is mentioned in `package.json` or not: The global package *is* required.

So, indeed, there is no advantage in *not* saving this information in a `package.json` file. In both cases you only have one choice: Either install the package *including* the global packages - or leave it.

**Comment by gpbl** [comment]
@SetTrend I'm pretty sure this will eventually end with a misuse of global packages, downgrading the solidity of npm (e.g. I still see people not understanding the package's scripts lifecycle). Why do you think a note in the package's documentation is not OK? After all, you are not requiring an *npm* package installed globally, but an executable binary.

**Comment by SetTrend** [comment]
@gpbl That because a note in the package's documentation is not mandatory nor is it formalized. It can be anywhere and nowhere (as it currently is with many packages, just naming the Microsoft/TypeScript package as one popular example here).

I fully comprehend to the need to constrain installation of global packages. And I understand that these are mainly supposed to drive the build process rather than required to run the package.

So my proposal would include an amendment to the `npm` tool, too: Let global packages mentioned in a `package.json` file be only installed by adding the `-g` flag to the `install` command; i.e.: `npm install -g`.

Installation of global packages could be performed interactive. So if a package is already installed to a machine, the user may be prompted, asking him/her whether the existing global package should be updated/downdated.

So a full install of a package would then look like this: 'npm install -g'. This would install both, local and global packages. While `npm install` would only install local packages. That would be backward compatible, too.

**Comment by felixfbecker** [comment]
This is a bad idea. How would you do version constraints on this? You cant have two versions of the same package installed globally at the same time. Just add it to devDependencies, use npm scripts and/or define a tasks.json until VS Code adds this.

**Comment by SetTrend** [comment]
@felixfbecker : You are describing the current situation. My proposal doesn't change anything of that.

For global installs there are no version constraints by nature. There always is only one single version of a command line tool installed on your machine. This is how it's done now and this won't change with the proposal.

You will still be required to install the globals if you want to run the tools required to build a package from the command line. There is no way around that. Not today and not after implementing my proposal. My proposal just adds a natural, formal way of *declaring* which global packages are required to be able to handle the package to npm. That's all.

Again: Global packages required by a package are required by a package. With or without declaring the requirement in a `package.json` file. Arguing against this is arguing against using global packages - not arguing against having these requirements listed somewhere formally.

This thread is not about arguing against using global packages. And it's not about arguing about what to do if there will be two different versions of a global package required by two different packages.

Having global packages listed in a dedicated section in `package.json` tells the user in a formally clean way which command line tools are required to run the package. Using the suggested `npm install -g` the user can still decide whether he/she wants to install the global packages or not.

**Comment by felixfbecker** [comment]
@SetTrend What if module A needs Gulp 3.0 and module B needs Gulp 4.0? It just doesnt work.
 > You will still be required to install the globals if you want to run the tools required to build a package from the command line. There is no way around that. Not today and not after implementing my proposal.

That is simply not true. Command line tools are not limited to global installs. You can install them locally as a devDependency and their binaries will be in `node_modules/.bin`. You can link to them in VS Code by using a relative path or in npm scripts as if they were global.

**Comment by SetTrend** [comment]
The following paragraph is from the official [NPM documentation](https://docs.npmjs.com/getting-started/installing-npm-packages-locally):

>"If you want to depend on the package from your own module using something like Node.js' require, then you want to install locally, which is npm install's default behavior. On the other hand, *if you want to use it as a command line tool, something like the `grunt` CLI, then you want to install it globally.*"

So CLI commands like `gulp`, `grunt`, `jake` etc. are supposed to be installed *globally*. So, whenever a package either lists CLI scripts like a `gulpfile`, a `gruntfile` or a `jakefile`, then the corresponding `package.json` is supposed to list these corresponding dependencies and to make sure they are installed globally.

If you want to suggest to have CLI commands installed locally, then the best way to do that is to propose your alteration suggestion to the NPM team. But as long as the documented NPM workflow pertains valid, CLI commands are supposed to be installed globally.
<br/>
> What global packages does Microsoft/TypeScript require you to install?

In the case of Microsoft/TypeScript it's `jake` which apparently [hasn't been installed as expected](https://github.com/Microsoft/TypeScript/issues/6342). VS Code apparently couldn't run `jake` when being installed locally.

**Comment by felixfbecker** [comment]
That documentation is for package consumers (end users, who use npm), not package creators. The documentation under package.json is for package creators and provides a nice example for using CLI tools that are devDependencies: https://docs.npmjs.com/files/package.json#devdependencies
In the end, why would node_modules/.bin even exist if NPM wants you to "depend" on global CLI tools.
There is also documentation about best practices with npm scripts.
If VS Code uses global jake instead of local jake, it is an issue with VS Code.

I have the feeling this discussion is not going anywhere, so I'm gonna unsubscribe from this thread. Cheers

**Comment by evan-boissonnot** [comment]
Hi

I've got the same problem. I'm so sad to see your bad reaction felixfbecker.

And now, how we could manage global dependencies ? how someone could know global dependencies if some modules need to be installed with -g ?

It's not a vs code issue, even if i understand your point of view.
