### ISSUE TITLE
npm should work for mixed case packages

### ISSUE THREAD

**Issue by jandrieu** [npm/npm#11059]
For private packages that use camelCase, npm init fails.
```
Sorry, name can no longer contain capital letters.
```
However, that is not a limitation of node. I, like the vast majority of npm users, will never publish my private packages to npm. This limitation is more than frustrating.

I have to retype the default name in lower case (because I'm in a camelCase directory) then edit the resulting package.json to change the name to the one that makes sense for my application.

I understand--and appreciate--the distinction that publishing case-sensitive packages is problematic. But for private packages, camelCase is standard naming procedure. Class=>File=>Package all use camelCase as standard.

Please change this to just a warning.

Yes, I looked at #9671, #7269, and https://docs.npmjs.com/getting-started/using-a-package.json#requirements 

I get the issues. However, `npm init` for private packages vastly outnumbers its use for public packages. It would be great if supporting these use cases could be a higher priority.

**Comment by othiym23** [comment]
Making this change would complicate the validation logic for publishing (because only checking it on the server leads to misleading and frequently unhelpful error messages). It also fails to handle the case where today's private package, which lives only in a local repository, may become tomorrow's package published as a private package on the primary registry, or be published as a public package. Also, just supporting mixed-case names for legacy packages has led to very painful issues that affected large numbers of npm users, so I'm very wary of any changes that could lead to further problems around this. Finally, if npm has a bias, it's biased towards sharing. For all of these reasons, this is not a change I'm interested in making to the CLI.

> However, `npm init` for private packages vastly outnumbers its use for public packages. It would be great if supporting these use cases could be a higher priority.

I would be very interested to see evidence that this is the case, because it doesn't jibe with my own intuition, nor am I aware of any good sources of data to verify whether this is true.

**Comment by jandrieu** [comment]
Actually, I got the private package ratio from someone on the npm team at Node Conf Adventure 2015. My apologies I forget whom. I believe it was in the session where I brought up the need for an "UNLICENSED" license or similar capability (issue #8557) I recall the mention of a 10:1 (was it 100:1?) ratio of private to public packages--I believe from ```npm init```s that never get published.   That was seen as a huge opportunity, i.e., look at how MANY packages we *could* get published if only it were easier, better, etc. That's fair. But I saw it as demonstrating that npm is far more often used for private, unshared packages than for packages bound for use by others.

I understand the bias for sharing. That's the power of open source and it has made node & npm the "largest ecosystem of open source libraries in the world."  But mostly, I use npm and package.json to build and maintain a manifest for my own apps. ```npm init``` and ```npm install --save X``` I've personally done that for at least 50 little node apps over the last few years, not because I was building a "module" that could be reused, but just to keep track of dependencies of whatever I was working on.  Sometimes the packages only existed for an few hours as I tested out an approach to my problem.

In my current application, we break our code into dozens of small modules, each exposing a single class, all of which are custom-tailored with the logic needed for our app. One or two modules might be publishable out of that list, but the rest are proprietary. Today, the naming convention aligning Class->File->Directory->Package name link is broken with npm init.  There is no way we'll switch our class naming convention to all lower case. Nor am I going to switch to a monolithic package architecture. And I don't see the value in having the package name be the exception in the chain of naming. Which means I'm stuck hand editing all of the package.jsons to undo the fake name npm init will force me to use.

To add insult to injury, npm init currently suggests a default name that I can't even use because it  replicates the name of my directory, which is camelCase.

It would be great if npm init would stop limiting what I can do and make it easy to do what I want to do. It feels like the business case for the npm registry is devaluing the actual dominant use case for npm init. The latest changes certainly make ```npm init``` more annoying for me, without--yet--any benefit from publishing.

**Comment by othiym23** [comment]
> To add insult to injury, npm init currently suggests a default name that I can't even use because it replicates the name of my directory, which is camelCase.

Having the default value be converted from `camelCase` to all-lower-case `snake-case` would be a very useful small tweak to `init-package-json` that would benefit many users. If you wanted to put together a patch to do that, it would be merged relatively quickly.

As to the rest, it sounds like you might get value from writing your own [drop-in replacement](https://www.npmjs.com/package/promzard#usage) for the `promzard` interview script (configured via [`init-module`](https://docs.npmjs.com/misc/config#init-module). That will allow you to set whatever default values you like at package-creation time.

> It feels like the business case for the npm registry is devaluing the actual dominant use case for npm init. 

This is a UX decision that has little to do with the needs of npm, Inc. and much to do with preventing the creation of situations where users end up with broken installs. The registry can handle packages with mixed-case names fine. Case-folding filesystems can't.

**Comment by jandrieu** [comment]
Ok. I'll look into that.

Thing is, the developer running ```npm init``` knows--or should know--what their file system can handle.  Unless you are building for distribution, all you care about is making it work on your own system.

I expect the ratio of those who use ```npm init``` for local, private packages compared to those who will actually publish a package for others--via npm or a "private" registry--will essentially follow the 1% rule, https://en.wikipedia.org/wiki/1%25_rule_(Internet_culture)  The vast number of npm users will just use npm to install things, not to publish. 

I'm that 99%, and while I look forward to publishing something in the not-to-distant future, I expect the packages I publish to never reach more than 5% of the number of packages I create with npm init.

It seems hard for me to imagine how your intuition is that different. Do you see that the majority of ```npm init``` executions actually create a new package *that will get published*?  That's just so far from my own experience it is hard to grasp.  As I outlined earlier, I use npm to install my software and run ```npm init``` to make it easy to track dependencies. Not to publish. Maybe someone as prolific and efficient as substack publishes most of the packages he creates, but I find it hard to imagine that is true for even 10% of developers.

The current UX direction is making how I use npm more and more annoying. For example, forcing me to type UNLICENSED, to temporarily accept a package name I'm not going to use, and forcing me to edit the package.json after the fact to set "private":true.  I appreciate all of the arguments for each of these decisions. I do. I am also, here, raising the flag to draw attention to the trend and my resulting sense of dismissal for how I--and I believe most developers--use npm.

That said, of course, I'm not being "forced" to do anything. I could write my own npminitter that creates a JSON file, but kind of the whole point of the open source thing is that if the common tools works, we get the benefit without having to maintain it.  And I'm not keen on maintaining a init tool that needs to stay on top of changes with node and other tools.

I'll look into the wizard. Maybe that's all I really need.

**Comment by SCLeoX** [comment]
> Making this change would complicate the validation logic for publishing.

```javascript
if (/[A-Z]/.test(name)) throw new Error('Oops, you can\'t have uppercase letters in your package name')
```

Of course it will greatly "complicate the validation logic for publishing".

I am more concerned that my package name won't show up in my shell if I have uppercase letters in them. To me, it seems absolutely ridiculous to ban uppercase letters.
