### ISSUE TITLE
Try to execute npm start but all the time ERR!

### ISSUE THREAD

**Issue by MiguelMB** [npm/npm#11058]
I install al the stuff of this page web 
https://docs.angularjs.org/tutorial/index#get-started
but when I execute 
 
```
npm start
```

the answer is 

```
 npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12

npm ERR! missing script: start
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\J\myApp\npm-debug.log
```

And the file npm-debug.log is 
----------------------------------------------
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.3.12
3 info using node@v5.3.0
4 verbose stack Error: missing script: start
4 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:147:19)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:57:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:345:5
4 verbose stack     at checkBinReferences_ (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:309:45)
4 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:343:3)
4 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:113:5)
4 verbose stack     at ReadFileContext.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:284:20)
4 verbose stack     at ReadFileContext.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:76:16)
4 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:324:13)
5 verbose cwd C:\Users\J\myApp
6 error Windows_NT 6.1.7601
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
8 error node v5.3.0
9 error npm  v3.3.12
10 error missing script: start
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```

I continued to try to find the soluction , 
Thanks for read 

Miguel

**Comment by KenanY** [comment]
@MiguelMB Did you `cd` into the `angular-phonecat` directory as that tutorial instructs?

**Comment by MiguelMB** [comment]
Yes @KenanY , but now say this :+1: C:\Users\J\Documents\GitHub\angular-phonecat [master]> npm install
npm WARN install Couldn't install optional dependency: Unsupported

> bufferutil@1.2.1 install C:\Users\J\Documents\GitHub\angular-phonecat\node_mod
ules\bufferutil
> node-gyp rebuild


C:\Users\J\Documents\GitHub\angular-phonecat\node_modules\bufferutil>if not defi
ned npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node
-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  re
build )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\nod
e_modules\node-gyp\lib\configure.js:116:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\configure.js:71:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\J\Documents\GitHub\angular-phonecat\node_modules\bufferuti
l
gyp ERR! node -v v5.3.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN install:bufferutil@1.2.1 bufferutil@1.2.1 install: `node-gyp rebuild`
npm WARN install:bufferutil@1.2.1 Exit status 1

> utf-8-validate@1.2.1 install C:\Users\J\Documents\GitHub\angular-phonecat\node
_modules\utf-8-validate
> node-gyp rebuild


C:\Users\J\Documents\GitHub\angular-phonecat\node_modules\utf-8-validate>if not
defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\
node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node
  rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\nod
e_modules\node-gyp\lib\configure.js:116:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\configure.js:71:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\J\Documents\GitHub\angular-phonecat\node_modules\utf-8-val
idate
gyp ERR! node -v v5.3.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN install:utf-8-validate@1.2.1 utf-8-validate@1.2.1 install: `node-gyp re
build`
npm WARN install:utf-8-validate@1.2.1 Exit status 1

> angular-phonecat@0.0.0 postinstall C:\Users\J\Documents\GitHub\angular-phoneca
t
> bower install

C:\Users\J\Documents\GitHub\angular-phonecat [master]>
maybe I need to downgreading the version , I try tomorrow , thank for the help :)

**Comment by KenanY** [comment]
@MiguelMB See the error message:

```
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
```

Be sure to read [the dependencies](https://github.com/nodejs/node-gyp#installation) of `node-gyp`. You need python installed.

**Comment by MiguelMB** [comment]
Thanks @KenanY , I need to install python but python with less version that the new version of python
