### ISSUE TITLE
npm i parse-git-log --save error in windows

### ISSUE THREAD

**Issue by manjudr** [npm/npm#11064]
i tried to install " npm i parse-git-log --save " its throwing an errors like refusing an install  parse-git-log as a dependency of itself

**Comment by KenanY** [comment]
@manjudr Sounds like you are already in a directory that contains `parse-git-log`. Does the `package.json` in your current working directory have a `"name"` attribute of `"parse-git-log"`?

**Comment by KenanY** [comment]
@manjudr Hi! It has been a few months since my response and I was just wondering if you are still seeing this issue?

**Comment by manjudr** [comment]
Sorry for the late response ..
Now that problem is resolved from ur sol .
Thanks a lot .

**Comment by KenanY** [comment]
Closing as resolved.
