### ISSUE TITLE
Could i config the way NPM create command soft link to '/usr/bin/' rather than '/usr/local/bin/'？

### ISSUE THREAD

**Issue by jkiss** [npm/npm#11063]
For some reason, when i use npm install some package, it will create command soft link into ***'/usr/local/bin/'***, But when i run it in ***'sudo'***, it will throw an error ***'Command not found'***, so if there some way that i can change it? thx!!!

**Comment by jkiss** [comment]
I think there should be a continue way rather than use ***'ln -s'*** to create manually...

**Comment by iarna** [comment]
You can control this with the `prefix` configuration item. You may find this discussion here helpful:

https://docs.npmjs.com/getting-started/fixing-npm-permissions

Does this answer your question?

**Comment by jkiss** [comment]
But, i don't want to change package ***installing path***, i just want change where ***command soft link*** created. So that i can run it in ***root identity***. You know, when running command as root, the ***PATH*** will be changed, it will not include ***'/usr/local/bin'***
![default](https://cloud.githubusercontent.com/assets/3231326/12189509/67301d8c-b5f9-11e5-861a-4c003a9fc843.PNG)
If it depend on the package execute statement, not NPM?

**Comment by iarna** [comment]
Oh, I understand much better now, thank you for the clarification.

The place that commands are linked is determined by where packages are installed, and can't be changed separately.

You _can_ change root's path to include `/usr/local/bin` or whatever path you would prefer, by adding a section to your sudoers like:

```
Defaults    secure_path=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin
```

Regardless, this isn't something npm is likely to support directly itself.
