### ISSUE TITLE
Npm moving modules up the hierarchy when installing single modules

### ISSUE THREAD

**Issue by fresheneesz** [npm/npm#11060]
I'm noticing that if I install a new version of do an `npm install some-module@whatever` and it uses a module already installed at the top-level of node_modules, npm can move that top-level module into the inner node_modules of the module being installed, even tho a package.json requires it at the top level. 

Repro steps:

Create an empty directory and add this package.json:
```
{
    "name": "whatever",
    "version": "0.1.0",
    "dependencies": {

        "cpr":"0.4.2",
        "graceful-fs":"*"
    }
}
```

Do an `npm install`, then do an `npm install cpr@1.0.0`. The `graceful-fs` module will be moved from the top-level into `node_modules/cpr/node_modules/graceful-fs`.  This makes no sense and is breaking our dev installation process. Please fix this. I'm using npm 3.3.12 in a linux centos environment.

**Comment by fresheneesz** [comment]
The same thing happens if, instead of installing `cpr@1.0.0`, you change cpr in the package.json to 1.0.0 and then run `npm update`

**Comment by iarna** [comment]
This is fixed the current version of npm (your example above doesn't reproduce with it, and we definitely fixed some bugs that sound a lot like this).  Please give it a try with:

```
npm install -g npm@latest
```

**Comment by fresheneesz** [comment]
Tested with npm v3.5.2 and seems to be fixed. Thanks!
