### ISSUE TITLE
Website does not show the latest published package.

### ISSUE THREAD

**Issue by MrSwitch** [npm/npm#11073]
Intitial npm publish failed with 401 see https://travis-ci.org/MrSwitch/hello.js/builds/100689857#L517

> npm ERR! You must be logged in to publish packages : hellojs

I fixed this by updating my travis properties.

Then second fime it failed with 403 https://travis-ci.org/MrSwitch/hello.js/builds/100787738#L505

> npm ERR! "You cannot publish over the previously published version 1.10.0." : hellojs

I've never published/unpublished this version before (https://github.com/npm/npm/issues/10886#issuecomment-165946445). This version is not visible through "npm install hello@1.10.0" or shown in the sidebar at https://www.npmjs.com/package/hellojs

**Comment by KenanY** [comment]
@MrSwitch Umm, actually, it has been published before:

``` sh
$ npm info hellojs time
{ modified: '2016-01-07T10:00:07.545Z',
  created: '2014-04-06T10:07:33.010Z',
  '0.1.5': '2014-04-06T10:07:33.010Z',
  '0.1.6': '2014-04-06T11:04:48.985Z',
  '0.2.0': '2014-04-06T13:52:24.667Z',
  '0.2.1': '2014-04-07T09:42:54.887Z',
  '0.2.2': '2014-05-14T15:15:06.100Z',
  '0.2.3': '2014-05-14T15:20:44.960Z',
  '0.2.4': '2014-05-16T14:51:11.403Z',
  '0.2.5': '2014-05-17T14:40:31.437Z',
  '1.0.0': '2014-09-02T13:16:07.534Z',
  '1.1.3': '2014-09-19T07:55:09.314Z',
  '1.3.2': '2014-12-08T07:12:37.123Z',
  '1.3.7': '2014-12-17T13:09:35.085Z',
  '1.4.0': '2015-01-07T18:31:55.290Z',
  '1.4.1': '2015-01-14T16:51:46.832Z',
  '1.4.2': '2015-02-13T12:05:00.507Z',
  '1.4.3': '2015-02-13T12:48:13.311Z',
  '1.5.0': '2015-02-28T04:35:42.129Z',
  '1.5.1': '2015-04-04T04:57:30.139Z',
  '1.6.0': '2015-05-16T08:08:06.627Z',
  '1.7.0': '2015-07-02T17:10:06.746Z',
  '1.7.3': '2015-07-09T11:40:50.369Z',
  '1.7.4': '2015-07-09T15:43:34.188Z',
  '1.7.5': '2015-07-09T21:14:32.150Z',
  '1.8.2': '2015-08-28T17:15:51.449Z',
  '1.8.3': '2015-09-18T21:39:13.355Z',
  '1.8.4': '2015-09-18T21:43:52.945Z',
  '1.9.3': '2015-10-03T14:51:24.868Z',
  '1.9.4': '2015-10-05T08:42:44.979Z',
  '1.9.5': '2015-10-15T20:14:51.528Z',
  '1.9.6': '2015-10-16T19:40:45.578Z',
  '1.9.7': '2015-11-08T10:25:05.666Z',
  '1.9.8': '2015-11-11T17:21:19.450Z',
  '1.9.9': '2015-12-19T00:17:09.157Z',
  '1.10.0': '2016-01-07T10:00:07.545Z' }
```

**Comment by MrSwitch** [comment]
Update: I can install it via `npm install hellojs@1.10.0`

The website https://www.npmjs.com/package/hellojs still says @1.9.9

**Comment by KenanY** [comment]
@MrSwitch So, is this issue about the website now?

**Comment by MrSwitch** [comment]
@KenanY yes very sorry, title changed.

**Comment by iarna** [comment]
I opened https://github.com/npm/newww/issues/1729 to get the right eyes on this. I'm going to close this here so discussion can happen in just one place.

**Comment by MrSwitch** [comment]
@iarna thanks
