### ISSUE TITLE
npm publish with prerelease metadata briefly shows incorrect version in terminal

### ISSUE THREAD

**Issue by sandfox** [npm/npm#11072]
node: v4.1.1
npm: 3.5.2

Hopefully the picture below self explanatory enough but here is the general gist:
1. I have made a package with the version string `"0.0.13-alpha.2"`
2. I run `npm publish`
3. during the upload the terminal prints a package/version string of `agent-jones@0.0.1`
4. once upload completes it shows the correct string package/version of `agent-jones@0.0.13-alpha.2`

```
$ less package.json | grep version
  "version": "0.0.13-alpha.2",
$ npm publish
publish:agent-jones@0.0.1 ▌ ╢░░░░░░░░░░░░░░░░╟
## The line above is then replaced by the line below once publishing succeeds
+ agent-jones@0.0.13-alpha.2
```

(screenshot is taking during upload/publish)
<img width="563" alt="screen shot 2016-01-07 at 17 17 21" src="https://cloud.githubusercontent.com/assets/260919/12177319/63f9b484-b563-11e5-8a22-585f49470d58.png">

**Comment by mikesherov** [comment]
Thanks for contributing! This seems like it's a clipping issue. I think npm's progress bar only outputs 25 of the current action being taken before rendering the actual progress bar.

**Comment by sandfox** [comment]
Ah-ha that would make a bit of sense. Would it be worth showing some form of truncation indicator (e.g `...`) ?

**Comment by iarna** [comment]
Yeah, that's the case. My plan right now is to swap the progress bar for the message, so the progress bar will be limited length and the message can grow to its heart's content.

**Comment by mikesherov** [comment]
@iarna how does that work for progress bars like install which need to display multiple messages of variable length?
