### ISSUE TITLE
Allow to reference package.json metadata in scripts section

### ISSUE THREAD

**Issue by bpasero** [npm/npm#11074]
My use case is that from a package.json I would like to define a "scripts" script that puts metadata from the package.json as argument to the script. Imagine a package.json like this:

```json
{
	"name": "something",
	"scripts": {
		"preinstall": "node bin/script -arg %name%"
	}
}
```

I would like to pass the value of "name" to the preinstall script.

**Comment by bpasero** [comment]
Alternatively it would also be cool if the meta data of my package.json was automatically set as environment to the script I am executing.

**Comment by othiym23** [comment]
Good news! Everything in the current `package.json` is set as an environment variable prefixed with `npm_package_`. You can get a dump of everything that will be set in the current context when scripts are run with `npm run env`.

Closing as resolved.

**Comment by bpasero** [comment]
Awesome! Even in npm 2.x?

**Comment by othiym23** [comment]
Yep! That dates back to sometime early in `npm@1` (at the very least, it precedes me joining the project).

**Comment by bpasero** [comment]
Excellent

**Comment by bpasero** [comment]
@othiym23 works nicely. It is also possible to override a specific value from the package.json through the command line?
