### ISSUE TITLE
npm test assumes unicode

### ISSUE THREAD

**Issue by gagern** [npm/npm#11086]
On my system, unicode support is not correctly detected out of the box due to https://github.com/iarna/has-unicode/issues/2. As a consequence, my tests list trees using ASCII data, and several tests fail because of this. I think the testing framework should not depend on the environment, but should either configure npm for predictable unicode setting or accept both possible renderings. Considering how some users may have trouble reading diffs involving unicode, it might be best to transform all tests to disabled unicode, and apply that setting consistently.

**Comment by iarna** [comment]
Ah, yes, thank you! We definitely want to take that PR.
