### ISSUE TITLE
Cannot find module 'npmlog' after upgrading to NodeJS 5.4.0 on debian

### ISSUE THREAD

**Issue by genesem** [npm/npm#11084]
Debian 8, I've updated nodejs to version 5.4 from 5.3 with apt and then run `npm update -g`, it also updated npm to 3.5.3 
And now I'm getting this error with any npm command:

```
me@TX:~# npm --version
module.js:328
    throw err;
    ^

Error: Cannot find module 'npmlog'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at /usr/lib/node_modules/npm/bin/npm-cli.js:20:13
    at Object.<anonymous> (/usr/lib/node_modules/npm/bin/npm-cli.js:76:3)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
```

**Comment by genesem** [comment]
just fixed it with:  `curl -L https://www.npmjs.org/install.sh | sh`

but now having:
---------
root@TX:~# npm update -g
`npm ERR! addLocal Could not install /tmp/npm.5903/package`
Б√▄ Б•╒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Бroot@TX:~#

**Comment by genesem** [comment]
running `npm install -g ` solved this too.

sorry for inconviniences..

**Comment by genesem** [comment]
Just updated node to 5.4.1 via apt-get 
got installed bundled version of npm (old).

After running 'npm update -g' got same error:

me@TX:~# npm --version
module.js:328
throw err;
^

Error: Cannot find module 'npmlog'



*It's definitely bad behavior.*

**Comment by genesem** [comment]
And this in additions:

@TX:~# *npm install -g*
Б√└ Б•╒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Бnpm ERR! addLocal Could not install /root
Б√░ Б•╒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒БrunTopLevelLifecycles     Б√▄ Б•╒Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√▒Б√npm ERR! Linux 3.16.0-4-686-pae
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g"
npm ERR! node v5.4.1
npm ERR! npm  v3.5.3
npm ERR! code EISDIR
npm ERR! errno -21
npm ERR! syscall read

**Comment by genesem** [comment]
full log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'install', '-g' ]
2 info using npm@3.5.3
3 info using node@v5.4.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData .
8 silly fetchOtherPackageData .
9 silly cache add args [ '.', null ]
10 verbose cache add spec .
11 silly cache add parsed spec Result {
11 silly cache add   raw: '.',
11 silly cache add   scope: null,
11 silly cache add   name: null,
11 silly cache add   rawSpec: '.',
11 silly cache add   spec: '/root',
11 silly cache add   type: 'local' }
12 error addLocal Could not install /root
13 silly fetchPackageMetaData Error: EISDIR: illegal operation on a directory, read
13 silly fetchPackageMetaData     at Error (native)
13 silly fetchPackageMetaData  error for . { [Error: EISDIR: illegal operation on a directory, read] errno: -21, code: 'EISDIR', syscall: 'read' }
14 silly rollbackFailedOptional Starting
15 silly rollbackFailedOptional Finishing
16 silly runTopLevelLifecycles Starting
17 silly runTopLevelLifecycles Finishing
18 silly install printInstalled
19 verbose stack Error: EISDIR: illegal operation on a directory, read
19 verbose stack     at Error (native)
20 verbose cwd /root
21 error Linux 3.16.0-4-686-pae
22 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g"
23 error node v5.4.1
24 error npm  v3.5.3
25 error code EISDIR
26 error errno -21
27 error syscall read
28 error eisdir EISDIR: illegal operation on a directory, read
29 error eisdir This is most likely not a problem with npm itself
29 error eisdir and is related to npm not being able to find a package.json in
29 error eisdir a package you are trying to install.
30 verbose exit [ -21, true ]
```

**Comment by genesem** [comment]
this second time `npm install -g npm@npm3.5.3`  solved issue but I believe next node.js update will broke verything again.

**Comment by myitcv** [comment]
Similar issues here. With a clean install (from downloaded binaries, `Linux 4.2.0-23-generic x86_64`) of `Node 5.4.1`:

```
$ node --version
v5.4.1
$ npm --version
3.3.12
$ npm install -g npm@3.5.4
....
$ npm --version
module.js:327
    throw err;
    ^

Error: Cannot find module 'npmlog'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /home/myitcv/nodes/lib/node_modules/npm/bin/npm-cli.js:20:13
    at Object.<anonymous> (/home/myitcv/nodes/lib/node_modules/npm/bin/npm-cli.js:76:3)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
```

Incidentally, installing `npm 3.5.3` works without issue on a fresh install of `Node 5.4.1`. As does installing `npm 3.5.3` followed by `npm 3.5.4`

**Comment by burakson** [comment]
:+1: 
Incidentally, installing npm 3.5.3 works without issue on a fresh install of Node 5.4.1. As does installing npm 3.5.3 followed by npm 3.5.4
