### ISSUE TITLE
Error while installing cordova

### ISSUE THREAD

**Issue by vibschits** [npm/npm#11098]
Can anybody help to understand whats missing? attached is debug file.

[npm-debug.txt](https://github.com/npm/npm/files/83627/npm-debug.txt)

**Comment by ashleygwilliams** [comment]
hi! this error is seen often with windows users. can you try `npm set registry https://registry.npmjs.org/`, then try to install ionic again?

**Comment by ashleygwilliams** [comment]
hi! it has been a week since there was motion on this so i am going to close, please open a new issue if you continue to have trouble!
