### ISSUE TITLE
Cannont find module 'mongodb'

### ISSUE THREAD

**Issue by SandeshBhandari** [npm/npm#11102]
I tried using both *npm install monogdb* and creating a package.json file and then using *npm install*. But when I try to run the js file it still says cannot find the module 'mongodb'.
<img width="580" alt="screen shot 2016-01-09 at 2 56 13 pm" src="https://cloud.githubusercontent.com/assets/9206214/12218050/2f4b5740-b6e1-11e5-81e1-8ded58575000.png">

**Comment by KenanY** [comment]
@SandeshBhandari From the screenshot I see that there is a typo in "mongodb". Do you see it too?

**Comment by SandeshBhandari** [comment]
Oh!! Now I see it. Stupid mistake on my part. Thank you very much..
