### ISSUE TITLE
Install Node.js on Windows 10 Failed

### ISSUE THREAD

**Issue by bob1457** [npm/npm#11109]
I am trying to install node.js on Windows 10, which is a virtual machine on VMWare 11.0. I got error saying: Failed to open XML file: ...\node_etw_provider.man, system error: -2147024703. I tried version 4.2.4, 5.4.0 both 32bit and 64bit. (My machine is 64bit).

I was running install as my account in Administrators group on Windows 10. I had no problem on other physical machines running Windows 10 to install node.js.

Thanks.

Bob

**Comment by KenanY** [comment]
@bob1457 Hmm this does not look like an issue with `npm` to me.

**Comment by bob1457** [comment]
Thanks anyway. I got it resolved. I close it.

**Comment by Sunny-guangge** [comment]
how to resolved ?
