### ISSUE TITLE
Angular2 application install & run via package.json possible?

### ISSUE THREAD

**Issue by srisree** [npm/npm#11114]
Hi-My question is related to this question that was asked 4 days ago: (URL#1) How to start Angular2 project with minimum of required files using npm?

I use the same package.json that was mentioned in the above URL and I am doing the same project. I get the following errors, for which I think the solution is: (URL#2) https://github.com/npm/npm/issues/8048

However, I want confirmation from someone that I have identified correctly what the problem is that is causing these errors. I am in the process of implementing the suggestions in #URL2 to see if my problem vanishes. I am trying this out (i.e "npm start" command) both on Windows 7 & Windows 10 & getting error in both OS.

For your benefit here is the detailed list of errors: 
```
error Windows_NT 6.1.7601 
error argv "C:\Program Files\nodejs\node.exe" "C:\Users\dev4\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "start" 
error npm v3.5.3 
error code ELIFECYCLE 
error angular2-quickstart@1.0.0 start: concurrent "npm run tsc:w" "npm run lite" 
error Exit status 1 
error Failed at the angular2-quickstart@1.0.0 start script 'concurrent "npm run tsc:w" "npm run lite" '. 
error Make sure you have the latest version of node.js and npm installed. 
error If you do, this is most likely a problem with the angular2-quickstart package, 
error not with npm itself. 
error Tell the author that this fails on your system: error concurrent "npm run tsc:w" "npm run lite" 
error You can get information on how to open an issue for this project with: 
error npm bugs angular2-quickstart 
error Or if that isn't available, you can get their info via: error npm owner ls angular2-quickstart 
error There is likely additional logging output above. verbose exit [ 1, true ]
```

Thank you for your time.

-Srikanth

**Comment by iarna** [comment]
Given the error above, I think you would be best served taking this question to the folks who put together the instructions you're following?

The command in the `start` section of your `package.json` is returning an error, though nothing in your error messages report what. You could try running the command by hand from the same place you ran `npm start`:

```concurrent "npm run tsc:w" "npm run lite"```

If that still doesn't get you specific error messages, you could try running the two commands passed to `concurrent` by hand:
```
npm run tsc:w
npm run lite
```

If further investigations lead you back to problems with npm, please feel free to open a new issue.
