### ISSUE TITLE
npm shrinkwrap results in ECONNRESET errors with 3rd Party Registry

### ISSUE THREAD

**Issue by simonua** [npm/npm#11117]
My apologies for this being vague and for not being able to provide proper STRs since this involves a private 3rd party npm registry, Inedo's ProGet. The Inedo team believes below issue may lie with npm, which is why I'm posting here. Any help and insights from the npm team would be appreciated. 

This issue is also posted on [SO](http://stackoverflow.com/questions/34665513/econnreset-errors-when-using-npm-shrinkwrap-via-proget) and the [Inedo Support Forum](http://inedo.com/support/questions/4109).

-----

We are seeing ECONNRESET issues when using a shrinkwrapped package installed through our internal ProGet server. When configuring npm registry to be the regular npm registry and shrinkwrapping a package based on that, everything installs fine. We delete node_modules and execute npm cache clean in between runs to ensure we force downloads from ProGet. Interestingly, all 1,000+ resource requests that are listed in npm-shrinkwrap.json download correctly when plugged into a file downloader.

When installing with the verbose flag, we see a number of 404s where the npm client appears to arbitrarily alter the registry url from http://<internal-url>/npm/npm to omit npm/npm for some requests, but we don't know why that occurs or whether it relates.

We use ProGet 3.8.6 (latest), npm 3.3.11, 3.5.3, and 3.5.4 (testing on several developer machines with the same results), and node 4.2.1, 4.2.3.

**Comment by iarna** [comment]
My suspicion is that ECONNRESET is probably a symptom of your registry getting overloaded– the biggest difference between npm and a download manager is that npm doesn't throttle the number of simultaneous downloads.  This is a feature that we would like to add– we have plans to approach this in the future.

As for the 404s, that is concerning, but without a log file I can't really comment. If you could produce a log with your host info redacted, we would be happy to look at it and see if the 404s are expected or the symptom of something problematic. For this sort of log file to be most useful, producing it with `--loglevel=silly` would be ideal, though the file will be huge.

I'm going to close this issue, but if you do put together a log file you can share, please open a new issue with it and we'll dig in further.

**Comment by simonua** [comment]
@iarna Thank you very much for the response. I'll give this a try and may open a new ticket referencing this one one and a log. 

Appreciate all you guys do!

**Comment by simonua** [comment]
Linking to new follow-up issue [11125](https://github.com/npm/npm/issues/11125).
