### ISSUE TITLE
I successfully installed node-red as a global module in intel galileo gen2.After installing node-red ,i tried installing the node-red-contrib-gpio,but its showing error

### ISSUE THREAD

**Issue by Pattrickps** [npm/npm#11116]
```
root@galileo:~/node_modules/node-red# npm install node-red-contrib-gpio
loadDep:xtend -> afterAdd / |##############-----------------------------------|
npm ERR! Linux 3.8.7-yocto-standard
npm ERR! argv "node" "/usr/bin/npm" "install" "node-red-contrib-gpio"
npm ERR! node v0.10.38
npm ERR! npm  v3.5.3
npm ERR! Cannot read property 'target' of nullnpm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Please include the following file with any support request:
npm ERR!     /home/root/node_modules/node-red/npm-debug.log
```

**Comment by iarna** [comment]
Hi there, thank you for reporting this! Can you share the contents of `/home/root/node_modules/node-red/npm-debug.log`? That has all the info we need to track down the source of this error.

**Comment by Pattrickps** [comment]
hi,thanks for the reply,but there's no such file names npm-debug.log

root@galileo:~# cd /home/root/node_modules/node-red
root@galileo:~/node_modules/node-red# ls
CONTRIBUTING.md  bin      node_modules  public  settings.js
LICENSE          editor   nodes         red
README.md        locales  package.json  red.js
root@galileo:~/node_modules/node-red# cd npm-debug.log
-sh: cd: npm-debug.log: No such file or directory

**Comment by iarna** [comment]
Hi there, could you try again with the current npm, we have reason to believe this might be fixed now. You can get the most recent version of npm with `npm install -g npm@next`.
