### ISSUE TITLE
npm install is failing for grunt installation

### ISSUE THREAD

**Issue by cade-galt-1** [npm/npm#11126]
Trying to install grunt globally.  I installed the grunt-cli globally and installed grunt globally which appeared to copy package.json and Gruntfile.js to this directory were I ran:

```
sudo npm install
```

Here is the debug file and package.son.

[npm-debug.txt](https://github.com/npm/npm/files/87869/npm-debug.txt)

Here is my package.json file:

```
{
  "_args": [
    [
      ".",
      ""
    ]
  ],
  "_from": "../../Users/a/root/config/grunt",
  "_id": "Grunt@0.1.0",
  "_inCache": true,
  "_installable": true,
  "_location": "/Grunt",
  "_phantomChildren": {},
  "_requested": {
    "name": null,
    "raw": ".",
    "rawSpec": ".",
    "scope": null,
    "spec": "/Users/a/root/config/grunt",
    "type": "directory"
  },
  "_requiredBy": [
    "#USER"
  ],
  "_resolved": "file:../../Users/a/root/config/grunt",
  "_shasum": "7d36360e586389591377f0fe521b18bb9c73d230",
  "_shrinkwrap": null,
  "_spec": ".",
  "_where": "",
  "author": {
    "name": "CA"
  },
  "dependencies": {},
  "devDependencies": {
    "grunt": "0.4.0",
    "grunt-contrib-uglify": "*",
    "grunt-contrib-watch": "*",
    "grunt-jslint": "*",
    "matchdep": "*"
  },
  "name": "Grunt",
  "optionalDependencies": {},
  "private": true,
  "readme": "ERROR: No README data found!",
  "version": "0.1.0"
}
```

**Comment by iarna** [comment]
Ok, let me see if I understand:

1. You want to install grunt globally.
2. To achieve this, it looks like you created a directory named `Grunt` in `/usr/local/lib/node_modules` and then ran `npm install` in it.

This is not going to achieve what you want. I recommend doing the following:

1. Make sure you aren't in the `Grunt` folder you made earlier: `cd ~`
2. Remove the existing `Grunt` folder you made: `rm -r /usr/local/lib/node_modules/Grunt`
3. Run `npm install -g grunt` to install grunt globally.

I'm going to close this issue, but if you run into new errors please don't hesitate to open a new issue.

**Comment by cade-galt-1** [comment]
Hi, I found that you are not supposed to install grunt globally.  It was doing all kinds of weird things like creating a directory and copying files into it.  I updated my question to make note of the link saying not to install grunt globally.
