### ISSUE TITLE
Option to install dependencies from directory

### ISSUE THREAD

**Issue by CWood1** [npm/npm#11124]
When attempting to install a package from a local directory/tgz, NPM will still happily request it's dependencies from the remote registry. Is it possible to add a --local-registry=~/path/to/local/registry option?

Rationale: I'm behind a firewall that steadfastly refuses to allow NPM to access the Internet. I can, however, download packages separately. Individually, at the bottom of the dependency tree, NPM can install these. Above that, nope.

I tried manually adding all of these into the cache, and then installing with --cache-min=Infinity, and still got an ETIMEDOUT error; is there a workaround I can use in the meantime, to get the packages installing from the local directory?

**Comment by othiym23** [comment]
Aside from using `--cache-min=Infinity`, which will only work if a package is already in your local cache, there isn't a general-purpose way to use a chunk of your filesystem as a registry, no. (The problem with adding packages to the cache by hand is that there's HTTP metadata along with the package metadata that npm will try to populate if it doesn't exist, and that's more or less impossible to create by hand.)

However, you can use [`npm_lazy`](https://www.npmjs.com/package/npm_lazy) or some other form of caching proxy, and add the packages to the mirror's database by hand. _Or_ you can see if your company is interested in using an on-premise proxy that supports whitelisting, which would give the IT team control over what gets downloaded, like [npm On-Site](https://www.npmjs.com/onsite) (among many others).

You can work around this by using [local dependencies](https://docs.npmjs.com/files/package.json#local-paths) in `package.json`, but that's not going to work very well for packages you need to share or deploy.

Good luck finding a solution that works for you, and I'm going to close this as being as resolved as it's likely to get for now. Thanks for your time!
