### ISSUE TITLE
No compatible version found: lodash._stack@^3.0.0

### ISSUE THREAD

**Issue by tomquas** [npm/npm#11133]
> npm install
npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/Cellar/node/4.2.1/bin/node" "/Users/tom/.npm/bin/npm" "install"
npm ERR! node v4.2.1
npm ERR! npm  v3.5.3

npm ERR! No compatible version found: lodash._stack@^3.0.0
npm ERR! Valid install targets:
npm ERR! 4.0.0

[npm-debug.log.txt](https://github.com/npm/npm/files/88926/npm-debug.log.txt)

**Comment by tomltd** [comment]
This started to happen to me with my travis build this morning. It was fine then started to do the same thing...

npm ERR! notarget No compatible version found: lodash._stack@'>=3.0.0 <4.0.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["4.0.0"]

**Comment by chimurai** [comment]
Got the same issue:
```
[ERROR] npm ERR! node v5.4.1
[ERROR] npm ERR! npm  v3.5.4
[ERROR] 
[ERROR] npm ERR! No compatible version found: lodash.keys@^4.0.0
[ERROR] npm ERR! Valid install targets:
[ERROR] npm ERR! 3.1.2, 3.1.1, 3.1.0, 3.0.7, 3.0.6, 3.0.5, 3.0.4, 3.0.3, 3.0.2, 3.0.1, 3.0.0, 2.4.1, 2.4.0, 2.3.0, 2.2.1, 2.2.0, 2.1.0, 2.0.0
```

Think it has to do with the release of lodash v4.0.0:
https://www.npmjs.com/package/lodash

**Comment by franksama** [comment]
Getting same error

```
npm ERR! notarget No compatible version found: lodash._stack@'>=3.0.0 <4.0.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["4.0.0"]
npm ERR! notarget 
```

**Comment by david0178418** [comment]
Ditto here on @franksama's error.

**Comment by KenanY** [comment]
From https://github.com/lodash/lodash/issues/1760 can we say that this is not an issue with `npm`? Can someone please expand on how this is an issue with `npm` and not an issue with certain versions of `lodash` modules simply not existing in the registry?

**Comment by tomquas** [comment]
yes, kenan, i agree with you – not an npm issue. sorry.

**Comment by jdalton** [comment]
The lodash issue should be resolved.
