### ISSUE TITLE
"npm" in command line...

### ISSUE THREAD

**Issue by sestspectrum** [npm/npm#11132]
Wrote me - "invalid package.json."

This file: npm-debug.log.

0 info it worked if it ends with ok
1 verbose cli [ '/home/oleg634/local/bin/node',
1 verbose cli   '/home/oleg634/local/bin/npm',
1 verbose cli   'v' ]
2 info using npm@3.5.1
3 info using node@v5.1.1
4 verbose config Skipping project config: /home/oleg634/.npmrc. (matches userconfig)
5 verbose stack Error: Invalid package.json
5 verbose stack     at /home/oleg634/local/lib/node_modules/npm/lib/view.js:81:30
5 verbose stack     at ReadFileContext.<anonymous> (/home/oleg634/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:79:21)
5 verbose stack     at ReadFileContext.callback (/home/oleg634/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:76:16)
5 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:324:13)
6 verbose cwd /home/oleg634
7 error Linux 3.19.0-28-generic
8 error argv "/home/oleg634/local/bin/node" "/home/oleg634/local/bin/npm" "v"
9 error node v5.1.1
10 error npm  v3.5.1
11 error Invalid package.json
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@sestspectrum What are you expecting to happen when you run `npm v` from your home directory?

**Comment by sestspectrum** [comment]
Thanks! A problem is done!

**Comment by sestspectrum** [comment]
"problem"
