### ISSUE TITLE
Contributing to docs: what does the (#) mean after a "See Also" doc reference 

### ISSUE THREAD

**Issue by kevinSuttle** [npm/npm#11136]
Example: 
https://github.com/npm/npm/blob/master/doc/cli/npm-init.md#see-also https://raw.githubusercontent.com/npm/npm/master/doc/cli/npm-init.md 

The external link is normal Markdown. What are the numbers after the doc references in this repo? Those should probably be added to the Contributing.md file, yes?

**Comment by dirceu** [comment]
These numbers represent the section that the man page for the command is assigned to (http://stackoverflow.com/a/62972). For instance, you can run this to get the man page:

```sh
$ man npm-scope # or `man 7 npm-scope`
```

However, the man page for `package.json` doesn't seem to be installed:

```sh
$ man -w npm-scope
/usr/local/share/man/man7/npm-scope.7

$ man -w npm-version
/usr/local/share/man/man1/npm-version.1

$ man -w package.json
No manual entry for package.json

$ npm --version   
3.7.2
```

**Comment by kevinSuttle** [comment]
Hm. Good find. Not sure what do to here.

**Comment by dirceu** [comment]
About the man page for `package.json`: I'll see if there is already an issue for that; otherwise I'll create one and try to write a patch for it.

I think it's safe to close this issue.

**Comment by dirceu** [comment]
Update: please disregard my comment about the `package.json` man page. This seems to be a homebrew issue: the man page is installed correctly, just the symlink is missing.

**Comment by dirceu** [comment]
Fixed the homebrew issue :-)
