### ISSUE TITLE
Waterline module not getting downloaded

### ISSUE THREAD

**Issue by svlungade** [npm/npm#11131]
```
C:\Users>npm install waterline
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "waterline"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7

npm ERR! shasum check failed for C:\Users\AppData\Local\Temp\npm-2892-85c49534\vossbasmgdd2oss01.ad.infosys.com_4873\anchor\-\anchor-0.11.0.tgz
npm ERR! Expected: 02fec8946ba41ad5a604256cbcd4fecce95f891e
npm ERR! Actual:   6311b99e3913c0ccee7a7ed668a9e4cd32ab4478
npm ERR! From:     http://vossbasmgdd2oss01.ad.infosys.com:4873/anchor/-/anchor-0.11.0.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\npm-debug.log
```

**Comment by KenanY** [comment]
@svlungade Does this also occur with the default registry (`registry.npmjs.org`)?

**Comment by svlungade** [comment]
with the default registry of my organization, I am able to download other modules, however this perticular one is giving this issue. If the problem was with registry, I should have not able to download any of them.

**Comment by KenanY** [comment]
@svlungade Have you tried running `npm cache clean`?

**Comment by svlungade** [comment]
yes, I tried that - still the same, is it because my machine is 32-bit? has it anything to do with 32/64 bit machines?

**Comment by tjwebb** [comment]
@svlungade you might want to email the maintainers of Anchor about this. Sails/Waterline aren't really actively maintained anymore, so you might want to look for a different solution.

**Comment by othiym23** [comment]
It looks like the version of waterline on `http://vossbasmgdd2oss01.ad.infosys.com:4873/` is either corrupt or was uploaded with the incorrect shasum. Try publishing a new version of the package to that registry, or getting the registry maintainers to do so.

As there's not much that the CLI team can do to help you out with this, I'm going to close this as resolved, but if you have further questions about what that error means, feel free to ask. Good luck getting this sorted out, and thanks for your time!
