### ISSUE TITLE
Remove test script and devDependencies from package.json after install

### ISSUE THREAD

**Issue by piranna** [npm/npm#11139]
It's a good practice to add the `test` folder and others to the `.npmignore` file so they don't get uploaded to the npm registry nor downloaded when a module gets installed as a dependency, using less bandwidth. Problem is, that `package.json` still hos the `devDependencies` and the `scripts/test` fields, that if the tests are removed they are useless. Since the `package.json` file is already modified to add some fields like `gitHead` and `dist`, I think they should be removed (only when installed as dependency) since they are only needed when used directly, for example when the project is downloaded directly from GitHub.

**Comment by othiym23** [comment]
Thanks for writing this up!

> It's a good practice to add the `test` folder and others to the `.npmignore` file so they don't get uploaded to the npm registry nor downloaded when a module gets installed as a dependency, using less bandwidth.

While many developers do prefer this, this is nowhere near a universal preference (many of us like packages being shipped complete with tests, as it makes it easier to hack on the packages as installed). As a tool, npm leaves it up to developers to decide how they want to package their projects for distribution, and this is something the team doesn't really see a need to change. As such, I don't think it makes sense to strip out `devDependencies`, and so this isn't a change the team is going to make.

**Comment by piranna** [comment]
> many of us like packages being shipped complete with tests, as it makes it easier to hack on the packages as installed

This is something I have though aboutseveral times in the past, it doesn't have relationship with this issue but maybe it's relevant: I have "hack" the modules several times in the past (just yesterday :-) ), but there's the problem that you can't be able to upload the changes to github or somewhere since you don't have the git info. I though that the modules can be installed "clean" (with `.npmignore`, removed tests and so), and when someone want to hack it "promote" them with a new command (`npm dev`, maybe?) that replace the module content downloaded from npm with the one from its repository, so you can later make a commit and a pull-request with your changes. I don't know if it makes sense to have this functionality on npm or on another independent command or if it makes sense at all, but I think it would be useful to allow both reduce bandwith and make it easier to push "hack" changes and quick bugfixes, what do you thing?
