### ISSUE TITLE
The UX of npm-init

### ISSUE THREAD

**Issue by kevinSuttle** [npm/npm#11137]
https://docs.npmjs.com/misc/config#init-module isn't referenced in https://docs.npmjs.com/cli/init#configuration 

`npm init` doesn't have an option to point to a specific config file/package.json stub, nor does it offer a way to save generated package.json files as a config option to use in the future, possibly as default

`npm config` only has a small subset of functionality when it comes to init defaults, and its releationship to npm init is confusing (at least to me). Seems like you're defining the same data in 2 different places. 

```bash
init-author-name
init-author-email
init-author-url
init-license
init-version
```

Missing from this
```bash
init-registry // or init-publishconfig
init-scope
```

These last 2 could (should?) even be used as defaults for `npmo` users instead of having to login with flags every time. See https://github.com/npm/npmo-auth-sso/issues/2 for an alternative idea to this.

But again, I'm not sure how `npm config` maps to `npm init`, though `npm config`'s docs are the only ones that reference **where to actually save the file**. 

Thanks.

**Comment by othiym23** [comment]
A patch to link between the docs pages would be very welcome.

I agree that the `npm init` user experience doesn't capture a lot of what would be useful for users who are primarily working with npmo. There's a little-known bit of functionality in `init-package-json` that allows you to swap out the interview script used by `promzard` to get the information to be put into the generated `package.json`. I suggest that the next step here is to file an issue on npm/npmo-installer and talking over with them what a custom interview script for npmo might look like. It might turn out that some of those stubbed values would be necessary to support in npm's own configuration, and I'm happy to add them once that becomes clearer, but I think starting the discussion with @bcoe and @nexdrew is the right place to start, so I'm going to close this. Thanks for putting this together!

**Comment by kevinSuttle** [comment]
@othiym23 Re: docs patch: I started to: https://github.com/npm/npm/issues/11136

**Comment by kevinSuttle** [comment]
cc: @isaacs @iarna

**Comment by kevinSuttle** [comment]
https://github.com/npm/npm/blob/master/lib/init.js#L14

**Comment by kevinSuttle** [comment]
Related: https://github.com/npm/npm/issues/10782
