### ISSUE TITLE
npm install error please help to fix this

### ISSUE THREAD

**Issue by ashishsingh2641** [npm/npm#11145]
```
$ npm install -g
npm ERR! addLocal Could not install c:\learn 
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code EISDIR
npm ERR! errno -4068

npm ERR! EISDIR, read
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     c:\learn \npm-debug.log
/c/Program Files/nodejs/npm: line 14:  1568 Signal 112              (core dumped) "$basedir/node.exe" "$basedir/node_modules/npm/bin/npm-cli.js" "$@"
```

**Comment by KenanY** [comment]
@ashishsingh2641 What are you expecting to happen when you run `npm install -g` with no arguments?

**Comment by bfilia** [comment]
If you installed Node.js using any popular method, it comes with npm installed. You can test this using <b>npm --version</b>.

If you're trying to install a node package globally, you need to specify it at the end of the command. For example: <b>npm install -g gulp</b>

**Comment by othiym23** [comment]
Node 0.12.0 is a particularly troubled release of Node, having numerous documented problems. You might want to upgrade to the newest Node.js 0.12 installer, or perhaps even the latest version of Node.js LTS (long-term support), which has far fewer bugs.

As @KenanY has noted, `npm install -g` doesn't do anything interesting, as you have to provide a list of packages to globally install (that error message could be better, I agree).

Closing as resolved.
