### ISSUE TITLE
Error when running npm install

### ISSUE THREAD

**Issue by Azuraxe** [npm/npm#11155]
Hello I am getting the following error when running npm install
```
root@____:/var/www/html/nodebb# npm install
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v0.12.9
npm ERR! npm  v2.14.9
npm ERR! code ENOMEM
npm ERR! errno ENOMEM
npm ERR! syscall spawn

npm ERR! spawn ENOMEM
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

Thanks!

**Comment by bfilia** [comment]
It looks like you're out of memory on your system.

You can try running --max-old-space-size=<value> and setting it to a higher value, or check your memory settings if you're running it from a VM. 

Hope that helps!

**Comment by iarna** [comment]
To clarify, `max-old-space` is an argument you would pass to `node` and not `npm`. Something like:
```
node ----max_old_space_size=SOMEVALUE $(which npm) install
```

But I suspect you just need more memory in your VM. As this seems to be resolved, I'm going to close it. If our diagnosis was wrong, or you have new issues, please don't hesitate to create a new issue here.

**Comment by Azuraxe** [comment]
Thanks for clarifying. Increasing memory seemed to fix the issue! Thanks for the support

**Comment by irvingswiftj** [comment]
`node --max-old-space-size=1000 $(which npm) install` worked for me in the end 👍
