### ISSUE TITLE
package metadata must include name (npm v 3.5.2, node v5.4.1)

### ISSUE THREAD

**Issue by ImranAhmed** [npm/npm#11159]
I've started seeing this error after upgrading from npm 2 to npm 3.

The package names definitely do have a name attribute. Any ideas?

```
473 verbose stack AssertionError: package metadata must include name
473 verbose stack     at getCacheRoot (c:\Program Files\nodejs\node_modules\npm\lib\cache\cached-package-root.js:10:3)
473 verbose stack     at addShrinkwrap (c:\Program Files\nodejs\node_modules\npm\lib\fetch-package-metadata.js:185:27)
473 verbose stack     at c:\Program Files\nodejs\node_modules\npm\lib\fetch-package-metadata.js:171:14
473 verbose stack     at c:\Program Files\nodejs\node_modules\npm\node_modules\iferr\index.js:13:50
473 verbose stack     at RES (c:\Program Files\nodejs\node_modules\npm\node_modules\inflight\inflight.js:23:14)
473 verbose stack     at f (c:\Program Files\nodejs\node_modules\npm\node_modules\once\once.js:17:25)
473 verbose stack     at c:\Program Files\nodejs\node_modules\npm\lib\cache.js:361:16
473 verbose stack     at c:\Program Files\nodejs\node_modules\npm\node_modules\write-file-atomic\index.js:29:9
473 verbose stack     at LOOP (c:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:7:26)
473 verbose stack     at c:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:18:7
```

**Comment by iarna** [comment]
I suspect this is from one of your dependencies and not from your top level module. So that we can help you, we need a couple of things:

1. What command were you running?
2. Please link to your `package.json` and the `npm-debug.log` that's produced when you get this error.

**Comment by ImranAhmed** [comment]
Hi Rebecca,

Thanks for the prompt reply and thank you for your time.

For simplicity I removed all dependencies and just referenced Angular however I am still seeing this error. 

The commands I ran are as follows:

npm cache clean
npm install

My package.json is as follows:
{
  "name": "ia",
  "version": "0.1.0",
  "private": true,
  "description": "website",
  "dependencies": {
    "angular": "^1.4.7"
  },
  "devDependencies": {
  }
}

and npm-debug.log is attached
[npm-debug.log.txt](https://github.com/npm/npm/files/94068/npm-debug.log.txt)

**Comment by Ancient-One** [comment]
Did you manage to find out what happened, I am seeing the same thing.

**Comment by ImranAhmed** [comment]
It was something very specific to the way our packages are packaged within our internal company repo. I had to drop from npm v3 back down to npm v2 as this is the version we support internally.
