### ISSUE TITLE
[Extension] Can I use NPM as a CDN?

### ISSUE THREAD

**Issue by puneethnarayana** [npm/npm#11157]
I wanted to get an input on this about how we can club these two functions. 
Any pointers as to where to look and tweak would be highly helpful. 

Basically I am trying to add CDN capabilities onto NPM.

SO Question Link:
http://stackoverflow.com/questions/34811027/can-a-private-npm-repository-be-used-as-a-cdn

Any pointers would be highly appreciated.

**Comment by iarna** [comment]
From looking at your stackoverflow question, I don't think this is the most appropriate venue for this question– this is for issues with the `npm` command line program, not with `node.js` software in general.

That said, I wonder if something like this isn't what you're looking for?

http://expressjs.com/en/starter/static-files.html

As this is a bit off topic I'm going to close it. If you do run into any issues with `npm` itself, please don't hesitate to open an issue here though.
