### ISSUE TITLE
errno -4048

### ISSUE THREAD

**Issue by VivekAnand23** [npm/npm#11164]
I am installing `isbinaryfile` package and getting following issue.

```
$ npm install -g isbinaryfile
npm ERR! tar.unpack untar error C:\Users\usern\AppData\Roaming\npm-cache\isbinaryfile\3.0.0\package.tgz
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "isbinaryfile"
npm ERR! node v5.4.1
npm ERR! npm  v3.3.12
npm ERR! path C:\Users\usern\AppData\Roaming\npm\node_modules\.staging\isbinaryfile-955500199ba032e4f27e5965666d6fbd\test\fixtures\pdf.pdf
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall open

npm ERR! Error: EPERM: operation not permitted, open 'C:\Users\usern\AppData\Roaming\npm\node_modules\.staging\isbinaryfile-955500199ba032e4f27e5965666d6fbd\test\fixtures\pdf.pdf'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM: operation not permitted, open 'C:\Users\usern\AppData\Roaming\npm\node_modules\.staging\isbinaryfile-955500199ba032e4f27e5965666d6fbd\test\fixtures\pdf.pdf']
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'open',
npm ERR!   path: 'C:\\Users\\usern\\AppData\\Roaming\\npm\\node_modules\\.staging\\isbinaryfile-955500199ba032e4f27e5965666d6fbd\\test\\fixtures\\pdf.pdf' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\sample\npm-debug.log
```

**Comment by othiym23** [comment]
```
npm ERR! Please try running this command again as root/Administrator.
```

Your npm is installed in such a way that you need to be running as Administrator to perform global package installs. Either open an Administrator prompt and try again, or change the ACL on `C:\Users\usern\AppData\Roaming\npm\node_modules` and its children to grant permissions to `usern`. 

Since this is a setup / configuration issue, I'm going to close this issue as resolved. Let us know if you do the above and continue to have problems!

**Comment by VivekAnand23** [comment]
`usern` is having all the rights on this folder. In fact, it is a part of `Administrator` group.

All other packages are getting installed without any issues. Wherever there is a `PDF`, it halts the process.

I tried changing the `ACL` for this folder, but no luck. Also ran the command after opening up the `Command Window` as `Run as Administrator`.

**Comment by sebaquevedo** [comment]
if someone is still getting this problem, try downgrading npm or, the easier uncontroled way...use **--force** with npm install
