### ISSUE TITLE
npm taking roughly 70 s to show info

### ISSUE THREAD

**Issue by niklas1375** [npm/npm#11162]
When I try to get the info on globally installed modules after issuing the command it takes about 70 seconds to receive the result. However I don't get an error I just have to wait for approx. 70 s.
OS: Windows 10
npm version: 2.14.7
node version: 4.2.2

**Comment by othiym23** [comment]
When you say "try to get the info on globally installed modules", what command are you running? `npm ls -g`? It's hard to say from the question as asked whether it's a network issue or maybe npm taking a while to read all the packages installed globally from disk.

**Comment by niklas1375** [comment]
Sorry for being unclear. I run "npm info cordova" I also tried it with express and it also took about 70 s. The delay stays more or less consistent though which kinda puzzles me.
Network issue is rather improbable because I didn't switch networks or network settings since the issue appeared.

**Comment by niklas1375** [comment]
I just reread documentation on the info command and realized it is network based. So I guess there might be some server related issues going on?
