### ISSUE TITLE
Authorization service failure causing ultra-slow installs

### ISSUE THREAD

**Issue by ashaffer** [npm/npm#11169]
A package i've written ([vdux](https://githhub.com/vdux/vdux)) is having extremely slow installs, and I think i've tracked it down to an error that looks like this:

```
npm http 500 https://registry.npmjs.org/@f%2fomit
npm verb headers { 'content-type': 'application/json',
npm verb headers   'cache-control': 'max-age=0',
npm verb headers   'content-length': '41',
npm verb headers   'accept-ranges': 'bytes',
npm verb headers   date: 'Sat, 16 Jan 2016 07:01:49 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-lax1420-LAX',
npm verb headers   'x-cache': 'MISS',
npm verb headers   'x-cache-hits': '0',
npm verb headers   'x-timer': 'S1452927678.311811,VS0,VE31044' }
```

These keep happening during my install, and they take forever. I assume it is related to the fact that it depends on a large number of small scoped modules. It seems like there is some authorization check that is happening when you try to install a scoped module - and that check is timing out or something. Not sure what's going on exactly.

**Comment by aliatsis** [comment]
+1

I've been running debug mode and seeing Authorization service failure frequently.
Installs and updates just hang forever. I've tried everything from `npm cache clean` to reinstalling npm/node.

This only started happening to me as of yesterday out of nowhere and it's killing me.

**Comment by shellscape** [comment]
We're seeing it on the east coast and in ireland today.

**Comment by MarkPieszak** [comment]
Yes it's happening here on the East coast for me today as well.

**Comment by dhyasama** [comment]
+1

also on the east coast

**Comment by Hades32** [comment]
This also happen e.g. when installing Angular2 packages... :(

npm http 500 https://registry.npmjs.org/@angular%2fcore
npm info retry will retry, error on last attempt: Error: Authorization service failure : @angular/core

**Comment by aliatsis** [comment]
I'm on the west coast (Silicon Valley) for what it's worth. This is so painful

**Comment by aliatsis** [comment]
I wonder what the odds are that this error has to do with scoped packages.
I have a lot of deps under my private scope.

For those experiencing this, is it with or without scoped packages for you?

**Comment by shellscape** [comment]
@aliatsis seeing it almost exclusively on scoped packages

**Comment by aliatsis** [comment]
@shellscape yep I'm noticing that too. I use scoped packages heavily on my projects so this really sucks.

**Comment by aliatsis** [comment]
yay!!! I filed a support ticket earlier:

```
Hello Anthony,

Thanks for emailing. I'm sorry to hear this issue has caused such a headache for you. I've checked with the registry team, and they've identified the issue resulting in the Error: Authorization service failure error message, and resolved it. Are you able to access this package again?

Thanks so much, 
Stephanie
```
