### ISSUE TITLE
npm install --production installs dev packages

### ISSUE THREAD

**Issue by saxicek** [npm/npm#11166]
I am using npm version 3.3.12 and it is installing unnecessary dev packages:
```npm install cloudant --production```

Check for installed packages:
```ls node_modules/cloudant/node_modules/nano/node_modules/```

It includes package e.g. istanbul which is development package.

I saw issue #9024 which says that development packages will not be installed. My OS is Ubuntu 14.04, Node version 5.4.1, nvm 0.30.1.

Trouble is that with this behavior my package with included dependencies is unnecessary big. Am I doing something wrong?

**Comment by iarna** [comment]
Even _without_ `--production`, neither `cloudant` nor `nano`'s dev dependencies should be installed. Not using `--production` should only result in your module's direct dev dependencies to be installed.

However, this is kind of a special case. `cloudant` _bundles_ `nano`. And by bundles, I mean that when an author of `cloudant` publishes new versions, npm is instructed to include the copy of `nano` that the author had on their computer. If the author had a dev dep installed, then you'll get that dev dep. While this is unusual, it's not strictly speaking an error.

It's not clear if they did this on purpose, or if it as unintended. I encourage you to reach out to the authors of [`cloudant`](https://github.com/cloudant/nodejs-cloudant) directly.
