### ISSUE TITLE
npm ls return code

### ISSUE THREAD

**Issue by curtisr7** [npm/npm#11160]
A change introduced by #2798 updated `npm` such that when errors/warnings are encountered during `npm ls` the script will return a non-zero error code. While this change satisfied the person reporting the problem, I think the change was applied too liberally. 

The description of the `ls` command is **This command will print to stdout all the versions of packages that are installed, as well as their dependencies, in a tree-structure**. That is what I would expect from running `npm ls`. This feature of performing extra validation seems somewhat out of place for the default case. 

I think it should be hidden behind a `-v/--validate`(or something) switch... although I'm not sure how many people a change like this would break.

**Comment by othiym23** [comment]
I would wager that validating that a tree's install is in a good condition is the primary use case of `npm ls` for a vast majority of its users. As such, I think it's way too late to make the suggested change, and so I'm going to close this feature request. _However_, I'd be happy to see the documents updated to reflect that `npm ls` does this validation, and that it returns a nonzero exit code in the case of warnings or errors. Thanks for your time!
