### ISSUE TITLE
error compiling Xen Orchestre from source

### ISSUE THREAD

**Issue by robina80** [npm/npm#11161]
[npm-debug.txt](https://github.com/npm/npm/files/92174/npm-debug.txt)

hi all,

trying to compile XO from source, i have tried to do it on ubuntu 15 and on debian 8

im following this how to -

https://github.com/vatesfr/xo/blob/master/doc/installation/manual_installation.md

i get stuck on the part where you cd into the xo-server directory and run the below

npm install && npm run build

this is the error i get -

```
root@XO:~/xo-server# npm install && npm run build
npm WARN engine trace@2.0.2: wanted: {"node":"^4.0"} (current: {"node":"5.4.1","npm":"3.3.12"})
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/gulpjs/gulp.git /root/.npm/_git-remotes/git-github-com-gulpjs-gulp-git-4-0-9508ac6e73bc4e2dd3065e6cd9e6f094: Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-gulpjs-gulp-git-4-0-9508ac6e73bc4e2dd3065e6cd9e6f094'...
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/gulpjs/gulp.git /root/.npm/_git-remotes/git-github-com-gulpjs-gulp-git-4-0-9508ac6e73bc4e2dd3065e6cd9e6f094: fatal: unable to connect to github.com:
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/gulpjs/gulp.git /root/.npm/_git-remotes/git-github-com-gulpjs-gulp-git-4-0-9508ac6e73bc4e2dd3065e6cd9e6f094: github.com[0: 192.30.252.130]: errno=Connection timed out
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.4.1
npm ERR! npm v3.3.12
npm ERR! code 128
npm ERR! Command failed: git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/gulpjs/gulp.git /root/.npm/_git-remotes/git-github-com-gulpjs-gulp-git-4-0-9508ac6e73bc4e2dd3065e6cd9e6f094
npm ERR! Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-gulpjs-gulp-git-4-0-9508ac6e73bc4e2dd3065e6cd9e6f094'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.130]: errno=Connection timed out
npm ERR!
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!
npm ERR! Please include the following file with any support request:
npm ERR! /root/xo-server/npm-debug.log

root@XO:~/xo-server#
```

EDIT - i have tried this as a non root user aswell and i get the same error as above

if anyone could help be great

thanks

rob

**Comment by KenanY** [comment]
@robina80 The "connection timed out" error message, coming from `git` not `npm`, indicates to me that this is an issue with your internet connection. Maybe you are behind a proxy or firewall. Maybe something is blocking the git protocol. Can't say anything for sure at the moment.

**Comment by robina80** [comment]
so git uses a different protocal other than http or https, can i get git to work on these protocals instead other than using the git one

i will try this at home as i know my firewall doesnt block anything going out

**Comment by robina80** [comment]
mmm...

the link that says here and the other web address that i copy/paste and click on the download zip file are two completley different zip files

xo-server-next-release.zip
xo-server-stable.zip

what one is the correct one i need?

**Comment by KenanY** [comment]
@robina80 I have no idea. I think it would be best to ask the project's authors since that has nothing to do with `npm` as far as I can tell.

**Comment by KaliszAd** [comment]
I have the same problem. I used git protocoll before, as you can see in these instructions: "https://github.com/vatesfr/xo/blob/master/doc/installation/manual_installation.md"

Also on AMD64 - Debian 8 Jessie

**Comment by KenanY** [comment]
@robina80 Are you still encountering this issue?

**Comment by KaliszAd** [comment]
@KenanY I am unable to test now, will check back in about 2 weeks. I think I have solved my problems somehow, but I forgot and have to find my notes on the problem and spin up the VM again.

**Comment by robina80** [comment]
Kenan,  no i am not anymore,  thank you for asking,  i followed their
official documentation to install on debian.

Thanks

Rob

**Comment by KenanY** [comment]
Closing as resolved.
