### ISSUE TITLE
Yeoman Angular 2 generator cannot read rxjs-5.0.0-alpha.7.tgz

### ISSUE THREAD

**Issue by MrRhino** [npm/npm#11174]
loadDep:zone.js → network ▀ ╢████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
npm ERR! fetch failed https://registry.npmjs.org/@reactivex/rxjs/-/rxjs-5.0.0-alpha.7.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 504
npm ERR! fetch failed https://registry.npmjs.org/@reactivex/rxjs/-/rxjs-5.0.0-alpha.7.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 504
npm ERR! fetch failed https://registry.npmjs.org/@reactivex/rxjs/-/rxjs-5.0.0-alpha.7.tgz
npm ERR! Darwin 11.4.2
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.2.0
npm ERR! npm  v3.5.3

npm ERR! fetch failed with status code 503
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by thisconnect** [comment]
Almost the same error (with status code 504) with `@sindresorhus/df` 
also tested `npm install @reactivex/rxjs`, that errors as well. 
```
npm ERR! node v5.4.1
npm ERR! npm  v3.5.3

npm ERR! fetch failed with status code 504
```

At this point I believe it only happens with scoped packages. I am not using a proxy :(. Could that be related with a recent OSX 10.11.2 updated?

**Comment by MrRhino** [comment]
I use OSX 10.7.5

**Comment by MrRhino** [comment]
Apparently the download is failing: http fetch GET https://registry.npmjs.org/@reactivex/rxjs/-/rxjs-5.0.0-alpha.7.tgz

I'm able to download the file by pasting the URL into my browser.

This is a snippet from the ".../yeoman-angular2/npm-debug.log" when things go south:

227 verbose addRemoteTarball https://registry.npmjs.org/@reactivex/rxjs/-/rxjs-5.0.0-alpha.7.tgz not in flight; adding
228 verbose addRemoteTarball [ 'https://registry.npmjs.org/@reactivex/rxjs/-/rxjs-5.0.0-alpha.7.tgz',
228 verbose addRemoteTarball   '3e2e8287b61e69b9cea72443920300f301127031' ]
229 info retry fetch attempt 1 at 12:24:12 PM
230 info attempt registry request try #1 at 12:24:12 PM
231 http fetch GET https://registry.npmjs.org/@reactivex/rxjs/-/rxjs-5.0.0-alpha.7.tgz
232 http fetch 503 https://registry.npmjs.org/@reactivex/rxjs/-/rxjs-5.0.0-alpha.7.tgz
233 info retry will retry, error on last attempt: Error: server error 503
234 info attempt registry request try #2 at 12:25:22 PM
235 http fetch GET https://registry.npmjs.org/@reactivex/rxjs/-/rxjs-5.0.0-alpha.7.tgz
236 http fetch 503 https://registry.npmjs.org/@reactivex/rxjs/-/rxjs-5.0.0-alpha.7.tgz
237 info retry will retry, error on last attempt: Error: server error 503
238 info attempt registry request try #3 at 12:27:23 PM
239 http fetch GET https://registry.npmjs.org/@reactivex/rxjs/-/rxjs-5.0.0-alpha.7.tgz
240 http fetch 503 https://registry.npmjs.org/@reactivex/rxjs/-/rxjs-5.0.0-alpha.7.tgz
241 error fetch failed https://registry.npmjs.org/@reactivex/rxjs/-/rxjs-5.0.0-alpha.7.tgz
242 warn retry will retry, error on last attempt: Error: fetch failed with status code 503
243 info retry fetch attempt 2 at 12:28:33 PM
244 info attempt registry request try #1 at 12:28:33 PM
245 http fetch GET https://registry.npmjs.org/@reactivex/rxjs/-/rxjs-5.0.0-alpha.7.tgz
246 http fetch 504 https://registry.npmjs.org/@reactivex/rxjs/-/rxjs-5.0.0-alpha.7.tgz
247 info retry will retry, error on last attempt: Error: server error 504
248 info attempt registry request try #2 at 12:29:36 PM
249 http fetch GET https://registry.npmjs.org/@reactivex/rxjs/-/rxjs-5.0.0-alpha.7.tgz
250 http fetch 504 https://registry.npmjs.org/@reactivex/rxjs/-/rxjs-5.0.0-alpha.7.tgz
251 info retry will retry, error on last attempt: Error: server error 504
252 info attempt registry request try #3 at 12:31:30 PM
253 http fetch GET https://registry.npmjs.org/@reactivex/rxjs/-/rxjs-5.0.0-alpha.7.tgz
254 http fetch 503 https://registry.npmjs.org/@reactivex/rxjs/-/rxjs-5.0.0-alpha.7.tgz
255 error fetch failed https://registry.npmjs.org/@reactivex/rxjs/-/rxjs-5.0.0-alpha.7.tgz
256 warn retry will retry, error on last attempt: Error: fetch failed with status code 503
257 info retry fetch attempt 3 at 12:33:30 PM
258 info attempt registry request try #1 at 12:33:30 PM
259 http fetch GET https://registry.npmjs.org/@reactivex/rxjs/-/rxjs-5.0.0-alpha.7.tgz
260 http fetch 504 https://registry.npmjs.org/@reactivex/rxjs/-/rxjs-5.0.0-alpha.7.tgz
261 info retry will retry, error on last attempt: Error: server error 504
262 info attempt registry request try #2 at 12:34:31 PM
263 http fetch GET https://registry.npmjs.org/@reactivex/rxjs/-/rxjs-5.0.0-alpha.7.tgz
264 http fetch 503 https://registry.npmjs.org/@reactivex/rxjs/-/rxjs-5.0.0-alpha.7.tgz
265 info retry will retry, error on last attempt: Error: server error 503
266 info attempt registry request try #3 at 12:36:32 PM
267 http fetch GET https://registry.npmjs.org/@reactivex/rxjs/-/rxjs-5.0.0-alpha.7.tgz
268 http fetch 503 https://registry.npmjs.org/@reactivex/rxjs/-/rxjs-5.0.0-alpha.7.tgz
269 error fetch failed https://registry.npmjs.org/@reactivex/rxjs/-/rxjs-5.0.0-alpha.7.tgz
270 silly rollbackFailedOptional Starting
271 silly rollbackFailedOptional Finishing
272 silly runTopLevelLifecycles Starting
273 silly runTopLevelLifecycles Finishing
274 silly install printInstalled
275 verbose stack Error: fetch failed with status code 503
275 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/fetch.js:51:14)
275 verbose stack     at emitOne (events.js:78:13)
275 verbose stack     at Request.emit (events.js:170:7)
275 verbose stack     at Request.onRequestResponse (/usr/local/lib/node_modules/npm/node_modules/request/request.js:951:10)
275 verbose stack     at emitOne (events.js:78:13)
275 verbose stack     at ClientRequest.emit (events.js:170:7)
275 verbose stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:422:21)
275 verbose stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:89:23)
275 verbose stack     at TLSSocket.socketOnData (_http_client.js:312:20)
275 verbose stack     at emitOne (events.js:78:13)
275 verbose stack     at TLSSocket.emit (events.js:170:7)

**Comment by thisconnect** [comment]
@MrRhino I believe `npm config ls -l` would be helpful info for the NPM people

**Comment by thisconnect** [comment]
Can you confirm that `npm install` works for you and the problem only appears with scoped packages?

Please test `npm install @sindresorhus/df`

**Comment by MrRhino** [comment]
npm install gives the same error.

Here is my config:

; cli configs
long = true
user-agent = "npm/3.5.3 node/v5.2.0 darwin x64"

; userconfig /Users/MickieMouse/.npmrc
dev = false

; default values
access = null
also = null
always-auth = false
bin-links = true
browser = null
ca = null
cache = "/Users/MickieMouse/.npm"
cache-lock-retries = 10
cache-lock-stale = 60000
cache-lock-wait = 10000
cache-max = null
cache-min = 10
cafile = undefined
cert = null
color = true
depth = null
description = true
dev = false
dry-run = false
editor = "vi"
engine-strict = false
fetch-retries = 2
fetch-retry-factor = 10
fetch-retry-maxtimeout = 60000
fetch-retry-mintimeout = 10000
force = false
git = "git"
git-tag-version = true
global = false
global-style = false
globalconfig = "/usr/local/etc/npmrc"
globalignorefile = "/usr/local/etc/npmignore"
group = 20
heading = "npm"
https-proxy = null
if-present = false
ignore-scripts = false
init-author-email = ""
init-author-name = ""
init-author-url = ""
init-license = "ISC"
init-module = "/Users/MickieMouse/.npm-init.js"
init-version = "1.0.0"
json = false
key = null
legacy-bundling = false
link = false
local-address = undefined
loglevel = "warn"
; long = false (overridden)
message = "%s"
node-version = "5.2.0"
npat = false
onload-script = null
only = null
optional = true
parseable = false
prefix = "/usr/local"
production = false
progress = true
proprietary-attribs = true
proxy = null
rebuild-bundle = true
registry = "https://registry.npmjs.org/"
rollback = true
save = false
save-bundle = false
save-dev = false
save-exact = false
save-optional = false
save-prefix = "^"
scope = ""
searchexclude = null
searchopts = ""
searchsort = "name"
shell = "/bin/bash"
shrinkwrap = true
sign-git-tag = false
strict-ssl = true
tag = "latest"
tag-version-prefix = "v"
tmp = "/var/folders/n_/7xh0y8gs2mzbq05sk_jpl9c00000gn/T"
umask = 18
unicode = true
unsafe-perm = true
usage = false
user = 0
; user-agent = "npm/{npm-version} node/{node-version} {platform} {arch}" (overridden)
userconfig = "/Users/MickieMouse/.npmrc"
version = false
versions = false
viewer = "man"

**Comment by thisconnect** [comment]
strange. I can not reproduce the problem anymore, I did test on another WIFI. Also `npm install @reactivex/rxjs` works for me. Sorry

**Comment by MrRhino** [comment]
It installs after replacing the dependencies in the package.json file with the ones found here:
https://angular.io/docs/js/latest/quickstart.html

**Comment by busches** [comment]
@KenanY both @thisconnect and @MrRhino report the problem has been resolved, looks like this can be closed.
