### ISSUE TITLE
Updating replaces local packages with packages with the same name from npm Registry

### ISSUE THREAD

**Issue by osener** [npm/npm#11177]
Let's say we have an internal tool called `usd`;
```sh
$ mkdir usd; cd usd
$ npm init -y
$ echo '#!/usr/bin/env node\nconsole.log("hello from usd");' > index.js
$ sed -i "s/main/bin/" package.json
$ npm install . -g
$ usd
> hello from usd
```

If someone publishes a new package to npm Registry with the same name and someone in our team runs `npm update -g` expecting to update tools like `gulp`, npm replaces our internal tool with the package which happens to have the same name:

```sh
$ npm update -g
$ which usd
> usd not found
# at this point usd is replaced with some library from npm Registry, https://www.npmjs.com/package/usd
```

**Comment by othiym23** [comment]
When you run `npm update -g`, you're asking npm to find the latest versions of packages from whatever registry you've configured (either the default, or a different value of registry in `$HOME/.npmrc`). It would be _possible_ to look at the `_from` fields in the `package.json`s for global packages and warn, error, or silently pass over packages that weren't originally installed from that registry, but it would be a significant (breaking) change from what npm's done up to this point, and also would probably be very surprising to the vast majority of users encountering it for the first time, as many people hack on packages using local packages to start, and then reinstall them from the registry when they're done.

I think this behavior, while undesirable for some use cases, is how npm is intended to operate, and as such I don't see it as a bug. Also, I don't think changing this behavior would be useful for most npm users. So I'm going to close this issue, but if you have further questions about why this works the way it does, feel free to ask. Thanks for your time, and for including a repro case!

**Comment by osener** [comment]
I was expecting npm to keep track of where packages came from, and have better support for non-registry packages. Even when I'm hacking on a public package I don't think I would expect it to get replaced with upstream during a update, I'd run `npm install -g <packagename>` just like running `npm install <packagename> --save` when I want to switch some dependency back to upstream version.

I wrote a small utility I had forgotten about that was getting called periodically (installed using `npm install . -g` because of its dependencies), and I was surprised to discover that the executable has just vanished at some point. I still think it's counter-intuitive for `npm update -g` to touch packages that didn't come from a registry in the first place but I understand the reasons behind the current behavior, thanks for the explanation.
