### ISSUE TITLE
npm 3.3.12 not installing node module dependencies into specific folders

### ISSUE THREAD

**Issue by Connor-Knabe** [npm/npm#11173]
With the older versions of npm when I would run "npm install express" within node_modules there would be one folder called "express" and inside of that it would have all the dependencies express has.  Now everything "express" requires is within the node_modules folder.

Is this correct or a bug?

**Comment by razh** [comment]
That is the intended behavior of `npm@3`: https://docs.npmjs.com/how-npm-works/npm3

**Comment by Connor-Knabe** [comment]
@razh thank you that is what I was looking for! :+1:
