### ISSUE TITLE
Can't install any private repository

### ISSUE THREAD

**Issue by StarpTech** [npm/npm#11178]
This message appears everytime.

NPM: 3.5.3
Node: v4.2.1

also happens with npm: 2.14.7

I use no proxy, no vpn, private repo is paid ;). I can reproduce issue also on my production server with Ubuntu 14.0.4 and with the same versions.

```
loadRequestedDeps → netwo ▄ ╢█████████████████████████████░░░
```

**Comment by alonweiss-sl** [comment]
+1. We're experiencing exactly the same issue and it started yesterday, worked just fine before that.

**Comment by hilkeheremans** [comment]
+1 I am also experiencing this, with NPM v3.5.3 and Node v4.2.1. The following error message which appears after a while:
````
Error: fetch failed with status code 504
````

I am _NOT_ experiencing this on another box which is running npm 2.14.12 and Node v4.2.4.

**Comment by mariuslundgard** [comment]
+1. Downgraded to npm v2 to no avail.

**Comment by sercanov** [comment]
+1. It stuck at "loadRequestedDeps → netwo". Tried with "npm install @exponent/react-native-navigator"

**Comment by hilkeheremans** [comment]
@sercanov That implies it is affecting not just private packages, but scoped packages as well.

Escalating this via twitter to npm ceo & cto as I suspect they will want this sorted out before monday hits.

**Comment by hilkeheremans** [comment]
@mariuslundgard That is interesting - I tested again and do not have any issues when using node v4.2.4 and npm 2.14.2. 

Both of the boxes are running Mac OS X and are pretty much identically configured, except that the working box is running nvm (with v4.2.4 as default), the non-working box is just running a single node version (v4.2.1).

**Comment by grozen** [comment]
Already reported this on the twitters, but can't hurt to add it here as well. It's the same deal for me since yesterday, while trying for @cyclejs/core.
Here's a [log file](https://t.co/lJLEebXqNN).

**Comment by sercanov** [comment]
@hilkeheremans tried with node v5.3.0 and npm v2.14.15 and v3.5.3 both fails.

**Comment by hilkeheremans** [comment]
I'm thinking this might be related to some servers being very slow/timing out, and causing retries. Perhaps something is caching the package on my other machine. Guess we'll find out soon.

Retrieving the packages directly by URL from the browser (eg ```https://registry.npmjs.org/@cycle/core/-/core-6.0.0.tgz```) seems to work fine - sporadically. Throws HTTP 503 from time to time.

**Comment by StarpTech** [comment]
People who can't reproduce can try this:

```
npm cache clean [<path>]
npm install <package>
```
* Don't execute`npm clean cache` without a path

I hope this will be fixed ASAP. It's a huge blocker for me. @othiym23 @iarna @chrisdickinson

**Comment by hilkeheremans** [comment]
@StarpTech Thanks, you were right, forgot that npm itself caches as well. Issue now also occurs there.

Also totally blocking for me. Imagine what would happen once Monday hits and this isn't resolved by then. :-)

**Comment by sercanov** [comment]
@hilkeheremans @StarpTech Yeah, totally blocking. Gave up on working and watching movie till this sorted out. Don't know if I should be sad or happy ^^

**Comment by hilkeheremans** [comment]
Well, I'm losing hours when I didn't have any to lose, but I'll live.

Can't help but wonder how many automated deployments are failing right now though (sure, you can mitigate, but I doubt everyone does). It's a little worrisome, and a good wake up call re our dependence on npm.

**Comment by mariuslundgard** [comment]
@StarpTech @sercanov: Me too. Wanted to dig deeper into Cycle.js today – guess I’ll clean around the house instead.

PS. Apparently it works in the US: https://twitter.com/adrukh/status/688691075242942465

**Comment by hilkeheremans** [comment]
@mariuslundgard Interesting, looks like this mostly affects EU to RU geo then, judging by the names posting here. :-)

**Comment by alonweiss-sl** [comment]
We've already started to move away from npm as we relied on it for
production and our continuous deployment infrastructure.

Instead we use a custom built repo based on amazon s3 and dynamo db,  as
they are clearly more reliable.

This is a sad day. We thought private npm would be at least as reliable as
public npm.

**Comment by mariuslundgard** [comment]
@hilkeheremans @StarpTech @sercanov:  I’m using this as a temporary fix:

```sh
mkdir tmp/@cycle
curl https://registry.npmjs.org/@cycle/core/-/core-6.0.0.tgz > tmp/@cycle/core-6.0.0.tgz
npm install tmp/@cycle/core-6.0.0.tgz
```

Will have to update dependencies `package.json` later on.

**Comment by hilkeheremans** [comment]
Issue seems to resolved, got this a little earlier via npm js status alerts:

````

Elevated 503 rates for users in Europe
Incident Report for npm, Inc.
New Incident Status: Resolved
The configuration problem that caused this issue is now solved.
Jan 17, 14:07 UTC
PREVIOUS UPDATES
Investigating
Our users in Europe are currently experiencing elevated 503 rates. We're investigating.
Jan 17, 13:46 UTC
````

Package installs work fine for me now.

**Comment by StarpTech** [comment]
yes it works. @hilkeheremans  thanks for update.

**Comment by othiym23** [comment]
This was due to an operational snafu in the European portion of our service infrastructure, and as noted above, our operations team has cleaned it up. Our sincere apologies to everyone who got tangled up in this, and thanks for bringing it to our attention!

**Comment by Niffy** [comment]
Is this still a problem?  I've started to get problems installing private modules.
Heroku says it cannot find the module pretty quickly and AWS is saying
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 504

**Comment by grozen** [comment]
@Niffy Worked just fine for me the other day (pretty soon after this was resolved). That's not to say it can't get un-resolved, though obviously you may be experiencing something completely different.

**Comment by Niffy** [comment]
Could be, I sent a support email anyway and hope I get this resolved pretty soon.
