### ISSUE TITLE
"latest" tag ignored if an "alpha" semver range is used

### ISSUE THREAD

**Issue by tjwebb** [npm/npm#11183]
npm version 3.3.12

Consider:
```
10:08:47 ~ $ npm dist-tags ls trailpack-hapi
latest: 1.0.0-alpha-6

10:06:42 ~ $ npm dist-tags add trailpack-hapi@1.0.0-alpha-6 latest
npm WARN dist-tag add latest is already set to version 1.0.0-alpha-6
```

When I naively run `npm install trailpack-hapi`, version 0.0.15 is downloaded, which is not what I want.

However
```
npm install trailpack-hapi@latest
```

works as expected, downloading 1.0.0-alpha-6. This seems like a bug.

**Comment by othiym23** [comment]
This depends on the version of npm you're using. The latest version bundled with Node.js, `npm@3.3.12`, will do what you're describing. However, `npm@3.4.1` or newer (note: _do not install `npm@3.4.1`. It was _no good_) [includes a change](https://github.com/npm/npm/blob/master/CHANGELOG.md#ask-for-nothing-get-latest) to make this behavior more intuitive, for exactly the scenario you describe. Update to `npm@latest` and give it a shot, and the behavior should be what you expect!

**Comment by tjwebb** [comment]
Thanks @othiym23 I'll give it a shot and report back if I have any further issues.
