### ISSUE TITLE
Problems with npm install

### ISSUE THREAD

**Issue by dnyaneshginde** [npm/npm#11193]
Hello,

I am having issues with npm install. Following is the log. Any help in this regard is highly appreciated.

npm http GET https://registry.npmjs.org/repeat-element
npm http GET https://registry.npmjs.org/preserve
npm http GET https://registry.npmjs.org/error-ex
npm http GET https://registry.npmjs.org/window-size/0.1.0
npm http GET https://registry.npmjs.org/signal-exit
npm http 304 https://registry.npmjs.org/camelcase
npm http 304 https://registry.npmjs.org/wrappy
npm http 304 https://registry.npmjs.org/indent-string
npm http 304 https://registry.npmjs.org/ee-first/1.1.1
npm http 304 https://registry.npmjs.org/for-own
npm http 304 https://registry.npmjs.org/assert-plus
npm http 304 https://registry.npmjs.org/is-extendable
npm http 304 https://registry.npmjs.org/mime-db
npm http 304 https://registry.npmjs.org/is-equal-shallow
npm http 304 https://registry.npmjs.org/read-pkg
npm http 304 https://registry.npmjs.org/is-primitive
npm http 304 https://registry.npmjs.org/pinkie-promise
npm http 304 https://registry.npmjs.org/kind-of
npm http 304 https://registry.npmjs.org/escape-string-regexp
npm http 304 https://registry.npmjs.org/expand-range
npm http 304 https://registry.npmjs.org/graceful-fs
npm http 304 https://registry.npmjs.org/camelcase
npm http 304 https://registry.npmjs.org/preserve
npm http 304 https://registry.npmjs.org/error-ex
npm http 304 https://registry.npmjs.org/repeat-element
npm http 304 https://registry.npmjs.org/window-size/0.1.0
npm http 304 https://registry.npmjs.org/signal-exit
npm http GET https://registry.npmjs.org/ms/0.7.1
npm http 304 https://registry.npmjs.org/ms/0.7.1
npm http GET https://registry.npmjs.org/ansi-regex
npm http GET https://registry.npmjs.org/strip-indent
npm http GET https://registry.npmjs.org/spdx-license-ids
npm http GET https://registry.npmjs.org/spdx-license-ids
npm http GET https://registry.npmjs.org/find-up
npm http GET https://registry.npmjs.org/spdx-exceptions
npm http GET https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/spdx-expression-parse
npm http GET https://registry.npmjs.org/spdx-correct
npm http GET https://registry.npmjs.org/builtin-modules
npm http 304 https://registry.npmjs.org/spdx-license-ids
npm http 304 https://registry.npmjs.org/strip-indent
npm http 304 https://registry.npmjs.org/spdx-license-ids
npm http 304 https://registry.npmjs.org/find-up
npm http 304 https://registry.npmjs.org/spdx-exceptions
npm http 304 https://registry.npmjs.org/ansi-regex
npm http GET https://registry.npmjs.org/ansi-wrap/0.1.0
npm http 304 https://registry.npmjs.org/spdx-correct
npm http 304 https://registry.npmjs.org/lodash
npm http 304 https://registry.npmjs.org/spdx-expression-parse
npm http 304 https://registry.npmjs.org/builtin-modules
npm http GET https://registry.npmjs.org/is-arrayish
npm http GET https://registry.npmjs.org/for-in
npm http GET https://registry.npmjs.org/number-is-nan
npm http 304 https://registry.npmjs.org/ansi-wrap/0.1.0
npm http 304 https://registry.npmjs.org/for-in
npm http 304 https://registry.npmjs.org/number-is-nan
npm http 304 https://registry.npmjs.org/is-arrayish
npm ERR! error rolling back Error: EPERM, unlink 'C:\development\workspace\portl
ets\cds-portlets\portlets\node_modules\istanbul\node_modules\handlebars\node_mod
ules\uglify-js\node_modules\yargs\node_modules\cliui\node_modules\right-align\no
de_modules\align-text\node_modules\longest\package.json'
npm ERR! error rolling back  handlebars@4.0.5 { [Error: EPERM, unlink 'C:\develo
pment\workspace\portlets\cds-portlets\portlets\node_modules\istanbul\node_module
s\handlebars\node_modules\uglify-js\node_modules\yargs\node_modules\cliui\node_m
odules\right-align\node_modules\align-text\node_modules\longest\package.json']
npm ERR! error rolling back   errno: 50,
npm ERR! error rolling back   code: 'EPERM',
npm ERR! error rolling back   path: 'C:\\development\\workspace\\portlets\\cds-p
ortlets\\portlets\\node_modules\\istanbul\\node_modules\\handlebars\\node_module
s\\uglify-js\\node_modules\\yargs\\node_modules\\cliui\\node_modules\\right-alig
n\\node_modules\\align-text\\node_modules\\longest\\package.json' }
npm ERR! error rolling back Error: EPERM, unlink 'C:\development\workspace\portl
ets\cds-portlets\portlets\node_modules\istanbul\node_modules\handlebars\node_mod
ules\uglify-js\node_modules\yargs\node_modules\cliui\node_modules\right-align\no
de_modules\align-text\node_modules\kind-of\package.json'
npm ERR! error rolling back  istanbul@0.3.22 { [Error: EPERM, unlink 'C:\develop
ment\workspace\portlets\cds-portlets\portlets\node_modules\istanbul\node_modules
\handlebars\node_modules\uglify-js\node_modules\yargs\node_modules\cliui\node_mo
dules\right-align\node_modules\align-text\node_modules\kind-of\package.json']
npm ERR! error rolling back   errno: 50,
npm ERR! error rolling back   code: 'EPERM',
npm ERR! error rolling back   path: 'C:\\development\\workspace\\portlets\\cds-p
ortlets\\portlets\\node_modules\\istanbul\\node_modules\\handlebars\\node_module
s\\uglify-js\\node_modules\\yargs\\node_modules\\cliui\\node_modules\\right-alig
n\\node_modules\\align-text\\node_modules\\kind-of\\package.json' }
npm ERR! Error: ENOENT, open 'C:\development\workspace\portlets\cds-portlets\por
tlets\node_modules\istanbul\node_modules\handlebars\node_modules\optimist\packag
e.json'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\dev\\nodejs0.10.26\\\\node.exe" "C:\\dev\\nodejs0.10.26\\n
ode_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd C:\development\workspace\portlets\cds-portlets\portlets
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! path C:\development\workspace\portlets\cds-portlets\portlets\node_modul
es\istanbul\node_modules\handlebars\node_modules\optimist\package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm http GET https://registry.npmjs.org/path-exists
npm http GET https://registry.npmjs.org/fill-range
npm http GET https://registry.npmjs.org/longest
npm http GET https://registry.npmjs.org/repeat-string
npm http 304 https://registry.npmjs.org/path-exists
npm http 304 https://registry.npmjs.org/fill-range
npm http 304 https://registry.npmjs.org/repeat-string
npm http 304 https://registry.npmjs.org/longest
npm ERR! error rolling back Error: EPERM, unlink 'C:\development\workspace\portl
ets\cds-portlets\portlets\node_modules\karma\node_modules\http-proxy\bin\node-ht
tp-proxy'
npm ERR! error rolling back  karma@0.12.37 { [Error: EPERM, unlink 'C:\developme
nt\workspace\portlets\cds-portlets\portlets\node_modules\karma\node_modules\http
-proxy\bin\node-http-proxy']
npm ERR! error rolling back   errno: 50,
npm ERR! error rolling back   code: 'EPERM',
npm ERR! error rolling back   path: 'C:\\development\\workspace\\portlets\\cds-p
ortlets\\portlets\\node_modules\\karma\\node_modules\\http-proxy\\bin\\node-http
-proxy' }
npm ERR! Error: ENOENT, lstat 'C:\development\workspace\portlets\cds-portlets\po
rtlets\node_modules\karma\node_modules\chokidar\node_modules\readdirp\node_modul
es\readable-stream\node_modules\string_decoder\index.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\dev\\nodejs0.10.26\\\\node.exe" "C:\\dev\\nodejs0.10.26\\n
ode_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd C:\development\workspace\portlets\cds-portlets\portlets
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! path C:\development\workspace\portlets\cds-portlets\portlets\node_modul
es\karma\node_modules\chokidar\node_modules\readdirp\node_modules\readable-strea
m\node_modules\string_decoder\index.js
npm ERR! fstream_path C:\development\workspace\portlets\cds-portlets\portlets\no
de_modules\karma\node_modules\chokidar\node_modules\readdirp\node_modules\readab
le-stream\node_modules\string_decoder\index.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack C:\dev\nodejs0.10.26\node_modules\npm\node_modules\fstrea
m\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat 'C:\development\workspace\portlets\cds-portlets\po
rtlets\node_modules\karma\node_modules\connect\node_modules\errorhandler\node_mo
dules\accepts\node_modules\mime-types\node_modules\mime-db\HISTORY.md'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\dev\\nodejs0.10.26\\\\node.exe" "C:\\dev\\nodejs0.10.26\\n
ode_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd C:\development\workspace\portlets\cds-portlets\portlets
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! path C:\development\workspace\portlets\cds-portlets\portlets\node_modul
es\karma\node_modules\connect\node_modules\errorhandler\node_modules\accepts\nod
e_modules\mime-types\node_modules\mime-db\HISTORY.md
npm ERR! fstream_path C:\development\workspace\portlets\cds-portlets\portlets\no
de_modules\karma\node_modules\connect\node_modules\errorhandler\node_modules\acc
epts\node_modules\mime-types\node_modules\mime-db\HISTORY.md
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack C:\dev\nodejs0.10.26\node_modules\npm\node_modules\fstrea
m\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm http GET https://registry.npmjs.org/path-type
npm http GET https://registry.npmjs.org/repeating
npm http GET https://registry.npmjs.org/load-json-file
npm http GET https://registry.npmjs.org/get-stdin
npm http GET https://registry.npmjs.org/minimist/0.0.8
npm http 304 https://registry.npmjs.org/path-type
npm http 304 https://registry.npmjs.org/load-json-file
npm http 304 https://registry.npmjs.org/get-stdin
npm http 304 https://registry.npmjs.org/repeating
npm http 304 https://registry.npmjs.org/minimist/0.0.8
npm http GET https://registry.npmjs.org/pify
npm http GET https://registry.npmjs.org/parse-json
npm http GET https://registry.npmjs.org/strip-bom
npm http 304 https://registry.npmjs.org/pify
npm http 304 https://registry.npmjs.org/parse-json
npm http 304 https://registry.npmjs.org/strip-bom
npm http GET https://registry.npmjs.org/pinkie
npm http 304 https://registry.npmjs.org/pinkie
npm WARN optional dep failed, continuing uglify-js@2.6.1
npm http GET https://registry.npmjs.org/async/0.2.10
npm http GET http://registry.npmjs.org/acorn/-/acorn-1.2.2.tgz
npm http GET http://registry.npmjs.org/acorn-globals/-/acorn-globals-1.0.5.tgz
npm http GET http://registry.npmjs.org/wordwrap/-/wordwrap-0.0.3.tgz
npm http GET http://registry.npmjs.org/uglify-to-browserify/-/uglify-to-browseri
fy-1.0.2.tgz
npm http GET http://registry.npmjs.org/acorn/-/acorn-2.4.0.tgz
npm http GET http://registry.npmjs.org/minimist/-/minimist-0.0.10.tgz
npm http GET http://registry.npmjs.org/yargs/-/yargs-3.5.4.tgz
npm http GET http://registry.npmjs.org/source-map/-/source-map-0.1.34.tgz
npm http 200 http://registry.npmjs.org/wordwrap/-/wordwrap-0.0.3.tgz
npm http 200 http://registry.npmjs.org/acorn/-/acorn-2.4.0.tgz
npm http 200 http://registry.npmjs.org/acorn-globals/-/acorn-globals-1.0.5.tgz
npm http 200 http://registry.npmjs.org/acorn/-/acorn-1.2.2.tgz
npm http 200 http://registry.npmjs.org/uglify-to-browserify/-/uglify-to-browseri
fy-1.0.2.tgz
npm http 200 http://registry.npmjs.org/yargs/-/yargs-3.5.4.tgz
npm http 200 http://registry.npmjs.org/minimist/-/minimist-0.0.10.tgz
npm http 200 http://registry.npmjs.org/source-map/-/source-map-0.1.34.tgz
npm http 304 https://registry.npmjs.org/async/0.2.10
npm http GET http://registry.npmjs.org/css/-/css-1.0.8.tgz
npm http GET http://registry.npmjs.org/promise/-/promise-2.0.0.tgz
npm http GET http://registry.npmjs.org/uglify-js/-/uglify-js-2.2.5.tgz
npm http GET https://registry.npmjs.org/ms/-/ms-0.6.2.tgz
npm http 200 http://registry.npmjs.org/css/-/css-1.0.8.tgz
npm http 200 http://registry.npmjs.org/promise/-/promise-2.0.0.tgz
npm http 200 http://registry.npmjs.org/uglify-js/-/uglify-js-2.2.5.tgz
npm http 200 https://registry.npmjs.org/ms/-/ms-0.6.2.tgz
npm http GET http://registry.npmjs.org/graceful-fs/-/graceful-fs-2.0.3.tgz
npm http GET http://registry.npmjs.org/minimatch/-/minimatch-0.2.14.tgz
npm http 200 http://registry.npmjs.org/minimatch/-/minimatch-0.2.14.tgz
npm http 200 http://registry.npmjs.org/graceful-fs/-/graceful-fs-2.0.3.tgz
npm http GET http://registry.npmjs.org/lodash/-/lodash-2.4.2.tgz
npm http GET https://registry.npmjs.org/abbrev/-/abbrev-1.0.7.tgz
npm http GET https://registry.npmjs.org/commander/-/commander-0.6.1.tgz
npm http GET http://registry.npmjs.org/glob/-/glob-3.2.11.tgz
npm http GET https://registry.npmjs.org/mkdirp/-/mkdirp-0.3.0.tgz
npm http GET http://registry.npmjs.org/grunt-legacy-log-utils/-/grunt-legacy-log
-utils-0.1.1.tgz
npm http GET http://registry.npmjs.org/underscore.string/-/underscore.string-2.3
.3.tgz
npm http GET http://registry.npmjs.org/graceful-fs/-/graceful-fs-1.2.3.tgz
npm http GET http://registry.npmjs.org/inherits/-/inherits-1.0.0.tgz
npm http 200 http://registry.npmjs.org/lodash/-/lodash-2.4.2.tgz
npm http 200 http://registry.npmjs.org/glob/-/glob-3.2.11.tgz
npm http 200 http://registry.npmjs.org/grunt-legacy-log-utils/-/grunt-legacy-log
-utils-0.1.1.tgz
npm http 200 http://registry.npmjs.org/underscore.string/-/underscore.string-2.3
.3.tgz
npm http 200 http://registry.npmjs.org/graceful-fs/-/graceful-fs-1.2.3.tgz
npm http 200 http://registry.npmjs.org/inherits/-/inherits-1.0.0.tgz
npm http 200 https://registry.npmjs.org/abbrev/-/abbrev-1.0.7.tgz
npm http 200 https://registry.npmjs.org/mkdirp/-/mkdirp-0.3.0.tgz
npm http 200 https://registry.npmjs.org/commander/-/commander-0.6.1.tgz
npm http GET http://registry.npmjs.org/core-util-is/-/core-util-is-1.0.1.tgz
npm http GET http://registry.npmjs.org/isarray/-/isarray-0.0.1.tgz
npm http GET http://registry.npmjs.org/string_decoder/-/string_decoder-0.10.31.t
gz
npm http GET http://registry.npmjs.org/argparse/-/argparse-0.1.16.tgz
npm http GET http://registry.npmjs.org/esprima/-/esprima-1.0.4.tgz
npm http GET http://registry.npmjs.org/bson/-/bson-0.3.2.tgz
npm http GET http://registry.npmjs.org/kerberos/-/kerberos-0.0.12.tgz
npm http 200 http://registry.npmjs.org/core-util-is/-/core-util-is-1.0.1.tgz
npm http 200 http://registry.npmjs.org/isarray/-/isarray-0.0.1.tgz
npm http 200 http://registry.npmjs.org/string_decoder/-/string_decoder-0.10.31.t
gz
npm http 200 http://registry.npmjs.org/argparse/-/argparse-0.1.16.tgz
npm http 200 http://registry.npmjs.org/esprima/-/esprima-1.0.4.tgz
npm http 200 http://registry.npmjs.org/bson/-/bson-0.3.2.tgz
npm http 200 http://registry.npmjs.org/kerberos/-/kerberos-0.0.12.tgz
npm ERR! addPlacedTarball Could not unpack "C:\\Users\\dg80222\\AppData\\Roaming
\\npm-cache\\mime-db\\1.13.0\\package.tgz" to "C:\\Users\\dg80222\\AppData\\Roam
ing\\npm-cache\\mime-db\\1.13.0"
npm http GET http://registry.npmjs.org/minimatch/-/minimatch-0.3.0.tgz
npm http 200 http://registry.npmjs.org/minimatch/-/minimatch-0.3.0.tgz
npm http GET http://registry.npmjs.org/acorn/-/acorn-2.4.0.tgz
npm http GET http://registry.npmjs.org/is-promise/-/is-promise-1.0.1.tgz
npm http 200 http://registry.npmjs.org/acorn/-/acorn-2.4.0.tgz
npm http 200 http://registry.npmjs.org/is-promise/-/is-promise-1.0.1.tgz
npm http GET http://registry.npmjs.org/css-parse/-/css-parse-1.0.4.tgz
npm http GET http://registry.npmjs.org/css-stringify/-/css-stringify-1.0.5.tgz
npm http 200 http://registry.npmjs.org/css-parse/-/css-parse-1.0.4.tgz
npm http 200 http://registry.npmjs.org/css-stringify/-/css-stringify-1.0.5.tgz
npm http GET http://registry.npmjs.org/decamelize/-/decamelize-1.0.0.tgz
npm http GET http://registry.npmjs.org/wordwrap/-/wordwrap-0.0.2.tgz
npm http GET http://registry.npmjs.org/ms/-/ms-0.7.1.tgz
npm http GET http://registry.npmjs.org/camelcase/-/camelcase-1.2.1.tgz
npm http GET http://registry.npmjs.org/window-size/-/window-size-0.1.0.tgz
npm http 200 http://registry.npmjs.org/wordwrap/-/wordwrap-0.0.2.tgz
npm http 200 http://registry.npmjs.org/ms/-/ms-0.7.1.tgz
npm http 200 http://registry.npmjs.org/decamelize/-/decamelize-1.0.0.tgz
npm http 200 http://registry.npmjs.org/camelcase/-/camelcase-1.2.1.tgz
npm http 200 http://registry.npmjs.org/window-size/-/window-size-0.1.0.tgz
npm http GET http://registry.npmjs.org/optimist/-/optimist-0.3.7.tgz
npm http 200 http://registry.npmjs.org/optimist/-/optimist-0.3.7.tgz
npm http GET http://registry.npmjs.org/underscore/-/underscore-1.7.0.tgz
npm http GET http://registry.npmjs.org/underscore.string/-/underscore.string-2.4
.0.tgz
npm http 200 http://registry.npmjs.org/underscore/-/underscore-1.7.0.tgz
npm http 200 http://registry.npmjs.org/underscore.string/-/underscore.string-2.4
.0.tgz

> ws@0.4.32 install C:\development\workspace\portlets\cds-portlets\portlets\node
_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules
\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

**Comment by shri3k** [comment]
>npm ERR! node -v v0.10.26
>npm ERR! npm -v 1.4.3

You're better off upgrading your node/npm. Node is in v5 and npm is in v3 right now. I doubt if there's any support for the versions that you're using.

**Comment by ashleygwilliams** [comment]
hi! @shri3k is correct please update your npm to 2 or 3. if you continue to have trouble, please open a new issue.
