### ISSUE TITLE
npm WARN deprecated lodash@0.9.2: lodash@<2.0.0 is no longer maintained. Upgrade to loda     sh@^3.0.0

### ISSUE THREAD

**Issue by jack0624** [npm/npm#11191]
jack@jack-PC MINGW64 /d/testdemo
$ npm install grunt --save-dev
npm WARN deprecated lodash@0.9.2: lodash@<2.0.0 is no longer maintained. Upgrade to loda     sh@^3.0.0
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "grunt" "--save-dev"
npm ERR! node v4.2.2
npm ERR! npm  v3.5.4
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read

npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "grunt" "--save-dev"
npm ERR! node v4.2.2
npm ERR! npm  v3.5.4
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read

npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "grunt" "--save-dev"
npm ERR! node v4.2.2
npm ERR! npm  v3.5.4
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read

npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm WARN saveError ENOENT: no such file or directory, open 'D:\testdemo\package.json'
D:\testdemo
`-- grunt@0.4.5
  +-- async@0.1.22
  +-- coffee-script@1.3.3
  +-- colors@0.6.2
  +-- dateformat@1.0.2-1.2.3
  +-- eventemitter2@0.4.14
  +-- exit@0.1.2
  +-- findup-sync@0.1.3
  | +-- glob@3.2.11
  | | +-- inherits@2.0.1
  | | `-- minimatch@0.3.0
  | `-- lodash@2.4.2
  +-- getobject@0.1.0
  +-- glob@3.1.21
  | +-- graceful-fs@1.2.3
  | `-- inherits@1.0.2
  +-- grunt-legacy-log@0.1.3
  | +-- grunt-legacy-log-utils@0.1.1
  | | +-- lodash@2.4.2
  | | `-- underscore.string@2.3.3
  | +-- lodash@2.4.2
  | `-- underscore.string@2.3.3
  +-- grunt-legacy-util@0.2.0
  +-- hooker@0.2.3
  +-- iconv-lite@0.2.11
  +-- js-yaml@2.0.5
  | +-- argparse@0.1.16
  | | +-- underscore@1.7.0
  | | `-- underscore.string@2.4.0
  | `-- esprima@1.0.4
  +-- lodash@0.9.2
  +-- minimatch@0.2.14
  | +-- lru-cache@2.7.3
  | `-- sigmund@1.0.1
  +-- nopt@1.0.10
  | `-- abbrev@1.0.7
  +-- rimraf@2.2.8
  +-- underscore.string@2.2.1
  `-- which@1.0.9

npm WARN enoent ENOENT: no such file or directory, open 'D:\testdemo\package.json'
npm WARN testdemo No description
npm WARN testdemo No repository field.
npm WARN testdemo No README data
npm WARN testdemo No license field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "grunt" "--save-dev"
npm ERR! node v4.2.2
npm ERR! npm  v3.5.4

npm ERR! Callback called more than once.
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\testdemo\npm-debug.log

**Comment by ashleygwilliams** [comment]
hi! this is a warning that the lodash team chose to show you. you can remove it by updating to the newest version of lodash.

**Comment by ashleygwilliams** [comment]
also, the `ECONNRESET ` refers to your network connection.
