### ISSUE TITLE
Proposal: install modules with version in path + node: require(<module>[, <version>])

### ISSUE THREAD

**Issue by blitmap** [npm/npm#11194]
Recently npm changed to install dependencies in a 'flatter' way.

https://docs.npmjs.com/how-npm-works/npm3

This is just my naive proposal but I'd like to suggest 2 things:

1) Install modules with their version in the path: `node_modules/moment/1.4.8/index.js`
2) Add a 2nd parameter to `require(<module>, <version>)` for requesting a specific semantic version
  - `require('./module')` would be equivalent to: `require('./module', '*')`
    - I've never used `*` in package.json, does it take the latest version or the first it finds?

Note: Modules sometimes change names, so you'd see `node_modules/extendr/1.4.2` and then `node_modules/extendible/1.4.3`.  A later version with a different module name would not go to the same `node_modules/extendr`.

I believe this would make it possible to install all dependencies in the first level of node_modules and allow loading modules like slots.

My reasoning is that if you need a specific version of something it should be reflected in your source code, not just package.json.

This would be making a change to require() which is 'Locked', but because it's an optional 2nd parameter I think it's acceptable to meddle with.  Previously I had thought require('./module', 'a', 'b', 'c') might pass those extra arguments to a module in `arguments` - but it seems not.  Providing a version there would be a non-breaking change.

Side-concern: `npm ls --depth=0` would show all dependencies - not just your 'primary' dependencies.  Some scripts might rely on this.

---

PS: I realize the **1** is node-related, not npm-related.  I'm proposing this with the full text in both projects for completeness/coherency.

**Comment by KenanY** [comment]
ref. https://github.com/nodejs/NG/issues/28

**Comment by othiym23** [comment]
Closing in favor of nodejs/NG#28, because any changes along these lines would need to be made to Node's module resolution algorithm first. Fair warning: this is unlikely to happen, because the module spec is pretty locked down.

**Comment by blitmap** [comment]
I was actually thinking about taking a look at that.  Theoretically it would be possible to support the 'old' way and the 'new' way: `node_modules/moment/1.4.2/...`

Basically if the module directory exists in `node_modules` but `package.json` doesn't exist 1-level within that it would assume the flatter install method I'm envisioning.

By default projects would assume the 'old' directory structure unless `package.json` specifies the new one.  (new projects created with `npm init` would insert something in `package.json` to enable this)

Anyway, more dreaming I suppose.. I understand the importance of locked specs.  The only reason corporations build against open-source software is if they can trust it not to change too quickly, or provide some support over the long-term.  Node has been advancing quite quickly upon pulling in io.js - I hope something like this can be possible.  IMO it's very important to get this right and not live with it for another half-decade...
