### ISSUE TITLE
npm install git+ssh --save does not save path used

### ISSUE THREAD

**Issue by eurochriskelly** [npm/npm#11192]
using npm (3.3.10) on windows 10

running ```npm install --save git+ssh://github.com/username/repo.git``` installs the package correctly in 
node_modules.

However, package json contains 
```
"dependencies" : {
    "repo" : "ssh://github.com/username/repo.git"
}
``` 

This breaks the package.json and nothing can install. Error:

"Unsupported URL Type : ssh://github.com/username/repo.git"

Manually adding "git+" fixes the issue. 

Is there a way to ensure entry gets added correctly to package.json?

**Comment by mveenman** [comment]
Same goes for npm 3.5.1 on window 8.1

**Comment by sebastianjonasson** [comment]
Yeah, got the same issue. Downloads package but does not save to package.json.

osx el captian 10.11.1

**Comment by olegman** [comment]
Same goes for npm 3.5.3 on osx el captian 10.11.2, fix please

**Comment by KenanY** [comment]
Is this a duplicate of https://github.com/npm/npm/issues/9679?

**Comment by eurochriskelly** [comment]
Yes. I see it is. Sorry I didn't see it before posting.
