### ISSUE TITLE
authenticating error

### ISSUE THREAD

**Issue by Moymee** [npm/npm#11197]
Hello to all,
This is my debug log
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'adduser' ]
2 info using npm@2.14.12
3 info using node@v4.2.4
4 warn Username must be lowercase
5 verbose adduser before first PUT { _id: 'org.couchdb.user:moises',
5 verbose adduser   name: 'moises',
5 verbose adduser   password: 'XXXXX',
5 verbose adduser   email: 'itmodelfont82@outlook.com',
5 verbose adduser   type: 'user',
5 verbose adduser   roles: [],
5 verbose adduser   date: '2016-01-18T18:33:24.495Z' }
6 verbose request uri https://registry.npmjs.org/-/user/org.couchdb.user:moises
7 verbose request new user, so can't send auth
8 info attempt registry request try #1 at 10:33:24 AM
9 verbose request id 21cacab8c06dce23
10 http request PUT https://registry.npmjs.org/-/user/org.couchdb.user:moises
11 http 400 https://registry.npmjs.org/-/user/org.couchdb.user:moises
12 verbose headers { 'content-type': 'application/json',
12 verbose headers   'cache-control': 'max-age=300',
12 verbose headers   'content-length': '57',
12 verbose headers   'accept-ranges': 'bytes',
12 verbose headers   date: 'Mon, 18 Jan 2016 18:33:22 GMT',
12 verbose headers   via: '1.1 varnish',
12 verbose headers   connection: 'keep-alive',
12 verbose headers   'x-served-by': 'cache-sjc3125-SJC',
12 verbose headers   'x-cache': 'MISS',
12 verbose headers   'x-cache-hits': '0',
12 verbose headers   'x-timer': 'S1453142002.344467,VS0,VE165' }
13 verbose request invalidating C:\Users\Owner.DESKTOP-UED4GGL\AppData\Roaming\npm-cache\registry.npmjs.org\-\user\org.couchdb.user_3Amoises on PUT
14 verbose adduser back [ { [Error: Unknown error while authenticating : -/user/org.couchdb.user:moises] statusCode: 400, code: 'E400' },
14 verbose adduser   { ok: false, error: 'Unknown error while authenticating' },
14 verbose adduser   '{"ok":false,"error":"Unknown error while authenticating"}' ]
15 verbose stack Error: Unknown error while authenticating : -/user/org.couchdb.user:moises
15 verbose stack     at makeError (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:264:12)
15 verbose stack     at CachingRegistryClient.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:252:14)
15 verbose stack     at Request._callback (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:172:14)
15 verbose stack     at Request.self.callback (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\request.js:198:22)
15 verbose stack     at emitTwo (events.js:87:13)
15 verbose stack     at Request.emit (events.js:172:7)
15 verbose stack     at Request.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\request.js:1082:10)
15 verbose stack     at emitOne (events.js:82:20)
15 verbose stack     at Request.emit (events.js:169:7)
15 verbose stack     at IncomingMessage.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\request.js:1009:12)
16 verbose statusCode 400
17 verbose cwd C:\
18 error Windows_NT 10.0.10586
19 error argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "adduser"
20 error node v4.2.4
21 error npm  v2.14.12
22 error code E400
23 error Unknown error while authenticating : -/user/org.couchdb.user:moises
24 error If you need help, you may report this error at:
24 error     <https://github.com/npm/npm/issues>
25 verbose exit [ 1, true ]

thank you.
Moe

**Comment by RobertJGabriel** [comment]
Same here

**Comment by KenanY** [comment]
@Moymee Are you still seeing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
