### ISSUE TITLE
Any use of autocomplete via TAB causes npm to crash.

### ISSUE THREAD

**Issue by SimonSchick** [npm/npm#11199]
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/5.4.1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'completion',
1 verbose cli   '--' ]
2 info using npm@3.3.12
3 info using node@v5.4.1
4 verbose stack TypeError: Cannot read property 'length' of undefined
4 verbose stack     at EventEmitter.completion (/usr/local/lib/node_modules/npm/lib/completion.js:79:22)
4 verbose stack     at Object.commandCache.(anonymous function) (/usr/local/lib/node_modules/npm/lib/npm.js:214:13)
4 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:74:30)
4 verbose stack     at nextTickCallbackWith0Args (node.js:452:9)
4 verbose stack     at process._tickCallback (node.js:381:13)
5 verbose cwd /Users/****/Documents/Projects/esprintf
6 error Darwin 15.2.0
7 error argv "/usr/local/Cellar/node/5.4.1/bin/node" "/usr/local/bin/npm" "completion" "--"
8 error node v5.4.1
9 error npm  v3.3.12
10 error Cannot read property 'length' of undefined
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```

OS: ```Darwin ****** 15.2.0 Darwin Kernel Version 15.2.0: Fri Nov 13 19:56:56 PST 2015; root:xnu-3248.20.55~2/RELEASE_X86_64 x86_64```

**Comment by SimonSchick** [comment]
Please mind, I did reinstall node and npm completely, I also tried the latest npm version (3.5.3) which has the same problem.

**Comment by ashleygwilliams** [comment]
hi! per the docs: https://docs.npmjs.com/cli/completion

you need to type:
- `source <(npm completion)`, or
- `npm completion >> ~/.bashrc`

your error message inidicates that you typed `npm completion --`, which is invalid

please try the docs suggestions. if you continue to have trouble, please file another issue.

**Comment by SimonSchick** [comment]
Ah, many thanks. I'd suggest catching this sort of thing and give a slightly more helpful error message.

**Comment by ashleygwilliams** [comment]
we are working on making more helpful error messages all across npm features :) we def agree it can be better. all in good time!
