### ISSUE TITLE
If shrinkwrapped dev dependencies no clean way to update

### ISSUE THREAD

**Issue by designfrontier** [npm/npm#11198]
`--save-dev` doesn't seem to update the shrinkwrap.json file even if it was generated with the `--dev` flag. Running version `2.14.9` on OS X 10.11.2 with node version `0.12.9`

**Comment by aldendaniels** [comment]
:+1: NPM@3 auto-updates the `npm-shrinkwrap.json` when `npm install xyz --save` is run. 

If the shrinkwrap file was created using ` npm shrinkwrap --also=dev` then ideally `npm install xyz --save-dev` would similarly update `npm-shrinkwrap.json`.

**Comment by cedrics** [comment]
:+1: Having the same issue. We had to add a `shrinkwrap.json` so our CI wouldn't constantly have issues because of some dependency update breaking our tests.
