### ISSUE TITLE
Encrypted password in proxy configuration settings

### ISSUE THREAD

**Issue by jbfm21** [npm/npm#11209]
Hello, 

I need to run the NPM on Windows behind authentication proxy on Windows, i know that i can configure the .npmrc file with proxy configuration like that:

```
https-proxy=http://user:pass@proxy.company:8080
http-proxy=http://user:pass@proxy.company:8080
```

but i don´t want to put my password in plain text format because is a security issue/risk, even when stored in my User Profile folder, and i can´t  use a local Proxy CNTLM.

Is there an alternative solution to configure the proxy credentials with encrypted password ?

**Comment by shri3k** [comment]
One thing you can do (if it's a shared computer) is that you can just export it your current session without saving it in `.npmrc` but I don't think this is specific to npm I see it being done on git and other tools too. Others might have some different ideas.

**Comment by jbfm21** [comment]
Hello, 

thanks, exporting it to my current session is a good workahound, but i will be glad if NPM have the same functionality of Nuget, or Maven (have a master key defined by user that is used to encrypt passwords)

    Proxy settings
    section: config
    keys: http_proxy, http_proxy.user and http_proxy.password

    Allows you to set the proxy settings to be used while connecting to your NuGet feed. More details here.

    This key can be added using NuGet.exe Config -Set command.

    It can also be set via environment variable http_proxy. While setting env variable, the value should be specified in the format http://[username]:[password]@proxy.com.

    Note
    The "http_proxy.password" key value is encrypted before storing in the nuget.config file. Hence it can      not be added manually by directly updating the config file.
