### ISSUE TITLE
npm-shrinkwrap.json merge conflict

### ISSUE THREAD

**Issue by lifehackett** [npm/npm#11205]
I am updating my branch with the latest changes from `master`.  I get a merge conflict on `npm-shrinkwrap.json`, but I am not sure how to go about resolving the conflict since it is an auto-generated file.

How do I resolve the conflicts?

Thanks

**Comment by romainPrignon** [comment]
My take on this is:
 - take npm-shrinkwrap.json
 - npm install
 - npm update (every packages that change in 'my branch')
 - npm shrinkwrap
 it should be resolved

**Comment by jaredbeck** [comment]
I think this issue can be closed. It is a request for help with git, not an npm issue.
