### ISSUE TITLE
Problems installing Jeet with npm...

### ISSUE THREAD

**Issue by scottkoons** [npm/npm#11208]
I am running El Capitan v. 10.11.3 Beta (15D9c) and I am having problems installing various repositories using CLI.  Most recently, I am trying to install Jeet.  When I run the following command: sudo npm install -g stylus jeet (this is what it says to run on their website), I get a host of errors, but the first one is: npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "stylus" "jeet"

I'm new to CLI and the whole git communitiy, so hopefully I am just doing something dumb that is an easy fix.  Attached is the npm error log.

Thanks for any help.

-Scott

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'stylus',
1 verbose cli   'jeet' ]
2 info using npm@3.3.12
3 info using node@v5.4.1
4 verbose stack Error: Cannot find module 'github-url-from-git'
4 verbose stack     at Function.Module._resolveFilename (module.js:325:15)
4 verbose stack     at Function.Module._load (module.js:276:25)
4 verbose stack     at Module.require (module.js:353:17)
4 verbose stack     at require (internal/module.js:12:17)
4 verbose stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:2:22)
4 verbose stack     at Module._compile (module.js:397:26)
4 verbose stack     at Object.Module._extensions..js (module.js:404:10)
4 verbose stack     at Module.load (module.js:343:32)
4 verbose stack     at Function.Module._load (module.js:300:12)
4 verbose stack     at Module.require (module.js:353:17)
4 verbose stack     at require (internal/module.js:12:17)
5 verbose cwd /Users/scottkoons/Desktop/JEET
6 error Darwin 15.3.0
7 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "stylus" "jeet"
8 error node v5.4.1
9 error npm  v3.3.12
10 error code MODULE_NOT_FOUND
11 error Cannot find module 'github-url-from-git'
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]

**Comment by ashleygwilliams** [comment]
hi! this is an issue that was fixed in npm `3.5.5`. could you update your npm and try again? if you continue to have trouble, please file a new issue.
