### ISSUE TITLE
issue while installing jsreport in Linux

### ISSUE THREAD

**Issue by cbmadhu** [npm/npm#11203]
I'm facing below issue while install jsreport via npm in Linux machine. Can you please guide on this.
Current Node version is : 5.4.1
Current NPM version is : 3.3.12

npm ERR! fetch failed https://github.com/rase-/node-XMLHttpRequest/archive/a6b6f2.tar.gz
loadDep:xmlhttprequest    â
npm ERR! Linux 2.6.32-573.3.1.el6.x86_64
npm ERR! argv "/usr/local/node/node-v5.4.1-linux-x64/bin/node" "/usr/local/node/node-v5.4.1-linux-x64/bin/npm" "install" "jsreport"
npm ERR! node v5.4.1
npm ERR! npm  v3.3.12
npm ERR! code UNABLE_TO_GET_ISSUER_CERT_LOCALLY

npm ERR! unable to get local issuer certificate
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/nodespace/npm-debug.log

**Comment by KenanY** [comment]
@cbmadhu Are you still experiencing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
