### ISSUE TITLE
Cannot find module 'read-package-json'

### ISSUE THREAD

**Issue by bsdfzzzy** [npm/npm#11217]
npm init
npm ERR! Linux 3.19.0-43-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "init"
npm ERR! node v5.4.1
npm ERR! npm  v3.5.4
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'read-package-json'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/zzy/home/zzy/public/node/myapp/npm-debug.log

**Comment by niksrc** [comment]
Try installing the module read-package-json globally
```npm install -g read-package-json ```.
It should work.

**Comment by ashleygwilliams** [comment]
@niksrc's advice is sound. i am going to close this issue. @bsdfzzzy if you continue to have trouble, please file a new issue.

**Comment by bsdfzzzy** [comment]
@niksrc Thanks, I had tried that method but not work.And now I find the problem is 'root' and 'not root' user in linux.So much thanks. @ashleygwilliams Okey, thanks.
