### ISSUE TITLE
Unable to install react 

### ISSUE THREAD

**Issue by Tushki87** [npm/npm#11211]
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/Cellar/node/4.2.1/bin/node" "/Users/tushar/.npm-packages/bin/npm" "install" "--save" "react" "react-dom"
npm ERR! node v4.2.1
npm ERR! npm  v3.3.9
npm ERR! code ENOSELF

npm ERR! Refusing to install react as a dependency of itself

npm-debug.log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/4.2.1/bin/node',
1 verbose cli   '/Users/tushar/.npm-packages/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   'react',
1 verbose cli   'react-dom' ]
2 info using npm@3.3.9
3 info using node@v4.2.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData react
8 silly fetchPackageMetaData react-dom
9 silly fetchNamedPackageData react
10 silly mapToRegistry name react
11 silly mapToRegistry using default registry
12 silly mapToRegistry registry https://registry.npmjs.org/
13 silly mapToRegistry uri https://registry.npmjs.org/react
14 silly fetchNamedPackageData react-dom
15 silly mapToRegistry name react-dom
16 silly mapToRegistry using default registry
17 silly mapToRegistry registry https://registry.npmjs.org/
18 silly mapToRegistry uri https://registry.npmjs.org/react-dom
19 verbose request uri https://registry.npmjs.org/react-dom
20 verbose request no auth needed
21 info attempt registry request try #1 at 1:56:14 PM
22 verbose request id b86f3ba08006c4f9
23 verbose etag "4P6RMJ035S3KIP9V9JMK4524Y"
24 http request GET https://registry.npmjs.org/react-dom
25 verbose request uri https://registry.npmjs.org/react
26 verbose request no auth needed
27 info attempt registry request try #1 at 1:56:14 PM
28 verbose etag "62YKH1RA8R5PYS7EM0IF3ZWOP"
29 http request GET https://registry.npmjs.org/react
30 http 304 https://registry.npmjs.org/react
31 verbose headers { date: 'Tue, 19 Jan 2016 21:56:13 GMT',
31 verbose headers   via: '1.1 varnish',
31 verbose headers   'cache-control': 'max-age=300',
31 verbose headers   etag: '"62YKH1RA8R5PYS7EM0IF3ZWOP"',
31 verbose headers   age: '146',
31 verbose headers   connection: 'keep-alive',
31 verbose headers   'x-served-by': 'cache-sjc3120-SJC',
31 verbose headers   'x-cache': 'HIT',
31 verbose headers   'x-cache-hits': '3',
31 verbose headers   'x-timer': 'S1453240573.597532,VS0,VE0',
31 verbose headers   vary: 'Accept' }
32 silly get cb [ 304,
32 silly get   { date: 'Tue, 19 Jan 2016 21:56:13 GMT',
32 silly get     via: '1.1 varnish',
32 silly get     'cache-control': 'max-age=300',
32 silly get     etag: '"62YKH1RA8R5PYS7EM0IF3ZWOP"',
32 silly get     age: '146',
32 silly get     connection: 'keep-alive',
32 silly get     'x-served-by': 'cache-sjc3120-SJC',
32 silly get     'x-cache': 'HIT',
32 silly get     'x-cache-hits': '3',
32 silly get     'x-timer': 'S1453240573.597532,VS0,VE0',
32 silly get     vary: 'Accept' } ]
33 verbose etag https://registry.npmjs.org/react from cache
34 verbose get saving react to /Users/tushar/.npm/registry.npmjs.org/react/.cache.json
35 http 304 https://registry.npmjs.org/react-dom
36 verbose headers { date: 'Tue, 19 Jan 2016 21:56:13 GMT',
36 verbose headers   via: '1.1 varnish',
36 verbose headers   'cache-control': 'max-age=300',
36 verbose headers   etag: '"4P6RMJ035S3KIP9V9JMK4524Y"',
36 verbose headers   age: '204',
36 verbose headers   connection: 'keep-alive',
36 verbose headers   'x-served-by': 'cache-sjc3135-SJC',
36 verbose headers   'x-cache': 'HIT',
36 verbose headers   'x-cache-hits': '2',
36 verbose headers   'x-timer': 'S1453240573.598076,VS0,VE0',
36 verbose headers   vary: 'Accept' }
37 silly get cb [ 304,
37 silly get   { date: 'Tue, 19 Jan 2016 21:56:13 GMT',
37 silly get     via: '1.1 varnish',
37 silly get     'cache-control': 'max-age=300',
37 silly get     etag: '"4P6RMJ035S3KIP9V9JMK4524Y"',
37 silly get     age: '204',
37 silly get     connection: 'keep-alive',
37 silly get     'x-served-by': 'cache-sjc3135-SJC',
37 silly get     'x-cache': 'HIT',
37 silly get     'x-cache-hits': '2',
37 silly get     'x-timer': 'S1453240573.598076,VS0,VE0',
37 silly get     vary: 'Accept' } ]
38 verbose etag https://registry.npmjs.org/react-dom from cache
39 verbose get saving react-dom to /Users/tushar/.npm/registry.npmjs.org/react-dom/.cache.json
40 silly install normalizeTree
41 silly loadCurrentTree Finishing
42 silly loadIdealTree Starting
43 silly install loadIdealTree
44 silly cloneCurrentTree Starting
45 silly install cloneCurrentTreeToIdealTree
46 silly cloneCurrentTree Finishing
47 silly loadShrinkwrap Starting
48 silly install loadShrinkwrap
49 silly loadShrinkwrap Finishing
50 silly loadAllDepsIntoIdealTree Starting
51 silly install loadAllDepsIntoIdealTree
52 silly rollbackFailedOptional Starting
53 silly rollbackFailedOptional Finishing
54 silly runTopLevelLifecycles Starting
55 silly runTopLevelLifecycles Finishing
56 silly install printInstalled
57 verbose stack Error: Refusing to install react as a dependency of itself
57 verbose stack     at checkSelf (/Users/tushar/.npm-packages/lib/node_modules/npm/lib/install/validate-args.js:40:14)
57 verbose stack     at Array.<anonymous> (/Users/tushar/.npm-packages/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
57 verbose stack     at LOOP (/Users/tushar/.npm-packages/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
57 verbose stack     at chain (/Users/tushar/.npm-packages/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
57 verbose stack     at /Users/tushar/.npm-packages/lib/node_modules/npm/lib/install/validate-args.js:15:5
57 verbose stack     at /Users/tushar/.npm-packages/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
57 verbose stack     at Array.forEach (native)
57 verbose stack     at /Users/tushar/.npm-packages/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
57 verbose stack     at Array.forEach (native)
57 verbose stack     at asyncMap (/Users/tushar/.npm-packages/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
58 verbose cwd /Users/tushar/Desktop/Node_ElasticSearch/React
59 error Darwin 15.3.0
60 error argv "/usr/local/Cellar/node/4.2.1/bin/node" "/Users/tushar/.npm-packages/bin/npm" "install" "--save" "react" "react-dom"
61 error node v4.2.1
62 error npm  v3.3.9
63 error code ENOSELF
64 error Refusing to install react as a dependency of itself
65 error If you need help, you may report this error at:
65 error     <https://github.com/npm/npm/issues>
66 verbose exit [ 1, true ]

**Comment by shri3k** [comment]
Check your `package.json`. I'm pretty sure your `package.json` has it's name as `react` which is why you're getting this error. Name your directory something else or rename it in `package.json`.

**Comment by ashleygwilliams** [comment]
hi! @shri3k's advice is sound. i am closing this issue. @Tushki87 please open a new issue if you continue to have trouble.
