### ISSUE TITLE
When moving bin files between global versions, Maximum call stack size exceeded

### ISSUE THREAD

**Issue by natew** [npm/npm#11214]
I put the details in here:

https://gist.github.com/natew/2931e46df9b5c003ac40

Steps to reproduce:

```
npm install -g flint@1.3.133
npm install -g flint
```

Affects a fair portion of our early users, we're getting a lot of help requests in our chat mostly because the error message is confusing.

Related to https://github.com/npm/npm/issues/9633

**Comment by othiym23** [comment]
This is still an issue, and still results in a broken install of `flint`, but as of `npm@3.7.4`, is no longer crashing with a `Maximum call stack size exceeded` error – the `ENOENT` errors are still there, though. Either way, this should be addressed as part of the CLI team's `big-bug` pass, which will be happening after the test rewrite project completes.

**Comment by zkat** [comment]
@natew can you try this on the latest version of npm and tell us if it's still a problem for you? I can't reproduce this.
