### ISSUE TITLE
 Error: No compatible version found: path-is-absolute@'^1.0.0'

### ISSUE THREAD

**Issue by jvopalensky** [npm/npm#11221]
After running "npm install" in my older repo, all looked fine except this error:

npm ERR! Error: No compatible version found: path-is-absolute@'^1.0.0'
npm ERR! Valid install targets:
npm ERR! ["1.0.0"]
npm ERR!     at installTargetsError (C:\Program Files\nodejs\node_modules\npm\lib\cache.js:563:10)
npm ERR!     at C:\Program Files\nodejs\node_modules\npm\lib\cache.js:478:10
npm ERR!     at saved (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\get.js:138:7)
npm ERR!     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:218:7
npm ERR!     at Object.oncomplete (fs.js:297:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"

npm ERR! cwd C:\Projects\pusher
npm ERR! node -v v0.8.15
npm ERR! npm -v 1.1.66

More details are in the attached npm-debug.log.
[npm-debug.log.txt](https://github.com/npm/npm/files/97865/npm-debug.log.txt)

**Comment by KenanY** [comment]
@jvopalensky Your versions of node and `npm` are several years old. Please, try updating first.

**Comment by jvopalensky** [comment]
OK thanks @KenanY I see that. But can I upgrade npm without upgrading node?

FYI - I ask because we have other parts of our code that depend on the older version of node, and I am trying to localize my changes only to one repo project (the "pusher" project).

**Comment by othiym23** [comment]
@jvopalensky You're in luck! npm supports Node.js 0.8, although we haven't tested it with anything as old as 0.8.15. It's worth at least a try.

If that doesn't work, unfortunately, you're on your own – `npm@1` is EOL and `npm@1.1` has been unsupported for years.

As the underlying issue is the old version of npm's lack of support for the `^` semver range operator, and this is fixed by upgrading to a newer npm, I'm going to close this issue. Good luck getting things sorted out!

**Comment by jvopalensky** [comment]
Thanks @othiym23 - I am trying to upgrade npm now, but get more errors (about to create to issue#)
