### ISSUE TITLE
error code ENOSELF

### ISSUE THREAD

**Issue by MAimmersivX** [npm/npm#11224]
Steps taken:
1. turned off firewall
2. cleared npm cache
3. npm version 3.3.12

When I try 

npm install terriajs

I get the attached error

[npm-debug.txt](https://github.com/npm/npm/files/98591/npm-debug.txt)

**Comment by KenanY** [comment]
@MAimmersivX Hello, sorry for the late response. Is the `"name"` attribute of your `package.json` set to `"terriajs"`? Have you tried changing it to something else?

**Comment by KenanY** [comment]
Closing as abandoned.
