### ISSUE TITLE
npm install <pkg> --save-exact doesn't update package.json

### ISSUE THREAD

**Issue by vicneanschi** [npm/npm#11229]
I'm running npm 3.5.3  and node  v0.10.33 on Windows 7 Professional

`npm install mkdirp --save-exact`

`--save-exact`  option doesn't update package.json
`--save`   works fine

**Comment by MarcDiethelm** [comment]
I can confirm this. 
```
$ npm -v
3.8.1
$ node -v
v4.4.0
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.11.3
```

**Comment by vicneanschi** [comment]
I realized that **--save-exact** must be used with **--save**

So the correct command would be:
**npm install mkdirp --save --save-exact**
