### ISSUE TITLE
npm phonegap install fails due to long path

### ISSUE THREAD

**Issue by hschop** [npm/npm#11228]
I'm trying to install phonegap CLI on Windows 8.1
I tried this several times
Updated my PATH, rebooted
Cleared npm cache
Ran cmd as admin
Also tried from a nodejs cmd
Tried a normal install and a global install
It keeps giving an error that the fully qualified path is to long, and I can imagine, because it is ridiculously long...

See screenshot and log file from a (none admin) cmd:

![phonegap install problems](https://cloud.githubusercontent.com/assets/16819402/12482650/1533bce8-c051-11e5-98f8-851649f22750.png)

[npm-debug.txt](https://github.com/npm/npm/files/99219/npm-debug.txt)

**Comment by Henning256** [comment]
Same here! (Win7 x64)
My Username is 10 characters long.
On another machine it worked (Win10 x64) the same version worked.
First i thought it was the 2 characters shorter username but as your username is only 6 chracters long it seems, als Win 10 handles this better than Win7.
