### ISSUE TITLE
Unable to upgrade npm from v.1.1.66 to latest version (on Windows 8)

### ISSUE THREAD

**Issue by jvopalensky** [npm/npm#11222]
After issuing the command "npm install npm -g" from my node,js command console, I received following errors:

npm http 200 https://registry.npmjs.org/npm/-/npm-3.5.3.tgz
npm ERR! tar pack Error reading D:\Temp\npm-16796\1453316151980-0.30867724982090294\package
npm ERR! TypeError: Cannot call method 'filter' of undefined
npm ERR!     at Packer.IgnoreReader.addIgnoreRules (C:\Program Files\nodejs\node_modules\npm\node_modules\fstream-npm\node_modules
\fstream-ignore\ignore.js:148:13)
npm ERR!     at Packer.IgnoreReader.addIgnoreFile (C:\Program Files\nodejs\node_modules\npm\node_modules\fstream-npm\node_modules\
fstream-ignore\ignore.js:133:10)
npm ERR!     at fs.readFile (fs.js:176:14)
npm ERR!     at fs.close (C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:90:5)
npm ERR!     at Object.oncomplete (fs.js:297:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
 "npm" "-g"
npm ERR! cwd C:\Projects\pusher
npm ERR! node -v v0.8.15
npm ERR! npm -v 1.1.66
npm ERR! type non_object_property_call
npm ERR! addLocalDirectory Could not pack "D:\\Temp\\npm-16796\\1453316151980-0.30867724982090294\\package" to "C:\\Users\\jan\\Ap
pData\\Roaming\\npm-cache\\npm\\3.5.3\\package.tgz"
npm ERR! SyntaxError: Unexpected end of input
npm ERR!     at Object.parse (native)
npm ERR!     at Packer.readRules (C:\Program Files\nodejs\node_modules\npm\node_modules\fstream-npm\fstream-npm.js:189:33)
npm ERR!     at Packer.IgnoreReader.addIgnoreFile (C:\Program Files\nodejs\node_modules\npm\node_modules\fstream-npm\node_modules\
fstream-ignore\ignore.js:132:22)
npm ERR!     at fs.readFile (fs.js:176:14)
npm ERR!     at fs.close (C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:90:5)
npm ERR!     at Object.oncomplete (fs.js:297:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
 "npm" "-g"
npm ERR! cwd C:\Projects\pusher
npm ERR! node -v v0.8.15
npm ERR! npm -v 1.1.66
npm ERR! file D:\Temp\npm-16796\1453316151980-0.30867724982090294\package\node_modules\read-package-tree\test\fixtures\bad\package
.json
npm ERR! path D:\Temp\npm-16796\1453316151980-0.30867724982090294\package\node_modules\read-package-tree\test\fixtures\bad
npm ERR! type unexpected_eos
npm ERR! fstream_path D:\Temp\npm-16796\1453316151980-0.30867724982090294\package\node_modules\read-package-tree\test\fixtures\bad

npm ERR! fstream_type Directory
npm ERR! fstream_class Packer
npm ERR! fstream_stack Packer.readRules (C:\Program Files\nodejs\node_modules\npm\node_modules\fstream-npm\fstream-npm.js:192:10)
npm ERR! fstream_stack Packer.IgnoreReader.addIgnoreFile (C:\Program Files\nodejs\node_modules\npm\node_modules\fstream-npm\node_m
odules\fstream-ignore\ignore.js:132:22)
npm ERR! fstream_stack fs.readFile (fs.js:176:14)
npm ERR! fstream_stack fs.close (C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:90:5)
npm ERR! fstream_stack Object.oncomplete (fs.js:297:15)
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Projects\pusher\npm-debug.log
npm ERR! not ok code 0

NOTE: If you want, I can attach the npm-debug.log. But I suspect the above error messages should suffice.

**Comment by jvopalensky** [comment]
I tried this command "npm install npm -g" again after clearing the npm-debug.log.
As expected, same issue. But now you can see better all the errors in the log file.
[npm-debug.log2.txt](https://github.com/npm/npm/files/97964/npm-debug.log2.txt)

**Comment by KenanY** [comment]
@jvopalensky Hmm, how about?:

```
npm install -g npm@1.4
npm install -g npm
```

(I am guessing that `npm@3` is _so_ different that you cannot go straight there from `npm@1.1`)

**Comment by othiym23** [comment]
Either try what @KenanY suggests or try the [Windows upgrade script for npm](https://www.npmjs.com/package/npm-windows-upgrade) from Microsoft. As I said elsewhere, though, if those don't work, there's not a lot more we can do for you. Node 0.8.15 and npm 1.1 are over three years old at this point, and much has changed since then.

**Comment by jvopalensky** [comment]
Thanks @KenanY. Your suggestion worked - esp. the first upgrade to 1.4.  

But I had to use "npm -g install npm@latest" for the final upgrade (from an admin elevated Windows prompt console) since I was getting the following warnings:

> npm WARN deprecated This version of npm lacks support for important features,
> npm WARN deprecated such as scoped packages, offered by the primary npm
> npm WARN deprecated registry. Consider upgrading to at least npm@2, if not the
npm WARN deprecated latest stable version. To upgrade to npm@2, run:
npm WARN deprecated
npm WARN deprecated   npm -g install npm@latest-2
npm WARN deprecated
npm WARN deprecated To upgrade to the latest stable version, run:
npm WARN deprecated
npm WARN deprecated   npm -g install npm@latest
npm WARN deprecated
npm WARN deprecated (Depending on how Node.js was installed on your system, you
npm WARN deprecated may need to prefix the preceding commands with `sudo`, or if
npm WARN deprecated on Windows, run them from an Administrator prompt.)
npm WARN deprecated
npm WARN deprecated If you're running the version of npm bundled with
npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
npm WARN deprecated will be bundled with a version of npm@2, which has some small
npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
npm WARN deprecated semver behavior.
C:\Program Files\nodejs\npm -> C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js
npm@3.5.3 C:\Program Files\nodejs\node_modules\npm


Now npm -v shows 3.5.3.

**Comment by KenanY** [comment]
@jvopalensky Enjoy `npm@3` :)
