### ISSUE TITLE
Use package.yaml instead of package.json

### ISSUE THREAD

**Issue by fabriziogiordano** [npm/npm#11230]
It would be nice to add **comments** in the package.json

Since json does not support comments it might be nice to use some other configuration formats.

**Yaml** is quite simple to pick up and quite popular alternative.

**Comment by KenanY** [comment]
https://github.com/npm/npm/issues/3336, https://github.com/npm/npm/issues/5901

**Comment by othiym23** [comment]
Closing as duplicate / not something the CLI team is going to do. Thanks for your time!

**Comment by BevanR** [comment]
Oh, bummer. :(
