### ISSUE TITLE
Invalid name: "@exponent/react-native-navigator" (npm@3.3.12)

### ISSUE THREAD

**Issue by zentuit** [npm/npm#11238]
I'm trying to install "react-native-router-flux" but it fails with Invalid name: "@exponent/react-native-navigator"

Here is the verbose npm-debug.log:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'i',
1 verbose cli   'react-native-router-flux',
1 verbose cli   '--save' ]
2 info using npm@3.3.12
3 info using node@v5.4.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData react-native-router-flux
8 silly fetchNamedPackageData react-native-router-flux
9 silly mapToRegistry name react-native-router-flux
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/react-native-router-flux
13 verbose request uri https://registry.npmjs.org/react-native-router-flux
14 verbose request no auth needed
15 info attempt registry request try #1 at 4:32:54 PM
16 verbose request id 73a91b0413d9fc05
17 verbose etag "5SFNTNFP3986P9LAY1Q8Q4R6E"
18 http request GET https://registry.npmjs.org/react-native-router-flux
19 http 304 https://registry.npmjs.org/react-native-router-flux
20 verbose headers { date: 'Thu, 21 Jan 2016 21:32:54 GMT',
20 verbose headers   via: '1.1 varnish',
20 verbose headers   'cache-control': 'max-age=300',
20 verbose headers   etag: '"5SFNTNFP3986P9LAY1Q8Q4R6E"',
20 verbose headers   age: '0',
20 verbose headers   connection: 'keep-alive',
20 verbose headers   'x-served-by': 'cache-jfk1037-JFK',
20 verbose headers   'x-cache': 'HIT',
20 verbose headers   'x-cache-hits': '1',
20 verbose headers   'x-timer': 'S1453411974.507158,VS0,VE94',
20 verbose headers   vary: 'Accept' }
21 silly get cb [ 304,
21 silly get   { date: 'Thu, 21 Jan 2016 21:32:54 GMT',
21 silly get     via: '1.1 varnish',
21 silly get     'cache-control': 'max-age=300',
21 silly get     etag: '"5SFNTNFP3986P9LAY1Q8Q4R6E"',
21 silly get     age: '0',
21 silly get     connection: 'keep-alive',
21 silly get     'x-served-by': 'cache-jfk1037-JFK',
21 silly get     'x-cache': 'HIT',
21 silly get     'x-cache-hits': '1',
21 silly get     'x-timer': 'S1453411974.507158,VS0,VE94',
21 silly get     vary: 'Accept' } ]
22 verbose etag https://registry.npmjs.org/react-native-router-flux from cache
23 verbose get saving react-native-router-flux to /Users/Tom/.npm/registry.npmjs.org/react-native-router-flux/.cache.json
24 silly install normalizeTree
25 silly loadCurrentTree Finishing
26 silly loadIdealTree Starting
27 silly install loadIdealTree
28 silly cloneCurrentTree Starting
29 silly install cloneCurrentTreeToIdealTree
30 silly cloneCurrentTree Finishing
31 silly loadShrinkwrap Starting
32 silly install loadShrinkwrap
33 silly loadShrinkwrap Finishing
34 silly loadAllDepsIntoIdealTree Starting
35 silly install loadAllDepsIntoIdealTree
36 silly resolveWithNewModule react-native-router-flux@2.0.9 checking installable status
37 silly cache add args [ 'react-native-router-flux', null ]
38 verbose cache add spec react-native-router-flux
39 silly cache add parsed spec Result {
39 silly cache add   raw: 'react-native-router-flux',
39 silly cache add   scope: null,
39 silly cache add   name: 'react-native-router-flux',
39 silly cache add   rawSpec: '',
39 silly cache add   spec: '_',
39 silly cache add   type: 'range' }
40 silly addNamed react-native-router-flux@_
41 verbose addNamed "_" is a valid semver range for react-native-router-flux
42 silly addNameRange { name: 'react-native-router-flux', range: '_', hasData: false }
43 silly mapToRegistry name react-native-router-flux
44 silly mapToRegistry using default registry
45 silly mapToRegistry registry https://registry.npmjs.org/
46 silly mapToRegistry uri https://registry.npmjs.org/react-native-router-flux
47 verbose addNameRange registry:https://registry.npmjs.org/react-native-router-flux not in flight; fetching
48 verbose get https://registry.npmjs.org/react-native-router-flux not expired, no request
49 silly addNameRange number 2 { name: 'react-native-router-flux', range: '*', hasData: true }
50 silly addNameRange versions [ 'react-native-router-flux',
50 silly addNameRange   [ '0.0.1',
50 silly addNameRange     '0.0.2',
50 silly addNameRange     '0.0.3',
50 silly addNameRange     '0.0.4',
50 silly addNameRange     '0.0.5',
50 silly addNameRange     '0.0.7',
50 silly addNameRange     '0.0.8',
50 silly addNameRange     '0.0.9',
50 silly addNameRange     '0.1.0',
50 silly addNameRange     '0.1.1',
50 silly addNameRange     '0.1.2',
50 silly addNameRange     '0.1.3',
50 silly addNameRange     '0.1.4',
50 silly addNameRange     '0.1.5',
50 silly addNameRange     '0.1.6',
50 silly addNameRange     '0.1.7',
50 silly addNameRange     '0.1.8',
50 silly addNameRange     '0.1.9',
50 silly addNameRange     '0.1.10',
50 silly addNameRange     '0.2.0',
50 silly addNameRange     '0.2.1',
50 silly addNameRange     '0.2.2',
50 silly addNameRange     '0.2.3',
50 silly addNameRange     '0.2.4',
50 silly addNameRange     '0.2.5',
50 silly addNameRange     '0.3.0',
50 silly addNameRange     '0.3.1',
50 silly addNameRange     '0.3.2',
50 silly addNameRange     '0.3.3',
50 silly addNameRange     '0.3.4',
50 silly addNameRange     '1.0.0',
50 silly addNameRange     '1.0.1',
50 silly addNameRange     '1.0.2',
50 silly addNameRange     '1.0.3',
50 silly addNameRange     '1.0.4',
50 silly addNameRange     '1.0.5',
50 silly addNameRange     '1.0.7',
50 silly addNameRange     '1.0.8',
50 silly addNameRange     '1.0.9',
50 silly addNameRange     '2.0.0',
50 silly addNameRange     '2.0.1',
50 silly addNameRange     '2.0.2',
50 silly addNameRange     '2.0.3',
50 silly addNameRange     '2.0.4',
50 silly addNameRange     '2.0.5',
50 silly addNameRange     '2.0.6',
50 silly addNameRange     '2.0.7',
50 silly addNameRange     '2.0.8',
50 silly addNameRange     '2.0.9' ] ]
51 silly addNamed react-native-router-flux@2.0.9
52 verbose addNamed "2.0.9" is a plain semver version for react-native-router-flux
53 silly cache afterAdd react-native-router-flux@2.0.9
54 verbose afterAdd /Users/Tom/.npm/react-native-router-flux/2.0.9/package/package.json not in flight; writing
55 verbose afterAdd /Users/Tom/.npm/react-native-router-flux/2.0.9/package/package.json written
56 silly fetchNamedPackageData @exponent/react-native-navigator
57 silly mapToRegistry name @exponent/react-native-navigator
58 silly mapToRegistry scope (from package name) @exponent
59 verbose mapToRegistry no registry URL found in name for scope @exponent
60 silly mapToRegistry using default registry
61 silly mapToRegistry registry https://registry.npmjs.org/
62 silly mapToRegistry uri https://registry.npmjs.org/@exponent%2freact-native-navigator
63 silly fetchNamedPackageData react-native-tabs
64 silly mapToRegistry name react-native-tabs
65 silly mapToRegistry using default registry
66 silly mapToRegistry registry https://registry.npmjs.org/
67 silly mapToRegistry uri https://registry.npmjs.org/react-native-tabs
68 verbose request uri https://registry.npmjs.org/@exponent%2freact-native-navigator
69 verbose request no auth needed
70 info attempt registry request try #1 at 4:32:55 PM
71 verbose etag "XD11VA9QCC0N1HC80I280G0P"
72 http request GET https://registry.npmjs.org/@exponent%2freact-native-navigator
73 verbose request uri https://registry.npmjs.org/react-native-tabs
74 verbose request no auth needed
75 info attempt registry request try #1 at 4:32:55 PM
76 verbose etag "57YISND7PRHLYMLUPSAN4L80Y"
77 http request GET https://registry.npmjs.org/react-native-tabs
78 http 304 https://registry.npmjs.org/react-native-tabs
79 verbose headers { date: 'Thu, 21 Jan 2016 21:32:55 GMT',
79 verbose headers   via: '1.1 varnish',
79 verbose headers   'cache-control': 'max-age=300',
79 verbose headers   etag: '"57YISND7PRHLYMLUPSAN4L80Y"',
79 verbose headers   age: '0',
79 verbose headers   connection: 'keep-alive',
79 verbose headers   'x-served-by': 'cache-jfk1035-JFK',
79 verbose headers   'x-cache': 'MISS',
79 verbose headers   'x-cache-hits': '0',
79 verbose headers   'x-timer': 'S1453411975.903451,VS0,VE417',
79 verbose headers   vary: 'Accept' }
80 silly get cb [ 304,
80 silly get   { date: 'Thu, 21 Jan 2016 21:32:55 GMT',
80 silly get     via: '1.1 varnish',
80 silly get     'cache-control': 'max-age=300',
80 silly get     etag: '"57YISND7PRHLYMLUPSAN4L80Y"',
80 silly get     age: '0',
80 silly get     connection: 'keep-alive',
80 silly get     'x-served-by': 'cache-jfk1035-JFK',
80 silly get     'x-cache': 'MISS',
80 silly get     'x-cache-hits': '0',
80 silly get     'x-timer': 'S1453411975.903451,VS0,VE417',
80 silly get     vary: 'Accept' } ]
81 verbose etag https://registry.npmjs.org/react-native-tabs from cache
82 verbose get saving react-native-tabs to /Users/Tom/.npm/registry.npmjs.org/react-native-tabs/.cache.json
83 silly resolveWithNewModule react-native-tabs@0.1.10 checking installable status
84 silly cache add args [ 'react-native-tabs@^0.1.8', null ]
85 verbose cache add spec react-native-tabs@^0.1.8
86 silly cache add parsed spec Result {
86 silly cache add   raw: 'react-native-tabs@^0.1.8',
86 silly cache add   scope: null,
86 silly cache add   name: 'react-native-tabs',
86 silly cache add   rawSpec: '^0.1.8',
86 silly cache add   spec: '>=0.1.8 <0.2.0',
86 silly cache add   type: 'range' }
87 silly addNamed react-native-tabs@>=0.1.8 <0.2.0
88 verbose addNamed ">=0.1.8 <0.2.0" is a valid semver range for react-native-tabs
89 silly addNameRange { name: 'react-native-tabs',
89 silly addNameRange   range: '>=0.1.8 <0.2.0',
89 silly addNameRange   hasData: false }
90 silly mapToRegistry name react-native-tabs
91 silly mapToRegistry using default registry
92 silly mapToRegistry registry https://registry.npmjs.org/
93 silly mapToRegistry uri https://registry.npmjs.org/react-native-tabs
94 verbose addNameRange registry:https://registry.npmjs.org/react-native-tabs not in flight; fetching
95 verbose get https://registry.npmjs.org/react-native-tabs not expired, no request
96 silly addNameRange number 2 { name: 'react-native-tabs',
96 silly addNameRange   range: '>=0.1.8 <0.2.0',
96 silly addNameRange   hasData: true }
97 silly addNameRange versions [ 'react-native-tabs',
97 silly addNameRange   [ '0.0.1',
97 silly addNameRange     '0.0.2',
97 silly addNameRange     '0.0.3',
97 silly addNameRange     '0.0.4',
97 silly addNameRange     '0.0.5',
97 silly addNameRange     '0.0.6',
97 silly addNameRange     '0.0.7',
97 silly addNameRange     '0.0.8',
97 silly addNameRange     '0.0.9',
97 silly addNameRange     '0.1.0',
97 silly addNameRange     '0.1.1',
97 silly addNameRange     '0.1.2',
97 silly addNameRange     '0.1.3',
97 silly addNameRange     '0.1.4',
97 silly addNameRange     '0.1.6',
97 silly addNameRange     '0.1.7',
97 silly addNameRange     '0.1.8',
97 silly addNameRange     '0.1.9',
97 silly addNameRange     '0.1.10' ] ]
98 silly addNamed react-native-tabs@0.1.10
99 verbose addNamed "0.1.10" is a plain semver version for react-native-tabs
100 silly cache afterAdd react-native-tabs@0.1.10
101 verbose afterAdd /Users/Tom/.npm/react-native-tabs/0.1.10/package/package.json not in flight; writing
102 verbose afterAdd /Users/Tom/.npm/react-native-tabs/0.1.10/package/package.json written
103 http 304 https://registry.npmjs.org/@exponent%2freact-native-navigator
104 verbose headers { date: 'Thu, 21 Jan 2016 21:32:55 GMT',
104 verbose headers   via: '1.1 varnish',
104 verbose headers   'cache-control': 'max-age=0',
104 verbose headers   etag: '"XD11VA9QCC0N1HC80I280G0P"',
104 verbose headers   age: '0',
104 verbose headers   connection: 'keep-alive',
104 verbose headers   'x-served-by': 'cache-jfk1026-JFK',
104 verbose headers   'x-cache': 'MISS',
104 verbose headers   'x-cache-hits': '0',
104 verbose headers   'x-timer': 'S1453411975.891626,VS0,VE474',
104 verbose headers   vary: 'Accept' }
105 silly get cb [ 304,
105 silly get   { date: 'Thu, 21 Jan 2016 21:32:55 GMT',
105 silly get     via: '1.1 varnish',
105 silly get     'cache-control': 'max-age=0',
105 silly get     etag: '"XD11VA9QCC0N1HC80I280G0P"',
105 silly get     age: '0',
105 silly get     connection: 'keep-alive',
105 silly get     'x-served-by': 'cache-jfk1026-JFK',
105 silly get     'x-cache': 'MISS',
105 silly get     'x-cache-hits': '0',
105 silly get     'x-timer': 'S1453411975.891626,VS0,VE474',
105 silly get     vary: 'Accept' } ]
106 verbose etag https://registry.npmjs.org/@exponent%2freact-native-navigator from cache
107 verbose get saving @exponent/react-native-navigator to /Users/Tom/.npm/registry.npmjs.org/_40exponent_252freact-native-navigator/.cache.json
108 silly resolveWithNewModule @exponent/react-native-navigator@0.3.7 checking installable status
109 silly cache add args [ '@exponent/react-native-navigator@^0.3.5', null ]
110 verbose cache add spec @exponent/react-native-navigator@^0.3.5
111 silly cache add parsed spec Result {
111 silly cache add   raw: '@exponent/react-native-navigator@^0.3.5',
111 silly cache add   scope: '@exponent',
111 silly cache add   name: '@exponent/react-native-navigator',
111 silly cache add   rawSpec: '^0.3.5',
111 silly cache add   spec: '>=0.3.5 <0.4.0',
111 silly cache add   type: 'range' }
112 silly addNamed @exponent/react-native-navigator@>=0.3.5 <0.4.0
113 verbose addNamed ">=0.3.5 <0.4.0" is a valid semver range for @exponent/react-native-navigator
114 silly addNameRange { name: '@exponent/react-native-navigator',
114 silly addNameRange   range: '>=0.3.5 <0.4.0',
114 silly addNameRange   hasData: false }
115 silly mapToRegistry name @exponent/react-native-navigator
116 silly mapToRegistry scope (from package name) @exponent
117 verbose mapToRegistry no registry URL found in name for scope @exponent
118 silly mapToRegistry using default registry
119 silly mapToRegistry registry https://registry.npmjs.org/
120 silly mapToRegistry uri https://registry.npmjs.org/@exponent%2freact-native-navigator
121 verbose addNameRange registry:https://registry.npmjs.org/@exponent%2freact-native-navigator not in flight; fetching
122 verbose get https://registry.npmjs.org/@exponent%2freact-native-navigator not expired, no request
123 silly addNameRange number 2 { name: '@exponent/react-native-navigator',
123 silly addNameRange   range: '>=0.3.5 <0.4.0',
123 silly addNameRange   hasData: true }
124 silly addNameRange versions [ '@exponent/react-native-navigator',
124 silly addNameRange   [ '0.1.0',
124 silly addNameRange     '0.1.1',
124 silly addNameRange     '0.1.2',
124 silly addNameRange     '0.1.3',
124 silly addNameRange     '0.1.4',
124 silly addNameRange     '0.2.0',
124 silly addNameRange     '0.2.1',
124 silly addNameRange     '0.2.2',
124 silly addNameRange     '0.2.3',
124 silly addNameRange     '0.2.4',
124 silly addNameRange     '0.2.5',
124 silly addNameRange     '0.2.6',
124 silly addNameRange     '0.2.7',
124 silly addNameRange     '0.2.8',
124 silly addNameRange     '0.2.9',
124 silly addNameRange     '0.3.0',
124 silly addNameRange     '0.3.1',
124 silly addNameRange     '0.3.2',
124 silly addNameRange     '0.3.3',
124 silly addNameRange     '0.3.5',
124 silly addNameRange     '0.3.6',
124 silly addNameRange     '0.3.7',
124 silly addNameRange     '0.4.1' ] ]
125 silly addNamed @exponent/react-native-navigator@0.3.7
126 verbose addNamed "0.3.7" is a plain semver version for @exponent/react-native-navigator
127 silly rollbackFailedOptional Starting
128 silly rollbackFailedOptional Finishing
129 silly runTopLevelLifecycles Starting
130 silly runTopLevelLifecycles Finishing
131 silly install printInstalled
132 verbose stack Error: Invalid name: "@exponent/react-native-navigator"
132 verbose stack     at ensureValidName (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:297:15)
132 verbose stack     at Object.module.exports.fixNameField (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:201:5)
132 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:29:38
132 verbose stack     at Array.forEach (native)
132 verbose stack     at normalize (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:28:15)
132 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:338:5)
132 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:113:5)
132 verbose stack     at ReadFileContext.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:178:20)
132 verbose stack     at ReadFileContext.callback (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:76:16)
132 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete](fs.js:324:13)
133 verbose cwd /Users/Tom/Projects/node_js/groceryListNative
134 error Darwin 14.5.0
135 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "react-native-router-flux" "--save"
136 error node v5.4.0
137 error npm  v3.3.12
138 error Invalid name: "@exponent/react-native-navigator"
139 error If you need help, you may report this error at:
139 error     https://github.com/npm/npm/issues
140 verbose exit [ 1, true ]

**Comment by alex3t** [comment]
update to latest NPM version will fix the problem

**Comment by KenanY** [comment]
Closing as abandoned. Can reopen if this is still an issue with the latest stable version of `npm`.
