### ISSUE TITLE
"npm develop" command to set up dev environment for package name.

### ISSUE THREAD

**Issue by stevage** [npm/npm#11241]
`npm install` can:

- acquire a package for use, and install its dependencies; or
- given a package already acquired for development, install its dependencies

However, it cannot:

- acquire a package for development, and install its dependencies.

I suggest a command `npm develop foo` (or perhaps `npm install --repo`) which does:

1. Search the NPM registry for a package named 'foo'
2. Checkout the repository defined by its `repository.url` into `./foo`
3. Run `npm install --dev ./foo`

**Comment by othiym23** [comment]
This sounds like a great thing to turn into a little utility tool! I don't think it's something that the CLI team is going to have time to get to this year, and I also don't think it really makes sense for the main CLI (we try to be really careful about how we bind npm to git and GitHub, and this blurs those lines a little). I do think it would be a useful utility to a bunch of people, though! Thanks for your time!

**Comment by stevage** [comment]
Thanks for the feedback. Turns out it already exists!

```
$ npm install -g npm-clone
$ npm-clone install foo
Cloning into 'foo'...
WARN engine npm@1.4.29: wanted: {"node":">=0.8","npm":"1"} (current: {"node":"0.12.0","npm":"3.5.3"})
...
```
