### ISSUE TITLE
npm run and the working directory

### ISSUE THREAD

**Issue by rauschma** [npm/npm#11247]
npm is increasingly used for installing executables locally. For that use case, it is inconvenient that `npm run` sets the current working directory to the root of the package. I’m not sure how difficult it would be to change that behavior, but if it was changed then there probably should be a variable like `$PACKAGE_ROOT`, which could be used whenever you want the current behavior of `npm run`.

**Comment by busches** [comment]
@othiym23 is this something `npm` would be open to accepting as a pr?

**Comment by othiym23** [comment]
@busches Hard to say. It needs further discussion and the CLI team probably isn't going to get to discussing this for a little while.
