### ISSUE TITLE
Markdown rendering issue: Incorrect Code Indents

### ISSUE THREAD

**Issue by jhuckaby** [npm/npm#11246]
When indenting code using real tabs (not spaces), npmjs.com renders it with very odd spacing:

https://www.npmjs.com/package/npm-markdown-bugs#incorrect-code-indents

Basically, anything nested more than one tab deep is collapsed to the left side.

For comparison, this same code snippet views fine on GitHub:

https://github.com/jhuckaby/npm-markdown-bugs#incorrect-code-indents

\- Joe

**Comment by othiym23** [comment]
This sounds like an issue for npm/newww, which is the code base for the web site. The CLI just publishes and installs packages, and doesn't render any Markdown!

**Comment by jhuckaby** [comment]
Whoops, thank you @othiym23, I didn't know.  Closing issue and reposting there!
