### ISSUE TITLE
unable to install ecstatic

### ISSUE THREAD

**Issue by bitini** [npm/npm#11252]
I intall node js and npm on windows 7 PC
it is working fine

But I am unable to install the ecstatic module.
I run command : npm install ecstatic@>=0.5.0   but failed
please find attached log file

[Log file error.docx](https://github.com/npm/npm/files/100885/Log.file.error.docx)

**Comment by KenanY** [comment]
@bitini Could you upload the `npm-debug.log` file to https://gist.github.com/ instead of converting it to a `docx`?

**Comment by bitini** [comment]
This is the log file : <script src="https://gist.github.com/bitini/fa0ead4147c1690b3f00.js"></script>

**Comment by bitini** [comment]
Ok done

**Comment by KenanY** [comment]
@bitini Post the link here?

**Comment by bitini** [comment]
<script src="https://gist.github.com/bitini/fa0ead4147c1690b3f00.js"></script>

**Comment by bitini** [comment]
The file can be found here : https://gist.github.com/bitini/fa0ead4147c1690b3f00/revisions

**Comment by ashleygwilliams** [comment]
same issue: this is the same as https://github.com/npm/npm/issues/11448
