### ISSUE TITLE
$npm_package_version env var is wrong during `preversion` lifecycle hook

### ISSUE THREAD

**Issue by jasonkarns** [npm/npm#11253]
Given `version` lifecycle scripts:

``` json
  "version": "1.0.0",
  "scripts": {
    "preversion": "echo $npm_package_version",
    "version": "echo $npm_package_version",
    "postversion": "echo $npm_package_version"
  },
```

When `$ npm version patch`

Then I should see:

``` bash
> preversion
1.0.0
> version
1.0.0
> postversion
1.0.1
```

Instead, I see:

``` bash
> preversion
1.0.1
> version
1.0.1
> postversion
1.0.1
```

It seems that the `npm_package_version` env var is updated to the new version before the lifecycle scripts are run. The var shouldn't be updated until the `postversion` script (since both `preversion` and `version` scripts are executed BEFORE the version bump).

Tested with: npm 3.5.3 (latest) and 3.6.0 (next)

**Comment by jasonkarns** [comment]
related to #8730

**Comment by remy** [comment]
Though I'm not saying this isn't a bug, it _is_ useful that the upcoming version is available in the `preversion` lifecycle.

In particular, it could be used to create the distribution build and check it all in as part of the version bump:

```
"scripts": {
  "version": "build src > dist/build.$npm_package_version.js && git add .",
}
```

This (contrived example) would build out my distribution build with the latest version, and add the changes into git before `npm version X` completed and committed the changes to git.

I think what would be useful here is somehow having access to the previous version (before the change) or changing as suggested by @jasonkarns but including the upcoming version in the first two lifecycle and the prev version in the last lifecycle (post) - though I suspect this is slightly more complicated for authors to grok.

**Comment by jasonkarns** [comment]
I'm not exactly sure what I was thinking when I opened the issue. The [docs clearly state](https://docs.npmjs.com/cli/version) that the package.json version is bumped *before* the `version` lifecycle script is run, so I would fully expect `$npm_package_version` to be the bumped value in both `version` and `postversion` hooks. I still maintain that `$npm_package_version` should be the old value during the `preversion` hook.

Updated expectation (same given/when from original post):

``` bash
> preversion
1.0.0
> version
1.0.1
> postversion
1.0.1
```

@remy does this jive with your expectations? You mentioned having the upcoming version available in `preversion`, but your example used the `version` script. I think your example is correct. The `version` script is the more appropriate place to run builds/changelogs/etc, and having the upcoming version is correct there. But the `preversion` is explicitly *before bumping*, so I'd expect the old value to be reflected there.

**Comment by jasonkarns** [comment]
Any other discussion on this? I still maintain that it's incorrect behavior for $npm_package_version to be the _bumped_ version for the _preversion_ hook.

**Comment by jasonkarns** [comment]
Changed issue title as I acknowledge that it's preferred for `$npm_package_version` to be the bumped value for the `version` hook. (just not `preversion`)

**Comment by tnguyen14** [comment]
I think `npm_package_version` should be bumped for `version` and `postversion` scripts as well. Could this issue be reopened?
