### ISSUE TITLE
getting error

### ISSUE THREAD

**Issue by h4harish** [npm/npm#11259]
My command is 
npm install 
When am gonna to run this command in on my webstorm terminol it going well but after am typing 
npm run build 
It's going to throw me error 
npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\harish\WebstormProjects\Angular 2 first Attemt\npm-debug.log

How to solve this Error,please give a Solution

**Comment by KenanY** [comment]
@h4harish Please upload the `npm-debug.log` to https://gist.github.com/ and post the link here.

**Comment by KenanY** [comment]
@h4harish ping

**Comment by KenanY** [comment]
@h4harish Second ping: are you still experiencing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
