### ISSUE TITLE
Rename username

### ISSUE THREAD

**Issue by demoneaux** [npm/npm#11258]
Is there a way to rename username? I couldn't find it in the npm site/issues.

**Comment by ashleygwilliams** [comment]
hi! i'm not sure exactly what you mean. do you mean transfer one user name to a new one? if so, no there is currently no way to do so.

if you wish to change your user name you can create a new user and grant them access to your modules. this is currently the only way to do this.

please open a new issue at https://github.com/npm/newww/issues (the website repo) if you meant something else.
