### ISSUE TITLE
npm not installed plugins into node_modules

### ISSUE THREAD

**Issue by furyscript** [npm/npm#11251]
I have windows 7, when I use npm install into projects, I have a package.json, but it install the plugin in current directory and it doesn't create node_modules folder.

Why this issue?

**Comment by ashleygwilliams** [comment]
hi! can you please comment with:
- the exact command you are using
- the contents of `package.json`
- your version of node and npm
- the project's directory tree

thanks!

**Comment by ashleygwilliams** [comment]
hi! it has been a week since there was any action on this ticket, so i am going to close. please file a new issue if you continue to have trouble! best of luck!
