### ISSUE TITLE
Error while init for mean application

### ISSUE THREAD

**Issue by mkbadri** [npm/npm#11268]
I have just started with MEAN and am following the instructions on mean.io

Have done the following steps until now:
$ npm install -g mean-cli -- goes through fine
$ mean init myMeanApp  -- goes through fine
$ cd myMeanApp && npm install --- Error 

I have already tried the troubleshooting steps on mean.io. Have reinstalled and node npm, updated to latest as well. 

The last few lines from the npm-debug.log ...
44440 info retry fetch attempt 1 at 11:21:14 AM
44441 info attempt registry request try #1 at 11:21:14 AM
44442 http fetch GET https://registry.npmjs.org/inherits/-/inherits-2.0.1.tgz
44443 info retry fetch attempt 1 at 11:21:14 AM
44444 info attempt registry request try #1 at 11:21:14 AM
44445 http fetch GET https://registry.npmjs.org/minimatch/-/minimatch-0.3.0.tgz
44446 silly cache afterAdd lodash@3.10.1
44447 verbose afterAdd /Users/badri/.npm/lodash/3.10.1/package/package.json not in flight; writing
44448 verbose afterAdd /Users/badri/.npm/lodash/3.10.1/package/package.json written
44449 http fetch 200 https://registry.npmjs.org/inherits/-/inherits-2.0.1.tgz
44450 silly fetchAndShaCheck shasum b17d08d326b4423e568eff719f91b0b1cbdf69f1
44451 verbose addTmpTarball /var/folders/fq/p28xk5s1109g341thpgpwvq9tyr93p/T/npm-828-d85cf532/registry.npmjs.org/inherits/-/inherits-2.0.1.tgz not in flight; adding
44452 verbose addTmpTarball validating metadata from /var/folders/fq/p28xk5s1109g341thpgpwvq9tyr93p/T/npm-828-d85cf532/registry.npmjs.org/inherits/-/inherits-2.0.1.tgz
44453 verbose tar unpack /var/folders/fq/p28xk5s1109g341thpgpwvq9tyr93p/T/npm-828-d85cf532/registry.npmjs.org/inherits/-/inherits-2.0.1.tgz
44454 verbose tar unpacking to /var/folders/fq/p28xk5s1109g341thpgpwvq9tyr93p/T/npm-828-d85cf532/unpack-1b295dce62ee97ed1651dd335ae6a3f0
44455 silly gentlyRm /var/folders/fq/p28xk5s1109g341thpgpwvq9tyr93p/T/npm-828-d85cf532/unpack-1b295dce62ee97ed1651dd335ae6a3f0 is being purged
44456 verbose gentlyRm don't care about contents; nuking /var/folders/fq/p28xk5s1109g341thpgpwvq9tyr93p/T/npm-828-d85cf532/unpack-1b295dce62ee97ed1651dd335ae6a3f0
44457 silly gunzTarPerm modes [ '755', '644' ]
44458 silly gunzTarPerm extractEntry package.json
44459 silly gunzTarPerm extractEntry README.md
44460 silly gunzTarPerm extractEntry LICENSE
44461 silly gunzTarPerm extractEntry inherits.js
44462 silly gunzTarPerm extractEntry inherits_browser.js
44463 silly gunzTarPerm extractEntry test.js
44464 silly cache afterAdd inherits@2.0.1
44465 verbose afterAdd /Users/badri/.npm/inherits/2.0.1/package/package.json not in flight; writing
44466 verbose afterAdd /Users/badri/.npm/inherits/2.0.1/package/package.json written
44467 http fetch 200 https://registry.npmjs.org/minimatch/-/minimatch-0.3.0.tgz
44468 silly fetchAndShaCheck shasum 275d8edaac4f1bb3326472089e7949c8394699dd
44469 verbose addTmpTarball /var/folders/fq/p28xk5s1109g341thpgpwvq9tyr93p/T/npm-828-d85cf532/registry.npmjs.org/minimatch/-/minimatch-0.3.0.tgz not in flight; adding
44470 verbose addTmpTarball validating metadata from /var/folders/fq/p28xk5s1109g341thpgpwvq9tyr93p/T/npm-828-d85cf532/registry.npmjs.org/minimatch/-/minimatch-0.3.0.tgz
44471 verbose tar unpack /var/folders/fq/p28xk5s1109g341thpgpwvq9tyr93p/T/npm-828-d85cf532/registry.npmjs.org/minimatch/-/minimatch-0.3.0.tgz
44472 verbose tar unpacking to /var/folders/fq/p28xk5s1109g341thpgpwvq9tyr93p/T/npm-828-d85cf532/unpack-2e84d6708b1fb6b21088153a43efbfaa
44473 silly gentlyRm /var/folders/fq/p28xk5s1109g341thpgpwvq9tyr93p/T/npm-828-d85cf532/unpack-2e84d6708b1fb6b21088153a43efbfaa is being purged
44474 verbose gentlyRm don't care about contents; nuking /var/folders/fq/p28xk5s1109g341thpgpwvq9tyr93p/T/npm-828-d85cf532/unpack-2e84d6708b1fb6b21088153a43efbfaa
44475 silly gunzTarPerm modes [ '755', '644' ]
44476 silly gunzTarPerm extractEntry package.json
44477 silly gunzTarPerm extractEntry .npmignore
44478 silly gunzTarPerm extractEntry README.md
44479 silly gunzTarPerm extractEntry LICENSE
44480 silly gunzTarPerm extractEntry minimatch.js
44481 silly gunzTarPerm extractEntry test/basic.js
44482 silly gunzTarPerm extractEntry test/brace-expand.js
44483 silly gunzTarPerm extractEntry test/caching.js
44484 silly gunzTarPerm extractEntry test/defaults.js
44485 silly gunzTarPerm extractEntry test/extglob-ending-with-state-char.js
44486 silly cache afterAdd minimatch@0.3.0
44487 verbose afterAdd /Users/badri/.npm/minimatch/0.3.0/package/package.json not in flight; writing
44488 verbose afterAdd /Users/badri/.npm/minimatch/0.3.0/package/package.json written
44489 silly fetchPackageMetaData lru-cache@https://registry.npmjs.org/lru-cache/-/lru-cache-2.7.3.tgz
44490 silly fetchPackageMetaData sigmund@https://registry.npmjs.org/sigmund/-/sigmund-1.0.1.tgz
44491 silly fetchOtherPackageData lru-cache@https://registry.npmjs.org/lru-cache/-/lru-cache-2.7.3.tgz
44492 silly cache add args [ 'lru-cache@https://registry.npmjs.org/lru-cache/-/lru-cache-2.7.3.tgz',
44492 silly cache add   null ]
44493 verbose cache add spec lru-cache@https://registry.npmjs.org/lru-cache/-/lru-cache-2.7.3.tgz
44494 silly fetchOtherPackageData sigmund@https://registry.npmjs.org/sigmund/-/sigmund-1.0.1.tgz
44495 silly cache add args [ 'sigmund@https://registry.npmjs.org/sigmund/-/sigmund-1.0.1.tgz',
44495 silly cache add   null ]
44496 verbose cache add spec sigmund@https://registry.npmjs.org/sigmund/-/sigmund-1.0.1.tgz
44497 silly cache add parsed spec Result {
44497 silly cache add   raw: 'lru-cache@https://registry.npmjs.org/lru-cache/-/lru-cache-2.7.3.tgz',
44497 silly cache add   scope: null,
44497 silly cache add   name: 'lru-cache',
44497 silly cache add   rawSpec: 'https://registry.npmjs.org/lru-cache/-/lru-cache-2.7.3.tgz',
44497 silly cache add   spec: 'https://registry.npmjs.org/lru-cache/-/lru-cache-2.7.3.tgz',
44497 silly cache add   type: 'remote' }
44498 silly mapToRegistry name lru-cache@https://registry.npmjs.org/lru-cache/-/lru-cache-2.7.3.tgz
44499 silly mapToRegistry using default registry
44500 silly mapToRegistry registry https://registry.npmjs.org/
44501 silly mapToRegistry uri https://registry.npmjs.org/lru-cache@https://registry.npmjs.org/lru-cache/-/lru-cache-2.7.3.tgz
44502 verbose addRemoteTarball https://registry.npmjs.org/lru-cache/-/lru-cache-2.7.3.tgz not in flight; adding
44503 verbose addRemoteTarball [ 'https://registry.npmjs.org/lru-cache/-/lru-cache-2.7.3.tgz',
44503 verbose addRemoteTarball   null ]
44504 silly cache add parsed spec Result {
44504 silly cache add   raw: 'sigmund@https://registry.npmjs.org/sigmund/-/sigmund-1.0.1.tgz',
44504 silly cache add   scope: null,
44504 silly cache add   name: 'sigmund',
44504 silly cache add   rawSpec: 'https://registry.npmjs.org/sigmund/-/sigmund-1.0.1.tgz',
44504 silly cache add   spec: 'https://registry.npmjs.org/sigmund/-/sigmund-1.0.1.tgz',
44504 silly cache add   type: 'remote' }
44505 silly mapToRegistry name sigmund@https://registry.npmjs.org/sigmund/-/sigmund-1.0.1.tgz
44506 silly mapToRegistry using default registry
44507 silly mapToRegistry registry https://registry.npmjs.org/
44508 silly mapToRegistry uri https://registry.npmjs.org/sigmund@https://registry.npmjs.org/sigmund/-/sigmund-1.0.1.tgz
44509 verbose addRemoteTarball https://registry.npmjs.org/sigmund/-/sigmund-1.0.1.tgz not in flight; adding
44510 verbose addRemoteTarball [ 'https://registry.npmjs.org/sigmund/-/sigmund-1.0.1.tgz',
44510 verbose addRemoteTarball   null ]
44511 info retry fetch attempt 1 at 11:21:14 AM
44512 info attempt registry request try #1 at 11:21:14 AM
44513 http fetch GET https://registry.npmjs.org/lru-cache/-/lru-cache-2.7.3.tgz
44514 info retry fetch attempt 1 at 11:21:14 AM
44515 info attempt registry request try #1 at 11:21:14 AM
44516 http fetch GET https://registry.npmjs.org/sigmund/-/sigmund-1.0.1.tgz
44517 http fetch 200 https://registry.npmjs.org/sigmund/-/sigmund-1.0.1.tgz
44518 silly fetchAndShaCheck shasum 3ff21f198cad2175f9f3b781853fd94d0d19b590
44519 verbose addTmpTarball /var/folders/fq/p28xk5s1109g341thpgpwvq9tyr93p/T/npm-828-d85cf532/registry.npmjs.org/sigmund/-/sigmund-1.0.1.tgz not in flight; adding
44520 verbose addTmpTarball validating metadata from /var/folders/fq/p28xk5s1109g341thpgpwvq9tyr93p/T/npm-828-d85cf532/registry.npmjs.org/sigmund/-/sigmund-1.0.1.tgz
44521 verbose tar unpack /var/folders/fq/p28xk5s1109g341thpgpwvq9tyr93p/T/npm-828-d85cf532/registry.npmjs.org/sigmund/-/sigmund-1.0.1.tgz
44522 verbose tar unpacking to /var/folders/fq/p28xk5s1109g341thpgpwvq9tyr93p/T/npm-828-d85cf532/unpack-0cdd0de7136b97c446edd1520b36c172
44523 silly gentlyRm /var/folders/fq/p28xk5s1109g341thpgpwvq9tyr93p/T/npm-828-d85cf532/unpack-0cdd0de7136b97c446edd1520b36c172 is being purged
44524 verbose gentlyRm don't care about contents; nuking /var/folders/fq/p28xk5s1109g341thpgpwvq9tyr93p/T/npm-828-d85cf532/unpack-0cdd0de7136b97c446edd1520b36c172
44525 silly gunzTarPerm modes [ '755', '644' ]
44526 silly gunzTarPerm extractEntry package.json
44527 silly gunzTarPerm extractEntry README.md
44528 silly gunzTarPerm extractEntry LICENSE
44529 silly gunzTarPerm extractEntry bench.js
44530 silly gunzTarPerm extractEntry sigmund.js
44531 silly gunzTarPerm extractEntry test/basic.js
44532 http fetch 200 https://registry.npmjs.org/lru-cache/-/lru-cache-2.7.3.tgz
44533 silly fetchAndShaCheck shasum 6d4524e8b955f95d4f5b58851ce21dd72fb4e952
44534 verbose addTmpTarball /var/folders/fq/p28xk5s1109g341thpgpwvq9tyr93p/T/npm-828-d85cf532/registry.npmjs.org/lru-cache/-/lru-cache-2.7.3.tgz not in flight; adding
44535 verbose addTmpTarball validating metadata from /var/folders/fq/p28xk5s1109g341thpgpwvq9tyr93p/T/npm-828-d85cf532/registry.npmjs.org/lru-cache/-/lru-cache-2.7.3.tgz
44536 verbose tar unpack /var/folders/fq/p28xk5s1109g341thpgpwvq9tyr93p/T/npm-828-d85cf532/registry.npmjs.org/lru-cache/-/lru-cache-2.7.3.tgz
44537 verbose tar unpacking to /var/folders/fq/p28xk5s1109g341thpgpwvq9tyr93p/T/npm-828-d85cf532/unpack-813f7d644a09f7518a0f34641d10f68f
44538 silly gentlyRm /var/folders/fq/p28xk5s1109g341thpgpwvq9tyr93p/T/npm-828-d85cf532/unpack-813f7d644a09f7518a0f34641d10f68f is being purged
44539 verbose gentlyRm don't care about contents; nuking /var/folders/fq/p28xk5s1109g341thpgpwvq9tyr93p/T/npm-828-d85cf532/unpack-813f7d644a09f7518a0f34641d10f68f
44540 silly gunzTarPerm modes [ '755', '644' ]
44541 silly gunzTarPerm extractEntry package.json
44542 silly gunzTarPerm extractEntry .npmignore
44543 silly gunzTarPerm extractEntry README.md
44544 silly gunzTarPerm extractEntry LICENSE
44545 silly gunzTarPerm extractEntry .travis.yml
44546 silly gunzTarPerm extractEntry CONTRIBUTORS
44547 silly gunzTarPerm extractEntry lib/lru-cache.js
44548 silly gunzTarPerm extractEntry test/basic.js
44549 silly cache afterAdd sigmund@1.0.1
44550 verbose afterAdd /Users/badri/.npm/sigmund/1.0.1/package/package.json not in flight; writing
44551 silly gunzTarPerm extractEntry test/foreach.js
44552 silly gunzTarPerm extractEntry test/memory-leak.js
44553 verbose afterAdd /Users/badri/.npm/sigmund/1.0.1/package/package.json written
44554 silly gunzTarPerm extractEntry test/serialize.js
44555 silly cache afterAdd lru-cache@2.7.3
44556 verbose afterAdd /Users/badri/.npm/lru-cache/2.7.3/package/package.json not in flight; writing
44557 verbose afterAdd /Users/badri/.npm/lru-cache/2.7.3/package/package.json written
44558 silly addBundled read tarball
44559 silly cleanup remove extracted module
44560 http fetch 200 https://registry.npmjs.org/entities/-/entities-1.0.0.tgz
44561 silly fetchAndShaCheck shasum b2987aa3821347fcde642b24fdfc9e4fb712bf26
44562 verbose addTmpTarball /var/folders/fq/p28xk5s1109g341thpgpwvq9tyr93p/T/npm-828-d85cf532/registry.npmjs.org/entities/-/entities-1.0.0.tgz not in flight; adding
44563 verbose addTmpTarball validating metadata from /var/folders/fq/p28xk5s1109g341thpgpwvq9tyr93p/T/npm-828-d85cf532/registry.npmjs.org/entities/-/entities-1.0.0.tgz
44564 verbose tar unpack /var/folders/fq/p28xk5s1109g341thpgpwvq9tyr93p/T/npm-828-d85cf532/registry.npmjs.org/entities/-/entities-1.0.0.tgz
44565 verbose tar unpacking to /var/folders/fq/p28xk5s1109g341thpgpwvq9tyr93p/T/npm-828-d85cf532/unpack-5564ae06681d474d4cb55b4dfb3a925a
44566 silly gentlyRm /var/folders/fq/p28xk5s1109g341thpgpwvq9tyr93p/T/npm-828-d85cf532/unpack-5564ae06681d474d4cb55b4dfb3a925a is being purged
44567 verbose gentlyRm don't care about contents; nuking /var/folders/fq/p28xk5s1109g341thpgpwvq9tyr93p/T/npm-828-d85cf532/unpack-5564ae06681d474d4cb55b4dfb3a925a
44568 silly gunzTarPerm modes [ '755', '644' ]
44569 silly gunzTarPerm extractEntry package.json
44570 silly gunzTarPerm extractEntry LICENSE
44571 silly gunzTarPerm extractEntry index.js
44572 silly gunzTarPerm extractEntry .travis.yml
44573 silly gunzTarPerm extractEntry lib/decode.js
44574 silly gunzTarPerm extractEntry lib/decode_codepoint.js
44575 silly gunzTarPerm extractEntry lib/encode.js
44576 silly gunzTarPerm extractEntry maps/decode.json
44577 silly gunzTarPerm extractEntry maps/entities.json
44578 silly gunzTarPerm extractEntry maps/legacy.json
44579 silly gunzTarPerm extractEntry maps/xml.json
44580 silly gunzTarPerm extractEntry readme.md
44581 silly gunzTarPerm extractEntry test/test.js
44582 silly gunzTarPerm extractEntry test/mocha.opts
44583 silly cache afterAdd entities@1.0.0
44584 verbose afterAdd /Users/badri/.npm/entities/1.0.0/package/package.json not in flight; writing
44585 verbose afterAdd /Users/badri/.npm/entities/1.0.0/package/package.json written
44586 silly rollbackFailedOptional Starting
44587 silly rollbackFailedOptional Finishing
44588 silly runTopLevelLifecycles Starting
44589 silly runTopLevelLifecycles Finishing
44590 silly install printInstalled
44591 verbose stack Error: unexpected end of file
44591 verbose stack     at Zlib._handle.onerror (zlib.js:363:17)
44592 verbose cwd /Users/badri/Documents/AngularMaterial/mean/meanMeetup
44593 error Darwin 15.2.0
44594 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
44595 error node v5.5.0
44596 error npm  v3.3.12
44597 error code Z_BUF_ERROR
44598 error errno -5
44599 error unexpected end of file
44600 error If you need help, you may report this error at:
44600 error     <https://github.com/npm/npm/issues>
44601 verbose exit [ -5, true ]

Please help. Thanks.

**Comment by zkat** [comment]
This is potentially a hiccup with a download that prevented the tarball from downloading fully: Try doing `npm cache clean` and repeating the steps you went through.

I'm going to close this for now, since that seems like a likely resolution, but please reopen this if it's still not fixed, ok? :D
