### ISSUE TITLE
How to automatically copy files from package to local directory via postinstall npm script?

### ISSUE THREAD

**Issue by dmitriz** [npm/npm#11260]
This should be a common question but no info in the Docs.

I want to automatically copy certain files from an npm package to user's local directory after running

``` sh
npm install my-package
```

I can get them installed by declaring "files" inside package.json. The problem is --- the files are not put in the local directory. So I need to run postinstall script.

But now I don't know where the package is installed (maybe higher up the directory tree), so how can I reliably access the files and copy them to the local directory via the script?

(By local directory I mean --- from where I run npm install my-package as user consuming the package.)

It seems the postinstall script runs as npm owned process with home directory being node_modules/my-package, so I still don't know how to access user's home directory other than with naive ../../.

Asked on SO but the answer given does not solve the problem:

http://stackoverflow.com/questions/34781630/how-to-automatically-copy-files-from-package-to-local-directory-via-postinstall

**Comment by u01jmg3** [comment]
+1

**Comment by maciejkowalski** [comment]
http://stackoverflow.com/a/43267100/418518
