### ISSUE TITLE
dependent packages using ^ versions not being de-duped correctly

### ISSUE THREAD

**Issue by mrsharpoblunto** [npm/npm#11264]
Given a package.json with

"dependencies": {
  "babel-core": "^6.4.5",
  "babel-runtime": "^6.3.19"
}

and where babel-core has a dependency on "babel-runtime": "^5.0.0"

When I run npm install I get

node_modules
  babel-core@6.4.5
  babel-runtime@6.3.19

This fails to run however as babel-core is using babel-runtime 6.3.19, not the expected 5.x version. I would expect the install structure in this case to be

node_modules
  babel-core@6.4.5
    babel-runtime@5.8.35
  babel-runtime@6.3.19

And in fact this is what happens if I run 'npm install babel-core' AFTER running the initial install. Based on the semver docs, caret version specifiers should not be installing packages that modify the leftmost non-zero digit, but this is happening in this case where 6.3.19 is being resolved as being compatible with ^5.0.0.

**Comment by KenanY** [comment]
Sounds like https://github.com/npm/npm/issues/11043
