### ISSUE TITLE
Trouble installing Ember-CLI

### ISSUE THREAD

**Issue by SeaBassTian** [npm/npm#11266]
Trying to install Ember via NPM on a Windows 10 device. Getting the following error message which I am attaching as a jpeg. For some reason, it seems to identify the system as Windows_NT 6.2.9200(?).
![npmi](https://cloud.githubusercontent.com/assets/10586972/12537921/d774b8bc-c299-11e5-9de4-db0f894b265a.JPG)

**Comment by razh** [comment]
Can you try updating npm?

https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows

From https://github.com/npm/npm/issues/6210#issuecomment-67704587

> This is sort of an unavoidable cost of doing business on Windows – if anything (an editor, an Explorer window, any other random process) is holding a file or directory open, any attempts to modify, rename, or remove the open file or directory will raise EBUSY. I have yet to see an instance of this that persists beyond a reboot of the system since **we fixed the most egregious race conditions inside npm (ca. npm@2.1.5)**.

**Comment by SeaBassTian** [comment]
Well, the odd thing is that it always works perfectly on my other machine running Windows10. Never a glitch! Perhaps I am running an older version of NPM on this laptop, I will attempt that and report back.

**Comment by zkat** [comment]
I'm closing this for now, but updating and trying again seems like a pretty good solution. I'm closing this for now, but please reopen it if it keeps happening and you've verified nothing (an IDE, etc) is keeping that file open. :)

**Comment by SeaBassTian** [comment]
Well, it's still a nightmare. I have upgraded to the latest Node & NPM packages but keep getting errors such as EPERM: Operation not permitted, Rename. I'm attaching a screenshots. I attempted to clear the npm-cache but that didn't seem to do the trick. I also wondered whether I could actually rename the file in question without causing serious problems... Why is this so difficult on Windows?
![eperm](https://cloud.githubusercontent.com/assets/10586972/13065837/65f23178-d42e-11e5-859f-c9645a3a9e08.JPG)
![wrappy](https://cloud.githubusercontent.com/assets/10586972/13065840/6de8f98e-d42e-11e5-855a-de12652580fd.JPG)

**Comment by SeaBassTian** [comment]
UPDATE: I finally got it to work after clearing the npm cache not once but twice. Now of course it runs painfully slow but at least I am up and running and ready to start coding again.

**Comment by zkat** [comment]
Hey, thanks for the update! I'm glad it managed to work after some cache clearing. Is the slowness related to npm itself?

There's an ongoing effort to make Windows support way better than it is right now -- unfortunately, issues like these aren't really a surprise. Hopefully by the end of the year, we'll have addressed a lot of ongoing problems with Windows, have CI up and running, etc.

Thanks for filing this -- I hope things go smoother from here on out, and that the stuff we're working on makes it even better. :)
