### ISSUE TITLE
unable to install phoneGap

### ISSUE THREAD

**Issue by rasthana666** [npm/npm#11270]
C:\Users\rasthana>npm install -g phonegap
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "phonegap"
npm ERR! node v5.5.0
npm ERR! npm  v3.3.12
npm ERR! code UNABLE_TO_GET_ISSUER_CERT_LOCALLY

npm ERR! unable to get local issuer certificate
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\rasthana\npm-debug.log

----------------------------------------------------------------------

debug.log 

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'phonegap' ]
2 info using npm@3.3.12
3 info using node@v5.5.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData phonegap
8 silly fetchNamedPackageData phonegap
9 silly mapToRegistry name phonegap
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/phonegap
13 verbose request uri https://registry.npmjs.org/phonegap
14 verbose request no auth needed
15 info attempt registry request try #1 at 2:21:44 PM
16 verbose request id 8b18cc1eed7d9b87
17 http request GET https://registry.npmjs.org/phonegap
18 info retry will retry, error on last attempt: Error: unable to get local issuer certificate
19 info attempt registry request try #2 at 2:21:54 PM
20 http request GET https://registry.npmjs.org/phonegap
21 info retry will retry, error on last attempt: Error: unable to get local issuer certificate
22 info attempt registry request try #3 at 2:22:55 PM
23 http request GET https://registry.npmjs.org/phonegap
24 silly fetchPackageMetaData Error: unable to get local issuer certificate
24 silly fetchPackageMetaData     at Error (native)
24 silly fetchPackageMetaData     at TLSSocket.<anonymous> (_tls_wrap.js:1057:38)
24 silly fetchPackageMetaData     at emitNone (events.js:80:13)
24 silly fetchPackageMetaData     at TLSSocket.emit (events.js:179:7)
24 silly fetchPackageMetaData     at TLSSocket._init.ssl.onclienthello.ssl.oncertcb.TLSSocket._finishInit (_tls_wrap.js:596:8)
24 silly fetchPackageMetaData     at TLSWrap.ssl.onclienthello.ssl.oncertcb.ssl.onnewsession.ssl.onhandshakedone (_tls_wrap.js:428:38)
24 silly fetchPackageMetaData  error for phonegap { [Error: unable to get local issuer certificate] code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY' }
25 silly rollbackFailedOptional Starting
26 silly rollbackFailedOptional Finishing
27 silly runTopLevelLifecycles Starting
28 silly runTopLevelLifecycles Finishing
29 silly install printInstalled
30 verbose stack Error: unable to get local issuer certificate
30 verbose stack     at Error (native)
30 verbose stack     at TLSSocket.<anonymous> (_tls_wrap.js:1057:38)
30 verbose stack     at emitNone (events.js:80:13)
30 verbose stack     at TLSSocket.emit (events.js:179:7)
30 verbose stack     at TLSSocket._init.ssl.onclienthello.ssl.oncertcb.TLSSocket._finishInit (_tls_wrap.js:596:8)
30 verbose stack     at TLSWrap.ssl.onclienthello.ssl.oncertcb.ssl.onnewsession.ssl.onhandshakedone (_tls_wrap.js:428:38)
31 verbose cwd C:\Users\rasthana
32 error Windows_NT 6.1.7601
33 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "phonegap"
34 error node v5.5.0
35 error npm  v3.3.12
36 error code UNABLE_TO_GET_ISSUER_CERT_LOCALLY
37 error unable to get local issuer certificate
38 error If you need help, you may report this error at:
38 error     <https://github.com/npm/npm/issues>
39 verbose exit [ 1, true ]

**Comment by zkat** [comment]
This looks like a misconfigured proxy: if you're configured a proxy or are using a transparent proxy and haven't included a CA bundle, this is what you'll see. Please check your proxy settings and reopen if it's still unresolved, but this is not an npm-specific issue.
