### ISSUE TITLE
npm view should optionally print valid json with a --raw flag

### ISSUE THREAD

**Issue by samccone** [npm/npm#11278]
Currently `npm view` prints a modified pretty printed version of the package information.

![image](https://cloud.githubusercontent.com/assets/883126/12561523/939afc02-c355-11e5-9cbd-45917bdc0795.png)

By not outputting to JSON (optionally) bash scripting against the output becomes more difficult.
Ideally I would be able to do something like `npm view backbone.marionette --raw | jq .`

If this is something you agree with, I can 100% add a patch and a test for this. 

Thanks for taking the time :hourglass: to read this.

**Comment by othiym23** [comment]
Does `npm view --json` not do what you want?

**Comment by samccone** [comment]
ah I missed the note about that!

would a PR to add this to the **synopsis** section under common options be welcome?
