### ISSUE TITLE
npm --save converts git+ssh:// URLs to ssh://

### ISSUE THREAD

**Issue by pornel** [npm/npm#11277]
```sh
npm i --save git+ssh://git@example.com/foo.git
```

produces `package.json` with:

```js
"foo": "ssh://git@example.com/foo.git"
```

and this URL is subsequently unusable with npm, which leads to problems like #11276.

The same happens when you do `npm up --save`.

**Comment by KenanY** [comment]
@pornel Is this a duplicate of https://github.com/npm/npm/issues/9679?

**Comment by pornel** [comment]
Yes, thanks.
