### ISSUE TITLE
npm automatic dedup + devDependencies + shrinkWrap ==> dependency lost!

### ISSUE THREAD

**Issue by psorowka** [npm/npm#11287]
We are working with npm@2.14.12 and have a weird situation that leads to missing dependencies in production installs.

Given we have the following simplified dependency tree

```
a@1.0.0        
 |- b@1.0.0    <-- dev dependency
 |- c@1.0.0
    |- b@1.0.0 <-- regular dependency
    |- d@1.0.0 <-- other regular dependency
```

A simple `npm install` will simplify the tree thanks to automatic dedupe as follows:

```
a@1.0.0        
 |- b@1.0.0
 |- c@1.0.0
    |- d@1.0.0
```

When I now run `npm shrinkwrap`, it will ignore `b` as a direct dependency of `a` because it is a dev dependency. As npm didn't install `b` in  `c/node_modules`, this won't appear in the shrinkwrap file either.

With this shrinkwrap file, after `npm install --production`, `b` is completely missing:

```
a@1.0.0        
 |- c@1.0.0
    |- d@1.0.0
```

And the application not running. I have tried `--legacy-bundling` with no luck.

Expected result would be

```
a@1.0.0        
 |- c@1.0.0
    |- b@1.0.0
    |- d@1.0.0
```

I figure this is a bug in `npm shrinkwrap` because the warning states:

```
npm WARN shrinkwrap Excluding devDependency: b { 'a': '1.0.0',
npm WARN shrinkwrap   'c': '1.0.0' }
```

_although_ `b` is _not_ a devDepency of `c`.

**Comment by mhart** [comment]
Ha, I was about to post exactly the same issue. npm v2.14.15

Exact same circumstances – in my case `b` in @psorowka's example is `babel-core` and `c` is `babel-register` (which has `babel-core` as a dep)

The only thing I'd disagree on is the expected result. I'd expect it to keep `b` at the top-level, where it was from the dedupe – but just not ignore it.

**Comment by mhart** [comment]
So basically, if any top-level deps are needed because they're a sub-dep of a production dep, then shrinkwrap should not ignore them.

**Comment by psorowka** [comment]
@mhart right, your expected tree makes sense as well. Arguments:

- the expected try I proposed would be the result of a direct `npm install --production` (without shrinkwrap) and thus kind of natural

- the expected tree you proposed would have a cleaner structure **and** (this is a strong argument) would be conform to the tree that existed during development and thus during testing

Either way - it is expected that the sub-dependencies succeed in requiring their sub-sub-dependencies... :)

**Comment by mhart** [comment]
@psorowka yeah, it doesn't really matter as long as at the end of the day it all works :smile_cat: 

I guess the thing that makes this issue hard to fix is that the following steps are probably expensive:

1. For each top-level dev dependency (I assume it's only top-levels that this can happen to)
2. Check all prod dependencies to see if they depend on it at any level *and* don't already have it as a sub-dep
3. If none do, safe to ignore and not add to shrinkwrap. Otherwise, add.

**Comment by mhart** [comment]
Could potentially be optimized by the shrinkwrap algorithm going through each prod dependency once and building a map of any sub-dependencies that are missing in its tree – if any of these are then found at the top-level, then they need to be added to shrinkwrap regardless of whether they're also dev deps or not.

**Comment by zkat** [comment]
Note: There were many, many bugfixes in `npm@3` involving shrinkwrap and deduping. Could you try using `npm@3` and see if it's any better for you?

**Comment by psorowka** [comment]
@zkat you are right, thanks to flat dependency trees in npm@3 this is no issue. But while npm@2 is still the official version for node4 I am curious if this behavior is "by design" or classified as a bug?

**Comment by zkat** [comment]
Fixing this behavior is kind of on the longer-term plan for LTS, since it's... not great. Unfortunately, it's also not on the roadmap to get fixed by one of us soon. We _would_ appreciate patches if anyone volunteers them for a PR, so I've added the `patch-welcome` tag. And, as with all other such taggings, I'm closing this just to keep the number of open issues under control and relevant to the actual plans for the next year. I also slapped `bug` on it for good measure :)

**Comment by zkat** [comment]
Oh oops. It's a bug so I shouldn't close it. sorry about that <3

**Comment by psorowka** [comment]
@zkat so what kind of fix would you think of? I see various possibilities :

- skip automatic dedupe for devdependencies
- not exclude devdependencies from shrinkwrap if they are regular dependency of any sub package
- completely rebuild the dependency tree for production before shrinkwrap 

Regarding the proposed expected trees we have discussed I figure solution 1 and 3 would result in what I proposed whereas the second results in what @mhart proposed.
