### ISSUE TITLE
getting npm results json with limits

### ISSUE THREAD

**Issue by pketh** [npm/npm#11282]
Hi, I’m trying to get npm search data in json format. Also new to couchdb, but when I try: 
[https://registry.npmjs.org/-/_view/byKeyword?startkey=[%22gulp%22]&endkey=[%22gulp%22,%7B%7D]&group_level=3](https://registry.npmjs.org/-/_view/byKeyword?startkey=[%22gulp%22]&endkey=[%22gulp%22,%7B%7D]&group_level=3)

I can get back a huge list of all packages with ‘gulp’. 

But when I try and add a `limit` to the query, I always get 0 results back ... 
[https://registry.npmjs.org/-/_view/byKeyword?startkey=[%22gulp%22]&endkey=[%22gulp%22,%7B%7D]&group_level=3&limit=6](https://registry.npmjs.org/-/_view/byKeyword?startkey=[%22gulp%22]&endkey=[%22gulp%22,%7B%7D]&group_level=3&limit=6)

Do you know what I'm doing wrong?

**Comment by zkat** [comment]
Unfortunately, our registry doesn't support `limit` for the foreseeable future :( It would involve a significant amount of work to change this in our stack, which involves proxying, wrappers, etc -- you're not hitting a real couchdb here.

We do have https://skimdb.npmjs.com/registry if you want to hit a real couch install -- skimdb only includes metadata, but it lacks the views available to the main registry so your particular query won't work.

There are third-party mirrors and some tools available in the registry that you could try installing and see if that serves your purpose, and I hope maybe those can help you do what you're trying to get at. I'm closing this for the time being! Good luck, and thanks for the question :) :) :)

**Comment by pketh** [comment]
Makes sense, thanks for the answer !
