### ISSUE TITLE
Publishing multiple feature branches as tags?

### ISSUE THREAD

**Issue by peterjuras** [npm/npm#11285]
Hi!

I have an npm package and I would like to publish different branches as different tags to the npm repo (privately hosted). However, I'd like to avoid increasing the version, because it would not be possible to keep the version in sync across multiple branches:

branch master: v1.0.0
branch feature/1 v1.0.1 (branched from master)
branch feature/2 v1.0.1 (branched from master)

if I publish these with the specific feature tags (say feature1, feature2) the feature that has been published last will override the other feature, because their versions are the same and according to the [package documentation](https://docs.npmjs.com/misc/developers), a tag is nothing more than a pointer to a version.

How can I avoid this and still publish all branches? (To have them available in development teams)

**Comment by KenanY** [comment]
I'm pretty sure each branch would have to have a unique version.

**Comment by zkat** [comment]
Have you considered using `npm dist-tag` along with prerelease semver versions? See http://semver.org/#spec-item-9 for details. You could easily do:

branch master: `v1.0.0`
branch feature/1: `v1.0.1-feature.1`
branch feature/2: `v1.0.1-feature.2`

If you publish using `npm publish --tag v1.0.1-feature.1`, it won't replace `latest`, so if someone does `npm install @your/repo`, they'll still get `v1.0.0`. You'll have to do `npm install @your/repo@v1.0.1-feature.1` to get the specific features.

How's that?

**Comment by peterjuras** [comment]
That sounds wonderfully suited for my problem! Thanks, I'll try it out! :)

**Comment by felixSchl** [comment]
I have a question regarding workflow: If I create my feature branch, then when do I change my packet json? Should it be the first commit in the feature branch? Do I need to remove that commit before merging back onto the mainline (since I don't want the mainline to use the feature's version)?

**Comment by b-b3rn4rd** [comment]
@zkat similar question regarding workflow, our current approach is following:
1. Github triggers a new build for a feature branch when the new code is pushed
2. Jenkins runs `npm version 1.0.1-feature.${BUILD_ID}` to modify `package.json`
3. Jenkins does the build and uploads to artifactory
4. Does Jenkins need to commit/push updated `package.json`, if it does it will trigger another build, and the process gets stuck in the loop ?

**Comment by icecreammatt** [comment]
@b-b3rn4rd This is probably way late for you but I just dealt with number 4. The solution I used which I don't care for is that when the job runs it checks to see if the last commit was by Jenkins and if it was it skips all of the remaining pipeline steps.

edit: sorry I just noticed the top of this post was from 2016 😬

**Comment by b-b3rn4rd** [comment]
Thanks @icecreammatt , yeah I ended up with a similar solution and wrote a Jenkins plugin to ignore builds from blacklisted users https://github.com/jenkinsci/ignore-committer-strategy-plugin
