### ISSUE TITLE
what's the diffrence between npm cache clean and npm cache clear

### ISSUE THREAD

**Issue by sunnysk** [npm/npm#11281]
I use window10 64-bit os ，when i execute npm cache clean ,that reports a permission error ,then i use npm cache clear , it works ,after that i execute npm cache clean ,it also works , so i wanner know what's the diffrence between clean and clear.

**Comment by KenanY** [comment]
@sunnysk I think they each do the same thing (they are simply aliases of each other)

https://github.com/npm/npm/blob/v3.6.0/lib/cache.js#L118

**Comment by zkat** [comment]
As @KenanY said (Thanks, Kenan!)

Aliases will do the same thing. Closing this as resolved. :)

**Comment by Cogitaria** [comment]
The _npm cache --help_ makes no mention of **clear** nor does the documentation so the alias does more harm than good, causes folks to wonder,  do google searches, post questions about.
