### ISSUE TITLE
I have a probleme when i update node with brew command

### ISSUE THREAD

**Issue by amine2233** [npm/npm#11293]
Hi,
I have a probleme when i have update node with brew, the command like bower exist bat we can't run-it, and when ! have try to update npm, i found this message error

tinks for you help

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/5.5.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   '--force' ]
2 info using npm@3.6.0
3 info using node@v5.5.0
4 warn using --force I sure hope you know what you are doing.
5 silly loadCurrentTree Starting
6 silly install loadCurrentTree
7 silly install readGlobalPackageData
8 silly fetchPackageMetaData .
9 silly fetchOtherPackageData .
10 silly cache add args [ '.', null ]
11 verbose cache add spec .
12 silly cache add parsed spec Result {
12 silly cache add   raw: '.',
12 silly cache add   scope: null,
12 silly cache add   name: null,
12 silly cache add   rawSpec: '.',
12 silly cache add   spec: '/Users/amine',
12 silly cache add   type: 'local' }
13 error addLocal Could not install /Users/amine
14 silly fetchPackageMetaData Error: EISDIR: illegal operation on a directory, read
14 silly fetchPackageMetaData     at Error (native)
14 silly fetchPackageMetaData  error for . { [Error: EISDIR: illegal operation on a directory, read] errno: -21, code: 'EISDIR', syscall: 'read' }
15 silly rollbackFailedOptional Starting
16 silly rollbackFailedOptional Finishing
17 silly runTopLevelLifecycles Starting
18 silly runTopLevelLifecycles Finishing
19 silly install printInstalled
20 verbose stack Error: EISDIR: illegal operation on a directory, read
20 verbose stack     at Error (native)
21 verbose cwd /Users/amine
22 error Darwin 15.3.0
23 error argv "/usr/local/Cellar/node/5.5.0/bin/node" "/usr/local/bin/npm" "install" "-g" "--force"
24 error node v5.5.0
25 error npm  v3.6.0
26 error code EISDIR
27 error errno -21
28 error syscall read
29 error eisdir EISDIR: illegal operation on a directory, read
30 error eisdir This is most likely not a problem with npm itself
30 error eisdir and is related to npm not being able to find a package.json in
30 error eisdir a package you are trying to install.
31 verbose exit [ -21, true ]

**Comment by KenanY** [comment]
@amine2233 From the log, I can see that you are running

```
npm install -g --force
```

That is, you are telling `npm` to install something globally, but you never say what to install! As [the `npm install` documentation](https://docs.npmjs.com/cli/install) states, you need to provide `npm` with module names via either command-line parameters or a `package.json`, but you are not providing either of these. If you would like to install a newer version of `npm`, I recommend trying:

```
npm install -g npm
```

Do note that, if you do not own the directory under which global `npm` modules are located, then you will have to run that command with `sudo` (or `chown` the directory to yourself, or configure the directory to be one which you actually have permission to modify).

Also note that, as I have just realized, you already have the absolute newest version of `npm` (`@3.6.0`) as of this writing!

**Comment by ashleygwilliams** [comment]
closing! @amine2233 please open another issue if you continue to have trouble.

**Comment by amine2233** [comment]
@ashleygwilliams & @KenanY think's its work
