### ISSUE TITLE
License parser doesn't work on website

### ISSUE THREAD

**Issue by infusion** [npm/npm#11296]
Hi,

I just removed the plural "licenses" attributes from my npm projects. As I published the libs under two licenses, I added "MIT OR GPL-2.0" to the package.json. Locally it works fine, but on npmjs.org, a link to exactly that string is added to the site.

**Comment by othiym23** [comment]
This is a known issue with the web site, and is being addressed by npm/newww#996, so head on over there and check on how that's going. Thanks for your time!
