### ISSUE TITLE
Cant install npm

### ISSUE THREAD

**Issue by Hellaphant75** [npm/npm#11295]
I'm getting this error when I try to install 'npm'

```
pattheautomater@Universalnetwork:~$ npm install
npm ERR! install Couldn't read dependencies
npm ERR! Error: ENOENT, open '/home/pattheautomater/package.json'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.16.0-59-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/pattheautomater
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /home/pattheautomater/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pattheautomater/npm-debug.log
npm ERR! not ok code 0
```

**Comment by keithajackson** [comment]
Are you attempting to install a new version of npm?  In this case you would want to run `npm install -g npm`.

Running `npm install` by itself looks for a `package.json` in the current directory and attempts to install packages from it.  The error you're getting is that it couldn't find a `package.json` in your home directory to read.

**Comment by Hellaphant75** [comment]
Wow! Thanks for the timely response! I'll try this out tonight after work.

**Comment by zkat** [comment]
As @keithajackson said -- you should update npm with `npm install -g npm`. `npm install` is going to try and install dependencies for whatever your current working directory is, which is why it's talking about a `package.json` in your home directory. Closing as resolved.
