### ISSUE TITLE
bug with working directory

### ISSUE THREAD

**Issue by evilebottnawi** [npm/npm#11304]
In line https://github.com/npm/npm/blob/34dec08519dcb3930eabb7c5a4d7a60ce50d858a/lib/utils/lifecycle.js#L56
If i install `imagemin-gifsicle`, npm install all deps include `gifsicle`. And this line return `index` of `imagemin-gifsicle`, not `gifsicle`. Detail: https://github.com/imagemin/gifsicle-bin/issues/59#issuecomment-175603778

**Comment by zkat** [comment]
This seems to be a false positive that we're landing a fix for this week. See #10582
