### ISSUE TITLE
Prompt for license - and create LICENSE file

### ISSUE THREAD

**Issue by Ginden** [npm/npm#11301]
Feature request: calling `npm init` and choosing open source license should prompt for creating `LICENSE` file with correct license text.

**Comment by zkat** [comment]
This is a much bigger feature than it seems on the surface -- it would involve writing a package that is able to fetch/somehow grab the individual licenses, make sure they're up to date, and it would involve doing more I/O than `npm init` already does.

We'd be open to something like this, though, in the form of a patch that contains your own custom `npm init` script, so we can look at it and evaluate how usable it actually is in practice.

As with most `patches-welcome` requests, though, I'm closing this until such a patch happens to float by. Thanks for your submission! :)
