### ISSUE TITLE
npm is not installing cordova

### ISSUE THREAD

**Issue by sree-kumar** [npm/npm#11312]
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "D:\\nodejs\\\\node.exe" "D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova"
npm ERR! node v0.12.7
I get the following error when trying to install cordova. Please help me out.

npm ERR! npm  v2.11.3

npm ERR! shasum check failed for C:\Users\SREEKU~1\AppData\Local\Temp\npm-5568-e3930947\registry.npmjs.org\cordova-lib\-
\cordova-li
[npm-debug.log.txt](https://github.com/npm/npm/files/107614/npm-debug.log.txt)

b-5.4.1.tgz
npm ERR! Expected: b15399e6f365568fb13b3b424a260d12206d7061
npm ERR! Actual:   e2164a86352168340fa7a9d0b7a5726711dea3c5
npm ERR! From:     https://registry.npmjs.org/cordova-lib/-/cordova-lib-5.4.1.tgz

**Comment by bluejamesbond** [comment]
Verified that it is working on node 5+ with npm 3+. So try to use `nvm` and update your node

**Comment by sree-kumar** [comment]
Sorry. I couldn't get it.  The lastest version of Node.js is 5.5.
My version is v0.12.7.
Also I don't have nvm.

Could you please elaborate on this.
warm regards,
sree

**Comment by ashleygwilliams** [comment]
hi! @sree-kumar this error is seen often with windows users. can you try `npm set registry https://registry.npmjs.org/`, then try to install cordova again?

**Comment by sree-kumar** [comment]
Thanks Ashley,

I have re-installed Cordova and no problems this time.  However, some
warning messages are coming based on registry.
I shall set the registry as you have suggested.

Thanks again,
warm regards,
sree

**Comment by ashleygwilliams** [comment]
excellent to hear!
