### ISSUE TITLE
Cannot find module 'npmlog' while using npm command

### ISSUE THREAD

**Issue by shahbaz17** [npm/npm#11313]
module.js:341
    throw err;
    ^

Error: Cannot find module 'npmlog'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at /usr/lib/node_modules/npm/bin/npm-cli.js:20:13
    at Object.<anonymous> (/usr/lib/node_modules/npm/bin/npm-cli.js:76:3)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)

How to correct this error?
Using Ubuntu 
3.19.0-47-generic #53~14.04.1-Ubuntu

**Comment by anshulguleria** [comment]
@shahbaz17 Have you installed the module?
`npm install --save nplog`

**Comment by shahbaz17** [comment]
@anshulguleria When i tried above steps i got the same result.
Is there any other way to correct this issue

**Comment by anshulguleria** [comment]
@shahbaz17 What command were you running ?

**Comment by shahbaz17** [comment]
@anshulguleria 
Actually this all started after i tried to install brave browser.
i have upgraded my node and npm to their required version. 
you can have a look at [here](https://github.com/shahbaz17/browser-laptop)

**Comment by anshulguleria** [comment]
Tried installing on my system, it succeeded.

**Comment by PaulNonatomic** [comment]
i'm having the same issue. Just updated node and now `npm install` throws this error
<img width="564" alt="error1" src="https://cloud.githubusercontent.com/assets/4581647/12725717/eb7f128a-c90b-11e5-8ec4-84226a0c5fd5.png">
<img width="559" alt="error2" src="https://cloud.githubusercontent.com/assets/4581647/12725718/eb86a5f4-c90b-11e5-985e-1386461daf20.png">

**Comment by cthurber** [comment]
Having the exact same issue as @PaulNonatomic. Any progress yet? I was working on getting Visual Code to execute C# code with OmniSharp.

**Comment by dwillitzer** [comment]
Bump. I am having same issues as @PaulNonatomic & @cthurber ... Guess I will try to roll back to a previous build until this is resolved.

**Comment by kevart** [comment]
Same error over here. @shahbaz17 closing without any comment sucks.

**Comment by stryd3r** [comment]
same issue for me

**Comment by ericbjones** [comment]
+1. Did anyone ever find a solution other than starting over/reinstalling npm?
