### ISSUE TITLE
Allow npm login with username and password arguments

### ISSUE THREAD

**Issue by Sk1Zy** [npm/npm#11319]
I am using private npm packages and being able to log in without requiring stdin is a requirement for our CI processes.

I'm creating a docker images that performs npm install while building and because we are using private npm packages I am unable to perform the install since it requires me to login.

If i could create ssh keys or provide username and password arguments that would solve the problem.

**Comment by KenanY** [comment]
https://github.com/npm/npm/issues/9325, https://github.com/npm/npm/issues/10920?

**Comment by dankonino** [comment]
@grimurd this is cool thing and works nicely https://www.npmjs.com/package/npm-cli-login
