### ISSUE TITLE
How to unlink a npm command-line tool?

### ISSUE THREAD

**Issue by qiuyuntao** [npm/npm#11311]
I use node to write a command-line tool.

this is the index.js.

```
    #!/usr/bin/env node
    console.log('qiuyuntao');
```

this is the package.json

```
    {
      "name": "qiu",
      "version": "1.0.0",
      "description": "",
      "main": "index.js",
      "scripts": {
        "test": "echo \"Error: no test specified\" && exit 1"
      },
      "author": "",
      "license": "ISC",
      "bin": {
        "qyt": "index.js"
      }
    }
```

After I use command `npm link`, I can use command `qyt` anywhere. Now I want to unlink the `command`, I use `npm unlink`, it said

```
npm ERR! gentlyRm containing path /usr/local/lib/node_modules/qiu isn't under npm's control
npm WARN install:qiu@1.0.0 Refusing to delete: /usr/local/bin/qyt not in /usr/local/lib/node_modules/qiu
- qiu@1.0.0 node_modules/qiu
```

So, what should I do to unlink it?

**Comment by qiuyuntao** [comment]
After delete `/usr/local/bin/qyt` and `/usr/local/lib/node_modules/qiu`, I can still use command `qyt`. It does't echo `qiuyuntao `, but echo `Empty string`.

**Comment by AshCoolman** [comment]
From http://stackoverflow.com/questions/35042547/how-to-unlink-a-npm-command-line-tool/41280442#41280442:

> Updating npm `3.9.5` > `4.0.5` fixed the same issue for me
> 
> Before update:
> 
>     $ npm unlink
>     npm WARN install:@coolman/my-module@1.0.0 Refusing to delete /Users/coolman/.nvm/versions/node/v6.2.0/bin/mymod: ../lib/node_modules/my-module/index-cli.js symlink target is not controlled by npm /Users/coolman/.nvm/versions/node/v6.2.0/lib/node_modules/@coolman/my-module
>     - @coolman/my-module@1.0.0 node_modules/@coolman/my-module
>     
>     $ npm --version
>     3.9.5
> 
> After update:    
> 
>     $ sudo npm install npm@latest -g
>     
>     $ npm --version
>     4.0.5
>     
>     $ npm unlink
>     - @coolman/my-module@1.0.0 node_modules/@coolman/my-module
> 
> And to repeat `npm link`, I needed to manually remove the bin:
> 
> 
>     $ npm link
>     npm WARN @my-company/my-module@1.0.0 No repository field.
>     npm ERR! Darwin 16.1.0
>     npm ERR! argv "/Users/coolman/.nvm/versions/node/v6.2.0/bin/node" "/Users/coolman/.nvm/versions/node/v6.2.0/bin/npm" "link"
>     npm ERR! node v6.2.0
>     npm ERR! npm  v4.0.5
>     npm ERR! path /Users/coolman/.nvm/versions/node/v6.2.0/bin/mymod
>     npm ERR! code EEXIST
>     
>     npm ERR! Refusing to delete /Users/coolman/.nvm/versions/node/v6.2.0/bin/mymod: ../lib/node_modules/my-module/index-cli.js symlink target is not controlled by npm /Users/coolman/my-company/tools/my-module
>     npm ERR! File exists: /Users/coolman/.nvm/versions/node/v6.2.0/bin/mymod
>     npm ERR! Move it away, and try again.
>     
>     npm ERR! Please include the following file with any support request:
>     npm ERR!     /Users/coolman/my-company/tools/my-module/npm-debug.log
>     
>     
>     $ rm /Users/coolman/.nvm/versions/node/v6.2.0/bin/mymod
>     
>     $ npm link
>     npm WARN @coolman/my-module@1.0.0 No repository field.
>     /Users/coolman/.nvm/versions/node/v6.2.0/bin/mymod -> /Users/coolman/.nvm/versions/node/v6.2.0/lib/node_modules/@coolman/my-module/index-cli.js
>     /Users/coolman/.nvm/versions/node/v6.2.0/lib/node_modules/@coolman/my-module -> /Users/coolman/perkbox/tools/run-with-pb-session
> 
> 
>
