### ISSUE TITLE
Error while installing ionic framework

### ISSUE THREAD

**Issue by dipalivaidya** [npm/npm#11318]
shasum check failed for /var/folders/gf/l4rngr3x01j4qzs8x3wy0mj00000gp/T/npm-74294-842af1d7/registry.npmjs.org/ionic/-/ionic-1.7.13.tgz

Expected: 0a16c0aea3280acd406938d31165fc0f2d258e06
npm ERR! Actual:   25103387ae75677fbf5942f7f828e98155823cbc
npm ERR! From:     https://registry.npmjs.org/ionic/-/ionic-1.7.13.tgz
[npm-debug.log.zip](https://github.com/npm/npm/files/108075/npm-debug.log.zip)

Please help.

**Comment by ashleygwilliams** [comment]
hi! @dipalivaidya this error is seen often with windows users. can you try `npm set registry https://registry.npmjs.org/`, then try to install ionic again?

**Comment by ashleygwilliams** [comment]
hi! since there has been no action on this ticket in 10 days i am closing it. i hope you solved your problem! if you continue to have trouble please file a new issue.
