### ISSUE TITLE
After running command - npm run bundle-js      <--- I am getting ERR!

### ISSUE THREAD

**Issue by panu1186** [npm/npm#11314]
After running command - npm run bundle-js      <--- I am getting following ERR! in the npm-debug.log file

```
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'bundle-js' ]
2 info using npm@3.3.12
3 info using node@v5.5.0
4 verbose stack Error: missing script: bundle-js
4 verbose stack     at run (D:\Program Files\nodejs\node_modules\npm\lib\run-script.js:147:19)
4 verbose stack     at D:\Program Files\nodejs\node_modules\npm\lib\run-script.js:57:5
4 verbose stack     at D:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:345:5
4 verbose stack     at checkBinReferences_ (D:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:309:45)
4 verbose stack     at final (D:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:343:3)
4 verbose stack     at then (D:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:113:5)
4 verbose stack     at D:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:300:12
4 verbose stack     at D:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:76:16
4 verbose stack     at tryToString (fs.js:414:3)
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
5 verbose cwd E:\ece\gwm
6 error Windows_NT 6.1.7601
7 error argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "bundle-js"
8 error node v5.5.0
9 error npm  v3.3.12
10 error missing script: bundle-js
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```

**Comment by othiym23** [comment]
What were  you trying to do when you ran this? Is there a "scripts" stanza in `E:\ece\gwm\package.json`? If there is, is there a script for "bundle-js"?

**Comment by anshulguleria** [comment]
@panu1186  Looking at debug:
`4 verbose stack Error: missing script: bundle-js`
It seems like you haven't created `bundle-js` script yet.
Can you show your `package.json` file also to be more sure?

**Comment by panu1186** [comment]
{
  "scripts": {
    "watch": "webpack -w -d"
  },
  "devDependencies": {
    "babel-core": "^6.4.0",
    "babel-loader": "^6.2.1",
    "babel-preset-es2015": "^6.3.13",
    "babel-preset-react": "^6.3.13",
    "expose-loader": "^0.7.1",
    "redux-devtools": "^3.0.1",
    "redux-devtools-dock-monitor": "^1.0.1",
    "redux-devtools-log-monitor": "^1.0.1",
    "webpack": "^1.12.10",
    "webpack-dev-server": "^1.14.0"
  },
  "dependencies": {
    "react": "^0.14.6",
    "react-dom": "^0.14.6",
    "react-redux": "^4.0.6",
    "react-router": "^2.0.0-rc5",
    "redux": "^3.0.5",
    "redux-simple-router": "^2.0.1"
  },
  "babel": {
    "presets": [
      "es2015",
      "react"
    ]
  },
  "browser": {
    "jquery": "./proj/PROJ/Content/js/jquery",
    "accordion": "./proj/PROJ/Content/js/accordion/accordion",
    "actionButtons": "./proj/PROJ/Content/js/actionButtons/actionButtons",
    "approvalControls":
"./proj/PROJ/Content/js/approvalControls/approvalControls",
    "ajax": "./proj/PROJ/Content/js/ajax",
    "async": "./proj/PROJ/Content/js/async",
    "bus": "./proj/PROJ/Content/js/bus",
    "checkBoxGroup": "./proj/PROJ/Content/js/checkBoxGroup/checkBoxGroup",
    "colorPicker": "./proj/PROJ/Content/js/colorPicker/colorPicker",
    "controlFactory": "./proj/PROJ/Content/js/controlFactory",
    "customizableSelect":
"./proj/PROJ/Content/js/customizableSelect/customizableSelect",
    "combobox": "./proj/PROJ/Content/js/combobox/combobox",
    "documentDownloader":
"./proj/PROJ/Content/js/documentDownloader/documentDownloader",
    "documentSection":
"./proj/PROJ/Content/js/documentSection/documentSection",
    "documentUploader":
"./proj/PROJ/Content/js/documentUploader/documentUploader",
    "eceControl": "./proj/PROJ/Content/js/eceControl/eceControl",
    "eceControlLocator":
"./proj/PROJ/Content/js/eceControl/eceControlLocator",
    "eceControlValues":
"./proj/PROJ/Content/js/eceControl/eceControlValues",
    "eceValidation": "./proj/PROJ/Content/js/eceControl/eceValidation",
    "fields": "./proj/PROJ/Content/js/fields",
    "fieldValidation":
"./proj/PROJ/Content/js/fieldValidation/fieldValidation",
    "formHeader": "./proj/PROJ/Content/js/formHeader/formHeader",
    "hasDiff": "./proj/PROJ/Content/js/hasDiff",
    "imageUploader": "./proj/PROJ/Content/js/imageUploader/imageUploader",
    "isFunction": "./proj/PROJ/Content/js/isFunction",
    "isNullOrUndefined": "./proj/PROJ/Content/js/isNullOrUndefined",
    "libraryFormHeader":
"./proj/PROJ/Content/js/libraryFormHeader/libraryFormHeader",
    "libraryItemSelector":
"./proj/PROJ/Content/js/libraryItemSelector/libraryItemSelector",
    "math": "./proj/PROJ/Content/js/math",
    "nav": "./proj/PROJ/Content/js/nav",
    "normalizeValue": "./proj/PROJ/Content/js/normalizeValue",
    "pageData": "./proj/PROJ/Content/js/pageData",
    "revisionControls":
"./proj/PROJ/Content/js/revisionControls/revisionControls",
    "radioGroup": "./proj/PROJ/Content/js/radioGroup/radioGroup",
    "screenActivator":
"./proj/PROJ/Content/js/screenActivator/screenActivator",
    "screens": "./proj/PROJ/Content/js/screens/screens",
    "screenState": "./proj/PROJ/Content/js/screenState/screenState",
    "sectionFinder": "./proj/PROJ/Content/js/sectionFinder",
    "selectionField":
"./proj/PROJ/Content/js/selectionField/selectionField",
    "smartSearch": "./proj/PROJ/Content/js/smartSearch/smartSearch",
    "tradeOrBrandNameLogic": "./proj/PROJ/Content/js/tradeOrBrandNameLogic",
    "unencodeJsonAttribute": "./proj/PROJ/Content/js/unencodeJsonAttribute",
    "unitControls": "./proj/PROJ/Content/js/unitControls/unitControls",
    "unitsComboBox": "./proj/PROJ/Content/js/unitsComboBox/unitsComboBox",
    "unitsTextBox": "./proj/PROJ/Content/js/unitsTextBox/unitsTextBox",
    "listTemplate": "./proj/PROJ/Content/js/listTemplate/listTemplate"
  }
}

**Comment by anshulguleria** [comment]
@panu1186 In your scripts section:
```js
 "scripts": { "watch": "webpack -w -d" },
```
You don't have any `bundle-js` script. You need to add some script for it.

```js
// example
 "scripts": { 
    "watch": "webpack -w -d",
    "bundle-js": "echo \"Bundle js\""
 },

**Comment by panu1186** [comment]
now I need to babelify using command - npm install -g babelify command

Isn't it?

**Comment by panu1186** [comment]
now I need to babelify using command - npm install -g babelify command

Isn't it?

**Comment by anshulguleria** [comment]
Its better if you show your errors also but if you are trying to bundle with `babelify` transform on `browserify` I have a [gitst](https://gist.github.com/anshulguleria/0c244aa6f9311fc3128a), have a look it might help.

**Comment by panu1186** [comment]
I fired both the commands which are executed without errors but still I could not bundle the js.
getting Error -

Error: Cannot find module 'babelify' from 'E:\Pro\proj\script'
    at C:\Users\isxx\AppData\Roaming\npm\node_modules\browserify\node_modules\resolve\lib\async.js:46:17
    at process (C:\Users\isxx\AppData\Roaming\npm\node_modules\browserify\node_modules\resolve\lib\async.js:173:43)
    at ondir (C:\Users\isxx\AppData\Roaming\npm\node_modules\browserify\node_modules\resolve\lib\async.js:188:17)
    at load (C:\Users\isxx\AppData\Roaming\npm\node_modules\browserify\node_modules\resolve\lib\async.js:69:43)
    at onex (C:\Users\isxx\AppData\Roaming\npm\node_modules\browserify\node_modules\resolve\lib\async.js:92:31)
    at C:\Users\isxx\AppData\Roaming\npm\node_modules\browserify\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)

**Comment by anshulguleria** [comment]
You have to install `babelify` as local dependency.
`npm install --save-dev babelify`
Refer official [babelify repo](https://github.com/babel/babelify) for usage documentation. Also I have used in my [gist](https://gist.github.com/anshulguleria/0c244aa6f9311fc3128a) above also. You can refer there also.

**Comment by othiym23** [comment]
This no longer looks like an npm issue, and so I'm going to close it. Thanks for helping @panu1186, @anshulguleria, and good luck to you, @panu1186, in getting Babel + browserify figured out!
