### ISSUE TITLE
`npm login` returns `npm ERR! cb() never called!` from one liner in docker

### ISSUE THREAD

**Issue by willfarrell** [npm/npm#11320]
I'm trying to setup the npm creds to a private npm repo during my docker build. The repo is behind a firewall and auth is set to open, so any creds will work (however passing in dummy creds is required).

Dockerfile

``` Dockerfile
FROM library/node:latest
# There is extra magic hind this to actually get npm to update, but trying to keep it simple here.
# https://github.com/npm/npm/issues/9863
RUN npm update -g 

ENV NPM_PRIVATE_REGISTRY http://example.com:8080

COPY npm_login /npm_login
RUN ./npm_login
```

npm_login

``` bash
echo "Try 1"
npm login --registry=$NPM_PRIVATE_REGISTRY <<!
npm
password
npm@watsco.com
!

echo "Try 2"

npm login --registry=$NPM_PRIVATE_REGISTRY << EOF
npm
password
npm@watsco.com
EOF

echo "Try 3"
npm login --registry=$NPM_PRIVATE_REGISTRY <<< "npm
password
npm@watsco.com
"

echo "Try 4"
printf 'npm\npassword\nnpm@watsco.com\n' | npm login --registry=$NPM_PRIVATE_REGISTRY
```

Console Output

``` bash
...
Try 1
npm info it worked if it ends with ok
npm info using npm@3.6.0
npm info using node@v5.5.0
Username: Password: npm ERR! cb() never called!
Try 2
npm info it worked if it ends with ok
npm info using npm@3.6.0
npm info using node@v5.5.0
Username: Password: npm ERR! cb() never called!
Try 3
npm info it worked if it ends with ok
npm info using npm@3.6.0
npm info using node@v5.5.0
Username: Password: npm ERR! cb() never called!
Try 4
npm info it worked if it ends with ok
npm info using npm@3.6.0
npm info using node@v5.5.0
Username: Password: npm ERR! cb() never called!
...
```

The `npm_login` script works on Mac OSX. Is there another way to pass in the creds? Or an attribute to send dummy creds for this use case?

**Comment by konradjurk** [comment]
I'm facing the same issue. Did you find a solution?

**Comment by Nemesis9765** [comment]
+1 to this issue, I'm experiencing the same issue while trying to integrate automatic npm publishing in gitlab-ci.

While trying with npm 3.8.8,
```
$ echo -e "$NPM_USERNAME\n$NPM_PASSWORD\n$NPM_EMAIL" | npm --always-auth --loglevel=verbose --registry=https://internalrepo.local login
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   '--always-auth',
npm verb cli   '--loglevel=verbose',
npm verb cli   '--registry=https://internalrepo.local',
npm verb cli   'login' ]
npm info using npm@3.8.8
npm info using node@v4.4.3
Username: Password: npm ERR! cb() never called!
```

While trying with npm 1.3,
```
$ echo -e "$NPM_USERNAME\n$NPM_PASSWORD\n$NPM_EMAIL" | npm --always-auth --loglevel=verbose --registry=https://internalrepo.local login
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   '--always-auth',
npm verb cli   '--loglevel=verbose',
npm verb cli   '--registry=https://internalrepo.local',
npm verb cli   'login' ]
npm info using npm@1.3.26
npm info using node@v4.4.3
Username: Password: npm ERR! cb() never called!
npm ERR! not ok code 0

ERROR: Build failed: exit code 1
```

**Comment by asaf** [comment]
The problem is that there's no tty, I don't think it's possible to perform this interactive trick,

I solved it by running
`npm login` via shell, once logged in, I echoed the authToken to the .npmrc file by

`echo '//someRepo/:_authToken=SomeToken.. >> ~/.npmrc`

(I'm not sure if tokens expires though)

**Comment by Jackyjjc** [comment]
same problem here.

```
docker run --env NPM_USER=jchen --env NPM_PASS=ksjfklasdf 9f8921a53646
npm info it worked if it ends with ok
npm info using npm@3.9.5
npm info using node@v6.2.2
Username: Password: npm ERR! cb() never called!
```

The script was:
```
#!/bin/bash
set -e -o pipefail

npm login --registry=https://npm-private << MULTILINE
$NPM_USER
$NPM_PASS
myemail@gmail.com
MULTILINE
```

**Comment by leoselig** [comment]
As mentioned in https://github.com/npm/npm/issues/13827 you can use
```sh
echo -e "$NPM_USERNAME\n$NPM_PASSWORD\n$NPM_EMAIL" | npm login
```
(https://glebbahmutov.com/blog/automatically-publish-to-npm/)

**Comment by webmutation** [comment]
@leoselig It may work for some CI solutions but in bamboo for instance it does not work :/

**Comment by awltux** [comment]
The expect utility seems to cope with the bamboo tty quirks (assuming it's installed). 
This is connecting to a Sinopia NPM proxy/server

` #!/bin/bash
`
`
`
`  # Escape passwords that contain the characters '/', '!', '$' and '.'
`
`  ESCAPED_NPM_REGISTRY_PASSWORD=$(echo "${NPM_REGISTRY_PASSWORD}" | sed -e 's/[\/\!\$\.&]/\\&/g' )
`
`
`
`  # Log into the internal registry
`
`  /usr/bin/expect <<HEREDOC
`
`    spawn npm login http://${NPM_REGISTRY_HOST}:${NPM_REGISTRY_PORT}
`
`    expect "Username:"
`
`    send "${NPM_REGISTRY_USER}\n"
`
`    expect "Password:"
`
`    send "${ESCAPED_NPM_REGISTRY_PASSWORD}\n"
`
`    expect Email:
`
`    send "${NPM_REGISTRY_EMAIL}\n"
`
`    expect eof
`
`HEREDOC
`

**Comment by andersekdahl** [comment]
I've finally been able to route around this. It's quite a bit of a hack, but what we're doing is:

1. `const npmLogin = child_process.spawn('npm', ['login'])`
1. Then:
  ```
  npmLogin.stdin.write(username + '\n');
  npmLogin.stdin.write(password + '\n');
  npmLogin.stdin.write(email + '\n');
  ```
1. First I then tried to do `npmLogin.stdin.end();` directly after, but that causes the `ERR! cb() never called!` error. So instead I listen to output from the process and once it says `Logged in as ...` I call `npmLogin.stdin.end();`
1. Then I wait for the npm process to exit and look at the exit code.

This works for me locally and on our TeamCity server.

**Comment by ekryski** [comment]
None of the solutions worked for me. I had to use this https://www.npmjs.com/package/npm-cli-login. Which is pretty silly that this is even an issue...

**Comment by BrysonR** [comment]
I finally figured out how to make this work. To begin with, you will need an auth token. This is easily obtainable by locally running `npm adduser` and then grabbing it from your `~/.npmrc`. In order to be authenticated on your deploy server this auth token needs to be appended to the registry URL in the user's `.npmrc` (similar to how it was locally), not the `.npmrc` located in the repo, so this worked great as script steps in my CI configuration

`- echo "//<npm-registry>:8080/:_authToken=$AUTH_TOKEN" > ~/.npmrc`
`- npm publish`

where AUTH_TOKEN is stored as a secret variable in your settings.
A good way to test this is to replace `npm publish` with `npm whoami` to test and make sure it successfully logged you in. 

Here is my entire publish configuration

```
publish:
  stage: deploy
  only:
    - tags
  script:
    - yarn run build
    - echo "//<npm-registry>:8080/:_authToken=$NPME_AUTH_TOKEN" > ~/.npmrc
    - npm publish
    - echo 'Congrats on your publication!'
```

I'm using gitlab-ci but I don't see why this wouldn't apply to any CI service.
