### ISSUE TITLE
Disabling cache completely

### ISSUE THREAD

**Issue by bountin** [npm/npm#11338]
Is it possible to completely disable npm's cache so that nothing is read or written from cache? I'd like to keep the installation run time and disk usage as low as possible for a docker installation.

Setting the cache directory to /dev/null does not work as npm tries to creates folders there.

**Comment by jerroydmoore** [comment]
+1 this. We're having corrupted cached packages on our build server that then causes all subsequent builds to fail.

**Comment by othiym23** [comment]
The short answer is no, it's not possible to bypass the CLI's cache.

The installer always unpacks package tarballs from the cache (even in the case of git dependencies, which are also kept in a different area of the cache), and so every package to be installed must at some point find its way into the cache. Given the current implementation of the CLI, removing the dependency on the cache would amount to a rewrite of about 1/2 of the installer (maybe slightly less, but almost all the complexity in npm that isn't part of the installer is in the caching code).

The CLI team has plans to partially redesign the caching logic, but that's with the intent of making the cache more efficient and robust (by making it a content-addressable store), and to more cleanly decouple it from the networking logic code while also minimizing the number of roundtrips the CLI makes to the registry. Even then, it's not going to be possible to avoid using an intermediate location to examine and partially process packages, thanks to features like shrinkwrap and `bundledDependencies`, which require the CLI to examine the package's contents (dealing with shrinkwrapping and `bundledDependencies` considerably complicates npm's installer, but they're valuable parts of the product, and at least one of them is relied upon by npm itself). As I hope this demonstrates, the cache kind of has to remain integral to npm's operation.

If build times within containers is a blocking issue for your teams, you may want to consider creating deployment branches for your applications, where you check in completely built package trees (including built native modules) to Git, and then check those branches out to your containers, which will greatly reduce the amount of stress on AUFS.

I'm going to close this issue now, as I think I've answered the original question, and also made clear that this isn't something that the CLI team can afford to change. Thanks for your time, and I hope you find this explanation useful.

**Comment by bountin** [comment]
Thanks for your detailed answer!

**Comment by SimenB** [comment]
For us it's simply a matter of keeping disk usage down, so we just do `npm install && npm cache clean (&& npm uninstall --global npm)`

**Comment by rubicks** [comment]
I may have a workaround:

    $ npm config set cache $(mktemp -d)

Can anyone more familiar with npm say if that actually works?

**Comment by cdaringe** [comment]
it's difficult when switching context between between registries (i know, I'm 1% use case). `npm install` grabs things from the cache, which creates a headache when you're doing things like `npm shrinkwrap`.  shrink-wrapped content can now mix registries, which is often taboo
