### ISSUE TITLE
Unable to install ionic, getting SSL error!

### ISSUE THREAD

**Issue by RastogiSaurabh** [npm/npm#11331]
npm http GET https://registry.npmjs.org/cordova
npm http GET https://registry.npmjs.org/ionic
npm http GET https://registry.npmjs.org/cordova
npm http GET https://registry.npmjs.org/ionic
npm http GET https://registry.npmjs.org/cordova
npm http GET https://registry.npmjs.org/ionic
npm ERR! Error: SSL Error: CERT_UNTRUSTED
npm ERR!     at ClientRequest.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\main.js:440:26)
npm ERR!     at ClientRequest.g (events.js:156:14)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1256:7)
npm ERR!     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:91:29)
npm ERR!     at CleartextStream.socketOnData [as ondata] (http.js:1288:20)
npm ERR!     at CleartextStream._push (tls.js:375:27)
npm ERR!     at SecurePair.cycle (tls.js:734:20)
npm ERR!     at EncryptedStream.write (tls.js:130:13)
npm ERR!     at Socket.ondata (stream.js:38:26)
npm ERR!  [Error: SSL Error: CERT_UNTRUSTED]
npm ERR! You may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "co
rdova" "ionic"
npm ERR! cwd C:\Ionic
npm ERR! node -v v0.6.20
npm ERR! npm -v 1.1.37
npm ERR! message SSL Error: CERT_UNTRUSTED
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Ionic\npm-debug.log
npm ERR! not ok code undefined
npm ERR! not ok code 1

**Comment by KenanY** [comment]
@RastogiSaurabh Node.js v0.6 and `npm@1.1` are several years old and have not been supported for quite some time. Upgrade Node.js and `npm`.

**Comment by ashleygwilliams** [comment]
hi @RastogiSaurabh please update to npm2 or npm3 and node > `0.8`. if you continue to have issues, please open a new issue. thanks!
