### ISSUE TITLE
npm install won't install devDependencies

### ISSUE THREAD

**Issue by hobcode** [npm/npm#11337]
Using package.json:
```
{
  "dependencies": {
    "jquery": "^3.0.0-beta1"
  },
  "devDependencies": {
    "gulp": "^3.9.0"
  }
}
```

And I have:
```
$ npm i
/Users/hob/Code/test
└── jquery@3.0.0-beta1 

npm WARN test No description
npm WARN test No repository field.
npm WARN test No license field.
$ npm -v && node -v
3.6.0
v5.5.0
```

**Comment by KenanY** [comment]
I cannot reproduce this

``` sh
$ npm --version
3.6.0
$ npm install
$ npm ls --depth 0
/tmp/npm-11337
├── gulp@3.9.0
└── jquery@3.0.0-beta1
```

Not sure why are you getting a different result. `npm config get production` returns `false`?

**Comment by hobcode** [comment]
May be any problem with my environment?
Yes, `npm config get production` returns `false`.

**Comment by ashleygwilliams** [comment]
hi! i also cannot reproduce this, using the same npm and node versions you have. can you run `npm ls --depth=0` as well as the `node_modules` directory tree? 

(a nice way to print the tree to console is `tree`, instructions on installation here: http://superuser.com/questions/359723/mac-os-x-equivalent-of-the-ubuntu-tree-command)

**Comment by hobcode** [comment]
Did I understand you correctly?

```
{
  "dependencies": {
    "jquery": "^3.0.0-beta1"
  },
  "devDependencies": {
    "gulp": "^3.9.0"
  }
}
```

```
$ npm i
/Users/hob/Code/test
└── jquery@3.0.0-beta1 

npm WARN test No description
npm WARN test No repository field.
npm WARN test No license field.
$ npm -v
3.7.1
$ npm ls --depth=0
/Users/hob/Code/test
└── jquery@3.0.0-beta1

$ npm ls --depth=0 -g
/usr/local/lib
├── bower@1.7.7
├── gulp@3.9.0
└── npm@3.7.1
```

**Comment by canvaskisa** [comment]
@hobcode Maybe you've got global `NODE_ENV=production` variable. NPM depends on it too.

**Comment by hobcode** [comment]
I don't know what happened but it works now! Right after this commands:
```
$ npm config get production
false
$ npm -g config get production
false
```
