### ISSUE TITLE
Permission denied (publickey).

### ISSUE THREAD

**Issue by chinachuner** [npm/npm#11339]
2037 verbose addNamed "2.11.1" is a plain semver version for browser-sync
2038 silly cache afterAdd browser-sync@2.11.1
2039 verbose afterAdd /Users/zhangrain/.npm/browser-sync/2.11.1/package/package.json not in flight; writing
2040 verbose afterAdd /Users/zhangrain/.npm/browser-sync/2.11.1/package/package.json written
2041 verbose git clone --template=/Users/zhangrain/.npm/_git-remotes/_templates --mirror git://github.com/douglasduteil/karma-coverage.git /Users/zhangrain/.npm/_git-remotes/git-github-com-douglasduteil-karma-coverage-git-next-d32aed5e0a3c01d55161c3f5246b32df: Cloning into bare repository '/Users/zhangrain/.npm/_git-remotes/git-github-com-douglasduteil-karma-coverage-git-next-d32aed5e0a3c01d55161c3f5246b32df'...
2041 verbose git clone --template=/Users/zhangrain/.npm/_git-remotes/_templates --mirror git://github.com/douglasduteil/karma-coverage.git /Users/zhangrain/.npm/_git-remotes/git-github-com-douglasduteil-karma-coverage-git-next-d32aed5e0a3c01d55161c3f5246b32df: fatal: unable to connect to github.com:
2041 verbose git clone --template=/Users/zhangrain/.npm/_git-remotes/_templates --mirror git://github.com/douglasduteil/karma-coverage.git /Users/zhangrain/.npm/_git-remotes/git-github-com-douglasduteil-karma-coverage-git-next-d32aed5e0a3c01d55161c3f5246b32df: github.com[0: 192.30.252.131]: errno=Operation timed out
2042 silly tryHTTPS attempting to clone git+https://github.com/douglasduteil/karma-coverage.git#next
2043 silly tryClone cloning douglasduteil/karma-coverage#next via git+https://github.com/douglasduteil/karma-coverage.git#next
2044 verbose tryClone git-https-github-com-douglasduteil-karma-coverage-git-next-e7b8d848bee87642720b4272be79a443 not in flight; caching
2045 info git [ 'clone',
2045 info git   '--template=/Users/zhangrain/.npm/_git-remotes/_templates',
2045 info git   '--mirror',
2045 info git   'https://github.com/douglasduteil/karma-coverage.git',
2045 info git   '/Users/zhangrain/.npm/_git-remotes/git-https-github-com-douglasduteil-karma-coverage-git-next-e7b8d848bee87642720b4272be79a443' ]
2046 verbose git clone --template=/Users/zhangrain/.npm/_git-remotes/_templates --mirror https://github.com/douglasduteil/karma-coverage.git /Users/zhangrain/.npm/_git-remotes/git-https-github-com-douglasduteil-karma-coverage-git-next-e7b8d848bee87642720b4272be79a443: Cloning into bare repository '/Users/zhangrain/.npm/_git-remotes/git-https-github-com-douglasduteil-karma-coverage-git-next-e7b8d848bee87642720b4272be79a443'...
2046 verbose git clone --template=/Users/zhangrain/.npm/_git-remotes/_templates --mirror https://github.com/douglasduteil/karma-coverage.git /Users/zhangrain/.npm/_git-remotes/git-https-github-com-douglasduteil-karma-coverage-git-next-e7b8d848bee87642720b4272be79a443: fatal: unable to access 'https://github.com/douglasduteil/karma-coverage.git/': Failed to connect to github.com port 443: Operation timed out
2047 silly trySSH attempting to clone git@github.com:douglasduteil/karma-coverage.git#next
2048 silly tryClone cloning douglasduteil/karma-coverage#next via git@github.com:douglasduteil/karma-coverage.git#next
2049 verbose tryClone git-github-com-douglasduteil-karma-coverage-git-next-3906f9680cf44460598daf8b4243b742 not in flight; caching
2050 info git [ 'config', '--get', 'remote.origin.url' ]
2051 silly validateExistingRemote douglasduteil/karma-coverage#next remote.origin.url: git@github.com:douglasduteil/karma-coverage.git
2052 verbose validateExistingRemote douglasduteil/karma-coverage#next is updating existing cached remote /Users/zhangrain/.npm/_git-remotes/git-github-com-douglasduteil-karma-coverage-git-next-3906f9680cf44460598daf8b4243b742
2053 info git [ 'fetch', '-a', 'origin' ]
2054 error git fetch -a origin (git@github.com:douglasduteil/karma-coverage.git) Permission denied (publickey).
2054 error git fetch -a origin (git@github.com:douglasduteil/karma-coverage.git) fatal: Could not read from remote repository.
2054 error git fetch -a origin (git@github.com:douglasduteil/karma-coverage.git)
2054 error git fetch -a origin (git@github.com:douglasduteil/karma-coverage.git) Please make sure you have the correct access rights
2054 error git fetch -a origin (git@github.com:douglasduteil/karma-coverage.git) and the repository exists.
2055 silly fetchPackageMetaData Error: Command failed: git fetch -a origin
2055 silly fetchPackageMetaData Permission denied (publickey).
2055 silly fetchPackageMetaData fatal: Could not read from remote repository.
2055 silly fetchPackageMetaData
2055 silly fetchPackageMetaData Please make sure you have the correct access rights
2055 silly fetchPackageMetaData and the repository exists.
2055 silly fetchPackageMetaData
2055 silly fetchPackageMetaData     at ChildProcess.exithandler (child_process.js:213:12)
2055 silly fetchPackageMetaData     at emitTwo (events.js:100:13)
2055 silly fetchPackageMetaData     at ChildProcess.emit (events.js:185:7)
2055 silly fetchPackageMetaData     at maybeClose (internal/child_process.js:821:16)
2055 silly fetchPackageMetaData     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
2055 silly fetchPackageMetaData  error for karma-coverage@github:douglasduteil/karma-coverage#next { [Error: Command failed: git fetch -a origin
2055 silly fetchPackageMetaData Permission denied (publickey).
2055 silly fetchPackageMetaData fatal: Could not read from remote repository.
2055 silly fetchPackageMetaData
2055 silly fetchPackageMetaData Please make sure you have the correct access rights
2055 silly fetchPackageMetaData and the repository exists.
2055 silly fetchPackageMetaData ]
2055 silly fetchPackageMetaData   killed: false,
2055 silly fetchPackageMetaData   code: 128,
2055 silly fetchPackageMetaData   signal: null,
2055 silly fetchPackageMetaData   cmd: 'git fetch -a origin' }
2056 silly rollbackFailedOptional Starting
2057 silly rollbackFailedOptional Finishing
2058 silly runTopLevelLifecycles Starting
2059 silly runTopLevelLifecycles Finishing
2060 silly install printInstalled
2061 verbose stack Error: Command failed: git fetch -a origin
2061 verbose stack Permission denied (publickey).
2061 verbose stack fatal: Could not read from remote repository.
2061 verbose stack
2061 verbose stack Please make sure you have the correct access rights
2061 verbose stack and the repository exists.
2061 verbose stack
2061 verbose stack     at ChildProcess.exithandler (child_process.js:213:12)
2061 verbose stack     at emitTwo (events.js:100:13)
2061 verbose stack     at ChildProcess.emit (events.js:185:7)
2061 verbose stack     at maybeClose (internal/child_process.js:821:16)
2061 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
2062 verbose cwd /Users/zhangrain/Documents/FE/BP-FE
2063 error Darwin 15.3.0
2064 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
2065 error node v5.5.0
2066 error npm  v3.3.12
2067 error code 128
2068 error Command failed: git fetch -a origin
2068 error Permission denied (publickey).
2068 error fatal: Could not read from remote repository.
2068 error
2068 error Please make sure you have the correct access rights
2068 error and the repository exists.
2069 error If you need help, you may report this error at:
2069 error     https://github.com/npm/npm/issues
2070 verbose exit [ 1, true ]

**Comment by STRML** [comment]
Not an npm bug, just appears that you're loading a GitHub dependency but your SSH key is missing or not linked to your account.

Relevant logging is:

```
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
