### ISSUE TITLE
npm ERR! Version not changed

### ISSUE THREAD

**Issue by harshadbankar** [npm/npm#11342]
I am using maven front end plugin for npm and node scipts, but npm version is failing with "[ERROR] npm ERR! Version not changed", when my package.json is has same version as that of command line version value. Any idea on how to override the package.json version if already exists same version?

**Comment by KenanY** [comment]
@harshadbankar What would you like to happen when you run `npm version 1.0.0` where `1.0.0` is already the `"version"` defined in your `package.json`?

**Comment by harshadbankar** [comment]
I just want npm not to complain about this on console, as it makes my maven front end build to fail, and in maven front end plugin, option of "failOnError" is not working. 


Thanks for reply @KenanY

**Comment by thybzi** [comment]
If you had already commited new version number into your `package.json`, just type `npm publish`, and npm will get your updated version of module

**Comment by harshadbankar** [comment]
Hi , i am not pushing this to git, just updating my local package.json, npm publish not working for me

**Comment by romero83** [comment]
Hi,

You can do it by using com.google.code.maven-replacer-plugin replacer maven plugin.

```
...
<build>
      <plugins>
	<plugin>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>build-helper-maven-plugin</artifactId>
            <version>${build-helper-maven-plugin.version}</version>
            <executions>
               <execution>
                  <phase>validate</phase>
                  <id>parse-version</id>
                  <goals>
                     <goal>parse-version</goal>
                  </goals>
                  <configuration>
                     <propertyPrefix>parsedVersion</propertyPrefix>
                  </configuration>
               </execution>
            </executions>
         </plugin>
         <plugin>
            <groupId>com.google.code.maven-replacer-plugin</groupId>
            <artifactId>replacer</artifactId>
            <version>1.5.3</version>
            <executions>
               <execution>
                  <phase>generate-sources</phase>
                  <goals>
                     <goal>replace</goal>
                  </goals>
               </execution>
            </executions>
            <configuration>
               <file>package.json</file>
               <replacements>
                  <replacement>
                     <token>"version": "(.*)",</token>
                     <value>"version": "${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.incrementalVersion}",</value>
                  </replacement>
               </replacements>
            </configuration>
         </plugin>
...
```

**Comment by lucastheisen** [comment]
I am attempting to do the exact same thing.  I have my maven project manage the version number of the project as a whole.  In my case, there are associated server side java REST services that are consumed by my SPA app.  So i have one large multi-module project of which one module is this javascript project.  All modules use the same version (coming from the parent project).  So, it just makes sense to push that version into the `package.json`.  While a solution like `maven-replacer-plugin` might work, it seems much more fragile.  For example if you had:
```
  "version":
    "1.0.0"
```
Not saying I do, but I could...

It would be much better if `npm version` had a switch that allowed setting to the same version.  Perhaps `--allow-same-version`.  Seems perfectly reasonable to ask for...

**Comment by nikgibbens** [comment]
I'm now seeing this issue again. I have run

`
npm config set allow-same-version true
`

But when I run the

`
npm version --force 1.0.0
`

It throws an error

`
npm WARN using --force I sure hope you know what you are doing.
npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "version" "--force" "1.0.0"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10

npm ERR! Version not changed
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ngibbens/stuff/github/task-notification-ui/npm-debug.log
`
This was working on an old version of NPM and Node. We upgrade to the latest versions of NPM and Node and now it's broken again.

NPM Version: 3.10.10
Node Version: v6.11.2

**Comment by daniellara** [comment]
Hi @nikgibbens, the option `--allow-same-version` was added in npm 4.6.1 so you have to update your npm version before use this option.

From npm@4.6.1 you can run `npm version --allow-same-version 1.0.0` and it will work without problem.

**Comment by alex198710** [comment]
As a workaround, for older version of npm, you could just do:
`npm version 0.1.0 && npm version 1.0.0`
This is what I'm using waiting for a better solution
