### ISSUE TITLE
Cannot install babel plugins. Error with .lock File Exists 

### ISSUE THREAD

**Issue by andrewmiro** [npm/npm#11343]
Hello

I'm trying to run

`sudo npm install babel-preset-es2015 babel-preset-react `

But this is failing with the following error:

```
npm ERR! EEXIST, open '/home/vagrant/.npm/bcc11fb1-babel-runtime-5-8-35-package-tgz.lock'
File exists: /home/vagrant/.npm/bcc11fb1-babel-runtime-5-8-35-package-tgz.lock
Move it away, and try again. 
npm ERR! System Linux 3.2.0-23-generic-pae
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "babel-preset-es2015" "babel-preset-react"
npm ERR! cwd /var/www
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! path /home/vagrant/.npm/bcc11fb1-babel-runtime-5-8-35-package-tgz.lock
npm ERR! code EEXIST
npm ERR! errno 47
npm ERR! not ok code 0`
```

As the error rightly says I'm running node v0.10.4 and npm v1.4.28

Does anyone have any ideas? I've seen various posts saying that this is fixed in 1.4.28.

The babel plugins are very large with many inter dependencies.

Regards
Andrew

**Comment by KenanY** [comment]
@andrewmiro Does this also occur if you update to the latest stable release of `npm`?

**Comment by andrewmiro** [comment]
@KenanY I can give that a go. What is the best way to update ``npm

**Comment by andrewmiro** [comment]
Got it.

Installed using `sudo npm install -g npm@latest`

**Comment by andrewmiro** [comment]
And have now successfully installed!!

Thank you @KenanY
