### ISSUE TITLE
npm-cli.js err

### ISSUE THREAD

**Issue by issd22** [npm/npm#11345]
I'm new to node, I run this script "npm run start" on command line. I created the start script on package.json running the jshint module. here's the erro i've got. Can you help me or enlighten me what would be the cause of additional information. 

Here's what I have on my package.json file:
{
  "name": "firstprodject",
  "version": "1.0.0",
  "description": "Testing lint",
  "main": "main.js",
  "dependencies": {},
  "devDependencies": {},
  "scripts": {
    "start": "jshint main.js",
    "test": "start"
  },
  "author": "xxx Leonor",
  "license": "ISC"
}

and the error I'm getting:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start' ]
2 info using npm@3.3.12
3 info using node@v5.5.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle firstprodject@1.0.0~prestart: firstprodject@1.0.0
6 silly lifecycle firstprodject@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle firstprodject@1.0.0~start: firstprodject@1.0.0
8 verbose lifecycle firstprodject@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle firstprodject@1.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\leonor1\vue\notaskrunner\node_modules\.bin;C:\Program Files (x86)\AMD APP\bin\x86_64;C:\Program Files (x86)\AMD APP\bin\x86;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Git\cmd;C:\Program Files (x86)\Git\bin;C:\Users\leonor1\AppData\Roaming\npm;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files\TortoiseSVN\bin;C:\ProgramData\chocolatey\bin;C:\Program Files\nodejs\;C:\Program Files\nodejs;C:\Users\leonor1\AppData\Roaming\npm
10 verbose lifecycle firstprodject@1.0.0~start: CWD: C:\Users\leonor1\vue\notaskrunner
11 silly lifecycle firstprodject@1.0.0~start: Args: [ '/d /s /c', 'jshint main.js' ]
12 silly lifecycle firstprodject@1.0.0~start: Returned: code: 2  signal: null
13 info lifecycle firstprodject@1.0.0~start: Failed to exec start script
14 verbose stack Error: firstprodject@1.0.0 start: `jshint main.js`
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:821:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid firstprodject@1.0.0
16 verbose cwd C:\Users\leonor1\vue\notaskrunner
17 error Windows_NT 6.1.7601
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
19 error node v5.5.0
20 error npm  v3.3.12
21 error code ELIFECYCLE
22 error firstprodject@1.0.0 start: `jshint main.js`
22 error Exit status 2
23 error Failed at the firstprodject@1.0.0 start script 'jshint main.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the firstprodject package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     jshint main.js
23 error You can get their info via:
23 error     npm owner ls firstprodject
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
Might need to ensure that `jshint` is installed before trying to use it:

```
npm install --save-dev jshint
```

**Comment by ashleygwilliams** [comment]
hi! i think @KenanY's suggestion is a great, as it is best practices. without having `jshint` as a dev dependency, you are relying on the user of your package having installed `jshint` globally (which it seems you did).

you are getting this error because `jshint` is returning a 2, which means that it failed. you probably need to fix lint errors in your `main.js`

designing your scripts like this is resulting in you not seeing the output you may expect. i would not run your test script via `npm start`. you can just run `npm test`.

please open a new issue if you continue to have problems. good luck!

**Comment by ashleygwilliams** [comment]
for more info on `jshint` return codes, see https://github.com/jshint/jshint/issues/916#issuecomment-14808738
