### ISSUE TITLE
I can't use hexo

### ISSUE THREAD

**Issue by FledgeXu** [npm/npm#11340]
0 info it worked if it ends with ok

    1 verbose cli [ 'node', '/usr/bin/npm', 'help', 'hexo' ]

    2 info using npm@1.3.6

    3 info using node@v0.10.36

    4 error TypeError: Cannot call method 'map' of undefined

    4 error     at formatResults (/usr/lib/node_modules/npm/lib/help-search.js:162:21)

    4 error     at /usr/lib/node_modules/npm/lib/help-search.js:32:9

    4 error     at searchFiles (/usr/lib/node_modules/npm/lib/help-search.js:141:12)

    4 error     at /usr/lib/node_modules/npm/lib/help-search.js:29:7

    4 error     at /usr/lib/node_modules/npm/lib/help-search.js:46:12

    4 error     at asyncMap (/usr/lib/node_modules/slide/lib/async-map.js:27:18)

    4 error     at readFiles (/usr/lib/node_modules/npm/lib/help-search.js:40:3)

    4 error     at /usr/lib/node_modules/npm/lib/help-search.js:26:5

    4 error     at Glob.<anonymous> (/usr/lib/node_modules/glob/glob.js:90:7)

    4 error     at Glob.emit (events.js:95:17)

**Comment by KenanY** [comment]
@FledgeXu `npm@1.3` is over two years old now and is no longer supported. Please try [updating](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm). Furthermore, check out the documentation on the [`npm` help`](https://docs.npmjs.com/cli/help) command; it is for viewing `npm`'s documentation, not that of other modules.

**Comment by ashleygwilliams** [comment]
hi! as @KenanY suggested, please update to either npm 2 or npm 3 (`npm install npm@<version> -g`). if you continue to have trouble, please open a new issue.

**Comment by FledgeXu** [comment]
Thank you,I have solved this problem.
