### ISSUE TITLE
Error Installing Sails

### ISSUE THREAD

**Issue by ysk8** [npm/npm#11346]
Using nvm for selecting node version 5.5.0 with npm 3.7.0
[npm-debug.log.zip](https://github.com/npm/npm/files/110510/npm-debug.log.zip)

**Comment by ctate** [comment]
http://blog.sailsjs.org/post/138232358567/warning-npm-v3312-may-derp-your-deps

**Comment by ashleygwilliams** [comment]
hi! this is a bug in `3.7.0`, fixed in `3.7.1`

please open a new issue if you continue to have problems!
