### ISSUE TITLE
cant install ATOM REACT PLUGIN

### ISSUE THREAD

**Issue by ruchikagamage** [npm/npm#11352]
```
$ apm install react
Installing react to C:\Users\USER\.atom\packages failed

npm ERR! git clone --template=C:\Users\USER\.atom\.apm\_git-remotes\_templates -
-mirror https://github.com/millermedeiros/rocambole.git C:\Users\USER\.atom\.apm
\_git-remotes\https-github-com-millermedeiros-rocambole-git-fa28ae6f: Cloning in
to bare repository 'C:\Users\USER\.atom\.apm\_git-remotes\https-github-com-mille
rmedeiros-rocambole-git-fa28ae6f'...
npm ERR! git clone --template=C:\Users\USER\.atom\.apm\_git-remotes\_templates -
-mirror https://github.com/millermedeiros/rocambole.git C:\Users\USER\.atom\.apm
\_git-remotes\https-github-com-millermedeiros-rocambole-git-fa28ae6f: fatal: Una
ble to find remote helper for 'https'
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "c:\\Users\\USER\\AppData\\Local\\atom\\app-1.4.1\\resources\\app\
\apm\\bin\\node.exe" "c:\\Users\\USER\\AppData\\Local\\atom\\app-1.4.1\\resource
s\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\US
ER\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\USER\\.atom\\.apmrc" "instal
l" "C:\\Users\\USER\\AppData\\Local\\Temp\\d-116030-8260-hi17z0\\package.tgz" "-
-target=0.34.5" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code 128

npm ERR! Command failed: Cloning into bare repository 'C:\Users\USER\.atom\.apm\
_git-remotes\https-github-com-millermedeiros-rocambole-git-fa28ae6f'...
npm ERR! fatal: Unable to find remote helper for 'https'
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

**Comment by emelonakos** [comment]
I am having a very similar error log:

npm ERR! git clone --template=C:\Users\Charles\.atom\.apm\_git-remotes\_templates --mirror https://github.com/millermedeiros/rocambole.git C:\Users\Charles\.atom\.apm\_git-remotes\https-github-com-millermedeiros-rocambole-git-fa28ae6f: Cloning into bare repository 'C:\Users\Charles\.atom\.apm\_git-remotes\https-github-com-millermedeiros-rocambole-git-fa28ae6f'...
npm ERR! git clone --template=C:\Users\Charles\.atom\.apm\_git-remotes\_templates --mirror https://github.com/millermedeiros/rocambole.git C:\Users\Charles\.atom\.apm\_git-remotes\https-github-com-millermedeiros-rocambole-git-fa28ae6f:       0 [main] git 15276 C:\cygwin64\bin\git.exe: *** fatal error in forked process - fork: can't reserve memory for parent stack 0x600000 - 0x800000, (child has 0x400000 - 0x600000), Win32 error 487
npm ERR! git clone --template=C:\Users\Charles\.atom\.apm\_git-remotes\_templates --mirror https://github.com/millermedeiros/rocambole.git C:\Users\Charles\.atom\.apm\_git-remotes\https-github-com-millermedeiros-rocambole-git-fa28ae6f:     238 [main] git 15276 cygwin_exception::open_stackdumpfile: Dumping stack trace to git.exe.stackdump
npm ERR! git clone --template=C:\Users\Charles\.atom\.apm\_git-remotes\_templates --mirror https://github.com/millermedeiros/rocambole.git C:\Users\Charles\.atom\.apm\_git-remotes\https-github-com-millermedeiros-rocambole-git-fa28ae6f:       0 [main] git 10408 fork: child -1 - forked process 15276 died unexpectedly, retry 0, exit code 0x100, errno 11
npm ERR! git clone --template=C:\Users\Charles\.atom\.apm\_git-remotes\_templates --mirror https://github.com/millermedeiros/rocambole.git C:\Users\Charles\.atom\.apm\_git-remotes\https-github-com-millermedeiros-rocambole-git-fa28ae6f: error: cannot fork() for git-remote-https: Resource temporarily unavailable
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\Charles\\AppData\\Local\\atom\\app-1.4.1\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Charles\\AppData\\Local\\atom\\app-1.4.1\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Charles\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Charles\\.atom\\.apmrc" "install" "C:\\Users\\Charles\\AppData\\Local\\Temp\\d-11611-14440-1ss6fgg\\package.tgz" "--target=0.34.5" "--arch=ia32" "--msvs_version=2013"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code 255

npm ERR! Command failed: Cloning into bare repository 'C:\Users\Charles\.atom\.apm\_git-remotes\https-github-com-millermedeiros-rocambole-git-fa28ae6f'...
npm ERR!       0 [main] git 15276 C:\cygwin64\bin\git.exe: *** fatal error in forked process - fork: can't reserve memory for parent stack 0x600000 - 0x800000, (child has 0x400000 - 0x600000), Win32 error 487
npm ERR!     238 [main] git 15276 cygwin_exception::open_stackdumpfile: Dumping stack trace to git.exe.stackdump
npm ERR!       0 [main] git 10408 fork: child -1 - forked process 15276 died unexpectedly, retry 0, exit code 0x100, errno 11
npm ERR! error: cannot fork() for git-remote-https: Resource temporarily unavailable
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
