### ISSUE TITLE
Error: ENOENT, lstat - [/Users/user/../../handlebars.js/node_modules/grunt-saucelabs/../Sauce-Connect.jar

### ISSUE THREAD

**Issue by nikosantoro** [npm/npm#11359]
![schermata 2016-01-31 alle 00 37 09](https://cloud.githubusercontent.com/assets/6201213/12699181/e00d083a-c7b2-11e5-865e-3616e00f38fe.png)

**Comment by othiym23** [comment]
You're using a completely obsolete and unsupported version of npm. Running `npm -g install npm@latest` should get you a version of npm that is substantially less likely to encounter the issue included in that screenshot. Since I'm pretty sure that's the source of your problem, I'm going to close this as resolved.

**Comment by othiym23** [comment]
Thanks for your time!

**Comment by nikosantoro** [comment]
Thanks very much for the help, i updated the npm and it works as expected.

2016-01-31 0:41 GMT+01:00 Forrest L Norvell <notifications@github.com>:

> Thanks for your time!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/npm/npm/issues/11359#issuecomment-177338829>.
>



-- 
*Nico Santoro*
Web Development & App Development
Via Reutele, 6 | 38046 Lavarone - Trento
*m* +39 348.5725673
www.facebook.com/nikosantorodeejay
*e* d <info@netwise.it>jsantoroniko@gmail.com
Rispetta l'ambiente: se non ti è necessario, non stampare questa email.
Ai sensi del Codice in materia di protezione dei dati personali (D.L.vo
196/03), il contenuto di questa e-mail e degli eventuali allegati Ã¨
riservato e ad uso esclusivo del destinatario. Chiunque riceva questo
messaggio per errore Ã¨ pregato di distruggerlo e contattare il mittente.
Si informa inoltre che la risposta alla presente comunicazione e gli
eventuali allegati potrebbero essere visionati, ai fini del disbrigo delle
competenze lavorative, anche da altro personale addetto.
According to the Italian data protection code (d.lgs. 196/03) the content
of this message and of its possible attachments is intended only for use by
the person to whom it is addressed. It may contain information that is
privileged and confidential. If you are not the intended recipient of this
message, kindly notify the sender immediately and destroy this message. The
reply to this communication, including possible attachments, may be viewed,
for working needs, also by other entrusted members of staff.
