### ISSUE TITLE
shrinkwrap doesn't work with symlinked devDependencies

### ISSUE THREAD

**Issue by rstacruz** [npm/npm#11354]
When dev dependencies are present as symlinks in `node_modules`, they're not shrinkwrappable.

Consider this dependency tree:

``` json
{
  "dependencies": { "mkdirp": "*" },
  "devDependencies": { "rimraf": "*" }
}
```

Then let's install them manually:

``` sh
npm install mkdirp
npm link rimraf  # assuming you have this linked globally
```

Now run `shrinkwrap`:

```
npm shrinkwrap
npm ERR! Darwin 15.3.0
npm ERR! argv "/Users/rsc/.nvm/versions/node/v4.1.0/bin/node" "/Users/rsc/.nvm/versions/node/v4.1.0/bin/npm" "shrinkwrap"
npm ERR! node v4.1.0
npm ERR! npm  v3.5.3

npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! extraneous: rimraf@2.5.1 /Users/rsc/Projects/rstacruz/cnpm/.tmp/node_modules/rimraf
```

**Comment by damienleroux** [comment]
+1. Same behavior. Either `npm shrinkwrap` triggers extraneous errors or `npm install` removes dev dependencies modules installed in the symlinked module. Any solution to be able to shrinkwrap modules declared as symlink and using dev dependencies?

I declared this problem on [SO](http://stackoverflow.com/questions/38312532/why-npm-install-override-node-modules-in-an-existing-symlink/38323177#38323177)

**Comment by wavded** [comment]
Any movement on this one?
