### ISSUE TITLE
getting error while installing cordova using npm 

### ISSUE THREAD

**Issue by harishpro** [npm/npm#11368]
i have node.js [v4.2.2] and npm [2.14.7] .
i had tried to install cordova usiing `npm install cordova -g` . it had been loaded for 5 minutes and showing warning as
 `npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm` .
and still loading..

**Comment by Vishnuraj910** [comment]
+1 Same here

**Comment by Vishnuraj910** [comment]
I run npm ls -g.

Got this : 

`npm ERR! invalid: readable-stream@1.1.13-1 C:\Users\vishnuraj.rajagopal\AppData\Roaming\npm\node_modules\vs-tac\node_modules\plugman\node_modules\cordova-lib\node_modules\cordova-js\node_modules\browserify\node_modules\concat-stream\node_modules\readable-stream
npm ERR! invalid: string_decoder@0.10.25-1 C:\Users\vishnuraj.rajagopal\AppData\Roaming\npm\node_modules\vs-tac\node_modules\plugman\node_modules\cordova-lib\node_modules\cordova-js\node_modules\browserify\node_modules\concat-stream\node_modules\readable-stream\node_modules\string_decoder
npm ERR! invalid: readable-stream@1.0.27-1 C:\Users\vishnuraj.rajagopal\AppData\Roaming\npm\node_modules\vs-tac\node_modules\plugman\node_modules\cordova-lib\node_modules\cordova-js\node_modules\browserify\node_modules\through2\node_modules\readable-stream
npm ERR! invalid: string_decoder@0.10.25-1 C:\Users\vishnuraj.rajagopal\AppData\Roaming\npm\node_modules\vs-tac\node_modules\plugman\node_modules\cordova-lib\node_modules\cordova-js\node_modules\browserify\node_modules\through2\node_modules\readable-stream\node_modules\string_decoder
`


`C:\Users\vishnuraj.rajagopal>node -v
v4.2.6

C:\Users\vishnuraj.rajagopal>npm -v
2.14.12
`

**Comment by Vishnuraj910** [comment]
[Cordova install log.txt](https://github.com/npm/npm/files/112078/Cordova.install.log.txt)

Find the log. Please help. I have tried Node v4.2.1 also, no luck.

Tried installing 

npm install -g cordova@5.4.0
npm install -g cordova@5.1.1
npm install -g cordova@5.0.0


All gave same error. I'm stuck on this from morning. Please fix this or give some workarounds.

**Comment by Vishnuraj910** [comment]
[cordova 5.4.0 v .txt](https://github.com/npm/npm/files/112085/cordova.5.4.0.v.txt)

**Comment by TheOtherRealm** [comment]
Same issue, tried doing: 
`npm uninstall -g npmconf`
But this did not wor

**Comment by Anusss** [comment]
I too have the same problem. i used the following command to install cordova,npm install -g cordova .Some files were installed too.But when i checked cordova version using cordova -v it doesn't show anything,I checked the npm version it is 3.7.2. When i tried install cordova again,it is showing npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm a
nd is now out of date with respect to npm. I uninstalled and reinstaled the npmconf also.What might be the problem? How can I solve it?
