### ISSUE TITLE
Wrong package name on E404 Not found eror message

### ISSUE THREAD

**Issue by tblaisot** [npm/npm#11369]
When using a custom registry like artifactory, if a package is not found on the registry the error is always the following one not matter the package name : 

```
[ERROR] npm ERR! node v4.2.3
[ERROR] npm ERR! npm  v3.6.0
[ERROR] npm ERR! code E404
[ERROR]
[ERROR] npm ERR! 404 Not Found: **artifactory**
[ERROR] npm ERR! 404
[ERROR] npm ERR! 404  '**artifactory**' is not in the npm registry.
[ERROR] npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
[ERROR] npm ERR! 404 It was specified as a dependency of 'my-module'
[ERROR] npm ERR! 404
[ERROR] npm ERR! 404 Note that you can also install from a
[ERROR] npm ERR! 404 tarball, folder, http url, or git url.
```

In this error the artifactory part is from the url of the registry : 
registry = http://10.104.19.102/artifactory/api/npm/repository-npm/
not from the package name

The error is caused by the wrong parsing of the url in **npm-registry-client\lib\request.js**

You can reproduce this error using a local artifactory registry configured to miror the main registry (or even by using a proxy rewriting the url) and pointing your conf to it, and then requesting a non existing module.

**Comment by bhovhannes** [comment]
This is valid issue for `Node v4.2.4` and `npm v3.8.5`, even without any url specified in package.json

**Comment by IEvangelist** [comment]
We are using artifactory as well and have it configured as an npm custom registry. We encounter the same issue, when is this going to be resolved?

```
λ node -v
v5.6.0
λ npm -v
3.6.0
```
