### ISSUE TITLE
Cannot find module 'github-url-from-git'

### ISSUE THREAD

**Issue by zbyszrom** [npm/npm#11363]
```
zbignienarsimac:~ zbyszrom$ sudo npm install -g gulp
npm ERR! Darwin 13.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "gulp"
npm ERR! node v5.5.0
npm ERR! npm  v3.3.12
npm ERR! code MODULE_NOT_FOUND

Cannot find module 'github-url-from-git'
npm ERR! 
```

I tried to reinstall node.js and git but it didn't help

**Comment by youngaj** [comment]
I'm getting this same error on windows.  Log output below.

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@3.3.12
3 info using node@v5.5.0
4 verbose stack Error: Cannot find module 'github-url-from-git'
4 verbose stack     at Function.Module._resolveFilename (module.js:339:15)
4 verbose stack     at Function.Module._load (module.js:290:25)
4 verbose stack     at Module.require (module.js:367:17)
4 verbose stack     at require (internal/module.js:16:19)
4 verbose stack     at Object.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\node_modules\normalize-package-data\lib\fixer.js:2:22)
4 verbose stack     at Module._compile (module.js:413:34)
4 verbose stack     at Object.Module._extensions..js (module.js:422:10)
4 verbose stack     at Module.load (module.js:357:32)
4 verbose stack     at Function.Module._load (module.js:314:12)
4 verbose stack     at Module.require (module.js:367:17)
5 verbose cwd c:\Users\ayoung\Documents\Work\Code\test
6 error Windows_NT 6.1.7601
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
8 error node v5.5.0
9 error npm  v3.3.12
10 error code MODULE_NOT_FOUND
11 error Cannot find module 'github-url-from-git'
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]

**Comment by chrisnault** [comment]
I am getting the same error trying to install babel. Did you have any luck fixing it?

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "github-url-from-git"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'github-url-from-git'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/user/dev/npm-debug.log

**Comment by oleh-zheleznyak** [comment]
Any luck with the issue, guys? I'm getting the same error no matter what command I launch on npm

```
C:\WINDOWS\system32>npm -g install npm@latest
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "-g" "install" "npm@latest"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'github-url-from-git'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\WINDOWS\system32\npm-debug.log
```

**Comment by kingbin** [comment]
I have personally fixed this error by removing or renaming "C:\Program Files\nodejs\node_modules" from a previous installation and reinstalled node.

**Comment by legodude17** [comment]
Everyone try @kingbin's solution. Does it not work for anyone?

**Comment by tondrey** [comment]
Doing what @kingbin suggested worked for me.  After removing the "C:\Program Files\nodejs\node_modules" folder and running the installer (Repair mode) all worked fine

**Comment by seanvelir** [comment]
I must have read 100 of these issues 
everything kept going back to 
https://github.com/nodejs/node/issues/3540

only @kingbin  fix worked for me!!!
