### ISSUE TITLE
problem while using npm install -d

### ISSUE THREAD

**Issue by koushik72** [npm/npm#11379]
I am new into node js.
I am trying to install all the dependecies but I am getting an error.
Please have a look at the ``` npm-debug.log ``` file and please tell me how I can solve it.
Please see the attachment.
Thanks.
[npm-debug.txt](https://github.com/npm/npm/files/113902/npm-debug.txt)

**Comment by ashleygwilliams** [comment]
it looks like from the log that you are somehow trying to install a package name `npm2` at version `1.0.0` which does not exist:

```
146 error node v5.5.0
147 error npm  v3.3.12
148 error No compatible version found: npm2@^1.0.0
148 error Valid install targets:
148 error 2.0.0
149 error If you need help, you may report this error at:
149 error     <https://github.com/npm/npm/issues>
150 verbose exit [ 1, true ]
```

i think you should just be using `npm install` to install from a `package.json`. i am not sure why you are using the `-d`.

could you try again with just `npm install`?

please open a new issue if you continue to have trouble. thanks!
