### ISSUE TITLE
npm install shows error on windows 7

### ISSUE THREAD

**Issue by mahmudulislamm** [npm/npm#11372]
> npm WARN package.json Dependency 'body-parser' exists in both dependencies and d
> evDependencies, using 'body-parser@^1.8.2' from dependencies
> npm WARN package.json Dependency 'compression' exists in both dependencies and d
> evDependencies, using 'compression@^1.1.0' from dependencies
> npm WARN package.json Dependency 'cors' exists in both dependencies and devDepen
> dencies, using 'cors@^2.2.0' from dependencies
> npm WARN package.json Dependency 'express' exists in both dependencies and devDe
> pendencies, using 'express@^4.9.3' from dependencies
> npm WARN package.json Dependency 'morgan' exists in both dependencies and devDep
> endencies, using 'morgan@^1.1.1' from dependencies
> npm WARN package.json Dependency 'serve-favicon' exists in both dependencies and
>  devDependencies, using 'serve-favicon@^2.0.1' from dependencies
> 
> > Starter-Gulp@0.1.0 install e:\Apps\xampp\htdocs\starter-project-gulp-angularjs
> 
> > bower install
> 
> 'bower' is not recognized as an internal or external command,
> operable program or batch file.
> 
> npm ERR! Windows_NT 6.1.7601
> npm ERR! argv "c:\\Program Files (x86)\\nodejs\\node.exe" "c:\\Program Files (x8
> 6)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
> npm ERR! node v4.2.6
> npm ERR! npm  v2.14.12
> npm ERR! code ELIFECYCLE
> npm ERR! Starter-Gulp@0.1.0 install: `bower install`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the Starter-Gulp@0.1.0 install script 'bower install'.
> npm ERR! This is most likely a problem with the Starter-Gulp package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     bower install
> npm ERR! You can get their info via:
> npm ERR!     npm owner ls Starter-Gulp
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     e:\Apps\xampp\htdocs\starter-project-gulp-angularjs\npm-debug.log

**Comment by mahmudulislamm** [comment]
problem solved. I don't know how it worked but it did. Setting proxy didn't work for me. I used this commands::

npm config set registry "http://registry.npmjs.org/"
npm config set strict-ssl false
npm config rm proxy
npm config rm https-proxy
unset HTTP_PROXY
unset HTTPS_PROXY
unset http_proxy
unset https_proxy

**Comment by ashleygwilliams** [comment]
yup! this is a known issue on windows machines. glad you got it working :) closing.
