### ISSUE TITLE
npm shrinkwrap is throwing error invalid error on dependencies that have "" version

### ISSUE THREAD

**Issue by zhuojloh** [npm/npm#11373]
attempt to npm shrinkwrap again after npm install from a dependency that have "" as version will produce error below. 

```
npm ERR! invalid: have async@1.5.2 (expected: ) ...
npm ERR! extraneous: async@1.5.2 ...
```

main dependencies

```
  "dependencies": {
    "async": "1.5.2",
    "gulp-s3": "^0.3.0",
  },
```

gulp-s3 dependencies

```
  "dependencies": {
    "async": "",
    "event-stream": "*",
    "gulp-util": "~2.2.6",
    "knox": "",
    "mime": "~1.2.11"
  },
```

**Comment by holm** [comment]
Seems the same as https://github.com/npm/npm/issues/11493

**Comment by sminnee** [comment]
Here's a replication case:

Test `package.json`

    {
      "name": "tmp3",
      "version": "1.0.0",
      "description": "",
      "main": "index.js",
      "scripts": {
        "test": "echo \"Error: no test specified\" && exit 1"
      },
      "author": "",
      "license": "ISC",
      "dependencies": {
        "async": "1.5.2",
        "gulp-s3": "^0.3.0"
      }
    }

Test script (`../../npm` is the folder where npm is checked out)

    #!/bin/bash
    rm -rf node_modules npm-shrinkwrap.json
    node ../../npm/bin/npm-cli.js install
    node ../../npm/bin/npm-cli.js shrinkwrap
    rm -rf node_modules
    node ../../npm/bin/npm-cli.js install
    node ../../npm/bin/npm-cli.js shrinkwrap
