### ISSUE TITLE
Error: failed to proxy package JSON from remote : <ownRemoteRegistryPackageName>

### ISSUE THREAD

**Issue by kasiwal123** [npm/npm#11376]
After upgrading from Yosemite to El Capitan, when using other remote registry, npm gives the following error while trying to fetch a certain package,

```
npm ERR! Error: failed to proxy package JSON from remote : <ownRemoteRegistryPackageName>
npm ERR!     at RegClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:300:14)
npm ERR!     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:238:65)
npm ERR!     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:123:22)
npm ERR!     at Request.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:893:14)
npm ERR!     at Request.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:844:12)
npm ERR!     at IncomingMessage.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:943:16
npm ERR!     at process._tickCallback (node.js:419:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 15.3.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/kasiwal/dev/starterplugin
npm ERR! node -v v0.10.31
npm ERR! npm -v 1.4.23
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/kasiwal/dev/starterplugin/npm-debug.log
npm ERR! not ok code 0

```

Any pointers as to what the issue is ?

**Comment by othiym23** [comment]
```
npm ERR! Error: failed to proxy package JSON from remote : <ownRemoteRegistryPackageName>
```

Since the above error text doesn't appear in the source of npm or any of its dependencies, I'm pretty sure it's being removed by your registry, so I would check the documentation from your registry vendor or ask your ops team if they know what that message means. Because I'm pretty sure this isn't coming from the npm CLI (or npm's primary registry network), I'm going to close this issue, but if you find evidence that this is indeed npm's problem, let me know, and we can reopen this issue. Thanks for your time!

**Comment by BernhardRode** [comment]
@othiym23 are you using npm enterprise? I'm having the same issue. Maybe you found a solution for the problem? =)

**Comment by AdamWillden** [comment]
@BernhardRode, please excuse the ping did you happen to figure this one out? I can't find any solutions online

**Comment by BernhardRode** [comment]
@AdamWillden no, sorry

**Comment by ezzatron** [comment]
In my case, I was using NPM Enterprise, and trying to use a branch of a GitHub Enterprise repo as a dependency. I fixed the error by prefixing the SSH URL with `git+ssh://`, which I assume forces the use of SSH instead of HTTP.
