### ISSUE TITLE
npm install -> npm ERR! cb() never called! npm v3.6.0

### ISSUE THREAD

**Issue by sandfox** [npm/npm#11378]
After installing node v5.5.0 via nvm and then running `npm install -g npm` which installed npm@3.6.0, running `npm install` on a project with no existing `node_modules` fails after some time with with this error `npm ERR! cb() never called!` and results in nothing being installed in the `node_modules` folder. running this command multiple times yields the same result

rolling the npm installation back to v3.4.1 via `npm install -g npm@3.4.1` makes npm install work again for the project.

shell output and package.json are here https://gist.github.com/sandfox/b14fd4f2866f32b4e95c

OS is OSX 10.11.3

**Comment by greyhwndz** [comment]
have the same error on my end:
`npm ERR! cb() never called!`
node: v5.9.0
npm: 3.8.2

Tried `npm cache clean` & `rm -rf ~/.npm` to no effect

**Comment by csaintc** [comment]
Same issue, I'm installing inside of latest Docker container

**Comment by gwin003** [comment]
Same exact issue. None of the above solutions worked.

**Comment by bdsoha** [comment]
Me too

**Comment by dskyberg-confyrm** [comment]
I have this error also:
-------------
OSX 10.10.5
Docker for Mac beta 7
npm 3.8.2
node  5.9.0
Alpine Linux container (smebberson/alpine-nodejs)
Host mounted volume - ie docker run ... -v <my folder>:/app

**Comment by dskyberg-confyrm** [comment]
I re-tested with Docker for Mac beta 8.  Same experience.

**Comment by cotocisternas** [comment]
al parecer upgrade a 5.10 o superior soluciona el problema https://github.com/npm/npm/issues/11976

**Comment by sylvainmouquet** [comment]
When i run npm install during a docker build i had "ERR! cb() never called"
The problem was a timeout connection with the enterprise proxy. I have added the npm registry uri in the environnement variable NO_PROXY and all is ok
