### ISSUE TITLE
ERR! addLocal Could not install /private/var/folders/cl/rk8c_n65471274j6vh56b7b80000gn/T/npm.65636/package

### ISSUE THREAD

**Issue by gerrymiller** [npm/npm#11385]
I have been using Homebrew-installed node.js on my El Capitan Macbook Pro. I recently modified my configuration to let Homebrew manage Node.js only, but let me manage `npm` separately as described here: https://gist.github.com/DanHerbert/9520689. Since then, I am getting the following error message consistently - it doesn't seem to impact `npm`'s ability to function, but philosophically the error bugs me. Any ideas on how best to diagnose/fix?

```
| ~ @ Gerry's MacBook (gerry) 
| => npm update -g
npm ERR! addLocal Could not install /private/var/folders/cl/rk8c_n65471274j6vh56b7b80000gn/T/npm.65636/package
```

**Comment by VeitSanner** [comment]
I encounter the same issue.

**Comment by bbk-pij-2012-20** [comment]
I also followed the https://gist.github.com/DanHerbert/9520689 install. 
I get a similar error message: 
npm ERR! addLocal Could not install /private/var/folders/lw/1vqry5xs5jddtwr97mlbjg_40000gn/T/npm.608/package

My node server doesn't seem to work either, I get the following error:

module.js:338
    throw err;
          ^
Error: Cannot find module '/Users/Shahin/server'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

I'm a relative novice so I may be missing something obvious. Any help appreciated.

**Comment by larssn** [comment]
Same problem, same procedure.

**Comment by pierredewilde** [comment]
Hi,

Same issue with `sudo npm update -g`.

This error is generated when trying to update `npm` itself:

`sudo npm update -g npm`

All other global packages are correctly updated.

Thanks,
Pierre

**Comment by ChasonTang** [comment]
Same issue in the npm v3.8.5, it have been disappear in v3.8.2,however, npm v3.8.2 couldn't upgrade to latest version by the command
```
npm update -g
```
so i reinstall the npm to the v3.8.5.there is disappointing that the issue is appear again.

**Comment by bronzeiii** [comment]
run this command, it resolved the issue for you

npm install -g npm@latest

**Comment by VeitSanner** [comment]
@bronzeiii, this has resolved the issue for me. Thanks for the update.

**Comment by JohnyDays** [comment]
Same problem with npm@3.10.7, I'm trying to install a private package from bitbucket.
Full log here:
```
npm ERR! addLocal Could not install /tmp/npm-3770-2e274f11/git-cache-5c5414c3/7777697552c5d76dd7d5647d677d342249ebb155
npm ERR! Linux 4.5.4-1-ARCH
npm ERR! argv "/home/johnydays/.nvm/versions/node/v6.5.0/bin/node" "/home/johnydays/.nvm/versions/node/v6.5.0/bin/npm" "i" "--save" "https://bitbucket.org/xxxxxx/xxxxxx"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.7
npm ERR! code EISDIR
npm ERR! errno -21
npm ERR! syscall read

npm ERR! eisdir EISDIR: illegal operation on a directory, read
npm ERR! eisdir This is most likely not a problem with npm itself
npm ERR! eisdir and is related to npm not being able to find a package.json in
npm ERR! eisdir a package you are trying to install.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/johnydays/projects/master-admin/npm-debug.log
```

Also tried adding .git and using ssh url, both failed.
Going to manually link for now, hit me up if I can provide any more information that could help.

**Comment by larssn** [comment]
This should have been fixed at this point, so running `npm install -g npm` should now be enough.

**Comment by ericandrewlewis** [comment]
Make sure the github repository you're installing as a package has a `package.json`, that was my problem

**Comment by rishabh7257** [comment]
This could also be a problem if you are copying the files manually along with package.json which i did. Although you can see the file in the folder then too the npm install will fail. I resolved this issue by 
1. deleting the package.json file in the project directory.
2. From CMD - 'npm init' (in the project directory).
3. Then 'npm install'

**Comment by webtechy** [comment]
I was receiving a similar issue when running;

`npm install ts-node --save-dev`

Turns out I had to retype "--save-dev" as Word had used a different character for the dash that I had copied the command from.

**Comment by karnikamit** [comment]
@webtechy thanks! it worked like a charm when typed.

**Comment by rishabhkashyap** [comment]
running below command worked for me
npm install -g npm@latest
