### ISSUE TITLE
`npm install` succeeds (with a false-positive), while `npm ls` throws "UNMET DEPENDENCY" if a submodule depends on a different version of itself

### ISSUE THREAD

**Issue by lxe** [npm/npm#11386]
Consider we have the following package versions:

1.0.0 package.json:
```
{
  "name": "self-dep",
  "version": "1.0.0"
}
```

2.0.0 package.json:
```
{
  "name": "self-dep",
  "version": "2.0.0",
  "dependencies": {
    "self-dep": "1.0.0"
  }
}
```

3.0.0 package.json:
```
{
  "name": "self-dep",
  "version": "3.0.0",
  "dependencies": {
    "self-dep": "2.0.0"
  }
}
```

*NOTE: I actually published these packages to npm to demonstrate*

Running `npm install` on 3.0.0 **succeeds** and yields the following tree:

```
node_modules
└── self-dep
    └── package.json
```

Where only one layer of self-dep is installed, which is self-dep@2.0.0

Running `npm ls` will then produce the following error:

```
self-dep@3.0.0 /Users/lxe/devel/self-dep
└─┬ self-dep@2.0.0
  └── UNMET DEPENDENCY self-dep@1.0.0
```

In this case, npm3 should produce a deep tree instead of attempting to flatten it. This works fine with npm 2.14.17:

```
node_modules
└── self-dep
    ├── node_modules
    │   └── self-dep
    │       └── package.json
    └── package.json
```

**Comment by othiym23** [comment]
This is pretty clearly a major inconsistency in the installer, and the team will definitely fix this if nobody else does first, but I'm curious: what were you doing that caused you to run into this? Is this just poking at the `npm@3` installer, or is this blocking a use case for you?

**Comment by lxe** [comment]
@othiym23 this is actually got surfaced due to an erroneously published package, where an older version (albeit referenced via git hash) was a a part of its dependencies. 

Looks like this is generically reproducible, even with regular semver dependencies. 

I'm speculating, but this could pop up in other places, such as test libraries using older versions of themselves are their devDependencies, etc...

**Comment by schmod** [comment]
This is sounding very similar to #10727. 

Does running `npm install` a second time produce a correct tree?

**Comment by iarna** [comment]
Flagging as needs-repro as we need to check back in and see if this is still broken in `3.10.x` as the changes there probably fixed this.

**Comment by lxe** [comment]
This works a tad better, but `npm ls` now fails with `npm ERR! invalid: self-dep@1.0.0` when installing withing `self-dep@3.0.0`:


```console
$ npm -v
3.10.2
```

`npm install` succeeds:

```console
$ npm install
npm http request GET https://unpm.uberinternal.com/self-dep
npm http 304 https://unpm.uberinternal.com/self-dep
npm WARN self-dep@3.0.0 No description
npm WARN self-dep@3.0.0 No repository field.
```

Both version 1 and version 2 are installed, and version 1 is a dependency of version 2, according to the tree, which is good:

```console
$ tree node_modules
node_modules
└── self-dep
    ├── node_modules
    │   └── self-dep
    │       └── package.json
    └── package.json
```

However, `npm ls` yields an `npm ERR! invalid: self-dep@1.0.0` error:

```console
$ npm ls
self-dep@3.0.0 /Users/aleksey/devel/self-dep
└─┬ self-dep@2.0.0
  └── self-dep@1.0.0 invalid

npm ERR! invalid: self-dep@1.0.0 /Users/aleksey/devel/self-dep/node_modules/self-dep/node_modules/self-dep
```

**Comment by zkat** [comment]
@lxe It looks like we now have a different bug in our hands. Do you mind creating a new issue for the `npm ls` bug and refer back to this issue? If you'd like, I can just make the issue myself, too. In the meantime, I'm going to close _this particular_ bug because that issue's fixed.

Thanks a lot for retrying the repro!

**Comment by zkat** [comment]
(there, I created #13634 just to make sure this doesn't get forgotten. Thanks again, @lxe!)
