### ISSUE TITLE
Problems installing expressjs with npm

### ISSUE THREAD

**Issue by Nebulashines** [npm/npm#11384]
I tried to install express js with this command:
npm install express@4.6.1

I go this error message:

npm ERR! node v0.12.7
npm ERR! npm v2.11.3
npm ERR! code CERT_UNTRUSTED

npm ERR! certificate not trusted

[npm-debug.pdf](https://github.com/npm/npm/files/114459/npm-debug.pdf)

**Comment by myshov** [comment]
It seems that your operation system (Windows as I understand) don't recognize ssl-certificate from registry.npmjs.org. It can occur is web site is using a trusted SSL certificate but it is missing a chain/intermediate certificate. I don't remember exactly but there was some settings somewhere in Windows for adding certificates that system should recognize as valid. Anyway I thin there should be some instructions to do that somewhere on the Internet just google it.

**Comment by Nebulashines** [comment]
Thank you Alexander. I will do just that.

**Comment by ashleygwilliams** [comment]
this seems solved! thanks @myshov !

please open another issue if you continue to have trouble @Nebulashines !
