### ISSUE TITLE
npm install express --save,failed 

### ISSUE THREAD

**Issue by dhnmagic** [npm/npm#11392]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/5.1.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'express' ]
2 info using npm@3.3.12
3 info using node@v5.1.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData express
8 silly fetchNamedPackageData express
9 silly mapToRegistry name express
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/express
13 verbose request uri https://registry.npmjs.org/express
14 verbose request no auth needed
15 info attempt registry request try #1 at 13:17:36
16 verbose request id 43140831d5324420
17 http request GET https://registry.npmjs.org/express
18 http 200 https://registry.npmjs.org/express
19 verbose headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
19 verbose headers   etag: '"1YFZ22C6H6EE31M0UOB5YCIM2"',
19 verbose headers   'content-type': 'application/json',
19 verbose headers   'cache-control': 'max-age=300',
19 verbose headers   'content-length': '533185',
19 verbose headers   'accept-ranges': 'bytes',
19 verbose headers   date: 'Wed, 03 Feb 2016 05:17:37 GMT',
19 verbose headers   via: '1.1 varnish',
19 verbose headers   age: '66',
19 verbose headers   connection: 'keep-alive',
19 verbose headers   'x-served-by': 'cache-lcy1127-LCY',
19 verbose headers   'x-cache': 'HIT',
19 verbose headers   'x-cache-hits': '2',
19 verbose headers   'x-timer': 'S1454476657.883324,VS0,VE0',
19 verbose headers   vary: 'Accept' }
20 silly get cb [ 200,
20 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
20 silly get     etag: '"1YFZ22C6H6EE31M0UOB5YCIM2"',
20 silly get     'content-type': 'application/json',
20 silly get     'cache-control': 'max-age=300',
20 silly get     'content-length': '533185',
20 silly get     'accept-ranges': 'bytes',
20 silly get     date: 'Wed, 03 Feb 2016 05:17:37 GMT',
20 silly get     via: '1.1 varnish',
20 silly get     age: '66',
20 silly get     connection: 'keep-alive',
20 silly get     'x-served-by': 'cache-lcy1127-LCY',
20 silly get     'x-cache': 'HIT',
20 silly get     'x-cache-hits': '2',
20 silly get     'x-timer': 'S1454476657.883324,VS0,VE0',
20 silly get     vary: 'Accept' } ]
21 verbose get saving express to /Users/dhn/.npm/registry.npmjs.org/express/.cache.json
22 verbose makeDirectory /Users/dhn/.npm creation not in flight; initializing
23 silly makeDirectory /Users/dhn/.npm uid: 501 gid: 20
24 silly install normalizeTree
25 silly loadCurrentTree Finishing
26 silly loadIdealTree Starting
27 silly install loadIdealTree
28 silly cloneCurrentTree Starting
29 silly install cloneCurrentTreeToIdealTree
30 silly cloneCurrentTree Finishing
31 silly loadShrinkwrap Starting
32 silly install loadShrinkwrap
33 silly loadShrinkwrap Finishing
34 silly loadAllDepsIntoIdealTree Starting
35 silly install loadAllDepsIntoIdealTree
36 silly rollbackFailedOptional Starting
37 silly rollbackFailedOptional Finishing
38 silly runTopLevelLifecycles Starting
39 silly runTopLevelLifecycles Finishing
40 silly install printInstalled
41 verbose stack Error: Refusing to install express as a dependency of itself
41 verbose stack     at checkSelf (/usr/local/lib/node_modules/npm/lib/install/validate-args.js:40:14)
41 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
41 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
41 verbose stack     at chain (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
41 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/validate-args.js:15:5
41 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
41 verbose stack     at Array.forEach (native)
41 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
41 verbose stack     at Array.forEach (native)
41 verbose stack     at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
42 verbose cwd /Users/dhn/Documents/node/express
43 error Darwin 15.2.0
44 error argv "/usr/local/Cellar/node/5.1.0/bin/node" "/usr/local/bin/npm" "install" "express"
45 error node v5.1.0
46 error npm  v3.3.12
47 error code ENOSELF
48 error Refusing to install express as a dependency of itself
49 error If you need help, you may report this error at:
49 error     <https://github.com/npm/npm/issues>
50 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@dhnmagic Try renaming your current directory to something other than `"express"`.

**Comment by ashleygwilliams** [comment]
Hi! as @KenanY mentioned, you cannot install `express` as a dependency inside a directory called `express`. if you change the name of the directory you should be all set.

please open another issue if you continue to have trouble!
