### ISSUE TITLE
Grunt install error

### ISSUE THREAD

**Issue by cpjoshi3110** [npm/npm#11396]
I tried to install grunt with CMD and got error. Can any once check attached files and let give us solution?

![error](https://cloud.githubusercontent.com/assets/17043356/12778692/1f858238-ca8a-11e5-9c02-cc3c5360d844.PNG)

Here is log file detail.......................
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'grunt',
1 verbose cli   '--save-dev' ]
2 info using npm@3.3.12
3 info using node@v5.5.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData grunt
8 silly fetchNamedPackageData grunt
9 silly mapToRegistry name grunt
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/grunt
13 verbose request uri https://registry.npmjs.org/grunt
14 verbose request no auth needed
15 info attempt registry request try #1 at 2:43:51 PM
16 verbose request id 39337f40ceeeb7ec
17 verbose etag "EC5EXEL6V1F3PE6TMR2JP2SGI"
18 http request GET https://registry.npmjs.org/grunt
19 http 304 https://registry.npmjs.org/grunt
20 verbose headers { date: 'Wed, 03 Feb 2016 09:13:53 GMT',
20 verbose headers   via: '1.1 varnish',
20 verbose headers   'cache-control': 'max-age=300',
20 verbose headers   etag: '"EC5EXEL6V1F3PE6TMR2JP2SGI"',
20 verbose headers   age: '5',
20 verbose headers   connection: 'keep-alive',
20 verbose headers   'x-served-by': 'cache-sin6926-SIN',
20 verbose headers   'x-cache': 'HIT',
20 verbose headers   'x-cache-hits': '1',
20 verbose headers   'x-timer': 'S1454490833.142816,VS0,VE0',
20 verbose headers   vary: 'Accept' }
21 silly get cb [ 304,
21 silly get   { date: 'Wed, 03 Feb 2016 09:13:53 GMT',
21 silly get     via: '1.1 varnish',
21 silly get     'cache-control': 'max-age=300',
21 silly get     etag: '"EC5EXEL6V1F3PE6TMR2JP2SGI"',
21 silly get     age: '5',
21 silly get     connection: 'keep-alive',
21 silly get     'x-served-by': 'cache-sin6926-SIN',
21 silly get     'x-cache': 'HIT',
21 silly get     'x-cache-hits': '1',
21 silly get     'x-timer': 'S1454490833.142816,VS0,VE0',
21 silly get     vary: 'Accept' } ]
22 verbose etag https://registry.npmjs.org/grunt from cache
23 verbose get saving grunt to C:\Users\admin\AppData\Roaming\npm-cache\registry.npmjs.org\grunt\.cache.json
24 silly install normalizeTree
25 silly loadCurrentTree Finishing
26 silly loadIdealTree Starting
27 silly install loadIdealTree
28 silly cloneCurrentTree Starting
29 silly install cloneCurrentTreeToIdealTree
30 silly cloneCurrentTree Finishing
31 silly loadShrinkwrap Starting
32 silly install loadShrinkwrap
33 silly loadShrinkwrap Finishing
34 silly loadAllDepsIntoIdealTree Starting
35 silly install loadAllDepsIntoIdealTree
36 silly rollbackFailedOptional Starting
37 silly rollbackFailedOptional Finishing
38 silly runTopLevelLifecycles Starting
39 silly runTopLevelLifecycles Finishing
40 silly install printInstalled
41 verbose stack Error: Refusing to install grunt as a dependency of itself
41 verbose stack     at checkSelf (C:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:40:14)
41 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
41 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
41 verbose stack     at chain (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
41 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:15:5
41 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
41 verbose stack     at Array.forEach (native)
41 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
41 verbose stack     at Array.forEach (native)
41 verbose stack     at asyncMap (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
42 verbose cwd E:\extra\grunt
43 error Windows_NT 6.1.7601
44 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "grunt" "--save-dev"
45 error node v5.5.0
46 error npm  v3.3.12
47 error code ENOSELF
48 error Refusing to install grunt as a dependency of itself
49 error If you need help, you may report this error at:
49 error     <https://github.com/npm/npm/issues>
50 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@cpjoshi3110 Rename the directory you are in to something other than `"grunt"`.

**Comment by ashleygwilliams** [comment]
Hi! as @KenanY said, you can't install `grunt` as a dependency in a directory with the name `grunt`. if you change the directory name, you should be all set.

please open a new issue if you continue to have trouble!
