### ISSUE TITLE
NPM install error

### ISSUE THREAD

**Issue by ashishtree** [npm/npm#11409]
Hi,

When running "npm install" this is giving error "npm ERR! fetch failed https://github.com/tmcw/jszip/archive/patch-1.tar.gz"

i am using node version "5.2.0" and npm version "3.7.1"

Please help.

**Comment by ashleygwilliams** [comment]
hi! it looks like that tar does not exist, which would explain why npm cannot retrieve it (if you click the link it 404s). you'll likely need to talk to the package maintainer about this issue. 

if you continue to have problems, please reopen an issue with the `package.json` and full error message.

good luck!
