### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by tiansiyuan** [npm/npm#11404]
```
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! Finance@0.0.1 start: `node node_modules/react-native/local-cli/cli.js start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Finance@0.0.1 start script 'node node_modules/react-native/local-cli/cli.js start'.
npm ERR! This is most likely a problem with the Finance package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/react-native/local-cli/cli.js start
npm ERR! You can get their info via:
npm ERR!     npm owner ls Finance
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/tiansiyuan/Documents/projects/FinanceReactNative/npm-debug.log


```

**Comment by tiansiyuan** [comment]
log attached.

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.14.12
3 info using node@v4.2.6
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart Finance@0.0.1
6 info start Finance@0.0.1
7 verbose unsafe-perm in lifecycle true
8 info Finance@0.0.1 Failed to exec start script
9 verbose stack Error: Finance@0.0.1 start: `node node_modules/react-native/local-cli/cli.js start`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:821:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid Finance@0.0.1
11 verbose cwd /Users/tiansiyuan/Documents/projects/FinanceReactNative
12 error Darwin 15.3.0
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
14 error node v4.2.6
15 error npm  v2.14.12
16 error code ELIFECYCLE
17 error Finance@0.0.1 start: `node node_modules/react-native/local-cli/cli.js start`
17 error Exit status 1
18 error Failed at the Finance@0.0.1 start script 'node node_modules/react-native/local-cli/cli.js start'.
18 error This is most likely a problem with the Finance package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node node_modules/react-native/local-cli/cli.js start
18 error You can get their info via:
18 error     npm owner ls Finance
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by ashleygwilliams** [comment]
hi! this is an issue with the `Finance` package. you'll need to bring this up with the maintainer of that package.
