### ISSUE TITLE
npm start doesn't work

### ISSUE THREAD

**Issue by nicromant9** [npm/npm#11411]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/5.3.0/bin/node',
1 verbose cli   '/Users/alex/.node/bin/npm',
1 verbose cli   'start' ]
2 info using npm@3.5.3
3 info using node@v5.3.0
4 verbose stack Error: missing script: start
4 verbose stack     at run (/Users/alex/.node/lib/node_modules/npm/lib/run-script.js:147:19)
4 verbose stack     at /Users/alex/.node/lib/node_modules/npm/lib/run-script.js:57:5
4 verbose stack     at /Users/alex/.node/lib/node_modules/npm/node_modules/read-package-json/read-json.js:345:5
4 verbose stack     at checkBinReferences_ (/Users/alex/.node/lib/node_modules/npm/node_modules/read-package-json/read-json.js:309:45)
4 verbose stack     at final (/Users/alex/.node/lib/node_modules/npm/node_modules/read-package-json/read-json.js:343:3)
4 verbose stack     at then (/Users/alex/.node/lib/node_modules/npm/node_modules/read-package-json/read-json.js:113:5)
4 verbose stack     at /Users/alex/.node/lib/node_modules/npm/node_modules/read-package-json/read-json.js:300:12
4 verbose stack     at /Users/alex/.node/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:76:16
4 verbose stack     at tryToString (fs.js:414:3)
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
5 verbose cwd /Users/alex/sfe
6 error Darwin 15.3.0
7 error argv "/usr/local/Cellar/node/5.3.0/bin/node" "/Users/alex/.node/bin/npm" "start"
8 error node v5.3.0
9 error npm  v3.5.3
10 error missing script: start

**Comment by MirzaMerdovic** [comment]
You probably have a bad package.json. This link here should help you out:
    http://stackoverflow.com/questions/31976722/start-script-missing-error-when-running-npm-start
or this:
    https://github.com/npm/npm/issues/7467

**Comment by ashleygwilliams** [comment]
hi! this error means that you are trying to run a `npm start` script, except you do not have a script named `start` in your `package.json`

you'll need to look at your `package.json`. you'd want to see something like this:

```
{
   "name": "my-project",
   "version": "1.0.0",
   "scripts": {
       "start": "node index.js" // this is where you define a start script
   }
}
```

**Comment by ashleygwilliams** [comment]
closing. please reopen if you continue to have problems.

**Comment by Skhoshhal** [comment]
after npm start it shows me these errors:

$ npm start

> ecc-component-healthstatus@0.1.0 start /home/eccenca/eccenca/ecc-component-healthstatus
> gulp

sh: 1: gulp: not found

npm ERR! Linux 4.4.0-21-generic
npm ERR! argv "/home/eccenca/.nvm/versions/node/v6.0.0/bin/node" "/home/eccenca/.nvm/versions/node/v6.0.0/bin/npm" "start"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! ecc-component-healthstatus@0.1.0 start: `gulp`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the ecc-component-healthstatus@0.1.0 start script 'gulp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ecc-component-healthstatus package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ecc-component-healthstatus
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ecc-component-healthstatus
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /home/eccenca/eccenca/ecc-component-healthstatus/npm-debug.log

**Comment by aghed** [comment]
my issue is very similar but, if i run the first time it works ,but if i stop it and start it again ,it doesn't work!!!??????,in order to continue i keep the server runing and make  my laptop  sleep!!
is there a way around this???
