### ISSUE TITLE
Reverse the ratios of progress bar to status text

### ISSUE THREAD

**Issue by nyteshade** [npm/npm#11426]
The npm progress bar, especially now that bugs have been fixed in 3.7.0, is great, but it would be nicer if the text flashing by was more readable and if the bar were significantly shorter in length. Even a 10-20 col wide progress bar at the beginning and 40-60 cols worth of text would be much nicer to work with.

**Comment by othiym23** [comment]
Great suggestion, @nyteshade! You should take this concern over to [`gauge`](https://github.com/iarna/gauge/issues), where @iarna is working on the next major version. The good news is that I believe this is exactly what @iarna has already done in her work-in-progress new major version. Thanks for your time!
