### ISSUE TITLE
No npm stats for namespaced packages?

### ISSUE THREAD

**Issue by chickendinosaur** [npm/npm#11428]
I know that you can't search namespaced packages but why isn't there a stat tracker for them? I am using namespaced packages for --access=public but want to know if anyone is downloading them. Any way to enable this?

**Comment by ashleygwilliams** [comment]
hi! right now unfortunately we can't do that. it will require a substantial rewrite to the service that currently serves those stats.

additionally, that is a service that is consumed by the website! so if you'd like to request this feature you should file [over there](https://github.com/npm/newww/issues) :)

hope that helps! and thanks for using name-spaced packages!
