### ISSUE TITLE
Optionally use .npmrc from nearest parent directory

### ISSUE THREAD

**Issue by erquhart** [npm/npm#11437]
There's a super common use case where a group of projects all use the same npm config, and there are multiple groups and associated configs - it would be awesome to just set an `.npmrc` in a parent folder for each group.

The simpler (less robust/potentially less problematic) approach would be for npm to check only the current directory and the parent directory, but it would also be nice to just have npm search all the way up the tree.

Has this come up in the past or been considered?

**Comment by othiym23** [comment]
The CLI team would definitely like to make changes that support a monorepo pattern of development. This particular change on its own is not something that makes sense in isolation, though. What _would_ be convenient and helpful would be for npm to follow the same rules for locating the package configuration that it does for `package.json`, which is to say that the CLI should look for the package-specific configuration file in the same place that it finds `package.json`.

We'd be happy to merge a patch to that effect (so I'm tagging this `patch-welcome`), although we're not going to have the resources to get to that ourselves in the next 6-12 months, so I'm going to close this issue.

**Comment by erquhart** [comment]
@othiym23 thanks for the response. I feel like we're not talking about the same things - especially based on this bit from your comment:

> What would be convenient and helpful would be for npm to follow the same rules for locating the package configuration that it does for package.json, which is to say that the CLI should look for the package-specific configuration file in the same place that it finds package.json.

I feel stupid saying this, as you probably wrote the code that supports this, but npm already does this per [the docs](https://docs.npmjs.com/files/npmrc#per-project-config-file):

> When working locally in a project, a .npmrc file in the root of the project (ie, a sibling of node_modules and package.json) will set config values specific to this project.

Again, guessing my original comment was misunderstood - it seems you took my suggestion from the perspective of an npm publisher rather than a consumer? I'm speaking from the vantage point of a consumer.

Concerning this bit:
> This particular change on its own is not something that makes sense in isolation, though.

To clarify my suggestion by way of example, I've added the private npm registry for my current employer to `~/.npmrc`. That registry requires a vpn connection. Later I switch over to a personal project - I'm not on the vpn, and I also don't want to unintentionally grab things from my employer's registry. To run `npm install/update`, I either have to have a `.npmrc` for every individual non-employer repo, or I have to manually change `~/.npmrc` to comment out the employer registry every time I switch between employer and personal work. The change I'm suggesting is that npm would, instead of simply looking alongside the current package.json and then at `~/.npmrc`, also climb the tree and check for configs in between. Then I can have `~/employer-stuff/.npmrc` specify the employer registry only for things nested in `~/employer-stuff/`, and everything else on my machine is left alone.

I imagine this is a very common frustration. There are a few hack libs out to help ease the pain - I'm suggesting a first class solution within npm itself. Does that not seem a worthwhile change?
