### ISSUE TITLE
npm install boomcatch not working

### ISSUE THREAD

**Issue by gavya** [npm/npm#11431]
gyp 'ERR!' make build failed with exit code 2
gyp 'ERR!' System Linux 4.1.13gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 4.1.13-100.fc21.x86_64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! npm http 304 https://registry.npmjs.org/amdefine
cwd /root/node_modules/boomcatch/node_modules/ain2/node_modules/unix-dgram
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v0.10.6
gyp ERR! not ok

**Comment by ashleygwilliams** [comment]
tried to reproduce this error but on `node 0.10.36`, `npm 1.4.28` it timed out, (i am on airplane wifi fwiw).

however, i updated npm to `3.7.1` && `2.14.18` and it installed successfully. i would recommend that you update your npm to the latest build of 3 or 2.

please open a new issue if you continue to have trouble! thanks :)
