### ISSUE TITLE
Cannot find module 'internal/util'

### ISSUE THREAD

**Issue by duzy** [npm/npm#11430]
```
duzy@WorkBox:/task/test-case$ sudo npm install -g bcrypt
npm ERR! Linux 4.2.0-19-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "bcrypt"
npm ERR! node v6.0.0-pre
npm ERR! npm  v3.6.0
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'internal/util'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /task/test-case/npm-debug.log
```

**Comment by Jaykah** [comment]
I am having the same issue on Trusty, everything was ok just yesterday.

**Comment by ashleygwilliams** [comment]
hey @duzy! this is a bug that was introduced to node 6 in https://github.com/nodejs/node/commit/1124de2d76ad7118267d91a08485aa928a5f0865

we plan on having a patch for npm in a week or two, but in the meantime it looks like Node will probably revert the change and add a deprecation warning

hope that helps!

**Comment by duzy** [comment]
@ashleygwilliams Thanks for the information!

**Comment by SudhakarKamana** [comment]
Hi, I get the same issue. Please let me know how to resolve this issue? Thank you

**Comment by dimpiax** [comment]
I have the same bug.
`...npm ERR! node v6.0.0-pre
npm ERR! npm v3.7.2...`

**Comment by vkurchatkin** [comment]
> this is a bug that was introduced to node 6

Correction: there is no bug in node

**Comment by TheAlphaNerd** [comment]
@duzy are you install node from source?
