### ISSUE TITLE
npm 3.6.0 freezes my connection

### ISSUE THREAD

**Issue by Foxandxss** [npm/npm#11435]
This is going to be the weirdest issue ever.

When I am installing a package (or the deps of a project) using the latest npm, I can see my internet connection (via cable) to shake. If I am in slack chatting, I can see how it loses the connection for a second and every a few seconds. Chrome starts to not load pages correctly...

I am not entirely sure if that is a connection issue from my part, but perhaps I am not alone and npm is somehow milking my router connections.

Even with that issues, I get my packages downloaded and installed.

**Comment by ihorskyi** [comment]
@Foxandxss is it shaking cable as well or just internet connection? :)
I used to travel a lot and saw similar issue in several places on weak connections and highspeed connections but with cheap/bad routers. 

What helped me:
1) npm config set registry http://registry.npmjs.org 
2) Turn off **anti spam** defence on router 
3) Turn off firewall on router

Hope that helps
