### ISSUE TITLE
stuck in step 3 of "LET'S SCAFFOLD A WEB APP WITH YEOMAN"

### ISSUE THREAD

**Issue by NajehM** [npm/npm#11445]
After typing yo angular 
it gives me "npm WARN karma-jasmine@0.3.7 requires a peer of jasmine-core@* but none was installed" 
and  "Error: Cannot find module 'karma'
when i try to install karma, i get the warning "no license field"
what shall i do

**Comment by NajehM** [comment]
npm WARN EPEERINVALID karma-jasmine@0.3.7 requires a peer of jasmine-core@* but none was installed.
npm WARN EPEERINVALID karma-phantomjs-launcher@1.0.0 requires a peer of phantomjs-prebuilt@>=1.9 but none was installed.
npm WARN EPACKAGEJSON hphppc@0.0.0 No license field.

**Comment by ashleygwilliams** [comment]
hi!

re: peer dependencies, you'll need to install them on your own, i.e. run `npm install` for each peer in your project director. peer dependencies are not automatically installed with an `npm install` from a `package.json`.

the warning re licenses means that you need to list a license in your `package.json`. e.g.:

```
// package.json

{
  "name": "my-project",
  "version": "1.0.0",
  "license" : "MIT" // declare a license here
}
```

please file another issue if you continue to have trouble. it is helpful to post the whole error as well as your node and npm versions. thanks!

**Comment by NajehM** [comment]
thank you @ashleygwilliams, it's just that i am all new to this

**Comment by ashleygwilliams** [comment]
totally understand! good luck in your node journey :)

**Comment by NajehM** [comment]
thanks ^^
