### ISSUE TITLE
error while npm start command

### ISSUE THREAD

**Issue by farhanmohsin** [npm/npm#11447]
6 error Windows_NT 6.1.7600
7 error argv "E:\\Program Files\\nodejs\\node.exe" "E:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
8 error node v5.1.0
9 error npm  v3.7.2
10 error missing script: start

**Comment by ashleygwilliams** [comment]
hi!

looks like you tried to run `npm start` but there was no start script defined in `package.json`.

your `package.json` should contain an attribute, `scripts`, that points to an object that contains a `start` attribute, e.g.:

```
// package.json
{
   "name": "my-project",
   "version": "1.0.0",
   "scripts" : {
       "start": "node index.js" // this is where the start script is defined
   }
}
```

hope that helps. please open a new issue if you continue to have trouble.
