### ISSUE TITLE
Couldn't install optional dependency: connect EADDRINUSE 23.235.43.162:443 - Local (undefined:undefined)

### ISSUE THREAD

**Issue by NLSurfMan** [npm/npm#11448]
I have installed a fresh copy of node in Windows 7. When trying to install, well, anything, I get a cryptic error. By the looks of it, it could be network related, but I have no idea why. Windows Firewall is off, my router's firewall is enabled, but there are no restrictions on outbound ports.

```
C:\dev\nodejs>node -v
v5.5.0

C:\dev\nodejs>npm -v
3.3.12
```

This is where npm pauses:

```
C:\dev\nodejs>npm -g install ember-cli
loadDep:yam → network     ▐ ╢███████████████████████████░░░░
```

When you wait and let is finish, this is the result:

```
C:\dev\nodejs>npm -g install ember-cli
npm WARN install Couldn't install optional dependency: connect EADDRINUSE 23.235.43.162:443 - Local (undefined:undefined)
npm WARN install Couldn't install optional dependency: connect EADDRINUSE 23.235.43.162:443 - Local (undefined:undefined)
npm WARN install Couldn't install optional dependency: connect EADDRINUSE 23.235.43.162:443 - Local (undefined:undefined)
** snip 30 identical lines **
npm WARN install Couldn't install optional dependency: connect EADDRINUSE 23.235.43.162:443 - Local (undefined:undefined)
npm WARN install Couldn't install optional dependency: connect EADDRINUSE 23.235.43.162:443 - Local (undefined:undefined)
npm ERR! fetch failed https://registry.npmjs.org/broccoli-funnel/-/broccoli-funnel-1.0.1.tgz
npm WARN retry will retry, error on last attempt: Error: connect EADDRINUSE 23.235.43.162:443 - Local (undefined:undefined)
```

I am able to reach the given address:

```
C:\dev\nodejs>ping 23.235.43.162

Pinging 23.235.43.162 with 32 bytes of data:
Reply from 23.235.43.162: bytes=32 time=3ms TTL=56
Reply from 23.235.43.162: bytes=32 time=3ms TTL=56
Reply from 23.235.43.162: bytes=32 time=3ms TTL=56
Reply from 23.235.43.162: bytes=32 time=3ms TTL=56

Ping statistics for 23.235.43.162:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 3ms, Maximum = 3ms, Average = 3ms
```

It's definately _not_ a wonky internet connection, because I am on a 500/500 Mbit fiber connection which have proved to be very reliable.

What is going on here?

**Comment by ashleygwilliams** [comment]
same as https://github.com/npm/npm/issues/11252

**Comment by NLSurfMan** [comment]
Somehow I wonder if issue #11252 is related. That seems to bail out over a self signed certificate. I find no such errors here.

Here's a verbose log of the install: https://gist.github.com/NLSurfMan/c67e24f9d4b676c88cc9
Command line used:  C:\dev\nodejs> npm -g --verbose install ember-cli > install-ember-cli.log 2>&1

Note: I have also tried using several VPNs with endpoints in the US, UK and Switzerland, but that doesn't make any difference.
