### ISSUE TITLE
Homebridge error - missing script: start 

### ISSUE THREAD

**Issue by rvdodewaard** [npm/npm#11450]
npm ERR! Linux 4.1.13+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
npm ERR! node v4.2.1
npm ERR! npm v2.14.7

npm ERR! missing script: start
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR! <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR! /root/homebridge/npm-debug.log

LOG:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'start' ]
2 info using npm@2.14.7
3 info using node@v4.2.1
4 verbose stack Error: missing script: start
4 verbose stack     at run (/usr/local/lib/node_modules/npm/lib/run-script.js:142:19)
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/run-script.js:58:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:345:5
4 verbose stack     at handleExists (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:318$
4 verbose stack     at FSReqWrap.cb [as oncomplete] (evalmachine.<anonymous>:212:19)
5 verbose cwd /root/homebridge
6 error Linux 4.1.13+
7 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
8 error node v4.2.1
9 error npm  v2.14.7
10 error missing script: start
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@rvdodewaard Are you following a tutorial? When I look at the readme file for homebridge I don't see any instructions to run `npm run start`.

(I am assuming that [this](https://github.com/nfarina/homebridge) is homebridge)

Are you sure you should not just be running `homebridge` after installing it globally? Or running `./bin/homebridge` if you have it installed globally.

**Comment by rvdodewaard** [comment]
It seems that I didn't installed it globally, but thanks to your comment now I did and it is working fine. Thanks
