### ISSUE TITLE
Can't access latest npm version in a Cygwin/Github console

### ISSUE THREAD

**Issue by TravelingTechGuy** [npm/npm#11453]
I had Node 5.5.0/ NPM 3.3.2 installed on my Windows 10 OS.
I upgraded to NPM 3.7.1 using `npm install -g npm@latest`. In a Windows command prompt, when I type `npm -v` I get the correct 3.7.1, but in a Cygwin command window (the one that came with Github) it still shows 3.3.2, even after restarting the environment several times. 

I have no idea where it's still getting it from. When I type `which npm` in Cygwin, I get `/c/Program Files/nodejs/npm`, which is the same as the Window command window (`C:\Program Files\nodejs\npm`).

Does installation of the latest version replace the current one, or does the old one still hangs around somewhere?

**Comment by bsclifton** [comment]
@TravelingTechGuy I believe the issue is that the Windows installers install both node.js AND npm. When you did that upgrade, it upgraded your roaming folder (which lives at %APPDATA%\npm).

The only way I'm aware of upgrading NPM would be to do one of the following:
* install a newer version of node.js (which has npm bundled)
* copy the files from your roaming directory over the ones at `C:\Program Files\nodejs\node_modules\npm`

**Comment by busches** [comment]
@TravelingTechGuy only one result is listed for the `which` in each terminal? Seems quite odd that the same file is reporting two different versions based on the terminal.

**Comment by TravelingTechGuy** [comment]
@busches I believe @bsclifton nailed it on the head: there ARE 2 NPM executables installed. Or rathher, there were. I ended up removing the whole mess and starting from scratch. I will no longer attempt to upgrade NPM through NPM on Windows, without figuring out how to update both.

And to throw a further detail: since originally posting this, Win10 Anniversary edition came out, with its Linux Bash subsystem. Installing Node there means you now have another NPM. However, since this behaves like real Ubuntu, it's quite predictable. And being self contained, I can now upgrade NPM successfully to latest, or roll back that version. Perhaps this is the way to go forward with Node on Windows.
