### ISSUE TITLE
Error uninstalling 'shell'

### ISSUE THREAD

**Issue by chooie** [npm/npm#11455]
Here is the log: [npm-debug.txt](https://github.com/npm/npm/files/120528/npm-debug.txt)

**Comment by ashleygwilliams** [comment]
hi! i see that you are on version 3.3.12 -- could you try updating please? i believe this is a bug that has been fixed.

`npm install npm@latest -g`

lemme know how that goes!

**Comment by chooie** [comment]
Yes, that sorted it. Thanks for your help.

**Comment by ashleygwilliams** [comment]
great! anytime :smile:
