### ISSUE TITLE
Error install module

### ISSUE THREAD

**Issue by dasilvaj4** [npm/npm#11458]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'steam' ]
2 info using npm@3.3.12
3 info using node@v5.5.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData steam
8 silly fetchNamedPackageData steam
9 silly mapToRegistry name steam
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/steam
13 verbose request uri https://registry.npmjs.org/steam
14 verbose request no auth needed
15 info attempt registry request try #1 at 08:44:25
16 verbose request id ba5cfceabd656f84
17 verbose etag "CBDCU5KF06N7XNI7UKG1XH320"
18 http request GET https://registry.npmjs.org/steam
19 http 304 https://registry.npmjs.org/steam
20 verbose headers { date: 'Sun, 07 Feb 2016 10:44:20 GMT',
20 verbose headers   via: '1.1 varnish',
20 verbose headers   'cache-control': 'max-age=300',
20 verbose headers   etag: '"CBDCU5KF06N7XNI7UKG1XH320"',
20 verbose headers   age: '101',
20 verbose headers   connection: 'keep-alive',
20 verbose headers   'x-served-by': 'cache-atl6243-ATL',
20 verbose headers   'x-cache': 'HIT',
20 verbose headers   'x-cache-hits': '1',
20 verbose headers   'x-timer': 'S1454841860.761817,VS0,VE0',
20 verbose headers   vary: 'Accept' }
21 silly get cb [ 304,
21 silly get   { date: 'Sun, 07 Feb 2016 10:44:20 GMT',
21 silly get     via: '1.1 varnish',
21 silly get     'cache-control': 'max-age=300',
21 silly get     etag: '"CBDCU5KF06N7XNI7UKG1XH320"',
21 silly get     age: '101',
21 silly get     connection: 'keep-alive',
21 silly get     'x-served-by': 'cache-atl6243-ATL',
21 silly get     'x-cache': 'HIT',
21 silly get     'x-cache-hits': '1',
21 silly get     'x-timer': 'S1454841860.761817,VS0,VE0',
21 silly get     vary: 'Accept' } ]
22 verbose etag https://registry.npmjs.org/steam from cache
23 verbose get saving steam to C:\Users\dasil\AppData\Roaming\npm-cache\registry.npmjs.org\steam\.cache.json
24 silly install normalizeTree
25 silly loadCurrentTree Finishing
26 silly loadIdealTree Starting
27 silly install loadIdealTree
28 silly cloneCurrentTree Starting
29 silly install cloneCurrentTreeToIdealTree
30 silly cloneCurrentTree Finishing
31 silly loadShrinkwrap Starting
32 silly install loadShrinkwrap
33 silly loadShrinkwrap Finishing
34 silly loadAllDepsIntoIdealTree Starting
35 silly install loadAllDepsIntoIdealTree
36 silly rollbackFailedOptional Starting
37 silly rollbackFailedOptional Finishing
38 silly runTopLevelLifecycles Starting
39 silly runTopLevelLifecycles Finishing
40 silly install printInstalled
41 verbose stack Error: Refusing to install steam as a dependency of itself
41 verbose stack     at checkSelf (C:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:40:14)
41 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
41 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
41 verbose stack     at chain (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
41 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:15:5
41 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
41 verbose stack     at Array.forEach (native)
41 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
41 verbose stack     at Array.forEach (native)
41 verbose stack     at asyncMap (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
42 verbose cwd D:\Arquivos\Desktop\node-steam
43 error Windows_NT 10.0.10586
44 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "steam"
45 error node v5.5.0
46 error npm  v3.3.12
47 error code ENOSELF
48 error Refusing to install steam as a dependency of itself
49 error If you need help, you may report this error at:
49 error     <https://github.com/npm/npm/issues>
50 verbose exit [ 1, true ]

**Comment by ashleygwilliams** [comment]
hi! this error is a result of you attempting to install a module within a directory that has the same name:

```
47 error code ENOSELF
48 error Refusing to install steam as a dependency of itself
```

if you chance the name of the directory you are installing in to something other than `steam` you should be all set.

please open another issue if you continue to have trouble!
