### ISSUE TITLE
Cannot find module 'internal/util'

### ISSUE THREAD

**Issue by dimpiax** [npm/npm#11464]
sudo make install
scripts/doc-build.sh doc/cli/npm-help-search.md man/man1/npm-help-search.1
make[1]: Entering directory `/home/ec2-user/node/npm'
node cli.js install marked-man --no-global
npm ERR! Linux 4.1.10-17.31.amzn1.x86_64
npm ERR! argv "/usr/local/bin/node" "/home/ec2-user/node/npm/cli.js" "install" "marked-man" "--no-global"
npm ERR! node v6.0.0-pre
npm ERR! npm  v3.7.2
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'internal/util'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ec2-user/node/npm/npm-debug.log
make[1]: *** [node_modules/.bin/marked-man] Error 1
make[1]: Leaving directory `/home/ec2-user/node/npm'
make: *** [man/man1/npm-help-search.1] Error 2

**Comment by dimpiax** [comment]
I install node.js and npm on Amazon, Linux server through this manual: https://github.com/SIB-Colombia/dataportal-explorer/wiki/How-to-install-node-and-mongodb-on-Amazon-EC2

But after `sudo make install` – get error below.
Can't do any installs with npm.

**Comment by KenanY** [comment]
https://github.com/npm/npm/issues/11430?

**Comment by dimpiax** [comment]
@KenanY there is another npm version

**Comment by KenanY** [comment]
@dimpiax But this is a Node.js v6 issue?

**Comment by dimpiax** [comment]
@KenanY no, with Node.js all is fine. I can't install with npm anything.

**Comment by KenanY** [comment]
@dimpiax Hmm, I mean that as https://github.com/npm/npm/issues/11430#issuecomment-180639366 states, this a bug that Node.js introduced and that has not been fixed in `npm` yet. I think this issue can be closed just as https://github.com/npm/npm/issues/11430 was since this is the exact same issue.

**Comment by dimpiax** [comment]
@KenanY ok, hope this bug will be resolved asap.

**Comment by JamesDonnelly** [comment]
For anyone still experiencing this problem, it's because your node modules are out of date and you need to clear your cache.

For NPM version 4 and under:
```
npm cache clean && npm install
```

For NPM 5+:
```
npm cache verify && npm install
```
