### ISSUE TITLE
Npm install errors

### ISSUE THREAD

**Issue by zangarmarsh** [npm/npm#11463]
Hi, when I execute npm install on my project's main folder I get several errors:
> sudo npm install
> npm WARN deprecated gulp-minify-css@0.3.13: Please use gulp-cssnano instead.
> npm WARN deprecated lodash@2.4.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0
> npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0
> npm WARN deprecated win-spawn@2.0.0: use [cross-spawn](https://github.com/IndigoUnited/node-cross-spawn) or [cross-spawn-async](https://github.com/IndigoUnited/node-cross-spawn-async) instead.
> npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
> npm ERR! Linux 3.13.0-71-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v5.4.0
npm ERR! npm  v3.7.2

> npm ERR! Invalid array buffer length
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

> <--- Last few GCs --->

> 121501 ms: Scavenge 148.3 (210.2) -> 134.3 (210.2) MB, 9.1 / 0 ms [allocation failure].
  121669 ms: Scavenge 148.8 (211.2) -> 135.3 (211.2) MB, 11.0 / 0 ms [allocation failure].
  121912 ms: Scavenge 150.3 (212.2) -> 137.5 (212.2) MB, 13.5 / 0 ms [allocation failure].
  122708 ms: Scavenge 152.5 (213.2) -> 143.2 (215.2) MB, 50.7 / 0 ms [allocation failure].
  145086 ms: Scavenge 154.7 (215.2) -> 159.3 (75569.2) MB, 452.0 / 2 ms [allocation failure].

> <--- JS stacktrace --->

> ==== JS stack trace =========================================

> Security context: 0x1b1334fe3ac1 <JS Object>
    2: nextTick [node.js:~514] [pc=0x38da25aa508e] (this=0x9e064314ea9 <a process with map 0x81b25511d01>,callback=0xdeb1d80e459 <JS Function resume_ (SharedFunctionInfo 0x416a242cf89)>)
    3: arguments adaptor frame: 3->1
    4: resume [_stream_readable.js:~698] [pc=0x38da25715808] (this=0x9719bffd9a1 <an Unzip with map 0x418bc22f709>)
    5: on [_stream_readable.js:~664] [pc=0x38da25691f81] ...

> FATAL ERROR: Committing semi space failed. Allocation failed - process out of memory

My package.json:
> {
  "private": true,
  "devDependencies": {
    "gulp": "^3.8.8"
  },
  "dependencies": {
    "bootstrap-sass": "^3.0.0",
    "express": "^4.13.3",
    "illuminate/html": "5.0.x-dev",
    "ioredis": "^1.14.0",
    "laravel-elixir": "^2.0.0",
    "node-uuid": "^1.4.7",
    "socket.io": "^1.4.4",
    "underscore": "^1.8.3"
  }
}

Sorry, it's my first npm experience, I don't really understand how to solve this problem and Google didn't help me..
Thank you.

**Comment by ihorskyi** [comment]
@zangarmarsh 
* Do you experience the same issue if you run ~~sudo~~```npm install``` without sudo?
* Are you running install inside some container (docker/whatever) with limited memory?

Try to do this:
```rm -rf node_modules```
then run install without sudo 
```npm install```

**Comment by zangarmarsh** [comment]
@ihorskyi 
Hi. I did what you described above but I got the same errors.
For the limited memory thing, I'm currently running this command on a VPS with 1GB RAM..

**Comment by ihorskyi** [comment]
Your first log clearly shows that there is an issue with usage of more memory that your machine able to provide at that period of time. In such case you could increase amount of memory on your machine and/or find culprit package greedy for memory. 
I can only take a guess that it's ```laravel-elixir``` as I know there are few greedy sass packages :)

First of all try to do this: 
```npm i laravel-elixir``` 
This way you can check if there is the same error while just installing single ```laravel-elixir```
If error exists then you need to increase memory for your virtual machine.
If no errors installing it you can do complete install with detailed log which could show who is responsible for huge memory allocation using this:
```npm i --loglevel=silly 2>very_long_detailed.log``` 

P.S. before any check perform cleaning via ```rm -rf node_modules```

**Comment by zangarmarsh** [comment]
Thank you very much @ihorskyi for your help. I have resized my VPS RAM amount and now npm install works correctly.

**Comment by vineeth030** [comment]
Are you using Amazon EC2? I also have this issue. My client is preferring Amazon free tire plan with memory 1 GB. To which plan did you upgrade to solve this issue?

**Comment by zangarmarsh** [comment]
Hey vineeth030. I'm not using Amazon EC2, I'm actually using another well known provider, digitalocean. By the way, I solved the issue adding just 1GB of memory.

**Comment by vineeth030** [comment]
Thanks @zangarmarsh 
I somehow fixed this issue with [https://laracasts.com/discuss/channels/forge/forge-composer-update-memory-allocation#reply-46072]( this Forge recipe )

**Comment by rittamdebnath** [comment]
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN prefer global node-gyp@3.3.1 should be installed with -g

**Comment by KenanY** [comment]
@rittamdebnath unrelated to this issue

**Comment by malipraful** [comment]
FATAL ERROR: Committing semi space failed. Allocation failed - process out of memory
