### ISSUE TITLE
Error on npm install 

### ISSUE THREAD

**Issue by alexanderfried** [npm/npm#11468]
I'm getting an error when attempting a npm install. see attached file...
[npm-debug.txt](https://github.com/npm/npm/files/121125/npm-debug.txt)

**Comment by zkat** [comment]
Hi! If you look at the very end of that log, it looks like at least one of the packages you tried to install is hitting your network's filter (`proxy-middleware`) -- You'll need to talk with your network admin about whitelisting `https://registry.npmjs.org` to prevent this happening in the future.
