### ISSUE TITLE
UNABLE TO LOGIN USING NPM

### ISSUE THREAD

**Issue by mojoboss** [npm/npm#11460]
**I'm not able to login to npm using npm login. The error message I get is:**

starlord@starlord-Lenovo-Z580 ~ $ npm login
Username: mojoboss
Password: 
Email: mojo.killer1@gmail.com
npm http PUT http://registry.npmjs.org/-/user/org.couchdb.user:mojoboss
npm http 400 http://registry.npmjs.org/-/user/org.couchdb.user:mojoboss
npm ERR! Error: Unknown error while authenticating : -/user/org.couchdb.user:mojoboss
npm ERR!     at RegClient.<anonymous> (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:272:14)
npm ERR!     at Request.self.callback (/usr/lib/nodejs/request/index.js:148:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/index.js:896:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/lib/nodejs/request/index.js:847:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-37-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "login"
npm ERR! cwd /home/starlord
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/starlord/npm-debug.log
npm ERR! not ok code 0
`

**Comment by ashleygwilliams** [comment]
hi! you are using a very old version of npm. please update to either npm v2 or v3. you can do this by writing `npm install npm@2 -g` or `npm install npm@3 -g`

if you continue to have trouble, please open a new issue. thanks!
