### ISSUE TITLE
"npm config list" ignores per-project .npmrc

### ISSUE THREAD

**Issue by mjomble** [npm/npm#11472]
I created an empty directory and executed this:

```
> echo foo=1234 > .npmrc
> npm -v
3.7.1
> npm config get foo
1234
```

which looks ok. But if I execute `npm config list` in the same directory, the `foo` setting does not show up. Same on Windows and Linux.

Is this expected behavior or a bug?

**Comment by zkat** [comment]
This is definitely something missing that we think the CLI should do. There's currently no way to `ls` in a way that takes into account per-project configs, even though we have `-g` and `-l` flags to get more detailed/different config information.

Looking at our product roadmap, this is also not something we're really expecting to be able to get to in the next year, so we'd love community patches for adding this functionality. :)

Thanks for submitting this! We didn't really take into account how `npm config ls` would interact with per-project configs when it was originally implemented.
