### ISSUE TITLE
unable to install connect

### ISSUE THREAD

**Issue by yanboyang713** [npm/npm#11476]
```
npm install connect
npm ERR! Linux 4.4.1-2-ARCH
npm ERR! argv "/usr/local/bin/node" "/usr/bin/npm" "install" "connect"
npm ERR! node v5.4.1
npm ERR! npm  v3.7.1

npm ERR! No compatible version found: connect@undefined3.4.1
npm ERR! Valid install targets:
npm ERR! 3.4.1, 3.4.0, 3.3.5, 3.3.4, 3.3.3, 3.3.2, 3.3.1, 3.3.0, 3.2.0, 3.1.1, 3.1.0, 3.0.2, 3.0.1, 3.0.0, 3.0.0-rc.2, 3.0.0-rc.1, 2.30.2, 2.30.1, 2.30.0, 2.29.2, 2.29.1, 2.29.0, 2.28.3, 2.28.2, 2.28.1, 2.28.0, 2.27.6, 2.27.5, 2.27.4, 2.27.3, 2.27.2, 2.27.1, 2.27.0, 2.26.6, 2.26.5, 2.26.4, 2.26.3, 2.26.2, 2.26.1, 2.26.0, 2.25.10, 2.25.9, 2.25.8, 2.25.7, 2.25.6, 2.25.5, 2.25.4, 2.25.3, 2.25.2, 2.25.1, 2.25.0, 2.24.3, 2.24.2, 2.24.1, 2.24.0, 2.23.0, 2.22.0, 2.21.1, 2.21.0, 2.20.2, 2.20.1, 2.20.0, 2.19.6, 2.19.5, 2.19.4, 2.19.3, 2.19.2, 2.19.1, 2.19.0, 2.18.0, 2.17.3, 2.17.2, 2.17.1, 2.17.0, 2.16.2, 2.16.1, 2.16.0, 2.15.0, 2.14.5, 2.14.4, 2.14.3, 2.14.2, 2.14.1, 2.14.0, 2.13.1, 2.13.0, 2.12.0, 2.11.2, 2.11.1, 2.11.0, 2.10.1, 2.10.0, 2.9.2, 2.9.1, 2.9.0, 2.8.8, 2.8.7, 2.8.6, 2.8.5, 2.8.4, 2.8.3, 2.8.2, 2.8.1, 2.8.0, 2.7.11, 2.7.10, 2.7.9, 2.7.8, 2.7.7, 2.7.6, 2.7.5, 2.7.4, 2.7.3, 2.7.2, 2.7.1, 2.7.0, 2.6.2, 2.6.1, 2.6.0, 2.5.0, 2.4.6, 2.4.5, 2.4.4, 2.4.3, 2.4.2, 2.4.1, 2.4.0, 2.3.9, 2.3.8, 2.3.7, 2.3.6, 2.3.5, 2.3.4, 2.3.3, 2.3.2, 2.3.1, 2.3.0, 2.2.2, 2.2.1, 2.2.0, 2.1.3, 2.1.2, 2.1.1, 2.1.0, 2.0.3, 2.0.2, 2.0.1, 2.0.0, 1.9.2, 1.9.1, 1.9.0, 1.8.7, 1.8.6, 1.8.5, 1.8.4, 1.8.3, 1.8.2, 1.8.1, 1.8.0, 1.7.3, 1.7.2, 1.7.1, 1.7.0, 1.6.4, 1.6.3, 1.6.2, 1.6.1, 1.6.0, 1.5.2, 1.5.1, 1.5.0, 1.4.6, 1.4.5, 1.4.4, 1.4.3, 1.4.2, 1.4.1, 1.4.0, 1.3.0, 1.2.3, 1.2.2, 1.2.1, 1.2.0, 1.1.5, 1.1.4, 1.1.3, 1.1.2, 1.1.1, 1.1.0, 1.0.6, 1.0.5, 1.0.4, 1.0.3, 1.0.2, 1.0.1, 1.0.0, 0.5.10, 0.5.9, 0.5.8, 0.5.7, 0.5.6, 0.5.5, 0.5.4, 0.5.3, 0.5.2, 0.5.1, 0.5.0, 0.4.0, 0.3.0, 0.2.7, 0.2.6, 0.2.5, 0.2.4, 0.2.3, 0.2.2, 0.2.1, 0.2.0, 0.1.0, 0.0.6, 0.0.5, 0.0.4, 0.0.3, 0.0.2, 0.0.1
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/yanboyang/npm-debug.log
```

**Comment by ihorskyi** [comment]
Could you please provide your ```package.json```? 
Guess there is line with something like
```"connect": "undefined3.4.1"````

**Comment by yanboyang713** [comment]
hi man,
Thanks, I am first in npm, where is package.json?

**Comment by yanboyang713** [comment]
why I have found lots of package.json

**Comment by ihorskyi** [comment]
That is file in that directory where you ran that ```npm install connect``` commmand

**Comment by ihorskyi** [comment]
> why I have found lots of package.json
it's a very long story :) But to fix this issue you need to find ```package.json``` in the root of your project

**Comment by yanboyang713** [comment]
I am run arch linux, I am no any idea about package.json. Can you recommend some book for nodejs and npm?

**Comment by yanboyang713** [comment]
I don't why I have found lots of package.json in npm

**Comment by yanboyang713** [comment]
lots of package.json in /usr/lib/node_modules/npm/node_modules

**Comment by yanboyang713** [comment]
ok, I think i am successful install connect, but I have found another error
npm WARN onload-script failed to require onload script npm-autoinit/autoinit
npm WARN onload-script Error: Cannot find module 'npm-autoinit/autoinit'
npm WARN onload-script     at Function.Module._resolveFilename (module.js:325:15)
npm WARN onload-script     at Function.Module._load (module.js:276:25)
npm WARN onload-script     at Module.require (module.js:353:17)
npm WARN onload-script     at require (internal/module.js:12:17)
npm WARN onload-script     at cb (/usr/local/lib/node_modules/npm/lib/npm.js:291:11)
npm WARN onload-script     at /usr/local/lib/node_modules/npm/lib/npm.js:391:16
npm WARN onload-script     at /usr/local/lib/node_modules/npm/lib/config/core.js:80:7
npm WARN onload-script     at Array.forEach (native)
npm WARN onload-script     at /usr/local/lib/node_modules/npm/lib/config/core.js:79:13
npm WARN onload-script     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:17:25)
npm WARN onload-script  { [Error: Cannot find module 'npm-autoinit/autoinit'] code: 'MODULE_NOT_FOUND' }

**Comment by ihorskyi** [comment]
@yanboyang713 I can recommend you this guide https://docs.npmjs.com/getting-started/what-is-npm to become familiar with npm

**Comment by yanboyang713** [comment]
Thanks m8
