### ISSUE TITLE
freshness self-check

### ISSUE THREAD

**Issue by othiym23** [npm/npm#11473]
In https://github.com/npm/npm/issues/10800#issuecomment-181439557, @rosskevin says:

> It's easy to forget to update npm, I wish it had a reminder for me to keep it up to date when it falls behind. Bower does this and I find it quite useful

Homebrew does something like this as well.

Given that it's only going to get more important over time to have an up-to-date npm (at some point, a new Node release will become available that will break pretty much every old release of npm), and given how much of our support traffic comes from users stuck on antique versions of npm, the sooner the CLI team implements something like this, the sooner it will start to become useful.

**Comment by KenanY** [comment]
ref. previous discussion https://github.com/npm/npm/issues/5495

**Comment by othiym23** [comment]
Thanks, Kenan. I'm going to close this issue in favor of #5495, which I (obviously?) forgot was around.

**Comment by KenanY** [comment]
No problem :)

**Comment by othiym23** [comment]
We're going to reopen this issue and close #5495, because the sense of the CLI team is that _notifying_ people that their CLI is out of date is useful, but _auto-updating_ the CLI is more dangerous than the team is comfortable with.
