### ISSUE TITLE
npm error

### ISSUE THREAD

**Issue by melvilgit** [npm/npm#11478]
getting this error while npm install 
9 error npm  v3.3.12
10 error code MODULE_NOT_FOUND
11 error Cannot find module 'internal/util'

**Comment by KenanY** [comment]
What Node.js version? This might be another instance of https://github.com/npm/npm/issues/11430.

**Comment by TheAlphaNerd** [comment]
@melvilgit are you installing node from source?

**Comment by KenanY** [comment]
@melvilgit Are you still seeing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
