### ISSUE TITLE
What version of NPM is compatible with shrinkwrap? 0.10.31 does not seem to work

### ISSUE THREAD

**Issue by xtianus79** [npm/npm#11488]
It may not be the npm version or node version specifically but I wanted to confirm when exactly did the npm / node version first have compatibility with NPM shrinkwrap?  

I am getting a ton of npm ERR! extraneous warnings and thus no npm-shrinkwrap file is created... 

Again, the node version I am running this on is node -v 0.10.31 && npm -v 1.4.23

A couple example ERR's 

npm ERR! extraneous: lodash._basetostring@3.0.1 /Users/mbp06/Repos/salesrotor/node_modules/karma/node_modules/chokidar/node_modules/fsevents/node_modules/lodash._basetostring
npm ERR! extraneous: lodash._createpadding@3.6.1 /Users/mbp06/Repos/salesrotor/node_modules/karma/node_modules/chokidar/node_modules/fsevents/node_modules/lodash._createpadding

At first glance it seems the sub dependencies of Karma are not usable in this version which is then causing the error.

**Comment by ashleygwilliams** [comment]
hi! you are using a very old version of npm! (1.4.23)

npm actually has a completely different release cycle than Node does. i would recommend that you upgrade to the latest npm (`npm install npm@latest -g`). it will work fine with Node 0.10.31, even though you should probably update that at somepoint as well :)

please open another issue if you continue to have trouble!

**Comment by xtianus79** [comment]
thanks @ashleygwilliams ... just to ask... does the latest version of npm have the flattening feature? or is that the node version that will flatten assets instead of nesting them?

**Comment by heycalmdown** [comment]
@xtianus79 https://docs.npmjs.com/how-npm-works/npm3
