### ISSUE TITLE
NPM hanging on loadRequestedDeps → netwo

### ISSUE THREAD

**Issue by nuggit32** [npm/npm#11482]
Trying to install a appium package and npm keeps hanging on loadRequestedDeps → newt.

VM-AUTO:lib vm1$ npm -v
3.7.2

Gist log.
Trying to install a appium package and npm keeps hanging on loadRequestedDeps → newt.

VM-AUTO:lib vm1$ npm -v
3.7.2

Gist log.
https://gist.github.com/nuggit32/f19dc8e213d6c27961ea

Not sure what to do to get past this.  Please advise.

**Comment by bhaveshgohel** [comment]
+1 same issue with npm V3.7.2!

**Comment by nuggit32** [comment]
It appears I needed to change the network adapter to be on my ethernet lan connection for this installation to download and install. Smaller packages worked on the virtual network connection, but this was a big package with a lot of dependecies.

**Comment by schippie** [comment]
@nuggit32 What did you change about your network adapter settings? As i am also experiencing the same problem.

**Comment by nuggit32** [comment]
@schippie I changed it from my virtual network to my LAN Connections (Ethernet card) to do the download.

**Comment by schippie** [comment]
Hmm weird I do not have such a configuration myself (i am already connected directly through LAN through my ethernet card) and today it seems to have faded again. Not sure what caused it though.

**Comment by tyler-rand** [comment]
Same issue here on npm v3.7.3

**Comment by deleuterio** [comment]
Make sure your package.json has right permissions or run as administrator => `sudo npm install`
![selection_035](https://cloud.githubusercontent.com/assets/12951402/15931472/463feef6-2e2e-11e6-8339-47c5d261f9a4.jpg)
My case user don't have permissions to write on package.json and cause this error.

**Comment by richashri87** [comment]
it is stuck since 30 mins
npm install -g appium@1.6.4
⸨    ░░░░░░░░░░░░░░⸩ ⠦ loadRequestedDeps: sill install loadAllDepsIntoIdealTree

**Comment by neeraj022** [comment]
[    ..............] - loadRequestedDeps: sill install loadAllDepsIntoIdealTree.

My npm is getting stuck while installing leaflet.
npm version: 3.10.10

**Comment by mxia** [comment]
Turns out that updating the npm version from 3.6.0 to 5.3.0 made it work for me.
