### ISSUE TITLE
Cannot install private npm package: Not Found

### ISSUE THREAD

**Issue by enkitosh** [npm/npm#11481]
I cannot install a private npm package after successfully authenticating and logging in.

    npm ERR! Linux 4.4.1-2-ARCH
    npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "@temposoftware/tempo-cli"
    npm ERR! node v5.5.0
    npm ERR! npm  v3.7.1
    npm ERR! code E404

    npm ERR! 404 Not found : @temposoftware/tempo-cli
    npm ERR! 404 
    npm ERR! 404  '@temposoftware/tempo-cli' is not in the npm registry.
    npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
    npm ERR! 404 
    npm ERR! 404 Note that you can also install from a
    npm ERR! 404 tarball, folder, http url, or git url.

    npm ERR! Please include the following file with any support request:
    npm ERR!     /home/hover/npm-debug.log

My .npmrc
//registry.npmjs.org/:_authToken=$AUTH_TOKEN

My login prompt

    Username: temposoftware
    Password: xxxxxxxx
    Email: (this IS public) thordurhe@temposoftware.com
    Logged in as temposoftware on https://registry.npmjs.org/.

**Comment by ihorskyi** [comment]
@enkitosh, you should check if
1. ```@temposoftware/tempo-cli``` is listed in your packages like this when you login your account on npmjs.org (starting with '@')
2. Is that the same email ```thordurhe@temposoftware.com``` you login to your account to npmjs.org?
3. Does it say your account with email ```thordurhe@temposoftware.com``` has at least read access to that ```@temposoftware/tempo-cli```package?

**Comment by enkitosh** [comment]
@ihorskyi Thank you for these suggestions. Turns out that the problem was on my side. I was installing packages globally with sudo but of course I hadn't done npm login through sud, so user was logged in, not sudo. As soon as I did sudo npm login it worked. Now installing nvm to improve my npm version and user handling :)
