### ISSUE TITLE
npm unconditionally creates $prefix/etc

### ISSUE THREAD

**Issue by jbergstroem** [npm/npm#11486]
I found an issue while updating the ebuild (how gentoo packages works) for nodejs -- we had a sandbox violation -- meaning the package tried to install files or create directories that weren't expected. The sandbox violation pointed to `/usr/etc` which I was able to point to how config is instantiated in npm which we found since we generate the bash completion during the packaging phase.

It looks like [the code in question](https://github.com/npm/npm/blob/master/lib/config/core.js#L155) does so intentionally, but I'd argue that this might not be the best of behaviour. In gentoo's case, this would imply npm creating `/usr/etc` on first run, only to look for configs.

I think the proper way forward here is to not assume that the directory have to exist.

**Comment by jbergstroem** [comment]
Is this possibly related to the fs.existSync gripes thread back in May last year? :)

**Comment by jbergstroem** [comment]
..or perhaps introduce a way to change where the global config should live. In gentoo's case we'd still like to have prefix set to `/usr` while global config would live in `/etc/npm`.

**Comment by jbergstroem** [comment]
Sorry for the commit spam; if you look at the commit you can see that we patch npm's core config to avoid using prefix and rather look in `/etc/npm/{npmrc,npmignore}`. Not my proudest moment but we need to move forward and hopefully there's a solution where we can configure where a global config should live.

**Comment by jbergstroem** [comment]
I think this might affect more people soon. Had a quick look at other packagers and they will run into the same issue. This includes [alpine linux](http://git.alpinelinux.org/cgit/aports/tree/main/nodejs/APKBUILD?id=aec4a358dd97c2a81e5f7a1a0d62d3d6c9121dab#n31), [arch linux](https://projects.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/nodejs#n43), [gentoo as reported above](https://github.com/gentoo/gentoo/blob/master/net-libs/nodejs/nodejs-5.6.0-r1.ebuild#L110), [debian](http://anonscm.debian.org/cgit/collab-maint/nodejs.git/tree/debian/rules#n37) and so on. More UNIX:ey systems (based on pkgsrc [illumos] or pkg [freebsd]) avoids this by having the cleaner `/{opt,usr}/local` approach. Once npm 3 hits a wider market I htink we can expect a _lot_ of `$prefix/etc` directories out there.

Oh, I also checked the binaries from nodesource:
```bash
$ node -e "console.log(process)" | grep prefix
        node_prefix: '/usr',
``

**Comment by rvagg** [comment]
Confirmed for the NodeSource debian and rpm distros for v5 where we use `./configure --prefix=/usr`, it makes an empty `/usr/etc` at the start and presumably uses it for global config.

**Comment by jbergstroem** [comment]
ping!

**Comment by watilde** [comment]
Hmm.. how about `process.execPath` in the Debian?
https://github.com/npm/npm/blob/master/lib/config/defaults.js#L98-L99

**Comment by jbergstroem** [comment]
@watilde to me it looks like it would use `/usr/etc` again since most packagers installs to `/usr` meaning binary lives at `/usr/bin/node`.

**Comment by Delagen** [comment]
+1

**Comment by jbergstroem** [comment]
Ping upstream.

**Comment by endquote** [comment]
I'm running into this. I have a directory `/source/server`, and in `server` I have a `package.json` with a `start` script in it. If I'm in `source` and run `npm --prefix server start`, a `/source/server/etc` directory appears.

It's empty and harmless, but... weird.

**Comment by jbergstroem** [comment]
..what? You didn't even triage it and its reproducible amongst multiple users. Clearly a violation of write permissions.
