### ISSUE TITLE
npm access/team subcommand to list all users who have access to an org

### ISSUE THREAD

**Issue by zkat** [npm/npm#11494]
Right now, there's various commands that, in combination with `npm team` and `npm access` let you figure out the various users with access to various packages in your org.

There is no single way to get a complete listing of all users with access to your org: You'll need to `npm team ls` multiple different teams and work out the overlap, or just fudge it with `npm team ls org:developers`, assuming no one is removed from that default team.

It would be nice to have a command that did this *and* listed users that aren't in any teams, either, but still belong to the org.

**Comment by zkat** [comment]
note: This might be pretty simple to implement on our end, but would need some support from registry to set up the API on their end first (and maybe a bit of discussion about what to call this).

**Comment by othiym23** [comment]
This is describing the same underlying issue as #11491, so I'm going to close this in favor of that. After some confusion, we realized that there was a difference between the teams and orgs feature guide and the actual implementation / the CLI help around how the command functions, but we still have yet to implement the functionality.
