### ISSUE TITLE
missing script: start

### ISSUE THREAD

**Issue by bfonacier** [npm/npm#11508]
I don't know enough about npm but, I was trying to use it to install some things in an angular 2 sample project of mine.  I run into some issues trying to use the tool.  The script error suggest to report this to npm.  Here is my cli:

```
$ npm start
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12

npm ERR! missing script: start
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\ben\gitProj\angDemo\angular2\npm-debug.log
```
I'm also attaching the associated debug log.

[npm-debug1.txt](https://github.com/npm/npm/files/126849/npm-debug1.txt)

**Comment by KenanY** [comment]
@bfonacier Do you have a `"start"` script defined in your `package.json`? If not, then `npm` will have no idea what you would like it to do when you run `npm start`.

Relevant documentation which might help clear up `npm` scripts:

   - https://docs.npmjs.com/cli/start
   - https://docs.npmjs.com/misc/scripts

**Comment by KenanY** [comment]
@bfonacier Have you since resolved this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
