### ISSUE TITLE
npm ERR! Error: EBUSY (npm -install -g strongloop)

### ISSUE THREAD

**Issue by katperezz** [npm/npm#11501]
browser bundle successfully generated
**npm ERR! Error: EBUSY,** open 'C:\Users\Katrine\AppData\Roaming\npm\node_modules\s
trongloop\node_modules\strong-registry\node_modules\inquirer\node_modules\lodash
\package.json'

**Comment by HardieBoeve** [comment]
Can you try to update npm?

**Comment by othiym23** [comment]
Closing as a duplicate of #8564.
