### ISSUE TITLE
peerDependencies do not deal with `""` (empty string) version constraint correctly

### ISSUE THREAD

**Issue by zerkms** [npm/npm#11511]
Given a project with this initial `package.json`:

``` json
{
  "name": "t",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": { },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "immutable": "^3.7.6",
    "react": "^0.14.7"
  }
}
```

after we install a library with the following peer dependencies:

```
  "peerDependencies": {
    "immutable": ">=2.0.10",
    "react": ""
  },
```

we expect that everything will run fine.

What happens instead is: the library is installed but with the error message:

```
├── UNMET PEER DEPENDENCY react@0.14.7
```

Why is it happening?

Reproducible on at least v3.6.0 and v3.7.1, not reproducible on v3.3.12

**Comment by tcoats** [comment]
Would you want to use "*" instead?

**Comment by zerkms** [comment]
It indeed works with the `*` but it must work with either.

**Comment by lxe** [comment]
I think that [`""` means the same as `"*"` as far as semver is concerned](https://github.com/npm/node-semver/commit/e17dc0a535ae3aa3d8a20d4537ed5a180339441e). Both are valid identifiers.

Maybe this is related to #11493 as well.
