### ISSUE TITLE
Facing the issue on npm install

### ISSUE THREAD

**Issue by nkhushir** [npm/npm#11514]
C:\Users\kumarnaveen>npm install express -g
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "express" "-g"
npm ERR! node v4.3.0
npm ERR! npm  v2.14.12
npm ERR! code UNABLE_TO_GET_ISSUER_CERT_LOCALLY

npm ERR! unable to get local issuer certificate
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\kumarnaveen\npm-debug.log

please hhelp me out ASAP

**Comment by japhethnyakundi** [comment]
try installing first bower "bower install" and change your "cd" after git cloning a resipotary

**Comment by KenanY** [comment]
@nkhushir Are you still seeing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
