### ISSUE TITLE
TypeError: The header content contains invalid characters

### ISSUE THREAD

**Issue by aroramanoj2005** [npm/npm#11515]
Getting below error when running this command:- npm install –g grunt-cli bower yo generator-karma generator-angular

TypeError: The header content contains invalid characters

**Comment by majo44** [comment]
+1

**Comment by aroramanoj2005** [comment]
any update on this issue? do we have any work around?

**Comment by SiegfriedEhret** [comment]
I got the same error using node v0.12.10.
I switched to 0.12.9 and it's fixed.
I switched back to 0.12.10 and it's working... Strange !

**Comment by othiym23** [comment]
This doesn't seem to be an error on the CLI side of npm. I'll run this past the registry team to see if they  have any ideas, but also, let me ask: are you accessing the registry from behind a proxy? This sounds like the kind of error that comes from one server talking to another, and the fact that in @SiegfriedEhret's case it's intermittent makes me wonder.

**Comment by programmador** [comment]
Yesterday I've installed fresh nodejs 4.3.1 on windows to use with angularjs tutorial
http://angular.ru/tutorial
When I run came up to 'npm start' - it started the webserver successfully on port 8000.
But when I tried to access localhost:8000 using the browser, server crashed with same error:
"The header content contains invalid characters"

**Comment by ssunkari** [comment]
Hi guys,
Make sure you dont have any extension methos on Objects like
Object.prototype.ofSomeFunc = function (args, done) {
   //do something
};
This will add unnecessary methods to the headers, latest node version doesn't like certain character codes especially unnecessary methods like these. Hope it helps.

**Comment by programmador** [comment]
In my case absolutely same code works in linux and crashes in windows. node version is 4.3.1 in both OS's.

**Comment by ssunkari** [comment]
is your node modules compiled native to linux? and running same
code on windows.

On Friday, February 19, 2016, Alexander Konotop <notifications@github.com>
wrote:

> In my case absolutely same code works in linux and crashes in windows.
> node version is 4.3.1 in both OS's.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/npm/npm/issues/11515#issuecomment-186382536>.
>


-- 
Sent from Gmail Mobile

**Comment by aroramanoj2005** [comment]
Running on windows

**Comment by gggin** [comment]
same problem

**Comment by programmador** [comment]
For me the case was the bug in `http-server`:
https://github.com/indexzero/http-server/issues/244
It's now fixed in 0.9.0.

But the message about invalid characters actually occured while running server `npm start` in non-english windows, and not while installing anything with npm.

**Comment by sneakyfildy** [comment]
Hi, please inspect this https://github.com/indexzero/http-server/issues/244#issuecomment-197804202
looks like Date.toString issue for non-english Windows

**Comment by abbazer** [comment]
Having the same problem? What's wrong who can tell?

Running "karma:unit" (karma) task
INFO [karma]: Karma v0.12.37 server started at http://localhost:8080/
INFO [launcher]: Starting browser PhantomJS
INFO [PhantomJS 1.9.8 (Windows 7 0.0.0)]: Connected on socket zzmMkvAyQWbv3fL01Ka5 with id 37564538
Fatal error: The header content contains invalid characters


Execution Time (2016-04-28 07:45:33 UTC)
concurrent:test       7s  ■■■■■■■■■■■■■■■■■■■■■■■■■■■ 63%
autoprefixer:dist  529ms  ■■■ 5%
connect:test        1.2s  ■■■■■ 11%
karma:unit          2.4s  ■■■■■■■■■■ 21%
Total 11.1s


Process finished with exit code 3

**Comment by sneakyfildy** [comment]
@abbazer have u seen https://github.com/karma-runner/karma/issues/1994
what is test environment locale?

**Comment by justlo0king** [comment]
If there are some strings injected into headers (that might have non-English characters) - make sure they are wrapped into encodeURIComponent() or something similar.

**Comment by donvadicastro** [comment]
I found this exception relates to "karma" npm package when non-english location used.

**Comment by abbazer** [comment]
[SOLVED]
The problem was in karma "common.js" middleware lib
Replaced "toString" with "toUTCString" in header execution. Thanks for all of you

**Comment by KenanY** [comment]
@aroramanoj2005 In your command, you are using a hyphen-minus instead of a regular hyphen. Fix that and you should be good to go :)

Everyone else in this thread seems to be getting this error in something that's completely unrelated to the `npm` CLI, so I'm gonna close this as resolved. If anyone still has this issue, please open a new ticket and fill out the support form :)
