### ISSUE TITLE
devDependencies break dependencies

### ISSUE THREAD

**Issue by yzarubin** [npm/npm#11510]
Just ran into this case on 3.6.0, but is also broken using latest 3.7.1.

Using the following package.json:
```
{
	"dependencies": {
		"express": "4.12.4"
	},
	"devDependencies": {
	 	"path-to-regexp": "1.2.1"
	}
}
```

It will install only the 1.2.1 version of `path-to-regexp` in the root, which will be subsequently consumed by Express. But, Express actually depends on `path-to-regexp 0.1.3`, which will NOT be installed as a local dependency of express.

**Comment by lxe** [comment]
Running npm install twice is usually the temporary workaround for these:

```console
$ npm install 
...
$ npm ls
npm ERR! missing: path-to-regexp@0.1.3, required by express@4.12.4
...
$ npm install
/Users/aleksey/test-devdeps
└─┬ express@4.12.4
  └── path-to-regexp@0.1.3
```

**Comment by iarna** [comment]
Closing in favor of #11766
