### ISSUE TITLE
shasum check failed for geoip-lite-1.1.6.tgz

### ISSUE THREAD

**Issue by rigoletj** [npm/npm#11518]
Here's the error I'm currently facing:

npm ERR! shasum check failed for /tmp/npm-259-bb43b1bd/registry.npmjs.org/geoip-lite/-/geoip-lite-1.1.6.tgz
npm ERR! Expected: 6801f740c27f38d46e185ac8323df9c8315e84e7
npm ERR! Actual:   104c01cf1a856181602ea0e62b11262568c37057
npm ERR! From:     https://registry.npmjs.org/geoip-lite/-/geoip-lite-1.1.6.tgz

**Comment by animeshsingh** [comment]
This is currently blocking us completely.

**Comment by KenanY** [comment]
@rigoletj Are you still experiencing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
