### ISSUE TITLE
extend npm-search - add searching by name/tags/description/LICENSE/dependencies/...

### ISSUE THREAD

**Issue by blitmap** [npm/npm#11519]
Searching on npmjs.com or using npm-search is unfiltered and painful.  npm-search does seem to allow searching with a regex, but this still matches against name _and_ description - still producing more results than you can make quick sense of.

I want to suggest that npm-search be extended to allow specifically searching by name, description, tag, **LICENSE**, and dependencies (normal, dev, optional).  Even supporting a filter expression to run against the object package.json creates?  (might be too expensive)

A common complaint I hear is that there are many modules released performing the same functions, but because we cannot easily find these projects we wind up further fracturing and producing more 'wheels'.

I believe improving npm-search (and making npmjs.com use the new functions) - would greatly improve how quickly people can become productive in node.  I commonly search on npmjs.com because I can potentially see an example of how the library is used.

It's frustrating when you find a module you really like, but later realize you can't make use of it because of the license.  Similarly, you may want to find only modules that make use of dependencies you already have in your project.  Being able to find 'complementary' modules would be fantastic!

PS: It might be cool to suggest related search terms.  I formerly did not know what 'scaffolding' was and had been searching for 'project layout' exhaustively with few good results.

PPS: Why does npm-search deal directly with how it colors itself in the terminal[0]?  I thought commands of npm would return an object to the 'main' script and that would color the output or format it (according to terminal width[1]) appropriately:

0: https://github.com/npm/npm/blob/master/lib/search.js#L249
1: https://github.com/npm/npm/blob/master/lib/search.js#L256

**Comment by jez9999** [comment]
I totally agree with this.

What's more, this issue should be expanded into a general "improve npm searching" request.  Additional suggestions:

- Put much more weight on number of downloads.  The module you want is *probably* popular.
- Put much more weight on number of stars.  The module you want is *probably* starred a lot.
- Add a dropdown to allow for ordering search results by downloads, stars, created, updated, alphabetical, and maybe some more.

**Comment by jcrben** [comment]
Agreed - in the meantime, there are various third-party tools at http://stackoverflow.com/questions/10568512/how-to-find-search-find-npm-packages

After glancing at a few - including http://npmsearch.com/ (https://github.com/nodesource/npmsearch) - none of them stood out as amazing to me.
