### ISSUE TITLE
[MODULES] Separate dev's modules from others

### ISSUE THREAD

**Issue by gchauvet** [npm/npm#11517]
I encountering a small limitation when I want to deploy a project into a production environment without development modules. From Jenkins, I have to this this kind of script:

Stage 1) the CI pass :
```sh
npm install
npm run test
```
Stage 2) If all tests is okay, deployment time :
```sh
rm -rf node_modules
npm install --production
#copy the whole project to the server destination
```
This is a bit greedy; I suggest to separate dev's dependencies from other dependencies by adding a new folder level inside "node_modules" directory as below :

For required dependencies :
```
node_modules/required
```
For dev dependencies :
```
node_modules/development
```
By this way, we just need to copy the project without including the "node_modules/development" folder.

**Comment by KenanY** [comment]
@gchauvet You'll have to ask the Node.js devs to change `require()` in such a way as to recognize those two new folders. Module system is locked though so I think this will be promptly rejected.

**Comment by othiym23** [comment]
@KenanY has it correctly here: this would require changes to the Node module resolution algorithm, which is locked down and extremely unlikely to change in this way. As such, I'm going to close this, but you might want to take a look at `npm prune --production`, which may save you a step or two when moving from development to production mode. (There's also `npm install --only=dev` and `npm install --only=prod` for some variations on this behavior.)

**Comment by gchauvet** [comment]
Thank you for your feedbacks, I will continue to work with my current scripts for now
