### ISSUE TITLE
npm install as root is buggy/unpredictable.

### ISSUE THREAD

**Issue by gigafied** [npm/npm#11512]
On Debian, and likely other Linux distros, running `npm install` inside a package as root has unexpected behavior:

Steps to repro :
Create a new folder `test`, add a `package.json` with the following contents :

```
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "install": "echo hello"
  },
  "author": "",
  "license": "ISC"
}
```

save and run `$ npm install`

You will see this happen :

```
npm WARN lifecycle test@1.0.0~install: cannot run in wd %s %s (wd=%s) test@1.0.0 echo hello /srv/test
npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No repository field.
```

There are three issues here.
- (minor) Formatting of the string is buggy
- It failed to run the install script (why?). Guessing this has something to do with `unsafe-perm`
- Despite failing to run the install script it exits with 0, this should be an error and considered fatal. It should not fail 'silently' (in the normal context of `npm install` the whole dependency tree gets dumped to stdout so this warning gets buried, making it worse).

If you install this as a module, i.e. :

```
$ cd ../
$ npm install ./test
```

It works!!? 

```
root@UniFi-NVR:/srv# npm install ./test

> test@1.0.0 install /srv/node_modules/test
> echo hello

hello
/srv
`-- test@1.0.0
```

If anything, I would expect the behavior to be reversed, but really it should either refuse to run any install scripts or run them all. It shouldn't be dependent on if it's the install script from the current module.

The harm of course, is an install script doing something like `$ rm -rf /` or installing malware, but there is much more risk/likelihood of a submodule being compromised than your own install script.

**Comment by othiym23** [comment]
What version of npm are you using?

**Comment by gigafied** [comment]
Sorry, this is on `3.7.1`

**Comment by johsnguyen** [comment]
apm install
