### ISSUE TITLE
npm cache clean attempts to destroy home directory

### ISSUE THREAD

**Issue by timbluespeck** [npm/npm#11520]
I noticed a strange problem today while building a docker file for an app I'm working on - npm cache clear appeared to delete the /root directory under certain conditions. I've replicated this bug using multiple versions of npm on two different machines. When the home directory is empty, running npm install elsewhere, then npm cache clear afterwards, will cause npm to try to remove the home directory.

**npm versions tested:** 2.14.9, 3.7.3
**tested from:** bash shell on alpine 3.3, bash shell on an Ubuntu box

**Steps to replicate**
1) Clear home directory of all files and directories, including hidden files
2) run "npm install async" (or other modules) in a directory not the home directory (eg /tmp/testbuild)
3) run "npm cache clean"

**Expected result:** npm cache is cleaned, removing only the ~/.npm directory

**Actual result:** npm cache clean attempts to remove the home directory too. If run as root, this will delete /root entirely. As a non-root user this throws the following error:

```
npm ERR! Linux 3.13.0-77-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "cache" "clean"
npm ERR! node v0.12.10
npm ERR! npm  v2.14.9
npm ERR! path /home/testamagig
npm ERR! code EACCES
npm ERR! errno -13

npm ERR! Error: EACCES, rmdir '/home/testamagig'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, rmdir '/home/testamagig'] errno: -13, code: 'EACCES', path: '/home/testamagig' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/lol/npm-debug.log
```

npm-debug.log - https://gist.github.com/timbluespeck/f3727faea4774e54

**Comment by pingunaut** [comment]
same problem here with npm v4.2.1 on RHEL.
The cache directory was set to a custom path like /my/node/path/cache
When running cache clear, it tries to remove it's parent folder /my/node/path

**Comment by Clement-TS** [comment]
Have the same issue here, and it might be a common case for Docker users.
I fix it by adding an empty file in the $HOME dir (.ash_history for instance)

**Comment by jodok** [comment]
same with a alpine3.4 based docker container
