### ISSUE TITLE
npm ERR! Cannot find module 'npm-autoinit/autoinit'

### ISSUE THREAD

**Issue by vickykm2000** [npm/npm#11522]
I am getting following error while installing appium on mac terminal using command [ "npm install -g appium"]

Please help..
## Error :--- 

npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/Cellar/node/5.4.0/bin/node" "/usr/local/bin/npm" "install" "-g" "appium"
npm ERR! node v5.4.0
npm ERR! npm  v3.3.12
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'npm-autoinit/autoinit'
npm ERR! 
npm ERR! If you need help, you may report this error at:

**Comment by stod0021** [comment]
npm config delete onload-script npm-autoinit/autoinit
try this... 
installing 'npm-autoinit/autoinit' caused this issue. previous command is how you get rid this error. 
npm uninstall npm-autoinit/autoinit to get rid of it.

**Comment by juank52009** [comment]
Hi...

If you have a issue like the following picture

![image](https://cloud.githubusercontent.com/assets/18407942/15079254/1854fe62-137d-11e6-837d-4466409f3a65.png)


Try: 

Search the following file: C:\Program Files\nodejs\node_modules\npm\lib\npm.js

Right Click and edit the file... Search in the file where the module is called and apply a comment:
![image](https://cloud.githubusercontent.com/assets/18407942/15079333/7ff0c8a8-137d-11e6-99ee-a4d53dbdb82b.png)

![image](https://cloud.githubusercontent.com/assets/18407942/15079335/89562046-137d-11e6-9ffb-085b2a175c6d.png)

 /*
if (onload) {
        try {
          require(onload)
        } catch (err) {
          log.warn('onload-script', 'failed to require onload script', onload)
          log.warn('onload-script', err)
        }
        onload = false
      }

*/

And finally review again if everything works ok:

![image](https://cloud.githubusercontent.com/assets/18407942/15079418/fb49f808-137d-11e6-87c3-10506f612692.png)

Regards,

JuanC

**Comment by jerryhall** [comment]
Thanks JuanC. Was having the same problem and this did the trick.  Node 6.5, npm v 3.10.3 on Win7
