### ISSUE TITLE
Global update doesn't work

### ISSUE THREAD

**Issue by infusion** [npm/npm#11534]
Hi,

I have `npm update -g` in my local update script for a while, but it doesn't work anymore since a few versions. When I ran `npm -g outdated` I saw mocha and a few other outdated global packages listed. When I update them via `npm -g install mocha` one by one, it works just fine, but the shortcut to update all packages doesn't work anymore - or at least it only updates npm itself.

I'm running on OSX 10.11.3, node v5.5.0 and npm 3.7.2.

**Comment by rbartoli** [comment]
+1

I get exactly the same.

```bash
$ npm outdated -g --depth=0

Package            Current  Wanted  Latest  Location
babel-cli            6.5.1   6.5.1   6.9.0
browser-sync        2.11.2  2.11.2  2.12.8
generator-nm         2.5.0   2.5.0   2.8.0
grunt-cli           0.1.13  0.1.13   1.2.0
hotel               0.4.12  0.4.12  0.4.22
http-server          0.8.5   0.8.5   0.9.0
local-npm            1.5.7   1.5.7   1.5.8
npm-check            5.0.3   5.0.3   5.2.1
npm-check-updates    2.5.8   2.5.8   2.6.5
react-native-cli    0.1.10  0.1.10   0.2.0
stylelint            4.3.6   4.3.6   6.5.1
svgo                 0.6.1   0.6.1   0.6.6
updtr                0.1.7   0.1.7  0.1.15
yo                   1.7.0   1.7.0   1.8.3
```

Then I try to update:
`npm update -g` 

And I get no output.

If I check the outdated modules I get the same output as before:
```bash
$ npm outdated -g --depth=0

Package            Current  Wanted  Latest  Location
babel-cli            6.5.1   6.5.1   6.9.0
browser-sync        2.11.2  2.11.2  2.12.8
generator-nm         2.5.0   2.5.0   2.8.0
grunt-cli           0.1.13  0.1.13   1.2.0
hotel               0.4.12  0.4.12  0.4.22
http-server          0.8.5   0.8.5   0.9.0
local-npm            1.5.7   1.5.7   1.5.8
npm-check            5.0.3   5.0.3   5.2.1
npm-check-updates    2.5.8   2.5.8   2.6.5
react-native-cli    0.1.10  0.1.10   0.2.0
stylelint            4.3.6   4.3.6   6.5.1
svgo                 0.6.1   0.6.1   0.6.6
updtr                0.1.7   0.1.7  0.1.15
yo                   1.7.0   1.7.0   1.8.3
```

**Comment by graycrow** [comment]
I have the same issue, Windows Server 2012R2, node 6.7.0, npm 3.10.8
`C:\>npm outdated -g --depth=0
Package                Current       Wanted   Latest  Location
electron-packager        7.4.0        7.4.0    8.1.0
eslint                   2.7.0        2.7.0    3.7.1
generator-aspnet         0.1.0        0.1.0    0.2.4
jspm                   0.16.34      0.16.34  0.16.46
tslint             3.7.0-dev.2  3.7.0-dev.2   3.15.1
typings                  1.3.2        1.3.2    1.4.0
vue-cli                  2.1.0        2.1.0    2.4.0
webpack                 1.13.0       1.13.0   1.13.2

C:\>npm -v
3.10.8

C:\>node -v
v6.7.0`

**Comment by warrenronsiek** [comment]
+1

**Comment by legodude17** [comment]
`npm update` is a known breaking point. It will be fixed in a later version.

**Comment by simevidas** [comment]
What’s the workaround? Uninstall, then install? 😅

**Comment by legodude17** [comment]
I think you can just install over it.

**Comment by adamreisnz** [comment]
It's beyond me how a glaring issue like this one doesn't get addressed or labelled for over a year and then just auto closed. I get that a lot of people use npm and that as a result, there are bound to be many issues that get raised, but surely there's a better way to filter through the issues and identify and prioritise actual showstoppers like this one.

**Comment by Extarys** [comment]
I totally agree. Like NPM doesn't really care.

**Comment by kylebebak** [comment]
It's amazing this issue hasn't been fixed, and more amazing it was auto-closed.

**Comment by massimocode** [comment]
I have installed nativescript globally. I have version `3.1.3`. The latest version is `3.3.0`. I keep doing `npm update nativescript -g` and nothing happens. That was with NPM version `5.0.3`.

I've since upgraded to NPM version `5.5.1` (by running `npm install npm@latest -g`) and now running `npm update nativescript -g` works fine.
