### ISSUE TITLE
how to resolve this error??

### ISSUE THREAD

**Issue by mueedahmed1** [npm/npm#11539]
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.14.12
3 info using node@v4.3.0
4 verbose stack Error: ENOENT: no such file or directory, open 'd:\Attendence\package.json'
4 verbose stack     at Error (native)
5 verbose cwd d:\Attendence
6 error Windows_NT 6.3.9600
7 error argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
8 error node v4.3.0
9 error npm  v2.14.12
10 error path d:\Attendence\package.json
11 error code ENOENT
12 error errno -4058
13 error syscall open
14 error enoent ENOENT: no such file or directory, open 'd:\Attendence\package.json'
14 error enoent This is most likely not a problem with npm itself
14 error enoent and is related to npm not being able to find a file.
15 verbose exit [ -4058, true ]
```

**Comment by KenanY** [comment]
Hi @mueedahmed1! From the error log, I can see that you are running `npm start` in a directory that does not contain a `package.json`. Frankly, `npm` has no idea what to do since there is no `package.json` available to describe what the `"start"` script should do. You can check out [the documentation](https://docs.npmjs.com/cli/start) for more information.

It is not clear to me what you are _expecting_ to happen when you run `npm start`. If you could explain, then maybe I will be able to help you reach that desired behavior.

**Comment by othiym23** [comment]
Hi, @mueedahmed1! @KenanY's guidance to you here is good – lifecycle scripts run by commands like `npm start` or `npm test` get their instructions from a `package.json` file in the current working directory when you run npm, which is what that error message is (imperfectly) communicating. If you read the documentation that @KenanY linked to, along with the information on [npm scripts](https://docs.npmjs.com/misc/scripts), you should get what you need. Therefore, I'm going to close this issue as resolved. Thanks for your time!

**Comment by mueedahmed1** [comment]
![check](https://cloud.githubusercontent.com/assets/12622228/13056586/0f358132-d438-11e5-811f-949be9f16b8a.png)

**Comment by mueedahmed1** [comment]
![check1](https://cloud.githubusercontent.com/assets/12622228/13056653/6e81021a-d438-11e5-8e86-344310cb96e3.png)
when run this command "npm start", so this error arise in cmd.

**Comment by othiym23** [comment]
It looks from your screenshots like you need to run `cd e:\Attendence\client` before running `npm start`, because from your editor screenshot it looks like `e:\Attendence\client` is where `package.json` is located. Am I reading that correctly?

**Comment by mueedahmed1** [comment]
I am running "npm start" only .my file is located in client folder.

**Comment by KenanY** [comment]
@mueedahmed1 Have you tried running `npm start` from within the `client/` folder?

**Comment by mueedahmed1** [comment]
@KenanY NO, I try this and then tell u what is happening..

**Comment by mueedahmed1** [comment]
@KenanY  problem is solve ...Thanks buddy for help...
and for your time

**Comment by mueedahmed1** [comment]
Also thanks to @othiym23 that give me a response..

**Comment by othiym23** [comment]
:+1: Glad you got everything figured out, @mueedahmed1!

**Comment by battalian** [comment]
I am getting this error when i tried to  install cordova & ionic "sudo npm install -g cordova ionic", what should i do??


![image](https://user-images.githubusercontent.com/18572376/27468218-3836e884-5806-11e7-88e9-9df28c8ba186.jpg)
