### ISSUE TITLE
npm list ignores --depth=x when used with --parseable

### ISSUE THREAD

**Issue by SrTobi** [npm/npm#11531]
`npm list --depth=0` only lists the direct dependencies of the current package.
But `npm list --depth=0 --parseable` prints the directories of all dependencies and completely ignores the `--depth=0`.

**Comment by KenanY** [comment]
Duplicate of https://github.com/npm/npm/issues/11495?

**Comment by KenanY** [comment]
I believe this was fixed in `npm@2.15.0` and `npm@3.8.2` (https://github.com/npm/npm/pull/11773).

**Comment by KenanY** [comment]
Closing as fixed. Can reopen if this is demonstrated to not be the case.
