### ISSUE TITLE
Can't install coffee script on windows 10

### ISSUE THREAD

**Issue by appuxc** [npm/npm#11542]
Can't install coffee script using " npm install -g coffee-script ".

**Comment by othiym23** [comment]
Hi! Can you provide a little more information as to what's going wrong? What version of npm are you running (and have you tried [updating npm recently](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows))? If there's an `npm-debug.log` left behind by the failed install, can you upload it?

**Comment by appuxc** [comment]
@othiym23  i've installed node.js  now (the stable version). node version - v4.3.0 , npm version - v2.14.12. I don't have any log file.

**Comment by othiym23** [comment]
What's the failure message you're seeing?

**Comment by appuxc** [comment]
Earlier i got stuck with something like this 'LoadRequestedDeps addR ' when using node.js v5, but now after installing v4 it didn't display any error, cursor blinks continuously

**Comment by othiym23** [comment]
That message is displayed as part of the new progress bar implementation in `npm@3`, and is a diagnostic that says what the installer is doing, so it's not necessarily an error. It sounds to me like the install is hanging, though, which is no good. Do you have Git installed on the machine running the install and in the `Path`? Are you accessing the network through a proxy?

**Comment by darkyen** [comment]
@appuxc can you do a verbose install ?

**Comment by busches** [comment]
@KenanY no updates in months

**Comment by KenanY** [comment]
Closing as abandoned.
