### ISSUE TITLE
npm pack does not pack typescript d.ts files

### ISSUE THREAD

**Issue by episage** [npm/npm#11546]
Sample repo: https://github.com/charto/example-typescript-npm

Compile it and `npm pack` it. 
Contents of tgz file will not have d.ts files. 
Why?

**Comment by vchatterji** [comment]
Why is this issue closed?

I can replicate it with TypeScript 1.8.10

Using npm pack does not include the d.ts files.

**Comment by vchatterji** [comment]
@episage in your sample project, you have `*.d.ts` included in your `.npmignore`.

I removed that and the files are included.

My project structure is:
```
|
|--- src
|--- test
|--- dist     <= My gulp file compiles and places the js, sourcemaps and .d.ts files here
|      |--- src
|      |--- test
|--- typings
.gitignore
.npmignore
gulpfile.js
package.json
README.md
tsconfig.json
tslint.json
typings.json
```

I added the following in `.npmignore` to avoid including extraneous files and keep the bare minimum to have the package imported and working:
```
node_modules/
*.log
*.tgz

src/
test/
gulpfile.js
tsconfig.json
tslint.json
typings.json
typings
dist/test
```

My `.gitignore` has:
```
typings

# ignore .js.map files
*.js.map
*.js

dist
```

My `package.json` has:
```
"main": "dist/src/index.js",
"typings":  "dist/src/index.d.ts",
```

Now I run:
```
npm pack
```

The resultant file has the following structure:
```
|
|--- dist
|       |--- src
|              |
|              index.js
|              index.js.map
|              index.d.ts
|
package.json
README.md
```

Now I go to the project where I want to use this as a library and type:
```
npm install ./project-1.0.0.tgz 
```

It successfully installs.

Now I create a file `index.ts` in my project where I just installed the npm
```
import Project = require("project");
```

Typing `Project.` gives me the Intellisense options which was the point of this whole exercise.

Hope this helps someone else in using their TypeScript npm projects as internal libraries in their bigger projects.

**Comment by BrainCrumbz** [comment]
Hi there

apparently we're incurring in the same problem. At [this](https://github.com/BrainCrumbz/Angular2-Toaster/tree/c269d3e4ea9fe33926ee0b2ef6731fb962fffac6) forked project branch: 

* `.npmignore` has been deleted (there was one originally)
* `files:` field in `package.json` has been added and it also lists the top `.d.ts` file
* `npm pack` adds top `.js` file and `.d.ts` files under `lib/`, but not the top `.d.ts` file

Is there anything wrong in there? Thanks
