### ISSUE TITLE
npm link inside project subfolder

### ISSUE THREAD

**Issue by osmanpontes** [npm/npm#11545]
Imagine the following folder structure to a package:

```
my-package
|--examples
|  `|--example1
|     `|...
|   |--example2
|     `|...
|--src
|  `|--file1.js
|   |--file2.js
|   |...
|--index.js
|--package.json 
```

The **examples/** folder has my example projects and I'd like to run them using the most recent **my-package**.
The **src/** folder has my-package files and the **index.js** has the access to my package public API.

What I did was run `npm link` in **../my-package**. After that, I ran `npm link my-package` inside **example1** folder. The problem is that in **my-package/examples/example1/node_modules** my-package is included with its **examples/** folder, ocurring a recursion, giving me a folder structure like this:

```
my-package
|--examples
|  `|--example1
|     `|--node_modules
|         `|--my-package
|            `|--examples
|               `|--example1
|                  `|--node_modules
|                     `|--my-package ...
|   |--example2
|     `|...
|--src
|  `|--file1.js
|   |--file2.js
|   |...
|--index.js
|--package.json 
```

I tried use **.npmignore** ignoring `exemples/`, but It didn't work. It works only on publish or install.

**Comment by uditalias** [comment]
@osmanpontes Have you found a solution for this issue?
