### ISSUE TITLE
Add documentation about being able to pass QueryBuilder as a value for knex.raw binding.

### ISSUE THREAD

**Issue by elhigu** [npm/npm#11556]
e.g. this is actually possible to do:

```js
knex('table').whereRaw('EXIST(?)', [knex('t2').where('id', 1)]).toString();
'select * from "table" where EXIST(select * from "t2" where "id" = \'1\')'
```

**Comment by KenanY** [comment]
@elhigu I think you have posted this to the wrong repository.

**Comment by othiym23** [comment]
> I think you have posted this to the wrong repository.

Indeed. The `knex` issue tracker is [thataway](https://github.com/tgriesser/knex/issues) (fun npm fact tho: did you know that you can get to the bugs project for an npm package by running `npm bugs knex`? It works with most packages!).

**Comment by elhigu** [comment]
Oops sorry :) Yeah definitely wrong repo :blush:
