### ISSUE TITLE
Rename '--global-style' to '--isolated'

### ISSUE THREAD

**Issue by Aarilight** [npm/npm#11554]
When installing a package during development of a dependent package, I frequently need to access them so see what's happening, or sometimes because I'm creating a new package myself.
I read through the install page three or four times before I found the `--global-style` option. The name doesn't really mean anything, so it was very easy to miss. I'm not sure many people will know what global packages even look like on the disk.

The reason I suggest `isolated` is it infers that the package you're installing will be isolated from the rest of the packages in the current folder (better for development).

**Comment by acarstoiu** [comment]
Funny, I find the name quite natural. Without knowing that this option existed I was looking the other day for a "global-like" setting.

**Comment by Aarilight** [comment]
Because you knew what global packages look like on disk? I don't even know where they're located--I never touch them haha

Maybe `--global-style` should stay, and `--isolated` (or a similar word) should be added to do the same thing. I still stand by the belief that `global-style` means nothing without knowing what it's referring to.

**Comment by cchamberlain** [comment]
@acarstoiu - One easy way to find where they are at is `which npm`, since npm is itself a global package.

**Comment by acarstoiu** [comment]
According to the [docs](https://docs.npmjs.com/files/folders), the correct way to obtain that is:
- on Unices: `which node` (or `process.env._` in JS), then go up two directories and add `/lib/node_modules`
- on Windows: `where node` (or `process.env._` in JS), then go up one directory and add `/node_modules`

The environment variable `NODE_PATH` has _no saying_ in this. It only has to do with Node.js, when `require()` calls are honoured and thus should contain the global directory computed by `npm`.
