### ISSUE TITLE
problem instaling Browsersync

### ISSUE THREAD

**Issue by y0el22** [npm/npm#11555]
hi guys any help with this please!!?

[debug info.docx](https://github.com/npm/npm/files/131939/debug.info.docx)

thank you!!

**Comment by KenanY** [comment]
@y0el22 Can you upload the `npm-debug.log` as a _text file_ to [gist.github.com](https://gist.github.com/) and post a link to it here?

**Comment by y0el22** [comment]
https://gist.github.com/y0el22/cd381e2dbe1e16470198

Is that what you need? sorry I'm new here.
