### ISSUE TITLE
Why are all the modules getting installed in such weird way?

### ISSUE THREAD

**Issue by koushik72** [npm/npm#11566]
Before When I was installing any module, it was getting installed like this
![2016-02-16 1](https://cloud.githubusercontent.com/assets/12221775/13082252/ea51c4de-d4f5-11e5-90ae-9feac026e3f4.png)

but now it's getting installed like this
![2016-02-16](https://cloud.githubusercontent.com/assets/12221775/13082267/fe8d2cd6-d4f5-11e5-83c3-1c8db95a62a1.png)

I can't really understand what's wrong?
I will really appreciate some input into it.
Thanks in advance.

**Comment by othiym23** [comment]
While this is surprising, nothing is wrong. You've probably recently updated to `npm@3`, which uses a new, maximally flat install algorithm by default. This means that more of your dependencies' dependencies will be installed in the top-level `node_modules` folder, and as a result npm is less likely to cause the path length issues that are such a chronic problem of working with Node on Windows. [Here's a bit more information](https://github.com/npm/npm/blob/master/CHANGELOG.md#flat-flat-flat) from the `npm@3` release notes, if you want more context. Thanks for your time!

**Comment by ashleygwilliams** [comment]
this docs page also visualizes the algorithm for you:
https://docs.npmjs.com/how-npm-works/npm3

**Comment by koushik72** [comment]
@othiym23 @ashleygwilliams Thanks a lot for your time.
I thought it was a problem with my system. Thanks for the clarification.
