### ISSUE TITLE
Reordering keys in package.json

### ISSUE THREAD

**Issue by lafin** [npm/npm#11568]
I have a problem with auto reordering keys, after installation dependencies  https://github.com/vicapow/webgl-heatmap/blob/master/package.json#L28-L34. For the section browserify -> transform ordering is important. Maybe has workaround for this? 
@ https://github.com/vicapow/webgl-heatmap/pull/1

**Comment by KenanY** [comment]
@lafin `npm --version`? This should have been fixed by https://github.com/npm/npm/pull/10185, which was released in `npm@3.7.0`.

**Comment by lafin** [comment]
3.6.0
@KenanY thanks
