### ISSUE TITLE
npm install fail error EADDRINUSE jshint

### ISSUE THREAD

**Issue by mlabmedia** [npm/npm#11572]
Hi
I have been trying to install jshint that is required for SublimeLinter-jshint following the instructions here: https://github.com/SublimeLinter/SublimeLinter-jshint

I am running windows 7 (64bit).

**It seems to keep failing with the error message:**

`C:\Users\Ephekz>npm install -g jshint
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files (x86)\nodejs\\node.exe" "C:\Program Files (
x86)\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "jshint"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code EADDRINUSE
npm ERR! errno EADDRINUSE
npm ERR! syscall connect

npm ERR! connect EADDRINUSE
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Ephekz\npm-debug.log`

**I have tried this so far:**
**1.** disabling AVG antivirus
**2.** disabling windows Firewall
**3.** checking if port 443 is in use by another service using netstat -aon : findstr:443. (nothing is listening in on that port)
**4.** tried different versions of nodejs v.5.6.0, v.4.3.0, v.0.1.24
**5.** tried multiple internet connections, also tried internet connection with no router
**6.** tried "npm cache clean"
**7.** tried "npm config set registry https://registry.npmjs.org/" and also "npm config set registry http://registry.npmjs.org/"
**8.** I have tried installing a different package (bower) which was successful.

I am not really sure what to do from here to make this work. Any suggestions would be greatly appreciated. I have attached [npm-debug-log.txt](https://github.com/npm/npm/files/133529/npm-debug.txt)

Thank you

**Comment by mlabmedia** [comment]
is there any support available for npm?

**Comment by mlabmedia** [comment]
I was able to resolve this issue by reinstalling the driver for my network adapter.

**Comment by ovidiubarbu** [comment]
I was not :( - opened another issue for it
