### ISSUE TITLE
npm install of package folder should respect the "engine-strict" setting in its .npmrc file

### ISSUE THREAD

**Issue by cybersam** [npm/npm#11573]
(I am using npm 3.7.2, and node 5.4.1.)

The `engine-strict` section of the [npm config doc](https://docs.npmjs.com/misc/config) claims:

> If set to true, then npm will stubbornly refuse to install (or even consider installing) any package that claims to not be compatible with the current Node.js version.

However, if the following are all true, then the above claim is FALSE, and `npm` will happily install the package without even a warning:
1. Use either the `npm install` or `npm install <folder>` command.
2. The package folder contains a `.npmrc` file (specifying `engine-strict: true`) that _should_ reverse the current `engine-strict` setting.
3. The package's `package.json` file contains an `engines` field that specifies a `node` version that is not satisfiable by the current node version.

I have found no way to get `npm install` to work as claimed in the above scenario.

However, I have found the following workaround when using `npm install <folder>`: `cd` to any folder _other than_ the package's folder, copy the `.npmrc` file to what is now the current folder, and install the package while in that folder. Doing so actually does cause `npm` to "stubbornly refuse to install". However, if the current `node` version _does_ satisfy the package's `engines` setting, and `npm package <folder>` succeeds, then the package's `node_modules` folder is created in the _current folder_, not the package's folder -- not very intuitive and possibly causing issues when actually running the package from within its folder (since the `node_modules` may not be in the module search path).

**Comment by mjrk** [comment]
Having the same problem ...

Did anybody find a way to use engine-strict: true (to validate the node/engine version!) while keeping the node_modules directory just where it is?

**Comment by kirkins** [comment]
I would also like to validate node version
