### ISSUE TITLE
NPM command stuck and doing nothing (hangs)

### ISSUE THREAD

**Issue by udaysurendra** [npm/npm#11577]
NPM command is not working  after upgrade from v0.10.37 to 4x and 5x.Once i type any npm command my command prompt gets stuck.Now it's even not working after downgrade to v0.10.37. Here below screen shots from my mechine

- [Screen shot on V4.2.3 ](http://iolife.in/4.2.3.PNG)
-  [Screen shot on V4.3.1 ](http://iolife.in/4.3.1.PNG)
-  [Screen shot on V5.6.0 ](http://iolife.in/5.6.0.PNG)

**Comment by darkyen** [comment]
What version of npm are you using ? I once was stuck with old version of npm (installed by the 0.x node) which was taking precedence over npm.

Can you try doing 

where npm and then checking the version of npm ? (If there are more than one).

**Comment by bendav91** [comment]
+1 Also getting this exact problem with Windows 10

[Screenshot
](http://i.imgur.com/EQSL0Wo.jpg)
Tried installing multiple versions, removing environment variables, & deleting folders manually - essentially cleansing machine completely of any traces of Node and NPM.

**Comment by bendav91** [comment]
Okay I resolved this on my machine, basically the global module location had been set incorrectly, and when NPM was initialising it couldn't find the folder with the global modules in, and just panics and doesn't know what to do.. 

**Here's what i did...**

So I navigated to my home directory. 
View hidden files, find the .npmrc file, and opened in a text editor. 
Change the path inside to a different location, (I created a .npm-global in the same directory)
