### ISSUE TITLE
npm install -g cordova has many errors after "bower install ngCordova"

### ISSUE THREAD

**Issue by bfonacier** [npm/npm#11579]
I just run across all these error.  Did I make a mistake installing cordova?  I have the log.

Oops, the log is too long.

**Comment by zkat** [comment]
Unfortunately, there's not much I can do without an actual error. Could you post the last few dozen lines of the log?

**Comment by bfonacier** [comment]
Here is a zip.  Hope it helps.
[npm-debug.zip](https://github.com/npm/npm/files/136083/npm-debug.zip)

**Comment by bfonacier** [comment]
I'm using windows 10.   I'm installing cordova. Npm could not find a file.

**Comment by zkat** [comment]
It looks like you're getting ECONNRESET errors -- usually, these are simply signs of flaky internet connections or flaky or misconfigured proxies. There's unfortunately not much we can do about that sort of stuff on our end -- you can probably keep retrying the install and hope it all works out one of those times, rely on the caching layer, etc.
