### ISSUE TITLE
npm init fail

### ISSUE THREAD

**Issue by cawo88** [npm/npm#11571]
When I run '_npm init_' I get this message.

```
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

See `npm help json` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg> --save` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
name: (abc)
```
I'm using npm version 3.7.3

This person had the same [issue] (https://github.com/npm/npm/issues/8120) but I don't have any capital letters in my folder name. I've also tried re-installing node as well.

**Comment by othiym23** [comment]
What's the failure you're seeing? What I'm seeing is the expected `npm init` prompt asking you for a package name.

**Comment by cawo88** [comment]
"Sorry, name can only contain URL-friendly characters."

**Comment by cawo88** [comment]
Okay.. I think I've fixed it by forcing it using 'npm init -f' again, weird thing is I rang this before but it didn't seem to work.

**Comment by etanlubeck** [comment]
@cawo88 what is the error you are getting?

**Comment by dhanyafranc** [comment]
am getting the same error "Sorry, name can only contain URL-friendly characters." on the npm init..
tried npm init -f.. but no luck..

**Comment by dhanyafranc** [comment]
am using npm 3.9.5

**Comment by jamelablack** [comment]
Was there any resolution to this issue? I am getting the same error.

**Comment by kentakozuka** [comment]
I had thought having a same issue, but I noticed I was typing 'npm install mypackage --save' instead of just package name. I am not sure this is a same issue though.

**Comment by SeanGallen** [comment]
I came across this problem in nodeschool.io  
So, if you have this problem exactly just type in the name of the package you want to creating.

Correct:
name: (abc) funtimes

Incorrect:
name: (abc) npm install funtimes--save

It should proceed as normal.

**Comment by Donny913** [comment]
I had the same problem, when was trying to run `npm init` **before** creating Gruntfile.js in the folder.
1) Create empty Gruntfile.js
2) Run `npm init`

**Comment by MisterCruz** [comment]
It looks like you're trying to install a package. You have to do npm init and complete the process before using npm install. npm init just sets up your package.json

**Comment by seyicole** [comment]
am getting the same error "Sorry, name can only contain URL-friendly characters." on the npm init..
tried npm init -f.. but no luck..
Just created my project file. am trying to install react js

**Comment by Razevich** [comment]
I am getting the same issue when trying to install react js. What is the solution?

**Comment by nataliadg** [comment]
I was getting the same issue trying to install express and I think I found the solution:
- First run ## npm init, first set the characteristics of the project, (if creating a standard project, just press enter for name, version, description, etc)

> This utility will walk you through creating a package.json file.
> 
> It only covers the most common items, and tries to guess sensible defaults.
> 
> See `npm help json` for definitive documentation on these fields
> 
> and exactly what they do.
> 
> Use `npm install <pkg> --save` afterwards to install a package and
> save it as a dependency in the package.json file.
> 
> Press ^C at any time to quit.
> name: (certinode)
> version: (1.0.0)
> description:
> git repository:
> keywords:
> author:
> license: (ISC)**

> 
> About to write to C:\Users\usuario\Desktop\projects\certinode\package.json:
> 
> {
>   "name": "certinode",
>   "version": "1.0.0",
>   "main": "app.js",
>   "scripts": {
>     "test": "echo \"Error: no test specified\" && exit 1"
>   },
>   "author": "",
>   "license": "ISC",
>   "dependencies": {
>     "express": "^4.15.2"
>   },
>   "devDependencies": {},
>   "description": ""
> }
> 
> 
> Is this ok? (yes)
> 


- Once you´ve finished the init accepting the characteristics, you can install all packages you need. Now yow can run as many ## npm install <package> --save as you want.

Hope it helps you.

**Comment by jaxsiete** [comment]
Hello Nataliadg:
I followed your commands and ended up with a very similar process as yours with the exception at the end which states: npm update check failed, Try running with sudo or get access to the local update config store via... 
Not sure what I am doing wrong. I have the latest version of npm installed?

<img width="798" alt="npm init" src="https://cloud.githubusercontent.com/assets/28573776/25865952/9dfddae0-34a9-11e7-8c84-c8286e9e438a.png">

**Comment by legodude17** [comment]
What is the problem?

**Comment by jaxsiete** [comment]
The problem is that I am trying to install package.json in my glup-dev file. After creating that file:
$ cd Desktop/outpostss/wp-content/themes
$ mkdir Glup-dev
I then run 'npm init' and follow the directions above that Natalia described. It works fine until the end when I want to save the package.json in gulp-dev and it gives me an error message. Package.json is not in the file. Not sure what the problem is?

**Comment by jaxsiete** [comment]
Figured it out....Never mind:)

**Comment by adityashukla74** [comment]
I am facing the same issue with Mac, Yosemite 
npm@5.0.3
node@8.1.3
Have tried doing npm init, npm cache clean with -f Flag too. 
Also tried uninstalling and reinstalling different versions of NPM and NODE.
From past 3 months it was working for me, this issue has come up from nowhere.
Help
Thanks in advance.

<img width="1070" alt="screen shot 2017-07-08 at 5 26 32 pm" src="https://user-images.githubusercontent.com/11692248/27985134-319bfd80-6403-11e7-99c5-d02008f349ce.png">

**Comment by ghost** [comment]
I got the same issue.
But then tried npm install -f option. Its working..

**Comment by SharangSharma09** [comment]
npm install -f works for me in this case

**Comment by tsa97** [comment]
command mkdir stands for creating a new directory
None of files in this directory

1. If we put "npm init" to command prompt, the "npm init" function will guide us to create a new package.json file to make store the package that we wanna use.

2. After the package.json created, we are freely install the package that we want by using either "npm install" or "npm install -f"
