### ISSUE TITLE
The header content contain invalid charecters

### ISSUE THREAD

**Issue by vasanth3390** [npm/npm#11575]
When i tried to install the Bower in node.js it shows me a error in npm saying

The header content contain invalid charecters.

Node.Js version is 5.6.0
Bower version is 3.6.0

Can any one help me to sort out this issue

**Comment by zkat** [comment]
Hey! Could you post more details about your platform (OS?), and your `npm-debug.log` after trying to do this?

**Comment by FredericRod** [comment]
Hi, I have the same issue. Here is my log file:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'http-server',
1 verbose cli   '–g' ]
2 info using npm@3.6.0
3 info using node@v5.6.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData http-server
8 silly fetchPackageMetaData –g
9 silly fetchNamedPackageData http-server
10 silly mapToRegistry name http-server
11 silly mapToRegistry using default registry
12 silly mapToRegistry registry https://registry.npmjs.org/
13 silly mapToRegistry uri https://registry.npmjs.org/http-server
14 silly fetchOtherPackageData –g
15 silly cache add args [ '–g', null ]
16 verbose cache add spec –g
17 verbose request uri https://registry.npmjs.org/http-server
18 verbose request no auth needed
19 info attempt registry request try #1 at 11:07:43 AM
20 verbose request id ffc91765fef2a7cd
21 http request GET https://registry.npmjs.org/http-server
22 verbose stack TypeError: The header content contains invalid characters
22 verbose stack     at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:348:11)
22 verbose stack     at new ClientRequest (_http_client.js:85:14)
22 verbose stack     at Object.exports.request (http.js:31:10)
22 verbose stack     at Object.exports.request (https.js:197:15)
22 verbose stack     at Request.start (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\request.js:746:30)
22 verbose stack     at Request.end (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\request.js:1357:10)
22 verbose stack     at end (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\request.js:574:14)
22 verbose stack     at Immediate._onImmediate (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\request.js:588:7)
22 verbose stack     at processImmediate [as _immediateCallback] (timers.js:383:17)
23 verbose cwd c:\Fred\Temp\Demo
24 error Windows_NT 6.1.7601
25 error argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "http-server" "–g"
26 error node v5.6.0
27 error npm  v3.6.0
28 error The header content contains invalid characters
29 error If you need help, you may report this error at:
29 error     <https://github.com/npm/npm/issues>
30 verbose exit [ 1, true ]

Thanks

**Comment by mvnsrpavankumar** [comment]
Hi Friends, I have the same issue. Here is my log file:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'gulp-sass',
1 verbose cli   '–g' ]
2 info using npm@2.14.12
3 info using node@v4.3.2
4 verbose install initial load of C:\Users\pavankumar_mvnsr\AppData\Roaming\npm\package.json
5 verbose installManyTop reading scoped package data from C:\Users\pavankumar_mvnsr\AppData\Roaming\npm\node_modules\gulp\package.json
6 verbose readDependencies loading dependencies from C:\Users\pavankumar_mvnsr\AppData\Roaming\npm\package.json
7 silly cache add args [ 'gulp-sass', null ]
8 verbose cache add spec gulp-sass
9 silly cache add args [ '–g', null ]
10 verbose cache add spec –g
11 silly cache add parsed spec Result {
11 silly cache add   raw: 'gulp-sass',
11 silly cache add   scope: null,
11 silly cache add   name: 'gulp-sass',
11 silly cache add   rawSpec: '',
11 silly cache add   spec: 'latest',
11 silly cache add   type: 'tag' }
12 silly addNamed gulp-sass@latest
13 verbose addNamed "latest" is being treated as a dist-tag for gulp-sass
14 info addNameTag [ 'gulp-sass', 'latest' ]
15 silly mapToRegistry name gulp-sass
16 silly mapToRegistry using default registry
17 silly mapToRegistry registry https://registry.npmjs.org/
18 silly mapToRegistry uri https://registry.npmjs.org/gulp-sass
19 verbose addNameTag registry:https://registry.npmjs.org/gulp-sass not in flight; fetching
20 silly cache add parsed spec Result {
20 silly cache add   raw: '–g',
20 silly cache add   scope: null,
20 silly cache add   name: null,
20 silly cache add   rawSpec: '–g',
20 silly cache add   spec: 'C:\\Users\\pavankumar_mvnsr\\AppData\\Roaming\\npm\\–g',
20 silly cache add   type: 'local' }
21 verbose request uri https://registry.npmjs.org/gulp-sass
22 verbose request no auth needed
23 info attempt registry request try #1 at 11:09:15 AM
24 verbose request id d93083f2afd4b521
25 http request GET https://registry.npmjs.org/gulp-sass
26 error addLocal Could not install C:\Users\pavankumar_mvnsr\AppData\Roaming\npm\–g
27 verbose stack TypeError: The header content contains invalid characters
27 verbose stack     at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:351:13)
27 verbose stack     at new ClientRequest (_http_client.js:79:14)
27 verbose stack     at Object.exports.request (http.js:31:10)
27 verbose stack     at Object.exports.request (https.js:167:15)
27 verbose stack     at Request.start (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:793:30)
27 verbose stack     at Request.end (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1400:10)
27 verbose stack     at end (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:564:14)
27 verbose stack     at Immediate._onImmediate (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:578:7)
27 verbose stack     at processImmediate [as _immediateCallback] (timers.js:383:17)
28 verbose cwd C:\Users\pavankumar_mvnsr\AppData\Roaming\npm
29 error Windows_NT 6.1.7601
30 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "gulp-sass" "–g"
31 error node v4.3.2
32 error npm  v2.14.12
33 error The header content contains invalid characters
34 error If you need help, you may report this error at:
34 error     <https://github.com/npm/npm/issues>
35 verbose exit [ 1, true ]


Can you some one please help me with a solution......

**Comment by KenanY** [comment]
Closing since @vasanth3390 never responded. Looking at the logs posted by @FredericRod and @mvnsrpavankumar, it seems like you're all use a [hyphen-minus](https://en.wikipedia.org/wiki/Hyphen-minus) instead of a regular hyphen. This issue should be resolved by simply using a regular hyphen.
