### ISSUE TITLE
npm install didnt follow package.json

### ISSUE THREAD

**Issue by annie-tseng** [npm/npm#11586]
I have wrote a package.json
{
  "name": "develop",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "ios6": "cordova emulate ios --target='iPhone-6'",
    "android": "cordova run android"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "jquery": "^2.1.3",
    "jquery-mobile": "^1.4.1",
    "xss": "^0.2.2"
  },
  "devDependencies": {
    "browser-sync": "^2.9.4",
    "gulp": "^3.8.11",
    "gulp-autoprefixer": "^2.1.0",
    "gulp-clean": "^0.3.1",
    "gulp-concat": "^2.5.2",
    "gulp-if": "^1.2.5",
    "gulp-jshint": "^1.9.4",
    "gulp-minify-css": "^1.0.0",
    "gulp-rename": "^1.2.0",
    "gulp-rev-mtime": "0.0.4",
    "gulp-ruby-sass": "^2.0.3",
    "gulp-sourcemaps": "^1.5.1",
    "gulp-uglify": "^1.1.0",
    "gulp-useref": "^1.2.0",
    "run-sequence": "^1.1.0"
  },
  "jshintConfig": {
    "unused": false,
    "globals": {
      "$": false,
      "jQuery": false
    }
  }
}

and I got lots of packages that I didnt write in devDependencies  after npm install. 

I also get same result after npm install gulp.

**Comment by KenanY** [comment]
@annie-tseng Is this with `npm@3`? What you are seeing is probably `npm` simply moving dependencies up the tree in order to produce the flattest structure possible.

**Comment by annie-tseng** [comment]
`brew install node --without-npm
mkdir "${HOME}/.npm-packages"
echo NPM_PACKAGES="${HOME}/.npm-packages" >> ${HOME}/.bashrc
echo prefix=${HOME}/.npm-packages >> ${HOME}/.npmrc
curl -L https://www.npmjs.org/install.sh | sh
echo NODE_PATH=\"\$NPM_PACKAGES/lib/node_modules:\$NODE_PATH\" >> ${HOME}/.bashrc
echo PATH=\"\$NPM_PACKAGES/bin:\$PATH\" >> ${HOME}/.bashrc
echo source "~/.bashrc" >> ${HOME}/.bash_profile
source ~/.bashrc`

I've used this script to install node, I'm not sure its npm@3 or not.

**Comment by KenanY** [comment]
@annie-tseng This is how `npm@3` works. Those "extra" packages you are seeing are dependencies of the packages you have defined in your `package.json`. https://docs.npmjs.com/how-npm-works/npm3

**Comment by annie-tseng** [comment]
this is the result I got after `npm ls`
├── browser-sync@2.11.1
├── gulp@3.9.1
├── gulp-autoprefixer@2.3.1
├── gulp-clean@0.3.1
├── gulp-concat@2.6.0
├── gulp-if@1.2.5
├── gulp-jshint@1.12.0
├── gulp-minify-css@1.2.3
├── gulp-rename@1.2.2
├── gulp-rev-mtime@0.0.4
├── gulp-ruby-sass@2.0.6
├── gulp-sourcemaps@1.6.0
├── gulp-uglify@1.5.2
├── gulp-useref@1.3.0
├── jquery@2.2.0
├── jquery-mobile@1.4.1
├── run-sequence@1.1.5
└── xss@0.2.10

but there are another folders in /node_modules like below
! [folder](http://imgur.com/gb7Tnf5)

**Comment by annie-tseng** [comment]
Thanks, I figured out what's the different between `npm@2` and `npm@3`.

**Comment by othiym23** [comment]
Closing as resolved.

**Comment by chan71** [comment]
Above link doesn't work. Here's what works as at today.
http://npm.github.io/how-npm-works-docs/npm3/how-npm3-works.html
