### ISSUE TITLE
node_modules/history always ends up in the NPM tarball, this bug happens in v3.x

### ISSUE THREAD

**Issue by xile611** [npm/npm#11582]
This bug was fixed in v2.x, but happens in v3.x now. Please fix it in v3.x.

**Comment by KenanY** [comment]
Based on the discussion in https://github.com/npm/npm/issues/9642, I believe this will be fixed by https://github.com/npm/npm/pull/10445.

**Comment by KenanY** [comment]
I believe this was fixed in `npm@3.8.7` (https://github.com/npm/npm/pull/11995).

**Comment by KenanY** [comment]
Closing as fixed. If this is not the case then I can reopen.
