### ISSUE TITLE
How could i install a specific version of yeoman for example 0.1.2

### ISSUE THREAD

**Issue by NajehM** [npm/npm#11591]
**i'v tried to install it using 
 npm install yo@0.1.2 but i got this**
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "yo@0.1.2"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12

npm ERR! version not found: yo@0.1.2
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Program Files\Git\npm-debug.log

*_npm version: 2.14.12
node version: 4.3.1
and i work with windows 7 *_

**Comment by KenanY** [comment]
@NajehM As the error message states, there does not exist such a version of `yo`. Here is a list of published versions:

``` sh
$ npm info yo versions
[ '1.1.0',
  '1.1.1',
  '1.1.2',
  '1.2.0',
  '1.2.1',
  '1.3.0',
  '1.3.2',
  '1.3.3',
  '1.4.1',
  '1.4.2',
  '1.4.4',
  '1.4.5',
  '1.4.6',
  '1.4.7',
  '1.4.8',
  '1.5.0',
  '1.5.1',
  '1.6.0' ]
```

**Comment by NajehM** [comment]
oh thanks

**Comment by NajehM** [comment]
in fact i have the version 1.6.0 installed and i would like to install older version, i want a more stable one. Kindly let me know how to do so. 
because i tried with npm install

**Comment by KenanY** [comment]
@NajehM Could you try the following?:

```
npm cache clean
npm set registry https://registry.npmjs.org/
```

**Comment by NajehM** [comment]
**@KenanY yes sure i ran it, and i tried again with npm install yo@1.2.0 but i got this**
npm WARN peerDependencies The peer dependency grunt-cli@>=0.1.7 included from yo will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency bower@>=1.0.0 included from yo will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'

> yo@1.2.0 postinstall C:\Program Files\Git\node_modules\yo
> node ./scripts/doctor

[Yeoman Doctor] Everything looks alright!

grunt-cli@0.1.13 node_modules\grunt-cli
├── resolve@0.3.1
├── nopt@1.0.10 (abbrev@1.0.7)
└── findup-sync@0.1.3 (lodash@2.4.2, glob@3.2.11)

bower@1.7.7 node_modules\bower

yo@1.2.0 node_modules\yo
├── is-root@0.1.0
├── sudo-block@0.4.0
├── fullname@0.1.1
├── opn@0.1.2
├── async@0.9.2
├── lodash@2.4.2
├── shelljs@0.3.0
├── chalk@0.4.0 (ansi-styles@1.0.0, has-color@0.1.7, strip-ansi@0.1.1)
├── yosay@0.2.1 (pad-component@0.0.1, word-wrap@0.1.3, minimist@0.0.9)
├── nopt@3.0.6 (abbrev@1.0.7)
├── findup@0.1.5 (commander@2.1.0, colors@0.6.2)
├── string-length@0.1.2 (strip-ansi@0.2.2)
├── update-notifier@0.1.10 (semver@2.3.2, configstore@0.3.2, request@2.69.0)
├── insight@0.3.1 (object-assign@0.1.2, async@0.2.10, lodash.debounce@2.4.1, request@2.27.0, configstore@0.2.3, inquirer@0.4.1)
└── yeoman-generator@0.17.7 (dargs@2.1.0, diff@1.4.0, isbinaryfile@2.0.4, underscore.string@2.4.0, mime@1.3.4, text-table@0.2.0, class-extend@0.1.2, iconv-lite@0.4.13, debug@1.0.4, mkdirp@0.5.1, cross-spawn@0.2.9, chalk@0.5.1, run-async@0.1.0, glob@4.5.3, rimraf@2.5.2, file-utils@0.2.2, github-username@1.1.1, cheerio@0.17.0, gruntfile-editor@0.2.0, request@2.69.0, grouped-queue@0.3.2, inquirer@0.7.3, findup-sync@0.1.3, download@1.0.7)

**Comment by NajehM** [comment]
and the version stills the same 1.6.0
