### ISSUE TITLE
npm install graceful-fs@4.0.0 npm ERR! version not found: graceful-fs@4.0.0

### ISSUE THREAD

**Issue by NinaNVY** [npm/npm#11607]
![294](https://cloud.githubusercontent.com/assets/15184314/13179261/2776d936-d734-11e5-9868-6d4d2e336e64.png)

**Comment by KenanY** [comment]
@NinaNVY As the error log indicates, there does not exist such a version of `graceful-fs`. `npm` can only install versions that exist, such as:

``` sh
$ npm info graceful-fs versions
[ '1.0.0',
  '1.0.1',
  '1.0.2',
  '1.1.0',
  '1.1.1',
  '1.1.2',
  '1.1.3',
  '1.1.4',
  '1.1.5',
  '1.1.6',
  '1.1.7',
  '1.1.8',
  '1.1.9',
  '1.1.10',
  '1.1.11',
  '1.1.12',
  '1.1.13',
  '1.1.14',
  '1.2.0',
  '1.2.1',
  '1.2.2',
  '1.2.3',
  '2.0.0',
  '2.0.1',
  '2.0.2',
  '2.0.3',
  '3.0.0',
  '3.0.1',
  '3.0.2',
  '3.0.3',
  '3.0.4',
  '3.0.5',
  '3.0.6',
  '3.0.7',
  '3.0.8',
  '4.1.0',
  '4.1.1',
  '4.1.2',
  '4.1.3' ]
```

**Comment by NinaNVY** [comment]
Thank you! 
Installed '4.1.3', but why does Gulp Installation tell me again about graceful-fs ?
![300](https://cloud.githubusercontent.com/assets/15184314/13180394/51b75644-d739-11e5-82ff-24249289acea.png)

**Comment by ashleygwilliams** [comment]
probably graceful-fs is a dependency of a dependency that you are using and the semver expression that dep is using does not allow version 4. you'll have to look at the `package.json` of the dep that requires it. this is also why u see the lodash warning and the second graceful-fs warning.

updating your other dependencies may help fix this as those lib maintainers likely (hopefully!) updated those deps.

**Comment by ashleygwilliams** [comment]
i'm going to close this now. please open another issue if you continue to have trouble!

**Comment by melissamcewen** [comment]
In my experience this often happens in VMs run on Windows if the project is in a shared folder.

**Comment by NinaNVY** [comment]
@melissamcewen Thank you!

**Comment by lgcho123** [comment]
omg...

**Comment by cesarsagaon** [comment]
Can someone say how to solve this problem? I am having the same exact problem with gulp. I am new to programing too..
