### ISSUE TITLE
Liste local linked modules/packages

### ISSUE THREAD

**Issue by thonymg** [npm/npm#11603]
Hello, 
In practice i install all package in global scope with `-g`, after i use `npm link <module>` in my project. 
i have a freak connection, and i can't re-install all modules localy for each project with 'npm install'. 
i have a script in my npm package to "automate" the process.
the script look like that: 
`"scripts": {
    "relink": "npm link [huge list of modules]"
  },` 
it's work good, but i must add module one by one in that list. 

i would like to have something like this:
`"LinkedDependencies": {
    "babel-core": "^6.5.2",
    "babel-loader": "^6.2.2",
    ....
  }
` 
all new linked modules is "automaticly" listed, or installed with one command in another project.
anyone have a solution ? 

Merci !!! 
Sorry, english is not my first language.

**Comment by ryanve** [comment]
@thonymg maybe useful: [symlinked](https://www.npmjs.com/package/symlinked)
