### ISSUE TITLE
npm run start

### ISSUE THREAD

**Issue by claudioferreira79** [npm/npm#11601]
hi, i'm getting the following error(s) after trying install my own parse server on a mongoldb database. the error is on command: npm run start :

npm ERR! Error: ENOENT, open '/root/package.json'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.13.0-77-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "run" "start"
npm ERR! cwd /root
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! path /root/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /root/npm-debug.log
npm ERR! not ok code 0

**Comment by KenanY** [comment]
Hi @claudioferreira79! From the log, I can tell that you are running that command from within a directory which does not contain a `package.json`. Frankly, `npm` has no idea what you want it to do when you run `npm run start` unless you provide a `package.json` which defines a `"start"` script. Newer versions of `npm` have better error messages for these kinds of things so recommend [upgrading](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm).

**Comment by KenanY** [comment]
@claudioferreira79 Are you still seeing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
