### ISSUE TITLE
devDependencies in linked packages should not be considered extraneous

### ISSUE THREAD

**Issue by isaacs** [npm/npm#11609]
Here's a gist: https://gist.github.com/isaacs/8e9902d969947a22dd1c

If a package is linked, it should be allowed to have devDependencies, since it's likely a development folder.

(Probably not urgent, and easy enough to ignore, but I noticed this and didn't want to let it go un-captured.)

**Comment by schmod** [comment]
A better question might be why `npm ls` traverses linked packages at all.

There's some discussion in #10343 about this, and there seems to be a weak consensus that NPM should aggressively assume that linked packages have taken care of their own dependencies.

`peerDependencies` might be a special case, but I can't imagine many scenarios where NPM's current behavior is desirable.  

I'd be fairly okay declaring an explicit contract that states that, by default, npm should _not_ attempt to learn about the transitive dependencies of a linked package (although it may be practical for commands like `npm ls` to be able to optionally override this behavior with a flag).
