### ISSUE TITLE
npm install express <npm err !!!> 

### ISSUE THREAD

**Issue by beaubaby** [npm/npm#11616]
I tried to run command npm install express and npm install express -g in many times but it still shown error via console as below message.

> npm install express
> npm ERR! Windows_NT 6.1.7601
> npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "prefix" "-g"
> npm ERR! node v5.6.0
> npm ERR! npm  v3.6.0
> npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'npm-autoinit/autoinit'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "prefix" "-g"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0

npm ERR! Callback called more than once.
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\psagulvanitchaporn\Desktop\app\npm-debug.log
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "express"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'npm-autoinit/autoinit'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

Please help me fix it. T^T

**Comment by ArMikael** [comment]
I have the same issue with those parameters. 
I deleted all data from the enviroment variables, removed previos version of node.js and installed the last one from the scratch, but it did not help.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.7.0
npm ERR! npm  v3.6.0
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'github-url-from-git'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
