### ISSUE TITLE
npm run scripts child process event bubbling.

### ISSUE THREAD

**Issue by danielmurray** [npm/npm#11612]
In node I am spawning a child process that executes an NPM build script, which kicks off a watchify and node-sass process, I want to be notified when either of these processes perform a js/sass compilation, to move it into another directory, however the child process (npm run ...) does not propagate the grandchild stdio events to it's own stdio. Does NPM have any config settings that will bubble child stdio events?

**Comment by othiym23** [comment]
npm doesn’t do anything with stdio for processes any deeper than the processes it spawns directly; if gulp-sass or watchify are swallowing the output of the tasks they’re running, there’s nothing npm can do to affect that. It’s not entirely clear from your description of the problem which piece of this is missing the output from a child. I don’t think that, aside from setting up the child process environment and making sure that stdout and stderr are piped out of the output of npm itself, there’s anything for npm to do here. Am I understanding what you’re asking correctly?
