### ISSUE TITLE
Dependencies with version in the range of 0.0.0 ... 0.0.x are treated in a very special way when using tilde ranges

### ISSUE THREAD

**Issue by silkentrance** [npm/npm#11610]
Say, I have a dependency

```
{
    "dependencies": {
        "foo" : "~0.0.3"
    }
}
```

I would expect npm to fetch at least versions ``<0.1.0`` whenever there is an update.

And I believe that the SEMVER restrictions on caret ranges do not apply to tilde ranges.

In order to overcome this I need to specify my dependency as follows

```
{
    "dependencies": {
        "foo" : "~0.0"
    }
}
```

Any plans on changing this rather special behavior?

**Comment by othiym23** [comment]
There are no plans to change the behavior of either the `~` or `^` operators, for the simple reason that every time the project does so, either by introducing a new operator (like `^`) or by changing how an existing operator behaves (i.e. prerelease matching and semver ranges), it's hugely disruptive. The behavior of `0.0.x` versions has always been special, even in the SemVer specification, with the reasoning that `0.0.x` versions are "anything goes" playgrounds, where the entire interface could be changing between versions. Avoiding this behavior is also pretty easy, in that you can just bump the minor to `0.1`.

Thanks for bringing this up, though!

**Comment by silkentrance** [comment]
@othiym23 thanks for investigating this. I will fix my build process.
