### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by rohitchopra32** [npm/npm#11619]
![npm error](https://cloud.githubusercontent.com/assets/17051320/13197744/4ad66f16-d81c-11e5-8aee-5a5321cc8350.JPG)
[npm-debug.txt](https://github.com/npm/npm/files/139226/npm-debug.txt)

**Comment by rohitchopra32** [comment]
guys help me please!!!!

**Comment by mrmozza** [comment]
Looks like you're getting a similar error to me but I'm running on a mac. I just reinstalled npm and everything seems to be working again now. Take a look here https://github.com/npm/npm/wiki/Troubleshooting

**Comment by rohitchopra32** [comment]
![a](https://cloud.githubusercontent.com/assets/17051320/13264593/e560875e-da94-11e5-8b0f-33f0230a03e0.JPG)
after reinstalling the newer version of node its giving this error.

**Comment by rohitchopra32** [comment]
closed by mistake..

**Comment by rohitchopra32** [comment]
can anyone show me proper steps for installing angular js properly??

**Comment by KenanY** [comment]
@rohitchopra32 Is this still an issue for you?

**Comment by KenanY** [comment]
Closing as abandoned.
