### ISSUE TITLE
Stop showing deprecation warnings of sub-dependencies to end users

### ISSUE THREAD

**Issue by leo** [npm/npm#11628]
Every time I'm installing a certain package for one of my projects, I get a lot of those:

<img width="143" alt="screen shot 2016-02-21 at 20 33 07" src="https://cloud.githubusercontent.com/assets/6170607/13204852/5bfdcdac-d8da-11e5-8714-d859838facff.png">

I understand that they're important: Because if they wouldn't exist, developers wouldn't be able to keep track of deprecated versions of their project's dependencies.

However I don't understand why I as an **end user** am seeing those. I mean: I'm not the person who's responsible for replacing/updating those deprecated dependencies. Only the maintainer of the dependency/package I'm installing is.

Here's an example:

> I've installed a package called "whatever" and even added it to my `package.json`'s dependencies. While it was installing, my terminal shouted a lot of those deprecation warnings at me. Okay, fine. But what should I do with those? I'm not the maintainer of the package that depends on those deprecated packages. Why am I seeing those errors?

Wouldn't it be better to only show those errors when running `npm install` within the package that depends on those deprecated packages? This way, we could make sure that only the **maintainers** and NOT the actual **users** of the package will see those errors.

**Comment by LinusU** [comment]
I think that it's good that they are always displayed. It puts more pressure on the developers to fix it.

**Comment by adambuczynski** [comment]
I tend to agree with this issue. The notifications are of no use to consumers of packages. In terms of it putting more pressure on the package developers, I doubt it. I've raised several issues in various repo's about their packages issuing warnings, but have yet to see a developer promptly going to update their packages ;)

Here's an example of a typical log that I see after running `npm install`

```
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated npmconf@2.1.1: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated lodash@2.4.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0
npm WARN prefer global jsonlint@1.6.2 should be installed with -g
npm WARN prefer global node-gyp@3.3.0 should be installed with -g
```

The first warning has an issue raised about it, but the author said something to the extent of "we have no alternative at this stage and are not going to fix this, you can ignore the warning".

As for the rest of the deprecations, it's often hard to track down which package is the one that is not updating their dependencies. You can do an `npm ls`, but then if the tree show 5 packages, which is the one that didn't update their deps? For example:

```
├─┬ gulp-sass@2.2.0
│ └─┬ node-sass@3.4.2
│   ├─┬ gaze@0.5.2
│   │ └─┬ globule@0.1.0
│   │   └── lodash@1.0.2 
```

You can see that globule 0.1.0 is using an outdated lodash. Great, let's go complain there. But what if they are already at version 0.5.0 with a newer lodash? Then I guess gaze 0.5.2 is to blame. Let's go complain there. But what if they are already at 0.7.8 which uses the newer globule package? Then I guess node-sass didn't update their dependencies. Do you see what I'm getting at? :)

For consumers of packages it's a drag to have to find out which package is outdated and causing the warning, and I am also not really interested in those warnings, as long as the packages do what they are meant to. If and when they update their deps is their responsibility.

In addition, I also think the warnings about "prefers to be installed with -g" should be dropped for nested packages, as that's also useless for the consumer of the top level packages to know.

**Comment by leo** [comment]
@adambuczynski :+1:

**Comment by destroyerofbuilds** [comment]
@LinusU that would be my hope as well, but that rarely happens in practice. Also, given the difficulties brought up by @adambuczynski, it's quite unlikely most developers would ever sufficiently get over those hurdles to successfully file an issue against the offending package, let alone that issue be resolved by the package's maintainer.

I do believe that any dependency reported to contain a [security vulnerability](https://nodesecurity.io/) should be flagged by npm. That should be made as visible as possible to end consumers of node modules.

**Comment by othiym23** [comment]
There are architectural reasons these warnings keep bubbling up, even though I agree that non-actionable warnings for indirect dependencies shouldn't show up. The CLI team will get to this eventually, but it may be a few months given our current workload. We'd be delighted if somebody sent us a patch (including a test) suppressing these warnings before then. Thanks to everyone for their time!

**Comment by othiym23** [comment]
> I do believe that any dependency reported to contain a security vulnerability should be flagged by npm. That should be made as visible as possible to end consumers of node modules.

That sounds like something that is best handled right now by nsp, snyk.io, or bithound.io's scanners, because it would require a parallel infrastructure for checking and reporting packages with vulnerabilities that doesn't currently exist. Were we to integrate this into the CLI, it would need to be done so as to not have too significant an impact on performance. Also, that's something probably better tracked as a separate feature request or (preferably) PR, because it's more or less unrelated to the original issue.

**Comment by adambuczynski** [comment]
@othiym23 thank you, I will see if I can find the time to look into this.

**Comment by krainboltgreene** [comment]
So I'm looking at this and there appear to be two "logging deprecation notices" functions:

  1. https://github.com/npm/npm/blob/master/lib/utils/depr-check.js
  2. https://github.com/npm/npm/blob/master/lib/utils/warn-deprecated.js

Which of these is the real one? I'm thinking 1.

**Comment by pgarrison** [comment]
Looked into this a little bit. Didn't fix it but I want to mention that `npm cache add graceful-fs@1` (for example) should still produce a deprecation warning no matter what the `package.json` has.

@krainboltgreene It's 1. The second is about deprecations in npm features.
