### ISSUE TITLE
Specifying custom GitHub repo for a published package doesn't work in package.json

### ISSUE THREAD

**Issue by abbr** [npm/npm#11629]
I have to use a customized version of a published package `swagger-editor-src` in this [package.json](https://github.com/BCDevExchange/BCDevExchange-app/blob/master/package.json):
```
"dependencies":{
   ...
   "swagger-editor-src": "BCDevExchange/swagger-editor",
   ...
}
```
However, `npm install` disregarded the GH source I specified and installed published version instead. The npm I use is v3.7.3. Problem also occurs in older npm version.

**Comment by KenanY** [comment]
I cannot reproduce this with `npm@3.7.4`/`npm@3.7.3`/`npm@2.14.20`/`npm@2.14.9`.

**Comment by abbr** [comment]
Hmm... when I singled out this dependency to a new temp package.json it does pull correctly. But in my full-blown app it failed when building the docker image. I will close the ticket for now and reopen if I can find a way to reproduce.
Thanks for checking.
