### ISSUE TITLE
npm test not working

### ISSUE THREAD

**Issue by marapel** [npm/npm#11627]
~$ npm test
npm ERR! Error: ENOENT, open '/home/hara/package.json'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "test"
npm ERR! cwd /home/hara
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! path /home/hara/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/hara/npm-debug.log
npm ERR! not ok code 0
hara@asus:~$ sudo npm test
[sudo] password for hara: 
npm ERR! Error: ENOENT, open '/home/hara/package.json'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "test"
npm ERR! cwd /home/hara
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! path /home/hara/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/hara/npm-debug.log
npm ERR! not ok code 0

**Comment by KenanY** [comment]
@marapel From the error log, I can see that you do not have a `package.json` in your current working directory, Without a `package.json` defined a `"test"` script, `npm` has no idea what you want it to do when you run `npm test`. This is described in the documentation for [`npm test`](https://docs.npmjs.com/cli/test) and [`npm` scripts](https://docs.npmjs.com/misc/scripts).

**Comment by marapel** [comment]
Thanks KenanY. Now I am right directory but still have problems.

hara@asus:~/Lataukset/key-recovery-service-master$ npm test

> key-recovery-service@0.0.3 test /home/hara/Lataukset/key-recovery-service-master
> istanbul cover ./node_modules/.bin/_mocha -- --recursive

**/usr/bin/env: node: There is not such file or directory**
npm ERR! Test failed.  See above for more details.
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0
hara@asus:~/Lataukset/key-recovery-service-master$ nodejs bin/server
database connection error:  { [MongoError: connect ECONNREFUSED] name: 'MongoError', message: 'connect ECONNREFUSED' }
hara@asus:~/Lataukset/key-recovery-service-master$ 

Should I make directory to /usr or whatl. I'm confuced.

**Comment by KenanY** [comment]
@marapel Okay, so now I see two errors. Only the first one has to do with `npm`, so I'll focus on that.

Have you read the file mentioned in the error message?:

```
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
```

On your system, the Node.js binary is named `nodejs` but it should really be named just `node`. You could try symlinking:

``` sh
sudo ln -s /usr/bin/nodejs /usr/bin/node
```

**Comment by KenanY** [comment]
@marapel Are you still experiencing these issues?

**Comment by KenanY** [comment]
Closing as abandoned.
