### ISSUE TITLE
Cordova Installation Error In Windows 7

### ISSUE THREAD

**Issue by arpitsharma923** [npm/npm#11625]
When I Installing Cordova in windows 7 then get following output.

C:\>npm install -g cordova -verbose
npm info it worked if it ends with ok
npm verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'install',
npm verb cli   '-g',
npm verb cli   'cordova',
npm verb cli   '-verbose' ]
npm info using npm@3.6.0
npm info using node@v5.6.0
npm verb request uri http://registry.npmjs.org/cordova
npm verb request no auth needed
npm info attempt registry request try #1 at 4:11:54 PM
npm verb request id dfcacf377b1e2e87
npm verb etag "D4LSYY2HK3ZTV0W0SXIQE1GRX"
npm http request GET http://registry.npmjs.org/cordova
npm http 304 http://registry.npmjs.org/cordova
npm verb headers { date: 'Sun, 21 Feb 2016 10:42:00 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   'cache-control': 'max-age=300',
npm verb headers   etag: '"D4LSYY2HK3ZTV0W0SXIQE1GRX"',
npm verb headers   age: '166',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-sin6925-SIN',
npm verb headers   'x-cache': 'HIT',
npm verb headers   'x-cache-hits': '2',
npm verb headers   'x-timer': 'S1456051320.515977,VS0,VE0',
npm verb headers   vary: 'Accept' }
npm verb etag http://registry.npmjs.org/cordova from cache
npm verb get saving cordova to C:\Users\Manish\AppData\Roaming\npm-cache\regist
y.npmjs.org\cordova\.cache.json
npm verb correctMkdir C:\Users\Manish\AppData\Roaming\npm-cache correctMkdir no
 in flight; initializing
npm verb cache add spec cordova
npm verb addNamed "latest" is being treated as a dist-tag for cordova
npm info addNameTag [ 'cordova', 'latest' ]
npm verb addNameTag registry:http://registry.npmjs.org/cordova not in flight; f
tching
npm verb get http://registry.npmjs.org/cordova not expired, no request
npm verb addNamed "6.0.0" is a plain semver version for cordova
npm verb afterAdd C:\Users\Manish\AppData\Roaming\npm-cache\cordova\6.0.0\packa
e\package.json not in flight; writing
npm verb correctMkdir C:\Users\Manish\AppData\Roaming\npm-cache correctMkdir no
 in flight; initializing
npm verb afterAdd C:\Users\Manish\AppData\Roaming\npm-cache\cordova\6.0.0\packa
e\package.json written
npm verb request uri http://registry.npmjs.org/ansi
npm verb request no auth needed
npm info attempt registry request try #1 at 4:11:55 PM
npm verb etag "1AT5UJ80MK2VK1QM4MWWIBZ43"
npm http request GET http://registry.npmjs.org/ansi
npm verb request uri http://registry.npmjs.org/cordova-lib
npm verb request no auth needed
npm info attempt registry request try #1 at 4:11:55 PM
npm verb etag "9GKNWAQPV4K0X3R8NWG6KUZ6V"
npm http request GET http://registry.npmjs.org/cordova-lib
npm verb request uri http://registry.npmjs.org/nopt
npm verb request no auth needed
npm info attempt registry request try #1 at 4:11:55 PM
npm verb etag "EOZTX9OIF152XUTZOK5DSHSTH"
npm http request GET http://registry.npmjs.org/nopt
npm verb request uri http://registry.npmjs.org/q
npm verb request no auth needed
npm info attempt registry request try #1 at 4:11:55 PM
npm verb etag "51R0MQHM5CBV9OGE6AARQI25"
npm http request GET http://registry.npmjs.org/q
npm verb request uri http://registry.npmjs.org/underscore
npm verb request no auth needed
npm info attempt registry request try #1 at 4:11:55 PM
npm verb etag "1ZIB8RAT6MHF5OKTID157K0AV"
npm http request GET http://registry.npmjs.org/underscore
npm verb request uri http://registry.npmjs.org/update-notifier
npm verb request no auth needed
npm info attempt registry request try #1 at 4:11:55 PM
npm verb etag "CWCZEVSXDDOKGZJJ4R86ZCYNL"
npm http request GET http://registry.npmjs.org/update-notifier
npm http 304 http://registry.npmjs.org/ansi
npm verb headers { date: 'Sun, 21 Feb 2016 10:42:01 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   'cache-control': 'max-age=300',
npm verb headers   etag: '"1AT5UJ80MK2VK1QM4MWWIBZ43"',
npm verb headers   age: '49',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-sin6925-SIN',
npm verb headers   'x-cache': 'HIT',
npm verb headers   'x-cache-hits': '1',
npm verb headers   'x-timer': 'S1456051321.063109,VS0,VE0',
npm verb headers   vary: 'Accept' }
npm verb etag http://registry.npmjs.org/ansi from cache
npm verb get saving ansi to C:\Users\Manish\AppData\Roaming\npm-cache\registry.
pmjs.org\ansi\.cache.json
npm verb correctMkdir C:\Users\Manish\AppData\Roaming\npm-cache correctMkdir no
 in flight; initializing
npm verb cache add spec ansi@^0.3.0
npm verb addNamed ">=0.3.0 <0.4.0" is a valid semver range for ansi
npm verb addNameRange registry:http://registry.npmjs.org/ansi not in flight; fe
ching
npm verb get http://registry.npmjs.org/ansi not expired, no request
npm verb addNamed "0.3.1" is a plain semver version for ansi
npm verb afterAdd C:\Users\Manish\AppData\Roaming\npm-cache\ansi\0.3.1\package\
ackage.json not in flight; writing
npm verb correctMkdir C:\Users\Manish\AppData\Roaming\npm-cache correctMkdir no
 in flight; initializing
npm verb afterAdd C:\Users\Manish\AppData\Roaming\npm-cache\ansi\0.3.1\package\
ackage.json written
npm http 304 http://registry.npmjs.org/underscore
npm verb headers { date: 'Sun, 21 Feb 2016 10:42:01 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   'cache-control': 'max-age=300',
npm verb headers   etag: '"1ZIB8RAT6MHF5OKTID157K0AV"',
npm verb headers   age: '207',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-sin6922-SIN',
npm verb headers   'x-cache': 'HIT',
npm verb headers   'x-cache-hits': '2',
npm verb headers   'x-timer': 'S1456051321.554941,VS0,VE0',
npm verb headers   vary: 'Accept' }
npm verb etag http://registry.npmjs.org/underscore from cache
npm verb get saving underscore to C:\Users\Manish\AppData\Roaming\npm-cache\reg
stry.npmjs.org\underscore\.cache.json
npm verb correctMkdir C:\Users\Manish\AppData\Roaming\npm-cache correctMkdir no
 in flight; initializing
npm http 304 http://registry.npmjs.org/q
npm verb headers { date: 'Sun, 21 Feb 2016 10:42:01 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   'cache-control': 'max-age=300',
npm verb headers   etag: '"51R0MQHM5CBV9OGE6AARQI25"',
npm verb headers   age: '72',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-sin6925-SIN',
npm verb headers   'x-cache': 'HIT',
npm verb headers   'x-cache-hits': '3',
npm verb headers   'x-timer': 'S1456051321.557043,VS0,VE0',
npm verb headers   vary: 'Accept' }
npm verb etag http://registry.npmjs.org/q from cache
npm verb get saving q to C:\Users\Manish\AppData\Roaming\npm-cache\registry.npm
s.org\q\.cache.json
npm verb correctMkdir C:\Users\Manish\AppData\Roaming\npm-cache correctMkdir no
 in flight; initializing
npm http 304 http://registry.npmjs.org/nopt
npm verb headers { date: 'Sun, 21 Feb 2016 10:42:01 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   'cache-control': 'max-age=300',
npm verb headers   etag: '"EOZTX9OIF152XUTZOK5DSHSTH"',
npm verb headers   age: '288',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-sin6920-SIN',
npm verb headers   'x-cache': 'HIT',
npm verb headers   'x-cache-hits': '6',
npm verb headers   'x-timer': 'S1456051321.613762,VS0,VE0',
npm verb headers   vary: 'Accept' }
npm verb etag http://registry.npmjs.org/nopt from cache
npm verb get saving nopt to C:\Users\Manish\AppData\Roaming\npm-cache\registry.
pmjs.org\nopt\.cache.json
npm verb correctMkdir C:\Users\Manish\AppData\Roaming\npm-cache correctMkdir no
 in flight; initializing
npm http 304 http://registry.npmjs.org/update-notifier
npm verb headers { date: 'Sun, 21 Feb 2016 10:42:01 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   'cache-control': 'max-age=300',
npm verb headers   etag: '"CWCZEVSXDDOKGZJJ4R86ZCYNL"',
npm verb headers   age: '80',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-sin6921-SIN',
npm verb headers   'x-cache': 'HIT',
npm verb headers   'x-cache-hits': '1',
npm verb headers   'x-timer': 'S1456051321.612291,VS0,VE6',
npm verb headers   vary: 'Accept' }
npm verb etag http://registry.npmjs.org/update-notifier from cache
npm verb get saving update-notifier to C:\Users\Manish\AppData\Roaming\npm-cach
\registry.npmjs.org\update-notifier\.cache.json
npm verb correctMkdir C:\Users\Manish\AppData\Roaming\npm-cache correctMkdir no
 in flight; initializing
npm verb cache add spec underscore@1.7.0
npm verb addNamed "1.7.0" is a plain semver version for underscore
npm verb addNameVersion registry:http://registry.npmjs.org/underscore not in fl
ght; fetching
npm verb cache add spec nopt@3.0.1
npm verb addNamed "3.0.1" is a plain semver version for nopt
npm verb addNameVersion registry:http://registry.npmjs.org/nopt not in flight;
etching
npm verb cache add spec update-notifier@^0.5.0
npm verb addNamed ">=0.5.0 <0.6.0" is a valid semver range for update-notifier
npm verb addNameRange registry:http://registry.npmjs.org/update-notifier not in
flight; fetching
npm verb cache add spec q@1.0.1
npm verb addNamed "1.0.1" is a plain semver version for q
npm verb addNameVersion registry:http://registry.npmjs.org/q not in flight; fet
hing
npm verb get http://registry.npmjs.org/underscore not expired, no request
npm verb get http://registry.npmjs.org/nopt not expired, no request
npm verb get http://registry.npmjs.org/update-notifier not expired, no request
npm verb addNamed "0.5.0" is a plain semver version for update-notifier
npm verb get http://registry.npmjs.org/q not expired, no request
npm verb afterAdd C:\Users\Manish\AppData\Roaming\npm-cache\underscore\1.7.0\pa
kage\package.json not in flight; writing
npm verb correctMkdir C:\Users\Manish\AppData\Roaming\npm-cache correctMkdir no
 in flight; initializing
npm verb afterAdd C:\Users\Manish\AppData\Roaming\npm-cache\nopt\3.0.1\package\
ackage.json not in flight; writing
npm verb correctMkdir C:\Users\Manish\AppData\Roaming\npm-cache correctMkdir no
 in flight; initializing
npm verb afterAdd C:\Users\Manish\AppData\Roaming\npm-cache\underscore\1.7.0\pa
kage\package.json written
npm verb afterAdd C:\Users\Manish\AppData\Roaming\npm-cache\update-notifier\0.5
0\package\package.json not in flight; writing
npm verb correctMkdir C:\Users\Manish\AppData\Roaming\npm-cache correctMkdir no
 in flight; initializing
npm verb afterAdd C:\Users\Manish\AppData\Roaming\npm-cache\nopt\3.0.1\package\
ackage.json written
npm verb afterAdd C:\Users\Manish\AppData\Roaming\npm-cache\q\1.0.1\package\pac
age.json not in flight; writing
npm verb correctMkdir C:\Users\Manish\AppData\Roaming\npm-cache correctMkdir no
 in flight; initializing
npm verb afterAdd C:\Users\Manish\AppData\Roaming\npm-cache\update-notifier\0.5
0\package\package.json written
npm verb afterAdd C:\Users\Manish\AppData\Roaming\npm-cache\q\1.0.1\package\pac
age.json written
npm http 304 http://registry.npmjs.org/cordova-lib
npm verb headers { date: 'Sun, 21 Feb 2016 10:42:02 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   'cache-control': 'max-age=300',
npm verb headers   etag: '"9GKNWAQPV4K0X3R8NWG6KUZ6V"',
npm verb headers   age: '166',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-sin6927-SIN',
npm verb headers   'x-cache': 'HIT',
npm verb headers   'x-cache-hits': '1',
npm verb headers   'x-timer': 'S1456051322.647245,VS0,VE0',
npm verb headers   vary: 'Accept' }
npm verb etag http://registry.npmjs.org/cordova-lib from cache
npm verb get saving cordova-lib to C:\Users\Manish\AppData\Roaming\npm-cache\re
istry.npmjs.org\cordova-lib\.cache.json
npm verb correctMkdir C:\Users\Manish\AppData\Roaming\npm-cache correctMkdir no
 in flight; initializing
npm verb cache add spec cordova-lib@6.0.0
npm verb addNamed "6.0.0" is a plain semver version for cordova-lib
npm verb addNameVersion registry:http://registry.npmjs.org/cordova-lib not in f
ight; fetching
npm verb get http://registry.npmjs.org/cordova-lib not expired, no request
npm verb afterAdd C:\Users\Manish\AppData\Roaming\npm-cache\cordova-lib\6.0.0\p
ckage\package.json not in flight; writing
npm verb correctMkdir C:\Users\Manish\AppData\Roaming\npm-cache correctMkdir no
 in flight; initializing
npm verb afterAdd C:\Users\Manish\AppData\Roaming\npm-cache\cordova-lib\6.0.0\p
ckage\package.json written
npm verb correctMkdir C:\Users\Manish\AppData\Roaming\npm-cache correctMkdir no
 in flight; initializing
npm verb addBundled extract C:\Users\Manish\AppData\Roaming\npm-cache\cordova-l
b\6.0.0\package.tgz
npm verb tar unpack C:\Users\Manish\AppData\Roaming\npm-cache\cordova-lib\6.0.0
package.tgz
npm verb tar unpacking to C:\Users\Manish\AppData\Local\Temp\npm-5508-807535ba\
npack-890b2098
npm verb gentlyRm don't care about contents; nuking C:\Users\Manish\AppData\Loc
l\Temp\npm-5508-807535ba\unpack-890b2098
npm verb cache add spec nopt@^3.0.6
loadDep:nopt              \ |############-------------------------------------|

**Comment by KenanY** [comment]
@arpitsharma923 I do not see an error in the output you have posted.

**Comment by arpitsharma923** [comment]
@KenanY  Thanks you for your response, actually it not show any error and also not installed cordova so i was stuck but now my issue is solved when I install earlier version of nodejs, then cordova successfully installed.

**Comment by othiym23** [comment]
Closing as resolved.
