### ISSUE TITLE
Global pre* and post* scripts

### ISSUE THREAD

**Issue by aristidesfl** [npm/npm#11635]
Is there a way to define a script which is run before/after any other script? A global `pre/post` script?

**Comment by levithomason** [comment]
I need this all the time.

***

### Proposal 1: Simple pre/post global
It would be great to have a simple global `pre` and `post` script that ran before/after any script.

### Proposal 2: Globbing pre/post
Say I have 3 build targets for a library `build:es`, `build:commonjs`, and `build:amd`.  If I need to run a single script before all builds, I have to:

```json
{
  "prebuild:es": "...",
  "prebuild:commonjs": "...",
  "prebuild:amd": "..."
}
```

Whereas this could simply be:
```json
{
  "prebuild:*": "..."
}
```

This could also solve the global pre/post cases elegantly:
```json
{
  "pre*": "..."
}
```
