### ISSUE TITLE
`npm faq` runs `npm help-search faq`

### ISSUE THREAD

**Issue by seldo** [npm/npm#11637]
As an invalid command, it should just fail.

It seems it still [has a file](https://github.com/npm/npm/blob/3440db7f200e81bb9cf930eb4c32aa5fc8359e7e/lib/faq.js) and so turns up in CLI help etc.

**Comment by KenanY** [comment]
Removed in https://github.com/npm/npm/pull/12143 so I believe this is resolved now.
