### ISSUE TITLE
Error installing ember-cli

### ISSUE THREAD

**Issue by mcshakes** [npm/npm#11630]
While following an Ember tutorial, I am asked to run this:

$ sudo npm install -g ember-cli

and get the following errors:

```
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/node/5.5.0/bin/node" "/usr/local/bin/npm" "install" "-g" "ember-cli"
npm ERR! node v5.5.0
npm ERR! npm  v3.5.3

npm ERR! No compatible version found: fs-extra@0.26.2
npm ERR! Valid install targets:
npm ERR! 0.20.1, 0.20.0, 0.19.0, 0.18.4, 0.18.3, 0.18.2, 0.18.1, 0.18.0, 0.17.0, 0.16.5, 0.16.4, 0.16.3, 0.16.2, 0.16.1, 0.16.0, 0.15.0, 0.14.0, 0.13.0, 0.12.0, 0.11.1, 0.11.0, 0.10.0, 0.9.1, 0.9.0, 0.8.1, 0.8.0, 0.7.1, 0.7.0, 0.6.4, 0.6.3, 0.6.2, 0.6.1, 0.6.0, 0.5.0, 0.4.0, 0.3.2, 0.3.1, 0.3.0, 0.2.1, 0.2.0, 0.1.3, 0.1.2, 0.1.1, 0.1.0, 0.0.11, 0.0.4, 0.0.3, 0.0.1
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
 ```

Here is the log file they ask me to attach:

npm ERR!     /Users/edmac/Turing/Module_5/bostonember/npm-debug.log

Is this an npm issue specifically? When I run $ ember --version, it says there is "No such file or directory"

**Comment by KenanY** [comment]
@mcshakes Is this still an issue for you?

**Comment by mcshakes** [comment]
Unfortunately, no. And I can't remember what I did to fix the problem. I want to say I removed and reinstalled everything (npm, ember etc.) Now I get:

```
$ ember --version
ember-cli: 2.5.1
node: 5.7.0
os: darwin x64
```
