### ISSUE TITLE
Error while installing phonegap via cmd

### ISSUE THREAD

**Issue by hustlerism** [npm/npm#11642]
npm install -g phonegap@latest
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\
node_modules\npm\bin\npm-cli.js" "install" "-g" "phonegap@latest"
npm ERR! node v5.5.0
npm ERR! npm  v3.3.12
npm ERR! code DEPTH_ZERO_SELF_SIGNED_CERT

npm ERR! self signed certificate
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     C:\windows\system32\npm-debug.log

**Comment by busches** [comment]
Is still occurring in the latest npm and node?
