### ISSUE TITLE
Could not insatall sqlite3

### ISSUE THREAD

**Issue by kreifeurm** [npm/npm#11649]
I tried many time to install sqlite3 (npm install sqlite3) without success.
I am using 
 - Xindows 7 64bits
 - node v5.3.0 (on windows)
 - npm v3.7.5
 - node-gyp v3.3.0
-  node-pre-gyp v0.6.21

it sees the install is looking dor node47. I do not understand why the folder 'E:\\**EnvLearning**' is used for installation. This folder  is the my working folder.

Here is the error: 
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mkreifeu\\AppData\\Roaming\\npm\\node_modules\\npm\\n
ode_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=**E:\\**EnvLearning**\\node_modules\\sqli
te3**\\lib\\binding\\node-v47-win32-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=E:\\EnvLearning\\n
ode_modules\\sqlite3\\lib\\binding\\node-v47-win32-x64"
gyp ERR! cwd E:\EnvLearning\node_modules\sqlite3
gyp ERR! node -v v5.3.0
gyp ERR! node-gyp -v v3.3.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=E:\EnvLearning\nod
e_modules\sqlite3\lib\binding\node-v47-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=E:\EnvLearni
ng\node_modules\sqlite3\lib\binding\node-v47-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (E:\EnvLearning\node_modules\sqlite3\node_modules\node-pre-gyp\l
ib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\EnvLearning\\node_modules\\sqlite3\\node_modules\\n
ode-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd E:\EnvLearning\node_modules\sqlite3
node-pre-gyp ERR! node -v v5.3.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.14
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=E:\EnvLearning\node_modules\sqlite3\lib\binding\n
ode-v47-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=E:\EnvLearning\node_modules\sqlite3\lib\bin
ding\node-v47-win32-x64' (1)
npm WARN enoent ENOENT: no such file or directory, open 'E:\EnvLearning\package.json'
npm WARN EnvLearning No description
npm WARN EnvLearning No repository field.
npm WARN EnvLearning No README data
npm WARN EnvLearning No license field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mkreifeu\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\
\npm-cli.js" "install" "sqlite3"
npm ERR! node v5.3.0
npm ERR! npm  v3.7.5
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@3.1.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@3.1.1 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sqlite3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\EnvLearning\npm-debug.log

**Comment by KenanY** [comment]
@kreifeurm Are you still seeing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
