### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by saower** [npm/npm#11640]
install Cloud9, but error !  thanks
 
info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'instal',
1 verbose cli   'cloud9' ]
2 info using npm@1.4.3
3 info using node@v0.10.26
4 error Error: Invalid version: "0.6"
4 error     at Object.module.exports.fixVersionField (/usr/local/lib/node_modules/npm/node_modules/read-pac$
4 error     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-packag$
4 error     at Array.forEach (native)
4 error     at normalize (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/norma$
4 error     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:328:33)
4 error     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:126:33)
4 error     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:252:40
4 error     at fs.js:266:14
4 error     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:105:5
4 error     at Object.oncomplete (fs.js:107:15)
5 error If you need help, you may report this *entire* log,
5 error including the npm and node versions, at:
5 error     <http://github.com/npm/npm/issues>
6 error System Linux 2.6.32-431.29.2.el6.x86_64
7 error command "/usr/local/bin/node" "/usr/local/bin/npm" "instal" "cloud9"
8 error cwd /home/cloud9-master/bin
9 error node -v v0.10.26
10 error npm -v 1.4.3
11 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@saowerchen In your `package.json`, is your `"version"` defined as `"0.6"`? That's not valid [SemVer](http://semver.org/spec/v2.0.0.html), which is a requirement (as documented [here](https://docs.npmjs.com/files/package.json#version)). Also, do note that `npm@1` is quite old at this point, so please consider [updating](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm).

**Comment by saowerchen** [comment]
@KenanY  thanks

**Comment by othiym23** [comment]
Closing as resolved.
