### ISSUE TITLE
Start script wont work + karma not working in npm

### ISSUE THREAD

**Issue by Innerfear** [npm/npm#11648]
I'm working on a internship together with a collegue from school, we started our project together. Last week I had a BSOD while working on the project and after that I'm not able to run the project anymore. I even reformatted my entire laptop for this. When I try to do "npm start" I get the following error message.

0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli   'C:\Users\[username]\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'start',
1 verbose cli   '-ddd' ]
2 info using npm@2.14.20
3 info using node@v4.3.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart angular_webpack@1.0.0
6 info start angular_webpack@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info angular_webpack@1.0.0 Failed to exec start script
9 verbose stack Error: angular_webpack@1.0.0 start: `webpack-dev-server --content -base js -p`
9 verbose stack Exit status 3221225501
9 verbose stack     at EventEmitter.<anonymous> (C:\Users[username]\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Users[username]\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:821:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid angular_webpack@1.0.0
11 verbose cwd C:\Development\Projects\js-submit-manager\Webpack_frontEnd
12 error Windows_NT 6.1.7600
13 error argv "C:\Program Files\nodejs\node.exe" "C:\Users\[username]\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "start" "-ddd"
14 error node v4.3.1
15 error npm  v2.14.20
16 error code ELIFECYCLE
17 error angular_webpack@1.0.0 start: `webpack-dev-server --content -base js -p`
17 error Exit status 3221225501
18 error Failed at the angular_webpack@1.0.0 start script 'webpack-dev-server --content -base js -p'.
18 error This is most likely a problem with the angular_webpack package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     webpack-dev-server --content -base js -p
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs angular_webpack
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls angular_webpack
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

I'm also working with karma, well I'm supposed to work with karma. Before the BSOD karma worked fine, now if I try to run "karma init karma.conf.js" I just get a blank line and my cmd window goes to the next line, ready for the next command.

I've installed webpack-dev-server and karma globally, I installed them local too to test, but that didn't help. Anyone who can help me out?

**Comment by herberton** [comment]
I have the same problema... Someone help us?

**Comment by volash86** [comment]
Me too! I work at Win7,  and the same code at Mac / Centos is OK! Why?
