### ISSUE TITLE
npm install failure

### ISSUE THREAD

**Issue by guoyinyue** [npm/npm#11655]
I have encountered one small problem when i run line npm install
`npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4

npm ERR! shasum check failed for /var/folders/55/rm5lc2q164s2rbdcx38hhn6c0000gn/T/npm-1779-b1640a46/registry.npm.taobao.org/react-native/download/react-native-0.20.0.tgz
npm ERR! Expected: a8ba5f1c2cf3a2d41eb655192a18b0b058cd3e62
npm ERR! Actual:   158d03ff52eb85270a179fe546e55b2a3d3d1998
npm ERR! From:     https://registry.npm.taobao.org/react-native/download/react-native-0.20.0.tgz
npm ERR! 
`
i dont know why the error show?

**Comment by KenanY** [comment]
@guoyinyue Does this also happen if you use the default registry (`https://registry.npmjs.org`)?

**Comment by KenanY** [comment]
@guoyinyue Are you still experiencing this issue? Have you tried my suggestion?

**Comment by guoyinyue** [comment]
@KenanY sorry to reply late .yes,the problem has been solved for a long time,and i remember that probably it should be the  mirror image of the address which caused the bug,thank u for your answer.
