### ISSUE TITLE
Frequent registry problems lately

### ISSUE THREAD

**Issue by adambuczynski** [npm/npm#11651]
Lately, I've been having more and more problems with installing npm packages, to the extent that most of my `npm install` commands for projects fail, and I have to re-do them at least once.

Errors vary from the occasional

```
npm ERR! registry error parsing json
npm ERR! registry error parsing json
```

which I've seen be spit out when the response is not coming back in a timely manner, to the actual failure of random packages

```
npm ERR! failed to fetch from registry: https://registry.npmjs.org/bluebird
```

It's never the same package, which leads me to speculate that perhaps the servers of npm are getting a bit overloaded.

Note that this happens to me from home, from work, wherever I am, so it's unlikely that it's my own internet connection that suddenly is failing wherever I go.

Just thought I'd report it, as it has been happening frequently lately.

**Comment by empierre** [comment]
same here:

npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! publish Failed PUT 503
npm ERR! Linux 4.2.0-27-lowlatency
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "publish"
npm ERR! node v5.6.0
npm ERR! npm  v3.7.3

npm ERR! Unexpected token <

**Comment by seldo** [comment]
There is always a smattering of timeouts across the whole internet; our stats do not show any significant increase in the number, with the exception that on the 23rd our CDN had an incident that caused a spike in 503s, limited primarily to the eastern US (so it shouldn't have affected either of you if your locations are accurate).

**Comment by adambuczynski** [comment]
Yesterday and today it was fine again. Maybe just a local network disruption in our areas/countries then.

**Comment by frederickfogerty** [comment]
I'm getting this as well - I'm in NZ (so I guess I'm being served by Sydney), and up until a week ago I've had no issues, but ever since then my npm installs have failed probably about 95% of the time, I have to keep cycling between http and https to get it to work.

**Comment by frederickfogerty** [comment]
I pretty much just do this to try get npm to install `npm i || npm i || npm i || npm i || npm i || npm i || npm i`

**Comment by adambuczynski** [comment]
Nz here as well by the way
