### ISSUE TITLE
I keep getting these errors on my npm install of Bootstrap CMS

### ISSUE THREAD

**Issue by wcousin** [npm/npm#11654]
Every time I try to install Bootstrap CMS (https://github.com/BootstrapCMS/CMS) i get this error.  Its when I try to run npm install in the bootstrap-cms file.  Terminal tells me to 'install apt-get install npm' and then after that I run 'npm install' and I get this error: (sorry it's so long)

`npm ERR! Error: ENOENT, lstat '/var/www/bootstrap-cms/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/node-sass/node_modules/node-gyp/gyp/pylib/gyp/generator/msvs.py'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-57-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /var/www/bootstrap-cms
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /var/www/bootstrap-cms/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/node-sass/node_modules/node-gyp/gyp/pylib/gyp/generator/msvs.py
npm ERR! fstream_path /var/www/bootstrap-cms/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/node-sass/node_modules/node-gyp/gyp/pylib/gyp/generator/msvs.py
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! error rolling back Error: ENOTEMPTY, rmdir '/var/www/bootstrap-cms/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/node-sass/node_modules'
npm ERR! error rolling back  node-sass@3.4.2 { [Error: ENOTEMPTY, rmdir '/var/www/bootstrap-cms/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/node-sass/node_modules']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: '/var/www/bootstrap-cms/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/node-sass/node_modules' }
npm ERR! EEXIST, mkdir '/var/www/bootstrap-cms/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/node-sass/node_modules/cross-spawn/node_modules/cross-spawn-async/node_modules/lru-cache/node_modules/yallist'
File exists: /var/www/bootstrap-cms/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/node-sass/node_modules/cross-spawn/node_modules/cross-spawn-async/node_modules/lru-cache/node_modules/yallist
Move it away, and try again.

npm ERR! System Linux 3.13.0-57-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /var/www/bootstrap-cms
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /var/www/bootstrap-cms/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/node-sass/node_modules/cross-spawn/node_modules/cross-spawn-async/node_modules/lru-cache/node_modules/yallist
npm ERR! fstream_path /var/www/bootstrap-cms/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/node-sass/node_modules/cross-spawn/node_modules/cross-spawn-async/node_modules/lru-cache/node_modules/yallist/CONTRIBUTING.md
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code EEXIST
npm ERR! errno 47
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:171:23
npm ERR! fstream_stack /usr/lib/nodejs/mkdirp/index.js:37:53
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! error rolling back Error: ENOTEMPTY, rmdir '/var/www/bootstrap-cms/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/node-sass/node_modules/cross-spawn/node_modules/cross-spawn-async/node_modules/lru-cache/node_modules/pseudomap'
npm ERR! error rolling back  gulp-sass@2.2.0 { [Error: ENOTEMPTY, rmdir '/var/www/bootstrap-cms/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/node-sass/node_modules/cross-spawn/node_modules/cross-spawn-async/node_modules/lru-cache/node_modules/pseudomap']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: '/var/www/bootstrap-cms/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/node-sass/node_modules/cross-spawn/node_modules/cross-spawn-async/node_modules/lru-cache/node_modules/pseudomap' }
npm ERR! error rolling back Error: ENOTEMPTY, rmdir '/var/www/bootstrap-cms/node_modules/laravel-elixir/node_modules/gulp-less/node_modules/less/test/less'
npm ERR! error rolling back  laravel-elixir@3.1.2 { [Error: ENOTEMPTY, rmdir '/var/www/bootstrap-cms/node_modules/laravel-elixir/node_modules/gulp-less/node_modules/less/test/less']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: '/var/www/bootstrap-cms/node_modules/laravel-elixir/node_modules/gulp-less/node_modules/less/test/less' }
npm ERR! weird error 127
npm ERR! tar pack Error reading /root/tmp/npm-10285-0NCYXSnM/1456276335432-0.6230673759710044/package
npm ERR! addLocalDirectory Could not pack "/root/tmp/npm-10285-0NCYXSnM/1456276335432-0.6230673759710044/package" to "/root/.npm/when/3.7.7/package.tgz"
npm ERR! EEXIST, mkdir '/var/www/bootstrap-cms/node_modules/laravel-elixir/node_modules/gulp-less/node_modules/less/test/less/errors'
File exists: /var/www/bootstrap-cms/node_modules/laravel-elixir/node_modules/gulp-less/node_modules/less/test/less/errors
Move it away, and try again.

npm ERR! System Linux 3.13.0-57-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /var/www/bootstrap-cms
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /var/www/bootstrap-cms/node_modules/laravel-elixir/node_modules/gulp-less/node_modules/less/test/less/errors
npm ERR! fstream_path /var/www/bootstrap-cms/node_modules/laravel-elixir/node_modules/gulp-less/node_modules/less/test/less/errors/bad-variable-declaration1.txt
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code EEXIST
npm ERR! errno 47
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:171:23
npm ERR! fstream_stack /usr/lib/nodejs/mkdirp/index.js:37:53
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm WARN engine hawk@3.1.3: wanted: {"node":">=0.10.32"} (current: {"node":"v0.10.25","npm":"1.3.10"})

npm ERR! Error: ENOENT, lstat '/var/www/bootstrap-cms/node_modules/laravel-elixir/node_modules/gulp-babel/node_modules/babel-core/browser.min.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-57-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /var/www/bootstrap-cms
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /var/www/bootstrap-cms/node_modules/laravel-elixir/node_modules/gulp-babel/node_modules/babel-core/browser.min.js
npm ERR! fstream_path /var/www/bootstrap-cms/node_modules/laravel-elixir/node_modules/gulp-babel/node_modules/babel-core/browser.min.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)

npm ERR! Error: ENOENT, lstat '/var/www/bootstrap-cms/node_modules/laravel-elixir/node_modules/gulp-phpspec/node_modules/expect/node_modules/is-equal/html/corejs.html'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-57-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /var/www/bootstrap-cms
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /var/www/bootstrap-cms/node_modules/laravel-elixir/node_modules/gulp-phpspec/node_modules/expect/node_modules/is-equal/html/corejs.html
npm ERR! fstream_path /var/www/bootstrap-cms/node_modules/laravel-elixir/node_modules/gulp-phpspec/node_modules/expect/node_modules/is-equal/html/corejs.html
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)`

**Comment by KenanY** [comment]
@wcousin `npm@1.3` is so old that it is no longer supported. Please try [updating](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm).

**Comment by KenanY** [comment]
@wcousin Are you still having this issue after updating to the latest, stable version of `npm`?

**Comment by KenanY** [comment]
Closing as abandoned.
