### ISSUE TITLE
when execute command "npm install" . this error occur

### ISSUE THREAD

**Issue by mueedahmed1** [npm/npm#11650]
![npm](https://cloud.githubusercontent.com/assets/12622228/13261777/73f907e6-da83-11e5-9189-2c8679e5eefe.png)

**Comment by KenanY** [comment]
@mueedahmed1 Do you have Python 2 installed? You need it to build native addons with `node-gyp`. This is documented in [`node-gyp`'s readme file](https://github.com/nodejs/node-gyp#installation).

**Comment by mueedahmed1** [comment]
No, I haven't installed python ..

**Comment by KenanY** [comment]
@mueedahmed1 Like I said, you need to have Python installed if you are going to be building native addons. Are you still seeing this issue?

**Comment by KenanY** [comment]
No response; closing as abandoned.
