### ISSUE TITLE
Help!Can't install hexo ! And run hexo server failure!

### ISSUE THREAD

**Issue by vbonluk** [npm/npm#11659]
First I run `sudo npm install -d`
then I get this Error:
`npm WARN enoent ENOENT: no such file or directory, open '/Users/Vbon/package.json'
npm WARN Vbon No description
npm WARN Vbon No repository field.
npm WARN Vbon No README data
npm WARN Vbon No license field.
npm info ok`

after that,I run `hexo init` and `hexo server`
I get error:
`{ [Error: Cannot find module './build/Release/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/default/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/Debug/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
ERROR Plugin load failed: hexo-renderer-marked`

I try to find how to fix it.
someone use `npm install hexo --no-optional` can fix.
But not work for me!
I get error:
`npm WARN enoent ENOENT: no such file or directory, open '/Users/Vbon/package.json'
npm WARN Vbon No description
npm WARN Vbon No repository field.
npm WARN Vbon No README data
npm WARN Vbon No license field.
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "hexo" "--no-optional"
npm ERR! node v5.7.0
npm ERR! npm  v3.6.0
npm ERR! path /Users/Vbon/node_modules/hexo
npm ERR! code ENOTEMPTY
npm ERR! errno -66
npm ERR! syscall rename`

please! help me!

**Comment by liamma** [comment]
sudo npm install --unsafe-perm --verbose -g hexo

**Comment by liamma** [comment]
try it.

**Comment by returnyuteng** [comment]
@liamma  Thx for your answer! it works for me!

**Comment by KenanY** [comment]
@vbonluk Are you still seeing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
