### ISSUE TITLE
invalid tar file

### ISSUE THREAD

**Issue by ramandeeprdb** [npm/npm#11665]
npm ERR! tar.unpack untar error C:\Users\PARAM JEET\AppData\Roaming\npm-cache\babel-core\5.8.35\package.tgz
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12

npm ERR! invalid tar file
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\ember\sodashop\npm-debug.log

<https://github.com/npm/npm/issues>

thanks

**Comment by KenanY** [comment]
@ramandeeprdb Can you delete this file?:

```
C:\Users\PARAM JEET\AppData\Roaming\npm-cache\babel-core\5.8.35\package.tgz
```

**Comment by KenanY** [comment]
(or `npm cache clean` might be more appropriate)
