### ISSUE TITLE
help please!

### ISSUE THREAD

**Issue by BloterMediaLab** [npm/npm#11677]
when wordpress calypso install...
show error...

npm ERR! Command failed: git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/pugjs/jade.git /root/.npm/_git-remotes/git-github-com-pugjs-jade-git-29784fd1ec6043397f4b43d45b4ee9e25177b940-dffe59e0
npm ERR! 간략한 저장소로('/root/.npm/_git-remotes/git-github-com-pugjs-jade-git-29784fd1ec6043397f4b43d45b4ee9e25177b940-dffe59e0') 복제합니다...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.131]: errno=?? ?? ??

my linux version Linux 2.6.32-431.23.3.el6.x86_64 with cent os
and node version v5.7.0, npm version v.3.6.0

how to fix it?

**Comment by KenanY** [comment]
@BloterMediaLab This looks like an issue with your internet connection, and the error is coming from `git` not `npm`:

```
npm ERR! fatal: unable to connect to github.com:
```

A possible cause is a proxy or firewall blocking the `git` protocol.

**Comment by KenanY** [comment]
@BloterMediaLab Are you still having this issue?
