### ISSUE TITLE
Can not install gulp on local directory

### ISSUE THREAD

**Issue by renaudMaupoux** [npm/npm#11673]
npm install --save-dev gulp doesn' t work.

[npm-debug.log.zip](https://github.com/npm/npm/files/146100/npm-debug.log.zip)

**Comment by zhougonglai** [comment]
me too:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'install', 'gulp' ]
2 info using npm@3.6.0
3 info using node@v5.7.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData gulp
8 silly fetchNamedPackageData gulp
9 silly mapToRegistry name gulp
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry http://registry.npm.taobao.org/
12 silly mapToRegistry uri http://registry.npm.taobao.org/gulp
13 verbose request uri http://registry.npm.taobao.org/gulp
14 verbose request no auth needed
15 info attempt registry request try #1 at 3:27:02 PM
16 verbose request id e7f3d0a4432dcc22
17 http request GET http://registry.npm.taobao.org/gulp
18 http 200 http://registry.npm.taobao.org/gulp
19 verbose headers { date: 'Thu, 25 Feb 2016 07:27:03 GMT',
19 verbose headers   'content-type': 'application/json; charset=utf-8',
19 verbose headers   'content-length': '123931',
19 verbose headers   connection: 'keep-alive',
19 verbose headers   etag: '"1e41b-4fpuFlvtGDiD1lx1/L2pgg"',
19 verbose headers   'x-readtime': '300' }
20 silly get cb [ 200,
20 silly get   { date: 'Thu, 25 Feb 2016 07:27:03 GMT',
20 silly get     'content-type': 'application/json; charset=utf-8',
20 silly get     'content-length': '123931',
20 silly get     connection: 'keep-alive',
20 silly get     etag: '"1e41b-4fpuFlvtGDiD1lx1/L2pgg"',
20 silly get     'x-readtime': '300' } ]
21 verbose get saving gulp to /Users/dengyang/.npm/registry.npm.taobao.org/gulp/.cache.json
22 verbose correctMkdir /Users/dengyang/.npm correctMkdir not in flight; initializing
23 silly install normalizeTree
24 silly loadCurrentTree Finishing
25 silly loadIdealTree Starting
26 silly install loadIdealTree
27 silly cloneCurrentTree Starting
28 silly install cloneCurrentTreeToIdealTree
29 silly cloneCurrentTree Finishing
30 silly loadShrinkwrap Starting
31 silly install loadShrinkwrap
32 silly loadShrinkwrap Finishing
33 silly loadAllDepsIntoIdealTree Starting
34 silly install loadAllDepsIntoIdealTree
35 silly rollbackFailedOptional Starting
36 silly rollbackFailedOptional Finishing
37 silly runTopLevelLifecycles Starting
38 silly runTopLevelLifecycles Finishing
39 silly install printInstalled
40 verbose stack Error: Refusing to install gulp as a dependency of itself
40 verbose stack     at checkSelf (/usr/local/lib/node_modules/npm/lib/install/validate-args.js:53:14)
40 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
40 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
40 verbose stack     at chain (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
40 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/validate-args.js:16:5
40 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
40 verbose stack     at Array.forEach (native)
40 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
40 verbose stack     at Array.forEach (native)
40 verbose stack     at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
41 verbose cwd /Users/dengyang/WebstormProjects/gulp
42 error Darwin 15.3.0
43 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "gulp"
44 error node v5.7.0
45 error npm  v3.6.0
46 error code ENOSELF
47 error Refusing to install gulp as a dependency of itself
48 error If you need help, you may report this error at:
48 error     <https://github.com/npm/npm/issues>
49 verbose exit [ 1, true ]

**Comment by renaudMaupoux** [comment]
npm-debug told me that threre was problem of permission so
I  resolved my bug by changing chmod on user/.npm to 777.
I think it different problem for @zhougonglai.  It says 'Refusing to install gulp as a dependency of itself'
Have you change directory first like cd Sites/... and then trying :  npm install gulp --save-dev  ?

**Comment by KenanY** [comment]
Closing since the original issue has been resolved. If you are still facing your separate issue, @zhougonglai, then feel free to open a new issue since it appears to be unrelated to that of @renaudMaupoux.
