### ISSUE TITLE
Additional Depreciation Information

### ISSUE THREAD

**Issue by patrickhousley** [npm/npm#11672]
Is there an easy way to get package in the package.json that is requiring a deprecated package? This may be useful for other warnings and errors. However, at the very least it would be nice to be able to know at a glance which package my project is depending on that is requiring old packages. I can certainly search through the dependency tree printed after install finishes but this can be cumbersome in large applications with many dependencies.

**Comment by KenanY** [comment]
Duplicate of https://github.com/npm/npm/issues/10438, perhaps. In the meantime you can do `npm ls pkg` to see all packages in the dependency tree which depend on `pkg`.

**Comment by patrickhousley** [comment]
Thanks. Guess I didn't use the write search params :)
