### ISSUE TITLE
Can't install ar-drone, ERR! Refusing to install ar-drone as dependency of itself

### ISSUE THREAD

**Issue by Caption101** [npm/npm#11675]
When I try to execute 'install ar-drone' i get a large list of errors.
Your environment has been set up for using Node.js 5.7.0 (x64) and npm.

C:\Users\NAME>npm install ar-drone
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "ar-drone"
npm ERR! node v5.7.0
npm ERR! npm  v3.6.0
npm ERR! code ENOSELF

npm ERR! Refusing to install ar-drone as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\NAME\npm-debug.log

C:\Users\NAME>

Am i doing something wrong? I just really need help. I have attached the npm-debug.log 
if that helps.
I have tried several times over the past few days.
[npm-debug.txt](https://github.com/npm/npm/files/146181/npm-debug.txt)

Thanks Caption101

**Comment by KenanY** [comment]
@Caption101 Hmm, does `C:\Users\NAME\package,json` exist?

**Comment by Caption101** [comment]
Yeah, C:\Users\NAME\package,json does exist. I have made sure everything I need is installed to the proper directory. What else could it be.

**Comment by KenanY** [comment]
@Caption101 Is `"name": "ar-drone"` in `C:\Users\NAME\package.json`?

**Comment by semanser** [comment]
@KenanY solved the same error today. Thanks! :+1:

**Comment by Caption101** [comment]
Yeah "name": "ar-drone" is in C:\Users\NAME\package.json

**Comment by Caption101** [comment]
Thanks, I solved it. I had to change "name" to the name of the file.
