### ISSUE TITLE
help!!! can't start npm

### ISSUE THREAD

**Issue by MAJDA55** [npm/npm#11671]
```
npm ERR! Windows_NT 6.1.7600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
npm ERR! node v5.7.0
npm ERR! npm  v3.6.0

npm ERR! missing script: start
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\nodeapps\testapps\npm-debug.log
```

**Comment by KenanY** [comment]
@MAJDA55 Hmm...

```
npm ERR! missing script: start
```

Do you have a `"start"` script defined in your `package.json`? Without one, `npm` will have no clue what to do, and will throw that error. This is documented [here](https://docs.npmjs.com/cli/run-script) and [here](https://docs.npmjs.com/misc/scripts).

**Comment by MAJDA55** [comment]
this is my package.json 
{
  "name": "testapps",
  
"version": "0.0.1",

  "description": "this is sample app",

"repository":{
"type":"git",
"url":"http://github.com/saan1984/testapps.git"},
  "main": "app.js",

  "dependencies": {
  
  "jade": "*",
    
"stylus": "*"
  },

  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },

  "author": "brad traversy",
 
 "license": "GPL-3.0",


  
"devDependencies": {
    "electron-prebuilt": "^0.36.8"
  }

}

what can i do please ???

**Comment by helionagamachi** [comment]
@MAJDA55 you can simply create a server.js file as explained on https://docs.npmjs.com/cli/start 
or change your package.json file to have a "start" script on the "scripts" object, it is also explained in the previous link and the links mentioned by @KenanY

**Comment by MAJDA55** [comment]
mejda@mejda-PC MINGW32 /c/nodeapps/testapps
$ npm run start

> testapps@0.0.1 start C:\nodeapps\testapps
> electron .


and no electron application started  !!! :(

**Comment by KenanY** [comment]
@MAJDA55 I've commented on [the new issue you created](https://github.com/npm/npm/issues/11680#issuecomment-188835052).

**Comment by othiym23** [comment]
Closing as resolved.
