### ISSUE TITLE
help please !!

### ISSUE THREAD

**Issue by MAJDA55** [npm/npm#11680]
mejda@mejda-PC MINGW32 /c/nodeapps/testapps
$ npm run start

testapps@0.0.1 start C:\nodeapps\testapps
electron .
and no electron application started !!! :(

**Comment by KenanY** [comment]
@MAJDA55 This does not look like an issue with `npm` to me. I think you should take this to [StackOverflow](https://stackoverflow.com/questions/tagged/electron) or the [Electron discussion forum](https://discuss.atom.io/c/electron).

**Comment by MAJDA55** [comment]
thank u
