### ISSUE TITLE
Trouble installing package: ENOTEMPTY error when dir doesn't exist

### ISSUE THREAD

**Issue by blair55** [npm/npm#11689]
I'm trying to install yeoman using

```
$ npm install -g yo
```

This is the error I receive:

```
npm ERR! Linux 4.2.0-30-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "yo"
npm ERR! node v4.3.1
npm ERR! npm  v3.7.3
npm ERR! path /usr/lib/node_modules/yo
npm ERR! code ENOTEMPTY
npm ERR! errno -39
npm ERR! syscall rename

npm ERR! ENOTEMPTY: directory not empty, rename '/usr/lib/node_modules/yo' -> '/usr/lib/node_modules/.yo.DELETE'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/nick/npm-debug.log
```

However, I get the following message when I try to `ls` the offending folder:

```
$ ls /usr/lib/node_modules/yo
ls: cannot access /usr/lib/node_modules/yo: No such file or directory
```

**Comment by bryan-snyder** [comment]
I have the same issues with gulp-cssnano

**Comment by cgiffard** [comment]
Also having what appears to be this same problem. It happens with `npm@3.8.8`, the latest version of npm at the time of writing, as well as `npm@3.6.0`.

* Many different modules are triggering the error.
* Permissions seem unrelated — I've done the dreaded `chmod -R 777 ./node_modules` — no dice.
* This appears to be happening with modules installed from git (like the example below) and modules installed from public npm alike.
* It's also unrelated to platform. Happens on both my Ubuntu Linux VM with 3.8.8 and my Mac with 3.6.0.


Installing from git:

```
npm WARN redisClient@1.1.11 No license field.
npm ERR! Linux 4.2.0-34-generic
npm ERR! argv "node" "/home/cgiffard/.nvm/v0.10.43/bin/npm" "install" "logger"
npm ERR! node v0.10.43
npm ERR! npm  v3.8.8
npm ERR! path /mnt/hgfs/autopilot/redisClient/node_modules/.logger.DELETE
npm ERR! code ENOTEMPTY
npm ERR! errno 53

npm ERR! ENOTEMPTY, rename '/mnt/hgfs/autopilot/redisClient/node_modules/.logger.DELETE'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/hgfs/autopilot/redisClient/npm-debug.log
```

Dependency from public npm:
```
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v6.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
logger@0.2.3 /mnt/hgfs/autopilot/logger
├── assertion-error@1.0.1  extraneous
├── coffee-script@1.10.0
├─┬ mocha@2.4.5
│ ├── commander@2.3.0
│ ├─┬ debug@2.2.0
│ │ └── ms@0.7.1
│ ├── diff@1.4.0
│ ├── escape-string-regexp@1.0.2
│ ├─┬ glob@3.2.3
│ │ ├── graceful-fs@2.0.3
│ │ ├── inherits@2.0.1
│ │ └─┬ minimatch@0.2.14
│ │   ├── lru-cache@2.7.3
│ │   └── sigmund@1.0.1
│ ├── growl@1.8.1
│ ├─┬ jade@0.26.3
│ │ ├── commander@0.6.1
│ │ └── mkdirp@0.3.0
│ ├─┬ mkdirp@0.5.1
│ │ └── minimist@0.0.8
│ └── supports-color@1.2.0
├─┬ redis@2.6.0-2
│ ├── double-ended-queue@2.1.0-0
│ ├── redis-commands@1.2.0
│ └── redis-parser@1.3.0
└── type-detect@1.0.0  extraneous

npm WARN logger@0.2.3 No license field.
npm ERR! Linux 4.2.0-34-generic
npm ERR! argv "node" "/home/cgiffard/.nvm/v0.10.43/bin/npm" "install"
npm ERR! node v0.10.43
npm ERR! npm  v3.8.8
npm ERR! path /mnt/hgfs/autopilot/logger/node_modules/.deep-eql.DELETE/node_modules/type-detect
npm ERR! code ENOENT
npm ERR! errno 34

npm ERR! enoent ENOENT, rename '/mnt/hgfs/autopilot/logger/node_modules/.deep-eql.DELETE/node_modules/type-detect'
npm ERR! enoent ENOENT, rename '/mnt/hgfs/autopilot/logger/node_modules/.deep-eql.DELETE/node_modules/type-detect'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/hgfs/autopilot/logger/npm-debug.log
```

In the latter example, `redis`, `type-detect`, and `mocha` were not installed. `coffee-script` was available globally. `assertion-error` and `commander` were installed to the local directory despite being dependencies of globally installed modules. `chai`, which was directly referenced by the package.json, was not installed.

[npm-debug.log](https://files.app.net/hqfk8scSr.log)

**Comment by adamcee** [comment]
I received a similar error with `gulp-ng-config`:
`ENOTEMPTY: directory not empty, rename '<my-project-path>/node_modules/gulp-ng-config' -> '<my-project-path>/node_modules/.gulp-ng-config.DELETE`

`node_modules/gulp-ng-config` did not exist, but `node_modules/.gulp-ng-config.DELETE` did exist. It appeared to have what you would normally expect in a node module. I renamed it to plain `gulp-ng-config` and then things worked fine for me.

I don't know exactly what the problem is, but it seems like npm has incorrect information about what exists in `node_modules`. I didn't try `npm cache clean` but that might do something as well....

**Comment by aramk** [comment]
I'm getting this issue from a clean installation with node v6.9.2 and npm v3.10.9. It's using the official node docker image and starting a clean image.

**Comment by dkent600** [comment]
This is happening to me more often than not.  Example:

    _npm ERR! enoent ENOENT: no such file or directory, rename 'C:\[...]\node_modules\rx' -> '[...]\node_modules\.rx.DELETE'_

It is a different file every time, sometimes doesn't happen at all, but when it does, always with `[something].DELETE`.

I'm using npm version 5.0.3

Turning off virus protection doesn't help.

Running `npm cache clean -f`, as administrator may have helped, but I'm not sure yet if that will "take". [EDIT:  it didn't]

The problem has been getting steadily worse since a week or so ago, but seems somewhat random

**Comment by dmastag** [comment]
@dkent600 even though I have the same problem, I would advise you to submit a new ticket since normally closed tickets are not monitored especially if there are still hundreds of open tickets

**Comment by dkent600** [comment]
@dmastag  Done:  https://github.com/npm/npm/issues/17444
