### ISSUE TITLE
In npm@^3, extraneous packages are removed if npm-shrinkwrap.json present

### ISSUE THREAD

**Issue by julianlam** [npm/npm#11682]
This seems to be an unexpected change in behaviour. If you have `npm-shrinkwrap.json` present, any packages you install manually via npm are removed if you run `npm i` again, because they are not in the shrinkwrap file.

In npm@^2, extraneous packages stayed put.
## Reproduce

Create package.json with this content:

``` json
{
  "name": "npmtest",
  "dependencies": {
    "async": "~1.5.0",
    "bcryptjs": "~2.3.0"
  }
}
```

Then, `npm i && npm shrinkwrap` to generate the shrinkwrap file

`npm i winston` just to install the extraneous dependency

`npm i` again, which returns:

```
$ npm i
- async@1.0.0 node_modules/winston/node_modules/async
- colors@1.0.3 node_modules/winston/node_modules/colors
- cycle@1.0.3 node_modules/winston/node_modules/cycle
- eyes@0.1.8 node_modules/winston/node_modules/eyes
- isstream@0.1.2 node_modules/winston/node_modules/isstream
- pkginfo@0.3.1 node_modules/winston/node_modules/pkginfo
- stack-trace@0.0.9 node_modules/winston/node_modules/stack-trace
- winston@2.1.1 node_modules/winston
```

Winston (and it's dependencies) are now missing from `node_modules/`.

---

You might say -- if you install extraneous packages, you should put them into `package.json` as well... except in NodeBB, **we don't do that**. We have plugins that are installed via npm, and they're considered optional/extraneous and not bundled into `package.json` or the shinkwrap file.

With new npm, we're basically stuck with users having all of their plugins automatically uninstalled every time they update their NodeBB, which is... undesirable.

Thanks for your time. My apologies if this is a duplicate.

**Comment by julianlam** [comment]
[Relevant XKCD](https://xkcd.com/1172/)

**Comment by frissdiegurke** [comment]
+1

Since you can use `npm prune` to remove extraneous packages, doing this implicitly within `npm install` is taking away power of `npm shrinkwrap`.

**Comment by julianlam** [comment]
Bumping for reminder, thanks.

**Comment by Kovensky** [comment]
`npm install --production` when a shrinkwrap is present seems to also run an `npm prune --production` for you.
