### ISSUE TITLE
upgrade bower 

### ISSUE THREAD

**Issue by techie-douglas** [npm/npm#11681]
Hey I want to upgrade bower on cmd from 1.7.2 to 1.7.7  here is the error log file

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'bower' ]
2 info using npm@3.3.12
3 info using node@v5.1.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData bower
8 silly fetchOtherPackageData bower
9 silly cache add args [ 'bower', null ]
10 verbose cache add spec bower
11 silly cache add parsed spec Result {
11 silly cache add   raw: 'bower',
11 silly cache add   scope: null,
11 silly cache add   name: null,
11 silly cache add   rawSpec: 'bower',
11 silly cache add   spec: 'C:\\Users\\daggytbt\\WebstormProjects\\UoKVotingWebApp\\bower',
11 silly cache add   type: 'local' }
12 silly addLocalTarball shasum (computed) da39a3ee5e6b4b0d3255bfef95601890afd80709
13 verbose addTmpTarball C:\Users\daggytbt\WebstormProjects\UoKVotingWebApp\bower not in flight; adding
14 verbose makeDirectory C:\Users\daggytbt\AppData\Roaming\npm-cache creation not in flight; initializing
15 verbose makeCacheDir UID & GID are irrelevant on win32
16 verbose addTmpTarball validating metadata from C:\Users\daggytbt\WebstormProjects\UoKVotingWebApp\bower
17 verbose tar unpack C:\Users\daggytbt\WebstormProjects\UoKVotingWebApp\bower
18 verbose tar unpacking to C:\Users\daggytbt\AppData\Local\Temp\npm-385224-43cb7cc8\unpack-3c889d6e1ad8b86d70934d866f129e00
19 silly gentlyRm C:\Users\daggytbt\AppData\Local\Temp\npm-385224-43cb7cc8\unpack-3c889d6e1ad8b86d70934d866f129e00 is being purged
20 verbose gentlyRm don't care about contents; nuking C:\Users\daggytbt\AppData\Local\Temp\npm-385224-43cb7cc8\unpack-3c889d6e1ad8b86d70934d866f129e00
21 silly gunzTarPerm modes [ '777', '666' ]
22 error tar.unpack error reading C:\Users\daggytbt\WebstormProjects\UoKVotingWebApp\bower
23 error addLocal Could not install C:\Users\daggytbt\WebstormProjects\UoKVotingWebApp\bower
24 silly fetchPackageMetaData Error: 0-byte tarball
24 silly fetchPackageMetaData Please run `npm cache clean`
24 silly fetchPackageMetaData     at C:\Program Files\nodejs\node_modules\npm\lib\utils\tar.js:262:14
24 silly fetchPackageMetaData     at FSReqWrap.oncomplete (fs.js:82:15)
24 silly fetchPackageMetaData  error for bower [Error: 0-byte tarball
24 silly fetchPackageMetaData Please run `npm cache clean`]
25 silly rollbackFailedOptional Starting
26 silly rollbackFailedOptional Finishing
27 silly runTopLevelLifecycles Starting
28 silly runTopLevelLifecycles Finishing
29 silly install printInstalled
30 verbose stack Error: 0-byte tarball
30 verbose stack Please run `npm cache clean`
30 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\utils\tar.js:262:14
30 verbose stack     at FSReqWrap.oncomplete (fs.js:82:15)
31 verbose cwd C:\Users\daggytbt\WebstormProjects\UoKVotingWebApp
32 error Windows_NT 10.0.10240
33 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "bower"
34 error node v5.1.0
35 error npm  v3.3.12
36 error 0-byte tarball
36 error Please run `npm cache clean`
37 error If you need help, you may report this error at:
37 error     <https://github.com/npm/npm/issues>
38 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@techie-douglas Have you tried running the command that is displayed in the error log?:

```
36 error Please run npm cache clean
```

**Comment by ashleygwilliams** [comment]
@techie-douglas @KenanY's suggestion should fix this issue. please open a new issue if you continue to have trouble! good luck!

**Comment by techie-douglas** [comment]
I did the nmp cache clean a it didn't help
