### ISSUE TITLE
npm install -production failing since 3.7.4 for all modules (OSX and Linux)

### ISSUE THREAD

**Issue by ixalon** [npm/npm#11699]
I've been having an error when using `npm install` using the `-production` flag since updating npm to 3.7.5, I've rolled back to 3.7.4 and still see the issue (tested on both OSX and Ubuntu). No debug log is written. 3.7.3 is working correctly.

npm correctly installs the module but immediately before exiting (with return code 1) logs: `npm ERR! code 1`.

I've setup my environment and run a test installing lodash (the same occurs with all modules I've tried) as such:
```bash
rm -rf /tmp/npm-test ~/.npm
mkdir /tmp/npm-test
cd /tmp/npm-test
npm init -y
npm install -production -verbose lodash 2> install.log
```

My `~/.npmrc` contains only:
```
//registry.npmjs.org/:_authToken=<token>
```

The log from 3.7.3: https://gist.github.com/ixalon/bbba9547787f4d356f5a
The log from 3.7.4: https://gist.github.com/ixalon/260011abf364889a2e76

The diff between the resulting two logs shows nothing significant other than the final outcome:
```diff
diff v3.7.3.log v3.7.4.log
8c8
< npm info using npm@3.7.3
---
> npm info using npm@3.7.4
12c12
< npm info attempt registry request try #1 at 6:33:43 PM
---
> npm info attempt registry request try #1 at 6:32:33 PM
14c14
< npm verb request id 41cc55263c6b90a8
---
> npm verb request id 1bc96515d810d857
23c23
< npm verb headers   date: 'Fri, 26 Feb 2016 18:33:45 GMT',
---
> npm verb headers   date: 'Fri, 26 Feb 2016 18:32:34 GMT',
26c26
< npm verb headers   'x-served-by': 'cache-lhr6322-LHR',
---
> npm verb headers   'x-served-by': 'cache-lhr6325-LHR',
29c29
< npm verb headers   'x-timer': 'S1456511624.593941,VS0,VE813',
---
> npm verb headers   'x-timer': 'S1456511554.377427,VS0,VE202',
43,44c43,44
< npm info retry fetch attempt 1 at 6:33:45 PM
< npm info attempt registry request try #1 at 6:33:45 PM
---
> npm info retry fetch attempt 1 at 6:32:34 PM
> npm info attempt registry request try #1 at 6:32:34 PM
48c48
< npm verb addTmpTarball /var/folders/2c/myq6vg0d5rd604gbz7n6_t980000gn/T/npm-60624-1477c735/registry.npmjs.org/lodash/-/lodash-4.5.1.tgz not in flight; adding
---
> npm verb addTmpTarball /var/folders/2c/myq6vg0d5rd604gbz7n6_t980000gn/T/npm-60616-88880e53/registry.npmjs.org/lodash/-/lodash-4.5.1.tgz not in flight; adding
73c73
< npm info ok 
---
> npm ERR! code 1
```

**Comment by ixalon** [comment]
The stdout differs too. I wonder if it's related to this commit: https://github.com/npm/npm/commit/8d90d25b3da086843ce43911329c9572bd109078

v3.7.3:
```
npm-test@1.0.0 /private/tmp/npm-test
└── lodash@4.5.1  extraneous
```
v3.7.4:
```
npm-test@1.0.0 /private/tmp/npm-test
└── (empty)
```

Adding `-save` to the command line also allows v3.7.4 to exit successfully.

**Comment by KenanY** [comment]
`git bisect` tells me that it's https://github.com/npm/npm/commit/8d90d25b3da086843ce43911329c9572bd109078

**Comment by ixalon** [comment]
Tracked this down:

`filterByEnv` now removes any modules from `data.dependencies` that aren't listed in the package.json `dependencies` object. This is called here: https://github.com/npm/npm/blob/8d90d25b3da086843ce43911329c9572bd109078/lib/ls.js#L71

We then immediately call `filterFound` which is passed the details of the module we've just installed. It can not find the module because it's just been removed by `filterByEnv`, so sets `data._found` to `false`.

When we get a bit further, we check the value of `data._found` and if false, set `process.exitCode` to `1`:
https://github.com/npm/npm/blob/8d90d25b3da086843ce43911329c9572bd109078/lib/ls.js#L98

**Comment by ixalon** [comment]
I have a fix. I'll raise a PR.
