### ISSUE TITLE
I want to translated chinese for npm project，convenient for china developers。I hope join npm github  organization。

### ISSUE THREAD

**Issue by CoderBOBO** [npm/npm#11692]

**Comment by othiym23** [comment]
The npm CLI team is still coming up with a plan for localizing npm. It will probably involve [intl.js](https://www.npmjs.com/package/intl) and standardization of npm's error messages, and is something that the current core team may begin work on this year, but only towards the end of the year.

We're also working on documenting the way that users can become collaborators on the project. Until that plan is ready, the easiest way to get involved with work on the project is to just go ahead and submit pull requests. If you want to start work on translating npm for Chinese users, the team can help you figure out where to start and support you if you if you run into obstacles. Thanks for your interest in contributing!
