### ISSUE TITLE
Error happens when I try to run command "npm install -g generator-webapp"

### ISSUE THREAD

**Issue by AlexCao2016** [npm/npm#11695]
npm ERR! Error: No compatible version found: generator-jasmine@'^0.2.1'
npm ERR! Valid install targets:
npm ERR! ["0.1.0","0.1.1","0.1.2","0.1.3","0.2.0","0.2.1","0.2.2"]
npm ERR!     at installTargetsError (C:\nodejs\node_modules\npm\lib\cache.js:719:10)
npm ERR!     at C:\nodejs\node_modules\npm\lib\cache.js:641:10
npm ERR!     at saved (C:\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\nodejs\\\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "generator-webapp"
npm ERR! cwd C:\gds\drug-management
npm ERR! node -v v0.10.12
npm ERR! npm -v 1.2.32
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\gds\drug-management\npm-debug.log
npm ERR! not ok code 0

**Comment by KenanY** [comment]
@AlexCao2016 See my comment on [the previous issue you opened](https://github.com/npm/npm/issues/11694#issuecomment-189258912).

**Comment by KenanY** [comment]
Closing because `npm@1.2` is way too old at this point.
