### ISSUE TITLE
How to resolve this error??

### ISSUE THREAD

**Issue by mueedahmed1** [npm/npm#11705]
![untitled](https://cloud.githubusercontent.com/assets/12622228/13373487/10672c3e-dd8b-11e5-92f5-81468dc87e5e.png)

**Comment by codebhendi** [comment]
This is an issue with node itself so you should probably ask on there repository. I am giving you the link for similar issue on their repo [https://github.com/nodejs/node-v0.x-archive/issues/4516](url)

**Comment by KenanY** [comment]
Closing as not an issue with `npm`.
