### ISSUE TITLE
getting error in npm install in ubuntu 14.04

### ISSUE THREAD

**Issue by SilentFlame** [npm/npm#11706]
```
speedy@vinay:~$ npm install
npm ERR! install Couldn't read dependencies
npm ERR! Error: ENOENT, open '/home/speedy/package.json'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.19.0-51-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/speedy
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /home/speedy/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/speedy/npm-debug.log
npm ERR! not ok code 0
```

Help needed.

**Comment by codebhendi** [comment]
1. Check if the directory where you are running `npm install` has a file named package.json
2. If it is there then run npm install with sudo.

**Comment by KenanY** [comment]
In addition, do note that `npm@1.3` is years old and is no longer supported. Consider [updating](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm).

**Comment by KenanY** [comment]
@SilentFlame Are you still seeing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.

**Comment by amitgunjal26** [comment]
Yeah right, that directory must contain the file named package.json

**Comment by amitgunjal26** [comment]
You can install npm by >>> sudo apt-get install npm
It is installed previously by the way.
