### ISSUE TITLE
Error installing sails.js

### ISSUE THREAD

**Issue by SebastienFCT** [npm/npm#11709]
Hi there,

Google didn't give me any answer related to my issue, so I post here as recommended by the prompt.

I got a weird issue while trying to install `sails.js` via `npm`. This is the output from my prompt:

>npm WARN deprecated lodash@2.4.1: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated lodash@0.9.2: Grunt needs your help! See https://github.com/gruntjs/grunt/issues/1403.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated grunt-lib-contrib@0.7.1: DEPRECATED. See readme: https://github.com/gruntjs/grunt-lib-contrib
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "-g" "install" "sails"
npm ERR! node v4.2.4
npm ERR! npm  v3.7.0
npm ERR! Converting circular structure to JSON
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Please include the following file with any support request:
npm ERR!     /Users/sebastienfockchowtho/Desktop/npm-debug.log

And please find enclosed the npm-debug.txt (I copied/pasted the content to a .txt file):
[npm-debug.txt](https://github.com/npm/npm/files/149682/npm-debug.txt)

(`sudo` didn't fix the issue).

**Comment by codebhendi** [comment]
@SebastienFCT I checked one or two issues relaeted to or similar to this issue and many of those issues mentioned this command `sudo chown -R `whoami` ~/.npm`, try this after updating your npm to the latest version `npm install -g npm` try these #7555

**Comment by SebastienFCT** [comment]
@codebhendi , thank you for your answer! If I understand well, I should change the owner of `~/.npm` to my current user. 

In my case, 

> drwxr-xr-x  1110 sebastienfockchowtho  staff    37740 27 Feb 19:01 .npm

would become:

> drwxr-xr-x  1110 sebastienfockchowtho  sebastienfockchowtho    37740 27 Feb 19:01 .npm

Does this can imply anything on my work later (such as giving error for previous packages installed or something else)? Should I keep my current user as the owner of `~/.npm` after I installed `sails.js`.

Thank you in advance

**Comment by ashleygwilliams** [comment]
thanks everyone!
