### ISSUE TITLE
ENOTEMPTY: directory not empty, rename   ->  .DELETE

### ISSUE THREAD

**Issue by robie1kenobi** [npm/npm#11708]
reads similar to #11689 

[npm-debug.txt](https://github.com/npm/npm/files/149649/npm-debug.txt)

**Comment by robie1kenobi** [comment]
I am trying to install body-parser

**Comment by ashleygwilliams** [comment]
hey! sorry you're having this trouble. are you able to `ls /home/gandalf/PNET/JavaScript/node_modules/body-parser` ?

**Comment by robie1kenobi** [comment]
Hi Ashleyls: cannot access /home/gandalf/PNET/JavaScript/node_modules/body-parser: No such file or directory
gandalf@gandalf-Aspire-ES1-512:~$ 


   Regards Robert Muir skype: Robert_Muir 

    On Tuesday, 1 March 2016, 3:03, ashley williams <notifications@github.com> wrote:
 

 hey! sorry you're having this trouble. are you able to ls /home/gandalf/PNET/JavaScript/node_modules/body-parser ?—
