### ISSUE TITLE
Can't install any npm package

### ISSUE THREAD

**Issue by kaanyilgin** [npm/npm#11712]
Hello,

I reinstalled node.js today again. But I can't install any nodejs package now. Here is the log text:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli   'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'gulp' ]
2 info using npm@3.3.12
3 info using node@v5.4.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData gulp
8 silly fetchNamedPackageData gulp
9 silly mapToRegistry name gulp
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/gulp
13 verbose request uri https://registry.npmjs.org/gulp
14 verbose request no auth needed
15 info attempt registry request try #1 at 3:36:24 PM
16 verbose request id 861fe3a6dabd4ceb
17 http request GET https://registry.npmjs.org/gulp
18 http 200 https://registry.npmjs.org/gulp
19 verbose headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
19 verbose headers   etag: '"ECQ8GN0CYNK4N824KUAVPU2CX"',
19 verbose headers   'content-type': 'application/json',
19 verbose headers   'cache-control': 'max-age=300',
19 verbose headers   'content-length': '112716',
19 verbose headers   'accept-ranges': 'bytes',
19 verbose headers   date: 'Sun, 28 Feb 2016 13:36:24 GMT',
19 verbose headers   via: '1.1 varnish',
19 verbose headers   age: '55',
19 verbose headers   connection: 'keep-alive',
19 verbose headers   'x-served-by': 'cache-ams4121-AMS',
19 verbose headers   'x-cache': 'HIT',
19 verbose headers   'x-cache-hits': '1',
19 verbose headers   'x-timer': 'S1456666584.511085,VS0,VE0',
19 verbose headers   vary: 'Accept' }
20 silly get cb [ 200,
20 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
20 silly get     etag: '"ECQ8GN0CYNK4N824KUAVPU2CX"',
20 silly get     'content-type': 'application/json',
20 silly get     'cache-control': 'max-age=300',
20 silly get     'content-length': '112716',
20 silly get     'accept-ranges': 'bytes',
20 silly get     date: 'Sun, 28 Feb 2016 13:36:24 GMT',
20 silly get     via: '1.1 varnish',
20 silly get     age: '55',
20 silly get     connection: 'keep-alive',
20 silly get     'x-served-by': 'cache-ams4121-AMS',
20 silly get     'x-cache': 'HIT',
20 silly get     'x-cache-hits': '1',
20 silly get     'x-timer': 'S1456666584.511085,VS0,VE0',
20 silly get     vary: 'Accept' } ]
21 verbose get saving gulp to C:\Users\Kaan Ali Yılgın\AppData\Roaming\npm-cache\registry.npmjs.org\gulp.cache.json
22 silly install normalizeTree
23 silly loadCurrentTree Finishing
24 silly loadIdealTree Starting
25 silly install loadIdealTree
26 silly cloneCurrentTree Starting
27 silly install cloneCurrentTreeToIdealTree
28 silly cloneCurrentTree Finishing
29 silly loadShrinkwrap Starting
30 silly install loadShrinkwrap
31 silly loadShrinkwrap Finishing
32 silly loadAllDepsIntoIdealTree Starting
33 silly install loadAllDepsIntoIdealTree
34 silly resolveWithNewModule gulp@3.9.1 checking installable status
35 silly cache add args [ 'gulp', null ]
36 verbose cache add spec gulp
37 silly cache add parsed spec Result {
37 silly cache add   raw: 'gulp',
37 silly cache add   scope: null,
37 silly cache add   name: 'gulp',
37 silly cache add   rawSpec: '',
37 silly cache add   spec: '_',
37 silly cache add   type: 'range' }
38 silly addNamed gulp@_
39 verbose addNamed "_" is a valid semver range for gulp
40 silly addNameRange { name: 'gulp', range: '_', hasData: false }
41 silly mapToRegistry name gulp
42 silly mapToRegistry using default registry
43 silly mapToRegistry registry https://registry.npmjs.org/
44 silly mapToRegistry uri https://registry.npmjs.org/gulp
45 verbose addNameRange registry:https://registry.npmjs.org/gulp not in flight; fetching
46 verbose request uri https://registry.npmjs.org/gulp
47 verbose request no auth needed
48 info attempt registry request try #1 at 3:36:25 PM
49 http request GET https://registry.npmjs.org/gulp
50 http 200 https://registry.npmjs.org/gulp
51 verbose headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
51 verbose headers   etag: '"ECQ8GN0CYNK4N824KUAVPU2CX"',
51 verbose headers   'content-type': 'application/json',
51 verbose headers   'cache-control': 'max-age=300',
51 verbose headers   'content-length': '112716',
51 verbose headers   'accept-ranges': 'bytes',
51 verbose headers   date: 'Sun, 28 Feb 2016 13:36:25 GMT',
51 verbose headers   via: '1.1 varnish',
51 verbose headers   age: '56',
51 verbose headers   connection: 'keep-alive',
51 verbose headers   'x-served-by': 'cache-ams4135-AMS',
51 verbose headers   'x-cache': 'HIT',
51 verbose headers   'x-cache-hits': '1',
51 verbose headers   'x-timer': 'S1456666585.647775,VS0,VE0',
51 verbose headers   vary: 'Accept' }
52 silly get cb [ 200,
52 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
52 silly get     etag: '"ECQ8GN0CYNK4N824KUAVPU2CX"',
52 silly get     'content-type': 'application/json',
52 silly get     'cache-control': 'max-age=300',
52 silly get     'content-length': '112716',
52 silly get     'accept-ranges': 'bytes',
52 silly get     date: 'Sun, 28 Feb 2016 13:36:25 GMT',
52 silly get     via: '1.1 varnish',
52 silly get     age: '56',
52 silly get     connection: 'keep-alive',
52 silly get     'x-served-by': 'cache-ams4135-AMS',
52 silly get     'x-cache': 'HIT',
52 silly get     'x-cache-hits': '1',
52 silly get     'x-timer': 'S1456666585.647775,VS0,VE0',
52 silly get     vary: 'Accept' } ]
53 verbose get saving gulp to C:\Users\Kaan Ali Yılgın\AppData\Roaming\npm-cache\registry.npmjs.org\gulp.cache.json
54 silly addNameRange number 2 { name: 'gulp', range: '*', hasData: true }
55 silly addNameRange versions [ 'gulp',
55 silly addNameRange   [ '0.0.1',
55 silly addNameRange     '0.0.2',
55 silly addNameRange     '0.0.3',
55 silly addNameRange     '0.0.4',
55 silly addNameRange     '0.0.5',
55 silly addNameRange     '0.0.7',
55 silly addNameRange     '0.0.8',
55 silly addNameRange     '0.0.9',
55 silly addNameRange     '0.1.0',
55 silly addNameRange     '0.2.0',
55 silly addNameRange     '1.0.0',
55 silly addNameRange     '1.1.0',
55 silly addNameRange     '1.2.0',
55 silly addNameRange     '1.2.1',
55 silly addNameRange     '2.0.0',
55 silly addNameRange     '2.0.1',
55 silly addNameRange     '2.1.0',
55 silly addNameRange     '2.2.0',
55 silly addNameRange     '2.3.0',
55 silly addNameRange     '2.4.0',
55 silly addNameRange     '2.4.1',
55 silly addNameRange     '2.6.0',
55 silly addNameRange     '2.6.1',
55 silly addNameRange     '2.7.0',
55 silly addNameRange     '3.0.0',
55 silly addNameRange     '3.1.1',
55 silly addNameRange     '3.1.2',
55 silly addNameRange     '3.1.3',
55 silly addNameRange     '3.1.4',
55 silly addNameRange     '3.2.0',
55 silly addNameRange     '3.2.1',
55 silly addNameRange     '3.2.2',
55 silly addNameRange     '3.2.3',
55 silly addNameRange     '3.2.4',
55 silly addNameRange     '3.2.5',
55 silly addNameRange     '3.3.0',
55 silly addNameRange     '3.3.1',
55 silly addNameRange     '3.3.2',
55 silly addNameRange     '3.3.4',
55 silly addNameRange     '3.4.0',
55 silly addNameRange     '3.5.0',
55 silly addNameRange     '3.5.1',
55 silly addNameRange     '3.5.2',
55 silly addNameRange     '3.5.5',
55 silly addNameRange     '3.5.6',
55 silly addNameRange     '3.6.0',
55 silly addNameRange     '3.6.1',
55 silly addNameRange     '3.6.2',
55 silly addNameRange     '3.7.0',
55 silly addNameRange     '3.8.0',
55 silly addNameRange     '3.8.1',
55 silly addNameRange     '3.8.2',
55 silly addNameRange     '3.8.3',
55 silly addNameRange     '3.8.4',
55 silly addNameRange     '3.8.5',
55 silly addNameRange     '3.8.6',
55 silly addNameRange     '3.8.7',
55 silly addNameRange     '3.8.8',
55 silly addNameRange     '3.8.9',
55 silly addNameRange     '3.8.10',
55 silly addNameRange     '3.8.11',
55 silly addNameRange     '3.9.0',
55 silly addNameRange     '3.9.1' ] ]
56 silly addNamed gulp@3.9.1
57 verbose addNamed "3.9.1" is a plain semver version for gulp
58 silly mapToRegistry name gulp
59 silly mapToRegistry using default registry
60 silly mapToRegistry registry https://registry.npmjs.org/
61 silly mapToRegistry uri https://registry.npmjs.org/gulp
62 verbose addRemoteTarball https://registry.npmjs.org/gulp/-/gulp-3.9.1.tgz not in flight; adding
63 verbose addRemoteTarball [ 'https://registry.npmjs.org/gulp/-/gulp-3.9.1.tgz',
63 verbose addRemoteTarball   '571ce45928dd40af6514fc4011866016c13845b4' ]
64 info retry fetch attempt 1 at 3:36:26 PM
65 info attempt registry request try #1 at 3:36:26 PM
66 http fetch GET https://registry.npmjs.org/gulp/-/gulp-3.9.1.tgz
67 http fetch 200 https://registry.npmjs.org/gulp/-/gulp-3.9.1.tgz
68 silly fetchAndShaCheck shasum 571ce45928dd40af6514fc4011866016c13845b4
69 verbose addTmpTarball C:\Users\KAANAL~1\AppData\Local\Temp\npm-4900-bf4f0e55\registry.npmjs.org\gulp-\gulp-3.9.1.tgz not in flight; adding
70 verbose addTmpTarball already have metadata; skipping unpack for gulp@3.9.1
71 silly rollbackFailedOptional Starting
72 silly rollbackFailedOptional Finishing
73 silly runTopLevelLifecycles Starting
74 silly runTopLevelLifecycles Finishing
75 silly install printInstalled
76 verbose stack Error: UNKNOWN: unknown error, mkdir 'C:\Users\Kaan Ali Yılgın\AppData\Roaming\npm-cache\gulp\3.9.1\package'
76 verbose stack     at Error (native)
77 verbose cwd C:....
78 error Windows_NT 6.3.9600
79 error argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "gulp"
80 error node v5.4.1
81 error npm  v3.3.12
82 error path C:\Users\Kaan Ali Yılgın\AppData\Roaming\npm-cache\gulp\3.9.1\package
83 error code UNKNOWN
84 error errno -4094
85 error syscall mkdir
86 error UNKNOWN: unknown error, mkdir 'C:\Users\Kaan Ali Yılgın\AppData\Roaming\npm-cache\gulp\3.9.1\package'
87 error If you need help, you may report this error at:
87 error     https://github.com/npm/npm/issues
88 verbose exit [ -4094, true ]

**Comment by kminehart** [comment]
are you in an admin command prompt?  I see that you ran `npm install -g gulp`.  Installing global packages requires elevated privileges.  although `UNKOWN: unknown error` is not a super helpful error message.

**Comment by kaanyilgin** [comment]
Yes I opened cmd as administrator but it didn't work. But this problem was about my windows user. I created a new windows user and it worked. I researched it a few hours but couldn't help any solution.

**Comment by zahmed-f3** [comment]
Try to install any package after cleaning cache using **npm cache clean** command or removing all the contents from **C:\Users\<Your User>\AppData\Roaming\npm-cache**.

**Comment by busches** [comment]
You said a new user fixed it, do you have a utf-8 character in the listed username? The I is showing off on my mobile at least.
