### ISSUE TITLE
Please Help: I can not install cat-picture module with npm

### ISSUE THREAD

**Issue by hid2718** [npm/npm#11715]
I'm now studying in workshop 'ELEMENTARY-ELECTRON', but I can not install cat-picture module with npm as following:
$ npm install "cat-picture" --save
or
$ sudo npm install "cat-picture" --save
-->> Refusing to install cat-picture as a dependency of itself

Please help!!
[npm-debug.log.txt](https://github.com/npm/npm/files/150750/npm-debug.log.txt)

**Comment by ashleygwilliams** [comment]
hi! this error occurs when you try to install a dependency in a package/directory with the same name as that dependency. is you directory/package also named `"catpicture"`? rename it and you should be all set :)

if you continue to have trouble please open a new issue. good luck! :cat:

**Comment by hid2718** [comment]
I could solve may problem! I appreciate in your quick and appropriate advices. Thank you!!
