### ISSUE TITLE
Error installing meanio.

### ISSUE THREAD

**Issue by Waffleboy** [npm/npm#11710]
Hi, i tried installing meanio using

npm install -g meanio

and

npm install -g meanio@latest

Both both throw me the error as shown.

![image](https://cloud.githubusercontent.com/assets/12254813/13378053/2d787020-de31-11e5-995e-204c1624d6a7.png)

I tried reinstalling node and npm, and now use NVM to update to latest version of node and npm and it still doesnt work.

Anyone have any ideas? :)

**Comment by KenanY** [comment]
@Waffleboy Is this still an issue for you?

**Comment by KenanY** [comment]
Closing as abandoned.
