### ISSUE TITLE
npm problem

### ISSUE THREAD

**Issue by MAJDA55** [npm/npm#11718]
Error: Cannot find module 'C:\Users\mejda\node_modules\electron-prebuilt\dist\re                                                                                                               sources\atom.asar\browser\lib\init.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:151:18)
    at node.js:1007:3

**Comment by KenanY** [comment]
@MAJDA55 Are you sure that `npm` is the one who is throwing this error?

**Comment by ashleygwilliams** [comment]
hi! this appears to be an issue with `electron-packager` on Windows. see this issue for some direction: https://github.com/atom/electron/issues/3181

if you continue to have trouble, please file an issue here: https://github.com/electron-userland/electron-packager

good luck!

**Comment by voldmar** [comment]
@ashleygwilliams, @MAJDA55 This is issue in `electron-winstaller`, I submitted pull request that should help. `electron-packager` makes perfect application, but it corrupted on making Setup.exe stage.
