### ISSUE TITLE
Cannot use Cat script

### ISSUE THREAD

**Issue by DennisNerush** [npm/npm#11711]
I'm trying to concat my css files into single file.
I'm following this solution:
http://stackoverflow.com/questions/35324055/combine-css-files-into-single-file-using-npm/35331888#35331888

How ever when I run the script I get this error:
Error: ENOENT: no such file or directory, open 'C:\dev\pharmvillie\Pharmville\Ph
armville\Client\js\**\*.css'
    at Error (native)

I've attached the build file and my Package.json

[npm-debug.zip](https://github.com/npm/npm/files/149798/npm-debug.zip)

**Comment by guilhermehn** [comment]
Seems like you mistyped the path: `\js*\.css`.

**Comment by DennisNerush** [comment]
I have the following file structure:
Client/
     ├──js/
         |──component1  
               ├──one.css 
               ├──one.js 
         |──component2  
               ├──two.css 
               ├──two.js 
    ├──output/
    └──package.json

What is the right way to set the path in order to address all the css files in the js directory?

**Comment by ashleygwilliams** [comment]
the path you are trying to write is `\js\*.css` which would map to all files in the `js` directory that have the `*.css` extension

if you continue to have issues, please file another issue! good luck!
