### ISSUE TITLE
Package installation via github fails silently if package name doesn't match

### ISSUE THREAD

**Issue by apfelbox** [npm/npm#11722]
Hi,

I just wanted to install a package with the following `package.json`:

``` json
{
  "private": true,
  "dependencies": {
    "matchMedia": "github:paulirish/matchMedia.js"
  }
}
```

This doesn't work, as the package name was changed in the meantime to `matchmedia-polyfill`. But if I run `npm install` with this `package.json`, I just get… nothing.

No package, but no error message either. Just nothing:

``` bash
$ npm install

$
```

I would suggest to show an error message in case the package name doesn't match the found `package.json` in the git repository?

**Comment by DavidCai1993** [comment]
:+1:  It's confused

**Comment by jochakovsky** [comment]
👍 Just ran into this myself
