### ISSUE TITLE
error npm install on Win 7 64 BIT

### ISSUE THREAD

**Issue by ebaad** [npm/npm#11723]
[npm-debug.txt](https://github.com/npm/npm/files/151949/npm-debug.txt)
Tried to install ember after a nodejs V 5.7.0 stable install and got the following error, any help would be appreciated.

> npm ERR! Windows_NT 6.1.7601
> npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g"
>  "ember-cli"
> npm ERR! node v5.7.0
> npm ERR! npm  v3.6.0
> npm ERR! code SELF_SIGNED_CERT_IN_CHAIN
> 
> npm ERR! self signed certificate in certificate chain
> npm ERR!
> npm ERR! If you need help, you may report this error at:
> npm ERR!     https://github.com/npm/npm/issues
> 
> npm ERR! Please include the following file with any support request:

**Comment by pedzed** [comment]
Relevant: #11740
