### ISSUE TITLE
Refusing to install parse-server as a dependency of itself

### ISSUE THREAD

**Issue by bhushanawasare90** [npm/npm#11727]
I am trying to install 'parse-server' module using command:
**sudo npm install parse-server**
But, this command is not installing parse-server module properly & giving me an error like:
_"Refusing to install parse-server as a dependency of itself"_.
I would like to listen if I am missing something.
Following is the screenshot of the Terminal:
![parse-server](https://cloud.githubusercontent.com/assets/16936524/13418519/19e68a1c-df9c-11e5-9b13-8d54166078f8.png)

Thanks in advance.

**Comment by KenanY** [comment]
@bhushanawasare90 It looks to me like you have already `git clone`d `parse-server` and that you are now trying to install the module within its own source code. This is not allowed by `npm`, this would imply that `parse-server` is a dependency of itself.

I think what you _should_ be doing is running `npm install parse-server` from within your project directory.

**Comment by bhushanawasare90** [comment]
Hi KenanY,
Thanks for your time.
I agree.! Sorry, but could you please suggest me any possible solution for it, as I am new to the same ?

**Comment by KenanY** [comment]
@bhushanawasare90 A solution to the specific error you are receiving would be to **not** run `npm install parse-server` in a folder which contains the source code for `parse-server`.

**Comment by KenanY** [comment]
@bhushanawasare90 Are you still seeing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
