### ISSUE TITLE
npm run fails on Windows when command contains "./"

### ISSUE THREAD

**Issue by kaiyoma** [npm/npm#11721]
I'm working on a project with a team of mixed operating systems (Windows, Linux, Mac) and our package.json has a few `npm run` definitions that include the dot-slash notation for executing a binary:

```
    ...
    "prod": "./scripts/build.sh",
    "test": "./scripts/test.sh",
    ...
```

When I try to run these commands in my git bash shell in Windows, I get this error:

```
$ npm run test

> ...@0.0.1 test C:\Users\...
> ./scripts/test.sh

'.' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "test"
npm ERR! node v5.5.0
npm ERR! npm  v3.7.0
npm ERR! code ELIFECYCLE
npm ERR! ...@0.0.1 test: `./scripts/test.sh`
npm ERR! Exit status 1
```

The dot-slash notation works just fine when run directly in the shell, so this is an issue with npm.

**Comment by simoneb** [comment]
bump

**Comment by brian-lamb-software-engineer** [comment]
im still experiencing this problem too.

**Comment by zkat** [comment]
sh scripts don't work on Windows. If you can't type `./scripts/test.sh` in your windows terminal, you can't use it through `run-script`. Note that npm does not directly support WSL, and any WSL-related issues should be directed to the repo for that project, instead.

**Comment by kaiyoma** [comment]
Running `./scripts/tesh.sh` doesn't work in Windows command prompt, true, but it _does_ work in Git bash, which is what I'm using. Not a big deal I guess. I ended up modifying my `package.json` to have entries like this instead:

```
...
"prod": "bash scripts/build.sh",
"test": "bash scripts/test.sh",
...
```
