### ISSUE TITLE
Raspberry Pi 2 npm error

### ISSUE THREAD

**Issue by rsokolski** [npm/npm#11725]
Any help for me :)???

pi@raspberrypi:~/alexaHarmonyApp-master $ npm install
npm WARN package.json alexa_harmony_hub_app@1.0.0 No repository field.
npm WARN engine harmonyhubjs-client@1.1.8: wanted: {"npm":">=3.0.0"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm ERR! not a package /tmp/npm-10539-NwYMexze/github.com/swissmanu/ltx.git
npm ERR! Error: ENOENT, open '/tmp/npm-10539-NwYMexze/github.com/swissmanu/ltx.git-unpack/package.json'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.1.17-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/pi/alexaHarmonyApp-master
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! path /tmp/npm-10539-NwYMexze/github.com/swissmanu/ltx.git-unpack/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/alexaHarmonyApp-master/npm-debug.log
npm ERR! not ok code 0

**Comment by pedzed** [comment]
Is your problem solved? If yes, please close the issue.

**Comment by aallanrd** [comment]
Are you missing the * package.json * ??? 

Try "ls -l" and check if there is a *package.json* 

If not you just need to *init* the repository 

> npm init

**Comment by KenanY** [comment]
@rsokolski ping

**Comment by pedzed** [comment]
> @rsokolski ping

Just close the issue if they don't answer within a reasonable time. You have over 2,300 issues open. This should be used for bug reporting, not asking for help.

**Comment by KenanY** [comment]
@pedzed I don't have the ability to close issues :/

**Comment by pedzed** [comment]
> @pedzed I don't have the ability to close issues :/

"npm member" keeps confusing me.

**Comment by KenanY** [comment]
@pedzed Yeah, it just means I'm part of the GitHub organization. I don't have "collaborator" status for this repo so I can't close/label issues.

/cc @npm/cli-team abandoned issue

**Comment by AndyBold** [comment]
For posterity, and anybody else who stumbles across this issue, the suggested fix of installing the latest version of npm does fix this problem.
