### ISSUE TITLE
Git dependencies and npm shrinkwrap don't work together

### ISSUE THREAD

**Issue by bouk** [npm/npm#11736]
Hi,

It seems npm shrinkwrap and git dependencies are fundamentally incompatible with each other. 

```bash
echo '{"private": true, "dependencies": {"jquery": "jquery/jquery"}}' > package.json
npm install
npm shrinkwrap
rm -rf node_modules
npm install
npm shrinkwrap
```

This will display an error similar to

```
npm ERR! Darwin 15.3.0
npm ERR! argv "/Users/bouke/.nvm/versions/node/v5.5.0/bin/node" "/Users/bouke/.nvm/versions/node/v5.5.0/bin/npm" "shrinkwrap"
npm ERR! node v5.5.0
npm ERR! npm  v3.3.12

npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! invalid: have jquery@3.0.0-pre (expected: github:jquery/jquery) /tmp/lolnpm/node_modules/jquery
npm ERR! extraneous: jquery@3.0.0-pre /tmp/lolnpm/node_modules/jquery
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/lolnpm/npm-debug.log
```

Installing from a shrinkwrap should not cause shrinkwrapping after to fail

**Comment by othiym23** [comment]
This appears to be a bug in how the installer deals with hosted git dependencies once they've been cached (you can see this just by reinstalling a hosted git package once it's been added to your cache and running `npm ls`, which will give you an error similar to the one above). Added to `big-bug` because it produces inconsistent installs and blocks use of shrinkwrap. Thanks for the report!

**Comment by XYliang** [comment]
Try using an administrator mode

**Comment by kazkovsky** [comment]
+1

I have my github repository in shrinkwrap, but it doesn't update on any machine.

`cat npm-shrinkwrap.json | grep <my repo>`

```
 "<my repo>": {
      "from": "git+https://<token>:x-oauth-basic@github.com/<my repo>.git",
      "resolved": "git+https://<token>:x-oauth-basic@github.com/<my repo>#9a68c540902e6497855699b990e662e5ab73d3ba"
```

after running `npm install` it keeps old version:

`npm list`
```
│ └── y18n@3.2.0
└─┬<my repo>@0.2.7 (git+https://<token>:x-oauth-basic@github.com/<my repo>#dd7d3fdf0cb57d8ae9ad1e70326fb4ad98675815)
  ├── canvas@1.2.11
  ├─┬ gulp-plumber@1.1.0
  │ └─┬ through2@2.0.1
```

**Comment by thomsbg** [comment]
This seems like a dupe or (or at least related to) #10502

**Comment by sminnee** [comment]
Another replication case.

Include this in dependencies:

    "dependencies": {
    ...
      "chosen": "github:harvesthq/chosen#v1.5.1",
    ...
    },

Clean the environment, install & re-shrinkwrap, then keep the shrinkwrap and install from that 

     rm -rf node_modules
     rm npm-shrinkwrap.json
     npm install
     npm shrinkwrap --dev
     # commit npm-shrinkwrap.json to source contorl
     rm -rf node_modues
     npm install

Finally, attempt to re-shrinkwrap:

    npm ERR! invalid: have chosen@1.5.1 (expected: github:harvesthq/chosen#v1.5.1) /<path>/node_modules/chosen
    npm ERR! extraneous: chosen@1.5.1 /<path>/node_modules/chosen

Verified on npm 3.8.6

**Comment by chromakode** [comment]
I'm experiencing the same bug. One thing I've noticed: if I individually `npm install` the specific packages that failed to shrinkwrap, the problem goes away. Diffing the resulting `package.json`s may help get to the bottom of this issue.

**Comment by chromakode** [comment]
Update: using full git URLs with commit hashes (instead of branch names) in `package.json` seems to work around this issue. 

For example, changing "jquery/jquery#master" to "git://github.com/jquery/jquery#73bf35ecf31867d7ed4662374121efa310cf9f8d" shrinkwraps successfully.

**Comment by saitodisse** [comment]
thanks @chromakode, save my life

**Comment by mashaalmemon** [comment]
@chromakode, your post saved me alot of time. Full URL and commit hash are the ticket to workaround npm shrinkwrap issue. Note, for anyone else who happens on this post, Also works with https full git URLs as well like so: 
"git+https://github.com/jquery/jquery.git#73bf35ecf31867d7ed4662374121efa310cf9f8d"

**Comment by istrau3** [comment]
@othiym23 
I think this issue has reappeared in the new npm 5+, in other words, when others try running `npm install` on my project, the install does not obey the shrinkwrap for git dependencies but instead obeys the package.json spec.
Should I create a separate issue?

**Comment by cklmercer** [comment]
Same issue here with npm 5+

using full url and commit hash
