### ISSUE TITLE
Guys, how to fix following errors..

### ISSUE THREAD

**Issue by iz-syed** [npm/npm#11739]
C:\Users\Syed Mubarak>npm install -g ionic
npm ERR! tar.unpack error reading C:\Users\Syed Mubarak\ionic
npm ERR! addLocal Could not install C:\Users\Syed Mubarak\ionic
npm ERR! Windows_NT 6.1.7600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ionic"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6

npm ERR! 0-byte tarball
npm ERR! Please run `npm cache clean`
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Syed Mubarak\npm-debug.log

C:\Users\Syed Mubarak>npm --version
3.3.6

**Comment by iz-syed** [comment]
Guys, how to fix following errors..
i am new one for ionic, anybody facing these error; please help me :(

**Comment by KenanY** [comment]
Hello @iz-syed! Did you try running the command (`npm cache clean`) that the error message is suggesting that you run?

**Comment by iz-syed** [comment]
Hello @KenanY  thanks for your reply :D yes i tried  (npm cache clean) couple of times. But i get same error again and again...

**Comment by pedzed** [comment]
Did you try to reinstall nodejs? https://nodejs.org/en/download

**Comment by markstos** [comment]
No response since the OP since March 3rd, I think this issue can be closed.

**Comment by pedzed** [comment]
> No response since the OP since March 3rd, I think this issue can be closed.

Yeah, the NPM team really should be a bit more aggressive in regards to closing issues. Having 2,400 issues open is very bad. Questions should be put in a forum or a Q/A site. Only bugs, feature requests, etc. should be accepted if you ask me.

**Comment by KenanY** [comment]
Closing as abandoned. I'm still working on going through all the abandoned issues. Last night alone I must have commented on dozens of issues from last year.

**Comment by pedzed** [comment]
> Last night alone I must have commented on dozens of issues from last year.

I noticed. Just close them with a standard message if you feel that it is abandoned. If the OP has something against it, you can just reopen.

**Comment by KenanY** [comment]
@pedzed Hmm, yeah, I could switch to doing that.

**Comment by pedzed** [comment]
In the end it is not my decision, but I want to emphasize that you should not allow support questions. Make a forum or a Q/A site available if there isn't one.

Labeling "support" works, but is that really ideal? Maybe that works, GitHub has a nice filter and search, but an outsider seeing 2.4k issues open isn't going to think that it is maintained well. That is my observation at least.

**Comment by KenanY** [comment]
@pedzed Yeah, it would be nice to have all support stuff go to StackOverflow (there's an `npm` tag there that I watch sometimes) and [npm/support-cli](https://github.com/npm/support-cli). Maybe one day :)
