### ISSUE TITLE
Property with the same name already exists: Cannot add property dist

### ISSUE THREAD

**Issue by zalow517** [npm/npm#11731]
Hi all,

I am encountering issues with installing a private package after publishing it successfully. I can't understand what's going on here and I've tried running the same thing on a different machine with the same Node/NPM setup.

The first time I published this package, everything worked fine - then I updated the package and republished. Now not even the first package that I had published is working, and is showing me the same error as the below:

```
29 info retry will retry, error on last attempt: Error: ArgumentException Can not add property dist to Newtonsoft.Json.Linq.JObject. Property with the same name already exists on object.: npm
30 info attempt registry request try #2 at 12:29:59 PM
31 http request GET <private repo URL>
32 http 500 <private repo URL>
33 verbose headers { 'cache-control': 'private',
33 verbose headers   'content-length': '153',
33 verbose headers   'content-type': 'application/json; charset=utf-8',
33 verbose headers   server: 'Microsoft-IIS/8.5',
33 verbose headers   'x-aspnet-version': '4.0.30319',
33 verbose headers   'x-powered-by': 'ASP.NET',
33 verbose headers   date: 'Tue, 01 Mar 2016 11:29:59 GMT' }
```

Any ideas? Tried searching everywhere but the E500 error code seems to be a very generic one and couldn't find anything related to 'npm install' for it.

**Comment by othiym23** [comment]
This appears to be an issue with the configuration of the private registry more than the npm CLI:

```
29 info retry will retry, error on last attempt: Error: ArgumentException Can not add property dist to Newtonsoft.Json.Linq.JObject. Property with the same name already exists on object.: npm
```

That's the message being returned by the registry along with the 500 status code. Talk to whoever's responsible for running your private registry and make sure that you've got everything configured as necessary on your install target.

As this isn't a bug in the CLI, and the CLI team isn't in a good spot to help you with your private registry software (I'm not even sure which product it is, from that error message), I'm going to close this issue. Good luck getting things sorted out, and thanks for your time!

**Comment by pascalberger** [comment]
@zalow517 Were you able to solve this solution? I've the same error trying to call `npm install` on https://github.com/StfBauer/SimpleStyle while running a private npm repository on ProGet with a connector to the public repository.
