### ISSUE TITLE
Firebase is not getting installed - npm

### ISSUE THREAD

**Issue by AshayAgrawal** [npm/npm#11730]
Hi,

I am not able to install firebase tools using npm. Logs are attached. Please help fix.
[npm-debug.txt](https://github.com/npm/npm/files/152500/npm-debug.txt)

**Comment by othiym23** [comment]
The host on which you're trying to install `firebase-tools` appears to have run into a transient network error. If you run `npm cache clear firebase-tools`, and then try the install again, does the error recur?

**Comment by Dssdiego** [comment]
I ran `npm3 install firebase --save` and worked

**Comment by AlexanderZon** [comment]
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "firebase"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ENOSELF

[npm-debug.txt](https://github.com/npm/npm/files/690138/npm-debug.txt)

**Comment by Charlotteis** [comment]
@AlexanderZon 

Please make sure that the `"name"` field in your `package.json` does not read `"firebase"`, change it to something else and you should be able to install firebase! 

🌸

**Comment by falahgs** [comment]
thanks @Dssdiego
I ran npm install firebase --save worked to me very well

**Comment by ratneshnavlakhe** [comment]
thanks @Charlotteis worked for me, my app name was `firebase`

**Comment by TheHackerdroid** [comment]
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os"
:"win32","arch":"x64"})
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "firebase" "
--save"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! path E:\Ionic\toDoList\node_modules\.staging\jsonwebtoken-3c111366
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename 'E:\Ionic\toDoList\node_modules\.staging\jsonwebtoken-3c111366' -> 'E:\Ionic\toDoLi
st\node_modules\firebase\node_modules\jsonwebtoken'
npm ERR!     at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:25:7)
npm ERR!     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'E:\Ionic\toDoList\node_modules\.staging\jsonwebtoken-3c111366' -> 'E:\Ionic\toDoLi
st\node_modules\firebase\node_modules\jsonwebtoken'
npm ERR!     at Error (native)
npm ERR!  { Error: EPERM: operation not permitted, rename 'E:\Ionic\toDoList\node_modules\.staging\jsonwebtoken-3c111366' -> 'E:\Ionic\toD
oList\node_modules\firebase\node_modules\jsonwebtoken'
npm ERR!     at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:25:7)
npm ERR!     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'E:\Ionic\toDoList\node_modules\.staging\jsonwebtoken-3c111366' -> 'E:\Ionic\toDoLi
st\node_modules\firebase\node_modules\jsonwebtoken'
npm ERR!     at Error (native) parent: 'firebase' }

**Comment by sachithamh** [comment]
node - v8.1.2
os macOS 10.12.5

npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm ERR! path /usr/local/lib/node_modules/firebase-tools/node_modules/.bin
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall rmdir
npm ERR! Error: EACCES: permission denied, rmdir '/usr/local/lib/node_modules/firebase-tools/node_modules/.bin'
npm ERR!  { Error: EACCES: permission denied, rmdir '/usr/local/lib/node_modules/firebase-tools/node_modules/.bin'
npm ERR!   cause: 
npm ERR!    { Error: EACCES: permission denied, rmdir '/usr/local/lib/node_modules/firebase-tools/node_modules/.bin'
npm ERR!      errno: -13,
npm ERR!      code: 'EACCES',
npm ERR!      syscall: 'rmdir',
npm ERR!      path: '/usr/local/lib/node_modules/firebase-tools/node_modules/.bin' },
npm ERR!   stack: 'Error: EACCES: permission denied, rmdir \'/usr/local/lib/node_modules/firebase-tools/node_modules/.bin\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'rmdir',
npm ERR!   path: '/usr/local/lib/node_modules/firebase-tools/node_modules/.bin' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/useraccount/.npm/_logs/2017-07-09T09_16_49_246Z-debug.log

**Comment by sachithamh** [comment]
answer: use node recommended  one not latest one and run command with sudo,
>sudo npm install -g firebase-tools
