### ISSUE TITLE
Installing devDependencies does not update shrinkwrap

### ISSUE THREAD

**Issue by sheepsteak** [npm/npm#11735]
I've created a shrink-wrap using `npm shrinkwrap --dev`. Installing new dependencies (`npm i -S express`) correctly updates the `npm-shrinkwrap.json`. However, installing a devDependency (`npm i -D eslint@1`) does **not** update the `npm-shrinkwrap.json`.

This seems counterintuitive as we've specified we want everything shrinkwrapped so you would expect `npm-shrinkwrap.json` to always be updated. To get around this at the moment we have to always remember to do `npm shrinkwrap --dev` after installing a new devDependency. Also, when updating a dependency with something like `npm i -D eslint@2` the `npm-shrinkwrap.json` is not updated either, which is probably even worse as it's already specified in the `npm-shrinkwrap.json`! :fearful:

This is with `npm@3.8.0`.

**Comment by othiym23** [comment]
Yep, this seems like a pretty straightforward bug. The CLI team is in the middle of a significant rewrite of its test suite, so it may be a little while until we get around to fixing this, but in the meantime, a patch that ensure that the behavior with shrinkwraps on `--save-dev` matches the behavior on `--save` would be very welcome. Thanks for your time!

**Comment by JohanNordlinder** [comment]
My team also suffer from this bug and I agree with sheepsteak, `npm install -[-S|--save|-D|` should also update the shrinkwrap we've created with `npm shrinkwrap --dev`, this is the behavior you would expect after reading the documentation.

**Comment by mkscrg** [comment]
We hit this as well. It makes managing shrinkwrapped devDependencies pretty difficult!

**Comment by szimek** [comment]
@othiym23 If shrinkwrap file was generated without `--dev` option, should `npm install --save-dev` update it as well?
