### ISSUE TITLE
getting npm error shasum check failed when trying to install kraken($ npm install -g yo generator-kraken bower grunt-cli)

### ISSUE THREAD

**Issue by poornimaprakashmj** [npm/npm#11737]
[npm-bebug.txt](https://github.com/npm/npm/files/153356/npm-bebug.txt)
error as shown: $ npm install -g yo generator-kraken bower grunt-cli
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\      node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "yo" "generator-kraken" "bowe      r" "grunt-cli"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! shasum check failed for C:\Users\poopraka\AppData\Local\Temp\npm-25328-      aa464253\registry.npmjs.org\generator-kraken\-\generator-kraken-2.2.2.tgz
npm ERR! Expected: 28c4f4089073d09a27179b1fd0a5bb0b35145808
npm ERR! Actual:   9edd6b8cf56c73b5e40ade1408cde68e34adf5c1
npm ERR! From:     https://registry.npmjs.org/generator-kraken/-/generator-krake      n-2.2.2.tgz
npm ERR!

**Comment by KenanY** [comment]
@poornimaprakashmj Have you tried `npm cache clean`?

**Comment by KenanY** [comment]
@poornimaprakashmj Just following up here as it has been a couple of months... are you still seeing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
