### ISSUE TITLE
redux 404

### ISSUE THREAD

**Issue by jessehattabaugh** [npm/npm#11744]
> 0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/opt/nvm/versions/node/v5.6.0/bin/node',
1 verbose cli   '/usr/local/opt/nvm/versions/node/v5.6.0/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--save-dev',
1 verbose cli   'redux' ]
2 info using npm@3.6.0
3 info using node@v5.6.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData redux
8 silly fetchNamedPackageData redux
9 silly mapToRegistry name redux
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/redux
13 verbose request uri https://registry.npmjs.org/redux
14 verbose request no auth needed
15 info attempt registry request try #1 at 3:55:36 AM
16 verbose request id fbb5b3503a682ec9
17 verbose etag "CZZFJLBHF29LC7OT0TQNEMAMZ"
18 http request GET https://registry.npmjs.org/redux
19 http 304 https://registry.npmjs.org/redux
20 verbose headers { date: 'Wed, 02 Mar 2016 03:55:36 GMT',
20 verbose headers   via: '1.1 varnish',
20 verbose headers   'cache-control': 'max-age=300',
20 verbose headers   etag: '"CZZFJLBHF29LC7OT0TQNEMAMZ"',
20 verbose headers   age: '0',
20 verbose headers   connection: 'keep-alive',
20 verbose headers   'x-served-by': 'cache-lax1422-LAX',
20 verbose headers   'x-cache': 'HIT',
20 verbose headers   'x-cache-hits': '1',
20 verbose headers   'x-timer': 'S1456890936.244874,VS0,VE41',
20 verbose headers   vary: 'Accept' }
21 silly get cb [ 304,
21 silly get   { date: 'Wed, 02 Mar 2016 03:55:36 GMT',
21 silly get     via: '1.1 varnish',
21 silly get     'cache-control': 'max-age=300',
21 silly get     etag: '"CZZFJLBHF29LC7OT0TQNEMAMZ"',
21 silly get     age: '0',
21 silly get     connection: 'keep-alive',
21 silly get     'x-served-by': 'cache-lax1422-LAX',
21 silly get     'x-cache': 'HIT',
21 silly get     'x-cache-hits': '1',
21 silly get     'x-timer': 'S1456890936.244874,VS0,VE41',
21 silly get     vary: 'Accept' } ]
22 verbose etag https://registry.npmjs.org/redux from cache
23 verbose get saving redux to /home/nitrous/.npm/registry.npmjs.org/redux/.cache.json
24 verbose correctMkdir /home/nitrous/.npm correctMkdir not in flight; initializing
25 silly install normalizeTree
26 silly loadCurrentTree Finishing
27 silly loadIdealTree Starting
28 silly install loadIdealTree
29 silly cloneCurrentTree Starting
30 silly install cloneCurrentTreeToIdealTree
31 silly cloneCurrentTree Finishing
32 silly loadShrinkwrap Starting
33 silly install loadShrinkwrap
34 silly loadShrinkwrap Finishing
35 silly loadAllDepsIntoIdealTree Starting
36 silly install loadAllDepsIntoIdealTree
37 silly resolveWithNewModule redux@3.3.1 checking installable status
38 silly cache add args [ 'redux', null ]
39 verbose cache add spec redux
40 silly cache add parsed spec Result {
40 silly cache add   raw: 'redux',
40 silly cache add   scope: null,
40 silly cache add   name: 'redux',
40 silly cache add   rawSpec: '',
40 silly cache add   spec: 'latest',
40 silly cache add   type: 'tag' }
41 silly addNamed redux@latest
42 verbose addNamed "latest" is being treated as a dist-tag for redux
43 info addNameTag [ 'redux', 'latest' ]
44 silly mapToRegistry name redux
45 silly mapToRegistry using default registry
46 silly mapToRegistry registry https://registry.npmjs.org/
47 silly mapToRegistry uri https://registry.npmjs.org/redux
48 verbose addNameTag registry:https://registry.npmjs.org/redux not in flight; fetching
49 verbose get https://registry.npmjs.org/redux not expired, no request
50 silly addNameTag next cb for redux with tag latest
51 silly addNamed redux@3.3.1
52 verbose addNamed "3.3.1" is a plain semver version for redux
53 silly cache afterAdd redux@3.3.1
54 verbose afterAdd /home/nitrous/.npm/redux/3.3.1/package/package.json not in flight; writing
55 verbose correctMkdir /home/nitrous/.npm correctMkdir not in flight; initializing
56 verbose afterAdd /home/nitrous/.npm/redux/3.3.1/package/package.json written
57 silly fetchNamedPackageData lodash
58 silly mapToRegistry name lodash
59 silly mapToRegistry using default registry
60 silly mapToRegistry registry https://registry.npmjs.org/
61 silly mapToRegistry uri https://registry.npmjs.org/lodash
62 silly fetchNamedPackageData lodash-es
63 silly mapToRegistry name lodash-es
64 silly mapToRegistry using default registry
65 silly mapToRegistry registry https://registry.npmjs.org/
66 silly mapToRegistry uri https://registry.npmjs.org/lodash-es
67 verbose request uri https://registry.npmjs.org/lodash-es
68 verbose request no auth needed
69 info attempt registry request try #1 at 3:55:36 AM
70 verbose etag "5DL0EY8MRJCXGT0HJCQEALHQX"
71 http request GET https://registry.npmjs.org/lodash-es
72 verbose request uri https://registry.npmjs.org/lodash
73 verbose request no auth needed
74 info attempt registry request try #1 at 3:55:36 AM
75 verbose etag "23DWWOVKJ3UT53R756NKD3WH2"
76 http request GET https://registry.npmjs.org/lodash
77 http 304 https://registry.npmjs.org/lodash
78 verbose headers { date: 'Wed, 02 Mar 2016 03:55:37 GMT',
78 verbose headers   via: '1.1 varnish',
78 verbose headers   'cache-control': 'max-age=300',
78 verbose headers   etag: '"23DWWOVKJ3UT53R756NKD3WH2"',
78 verbose headers   age: '54',
78 verbose headers   connection: 'keep-alive',
78 verbose headers   'x-served-by': 'cache-sjc3125-SJC',
78 verbose headers   'x-cache': 'HIT',
78 verbose headers   'x-cache-hits': '7',
78 verbose headers   'x-timer': 'S1456890937.041782,VS0,VE0',
78 verbose headers   vary: 'Accept' }
79 silly get cb [ 304,
79 silly get   { date: 'Wed, 02 Mar 2016 03:55:37 GMT',
79 silly get     via: '1.1 varnish',
79 silly get     'cache-control': 'max-age=300',
79 silly get     etag: '"23DWWOVKJ3UT53R756NKD3WH2"',
79 silly get     age: '54',
79 silly get     connection: 'keep-alive',
79 silly get     'x-served-by': 'cache-sjc3125-SJC',
79 silly get     'x-cache': 'HIT',
79 silly get     'x-cache-hits': '7',
79 silly get     'x-timer': 'S1456890937.041782,VS0,VE0',
79 silly get     vary: 'Accept' } ]
80 verbose etag https://registry.npmjs.org/lodash from cache
81 verbose get saving lodash to /home/nitrous/.npm/registry.npmjs.org/lodash/.cache.json
82 verbose correctMkdir /home/nitrous/.npm correctMkdir not in flight; initializing
83 silly resolveWithNewModule lodash@4.6.0 checking installable status
84 silly cache add args [ 'lodash@^4.2.1', null ]
85 verbose cache add spec lodash@^4.2.1
86 silly cache add parsed spec Result {
86 silly cache add   raw: 'lodash@^4.2.1',
86 silly cache add   scope: null,
86 silly cache add   name: 'lodash',
86 silly cache add   rawSpec: '^4.2.1',
86 silly cache add   spec: '>=4.2.1 <5.0.0',
86 silly cache add   type: 'range' }
87 silly addNamed lodash@>=4.2.1 <5.0.0
88 verbose addNamed ">=4.2.1 <5.0.0" is a valid semver range for lodash
89 silly addNameRange { name: 'lodash', range: '>=4.2.1 <5.0.0', hasData: false }
90 silly mapToRegistry name lodash
91 silly mapToRegistry using default registry
92 silly mapToRegistry registry https://registry.npmjs.org/
93 silly mapToRegistry uri https://registry.npmjs.org/lodash
94 verbose addNameRange registry:https://registry.npmjs.org/lodash not in flight; fetching
95 verbose get https://registry.npmjs.org/lodash not expired, no request
96 silly addNameRange number 2 { name: 'lodash', range: '>=4.2.1 <5.0.0', hasData: true }
97 silly addNameRange versions [ 'lodash',
97 silly addNameRange   [ '0.1.0',
97 silly addNameRange     '0.2.0',
97 silly addNameRange     '0.2.1',
97 silly addNameRange     '0.2.2',
97 silly addNameRange     '0.3.0',
97 silly addNameRange     '0.3.1',
97 silly addNameRange     '0.3.2',
97 silly addNameRange     '0.4.0',
97 silly addNameRange     '0.4.1',
97 silly addNameRange     '0.4.2',
97 silly addNameRange     '0.5.0-rc.1',
97 silly addNameRange     '0.5.0',
97 silly addNameRange     '0.5.1',
97 silly addNameRange     '0.5.2',
97 silly addNameRange     '0.6.0',
97 silly addNameRange     '0.6.1',
97 silly addNameRange     '0.7.0',
97 silly addNameRange     '0.8.0',
97 silly addNameRange     '0.8.1',
97 silly addNameRange     '0.8.2',
97 silly addNameRange     '0.9.0',
97 silly addNameRange     '0.9.1',
97 silly addNameRange     '0.9.2',
97 silly addNameRange     '0.10.0',
97 silly addNameRange     '1.0.0-rc.1',
97 silly addNameRange     '1.0.0-rc.2',
97 silly addNameRange     '1.0.0-rc.3',
97 silly addNameRange     '1.0.0',
97 silly addNameRange     '1.0.1',
97 silly addNameRange     '1.1.0',
97 silly addNameRange     '1.1.1',
97 silly addNameRange     '1.2.0',
97 silly addNameRange     '1.2.1',
97 silly addNameRange     '1.3.0',
97 silly addNameRange     '1.3.1',
97 silly addNameRange     '2.0.0',
97 silly addNameRange     '2.1.0',
97 silly addNameRange     '2.2.0',
97 silly addNameRange     '2.2.1',
97 silly addNameRange     '2.3.0',
97 silly addNameRange     '2.4.0',
97 silly addNameRange     '2.4.1',
97 silly addNameRange     '3.0.0',
97 silly addNameRange     '3.0.1',
97 silly addNameRange     '3.1.0',
97 silly addNameRange     '3.2.0',
97 silly addNameRange     '3.3.0',
97 silly addNameRange     '3.3.1',
97 silly addNameRange     '3.4.0',
97 silly addNameRange     '3.5.0',
97 silly addNameRange     '3.6.0',
97 silly addNameRange     '1.0.2',
97 silly addNameRange     '3.7.0',
97 silly addNameRange     '2.4.2',
97 silly addNameRange     '3.8.0',
97 silly addNameRange     '3.9.0',
97 silly addNameRange     '3.9.1',
97 silly addNameRange     '3.9.2',
97 silly addNameRange     '3.9.3',
97 silly addNameRange     '3.10.0',
97 silly addNameRange     '3.10.1',
97 silly addNameRange     '4.0.0',
97 silly addNameRange     '4.0.1',
97 silly addNameRange     '4.1.0',
97 silly addNameRange     '4.2.0',
97 silly addNameRange     '4.2.1',
97 silly addNameRange     '4.3.0',
97 silly addNameRange     '4.4.0',
97 silly addNameRange     '4.5.0',
97 silly addNameRange     '4.5.1',
97 silly addNameRange     '4.6.0' ] ]
98 silly addNamed lodash@4.6.0
99 verbose addNamed "4.6.0" is a plain semver version for lodash
100 silly cache afterAdd lodash@4.6.0
101 verbose afterAdd /home/nitrous/.npm/lodash/4.6.0/package/package.json not in flight; writing
102 verbose correctMkdir /home/nitrous/.npm correctMkdir not in flight; initializing
103 verbose afterAdd /home/nitrous/.npm/lodash/4.6.0/package/package.json written
104 http 304 https://registry.npmjs.org/lodash-es
105 verbose headers { date: 'Wed, 02 Mar 2016 03:55:37 GMT',
105 verbose headers   via: '1.1 varnish',
105 verbose headers   'cache-control': 'max-age=300',
105 verbose headers   etag: '"5DL0EY8MRJCXGT0HJCQEALHQX"',
105 verbose headers   age: '0',
105 verbose headers   connection: 'keep-alive',
105 verbose headers   'x-served-by': 'cache-lax1434-LAX',
105 verbose headers   'x-cache': 'HIT',
105 verbose headers   'x-cache-hits': '1',
105 verbose headers   'x-timer': 'S1456890937.062506,VS0,VE99',
105 verbose headers   vary: 'Accept' }
106 silly get cb [ 304,
106 silly get   { date: 'Wed, 02 Mar 2016 03:55:37 GMT',
106 silly get     via: '1.1 varnish',
106 silly get     'cache-control': 'max-age=300',
106 silly get     etag: '"5DL0EY8MRJCXGT0HJCQEALHQX"',
106 silly get     age: '0',
106 silly get     connection: 'keep-alive',
106 silly get     'x-served-by': 'cache-lax1434-LAX',
106 silly get     'x-cache': 'HIT',
106 silly get     'x-cache-hits': '1',
106 silly get     'x-timer': 'S1456890937.062506,VS0,VE99',
106 silly get     vary: 'Accept' } ]
107 verbose etag https://registry.npmjs.org/lodash-es from cache
108 verbose get saving lodash-es to /home/nitrous/.npm/registry.npmjs.org/lodash-es/.cache.json
109 verbose correctMkdir /home/nitrous/.npm correctMkdir not in flight; initializing
110 silly resolveWithNewModule lodash-es@4.6.0 checking installable status
111 silly cache add args [ 'lodash-es@^4.2.1', null ]
112 verbose cache add spec lodash-es@^4.2.1
113 silly cache add parsed spec Result {
113 silly cache add   raw: 'lodash-es@^4.2.1',
113 silly cache add   scope: null,
113 silly cache add   name: 'lodash-es',
113 silly cache add   rawSpec: '^4.2.1',
113 silly cache add   spec: '>=4.2.1 <5.0.0',
113 silly cache add   type: 'range' }
114 silly addNamed lodash-es@>=4.2.1 <5.0.0
115 verbose addNamed ">=4.2.1 <5.0.0" is a valid semver range for lodash-es
116 silly addNameRange { name: 'lodash-es', range: '>=4.2.1 <5.0.0', hasData: false }
117 silly mapToRegistry name lodash-es
118 silly mapToRegistry using default registry
119 silly mapToRegistry registry https://registry.npmjs.org/
120 silly mapToRegistry uri https://registry.npmjs.org/lodash-es
121 verbose addNameRange registry:https://registry.npmjs.org/lodash-es not in flight; fetching
122 verbose get https://registry.npmjs.org/lodash-es not expired, no request
123 silly addNameRange number 2 { name: 'lodash-es', range: '>=4.2.1 <5.0.0', hasData: true }
124 silly addNameRange versions [ 'lodash-es',
124 silly addNameRange   [ '3.0.0',
124 silly addNameRange     '3.0.1',
124 silly addNameRange     '3.1.0',
124 silly addNameRange     '3.2.0',
124 silly addNameRange     '3.3.0',
124 silly addNameRange     '3.3.1',
124 silly addNameRange     '3.4.0',
124 silly addNameRange     '3.5.0',
124 silly addNameRange     '3.6.0',
124 silly addNameRange     '3.7.0',
124 silly addNameRange     '3.8.0',
124 silly addNameRange     '3.9.0',
124 silly addNameRange     '3.9.2',
124 silly addNameRange     '3.9.3',
124 silly addNameRange     '3.10.0',
124 silly addNameRange     '3.10.1',
124 silly addNameRange     '4.0.0',
124 silly addNameRange     '4.0.1',
124 silly addNameRange     '4.1.0',
124 silly addNameRange     '4.2.0',
124 silly addNameRange     '4.2.1',
124 silly addNameRange     '4.3.0',
124 silly addNameRange     '4.4.0',
124 silly addNameRange     '4.5.0',
124 silly addNameRange     '4.5.1',
124 silly addNameRange     '4.6.0' ] ]
125 silly addNamed lodash-es@4.6.0
126 verbose addNamed "4.6.0" is a plain semver version for lodash-es
127 silly mapToRegistry name lodash-es
128 silly mapToRegistry using default registry
129 silly mapToRegistry registry https://registry.npmjs.org/
130 silly mapToRegistry uri https://registry.npmjs.org/lodash-es
131 verbose addRemoteTarball https://registry.npmjs.org/lodash-es/-/lodash-es-4.6.0.tgz not in flight; adding
132 verbose addRemoteTarball [ 'https://registry.npmjs.org/lodash-es/-/lodash-es-4.6.0.tgz',
132 verbose addRemoteTarball   '81d925c4062f9efabde699fb7ef38594fbc112c0' ]
133 info retry fetch attempt 1 at 3:55:37 AM
134 info attempt registry request try #1 at 3:55:37 AM
135 http fetch GET https://registry.npmjs.org/lodash-es/-/lodash-es-4.6.0.tgz
136 info retry will retry, error on last attempt: Error: socket hang up
137 info attempt registry request try #2 at 3:56:48 AM
138 http fetch GET https://registry.npmjs.org/lodash-es/-/lodash-es-4.6.0.tgz
139 http fetch 504 https://registry.npmjs.org/lodash-es/-/lodash-es-4.6.0.tgz
140 info retry will retry, error on last attempt: Error: server error 504
141 info attempt registry request try #3 at 3:58:38 AM
142 http fetch GET https://registry.npmjs.org/lodash-es/-/lodash-es-4.6.0.tgz
143 error fetch failed https://registry.npmjs.org/lodash-es/-/lodash-es-4.6.0.tgz
144 warn retry will retry, error on last attempt: Error: socket hang up
145 info retry fetch attempt 2 at 3:59:49 AM
146 info attempt registry request try #1 at 3:59:49 AM
147 http fetch GET https://registry.npmjs.org/lodash-es/-/lodash-es-4.6.0.tgz
148 http fetch 504 https://registry.npmjs.org/lodash-es/-/lodash-es-4.6.0.tgz
149 info retry will retry, error on last attempt: Error: server error 504
150 info attempt registry request try #2 at 4:00:50 AM
151 http fetch GET https://registry.npmjs.org/lodash-es/-/lodash-es-4.6.0.tgz
152 http fetch 504 https://registry.npmjs.org/lodash-es/-/lodash-es-4.6.0.tgz
153 info retry will retry, error on last attempt: Error: server error 504
154 info attempt registry request try #3 at 4:02:40 AM
155 http fetch GET https://registry.npmjs.org/lodash-es/-/lodash-es-4.6.0.tgz
156 http fetch 404 https://registry.npmjs.org/lodash-es/-/lodash-es-4.6.0.tgz
157 error fetch failed https://registry.npmjs.org/lodash-es/-/lodash-es-4.6.0.tgz
158 warn retry will retry, error on last attempt: Error: fetch failed with status code 404
159 info retry fetch attempt 3 at 4:03:41 AM
160 info attempt registry request try #1 at 4:03:41 AM
161 http fetch GET https://registry.npmjs.org/lodash-es/-/lodash-es-4.6.0.tgz
162 http fetch 404 https://registry.npmjs.org/lodash-es/-/lodash-es-4.6.0.tgz
163 error fetch failed https://registry.npmjs.org/lodash-es/-/lodash-es-4.6.0.tgz
164 silly rollbackFailedOptional Starting
165 silly rollbackFailedOptional Finishing
166 silly runTopLevelLifecycles Starting
167 silly runTopLevelLifecycles Finishing
168 silly install printInstalled
169 verbose stack Error: fetch failed with status code 404
169 verbose stack     at Request.<anonymous> (/usr/local/opt/nvm/versions/node/v5.6.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/fetch.js:51:14)
169 verbose stack     at emitOne (events.js:90:13)
169 verbose stack     at Request.emit (events.js:182:7)
169 verbose stack     at Request.onRequestResponse (/usr/local/opt/nvm/versions/node/v5.6.0/lib/node_modules/npm/node_modules/request/request.js:951:10)
169 verbose stack     at emitOne (events.js:90:13)
169 verbose stack     at ClientRequest.emit (events.js:182:7)
169 verbose stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:425:21)
169 verbose stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:89:23)
169 verbose stack     at TLSSocket.socketOnData (_http_client.js:315:20)
169 verbose stack     at emitOne (events.js:90:13)
170 verbose cwd /home/nitrous/code/holigazing
171 error Linux 4.2.0-18-generic
172 error argv "/usr/local/opt/nvm/versions/node/v5.6.0/bin/node" "/usr/local/opt/nvm/versions/node/v5.6.0/bin/npm" "install" "--save-dev" "redux"
173 error node v5.6.0
174 error npm  v3.6.0
175 error fetch failed with status code 404
176 error If you need help, you may report this error at:
176 error     <https://github.com/npm/npm/issues>
177 verbose exit [ 1, true ]

**Comment by jgraham-plm** [comment]
I'm getting a similar 404 on [pkginfo](https://www.npmjs.com/package/pkginfo):

```
npm ERR! fetch failed https://registry.npmjs.org/pkginfo/-/pkginfo-0.4.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
```

**Comment by jessehattabaugh** [comment]
works now!
