### ISSUE TITLE
Addition to link docs page - how to unlink/uninstall

### ISSUE THREAD

**Issue by jolyonruss** [npm/npm#11745]
I've just been through the process of linking my own module in another project, then I wanted to unlink it and start using a version hosted on Github, but there's nothing on this docs page https://docs.npmjs.com/cli/link to explain how to unlink.

I found this SO answer which lists a few options http://stackoverflow.com/a/19094631/313990

**Comment by jgravois** [comment]
`unlink` is just a documented alias of [`uninstall`](https://docs.npmjs.com/cli/uninstall).

the information is currently hard to find, so additional pages for aliases in the toc that redirect the user to the appropriate page thats already present would definitely be helpful.
