### ISSUE TITLE
fetch failed 503 (Windows)

### ISSUE THREAD

**Issue by duckinator** [npm/npm#11743]
`node -v`: v4.3.1
`npm -v`: 2.14.12
OS: Windows 8.1, 64bit

I'm getting the following from an `npm install`: `fetch failed with status code 503`.

Debug logs: https://gist.github.com/duckinator/d77681aaf4047ff80fb1
Codebase: https://gitlab.com/duckinator/marie.codes

This does not occur on my Linux system, using the same node and npm versions.

**Comment by othiym23** [comment]
We're having a small infrastructural issue that the registry team is currently [working to resolve](http://status.npmjs.org/incidents/9zwnxr4n3bpl). Thanks for the heads up, and we hope to have things back to normal very soon!

**Comment by duckinator** [comment]
Looks like it's fixed!
