### ISSUE TITLE
SELF_SIGNED_CERT_IN_CHAIN error installing Vorlon.js

### ISSUE THREAD

**Issue by cminarik** [npm/npm#11740]
I was trying to install Vorlon.js, but I got the error message "SELF_SIGNED_CERT_IN_CHAIN".  I attached the log file.
[npm-debug.zip](https://github.com/npm/npm/files/153660/npm-debug.zip)

What am I supposed to do about it?  TIA.

**Comment by pedzed** [comment]
Why did you zip it?

> 0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'i',
1 verbose cli   '-g',
1 verbose cli   'vorlon' ]
2 info using npm@2.14.12
3 info using node@v4.3.1
4 verbose install initial load of C:\Users\minarch\AppData\Roaming\npm\package.json
5 verbose readDependencies loading dependencies from C:\Users\minarch\AppData\Roaming\npm\package.json
6 silly cache add args [ 'vorlon', null ]
7 verbose cache add spec vorlon
8 silly cache add parsed spec Result {
8 silly cache add   raw: 'vorlon',
8 silly cache add   scope: null,
8 silly cache add   name: 'vorlon',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: 'latest',
8 silly cache add   type: 'tag' }
9 silly addNamed vorlon@latest
10 verbose addNamed "latest" is being treated as a dist-tag for vorlon
11 info addNameTag [ 'vorlon', 'latest' ]
12 silly mapToRegistry name vorlon
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/vorlon
16 verbose addNameTag registry:https://registry.npmjs.org/vorlon not in flight; fetching
17 verbose request uri https://registry.npmjs.org/vorlon
18 verbose request no auth needed
19 info attempt registry request try #1 at 4:26:41 PM
20 verbose request id 5c70e02f536c08c6
21 http request GET https://registry.npmjs.org/vorlon
22 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
23 info attempt registry request try #2 at 4:26:52 PM
24 http request GET https://registry.npmjs.org/vorlon
25 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
26 info attempt registry request try #3 at 4:27:52 PM
27 http request GET https://registry.npmjs.org/vorlon
28 verbose stack Error: self signed certificate in certificate chain
28 verbose stack     at Error (native)
28 verbose stack     at TLSSocket.<anonymous> (_tls_wrap.js:1016:38)
28 verbose stack     at emitNone (events.js:67:13)
28 verbose stack     at TLSSocket.emit (events.js:166:7)
28 verbose stack     at TLSSocket._finishInit (_tls_wrap.js:585:8)
29 verbose cwd C:\Users\minarch
30 error Windows_NT 6.1.7601
31 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "-g" "vorlon"
32 error node v4.3.1
33 error npm  v2.14.12
34 error code SELF_SIGNED_CERT_IN_CHAIN
35 error self signed certificate in certificate chain
36 error If you need help, you may report this error at:
36 error     <https://github.com/npm/npm/issues>
37 verbose exit [ 1, true ]

Your npm version is `2.14.12`. Try updating it?
```
npm -g install npm
```
If that fails, just reinstall nodejs. https://nodejs.org/en/download
