### ISSUE TITLE
The dependency tree problem

### ISSUE THREAD

**Issue by arhangelsoft** [npm/npm#11747]
The problem:
Each dependency it's a package, that 
....have it's own dependencies in separated "node_modules" folder,
each dependency  in that folder....

That recursion may be deeper than hell, and that fact is sucks. Also it makes some problem for file system whitch disallow create long path or even more, allow that, but disallow remove it :)

Another idea of packege dependency tree:
List them in single folder, separating by version e.g.
<project>/node_modules/<dependency_package>/version

and no more that hell:
project/node_modules/dependency_package/node_modules/dependency_package/node_modules/dependency_package/
node_modules/dependency_package/
node_modules/dependency_package/

each dependency_package have it's own dependencies, but now all of them stored in folder, x2 upper of current dependency_package folder:
If package/npm looking for packages, just 
make up twice (make cd .. ..) from project/node_modules/dependency_package/version folder, to root directory of all dep modules project/node_modules/ and look next for needed of place here new dependency, and in it folder create folder with version of dep.

Tree architecture is good for NPM's database that's looks like JSON, but not good for any file-system, which can have some limits for depth of folders tree in some situations this can make development is inpossible with npm. Even more:
Some packages on different levels in project dependency three uses the same package with the same version, and we have duplicate of the same resources, because npm don't know, that this package already have in dependency tree, and just unpack chached version and make copy of it. Not good implementation as I think.

What you think?

**Comment by KenanY** [comment]
Hello @arhangelsoft! Does https://github.com/nodejs/NG/issues/28 look like what you are proposing?

**Comment by arhangelsoft** [comment]
@KenanY Yes, it is.

**Comment by ashleygwilliams** [comment]
in order for this change to even be plausible on npm's side, the node.js module loader would have to change. https://github.com/nodejs/NG/issues/28 seems like a good place to discuss that! closing.
