### ISSUE TITLE
NPM error on ubuntu 14.04.2 LTS Desktop 64bit

### ISSUE THREAD

**Issue by hokyoon** [npm/npm#11742]
Log file attached.

[npm-debug.txt](https://github.com/npm/npm/files/153866/npm-debug.txt)

**Comment by KenanY** [comment]
@hokyoon Are you trying to install `filterizr` in a directory which already contains the source code for the module?

**Comment by KenanY** [comment]
@hokyoon Are you still experiencing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
