### ISSUE TITLE
cannot install aframe with npm

### ISSUE THREAD

**Issue by aminesysy** [npm/npm#11756]

**Comment by KenanY** [comment]
Hello @aminesysy! There is currently not enough information in this blank issue for me to help you. Is there a `npm-debug.log` file generated which you can upload to [gist.github.com](https://gist.github.com/) and link here?

**Comment by pedzed** [comment]
@KenanY There are almost 2,000 issues open. Just close the issue.

**Comment by KenanY** [comment]
@pedzed I don't have the GitHub permissions necessary to do that.
