### ISSUE TITLE
v3.3.12 - Tab completion of directories as -- arguments to scripts fails in ZSH

### ISSUE THREAD

**Issue by bradbarrow** [npm/npm#11758]
Given an installation of `npm v3.3.12` running in `zsh` on `OSX 10.10.5`

When passing an argument via `--` to an `npm` task, tab completion does not work as a method of auto completing directory paths:

**Expected:**

```
$> npm run my:script:here -- path/to/fi[TAB]
$> npm run my:script:here -- path/to/file.js
```

**Actual:**

```
$> npm run my:script:here -- path/to/fi[TAB]
$> npm run my:script:here -- path/to/fi
```

The completion does not work at all, no errors are shown.
I have run the recommended `npm completion` commands which resolved an existing zsh issue (`egrep`) but it hasn't resolved this.

**Comment by lencioni** [comment]
Not sure if this is helpful for this issue, but I believe that the zsh completion is wired up right here: https://github.com/zsh-users/zsh/blob/fd144877/Completion/Unix/Command/_npm
