### ISSUE TITLE
Some errors while executing a setup script

### ISSUE THREAD

**Issue by Pleite4d** [npm/npm#11759]
Hey there,

after some PC problems i had to reinstall a working vm and now i have problems while executing a setup script on the VM. I think it depends on nodejs but im not sure. I did the same procedure without errors some weeks ago.

I got two error during "Install npm modules", that's the reason to post it here. I didn't find some information about the error codes. Maybe you have a tip to solve my problem.

Thx.

`npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! path ../rimraf/bin.js
npm ERR! code EPROTO
npm ERR! errno -71

npm ERR! EPROTO, symlink '../rimraf/bin.js'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! path npm-debug.log.eafb6ba02d87a7ef52f2ae4f5530e874
npm ERR! code ETXTBSY
npm ERR! errno -26

npm ERR! ETXTBSY, rename 'npm-debug.log.eafb6ba02d87a7ef52f2ae4f5530e874'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /data/shop/development/current/npm-debug.log`

Result of npm-debug.log

`0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'spy-setup',
1 verbose cli   'all' ]
2 info using npm@3.6.0
3 info using node@v5.6.0
4 verbose run-script [ 'prespy-setup', 'spy-setup', 'postspy-setup' ]
5 info lifecycle yves_zed@0.3.0~prespy-setup: yves_zed@0.3.0
6 silly lifecycle yves_zed@0.3.0~prespy-setup: no script for prespy-setup, continuing
7 info lifecycle yves_zed@0.3.0~spy-setup: yves_zed@0.3.0
8 verbose lifecycle yves_zed@0.3.0~spy-setup: unsafe-perm in lifecycle true
9 verbose lifecycle yves_zed@0.3.0~spy-setup: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/data/shop/development/current/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/games:/home/vagrant/.composer/vendor/bin
10 verbose lifecycle yves_zed@0.3.0~spy-setup: CWD: /data/shop/development/current
11 silly lifecycle yves_zed@0.3.0~spy-setup: Args: [ '-c',
11 silly lifecycle   'npm install && npm run spy-yves && npm run spy-zed "all"' ]
12 silly lifecycle yves_zed@0.3.0~spy-setup: Returned: code: 185  signal: null
13 info lifecycle yves_zed@0.3.0~spy-setup: Failed to exec spy-setup script
14 verbose stack Error: yves_zed@0.3.0 spy-setup: `npm install && npm run spy-yves && npm run spy-zed "all"`
14 verbose stack Exit status 185
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:827:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid yves_zed@0.3.0
16 verbose cwd /data/shop/development/current
17 error Linux 3.16.0-4-amd64
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "spy-setup" "all"
19 error node v5.6.0
20 error npm  v3.6.0
21 error code ELIFECYCLE
22 error yves_zed@0.3.0 spy-setup: `npm install && npm run spy-yves && npm run spy-zed "all"`
22 error Exit status 185
23 error Failed at the yves_zed@0.3.0 spy-setup script 'npm install && npm run spy-yves && npm run spy-zed "all"'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the yves_zed package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm install && npm run spy-yves && npm run spy-zed "all"
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs yves_zed
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls yves_zed
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]`

**Comment by KenanY** [comment]
Hello @Pleite4d! Looks like your VM does not support symbolic links. Have you tried using the
[`--no-bin-links`](https://docs.npmjs.com/misc/config#bin-links) flag?

**Comment by KenanY** [comment]
@Pleite4d It has been quite a while with no response from you... are you still experiencing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
