### ISSUE TITLE
manipulation of button styles in Bootbox.

### ISSUE THREAD

**Issue by dave-cheever** [npm/npm#11754]
this is my code, is it possible to edit the button styles from bootbox?  

`self.saveApprovals = function () {
                bootbox.dialog({
                    message: "Are you sure you want to save these changes? All requests submitted before you hit save will follow the old setting.",
                    title: "",
                    buttons: {
                        success: {
                            label: "Save",
                            className: "btn-success",
                            callback: function () {
                                SaveAttendance();
                            }
                        },
                        main: {
                            label: "or Cancel",
                            className: "btn-primary",
                            callback: function () {

                            }
                        }
                    }
                });
            }`

**Comment by KenanY** [comment]
Hello @dave-cheever! Your question does not seem to involve `npm` at all. I would suggest that you take this question to somewhere like [here](https://github.com/makeusabrew/bootbox/issues) or StackOverflow.
