### ISSUE TITLE
cant install babel-cli

### ISSUE THREAD

**Issue by vickenliu** [npm/npm#11767]
i can't install babel-cli, followed the setup online, it won't work anyway. please have a look of the npm-debug.log
here is the link https://gist.github.com/vickenliu/68bfe3471986a230b7d2

thanks.

**Comment by KenanY** [comment]
https://github.com/npm/npm/issues/10333#issuecomment-192287386

**Comment by vickenliu** [comment]
it works with @KenanY 's comment
