### ISSUE TITLE
Intermittent npm ERR! code ECONNRESET issue.

### ISSUE THREAD

**Issue by sharmasu** [npm/npm#11770]
When i run npm install on my machine, i get above message. I am not behind proxy and I have windows 7 machine. Its a hit or miss. Some times it works and other times it won't. The problem is that we use npm to install some gulp and bower and then some other packages that are defined in our package.json. Even if i ignore the errors and keep trying, once the install is successful, i don't get all the dependencies for the packages in package.json. I have tried lots of solutions that I have come across during my research on internet like setting alternate registry and clearing the cache.

Here is the log from when installing npm
npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read

when it succeed, one of the packages in package.json file (post-css) does not download all the dependencies and i get and error while running my gulpfile.js file, here is that error :

Failed to load "<solutionDir>\gulpfile.js"...
module.js:340
    throw err;
    ^

Error: Cannot find module '../../plugins/removeXMLProcInst'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at "<solutionDir>\node_modules\gulp-cssnano\node_modules\cssnano\node_modules\postcss-svgo\node_modules\svgo\lib\svgo\config.js:95:33
    at Array.map (native)
    at preparePluginsArray (<solutionDir>\node_modules\gulp-cssnano\node_modules\cssnano\node_modules\postcss-svgo\node_modules\svgo\lib\svgo\config.js:60:20)
    at module.exports (<solutionDir>\node_modules\gulp-cssnano\node_modules\cssnano\node_modules\postcss-svgo\node_modules\svgo\lib\svgo\config.js:28:28)
    at new module.exports (<solutionDir>\node_modules\gulp-cssnano\node_modules\cssnano\node_modules\postcss-svgo\node_modules\svgo\lib\svgo.js:21:19)
    at <solutionDir>\node_modules\gulp-cssnano\node_modules\cssnano\node_modules\postcss-svgo\dist\index.js:73:16

Failed to load "<solutionDir>\gulpfile.js"...
module.js:340
    throw err;
    ^

Thanks

**Comment by chris-brown** [comment]
me too i get this when i run an npm install on the [Ghost](https://github.com/TryGhost/Ghost) project

**Comment by chris-brown** [comment]
@sharmasu what console are you running the command on. Mine was powershell but i switched to [bash](http://ftp.gnu.org/gnu/bash/) and it now works. do a `git config -l' and look for any urls prefixed with http. it might be trying to clone `removeXMLProcInst` for instance and unable because of authentication issue.

**Comment by ojongerius** [comment]
This issue probably timed out but for the record: upgrading to a more recent version of npm and or node will most likely have fixed this issue. See https://github.com/npm/registry/issues/10
