### ISSUE TITLE
Cannot read property 'gulp' of undefined

### ISSUE THREAD

**Issue by edubuc** [npm/npm#11780]
sudo npm install jquery --save
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "jquery" "--save"
npm ERR! node v5.7.0
npm ERR! npm  v3.6.0

npm ERR! Cannot read property 'gulp' of undefined
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/edubuc/Code/xxx/xxx/npm-debug.log

**Comment by pedzed** [comment]
Try the command again. It's weird that it requires gulp(?)

If it still fails, try:
```
npm -g install gulp
```
