### ISSUE TITLE
Run single test

### ISSUE THREAD

**Issue by doug-wade** [npm/npm#11788]
Currently, if you want to do TDD/BDD, you have to wait ~6 minutes between cycles to allow all 3000+ tests to run.  It'd be amazing/fantastic/wow if instead I could run something like `node cli.js test version-no-tags` and only run the tests defined in test/tap/version-no-tags

**Comment by KenanY** [comment]
@doug-wade Is this regarding `npm`'s test suite specifically? If so, you can already just do this:

```
node test/tap/version-no-tags.js
```

**Comment by othiym23** [comment]
Also, `npm run tap -- test/tap/version-no-tags.js` will also work. `npm run` with no additional arguments in the project repo's root will show you how the test commands are wired together. Thanks for your time!

**Comment by doug-wade** [comment]
Thanks @othiym23 @KenanY!  Would you take a PR to add something to that effect to CONTRIBUTING.md?
