### ISSUE TITLE
Cant install module in iobroker

### ISSUE THREAD

**Issue by aski71** [npm/npm#11793]
Hi, 

I am getting this:

$ ./iobroker add hm-rega
host.thebigone.fritz.box install adapter hm-rega
npm install --production --prefix "/Users/alex/iobroker/node_modules/iobroker.hm-rega" (System call)
npm
 ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--production" "--prefix" "/Users/alex/iobroker/node_modules/iobroker.hm-rega"
npm ERR! node v5.7.1npm ERR! npm  v3.6.0

npm ERR! Cannot read property 'target' of nullnpm ERR! 
npm ERR!
 If you need help, you may report this error at:npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:npm ERR!     /Users/alex/npm-debug.log

Cannot install iobroker.hm-rega: 1
ERROR: process exited with code 25

What do I do?

**Comment by whmountains** [comment]
This looks like it's a problem with iobroker itself.  You'll probably get more knowledgeable help if you report your problem at https://github.com/ioBroker/ioBroker.
