### ISSUE TITLE
Had a system crash and home bridge stopped functioning - error on re-install

### ISSUE THREAD

**Issue by AtSomePoint** [npm/npm#11795]
I have been running home bridge through npm install without issue.  I have a power outage which crashed the server, on re-run, home bridge would not run.  Updated npm and nodejs but still get errors when trying to re-install.
Scotts-MacBook-Pro:~ scottweidig$ sudo npm install -g homebridge
npm WARN addRemoteGit git://github.com/KhaosT/ed25519.git resetting remote /Users/scottweidig/.npm/_git-remotes/git-github-com-KhaosT-ed25519-git-d8bdee1d because of error: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
npm WARN addRemoteGit git://github.com/KhaosT/node_mdns.git resetting remote /Users/scottweidig/.npm/_git-remotes/git-github-com-KhaosT-node-mdns-git-fa6757ad because of error: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
npm WARN addRemoteGit git://github.com/KhaosT/node-curve25519.git resetting remote /Users/scottweidig/.npm/_git-remotes/git-github-com-KhaosT-node-curve25519-git-750fb09d because of error: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
npm WARN addRemoteGit git://github.com/KhaosT/node-srp.git resetting remote /Users/scottweidig/.npm/_git-remotes/git-github-com-KhaosT-node-srp-git-b14235ae because of error: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
npm ERR! git clone --template=/Users/scottweidig/.npm/_git-remotes/_templates --mirror git://github.com/KhaosT/node_mdns.git /Users/scottweidig/.npm/_git-remotes/git-github-com-KhaosT-node-mdns-git-fa6757ad: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
npm ERR! git clone --template=/Users/scottweidig/.npm/_git-remotes/_templates --mirror git://github.com/KhaosT/ed25519.git /Users/scottweidig/.npm/_git-remotes/git-github-com-KhaosT-ed25519-git-d8bdee1d: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
npm ERR! git clone --template=/Users/scottweidig/.npm/_git-remotes/_templates --mirror git://github.com/KhaosT/node-curve25519.git /Users/scottweidig/.npm/_git-remotes/git-github-com-KhaosT-node-curve25519-git-750fb09d: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
npm ERR! git clone --template=/Users/scottweidig/.npm/_git-remotes/_templates --mirror git://github.com/KhaosT/node-srp.git /Users/scottweidig/.npm/_git-remotes/git-github-com-KhaosT-node-srp-git-b14235ae: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "homebridge"
npm ERR! node v4.3.2
npm ERR! npm  v2.14.12
npm ERR! code 1

npm ERR! Command failed: git clone --template=/Users/scottweidig/.npm/_git-remotes/_templates --mirror git://github.com/KhaosT/node_mdns.git /Users/scottweidig/.npm/_git-remotes/git-github-com-KhaosT-node-mdns-git-fa6757ad
npm ERR! xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/scottweidig/npm-debug.log

Looking for help on getting home bridge to install

**Comment by whmountains** [comment]
Try re-installing the apple command line tools with `sudo xcode-select --reset && sudo xcode-select --install`

**Comment by AtSomePoint** [comment]
Thank you! That did it.  I was able to re-install. After that I needed to delete the persist file, edit the config file to provide a new bridge name, username, and pair code... after that, all was about to be recognized!

Appreciate the help!
