### ISSUE TITLE
npm start

### ISSUE THREAD

**Issue by mkalanj** [npm/npm#11797]
![lalla](https://cloud.githubusercontent.com/assets/17614124/13557246/6d0c8814-e3ec-11e5-91e3-1306698202ce.JPG)

what this means

**Comment by whmountains** [comment]
What do you get when you run `type package.json`?

**Comment by akenn** [comment]
Do you have a `start` script defined in `package.json` or a file called `server.js` in that directory? https://github.com/npm/npm/blob/d623783488aa5ee22fd3498cbffb4819cbd36f47/doc/cli/npm-start.md#description

**Comment by KenanY** [comment]
@mkalanj Are you still seeing this issue?

**Comment by mkalanj** [comment]
No? Thank everyone's for helping.. i fix that problem, now i still work on my project @KenanY, @akenn, @whmountains

**Comment by KenanY** [comment]
@mkalanj Thanks for following up.
