### ISSUE TITLE
when installing packages through npm in window 8.1 then I got 

### ISSUE THREAD

**Issue by srawan** [npm/npm#11792]
npm WARN package.json angular2demo@1.0.0 No description
npm WARN package.json angular2demo@1.0.0 No repository field.
npm WARN package.json angular2demo@1.0.0 No README data
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\node\node.exe" "C:\node\node_modules\npm\bin\npm-cli.js" "insta
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12

npm ERR! error:0906D06C:PEM routines:PEM_read_bio:no start line
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\node\node.exe" "C:\node\node_modules\npm\bin\npm-cli.js" "insta
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12

npm ERR! error:0906D06C:PEM routines:PEM_read_bio:no start line
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\node\node.exe" "C:\node\node_modules\npm\bin\npm-cli.js" "insta
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12

npm ERR! error:0906D06C:PEM routines:PEM_read_bio:no start line
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\node\node.exe" "C:\node\node_modules\npm\bin\npm-cli.js" "insta
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12

npm ERR! error:0906D06C:PEM routines:PEM_read_bio:no start line
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\node\node.exe" "C:\node\node_modules\npm\bin\npm-cli.js" "insta
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12

npm ERR! error:0906D06C:PEM routines:PEM_read_bio:no start line
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\node\node.exe" "C:\node\node_modules\npm\bin\npm-cli.js" "insta
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12

npm ERR! error:0906D06C:PEM routines:PEM_read_bio:no start line
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\node\node.exe" "C:\node\node_modules\npm\bin\npm-cli.js" "insta
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12

npm ERR! error:0906D06C:PEM routines:PEM_read_bio:no start line
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     F:\angular2demo\npm-debug.log

**Comment by pedzed** [comment]
Read the first three lines.
> npm WARN package.json angular2demo@1.0.0 No description
> npm WARN package.json angular2demo@1.0.0 No repository field.
> npm WARN package.json angular2demo@1.0.0 No README data

Try `npm init`.
