### ISSUE TITLE
what is -g with npm ?

### ISSUE THREAD

**Issue by flik** [npm/npm#11799]
npm -help is not showing any detail about -g 
Can you tell me some detail about this ?

**Comment by sheepsteak** [comment]
It installs packages globally. Some info here - https://docs.npmjs.com/getting-started/installing-npm-packages-globally

**Comment by flik** [comment]
You are right. I can ask detail about this from any forum but My issue was : Why this switch is not describing in npm -help ?

**Comment by sheepsteak** [comment]
If you do `npm help install` there is one line quite far down where it describes the arguments:
> The -g or --global argument will cause npm to install the package globally rather than locally.  See npm help 5 npm-folders.

**Comment by flik** [comment]
ok. thanks

**Comment by kasicka** [comment]
I'd still have to google this (and many other things) if I were using npm in docker container
