### ISSUE TITLE
Errors while running npm install -g yo

### ISSUE THREAD

**Issue by sbelvadi** [npm/npm#11806]
Getting permission denied errors while running npm install -g yo
1. I downloaded Node.js for Mac and installed it - as myself not root.
2. After this I tried npm install -g yo - as myself not root.
Error says it cannot write to /usr/local/lib/node_modules
This folder is owned by root. 
Can I not install the above as myself.

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "yo"
npm ERR! node v5.7.1
npm ERR! npm  v3.6.0
npm ERR! path /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, access '/usr/local/lib/node_modules']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "yo"
npm ERR! node v5.7.1
npm ERR! npm  v3.6.0
npm ERR! path npm-debug.log.2742521777
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall open

npm ERR! Error: EACCES: permission denied, open 'npm-debug.log.2742521777'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, open 'npm-debug.log.2742521777']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'open',
npm ERR!   path: 'npm-debug.log.2742521777' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/npm-debug.log

**Comment by doug-wade** [comment]
Check the docs: https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by KenanY** [comment]
Closing as abandoned/resolved. Can reopen if this is still an issue.
