### ISSUE TITLE
npm view can return non-compliant JSON

### ISSUE THREAD

**Issue by dfabulich** [npm/npm#11807]
```
$ npm --version
3.8.0
$ npm view newrelic@1.24.0 dependencies

{ 'concat-stream': '^1.5.0',
  'https-proxy-agent': '^0.3.5',
  'json-stringify-safe': '^5.0.0',
  'readable-stream': '^1.1.13',
  semver: '^4.2.0',
  yakaa: '^1.0.1' }
```

Apostrophes aren't valid JSON; unquoted key names are definitely not valid JSON. This is annoying, because Python has no built-in module that can handle lazy JSON like this.

**Comment by othiym23** [comment]
It's not JSON at all, lazy or otherwise. ;) It's the default output of `util.inspect` (which in many cases is far more readable for humans). To get JSON out of `npm view`, use `npm view --json`, which is guaranteed to be compliant JSON. Thanks for your time!
