### ISSUE TITLE
npm ERR! Command failed: fatal: Authentication failed npm

### ISSUE THREAD

**Issue by frank-simone** [npm/npm#11803]
link to the log file
https://javabuild.factset.com/jenkins/job/CoMA/job/news_alerting_options/ws/npm-debug.log

My build failed in Jenkins, see the link below for the Jenkins build
https://javabuild.factset.com/jenkins/job/CoMA/job/news_alerting_options/22/

**Comment by doug-wade** [comment]
The link to the log file is unreachable -- Chrome tells me 

```
This site can’t be reached

javabuild.factset.com’s server DNS address could not be found.
DNS_PROBE_FINISHED_NXDOMAIN

```

Add it to a paste bin that is publicly available, like http://www.pastebucket.com/.

Also fair warning: this is unlikely to be a problem with `npm`, and likely to be a problem with your Jenkins set up.
