### ISSUE TITLE
npm view --json returns non-json when there are multiple versions

### ISSUE THREAD

**Issue by dfabulich** [npm/npm#11808]
```
$ npm --version
3.8.1
$ npm view --json npm@^3.8.0 version
undefined@3.8.0 "3.8.0"
undefined@3.8.1 "3.8.1"
```

I don't know what that format is; it's not JSON.

**Comment by watilde** [comment]
Hi! Unfortunately it's a typo. You need to type "version**s**" like the following:
```
$ npm view --json npm@^3.8.0 versions
```

Here is a docs for it:
https://github.com/npm/npm/blob/master/doc/cli/npm-view.md#description

**Comment by dfabulich** [comment]
No, that's not correct. `npm view --json npm@^3.8.0 versions` does not print out valid JSON; it prints out:

```
undefined@3.8.0
[
  "1.1.25",
  "1.1.70",
  "1.1.71",
  ...
]
undefined@3.8.1
[
  "1.1.25",
  "1.1.70",
  "1.1.71",
  ...
]
```

That's not valid JSON either. It's two JSON blobs embedded in a newline-delimited non-standard format.
