### ISSUE TITLE
I use the "npm start" executed "GitHub-Pages" project, an error occurred ,please help

### ISSUE THREAD

**Issue by WilldNY** [npm/npm#11809]
HI,I was troubled for a long time this issue,

root@a-virtual-machine:/data/proj/GitLab-Pages# npm start

> GitLab-Pages@0.1.0 start /data/proj/GitLab-Pages
> node ./bin/www

module.js:327
    throw err;
    ^

Error: Cannot find module '../build/Debug/nodegit.node'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/data/proj/GitLab-Pages/node_modules/nodegit/lib/nodegit.js:16:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.3.2
npm ERR! npm  v3.8.0
npm ERR! code ELIFECYCLE
npm ERR! GitLab-Pages@0.1.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the GitLab-Pages@0.1.0 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the GitLab-Pages package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs GitLab-Pages
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls GitLab-Pages
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /data/proj/GitLab-Pages/npm-debug.log

But I can not find "Debug" directory!!!!!    nodejs version is the problem? or npm version?

**Comment by KenanY** [comment]
@WilldNY Are you still seeing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
