### ISSUE TITLE
Error while installing appium

### ISSUE THREAD

**Issue by siva2503** [npm/npm#11816]
I got the below error when i tried to install appium on my ubuntu machine.

please advise.

command used : sudo npm install -g appium

sh: 1: node: not found
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! Error: ENOENT, chown '/usr/local/lib/node_modules/appium/node_modules/lodash/internal/createPartial.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Linux 3.16.0-57-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "appium"
npm ERR! cwd /home/networktest
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /usr/local/lib/node_modules/appium/node_modules/lodash/internal/createPartial.js
npm ERR! fstream_path /usr/local/lib/node_modules/appium/node_modules/lodash/internal/createPartial.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! fstream_finish_call chown
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:305:19
npm ERR! fstream_stack /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! error rolling back Error: ENOTEMPTY, rmdir '/usr/local/lib/node_modules/appium/node_modules/core-js/library/fn/reflect'
npm ERR! error rolling back  appium@1.5.0 { [Error: ENOTEMPTY, rmdir '/usr/local/lib/node_modules/appium/node_modules/core-js/library/fn/reflect']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/appium/node_modules/core-js/library/fn/reflect' }
npm ERR! weird error 127
npm ERR! Error: ENOENT, open '/usr/local/lib/node_modules/appium/node_modules/winston/node_modules/colors/lib/extendStringPrototype.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Linux 3.16.0-57-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "appium"
npm ERR! cwd /home/networktest
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /usr/local/lib/node_modules/appium/node_modules/winston/node_modules/colors/lib/extendStringPrototype.js
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! Error: ENOENT, open '/home/networktest/tmp/npm-9132-OZORowo4/1457451735820-0.5522692161612213/package/_getView.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Linux 3.16.0-57-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "appium"
npm ERR! cwd /home/networktest
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /home/networktest/tmp/npm-9132-OZORowo4/1457451735820-0.5522692161612213/package/_getView.js
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! EEXIST, mkdir '/home/networktest/tmp/npm-9132-OZORowo4/1457451737270-0.03963322890922427/package/es6'
File exists: /home/networktest/tmp/npm-9132-OZORowo4/1457451737270-0.03963322890922427/package/es6
Move it away, and try again. 

npm ERR! System Linux 3.16.0-57-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "appium"
npm ERR! cwd /home/networktest
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /home/networktest/tmp/npm-9132-OZORowo4/1457451737270-0.03963322890922427/package/es6
npm ERR! fstream_path /home/networktest/tmp/npm-9132-OZORowo4/1457451737270-0.03963322890922427/package/es6/promise.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code EEXIST
npm ERR! errno 47
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:171:23
npm ERR! fstream_stack /usr/lib/nodejs/mkdirp/index.js:37:53
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/build/test/e2e/testapp/location-specs.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Linux 3.16.0-57-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "appium"
npm ERR! cwd /home/networktest
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/build/test/e2e/testapp/location-specs.js
npm ERR! fstream_path /usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/build/test/e2e/testapp/location-specs.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/home/networktest/tmp/npm-9132-OZORowo4/1457451738473-0.025441678939387202/package/js/release/context.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Linux 3.16.0-57-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "appium"
npm ERR! cwd /home/networktest
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /home/networktest/tmp/npm-9132-OZORowo4/1457451738473-0.025441678939387202/package/js/release/context.js
npm ERR! fstream_path /home/networktest/tmp/npm-9132-OZORowo4/1457451738473-0.025441678939387202/package/js/release/context.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! tar pack Error reading /home/networktest/tmp/npm-9132-OZORowo4/1457451735570-0.8612059529405087/package
npm ERR! tar pack Error reading /home/networktest/tmp/npm-9132-OZORowo4/1457451737269-0.46498313662596047/package
npm ERR! addLocalDirectory Could not pack "/home/networktest/tmp/npm-9132-OZORowo4/1457451735570-0.8612059529405087/package" to "/home/networktest/.npm/babel-runtime/5.8.20/package.tgz"
npm ERR! addLocalDirectory Could not pack "/home/networktest/tmp/npm-9132-OZORowo4/1457451737269-0.46498313662596047/package" to "/home/networktest/.npm/babel-runtime/5.5.5/package.tgz"
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/appium/node_modules/winston/node_modules/async/README.md'
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Linux 3.16.0-57-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "appium"
npm ERR! cwd /home/networktest
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /usr/local/lib/node_modules/appium/node_modules/winston/node_modules/async/README.md
npm ERR! fstream_path /usr/local/lib/node_modules/appium/node_modules/winston/node_modules/async/README.md
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/appium/node_modules/date-utils/doc/styles/site.amelia.css'
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Linux 3.16.0-57-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "appium"
npm ERR! cwd /home/networktest
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /usr/local/lib/node_modules/appium/node_modules/date-utils/doc/styles/site.amelia.css
npm ERR! fstream_path /usr/local/lib/node_modules/appium/node_modules/date-utils/doc/styles/site.amelia.css
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd4/TestApp.app.dSYM/Contents/Resources/DWARF/TestApp'
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Linux 3.16.0-57-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "appium"
npm ERR! cwd /home/networktest
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /usr/local/lib/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd4/TestApp.app.dSYM/Contents/Resources/DWARF/TestApp
npm ERR! fstream_path /usr/local/lib/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd4/TestApp.app.dSYM/Contents/Resources/DWARF/TestApp
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/appium/node_modules/appium-atoms/atoms/type.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Linux 3.16.0-57-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "appium"
npm ERR! cwd /home/networktest
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /usr/local/lib/node_modules/appium/node_modules/appium-atoms/atoms/type.js
npm ERR! fstream_path /usr/local/lib/node_modules/appium/node_modules/appium-atoms/atoms/type.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, open '/home/networktest/tmp/npm-9132-OZORowo4/1457451739920-0.8732261669356376/package/amd-test/require.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Linux 3.16.0-57-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "appium"
npm ERR! cwd /home/networktest
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /home/networktest/tmp/npm-9132-OZORowo4/1457451739920-0.8732261669356376/package/amd-test/require.js
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/appium/node_modules/appium-selendroid-driver/test/.selendroid-specs.js.un~'
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Linux 3.16.0-57-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "appium"
npm ERR! cwd /home/networktest
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /usr/local/lib/node_modules/appium/node_modules/appium-selendroid-driver/test/.selendroid-specs.js.un~
npm ERR! fstream_path /usr/local/lib/node_modules/appium/node_modules/appium-selendroid-driver/test/.selendroid-specs.js.un~
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/appium/node_modules/traceur/bin/traceur.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Linux 3.16.0-57-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "appium"
npm ERR! cwd /home/networktest
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /usr/local/lib/node_modules/appium/node_modules/traceur/bin/traceur.js
npm ERR! fstream_path /usr/local/lib/node_modules/appium/node_modules/traceur/bin/traceur.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/home/networktest/tmp/npm-9132-OZORowo4/1457451738221-0.04647051799111068/package/test/test.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Linux 3.16.0-57-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "appium"
npm ERR! cwd /home/networktest
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /home/networktest/tmp/npm-9132-OZORowo4/1457451738221-0.04647051799111068/package/test/test.js
npm ERR! fstream_path /home/networktest/tmp/npm-9132-OZORowo4/1457451738221-0.04647051799111068/package/test/test.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/appium/node_modules/babel-core/browser.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Linux 3.16.0-57-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "appium"
npm ERR! cwd /home/networktest
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /usr/local/lib/node_modules/appium/node_modules/babel-core/browser.js
npm ERR! fstream_path /usr/local/lib/node_modules/appium/node_modules/babel-core/browser.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/ApiDemos-debug.apk'
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Linux 3.16.0-57-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "appium"
npm ERR! cwd /home/networktest
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /usr/local/lib/node_modules/appium/node_modules/appium-android-driver/ApiDemos-debug.apk
npm ERR! fstream_path /usr/local/lib/node_modules/appium/node_modules/appium-android-driver/ApiDemos-debug.apk
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/appium/node_modules/appium-adb/jars/appium_apk_tools.jar'
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Linux 3.16.0-57-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "appium"
npm ERR! cwd /home/networktest
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /usr/local/lib/node_modules/appium/node_modules/appium-adb/jars/appium_apk_tools.jar
npm ERR! fstream_path /usr/local/lib/node_modules/appium/node_modules/appium-adb/jars/appium_apk_tools.jar
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/networktest/npm-debug.log
npm ERR! not ok code 0

**Comment by KenanY** [comment]
Hello @siva2503! `npm@1.3` is no longer supported. Please try [updating](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm). Also, be sure to read the file mentioned in the error message:

```
sh: 1: node: not found
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
```

**Comment by siva2503** [comment]
Thanks for the reply KenanY, that helped.

But now proceeding with that, facing the below issue..

user@machinename:~$ npm install appium
/home/path
└── appium@1.5.0 

npm WARN optional Skipping failed optional dependency /appium/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.8
npm WARN enoent ENOENT: no such file or directory, open '/home/networktest/package.json'
npm WARN networktest No description
npm WARN networktest No repository field.
npm WARN networktest No README data
npm WARN networktest No license field.



Please help.

**Comment by KenanY** [comment]
@siva2503 Those look like nothing more than a few warnings. I would expect `appium` to have installed just fine. Is this not the case?

**Comment by KenanY** [comment]
@siva2503 Are you still facing any issues?

**Comment by nawazshaik** [comment]
@KenanY, I do have the same Warning messages while installing Appium in my machine. After all those warning messages Appium is NOT Installed in my machine. Plz help

npm WARN optional Skipping failed optional dependency /appium/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.8
npm WARN enoent ENOENT: no such file or directory, open '/home/networktest/package.json'
npm WARN networktest No description
npm WARN networktest No repository field.
npm WARN networktest No README data
npm WARN networktest No license field
