### ISSUE TITLE
npm Cannot find module 'typechecker'

### ISSUE THREAD

**Issue by VanisreeThazhedamVeedu** [npm/npm#11810]
I have installed node v5.7.1. for appcelerator studio.
when I try anthing with 'appc' command, I am getting the following error -

*****************************************************
An uncaught exception was thrown!
Cannot find module 'typechecker'
Cannot find module 'typechecker'
*****************************************************

**Comment by KenanY** [comment]
@VanisreeThazhedamVeedu Are you still seeing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
