### ISSUE TITLE
unable to install appium

### ISSUE THREAD

**Issue by cw-cz-asrivastava** [npm/npm#11814]
$ npm install -g appium
npm ERR! tar.unpack unzip error /tmp/npm-5873-495ac80a/registry.npmjs.org/appium-atoms/-/appium-atoms-0.1.0.tgz
npm ERR! tar.unpack untar error /tmp/npm-5873-495ac80a/registry.npmjs.org/appium-atoms/-/appium-atoms-0.1.0.tgz
npm ERR! tar.unpack unzip error /tmp/npm-5873-495ac80a/registry.npmjs.org/appium-adb/-/appium-adb-2.4.3.tgz
npm ERR! tar.unpack untar error /tmp/npm-5873-495ac80a/registry.npmjs.org/appium-adb/-/appium-adb-2.4.3.tgz
npm ERR! tar.unpack unzip error /tmp/npm-5873-495ac80a/registry.npmjs.org/appium-android-driver/-/appium-android-driver-1.6.12.tgz
npm ERR! tar.unpack untar error /tmp/npm-5873-495ac80a/registry.npmjs.org/appium-android-driver/-/appium-android-driver-1.6.12.tgz
npm ERR! tar.unpack unzip error /tmp/npm-5873-495ac80a/registry.npmjs.org/appium-android-bootstrap/-/appium-android-bootstrap-2.5.1.tgz
npm ERR! tar.unpack untar error /tmp/npm-5873-495ac80a/registry.npmjs.org/appium-android-bootstrap/-/appium-android-bootstrap-2.5.1.tgz
npm ERR! Linux 3.13.0-32-generic
npm ERR! argv "/home/craterzone3/.linuxbrew/Cellar/node/5.7.1/bin/node" "/home/craterzone3/.linuxbrew/bin/npm" "install" "-g" "appium"
npm ERR! node v5.7.1
npm ERR! npm  v3.8.0
npm ERR! code Z_BUF_ERROR
npm ERR! errno -5

**Comment by vinayviga** [comment]
have you installed brew?

**Comment by KenanY** [comment]
@cw-cz-asrivastava Is this still an issue for you?

**Comment by KenanY** [comment]
Closing as abandoned.
