### ISSUE TITLE
semver.npmjs.com uses an invalid security certificate

### ISSUE THREAD

**Issue by pygy** [npm/npm#11819]
Hi there!

As told by Firefox when visiting https://semver.npmjs.com/:

```
semver.npmjs.com uses an invalid security certificate.

The certificate is only valid for the following names: bizz.vizz.buzz, www.bizz.vizz.buzz

(Error code: ssl_error_bad_cert_domain)
```

**Comment by othiym23** [comment]
Issues on `semver.npmjs.com` site go [→ thataway](https://github.com/npm/semver.npmjs.com/issues). As this isn't an issue with the npm CLI, I'm going to close this. Thanks for bringing it up, though!

**Comment by pygy** [comment]
Forwarding, then. Thanks for the quick reply :-)
