### ISSUE TITLE
Installing modules from local folder doesn't keep track of it's version

### ISSUE THREAD

**Issue by TCMiranda** [npm/npm#11818]
Installing and saving the reference of a module saved on local file system (`"module": "file:./path/to/module..."`) should keep track of the package version, as it have the necessary information at `./path/to/module/package.json`.

So I could use

    "local_module": "file:local_modules/local_module@version"

Right? Thanks!

**Comment by KenanY** [comment]
How would this work? Only one version of a package can exist in a given directory. What would even be the use-case?

**Comment by othiym23** [comment]
The thing on the right-hand side of a dependency is the _package specifier_ – it's what's necessary, whether it's a URL, a semver range, or a path, to uniquely determine what's to be installed. There can only ever be one version of a package at a given path, so this specifier is at best ambiguous and possibly erroneous in the case where the package at the path doesn't have a version matching what's being requested. In general, local paths are a development tool, and aren't really suited for use in situations where having tight control over dependency versions is desired.

As such, this isn't a change that's going to happen to the CLI, and so I'm going to close this issue. Thanks for your time, and I hope this explanation is sufficiently clear to be useful.

**Comment by TCMiranda** [comment]
Thanks for the answer @othiym23 
I am just going to document my use case in response to @KenanY 

I am currently coding to AWS Lambda and I found that using local modules to share code between my services is a good way to organize them since I have to compile every module to node v.10

So every of my "shared modules" are in the form of

    ..
    dist/
    src/
    package.json

So I can compile `src` to `dist` in a more organized way.

The problem I issued is that every change to those modules, requires me to `npm i ../modules/module` again, since the version at the `../modules/module/package.json` are not tracked with just `npm install`.


Note that the shared modules are in another folder. 
My Lambda function has a package.json, where the local module is defined with

    "dependencies": {
        "local_module": "file:../local_modules/local_module@version"
    }


Would you find a better scenario for that?

Thanks, Tiago
