### ISSUE TITLE
npm install -g gulp issue

### ISSUE THREAD

**Issue by ashish-jagdale** [npm/npm#11829]
After executing "npm install -g gulp" command - I am getting error as "404 - File or directory not found."

19 verbose bad json <div id="header"><h1>Server Error</h1></div>
19 verbose bad json <div id="content">
19 verbose bad json  <div class="content-container"><fieldset>
19 verbose bad json   <h2>404 - File or directory not found.</h2>
19 verbose bad json   <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
19 verbose bad json  </fieldset></div>
19 verbose bad json </div>

**Comment by pedzed** [comment]
You should really give some more information. Do you still have a problem? What is your operating system?

**Comment by KenanY** [comment]
@ashish-jagdale Are you still seeing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
