### ISSUE TITLE
Trouble with --save-dev for a gulp-sass

### ISSUE THREAD

**Issue by olegkukharuk** [npm/npm#11828]
Response of cmd
[http://i.imgur.com/CqGO7IO.jpg](http://i.imgur.com/CqGO7IO.jpg)

npm-debug.log
[https://jsfiddle.net/hco9wb3e/](https://jsfiddle.net/hco9wb3e/)

**Comment by KenanY** [comment]
Hmm, do you have `"name": "gulp-sass"` in your `package.json` by any chance?
