### ISSUE TITLE
Self signed certificate in certificate chain

### ISSUE THREAD

**Issue by KeerthiSattaluri** [npm/npm#11826]
npm ERR! Linux 3.13.0-24-generic
npm ERR! argv "/home/keerthi/project/nodejs/bin/node" "/home/keerthi/project/nodejs/bin/npm" "install"
npm ERR! node v5.7.1
npm ERR! npm  v3.6.0
npm ERR! code SELF_SIGNED_CERT_IN_CHAIN

npm ERR! self signed certificate in certificate chain

[npm-debug.log.txt](https://github.com/npm/npm/files/164927/npm-debug.log.txt)

**Comment by KenanY** [comment]
@KeerthiSattaluri Are you still seeing this issue?

**Comment by KenanY** [comment]
Closing due to no response.
