### ISSUE TITLE
Npm issue

### ISSUE THREAD

**Issue by Sourcebits-Abhilasha** [npm/npm#11827]
I am facing this error every time , when I am trying to install any module using "npm install" 
please tell me how can I solve this issue,
I install node js latest version, n unable to install gulp bower n so on.., getting same error on each try.
i tried installing the missing module which is shown in screenshot, still got same error, 
Thanks in advance
![cmd](https://cloud.githubusercontent.com/assets/10348375/13634649/e1252148-e61c-11e5-9d7b-bd53fe6ee852.png)

**Comment by jacobmischka** [comment]
Something is wrong with your npm installation, try reinstalling node.

**Comment by pedzed** [comment]
> Please include the following file with any support request:
>  C:\Users\546760\npm-debug.log

**Comment by KenanY** [comment]
@Sourcebits-Abhilasha Are you still seeing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
