### ISSUE TITLE
`npm link` should check for installed packages before querying the npm registry

### ISSUE THREAD

**Issue by augustl** [npm/npm#1182]
When I `npm link` a package with a dependency that I have installed via npm link or a tarball, that isn't in the npm registry, npm fails.

Update 1:
Seems like npm link will npm install itself post link, to handle dependencies. And npm install doesn't seem to check if a dependency of a package is already installed before querying the registry. So that's the only fix needed it seems.

Update 2:
`targetResolver` in npm install only checks for existing installs in node_modules of the package from where `npm link` is executed. As seen below, this means it won't find packages that has been linked, since linking installs to  ~/local/node/lib/node_modules.

So a sensible fix as far as I know would be to have `targetResolver` do a full scale check - i.e. NODE_PATH and node_modules in all parent directories.

Piggybacking on `require.resolve` is probably not a good idea, as some packages might only have a bin/ for example, and is not requireable.
## How to reproduce

In ~/package-foo/package.json:

```
{
    "name": "package-foo",
    "version": "0.5.0"
}
```

In ~/package-bar/package.json:

```
{
    "name": "package-bar",
    "version": "0.5.0",
    "dependencies": {
        "package-foo": "*"
    }
}
```

Then run:

```
$> cd ~/package-foo
$> npm-link
../local/node/lib/node_modules/package-foo -> /home/augustl/package-foo
$> cd ~/package-bar
$> npm link
npm ERR! 404 'package-foo' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it.
npm ERR! 404 Note that you can also install from a tarball or folder.
npm ERR! 
npm ERR! System Linux 2.6.39-ARCH
npm ERR! command "node" "/home/augustl/local/node/bin/npm" "link"
npm ERR! cwd /home/augustl/sandbox/package-bar
npm ERR! node -v v0.4.8
npm ERR! npm -v 1.0.20
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/augustl/package-bar/npm-debug.log
npm not ok
```

**Comment by tomekwi** [comment]
Is there any way to execute `npm link` without implying an `npm install`?

**Comment by othiym23** [comment]
@tomekwi No, there isn't.

**Comment by niklas-dahl** [comment]
it would be awesome if there was a flag for `npm link` so that the local package gets linked without checking dependencies at all.

**Comment by gms1** [comment]
I want to confirm this bug for version 3.10.9 and 4.0.5:
quote: "When I npm link a package with a dependency that I have installed via npm link or a tarball, that isn't in the npm registry, npm fails."
is not resolved yet
