### ISSUE TITLE
Invalid Version: 0.4.0rc8 when running 'npm install grunt'

### ISSUE THREAD

**Issue by justinbleach** [npm/npm#11836]
I'm not using an internal registry which seemed to be the problem for another gentlemen when I searched for this issue on here. Please note I have already run 'npm install grunt-cli' with no problems.

I'm using: https://registry.npmjs.org/grunt and I get the following error (whether SUDO or not) when running 'npm install grunt' :

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "grunt"
npm ERR! node v4.2.4
npm ERR! npm  v3.8.0

npm ERR! Invalid Version: 0.4.0rc8
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jbleach/workspaces/nox/noxApp/WebContent/npm-debug.log

Here is what I have from the npm-debug.log:

 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'grunt' ]
2 info using npm@3.8.0
3 info using node@v4.2.4
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData grunt@~0.4.5
8 silly fetchNamedPackageData grunt
9 silly mapToRegistry name grunt
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/grunt
13 verbose request uri https://registry.npmjs.org/grunt
14 verbose request no auth needed
15 info attempt registry request try #1 at 1:35:21 PM
16 verbose request id 729820f5db8e203a
17 verbose etag "56d7d616-16ddf"
18 verbose lastModified Thu, 03 Mar 2016 06:13:42 GMT
19 http request GET https://registry.npmjs.org/grunt
20 http 304 https://registry.npmjs.org/grunt
21 verbose headers { date: 'Wed, 09 Mar 2016 18:35:22 GMT',
21 verbose headers   via: '1.1 varnish',
21 verbose headers   'cache-control': 'max-age=300',
21 verbose headers   etag: '"56d7d616-16ddf"',
21 verbose headers   expires: 'Thu, 10 Mar 2016 00:15:35 GMT',
21 verbose headers   age: '887',
21 verbose headers   connection: 'keep-alive',
21 verbose headers   'x-served-by': 'cache-jfk1046-JFK',
21 verbose headers   'x-cache': 'HIT',
21 verbose headers   'x-cache-hits': '13',
21 verbose headers   'x-timer': 'S1457548522.741329,VS0,VE0' }
22 silly get cb [ 304,
22 silly get   { date: 'Wed, 09 Mar 2016 18:35:22 GMT',
22 silly get     via: '1.1 varnish',
22 silly get     'cache-control': 'max-age=300',
22 silly get     etag: '"56d7d616-16ddf"',
22 silly get     expires: 'Thu, 10 Mar 2016 00:15:35 GMT',
22 silly get     age: '887',
22 silly get     connection: 'keep-alive',
22 silly get     'x-served-by': 'cache-jfk1046-JFK',
22 silly get     'x-cache': 'HIT',
22 silly get     'x-cache-hits': '13',
22 silly get     'x-timer': 'S1457548522.741329,VS0,VE0' } ]
23 verbose etag https://registry.npmjs.org/grunt from cache
24 verbose get saving grunt to /Users/jbleach/.npm/registry.npmjs.org/grunt/.cache.json
25 verbose correctMkdir /Users/jbleach/.npm correctMkdir not in flight; initializing
26 verbose stack TypeError: Invalid Version: 0.4.0rc8
26 verbose stack     at new SemVer (/usr/local/lib/node_modules/npm/node_modules/semver/semver.js:293:11)
26 verbose stack     at SemVer.compare (/usr/local/lib/node_modules/npm/node_modules/semver/semver.js:342:13)
26 verbose stack     at compare (/usr/local/lib/node_modules/npm/node_modules/semver/semver.js:566:31)
26 verbose stack     at rcompare (/usr/local/lib/node_modules/npm/node_modules/semver/semver.js:576:10)
26 verbose stack     at Array.sort (native)
26 verbose stack     at pickVersionFromRegistryDocument (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:121:48)
26 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/iferr/index.js:13:50
26 verbose stack     at /usr/local/lib/node_modules/npm/lib/utils/pulse-till-done.js:19:8
26 verbose stack     at saved (/usr/local/lib/node_modules/npm/lib/cache/caching-client.js:168:7)
26 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:210:7
27 verbose cwd /Users/jbleach/workspaces/test/testApp/WebContent
28 error Darwin 15.3.0
29 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "grunt"
30 error node v4.2.4
31 error npm  v3.8.0
32 error Invalid Version: 0.4.0rc8
33 error If you need help, you may report this error at:
33 error     <https://github.com/npm/npm/issues>
34 verbose exit [ 1, true ]

**Comment by wllmtrng** [comment]
Had the same problem, but it seemed like it fixed itself.

**Comment by soldair** [comment]
we made a change to the cdn configuration that resulted in this odd bug. this has been resolved please let me know if you run into anything else.

**Comment by justinbleach** [comment]
Just ran it again and now it works. Thanks!

**Comment by bahmutov** [comment]
I would like this bug to be reopened, getting this breaking when a dependency tries to install handlebars which includes `1.0.5beta` version.

The problem is the sorting of versions in line https://github.com/npm/npm/blob/4ec9a49e0cdbf0ab301b99b823372f610668e99e/lib/fetch-package-metadata.js#L121

```js
var versions = Object.keys(pkg.versions).sort(semver.rcompare)
```
The `semver.rcompare` is `function rcompare(a, b, loose)` but we are passing `loose` as undefined, thus rcompare throws an error if the list of versions includes a non-valid semver.
We really should be using `semver.rsort(Object.keys(pkg.versions), true)` or filter invalid semvers before sorting

**Comment by soldair** [comment]
curious. Are you using the version of handlebars published to the public registry?   `registry.npmjs.org/handlebars`
the server cleans these versions so you shouldn't be hitting this.

**Comment by bahmutov** [comment]
Oh, you are right, this is going through sinopia proxy. Going directly to the public does clean this up.

**Comment by bahmutov** [comment]
Not sure what to do - feel like being more robust at sorting would still help
