### ISSUE TITLE
Support annotating version tags separately from commits

### ISSUE THREAD

**Issue by alex-shpilkin** [npm/npm#11833]
Currently, `npm version` [reuses](https://github.com/npm/npm/blob/master/lib/version.js#L261) the same message created from `--message` for both version bump commits and annotated version tags. I think this misses the point of annotated tags: annotations on the version tags of a project could actually serve to store the equivalent of a conventional change log. So there should be a way to set them to something more informative and not auto-generated.

A simple way to achieve this would be to grab the message from `.git/TAG_EDITMSG` (where the user or the `preversion` script could place it), as git will destroy its contents later during tag creation anyway, and revert to the default behaviour otherwise. (I could implement that if anybody’s interested.)

**Comment by othiym23** [comment]
See the resolution for #11796. `npm version` is a relatively simple command intended to ease managing versions for packages. In many ways, its use as of Git is incidental, and adding additional behavior there threatens to overcomplicate the feature. That said, there's nothing stopping you from using package scripts or additional tooling to create customized workflows for this, and there are other people who would find that behavior useful were you to turn it into a package.

As this isn't something the CLI team is going to add to npm, I'm going to close this feature request. Thank you for your time!

**Comment by eljefedelrodeodeljefe** [comment]
There could be, however, a valid point for such a feature. Since `npm version [major | minor | patch]` is variable, I would want to do a possible workflow like

```bash
npm version patch # done by human
# done by postversion
npm version annotate lastTag -m $(echo $(git log `git describe --tags --abbrev=0 HEAD^`..HEAD --oneline)) && git push && git push --tags
```  
This could give you all the commits with oneline description for the current tag up to the tag before.

Just saying, just +0 on this, since it can be worked around.

**Comment by eljefedelrodeodeljefe** [comment]
Workaround (or feature showcase) would be this script: 

```json
{
   "scripts": {
        "postversion": "TAG=$(echo $(git describe --tags $(git rev-list --tags --max-count=1))) && git tag -a $TAG $TAG -f -m \"$(git log `git describe --tags --abbrev=0 HEAD^`..HEAD --oneline)\" && git push && git push --tags"
   }
}
```
