### ISSUE TITLE
don't publish unless `version` in package.json passes strict semver validation

### ISSUE THREAD

**Issue by othiym23** [npm/npm#11837]
It appears that the CLI will currently publish a package even if the version isn't one that it would accept at install time. The primary registry has been normalizing published packages, so as long as they're parseable with `semver` in loose mode, the resulting package will be installable. The registry team recently rolled out a change to the registry that (unintentionally) removed this normalization, and it caused immediate installation failures for end users. `npm publish` should refuse to publish any package that doesn't have a strictly conformant value in `version` (even though registries will need to continue normalizing version fields because of the large number of iffy version fields in the wild).

**Comment by ifandelse** [comment]
We are experiencing the same issue with our projects at LeanKit. In our case, shelljs is a dependency down the tree from things we're using (like eslint, etc.). Since shelljs was able to be published with a poorly formed version tag of 0.0.6pre2, when we started building new docker containers (and thus, fresh npm install) on projects with shelljs in the dep tree, we're now seeing this:
```
npm ERR! Linux 4.1.17-boot2docker
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v5.7.1
npm ERR! npm  v3.8.1

npm ERR! Invalid Version: 0.0.6pre2
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /app/npm-debug.log
The command '/bin/sh -c npm install' returned a non-zero code: 1
```

I know in this case the burden of un-publishing the bad version tags is likely on the individual projects, but preventing bad versions from being published would be ideal to prevent this. Thanks!

**Comment by othiym23** [comment]
@ifandelse You encountered a transient issue with our registry infrastructure (see #11835 / #11836), but yes, this is important for people publishing to registries other than the primary registry, as well as acting as a backstop to keep bad package data from being published to the primary regsitry.

**Comment by ifandelse** [comment]
@othiym23 thanks so much for the quick reply. We're actually still encountering this issue with npm 3.x (just retried). Do we have any recourse short of waiting on shelljs to un-publish their bad versions? (we've reached out to them as well).

**Comment by shane-walker** [comment]
@ifandelse I opened [an issue with shelljs](https://github.com/shelljs/shelljs/issues/390) a little while ago too. We're seeing the same problem that you're seeing. Specifically because of shelljs as required by eslint.

**Comment by ariporad** [comment]
Hi Everyone, Shelljs maintainer here!

I'm not seeing this issue. https://semver.npmjs.com doesn't show any problematic versions, neither does my terminal:

```bash
 $ npm view shelljs versions
[ '0.0.1-alpha1',
  '0.0.1',
  '0.0.2-pre1',
  '0.0.2',
  '0.0.3',
  '0.0.4-pre1',
  '0.0.4',
  '0.0.5-pre1',
  '0.0.5-pre2',
  '0.0.5-pre3',
  '0.0.5-pre4',
  '0.0.5',
  '0.0.6-pre1',
  '0.0.6-pre2',
  '0.0.6',
  '0.0.7',
  '0.0.8',
  '0.0.9',
  '0.1.0',
  '0.1.1',
  '0.1.2',
  '0.1.3',
  '0.1.4',
  '0.2.0',
  '0.2.1',
  '0.2.2',
  '0.2.3',
  '0.2.4',
  '0.2.5',
  '0.2.6',
  '0.3.0',
  '0.4.0',
  '0.5.0',
  '0.5.1',
  '0.5.2',
  '0.5.3',
  '0.6.0' ]
```

I'm unpublishing the problematic versions, even though they don't seem to exist?

**Comment by siroky** [comment]
+1

**Comment by zkat** [comment]
This was fixed with #11838 -- thanks, @watilde!

**Comment by watilde** [comment]
@zkat Oops, this wasn't fixed yet actually. Will be fixed by next release probably!
https://github.com/npm/npm/pull/11838#issuecomment-217979403

**Comment by iarna** [comment]
It is actually landed! =)
