### ISSUE TITLE
npm ERR! Error: version not found: asd-consolidated-summary@0.0.2

### ISSUE THREAD

**Issue by poundingCode** [npm/npm#11830]
====Executing command 'npm install'====

npm WARN package.json Geico.AsdService.Edge.Ui.Web@0.0.0 No description
npm WARN package.json Geico.AsdService.Edge.Ui.Web@0.0.0 No repository field.
npm WARN package.json Geico.AsdService.Edge.Ui.Web@0.0.0 No README data
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/asd-consolidated-summary
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/asd-ui-angular
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/angular-touch
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/eslint-plugin-asd-angular
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/extend
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/canonical-path
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-autoprefixer
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-ignore
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-ng-annotate
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-order
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-rename
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-replace
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-rev-replace
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/jquery
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/angular-translate
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-util
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/htmlparser2
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/karma-coverage
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/pseudoizer
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/asd-core
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-rev
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-csso
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-angular-filesort
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-flatten
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/angular-ui-router
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/require-dir
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/domutils
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/angular-mocks
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/dgeni
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/asd-test-angular
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/jasmine-core
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/browser-sync
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-if
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/del
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-size
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/uglify-save-license
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-uglify
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/karma-ng-html2js-preprocessor
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/through2
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-minify-html
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/karma-jasmine
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-filter
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/karma-chrome-launcher
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/moment
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-cache
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-ng-html2js
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/run-sequence
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-changed
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-useref
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/yargs
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/angular-sanitize
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-eslint
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/glob
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/http-proxy
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/angular
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-inject
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/lodash
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/wiredep
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/eslint-config-asd
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/glob-array
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-help
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/dgeni-packages
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/karma
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/eslint
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/extend
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/angular-touch
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/asd-ui-angular
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/asd-consolidated-summary
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/eslint-plugin-asd-angular
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-autoprefixer
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-ng-annotate
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-order
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-ignore
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/canonical-path
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-replace
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/jquery
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-rename
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/angular-translate
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-rev-replace
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/htmlparser2
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/karma-coverage
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-util
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/asd-core
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/pseudoizer
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-rev
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-angular-filesort
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-csso
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/angular-ui-router
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-flatten
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/domutils
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/require-dir
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/angular-mocks
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/asd-test-angular
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/dgeni
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-if
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/jasmine-core
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/del
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/browser-sync
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-size
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/through2
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-uglify
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/karma-ng-html2js-preprocessor
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/uglify-save-license
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-minify-html
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/karma-jasmine
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-cache
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-filter
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/karma-chrome-launcher
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/moment
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-changed
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/run-sequence
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-ng-html2js
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/yargs
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-useref
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/glob
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/angular-sanitize
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-eslint
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/http-proxy
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/eslint-config-asd
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/wiredep
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-inject
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/angular
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/lodash
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/dgeni-packages
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/glob-array
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-help
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/karma
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/eslint
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/angular-touch
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/extend
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/asd-ui-angular
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/asd-consolidated-summary
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/eslint-plugin-asd-angular
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-order
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/canonical-path
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-autoprefixer
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-ignore
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-ng-annotate
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/angular-translate
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-rename
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/jquery
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-replace
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-rev-replace
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/htmlparser2
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-util
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/asd-core
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/karma-coverage
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/pseudoizer
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-rev
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-angular-filesort
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/angular-ui-router
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-csso
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-flatten
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/domutils
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/angular-mocks
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/require-dir
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/asd-test-angular
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/dgeni
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/jasmine-core
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-if
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/del
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/browser-sync
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-size
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/through2
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-uglify
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/karma-ng-html2js-preprocessor
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/uglify-save-license
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-minify-html
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/karma-jasmine
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-cache
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-filter
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/karma-chrome-launcher
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/moment
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-changed
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/yargs
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/run-sequence
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-ng-html2js
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-useref
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/glob
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-eslint
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/angular-sanitize
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/http-proxy
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp
npm ERR! Error: version not found: asd-consolidated-summary@0.0.2
npm ERR!     at C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External\npm\node_modules\npm\lib\cache.js:846:12
npm ERR!     at saved (C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External\npm\node_modules\npm-registry-client\lib\get.js:148:7)
npm ERR!     at C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External\npm\node_modules\graceful-fs\polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\IDE\\Extensions\\Microsoft\\Web Tools\\External\\\\node\\node" "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\IDE\\Extensions\\Microsoft\\Web Tools\\External\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd C:\dev\asd\Edge\Main\src\Geico.AsdService.Edge.Ui.Web
npm ERR! node -v v0.10.31
npm ERR! npm -v 1.4.9
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/eslint-config-asd
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/wiredep
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-inject
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/angular
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/lodash
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/dgeni-packages
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/gulp-help
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/glob-array
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/karma
npm http GET https://mvnrepo.dev.ibu.geico.net/api/npm/npm-registry/eslint
npm WARN deprecated gulp-minify-html@1.0.5: Please use gulp-htmlmin
npm

====npm command completed with exit code 1====

**Comment by KenanY** [comment]
Hello @poundingCode! I see that you are using a custom registry. Does

```
npm ERR! Error: version not found: asd-consolidated-summary@0.0.2
```

exist in your registry?

Also, do note that `npm@1.4.9` is not really supported anymore.

**Comment by KenanY** [comment]
@poundingCode Are you still seeing this issue?

**Comment by poundingCode** [comment]
Thanks for following up. I'm good.
