### ISSUE TITLE
unable to install protractor

### ISSUE THREAD

**Issue by keviv89** [npm/npm#11847]
C:\Program Files\nodejs\node_modules>cd npm

C:\Program Files\nodejs\node_modules\npm>npm install -g protractor
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs
\node_modules\npm\bin\npm-cli.js" "install" "-g" "protractor"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! syscall getaddrinfo

npm ERR! getaddrinfo EAI_AGAIN
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     http://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Program Files\nodejs\node_modules\npm\npm-debug.log

C:\Program Files\nodejs\node_modules\npm>

**Comment by keviv89** [comment]
Can anyone help me out in fixing this error ? I have navigated to the location where npm is present but when I am running the command to run in command prompt I am unable to install protractor. Kindly help

**Comment by pedzed** [comment]
Is this your first time using npm? Try to download the newest version of nodejs: https://nodejs.org/en/download

**Comment by zkat** [comment]
@keviv89 are you behind a proxy or firewall? Or are you dealing with a flaky internet connection? This error usually means you've got some configuration issue for some DNS-related bit. npm can be [configured to work behind a proxy](http://jjasonclark.com/how-to-setup-node-behind-web-proxy/), if that's the case.
