### ISSUE TITLE
Mongo-edu

### ISSUE THREAD

**Issue by illegitimis** [npm/npm#11849]
root@andrei-MYWAY:~# npm install mongo-edu -gnpm http GET https://registry.npmjs.org/mongo-edu
npm http 304 https://registry.npmjs.org/mongo-edu
npm http GET https://registry.npmjs.org/cheerio
npm http GET https://registry.npmjs.org/colors
npm http GET https://registry.npmjs.org/easy-table
npm http GET https://registry.npmjs.org/extract-zip
npm http GET https://registry.npmjs.org/get-youtube-id
npm http GET https://registry.npmjs.org/filesize
npm http GET https://registry.npmjs.org/glob
npm http GET https://registry.npmjs.org/inquirer
npm http GET https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/moment
npm http GET https://registry.npmjs.org/mv
npm http GET https://registry.npmjs.org/path-extra
npm http GET https://registry.npmjs.org/pretty-error
npm http GET https://registry.npmjs.org/progress
npm http GET https://registry.npmjs.org/request-progress
npm http GET https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/which
npm http GET https://registry.npmjs.org/yargs
npm http GET https://registry.npmjs.org/youtube-dl
npm http 304 https://registry.npmjs.org/cheerio
npm http 304 https://registry.npmjs.org/colors
npm http 304 https://registry.npmjs.org/glob
npm http 304 https://registry.npmjs.org/inquirer
npm http 304 https://registry.npmjs.org/lodash
npm http 304 https://registry.npmjs.org/filesize
npm http 304 https://registry.npmjs.org/easy-table
npm http 304 https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/moment
npm http 304 https://registry.npmjs.org/mv
npm http 304 https://registry.npmjs.org/pretty-error
npm http 304 https://registry.npmjs.org/request-progress
npm http 304 https://registry.npmjs.org/request
npm http 304 https://registry.npmjs.org/rimraf
npm http 304 https://registry.npmjs.org/get-youtube-id
npm http 304 https://registry.npmjs.org/which
npm http 304 https://registry.npmjs.org/progress
npm http 304 https://registry.npmjs.org/yargs
npm http 304 https://registry.npmjs.org/path-extra
npm http 304 https://registry.npmjs.org/extract-zip
npm http 304 https://registry.npmjs.org/youtube-dl
npm http GET https://registry.npmjs.org/concat-stream/1.5.0
npm http GET https://registry.npmjs.org/debug/0.7.4
npm http GET https://registry.npmjs.org/mkdirp/0.5.0
npm http GET https://registry.npmjs.org/yauzl/2.4.1
npm ERR! Error: ENOENT, lstat '/home/andrei/local/node/lib/node_modules/mongo-edu/node_modules/lodash/max.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-79-generic
npm ERR! command "/home/andrei/local/node/bin/node" "/home/andrei/local/node/bin/npm" "install" "mongo-edu" "-g"
npm ERR! cwd /home/andrei
npm ERR! node -v v0.10.7
npm ERR! npm -v 1.2.21
npm ERR! path /home/andrei/local/node/lib/node_modules/mongo-edu/node_modules/lodash/max.js
npm ERR! fstream_path /home/andrei/local/node/lib/node_modules/mongo-edu/node_modules/lodash/max.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /home/andrei/local/node/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/home/andrei/local/node/lib/node_modules/mongo-edu/node_modules/request/LICENSE'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-79-generic
npm ERR! command "/home/andrei/local/node/bin/node" "/home/andrei/local/node/bin/npm" "install" "mongo-edu" "-g"
npm ERR! cwd /home/andrei
npm ERR! node -v v0.10.7
npm ERR! npm -v 1.2.21
npm ERR! path /home/andrei/local/node/lib/node_modules/mongo-edu/node_modules/request/LICENSE
npm ERR! fstream_path /home/andrei/local/node/lib/node_modules/mongo-edu/node_modules/request/LICENSE
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /home/andrei/local/node/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! error rolling back Error: ENOTEMPTY, rmdir '/home/andrei/local/node/lib/node_modules/mongo-edu/node_modules/pretty-error/lib'
npm ERR! error rolling back  mongo-edu@0.2.53 { [Error: ENOTEMPTY, rmdir '/home/andrei/local/node/lib/node_modules/mongo-edu/node_modules/pretty-error/lib']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: '/home/andrei/local/node/lib/node_modules/mongo-edu/node_modules/pretty-error/lib' }
npm ERR! Error: No compatible version found: glob@'^7.0.0'
npm ERR! Valid install targets:
npm ERR! ["1.1.0","2.0.9","2.0.8","2.0.7","2.1.0","3.0.0","3.0.1","3.1.0","3.1.1","3.1.2","3.1.3","3.1.4","3.1.5","3.1.6","3.1.7","3.1.9","3.1.10","3.1.11","3.1.12","3.1.13","3.1.14","3.1.15","3.1.16","3.1.17","3.1.18","3.1.19","3.1.20","3.1.21","3.2.0","3.2.1","3.2.3","3.2.4","3.2.5","3.2.6","3.2.7","3.2.8","3.2.9","3.2.10","3.2.11","4.0.0","4.0.1","4.0.2","4.0.3","4.0.4","4.0.5","4.0.6","4.1.2-beta","4.1.2","4.1.3","4.1.4","4.1.5","4.1.6","4.2.0","4.2.1","4.2.2","4.3.0","4.3.1","4.3.2","4.3.3","4.3.4","4.3.5","4.4.0","4.4.2","4.5.0","5.0.0","4.5.1","5.0.1","4.5.2","5.0.2","4.5.3","5.0.3","5.0.4","5.0.5","5.0.6","5.0.7","5.0.9","5.0.10","5.0.11","5.0.12","5.0.13","5.0.14","5.0.15","6.0.1","6.0.2","6.0.3","6.0.4","7.0.0","7.0.1","7.0.3"]
npm ERR!     at installTargetsError (/home/andrei/local/node/lib/node_modules/npm/lib/cache.js:709:10)
npm ERR!     at /home/andrei/local/node/lib/node_modules/npm/lib/cache.js:631:10
npm ERR!     at RegClient.get_ (/home/andrei/local/node/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:101:14)
npm ERR!     at RegClient.<anonymous> (/home/andrei/local/node/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:37:12)
npm ERR!     at fs.js:266:14
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-79-generic
npm ERR! command "/home/andrei/local/node/bin/node" "/home/andrei/local/node/bin/npm" "install" "mongo-edu" "-g"
npm ERR! cwd /home/andrei
npm ERR! node -v v0.10.7
npm ERR! npm -v 1.2.21
npm http GET https://registry.npmjs.org/ncp
npm http GET https://registry.npmjs.org/is-absolute
npm http GET https://registry.npmjs.org/isexe
npm ERR! Error: ENOENT, lstat '/home/andrei/local/node/lib/node_modules/mongo-edu/node_modules/cheerio/History.md'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-79-generic
npm ERR! command "/home/andrei/local/node/bin/node" "/home/andrei/local/node/bin/npm" "install" "mongo-edu" "-g"
npm ERR! cwd /home/andrei
npm ERR! node -v v0.10.7
npm ERR! npm -v 1.2.21
npm ERR! path /home/andrei/local/node/lib/node_modules/mongo-edu/node_modules/cheerio/History.md
npm ERR! fstream_path /home/andrei/local/node/lib/node_modules/mongo-edu/node_modules/cheerio/History.md
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /home/andrei/local/node/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/home/andrei/local/node/lib/node_modules/mongo-edu/node_modules/youtube-dl/scripts/download.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-79-generic
npm ERR! command "/home/andrei/local/node/bin/node" "/home/andrei/local/node/bin/npm" "install" "mongo-edu" "-g"
npm ERR! cwd /home/andrei
npm ERR! node -v v0.10.7
npm ERR! npm -v 1.2.21
npm ERR! path /home/andrei/local/node/lib/node_modules/mongo-edu/node_modules/youtube-dl/scripts/download.js
npm ERR! fstream_path /home/andrei/local/node/lib/node_modules/mongo-edu/node_modules/youtube-dl/scripts/download.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /home/andrei/local/node/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/home/andrei/local/node/lib/node_modules/mongo-edu/node_modules/yargs/index.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-79-generic
npm ERR! command "/home/andrei/local/node/bin/node" "/home/andrei/local/node/bin/npm" "install" "mongo-edu" "-g"
npm ERR! cwd /home/andrei
npm ERR! node -v v0.10.7
npm ERR! npm -v 1.2.21
npm ERR! path /home/andrei/local/node/lib/node_modules/mongo-edu/node_modules/yargs/index.js
npm ERR! fstream_path /home/andrei/local/node/lib/node_modules/mongo-edu/node_modules/yargs/index.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /home/andrei/local/node/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/home/andrei/local/node/lib/node_modules/mongo-edu/node_modules/mkdirp/test/rel.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-79-generic
npm ERR! command "/home/andrei/local/node/bin/node" "/home/andrei/local/node/bin/npm" "install" "mongo-edu" "-g"
npm ERR! cwd /home/andrei
npm ERR! node -v v0.10.7
npm ERR! npm -v 1.2.21
npm ERR! path /home/andrei/local/node/lib/node_modules/mongo-edu/node_modules/mkdirp/test/rel.js
npm ERR! fstream_path /home/andrei/local/node/lib/node_modules/mongo-edu/node_modules/mkdirp/test/rel.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /home/andrei/local/node/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/home/andrei/local/node/lib/node_modules/mongo-edu/node_modules/glob/sync.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-79-generic
npm ERR! command "/home/andrei/local/node/bin/node" "/home/andrei/local/node/bin/npm" "install" "mongo-edu" "-g"
npm ERR! cwd /home/andrei
npm ERR! node -v v0.10.7
npm ERR! npm -v 1.2.21
npm ERR! path /home/andrei/local/node/lib/node_modules/mongo-edu/node_modules/glob/sync.js
npm ERR! fstream_path /home/andrei/local/node/lib/node_modules/mongo-edu/node_modules/glob/sync.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /home/andrei/local/node/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/home/andrei/local/node/lib/node_modules/mongo-edu/node_modules/colors/lib/custom/zalgo.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-79-generic
npm ERR! command "/home/andrei/local/node/bin/node" "/home/andrei/local/node/bin/npm" "install" "mongo-edu" "-g"
npm ERR! cwd /home/andrei
npm ERR! node -v v0.10.7
npm ERR! npm -v 1.2.21
npm ERR! path /home/andrei/local/node/lib/node_modules/mongo-edu/node_modules/colors/lib/custom/zalgo.js
npm ERR! fstream_path /home/andrei/local/node/lib/node_modules/mongo-edu/node_modules/colors/lib/custom/zalgo.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /home/andrei/local/node/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/home/andrei/local/node/lib/node_modules/mongo-edu/node_modules/moment/moment.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-79-generic
npm ERR! command "/home/andrei/local/node/bin/node" "/home/andrei/local/node/bin/npm" "install" "mongo-edu" "-g"
npm ERR! cwd /home/andrei
npm ERR! node -v v0.10.7
npm ERR! npm -v 1.2.21
npm ERR! path /home/andrei/local/node/lib/node_modules/mongo-edu/node_modules/moment/moment.js
npm ERR! fstream_path /home/andrei/local/node/lib/node_modules/mongo-edu/node_modules/moment/moment.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /home/andrei/local/node/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm http 304 https://registry.npmjs.org/debug/0.7.4
npm http 304 https://registry.npmjs.org/mkdirp/0.5.0
npm http 304 https://registry.npmjs.org/is-absolute
npm http 304 https://registry.npmjs.org/isexe
npm http 304 https://registry.npmjs.org/ncp
npm ERR! EEXIST, mkdir '/home/andrei/local/node/lib/node_modules/mongo-edu/node_modules/mv/node_modules/ncp/test/regular-fixtures/src'
File exists: /home/andrei/local/node/lib/node_modules/mongo-edu/node_modules/mv/node_modules/ncp/test/regular-fixtures/src
Move it away, and try again. 

npm ERR! System Linux 3.13.0-79-generic
npm ERR! command "/home/andrei/local/node/bin/node" "/home/andrei/local/node/bin/npm" "install" "mongo-edu" "-g"
npm ERR! cwd /home/andrei
npm ERR! node -v v0.10.7
npm ERR! npm -v 1.2.21
npm ERR! path /home/andrei/local/node/lib/node_modules/mongo-edu/node_modules/mv/node_modules/ncp/test/regular-fixtures/src
npm ERR! fstream_path /home/andrei/local/node/lib/node_modules/mongo-edu/node_modules/mv/node_modules/ncp/test/regular-fixtures/src/d
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code EEXIST
npm ERR! errno 47
npm ERR! fstream_stack /home/andrei/local/node/lib/node_modules/npm/node_modules/fstream/lib/writer.js:171:23
npm ERR! fstream_stack /home/andrei/local/node/lib/node_modules/npm/node_modules/mkdirp/index.js:37:53
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm http 304 https://registry.npmjs.org/concat-stream/1.5.0
npm http 304 https://registry.npmjs.org/yauzl/2.4.1
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/typedarray
npm http GET https://registry.npmjs.org/readable-stream
npm http GET https://registry.npmjs.org/fd-slicer
npm http GET https://registry.npmjs.org/minimist/0.0.8
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/typedarray
npm http 304 https://registry.npmjs.org/fd-slicer
npm http 304 https://registry.npmjs.org/readable-stream
npm http 304 https://registry.npmjs.org/minimist/0.0.8
npm http GET https://registry.npmjs.org/pend
npm http GET https://registry.npmjs.org/core-util-is
npm http GET https://registry.npmjs.org/isarray/0.0.1
npm http GET https://registry.npmjs.org/process-nextick-args
npm http GET https://registry.npmjs.org/util-deprecate
npm http GET https://registry.npmjs.org/string_decoder
npm http 304 https://registry.npmjs.org/pend
npm http 304 https://registry.npmjs.org/core-util-is
npm http 304 https://registry.npmjs.org/util-deprecate
npm http 304 https://registry.npmjs.org/isarray/0.0.1
npm http 304 https://registry.npmjs.org/process-nextick-args
npm http 304 https://registry.npmjs.org/string_decoder
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/andrei/npm-debug.log
npm ERR! not ok code 0

**Comment by othiym23** [comment]
Hi! You're using `npm@1.2`, which is several years out of date and can't handle a number of newer registry features. You should update to the latest npm (`npm -g install npm@latest`, with a `sudo` if you need to be root to globally install packages). Once you do that, this install should succeed. Thanks for your time!
