### ISSUE TITLE
npm install issue nodeJs

### ISSUE THREAD

**Issue by ashish-pandey-tavant** [npm/npm#11845]

**Comment by pedzed** [comment]
Is the issue solved? If yes, please close the issue. If not, please provide `npm-debug.log`.

**Comment by ashish-pandey-tavant** [comment]
Please find error log in node_debug.log

41040 error Windows_NT 6.3.9600
41041 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
41042 error node v5.1.1
41043 error npm  v3.3.12
41044 error Unexpected token H
41044 error HTTP/1.1 200 OK
41044 error server: CouchDB/1.5.0 (Erlang OTP/R16B03)
41044 error etag: "8GNHNGZWEH11ULIPJW9WH1OUG"
41044 error Content-Type: application/json
41044 error Cache-Control: max-age=300
41044 error Content-Length: 6378
41044 error Accept-Ranges: bytes
41044 error Date: Fri, 11 Mar 2016 10:54:04 GMT
41044 error Via: 1.1 varnish
41044 error Age: 14
41044 error Connection: keep-alive
41044 error X-Served-By: cache-sin6927-SIN
41044 error X-Cache: HIT
41044 error X-Cache-Hits: 1
41044 error X-Timer: S1457693644.738557,VS0,VE0
41044 error Vary: Accept
41044 error
41044 error {"_id":"to-absolute-glob","_rev":"2-a3f8174835402256ab5aad3f6b328b76","name":"to-absolute-glob","description":"Make a glob pattern absolute, ensuring that negative globs and patterns with trailing slashes are correctly handled.","dist-tags":{"latest":"0.1.1"},"versions":{"0.1.0":{"name":"to-absolute-glob","description":"Make a glob pattern absolute, ensuring that negative globs and patterns with trailing slashes are correctly handled.","version":"0.1.0","homepage":"https://github.com/jonschlinkert/to-absolute-glob","author":{"name":"Jon Schlinkert","url":"https://github.com/jonschlinkert"},"repository":{"type":"git","url":"git+https://github.com/jonschlinkert/to-absolute-glob.git"},"bugs":{"url":"https://github.com/jonschlinkert/to-absolute-glob/issues"},"license":"MIT","files":["index.js"],"main":"index.js","engines":{"node":">=0.10.0"},"scripts":{"test":"mocha"},"dependencies":{"extend-shallow":"^2.0.1"},"devDependencies":{"mocha":"*"},"keywords":["resolve","pattern","absolute","glob"],"verb":{"related":{"list":["is-glob","is-valid-glob","has-glob"]}},"gitHead":"42428d988edb8c0cd7d97fbc0622b9720dc57437","_id":"to-absolute-glob@0.1.0","_shasum":"e24acadac35f02b4d5905fae8acc8e333a15f67b","_from":".","_npmVersion":"3.3.6","_nodeVersion":"5.0.0","_npmUser":{"name":"jonschlinkert","email":"github@sellside.com"},"maintainers":[{"name":"jonschlinkert","email":"github@sellside.com"}],"dist":{"shasum":"e24acadac35f02b4d5905fae8acc8e333a15f67b","tarball":"http://registry.npmjs.org/to-absolute-glob/-/to-absolute-glob-0.1.0.tgz"},"directories":{}},"0.1.1":{"name":"to-absolute-glob","description":"Make a glob pattern absolute, ensuring that negative globs and patterns with trailing slashes are correctly handled.","version":"0.1.1","homepage":"https://github.com/jonschlinkert/to-absolute-glob","author":{"name":"Jon Schlinkert","url":"https://github.com/jonschlinkert"},"repository":{"type":"git","url":"git+https://github.com/jonschlinkert/to-absolute-glob.git"},"bugs":{"url":"https://github.com/jonschlinkert/to-absolute-glob/issues"},"license":"MIT","files":["index.js"],"main":"index.js","engines":{"node":">=0.10.0"},"scripts":{"test":"mocha"},"dependencies":{"extend-shallow":"^2.0.1"},"devDependencies":{"mocha":"*"},"keywords":["resolve","pattern","absolute","glob"],"verb":{"related":{"list":["is-glob","is-valid-glob","has-glob"]}},"gitHead":"42428d988edb8c0cd7d97fbc0622b9720dc57437","_id":"to-absolute-glob@0.1.1","_shasum":"1cdfa472a9ef50c239ee66999b662ca0eb39937f","_from":".","_npmVersion":"3.3.6","_nodeVersion":"5.0.0","_npmUser":{"name":"jonschlinkert","email":"github@sellside.com"},"maintainers":[{"name":"jonschlinkert","email":"github@sellside.com"}],"dist":{"shasum":"1cdfa472a9ef50c239ee66999b662ca0eb39937f","tarball":"http://registry.npmjs.org/to-absolute-glob/-/to-absolute-glob-0.1.1.tgz"},"directories":{}}},"readme":"# to-absolute-glob [![NPM version](https://badge.fury.io/js/to-absolute-glob.svg)](http://badge.fury.io/js/to-absolute-glob)\n\n> Make a glob pattern absolute, ensuring that negative globs and patterns with trailing slashes are correctly handled.\n\n## Install\n\nInstall with [npm](https://www.npmjs.com/)\n\n```sh\n$ npm i to-absolute-glob --save\n```\n\n## Usage\n\n```js\nvar toAbsGlob = require('to-absolute-glob');\ntoAbsGlob('a/*.js');\n//=> '/dev/foo/a/*.js'\n```\n\n## Examples\n\nGiven the current project folder (cwd) is `/dev/foo/`:\n\n**makes a path absolute**\n\n```js\ntoAbsGlob('a');\n//=> '/dev/foo/a'\n```\n\n**makes a glob absolute**\n\n```js\ntoAbsGlob('a/*.js');\n//=> '/dev/foo/a/*.js'\n```\n\n**retains trailing slashes**\n\n```js\ntoAbsGlob('a/*/');\n//=> '/dev/foo/a/*/'\n```\n\n**retains trailing slashes with cwd**\n\n```js\ntoAbsGlob('./fixtures/whatsgoingon/*/', {cwd: __dirname});\n//=> '/dev/foo/'\n```\n\n**makes a negative glob absolute**\n\n```js\ntoAbsGlob('!a/*.js');\n//=> '!/dev/foo/a/*.js'\n```\n\n**from a cwd**\n\n```js\ntoAbsGlob('a/*.js', {cwd: 'foo'});\n//=> '/dev/foo/foo/a/*.js'\n```\n\n**makes a negative glob absolute from a cwd**\n\n```js\ntoAbsGlob('!a/*.js', {cwd: 'foo'});\n//=> '!/dev/foo/foo/a/*.js'\n```\n\n**from a root path**\n\n```js\ntoAbsGlob('/a/*.js', {root: 'baz'});\n//=> '/dev/foo/baz/a/*.js'\n```\n\n**from a root slash**\n\n```js\ntoAbsGlob('/a/*.js', {root: '/'});\n//=> '/dev/foo/a/*.js'\n```\n\n**from a negative root path**\n\n```js\ntoAbsGlob('!/a/*.js', {root: 'baz'});\n//=> '!/dev/foo/baz/a/*.js'\n```\n\n**from a negative root slash**\n\n```js\ntoAbsGlob('!/a/*.js', {root: '/'});\n//=> '!/dev/foo/a/*.js'\n```\n\n## Related projects\n\n* [has-glob](https://www.npmjs.com/package/has-glob): Returns `true` if an array has a glob pattern. | [homepage](https://github.com/jonschlinkert/has-glob)\n* [is-glob](https://www.npmjs.com/package/is-glob): Returns `true` if the given string looks like a glob pattern or an extglob pattern.â€¦ [more](https://www.npmjs.com/package/is-glob) | [homepage](https://github.com/jonschlinkert/is-glob)\n* [is-valid-glob](https://www.npmjs.com/package/is-valid-glob): Return true if a value is a valid glob pattern or patterns. | [homepage](https://github.com/jonschlinkert/is-valid-glob)\n\n## Running tests\n\nInstall dev dependencies:\n\n```sh\n$ npm i -d && npm test\n```\n\n## Contributing\n\nPull requests and stars are always welcome. For bugs and feature requests, [please create an issue](/new).\n\n## Author\n\n**Jon Schlinkert**\n\n+ [github/jonschlinkert](https://github.com/jonschlinkert)\n+ [twitter/jonschlinkert](http://twitter.com/jonschlinkert)\n\n## License\n\nCopyright Â© 2015 Jon Schlinkert\nReleased under the MIT license.\n\n***\n\n_This file was generated by [verb-cli](https://github.com/assemble/verb-cli) on November 05, 2015._","maintainers":[{"name":"jonschlinkert","email":"github@sellside.com"}],"time":{"modified":"2015-11-05T21:03:56.171Z","created":"2015-11-05T17:00:28.352Z","0.1.0":"2015-11-05T17:00:28.352Z","0.1.1":"2015-11-05T21:03:56.171Z"},"homepage":"https://github.com/jonschlinkert/to-absolute-glob","keywords":["resolve","pattern","absolute","glob"],"repository":{"type":"git","url":"git+https://github.com/jonschlinkert/to-absolute-glob.git"},"author":{"name":"Jon Schlinkert","url":"https://github.com/jonschlinkert"},"bugs":{"url":"https://github.com/jonschlinkert/to-absolute-glob/issues"},"license":"MIT","readmeFilename":"readme.md","_attachments":{}}
41045 error If you need help, you may report this error at:
41045 error     <https://github.com/npm/npm/issues>
41046 verbose exit [ 1, true ]

**Comment by pedzed** [comment]
What are you trying to install?

**Comment by KenanY** [comment]
@ashish-pandey-tavant Is this still an issue for you?

**Comment by KenanY** [comment]
Closing as abandoned.
