### ISSUE TITLE
Shrinkwrap ordering inconsistent after multiple runs in 2.14.20

### ISSUE THREAD

**Issue by lostthetrail** [npm/npm#11842]
If you run shrinkwrap multiple times on the same code, you will get back a different npm-shrinkwrap.json file each time. The delta is object locations.

This causes code reviews to be overly onerous.

```
npm --version
2.14.20
```

**Comment by othiym23** [comment]
The team is working towards making the shrinkwrap process more consistent. We'll get there eventually, but there's still a ways to go. That said, `npm@3` includes [substantial improvements](https://github.com/npm/npm/blob/master/CHANGELOG.md#shrinkwraps-they-are-a-changin) that are tied to the changes to the installer code, which means they won't be backported to `npm@lts`. I believe that the churn you're describing doesn't exist when using shrinkwrap with `npm@3`, so updating should resolve your problem. Thanks for your time!
