### ISSUE TITLE
Bower install angular command failing with the error

### ISSUE THREAD

**Issue by manjeet82** [npm/npm#11843]
Hi,

When i try to install bower i get an error message as shown in the attached log file. have been trying a lot to understand how to get it to work, Can you please provide help with this issue.

[npm-debug.txt](https://github.com/npm/npm/files/166379/npm-debug.txt)

**Comment by jacobmischka** [comment]
```
346 verbose bad json <HEAD><TITLE>Authorization Required</TITLE></HEAD>
346 verbose bad json <BODY BGCOLOR="white" FGCOLOR="black"><H1>Authorization Required</H1><HR>
346 verbose bad json <FONT FACE="Helvetica,Arial"><B>
346 verbose bad json Description: Authorization is required for access to this proxy</B></FONT>
346 verbose bad json <HR>
346 verbose bad json <!-- default "Authorization Required" response (401) -->
346 verbose bad json </BODY>
```

Looks like a problem with your network configuration.

**Comment by pedzed** [comment]
@manjeet82 Is the problem solved now?

**Comment by manjeet82** [comment]
Thanks Jacob. yeah it was a network issue and also had to overwrite some config optiojn in git-config file

**Comment by manjeet82** [comment]
@ped yes the issue is resolved now

**Comment by pedzed** [comment]
> yes the issue is resolved now

Cool. You can close this issue then.
