### ISSUE TITLE
regarding connect installation 

### ISSUE THREAD

**Issue by Darshan00003** [npm/npm#11846]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli   'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'connect' ]
2 info using npm@3.6.0
3 info using node@v5.7.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData connect
8 silly fetchNamedPackageData connect
9 silly mapToRegistry name connect
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/connect
13 verbose request uri https://registry.npmjs.org/connect
14 verbose request no auth needed
15 info attempt registry request try #1 at 1:46:35 PM
16 verbose request id 36d5a6095c3b4f3a
17 http request GET https://registry.npmjs.org/connect
18 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
19 info attempt registry request try #2 at 1:46:56 PM
20 http request GET https://registry.npmjs.org/connect
21 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
22 info attempt registry request try #3 at 1:48:07 PM
23 http request GET https://registry.npmjs.org/connect
24 silly fetchPackageMetaData Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
24 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:856:11)
24 silly fetchPackageMetaData     at errnoException (dns.js:31:15)
24 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete](dns.js:77:26)
24 silly fetchPackageMetaData  error for connect { [Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443]
24 silly fetchPackageMetaData   code: 'EAI_AGAIN',
24 silly fetchPackageMetaData   errno: 'EAI_AGAIN',
24 silly fetchPackageMetaData   syscall: 'getaddrinfo',
24 silly fetchPackageMetaData   hostname: 'registry.npmjs.org',
24 silly fetchPackageMetaData   host: 'registry.npmjs.org',
24 silly fetchPackageMetaData   port: 443 }
25 silly rollbackFailedOptional Starting
26 silly rollbackFailedOptional Finishing
27 silly runTopLevelLifecycles Starting
28 silly runTopLevelLifecycles Finishing
29 silly install printInstalled
30 verbose stack Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
30 verbose stack     at Object.exports._errnoException (util.js:856:11)
30 verbose stack     at errnoException (dns.js:31:15)
30 verbose stack     at GetAddrInfoReqWrap.onlookup [as oncomplete](dns.js:77:26)
31 verbose cwd C:\Users\Darshan\WebstormProjects\untitled
32 error Windows_NT 6.1.7601
33 error argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "connect"
34 error node v5.7.1
35 error npm  v3.6.0
36 error code EAI_AGAIN
37 error errno EAI_AGAIN
38 error syscall getaddrinfo
39 error getaddrinfo EAI_AGAIN registry.npmjs.org:443
40 error If you need help, you may report this error at:
40 error     https://github.com/npm/npm/issues
41 verbose exit [ 1, true ]

**Comment by rchandrakar15** [comment]
same problem I am facing

**Comment by zkat** [comment]
Heya! Are you behind a proxy or firewall? You should consider [configuring npm to use your proxy](http://jjasonclark.com/how-to-setup-node-behind-web-proxy/). You need to be able to access https://registry.npmjs.org in order to use our public registry.
