### ISSUE TITLE
Check if module has already been added

### ISSUE THREAD

**Issue by pedro93** [npm/npm#11848]
Is it possible to change the way npm searches dependencies in package.json files and installs them?
I have a project where certain modules appear at different levels in the dependency tree.
By checking if a module already exists in the node_modules folder then npm should not install the module and proceed to the following dependency. 
I am not sure if this is already implemented, from my experience it does not seem to be.
```
project
│   node_modules/
└───package.json
    │   module_dependency1 //dependency already exists-> ignore
    │   module_dependency2
    │
    ├───package2.json
    │   │    module_dependency1 //download,compile module and put it in node_modules
    │   │    module_dependency3
    │   │   ...
```
Thank you for taking your time to read this.

**Comment by jacobmischka** [comment]
https://docs.npmjs.com/how-npm-works/npm3

**Comment by pedro93** [comment]
Thank you for the link, that was what I was looking for, there is just one pending question. What is the version difference allowed to not create nested dependencies? Does it follow the Semver standard and match minor versions as the same? Does it override to the latest version?

**Comment by zkat** [comment]
This looks like it answered any relevant questions, and it's been two weeks, so I'm closing it.
