### ISSUE TITLE
can't install tiny-trigger

### ISSUE THREAD

**Issue by jessehattabaugh** [npm/npm#11856]
When I run `$ npm install tiny-trigger` it stalls on `loadRequestedDeps -> netwo`. Eventually it times out and tries again. Other packages can install just fine. I've tried on two networks, so I don't think it's my connection.

**Comment by blindfish3** [comment]
+1
It's requesting the package from: 
https://registry.npmjs.org/tiny-trigger/-/tiny-trigger-0.1.3.tgz
My browser returns: {"error":"package could not be found."}

**Comment by blindfish3** [comment]
Have raised an issue with the author: [tiny-trigger/issues/4](https://github.com/scottcorgan/tiny-trigger/issues/4)

**Comment by zkat** [comment]
Looks like the tarball disappeared! :o I've notified the registry folks. Thanks for the report!

**Comment by jessehattabaugh** [comment]
I'm still experiencing this issue
