### ISSUE TITLE
Problem to install with npm

### ISSUE THREAD

**Issue by javiersvela** [npm/npm#11851]
I have a problem in the instalation of the node dht sensor with npm.

I change the permissions of the directories but the problem persist.

Copied the log:

pi@raspberrypi:~ $ sudo su
root@raspberrypi:/home/pi# sudo chown -R `whoami` ~/.npm
root@raspberrypi:/home/pi# sudo chown -R `whoami` /usr/local/lib/node_modules
root@raspberrypi:/home/pi# sudo npm install -g node-dht-sensor
\

> node-dht-sensor@0.0.11 preinstall /usr/local/lib/node_modules/node-dht-sensor
> ./preinst

Library bcm2835 found.
Installing Native Abstractions for Node.js (NAN)...
npm ERR! Error: Attempt to unlock nan, which hasn't been locked
npm ERR!     at unlock (/usr/share/npm/lib/utils/locker.js:44:11)
npm ERR!     at cb (/usr/share/npm/lib/cache/add-local.js:30:5)
npm ERR!     at /usr/share/npm/lib/cache/add-local.js:47:20
npm ERR!     at /usr/share/npm/lib/utils/locker.js:22:20
npm ERR!     at /usr/share/npm/node_modules/inflight/inflight.js:22:7
npm ERR!     at Array.forEach (native)
npm ERR!     at res (/usr/share/npm/node_modules/inflight/inflight.js:21:9)
npm ERR!     at /usr/lib/nodejs/once.js:17:15
npm ERR!     at afterMkdir (/usr/share/npm/lib/cache/get-stat.js:53:14)
npm ERR!     at /usr/lib/nodejs/mkdirp/index.js:46:53
npm ERR! If you need help, you may report this _entire_ log,
npm ERR! including the npm and node versions, at:
npm ERR!     http://github.com/npm/npm/issues

npm ERR! System Linux 4.1.18-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "nan"
npm ERR! cwd /usr/local/lib/node_modules/node-dht-sensor
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21

Thanks for the help!!

**Comment by pedzed** [comment]
Installing packages as root is really bad practice. It can be quite dangerous. 

I recommend using #11783 and updating npm.
```
npm -g install npm
```

**Comment by javiersvela** [comment]
Hello!

I have made recommendations yours, but I have another error:

pi@raspberrypi:~ $ sudo npm install -g node-dht-sensor
npm WARN lifecycle node-dht-sensor@0.0.11~preinstall: cannot run in wd %s %s (wd=%s) node-dht-sensor@0.0.11 ./preinst /root/.local/share/npm/lib/node_modules/.staging/node-dht-sensor-ca3406a3
/root/.local/share/npm/lib
└── node-dht-sensor@0.0.11 

Thanks for your help.

**Comment by pedzed** [comment]
Have you tried Google? "preinstall: cannot run in wd"

https://stackoverflow.com/questions/18136746/npm-install-failed-with-cannot-run-in-wd

Try
```
sudo npm -g install node-dht-sensor --unsafe-perm=true
```
