### ISSUE TITLE
'npm test' error in windows

### ISSUE THREAD

**Issue by fpmalard** [npm/npm#11850]
When trying to run 'npm test' it seems it can't find the 'make' tool.
Even if I just call 'make -v' it returns 'make' as not recognized as internal or external command.

<img width="1440" alt="error_vs2015" src="https://cloud.githubusercontent.com/assets/818592/13680904/6d1c9386-e6d9-11e5-8950-e2e0d55f7c93.png">

Nodejs version 5.8.0
Windows 10, x64
Visual Studio 2013 or 2015
Running Node.js Tools version 1.1

**Comment by fpmalard** [comment]
It seems by installing MinGW and adding the following folder to my PATH environment variable did the trick:

C:\MinGW\msys\1.0\bin

Now the 'npm test' call works and runs the test module accordingly.

Can anyone confirm this?
Should Nodejs package for windows recommend MinGW or include it on its default installation?

Regards.

**Comment by zkat** [comment]
`make` isn't included by default in MinGW or Git Bash. You'll have to [install it yourself](http://gnuwin32.sourceforge.net/packages/make.htm). Let me know if that helps at all!

**Comment by busches** [comment]
@fpmalard what project were you running `npm test` with? `npm` itself does not require `make` but certain projects may, ideally they would inform you of this.
