### ISSUE TITLE
Installing “agda-mode@0.4.10” failed

### ISSUE THREAD

**Issue by stephanalexanderspahn** [npm/npm#11860]
hello,
I received the following error message while attempting to install the agda-mode in Atom

npm ERR! Command failed: Cloning into bare repository '/Users/Stephan/.atom/.apm/_git-remotes/git-github-com-kanaka-miniMAL-git-03f74218'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.130]: errno=Connection refused

**Comment by KenanY** [comment]
To me, this looks like an issue with your internet connection

```
npm ERR! fatal: unable to connect to github.com:
```

ensure that you do not have a proxy or firewall blocking your connection to `github.com` or the `git:` protocol.

**Comment by zkat** [comment]
As @KenanY said, this is almost certainly an issue connecting to github itself (and the IP looks correct, so it's not a DNS issue). It's also more relevant to [apm, Atom's package manager](https://github.com/atom/apm), which is a separate thing from npm. As such, I'm going to close this.

As a potential clue, you might want to look into any proxy settings you have, specially for git.
