### ISSUE TITLE
node_modules ignore not mentioned

### ISSUE THREAD

**Issue by Jameskmonger** [npm/npm#11863]
In the [files section of the npm website](https://docs.npmjs.com/files/package.json#files), there is no mention of `node_modules` being ignored when publishing to npm.

**Comment by KenanY** [comment]
This was resolved by https://github.com/npm/npm/pull/11884. Thanks!

**Comment by KenanY** [comment]
Actually I'm gonna reopen this since it isn't live yet: https://docs.npmjs.com/files/package.json#files
