### ISSUE TITLE
Add command equivalent to "rm -fr ./node_modules"

### ISSUE THREAD

**Issue by gajus** [npm/npm#11867]
`rm -fr ./node_modules` has become a common command to type. It would be nice to have it in npm program: a command to remove the local `./node_modules` directory.

This could be done using `npm remove` command (without a package name) or using a new command altogether (e.g. `npm truncate`).

**Comment by pedzed** [comment]
`npm uninstall PACKAGE_NAME` already exists, so why not `npm uninstall` to remove everything?

**Comment by cbrwizard** [comment]
I agree that there is no need to add a new command as `uninstall` already exists for the role to remove packages.
However, letting command `npm uninstall` to remove everything is _scary_. What if someone uses that by mistake? Here are my ideas:

**Option A**. Let's add a confirmation after user writes `npm uninstall`.
```shell
$ npm uninstall
- This will remove all packages inside a local node_modules directory. Are you sure you want to continue? (y/n).
$ y
```
Let's also add a `-f` `--force` flag to this command which removes all packages without the confirmation.

**Option B**. Let's add a support for the wildcard for this command. This is explained [here](https://github.com/npm/npm/issues/10385). This way you will need to run
```shell
$ npm uninstall '*'
```
To remove all packages.

**Comment by gajus** [comment]
What is "scary" about it?

**Comment by gajus** [comment]
There is nothing "scary" about deleting the entire `./node_modules` folder even if you have done it by accident. There should be no confirmation prompt.

Simple:

```sh
npm uninstall
```

should delete `./node_modules` path in the current working directory.

**Comment by othiym23** [comment]
If you want to bring the current `node_modules` into sync with what's in `package.json`, you can use `npm prune` (or if you want to strip out `devDependencies`, you can use `npm prune --production`. If you want to ensure that the package tree is in the correct state, you can run `npm install`. If you want to add or remove packages from `package.json` `dependencies` or `devDependencies`, you can use `--save` or `--save-dev` with `npm install` or `npm uninstall`. Those are all the common cases in which npm directly manages the set of packages in `node_modules`, and if there are situations in which running those commands produces incorrect or inconsistent trees, those are serious issues with the installer that should be filed as issues and / or patched.

If you really want to get out of the car and get back in again, `rm -rf node_modules` or `npm install -g rimraf ; rimraf node_modules` are pretty easy ways to do this. I don't think it makes sense to add such a blunt-force tool to npm itself, and so I'm going to close this feature request. Thanks for your time!

**Comment by pedzed** [comment]
> Thanks for your time!

Thanks for your time.


> If you want to add or remove packages from package.json dependencies or devDependencies, you can use --save or --save-dev with npm install or npm uninstall.

Correction: `npm uninstall PACKAGE_NAME`. You cannot do `npm uninstall` to remove all packages.
