### ISSUE TITLE
Problem with find Java Objects

### ISSUE THREAD

**Issue by TiREX69** [npm/npm#11864]
Hi, i must find packages for node.js with  objects similar to ObjectOutputStream and ObjectInputStream in java.

Sorry, for my bad english.

Regards
Szymon

**Comment by zkat** [comment]
Heya! npm is for code written in JavaScript, which is a completely different language than Java, and does not share any packages. You may want to look into something like [Maven](http://maven.apache.org/).

I'm gonna close this as it really doesn't pertain to us. Good luck!
