### ISSUE TITLE
Application start issue

### ISSUE THREAD

**Issue by pradip3661** [npm/npm#11865]
when i have execute "npm start", i got this issue. Please help me, If any mistake in installation or project creation than please tell me step for that.

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.14.12
3 info using node@v4.2.6
4 verbose stack Error: missing script: start
4 verbose stack     at run (C:\Program Files (x86)\nodejs\node_modules\npm\lib\run-script.js:142:19)
4 verbose stack     at C:\Program Files (x86)\nodejs\node_modules\npm\lib\run-script.js:58:5
4 verbose stack     at C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:345:5
4 verbose stack     at checkBinReferences_ (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:309:45)
4 verbose stack     at final (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:343:3)
4 verbose stack     at then (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:113:5)
4 verbose stack     at ReadFileContext.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:284:20)
4 verbose stack     at ReadFileContext.callback (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:76:16)
4 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:303:13)
5 verbose cwd D:\Electron\Helloworld
6 error Windows_NT 6.2.9200
7 error argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
8 error node v4.2.6
9 error npm  v2.14.12
10 error missing script: start
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
Hello @pradip3661!

```
10 error missing script: start
```

Do you have a `"start"` script defined in your `package.json`?

**Comment by othiym23** [comment]
As @KenanY said, in order for `npm start` to work, you'll need a `"start"` script defined in the `"scripts"` section of the `package.json` file in the current working directory. Add that, and the script should work! As such, I'm going to close this issue. Thanks for your time, and good luck!

**Comment by pradip3661** [comment]
Thanks @KenanY and othiym23..
This in package.json file....please tell how can resolve this problem.

{
  "name": "helloworld",
  "version": "1.0.0",
  "description": "",
  "main": "main.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/pradip3661/electron-app.git"
  },
  "author": "",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/pradip3661/electron-app/issues"
  },
  "homepage": "https://github.com/pradip3661/electron-app#readme",
  "devDependencies": {
    "electron-prebuilt": "^0.36.11"
  }
}

**Comment by KenanY** [comment]
@pradip3661 Here's the important bit:

``` json
"scripts": {
  "test": "echo \"Error: no test specified\" && exit 1"
},
```

So, you have a `"test"` script defined (this is the default one), but you do not have a `"start"` script. You'll want to do something like

``` json
"scripts": {
  "test": "echo \"Error: no test specified\" && exit 1",
  "start": " "
},
```

Where you will fill out the blank space with the command that you want `npm` to run when you do `npm start`.

**Comment by pradip3661** [comment]
Thanks its work....but output window is not appearing.

Is ther any mistake in project structure?

**Comment by KenanY** [comment]
@pradip3661 Maybe.

**Comment by pradip3661** [comment]
This is my project structure
rootfolder
--app
-- --index.html
--node_modules
--main.js
--package.json

**Comment by pradip3661** [comment]
can you gauid me about project structure????
please

**Comment by KenanY** [comment]
@pradip3661 Ask other electron users.
