### ISSUE TITLE
npm can't install in visual studio 2015 , 

### ISSUE THREAD

**Issue by banukusuma** [npm/npm#11873]
i build ionic new project in visual studio 2015 , but it have some problem in npm installation

![capture](https://cloud.githubusercontent.com/assets/8449463/13721201/19113c1e-e851-11e5-8359-55c67d2111bf.PNG)

**Comment by pedzed** [comment]
Why did you mention Visual Studio 2015? Does it work in 2013? Does it work using CMD?

This looks like [a duplicate](https://github.com/npm/npm/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+ionic).
#11777
#11739
#11720
#11660
#11257
And many more.
