### ISSUE TITLE
Can't update npm on ubuntu 12.04

### ISSUE THREAD

**Issue by ast0708** [npm/npm#11877]
When I run the update command - 
npm update -g npm

I get the following error

npm ERR! Linux 3.8.0-44-generic
npm ERR! argv "/root/.nvm/versions/node/v5.8.0/bin/node" "/root/.nvm/versions/node/v5.8.0/bin/npm" "update" "-g" "npm"
npm ERR! node v5.8.0
npm ERR! npm  v3.7.3
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on http://registry.npmjs.org/karma/npm
npm ERR! 404 
npm ERR! 404  'karma' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/atul/dev/piggy/npm-debug.log

Thanks in advace

**Comment by pedzed** [comment]
Update didn't work for me either. You could update with `install`, unless you're on Windows.
```
npm -g install npm
```

**Comment by ast0708** [comment]
That also is not working, giving the same error. Thanks

**Comment by pedzed** [comment]
Try this:
```
sudo apt-get remove nodejs ^node-* nodejs-*
sudo apt-get autoremove
sudo apt-get clean
curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -
sudo apt-get install nodejs
```

Then run this:
```
curl https://raw.githubusercontent.com/creationix/nvm/v0.31.0/install.sh | sh
```
*For future readers, obviously you should [use the latest release](https://github.com/creationix/nvm/releases) instead of v0.31.0.*

After this, open a new terminal and check the npm version:
```
npm --version
```
Does that work?
