### ISSUE TITLE
npm install issue 800+ parallel request same time

### ISSUE THREAD

**Issue by GongT** [npm/npm#11878]
```
[root angular]# npm install
npm info it worked if it ends with ok
npm info using npm@3.7.3
npm info using node@v5.8.0
npm info retry fetch attempt 1 at 23:12:55
npm info attempt registry request try #1 at 23:12:55
npm http fetch GET http://registry.npmjs.org/abbrev/-/abbrev-1.0.7.tgz
npm info retry fetch attempt 1 at 23:12:55
npm info attempt registry request try #1 at 23:12:55
npm http fetch GET http://github.com/component/global/archive/v2.0.1.tar.gz
npm info retry fetch attempt 1 at 23:12:55
npm info attempt registry request try #1 at 23:12:55
npm http fetch GET http://github.com/rase-/node-XMLHttpRequest/archive/a6b6f2.tar.gz
*********** (800+ times repeat of these 3 lines fetching different package) ***********
npm info attempt registry request try #1 at 23:12:55
npm http fetch GET http://registry.npmjs.org/punycode/-/punycode-1.4.0.tgz
npm info retry fetch attempt 1 at 23:12:55
npm info attempt registry request try #1 at 23:12:55
npm http fetch GET http://registry.npmjs.org/pseudomap/-/pseudomap-1.0.1.tgz
npm info retry fetch attempt 1 at 23:12:55
^C
[root angular]#
```

registry.npmjs.org will return 503 error when I connect directly

my proxy server will ban my client immediately when I using proxy

**Comment by zkat** [comment]
Hey! So as of `npm@3.8.0` and `npm@2.15.0` (for LTS), there's a [`maxsockets` option in npm](https://github.com/npm/npm/pull/11666).

It defaults to `50`, but can be made even lower, depending on the needs of your proxy server. I hope this solves your problem! I'm closing this as resolved, since I'm pretty sure this addresses the reported problem. :) Let me know if there's anything else or if this doesn't help!

**Comment by jgreen210** [comment]
maxsockets doesn't affect the number of connections made to HTTP proxies: https://github.com/npm/npm/issues/18903

**Comment by mk-pmb** [comment]
In case you missed it in the other thread, I made a guarding proxy that limits connections to its upstream proxy: [tcpfwd-maxconc-pmb](https://www.npmjs.com/package/tcpfwd-maxconc-pmb)
