### ISSUE TITLE
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

### ISSUE THREAD

**Issue by pubmikeb** [npm/npm#11876]
I'm trying to execute recursive update of all Node.js modules with:
`npm update --depth 50`

But get the following error message:

> <--- Last few GCs --->
> 
>   306256 ms: Scavenge 1375.9 (1458.1) -> 1375.9 (1458.1) MB, 7.1 / 0 ms (+ 2.0 ms in 1 steps since last GC) [allocation failure] [incremental marking delaying mark-sweep].
>   307234 ms: Mark-sweep 1375.9 (1458.1) -> 1375.9 (1458.1) MB, 978.0 / 1 ms (+ 58.0 ms in 184 steps since start of marking, biggest step 3.0 ms) [last resort gc].
>   308252 ms: Mark-sweep 1375.9 (1458.1) -> 1375.9 (1458.1) MB, 1017.8 / 0 ms [last resort gc].
> 
> <--- JS stacktrace --->
> 
> ==== JS stack trace =========================================
> 
> Security context: 00000152B4FE3AD1 <JS Object>
>     1: start [C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:~720] [pc=0000033E9544D569](this=000000E807083DC9 <a Request with map 000000F898616271)
>     2: end [C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:~1373] [pc=0000033E955A9810](this=000000E807083DC9 <a Request with map 000000F898616271>,chunk=00000152B4F04189 <undefined)
>     3: ...
> 
> FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

This error doesn't occur if I specify the depth value as 30.
On StackOverflow I read that for the complete recursive update I have to specify the depth value as 9999, but how it can be possible if even the 50 depth causes to memory allocation issue.

My laptop has 8 GB of RAM, Windows 10 x64, NPM 3.8.1.

**Comment by pedzed** [comment]
Could you give some more information? Is there a `npm-debug.log` you could post?

**Comment by pubmikeb** [comment]
I tried to reproduce the case again with `npm update --depth 30` and got the same error:

> <--- Last few GCs --->
> 
>   379787 ms: Scavenge 1408.7 (1458.1) -> 1408.7 (1458.1) MB, 16.4 / 0 ms (+ 3.0 ms in 1 steps since last GC) [allocation failure] [incremental marking delaying mark-sweep].
>   380989 ms: Mark-sweep 1408.7 (1458.1) -> 1408.7 (1458.1) MB, 1201.8 / 0 ms (+ 4.0 ms in 2 steps since start of marking, biggest step 3.0 ms) [last resort gc].
>   382117 ms: Mark-sweep 1408.7 (1458.1) -> 1408.7 (1458.1) MB, 1128.8 / 0 ms [last resort gc].
> 
> <--- JS stacktrace --->
> 
> ==== JS stack trace =========================================
> 
>     2: arguments adaptor frame: 1->2
> Security context: 00000097411E3AD1 <JS Object>
>     3: connect [_tls_wrap.js:1003] [pc=00000253FF4D30EA] (this=000002FAFD3A5541 <an Object with map 00000047E09A7161>)
>     4: arguments adaptor frame: 2->0
>     5: createConnection [https.js:~50] [pc=00000253FF2208F8] (this=0000014589792C79 <an Agent with map 00000047E09A7D11>,port=0000002DC537FDA1 <an Object with map 000003C50E299561>,host=0000002DC537FDB9...
> 
> FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

I checked the Task manager during the update and paid attention that Node.js consumes something about **1.8 GB** of RAM. It is too much just for a simple update process, isn't? It looks like memory leak.

Where I can find `npm-debug.log`?

![12_214216](https://cloud.githubusercontent.com/assets/17231333/13724889/1559d72a-e89c-11e5-9262-89324d239908.png)

**Comment by pedzed** [comment]
![NodeJS RAM](https://cloud.githubusercontent.com/assets/8146593/13728486/eb72c168-e91a-11e5-82ec-6560dc0f82e3.png)

**Comment by pubmikeb** [comment]
Hm, looks fine.
I have Core i5 Ivy Bridge, 8 GB RAM.

My reproduction steps:

1. Go to https://nodejs.org, install Node.js 5.8.0
2. Install Node.js
3. Update NPM to the latest version
```
cd C:\Program Files\nodejs
npm install npm@latest --save
```
4. Install `npm-check-updates`: npm install -g npm-check-updates@latest --save
5. Execute modules update:
```
cd C:\Program Files\nodejs\node_modules\npm
ncu -a
npm update --depth 50
```

And get the error.

**Comment by gingur** [comment]
Same issue
```
npm outdated -depth=999

<--- Last few GCs --->

 1215813 ms: Scavenge 1391.2 (1458.0) -> 1391.2 (1458.0) MB, 1.1 / 0 ms (+ 7.0 ms in 2 steps since last GC) [allocation failure] [incremental marking delaying mark-sweep].
 1216958 ms: Mark-sweep 1391.2 (1458.0) -> 1388.0 (1458.0) MB, 1139.2 / 0 ms (+ 14.0 ms in 4 steps since start of marking, biggest step 6.0 ms) [last resort gc].
 1217950 ms: Mark-sweep 1388.0 (1458.0) -> 1288.2 (1458.0) MB, 991.9 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 000001FE6DBB4639 <JS Object>
    1: fromString(aka fromString) [buffer.js:110] [pc=0000003D8010C3C8] (this=000001FE6DB041B9 <undefined>,string=000003E150CC5E31 <Very long string[146394]>,encoding=000001FE6DBBC241 <String[4]: utf8>)
    2: new constructor(aka Buffer) [buffer.js:59] [pc=0000003D71B43D67] (this=00000238F3E584A9 <a Buffer with map 000000207BC17299>,arg=000003E150CC5E31 <Very long string[146394]>,encoding=000...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory```

**Comment by JerryFox1** [comment]
has this been fixed?

**Comment by chrstfer** [comment]
I am running windows 7, and on both [Babun](http://babun.github.io/) and Powershell I get this error for every call to npm I make. I did a full uninstall (including searching for any folders in AppData and deleting them, then reinstalled using all the defaults. I still get the error. So I did another complete uninstall, reinstalled to a nonstandard directory with no spaces and I continue to get the error. The same output is observed across all these installs, so I will only post the latest. 

```
{ ~ }  » npm install gitbook-cli -g                                                                    [ 2:57PM ]
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
{ ~ }  » npm install -g npm-check-updates@latest --save                                            [ 3:01PM ] 3
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
{ ~ }  » npm --help                                                                                  [ 3:07PM ] 3
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
{ ~ }  »                                                                                             [ 3:08PM ] 3
```

Note that the right prompt consists of the time and any error code returned by the last process, so the error code returned is `3`. The command appears to try twice, and runs into the ceiling both times. During the time it is running, it is using around ~15-20 cpu cycles, as reported by windows task manager; it quickly increases in memory consumption to around 1,500,000 Kb, then the process dies and reports the error. After the second try my prompt is returned. 

As you can see, it's not only relegated to install commands; indeed, even "--help" gives me this error, as does trying to tab complete npm. 

I will be looking into this, but I cant promise anything. Feel free to ask any questions, and make any comments or suggestions. If there is any more information (will be looking at my logs soon, and reporting back) that could be of use, ask for it. 

An interesting development: 

```
{ debugging }  » git clone https://github.com/npm/npm.git                                              [ 3:16PM ]
Cloning into 'npm'...
remote: Counting objects: 55737, done.
remote: Compressing objects: 100% (226/226), done.
remote: Total 55737 (delta 124), reused 3 (delta 3), pack-reused 55508
Receiving objects: 100% (55737/55737), 29.27 MiB | 2.53 MiB/s, done.
Resolving deltas: 100% (30625/30625), done.
Checking connectivity... done.
{ debugging }  » cd npm                                                                                [ 3:17PM ]
{ npm } master » ls                                                                                    [ 3:17PM ]
AUTHORS  CHANGELOG.md  cli.js     CONTRIBUTING.md  html  LICENSE   Makefile      package.json  scripts
bin      changelogs    configure  doc              lib   make.bat  node_modules  README.md     test
{ npm } master » make                                                                                  [ 3:17PM ]
scripts/doc-build.sh doc/cli/npm-access.md man/man1/npm-access.1
make[1]: Entering directory '/cygdrive/m/Projects/debugging/npm'
node cli.js install marked-man --no-global
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
Makefile:151: recipe for target 'node_modules/.bin/marked-man' failed
make[1]: *** [node_modules/.bin/marked-man] Error 3
make[1]: Leaving directory '/cygdrive/m/Projects/debugging/npm'
Makefile:96: recipe for target 'man/man1/npm-access.1' failed
make: *** [man/man1/npm-access.1] Error 2
{ npm } master »                                                                                     [ 3:18PM ] 2
```

Altogether this looks like a Node.js bug to me, but `node -e 'console.log("hello");'` runs fine (though I realize that's a terrible test case, I just don't know what would be a good one). Will continue investigating. 

*_FINAL EDIT: So, apparently when an .npmrc refers to a location that no longer exists (on a drive that is no longer installed), the npm doesn't notice that and doesn't like it at all. I propose that it should check all paths before attempting to use them. That being said, my issue cleared up when I cleared a rogue .npmrc (in my windows home folder) that was referring to an old install. I don't know if that was a cause of this error in the other comments here, but it might generally be a good thing to check that all addresses and directories exist and are accessible (that may be why requests.js was implicated above). *_

**Comment by martianmartian** [comment]
I hope you all get spammed

Sent from my iPhone

On Apr 23, 2016, at 3:10 PM, Christopher Carrigan Brolly <notifications@github.com<mailto:notifications@github.com>> wrote:


I am running windows 7, and on both Babun<http://babun.github.io/> and Powershell I get this error for every call to npm I make. I did a full uninstall (including searching for any folders in AppData and deleting them, then reinstalled using all the defaults. I still get the error. So I did another complete uninstall, reinstalled to a nonstandard directory with no spaces and I continue to get the error. The same output is observed across all these installs, so I will only post the latest.

{ ~ }  > npm install gitbook-cli -g                                                                    [ 2:57PM ]
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
{ ~ }  > npm install -g npm-check-updates@latest --save                                            [ 3:01PM ] 3
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
{ ~ }  > npm --help                                                                                  [ 3:07PM ] 3
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
{ ~ }  >                                                                                             [ 3:08PM ] 3


Note that the right prompt consists of the time and any error code returned by the last process, so the error code returned is 3. The command appears to try twice, and runs into the ceiling both times. During the time it is running, it is using around ~15-20 cpu cycles, as reported by windows task manager; it quickly increases in memory consumption to around 1,500,000 Kb, then the process dies and reports the error. After the second try my prompt is returned.

As you can see, it's not only relegated to install commands; indeed, even "--help" gives me this error, as does trying to tab complete npm.

I will be looking into this, but I cant promise anything. Feel free to ask any questions, and make any comments or suggestions.

-

**Comment by leedm777** [comment]
I've run into a similar issue (#15393) with `npm outdated` that appear to be related to cyclic dependencies. OP and others: think this might be related?
