### ISSUE TITLE
NPM unable to find installed package

### ISSUE THREAD

**Issue by NullDivision** [npm/npm#11879]
This is an issue i ran into on version 3.8.0 of NPM with Node version 5.8.0.

With my script containing:

```
"scripts": {"lint": "eslint ./src"}
# ...reduced for brevity's sake
"devDependencies": {"eslint": "^2.3.0"}
```

After running `npm i && npm run lint` I get the error `eslint: not found`.

I checked and `node_modules/.bin` contains the eslint binary. The result is the same with all packages that I run from the scripts section.

**Comment by zkat** [comment]
heya -- I tried this on `npm@3.8.0` with a minimal package and was unable to reproduce this, with `eslint@2.3.0`. Do you have more details? Perhaps a `npm-debug.log`?

**Comment by NullDivision** [comment]
The issue has nothing to do with eslint. On NPM 3.8.0 if I run a script declared in package.json (eg. `npm  run somescript`) any command declared in `somescript`throws because it can't find the package unless it's installed globally.

To reproduce, do you already have eslint installed globally @zkat?

**Comment by zkat** [comment]
Can you manually run `$(npm bin)/eslint ./src` from your project?

**Comment by zkat** [comment]
Also: `npm run env | grep PATH | grep node_modules/.bin` does this return anything?

**Comment by NullDivision** [comment]
Sorry for the horribly long wait but I had to abandon the issue for a bit.

`$(npm bin)/eslint ./src` works fine. `npm bin` displays the right path.

`npm run env | grep PATH | grep node_modules/.bin` returns `PATH=/usr/lib/node_modules/npm/bin/node-gyp-bin:/var/lib/jenkins/jobs/ATB/branches/task%2FATB-912/workspace/node_modules/.bin:/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games`
