### ISSUE TITLE
Unable to install a module via npm install command

### ISSUE THREAD

**Issue by ohmtrivedi** [npm/npm#11886]
I am trying to install the following module: ewd-vista-rpc
I am using the dEWDrop virtual machine. I checked that apt-get update executed properly. Also, I am able to ping to various hostnames.

But, I get the following errors when I execute the command - npm install ewd-vista-rpc.
I tried to find solutions on web, but couldn't find any. Please help.

vista@dEWDrop:~$ npm install ewd-vista-rpc
npm ERR! Linux 3.2.0-36-virtual
npm ERR! argv "/home/vista/.nvm/versions/node/v4.2.6/bin/node" "/home/vista/.nvm/versions/node/v4.2.6/bin/npm" "install" "ewd-vista-rpc"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12

npm ERR! Hostname/IP doesn't match certificate's altnames: "Host: registry.npmjs.org. is not in the cert's altnames: DNS:*.fau.edu, DNS:fau.edu"
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vista/npm-debug.log

The npm-debug file is as follows:

0 info it worked if it ends with ok
1 verbose cli [ '/home/vista/.nvm/versions/node/v4.2.6/bin/node',
1 verbose cli   '/home/vista/.nvm/versions/node/v4.2.6/bin/npm',
1 verbose cli   'install',
1 verbose cli   'ewd-vista-rpc' ]
2 info using npm@2.14.12
3 info using node@v4.2.6
4 verbose config Skipping project config: /home/vista/.npmrc. (matches userconfig)
5 verbose install initial load of /home/vista/package.json
6 verbose readDependencies loading dependencies from /home/vista/package.json
7 silly cache add args [ 'ewd-vista-rpc', null ]
8 verbose cache add spec ewd-vista-rpc
9 silly cache add parsed spec Result {
9 silly cache add   raw: 'ewd-vista-rpc',
9 silly cache add   scope: null,
9 silly cache add   name: 'ewd-vista-rpc',
9 silly cache add   rawSpec: '',
9 silly cache add   spec: 'latest',
9 silly cache add   type: 'tag' }
10 silly addNamed ewd-vista-rpc@latest
11 verbose addNamed "latest" is being treated as a dist-tag for ewd-vista-rpc
12 info addNameTag [ 'ewd-vista-rpc', 'latest' ]
13 silly mapToRegistry name ewd-vista-rpc
14 silly mapToRegistry using default registry
15 silly mapToRegistry registry https://registry.npmjs.org/
16 silly mapToRegistry uri https://registry.npmjs.org/ewd-vista-rpc
17 verbose addNameTag registry:https://registry.npmjs.org/ewd-vista-rpc not in flight; fetching
18 verbose request uri https://registry.npmjs.org/ewd-vista-rpc
19 verbose request no auth needed
20 info attempt registry request try #1 at 7:48:33 PM
21 verbose request id b3edcb7703d45c1e
22 http request GET https://registry.npmjs.org/ewd-vista-rpc
23 info retry will retry, error on last attempt: Error: Hostname/IP doesn't match certificate's altnames: "Host: registry.npmjs.org. is not in the cert's altnames: DNS:*.fau.edu, DNS:fau.edu"
24 info attempt registry request try #2 at 7:48:43 PM
25 http request GET https://registry.npmjs.org/ewd-vista-rpc
26 info retry will retry, error on last attempt: Error: Hostname/IP doesn't match certificate's altnames: "Host: registry.npmjs.org. is not in the cert's altnames: DNS:*.fau.edu, DNS:fau.edu"
27 info attempt registry request try #3 at 7:49:43 PM
28 http request GET https://registry.npmjs.org/ewd-vista-rpc
29 verbose stack Error: Hostname/IP doesn't match certificate's altnames: "Host: registry.npmjs.org. is not in the cert's altnames: DNS:*.fau.edu, DNS:fau.edu"
29 verbose stack     at Object.checkServerIdentity (tls.js:186:15)
29 verbose stack     at TLSSocket.<anonymous> (_tls_wrap.js:1022:29)
29 verbose stack     at emitNone (events.js:67:13)
29 verbose stack     at TLSSocket.emit (events.js:166:7)
29 verbose stack     at TLSSocket._finishInit (_tls_wrap.js:585:8)
30 verbose cwd /home/vista
31 error Linux 3.2.0-36-virtual
32 error argv "/home/vista/.nvm/versions/node/v4.2.6/bin/node" "/home/vista/.nvm/versions/node/v4.2.6/bin/npm" "install" "ewd-vista-rpc"
33 error node v4.2.6
34 error npm  v2.14.12
35 error Hostname/IP doesn't match certificate's altnames: "Host: registry.npmjs.org. is not in the cert's altnames: DNS:*.fau.edu, DNS:fau.edu"
36 error If you need help, you may report this error at:
36 error     <https://github.com/npm/npm/issues>
37 verbose exit [ 1, true ]

**Comment by amandeepmittal** [comment]
Do you "root" rights to install it? Or is it a local package/dependency for a project?

**Comment by ohmtrivedi** [comment]
I have root rights on the Ubuntu machine. Also, the module ewd-vista-rpc, its not local, it is freely available here -> https://github.com/robtweed/ewd-vista-rpc

**Comment by amandeepmittal** [comment]
@ohmtrivedi looks like a DNS issue to me. Is there a proxy server on your network? Also, try updateing your node and npm versions...

**Comment by zkat** [comment]
Like @amandeepmittal said, this looks like a DNS issue with `fau.edu` putzing around with your requests and causing TLS issues because of that.

**Comment by ohmtrivedi** [comment]
It was a mere update isse with nvm. I updated it to the late 0.31. And everything else worked. Thanks!

**Comment by zkat** [comment]
Awesome! I'm glad it's fixed! :)
