### ISSUE TITLE
node-red-contrib-ui install on raspberry pi

### ISSUE THREAD

**Issue by Neil20** [npm/npm#11882]
having problems installing the contrib-ui keep getting error any help would be great.
[npm-debug.txt](https://github.com/npm/npm/files/170901/npm-debug.txt)

**Comment by pedzed** [comment]
Using npm v3.8.1 on Linux, am I right? Before somebody looks at the 22.5k lines of debug log, could you briefly explain what happened? Did it work before?

**Comment by Neil20** [comment]
Hi, i’m new to Node-red and have only just started using it.  Node-red is working just fine and this was the first attempt as getting the ui part up and running.

 

Running Raspbian Jessie as shown below

 



 

I followed examples on how to install the node-red-contrib-ui on to a raspberry pi.



http://localhost:1880/ui gives “Cannot get /ui”

 

and 

http://localhost:1880/ shows node-red with ui controls at the bottom

 

end of error log shows this which is the only errors i see on the pi during the install

 

16746 error Linux 4.1.17+

16747 error argv "node" "/usr/local/bin/npm" "install"

16748 error node v0.10.29

16749 error npm  v3.8.1

 

Hope this helps and thanks for the prompt reply

**Comment by pedzed** [comment]
I have no clue. Are you sure this is an npm problem?

Perhaps if you could post the commands you entered, I could try to reproduce (in Ubuntu).

**Comment by Neil20** [comment]
Not sure what the problem was, re-installed the operating system on the PI-1 and then re-installed Node-red, npm, and then the contrib-ui.

Now works and all is well, apart from having to do it about 6 times.

starting from a clean setup helped.

**Comment by yannzak** [comment]
Same problem and fixed that by replacing the following command :

> cd ~\.node-red

By the real node red path on Raspbian :

> cd /home/pi/.node-red

**Comment by Butterfly** [comment]
@yannzak For Raspbian, does `cd ~/.node-red` work (instead of `cd ~.node-red`)? :smile:
