### ISSUE TITLE
npm ERR! errno -66

### ISSUE THREAD

**Issue by monajalal** [npm/npm#11889]
So what's the fix in OSX Yosemite?

```
bash-3.2$ sudo chmod ugo+wrx /Users/mona/interviews/mean/mean/node_modules/node-pre-gyp
bash-3.2$ npm install
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN mongodb-core@1.2.31 requires a peer of kerberos@~0.0 but none was installed.
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.8.0
npm ERR! npm  v3.8.2
npm ERR! path /Users/mona/interviews/mean/mean/node_modules/node-pre-gyp
npm ERR! code ENOTEMPTY
npm ERR! errno -66
npm ERR! syscall rename

npm ERR! ENOTEMPTY: directory not empty, rename '/Users/mona/interviews/mean/mean/node_modules/node-pre-gyp' -> '/Users/mona/interviews/mean/mean/node_modules/.node-pre-gyp.DELETE'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mona/interviews/mean/mean/npm-debug.log
```

**Comment by zkat** [comment]
This is totally a bug, most likely because some sort of interruption happened while deleting or doing similar operations on a package.

You can work around this by just doing `rm /Users/mona/interviews/mean/mean/node_modules/.node-pre-gyp.DELETE`, or just `rm -rf node_modules/` for now, but we'll try to get the underlying issue fixed soon. Thanks for the report~ :tada:

**Comment by kellyjandrews** [comment]
@zkat do you know if this was fixed recently or is it still outstanding?

**Comment by zkat** [comment]
@kellyjandrews if you're still seeing it, you should just rm for now. This might get fixed along with other changes we happen to be doing, but I have neither a guarantee nor a timeline for you on that.
