### ISSUE TITLE
Unable to install appium

### ISSUE THREAD

**Issue by nchariti** [npm/npm#11885]
Hi I am trying to install appium via npm. I didn't get to have any issue with other packages so far. This is what I am getting every time:

![npm appium issue](https://cloud.githubusercontent.com/assets/17817814/13732487/956fc2bc-e98c-11e5-8164-d04592da9f15.png)

Perhaps I am doing something incorrectly, but I cannot figure out what so far.

**Comment by zkat** [comment]
Do you have the Java JDK and JRE installed in your system, and available in your `PATH`?

**Comment by nchariti** [comment]
Yes, I have also tried installing the latest version. Here is what I see when I run java and appium-doctor: 

![java version](https://cloud.githubusercontent.com/assets/17817814/14079395/0eaba4b4-f506-11e5-89de-71774d2cadc1.png)

Is there anything else I need to check?

Note: I am able to install an older version of appium (1.4.16)

**Comment by zkat** [comment]
This doesn't really seem like an npm CLI issue to me. You'll need to file an issue with appium. I'm closing this for now, but if you find something specific to the CLI, please ping again and let me know!
