### ISSUE TITLE
npm command not responding

### ISSUE THREAD

**Issue by adoura** [npm/npm#11892]
Hello, 
my problem is npm not respoding , for example if i type node -v it gives me : v5.8.0
but when type npm -v , command propmt not responding with anything. 

this also the same for all other commands for npm.
i checked folder C:\Users\user\AppData\Roaming\npm but it is empty
and there is npm folder in C:\Program Files\nodejs\node_modules\npm

i don't know why it is not working so any help will be appreciated.

**Comment by uharbachou** [comment]
hm, yesterday try to install 4.x and 5.x. All work fine. What kind of OS you use?

**Comment by adoura** [comment]
OS is windows 7

**Comment by uharbachou** [comment]
try to reinstall and reboot pc

**Comment by adoura** [comment]
i did 3 times

**Comment by adoura** [comment]
any path variables or folders to check ?

**Comment by othiym23** [comment]
- Are you using 64-bit or 32-bit builds of Windows or Node?
- What happens if you run `node -p "console.log(require('util').inspect(process.versions))"`?
- What happens if you run `npm -ddd install`?

**Comment by TinkuShanmu** [comment]
I am also facing the same issue, PFB the response, but still npm commands are not working, mine is 64bit windows 10 OS 

G:\>node -p "console.log(require('util').inspect(process.versions))"
{ http_parser: '2.7.0',
  node: '5.11.0',
  v8: '4.6.85.31',
  uv: '1.8.0',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '56.1',
  modules: '47',
  openssl: '1.0.2g' }
undefined

**Comment by prmohanty08** [comment]
I experienced this when I modified **npmrc** to set custom ***prefix*** and ***cache***. Then I updated the node and restarted the machine, but still facing the same issue.
I tried `node -p "console.log(require('util').inspect(process.versions))"` as suggested by @othiym23 got the below output.
```javascript
{ http_parser: '2.7.0',
  node: '6.2.2',
  v8: '5.0.71.52',
  uv: '1.9.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '57.1',
  modules: '48',
  openssl: '1.0.2h' }
undefined
```
But `npm -ddd install` didn't work.

**Comment by prmohanty08** [comment]
After looking into the processing of ```npm.cmd``` I found that, while executing
```
FOR /F "delims=" %%F IN ('CALL "%NODE_EXE%" "%NPM_CLI_JS%" prefix -g') DO (
  SET "NPM_PREFIX_NPM_CLI_JS=%%F\node_modules\npm\bin\npm-cli.js"
)
```
the process becomes unresponsive. There must be some problem. But I could not understand why this loop is there in the batch file. After commenting these three lines in the ***npm.cmd*** file everything is working fine.

**Comment by prmohanty08** [comment]
Tried to check with all possible versions of **node** by reinstalling the same, but no luck. Can anyone please suggest any alternative of **_npm_** ?

**Comment by prmohanty08** [comment]
In the home directory, there was an entry of __.npmrc__, and this was probably creating a conflict with the default configuration of the __npm__ inside __node__. By removing __.npmrc__ from user home did the trick.
Note: For _windows_ this file will be inside _user_ folder.
@kmanion Thanks for your help.

**Comment by kmanion** [comment]
@prmohanty08 you're welcome. :)

**Comment by thamizhchelvan** [comment]
@prmohanty08 Thanks, it works..

**Comment by igimuhendis** [comment]
Thanks it worked.

**Comment by legodude17** [comment]
Does anyone still have this issue?

**Comment by thisjs** [comment]
@prmohanty08 "removing .npmrc from user home" which directory is home directory, I can't find this

**Comment by Charlotteis** [comment]
@thisjs 
You can find the location of your personal `.npmrc` using the following command

```
npm config get userconfig
```

On a mac, mine looks like: `/Users/charlotteis/.npmrc`

On Windows it may look like: `C:\Users\charlotteis\.npmrc`

(Replacing `charlotteis` with your username)

**Comment by Andy-wangke** [comment]
@prmohanty08 Thanks,save my days.It works.

**Comment by legodude17** [comment]
Anyone else still have this?

**Comment by anovinger** [comment]
I am having this issue.  I am running on RHEL 6, and I cannot find the .nrpmc file in any users home folder, or on the system at all.

I have tried commenting out the 3 lines mention above no luck.

Outputs from the commands
./node -v
v6.10.1
./node -p "console.log(require('util').inspect(process.versions))"
{ http_parser: '2.7.0',
  node: '6.10.1',
  v8: '5.1.281.95',
  uv: '1.9.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '58.2',
  modules: '48',
  openssl: '1.0.2k' }
undefined

**Comment by nish1998** [comment]
thanks to all, worked for me
