### ISSUE TITLE
Cannot install ethashjs

### ISSUE THREAD

**Issue by bokkypoobah** [npm/npm#11895]
I'm trying to install the module ethashjs, but it gives a package.json file not found error. Are there any workarounds or does this module have to be re-packaged? Thanks.

beef@localhost:~/EtherPool-master$ npm install ethashjs
npm WARN package.json ethpool@1.0.0 No repository field.
npm http GET https://registry.npmjs.org/ethashjs/0.0.3
npm http 304 https://registry.npmjs.org/ethashjs/0.0.3
npm http GET https://registry.npmjs.org/bitwise-xor/0.0.0
npm http GET https://registry.npmjs.org/es6-shim
npm http GET https://registry.npmjs.org/miller-rabin
npm http GET https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/es6-shim
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/miller-rabin
npm http 304 https://registry.npmjs.org/bitwise-xor/0.0.0
npm ERR! Error: ENOENT, open '/home/beef/tmp/npm-16930-OoobM1Tr/1457964856105-0.9844409516081214/package/package.json'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.4.0-x86_64-linode63
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "ethashjs"
npm ERR! cwd /home/beef/EtherPool-master
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /home/beef/tmp/npm-16930-OoobM1Tr/1457964856105-0.9844409516081214/package/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/beef/EtherPool-master/npm-debug.log
npm ERR! not ok code 0

**Comment by KenanY** [comment]
Hello @bokkypoobah! `npm@1.3` is no longer supported. Please try [upgrading](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm).

**Comment by bokkypoobah** [comment]
Thanks. I'll try upgrading.

**Comment by bokkypoobah** [comment]
Upgraded - same problem.

beef@localhost:~/EtherPool-master$ npm install ethashjs
npm WARN package.json ethpool@1.0.0 No repository field.
npm ERR! addLocal Could not install /tmp/npm-3823-964ec265/git-cache-71465fb23428/b4efe58da3333549670ffbfad1f1821cd282e937
npm ERR! Linux 4.4.0-x86_64-linode63
npm ERR! argv "node" "/usr/local/bin/npm" "install" "ethashjs"
npm ERR! node v0.10.25
npm ERR! npm  v2.14.22
npm ERR! code EISDIR
npm ERR! errno 28

npm ERR! eisdir EISDIR, read
npm ERR! eisdir This is most likely not a problem with npm itself
npm ERR! eisdir and is related to npm not being able to find a package.json in
npm ERR! eisdir a package you are trying to install.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/beef/EtherPool-master/npm-debug.log

Uploaded debug log.

[npm-debug.log.txt](https://github.com/npm/npm/files/172179/npm-debug.log.txt)

**Comment by bokkypoobah** [comment]
I could not get it working using npm, so I manually installed the modules myself. I've got it all working now. Thanks for your time.
