### ISSUE TITLE
After I type npm init, fill it out, and then type npm start, I receive the following error.

### ISSUE THREAD

**Issue by TheC0mposer** [npm/npm#11896]
```
host-173-230-97-54:FrontendPortfolio imclockedout$ npm start
npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.4.0
npm ERR! npm  v2.14.20

npm ERR! missing script: start
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/imclockedout/Code/FrontendPortfolio/npm-debug.log
```

**I am fairly new to node and npm, so I'm sure I may of just missed a step somewhere or something, any help is deeply appreciated, I also have a screen hero if anyone is interested in solving this mystery**
**I am running OS X Elcap 10.11.2 **
**My node version is v4.4.0**
**My npm version is 2.14.20**

**Comment by albertosouza** [comment]
I think you need to add one command for **start** in **scripts** configuration in your **package.json** file

See one example here: https://github.com/madhums/node-express-mongoose-demo/blob/master/package.json#L22
Or other example here: https://github.com/wejs-examples/we-project-groups/blob/master/package.json#L11

**Comment by TheC0mposer** [comment]
@albertosouza hmm, is that normal for everyone to have to add them manually after your install node, and npm from there website? I'll give it a go and let you know what happens!

**Comment by TheC0mposer** [comment]
In my project directory I used the "sudo nano package.json" command, and alls that was under the script property was  

"scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },

so I added this

 "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node app.js"
  },

I typed ctrl + o, then ctrl + x
I closed terminal, reopened it and tried starting it again with "npm start" and received this

host-173-230-97-54:FrontendPortfolio imclockedout$ npm start

> portfoliojson@1.0.0 start /Users/imclockedout/Code/FrontendPortfolio
> node app.js

module.js:327
    throw err;
    ^

Error: Cannot find module '/Users/imclockedout/Code/FrontendPortfolio/app.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.4.0
npm ERR! npm  v2.14.20
npm ERR! code ELIFECYCLE
npm ERR! portfoliojson@1.0.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the portfoliojson@1.0.0 start script 'node app.js'.
npm ERR! This is most likely a problem with the portfoliojson package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs portfoliojson
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls portfoliojson
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/imclockedout/Code/FrontendPortfolio/npm-debug.log

**Comment by albertosouza** [comment]
How are the main script of your app? app.js? server.js?

How you run your app (project) localy?

**Comment by TheC0mposer** [comment]
@albertosouza Here is a link to a gist I just created containing my app.js script, read the note I placed at the top of the gist, if you don't mind.  https://gist.github.com/TheC0mposer/2acaa96f7ac0210889c0

And my goal is to find out how to run my angular project locally, I am coming from being a backend PhP/Laravel dev and I used vagrant and homestead to view my project, do I need MAMP or something in order for npm start to work?

**Comment by albertosouza** [comment]
@TheC0mposer This is one angular.js app, it dont run in node.js.

For node.js you need one node.js app ... take a look in Express.js Getting Started tutorial: http://expressjs.com/en/starter/installing.html

And for serve the current folder you need something like express-static or http-server: http://stackoverflow.com/questions/16333790/node-js-quick-file-server-static-files-over-http

**Comment by TheC0mposer** [comment]
yes yes! "http-server", I thought I needed npm start to work for http-server to work, when I type the 
"http-server" command from my project directory I get this error 

host-173-230-97-54:FrontendPortfolio imclockedout$ http-server
bash: http-server: command not found
host-173-230-97-54:FrontendPortfolio imclockedout$ 

dose "http-server" pull up my project in a localhost? Or do I need MAMP or XAMP to make a localhost?
