### ISSUE TITLE
`npm version` will update package.json, but not stage/commit it properly in git

### ISSUE THREAD

**Issue by DannyDelott** [npm/npm#11898]
My `package.json` lives in the top-level directory of my project (`npm-deploy-scripts/`). 

When I run `npm version patch` in the `projects/` subdirectory, npm is able to find and increment the version entry in `package.json`, but fails to stage the `package.json` in git.

Screenshot:

![screen shot 2016-03-14 at 4 10 52 pm](https://cloud.githubusercontent.com/assets/4524175/13762904/5f42f22c-e9ff-11e5-9cae-08945818d123.png)

**Comment by KrekkieD** [comment]
I have the same thing, npm version 3.7.2.

**Comment by zkat** [comment]
Hi! Please update to the latest `npm@3` -- this was fixed as of https://github.com/npm/npm/pull/10627, which was included in `npm@3.5.3`. Closing as a duplicate, and thanks for filing the issue :+1:
