### ISSUE TITLE
Express framework installation error

### ISSUE THREAD

**Issue by Luckybanda** [npm/npm#11893]
While installing express in windows using 'npm install express' I am getting error 443. Please help me to resolve this issue....

**Comment by amandeepmittal** [comment]
Try 
`npm cache clean`
then try running the command to install express again.

**Comment by Luckybanda** [comment]
![capture](https://cloud.githubusercontent.com/assets/17828802/13769634/41e8b678-eaa7-11e5-8e1c-6514a09b56ac.PNG)

Tried as you said but still facing the same issue.
I have attached the screenshot of command prompt giving error.

**Comment by amandeepmittal** [comment]
@Luckybanda Is there a proxy setting on your network?
Also, which `npm` version are you using?

**Comment by zkat** [comment]
Like @amandeepmittal said, this is almost certainly a proxy or other network issue, please check your npm proxy configuration and try again.

**Comment by Luckybanda** [comment]
Thanks @amandeepmittal and @zkat

**Comment by zkat** [comment]
Cool -- I'm closing this for now. Cheers!

**Comment by amandeepmittal** [comment]
You're welcome @Luckybanda
