### ISSUE TITLE
npm ERR! of Query "npm install mocha --save-dev"

### ISSUE THREAD

**Issue by gkreddy88** [npm/npm#11908]
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "mocha" "--save-dev"
npm ERR!    ** D:\IBM Bluemix\kasiFizzBuzz\npm-debug.log**

Thanks
Kasireddy

**Comment by KenanY** [comment]
Hello @gkreddy88! Please upload the `npm-debug.log` file as a [gist](https://gist.github.com/) and link it here.

**Comment by johsnguyen** [comment]
hangs
