### ISSUE TITLE
Ability to exclude certain files from downloading

### ISSUE THREAD

**Issue by ZakariaRidouh** [npm/npm#11915]
Hey Guys! I would like to ask about the ability to exclude certain things in the modules that are being installed. For example, if I add Bootstrap, jQuery, and Font Awesome to my package.json, it will install everything in those repositories. I don't need all of that (junk) stuff that comes with it, all I need is the main minified version, so why not have the ability to only allow that certain file from installing.

Thanks!

**Comment by zkat** [comment]
There’s two parts to this: for one, it’s the package maintainer’s responsibility to determine what files should be included in their distributed packages. This is what tools like the [`files` array in `package.json`](https://docs.npmjs.com/files/package.json#files) and [`.npmignore`](https://docs.npmjs.com/cli/publish#description) are meant for. Furthermore, in the specific case of minified files like this, and similar “front-end” resources, it might be better to just use a CDN or similar service, depending on what you’re doing.

Implementing selective download on the CLI side is kind of complicated and not a generally useful feature, so this isn’t something the team is likely to add. As such, I’m going to close this feature request. For another approach to solving this issue, you might want to take a look at http://npm.im/copy-browser-modules. Thanks for your time!
