### ISSUE TITLE
Mac Instalation Problem ( missing script: start)

### ISSUE THREAD

**Issue by syedfarrukhqamar** [npm/npm#11917]
i have just installed ionic on my mac and then tried to create first project by
 npm start myApp tabs

then i have seen the following problem on the termianl window

 npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start" "myApp" "tabs"
npm ERR! node v4.4.0
npm ERR! npm  v2.14.20

npm ERR! missing script: start
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/myName/myapp/npm-debug.log
bmc:myApp farrukhqamar$ npm start myApp tabs
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start" "myApp" "tabs"
npm ERR! node v4.4.0
npm ERR! npm  v2.14.20

npm ERR! missing script: start
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/farrukhqamar/myapp/npm-debug.log
bmc:myApp myName$ npm start myApp blank
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start" "myApp" "blank"
npm ERR! node v4.4.0
npm ERR! npm  v2.14.20

npm ERR! missing script: start
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/myName/myapp/npm-debug.log

is there any suggestion how to resolve it 

thanks a lot

**Comment by KenanY** [comment]
Hello @syedfarrukhqamar!

> then tried to create first project by `npm start myApp tabs`

This is not what `npm start` does... please read [the documentation](https://docs.npmjs.com/cli/start).

**Comment by KenanY** [comment]
@syedfarrukhqamar Are you still having any issues?
