### ISSUE TITLE
npm preinstall not really run at the start of install

### ISSUE THREAD

**Issue by jchbh-duplicate** [npm/npm#11914]
I use symlink to rename some packages with fix/pr to the name of original packages. and found the npm cannot install when package.json change when there are some symlink inside node_modules.
so I try to add an command in preinstall script, to remove symlink before doing install, hope that the install can correct do to the correct node_modules directory, but it seems no use. 
npm looks first do some checks before run preinstall, and the not check after the preinstall script.

**Comment by palmerj3** [comment]
This is already a bug since November and still not fixed. https://github.com/npm/npm/issues/10379
