### ISSUE TITLE
NPM loops forever when starting new ember project

### ISSUE THREAD

**Issue by CodeStrider35** [npm/npm#11913]
![capture](https://cloud.githubusercontent.com/assets/12943278/13800319/636637a6-eae5-11e5-8530-ad0607db96e9.PNG)

ember new projectname -seems to work fine until "installing packages for tooling via NPM" then it loops forever, just keeps on saying the same thing over and over again. Node.js is up-to-date and NPM is on its current version. 3.8.2

**Comment by KenanY** [comment]
@CodeStrider35 Is this still an issue for you?

**Comment by KenanY** [comment]
Closing as abandoned.
