### ISSUE TITLE
error code SELF_SIGNED_CERT_IN_CHAIN

### ISSUE THREAD

**Issue by onessimofalconi** [npm/npm#11919]
65 verbose stack Error: self signed certificate in certificate chain
65 verbose stack     at Error (native)
65 verbose stack     at TLSSocket.<anonymous> (_tls_wrap.js:1016:38)
65 verbose stack     at emitNone (events.js:67:13)
65 verbose stack     at TLSSocket.emit (events.js:166:7)
65 verbose stack     at TLSSocket._finishInit (_tls_wrap.js:585:8)
66 verbose cwd c:\workspace\simet_frontend\simet
67 error Windows_NT 6.0.6002
69 error node v4.2.4
70 error npm  v2.14.12
71 error code SELF_SIGNED_CERT_IN_CHAIN
72 error self signed certificate in certificate chain
73 error If you need help, you may report this error at:
73 error     https://github.com/npm/npm/issues
74 verbose exit [ 1, true ]

**Comment by zkat** [comment]
Hey! This is usually caused by a misconfigured proxy with a self-signed cert somewhere along the way. Could you check with your network admin that certificates along the way are all valid, and that your proxy configuration is right?
