### ISSUE TITLE
Strong loop Got expecting https error during installed with npm in node cmd

### ISSUE THREAD

**Issue by Balukompalli** [npm/npm#11928]
I installed Node js and it is working fine. Npm is also working fine. Node js path variable is also set fine. 
But when i tried to install strongloop with npm it generates error and struck the screen there. 

error is "Protocol https is not supported. Expected  http: "

 please resolve my error and give the step to solve this error. I attacched my error as a screen shot. Please consider and give good solution.

thank you.

!![screenshot 674](https://cloud.githubusercontent.com/assets/14317499/13824709/35c34f1e-ebd5-11e5-85a1-1f6f838c9e3a.png)

**Comment by zkat** [comment]
@Balukompalli could you upload an `npm-debug.log` to let us have more detail about it? It should be in the directory where you ran `npm install`
