### ISSUE TITLE
Express installation error

### ISSUE THREAD

**Issue by shilpi2905** [npm/npm#11925]
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ECONNRESET

npm ERR! network tunneling socket could not be established, cause=getaddrinfo EN
OTFOUND proxy.company.com
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

**Comment by johsnguyen** [comment]
0

**Comment by amandeepmittal** [comment]
@shilpi2905 
The problem is with your proxy server. Please check your npm proxy configuration.
Also update your npm version.
