### ISSUE TITLE
require('module') should be able to load global packages

### ISSUE THREAD

**Issue by calidion** [npm/npm#11924]
npm install should ignore packages globally installed.

if grunt@2.2.0 is globally installed,

npm install will have a way to avoid package grunt@2.2.0  being installed into local node_modules folder.

**Comment by calidion** [comment]
global packages are flat,
local packages are nested.
when packages are annotated as flat/global, it will be installed globally

versions should always be cared.

**Comment by KenanY** [comment]
@calidion The title of your issue does not match the body text.

> require('module') should be able to load global packages

Isn't this what `NODE_PATH` is for? https://nodejs.org/api/modules.html#modules_loading_from_the_global_folders

> npm install should ignore packages globally installed.

:-1:, the well-accepted standard is to keep dependencies which are local to your project local rather than global.

**Comment by othiym23** [comment]
There's nothing for the CLI team to act on her that will fit the design of the npm CLI within the scope of the current Node.js module resolution algorithm, so I'm going to close this issue. Thanks for your time, though!
