### ISSUE TITLE
File group, owner gets changed to root:root after every npm install 

### ISSUE THREAD

**Issue by lekhnath** [npm/npm#11923]
OS Ubuntu 13.10, Node.js v4.4.0(LTS) , npm v2.14.20

Every time I run `sudo npm install <packagename> -S` my package.json file's group, owner becomes root:root.I've attached screenshot too as a proof :) .

Screen shot shows 

`ls -la` (this time package.json has lekhnath:lekhnath group and owner)
`npm install bootstrap-sass -S`
`ls -la` (this time package.json has root:root group and owner)
**Why??**

![npm-install-changes-group-owner](https://cloud.githubusercontent.com/assets/4231691/13817953/4138c8f6-ebbc-11e5-9d0d-018c02cf00ad.png)

**Comment by albertosouza** [comment]
@lekhnath this is related to your linux, if you run any command with 'sudo' by default your system will create all files with root user.

To test this creating one empty file do:
```sh
sudo touch file_as_root.txt
ls -la file_as_root.txt
# -rw-r--r--. 1 root root 0 Mar 16 19:21 file_as_root.txt
touch file_as_current_user.txt
ls -la file_as_current_user.txt 
#-rw-rw-r--. 1 a a 0 Mar 16 19:21 file_as_current_user.txt
```

**Comment by lekhnath** [comment]
@albertosouza you were correct. But once I change file ownership to `user:user` and then `touch` that file again with `sudo` the file `owner` remains the same - `user:user`. Whereas `package.json` file's ownership gets change even after `chowning` it to `user:user` before doing `sudo npm install`.

If this problem is not related to `npm` itself, and the result was obvious can you suggest me how to not change file ownership to root after each sudo. I am tired of reverting group, owner back to user each time I do `sudo npm install`. I tried googling but no luck.

Thankyou.

**Comment by iarna** [comment]
@lekhnath The answer here is that you shouldn't be using `sudo` here. Just run `npm install` and it will do what you want.

`sudo` can be appropriate sometimes when installing global tools, but for installing libraries in your project it should never be used.

I'm going to close this issue, but if you have more questions please feel free to open a new issue or reach out to our support team at support@npmjs.com
