### ISSUE TITLE
node_modules\mocha\lib\utils.js:628  throw new Error("cannot resolve path (or pattern) '" + path + "'")

### ISSUE THREAD

**Issue by gkreddy88** [npm/npm#11920]
Hi PFB..
i'm trying test REST API.
What to set for "Path" ?

D:\IBM Bluemix Dev\kasiFizzBuzz>node_modules\.bin\mocha -w
D:\IBM Bluemix Dev\kasiFizzBuzz\node_modules\mocha\lib\utils.js:628
        throw new Error("cannot resolve path (or pattern) '" + path + "'");
        ^

Error: cannot resolve path (or pattern) '-w'
    at Object.lookupFiles (D:\IBM Bluemix Dev\kasiFizzBuzz\node_modules\mocha\li
b\utils.js:628:15)
    at D:\IBM Bluemix Dev\kasiFizzBuzz\node_modules\mocha\bin\_mocha:326:30
    at Array.forEach (native)
    at Object.<anonymous> (D:\IBM Bluemix Dev\kasiFizzBuzz\node_modules\mocha\bi
n\_mocha:325:6)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

D:\IBM Bluemix Dev\kasiFizzBuzz> -w
'-w' is not recognized as an internal or external command,
operable program or batch file.

Thanks in advance
Kasi

**Comment by KenanY** [comment]
Hello @gkreddy88! Could you expand on how this is an issue with `npm`?

**Comment by gkreddy88** [comment]
Hello Kenan,

Thanks for quick reply,

Actually i try to test the REST API which is created based on a *Exercise
5c: Test-driven development .*

3. Configure Mocha to continually run tests: a. In the Terminals view, run
the following command: o Mac and Linux: node_modules/.bin/mocha -w   o
Windows: node_modules\.bin\mocha –w
You will see that the tests are failing because of an error: Error: Cannot
find module '../fizzbuzz.js'
b. In the root of the project, create the file fizzbuzz.js.
c. Add the following code to configure the fizzbuzz.js file:
var FizzBuzz = function (){ };
module.exports = FizzBuzz;

i saved above fizzbuzz.js and try to test it. there i'm getting the npm
error.

Thanks
Kasi



Thanks & Regards
Kasireddy Golamaru

**Comment by mobiletestforce** [comment]
Hi

I am also facing the same problem. could you please let me know how did you resolved this issue?

Thanks,
Ranga

**Comment by KenanY** [comment]
I'm gonna close this as not an issue with `npm`. You can prove otherwise with a `npm-debug.log` file, for the most part, but none was ever provided.
