### ISSUE TITLE
"Cannot read property 'emit' of null" from npm install

### ISSUE THREAD

**Issue by Melvintehu** [npm/npm#11929]
Everytime I run npm install on windows I get this error message. 
- I tried reinstalling nodejs.
- deleted node_modules folder before using npm install again.

Anyone has a solution for this problem?

**npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v5.8.0
npm ERR! npm  v3.7.3

npm ERR! Cannot read property 'emit' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v5.8.0
npm ERR! npm  v3.7.3

npm ERR! Cannot read property 'emit' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues**

**Comment by amandeepmittal** [comment]
@Melvintehu 
uninstall both npm and node.js and try downloading node.js verison 4.4.0 LTS, that might solve it.

**Comment by zkat** [comment]
@Melvintehu could you upload your `npm-debug.log` somewhere? This looks like a potential bug. I'm gonna mark it as such for now.

**Comment by huqiliang** [comment]
I also have this problem 

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "yog2" "-g"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1

npm ERR! Cannot read property 'emit' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
