### ISSUE TITLE
Ionic Installation using Node

### ISSUE THREAD

**Issue by PremkumarAgrawal** [npm/npm#11934]
npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\premkumar.agrawal\npm-debug.log

**Comment by PremkumarAgrawal** [comment]
Hey I solved the Issue

Download Node.js, git and Apache ant

->Install Node.js, Git
->Set Path variables for
	Nodejs\bin
	Git\bin
	apache ant\bin
	AndroidSDK\platform tools
	AndroidSDK\tools
-> install updated npm
	>npm install npm@latest
-> install cordova
	>npm install -g cordova
->install ionic
	>npm install -g ionic 

-----------------------------------------------------------------------------------------------------------------------
C:\Users\premkumar.agrawal>npm install -g ionic
C:\Users\premkumar.agrawal\AppData\Roaming\npm\ionic -> C:\Users\premkumar.agraw
al\AppData\Roaming\npm\node_modules\ionic\bin\ionic

> node-sass@3.4.2 install C:\Users\premkumar.agrawal\AppData\Roaming\npm\node_mo
dules\ionic\node_modules\node-sass
> node scripts/install.js

Binary downloaded and installed at C:\Users\premkumar.agrawal\AppData\Roaming\np
m\node_modules\ionic\node_modules\node-sass\vendor\win32-ia32-47\binding.node

> spawn-sync@1.0.15 postinstall C:\Users\premkumar.agrawal\AppData\Roaming\npm\n
ode_modules\ionic\node_modules\spawn-sync
> node postinstall


> node-sass@3.4.2 postinstall C:\Users\premkumar.agrawal\AppData\Roaming\npm\nod
e_modules\ionic\node_modules\node-sass
> node scripts/build.js

` C:\Users\premkumar.agrawal\AppData\Roaming\npm\node_modules\ionic\node_modules
\node-sass\vendor\win32-ia32-47\binding.node ` exists.
 testing binary.
Binary is fine; exiting.
C:\Users\premkumar.agrawal\AppData\Roaming\npm
`-- ionic@1.7.14
  +-- cli-table@0.3.1
  | `-- colors@1.0.3
  +-- connect@3.1.1
  | `-- utils-merge@1.0.0
  +-- expand-tilde@1.2.0
  | `-- user-home@1.1.1
  +-- gulp@3.8.8
  | +-- gulp-util@3.0.7
  | | +-- dateformat@1.0.12
  | | +-- fancy-log@1.1.0
  | | +-- through2@2.0.0
  | | | `-- readable-stream@2.0.5
  | | |   `-- util-deprecate@1.0.2
  | | `-- vinyl@0.5.3
  | +-- liftoff@0.12.1
  | | `-- findup-sync@0.1.3
  | |   `-- lodash@2.4.2
  | `-- orchestrator@0.3.7
  |   `-- end-of-stream@0.1.5
  |     `-- once@1.3.3
  |       `-- wrappy@1.0.1
  +-- ionic-app-lib@0.7.0
  | +-- archiver@0.5.2
  | | +-- lazystream@0.1.0
  | | | `-- readable-stream@1.0.33
  | | +-- lodash@2.4.2
  | | +-- readable-stream@1.0.33
  | | `-- zip-stream@0.1.4
  | |   `-- readable-stream@1.0.33
  | +-- cross-spawn@2.0.0
  | | +-- cross-spawn-async@2.1.8
  | | | +-- lru-cache@4.0.0
  | | | | `-- yallist@2.0.0
  | | | `-- which@1.2.4
  | | `-- spawn-sync@1.0.15
  | |   `-- concat-stream@1.5.1
  | |     `-- readable-stream@2.0.5
  | +-- ionic-cordova-lib@5.1.10
  | | +-- cordova-js@4.0.0
  | | | +-- browserify@10.1.3
  | | | | +-- assert@1.3.0
  | | | | +-- browser-pack@4.0.4
  | | | | | `-- through2@0.5.1
  | | | | |   `-- readable-stream@1.0.33
  | | | | +-- deps-sort@1.3.9
  | | | | | `-- through2@1.1.1
  | | | | +-- glob@4.5.3
  | | | | +-- insert-module-globals@6.6.3
  | | | | | `-- through2@1.1.1
  | | | | +-- labeled-stream-splicer@1.0.2
  | | | | | `-- stream-splicer@1.3.2
  | | | | |   `-- through2@1.1.1
  | | | | +-- module-deps@3.9.1
  | | | | | +-- stream-combiner2@1.0.2
  | | | | | | `-- through2@0.5.1
  | | | | | |   `-- readable-stream@1.0.33
  | | | | | `-- through2@1.1.1
  | | | | +-- through2@1.1.1
  | | | | +-- url@0.10.3
  | | | | | `-- punycode@1.3.2
  | | | | +-- util@0.10.3
  | | | | `-- vm-browserify@0.0.4
  | | | `-- uglify-js@2.6.1
  | | |   `-- async@0.2.10
  | | +-- glob@4.0.6
  | | | `-- graceful-fs@3.0.8
  | | +-- init-package-json@1.9.3
  | | | +-- glob@6.0.4
  | | | +-- read-package-json@2.0.3
  | | | | `-- glob@6.0.4
  | | | +-- validate-npm-package-license@3.0.1
  | | | `-- validate-npm-package-name@2.2.2
  | | +-- npm@2.14.17
  | | | +-- cmd-shim@2.0.1
  | | | | `-- graceful-fs@3.0.8
  | | | +-- glob@5.0.15
  | | | +-- inflight@1.0.4
  | | | +-- node-gyp@3.2.1
  | | | | `-- glob@4.5.3
  | | | +-- normalize-package-data@2.3.5
  | | | +-- npm-registry-client@7.0.9
  | | | | `-- concat-stream@1.5.1
  | | | |   `-- readable-stream@2.0.4
  | | | |     `-- util-deprecate@1.0.2
  | | | +-- once@1.3.3
  | | | +-- request@2.67.0
  | | | | +-- bl@1.0.0
  | | | | | `-- readable-stream@2.0.4
  | | | | |   `-- util-deprecate@1.0.2
  | | | | +-- har-validator@2.0.3
  | | | | | `-- is-my-json-valid@2.12.3
  | | | | |   `-- xtend@4.0.1
  | | | | `-- http-signature@1.1.0
  | | | |   `-- jsprim@1.2.2
  | | | |     `-- verror@1.3.6
  | | | +-- validate-npm-package-license@3.0.1
  | | | +-- validate-npm-package-name@2.2.2
  | | | `-- wrappy@1.0.1
  | | +-- npmconf@2.1.2
  | | +-- plist@1.1.0
  | | | `-- xmldom@0.1.22
  | | +-- through2@0.6.3
  | | | `-- readable-stream@1.0.33
  | | `-- valid-identifier@0.0.1
  | +-- node-sass@3.4.2
  | | +-- cross-spawn@2.1.5
  | | +-- glob@5.0.15
  | | | `-- inflight@1.0.4
  | | +-- meow@3.7.0
  | | | +-- normalize-package-data@2.3.5
  | | | `-- read-pkg-up@1.0.1
  | | |   `-- read-pkg@1.1.0
  | | +-- node-gyp@3.2.1
  | | +-- request@2.69.0
  | | | +-- bl@1.0.1
  | | | | `-- readable-stream@2.0.5
  | | | +-- har-validator@2.0.6
  | | | | `-- is-my-json-valid@2.12.4
  | | | `-- http-signature@1.1.1
  | | |   `-- jsprim@1.2.2
  | | |     `-- verror@1.3.6
  | | `-- sass-graph@2.1.0
  | |   +-- glob@6.0.4
  | |   `-- yargs@3.10.0
  | |     +-- camelcase@1.2.1
  | |     +-- cliui@2.1.0
  | |     `-- window-size@0.1.0
  | +-- opbeat-ionic@1.1.3
  | | +-- after-all@2.0.2
  | | `-- stackman@0.2.3
  | +-- unzip2@0.2.5
  | | +-- fstream@0.1.31
  | | | `-- graceful-fs@3.0.8
  | | `-- readable-stream@1.0.33
  | +-- vinyl-fs@1.0.0
  | | +-- duplexify@3.4.2
  | | | +-- end-of-stream@1.0.0
  | | | `-- readable-stream@2.0.5
  | | +-- glob-stream@4.1.1
  | | | +-- glob@4.5.3
  | | | `-- unique-stream@2.2.0
  | | |   `-- through2-filter@2.0.0
  | | +-- graceful-fs@3.0.8
  | | +-- merge-stream@0.1.8
  | | | `-- through2@0.6.5
  | | |   `-- readable-stream@1.0.33
  | | +-- strip-bom@1.0.0
  | | +-- through2@0.6.5
  | | | `-- readable-stream@1.0.33
  | | `-- vinyl@0.4.6
  | |   `-- clone@0.2.0
  | `-- winston@1.1.2
  |   +-- async@1.0.0
  |   `-- colors@1.0.3
  +-- npm@2.1.3
  | +-- npm-registry-client@3.2.2
  | | `-- npmlog@2.0.3
  | |   `-- are-we-there-yet@1.1.2
  | |     `-- readable-stream@2.0.6
  | `-- wrappy@1.0.1
  +-- optimist@0.6.0
  | `-- wordwrap@0.0.2
  +-- prompt@0.2.12
  | `-- utile@0.2.1
  |   `-- async@0.2.10
  +-- request@2.51.0
  | `-- bl@0.9.5
  |   `-- readable-stream@1.0.33
  +-- serve-static@1.7.1
  +-- unzip@0.1.9
  | +-- fstream@0.1.31
  | | `-- graceful-fs@3.0.8
  | +-- match-stream@0.0.2
  | | `-- readable-stream@1.0.33
  | +-- pullstream@0.4.1
  | | +-- readable-stream@1.0.33
  | | `-- slice-stream@1.0.0
  | |   `-- readable-stream@1.0.33
  | `-- readable-stream@1.0.33
  +-- vinyl-fs@0.3.7
  | +-- glob-stream@3.1.18
  | | +-- glob@4.5.3
  | | `-- through2@0.6.5
  | |   `-- readable-stream@1.0.33
  | +-- graceful-fs@3.0.8
  | +-- lodash@2.4.2
  | +-- strip-bom@1.0.0
  | +-- through2@0.6.5
  | | +-- readable-stream@1.0.33
  | | `-- xtend@4.0.1
  | `-- vinyl@0.4.6
  |   `-- clone@0.2.0
  `-- xml2js@0.4.4
    +-- sax@0.6.1
    `-- xmlbuilder@2.2.1


C:\Users\premkumar.agrawal>ionic -v
1.7.14

**Comment by tk120404** [comment]
@ashleygwilliams Please close this issue

**Comment by othiym23** [comment]
Closing as resolved. Thanks for the assist, @tk120404!
