### ISSUE TITLE
shasum check failed for /tmp/npm-3136-64657b4d/registry.npmjs.org/node-inspector/-/node-inspector-0.12.7.tgz

### ISSUE THREAD

**Issue by narayand4** [npm/npm#11933]
Hi,

When i'm trying to execute "npm install" command showing this error in my terminal.
shasum check failed for /tmp/npm-3136-64657b4d/registry.npmjs.org/node-inspector/-/node-inspector-0.12.7.tgz
npm ERR! Expected: 99289f6a15826c01d7cd15d8f54b2fc9cef2d3c5
npm ERR! Actual:   978825e84e3d9563e85264568540f5e246124d93
npm ERR! From:     https://registry.npmjs.org/node-inspector/-/node-inspector-0.12.7.tgz I have attached npm-debug.log
please help me what i'm doing wrong. 

[npm-debug.txt](https://github.com/npm/npm/files/177193/npm-debug.txt)

Thanks.

**Comment by KenanY** [comment]
@narayand4 Are you still seeing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
