### ISSUE TITLE
npm fails to install package due to an error - ETIMEDOUT 185.31.19.162:443

### ISSUE THREAD

**Issue by h4ck3r8ug5** [npm/npm#11939]
Hi all.

I'm not sure if this is the correct place to post this so apologies if it isn't

While doing a build on our frontend app, my build fails intermittently due to this error:
npm ERR! network connect ETIMEDOUT 185.31.19.162:443

I can ping the IP address so sometimes it's down and sometimes it's alive so I'm not sure if this address might be behind a firewall and that could be tossing out the multiple requests? I'm just taking a guess here.
Thinking it might be the internet at the client I'm based at, I have tried to run npm install from home and the same error happens.

Does anyone else have issues connecting to the above address?

Kind regards,

**Comment by zkat** [comment]
If you're not behind a firewall, then it's most likely an issue with your internet service provider. npm has a cache that should help reduce the load on connections, but there's unfortunately not much we can do if your computer can't go out and fetch stuff. :\
