### ISSUE TITLE
npm install command hang 

### ISSUE THREAD

**Issue by tongcat** [npm/npm#11937]
I typed this `npm install`, it's run but stuck on 
`make: Leaving directory `/home/openproject/openproject-ce/frontend/node_modules/protractor/node_modules/selenium-webdriver/node_modules/ws/node_modules/bufferutil/build' `

I tried and run again `npm install`
`rm -fR ~/.npm
npm cache clean`

The result as below

`npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/home/openproject/.nodenv/versions/0.12.7/bin/node" "/home/openproject/.nodenv/versions/0.12.7/bin/npm" "install" 
npm ERR! node v0.12.7
npm ERR! npm v2.11.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! openproject-frontend@0.1.0 postinstall: `bower install --config.interactive=false`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the openproject-frontend@0.1.0 postinstall script 'bower install --config.interactive=false'.
npm ERR! This is most likely a problem with the openproject-frontend package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! bower install --config.interactive=false
npm ERR! You can get their info via:
npm ERR! npm owner ls openproject-frontend
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR! /home/openproject/openproject-ce/frontend/npm-debug.log

npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/home/openproject/.nodenv/versions/0.12.7/bin/node" "/home/openproject/.nodenv/versions/0.12.7/bin/npm" "install" 
npm ERR! node v0.12.7
npm ERR! npm v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! openproject@0.1.0 postinstall: `cd frontend && npm install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the openproject@0.1.0 postinstall script 'cd frontend && npm install'.
npm ERR! This is most likely a problem with the openproject package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! cd frontend && npm install
npm ERR! You can get their info via:
npm ERR! npm owner ls openproject
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR! /home/openproject/openproject-ce/npm-debug.log`

I have no idea on what problem is it. Any help?

**Comment by tongcat** [comment]
```
npm ERR! Linux 3.19.0-25-generic npm ERR! argv "/home/openproject/.nodenv/versions/0.12.7/bin/node" "/home/openproject/.nodenv/versions/0.12.7/bin/npm" "install" npm ERR! node v0.12.7 npm ERR! npm v2.11.3 npm ERR! file sh npm ERR! code ELIFECYCLE npm ERR! errno ENOENT npm ERR! syscall spawn npm ERR! openproject-frontend@0.1.0 postinstall:bower install --config.interactive=false`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the openproject-frontend@0.1.0 postinstall script 'bower install --config.interactive=false'.
npm ERR! This is most likely a problem with the openproject-frontend package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! bower install --config.interactive=false
npm ERR! You can get their info via:
npm ERR! npm owner ls openproject-frontend
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR! /home/openproject/openproject-ce/frontend/npm-debug.log

npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/home/openproject/.nodenv/versions/0.12.7/bin/node" "/home/openproject/.nodenv/versions/0.12.7/bin/npm" "install" 
npm ERR! node v0.12.7
npm ERR! npm v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! openproject@0.1.0 postinstall: cd frontend && npm install
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the openproject@0.1.0 postinstall script 'cd frontend && npm install'.
npm ERR! This is most likely a problem with the openproject package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! cd frontend && npm install
npm ERR! You can get their info via:
npm ERR! npm owner ls openproject
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR! /home/openproject/openproject-ce/npm-debug.log`
```

**Comment by pedzed** [comment]
Run `npm install -g bower` and try again.

**Comment by zkat** [comment]
Like @pedzed said -- it looks like `openproject-frontend` has a dependency on `bower` for its `postinstall` script. You'll need to either add `bower` as a dependency of `openproject-frontend` (which will put it in your path), or just work around it by installing `bower` globally, as @pedzed said.
