### ISSUE TITLE
error on install ing the npm

### ISSUE THREAD

**Issue by kavishjoshi** [npm/npm#11935]
npm ERR! node v5.9.0
npm ERR! npm  v3.7.3

npm ERR! Unexpected token <
npm ERR! 
npm ERR! <?xml version="1.0" encoding="utf-8"?>
npm ERR! <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
npm ERR!  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
npm ERR! <html>
npm ERR!   <head>
npm ERR!     <title>503 backend read error</title>
npm ERR!   </head>
npm ERR!   <body>
npm ERR!     <h1>Error 503 backend read error</h1>
npm ERR!     <p>backend read error</p>
npm ERR!     <h3>Guru Mediation:</h3>
npm ERR!     <p>Details: cache-sin6927-SIN 1458198409 1823933740</p>
npm ERR!     <hr>
npm ERR!     <p>Varnish cache server</p>
npm ERR!   </body>
npm ERR! </html>
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /home/kavish/npm-debug.log

**Comment by amandeepmittal** [comment]
Looks like this a problem caused by a proxy server. You need to set proxy that npm can use. Please refer to this link: [https://stackoverflow.com/questions/18569054/npm-behind-ntlm-proxy]( https://stackoverflow.com/questions/18569054/npm-behind-ntlm-proxy)
