### ISSUE TITLE
 error Error: No compatible version found: run-sequence@'^1.0.2'

### ISSUE THREAD

**Issue by kamal2222ahmed** [npm/npm#11948]
i was running gradle clean jar and this also has npm targets. Here is the error log

462 verbose etag "5CS8D0MSYSH09VUAY1DFBF9XR"
463 http GET https://registry.npmjs.org/jasmine-jquery
464 verbose url raw bower
465 verbose url resolving [ 'https://registry.npmjs.org/', './bower' ]
466 verbose url resolved https://registry.npmjs.org/bower
467 info trying registry request attempt 1 at 15:26:12
468 verbose etag "1AKVYVYK36FUNTO2W7B3IWWFY"
469 http GET https://registry.npmjs.org/bower
470 http 304 https://registry.npmjs.org/run-sequence
471 silly registry.get cb [ 304,
471 silly registry.get   { date: 'Thu, 17 Mar 2016 19:26:13 GMT',
471 silly registry.get     via: '1.1 varnish',
471 silly registry.get     'cache-control': 'max-age=300',
471 silly registry.get     etag: '"78ICF7GCZQW027OE5E2H6RNQL"',
471 silly registry.get     age: '147',
471 silly registry.get     connection: 'keep-alive',
471 silly registry.get     'x-served-by': 'cache-jfk1040-JFK',
471 silly registry.get     'x-cache': 'HIT',
471 silly registry.get     'x-cache-hits': '1',
471 silly registry.get     'x-timer': 'S1458242773.080765,VS0,VE0',
471 silly registry.get     vary: 'Accept' } ]
472 verbose etag run-sequence from cache
473 silly lockFile 95fa9867-run-sequence-1-0-2 run-sequence@^1.0.2
474 silly lockFile 95fa9867-run-sequence-1-0-2 run-sequence@^1.0.2
475 error Error: No compatible version found: run-sequence@'^1.0.2'
475 error Valid install targets:
475 error ["0.3.1","0.3.2","0.3.3","0.3.4","0.3.5","0.3.6","0.3.7","1.0.0","1.0.1","1.0.2","1.1.0","1.1.1","1.1.2","1.1.3","1.1.4","1.1.5"]
475 error     at installTargetsError (/opt/nodejs/node-v0.10.15-linux-x64/lib/node_modules/npm/lib/cache.js:719:10)
475 error     at /opt/nodejs/node-v0.10.15-linux-x64/lib/node_modules/npm/lib/cache.js:638:10
475 error     at saved (/opt/nodejs/node-v0.10.15-linux-x64/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:142:7)
475 error     at /opt/nodejs/node-v0.10.15-linux-x64/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:133:7
475 error     at Object.oncomplete (fs.js:107:15)
476 error If you need help, you may report this log at:
476 error     <http://github.com/isaacs/npm/issues>
476 error or email it to:
476 error     <npm-@googlegroups.com>
477 error System Linux 2.6.32-573.1.1.el6.x86_64
478 error command "/opt/nodejs/node-v0.10.15-linux-x64/bin/node" "/opt/nodejs/node-v0.10.15-linux-x64/bin/npm" "install" "angular-mocks" "bower" "del" "gulp" "gulp-angular-templatecache" "gulp-bundle-assets" "gulp-html-replace" "gulp-if" "gulp-js-wrapper" "gulp-jsbeautifier" "gulp-jscs" "gulp-jshint" "gulp-jshint-html-reporter" "gulp-less" "gulp-ng-annotate" "gulp-notify" "gulp-watch" "lazypipe" "less" "lodash" "merge" "normalize-path" "plato" "protractor" "run-sequence" "to-single-quotes" "jquery@1.11.0" "jasmine-core" "jasmine-jquery" "--save-dev"

480 error node -v v0.10.15

**Comment by KenanY** [comment]
Hello @kamal2222ahmed! Please upload the entire log as a [gist](https://gist.github.com/) and link it here instead of cutting off hundreds of lines next time. Regardless, I am almost certain that you must have an old version of `npm`. Please try [updating](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm).

**Comment by KenanY** [comment]
@kamal2222ahmed Hi! Just following up here since it has been over a month... are you still seeing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
