### ISSUE TITLE
npm ERR! code 1 on running  npm list -g grep grunt in node v4.2.6

### ISSUE THREAD

**Issue by sudanvellakovilkanakavel** [npm/npm#11957]
Hi I am trying to install react framework by installing webpack,webpack-dev-server,  etc

on running 

CJBTDLDD0003:~ kanaks$ npm list -g  grunt
/Users/kanaks/.npm-global/lib
└── (empty)

npm ERR! code 1
CJBTDLDD0003:~ kanaks$ npm list -g  grep grunt
/Users/kanaks/.npm-global/lib
└── (empty)

npm ERR! code 1

I get the above error. 

I am using 
CJBTDLDD0003:~ kanaks$ node -v
v4.2.6
CJBTDLDD0003:~ kanaks$ npm -v
3.8.0

CJBTDLDD0003:desktop kanaks$ npm start

> kanaks@1.0.0 start /Users/kanaks/Desktop
> webpack-dev-server --hot

sh: webpack-dev-server: command not found

npm ERR! Darwin 14.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.8.0
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! kanaks@1.0.0 start: `webpack-dev-server --hot`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the kanaks@1.0.0 start script 'webpack-dev-server --hot'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the kanaks package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --hot
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs kanaks
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls kanaks
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kanaks/Desktop/npm-debug.log

CJBTDLDD0003:desktop kanaks$ npm list -g --depth=0
/Users/kanaks/.npm-global/lib
├── babel@6.5.2
├── compression@1.6.1
├── connect-history-api-fallback@1.1.0
├── express@4.13.4
├── graceful@1.0.0
├── gulp@3.9.1
├── http-proxy@1.13.2
├── jade@1.11.0
├── jade-bootstrap@1.0.2
├── nodemon@1.9.1
├── optimist@0.6.1
├── pm2@1.0.2
├── react@0.14.7
├── react-dom@0.14.7
├── serve-index@1.7.3
├── sockjs@0.3.15
├── sockjs-client@1.0.3
├── strip-ansi@3.0.1
├── supports-color@3.1.2
├── webpack@1.12.14
├── webpack-dev-middleware@1.5.1
└── webpack-dev-server@1.14.1

**Comment by KenanY** [comment]
```
CJBTDLDD0003:~ kanaks$ npm list -g grunt
/Users/kanaks/.npm-global/lib
└── (empty)
```

From your list of global modules...

```
...
├── express@4.13.4
├── graceful@1.0.0
├── gulp@3.9.1
├── http-proxy@1.13.2
...
```

you don't have `grunt` installed, so `npm` is behaving as expected here.

I'm not sure about about the `webpack-dev-server` error.

**Comment by sudanvellakovilkanakavel** [comment]
Hi KenanY

Thank you very much for your speed replay,I am new to bode,npm ,react stuff....
thank you very much.
