### ISSUE TITLE
Error: failed to fetch from registry: grunt-sass-lint

### ISSUE THREAD

**Issue by emanzx** [npm/npm#11954]
npm ERR! Error: failed to fetch from registry: grunt-sass-lint
npm ERR!     at /usr/local/lib/node_modules/npm/lib/utils/npm-registry-client/get.js:139:12
npm ERR!     at cb (/usr/local/lib/node_modules/npm/lib/utils/npm-registry-client/request.js:32:9)
npm ERR!     at Request._callback (/usr/local/lib/node_modules/npm/lib/utils/npm-registry-client/request.js:137:18)
npm ERR!     at Request.callback (/usr/local/lib/node_modules/npm/node_modules/request/main.js:109:22)
npm ERR!     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/main.js:198:58)
npm ERR!     at Request.emit (events.js:88:20)
npm ERR!     at ClientRequest.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/main.js:356:14)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at HTTPParser.onIncoming (http.js:1254:11)
npm ERR!     at HTTPParser.onHeadersComplete (http.js:102:31)
npm ERR! You may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
npm ERR!
npm ERR! System FreeBSD 10.3-RC1
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /usr/home/system/go/src/github.com/grafana/grafana
npm ERR! node -v v0.6.9
npm ERR! npm -v 1.1.0-3
npm ERR! message failed to fetch from registry: grunt-sass-lint
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /usr/home/system/go/src/github.com/grafana/grafana/npm-debug.log
npm not ok

**Comment by KenanY** [comment]
@emanzx Outdated Node.js and `npm`. Please update both.

**Comment by emanzx** [comment]
Thanks. I have update it.. It works now..

**Comment by zkat** [comment]
Looks like this got resolved! Thanks, @KenanY!
