### ISSUE TITLE
Error while cloning Uptime from GIT

### ISSUE THREAD

**Issue by vinayakelex** [npm/npm#11955]
Hi,

I am trying to clone uptime from git reporsitory but it will give me error "Unable to access". Can you please help to get uptime up on my system. below is the detail error message.

$ git clone https://github.com/fzaninotto/uptime.git
Cloning into 'uptime'...
fatal: unable to access 'https://github.com/fzaninotto/uptime.git/': error:14077419:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert access denied

$ git clone git://github.com/fzaninotto/uptime.git
Cloning into 'uptime'...
fatal: unable to connect to github.com:
github.com[0: 192.30.252.130]: errno=Invalid argument

**Comment by KenanY** [comment]
Hello @vinayakelex! I don't think this is relevant to `npm` at all.

**Comment by zkat** [comment]
This is purely a `git` issue, and has nothing at all to do with npm.

That said: It looks like you might be behind a corporate firewall. It might be beneficial to look into setting up a proxy or asking your admin to open ports.

But as this has nothing to do with npm, I'm closing it. Good luck! :)
