### ISSUE TITLE
Error: EFAULT, mkdir '/tmp/npm-29644-Dv4vnh0b/registry.npmjs.org/express/-'

### ISSUE THREAD

**Issue by ashish0304** [npm/npm#11953]
Debian jessie android arm proot(GnuRoot Debian)

dNameRange     '2.5.1',
29 silly addNameRange     '2.5.2',
29 silly addNameRange     '2.5.3',
29 silly addNameRange     '2.5.4',
29 silly addNameRange     '2.5.5',
29 silly addNameRange     '2.5.6',
29 silly addNameRange     '2.5.7',
29 silly addNameRange     '2.5.8',
29 silly addNameRange     '2.5.9',
29 silly addNameRange     '2.5.10',
29 silly addNameRange     '2.5.11',
29 silly addNameRange     '3.0.0',
29 silly addNameRange     '3.0.1',
29 silly addNameRange     '3.0.2',
29 silly addNameRange     '3.0.3',
29 silly addNameRange     '3.0.4',
29 silly addNameRange     '3.0.5',
29 silly addNameRange     '3.0.6',
29 silly addNameRange     '3.1.0',
29 silly addNameRange     '3.1.1',
29 silly addNameRange     '3.1.2',
29 silly addNameRange     '3.2.0',
29 silly addNameRange     '3.2.1',
29 silly addNameRange     '3.2.2',
29 silly addNameRange     '3.2.3',
29 silly addNameRange     '3.2.4',
29 silly addNameRange     '3.2.5',
29 silly addNameRange     '3.2.6',
29 silly addNameRange     '3.3.0',
29 silly addNameRange     '3.3.1',
29 silly addNameRange     '3.3.2',
29 silly addNameRange     '3.3.3',
29 silly addNameRange     '3.3.4',
29 silly addNameRange     '3.3.5',
29 silly addNameRange     '3.3.6',
29 silly addNameRange     '1.0.0-beta',
29 silly addNameRange     '1.0.0-beta2',
29 silly addNameRange     '1.0.0-rc',
29 silly addNameRange     '1.0.0-rc2',
29 silly addNameRange     '1.0.0-rc3',
29 silly addNameRange     '1.0.0-rc4',
29 silly addNameRange     '2.0.0-beta',
29 silly addNameRange     '2.0.0-beta2',
29 silly addNameRange     '2.0.0-beta3',
29 silly addNameRange     '2.0.0-rc',
29 silly addNameRange     '2.0.0-rc2',
29 silly addNameRange     '2.0.0-rc3',
29 silly addNameRange     '3.0.0-alpha1',
29 silly addNameRange     '3.0.0-alpha2',
29 silly addNameRange     '3.0.0-alpha3',
29 silly addNameRange     '3.0.0-alpha4',
29 silly addNameRange     '3.0.0-alpha5',
29 silly addNameRange     '3.0.0-beta1',
29 silly addNameRange     '3.0.0-beta2',
29 silly addNameRange     '3.0.0-beta3',
29 silly addNameRange     '3.0.0-beta4',
29 silly addNameRange     '3.0.0-beta6',
29 silly addNameRange     '3.0.0-beta7',
29 silly addNameRange     '3.0.0-rc1',
29 silly addNameRange     '3.0.0-rc2',
29 silly addNameRange     '3.0.0-rc3',
29 silly addNameRange     '3.0.0-rc4',
29 silly addNameRange     '3.0.0-rc5',
29 silly addNameRange     '3.3.7',
29 silly addNameRange     '3.3.8',
29 silly addNameRange     '3.4.0',
29 silly addNameRange     '3.4.1',
29 silly addNameRange     '3.4.2',
29 silly addNameRange     '3.4.3',
29 silly addNameRange     '3.4.4',
29 silly addNameRange     '3.4.5',
29 silly addNameRange     '3.4.6',
29 silly addNameRange     '3.4.7',
29 silly addNameRange     '3.4.8',
29 silly addNameRange     '4.0.0-rc1',
29 silly addNameRange     '4.0.0-rc2',
29 silly addNameRange     '3.5.0',
29 silly addNameRange     '4.0.0-rc3',
29 silly addNameRange     '4.0.0-rc4',
29 silly addNameRange     '3.5.1',
29 silly addNameRange     '4.0.0',
29 silly addNameRange     '3.5.2',
29 silly addNameRange     '4.1.0',
29 silly addNameRange     '4.1.1',
29 silly addNameRange     '3.5.3',
29 silly addNameRange     '4.1.2',
29 silly addNameRange     '3.6.0',
29 silly addNameRange     '4.2.0',
29 silly addNameRange     '3.7.0',
29 silly addNameRange     '3.8.0',
29 silly addNameRange     '4.3.0',
29 silly addNameRange     '4.3.1',
29 silly addNameRange     '3.8.1',
29 silly addNameRange     '4.3.2',
29 silly addNameRange     '3.9.0',
29 silly addNameRange     '4.4.0',
29 silly addNameRange     '4.4.1',
29 silly addNameRange     '3.10.0',
29 silly addNameRange     '3.10.1',
29 silly addNameRange     '3.10.2',
29 silly addNameRange     '3.10.3',
29 silly addNameRange     '3.10.4',
29 silly addNameRange     '4.4.2',
29 silly addNameRange     '3.10.5',
29 silly addNameRange     '4.4.3',
29 silly addNameRange     '3.11.0',
29 silly addNameRange     '4.4.4',
29 silly addNameRange     '3.12.0',
29 silly addNameRange     '3.12.1',
29 silly addNameRange     '4.4.5',
29 silly addNameRange     '3.13.0',
29 silly addNameRange     '4.5.0',
29 silly addNameRange     '4.5.1',
29 silly addNameRange     '3.14.0',
29 silly addNameRange     '4.6.0',
29 silly addNameRange     '4.6.1',
29 silly addNameRange     '3.15.0',
29 silly addNameRange     '4.7.0',
29 silly addNameRange     '3.15.1',
29 silly addNameRange     '4.7.1',
29 silly addNameRange     '3.15.2',
29 silly addNameRange     '4.7.2',
29 silly addNameRange     '4.7.3',
29 silly addNameRange     '3.15.3',
29 silly addNameRange     '4.7.4',
29 silly addNameRange     '3.16.0',
29 silly addNameRange     '4.8.0',
29 silly addNameRange     '3.16.1',
29 silly addNameRange     '4.8.1',
29 silly addNameRange     '3.16.2',
29 silly addNameRange     '4.8.2',
29 silly addNameRange     '3.16.3',
29 silly addNameRange     '3.16.4',
29 silly addNameRange     '4.8.3',
29 silly addNameRange     '3.16.5',
29 silly addNameRange     '3.16.6',
29 silly addNameRange     '4.8.4',
29 silly addNameRange     '3.16.7',
29 silly addNameRange     '4.8.5',
29 silly addNameRange     '3.16.8',
29 silly addNameRange     '4.8.6',
29 silly addNameRange     '3.16.9',
29 silly addNameRange     '4.8.7',
29 silly addNameRange     '3.16.10',
29 silly addNameRange     '4.8.8',
29 silly addNameRange     '3.17.0',
29 silly addNameRange     '3.17.1',
29 silly addNameRange     '4.9.0',
29 silly addNameRange     '3.17.2',
29 silly addNameRange     '4.9.1',
29 silly addNameRange     '4.9.2',
29 silly addNameRange     '3.17.3',
29 silly addNameRange     '4.9.3',
29 silly addNameRange     '3.17.4',
29 silly addNameRange     '4.9.4',
29 silly addNameRange     '3.17.5',
29 silly addNameRange     '4.9.5',
29 silly addNameRange     '3.17.6',
29 silly addNameRange     '3.17.7',
29 silly addNameRange     '4.9.6',
29 silly addNameRange     '4.9.7',
29 silly addNameRange     '3.17.8',
29 silly addNameRange     '4.9.8',
29 silly addNameRange     '3.18.0',
29 silly addNameRange     '3.18.1',
29 silly addNameRange     '4.10.0',
29 silly addNameRange     '3.18.2',
29 silly addNameRange     '4.10.1',
29 silly addNameRange     '5.0.0-alpha.1',
29 silly addNameRange     '3.18.3',
29 silly addNameRange     '4.10.2',
29 silly addNameRange     '3.18.4',
29 silly addNameRange     '4.10.3',
29 silly addNameRange     '4.10.4',
29 silly addNameRange     '4.10.5',
29 silly addNameRange     '3.18.5',
29 silly addNameRange     '3.18.6',
29 silly addNameRange     '4.10.6',
29 silly addNameRange     '4.10.7',
29 silly addNameRange     '3.19.0',
29 silly addNameRange     '4.10.8',
29 silly addNameRange     '4.11.0',
29 silly addNameRange     '3.19.1',
29 silly addNameRange     '4.11.1',
29 silly addNameRange     '3.19.2',
29 silly addNameRange     '4.11.2',
29 silly addNameRange     '3.20.0',
29 silly addNameRange     '4.12.0',
29 silly addNameRange     '3.20.1',
29 silly addNameRange     '4.12.1',
29 silly addNameRange     '4.12.2',
29 silly addNameRange     '3.20.2',
29 silly addNameRange     '4.12.3',
29 silly addNameRange     '3.20.3',
29 silly addNameRange     '4.12.4',
29 silly addNameRange     '3.21.0',
29 silly addNameRange     '4.13.0',
29 silly addNameRange     '3.21.1',
29 silly addNameRange     '4.13.1',
29 silly addNameRange     '5.0.0-alpha.2',
29 silly addNameRange     '3.21.2',
29 silly addNameRange     '4.13.2',
29 silly addNameRange     '4.13.3',
29 silly addNameRange     '4.13.4' ] ]
30 verbose addNamed [ 'express', '4.13.4' ]
31 verbose addNamed [ '4.13.4', '4.13.4' ]
32 silly lockFile 23607823-express-4-13-4 express@4.13.4
33 verbose lock express@4.13.4 /home/.npm/23607823-express-4-13-4.lock
34 silly lockFile 65e0249d-s-org-express-express-4-13-4-tgz https://registry.npmjs.org/express/-/express-4.13.4.tgz
35 verbose lock https://registry.npmjs.org/express/-/express-4.13.4.tgz /home/.npm/65e0249d-s-org-express-express-4-13-4-tgz.lock
36 verbose addRemoteTarball [ 'https://registry.npmjs.org/express/-/express-4.13.4.tgz',
36 verbose addRemoteTarball   '3c0b76f3c77590c8345739061ec0bd3ba067ec24' ]
37 silly lockFile 65e0249d-s-org-express-express-4-13-4-tgz https://registry.npmjs.org/express/-/express-4.13.4.tgz
38 silly lockFile 65e0249d-s-org-express-express-4-13-4-tgz https://registry.npmjs.org/express/-/express-4.13.4.tgz
39 silly lockFile 23607823-express-4-13-4 express@4.13.4
40 silly lockFile 23607823-express-4-13-4 express@4.13.4
41 silly lockFile 64a534c1-express express@
42 silly lockFile 64a534c1-express express@
43 error Error: EFAULT, mkdir '/tmp/npm-29644-Dv4vnh0b/registry.npmjs.org/express/-'
44 error If you need help, you may report this *entire* log,
44 error including the npm and node versions, at:
44 error     <http://github.com/npm/npm/issues>
45 error System Linux 3.10.49-gf9e7acc
46 error command "/usr/bin/nodejs" "/usr/bin/npm" "install" "express"
47 error cwd /home
48 error node -v v0.10.29
49 error npm -v 1.4.21
50 error path /tmp/npm-29644-Dv4vnh0b/registry.npmjs.org/express/-
51 error code EFAULT
52 error errno 15
53 verbose exit [ 15, true ]

**Comment by zkat** [comment]
`EFAULT` is a pretty low-level program failure, and it's very unlikely to come from npm specifically -- I notice you have a pretty old version of nose and npm. Would is be possible to update it, and try again?
