### ISSUE TITLE
NPM does not save git url as it is in package.json

### ISSUE THREAD

**Issue by tamilvendhank** [npm/npm#11959]
`npm install git+ssh://git@domain:username/project.git --save` updates `package.json` with out `git+` in dependencies section.

```
"dependencies": {
    "project": "ssh://git@domain:username/project.git"
}
```

So, I have to manually edit the package.json after the install.

**Comment by KenanY** [comment]
@tamilvendhank `npm --version`? Looks like a duplicate of https://github.com/npm/npm/issues/9679.

**Comment by tamilvendhank** [comment]
@KenanY 

$ npm --version
3.3.12

**Comment by tamilvendhank** [comment]
@KenanY, This is the duplicate of https://github.com/npm/npm/issues/9679. Closing this now.
