### ISSUE TITLE
bower install angular-local-storage --save

### ISSUE THREAD

**Issue by opegm** [npm/npm#11961]
Hi, 
Please I need help here, I can't run these commands "bower install angular-local-storage --save" or "npm install angular-local-storage" each time I run. I get this error message.
![image](https://cloud.githubusercontent.com/assets/13622716/13882348/5c2b6c9e-ed25-11e5-9c3e-9276b6702604.png)

**Comment by KenanY** [comment]
@opegm I don't see an error in the `npm` part. Just a few warnings which can be ignored for the most part.

**Comment by opegm** [comment]
Thanks for the quick response. However I cannot find the angular-local-storage file in the directory. app.js folder after download.

**Comment by KenanY** [comment]
@opegm `npm ls angular-local-storage`?

**Comment by opegm** [comment]
when I proceeded I found this when I tried simulating with phone gap.
![image](https://cloud.githubusercontent.com/assets/13622716/13883767/4bd3fe78-ed2b-11e5-8a77-1d9cccdd819c.png)

**Comment by KenanY** [comment]
@opegm Maybe try `npm cache clean`.

**Comment by opegm** [comment]
Ok thanks. I will try and get back to you

**Comment by KenanY** [comment]
@opegm ping :)

**Comment by othiym23** [comment]
Closing as abandoned. Open a new issue if you encounter this behavior again!
