### ISSUE TITLE
sudo npm install -g cordova - I am getting this error while installing cordova

### ISSUE THREAD

**Issue by AkshayMehta78** [npm/npm#11963]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'ionic' ]
2 info using npm@2.14.3
3 info using node@v4.1.0
4 verbose install initial load of /Users/akshaymehta/akshay/npm-global/lib/package.json
5 verbose readDependencies loading dependencies from /Users/akshaymehta/akshay/npm-global/lib/package.json
6 silly cache add args [ 'ionic', null ]
7 verbose cache add spec ionic
8 silly cache add parsed spec Result {
8 silly cache add   raw: 'ionic',
8 silly cache add   scope: null,
8 silly cache add   name: 'ionic',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 silly addNamed ionic@*
10 verbose addNamed "*" is a valid semver range for ionic
11 silly addNameRange { name: 'ionic', range: '*', hasData: false }
12 silly mapToRegistry name ionic
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/ionic
16 verbose addNameRange registry:https://registry.npmjs.org/ionic not in flight; fetching
17 verbose request uri https://registry.npmjs.org/ionic
18 verbose request no auth needed
19 info attempt registry request try #1 at 10:35:54 PM
20 verbose request id 45964d9241ea2463
21 http request GET https://registry.npmjs.org/ionic
22 info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=connect ETIMEDOUT 218.93.250.18:8080
23 info attempt registry request try #2 at 10:37:20 PM
24 http request GET https://registry.npmjs.org/ionic
25 info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=connect ETIMEDOUT 218.93.250.18:8080
26 info attempt registry request try #3 at 10:39:35 PM
27 http request GET https://registry.npmjs.org/ionic
28 verbose stack Error: tunneling socket could not be established, cause=connect ETIMEDOUT 218.93.250.18:8080
28 verbose stack     at ClientRequest.onError (/usr/local/lib/node_modules/npm/node_modules/request/node_modules/tunnel-agent/index.js:174:17)
28 verbose stack     at ClientRequest.g (events.js:260:16)
28 verbose stack     at emitOne (events.js:77:13)
28 verbose stack     at ClientRequest.emit (events.js:169:7)
28 verbose stack     at Socket.socketErrorListener (_http_client.js:259:9)
28 verbose stack     at emitOne (events.js:77:13)
28 verbose stack     at Socket.emit (events.js:169:7)
28 verbose stack     at emitErrorNT (net.js:1250:8)
28 verbose stack     at doNTCallback2 (node.js:429:9)
28 verbose stack     at process._tickCallback (node.js:343:17)
29 verbose cwd /Users/akshaymehta
30 error Darwin 14.4.0
31 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "ionic"
32 error node v4.1.0
33 error npm  v2.14.3
34 error code ECONNRESET
35 error network tunneling socket could not be established, cause=connect ETIMEDOUT 218.93.250.18:8080
35 error network This is most likely not a problem with npm itself
35 error network and is related to network connectivity.
35 error network In most cases you are behind a proxy or have bad network settings.
35 error network
35 error network If you are behind a proxy, please make sure that the
35 error network 'proxy' config is set properly.  See: 'npm help config'
36 verbose exit [ 1, true ]

**Comment by amandeepmittal** [comment]
@AkshayMehta78 
This is your npm debug file log. Can you please share what errors and warning it gives when you attempt to install cordova globally in the terminal?
