### ISSUE TITLE
having trouble working with npm for the first time please someone help me

### ISSUE THREAD

**Issue by samastshi** [npm/npm#11960]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose config Skipping project config: C:\Users\m.mossadek/.npmrc. (matches userconfig)
6 verbose stack Error: ENOENT, open 'C:\Users\m.mossadek\package.json'
6 verbose stack     at Error (native)
7 verbose cwd C:\Users\m.mossadek
8 error Windows_NT 6.1.7601
9 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
10 error node v0.12.0
11 error npm  v2.5.1
12 error path C:\Users\m.mossadek\package.json
13 error code ENOENT
14 error errno -4058
15 error enoent ENOENT, open 'C:\Users\m.mossadek\package.json'
15 error enoent This is most likely not a problem with npm itself
15 error enoent and is related to npm not being able to find a file.
16 verbose exit [ -4058, true ]

**Comment by KenanY** [comment]
Hello @samastshi! Does `C:\Users\m.mossadek\package.json` exist?

**Comment by samastshi** [comment]
Hi Kenan, Thanks for your prompt answer. No it does not exist

Le vendredi 18 mars 2016, Kenan Yildirim <notifications@github.com> a
écrit :

> Hello @samastshi <https://github.com/samastshi>! Does
> C:\Users\m.mossadek\package.json exist?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/npm/npm/issues/11960#issuecomment-198389901>
>


-- 
----
Mosaddeq Mohammed

**Comment by KenanY** [comment]
@samastshi What are you expecting to happen when you run `npm start` without a `package.json` in your current working directory?

**Comment by samastshi** [comment]
hhh I don't know franckly, I have cloned a repo on my drive, then in the terminal i run npm install, the package.json is there and still not working

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info prestart js-assessment@0.3.0
7 info start js-assessment@0.3.0
8 verbose unsafe-perm in lifecycle true
9 info js-assessment@0.3.0 Failed to exec start script
10 verbose stack Error: js-assessment@0.3.0 start: `node index.js`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
10 verbose stack     at EventEmitter.emit (events.js:110:17)
10 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:14:12)
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1008:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
11 verbose pkgid js-assessment@0.3.0
12 verbose cwd C:\Users\m.mossadek\js-assessment-master
13 error Windows_NT 6.1.7601
14 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
15 error node v0.12.0
16 error npm  v2.5.1
17 error code ELIFECYCLE
18 error js-assessment@0.3.0 start: `node index.js`
18 error Exit status 1
19 error Failed at the js-assessment@0.3.0 start script 'node index.js'.
19 error This is most likely a problem with the js-assessment package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     node index.js
19 error You can get their info via:
19 error     npm owner ls js-assessment
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@samastshi Looks like `node index.js` is producing an error. Not an `npm` issue.

**Comment by KenanY** [comment]
Closing as not an issue with `npm`.
