### ISSUE TITLE
npm install does not respect version ranges

### ISSUE THREAD

**Issue by andrenarchy** [npm/npm#11964]
When `npm install` is executed with the following content of `package.json`
```
{
  ...
  "dependencies": {
    "simple-oauth2": "^0.5.0"
  },
  "devDependencies": {
    "bluebird": "^3.0.5"
  }
}
```
then it does not respect `simple-oauth2`'s dependency on `bluebird ^2.10.1` but only installs `bluebird 3.3.4` in the top level of `node_modules` (and nothing under `node_modules/simple-oauth2/node_modules`).

**Comment by zkat** [comment]
This does seem like an installer bug. /cc @iarna

**Comment by iarna** [comment]
Repros for me w/ npm @3.8.0

**Comment by iarna** [comment]
Closing as duplicate of #11766
