### ISSUE TITLE
Couldn't install optional browser-sync

### ISSUE THREAD

**Issue by recervictory** [npm/npm#11965]
npm WARN optional dep failed, continuing fsevents@1.0.8

> bufferutil@1.2.1 install /home/victor/.npm-global/lib/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

make: Entering directory `/home/victor/.npm-global/lib/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  COPY Release/bufferutil.node
make: Leaving directory`/home/victor/.npm-global/lib/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil/build'

> utf-8-validate@1.2.1 install /home/victor/.npm-global/lib/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

make: Entering directory `/home/victor/.npm-global/lib/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  COPY Release/validation.node
make: Leaving directory`/home/victor/.npm-global/lib/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate/build'

> bufferutil@1.2.1 install /home/victor/.npm-global/lib/node_modules/browser-sync/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

make: Entering directory `/home/victor/.npm-global/lib/node_modules/browser-sync/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  COPY Release/bufferutil.node
make: Leaving directory`/home/victor/.npm-global/lib/node_modules/browser-sync/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil/build'

> utf-8-validate@1.2.1 install /home/victor/.npm-global/lib/node_modules/browser-sync/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

make: Entering directory `/home/victor/.npm-global/lib/node_modules/browser-sync/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  COPY Release/validation.node
make: Leaving directory`/home/victor/.npm-global/lib/node_modules/browser-sync/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate/build'
/home/victor/.npm-global/bin/browser-sync -> /home/victor/.npm-global/lib/node_modules/browser-sync/bin/browser-sync.js
browser-sync@2.11.1 /home/victor/.npm-global/lib/node_modules/browser-sync
├── ucfirst@1.0.0
├── async-each-series@0.1.1
├── longest@1.0.1
├── emitter-steward@1.0.0
├── easy-extender@2.3.2
├── dev-ip@1.0.1
├── immutable@3.7.6
├── ua-parser-js@0.7.10
├── query-string@2.4.2 (strict-uri-encode@1.1.0)
├── opn@3.0.3 (object-assign@4.0.1)
├── portscanner@1.0.0 (async@0.1.15)
├── browser-sync-client@2.4.1 (etag@1.7.0, fresh@0.3.0)
├── serve-static@1.10.2 (escape-html@1.0.3, parseurl@1.3.1, send@0.13.1)
├── connect@3.4.1 (utils-merge@1.0.0, parseurl@1.3.1, debug@2.2.0, finalhandler@0.4.1)
├── resp-modifier@5.0.2 (debug@2.2.0, minimatch@2.0.10)
├── meow@3.3.0 (object-assign@3.0.0, minimist@1.2.0, camelcase-keys@1.0.0, indent-string@1.2.2)
├── chokidar@1.4.1 (path-is-absolute@1.0.0, inherits@2.0.1, async-each@0.1.6, glob-parent@2.0.0, is-glob@2.0.1, anymatch@1.3.0, is-binary-path@1.0.1, readdirp@2.0.0)
├── eazy-logger@2.1.2 (opt-merger@1.1.1, tfunk@3.0.1)
├── foxy@11.1.4 (http-proxy@1.13.2, lodash.merge@3.3.2, resp-modifier@4.0.4)
├── serve-index@1.7.3 (escape-html@1.0.3, parseurl@1.3.1, batch@0.5.3, http-errors@1.3.1, mime-types@2.1.10, debug@2.2.0, accepts@1.2.13)
├── fs-extra@0.26.7 (path-is-absolute@1.0.0, klaw@1.1.3, jsonfile@2.2.3, graceful-fs@4.1.3, rimraf@2.5.2)
├── bs-recipes@1.1.0
├── micromatch@2.3.5 (filename-regex@2.0.0, is-glob@2.0.1, array-unique@0.2.1, is-extglob@1.0.0, normalize-path@2.0.1, lazy-cache@0.2.7, expand-brackets@0.1.4, extglob@0.3.2, arr-diff@2.0.0, kind-of@3.0.2, regex-cache@0.4.2, parse-glob@3.0.4, object.omit@2.0.0, braces@1.8.3)
├── lodash@3.10.1
├── localtunnel@1.8.1 (openurl@1.1.0, debug@2.2.0, yargs@3.29.0, request@2.65.0)
├── browser-sync-ui@0.5.18 (connect-history-api-fallback@1.1.0, stream-throttle@0.1.3, weinre@2.0.0-pre-I0Z7U9OV)
└── socket.io@1.3.7 (debug@2.1.0, has-binary-data@0.1.3, socket.io-parser@2.2.4, socket.io-adapter@0.3.1, engine.io@1.5.4, socket.io-client@1.3.7)

**Comment by kuanb** [comment]
Any solution to this I am getting caught up on `fsevents` `npm WARN optional dep failed, continuing fsevents@1.0.8` as well.

**Comment by zkat** [comment]
This is what an optionalDep failure looks like, and it should not have stopped your install. It looks like it completed properly?

**Comment by recervictory** [comment]
yes, It has installed correctly. But  I have to add the path of directory everytime open the terminal.

**Comment by zkat** [comment]
If you add `/home/victor/.npm-global/lib/node_modules/browser-sync/bin` to your `$PATH`, you should be able to use any binaries in your custom prefix without doing that every time. :)
