### ISSUE TITLE
npm ERR! xcrun: error: invalid active developer path

### ISSUE THREAD

**Issue by marcothesis** [npm/npm#11962]
Is the path still working?

---

[npm-debug.txt](https://github.com/npm/npm/files/179971/npm-debug.txt)

Command failed: git clone --template=/Users/MT/.npm/_git-remotes/_templates --mirror git://github.com/stephen/node-sonos.git /Users/MT/.npm/_git-remotes/git-github-com-stephen-node-sonos-git-stephen-1-0-0-6a58f9b2

npm ERR! xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

**Comment by zkat** [comment]
Hi! This is not an npm issue, but an issue with the OSX Command Line Tools. According to my googlin', it looks like simply configuring the correct path to your Xcode should fix the problem: `sudo xcode-select -switch /Developer/Applications/Xcode.app` or similar.
