### ISSUE TITLE
error fatal: unable to access 'https://github.com/gruntjs/node-http2.git/'

### ISSUE THREAD

**Issue by sukanya13** [npm/npm#11979]
Hi, I get the error while trying to execute the below command in the command prompt

npm install grunt-contrib-connect --save-dev

error fatal: unable to access 'https://github.com/gruntjs/node-http2.git/': Failed to connect to github.com port 443: Connection refused

Not sure what the problem is. Can i get some help on this

**Comment by MadhukarMallia** [comment]
@sukanya13 I thinks its because of your connectivity. Are you behind a proxy? Also, what version on  npm are you using?

**Comment by othiym23** [comment]
If you're deploying from behind a corporate firewall, you may need to configure Git to use a proxy. If you can't use HTTPS to access GitHub and must use ssh instead, look into the configuration for using [`.insteadOf =`](https://github.com/npm/npm/wiki/Troubleshooting#npm-only-uses-git-and-sshgit-urls-for-github-repos-breaking-proxies) configuration for Git. Closing as resolved.
