### ISSUE TITLE
I can't install any package

### ISSUE THREAD

**Issue by sharkoman** [npm/npm#11974]
NodeJs 5 with npm 3.7.3
i am trying to install any package with npm, the installation taking forever 
i uninstalled node js and installed nodejs 4 stable and the same result...
the installation stick in : **loadDep:vinyl-fs  -> network**
and it keeps spinning forever

**Comment by tk120404** [comment]
try npm install in a different folder and if it doesnt work, then please attach the full log from npm

**Comment by sharkoman** [comment]
Now it's working .. thank you :+1:

**Comment by tk120404** [comment]
@ashleygwilliams close this issue
