### ISSUE TITLE
Fixing npm permissions when following docs doesn't work

### ISSUE THREAD

**Issue by thedamon** [npm/npm#11977]
I followed the instructions at https://docs.npmjs.com/getting-started/fixing-npm-permissions to try and stop having to sudo to do installs. 

My `npm config get prefix` is  `/Users/l392044/.npm-packages`

I ran `sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}`

Then I tried the test `npm install -g jshint` and got 

```
npm WARN locking Error: EACCES: permission denied, open '/Users/l392044/.npm/_locks/jshint-aa957a274ecf99a5.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/l392044/.npm/_locks/jshint-aa957a274ecf99a5.lock failed { [Error: EACCES: permission denied, open '/Users/l392044/.npm/_locks/jshint-aa957a274ecf99a5.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   syscall: 'open',
npm WARN locking   path: '/Users/l392044/.npm/_locks/jshint-aa957a274ecf99a5.lock' }
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/Users/l392044/.npm-packages/bin/npm" "install" "-g" "jshint"
npm ERR! node v4.0.0
npm ERR! npm  v2.11.2

npm ERR! Attempt to unlock /Users/l392044/.npm-packages/lib/node_modules/jshint, which hasn't been locked
```

my `~/npm-debug.log` doesn't exist. which i guess is related to the permissions issue.

I tried following steps 2-4 and still had pretty much the same problem, with identical error message except updated path in `Attempt to unlock /Users/l392044/.npm-global/lib/node_modules/jshint, which hasn't been locked`.

Wondering what else to try :|

**Comment by tk120404** [comment]
Checkout the owner of the .npm home folder. If it is owned by root, change it to your username `sudo chown -R [username] .npm` and then run the npm install

**Comment by thedamon** [comment]
The only thing in my home directory (`cd ~`, `ll -a`) that isn't owned by my user is the `Temp` dir, which is root. Permissions is listed as `drwxr-xr-x` for all the npm/node related dirs in `~`.

`drwxr-xr-x  1470 l392044  staff    49K 16 Mar 15:09 .npm`

This is a work computer set up by a team that isn't really hip to npm etc so I dno if there's other stuff that may be foiling me/getting in the way related to that.

**Comment by zkat** [comment]
For the sake of this particular care, could you do `sudo chown -R $(whoami) ~/.npm`? Followed by `npm cache clean` to wipe your cache if possible. Something may have gone awry with some prior sudo-experimentation here.

**Comment by thedamon** [comment]
@zkat WOO! months of latent annoyance as i fail to deal with this have been solved. thank you! :)
