### ISSUE TITLE
npm installs fails

### ISSUE THREAD

**Issue by park6447** [npm/npm#11970]
When I type as "ubuntu@ip-172-31-13-9:~/spy007$ sudo npm install", I keep get the error message as the below:

Please help me

npm ERR! not a package /tmp/npm-383-45kwiDxP/github.com/keystonejs/keystone.git
npm ERR! Error: ENOENT, open '/tmp/npm-383-45kwiDxP/github.com/keystonejs/keystone.git-unpack/package.json'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.13.0-74-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/ubuntu/spy007
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! path /tmp/npm-383-45kwiDxP/github.com/keystonejs/keystone.git-unpack/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/ubuntu/spy007/npm-debug.log
npm ERR! not ok code 0

**Comment by KenanY** [comment]
Hello @park6447! Please try [updating `npm`](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm).

**Comment by KenanY** [comment]
@park6447 Are you still facing this issue after updating `npm`?

**Comment by othiym23** [comment]
Closing as abandoned. Open a new issue if you encounter this behavior again!
