### ISSUE TITLE
Error installing node.js

### ISSUE THREAD

**Issue by evcrimmi** [npm/npm#11975]
I'm trying to install particle node.js on terminal but keep getting an error. 
Any suggestions?

I have the most recent version of xcode. I get the following error:

Eriks-MacBook:~ erikvan$ npm install –g particle-cli
npm ERR! addLocal Could not install /Users/erikvan/–g
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "–g" "particle-cli"
npm ERR! node v4.4.0
npm ERR! npm  v2.14.20

npm ERR! The header content contains invalid characters
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/erikvan/npm-debug.log

**Comment by tk120404** [comment]
This link could help in fixing this https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by zkat** [comment]
@evcrimmi heya: `–` is not a command-line flag character. It's quite likely you copy-pasted this command from somewhere. Use `-` instead (which is usually the one available on keyboards). They look similar but they're very much different characters :)

I'm certain enough that this was the issue that I'm just gonna close this ticket. Feel free to comment on it if you're still running into issues for some reason. Thanks for your time, and I hope this helps!
