### ISSUE TITLE
'npm update' fails with EBADPLATFORM for a previously skipped opt. dependency

### ISSUE THREAD

**Issue by MightyPork** [npm/npm#11973]
This is related to #10768, however that is closed and locked.

`npm update` fails if there is an optional dependency that was previously skipped in `npm install` because it's not available for this platform.

**Steps to reproduce:**

Put this in `package.json` (example from [GPMDP](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-) where I came across the issue)

``` json
{
  "optionalDependencies": {
    "ll-keyboard-hook-win": "^2.0.1"
  }
}
```

Run `npm install`, skipped as expected.

``` none
~/tmp/minimal $ npm install
npm WARN optional Skipping failed optional dependency //ll-keyboard-hook-win:
npm WARN notsup Not compatible with your operating system or architecture: ll-keyboard-hook-win@2.0.2
npm WARN minimal No description
npm WARN minimal No repository field.
npm WARN minimal No license field.
```

Run `npm update` - large red error and update fails.

``` none
~/tmp/minimal $ npm update
npm ERR! Linux 4.4.5-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "update"
npm ERR! node v5.9.0
npm ERR! npm  v3.8.1
npm ERR! code EBADPLATFORM

npm ERR! notsup Not compatible with your operating system or architecture: ll-keyboard-hook-win@2.0.2
npm ERR! notsup Valid OS:    win32
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ondra/tmp/minimal/npm-debug.log
```

**Platform:**

``` none
Kernel: 4.4.5-1-ARCH x86_64 (64 bit) 
Desktop: Xfce 4.12.3 
Distro: Arch Linux
NPM: 3.8.2
Node: 5.9.0
```

The log file it asked me to include is posted here: http://data.ondrovo.com/f/npm-debug.log

**Comment by zkat** [comment]
We shouldn't be crashing like this for optDeps, I think :)

**Comment by wvanderdeijl** [comment]
This is killing our Windows based builds. They start with an `npm update --depth 999` to ensure we used the latest versions of all dependencies. This fails for every project as we use `gulp` that requires `chokidar` which optionally requires `fsevents` which is OSX specific.

Simple steps to reproduce this in an empty **Windows** directory: create new npm project, add dependency to `chokidar`, run `update --depth 99`. See below for details:
```
D:\work\temp>npm init --yes
Wrote to D:\work\svn\client\package.json:

{
  "name": "temp",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "directories": {
    "test": "test"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}

D:\work\temp>npm install --save chokidar
`-- chokidar@1.4.3
  +-- anymatch@1.3.0
  | +-- arrify@1.0.1
  <... snip ... >
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.11
npm WARN temp@1.0.0 No description
npm WARN temp@1.0.0 No repository field.

D:\work\temp>npm update --depth 9
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" 
npm ERR! node v5.10.1
npm ERR! npm  v3.7.2
npm ERR! code EBADPLATFORM

npm ERR! notsup Not compatible with your operating system or architecture: fsevents@1.0.11
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64

npm ERR! Please include the following file with any support request:
npm ERR!     D:\work\temp\npm-debug.log
```

Only workaround I could find is to clear node_modules directory each time which is a PITA.

**Comment by wvanderdeijl** [comment]
Seems related to #11992

**Comment by emirotin** [comment]
Has just encountered myself

**Comment by emirotin** [comment]
This doesn't sound like a reasonable approach to issues, npm.
The issue is not fixed, no reaction from the team shouldn't be equal "close"

**Comment by wvanderdeijl** [comment]
Strange to auto-close a bug that has been marked a bug by the project owner

**Comment by 007imash** [comment]
"Simple steps to reproduce this in an empty Windows directory: create new npm project, add dependency to chokidar, **_run update --depth 99._** See below for details:"

"D:\work\temp>npm update --depth 9"

You just typed in the command Incorrectly ... I got a similar error after typing the command incorrectly.

**Comment by shawnwhinnery** [comment]
wow I wish my project had a bot that auto-closed bugs we ignored for 30 days.

**Comment by turnerhayes** [comment]
Getting this issue for `fsevents` which wants OS darwin (optionally required by some third-party module). Never seen npm error out on it before, just got warnings.
