### ISSUE TITLE
"npm update" not working with "npm link" modules

### ISSUE THREAD

**Issue by blitzprog** [npm/npm#11998]
npm exits with...
```bash
npm ERR! No compatible version found: aero-ajax@linked
```
...when executing it in a project that uses npm linked modules (symlinks).
However the expected result is to ignore symlinked modules and update the normal modules.

**Comment by KenanY** [comment]
@blitzprog `npm --version`?

**Comment by blitzprog** [comment]
@KenanY: 3.7.3.

After seeing your comment I did...
```bash
npm install -g npm
```
...and it seems to be fixed now.

I apologize for the report on an outdated version.
