### ISSUE TITLE
npm self-destructs when being updated

### ISSUE THREAD

**Issue by oliversalzburg** [npm/npm#11994]
Whenever I have an issue with npm, I run `npm i -g npm` first, to make sure I don't have an outdated version.

This is a big mistake, because I keep forgetting that npm will destroy itself when I issue that command. I end up with the following output:

```
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Oliver\\AppData\                                                                                                                                                                                            \Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i" "-g" "npm"
npm ERR! node v4.3.1
npm ERR! npm  v3.3.10
npm ERR! path C:\Users\Oliver\AppData\Roaming\npm\npm
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall open

npm ERR! Error: EPERM: operation not permitted, open 'C:\Users\Oliver\AppData\Roaming\npm\npm'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM: operation not permitted, open 'C:\Users\Oliver\AppData\Roaming\npm\npm']
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'open',
npm ERR!   path: 'C:\\Users\\Oliver\\AppData\\Roaming\\npm\\npm' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Oliver\Projects\npm-debug.log
```

The result here is of course, that npm no longer works. The npm "binary" is missing now and I have to reinstall npm manually.

There is really no reason why npm shouldn't have access to my AppData folder. In fact, it works just fine:

```
Oliver@oliver-home MINGW64 ~/Projects
$ echo foo > /c/Users/Oliver/AppData/Roaming/npm/npm

Oliver@oliver-home MINGW64 ~/Projects
$ cat /c/Users/Oliver/AppData/Roaming/npm/npm
foo
```

[`npm-debug.log`](https://gist.github.com/oliversalzburg/57fb7aa18fc932eadaaf)

**Comment by oliversalzburg** [comment]
This still happens every single time I upgrade npm. Is there anything I can do to help resolve this?

**Comment by busches** [comment]
Have you tried running `npm cache clean`? How are you running `npm`? Through `cmd` or some other program? I personal run the same command myself on Windows 10, via `cmder` and don't have any issues and no one else appears to be reporting the same thing which make it appear like an environment issue.

**Comment by oliversalzburg** [comment]
I've been running it through the Git Bash. However, I've since migrated to https://github.com/felixrieseberg/npm-windows-upgrade to work around the issue.
