### ISSUE TITLE
npm

### ISSUE THREAD

**Issue by FETAR** [npm/npm#11996]
![image](https://cloud.githubusercontent.com/assets/17994900/13938736/3c2e965c-efc6-11e5-8271-f26d943fc7af.png)
Hi

This is what I am getting whenever I try to install npm install -g cordova ionic. Can anyone help

**Comment by amandeepmittal** [comment]
Is there a proxy server on your network? Please check your npm proxy configuration and try again.

**Comment by FETAR** [comment]
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\windows\system32>node --version
v4.4.0

C:\windows\system32>npm --version
3.8.2

C:\windows\system32>cd c:\

c:\>npm install -g cordova ionic
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm a
nd is now out of date with respect to npm
C:\Users\FETARSTJOHN\AppData\Roaming\npm\cordova -> C:\Users\FETARSTJOHN\AppData
\Roaming\npm\node_modules\cordova\bin\cordova
C:\Users\FETARSTJOHN\AppData\Roaming\npm\ionic -> C:\Users\FETARSTJOHN\AppData\R
oaming\npm\node_modules\ionic\bin\ionic
C:\Users\FETARSTJOHN\AppData\Roaming\npm
+-- cordova@6.0.0
`-- ionic@1.7.14


c:\>

**Comment by FETAR** [comment]
Hi amandeep. I turned the proxy server on. This was the result. thanks for your help.

**Comment by FETAR** [comment]
Hi Amandeep.

 I turned the proxy server on and this was the result. Not entirely sure if ionic is installed.

Thanks for your help

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\windows\system32>node --version
v4.4.0

C:\windows\system32>npm --version
3.8.2

C:\windows\system32>cd c:\

c:\>npm install -g cordova ionic
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm a
nd is now out of date with respect to npm
C:\Users\FETARSTJOHN\AppData\Roaming\npm\cordova -> C:\Users\FETARSTJOHN\AppData
\Roaming\npm\node_modules\cordova\bin\cordova
C:\Users\FETARSTJOHN\AppData\Roaming\npm\ionic -> C:\Users\FETARSTJOHN\AppData\R
oaming\npm\node_modules\ionic\bin\ionic
C:\Users\FETARSTJOHN\AppData\Roaming\npm
+-- cordova@6.0.0
`-- ionic@1.7.14


c:\>

**Comment by amandeepmittal** [comment]
glad to hear that but you reopened the issue, is there still a problem?

**Comment by FETAR** [comment]
Everything seems fine now . Thanks again
