### ISSUE TITLE
Error: 400 Bad Request

### ISSUE THREAD

**Issue by achmatch** [npm/npm#11999]
```
npm ERR!     at WriteStream.<anonymous> (/usr/lib/node_modules/npm/lib/utils/fetch.js:57:12)
npm ERR!     at WriteStream.emit (events.js:117:20)
npm ERR!     at fs.js:1610:14
npm ERR!     at /usr/lib/node_modules/graceful-fs/graceful-fs.js:103:5
npm ERR!     at Object.oncomplete (fs.js:108:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-573.18.1.el6.i686
npm ERR! command "node" "/usr/bin/npm" "install"
npm ERR! cwd /var/www/html/ghost
npm ERR! node -v v0.10.42
npm ERR! npm -v 1.3.6
```

**Comment by othiym23** [comment]
The versions of npm and Node.js packaged by Debian and Ubuntu are very old. In the case of npm, they're so old they're no longer supported and will no longer work with the npm registry. I suggest that you remove the Debian / Ubuntu-packaged versions of Node.js and replace them with [NodeSource distribution](https://github.com/nodesource/distributions). You'll get a more up-to-date Node and npm in the bargain. If you do this, you should be able to install Ghost. I'm going to close this for now, but let me know if that doesn't work, and we can reopen.

**Comment by achmatch** [comment]
But im using CentOS 6.7 32Bit....

**Comment by othiym23** [comment]
That's useful to know! Thank you!

My advice remains the same – those versions of npm and Node.js are very old, and the version of npm is unsupported by the team (and Node.js 0.10 is drawing close to being [end of life](https://github.com/nodejs/LTS) as well). There should be [a `yum install`able version of Node LTS](https://github.com/nodesource/distributions#rpm) on the Node distributions page you can use with CentOS.

**Comment by achmatch** [comment]
Thanks Bro.....
