### ISSUE TITLE
npm install -g global writes incorrect shortcut to AppData\Roaming\npm

### ISSUE THREAD

**Issue by s-a** [npm/npm#12005]
Trying to install a test module (https://github.com/s-a/terminal-center) globaly and figured out, that npm does not write the ```.cmd``` on Windows 10 correct.

Look like npm does not know where the local node was installed.

Left side was written by node  
Right side was fixed by me
![image](https://cloud.githubusercontent.com/assets/1270662/13951514/be42f514-f031-11e5-8af0-7168b5fb906e.png)

```
)npm -v
2.14.20

)node -v
v4.4.0
```

Any ideas what s going wrong on my system?

**Comment by zkat** [comment]
We don't rewrite things quite like that: try `#!/usr/bin/env node`, which `cmd-shim` has special support for, instead of pathing fully to node. It's probably gonna cause problems for your shebang to path to a specific node like that, even on *nixes

**Comment by s-a** [comment]
Thanks a lot! this was very helpful. Would be nice if npm could warn about this circumstance. :)
