### ISSUE TITLE
Invalid Version 1.0.2beta

### ISSUE THREAD

**Issue by craigodavis** [npm/npm#12004]
Hi,  I just installed npm 3.8.2 and am getting the following error when running npm install:
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.9.0
npm ERR! npm  v3.8.2

npm ERR! Invalid Version: 1.0.2beta
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

Here is the log file:
[npm-debug.log.zip](https://github.com/npm/npm/files/184016/npm-debug.log.zip)

Any help would be greatly appreciated!

**Comment by zkat** [comment]
Are you using `1.0.2beta` as the version for your package? That's not a valid semver range. According to [the semver spec](http://semver.org/#spec-item-9), the correct syntax would be `1.0.2-beta` in order to be valid.

**Comment by godserahul1986** [comment]
@zkat So the semver specs are applied on all npm versions now onwards? I had a package versioned 9.2.0.2 and everything worked fine weeks back and now the build fails with the error Invalid version: 9.2.0.2

**Comment by zkat** [comment]
@godserahul1986 I honestly don't know what version of npm would allow you to get away with an invalid semver like that -- `version` was never meant to be anything but valid semver ranges, and any case where that was possible is simply a bug.

**Comment by nikhilmotiani** [comment]
I tried with npm v3.8.6, the issue is still there.. Is there an expected timeline when this would get fixed?

**Comment by KenanY** [comment]
@nikhilmotiani There's no bug here as far as I can tell.
