### ISSUE TITLE
Can't install gulp-babel with npm

### ISSUE THREAD

**Issue by justintemps** [npm/npm#12012]
npm gives me this error: No compatible version found: left-pad@0.0.3

**Comment by eikeon** [comment]
Ditto: https://hub.docker.com/r/eikeon/bagger-js/builds/brerab2zag6szfdpgtv8jba/

**Comment by othiym23** [comment]
The maintainers of [`left-pad`](http://npm.im/left-pad) have chosen to unpublish it, for reasons that are [not yet clear](https://github.com/azer/left-pad/issues/4). This is not an issue with npm, but is something that should be taken up with both the maintainers of `left-pad` and those of `babelify`, `gulp-babel`, and the other users of `left-pad`. As this isn't an issue with the npm CLI, there really isn't much the CLI team can do.

**Comment by givanse** [comment]
duh! thanks :+1:

**Comment by elad-maimon** [comment]
Same issue here.
That means it's impossible to install babel-core since left-pad@0.0.3 is a dependency of it..

**Comment by othiym23** [comment]
@elad-maimon That's true! But this isn't an issue that the npm CLI team can fix. If you look at azer/left-pad#4, you'll see that the Babel collaborators are working on getting out a fixed version of `babel-core` that doesn't depend on the unpublished version of `left-pad`.

**Comment by DefinitelyCarter** [comment]
Just curious, why is it possible to unpublish a module that is depended on others?  Seems like NPM folks should validate that.

**Comment by sammosampson** [comment]
yep this really screws up a lot of things including react native

**Comment by elad-maimon** [comment]
@othiym23 sure I'm sorry, I'm following azer/left-pad#4. Thanks!

**Comment by givanse** [comment]
babel-core doesn't depend on it directly apparently, its more of a dependency of a dependency...

**Comment by othiym23** [comment]
> Just curious, why is it possible to unpublish a module that is depended on others?

Because there may be a critical security flaw, or the package may contain sensitive information and have been published in error, or any of a host of other issues. I agree that this is inconvenient, but this is a necessary feature in a registry to which anybody can contribute packages.

**Comment by joeandaverde** [comment]
@othiym23 would it have been possible for him to publish the same version WITH a security flaw?

**Comment by othiym23** [comment]
@joeandaverde I'm not sure what you mean.

**Comment by DefinitelyCarter** [comment]
> Because there may be a critical security flaw, or the package may contain sensitive information and have been published in error, or any of a host of other issues. I agree that this is inconvenient, but this is a necessary feature in a registry to which anybody can contribute packages.

I think in that scenario `npm install left-pad@0.0.4` could fail but the other modules that depend on it should succeed.  

Those authors should be notified when a version they depend on is unpublished.  Allowing their module to work and find and upgrade path.

**Comment by joeandaverde** [comment]
@othiym23 If he can remove a package, surely he can re-add with the same version. Wouldn't that give him the opportunity to upload a malicious version?

**Comment by seldo** [comment]
@joeandaverde: it is not possible to republish a package with the same version as an unpublished version.

**Comment by redconfetti** [comment]
For reference: [azer/left-pad](https://github.com/azer/left-pad)

**Comment by krainboltgreene** [comment]
Just so it's clear: This is how rubygems operates as well. We (package managers) have to be able to remove access to published libraries for a variety of reasons.

Sadly there's no computer program in existence that can make sure removing is for the right reason.

**Comment by givanse** [comment]
The problem is not the ability to do those things. It is needed.

What is needed is improved communication. Make it very loud and obvious that the package was removed so that the maintainers can decide to add it back or not.

```
npm install
```

Should fail for packages that were re-published, so that they get be approved by consumers again.

**Comment by krainboltgreene** [comment]
> Make it very loud and obvious that the package was removed so that the maintainers can decide to add it back or not.

The maintainers of the package unpublished the package themselves.

> Should fail for packages that were re-published

Just for clarification "re-publish" means push a new version, which seems to be what should have happened.

**Comment by elad-maimon** [comment]
@othiym23 as a suggestion maybe instead of removing it allow the publisher to mark it as deprecated or something else that will show a warning ?

After all, if a package has been removed it won't make any difference for running applications, it will just stop the development process since "npm install" won't work. So IMHO a warning should be enough to continue working while opening a bug for the maintainers to bump a version in their dependencies.

**Comment by rahatarmanahmed** [comment]
Relevant blog post: https://medium.com/@azerbike/i-ve-just-liberated-my-modules-9045c06be67c#.kffhh1epq

**Comment by krainboltgreene** [comment]
@elad-maimon Here's the Rubygems ongoing discussion on this feature: https://github.com/rubygems/rubygems/issues/1506

**Comment by bjrmatos** [comment]
> Because there may be a critical security flaw, or the package may contain sensitive information and have been published in error, or any of a host of other issues. I agree that this is inconvenient, but this is a necessary feature in a registry to which anybody can contribute packages.

@othiym23 i understand those reasons but it is practically unacceptable that if someone decides to unpublish a package that decision affects a lot of installs and practically break the whole build in our projects :(

**Comment by krainboltgreene** [comment]
@bjrmatos: That's a great ideal until someone publishes your home address or social security number.

Alternatively: It's the author's content, not the users.

**Comment by othiym23** [comment]
As this is well beyond the scope of the CLI, and as there isn't any new or useful discussion happening here, I'm going to lock this thread. Thanks to all who helped in quickly responding to this issue, and I'm genuinely sorry this created so much awkwardness and wasted time for so many.
