### ISSUE TITLE
Cannot init React Native project - "npm ERR! Invalid Version: 0.0.1alpha1"

### ISSUE THREAD

**Issue by ghost** [npm/npm#12011]
Hi,

as stated in the subject, I can't get React Native going. Already tried to update node and npm, to no avail. Globally installing semver also didn't help. Error message:

`This will walk you through creating a new React Native project in` `/Users/Ronin/Developer/ReactNative/FirstProject`
`Installing react-native package from npm...`

`npm ERR! Darwin 15.4.0`
`npm ERR! argv "/usr/local/Cellar/node/5.9.0/bin/node" "/usr/local/bin/npm" "install" "--save" "react-native"`
`npm ERR! node v5.9.0`
`npm ERR! npm  v3.8.2`

`npm ERR! Invalid Version: 0.0.1alpha1`
`npm ERR!`
`npm ERR! If you need help, you may report this error at:`
`npm ERR!     <https://github.com/npm/npm/issues>`

`npm ERR! Please include the following file with any support request:`
`npm ERR!     /Users/Ronin/Developer/ReactNative/FirstProject/npm-debug.log`

`npm install --save react-native failed`

npm-debug.log can be found under [https://www.dropbox.com/s/i18ney35t93ldts/npm-debug.log?dl=0](url).

I'd appreciate help with this issue. This most likely is just some rookie mistake, but I'm out of ideas, and so is Google.

Regards,
Michal

**Comment by zkat** [comment]
Hi! It looks like your package might be using an invalid semver range. According to the [semver spec](http://semver.org/#spec-item-9), your version would need to be `0.0.1-alpha1` in order to be valid.

**Comment by jt3k** [comment]
`mv ~/.npmrc ~/.npmrc-maybe-bad`
is fix the problem
