### ISSUE TITLE
Set uid Issue in Ubuntu Node 0.10.25

### ISSUE THREAD

**Issue by allupaku** [npm/npm#12023]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'intall', '-g', 'pm2' ]
2 info using npm@1.4.21
3 info using node@v0.10.25
4 error Error: setuid user id does not exist
4 error     at /usr/share/npm/node_modules/uid-number/uid-number.js:44:16
4 error     at ChildProcess.exithandler (child_process.js:635:7)
4 error     at ChildProcess.EventEmitter.emit (events.js:98:17)
4 error     at maybeClose (child_process.js:743:16)
4 error     at Process.ChildProcess._handle.onexit (child_process.js:810:5)
5 error If you need help, you may report this _entire_ log,
5 error including the npm and node versions, at:
5 error     http://github.com/npm/npm/issues
6 error System Linux 4.5.0-x86_64-linode65
7 error command "/usr/bin/nodejs" "/usr/bin/npm" "intall" "-g" "pm2"
8 error cwd /var/www
9 error node -v v0.10.25
10 error npm -v 1.4.21
11 verbose exit [ 1, true ]

**Comment by zkat** [comment]
Hi! We don't really support the version of npm you're currently running, and I suspect there's a good chance upgrading will fix your issue: Could you do `npm i -g npm` (use `sudo` if you get a permissions error), and try again?
