### ISSUE TITLE
issue with npm install concat@1.0.0

### ISSUE THREAD

**Issue by ranjansumit** [npm/npm#12022]
I was using npm install concat@1.0.0 till 22nd march,2016. and it stopped working 23rd onwards. I logged to website https://www.npmjs.com/package/concat and saw that new concat is available 6 hours ago. So I want to know whether 1.0.0 is supported version or it won't be supported.

I am using it in my automation. so every time a release happens, Do I need to upgrade the version?

**Comment by c-goldschmidt** [comment]
[Registry request](https://registry.npmjs.org/concat/1.0.0) 404's, for all versions before 2.0.0, i guess the author broke it by accident when releasing 2.0.0

**Comment by ranjansumit** [comment]
@c-goldschmidt Do you have any idea, whether that was done intentionally or that would be fixed later.

**Comment by paulcurley** [comment]
https://medium.com/@azerbike/i-ve-just-liberated-my-modules-9045c06be67c#.5gx4ly5w2

**Comment by zkat** [comment]
@ranjansumit that package was removed from the registry. You'll have to use a different one or wait until someone decides to republish with a new version, and upgrade to that.

I'm gonna close this, since there's not much to be done about packages that just don't exist in our registry :\
