### ISSUE TITLE
browser-sync installation failing again and again

### ISSUE THREAD

**Issue by karkun** [npm/npm#12020]
![capture2](https://cloud.githubusercontent.com/assets/17996853/13975836/96963270-f0df-11e5-8ea7-4eb43b656549.JPG)

**Comment by zkat** [comment]
I really don't know what this is, but it's really really strange. I can't even find any sign of this sort of error message, aside from having seen one in fairly different circumstances with #9052. I'm marking this as a bug and hopefully we find a way to repro it or get more details or something.

Could you please upload npm-debug.log for us into a gist or similar, so we can look at that log for details?
