### ISSUE TITLE
NPM 3.5.2 strict-ssl .npmrc at project level

### ISSUE THREAD

**Issue by deenairn** [npm/npm#12025]
I've noticed that when I add strict-ssl = false in the project level .npmrc file - the behaviour is different to when it is added at the user or global settings. It does not appear to use the .npmrc setting at the project level for strict-ssl, but does use any of the other settings applied (proxy, http-proxy, registry). The only way I've found to get it to work is to add strict-ssl at either the user or global level. Is this the anticipated behaviour of NPM or a defect?

**Comment by francisoud** [comment]
Can't reproduce.
I just added this line to my "project level" .npmrc (making sure it wasn't set elsewhere global/user) and it worked for me:

`strict-ssl=false`

```
>npm --version
3.9.3
> ver
Microsoft Windows [version 6.1.7601]
```
