### ISSUE TITLE
Installation of swagger editor on Windows fails

### ISSUE THREAD

**Issue by Abel-Torres** [npm/npm#12033]
From the command line:

C:\>npm install -g swagger
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "swagger"

npm ERR! node v4.4.0
npm ERR! npm  v2.14.20
npm ERR! code DEPTH_ZERO_SELF_SIGNED_CERT

npm ERR! self signed certificate
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\npm-debug.log

C:\>npm install -g swagger
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "swagger"

npm ERR! node v4.4.0
npm ERR! npm  v2.14.20
npm ERR! code DEPTH_ZERO_SELF_SIGNED_CERT

**Comment by zkat** [comment]
Hi @Abel-Torres! Could you upload the `npm-debug.log` in question? Also: Are you behind a corporate firewall or similar? Certificate errors tend to point towards proxy issues.

**Comment by Abel-Torres** [comment]
Thank you for your prompt response!



You are right: I needed to define the proxy used here. I’ve done that and ran the following command:
   npm install –g swagger

However, the next command fails because there is no such directory:
   cd swagger-editor

It did create this:
C:\Users\torreabe.AUTH\AppData\Roaming\npm\node_modules\swagger


So, where’s the swagger editor installation?


--Abel Torres

**Comment by zkat** [comment]
npm isn't like git -- when you do `npm i -g swagger`, it's actually going to install the application globally. In this case (after I looked at the [readme](https://www.npmjs.com/package/swagger#1-install-the-swagger-module)), it means you should be able to run `swagger` in the command line now. If you want the source code, you should instead [clone the git repository itself](https://github.com/swagger-api/swagger-node), through github.

**Comment by Abel-Torres** [comment]
Yes, I can run it from the command line now.

Consider this issue closed.

Thank you!
--Abel

**Comment by zkat** [comment]
Glad I could help! Have a good one, and thanks for your time, too :)
