### ISSUE TITLE
Npm Errors

### ISSUE THREAD

**Issue by ruchikasb** [npm/npm#12036]
$ /var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/marketing/bin/npm install -g --ignore-ssl-errors=true  --strict-ssl=false  grunt@0.4.5 grunt-cli@0.1.13 bower@1.4.1 karma@0.12 gulp@3.9.0
npm ERR! Usage:
npm ERR!     npm cache add <tarball-url>
npm ERR!     npm cache add <pkg>@<ver>
npm ERR!     npm cache add <tarball>
npm ERR!     npm cache add <folder>
npm ERR! 
[workspace] $ /bin/sh -xe /tmp/hudson3455566568059752299.sh
+ npm cache clean all
+ npm prune
npm WARN package.json marketing@2.0.0 No license field.
+ npm install
npm WARN package.json marketing@2.0.0 No license field.
npm WARN deprecated gulp-karma@0.0.4: Please use Karma directly: https://github.com/karma-runner/gulp-karma
npm WARN deprecated gulp-plato@1.0.2: Deprecated. Just use the `plato` module directly.
npm WARN engine karma@0.12.1: wanted: {"node":"~0.8 || ~0.10"} (current: {"node":"4.1.2","npm":"2.14.4"})
npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated npmconf@0.0.24: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN engine coffee-script-redux@2.0.0-beta8: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"4.1.2","npm":"2.14.4"})
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated lodash@2.4.1: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN optional dep failed, continuing fsevents@0.2.1
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
> kerberos@0.0.3 install /opt/jenkins_jobs/marketing-hal-qa-BUILD/workspace/node_modules/mongodb/node_modules/kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/opt/jenkins_jobs/marketing-hal-qa-BUILD/workspace/node_modules/mongodb/node_modules/kerberos/build'
  SOLINK_MODULE(target) Release/obj.target/kerberos.node
  COPY Release/kerberos.node
make: Leaving directory `/opt/jenkins_jobs/marketing-hal-qa-BUILD/workspace/node_modules/mongodb/node_modules/kerberos/build'
> bson@0.2.12 install /opt/jenkins_jobs/marketing-hal-qa-BUILD/workspace/node_modules/mongodb/node_modules/bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/opt/jenkins_jobs/marketing-hal-qa-BUILD/workspace/node_modules/mongodb/node_modules/bson/build'
  CXX(target) Release/obj.target/bson/ext/bson.o
make: Leaving directory `/opt/jenkins_jobs/marketing-hal-qa-BUILD/workspace/node_modules/mongodb/node_modules/bson/build'

> phantomjs@1.9.8 install /opt/jenkins_jobs/marketing-hal-qa-BUILD/workspace/node_modules/phantomjs
> node install.js

Download already available at /tmp/phantomjs/phantomjs-1.9.7-linux-x86_64.tar.bz2
Extracting tar contents (via spawned process)
Copying extracted folder /tmp/phantomjs/phantomjs-1.9.7-linux-x86_64.tar.bz2-extract-1458766504598/phantomjs-1.9.7-linux-x86_64 -> /opt/jenkins_jobs/marketing-hal-qa-BUILD/workspace/node_modules/phantomjs/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /opt/jenkins_jobs/marketing-hal-qa-BUILD/workspace/node_modules/phantomjs/lib/phantom/bin/phantomjs
npm WARN deprecated graceful-fs@1.1.14: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
> ws@0.4.32 install /opt/jenkins_jobs/marketing-hal-qa-BUILD/workspace/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/opt/jenkins_jobs/marketing-hal-qa-BUILD/workspace/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
make: Leaving directory `/opt/jenkins_jobs/marketing-hal-qa-BUILD/workspace/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/build'
npm ERR! Linux 2.6.32-504.3.3.el6.x86_64
npm ERR! argv "/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/marketing/bin/node" "/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/marketing/bin/npm" "install"
npm ERR! node v4.1.2
npm ERR! npm  v2.14.4

npm ERR! version not found: iter@0.0.5
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/jenkins_jobs/marketing-hal-qa-BUILD/workspace/npm-debug.log
Build step 'Execute shell' marked build as failure
Started calculate disk usage of build
Finished Calculation of disk usage of build in 0 seconds
Started calculate disk usage of workspace
Finished Calculation of disk usage of workspace in  1 second
Finished: FAILURE

**Comment by arLevi** [comment]
+1
