### ISSUE TITLE
Stream `npm pack` result when invoked with `--stdout`

### ISSUE THREAD

**Issue by anko** [npm/npm#12039]
At the moment, `npm pack` always outputs a file in the current directory, and its name on `stdout`.

```
$ ls
package.json
$ npm pack
packagename-1.0.0.tgz
$ ls
package.json  what-1.0.0.tgz
```

But sometimes you want to send the file immediately to a server somewhere e.g. for deployment. I'd like to be able to do this in a project directory:

```
$ npm pack --stdout | ssh myserver deployscript.sh
```

Every part of the compressed package would then be compressed and streamed as soon as any of it is ready, without having to hit the disk in between. This should make a difference when working with big packages or slow filesystems. And a one-liner deploy would be _super nice_.

Would you take a PR for this?

**Comment by ranolf** [comment]
+1

**Comment by ORESoftware** [comment]
I am definitely looking for this feature.

`npm pack` should always write to stdout. if you want to write to a file, you would just do:

`npm pack > $file`

but now that the API is already like it is, I think we should have an option to write to stdout.

`npm pack --stdout`

**Comment by ORESoftware** [comment]
@anko perhaps we can create our own implementation of `npm pack` that writes to stdout?

**Comment by legodude17** [comment]
Based on initial research, you would need to modify [this](https://github.com/npm/npm/blob/latest/lib/pack.js#L82) and [this](https://github.com/npm/npm/blob/latest/lib/pack.js#L107) to respect your new option.

**Comment by ORESoftware** [comment]
Yes here is my _exact issue_ - using Docker, I mount some readonly (RO) volumes. if `npm pack` writes to the filesystem, it won't work. I need `npm pack` to read from a local package, but not write to it - it needs to write to stdout instead. I basically I want to do exactly what @anko wants to do.

@legodude17 sorry I don't understand those two links, I read them but much of the NPM codebase is pretty  foreign to me.

Would you accept a PR for just the feature, and then we can go from there? I assume `npm.commands.pack = ` is the place to start for a PR for the original issue here.

**Comment by ORESoftware** [comment]
If anyone has insights on this question - replicating npm pack behavior with tar, lmk:
https://stackoverflow.com/questions/50356339/replicating-npm-pack-behavior

**Comment by ORESoftware** [comment]
the tar package used by NPM itself, has an option to write to stdout:
https://www.npmjs.com/package/tar

eg:

```js
tar.c( // or tar.create
  {
    gzip: <true|gzip options>
  },
  ['some', 'files', 'and', 'folders']
).pipe(fs.createWriteStream('my-tarball.tgz')
```

so this can't be that hard, maybe it's just not documented?

`npm pack -x`

there must be some switch we can use to send to stdout or something

**Comment by legodude17** [comment]
From what I've seen, there is no option like that currently, but it's not too hard to add it.
