### ISSUE TITLE
Error: version not found: read-json@0.1.0

### ISSUE THREAD

**Issue by sgxman** [npm/npm#12030]
Error running npm install in bootstrap directory.

Error: 
version not found: read-json@0.1.0

Tried everything but can't figure it out.

**Comment by KenanY** [comment]
@sgxman `readjson@0.1.0` has been unpublished. Try installing a newer version, such as one of the following

``` bash
$ npm info read-json versions
[ '1.0.1', '1.0.2', '1.0.3' ]
```

**Comment by sgxman** [comment]
Should I run "nmp install read-json" from the bootstrap directory or from another directory?
Is there any additional steps to take. Running on WIndows 10.
Installed git, nodejs, grunt, bootstrap 4 days ago on another Windows 10 PC without any problems.

**Comment by zkat** [comment]
Looks like you're all set! Glad you could figure it out. :)
