### ISSUE TITLE
shasum check failed while installing any package

### ISSUE THREAD

**Issue by atulquest93** [npm/npm#12034]
Already Tried 
 - Direct installing using URL. 
 - Changing http://registry.npmjs.org to chinese mirror.

NPM : @3.7.2
Node : v5.9.1
```
atulquest93@atulquest99 MINGW64 ~
$ npm install cordova
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "cordova"
npm ERR! node v5.9.1
npm ERR! npm  v3.7.3

npm ERR! shasum check failed for C:\Users\ATULQU~1\AppData\Local\Temp\npm-5060-d9830b4e\registry.npmjs.org\cordova-lib\-\cordova-lib-6.1.0.tgz
npm ERR! Expected: 9235ba315a1da492aa68bda0f39b37c84ee4a9b1
npm ERR! Actual:   b5fb5f6c150f9b454e4dc8023b70e497e30017f6
npm ERR! From:     http://registry.npmjs.org/cordova-lib/-/cordova-lib-6.1.0.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>


```

**Comment by zkat** [comment]
Hi, @atulquest93! Would you mind doing `npm cache clean` and trying this again? If that fails, could you upload the `npm-debug.log` file, which will have more details about this failure?

**Comment by atulquest93** [comment]
Forgot to mention, i have already tried clearning cache.
Here's the npm-debug

[npm-debug.txt](https://github.com/npm/npm/files/187150/npm-debug.txt)

**Comment by zkat** [comment]
Could you try removing that specific file and trying again:
`rm C:\Users\ATULQU~1\AppData\Local\Temp\npm-5060-d9830b4e\registry.npmjs.org\cordova-lib\-\cordova-lib-6.1.0.tgz`

I download the current tarball in our registry and checked the shasum and it seems right, so let's try that and see :)

**Comment by atulquest93** [comment]
@zkat 
Thanks ! Solved. 
I think the problem is with the corrupted downloaded. Cleared the %temp% and it works.
