### ISSUE TITLE
Properly document the --dev flag of `npm shrinkwrap`

### ISSUE THREAD

**Issue by cvrebert** [npm/npm#12043]
- It's missing from the SYNOPSIS
- It should be documented as a flag, ala:

> o **--dev**: Include **devDependencies**

**Comment by zkat** [comment]
Based on your previous contribs, it sounds like we should expect a PR soon? ;)

**Comment by cvrebert** [comment]
No, you shouldn't.

**Comment by zkat** [comment]
Aww fair enough. Sorry for assuming! And thanks for submitting the issue. :)

**Comment by watilde** [comment]
Is this part of the docs mentioned about `--dev` flag not enough?
> devDependencies will not be included unless you explicitly set the --dev flag when you run npm shrinkwrap
https://github.com/npm/npm/blob/master/doc/cli/npm-shrinkwrap.md#other-notes

In this context, a way of writing to mention about command line options is not standardized.

**Comment by cvrebert** [comment]
> In this context, a way of writing to mention about command line options is not standardized.

What context are you referring to? The de facto standard for manpages is to list all the options and include a description along with each list item. [The docs for `npm install`](https://github.com/npm/npm/blob/master/doc/cli/npm-install.md) work the same way:


> o **-S**, **--save**: Package will appear in your dependencies.
> [...]
> The **--tag** argument will [...]

There's quibbling over how to format the list, but it's still presented as a list, with the option itself near the front, not buried inside a prose paragraph.
And it's put in the DESCRIPTION or OPTIONS section, not buried in "Other Notes" like shrinkwrap does.

**Comment by watilde** [comment]
Yeah I meant the docs formatting to list all the options like `aliases` which are written in all cli docs as same formatting. I mentioned it because I did format recently for aliases f0bf684 and knew it is easy to forget adding to docs, but yeah it's not a really important for now like you said. Agreed :)
// Formatting docs sometimes helps us when we update docs and docs will be translated

**Comment by cvrebert** [comment]
This is still relevant, silly npm bot.
