### ISSUE TITLE
Prevent publishing to public registries with License that doesn't allow sharing.

### ISSUE THREAD

**Issue by martinheidegger** [npm/npm#12042]
_(Note: I am not sure what the exact current behaviour is, maybe needs work on the documentation?!)_
Referencing recent problems I wondered if it might be a good idea to prevent people from publishing public packages to **the public npm registry** under a license that prevents redistribution? Seeing as the public registry already distributes the package it would just make sense to me?

**Comment by zkat** [comment]
Hey Martin! :D 

There's been conversations in the past about eventually having a semantic tool (with uh, lawyer help ;) ) that could be used to analyze the various compatibility issues involved in very large projects. We know some licensing-sensitive companies who use npm have talked to us about this in the past.

At the same time, it's unlikely we'll outright prevent publishing, and even unlikely that we would prevent installation, unless explicitly requested by the installing user. (odds are, if this ever gets written, that we'd just spit out a warning).

All that said, it's very unlikely we'd get around to a feature request that addresses this in the next year, and I imagine this would be tricky for us to simply accept a patch for this from the community without extensive discussions (and probably a lot of consulting with relevant counsel). Usually, we mark those types of feature requests and close them right off, but I want to take a day or two to check on that and figure out if there's some other resources I can point you to about this: my searches failed, here.

Thanks for filing this, and hi! :wave: Hope Kansai is nice this time of year. The weather in Oakland has been fantastic (by my standards! :joy_cat:)

**Comment by martinheidegger** [comment]
Hi Kat,

Could a list of licences that allow distribution, verified by an (american?) lawyer help this issue? The question that the lawyer would need to answer is "Does license-x allow free redistribution?"

**Comment by zkat** [comment]
Unlikely. A lot of this also has to do with checking license compatibilities, and we happen to have access to this sort of counsel. Most of the work is probably planning out the feature and allocating time and resources to seeing it through, and _that_ is very unlikely to happen soon. It's basically on users to check that they're following things appropriately. :)

**Comment by martinheidegger** [comment]
For this particular case: License compatibility would not be required, am i wrong? Its just `if (allowsRedistribution(license)) {....}`

If **your** resources don't allow to work on it, it would be nice to see/know if others could work at this.

PS.: I have never been to Oakland but it sounds nice from what I hear. Osaka (Kyoto right this minute) is just about to get nice and warm. Cherry blossom next week.
