### ISSUE TITLE
Error while Installing grunt using NPM

### ISSUE THREAD

**Issue by vprasadkot** [npm/npm#12044]
I am getting below error while running install command for grunt. (not only for this for all installations). I have also set the path for nodejs and node_modules in environment variables. 
Please help me in fixing this
Note: I do not have admin privileges to system. So iam using D drive for this.

Command used : npm install -g grunt-cli
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\nodejs\\node.exe" "D:\nodejs\node_modules\npm\bin\npm-
cli.js" "install" "-g" "grunt-cli"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! syscall getaddrinfo

npm ERR! getaddrinfo EAI_AGAIN
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     http://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\venkataprasad.kota\npm-debug.log

**Comment by zkat** [comment]
Hey! `EAI_AGAIN` errors coming from `getaddrinfo` usually point to network issues: most likely proxies and firewalls.

Are you behind a corporate firewall? Make sure you can access https://registry.npmjs.org with this computer, and talk with your network admin about whitelisting, or setting up a proxy for npm, it so you can download packages :)

**Comment by vprasadkot** [comment]
Hi zkat, Though I am in corporate network, I am having access to this URL and i could able to browse that link. Will be there any restriction from command prompt to access secured urls

**Comment by zkat** [comment]
Could you try `npm ping`?

**Comment by vprasadkot** [comment]
I am sorry i am not that families with the syntax. please let me know whether the syntax is correct or not 
npm ping --registry 'https://registry.npmjs.org'

**Comment by zkat** [comment]
That is correct. Could you try it with both `--registry` and without it?

**Comment by vprasadkot** [comment]
I have tried in both ways. Using "--registry" statement, below message showing allong with npm help for comman. Without "--registry" it is showing npm command help
npm WARN invalid config registry="'https://registry.npmjs.org
npm WARN invalid config Must be a full url with 'http://'

**Comment by zkat** [comment]
ah! Try it without the `'` quotes: `npm ping --registry https://registry.npmjs.org`

**Comment by vprasadkot** [comment]
Response is as below 

Usage: npm <command>

where <command> is one of:
    access, add-user, adduser, apihelp, author, bin, bugs, c,
    cache, completion, config, ddp, dedupe, deprecate, dist-tag,
    dist-tags, docs, edit, explore, faq, find, find-dupes, get,
    help, help-search, home, i, info, init, install, issues, la,
    link, list, ll, ln, login, ls, outdated, owner, pack,
    prefix, prune, publish, r, rb, rebuild, remove, repo,
    restart, rm, root, run-script, s, se, search, set, show,
    shrinkwrap, star, stars, start, stop, t, tag, test, tst, un,
    uninstall, unlink, unpublish, unstar, up, update, v,
    verison, version, view, whoami

npm <cmd> -h     quick help on <cmd>
npm -l           display full usage info
npm faq          commonly asked questions
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    C:\Users\venkataprasad.kota\.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@2.5.1 C:\Program Files\nodejs\node_modules\npm

**Comment by zkat** [comment]
oh. Sorry. That's right, your npm version is too old for that. :(

I'll have to continue this tomorrow. It's late here and I'm afraid I'll be less helpful from here.

**Comment by vprasadkot** [comment]
Thank you so much for helping, I will try from my end to touch with network team, whether they could resolve. 

running version is 2.5.1 
when i tried with this , npm update -g npm, it executed successfully.

**Comment by InfiniteStyles** [comment]
Not sure if this was ever resolved, but this issue seems rather closed. Except for other people to use as a reference in similar situations.

**Comment by seg7293** [comment]
I know some other people

**Comment by legodude17** [comment]
Does anyone still have a problem with this?
