### ISSUE TITLE
Installing @privately-scoped packages with --no-bin-links fails for executables

### ISSUE THREAD

**Issue by mikerandall** [npm/npm#12049]
I've been experimenting with @scoped packages for our development team, and I came across an issue with --no-bin-links. 

The package in question is https://github.com/mikerandall/exos-npm-html2js. We currently have it in our private packages under a different name, and it's being used by a team of mostly Mac developers in a Vagrant VM. It installs fine for them, and is accessible in the command line via the command "npm-html2js". 

However, for our Windows developer, he needs to install all packages using the --no-bin-links attribute to circumvent the symlink issues. But doing so with private packages causes the "bin" to not be found. The package installs fine, but is not available on command line. After republishing the package publicly, it would install and be executable without any errors.

**Comment by othiym23** [comment]
> However, for our Windows developer, he needs to install all packages using the --no-bin-links attribute to circumvent the symlink issues.

The [purpose of the `--no-bin-links` option](https://docs.npmjs.com/misc/config#bin-links) is to prevent the creation of the links / shims that are used to expose command-line utilties from packages. What are you expecting to happen here?

**Comment by mikerandall** [comment]
Woops, you are correct—after I'd made this public, the puppet scripts used a different call without --no-bin-links. This is not an issue.
