### ISSUE TITLE
npm install cassandra-driver does not support Cassandra 3.4.0

### ISSUE THREAD

**Issue by lakandasamy** [npm/npm#12048]
No compatible version found: cassandra-driver@^3.4.0
npm ERR! Valid install targets:
npm ERR! 3.0.1, 3.0.0, 3.0.0-rc1, 3.0.0-beta1, 2.2.2, 2.2.1, 2.2.0, 2.2.0-rc1, 2.1.2, 2.1.1, 2.1.0, 2.0.1, 2.0.0, 1.0.3, 1.0.2, 1.0.1, 1.0.0, 1.0.0-beta1, 0.0.1-beta1
npm ERR!

**Comment by KenanY** [comment]
@lakandasamy Is this an issue with `npm`? No such version of `cassandra-driver` exists in the registry at the moment.

**Comment by lakandasamy** [comment]
Yes, it is an issue with npm.  It didn't find the cassandra-driver for cassandra version 3.4.0.

Thanks,
Latha

**Comment by KenanY** [comment]
@lakandasamy Ask the authors of `cassandra-driver` about their support for cassandra v3.4.0. This is not an issue with `npm`.

**Comment by jorgebay** [comment]
@lakandasamy All features of Cassandra 3.4 are supported in the latest driver version (v3.0.1): don't expect the server version to match the driver client version. 

You can close this issue.

**Comment by lakandasamy** [comment]
Yes, I did see them and it is working now with driver version (v3.0.1). Thanks.
