### ISSUE TITLE
reinstall node fail

### ISSUE THREAD

**Issue by highway33** [npm/npm#12054]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/5.6.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'info' ]
2 info using npm@3.6.0
3 info using node@v5.6.0
4 verbose config Skipping project config: /Users/haidong/.npmrc. (matches userconfig)
5 verbose stack Error: Invalid package.json
5 verbose stack     at /usr/local/lib/node_modules/npm/lib/view.js:81:30
5 verbose stack     at ReadFileContext.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:79:21)
5 verbose stack     at ReadFileContext.callback (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:76:16)
5 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete](fs.js:324:13)
6 verbose cwd /Users/haidong
7 error Darwin 14.5.0
8 error argv "/usr/local/Cellar/node/5.6.0/bin/node" "/usr/local/bin/npm" "info"
9 error node v5.6.0
10 error npm  v3.6.0
11 error Invalid package.json
12 error If you need help, you may report this error at:
12 error     https://github.com/npm/npm/issues
13 verbose exit [ 1, true ]

**Comment by zkat** [comment]
It looks like you tried to run `npm info` with no arguments in your user directory. That will try to read a (non-existent, probably) `package.json` and give you this error.

See the documentation for `npm info` by typing `npm help info`.

If you want information on a specific package, you can do `npm info <packagename>`, and you should be able to use that command from anywhere.
