### ISSUE TITLE
npm install react-native fail 

### ISSUE THREAD

**Issue by highway33** [npm/npm#12055]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/5.6.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'react-native' ]
2 info using npm@3.6.0
3 info using node@v5.6.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData react-native
8 silly fetchNamedPackageData react-native
9 silly mapToRegistry name react-native
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/react-native
13 verbose request uri https://registry.npmjs.org/react-native
14 verbose request no auth needed
15 info attempt registry request try #1 at 08:42:16
16 verbose request id 78a2a5ea526088f6
17 verbose etag "12K2NZMGP8K6O7NJZMBM10RG6"
18 http request GET https://registry.npmjs.org/react-native
19 info retry will retry, error on last attempt: Error: socket hang up
20 info attempt registry request try #2 at 08:43:28
21 verbose etag "12K2NZMGP8K6O7NJZMBM10RG6"
22 http request GET https://registry.npmjs.org/react-native
23 info retry will retry, error on last attempt: Error: socket hang up
24 info attempt registry request try #3 at 08:45:30
25 verbose etag "12K2NZMGP8K6O7NJZMBM10RG6"
26 http request GET https://registry.npmjs.org/react-native
27 silly get cb [ 304, undefined ]
28 verbose etag https://registry.npmjs.org/react-native from cache
29 verbose get saving react-native to /Users/haidong/.npm/registry.npmjs.org/react-native/.cache.json
30 verbose correctMkdir /Users/haidong/.npm correctMkdir not in flight; initializing
31 silly install normalizeTree
32 silly loadCurrentTree Finishing
33 silly loadIdealTree Starting
34 silly install loadIdealTree
35 silly cloneCurrentTree Starting
36 silly install cloneCurrentTreeToIdealTree
37 silly cloneCurrentTree Finishing
38 silly loadShrinkwrap Starting
39 silly install loadShrinkwrap
40 silly loadShrinkwrap Finishing
41 silly loadAllDepsIntoIdealTree Starting
42 silly install loadAllDepsIntoIdealTree
43 silly rollbackFailedOptional Starting
44 silly rollbackFailedOptional Finishing
45 silly runTopLevelLifecycles Starting
46 silly runTopLevelLifecycles Finishing
47 silly install printInstalled
48 verbose stack Error: Refusing to install react-native as a dependency of itself
48 verbose stack     at checkSelf (/usr/local/lib/node_modules/npm/lib/install/validate-args.js:53:14)
48 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
48 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
48 verbose stack     at chain (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
48 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/validate-args.js:16:5
48 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
48 verbose stack     at Array.forEach (native)
48 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
48 verbose stack     at Array.forEach (native)
48 verbose stack     at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
49 verbose cwd /Users/haidong/Documents/react-native
50 error Darwin 14.5.0
51 error argv "/usr/local/Cellar/node/5.6.0/bin/node" "/usr/local/bin/npm" "install" "react-native"
52 error node v5.6.0
53 error npm  v3.6.0
54 error code ENOSELF
55 error Refusing to install react-native as a dependency of itself
56 error If you need help, you may report this error at:
56 error     <https://github.com/npm/npm/issues>
57 verbose exit [ 1, true ]

**Comment by zkat** [comment]
Hi! You can't install modules as dependencies of themselves, so if you did a `git clone` on the `react-native` repo, you'll see this error message. If you want to use `react-native` as a dependency, create a new project (not called `react-native`), and then do this. Otherwise, if you want to _develop_ on a cloned copy of the project, cd into the git clone, and run a plain `npm install` with no other arguments -- that will install devDependencies for you.

**Comment by highway33** [comment]
thank you

**Comment by zkat** [comment]
No problem! Feel free to ping this issue again if you're still having problems. I'll close this for now. :)

**Comment by Jiangjinjin1** [comment]
$ react-native init AwareProject
This will walk you through creating a new React Native project in D:\Jiangjinjin                                                                                                                Project\app_project\AwareProject
Installing react-native package from npm...

> spawn-sync@1.0.15 postinstall D:\JiangjinjinProject\app_project\AwareProject\n                                                                                                                ode_modules\react-native\node_modules\yeoman-generator\node_modules\cross-spawn\                                                                                                                node_modules\spawn-sync
> node postinstall


> spawn-sync@1.0.15 postinstall D:\JiangjinjinProject\app_project\AwareProject\n                                                                                                                ode_modules\react-native\node_modules\yeoman-environment\node_modules\inquirer\n                                                                                                                ode_modules\external-editor\node_modules\spawn-sync
> node postinstall


npm WARN peerDependencies The peer dependency react@~15.2.0 included from react-                                                                                                                native will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerD                                                                                                                ependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it                                                                                                                 explicitly.
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a bu                                                                                                                ild toolchain, use it instead!
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher                                                                                                                 to avoid a RegExp DoS issue
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\                                                                                                                node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "--save-exact" "react-nat                                                                                                                ive"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! path C:\Users\jiangjinjin\AppData\Roaming\npm-cache\object-assign\4.1.0                                                                                                                \package\package.json.082d9dd994dc853e5460b92c83c59af3
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\jiangjinjin\App                                                                                                                Data\Roaming\npm-cache\object-assign\4.1.0\package\package.json.082d9dd994dc853e                                                                                                                5460b92c83c59af3' -> 'C:\Users\jiangjinjin\AppData\Roaming\npm-cache\object-assi                                                                                                                gn\4.1.0\package\package.json'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM: operation not permitted, rename 'C:\Users\jiangjinjin                                                                                                                \AppData\Roaming\npm-cache\object-assign\4.1.0\package\package.json.082d9dd994dc                                                                                                                853e5460b92c83c59af3' -> 'C:\Users\jiangjinjin\AppData\Roaming\npm-cache\object-                                                                                                                assign\4.1.0\package\package.json']
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'rename',
npm ERR!   path: 'C:\\Users\\jiangjinjin\\AppData\\Roaming\\npm-cache\\object-as                                                                                                                sign\\4.1.0\\package\\package.json.082d9dd994dc853e5460b92c83c59af3',
npm ERR!   dest: 'C:\\Users\\jiangjinjin\\AppData\\Roaming\\npm-cache\\object-as                                                                                                                sign\\4.1.0\\package\\package.json',
npm ERR!   parent: 'figures' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\JiangjinjinProject\app_project\AwareProject\npm-debug.log

`npm install --save --save-exact react-native` failed

请问下，这个问题怎么解决
