### ISSUE TITLE
npm update doesn't update locally-installed peerDependencies

### ISSUE THREAD

**Issue by doug-wade** [npm/npm#12066]
When locally linking or installing a development copy of a package that declares peerDependencies with npm 2, the peerDependency is automatically helpfully installed to develop against.  However, when the version changes on master and you pull locally, you'll get ERR! Peer Invalid for the incorrect version that is not fixed by an `npm update`, and errors on `npm install`.  This is resolveable with an `npm install peerDependency@requiredVersion`, but I believe that `npm update` in npm 2 should also solve this situation (since it solves the equivalent problem when in an installed state).

**Comment by zkat** [comment]
Hi @doug-wade!

So `npm@2` is in LTS mode right now, which means it's very very unlikely we would make any changes to it other than patches or registry-related additions. `npm@3` also brought with it `peerDep`-related changes that address this sort of stuff.

As such, I'm going to mark this as a feature request and close it. Feel free to comment further if you disagree and we can talk more about what can be done, but I think this is the best decision for something like this -- Upgrading might be what you want, here.
