### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by river9100** [npm/npm#12064]
ERR! TypeError: Object.keys called on non-object
npm ERR!     at Function.keys (native)
npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:708:24)
npm ERR!     at /usr/share/npm/lib/cache.js:638:10
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.2.0-27-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/andy/jitsi-meet
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type called_on_non_object
npm http 304 https://registry.npmjs.org/async/0.9.0

**Comment by KenanY** [comment]
@river9100 `npm@1.3` is no longer supported. Please try updating.

**Comment by raedlime** [comment]
do this `npm -g install npm` and your fine ;)

**Comment by river9100** [comment]
thanks very much, I'll try again.

**Comment by KenanY** [comment]
@river9100 Are you still seeing this issue after updating `npm`?

**Comment by dmitrif** [comment]
Still seeing this issue with a private mirror.
Please see log below:
```
23757 http request GET http://nexus.kjdev.ca/content/groups/npmall/core-js
23758 verbose request uri http://nexus.kjdev.ca/content/groups/npmall/regenerator-runtime
23759 verbose request no auth needed
23760 info attempt registry request try #1 at 2:29:55 PM
23761 verbose lastModified Tue, 14 Jun 2016 18:16:52 GMT
23762 http request GET http://nexus.kjdev.ca/content/groups/npmall/regenerator-runtime
23763 http 200 http://nexus.kjdev.ca/content/groups/npmall/regenerator-runtime
23764 verbose headers { date: 'Tue, 14 Jun 2016 18:29:55 GMT',
23764 verbose headers   server: 'Nexus/2.11.2-06',
23764 verbose headers   'x-frame-options': 'SAMEORIGIN',
23764 verbose headers   'x-content-type-options': 'nosniff',
23764 verbose headers   'accept-ranges': 'bytes',
23764 verbose headers   'content-type': 'application/json',
23764 verbose headers   'last-modified': 'Tue, 14 Jun 2016 18:29:55 GMT',
23764 verbose headers   'content-length': '77' }
23765 silly get cb [ 200,
23765 silly get   { date: 'Tue, 14 Jun 2016 18:29:55 GMT',
23765 silly get     server: 'Nexus/2.11.2-06',
23765 silly get     'x-frame-options': 'SAMEORIGIN',
23765 silly get     'x-content-type-options': 'nosniff',
23765 silly get     'accept-ranges': 'bytes',
23765 silly get     'content-type': 'application/json',
23765 silly get     'last-modified': 'Tue, 14 Jun 2016 18:29:55 GMT',
23765 silly get     'content-length': '77' } ]
23766 verbose get saving regenerator-runtime to /Users/dfarkov/.npm/nexus.kjdev.ca/content/groups/npmall/regenerator-runtime/.cache.json
23767 verbose correctMkdir /Users/dfarkov/.npm correctMkdir not in flight; initializing
23768 verbose stack TypeError: Cannot convert undefined or null to object
23768 verbose stack     at Function.keys (native)
23768 verbose stack     at pickVersionFromRegistryDocument (/opt/boxen/nodenv/versions/v4.2.6/lib/node_modules/npm/lib/fetch-package-metadata.js:125:29)
23768 verbose stack     at /opt/boxen/nodenv/versions/v4.2.6/lib/node_modules/npm/node_modules/iferr/index.js:13:50
23768 verbose stack     at /opt/boxen/nodenv/versions/v4.2.6/lib/node_modules/npm/lib/utils/pulse-till-done.js:19:8
23768 verbose stack     at saved (/opt/boxen/nodenv/versions/v4.2.6/lib/node_modules/npm/lib/cache/caching-client.js:174:7)
23768 verbose stack     at /opt/boxen/nodenv/versions/v4.2.6/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:210:7
23768 verbose stack     at FSReqWrap.oncomplete (fs.js:82:15)```

**Comment by KenanY** [comment]
@dmitrif Looks unrelated to this issue. Does this also occur with the default npm registry? What version of `npm` do you have?

**Comment by dmitrif** [comment]
@KenanY You are right, it seems nexus is caching `{ time: { modified: '2014-07-04T06:36:41.889Z' }` instead of the package.json. I'll try to clear the cache first, but if that fails I'll try to set up a repo to allow for reproduction of the bug without the private registry. 

Cheers & Thanks!

**Comment by KenanY** [comment]
Closing as abandoned. If you are still facing this issue @river9100, feel free to let me know and we can reopen.

**Comment by webia1** [comment]
Hi @dmitrif how did you delete the cache at nexus?
