### ISSUE TITLE
npm install oracledb error

### ISSUE THREAD

**Issue by davides93** [npm/npm#12060]
after installed all previous requests:
-Python 2.7.11 -> path setted
-node,js update to latest version (with npm) -> path setted
-oracle instant client -> path setted

-Microsoft visual studio community edition (Free) 2015

but i've this error:
![image](https://cloud.githubusercontent.com/assets/7363222/14043327/6281c3e6-f283-11e5-9d7b-8691b8dca92b.png)

**Comment by zkat** [comment]
Hi! This error just means that you're trying to install a package as a dependency of itself, which npm does not support.

Most likely, what you want is to create a new project (_not_ called `oracledb`), and use `npm install -S oracledb` to set it up as a dependency.

See 'getting started' section over at https://docs.npmjs.com/ for further clarification, or feel free to ask specific questions here.
