### ISSUE TITLE
npm install --save-inline (Inlined Dependencies)

### ISSUE THREAD

**Issue by davidmarkclements** [npm/npm#12068]
Advantages:

* opt in
* retain dependent / dependencies stats
* faster download/install times
* ...peace of mind 

Disadvantages

* larger publish payloads
* duplicated code (could affect whether v8 inlines a function, could also affect browser bundling, disk space less of a deal)

command:
```sh
npm install --save-inline some-module
```

package.json
```
{
  "name": "my-awesome-module",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "test": "tap test"
  },
  "author": "David Mark Clements",
  "license": "ISC",
  "inlinedDependencies": {
    "some-module": "^1.2.3"
  }
}
```

consumer code:

```js
var some = require('some-module')

some({my: opts}) //etc.
```

when `npm publish` happens:

1) check for inlinedDependencies
2) check for require calls to inlined deps (https://www.npmjs.com/package/module-deps could be a good starting point)
3) inline the require calls, save output to a temp file:

```js
var some = (function () { var m = {exports: {}}; (function (exports, require, module, __filename, __dirname) { /*mod code*/})(m.exports, require, m, 'index.js', 'blah/blah/node_modules/some-module'); return m.exports; })()

some({my: opts}) //etc.
````

4) during publish transparently supplant the entry point with the inlined alternatively

A transparent process has advantages, it removes the "build step" as far as developers are concerned, and means zero setup. 

For deployment, an `npm inline` that outputs inlined code to stdout would be useful as a production build step.

**Comment by davidmarkclements** [comment]
a variation could be to inline modules in the require cache, which would address the duplicate code issue

**Comment by othiym23** [comment]
How is this different from [`bundledDependencies`](https://docs.npmjs.com/files/package.json#bundleddependencies)? Put another way, what problem is this intended to solve?

**Comment by davidmarkclements** [comment]
well, it solves the same problem, and when I had the idea I wasn't considering `bundledDependencies`

However, where this approach does have some additional benefits, primarily around a workflow that supports a more conservative dependency strategy

If we decide our strategy for a project will be one of inlining modules we don't control, we'll just append -inline to our install commands, `npm i --save-inline mod` 

However, the bundling of `node_modules` folders is more practical, less work and already implemented, so maybe this should change to a suggestion for `npm install --save-bundled` along with an 'always-bundle' config setting

**Comment by othiym23** [comment]
I have [good news](https://docs.npmjs.com/misc/config#save-bundle) for you. `npm config set save-bundle true` will enable it by default, but I think you'd discover that in practice it's a pretty heavy hammer. However, is that good enough to consider this feature request fulfilled for you?

**Comment by davidmarkclements** [comment]
Yes thanks, although --save-bundle would be a nice addition

**Comment by othiym23** [comment]
Did you follow the link I sent you? `--save-bundle` has been part of npm for a pretty long time now.

**Comment by davidmarkclements** [comment]
Yep, not seeing --save-bundle in that doc but that's awesome, I did not know that, should have checked first - cheers
