### ISSUE TITLE
Invalid Version: 13.04.14

### ISSUE THREAD

**Issue by twhid** [npm/npm#12070]
Hi,

My org continues to use npm@2 but would very much like to upgrade to npm@3. However, there's a  nested dependency in one of our private packages that throws `Invalid Version: 13.04.14` when trying to install via npm@3 (tested with both 3.7.1 and 3.8.3).

My first questions is: what's invalid about that version? Looks like valid semver to me.

Or, am I misunderstanding and this error means the version couldn't be satisfied with published modules?

The stack trace is completely unhelpful on tracking down the offending dependency:

```
1244 verbose stack TypeError: Invalid Version: 13.04.14
1244 verbose stack     at new SemVer (/path/to/npm/node_modules/semver/semver.js:293:11)
1244 verbose stack     at compare (/path/to/npm/node_modules/semver/semver.js:566:10)
1244 verbose stack     at rcompare (/path/to/npm/node_modules/semver/semver.js:576:10)
1244 verbose stack     at Array.sort (native)
1244 verbose stack     at pickVersionFromRegistryDocument (/path/to/npm/lib/fetch-package-metadata.js:121:48)
1244 verbose stack     at /path/to/npm/node_modules/iferr/index.js:13:50
1244 verbose stack     at /path/to/npm/lib/utils/pulse-till-done.js:19:8
1244 verbose stack     at saved (/path/to/npm/lib/cache/caching-client.js:168:7)
1244 verbose stack     at /path/to/npm/node_modules/graceful-fs/polyfills.js:210:7
1244 verbose stack     at FSReqWrap.oncomplete (fs.js:82:15)
```

Which leads to my second question: any tips on tracking down the offending package?

Thanks,

**Comment by KenanY** [comment]
http://semver.org/spec/v2.0.0.html

> A normal version number MUST take the form X.Y.Z where X, Y, and Z are non-negative integers, and MUST NOT contain leading zeroes.

There's a leading zero in the Y (the "minor") of `13.04.14`.

**Comment by twhid** [comment]
Thanks @KenanY ! My colleague just pointed that out to me as well.

Nevertheless, npm@2 installs the package and all its dependencies just fine, which is how this sort of error can continue to propagate.

**Comment by twhid** [comment]
Really scratching my head. There's no help from the error stack in tracking down the offending package. Yet, when I install via npm@2 there is no package that is installed with that version (according to `npm install` output and `npm ls`).

**Comment by zkat** [comment]
Could you look in your `npm-debug.log`? That likely has clues as to which module caused this.

That said, we've got a number of issues related to reporting errors a little better, so I'm gonna tag this as a ux feature request so we can hopefully make it nicer to figure out who's at fault when these errors are reported.

**Comment by twhid** [comment]
Hi @zkat 

Thanks for the reply. 

There doesn't seem to be any clues in the debug log. It's definitely in the dependency graph of a private module of ours, which is -- unfortunately -- huge. I've searched for the string "13.04.14" in the debug log, in the `npm install` output of a successful install and in the `npm ls` of a successful install -- no trace of it.

Does the semver validation happen to *all* versions of a package? Or only to the version one is attempting to install ?

Best,

**Comment by MGMsystems** [comment]
Hi, 
@zkat ,

We seem to have a similar issue. On a lot of different dependencies.
one example:
I try to install `grunt-contrib-clean` with the latest version but it fails.

Error:
`verbose stack TypeError: Invalid Version: 0.4.0rc5`
`508 verbose stack     at new SemVer (c:\Program Files\nodejs\node_modules\npm\node_modules\semver\semver.js:293:11)`
`508 verbose stack     at compare (c:\Program Files\nodejs\node_modules\npm\node_modules\semver\semver.js:566:10)`
`508 verbose stack     at rcompare (c:\Program Files\nodejs\node_modules\npm\node_modules\semver\semver.js:576:10)`
`508 verbose stack     at Array.sort (native)`
`508 verbose stack     at pickVersionFromRegistryDocument (c:\Program Files\nodejs\node_modules\npm\lib\fetch-package-metadata.js:121:48)`
`508 verbose stack     at c:\Program Files\nodejs\node_modules\npm\node_modules\iferr\index.js:13:50`
`508 verbose stack     at c:\Program Files\nodejs\node_modules\npm\lib\utils\pulse-till-done.js:19:8`
`508 verbose stack     at saved (c:\Program Files\nodejs\node_modules\npm\lib\cache\caching-client.js:168:7)`
`508 verbose stack     at c:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:210:7`
`508 verbose stack     at FSReqWrap.oncomplete (fs.js:82:15)`


If I look in the registry it seems that there are indeed wrong semver versions. [http://registry.npmjs.org/grunt-contrib-clean](http://registry.npmjs.org/grunt-contrib-clean)
Seems like semver crashes if he tries to compare an invalid version.

This issue only appeared after I upgraded to the latest version of npm@3.
Before we were using npm@2 and all was fine.
