### ISSUE TITLE
-bash: react-native: command not found ,i do that brew intall node, npm install -g react-native-cli 

### ISSUE THREAD

**Issue by highway33** [npm/npm#12077]
i do npm install -g react-native-cli 
the result
/Users/haidong/.npm-packages/bin/react-native -> /Users/haidong/.npm-packages/lib/node_modules/react-native-cli/index.js
/Users/haidong/.npm-packages/lib
└── react-native-cli@0.2.0 

-bash: /usr/local/Cellar/nvm/0.30.1/nvm.sh: No such file or directory

**Comment by folivi** [comment]
+1
