### ISSUE TITLE
Installing scoped packages into node_modules instead of scoped folder

### ISSUE THREAD

**Issue by sasidhar** [npm/npm#12074]
This is a question.

We have some private NPM packages using npmjs' private repository. 

Assume
- scope name : `@scope`
- private package name as : `private-package`

When we install this NPM package using 
```npm install @scope/private-package``` 

It is installed to : ```./node_modules/@scope/private-package```

Is there any option to install these packages normally `.node_modules/private-package` instead of having them loaded into a separate `@scoped` folder?

Of course, our private-packages doesn't conflict with any of the existing package names.

This will allow us to import these modules with the package name instead of adding one more not-so-common `@scope` folder.

FYI, we are using Angular 2 + TypeScript along with VSCode.

**Comment by zkat** [comment]
Nope, that's how scoped packages work. You can require them with `require('@scope/private-package')`. It's recommended that you avoid pathing straight into `node_modules/` whenever possible, in general :)

This is a pretty core thing about how npm and scopes packages work, so it's very unlikely to change.

**Comment by sasidhar** [comment]
@zkat Got it!

The issue that we are facing we have many private packages and they have many components which are re-used in different TypeScript files. Adding `@scope` seems really a pain.

May be there should be an option in TypeScript. I am looking for that. Once I get any update, I will update it here and close this ticket.

**Comment by sasidhar** [comment]
Related : https://github.com/Microsoft/vscode/issues/4687

**Comment by sasidhar** [comment]
Issue Moved to TypeScript @ https://github.com/Microsoft/TypeScript/issues/7695
