### ISSUE TITLE
Trying to run 'yo mobileangularui' - get verbose stack Error: UNKNOWN, symlink '../atob/bin/atob.js'

### ISSUE THREAD

**Issue by kramerdog** [npm/npm#12078]
Ran `yo mobileangularui `

from a bash prompt in Ubuntu 14.04 (with and without sudo) and each time get the error below (also see attached logifle)

```
910 verbose stack Error: UNKNOWN, symlink '../atob/bin/atob.js'
911 verbose cwd /var/squirrl/ui
912 error Linux 3.13.0-40-generic
913 error argv "node" "/usr/local/bin/npm" "install"
914 error node v0.10.25
915 error npm  v3.8.3
916 error path ../atob/bin/atob.js
917 error code UNKNOWN
918 error errno -1
919 error UNKNOWN, symlink '../atob/bin/atob.js'
```

Would appreciate any pointers to the problem.

[npm-debug.txt](https://github.com/npm/npm/files/190361/npm-debug.txt)

**Comment by othiym23** [comment]
Are you running within a container environment, or otherwise running the install on a volume that doesn't support symbolic links? The `UNKNOWN` is strange (and coming out of Node, not npm, for what that's worth), but it's not unusual for npm to fail when trying to install on filesystems that don't allow links.

**Comment by kramerdog** [comment]
Now you mention symbolic links, when I Google that I get some ideas that there are permissions issues with creating a symbolic link within a VM container where the link is contained within a folder shared to a Windows file system.

Thanks for the pointer - I'll investigate further and report back.

**Comment by kramerdog** [comment]
Looks like @othiym23 was right.

This discussion - http://www.ahtik.com/blog/fixing-your-virtualbox-shared-folder-symlink-error/ - and specifically the solution of running VirtualBox with "run as administrator" fixed the problem. Thanks.
