### ISSUE TITLE
Missing Write Access in Windows

### ISSUE THREAD

**Issue by rakeen** [npm/npm#12087]
I tried `npm cache clean` and manually deleting the npm_cache directory also.
Tried executing these commands using `CMD` as an administrator.
Tried executing these commands from `powershell` as an administrator.  
nothing worked.

I'm using Windows 7 Ultimate (32-bit)  6.1.7600 Build 7600  

[npm-debug.log](http://pastebin.com/f1DJsisu)

**Comment by chrish619** [comment]
Have you tried some of the stuff at: https://docs.npmjs.com/getting-started/fixing-npm-permissions ?
I know it's pretty much linux / Mac based.

Another option is to try and (re)install nodejs via chocolatey (https://chocolatey.org/), e.g. "choco install nodejs"
Have done this very recently, and don't get any issues here.

Also, what version of Windows are you on? (might help for further debugging)

**Comment by rakeen** [comment]
I'm sorry I can't seem to reproduce the problem :disappointed: should have logged more data.  
I ended up using `nvm` to switch between versions.(don't remember why I did that, both 4.4.1 & 5.9.1 seem to work now.  
I'm using Windows 7. (updated the post)
