### ISSUE TITLE
npm outdated shows newer "current" version is older than older "latest" version

### ISSUE THREAD

**Issue by mattly** [npm/npm#12089]
```
$ npm -g outdated
Package   Current  Wanted  Latest  Location
npm         3.8.5   3.8.5   3.8.3
```
I just updated. Your guess is as good as mine.

**Comment by othiym23** [comment]
This is how [npm outdated](https://docs.npmjs.com/cli/outdated) is designed to work, and is a byproduct of the [npm CLI release process](https://github.com/npm/npm/wiki/Release-Process#the-npm-release-train). As this behavior is intended (if mildly confusing if you don't know what's going on), I'm going to close this issue. Thanks for your time!

**Comment by mattly** [comment]
I'm taking this to mean that if I want to "upgrade" something to match whatever "outdated" thinks is the "latest", I should use "install" instead of "upgrade", correct?
