### ISSUE TITLE
package.json sub-dependency version

### ISSUE THREAD

**Issue by seanmcilvenna** [npm/npm#12088]
hello. I have a question about package.json structure. a dependency I am using references another dependency with ">0.1.0", but this is causing it to download the latest version of that dependency, which causes a bug. Is it possible to tell npm to override the dependency's version in my package.json so that it doesn't download the latest version of the sub-dependency?

**Comment by benzen** [comment]
for this kind of finer grained controled you should use shrinkwrap.
See  https://docs.npmjs.com/cli/shrinkwrap
