### ISSUE TITLE
npm run-script doesn't run scripts (automatically exits with 0)

### ISSUE THREAD

**Issue by bfred-it** [npm/npm#12082]
Until a few hours ago, running `npm run build` would produce an output similar to this:

<img src="https://raw.githubusercontent.com/dsernst/npm-run-help/master/screenshot.png">

Now it just exits without any output unless I use `--verbose`, which still doesn't fix it.

<img width="500" alt="npm info it worked if it ends with ok
npm verb cli [ '/usr/local/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'run',
npm verb cli   'build',
npm verb cli   '--verbose' ]
npm info using npm@3.7.3
npm info using node@v5.8.0
npm verb run-script [ 'prebuild', 'build', 'postbuild' ]
npm info lifecycle my-module@1.0.0~prebuild: my-module@1.0.0
npm info lifecycle my-module@1.0.0~build: my-module@1.0.0
npm info lifecycle my-module@1.0.0~postbuild: my-module@1.0.0
npm verb exit [ 0, true ]
npm info ok" src="https://cloud.githubusercontent.com/assets/1402241/14060307/5d82592e-f31d-11e5-8c4c-ab08136011a8.png">

`package.json` is read correctly because if I remove the `build` script it tells me it's missing.

```json
{
  "name": "my-module",
  "version": "1.0.0",
  "description": "my-module",
  "scripts": {
    "build": "echo 1"
  }
}
```

It doesn't matter what version of npm and node I try, even 0.10 and 2.x.x. It always behaves the same. Currently on:

```
$ npm -v
3.7.3
$ node -v
v5.8.0
```

I tried

* rebooting
* cleaning cache
* uninstalling npm completely and reinstalling it but nothing changed. 

## Edit 1

Currently debugging this with:

```sh
node-inspector &
node --debug-brk /usr/local/bin/npm run build
```

I also found the log level "silly" which gives some important information:

<img width="728" alt="screen shot 2016-03-26 at 23 38 10" src="https://cloud.githubusercontent.com/assets/1402241/14061159/dfaa6e94-f3ab-11e5-90ce-93c4235526e4.png">

Will keep updating

**Comment by bfred-it** [comment]
Okay. This is resolved. I had followed the [recent suggestion to `ignore-scripts`](http://blog.npmjs.org/post/141702881055/package-install-scripts-vulnerability) globally:

```sh
npm config set ignore-scripts true
```

... which is terrible, considering that it causes scripts to be ignored silently. This restored the correct behavior:


```sh
npm config set ignore-scripts false
```

**Comment by Trevoke** [comment]
Whoa. I'm so glad you went through this for me. That was completely unexpected behavior, based on their blod entry.

**Comment by szarouski** [comment]
I agree with you that it is quite unfriendly, it would be much better to be able to white list packages that should be able to run scripts.
