### ISSUE TITLE
No progress bar on Windows 10

### ISSUE THREAD

**Issue by kpodemski** [npm/npm#12098]
Hello guys,

I've recently moved from Windows 8.1 to Windows 10 and after setting up entire environment I noticed that there is no progress bar while installing packages, nor on Babun.io nor on Git-Bash, I see in configuration that `progress` is set to `true`, any clues how to get progress bar back? It is really helpful to see if something going on etc...

**Comment by bruceCzK** [comment]
Same here after I upgrade git to 2.8.2

**Comment by kpodemski** [comment]
Good to know that I'm not alone with this ^^

**Comment by nolanlawson** [comment]
This is not an npm issue; any library using `progress-bar` will run into this. E.g. my `slow-deps` package has this problem.

Confirmed in Git Bash as well; seems to be a mintty issue. I'm using mintty 2.0.3. BTW you can fix this by switching to Bash on Ubuntu on Windows (aka Linux Subsystem).

**Comment by nolanlawson** [comment]
Related: https://github.com/mintty/mintty/issues/56 https://github.com/babun/babun/issues/403

**Comment by mintty** [comment]
Just got aware of this issue, and I even have a suspicion about its cause.
However, since I don't have access to npm, I cannot test it.
Please provide a screen log (not screenshot) of the spinner, so I can analyse it.
