### ISSUE TITLE
npm ERR! connect EHOSTUNREACH 23.235.43.162:443

### ISSUE THREAD

**Issue by wouterds** [npm/npm#12097]
Hi,

I'm trying to install a package on my Raspberry Pi but I keep getting this error.

![Screenshot](https://up.kibakoapp.com/8UzrVrsGSF\!#d)

This the full output (contents of npm-debug.log). Anyone else experiencing issues?

	➜  ~ cat npm-debug.log 
	0 info it worked if it ends with ok
	1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'install', 'rpio' ]
	2 info using npm@3.7.3
	3 info using node@v5.9.1
	4 verbose config Skipping project config: /home/pi/.npmrc. (matches userconfig)
	5 silly loadCurrentTree Starting
	6 silly install loadCurrentTree
	7 silly install readLocalPackageData
	8 silly fetchPackageMetaData rpio
	9 silly fetchNamedPackageData rpio
	10 silly mapToRegistry name rpio
	11 silly mapToRegistry using default registry
	12 silly mapToRegistry registry https://registry.npmjs.org/
	13 silly mapToRegistry uri https://registry.npmjs.org/rpio
	14 verbose request uri https://registry.npmjs.org/rpio
	15 verbose request no auth needed
	16 info attempt registry request try #1 at 8:53:50 PM
	17 verbose request id df268501b4d9746b
	18 http request GET https://registry.npmjs.org/rpio
	19 info retry will retry, error on last attempt: Error: connect EHOSTUNREACH 23.235.43.162:443
	20 info attempt registry request try #2 at 8:54:12 PM
	21 http request GET https://registry.npmjs.org/rpio
	22 info retry will retry, error on last attempt: Error: connect EHOSTUNREACH 23.235.43.162:443
	23 info attempt registry request try #3 at 8:55:23 PM
	24 http request GET https://registry.npmjs.org/rpio
	25 silly fetchPackageMetaData Error: connect EHOSTUNREACH 23.235.43.162:443
	25 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:890:11)
	25 silly fetchPackageMetaData     at exports._exceptionWithHostPort (util.js:913:20)
	25 silly fetchPackageMetaData     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1061:14)
	25 silly fetchPackageMetaData  error for rpio { [Error: connect EHOSTUNREACH 23.235.43.162:443]
	25 silly fetchPackageMetaData   code: 'EHOSTUNREACH',
	25 silly fetchPackageMetaData   errno: 'EHOSTUNREACH',
	25 silly fetchPackageMetaData   syscall: 'connect',
	25 silly fetchPackageMetaData   address: '23.235.43.162',
	25 silly fetchPackageMetaData   port: 443 }
	26 silly rollbackFailedOptional Starting
	27 silly rollbackFailedOptional Finishing
	28 silly runTopLevelLifecycles Starting
	29 silly runTopLevelLifecycles Finishing
	30 silly install printInstalled
	31 verbose stack Error: connect EHOSTUNREACH 23.235.43.162:443
	31 verbose stack     at Object.exports._errnoException (util.js:890:11)
	31 verbose stack     at exports._exceptionWithHostPort (util.js:913:20)
	31 verbose stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1061:14)
	32 verbose cwd /home/pi
	33 error Linux 4.1.19+
	34 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "rpio"
	35 error node v5.9.1
	36 error npm  v3.7.3
	37 error code EHOSTUNREACH
	38 error errno EHOSTUNREACH
	39 error syscall connect
	40 error connect EHOSTUNREACH 23.235.43.162:443
	41 error If you need help, you may report this error at:
	41 error     <https://github.com/npm/npm/issues>
	42 verbose exit [ 1, true ]

**Comment by wouterds** [comment]
Faulty network configuration, my bad.

**Comment by CaptainYouz** [comment]
Hi,

did you find a solution for that ? it will be helpful if you share :)
i have exactly the same problem, but i don't understand why.

**Comment by wikijm** [comment]
@wouterds Same case for me, stuck like you @CaptainYouz
