### ISSUE TITLE
No compatible version found: tower-attr@~0.1.0 (available: 0.1.0-pre)

### ISSUE THREAD

**Issue by ltcmdr927** [npm/npm#12091]
I'm getting to be failed to install tower with npm.
tower-attr@~0.1.0 is required, but valid install target is @~0.1.0-pre

```
bash-3.2$ npm install -g tower
npm ERR! Darwin 15.4.0
npm ERR! argv "/Users/ltcmdr927/.nvm/versions/node/v5.9.1/bin/node" "/Users/ltcmdr927/.nvm/versions/node/v5.9.1/bin/npm" "install" "-g" "tower"
npm ERR! node v5.9.1
npm ERR! npm  v3.7.3

npm ERR! No compatible version found: tower-attr@~0.1.0
npm ERR! Valid install targets:
npm ERR! 0.1.0-pre
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ltcmdr927/Workspaces/sandbox/npm-debug.log
```

My environment is:

```
bash-3.2$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.11.4
BuildVersion:   15E65
```

**Comment by mathiswan** [comment]
Hi, I am facing the same issue, is there any solution to fix it or work around? thx

**Comment by KenanY** [comment]
Probably just don't use `tower`. It's been abandoned for almost 3 years now. The alternative solution would be to fork it and change the dependency to `tower-attr@0.1.0-pre`.

**Comment by KenanY** [comment]
Closing as abandoned.

**Comment by KenanY** [comment]
"Abandoned" is probably not what I should say. Rather, newer versions of `npm` no longer allow prerelease versions to be matched by a range, hence why this error is occurring in this case. The solution would not be a change to `npm` itself, but to `tower`. So, if anyone really wants to see this fix, I would take it up with the `tower` developers (who, you should note, abandoned the project a while ago).
