### ISSUE TITLE
node

### ISSUE THREAD

**Issue by anbu004** [npm/npm#12105]
npm ERR! Windows_NT 6.1.7600

**Comment by anbu004** [comment]
npm ERR! Windows_NT 6.1.7600

**Comment by KenanY** [comment]
Hi @anbu004! Is there a `npm-debug.log` file you can upload to gist.github.com and link here?

**Comment by KenanY** [comment]
@anbu004 Are you still having issues with `npm`? If so, can you provide the information I requested?

**Comment by othiym23** [comment]
Closing as abandoned. Open a new issue if you encounter this behavior again!
