### ISSUE TITLE
Error: Invalid name: "@oddnetworks/seneca-odd-entitlement"

### ISSUE THREAD

**Issue by balagcontus** [npm/npm#12109]
Hi Team,

I got this error 

Error: Invalid name: "@oddnetworks/seneca-odd-entitlement"

Please give solution.

**Comment by KenanY** [comment]
@balagcontus `npm --version`?

**Comment by zkat** [comment]
@balagcontus this is almost certainly due to you using a version of npm prior to `npm@2`. Please update npm (with `sudo npm i -g npm`), and try again.

**Comment by KenanY** [comment]
Closing as probably resolved in `npm@>=2`. Can reopen if this is not the case.
