### ISSUE TITLE
Refusing to install grunt-uncss as a dependency of itself

### ISSUE THREAD

**Issue by mediafish** [npm/npm#12103]
Hi, I get an error while installing: 

Refusing to install grunt-uncss as a dependency of itself attached the debug file... thanks for having a look at it. 

[npm-debug.txt](https://github.com/npm/npm/files/191581/npm-debug.txt)

**Comment by Shahjalal7311** [comment]
Hi i get same error while installing 
Refusing to install grunt-uncss as a dependency of itself 

how can solve it?

**Comment by legodude17** [comment]
Ensure that the `name` field of your `package.json` is not `grunt-uncss`, as `npm` will not install packages as dependencies of themselves.
