### ISSUE TITLE
Support for JQuery-UI version 1.11.2

### ISSUE THREAD

**Issue by aounhaider1** [npm/npm#12106]
We recently switched to npm from bower. Unfortunately, the current approved version of JQuery-UI for our project is 1.11.2 which is currently not supported by npm(versions [ '1.10.4', '1.10.5', '1.12.0-beta.1', '1.12.0-rc.1' ] are supported). Is it possible to get support for 1.11.2?
Attached you can find the npm debug file.
[npm-debug.txt](https://github.com/npm/npm/files/191891/npm-debug.txt)

**Comment by KenanY** [comment]
@aounhaider1 Ask the jquery-ui authors about publishing 1.11.2.

**Comment by scottgonzalez** [comment]
This has nothing to do with npm itself. @aounhaider1 please close this issue.

**Comment by zkat** [comment]
Hi @aounhaider1 -- as other pointed out, that version is not in the npm registry itself.

That said, all is not lost: You can install (and save) the jquery version you were using before by using git dependencies: `npm i -S "git://github.com/jquery/jquery-ui#1.11.2"` will download and install the same version you were using in bower for you, and save the git dependency in your `package.json`. Happy hacking!

**Comment by aounhaider1** [comment]
You are savior @zkat. :+1: I really appreciate the help rather than telling me it had nothing to do with npm. Thanks again! :)
