### ISSUE TITLE
error npm install –g jspm

### ISSUE THREAD

**Issue by MarceloLopes22** [npm/npm#12116]
```
$ npm install –g jspm
npm ERR! addLocal Could not install C:\Projetos\ASP.NET 5 Empty\src\ASP.NET 5 Empty\wwwroot\–g
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x8                                                                                                                6)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "–g" "jspm"
npm ERR! node v5.9.1
npm ERR! npm  v3.7.3

npm ERR! The header content contains invalid characters
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

**Comment by rempatterson** [comment]
Please take me off this list.

On 03/28/2016 11:08 PM, MarceloLopes22 wrote:
>
> $ npm install –g jspm
> npm ERR! addLocal Could not install C:\Projetos\ASP.NET 5 
> Empty\src\ASP.NET 5 Em pty\wwwroot\–g
> npm ERR! Windows_NT 6.2.9200
> npm ERR! argv "C:\Program Files (x86)\nodejs\node.exe" "C:\Program 
> Files (x8 6)\nodejs\node_modules\npm\bin\npm-cli.js" "install" "–g" "jspm"
> npm ERR! node v5.9.1
> npm ERR! npm v3.7.3
>
> npm ERR! The header content contains invalid characters
> npm ERR!
> npm ERR! If you need help, you may report this error at:
> npm ERR! https://github.com/npm/npm/issues
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/npm/npm/issues/12116>
>


-- 
Bill Patterson

**Comment by MarceloLopes22** [comment]
I can not use the npm command to install the package manager jspm

**Comment by KenanY** [comment]
```
npm install –g jspm
```

Is this a hyphen-minus? Could you try using just a regular hyphen (`-`)?

**Comment by MarceloLopes22** [comment]
i use hyphen-minus but show a message this command is deprecated

**Comment by KenanY** [comment]
@MarceloLopes22 What about when you use a regular hyphen?

**Comment by KenanY** [comment]
@MarceloLopes22 ping?

**Comment by akras14** [comment]
This might be helpful: http://www.alexkras.com/typeerror-the-header-content-contains-invalid-characters/

**Comment by othiym23** [comment]
What @KenanY is saying is that the character you used when typing `-g` was actually not the hyphen npm (and most other command-line utilities was expecting):

```
// cut and pasted from issue text vs typed in by hand
> '–g' === '-g'
false
```

Switch to using the hyphen / minus key from your keyboard, and this problem should go away. As such, I'm closing this issue as resolved. Thanks for your time!
