### ISSUE TITLE
gulp-util error  ENOTEMPTY: directory not empty,

### ISSUE THREAD

**Issue by FiF0o** [npm/npm#12129]
Hi,
I am having issues when trying to install gulp-util plugin.

ENOTEMPTY: directory not empty,
/Users/user/Documents/01-Development/BoilerPlate/node_modules/gulp-util' -> '/Users/user/Documents/01-Development/BoilerPlate/node_modules/.gulp-util.DELETE'

However my node_modules directory does not contain such folder

I have attached the report
I tried npm cache clean before.

I am on OS X 10.11.3

Thanks a lot for the help,
[log.txt](https://github.com/npm/npm/files/193803/log.txt)

**Comment by FiF0o** [comment]
Issue is resolved, it seemed that the file was hidden.

**Comment by Dandice** [comment]
how did you solve it?

**Comment by ghadeerrahhal** [comment]
This is how I solved it:  sudo rm -rf node_modules/.gulp-util.DELETE
