### ISSUE TITLE
Refusing to install webpack as a dependency of itself

### ISSUE THREAD

**Issue by kkulg** [npm/npm#12121]
npm WARN extract-text-webpack-plugin@1.0.1 requires a peer of webpack@^1.9.11 but none was installed.

npm install webpack@^1.9.11 --save-dev

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "webpack@^1.9.11" "--save-dev"
npm ERR! node v5.9.1
npm ERR! npm  v3.7.3
npm ERR! code ENOSELF

npm ERR! Refusing to install webpack as a dependency of itself

**Comment by kkulg** [comment]
package.json里面name不能是webpack

**Comment by danieljwest** [comment]
I was running a class where this was happening. It only happened to one student. Oddly enough it was happening in a cloud9 docker instance which was configured exactly the same as every other student's instance. 
I had to manually edit the package.json file and then run npm install and that stopped the problem.
Not really sure what was happening.

**Comment by learntoswim** [comment]
This generally happens when the name of the working folder is the same name as a package that you're trying to install. 

```
$  pwd
/xxxx/webpack
$  npm i webpack --save
npm ERR! Darwin 15.4.0
npm ERR! argv "/xxxx/node" "/xxxx/npm" "i" "webpack" "--save"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! code ENOSELF

npm ERR! Refusing to install webpack as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /xxxx/webpack/npm-debug.log
```

**Comment by mhurwi** [comment]
Thanks for that note, fixed this issue for me.

**Comment by OmarMakled** [comment]
the same issue and solved just by changing package name

**Comment by qw4990** [comment]
The name in package.json can't be "webpack".

**Comment by jaumesalatantinya** [comment]
Thank you!!!!!

**Comment by cloudliving** [comment]
Thank you very much !!!

**Comment by duanlikang** [comment]
Thank you!

**Comment by eduardohenriquesousa** [comment]
Thank you!

**Comment by veereshradder** [comment]
Thank you..

**Comment by ntscshen** [comment]
Thank you!

**Comment by flashadicts** [comment]
thank you 👍

**Comment by LincolnLuiz** [comment]
thank yout @learntoswim

**Comment by Sessionking** [comment]
Thank you

**Comment by MooJhingjit** [comment]
Thank a lot

**Comment by ghost** [comment]
Thanks a milli

**Comment by eiamei** [comment]
Thanks!

**Comment by cScarlson** [comment]
Thank you!... But... I still had to go in manually and install the version explicitly after changing the directory name didn't work for me.
