### ISSUE TITLE
error npm install jade --save

### ISSUE THREAD

**Issue by mbrig-co** [npm/npm#12120]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'install', 'jade', '--save' ]
2 info using npm@3.8.3
3 info using node@v5.7.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData jade
8 silly fetchNamedPackageData jade
9 silly mapToRegistry name jade
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'jade',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   name: 'jade',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/jade
14 verbose request uri https://registry.npmjs.org/jade
15 verbose request no auth needed
16 info attempt registry request try #1 at 12:47:56
17 verbose request using bearer token for auth
18 verbose request id 32af92cf2d457d98
19 verbose etag "67E22BHWHBYY1JYWT5H8JLAJ"
20 http request GET https://registry.npmjs.org/jade
21 http 304 https://registry.npmjs.org/jade
22 verbose headers { 'cache-control': 'max-age=300',
22 verbose headers   'accept-ranges': 'bytes',
22 verbose headers   date: 'Tue, 29 Mar 2016 08:17:23 GMT',
22 verbose headers   via: '1.1 varnish',
22 verbose headers   connection: 'keep-alive',
22 verbose headers   'x-served-by': 'cache-ams4121-AMS',
22 verbose headers   'x-cache': 'MISS',
22 verbose headers   'x-cache-hits': '0',
22 verbose headers   'x-timer': 'S1459239443.527773,VS0,VE379' }
23 silly get cb [ 304,
23 silly get   { 'cache-control': 'max-age=300',
23 silly get     'accept-ranges': 'bytes',
23 silly get     date: 'Tue, 29 Mar 2016 08:17:23 GMT',
23 silly get     via: '1.1 varnish',
23 silly get     connection: 'keep-alive',
23 silly get     'x-served-by': 'cache-ams4121-AMS',
23 silly get     'x-cache': 'MISS',
23 silly get     'x-cache-hits': '0',
23 silly get     'x-timer': 'S1459239443.527773,VS0,VE379' } ]
24 verbose etag https://registry.npmjs.org/jade from cache
25 verbose get saving jade to /home/mnr/.npm/registry.npmjs.org/jade/.cache.json
26 verbose correctMkdir /home/mnr/.npm correctMkdir not in flight; initializing
27 silly install normalizeTree
28 silly loadCurrentTree Finishing
29 silly loadIdealTree Starting
30 silly install loadIdealTree
31 silly cloneCurrentTree Starting
32 silly install cloneCurrentTreeToIdealTree
33 silly cloneCurrentTree Finishing
34 silly loadShrinkwrap Starting
35 silly install loadShrinkwrap
36 silly loadShrinkwrap Finishing
37 silly loadAllDepsIntoIdealTree Starting
38 silly install loadAllDepsIntoIdealTree
39 silly rollbackFailedOptional Starting
40 silly rollbackFailedOptional Finishing
41 silly runTopLevelLifecycles Starting
42 silly runTopLevelLifecycles Finishing
43 silly install printInstalled
44 verbose stack Error: Refusing to install jade as a dependency of itself
44 verbose stack     at checkSelf (/usr/lib/node_modules/npm/lib/install/validate-args.js:53:14)
44 verbose stack     at Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
44 verbose stack     at LOOP (/usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
44 verbose stack     at chain (/usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
44 verbose stack     at /usr/lib/node_modules/npm/lib/install/validate-args.js:16:5
44 verbose stack     at /usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
44 verbose stack     at Array.forEach (native)
44 verbose stack     at /usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
44 verbose stack     at Array.forEach (native)
44 verbose stack     at asyncMap (/usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
45 verbose cwd /home/mnr/Desktop/MEAN/Stack/2. ExpressJS/2. ExpressJS Practices/ExpressJS tests/jade
46 error Linux 4.1.15-8-default
47 error argv "/usr/bin/node" "/usr/bin/npm" "install" "jade" "--save"
48 error node v5.7.0
49 error npm  v3.8.3
50 error code ENOSELF
51 error Refusing to install jade as a dependency of itself
52 error If you need help, you may report this error at:
52 error     <https://github.com/npm/npm/issues>
53 verbose exit [ 1, true ]

**Comment by amandeepmittal** [comment]
are you using a proxy server? If yes, please check your npm proxy configuration.

**Comment by KenanY** [comment]
@mbrig-co Try renaming your current directory to something other than `"jade"`.

**Comment by mbrig-co** [comment]
@KenanY Thanks it worked, so I am going to close it.
