### ISSUE TITLE
No compatible version found: get-object-path

### ISSUE THREAD

**Issue by YazanRawashdeh** [npm/npm#12122]
**## I have Node 4.4.1 and npm 3.8.3 
trying to simply install dependencies for a project but the output still gives me **

```
**Linux 3.13.0-24-generic
 argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
 node v4.4.1
 npm  v3.8.3
 No compatible version found: get-object-path@^0.0.2
 Valid install targets:
 0.0.3
 If you need help, you may report this error at:
     <https://github.com/npm/npm/issues>**
```

**Comment by KenanY** [comment]
@YazanRawashdeh I do not think that `npm` is behaving incorrectly here. `0.0.3` does not match the the semver range `^0.0.2`. How about changing that semver range to `^0.0.3`?
