### ISSUE TITLE
cannot spawn sh on Windows

### ISSUE THREAD

**Issue by zakijzhang** [npm/npm#12138]
```
npm ERR! Cloning into 'C:\Users\ZAKIJZ~1\AppData\Local\Temp\npm-6036-98be3362\git-cache-a7324bde\868daf12d720d0b5d4292f36bef00f3edf07c946'...
npm ERR! error: cannot spawn sh: No such file or directory
npm ERR! fatal: unable to fork
```

**Comment by nytamin** [comment]
I had the same issue, however I solved it with:
1. Make sure you've installed Git for Windows.
2. Make sure you have "C:\Program Files\Git\bin;" prepended to your PATH.

**Comment by janat08** [comment]
https://stackoverflow.com/questions/22619355/trouble-pushing-to-github-cannot-spawn-sh-no-such-file-or-directory

Doesn't work for me anyway, although I haven't reinstalled it.
