### ISSUE TITLE
feedback on new unpublish policy.

### ISSUE THREAD

**Issue by mattfysh** [npm/npm#12139]
Thank you for taking such quick and decisive action on the recent turmoil. A couple of concerns upon reading the proposed changes:

"Because all dependents are satisfied by 1.0.1, support agrees to grant Supreet’s request to delete 1.0.0."
... this does break shrinkwrap behaviors if the shrinkwrap were to refer to a direct version that becomes subject to deletion.

"Cool Kids Club sees this notice"
... no one is going to see this notice unless it requires interactive confirmation.

**Comment by othiym23** [comment]
@mattfysh I suggest you take this footage thataway ➡️ npm/policies#44. This isn't something that's pertinent to the CLI, so I'm going to close this issue. @ashleygwilliams and the rest of us will be happy to answer your questions over there! Thanks!

**Comment by mattfysh** [comment]
ah got it, thanks @othiym23 will follow along there :)
