### ISSUE TITLE
Ampersand deprecated -state@4.9.1 no compatible version found: get-object-path

### ISSUE THREAD

**Issue by janat08** [npm/npm#12148]
So provided I can't zip the log file properly, I declare that it wants me to have ampersand-state that isn't even in packages json which is still a problem after I've installed and then it gives me that no compatible crap.

**Comment by janat08** [comment]
Sitting in ampersand chat all day asking for hand out I realize that they actuall touch on that subject that being a dependency of -view at which point I uncover some nefarious travesty has occured.

**Comment by othiym23** [comment]
Assuming you're talking about the [late unpleasantness](http://blog.npmjs.org/post/141577284765/kik-left-pad-and-npm), which I believe involved [`get-object-path`](https://www.npmjs.com/package/get-object-path), it's been republished, preventing ampersand installs from breaksing. As such I'm going to close this issue. We have a [new policy around unpublishing]() to prevent something like this happening in the future, and will be working on updating our policy on name dispute resolution shortly. Thanks for your time!
