### ISSUE TITLE
part of the dependency tree is listed after every operation without explanation 

### ISSUE THREAD

**Issue by ben-page** [npm/npm#12145]
On one of my modules when I run an install or remove, npm lists three additional unrelated packages (in yellow) with no explanation. 

**npm install**

```
C:\my-module>npm i five
my-module@1.0.57 C:\my-module
+-- escodegen@1.8.0
+-- esmangle@1.0.1
+-- estraverse@4.2.0
`-- five@0.8.0  extraneous
```

**npm remove**

```
C:\my-module>npm remove five
- five@0.8.0 node_modules\five
my-module@1.0.57 C:\my-module
+-- escodegen@1.8.0
+-- esmangle@1.0.1
`-- estraverse@4.2.0
```

`escodegen`, `esmangle`, and `estraverse` have nothing to do with `five`. The text of these three lines is yellow, so assume this it's some sort of warning. I expected some sort of information (like extraneous), but there is nothing. Additionally, those modules are the dependencies in the package.json and they are not outdated.

So what do these lines mean? Why are only three of the dependencies being listed? Why isn't there a more clear explanation in the console?

**Comment by pedzed** [comment]
What is the output of `npm --version`?

**Comment by ben-page** [comment]
3.8.3

**Comment by ben-page** [comment]
I just discovered that simply running `npm i` causes the warnings:
```
C:\my-module>npm i
my-module@1.0.57 C:\my-module
+-- escodegen@1.8.0
+-- esmangle@1.0.1
`-- estraverse@4.2.0
```

**Comment by ben-page** [comment]
So I moved the `node_modules` directory and ran `npm i`. The warnings went away. So I compared the new `node_modules` directory to the original one. It seems `wordwrap`, a sub-module of `esmangle` was not installed. I have no idea why is wasn't installed by `npm`, but the warning seems to be that the modules (or their dependencies) are not properly installed.

To test this theory, I restored the original `node_modules` directory and ran `npm i estraverse escodegen esmangle`. This did not fix the problem. I had to first remove the modules (`npm remove estraverse escodegen esmangle`), then run `npm i estraverse escodegen esmangle`. The warnings went away.

I have no way of going back in time to reproduce what caused the modules to end up like this. And it likely happened on a old version of npm. So the issue I'm reporting is that, `npm` need more explicit warnings. `+--esmangle` doesn't mean anything to me and I could not find an explanation in the documentation.

**Comment by passcod** [comment]
`+--something` is not a warning, it's part of the display of the dependency tree of your package. The non-Unicode version. The Unicode version looks like this:

```
 ├── boolbase@1.0.0 
 ├── css-what@1.0.0 
 ├── domutils@1.4.3 
 └── nth-check@1.0.1
```

This is not a warning. Warnings are pretty explicit in npm, and start with the `npm WARN` prefix on every line. So what this output is saying is that your program lists three first-level dependencies and they are installed.

**Comment by pedzed** [comment]
> +--something is not a warning, it's part of the display of the dependency tree of your package. The non-Unicode version.


This is the correct answer. An example of how it looks like in Ubuntu 16.04 with npm 3.5.2:

![bash npm install](https://cloud.githubusercontent.com/assets/8146593/14225927/55fd4d50-f8d4-11e5-9091-537af697aa83.png)

**Comment by ben-page** [comment]
I understand that's is part of the dependency tree. But 3 (of the 10 or so) dependencies are displayed after every `install` and `remove` operation. So what is npm trying to tell me about those 3 dependencies?

**Comment by ben-page** [comment]
@passcod, not all NPM warnings begin with NPM WARN. Warning about dependencies are shown, by displaying the dependency followed by a message. For example, an extraneous module would look like this:
```
`-- five@0.8.0  extraneous
```

**Comment by ben-page** [comment]
**Example**
Try this in an empty directory:
```
C:\test>npm i five
C:\test
`-- five@0.8.0

npm WARN enoent ENOENT: no such file or directory, open 'C:\test\package.json'
npm WARN test No description
npm WARN test No repository field.
npm WARN test No README data
npm WARN test No license field.

C:\test>npm init -y
Wrote to C:\test\package.json:

C:\test>npm i cows --save

C:\test>npm i
test@1.0.0 C:\test
`-- five@0.8.0
```

See that how ``-- five@0.8.0` is listed after the `npm i` without any explanation.
This isn't just the dependency tree. First of all, `five` isn't even in the newly created `package.json`. Second, `cows` is a dependency and it isn't listed..

Let's try to fix `five`:
```
C:\test>npm i five --save

C:\test>npm i
test@1.0.0 C:\test
`-- five@0.8.0
```
Adding `five` to the `package.json` didn't fix the problem.

```
C:\test>npm remove five
- five@0.8.0 node_modules\five

C:\test>npm i five
test@1.0.0 C:\test
`-- five@0.8.0

C:\test>npm i
```
Removing the `five` and reinstalling it, fixes the problem.

**Explaination**
The problem seems to lie in the  `package.json` file in `node_modules\five\`. When `five` first installed, `_requiredBy` looks like this:
```JSON
  "_requiredBy": [
    "#USER",
    "/"
  ],
```
After being removed and reinstalled, it looks like this:
```JSON
  "_requiredBy": [
    "/"
  ],
```

**Conclusion**
If `#USER` is in the array `_requiredBy` in the `package.json` of a submodule, npm lists that dependency after every `install` or `remove` operation.

I see two problems:

1. It's still now clear to me why these dependencies are being listed. But if it's not an mistake, some message should follow the dependency (like how it's done for `extraneous` modules).
2. As far as I can tell, the only way to clear this message is to remove and reinstall the module. That's not at all intuitive. Simply `install`ing the module should fix this condition.

**Comment by passcod** [comment]
> not all NPM warnings begin with NPM WARN.

That's still not a warning, that's an info message. Semantics aside, I think I see what you mean. Hopefully an npm member can chime in once the weekend is over ;)
