### ISSUE TITLE
Deprecate package - Can't publish over error

### ISSUE THREAD

**Issue by cubicleWar** [npm/npm#12158]
I recently renamed my project and republished on npm. When I try to deprecate the old package I get an error.

I attempt deprecation by:

    npm deprecate neutriumjs.steam@"< 1.1.3" "WARNING: This project has been renamed neutriumjs.thermo.iapws97. Install using neutriumjs.thermo.iapws97 instead."

With the following results:

    npm ERR! node v4.3.1
    npm ERR! npm  v2.14.12
    npm ERR! code E403
    npm ERR! "You cannot publish over the previously published version 1.0.5." : neutriumjs.steam

**Comment by othiym23** [comment]
This sounds like an issue with how the registry is handling deprecation attempts, so you should take this issue over to the [newly-created registry issue tracker](https://github.com/npm/registry/issues) and let them know this is happening. I'm going to close this issue, as it's not a problem with the CLI, but feel free to reference it over there. Thanks for your time!
