### ISSUE TITLE
error npm :( 

### ISSUE THREAD

**Issue by MAJDA55** [npm/npm#12157]
how to use npm to execute the given base on Electron
![12899727_1662997647302307_1689010173_n](https://cloud.githubusercontent.com/assets/17464372/14173535/b3370e08-f73e-11e5-8e6e-2775bc14d6a7.png)

**Comment by pedzed** [comment]
This does not look like an npm problem. You seem to want to make an issue at Electron.

If you have a question, please give more information.

**Comment by othiym23** [comment]
I agree with @pedzed, and am going to close this issue as not an issue with the npm CLI. This looks like an issue with Electron shell, so you might want to take it up [with the Electron maintainers](https://github.com/electron/electron). Thanks for your time!
