### ISSUE TITLE
the ability to force nested and keep silence of version outdated.

### ISSUE THREAD

**Issue by calidion** [npm/npm#12165]
flat and nested are both very useful for dependency resolving.
To get rid of dependency explosion, flat  is a good choice.
To keep packages safe, nested is a better choice.

As npm3 defaults to flat now, it is very good to reduce some redundancies.

But npm should provide a way to keep them both available and be in harmony.

I would like to suggest npm having some options in both command line and package.json
to make both nested and flat possible.
for command line:

``` sh
npm install --force-nested / --force-flat
```

for packages:

``` json
nestedDependencies: {
}
flatDependencies: {
}
```

and can be updated with 

``` sh
--save-force-nested/--save-force-flat.
```

For those who think too much nested packages will waste their time,

``` sh
 npm install --force-flat 
```

will help.

For those who think package stability is more important, 

``` sh
npm install --force-nested
```

will help.

And it would be better to keep silent for version outdated, because we don't need updating every time a new update is ready when we are happy with the old version.
some times updating into a new version will ruin every thing built and waste a lot of time to fix them but get nothing in return.

thanks.

**Comment by AgentME** [comment]
Why is nested a better way to keep packages safe?

**Comment by passcod** [comment]
And what do you mean by your last paragraph? `npm install` doesn't tell about outdated versions, only `npm outdated` does.

**Comment by calidion** [comment]
@AgentME 
because nested way keeps package dependencies to versions tested with the package.

@passcod 

currently, it seems npm very cares about upgrading to the newest version.
And it will give warnings to those using <code>npm install</code>.
but it is no a good idea.
Not all packages need to be updated when their dependencies are updated.

To keep version update silence is good to get rid of unnecessary work just because of version update.

that is what i mean.
