### ISSUE TITLE
npm install error ERR! Windows_NT 6.1.7601

### ISSUE THREAD

**Issue by Vasant2411** [npm/npm#12160]
42929 error Windows_NT 6.1.7601
42930 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
42931 error node v5.7.0
42932 error npm  v3.6.0
42933 error file C:\Users\VTG\AppData\Roaming\npm-cache\elegant-spinner\1.0.1\package\package.json
42934 error code EJSONPARSE
42935 error Failed to parse json
42935 error No data, empty input at 1:1
42935 error
42935 error ^
42936 error File: C:\Users\VTG\AppData\Roaming\npm-cache\elegant-spinner\1.0.1\package\package.json
42937 error Failed to parse package.json data.
42937 error package.json must be actual JSON, not just JavaScript.
42937 error
42937 error This is not a bug in npm.
42937 error Tell the package author to fix their package.json file. JSON.parse
42938 verbose exit [ 1, true ]
[npm-debug.txt](https://github.com/npm/npm/files/197563/npm-debug.txt)

**Comment by pedzed** [comment]
Everything is so clear from the logs. Did you read it?

> Failed to parse package.json data.

You have a problem with the package.json.

> 42935 error Failed to parse json
42935 error No data, empty input at 1:1

JSON seems to be wrong.

> This is not a bug in npm.

...
