### ISSUE TITLE
Is it possible to install devDependencies of first-level dependencies?

### ISSUE THREAD

**Issue by TomiS** [npm/npm#12167]
Hi.

Is it possible to force NPM to install dev-dependencies of first level dependency. I have a following example situation where I'd like to install all Platform dev-dependencies to my App. The only workaround I found was to move all platform dev-dependencies to dependencies which is kind of ugly.

```
# App package
{
  "name": "@my/app",
  "dependencies": {
    "@my/platform": "^0.1.0"
  }
}
```

```
# Platform package (simplified)
{
  "name": "@my/platform",
  "version": "0.1.0",
  "dependencies": {
    "react": "^0.14.8"
  },
  "devDependencies": {
    "webpack": "^1.12.2"
  }
}
```

The rationale for this is that there are multiple Apps that use the same Platform and I wouldn't like to copy all dev-dependencies to each App.

**Comment by albertosouza** [comment]
Try:

Option 1: Add the first-level dev dependencies in your project:

```js
# App package
{
  "name": "@my/app",
  "dependencies": {
    "@my/platform": "^0.1.0"
  },
  "devDependencies": {
    "webpack": "^1.12.2"
  }
```

```js
# Platform package (simplified)
{
  "name": "@my/platform",
  "version": "0.1.0",
  "dependencies": {
    "react": "^0.14.8"
  },
  "devDependencies": {
    "webpack": "^1.12.2"
  }
}
```
Option 2: Or make an small script to enter in your sub module and run `npm install`

**Comment by jolim24601** [comment]
@TomiS
