### ISSUE TITLE
publishing public scoped module fails

### ISSUE THREAD

**Issue by puckey** [npm/npm#12168]
When I try to publish a public scoped module (`npm publish --access public`), I get the following error: `You need a paid account to perform this action. For more info, visit: https://www.npmjs.com/private-modules : @studiomoniker/point`

[npm-debug.txt](https://github.com/npm/npm/files/199560/npm-debug.txt)

**Comment by jelbourn** [comment]
I ran into a similar issue. I tried to publish a new scoped package with just `npm publish`, having forgotton the `--access public`. This actually _created_ a private scoped package on npm that was inaccessible, despite `npm publish` failing with an error. Subsequent attempts to publish with `--access public` continues to fail.

I fixed it by using `npm access public` on the package.

**Comment by boneskull** [comment]
I can confirm @jelbourn 's workaround works

**Comment by gabmontes** [comment]
Same issue. Thanks @jelbourn for the workaround!!

**Comment by SebastienDaniel** [comment]
@jelbourn solution works.

however, It's odd behaviour for sure..

**Comment by bebraw** [comment]
`npm access public` gives `npm ERR! 500 Internal Server Error` to me. Maybe something has changed in the backend.

**Comment by legodude17** [comment]
pinging @soldair for backend issues, also you may want to take it over to npm/registry
