### ISSUE TITLE
npm Install Errors in Windows 8.1. x64 laravel/homestead

### ISSUE THREAD

**Issue by mirbatworks** [npm/npm#12185]
I'm using windows 8.1 x64 architecture and Laravel Homestead. This is Error what I get when I run command "npm install" inside ssh.

```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.11
npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v5.7.0
npm ERR! npm  v3.6.0
npm ERR! path /home/vagrant/sites/cms/node_modules/.staging/abbrev-616613c3/package.json.1692531893
npm ERR! code EPERM
npm ERR! errno -1
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename '/home/vagrant/sites/cms/node_modules/.staging/abbrev-616613c3/package.json.1692531893' -> '/home/vagrant/sites/cms/node_modules/.staging/abbrev-616613c3/package.json'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM: operation not permitted, rename '/home/vagrant/sites/cms/node_modules/.staging/abbrev-616613c3/package.json.1692531893' -> '/home/vagrant/sites/cms/node_modules/.staging/abbrev-616613c3/package.json']
npm ERR!   errno: -1,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'rename',
npm ERR!   path: '/home/vagrant/sites/cms/node_modules/.staging/abbrev-616613c3/package.json.1692531893',
npm ERR!   dest: '/home/vagrant/sites/cms/node_modules/.staging/abbrev-616613c3/package.json' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/sites/cms/npm-debug.log
```

[npm-debug.zip](https://github.com/npm/npm/files/202675/npm-debug.zip)

**Comment by mirbatworks** [comment]
This is what I get when I try to run gulp:
vagrant@homestead:~/sites/cms$ gulp
module.js:341
    throw err;
    ^

Error: Cannot find module 'laravel-elixir'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/vagrant/sites/cms/gulpfile.js:1:76)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)

**Comment by vdonchev** [comment]
Same here, Win 10 x64 laravel/homestead

**Comment by AdamEsterle** [comment]
Saem here, Windows 7 x64 laravel/homestead

**Comment by jsergiu** [comment]
There are some issues with installing the node packages directly in the shared folder. A good workaround is to install the packages somewhere inside the vm then create a symlink. 
Ex:
cd /vagrant
rm -rf node_modules
mkdir /home/vagrant/vagrant_node_modules
cp package.json /home/vagrant/vagrant_node_modules
cd /home/vagrant/vagrant_node_modules
npm install
cd /vagrant 
ln -s /home/vagrant/vagrant_node_modules/node_modules node_modules
ls -ld node_modules

**Comment by AdamEsterle** [comment]
A workaround that helped me was to do
npm install
on my windows side (not in homestead)

**Comment by ahmediftar** [comment]
I still have this same problem and I'm not able to solve it.  Can someone help out?

**Comment by AdamEsterle** [comment]
@ahmediftar 
NPM + Homestead = very fickle for some reason
Here is my list of options I try when I am running into problems:

npm install
npm update
try sudo
try --no-bin-links (npm install --no-bin-links)
try deleting node_modules folder
try on host machine (not homestead)
