### ISSUE TITLE
No compatible version found: mongodb@~3.2.4 npm ERR! 

### ISSUE THREAD

**Issue by nags84** [npm/npm#12189]
i am getting the below mentioned error when i tried to run npm install command

npm ERR! No compatible version found: mongodb@~3.2.4
npm ERR! Valid install targets:
npm ERR! 2.1.14, 2.1.13, 2.1.12, 2.1.11, 2.1.10, 2.1.9, 2.1.8, 2.1.7, 2.1.6, 2.1.5, 2.1.4, 2.1.3, 2.1.2, 2.1.1, 2.1.0, 2.1.0-rc1, 2.1.0-alpha, 2.0.55, 2.0.54, 2.0.53, 2.0.52, 2.0.51, 2.0.50, 2.0.49, 2.0.48, 2.0.47, 2.0.46, 2.0.45, 2.0.44, 2.0.43, 2.0.42, 2.0.41, 2.0.40, 2.0.39, 2.0.38, 2.0.37, 2.0.36, 2.0.35, 2.0.34, 2.0.33, 2.0.32, 2.0.31, 2.0.30, 2.0.29, 2.0.28, 2.0.27, 2.0.26, 2.0.25, 2.0.24, 2.0.23, 2.0.22, 2.0.21, 2.0.20, 2.0.19, 2.0.18, 2.0.17, 2.0.16, 2.0.15, 2.0.14, 2.0.13, 2.0.12, 2.0.11, 2.0.10, 2.0.9, 2.0.8, 2.0.7, 2.0.6, 2.0.5, 2.0.4, 2.0.3, 2.0.2, 2.0.1, 2.0.0, 2.0.0-alpha2, 2.0.0-alpha1, 1.4.40, 1.4.39, 1.4.38, 1.4.37, 1.4.36, 1.4.35, 1.4.34, 1.4.33, 1.4.32, 1.4.31, 1.4.30, 1.4.29, 1.4.28, 1.4.27, 1.4.26, 1.4.25, 1.4.24, 1.4.23, 1.4.22, 1.4.20, 1.4.19, 1.4.18, 1.4.17, 1.4.16, 1.4.15, 1.4.14, 1.4.12, 1.4.11, 1.4.10, 1.4.9, 1.4.8, 1.4.7, 1.4.6, 1.4.5, 1.4.4, 1.4.3, 1.4.2, 1.4.1, 1.4.0, 1.4.0-rc9, 1.4.0-rc8, 1.4.0-rc7, 1.4.0-rc6, 1.4.0-rc5, 1.4.0-rc4, 1.4.0-rc3, 1.4.0-rc2, 1.4.0-rc10, 1.3.23, 1.3.22, 1.3.21, 1.3.20, 1.3.19, 1.3.18, 1.3.17, 1.3.15, 1.3.14, 1.3.12, 1.3.11, 1.3.10, 1.3.9, 1.3.8, 1.3.7, 1.3.6, 1.3.5, 1.3.4, 1.3.3, 1.3.2, 1.3.1, 1.3.0, 1.2.14, 1.2.13, 1.2.12, 1.2.11, 1.2.10, 1.2.9, 1.2.8, 1.2.7, 1.2.6, 1.2.5, 1.2.4, 1.2.3, 1.2.2, 1.2.1, 1.2.0, 1.1.11, 1.1.10, 1.1.9, 1.1.8, 1.1.7, 1.1.6, 1.1.5, 1.1.4, 1.1.3, 1.1.2, 1.1.1, 1.1.0, 1.1.0-beta, 1.0.2, 1.0.1, 1.0.0, 0.9.9, 0.9.9-8, 0.9.9-7, 0.9.9-6, 0.9.9-5, 0.9.9-4, 0.9.9-3, 0.9.9-2, 0.9.9-1, 0.9.8, 0.9.8-7, 0.9.8-6, 0.9.8-5, 0.9.8-4, 0.9.8-3, 0.9.8-2, 0.9.8-1, 0.9.7, 0.9.7-3-5, 0.9.7-3-4, 0.9.7-3-3, 0.9.7-3-2, 0.9.7-3-1, 0.9.7-2-5, 0.9.7-2-4, 0.9.7-2-3, 0.9.7-2-2, 0.9.7-2-1, 0.9.7-3, 0.9.7-2, 0.9.7-1.4, 0.9.7-1.3, 0.9.7-1.2, 0.9.7-1.1, 0.9.7-1, 0.9.7-0, 0.9.6-23, 0.9.6-22, 0.9.6-21, 0.9.6-20, 0.9.6-19, 0.9.6-18, 0.9.6-17, 0.9.6-16, 0.9.6-15, 0.9.6-14, 0.9.6-13, 0.9.6-12, 0.9.6-11, 0.9.6-10, 0.9.6-9, 0.9.6-8, 0.9.6-7, 0.9.4, 0.9.4-4, 0.9.3, 0.9.2, 0.9.1
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by othiym23** [comment]
There's no version of `mongodb` compatible with the semver range `~3.2.4`, because there are no published versions of the package on the registry equal to or greater than 3.2.4 and less than 3.3.0 – you can see that in the included list of versions. Since this is the intended (and expected) behavior, I'm going to close this issue. I'd double-check to make sure that both the package name and version are correct. Thanks for your time, and good luck getting this sorted out!

**Comment by nags84** [comment]
Thanks for the update Othiym, but i have installed the latest version of mongodb which tells me this:

rajesh@rajesh-ThinkPad-T420:~/app3/Vidzy$ mongod --version
db version v3.2.4
git version: e2ee9ffcf9f5a94fad76802e28cc978718bb7a30
OpenSSL version: OpenSSL 1.0.1f 6 Jan 2014
allocator: tcmalloc
modules: none
build environment:
    distmod: ubuntu1404
    distarch: x86_64
    target_arch: x86_64

can you please me where am i missing here :(, Also i am trying to connect mongodb using monk.

**Comment by KenanY** [comment]
`mongod` is the database itself. What you get from `npm install mongodb` is a Node.js driver for the database. The two do not necessarily have the same version numbers.

**Comment by othiym23** [comment]
There's no correlation between the version of MongoDB and the Node.js driver. If you check http://npm.im/mongodb, you'll see that it's still at `2.1.x`, as well as instructions on how to use the driver with MongoDB.
