### ISSUE TITLE
Refusing to install react as a dependency of itself

### ISSUE THREAD

**Issue by christofferengstrom** [npm/npm#12204]
I can't initiate new react projects anymore..

`npm ERR! Darwin 15.4.0`
`npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "react" "----save"`
`npm ERR! node v5.7.0`
`npm ERR! npm  v3.6.0`
`npm ERR! code ENOSELF`

Refusing to install react as a dependency of itself.

[npm-debug.log.zip](https://github.com/npm/npm/files/204621/npm-debug.log.zip)

**Comment by KenanY** [comment]
@christofferengstrom Is the name of your current directory `"react"`? Is the `"name"` attribute in your `package.json` equal to `"react"`?

**Comment by christofferengstrom** [comment]
Oh, so naming the project to `react` was the problem? Worked fine when I changed from ´react-native init react' to ´react-native init NewProject'.

I tried both in my home folder and some other different directory. 
So yes, the `"name"` attribute in my `package.json` was equal to `"react"`.

**Comment by KenanY** [comment]
@christofferengstrom Yeah your project can't share a name with one of your dependencies.

**Comment by christofferengstrom** [comment]
Thank you for the help! @KenanY

**Comment by gitneo** [comment]
Thanks! This Helped.

**Comment by amitsaini000** [comment]
Great!!

**Comment by anjasmaradwisetiadi** [comment]
How to install npm-debug.log in react ? please help me.

**Comment by ghost** [comment]
@KenanY  Last night I had a problem related to this and I solved that with your help thank you so much
