### ISSUE TITLE
Which kind of issue is it ??!

### ISSUE THREAD

**Issue by Chaoui05** [npm/npm#12203]
```
ERROR: Error: ENOENT: no such file or directory, mkdir 'D:\testDalek\report\dalek\details
```

**Comment by othiym23** [comment]
Could you give us some more details? This is going to be hard to troubleshoot with the information provided.

**Comment by Chaoui05** [comment]
Yes of course ; i will put a screen

**Comment by Chaoui05** [comment]
i instal this modul to get a report in Dalek
![dalekreport1](https://cloud.githubusercontent.com/assets/18040660/14313196/7f877a14-fbf0-11e5-99e7-880915d650e5.png)
 And when i use the line command this error message appears :+1: 
![dalekreport2](https://cloud.githubusercontent.com/assets/18040660/14313225/a4db423c-fbf0-11e5-9906-98f5e2f7cbca.png)

**Comment by heijmans** [comment]
This is a dalek issue and not a npm issue. I would suggest that you file an issue with dalekjs and that this issue be closed.

**Comment by KenanY** [comment]
Closing since I don't see any `npm` issues here. Thanks for the heads-up, @heijmans :)
