### ISSUE TITLE
error while npm install

### ISSUE THREAD

**Issue by Asaak** [npm/npm#12206]
Hi!

I've put my cloned directory inside C:/ffwdme , so I think there is nothing wrong with long path names. However, when I try to do npm install, I get this error:

> npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
> npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
> npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
> npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
> npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
> npm WARN addRemoteGit
> npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:202:12)
> npm WARN addRemoteGit     at emitTwo (events.js:100:13)
> npm WARN addRemoteGit     at ChildProcess.emit (events.js:185:7)
> npm WARN addRemoteGit     at maybeClose (internal/child_process.js:850:16)
> npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
> npm WARN addRemoteGit  git://github.com/bessdsv/bower-installer.git#temp resetting remote C:\Users\antonio.linaresbravo\AppData\Roaming\npm-cache\_git-remotes\git-github-com-bessdsv-bower-installer-git-temp-5f628818 because of error: { [Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
> npm WARN addRemoteGit ]
> npm WARN addRemoteGit   killed: false,
> npm WARN addRemoteGit   code: 1,
> npm WARN addRemoteGit   signal: null,
> npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
> npm ERR! git clone --template=C:\Users\antonio.linaresbravo\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/bessdsv/bower-installer.git C:\Users\antonio.linaresbravo\AppData\Roaming\npm-cache\_git-remotes\git-github-com-bessdsv-bower-installer-git-temp-5f628818: Cloning into bare repository 'C:\Users\antonio.linaresbravo\AppData\Roaming\npm-cache\_git-remotes\git-github-com-bessdsv-bower-installer-git-temp-5f628818'...
> npm ERR! git clone --template=C:\Users\antonio.linaresbravo\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/bessdsv/bower-installer.git C:\Users\antonio.linaresbravo\AppData\Roaming\npm-cache\_git-remotes\git-github-com-bessdsv-bower-installer-git-temp-5f628818: fatal: unable to connect to github.com:
> npm ERR! git clone --template=C:\Users\antonio.linaresbravo\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/bessdsv/bower-installer.git C:\Users\antonio.linaresbravo\AppData\Roaming\npm-cache\_git-remotes\git-github-com-bessdsv-bower-installer-git-temp-5f628818: github.com[0: 192.30.252.122]: errno=Invalid argument
> npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
> npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.11
> npm ERR! Windows_NT 10.0.10586
> npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
> npm ERR! node v5.10.0
> npm ERR! npm  v3.8.3
> npm ERR! code 128
> 
> npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\antonio.linaresbravo\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/bessdsv/bower-installer.git C:\Users\antonio.linaresbravo\AppData\Roaming\npm-cache\_git-remotes\git-github-com-bessdsv-bower-installer-git-temp-5f628818
> npm ERR! Cloning into bare repository 'C:\Users\antonio.linaresbravo\AppData\Roaming\npm-cache\_git-remotes\git-github-com-bessdsv-bower-installer-git-temp-5f628818'...
> npm ERR! fatal: unable to connect to github.com:
> npm ERR! github.com[0: 192.30.252.122]: errno=Invalid argument
> npm ERR!
> npm ERR!
> npm ERR!
> npm ERR! If you need help, you may report this error at:
> npm ERR!     <https://github.com/npm/npm/issues>
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     C:\ffwdme\npm-debug.log

Any idea what is wrong? 

Thank you!

**Comment by othiym23** [comment]
This is probably due to some [wobbliness with GitHub]() today. Wait a bit and try again. Because this is due to something not under npm's control, I'm going to go ahead and close this issue. Thanks for the heads up, and good luck (to all of us)!
