### ISSUE TITLE
`bundledDependencies` could use better docs

### ISSUE THREAD

**Issue by zkat** [npm/npm#12208]
The [current documentation for `bundledDependencies`](https://docs.npmjs.com/files/package.json#bundleddependencies) is pretty sparse compared to a lot of other settings. It would be really nice to describe how to use it, and how the npm installer handles them, and how they interact with other settings, shrinkwrap, etc.

To start, some slightly-expanded docs would be great, though!

**Comment by KenanY** [comment]
https://github.com/npm/npm/pull/11483 is a good start.

**Comment by zkat** [comment]
Oh! It is! Good call! I pinged @ashleygwilliams about getting the website updated. I'll close this for now, since I think that's a fine thing to have for now.
