### ISSUE TITLE
npm link does not support unsafe-perm

### ISSUE THREAD

**Issue by ijsf** [npm/npm#12215]
When using `npm --install`, we can specify the `--unsafe-perm` option to safely ignore npm's "safety" features. Additionally, we can specify this in the `package.json` file.

However, when running `npm link` there is no such option. This is especially annoying for modules that have `install` scripts (e.g. build commands) in their `package.json` file. Furthermore, the `unsafe-perm` option in `package.json` is completely ignored.

**Comment by othiym23** [comment]
Even though it's not documented as such on the `npm link` page, `--unsafe-perm` should do the exact same thing when used on the command line (`npm link --unsafe-perm`) that it does when included with `npm install`. If you have an example of this not working in practice with a current version of `npm@2` or `npm@3`, let us know and I'll reopen this issue. Thanks for your time!
