### ISSUE TITLE
Selenium Standalone-server installation

### ISSUE THREAD

**Issue by akhila-m** [npm/npm#12212]
Seeing errors on installing selenium standalone-server
[npm-debug.log.zip](https://github.com/npm/npm/files/205064/npm-debug.log.zip)

**Comment by othiym23** [comment]
```
36 error No compatible version found: selenium-standalone@latest-g
```

The command you should be running is instead

```
npm install standalone-server@latest -g
```

(note the space between `latest` and `-g`)

Closing as resolved. Thanks for your time!
