### ISSUE TITLE
npm install -g gulp fails (npm 1.3.10, node 0.10.25, ubuntu 14.04)

### ISSUE THREAD

**Issue by occamsraiser** [npm/npm#12219]
... with the error "ENOENT, chown '/usr/local/lib/node_modules/gulp/node_modules/minimist/test/whitespace.js'"

See attached screengrabs. 

![gulp_error_part1](https://cloud.githubusercontent.com/assets/6416011/14299340/1f99b206-fb47-11e5-8316-221fc356852e.png)
![gulp_error_part2](https://cloud.githubusercontent.com/assets/6416011/14299343/234c6d44-fb47-11e5-9b9c-1b5b46c54c18.png)

This just started happening in the last 24 hours or so.

**Comment by othiym23** [comment]
This is probably a consequence of #12196, but it's hard to say from that screenshot. I'm going to close it as a duplicate, but you also should update to a newer version of npm (I suggest the [Node|Source distribution](https://github.com/nodesource/distributions) if you're on Ubuntu, as you appear to be). `npm@1.3` is nearly three years old and no longer supported by the npm CLI team. Newer versions of npm are _much_ more reliable than `npm@1`. Thanks for your time!
