### ISSUE TITLE
Multiple npm scripts bound to one command?

### ISSUE THREAD

**Issue by jamen** [npm/npm#12226]
Is it possible to bind multiple npm scripts to one command?  This way you can have a shorter configurations.  For instance, projects that have a lot of pre-compiling, building, or gulp would benefit.
```javascript
{
  // ...
  "scripts": {
    // ...
  }
}
```
```javascript
"build,preinstall,prepublish,pretest": "gulp" 
```
```javascript
"pre*": "gulp"
```

**Comment by othiym23** [comment]
While I see the appeal of this, the CLI team feels that a clear, simple, and sometimes repetitive syntax is a lot easier to learn and use than one that tries to DRY up everything. It would be useful if there were a tool that could build out the "scripts" section of `package.json` like you describe, but even so, we'd want the scripts section to keep explicitly mapping single lifecycle events to actions, even if it's a little repetitive or noisy. As such, I'm going to close this issue. Thanks for your time!
