### ISSUE TITLE
Errors while npm install -g

### ISSUE THREAD

**Issue by bekkemg** [npm/npm#12222]
$ sudo npm install -g
```
npm http GET https://registry.npmjs.org/jasminewd2/0.0.6
npm http GET https://registry.npmjs.org/protractor/3.0.0
npm http GET https://registry.npmjs.org/png-image/1.0.0
npm http GET https://registry.npmjs.org/jasmine/2.4.1
npm http GET https://registry.npmjs.org/jasminewd/1.1.0
npm http GET https://github.com/MrUkyoDuong/blink-diff.git#fcbb9730d731beb424f41ad3d3bd40ce3bc75979
npm http GET https://registry.npmjs.org/selenium-webdriver/2.52.0
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://github.com/Mr/pix-diff.git#e8663ddff67248242090a98cfc8ac599d8c1d426
npm http GET https://registry.npmjs.org/protractor-jasmine2-html-reporter/0.0.5
npm http GET https://registry.npmjs.org/jasmine-reporters/2.0.7
npm http 200 https://github.com/Mr/blink-diff.git#fcbb9730d731beb424f41ad3d3bd40ce3bc75979
npm http 200 https://github.com/Mr/pix-diff.git#e8663ddff67248242090a98cfc8ac599d8c1d426
npm ERR! not a package /srv/home/---/tmp/npm-20887--1w9iV1X/1459913556761-0.638673227513209/tmp.tgz
npm http 304 https://registry.npmjs.org/png-image/1.0.0
npm http 304 https://registry.npmjs.org/jasminewd/1.1.0
npm http 200 https://registry.npmjs.org/jasminewd2/0.0.6
npm http 304 https://registry.npmjs.org/jasmine/2.4.1
npm http 200 https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/protractor/3.0.0
npm http 304 https://registry.npmjs.org/selenium-webdriver/2.52.0
npm ERR! Error: ENOENT, open '/srv/home/-----/tmp/npm-20887--1w9iV1X/1459913556761-0.638673227513209/package/package.json'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-48-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g"
npm ERR! cwd /srv/home/---/git/qa/automation/portal
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /srv/home/-----/tmp/npm-20887--1w9iV1X/1459913556761-0.638673227513209/package/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! not a package /srv/home/----/tmp/npm-20887--1w9iV1X/1459913556778-0.3756314718630165/tmp.tgz
npm http GET https://registry.npmjs.org/jasminewd2/-/jasminewd2-0.0.6.tgz
npm http 304 https://registry.npmjs.org/protractor-jasmine2-html-reporter/0.0.5
npm http 200 https://registry.npmjs.org/jasminewd2/-/jasminewd2-0.0.6.tgz
npm http 304 https://registry.npmjs.org/jasmine-reporters/2.0.7
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /srv/home/----/git/qa/automation/portal/npm-debug.log
npm ERR! not ok code 0
```

I am trying to install following packages using .Json file:

"protractor": "3.0.0",
    "png-image": "1.0.0",
    "jasmine": "2.4.1",
    "jasminewd": "1.1.0",
    "jasminewd2": "0.0.6",
    "selenium-webdriver": "2.52.0",
    "mkdirp": "~0.3.5",
    "protractor-jasmine2-html-reporter": "0.0.5",
    "jasmine-reporters": "2.0.7",
    "blink-diff": "https://github.com/Mr/blink-diff.git#fcbb9730d731beb424f41ad3d3bd40ce3bc75979",
    "pix-diff": "https://github.com/Mr/pix-diff.git#e8663ddff67248242090a98cfc8ac599d8c1d426"

Resolving this issue will be appreciated!

Thanks!

**Comment by KenanY** [comment]
@bekkemg Try not using the `-g` flag. Also note that `npm@1.3` is very old and no longer supported.

**Comment by bekkemg** [comment]
@KenanY I am getting the following error if I run with out -g

sudo npm install
npm http GET https://registry.npmjs.org/png-image/1.0.0
npm http GET https://registry.npmjs.org/protractor/3.0.0
npm http GET https://registry.npmjs.org/jasminewd/1.1.0
npm http GET https://registry.npmjs.org/jasmine/2.4.1
npm http GET https://registry.npmjs.org/jasminewd2/0.0.6
npm http GET https://registry.npmjs.org/selenium-webdriver/2.52.0
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/protractor-jasmine2-html-reporter/0.0.5
npm http GET https://registry.npmjs.org/jasmine-reporters/2.0.7
npm http GET https://github.com/Mr/blink-diff.git#fcbb9730d731beb424f41                                                                                                             ad3d3bd40ce3bc75979
npm http GET https://github.com/Mr/pix-diff.git#e8663ddff67248242090a98                                                                                                             cfc8ac599d8c1d426
npm http 304 https://registry.npmjs.org/jasminewd2/0.0.6
npm http 304 https://registry.npmjs.org/jasmine/2.4.1
npm http 304 https://registry.npmjs.org/protractor/3.0.0
npm http 304 https://registry.npmjs.org/jasminewd/1.1.0
npm http 304 https://registry.npmjs.org/png-image/1.0.0
npm http 304 https://registry.npmjs.org/selenium-webdriver/2.52.0
npm http 304 https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/protractor-jasmine2-html-reporter/0.0.5
npm http 304 https://registry.npmjs.org/jasmine-reporters/2.0.7
npm http 200 https://github.com/Mr/pix-diff.git#e8663ddff67248242090a98                                                                                                             cfc8ac599d8c1d426
npm ERR! not a package /srv/home/------/tmp/npm-8744-_PJi-XPq/1459965300140-0.9                                                                                                             977170082274824/tmp.tgz
npm ERR! Error: ENOENT, open '/srv/home/-----/tmp/npm-8744-_PJi-XPq/1459965300                                                                                                             140-0.9977170082274824/package/package.json'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-48-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /srv/home/----/git/qa/automation/portal
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /srv/home/----/tmp/npm-8744-_PJi-XPq/1459965300140-0.9977170082                                                                                                             274824/package/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm http 200 https://github.com/Mr-------/blink-diff.git#fcbb9730d731beb424f41                                                                                                             ad3d3bd40ce3bc75979
npm ERR! not a package /srv/home/----/tmp/npm-8744-_PJi-XPq/1459965300139-0.1                                                                                                             862195306457579/tmp.tgz
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /srv/home/-------/git/qa/automation/portal/npm-debug.log
npm ERR! not ok code 0

**Comment by KenanY** [comment]
@bekkemg [Update `npm`](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm).

**Comment by bekkemg** [comment]
Got it Thanks! @KenanY

**Comment by othiym23** [comment]
Closing as resolved. It's possible the underlying issue was related to #12196, but without the entire `npm-debug.log`, I can't say for sure.
