### ISSUE TITLE
npm removes required dependency from other packages

### ISSUE THREAD

**Issue by Risto-Stevcev** [npm/npm#12235]
Example:
1. I install `babel-core` because I want to use babel in my project
2. I decide a little later that I want to use gulp instead, so I install `gulp-babel`
3. I don't need `babel-core` anymore so I uninstall it. However, if I try to run `gulp-babel`, it will throw an error now:

``` bash
Error: Cannot find module 'babel-core'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/user/myproj/node_modules/gulp-babel/index.js:8:13)
```

Uninstalling `babel-core` will also break existing packages that depend on it. Does this have something to do with npm3 flattening the dependency tree?

And if so, why can't npm intelligently uninstall (ie, just move `babel-core` to `gulp-babel`'s node_modules as if it was never installed separately)

**Comment by tleb** [comment]
+1, I think npm should tell us that another package depends on it and ask us if we still want to remove the specified package.

**Comment by jedwards1211** [comment]
Is it just me, or does the tree flattening seem to have cause a whole host of bugs that weren't an issue in npm 2?
