### ISSUE TITLE
issue in installing cookie-parser package

### ISSUE THREAD

**Issue by alokbhawsinka** [npm/npm#12233]
I am newbie on node js. Just trying to install npm cookie-parser. SO I got
![screenshot from 2016-04-06 16_28_07](https://cloud.githubusercontent.com/assets/832124/14314798/1c94b986-fc17-11e5-8a6c-c151862765d2.png)
 following issue.

**Comment by KenanY** [comment]
Looks like https://github.com/npm/npm/issues/12196.

**Comment by alokbhawsinka** [comment]
Thanks Kenan.It's fixed
