### ISSUE TITLE
Node Inspector access

### ISSUE THREAD

**Issue by 3y3** [npm/npm#12249]
Hello, I'm a maintainer on Node Inspector project.
https://www.npmjs.com/package/node-inspector
https://github.com/node-inspector/node-inspector

At current time I have a problems with publishing

npm ERR! you do not have permission to publish "node-inspector". Are you logged in as the correct user? : node-inspector

`npm owner ls` responds me with
> admin party!

Expected behavior - `npm owner ls` responds me with:
dannycoates <dannycoates@gmail.com>
bajtos <miro.bajtos@gmail.com>
3y3 <3y3@bk.ru>

Please help me to restore access to project.

**Comment by othiym23** [comment]
I believe you've already contacted support@npmjs.com. I'm going to close this issue as that's the correct venue for help with issues with the registry. Thanks for your time and patience, and I hope that this gets sorted out quickly!
