### ISSUE TITLE
npm install bower is not working 

### ISSUE THREAD

**Issue by MahaSannasi** [npm/npm#12259]
```
C:\Users\Administrator\git\hygieia\UI>npm install bower
 npm ERR! registry error parsing json
 npm ERR! Windows_NT 6.3.9600
 npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\
 node_modules\npm\bin\npm-cli.js" "install" "bower"
 npm ERR! node v5.10.1
 npm ERR! npm v3.8.3
 npm ERR! Unexpected token C
 npm ERR! Cannot GET /bower
 npm ERR!
 npm ERR!
 npm ERR! If you need help, you may report this error at:
 npm ERR! https://github.com/npm/npm/issues
 npm ERR! Please include the following file with any support request:
 npm ERR! C:\Users\Administrator\git\hygieia\UI\npm-debug.log
```

![error-git](https://cloud.githubusercontent.com/assets/13997388/14355350/40b2f156-fcfe-11e5-8729-5ed990705d87.png)

**Comment by othiym23** [comment]
The npm registry team has been working on fixing a configuration issue that was causing problems for some users of older versions of npm. Does this failure happen consistently? If so, can you [make a gist](https://gist.github.com/) out of the `npm-debug.log` file that npm leaves behind on failure? What you've provided here is useful, but insufficient to figure out what's actually going on.

**Comment by MahaSannasi** [comment]
[debug_file.txt](https://github.com/npm/npm/files/209686/debug_file.txt)

**Comment by MahaSannasi** [comment]
Yeah I am getting this continuously. Please tell the solution

**Comment by shubhamrastogi1994** [comment]
Try using it in Git Bash on Windows
