### ISSUE TITLE
errno -4058 when npm install npm@2.14.5

### ISSUE THREAD

**Issue by weicyang** [npm/npm#12258]
hi, 

  I meet a problem when I install npm.
  I install nodeJs() first, then run  cmd  as administrator and input : npm install –g npm@2.14.5,
  I want update to 2.14.5, but one error report:

```
C:\Users\lch>npm install –g npm@2.14.5
npm ERR! addLocal Could not install C:\Users\lch\–g
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (
x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "–g" "npm@2.14.5"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! path C:\Users\lch\–g
npm ERR! code ENOENT
npm ERR! errno -4058

npm ERR! enoent ENOENT, open 'C:\Users\lch\–g'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\lch\npm-debug.log
```

when run  npm install –g nodeunit, have same error, How can I slove it ,thanks!

**Comment by KenanY** [comment]
@weicyang Try:

```
npm install -g npm@2.14.5
```

Use a regular hyphen instead of a hyphen-minus.

**Comment by weicyang** [comment]
@KenanY , It is ok use your method, thanks very much!

**Comment by KenanY** [comment]
Closing as resolved.

**Comment by bhabanipattanayak** [comment]
What is the difference between npm install -g npm@2.14.5   and npm install -g
One of the machine i tried to run 'npm install -g' and it works fine but another machine it did not work,
but 'npm install -g npm@2.14.5' worked.
I am not sure what is the reason. Can anyone explain.

**Comment by kenany** [comment]
`npm install -g npm@2.14.5` globalls installs `npm@2.14.5`.

`npm install -g` globally installs whatever module is in your current working directory.
