### ISSUE TITLE
unable to connect MySql with Nodejs

### ISSUE THREAD

**Issue by akash16** [npm/npm#12253]
Following error is received:
{"fault":{"faultstring":"Script execution failed: Cannot enqueue Handshake after fatal error.:     at \/organization\/environment\/api\/logindatavalidation.js:16\n    at domain.js:183\n    at \/organization\/environment\/api\/node_modules\/mysql\/lib\/protocol\/sequences\/Sequence.js:96\n    at \/organization\/environment\/api\/node_modules\/mysql\/lib\/protocol\/Protocol.js:226\n    at _tickDomainCallback (trireme.js:491)\n    at _tickFromSpinner (trireme.js:422)\n","detail":{"errorcode":"scripts.node.runtime.ScriptExecutionError"}}}

**Comment by KenanY** [comment]
@akash16 Is this an issue with `npm`?

**Comment by othiym23** [comment]
Closing, because this isn't an issue with the npm CLI. It looks like this is probably a configuration issue with the MySQL client, which isn't something the npm CLI team is going to be able to help you with. Thanks for your time and good luck!

**Comment by akash16** [comment]
Actaully I am able to connect with the same mysql server using Java, but I am facing issues while connecting through Node Js . So, it seems to be an issue with npm only. Could you please look into it again and let me know if some more information is required.

**Comment by othiym23** [comment]
This may well be a problem with the Node.js driver for MySQL, but this issue tracker is only for the npm command-line client to the npm registry – we don't (and can't, give the scale and scope of what's available via the registry) provide general-purpose support for issues with packages that can be downloaded and installed using the CLI.
