### ISSUE TITLE
npm update --save after running npm update does not save

### ISSUE THREAD

**Issue by AlexTes** [npm/npm#12256]
The documentation notes the above behavior.
> Note that npm will only write an updated version to package.json if it installs a new package.

However that doesn't help me very much. Our unit-tests failed with a normal `npm install` with only a clean install fixing things. Because of that I'd like to force the version ranges to be at least their latest compatible version. However, as I ran a clean install, and don't version control our node_modules, I now cannot use `npm update --save`.
Neither [npm-check](https://www.npmjs.com/package/npm-check) or [npm-check-updates](https://www.npmjs.com/package/npm-check-updates) supports this, so it seems I'm dead out of luck.

Is doing it all by hand / writing a script that checks mismatches between the currently installed version `npm list --depth=0` against the `package.json` the only way? Because if so, perhaps you too feel npm could be more helpful in this use-case.

Thanks!

**Comment by othiym23** [comment]
The current behavior stems from the fact that `npm update --save` _does_ only save packages that have been changed by this operation. You're right that updating package semver ranges in dependencies is kind of laborious right now. In the future, the CLI may change to make it easier to bring `package.json` up to date with either what's in `node_modules` or on the registry for a set of dependencies, but this is something that requires some careful design, and it isn't something CLI team is likely to get to within the next 6-12 months. As such, I'm going to close this feature request. Thanks for your time and the clear problem statement!
