### ISSUE TITLE
npm install problem - Hostname/IP doesn't match certificate's altnames

### ISSUE THREAD

**Issue by esykes** [npm/npm#12261]
I'm encountering a problem when running "npm install". I was first getting "could not get local issuer certificate", but after pointing at a file that contains my organization's root CA certificate I now see this:

npm ERR! Hostname/IP doesn't match certificate's altnames: "Host: registry.npmjs
.org. is not in the cert's altnames: DNS:a.sni.fastly.net, DNS:a.sni.global-ssl.
fastly.net"

I must admit, I'm really new to all of this. I followed the instructions here (the accepted answer) to get the root CA cert to be consulted. I did what he suggests at the end, and used curl's Mozilla based CA bundle with my root CA cert appended at the bottom of the file. Hopefully that did not screw anything up!

**Comment by esykes** [comment]
[npm error log.txt](https://github.com/npm/npm/files/209089/npm.error.log.txt)

**Comment by ysweiseh** [comment]
Try this command "npm config set strict-ssl false".
