### ISSUE TITLE
npm version && git push && npm publish

### ISSUE THREAD

**Issue by nodesocket** [npm/npm#12264]
I'm trying to have a single command that:

     - bumps package.json version
     - git add -A .
     - git commit -m "$MESSAGE_HERE"
     - git push
     - npm publish

I came up with:

```
"scripts": {
    "version": "git add -A .",
    "postversion": "git push && npm publish"
}
````

Then running:

````
npm version --force patch -m "commit message here"
````

But it required using the `--force` flag because there are unstaged files. Is there a way to do this without using the `--force` flag? Seems like I am doing something naughty because of the warning message:

> npm WARN using --force I sure hope you know what you are doing.

**Comment by othiym23** [comment]
If you have a tool that makes changes automatically, e.g. a conventional changelog generator, you can plug that into `"preversion"` and it'll get run between the check for whether the directory is dirty and the package.json bump, so you can make those changes and stage them before the version bump and it will all be part of a single commit. However, there isn't a way to include _all_ your changes into a single commit, except through the kind of shenanigans using `--force` that you describe.

This workflow is pretty flexible and safe, and handles the most common use cases without making the dependency between npm and Git too tight (as in, it'll use Git for some things if a repo is available, but it doesn't require a Git-based flow). If it doesn't correspond to your preferred workflow, then you're probably better off doing it with a short shell script or a `Makefile` that does what you want; this is what npm does for its own versioning and publishing flows.

As this is something that works reasonably well without too deeply entangling Git and npm, the CLI team is unlikely to change it, and so we're going to close this issue. Thanks for the problem statement and your time!
