### ISSUE TITLE
Cannot install cordova through npm

### ISSUE THREAD

**Issue by muktanpromish** [npm/npm#12269]
Hi All,
I am trying to install cordova in my windows machine but couldn't understand the installation problem.
Node js and npm seems to be installed properly with its latest version.

Below is my screen shot as i tried to install cordova.

```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\Promish>npm --version
npm info it worked if it ends with ok
npm info using npm@2.15.0
npm info using node@v4.4.2
npm info ok
2.15.0

C:\Users\Promish>npm install -g cordova
npm info it worked if it ends with ok
npm info using npm@2.15.0
npm info using node@v4.4.2
npm info ok
npm info it worked if it ends with ok
npm info using npm@2.15.0
npm info using node@v4.4.2
npm info addNameTag [ 'cordova', 'latest' ]
npm info attempt registry request try #1 at 4:12:49 PM
npm http request GET http://registry.npmjs.org/cordova
npm http 304 http://registry.npmjs.org/cordova
```

Appreciate your help. Thanks.

![capture](https://cloud.githubusercontent.com/assets/5129054/14375463/e2f977a4-fda4-11e5-8735-1351af4c3fd1.PNG)

**Comment by AndroConsis** [comment]
Had the same issue here. It seems to be a bower problem and less an overall npm problem. Was able to get things working by uninstalling and reinstalling bower:

npm uninstall -g bower
npm install -g bower
