### ISSUE TITLE
Under certain conditions, npm init copies entries from `devDependencies` to `dependencies`

### ISSUE THREAD

**Issue by cappslock** [npm/npm#12260]
Using npm v2.15.3 and node v4.4.1, I'm attempting to use a templated package.json as a starting point for new modules. There's more to it, but I've reduced the bug to a package.json with these contents:

```
{
  "devDependencies": {
    "eslint": "^2.7.0"
  }
}
```

If you `npm install` in a directory containing this, a `node_modules` directory will be created. If you then run `npm init` and follow the prompts, the resulting package.json will have copied the devDependencies to dependencies, resulting in something like this:

```
{
  "devDependencies": {
    "eslint": "^2.7.0"
  },
  "name": "test2",
  "version": "1.0.0",
  "main": "index.js",
  "dependencies": {
    "eslint": "^2.7.0"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "description": ""
}
```

If you have NOT run `npm install` beforehand, or if you clobber the `node_modules` directory, the resulting package.json will NOT have the duplicated dependency:

```
{
  "devDependencies": {
    "eslint": "^2.7.0"
  },
  "name": "test2",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "description": ""
}
```

**Comment by addaleax** [comment]
https://github.com/npm/init-package-json/pull/61 should fix this.

**Comment by jokeyrhyme** [comment]
I came across this too, documented my findings here: https://github.com/jokeyrhyme/node-init.js/issues/96
