### ISSUE TITLE
Error in npm installed package.json? Bower works fine.

### ISSUE THREAD

**Issue by baasdesign** [npm/npm#12279]
NPM/Node throws an ENOENT error when installing dependencies for GruntJS in a nested node_modules folder with `npm install`.

I take these steps to create the error:

- `npm install pavilion`
- `cd node_modules/pavilion`
- `npm install`

When installing the dependencies for Grunt, listed in the package.json...it throws the error as seen below.
PS. please continue reading below. 

```
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.0.0
npm ERR! npm  v3.8.6
npm ERR! path /Users/Baasdesign/Desktop/test/node_modules/pavilion/node_modules/.staging/pavilion-8a19d0be
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/Users/Baasdesign/Desktop/test/node_modules/pavilion/node_modules/.staging/pavilion-8a19d0be' -> '/Users/Baasdesign/Desktop/test/node_modules/pavilion'
npm ERR! enoent ENOENT: no such file or directory, rename '/Users/Baasdesign/Desktop/test/node_modules/pavilion/node_modules/.staging/pavilion-8a19d0be' -> '/Users/Baasdesign/Desktop/test/node_modules/pavilion'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.0.0
npm ERR! npm  v3.8.6
npm ERR! path npm-debug.log.575049388
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'npm-debug.log.575049388'
npm ERR! enoent ENOENT: no such file or directory, open 'npm-debug.log.575049388'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Baasdesign/Desktop/test/node_modules/pavilion/npm-debug.log
```

Now the weird part. When I use Bower to install the package...I don't get the error. Here are my steps:

- `bower install pavilion`
- `cd bower_components/pavilion`
- `npm install`

Everything installs fine. The difference? ---> *the package.json.*
Bower gives me a clean package.json, as created by myself before publishing to npm.
NPM install gives me an package.json that had a lot more info in there. When I use the bower package.json...everything install fine...even when I paste and replace the npm package.json in the node_modules folder.

What's the deal here? It seems that the package.json delivered with the npm install messes up the dependency installation.

Here is the bower package.json delivery: 
http://pastebin.com/g8FgSDNG

And here is the npm package.json delivery:
http://pastebin.com/xTiQ15ih

sysinfo:
OSX Yosemite
node - 5.0.0
npm - 3.8.6

**Comment by baasdesign** [comment]
The problem was that I didn't save the dependency in the package.json.
I guess Node gets the paths wrong if you do that. 

So the correct workflow is:

 - `npm init` (create the package.json)
 - `npm install <package> --save-dev`
 - `cd node_modules/pavilion`
 - `npm install`

Then it works fine. The `<package>` needs to be added to the parent directory's package.json.

**Comment by iarna** [comment]
For the record, I get the following error with this scenario:
```
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.7.0
npm ERR! npm  v3.8.0

npm ERR! Cannot read property 'target' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Rebecca\xxx\node_modules\pavilion\npm-debug.log
```

**Comment by zkat** [comment]
This was fixed as of `npm@3.10.0`. I'm not sure which commit did it, but it's definitely that release that fixed it. Marking as fixed and closing!

**Comment by baasdesign** [comment]
Ok :) nice

**Comment by poperechnyi1** [comment]
I have a problem. What`s happened? I would like fix this error. How?
`D:\GULP\FIRST try\node_modules\.bin>npm install -g bower
npm ERR! not a package D:\GULP\FIRST try\node_modules\.bin\bower
npm ERR! addLocal Could not install D:\GULP\FIRST try\node_modules\.bin\bower
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "bower"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9
npm ERR! path C:\Users\STEPAN~1\AppData\Local\Temp\npm-224-9cb2b78b\unpack-f55148c48767\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\STEPAN~1\AppData\Local\Temp\npm-224-9cb2b78b\unpack-f55148c48767\package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     D:\GULP\FIRST try\node_modules\.bin\npm-debug.log

D:\GULP\FIRST try\node_modules\.bin>bower install jquery
bower                         EINVALID Name must be lowercase, can contain digits, dots, dashes, "@" or spaces`
