### ISSUE TITLE
activedirectory error

### ISSUE THREAD

**Issue by adelindobre** [npm/npm#12275]
I'm unable to install active directory:

The output of this command: "npm install activedirectory" is the next one:

```
npm ERR! node v4.4.2
npm ERR! npm  v3.8.6
npm ERR! code ENOSELF

npm ERR! Refusing to install activedirectory as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Adelin\Desktop\node-activedirectory\npm-debug.log
```

**Comment by KenanY** [comment]
@adelindobre Do you have a `package.json` in your current directory that has the `"name"` set to `"activedirectory"`?

**Comment by adelindobre** [comment]
Yes. Actually i"m trying to run this project https://github.com/gheeres/node-activedirectory which has a package.json with name set to activedirectory.

**Comment by KenanY** [comment]
@adelindobre Oh, then just run `npm install` inside that directory. By running `npm install activedirectory` you are trying to install the `activedirectory` module within the source code for the same module, which is not allowed (and usually makes no sense anyways).

**Comment by KenanY** [comment]
@adelindobre Are you still having this issue?
