### ISSUE TITLE
Extra peer dependencies are installed when shrinkwrap is present

### ISSUE THREAD

**Issue by robrichard** [npm/npm#12276]
Using npm 2.15.3

If I set up a project with three dependencies: 

``` json
  "dependencies": {
    "react": "^0.14.8",
    "react-bootstrap": "^0.28.5",
    "react-dom": "^0.14.8"
  }
```

Note that react-bootstrap@0.28.5 has a peer dependency on react >=0.14.0 and react-dom >=0.14.0.

Starting from an empty node_modules folder, running npm install will install these packages:

```
react-dom@0.14.8 node_modules/react-dom

react-bootstrap@0.28.5 node_modules/react-bootstrap
├── uncontrollable@3.2.3
├── classnames@2.2.3
├── react-prop-types@0.3.0
├── keycode@2.1.1
├── dom-helpers@2.4.0
├── react-overlays@0.6.3 (react-prop-types@0.2.2)
├── warning@2.1.0 (loose-envify@1.1.0)
├── invariant@2.2.1 (loose-envify@1.1.0)
├── lodash-compat@3.10.2
└── babel-runtime@5.8.38 (core-js@1.2.6)

react@0.14.8 node_modules/react
├── fbjs@0.6.1 (whatwg-fetch@0.9.0, ua-parser-js@0.7.10, loose-envify@1.1.0, promise@7.1.1, core-js@1.2.6)
└── envify@3.4.0 (through@2.3.8, jstransform@10.1.0)
```

So far so good. If I run `npm shrinkwrap`, a shrinkwrap file will be produced (attached). The shrinkwrap seems fine and matches what is currently installed.

Now if I remove `node_modules` and run `npm install` again (with the shrinkwrap present), the following packages are installed

```
react-dom@0.14.8 node_modules/react-dom

react@0.14.8 node_modules/react
├── envify@3.4.0 (through@2.3.8, jstransform@10.1.0)
└── fbjs@0.6.1 (whatwg-fetch@0.9.0, ua-parser-js@0.7.10, loose-envify@1.1.0, promise@7.1.1, core-js@1.2.6)

react-bootstrap@0.28.5 node_modules/react-bootstrap
├── uncontrollable@3.2.3
├── classnames@2.2.3
├── react-prop-types@0.3.0
├── keycode@2.1.1
├── dom-helpers@2.4.0
├── warning@2.1.0 (loose-envify@1.1.0)
├── invariant@2.2.1 (loose-envify@1.1.0)
├── lodash-compat@3.10.2
├── babel-runtime@5.8.38 (core-js@1.2.6)
├── react-dom@15.0.0
├── react@15.0.0 (object-assign@4.0.1, loose-envify@1.1.0, fbjs@0.8.0)
└── react-overlays@0.6.3 (react-prop-types@0.2.2)
```

Two versions of react and react-dom are installed (0.14.8 at the top level and 15.0.0 under react-bootstrap). This causes the application to break. Version 15.0.0 should not be installed at all. It is not present anywhere in the shrinkwrap file and react-bootstrap's peer dependency is satisfied by react 0.14.8. Shouldn't the shrinkwrap file ensure reliable installs? This set up would have worked up until react and react-dom 15.0.0 were published.

[npm-shrinkwrap.json.txt](https://github.com/npm/npm/files/210487/npm-shrinkwrap.json.txt)

**Comment by baens** [comment]
Made the exact same find, just [commented over here](https://github.com/npm/npm/issues/5135#issuecomment-207536617)

Seems to be a problem with the LTS version but not stable. Hope a fix can be put on LTS though.

**Comment by baens** [comment]
PR #12290 might be the fix here.

**Comment by majgis** [comment]
Please help with testing the fix if you can:

To install npm v2 with this fix:
```
npm i -g git+https://github.com/majgis/npm.git#366c0728a1a8865d265d5a9f06389fe0b5dd8183
```

To restore to the latest official version of npm v2:
```
npm i -g npm@2
```

Report your findings here:  https://github.com/npm/npm/pull/12290

**Comment by robrichard** [comment]
@majgis I tested my application with your branch and can confirm it fixes this issue.
