### ISSUE TITLE
npm install express create several folders in node_modules

### ISSUE THREAD

**Issue by marcoshmendes** [npm/npm#12273]
Hi, i'm starting with node and i have a question. When i got express by npm install some days ago, i could see express creates only one folder "express" inside node_modules. After updating my npm, when i install express, it creates a lot of folders inside node_modules, it looks disorganized. Is it my machine or it just change this way?
![folder](https://cloud.githubusercontent.com/assets/17493368/14382703/25ec3e32-fd66-11e5-903b-6e80f178e02d.PNG)

**Comment by ericmdantas** [comment]
That's the way it's supposed to work with npm 3~, where they folders are as flat as possible.

**Comment by marcoshmendes** [comment]
So, from now on it going to be this way? Several folders?

**Comment by ericmdantas** [comment]
Yup, see this: https://docs.npmjs.com/how-npm-works/npm3.

**Comment by marcoshmendes** [comment]
Thank you so much Eric, now i got it.
I read in post that when i want see my primary dependencies just run "npm ls --depth=0", that's really work and it's nice. Thank you again!

**Comment by ericmdantas** [comment]
You're welcome!

Could you please close the issue?

**Comment by marcoshmendes** [comment]
Yeah! See ya.

**Comment by wilsonmoraes** [comment]
just use : 
'npm install --legacy-bundling'
