### ISSUE TITLE
I just published a package autocjs, i need remove it an republish as an other user yaohaixiao

### ISSUE THREAD

**Issue by yaohaixiao** [npm/npm#12271]
the current user is autoc and  i want change an user as yaohaixiao and republished

**Comment by othiym23** [comment]
This isn't an issue with the npm CLI, which appears to be working as designed. You're going to need to raise this issue with the support team for whichever registry you're using. If it's the primary npm, Inc. registry, contact support@npmjs.com, and they'll help you out. If it's another registry, check their documentation. Thanks for your time!
