### ISSUE TITLE
Sign the version bump.

### ISSUE THREAD

**Issue by hemanth** [npm/npm#12288]
Now that Github allows to sign the commits with GPG keys, would it make sense for `npm version` to have a `-S` flag to sign the version bumps?

**Comment by KenanY** [comment]
Duplicate of https://github.com/npm/npm/issues/12696.

**Comment by hemanth** [comment]
@KenanY Ins't `12288 < 12696` ? 

Shouldn't the other issue be closed and marked as duplicate?

**Comment by KenanY** [comment]
@hemanth Whoops :)

**Comment by othiym23** [comment]
in general, the CLI team treats the version of an issue with the most discussion or supporting documentation as the "master" issue, rather than the first filed. That's not a hard and fast rule, tho – more important is keeping duplicates to a minimum when possible.

**Comment by hemanth** [comment]
@othiym23 Agree 👼
