### ISSUE TITLE
Recommended way to transform/change package.json during prepublish/prepublishOnly?

### ISSUE THREAD

**Issue by theoy** [npm/npm#12282]
Hi! I really love npm, and the excellent work that has gone into building a feature-rich, reliable package manager.

In addition, I've seen the excellent discussion in #10074 and related threads with regards to `prepublish` and `prepublishOnly`. However, I was wondering that the recommendation was from the npm team on the following `prepublishOnly` scenarios, that specifically relate to transforming data in the package.json:
1. **Automatic pre-release versioning**. Semver is great, but for my team at work, I'd love to make it so that people can create/distribute versioned packages for private testing, etc. Or it would be awesome to have them automatically generated by CI, etc, and then plopped somewhere for test use.
   
   One pretty natural way to do that is to do a generate a hash-based prerelease version, since private test forks of a component are non-linear in nature. I'd really like to avoid having a pattern that introduces commits every time a private version is generated. In addition `prepublishOnly` seems relevant/important, as it would be confusing/error-prone to edit the real `package.json` every time a dev is trying to just "build".
2. **Transforming of local `file:`-based dependencies** into something that is externally referenceable. `file:` dependencies are great at dev-time, especially with `npm link` or @timoxley's `linklocal` tool. In the case that you are publishing multiple packages in a batch though, it could be very cool to replace the `file:` based dependency references with some other equivalent reference identity. 
   
   I'm sure `bundledDependencies` could help here, but it's kind of a workaround if you really didn't intend for bundling. I'm guessing this is a much more involved feature to support (e.g. figuring out if users wanted to replace those dependencies with exact vs. `^` compat ranges, etc.)... however, I think this is a valuable scenario to invest some design thinking about. If anything, to help understand what is the best approach for a workaround.

So... thoughts would be appreciated :grin:. I'm also willing to contribute towards implementing something, but I figured some thing like this would necessitate a design discussion first.

**Comment by eddiemonge** [comment]
Why don't you use git commits to solve your first problem? Read the section titled **[npm install <git remote url>:](https://docs.npmjs.com/cli/install)** for usage.

I'm not really sure what you mean by your second point so I'm not going to answer about that.
