### ISSUE TITLE
npm error when installing build package in atom

### ISSUE THREAD

**Issue by l-gothberg** [npm/npm#12285]
I keep getting the following error when I try to install the "build" package (noseglid, ~78k downloads) in Atom.  Latest version of node.js installed.  Running via command line, both with and without sudo, has no effect; same error message.

Installing “build@0.59.0” failed.Hide output…

```
npm WARN addRemoteGit git+https://github.com/jeremyramin/term.js.git#de1635fc2695e7d8165012d3b1d007d7ce60eea2 resetting remote /Users/Leo/.atom/.apm/_git-remotes/https-github-com-jeremyramin-term-js-git-e93f5087 because of error: Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.
npm ERR! git clone --template=/Users/Leo/.atom/.apm/_git-remotes/_templates --mirror https://github.com/jeremyramin/term.js.git /Users/Leo/.atom/.apm/_git-remotes/https-github-com-jeremyramin-term-js-git-e93f5087: Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.
npm ERR! Darwin 15.4.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/Leo/.atom/.apm/.apmrc" "--userconfig" "/Users/Leo/.atom/.apmrc" "install" "/private/var/folders/n9/kj5bnnms3mv47hh420vlv17w0000gn/T/d-11638-23469-1e0r3lz/package.tgz" "--target=0.34.5" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code 69

npm ERR! Command failed: 
npm ERR! 
npm ERR! Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.
npm ERR! 
npm ERR! 
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/n9/kj5bnnms3mv47hh420vlv17w0000gn/T/apm-install-dir-11638-23469-1gzf5pe/npm-debug.log
```

**Comment by amandeepmittal** [comment]
Do you have shell commands installed in Atom? You need to have shell command installed. Also, try `npm cache clean`
then try installing the package with sudo command again!

**Comment by l-gothberg** [comment]
I feel kinda dumb actually.  While I did have xCode installed, I hadn't launched it since a recent system restore.  Once I did that (and accepted the accompanying license agreement) and retired installing the package, it worked fine.  Thanks for the suggestion though.

**Comment by amandeepmittal** [comment]
Actually, Xcode is necessary element for shell commands. Any IDE you use on MAC that supports and requires shell usage, Xcode is needed even though you don't use Xcode at all. It act as a bridge between the shell and the other applications that require shell commands.

**Comment by l-gothberg** [comment]
I know, but before the system allows Xcode to do its thing passing things back and forth, you have to launch it at least once and accept the terms.  Launched it, clicked accept, and then quit, and fixed.  It's annoying.

**Comment by amandeepmittal** [comment]
Ah, okay. Yeah, I forgot about the step of opening the Xcode & agreeing a license.
