### ISSUE TITLE
With preversion the updated version number is not printed

### ISSUE THREAD

**Issue by unional** [npm/npm#12284]
E.g.:
```js
{
  "script"; {
    "preversion": "npm test",
    "test": "echo test"
  }
}
```
```sh
npm version patch

> x@1.0.2 preversion E:\hwong\bitbucket\x
> npm test


> x@1.0.1 test E:\hwong\bitbucket\x
> echo test

test
/ |--------------------------------------------------------------------------------------------------------------------------------|
```

The normal `v1.0.2` is not printed at the end.

**Comment by busches** [comment]
Can you provide more details on this? For example, what version of `npm` and `node` you are/were using? Thanks.

**Comment by unional** [comment]
It was a while back, It was in 3.x for sure, but don't know what that version is now.

I test with 3.10.3 and it is working correctly now. So if you don't need to consider backporting, please close this issue.

Thanks,
Unional

**Comment by busches** [comment]
@KenanY can you close this?
