### ISSUE TITLE
Cordova installation error

### ISSUE THREAD

**Issue by alok1141** [npm/npm#12296]
When I am trying to install cordova through npm command line it is throwing following error: 
Please refer to the screenshot
![error](https://cloud.githubusercontent.com/assets/18376537/14409269/6d8c2b00-ff2b-11e5-9395-c2767818f79d.PNG)

**Comment by KenanY** [comment]
@alok1141 Have you tried `npm cache clean`?

**Comment by KenanY** [comment]
@alok1141 Have you tried my suggestion? Are you still having this issue?

**Comment by alok1141** [comment]
Yea, it's fine now

Thanks & Regards,
Alok Rai
+91-8600666742

**Comment by othiym23** [comment]
Closing as resolved. Thanks for your time!
