### ISSUE TITLE
npm ERR! Windows_NT 6.1.7601

### ISSUE THREAD

**Issue by kikyives** [npm/npm#12297]
npm ERR! argv "E:\\nodejs\\node.exe" "E:\\nodejs\\node_modules\\npm\\npm-cli.js" "install" "css-losder" "--save-dev"

Can someone come across this situation? Why would an error?

**Comment by KenanY** [comment]
@kikyives Providing one line of an entire error log is not very useful. Nonetheless, it looks like there's a typo, perhaps? You are typing `"css-losder"` instead of `"css-loader"`?

**Comment by KenanY** [comment]
@kikyives Are you still having this issue?

**Comment by othiym23** [comment]
Closing as abandoned. Open a new issue if you encounter this behavior again!

**Comment by kikyives** [comment]
@KenanY @othiym23 Sorry，Has been solved, is a network problem
