### ISSUE TITLE
(npm) shasum check failed 

### ISSUE THREAD

**Issue by Darwiish** [npm/npm#12299]
npm ERR! shasum check failed for /tmp/npm-3267-7088a2ef/registry.npmjs.org/bower/-/bower-1.7.9.tgz

Can someone please help me with this error?

**Comment by KenanY** [comment]
@Darwiish Have you tried `npm cache clean`?

**Comment by Darwiish** [comment]
@KenanY Yes I have tried it and also npm cache clear -f and still it didn't work.

**Comment by hw118118** [comment]
Did you solve the problem?I also get the problem

**Comment by Darwiish** [comment]
@hw118118 My bash file was messed up somehow . I got somebody to fix it,and it took him more than three hours.

**Comment by KenanY** [comment]
Closing as resolved then.
