### ISSUE TITLE
--ignore-scripts causes npm run <script> to exit successfully

### ISSUE THREAD

**Issue by dominictarr** [npm/npm#12294]
it's a obviously a contradiction to instruct npm to run a script but also tell it to ignore scripts,
This should probably print a warning to make the config conflict obvious, or possibly exit with an error.

if npm was more sensible about when it ran scripts then it there wouldn't be such a need for bandaids like "--ignore-scripts".

**Comment by tjconcept** [comment]
Just hit this as well. Completely unexpected that `ignore-scripts` will prevent me from *explicitly* running them with `npm run <script>` - given that command, I obviously want to run the script regardless.
I think npm should treat `ignore-scripts` like a default, in line with other global configuration, and allow it to be overriden on a case by case basis.
