### ISSUE TITLE
npm recompiles binary addons that I didn't ask it to install

### ISSUE THREAD

**Issue by dominictarr** [npm/npm#12293]
If I already have a binary addon installed, and I install another module, sometimes it rebuilds that module, even though I didn't ask it to do anything that is anything to do with that (!)

It's hard to say what causes this, but I see it often.

**Comment by dominictarr** [comment]
here is more details:
working in https://github.com/ssbc/scuttlebot and installing a different version of multiblob,
running `--loglevel info` shows that npm is messing around with chloridedown.

```
$ npm install multiblob@1.8 --loglevel info
npm info it worked if it ends with ok
npm info using npm@3.6.0
npm info using node@v5.6.0
npm info lifecycle chloridedown@1.0.22~preinstall: chloridedown@1.0.22
npm info lifecycle chloride@2.1.1~preinstall: chloride@2.1.1
npm info linkStuff chloridedown@1.0.22
npm info linkStuff chloride@2.1.1
npm info lifecycle chloridedown@1.0.22~install: chloridedown@1.0.22
npm info lifecycle chloride@2.1.1~install: chloride@2.1.1
npm info lifecycle chloridedown@1.0.22~postinstall: chloridedown@1.0.22
npm info lifecycle chloride@2.1.1~postinstall: chloride@2.1.1
```

multiblob does not depend on chloride, so why would npm be touching chloridedown?

Also: if I try doing `npm install multiblob --ignore-scripts` npm _still_ does something to chloridedown so that now the bindings I had previously built do not work. compiling everytime makes npm take much longer than it needs to.

**Comment by dominictarr** [comment]
another great candidate for [--literally](https://github.com/npm/npm/issues/9721)

**Comment by dominictarr** [comment]
@othiym23 I notice that you tagged this as feature request, but it's really a bug fix.

**Comment by dominictarr** [comment]
to reproduce:

```
mkdir test_dir
cd test_dir
npm init --yes
#install module with binary addons
npm install leveldown
```
that installs and runs the build scripts etc, everything is normal so far
now, install a normal module (without binary deps)
```
npm install pull-stream
```
it _also_ runs the post-install step for `leveldown`.
this is relatively benign with leveldown because it uses pre-gyp so the build step is fast,
if you install `chloridedown

**Comment by dominictarr** [comment]
note: it only does this if you _directly_ install the binary addon, if you install a module which depends on the binary addon but does not have it's own build step the addon's buildstep won't run.

**Comment by busches** [comment]
Is this still happening with the latest npm 3?
