### ISSUE TITLE
Support Q => images not showing up on README.md once it hits the NPM site

### ISSUE THREAD

**Issue by ORESoftware** [npm/npm#12302]
see this question

http://stackoverflow.com/questions/36537836/image-wont-show-up-on-npm-but-shows-up-on-github

=> any idea why markdown images would display properly on Github but not on NPM?

I looked at the network history once I loaded the page on NPM and the http request for the image is a 200, so something's up, thanks

**Comment by ehsalazar** [comment]
@ORESoftware what happens if you change the logo url to:
```
https://raw.githubusercontent.com/ORESoftware/suman/master/images/suman.png
```
If it doesn't work, reach out us at support@npmjs.com and we'll see if we can help.

**Comment by othiym23** [comment]
This is an issue with npm's web site, so since this repo is only for the CLI, I'm going to close it. You probably want to resend this to support@npmjs.com, where @ehsalazar, who already weighed in here, will take care of you. Thanks for your time!

**Comment by bcherny** [comment]
Hey guys, was there a resolution here? I have this problem for many of my repos. It would be nice if the way NPM resolved images was compatible with the way Github does it.

External badges and images from the repo sometimes show up, and sometimes they don't. Is this some sort of caching issue?

Positive example (all images show up fine): https://www.npmjs.com/package/babydux
Negative example (should have build badge, etc.): https://www.npmjs.com/package/json-schema-to-typescript
