### ISSUE TITLE
unpublish: error 400 

### ISSUE THREAD

**Issue by iiiyx** [npm/npm#12308]
Please help. I can't unpublish project.
```
[root@iiiyxep node_modules]# npm unpublish nodebb-plugin-sirius --force
npm WARN using --force I sure hope you know what you are doing.
npm ERR! Linux 2.6.32-042stab113.17
npm ERR! argv "/root/.nvm/v4.4.2/bin/node" "/root/.nvm/v4.4.2/bin/npm" "unpublish" "nodebb-plugin-sirius" "--force"
npm ERR! node v4.4.2
npm ERR! npm  v2.15.0
npm ERR! code E400

npm ERR! Registry returned 400 for DELETE on https://registry.npmjs.org/nodebb-plugin-sirius/-rev/9-d2119643615d6583c2da2dfbe1d3e214
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/talks/node_modules/npm-debug.log

```

**Comment by aldendaniels** [comment]
Same issue here

**Comment by Raathigesh** [comment]
You can not unpublish the module directly now. There were changed made to the[ unpublish policy ](http://blog.npmjs.org/post/141905368000/changes-to-npms-unpublish-policy)after the [this ](https://medium.com/@azerbike/i-ve-just-liberated-my-modules-9045c06be67c)incident.

You have to contact npm (support@npmjs.com) to get the module unpublished.

**Comment by KenanY** [comment]
I'm gonna close this since @Raathigesh is right, you gotta contact that email if you want to unpublish things that are older than 24 hours.
