### ISSUE TITLE
Cross-platform environmental variables within scripts

### ISSUE THREAD

**Issue by brettz9** [npm/npm#12300]
While `npm config` nicely allows the user to override `config` defaults from `package.json` in a platform-independent manner, unless one is retrieving the variable from within a Node script, one apparently has no way to readily utilize these variables within `scripts` in a cross-platform manner.

It is essential, imv, to have a way to retrieve environmental variables within `scripts` in a cross-platform manner so that `scripts` (e.g., those which call binaries that accept arguments but do not themselves check env. variables set by `npm`) will work out-of-the-box with such configuration regardless of platform.

If implemented so as to actually set the OS' genuine env. variables, this would also benefit the somewhat different but also common use case described in the closed issue #2800.

This is not asking for something like a cross-platform wrapper for all OS commands (as nice as that would be). The idea is merely for using environmental variables within the `scripts` facility that is provided presumably for convenience. I see no reason that the workarounds that exist should be required for such a very frequent and very basic need.

**Comment by edmorley** [comment]
Please can this feature request be reopened?

**Comment by edmorley** [comment]
Ping for reopening?

**Comment by csentis** [comment]
Same here...

**Comment by chyzwar** [comment]
We should collect related issues and create a new issue.
