### ISSUE TITLE
Error 403 while trying to publish a new npm module

### ISSUE THREAD

**Issue by dkamit** [npm/npm#12307]
Hi,

This is my first npm module I am publishing to npm registry. I googled about the error and didn't find the root cause of the problem.
Following is the console error 

```
➜  fs-more git:(master) ✗ npm publish
npm ERR! publish Failed PUT 403
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "publish"
npm ERR! node v0.12.2
npm ERR! npm  v2.11.1
npm ERR! code E403

npm ERR! you do not have permission to publish "fs-more". Are you logged in as the correct user? : fs-more
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/amith/experiments/fs-more/npm-debug.log
```

**Are you logged in as the correct user? : fs-more** I dont know why npm is trying to login as fs-more

```
➜  fs-more git:(master) ✗ npm whoami
dkamit
➜  fs-more git:(master) ✗
```

npm whoami retured correctly as dkamit please help me :)

I have attached the debug log as well.

Thanks
Amith

[npm-debug.txt](https://github.com/npm/npm/files/212853/npm-debug.txt)

**Comment by KenanY** [comment]
@dkamit The `"fs-more"` module name is [already taken](https://www.npmjs.com/package/fs-more).

**Comment by KenanY** [comment]
@dkamit Have you resolved this issue?

**Comment by othiym23** [comment]
Closing as abandoned. Open a new issue if you encounter this behavior again!

**Comment by ghost** [comment]
Hi, I'm having the same issue! I've read your suggestions and changed the name of the module but still encounter the same error. Please help

**Comment by hxkuan** [comment]
The  module need  a uniqueness of name，so I am ok
