### ISSUE TITLE
missing script: start

### ISSUE THREAD

**Issue by pmukanova** [npm/npm#12301]
ERR Instance (index 0) failed to start accepting connections

**Comment by KenanY** [comment]
@pmukanova Not enough information provided. Is there a `npm-debug.log` file that you can upload as a [gist](https://gist.github.com/) and link here?

**Comment by mayankOM** [comment]
Hi,

I have same error arose.
Please check in your "package.json" file.

Here, main file is server.js. 
So, by writing "npm start" command. First of all server.js file execute.

"main": "./server.js",

Then after it will need "scripts" to start the node environment. For that i had put "scripts" element in package json file

"scripts": {
    "start": "node ./bin/www"
}

It is working fine for me.!

Hope it will help you. :)

**Comment by KenanY** [comment]
@pmukanova Are you still facing this issue? If so, can you provide the information I requested?

**Comment by othiym23** [comment]
Closing as abandoned.
