### ISSUE TITLE
I can't understand peerinvalid's error mesasge

### ISSUE THREAD

**Issue by ldct** [npm/npm#12303]
I'm getting this error when running `npm install`

```
npm ERR! peerinvalid The package react@15.0.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-overlays@0.5.4 wants react@>=0.14.0
npm ERR! peerinvalid Peer uncontrollable@3.2.1 wants react@>=0.11.0
npm ERR! peerinvalid Peer react-dom@0.14.8 wants react@^0.14.8
```

However we're explicitly depending on `react 0.14.7` and `react-dom 0.14.7` - why would npm try to install `react-dom 0.14.8` or `react 15.0.1`?

**Comment by RavenHursT** [comment]
@zodiac I just came across this just now.. same situation as you.  We had `react-async-script-loader@^0.2.0` and `react@^0.14.0` in our `package.json`..

Problem was that recently updated their `package.json` to be `react@^15.0.1` and so that error is saying "react-async-script-loader wants 15.0.1 but all these other packages want 0.14.x"

The change was made in `react-async-script-loader@0.2.1` so we just took the `^` out of our `package.json` to force the previous version.

So one of your deps may have updated to `react@15.0.x`.. so just make sure you're either forcing those packages back to the previous versions, or else update to `15.0.x`

**Comment by zodiac** [comment]
@RavenHursT I'll check if that is the case. If it is, I think npm should name the package (react-async-script-loader) causing it to try to use `react 15.0.1`

**Comment by RavenHursT** [comment]
@zodiac I completely agree.. it did list it in mine.. don't know what your dep tree is though :-(

**Comment by zgalvin111** [comment]
I am gettting this error when I run 'npm install'. I am on a mac and ive tried to uninstall npm and node and I can't get anything to work. These dependancies are not listed in the package.json and so I'm not sure where i can edit them. What else can I do?

'''javascript
error code EPEERINVALID
error peerinvalid The package @angular/compiler@2.1.0 does not satisfy its siblings' peerDependencies requirements!
error peerinvalid Peer @angular/compiler-cli@0.6.4 wants @angular/compiler@2.0.2
error peerinvalid Peer @angular/platform-browser-dynamic@2.1.0 wants @angular/compiler@2.1.0
error peerinvalid Peer @angular/platform-server@2.1.0 wants @angular/compiler@2.1.0
'''

**Comment by Dameng0803** [comment]
Any one help? I got same error ...

**Comment by legodude17** [comment]
Try running `npm install @angular/compiler@2.0.2`. Does the error go away?

**Comment by Dameng0803** [comment]
@legodude17 : sry, mate, it does not work ...

**Comment by Dameng0803** [comment]
Actually, my error is caused when I try to install react-scroll-effects package, and the error occurred, and I have no clue how to resolve it ...

**Comment by Dameng0803** [comment]
npm WARN package.json react-webpack-rails-tutorial@0.0.1 No repository field.
npm WARN package.json react-webpack-rails-tutorial@0.0.1 No README data
npm WARN package.json react-webpack-rails-tutorial@0.0.1 No license field.
npm WARN peerDependencies The peer dependency react@^0.13.2 included from react-scroll-effects will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "react-scroll-effects" "--save"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react@15.3.2 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-dom@15.3.2 wants react@^15.3.2
npm ERR! peerinvalid Peer react-on-rails@6.1.2 wants react@>= 0.14
npm ERR! peerinvalid Peer react-scroll-effects@1.0.9 wants react@^0.13.2

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/damonwu/damengworks/DamonPortfolio/client/npm-debug.log

**Comment by legodude17** [comment]
What do you think @KenanY?

**Comment by legodude17** [comment]
I am stumped. What is you package.json @Dameng0803?

**Comment by Dameng0803** [comment]
"version": "0.0.1",
  "engines": {
    "node": "5.10.0",
    "npm": "3.5.0"
  },
  "scripts": {
    "build:test": "webpack --config webpack.config.js",
    "build:production": "NODE_ENV=production webpack --config webpack.config.js",
    "build:development": "webpack -w --config webpack.config.js"
  },
  "cacheDirectories": [
    "node_modules",
    "client/node_modules"
  ],
  "dependencies": {
    "babel": "^6.5.2",
    "babel-cli": "^6.6.5",
    "babel-core": "^6.7.4",
    "babel-loader": "^6.2.4",
    "babel-polyfill": "^6.7.4",
    "babel-preset-es2015": "^6.6.0",
    "babel-preset-react": "^6.5.0",
    "babel-preset-stage-0": "^6.5.0",
    "babel-runtime": "^6.6.1",
    "es5-shim": "^4.5.7",
    "expose-loader": "^0.7.1",
    "glob": "^7.1.1",
    "imports-loader": "^0.6.5",
    "react": "^15.3.2",
    "react-dom": "^0.14.8 || ^15.0.0",
    "react-magic-effects": "^0.1.0",
    "react-on-rails": "6.1.2",
    "react-scroll": "^1.4.4",
    "react-scroll-effects": "^1.0.9",
    "webpack": "^1.12.14"
  },
  "peerDependencies": {
    "react": ">= 0.13",
    "react-dom": ">= 0.13",
    "babel-runtime": ">= 6"
  },
  "devDependencies": {}

**Comment by Dameng0803** [comment]
@legodude17 : I have reinstalled my node and npm, and now it looks like this 

react-webpack-rails-tutorial@0.0.1 /Users/damonwu/damengworks/DamonPortfolio/client
├── UNMET PEER DEPENDENCY react@15.3.2 extraneous
└── react-scroll-effects@1.0.9

npm WARN react-scroll-effects@1.0.9 requires a peer of react@^0.13.2 but none was installed.
npm WARN react-webpack-rails-tutorial@0.0.1 No description
npm WARN react-webpack-rails-tutorial@0.0.1 No repository field.
npm WARN react-webpack-rails-tutorial@0.0.1 No license field.

**Comment by legodude17** [comment]
To resolve this just run `npm install react@0.13.2`.

**Comment by Dameng0803** [comment]
@legodude17 : I have already tried this solution, but it comes with other errors:

react-dom@15.3.2 requires a peer of react@^15.3.2 but none was installed.

I think this might be a conflict between these two versions ...

**Comment by legodude17** [comment]
Yeah. I think you might just have to bug the author of `react-scroll-effects` to update their `react` dependency. I think this is no longer an `npm` issue.

**Comment by Dameng0803** [comment]
thx for help @legodude17

**Comment by legodude17** [comment]
Anyone still having this issue?

**Comment by junibrosas** [comment]
I have encountered this issue. The installation worked on my Mac but not when I tried installing it on Windows.

**Comment by legodude17** [comment]
Is it also the `react-scroll-effects` package? If it is then use the same advice I game to @Dameng0803.

**Comment by AlokJoshi** [comment]
Hi Friends
I am getting the following error. Can you please help?

C:\WS\graphql-blog-schema>npm install
(node:7052) fs: re-evaluating native module sources is not supported. If you are
 using the graceful-fs module, please update it to a more recent version.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher
 to avoid a RegExp DoS issue
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Alok\\AppData\\R
oaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.9.1
npm ERR! npm  v2.11.2
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react does not satisfy its siblings' peerDepend
encies requirements!
npm ERR! peerinvalid Peer graphiql@0.3.1 wants react@^0.13 || ^0.14.0-beta
npm ERR! peerinvalid Peer react-dom@0.14.8 wants react@^0.14.8

npm ERR! Please include the following file with any support request:
npm ERR!     C:\WS\graphql-blog-schema\npm-debug.log

I am using npm version 2.11.2 and node version v6.9.1 and Windows 7

Thanks.

**Comment by legodude17** [comment]
@AlokJoshi, you should file an issue with `graphiql` and `react-dom` to upgrade their `react` versions. Also, please update `npm` to the latest version.

**Comment by legodude17** [comment]
@othiym23, what is the `needs-discussion` label for? I think that the error message might want to be updated.

**Comment by AlokJoshi** [comment]
@legodude17 Thank you very much for your response.
