### ISSUE TITLE
Unable to install strongloop on Windows 7

### ISSUE THREAD

**Issue by Midhuntcs** [npm/npm#12305]
Hi,

I am trying to install strongloop using the command "npm install strongloop". My node version is 4.4.2 and npm version is 2.15.0. On trying to install strongloop I am getting below error ;

```
C:\Windows\System32>npm install strongloop
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "strongloop"
npm ERR! node v4.4.2
npm ERR! npm  v2.15.0
npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! syscall getaddrinfo

npm ERR! getaddrinfo EAI_AGAIN registry.npmjs.org:443
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Windows\System32\npm-debug.log
```

---

Kindly help me to resolve the issue.

**Comment by amandeepmittal** [comment]
Do you use a proxy? If yes, please check your proxy settings/configuration.

**Comment by tushar962** [comment]
Can some help what am I supposed to do in here? I'm facing the same issue. I saw this link http://digitaldrummerj.me/proxy-configurations/ but I still wasn' able to install bower

**Comment by vasyland** [comment]
StrongLoop requires Windows 8.
https://loopback.io/doc/en/lb3/LoopBack-FAQ.html
