### ISSUE TITLE
Many Errors during npm installation process

### ISSUE THREAD

**Issue by ivan3177** [npm/npm#12316]
Have web project which require use of npm. Installed lates version of npm and nodejs, run npm install in my project directory but got a lot of errors. 
Any ideas what might be wrong?
npm debug log is included to this message.

https://gist.github.com/othiym23/48ba02f19868112580856c1b47a2bec6

**Comment by KenanY** [comment]
@ivan3177 `npm@1.3` is no longer supported. Please try [upgrading](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm).

**Comment by othiym23** [comment]
@KenanY is correct – `npm@1` is no longer supported by the CLI team, and you should either upgrade npm, as he suggests, or go ahead and [install a newer distribution of Node](https://github.com/nodesource/distributions). Either way, as this is an issue with an unsupported version of the CLI, I'm going to close this issue. Thanks for your time, and good luck getting everything sorted out!
