### ISSUE TITLE
npm update fails whe npm is executed from the module folder

### ISSUE THREAD

**Issue by markjose** [npm/npm#12317]
cd ./node_modules/<my-npm-module>

npm update --verbose <my-npm-module>
- npm info it worked if it ends with ok
- npm verb cli [ 'C:\Program Files\nodejs\node.exe',
- npm verb cli   'C:\Users\***********\npm\node_modules\npm\bin\npm-cli.js',
- npm verb cli   'update',
- npm verb cli   '--verbose',
- npm verb cli   '<my-npm-module>' ]
- npm info using npm@3.8.6
- npm info using node@v4.4.2
- npm verb exit [ 0, true ]
- npm info ok

Verbose logging shows success, however package is not updated

cd .. (back out)

npm update <my-npm-module> <-- this now works as expected

My package name above has been replaced with <my-npm-module> but does not include < or > characters.

os = Windows 10

**Comment by othiym23** [comment]
What does `npm outdated` return when run in that same module folder?

**Comment by markjose** [comment]
$ npm outdated
Package               Current  Wanted  Latest  Location
babel-core            MISSING   6.7.2   6.7.6  my-module-name
babel-preset-es2015   MISSING   6.6.0   6.6.0  my-module-name
babel-preset-stage-0  MISSING   6.5.0   6.5.0  my-module-name
node-fetch            MISSING   1.5.0   1.5.0  my-module-name

It's also worth mentioning that I'm pulling from a git repo using git+ssh rather than a package.
