### ISSUE TITLE
sudo npm install nativescript -g --unsafe-perm  :command not working correctly.

### ISSUE THREAD

**Issue by Deepak1711** [npm/npm#12326]
Posting the output of the command and tns command is also not working.

npm http GET https://registry.npmjs.org/center-align
npm http GET https://registry.npmjs.org/right-align
npm http GET https://registry.npmjs.org/wordwrap/0.0.2
npm http 304 https://registry.npmjs.org/commander
npm http 304 https://registry.npmjs.org/cli-color/0.3.2
npm http GET https://registry.npmjs.org/d
npm http GET https://registry.npmjs.org/es5-ext
npm http GET https://registry.npmjs.org/memoizee
npm http GET https://registry.npmjs.org/timers-ext
npm http 304 https://registry.npmjs.org/connect
npm http 304 https://registry.npmjs.org/broccoli-read-compat
npm http 304 https://registry.npmjs.org/copy-dereference
npm http GET https://registry.npmjs.org/rsvp
npm http GET https://registry.npmjs.org/lodash-node
npm http 304 https://registry.npmjs.org/handlebars
npm http 304 https://registry.npmjs.org/findup-sync
npm http 304 https://registry.npmjs.org/rimraf
npm http 304 https://registry.npmjs.org/mime
npm http 304 https://registry.npmjs.org/promise-map-series
npm http 304 https://registry.npmjs.org/quick-temp
npm http 304 https://registry.npmjs.org/ansi-regex
npm http 304 https://registry.npmjs.org/cli-width
npm http 304 https://registry.npmjs.org/broccoli-kitchen-sink-helpers
npm http 304 https://registry.npmjs.org/pegjs/0.6.2
npm http 304 https://registry.npmjs.org/figures
npm http 304 https://registry.npmjs.org/rsvp
npm http 304 https://registry.npmjs.org/readline2
npm http 304 https://registry.npmjs.org/broccoli-slow-trees
npm http 304 https://registry.npmjs.org/run-async
npm http GET https://registry.npmjs.org/glob
npm http GET https://registry.npmjs.org/underscore.string
npm http GET https://registry.npmjs.org/mktemp
npm http GET https://registry.npmjs.org/glob
npm http GET https://registry.npmjs.org/glob
npm http 304 https://registry.npmjs.org/rx-lite
npm http GET https://registry.npmjs.org/graceful-readlink
npm http GET https://registry.npmjs.org/finalhandler/0.4.1
npm http GET https://registry.npmjs.org/parseurl
npm http GET https://registry.npmjs.org/utils-merge/1.0.0
npm http 304 https://registry.npmjs.org/through
npm http GET https://registry.npmjs.org/mute-stream/0.0.4
npm http GET https://registry.npmjs.org/strip-ansi
npm http GET https://registry.npmjs.org/once
npm http 304 https://registry.npmjs.org/options
npm http 304 https://registry.npmjs.org/ultron
npm http GET https://registry.npmjs.org/optimist
npm http GET https://registry.npmjs.org/uglify-js
npm http GET https://registry.npmjs.org/source-map
npm http 304 https://registry.npmjs.org/node-uuid/1.3.3
npm http 304 https://registry.npmjs.org/lodash/3.2.0
npm http GET https://registry.npmjs.org/lodash/-/lodash-3.2.0.tgz
npm http 304 https://registry.npmjs.org/colors/0.6.2
npm http 304 https://registry.npmjs.org/base64-js/0.0.6
npm http 304 https://registry.npmjs.org/xmlbuilder/2.2.1
npm http 304 https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/core-util-is
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/util-deprecate/1.0.0
npm http GET https://registry.npmjs.org/lodash-node
npm http 304 https://registry.npmjs.org/isarray
npm http 304 https://registry.npmjs.org/bindings
npm http 304 https://registry.npmjs.org/bindings
npm http GET https://registry.npmjs.org/ms/0.7.1

> utf-8-validate@1.0.1 install /usr/local/lib/node_modules/nativescript/node_modules/utf-8-validate
> node ./build.js

npm http 304 https://registry.npmjs.org/string_decoder
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm http 304 https://registry.npmjs.org/process-nextick-args

> nativescript@1.7.1 preuninstall /usr/local/lib/node_modules/nativescript
> node preuninstall.js

npm WARN continuing anyway undefined
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! Error: ENOENT, chown '/usr/local/lib/node_modules/nativescript/node_modules/bufferutil/node_modules/prebuilt/.npmignore'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.2.0-35-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "nativescript" "-g" "--unsafe-perm"
npm ERR! cwd /home/deepak
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /usr/local/lib/node_modules/nativescript/node_modules/bufferutil/node_modules/prebuilt/.npmignore
npm ERR! fstream_path /usr/local/lib/node_modules/nativescript/node_modules/bufferutil/node_modules/prebuilt/.npmignore
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! fstream_finish_call chown
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:305:19
npm ERR! fstream_stack /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! error rolling back Error: ENOTEMPTY, rmdir '/usr/local/lib/node_modules/nativescript/node_modules/bufferutil/node_modules/nan'
npm ERR! error rolling back  nativescript@1.7.1 { [Error: ENOTEMPTY, rmdir '/usr/local/lib/node_modules/nativescript/node_modules/bufferutil/node_modules/nan']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/nativescript/node_modules/bufferutil/node_modules/nan' }
npm ERR! weird error 1
npm http 304 https://registry.npmjs.org/util-deprecate
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/semver
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/nativescript/node_modules/bufferutil/node_modules/bindings/README.md'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.2.0-35-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "nativescript" "-g" "--unsafe-perm"
npm ERR! cwd /home/deepak
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /usr/local/lib/node_modules/nativescript/node_modules/bufferutil/node_modules/bindings/README.md
npm ERR! fstream_path /usr/local/lib/node_modules/nativescript/node_modules/bufferutil/node_modules/bindings/README.md
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm http 304 https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/express
npm http 304 https://registry.npmjs.org/underscore/1.8.2
npm http 304 https://registry.npmjs.org/glob
npm http 304 https://registry.npmjs.org/opener
npm http 304 https://registry.npmjs.org/rc
npm http 304 https://registry.npmjs.org/which
npm http 304 https://registry.npmjs.org/strong-data-uri
npm http 304 https://registry.npmjs.org/object-keys
npm http 304 https://registry.npmjs.org/isarray/0.0.1
npm http 304 https://registry.npmjs.org/bindings
npm http 304 https://registry.npmjs.org/yargs
npm http 200 https://registry.npmjs.org/lodash/-/lodash-3.2.0.tgz
npm http 304 https://registry.npmjs.org/lodash.keys
npm http GET https://registry.npmjs.org/deep-extend
npm http GET https://registry.npmjs.org/ini
npm http GET https://registry.npmjs.org/truncate
npm http GET https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/tinycolor
npm http GET https://registry.npmjs.org/parseurl/1.0.1
npm http GET https://registry.npmjs.org/accepts/1.0.0
npm http GET https://registry.npmjs.org/range-parser/1.0.0
npm http GET https://registry.npmjs.org/type-is/1.0.0
npm http GET https://registry.npmjs.org/cookie/0.1.0
npm http GET https://registry.npmjs.org/buffer-crc32/0.2.1
npm http 304 https://registry.npmjs.org/lodash._baseassign
npm http GET https://registry.npmjs.org/methods/0.1.0
npm http GET https://registry.npmjs.org/fresh/0.2.2
npm http GET https://registry.npmjs.org/send/0.2.0
npm http GET https://registry.npmjs.org/cookie-signature/1.0.3
npm http GET https://registry.npmjs.org/merge-descriptors/0.0.2
npm http GET https://registry.npmjs.org/escape-html/1.0.1
npm http GET https://registry.npmjs.org/qs/0.6.6
npm http GET https://registry.npmjs.org/serve-static/1.0.1
npm http GET https://registry.npmjs.org/path-to-regexp/0.1.2
npm http 304 https://registry.npmjs.org/lodash._createassigner
npm http GET https://registry.npmjs.org/lodash._basecopy
npm http GET https://registry.npmjs.org/lodash._bindcallback
npm http GET https://registry.npmjs.org/lodash._isiterateecall
npm http GET https://registry.npmjs.org/lodash.restparam
npm http GET https://registry.npmjs.org/lodash._getnative
npm http GET https://registry.npmjs.org/lodash.isarguments
npm http GET https://registry.npmjs.org/lodash.isarray
npm http 304 https://registry.npmjs.org/deep-equal
npm ERR! tar.unpack error reading /home/deepak/tmp/npm-4504-enJemeDM/1460494428655-0.510400959989056/tmp.tgz
npm http 304 https://registry.npmjs.org/base64-js/0.0.8
npm http 304 https://registry.npmjs.org/ansicolors
npm http 304 https://registry.npmjs.org/lodash
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm http 304 https://registry.npmjs.org/glob
npm http 304 https://registry.npmjs.org/util-deprecate/1.0.2
npm http 304 https://registry.npmjs.org/redeyed
npm http 304 https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/lru-cache
npm http GET https://registry.npmjs.org/sigmund
npm http GET https://registry.npmjs.org/graceful-fs
npm http GET https://registry.npmjs.org/esprima-fb
npm http 304 https://registry.npmjs.org/balanced-match
npm http 304 https://registry.npmjs.org/defaults
npm http 304 https://registry.npmjs.org/concat-map/0.0.1
npm http GET https://registry.npmjs.org/clone
npm ERR! tar.unpack error reading /home/deepak/tmp/npm-4504-enJemeDM/1460494429299-0.7435443580616266/tmp.tgz
npm http 304 https://registry.npmjs.org/end-of-stream
npm http 304 https://registry.npmjs.org/xmlbuilder/4.0.0
npm http 304 https://registry.npmjs.org/user-home
npm http 304 https://registry.npmjs.org/array-differ
npm http 304 https://registry.npmjs.org/array-uniq
npm http 304 https://registry.npmjs.org/dateformat
npm http 304 https://registry.npmjs.org/sequencify
npm http 304 https://registry.npmjs.org/stream-consume
npm http GET https://registry.npmjs.org/once
npm http 304 https://registry.npmjs.org/beeper
npm http 304 https://registry.npmjs.org/fancy-log
npm http 304 https://registry.npmjs.org/gulplog
npm http 304 https://registry.npmjs.org/has-gulplog
npm http 304 https://registry.npmjs.org/lodash._reescape
npm http 304 https://registry.npmjs.org/lodash._reevaluate
npm http 304 https://registry.npmjs.org/glob-stream
npm http 304 https://registry.npmjs.org/lodash._reinterpolate
npm http 304 https://registry.npmjs.org/lodash.template
npm http 304 https://registry.npmjs.org/graceful-fs
npm http 304 https://registry.npmjs.org/multipipe
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm http 304 https://registry.npmjs.org/strip-bom
npm http 304 https://registry.npmjs.org/object-assign
npm http 304 https://registry.npmjs.org/replace-ext/0.0.1
npm http 304 https://registry.npmjs.org/vinyl
npm http 304 https://registry.npmjs.org/vinyl
npm http 304 https://registry.npmjs.org/extend
npm http GET https://registry.npmjs.org/sparkles
npm http GET https://registry.npmjs.org/chalk
npm http GET https://registry.npmjs.org/time-stamp
npm http GET https://registry.npmjs.org/glogg
npm http GET https://registry.npmjs.org/lodash._basetostring
npm http GET https://registry.npmjs.org/lodash._basevalues
npm http GET https://registry.npmjs.org/lodash.escape
npm http GET https://registry.npmjs.org/lodash.templatesettings
npm http GET https://registry.npmjs.org/duplexer2/0.0.2
npm http GET https://registry.npmjs.org/clone
npm http GET https://registry.npmjs.org/clone-stats
npm http GET https://registry.npmjs.org/get-stdin
npm http GET https://registry.npmjs.org/meow
npm http 304 https://registry.npmjs.org/findup-sync
npm http 304 https://registry.npmjs.org/glob-watcher
npm http 304 https://registry.npmjs.org/resolve
npm http GET https://registry.npmjs.org/ordered-read-streams
npm http GET https://registry.npmjs.org/first-chunk-stream
npm http GET https://registry.npmjs.org/is-utf8
npm http GET https://registry.npmjs.org/unique-stream
npm http GET https://registry.npmjs.org/glob2base
npm http GET https://registry.npmjs.org/readable-stream
npm http GET https://registry.npmjs.org/xtend
npm http GET https://registry.npmjs.org/clone
npm http 304 https://registry.npmjs.org/flagged-respawn
npm http 304 https://registry.npmjs.org/center-align
npm http 304 https://registry.npmjs.org/rechoir
npm http 304 https://registry.npmjs.org/right-align
npm http 304 https://registry.npmjs.org/wordwrap/0.0.2
npm http GET https://registry.npmjs.org/align-text
npm http GET https://registry.npmjs.org/align-text
npm http GET https://registry.npmjs.org/lazy-cache
npm http GET https://registry.npmjs.org/inflight
npm http GET https://registry.npmjs.org/path-is-absolute
npm http 304 https://registry.npmjs.org/rsvp
npm http 304 https://registry.npmjs.org/es5-ext
npm http 304 https://registry.npmjs.org/d
npm http 304 https://registry.npmjs.org/glob
npm http 304 https://registry.npmjs.org/underscore.string
npm http 304 https://registry.npmjs.org/glob
npm http 304 https://registry.npmjs.org/timers-ext
npm http 304 https://registry.npmjs.org/memoizee
npm http 304 https://registry.npmjs.org/glob
npm http GET https://registry.npmjs.org/next-tick
npm http GET https://registry.npmjs.org/es6-weak-map
npm http GET https://registry.npmjs.org/event-emitter
npm http GET https://registry.npmjs.org/lru-queue
npm http 304 https://registry.npmjs.org/graceful-readlink
npm http 304 https://registry.npmjs.org/lodash-node
npm WARN deprecated lodash-node@2.4.1: This package has been discontinued in favor of lodash@^4.0.0.
npm http 304 https://registry.npmjs.org/finalhandler/0.4.1
npm http 304 https://registry.npmjs.org/parseurl
npm http 304 https://registry.npmjs.org/utils-merge/1.0.0
npm http GET https://registry.npmjs.org/unpipe
npm http GET https://registry.npmjs.org/escape-html
npm http GET https://registry.npmjs.org/on-finished
npm http 304 https://registry.npmjs.org/strip-ansi
npm http 304 https://registry.npmjs.org/once
npm http GET https://registry.npmjs.org/wrappy
npm http 304 https://registry.npmjs.org/mute-stream/0.0.4
npm http 304 https://registry.npmjs.org/mktemp
npm http 304 https://registry.npmjs.org/optimist
npm http 304 https://registry.npmjs.org/uglify-js
npm http GET https://registry.npmjs.org/es6-iterator
npm http GET https://registry.npmjs.org/es6-symbol
npm http 304 https://registry.npmjs.org/lodash-node
npm http 304 https://registry.npmjs.org/ms/0.7.1
npm http 304 https://registry.npmjs.org/source-map
npm http 304 https://registry.npmjs.org/ini
npm http GET https://registry.npmjs.org/wordwrap
npm http GET https://registry.npmjs.org/minimist
npm http 304 https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/amdefine
npm http 304 https://registry.npmjs.org/deep-extend
npm http 304 https://registry.npmjs.org/parseurl/1.0.1
npm http 304 https://registry.npmjs.org/accepts/1.0.0
npm http 304 https://registry.npmjs.org/range-parser/1.0.0
npm http 304 https://registry.npmjs.org/truncate
npm http 304 https://registry.npmjs.org/tinycolor

> ws@0.4.32 install /usr/local/lib/node_modules/nativescript/node_modules/node-inspector/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

npm http 304 https://registry.npmjs.org/type-is/1.0.0
npm ERR! tar.unpack error reading /home/deepak/tmp/npm-4504-enJemeDM/1460494429298-0.9883693219162524/tmp.tgz
npm http 304 https://registry.npmjs.org/cookie/0.1.0
npm http 304 https://registry.npmjs.org/fresh/0.2.2
npm http 304 https://registry.npmjs.org/buffer-crc32/0.2.1
npm http 304 https://registry.npmjs.org/methods/0.1.0
npm http 304 https://registry.npmjs.org/escape-html/1.0.1
npm http 304 https://registry.npmjs.org/send/0.2.0
npm http 304 https://registry.npmjs.org/qs/0.6.6
npm http 304 https://registry.npmjs.org/merge-descriptors/0.0.2
npm http 304 https://registry.npmjs.org/serve-static/1.0.1
npm http 304 https://registry.npmjs.org/lodash._basecopy
npm http 304 https://registry.npmjs.org/cookie-signature/1.0.3
npm http 304 https://registry.npmjs.org/lodash._bindcallback
npm http 304 https://registry.npmjs.org/lodash._isiterateecall
npm http 304 https://registry.npmjs.org/lodash.restparam
npm http 304 https://registry.npmjs.org/lodash._getnative
npm http 304 https://registry.npmjs.org/lodash.isarguments
npm http 304 https://registry.npmjs.org/lodash.isarray
npm http 304 https://registry.npmjs.org/lru-cache
npm http 304 https://registry.npmjs.org/sigmund
npm http 304 https://registry.npmjs.org/graceful-fs
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm http 304 https://registry.npmjs.org/clone
npm http 304 https://registry.npmjs.org/once
npm http 304 https://registry.npmjs.org/path-to-regexp/0.1.2
npm http 304 https://registry.npmjs.org/esprima-fb
npm http 304 https://registry.npmjs.org/sparkles
npm http GET https://registry.npmjs.org/mime
npm http GET https://registry.npmjs.org/send/0.1.4
npm http GET https://registry.npmjs.org/mime
npm http GET https://registry.npmjs.org/negotiator
npm http 304 https://registry.npmjs.org/chalk
npm http 304 https://registry.npmjs.org/glogg
npm http 304 https://registry.npmjs.org/lodash._basetostring
npm http 304 https://registry.npmjs.org/lodash._basevalues
npm http 304 https://registry.npmjs.org/lodash.escape
npm http 304 https://registry.npmjs.org/lodash.templatesettings
npm http GET https://registry.npmjs.org/lodash._root
npm http 304 https://registry.npmjs.org/duplexer2/0.0.2
npm http GET https://registry.npmjs.org/readable-stream
npm http 304 https://registry.npmjs.org/clone
npm http 304 https://registry.npmjs.org/clone-stats
npm http 304 https://registry.npmjs.org/meow
npm http 304 https://registry.npmjs.org/ordered-read-streams
npm http 304 https://registry.npmjs.org/first-chunk-stream
npm http 304 https://registry.npmjs.org/time-stamp
npm http GET https://registry.npmjs.org/ansi-styles
npm http GET https://registry.npmjs.org/escape-string-regexp
npm http GET https://registry.npmjs.org/has-ansi
npm http GET https://registry.npmjs.org/supports-color
npm http 304 https://registry.npmjs.org/is-utf8
npm http 304 https://registry.npmjs.org/unique-stream
npm http 304 https://registry.npmjs.org/readable-stream
npm http 304 https://registry.npmjs.org/xtend
npm http 304 https://registry.npmjs.org/clone
npm http GET https://registry.npmjs.org/core-util-is
npm http GET https://registry.npmjs.org/isarray/0.0.1
npm http GET https://registry.npmjs.org/string_decoder
npm http GET https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/align-text
npm http GET https://registry.npmjs.org/kind-of
npm http GET https://registry.npmjs.org/longest
npm http GET https://registry.npmjs.org/repeat-string
npm http 304 https://registry.npmjs.org/align-text
npm http 304 https://registry.npmjs.org/glob2base
npm http GET https://registry.npmjs.org/find-index
npm http 304 https://registry.npmjs.org/get-stdin
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/camelcase-keys
npm http GET https://registry.npmjs.org/decamelize
npm http GET https://registry.npmjs.org/loud-rejection
npm http GET https://registry.npmjs.org/map-obj
npm http GET https://registry.npmjs.org/normalize-package-data
npm http GET https://registry.npmjs.org/read-pkg-up
npm http GET https://registry.npmjs.org/redent
npm http GET https://registry.npmjs.org/trim-newlines
npm http 304 https://registry.npmjs.org/inflight
npm http 304 https://registry.npmjs.org/path-is-absolute
npm http 304 https://registry.npmjs.org/next-tick
npm http 304 https://registry.npmjs.org/unpipe
npm http 304 https://registry.npmjs.org/event-emitter
npm http 304 https://registry.npmjs.org/lru-queue
npm http 304 https://registry.npmjs.org/escape-html
npm http 304 https://registry.npmjs.org/lazy-cache
npm http 304 https://registry.npmjs.org/on-finished
npm http GET https://registry.npmjs.org/ee-first/1.1.1
npm http 304 https://registry.npmjs.org/wrappy
npm http 304 https://registry.npmjs.org/es6-symbol
npm http 304 https://registry.npmjs.org/wordwrap
npm http 304 https://registry.npmjs.org/es6-weak-map
npm http GET https://registry.npmjs.org/es6-iterator
npm http 304 https://registry.npmjs.org/amdefine
npm http 304 https://registry.npmjs.org/mime
npm http 304 https://registry.npmjs.org/mime
npm http 304 https://registry.npmjs.org/lodash._root
npm http 304 https://registry.npmjs.org/es6-iterator
npm http 304 https://registry.npmjs.org/minimist
npm http 304 https://registry.npmjs.org/readable-stream
npm http 304 https://registry.npmjs.org/ansi-styles
npm http 304 https://registry.npmjs.org/escape-string-regexp
npm http 304 https://registry.npmjs.org/has-ansi
npm http 304 https://registry.npmjs.org/negotiator
npm http 304 https://registry.npmjs.org/send/0.1.4
npm http GET https://registry.npmjs.org/range-parser/0.0.4
npm http GET https://registry.npmjs.org/fresh/0.2.0
npm http 304 https://registry.npmjs.org/supports-color
npm http 304 https://registry.npmjs.org/core-util-is
npm http GET https://registry.npmjs.org/ansi-regex
npm http 304 https://registry.npmjs.org/isarray/0.0.1
npm http 304 https://registry.npmjs.org/string_decoder
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/longest
npm http 304 https://registry.npmjs.org/repeat-string
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/kind-of
npm http GET https://registry.npmjs.org/is-buffer
npm http 304 https://registry.npmjs.org/camelcase-keys
npm http 304 https://registry.npmjs.org/find-index
npm http 304 https://registry.npmjs.org/decamelize
npm http 304 https://registry.npmjs.org/loud-rejection
npm http 304 https://registry.npmjs.org/map-obj
npm http 304 https://registry.npmjs.org/normalize-package-data
npm http 304 https://registry.npmjs.org/read-pkg-up
npm http 304 https://registry.npmjs.org/redent
npm http 304 https://registry.npmjs.org/trim-newlines
npm http 304 https://registry.npmjs.org/ee-first/1.1.1
npm http GET https://registry.npmjs.org/camelcase
npm http GET https://registry.npmjs.org/indent-string
npm http GET https://registry.npmjs.org/strip-indent
npm http GET https://registry.npmjs.org/find-up
npm http GET https://registry.npmjs.org/read-pkg
npm http GET https://registry.npmjs.org/array-find-index
npm http GET https://registry.npmjs.org/signal-exit
npm http GET https://registry.npmjs.org/hosted-git-info
npm http GET https://registry.npmjs.org/is-builtin-module
npm http GET https://registry.npmjs.org/validate-npm-package-license
npm http 304 https://registry.npmjs.org/es6-iterator
npm http 304 https://registry.npmjs.org/ansi-regex
npm http 304 https://registry.npmjs.org/is-buffer
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"v0.10.25","npm":"1.3.10"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"v0.10.25","npm":"1.3.10"})
npm http 304 https://registry.npmjs.org/camelcase
npm http 304 https://registry.npmjs.org/fresh/0.2.0
npm http 304 https://registry.npmjs.org/indent-string
npm http 304 https://registry.npmjs.org/strip-indent
npm http GET https://registry.npmjs.org/repeating
npm http 304 https://registry.npmjs.org/find-up
npm http 304 https://registry.npmjs.org/read-pkg
npm http GET https://registry.npmjs.org/load-json-file
npm http GET https://registry.npmjs.org/path-type
npm http GET https://registry.npmjs.org/path-exists
npm http GET https://registry.npmjs.org/pinkie-promise
npm http 304 https://registry.npmjs.org/array-find-index
npm http 304 https://registry.npmjs.org/signal-exit
npm http 304 https://registry.npmjs.org/hosted-git-info
npm http 304 https://registry.npmjs.org/is-builtin-module
npm http 304 https://registry.npmjs.org/range-parser/0.0.4
npm http 304 https://registry.npmjs.org/validate-npm-package-license
npm http GET https://registry.npmjs.org/builtin-modules
npm http 304 https://registry.npmjs.org/repeating
npm http GET https://registry.npmjs.org/spdx-correct
npm http GET https://registry.npmjs.org/spdx-expression-parse
npm http GET https://registry.npmjs.org/is-finite
npm http 304 https://registry.npmjs.org/load-json-file
npm http 304 https://registry.npmjs.org/path-type
npm http GET https://registry.npmjs.org/pify
npm http GET https://registry.npmjs.org/parse-json
npm http 304 https://registry.npmjs.org/path-exists
npm http GET https://registry.npmjs.org/strip-bom
npm http 304 https://registry.npmjs.org/pinkie-promise
npm http GET https://registry.npmjs.org/pinkie
npm http 304 https://registry.npmjs.org/builtin-modules
npm http 304 https://registry.npmjs.org/spdx-correct
npm http 304 https://registry.npmjs.org/spdx-expression-parse
npm http GET https://registry.npmjs.org/spdx-license-ids
npm http GET https://registry.npmjs.org/spdx-exceptions
npm http GET https://registry.npmjs.org/spdx-license-ids
npm http 304 https://registry.npmjs.org/is-finite
npm http GET https://registry.npmjs.org/number-is-nan
npm http 304 https://registry.npmjs.org/pify
npm http 304 https://registry.npmjs.org/parse-json
npm http 304 https://registry.npmjs.org/strip-bom
npm http 304 https://registry.npmjs.org/pinkie
npm http 304 https://registry.npmjs.org/spdx-license-ids
npm http GET https://registry.npmjs.org/error-ex
npm http 304 https://registry.npmjs.org/spdx-exceptions
npm http 304 https://registry.npmjs.org/spdx-license-ids
npm http 304 https://registry.npmjs.org/number-is-nan
npm http 304 https://registry.npmjs.org/error-ex
npm http GET https://registry.npmjs.org/is-arrayish
npm http 304 https://registry.npmjs.org/is-arrayish

> ref@1.1.3 install /usr/local/lib/node_modules/nativescript/node_modules/ref
> node ./build.js

npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/deepak/npm-debug.log
npm ERR! not ok code 0

**Comment by Deepak1711** [comment]
Output for $ tns doctor:

No command 'tns' found, did you mean:
 Command 'tls' from package 'python-tlslite' (universe)
 Command 'tnb' from package 'pvm-examples' (universe)
 Command 'ts' from package 'moreutils' (universe)
 Command 'tcs' from package 'tcs' (universe)
 Command 'tqs' from package 'ssake' (universe)
 Command 'nns' from package 'tcllib' (universe)
 Command 'ns' from package 'ns2' (universe)
 Command 'trs' from package 'konwert' (main)
tns: command not found

**Comment by KenanY** [comment]
@Deepak1711 Did you read the file mentioned in the error message?:

```
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
```

**Comment by Deepak1711** [comment]
Following is ths content of README.Debian file

nodejs for Debian
=================

packaged modules
----------------

The global search path for modules is
/usr/lib/nodejs

Future packages of node modules will use that directory,
so it should be used wisely.


user modules
------------

Node looks for modules in ./node_modules directory first;
please read node#modules documentation carefully for more information.

Node does not look for modules in /usr/local/lib/node_modules,
where npm put them.
Please read npm-link(1) of npm package, to understand how to properly
use npm-installed modules in a project.

Note that require.paths is not supported in future node versions.
See also node(1) for more information about NODE_PATH.


nodejs command
--------------

The upstream name for the Node.js interpreter command is "node".
In Debian the interpreter command has been changed to "nodejs".

This was done to prevent a namespace collision: other commands use
the same name in their upstreams, such as ax25-node from the "node"
package.

Scripts calling Node.js as a shell command must be changed to instead
use the "nodejs" command.

**Comment by KenanY** [comment]
@Deepak1711 Are you still seeing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
