### ISSUE TITLE
Unable to install latest of sub-dependency using npm 3 and dedup

### ISSUE THREAD

**Issue by destroyerofbuilds** [npm/npm#12323]
The focus of my issue is on updating the dependency of one of my dependencies.

What I have is a project that depends on a semantic version of package A. Package A depends on package B using `dist-tag` `latest`. 

Package B is published with new minor releases on a very regular basis.

My expectation is that I should be able to run `npm install` at the root of my project and package B will be updated to the latest version.

It's quite easy to verify that this works if package B is a direct dependency of my project, and I'm using `latest` as the version.

In this scenario, after B is installed via it's inclusion in my project's `package.json` file, I replace it with an older version: `npm install B@x.y.z`

`npm install` reports that the package is `extraneous`.

I then run `npm install`. Package B is now updated to the latest published version.

This also works in my earlier scenario if I turn of dedup using the `--legacy-bundling` flag.

`npm` version 3 only fails to install the latest version of package B when dedup is enabled. In that case package B is moved to the top level `node_modules/` directory, even though it's a dependency of A.

If it matters, I ran into this issue why working with private scoped packages.

**Comment by zkat** [comment]
I'm really not sure what the bug is, here.

Judging purely by your issue, the reason you're seeing `extraneous` is likely because you forgot to save your spec after doing `npm install B@x.y.z`.

If you want transitive dependencies to be updated, though, you can do three things that together. I think, will solve this specific scenarios:

1. In the package A `package.json`, set the package B dependency to point to `^3` or whatever the semver-major version you want to track is. That will match the newest available version between `3.0.0` and `4.0.0` (non-inclusive)

2. In your toplevel package, install things as usual -- then run `npm update` any time you want `package B` to be updated. That will pull in whatever the latest version of package B is, as long as it doesn't go beyond 4.0.

3. Any time you want to set a "minimum viable" version for package B, go into `package A` and set the semver range accordingly. The `^` will match anything between that version and the next semver-major version (unless your package isn't at v1.0.0 yet, because semantics there are different and all I can say is please just tag 1.0)

I believe this will solve your problem, as far as I understand from your description. If I missed the mark, it would be nice if you could show what problem you're having using a minimal example project that I can look at.

**Comment by destroyerofbuilds** [comment]
@zkat I'm sorry my original explanation lacked sufficient details.

I've put together the following example to demonstrate how to reproduce the issue we're experiencing.

If you feel any points in this reproducer are problematic, please let me know and I can work on improving the fidelity of the example.

Before conducting this test, I upgrade my `npm` installation - `npm install --global npm@latest`

```bash
$ npm --version
4.5.0
```

I created a package called `middle-package`.

`middle-package` has one production dependency. That production dependency is, for the sake of a name, `@example/data`. (The actual package is an internal one to our company, so the name is left out here, but the contents of that package is a single JSON metadata file that is updated on a very regular basis)

The contents of `package.json` for `middle-package` is now:

```bash
$ cat package.json
```

```json
{
  "name": "middle-package",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@example/data": ">=0.0.0"
  }
}
```

> Please note that `@example/data` is using `>=` semantic range syntax. `@example/data` is published using only minor versions, so as of today, the version of `@example/data` is `0.1859.0`. To consume the latest minor we have used `*`, `latest`, and `>=`. This reproducer behaves the same regardless of the range chosen. Since only minor versions are published, using `^` would not work in this situation. To my knowledge, only the ranges `*`, `latest`, and `>=`, would work for the purpose of saying I want the most recent version.

I then created a package called `my-app`. `my-app` is a front-end application that depends on `middle-package` as a development dependency.

The contents of `package.json` for `my-app` is now:

```bash
$ cat package.json
```

```json
{
  "name": "my-app",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "middle-package": "file:///C:\\Users\\hbetts\\Workspace\\middle-package"
  }
}
```

From `my-app`, I have the following dependency tree:

```bash
$ npm ls
my-app@1.0.0 C:\Users\hbetts\Workspace\my-app
`-- middle-package@1.0.0
  `-- @example/data@0.1859.0
    +-- lodash@2.4.2
    `-- semver@5.1.1
```

```bash
$ ls node_modules/
@example  lodash  middle-package  semver
```

The next step is to forcibly downgrade `@example/data` within `my-app` to create the scenario.

```bash
$ npm install @example/data@0.1518.0
my-app@1.0.0 C:\Users\hbetts\Workspace\my-app
`-- middle-package@1.0.0
  `-- @example/data@0.1518.0
```

```bash
$ npm ls
my-app@1.0.0 C:\Users\hbetts\Workspace\my-app
`-- middle-package@1.0.0
  `-- @example/data@0.1518.0
    +-- lodash@2.4.2
    `-- semver@5.1.1
```

```bash
$ cat /c/Users/hbetts/Workspace/my-app/node_modules/\@example/data/package.json | grep version
  "version": "0.1518.0"
```

Lastly, I run `npm install`, with the expectation that `@example/data` will be updated to the latest version.

```bash
$ npm install
npm WARN my-app@1.0.0 No description
npm WARN my-app@1.0.0 No repository field.

$ npm ls
my-app@1.0.0 C:\Users\hbetts\Workspace\my-app
`-- middle-package@1.0.0
  `-- @example/data@0.1518.0
    +-- lodash@2.4.2
    `-- semver@5.1.1


$ cat /c/Users/hbetts/Workspace/my-app/node_modules/\@example/data/package.json | grep version
  "version": "0.1518.0"
```

I also tried `npm update`.

```bash
$ npm update

$ npm ls
my-app@1.0.0 C:\Users\hbetts\Workspace\my-app
`-- middle-package@1.0.0
  `-- @example/data@0.1518.0
    +-- lodash@2.4.2
    `-- semver@5.1.1

hbetts@hbettspc MINGW32 ~/Workspace/my-app
$ cat /c/Users/hbetts/Workspace/my-app/node_modules/\@example/data/package.json | grep version
  "version": "0.1518.0"
```

---

> The ^ will match anything between that version and the next semver-major version (unless your package isn't at v1.0.0 yet, because semantics there are different and all I can say is please just tag 1.0)

^ So, you are entirely correct. We are on major version zero, publishing only minor versions off of `0`.

**Comment by destroyerofbuilds** [comment]
> In the package A package.json, set the package B dependency to point to ^3 or whatever the semver-major version you want to track is. That will match the newest available version between 3.0.0 and 4.0.0 (non-inclusive)

I did try replacing the `>=0.0.0` range within `middle-package` with `>=0` to simulate the suggestion, but neither `npm install`, nor `npm update`, from with `my-app`, would update the `@example/data` package.

**Comment by zkat** [comment]
@destroyerofbuilds 

* `npm install` will not update already-installed packages. To get it to bump versions like this, you would need to remove `node_modules` first.

* `npm update` defaults to `--depth=0`. That is, it will only update toplevel packages. To have it update transitive dependencies, increase the depth level (probably just do `--depth=9999`.

**Comment by destroyerofbuilds** [comment]
Thank you @zkat.

Using the scenario I provided above, I was able to confirm `npm_config_depth=9999 npm update` updated the transitive `@example/data` package.

I'm closing this issue out as the current behavior is intended, and a work around for transitive dependencies exists.
