### ISSUE TITLE
npm prune traverses symlinked packages and causes problems

### ISSUE THREAD

**Issue by ffxsam** [npm/npm#12327]
In a project, I've got a symlink of material-ui:

```
$ npm link material-ui
```

When I do an `npm prune` in my project folder, I noticed it goes into the `node_modules/material-ui` symlinked folder and removes packages there as well. I'm guessing it probably shouldn't do that, as it causes a breaking state in my app. I have to go back into my material-ui folder and run `npm i`.

**Comment by busches** [comment]
Can you provide more information, such as the version of npm/node you're using to replicate this error? Thanks
