### ISSUE TITLE
npm ERR! Windows_NT 6.1.7601

### ISSUE THREAD

**Issue by Ib467** [npm/npm#12325]
Indi@Indi-HP MINGW64 /c/wamp/www/abcFile/React
$ npm install gulp
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "gulp"
npm ERR! node v5.6.0
npm ERR! npm  v2.15.0

npm ERR! Invalid version: "1.0"
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\wamp\www\abcFile/React\npm-debug.log

This is the error i am getting when trying to install gulp in the project folder. Cannot seem to install any packages are this time. Please help with any suggestions. thank you

**Comment by KenanY** [comment]
@Ib467 The `"version"` attribute in your `package.json` is not valid [semver](http://semver.org/spec/v2.0.0.html). It must be valid semver, [as documented](https://docs.npmjs.com/files/package.json#version). Try setting it to `"1.0.0"` for example.

**Comment by Ib467** [comment]
set the version to "1.0.0" still the error comes for Windows_NT 6.1.7601

**Comment by KenanY** [comment]
@Ib467 Can I see `/c/wamp/www/abcFile/React/package.json`?

**Comment by KenanY** [comment]
@Ib467 Are you still having this issue?

**Comment by Hetachi** [comment]
This issue is caused when you try to install react in a folder named React / react and if you used npm init and skipped all steps.

To fix this error all you have to do is rename project into something else than "React" or "react" in package.json
