### ISSUE TITLE
Ubuntu 16.04 Webpack Problem

### ISSUE THREAD

**Issue by WebRuin** [npm/npm#12322]
I was able to install Webpack globaly with `sudo npm install webpack -g`.  However when I try to install webpack locally in my project with `sudo npm i webpack -D` or `sudo npm install webpack --save-dev` I get:

`npm ERR! Linux 4.4.0-18-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/local/bin/npm" "install" "webpack" "-D"
npm ERR! node v4.2.6
npm ERR! npm  v3.8.6
npm ERR! code ENOSELF

npm ERR! Refusing to install webpack as a dependency of itself
`

Is this a known issue?  I have to install all npm packages with sudo on my Ubuntu box.  I now of npm "sudo fixes" for mac but not Ubuntu

**Comment by WebRuin** [comment]
https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md helped

**Comment by KenanY** [comment]
@WebRuin Is your project named `"webpack"` by any chance?

**Comment by WebRuin** [comment]
https://github.com/webpack/webpack

**Comment by WebRuin** [comment]
I am still having trouble installing it localy

**Comment by KenanY** [comment]
@WebRuin Are you trying to run `npm install webpack` in a directory which contains the source code for webpack? Can you provide your project's `package.json` (at least let me see the `"name"` thing). More information is required.

**Comment by KenanY** [comment]
@WebRuin Are you still experiencing this issue?
