### ISSUE TITLE
My node is running grunt task

### ISSUE THREAD

**Issue by kamiaslam** [npm/npm#12320]
```
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3

npm ERR! Invalid name: "Javelin JLS"
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kamiaslam/Documents/_project/JLS/javelin-living-styleguide/npm-debug.log
```

**Comment by KenanY** [comment]
@kamiaslam Spaces and capital letters are not permitted in package names.

**Comment by kamiaslam** [comment]
Thanks KenanY, I have changed that but still no luck :(

**Comment by KenanY** [comment]
@kamiaslam Same error? Different error? Is there a `npm-debug.log` file you can upload to [gist.github.com](https://gist.github.com/) and link here?

**Comment by KenanY** [comment]
@kamiaslam Are you still seeing any issues with `npm`? If so, could you please provide a `npm-debug.log`?

**Comment by KenanY** [comment]
Closing as abandoned.
