### ISSUE TITLE
I got below error while installing serial port on beagle bone black.

### ISSUE THREAD

**Issue by kapdivyang** [npm/npm#12334]
Error log is as below.

root@beaglebone:~# npm install -g serialport*
npm http GET https://registry.npmjs.org/serialport*
npm http GET https://registry.npmjs.org/serialport*
npm http GET https://registry.npmjs.org/serialport*
npm ERR! Error: getaddrinfo ENOTFOUND
npm ERR!     at errnoException (dns.js:37:11)
npm ERR!     at Object.onanswer [as oncomplete] (dns.js:124:16)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.8.13
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "-g" "serialport*"
npm ERR! cwd /home/root
npm ERR! node -v v0.8.22
npm ERR! npm -v 1.2.14
npm ERR! syscall getaddrinfo
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/root/npm-debug.log
npm ERR! not ok code 0

**Comment by busches** [comment]
@kapdivyang you have an extra `*` at the end of the install command. You cannot pass a wildcard to `npm install <package>` to my knowledge. At least it's not working in the latest `npm@3`.

cc\ @KenanY

**Comment by KenanY** [comment]
Gonna close per @busches's comment. Also `npm@1.2` is years old and is no longer supported.
