### ISSUE TITLE
Error when run "npm install"

### ISSUE THREAD

**Issue by autn** [npm/npm#12330]
When I run "sudo npm install", I get this error: `npm ERR! EPROTO: protocol error, symlink ...`
My debug log:

> 43167 warn optional Skipping failed optional dependency /chokidar/fsevents:
> 43168 warn notsup Not compatible with your operating system or architecture: fsevents@1.0.11
> 43169 warn angular2-quickstart@1.0.0 No description
> 43170 warn angular2-quickstart@1.0.0 No repository field.
> 43171 verbose stack Error: EPROTO: protocol error, symlink '../semver/bin/semver' -> '/var/www/html/gcl-fe/node_modules/agent-base/node_modules/.bin/semver'
> 43171 verbose stack     at Error (native)
> 43172 verbose cwd /var/www/html/gcl-fe
> 43173 error Linux 3.13.0-85-generic
> 43174 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
> 43175 error node v5.10.1
> 43176 error npm  v3.8.3
> 43177 error path ../semver/bin/semver
> 43178 error code EPROTO
> 43179 error errno -71
> 43180 error syscall symlink
> 43181 error EPROTO: protocol error, symlink '../semver/bin/semver' -> '/var/www/html/gcl-fe/node_modules/agent-base/node_modules/.bin/semver'
> 43182 error If you need help, you may report this error at:
> 43182 error     https://github.com/npm/npm/issues
> 43183 verbose exit [ -71, true ]

When I run "sudo npm start", I get this error:

> angular2-quickstart@1.0.0 start /var/www/html/gcl-fe
> tsc && concurrently "npm run tsc:w" "npm run lite"
> sh: 1: tsc: not found
> npm ERR! Linux 3.13.0-85-generic
> npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
> npm ERR! node v5.10.1
> npm ERR! npm  v3.8.3
> npm ERR! file sh
> npm ERR! code ELIFECYCLE
> npm ERR! errno ENOENT
> npm ERR! syscall spawn
> npm ERR! angular2-quickstart@1.0.0 start: `tsc && concurrently "npm run tsc:w" "npm run lite"`
> npm ERR! spawn ENOENT
> npm ERR!
> npm ERR! Failed at the angular2-quickstart@1.0.0 start script 'tsc && concurrently "npm run tsc:w" "npm run lite" '.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the angular2-quickstart package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     tsc && concurrently "npm run tsc:w" "npm run lite"
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs angular2-quickstart
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls angular2-quickstart
> npm ERR! There is likely additional logging output above.
> npm ERR! Please include the following file with any support request:
> npm ERR!     /var/www/html/gcl-fe/npm-debug.log

**Comment by MarkPieszak** [comment]
Same issue as mine: #12412 

More specifically it's an issue where `tsc` is being ran in npm scripts. Your title is extremely vague.
