### ISSUE TITLE
npm ERR! Linux 3.13.0-74-generic (MEANJS)

### ISSUE THREAD

**Issue by AbdullahElamir** [npm/npm#12337]
Error: Command failed: cd mean && npm install
npm ERR! Linux 3.13.0-74-generic
npm ERR! argv "/usr/bin/nodejs" "/home/abdullah/.node/bin/npm" "install"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.7

npm ERR! shasum check failed for /tmp/npm-3701-dbdfbcd8/registry.npmjs.org/bower/-/bower-1.7.9.tgz
npm ERR! Expected: b7296c2393e0d75edaa6ca39648132dd255812b0
npm ERR! Actual:   4f4ee8d715e488bfbe9fd3cd3d72bd838fd73fa4
npm ERR! From:     https://registry.npmjs.org/bower/-/bower-1.7.9.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /media/sda2/meanwhile/mean/npm-debug.log

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)

**Comment by KenanY** [comment]
@AbdullahElamir Have you tried `npm cache clean`?

**Comment by KenanY** [comment]
@AbdullahElamir Are you still encountering this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
