### ISSUE TITLE
'npm install' creating 'node_modules' directory in a directory that does not contain `package.json`

### ISSUE THREAD

**Issue by kuncevic** [npm/npm#12332]
`npm install` creating `node_modules` directory whatever you have `package.json` in current directory or not. If you do not have `package.json` in a directory means there is no npm modules to install so no need to create `node_modules` directory.

So basically if you just run `npm install` it is always creating `node_modules` directory which should not be a case. `node_modules` should be created only if `package.json` exists and if there anything in `devDependencies` or `dependencies`.

It is not a critical thing at all but may be you can look at it once you have a time.

**Comment by KenanY** [comment]
Duplicate of https://github.com/npm/npm/issues/11967.

**Comment by othiym23** [comment]
Closing as duplicate of #11967.
