### ISSUE TITLE
npm i webpack -S command is not working 

### ISSUE THREAD

**Issue by maryamjamil** [npm/npm#12348]
When i m using this command I am finding these errors:

![2](https://cloud.githubusercontent.com/assets/5530298/14520305/2f49c928-023d-11e6-9bb1-660a08ae2f91.png)

**Comment by KenanY** [comment]
@maryamjamil Looks like you are behind a proxy. Ensure that you have configured `npm` to use your proxy by setting the relevant configuration settings: `proxy`, `https-proxy`, and `cafile`.

**Comment by maryamjamil** [comment]
how to set these configuration settings ??

**Comment by KenanY** [comment]
@maryamjamil Try `npm config set` :) documentation: https://docs.npmjs.com/cli/config#set

**Comment by maryamjamil** [comment]
what sdhould i set in my .npmrc file to get correct values

**Comment by maryamjamil** [comment]
![12](https://cloud.githubusercontent.com/assets/5530298/14538252/519ea406-0294-11e6-91a8-cfdf23c3e1f9.png)
This is the error i am currently facing
