### ISSUE TITLE
could not install terminal-plus 

### ISSUE THREAD

**Issue by pscpraveen** [npm/npm#12344]
it give the following error message while installing 

Installing “terminal-plus@0.14.5” failed.Hide output…

```
npm WARN addRemoteGit Error: Command failed: 
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:658:15)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:98:17)
npm WARN addRemoteGit     at maybeClose (child_process.js:766:16)
npm WARN addRemoteGit     at Socket.<anonymous> (child_process.js:979:11)
npm WARN addRemoteGit     at Socket.emit (events.js:95:17)
npm WARN addRemoteGit     at Pipe.close (net.js:466:12)
npm WARN addRemoteGit  git+https://github.com/jeremyramin/term.js.git resetting remote C:\Users\Praveen Kumar\.atom\.apm\_git-remotes\https-github-com-jeremyramin-term-js-git-7be5884d because of error: { [Error: Command failed: ] killed: false, code: -1073741502, signal: null }
npm WARN addRemoteGit Error: Command failed: 
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:658:15)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:98:17)
npm WARN addRemoteGit     at maybeClose (child_process.js:766:16)
npm WARN addRemoteGit     at Socket.<anonymous> (child_process.js:979:11)
npm WARN addRemoteGit     at Socket.emit (events.js:95:17)
npm WARN addRemoteGit     at Pipe.close (net.js:466:12)
npm WARN addRemoteGit  git+https://github.com/jeremyramin/pty.js.git#28f2667 resetting remote C:\Users\Praveen Kumar\.atom\.apm\_git-remotes\https-github-com-jeremyramin-pty-js-git-9387efda because of error: { [Error: Command failed: ] killed: false, code: -1073741502, signal: null }
npm ERR! git clone --template=C:\Users\Praveen Kumar\.atom\.apm\_git-remotes\_templates --mirror https://github.com/jeremyramin/term.js.git C:\Users\Praveen Kumar\.atom\.apm\_git-remotes\https-github-com-jeremyramin-term-js-git-7be5884d: error launching git: The paging file is too small for this operation to complete.
npm ERR! git clone --template=C:\Users\Praveen Kumar\.atom\.apm\_git-remotes\_templates --mirror https://github.com/jeremyramin/pty.js.git C:\Users\Praveen Kumar\.atom\.apm\_git-remotes\https-github-com-jeremyramin-pty-js-git-9387efda: 
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\Praveen Kumar\\AppData\\Local\\atom\\app-1.6.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Praveen Kumar\\AppData\\Local\\atom\\app-1.6.2\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Praveen Kumar\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Praveen Kumar\\.atom\\.apmrc" "install" "C:\\Users\\PRAVEE~1\\AppData\\Local\\Temp\\d-116314-15084-1dsdv6y\\package.tgz" "--target=0.34.5" "--arch=ia32" "--msvs_version=2013"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code 1

npm ERR! Command failed: error launching git: The paging file is too small for this operation to complete.
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

**Comment by Joelstonge** [comment]
has anybody figur this out yet ?

`npm ERR! git clone --template=/Users/joelstonge/.atom/.apm/_git-remotes/_templates --mirror https://github.com/jeremyramin/pty.js.git /Users/joelstonge/.atom/.apm/_git-remotes/git-https-github-com-jeremyramin-pty-js-git-28f2667-421baa32: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
npm ERR! git clone --template=/Users/joelstonge/.atom/.apm/_git-remotes/_templates --mirror https://github.com/jeremyramin/term.js.git /Users/joelstonge/.atom/.apm/_git-remotes/git-https-github-com-jeremyramin-term-js-git-4788d323: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
npm ERR! Darwin 16.1.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/joelstonge/.atom/.apm/.apmrc" "--userconfig" "/Users/joelstonge/.atom/.apmrc" "install" "/private/var/folders/xk/kcv7l3rx5vx7my544lfyzk0c0000gn/T/d-1161012-17486-1ynqvy1/package.tgz" "--runtime=electron" "--target=1.3.6" "--arch=x64" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code 1

npm ERR! Command failed: git clone --template=/Users/joelstonge/.atom/.apm/_git-remotes/_templates --mirror https://github.com/jeremyramin/pty.js.git /Users/joelstonge/.atom/.apm/_git-remotes/git-https-github-com-jeremyramin-pty-js-git-28f2667-421baa32
npm ERR! xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/xk/kcv7l3rx5vx7my544lfyzk0c0000gn/T/apm-install-dir-1161012-17486-1jes4ro/npm-debug.log

 `

**Comment by legodude17** [comment]
Does `git clone --template=/Users/joelstonge/.atom/.apm/_git-remotes/_templates --mirror https://github.com/jeremyramin/term.js.git` work?
