### ISSUE TITLE
npm windows error

### ISSUE THREAD

**Issue by kanchan17** [npm/npm#12346]
Hi,
I am new to node.js. Just install with wizard. and trying to install strongloop package so ran command
npm install -g strongloop

Below is the error I am getting

```
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "strongloop"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read

npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Program Files\nodejs\npm-debug.log
```

Please help me.

I have set  Path environment variable for node.js. No proxy settings is there.

**Comment by KenanY** [comment]
@kanchan17 Are you behind a proxy or firewall that could be preventing `npm` from connecting to the registry? This looks like an issue with your internet connection and not `npm` itself.

**Comment by philipbjorge** [comment]
@KenanY -- Starting about 2 weeks ago, we've noticed ECONNRESETs have began occurring at an alarming frequency on our windows machines.
We're seeing this on our build servers as well as an external hosting provider AppHarbor -- so we have 2 independent build servers now that are exhibiting this problem.
Retrying 3-10 times resolves the issue.
