### ISSUE TITLE
npm unpublish private package bug? logined but return 400

### ISSUE THREAD

**Issue by kkatblm** [npm/npm#12345]
Hi, 

i can't unpublish this private package with --force

i have logined with npm login

this npm package was publish with travis-ci

any idea?

[npm-debug.txt](https://github.com/npm/npm/files/218401/npm-debug.txt)

**Comment by kkatblm** [comment]
![qq20160415-0 2x](https://cloud.githubusercontent.com/assets/15902381/14548974/49f25298-02ee-11e6-93f8-bf2fddb31016.png)

any idea? @KenanY

**Comment by KenanY** [comment]
@kkatblm Might be caused by [this](http://blog.npmjs.org/post/141905368000/changes-to-npms-unpublish-policy)?

**Comment by kkatblm** [comment]
thx man @KenanY
