### ISSUE TITLE
npm v3 on Bash on Ubuntu on Windows is working incorrectly.

### ISSUE THREAD

**Issue by xuqingkuang** [npm/npm#12353]
As we know Nodejs runs on Windows is always a big problem, because most of 3rd party modules haven't tested on Windows platform, I was ran Nodejs with Docker in previous previous period.

 [Bash on Ubuntu on Windows](https://blogs.windows.com/buildingapps/2016/03/30/run-bash-on-ubuntu-on-windows/) in the latest Windows Insider makes a new way to execute Linux programs on Windows with better performance, it still in developing and lacked many features, have a lot of bugs.

After a lot of trials, I had makes npm working except file system problem, the problem looks very same with #9863, Bash on Windows is running on a cross device file system, the RENAME system call seems is working broken on this situation.

![screenshot](https://cloud.githubusercontent.com/assets/32739/14525203/efc8a382-026e-11e6-8bf5-859a10516a7c.PNG)

My environment is

    $npm config list
    ; cli configs
    user-agent = "npm/3.8.3 node/v5.10.1 linux x64"

    ; globalconfig /usr/etc/npmrc
    cache = "/home/xuqing.kxq/.npm"
    prefix = "/home/xuqing.kxq/.npm"

    ; node bin location = /usr/bin/nodejs
    ; cwd = /home/xuqing.kxq
    ; HOME = /home/xuqing.kxq
    ; "npm config ls -l" to show all defaults.

This topic just wish to discuss how to make npm works.

**Comment by othiym23** [comment]
In [this recording of the most recent CLI team weekly meeting](https://www.youtube.com/watch?v=vLcOkHhEt1g), I discuss the issues with bash on Ubuntu on Windows, as well as my belief that the Ubuntu layer isn't ready for production use, at least when it comes to Node and npm. Changes are going to be necessary in at least a few places before it's ready to go. As such, I'm going to close issues related to npm and Ubuntu on Windows until there's more of an expectation that it's ready for wider use. Thanks for your time!

**Comment by samuelkdavis** [comment]
For me, running the below command worked:

sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}

My issue was slightly different, but was permission based which seems to be the issue above. I wasn't able to create or remove a directory in the node_modules folder.

Before:
![image](https://cloud.githubusercontent.com/assets/6887841/18855974/8d081d3c-84b3-11e6-9f5b-6082fc524bed.png)

After:
![image](https://cloud.githubusercontent.com/assets/6887841/18855993/ab485208-84b3-11e6-9d9c-b7e2ceaf6a7b.png)

**Comment by samuelkdavis** [comment]
npm seems to be working for me.

npm wouldn't initially install without the below command due to permission issues (which seems to be your issue too):

sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}

![image](https://cloud.githubusercontent.com/assets/6887841/18856032/f516c39c-84b3-11e6-9258-25337c6bc5b5.png)

**Comment by dustinsoftware** [comment]
For others who stumble onto this issue from Google, it appears this is working on Windows build 14393.

**Comment by roywatson** [comment]
No it's not working
