### ISSUE TITLE
Error... $npm install -g bower

### ISSUE THREAD

**Issue by aanbuvenkatesh** [npm/npm#12359]
```
$ npm install -g bower
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "bower"
npm ERR! node v4.4.2
npm ERR! npm  v2.15.0

npm ERR! shasum check failed for C:\Users\Anbu\AppData\Local\Temp\npm-1064-b20ecb90\registry.npmjs.org\bower\-\bower-1.7.9.tgz
npm ERR! Expected: b7296c2393e0d75edaa6ca39648132dd255812b0
npm ERR! Actual:   022cb6cd6474dba3661d79d7846c254cd33db0ca
npm ERR! From:     https://registry.npmjs.org/bower/-/bower-1.7.9.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\polymer\polymer-project\npm-debug.log
```
[npm-debug.txt](https://github.com/npm/npm/files/219644/npm-debug.txt)

**Comment by KenanY** [comment]
@aanbuvenkatesh Have you tried `npm cache clean`?

**Comment by aanbuvenkatesh** [comment]
yes, i have tried. i does not work.

**Comment by aanbuvenkatesh** [comment]
last night it was not working. but today npm install -g bower worked. but while bower install
$ bower install
bower polymer#^1.0.3        not-cached git://github.com/polymer/polymer.git#^1.0.3
bower polymer#^1.0.3           resolve git://github.com/polymer/polymer.git#^1.0.3
bower polymer#^1.0.3           ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/polymer/polymer.git", exit code of #128 fatal: unable to connect to github.com: github.com[0: 192.30.252.122]: errno=No error

Additional error details:
fatal: unable to connect to github.com:
github.com[0: 192.30.252.122]: errno=No error

**Comment by KenanY** [comment]
@aanbuvenkatesh Looks like an issue with your internet connection, no?

**Comment by swetapatil** [comment]
did it work? I am also getting same error.

**Comment by aanbuvenkatesh** [comment]
which error are you asking? first or second

**Comment by KenanY** [comment]
Closing as not-an-issue-with-`npm`.
