### ISSUE TITLE
Unable to unpublish private package

### ISSUE THREAD

**Issue by nozshand** [npm/npm#12362]
somehow I was able to publish private package without a paid account but unable unpublish them nor was I able to access them

[nozshand@localhost npm-example]$ npm unpublish nozshand/npm-example@0.0.0
- @nozshand/npm-example@0.0.0

tried to publish another 2 private packaged both succeed despite the error says I need a paid account

Any way I can remove those packages?

**Comment by othiym23** [comment]
You'll need to contact <mailto:support@npmjs.com>. npm, Inc. recently [changed the unpublish policy](http://blog.npmjs.org/post/141905368000/changes-to-npms-unpublish-policy) on the public registry, and for the time being, all users will need to go through support to unpublish. That blog post goes into detail how the policy works and why we've changed it, which I hope addresses your concerns. Thanks for your time!
