### ISSUE TITLE
Multiple 404's appearing for multiple modules

### ISSUE THREAD

**Issue by JADurham909** [npm/npm#12369]
This started happening locally and on CircleCI about 20 - 30 minutes ago.

```
npm install react-router
npm ERR! fetch failed https://registry.npmjs.org/react-router/-/react-router-2.2.3.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://registry.npmjs.org/react-router/-/react-router-2.2.3.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://registry.npmjs.org/react-router/-/react-router-2.2.3.tgz
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/Users/jdurham/.npm-packages/bin/npm" "install" "react-router"
npm ERR! node v4.2.3
npm ERR! npm  v3.8.6
```

**Comment by JADurham909** [comment]
I attempted an npm cache clear, but it had no affect.  Here is another...

npm install mocha-junit-reporter
npm ERR! fetch failed https://registry.npmjs.org/mocha-junit-reporter/-/mocha-junit-reporter-1.11.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404

**Comment by gaborluk** [comment]
https://npmjs.statuspage.io/incidents/7n06gj3f83tz
This has just happened, and I'm sure not only the western US is affected, as I was, too, in Europe. The issue seems to have resolved on my end, give `npm install` another try now, it'll hopefully work this time.

**Comment by othiym23** [comment]
Since this is an issue with npm's registry, I'm going to close this with the suggestion that if it doesn't resolve soon (according to https://npmjs.statuspage.io/incidents/7n06gj3f83tz), you open a new issue on the [primary registry's issue tracker](https://github.com/npm/registry/issues). Thanks for your time and patience as we work this out!
