### ISSUE TITLE
Gulp task reading package.json in wrong path.

### ISSUE THREAD

**Issue by sabapk** [npm/npm#12363]
I am trying to run gulp task using, `npm run server -- --api http://test.site.com/api`. There is package.json present in the current directory but it is referring to another file which is not even present.

    0 info it worked if it ends with ok
    1 verbose cli [ '/usr/bin/nodejs',
    1 verbose cli   '/usr/bin/npm',
    1 verbose cli   'run',
    1 verbose cli   'server',
    1 verbose cli   '--',
    1 verbose cli   '--api',
    1 verbose cli   'http://test.site.com/api' ]
    2 info using npm@1.3.10
    3 info using node@v0.10.25
    4 error Error: ENOENT, open '/opt/bitnami/apps/jenkins/jenkins_home/jobs/Site/workspace/node_modules/server/package.json'
    5 error If you need help, you may report this log at: 
    5 error     <http://github.com/isaacs/npm/issues>
    5 error or email it to:
    5 error     <npm-@googlegroups.com>
    6 error System Linux 3.13.0-79-generic
    7 error command "/usr/bin/nodejs" "/usr/bin/npm" "run" "server" "--" "--api" "http://test.site.com/api"
    8 error cwd /opt/bitnami/apps/jenkins/jenkins_home/jobs/Site/workspace
    9 error node -v v0.10.25
    10 error npm -v 1.3.10
    11 error path /opt/bitnami/apps/jenkins/jenkins_home/jobs/Site/workspace/node_modules/server/package.json
    12 error code ENOENT 
    13 error errno 34
    14 verbose exit [ 34, true ]

**Comment by KenanY** [comment]
@sabapk [Update `npm`](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm).

**Comment by sabapk** [comment]
Done. But does not resolve the issue.

**Comment by KenanY** [comment]
@sabapk Post new log.

**Comment by sabapk** [comment]
npm ERR! Error: ENOENT, open '/opt/bitnami/apps/jenkins/jenkins_home/jobs/Site/workspace/node_modules/server/package.json'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-79-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "run" "server" "--" "--api" "http://test.site.com/api"
npm ERR! cwd /opt/bitnami/apps/jenkins/jenkins_home/jobs/Site/workspace
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /opt/bitnami/apps/jenkins/jenkins_home/jobs/Site/workspace/node_modules/server/package.json
npm ERR! code ENOENT
npm ERR! errno 34

▽
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /opt/bitnami/apps/jenkins/jenkins_home/jobs/Site/workspace/npm-debug.log
npm ERR! not ok code 0
root@ip-10-0-0-117:/opt/bitnami/apps/jenkins/jenkins_home/jobs/Site/workspace# npm run server -- --api http://test.site.com/apinpm ERR! Error: ENOENT, open '/opt/bitnami/apps/jenkins/jenkins_home/jobs/Site/workspace/node_modules/server/package.json'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-79-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "run" "server" "--" "--api" "http://test.site.com/api"
npm ERR! cwd /opt/bitnami/apps/jenkins/jenkins_home/jobs/Site/workspace
npm ERR! node -v v0.10.25

**Comment by KenanY** [comment]
@sabapk 

```
npm ERR! npm -v 1.3.10
```

Still using outdated, unsupported version of `npm`.

**Comment by sabapk** [comment]
Set permission to the project on remote server. Was running the command through jenkins.

**Comment by othiym23** [comment]
Closing as resolved.
