### ISSUE TITLE
npm install ignores nested shrinkwrapped dependencies

### ISSUE THREAD

**Issue by misterbyrne** [npm/npm#12372]
Related issue? https://github.com/npm/npm/issues/6928

During an `npm install`, the shrinkwrap is inflated, but only one level deep. As a result the versions of these nested sub-dependencies are resolved the non-shrinkwrapped way.

This only seems to occur during multi-stage installs (i.e. `rm -rf node_modules && npm install` will result in the correct versions being installed). When it does happen it can result in different versions of sub-dependencies being installed than specified in the shrinkwrap file. This is probably more likely to happen where people rely on multi-stage installs (i.e. restoring a 'cached' `node_modules` directory from a previous build followed by `npm install` - pretty common in hosted CI - e.g. CodeShip / CircleCI).

### Reproduction steps

(there's a similar test [here](https://github.com/npm/npm/issues/12373) that fails on the master branch)

1. `npm init`
2. `npm install repeating@1.0.0 --save`
3. `npm install redent@1.0.0 --save`
4. `npm shrinkwrap` - notice that there's a sub-dependency nested within the shrinkwrap

    ![image](https://cloud.githubusercontent.com/assets/1167425/14575786/fe4b8a8a-035b-11e6-911c-e6b22315d8d8.png)

5. Edit the shrinkwrap file to change the `repeating@2.0.1` sub-dependency to `repeating@2.0.0`, e.g.

    `sed -i.bak "s/2.0.1/2.0.0/g" npm-shrinkwrap.json`

    I know manually editing a shrinkwrap file is kinda crazy, but this is just to get a quick repro in place - in practise this happens frequently whenever the sub-dependency has a patch release version bump [albeit from a lower version number to a higher one].

6. `npm install`

### Expected outcome

The `repeating@2.0.1` sub-dependency is downgraded to `2.0.0`

### Actual outcome

Nothing happens - the 'ideal' tree and the current tree are identical.

Incidentally, this was made apparent because ember cli runs a [dependency checker](https://github.com/quaertym/ember-cli-dependency-checker) before running and flags any version mismatches between what's in `npm-shrinkwrap.json` and `node_modules`.

**Comment by iarna** [comment]
Yeah, this is awkward because we currently allow partial shrinkwraps (which is necessary to install `hapi`), which means that you're allowed to have modules in your tree that aren't in the shrinkwrap as long as the match a `package.json` entry, and in this case it does. =/

I'm not sure if there's any solution here short of nixing the partial shrinkwrap feature. (Which would please   me greatly.)

**Comment by misterbyrne** [comment]
Ah. Okay. Are there tests for the partial shrinkwrap feature? I'm wondering because my PR passes CI. I'll try have a dig round soon either way!

**Comment by misterbyrne** [comment]
I've tried the following:

Comparing installing hapi

```bash
mkdir swtest
cd swtest
# install using system npm@latest
npm init
npm install hapi --save
# use git to see is there any difference between my branch and the latest release
git init
git add .
git commit -m"installed using npm@latest"
# install using npm@ my branch
node ~/src/npm/bin/npm-cli.js install hapi --save
# this shows 'nothing to commit' - no changes
git status
```

I tried a similar approach in the hapi repo and it worked similarly.
I'm probably missing something though :/

**Comment by iarna** [comment]
Ok, I have had time to sit down and go through your repro and I understand the implications of your fix better now and it looks right to me. (My earlier concern around hapi was due to a misreading of the issue. Your change shouldn't cause problems.)

**Comment by misterbyrne** [comment]
Aw cool, that's great news! Thanks so much for looking at this.
