### ISSUE TITLE
Not found errors are malformed when using Nexus

### ISSUE THREAD

**Issue by martypitt** [npm/npm#12374]
When using [Nexus 3.x](http://www.sonatype.com/download-oss-sonatype) (Specifically, OSS 3.0.0-b2016011501), package urls are longer than the standard http format:

```
http://mynexus.com/repository/npm-all/my-package
```

If this is not found in the registry, the error reports `repository` as the missing dependency, rather than `my-package`:

`639 error 404 'repository' is not in the npm registry.`

Here's the relevant snippets from the log:

```
➜  npmtst cat npm-debug.log | grep 404
259 http 404 http://mynexus.com/repository/npm-all/my-package
261 silly get cb [ 404,
262 silly fetchPackageMetaData  error for my-package@>0.1.0-SNAPSHOT { [Error: Not found : repository] pkgid: 'repository', statusCode: 404, code: 'E404' }
...
629 verbose statusCode 404
636 error code E404
637 error 404 Not found : repository
638 error 404
639 error 404 'repository' is not in the npm registry.
640 error 404 You should bug the author to publish it (or use the name yourself!)
641 error 404 It was specified as a dependency of 'my-project'
642 error 404 Note that you can also install from a
643 error 404 tarball, folder, http url, or git url.
```

NPM version 3.6.0
Node version 5.7.0

**Comment by HeavyStorm** [comment]
This is still an issue.

**Comment by webia1** [comment]
same here,..

**Comment by marchaos** [comment]
Me too.

**Comment by RobotLimeLtd** [comment]
This also happens when a dependency is not found.

**Comment by brunohcastro** [comment]
I found a way to fix that by using a nginx proxy in front of nexus. It also adds the ability of using the same address to publish to a hosted (private) repo and download from the group (hosted + proxy).

The configuration goes like:

```
server {
    server_name npm.example.com;
    listen 80;

    client_max_body_size 200M;

    rewrite ^/repository/npm-internal/(.*)$ https://npm.example.com/$1 permanent;
    rewrite ^/repository/npm/(.*)$ https://npm.example.com/$1 permanent;

    location ~* \.(css|js|svg|png|ico|jpe?g|gif)(\?((\d\.|\d-|\d)*))?$ {
        rewrite ^/(.*)$ https://nexus.example.com/$1 permanent;
    }

    location / {
        if ($request_method = GET ) {
            rewrite ^/(.*)$ /repository/npm/$1 break;
        }

        rewrite ^/(.*)$ /repository/npm-private/$1 break;

        proxy_set_header    Host            $host;
        proxy_set_header    X-Real-IP       $remote_addr;
        proxy_set_header    X-Forwarded-for $remote_addr;

        proxy_pass http://localhost:8081;
        proxy_redirect default;
    }
}
```

I'll try to explain each part:

1.
```
    rewrite ^/repository/npm-internal/(.*)$ https://npm.example.com/$1 permanent;
    rewrite ^/repository/npm/(.*)$ https://npm.example.com/$1 permanent;
```

The whole problem that this issue addresses is when clients try to reach the repo through the /repository/npm address. It seems like npm resolves the missing package name through the request url, getting the name just after the host address. 

This code tells that any client that reaches this endpoint should be redirected to the server base. So npm will try to reach the resource through the proper channels and the error message will be accurate.

2.
```
    location ~* \.(css|js|svg|png|ico|jpe?g|gif)(\?(\d(\.|-)?)+)?$ {
        rewrite ^/(.*)$ https://nexus.example.com/$1 permanent;
    }
```

This part is completely unnecessary. But if you are a freak like me, this will please you. When you hit the repository in a browser, you will get the Nexus page with images and css. (remember to set the base url if you want the links to go to the correct page).

3.
```
        if ($request_method = GET ) {
            rewrite ^/(.*)$ /repository/npm/$1 break;
        }

        rewrite ^/(.*)$ /repository/npm-private/$1 break;
```

Here we just rewrite the request uri to the correct place. If it is a GET request, we call the repository group. If it is a PUT, POST, DELETE or other request we call the private repository.


Hope this helps.

Good coding!

**Comment by marceloavan** [comment]
Thank you @brunohcastro, your solution works fine to me.
