### ISSUE TITLE
bin scripts should always have Unix line endings

### ISSUE THREAD

**Issue by othiym23** [npm/npm#12371]
See #2097 for context and discussion. When publishing from Windows, depending on how developers set up Git, it's possible that binary scripts will end up in the tarball with `CR LF` line endings, instead of the `LF` expected by Unix / OS X. This can cause failures when those scripts are invoked. The logic that Git applies to figure out whether a file is binary or not is surprisingly subtle, and this is the sort of thing that can cause really hard to debug issues if not handled correctly. This is the heuristic @iarna and I have come up with for figuring out which files need their line endings cleaned up:
1. Is it linked to from `bin`?
2. Is the first line a shebang?
#2 is necessary in the case in which `bin` links to a native binary, which we don't want to mangle during the publish or installation processes.

To be a complete solution, this would need to be some kind of stream transform that gets applied at both publish and install time – publish, so that newly-published packages have the correct line endings, and install, so that non-Windows users running installs with the fixed version of the CLI aren't bitten by legacy packages with the wrong line endings in their scripts.

**Comment by ikatun** [comment]
Just add `"prepublish": "dos2unix index.js"` line to your "scripts" in package.json.

Also make sure that dos2unix is added to the dev dependencies (npm install --saveDev dos2unix).

**Comment by s-h-a-d-o-w** [comment]
dos2unix doesn't offer a CLI, so that won't work.

What does work however is the tool mentioned here: https://github.com/npm/npm/issues/2097#issuecomment-144892185

To do the one-way conversion that you seem to describe (except that I'd do it for everything in the "bin" directory), one would simply have to do:
```
    "prepublish": "crlf --set=LF bin/*"
```


If one wants to convert back to CRLF after publishing, to get the "Git for Windows" behavior (see: https://github.com/npm/npm/issues/2097#issuecomment-183319865), one would need to use some dirty hacks to ensure that it works on all platforms:
```
    "prepublish": "true || IF a==a crlf --set=LF bin/*",
    "postpublish": "true || IF a==a crlf --set=CRLF bin/*",
```
It's not pretty but by failing silently on non-Windows machines, it avoids having to e.g. create a separate script that does OS checking and that one would need to include in every single package.

**Comment by yavorski** [comment]
This is problematic `"prepublish": "crlf --set=LF bin/*"`.
It would cause `npm install` to fail if `crlf` is not globally installed. 
Because `"prepublish"` will run with `"npm install"` too. 
Solution would be to use the newly introduced hook `prepublishOnly`

**Comment by eight04** [comment]
After reading the comments, it seems that 0ef320c only normalize new lines while the installation, so package authors are still recommended to use `crlf` before publishing, right?

**Comment by ScottFreeCode** [comment]
That sounds correct to me; I suppose I should've been more careful about "fixes ..." in the GitHub format.

Based on https://github.com/npm/npm/pull/16634#issuecomment-323156085 and the 5.4.0 release notes we should now be good to start looking at a publish-side fix, however.

I'd also love to see it tackle the file permissions (and I'd like to look into ensuring the file permissions and line ending normalization on install occur even with the flag that disables bin links), but I'll have to go dig up the issues concerning that.

**Comment by marcosscriven** [comment]
The fix for this issue unfortunately caused a new one https://github.com/npm/npm/issues/19151

**Comment by janwidmer** [comment]
Is there any new solution to solve the publish problem besides using `prebublish` and `postpublish` in combination with the clrf plugin?

We are experiencing the original problem descriped here https://github.com/npm/npm/issues/2097  with .githook files being generated by a yeoman generator
