### ISSUE TITLE
Not able to find my published npm package

### ISSUE THREAD

**Issue by ratneshn** [npm/npm#12383]
```
npm ERR! publish Failed PUT 403
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "publish"
npm ERR! node v5.7.0
npm ERR! npm  v3.8.6
npm ERR! code E403

npm ERR! You cannot publish the same version more than once
npm ERR! Bump the version number in package.json, and try again. : animal-picture
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ratnesh/Documents/dog-picture/npm-debug.log
```

**Comment by troublete** [comment]
Could u please post your composer.json.

**Comment by ratneshn** [comment]
{
  "name": "animal-picture",
  "version": "1.0.0",
  "description": "a dog appear on your web site",
  "main": "index.js",
  "scripts": {
    "test": "node test.js"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/ratneshn/dog-picture.git"
  },
  "author": "ratneshn",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/ratneshn/dog-picture/issues"
  },
  "homepage": "https://github.com/ratneshn/dog-picture#readme",
  "dependencies": {
    "once": "^1.3.1"
  }
}

**Comment by mikhail-riabokon** [comment]
@ratneshn Hi. Have you tired change patch version ```npm version patch``` and publish it again? Or if nobody use it except you, probably you can delete it from npm and try to publish again.
