### ISSUE TITLE
npm install error 4058, can't install private module in windows

### ISSUE THREAD

**Issue by VincentLinsanity** [npm/npm#12389]
I can't install my private module call storage:0.1.1 when I command "npm install" in the root path

I write package.json to install this module as:

"dependencies": { "storage": "file:modules/storage" }

and I also write package.json in the private module stroage already, it's work on my linux well, on windows well before, but one day I install occur error -4058

and there are error message:

```
909 verbose stack Error: ENOENT: no such file or directory, scandir 'C:\Users\vincent_lin\AppData\Roaming\npm-cache\storage\0.1.1\package.tgz'
909 verbose stack at Error (native) 
910 verbose cwd D:\networkteam\meta\git_meta_static_develop 
911 error Windows_NT 6.1.7601 
912 error argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" 
913 error node v4.4.2 
914 error npm v2.15.0 
915 error path C:\Users\vincent_lin\AppData\Roaming\npm-cache\storage\0.1.1\package.tgz 
916 error code ENOENT 
917 error errno -4058 
918 error syscall scandir 
919 error enoent ENOENT: no such file or directory, scandir 'C:\Users\vincent_lin\AppData\Roaming\npm-cache\storage\0.1.1\package.tgz' 
919 error enoent This is most likely not a problem with npm itself
919 error enoent and is related to npm not being able to find a file. 
920 verbose exit [ -4058, true ]
```

ps: I have tried to use powershell with administration and I checked the path 'C:\Users\vincent_lin\AppData\Roaming\npm-cache\storage\0.1.1\package.tgz' is correct.
and I ever update npm to latest version, it still exist error.

Thanks for any response.

**Comment by othiym23** [comment]
Can you provide the entire `npm-debug.log` [as a gist](https://gist.github.com)?
