### ISSUE TITLE
cannot find published npm package 

### ISSUE THREAD

**Issue by nmalik92** [npm/npm#12400]
```
Nadias-MacBook-Pro:ibm-cloud-object-storage nadiamalik$ npm publish --registry=$IBM_NPM_REGISTRY 
npm ERR! publish Failed PUT 401
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "publish" "--registry=http://173.192.225.82:8080"
npm ERR! node v5.1.0
npm ERR! npm  v3.3.12
npm ERR! code E401

npm ERR! visit https://w3id.tap.ibm.com/auth/sps/samlidp/saml20/login...... to validate your session : ibm-cloud-sdk-for-nodejs
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/nadiamalik/gitHub/ibm-cloud-object-storage/npm-debug.log

Nadias-MacBook-Pro:ibm-cloud-object-storage nadiamalik$ npm publish --registry=$IBM_NPM_REGISTRY 
npm ERR! publish Failed PUT 403
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "publish" "--registry=http://173.192.225.82:8080"
npm ERR! node v5.1.0
npm ERR! npm  v3.3.12
npm ERR! code E403

npm ERR! "You cannot publish over the previously published version 1.0.0. Try bumping the version to 2.0.0" : ibm-cloud-sdk-for-nodejs
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```
I cannot find  "ibm-cloud-sdk-for-nodejs" http://173.192.225.82:8081/search?q=nodejs&page=1 . I'm assuming it was published because when I try to republish there is an error to update my version.

**Comment by bcoe** [comment]
@nmalik92 it looks like your SAML session has run out, when you try to publish, copy the login URL and login (I believe sessions are configured for two weeks).

The second error looks to be that you are publishing over a previously published version of the module, does the publication succeed if you bump to `1.0.1`?

**Comment by nmalik92** [comment]
@bcoe there was an issue with the url i had specified in the package.json. i was able to publish it here: http://173.192.225.82:8081/package/ibm-cloud-object-storage but when running npm i ibm-cloud-object-storage i see the following error: 

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "ibm-cloud-object-storage"
npm ERR! node v5.1.0
npm ERR! npm  v3.3.12
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/ibm-cloud-object-storage
npm ERR! 404 
npm ERR! 404 'ibm-cloud-object-storage' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by bcoe** [comment]
@nmalik92 it looks like you're publishing the module to the private registry (`http://173.192.225.82:8081`) but then installing the module from the public registry, `https://registry.npmjs.org`; if you want to publish to and install from your private registry, you will need to specify `--registry=$IBM_NPM_REGISTRY` in both the publish and install step.

Another option is to use scoped modules for your private modules, and to store the mapping to your private registry in your `.npmrc`, you do so as follows:

1. `npm login --scope=@my-company --registry=http://173.192.225.82:8081`
2. when creating new modules, name them `@my-company/foo`, ``@my-company/foo2`, etc.
3. you will now be able to install from, and publish to your private registry without including `-registry=$IBM_NPM_REGISTRY` in each request (it also makes it less likely that you accidentally publish to the public registry).

**Comment by bcoe** [comment]
@nmalik92 this content is also a great read: https://docs.npmjs.com/misc/scope

**Comment by bcoe** [comment]
@nmalik92 if you run into any more issues with the private instance, send an email to `support [at] npmjs.com` and feel free to CC `ben [at] npmjs.com`, I can continue helping to introduce you to how private modules work.
