### ISSUE TITLE
Private git packages from AWS CodeCommit cannot be updated

### ISSUE THREAD

**Issue by bakpakin** [npm/npm#12401]
Our team is currently using AWS CodeCommit to host source code. I would like to reference our private packages directly from git. I can successfully install a package via

``` bash
npm install --save git+https://aws-repository-here
```

for the first install. However, when updating the package, or running `npm install` without extra arguments, I get a 401 error:

```
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
```

npm will then retry a few times, and then fail, saying to report a bug.

The AWS cli tools and authentication scheme is quirky and doesn't play nice with many tools, but I am confused as to why installing all packages in package.json doesn't work while installing that one package does work.

**Comment by zkat** [comment]
@bakpakin could you upload your `npm-debug.log` and/or post it as a gist? We need to see what's happening under here.

**Comment by bakpakin** [comment]
I'm having trouble reproducing the issue two weeks later. I will make sure to keep the log if the issue comes up again. It seems to have fixed itself.
