### ISSUE TITLE
install error for plato.js

### ISSUE THREAD

**Issue by ua1005** [npm/npm#12407]
on window7, i can find the following error to install plato.js
how do i do?
<error log in npm-debug.log>
0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files (x86)\nodejs\node.exe',
1 verbose cli   'C:\Program Files (x86)\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'plato' ]
2 info using npm@2.15.1
3 info using node@v4.4.3
4 verbose install initial load of C:\Users\JackLee\AppData\Roaming\npm\package.json
5 verbose readDependencies loading dependencies from C:\Users\JackLee\AppData\Roaming\npm\package.json
6 silly cache add args [ 'plato', null ]
7 verbose cache add spec plato
8 silly cache add parsed spec Result {
8 silly cache add   raw: 'plato',
8 silly cache add   scope: null,
8 silly cache add   name: 'plato',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: 'latest',
8 silly cache add   type: 'tag' }
9 silly addNamed plato@latest
10 verbose addNamed "latest" is being treated as a dist-tag for plato
11 info addNameTag [ 'plato', 'latest' ]
12 silly mapToRegistry name plato
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry http://registry.npmjs.org/
15 silly mapToRegistry data Result {
15 silly mapToRegistry   raw: 'plato',
15 silly mapToRegistry   scope: null,
15 silly mapToRegistry   name: 'plato',
15 silly mapToRegistry   rawSpec: '',
15 silly mapToRegistry   spec: 'latest',
15 silly mapToRegistry   type: 'tag' }
16 silly mapToRegistry uri http://registry.npmjs.org/plato
17 verbose addNameTag registry:http://registry.npmjs.org/plato not in flight; fetching
18 verbose request uri http://registry.npmjs.org/plato
19 verbose request no auth needed
20 info attempt registry request try #1 at 17:15:10
21 verbose request id 9f6a8b926375495b
22 http request GET http://registry.npmjs.org/plato
23 http 404 http://registry.npmjs.org/plato
24 verbose bad json <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
24 verbose bad json <html><head>
24 verbose bad json <title>404 Not Found</title>
24 verbose bad json </head><body>
24 verbose bad json <h1>Not Found</h1>
24 verbose bad json <p>The requested URL /plato was not found on this server.</p>
24 verbose bad json <hr>
24 verbose bad json <address>Apache/2.2.15 (CentOS) Server at registry.npmjs.org Port 80</address>
24 verbose bad json </body></html>
25 error registry error parsing json
26 verbose headers { date: 'Tue, 19 Apr 2016 08:15:08 GMT',
26 verbose headers   server: 'Apache/2.2.15 (CentOS)',
26 verbose headers   'content-length': '287',
26 verbose headers   connection: 'close',
26 verbose headers   'content-type': 'text/html; charset=iso-8859-1' }
27 silly get cb [ 404,
27 silly get   { date: 'Tue, 19 Apr 2016 08:15:08 GMT',
27 silly get     server: 'Apache/2.2.15 (CentOS)',
27 silly get     'content-length': '287',
27 silly get     connection: 'close',
27 silly get     'content-type': 'text/html; charset=iso-8859-1' } ]
28 verbose stack SyntaxError: Unexpected token <
28 verbose stack <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
28 verbose stack <html><head>
28 verbose stack <title>404 Not Found</title>
28 verbose stack </head><body>
28 verbose stack <h1>Not Found</h1>
28 verbose stack <p>The requested URL /plato was not found on this server.</p>
28 verbose stack <hr>
28 verbose stack <address>Apache/2.2.15 (CentOS) Server at registry.npmjs.org Port 80</address>
28 verbose stack </body></html>
28 verbose stack
28 verbose stack     at Object.parse (native)
28 verbose stack     at CachingRegistryClient.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:199:23)
28 verbose stack     at Request._callback (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:172:14)
28 verbose stack     at Request.self.callback (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\request.js:199:22)
28 verbose stack     at emitTwo (events.js:87:13)
28 verbose stack     at Request.emit (events.js:172:7)
28 verbose stack     at Request.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\request.js:1036:10)
28 verbose stack     at emitOne (events.js:82:20)
28 verbose stack     at Request.emit (events.js:169:7)
28 verbose stack     at IncomingMessage.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\request.js:963:12)
29 verbose cwd C:\Users\JackLee
30 error Windows_NT 6.1.7601
31 error argv "C:\Program Files (x86)\nodejs\node.exe" "C:\Program Files (x86)\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "plato"
32 error node v4.4.3
33 error npm  v2.15.1
34 error Unexpected token <
34 error <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
34 error <html><head>
34 error <title>404 Not Found</title>
34 error </head><body>
34 error <h1>Not Found</h1>
34 error <p>The requested URL /plato was not found on this server.</p>
34 error <hr>
34 error <address>Apache/2.2.15 (CentOS) Server at registry.npmjs.org Port 80</address>
34 error </body></html>
35 error If you need help, you may report this error at:
35 error     https://github.com/npm/npm/issues
36 verbose exit [ 1, true ]

**Comment by ihorskyi** [comment]
Looks like a temporary issue on server. Do you still have this problem when installing?

**Comment by ua1005** [comment]
Yes, i have still this problem! How do I do?

**Comment by ihorskyi** [comment]
what happens when you clicks this link http://registry.npmjs.org/plato ?

**Comment by ua1005** [comment]
yes. i can get plato.json!!! so that i checked the config setting and I can fix this issue.
The problem is come from the setting of proxy IP address.
Thank you for your following comments. (your following comments can be the hint to resolve this issue. Thanks for your sincerely support and comments)
cf) Frankly speaking, the above log from npm.js does not provide the "proxy issue". If it would comment the proxy issue, it would be better. ;-)
