### ISSUE TITLE
Unable to install EJS 

### ISSUE THREAD

**Issue by saigeetham** [npm/npm#12416]
Hi,

```
 I am trying to install EJS in node.js but I couldn't and also I tried to install the "npm"  latest  version but failed. I am unable to fix the issue ...  help me out in resolving it
```

0 info it worked if it ends with ok
1 verbose cli [ 'C:\Users\geetha\Desktop\nodejs\node.exe',
1 verbose cli   'C:\Users\geetha\Desktop\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'ejs' ]
2 info using npm@2.15.1
3 info using node@v4.4.3
4 verbose install initial load of C:\Users\geetha\Desktop\nodejs\package.json
5 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\package.json
6 info package.json npm@2.15.1 Non-dependency in bundleDependencies: ansi-regex
7 info package.json npm@2.15.1 Non-dependency in bundleDependencies: imurmurhash
8 verbose readDependencies loading dependencies from C:\Users\geetha\Desktop\nodejs\package.json
9 silly cache add args [ 'ejs', null ]
10 verbose cache add spec ejs
11 silly cache add parsed spec Result {
11 silly cache add   raw: 'ejs',
11 silly cache add   scope: null,
11 silly cache add   name: 'ejs',
11 silly cache add   rawSpec: '',
11 silly cache add   spec: 'latest',
11 silly cache add   type: 'tag' }
12 silly addNamed ejs@latest
13 verbose addNamed "latest" is being treated as a dist-tag for ejs
14 info addNameTag [ 'ejs', 'latest' ]
15 silly mapToRegistry name ejs
16 silly mapToRegistry using default registry
17 silly mapToRegistry registry https://registry.npmjs.org/
18 silly mapToRegistry data Result {
18 silly mapToRegistry   raw: 'ejs',
18 silly mapToRegistry   scope: null,
18 silly mapToRegistry   name: 'ejs',
18 silly mapToRegistry   rawSpec: '',
18 silly mapToRegistry   spec: 'latest',
18 silly mapToRegistry   type: 'tag' }
19 silly mapToRegistry uri https://registry.npmjs.org/ejs
20 verbose addNameTag registry:https://registry.npmjs.org/ejs not in flight; fetching
21 verbose request uri https://registry.npmjs.org/ejs
22 verbose request no auth needed
23 info attempt registry request try #1 at 11:17:08 AM
24 verbose request id a5217f26b2f3a4a2
25 http request GET https://registry.npmjs.org/ejs
26 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
27 info attempt registry request try #2 at 11:17:18 AM
28 http request GET https://registry.npmjs.org/ejs
29 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
30 info attempt registry request try #3 at 11:18:18 AM
31 http request GET https://registry.npmjs.org/ejs
32 verbose stack Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
32 verbose stack     at Object.exports._errnoException (util.js:870:11)
32 verbose stack     at errnoException (dns.js:32:15)
32 verbose stack     at GetAddrInfoReqWrap.onlookup [as oncomplete](dns.js:78:26)
33 verbose cwd C:\Users\geetha\Desktop\nodejs
34 error Windows_NT 6.1.7601
35 error argv "C:\Users\geetha\Desktop\nodejs\node.exe" "C:\Users\geetha\Desktop\nodejs\node_modules\npm\bin\npm-cli.js" "install" "ejs"
36 error node v4.4.3
37 error npm  v2.15.1
38 error code EAI_AGAIN
39 error errno EAI_AGAIN
40 error syscall getaddrinfo
41 error getaddrinfo EAI_AGAIN registry.npmjs.org:443
42 error If you need help, you may report this error at:
42 error     https://github.com/npm/npm/issues
43 verbose exit [ 1, true ]

**Comment by ihorskyi** [comment]
```41 error getaddrinfo EAI_AGAIN registry.npmjs.org:443``` - means a temporary failure in name resolution or simply the name server returned a temporary failure indication. Do you still have this issue?

**Comment by saigeetham** [comment]
Yes, I still facing have the issue.. @ihorskyi

**Comment by ihorskyi** [comment]
Please run these commands in your terminal/CMD and paste result here

```bash 
ping registry.npmjs.org
```
```bash 
tracert registry.npmjs.org
```
```bash 
telnet registry.npmjs.org 443
```

**Comment by saigeetham** [comment]
These are the results when I run those 3 commands on my cmd prompt @ihorskyi 



C:\Program Files\nodejs>ping registry.npmjs.org
Ping request could not find host registry.npmjs.org. Please check the name and t
ry again.

C:\Program Files\nodejs>tracert registry.npmjs.org
Unable to resolve target system name registry.npmjs.org.

C:\Program Files\nodejs>telnet registry.npmjs.org 443
'telnet' is not recognized as an internal or external command,
operable program or batch file.

**Comment by martianmartian** [comment]
Fuck u all

Sent from my iPhone

On Apr 26, 2016, at 2:35 AM, saigeetham <notifications@github.com<mailto:notifications@github.com>> wrote:


These are the results when I run those 3 commands on my cmd prompt @ihorskyi<https://github.com/ihorskyi>

C:\Program Files\nodejs>ping registry.npmjs.org<http://registry.npmjs.org>
Ping request could not find host registry.npmjs.org<http://registry.npmjs.org>. Please check the name and t
ry again.

C:\Program Files\nodejs>tracert registry.npmjs.org<http://registry.npmjs.org>
Unable to resolve target system name registry.npmjs.org<http://registry.npmjs.org>.

C:\Program Files\nodejs>telnet registry.npmjs.org<http://registry.npmjs.org> 443
'telnet' is not recognized as an internal or external command,
operable program or batch file.

-

**Comment by cmglez10** [comment]
It seems you don't have internet access. Do you?
