### ISSUE TITLE
Install NPM packages on read-only file systems

### ISSUE THREAD

**Issue by zanona** [npm/npm#12418]
Hey folks,
I was wondering if there's actually any possible way to install npm modules on read-only file systems while pointing the installation to `/tmp`?

I am coming from the point that I still have access to commands like:

``` sh
dir=$(mktemp -d)/foo
echo bar > $dir/foo
```

Which made me wonder about this option.
Now, I understand that many npm modules may perform `pre-install` scripts that need access to the file system as well as the ones providing CLI commands, however, in this case I am only concerned about downloading the necessary module source files to that specific directory under `/tmp`, and then compile a file that use those dependencies and output a standalone browserify module, so not really running any scripts besides the module installation at this point.

I hope that makes sense to you guys.

Thanks in advance and all the best.

**Comment by sumit08** [comment]
I am also facing the same issue. Can someone help with that ??

**Comment by sribalakumar** [comment]
@zanona Any luck with this or ways on how to achieve this. I have write access only to /tmp but npm install fails giving EROFS error even after pointing destination directory to /tmp.

**Comment by zanona** [comment]
@sribalakumar Not at the moment I'm afraid. Hopefully, with the potential this offers to Lambda, someone will notice this issue soon.

**Comment by xarsh** [comment]
I had same problem. But for ephemeral environment like AWS lambda, you can modify environment variable and works fine.
```
export HOME='/tmp' && npm install *** --prefix='/tmp'
```

**Comment by zanona** [comment]
That's awsome @xarsh! Thanks a lot for sharing.
Imagine the possbilities :)

Of course, not to install modules on every run, but there are cases where this can be very very useful.

Just a snippet just in case someone wants to test it out.

```js
const exec        = require('child_process').execSync,
      tmpRequire  = exec("export HOME='/tmp' && npm install moment --prefix='/tmp'"),
      moment      = require('../../tmp/node_modules/moment');

exports.handler = (event, context) => {;
  context.succeed(moment().add(1, 'days').fromNow());
}
```

**Comment by sribalakumar** [comment]
@zanona @xarsh We might have difficulties catching the error at run time if npm install fails, prefer programatically installing it using npm.commands.install, but wonder how can we set prefix and HOME in that case.

**Comment by zanona** [comment]
@sribalakumar isn't possible to listen to `stderr` on the [async version of exec](https://nodejs.org/dist/latest-v4.x/docs/api/child_process.html#child_process_child_process_exec_command_options_callback)?

The callback should give you:

```js
const exec = require('child_process').exec;
exec('cat *.js bad_file | wc -l', (error, stdout, stderr) => {
  if (error) {
    console.error(`exec error: ${error}`);
    return;
  }
  console.log(`stdout: ${stdout}`);
  console.log(`stderr: ${stderr}`);
});
```

**Comment by sribalakumar** [comment]
@zanona yes that should work :)

**Comment by alex-nishikawa** [comment]
`export HOME='/tmp'`  didn't work for me on AWS lambda, I had to set the environment variable through the AWS console (or AWS CLI).

**Comment by iamapark** [comment]
@alex-nishikawa it works for me!! thanks!
