### ISSUE TITLE
Issue in NPM while installing bower

### ISSUE THREAD

**Issue by krishnachaitanyap** [npm/npm#12411]
npm ERR! not a package /opt/incubator-zeppelin/zeppelin-web/bower
npm ERR! addLocal Could not install /opt/incubator-zeppelin/zeppelin-web/bower
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/Cellar/node/5.10.1/bin/node" "/usr/local/bin/npm" "install" "-g" "bower"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.6
npm ERR! path /var/folders/rb/wmrqhjg948xfn199y6vkvmnw0000gn/T/npm-2644-ccc113d3/unpack-79e40234/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/var/folders/rb/wmrqhjg948xfn199y6vkvmnw0000gn/T/npm-2644-ccc113d3/unpack-79e40234/package.json'
npm ERR! enoent ENOENT: no such file or directory, open '/var/folders/rb/wmrqhjg948xfn199y6vkvmnw0000gn/T/npm-2644-ccc113d3/unpack-79e40234/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/incubator-zeppelin/zeppelin-web/npm-debug.log

**Comment by KenanY** [comment]
@krishnachaitanyap Could you try renaming this directory to something other than `bower`?: `/opt/incubator-zeppelin/zeppelin-web/bower`, or running the command from a different directory? Since you have a directory called `bower/` in your current working directory, `npm` is trying to install it when you run `npm install -g bower` but apparently that directory does not contain a `package.json`, hence the error.

**Comment by skhanam** [comment]
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/Cellar/node/5.10.1/bin/node" "/usr/local/bin/npm" "install" "-g" "appium@1.5.1"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! path /usr/local/bin/appium
npm ERR! code EEXIST

npm ERR! Refusing to delete /usr/local/bin/appium: ../lib/node_modules/appium/bin/appium.js symlink target is not controlled by npm /usr/local
npm ERR! File exists: /usr/local/bin/appium
npm ERR! Move it away, and try again.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Shabana/npm-debug.log
npm ERR! code 1

**Comment by KenanY** [comment]
@krishnachaitanyap Are you still experiencing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
