### ISSUE TITLE
ELIFECYCLE - "tsc" exist status 1 error when ran inside an "npm script"

### ISSUE THREAD

**Issue by MarkPieszak** [npm/npm#12412]
**TypeScript Version:** 
1.7.5 1.9 nightly (doesn't matter)

**Node & npm**
5.10.1  & 3.8.6

#### To reproduce, simply try to run **`tsc`** when inside an npm script on **Windows** when you have a few things that haven't been "declared" for typings. Let's say Promise / require / etc

These are "light" errors thrown by TS that shouldn't require npm to exit. For example, on mac it runs completely fine.

In my example I have:

    "scripts" : {
        "build-ts" : "tsc"
    }

When running:

    npm run build-ts

It runs typescript compiler and all of that seems to work fine. After, it seems to error out (causing any further scripts to never run as well)
Note: `tsc` alone when ran in the console works fine.

I believe **npm's** lifecylce is failing on 'close' perhaps:
https://github.com/npm/npm/blob/9265e1dd068b7e0cabf2135eb73f211f9e2f73aa/lib/utils/lifecycle.js#L239

> ELIFECYCLE
> Exist status 1
> Failed at ... build-ts script 'tsc'
> Make sure you have the latest version of node.js and npm installed.

**Comment by Tomino2112** [comment]
+1 on this, I am using one of JetBrains IDE and have my testing run task setup, one of the options is to run another task before, so I setup `tsc` from my package.json to make sure all TS is compiled before tests. But because tsc fails, it won't run my tests.

**Comment by MarkPieszak** [comment]
Are you on windows 7 as well? @Tomino2112

**Comment by Tomino2112** [comment]
@MarkPieszak im on Windows 10. I should say that TypeScript compilation actually does show warnings while compiling,  but hardly you will get no warnings on big project,  especially node project

**Comment by MarkPieszak** [comment]
It seems something has changed recently. Although those errors come up from `tsc` it shouldn't be ending the ELIFECYCLE of npm. It makes chaining scripts impossible if there's the tiniest little fudge-up in the Typescript.

Hoping someone on the *npm* team can give us some insight on this. I'm fine on OS X, but Win7 completely craps out the process. 👎

**Comment by iarna** [comment]
If `tsc` is exiting with a non-zero exit status then npm will end in error and that's normal and expected. If this is what you're experiencing you would get a bunch of lines starting with `npm ERR!` in our output.

If that is the case, and you believe `tsc` shouldn't be indicating an error, you'll need to reach out to the [typescript folks](https://github.com/microsoft/typescript) and ask them to change that.

---

If you want to ignore errors coming out of `tsc` in a cross platform compatible manner you can do that with something like:
```
"build-tsc": "tsc && echo ok || echo not ok"
```

---

There's another possibility however. If you are running `npm run build-tsc` from `msbuild` and you _aren't_ seeing `npm ERR!` lines then you're being bit by a quirk of `msbuild` behavior. If something prints to `stderr` then `msbuild` will assume that an error occurred and act as if the exit code were -1. If `tsc` is printing its warnings to `stderr` then it would trigger this. Again, if this is what you're seeing you will have to take it up with the [typescript project](https://github.com/microsoft/typescript).

**Comment by iarna** [comment]
https://github.com/npm/npm/issues/5253 discusses some related issues, apparently if you are running npm from PowerShell scripts then you'll see the same behavior as with `msbuild`.

**Comment by lastmjs** [comment]
I'm having similar problems, Ubuntu 14.04, Node.js v6.0.0, TypeScript v1.8.10

**Comment by MarkPieszak** [comment]
Yeah I'm still getting the same issues with Node 6+ now as well, seems updating npm didn't fix it as I hoped it would :(

Tried everything I can think of!

**Comment by MarkPieszak** [comment]
Is there anyway to get npm to not exit the Lifecycle on Exit 1 errors?
