### ISSUE TITLE
Error installing Appium

### ISSUE THREAD

**Issue by robegs** [npm/npm#12428]
When I try to install  Appium I get this error:

pm http 200 https://registry.npmjs.org/options/-/options-0.0.6.tgz
npm http 200 https://registry.npmjs.org/ultron/-/ultron-1.0.2.tgz
npm ERR! weird error 1
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-remote-debugger/node_modules/appium-atoms/atoms/frame_by_id_or_name.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.16.0-38-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "appium"
npm ERR! cwd /home/roberto/appium-test
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-remote-debugger/node_modules/appium-atoms/atoms/frame_by_id_or_name.js
npm ERR! fstream_path /usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-remote-debugger/node_modules/appium-atoms/atoms/frame_by_id_or_name.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, chown '/home/roberto/tmp/npm-29679-tcnxadCB/1461248335312-0.24524033768102527/package/.travis.yml'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.16.0-38-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "appium"
npm ERR! cwd /home/roberto/appium-test
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /home/roberto/tmp/npm-29679-tcnxadCB/1461248335312-0.24524033768102527/package/.travis.yml
npm ERR! fstream_path /home/roberto/tmp/npm-29679-tcnxadCB/1461248335312-0.24524033768102527/package/.travis.yml
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! fstream_finish_call chown
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:305:19
npm ERR! fstream_stack /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! tar pack Error reading /home/roberto/tmp/npm-29679-tcnxadCB/1461248335311-0.6541080018505454/package
npm ERR! Error: ENOENT, lstat '/home/roberto/tmp/npm-29679-tcnxadCB/1461248335046-0.8238396469969302/package/coverage/coverage.json'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.16.0-38-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "appium"
npm ERR! cwd /home/roberto/appium-test
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /home/roberto/tmp/npm-29679-tcnxadCB/1461248335046-0.8238396469969302/package/coverage/coverage.json
npm ERR! fstream_path /home/roberto/tmp/npm-29679-tcnxadCB/1461248335046-0.8238396469969302/package/coverage/coverage.json
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! addLocalDirectory Could not pack "/home/roberto/tmp/npm-29679-tcnxadCB/1461248335311-0.6541080018505454/package" to "/home/roberto/.npm/options/0.0.6/package.tgz"
npm ERR! tar pack Error reading /home/roberto/tmp/npm-29679-tcnxadCB/1461248320780-0.8044157084077597/package
npm ERR! addLocalDirectory Could not pack "/home/roberto/tmp/npm-29679-tcnxadCB/1461248320780-0.8044157084077597/package" to "/home/roberto/.npm/lodash/3.10.1/package.tgz"
npm ERR! Error: ENOENT, lstat '/home/roberto/tmp/npm-29679-tcnxadCB/1461248335055-0.3593353843316436/package/BigInteger.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.16.0-38-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "appium"
npm ERR! cwd /home/roberto/appium-test
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /home/roberto/tmp/npm-29679-tcnxadCB/1461248335055-0.3593353843316436/package/BigInteger.js
npm ERR! fstream_path /home/roberto/tmp/npm-29679-tcnxadCB/1461248335055-0.3593353843316436/package/BigInteger.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-instruments/thirdparty/iwd7/TestApp.app/Frameworks/libswiftCore.dylib'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.16.0-38-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "appium"
npm ERR! cwd /home/roberto/appium-test
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-instruments/thirdparty/iwd7/TestApp.app/Frameworks/libswiftCore.dylib
npm ERR! fstream_path /usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-instruments/thirdparty/iwd7/TestApp.app/Frameworks/libswiftCore.dylib
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/appium/node_modules/appium-selendroid-driver/node_modules/appium-adb/jars/appium_apk_tools.jar'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.16.0-38-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "appium"
npm ERR! cwd /home/roberto/appium-test
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /usr/local/lib/node_modules/appium/node_modules/appium-selendroid-driver/node_modules/appium-adb/jars/appium_apk_tools.jar
npm ERR! fstream_path /usr/local/lib/node_modules/appium/node_modules/appium-selendroid-driver/node_modules/appium-adb/jars/appium_apk_tools.jar
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
ls
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/roberto/appium-test/npm-debug.log
npm ERR! not ok code 0

**Comment by KenanY** [comment]
@robegs `npm@1.3` is years old and no longer supported. Please try [upgrading](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm).

**Comment by KenanY** [comment]
@robegs ping

**Comment by othiym23** [comment]
Closing as abandoned.
