### ISSUE TITLE
Problem when i opened terminal in ubuntu it shows nvm prefix currently set to /usr/local and says run 'npm config delete-prefix v5.10.1 --silent?

### ISSUE THREAD

**Issue by tusar-nill** [npm/npm#12429]
I'm beginner in ubuntu .. I don't know what command works for .... 
nvm is not compatible with the npm config "prefix" option: currently set to "/usr/local"
Run `npm config delete prefix` or `nvm use --delete-prefix v5.10.1 --silent` to unset it.

I have tried npm config delete-prefix v5.10.1 --silent And I'm getting these errors
npm ERR! Error: ENOENT, unlink '/home/tusar-nill/.npmrc'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.2.0-35-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "config" "delete" "prefix"
npm ERR! cwd /home/tusar-nill
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /home/tusar-nill/.npmrc
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/tusar-nill/npm-debug.log
npm ERR! not ok code 0

How to solve these problem and how to solve this npm prefix problem?

**Comment by KenanY** [comment]
@tusar-nill `npm@1.3` is years old and no longer supported. Consider [upgrading](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm).

**Comment by KenanY** [comment]
@tusar-nill ping

**Comment by othiym23** [comment]
Closing as abandoned.
