### ISSUE TITLE
Can't install Script Atom Package

### ISSUE THREAD

**Issue by YairZiv5951** [npm/npm#12427]
Trying to install the Script Package in Atom and getting the next error:

npm WARN addRemoteGit Error: Command failed: 
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:658:15)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:98:17)
npm WARN addRemoteGit     at maybeClose (child_process.js:766:16)
npm WARN addRemoteGit     at Socket.<anonymous> (child_process.js:979:11)
npm WARN addRemoteGit     at Socket.emit (events.js:95:17)
npm WARN addRemoteGit     at Pipe.close (net.js:466:12)
npm WARN addRemoteGit  git://github.com/monsterkodi/node-simple-plist.git resetting remote C:\Users\User.atom.apm_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541 because of error: { [Error: Command failed: ] killed: false, code: 1, signal: null }
npm ERR! git clone C:\Users\User.atom.apm_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541 C:\Users\User\AppData\Local\Temp\npm-4220-88e261a7\git-cache-4ad547f6ca89\5ff35d61ff600391ccd784a18616fa73c09e0aea: Cloning into 'C:\Users\User\AppData\Local\Temp\npm-4220-88e261a7\git-cache-4ad547f6ca89\5ff35d61ff600391ccd784a18616fa73c09e0aea'...
npm ERR! git clone C:\Users\User.atom.apm_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541 C:\Users\User\AppData\Local\Temp\npm-4220-88e261a7\git-cache-4ad547f6ca89\5ff35d61ff600391ccd784a18616fa73c09e0aea: error: cannot spawn sh: No such file or directory
npm ERR! git clone C:\Users\User.atom.apm_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541 C:\Users\User\AppData\Local\Temp\npm-4220-88e261a7\git-cache-4ad547f6ca89\5ff35d61ff600391ccd784a18616fa73c09e0aea: fatal: unable to fork
npm ERR! git clone C:\Users\User.atom.apm_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541 C:\Users\User\AppData\Local\Temp\npm-4220-88e261a7\git-cache-4ad547f6ca89\5ff35d61ff600391ccd784a18616fa73c09e0aea: 
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\atom\app-1.7.2\resources\app\apm\bin\node.exe" "D:\atom\app-1.7.2\resources\app\apm\node_modules\npm\bin\npm-cli.js" "--globalconfig" "C:\Users\User\.atom\.apm\.apmrc" "--userconfig" "C:\Users\User\.atom\.apmrc" "install" "C:\Users\User\AppData\Local\Temp\d-116321-9176-l9d6wq\package.tgz" "--target=0.36.8" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code 128

npm ERR! Command failed: Cloning into 'C:\Users\User\AppData\Local\Temp\npm-4220-88e261a7\git-cache-4ad547f6ca89\5ff35d61ff600391ccd784a18616fa73c09e0aea'...
npm ERR! error: cannot spawn sh: No such file or directory
npm ERR! fatal: unable to fork
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

**Comment by ihorskyi** [comment]
You should show this to creator of that package - the issue is about incorrect identification of OS
Hints:
```npm ERR! Windows_NT 6.1.7601```
Windows_NT does not have ```sh``` - only *nux systems do
```
npm ERR! error: cannot spawn sh: No such file or directory
npm ERR! fatal: unable to fork
```
