### ISSUE TITLE
Search users via CLI

### ISSUE THREAD

**Issue by kevinSuttle** [npm/npm#12433]
It would be nice to be able to search users by 
- username
- email address
- scope/org/team
- packages 

You can _sort of_ do this now, but the APIs should be in place to search on a more narrow scope.

<img width="1440" alt="screen shot 2016-04-21 at 5 31 30 pm" src="https://cloud.githubusercontent.com/assets/95672/14724916/0693e4aa-07e7-11e6-8b96-f494ef2c4d62.png">

**Comment by mk-pmb** [comment]
Hi, I'd like to search packages by username as well. I can see some of my packages with
`npm search --parseable '~pmb'` or on https://npmsearch.com/?q=author:pmb ,
but I get no results when I write my full username,
`npm search --parseable '~mk-pmb'` or on https://npmsearch.com/?q=author:mk-pmb .
Any ideas?
