### ISSUE TITLE
Document that bin scripts should start with #!/usr/bin/env node so npm install will create proper node_modules/.bin scripts

### ISSUE THREAD

**Issue by dotchev** [npm/npm#12438]
If the .js script referenced in package.json > [bin](https://docs.npmjs.com/files/package.json#bin) does not start with  `#!/usr/bin/env node`, `npm install` generates a script under node_modules/.bin which starts directly the .js script without node executable.
This does not work at least on Windows.

This seems to be handled by [cmd-shim](https://github.com/ForbesLindesay/cmd-shim)

**Comment by mxstbr** [comment]
On it!
