### ISSUE TITLE
I can't delete folder which is locked in ubuntu 14.04 

### ISSUE THREAD

**Issue by tusar-nill** [npm/npm#12431]
I have tried to download a file via terminal use command 
sudo wget http://www.link/something 
After downloaded i cann't open or delete this file. And ls -l shows below line of information about this file 
drwxr-xr-x  3 root  root  700416 Apr  21 10:08 php-chunked-xhtml

I'm very beginner in ubuntu so please help me solve the my-mistake problem if i did.

**Comment by KenanY** [comment]
@tusar-nill Is this an issue with `npm`?

**Comment by tusar-nill** [comment]
@KenanY  actually I don't understand what it is .

**Comment by sethbergman** [comment]
1. Check the current owner/group/permissions status by right clicking the file/folder, clicking `Properties` and then switching to the `Permissions` tab.
2. Open a Terminal by hitting `Ctrl+Alt+t`.
If you are the Owner of the file (i.e. the Owner field shows your username): add write permission to the owner by running this command: `chmod u+w <path_to_file_folder>`
3. If you are not the Owner of the file, but you are in the Group (i.e. the Group field shows your username or a name of a group to which you belong, e.g. sudo): add write permission to the group by running this command: `sudo chmod g+w <path_to_file_folder>`
4. If you are not the Owner of the file and you are not in the Group: add write permission to the others by running this command: `sudo chmod o+w <path_to_file_folder>`

Alternatively:
5. Open a Terminal by hitting `Ctrl+Alt+t`.
Remove the file/folder as root by running this command: `sudo rm -rf <path_to_file_folder>`

**Comment by zkat** [comment]
This has nothing at all to do with npm or anything of the sort. Closing.
