### ISSUE TITLE
npm ERR! Refusing to install karma-jasmine as a dependency of itself

### ISSUE THREAD

**Issue by scv2** [npm/npm#12442]
```
C:\Coding\KarmaAndJasmine>npm install karma-jasmine --save-dev
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "karma-jasmine" "--save-dev"
npm ERR! node v5.11.0
npm ERR! npm  v3.8.6
npm ERR! code ENOSELF

npm ERR! Refusing to install karma-jasmine as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Coding\KarmaAndJasmine\npm-debug.log
```

Here's the log file:

[npm-debug.log.txt](https://github.com/npm/npm/files/232519/npm-debug.log.txt)

**Comment by KenanY** [comment]
@scv2 Is the `"name"` attribute of your `package.json` set to `"karma-jasmine"`?

**Comment by scv2** [comment]
@KenanY ,

I was using node 5.11.0 and npm v3.8.6
i thought it might be issue with latest version, so i downgraded node and npm to 
node 4.4.3 and npm 2.15.1

after this, when i try to install karma-jasmine, it gives no error but warning
C:\Coding\KarmaAndJasmine>npm install karma-jasmine --save-dev
npm WARN package.json karma-jasmine@1.0.0 No repository field.
npm WARN package.json karma-jasmine@1.0.0 No README data
npm WARN install Refusing to install karma-jasmine as a dependency of itself

but doesn't add anything to package.json

Any thought?

**Comment by scv2** [comment]
@KenanY 

Here's my package.json

"devDependencies": {
    "jasmine": "^2.4.1",
    "jasmine-core": "^2.4.1",
    "karma": "^0.13.22",
    "karma-chrome-launcher": "^0.2.3",
    "karma-phantomjs-launcher": "^1.0.0",
    "phantomjs": "^2.1.7",
    "phantomjs-prebuilt": "^2.1.7"
  }

**Comment by scv2** [comment]
found resolution for this:

C:\Coding\KarmaAndJasmine>npm install karma-jasmine --save-dev -f


i've no idea what '-f' does, but it seems pass over the warning and install 'karma-jasmine'

**Comment by othiym23** [comment]
Closing as resolved!

**Comment by sahilbabbar** [comment]
@scv2 `-f` is for forcing installation of the npm package.
