### ISSUE TITLE
Cannot execute npm on windows insider bash

### ISSUE THREAD

**Issue by Lorac** [npm/npm#12445]
I'm running Windows Insider with the Ubuntu Bash. When I'm trying to run npm

```
Microsoft Windows [Version 10.0.14328] (c) 2016 Microsoft Corporation. All rights reserved. 
C:\Users\Maxime>bash
maxime@MAXIME-PC:/mnt/c/Users/Maxime$ npm
fs.js:584 return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);  
Error: Unknown system error -25: Unknown system error -25, open '/usr/local/lib/node_modules/npm/bin/npm-cli.js' at Error (native) 
    at Object.fs.openSync (fs.js:584:18) 
    at Object.fs.readFileSync (fs.js:431:33) 
    at Object.Module._extensions..js (module.js:421:20) 
    at Module.load (module.js:357:32) 
    at Function.Module._load (module.js:314:12) 
    at Function.Module.runMain (module.js:447:10) 
    at startup (node.js:146:18) at node.js:404:3 
maxime@MAXIME-PC:/mnt/c/Users/Maxime$
```

I'm not sure if npm issue or the insider bash

**Comment by othiym23** [comment]
This is an issue with Node.js running under the Ubuntu environment within Windows. As [the team has discussed](https://www.youtube.com/watch?v=vLcOkHhEt1g) in previous team meetings, the Ubuntu compatibility layer and bash on Windows are unsupported until some of the many blocking cross-platform issues that arise in this environment are addressed. In this particular case, Node isn't even managing to load npm before something happens at the filesystem level that it can't handle. Good luck making it work, but until this is all a little more fully-baked, you're on your own. Thanks for your time!
