### ISSUE TITLE
cannot install npm

### ISSUE THREAD

**Issue by jamesscaggs** [npm/npm#12444]
```
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "-g" "install" "npm"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'has-unicode'
npm ERR!
npm ERR! If you need help, you may report this error at:


npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jamesscaggs/npm-debug.log
```

Here is my debug.log file:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   '-g',
1 verbose cli   'install',
1 verbose cli   'npm' ]
2 info using npm@2.15.1
3 info using node@v4.4.3
4 verbose stack Error: Cannot find module 'has-unicode'
4 verbose stack     at Function.Module._resolveFilename (module.js:325:15)
4 verbose stack     at Function.Module._load (module.js:276:25)
4 verbose stack     at Module.require (module.js:353:17)
4 verbose stack     at require (internal/module.js:12:17)
4 verbose stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-install-checks/node_modules/npmlog/node_modules/gauge/progress-bar.js:2:18)
4 verbose stack     at Module._compile (module.js:409:26)
4 verbose stack     at Object.Module._extensions..js (module.js:416:10)
4 verbose stack     at Module.load (module.js:343:32)
4 verbose stack     at Function.Module._load (module.js:300:12)
4 verbose stack     at Module.require (module.js:353:17)
4 verbose stack     at require (internal/module.js:12:17)
5 verbose cwd /Users/jamesscaggs
6 error Darwin 15.4.0
7 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "-g" "install" "npm"
8 error node v4.4.3
9 error npm  v2.15.1
10 error code MODULE_NOT_FOUND
11 error Cannot find module 'has-unicode'
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]
 ```

**Comment by Ricke21** [comment]
I'm having the same issue. 

npm install –g express
npm ERR! addLocal Could not install /usr/–g
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "–g" "express"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1

npm ERR! The header content contains invalid characters
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "–g" "express"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! path npm-debug.log.41316913
npm ERR! code EPERM
npm ERR! errno -1
npm ERR! syscall open

npm ERR! Error: EPERM: operation not permitted, open 'npm-debug.log.41316913'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM: operation not permitted, open 'npm-debug.log.41316913']
npm ERR!   errno: -1,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'open',
npm ERR!   path: 'npm-debug.log.41316913' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/npm-debug.log

**Comment by KenanY** [comment]
@Ricke21 Looks like a completely different issue. Try using a regular hyphen instead of a hyphen-minus for the `-g` flag.

**Comment by Ricke21** [comment]
Thank you, Nice eye.  
I also found a whole new keyboard œ∑åΩ≈ß∑´∂ç√ƒ®†©∫˜˙¥¨∆µ˚ˆø¬≥÷…π“æ÷ºª•¶§∞¢£™¡

Awesome- any side projects you need Kickstarted?

**Comment by kmanion** [comment]
Hi @jamesscaggs, the error ​sounds_ like it can't find a dependency while installing, but it's actually the ​existing copy of `npm` that's crashing, because it's incomplete. The solution is to `rm -fr /usr/local/lib/node_modules/npm` (maybe w/ `sudo`) and then reinstall Node. 

Let me know if this helps.

**Comment by jamesscaggs** [comment]
You were right. I uninstalled and reinstalled and everything worked fine.
Thank you!
