### ISSUE TITLE
can't install gulp

### ISSUE THREAD

**Issue by marina-cs** [npm/npm#12456]
can't install gulp on Mac 10.11.2

npm WARN package.json gulp-project@1.0.0 No repository field.
npm WARN package.json gulp-project@1.0.0 No README data
npm WARN package.json gulp-project@1.0.0 No license field.

and the other problem: 
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.

 here is the log
[npm-debug.log.txt](https://github.com/npm/npm/files/233629/npm-debug.log.txt)

**Comment by ericmdantas** [comment]
Gulp is being installed just fine, those are just warnings about your package.json and some deprecation warnings.

**Comment by marina-cs** [comment]
https://github.com/agragregra/start_html/tree/master/_optimized_gulp_sass what is wrong with this json? I've installed it

**Comment by ericmdantas** [comment]
Nothing really wrong, it's just missing two properties: repository url and license. 

It's also letting you know you have no README.md in the same folder you're in.

**Comment by marina-cs** [comment]
i'm sorry can we use teamviewer?

**Comment by ericmdantas** [comment]
Sure

**Comment by marina-cs** [comment]
ID 136 518 140 password 1741

**Comment by ericmdantas** [comment]
This can be closed since it's not a problem with npm itself.

**Comment by EvaPawlowskiBit** [comment]
unsuscribe

Von: Marina [mailto:notifications@github.com]
Gesendet: Montag, 25. April 2016 08:51
An: npm/npm <npm@noreply.github.com>
Betreff: Re: [npm/npm] can't install gulp (#12456)


Closed #12456<https://github.com/npm/npm/issues/12456>.
