### ISSUE TITLE
Cannot update global installed npm packages

### ISSUE THREAD

**Issue by rudolfschmidt** [npm/npm#12461]
```
$ sudo npm update -g
npm ERR! addLocal Could not install /build/semver/src/semver-5.1.0.tgz
npm ERR! addLocal Could not install /build/semver/src/semver-5.1.0.tgz
npm ERR! addLocal Could not install /build/npm/src/npm
```

```
$ npm -v
3.8.7
```

```
$ node -v
v5.11.0
```

any ideas whats wrong? google tells not a lot

**Comment by murth** [comment]
Getting the same:

npm ERR! addLocal Could not install /build/semver/src/semver-5.1.0.tgz
npm ERR! addLocal Could not install /build/semver/src/semver-5.1.0.tgz
npm ERR! addLocal Could not install /build/semver/src/semver-5.1.0.tgz
npm ERR! addLocal Could not install /build/gulp/src/gulp-3.9.1.tgz
npm ERR! addLocal Could not install /build/typescript/src/typescript-1.8.10.tgz
npm ERR! addLocal Could not install /build/npm/src/npm

However, I reinstalled each item with:
$ sudo npm install -g semver
etc, and npm was then happy with global updates.
However, i noticed the pattern, which is that each of these package I also have installed via my package manager on Arch linux, so I guess there's some kind of conflict happening due to that.

**Comment by rudolfschmidt** [comment]
I also use arch linux and after updating the packages individually I got that output:
$ sudo npm -g update
npm ERR! addLocal Could not install /build/npm/src/npm

**Comment by murth** [comment]
Did you also do 
$ sudo npm install -g npm
Because that was required for me to get rid of all the messages too.

**Comment by vitaliy-kuzmich** [comment]
I have the same issue.

**Comment by rudolfschmidt** [comment]
@murth I have tried it already. Same result.

**Comment by brianlinuxing** [comment]
I got the same error running it on a Pi 3 and Manjaro ARM.

It complained "npm WARN enoent ENOENT: no such file or directory, open '/root/package.json'"

1.My first clumsy solution (your mileage may vary) was to create it with t**ouch /root/package.json** but that doesn't work, therefore I did a 

**npm init
npm install semver**

2. which seemed to work, only a warning, but then a  **npm update -g** shows:

npm ERR! addLocal Could not install /build/semver/src/semver-5.1.0.tgz
npm ERR! addLocal Could not install /build/typescript/src/typescript-1.8.10.tgz
npm ERR! addLocal Could not install /build/semver/src/semver-5.1.0.tgz

Removing **pacman -R typescript** fixes one of the errors.

3. Removing semver and re-installing works to a fashion, but leaves it as semver@4.3.6 

$ **sudo npm remove semver**
$ **sudo npm install semver**
atom@1.8.0 /home/manjaro/atom
`-- semver@4.3.6 

$ **sudo npm update -g**
npm ERR! addLocal Could not install /build/semver/src/semver-5.1.0.tgz
npm ERR! addLocal Could not install /build/semver/src/semver-5.1.0.tgz

**Comment by angel333** [comment]
Maybe not the perfect solution, but installing npm outside of pacman worked for me. Either change [the prefix](https://docs.npmjs.com/getting-started/fixing-npm-permissions#option-2-change-npms-default-directory-to-another-directory) and reinstall npm, or, if you want to keep the system-wide prefix, you can do something like this:

```
# Install a temporary npm somewhere
mkdir /tmp/npmtmp && cd $_
npm install npm

# Remove pacman's npm
sudo pacman -Rns --noconfirm npm

# Install npm globally using the temporary npm
sudo /tmp/npmtmp/node_modules/.bin/npm install -g npm
```

**Comment by aureooms** [comment]
This solves the issue
```
sudo npm i -g npm
sudo npm i -g semver
```

**Comment by TheAifam5** [comment]
https://github.com/npm/npm/issues/10165

**Comment by noraj1337** [comment]
```
$ node -v
v7.1.0

$ npm -v
3.10.9

$ npm update -g
npm ERR! addLocal Could not install /build/npm/src/npm
```

**Comment by archpoint** [comment]
Same here on Arch Linux running on the Raspberry Pi. npn update -g returns nothing.

**Comment by Frederick888** [comment]
Package managers like `pip` and `npm` never works well with system package managers when things come to global packages :(

**Comment by noraj** [comment]
This convenient to have a bot closing issue...
