### ISSUE TITLE
package.json/script: path/to/a/script.js

### ISSUE THREAD

**Issue by sarbbottam** [npm/npm#12483]
`npm scripts` are great, I personally prefer it over any other workflow tools. However, its bloating the `package.json` with [excessive usage](https://github.com/ReactiveX/rxjs/blob/a3ec89605a24a6f54e577d21773dad11f22fdb14/package.json#L14-L96)

[p-s](https://www.npmjs.com/package/p-s) has a workaround to mitigate it.

Please find the excerpt from [p-s](https://www.npmjs.com/package/p-s)'s [readme]

> npm scripts have a ton of advantages ([learn more](https://medium.freecodecamp.com/why-i-left-gulp-and-grunt-for-npm-scripts-3d6853dd22b8#.9qghcfdr9)), it can grow into an
> [unmaintainable mess](https://github.com/ReactiveX/rxjs/blob/a3ec89605a24a6f54e577d21773dad11f22fdb14/package.json#L14-L96) in your `package.json` file. Part of the problem is we're configuring scripts in `json` which has fundamental issues (like no comments).

---

Wondering if a `file path` can be passed instead of an `object like` in `package.json`

```
...
"scripts": "path/to/scripts.js",
...
```

[run-script](https://github.com/npm/npm/blob/master/lib/run-script.js) on reading the `package.json/scripts`

```
if scripts is a string and path to a file
   read the file 
   business as usual, 
else 
   business as usual
```

**Comment by sarbbottam** [comment]
If this is accepted, I am happy to work on a PR, with a little guidance.

**Comment by gustavnikolaj** [comment]
This issue seems to be conflicting with the answer that @othiym23 gave [here](https://github.com/npm/npm/issues/11418#issuecomment-180640530) in issue #11418

While explaining why the proposal weren't good enough, an argument were made against changing the scripts property.

> As @iarna wrote, the technical problem with using arrays and nested object literals to decompose package scripts is that old versions of npm aren't forward-compatible with either, meaning this is a breaking change to the ecosystem. 

The proposal to change it to a reference to a file would have the exact same problem. :-)
