### ISSUE TITLE
Errors at angular2 quickstart..

### ISSUE THREAD

**Issue by ioakranas** [npm/npm#12494]
I'm new at developing and angular2 and i tried the quickstart tutorial.
I c/p everything from the tutorial but when i type "npm start" to run the quickstart i have this errors..
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.4.3
npm ERR! npm v2.15.1
npm ERR! missing script: start

I have closed windows firewall and i don't have any antivirys program..
Also in my package.json file i have the script
"scripts": {
    "start": "tsc && concurrently \"npm run tsc:w\" \"npm run lite\" "

Any suggestions??

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.15.1
3 info using node@v4.4.3
4 verbose stack Error: missing script: start
4 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:142:19)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:58:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:345:5
4 verbose stack     at handleExists (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:318:20)
4 verbose stack     at FSReqWrap.cb [as oncomplete] (fs.js:212:19)
5 verbose cwd C:\Program Files\nodejs\node_modules\npm\bin\angular2-quickstart
6 error Windows_NT 6.1.7601
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
8 error node v4.4.3
9 error npm  v2.15.1
10 error missing script: start
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@ioakranas Can I see
`C:\Program Files\nodejs\node_modules\npm\bin\angular2-quickstart\package.json`?

**Comment by ioakranas** [comment]
Is the same as the tutorial - quickstart..
This is my package.json 

{
  "name": "angular2-quickstart",
  "version": "1.0.0",
  "scripts": {
    "start": "tsc && concurrently \"npm run tsc:w\" \"npm run lite\" ",
    "lite": "lite-server",
    "postinstall": "typings install",
    "tsc": "tsc",
    "tsc:w": "tsc -w",
    "typings": "typings"
  },
  "license": "ISC",
  "dependencies": {
    "angular2": "2.0.0-beta.16",
    "systemjs": "0.19.26",
    "es6-shim": "^0.35.0",
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-beta.2",
    "zone.js": "0.6.12"
  },
  "devDependencies": {
    "concurrently": "^2.0.0",
    "lite-server": "^2.2.0",
    "typescript": "^1.8.10",
    "typings":"^0.8.1"
  }
}

**Comment by KenanY** [comment]
@ioakranas What does `npm run-script` return? Should list all the scripts.

**Comment by ioakranas** [comment]
Lifecycle scripts included in npm:
   prepublish
       node bin/npm-cli.js prune --prefix=. --no-global && rimraf test/*/*/mode_modules && make -j4 doc
   preversion
        bash scripts/update-authors.sh && git add AUTHORS && git commit -m "update AUTHORS" || true
   test
       npm run test-tap

available via 'npm run-script':
   dumpconf
       env | grep npm | sort | uniq
   tap
       tap --timeout 240
   test-tap
       npm run tap -- "test/tap/*.js"

**Comment by KenanY** [comment]
@ioakranas Looks like you are not running these commands from the right directory. You need to ensure that you are in the directory which contains the `package.json` with a `"start"` script. As your latest output shows, you are in `npm`'s source directory; those scripts are `npm`'s (as you can see [here](https://github.com/npm/npm/blob/db5d7cdf2e2539f38978249cb0ef591370efd322/package.json#L203-211)). So far this is not an issue with `npm`.

**Comment by ioakranas** [comment]
I'm running these commands from C:\nodejs\node_modules\npm\bin\angular2-quickstart>

At the angular2-quickstart folder is the package.json ...

**Comment by ioakranas** [comment]
@KenanY thanks for the help!!

**Comment by ioakranas** [comment]
Finally i found the problem..
Every file i saved had .txt extension (.json.txt)....

**Comment by KenanY** [comment]
@ioakranas Interesting... :smile:
