### ISSUE TITLE
npm WARN notsup Not compatible with your operating system or architecture

### ISSUE THREAD

**Issue by hechuanhua** [npm/npm#12497]
npm WARN optional Skipping failed optional dependency /webpack/watchpack/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.11
I have installed webpack some of the plugins have been a little bit of a problem, is this information affected?
version ：
win10  64
nodejs : 6.0
npm 3.8.3

**Comment by KenanY** [comment]
@hechuanhua `fsevents` is Mac only, so you can safely ignore that warning.

**Comment by othiym23** [comment]
Closing as resolved, by @KenanY, who as always is very helpful.
