### ISSUE TITLE
Error when installing themes and plugins

### ISSUE THREAD

**Issue by TheHanns** [npm/npm#12492]
Here's a screenshot i took. I tried to completely uninstall atom.
<img src="http://fotos.subefotos.com/a6cb62ee23446283160df78895949976o.jpg" href="http://fotos.subefotos.com/a6cb62ee23446283160df78895949976o.jpg" target="_blank"/>

Thank you all.

**Comment by KenanY** [comment]
@TheHanns From https://github.com/npm/npm/issues/3858#issuecomment-64730272:

> 1. Something unspecified is wrong with I/O on the system – the hard drive is going bad, something's wrong with the block device driver, the OS is having a meltdown, or
> 2. You're running Windows and somehow you've ended up with a system codepage installed that's incompatible with how you're naming things. `chcp 850` in `cmd.exe` should fix this.

**Comment by KenanY** [comment]
@TheHanns Are you still facing this issue?

**Comment by TheHanns** [comment]
@KenanY Yes i do, meanwhile i'm using sublime... I hope i can switch again to Atom without getting this issue
