### ISSUE TITLE
Transitive dependencies sometimes not installed

### ISSUE THREAD

**Issue by gustavnikolaj** [npm/npm#12503]
I have a hard to debug deduplication error (I assume), which is reproducible, but hard to cage in for me.

It happens in the project [assetgraph/assetgraph](https://github.com/assetgraph/assetgraph/) and is happening consistently [on CI](https://travis-ci.org/assetgraph/assetgraph/builds/122372717) since we upgraded chalk from 1.1.2 to 1.1.3.

All the build errors manifest the same way - by eslint not being able to find a module called 'has-ansi' required by 'chalk' in one of it's repoters. Because of [a bug in eslint](https://github.com/eslint/eslint/issues/5977), it shows as if the loader couldn't be loaded though:

```
> assetgraph@2.3.0 lint /home/travis/build/assetgraph/assetgraph
> eslint .
Could not find formatter 'stylish'.
```

It fails on node 5 and 6, but not on 0.10, 0.12, or 4. Which lead me to think that it was related to npm version 3. I have been able to confirm that by running the following commands from a clean checkout of [current HEAD](https://github.com/assetgraph/assetgraph/tree/9c483ef273d4d64027ad47f9e7f056b78a67bd14) of AssetGraph.

```
$ npm install && echo "node: `node -v`" && echo "npm: `npm -v`" && npm run lint
```

That yields the following outputs, with different configurations:

```
$ npm install && echo "node: `node -v`" && echo "npm: `npm -v`" && npm run lint
... truncated npm install output ...
node: v0.10.42
npm: 2.15.2

> assetgraph@2.3.0 lint /home/gno/Scratch/reproDedupError
> eslint .

```

```
$ npm install && echo "node: `node -v`" && echo "npm: `npm -v`" && npm run lint
node: v5.11.0
npm: 2.15.4

> assetgraph@2.3.0 lint /home/gno/Scratch/assetgraph-test/assetgraph
> eslint .

```

```
$ npm install && echo "node: `node -v`" && echo "npm: `npm -v`" && npm run lint
... truncated npm install output ...
node: v5.10.1
npm: 3.8.3

> assetgraph@2.3.0 lint /home/gno/Projects/assetgraph
> eslint .

Could not find formatter 'stylish'.

npm ERR! Linux 4.2.0-35-generic
... truncated error output ...
```

```
$ npm install && echo "node: `node -v`" && echo "npm: `npm -v`" && npm run lint
... truncated npm install output ...
node: v5.11.0
npm: 3.8.7

> assetgraph@2.3.0 lint /home/gno/Scratch/assetgraph-test/assetgraph
> eslint .

Could not find formatter 'stylish'.

npm ERR! Linux 4.2.0-35-generic
... truncated error output ...
```

It fails consistently with npm@3, and it works with npm@2. Running npm install again, after having triggered the error with npm@3, will actually install the missing package, and fix the problem.

That makes me really certain that this problem is related to npm and npm 3 in particular.

I have spent a long time trying to reproduce this with a smaller set of packages, but I haven't been able to. I hope that I provided enough information that you will be able to pick it up.

Let me know if there's any details missing.

**Comment by zkat** [comment]
I wasn't able to reproduce this on `npm@3.8.9`, please lmk if this is still an issue, @gustavnikolaj

**Comment by papandreou** [comment]
@zkat It's still reproducible, also with npm 3.8.8 and 3.8.9. We upgraded some dependencies on assetgraph master since then, including eslint, which somehow makes it no longer happen there.

Please check out the commit assetgraph 566fbed972, which represents the state at the time this was reported. It can still be reproduced there.

**Comment by zkat** [comment]
Thanks, @papandreou! I'll take a look probably next week. :)

**Comment by zkat** [comment]
I tried this in a few different ways with various combinations on that commit, and couldn't reproduce it. :( Does your repro case work across machines, @papandreou ?

**Comment by papandreou** [comment]
It seems to happen consistently on Travis. I branched out from the bad commit, removed the workaround (an extra `npm install`), and kicked off a build just now: https://travis-ci.org/assetgraph/assetgraph/jobs/129258165

However, I just tried twice on my laptop, and it worked fine both times. Previously it has been reproduced on my computer at work and @gustavnikolaj's.

So yeah, it seems like it's one of those intermittent issues :/

**Comment by schmod** [comment]
#10727 also deals with transitive dependencies, and has the same workaround (run `npm install` twice).  

I suspect that #12503, #11386, and #10727 are all closely related.

**Comment by schmod** [comment]
I can't repro this with [assetgraph/assetgraph](https://github.com/assetgraph/assetgraph/) and NPM 3.8.7, even if I go back to a commit from around the time you opened this issue.  

I'm about to submit a PR that solves the transitive dependency issues described in #10727.  If you have steps to consistently repro the issue that you're seeing with assetgraph, I'd love to verify that my fix solves this issue as well.

**Comment by papandreou** [comment]
@schmod That sounds great! It seems to repro consistenly on Travis and on my work computer. Let me know when you've pushed your branch, then I'll try it out.

**Comment by papandreou** [comment]
@schmod, I [switched to your patch](https://github.com/assetgraph/assetgraph/commit/cbc739af27ae140aac3b6f9d696e2f57f04b126d) on my test branch, which fixed the build: https://travis-ci.org/assetgraph/assetgraph/jobs/132409036

Just to be sure, I [switched to the commit right before your fix](https://github.com/assetgraph/assetgraph/commit/bac301aed5bfe2b37b809388ea2467684184dd5f) and pushed the branch again, and it also worked: https://travis-ci.org/assetgraph/assetgraph/jobs/132410596

... which seems to indicate that the problem can no longer be reproduced on Travis, or that new versions of some secondary dependencies been published. I'll try on my work computer tomorrow.
