### ISSUE TITLE
Allow checkout of a git repo directly into node_modules

### ISSUE THREAD

**Issue by kring** [npm/npm#12506]
`npm install` currently bails when it detects that a directory in `node_modules` has a `.git` subdirectory.  In order to provide a much more convenient way of working on multiple packages in a modular application, I propose that it should not bail and instead:
1. npm _should_ skip installing anything into that directory.  Also `npm prune` shouldn't remove it.
2. npm should _not_ replace it with another package under any circumstances.  If the package's version is incompatible, npm should inform the user of this but not attempt to, e.g., upgrade it with a new version from the npm ergistry.
3. npm _should_ do as it pleases with that package's `node_modules` directory.  Specifically, packages should be de-duplicated exactly as if npm had installed this package itself from the registry.
4. npm _should_ (perhaps optionally?) install the package's `devDependencies` in addition to its `dependencies`.  Again, these should be deduplicated.  The way I think about it is: "pretend all of this one package's `devDependencies` are added to `dependencies` and then run the `npm install` algorithm normally."

This avoids a lot of the complexity, caveats, and potential for bugs in using `npm link`.  Some examples of the problems with `npm link`:

https://github.com/npm/npm/issues/10800
https://github.com/npm/npm/milestones/understandable%20links
https://github.com/substack/node-browserify/issues/692

I think that many of these reported problems aren't actually bugs, but rather flaws with the `npm link` approach.  In npm 3, deduplication is the default.  Packages are installed in the top-level node_modules folder, unless there is a version conflict.  But this presents a problem for `npm link`.  If my package C is a dependency of two packages A and B, the contents of C's deduplicated `node_modules` directory is potentially different based on the set of packages depended on by A versus B.  When C is shared between A and B via `npm link`, correct deduplication is impossible.  Worse, we can't really tell if C might be shared like that, so we have to assume it is.

That leads to what I believe is the current approach used by npm: linked packages are entirely responsible for their own dependencies; deduplication will never move packages in or out of a linked package.  I believe npm has some bugs in its attempt to do this at the moment, but even if they were all fixed, the situation is still less than ideal because it prevents deduplication.  Without deduplication, it's relatively easy for multiple copies of the same (or different but semver-compatible) modules to be loaded, and I've personally seen things break as a result of this.  For example, the Webpack node API gets angry if you construct one of its plugins from one copy of Webpack and try to use it with another.  The `node-browserify` bug above is another symptom of this problem.

On top of these problems with linking, I'd argue that the shared-dependency model provided by `npm link` is not even useful in most cases.  When I'm working on my modular app, I commonly need to also make changes to the packages that it is made up of.  That's why I use npm link.  Very rarely do I need to do this from multiple applications simultaneously, and when I do, I can easily use git to move changes between separate copies of the common dependency package.

So, a simpler model that lets me use a package checked out from git directly in my node_modules directory would satisfy this very common use-case without all the caveats and pitfalls of npm link.

I think possibly `npm link` made sense in the old days of npm when - as I remember and understand it - deduplication was not the default and each package had a local `node_modules` directory with its own dependencies.  It was necessary to be able to link a single copy of the code into multiple places in that dependency tree.  But today, where we usually only have one copy of each package _except if there are version conflicts_, all we really need is to be able to make that one copy a fully functional git repo.

If this proposal makes sense, I plan to look into adding the feature and opening a pull request.  I'd love to hear any feedback or criticism first, though.

**Comment by kring** [comment]
I've implemented this as a wrapper around npm:
https://www.npmjs.com/package/npmgitdev

It's a bit hacky, but has already drastically improved my life. :)

**Comment by ChrisRus** [comment]
I've had poor success with webpack/babel/etc. when working with npm link. This is highly frustrating.

To simplify, I've got a project going currently that has one top-level package and four dependency packages -under-development cloned in node_modules. Works like a charm except for the fact that it completes breaks npm.

In my example, I have declared dependencies on the four sub-packages I'm working on that specify private github repos sans commit tag. In this case, I believe npm will want to refetch and overwrite. Why not just skip this operation and continue without error if the directory happens to be a git repo?

**Comment by kring** [comment]
@ChrisRus have you tried the `npmgitdev` tool mentioned above?  My experience with webpack/babel was similar to yours; I found `npm link` completely unworkable.  `npmgitdev` is a decent solution.

**Comment by ChrisRus** [comment]
@kring - I have not but will look into it. Really, I cannot understand why npm link makes _any_ sense at all given that this seemingly trivial change would:

* Make developing large projects with dozens of dependent packages under development simpler to manage
* Very friendly for highly-automated build, test, deploy scenarios.
* Zero native filesystem issues.

**Comment by kring** [comment]
Let me know how you go @ChrisRus.  I think it makes a lot of sense for npm to do what npmgitdev does out of the box, but we'll need a lot more than just me thinking so before it will happen. :)

**Comment by ChrisRus** [comment]
Hi, @kring. Been busy enough to not worry so much about this. It's a bit sloppy but added a gulp task and npm run verbs that allow me to mv my subprojects out of node_modules and my packages back in (and vice-versa). As one doesn't typically pick up a lot of new dependencies once you're rolling it's not that big of a deal I guess. Once the task at hand is done, then I'm going to take a look at npmgitdev more closely. Thanks for the suggestion!

**Comment by nenadalm** [comment]
hi. I just came across this, as I was looking how to do that.

Here is how it works for clojure: https://github.com/technomancy/leiningen/blob/master/doc/TUTORIAL.md#checkout-dependencies

terminology:
- leiningen = npm
- project.clj = package.json

So what the link says is that additional directory with packages can exist. Package manager then uses modules from the directory or external registry (in case the directory doesn't contain the package).
