### ISSUE TITLE
Very easy to hit MAX_PATH failures when installing from Git URL with npm@3 defaults

### ISSUE THREAD

**Issue by theoy** [npm/npm#12501]
This happened to my team in a real world scenario, since many use Windows (and npm@3, with its awesome deduping behaviour).

Our Git remote URL is 103 characters long (once you include the `https://`), because of DNS name of our Git host, their URL partitioning scheme, and then our organisation's sub-partitioning scheme.

However, we easily hit this error (root cause is Git exe):

```
npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\A
BCDEFG\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://abcde
fghijklmnopqrstovwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdef
ghijklmnopq C:\Users\ABCDEFG\AppData\Roaming\npm-cache\_git-remotes\git-https-a
bcdefghijklmnopqrstovwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzab
cdefghijklmnopq-f88e2d9ceefe67871695cf2f8726ca57115a8bf8-45dab77b

npm ERR! fatal: insane git directory C:/Users/ABCDEFG/AppData/Roaming/npm-cache
/_git-remotes/git-https-abcdefghijklmnopqrstovwxyzabcdefghijklmnopqrstuvwxyzabc
defghijklmnopqrstuvwxyzabcdefghijklmnopq-f88e2d9ceefe67871695cf2f8726ca57115a8b
f8-45dab77b
```

This is a combination of:
- default location of `npm` CLI cache on Windows
- cache FS scheme for Git remotes
- Windows MAX_PATH limitation (260 chars)

Let's assume the Windows user name is a reasonable maximum (e.g. 8 characters), this leaves the default cache directory for git remotes to be 

```
C:/Users/ABCDEFGH/AppData/Roaming/npm-cache/_git-remotes/
```

... or 57 characters long.

On top of it, I believe in the current scheme, npm always concatenates the resolved commit hash of the Git remote, which is 40 characters.

And then... for git's own internal storage, it usually wants approximately 54 characters - for example:

```
.git/objects/01/23456789abcdef0123456789abcdef01234567
```

That basically causes ~58% (151/260) of the path length budget to be taken up just from overhead, even before the user-provided path is factored in 😦 
## Suggestion

Change cache path scheme for URL-based installs to more resilient to long URLs, by say using a hash+overflow. For example,
1. A user installs with a Git URL that resolves to a URL + Commit hash (ID tuple)
2. Hash the ID tuple (say, even 40-len SHA1 `0123...def01234567)
3. Next level subdirectory is for hypothetical hash collisions (`1/`, `2/`, ...)
4. Inside the cache directory, verify with the full ID tuple contents

C:/Users/ABCDEFGH/AppData/Roaming/npm-cache/_git-remotes/01/23456789abcdef0123456789abcdef01234567/1/

This makes the cache folder typically 102 characters, + 54 for Git internal representation makes it nearly impossible to exceed MAX_PATH unless you have astronomical numbers of SHA1 hash collisions.

Yes, this is slower to calculate than the current path partitioning scheme... but I think this shouldn't be in a hot path hopefully, and it should only need to be calculated/allocated once per invocation per remote.

**Comment by DJviolin** [comment]
Maybe my issue connected to this?

https://github.com/npm/npm/issues/12534
