### ISSUE TITLE
npm install osrm not working on Windows

### ISSUE THREAD

**Issue by rcalcaraz** [npm/npm#12500]
**npm version:** 3.8.7
**node version:** 4.4.0
**so:** Windows 10 Home

**Output**
> npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Rafa\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm
-cli.js" "install" "osrm"
npm ERR! node v4.4.0
npm ERR! npm  v3.8.7
npm ERR! code ENOSELF
npm ERR! Refusing to install osrm as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Rafa\Desktop\osrm\npm-debug.log

**Error log**

> 0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Rafa\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'osrm' ]
2 info using npm@3.8.7
3 info using node@v4.4.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData osrm
8 silly fetchNamedPackageData osrm
9 silly mapToRegistry name osrm
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'osrm',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   name: 'osrm',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/osrm
14 verbose request uri https://registry.npmjs.org/osrm
15 verbose request no auth needed
16 info attempt registry request try #1 at 21:34:55
17 verbose request id 985d77e7158af808
18 verbose etag "AWNIXT9UKY93XPUPNUGHDG4VH"
19 http request GET https://registry.npmjs.org/osrm
20 http 304 https://registry.npmjs.org/osrm
21 verbose headers { date: 'Wed, 27 Apr 2016 19:34:52 GMT',
21 verbose headers   via: '1.1 varnish',
21 verbose headers   'cache-control': 'max-age=300',
21 verbose headers   etag: '"AWNIXT9UKY93XPUPNUGHDG4VH"',
21 verbose headers   age: '136',
21 verbose headers   connection: 'keep-alive',
21 verbose headers   'x-served-by': 'cache-lhr6348-LHR',
21 verbose headers   'x-cache': 'HIT',
21 verbose headers   'x-cache-hits': '1',
21 verbose headers   'x-timer': 'S1461785692.809540,VS0,VE0',
21 verbose headers   vary: 'Accept-Encoding' }
22 silly get cb [ 304,
22 silly get   { date: 'Wed, 27 Apr 2016 19:34:52 GMT',
22 silly get     via: '1.1 varnish',
22 silly get     'cache-control': 'max-age=300',
22 silly get     etag: '"AWNIXT9UKY93XPUPNUGHDG4VH"',
22 silly get     age: '136',
22 silly get     connection: 'keep-alive',
22 silly get     'x-served-by': 'cache-lhr6348-LHR',
22 silly get     'x-cache': 'HIT',
22 silly get     'x-cache-hits': '1',
22 silly get     'x-timer': 'S1461785692.809540,VS0,VE0',
22 silly get     vary: 'Accept-Encoding' } ]
23 verbose etag https://registry.npmjs.org/osrm from cache
24 verbose get saving osrm to C:\Users\Rafa\AppData\Roaming\npm-cache\registry.npmjs.org\osrm\.cache.json
25 verbose correctMkdir C:\Users\Rafa\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
26 silly install normalizeTree
27 silly loadCurrentTree Finishing
28 silly loadIdealTree Starting
29 silly install loadIdealTree
30 silly cloneCurrentTree Starting
31 silly install cloneCurrentTreeToIdealTree
32 silly cloneCurrentTree Finishing
33 silly loadShrinkwrap Starting
34 silly install loadShrinkwrap
35 silly loadShrinkwrap Finishing
36 silly loadAllDepsIntoIdealTree Starting
37 silly install loadAllDepsIntoIdealTree
38 silly rollbackFailedOptional Starting
39 silly rollbackFailedOptional Finishing
40 silly runTopLevelLifecycles Starting
41 silly runTopLevelLifecycles Finishing
42 silly install printInstalled
43 verbose stack Error: Refusing to install osrm as a dependency of itself
43 verbose stack     at checkSelf (C:\Users\Rafa\AppData\Roaming\npm\node_modules\npm\lib\install\validate-args.js:53:14)
43 verbose stack     at Array.<anonymous> (C:\Users\Rafa\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
43 verbose stack     at LOOP (C:\Users\Rafa\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
43 verbose stack     at chain (C:\Users\Rafa\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
43 verbose stack     at C:\Users\Rafa\AppData\Roaming\npm\node_modules\npm\lib\install\validate-args.js:16:5
43 verbose stack     at C:\Users\Rafa\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
43 verbose stack     at Array.forEach (native)
43 verbose stack     at C:\Users\Rafa\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
43 verbose stack     at Array.forEach (native)
43 verbose stack     at asyncMap (C:\Users\Rafa\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
44 verbose cwd C:\Users\Rafa\Desktop\osrm
45 error Windows_NT 10.0.10586
46 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Rafa\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "osrm"
47 error node v4.4.0
48 error npm  v3.8.7
49 error code ENOSELF
50 error Refusing to install osrm as a dependency of itself
51 error If you need help, you may report this error at:
51 error     <https://github.com/npm/npm/issues>
52 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@rcalcaraz Is the `"name"` field of your `package.json` set to `"osrm"`? Have you tried changing it to something else?

**Comment by KenanY** [comment]
Closing as abandoned.
