### ISSUE TITLE
inaccurate handling of error messages when the registry URL path is not at root

### ISSUE THREAD

**Issue by peterlynch** [npm/npm#12512]
In the case of private registries, the root of the registry may be under 1 or more path parts. This path nesting seems to confuse the error handling of the NPM client.

Examples - using a registry that is mapped to the base path, the error message looks decent:

```
> npm info invalid-package --registry=http://registry.npmjs.org/
npm ERR! Darwin 15.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "info" "invalid-package" "--registry=http://registry.npmjs.org/"
npm ERR! node v0.12.2
npm ERR! npm  v3.8.7
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on http://registry.npmjs.org/invalid-package
npm ERR! 404 
npm ERR! 404  'invalid-package' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /npm/test/npm-debug.log
```

Now try the same command for a registry that is not at base path ( a private registry ):

```
> npm install invalid-package --registry=http://localhost:8081/repository/npm-proxy/
npm ERR! Darwin 15.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "invalid-package" "--registry=http://localhost:8081/repository/npm-proxy/"
npm ERR! node v0.12.2
npm ERR! npm  v3.8.7
npm ERR! code E404

npm ERR! 404 Package 'invalid-package' not found : repository
npm ERR! 404 
npm ERR! 404  'repository' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /npm/test/npm-debug.log
```

The message `'repository' is not in the npm registry.` is poorly constructed. "repository" is a path part, not the package. It should read:

> 'invalid-package' is not in the npm registry

Also "Package 'invalid-package' not found" in this case is a message included in the JSON payload response for the 404:

```
< HTTP/1.1 404 Not Found
< Date: Thu, 28 Apr 2016 15:08:49 GMT
< Server: Nexus/3.0.0-03 (OSS)
< X-Frame-Options: SAMEORIGIN
< X-Content-Type-Options: nosniff
< Content-Type: application/json
< Content-Length: 63
< 
* Connection #0 to host localhost left intact
{"success":false,"error":"Package 'invalid-package' not found"}
```

Contrary, the 404 from the official registry does not include any JSON content. `{}`

I also don't know why the ": repository" part is being appended to the npm client message, but it doesn't make sense either.

A similar problem happens for `npm info` commands as these essentially make the same type of package request. Other npm commands may be similar. 

Expected:
- All URL parsing and error message handling in NPM client should properly expect to deal with URL path parts that are not a package.
- make no assumption a registry starts at the root of a URL

**Comment by peterlynch** [comment]
semi-duplicate? https://github.com/npm/npm-registry-client/issues/80

**Comment by jameswomack** [comment]
This same issue appears if you simply enter a bad semantic version for a dependency when using a private registry in this manner. E.g. enter a dependency as `"buil": "npm run build"` (mistakenly putting a script in deps) will result in the above api-related error message.

**Comment by peterlynch** [comment]
Looks like a duplicate of https://github.com/npm/npm/issues/12374
