### ISSUE TITLE
npm i cheerio fails

### ISSUE THREAD

**Issue by matamx** [npm/npm#12514]
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/Cellar/node/5.10.1/bin/node" "/usr/local/bin/npm" "i" "cheerio"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.7

npm ERR! shasum check failed for /var/folders/nk/gd3lmzrx14j06jc36f5l43vr0000gn/T/npm-2118-2df0617b/registry.npmjs.org/htmlparser2/-/htmlparser2-3.8.3.tgz
npm ERR! Expected: 996c28b191516a8be86501a7d79757e5c70c1068
npm ERR! Actual:   46499f6126e504f5e193bb96cebfdd8b55261edf
npm ERR! From:     http://registry.npmjs.org/htmlparser2/-/htmlparser2-3.8.3.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by KenanY** [comment]
@matamx Have you tried `npm cache clean`?

**Comment by matamx** [comment]
it works thank you
