### ISSUE TITLE
Version compatibility.

### ISSUE THREAD

**Issue by atanl** [npm/npm#12519]
I really think it is necessary to add a wrapper like gradle wrapper, since so many package rely on the version of npm. My code work properly yesterday, but it update the node and npm, I go wrong everywhere. So, if there is a wrapper, I can specify the npm version in my project's configuration, and then very time I work with the same version of npm on one project.

Now, my teammate and I use

```
npm install
```

to install and update the dependent packages. But sometimes, the npm version on our computer not the same version.

I wish to use the npm like this,

```
npmw install
```

where npmw is a wrapper for npm of specified version. Just like Gradle, it read the specified version infomation from a directory name **gradle** in project.

**Comment by vjkoskela** [comment]
+1
