### ISSUE TITLE
gulp install error in nodejs 6.0

### ISSUE THREAD

**Issue by yreenchan** [npm/npm#12520]
- **v6.0.0**:
- **windows**:
- **Subsystem**:

After I upgrade node to 6.0, I got error when install gulp
![2b64c5ba-0d55-11e6-9a0b-d5131c7ea3b7](https://cloud.githubusercontent.com/assets/3251726/14906852/f119a7ec-0df2-11e6-8022-24fad2a8fec9.jpg)

[npm-debug.txt](https://github.com/npm/npm/files/241718/npm-debug.txt)

**Comment by atanl** [comment]
I encounter this problem too.

**Comment by bricss** [comment]
Try this:
```shell
rm -rf node_modules
npm install
```

**Comment by yreenchan** [comment]
@bricss that works! Thanks!
