### ISSUE TITLE
Cannot install cordova

### ISSUE THREAD

**Issue by jozeffraai** [npm/npm#12526]
Im getting an error while installing cordova through the command line using `sudo npm install cordova`

The error says:

```
npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/abbrev-ef9cc920' -> '/usr/local/lib/node_modules/cordova/node_modules/npm/node_modules/abbrev'
npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/abbrev-ef9cc920' -> '/usr/local/lib/node_modules/cordova/node_modules/npm/node_modules/abbrev'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
```

Here is the debug log
[npm-debug.txt](https://github.com/npm/npm/files/242628/npm-debug.txt)

```
23842 verbose stack Error: ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/abbrev-ef9cc920' -> '/usr/local/lib/node_modules/cordova/node_modules/npm/node_modules/abbrev'
23842 verbose stack     at destStatted (/usr/local/lib/node_modules/npm/lib/install/action/finalize.js:25:7)
23842 verbose stack     at FSReqWrap.oncomplete (fs.js:82:15)
23842 verbose stack
23842 verbose stack Error: ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/abbrev-ef9cc920' -> '/usr/local/lib/node_modules/cordova/node_modules/npm/node_modules/abbrev'
23842 verbose stack     at Error (native)
23843 verbose cwd /Users/spinimac/Desktop
23844 error Darwin 15.3.0
23845 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "cordova"
23846 error node v4.4.3
23847 error npm  v3.8.8
23848 error path /usr/local/lib/node_modules/.staging/abbrev-ef9cc920
23849 error code ENOENT
23850 error errno -2
23851 error syscall rename
23852 error enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/abbrev-ef9cc920' -> '/usr/local/lib/node_modules/cordova/node_modules/npm/node_modules/abbrev'
23853 error enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/abbrev-ef9cc920' -> '/usr/local/lib/node_modules/cordova/node_modules/npm/node_modules/abbrev'
23853 error enoent This is most likely not a problem with npm itself
23853 error enoent and is related to npm not being able to find a file.
23854 verbose exit [ -2, true ]
```

**Comment by ademiawansyah** [comment]
It happen to me in Windows 10 64-bit too. 


npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! path C:\Users\{MyUser}\AppData\Roaming\npm\node_modules\.staging\abbrev-6e011008
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\{MyUser}\AppData\Roaming\npm\node_modules\.staging\abbrev-6e011008' -> 'C:\Users\{MyUser}\AppData\Roaming\npm\node_modules\cordova\node_modules\npm\node_modules\abbrev'
npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\{MyUser}\AppData\Roaming\npm\node_modules\.staging\abbrev-6e011008' -> 'C:\Users\{MyUser}\AppData\Roaming\npm\node_modules\cordova\node_modules\npm\node_modules\abbrev'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

**Comment by coderroggie** [comment]
I'm on OSX 10.11.4 (15E65) and had installed node v 6.0.0 and ran into this problem.  I downgraded to the v4.4.3 LTS version and it resolved my issues with installing cordova.

**Comment by shivisingh94** [comment]
I get the following output when I try to install Cordova: 
npm install -g cordova
C:\Users\shivi_star\AppData\Roaming\npm\cordova -> C:\Users\shivi_star\AppData\Roaming\npm\node_modules\cordova\bin\cordova
C:\Users\shivi_star\AppData\Roaming\npm
`-- cordova@6.1.1

I have been looking at this for hours and still cannot figure out what is wrong! I have reinstalled Node and npm  ( running Node  4.4.4). Please do advise

**Comment by 0x4d4746h** [comment]
This is a big bug for node module, You need to reinstall Node LTS version for continue

**Comment by daviddahl** [comment]
Any progress here? I am seeing the exact same issue with breakpoint-sass package and node 6.x:

`verbose stack Error: ENOENT: no such file or directory, rename '/home/vagrant/foo/node_modules/.staging/breakpoint-sass-31879aa2' -> '/home/vagrant/foo/node_modules/@marketplace/sass-ui/node_modules/breakpoint-sass'`

**Comment by peillis** [comment]
Same here with node 4.3.0
