### ISSUE TITLE
".staging" folder inside of node_modules

### ISSUE THREAD

**Issue by benstaker** [npm/npm#12540]
There seems to be a **".staging"** folder inside of my applications **node_modules** folder.

![13149920_10208943803290456_469187674_n](https://cloud.githubusercontent.com/assets/2591500/14942556/fd4bf418-0fb7-11e6-8621-c3a1217dd3a9.png)

I've had no luck solving this issue... I've tried installing **Node.JS v5.x** and also tried **Node.JS v6.x**.
The OS I'm using is **CentOS v7.x** and the NPM version is **v3.8.6**.

This could be an issue with my package.json file:
**NOTE:** I have removed info from this, which can be seen with **"..."**.

```javascript
{
  "name": "...",
  "version": "...",
  "license": "MIT",
  "author": "...",
  "description": "...",
  "keywords": [ ... ],
  "main": "index.js",
  "scripts": { ... },
  "repository": { ... },
  "bugs": { ... },
  "engines": { ... },
  "dependencies": {
    "async": "2.0.0-rc.3",
    "body-parser": "1.15.0",
    "cloudinary": "1.2.5",
    "colors": "1.1.2",
    "compression": "1.5.2",
    "connect-flash": "0.1.1",
    "connect-gzip-static": "1.0.0",
    "connect-modrewrite": "0.8.2",
    "connect-mongostore": "0.1.4",
    "cookie-parser": "1.4.0",
    "express": "4.13.3",
    "express-session": "1.12.1",
    "flash": "1.1.0",
    "jit-grunt": "0.9.1",
    "jsdoc": "3.3.3",
    "jwt-simple": "0.3.1",
    "lodash": "4.11.1",
    "mailcomposer": "2.1.0",
    "mailgun": "0.5.0",
    "md5": "2.1.0",
    "moment": "2.10.6",
    "mongoose": "4.2.3",
    "oauth2orize": "1.1.1",
    "passport": "0.3.0",
    "passport-facebook": "2.0.0",
    "passport-github": "1.0.0",
    "passport-google-oauth": "0.2.0",
    "passport-http": "0.3.0",
    "passport-http-bearer": "1.0.1",
    "passport-local": "1.0.0",
    "passport-oauth2-client-password": "0.1.2",
    "passport-twitter": "1.0.3",
    "pug": "2.0.0-alpha6",
    "serve-favicon": "2.3.0",
    "serve-static": "1.10.0",
    "session.socket.io": "0.2.1",
    "socket.io": "1.3.7",
    "uuid": "2.0.1"
  },
  "devDependencies": {
    "grunt": "0.4.5",
    "grunt-angular-templates": "0.5.7",
    "grunt-bower-task": "0.4.0",
    "grunt-cli": "1.2.0",
    "grunt-connect-proxy": "0.2.0",
    "grunt-contrib-clean": "0.6.0",
    "grunt-contrib-compress": "0.14.0",
    "grunt-contrib-concat": "0.5.1",
    "grunt-contrib-connect": "0.11.2",
    "grunt-contrib-copy": "0.8.2",
    "grunt-contrib-cssmin": "0.14.0",
    "grunt-contrib-htmlmin": "0.6.0",
    "grunt-contrib-jshint": "0.11.3",
    "grunt-contrib-less": "1.0.1",
    "grunt-contrib-nodeunit": "0.4.1",
    "grunt-contrib-pug": "0.0.0",
    "grunt-contrib-uglify": "0.10.0",
    "grunt-contrib-watch": "0.6.1",
    "grunt-include-source": "0.7.0",
    "grunt-jsdoc": "1.0.0",
    "grunt-usemin": "3.0.0",
    "grunt-wiredep": "2.0.0"
  }
}
```

...but I cannot see anything wrong with it.

**Comment by benstaker** [comment]
I have discovered a workaround, maybe this'll help with debugging:

```
npmModulesFolder="./node_modules"

echo "Removing '$npmModulesFolder', NPM installing w/ sudo, then chowning '$npmModulesFolder'"

sudo rm -rf $npmModulesFolder
sudo npm install
sudo chown -R $USER:$USER $npmModulesFolder
sudo chmod -R 755 $npmModulesFolder
```

**Comment by benstaker** [comment]
I'm still getting issues with this.

Could someone from the npm team explain to me when the ".staging" folder is created and what could be preventing it from progressing further? Thanks!

**Comment by quinn** [comment]
I'm also having this problem. where does the `.staging` dir come from

**Comment by quinn** [comment]
@benstaker adding swap fixed this for me. (`npm install` was running out of memory)

**Comment by benstaker** [comment]
@quinn thank you for sharing your findings! I will give this a go and will report back.

**Comment by benstaker** [comment]
Adding a 2GB swapfile allowed me to install the node_modules!
Closing this issue.

**Comment by FuckingNoO** [comment]
useful，when comes to node_modules issues

**Comment by leandrocrs** [comment]
I'm experiencing the same issue, but my setup is:
Host => Windows 10 x64 Pro + Docker for Windows installed
Guest => node:boron container

How can I add a swap for a Docker Container? Do I really need this?

**Comment by quinn** [comment]
@leandrw either allocate more memory to the VM that runs docker or you could add the commands to create swap to your `Dockerfile`. Though I'm not sure if swap works the same way inside of a container. You may need to add the swap to the host VM (not windows, the linux VM)
