### ISSUE TITLE
npm dowsnt update version

### ISSUE THREAD

**Issue by kpmbro** [npm/npm#12547]
hi ,
ths machine run ubuntu 14.04 
i have installed npm using 
**apt-get install npm.**
after this i am trying to check the version:
**npm -v 
1.3.10**
i need to run npm version 2 and above so i am trying to run this command:
**npm install npm -g**
this is the output: 
**
npm http GET https://registry.npmjs.org/npm
npm http 304 https://registry.npmjs.org/npm
npm http GET https://registry.npmjs.org/npm/-/npm-3.8.8.tgz
npm http 200 https://registry.npmjs.org/npm/-/npm-3.8.8.tgz
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
npm@3.8.8 /usr/local/lib/node_modules/npm
**
after this i am trying to check the npm version 
**npm -v
1.3.10**

i even try to run the install npm -g 3 times and there was no diffrence. 
i found a forum chat the said to clean the cache of the npm so i used this command:
**npm cache clean -f**
after this i checked the version again:
**npm -v
1.3.10**

so how could i update the npm ?

**Comment by heijmans** [comment]
The npm that you installed with apt-get is probably located in /usr/bin/npm. The npm 3 is placed in /usr/local/bin/npm. So you now have 2 npm versions. If you run npm, the old one is used. You can probably uninstall the old npm using `apt-get remove npm`.
