### ISSUE TITLE
npm started uninstall before preuninstall script finished

### ISSUE THREAD

**Issue by bosco-li** [npm/npm#12545]
We have a program that saves configuration information in the user home directory.  We wanted to remove such directory when the program is uninstalled.  We created an option for our program so that it will detect the OS type and remove the config directory at the `preuninstall` phase.  

We added the below in `package.json`

```
  "scripts": {
    "preuninstall": "myscript --removeUserConfigDir",
  },
```

Now when we call `npm uninstall myscript`, we do expect the below to happen in order
1. `myscript --removeUserConfigDir` will remove the user directory
2. npm will uninstall myscript

However, during stage 1, npm already started removing modules like `rimraf` that is being used as a result, 1 is not able to location `rimraf` to remove the user directory.

Is this a bug or expected that 2 started before 1 is finished?

Thanks for helping!

**Comment by NotMyself** [comment]
Here is a repository with a repro of this bug: https://github.com/NotMyself/ghost-azurestorage

Note that `preuninstall` fails because rimraf is removed before the script is called.

**Comment by thomasklein** [comment]
Hi guys! Any update on this one?
