### ISSUE TITLE
Error while installing gulp 3.9.1

### ISSUE THREAD

**Issue by cbmadhu** [npm/npm#12543]
Hi
I am facing below error while installing gulp@3.9.1. Please let me know how to resolve this

Node version is : V4.4.2
npm Version is : 2.15.0

```
Madhus-MacBook-Pro:Gulp_Workspace root# npm install –g gulp@3.9.1
npm WARN package.json Gulp_Workspace@1.0.0 No description
npm WARN package.json Gulp_Workspace@1.0.0 No repository field.
npm WARN package.json Gulp_Workspace@1.0.0 No README data
npm ERR! addLocal Could not install /Users/MadhuSangee/Documents/workspace/Gulp_Workspace/–g
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "–g" "gulp@3.9.1"
npm ERR! node v4.4.2
npm ERR! npm  v2.15.0
npm ERR! The header content contains invalid characters
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

**Comment by KenanY** [comment]
@cbmadhu Use `-g` instead of `–g` (that is, use a regular hyphen instead of a hyphen-minus).

**Comment by AntonTrapp** [comment]
Nice one, just stumbled upon the same problem (different package). Copy/Paste problem. Real - did the trick. Would have spent hours to find this one out :D - TNX!

**Comment by KenanY** [comment]
@AntonTrapp No problem! Fortunately https://github.com/npm/npm/pull/12475 will add a warning for this kind of thing :)

**Comment by AntonTrapp** [comment]
great!

**Comment by KenanY** [comment]
@cbmadhu ping

**Comment by othiym23** [comment]
Closing as abandoned.
