### ISSUE TITLE
npm@3.3.4 fails to list extraneous packages

### ISSUE THREAD

**Issue by raquelsa** [npm/npm#12549]
I noticed this behavior change on version 3.3.4. Remove a package that is currently installed from package.json and it run npm ls. The removed package is not listed as "Extraneous" anymore. Am I missing anything here?

**Comment by jmm** [comment]
I encountered a similar issue (still, in npm@3.9.0). For me it happens with something that was a `devDependency` when installed. See https://github.com/npm/npm/issues/12646.
