### ISSUE TITLE
when I use command "npm search",I got an error

### ISSUE THREAD

**Issue by SevenLin** [npm/npm#12555]
**The log like this:**
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/5.3.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'search',
1 verbose cli   'grunt-cli' ]
2 info using npm@3.8.2
3 info using node@v5.3.0
4 verbose config Skipping project config: /Users/sevenlin/.npmrc. (matches userconfig)
5 silly mapToRegistry name -/all
6 silly mapToRegistry using default registry
7 silly mapToRegistry registry https://registry.npm.taobao.org/
8 silly mapToRegistry uri https://registry.npm.taobao.org/-/all
9 info updateIndex /Users/sevenlin/.npm/registry.npm.taobao.org/-/all/.cache.json
10 verbose correctMkdir /Users/sevenlin/.npm correctMkdir not in flight; initializing
11 warn Building the local index for the first time, please be patient
12 silly update-index fetching https://registry.npm.taobao.org/-/all
13 verbose request uri https://registry.npm.taobao.org/-/all
14 verbose request no auth needed
15 info attempt registry request try #1 at 5:21:40 PM
16 verbose request id d20254aa45391da0
17 http request GET https://registry.npm.taobao.org/-/all
18 http 200 https://registry.npm.taobao.org/-/all
19 verbose headers { date: 'Tue, 03 May 2016 09:21:45 GMT',
19 verbose headers   'content-type': 'application/json; charset=utf-8',
19 verbose headers   'content-length': '6146928',
19 verbose headers   connection: 'keep-alive',
19 verbose headers   etag: '"5dcb70-/mhGmyuUp0EJuE4Syq2BpQ"',
19 verbose headers   'x-readtime': '4085' }
20 verbose stack Error: true true: -/all
20 verbose stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
20 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:252:14)
20 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
20 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:199:22)
20 verbose stack     at emitTwo (events.js:87:13)
20 verbose stack     at Request.emit (events.js:172:7)
20 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1036:10)
20 verbose stack     at emitOne (events.js:82:20)
20 verbose stack     at Request.emit (events.js:169:7)
20 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:963:12)
21 verbose statusCode 200
22 verbose cwd /Users/sevenlin/project/hf-csa-manager
23 error Darwin 15.4.0
24 error argv "/usr/local/Cellar/node/5.3.0/bin/node" "/usr/local/bin/npm" "search" "grunt-cli"
25 error node v5.3.0
26 error npm  v3.8.2
27 error code E200
28 error true true: -/all
29 error If you need help, you may report this error at:
29 error     <https://github.com/npm/npm/issues>
30 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@SevenLin Does this also occur with the default registry?

**Comment by KenanY** [comment]
@SevenLin ping

**Comment by othiym23** [comment]
Closing as abandoned.
