### ISSUE TITLE
npm run build error

### ISSUE THREAD

**Issue by fecalemos** [npm/npm#12560]
I am having trouble running this package.json file

{
	"name": "NodejsStarterApp",
	"version": "0.0.1",
    "private": true,
	"scripts": {
		"start": "node app.js"
	},
	"dependencies": {
		"express": "4.13.x",
		"cfenv": "1.0.x"
	},
	"repository": {},
	"engines": {
		"node": "4.2.x"
	} 
}

I get this error in consol

npm ERR! Linux 4.4.0-21-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1

npm ERR! missing script: build
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/fecalemos/Applications/AppAcessibilityDeaf/npm-debug.log

here is the npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@2.15.1
3 info using node@v4.4.3
4 verbose stack Error: missing script: build
4 verbose stack     at run (/usr/lib/node_modules/npm/lib/run-script.js:142:19)
4 verbose stack     at /usr/lib/node_modules/npm/lib/run-script.js:58:5
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:345:5
4 verbose stack     at checkBinReferences_ (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:309:45)
4 verbose stack     at final (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:343:3)
4 verbose stack     at then (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:113:5)
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:232:12
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
5 verbose cwd /home/fecalemos/Applications/AppAcessibilityDeaf
6 error Linux 4.4.0-21-generic
7 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
8 error node v4.4.3
9 error npm  v2.15.1
10 error missing script: build
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@fecalemos Looks like you do not have a `"build"` script defined in your `package.json`, hence the error:

```
4 verbose stack Error: missing script: build
```

**Comment by KenanY** [comment]
@fecalemos ping

**Comment by othiym23** [comment]
Closing as abandoned.
