### ISSUE TITLE
not able to  connection github.com

### ISSUE THREAD

**Issue by nvianhd** [npm/npm#12568]
I had tried to go to https://www.github.com. It is working fine in Chrome, but when I tried command below. I got error

npm install && bower install
npm ERR! git fetch -a origin (git://github.com/chriseldredge/broccoli-msbuild.git) fatal: unable to connect to github.com:
npm ERR! git fetch -a origin (git://github.com/chriseldredge/broccoli-msbuild.git) github.com[0: 192.30.252.122]: errno=No error
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true fetch -a origin
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.122]: errno=No error
npm ERR!
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Temp\klondike\npm-debug.log

**Comment by KenanY** [comment]
@nvianhd Maybe you are behind a proxy or firewall which blocks the `git:` protocol? Maybe you have not configured `npm` to use your proxy (if you have one)?

**Comment by nvianhd** [comment]
nNo, there is no proxy or firewall. My home wireless, doesn't have any kind that blocking.
npm can download other package from Internet. I am not sure why only github get block

**Comment by nvianhd** [comment]
I found the problem, by default windows 10 is blocking ping command
