### ISSUE TITLE
if "UNMET PEER DEPENDENCIES" is a warning, it should be yellow and lowercase

### ISSUE THREAD

**Issue by bendavis78** [npm/npm#12567]
The "UNMET PEER DEPENDENCIES" output is red and all-caps, making it seem like an error, but the corresponding message below says it's just a warning. This is confusing.

![image](https://cloud.githubusercontent.com/assets/324392/15001119/8e2d9812-115a-11e6-882b-68bb72dcfffe.png)

**Comment by Rahulraj9736** [comment]
Installation configuration..!
