### ISSUE TITLE
UNABLE_TO_VERIFY_LEAF_SIGNATURE

### ISSUE THREAD

**Issue by jvarelafilos** [npm/npm#12565]
**Not sure what is broken here or how to fix it. Any help is greatly appreciated.**

**[jvarela@jvarela grafana]$ npm install**
npm ERR! Linux 3.16.2-201.fc20.x86_64
npm ERR! argv "/home/jvarela/node.js_6.0/node-v4.4.3-linux-x64/bin/node" "/home/jvarela/node.js_6.0/node-v4.4.3-linux-x64/bin/npm" "install"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code UNABLE_TO_VERIFY_LEAF_SIGNATURE

npm ERR! unable to verify the first certificate
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jvarela/go_1.5/work/src/github.com/grafana/grafana/npm-debug.log
**[jvarela@jvarela grafana]$ less /home/jvarela/go_1.5/work/src/github.com/grafana/grafana/npm-debug.log**
0 info it worked if it ends with ok
1 verbose cli [ '/home/jvarela/node.js_6.0/node-v4.4.3-linux-x64/bin/node',
1 verbose cli   '/home/jvarela/node.js_6.0/node-v4.4.3-linux-x64/bin/npm',
1 verbose cli   'install' ]
2 info using npm@2.15.1
3 info using node@v4.4.3
4 verbose readDependencies loading dependencies from /home/jvarela/go_1.5/work/src/github.com/grafana/grafana/package.json
5 verbose install where, deps [ '/home/jvarela/go_1.5/work/src/github.com/grafana/grafana',
5 verbose install   [ 'eventemitter3',
5 verbose install     'grunt-jscs',
5 verbose install     'grunt-sass-lint',
...
...
1255 http request GET https://registry.npmjs.org/grunt-usemin
1256 info attempt registry request try #3 at 3:56:38 PM
1257 http request GET https://registry.npmjs.org/reflect-metadata
1258 info attempt registry request try #3 at 3:56:38 PM
1259 http request GET https://registry.npmjs.org/mocha
1260 info attempt registry request try #3 at 3:56:38 PM
1261 http request GET https://registry.npmjs.org/grunt-filerev
1262 info attempt registry request try #3 at 3:56:38 PM
1263 http request GET https://registry.npmjs.org/grunt-sass
1264 info attempt registry request try #3 at 3:56:38 PM
1265 http request GET https://registry.npmjs.org/rxjs
1266 info attempt registry request try #3 at 3:56:38 PM
1267 http request GET https://registry.npmjs.org/grunt-cli
1268 info attempt registry request try #3 at 3:56:38 PM
1269 http request GET https://registry.npmjs.org/grunt-contrib-jshint
1270 info attempt registry request try #3 at 3:56:38 PM
1271 http request GET https://registry.npmjs.org/tether-drop
1272 info attempt registry request try #3 at 3:56:38 PM
1273 http request GET https://registry.npmjs.org/karma-coveralls
1274 info attempt registry request try #3 at 3:56:38 PM
1275 http request GET https://registry.npmjs.org/sass-lint
1276 verbose stack Error: unable to verify the first certificate
1276 verbose stack     at Error (native)
1276 verbose stack     at TLSSocket.<anonymous> (_tls_wrap.js:1017:38)
1276 verbose stack     at emitNone (events.js:67:13)
1276 verbose stack     at TLSSocket.emit (events.js:166:7)
1276 verbose stack     at TLSSocket._init.ssl.onclienthello.ssl.oncertcb.TLSSocket._finishInit (_tls_wrap.js:582:8)
1276 verbose stack     at TLSWrap.ssl.onclienthello.ssl.oncertcb.ssl.onnewsession.ssl.onhandshakedone (_tls_wrap.js:424:38)
1277 verbose cwd /home/jvarela/go_1.5/work/src/github.com/grafana/grafana
1278 error Linux 3.16.2-201.fc20.x86_64
1279 error argv "/home/jvarela/node.js_6.0/node-v4.4.3-linux-x64/bin/node" "/home/jvarela/node.js_6.0/node-v4.4.3-linux-x64/bin/npm" "install"
1280 error node v4.4.3
1281 error npm  v2.15.1
1282 error code UNABLE_TO_VERIFY_LEAF_SIGNATURE
1283 error unable to verify the first certificate
1284 error If you need help, you may report this error at:
1284 error     https://github.com/npm/npm/issues
1285 verbose exit [ 1, true ]

**Comment by ishitaIndraneel** [comment]
For me the solution was getting out of the corporate network and using a different wi-fi.It let me install jshint

**Comment by Bluscream** [comment]
I have the same issue
