### ISSUE TITLE
Bad interactions w/ Python virtualenv via PATH

### ISSUE THREAD

**Issue by mojodna** [npm/npm#12566]
https://github.com/npm/npm/commit/3eae40b7a681aa067dfe4fea8c9a76da5b508b48 introduced functionality equivalent to prefixing `PATH` with `$(npm prefix -g)/bin`. On Linux systems, this is often `/usr/bin` (which is likely already present).

Beyond setting `VIRTUAL_ENV`, `virtualenv` prefixes `PATH` to include a `python` wrapper that includes locally-installed modules. This ensures that a hashbang like `#!/usr/bin/env python` executes the version of Python that is able to find those modules.

When running a Node app that shells out into a `virtualenv` (i.e. a correctly set environment) under `npm`, the above behavior is negated due to the above commit, as `python` is executed from `/usr/bin` and it can't find locally-installed modules.

Proposed fix:

``` javascript
var execPathDir = path.dirname(process.execPath)

// only prepend PATH if the target isn't already present
if (pathArr.indexOf(execPathDir) < 0) {
  pathArr.push(execPathDir)
}
```

This won't fix it in all situations (i.e. when `PATH` doesn't contain the problematic target), but it will prevent intentional de-prioritization of system paths.

**Comment by mojodna** [comment]
2.x is also affected: https://github.com/npm/npm/commit/02813c55782a9def23f7f1e614edc38c6c88aed3

**Comment by busches** [comment]
Is this still an issue in the latest `npm` 2 and 3?
