### ISSUE TITLE
Error while installing Vue with npm

### ISSUE THREAD

**Issue by mttk** [npm/npm#12561]
Hey, 

I'm trying to install vue by using npm and I'm getting the following error: "No compatible version found: vue@undefined1.0.21" 

I'm running "sudo npm install vue" on Ubuntu 14.04, and the log is as attached:
[npm-debug.txt](https://github.com/npm/npm/files/247254/npm-debug.txt)

I found the instructions for installation on the official Vue site (http://vuejs.org/guide/installation.html#NPM), so I'm not sure who to point fingers at.

Thanks!

**Comment by heijmans** [comment]
`undefined1.0.21` is not a correct version. Perhaps this is picked up from your `package.json`. Can you include your `package.json` or check if there is a dependency on vue in your `package.json`?

**Comment by mttk** [comment]
@heijmans sorry, I've since switched PC's - not able to replicate the error anymore.
