### ISSUE TITLE
Suggestion: efficient node_modules 

### ISSUE THREAD

**Issue by dharmax** [npm/npm#12572]
1. Currently, any module carries the weight of all its dependencies, recursively
2. On any serious project, that means a huge amount of files, due to innumerable redundancy.
3. i suggest adding a logic that will reuse an already existing packages, whenever the required semver matches
4. i know it complicates npm, but have 10s of 1000s files for any little project seems to be absurd, and it may become even worse
5. Aside for the clear benefits of footprint and update performance, there's a rather interesting and indirect benefit, which can be worthwhile in and for itself: is that currently, when a dependent package A that depends on package B, will keep package B's old version even if package B is updated (and semver compatible). In the new scheme, package B will be updated and it may make package A "better" (bug fixes? performance improvement) even if it doesn't have a newer version.

**Comment by somebody1234** [comment]
That wouldn't work the way you describe it - it will probably not make package A better - it's just as likely to break compatibility. But if it allows multiple package versions, then this may be a possibility.

**Comment by KenanY** [comment]
@dharmax Does `npm@3` solve most of this already? https://docs.npmjs.com/how-npm-works/npm3

**Comment by dharmax** [comment]
@somebody1234 - of course it must allow multiple package versions... 
@KenanY - i didn't know there's npm3 already... and it looks like it is going in the direction i proposed, as much as i can tell in glance at your link...

**Comment by KenanY** [comment]
@dharmax Hmm, what part specifically makes you say that?

**Comment by dharmax** [comment]
Their illustrations show that there could be duplicate packages of the same
versions.

**Comment by somebody1234** [comment]
Yeah, other versions of a package are still nested in npm3

**Comment by KenanY** [comment]
Like this example?

![image](https://cloud.githubusercontent.com/assets/733364/15098627/31835dfa-150f-11e6-96cc-70cda4d50688.png)

How would we have two different versions of the same module be present at the same directory level? I do not think it is possible to have two directories of the same name within a shared parent directory.

**Comment by dharmax** [comment]
@KenanY yes, like in that example. And yes - it is not trivial, but i'd never be too hasty to say "not possible" about anything... ;)

**Comment by KenanY** [comment]
@dharmax In that case, I cannot speak for the core `npm` team, but I would say that suggestions are welcome and pull requests doubly welcomed :) so long as the `require()` algorithm is not touched at all.
