### ISSUE TITLE
npm install: failed to fetch from registry: codebox

### ISSUE THREAD

**Issue by oquidave** [npm/npm#12577]
Hello, am attempting to install codebox on Freebsd 8. But I get the following errors. What could be the problem? Thanks

# npm install -g codebox
npm http GET https://registry.npmjs.org/codebox
npm ERR! Error: failed to fetch from registry: codebox
npm ERR!     at /usr/local/lib/node_modules/npm/lib/utils/npm-registry-client/get.js:139:12
npm ERR!     at cb (/usr/local/lib/node_modules/npm/lib/utils/npm-registry-client/request.js:32:9)
npm ERR!     at Request._callback (/usr/local/lib/node_modules/npm/lib/utils/npm-registry-client/request.js:137:18)
npm ERR!     at Request.callback (/usr/local/lib/node_modules/npm/node_modules/request/main.js:104:22)
npm ERR!     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/main.js:181:58)
npm ERR!     at Request.emit (events.js:88:20)
npm ERR!     at ClientRequest.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/main.js:329:14)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at HTTPParser.onIncoming (http.js:1225:11)
npm ERR!     at HTTPParser.onHeadersComplete (http.js:102:31)
npm ERR! Report this *entire* log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
npm ERR! 
npm ERR! System FreeBSD 8.2-RELEASE
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g" "codebox"
npm ERR! cwd /usr2/mail
npm ERR! node -v v0.6.6
npm ERR! npm -v 1.1.0-beta-4
npm ERR! message failed to fetch from registry: codebox
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /usr2/mail/npm-debug.log
npm not ok

**Comment by KenanY** [comment]
@oquidave Node.js v0.6 and `npm@1.1` are years old and no longer supported. Try updating both ([Node.js](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-node), [`npm`](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm)).

**Comment by KenanY** [comment]
@oquidave ping

**Comment by oquidave** [comment]
Upgrading worked, thanks

**Comment by othiym23** [comment]
Closing as resolved.
