### ISSUE TITLE
NODE_ENV=production causes `npm ls -g` to fail

### ISSUE THREAD

**Issue by wadey** [npm/npm#12579]
I am using Node 4.4.3 and npm 3.8.8. If I set NODE_ENV=production, `npm ls -g` fails. There is no information displayed about why it failed and there are no further logs if I enable loglevel silly.

```
$ NODE_ENV=production npm ls -g gulp
/usr/local/node/lib
└── (empty)

npm ERR! code 1
```

```
$ NODE_ENV=notproduction npm ls -g gulp
/usr/local/node/lib
└── gulp@3.9.1
```

The only thing I see mentioned in the docs is:

> prod / production
> 
> Type: Boolean
> Default: false
> Display only the dependency tree for packages in dependencies.

https://docs.npmjs.com/cli/ls#prod--production

**Comment by achinth** [comment]
I can confirm this issue still exists with:

npm 5.6.0
node 8.9.3
centos 7.4.1708

Please re-open and fix
