### ISSUE TITLE
unable to setup EZWEB2.0 in my pc

### ISSUE THREAD

**Issue by UMAPATHYGURAJALA** [npm/npm#12576]
0 info it worked if it ends with ok
1 verbose cli [ 'D:\ugurajal092310\nodist\v\nodev5.5.0\node.exe',
1 verbose cli   'D:\ugurajal092310\nodist\bin\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'yo' ]
2 info using npm@3.8.5
3 info using node@v5.5.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData yo
8 silly fetchNamedPackageData yo
9 silly mapToRegistry name yo
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://itbox-nexus-ext.fr.world.socgen/nexus-ext/content/repositories/ext-all-npm-group/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'yo',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   name: 'yo',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://itbox-nexus-ext.fr.world.socgen/nexus-ext/content/repositories/ext-all-npm-group/yo
14 verbose request uri https://itbox-nexus-ext.fr.world.socgen/nexus-ext/content/repositories/ext-all-npm-group/yo
15 verbose request no auth needed
16 info attempt registry request try #1 at 5:46:45 PM
17 verbose request id 40178bd8876164d7
18 http request GET https://itbox-nexus-ext.fr.world.socgen/nexus-ext/content/repositories/ext-all-npm-group/yo
19 info retry will retry, error on last attempt: Error: unable to verify the first certificate
20 info attempt registry request try #2 at 5:46:56 PM
21 http request GET https://itbox-nexus-ext.fr.world.socgen/nexus-ext/content/repositories/ext-all-npm-group/yo
22 info retry will retry, error on last attempt: Error: unable to verify the first certificate
23 info attempt registry request try #3 at 5:47:56 PM
24 http request GET https://itbox-nexus-ext.fr.world.socgen/nexus-ext/content/repositories/ext-all-npm-group/yo
25 silly fetchPackageMetaData Error: unable to verify the first certificate
25 silly fetchPackageMetaData     at Error (native)
25 silly fetchPackageMetaData     at TLSSocket.<anonymous> (_tls_wrap.js:1057:38)
25 silly fetchPackageMetaData     at emitNone (events.js:80:13)
25 silly fetchPackageMetaData     at TLSSocket.emit (events.js:179:7)
25 silly fetchPackageMetaData     at TLSSocket._init.ssl.onclienthello.ssl.oncertcb.TLSSocket._finishInit (_tls_wrap.js:596:8)
25 silly fetchPackageMetaData     at TLSWrap.ssl.onclienthello.ssl.oncertcb.ssl.onnewsession.ssl.onhandshakedone (_tls_wrap.js:428:38)
25 silly fetchPackageMetaData  error for yo { [Error: unable to verify the first certificate] code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE' }
26 silly rollbackFailedOptional Starting
27 silly rollbackFailedOptional Finishing
28 silly runTopLevelLifecycles Starting
29 silly runTopLevelLifecycles Finishing
30 silly install printInstalled
31 verbose stack Error: unable to verify the first certificate
31 verbose stack     at Error (native)
31 verbose stack     at TLSSocket.<anonymous> (_tls_wrap.js:1057:38)
31 verbose stack     at emitNone (events.js:80:13)
31 verbose stack     at TLSSocket.emit (events.js:179:7)
31 verbose stack     at TLSSocket._init.ssl.onclienthello.ssl.oncertcb.TLSSocket._finishInit (_tls_wrap.js:596:8)
31 verbose stack     at TLSWrap.ssl.onclienthello.ssl.oncertcb.ssl.onnewsession.ssl.onhandshakedone (_tls_wrap.js:428:38)
32 verbose cwd D:\ugurajal092310\nodist
33 error Windows_NT 6.1.7601
34 error argv "D:\ugurajal092310\nodist\v\nodev5.5.0\node.exe" "D:\ugurajal092310\nodist\bin\node_modules\npm\bin\npm-cli.js" "install" "-g" "yo"
35 error node v5.5.0
36 error npm  v3.8.5
37 error code UNABLE_TO_VERIFY_LEAF_SIGNATURE
38 error unable to verify the first certificate
39 error If you need help, you may report this error at:
39 error     https://github.com/npm/npm/issues
40 verbose exit [ 1, true ]

**Comment by linsolas** [comment]
Hello,

Could you please close this issue, EzWeb is a proprietary solution and this question **does not** belong to the npm repository.

Thanks.

**Comment by legodude17** [comment]
Please go through the [troubleshooting guide](https://github.com/npm/npm/wiki/Troubleshooting).

**Comment by linsolas** [comment]
Hello All,

Sorry this issue should be closed by an admin or the user itself since EzWeb is a specific tool for Société Générale company. We have a dedicated support internally and the user should have used it instead of posting an issue here. Sorry for that. 

And for the record, the issue seems to be related to his npm configuration and a bad cafile property ;)

Regards.

**Comment by legodude17** [comment]
@KenanY Ok, can you close this?

**Comment by linsolas** [comment]
Thanks all
