### ISSUE TITLE
Cannot find module './git-host-info.js'

### ISSUE THREAD

**Issue by samier** [npm/npm#12598]
getting error on bower update

**Comment by KenanY** [comment]
@samier Is this error coming from `npm`? Is there a `npm-debug.log` file you can upload to [gist.github.com](https://gist.github.com/)? If not, then this is probably not an issue with `npm` :)

**Comment by KenanY** [comment]
@samier Hi, just following up one week later: are you still seeing this error? If so, could you provide the generated `npm-debug.log`? If no such file is generated, then this is probably not an issue with `npm`, but you can still provide some terminal output instead if you'd like.

**Comment by KenanY** [comment]
Closing as abandoned.
