### ISSUE TITLE
linux npm login prompt Incorrect username or password

### ISSUE THREAD

**Issue by Luncher** [npm/npm#12597]
linux npm login prompt Incorrect username or password but But I can log in on browser.

---

prompt: 

[luncher@localhost LocalHolaStudio]$ npm login
Username: lebron
Password: 
Email: (this IS public) c.lin@holaverse.com
npm WARN adduser Incorrect username or password
npm WARN adduser You can reset your account by visiting:
npm WARN adduser 
npm WARN adduser     https://npmjs.org/forgot
npm WARN adduser 
npm ERR! Linux 4.1.13-100.fc21.x86_64
npm ERR! argv "/home/luncher/.nvm/versions/node/v5.8.0/bin/node" "/home/luncher/.nvm/versions/node/v5.8.0/bin/npm" "login"
npm ERR! node v5.8.0
npm ERR! npm  v3.8.7
npm ERR! code E401

npm ERR! unauthorized Login first: -/user/org.couchdb.user:lebron/-rev/undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /data/LocalHolaStudio/npm-debug.log

**Comment by Luncher** [comment]
Change Password cached it?

**Comment by busches** [comment]
@Luncher are you still seeing this problem or did changing your password fix it?

**Comment by Luncher** [comment]
I will try again later .... please wait..
