### ISSUE TITLE
env variables in npm scripts are not available in subsequent commands

### ISSUE THREAD

**Issue by leonid-bauxy** [npm/npm#12607]
If we run this command in the terminal

``` sh
MY_VAR=true node ./script1.js && node ./script2.js
```

then `process.env.MY_VAR` will equal to `"true"` in both `./script1.js` and `./script2.js`

If we put this same line in `npm start` script:

``` json
{
  "start": "MY_VAR=true node ./script1.js && node ./script2.js"
}
```

then `process.env.MY_VAR` will equal to `"true"` in `./script1.js`, but will be equal to `undefined` in `./script2.js`.

So to go around this i have to write:

``` json
{
  "start": "MY_VAR=true node ./script1.js && MY_VAR=true node ./script2.js"
}
```

which makes me duplicate it and adds unnecessary noise.

`npm` version: `3.8.8`
`OS`: `OSX 10.11.4`

Please, let me know if i can provide more info.

**Comment by codeHatcher** [comment]
Wow, I'm having this same problem in OSX with npm v4. Is this a known issue that won't be fixed? How did you get around this issue @leonid-bauxy?
