### ISSUE TITLE
Add `--preid` to `version` command

### ISSUE THREAD

**Issue by ssova-4xxi** [npm/npm#12609]
Add `--preid` parameter from https://github.com/npm/node-semver#prerelease-identifiers

or second optional parameter for `npm version`:

```
npm version [<newversion> | major | minor | patch | premajor | preminor | prepatch | prerelease | from-git] [alpha | beta | rc | dev]
```

command:

``` bash
npm version prepatch rc
```

should increment `1.0.1` to `1.0.2-rc.0`
similar by

``` bash
semver 1.0.1 -i prepatch --preid rc
```

**Comment by zallek** [comment]
👍

**Comment by Bamieh** [comment]
please this is very important, and its stated in the semver documentation.

**Comment by Bamieh** [comment]
i submitted a pull request adding this feature for "prerelease" version bumps. https://github.com/npm/npm/pull/13794

**Comment by spudly** [comment]
There's already a pull request: https://github.com/npm/npm/pull/12936

**Comment by zkat** [comment]
Closing this, in light of https://github.com/npm/npm/pull/12936#issuecomment-248153743

**Comment by bertho-zero** [comment]
This not works with npm 5.5.1

**Comment by AndyOGo** [comment]
@zkat 
Is this still broken?
If so please reopen. Prerelease identifiers are an intrinsic feature of `node-semver` -> https://github.com/npm/node-semver#prerelease-identifiers
