### ISSUE TITLE
 Refusing to install express-restify-mongoose as a dependency of itself

### ISSUE THREAD

**Issue by prachi9418** [npm/npm#12601]
#  **npm install express-restify-mongoose --save **
On installing above command in my project it showing me above error:

npm ERR! Linux 3.16.0-30-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "express-restify-mongoose" "--save"
npm ERR! node v5.1.0
npm ERR! npm  v3.3.12
npm ERR! code ENOSELF

npm ERR! Refusing to install express-restify-mongoose as a dependency of itself
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/bugatti/workspace/express-restify-mongoose/npm-debug.log
bugatti@BugattiVeyron:~/workspace/express-restify-mongoose$ npm install express-restify-mongoose --save
npm ERR! Linux 3.16.0-30-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "express-restify-mongoose" "--save"
npm ERR! node v5.1.0
npm ERR! npm  v3.3.12
npm ERR! code ENOSELF

npm ERR! Refusing to install express-restify-mongoose as a dependency of itself
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/bugatti/workspace/express-restify-mongoose/npm-debug.log
bugatti@BugattiVeyron:~/workspace/express-restify-mongoose$ cd..
cd..: command not found
bugatti@BugattiVeyron:~/workspace/express-restify-mongoose$ cd ..
bugatti@BugattiVeyron:~/workspace$ cd express-restify/
bugatti@BugattiVeyron:~/workspace/express-restify$ npm install express-restify-mongoose --save
npm ERR! Linux 3.16.0-30-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "express-restify-mongoose" "--save"
npm ERR! node v5.1.0
npm ERR! npm  v3.3.12
npm ERR! code ENOSELF

npm ERR! Refusing to install express-restify-mongoose as a dependency of itself
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/bugatti/workspace/express-restify/npm-debug.log
bugatti@BugattiVeyron:~/workspace/express-restify$ cd express-restify/bash: cd: express-restify/: No such file or directory
bugatti@BugattiVeyron:~/workspace/express-restify$ sudo npm install express-restify-mongoose --save
npm ERR! Linux 3.16.0-30-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "express-restify-mongoose" "--save"
npm ERR! node v5.1.0
npm ERR! npm  v3.3.12
npm ERR! code ENOSELF

npm ERR! Refusing to install express-restify-mongoose as a dependency of itself
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/bugatti/workspace/express-restify/npm-debug.log

**Comment by KenanY** [comment]
@prachi9418 Rename this directory `~/workspace/express-restify-mongoose` to something which does not share a name with one of your dependencies. Also ensure that the `"name"` field in your `package.json` is not set to `"~/workspace/express-restify-mongoose"` either.

**Comment by prachi9418** [comment]
Thanks Kenan Y .It was having the name of package.json as "express-restify-mongoose" hence by renaming it i am able to install this package.Thanks for your great solutions
