### ISSUE TITLE
npm cannot install any package

### ISSUE THREAD

**Issue by SLSJL** [npm/npm#12600]
$ npm install epxress
npm WARN onload-script failed to require onload script npm-autoinit/autoinit
npm WARN onload-script Error: Cannot find module 'npm-autoinit/autoinit'
npm WARN onload-script     at Function.Module._resolveFilename (module.js:325:15)
npm WARN onload-script     at Function.Module._load (module.js:276:25)
npm WARN onload-script     at Module.require (module.js:353:17)
npm WARN onload-script     at require (internal/module.js:12:17)
npm WARN onload-script     at cb (D:\Program Files\nodejs\node_modules\npm\lib\npm.js:289:9)
npm WARN onload-script     at D:\Program Files\nodejs\node_modules\npm\lib\npm.js:382:14
npm WARN onload-script     at D:\Program Files\nodejs\node_modules\npm\lib\config\core.js:82:7
npm WARN onload-script     at Array.forEach (native)
npm WARN onload-script     at D:\Program Files\nodejs\node_modules\npm\lib\config\core.js:81:13
npm WARN onload-script     at f (D:\Program Files\nodejs\node_modules\npm\node_modules\once\once.js:17:25)
npm WARN onload-script  { [Error: Cannot find module 'npm-autoinit/autoinit'] code: 'MODULE_NOT_FOUND' }
npm WARN onload-script failed to require onload script npm-autoinit/autoinit
npm WARN onload-script Error: Cannot find module 'npm-autoinit/autoinit'
npm WARN onload-script     at Function.Module._resolveFilename (module.js:325:15)
npm WARN onload-script     at Function.Module._load (module.js:276:25)
npm WARN onload-script     at Module.require (module.js:353:17)
npm WARN onload-script     at require (internal/module.js:12:17)
npm WARN onload-script     at cb (D:\Program Files\nodejs\node_modules\npm\lib\npm.js:289:9)
npm WARN onload-script     at D:\Program Files\nodejs\node_modules\npm\lib\npm.js:382:14
npm WARN onload-script     at D:\Program Files\nodejs\node_modules\npm\lib\config\core.js:82:7
npm WARN onload-script     at Array.forEach (native)
npm WARN onload-script     at D:\Program Files\nodejs\node_modules\npm\lib\config\core.js:81:13
npm WARN onload-script     at f (D:\Program Files\nodejs\node_modules\npm\node_modules\once\once.js:17:25)
npm WARN onload-script  { [Error: Cannot find module 'npm-autoinit/autoinit'] code: 'MODULE_NOT_FOUND' }
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "D:\Program Files\nodejs\node.exe" "D:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "epxress"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code E404
npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/epxress
npm ERR! 404
npm ERR! 404 'epxress' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     F:\sjl\imooc\npm-debug.log

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/epxress
npm ERR! 404
npm ERR! 404 'epxress' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     F:\sjl\imooc\npm-debug.log

---

Abouve all are the failed massages, I have tried to uninstall node and git,  clean up my pc, then install them again, doesnt work. I have no idea where the problem is. 

Is there anybody got the same issue? Give some advice please.

**Comment by kimroen** [comment]
Hi!

Yes, it looks like you might have spelled the name of the module your are trying to install incorrectly.

There's no module named `epxress`, but there is one named `express`, which is probably what you were looking for.

Try again:

```
npm install express
```

**Comment by SLSJL** [comment]
Thank you for your help.

I have tried the way you told me. But the result shows that the reason might not be the spell of 'express'. Cause I tried to install other modules, Here also comes the same error.   


> npm WARN onload-script failed to require onload script npm-autoinit/autoinit
> npm WARN onload-script Error: Cannot find module 'npm-autoinit/autoinit'
> npm WARN onload-script     at Function.Module._resolveFilename (module.js:325:15)
> npm WARN onload-script     at Function.Module._load (module.js:276:25)
> npm WARN onload-script     at Module.require (module.js:353:17)
> npm WARN onload-script     at require (internal/module.js:12:17)
> npm WARN onload-script     at cb (D:\Program Files\nodejs\node_modules\npm\lib\npm.js:289:9)
> npm WARN onload-script     at D:\Program Files\nodejs\node_modules\npm\lib\npm.js:382:14
> npm WARN onload-script     at D:\Program Files\nodejs\node_modules\npm\lib\config\core.js:82:7
> npm WARN onload-script     at Array.forEach (native)
> npm WARN onload-script     at D:\Program Files\nodejs\node_modules\npm\lib\config\core.js:81:13
> npm WARN onload-script     at f (D:\Program Files\nodejs\node_modules\npm\node_modules\once\once.js:17:25)
> npm WARN onload-script  { [Error: Cannot find module 'npm-autoinit/autoinit'] code: 'MODULE_NOT_FOUND' }
> npm WARN onload-script failed to require onload script npm-autoinit/autoinit
> npm WARN onload-script Error: Cannot find module 'npm-autoinit/autoinit'
> npm WARN onload-script     at Function.Module._resolveFilename (module.js:325:15)
> npm WARN onload-script     at Function.Module._load (module.js:276:25)
> npm WARN onload-script     at Module.require (module.js:353:17)
> npm WARN onload-script     at require (internal/module.js:12:17)
> npm WARN onload-script     at cb (D:\Program Files\nodejs\node_modules\npm\lib\npm.js:289:9)
> npm WARN onload-script     at D:\Program Files\nodejs\node_modules\npm\lib\npm.js:382:14
> npm WARN onload-script     at D:\Program Files\nodejs\node_modules\npm\lib\config\core.js:82:7
> npm WARN onload-script     at Array.forEach (native)
> npm WARN onload-script     at D:\Program Files\nodejs\node_modules\npm\lib\config\core.js:81:13
> npm WARN onload-script     at f (D:\Program Files\nodejs\node_modules\npm\node_modules\once\once.js:17:25)
> npm WARN onload-script  { [Error: Cannot find module 'npm-autoinit/autoinit'] code: 'MODULE_NOT_FOUND' }
> npm WARN package.json imooc@1.0.0 No repository field.

I don't know how to resolve this problem. Do have any idea about the solution?

**Comment by queckezz** [comment]
No idea why but this worked for me, see https://github.com/npm/npm/issues/11487:

```
npm config delete onload-script npm-autoinit/autoinit
```

**Comment by SLSJL** [comment]
@queckezz Thank you. It works for me too.

**Comment by SLSJL** [comment]
@kimroen Thank you for your advice. I solved this problem using queckezz's method .

**Comment by mdaliyan** [comment]
No, It's not a Windows only problem. I had it on Fedora.

**Comment by angelnmara** [comment]
gracias!!! esto trabajo en windows 10

**Comment by khanshab003** [comment]
@queckezz it worked for me too.
Thank you!!

**Comment by legodude17** [comment]
Anyone still have this issue?

**Comment by mdaliyan** [comment]
[This still works](https://github.com/npm/npm/issues/12600#issuecomment-217795940)

**Comment by legodude17** [comment]
If no one has this issue then it it can be closed. @KenanY

**Comment by PradepB** [comment]
thanks @queckezz

**Comment by PradepB** [comment]
angular.js:14328Error: [$controller:ctrlreg] http://errors.angularjs.org/1.6.1/$controller/ctrlreg?p0=AppCtrl
    at angular.js:38
    at angular.js:10668
    at ca (angular.js:9757)
    at n (angular.js:9527)
    at g (angular.js:8881)
    at g (angular.js:8884)
    at g (angular.js:8884)
    at angular.js:8746
    at angular.js:1843
    at m.$eval (angular.js:17972)
(anonymous) @ angular.js:14328
(anonymous) @ angular.js:10837
$apply @ angular.js:18077
(anonymous) @ angular.js:1841
invoke @ angular.js:4842
c @ angular.js:1839
Mc @ angular.js:1859
pe @ angular.js:1744
(anonymous) @ angular.js:32977
b @ angular.js:3314



how to solve this prb

**Comment by Charlotteis** [comment]
@PradepB this is an issue with Angular, not npm. So I suggest you go make an issue in the angular project :)
