### ISSUE TITLE
npm run installWPHC throw error

### ISSUE THREAD

**Issue by sanjeevbudhamagar** [npm/npm#12617]
> wordpress-hybrid-client@2.0.0-beta08 installWPHC /home/sanjeevbudha/wordpress-hybrid-client
> cd scripts && node ./install.js

module.js:328
    throw err;
    ^

Error: Cannot find module 'fs-extra'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/sanjeevbudha/wordpress-hybrid-client/scripts/install.js:3:10)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)

npm ERR! Linux 4.4.0-21-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "installWPHC"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! wordpress-hybrid-client@2.0.0-beta08 installWPHC: `cd scripts && node ./install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wordpress-hybrid-client@2.0.0-beta08 installWPHC script 'cd scripts && node ./install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the wordpress-hybrid-client package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd scripts && node ./install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs wordpress-hybrid-client
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls wordpress-hybrid-client
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/sanjeevbudha/wordpress-hybrid-client/npm-debug.log

**Comment by KenanY** [comment]
@sanjeevbudhamagar Seems like `/home/sanjeevbudha/wordpress-hybrid-client/scripts/install.js` wants `fs-extra` installed but it can't find it. Do you have it installed locally (`npm ls fs-extra`)?

**Comment by sanjeevbudhamagar** [comment]
Thanks Kenan.
