### ISSUE TITLE
npm init fails with MODULE_NOT_FOUND for spdx

### ISSUE THREAD

**Issue by hpinsley** [npm/npm#12618]
Interestingly, it does not prompt for any inputs and then says, "Is this OK?".  If I respond, Yes, it creates a four-line package.json file with virtually nothing in it.  Here is the npm-debug.log

> hpins-mba-osx:course howard.pinsley$ cat npm-debug.log 
> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'init' ]
> 2 info using npm@2.15.1
> 3 info using node@v4.4.4
> 4 silly package data undefined
> 5 info init written successfully
> 6 verbose stack Error: Cannot find module 'spdx'
> 6 verbose stack     at Function.Module._resolveFilename (module.js:325:15)
> 6 verbose stack     at Function.Module._load (module.js:276:25)
> 6 verbose stack     at Module.require (module.js:353:17)
> 6 verbose stack     at require (internal/module.js:12:17)
> 6 verbose stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/init-package-json/node_modules/validate-npm-package-license/index.js:1:74)
> 6 verbose stack     at Module._compile (module.js:409:26)
> 6 verbose stack     at Object.Module._extensions..js (module.js:416:10)
> 6 verbose stack     at Module.load (module.js:343:32)
> 6 verbose stack     at Function.Module._load (module.js:300:12)
> 6 verbose stack     at Module.require (module.js:353:17)
> 7 verbose cwd /Users/howard.pinsley/dev/react/course
> 8 error Darwin 13.4.0
> 9 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "init"
> 10 error node v4.4.4
> 11 error npm  v2.15.1
> 12 error code MODULE_NOT_FOUND
> 13 error Cannot find module 'spdx'
> 14 error If you need help, you may report this error at:
> 14 error     https://github.com/npm/npm/issues
> 15 verbose exit [ 1, true ]
> hpins-mba-osx:course howard.pinsley$

**Comment by hpinsley** [comment]
I think I see part of the problem.  Even though I just upgraded node and npm -- the latter to 3.x, when I run npm --version from the terminal (Mac OS X), it is reporting version 2.15.1. npm is a symbolic link in /usr/local/bin/npm which points to ===> ../lib/node_modules/npm/bin/npm-cli.js.  And this is indeed 2.15.1.  So I think I need to properly uninstall 2.15.1 before I upgrade to 3.x?

**Comment by Tonyhark** [comment]
@hpinsley  After reseached for several hours, i have resolved the same promblem I met yesterday 

step one:just uninstall the node and npm via http://stackoverflow.com/questions/9044788/how-do-i-uninstall-nodejs-installed-from-pkg-mac-os-x
step two: reinstall via node-v4.4.5.pkg
