### ISSUE TITLE
wiki doc windows section uses bash style env vars?

### ISSUE THREAD

**Issue by tmuka** [npm/npm#12611]
on
https://github.com/npm/npm/wiki/Troubleshooting#a-brief-note-on-the-built-in-windows-configuration

i ran into an issue following the doc as written which set my prefix to c:\npm because the envar string wasn't right.

this fix worked for me.

```
-npm config set prefix "${APPDATA}/npm" -g
+npm config set prefix "%APPDATA%/npm" -g^M
```

```
-npm config set prefix "${LOCALAPPDATA}/npm" -g
+npm config set prefix "%LOCALAPPDATA%/npm" -g^M
```

this shows following the steps before and after my change...

```
PS C:\Program Files\nodejs\node_modules> npm --version
3.8.9
PS C:\Program Files\nodejs\node_modules> npm config get prefix -g
C:\Program Files\nodejs
PS C:\Program Files\nodejs\node_modules> npm config set prefix "${APPDATA}/npm" -g
PS C:\Program Files\nodejs\node_modules> npm config get prefix -g
C:\npm
PS C:\Program Files\nodejs\node_modules> npm config set prefix "%APPDATA%/npm" -g
PS C:\Program Files\nodejs\node_modules> npm config get prefix -g
C:\Users\me.DOMAIN\AppData\Roaming\npm
```

hope this helps somebody else on windows!

**Comment by lbearl** [comment]
@tmuka interestingly that behavior only happens when you are in PowerShell, running through regular cmd.exe works perfectly.
