### ISSUE TITLE
readme files not included in `npm pack`

### ISSUE THREAD

**Issue by jdalton** [npm/npm#12614]
I've tried `npm@^2.0.0` and `npm@^3.0.0` and on OSX `npm pack` is not including the `README.md` for projects like [lodash/lodash-webpack-plugin](https://github.com/lodash/lodash-webpack-plugin). I'm not sure when this started happening but can confirm others aren't seeing it so I figured I'd post.

**Comment by KenanY** [comment]
@jdalton Node.js version?

**Comment by jdalton** [comment]
Node v6.0.0 via `nvm`. I'm wondering if it's an issue with `nvm` + `npm`.

**Comment by othiym23** [comment]
Closing as duplicate of #5082. Please check that issue for what's up and what action we're taking to remedy it. Thanks for your time!
