### ISSUE TITLE
 Failed to connect to githubs.com port 443: Connection refused, but no proxy server for my LAN

### ISSUE THREAD

**Issue by Changomazo** [npm/npm#12625]
I know this issue has been there for ages, but all i see is how to configure gitconfig to unset proxy servers, and how to set new ones, the issue here is simple: I am not behind a proxy, I have checked my internet connection and no proxy server is found, using command line:

netsh winhttp show proxy

I get this:

current WinHTTP proxy settings:

Direct access (no proxy server).

and through the control panel-->internet options....... No proxy server (the option of using a proxy server is not activated)

So any thoughts about it......I am trying to pull repos with no success!!!!

**Comment by Changomazo** [comment]
One more thing i forgot to mention, whn i checked my LAN proxy in cmd in windows 10 using the command:

netsh winhttp show proxy

I get this:

urrent WinHTTP proxy settings:

    Direct access (no proxy server).

So i do not understabnd why i get teh connection error in port 443!

**Comment by busches** [comment]
Can you post the full npm debug log?
