### ISSUE TITLE
selenium for java script

### ISSUE THREAD

**Issue by jabussko** [npm/npm#12628]
Hi, I'm trying install selenium for java script.

I have error no repository field. I find somewhere this issue and the solution was to create repository and type new url in package.jason or make repository private. 

I tried both. And any of those work. 

Any idea why npm doesn't see repository?

**Comment by KenanY** [comment]
@jabussko The "no repository field" message should only be a warning, not an error, and it should be safe to ignore it. Regardless, if you would like help with this then please provide your `package.json` and `npm-debug.log`.

**Comment by jabussko** [comment]
@KenanY So if I don't need repository how should I add selenium to project? I'm totally new in it and can't find anything for JavaScript. In instruction for Java there is I should just add library, but in package  which was installed there is no libraries. So I tried another way and download  selenium-webdriver throw PhpStorm (this is what I'm using), but I still don't know if it's ok.

Can you recommend some tutorials or instructions how to start with selenium for JavaScript?

**Comment by KenanY** [comment]
@jabussko Sorry, I have no knowledge of selenium stuff. I recommend finding a forum or IRC channel for other selenium users and asking them. This issue tracker is for bugs in `npm`.

**Comment by jabussko** [comment]
@KenanY I juts hope you will know. Thanks anyway ;)
