### ISSUE TITLE
npm shrinkwrap error

### ISSUE THREAD

**Issue by ajayindfw** [npm/npm#12626]
I am getting a npm shrinkwrap error with:

missing: chalk@^0.5.0 required by gulp-util@0.2.20

npm install works just fine.  I just checked my package.json file.  It has "chalk" listed under package.json as:

"devDevDependencies": {

"chalk": "^1.1.1".

**Comment by elijahsmith** [comment]
"devDevDependencies" is not a valid package.json key -- do you mean "devDependencies", which is?

Also, the "^0.5.0" semver will match anything with the major version 0 but not the major version 1 (as is seen in "chalk": "^1.1.1")
