### ISSUE TITLE
Error when installing gulp

### ISSUE THREAD

**Issue by haider885** [npm/npm#12631]
```
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
```
![gulp error](https://cloud.githubusercontent.com/assets/11913099/15113506/28a3f596-160e-11e6-80de-b09a85f609f0.PNG)

**Comment by KenanY** [comment]
@haider885 Doesn't actually look like an error, just that some of your dependencies are using a deprecated version of `graceful-fs`. You can find these modules with `npm ls graceful-fs`, as the deprecation message already states.

**Comment by haider885** [comment]
So, What should I do next?
"npm ls graceful-fs" shows some kind of tree. But I don't know what to do?

Here is the Output:
===============================================================
├─┬ gulp@3.9.1
│ ├─┬ gulp-util@3.0.7
│ │ └─┬ dateformat@1.0.12
│ │   └─┬ meow@3.7.0
│ │     └─┬ read-pkg-up@1.0.1
│ │       └─┬ read-pkg@1.1.0
│ │         ├─┬ load-json-file@1.1.0
│ │         │ └── graceful-fs@4.1.4
│ │         └─┬ path-type@1.1.0
│ │           └── graceful-fs@4.1.4
│ └─┬ vinyl-fs@0.3.14
│   ├─┬ glob-watcher@0.0.6
│   │ └─┬ gaze@0.5.2
│   │   └─┬ globule@0.1.0
│   │     └─┬ glob@3.1.21
│   │       └── graceful-fs@1.2.3
│   └── graceful-fs@3.0.8
└─┬ laravel-elixir@5.0.0
  ├─┬ browser-sync@2.12.5
  │ ├─┬ chokidar@1.4.3
  │ │ └─┬ readdirp@2.0.0
  │ │   └── graceful-fs@4.1.4
  │ ├─┬ fs-extra@0.26.7
  │ │ └── graceful-fs@4.1.4
  │ └─┬ yargs@4.4.0
  │   ├─┬ pkg-conf@1.1.2
  │   │ └─┬ load-json-file@1.1.0
  │   │   └── graceful-fs@4.1.4
  │   └─┬ read-pkg-up@1.0.1
  │     └─┬ read-pkg@1.1.0
  │       ├─┬ load-json-file@1.1.0
  │       │ └── graceful-fs@4.1.4
  │       └─┬ path-type@1.1.0
  │         └── graceful-fs@4.1.4
  ├─┬ gulp-less@3.1.0
  │ ├─┬ accord@0.23.0
  │ │ └─┬ fobject@0.0.4
  │ │   └── graceful-fs@4.1.4
  │ └─┬ less@2.7.0
  │   └── graceful-fs@4.1.4
  ├─┬ gulp-rev@5.1.0
  │ └─┬ vinyl-file@1.3.0
  │   └── graceful-fs@4.1.4
  ├─┬ gulp-sass@2.3.1
  │ └─┬ node-sass@3.7.0
  │   ├─┬ meow@3.7.0
  │   │ └─┬ read-pkg-up@1.0.1
  │   │   └─┬ read-pkg@1.1.0
  │   │     ├─┬ load-json-file@1.1.0
  │   │     │ └── graceful-fs@4.1.4
  │   │     └─┬ path-type@1.1.0
  │   │       └── graceful-fs@4.1.4
  │   └─┬ node-gyp@3.3.1
  │     └── graceful-fs@4.1.4
  ├─┬ gulp-sourcemaps@1.6.0
  │ └── graceful-fs@4.1.4
  ├─┬ gulp-util@3.0.7
  │ └─┬ dateformat@1.0.12
  │   └─┬ meow@3.7.0
  │     └─┬ read-pkg-up@1.0.1
  │       └─┬ read-pkg@1.1.0
  │         ├─┬ load-json-file@1.1.0
  │         │ └── graceful-fs@4.1.4
  │         └─┬ path-type@1.1.0
  │           └── graceful-fs@4.1.4
  ├─┬ gulp-watch@4.3.5
  │ ├─┬ chokidar@1.4.3
  │ │ └─┬ readdirp@2.0.0
  │ │   └── graceful-fs@4.1.4
  │ └─┬ vinyl-file@1.3.0
  │   └── graceful-fs@4.1.4
  └─┬ watchify@3.7.0
    └─┬ chokidar@1.4.3
      └─┬ readdirp@2.0.0
        └── graceful-fs@4.1.4

**Comment by haider885** [comment]
But the good thing is that, gulp is running now.

**Comment by KenanY** [comment]
@haider885 Ask the authors of those modules to update to a version of `graceful-fs` that is not deprecated.

**Comment by othiym23** [comment]
Closing as resolved – this is only a warning for now, but by Node.js 7, older versions of `graceful-fs` will stop working (you'll need a newish npm by then as well). @KenanY is correct that these issues should be raised with the maintainers of the affected packages.

**Comment by cliffhall** [comment]
For anyone else running into this and wondering what, if anything, to do about it:

https://github.com/gulpjs/gulp/issues/1571
"We are aware of the graceful-fs deprecation warning upon install of gulp 3.x.

This is due to:
1. our graceful-fs devDependency
2. the vinyl-fs dependency

Both of which we are unable to upgrade due to API breaking changes.

There is nothing wrong with the dependency, especially since it is only used in development. We will be updating or removing it in gulp 4 and the message will go away.

Please do not open issues about this topic.
Thank you,
-The gulp team"

**Comment by LAOMUSIC** [comment]
I have:
sudo npm install gulp   
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
