### ISSUE TITLE
can not install express

### ISSUE THREAD

**Issue by lh8725473** [npm/npm#12639]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'express',
1 verbose cli   '--save' ]
2 info using npm@3.8.6
3 info using node@v6.1.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData express
8 silly fetchNamedPackageData express
9 silly mapToRegistry name express
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'express',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   name: 'express',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/express
14 verbose request uri https://registry.npmjs.org/express
15 verbose request no auth needed
16 info attempt registry request try #1 at 09:38:04
17 verbose request id ab52fa9eb82e2c7e
18 verbose etag "6J61RUF7M9V6D09ZLC31GTPOG"
19 http request GET https://registry.npmjs.org/express
20 http 200 https://registry.npmjs.org/express
21 verbose headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
21 verbose headers   etag: '"5QB5PX58CUYZOAEL3J690XNRC"',
21 verbose headers   'content-type': 'application/json',
21 verbose headers   'cache-control': 'max-age=300',
21 verbose headers   'content-length': '536797',
21 verbose headers   'accept-ranges': 'bytes',
21 verbose headers   date: 'Tue, 10 May 2016 01:38:05 GMT',
21 verbose headers   via: '1.1 varnish',
21 verbose headers   age: '40',
21 verbose headers   connection: 'keep-alive',
21 verbose headers   'x-served-by': 'cache-nrt6122-NRT',
21 verbose headers   'x-cache': 'HIT',
21 verbose headers   'x-cache-hits': '20',
21 verbose headers   'x-timer': 'S1462844285.341549,VS0,VE0',
21 verbose headers   vary: 'Accept-Encoding' }
22 silly get cb [ 200,
22 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
22 silly get     etag: '"5QB5PX58CUYZOAEL3J690XNRC"',
22 silly get     'content-type': 'application/json',
22 silly get     'cache-control': 'max-age=300',
22 silly get     'content-length': '536797',
22 silly get     'accept-ranges': 'bytes',
22 silly get     date: 'Tue, 10 May 2016 01:38:05 GMT',
22 silly get     via: '1.1 varnish',
22 silly get     age: '40',
22 silly get     connection: 'keep-alive',
22 silly get     'x-served-by': 'cache-nrt6122-NRT',
22 silly get     'x-cache': 'HIT',
22 silly get     'x-cache-hits': '20',
22 silly get     'x-timer': 'S1462844285.341549,VS0,VE0',
22 silly get     vary: 'Accept-Encoding' } ]
23 verbose get saving express to C:\Users\liuh\AppData\Roaming\npm-cache\registry.npmjs.org\express\.cache.json
24 verbose correctMkdir C:\Users\liuh\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
25 silly install normalizeTree
26 silly loadCurrentTree Finishing
27 silly loadIdealTree Starting
28 silly install loadIdealTree
29 silly cloneCurrentTree Starting
30 silly install cloneCurrentTreeToIdealTree
31 silly cloneCurrentTree Finishing
32 silly loadShrinkwrap Starting
33 silly install loadShrinkwrap
34 silly loadShrinkwrap Finishing
35 silly loadAllDepsIntoIdealTree Starting
36 silly install loadAllDepsIntoIdealTree
37 silly rollbackFailedOptional Starting
38 silly rollbackFailedOptional Finishing
39 silly runTopLevelLifecycles Starting
40 silly runTopLevelLifecycles Finishing
41 silly install printInstalled
42 verbose stack Error: Refusing to install express as a dependency of itself
42 verbose stack     at checkSelf (C:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:53:14)
42 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
42 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
42 verbose stack     at chain (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
42 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:16:5
42 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
42 verbose stack     at Array.forEach (native)
42 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
42 verbose stack     at Array.forEach (native)
42 verbose stack     at asyncMap (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
43 verbose cwd D:\myGithub\express
44 error Windows_NT 6.1.7601
45 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "express" "--save"
46 error node v6.1.0
47 error npm  v3.8.6
48 error code ENOSELF
49 error Refusing to install express as a dependency of itself
50 error If you need help, you may report this error at:
50 error     <https://github.com/npm/npm/issues>
51 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@lh8725473 Rename `D:\myGithub\express` to something which does not share a name with one of your dependencies. Also ensure that your `"name"` attribute in your `package.json` is not set to `"express"`.

**Comment by lh8725473** [comment]
@KenanY   thanks
