### ISSUE TITLE
[3.9.0] Broken release (EMISSINGARG)

### ISSUE THREAD

**Issue by theofidry** [npm/npm#12647]
Hello,

I have a `package.json` and `npm-shrinkwrap.json` (including dev dependencies) both up to date and no `node_modules` (seems to work when there is a `node_modules` already present. When trying to do an install locally (OSX 10.9) or on Travis (cf. [build](https://travis-ci.org/theofidry/travis-bug-demo/jobs/128909465)), `npm install` fails miserably (cf. the screenshot below).
- node: `4.2.6`
- npm: `3.9.0`

<img width="877" alt="screen shot 2016-05-09 at 18 23 09" src="https://cloud.githubusercontent.com/assets/5175937/15121559/1e0b4210-1613-11e6-990e-a5c3d5f5186a.png">

Full `npm-debug.log` content [here](https://gist.github.com/theofidry/3212be0e1c08bddfae928360820cfce9).

**In my case I fixed the problem by downgrading to npm `3.8.9`.**

I would also like to add that there is a couple of similar issues on npm. It maybe would be better to try to regroup them:

They don't all refer to the same node and npm versions. [In some cases](https://github.com/npm/npm/issues/12342#issuecomment-216892552) this seems to be due to a bad symlink when using nvm (btw this issue can be closed AFAICS), but no
- #12342 (npm `3.7.5`, seems to be due to a bad symlink)
- #11728 (npm `3.3.12`)
- #11432 (npm `3.7.1`)
- #11398 (npm `3.6.0`)
- #11085 (npm `3.5.3`)
- #10962 (npm `3.3.12`)
- #10902 (npm `3.5.2`)
- #10704 (npm `3.3.12`)
- #10201 (seems related to #12342)
- #9720 (npm `3.3.3`, `3.3.8`, `3.3.9`, `3.3.12`, `3.5.3`, `3.9.0`)
- #9659 (npm `3.3.3`)
- #12134 (npm `3.7.3`)

As explained at the start of this issue, I have a "clean" repo where you can reproduce the problem: https://github.com/theofidry/npm-bug-demo.

**Comment by mheiniger** [comment]
I have exactly the same problem on OSX 10.11.4 and Travis (actually in a Docker-container)

> npm ERR! node v4.4.2
> npm ERR! npm  v3.9.0
> npm ERR! code EMISSINGARG
> npm ERR! typeerror Error: Missing required argument #1`

It only happens if i have a `npm-shrinkwrap.json`. Without it `npm install` runs fine.

It also doesn't matter if i have dev dependencies in it or not (`npm shrinkwrap` or `npm shrinkwrap --dev`), it crashes for both shrinkwrap files.

Changing back to npm `3.8.9` helped for me too.

**Comment by kamui** [comment]
I'm getting this locally on OS X 10.11.4 and on Heroku too with 3.9.0.

**Comment by groovecoder** [comment]
FWIW if you're hitting this on Travis you can force travis to install 3.8.9 with a simple `npm install -g npm@3.8.9` line.

**Comment by gijsroge** [comment]
Thanks for reporting this. Experiencing the same issue.

**Comment by pasupulaphani** [comment]
We have the same problem. Downgrading to 3.8.

**Comment by bolczyslaw** [comment]
Same here. Downgrading to 3.8 fixed error

**Comment by iarna** [comment]
Flagging as needs-repro as we fixed something similar in early 3.9.x releases and they may have caught this too.

**Comment by theofidry** [comment]
@iarna I reproduced this error in https://github.com/theofidry/npm-bug-demo, but it looks like it has been fixed in `3.6.9` at least.

**Comment by zkat** [comment]
I can't reproduce this one anymore, @theofidry. Are you saying you can't reproduce it with `npm@latest`? If so, I'd like to close this as fixed.

**Comment by theofidry** [comment]
@zkat I only retried with `3.6.9` I didn't check what `latest` is pointing to. This can be closed with a couple of other tickets I've linked in the description.

**Comment by wzlee** [comment]
3.9.3 happen this issue too, how to fixed it ?

**Comment by theofidry** [comment]
Too old, forgot about it :)
