### ISSUE TITLE
How to uninstall a dependency from both package.json and npm-shrinkwrap.json ?

### ISSUE THREAD

**Issue by stouf** [npm/npm#12642]
By looking at the man page of `npm-shrinkwrap` or the [dedicated documentation](https://docs.npmjs.com/cli/shrinkwrap), I can see instructions as for how to add or update dependencies, but I can't see any about how to uninstall dependencies.

By looking at the [documentation of `npm-uninstall`](https://docs.npmjs.com/cli/uninstall), it is said (if we use one of the `--save` options):

> Further, if you have an npm-shrinkwrap.json then it will be updated as well.

However, it doesn't seem to work for me... =/

```
npm uninstall --save my_package
```

will indeed remove `my_package` from my `package.json` file, but my `npm_shrinkwrap.json` file will remain untouched.

Is there a way to remove dependencies from `npm-shrinkwrap.json` through `npm` ? Can we update the documentations I referred to above ?

**Comment by lukasgeiter** [comment]
I just ran into this as well. The shrinkwrap file can be updated by running `npm shrinkwrap` again, but this should definitely happen automatically when uninstalling a package.

**Comment by i-a-n** [comment]
Seeing this problem on NPM version `3.10.3` as well. Anyone have any input or workarounds? (re-running shrinkwrap excluded; not feasible for some of my projects)

**Comment by legodude17** [comment]
Try updating `npm`, also make sure to run it with `--save`.

**Comment by stouf** [comment]
> Try updating `npm`, also make sure to run it with `--save`.

I could confirm that this works with npm v3.10.9! :D

**Comment by 1999** [comment]
I'm sure this is not Stackoverflow, but if your npm-shrinkwrap.json gets close to empty after you run `npm uninstall <package> --save` you just need to run first `npm install` and only then `npm uninstall <package> --save`. Hopefully it works.
