### ISSUE TITLE
Specify package search order on npmjs.com

### ISSUE THREAD

**Issue by Risto-Stevcev** [npm/npm#12643]
It would be nice to have the ability to specify the package search order on npmjs.com

For example:
Have the search results show by most downloads or most stars first.
And to have it show exact matches as the first result.

**Comment by KenanY** [comment]
@Risto-Stevcev https://github.com/npm/newww

**Comment by othiym23** [comment]
@Risto-Stevcev, as @KenanY sorta tersely indicated, this is the issue tracker for the npm CLI. Issues with npm's web site go to [`npm/newww`](https://github.com/npm/newww], and issues with npm's registry go to [`npm/registry`](https://github.com/npm/registry). Closing as not an issue with the CLI. Thanks for your time!
