### ISSUE TITLE
Error: No compatible version found: uglify-js@'~2.3.6'. Regression? 

### ISSUE THREAD

**Issue by CxRes** [npm/npm#12656]
As requested by @KenanY, I am filing a bug report for a problem that seems identical to npm/npm#4833.

This happens when I try to run npm install on the package [private-parts](https://github.com/philipwalton/private-parts). 

Running node 6.0.0, npm 3.8.4, windows 10.
Log File: [npm-debug.log](https://github.com/npm/npm/files/258336/npm-debug.log.txt)

**Comment by KenanY** [comment]
@CxRes I cannot reproduce this with `npm@3.8.4` or `npm@3.8.9` (Node.js v5.9.1, Linux).

Also, when I search your log for

```
Error: No compatible version found: uglify-js@'~2.3.6'
```

I find no such line. I see some lines that look like it, but there's no hyphen in `uglify-js` in those cases. However, when I run `npm install` myself, running `npm ls uglifyjs` afterwards yields no results (meaning that no module is depending on `uglifyjs`). So I don't know why your log shows `npm` trying to install this module (the correct module is `uglify-js`).

**Comment by CxRes** [comment]
Sorry about the *hyphen* and also misquoting npm version (which should be 3.8.6). The error has no hyphen (I got this wrong because even my expectation is that it should be `uglify-js`). The error occurs line 27055 onward in the log file:
```
12733 silly fetchPackageMetaData Error: No compatible version found: uglifyjs@~2.3.6
```
npm refuses to create a `node_modules` folder so I have nothing to `ls` against. But logic suggests there must be a  `uglifyjs` dependency specified somewhere? Is there no way to check where npm encounters this package during its execution?

Could you please try executing this against node 6.0.0, which is the only other thing I could guess might be causing the issue.

**Comment by CxRes** [comment]
Found the problem!!! I installed each dependency by hand and found the `uglify-js` to be inside [grunt-html-smoosher](https://www.npmjs.com/package/grunt-html-smoosher).

Maybe I should open a feature request ticket to always indicate the parent package where the issue occurs. This is too painful a way to debug. 
 
@KenanY Sorry for the trouble and thanks!!!
