### ISSUE TITLE
Installing react-native-cli with node.js 6.1

### ISSUE THREAD

**Issue by faridesquivel** [npm/npm#12655]
Hi, I'm new at this, I want to install the react native command line tools to start using it but this shows up, I tried the "npm install -g react-native-cli" command in different ways but it doesn't work.

(node:22305) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
npm ERR! Error: Cannot find module 'normalize-package-data'
npm ERR!     at Function.Module._resolveFilename (module.js:438:15)
npm ERR!     at Function.Module._load (module.js:386:25)
npm ERR!     at Module.require (module.js:466:17)
npm ERR!     at require (internal/module.js:20:19)
npm ERR!     at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:16:21)
npm ERR!     at Module._compile (module.js:541:32)
npm ERR!     at Object.Module._extensions..js (module.js:550:10)
npm ERR!     at Module.load (module.js:456:32)
npm ERR!     at tryModuleLoad (module.js:415:12)
npm ERR!     at Function.Module._load (module.js:407:3)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 15.4.0
npm ERR! command "/usr/local/Cellar/node/6.1.0/bin/node" "/usr/local/bin/npm" "install" "-g" "react-native-cli"
npm ERR! cwd /Users/farid
npm ERR! node -v v6.1.0
npm ERR! npm -v 1.4.28
npm ERR! code MODULE_NOT_FOUND
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/farid/npm-debug.log
npm ERR! not ok code 0

**Comment by KenanY** [comment]
@faridesquivel Node.js v6 is years old and is no longer supported. `npm@1` is just as old. Please try updating both.

  - https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-node
  - https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm

**Comment by KenanY** [comment]
@faridesquivel Hi, following up a week later: are you still seeing this issue after updating to the latest stable releases of Node.js and `npm`?

**Comment by faridesquivel** [comment]
Hello, updating Node.js and npm fixed this error, thank you very much!
