### ISSUE TITLE
npm installation failing after cloning angular-material project from github

### ISSUE THREAD

**Issue by krantichevula** [npm/npm#12659]
D:\Work\Repo\delete\angular-material-proj\material-start>npm install
npm ERR! git clone --template=C:\Users\cmohanaranga\AppData\Roaming\npm-cache_g
it-remotes_templates --mirror ssh://git@github.com/angular/bower-material.git C
:\Users\cmohanaranga\AppData\Roaming\npm-cache_git-remotes\git-ssh-git-github-c
om-angular-bower-material-git-master-5f5812a5: Cloning into bare repository 'C:\
Users\cmohanaranga\AppData\Roaming\npm-cache_git-remotes\git-ssh-git-github-com
-angular-bower-material-git-master-5f5812a5'...
npm ERR! git clone --template=C:\Users\cmohanaranga\AppData\Roaming\npm-cache_g
it-remotes_templates --mirror ssh://git@github.com/angular/bower-material.git C
:\Users\cmohanaranga\AppData\Roaming\npm-cache_git-remotes\git-ssh-git-github-c
om-angular-bower-material-git-master-5f5812a5: Host key verification failed.
npm ERR! git clone --template=C:\Users\cmohanaranga\AppData\Roaming\npm-cache_g
it-remotes_templates --mirror ssh://git@github.com/angular/bower-material.git C
:\Users\cmohanaranga\AppData\Roaming\npm-cache_git-remotes\git-ssh-git-github-c
om-angular-bower-material-git-master-5f5812a5: fatal: Could not read from remote
 repository.
npm ERR! git clone --template=C:\Users\cmohanaranga\AppData\Roaming\npm-cache_g
it-remotes_templates --mirror ssh://git@github.com/angular/bower-material.git C
:\Users\cmohanaranga\AppData\Roaming\npm-cache_git-remotes\git-ssh-git-github-c
om-angular-bower-material-git-master-5f5812a5:
npm ERR! git clone --template=C:\Users\cmohanaranga\AppData\Roaming\npm-cache_g
it-remotes_templates --mirror ssh://git@github.com/angular/bower-material.git C
:\Users\cmohanaranga\AppData\Roaming\npm-cache_git-remotes\git-ssh-git-github-c
om-angular-bower-material-git-master-5f5812a5: Please make sure you have the cor
rect access rights
npm ERR! git clone --template=C:\Users\cmohanaranga\AppData\Roaming\npm-cache_g
it-remotes_templates --mirror ssh://git@github.com/angular/bower-material.git C
:\Users\cmohanaranga\AppData\Roaming\npm-cache_git-remotes\git-ssh-git-github-c
om-angular-bower-material-git-master-5f5812a5: and the repository exists.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Users\cmohanaranga\Ap
pData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v4.4.3
npm ERR! npm  v3.8.9
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\cm
ohanaranga\AppData\Roaming\npm-cache_git-remotes_templates --mirror ssh://git@
github.com/angular/bower-material.git C:\Users\cmohanaranga\AppData\Roaming\npm-
cache_git-remotes\git-ssh-git-github-com-angular-bower-material-git-master-5f58
12a5
npm ERR! Cloning into bare repository 'C:\Users\cmohanaranga\AppData\Roaming\npm
-cache_git-remotes\git-ssh-git-github-com-angular-bower-material-git-master-5f5
812a5'...
npm ERR! Host key verification failed.
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Work\Repo\delete\angular-material-proj\material-start\npm-debug.
log

D:\Work\Repo\delete\angular-material-proj\material-start>n

**Comment by lbrln** [comment]
Having the same problem.
Is there an alternative source for download?
Sorry if it is silly question (first time on github), I need to build something on the top of it in few days and now stuck as I can't even download it :(

**Comment by dev-ab** [comment]
Having same problem here

**Comment by Jmales** [comment]
Did you guys solve this? I'm having the same problem (https://github.com/npm/npm/issues/15699)
