### ISSUE TITLE
Getting node_modules in non npm directory

### ISSUE THREAD

**Issue by aayushkapoor206** [npm/npm#12652]
The folder gets auto generated even when there is no package.json file in the directory after npm install

**Comment by KenanY** [comment]
Sounds like a duplicate of https://github.com/npm/npm/issues/11967.

**Comment by KenanY** [comment]
@aayushkapoor206 Following up a week later: can this issue be closed as a duplicate of the issue I mentioned above?

**Comment by aayushkapoor206** [comment]
@KenanY Yes but it's still unsolved...
