### ISSUE TITLE
Interaction between npm cache, shrinkwrap and npm config set registry prevents us from reliably installing from our internal registry

### ISSUE THREAD

**Issue by BenjaminMalley** [npm/npm#12671]
We run an internal npm registry. We've discovered that when users run shrinkwrap, the shrinkwrap manifest records the url the package resolved to **at the point it was added to the user's local cache** and further, because it is installed from shrinkwrap on subsequent installations, it will always be installed from said url. This means that if a user ever installs a dependency from registry.npmjs.org in any project on their local machine, registry.npmjs.org will show up in their shrinkwrap and npm will install dependencies from registry.npmjs.org, even when the npm config is set to a different registry.

Of course, users could prevent this problem from occurring by maintaining a separate npm cache for their open source projects, but this feels overly burdensome. Mostly, I feel, what users using shrinkwrap want is to record the artifact name & version, not necessarily specify the url to retrieve it. Is there a way in npm to achieve something like this? Clearly, this wouldn't work for dependencies source from github, etc., but for artifacts that have name & version, is it necessary to record (and subsequently fetch from) the url?

**Comment by Fryie** [comment]
agreed; ideally, the shrinkwrap would add a hash of the file contents, but the exact location the package was retrieved from doesn't belong there IMHO. See also #12675.
