### ISSUE TITLE
issue regarding installation of ReactJS

### ISSUE THREAD

**Issue by shubham19bhatt** [npm/npm#12688]
Hello Sir
            I am facing problem while installation of ReactJS via command prompt,when I tried to run these files  ' npm install babel-core,npm install babel-loader,npm install babel-preset-react,npm install babel-preset-es2015',i got errors which are as follows:-1)Skipping failed optional  dependency/chokidar/fsevents:  
(2)Not compatible with your operating system or architecture:fsevents@0.1.12
Along with it when I run 'npm start' command I got following errors: 1) npm ERR! Windows_NT 6.3.9600
2)node ERR! node v6.1.0
3)npm ERR! node v3.8.6
4)npm ERR! missing script : start

**Comment by KenanY** [comment]
@shubham19bhatt `fsevents` is a module that is intended for use on Mac OS only, so it is safe to ignore that warning since you are using Windows.

Do you have a `"start"` script defined in your `package.json`? If not, `npm` will have no idea what you want it to do when you run `npm start`, and will throw the error message you are seeing.

**Comment by KenanY** [comment]
@shubham19bhatt It has been several weeks with no response from you... are you still seeing this issue?

**Comment by shubham19bhatt** [comment]
@KenanY Yes am still facing several issues while starting npm, and yes i have described that "start" script in my package.json file but its not working. Issues are as follows : Windows NT 9600.6.3,argv err,webpack dev start and many others
Thanks for replying and i hope this time you will give me best resolution for it.

**Comment by KenanY** [comment]
@shubham19bhatt Can I see a `npm-debug.log` file and perhaps your `package.json` as well?

**Comment by KenanY** [comment]
@shubham19bhatt Hi, it has been over two weeks now with no response from you. Are you still facing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
