### ISSUE TITLE
No compatible version found: lodash._basetostring@~4.12.0

### ISSUE THREAD

**Issue by vbotnaru** [npm/npm#12680]
33599 error node v4.4.0
33600 error npm  v3.8.9
33601 error No compatible version found: lodash._basetostring@~4.12.0
33601 error Valid install targets:
33601 error 3.0.1, 3.0.0
33602 error If you need help, you may report this error at:
33602 error     <https://github.com/npm/npm/issues>
33603 verbose exit [ 1, true ]

**Comment by rrazony** [comment]
I'm getting same error message.

**Comment by KenanY** [comment]
ref. https://github.com/lodash/lodash/issues/2326

**Comment by jdalton** [comment]
What's your lodash package dep (name, version).

**Comment by BadAsstronaut** [comment]
Same problem observed by myself and at least 3 other coworkers.

**Comment by kennygrubb** [comment]
I'm getting the same error as well.

**Comment by jdalton** [comment]
Looks like folks in the U.S. (SF, WA, MD) are getting 4.12.0 but others aren't.
For those not getting it what general location are you in?

**Comment by vbotnaru** [comment]
Montreal

**Comment by BadAsstronaut** [comment]
CO, USA.

**Comment by kzettlmeier** [comment]
Also seeing this issue Chicago, IL

**Comment by kennygrubb** [comment]
so my issue was that we use nexus to proxy npm, and our nexus server was configured to sync every 24 hours. Are you guys using npm proxies? I'm in Houston,TX

**Comment by kzettlmeier** [comment]
@kennygrubb we are using Nexus as a proxy, but others at the company don't seem to be having this issue except for me.

**Comment by kzettlmeier** [comment]
@kennygrubb must of still been related to Nexus cache though, I invalidated the cache on the Nexus Repository and it started to work for me.

**Comment by othiym23** [comment]
Closing because this is an issue with the registry and not the CLI – if you're still seeing this issue, please take your comments and troubleshooting info over to [the `npm/registry` issue tracker](https://github.com/npm/registry/issues), which is meant for these kinds of issues. Thanks for your time!

**Comment by jdalton** [comment]
Moved to https://github.com/npm/registry/issues/18.

**Comment by varunkumar** [comment]
I m facing the same issue with Nexus. How do we invalidate the cache there?

**Comment by gcusnieux** [comment]
@varunkumar Go to nexus, Right Click on proxy repository and expire cache
