### ISSUE TITLE
Issue and Pull Request templates

### ISSUE THREAD

**Issue by watilde** [npm/npm#12681]
You know we can have a template to help contributors report/proposal something easily:
https://github.com/blog/2111-issue-and-pull-request-templates

Within the issue template file, the file should contain the following points:
- version of npm
- version of Node.js
- platform
- npm-debug.log

For the pull request template, we can use the nodejs's one as reference:
https://github.com/nodejs/node/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by legodude17** [comment]
You could also incorporate that template into `npm bugs npm` so it asks for those things and auto includes npm-debug.

**Comment by watilde** [comment]
Yeah there was a similar plan to that called `npm report`: https://github.com/npm/npm/issues/5214

**Comment by legodude17** [comment]
@watilde  I would want something where you go like:
`npm report`
`What is the error? Error`
`Describe it. blahblahblah`
`Path to npm-debug? /home/.../Desktop/Code/.../.../npm-debug.log`
`Thank you.`
So it would bring you to https://github.com/npm/support-cli/issues/new?body=blahblahblah&title=Error. You could add more questions.

**Comment by EmmaRamirez** [comment]
Reopening because we still need to open a PR template!
