### ISSUE TITLE
Offline: Installing from cache is slower (!) than with internet connection

### ISSUE THREAD

**Issue by franzliedke** [npm/npm#12689]
I recently did some development without internet access. After switching to another branch in my repo, I needed to update some dependencies. Because I had used that branch earlier, I suspected the packages may be available in the cache, so I tried running `npm install`.

The installation did, in fact, work, so hurray for that. However, it took much longer than with internet (and it's already slow then). Apparently, for every package to install, NPM tried to contact the registry, and after a timeout of what must have been around 30 seconds decided to fall back to the cache, where it found the package.

Shouldn't the installer be smart enough to skip the timeout after having established that there is no connection?

Node version: 5.0.0
NPM version: 3.3.6

This _might_ be related to #2568, but it seems to be a somewhat different feature request, so I'm creating a new one...

**Comment by whitecolor** [comment]
Latest versions are much slower then previous almost in any aspects, `yarn` is much better in this sense regardless its current caveats.
