### ISSUE TITLE
Cannot start npm

### ISSUE THREAD

**Issue by bkabiro** [npm/npm#12693]
```
npm ERR! Linux 4.2.0-36-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v5.11.1
npm ERR! npm  v3.8.6

npm ERR! missing script: start
npm ERR! 
```

**Comment by KenanY** [comment]
@bkabiro Do you have a `"start"` script defined in your `package.json`? Without one, `npm` will have no idea what you want it to do, and as such it will throw the error you are seeing.

**Comment by KenanY** [comment]
@bkabiro It has been several weeks with no response from you; are you still seeing this issue?

**Comment by bkabiro** [comment]
I'm sorry I didn't get back.I had Ubuntu installed on my machine but I
replaced it with Windows 8. I was a newbie and so I had a hard time
understanding it then.
I have had no problem with npm on Windows so thats why I kept quiet.
Thanks for the follow up, Kenan.

**Comment by KenanY** [comment]
Closing as resolved and not an issue with `npm`.
