### ISSUE TITLE
npm ignores parent folder's node_modules

### ISSUE THREAD

**Issue by andreineculau** [npm/npm#12690]
Using npm 3.8.6, I get an unexpected behaviour, where npm is ignoring the parent folder's node_modules, despite matching semvers, and installs the dependency "again".

This seems to contradict https://docs.npmjs.com/files/folders#cycles-conflicts-and-folder-parsimony

> Cycles are handled using the property of node's module system that it walks up the directories looking for node_modules folders. So, at every stage, if a package is already installed in an ancestor node_modules folder, then it is not installed at the current location.

Repository to reproduce https://github.com/andreineculau/test-npm-parent-node_modules

**Comment by pocesar** [comment]
the behavior is different from an executed file from node itself, that will look for parent folders when doing a `require`, was expecting the same behavior from npm. I have many subfolders and their respective test folders, and when I try to make use of a common `node_modules` with test. 
`ava` and `nyc` are reaaally big (with all it's dependencies) around 25MB, having to install them for 18+ folders... wow

**Comment by harsimranb** [comment]
Any update on this?  I am also experiencing this issue.  Could really use node_modules in parent directory to save time.

**Comment by ruifortes** [comment]
Would be really nice to have an option to install that would link to modules found in parent.
Seams so clean and useful. Why is this problematic?

**Comment by pocesar** [comment]
@npm-robot you silly goose
