### ISSUE TITLE
Add `sign-git-commit` config for GPG-signed commits during `npm version`

### ISSUE THREAD

**Issue by tribou** [npm/npm#12696]
Currently, `npm@3.8.9` supports a `sign-git-tag` config which enables the `git tag -s` command instead of `git tag` in order to perform GPG-signed tags.  However, the git commit performed prior to the tagging and after the package version is bumped does not support signing.  This results in a signed tag but an unsigned git commit.

For consistency, it would be nice to have an additional `git-sign-commit` boolean npm config flag which enabled `git commit -S` when creating the commit to save the new package version.

This would be a non-breaking feature addition since the default behavior could fallback to the current `git commit` when the `sign-git-commit=true` config is not present.

The change could me made [similar to this](https://github.com/npm/npm/blob/2a5977e0c65b244e92d848fcd56f2f80ba8cdf3b/lib/version.js#L261).  However, if I'm not mistaken, the `-S` flag in the `git commit` command may need to be spaced separately from the `-m` instead of being combined like the the `-sm` in the `git tag` command.

**Comment by maxkoryukov** [comment]
Probably, **must be reopened**

@tribou

**Comment by tribou** [comment]
Yes, it'd be great if this could be re-considered.

The PR would probably need to be re-written since it's been over a year...

**Comment by tribou** [comment]
For anyone following this thread, I forgot to mention this feature was re-opened here: #17429.
