### ISSUE TITLE
unble to run npm install successfully

### ISSUE THREAD

**Issue by saiteja-happy** [npm/npm#12708]

**Comment by saiteja-happy** [comment]
DONE!!

npm config rm proxy
npm config rm https-proxy

**Comment by doug-wade** [comment]
Hey @saiteja-happy, it looks like you resolved your issue.  If so, consider closing the issue.  If not, you should have seen a similar couple of lines in your error message

```
npm ERR! Please include the following file with any support request:
npm ERR!     /Users/doug.wade/code/stratocacher/npm-debug.log
```

please include that npm-debug.log file.
