### ISSUE TITLE
Getting an "UNABLE_TO_GET_ISSUER_CERT_LOCALLY" message

### ISSUE THREAD

**Issue by HenryReissig** [npm/npm#12701]
hreissig01@HH0082013709 MINGW64 ~/desktop/helloreact
$ npm install express@4 --save
npm WARN package.json hello-react@1.0.0 No repository field.
npm WARN package.json hello-react@1.0.0 No README data
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files (x86)\nodejs\node.exe" "C:\Program Files (x86)\nodejs\node_modules\npm\bin\npm-cli.js" "install" "express@4" "--save"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code UNABLE_TO_GET_ISSUER_CERT_LOCALLY

npm ERR! unable to get local issuer certificate
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\HReissig01\desktop\helloreact\npm-debug.log

**Comment by salamanderjoe** [comment]
Please let me know if you are you connected via a proxy

**Comment by salamanderjoe** [comment]
If you are, it may be that you need to add your CA to include your company's certificate chain like this
`npm config set cafile="your_CA_file_here.pem" `
More details can be found here: [Link](https://docs.npmjs.com/misc/config#cafile)
Alternatively, you can do
`npm config set strict-ssl false`

**Comment by KaKmi** [comment]
I user set cafile,then Ok ,thanks
