### ISSUE TITLE
Pre-Release Version 3.9.1 Crashes for Incremental Shrinkwrap Installs

### ISSUE THREAD

**Issue by misterbyrne** [npm/npm#12702]
Hey,

I've tested the latest pre-release version (npm@3.9.1) here with an incremental shrinkwrap install and it crashes reliably.
I confirmed that my original branch (based off an old master) didn't crash, and that the current master branch didn't crash if I reverted my commit (this one https://github.com/npm/npm/commit/b8944139a935680c4a267468bb2d3c3082b5609f).

Here's the crash:

```
npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at markDeps (/Users/adambyrne/.nvm/versions/node/v5.10.1/lib/node_modules/npm/lib/install/deps.js:106:5)
npm ERR! typeerror     at /Users/adambyrne/.nvm/versions/node/v5.10.1/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
npm ERR! typeerror     at Array.forEach (native)
npm ERR! typeerror     at /Users/adambyrne/.nvm/versions/node/v5.10.1/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
npm ERR! typeerror     at Array.forEach (native)
npm ERR! typeerror     at asyncMap (/Users/adambyrne/.nvm/versions/node/v5.10.1/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
npm ERR! typeerror     at Array.<anonymous> (/Users/adambyrne/.nvm/versions/node/v5.10.1/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
npm ERR! typeerror     at LOOP (/Users/adambyrne/.nvm/versions/node/v5.10.1/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
npm ERR! typeerror     at chain (/Users/adambyrne/.nvm/versions/node/v5.10.1/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
npm ERR! typeerror     at recalculateMetadata (/Users/adambyrne/.nvm/versions/node/v5.10.1/lib/node_modules/npm/lib/install/deps.js:147:3)
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>
```

I debugged a little and could see that it's because here: https://github.com/npm/npm/blob/master/lib/install/deps.js#L139-L141
`child.package._spec` is undefined for all the `childrenOnlyInShrinkwrap`

So I did a `git bisect` to figure out what might have brought about the incompatibility (since it worked okay on my old branch). It seems to be this commit:

https://github.com/npm/npm/commit/e928a30947477a09245f54e9381f46b97bee32d5

So the master branch with either one of those commits missing works just fine, but as it is it crashes. Probably not with all incremental shrinkwrap installs, I can definitely recreate it easily here (with a private repo though).

**Comment by iarna** [comment]
So the problem here is that packages inflated from shrinkwrap that are already on disk bypass the fetch-package-metadata step. `fetch-package-metadata` adds some diagnostic and some crucial metadata to packages. One-offing `_spec` will surely solve the problem in this case, but I'd like to generalize that a bit.

The reason the test didn't catch it is that this does not impact trees created by `npm@3.9.1`. Because those trees have `_spec` in their `package.json` files, and so this error never comes up.

**Comment by misterbyrne** [comment]
Cool - I figured you would come up with a more general solution! Thanks for the info.

**Comment by iarna** [comment]
Ah, this was fixed quite a while ago!
