### ISSUE TITLE
Not able to install synchronize in windows 7 64 bit

### ISSUE THREAD

**Issue by deechakr** [npm/npm#12717]
Hi team,

Not able to install synchronize in windows

 7 64 bit. Log file attached.

**Comment by deechakr** [comment]
[npm-debug.txt](https://github.com/npm/npm/files/265820/npm-debug.txt)

**Comment by martinheidegger** [comment]
Hello @deechakr  I am not part of the team here but I think for triaging this bug it would be good to have the dependencies (and devDependencies) of your package.json and the list of packages in `node_modules`.
