### ISSUE TITLE
Refusing to install avconv as a dependency of itself

### ISSUE THREAD

**Issue by Doug-Wyman** [npm/npm#12716]
```
npm ERR! Linux 3.10.65-5-pine64-longsleep
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "avconv"
npm ERR! node v7.0.0-pre
npm ERR! npm  v3.9.0
npm ERR! code ENOSELF

npm ERR! Refusing to install avconv as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/code/GitHub/avconv/npm-debug.log
```

[npm-debug.txt](https://github.com/npm/npm/files/265389/npm-debug.txt)

**Comment by Doug-Wyman** [comment]
Installing on a pine64 running Debian.  Installed node then npm then tried installing avconv.

**Comment by mattiafianco** [comment]
I have the same problem, the terminal tells me "Refusing to install avconv as a dependency of itself"
The Parrot AR Drone is connected with the wifi but it does not work.

**Comment by KenanY** [comment]
@Doug-Wyman Try renaming the `/mnt/code/GitHub/avconv/` directory to something which does not share a name with one of your dependencies (in this case, anything but `"avconv"`). Also ensure that the `"name"` attribute of your `package.json` is not set to `"avconv"`.

**Comment by Doug-Wyman** [comment]
@KenanY Thank you.  changing the name in package.json overcame that error.  Now I am on to the next error.  Is the forum protocol to create another thread?  I am going to paste the new error and errorfile here but will start a new thread if that is the preferred way.

 npm install avconv
npm ERR! tar.unpack untar error /root/.npm/avconv/3.0.2/package.tgz
npm WARN You are using a pre-release version of node and things may not work as expected
npm ERR! Linux 3.10.65-5-pine64-longsleep
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "avconv"
npm ERR! node v7.0.0-pre
npm ERR! npm  v3.9.0
npm ERR! path /mnt/code/GitHub/av_conv/node_modules/.staging/avconv-b7ddcf78/package.json
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall chown

npm ERR! Error: EACCES: permission denied, chown '/mnt/code/GitHub/av_conv/node_modules/.staging/avconv-b7ddcf78/package.json'
npm ERR!     at Error (native)
npm ERR!  { Error: EACCES: permission denied, chown '/mnt/code/GitHub/av_conv/node_modules/.staging/avconv-b7ddcf78/package.json'
npm ERR!     at Error (native)
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'chown',
npm ERR!   path: '/mnt/code/GitHub/av_conv/node_modules/.staging/avconv-b7ddcf78/package.json',
npm ERR!   fstream_finish_call: 'chown',
npm ERR!   fstream_type: 'File',
npm ERR!   fstream_path: '/mnt/code/GitHub/av_conv/node_modules/.staging/avconv-b7ddcf78/package.json',
npm ERR!   fstream_class: 'FileWriter',
npm ERR!   fstream_stack:
npm ERR!    [ '/usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:306:21',
npm ERR!      '/usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:210:7',
npm ERR!      'FSReqWrap.oncomplete (fs.js:117:15)' ],
npm ERR!   parent: 'av_conv' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/code/GitHub/av_conv/npm-debug.log
[npm-debug2.txt](https://github.com/npm/npm/files/266602/npm-debug2.txt)

**Comment by Doug-Wyman** [comment]
I think I just found the answer to this latest.  I am running the install from a file server and the Pine64 can't CHOWN on that serve.  Moving install files to my Pine64

**Comment by KenanY** [comment]
@Doug-Wyman 

Seeing

```
└── avconv@3.0.2 extraneous
```

 in your `npm ls` or `npm install` output _should_ indicate that `avconv` is installed. The "extraneous" part is only indicating that the module is not defined as a dependency in your `package.json`, so `npm` considers it extraneous.

**Comment by Doug-Wyman** [comment]
@KenanY  Thank you very much.  avconv still didn't install but that could be caused by any number of things.  I ended up with a pre-release node (don't know how) and need to replace it with a release version for ARM 64 processor.  That plus it being a Pine64 and new release OS which may be buggy.  Ah the fun of experimentation and learning when retired and 73 years old.
