### ISSUE TITLE
When shrinkwrap is used npm install won't update git dependencies

### ISSUE THREAD

**Issue by kossnocorp** [npm/npm#12718]
See the problem:

![](http://i.ncrp.co/2F1u040j3t2B/Fullscreen_16_05_16_15_46.png)

To reproduce locally, run (see https://github.com/kossnocorp/npm-shrinkwrap-bug):

```bash
git clone git@github.com:kossnocorp/npm-shrinkwrap-bug.git
cd npm-shrinkwrap-bug
npm install
```

**Comment by philberg** [comment]
If you run shrinkwrap on this, it will also fail.

I am also facing this issue for the following reason.

My top level package "A" has a dep "B" which is installed via git.  Dep "B" has a dep on the chai package (v3.4.*) and package "A" has a devDep on chai (v3.3.*).  This is breaking shrinkwrap

`npm ERR! missing: chai@3.4.*, required by package B`

**Comment by iarna** [comment]
For reference:
```
$ npm ls
npm-shrinkwrap-bug@ /Users/rebecca/code/npmtest/12718/npm-shrinkwrap-bug
└── left-pad@1.1.0 invalid (git://github.com/stevemao/left-pad.git#37723f75f3a2cf99ce0b64bd14de6c2818cfb506)

npm ERR! invalid: left-pad@1.1.0 /Users/rebecca/code/npmtest/12718/npm-shrinkwrap-bug/node_modules/left-pad
```
Obviously, it should be seeing that the installed version doesn't match and try to install from the shrinkwrap (which would then fail, because that committish doesn't exist).

**Comment by kossnocorp** [comment]
I've successfully wrote a fix:

```diff
diff --git a/lib/install/inflate-shrinkwrap.js b/lib/install/inflate-shrinkwrap.js
index f5f53f1..dfc12fc 100644
--- a/lib/install/inflate-shrinkwrap.js
+++ b/lib/install/inflate-shrinkwrap.js
@@ -29,7 +29,7 @@ var inflateShrinkwrap = module.exports = function (tree, swdeps, finishInflating
     if (child && (child.fromShrinkwrap ||
                   (sw.resolved && child.package._resolved === sw.resolved) ||
                   (sw.from && url.parse(sw.from).protocol && child.package._from === sw.from) ||
-                  child.package.version === sw.version)) {
+                  (!child.package.gitHead && child.package.version === sw.version))) {
       if (!child.fromShrinkwrap) child.fromShrinkwrap = spec
       tree.children.push(child)
       return inflateShrinkwrap(child, sw.dependencies || {}, next)
```

It fixes the both problems (missing update and failure during `npm shrinkwrap` run). Now I need to add tests, but I'm not sure where to start. It would be cool if someone could help me with that.

**Comment by kossnocorp** [comment]
See PR: https://github.com/npm/npm/pull/12770

**Comment by codykrainock** [comment]
I described the issue in vivid detail here: https://github.com/codykrainock/use-sw-bug

Can we please have the fix merged? This bug broke our site today.
