### ISSUE TITLE
npm ls - list installed tarballs

### ISSUE THREAD

**Issue by DanielSchuech** [npm/npm#12711]
Hi,

I've created a tarball with `npm pack` and installed it with the --save parameter. The dependency field in the package.json contains correctly the file path to the tarball. `npm ls` don't recognize the package and don't list it.

**Comment by KenanY** [comment]
@DanielSchuech Thanks for the bug report! `npm --version`?

**Comment by DanielSchuech** [comment]
3.60

I thought I ve done an update but my git bash under windows hasn't updated npm. Its working correctly under version 3.9.0. Sry for the inconveniences and thanks for the fast answer.

**Comment by KenanY** [comment]
@DanielSchuech No inconvenience at all! I'm glad to hear that it's working now :)
