### ISSUE TITLE
Issue while installing NPM behind firewall

### ISSUE THREAD

**Issue by GirishVC86** [npm/npm#12729]
C:\Inetpub\wwwroot\angularjs2>npm install
npm WARN package.json angular2-quickstart@1.0.0 No description
npm WARN package.json angular2-quickstart@1.0.0 No repository field.
npm WARN package.json angular2-quickstart@1.0.0 No README data
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1

npm ERR! Unexpected token <
npm ERR! <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
npm ERR! <HTML><HEAD><TITLE>The page cannot be found</TITLE>
npm ERR! <META HTTP-EQUIV="Content-Type" Content="text/html; charset=Windows-1252">
npm ERR! <STYLE type="text/css">
npm ERR!   BODY { font: 8pt/12pt verdana }
npm ERR!   H1 { font: 13pt/15pt verdana }
npm ERR!   H2 { font: 8pt/12pt verdana }
npm ERR!   A:link { color: red }
npm ERR!   A:visited { color: maroon }
npm ERR! </STYLE>
npm ERR! </HEAD><BODY><TABLE width=500 border=0 cellspacing=10><TR><TD>
npm ERR!
npm ERR! <h1>The page cannot be found</h1>
npm ERR! The page you are looking for might have been removed, had its name changed, or is temporarily unavailable.
npm ERR! <hr>
npm ERR! <p>Please try the following:</p>
npm ERR! <ul>
npm ERR! <li>Make sure that the Web site address displayed in the address bar of your browser is spelled and formatted correctly.</li>
npm ERR! <li>If you reached this page by clicking a link, contact
npm ERR!  the Web site administrator to alert them that the link is incorrectly formatted.
npm ERR! </li>
npm ERR! <li>Click the <a href="javascript:history.back(1)">Back</a> button to try another link.</li>
npm ERR! </ul>
npm ERR! <h2>HTTP Error 404 - File or directory not found.<br>Internet Information Services (IIS)</h2>
npm ERR! <hr>
npm ERR! <p>Technical Information (for support personnel)</p>
npm ERR! <ul>
npm ERR! <li>Go to <a href="http://go.microsoft.com/fwlink/?linkid=8180">Microsoft Product Support Services</a> and perform a title search for the words <b>HTTP</b> and <b>404</b>.</li>
npm ERR! <li>Open <b>IIS Help</b>, which is accessible in IIS Manager (inetmgr),
npm ERR!  and search for topics titled <b>Web Site Setup</b>, <b>Common Administrative Tasks</b>, and <b>About Custom Error Messages</b>.</li>
npm ERR! </ul>
npm ERR!
npm ERR! </TD></TR></TABLE></BODY></HTML>
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Inetpub\wwwroot\angularjs2\npm-debug.log

C:\Inetpub\wwwroot\angularjs2>npm cache clean -f
npm WARN using --force I sure hope you know what you are doing.

C:\Inetpub\wwwroot\angularjs2>npm install -g n
npm ERR! registry error parsing json
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "n"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1

npm ERR! Unexpected token <
npm ERR! <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
npm ERR! <HTML><HEAD><TITLE>The page cannot be found</TITLE>
npm ERR! <META HTTP-EQUIV="Content-Type" Content="text/html; charset=Windows-1252">
npm ERR! <STYLE type="text/css">
npm ERR!   BODY { font: 8pt/12pt verdana }
npm ERR!   H1 { font: 13pt/15pt verdana }
npm ERR!   H2 { font: 8pt/12pt verdana }
npm ERR!   A:link { color: red }
npm ERR!   A:visited { color: maroon }
npm ERR! </STYLE>
npm ERR! </HEAD><BODY><TABLE width=500 border=0 cellspacing=10><TR><TD>
npm ERR!
npm ERR! <h1>The page cannot be found</h1>
npm ERR! The page you are looking for might have been removed, had its name changed, or is temporarily unavailable.
npm ERR! <hr>
npm ERR! <p>Please try the following:</p>
npm ERR! <ul>
npm ERR! <li>Make sure that the Web site address displayed in the address bar of your browser is spelled and formatted correctly.</li>
npm ERR! <li>If you reached this page by clicking a link, contact
npm ERR!  the Web site administrator to alert them that the link is incorrectly formatted.
npm ERR! </li>
npm ERR! <li>Click the <a href="javascript:history.back(1)">Back</a> button to try another link.</li>
npm ERR! </ul>
npm ERR! <h2>HTTP Error 404 - File or directory not found.<br>Internet Information Services (IIS)</h2>
npm ERR! <hr>
npm ERR! <p>Technical Information (for support personnel)</p>
npm ERR! <ul>
npm ERR! <li>Go to <a href="http://go.microsoft.com/fwlink/?linkid=8180">Microsoft Product Support Services</a> and perform a title search for the words <b>HTTP</b> and <b>404</b>.</li>
npm ERR! <li>Open <b>IIS Help</b>, which is accessible in IIS Manager (inetmgr),
npm ERR!  and search for topics titled <b>Web Site Setup</b>, <b>Common Administrative Tasks</b>, and <b>About Custom Error Messages</b>.</li>
npm ERR! </ul>
npm ERR!
npm ERR! </TD></TR></TABLE></BODY></HTML>
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Inetpub\wwwroot\angularjs2\npm-debug.log[](url)

[npm-debug.txt](https://github.com/npm/npm/files/268020/npm-debug.txt)

**Comment by KenanY** [comment]
@GirishVC86 Have you configured your firewall to allow `npm`'s requests to the registry?

**Comment by GirishVC86** [comment]
I have used the following command 

npm config set proxy http://"username@domainname:password"@hsot:port
npm config set https-proxy http://"username@domainname:password"@hsot:port

and even tried the following

npm config set http_proxy "http://domain%5Cusername:password@host:port"
npm config set proxy "http://domain%5Cusername:password@host:port"

**Comment by legodude17** [comment]
What were you trying to install? Can you upload `npm-debug.log` and post the link? Is your internet connection working? Does your proxy allow requests to `https://registry.npmjs.com`?

**Comment by KenanY** [comment]
Closing as abandoned.
