### ISSUE TITLE
npm ERR! network If you are behind a proxy

### ISSUE THREAD

**Issue by mcshakes** [npm/npm#12725]
$ npm install -g ember-cli
npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/edmac/.nvm/versions/node/v5.7.0/bin/node" "/Users/edmac/.nvm/versions/node/v5.7.0/bin/npm" "install" "-g" "ember-cli"
npm ERR! node v5.7.0
npm ERR! npm  v3.6.0
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! syscall connect

npm ERR! network connect ETIMEDOUT 23.235.47.162:443
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

-----

Thing is, I'm not behind a proxy. What can I do about this? Anything on my end to help with the install?

**Comment by KenanY** [comment]
@mcshakes Maybe you are behind a firewall? Have you tried connecting to a different network?

**Comment by lxe** [comment]
Are you able to access https://registry.npmjs.org via a browser? If not, the problem might lie in your firewall/network set up.

**Comment by mcshakes** [comment]
@KenanY I don't believe so and not behind a proxy. I'll try at a cafe maybe...

@lxe I was able to access it. Got 
```
{"db_name":"registry","doc_count":325969,"doc_del_count":356,"update_seq":2473247,"purge_seq":0,"compact_running":false,"disk_size":1660866683,"data_size":1221259956,"instance_start_time":"1463454303694056","disk_format_version":6,"committed_update_seq":2473247}
```
Does that look right?

**Comment by mcshakes** [comment]
Ran it again from a different area, and it installed normally. I don't have have a firewall nor am I behind a proxy, but oh well. I'll close this issue, thanks.
