### ISSUE TITLE
symlink protocol error

### ISSUE THREAD

**Issue by joenmarz** [npm/npm#12733]
After npm install I got this error:

npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! path ../acorn/bin/acorn
npm ERR! code EPROTO
npm ERR! errno -71
npm ERR! syscall symlink

npm ERR! EPROTO: protocol error, symlink '../acorn/bin/acorn' -> '/home/vagrant/Code/inventory-system/node_modules/.bin/acorn'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/Code/inventory-system/npm-debug.log

**Comment by KenanY** [comment]
@joenmarz Is this Vagrant on top of Windows?

**Comment by joenmarz** [comment]
@KenanY I'm using Linux

**Comment by KenanY** [comment]
@joenmarz Are symlinks supported? Does using the [`--no-bin-links`](https://docs.npmjs.com/misc/config#bin-links) flag help at all?

**Comment by joenmarz** [comment]
It helps. Thanks @KenanY
over and out.

**Comment by Dmitrev** [comment]
Run `vagrant up` in an Administrator command prompt .

**Comment by Nezteb** [comment]
For future people who stumble upon this:

If you're on a Windows host using vagrant with a shared VM folder to a Linux box and using npm, the full command (as @KenanY suggested) is:

`npm install --no-bin-links`

**Comment by pdwjun** [comment]
If you are running a virtual mechine on Windows, this may help. 

As jehy said in https://github.com/npm/npm/issues/9901#issuecomment-281337751

**Comment by markoseigra** [comment]
@Dmitrev Admin execution fixed it. Cheers.

**Comment by ClaraLeigh** [comment]
I'd go one further than this comment https://github.com/npm/npm/issues/12733#issuecomment-261026906 for people using vagrant on windows...
Why not just use npm or yarn directly through windows instead of the vagrant box!
It'll probably run faster too ;)
