### ISSUE TITLE
Refusing to install mithril as a dependency of itself

### ISSUE THREAD

**Issue by vavdav** [npm/npm#12734]
Hello please I have problem with instalation mithriljs. Where is problem?

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'mithril' ]
2 info using npm@3.8.6
3 info using node@v6.1.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData mithril
8 silly fetchNamedPackageData mithril
9 silly mapToRegistry name mithril
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'mithril',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   name: 'mithril',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/mithril
14 verbose request uri https://registry.npmjs.org/mithril
15 verbose request no auth needed
16 info attempt registry request try #1 at 21:13:11
17 verbose request id cbb69923b01b719f
18 http request GET https://registry.npmjs.org/mithril
19 http 200 https://registry.npmjs.org/mithril
20 verbose headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
20 verbose headers   etag: '"B1AC323E4PP4H7THO0AJZBGQI"',
20 verbose headers   'content-type': 'application/json',
20 verbose headers   'content-encoding': 'gzip',
20 verbose headers   'cache-control': 'max-age=300',
20 verbose headers   'content-length': '4726',
20 verbose headers   'accept-ranges': 'bytes',
20 verbose headers   date: 'Tue, 17 May 2016 19:13:12 GMT',
20 verbose headers   via: '1.1 varnish',
20 verbose headers   age: '114',
20 verbose headers   connection: 'keep-alive',
20 verbose headers   'x-served-by': 'cache-fra1245-FRA',
20 verbose headers   'x-cache': 'HIT',
20 verbose headers   'x-cache-hits': '1',
20 verbose headers   'x-timer': 'S1463512392.052645,VS0,VE0',
20 verbose headers   vary: 'Accept-Encoding' }
21 silly get cb [ 200,
21 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
21 silly get     etag: '"B1AC323E4PP4H7THO0AJZBGQI"',
21 silly get     'content-type': 'application/json',
21 silly get     'content-encoding': 'gzip',
21 silly get     'cache-control': 'max-age=300',
21 silly get     'content-length': '4726',
21 silly get     'accept-ranges': 'bytes',
21 silly get     date: 'Tue, 17 May 2016 19:13:12 GMT',
21 silly get     via: '1.1 varnish',
21 silly get     age: '114',
21 silly get     connection: 'keep-alive',
21 silly get     'x-served-by': 'cache-fra1245-FRA',
21 silly get     'x-cache': 'HIT',
21 silly get     'x-cache-hits': '1',
21 silly get     'x-timer': 'S1463512392.052645,VS0,VE0',
21 silly get     vary: 'Accept-Encoding' } ]
22 verbose get saving mithril to /Users/xx/.npm/registry.npmjs.org/mithril/.cache.json
23 verbose correctMkdir /Users/xxx/.npm correctMkdir not in flight; initializing
24 verbose makeDirectory /Users/xxx/.npm creation not in flight; initializing
25 silly makeDirectory /Users/xxx/.npm uid: 501 gid: 20
26 silly install normalizeTree
27 silly loadCurrentTree Finishing
28 silly loadIdealTree Starting
29 silly install loadIdealTree
30 silly cloneCurrentTree Starting
31 silly install cloneCurrentTreeToIdealTree
32 silly cloneCurrentTree Finishing
33 silly loadShrinkwrap Starting
34 silly install loadShrinkwrap
35 silly loadShrinkwrap Finishing
36 silly loadAllDepsIntoIdealTree Starting
37 silly install loadAllDepsIntoIdealTree
38 silly rollbackFailedOptional Starting
39 silly rollbackFailedOptional Finishing
40 silly runTopLevelLifecycles Starting
41 silly runTopLevelLifecycles Finishing
42 silly install printInstalled
43 verbose stack Error: Refusing to install mithril as a dependency of itself
43 verbose stack     at checkSelf (/usr/local/lib/node_modules/npm/lib/install/validate-args.js:53:14)
43 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
43 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
43 verbose stack     at chain (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
43 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/validate-args.js:16:5
43 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
43 verbose stack     at Array.forEach (native)
43 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
43 verbose stack     at Array.forEach (native)
43 verbose stack     at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
44 verbose cwd /Users/xxx/Documents/projects/os/mithril
45 error Darwin 15.4.0
46 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "mithril"
47 error node v6.1.0
48 error npm  v3.8.6
49 error code ENOSELF
50 error Refusing to install mithril as a dependency of itself
51 error If you need help, you may report this error at:
51 error     <https://github.com/npm/npm/issues>
52 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@vavdav Try renaming this directory `/Users/davidvavrousek/Documents/projects/os/mithril` to something other than `mithril`. Also, ensure that the `"name"` property in your `package.json` is not set to `"mithril"`.

**Comment by vavdav** [comment]
thank you it is working :)

**Comment by sirjowee** [comment]
thanks Kennany, working now
