### ISSUE TITLE
Show "next" version of a package on npmjs.com

### ISSUE THREAD

**Issue by acidicX** [npm/npm#12730]
It currently only shows the "latest" release on the page. You have to go looking for it with `npm show <package` manually, if you want to find a beta/alpha release.

It would be great to have that info on the package page as well.
(sorry if this is not the right place for website improvements, but I didn't find a repo for the website)

**Comment by KenanY** [comment]
Here's the repo for the website: https://github.com/npm/newww :)

**Comment by acidicX** [comment]
Thx, I'll post it there.
P.S: Wow, the github repo search is really bad. Searching for 'website' won't bring it up even though it is in the repo description.
