### ISSUE TITLE
failed installing npm for SB Admin v2.0

### ISSUE THREAD

**Issue by akehat** [npm/npm#12735]
vagrant@homestead:~/homestead/sbadmin$ npm install
npm WARN package.json @ No repository field.
npm WARN package.json @ No license field.
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN optional dep failed, continuing fsevents@1.0.12
npm WARN optional dep failed, continuing fsevents@1.0.12
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm ERR! tar.unpack untar error /home/vagrant/.npm/babel-traverse/6.9.0/package.tgz
npm WARN optional dep failed, continuing fsevents@1.0.12
npm ERR! tar.unpack untar error /home/vagrant/.npm/babel-traverse/6.9.0/package.tgz
npm ERR! tar.unpack untar error /home/vagrant/.npm/source-map-support/0.2.10/package.tgz
npm ERR! tar.unpack untar error /home/vagrant/.npm/json5/0.4.0/package.tgz
npm ERR! tar.unpack untar error /home/vagrant/.npm/base64-arraybuffer/0.1.2/package.tgz
npm ERR! tar.unpack untar error /home/vagrant/.npm/lodash/4.12.0/package.tgz
npm ERR! tar.unpack untar error /home/vagrant/.npm/core-js/2.4.0/package.tgz
npm ERR! tar.unpack untar error /home/vagrant/.npm/es5-ext/0.10.11/package.tgz
npm WARN optional dep failed, continuing mime@1.3.4
npm WARN optional dep failed, continuing image-size@0.5.0
npm WARN optional dep failed, continuing errno@0.1.4
npm WARN optional dep failed, continuing mkdirp@0.5.1
npm ERR! tar.unpack untar error /home/vagrant/.npm/core-js/2.4.0/package.tgz
npm ERR! tar.unpack untar error /home/vagrant/.npm/core-js/2.4.0/package.tgz
npm ERR! tar.unpack untar error /home/vagrant/.npm/core-js/2.4.0/package.tgz
npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! path ../semver/bin/semver
npm ERR! code EPROTO
npm ERR! errno -71
npm ERR! syscall symlink

npm ERR! EPROTO: protocol error, symlink '../semver/bin/semver' -> '/home/vagrant/homestead/sbadmin/node_modules/gulp/node_modules/.bin/semver'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues
npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! path npm-debug.log.3423149e0bfca9070a818f65d40c15b4
npm ERR! code ETXTBSY
npm ERR! errno -26
npm ERR! syscall rename

npm ERR! ETXTBSY: text file is busy, rename 'npm-debug.log.3423149e0bfca9070a818f65d40c15b4' -> 'npm-debug.log'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/homestead/sbadmin/npm-debug.log

/home/vagrant/homestead/sbadmin/npm-debug.log does not exist

**Comment by KenanY** [comment]
@akehat Is this vagrant on top of Windows?

**Comment by akehat** [comment]
Yes
בתאריך 18 במאי 2016 01:02, "Kenan Yildirim" <notifications@github.com> כתב:

**Comment by KenanY** [comment]
@alexkwolfe Oh, then symlinks won't work here. Try using the [`--no-bin-links`](https://docs.npmjs.com/misc/config#bin-links) flag.

**Comment by akehat** [comment]
On Wed, May 18, 2016 at 6:23 AM, Kenan Yildirim <notifications@github.com>
wrote:

> --no-bin-links


​Tried.

Still didn't work

vagrant@homestead:~/homestead/public/sbadmin$ *npm install --no-bin-links*
npm WARN package.json @ No repository field.
npm WARN package.json @ No license field.
npm WARN unmet dependency
/home/vagrant/homestead/public/sbadmin/node_modules/laravel-elixir/node_modules/browserify
requires glob@'^4.0.5' but will load
npm WARN unmet dependency
/home/vagrant/homestead/public/sbadmin/node_modules/laravel-elixir/node_modules/glob,
npm WARN unmet dependency which is version 5.0.15
npm WARN unmet dependency
/home/vagrant/homestead/public/sbadmin/node_modules/laravel-elixir/node_modules/watchify
requires browserify@'^13.0.0' but will load
npm WARN unmet dependency
/home/vagrant/homestead/public/sbadmin/node_modules/laravel-elixir/node_modules/browserify,
npm WARN unmet dependency which is version 11.2.0
npm WARN unmet dependency
/home/vagrant/homestead/public/sbadmin/node_modules/laravel-elixir/node_modules/del/node_modules/rimraf
requires glob@'^7.0.0' but will load
npm WARN unmet dependency
/home/vagrant/homestead/public/sbadmin/node_modules/laravel-elixir/node_modules/glob,
npm WARN unmet dependency which is version 5.0.15
npm WARN unmet dependency
/home/vagrant/homestead/public/sbadmin/node_modules/laravel-elixir/node_modules/gulp-less/node_modules/accord
requires glob@'7.0.3' but will load
npm WARN unmet dependency
/home/vagrant/homestead/public/sbadmin/node_modules/laravel-elixir/node_modules/glob,
npm WARN unmet dependency which is version 5.0.15
npm WARN unmet dependency
/home/vagrant/homestead/public/sbadmin/node_modules/laravel-elixir/node_modules/gulp-load-plugins/node_modules/findup-sync
requires glob@'~4.3.0' but will load
npm WARN unmet dependency
/home/vagrant/homestead/public/sbadmin/node_modules/laravel-elixir/node_modules/glob,
npm WARN unmet dependency which is version 5.0.15
npm WARN unmet dependency
/home/vagrant/homestead/public/sbadmin/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/node-sass
requires glob@'^7.0.3' but will load
npm WARN unmet dependency
/home/vagrant/homestead/public/sbadmin/node_modules/laravel-elixir/node_modules/glob,
npm WARN unmet dependency which is version 5.0.15
npm WARN unmet dependency
/home/vagrant/homestead/public/sbadmin/node_modules/laravel-elixir/node_modules/gulp-watch/node_modules/vinyl-file
requires vinyl@'^1.1.0' but will load
npm WARN unmet dependency
/home/vagrant/homestead/public/sbadmin/node_modules/laravel-elixir/node_modules/gulp-watch/node_modules/vinyl,
npm WARN unmet dependency which is version 0.5.3
npm WARN unmet dependency
/home/vagrant/homestead/public/sbadmin/node_modules/gulp/node_modules/gulp-util/node_modules/dateformat/node_modules/meow
requires object-assign@'^4.0.1' but will load
npm WARN unmet dependency
/home/vagrant/homestead/public/sbadmin/node_modules/gulp/node_modules/gulp-util/node_modules/object-assign,
npm WARN unmet dependency which is version 3.0.0
npm WARN unmet dependency
/home/vagrant/homestead/public/sbadmin/node_modules/gulp/node_modules/vinyl-fs/node_modules/mkdirp
requires minimist@'0.0.8' but will load
npm WARN unmet dependency
/home/vagrant/homestead/public/sbadmin/node_modules/gulp/node_modules/minimist,
npm WARN unmet dependency which is version 1.2.0
​

​Thanks

​Avi

**Comment by KenanY** [comment]
@akehat Well, you are not receiving any errors anymore, so it looks like it worked to me. Now all you have are some warnings.

**Comment by akehat** [comment]
but what do I do with all those "unmet dependency"s?
