### ISSUE TITLE
MODULE_NOT_FOUND 'lodash._setcache'

### ISSUE THREAD

**Issue by razzildinho** [npm/npm#12745]
I'm having an issue when running most npm commands; install, update, cache etc. Getting a MODULE_NOT_FOUND error for 'lodash._setcache'.

node version 4.2.1, npm version 3.9.0

**debug.log**
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'update', '-g' ]
2 info using npm@3.9.0
3 info using node@v4.2.1
4 verbose stack Error: Cannot find module 'lodash._setcache'
4 verbose stack     at Function.Module._resolveFilename (module.js:337:15)
4 verbose stack     at Function.Module._load (module.js:287:25)
4 verbose stack     at Module.require (module.js:366:17)
4 verbose stack     at require (module.js:385:17)
4 verbose stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/lodash._baseuniq/index.js:9:16)
4 verbose stack     at Module._compile (module.js:435:26)
4 verbose stack     at Object.Module._extensions..js (module.js:442:10)
4 verbose stack     at Module.load (module.js:356:32)
4 verbose stack     at Function.Module._load (module.js:311:12)
4 verbose stack     at Module.require (module.js:366:17)
4 verbose stack     at require (module.js:385:17)
5 verbose cwd /home/ronan
6 error Linux 4.4.0-22-generic
7 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "update" "-g"
8 error node v4.2.1
9 error npm  v3.9.0
10 error code MODULE_NOT_FOUND
11 error Cannot find module 'lodash._setcache'
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]
```

**Comment by razzildinho** [comment]
Reinstall of nodejs and npm fixed the issue.

**Comment by con-ssc** [comment]
`Does not for me
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   '%USERPROFILE%\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'update',
1 verbose cli   '-g',
1 verbose cli   '-dd' ]
2 info using npm@3.8.9
3 info using node@v6.2.1
4 verbose stack Error: Cannot find module 'lodash._setcache'
4 verbose stack     at Function.Module._resolveFilename (module.js:440:15)
4 verbose stack     at Function.Module._load (module.js:388:25)
4 verbose stack     at Module.require (module.js:468:17)
4 verbose stack     at require (internal/module.js:20:19)
4 verbose stack     at Object.<anonymous> (%USERPROFILE%\AppData\Roaming\npm\node_modules\npm\node_modules\lodash._baseuniq\index.js:9:16)
4 verbose stack     at Module._compile (module.js:541:32)
4 verbose stack     at Object.Module._extensions..js (module.js:550:10)
4 verbose stack     at Module.load (module.js:458:32)
4 verbose stack     at tryModuleLoad (module.js:417:12)
4 verbose stack     at Function.Module._load (module.js:409:3)
5 verbose cwd D:\
6 error Windows_NT 10.0.10586
7 error argv "C:\\Program Files\\nodejs\\node.exe" "%USERPROFILE%\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "update" "-g" "-dd"
8 error node v6.2.1
9 error npm  v3.8.9
10 error code MODULE_NOT_FOUND
11 error Cannot find module 'lodash._setcache'
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]
`
