### ISSUE TITLE
Not able to install packages 

### ISSUE THREAD

**Issue by Suban118** [npm/npm#12746]
Not able to install packages through node.js command prompt. please find the attachment. 
Help me to start learn this react..

![error](https://cloud.githubusercontent.com/assets/19428387/15356677/d3263c3a-1d17-11e6-94dc-e440315f6097.png)

[npm-debug.zip](https://github.com/npm/npm/files/270301/npm-debug.zip)

**Comment by dawsonbotsford** [comment]
Please provide the following output for us to better understand the issue at hand:

1. npm --version
2. node --version
3. The command you entered which gave you this error.

**Comment by Suban118** [comment]
Hi ,

Npm – 2.15.1

Node -- v4.4.4-x86.msi  - Windows 32 bit installer

Thanks
Suban J

**Comment by dawsonbotsford** [comment]
Start by upgrading npm, that's a pretty old version. Let's see if that helps at all.

In addition, you didn't post the terminal command which caused this to fail (number three in my last post).
