### ISSUE TITLE
npm won't run start & other scripts

### ISSUE THREAD

**Issue by aramando** [npm/npm#12748]
I'm having lots of trouble with npm on a Windows machine at work. Sadly I'm not able to reinstall Windows and start afresh, however it is a clean install of node and npm (I uninstalled node and deleted npm and npm-cache from my AppData folder). I've tred this with Node 4.4.4 LTS (both with the bundled npm 2.1.5 and version 3.9.0) and also with Node 6.1.0 (with npm 3.9.0). 

The first indication that something was amiss was when attempting to `npm install node-sass` and other native packages requiring building; I got an `ENOENT` error but it was unclear which path was an issue. Then I realised I couldn't even `npm start` or `npm run-script foo`. Running the contents of the start script, i.e. `node index.js`, directly works just fine.

Here are the console output and npm debug log: https://gist.github.com/aramando

**Comment by devahome** [comment]
Same issue - but it happens only on some machines and not others.
