### ISSUE TITLE
variable not support

### ISSUE THREAD

**Issue by niwota865** [npm/npm#12743]
variable npm_package_name under the Windows 7 system does not support

**Comment by KenanY** [comment]
@niwota865 Hi! Could you please provide more information on the issue you are seeing? Please take some time to read the [contributing guidelines](https://github.com/npm/npm/wiki/Contributing-Guidelines).

**Comment by KenanY** [comment]
@niwota865 It has been almost three weeks now with no response from you. Without at least a
`npm-debug.log` it is virtually impossible for me to help you. Are you still seeing this issue?

**Comment by KenanY** [comment]
Closing as abandoned. No log provided; very difficult to provide any support here :(
