### ISSUE TITLE
Npm throwing error while installing protractor

### ISSUE THREAD

**Issue by SomeshKumarN** [npm/npm#12742]
I have tried the way mentioned in the below link to install protractor into my machine but i got the below error.

Referred link:
http://www.jomendez.com/2015/02/03/installing-protractor-npm-windows-environment-behind-proxy/

error message in screen shot attached.
![protractor istalling issue](https://cloud.githubusercontent.com/assets/18733133/15348822/4b890784-1ceb-11e6-9418-76a2d7450eda.jpg)

[npm-debug.log.txt](https://github.com/npm/npm/files/269722/npm-debug.log.txt)

**Comment by lxe** [comment]
You can always try [`--strict-ssl=false`](https://docs.npmjs.com/misc/config#strict-ssl)

**Comment by SomeshKumarN** [comment]
![protractor istalling issue1](https://cloud.githubusercontent.com/assets/18733133/15460617/77672c9e-20d0-11e6-90e4-402fa822e9ff.jpg)

@lxe  i have tried your suggestion but still i am getting the above issue. do we have any other way around for this?

Note: i have given the comment in the below way in command prompt.
>npm install -g protractor --strict-ssl=false
