### ISSUE TITLE
version not found: ionic-sdk@1.3.1

### ISSUE THREAD

**Issue by lamphattai100590** [npm/npm#12752]
meteor npm install ionic-scripts       
npm WARN deprecated ionic-scripts@1.3.1: Wrong dependency
npm WARN peerDependencies The peer dependency angular@^1.5.3 included from ionic-scripts will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency angular-animate@^1.5.3 included from ionic-scripts will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency angular-sanitize@^1.5.3 included from ionic-scripts will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency angular-ui-router@^0.2.13 included from ionic-scripts will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm ERR! Darwin 15.5.0
npm ERR! argv "node" "/Users/lamphattai/.meteor/packages/meteor-tool/.1.3.2_4.lbyo5v++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm" "install" "ionic-scripts"
npm ERR! node v0.10.43
npm ERR! npm  v2.14.22

npm ERR! version not found: ionic-sdk@1.3.1

**Comment by minatogawa** [comment]
I'm facing the same situation.

**Comment by GLinBoy** [comment]
I'm too; :-(

**Comment by xakin** [comment]
same here

**Comment by jesusEntelgy** [comment]
I have the same problem!
I tried to install ionic from http://ionicframework.com with _npm install -g cordova ionic_ but is not possible....
Please give an answer

**Comment by azastrael** [comment]
Hello !

The problem comes from the "ionic-scripts" package which requires a wrong version of "ionic-sdk" ( or at least which has not been released on npm ).

As the author of "ionic-scripts" said [here](https://github.com/DAB0mB/meteor-npm-ionic/issues/2), v1.3.1 is deprecated and you should install v1.2.4 ( by doing `meteor npm install ionic-scripts@1.2.4` ).

**Comment by TonGarcia** [comment]
@azastrael I got the same:

Iltons-MacBook-Pro:whatsapp iltonsilveira$ meteor npm install ionic-scripts@1.2.4
npm ERR! Darwin 15.4.0
npm ERR! argv "node" "/Users/iltonsilveira/.meteor/packages/meteor-tool/.1.3.2_4.lbyo5v++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm" "install" "ionic-scripts@1.2.4"
npm ERR! node v0.10.43
npm ERR! npm  v2.14.22

npm ERR! version not found: ionic-scripts@1.2.4
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/iltonsilveira/Projetos/mobile/cordova/meteor/learning/whatsapp/npm-debug.log

**Comment by windmaple** [comment]
Same here. 'meteor npm install ionic-scripts@1.2.4' led to the same error as TonGarcia had.

**Comment by jesusEntelgy** [comment]
SOLUTION: meteor npm install ionic-scripts@0.0.1 --save
look at the package.json https://github.com/DAB0mB/angular-meteor-whatsapp/blob/master/package.json

**Comment by albe-rosado** [comment]
That's right , Jesus solved the problem !!!

**Comment by fangj99** [comment]
thanks, solved by using jesusEntelgy's resolution  meteor npm install ionic-scripts@0.0.1 --save

**Comment by lamphattai100590** [comment]
Thank you very much, it's solved
