### ISSUE TITLE
Q: How can we enforce exact versions?

### ISSUE THREAD

**Issue by colllin** [npm/npm#12753]
# Update: @ba55ie has [the solution](https://github.com/npm/npm/issues/12753#issuecomment-302350897)

Original question
---

The situation: We are writing a node application.  Nothing will ever use it as a "package", but we have a package.json file for managing dependencies.  It doesn't make sense for 2 developers to run the application with different package versions, i.e. it doesn't make sense for us to ever specify a range of package versions that are acceptable – everyone should be using the same versions everywhere.  

It seems like shrinkwrap is intended to solve this.  We've tried shrinkwrap... but we've had a terrible experience with it.  It doesn't work great across npm versions, and there's no way to enforce an npm version in development, so we end up re-shrinkwrapping in a postinstall script because otherwise shrinkwrap doesn't update correctly.  Also, it makes a mess of our git diffs.  Also, our production deploys broke last night because it seemed like there was a bug in npm 3.9.0 when using a shrinkwrap.  When we removed the shrinkwrap, some of our packages were unintentially updated in production, which had a similar minor-version breaking-change, which is when we decided to switch from `^` to `~` on our dependencies.

This isn't a perfect solution.  The package developers intended to support semver but accidentally published breaking changes.  This could happen on a patch update just as easily as it did on a minor update.  So at this point it seems like our best solution is to `--save-exact`, but this is unreliable since it relies on developer training and memory.

Do you think we could make a case for a more defensive version of `--save-exact`, which would require exact versions across your package?  e.g. a `installExact: true` flag in package.json, such that `npm install` would only ever save exact versions, and would throw an error if package.json specifies an inexact version.

For this scenario where it doesn't make sense for developers to use this application with different versions of its required packages, this would give us a way to specify & enforce that behavior.  Also consider that if it were advisable to commit node_modules (I'm told that it's not), that would make sense for us since this isn't even really a "package", we're just using a package.json to manage dependencies.

What solution do you recommend?

**Comment by colllin** [comment]
I found an npm config for this exact purpose:

https://docs.npmjs.com/misc/config#save-exact

And tried setting it using...

```
  "config": {
    "save-exact": true
  },
```

But it doesn't seem to be obeyed that way.  Why not?

Instead, I found a temporary workaround: force developers to set their npm config to `save-exact=true` in a `preinstall` script:

```
    "preinstall": "npm config set save-exact=true",
```

Bad news: Only runs on plain `npm install`, not on `npm install xyz`.  Good news: You only need to run it once per project.  So if you add this script at the same time as you add a new dependency, then all of your developers will get this flag next time they `git pull` & `npm install`.

**Comment by busches** [comment]
Similar to `shrinkwrap` you can remove the `~` and `^` and that will install the exact version. You can force this by running `npm config set save-prefix ""`. If you go more into the issues you faced with `shrinkwrap` then there may be something to fix, otherwise this issue comes down to developer awareness as you mentioned.

**Comment by ba55ie** [comment]
1. Add an [`.npmrc` file](https://docs.npmjs.com/files/npmrc) to your project.
1. Add [`save-exact=true`](https://docs.npmjs.com/misc/config#save-exact) to that file.
1. Remove the `^` or `~` from your `package.json`. Newly installed packages will be saved without a prefix.
