### ISSUE TITLE
Cannot install packages error: EINVALIDTYPE

### ISSUE THREAD

**Issue by anikahhh** [npm/npm#12751]
I'm using node v5.0.0 and npm 3.3.6 on mac an I'm having problems installing packages. Every package I tried gives me the same error, the latest was node-postures, saying it's a problem with wpm itself. Any help appreciated.

[npm-debug.txt](https://github.com/npm/npm/files/270969/npm-debug.txt)

npm ERR! code EINVALIDTYPE

npm ERR! typeerror Error: Argument #1: Expected string but got object
npm ERR! typeerror     at markDeps (/usr/local/lib/node_modules/npm/lib/install/deps.js:87:5)
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
npm ERR! typeerror     at Array.forEach (native)
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
npm ERR! typeerror     at Array.forEach (native)
npm ERR! typeerror     at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
npm ERR! typeerror     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
npm ERR! typeerror     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
npm ERR! typeerror     at chain (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
npm ERR! typeerror     at recalculateMetadata (/usr/local/lib/node_modules/npm/lib/install/deps.js:112:3)
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     http://github.com/npm/npm/issues

**Comment by somecallmejosh** [comment]
I'm having the same issue.

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'install' ]
2 info using npm@3.3.6
3 info using node@v5.0.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly install normalizeTree
8 verbose stack Error: Argument #1: Expected string but got object
8 verbose stack     at markDeps (/usr/local/lib/node_modules/npm/lib/install/deps.js:87:5)
8 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
8 verbose stack     at Array.forEach (native)
8 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
8 verbose stack     at Array.forEach (native)
8 verbose stack     at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
8 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
8 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
8 verbose stack     at chain (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
8 verbose stack     at recalculateMetadata (/usr/local/lib/node_modules/npm/lib/install/deps.js:112:3)
9 verbose cwd /Users/jbriley/Documents/atk
10 error Darwin 15.5.0
11 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
12 error node v5.0.0
13 error npm  v3.3.6
14 error code EINVALIDTYPE
15 error typeerror Error: Argument #1: Expected string but got object
15 error typeerror     at markDeps (/usr/local/lib/node_modules/npm/lib/install/deps.js:87:5)
15 error typeerror     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
15 error typeerror     at Array.forEach (native)
15 error typeerror     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
15 error typeerror     at Array.forEach (native)
15 error typeerror     at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
15 error typeerror     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
15 error typeerror     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
15 error typeerror     at chain (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
15 error typeerror     at recalculateMetadata (/usr/local/lib/node_modules/npm/lib/install/deps.js:112:3)
15 error typeerror This is an error with npm itself. Please report this error at:
15 error typeerror     <http://github.com/npm/npm/issues>
16 verbose exit [ 1, true ]
```

**Comment by anikahhh** [comment]
I ended up uninstalling npm and node and re-installing. Now I'm using node v4.4.4. Not sure if the different version fixed it or if a new install of any version would.

**Comment by somecallmejosh** [comment]
That seemed to work for me, temporarily. But, I'm running into the same issue again.
