### ISSUE TITLE
Unable to publish package

### ISSUE THREAD

**Issue by samjbmason** [npm/npm#12767]
I have been added as a contributor to a package `lmn-monkey`, I have been making some change and when i went to `npm publish`, I was shown a 403 `you do not have permission to publish "lmn-monkey".` message in my console.

I can confirm I am logged in as the user that was granted access and I have gone so far as logging in again, restarting but still no joy.

**Comment by dawsonbotsford** [comment]
Can you provide a screenshot showing that you are indeed a contributor? In addition, provide us the output for the command: `npm whoami`

Cheers

**Comment by samjbmason** [comment]
![screen shot 2016-05-20 at 15 21 39](https://cloud.githubusercontent.com/assets/878503/15430769/a5f5b7bc-1e9e-11e6-932b-ad8233e102b0.png)

Output from `npm whoami`: `samjbmason`

**Comment by dawsonbotsford** [comment]
Not sure where to go from here. Let's wait on some of the npm devs perhaps. This could be an internal issue anyone that is unfixable without having access to the closed-source parts of npm.
