### ISSUE TITLE
missing script: dev

### ISSUE THREAD

**Issue by CarsonYang** [npm/npm#12763]
help!

When i run webpack with reactjs,there goes this problem.
I did the steps as https://fakefish.github.io/react-webpack-cookbook/Configuring-react-js.html,but at the last step(Run 'npm run dev') ,it went wrong.

Here is npm-debug.log:

error Windows_NT 6.1.7601
error argv "\\nodejs\\node.exe" "\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
error node v6.2.0
error npm  v3.8.9
error missing script: dev
error If you need help, you may report this error at:
error     <https://github.com/npm/npm/issues>
verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@CarsonYang Do you have a `"dev"` script defined in your `package.json`? Looks like it is explained [here](https://fakefish.github.io/react-webpack-cookbook/Running-a-workflow.html).

**Comment by CarsonYang** [comment]
@KenanY thanks for your reply! I have solved it ! This is my first try to making an issue in github,so it makes me exciting! : D
