### ISSUE TITLE
Failed installation of React package in Atom Editor

### ISSUE THREAD

**Issue by billt431** [npm/npm#12771]
I received the below error message when trying to install the React Package to Atom:

Installing “react@0.15.0” failed.Hide output…

npm ERR! git clone C:\Users\Matt10-8 Media.atom.apm_git-remotes\https-github-com-millermedeiros-rocambole-git-fa28ae6f C:\Users\MATT10~1\AppData\Local\Temp\npm-9284-46111a7e\git-cache-d3f976cd063b\1bd5044df1d6c888a1bd1b511158fb34b011e9aa: Cloning into 'C:\Users\MATT10~1\AppData\Local\Temp\npm-9284-46111a7e\git-cache-d3f976cd063b\1bd5044df1d6c888a1bd1b511158fb34b011e9aa'...
npm ERR! git clone C:\Users\Matt10-8 Media.atom.apm_git-remotes\https-github-com-millermedeiros-rocambole-git-fa28ae6f C:\Users\MATT10~1\AppData\Local\Temp\npm-9284-46111a7e\git-cache-d3f976cd063b\1bd5044df1d6c888a1bd1b511158fb34b011e9aa: error: cannot spawn sh: No such file or directory
npm ERR! git clone C:\Users\Matt10-8 Media.atom.apm_git-remotes\https-github-com-millermedeiros-rocambole-git-fa28ae6f C:\Users\MATT10~1\AppData\Local\Temp\npm-9284-46111a7e\git-cache-d3f976cd063b\1bd5044df1d6c888a1bd1b511158fb34b011e9aa: fatal: unable to fork
npm ERR! git clone C:\Users\Matt10-8 Media.atom.apm_git-remotes\https-github-com-millermedeiros-rocambole-git-fa28ae6f C:\Users\MATT10~1\AppData\Local\Temp\npm-9284-46111a7e\git-cache-d3f976cd063b\1bd5044df1d6c888a1bd1b511158fb34b011e9aa: 
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\Users\Matt10-8 Media\AppData\Local\atom\app-1.7.3\resources\app\apm\bin\node.exe" "C:\Users\Matt10-8 Media\AppData\Local\atom\app-1.7.3\resources\app\apm\node_modules\npm\bin\npm-cli.js" "--globalconfig" "C:\Users\Matt10-8 Media\.atom\.apm\.apmrc" "--userconfig" "C:\Users\Matt10-8 Media\.atom\.apmrc" "install" "C:\Users\MATT10~1\AppData\Local\Temp\d-116419-11044-1ph1qq4\package.tgz" "--target=0.36.8" "--arch=ia32" "--msvs_version=2013"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code 128

npm ERR! Command failed: Cloning into 'C:\Users\MATT10~1\AppData\Local\Temp\npm-9284-46111a7e\git-cache-d3f976cd063b\1bd5044df1d6c888a1bd1b511158fb34b011e9aa'...
npm ERR! error: cannot spawn sh: No such file or directory
npm ERR! fatal: unable to fork
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

Any guidance would be appreciated.

**Comment by auscompgeek** [comment]
Looks like your Git installation is broken.

> ```
npm ERR! git clone [...]: error: cannot spawn sh: No such file or directory
```

**Comment by billt431** [comment]
David,

Thank you for your response.  I uninstalled all things Git and reinstalled them, but  I still get the same error message.  I’m running Windows 10 on a Lenova laptop.  Also, I followed the instructions step by step that the instructor gave for an online course that I’m taking through Udemy.  I appreciate any help.

Regards,

Bill
