### ISSUE TITLE
Add hint to use "npm help <command>" to text displayed by "npm <command> --help"

### ISSUE THREAD

**Issue by thomasboyt** [npm/npm#12787]
This morning, while I trying to figure out how to use `npm shrinkwrap`, I used the technique that I usually use to discover how to use a command - running `<command> --help` - and was greeted with this less-than-useful message:

![screen shot 2016-05-20 at 10 28 54 am](https://cloud.githubusercontent.com/assets/579628/15433383/23702444-1e80-11e6-8013-896f3214dce4.png)

This is because NPM's `--help` shows the usage synopsis of the usage of a command, rather than the longer man page for it. `shrinkwrap` doesn't have much of a usage synopsis right now (that's tracked in a separate issue), but even once it does, it still won't include a longer usage description. For example, the synopsis for `npm cache` is just:

```
$ npm cache --help
npm cache add <tarball file>
npm cache add <folder>
npm cache add <tarball url>
npm cache add <git url>
npm cache add <name>@<version>
npm cache ls [<path>]
npm cache clean [<pkg>[@<version>]]
```

This is all fine _if_ you know that `npm help <command>` exists, which I did not. I thought this was the only documentation available for these commands, and was super disheartened by how limited it was!

A little while later I did discover `npm help` (though by then I'd just googled for more information on shrinkwrap). It would have been nice if the short-form usage message had included a hint that pointed me at the longer help text. For example:

![screen shot 2016-05-20 at 11 03 50 am](https://cloud.githubusercontent.com/assets/579628/15433521/b0df8932-1e80-11e6-84ab-56f200b683a6.png)

I went ahead and implemented this as https://github.com/thomasboyt/npm/commit/f66996909670d6d22f2e036ba5fa7bba2d727cb8 but wanted to see if there was interest in this UX change before I submitted it as a PR, and whether there were any subtle repercussions of this change that I should be aware of.

(cc @ashleygwilliams since we were talking about this on twitter)

**Comment by RichardLitt** [comment]
I would definitely be interested in this; I ran into the same problem today. Thanks for PRing this already, @thomasboyt.

**Comment by RichardLitt** [comment]
I would like this to be opened again. I think this is still a valid issue.
