### ISSUE TITLE
npm markAsFailed recursion results in "Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by vtravieso** [npm/npm#12781]
Invoking an npm command on the 'cli-color' package results in a "Maximum call stack size exceeded". 

Node: v4.4.4
npm: v3.9.2

Steps to reproduce:
1. npm install -g cli-color
2. change directory to where cli-color is installed
3. npm uninstall foo

Result: Npm throws the error "Maximum call stack size exceeded"

The error seems to be caused by the cli-color package having circular dependencies, which causes an infinite recursion in the npm code that marks a package and its reqs as failed (node_modules\npm\lib\install\actions.js:54:16) - see attached log file.

Skipping the recursion when the req has already been flagged avoids the error.

[npm-debug.zip](https://github.com/npm/npm/files/274612/npm-debug.zip)

**Comment by jblotus** [comment]
+1

I had similar issue - disabling progress actually allowed my install to complete
`npm set progress=false && rm -rf ~/.npm && rm -rf node_modules && npm install`

https://github.com/npm/npm/issues/11283
