### ISSUE TITLE
$ sudo npm install npm # results in "ERR! Darwin 15.4.0"

### ISSUE THREAD

**Issue by krisrandall** [npm/npm#12793]
I get the following output when trying to run "npm install" :

$ sudo npm install
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/Cellar/node/6.2.0/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9

npm ERR! No compatible version found: rethinkdb@1.10.*
npm ERR! Valid install targets:
npm ERR! 2.3.1, 2.3.0, 2.2.3, 2.2.2, 2.2.1, 2.2.0, 2.1.1, 2.1.0, 2.0.2, 2.0.0, 2.0.0-2, 2.0.0-1, 1.16.2, 1.16.1, 1.16.0, 1.15.0, 1.15.0-0, 1.14.0-0, 1.13.0-3, 1.13.0-2, 1.13.0-1, 1.13.0-0, 1.12.0-1, 1.12.0-0, 1.11.0-4, 1.11.0-3, 1.11.0-2, 1.11.0-1, 1.11.0-0, 1.10.0-0, 1.9.0-1, 1.9.0-0, 1.8.0-0, 1.7.0-2, 1.7.0-1, 1.6.0-0, 1.5.0-0, 1.4.0-3, 1.4.0-2, 1.4.0-1, 1.4.0-0, 1.2.6-1, 1.2.6-0, 1.2.5-0, 1.2.0-0
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /path
[npm-debug.log.txt](https://github.com/npm/npm/files/275829/npm-debug.log.txt)

/npm-debug.log

**Comment by KenanY** [comment]
@krisrandall Looks like you have a dependency on a range of `rethinkdb` versions which does not actually encompass any existing version of the module. Hence, the error you are receiving. I would suggest changing that version range in your `"dependencies"` or `"devDependencies"`.

**Comment by KenanY** [comment]
@krisrandall Hi, it has been over a week now with no response from you. Are you still seeing this issue?

**Comment by theartsnetwork** [comment]
I am facing the same issue when I am trying 
npm -g install npm@latest
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "-g" "install" "npm@latest"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! path /usr/local/lib/node_modules/npm/.mailmap
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall unlink

npm ERR! Error: EACCES: permission denied, unlink '/usr/local/lib/node_modules/npm/.mailmap'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, unlink '/usr/local/lib/node_modules/npm/.mailmap']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'unlink',
npm ERR!   path: '/usr/local/lib/node_modules/npm/.mailmap' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
npm ERR! error rolling back Error: EACCES: permission denied, unlink '/usr/local/lib/node_modules/npm/.mailmap'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  { [Error: EACCES: permission denied, unlink '/usr/local/lib/node_modules/npm/.mailmap']
npm ERR! error rolling back   errno: -13,
npm ERR! error rolling back   code: 'EACCES',
npm ERR! error rolling back   syscall: 'unlink',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/npm/.mailmap' }

npm ERR! Please include the following file with any support request:
FFA npmdebug.log for reference 
[npm-debug.log.zip](https://github.com/npm/npm/files/306488/npm-debug.log.zip)

**Comment by KenanY** [comment]
Closing as abandoned :(
