### ISSUE TITLE
must have a URL that starts with http: or https: when trying to install @angular/common

### ISSUE THREAD

**Issue by petricsasa** [npm/npm#12795]
I've got an error "must have a URL that starts with http: or https: " when I tired to install package @angular/common or any other angular 2 RC package. There is a npm log in attachment

[npm-debug.txt](https://github.com/npm/npm/files/276038/npm-debug.txt)

**Comment by xe4me** [comment]
1+

**Comment by xe4me** [comment]
I'm having the same issue

**Comment by hommaam** [comment]
Check `.npmrc` file may exist in `/Users/Yourname/.npmrc`.

There must be not `registry=htp://registry.npmjs.org/` but `registry=http://registry.npmjs.org/`.
