### ISSUE TITLE
Getting error when installing htmling-demo-app

### ISSUE THREAD

**Issue by cw6834** [npm/npm#12809]
getting the following error: 

c:\inetpub\htmling-demo-app>npm install htmling-demo-app
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "htmling-demo-app"
npm ERR! node v5.10.0
npm ERR! npm  v3.8.3
npm ERR! code ENOSELF

npm ERR! Refusing to install htmling-demo-app as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     c:\inetpub\htmling-demo-app\npm-debug.log

c:\inetpub\htmling-demo-app>

can someone help me with this?

Thanks

**Comment by KenanY** [comment]
@cw6834 Hello! Sorry for the late response. Can you please try renaming `c:\inetpub\htmling-demo-app` to something else and ensuring that the `"name"` attribute of your `package.json` is not set to `"htmling-demo-app"`?

**Comment by KenanY** [comment]
Closing as abandoned.
