### ISSUE TITLE
Problem with npm saving dependency

### ISSUE THREAD

**Issue by scorpioRED** [npm/npm#12800]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'i',
1 verbose cli   '-S',
1 verbose cli   'posthtml' ]
2 info using npm@3.8.9
3 info using node@v6.2.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData posthtml
8 silly fetchNamedPackageData posthtml
9 silly mapToRegistry name posthtml
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'posthtml',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   name: 'posthtml',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/posthtml
14 verbose request uri https://registry.npmjs.org/posthtml
15 verbose request no auth needed
16 info attempt registry request try #1 at 10:46:45
17 verbose request id 40473a18c0a0d4ce
18 verbose etag "90ROYJKTW3EXQ4VM4FPQ8LUPI"
19 http request GET https://registry.npmjs.org/posthtml
20 http 304 https://registry.npmjs.org/posthtml
21 verbose headers { date: 'Mon, 23 May 2016 07:46:40 GMT',
21 verbose headers   via: '1.1 varnish',
21 verbose headers   'cache-control': 'max-age=300',
21 verbose headers   etag: '"90ROYJKTW3EXQ4VM4FPQ8LUPI"',
21 verbose headers   age: '0',
21 verbose headers   connection: 'keep-alive',
21 verbose headers   'x-served-by': 'cache-fra1235-FRA',
21 verbose headers   'x-cache': 'MISS',
21 verbose headers   'x-cache-hits': '0',
21 verbose headers   'x-timer': 'S1463989600.948670,VS0,VE376',
21 verbose headers   vary: 'Accept-Encoding' }
22 silly get cb [ 304,
22 silly get   { date: 'Mon, 23 May 2016 07:46:40 GMT',
22 silly get     via: '1.1 varnish',
22 silly get     'cache-control': 'max-age=300',
22 silly get     etag: '"90ROYJKTW3EXQ4VM4FPQ8LUPI"',
22 silly get     age: '0',
22 silly get     connection: 'keep-alive',
22 silly get     'x-served-by': 'cache-fra1235-FRA',
22 silly get     'x-cache': 'MISS',
22 silly get     'x-cache-hits': '0',
22 silly get     'x-timer': 'S1463989600.948670,VS0,VE376',
22 silly get     vary: 'Accept-Encoding' } ]
23 verbose etag https://registry.npmjs.org/posthtml from cache
24 verbose get saving posthtml to /Users/scorpio/.npm/registry.npmjs.org/posthtml/.cache.json
25 verbose correctMkdir /Users/scorpio/.npm correctMkdir not in flight; initializing
26 silly install normalizeTree
27 silly loadCurrentTree Finishing
28 silly loadIdealTree Starting
29 silly install loadIdealTree
30 silly cloneCurrentTree Starting
31 silly install cloneCurrentTreeToIdealTree
32 silly cloneCurrentTree Finishing
33 silly loadShrinkwrap Starting
34 silly install loadShrinkwrap
35 silly loadShrinkwrap Finishing
36 silly loadAllDepsIntoIdealTree Starting
37 silly install loadAllDepsIntoIdealTree
38 silly rollbackFailedOptional Starting
39 silly rollbackFailedOptional Finishing
40 silly runTopLevelLifecycles Starting
41 silly runTopLevelLifecycles Finishing
42 silly install printInstalled
43 verbose stack Error: Refusing to install posthtml as a dependency of itself
43 verbose stack     at checkSelf (/usr/local/lib/node_modules/npm/lib/install/validate-args.js:53:14)
43 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
43 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
43 verbose stack     at chain (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
43 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/validate-args.js:16:5
43 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
43 verbose stack     at Array.forEach (native)
43 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
43 verbose stack     at Array.forEach (native)
43 verbose stack     at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
44 verbose cwd /Users/scorpio/Documents/git/kottans-js-2016/week_01/posthtml
45 error Darwin 15.4.0
46 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "-S" "posthtml"
47 error node v6.2.0
48 error npm  v3.8.9
49 error code ENOSELF
50 error Refusing to install posthtml as a dependency of itself
51 error If you need help, you may report this error at:
51 error     <https://github.com/npm/npm/issues>
52 verbose exit [ 1, true ]

[npm-debug.txt](https://github.com/npm/npm/files/277027/npm-debug.txt)

**Comment by KenanY** [comment]
@scorpioRED Is the `"name"` attribute of your `package.json` set to `"posthtml"`? Does changing the name of directory `/Users/scorpio/Documents/git/kottans-js-2016/week_01/posthtml` help at all?

**Comment by scorpioRED** [comment]
Yes, know it, I just forget to close it issue.
But thanks for your comment
