### ISSUE TITLE
NPM working on CMD but not on PowerShell

### ISSUE THREAD

**Issue by pushpsmarty** [npm/npm#12808]
I have installed Node 4.4.4 and when i try to run NPM from PowerShell i get below error:

PS C:\Users\pushpkum> npm -v
Program 'npm.cmd' failed to run: The system cannot find the file specifiedAt line:1 char:1
- npm -v
- ~~~~~~.
  At line:1 char:1
- npm -v
- ~~~~~~
  - CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
  - FullyQualifiedErrorId : NativeCommandFailed

PS C:\Users\pushpkum>

When i try the same with CMD below is output:

C:\Users\pushpkum>npm -v
'CALL "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules
\npm\bin\npm-cli.js" prefix -g' is not recognized as an internal or external com
mand,
operable program or batch file.
2.15.1

**Comment by busches** [comment]
It looks like your `.npmrc` configuration may have been corrupted. Can you paste the contents of the file, if you're still getting the error?
