### ISSUE TITLE
mongodb-runner install fails on ubuntu 14

### ISSUE THREAD

**Issue by costamirkin** [npm/npm#12803]
costa@costaparse:/root$ sudo npm install -g  mongodb-runner
npm http GET https://registry.npmjs.org/mongodb-runner
npm http 304 https://registry.npmjs.org/mongodb-runner
npm WARN engine mongodb-runner@3.3.2: wanted: {"node":">=4.0.0"} (current: {"node":"v0.10.25","npm":"1.3.10"})
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/clui
*
*
*
npm http 304 https://registry.npmjs.org/mongodb
npm ERR! Error: No compatible version found: mongodb-tools@'mongodb-js/mongodb-tools'
npm ERR! Valid install targets:
npm ERR! ["1.0.0","1.0.1","1.0.2","1.0.3","1.0.4","1.0.5","1.0.6"]
npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:719:10)
npm ERR!     at /usr/share/npm/lib/cache.js:638:10
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-85-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "mongodb-runner"
npm ERR! cwd /root
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /root/npm-debug.log
npm ERR! not ok code 0

**Comment by KenanY** [comment]
@costamirkin `npm@1.3` is no longer supported.Try [updating](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm).

**Comment by KenanY** [comment]
@costamirkin Hi, it has been over a week now with no response from you. Are you still seeing this issue after updating `npm`?

**Comment by KenanY** [comment]
Closing as abandoned.
