### ISSUE TITLE
cannot npm install (npm v2.15.1/nodejs v4.4.4)

### ISSUE THREAD

**Issue by aopal** [npm/npm#12819]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'jasmine' ]
2 info using npm@2.15.1
3 info using node@v4.4.4
4 verbose stack Error: Cannot find module 'has-unicode'
4 verbose stack     at Function.Module._resolveFilename (module.js:325:15)
4 verbose stack     at Function.Module._load (module.js:276:25)
4 verbose stack     at Module.require (module.js:353:17)
4 verbose stack     at require (internal/module.js:12:17)
4 verbose stack     at Object.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-install-checks\node_modules\npmlog\node_modules\gauge\progress-bar.js:2:18)
4 verbose stack     at Module._compile (module.js:409:26)
4 verbose stack     at Object.Module._extensions..js (module.js:416:10)
4 verbose stack     at Module.load (module.js:343:32)
4 verbose stack     at Function.Module._load (module.js:300:12)
4 verbose stack     at Module.require (module.js:353:17)
4 verbose stack     at require (internal/module.js:12:17)
5 verbose cwd C:\Users\aopal
6 error Windows_NT 6.3.9600
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "jasmine"
8 error node v4.4.4
9 error npm  v2.15.1
10 error code MODULE_NOT_FOUND
11 error Cannot find module 'has-unicode'
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]

**Comment by watilde** [comment]
Probably this issue duplicate with https://github.com/npm/npm/issues/12692

**Comment by KenanY** [comment]
@aopal Is this still an issue for you with `npm@^3.6.0`?

**Comment by KenanY** [comment]
Closing as abandoned.
