### ISSUE TITLE
why can not fetch versions for scoped packages which are public

### ISSUE THREAD

**Issue by dead-horse** [npm/npm#12812]
it break  [pnpm](https://github.com/rstacruz/pnpm) and [npminstall](https://github.com/cnpm/npminstall)

```
$ curl -I https://registry.npmjs.com/@bigfunger%2Fdecompress-zip/0.2.0-stripfix2

HTTP/1.1 401 Unauthorized
npm-notice: ERROR: you cannot fetch versions for scoped packages
Cache-Control: max-age=0
Transfer-Encoding: chunked
Accept-Ranges: bytes
Date: Tue, 24 May 2016 03:05:26 GMT
Via: 1.1 varnish
Connection: keep-alive
X-Served-By: cache-nrt6123-NRT
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1464059126.382787,VS0,VE484
```

**Comment by dead-horse** [comment]
Hi, this issue is still there and unsolved.

**Comment by iarna** [comment]
This is not an issue with the npm cli, so I'm going to close this issue. The correct venue for registry issues is: https://github.com/npm/registry

That is in the [documented endpoints](https://github.com/npm/registry/blob/master/docs/REGISTRY-API.md#package-endpoints) so I'd expect it to work too, although npm itself does not make use of it, obviously. (There are some other issues with it currently, like it doesn't resolve version ranges exactly the same as the cli. If you were to ask my advice, I'd encourage pnpm and npminstall to switch over to the unversioned package endpoint ([with filtered data](https://github.com/npm/registry/blob/master/docs/responses/package-metadata.md).)
