### ISSUE TITLE
fetch failed with status code 404

### ISSUE THREAD

**Issue by TonyScript** [npm/npm#12829]
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1

npm ERR! fetch failed with status code 404
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by watilde** [comment]
Hi Tony,
It seems registry return 404. Let me ask you 2 things to resolve this:
+ Did you have a proxy in the back?
+ Can you share us the log file called `npm-debug.log` on this issue if it exists?

**Comment by KenanY** [comment]
@TonyScript Are you still facing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
