### ISSUE TITLE
 npm install fails on babun

### ISSUE THREAD

**Issue by rasenplanscher** [npm/npm#12821]
I'm on Windows 7 pro, using nodist. When I run an `npm install` in `git-bash` or `cmd`, it works. When I do the same, I get permission errors en masse. As I read the [log (npm-debug.log)](https://gist.github.com/rasenplanscher/9527b98859d2fa2c8f0748bc1aaf7b7a), it's supposedly an issue executing a `git clone`; however, when I run it directly, it works without a hitch. I really have no idea what to look at right now. Any pointers would be much appreciated.

**Comment by ericprieto** [comment]
For some reason, babun's sandboxed git can't download git repos when used through npm. To solve this, you can uninstall babun's git with `pact remove git` and use the Git for Windows that you already have installed.
