### ISSUE TITLE
getting issue while doing npm install chimp.

### ISSUE THREAD

**Issue by anirbanmishra** [npm/npm#12827]
Have attached the error log...can someone help me??
[Issue.txt](https://github.com/npm/npm/files/280595/Issue.txt)

**Comment by kuangniaokuang** [comment]
npm install -g concurrently
npm install -g lite-server
npm install -g typescript

**Comment by anirbanmishra** [comment]
Tried the above still some issues...
[Issue.txt](https://github.com/npm/npm/files/280960/Issue.txt)

**Comment by anirbanmishra** [comment]
Can close the issue...the class path for GIT while setting up in Windows was set to the cmd\ folder...just changed that to bin\ folder and everything worked fine.
