### ISSUE TITLE
npm install EEXIST errno -17 (node 6.2, npm 3.9.2)

### ISSUE THREAD

**Issue by anthonator** [npm/npm#12822]
Whenever we try to `npm install` we keep running into various dependencies failing with this error. If I delete `/usr/src/app/node_modules/dashdash/node_modules` it will either break here again or another module. Seems like it could be a race condition. Saw some older closed issues that seemed similar to this.

We're completely stuck at the moment.

```
npm ERR! Linux 4.4.9-moby
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.2.0
npm ERR! npm  v3.9.2
npm ERR! path /usr/src/app/node_modules/dashdash/node_modules
npm ERR! code EEXIST
npm ERR! errno -17
npm ERR! syscall mkdir

npm ERR! EEXIST: file already exists, mkdir '/usr/src/app/node_modules/dashdash/node_modules'
npm ERR! File exists: /usr/src/app/node_modules/dashdash/node_modules
npm ERR! Move it away, and try again.
```

```js
{
  "private": true,
  "dependencies": {
    "babel-core": "^6.4.0",
    "babel-loader": "^6.2.0",
    "babel-plugin-transform-runtime": "^6.4.0",
    "babel-polyfill": "^6.3.0",
    "babel-preset-es2015": "^6.3.0",
    "babel-preset-react": "^6.3.0",
    "babel-preset-stage-0": "^6.3.0",
    "babel-runtime": "^6.3.19",
    "bourbon": "^4.2.7",
    "bourbon-neat": "^1.7.4",
    "change-case": "~2.3.0",
    "classnames": "^2.2.5",
    "css-loader": "^0.23.0",
    "d3": "^3.5.17",
    "dotenv": "^2.0.0",
    "express": "~4.13.0",
    "file-loader": "^0.8.0",
    "html-webpack-plugin": "^2.7.0",
    "json-loader": "~0.5.0",
    "moment": "^2.13.0",
    "morgan": "~1.7.0",
    "node-sass": "^3.4.0",
    "pwny": "~0.3.0",
    "react": "~15.1.0",
    "react-dom": "~15.1.0",
    "react-redux": "~4.4.0",
    "react-router": "~2.4.0",
    "react-router-redux": "~4.0.0",
    "react-tap-event-plugin": "^1.0.0",
    "redux": "~3.5.0",
    "redux-thunk": "~2.0.0",
    "resolve-url-loader": "^1.4.0",
    "sass-loader": "^3.1.0",
    "style-loader": "^0.13.0",
    "url-loader": "^0.5.0",
    "webpack": "~1.13.0"
  },
  "devDependencies": {
    "babel-eslint": "^6.0.0",
    "babel-preset-node6": "^11.0.0",
    "eslint": "^2.8.0",
    "eslint-plugin-react": "^5.0.0",
    "react-hot-loader": "^1.3.0",
    "webpack-dev-server": "^1.14.0"
  },
  "scripts": {
    "lint": "eslint . --ext .js,.jsx --parser babel-eslint",
    "postinstall": "webpack --config app/config/webpack.config.js",
    "start": "node web.js",
    "start:dev": "webpack-dev-server --config app/config/webpack.config.js --host 0.0.0.0 --hot --progress --inline --history-api-fallback"
  }
}
```

[npm-debug.log.txt](https://github.com/npm/npm/files/279776/npm-debug.log.txt)

**Comment by anthonator** [comment]
If I try to install `dashdash` by itself (`npm install dashdash`) I'm getting the same issue.

**Comment by anthonator** [comment]
Should probably stop neglecting to mention I'm running this using Docker.

**Comment by anthonator** [comment]
Seems others are also having this issue.

https://forums.docker.com/t/npm-install-doesnt-complete-inside-docker-container/12640/7

**Comment by dsheets** [comment]
This is a problem with Docker for Mac Beta. It should be fixed in the forthcoming Beta 13 release.

**Comment by anthonator** [comment]
@dsheets great news!

Is there an issue or documentation somewhere stating this?

**Comment by dsheets** [comment]
There will be more information in the Beta 13 release notes.

**Comment by anthonator** [comment]
This was fixed with beta 13.

**Comment by itsecpmsf** [comment]
I ran into this issue today (Aug 30, 2016).
It was working 15 days ago....I am using docker beta for MAC

**Comment by dsheets** [comment]
@itsecpmsf This issue report corresponds to potentially many underlying issues. Please report issues to the [docker/for-mac issue tracker](https://github.com/docker/for-mac/issues). The current beta is Beta 24. Please upgrade to that version and test your use case before reporting your issue. Thanks!
