### ISSUE TITLE
npm 3 with npm link.

### ISSUE THREAD

**Issue by pwang2** [npm/npm#12826]
npm3 's flat structure is sleek mostly. One special case is with `npm link` in dev workflow.

If we install A to project through `npm install A`,  A depends on B.  If we use `npm link A` thereafter for developing purpose ,   it will introduce an extraneous error as the B is already installed in A's node_module folder where the symbolic target refers, the flattened folder also contains B from previous `npm install A` become extraneous. 

This is not a huge issue. but could be prevented by post-checking after `npm link`.  This sounds making more sense to me? Any comments?

**Comment by kaore** [comment]
+1

**Comment by bertho-zero** [comment]
+1

**Comment by bertho-zero** [comment]
This problem still exists with npm 3, 4 and 5 ... And it's really very embarrassant.
