### ISSUE TITLE
Api connect install

### ISSUE THREAD

**Issue by Venky69** [npm/npm#12839]
Error while installing api connect 
[npm-debug.docx](https://github.com/npm/npm/files/282601/npm-debug.docx)

**Comment by KenanY** [comment]
@Venky69 Could you upload the `npm-debug.log` as a text file to [gist.github.com](https://gist.github.com/)?

**Comment by Venky69** [comment]
[npm-debug.TXT](https://github.com/npm/npm/files/284254/npm-debug.TXT)
