### ISSUE TITLE
NPM Link can't create a link on a mapped drive folder.

### ISSUE THREAD

**Issue by Jackbennett** [npm/npm#12835]
Hi, I didn't see a similar issue so just making a new one. I don't know if this can be fixed.

```
npm link
npm WARN announce@0.1.0 No repository field.
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\jbennett\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "link"
npm ERR! node v4.4.3
npm ERR! npm  v3.9.2
npm ERR! path C:\Users\jbennett\AppData\Roaming\npm\node_modules\announce\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\jbennett\AppData\Roaming\npm\node_modules\announce\package.json'
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\jbennett\AppData\Roaming\npm\node_modules\announce\package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     N:\Documents\src\project-discovery\announce\npm-debug.log
```

Can't seem to use link from `N:\Documents\src\project-discovery\announce\` N:\ being mapped to a network share. If I copy these things to c:/temp it all works fine. The above is from an administrator prompt. I see a shotcut created at `C:\Users\jbennett.BHS\AppData\Roaming\npm\node_modules` but clicking it has this error;
![image](https://cloud.githubusercontent.com/assets/791134/15541678/812b960a-2285-11e6-94d8-f71e4d9e6a71.png)

W10 x64, node 4.4.3 the npm that ships with and also 3.9.2.

**Comment by jordwalke** [comment]
Where are the limitations of windows symlinking (either via `npm link` or `bin-link`) clearly documented in npm's docs? I read through all of the and couldn't find anything that indicated my code wouldn't work on windows. It seems this is something people should be abundantly aware of when developing packages.
