### ISSUE TITLE
NPM outdated 'dir' column unreadable with solarized dark theme

### ISSUE THREAD

**Issue by tribou** [npm/npm#12842]
I didn't even realize there was anything in the Location column until I accidentally highlighted:

![screen shot 2016-05-25 at 5 37 52 pm](https://cloud.githubusercontent.com/assets/1641390/15558415/9b9fab9c-229f-11e6-8408-028119a0fc38.png)

I vote we complete the color wheel triad with cyan:

![screen shot 2016-05-25 at 5 39 23 pm](https://cloud.githubusercontent.com/assets/1641390/15558422/af2e8822-229f-11e6-998f-3f2bb35a7bf7.png)

**Comment by busches** [comment]
@iarna merged this back in May, this can be closed.
