### ISSUE TITLE
fail to install formidable 

### ISSUE THREAD

**Issue by daiseita** [npm/npm#12848]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'formidable' ]
2 info using npm@2.15.1
3 info using node@v4.4.3
4 verbose install initial load of C:\node\faceCms\package.json
5 warn package.json faceCms@ No description
6 warn package.json faceCms@ No repository field.
7 warn package.json faceCms@ No README data
8 warn package.json faceCms@ No license field.
9 verbose installManyTop reading scoped package data from C:\node\faceCms\node_modules\body-parser\package.json
10 verbose installManyTop reading scoped package data from C:\node\faceCms\node_modules\ejs\package.json
11 verbose installManyTop reading scoped package data from C:\node\faceCms\node_modules\express\package.json
12 verbose installManyTop reading scoped package data from C:\node\faceCms\node_modules\fs\package.json
13 verbose installManyTop reading scoped package data from C:\node\faceCms\node_modules\mssql\package.json
14 verbose installManyTop reading scoped package data from C:\node\faceCms\node_modules\path\package.json
15 verbose installManyTop reading scoped package data from C:\node\faceCms\node_modules\q\package.json
16 info package.json fs@0.0.2 fs is also the name of a node core module.
17 info package.json fs@0.0.2 No description
18 info package.json fs@0.0.2 No repository field.
19 info package.json path@0.12.7 path is also the name of a node core module.
20 info package.json q@1.4.1 license should be a valid SPDX license expression
21 verbose readDependencies loading dependencies from C:\node\faceCms\package.json
22 silly cache add args [ 'formidable', null ]
23 verbose cache add spec formidable
24 silly cache add parsed spec Result {
24 silly cache add   raw: 'formidable',
24 silly cache add   scope: null,
24 silly cache add   name: 'formidable',
24 silly cache add   rawSpec: '',
24 silly cache add   spec: 'latest',
24 silly cache add   type: 'tag' }
25 silly addNamed formidable@latest
26 verbose addNamed "latest" is being treated as a dist-tag for formidable
27 info addNameTag [ 'formidable', 'latest' ]
28 silly mapToRegistry name formidable
29 silly mapToRegistry using default registry
30 silly mapToRegistry registry http://registry.cnpmjs.org/
31 silly mapToRegistry data Result {
31 silly mapToRegistry   raw: 'formidable',
31 silly mapToRegistry   scope: null,
31 silly mapToRegistry   name: 'formidable',
31 silly mapToRegistry   rawSpec: '',
31 silly mapToRegistry   spec: 'latest',
31 silly mapToRegistry   type: 'tag' }
32 silly mapToRegistry uri http://registry.cnpmjs.org/formidable
33 verbose addNameTag registry:http://registry.cnpmjs.org/formidable not in flight; fetching
34 verbose request uri http://registry.cnpmjs.org/formidable
35 verbose request no auth needed
36 info attempt registry request try #1 at 12:14:29
37 verbose request id 4a46fdbb7f375b8a
38 http request GET http://registry.cnpmjs.org/formidable
39 info retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND registry.cnpmjs.org registry.cnpmjs.org:80
40 info attempt registry request try #2 at 12:14:51
41 http request GET http://registry.cnpmjs.org/formidable
42 info retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND registry.cnpmjs.org registry.cnpmjs.org:80
43 info attempt registry request try #3 at 12:16:03
44 http request GET http://registry.cnpmjs.org/formidable
45 silly get cb [ 304, undefined ]
46 verbose stack Error: failed to fetch from registry: http://registry.cnpmjs.org/formidable
46 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\cache\caching-client.js:163:27
46 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\cache\caching-client.js:52:8
46 verbose stack     at f (C:\Program Files\nodejs\node_modules\npm\node_modules\once\once.js:17:25)
46 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:89:10
46 verbose stack     at f (C:\Program Files\nodejs\node_modules\npm\node_modules\once\once.js:17:25)
46 verbose stack     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:186:20)
46 verbose stack     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:163:20)
46 verbose stack     at self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:199:22)
46 verbose stack     at emitOne (events.js:82:20)
46 verbose stack     at Request.emit (events.js:169:7)
47 verbose cwd C:\node\faceCms
48 error Windows_NT 6.1.7601
49 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "formidable"
50 error node v4.4.3
51 error npm  v2.15.1
52 error failed to fetch from registry: http://registry.cnpmjs.org/formidable
53 error If you need help, you may report this error at:
53 error     <https://github.com/npm/npm/issues>
54 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@daiseita Does this also occur if you use the default registry (`https://registry.npmjs.org`)?

**Comment by KenanY** [comment]
@daiseita Hi, it has been a week now with no response. Are you still seeing this issue with the default registry?

**Comment by KenanY** [comment]
Closing as abandoned.
