### ISSUE TITLE
No compatible version found: walkie-talkie@0.0.4

### ISSUE THREAD

**Issue by kjbrazil** [npm/npm#12850]
```
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.4.5
npm ERR! npm  v3.9.2

npm ERR! No compatible version found: walkie-talkie@0.0.4
npm ERR! Valid install targets:
npm ERR! 0.4.1, 0.4.0, 0.3.2, 0.3.1, 0.3.0, 0.2.3, 0.2.1, 0.2.0, 0.1.0, 0.0.7 
```

My log file can be found here: https://gist.github.com/kjbrazil/cdea7c063c84d02430c549c26ca1e0b7

Trying to install this intercom-cli tool: https://github.com/kouk/intercom-cli

**Comment by KenanY** [comment]
@kjbrazil Looks like that tool is depending on a version of `walkie-talkie` that no longer exists (as the error messages somewhat points out). I do not think that this is an issue with `npm`. The best solution would probably be to send a pull request to the `intercom-cli` project updating that dependency version to one which exists in the npm registry.

**Comment by kjbrazil** [comment]
Ah, gotcha. Thanks @KenanY. I removed the dependency for the time being and the install worked.
