### ISSUE TITLE
googleapis is not installing

### ISSUE THREAD

**Issue by QandeelHaider** [npm/npm#12858]
When i write  npm install googleapis --save
It shows me this error...
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Users\\Qandeel Haider\\AppData\\Roaming\\npm\\node.exe" "C:\\Users\\Qandeel Haider\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "googleapis" "--save"
npm ERR! node v4.4.1
npm ERR! npm  vSyntaxError: Unexpected string

npm ERR! Invalid Version: SyntaxError: Unexpected string
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Qandeel Haider\npm-debug.log

**Comment by KenanY** [comment]
@QandeelHaider Hmm, this looks a bit weird to me. What does `npm --version` return? Is there a full `npm-debug.log` that you can upload to [gist.github.com](https://gist.github.com)?

**Comment by KenanY** [comment]
@QandeelHaider Hi, it's been a week now with no response. Are you still seeing this issue? If so, could you provide the file I requested?

**Comment by KenanY** [comment]
Closing as abandoned. Still curious what this issue was... only one like it I have ever seen on this issue tracker.
