### ISSUE TITLE
uid must be an unsigned int

### ISSUE THREAD

**Issue by Sunil23391** [npm/npm#12852]
![npm_error](https://cloud.githubusercontent.com/assets/12194923/15569324/0a66ffc2-234e-11e6-80dc-0db3dd5a45a2.png)
I'm getting the above error, I'm using the node version: 4.4.4 and npm version:2.2.0

**Comment by KenanY** [comment]
@Sunil23391 Does this also occur if you [update `npm`](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm)?

**Comment by KenanY** [comment]
@Sunil23391 Hi, it has been a week now with no response. Are you still seeing this issue after updating to the latest stable release of `npm`?

**Comment by KenanY** [comment]
Closing as abandoned.
