### ISSUE TITLE
Cannot install ionic

### ISSUE THREAD

**Issue by olamieUsman** [npm/npm#12869]
Here is the issue I am having here

![npm](https://cloud.githubusercontent.com/assets/11750102/15604128/64bb123a-23f6-11e6-882b-6df3a951cef0.PNG)

**Comment by KenanY** [comment]
@olamieUsman Have you tried running `npm cache clean`?

**Comment by olamieUsman** [comment]
Yes, I did that several times. @KenanY

**Comment by zkat** [comment]
Closing as a duplicate of https://github.com/npm/npm/issues/14626
