### ISSUE TITLE
NPM config file is not loaded for Codeship and Vagrant

### ISSUE THREAD

**Issue by StephanBijzitter** [npm/npm#12860]
Created a new issue which may or may not be tightly related to: #7995

Following the guide on Codeship's official website, I added the following to our provisioning script:
https://codeship.com/documentation/languages/nodejs/#npm-private-modules

``` bash
echo "Setting up read-only private NPM...";
touch "${HOME}/.npmrc" || exit 1;
export NPM_REGISTRY=https://registry.npmjs.org/ || exit 1;
export NPM_TOKEN_READ=<redacted> || exit 1;
echo "//${NPM_REGISTRY}/:_authToken=${NPM_TOKEN_READ}" > "${HOME}/.npmrc" || exit 1;
```

The `.npmrc` file is as expected:

``` bash
cat "${HOME}/.npmrc";

//https://registry.npmjs.org//:_authToken=<redacted>
```

This however, did not work.
However, the following does work:

``` bash
echo "Setting up read-only private NPM...";
export NPM_REGISTRY=https://registry.npmjs.org/ || exit 1;
export NPM_TOKEN_READ=<redacted> || exit 1;
npm config set //$NPM_REGISTRY/:_authToken=$NPM_TOKEN_READ || exit 1;
```

This leads me to believe that `npm install` is not using the latest configuration that was manually set by editing the `.npmrc` file. As logging in using `npm login` and setting the configuration with `npm config set` does resolve this issue.

I would suggest that `npm install` _always_ re-reads the `.npmrc` file.

**Comment by StephanBijzitter** [comment]
So... my token does not work anymore.

**Comment by joeyfigaro** [comment]
Any updates on this? Running into the same issue, except neither example that @StephanBijzitter works.

**Comment by legodude17** [comment]
@StephanBijzitter, `npm install` doesn't read the file, it just loads config from `config-chain`, I am not sure why your first example failed.

@joeyfigaro, are you doing `npm config set //$NPM_REGISTRY/:_authToken=$NPM_TOKEN_READ`?

**Comment by joeyfigaro** [comment]
@legodude17 I've tried the following:
`npm config set //registry.npmjs.org/:_authToken={$NPM_AUTH_TOKEN}`
`npm config set //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN`
`npm config set //registry.npmjs.org/:_authToken=<actual-redacted-token>`

Not even the last one worked, where we weren't even depending on env vars. 

Might be worth mentioning that we've also got an `.npmrc` in the root of our repository, ala codeship's tutorial.

**Comment by legodude17** [comment]
I agree with that assessment. Can post both of your `.npmrc`s?

**Comment by joeyfigaro** [comment]
@legodude17 Yep, appears that was it so far. 

Went with just an `.npmrc` at root of project with the following: 
`//registry.npmjs.org/:_authToken=$REDACTED_TOKEN_NAME
scope=@REDACTED
@painless1099:registry=https://registry.npmjs.org/
`
 Env var is supplied via codeship, and also exists on the remote machine, so not 100% sure which is actually supplying the value when called for.

**Comment by legodude17** [comment]
Does it work with just the `.npmrc`?

**Comment by joeyfigaro** [comment]
@legodude17 It does so far, yep! Tested on two pipelines for one repository. Confirming with a second repository and two more pipelines now.

**Comment by joeyfigaro** [comment]
@legodude17 We're back to failing after our dependency cache was reset on codeship. Logged into npm, updated env var with new token for `.npmrc`.

**Comment by legodude17** [comment]
@joeyfigaro did your token expire or was it this issue?
