### ISSUE TITLE
No compatible version found: phantomjs@~1.8.1

### ISSUE THREAD

**Issue by HogiQuin** [npm/npm#12861]
Somabody can help me? is miy first time with node 

[npm-debug.txt](https://github.com/npm/npm/files/285012/npm-debug.txt)

**Comment by KenanY** [comment]
@HogiQuin Could you share the `"dependencies"` and `"devDependencies"` parts of your `package.json`?

**Comment by HogiQuin** [comment]
{
  "name": "Strut",
  "version": "0.4.0",
  "devDependencies": {
    "grunt": "~0.4.1",
    "grunt-contrib-handlebars": "~0.5.10",
    "grunt-contrib-copy": "~0.4.0",
    "grunt-contrib-concat": "~0.3.0",
    "grunt-contrib-uglify": "~0.2.0",
    "grunt-contrib-jshint": "~0.6.0",
    "grunt-contrib-cssmin": "~0.6.0",
    "grunt-contrib-connect": "0.3.0",
    "grunt-contrib-clean": "~0.4.1",
    "grunt-contrib-htmlmin": "~0.1.3",
    "grunt-contrib-imagemin": "~0.1.4",
    "grunt-contrib-watch": "~0.4.0",
    "grunt-contrib-livereload": "0.1.1",
    "grunt-usemin": "~0.1.9",
    "grunt-contrib-requirejs": "~0.4.1",
    "grunt-open": "~0.2.0",
    "matchdep": "~0.1.2",
    "grunt-text-replace": "~0.3.2"
  },
  "engines": {
    "node": ">=0.8.0"
  }
}

**Comment by KenanY** [comment]
@HogiQuin Thanks! Unfortunately I cannot reproduce this at all. In fact, when I run `npm ls phantomjs` after the install succeeds, I get no results, which indicates that no module in your dependency tree has a dependency on the module that is giving you an issue. Does this still occur after running `npm cache clean` and after removing your entire `node_modules/` directory?

``` bash
$ node -v && npm -v
v5.9.1
3.9.1
```

**Comment by HogiQuin** [comment]
sonnica@desarrollo:~/Escritorio/Strut$ npm install
npm WARN deprecated grunt-contrib-livereload@0.1.1: Deprecated in favor of grunt-contrib-watch which now have Livereload support built-in.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN prefer global jshint@2.1.11 should be installed with -g

> optipng-bin@0.2.6 postinstall /home/sonnica/Escritorio/Strut/node_modules/optipng-bin
> node pre-build.js

(node:2388) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.


  3 tests complete (415 ms)

pre-build test passed successfully, skipping build...

> jpegtran-bin@0.1.7 postinstall /home/sonnica/Escritorio/Strut/node_modules/jpegtran-bin
> node pre-build.js

(node:2410) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.














  3 tests complete (403 ms)

pre-build test passed successfully, skipping build...
Strut@0.4.0 /home/sonnica/Escritorio/Strut
├─┬ grunt@0.4.5 
│ ├── async@0.1.22 
│ ├── coffee-script@1.3.3 
│ ├── colors@0.6.2 
│ ├── dateformat@1.0.2-1.2.3 
│ ├── eventemitter2@0.4.14 
│ ├── exit@0.1.2 
│ ├─┬ findup-sync@0.1.3 
│ │ ├─┬ glob@3.2.11 
│ │ │ ├── inherits@2.0.1 
│ │ │ └── minimatch@0.3.0 
│ │ └── lodash@2.4.2 
│ ├── getobject@0.1.0 
│ ├─┬ glob@3.1.21 
│ │ ├── graceful-fs@1.2.3 
│ │ └── inherits@1.0.2 
│ ├─┬ grunt-legacy-log@0.1.3 
│ │ ├─┬ grunt-legacy-log-utils@0.1.1 
│ │ │ ├── lodash@2.4.2 
│ │ │ └── underscore.string@2.3.3 
│ │ ├── lodash@2.4.2 
│ │ └── underscore.string@2.3.3 
│ ├── grunt-legacy-util@0.2.0 
│ ├── hooker@0.2.3 
│ ├── iconv-lite@0.2.11 
│ ├─┬ js-yaml@2.0.5 
│ │ ├─┬ argparse@0.1.16 
│ │ │ ├── underscore@1.7.0 
│ │ │ └── underscore.string@2.4.0 
│ │ └── esprima@1.0.4 
│ ├── lodash@0.9.2 
│ ├─┬ minimatch@0.2.14 
│ │ ├── lru-cache@2.7.3 
│ │ └── sigmund@1.0.1 
│ ├─┬ nopt@1.0.10 
│ │ └── abbrev@1.0.7 
│ ├── rimraf@2.2.8 
│ ├── underscore.string@2.2.1 
│ └── which@1.0.9 
├── grunt-contrib-clean@0.4.1 
├── grunt-contrib-concat@0.3.0 
├─┬ grunt-contrib-connect@0.3.0 
│ └─┬ connect@2.7.11 
│   ├── buffer-crc32@0.2.1 
│   ├── bytes@0.2.0 
│   ├── cookie@0.0.5 
│   ├── cookie-signature@1.0.1 
│   ├─┬ debug@2.2.0 
│   │ └── ms@0.7.1 
│   ├── formidable@1.0.14 
│   ├── fresh@0.1.0 
│   ├── pause@0.0.1 
│   ├── qs@0.6.5 
│   └─┬ send@0.1.1 
│     ├── mime@1.2.11 
│     └── range-parser@0.0.4 
├── grunt-contrib-copy@0.4.1 
├─┬ grunt-contrib-cssmin@0.6.2 
│ ├─┬ clean-css@1.1.7 
│ │ └── commander@2.0.0 
│ └─┬ grunt-lib-contrib@0.6.1 
│   └── zlib-browserify@0.0.1 
├─┬ grunt-contrib-handlebars@0.5.12 
│ ├── grunt-lib-contrib@0.5.3 
│ └─┬ handlebars@1.0.12 
│   ├─┬ optimist@0.3.7 
│   │ └── wordwrap@0.0.3 
│   └─┬ uglify-js@2.3.6 
│     ├── async@0.2.10 
│     └── source-map@0.1.43 
├─┬ grunt-contrib-htmlmin@0.1.3 
│ └── html-minifier@0.5.6 
├─┬ grunt-contrib-imagemin@0.1.4 
│ ├── filesize@1.7.9 
│ ├─┬ jpegtran-bin@0.1.7 
│ │ ├─┬ mocha@1.9.0 
│ │ │ ├── commander@0.6.1 
│ │ │ ├── diff@1.0.2 
│ │ │ ├── growl@1.7.0 
│ │ │ ├─┬ jade@0.26.3 
│ │ │ │ ├── commander@0.6.1 
│ │ │ │ └── mkdirp@0.3.0 
│ │ │ ├── mkdirp@0.3.3 
│ │ │ └── ms@0.3.0 
│ │ ├─┬ request@2.16.6 
│ │ │ ├── aws-sign@0.2.0 
│ │ │ ├── cookie-jar@0.2.0 
│ │ │ ├── forever-agent@0.2.0 
│ │ │ ├─┬ form-data@0.0.10 
│ │ │ │ ├── async@0.2.10 
│ │ │ │ └─┬ combined-stream@0.0.7 
│ │ │ │   └── delayed-stream@0.0.5 
│ │ │ ├─┬ hawk@0.10.2 
│ │ │ │ ├── boom@0.3.8 
│ │ │ │ ├── cryptiles@0.1.3 
│ │ │ │ ├── hoek@0.7.6 
│ │ │ │ └── sntp@0.1.4 
│ │ │ ├── json-stringify-safe@3.0.0 
│ │ │ ├── node-uuid@1.4.7 
│ │ │ ├── oauth-sign@0.2.0 
│ │ │ ├── qs@0.5.6 
│ │ │ └── tunnel-agent@0.2.0 
│ │ └─┬ tar@0.1.20 
│ │   ├── block-stream@0.0.9 
│ │   └─┬ fstream@0.1.31 
│ │     ├── graceful-fs@3.0.8 
│ │     └─┬ mkdirp@0.5.1 
│ │       └── minimist@0.0.8 
│ └── optipng-bin@0.2.6 
├─┬ grunt-contrib-jshint@0.6.5 
│ └─┬ jshint@2.1.11 
│   ├── cli@0.4.5 
│   ├── console-browserify@0.1.6 
│   ├── shelljs@0.1.4 
│   └── underscore@1.4.4 
├─┬ grunt-contrib-livereload@0.1.1 
│ └─┬ tiny-lr@0.0.9 
│   ├─┬ body-parser@1.15.1 
│   │ ├── bytes@2.3.0 
│   │ ├── content-type@1.0.2 
│   │ ├── depd@1.1.0 
│   │ ├─┬ http-errors@1.4.0 
│   │ │ └── statuses@1.3.0 
│   │ ├── iconv-lite@0.4.13 
│   │ ├─┬ on-finished@2.3.0 
│   │ │ └── ee-first@1.1.1 
│   │ ├── qs@6.1.0 
│   │ ├─┬ raw-body@2.1.6 
│   │ │ ├── bytes@2.3.0 
│   │ │ ├── iconv-lite@0.4.13 
│   │ │ └── unpipe@1.0.0 
│   │ └─┬ type-is@1.6.13 
│   │   ├── media-typer@0.3.0 
│   │   └─┬ mime-types@2.1.11 
│   │     └── mime-db@1.23.0 
│   ├── debug@0.8.1 
│   ├─┬ faye-websocket@0.7.3 
│   │ └─┬ websocket-driver@0.6.5 
│   │   └── websocket-extensions@0.1.1 
│   ├─┬ noptify@0.0.3 
│   │ └── nopt@2.0.0 
│   ├── parseurl@1.3.1 
│   └── qs@0.6.6 
├─┬ grunt-contrib-requirejs@0.4.4 
│ └── requirejs@2.1.22 
├─┬ grunt-contrib-uglify@0.2.7 
│ └─┬ uglify-js@2.4.24 
│   ├── async@0.2.10 
│   ├─┬ source-map@0.1.34 
│   │ └── amdefine@1.0.0 
│   ├── uglify-to-browserify@1.0.2 
│   └─┬ yargs@3.5.4 
│     ├── camelcase@1.2.1 
│     ├── decamelize@1.2.0 
│     ├── window-size@0.1.0 
│     └── wordwrap@0.0.2 
├─┬ grunt-contrib-watch@0.4.4 
│ ├─┬ gaze@0.3.4 
│ │ └── fileset@0.1.8 
│ └─┬ tiny-lr@0.0.4 
│   ├── debug@0.7.4 
│   ├── faye-websocket@0.4.4 
│   ├─┬ noptify@0.0.3 
│   │ └── nopt@2.0.0 
│   └── qs@0.5.6 
├─┬ grunt-open@0.2.3 
│ └── open@0.0.5 
├── grunt-text-replace@0.3.12 
├── grunt-usemin@0.1.13 
└── matchdep@0.1.2 

npm WARN Strut@0.4.0 No repository field.
npm WARN Strut@0.4.0 No license field.


I think the installation is complete, but now I have another problem, the instruction say: "put 'grunt server' "but when u put that in the terminal, the terminal show me that:

sonnica@desarrollo:~/Escritorio/Strut$ grunt server
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:1146:7)
    at Object.<anonymous> (/usr/local/lib/node_modules/grunt/bin/grunt:13:16)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
  
any idea?

**Comment by KenanY** [comment]
@HogiQuin No idea, that's not an issue with `npm` as far as I can tell. Maybe ask other `grunt` users?

**Comment by HogiQuin** [comment]
Where I can find grunt users?

**Comment by KenanY** [comment]
@HogiQuin http://gruntjs.com/help-resources
