### ISSUE TITLE
Issue with installing of Ionic

### ISSUE THREAD

**Issue by Hackwolf** [npm/npm#12867]
Issue with installing of Ionic.

![ionic issue](https://cloud.githubusercontent.com/assets/19602897/15598461/0a01fa42-23e3-11e6-8342-bf88774f2df6.jpg)

Content of npm-debug.log:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'ionic' ]
2 info using npm@2.14.12
3 info using node@v4.2.6
4 verbose install initial load of C:\Users\Cubar\AppData\Roaming\npm\package.json
5 verbose readDependencies loading dependencies from C:\Users\Cubar\AppData\Roaming\npm\package.json
6 silly cache add args [ 'ionic', null ]
7 verbose cache add spec ionic
8 silly cache add parsed spec Result {
8 silly cache add   raw: 'ionic',
8 silly cache add   scope: null,
8 silly cache add   name: 'ionic',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: 'latest',
8 silly cache add   type: 'tag' }
9 silly addNamed ionic@latest
10 verbose addNamed "latest" is being treated as a dist-tag for ionic
11 info addNameTag [ 'ionic', 'latest' ]
12 silly mapToRegistry name ionic
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/ionic
16 verbose addNameTag registry:https://registry.npmjs.org/ionic not in flight; fetching
17 verbose request uri https://registry.npmjs.org/ionic
18 verbose request no auth needed
19 info attempt registry request try #1 at 07:42:34
20 verbose request id d5b5b68768dac742
21 verbose etag "1ODPFRI9GJNYCEO0PMMEFTEBW"
22 http request GET https://registry.npmjs.org/ionic
23 http 200 https://registry.npmjs.org/ionic
24 verbose headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
24 verbose headers   etag: '"50OWXNJR23DNSNBF5G6YB4ZET"',
24 verbose headers   'content-type': 'application/json',
24 verbose headers   'content-encoding': 'gzip',
24 verbose headers   'cache-control': 'max-age=300',
24 verbose headers   'content-length': '61517',
24 verbose headers   'accept-ranges': 'bytes',
24 verbose headers   date: 'Fri, 27 May 2016 04:42:30 GMT',
24 verbose headers   via: '1.1 varnish',
24 verbose headers   age: '0',
24 verbose headers   connection: 'keep-alive',
24 verbose headers   'x-served-by': 'cache-fra1243-FRA',
24 verbose headers   'x-cache': 'HIT',
24 verbose headers   'x-cache-hits': '1',
24 verbose headers   'x-timer': 'S1464324149.903550,VS0,VE107',
24 verbose headers   vary: 'Accept-Encoding' }
25 silly get cb [ 200,
25 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
25 silly get     etag: '"50OWXNJR23DNSNBF5G6YB4ZET"',
25 silly get     'content-type': 'application/json',
25 silly get     'content-encoding': 'gzip',
25 silly get     'cache-control': 'max-age=300',
25 silly get     'content-length': '61517',
25 silly get     'accept-ranges': 'bytes',
25 silly get     date: 'Fri, 27 May 2016 04:42:30 GMT',
25 silly get     via: '1.1 varnish',
25 silly get     age: '0',
25 silly get     connection: 'keep-alive',
25 silly get     'x-served-by': 'cache-fra1243-FRA',
25 silly get     'x-cache': 'HIT',
25 silly get     'x-cache-hits': '1',
25 silly get     'x-timer': 'S1464324149.903550,VS0,VE107',
25 silly get     vary: 'Accept-Encoding' } ]
26 verbose get saving ionic to C:\Users\Cubar\AppData\Roaming\npm-cache\registry.npmjs.org\ionic\.cache.json
27 silly addNameTag next cb for ionic with tag latest
28 silly addNamed ionic@1.7.15
29 verbose addNamed "1.7.15" is a plain semver version for ionic
30 silly mapToRegistry name ionic
31 silly mapToRegistry using default registry
32 silly mapToRegistry registry https://registry.npmjs.org/
33 silly mapToRegistry uri https://registry.npmjs.org/ionic
34 verbose addRemoteTarball https://registry.npmjs.org/ionic/-/ionic-1.7.15.tgz not in flight; adding
35 verbose addRemoteTarball [ 'https://registry.npmjs.org/ionic/-/ionic-1.7.15.tgz',
35 verbose addRemoteTarball   'fe83a72a60d03d667d0f3bb47a4210f57356c322' ]
36 info retry fetch attempt 1 at 07:42:38
37 info attempt registry request try #1 at 07:42:38
38 http fetch GET https://registry.npmjs.org/ionic/-/ionic-1.7.15.tgz
39 http fetch 200 https://registry.npmjs.org/ionic/-/ionic-1.7.15.tgz
40 info retry will retry, error on last attempt: Error: read ECONNRESET
41 info retry will retry, error on last attempt: Error: read ECONNRESET
42 silly fetchAndShaCheck shasum fe83a72a60d03d667d0f3bb47a4210f57356c322
43 verbose stack Error: shasum check failed for C:\Users\Cubar\AppData\Local\Temp\npm-96704-2a8818b8\registry.npmjs.org\ionic\-\ionic-1.7.15.tgz
43 verbose stack Expected: fe83a72a60d03d667d0f3bb47a4210f57356c322
43 verbose stack Actual:   ea653eef317300718d155ba5b9abf485b75173b2
43 verbose stack From:     https://registry.npmjs.org/ionic/-/ionic-1.7.15.tgz
43 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:25:8
43 verbose stack     at ReadStream.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:72:7)
43 verbose stack     at emitNone (events.js:72:20)
43 verbose stack     at ReadStream.emit (events.js:166:7)
43 verbose stack     at endReadableNT (_stream_readable.js:905:12)
43 verbose stack     at nextTickCallbackWith2Args (node.js:441:9)
43 verbose stack     at process._tickCallback (node.js:355:17)
44 verbose cwd C:\Ionic_projects\Coach
45 error Windows_NT 10.0.10586
46 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ionic"
47 error node v4.2.6
48 error npm  v2.14.12
49 error shasum check failed for C:\Users\Cubar\AppData\Local\Temp\npm-96704-2a8818b8\registry.npmjs.org\ionic\-\ionic-1.7.15.tgz
49 error Expected: fe83a72a60d03d667d0f3bb47a4210f57356c322
49 error Actual:   ea653eef317300718d155ba5b9abf485b75173b2
49 error From:     https://registry.npmjs.org/ionic/-/ionic-1.7.15.tgz
50 error If you need help, you may report this error at:
50 error     <https://github.com/npm/npm/issues>
51 verbose exit [ 1, true ]

Please, help me.

**Comment by KenanY** [comment]
@Hackwolf Have you tried running `npm cache clean`?

**Comment by Hackwolf** [comment]
@KenanY, thank you very much. The problem was decided.
