### ISSUE TITLE
npm 3.9.3 installs huge (331MB) .nyc_output directory in /usr/local/lib/node_modules/npm

### ISSUE THREAD

**Issue by mhart** [npm/npm#12873]
Not sure when this started happening, but I suspect sometime in the last couple of releases (edit: definitely v3.9.3)

It may have actually been pushed up in the npm publish itself? Not exactly sure where it came from – perhaps one of the npm devs used `nyc` at some point for coverage?

**Comment by mhart** [comment]
Just for completeness:

OS: happens on (at least) Mac OS X and Alpine Linux
Node.js: tried on v4.4.4 and v6.1.0

Ran the following command: `npm install npm@3`

**Comment by mhart** [comment]
Just confirmed this with manual inspection:

https://registry.npmjs.org/npm/-/npm-3.9.3.tgz is 49.6MB

https://registry.npmjs.org/npm/-/npm-3.9.2.tgz is 2.9MB

**Comment by mhart** [comment]
And just for extra completeness: Yes, I'm running this from NYC 🗽

Kinda feel like that might just be unrelated though 😸

**Comment by zkat** [comment]
looks like I did this for `npm@3.9.4`, too. But the `.nyc_output` patch will land with `npm@3.9.5`, and I'm already downstreaming to node without the `.nyc_output`, manually, so that one won't bloat up the package size. Thanks for pointing this out!

**Comment by mhart** [comment]
No probs – perhaps there's room for a feature here in the npm cmd to help devs from doing this!

"You are about to publish 331MB more than the last version, are you sure you want to do this? y/N"

**Comment by KenanY** [comment]
@mhart I agree :) https://github.com/npm/npm/issues/6252

**Comment by mhart** [comment]
@KenanY oh nice! Yep, that'd do it. 👍
