### ISSUE TITLE
Lots of npm errors after running yo hubot command

### ISSUE THREAD

**Issue by TwinsMaj** [npm/npm#12870]
I've been on this for about a day now. I'm running ubuntu/trusty64 on virtual box via vagrant. Each time i try to scaffold a new hubot project with yo hubot command, hubot gets installed but with npm errors. I really can't figure out what the issue is.

i installed node, npm, hubot and coffee script via the shell. here is what my provision.sh script looks like

    #!/bin/bash

    # update package libraries
    apt-get -y update url

    # install curl if it is not already installed
    apt-get -y  install curl

    # if nodejs is not installed...
    type node >/dev/null 2>&1 || if [[ $? != 0 ]]; then
        # we install it
        curl -sL http://deb.nodesource.com/setup_5.x | sudo -E bash -
        apt-get -y install nodejs

       # update npm
        npm install -g npm

    fi

    command -v hubot &>/dev/null || {
        npm install -g hubot coffee-script
    }

    # install yeoman for hubot
    command -v yo &>/dev/null || {
        npm install -g yo generator-hubot
    }

The nodejs version installed is v5.11.1 The npm version installed is v3.8.6

After installation, the next step is to scaffold hubot. This is done by creating a new directory.I named the directory myhubot. When I switch into the directory and type the command: Yo hubot --default, it begins installation but it ends with the error in the image below:

[npm-debug.txt](https://github.com/npm/npm/files/286251/npm-debug.txt)
![error](https://cloud.githubusercontent.com/assets/19359902/15606008/5b69ca18-2401-11e6-9528-8bd3f08ef107.PNG)

Apparently, even after the error log, if type the "hubot" command, I'm logged into the hubot shell. But then, when i ping hubot, I don't get a reply.

**Comment by KenanY** [comment]
@TwinsMaj Have you tried using the [`--no-bin-links`](https://docs.npmjs.com/misc/config#bin-links) flag?

**Comment by KenanY** [comment]
@TwinsMaj It has been over a week with no response from you; are you still experiencing this issue? Have you tried my suggested solution?

**Comment by KenanY** [comment]
Closing as abandoned.
