### ISSUE TITLE
Cannot start with command "npm start"

### ISSUE THREAD

**Issue by linhtong** [npm/npm#12871]
**Hello Guy!**

I have a problem that need somebody help me resolve it to run, the below image will show detail:
![issues](https://cloud.githubusercontent.com/assets/19607716/15606176/b8225efe-2434-11e6-8fd5-6df055f1a29e.png)

**The log file when i run "npm start" command:**
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.15.1
3 info using node@v4.4.4
4 verbose stack Error: missing script: start
4 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:142:19)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:58:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:345:5
4 verbose stack     at checkBinReferences_ (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:309:45)
4 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:343:3)
4 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:113:5)
4 verbose stack     at ReadFileContext.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:284:20)
4 verbose stack     at ReadFileContext.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16)
4 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:303:13)
5 verbose cwd C:\Websites\WebApp\reactApp
6 error Windows_NT 10.0.10586
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
8 error node v4.4.4
9 error npm  v2.15.1
10 error missing script: start
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

Thanks & Best Regard.
Linh Tong

**Comment by KenanY** [comment]
@linhtong Do you have a `"start"` script defined in your `package.json`? The error message is saying that you do not. Hence, when you try to run `npm start`, `npm` will produce this error because you are trying to run a script which simply does not exist.

**Comment by linhtong** [comment]
@KenanY thank for support. I was resolved this problem.
Thank you so much!

**Comment by KenanY** [comment]
Closing as resolved.

**Comment by view2killu** [comment]
i had the same issue over windows , by using IDE webstorm 2016.1.3. i just changed the port inside the properties back to its original ( tried before to change it on deployment to 8080 ) and than restarted the IDE and  installed the npm over and its all worked.

**Comment by phpdeveloperbalaji** [comment]
Am also facing the same kind of issue..  Seems there is issue in extracting the tarball. Can anyone suggest the solution?
![error](https://cloud.githubusercontent.com/assets/15012682/21400551/f0c230d4-c7b0-11e6-802f-9e7c8f781d83.PNG)

**Comment by alex984god** [comment]
Hello Guys! I,m new to Angularjs actually i have just started to learn. Evrything was ok but suddenly I cant open my page with npm start. Its shows me this messages in the command prompt window.
![command_prompt](https://cloud.githubusercontent.com/assets/25083512/21897358/a8db76e6-d8e9-11e6-8dbd-58ad74213c5f.png)

Can somebody help me to resolve this problem and to run my page.

Thanks & Best Regard.
Aleksandar Kostovski

**Comment by Charlotteis** [comment]
Looks like this is a problem with your angular code and nothing to do with npm itself.
Specifically looks like an error in your `product-list.component.ts` file on line 9, where you're missing a semicolon, `;`, likely at the end of that line.

**Comment by alex984god** [comment]
Thanks Charlotte very much! I haven't even notice the line of text which points where is the bug in my code.
Now in future probably I'll know where to look for my bugs in the command prompt.This was maybe a stupid question but as I said I,m new to angular.

**Comment by Charlotteis** [comment]
There are no "stupid" questions. Good luck! :)

**Comment by RodolfoEscalante** [comment]
Thanks @KenanY  very much!

**Comment by nurulshuqriah** [comment]
![pic](https://user-images.githubusercontent.com/38705098/39214065-d7284872-4845-11e8-8de1-7e0891805d18.PNG)

help me please. im first do this and i can figure this out.

**Comment by kenany** [comment]
@nurulshuqriah You do not have a `package.json` file in your current directory, but one is required for `npm start` to function. Hence the error you are receiving. Please open a new issue if you have any further questions.

**Comment by lkrodi** [comment]
You started with `npm init` ?? Because this tries to open a file that does not exist or is incorrectly configured. 

- Rewrite in your console / terminal.
`-> npm init`
- When you get the option "entry point" you type 
`-> server.js`
- Now write again 
`-> npm start`

**Comment by luthieisilra** [comment]
how to install package.json?
