### ISSUE TITLE
NPM install fails, have cleared cache etc

### ISSUE THREAD

**Issue by sdn3rd** [npm/npm#12888]
3061 error Error: ENOENT, open '/root/tmp/npm-29372-BYa8eZtF/1464475082155-0.851984241977334/package/package.json'
3062 error If you need help, you may report this log at:
3062 error     <http://github.com/isaacs/npm/issues>
3062 error or email it to:
3062 error     <npm-@googlegroups.com>
3063 error System Linux 3.0.36+
3064 error command "/usr/bin/nodejs" "/usr/bin/npm" "install"
3065 error cwd /root/alexa-app-server/alexaHarmonyApp
3066 error node -v v0.10.25
3067 error npm -v 1.3.10
3068 error path /root/tmp/npm-29372-BYa8eZtF/1464475082155-0.851984241977334/package/package.json
3069 error code ENOENT
3070 error errno 34
3071 verbose exit [ 34, true ]

**Comment by KenanY** [comment]
Hi @sdn3rd! `npm@1.3` is no longer supported. Try [updating](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) and let me know whether or not that solves your issue.

**Comment by KenanY** [comment]
@sdn3rd Are you still seeing this issue with `npm@2` or `npm@3`?

**Comment by KenanY** [comment]
Closing as abandoned.
