### ISSUE TITLE
npm install issues

### ISSUE THREAD

**Issue by NimitBedi** [npm/npm#12892]
I am unable to install pug for node.js
PFA the log file associated.
I have tried installing both express and pug, but got an error in both of these.

**Comment by KenanY** [comment]
Hi @NimitBedi! Can you please upload a `npm-debug.log` file to [gist.github.com](https://gist.github.com/) and link it here?

**Comment by KenanY** [comment]
@NimitBedi Are you still seeing this issue? If so, could you provide the `npm-debug.log` file?

**Comment by KenanY** [comment]
Closing as abandoned.
