### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by praba88** [npm/npm#12896]
C:\Users\avinashs>
[npm-debug.txt](https://github.com/npm/npm/files/288986/npm-debug.txt)

npm install -g bigcommerce/stencil-cli
npm WARN peerDependencies The peer dependency good@>= 5.x.x included from good-c
onsole will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerD
ependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it
explicitly.
npm WARN peerDependencies The peer dependency hapi@>= 8.x.x included from good w
ill no
npm WARN peerDependencies longer be automatically installed to fulfill the peerD
ependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it
explicitly.
|

> typechecker@2.0.8 preinstall C:\Users\avinashs\AppData\Roaming\npm\node_module
> s\@bigcommerce\stencil-cli\node_modules\@bigcommerce\stencil-paper\node_modules\
> messageformat\node_modules\watchr\node_modules\extendr\node_modules\typechecker
> node ./cyclic.js

\

> typechecker@2.0.8 preinstall C:\Users\avinashs\AppData\Roaming\npm\node_module
> s\@bigcommerce\stencil-cli\node_modules\@bigcommerce\stencil-paper\node_modules\
> messageformat\node_modules\watchr\node_modules\extract-opts\node_modules\typeche
> cker
> node ./cyclic.js

npm ERR! fetch failed http://registry.npmjs.org/http-proxy/-/http-proxy-1.13.2.t
gz
npm WARN retry will retry, error on last attempt: Error: fetch failed with statu
s code 403
npm ERR! fetch failed http://registry.npmjs.org/http-proxy/-/http-proxy-1.13.2.t
gz
npm WARN retry will retry, error on last attempt: Error: fetch failed with statu
s code 403
\

> spawn-sync@1.0.15 postinstall C:\Users\avinashs\AppData\Roaming\npm\node_modul
> es\@bigcommerce\stencil-cli\node_modules\@bigcommerce\stencil-styles\node_module
> s\node-sass\node_modules\cross-spawn\node_modules\spawn-sync
> node postinstall
## 

> bufferutil@1.2.1 install C:\Users\avinashs\AppData\Roaming\npm\node_modules\@b
> igcommerce\stencil-cli\node_modules\browser-sync\node_modules\socket.io\node_mod
> ules\engine.io\node_modules\ws\node_modules\bufferutil
> node-gyp rebuild

\
C:\Users\avinashs\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\node
_modules\browser-sync\node_modules\socket.io\node_modules\engine.io\node_modules
\ws\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Program
 Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-g
yp\bin\node-gyp.js" rebuild )  else (node  rebuild )
C:\Users\avinashs\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\nod
e_modules\browser-sync\node_modules\socket.io\node_modules\engine.io\node_modul
es\ws\node_modules\bufferutil\build\binding.sln : error MSB3411: Could not load
 the Visual C++ component "VCBuild.exe". If the component is not installed, eit
her 1) install the Microsoft Windows SDK for Windows Server 2008 and .NET Frame
work 3.5, or 2) install Microsoft Visual Studio 2008.
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v3.5\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_mo
dules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074
:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\Program Files (x86)\nodejs\node_modules\npm\nod
e_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\avinashs\AppData\Roaming\npm\node_modules\@bigcommerce\ste
ncil-cli\node_modules\browser-sync\node_modules\socket.io\node_modules\engine.io
\node_modules\ws\node_modules\bufferutil
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok

> utf-8-validate@1.2.1 install C:\Users\avinashs\AppData\Roaming\npm\node_module
> s\@bigcommerce\stencil-cli\node_modules\browser-sync\node_modules\socket.io\node
> _modules\engine.io\node_modules\ws\node_modules\utf-8-validate
> node-gyp rebuild

/
C:\Users\avinashs\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\node
_modules\browser-sync\node_modules\socket.io\node_modules\engine.io\node_modules
not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_module
s\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild )
else (node  rebuild )
C:\Users\avinashs\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\nod
e_modules\browser-sync\node_modules\socket.io\node_modules\engine.io\node_modul
es\ws\node_modules\utf-8-validate\build\binding.sln : error MSB3411: Could not
load the Visual C++ component "VCBuild.exe". If the component is not installed,
 either 1) install the Microsoft Windows SDK for Windows Server 2008 and .NET F
ramework 3.5, or 2) install Microsoft Visual Studio 2008.
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v3.5\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_mo
dules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074
:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\Program Files (x86)\nodejs\node_modules\npm\nod
e_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\avinashs\AppData\Roaming\npm\node_modules\@bigcommerce\ste
ncil-cli\node_modules\browser-sync\node_modules\socket.io\node_modules\engine.io
\node_modules\ws\node_modules\utf-8-validate
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm WARN optional dep failed, continuing bufferutil@1.2.1
npm WARN optional dep failed, continuing utf-8-validate@1.2.1
/

> utf-8-validate@1.2.1 install C:\Users\avinashs\AppData\Roaming\npm\node_module
> s\@bigcommerce\stencil-cli\node_modules\browser-sync\node_modules\socket.io\node
> _modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_mod
> ules\utf-8-validate
> node-gyp rebuild
## 

C:\Users\avinashs\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\node
_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_
modules\engine.io-client\node_modules\ws\node_modules\utf-8-validate>if not defi
ned npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bi
n\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (no
de  rebuild )
Traceback (most recent call last):
  File "C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\gyp
\gyp_main.py", line 18, in <module>
    sys.exit(gyp.script_main())
  File "C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\gyp
\pylib\gyp__init__.py", line 533, in script_main
    return main(sys.argv[1:])
  File "C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\gyp
\pylib\gyp__init__.py", line 526, in main
    return gyp_main(args)
  File "C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\gyp
\pylib\gyp__init__.py", line 511, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\gyp
\pylib\gyp\generator\msvs.py", line 2006, in GenerateOutput
    version=msvs_version)
  File "C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\gyp
\pylib\gyp\MSVSNew.py", line 213, in **init**
    self.Write()
  File "C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\gyp
\pylib\gyp\MSVSNew.py", line 241, in Write
    f = writer(self.path)
  File "C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\gyp
\pylib\gyp\common.py", line 392, in WriteOnDiff
    return Writer()
  File "C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\gyp
\pylib\gyp\common.py", line 339, in **init**
    dir=os.path.split(filename)[0])
  File "C:\Python27\lib\tempfile.py", line 314, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags)
  File "C:\Python27\lib\tempfile.py", line 244, in _mkstemp_inner
    fd = _os.open(file, flags, 0600)
OSError: [Errno 2] No such file or directory: 'C:\Users\avinashs\AppData\Roa
ming\npm\node_modules\@bigcommerce\stencil-cli\node_modules\browser-sync\
node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io
-client\node_modules\ws\node_modules\utf-8-validate\build\binding.sln.gyp.
wgbokd.tmp'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files (x86)\nodejs\node_
modules\npm\node_modules\node-gyp\lib\configure.js:355:16)
 ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074
:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\Program Files (x86)\nodejs\node_modules\npm\nod
e_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\avinashs\AppData\Roaming\npm\node_modules\@bigcommerce\ste
ncil-cli\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io
-client\node_modules\engine.io-client\node_modules\ws\node_modules\utf-8-validat
e
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok

> bufferutil@1.2.1 install C:\Users\avinashs\AppData\Roaming\npm\node_modules\@b
> igcommerce\stencil-cli\node_modules\browser-sync\node_modules\socket.io\node_mod
> ules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules
> \bufferutil
> node-gyp rebuild

/
C:\Users\avinashs\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\node
_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_
modules\engine.io-client\node_modules\ws\node_modules\bufferutil>if not defined
npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\no
de-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node
rebuild )
C:\Users\avinashs\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\nod
e_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\nod
e_modules\engine.io-client\node_modules\ws\node_modules\bufferutil\build\bindin
g.sln : error MSB3411: Could not load the Visual C++ component "VCBuild.exe". I
f the component is not installed, either 1) install the Microsoft Windows SDK f
or Windows Server 2008 and .NET Framework 3.5, or 2) install Microsoft Visual S
tudio 2008.
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v3.5\msbuild.exe` fail
ed with exit code: 1
stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm
\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074
:12)
 System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\Program Files (x86)\nodejs\node_modules\npm\nod
e_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\avinashs\AppData\Roaming\npm\node_modules\@bigcommerce\ste
ncil-cli\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io
-client\node_modules\engine.io-client\node_modules\ws\node_modules\bufferutil
ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm WARN optional dep failed, continuing utf-8-validate@1.2.1
npm WARN optional dep failed, continuing bufferutil@1.2.1
npm ERR! fetch failed http://registry.npmjs.org/http-proxy/-/http-proxy-1.13.2.t
gz
npm WARN optional dep failed, continuing fsevents@1.0.8
/

> node-sass@3.4.2 install C:\Users\avinashs\AppData\Roaming\npm\node_modules\@bi
> gcommerce\stencil-cli\node_modules\@bigcommerce\stencil-styles\node_modules\node
> -sass
> node scripts/install.js

Binary downloaded and installed at C:\Users\avinashs\AppData\Roaming\npm\node_mo
dules\@bigcommerce\stencil-cli\node_modules\@bigcommerce\stencil-styles\node_mod
ules\node-sass\vendor\win32-ia32-14\binding.node

> node-sass@3.4.2 postinstall C:\Users\avinashs\AppData\Roaming\npm\node_modules
> \@bigcommerce\stencil-cli\node_modules\@bigcommerce\stencil-styles\node_modules\
> node-sass
> node scripts/build.js

`C:\Users\avinashs\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\no
de_modules\@bigcommerce\stencil-styles\node_modules\node-sass\vendor\win32-ia32-
14\binding.node` exists.
 testing binary.
Binary is fine; exiting.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files (x86)\nodejs\\node.exe" "C:\Program Files (
x86)\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "bigcommerce/st
encil-cli"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! fetch failed with status code 403
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\avinashs\npm-debug.log

**Comment by gnerkus** [comment]
It seems like you are behind a corporate web proxy. You'll need to configure `npm` to work behind the proxy.
