### ISSUE TITLE
problem in adding npm dist-tag add

### ISSUE THREAD

**Issue by Devil01** [npm/npm#12897]
I am trying to add dist-tag in npm which is showing  following error
:~/workspace (master) $ npm dist-tag add "version:"["1.1.0"]                                                                                              
npm ERR! Linux 4.2.0-c9
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v4.4.3/bin/node" "/home/ubuntu/.nvm/versions/node/v4.4.3/bin/npm" "dist-tag" "add" "version:[1.1.0]"
npm ERR! node v4.4.3
npm ERR! npm  v3.9.3

npm ERR! Unsupported URL Type: version:[1.1.0]
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/workspace/npm-debug.log

please help me out

**Comment by KenanY** [comment]
@Devil01 Are you sure that you are using the [proper syntax](https://docs.npmjs.com/cli/dist-tag) for that command?

**Comment by KenanY** [comment]
@Devil01 It has been a week now with no response from you... are you still experiencing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
