### ISSUE TITLE
NPM Modules binaries getting deleted

### ISSUE THREAD

**Issue by Sinsho** [npm/npm#12904]
While running gulp.js build we get the error that a node module was not found. 

The build itself is triggered over Teamcity, the agent where npm runs on is a CentOS 7 system.

Funny about that is that npm install does not notice anything about that and still says that all modules are sucessfully installed. 

If I connect to the dev System itself and check inside the npm_module/\<module name\> folder, binaries and js files are missing. Often the whole bin/ folder was missing. 

Here an example with the module viny:

How it should look like after a successfull npm install:
<blockquote>
index.js
lib
LICENSE
package.json
README.md
test
</blockquote>
 
How it looks like if the module can not be found:
<blockquote>
lib
package.json
test
</blockquote>

As you can see the index.js file was removed for some reason aswell as the whole lib/ folder is empty. NPM itself does not throw any error at installing the node module.

The problem does occur randomly and it does not matter if we use the npm cache or not. As soon as the problem occured once, we have to delete the module folder in order to make npm install it again (since it thinks it's installed correctly).

Does anyone have similar issues or knows something about this kind of behaviour?

**Comment by backflip** [comment]
Addendum: We use Node 0.12.2 with npm 2.7.4. The same setup works fine locally on OS X and on a Jenkins CI using CentOS 6. Upgrading npm to 3 did not help.
