### ISSUE TITLE
archiver(version0.14.4)------> npm ERR! publish Failed PUT 401   

### ISSUE THREAD

**Issue by onkarojha77** [npm/npm#12901]
#npm publish archiver-0.14.4.tgz --registry http://localhost:8080/nexus/content/repositories/npm-third-party
npm ERR! publish Failed PUT 401
npm ERR! Error: Could not authenticate npmdeploy-test : archiver
npm ERR!     at RegClient.<anonymous> (/usr/local/node-v0.10.33-linux-x64/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:308:14)
npm ERR!     at Request._callback (/usr/local/node-v0.10.33-linux-x64/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:246:65)
npm ERR!     at Request.self.callback (/usr/local/node-v0.10.33-linux-x64/lib/node_modules/npm/node_modules/request/request.js:236:22)
npm ERR!     at Request.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/local/node-v0.10.33-linux-x64/lib/node_modules/npm/node_modules/request/request.js:1142:14)
npm ERR!     at Request.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/local/node-v0.10.33-linux-x64/lib/node_modules/npm/node_modules/request/request.js:1096:12)
npm ERR!     at IncomingMessage.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:943:16
npm ERR!     at process._tickCallback (node.js:419:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 2.6.32-431.el6.x86_64
npm ERR! command "/usr/local/node-v0.10.33-linux-x64/bin/node" "/usr/local/node-v0.10.33-linux-x64/bin/npm" "publish" "archiver-0.14.4.tgz" "--registry" "http://localhost:8080/nexus/content/repositories/npm-third-party"
npm ERR! cwd /xxx/xxx/xx_user_home/.npm/archiver/0.14.4

npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /xxx/xxx/xx_user_home/.npm/archiver/0.14.4/npm-debug.log
npm ERR! not ok code 0

=======================npm-debug.log=================================
/xxx/xxx/xx_user_home/.npm/archiver/0.14.4/npm-debug.log

cat output/npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/node-v4.2.4-linux-x64/bin/node',
1 verbose cli   '/usr/local/node-v4.2.4-linux-x64/bin/npm',
1 verbose cli   'publish',
1 verbose cli   '--ignore-scripts',
1 verbose cli   './archiver-0.14.4.tgz',
1 verbose cli   '--registry',
1 verbose cli   'http://localhost:8080/nexus/content/repositories/npm-third-party' ]
2 info using npm@2.14.12
3 info using node@v4.2.4
4 verbose publish [ './archiver-0.14.4.tgz' ]
5 silly cache add args [ './archiver-0.14.4.tgz', null ]
6 verbose cache add spec ./archiver-0.14.4.tgz
7 silly cache add parsed spec Result {
7 silly cache add   raw: './archiver-0.14.4.tgz',
7 silly cache add   scope: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: './archiver-0.14.4.tgz',
7 silly cache add   spec: '/opt/maestrodata/maestro_user_home/npmmanager/third-party-publisher/output/archiver-0.14.4.tgz',
7 silly cache add   type: 'local' }
8 silly addLocalTarball shasum (computed) 5b9ddb9f5ee1ceef21cb8f3b020e6240ecb4315c
9 verbose addTmpTarball /opt/maestrodata/maestro_user_home/npmmanager/third-party-publisher/output/archiver-0.14.4.tgz not in flight; adding
10 verbose addTmpTarball validating metadata from /opt/maestrodata/maestro_user_home/npmmanager/third-party-publisher/output/archiver-0.14.4.tgz
11 verbose tar unpack /opt/maestrodata/maestro_user_home/npmmanager/third-party-publisher/output/archiver-0.14.4.tgz
12 verbose tar unpacking to /opt/maestrodata/maestro_user_home/npm-working-tmp-files/npm-55462-99999aa1/unpack-2b0c8fb1a3f6
13 silly gentlyRm /opt/maestrodata/maestro_user_home/npm-working-tmp-files/npm-55462-99999aa1/unpack-2b0c8fb1a3f6 is being purged
14 verbose gentlyRm don't care about contents; nuking /opt/maestrodata/maestro_user_home/npm-working-tmp-files/npm-55462-99999aa1/unpack-2b0c8fb1a3f6
15 silly gunzTarPerm modes [ '755', '644' ]
16 silly gunzTarPerm extractEntry package.json
17 silly gunzTarPerm modified mode [ 'package.json', 438, 420 ]
18 silly gunzTarPerm extractEntry README.md
19 silly gunzTarPerm modified mode [ 'README.md', 438, 420 ]
20 silly gunzTarPerm extractEntry LICENSE
21 silly gunzTarPerm modified mode [ 'LICENSE', 438, 420 ]
22 silly gunzTarPerm extractEntry lib/archiver.js
23 silly gunzTarPerm modified mode [ 'lib/archiver.js', 438, 420 ]
24 silly gunzTarPerm extractEntry lib/core.js
25 silly gunzTarPerm modified mode [ 'lib/core.js', 438, 420 ]
26 silly gunzTarPerm extractEntry lib/plugins/json.js
27 silly gunzTarPerm modified mode [ 'lib/plugins/json.js', 438, 420 ]
28 silly gunzTarPerm extractEntry lib/plugins/tar.js
29 silly gunzTarPerm modified mode [ 'lib/plugins/tar.js', 438, 420 ]
30 silly gunzTarPerm extractEntry lib/plugins/zip.js
31 silly gunzTarPerm modified mode [ 'lib/plugins/zip.js', 438, 420 ]
32 silly gunzTarPerm extractEntry lib/util/file.js
33 silly gunzTarPerm modified mode [ 'lib/util/file.js', 438, 420 ]
34 silly gunzTarPerm extractEntry lib/util/index.js
35 silly gunzTarPerm modified mode [ 'lib/util/index.js', 438, 420 ]
36 silly cache afterAdd archiver@0.14.4
37 verbose afterAdd /opt/maestrodata/maestro_user_home/.npm/archiver/0.14.4/package/package.json not in flight; writing
38 verbose afterAdd /opt/maestrodata/maestro_user_home/.npm/archiver/0.14.4/package/package.json written
39 silly publish { name: 'archiver',
39 silly publish   version: '0.14.4',
39 silly publish   description: 'a streaming interface for archive generation',
39 silly publish   homepage: 'https://github.com/archiverjs/node-archiver',
39 silly publish   author: { name: 'Chris Talkington', url: 'http://christalkington.com/' },
39 silly publish   repository:
39 silly publish    { type: 'git',
39 silly publish      url: 'git+https://github.com/archiverjs/node-archiver.git' },
39 silly publish   bugs: { url: 'https://github.com/archiverjs/node-archiver/issues' },
39 silly publish   license: 'MIT',
39 silly publish   main: 'lib/archiver.js',
39 silly publish   files: [ 'lib' ],
39 silly publish   engines: { node: '>= 0.10.0' },
39 silly publish   scripts:
39 silly publish    { test: 'mocha --reporter dot',
39 silly publish      bench: 'node benchmark/simple/pack-zip.js' },
39 silly publish   dependencies:
39 silly publish    { async: '~0.9.0',
39 silly publish      'buffer-crc32': '~0.2.1',
39 silly publish      glob: '~4.3.0',
39 silly publish      lazystream: '~0.1.0',
39 silly publish      lodash: '~3.2.0',
39 silly publish      'readable-stream': '~1.0.26',
39 silly publish      'tar-stream': '~1.1.0',
39 silly publish      'zip-stream': '~0.5.0' },
39 silly publish   devDependencies:
39 silly publish    { chai: '~2.0.0',
39 silly publish      mocha: '~2.1.0',
39 silly publish      rimraf: '~2.2.8',
39 silly publish      mkdirp: '~0.5.0',
39 silly publish      'stream-bench': '~0.1.2',
39 silly publish      tar: '~1.0.3',
39 silly publish      yauzl: '~2.2.1' },
39 silly publish   keywords: [ 'archive', 'archiver', 'stream', 'zip', 'tar' ],
39 silly publish   publishConfig: { registry: 'https://registry.npmjs.org/' },
39 silly publish   readme: '# Archiver v0.14.4 [![Build Status](https://travis-ci.org/archiverjs/node-archiver.svg?branch=master)](https://travis-ci.org/archiverjs/node-archiver)\r\n\r\na streaming interface for archive generation\r\n\r\n[![NPM](https://nodei.co/npm/archiver.png)](https://nodei.co/npm/archiver/)\r\n\r\n## Install\r\n\r\n```bash\r\nnpm install archiver --save\r\n```\r\n\r\nYou can also use `npm install https://github.com/archiverjs/node-archiver/archive/master.tar.gz` to test upcoming versions.\r\n\r\n## Archiver\r\n\r\n#### create(format, options)\r\n\r\nCreates an Archiver instance based on the format (zip, tar, etc) passed. Parameters can be passed directly to `Archiver` constructor for convenience.\r\n\r\n#### registerFormat(format, module)\r\n\r\nRegisters an archive format. Format modules are essentially transform streams with a few required methods. They will be further documented once a formal spec is in place.\r\n\r\n### Instance Methods\r\n\r\nInherits [Transform Stream](http://nodejs.org/api/stream.html#stream_class_stream_transform) methods.\r\n\r\n#### abort()\r\n\r\nAborts the archiving process, taking a best-effort approach, by:\r\n\r\n* removing any pending queue tasks\r\n* allowing any active queue workers to finish\r\n* detaching internal module pipes\r\n* ending both sides of the Transform stream\r\n\r\n*It will NOT drain any remaining sources.*\r\n\r\n#### append(input, data)\r\n\r\nAppends an input source (text string, buffer, or stream) to the instance. When the instance has received, processed, and emitted the input, the `entry` event is fired.\r\n\r\nReplaced `#addFile` in v0.5.\r\n\r\n```js\r\narchive.append(\'string\', { name:\'string.txt\' });\r\narchive.append(new Buffer(\'string\'), { name:\'buffer.txt\' });\r\narchive.append(fs.createReadStream(\'mydir/file.txt\'), { name:\'stream.txt\' });\r\narchive.append(null, { name:\'dir/\' });\r\n```\r\n\r\n#### bulk(mappings)\r\n\r\nAppends multiple entries from passed array of src-dest mappings. A [lazystream](https://github.com/jpommerening/node-lazystream) wrapper is used to prevent issues with open file limits.\r\n\r\nGlobbing patterns are supported through use of the bundled [file-utils](https://github.com/SBoudrias/file-utils) module.\r\n\r\nThe `data` property can be set (per src-dest mapping) to define data for matched entries.\r\n\r\n```js\r\narchive.bulk([\r\n  { src: [\'mydir/**\'], data: { date: new Date() } },\r\n  { expand: true, cwd: \'mydir\', src: [\'**\'], dest: \'newdir\' }\r\n]);\r\n```\r\n\r\nFor more detail on this feature, please see [BULK.md](https://github.com/archiverjs/node-archiver/blob/master/BULK.md).\r\n\r\n#### directory(dirpath[, destpath, data])\r\n\r\nAppends a directory and its files, recusively, given its dirpath. This is meant to be a simplier approach to something previously only possible with `bulk`. The use of `destpath` allows one to define a custom destination path within the resulting archive and `data` allows for setting data on each entry appended.\r\n\r\n```js\r\n// mydir/ -> archive.ext/mydir/\r\narchive.directory(\'mydir\');\r\n\r\n// mydir/ -> archive.ext/abc/\r\narchive.directory(\'mydir\', \'abc\');\r\n\r\n// mydir/ -> archive.ext/\r\narchive.directory(\'mydir\', false, { date: new Date() });\r\n```\r\n\r\n#### file(filepath, data)\r\n\r\nAppends a file given its filepath using a [lazystream](https://github.com/jpommerening/node-lazystream) wrapper to prevent issues with open file limits. When the instance has received, processed, and emitted the file, the `entry` event is fired.\r\n\r\n```js\r\narchive.file(\'mydir/file.txt\', { name:\'file.txt\' });\r\n```\r\n\r\n#### finalize()\r\n\r\nFinalizes the instance and prevents further appending to the archive structure (queue will continue til drained). The `end`, `close` or `finish` events on the destination stream may fire right after calling this method so you should set listeners beforehand to properly detect stream completion.\r\n\r\n*You must call this method to get a valid archive and end the instance stream.*\r\n\r\n#### pointer()\r\n\r\nReturns the current byte length emitted by archiver. Use this in your end callback to log generated size.\r\n\r\n## Events\r\n\r\nInherits [Transform Stream](http://nodejs.org/api/stream.html#stream_class_stream_transform) events.\r\n\r\n#### entry\r\n\r\nFired when the entry\'s input has been processed and appended to the archive. Passes entry data as first argument.\r\n\r\n## Zip\r\n\r\n### Options\r\n\r\n#### comment `string`\r\n\r\nSets the zip comment.\r\n\r\n#### statConcurrency `number`\r\n\r\nSets the number of workers used to process the internal fs stat queue. Defaults to 4.\r\n\r\n#### store `boolean`\r\n\r\nIf true, all entries will be archived without compression. Defaults to `false`.\r\n\r\n#### zlib `object`\r\n\r\nPassed to node\'s [zlib](http://nodejs.org/api/zlib.html#zlib_options) module to control compression. Options may vary by node version.\r\n\r\n### Entry Data\r\n\r\n#### name `string` `required`\r\n\r\nSets the entry name including internal path.\r\n\r\n#### date `string|Date`\r\n\r\nSets the entry date. This can be any valid date string or instance. Defaults to current time in locale.\r\n\r\nWhen using the `bulk` or `file` methods, fs stat data is used as the default value.\r\n\r\n#### store `boolean`\r\n\r\nIf true, this entry will be archived without compression. Defaults to global `store` option.\r\n\r\n#### comment `string`\r\n\r\nSets the entry comment.\r\n\r\n#### mode `number`\r\n\r\nSets the entry permissions. Defaults to octal 0755 (directory) or 0644 (file).\r\n\r\nWhen using the `bulk` or `file` methods, fs stat data is used as the default value.\r\n\r\n#### stats `fs.Stats`\r\n\r\nSets the fs stat data for this entry. This allows for reduction of fs stat calls when stat data is already known.\r\n\r\n## Tar\r\n\r\n### Options\r\n\r\n#### gzip `boolean`\r\n\r\nCompresses the tar archive using gzip, default is false.\r\n\r\n#### gzipOptions `object`\r\n\r\nPassed to node\'s [zlib](http://nodejs.org/api/zlib.html#zlib_options) module to control compression. Options may vary by node version.\r\n\r\n#### statConcurrency `number`\r\n\r\nSets the number of workers used to process the internal fs stat queue. Defaults to 4.\r\n\r\n### Entry Data\r\n\r\n#### name `string` `required`\r\n\r\nSets the entry name including internal path.\r\n\r\n#### date `string|Date`\r\n\r\nSets the entry date. This can be any valid date string or instance. Defaults to current time in locale.\r\n\r\nWhen using the `bulk` or `file` methods, fs stat data is used as the default value.\r\n\r\n#### mode `number`\r\n\r\nSets the entry permissions. Defaults to octal 0755 (directory) or 0644 (file).\r\n\r\nWhen using the `bulk` or `file` methods, fs stat data is used as the default value.\r\n\r\n#### stats `fs.Stats`\r\n\r\nSets the fs stat data for this entry. This allows for reduction of fs stat calls when stat data is already known.\r\n\r\n## Custom Formats\r\n\r\nArchiver ships with out of the box support for TAR and ZIP archives. You can register additional formats with `registerFormat`.\r\n\r\n## Libraries\r\n\r\nArchiver makes use of several libraries/modules to avoid duplication of efforts.\r\n\r\n- [zip-stream](https://npmjs.org/package/zip-stream)\r\n- [tar-stream](https://npmjs.org/package/tar-stream)\r\n\r\n## Things of Interest\r\n\r\n- [Examples](https://github.com/archiverjs/node-archiver/blob/master/examples)\r\n- [Changelog](https://github.com/archiverjs/node-archiver/releases)\r\n- [Contributing](https://github.com/archiverjs/node-archiver/blob/master/CONTRIBUTING.md)\r\n- [MIT License](https://github.com/archiverjs/node-archiver/blob/master/LICENSE-MIT)',
39 silly publish   readmeFilename: 'README.md',
39 silly publish   _id: 'archiver@0.14.4',
39 silly publish   _shasum: '5b9ddb9f5ee1ceef21cb8f3b020e6240ecb4315c',
39 silly publish   _resolved: 'file:output/archiver-0.14.4.tgz',
39 silly publish   _from: 'output/archiver-0.14.4.tgz' }
40 info prepublish archiver@0.14.4
41 verbose getPublishConfig { registry: 'https://registry.npmjs.org/' }
42 silly mapToRegistry name archiver
43 silly mapToRegistry using default registry
44 silly mapToRegistry registry https://registry.npmjs.org/
45 silly mapToRegistry uri https://registry.npmjs.org/archiver
46 verbose publish registryBase https://registry.npmjs.org/
47 silly publish uploading /opt/maestrodata/maestro_user_home/.npm/archiver/0.14.4/package.tgz
48 verbose request uri https://registry.npmjs.org/archiver
49 verbose request always-auth set; sending authorization
50 info attempt registry request try #1 at 9:34:18 AM
51 verbose request id 3eefaf74c270eba8
52 http request PUT https://registry.npmjs.org/archiver
53 http 401 https://registry.npmjs.org/archiver
54 verbose headers { 'content-type': 'application/json',
54 verbose headers   'cache-control': 'max-age=300',
54 verbose headers   'content-length': '49',
54 verbose headers   'accept-ranges': 'bytes',
54 verbose headers   date: 'Mon, 30 May 2016 16:34:18 GMT',
54 verbose headers   via: '1.1 varnish',
54 verbose headers   connection: 'keep-alive',
54 verbose headers   'x-served-by': 'cache-lax1420-LAX',
54 verbose headers   'x-cache': 'MISS',
54 verbose headers   'x-cache-hits': '0',
54 verbose headers   'x-timer': 'S1464626058.462971,VS0,VE219',
54 verbose headers   vary: 'Accept-Encoding' }
55 verbose request invalidating /opt/maestrodata/maestro_user_home/.npm/registry.npmjs.org/archiver on PUT
56 error publish Failed PUT 401
57 verbose stack Error: Could not authenticate npmdeploy-test : archiver
57 verbose stack     at makeError (/usr/local/node-v4.2.4-linux-x64/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
57 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/node-v4.2.4-linux-x64/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:252:14)
57 verbose stack     at Request._callback (/usr/local/node-v4.2.4-linux-x64/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
57 verbose stack     at Request.self.callback (/usr/local/node-v4.2.4-linux-x64/lib/node_modules/npm/node_modules/request/request.js:198:22)
57 verbose stack     at emitTwo (events.js:87:13)
57 verbose stack     at Request.emit (events.js:172:7)
57 verbose stack     at Request.<anonymous> (/usr/local/node-v4.2.4-linux-x64/lib/node_modules/npm/node_modules/request/request.js:1082:10)
57 verbose stack     at emitOne (events.js:82:20)
57 verbose stack     at Request.emit (events.js:169:7)
57 verbose stack     at IncomingMessage.<anonymous> (/usr/local/node-v4.2.4-linux-x64/lib/node_modules/npm/node_modules/request/request.js:1009:12)
58 verbose statusCode 401
59 verbose pkgid archiver
60 verbose cwd /opt/maestrodata/maestro_user_home/npmmanager/third-party-publisher/output
61 error Linux 2.6.32-431.el6.x86_64
62 error argv "/usr/local/node-v4.2.4-linux-x64/bin/node" "/usr/local/node-v4.2.4-linux-x64/bin/npm" "publish" "--ignore-scripts" "./archiver-0.14.4.tgz" "--registry" "http://localhost:8080/nexus/content/repositories/npm-third-party"
63 error node v4.2.4
64 error npm  v2.14.12
65 error code E401
66 error Could not authenticate npmdeploy-test : archiver
67 error If you need help, you may report this error at:
67 error     <https://github.com/npm/npm/issues>
68 verbose exit [ 1, true ]

====================================================================
=========================package.json=================================
[maestro@repo1-aedc package]$ cat package.json
{"name":"archiver","version":"0.14.4","description":"a streaming interface for archive generation","homepage":"https://github.com/archiverjs/node-archiver","author":{"name":"Chris Talkington","url":"http://christalkington.com/"},"repository":{"type":"git","url":"git+https://github.com/archiverjs/node-archiver.git"},"bugs":{"url":"https://github.com/archiverjs/node-archiver/issues"},"license":"MIT","main":"lib/archiver.js","files":["lib"],"engines":{"node":">= 0.10.0"},"scripts":{"test":"mocha --reporter dot","bench":"node benchmark/simple/pack-zip.js"},"dependencies":{"async":"~0.9.0","buffer-crc32":"~0.2.1","glob":"~4.3.0","lazystream":"~0.1.0","lodash":"~3.2.0","readable-stream":"~1.0.26","tar-stream":"~1.1.0","zip-stream":"~0.5.0"},"devDependencies":{"chai":"~2.0.0","mocha":"~2.1.0","rimraf":"~2.2.8","mkdirp":"~0.5.0","stream-bench":"~0.1.2","tar":"~1.0.3","yauzl":"~2.2.1"},"keywords":["archive","archiver","stream","zip","tar"],"publishConfig":{"registry":"https://registry.npmjs.org/"},"readme":"# Archiver v0.14.4 [![Build Status](https://travis-ci.org/archiverjs/node-archiver.svg?branch=master)](https://travis-ci.org/archiverjs/node-archiver)\r\n\r\na streaming interface for archive generation\r\n\r\n[![NPM](https://nodei.co/npm/archiver.png)](https://nodei.co/npm/archiver/)\r\n\r\n## Install\r\n\r\n```bash\r\nnpm install archiver --save\r\n```\r\n\r\nYou can also use `npm install https://github.com/archiverjs/node-archiver/archive/master.tar.gz` to test upcoming versions.\r\n\r\n## Archiver\r\n\r\n#### create(format, options)\r\n\r\nCreates an Archiver instance based on the format (zip, tar, etc) passed. Parameters can be passed directly to `Archiver` constructor for convenience.\r\n\r\n#### registerFormat(format, module)\r\n\r\nRegisters an archive format. Format modules are essentially transform streams with a few required methods. They will be further documented once a formal spec is in place.\r\n\r\n### Instance Methods\r\n\r\nInherits [Transform Stream](http://nodejs.org/api/stream.html#stream_class_stream_transform) methods.\r\n\r\n#### abort()\r\n\r\nAborts the archiving process, taking a best-effort approach, by:\r\n\r\n* removing any pending queue tasks\r\n* allowing any active queue workers to finish\r\n* detaching internal module pipes\r\n* ending both sides of the Transform stream\r\n\r\n*It will NOT drain any remaining sources.*\r\n\r\n#### append(input, data)\r\n\r\nAppends an input source (text string, buffer, or stream) to the instance. When the instance has received, processed, and emitted the input, the `entry` event is fired.\r\n\r\nReplaced `#addFile` in v0.5.\r\n\r\n```js\r\narchive.append('string', { name:'string.txt' });\r\narchive.append(new Buffer('string'), { name:'buffer.txt' });\r\narchive.append(fs.createReadStream('mydir/file.txt'), { name:'stream.txt' });\r\narchive.append(null, { name:'dir/' });\r\n```\r\n\r\n#### bulk(mappings)\r\n\r\nAppends multiple entries from passed array of src-dest mappings. A [lazystream](https://github.com/jpommerening/node-lazystream) wrapper is used to prevent issues with open file limits.\r\n\r\nGlobbing patterns are supported through use of the bundled [file-utils](https://github.com/SBoudrias/file-utils) module.\r\n\r\nThe `data` property can be set (per src-dest mapping) to define data for matched entries.\r\n\r\n```js\r\narchive.bulk([\r\n  { src: ['mydir/**'], data: { date: new Date() } },\r\n  { expand: true, cwd: 'mydir', src: ['**'], dest: 'newdir' }\r\n]);\r\n```\r\n\r\nFor more detail on this feature, please see [BULK.md](https://github.com/archiverjs/node-archiver/blob/master/BULK.md).\r\n\r\n#### directory(dirpath[, destpath, data])\r\n\r\nAppends a directory and its files, recusively, given its dirpath. This is meant to be a simplier approach to something previously only possible with `bulk`. The use of `destpath` allows one to define a custom destination path within the resulting archive and `data` allows for setting data on each entry appended.\r\n\r\n```js\r\n// mydir/ -> archive.ext/mydir/\r\narchive.directory('mydir');\r\n\r\n// mydir/ -> archive.ext/abc/\r\narchive.directory('mydir', 'abc');\r\n\r\n// mydir/ -> archive.ext/\r\narchive.directory('mydir', false, { date: new Date() });\r\n```\r\n\r\n#### file(filepath, data)\r\n\r\nAppends a file given its filepath using a [lazystream](https://github.com/jpommerening/node-lazystream) wrapper to prevent issues with open file limits. When the instance has received, processed, and emitted the file, the `entry` event is fired.\r\n\r\n```js\r\narchive.file('mydir/file.txt', { name:'file.txt' });\r\n```\r\n\r\n#### finalize()\r\n\r\nFinalizes the instance and prevents further appending to the archive structure (queue will continue til drained). The `end`, `close` or `finish` events on the destination stream may fire right after calling this method so you should set listeners beforehand to properly detect stream completion.\r\n\r\n*You must call this method to get a valid archive and end the instance stream.*\r\n\r\n#### pointer()\r\n\r\nReturns the current byte length emitted by archiver. Use this in your end callback to log generated size.\r\n\r\n## Events\r\n\r\nInherits [Transform Stream](http://nodejs.org/api/stream.html#stream_class_stream_transform) events.\r\n\r\n#### entry\r\n\r\nFired when the entry's input has been processed and appended to the archive. Passes entry data as first argument.\r\n\r\n## Zip\r\n\r\n### Options\r\n\r\n#### comment `string`\r\n\r\nSets the zip comment.\r\n\r\n#### statConcurrency `number`\r\n\r\nSets the number of workers used to process the internal fs stat queue. Defaults to 4.\r\n\r\n#### store `boolean`\r\n\r\nIf true, all entries will be archived without compression. Defaults to `false`.\r\n\r\n#### zlib `object`\r\n\r\nPassed to node's [zlib](http://nodejs.org/api/zlib.html#zlib_options) module to control compression. Options may vary by node version.\r\n\r\n### Entry Data\r\n\r\n#### name `string` `required`\r\n\r\nSets the entry name including internal path.\r\n\r\n#### date `string|Date`\r\n\r\nSets the entry date. This can be any valid date string or instance. Defaults to current time in locale.\r\n\r\nWhen using the `bulk` or `file` methods, fs stat data is used as the default value.\r\n\r\n#### store `boolean`\r\n\r\nIf true, this entry will be archived without compression. Defaults to global `store` option.\r\n\r\n#### comment `string`\r\n\r\nSets the entry comment.\r\n\r\n#### mode `number`\r\n\r\nSets the entry permissions. Defaults to octal 0755 (directory) or 0644 (file).\r\n\r\nWhen using the `bulk` or `file` methods, fs stat data is used as the default value.\r\n\r\n#### stats `fs.Stats`\r\n\r\nSets the fs stat data for this entry. This allows for reduction of fs stat calls when stat data is already known.\r\n\r\n## Tar\r\n\r\n### Options\r\n\r\n#### gzip `boolean`\r\n\r\nCompresses the tar archive using gzip, default is false.\r\n\r\n#### gzipOptions `object`\r\n\r\nPassed to node's [zlib](http://nodejs.org/api/zlib.html#zlib_options) module to control compression. Options may vary by node version.\r\n\r\n#### statConcurrency `number`\r\n\r\nSets the number of workers used to process the internal fs stat queue. Defaults to 4.\r\n\r\n### Entry Data\r\n\r\n#### name `string` `required`\r\n\r\nSets the entry name including internal path.\r\n\r\n#### date `string|Date`\r\n\r\nSets the entry date. This can be any valid date string or instance. Defaults to current time in locale.\r\n\r\nWhen using the `bulk` or `file` methods, fs stat data is used as the default value.\r\n\r\n#### mode `number`\r\n\r\nSets the entry permissions. Defaults to octal 0755 (directory) or 0644 (file).\r\n\r\nWhen using the `bulk` or `file` methods, fs stat data is used as the default value.\r\n\r\n#### stats `fs.Stats`\r\n\r\nSets the fs stat data for this entry. This allows for reduction of fs stat calls when stat data is already known.\r\n\r\n## Custom Formats\r\n\r\nArchiver ships with out of the box support for TAR and ZIP archives. You can register additional formats with `registerFormat`.\r\n\r\n## Libraries\r\n\r\nArchiver makes use of several libraries/modules to avoid duplication of efforts.\r\n\r\n- [zip-stream](https://npmjs.org/package/zip-stream)\r\n- [tar-stream](https://npmjs.org/package/tar-stream)\r\n\r\n## Things of Interest\r\n\r\n- [Examples](https://github.com/archiverjs/node-archiver/blob/master/examples)\r\n- [Changelog](https://github.com/archiverjs/node-archiver/releases)\r\n- [Contributing](https://github.com/archiverjs/node-archiver/blob/master/CONTRIBUTING.md)\r\n- [MIT License](https://github.com/archiverjs/node-archiver/blob/master/LICENSE-MIT)","readmeFilename":"README.md","_id":"archiver@0.14.4","_shasum":"5b9ddb9f5ee1ceef21cb8f3b020e6240ecb4315c","_resolved":"file:output/archiver-0.14.4.tgz","_from":"output/archiver-0.14.4.tgz"}
===============================x=====================================

Please guide me, for this artifact im not able to publish it.... attached error logs and json file.

**Comment by KenanY** [comment]
@onkarojha77 Are you still experiencing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
