### ISSUE TITLE
unmet peer dependencies

### ISSUE THREAD

**Issue by taanyadps** [npm/npm#12906]
![grunterr](https://cloud.githubusercontent.com/assets/11797129/15670150/7ee06216-2741-11e6-8d3e-7dd2a62d4ac6.png)

I am getting this error when i am running the command npm install grunt-contrib and it says there are some unmet dependencies and some plugins are extraneous and it could install none of them . How to resolve this issue?

**Comment by taanyadps** [comment]
![grunterr2](https://cloud.githubusercontent.com/assets/11797129/15670396/caa40ddc-2742-11e6-9061-037c0945c7ac.png)
This is the rest of them

**Comment by joedragons** [comment]
Maybe this helps? http://stackoverflow.com/questions/35738346/how-to-solve-npm-unmet-peer-dependency
