### ISSUE TITLE
Does npm support Shadowsocks' PAC mode?

### ISSUE THREAD

**Issue by Loyalsoldier** [npm/npm#12907]
I'm from China. You know there is the GFW. I use shadowsocks for my network proxy and it's great  working under the PAC mode. I also use a npm registry called `taobao` in China because using npm through shadowsocks somehow is not very stable all the time.

Now I have a problem:
1. I use taobao as the default npm registry which is slow under the shadowsocks proxy
2. then I just access the taobao registry directly
3. however, it often comes across some npm packages like [phantomjs-prebuilt](https://github.com/Medium/phantomjs) that need to download tarball files from Amazon AWS as well as github.com, which must access to through Shadowsocks proxy or it would be very slow.

So, does npm support PAC mode?
I need to directly access to taobao registry to download npm packages while downloading tarball files from Shadowsocks PAC mode proxy.(Less use of Shadowsocks proxy is better due to its unstability.)

**Comment by RunningV** [comment]
I have the same problem:question:. My company forbid the networks from alibaba、jd、qq and so on. So i can't use tabbao proxy cnpm. Then i buy a Shadowsockes account but i found i couldn't use it download node_modules from npm official too. what should i do ???:cry::dog:

**Comment by Loyalsoldier** [comment]
@RunningV You should use [Yarn](https://github.com/yarnpkg/yarn) instead of npm and you should use a third-party shadowsocks client [MEOW](https://github.com/renzhn/MEOW). I wrote a blog post about using MEOW step by step here: https://www.loyalsoldier.me/an-easy-guideline-to-fuck-the-gfw/ . I think you should read it.
