### ISSUE TITLE
no comments possible in package.json

### ISSUE THREAD

**Issue by fvanderwielen** [npm/npm#12902]
I would like to state WHY certain things are as they are in my package,json, but it is not possible to place comments explaining this. 

This would help me help others participating in my projects a lot, because then they will not run into the same underlying issues as I have. Therefore it improves participation in modules greatly from my perspective.

**Comment by KenanY** [comment]
Very unlikely that this will ever happen, see the discussions at https://github.com/npm/npm/issues/4482 and https://github.com/npm/read-package-json/pull/46.

**Comment by fvanderwielen** [comment]
@KenanY  Thanks for the quick feedback!

as mentioned here: https://github.com/npm/npm/issues/4482#issuecomment-212010595
it uses JSON.parse is used and a trick like mentioned here http://stackoverflow.com/a/18048155 should work right? I have difficulty finding this in the docs and the code, sorry.

**Comment by KenanY** [comment]
I believe most of the logic is in [`read-package-json`](https://github.com/npm/read-package-json). I'll close this since this request has been made countless times before and the decision has already been made by the development team.
