### ISSUE TITLE
PeerDependencies (plugins for globally installed packages)

### ISSUE THREAD

**Issue by zanona** [npm/npm#12905]
I have created a  [plugin](https://www.npmjs.com/less-plugin-html) for [less](https://www.npmjs.com/package/less) with the intent to be used as:

`lessc --html file.html`

And for this reason was natural for me thinking that I should use a peerDependency of `less@2.x`, however it turns out that when I decided to test the installation it complains about:

`npm WARN less-plugin-html@1.0.0 requires a peer of less@2.x but none was installed.`

However I do have `less@2.71` installed (globally, as expected for my needs) and yet, peer dependency won't acknowledge that. The only way to make it work, is to install `less` locally under the project directory, but that in someway I believe it would defeat the purpose of the plugin?

With NPM 3 not installing peer dependencies as its previous versions, I fail to understand a reason for not acknowledging globally installed peerDependencies in order to proceed with the installation. Specially considering I have `preferGlobal` attribute set to **true** under _package.json_ file.

Would you guys have any considerations about this? 
It was really counter-intuitive for me when facing this issue unexpectedly.

Thanks in advance

**Comment by SimenB** [comment]
If you install both at the same time, no warnings is issued. So I think it's a small bug in the peerDep check, and not intentional behavior.

**Comment by jacksonrayhamilton** [comment]
Also running into this when globally installing a plugin for another module after that other module is already installed globally. Very confusing, since the peer dependency is definitely installed and satisfies the semver range.
