### ISSUE TITLE
Document how to write tests

### ISSUE THREAD

**Issue by schmod** [npm/npm#12908]
NPM needs more tests.

Contributors are [encouraged](https://github.com/npm/npm/wiki/Contributing-Guidelines) to write tests, but there's little documentation describing how NPM's various components should be tested.

The existing suite contains several distinct approaches for writing tests and mocks, at least one of which appears to be deprecated (direct API access, ie. `require('npm').install()` ).  

We have some helpers in `common-tap.js` and a [registry mock](https://github.com/npm/npm-registry-mock), but it isn't clear when these should be used. 

---

We should provide a small guide for writing new tests for NPM, documenting what the current best-practices are, what tools are are available, and provide general guidelines for how to optimize the test-suite for speed and correctness.

**Comment by schmod** [comment]
Some things I've encountered/discovered/pondered as a new contributor:

* The tap tests can be run as standalone scripts.  So cool!  Just run `node test/tap/test-name.js`!
* Debuggers are obviously helpful.  Tools like [iron-node](https://s-a.github.io/iron-node/) work well, particularly because the tests can be run on their own.
    * For some reason, running NPM's tests in iron-node breaks tap's console output.
* How should test-cases be organized?  Are there naming conventions?
* NPM's JS API is undocumented, and appears to be deprecated; even for testing purposes.  Many tests still use it.
* A lot of tests use `common.npm()`.  Is this meant to replace the JS API?  How should it be used?
   * `common.npm()` runs NPM in a new process. Can I attach a debugger to this new process?
* Some tests mock a registry.  Other tests find clever ways to avoid that.  Is there a preferred approach for writing mocks?
* There seem to be a lot of ways to setup/tear-down a test.  NPM's tests never use tap's `beforeEach()`/`afterEach()` helpers.  Why?
* The entire test suite takes a while to run.  Are there well-known performance bottlenecks that new contributors should take care to avoid?
* A few tests create temporary files.  Are there standard conventions for where these should go, or how they should be cleaned up?
   * On a similar note, the content of these files is often provided inline within the test sources.  Does NPM deliberately avoid fixtures?
* Certain behaviors (ie. warning messages) rarely have test coverage.  Is this deliberate?

**Comment by othiym23** [comment]
@iarna had some notes towards a draft of a test-writing guide; I don't think they're much more than chicken-scratches right now, but maybe she could put them in a gist and share them here? Overhauling `CONTRIBUTING.md` and drafting a developer's guide for the CLI are on my list of important things to do, but there are far more things on that list than I can reasonably hope to get to in the immediate future.
