### ISSUE TITLE
missing peerDependencies prevent one from creating shrinkwrap in npm 3

### ISSUE THREAD

**Issue by mgol** [npm/npm#12909]
I thought npm 3 was supposed to solve all peerDependencies problems by always warning if they're missing but otherwise not breaking. Unfortunately, even with npm 3.9.3, `npm shrinkwrap` will still fail if a peerDependency is missing. For example, with the following `package.json`:

``` json
{
  "name": "test",
  "dependencies": {
    "jquery-placeholder": "2.3.1"
  }
}
```

Running `npm install` & then `npm shrinkwrap` results in an error:

```
npm ERR! Darwin 15.5.0
npm ERR! argv "/Users/mgol/.nvm/versions/node/v6.2.0/bin/node" "/Users/mgol/.nvm/versions/node/v6.2.0/bin/npm" "shrinkwrap"
npm ERR! node v6.2.0
npm ERR! npm  v3.9.3

npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! peer invalid: jquery@*, required by jquery-placeholder@2.3.1
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mgol/_/npm-debug.log
```

and no shrinkwrap is created.

I'd expect npm to only warn in such a case as well.

Is there any way to generate shrinkwrap with missing peerDependencies in npm 3?

**Comment by lmaze** [comment]
Same problem here !
Is there a way to make the shrinkwrap work with the peerDependencies ?

**Comment by Vaccano** [comment]
I will add a +1 to this.  It should just be a warning.  

I need a workaround now....

**Comment by tomalex0** [comment]
is there any workaround, for this scenario

**Comment by legodude17** [comment]
The best would be to just install the missing dep.

**Comment by z0d14c** [comment]
i have a package where a listed dependency is out of date, and we are using a more up-to-date version of that dependency. unfortunately shrinkwrap gives us trouble and wants us to list the more out-of-date version in our package.json. would love to be able to ignore the requirement somehow.

**Comment by iammikecohen** [comment]
I'm seeing this with a package that lists Angular 2 as a peer dependency when I use Angular 4. I've tried updating the dependency of the package to `"@angular/core": "^2.0.0 <=4.0.2"` but that errors out as well.

**Comment by mgol** [comment]
@iammikecohen `"@angular/core": "^2.0.0 <=4.0.2"` is effectively the same as `"@angular/core": "^2.0.0"` or `"@angular/core": ">=2.0.0 <3"` so you're using Angular 2, not 4 then.

https://semver.npmjs.com/ can help you to figure out semver ranges.

**Comment by iammikecohen** [comment]
@mgol Thank you, I should have been using `"@angular/core": "^2.2.0 || ~4.0.0"`

**Comment by Rovack** [comment]
@mgol How did you end up solving this?

**Comment by mgol** [comment]
@Rovack I haven't. The only projects in which I used npm shrinkwrap are non-public company projects that have since migrated to Yarn.

I haven't tested it recently but I assume the issue is still there.

**Comment by Rovack** [comment]
It definitely is. Quite surprising, then, that all issues opened around this (e.g [this](https://github.com/npm/npm/issues/10836) and [this](https://github.com/npm/npm/issues/13335)) seem to have been closed with no resolution.
Perhaps the assumption is that no projects use shrinkwrap anymore...

**Comment by tuxracer** [comment]
Issue is definitely still happening `shrinkwrap` is still enforcing peerDependencies that are only a warning on `install`

**Comment by vprasanth** [comment]
I'm going to bump this so the dumbass npm issue bot doesn't auto close it. Using npm 4.6.1 and I can't shrinkwrap since it doesn't ignore the peerDependency warning. It's isn't so that I'm missing the dependency even it's just the package I'm using has stupid strict peerDependency versions.

**Comment by diegopamio** [comment]
I'm also having issues to shrinkwrap when peer dependencies of third parties doesn't get fullfilled.

**Comment by praveen16** [comment]
+1 on the issue. `npm shrinkwrap` fails with invalid peer dependency on transitive dependencies

**Comment by bobpf** [comment]
Having the same issues with npm shrinkwrap

**Comment by httpete** [comment]
same. 

npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! peer invalid: popper.js@^1.11.0, required by bootstrap@4.0.0-beta
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     c:\Users\peters1\bench\um_kb\npm-debug.log

**Comment by garethtalty** [comment]
+1

```
npm ERR! Linux 3.13.0-129-generic
npm ERR! argv "/opt/nvm/versions/node/v6.10.3/bin/node" "/opt/nvm/versions/node/v6.10.3/bin/npm" "shrinkwrap"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10

npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! peer invalid: webpack@^1.12.13 || ^2.1.0-beta.15, required by mocha-webpack@0.7.0
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/gousto2frontend/src/npm-debug.log
```

**Comment by ghost** [comment]
Hi guys, I am facing the same problem as @garethtalty . 
Someone knows how to fix this issue?

**Comment by eswarreddy43** [comment]
+1

**Comment by jesseseligman** [comment]
+1

**Comment by garyjohnson** [comment]
+1

**Comment by mlnj** [comment]
+1

**Comment by STEVEOO6** [comment]
+1 Exactly the same issue as @httpete

**Comment by artyomtrityak** [comment]
+1

**Comment by totorean** [comment]
+1

**Comment by derchirurg** [comment]
+1

**Comment by Mac-lp3** [comment]
+1

**Comment by dillonburns** [comment]
+1

**Comment by raulgg** [comment]
+1

**Comment by envynoiz** [comment]
+1

**Comment by Jones-S** [comment]
+1

**Comment by nassia** [comment]
+1
