### ISSUE TITLE
npm renames .gitignore to .npmignore when packaging

### ISSUE THREAD

**Issue by ChALkeR** [npm/npm#12917]
npm renames `.gitignore` to `.npmignore` if `.npmignore` wasn't present and just excludes `.gitignore` file from package if `.npmignore` is present.

Example:
```
$ ls -a
.  ..  .gitignore  package.json
$ cat .gitignore
$ cat package.json 
{
  "name": "test1",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "author": "",
  "license": "ISC"
}
$ npm pack
test1-1.0.0.tgz
$ tar --list -f test1-1.0.0.tgz 
package/package.json
package/.npmignore
$ touch .npmignore
$ rm test1-1.0.0.tgz
$ ls -a
.  ..  .gitignore  .npmignore  package.json
$ npm pack
test1-1.0.0.tgz
$ tar --list -f test1-1.0.0.tgz 
package/package.json
package/.npmignore
```

It doesn't work even if `.gitignore` is specified in `files` — there seems to be no way to get it inside the package.

This is a duplicate of #3763 (see it for more people being interested), but the resolution on that one does not seem correct to me, because it looks like @domenic thought that it was about the stuff matched by `.gitignore` vs stuff matched by `.npmignore`, not the `.gitignore` files themselves.

Ignoring `.gitignore` file itself isn't documented in https://docs.npmjs.com/files/package.json#files.

**Comment by UltCombo** [comment]
Here's another dupe with more insight about this issue: #7252

**Comment by ChALkeR** [comment]
@UltCombo Ah, sorry. I somewhy didn't find that issue.

**Comment by ChALkeR** [comment]
I think I should close this as a dupe of #7252.
