### ISSUE TITLE
npm issue with Amazon ec2 linux

### ISSUE THREAD

**Issue by anjibodepudi** [npm/npm#12911]
can you please verify this issue 

![npm issue](https://cloud.githubusercontent.com/assets/3363429/15678933/0f28bd24-271e-11e6-868a-b7f936e3bb63.PNG)
![npm issue](https://cloud.githubusercontent.com/assets/3363429/15678945/152c645a-271e-11e6-9e98-ec58a900ba3f.PNG)

**Comment by KenanY** [comment]
@anjibodepudi Node.js v6 and `npm@1` are years old and no longer supported. Please try updating both before asking for any support. Guides on how to update Node.js and `npm` can be found at the [Troubleshooting](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-node) page.

**Comment by KenanY** [comment]
@anjibodepudi It has been a week now with no response from you... are you still seeing this issue after updating both Node.js and `npm` to their latest stable versions?

**Comment by KenanY** [comment]
Closing as abandoned.
