### ISSUE TITLE
npm install fails to install required downstream dependency if an incompatible version is specified as a devDependency

### ISSUE THREAD

**Issue by zetlen** [npm/npm#12915]
When an NPM package declares `async@^0.8.0` in its devDependencies, and one of its hard dependencies requires `async@^1.3.0`, NPM 3 (3.9.5 as of now, but I confirmed this also happens on 3.0.0) will only install `async@0.8.0` at package root. It will fail to install the required `async@^1.3.0` dependency further up the tree.

We found this in a production app, but I created what I think is the simplest possible repro case in [this repository](https://github.com/zetlen/fear-of-npm). Here's a quick repro.

Prerequisites: Node 4.x, NPM 3.x

```sh
git clone https://github.com/zetlen/fear-of-npm
cd fear-of-npm
npm cache clean && npm install
```

That repository is an NPM package which runs a simple testing script in its `prepublish` step, which runs when running a local `npm install`. It shows that the dependency `@jzetlen/depends-on-async1` (a nonce package I made just to demonstrate this) gets the wrong version of `async` at runtime. You can also examine the resolved directory structure to see that `async@^1.3.0` is missing from the dependency.

We've tested:
 - removing the `prepublish` step, which does not fix the problem
 - using a non-scoped package (any module that depends on async>1 would work, try `bundalo`), which does not fix the problem
 - using NPM2, which does not display this behavior because of its different resolution system
 - using local directories as dependency targets, e.g. "depends-on-async1": "../depends-on-async1", which does not reproduce the issue but is not a suitable workaround.

Please let me know if I can provide anything else!

**Comment by ljharb** [comment]
I can repro this - running `npm install` second time appears to work fine.

**Comment by leonyu** [comment]
is this a dupe of #10277?

**Comment by zetlen** [comment]
Sure enough, @leonyu, I think it is! Looks like we're waiting for https://github.com/npm/npm/pull/12811 to go through review. Thanks for finding that!
