### ISSUE TITLE
npm publish / npm owner not working

### ISSUE THREAD

**Issue by jeffreywescott** [npm/npm#12914]
I am the owner / maintainer for [subcli](https://www.npmjs.com/package/subcli). I managed to successfully publish the first version of it with no problems.

Then, I tried to use `npm owner` to add `learnersguild-dev` as a collaborator so that we could publish from that account. After signing-out and signing-in as `learnersguild-dev`, I was unable to publish a new version of the package.

Now I've signed-out and signed-in again as `jeffreywescott` and I cannot even publish a new version of the package from _that_ account. I've signed-in and out multiple times, read all of the previous bug reports for this issue and cannot figure out what I'm doing wrong, which has led me to believe that ... I'm _not_ doing anything wrong.

Please help!

**Comment by jeffreywescott** [comment]
Hmm. For some reason, now things are working. I changed nothing, other than waiting a while.

Is npm caching permissions somewhere? If so, it should be documented, or (better yet) the cache should be invalidated when permissions changed.

**Comment by enlore** [comment]
Were you seeing an `E403` when you tried to publish?

**Comment by jeffreywescott** [comment]
Yep. I had also sent a support email, and it sounds like they cleared the cache.

Seems to me that the cache should be invalidated when permissions change.
