### ISSUE TITLE
npm install failed 

### ISSUE THREAD

**Issue by maniskum** [npm/npm#12918]
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated koa-router@5.0.1: please upgrade to v5.2.1
npm ERR! git clone --template=/.npm/_git-remotes/_templates --mirror git://github.com/azer/left-pad.git /Users/.npm/_git-remotes/git-github-com-azer-left-pad-git-bff80e3ef0db0bfaba7698606c4f623433d14355-2fddc443: Cloning into bare repository '/Users/.npm/_git-remotes/git-github-com-azer-left-pad-git-bff80e3ef0db0bfaba7698606c4f623433d14355-2fddc443'...
npm ERR! git clone --template=/Users/.npm/_git-remotes/_templates --mirror git://github.com/azer/left-pad.git /Users/.npm/_git-remotes/git-github-com-azer-left-pad-git-bff80e3ef0db0bfaba7698606c4f623433d14355-2fddc443: fatal: unable to connect to github.com:
npm ERR! git clone --template=/Users/.npm/_git-remotes/_templates --mirror git://github.com/azer/left-pad.git /Users/.npm/_git-remotes/git-github-com-azer-left-pad-git-bff80e3ef0db0bfaba7698606c4f623433d14355-2fddc443: github.com[0: 192.30.252.129]: errno=Operation timed out
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/Cellar/node/6.2.0/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code 128

npm ERR! Command failed: git clone --template=/Users/.npm/_git-remotes/_templates --mirror git://github.com/azer/left-pad.git /Users/.npm/_git-remotes/git-github-com-azer-left-pad-git-bff80e3ef0db0bfaba7698606c4f623433d14355-2fddc443
npm ERR! Cloning into bare repository '/Users/.npm/_git-remotes/git-github-com-azer-left-pad-git-bff80e3ef0db0bfaba7698606c4f623433d14355-2fddc443'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.129]: errno=Operation timed out

**Comment by steezeburger** [comment]
You should install Pug. Jade is deprecated. Looks like this is trying to install Left-Pad from Azer 😂
