### ISSUE TITLE
npm update -g throw exception : Registry returned 404 for GET on https://registry.npm.taobao.org/npm-debug.log

### ISSUE THREAD

**Issue by erluzi** [npm/npm#12921]
localhost:~ cq$ npm update -g
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/Cellar/node/6.2.0/bin/node" "/usr/local/bin/npm" "update" "-g"
npm ERR! node v6.2.0
npm ERR! npm  v3.9.3
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npm.taobao.org/npm-debug.log
npm ERR! 404 
npm ERR! 404  'npm-debug.log' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/cq/npm-debug.log
localhost:~ cq$

**Comment by biancaglez** [comment]
Did you find a solution? I am having a similar issue.

**Comment by erluzi** [comment]
delete npm-debug.log  that in your npm dir,
