### ISSUE TITLE
Unable to install npm in project file

### ISSUE THREAD

**Issue by ChrisGentile** [npm/npm#12934]
I get error code 128. I tried researching what this is but haven't been too lucky. I've also tried various solutions but nothing has worked. Anyone ever have this error code?

**Comment by KenanY** [comment]
@ChrisGentile Is there a `npm-debug.log` file you can upload to [**gist.github.com**](https://gist.github.com/) and link here?

**Comment by KenanY** [comment]
@ChrisGentile Hi, it has been a week now with no reply from you. Are you still experiencing this issue?

**Comment by ChrisGentile** [comment]
Yes, I'm sorry for the delay. I resubmitted the issue under github.com/typings/typings/issues/581

**Comment by KenanY** [comment]
Closing since this is not an issue with `npm`.
