### ISSUE TITLE
npm ERR! Invalid protocol: null

### ISSUE THREAD

**Issue by kanutsananlive** [npm/npm#12939]
"C:\Program Files\nodejs\npm.cmd" "install"
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9

npm ERR! Invalid protocol: null
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Workstation\nodejs\readdig\api\npm-debug.log
Done.

**Comment by kanutsananlive** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@3.8.9
3 info using node@v6.2.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly install normalizeTree
8 silly loadCurrentTree Finishing
9 silly loadIdealTree Starting
10 silly install loadIdealTree
11 silly cloneCurrentTree Starting
12 silly install cloneCurrentTreeToIdealTree
13 silly cloneCurrentTree Finishing
14 silly loadShrinkwrap Starting
15 silly install loadShrinkwrap
16 silly loadShrinkwrap Finishing
17 silly loadAllDepsIntoIdealTree Starting
18 silly install loadAllDepsIntoIdealTree
19 silly fetchNamedPackageData mongoose
20 silly mapToRegistry name mongoose
21 silly mapToRegistry using default registry
22 silly mapToRegistry registry http://registry.npmjs.org/
23 silly mapToRegistry data Result {
23 silly mapToRegistry   raw: 'mongoose',
23 silly mapToRegistry   scope: null,
23 silly mapToRegistry   name: 'mongoose',
23 silly mapToRegistry   rawSpec: '',
23 silly mapToRegistry   spec: 'latest',
23 silly mapToRegistry   type: 'tag' }
24 silly mapToRegistry uri http://registry.npmjs.org/mongoose
25 verbose request uri http://registry.npmjs.org/mongoose
26 verbose request no auth needed
27 info attempt registry request try #1 at 05:12:13
28 verbose request id d62a58db00bb4994
29 http request GET http://registry.npmjs.org/mongoose
30 info retry will retry, error on last attempt: Error: Invalid protocol: null
31 info attempt registry request try #2 at 05:12:23
32 http request GET http://registry.npmjs.org/mongoose
33 info retry will retry, error on last attempt: Error: Invalid protocol: null
34 info attempt registry request try #3 at 05:13:23
35 http request GET http://registry.npmjs.org/mongoose
36 silly fetchPackageMetaData Error: Invalid protocol: null
36 silly fetchPackageMetaData     at Request.init (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:473:31)
36 silly fetchPackageMetaData     at new Request (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:142:8)
36 silly fetchPackageMetaData     at request (C:\Program Files\nodejs\node_modules\npm\node_modules\request\index.js:55:10)
36 silly fetchPackageMetaData     at CachingRegistryClient.makeRequest (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:149:13)
36 silly fetchPackageMetaData     at C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:66:17
36 silly fetchPackageMetaData     at RetryOperation._fn (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\attempt.js:18:5)
36 silly fetchPackageMetaData     at Timeout._onTimeout (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\node_modules\retry\lib\retry_operation.js:49:10)
36 silly fetchPackageMetaData     at tryOnTimeout (timers.js:224:11)
36 silly fetchPackageMetaData     at Timer.listOnTimeout (timers.js:198:5)
36 silly fetchPackageMetaData  error for mongoose@4.4.19 Error: Invalid protocol: null
36 silly fetchPackageMetaData     at Request.init (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:473:31)
36 silly fetchPackageMetaData     at new Request (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:142:8)
36 silly fetchPackageMetaData     at request (C:\Program Files\nodejs\node_modules\npm\node_modules\request\index.js:55:10)
36 silly fetchPackageMetaData     at CachingRegistryClient.makeRequest (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:149:13)
36 silly fetchPackageMetaData     at C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:66:17
36 silly fetchPackageMetaData     at RetryOperation._fn (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\attempt.js:18:5)
36 silly fetchPackageMetaData     at Timeout._onTimeout (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\node_modules\retry\lib\retry_operation.js:49:10)
36 silly fetchPackageMetaData     at tryOnTimeout (timers.js:224:11)
36 silly fetchPackageMetaData     at Timer.listOnTimeout (timers.js:198:5)
37 silly rollbackFailedOptional Starting
38 silly rollbackFailedOptional Finishing
39 silly runTopLevelLifecycles Starting
40 silly runTopLevelLifecycles Finishing
41 silly install printInstalled
42 verbose stack Error: Invalid protocol: null
42 verbose stack     at Request.init (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:473:31)
42 verbose stack     at new Request (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:142:8)
42 verbose stack     at request (C:\Program Files\nodejs\node_modules\npm\node_modules\request\index.js:55:10)
42 verbose stack     at CachingRegistryClient.makeRequest (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:149:13)
42 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:66:17
42 verbose stack     at RetryOperation._fn (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\attempt.js:18:5)
42 verbose stack     at Timeout._onTimeout (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\node_modules\retry\lib\retry_operation.js:49:10)
42 verbose stack     at tryOnTimeout (timers.js:224:11)
42 verbose stack     at Timer.listOnTimeout (timers.js:198:5)
43 verbose cwd D:\Workstation\nodejs\readdig\api
44 error Windows_NT 6.1.7601
45 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
46 error node v6.2.0
47 error npm  v3.8.9
48 error Invalid protocol: null
49 error If you need help, you may report this error at:
49 error     <https://github.com/npm/npm/issues>
50 verbose exit [ 1, true ]

**Comment by CSchulz** [comment]
The most important part is the `proxy = http://registry.npmjs.org/`.

Same issue with own registry, you have to set both options (registry and proxy).

**Comment by LiuSuY** [comment]
谢谢你，这个问题困扰了我好久，采用你的方法终于解决了。

**Comment by legodude17** [comment]
Try `npm config set proxy null`.

**Comment by 757470062** [comment]
满篇的英文看见个中文好亲切

**Comment by legodude17** [comment]
Anyone still having this issue?

**Comment by 757470062** [comment]
yes!

**Comment by legodude17** [comment]
Did you try my suggestion?

**Comment by 757470062** [comment]
i set proxy null,it is not work yet！

**Comment by legodude17** [comment]
What are the results of:
1. `npm config get registry`
2. `npm config get http-proxy`
3. `npm config get https-proxy`

**Comment by gayanpathirage** [comment]
My issue is due to windows http_proxy environment variable being set; while I don't use a proxy.

Following command in command prompt will display, if http_proxy is set;

    set http

If set removed the variable with below command and problem solved.

    set http_proxy=

> Above command will remove the http_proxy from the current
> command line. However, if you need to permanently remove it, just
> remove it from System Properties>Advanced Tab>Environment Variables
> dialog box.

**Comment by ibugs961** [comment]
Same issue with private registry(Private npm repository server, https://github.com/rlidwka/sinopia/)
and set
registry=http://your.private.repository/
proxy = http://your.private.repository/
