### ISSUE TITLE
Unable to set up angular 2 

### ISSUE THREAD

**Issue by deepuec** [npm/npm#12932]
Hi,

i am trying to install nodejs as per the below blog.
https://angular.io/docs/ts/latest/quickstart.html

But i am getting some proxy errors.
Below is the attached file. Please have a look

[npm-debug.txt](https://github.com/npm/npm/files/295707/npm-debug.txt)

**Comment by KenanY** [comment]
Hi @deepuec! From the log, I see many errors indicating that you need to authenticate yourself before using your proxy. Have you done so? This isn't something that is the fault of `npm`.

**Comment by deepuec** [comment]
Hi Kenan,
Do u know how to authenticate for the proxy?

**Comment by KenanY** [comment]
@deepuec You can try setting the [`proxy`](https://docs.npmjs.com/misc/config#proxy), [`https-proxy`](https://docs.npmjs.com/misc/config#https-proxy), and [`cafile`](https://docs.npmjs.com/misc/config#cafile) configs.

**Comment by KenanY** [comment]
@deepuec Just following up since it has been over a week now: are you still experiencing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.

**Comment by deepuec** [comment]
@KenanY 
Issue has been resolved after adding proxy
**npm config set proxy http://username:password@proxyhost:port/**

Thanks for your help.
