### ISSUE TITLE
run a project on github without npm start

### ISSUE THREAD

**Issue by MariusGarbea** [npm/npm#12935]
Hi! Is there any way I could run my page on gh-pages without manually starting the server with npm start? Thanks!

**Comment by KenanY** [comment]
@MariusGarbea GitHub pages is just a static host. Whatever files you have in your `gh-pages` branch get hosted. There should be no need to run your own server at all; in fact, I do not think that is supported at all.

**Comment by MariusGarbea** [comment]
@KenanY Thanks for the info! Then how can I use my webpack.config file?

**Comment by KenanY** [comment]
@MariusGarbea Just bundle your js locally with webpack then commit the bundled js to the `gh-pages` branch and it should be served.

**Comment by MariusGarbea** [comment]
@KenanY I cannot make it work out. I would be grateful if you could help me out. I'm a beginner.
Here is my webpack.config: 

`module.exports = {
  entry: './main.js',
  output: {
    path: './',
    filename: 'index.js'
  },
  devServer: {
    inline: true,
    port: 6969
  },
  module: {
    loaders: [
      {
        test:/\.js$/,
        exclude: /node_modules/,
        loader: 'babel',
        query: {
          presets: ['es2015', 'react']
        }
      }
    ]
  }
}`

In index.html I include index.js as script and in package.json I set webpack-dev-server on start.
When I open index.html without starting the server, I get an error (index.js cannot be found). Thanks for your time! :)

**Comment by KenanY** [comment]
@MariusGarbea I'm no webpack expert, but isn't there a way to compile `main.js` into `index.js` without starting a server?

**Comment by MariusGarbea** [comment]
@KenanY Well, I don't know that either. There should be, however, after a lot of research I couldn't find anything useful. I will repost this to webpack's github and hope they will answer as fast as you. :D

**Comment by KenanY** [comment]
Closing as not an issue with `npm`. If I am mistaken I can gladly reopen.
