### ISSUE TITLE
cordova error

### ISSUE THREAD

**Issue by durexdijo** [npm/npm#12938]
When i tried installing Cordova.. This is the error i get... What could be the reason? And again.. I have admin privileges.. How do i solve this as im new here. 

C:\Users>npm install -g cordova
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9

npm ERR! shasum check failed for C:\Users\Dijo\AppData\Local\Temp\npm-16260-5628d4fb\registry.npmjs.org\cordova-app-hello-world\-\cordova-app-hello-world-3.10.0.tgz
npm ERR! Expected: e3825fc6ca950090a6a37437fcfb88c1622fd80e
npm ERR! Actual:   c1d942f3dc0ed01118b73602dae8a88eb02dff5e
npm ERR! From:     https://registry.npmjs.org/cordova-app-hello-world/-/cordova-app-hello-world-3.10.0.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! path C:\Users\npm-debug.log.1379610330
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall open

npm ERR! Error: EPERM: operation not permitted, open 'C:\Users\npm-debug.log.1379610330'
npm ERR!     at Error (native)
npm ERR!  { Error: EPERM: operation not permitted, open 'C:\Users\npm-debug.log.1379610330'
npm ERR!     at Error (native)
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'open',
npm ERR!   path: 'C:\\Users\\npm-debug.log.1379610330' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\npm-debug.log

**Comment by KenanY** [comment]
@durexdijo Have you tried running `npm cache clean`?

**Comment by durexdijo** [comment]
Yeah, seems thats working works.

Thanks man!

**Comment by KenanY** [comment]
Closing as resolved.
