### ISSUE TITLE
sub-dependency esprima-fb doesn't flatten (npm3)

### ISSUE THREAD

**Issue by debugwand** [npm/npm#12947]
I have 3 dependencies that all reference esprima-fb, and the version resolves to 15001.1001.0-dev-harmony-fb for all of them.

I was expecting to see esprima-fb in the top level of node_modules folder, but it isn't there. They are in the node_modules folder of each dependency.  Given the documentation at https://docs.npmjs.com/how-npm-works/npm3 I would expect at least one of the packages to put esprima-fb at the top level of node_modules.

Everything still works, but it means that I cannot successfully ensure that my npm-shrinkwrap.json file is up to date, because the tool I am using expects to find esprima-fb at the top level of npm-shrinkwrap.json dependencies, not nested inside each of the dependencies.

Is this expected behaviour? Is it because there are letters in the version name?

**Comment by SimenB** [comment]
Have you tried running`npm dedupe`? I've noticed that unless I do a clean install, deduping manually is sometimes needed

**Comment by debugwand** [comment]
My approach has been to delete the node_modules folder to get a clean install. I can give dedupe a try.

**Comment by debugwand** [comment]
I gave dedupe a try and esprima-fb is still not going to the top level

The line in dependencies for the 3 affected modules is `"esprima-fb": "~15001.1001.0-dev-harmony-fb"`, so the first thing that comes to mind is wondering how npm will cope with a version number that is alphanumeric rather than numeric.
