### ISSUE TITLE
Wrong arguments when using `npm start -- --foo bar`

### ISSUE THREAD

**Issue by FezVrasta** [npm/npm#12946]
I have asked this question o SO but it seems like a bug to me.

http://stackoverflow.com/questions/37615040/arguments-passed-to-npm-start-are-not-recognized-like-the-ones-passed-using-n

I have a simple npm script:

```
"scripts": {
  "start": "node server.js"
}
```

Inside `server.js` I have:

```
console.log(require('minimist')(process.argv.slice(2)));
```

Running the following commands, these are the outputs:

```
$ npm start -- --test one
{ _: [ 'one' ] }

$ npm run start -- --test one
{ _: [], test: 'one' }
```

The second output is the one I'd like to have when I use `npm start`, why instead I get the first one?

**Comment by KenanY** [comment]
@FezVrasta Thanks for the bug report. What is the output of `npm --version`? I cannot reproduce this with `npm@3.9.5`:

``` bash
$ npm start -- --test one

> @ start
> node server.js "--test" "one"

{ _: [], test: 'one' }

$ npm run start -- --test one

> @ start
> node server.js "--test" "one"

{ _: [], test: 'one' }
```

**Comment by FezVrasta** [comment]
I'm on 3.8.9 actually... I'm updating, then I'll let you know if it get fixed

**Comment by FezVrasta** [comment]
Even with `3.9.5` I get the same problem.

Node is v6.2.0, npm is 3.9.5

**Comment by FezVrasta** [comment]
ok actually seems like the bug occurs with this configuration:

```json
{
  "scripts": {
    "start": "npm run start:dev",
    "start:dev": "node server.js"
  }
}
```

If I put `node server.js` directly inside `start`, it works as expected.

**Comment by KenanY** [comment]
@FezVrasta Oh, in that case you can do

``` bash
$ npm start -- -- --test one

> @ start
> npm run start:dev "--" "--test" "one"


> @ start:dev
> node server.js "--test" "one"

{ _: [], test: 'one' }
```

:smirk: 

But yeah this might be a bug.

**Comment by FezVrasta** [comment]
Yup, it's kinda hard to write in the module documentation:

> If you want to start the app, run `npm start -- -- --remote localhost`
> You can start the app in production mode running `npm run start:prod -- --remote localhost`
> Note the doble `--` in the first command!

:)

**Comment by FezVrasta** [comment]
Is this ticket going to be labelled at least?

**Comment by FezVrasta** [comment]
This is probably one of the most idiotic ways to manage old issues I ever seen. No surprise Yarn is kicking your ass so badly.
