### ISSUE TITLE
npm error parsing json when running npm install -g yo generator-hubot

### ISSUE THREAD

**Issue by nick-lange** [npm/npm#12943]
Using win 8.1x64 with nodejs6.2.1 and npm 3.9.3 I get the attached error log

[npm-debug-log.txt](https://github.com/npm/npm/files/297535/npm-debug-log.txt)

**Comment by busches** [comment]
Looks like your `npm` `registry` is set to `https://github.com/jquery/esprima` which is not a valid registry.

You can confirm by running `npm config get registry`

You can either delete the key to have it go back to the default registry or set it to a correct registry:
`npm config delete registry`
`npm config set registry <registry URL>`

cc\ @KenanY
