### ISSUE TITLE
Error on npm install

### ISSUE THREAD

**Issue by cojarbi** [npm/npm#12945]
This is what i get on OSX

Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.0.0
npm ERR! npm  v3.9.5

npm ERR! No compatible version found: serialport@4.0.x
npm ERR! Valid install targets:
npm ERR! 4.0.0-beta3, 4.0.0-beta2, 4.0.0-beta1, 3.2.0-beta1, 3.1.2, 3.1.2-beta7, 3.1.2-beta6, 3.1.2-beta5, 3.1.2-beta3, 3.1.2-beta2, 3.1.2-beta1, 3.1.1, 3.1.0, 3.0.1, 3.0.0, 2.1.2, 2.1.1, 2.1.0, 2.0.7-beta5, 2.0.7-beta4, 2.0.7-beta3, 2.0.7-beta2, 2.0.7-beta1, 2.0.6, 2.0.5, 2.0.4, 2.0.3, 2.0.2, 2.0.1, 2.0.0, 1.7.4, 1.7.3, 1.7.1, 1.7.0, 1.6.3, 1.6.2, 1.6.1, 1.5.0, 1.4.10, 1.4.9, 1.4.8, 1.4.6, 1.4.5, 1.4.2, 1.4.1, 1.4.0, 1.3.1, 1.3.0, 1.2.5, 1.2.4, 1.2.3, 1.2.2, 1.2.1, 1.2.0, 1.1.3, 1.1.1, 1.1.0, 1.0.8, 1.0.7, 1.0.6, 1.0.5, 1.0.4, 1.0.3, 1.0.2, 1.0.1, 1.0.0, 0.7.5, 0.7.4, 0.7.3, 0.7.2, 0.7.1, 0.7.0, 0.6.7, 0.6.6, 0.6.5, 0.6.3, 0.6.2, 0.6.1, 0.6.0, 0.3.0, 0.2.9, 0.2.8, 0.2.7, 0.2.6, 0.2.5, 0.2.4, 0.2.3, 0.2.2, 0.2.0, 0.1.3, 0.1.1, 0.1.0

**Comment by cojarbi** [comment]
[npm-debug.log.zip](https://github.com/npm/npm/files/297665/npm-debug.log.zip)

**Comment by KenanY** [comment]
Hi @cojarbi! Can I see the `"dependencies"` and `"devDependencies"` portions of your `package.json`? The error log is saying that you are trying to download a version of `serialport` which does not exist.

**Comment by cojarbi** [comment]
@KenanY thanks, here is the complete json file 

{
  "name": "laserweb3",
  "description": "a fully featured web ui for laser cutter/engravers, reprap and other 3d printers",
  "contributors": [
    {
      "name": "Peter van der Walt",
      "email": "peter.plaaswerf@gmail.com"
    }
  ],
  "repository" :
  {
  	"type" : "git",
  	"url" : "https://github.com/openhardwarecoza/LaserWeb3.git"
  },
  "licenses": [
    {
      "type": "AGPL-3.0",
      "url": "http://www.gnu.org/licenses/agpl-3.0.txt"
    }
  ],
  "dependencies": {
    "chalk": "1.x.x",
    "dotenv": "2.x.x",
    "node-static": "0.7.x",
    "serialport": "4.0.x",
    "socket.io": "1.3.x"
  },
  "license": "AGPL-3.0"
}

**Comment by KenanY** [comment]
@cojarbi Thanks! This confirms my suspicion that the issue is that you are depending on a version range of `serialport` which has no matching versions. You are asking for `4.0.x`, but as the error message shows there is no version which matches that (note that the `-beta` versions will not match any version range; this behavior was adding in `npm@2` a while back).

**Comment by cojarbi** [comment]
@KenanY thanks again.

@openhardwarecoza trying to get LW3 running on Mac

**Comment by openhardwarecoza** [comment]
Just pushed an updated package . json 

Or manually install npm serialport@4.0.0-beta3

**Comment by cojarbi** [comment]
@openhardwarecoza thanks just did, works

**Comment by openhardwarecoza** [comment]
Oops yes,  i added -beta,  so then it wont natch with npm.  Manual install it is then
