### ISSUE TITLE
Cannot install pug through npm

### ISSUE THREAD

**Issue by amand1996** [npm/npm#12957]
Cannot install the package 'pug' (previously known as jade) on my Ubuntu 16.04. The Debug log has been attached.
```
sudo npm install pug -g
npm ERR! fetch failed https://registry.npmjs.org/wordwrap/-/wordwrap-0.0.2.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503
npm ERR! fetch failed https://registry.npmjs.org/wordwrap/-/wordwrap-0.0.2.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503
npm ERR! fetch failed https://registry.npmjs.org/wordwrap/-/wordwrap-0.0.2.tgz
npm ERR! Linux 4.4.0-22-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "pug" "-g"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2

npm ERR! fetch failed with status code 503
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/aman/Desktop/Kuvera/npm-debug.log

```

[npm-debug.txt](https://github.com/npm/npm/files/299215/npm-debug.txt)

**Comment by KevinChien** [comment]
I got the same error log just like what you post.
Maybe server has something wrong, keep waiting for...

**Comment by mabusubhani18** [comment]
I am also getting same error. Any work around?

npm WARN retry will retry, error on last attempt: Error: fetch failed with statu
s code 503
npm ERR! fetch failed https://registry.npmjs.org/buffer/-/buffer-4.5.1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with statu
s code 503
npm ERR! fetch failed https://registry.npmjs.org/path-browserify/-/path-browseri
fy-0.0.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with statu
s code 503
npm ERR! fetch failed https://registry.npmjs.org/process/-/process-0.11.2.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with statu
s code 503
npm ERR! fetch failed https://registry.npmjs.org/buffer/-/buffer-4.5.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/os-browserify/-/os-browserify-0
.2.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/path-browserify/-/path-browseri
fy-0.0.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/process/-/process-0.11.2.tgz
npm ERR! Windows_NT 6.1.7600

npm ERR! node v0.10.43
npm ERR! npm  v2.14.22

npm ERR! fetch failed with status code 503
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Meteror_train\meteor\socially\npm-debug.log

**Comment by Obversity** [comment]
I'm getting 503 errors trying to install Sails, as well.

**Comment by rodleviton** [comment]
Same here! Is there an alternate registry mirror?

**Comment by TheIndieCoder** [comment]
I could get rid of the errors with admin privileges. 
Privilege issue ?

**Comment by amand1996** [comment]
No. I m already using the sudo way. There's some other problem I guess.

**Comment by CodinCat** [comment]
I think it's just npm's problem, I can't install other packages as well.

but it's back now, try to install again!

**Comment by CodinCat** [comment]
see: http://status.npmjs.org/incidents/40wxc00d4cgc
