### ISSUE TITLE
installation is not working using npm

### ISSUE THREAD

**Issue by baloda** [npm/npm#12953]
output of  npm init
{
  "name": "app",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}
output of  npm install package-name

npm WARN package.json app@1.0.0 No repository field.
npm WARN package.json app@1.0.0 No README data
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5

npm ERR! Unexpected token <
npm ERR! <HTML>
npm ERR! <HEAD><TITLE>400 Bad Request</TITLE></HEAD>
npm ERR! <BODY BGCOLOR="#cc9999" TEXT="#000000" LINK="#2020ff" VLINK="#4040cc">
npm ERR! <H4>400 Bad Request</H4>
npm ERR! Bad filename.
npm ERR! <HR>
npm ERR! <ADDRESS><A HREF="http://www.acme.com/software/mini_httpd/">mini_httpd/1.19 19dec2003</A></ADDRESS>
npm ERR! </BODY>
npm ERR! </HTML>
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

**Comment by bjskistad** [comment]
You might've missed some indenting?

    {
    "name": "app",
    "version": "1.0.0",
    "description": "",
    "main": "index.js",
    "scripts": {
      "test": "echo \"Error: no test specified\" && exit 1"
    },
    "author": "",
    "license": "ISC"
    }

**Comment by baloda** [comment]
this file is generated by npm init.

**Comment by bjskistad** [comment]
Might be a proxy. Check for your package by going to https://registry.npmjs.com/package

**Comment by bjskistad** [comment]
If it exists it will show up.
