### ISSUE TITLE
Cannot install this particular package - 'thoughts'.

### ISSUE THREAD

**Issue by nirajpandkar** [npm/npm#12956]
`npm install thoughts` is giving an error - 
`fetch failed with status code 503`

What does this error code signify?

Here is the npm debug log - 

0 info it worked if it ends with ok
1 verbose cli [ '/home/niraj/.nvm/versions/node/v5.0.0/bin/node',
1 verbose cli   '/home/niraj/.nvm/versions/node/v5.0.0/bin/npm',
1 verbose cli   'install',
1 verbose cli   'thoughts' ]
2 info using npm@3.3.6
3 info using node@v5.0.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData thoughts
8 silly fetchNamedPackageData thoughts
9 silly mapToRegistry name thoughts
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/thoughts
13 verbose request uri https://registry.npmjs.org/thoughts
14 verbose request no auth needed
15 info attempt registry request try #1 at 11:08:06 AM
16 verbose request using bearer token for auth
17 verbose request id f1b919192f096940
18 verbose etag "33UMUJNA4ZCT2Z64TIQFOLKTZ"
19 http request GET https://registry.npmjs.org/thoughts
20 http 304 https://registry.npmjs.org/thoughts
21 verbose headers { 'cache-control': 'max-age=300',
21 verbose headers   'accept-ranges': 'bytes',
21 verbose headers   date: 'Sun, 05 Jun 2016 05:38:07 GMT',
21 verbose headers   via: '1.1 varnish',
21 verbose headers   connection: 'keep-alive',
21 verbose headers   'x-served-by': 'cache-sin6926-SIN',
21 verbose headers   'x-cache': 'MISS',
21 verbose headers   'x-cache-hits': '0',
21 verbose headers   'x-timer': 'S1465105086.824746,VS0,VE249',
21 verbose headers   vary: 'Accept-Encoding' }
22 silly get cb [ 304,
22 silly get   { 'cache-control': 'max-age=300',
22 silly get     'accept-ranges': 'bytes',
22 silly get     date: 'Sun, 05 Jun 2016 05:38:07 GMT',
22 silly get     via: '1.1 varnish',
22 silly get     connection: 'keep-alive',
22 silly get     'x-served-by': 'cache-sin6926-SIN',
22 silly get     'x-cache': 'MISS',
22 silly get     'x-cache-hits': '0',
22 silly get     'x-timer': 'S1465105086.824746,VS0,VE249',
22 silly get     vary: 'Accept-Encoding' } ]
23 verbose etag https://registry.npmjs.org/thoughts from cache
24 verbose get saving thoughts to /home/niraj/.npm/registry.npmjs.org/thoughts/.cache.json
25 silly install normalizeTree
26 silly loadCurrentTree Finishing
27 silly loadIdealTree Starting
28 silly install loadIdealTree
29 silly cloneCurrentTree Starting
30 silly install cloneCurrentTreeToIdealTree
31 silly cloneCurrentTree Finishing
32 silly loadShrinkwrap Starting
33 silly install loadShrinkwrap
34 silly loadShrinkwrap Finishing
35 silly loadAllDepsIntoIdealTree Starting
36 silly install loadAllDepsIntoIdealTree
37 silly resolveWithNewModule thoughts@2.0.0 checking installable status
38 silly cache add args [ 'thoughts', null ]
39 verbose cache add spec thoughts
40 silly cache add parsed spec Result {
40 silly cache add   raw: 'thoughts',
40 silly cache add   scope: null,
40 silly cache add   name: 'thoughts',
40 silly cache add   rawSpec: '',
40 silly cache add   spec: '*',
40 silly cache add   type: 'range' }
41 silly addNamed thoughts@*
42 verbose addNamed "*" is a valid semver range for thoughts
43 silly addNameRange { name: 'thoughts', range: '*', hasData: false }
44 silly mapToRegistry name thoughts
45 silly mapToRegistry using default registry
46 silly mapToRegistry registry https://registry.npmjs.org/
47 silly mapToRegistry uri https://registry.npmjs.org/thoughts
48 verbose addNameRange registry:https://registry.npmjs.org/thoughts not in flight; fetching
49 verbose get https://registry.npmjs.org/thoughts not expired, no request
50 silly addNameRange number 2 { name: 'thoughts', range: '*', hasData: true }
51 silly addNameRange versions [ 'thoughts', [ '1.0.0', '1.2.0', '1.2.1', '1.2.2', '2.0.0' ] ]
52 silly addNamed thoughts@2.0.0
53 verbose addNamed "2.0.0" is a plain semver version for thoughts
54 silly mapToRegistry name thoughts
55 silly mapToRegistry using default registry
56 silly mapToRegistry registry https://registry.npmjs.org/
57 silly mapToRegistry uri https://registry.npmjs.org/thoughts
58 verbose addRemoteTarball https://registry.npmjs.org/thoughts/-/thoughts-2.0.0.tgz not in flight; adding
59 verbose addRemoteTarball [ 'https://registry.npmjs.org/thoughts/-/thoughts-2.0.0.tgz',
59 verbose addRemoteTarball   '4ad6ed36bc37904132128a4e52d4e5209956f58d' ]
60 info retry fetch attempt 1 at 11:08:07 AM
61 info attempt registry request try #1 at 11:08:07 AM
62 http fetch GET https://registry.npmjs.org/thoughts/-/thoughts-2.0.0.tgz
63 verbose request using bearer token for auth
64 http fetch 503 https://registry.npmjs.org/thoughts/-/thoughts-2.0.0.tgz
65 info retry will retry, error on last attempt: Error: server error 503
66 info attempt registry request try #2 at 11:08:17 AM
67 http fetch GET https://registry.npmjs.org/thoughts/-/thoughts-2.0.0.tgz
68 verbose request using bearer token for auth
69 http fetch 503 https://registry.npmjs.org/thoughts/-/thoughts-2.0.0.tgz
70 info retry will retry, error on last attempt: Error: server error 503
71 info attempt registry request try #3 at 11:09:17 AM
72 http fetch GET https://registry.npmjs.org/thoughts/-/thoughts-2.0.0.tgz
73 verbose request using bearer token for auth
74 http fetch 503 https://registry.npmjs.org/thoughts/-/thoughts-2.0.0.tgz
75 error fetch failed https://registry.npmjs.org/thoughts/-/thoughts-2.0.0.tgz
76 warn retry will retry, error on last attempt: Error: fetch failed with status code 503
77 info retry fetch attempt 2 at 11:09:28 AM
78 info attempt registry request try #1 at 11:09:28 AM
79 http fetch GET https://registry.npmjs.org/thoughts/-/thoughts-2.0.0.tgz
80 verbose request using bearer token for auth
81 http fetch 503 https://registry.npmjs.org/thoughts/-/thoughts-2.0.0.tgz
82 info retry will retry, error on last attempt: Error: server error 503
83 info attempt registry request try #2 at 11:09:38 AM
84 http fetch GET https://registry.npmjs.org/thoughts/-/thoughts-2.0.0.tgz
85 verbose request using bearer token for auth
86 http fetch 503 https://registry.npmjs.org/thoughts/-/thoughts-2.0.0.tgz
87 info retry will retry, error on last attempt: Error: server error 503
88 info attempt registry request try #3 at 11:10:38 AM
89 http fetch GET https://registry.npmjs.org/thoughts/-/thoughts-2.0.0.tgz
90 verbose request using bearer token for auth
91 http fetch 503 https://registry.npmjs.org/thoughts/-/thoughts-2.0.0.tgz
92 error fetch failed https://registry.npmjs.org/thoughts/-/thoughts-2.0.0.tgz
93 warn retry will retry, error on last attempt: Error: fetch failed with status code 503
94 info retry fetch attempt 3 at 11:11:38 AM
95 info attempt registry request try #1 at 11:11:38 AM
96 http fetch GET https://registry.npmjs.org/thoughts/-/thoughts-2.0.0.tgz
97 verbose request using bearer token for auth
98 http fetch 503 https://registry.npmjs.org/thoughts/-/thoughts-2.0.0.tgz
99 info retry will retry, error on last attempt: Error: server error 503
100 info attempt registry request try #2 at 11:11:49 AM
101 http fetch GET https://registry.npmjs.org/thoughts/-/thoughts-2.0.0.tgz
102 verbose request using bearer token for auth
103 http fetch 503 https://registry.npmjs.org/thoughts/-/thoughts-2.0.0.tgz
104 info retry will retry, error on last attempt: Error: server error 503
105 info attempt registry request try #3 at 11:12:49 AM
106 http fetch GET https://registry.npmjs.org/thoughts/-/thoughts-2.0.0.tgz
107 verbose request using bearer token for auth
108 http fetch 503 https://registry.npmjs.org/thoughts/-/thoughts-2.0.0.tgz
109 error fetch failed https://registry.npmjs.org/thoughts/-/thoughts-2.0.0.tgz
110 silly rollbackFailedOptional Starting
111 silly rollbackFailedOptional Finishing
112 silly runTopLevelLifecycles Starting
113 silly runTopLevelLifecycles Finishing
114 silly install printInstalled
115 verbose stack Error: fetch failed with status code 503
115 verbose stack     at Request.<anonymous> (/home/niraj/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/fetch.js:51:14)
115 verbose stack     at emitOne (events.js:77:13)
115 verbose stack     at Request.emit (events.js:169:7)
115 verbose stack     at Request.onRequestResponse (/home/niraj/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/request/request.js:998:10)
115 verbose stack     at emitOne (events.js:77:13)
115 verbose stack     at ClientRequest.emit (events.js:169:7)
115 verbose stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:421:21)
115 verbose stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
115 verbose stack     at TLSSocket.socketOnData (_http_client.js:311:20)
115 verbose stack     at emitOne (events.js:77:13)
116 verbose cwd /home/niraj/WebstormProjects/QuotesExtension
117 error Linux 3.13.0-83-generic
118 error argv "/home/niraj/.nvm/versions/node/v5.0.0/bin/node" "/home/niraj/.nvm/versions/node/v5.0.0/bin/npm" "install" "thoughts"
119 error node v5.0.0
120 error npm  v3.3.6
121 error fetch failed with status code 503
122 error If you need help, you may report this error at:
122 error     <https://github.com/npm/npm/issues>
123 verbose exit [ 1, true ]

**Comment by Obversity** [comment]
I'm getting 503s attempting to install Sails as well.

**Comment by rodleviton** [comment]
I have just started getting 503's when I try and install as well (all packages).

**Comment by nirajpandkar** [comment]
Well this hasn't happened for the first time. This issue https://github.com/npm/npm/issues/4773 from Feb 2014 is the same one. And npm blog had this to say - http://blog.npmjs.org/post/77713120210/four-hours-of-partial-outage-2014-02-24 . Maybe that's what is happening again?

**Comment by zeitgeb3r** [comment]
Melbourne Australia here.
I'm getting the same error.

2016 June 05 06:45 UTC.
2016 June 05 16:45 local time.

npm install --save react-cookie
fetch failed with status code 503

**Comment by sakshamsaxena** [comment]
And yet the registry status is all green... :disappointed:

**Comment by nirajpandkar** [comment]
I guess there is a server outage or a non-responsive connection.

**Comment by nirajk42** [comment]
Use npm install --registry https://registry.nodejitsu.com  
It's working

**Comment by zeitgeb3r** [comment]
npm is now working for me just then.

2016 June 05 07:13 UTC Sunday.
2016 June 05 17:13 local time Sunday.

**Comment by rodleviton** [comment]
Just started working for me then too :)

**Comment by nirajpandkar** [comment]
Started to work for me too :+1:
