### ISSUE TITLE
Cannot install grunt-docco

### ISSUE THREAD

**Issue by znikolovski** [npm/npm#12958]
npm install grunt-docco --save-dev
npm ERR! fetch failed https://registry.npmjs.org/grunt-docco/-/grunt-docco-0.4.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503
npm ERR! fetch failed https://registry.npmjs.org/grunt-docco/-/grunt-docco-0.4.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503
npm ERR! fetch failed https://registry.npmjs.org/grunt-docco/-/grunt-docco-0.4.0.tgz
npm ERR! Darwin 15.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "grunt-docco" "--save-dev"
npm ERR! node v0.12.7
npm ERR! npm  v3.7.1

npm ERR! fetch failed with status code 503

[npm-debug.log.zip](https://github.com/npm/npm/files/299221/npm-debug.log.zip)

**Comment by busches** [comment]
A http status code of `503` is the server is unavailable, are you still facing these issues if you try again today? I'm able to install version `0.4.0` of `grunt-docco` now.
