### ISSUE TITLE
problem with root@raspberrypi:~/.node-red# npm install node-red-contrib-freeboard

### ISSUE THREAD

**Issue by janeksz** [npm/npm#12969]
root@raspberrypi:~/.node-red# npm install node-red-contrib-freeboard
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/freeboard/freeboard.git /root/.npm/_git-remot.
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/freeboard/freeboard.git /root/.npm/_git-remot:
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/freeboard/freeboard.git /root/.npm/_git-remott
npm ERR! Linux 4.1.19-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "node-red-contrib-freeboard"
npm ERR! node v0.12.13
npm ERR! npm  v2.15.0
npm ERR! code 128

npm ERR! Command failed: git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/freeboard/freeboard.git /root9
npm ERR! Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-freeboard-freeboard-git-edbc1d29'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.120]: errno=Connection timed out
npm ERR!
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /root/.node-red/npm-debug.log
root@raspberrypi:~/.node-red#

[npm-debug.txt](https://github.com/npm/npm/files/299802/npm-debug.txt)

**Comment by KenanY** [comment]
@janeksz The "Connection timed out" error indicates that this is a problem with your internet connection rather than with `npm` itself. Make sure that no proxy or firewall is blocking `github.com` or the `git:` protocol.

**Comment by KenanY** [comment]
@janeksz It has been a week now with no response from you. Are you still seeing this issue?

**Comment by janeksz** [comment]
still no luck.
Today it took it home to try (university might have firewalls) and the result is still negative.
Maybe it needs a newer version of nodejs

root@raspberrypi:~/.node-red# npm install node-red-contrib-freeboard
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/freeboard/freeboard.git /root/.npm/_git-remotes/git-github-com-freeboard-freeboard-git-edbc1d29: Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-freeboard-freeboard-git-edbc1d29'...
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/freeboard/freeboard.git /root/.npm/_git-remotes/git-github-com-freeboard-freeboard-git-edbc1d29: fatal: unable to connect to github.com:
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/freeboard/freeboard.git /root/.npm/_git-remotes/git-github-com-freeboard-freeboard-git-edbc1d29: github.com: Name or service not known
npm ERR! Linux 4.1.19-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "node-red-contrib-freeboard"
npm ERR! node v0.12.13
npm ERR! npm  v2.15.0
npm ERR! code 128

npm ERR! Command failed: git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/freeboard/freeboard.git /root/.npm/_git-remotes/git-github-com-freeboard-freeboard-git-edbc1d29
npm ERR! Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-freeboard-freeboard-git-edbc1d29'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com: Name or service not known
npm ERR!
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /root/.node-red/npm-debug.log
root@raspberrypi:~/.node-red#
