### ISSUE TITLE
npm ERR! fetch failed with status code 503

### ISSUE THREAD

**Issue by weeix** [npm/npm#12960]
I tried installing express with:

`npm install express --save`

But got these errors:

> npm ERR! fetch failed https://registry.npmjs.org/express/-/express-4.13.4.tgz
> npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503
> npm ERR! fetch failed https://registry.npmjs.org/express/-/express-4.13.4.tgz
> npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503
> npm ERR! fetch failed https://registry.npmjs.org/express/-/express-4.13.4.tgz
> npm ERR! Windows_NT 6.1.7601
> npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "express" "--save"
> npm ERR! node v4.4.5
> npm ERR! npm  v2.15.5
> 
> npm ERR! fetch failed with status code 503
> npm ERR!
> npm ERR! If you need help, you may report this error at:
> npm ERR!     <https://github.com/npm/npm/issues>
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     C:\Users\WeeIX\Desktop\speedy-quiz\npm-debug.log

I saw "All Systems Operational" in http://status.npmjs.org/

Here is the log file: [npm-debug.zip](https://github.com/npm/npm/files/299226/npm-debug.zip)

**Comment by cheersjosh** [comment]
I'm getting the same problem with numerous packages, namely `react-router` and `react-helmet` but I suspect it's to do with NPM.

**Comment by indraneelr** [comment]
Same here..

**Comment by ruswerner** [comment]
I'm also getting lots of failures with react and related packages now. I'm based in NZ.

**Comment by cheersjosh** [comment]
NPM incident report updated: http://status.npmjs.org

Sydney EC2 outage.

**Comment by nirajpandkar** [comment]
Started working again :+1:

**Comment by weeix** [comment]
I can now install express :ok_hand:

Anyone still having this problem?

**Comment by cheersjosh** [comment]
Seems all good now! 👍🏻

**Comment by lakinmohapatra** [comment]
Once again it happended today.

**Comment by mehultandale** [comment]
Yes, happening right now.

**Comment by AakashIyer** [comment]
Yeah, happening right now.

**Comment by sandy1601** [comment]
i was installing npm and got this
 npm ERR! fetch failed https://registry.npmjs.org/react-tween-state/-/react-tween-state-0.1.5.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503

what to do?

**Comment by savadks95** [comment]
me too got this error
$ npm i
npm ERR! fetch failed https://registry.npmjs.org/react-router-redux/-/react-router-redux-4.0.7.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503
npm ERR! fetch failed https://registry.npmjs.org/react-router-redux/-/react-router-redux-4.0.7.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503
npm ERR! fetch failed https://registry.npmjs.org/react-router-redux/-/react-router-redux-4.0.7.tgz
npm ERR! Linux 4.4.0-45-generic
npm ERR! argv "/home/savad/.nvm/versions/node/v6.6.0/bin/node" "/home/savad/.nvm/versions/node/v6.6.0/bin/npm" "i"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3

npm ERR! fetch failed with status code 503
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/savad/Metacode/GeneratedAPP/ffrrsst/npm-debug.log

**Comment by quanganh1202** [comment]
Got same problem but I have tried on another server and everything's ok.

**Comment by vandananf** [comment]
I got the same issue while installing npm. Is there any way to fix it?

**Comment by Venkat-18** [comment]
Here is the link to get updates about npm server.
http://status.npmjs.org/

**Comment by savadks95** [comment]
Now its working
:)

**Comment by SGissubel** [comment]
I am still getting this ONCE in a while while building in VSTS.  Does not happen every time. But for some reason happens every couple of builds. 

2018-06-25T19:51:54.1785375Z npm ERR! fetch failed https://...privatepackage.../_packaging/Kultera/npm/registry/@angular/http/-/http-5.2.11.tgz
...
2018-06-25T19:51:54.1788768Z  npm ERR! Windows_NT 6.3.9600
2018-06-25T19:51:54.1789012Z npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
2018-06-25T19:51:54.1789236Z npm ERR! node v6.9.1
2018-06-25T19:51:54.1789440Z npm ERR! npm  v3.10.8
2018-06-25T19:51:54.1789587Z 
2018-06-25T19:51:54.1789780Z npm ERR! fetch failed with status code 503
2018-06-25T19:51:54.1789964Z npm ERR!

**Comment by SGissubel** [comment]
https://status.npmjs.org/ -- Says it was fixed on the 13th of June, but I we are still getting this intermittent error.
