### ISSUE TITLE
I need help!

### ISSUE THREAD

**Issue by huzhenjie** [npm/npm#12975]
```
# npm install -g npm
npm ERR! Linux 3.10.0-123.9.3.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "npm"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5

npm ERR! shasum check failed for /tmp/npm-17192-0117da52/registry.npmjs.org/npm/-/npm-3.9.5.tgz
npm ERR! Expected: 64aedc79b46c1855e6dd21fb2ff43666acfae9b0
npm ERR! Actual:   5e108350ed06984222f1fcd5608aff377fa78cd9
npm ERR! From:     https://registry.npmjs.org/npm/-/npm-3.9.5.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

**Comment by KenanY** [comment]
@huzhenjie Have you tried running `npm cache clean`?

**Comment by huzhenjie** [comment]
[root@iZ28llcd5e9Z ~]# npm cache clean
[root@iZ28llcd5e9Z ~]# npm install -g strongloop
npm WARN optional Skipping failed optional dependency /strongloop/strong-debugger:
npm WARN shasum check failed for /tmp/npm-17715-5bfb29dc/registry.npmjs.org/strong-debugger/-/strong-debugger-1.0.0.tgz
npm WARN Expected: f0a1eca5bbad50877475c27fb7dbfaa8eb566c07
npm WARN Actual:   6808d25c84f87d6293fd8bc137c044f1bd4480de
npm WARN From:     https://registry.npmjs.org/strong-debugger/-/strong-debugger-1.0.0.tgz
npm ERR! Linux 3.10.0-123.9.3.el7.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "strongloop"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3

npm ERR! shasum check failed for /tmp/npm-17715-5bfb29dc/registry.npmjs.org/strong-arc/-/strong-arc-1.8.8.tgz
npm ERR! Expected: 690d6fae6d585caa77199b43e441634cdaadcfa4
npm ERR! Actual:   0650524dc365e1e9735a33ac0863a1f61bd194f3
npm ERR! From:     https://registry.npmjs.org/strong-arc/-/strong-arc-1.8.8.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log

**Comment by huzhenjie** [comment]
```
$ wget https://registry.npmjs.org/strong-arc/-/strong-arc-1.8.8.tgz
$ mv strong-arc-1.8.8.tgz /tmp/npm-17715-5bfb29dc/registry.npmjs.org/strong-arc/-/strong-arc-1.8.8.tgz
```

try again

it works
