### ISSUE TITLE
npm shrinkwrap error

### ISSUE THREAD

**Issue by watscho** [npm/npm#12970]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\Development\NodeJS\node.exe',
1 verbose cli   'C:\Development\NodeJS\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'shrinkwrap' ]
2 info using npm@2.15.5
3 info using node@v4.4.5
4 verbose stack Error: Problems were encountered
4 verbose stack Please correct and try again.
4 verbose stack peer invalid: laravel-elixir@6.0.0-2 F:\Localhost\htdocs\facehub\node_modules\laravel-elixir
4 verbose stack     at shrinkwrap_ (C:\Development\NodeJS\node_modules\npm\lib\shrinkwrap.js:37:15)
4 verbose stack     at C:\Development\NodeJS\node_modules\npm\lib\shrinkwrap.js:31:5
4 verbose stack     at C:\Development\NodeJS\node_modules\npm\lib\ls.js:47:30
4 verbose stack     at C:\Development\NodeJS\node_modules\npm\node_modules\read-installed\read-installed.js:142:5
4 verbose stack     at C:\Development\NodeJS\node_modules\npm\node_modules\read-installed\read-installed.js:263:14
4 verbose stack     at cb (C:\Development\NodeJS\node_modules\npm\node_modules\slide\lib\async-map.js:47:24)
4 verbose stack     at C:\Development\NodeJS\node_modules\npm\node_modules\read-installed\read-installed.js:263:14
4 verbose stack     at cb (C:\Development\NodeJS\node_modules\npm\node_modules\slide\lib\async-map.js:47:24)
4 verbose stack     at C:\Development\NodeJS\node_modules\npm\node_modules\read-installed\read-installed.js:263:14
4 verbose stack     at cb (C:\Development\NodeJS\node_modules\npm\node_modules\slide\lib\async-map.js:47:24)
5 verbose cwd F:\Localhost\htdocs\facehub
6 error Windows_NT 10.0.10586
7 error argv "C:\Development\NodeJS\node.exe" "C:\Development\NodeJS\node_modules\npm\bin\npm-cli.js" "shrinkwrap"
8 error node v4.4.5
9 error npm  v2.15.5
10 error Problems were encountered
10 error Please correct and try again.
10 error peer invalid: laravel-elixir@6.0.0-2 F:\Localhost\htdocs\facehub\node_modules\laravel-elixir
11 error If you need help, you may report this error at:
11 error     https://github.com/npm/npm/issues
12 verbose exit [ 1, true ]

**Comment by agrodriguez** [comment]
i have the same problem
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'shrinkwrap' ]
2 info using npm@2.15.1
3 info using node@v4.4.3
4 warn shrinkwrap Excluding devDependency: gulp undefined
5 verbose stack TypeError: Cannot convert undefined or null to object
5 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\shrinkwrap.js:55:39
5 verbose stack     at Array.forEach (native)
5 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\shrinkwrap.js:48:43
5 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:345:5
5 verbose stack     at checkBinReferences_ (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:309:45)
5 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:343:3)
5 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:113:5)
5 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:232:12
5 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
5 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
6 verbose cwd C:\inetpub\wwwsakilav2
7 error Windows_NT 10.0.10586
8 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "shrinkwrap"
9 error node v4.4.3
10 error npm  v2.15.1
11 error Cannot convert undefined or null to object
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]
