### ISSUE TITLE
npm shrinkwrap includes sub dependancies of devDependancies

### ISSUE THREAD

**Issue by sariag** [npm/npm#12972]
I have an example package
`{
  "name": "npm-test",
  "version": "1.0.0",
  "dependencies": {
    "apn": "^1.7.6"
  },
  "devDependencies": {
    "browser-sync": "^2.12.10"
  }
}`

when I do `npm install` then `npm shrinkwrap` the `npm-shrinkwrap.json` file includes `browser-sync-client` which is a dependency of `browser-sync` that is in itself a devDependency and should not be included in the shrinkwrap per the shrinkwrap doc https://docs.npmjs.com/cli/shrinkwrap

npm: 3.9.5
node: 6.2.1

**Comment by andyedwardsdfdl** [comment]
Replicated - I'm seeing the same with `jsdoc` as a devDependency pulling in `bluebird` (and some others) which then ends up in the `npm-shrinkwrap.json` file.

npm: 3.9.5

**Comment by SCdF** [comment]
I have also replicated this. I created a little test repository to help me work out where it broke: https://github.com/SCdF/shrinkwarped

Looks like it was somewhere between `npm 2.14.12 <-> 3.8.5`, or `node 4.2.4 <-> 5.4.0` (not sure which of those versions is the important one.

**Comment by jfmengels** [comment]
I'm reproducing this still with Node v6.5.0 and `npm` 3.10.3.

**Comment by mvila** [comment]
Same issue with Node v6.6.0 and npm v4.0.5.
