### ISSUE TITLE
unable to install onoff module on beaglebone black - code ENOTFOUND  errno ENOTFOUND

### ISSUE THREAD

**Issue by thenaughtychild** [npm/npm#12977]
Hey Sir/Ma'am,
I am unable to install onoff module on beaglebone black using npm. 
Please find below the details of the error and ip config settings:
npm ERR! network getaddrinfo ENOTFOUND
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! System Linux 3.8.13-bone50
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "onoff"
npm ERR! cwd /root
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! syscall getaddrinfo
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /root/npm-debug.log
npm ERR! not ok code 0

root@beaglebone:~# npm config get proxy
null
root@beaglebone:~# npm config get https-proxy
null

root@beaglebone:~# npm -v
1.3.10
root@beaglebone:~# nodejs -v
v0.10.25

**Comment by KenanY** [comment]
@thenaughtychild `npm@1.3` is years old and no longer supported. Please try [updating](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) first.

**Comment by KenanY** [comment]
@thenaughtychild Are you still experiencing this issue with `npm@2` or `npm@3`?

**Comment by KenanY** [comment]
Closing as abandoned.
