### ISSUE TITLE
Unexpected token } in JSON at position 0

### ISSUE THREAD

**Issue by rchoudhary** [npm/npm#12985]
Yesterday I installed the JSDoc package using `npm install -g jsdoc` and used it just fine. Today when I tried to use it again, I got the following error:

```
module.js:96
    throw e;
    ^

SyntaxError: Error parsing ...npm\node_modules\jsdoc\node_modules\requizzle\package.json: Unexpected token } in JSON at position 0
    at Object.parse (native)
    at readPackage (module.js:92:52)
    at tryPackage (module.js:102:13)
    at Function.Module._findPath (module.js:172:20)
    at Function.Module._resolveFilename (module.js:438:25)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
```

I've actually gotten this numerous times before and a clean reinstall of the package fixes it, but I was wondering what keeps causing this error and if a more permanent fix were available.

I am running npm 3.8.9 and node 6.2.0 on Windows

**Comment by rchoudhary** [comment]
**Quick note:** I am on my office laptop.

When I open up the `package.json` file mentioned in the error, it looks like a binary file with a bunch of weird symbols. 

The first character is a `}` which explains the error. Something was messing with my `package.json` files. I suspected that restarting my computer was causing this, because when I installed things, they worked fine. It was only the next day I encountered this error.

To test this, I cleaned out the `node_modules` folder and reinstalled jsdoc with `npm install -g jsdoc`. I checked the `package.json` file: it's all plaintext and looks great.

I then shut down and start up my computer. Not only is the jsdoc `package.json` file obfuscated, _the `package.json` files of all its dependencies are also obfuscated!_ This little bug is recursive!

To test it further, I took the json file, duplicated it and renamed it `PACKAGE_DUP.json` and placed it right next to the original json file. I also took the `node_modules` folder and made a copy called `NODE_MOD_DUP`, again next to the original. So now there are 4 `package.json` files in my npm folder:

1. `node_modules/package.json`
2. `node_modules/PACKAGE_DUP.json`
3. `NODE_MOD_DUP/package.json`
4. `NODE_MOD_DUP/PACKAGE_DUP.json`

When I restarted my computer, the _only_ json file affected was the `package.json` file in the `node_modules` folder (item number 1). So it's being targeted specifically!

Virus scans are coming up clean, and every other json file in the modules folders and on my system as a whole are completely unscathed. Also, the `package.json` files that come with the modules bundled with node work fine. It's only modules installed with `npm install` that are giving me a problem (whether installed globally or locally for that matter).

At this point I no longer suspect this to be an npm issue, however it is frustrating me nonetheless!

**Comment by DavitaMatt** [comment]
Did you ever figure this out? I am also running into this. Did a ton of work on Friday, to come back on Monday, to jacked up Package.json files. Also on laptop. Very frustrating.

**Comment by silvafass** [comment]
I'm also having exactly the same problem, I continually have to remove the node_modules and reinstall the dependencies again.

**Comment by legodude17** [comment]
What OS do all of you have?

**Comment by silvafass** [comment]
Mine is "windows 7 Enterprise, Service Pack 1"

**Comment by DavitaMatt** [comment]
Windows 8.1
I just checked again, as I have been working on other projects.

Here is an example:
C:\Program Files\nodejs\node_modules\grunt\node_modules\minimist\package.json

![node-modules-confuscated](https://cloud.githubusercontent.com/assets/20686747/20441621/434dfadc-ad93-11e6-902f-955177121827.png)

Also, here is my npmrc, with name redacted
[npmrc-example.txt](https://github.com/npm/npm/files/600651/npmrc-example.txt)

**Comment by legodude17** [comment]
That looks really odd. This seems to be only on Windows.

**Comment by sweetpotatoz** [comment]
Windows 8.1
node 6.9.1
npm 3.10.8

The issue described here always happens for my gulp-cli package.json
I installed gulp-cli globally.  i have to npm uninstall -g then install again to resolve this issue.
It seems to happen even though i did not reboot/restart my PC.  Generally happens almost after a day (even no shutdown, no reboot)

SyntaxError: Error parsing C:\Users\<username>\AppData\Roaming\npm\node_modules\gulp-cli\package.json: Unexpected token �
 in JSON at position 0
    at Object.parse (native)
    at readPackage (module.js:92:52)
    at tryPackage (module.js:102:13)
    at Function.Module._findPath (module.js:200:18)
    at Function.Module._resolveFilename (module.js:467:25)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\<username>\AppData\Roaming\npm\node_modules\gulp-cli\bin\gulp.js:5:1)
    at Module._compile (module.js:570:32)

**Comment by legodude17** [comment]
This is not an npm issue, it appears to be a windows bug. Maybe try contacting windows support?

**Comment by shashankvivek** [comment]
Same problem being faced by me too.

**Comment by Robba-JT** [comment]
I encounter the same issuewith all modules installed globally.
I'm on windows 7 professional service pack 1.

**Comment by pearldiver** [comment]
I resolved the problem by open the problematic json in Notepad++ and Menu->Eoncoding->Convert to UTF 8

My issue is caused by the json file contained bom, in windows some tool (e.g. notepad) will save file with a bom by default which is only visible when you use binary editor. this kind of file is not acceptable by npm.

**Comment by sNICkerssss** [comment]
I removed all packages and reinstall them. Such action solved this problem for me.
