### ISSUE TITLE
README.md not published

### ISSUE THREAD

**Issue by ChristianGrete** [npm/npm#12984]
I'm trying to publish a new version of my [module](https://github.com/ChristianGrete/polymer-mustache-template) (using Node.js v6.2.1 and npm v3.9.5) on npm but it seems that the `README.md` file is ignored although it is present, has been updated and is included in the `files` array in `package.json`.

npmjs.com displays the latest `README.md` as well (see https://www.npmjs.com/package/polymer-mustache-template) but when the package has been installed as a dependency, there is no more `README.md` included.

I tried to figure out whether this has something to do with my updated release script and reverted it but I'm still having this problem.

**Comment by ChristianGrete** [comment]
As it seems, this issue has something to do with Node.js v6... It worked fine for me after I downgraded Node.js to v4.4.5 LTS.

**Comment by nsztercsa** [comment]
Hi,

We experience similar issue with out npm package [xively-kinesis-bridge](https://www.npmjs.com/package/xively-kinesis-bridge). No README.md file included when the package is installed as a dependency. However in case of the [urbanjs-tools](https://www.npmjs.com/package/urbanjs-tools) the installed package includes the README.md file. Both packages were deployed using Node.js v6.2.1 and npm v3.9.5.
