### ISSUE TITLE
Some errors has occured while installing jsonc-parser

### ISSUE THREAD

**Issue by teru0915** [npm/npm#12981]
when I launtched vscode(linux) on rasberryPi3,then shows  "Activating extension 'vscode .javascript' failed:Cannot find module 'jsonc-parser'".
So I commanded like below,but some errors has occured. 
What shoud  I do?

pi@raspberrypi:~/vscode $ npm install jsonc-parser
npm http GET https://registry.npmjs.org/jsonc-parser
npm http 304 https://registry.npmjs.org/jsonc-parser
npm http GET https://registry.npmjs.org/vscode-nls
npm http 304 https://registry.npmjs.org/vscode-nls
npm ERR! Error: No compatible version found: vscode-nls@'^1.0.4'
npm ERR! Valid install targets:
npm ERR! ["1.0.0","1.0.1","1.0.2","1.0.3","1.0.4","1.0.5","1.0.6","1.0.7"]
npm ERR!     at installTargetsError (/home/pi/.nodebrew/node/v0.10.0/lib/node_modules/npm/lib/cache.js:682:10)
npm ERR!     at /home/pi/.nodebrew/node/v0.10.0/lib/node_modules/npm/lib/cache.js:597:10
npm ERR!     at saved (/home/pi/.nodebrew/node/v0.10.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:93:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.4.11-v7+
npm ERR! command "/home/pi/.nodebrew/node/v0.10.0/bin/node" "/home/pi/.nodebrew/current/bin/npm" "install" "jsonc-parser"
npm ERR! cwd /home/pi/vscode
npm ERR! node -v v0.10.0
npm ERR! npm -v 1.2.14
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/vscode/npm-debug.log
npm ERR! not ok code 0

**Comment by KenanY** [comment]
@teru0915 `npm@1.2` is years old and no longer supported. Please try [updating](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) first.

Also, it wouldn't hurt to update Node.js as well.

**Comment by KenanY** [comment]
@teru0915 Are you still experiencing this issue with `npm@2` or `npm@3`?

**Comment by KenanY** [comment]
Closing as abandoned.
