### ISSUE TITLE
npm install --time-machine (ignore packages released after a given date)

### ISSUE THREAD

**Issue by jedwards1211** [npm/npm#12994]
Recently I've run into an issue where a new version of some transitive dependency of `babel-eslint` fails to parse Flow parameterized types. Downgrading `babel-eslint` didn't work because the newer versions of the transitive deps are semver-compatible with the older version of `babel-eslint`.

Since a fresh `npm install` worked fine several months ago, if there was a time machine-like feature whereby it would install exactly the same packages as it would have on a specific date several months ago, I should be able to get a working project setup again, because I would get all the older versions of all the transitive dependencies.

I can't think of any simpler way to get a working project setup, because I've lost a working copy with all the old transitive deps that worked.

**Comment by DaveEmmerson** [comment]
@jedwards1211 This would be great... but given it's almost a year later, how did you solve your issue? I'm facing a similar problem and my first thought is to run the dependency list through npm to get versions and release dates (if that's possible) and run them through a script to filter out the newer ones.

**Comment by jedwards1211** [comment]
I did solve it using this fork... You could use it temporarily to install what you need, then shrinkwrap and switch back to official npm.  Let me know if you need help installing/running this fork.

**Comment by DaveEmmerson** [comment]
I don't see the fork in your list of repositories. I can see the other issue referenced and the changes on there, but the fork doesn't show. Any clue? I could try to pull npm from the date of your commits and just apply the changes, but if the fork is still around somewhere that would be easier :)

**Comment by jedwards1211** [comment]
@DaveEmmerson ah sorry, here it is: https://github.com/jedwards1211/npm/tree/time-machine

**Comment by DaveEmmerson** [comment]
Thanks. I managed to sort it, although I ended up using a script to
reinstall all the deps at the versions listed, just by removing the ^.

Hopefully the link helps someone else looking. Sorry to trouble you :)
