### ISSUE TITLE
Error running npm install

### ISSUE THREAD

**Issue by charleszardo** [npm/npm#12990]
I am getting the following message upon running npm install:

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/Cellar/node/6.2.1/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.5

npm ERR! No compatible version found: graceful-fs@undefined4.1.4
npm ERR! Valid install targets:
npm ERR! 4.1.4, 4.1.3, 4.1.2, 4.1.1, 4.1.0, 3.0.8, 3.0.7, 3.0.6, 3.0.5, 3.0.4, 3.0.3, 3.0.2, 3.0.1, 3.0.0, 2.0.3, 2.0.2, 2.0.1, 2.0.0, 1.2.3, 1.2.2, 1.2.1, 1.2.0, 1.1.14, 1.1.13, 1.1.12, 1.1.11, 1.1.10, 1.1.9, 1.1.8, 1.1.7, 1.1.6, 1.1.5, 1.1.4, 1.1.3, 1.1.2, 1.1.1, 1.1.0, 1.0.2, 1.0.1, 1.0.0

Here's the npm-debug log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/6.2.1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install' ]
2 info using npm@3.9.5
3 info using node@v6.2.1
4 verbose config Skipping project config: /Users/dave.charnuska/.npmrc. (matches userconfig)
5 silly loadCurrentTree Starting
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 silly install normalizeTree
9 silly loadCurrentTree Finishing
10 silly loadIdealTree Starting
11 silly install loadIdealTree
12 silly cloneCurrentTree Starting
13 silly install cloneCurrentTreeToIdealTree
14 silly cloneCurrentTree Finishing
15 silly loadShrinkwrap Starting
16 silly install loadShrinkwrap
17 silly loadShrinkwrap Finishing
18 silly loadAllDepsIntoIdealTree Starting
19 silly install loadAllDepsIntoIdealTree
20 silly fetchNamedPackageData graceful-fs
21 silly mapToRegistry name graceful-fs
22 silly mapToRegistry using default registry
23 silly mapToRegistry registry https://registry.npmjs.org/
24 silly mapToRegistry data Result {
24 silly mapToRegistry   raw: 'graceful-fs',
24 silly mapToRegistry   scope: null,
24 silly mapToRegistry   name: 'graceful-fs',
24 silly mapToRegistry   rawSpec: '',
24 silly mapToRegistry   spec: 'latest',
24 silly mapToRegistry   type: 'tag' }
25 silly mapToRegistry uri https://registry.npmjs.org/graceful-fs
26 verbose request uri https://registry.npmjs.org/graceful-fs
27 verbose request no auth needed
28 info attempt registry request try #1 at 3:43:34 PM
29 verbose request id c4b75d868c794fa9
30 verbose etag "FMU06AXM5Y6LFTITKOQ596SN"
31 http request GET https://registry.npmjs.org/graceful-fs
32 http 304 https://registry.npmjs.org/graceful-fs
33 verbose headers { date: 'Tue, 07 Jun 2016 19:43:34 GMT',
33 verbose headers   via: '1.1 varnish',
33 verbose headers   'cache-control': 'max-age=300',
33 verbose headers   etag: '"FMU06AXM5Y6LFTITKOQ596SN"',
33 verbose headers   age: '271',
33 verbose headers   connection: 'keep-alive',
33 verbose headers   'x-served-by': 'cache-jfk1032-JFK',
33 verbose headers   'x-cache': 'HIT',
33 verbose headers   'x-cache-hits': '44',
33 verbose headers   'x-timer': 'S1465328614.305071,VS0,VE0',
33 verbose headers   vary: 'Accept-Encoding' }
34 silly get cb [ 304,
34 silly get   { date: 'Tue, 07 Jun 2016 19:43:34 GMT',
34 silly get     via: '1.1 varnish',
34 silly get     'cache-control': 'max-age=300',
34 silly get     etag: '"FMU06AXM5Y6LFTITKOQ596SN"',
34 silly get     age: '271',
34 silly get     connection: 'keep-alive',
34 silly get     'x-served-by': 'cache-jfk1032-JFK',
34 silly get     'x-cache': 'HIT',
34 silly get     'x-cache-hits': '44',
34 silly get     'x-timer': 'S1465328614.305071,VS0,VE0',
34 silly get     vary: 'Accept-Encoding' } ]
35 verbose etag https://registry.npmjs.org/graceful-fs from cache
36 verbose get saving graceful-fs to /Users/dave.charnuska/.npm/registry.npmjs.org/graceful-fs/.cache.json
37 verbose correctMkdir /Users/dave.charnuska/.npm correctMkdir not in flight; initializing
38 silly fetchNamedPackageData No valid target from cache, forcing network
39 verbose request uri https://registry.npmjs.org/graceful-fs
40 verbose request no auth needed
41 info attempt registry request try #1 at 3:43:34 PM
42 http request GET https://registry.npmjs.org/graceful-fs
43 http 200 https://registry.npmjs.org/graceful-fs
44 verbose headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
44 verbose headers   etag: '"FMU06AXM5Y6LFTITKOQ596SN"',
44 verbose headers   'content-type': 'application/json',
44 verbose headers   'content-encoding': 'gzip',
44 verbose headers   'cache-control': 'max-age=300',
44 verbose headers   'content-length': '8130',
44 verbose headers   'accept-ranges': 'bytes',
44 verbose headers   date: 'Tue, 07 Jun 2016 19:43:34 GMT',
44 verbose headers   via: '1.1 varnish',
44 verbose headers   age: '271',
44 verbose headers   connection: 'keep-alive',
44 verbose headers   'x-served-by': 'cache-jfk1032-JFK',
44 verbose headers   'x-cache': 'HIT',
44 verbose headers   'x-cache-hits': '45',
44 verbose headers   'x-timer': 'S1465328614.327770,VS0,VE0',
44 verbose headers   vary: 'Accept-Encoding' }
45 silly get cb [ 200,
45 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
45 silly get     etag: '"FMU06AXM5Y6LFTITKOQ596SN"',
45 silly get     'content-type': 'application/json',
45 silly get     'content-encoding': 'gzip',
45 silly get     'cache-control': 'max-age=300',
45 silly get     'content-length': '8130',
45 silly get     'accept-ranges': 'bytes',
45 silly get     date: 'Tue, 07 Jun 2016 19:43:34 GMT',
45 silly get     via: '1.1 varnish',
45 silly get     age: '271',
45 silly get     connection: 'keep-alive',
45 silly get     'x-served-by': 'cache-jfk1032-JFK',
45 silly get     'x-cache': 'HIT',
45 silly get     'x-cache-hits': '45',
45 silly get     'x-timer': 'S1465328614.327770,VS0,VE0',
45 silly get     vary: 'Accept-Encoding' } ]
46 verbose get saving graceful-fs to /Users/dave.charnuska/.npm/registry.npmjs.org/graceful-fs/.cache.json
47 verbose correctMkdir /Users/dave.charnuska/.npm correctMkdir not in flight; initializing
48 silly fetchPackageMetaData Error: No compatible version found: graceful-fs@undefined4.1.4
48 silly fetchPackageMetaData Valid install targets:
48 silly fetchPackageMetaData 4.1.4, 4.1.3, 4.1.2, 4.1.1, 4.1.0, 3.0.8, 3.0.7, 3.0.6, 3.0.5, 3.0.4, 3.0.3, 3.0.2, 3.0.1, 3.0.0, 2.0.3, 2.0.2, 2.0.1, 2.0.0, 1.2.3, 1.2.2, 1.2.1, 1.2.0, 1.1.14, 1.1.13, 1.1.12, 1.1.11, 1.1.10, 1.1.9, 1.1.8, 1.1.7, 1.1.6, 1.1.5, 1.1.4, 1.1.3, 1.1.2, 1.1.1, 1.1.0, 1.0.2, 1.0.1, 1.0.0
48 silly fetchPackageMetaData
48 silly fetchPackageMetaData     at pickVersionFromRegistryDocument (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:170:16)
48 silly fetchPackageMetaData     at /usr/local/lib/node_modules/npm/node_modules/iferr/index.js:13:50
48 silly fetchPackageMetaData     at /usr/local/lib/node_modules/npm/lib/utils/pulse-till-done.js:19:8
48 silly fetchPackageMetaData     at saved (/usr/local/lib/node_modules/npm/lib/cache/caching-client.js:174:7)
48 silly fetchPackageMetaData     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:210:7
48 silly fetchPackageMetaData     at FSReqWrap.oncomplete (fs.js:117:15)
48 silly fetchPackageMetaData  error for graceful-fs@undefined4.1.4 Error: No compatible version found: graceful-fs@undefined4.1.4
48 silly fetchPackageMetaData Valid install targets:
48 silly fetchPackageMetaData 4.1.4, 4.1.3, 4.1.2, 4.1.1, 4.1.0, 3.0.8, 3.0.7, 3.0.6, 3.0.5, 3.0.4, 3.0.3, 3.0.2, 3.0.1, 3.0.0, 2.0.3, 2.0.2, 2.0.1, 2.0.0, 1.2.3, 1.2.2, 1.2.1, 1.2.0, 1.1.14, 1.1.13, 1.1.12, 1.1.11, 1.1.10, 1.1.9, 1.1.8, 1.1.7, 1.1.6, 1.1.5, 1.1.4, 1.1.3, 1.1.2, 1.1.1, 1.1.0, 1.0.2, 1.0.1, 1.0.0
48 silly fetchPackageMetaData
48 silly fetchPackageMetaData     at pickVersionFromRegistryDocument (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:170:16)
48 silly fetchPackageMetaData     at /usr/local/lib/node_modules/npm/node_modules/iferr/index.js:13:50
48 silly fetchPackageMetaData     at /usr/local/lib/node_modules/npm/lib/utils/pulse-till-done.js:19:8
48 silly fetchPackageMetaData     at saved (/usr/local/lib/node_modules/npm/lib/cache/caching-client.js:174:7)
48 silly fetchPackageMetaData     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:210:7
48 silly fetchPackageMetaData     at FSReqWrap.oncomplete (fs.js:117:15)
49 silly rollbackFailedOptional Starting
50 silly rollbackFailedOptional Finishing
51 silly runTopLevelLifecycles Starting
52 silly runTopLevelLifecycles Finishing
53 silly install printInstalled
54 verbose stack Error: No compatible version found: graceful-fs@undefined4.1.4
54 verbose stack Valid install targets:
54 verbose stack 4.1.4, 4.1.3, 4.1.2, 4.1.1, 4.1.0, 3.0.8, 3.0.7, 3.0.6, 3.0.5, 3.0.4, 3.0.3, 3.0.2, 3.0.1, 3.0.0, 2.0.3, 2.0.2, 2.0.1, 2.0.0, 1.2.3, 1.2.2, 1.2.1, 1.2.0, 1.1.14, 1.1.13, 1.1.12, 1.1.11, 1.1.10, 1.1.9, 1.1.8, 1.1.7, 1.1.6, 1.1.5, 1.1.4, 1.1.3, 1.1.2, 1.1.1, 1.1.0, 1.0.2, 1.0.1, 1.0.0
54 verbose stack
54 verbose stack     at pickVersionFromRegistryDocument (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:170:16)
54 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/iferr/index.js:13:50
54 verbose stack     at /usr/local/lib/node_modules/npm/lib/utils/pulse-till-done.js:19:8
54 verbose stack     at saved (/usr/local/lib/node_modules/npm/lib/cache/caching-client.js:174:7)
54 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:210:7
54 verbose stack     at FSReqWrap.oncomplete (fs.js:117:15)
55 verbose cwd /Users/dave.charnuska/HBP_Projects/hmm12
56 error Darwin 15.5.0
57 error argv "/usr/local/Cellar/node/6.2.1/bin/node" "/usr/local/bin/npm" "install"
58 error node v6.2.1
59 error npm  v3.9.5
60 error No compatible version found: graceful-fs@undefined4.1.4
60 error Valid install targets:
60 error 4.1.4, 4.1.3, 4.1.2, 4.1.1, 4.1.0, 3.0.8, 3.0.7, 3.0.6, 3.0.5, 3.0.4, 3.0.3, 3.0.2, 3.0.1, 3.0.0, 2.0.3, 2.0.2, 2.0.1, 2.0.0, 1.2.3, 1.2.2, 1.2.1, 1.2.0, 1.1.14, 1.1.13, 1.1.12, 1.1.11, 1.1.10, 1.1.9, 1.1.8, 1.1.7, 1.1.6, 1.1.5, 1.1.4, 1.1.3, 1.1.2, 1.1.1, 1.1.0, 1.0.2, 1.0.1, 1.0.0
61 error If you need help, you may report this error at:
61 error     <https://github.com/npm/npm/issues>
62 verbose exit [ 1, true ]

**Comment by ctilley83** [comment]
Why was this closed.  I'm having the same issue. any solution?

**Comment by charleszardo** [comment]
I closed this issue because it seemed to be a local issue on my machine and not an actual npm issue.  With help from a much more experienced coworker, I completely remove node/npm and installed natively (previously I had installed it through Homebrew and I actually still had old MacPorts relics kicking around from an even further back install).
