### ISSUE TITLE
Error on antd-init package w/ npm install

### ISSUE THREAD

**Issue by erinjerri** [npm/npm#12998]
I tried to install this package upon `npm install` I received two main errors:
1) Issue filed [here](https://github.com/ant-design/antd-init/issues/71)

and 2)
`npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "antd"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3
npm ERR! code ENOSELF

npm ERR! Refusing to install antd as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/erinpangilinan/Desktop/ant-design-master/npm-debug.log
Erins-MacBook-Pro:ant-design-master erinpangilinan$ npm install antd
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "antd"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3
npm ERR! code ENOSELF

npm ERR! Refusing to install antd as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/erinpangilinan/Desktop/ant-design-master/npm-debug.log
Erins-MacBook-Pro:ant-design-master erinpangilinan$ npm run build
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3`

**Comment by KenanY** [comment]
@erinjerri If the `"name"` property of your `package.json` is equal to the name of a package that you are trying to install, then you will receive this `ENOSELF` error, since as far as `npm` can tell you are trying to install a module as a dependency of itself, which is not allowed.

**Comment by KenanY** [comment]
@erinjerri Hello, it has been over two weeks now with no reply from you. Are you still seeing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
