### ISSUE TITLE
AngularJs2 npm install error

### ISSUE THREAD

**Issue by csnehan** [npm/npm#13002]
Hi,

I am trying to install angularJs2 modules from npm. I am constantly getting the error as attached. Kindly help to resolve this issue.
[npm-debug-log-Angularjs2.txt](https://github.com/npm/npm/files/306730/npm-debug-log-Angularjs2.txt)

**Comment by legodude17** [comment]
#11308
This looks like the same problem. Try checking your proxy settings.

**Comment by csnehan** [comment]
Hi,

Thanks for your reply. I do not have any proxy settings and I also I'm able to access https://registry.npmjs.org.

**Comment by pradeeprajr93** [comment]
I'm also getting error message stating "getaddrinfo EAI_AGAIN registry.npmjs.org:443". Kindly help me.

**Comment by KenanY** [comment]
@csnehan Are you still facing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.

**Comment by saiprasad2392** [comment]
Hi i am facing the same issue. "getaddrinfo EAI_AGAIN registry.npmjs.org:443"
Can anyone help me?
