### ISSUE TITLE
ERR! Darwin 15.4.0 issue while doing $ npm install -g cordova npm

### ISSUE THREAD

**Issue by theartsnetwork** [npm/npm#13001]
$ npm install -g cordova
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "cordova"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! path /usr/local/lib/node_modules/cordova/.gitattributes
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall unlink

npm ERR! Error: EACCES: permission denied, unlink '/usr/local/lib/node_modules/cordova/.gitattributes'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, unlink '/usr/local/lib/node_modules/cordova/.gitattributes']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'unlink',
npm ERR!   path: '/usr/local/lib/node_modules/cordova/.gitattributes' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
npm ERR! error rolling back Error: EACCES: permission denied, unlink '/usr/local/lib/node_modules/cordova/.gitattributes'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  { [Error: EACCES: permission denied, unlink '/usr/local/lib/node_modules/cordova/.gitattributes']
npm ERR! error rolling back   errno: -13,
npm ERR! error rolling back   code: 'EACCES',
npm ERR! error rolling back   syscall: 'unlink',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/cordova/.gitattributes' }

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/akshayjirage/ArtmarqFirebase/npm-debug.log
Akshays-MacBook-Pro:artmarqfirebase akshayjirage$ cordova prepare ios
-bash: /usr/local/bin/cordova: No such file or directory
Akshays-MacBook-Pro:artmarqfirebase akshayjirage$ npm -g install npm@latest
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "-g" "install" "npm@latest"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! path /usr/local/lib/node_modules/npm/.mailmap
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall unlink

npm ERR! Error: EACCES: permission denied, unlink '/usr/local/lib/node_modules/npm/.mailmap'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, unlink '/usr/local/lib/node_modules/npm/.mailmap']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'unlink',
npm ERR!   path: '/usr/local/lib/node_modules/npm/.mailmap' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
npm ERR! error rolling back Error: EACCES: permission denied, unlink '/usr/local/lib/node_modules/npm/.mailmap'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  { [Error: EACCES: permission denied, unlink '/usr/local/lib/node_modules/npm/.mailmap']
npm ERR! error rolling back   errno: -13,
npm ERR! error rolling back   code: 'EACCES',
npm ERR! error rolling back   syscall: 'unlink',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/npm/.mailmap' }

[npm-debug.log.zip](https://github.com/npm/npm/files/306498/npm-debug.log.zip)

**Comment by KenanY** [comment]
@theartsnetwork Try prefixing your `npm install -g` commands with `sudo`. The error log indicates that you do not have permission to modify `/usr/local`, which is the directory you currently have `npm` configured to install global modules to.

**Comment by theartsnetwork** [comment]
It worked. Thanks very much.

**Comment by jortiz31** [comment]
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "foundation-cli"
npm ERR! node v4.4.5
npm ERR! npm  v3.9.3
npm ERR! path /Users/Maverick/.npm-packages/lib/node_modules/foundation-cli
npm ERR! code ENOTEMPTY
npm ERR! errno -66
npm ERR! syscall rename

npm ERR! ENOTEMPTY: directory not empty, rename '/Users/Maverick/.npm-packages/lib/node_modules/foundation-cli' -> '/Users/Maverick/.npm-packages/lib/node_modules/.foundation-cli.DELETE'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Maverick/GitHub/DEV/app/npm-debug.log
npm ERR! code 1

**Comment by jortiz31** [comment]
Getting this error, haven't been able to solve it for 3 days, I've tried everything in this and many other pages.

**Comment by sharoni3d** [comment]
how to do we fix this permission problem. i'm new to this is it possible to write a step by step fix thanks
