### ISSUE TITLE
any help with this issue!!

### ISSUE THREAD

**Issue by snatic** [npm/npm#13008]
C:\Windows\system32>npm i -g phonegap to update
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\snatic\\AppData\
\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i" "-g" "phonegap" "to" "upd
ate"
npm ERR! node v4.4.5
npm ERR! npm  v2.0.0

npm ERR! Unsupported URL Type: github:jonschlinkert/inquirer2
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>
npm WARN optional dep failed, continuing fsevents@1.0.12
\

**Comment by KenanY** [comment]
@snatic Does this also occur with newer versions of `npm`? Is it intentional that you are running:

```
$ npm i -g phonegap to update
```

which will install the `to` and `update` modules in addition to `phonegap`?

**Comment by snatic** [comment]
my mistake all my components are not updated, i fix all, updating NPM, node and all components too, 

Regards
