### ISSUE TITLE
npm fetch fail

### ISSUE THREAD

**Issue by psharmz** [npm/npm#13006]
hi!

I'm trying to do an npm install but i keep getting these errors:

''' 
npm ERR! fetch failed https://registry.npmjs.org/vinyl/-/vinyl-0.4.6.tgz
npm ERR! fetch failed https://registry.npmjs.org/onetime/-/onetime-1.1.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/semver-diff/-/semver-diff-0.1.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/enhanced-resolve/-/enhanced-resolve-0.7.6.tgz
npm ERR! fetch failed https://registry.npmjs.org/uuid/-/uuid-2.0.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/error-ex/-/error-ex-1.3.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/orchestrator/-/orchestrator-0.3.7.tgz
npm ERR! fetch failed https://registry.npmjs.org/sane/-/sane-1.3.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/ember-template-compiler/-/ember-template-compiler-1.7.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/es5-ext/-/es5-ext-0.10.11.tgz
npm ERR! fetch failed https://registry.npmjs.org/envify/-/envify-3.2.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/elliptic/-/elliptic-6.2.3.tgz
npm ERR! fetch failed https://registry.npmjs.org/entities/-/entities-1.1.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/each-async/-/each-async-1.1.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/es6-iterator/-/es6-iterator-2.0.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/home-or-tmp/-/home-or-tmp-1.0.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/end-of-stream/-/end-of-stream-1.0.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/es6-weak-map/-/es6-weak-map-0.1.4.tgz
npm ERR! fetch failed https://registry.npmjs.org/encoding/-/encoding-0.1.12.tgz
npm ERR! fetch failed https://registry.npmjs.org/http-signature/-/http-signature-0.10.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/errno/-/errno-0.1.4.tgz
npm ERR! fetch failed https://registry.npmjs.org/http-browserify/-/http-browserify-1.7.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/es6-symbol/-/es6-symbol-3.0.2.tgz
npm ERR! fetch failed https://registry.npmjs.org/inflight/-/inflight-1.0.4.tgz
npm ERR! fetch failed https://registry.npmjs.org/es6-promise/-/es6-promise-2.0.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/lodash._escapestringchar/-/lodash._escapestringchar-2.4.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/hawk/-/hawk-1.1.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/retry/-/retry-0.6.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/htmlescape/-/htmlescape-1.1.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/lodash._escapehtmlchar/-/lodash._escapehtmlchar-2.4.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/lodash._createwrapper/-/lodash._createwrapper-2.4.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/lodash._createassigner/-/lodash._createassigner-3.1.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/ecc-jsbn/-/ecc-jsbn-0.1.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/inherits/-/inherits-2.0.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/escope/-/escope-3.4.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/ieee754/-/ieee754-1.1.6.tgz
npm ERR! fetch failed https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.4.13.tgz
npm ERR! fetch failed https://registry.npmjs.org/immutable/-/immutable-3.7.6.tgz
npm ERR! fetch failed https://registry.npmjs.org/es6-map/-/es6-map-0.1.3.tgz
npm ERR! fetch failed https://registry.npmjs.org/parse5/-/parse5-1.5.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/pretty-hrtime/-/pretty-hrtime-0.2.2.tgz
npm ERR! fetch failed https://registry.npmjs.org/strip-bom/-/strip-bom-2.0.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/prelude-ls/-/prelude-ls-1.1.2.tgz
npm ERR! fetch failed https://registry.npmjs.org/lodash._getnative/-/lodash._getnative-3.9.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/string-width/-/string-width-1.0.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/which/-/which-1.0.9.tgz
npm ERR! fetch failed https://registry.npmjs.org/promise/-/promise-7.1.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/stream-combiner2/-/stream-combiner2-1.0.2.tgz
npm ERR! fetch failed https://registry.npmjs.org/lodash.isplainobject/-/lodash.isplainobject-3.2.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/is-fullwidth-code-point/-/is-fullwidth-code-point-1.0.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/lodash.isarray/-/lodash.isarray-3.0.4.tgz
npm ERR! fetch failed https://registry.npmjs.org/lodash.isarguments/-/lodash.isarguments-3.0.7.tgz
npm ERR! fetch failed https://registry.npmjs.org/stringmap/-/stringmap-0.2.2.tgz
npm ERR! fetch failed https://registry.npmjs.org/string_decoder/-/string_decoder-0.10.31.tgz
npm ERR! fetch failed https://registry.npmjs.org/lodash.memoize/-/lodash.memoize-3.0.4.tgz
npm ERR! fetch failed https://registry.npmjs.org/lodash.isfunction/-/lodash.isfunction-2.4.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/lodash.clonedeep/-/lodash.clonedeep-3.0.2.tgz
npm ERR! fetch failed https://registry.npmjs.org/promptly/-/promptly-0.2.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/lodash.identity/-/lodash.identity-2.4.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/lodash.istypedarray/-/lodash.istypedarray-3.0.5.tgz
npm ERR! fetch failed https://registry.npmjs.org/is-root/-/is-root-1.0.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/is-path-inside/-/is-path-inside-1.0.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/is-path-in-cwd/-/is-path-in-cwd-1.0.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/isexe/-/isexe-1.1.2.tgz
npm ERR! fetch failed https://registry.npmjs.org/onetime/-/onetime-1.1.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/semver-diff/-/semver-diff-0.1.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/enhanced-resolve/-/enhanced-resolve-0.7.6.tgz
npm ERR! fetch failed https://registry.npmjs.org/uuid/-/uuid-2.0.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/error-ex/-/error-ex-1.3.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/orchestrator/-/orchestrator-0.3.7.tgz
npm ERR! fetch failed https://registry.npmjs.org/sane/-/sane-1.3.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/ember-template-compiler/-/ember-template-compiler-1.7.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/es5-ext/-/es5-ext-0.10.11.tgz
npm ERR! fetch failed https://registry.npmjs.org/envify/-/envify-3.2.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/elliptic/-/elliptic-6.2.3.tgz
npm ERR! fetch failed https://registry.npmjs.org/entities/-/entities-1.1.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/each-async/-/each-async-1.1.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/es6-iterator/-/es6-iterator-2.0.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/home-or-tmp/-/home-or-tmp-1.0.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/es6-weak-map/-/es6-weak-map-0.1.4.tgz
npm ERR! fetch failed https://registry.npmjs.org/end-of-stream/-/end-of-stream-1.0.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/encoding/-/encoding-0.1.12.tgz
npm ERR! fetch failed https://registry.npmjs.org/errno/-/errno-0.1.4.tgz
npm ERR! fetch failed https://registry.npmjs.org/http-signature/-/http-signature-0.10.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/http-browserify/-/http-browserify-1.7.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/inflight/-/inflight-1.0.4.tgz
npm ERR! fetch failed https://registry.npmjs.org/es6-symbol/-/es6-symbol-3.0.2.tgz
npm ERR! fetch failed https://registry.npmjs.org/es6-promise/-/es6-promise-2.0.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/lodash._escapestringchar/-/lodash._escapestringchar-2.4.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/hawk/-/hawk-1.1.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/htmlescape/-/htmlescape-1.1.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/lodash._escapehtmlchar/-/lodash._escapehtmlchar-2.4.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/retry/-/retry-0.6.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/lodash._createwrapper/-/lodash._createwrapper-2.4.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/lodash._createassigner/-/lodash._createassigner-3.1.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/ecc-jsbn/-/ecc-jsbn-0.1.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/inherits/-/inherits-2.0.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/escope/-/escope-3.4.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/ieee754/-/ieee754-1.1.6.tgz
npm ERR! fetch failed https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.4.13.tgz
npm ERR! fetch failed https://registry.npmjs.org/immutable/-/immutable-3.7.6.tgz
npm ERR! fetch failed https://registry.npmjs.org/es6-map/-/es6-map-0.1.3.tgz
npm ERR! fetch failed https://registry.npmjs.org/pretty-hrtime/-/pretty-hrtime-0.2.2.tgz
npm ERR! fetch failed https://registry.npmjs.org/strip-bom/-/strip-bom-2.0.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/prelude-ls/-/prelude-ls-1.1.2.tgz
npm ERR! fetch failed https://registry.npmjs.org/lodash._getnative/-/lodash._getnative-3.9.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/string-width/-/string-width-1.0.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/which/-/which-1.0.9.tgz
npm ERR! fetch failed https://registry.npmjs.org/promise/-/promise-7.1.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/stream-combiner2/-/stream-combiner2-1.0.2.tgz
npm ERR! fetch failed https://registry.npmjs.org/lodash.isplainobject/-/lodash.isplainobject-3.2.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/is-fullwidth-code-point/-/is-fullwidth-code-point-1.0.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/lodash.isarray/-/lodash.isarray-3.0.4.tgz
npm ERR! fetch failed https://registry.npmjs.org/lodash.isarguments/-/lodash.isarguments-3.0.7.tgz
npm ERR! fetch failed https://registry.npmjs.org/stringmap/-/stringmap-0.2.2.tgz
npm ERR! fetch failed https://registry.npmjs.org/string_decoder/-/string_decoder-0.10.31.tgz
npm ERR! fetch failed https://registry.npmjs.org/lodash.memoize/-/lodash.memoize-3.0.4.tgz
npm ERR! fetch failed https://registry.npmjs.org/lodash.isfunction/-/lodash.isfunction-2.4.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/lodash.clonedeep/-/lodash.clonedeep-3.0.2.tgz
npm ERR! fetch failed https://registry.npmjs.org/promptly/-/promptly-0.2.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/lodash.identity/-/lodash.identity-2.4.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/lodash.istypedarray/-/lodash.istypedarray-3.0.5.tgz
npm ERR! fetch failed https://registry.npmjs.org/is-root/-/is-root-1.0.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/is-path-inside/-/is-path-inside-1.0.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/is-path-in-cwd/-/is-path-in-cwd-1.0.0.tgz
npm ERR! cb() never called!
npm ERR! not ok code 0
'''

I've also tried npm config set registry http://registry.npmjs.org/ and then doing a reinstall but the issue persists. Any advice?

Thanks!

**Comment by KenanY** [comment]
@psharmz What is the output of `npm --version`?

**Comment by psharmz** [comment]
1.4.28 and node -v is v0.10.40 ...I understand its an older version but i need to use the older version

**Comment by othiym23** [comment]
`npm@1` is no longer supported by the CLI team. Can you at least update to `npm@2`?

**Comment by KenanY** [comment]
@psharmz Are you still seeing this issue after updating to `npm@2` or `npm@3`?

**Comment by KenanY** [comment]
Closing as abandoned.
