### ISSUE TITLE
Document custom init interviewer feature more clearly.

### ISSUE THREAD

**Issue by zkat** [npm/npm#13005]
It's a little-known fact that npm has a power user feature that allows people to write custom interviewers for `npm init`. The way `.npm-init.js` works and how to configure its location, though, are spread across the documention for 3 different projects, and aren't terribly clearly marked.

It would be fantastic to have a single, central document right in the npm docs that we could point to for people to figure out how this feature works, specially since @seldo keeps mentioning it in talks! ;)

Docs for the various parts of the feature are at:

* https://github.com/npm/init-package-json/blob/master/README.md
* https://github.com/npm/promzard/blob/master/README.md
* https://docs.npmjs.com/misc/config#init-module

**Comment by lholmquist** [comment]
It seems to me that this might be the best place for it, https://docs.npmjs.com/getting-started/using-a-package.json.  i've just recently watched the node live paris talk from @ashleygwilliams and this feature is mentioned at pretty much the same time as the `npm init` command.

I could try to get a PR going for this

**Comment by zkat** [comment]
As far as I'm concerned, a PR is a great idea! Make sure you talk to @ashleygwilliams first and it should be ok :)

Thanks a bunch!

**Comment by lholmquist** [comment]
@ashleygwilliams thoughts on adding a section for this in this "chapter":   https://docs.npmjs.com/getting-started/using-a-package.json.

**Comment by lholmquist** [comment]
@zkat i've added an initial PR to the docs repo for this :  https://github.com/npm/docs/pull/735

**Comment by zkat** [comment]
@lholmquist 🎉 thank you!

**Comment by lholmquist** [comment]
@zkat just pinging to see if there is any update here?

**Comment by zkat** [comment]
@lholmquist sorry for the delay. Some minor confusion about the docs repo on my part, but that's merged and will be included in the next release <3

Thank you a lot for this again! I've already pointed at least one person at those docs, and they commented on how nice and easy they were to use! 🎉

**Comment by lholmquist** [comment]
@zkat Rad!!

**Comment by zkat** [comment]
This is live! Check https://docs.npmjs.com/getting-started/using-a-package.json :D
