### ISSUE TITLE
npm install 

### ISSUE THREAD

**Issue by shravankumarj** [npm/npm#13000]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'express' ]
2 info using npm@3.9.3
3 info using node@v6.2.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData express@^4.13.1
8 silly fetchNamedPackageData express
9 silly mapToRegistry name express
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry http://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'express',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   name: 'express',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri http://registry.npmjs.org/express
14 verbose request uri http://registry.npmjs.org/express
15 verbose request no auth needed
16 info attempt registry request try #1 at 11:40:37 AM
17 verbose request id 120ac1ddcb390585
18 http request GET http://registry.npmjs.org/express
19 http 404 http://registry.npmjs.org/express
20 verbose bad json <html>
20 verbose bad json <head><title>404 Not Found</title></head>
20 verbose bad json <body bgcolor="white">
20 verbose bad json <center><h1>404 Not Found</h1></center>
20 verbose bad json <hr><center>nginx/1.10.0</center>
20 verbose bad json </body>
20 verbose bad json </html>
21 error registry error parsing json
22 verbose headers { server: 'nginx/1.10.0',
22 verbose headers   date: 'Wed, 08 Jun 2016 18:40:37 GMT',
22 verbose headers   'content-type': 'text/html',
22 verbose headers   'content-length': '169',
22 verbose headers   connection: 'keep-alive' }
23 silly get cb [ 404,
23 silly get   { server: 'nginx/1.10.0',
23 silly get     date: 'Wed, 08 Jun 2016 18:40:37 GMT',
23 silly get     'content-type': 'text/html',
23 silly get     'content-length': '169',
23 silly get     connection: 'keep-alive' } ]
24 silly fetchPackageMetaData SyntaxError: Unexpected token < in JSON at position 0
24 silly fetchPackageMetaData <html>
24 silly fetchPackageMetaData <head><title>404 Not Found</title></head>
24 silly fetchPackageMetaData <body bgcolor="white">
24 silly fetchPackageMetaData <center><h1>404 Not Found</h1></center>
24 silly fetchPackageMetaData <hr><center>nginx/1.10.0</center>
24 silly fetchPackageMetaData </body>
24 silly fetchPackageMetaData </html>
24 silly fetchPackageMetaData
24 silly fetchPackageMetaData     at Object.parse (native)
24 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:199:23)
24 silly fetchPackageMetaData     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:172:14)
24 silly fetchPackageMetaData     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:200:22)
24 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
24 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
24 silly fetchPackageMetaData     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1067:10)
24 silly fetchPackageMetaData     at emitOne (events.js:101:20)
24 silly fetchPackageMetaData     at Request.emit (events.js:188:7)
24 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:988:12)
24 silly fetchPackageMetaData  error for express@^4.13.1 SyntaxError: Unexpected token < in JSON at position 0
24 silly fetchPackageMetaData <html>
24 silly fetchPackageMetaData <head><title>404 Not Found</title></head>
24 silly fetchPackageMetaData <body bgcolor="white">
24 silly fetchPackageMetaData <center><h1>404 Not Found</h1></center>
24 silly fetchPackageMetaData <hr><center>nginx/1.10.0</center>
24 silly fetchPackageMetaData </body>
24 silly fetchPackageMetaData </html>
24 silly fetchPackageMetaData
24 silly fetchPackageMetaData     at Object.parse (native)
24 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:199:23)
24 silly fetchPackageMetaData     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:172:14)
24 silly fetchPackageMetaData     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:200:22)
24 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
24 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
24 silly fetchPackageMetaData     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1067:10)
24 silly fetchPackageMetaData     at emitOne (events.js:101:20)
24 silly fetchPackageMetaData     at Request.emit (events.js:188:7)
24 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:988:12)
25 silly rollbackFailedOptional Starting
26 silly rollbackFailedOptional Finishing
27 silly runTopLevelLifecycles Starting
28 silly runTopLevelLifecycles Finishing
29 silly install printInstalled
30 verbose stack SyntaxError: Unexpected token < in JSON at position 0
30 verbose stack <html>
30 verbose stack <head><title>404 Not Found</title></head>
30 verbose stack <body bgcolor="white">
30 verbose stack <center><h1>404 Not Found</h1></center>
30 verbose stack <hr><center>nginx/1.10.0</center>
30 verbose stack </body>
30 verbose stack </html>
30 verbose stack
30 verbose stack     at Object.parse (native)
30 verbose stack     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:199:23)
30 verbose stack     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:172:14)
30 verbose stack     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:200:22)
30 verbose stack     at emitTwo (events.js:106:13)
30 verbose stack     at Request.emit (events.js:191:7)
30 verbose stack     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1067:10)
30 verbose stack     at emitOne (events.js:101:20)
30 verbose stack     at Request.emit (events.js:188:7)
30 verbose stack     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:988:12)
31 verbose cwd C:\userStory
32 error Windows_NT 6.1.7601
33 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "express"
34 error node v6.2.1
35 error npm  v3.9.3
36 error Unexpected token < in JSON at position 0
36 error <html>
36 error <head><title>404 Not Found</title></head>
36 error <body bgcolor="white">
36 error <center><h1>404 Not Found</h1></center>
36 error <hr><center>nginx/1.10.0</center>
36 error </body>
36 error </html>
37 error If you need help, you may report this error at:
37 error     <https://github.com/npm/npm/issues>
38 verbose exit [ 1, true ]

**Comment by EmmaRamirez** [comment]
Hi @shravankumarj, could you provide more context for what you did? Were you just running npm install? If so, you may want to check your package.json file to make sure it's formatted correctly (i.e. braces and the like in the correct position).

**Comment by KenanY** [comment]
Closing as abandoned due to no response. Can reopen if this is still an issue.
