### ISSUE TITLE
ENOENT, open '/root/package.json'

### ISSUE THREAD

**Issue by dhavalpadshala** [npm/npm#13017]
Hi..I am getting this error while npm start 

> ENOENT, open '/root/package.json'

plz correct this if anyone able.

**Comment by EdaProgrammer** [comment]
Try to copy the package.json of this repository in the required path

**Comment by EdaProgrammer** [comment]
@dhavalpadshala

**Comment by EdaProgrammer** [comment]
@dhavalpadshala

**Comment by KenanY** [comment]
@dhavalpadshala The error you are seeing is indicating that you do now have a `package.json` in your current working directory. Without a `package.json` to define the `"start"` script you want, `npm start` will not work.

**Comment by KenanY** [comment]
@dhavalpadshala Hello, it has been over two weeks now with no reply from you. Are you still experiencing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
