### ISSUE TITLE
Failed PUT 403 with npm publish of existing project

### ISSUE THREAD

**Issue by binhums** [npm/npm#13012]
Trying to publish to [ember-cli-reporter](https://www.npmjs.com/package/ember-cli-reporter) getting a 403 despite [being a maintainer](https://www.npmjs.com/package/ember-cli-reporter/access).

```
$ npm publish
npm ERR! publish Failed PUT 403
npm ERR! Darwin 15.5.0
npm ERR! argv "/opt/nodes/v4.4.5/bin/node" "/opt/boxen/nodenv/versions/v4.4.5/bin/npm" "publish"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code E403

npm ERR! you do not have permission to publish "ember-cli-reporter". Are you logged in as the correct user? : ember-cli-reporter
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ben/src/ember-cli-reporter/npm-debug.log
$ npm whoami
binhums
```

Find log attached:

[npm-debug.log.txt](https://github.com/npm/npm/files/307910/npm-debug.log.txt)

**Comment by edoura** [comment]
same for me

**Comment by edoura** [comment]
@binhums, I changed the app name in `package.json` and it worked. must already exist the package name in npmjs.com

**Comment by binhums** [comment]
Sounds like a synching issue, tried again and the maintainer rights have resolved themselves.
