### ISSUE TITLE
node node_modules/jsreport --init not working in Ubuntu 

### ISSUE THREAD

**Issue by Dasithz** [npm/npm#13011]
When I am going to start npm in Ubuntu below error is prompting. 

```
npm ERR! Error: ENOENT, open '/home/dasitha/package.json'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.16.0-30-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /home/dasitha
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /home/dasitha/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/dasitha/npm-debug.log
npm ERR! not ok code 0
```

**Comment by KenanY** [comment]
@Dasithz First of all, `npm@1.3` is years old and no longer supported. Please consider [updating](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm). Secondly, the error you are seeing is indicative of the lack of a `package.json` file in your current working directory. Without a `package.json` file to define your `"start"` script, `npm` will have no idea what you want it to do when you run `npm start`.

**Comment by Dasithz** [comment]
@KenanY ThanksJan for the support. This happened when I tried to upload the image suddenly jsreports went down. then I tried to up and ended up with this error. I have deleted the uploded image folder. Then it works.
