### ISSUE TITLE
Failed to install ionic after successfully installing Cordova

### ISSUE THREAD

**Issue by juste-therock** [npm/npm#13019]
Here goes the displayed error:
> npm install -g ionic                                                          
npm ERR! Windows_NT 6.2.9200                                                    
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ionic"                      
npm ERR! node v6.2.1                                                            
npm ERR! npm  v3.9.3                                                            
                                                                                
npm ERR! shasum check failed for C:\Users\JUSTER~1\AppData\Local\Temp\npm-5252-7
0746c7c\registry.npmjs.org\ionic\-\ionic-1.7.15.tgz                             
npm ERR! Expected: fe83a72a60d03d667d0f3bb47a4210f57356c322                     
npm ERR! Actual:   fa20440fd17bc1f5eddd6adf27867e75aad25c52                     
npm ERR! From:     https://registry.npmjs.org/ionic/-/ionic-1.7.15.tgz          
npm ERR!                                                                        
npm ERR! If you need help, you may report this error at:                        
npm ERR!     <https://github.com/npm/npm/issues>                                
                                                                                
npm ERR! Please include the following file with any support request:            
npm ERR!     C:\Users\Juste Rocca\npm-debug.log

**Comment by KenanY** [comment]
@juste-therock Have you tried running `npm cache clean`?

**Comment by juste-therock** [comment]
It is okay. Thank you for your help.


Best regards.



Juste AHOUANSOU
Menelic Ltd | Applied Knowledge Is Power
M: (+229)97 35 85 56 & (+229)94 73 79 20
W: www.menelic.com

**Comment by othiym23** [comment]
Closing as resolved.
