### ISSUE TITLE
[Proposal]: npm process-versions

### ISSUE THREAD

**Issue by wilmoore** [npm/npm#13010]
This proposal is for extracting the `npm version` functionality out as a separation of concerns. Currently, `npm version` is responsible for:
1. Bumping a package version
2. Exporting a hash of process versions

Not only is #2 [not documented](https://docs.npmjs.com/cli/version) but it is also overloading the functionality of the command which forces [unnecessary branching in the code](https://github.com/npm/npm/blob/master/lib/version.js#L33).

I would like to propose an extract of the functionality of [`dump`](https://github.com/npm/npm/blob/2a5977e0c65b244e92d848fcd56f2f80ba8cdf3b/lib/version.js#L166-L179) into a new command.
###### A couple options:
1. `npm process-versions`
2. `npm versions`
###### Additional considerations:

As it is now, the current `npm version` command outputs the object as-is instead of serialized. I would expect that the default output would be run through `JSON.stringify`. You can current do: `NPM_CONFIG_JSON=1 npm version` but that is not intuitive at all and is completely undocumented as far as I can tell. To discover this, I had to [read the source](https://github.com/npm/npm/blob/2a5977e0c65b244e92d848fcd56f2f80ba8cdf3b/lib/version.js#L175).

IMHO, this provides a sub-par user experience.
###### Finally

If this proposal looks fair, I'd like to submit a PR to satisfy; however, I'd like to collect feedback before getting started.

Thanks.

**Comment by jasonkarns** [comment]
I'm +1 to separating these concerns and my vote goes to `npm versions` as the command.

While I'm not typically in favor of emitting JSON, I do think that dumping as an object is rather pointless. I would expect the output to be parseable (by default) with standard unix utilities. So:
```
$ npm versions
x=1.1
y=2.2
```

Then adding some --json flag to force proper json output.
