### ISSUE TITLE
npm ERR

### ISSUE THREAD

**Issue by evilxyz** [npm/npm#13022]
```
xyz@evil /opt/atom (git)-[master] % sudo ./script/build 
Node: v6.2.1
npm: v3.9.5
Installing build modules...
npm ERR! Linux 4.5.4-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "--userconfig=/opt/atom/build/.npmrc" "install" "--loglevel" "error"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.5

npm ERR! shasum check failed for /tmp/npm-26088-d94fdc92/registry.npmjs.org/babel-core/-/babel-core-5.8.38.tgz
npm ERR! Expected: 1fcaee79d7e61b750b00b8e54f6dfc9d0af86558
npm ERR! Actual:   78027dfa14e24448ebd725c3af3264628d775c33
npm ERR! From:     https://registry.npmjs.org/babel-core/-/babel-core-5.8.38.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/atom/build/npm-debug.log
sudo ./script/build  20.87s user 1.92s system 1% cpu 20:35.54 total

OS: Arch Linux 
Kernel: x86_64 Linux 4.5.4-1-ARCH
Npm: 3.9.5
```

I don't know this error...

**Comment by KenanY** [comment]
@evilxyz Have you tried running `npm cache clean`?

**Comment by evilxyz** [comment]
@KenanY  Yes, before i build atom, i execute `npm cache clean` , but got a new error...

xyz@evilxyz /opt/atom (git)-[master] % sudo ./script/build 
Node: v6.2.1
npm: v3.9.5
Installing build modules...
=> Took 765683ms.

Installing apm...
(node:30938) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:30938) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:30938) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:30938) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:30938) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:30938) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:30938) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:30938) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:30938) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:31141) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:31141) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:31263) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:31263) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
../deps/libgit2/deps/zlib/inflate.c: In function ‘inflateMark’:
../deps/libgit2/deps/zlib/inflate.c:1507:61: warning: left shift of negative value [-Wshift-negative-value]
     if (strm == Z_NULL || strm->state == Z_NULL) return -1L << 16;
                                                             ^~
(node:1890) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:1890) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:3094) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:3094) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:3094) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
=> Took 1879543ms.

Deleting old packages...
=> Took 382ms.


gyp info it worked if it ends with ok
gyp info using node-gyp@2.0.2
gyp info using node@0.10.40 | linux | x64
gyp http GET https://atom.io/download/atom-shell/v0.37.8/node-v0.37.8.tar.gz
gyp http 200 https://atom.io/download/atom-shell/v0.37.8/node-v0.37.8.tar.gz
gyp http GET https://atom.io/download/atom-shell/v0.37.8/SHASUMS256.txt
gyp WARN install got an error, rolling back install
gyp ERR! install error 
gyp ERR! stack Error: getaddrinfo ENOTFOUND
gyp ERR! stack     at errnoException (dns.js:37:11)
gyp ERR! stack     at Object.onanswer [as oncomplete] (dns.js:124:16)
gyp ERR! System Linux 4.6.2-1-ARCH
gyp ERR! command "/opt/atom/apm/node_modules/atom-package-manager/bin/node" "/opt/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "install" "--target=0.37.8" "--dist-url=https://atom.io/download/atom-shell" "--arch=x64" "--ensure"
gyp ERR! cwd /root/.atom
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 

sudo ./script/build  187.09s user 19.50s system 7% cpu 44:57.24 total

**Comment by evilxyz** [comment]
@KenanY done...  
`yaourt -S atom-editor-bin --noconfirm`

**Comment by KenanY** [comment]
Seems like you resolved this yourself, so I'm gonna close.
