### ISSUE TITLE
npm does not support Basic Authentication

### ISSUE THREAD

**Issue by boeboe** [npm/npm#13027]
We are using a Nexus Artifact repository (both as proxy for npmjs packages and storage of our own private npm packages). The Nexus Repository is accessible through Basic Auth behind a Nginx reverse proxy.

In order to get basic authentication trying to work, I executed the following steps:

> $ npm config set registry http://repository.example.com/repository/npm-public
> $ cat ~/.npmrc
> registry=http://repository.example.com/repository/npm-public
> $ npm login --registry=http://repository.example.com:80/repository/npm-public
> Username: (me) test
> Password: ****
> Email: (this IS public) (test@example.com)
> 
> npm ERR! registry error parsing json
> npm WARN adduser Incorrect username or password
> npm WARN adduser You can reset your account by visiting:
> npm WARN adduser 
> npm WARN adduser     https://npmjs.org/forgot
> npm WARN adduser 
> npm ERR! Linux 4.4.0-22-generic
> npm ERR! argv "/usr/bin/nodejs" "/usr/local/bin/npm" "login" "--registry=http://repository.example.com/repository/npm-public"
> npm ERR! node v4.2.6
> npm ERR! npm  v3.9.5
> npm ERR! Unexpected token 
> npm ERR! 401 Authorization Required
> npm ERR! nginx/1.4.6 (Ubuntu)

I opened wireshark, to sniff on the wire what was really going on and saw the following:

> PUT /repository/npm-public/-/user/org.couchdb.user:test HTTP/1.1
> accept-encoding: gzip
> version: 3.9.5
> accept: application/json
> referer: adduser
> npm-session: 3004ccc439897198
> user-agent: npm/3.9.5 node/v4.2.6 linux x64
> host: repository.example.com:80
> content-type: application/json
> content-length: 175
> Connection: keep-alive
> 
> {"_id":"org.couchdb.user:test","name":"test","password":"****","email":"test@example.com","type":"user","roles":[],"date":"2016-06-12T08:53:02.978Z"}HTTP/1.1 401 Unauthorized
> Server: nginx/1.4.6 (Ubuntu)
> Date: Sun, 12 Jun 2016 08:53:01 GMT
> Content-Type: text/html
> Content-Length: 203
> Connection: keep-alive
> WWW-Authenticate: Basic realm="Restricted Content"
> 
> 401 Authorization Required
> nginx/1.4.6 (Ubuntu)

As you can see, npm is sending a JSON body with some bizarre "authentication". What I would expect is that npm does authentication on HTTP level (like for example in the following example with maven):

> GET /repository/maven-public/org/springframework/boot/spring-boot-starter-parent/1.3.5.RELEASE/spring-boot-starter-parent-1.3.5.RELEASE.pom HTTP/1.1
> Cache-control: no-cache
> Cache-store: no-store
> Pragma: no-cache
> Expires: 0
> Accept-Encoding: gzip
> User-Agent: Apache-Maven/3.3.9 (Java 1.8.0_91; Linux 4.4.0-22-generic)
> Host: repository.example.com
> Connection: Keep-Alive
> 
> HTTP/1.1 401 Unauthorized
> Server: nginx/1.4.6 (Ubuntu)
> Date: Sun, 12 Jun 2016 08:55:02 GMT
> Content-Type: text/html
> Content-Length: 203
> Connection: keep-alive
> WWW-Authenticate: Basic realm="Restricted Content"
> 
> 401 Authorization Required
> nginx/1.4.6 (Ubuntu)
> 
> GET /repository/maven-public/org/springframework/boot/spring-boot-starter-parent/1.3.5.RELEASE/spring-boot-starter-parent-1.3.5.RELEASE.pom HTTP/1.1
> Cache-control: no-cache
> Cache-store: no-store
> Pragma: no-cache
> Expires: 0
> Accept-Encoding: gzip
> User-Agent: Apache-Maven/3.3.9 (Java 1.8.0_91; Linux 4.4.0-22-generic)
> Host: repository.example.com
> Connection: Keep-Alive
> Authorization: Basic cHJvYWxscdcdY2U6cHJvQWxsaWFuY2U=
> 
> HTTP/1.1 200 OK
> Server: nginx/1.4.6 (Ubuntu)
> Date: Sun, 12 Jun 2016 08:55:02 GMT
> Content-Type: application/xml
> Content-Length: 7120
> Connection: keep-alive
> X-Frame-Options: SAMEORIGIN
> X-Content-Type-Options: nosniff
> Set-Cookie: NXREMEMBERME=deleteMe; Path=/; Max-Age=0; Expires=Sat, 11-Jun-2016 08:55:02 GMT
> ETag: "211b88caf1e4295b4a61129f9226ddd8"
> Last-Modified: Tue, 10 May 2016 06:36:35 GMT

So my question here is two-fold:
- Does NPM supports basic authentication?
- In case basic authentication is not supported, will this be on the road map anywhere soon? In case it is supported, I am eager to find out how to configure it.

BR,
Bart

**Comment by yuchi** [comment]
This is not an issue on npm, it’s pretty ok for them to **not** support Basic.
What you need to do is set up the *npm Bearer Token Realm*. [See this post from Joe Tom of Sonatype for more info](http://www.sonatype.org/nexus/2015/11/19/new-npm-tools-for-your-nexus-repository-manager-tool-box/)

**Comment by boeboe** [comment]
@yuchi - I do not agree that basic authentication is a useless feature request.

From a corporate security/operational perspective, many companies host there own NPM proxy repositories (like Nexus for example), for the following 2 reasons:

- for caching publicly available packages, which unfortunately often disappear sometimes
- for having a private push repo for private packages

When you create such a repository, it is good common practice to install such a repo behind a reverse proxy (nginx for example) with basic authentication, in order to shield away direct access to the repo (other people don't have any business with the kind of infrastructure a company is using).

Could you reconsider this feature request, as I believe it is truly an added value.

**Comment by dokaspar** [comment]
Very good point by @boeboe.

We are in exactly this reverse proxy scenario with a hosted/private npm repository (grouped together with the public one at npmjs.org). If I understand correctly, the lack of basic auth support implies that all our npm users must configure a registry with their username and password spelled out in plain text, like this:

`registry=https://user:password@mycompany.com/nexus3/repository/mycompany-npm-group/`

Can I at least be sure that the password isn't transmitted in plain-text as well?

**Comment by michaelficarra** [comment]
@dokaspar Basic auth *is* plaintext.

**Comment by Kriegslustig** [comment]
@michaelficarra
> Basic auth is plaintext.

Yeah, but not in the case described by @dokaspar. He's using TLS. HTTP Basic Auth credentials are written into the `Authorization` header. So it will be encrypted along with all other headers.

@dokaspar 
> Can I at least be sure that the password isn't transmitted in plain-text as well?

Yes, if you're running the service over TLS as in your example.

**Comment by gsdevme** [comment]
Also have ran into this where we want to run a reserve proxy infront of the NPM registry for very good reasons.  We are running a TLS/SSL proxy infront of it and would like to just http-auth it to shield from randomness and provide a security layer. 

Ideally it would just be as simple as the following, however it doesn't work :( :( :(
```
registry=https://user:pass@npm.org.com
```
