### ISSUE TITLE
npm does not add alias automatically when installing a new package

### ISSUE THREAD

**Issue by HamzaLJ** [npm/npm#13025]
When I try to run a command to call a package installed using npm.

e.g: cordova
> cordova -v

It does not work, it works only when I run the full path:

> /Users/Hamza/.npm-packages/bin/cordova -v

For that I need to create an alias for each package in order to avoid calling using the full paths, which causes many issues in many levels.

My npm version is:
3.7.3

My O.S
Mac OSx El Capitan

**Comment by KenanY** [comment]
@HamzaLJ Is `/Users/Hamza/.npm-packages/bin/` in your `PATH`?

**Comment by KenanY** [comment]
@HamzaLJ Hello, it has been over two weeks now with no reply from you. Are you still experiencing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
