### ISSUE TITLE
Problem starting a node.js heroku server

### ISSUE THREAD

**Issue by wd2311** [npm/npm#13029]
Any help with why this may not be working would be highly appreciated :)

![cmdproblem](https://cloud.githubusercontent.com/assets/8781492/15994196/41605e3e-30cc-11e6-8cb2-8733a3a666a7.PNG)

![cmdproblem2](https://cloud.githubusercontent.com/assets/8781492/15994199/58adf1f0-30cc-11e6-9165-797ac64ccba2.PNG)

**Comment by wd2311** [comment]
https://github.com/wd2311/ballsTogether

I posted the files to github and you can find them by clicking the link above :)

**Comment by KenanY** [comment]
@wd2311 As the error message points out, you do not have a `"start"` script defined in your `package.json`. Hence, `npm start` will display that error, as intended. [The documentation](https://docs.npmjs.com/misc/scripts) contains information on how to define scripts.

**Comment by KenanY** [comment]
@wd2311 Hello, it has been two weeks now with no reply from you. Are you still experiencing this issue?

**Comment by wd2311** [comment]
Nope, I figured it out. Thanks a lot.

**Comment by othiym23** [comment]
Closing as resolved.
