### ISSUE TITLE
Add a "suggestions"-object to "package.json"-schema

### ISSUE THREAD

**Issue by dnepro** [npm/npm#13034]
Hello everybody,

I've got a workflow where my build tool is based on bash scripts managed with npm and one part of building my files is to copy images to a dest folder and i've included an option to run "imageoptim" but it is a cli option.

Now for this to run i need the user to have "imageoptim" installed, but definitely not every user wants/needs to install it, so i basically would appreciate a "suggestions"-object in package.json, just like [Composer](https://getcomposer.org/doc/04-schema.md#suggest) does.

Its defined as a simple "key value"-pair, in which the key is the package e.g. "imageoptim" and the value is a message e.g. "it minimizes the images, for better website delivery and speed". The message then gets printed out to the user e.g. something like `"This package suggests to install $package, because $message \n to install this dependency run \"npm install $package\"`

Thanks in advance,
Roman

**Comment by legodude17** [comment]
Another feature of this would be to be able to run something like `npm install $your-package --suggest` to auto install those.
