### ISSUE TITLE
NPM install -g doesn't install globally

### ISSUE THREAD

**Issue by richardxu100** [npm/npm#13039]
Hello everybody, I'm currently trying to install bower by using the npm command 
`npm install -g bower`
But npm just installs bower into a folder called myproject onto my desktop. 

`Richards-MBP:app Richard$ npm install -g bower
/Users/Richard/desktop/myproject/npm-global/bin/bower -> /Users/Richard/desktop/myproject/npm-global/lib/node_modules/bower/bin/bower
bower@1.7.9 /Users/Richard/desktop/myproject/npm-global/lib/node_modules/bower
Richards-MBP:app Richard$`

I think I messed up npm -g because a while ago I was trying to install gulp globally too, and I tried to do everything but I couldn't get it to work. Does anyone know how I can fix this problem?

**Comment by KenanY** [comment]
@richardxu100 Hmm, what is the output of

``` bash
npm config get prefix
```

**Comment by richardxu100** [comment]
Oh it's /Users/Richard/desktop/myproject/npm-global

**Comment by KenanY** [comment]
@richardxu100 That's why global modules are going to that directory then. You can change it to something else if you'd like with

``` bash
npm config set prefix ~/.npm-packages
```

**Comment by richardxu100** [comment]
Thank you a lot for your help!

**Comment by othiym23** [comment]
Closing as resolved.
