### ISSUE TITLE
"npm install" executes "npm pretest"

### ISSUE THREAD

**Issue by dragonprojects** [npm/npm#13035]
I found a similar tickets described that "prepublish" are executed during "npm install" (like #3059). This behavior seems to be fixed (it's not executed anymore in 4.x+).

But is there some documentation, discussion, plans what's with "pretest"?

Currently "npm install" executes "npm pretest" and I don't found any information why this behavior exists.

**Comment by legodude17** [comment]
Where is this in the code? I would like to look at it.

**Comment by dragonprojects** [comment]
Oh, I think I looked completely wrong. I retested my examples, its also in my examples the "prepublish" which is executed during the "npm install", not the "pretest".

So I think this ticket can be closed in favor of #10074.

Sry for the confusion. :(
