### ISSUE TITLE
I can't install anything.

### ISSUE THREAD

**Issue by saimonventura** [npm/npm#13044]
pi@raspberrypi:~/npm $ npm install arduino
npm ERR! Linux 4.4.11-v7+
npm ERR! argv "node" "/usr/local/bin/npm" "install" "arduino"
npm ERR! node v0.10.29
npm ERR! npm  v3.9.5
npm ERR! path /home/pi/.npm/serialport/3.1.2
npm ERR! code UNKNOWN
npm ERR! errno -1

npm ERR! UNKNOWN, mkdir '/home/pi/.npm/serialport/3.1.2'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/npm/npm-debug.log

**Comment by brewern** [comment]
You might try upgrading your version of Node. It looks like you're on a very old version, it may not work well with npm v3.

**Comment by christophehurpeau** [comment]
To install node 6 on a raspberry, do this:

```
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs
```

**Comment by saimonventura** [comment]
I done this.. and now the comand line node-red-start doens't work... How I start it now?
