### ISSUE TITLE
`npm install` within an extraneous package's subdirectory obliterates that directory.

### ISSUE THREAD

**Issue by rkirsling** [npm/npm#13043]
NPM v3 exhibits the following bug:

1. Create a new, empty project:
  `mkdir test && cd test && echo "{}" > package.json`

  (_Alternatively, just go to the root directory of any existing project._)

2. Install a new package without saving it (causing it to be marked it as `extraneous`):
  `npm install lodash`

3. Go into the new package's subdirectory and attempt to install its `devDependencies`:
  `cd node_modules/lodash && npm install`

→ A slew of `enoent` errors appear and `node_modules/lodash` (_still the working directory_) is totally gone!

**Comment by rkirsling** [comment]
Console output:
![image](https://cloud.githubusercontent.com/assets/2172590/16029680/9bee4fc2-319f-11e6-96f2-b610e7caae92.png)

**Comment by rkirsling** [comment]
This issue is even more striking when `npm link` is brought into the picture:
```bash
# After installing some package globally and linking it locally...
npm install -g jshint
npm link jshint

# ...if we use the absolute path, everything installs happily.
cd /usr/local/lib/node_modules/jshint
npm install 

# ...if we follow the symlink, we get repro: the globally-installed package is deleted!
cd node_modules/jshint
npm install
```

**Comment by legodude17** [comment]
I did not end up with this issue, everything works fine with me. Can you post the output of `npm version`? I get 
```
{ npm: '3.10.5',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '56.1',
  modules: '48',
  node: '6.0.0',
  openssl: '1.0.2g',
  uv: '1.9.0',
  v8: '5.0.71.35',
  zlib: '1.2.8' }
```

**Comment by rkirsling** [comment]
I experienced this with NPM 3.9.5 (Node 6.2.0), as the screenshot shows, but I can confirm that it does not occur in NPM 3.10.6 (Node 6.2.1).

Guess I may as close this then. :smile:
