### ISSUE TITLE
Make default --save semver option configurable

### ISSUE THREAD

**Issue by vcanfield** [npm/npm#13049]
Allowing the default semver range to to be configurable and passed on the command line will probably get more developers making a conscious choice about their semver ranges on a per-package basis.

Currently, it seems if you don't want to use the default semver, you're effectively punished by npm as you can no longer use any of the --save conveniences that it provides.

Most will pick the default semver range and not give it another thought simply because it's convenient. Maybe that's a good thing though, as ~ is probably better than everyone getting paranoid and using fixed ranges all the time.

Perhaps the issue of whether to use ~ or ^ is solved simply by making it configurable globally and at --save time?

Something like:

```
$ npm config set semver-range=close # set default to use 'close' range 
$ npm install --save [--range=^ | --range=compat[ible]] express # use ^
$ npm install --save [--range=~ | --range=close | --close] express # use ~
$ npm install --save [--no-range | --range=false] express # use exact version
```

or perhaps the range keyword is semver:

```
$ npm install --save [--semver=^ | --semver=compat[ible]] express # use ^
$ npm install --save [--semver=~ | --semver=close | --close] express # use ~
$ npm install --save [--no-semver | --semver=false] express # use exact version
```

Perhaps packages themselves could indicate how strict they are about semver. i.e. When npm installs a package with --save, it will use the package's 'preferred semver' if the user has not overridden 🍆. Ideally, everyone follows semver strictly but as there's no real way to enforce semver, this doesn't really happen in reality.

e.g. specifying preferred semver via package.json:

```
{
 "name": "express",
 "preferredSemver": "^", // patch and minors probably safe
}

{
 "name": "mux-demux",
 "preferredSemver": "~", // I follow strict semver
}

{
 "name": "underscore",
 "preferredSemver": "@" // no semver, please use fixed versions
}

{
 "name": "polyfill-webcomponents",
 "preferredSemver": "*" // yolo
}
```

**Comment by busches** [comment]
I'm confident what you're asking for already exists as an `npm config` option, it's called [save-prefix](https://docs.npmjs.com/misc/config#save-prefix).

cc\ @KenanY

**Comment by KenanY** [comment]
@vcanfield Is `save-prefix` sufficient for what you would like to do?

**Comment by KenanY** [comment]
Closing due to no reply after a month.
