### ISSUE TITLE
Completion causing command line to disappear

### ISSUE THREAD

**Issue by OliverJAsh** [npm/npm#13047]
I have an npm script called `watch`. When I use npm's tab completion, e.g.:

```
$ npm run wat<tab>
```

The autocompletion works, but my command line disappears and only the completed text is shown:

```
ch
```

Versions:

```
$ zsh --version
zsh 5.2 (x86_64-apple-darwin15.4.0)

$ npm --version
3.9.3
```

**Comment by OliverJAsh** [comment]
Any ideas on this one?

**Comment by busches** [comment]
@OliverJAsh are you still seeing this? Have you tried `bash` or any other terminal? The problem does not exist on Windows with `clink` in `3.10.5`.

**Comment by OliverJAsh** [comment]
Just tried and I can't reproduce in bash… hmm!

**Comment by busches** [comment]
But the latest version still fails in `zsh`?

**Comment by OliverJAsh** [comment]
Tested with npm 3.10.3 which ships with latest Node stable I believe (6.6.0)

**Comment by busches** [comment]
Is it only the run scripts autocompletion causing the error or does tabbing
on `npm r` to complete run also cause an issue?

On Thu, Sep 22, 2016 at 8:30 AM, Oliver Joseph Ash <notifications@github.com

**Comment by OliverJAsh** [comment]
- If I tab `npm r`, my command disappears for a second and then comes back
with a list of options beneath (rebuild, remove, run, etc.)
- If I tab `npm ru, my command disappears and then npm complete kicks in,
leaving my command line with only `n`
So I believe it's a general problem with npm autocompletion

It only happens the first time I try to using npm completion after opening
a shell. It is fine the second time round. That said, it's not rare for me
to be opening/closing shells frequently.
