### ISSUE TITLE
Error to install npm

### ISSUE THREAD

**Issue by kudumulagithub** [npm/npm#13046]
npm ERR! tar.unpack error reading C:\Users\kdu2kor\npm
npm ERR! addLocal Could not install C:\Users\kdu2kor\npm
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\
node_modules\npm\bin\npm-cli.js" "install" "npm" "-g"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5

npm ERR! 0-byte tarball
npm ERR! Please run `npm cache clean`
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\kdu2kor\npm-debug.log
[npm_debug.txt](https://github.com/npm/npm/files/313327/npm_debug.txt)

**Comment by christophehurpeau** [comment]
@kudumulagithub did you run `npm cache clean` ?

**Comment by brdeav39** [comment]
I am having the same exact issue. Tried npm cache clean and still the same thing.
