### ISSUE TITLE
NPM Install Failure (Darwin 15.5.0 ERR!)

### ISSUE THREAD

**Issue by willkilroy** [npm/npm#13055]
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5

npm ERR! version not found: socket.io@2.15.5
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

[npm-debug.txt](https://github.com/npm/npm/files/314636/npm-debug.txt)

**Comment by KenanY** [comment]
@willkilroy Can I see your `package.json`?

**Comment by willkilroy** [comment]
sure


{
    "name": "Will",
    "version": "0.0.1",
    "private": "true",
    "dependencies": {
        "express": "2.15.5",
        "socket.io": "2.15.5"
    }
}

**Comment by KenanY** [comment]
@willkilroy You are asking `npm` to install a version of `socket.io` which does not exist. You can view existing versions with

``` bash
$ npm info socket.io versions
```

You can do the same with `express` too:

``` bash
$ npm info express versions
```

**Comment by willkilroy** [comment]
Great it works, thank you very much

**Comment by KenanY** [comment]
Closing as resolved :tada:

**Comment by Ramesh209025** [comment]
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "ionic" "cordova"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8

npm ERR! Invalid name: "@ionic/app-generators"
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/sasken/npm-debug.log

I'm getting this error in mac while installing ionic cordova

**Comment by KenanY** [comment]
@Ramesh209025 Open a new ticket please.
