### ISSUE TITLE
protractor installation failed

### ISSUE THREAD

**Issue by gurchet** [npm/npm#13059]
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "protractor@2"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code UNABLE_TO_VERIFY_LEAF_SIGNATURE

npm ERR! unable to verify the first certificate
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

**Comment by EmmaRamirez** [comment]
Are you by chance using a proxy or vpn?

**Comment by gurchet** [comment]
I haven't used any proxy or vpn EmmaRamirez.
