### ISSUE TITLE
Cannot install packages

### ISSUE THREAD

**Issue by roblyn** [npm/npm#13052]
[npm-debug.txt](https://github.com/npm/npm/files/314297/npm-debug.txt)

I´m trying to install npm package on localhost without success, could you please help me?

Thanks

**Comment by KenanY** [comment]
@roblyn Are you behind a proxy by any chance?

**Comment by roblyn** [comment]
@KenanY  how can I check it?

**Comment by roblyn** [comment]
[npm-debug.txt](https://github.com/npm/npm/files/314337/npm-debug.txt

I close the MAMP and now comming this error!!!!!!

**Comment by roblyn** [comment]
I reinstall  node and try again but still not working 
but I get a different error 
[npm-debug.txt](https://github.com/npm/npm/files/314614/npm-debug.txt)

**Comment by legodude17** [comment]
This one is an error where cnpm cannot find the module. The http://cnpmjs.org/stylus was not found and returned 404. The message was HTML so npm broke while attempting to JSON.parse it.

**Comment by roblyn** [comment]
@legodude17  So what can I do?

**Comment by legodude17** [comment]
Try going to that url in your browser. Does it resolve into JSON?

**Comment by roblyn** [comment]
just open in the browser and then what?

**Comment by legodude17** [comment]
What does it say?

**Comment by roblyn** [comment]
@legodude17  still the same

**Comment by legodude17** [comment]
I got this. Is this the same thing you got. Try the command again.
[stylus.txt](https://github.com/npm/npm/files/314657/stylus.txt)

**Comment by roblyn** [comment]
@legodude17  Sorry I don´t understand, what should i do with that .txt file?

**Comment by legodude17** [comment]
Compare it to what you got when you opened http://r.cnpmjs.org/stylus in your browser.

**Comment by roblyn** [comment]
[npm-debug.txt](https://github.com/npm/npm/files/314668/npm-debug.txt)
this what I get

**Comment by legodude17** [comment]
What happens when you click the link up there? What does the browser show?

**Comment by legodude17** [comment]
Save it as a txt file and attach it to a comment.

**Comment by roblyn** [comment]
yes is the same file but what to do with that file?

**Comment by legodude17** [comment]
So the url works in the browser but not with npm? Try `curl http://r.cnpmjs.com/stylus` Also try changing the registry back to registry.npmjs.org and see if it works then.

**Comment by roblyn** [comment]
[npm-debug.txt](https://github.com/npm/npm/files/314687/npm-debug.txt)
Now I get this error

**Comment by roblyn** [comment]
ECONNRESET

**Comment by roblyn** [comment]
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "stylus"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code ECONNRESET

npm ERR! network tunneling socket could not be established, cause=Parse Error
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/EAK/npm-debug.log

**Comment by legodude17** [comment]
Have you followed the instructions?

**Comment by roblyn** [comment]
yes

**Comment by legodude17** [comment]
Do you have any proxy connections or VPNs?

**Comment by roblyn** [comment]
no proxy and vpn just on chrome hola.org

**Comment by legodude17** [comment]
Is the hola.org just on chrome or whole machine?

**Comment by roblyn** [comment]
just on chrome but is not the vpn, I was using stylus and no problems but from yesterday start problems with node and npm

**Comment by legodude17** [comment]
What happened yesterday? Anything big you remember?

**Comment by roblyn** [comment]
not really, i tried to install other packages "express"

**Comment by legodude17** [comment]
Speaking of other packages try installing something else and upload the results.

**Comment by roblyn** [comment]
said the same, I really don´t know what happens, reinstall its not helping :(

**Comment by legodude17** [comment]
Try running `npm config set registry https://registry.npmjs.org` to reset the registry and then try again.

**Comment by roblyn** [comment]
I try a lot of times with _https://github.com/npm/npm/issues_  and still not working. Now i get this error
[npm-debug.txt](https://github.com/npm/npm/files/316278/npm-debug.txt)

**Comment by roblyn** [comment]
I try with _npm config set registry https://registry.npmjs.org_ and still not working. but now I get this error.

[npm-debug.txt](https://github.com/npm/npm/files/316282/npm-debug.txt)

**Comment by legodude17** [comment]
It is still trying to access localhost:8888.

**Comment by roblyn** [comment]
that was the last try

**Comment by roblyn** [comment]
See here!!! with the registry 


[npm-debug.txt](https://github.com/npm/npm/files/316317/npm-debug.txt)

**Comment by roblyn** [comment]
![screen shot 2016-06-15 at 16 36 23](https://cloud.githubusercontent.com/assets/7288471/16084004/6219f0ca-3317-11e6-8a62-0429d1ca9739.png)

**Comment by legodude17** [comment]
Try running `curl https://registry.npmjs.org/stylus` and show the results.

**Comment by roblyn** [comment]
[result.txt](https://github.com/npm/npm/files/316564/result.txt)

**Comment by roblyn** [comment]
after that I run the code and get this error


[npm-debug.txt](https://github.com/npm/npm/files/316573/npm-debug.txt)

**Comment by legodude17** [comment]
Try `npm install stylus` and `npm install log`.

**Comment by roblyn** [comment]
When i run `npm install log.` I get this 

[npm-debug.txt](https://github.com/npm/npm/files/317056/npm-debug.txt)

**Comment by roblyn** [comment]
And runing `npm install stylus` I get this 
[npm-debug.txt](https://github.com/npm/npm/files/317059/npm-debug.txt)

**Comment by roblyn** [comment]
I was thinking and I got the first issues after update my OSX

**Comment by legodude17** [comment]
What were you on and what are you on now?

**Comment by legodude17** [comment]
Are you using a proxy?

**Comment by KenanY** [comment]
Closing as abandoned.
