### ISSUE TITLE
how to solve this problem

### ISSUE THREAD

**Issue by soujanyamypala** [npm/npm#13067]
[npm-debug.docx](https://github.com/npm/npm/files/317945/npm-debug.docx)
  please find the debug file errors when i am trying to install npm modules 

Thanks in advance.

**Comment by zhaoyaqin** [comment]
[npm-debug.log.zip](https://github.com/npm/npm/files/318001/npm-debug.log.zip)

**Comment by soujanyamypala** [comment]
[npm-debug.zip](https://github.com/npm/npm/files/318069/npm-debug.zip)

This is the new error I am gettin can someone please help me .
