### ISSUE TITLE
how to solve this error

### ISSUE THREAD

**Issue by ominfowave** [npm/npm#13066]
![capture](https://cloud.githubusercontent.com/assets/4697885/16106753/eedbfc4a-33b4-11e6-88c7-2053192f1624.PNG)

**Comment by visualfanatic** [comment]
I would remove `node_modules` directory, update `npm` and then try again.

**Comment by KenanY** [comment]
@ominfowave You may also try running `npm cache clean`.

**Comment by KenanY** [comment]
@ominfowave Hello, it has been over a week now with no reply from you. Are you still experiencing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
