### ISSUE TITLE
Dependency resolution fails on urls with commit

### ISSUE THREAD

**Issue by tejohnso** [npm/npm#13076]
npm version 3.9.5

A requires url-to/B.git#abcd
A requires C which requires url-to/B.git

Expected tree: 
A/node_modules/B (at abcd)
A/node_modules/C/node_modules/B

Resulting Behavior:
A/node_modules/B (not at abcd)
A/node_modules/C/node_modules/B (not at abcd)

Note: B's version in package.json is the same at both commits.  But given that a commit was specified in lieu of a version this should not matter.

**Comment by derhuerst** [comment]
I think I have a similar problem.

In a demo project, my `package.json` has only one dependency `hafas-client@derhuerst/hafas-client`. Running `npm i` with `npm@3.9.3`, `parse.js` inside `node_modules/hafas-client` is missing, even though [`derhuerst/hafas-client` at `5b0a4034cfa9f4edcb390c9bead2a3c17c8da177` contains it](https://github.com/derhuerst/hafas-client/tree/5b0a4034cfa9f4edcb390c9bead2a3c17c8da177).

**Comment by caligo-mentis** [comment]
The problem is still exist in npm v3.10.3. 

For us dependencies described as url with branch are broken, and we forced to use `npm link` instead.
