### ISSUE TITLE
Installation problems 

### ISSUE THREAD

**Issue by Rlupo07** [npm/npm#13074]
Hello,

I'm encountering numerous errors.

npm ERR! code 1
###### 
### Installing pac ...

\us\public\MULTI-Dev-Dept\PCC\RDU\Automation.modules\pac-v0.1.0.tgz
1 File(s) copied
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0

npm ERR! registry URL is required
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0

npm ERR! registry URL is required
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0

npm ERR! registry URL is required
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0

npm ERR! registry URL is required
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0

npm ERR! registry URL is required
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0

npm ERR! registry URL is required
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0

npm ERR! registry URL is required
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     C:\UI\qa\AdvisorApp\e2e\utils\npm-debug.log

**Comment by andersborgabiro** [comment]
I get something similar :,(

I updated Node.js and npm to latest before.

C:\WINDOWS\system32>npm install -g phonegap
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\ANDERS~2\AppData\Local\Temp\npm-10904-723a663d\registry.npmjs.org\pluralize\-\pluralize-0.0.4.tgz.4093653594' -> 'C:\Users\ANDERS~2\AppData\Local\Temp\npm-10904-723a663d\registry.npmjs.org\pluralize\-\pluralize-0.0.4.tgz'
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "phonegap"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
