### ISSUE TITLE
Getting npm ERR! not a package 

### ISSUE THREAD

**Issue by nscsekhar** [npm/npm#13072]
Hi,

I am looking to install a package grpcli as indicated in https://github.com/nathangoulding/grpcli. I am stuck with the following error. 

npm ERR! not a package /root/tmp/npm-10638-FJ5XCY0r/1466082978801-0.3723528948612511/tmp.tgz
(full log below)

Can you please let me know what could be the issue and how I can get over this?

Thanks,
Surya

~/surya/grpc# sudo npm install -g grpcli
npm http GET https://registry.npmjs.org/grpcli
npm http 304 https://registry.npmjs.org/grpcli
npm http GET https://registry.npmjs.org/bnf
npm http GET https://registry.npmjs.org/colors
npm http GET https://registry.npmjs.org/commander
npm http GET https://registry.npmjs.org/grpc
npm http GET https://registry.npmjs.org/ip
npm http GET https://registry.npmjs.org/rc
npm http GET https://registry.npmjs.org/prompt
npm http GET http://github.com/nathangoulding/stdrepl
npm http GET https://registry.npmjs.org/wait.for
npm http 304 https://registry.npmjs.org/commander
npm http 200 https://registry.npmjs.org/colors
npm http 304 https://registry.npmjs.org/prompt
npm http 304 https://registry.npmjs.org/bnf
npm http 304 https://registry.npmjs.org/wait.for
npm http 304 https://registry.npmjs.org/ip
npm http 304 https://registry.npmjs.org/rc
npm http 304 https://registry.npmjs.org/grpc
npm http 200 http://github.com/nathangoulding/stdrepl
npm ERR! not a package /root/tmp/npm-10638-FJ5XCY0r/1466082978801-0.3723528948612511/tmp.tgz
npm ERR! Error: ENOENT, open '/root/tmp/npm-10638-FJ5XCY0r/1466082978801-0.3723528948612511/package/package.json'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-32-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "grpcli"
npm ERR! cwd /root/surya/grpc
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /root/tmp/npm-10638-FJ5XCY0r/1466082978801-0.3723528948612511/package/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /root/surya/grpc/npm-debug.log
npm ERR! not ok code 0

**Comment by KenanY** [comment]
@nscsekhar `npm@1.3` is no longer supported. Could you try [updating](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm)?

**Comment by KenanY** [comment]
@nscsekhar Hello, it has been over a week now with no reply from you. Are you still experiencing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
