### ISSUE TITLE
sudo npm install grunt (--save-dev) fails on ubuntu 14.04.4 LTS

### ISSUE THREAD

**Issue by mvanonna** [npm/npm#13070]
Dear Npm,

I'm trying to install grunt as I need it for some testing-suite. I use sudo and have updated my 14.04 Ubuntu system. I'm using this system through Vagrant+VirtualBox (virtual machine), but this has never given me related errors. I've tried with and without the --save-dev option.

I've never used npm/grunt before, so I might be overlooking a simple thing.
Below is the last part of the npm-debug.log

If you require the full (long) log, please let me know.

Regards,

Matthijs

2315 error error rolling back Error: UNKNOWN, unlink '/home/vagrant/xAPI_LRS_Test/src/node_modules/grunt/node_modules/js-yaml/dist/js-yaml.js'
2315 error error rolling back  grunt@1.0.1 { [Error: UNKNOWN, unlink '/home/vagrant/xAPI_LRS_Test/src/node_modules/grunt/node_modules/js-yaml/dist/js-yaml.js']
2315 error error rolling back   errno: -1,
2315 error error rolling back   code: 'UNKNOWN',
2315 error error rolling back   path: '/home/vagrant/xAPI_LRS_Test/src/node_modules/grunt/node_modules/js-yaml/dist/js-yaml.js' }
2316 error Error: UNKNOWN, symlink '../rimraf/bin.js'

....

2318 error System Linux 3.13.0-83-generic
2319 error command "/usr/bin/nodejs" "/usr/bin/npm" "install" "grunt" "--save-dev"
2320 error cwd /home/vagrant/xAPI_LRS_Test/src
2321 error node -v v0.10.25
2322 error npm -v 1.3.10
2323 error path ../rimraf/bin.js
2324 error code UNKNOWN
2325 error errno -1
2326 verbose exit [ -1, true ]

P.s. I firstly tried to email this to the npm- group as recommended, but I got the following error:

Delivery to the following recipient failed permanently:

     npm-@googlegroups.com

Technical details of permanent failure:
The group npm-@googlegroups.com does not allow posting through email.

**Comment by KenanY** [comment]
@mvanonna `npm@1.3` is no longer supported. Please try [updating](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) first. If that doesn't help, you can also try using the [`--no-bin-links`](https://docs.npmjs.com/misc/config#bin-links) flag.

**Comment by KenanY** [comment]
@mvanonna Hello, it has been over a week now with no reply from you. Are you still experiencing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
