### ISSUE TITLE
can't install electron-screenshot-service

### ISSUE THREAD

**Issue by yihuds** [npm/npm#13083]
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/Cellar/node/6.2.1/bin/node" "/usr/local/bin/npm" "install" "electron-screenshot-service"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3
npm ERR! code ENOSELF

npm ERR! Refusing to install electron-screenshot-service as a dependency of itself
[npm-debug.txt](https://github.com/npm/npm/files/320111/npm-debug.txt)

**Comment by KenanY** [comment]
@yihuds Is the `"name"` property in your `package.json` set to `"electron-screenshot-service"`? Have you tried changing it to something else?

**Comment by KenanY** [comment]
@yihuds Hello, it has been just over a week now with no reply from you. Are you still experiencing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
