### ISSUE TITLE
npm install nonexistent version 

### ISSUE THREAD

**Issue by ilbonte** [npm/npm#13087]
`npm i -S bebel-core` installs version 999.999.999 that doesn't exists in the registry. (see: https://www.npmjs.com/package/babel-core)
![image](https://phabricator.babeljs.io/file/data/2sfcms62fwreacgtebn5/PHID-FILE-tvypqh5xlimuvxb5lcjx/pasted_file)

Also npm outdated says that the latest version available is 999.999.999

![image](https://cloud.githubusercontent.com/assets/7412876/16153580/36421964-34a7-11e6-84f7-38b52995c46c.png)

I'm using npm 3.9.3 on win10

**Comment by jayphelps** [comment]
I think the easiest solution is for babel to publish a version `999.999.999`. I think @hzoo can do that for us?

**Comment by legodude17** [comment]
Does it install successfully? If so, can you try to compare what is in node_modules/babel-core to what is on the GitHub repo for babel?

**Comment by ilbonte** [comment]
Just wanna say that I don't have this problem anymore. (Using npm 3.10.3)

**Comment by legodude17** [comment]
That's good. Can you close this @KenanY?
