### ISSUE TITLE
Unable to unpublish package

### ISSUE THREAD

**Issue by ReactorboY** [npm/npm#13085]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Sam\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'unpublish',
1 verbose cli   'Basic-Material-framework@1.0.6' ]
2 info using npm@3.9.6
3 info using node@v6.2.1
4 verbose config Skipping project config: C:\Users\Sam/.npmrc. (matches userconfig)
5 silly unpublish args[0] Basic-Material-framework@1.0.6
6 silly unpublish thing Result {
6 silly unpublish   raw: 'Basic-Material-framework@1.0.6',
6 silly unpublish   scope: null,
6 silly unpublish   name: 'Basic-Material-framework',
6 silly unpublish   rawSpec: '1.0.6',
6 silly unpublish   spec: '1.0.6',
6 silly unpublish   type: 'version' }
7 verbose getPublishConfig null
8 silly ls normalized Basic-Material-framework\1.0.6
9 silly gentlyRm C:\Users\Sam\AppData\Roaming\npm-cache\Basic-Material-framework\1.0.6 is being purged
10 verbose gentlyRm don't care about contents; nuking C:\Users\Sam\AppData\Roaming\npm-cache\Basic-Material-framework\1.0.6
11 silly mapToRegistry name Basic-Material-framework
12 silly mapToRegistry using default registry
13 silly mapToRegistry registry http://registry.npmjs.org/
14 silly mapToRegistry data Result {
14 silly mapToRegistry   raw: 'Basic-Material-framework',
14 silly mapToRegistry   scope: null,
14 silly mapToRegistry   name: 'Basic-Material-framework',
14 silly mapToRegistry   rawSpec: '',
14 silly mapToRegistry   spec: 'latest',
14 silly mapToRegistry   type: 'tag' }
15 silly mapToRegistry uri http://registry.npmjs.org/Basic-Material-framework
16 verbose get GET as part of write; not caching result
17 verbose request uri http://registry.npmjs.org/Basic-Material-framework?write=true
18 verbose request no auth needed
19 info attempt registry request try #1 at 6:53:28 PM
20 verbose request using bearer token for auth
21 verbose request id 9333eda5d8c59dca
22 http request GET http://registry.npmjs.org/Basic-Material-framework?write=true
23 http 200 http://registry.npmjs.org/Basic-Material-framework?write=true
24 verbose headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
24 verbose headers   etag: '"2MYZ7KA6EL6IGINDN3Q3S4GBW"',
24 verbose headers   'content-type': 'application/json',
24 verbose headers   'content-encoding': 'gzip',
24 verbose headers   'cache-control': 'max-age=0',
24 verbose headers   'transfer-encoding': 'chunked',
24 verbose headers   'accept-ranges': 'bytes',
24 verbose headers   date: 'Fri, 17 Jun 2016 13:23:30 GMT',
24 verbose headers   via: '1.1 varnish',
24 verbose headers   connection: 'keep-alive',
24 verbose headers   'x-served-by': 'cache-sin6920-SIN',
24 verbose headers   'x-cache': 'MISS',
24 verbose headers   'x-cache-hits': '0',
24 verbose headers   'x-timer': 'S1466169809.834051,VS0,VE800',
24 verbose headers   vary: 'Accept-Encoding' }
25 silly get cb [ 200,
25 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
25 silly get     etag: '"2MYZ7KA6EL6IGINDN3Q3S4GBW"',
25 silly get     'content-type': 'application/json',
25 silly get     'content-encoding': 'gzip',
25 silly get     'cache-control': 'max-age=0',
25 silly get     'transfer-encoding': 'chunked',
25 silly get     'accept-ranges': 'bytes',
25 silly get     date: 'Fri, 17 Jun 2016 13:23:30 GMT',
25 silly get     via: '1.1 varnish',
25 silly get     connection: 'keep-alive',
25 silly get     'x-served-by': 'cache-sin6920-SIN',
25 silly get     'x-cache': 'MISS',
25 silly get     'x-cache-hits': '0',
25 silly get     'x-timer': 'S1466169809.834051,VS0,VE800',
25 silly get     vary: 'Accept-Encoding' } ]
26 verbose get saving Basic-Material-framework to C:\Users\Sam\AppData\Roaming\npm-cache\registry.npmjs.org\Basic-Material-framework_3Fwrite_3Dtrue\.cache.json
27 verbose correctMkdir C:\Users\Sam\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
28 verbose unpublish removing attachments { shasum: '14453434a9e7c4dc5a1636a529ff2e1e070ff9c7',
28 verbose unpublish   tarball: 'http://registry.npmjs.org/Basic-Material-framework/-/Basic-Material-framework-1.0.6.tgz' }
29 verbose request uri http://registry.npmjs.org/Basic-Material-framework/-rev/4-06e8272106414a6af10d1f48520d79e9
30 verbose request sending authorization for write operation
31 info attempt registry request try #1 at 6:53:30 PM
32 verbose request using bearer token for auth
33 http request PUT http://registry.npmjs.org/Basic-Material-framework/-rev/4-06e8272106414a6af10d1f48520d79e9
34 http 500 http://registry.npmjs.org/Basic-Material-framework/-rev/4-06e8272106414a6af10d1f48520d79e9
35 verbose headers { 'content-type': 'application/json',
35 verbose headers   'cache-control': 'max-age=0',
35 verbose headers   'content-length': '80',
35 verbose headers   'accept-ranges': 'bytes',
35 verbose headers   date: 'Fri, 17 Jun 2016 13:23:32 GMT',
35 verbose headers   via: '1.1 varnish',
35 verbose headers   connection: 'keep-alive',
35 verbose headers   'x-served-by': 'cache-sin6920-SIN',
35 verbose headers   'x-cache': 'MISS',
35 verbose headers   'x-cache-hits': '0',
35 verbose headers   'x-timer': 'S1466169811.514064,VS0,VE916' }
36 info retry will retry, error on last attempt: Error: "cannot unpublish a version that is >24 hours old" : Basic-Material-framework
37 info attempt registry request try #2 at 6:53:42 PM
38 verbose request using bearer token for auth
39 http request PUT http://registry.npmjs.org/Basic-Material-framework/-rev/4-06e8272106414a6af10d1f48520d79e9
40 http 500 http://registry.npmjs.org/Basic-Material-framework/-rev/4-06e8272106414a6af10d1f48520d79e9
41 verbose headers { 'content-type': 'application/json',
41 verbose headers   'cache-control': 'max-age=0',
41 verbose headers   'content-length': '80',
41 verbose headers   'accept-ranges': 'bytes',
41 verbose headers   date: 'Fri, 17 Jun 2016 13:23:43 GMT',
41 verbose headers   via: '1.1 varnish',
41 verbose headers   connection: 'keep-alive',
41 verbose headers   'x-served-by': 'cache-sin6920-SIN',
41 verbose headers   'x-cache': 'MISS',
41 verbose headers   'x-cache-hits': '0',
41 verbose headers   'x-timer': 'S1466169822.953815,VS0,VE811' }
42 info retry will retry, error on last attempt: Error: "cannot unpublish a version that is >24 hours old" : Basic-Material-framework
43 info attempt registry request try #3 at 6:54:43 PM
44 verbose request using bearer token for auth
45 http request PUT http://registry.npmjs.org/Basic-Material-framework/-rev/4-06e8272106414a6af10d1f48520d79e9
46 http 500 http://registry.npmjs.org/Basic-Material-framework/-rev/4-06e8272106414a6af10d1f48520d79e9
47 verbose headers { 'content-type': 'application/json',
47 verbose headers   'cache-control': 'max-age=0',
47 verbose headers   'content-length': '80',
47 verbose headers   'accept-ranges': 'bytes',
47 verbose headers   date: 'Fri, 17 Jun 2016 13:24:45 GMT',
47 verbose headers   via: '1.1 varnish',
47 verbose headers   connection: 'keep-alive',
47 verbose headers   'x-served-by': 'cache-sin6920-SIN',
47 verbose headers   'x-cache': 'MISS',
47 verbose headers   'x-cache-hits': '0',
47 verbose headers   'x-timer': 'S1466169884.293783,VS0,VE858' }
48 verbose request invalidating C:\Users\Sam\AppData\Roaming\npm-cache\registry.npmjs.org\Basic-Material-framework on PUT
49 error unpublish Failed to update data
50 verbose stack Error: "cannot unpublish a version that is >24 hours old" : Basic-Material-framework
50 verbose stack     at makeError (C:\Users\Sam\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-client\lib\request.js:264:12)
50 verbose stack     at CachingRegistryClient.<anonymous> (C:\Users\Sam\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-client\lib\request.js:252:14)
50 verbose stack     at Request._callback (C:\Users\Sam\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-client\lib\request.js:172:14)
50 verbose stack     at Request.self.callback (C:\Users\Sam\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:200:22)
50 verbose stack     at emitTwo (events.js:106:13)
50 verbose stack     at Request.emit (events.js:191:7)
50 verbose stack     at Request.<anonymous> (C:\Users\Sam\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:1067:10)
50 verbose stack     at emitOne (events.js:101:20)
50 verbose stack     at Request.emit (events.js:188:7)
50 verbose stack     at IncomingMessage.<anonymous> (C:\Users\Sam\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:988:12)
51 verbose statusCode 500
52 verbose pkgid Basic-Material-framework
53 verbose cwd C:\Users\Sam
54 error Windows_NT 6.1.7601
55 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Sam\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "unpublish" "Basic-Material-framework@1.0.6"
56 error node v6.2.1
57 error npm  v3.9.6
58 error code E500
59 error "cannot unpublish a version that is >24 hours old" : Basic-Material-framework
60 error If you need help, you may report this error at:
60 error     <https://github.com/npm/npm/issues>
61 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@ReactorboY 

```
59 error "cannot unpublish a version that is >24 hours old" : Basic-Material-framework
```

Please see <http://blog.npmjs.org/post/141905368000/changes-to-npms-unpublish-policy>

**Comment by ReactorboY** [comment]
thnx @KenanY
