### ISSUE TITLE
npm 3 dependencies of bundled dependencies missing from package

### ISSUE THREAD

**Issue by stevengill** [npm/npm#13088]
So my package has some `bundleddependencies`. When I run `npm pack`, those `bundleddependencies` are included in the package but the `dependencies` of those `bundleddependenceis` are missing. This is because `npm@3` installs the dependencies as flat. So the deps of my bundleddependenceis are siblings instead of nested.

Two short term solutions for this problem

1) I use npm@2 and run `npm install` before I run `npm pack` to ensure the deps are nested.
2) I include the dependenceis of my `bundledDependencies` as `bundledDependenceis` in my `package.json`

If I'm npm installing the package, not having the dependencies of of `bundledDependencies` isn't a big deal as they will get fetched and installed. But I thought the point of `bundledDependenceis` were that they would be included in the package and wouldn't require extra fetching.

In Cordova, we `npm cache add` some modules instead of `npm install` them. This means, we are relying on `bundledDependencies` to include all necessary dependencies since we don't run `npm install`. In the next major version of Cordova, we are switching to using `npm install` instead of `npm cache add`. 

Thanks! You all are doing an amazing job :)

**Comment by othiym23** [comment]
So, you'll want to read [this chunk of the release notes](https://github.com/npm/npm/blob/b38573fae383aaaeaec0548c2ae616778a3b5dab/CHANGELOG.md#erk) of the new `npm@next` to understand what happened here (you might want to [read this (for context)](https://github.com/npm/npm/blob/b38573fae383aaaeaec0548c2ae616778a3b5dab/CHANGELOG.md#whoa) too). This was an entirely unintentional regression, and should be fixed now. Thanks so much for bringing this to our attention, Steve!
