### ISSUE TITLE
Angular Material Downloaded App doesnt work

### ISSUE THREAD

**Issue by Sabyasachi01** [npm/npm#13109]
I followed the steps mentioned in the following link to install the angular App from Angular Material Website.
Link : [](https://github.com/start-angular/sb-admin-angular/blob/master/README.md)
 But the website doesnt start .  It gives me the following error after I type npm start in the cmd. I am relatively new to angular JS. Can you please help me with this?
![image](https://cloud.githubusercontent.com/assets/20038608/16185793/f6f52334-36e3-11e6-8b8d-98faeeb0c283.png)

**Comment by KenanY** [comment]
@Sabyasachi01 Do you have `git` installed? Do you have a `"start"` script defined in your `package.json`?

**Comment by KenanY** [comment]
Closing as abandoned.
