### ISSUE TITLE
I can't npm install express --save

### ISSUE THREAD

**Issue by TakhirMirzaev** [npm/npm#13107]
Takhirs-iMac:~ takhir$ npm install express --save
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "express" "--save"
npm ERR! node v4.4.5
npm ERR! npm  v3.9.6
npm ERR! code ENOSELF

npm ERR! Refusing to install express as a dependency of itself
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/takhir/npm-debug.log
Takhirs-iMac:~ takhir$

**Comment by EmmaRamirez** [comment]
Have you tried making sure that your package.json doesn't list your project's name as "express"? This error usually occurs when the name of your project and of the dependency are the same.

**Comment by TakhirMirzaev** [comment]
Thank you very much you right. It's working

**Comment by KenanY** [comment]
Closing as resolved.
