### ISSUE TITLE
how could this happen?

### ISSUE THREAD

**Issue by calidion** [npm/npm#13112]
waterline version formerly 0.12.2,
current 0.1.4?
what's wrong and how could this be possible?

**Comment by othiym23** [comment]
This is most likely a question for the [`waterline`](https://github.com/balderdashy/waterline) maintainers, but I'll leave it open for now.

**Comment by calidion** [comment]
@othiym23  it is a problem of npm too.
npm should prevent a package from releasing a version that is lower than previous version.

**Comment by othiym23** [comment]
@calidion Why? It's quite common for developers to be supporting multiple release lines of a package. npm itself does this with `npm@latest` (`npm@3`) and `npm@lts` (`npm@2`), and while it's not common for `latest` to go backwards, it's neither unusual nor erroneous on its own for developers to do so.

**Comment by calidion** [comment]
@othiym23 
it is obvious that the lastest version should be the one that is of the highest version & latest updated,
not the one that patches a very old version.

waterline for instance:
```
npm show waterline@latest version
```
should show the version:
```
waterline@0.12.2
```
instead of 
```
waterline@0.1.4
````
npm should be aware of the version greatness and the latest labelled version should ignore those updates that are not on top of the largest version to avoid version shuttling

**Comment by othiym23** [comment]
As I said above, it's up to the publishers to decide which version is latest, and it's quite common (e.g. with prerelease versions) to publish a version to `latest` that sorts lower than previously-published versions. `latest` is a [`dist-tag`](https://docs.npmjs.com/cli/dist-tag) that's set either by `npm publish` or `npm dist-tag add`; it's not an intrinsic property of the version. This behavior isn't a bug, nor is it likely to change, as a lot of projects make pretty heavy use of it. Given that, I think it's now appropriate to close this issue as resolved.

**Comment by calidion** [comment]
and further more, it would be nice to warn a none highest version install.
and gives top versions of each release respectively if possible.

**Comment by calidion** [comment]
if npm is publish in sequence:
3, 2, 1
which one this the latest?
and which one would be installed by
```
npm install -g npm
```
if packages only need a lower version to be updated.
what will happen?

as i have tested, the result is as follows:
```
npm publish
+ bad-version@0.0.1
npm publish
+ bad-version@0.2.1
npm publish
+ bad-version@0.0.2
npm show bad-version@latest version
0.0.2
npm install -g bad-version
/home/eric/.nvm/versions/node/v4.2.3/lib
└── bad-version@0.0.2 
```
Is this a reasonable result?

**Comment by othiym23** [comment]
it's up to you, _as the publisher_, to define whether that's a reasonable result for your package. This is why `npm publish --tag=<dist-tag>` exists. I see why you consider this a footgun, but it's a feature used by a large number of high-profile packages and ecosystems, including npm itself.

**Comment by calidion** [comment]
will there be an improvement on this?
I don't think it is intuitive to package publishers.

**Comment by calidion** [comment]
@othiym23 
how to make a none current version current?

**Comment by calidion** [comment]
solved by
```
npm dist-tag add xxx@xxx latest
````
