### ISSUE TITLE
I couldn't install anything...

### ISSUE THREAD

**Issue by chankalun** [npm/npm#13122]
And here are the errors I got... Can someone help me please ><

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "mongodb"
npm ERR! node v4.2.3
npm ERR! npm  v3.5.1
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'npm-autoinit/autoinit'

**Comment by KenanY** [comment]
@chankalun Are you still seeing this issue?

**Comment by KenanY** [comment]
Closing due to no response.
