### ISSUE TITLE
Unable to install file-system module at npm 

### ISSUE THREAD

**Issue by ravendra-payasi** [npm/npm#13132]
I am executing the commad npm install fs in ubuntu system. its given me message.
Linux 4.4.0-24-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "file-system"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2

npm ERR! Cannot read property 'target' of null
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/lib/node_modules/express/npm-debug.log
[unable-install.txt](https://github.com/npm/npm/files/325775/unable-install.txt)

**Comment by CodeLenny** [comment]
[fs](https://nodejs.org/api/fs.html) is preinstalled in Node, and is not in the NPM repository.
