### ISSUE TITLE
missing script:start

### ISSUE THREAD

**Issue by pawan-mobileprogramming** [npm/npm#13131]
Hi ,

when i try to run "npm start command " its give below error .

$ npm start
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5

npm ERR! missing script: start
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by suyuTech** [comment]
is there a script with the key start in scripts object of your package.json file?

**Comment by pawan-mobileprogramming** [comment]
when i go to C:\Program Files\nodejs\node_modules\npm . In npm folder there is one package.json file which is below 

{
  "version": "2.15.5",
  "name": "npm",
  "description": "a package manager for JavaScript",
  "keywords": [
    "package manager",
    "modules",
    "install",
    "package.json"
  ],
  "preferGlobal": true,
  "config": {
    "publishtest": false
  },
  "homepage": "https://docs.npmjs.com/",
  "author": "Isaac Z. Schlueter <i@izs.me> (http://blog.izs.me)",
  "repository": {
    "type": "git",
    "url": "https://github.com/npm/npm"
  },
  "bugs": {
    "url": "https://github.com/npm/npm/issues"
  },
  "directories": {
    "doc": "./doc",
    "man": "./man",
    "lib": "./lib",
    "bin": "./bin"
  },
  "main": "./lib/npm.js",
  "bin": "./bin/npm-cli.js",
  "dependencies": {
    "abbrev": "~1.0.7",
    "ansi": "~0.3.1",
    "ansicolors": "~0.3.2",
    "ansistyles": "~0.1.3",
    "archy": "~1.0.0",
    "async-some": "~1.0.2",
    "block-stream": "0.0.9",
    "char-spinner": "~1.0.1",
    "chmodr": "~1.0.2",
    "chownr": "~1.0.1",
    "cmd-shim": "~2.0.2",
    "columnify": "~1.5.4",
    "config-chain": "~1.1.10",
    "dezalgo": "~1.0.3",
    "editor": "~1.0.0",
    "fs-vacuum": "~1.2.9",
    "fs-write-stream-atomic": "~1.0.8",
    "fstream": "~1.0.8",
    "fstream-npm": "~1.0.7",
    "github-url-from-git": "~1.4.0",
    "github-url-from-username-repo": "~1.0.2",
    "glob": "~7.0.3",
    "graceful-fs": "~4.1.4",
    "hosted-git-info": "~2.1.4",
    "inflight": "~1.0.4",
    "inherits": "~2.0.1",
    "ini": "~1.3.4",
    "init-package-json": "~1.9.3",
    "lockfile": "~1.0.1",
    "lru-cache": "~4.0.1",
    "minimatch": "~3.0.0",
    "mkdirp": "~0.5.1",
    "node-gyp": "~3.3.1",
    "nopt": "~3.0.6",
    "normalize-git-url": "~3.0.2",
    "normalize-package-data": "~2.3.5",
    "npm-cache-filename": "~1.0.2",
    "npm-install-checks": "~1.0.7",
    "npm-package-arg": "~4.1.0",
    "npm-registry-client": "~7.1.0",
    "npm-user-validate": "~0.1.2",
    "npmlog": "~2.0.3",
    "once": "~1.3.3",
    "opener": "~1.4.1",
    "osenv": "~0.1.3",
    "path-is-inside": "~1.0.0",
    "read": "~1.0.7",
    "read-installed": "~4.0.3",
    "read-package-json": "~2.0.4",
    "readable-stream": "~2.1.2",
    "realize-package-specifier": "~3.0.1",
    "request": "~2.72.0",
    "retry": "~0.9.0",
    "rimraf": "~2.5.2",
    "semver": "~5.1.0",
    "sha": "~2.0.1",
    "slide": "~1.1.6",
    "sorted-object": "~2.0.0",
    "spdx-license-ids": "~1.2.1",
    "strip-ansi": "~3.0.1",
    "tar": "~2.2.1",
    "text-table": "~0.2.0",
    "uid-number": "0.0.6",
    "umask": "~1.1.0",
    "validate-npm-package-license": "~3.0.1",
    "validate-npm-package-name": "~2.2.2",
    "which": "~1.2.8",
    "wrappy": "~1.0.1",
    "write-file-atomic": "~1.1.4"
  },
  "bundleDependencies": [
    "abbrev",
    "ansi",
    "ansi-regex",
    "ansicolors",
    "ansistyles",
    "archy",
    "async-some",
    "block-stream",
    "char-spinner",
    "chmodr",
    "chownr",
    "cmd-shim",
    "columnify",
    "config-chain",
    "dezalgo",
    "editor",
    "fs-vacuum",
    "fs-write-stream-atomic",
    "fstream",
    "fstream-npm",
    "github-url-from-git",
    "github-url-from-username-repo",
    "glob",
    "graceful-fs",
    "hosted-git-info",
    "imurmurhash",
    "inflight",
    "inherits",
    "ini",
    "init-package-json",
    "lockfile",
    "lru-cache",
    "minimatch",
    "mkdirp",
    "node-gyp",
    "nopt",
    "normalize-git-url",
    "normalize-package-data",
    "npm-cache-filename",
    "npm-install-checks",
    "npm-package-arg",
    "npm-registry-client",
    "npm-user-validate",
    "npmlog",
    "once",
    "opener",
    "osenv",
    "path-is-inside",
    "read",
    "read-installed",
    "read-package-json",
    "readable-stream",
    "realize-package-specifier",
    "request",
    "retry",
    "rimraf",
    "semver",
    "sha",
    "slide",
    "sorted-object",
    "spdx-license-ids",
    "strip-ansi",
    "tar",
    "text-table",
    "uid-number",
    "umask",
    "validate-npm-package-license",
    "validate-npm-package-name",
    "which",
    "wrappy",
    "write-file-atomic"
  ],
  "devDependencies": {
    "deep-equal": "~1.0.1",
    "marked": "~0.3.5",
    "marked-man": "~0.1.5",
    "npm-registry-couchapp": "~2.6.12",
    "npm-registry-mock": "~1.0.1",
    "require-inject": "~1.3.1",
    "sprintf-js": "~1.0.3",
    "tacks": "~1.2.1",
    "tap": "~5.7.1"
  },
  "scripts": {
  "start": "node server.js",
    "dumpconf": "env | grep npm | sort | uniq",
    "prepublish": "node bin/npm-cli.js prune --prefix=. --no-global && rimraf test/*/*/node_modules && make doc-clean && make -j4 doc",
    "preversion": "bash scripts/update-authors.sh && git add AUTHORS && git commit -m \"update AUTHORS\" || true",
    "tap": "tap --timeout 240",
    "test": "npm run test-tap",
    "test-tap": "npm run tap -- \"test/tap/*.js\""
  },
  "license": "Artistic-2.0"
}




and in npm folder there is no server.js or app.js file.

**Comment by suyuTech** [comment]
Well,I mean that the package.json file I mentioned above is in directory where you run "npm start", rather than the package.json in npm folder.

**Comment by pawan-mobileprogramming** [comment]
thanks suyu. I am now able to run npm start.

**Comment by KenanY** [comment]
Closing as resolved.
