### ISSUE TITLE
npm ERR! missing script: minify

### ISSUE THREAD

**Issue by test313918** [npm/npm#13141]
C:\Users\amane\Desktop\IonicApps\Example>npm run minify
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "minify"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5

npm ERR! missing script: minify
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\amane\Desktop\IonicApps\Example\npm-debug.log

**Comment by KenanY** [comment]
@test313918 Do you have a `"minify"` script defined in your `package.json`?

**Comment by KenanY** [comment]
Closing as abandoned.
