### ISSUE TITLE
version not found: @angular/router-deprecated@2.0.0-rc.3

### ISSUE THREAD

**Issue by rajarul** [npm/npm#13143]
version not found: @angular/router-deprecated@2.0.0-rc.3 
[npm-debug - Copy.txt](https://github.com/npm/npm/files/327411/npm-debug.-.Copy.txt)

**Comment by watilde** [comment]
The version `2.0.0-rc.3 ` of the `@angular/router-deprecated` seems isn't shipped yet.
```
$ npm view @angular/router-deprecated versions
[ '0.0.0-6', '0.0.0-7', '2.0.0-rc.0', '2.0.0-rc.1', '2.0.0-rc.2' ]
```
