### ISSUE TITLE
Error while "npm install" in 5 MIN QUICKSTART example of Angular JS

### ISSUE THREAD

**Issue by harishcheruku** [npm/npm#13147]
[npm-debug.txt](https://github.com/npm/npm/files/327763/npm-debug.txt)

I am fetting following erros while executing "npm install" command.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "E:\NodeJSPlayGround\node.exe" "E:\NodeJSPlayGround\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5

npm ERR! No compatible version found: @angular/router-deprecated@2.0.0-rc.3
npm ERR! Valid install targets:
npm ERR! 2.0.0-rc.2, 2.0.0-rc.1, 2.0.0-rc.0, 0.0.0-7, 0.0.0-6
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     E:\NodePlayGround\MyApp\npm-debug.log

**Comment by jvargas01** [comment]
I am having the same issue.

**Comment by jvargas01** [comment]
I got it to install. It seems that the @angular/router-deprecated@2.0.0-rc.3 has not been released yet.
I changed all references to rc.3  to rc.2

I also install these packages globally.
npm install -g concurrently
npm install -g lite-server
npm install -g typescript

Hope this helps someone.

**Comment by DavidTheProgrammer** [comment]
@jvargas01 thanks. it's worked for now. a few scary errors, but i think it's got me all set up

**Comment by jvargas01** [comment]
Awesome. Glad to hear.
