### ISSUE TITLE
Cannot unpublish a private package

### ISSUE THREAD

**Issue by CharlieDLee** [npm/npm#13140]
I am receiving the following when trying to unpublish a private package.  There should not be any consumers of this package as it was only a test package and I want to remove it now.

I have deprecated the package to ensure nobody uses it accidentally, but I would like to unpublish it completely.

`C:\Users\leec>npm unpublish @ridgian/mail
npm ERR! Refusing to delete entire project.
npm ERR! Run with --force to do this.
npm ERR! npm unpublish [<@scope>/]<pkg>[@<version>]

C:\Users\leec>npm unpublish @ridgian/mail --force
npm WARN using --force I sure hope you know what you are doing.
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "unpublish" "@ridgian/mail" "--force"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code E400

npm ERR! Registry returned 400 for DELETE on https://registry.npmjs.org/@ridgian%2fmail/-rev/8-f7c0f037b190809324249cfe05ba1d7a
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\leec\npm-debug.log`

**Comment by mabc224** [comment]
+1

**Comment by KenanY** [comment]
@CharlieDLee Could you try sending an email to `support@npmjs.com`?

**Comment by mabc224** [comment]
i am trying to delete package from my private registry, but getting error.
I have already sent an email to support but did not got response.

```
npm unpublish @c2cs/c2cs-devlib-core@1.2.21
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Arsalan\\AppData
\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "unpublish" "@c2cs/c2cs-devl
ib-core@1.2.21"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.6
npm ERR! code E400

npm ERR! Registry returned 400 for DELETE on https://registry.npmjs.org/@c2cs%2f
c2cs-devlib-core/-rev/3-6675923dc9e17565aed2da60e8b2455f
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Arsalan\npm-debug.log
```

**Comment by KenanY** [comment]
Closing since it's been a week now with no further activity here, and stuff like this can really only be dealt with through `support@npmjs.com`. These errors are coming from the registry, not `npm`, and this issue tracker is for `npm` issues. If I am mistaken then one of the core devs can reopen :)
