### ISSUE TITLE
bug: npm runs post-install for all directly installed modules

### ISSUE THREAD

**Issue by dominictarr** [npm/npm#13146]
npm runs the post-install scripts not just for the module you are currently installing,
but for all the top(bottom?) level modules. to reproduce use `--loglevel info`
install several modules, then install another module with `--loglevel info`. You'll see the post-install scripts run for all the modules.

This only happens for the modules you directly installed via typing `npm install modulename` but not those module's recursive dependencies.

For modules without compile scripts does not cause a big problem, but if you use a binary addon that must be compiled it makes installs take a very long time indeed - and given that sometimes complication fails for strange reasons, that can mean that a currently working install breaks because you installed a completely unrelated module, which as you might imagine is very frustrating.

**Comment by yalamber** [comment]
I just experienced same issue. 
node version: 6.2.2
npm version: 3.9.5

**Comment by idiotWu** [comment]
Same issue with:
node: v6.2.1
npm: 3.9.3
