### ISSUE TITLE
Error (REACT-newbie)

### ISSUE THREAD

**Issue by AbsarF** [npm/npm#13150]
Hi..
Pls help me to resolve the following error..
This error happens when i issue the command "npm run production"...
(I am sorry if I posted this problem wrongly in this forum as I was directed from the error msg)

many thanks
(new convert to REACT)
-----------------------------------------------
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "production"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5

npm ERR! missing script: production
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by kellyjandrews** [comment]
Does your `package.js` file have a `production` command in `scrips`?

```
{ "scripts" :
  { 
    "production" : "something"
  }
}
```

https://docs.npmjs.com/misc/scripts

**Comment by AbsarF** [comment]
Thanks god your reply Andrew...
Something went wrong with the npm installation ..after re-installing everything went fine..
