### ISSUE TITLE
`npm install` output messy code

### ISSUE THREAD

**Issue by UniFreak** [npm/npm#13161]
I'm in Windows7 64bit, system language is Chinese.

every time when I'm trying to install something , say jshint, output like this:

![qq 20160623233657](https://cloud.githubusercontent.com/assets/7945546/16309567/bdb8c5ac-399b-11e6-9d69-f1fc9c5b7d69.png)

**Comment by KenanY** [comment]
@UniFreak `npm --version`?

**Comment by UniFreak** [comment]
@KenanY 3.3.6

**Comment by KenanY** [comment]
@UniFreak Does this also occur with newer versions of `npm`?

**Comment by UniFreak** [comment]
@KenanY I upgrade npm to 3.10.3, now the issue disappear. Thank you!
