### ISSUE TITLE
Unable to install from GitHub URL in package.json

### ISSUE THREAD

**Issue by HouCoder** [npm/npm#13168]
**Environment:**

Node version: `v0.10.42`
Npm version: `1.3.6`
OS: `CentOS release 6.5 (Final)`

**Issue detail:**

In [package.json | npm Documentation#GitHub URLs](https://docs.npmjs.com/files/package.json#github-urls), it says:

> As of version 1.1.65, you can refer to GitHub urls as just "foo": "user/foo-project".

I tried `$ npm install juwai/juwai-lint-cfg` and it completed successfully, then I add `"juwai-lint-cfg": "juwai/juwai-lint-cfg"` in my package.json and did `$ npm install`, however it fails with this error message:

```shell
[vagrant@vagrant-centos65 test]$ npm install
npm http GET https://registry.npmjs.org/juwai-lint-cfg
npm http 404 https://registry.npmjs.org/juwai-lint-cfg
npm ERR! TypeError: Object.keys called on non-object
npm ERR!     at Function.keys (native)
npm ERR!     at installTargetsError (/usr/lib/node_modules/npm/lib/cache.js:708:24)
npm ERR!     at /usr/lib/node_modules/npm/lib/cache.js:638:10
npm ERR!     at saved (/usr/lib/node_modules/npm-registry-client/lib/get.js:148:7)
npm ERR!     at /usr/lib/node_modules/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:108:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-431.3.1.el6.x86_64
npm ERR! command "node" "/usr/bin/npm" "install"
npm ERR! cwd /home/vagrant/test
npm ERR! node -v v0.10.42
npm ERR! npm -v 1.3.6
npm ERR! type called_on_non_object
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/vagrant/test/npm-debug.log
npm ERR! not ok code 0
```

This is my package.json content:

```json
{
  "private": true,
  "dependencies": {
    "juwai-lint-cfg": "juwai/juwai-lint-cfg"
  }
}
```

So my question is what's the difference between these two npm package installation?

**Comment by KenanY** [comment]
@HouCoder `npm@1` is no longer supported. Does this also occur after updating to `npm@2` or `npm@3`?

**Comment by HouCoder** [comment]
@KenanY No, it only happens on `npm@1`.

**Comment by KenanY** [comment]
@HouCoder Glad to hear that :)

**Comment by KenanY** [comment]
Closing as not an issue with recent, supported versions of `npm`.
