### ISSUE TITLE
EBUSY:resource busy or locked, open c:\users\user\NTUSER.DAT 

### ISSUE THREAD

**Issue by ArunaLanda** [npm/npm#13178]
### I'm opening this issue because:

  - [ ] npm is crashing
  - [ ] npm is producing an incorrect install
  - [x] npm is doing something I don't understand
  - [ ] other (_see below for feature requests_)

**Comment by KenanY** [comment]
@ArunaLanda Not enough information provided. Is there a `npm-debug.log` file that you can upload to [gist.github.com](https://gist.github.com/)?

**Comment by bennybriel** [comment]
I got similar error. What I did was that, I disabled my Bytefence anti-virus  and it works properly

**Comment by KenanY** [comment]
Closing since further information was never provided.
