### ISSUE TITLE
Does npminclude still exist?

### ISSUE THREAD

**Issue by mapsam** [npm/npm#13171]
Hey! I am looking at packaging some `.hpp` files in a package, and want to ignore a bunch of related build files in the `.npmignore` file, which falls out of sync quickly. I searched for `.npminclude` and see it was [implemented a long time ago](https://github.com/npm/npm/issues/94). I tried using `npm pack` to test it out, but no luck. Is there still support for `.npminclude` files?

npm version: `2.15.5`

**Comment by othiym23** [comment]
A simple question with a simple answer: no. See a1c926184ce263ebc754d62da381c8350a110cde and 4b25fe78b9a7d94af2f52d347f3c7a2b7fa9b5e4 for details. Thanks for your time!

**Comment by mapsam** [comment]
Thanks for the clear answer @othiym23!
