### ISSUE TITLE
too slow to search for packages

### ISSUE THREAD

**Issue by justin-romano** [npm/npm#13172]
This is for the website mainly. But it is way to slow to search. I would expect to get results back sub second.

**Comment by EmmaRamirez** [comment]
Hi @justin-romano, search is currently broken on the npm CLI itself. As for the website search, any issues there should be filed to the [npm website issues](https://github.com/npm/newww/issues). In the meantime, check out [npms.io](https://npms.io/)!

**Comment by zkat** [comment]
https://github.com/npm/npm/pull/13746 should improve the situation a bit, but it's gonna be a while before the overall search story is better.
