### ISSUE TITLE
Can't update Cordova to latest version

### ISSUE THREAD

**Issue by marcodafonseca** [npm/npm#13176]
### I'm opening this issue because:
  - [ ] npm is erroring when I try update to the latest version of Cordova

#### Node version:

4.4.5

#### npm version:

2.15.5

#### How did you try update Cordova?

npm install -g cordova

#### Operating system version and distribution:

Windows 10 Pro

#### Containerization or virtualization environment:

None

#### Are you using [a proxy](https://docs.npmjs.com/misc/config#proxy)?

No

#### What problem are you seeing?
Error message displayed:
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5

npm ERR! shasum check failed for C:\Users\Marco\AppData\Local\Temp\npm-8988-26a02fbb\registry.npmjs.org\npm\-\npm-2.15.8.tgz
npm ERR! Expected: 9ada0f2f8a17575cf0238ffac79ebd051236bf66
npm ERR! Actual:   82430ef40222a2ecd7522799a11e7bd1ff2d244b
npm ERR! From:     https://registry.npmjs.org/npm/-/npm-2.15.8.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

#### Attached log
[npm-debug.txt](https://github.com/npm/npm/files/333052/npm-debug.txt)

#### How can the problem be reproduced?
Run the above command

**Comment by KenanY** [comment]
@marcodafonseca Have you tried running `npm cache clean`?

**Comment by marcodafonseca** [comment]
This was my bad. Running the command from command prompt in admin mode sorted me out.
