### ISSUE TITLE
GC error during npm install

### ISSUE THREAD

**Issue by Klathmon** [npm/npm#13192]
### I'm opening this issue because:
- [X] npm is crashing
- [ ] npm is producing an incorrect install
- [ ] npm is doing something I don't understand
- [ ] other (_see below for feature requests_)
#### Node version:

v6.2.0
#### npm version:

3.10.2
#### How did you install Node and npm?

nodejs.org installer
#### Operating system version and distribution:

Windows 10
#### Containerization or virtualization environment:

Using the "Git bash" shell (uname -a gives `MINGW64_NT-10.0 Atlas 2.5.0(0.295/5/3) 2016-03-31 18:47 x86_64 Msys`) However I tried it without and got the same result using cmd.exe
#### Are you using [a proxy](https://docs.npmjs.com/misc/config#proxy)?

no
#### What problem are you seeing?

GC error while trying to run npm install on a fairly large project. (GC in old space requested).

Full error at the bottom of the message. Regardless of how many times I try to run it, it always fails with the same error message and at the same point (both with the output, and always within a second or 2 of each run).
#### How can the problem be reproduced?

for me it's just running npm install on a large package.json which includes about 50 devDependencies and about 15 dependencies (including 2 git repos).
#### Error message:

```
npm WARN deprecated sass-loader@3.2.2: This patch may introduce a breaking change in certain scenarios, see https://github.com/jtangel
der/sass-loader/pull/250
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated js-toolkit@0.0.5: Use sb-promisify instead
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
[               ...] | extract:core-js: verb gentlyRm don't care about contents; nuking A:\Projects\ScanTrac-Client\node_modules\.sta
<--- Last few GCs --->

  368729 ms: Mark-sweep 1219.3 (1434.7) -> 1219.2 (1434.7) MB, 1296.0 / 0 ms [allocation failure] [GC in old space requested].
  370019 ms: Mark-sweep 1219.2 (1434.7) -> 1219.2 (1434.7) MB, 1290.4 / 0 ms [allocation failure] [GC in old space requested].
  371330 ms: Mark-sweep 1219.2 (1434.7) -> 1219.1 (1434.7) MB, 1311.0 / 0 ms [last resort gc].
  372629 ms: Mark-sweep 1219.1 (1434.7) -> 1219.1 (1434.7) MB, 1298.2 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 000002D58C2C9E79 <JS Object>
    1: generatePreAndPost(aka generatePreAndPost) [C:\Users\gregb\AppData\Roaming\npm\node_modules\npm\node_modules\npmlog\node_module
s\gauge\render-template.js:37] [pc=0000032FE6849089] (this=000002D58C204189 <undefined>,baseItem=000002E00305A5E1 <a TemplateItem with
 map 000000E304A1D389>,parentValues=000002E003059EC9 <an Object with map 000000E304A77C71>)
    2: cloneAndObjectify(aka cloneA...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
```

**Comment by AgNm** [comment]
I'm also facing this issue while installing cordova : npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

**Comment by Klathmon** [comment]
I moved back to NPM 3.9.6 and it's working in that version, so that's my current workaround.

**Comment by AgNm** [comment]
My npm current version 2.15.5. How can i upgrade?

**Comment by Klathmon** [comment]
It depends on your node version and os platform.

For most you should be able to just do `npm install -g npm@x.x.x` replacing `x.x.x` with the version you want. (you can look (here)[https://github.com/npm/npm/releases] for npm releases)

Until fairly recently, you basically need to upgrade your node.js install on windows to be able to upgrade NPM.

Also, you probably shouldn't jump from 2.x.x to 3.x.x without really understanding what's going on. I don't know enough about it to help you, but I do know that the 2.x branch is still being updated, and blindly jumping from 2 to 3 probably will cause some issues.

**Comment by Eng163word** [comment]
Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
anybody help me out?

**Comment by pyaria** [comment]
Klathmon's solution worked like a charm for me!

I'm new to node.js, so I might be misunderstanding this, but before I downgraded to npm 3.9.6 I ran $npm ls minimatch and got this:

├── minimatch@3.0.2
└─┬ webpack-windows@0.0.3
  └─┬ map-files@0.3.0
    └─┬ globby@0.1.1
      └─┬ glob@4.5.3
        └── minimatch@2.0.10

Am I misunderstanding something or is it saying that minimatch@3.0.2 depends on minimatch@2.0.10???

**Comment by KenanY** [comment]
@pyaria Misunderstanding.

**Comment by mastershaig** [comment]
same issue

**Comment by axreid** [comment]
same issue on clean clone of angular

**Comment by suiwenfeng** [comment]
same issue @npm3.10.8 while do npm search.

**Comment by KenanY** [comment]
@suiwenfeng That is not the same as this issue. Update to `npm@4` if you wanna use `npm search`.

**Comment by suiwenfeng** [comment]
@KenanY `npm install npm@latest -g`

Thanks, Greate Improve.
