### ISSUE TITLE
Npm error

### ISSUE THREAD

**Issue by MaxPrime05** [npm/npm#13197]
Installing dependencies, please wait...
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\MAXSIE~1\AppData\Local\Temp\npm-3124-813e0a50\registry.npmjs.org\async\-\async-1.5.2.tgz.1460168524' -> 'C:\Users\MAXSIE~1\AppData\Local\Temp\npm-3124-813e0a50\registry.npmjs.org\async\-\async-1.5.2.tgz'
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.9.1
npm ERR! npm  v3.7.3

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\MAXSIE~1\AppData\Local\Temp\npm-3124-813e0a50\registry.npmjs.org\minimatch\-\minimatch-3.0.2.tgz.3772586049' -> 'C:\Users\MAXSIE~1\AppData\Local\Temp\npm-3124-813e0a50\registry.npmjs.org\minimatch\-\minimatch-3.0.2.tgz'
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.9.1
npm ERR! npm  v3.7.3

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\MAXSIE~1\AppData\Local\Temp\npm-3124-813e0a50\registry.npmjs.org\wrappy\-\wrappy-1.0.2.tgz.3489718590' -> 'C:\Users\MAXSIE~1\AppData\Local\Temp\npm-3124-813e0a50\registry.npmjs.org\wrappy\-\wrappy-1.0.2.tgz'
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.9.1
npm ERR! npm  v3.7.3

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm

**Comment by KenanY** [comment]
@MaxPrime05 Are you still seeing this issue?

**Comment by KenanY** [comment]
Closing due to no response.
