### ISSUE TITLE
Need help in setup of blockapps using npm command

### ISSUE THREAD

**Issue by kasirahul2006** [npm/npm#13194]
I want to install blockapps bloc. pls guide me. i tried to install using the steps mentioned in block apps site but I don't know where to give those commands. I tried those in the powershell. I need to run a keyserver and create DApps in visual studio 2013. kindlt guide me. Thanks

### I'm opening this issue because:
- [ ] npm is crashing
- [ ] npm is producing an incorrect install
- [x] npm is doing something I don't understand
- [ ] other (_see below for feature requests_)

**Comment by kasirahul2006** [comment]
[npm-debug.zip](https://github.com/npm/npm/files/334905/npm-debug.zip)
 PFA the log file when I run the command "npm install blockapps-bloc"

**Comment by busches** [comment]
@kasirahul2006 you didn't provide most of the information the issue asks for. Can you at least add the commands you're running? Thanks.
