### ISSUE TITLE
Getting error when install npm typings.

### ISSUE THREAD

**Issue by ankitpachori** [npm/npm#13195]
Hi,
I am installing npm typings  but i am getting such kind of error.
![capture](https://cloud.githubusercontent.com/assets/19892558/16384370/32752612-3ca6-11e6-9d1a-1aadc6b9ef4c.PNG)

**Comment by robertkowalski** [comment]
the package tries to run `typings install` on your machine, but it seems it is not installed. from teh docs of the module it seems you are missing a dependency. this is not a bug with npm.

**Comment by robertkowalski** [comment]
more info here: https://www.npmjs.com/package/typings

**Comment by KenanY** [comment]
Closing as not an issue with `npm`.
