### ISSUE TITLE
Missing start script NODE NPM Start 

### ISSUE THREAD

**Issue by biancaglez** [npm/npm#13198]
Hello similar question to this post:
http://stackoverflow.com/questions/31976722/start-script-missing-error-when-running-npm-start 

'npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.4.0
npm ERR! npm  v3.10.2

npm ERR! missing script: start
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
'

I've tried adding the start script in my json file and renaming file to server.js. I'm on a mac, thanks for any help.

**Comment by KenanY** [comment]
@biancaglez Can I see the `package.json` file?

**Comment by biancaglez** [comment]
Here are the contents of the file. Thanks Kenan!
' {
  "name": "akfar",
  "version": "1.0.0",
  "description": "Harvard afkar",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/biancaglez/afkar.git"
  },
  "keywords": [
    "Harvard's",
    "Afkar"
  ],
  "author": "Bianca Gonzalez",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/biancaglez/afkar/issues"
  },
  "homepage": "https://github.com/biancaglez/afkar#readme",
  "dependencies": {},
  "devDependencies": {}

}
'

**Comment by KenanY** [comment]
@biancaglez I do not see a `"start"` script in that file. You should define one like this, for example:

``` json
{
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node my-app.js"
  }
}
```

**Comment by biancaglez** [comment]
Thank you, I've just tried pasting this again, but to no avail. 

Here is the error 
Failed to parse json
npm ERR! Unexpected token 's' at 8:6
npm ERR!     "start": "node my-app.js"
npm ERR!      ^
npm ERR! File: /Users/BiancaGonzalez/Desktop/afkar/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.

**Comment by KenanY** [comment]
@biancaglez I'm gonna have to see the entire file again in order to diagnose syntax errors like that.

**Comment by biancaglez** [comment]
@KenanY 
Yes, it is the same code plus the start line. Here is the code for the package.json file. 

{
  "name": "akfar",
  "version": "1.0.0",
  "description": "Harvard afkar",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
    "start": "node my-app.js"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/biancaglez/afkar.git"
  },
  "keywords": [
    "Harvard's",
    "Afkar"
  ],
  "author": "Bianca Gonzalez",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/biancaglez/afkar/issues"
  },
  "homepage": "https://github.com/biancaglez/afkar#readme",
  "dependencies": {},
  "devDependencies": {}

}

**Comment by lxe** [comment]
You missed a comma after `"test": "echo \"Error: no test specified\" && exit 1"`

**Comment by biancaglez** [comment]
I don't think this is the solution. I've inserted a comma to the direct code above, but still receive this error, although different this time. I don't understand the error messages, anyone?

Bianca 

npm ERR! owner ls Couldn't get owner data akfar
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "owner" "ls" "akfar"
npm ERR! node v5.4.0
npm ERR! npm  v3.10.2
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/akfar
npm ERR! 404 
npm ERR! 404  'akfar' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by KenanY** [comment]
@biancaglez `npm owner` [queries the registry](https://docs.npmjs.com/cli/owner) for information on who owns what packages. Since you have not yet published your package, there is no data in the registry for it, hence the error you are seeing.

**Comment by biancaglez** [comment]
Thanks! I am following this tutorial now to publish my package:
https://docs.npmjs.com/getting-started/publishing-npm-packages

**Comment by manikachhabra** [comment]
Hi
I am having somewhat similar problem and not able to resolve it with the solution provided here.
Can i have some help please?

**Comment by KenanY** [comment]
@manikachhabra Could you open a new issue?

**Comment by Bswanny** [comment]
don't know if you found your solution yet , but in your file you use AKFAR and AFKAR.
