### ISSUE TITLE
TypeError: config.getCredentialsByURI is not a function

### ISSUE THREAD

**Issue by fangx** [npm/npm#13204]
### I'm opening this issue because:

npm ERR!     at mapToRegistry (/usr/local/lib/node_modules/npm/lib/utils/map-to-registry.js:48:21)
npm ERR!     at getOnceFromRegistry (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:32:3)
npm ERR!     at addNameRange (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:228:3)
npm ERR!     at addNamed (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:61:5)
npm ERR!     at add (/usr/local/lib/node_modules/npm/lib/cache.js:275:11)
npm ERR!     at maybeAt (/usr/local/lib/node_modules/npm/lib/cache.js:354:5)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:344:5
npm ERR!     at FSReqWrap.oncomplete (fs.js:82:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

#### Node version:
node -v v4.4.5

#### npm version:

npm -v 1.4.28

**Comment by othiym23** [comment]
`npm@1` is no longer supported by the CLI team, and it seems that the version of npm you have installed was at least partially overwritten by another install. Uninstall Node, ensure that there's no version of npm remaining on your path and that `/usr/local/lib/node_modules/npm` has been completely removed, and then use one of the official installers to reinstall Node and npm. Installing the latest Node.js LTS release (which is what the npm CLI team recommends for most users) should get you a reasonably recent version of  `npm@2`. Thanks for your time!

**Comment by fangx** [comment]
Im ok now,Thanks~
