### ISSUE TITLE
EAFNOSUPPORT error while trying to install anything with npm install

### ISSUE THREAD

**Issue by blackraider7** [npm/npm#13208]
I'm trying to install jslint on my win7 comp with _npm install -g jslint_ but i get this error :

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\b
in\\npm-cli.js" "install" "-g" "jslint"
npm ERR! node v4.4.6
npm ERR! npm  v2.15.5
npm ERR! code EAFNOSUPPORT
npm ERR! errno EAFNOSUPPORT
npm ERR! syscall connect

npm ERR! connect EAFNOSUPPORT 185.31.17.162:443 - Local (0.0.0.0:57579)
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

I'm getting the same error if i try to install anything else with npm install 
i have disabled all firewalls so it's not that, i have tried it from my win xp system on the same comp but i got same error
i have tried it from my brothers comp that is in the same network behind same router and it works ...

**Comment by blackraider7** [comment]
it seems that problem was in Netlimiter,  once i uninstalled it npm error goes away ...

**Comment by KenanY** [comment]
Hmm, closing as resolved then.
