### ISSUE TITLE
questions about npm run bulid

### ISSUE THREAD

**Issue by caoxiaoshuai1** [npm/npm#13215]
when I run code 'npm run bulid', the cmd show me errors 
```
C:\Users\Administrator>npm run build
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Fil
node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! path C:\Users\Administrator\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\Ad
package.json'
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\Ad
package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Administrator\npm-debug.log
```
plz help me to get a solution.

**Comment by KenanY** [comment]
@caoxiaoshuai1 Does `C:\Users\Administrator\package.json` exist?

**Comment by caoxiaoshuai1** [comment]
![Uploading 未标题-1.jpg…]()
This path have package.json,but the errpr still  exist.
cd C:\Program Files\nodejs\node_global\node_modules\gulp

**Comment by caoxiaoshuai1** [comment]
C:\Program Files\nodejs\node_global\node_modules\gulp>npm run build
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5

npm ERR! missing script: build
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Program Files\nodejs\node_global\node_modules\gulp\npm-debug.log


C:\Program Files\nodejs\node_global\node_modules\gulp>

**Comment by KenanY** [comment]
@caoxiaoshuai1 Do you have a `"build"` script defined in your `package,json`? If not, then `npm` will give you that "missing script" error.

**Comment by KenanY** [comment]
Closing as abandoned.
