### ISSUE TITLE
npm ERR! network connect ETIMEDOUT

### ISSUE THREAD

**Issue by sxp231** [npm/npm#13217]
C:\Users\sxp231>npm install -g newman
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\nodejs\\\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\npm-
cli.js" "install" "-g" "newman"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! syscall connect

npm ERR! network connect ETIMEDOUT
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\sxp231\npm-debug.log

Please suggest how to reslove this issue.

**Comment by KenanY** [comment]
@sxp231 As the error indicates, this is an issue with your internet connection and not with `npm`. Maybe you are behind a proxy or firewall?

**Comment by KenanY** [comment]
Closing as abandoned.
