### ISSUE TITLE
Error: Refusing to install sound as a dependency of itself on El Capitan

### ISSUE THREAD

**Issue by woo37830** [npm/npm#13221]
### I'm opening this issue because:

  - [ ] npm is crashing
  - [ ] npm is producing an incorrect install
  - [x] npm is doing something I don't understand
  - [ ] other (_see below for feature requests_)

#### Node version:

v0.12.7
#### npm version:

3.8.6
#### How did you install Node and npm?

brew install node, brew install wpm
#### Operating system version and distribution:
OS X 10.11.5

Darwin MacBook-Pro.local 15.5.0 Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64 x86_64

#### Containerization or virtualization environment:

?
#### Are you using [a proxy](https://docs.npmjs.com/misc/config#proxy)?
No
#### What problem are you seeing?
npm install sound
npm ERR! Darwin 15.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "sound"
npm ERR! node v0.12.7
npm ERR! npm  v3.8.6
npm ERR! code ENOSELF

npm ERR! Refusing to install sound as a dependency of itself
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/woo/npm-debug.log
#### How can the problem be reproduced?

https://gist.github.com/woo37830/2b8e7a590cd330c5e3f1b613c487d0fd

**Comment by KenanY** [comment]
@woo37830 Hmm, is there a `package.json` in your current working directory?

**Comment by KenanY** [comment]
Closing as abandoned.
