### ISSUE TITLE
npm doesn't install yo, grunt or bower

### ISSUE THREAD

**Issue by PoonamG** [npm/npm#13229]
npm log shared below

[https://gist.github.com/anonymous/b95bf2b523daffa7c814b3e6e86746e2](url)

**Comment by KenanY** [comment]
@PoonamG Hello! Should I close this in favor of https://github.com/npm/npm/issues/13229 (which is also by you, I think?)?

**Comment by PoonamG** [comment]
Sure, you can close this

**Comment by KenanY** [comment]
@PoonamG Thanks!
