### ISSUE TITLE
"npm shrinkwrap" only removes dev dependencies but lists the dependencies of dev dependencies

### ISSUE THREAD

**Issue by sameercaresu** [npm/npm#13227]
Consider this package.json

{
  "name": "test",
  "devDependencies": {
    "grunt": "0.4.5"
  },
  "dependencies": {
    "abbrev": "^1.0.9"
  }
}

"abbrev" is one of the dependencies in grunt. Just for testing I wrote it as dependency here.

Then I do
- npm install
- npm shrinkwrap

"npm shrinkwrap" lists all the dependencies of grunt. It just doesn't list "grunt" mentioned in the package.json.

Doing "npm shrinkwrap --dev" will add "grunt" entry to npm-shrinkwrap.json.

Doing 
- npm prune --production
- npm shrinkwrap
will give the npm-shrinkwrap.json with only one entry "abbrev"

I think "npm shrinkwrap" should give result as "npm prune --production & npm shrinkwrap" (Ofcourse without actually pruning).

Is that not so or am I missing something?

**Comment by SimenB** [comment]
We have the same problem

**Comment by sameercaresu** [comment]
Closing this. Seems to be solved in #13303
