### ISSUE TITLE
npm install problems on mounted filesystem in vagrant box.

### ISSUE THREAD

**Issue by seenteage** [npm/npm#13224]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [x] npm is producing an incorrect install.
- [ ] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
#### What's going wrong?
- Try to install packages which links to `node_modules/.bin` (for example `mocha`, `coffee-script`)
- Some executables don't show up in `node_modules/.bin`.
- This happens with node 6 (npm 3), but not with node 4 (npm 2)
- It only happens in the mounted filesystem (`/vagrant`) which is synced with the host system, but not in other folders in the vagrant box (for example `/tmp`)
- Sometimes `npm install` returns an error (https://gist.github.com/seenteage/57b5de78e5e1b4af3323082faedc0931#file-npm-debug-log-L3007-L3019)
- Sometimes `npm install` returns no error, but doesn't contain the binary (https://gist.github.com/seenteage/adffa329c830e03a8ecd1dc16ac62a3f#file-vagrant-log-L208-L236)
- Definitely not always the same behaviour. `npm install coffee-script` sometimes returns an error sometimes not. Here I run (npm install coffee-script) multiple times: https://gist.github.com/seenteage/08f403b301e5162135d3b6e8fd965be1
- Some modules are linked correctly (for example `grunt-cli`)
- Using `--no-bin-links` is no solution for this problem, as the project expects to have these files in the bin folder.
- Using the latest `npm@2` version (2.5.19) works perfectly. The issue is with `npm@3`.
#### How can the CLI team reproduce the problem?

Use this `Vagrantfile`

``` ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
curl -sL https://deb.nodesource.com/setup_6.x | bash -
apt-get install -y nodejs
cd /vagrant # Move to shared filesystem
rm -rf node_modules npm-debug.log
npm install mocha
node_modules/.bin/mocha
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provision "shell", inline: $script
end
```

Run with `vagrant destroy --force; vagrant up`
### supporting information:
- `npm -v` prints: 3.9.5
- `node -v` prints: 6.2.2
- `npm config get registry` prints: https://registry.npmjs.org/
- Windows, OS X, or Linux?:  OS X or Linux running Linux in a vagrant virtual box.
- Network issues:
  - Geographic location where npm was run:
  - [ ] I use a proxy to connect to the npm registry.
  - [ ] I use a proxy to connect to the web.
  - [ ] I use a proxy when downloading Git repos.
  - [ ] I access the npm registry via a VPN
  - [ ] I don't use a proxy, but have limited or unreliable internet access.
- Container:
  - [ ] I develop using Vagrant on Windows.
  - [x] I develop using Vagrant on OS X or Linux.
  - [ ] I develop / deploy using Docker.
  - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by seenteage** [comment]
Do you need any more help or do you need more information?
I'm happy to provide you with more details.

This errors makes npm behave unexpectedly if run in a vagrant environment.

**Comment by michPl** [comment]
Have the same problem
