### ISSUE TITLE
Problem in starting Npm?

### ISSUE THREAD

**Issue by rishabhbahukhandi** [npm/npm#13231]
[root@ip-172-31-11-2 npm]# npm start
npm ERR! Linux 4.4.11-23.53.amzn1.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v7.0.0-pre
npm ERR! npm  v3.10.3

npm ERR! missing script: start
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /root/node/npm/npm-debug.log

**Comment by KenanY** [comment]
@rishabhbahukhandi Hello! Do you have a `"start"` script defined in your `package.json`? Without one, `npm` will throw the error you are seeing, since it does not know what you want it to run.

**Comment by KenanY** [comment]
One week without a response :(

Gonna close as abandoned.

**Comment by rishabh03** [comment]
I have an Start Script. I have include all the dependencies in the package.json

**Comment by KenanY** [comment]
@rishabh03 Open a new issue please and include the `npm-debug.log` and `package.json`.
