### ISSUE TITLE
CANT INSTALL nedb

### ISSUE THREAD

**Issue by kdovale** [npm/npm#13239]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [X ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I run nom install nedb abd the result is an untrusted cert issue I think.. below is the log file
#### How can the CLI team reproduce the problem?

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'nedb' ]
2 info using npm@1.1.37
3 info using node@v0.6.20
4 verbose node symlink C:\Program Files (x86)\nodejs\\node.exe
5 verbose config file C:\Users\Administrator\.npmrc
6 verbose config file C:\Program Files (x86)\nodejs\etc\npmrc
7 verbose config file C:\Program Files (x86)\nodejs\node_modules\npm\npmrc
8 verbose read json C:\Users\Administrator\package.json
9 verbose read json C:\Users\Administrator\package.json
10 verbose cache add [ 'nedb', null ]
11 silly cache add name=undefined spec="nedb" args=["nedb",null]
12 verbose parsed url { pathname: 'nedb', path: 'nedb', href: 'nedb' }
13 silly lockFile a1971d45-nedb nedb
14 verbose lock nedb C:\Users\Administrator\AppData\Roaming\npm-cache\a1971d45-nedb.lock
15 silly lockFile a1971d45-nedb nedb
16 verbose addNamed [ 'nedb', '' ]
17 verbose addNamed [ null, '' ]
18 silly lockFile c21a1013-nedb nedb@
19 verbose lock nedb@ C:\Users\Administrator\AppData\Roaming\npm-cache\c21a1013-nedb.lock
20 silly addNameRange { name: 'nedb', range: '', hasData: false }
21 verbose url raw nedb
22 verbose url resolving [ 'https://registry.npmjs.org/', './nedb' ]
23 verbose url resolved https://registry.npmjs.org/nedb
24 info retry registry request attempt 1 at 10:54:59
25 http GET https://registry.npmjs.org/nedb
26 info retry will retry, error on last attempt: Error: SSL Error: CERT_UNTRUSTED
27 info retry registry request attempt 2 at 10:55:12
28 http GET https://registry.npmjs.org/nedb
29 info retry will retry, error on last attempt: Error: SSL Error: CERT_UNTRUSTED
30 info retry registry request attempt 3 at 10:56:13
31 http GET https://registry.npmjs.org/nedb
32 silly lockFile c21a1013-nedb nedb@
33 error Error: SSL Error: CERT_UNTRUSTED
33 error     at ClientRequest.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\main.js:440:26)
33 error     at ClientRequest.g (events.js:156:14)
33 error     at ClientRequest.emit (events.js:67:17)
33 error     at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1256:7)
33 error     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:91:29)
33 error     at CleartextStream.socketOnData [as ondata] (http.js:1288:20)
33 error     at CleartextStream._push (tls.js:375:27)
33 error     at SecurePair.cycle (tls.js:734:20)
33 error     at EncryptedStream.write (tls.js:130:13)
33 error     at Socket.ondata (stream.js:38:26)
33 error  [Error: SSL Error: CERT_UNTRUSTED]
34 error You may report this log at:
34 error     <http://github.com/isaacs/npm/issues>
34 error or email it to:
34 error     <npm-@googlegroups.com>
35 error System Windows_NT 6.1.7601
36 error command "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "nedb"
37 error cwd C:\Users\Administrator
38 error node -v v0.6.20
39 error npm -v 1.1.37
40 error message SSL Error: CERT_UNTRUSTED
41 verbose exit [ 1, true ]

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@kdovale Hello! Both Node.js v0.6 and `npm@1` are years old and are no longer supported. Please try updating both of them first.

**Comment by KenanY** [comment]
One week without a reply :(

Closing as abandoned.
