### ISSUE TITLE
Force installation in parent folder

### ISSUE THREAD

**Issue by martinheidegger** [npm/npm#13237]
I'm opening this issue because it is unnecessarily hard to manage dependencies with npm in docker and would like to ask for a feature that might mitigate this.
#### The problem

When you run a node project inside docker then usually the node and npm version is determined by the docker base image. This means that installed packages (particularly with c bindings) are installed with a certain version. Now, docker allows the use of [volumes](https://docs.docker.com/v1.10/engine/userguide/containers/dockervolumes/#mount-a-host-directory-as-a-data-volume) to edit code while the server is running (super useful for development). If you use the feature and install code with `npm i` however then docker runs into several problems. For example: the connected volume does not have the same permissions as other folders. Also features such as symlinks don't work properly.
#### Solution

Node.js supports [loading from `node_modules` in a parent folder](https://nodejs.org/api/modules.html#modules_loading_from_node_modules_folders) or from [`NODE_PATH`](https://nodejs.org/api/modules.html#modules_loading_from_the_global_folders). 
#### Approach 1

It would be awesome if npm could support to install dependencies in a parent folder attribute like
`npm i --parent` to install the dependencies in the parent `node_modules` folder. The lookup system of node will automatically find the dependencies of the parent folder. This way the `package.json` could still stay in the linked folder while the dependencies could stay within the docker container.
#### Approach 2

Alternatively I could imagine that npm could support a `--node-path` property that would automatically install the dependencies in the `NODE_PATH`. Again: the lookup will go right into the correct folder without storing the on the shared volume or creating weird linking problems. _The problem with this solution is, however, that some projects rely on the `NODE_PATH` to be pointing at a certain folder and it can not be used for this purpose,_

**Comment by mlucool** [comment]
:+1:

**Comment by aborchew** [comment]
👍 I'm currently experiencing the same frustration while writing a Node.js script that will check out several sibling component libraries and generate unit test results for all components. Having n copies of my Node (and Bower, for that matter) dependencies seems like an unnecessary expense.

@martinheidegger have you found a viable workaround for this in the meantime, or are you content with having several node_module directories exist until this feature is developed?

**Comment by mlucool** [comment]
I think this is the result of a bug actually. See https://github.com/npm/npm/issues/14029
