### ISSUE TITLE
file:///home/loayelzobeidy/workspaceO/SE/stackoverflow-says-what/npm-debug

### ISSUE THREAD

**Issue by loayelzobeidy** [npm/npm#13233]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@loayelzobeidy Hello! Could you please fill out the support form, which is in your opening post? At the moment, it is not clear to me what issue you are having. Could you upload your `npm-debug.log` to [gist.github.com](https://gist.github.com/) and post the link here?

**Comment by loayelzobeidy** [comment]
posted :D

2016-06-30 16:33 GMT+02:00 Kenan Yildirim <notifications@github.com>:

**Comment by KenanY** [comment]
@loayelzobeidy What's the link?

**Comment by KenanY** [comment]
One week without a reply :(

Closing as abandoned.
