### ISSUE TITLE
NPM not installing JSHint

### ISSUE THREAD

**Issue by jbmonroe** [npm/npm#13232]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### How can the CLI team reproduce the problem?

Follow the instructions provided by VS Code for how to install jshint (pretty much go to workspace folder and issue 'npm install jshint' or 'npm install -g jshint').

https://gist.github.com/jbmonroe/b70d6b813e5b1b658f1d58904b315546

### supporting information:

 - `npm -v` prints: 1.2.11
 - `node -v` prints: v0.8.20
 - `npm config get registry` prints:https://registry.npmjs.org/
 - Windows, OS X, or Linux?: Windows 7
 - Network issues:
   - Geographic location where npm was run: Florida USA  51° 30' 12.27'' N,0° 7' 39.33'' W
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@jbmonroe `npm@1.2` is years old and is no longer supported by the npm team. Please try updating both Node.js and `npm` first.

**Comment by jbmonroe** [comment]
'npm install jshint' didn't provide anything VSCode could use after the upgrade to Node, but the global install did, so I'm of the opinion that's a problem with VSCode.  Thanks!
