### ISSUE TITLE
npm modifying package.json files while downloading?

### ISSUE THREAD

**Issue by erdog** [npm/npm#13240]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [ ] npm is producing an incorrect install.
- [x] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
#### What's going wrong?

A package.json (from package JSV) contains an empty array for its dependencies, rather than an expected empty map. NPM appears to be okay with this and even converts it to a map at some point when downloading.

This issue comes from uploading to our artifact server (Artifactory). It expects a specific json format for package.json, which JSV doesn't meet. This causes the upload to fail.

I would like to confirm that NPM does in fact convert arrays to maps while downloading package.json files.
#### How can the CLI team reproduce the problem?

They can't fully reproduce without Artifactory, but by downloading the JSV package with NPM they can view changes to the package.json by NPM.

**Comment by mvayngrib** [comment]
also, some packages do require() their own package.json, or a dependency's and become unnecessarily bloated when npm modifies it during install (particularly when adding their README under the "readme" field!). If this is the wrong issue, please tell me where to repost :)
