### ISSUE TITLE
npm version --no-git-tag-version -m "%s" doesn't commit the message passed

### ISSUE THREAD

**Issue by jhspaybar** [npm/npm#13242]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [ ] npm is producing an incorrect install.
- [ ] npm is doing something I don't understand.
- [ X ] Other (_see below for feature requests_):
#### What's going wrong?

`npm --no-git-tag-version version patch -m "Releasing %s"` is not creating a commit.  I would expect this to still create the commit but skip the tag only.
#### How can the CLI team reproduce the problem?

run `npm --no-git-tag-version version patch -m "Releasing %s"` on any npm package and observe no commit made.
### supporting information:

https://github.com/npm/npm/issues/7186 seems to say after a code dive that this is what the code does as the commit and tag is a single function
#### What's the feature?

Make --no-git-tag-version not tag but still commit
#### What problem is the feature intended to solve?

I manage my own tagging, but would like the commit functionality.
#### Is the absence of this feature blocking you or your team? If so, how?

No, but it requires I do a `git commit` in post-version and the flag is misleading.  Also, it's not straightforward to put the version in the commit message as would typically be done by npm version -m "Releasing %s"
#### Is this a feature you're prepared to implement, with support from the npm CLI team?

I suppose I could, I'm happy to contribute if that's what you'd like, but since this changes existing behavior potentially I'd need some guidance on the right way to fix this.

**Comment by ivoputzer** [comment]
@jhspaybar moreover `npm version from-git --no-git-tag-version` creates the commit regardless of the flag.
