### ISSUE TITLE
npm search failing with "npm ERR! Unexpected token g"

### ISSUE THREAD

**Issue by geuis** [npm/npm#13247]
#### I'm opening this issue because:
  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
When I search for something, I get results for the first search. Subsequent searches, even for the same term, produce invalid output.

I have uninstalled and reinstalled the latest npm@3.10.3 and have the same issue that was occuring with 3.9 (previously installed).

#### How can the CLI team reproduce the problem?
npm-debug.log gist here: https://gist.github.com/geuis/198fd71410a40bfeaf0a875f42b276ef

npm cache clean
npm search <term>
    // get correct results
npm search <term or another term>
    // get error and invalid results

// now do the whole thing again
npm cache clean
npm search <term again>
    // get correct results
npm search <term or another term>
    // get error and invalid results

### supporting information:

 - `npm -v` prints: 3.10.3
 - `node -v` prints: v4.3.1
 - `npm config get registry` prints: http://registry.npmjs.org/
 - Windows, OS X, or Linux?: OS X
 - Network issues:
   - Geographic location where npm was run: San Francisco
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by zkat** [comment]
This should be fixed by https://github.com/npm/npm/pull/13746 once that's done.
