### ISSUE TITLE
Docs: Show `--silent` flag usage for npm run script

### ISSUE THREAD

**Issue by styfle** [npm/npm#13241]
#### What's the feature?

Hide/silence npm ERR output when using `npm run script` so that the only output on the console is the from the script that was executed, not from npm.
#### What problem is the feature intended to solve?

Many times a day, developers use `npm run build` and the "npm ERR!" output is filling up the console with useless information. The dev has to scroll up past all the junk to find the actual error message. See [this question](http://stackoverflow.com/q/38084112/266535) on stackoverflow for more details.
#### Is the absence of this feature blocking you or your team? If so, how?

No
#### Is this feature similar to an existing feature in another tool?

Typically there is a `--verbose` flag to get additional details and the default behavior is to have fewer details. Some tools use a `--silent` flag if the default is verbose.
#### Is this a feature you're prepared to implement, with support from the npm CLI team?

Maybe

**Comment by styfle** [comment]
I found my answer in #5452.
There already is a `--silent` flag.

This should really be added to the documentation, though.

**Comment by styfle** [comment]
Also I would like to vote for #8821 to avoid the need for a silent flag on my `build` and `test` scripts.

**Comment by iarna** [comment]
The fix for this was merged as d57d4f48c and will be in the next npm release.
