### ISSUE TITLE
Angularjs 2 NPM start not working

### ISSUE THREAD

**Issue by mobi35** [npm/npm#13254]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@mobi35 Hello! Could you please take the time to fill out the support form in your post? It will go a long way in making sure that we get your issue resolved. Also, if there is a `npm-debug.log` file, could you please upload it to https://gist.github.com/.

**Comment by KenanY** [comment]
Closing as abandoned. Can reopen if this is still an issue and the requested information is provided.
