### ISSUE TITLE
Shrinkwrap lifecycle scripts have wrong cwd

### ISSUE THREAD

**Issue by STRML** [npm/npm#13252]
#### I'm opening this issue because:

Shrinkwrap lifecycle scripts behave oddly.

#### What's going wrong?

For most lifecycle scripts, the cwd is the root of the project. For example,
a scripts like this resolve fine:

```json
"dev": "./run-dev.sh",
"preCommit": "scripts/precommit.sh"
```

However, `preshrinkwrap` and `postshrinkwrap` resolve relative to `./node_modules`, making the below an error:

```json
"preshrinkwrap": "scripts/pre-shrinkwrap.sh",
"postshrinkwrap": "scripts/post-shrinkwrap.sh",
```

```bash
$ npm shrinkwrap

> x-x @1.1.0 preshrinkwrap /Users/x/x/x/node_modules
> scripts/pre-shrinkwrap.sh

sh: scripts/pre-shrinkwrap.sh: No such file or directory
```

You must instead prepend `../`:

```json
"preshrinkwrap": "../scripts/pre-shrinkwrap.sh",
"postshrinkwrap": "../scripts/post-shrinkwrap.sh",
```

This also means that any scripts these lifecycles call have a CWD in `node_modules` instead of the root of the project, which can cause breakage.

#### How can the CLI team reproduce the problem?

Add any preshrinkwrap/postshrinkwrap lifecycle scripts.

### Supporting information:

 - `npm -v` prints: 3.10.3
 - `node -v` prints: v6.2.1
 - Windows, OS X, or Linux?: OS X

**Comment by iarna** [comment]
I've tried to reproduce this and it's not happening for me. Can you put together a git repo that displays this behavior?

Here's what I tried:

**package.json**:
```
{
  "name": "13253",
  "version": "1.0.0",
  "scripts": {
    "preshrinkwrap": "scripts/shrinkwrap.sh pre",
    "shrinkwrap": "scripts/shrinkwrap.sh -",
    "postshrinkwrap": "scripts/shrinkwrap.sh post"
  }
}
```

**scripts/shrinkwrap.sh** (mode: 0755):
```
#!/bin/bash
echo Shrinkwrap $1 $(pwd)
```

Result of run:
```
$ npm --version
3.10.3
$ npm shrinkwrap

> 13253@1.0.0 preshrinkwrap /Users/rebecca/code/npmtest/13253
> scripts/shrinkwrap.sh pre

Shrinkwrap pre /Users/rebecca/code/npmtest/13253

> 13253@1.0.0 shrinkwrap /Users/rebecca/code/npmtest/13253
> scripts/shrinkwrap.sh -

Shrinkwrap - /Users/rebecca/code/npmtest/13253
wrote npm-shrinkwrap.json

> 13253@1.0.0 postshrinkwrap /Users/rebecca/code/npmtest/13253
> scripts/shrinkwrap.sh post

Shrinkwrap post /Users/rebecca/code/npmtest/13253
```

**Comment by STRML** [comment]
This is actually related to #13253 and is due to the recursive call, but what's weird is that it only happens with `--dev`. Easy reproduction:

```json
"scripts": {
  "shrinkwrap": "scripts/shrinkwrap.sh"
}
```

*shrinkwrap.sh*

```bash
echo $(pwd)
# should have --ignore-scripts but didn't know about that option at writing
npm shrinkwrap --dev
```

Result:

```
$ npm run shrinkwrap

> project@1.0.0 shrinkwrap /git/test/project
> scripts/shrinkwrap.sh

++ pwd
+ echo /git/test/project
/git/test/project
+ npm shrinkwrap --dev

> project@1.0.0 shrinkwrap /git/test/project/node_modules
> scripts/shrinkwrap.sh

sh: scripts/shrinkwrap.sh: No such file or directory
```

**Comment by iarna** [comment]
I don't get the `No such file or directory`, I just get the infinite loop.

**Comment by STRML** [comment]
Thanks for putting this much attention into this. I'll work on getting a repro going.

**Comment by STRML** [comment]
Something stranger is going on. I can't reproduce even with my project's full `package.json`, until I actually install all of its modules. This causes the `cwd` of the recursive call to be inside the project's `node_modules`, instead of at the root. Very strange. I'm going to narrow it down to which package in particular is doing this. It seems odd that any package could affect the cwd of a lifecycle script call.

**Comment by STRML** [comment]
Okay, the issue is not any particular package, it is simply the mere presence of the `node_modules` folder. Please pull the repo, I've added the folder:

```
~/g/f/npm-13252 (master|✔) $ npm run shrinkwrap

> 13252@1.0.0 shrinkwrap /Users/samuelreed/git/forks/npm-13252
> scripts/shrinkwrap.sh

/Users/samuelreed/git/forks/npm-13252

> 13252@1.0.0 shrinkwrap /Users/samuelreed/git/forks/npm-13252/node_modules
> scripts/shrinkwrap.sh

sh: scripts/shrinkwrap.sh: No such file or directory
```

**Comment by iarna** [comment]
oooh, very interesting!

**Comment by iarna** [comment]
alright, excellent, I should be able to track this down now.

**Comment by iarna** [comment]
I've simplified the repro and got it saving the correct npm-debug.log now!

**Comment by evocateur** [comment]
I can definitely confirm this is happening with npm v3.10.7
