### ISSUE TITLE
NPM unable to install

### ISSUE THREAD

**Issue by ChaiBapchya** [npm/npm#13265]
#### I'm opening this issue because:

  - [ ] npm is crashing.

#### What's going wrong?

Unable to install the NPM for the following command - 
npm install

#### How can the CLI team reproduce the problem?

0 info it worked if it ends with ok
```
1 verbose cli [ 'node', '/bin/npm', 'install' ]
2 info using npm@1.3.6
3 info using node@v0.10.42
4 verbose node symlink /bin/node
5 error install Couldn't read dependencies
6 error Error: ENOENT, open '/package.json'
7 error If you need help, you may report this log at:
7 error     <http://github.com/isaacs/npm/issues>
7 error or email it to:
7 error     <npm-@googlegroups.com>
8 error System Linux 4.5.7-200.fc23.x86_64
9 error command "node" "/bin/npm" "install"
10 error cwd /
11 error node -v v0.10.42
12 error npm -v 1.3.6
13 error path /package.json
14 error code ENOENT
15 error errno 34
16 verbose exit [ 34, true ]
```
### supporting information:

 - Windows, OS X, or Linux?: Fedora
 - Network issues:
   - Geographic location where npm was run: Mumbai, India

**Comment by flxn** [comment]
This doesn't look like an error caused by npm.
Are you sure, you're executing `npm install` in the directory of your project?
Is there a valid package.json file?
Do you have the right permissions to access it?

**Comment by ChaiBapchya** [comment]
Ya. Issue resolved. I was not in the right directory with working package.json.
I changed the right permission and now it worked
Thank you
