### ISSUE TITLE
Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443

### ISSUE THREAD

**Issue by munishsainicr** [npm/npm#13264]
While install the angular using npm from node through cmd (windows) I am getting bellow error:
Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443.

Complete Logs are below:

0 info it worked if it ends with ok
1 verbose cli [ 'D:\Soft_Install\NodeJS\node.exe',
1 verbose cli   'D:\Soft_Install\NodeJS\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'angular' ]
2 info using npm@2.15.8
3 info using node@v4.4.7
4 verbose install initial load of D:\Soft_Install\ApacheWebServer\webapps\ngClassifieds\package.json
5 warn package.json ng-classifieds@1.0.0 No description
6 warn package.json ng-classifieds@1.0.0 No repository field.
7 warn package.json ng-classifieds@1.0.0 No README data
8 verbose readDependencies loading dependencies from D:\Soft_Install\ApacheWebServer\webapps\ngClassifieds\package.json
9 silly cache add args [ 'angular', null ]
10 verbose cache add spec angular
11 silly cache add parsed spec Result {
11 silly cache add   raw: 'angular',
11 silly cache add   scope: null,
11 silly cache add   name: 'angular',
11 silly cache add   rawSpec: '',
11 silly cache add   spec: 'latest',
11 silly cache add   type: 'tag' }
12 silly addNamed angular@latest
13 verbose addNamed "latest" is being treated as a dist-tag for angular
14 info addNameTag [ 'angular', 'latest' ]
15 silly mapToRegistry name angular
16 silly mapToRegistry using default registry
17 silly mapToRegistry registry https://registry.npmjs.org/
18 silly mapToRegistry data Result {
18 silly mapToRegistry   raw: 'angular',
18 silly mapToRegistry   scope: null,
18 silly mapToRegistry   name: 'angular',
18 silly mapToRegistry   rawSpec: '',
18 silly mapToRegistry   spec: 'latest',
18 silly mapToRegistry   type: 'tag' }
19 silly mapToRegistry uri https://registry.npmjs.org/angular
20 verbose addNameTag registry:https://registry.npmjs.org/angular not in flight; fetching
21 verbose request uri https://registry.npmjs.org/angular
22 verbose request no auth needed
23 info attempt registry request try #1 at 12:20:41 PM
24 verbose request id 686130a4fd043cd8
25 http request GET https://registry.npmjs.org/angular
26 info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=getaddrinfo EAI_AGAIN proxy.company.com:8080
27 info attempt registry request try #2 at 12:20:51 PM
28 http request GET https://registry.npmjs.org/angular
29 info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=getaddrinfo EAI_AGAIN proxy.company.com:8080
30 info attempt registry request try #3 at 12:21:51 PM
31 http request GET https://registry.npmjs.org/angular
32 verbose stack Error: tunneling socket could not be established, cause=getaddrinfo EAI_AGAIN proxy.company.com:8080
32 verbose stack     at ClientRequest.onError (D:\Soft_Install\NodeJS\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:176:17)
32 verbose stack     at ClientRequest.g (events.js:260:16)
32 verbose stack     at emitOne (events.js:77:13)
32 verbose stack     at ClientRequest.emit (events.js:169:7)
32 verbose stack     at Socket.socketErrorListener (_http_client.js:267:9)
32 verbose stack     at emitOne (events.js:77:13)
32 verbose stack     at Socket.emit (events.js:169:7)
32 verbose stack     at connectErrorNT (net.js:1012:8)
32 verbose stack     at nextTickCallbackWith2Args (node.js:442:9)
32 verbose stack     at process._tickCallback (node.js:356:17)
33 verbose cwd D:\Soft_Install\ApacheWebServer\webapps\ngClassifieds
34 error Windows_NT 6.1.7601
35 error argv "D:\Soft_Install\NodeJS\node.exe" "D:\Soft_Install\NodeJS\node_modules\npm\bin\npm-cli.js" "install" "angular"
36 error node v4.4.7
37 error npm  v2.15.8
38 error code ECONNRESET
39 error network tunneling socket could not be established, cause=getaddrinfo EAI_AGAIN proxy.company.com:8080
39 error network This is most likely not a problem with npm itself
39 error network and is related to network connectivity.
39 error network In most cases you are behind a proxy or have bad network settings.
39 error network
39 error network If you are behind a proxy, please make sure that the
39 error network 'proxy' config is set properly.  See: 'npm help config'
40 verbose exit [ 1, true ]

**Comment by aayushjains20** [comment]
try and change the proxy settings for npm.
do run the commands
npm config set proxy http://proxy.company.com:8080
npm config set https-proxy http://proxy.company.com:8080

**Comment by tomatehk** [comment]
Execute cmd as admin

**Comment by andre-filho** [comment]
I've run command again and worked

**Comment by binarymist** [comment]
If using Docker, this known issue is discussed in detail here: https://development.robinwinslow.uk/2016/06/23/fix-docker-networking-dns/

Simple fix is to create the file `/etc/docker/daemon.json`

and insert:

```
{
    "dns": ["10.0.0.2", "8.8.8.8"]
}
```
where `10.0.0.2` is the first DNS server your machine requests records from, and `8.8.8.8` is the fallback DNS server, google in this case.
