### ISSUE TITLE
npm installs packages with broken files on Docker with a locally mounted folder

### ISSUE THREAD

**Issue by martinheidegger** [npm/npm#13266]
#### I'm opening this issue because:
- [x] npm is producing an incorrect install.
#### What's going wrong?

When running npm in a docker container of a local boot2docker instance with a mounted app directory, some files of packages installed by npm are corrupted and contain weird blocks of text like:

``` javascript
/**
 * Set / get the command usage `str`.
 *
 * @param {String} str
 * @return {String|Command}
 * @api publi^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^
@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^
@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^
@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^
@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^
@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^
@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^
@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^
@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^
@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@name = function() {
  return this._name;
};
```
#### How can the CLI team reproduce the problem?

On a mac: start a docker container in a folder with a `package.json` file that contains more than a few dependencies and without a pre-existing `node_modules` folder, run: 

`docker run -it -v "$(pwd):/usr/app/src" node:5-wheezy npm install`

It should create a `node_modules` folder on the source of the file and several files should be corrupted.
### supporting information:

[`Docker Toolbox 1.11.2`](https://github.com/docker/toolbox/releases/tag/v1.11.2)
- `npm -v` prints: v5.12.0
- `node -v` prints: 3.10.2
- `npm config get registry` prints: https://registry.npmjs.org/
- Windows, OS X, or Linux?: Mac OS X 10.11.4
- Network issues:
  - Geographic location where npm was run: Japan
- Container:
  - [x] I develop / ~~deploy~~ using Docker.

**Comment by martinheidegger** [comment]
Amendment: We just retested it with the recently published [`Docker for Mac beta`](https://docs.docker.com/engine/installation/mac/) and we could reproduce the problem.

**Comment by othiym23** [comment]
@martinheidegger Can you provide a Dockerfile with enough instructions for us to repro this ourselves? If we can, this gets bumped up to either an issue on Docker itself or a `big-bug` within npm. Thanks for your time!
