### ISSUE TITLE
np shows ENOTSUP warning on every other install

### ISSUE THREAD

**Issue by janbiasi** [npm/npm#13267]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [ ] npm is producing an incorrect install.
- [x] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
#### What's going wrong?

I've installed the [`chokdiar`](https://www.npmjs.com/package/chokidar) module which requires the (Mac OS  X only) [`fsevents`](https://www.npmjs.com/package/fsevents) module - this shows the message below, which is fine ...

``` bash
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:      
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12    
```

... but what I really don't understand is when I install any other package like `gulp` or `imagemin-pngquant` (it doesn't matter which NPM package) it shows me the same message like above.

I wouldn't know why NPM should hint a message for the unsupported message of another module every time NPM installs another module which don't even have any connections to the other module with the notsup error.

I know that the `--no-optional` flag on every single new module install command surpresses the warning message but this can't be the solution for this case.
#### How can the CLI team reproduce the problem?

This example only works on windows machines;

``` bash
npm install --save-dev chokidar # notsup
npm install --save-dev gulp gulp-if gulp-uglify # notsup again
```
### supporting information:
- `npm -v` prints: 3.8.9
- `node -v` prints: 4.2.2
- `npm config get registry` prints: https://registry.npmjs.org/
- Windows, OS X, or Linux?: Windows 10
- Network issues:
  - Geographic location where npm was run:
  - [ ] I use a proxy to connect to the npm registry.
  - [ ] I use a proxy to connect to the web.
  - [ ] I use a proxy when downloading Git repos.
  - [ ] I access the npm registry via a VPN
  - [ ] I don't use a proxy, but have limited or unreliable internet access.
- Container:
  - [ ] I develop using Vagrant on Windows.
  - [ ] I develop using Vagrant on OS X or Linux.
  - [ ] I develop / deploy using Docker.
  - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by InfiniteStyles** [comment]
I'm getting this same error on Windows 10, I always assumed it was because Gulp requested the **fsevents ** module somewhere in its dependencies. As that is the only thing that made sense

Are you sure that Gulp and all its sub-dependencies are completely seperated from **fsevents**?
