### ISSUE TITLE
"$ sudo npm install --save-dev gulp" going wrong

### ISSUE THREAD

**Issue by zjj796** [npm/npm#13263]
I'm opening this issue because:
npm is producing an incorrect install.
"$ sudo npm install --save-dev gulp" going wrong

![image](https://cloud.githubusercontent.com/assets/19684548/16550012/197fb9ce-41d8-11e6-90e0-cade70ccf3be.png)

![image](https://cloud.githubusercontent.com/assets/19684548/16550021/2ab2dbfe-41d8-11e6-9670-64aea8ddd05e.png)

the folder:
bin     doc     LICENSE     package.json     TESTING.md 
CHANGELOG.md     gulpfiles.js     node_modules     README.md     vendor 
CONTRIBUTING.md     lib     npm-debug.log    res

node --version
v4.2.6
npm --version
3.5.2

thank you!

**Comment by KenanY** [comment]
@zjj796 Does this also occur with the latest stable release of `npm@3`? At this time it is `npm@3.10.3`.

**Comment by zjj796** [comment]
i installed npm@3.10.3 and download a new node
then npm --version
3.9.5
but npm install is fine.
thanks!
