### ISSUE TITLE
Feature Request: force latest semver match for dependency

### ISSUE THREAD

**Issue by mscdex** [npm/npm#13279]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [ ] npm is producing an incorrect install.
- [ ] npm is doing something I don't understand.
- [X] Other (_see below for feature requests_):

#### What's the feature?

Allow `dependency` values that _force_ the latest version matching the specified semver range.
#### What problem is the feature intended to solve?

Here is the problem: imagine you install two modules that share a dependency, but with different version requirements. One of these modules ("module A") uses a semver range specifier (e.g. `^2.3.0`) and the other ("module B") uses a specific version (e.g. `2.3.1`). Currently when these modules get installed, both modules will use and share version `2.3.1` of this dependency. Now imagine that `2.3.1` happens to have a showstopping bug in it and people start to complain to the author of "module A" because of the bug and the need to update the range to `^2.3.2` to include the fix for the bug.

This problem gets even worse when you have _many_ modules that all use the same semver range for the same dependency module. To me, one of the major benefits of being able to specify a range in the first place is (would be) that I don't have to continually update my package.json (to get the "latest" matching version).
#### Is the absence of this feature blocking you or your team? If so, how?

This problem is _really_ annoying when trying to manage a bunch of modules. It's blocking me from being a _happy_ and _productive_ developer.
#### Is this feature similar to an existing feature in another tool?

No idea.
#### Is this a feature you're prepared to implement, with support from the npm CLI team?

Uh, sure, but I don't think this would be particularly hard to implement? Perhaps add an extra symbol to denote this "force latest match" (e.g. `+`)?

**Comment by lxe** [comment]
So version-pinned dependencies are preventing semver-ranged dependencies from updating automatically?

My perspective on this has been to never assume that semver ranges mean that "always download the latest version that matches the semver range." Semver range means that "any version in the range is valid". 

If some version of some sub-dependency in your tree contains a bug or a secury flaw, it's the responsibility of the dependency using that uses that sub-dependency to eliminate that buggy version from the semver range, and not to assume that it will be automatically upgraded.

**Comment by mscdex** [comment]
> My perspective on this has been to never assume that semver ranges mean that "always download the latest version that matches the semver range." Semver range means that "any version in the range is valid".

I never assumed this, but this feature request is asking to support this. :-)

> If some version of some sub-dependency in your tree contains a bug or a secury flaw, it's the responsibility of the dependency that uses that sub-dependency to eliminate that buggy version from the semver range, and not to assume that it will be automatically upgraded.

Good luck telling that to end users. Being able to force the latest version will avoid the problem altogether. I can't sit around and wait for the author of some random module to change their package.json *and* publish a new version containing those changes. Even *if* they did so, that doesn't help people that already have an older version of that module installed.

**Comment by JerryCauser** [comment]
> Here is the problem: imagine you install two modules that share a dependency, but with different version requirements.
Is it really trouble? If your are using `dedupe`, then take responsibility for that action. If you install packages simply `npm i` — packages will not use same modules.

**Comment by mscdex** [comment]
@JerryCauser I can't speak for the end users, but I am assuming they are just using `npm install`. Doesn't npm 3.x do more dependency module sharing out of the box?
