### ISSUE TITLE
v3.10.0+ Regression: progress bar new lines on Windows

### ISSUE THREAD

**Issue by AviVahl** [npm/npm#13274]
Post the recent progress bar improvement patches (v3.10.0), npm prints every update to the progress bar in its own line.

Does not occur on npm2 or older npm3
#### How can the CLI team reproduce the problem?

Hopefully you can reproduce it on your end by opening command prompt on Windows and running `npm i <any valid package>`.
### supporting information:
- `npm -v` prints: **3.10.4**
- `node -v` prints: **0.12.14**
- `npm config get registry` prints: **https://registry.npmjs.org/**
- Windows, OS X, or Linux?: **Windows 10 (+all updates)**

FYI @iarna

Tested on Command Prompt, PowerShell , Cmder. Regressed on all.
![image](https://cloud.githubusercontent.com/assets/8952081/16579749/deb21ff8-42a9-11e6-80df-ba65c8dded17.png)

**Comment by iarna** [comment]
This doesn't repro for me so I'm not sure what could be causing this...

**Comment by iarna** [comment]
ah 0.12... I'll see about trying that (0.12 is pretty buggy), I've been using LTS for testing.

**Comment by iarna** [comment]
I _am_ seeing the progress bar not being colored correctly, Which grr. I'm currently using the `invert` ANSI code which is apparently being ignored, so I may have to switch to explicitly setting white on black for Windows at least.

**Comment by iarna** [comment]
And yup, totally does fail in node 0.12. That is super weird.

**Comment by iarna** [comment]
Ok, I just tested with the latest 0.10, 0.12, v4, v5 & v6 branches and it only fails in 0.10 and 0.12.

**Comment by iarna** [comment]
I've opened an issue over on gauge and further work on fixing this will happen there.

**Comment by AviVahl** [comment]
Oh, nice catch. Thank you for looking into this.
Should I close this ticket and track the other one?
I'm afraid I have to use 0.12 until my team bumps the minimum requirements to current node LTS... :(
