### ISSUE TITLE
I want to unpublish modules that are dead and completely unused.

### ISSUE THREAD

**Issue by robcolbert** [npm/npm#13277]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [X] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I can't unpublish modules.

#### How can the CLI team reproduce the problem?

"npm unpublish --force" in an NPM module's directory.

### supporting information:

 - `npm -v` prints:
3.10.2

 - `node -v` prints:
v4.4.6

 - `npm config get registry` prints:
https://registry.npmjs.org/

 - Windows, OS X, or Linux?:
Linux (KXStudio/Ubuntu 14.04 LTS)

**Comment by KenanY** [comment]
@robcolbert Due to a [change in unpublish policy](http://blog.npmjs.org/post/141905368000/changes-to-npms-unpublish-policy), you are going to have to contact `support@npmjs.com`.

**Comment by robcolbert** [comment]
Easier to update all the packages to have the contact information *of* support and nuke the repos out from under them. That way, as people get in touch to learn why the project isn't working, it's literally the support email they're using to ask about it. That'll work for me.

Read up. It's your policy. That's okay. But, there are about 30-ish modules under a now-dead github organization (@decentraleyes). And, it's dead thanks to a name collision with another project I dind't know about when starting (a simple browser extension).

So, the @decentraleyes/* repos aren't used anymore. These modules were never used by anyone (at all) as I haven't even been marketing this or telling people about it. That is a fact a computer can check and allow. So, I just don't mind abandoning 30+ modules. Because, no, I don't know what interacting with support would be like over this. And, I just don't want to take the time.

Again - it's your policy. The modules are dead. They should be deleted.

**Comment by KenanY** [comment]
Closing since there's nothing more to be done here.
