### ISSUE TITLE
npm causes inode pollution

### ISSUE THREAD

**Issue by srcspider** [npm/npm#13271]
_For anyone who doesn't know, an inode is a filesystem structure used to store metadata on directories and files. There's a hard limit on them. If you run out you can't actually do anything even if you technically have disk space._

`npm` has been built on the philosophy of splitting everything into tiny super specialized modules. This has worked great for general cases, and traditional servers, but there's a problem. 

For things like docker & kubernetes this causes some very severe problems with inodes.

To put things in perspective, an average node in a google container engine cluster has a capacity 6'553'600 inodes. In the worst case scenario if you're using npm@2 and dont dedupe a install will eat up around 65000 inodes. Basically do that 100 times and you've eaten up all the inodes just from npm installs alone. We'll get back to why "100 times" is very little in this context shortly.

Traditionaly this isn't a problem. Normal servers usually use some sort of file sync so a server only really pays the cost once, which makes even something like 65000 not be anything to worry about. However when you have docker images in combination with npm and containers in a service oriented architecture, things are just anything but acceptable. Each container, even if you initialize it from the same image will eat its own share of inodes, images themselves will also happily eat inodes just sitting on disk. So for example, if you just happen to have 10 things running on the node, each derived from the same 65000 inode npm install you now have just 90/100 installs left. Maybe you make some improvements and deploy some new images and containers, well if those 10 alone update that's another 10 installs gone. As you can probably tell by now, it's super easy to destroy servers with this. Monitoring inodes is also generally _not a thing_, it's just too unreasonable for anything to eat that much that systems like kubernetes generally monitor only disk usage.

And yes the 65000 has the caveat here that it's a `npm@2` install, but if you're not aware of it you're not really gonna notice it easily (at least not until you get failures).

`npm@3` produces better results, but still very inode hungry compared to average applications. The equivalent to the previous example in `npm@2` is of 8082, so 8x smaller inode usage. If you're using docker images or anything similar you definitely want to use `npm@3` exclusively, but this is from another perspective just... 8 times slower to reach the limit.

8000 is actually quite large. To put it into perspective do you have 8000 sources files? probably not for the average project. Does it really make sense that you have 8000 dependencies? Well as it turns out those 8000 dependencies are mostly junk. There are a lot of patterns and "recommended practices" that don't really amount to much on their own but when reaching critical mass make quite a difference in a negative way.

Just for the purpose of testing I've made this crude script for removing unseful files. Note that things like licenses can be aggregated into a single file for statistics and other purposes, so they really don't have much right to be scattered in node_modules.

``` ruby
#!/usr/bin/env ruby

require 'fileutils';
require 'json';

unusable_extentions = [
    '.exe',
    '.coffee',
    '.old',
    '.patch',
    '.md', '.markdown', '.mdown', '.txt',
    '.gz',
    '.el',
    '.bat',
    '.flow',
    '.map'
]

unusable_misc_files = [
    '.npmignore',
    '.travis.yml',
    '.jshintrc',
    '.editorconfig',
    '.jshintignore',
    '.gitattributes',
    '.eslintrc',
    '.lint',
    '.keep',
    '.spmignore',
    '.zuul.yml',
    '.gitmodules',
    '.dockerignore',
    '.babelrc',
    '.eslintignore',
    'appveyor.yml',
    'gnumakefile',
    'makefile',
    'authors',
    'readme',
    'license', 'licence', 'license-mit', 'license.mit', 'license.bsd', 'license.apache2', 'license-jsbn',
    'changelog', 'changes',
    'contributors',
    'patents',
    'todo'
]

unusable_misc_dirs = [
    'test',
    'man',
    '__tests__',
    'benchmark',
    'tests',
    'debug',
    'coverage',
    'example',
    'examples',
    'doc'
]


Dir.glob("./node_modules/**/{*,.*}").each do |file|

    basename = File.basename(file);
    name = basename.downcase

    if ! File.directory? file

        ext = File.extname(file)

        if ext != '.js' && ext != '.json'
            if unusable_extentions.include?(ext)
                FileUtils.rm_rf file, :verbose => true
            elsif unusable_misc_files.include?(name) || name =~ /\~$/
                FileUtils.rm_rf file, :verbose => true
            else
                puts file + ' -> ' + name
            end
        elsif name == 'package.json'
            dir = File.dirname(file)
            if File.exists?("#{dir}/index.js")
                package = JSON.parse(File.read("#{dir}/package.json"));
                if ! package.key?('main') || package['main'] == 'index.js'
                    FileUtils.rm_rf file, :verbose => true
                end
            end
        elsif name == 'bower.json'
            FileUtils.rm_rf file, :verbose => true
        end

    else # directory
        if unusable_misc_dirs.include?(name)
            FileUtils.rm_rf file, :verbose => true
        end
    end

end#glob
```

Running the script reduces node_modules from 8082 to 6309. This gain of 1773 might seem insignificant, but to put it into perspective, a wordpress install is just 1472.

In the remaining 6309 generally have a situation of structures like this,

``` bash
module_name/
    index.js
    package.json
```

Or this,

``` bash
module_name/
  lib/
     module_name.js
  package.json
```

There are other patterns but these two are the most common. Sometimes (after removing the dotfiles and others) the structure above is all you see (exactly as many files and directory as you see there). This is actually inefficient, not just in inodes but in space as well. For one the package json almost always larger or just as large as the actual module code! (it's a bit absurd). In large part this is due to boilerplate from npm (metadata from what I can tell), as well as what I would call "stale" data: description, boilerplate, tags, etc. 

The metadata in package.json should not be in proximity to the modules. I don't think there's any disadvantage to just placing all of it in a separate file and purging it of npm specific configuration data (keywords and whatnot). This way it's easy in deployments to ignore or include the metadata by choice, rather then being forced to.

As for inodes, the most ideal resolution for modules following the structure above (single library file) is as follows:
- relevant metadata files (readme, license files etc) concatenated into a single database file outside of npm
- package.json main resolved and the file removed with metadata in a separate db file outside of node_modules
- the entire module resolved to `module_name.js` since if it's just 1 file the directory is completely unnecessary, so long as its directly in `node_module` it will resolve

This results in 3x to 4x smaller inode usage for those cases (and they are quite common).

The more extreme and ideal solution in the case of server applications is for npm to have the ability to (at least partially) compile all modules into a single bundle and have a hook that installs into `require`. Depending on circumstances 65000 or more inode disaster would be converted to 2-3 inodes (constant). However this solution may be hard when it comes to compatibility.

Honestly I don't know what the best solution is, but hopefully something can be done about this since growing inode limit is most of the time impossible and frankly unreasonable. Monitoring systems should probably keep a watch but when it gets to absurd values in usage you're generally left with bad choices; and unfortunately many don't monitor inodes. And even if that wasn't the case aggressively garbage collecting results in loss of flexibility, and overall absurd inode usage lowers limits and options for no good reason.

**Comment by LoveIsGrief** [comment]
We're running into this problem as well. We have ~10 projects which each have their own `package.json` and the last count of files: 4M files.

The projects have similar dependencies and yet those dependencies are copied to each respective `node_modules` folder.

[npm-folders](https://docs.npmjs.com/files/folders)
>When you run **npm install foo@1.2.3**, then the package is loaded into the cache, and then unpacked into **./node_modules/foo**. Then, any of foo's dependencies are similarly unpacked into **./node_modules/foo/node_modules/....**

A possible solution would be to enable symlinking or even hardlinking instead of unpacking the deps from the cache into the `node_modules` folders.

**Comment by shaunwarman** [comment]
This is a really valid and well written issue.

**Comment by ghost** [comment]
Does yarn solve this issue?

Edit: Seems like they're on the right track https://github.com/yarnpkg/yarn/commit/3dc9cf43448da51d3b8890de339a0ed27b12ca62
