### ISSUE TITLE
GULP не запускается

### ISSUE THREAD

**Issue by DjusTV** [npm/npm#13276]
C:\Users\Alex\Desktop\Home\OpenServer\domains\kpk.ru>npm i gulp -g npm ERR! tar.unpack error reading C:\Users\Alex\Desktop\Home\OpenServer\domains\kpk.ru\gulp npm ERR! addLocal Could not install C:\Users\Alex\Desktop\Home\OpenServer\domains\kpk.ru\gulp npm ERR! Windows_NT 10.0.10586 npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "i" "gulp" "-g" npm ERR! node v4.4.7 npm ERR! npm v2.15.8

npm ERR! 0-byte tarball npm ERR! Please run npm cache clean npm ERR! npm ERR! If you need help, you may report this error at: npm ERR! https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request: npm ERR! C:\Users\Alex\Desktop\Home\OpenServer\domains\kpk.ru\npm-debug.log

C:\Users\Alex\Desktop\Home\OpenServer\domains\kpk.ru>gulp module.js:327 throw err; ^

Error: Cannot find module 'vinyl' at Function.Module._resolveFilename (module.js:325:15) at Function.Module._load (module.js:276:25) at Module.require (module.js:353:17) at require (internal/module.js:12:17) at Object. (C:\Users\Alex\AppData\Roaming\npm\node_modules\gulp\node_modules\gulp-util\index.js:2:9) at Module._compile (module.js:409:26) at Object.Module._extensions..js (module.js:416:10) at Module.load (module.js:343:32) at Function.Module._load (module.js:300:12) at Module.require (module.js:353:17)

**Comment by KenanY** [comment]
@DjusTV Have you tried running `npm cache clean`?

**Comment by KenanY** [comment]
Closing as abandoned.
