### ISSUE TITLE
failed to install unlock-apk

### ISSUE THREAD

**Issue by lzhang1** [npm/npm#13275]
root@zhanglei-ThinkPad-X240:~# cnpm install unlock-apk -g 
npm ERR! Linux 4.2.0-42-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "--registry=https://registry.npm.taobao.org" "--cache=/root/.npm/.cache/cnpm" "--disturl=https://npm.taobao.org/dist" "--userconfig=/root/.cnpmrc" "install" "unlock-apk" "-g"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5

npm ERR! No compatible version found: ant-build@~1.0.0
npm ERR! Valid install targets:
npm ERR! 0.1.4, 0.1.3, 0.1.2, 0.1.1, 0.1.0
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log

**Comment by KenanY** [comment]
@lzhang1 Hmm, does this also occur when you use the default registry?

**Comment by lzhang1** [comment]
seems not.

root@zhanglei-ThinkPad-X240:~# npm install unlock-apk 
npm ERR! Linux 4.2.0-42-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "unlock-apk"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5

npm ERR! No compatible version found: ant-build@~1.0.0
npm ERR! Valid install targets:
npm ERR! 0.1.4, 0.1.3, 0.1.2, 0.1.1, 0.1.0
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log

**Comment by KenanY** [comment]
@lzhang1 I would bring this up with the author of `unlock-apk`, since it seems like that module is depending on a version of `ant-build` which does not exist in the npm registry.

**Comment by KenanY** [comment]
Closing since this does not appear to be that `npm` can solve.
