### ISSUE TITLE
missing script start

### ISSUE THREAD

**Issue by crashspringfield** [npm/npm#13278]
WhenIi try to npm start I get this error

    0 info it worked if it ends with ok
    1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
    2 info using npm@3.9.3
    3 info using node@v6.2.1
    4 verbose stack Error: missing script: start
    4 verbose stack     at run (/usr/lib/node_modules/npm/lib/run-script.js:150:19)
    4 verbose stack     at /usr/lib/node_modules/npm/lib/run-script.js:60:5
    4 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:356:5
    4 verbose stack     at checkBinReferences_ (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:320:45)
    4 verbose stack     at final (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:354:3)
    4 verbose stack     at then (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:124:5)
    4 verbose stack     at ReadFileContext.<anonymous> (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:295:20)
    4 verbose stack     at ReadFileContext.callback (/usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16)
    4 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:359:13)
    5 verbose cwd /home/crash/js/node/newboston/myapp
    6 error Linux 3.19.0-32-generic
    7 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
    8 error node v6.2.1
    9 error npm  v3.9.3
    10 error missing script: start
    11 error If you need help, you may report this error at:
    11 error     <https://github.com/npm/npm/issues>
    12 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@crashspringfield Do you have a `"start"` script defined in your `package.json`?

**Comment by SimenB** [comment]
Start doesn't have to be defined, as per the [https://docs.npmjs.com/cli/start](docs)

**Comment by KenanY** [comment]
@SimenB You are correct, I did not mean to imply that one was necessary. Nevertheless this is always the first question I ask for these kinds of issues.

**Comment by crashspringfield** [comment]
I do. I think I figured out the issue. When I use the express generator, for some reason it isn't creating bin/www. Is there a repository with that file? I could just put that into my project and see if that does the trick.

**Comment by KenanY** [comment]
@crashspringfield Do you have a link to this generator?

**Comment by crashspringfield** [comment]
Sorry I didn't frame that well. I followed the direction on the express website:
    npm install express
    npm install express
    express /appname && cd /appname
    npm install
    npm start

but npm start throws the error

**Comment by crashspringfield** [comment]
{
      "name": "express_tut",
      "version": "1.0.0",
      "private": true,
      "description": "express tutorial",
      "main": "app.js",
      "scripts": {
        "start": "node ./bin/www",
        "test": "echo \"Error: no test specified\" && exit 1"
      },
      "author": "",
      "license": "ISC",
      "dependencies": {
        "body-parser": "^1.15.2",
        "cookie-parser": "^1.4.3",
        "debug": "~2.2.0",
        "ejs": "^2.4.2",
        "express": "^4.14.0",
        "express-handlebars": "^3.0.0",
        "express-session": "^1.14.0",
        "formidable": "^1.0.17",
        "fs": "0.0.2",
        "kerberos": "~0.0.17",
        "mongodb": "~2.0.33",
        "morgan": "~1.6.1",
        "parseurl": "^1.3.1",
        "serve-favicon": "~2.3.0"
      }
    }

**Comment by KenanY** [comment]
@crashspringfield Thanks. I _think_ [this](https://github.com/expressjs/generator/blob/aa54de6c5816d23a34b530575a661d2c38b25f66/templates/js/www) might be the `www` file you are looking for, but I could be wrong.

**Comment by crashspringfield** [comment]
yes! and putting it in there got npm start to work. still not sure why it didn't show up like it was supposed to, but i guess that's more of an issue with express.

**Comment by faridhwisanggeni** [comment]
how about this? i have same error with @crashspringfield, i use "start bla..bla.." but still same error..?

{
  "name": "node-testing-tdd",
  "version": "1.0.0",
  "description": "Node.js on Docker",
  "author": "First Last <first.last@example.com>",
  "main": "app.js",
  "scripts": {
    "start": "node app.js"
  },
  "dependencies": {
    "express": "^4.14.0",
    "request": "^2.65.0"
  },
  "devDependencies": {
    "chai": "^3.4.0",
    "mocha": "1.6.0",
    "nock": "^2.17.0",
    "sinon": "^1.17.2"
  },
  "scripts": {
    "test": "mocha tests/**"
  } 
}

**Comment by faridhwisanggeni** [comment]
ok, i have found the trouble

i used 
"main": "app.js",
"scripts": {
"start": "node app.js"
},


and must be

"main": "server.js",
"scripts": {
"start": "node server.js"
},
