### ISSUE TITLE
Error run command  "npm run gulp"

### ISSUE THREAD

**Issue by donmacoba** [npm/npm#13285]
Whwn i run this command  "npm run gulp"  here's the error below

0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli   'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'gulp' ]
2 info using npm@3.6.0
3 info using node@v5.6.0
4 verbose stack Error: missing script: gulp
4 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:147:19)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:57:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:345:5
4 verbose stack     at checkBinReferences_ (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:309:45)
4 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:343:3)
4 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:113:5)
4 verbose stack     at ReadFileContext.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:284:20)
4 verbose stack     at ReadFileContext.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:76:16)
4 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete](fs.js:324:13)
5 verbose cwd C:\Users\Don.Acoba\Downloads\themeforest-12931855-fuse-angularjs-material-design-admin-template\Fuse-1.3.0-demo
6 error Windows_NT 6.1.7601
7 error argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "run" "gulp"
8 error node v5.6.0
9 error npm  v3.6.0
10 error missing script: gulp
11 error If you need help, you may report this error at:
11 error     https://github.com/npm/npm/issues
12 verbose exit [ 1, true ]

**Comment by watilde** [comment]
Hello! The actual error is `missing script: gulp` and it usually means something wrong in your `package.json`. Could you check the script field in your `package.json` or see the result of `npm run`? If there is no gulp property in your scripts field, it is the `missing script: gulp`. It should be like the following:

```json
{
...
  "scripts": {
    "gulp": "gulp"
  },
...
}
```

related docs:
+ https://docs.npmjs.com/files/package.json#scripts
+ https://docs.npmjs.com/misc/scripts#default-values
