### ISSUE TITLE
npm install -g browser-sync

### ISSUE THREAD

**Issue by beni1** [npm/npm#13280]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
err
### supporting information:
C:\Users\username>npm -version
2.14.7

C:\Users\username>npm install -g browser-sync
npm ERR! tar.unpack error reading C:\Users\sonee\browser-sync
npm ERR! addLocal Could not install C:\Users\sonee\browser-sync
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x8
6)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "browser-sync"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7

npm ERR! 0-byte tarball
npm ERR! Please run `npm cache clean`
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\username\npm-debug.log

**Comment by beni1** [comment]
error

**Comment by KenanY** [comment]
@beni1 Have you tried running `npm cache clean`?

**Comment by beni1** [comment]
Yes I did it, still error. I have nodejs 4.2.1, but I need nodejs 4.2.4 but cannot find it from search engine.

Sent from Yahoo Mail on Android

**Comment by KenanY** [comment]
@beni1 Is there a `npm-debug.log` file you can upload to https://gist.github.com/?

**Comment by beni1** [comment]
Ok thanks I will check tomorrow as its over midnight in scandinavia

Sent from Yahoo Mail on Android

**Comment by beni1** [comment]
Here is the attached file, but I don't know how to complete the sending in github as I don't know what filename extension is needed. 

    On Wednesday, July 6, 2016 1:10 AM, Kenan Yildirim <notifications@github.com> wrote:
 

 @beni1 Is there a npm-debug.log file you can upload to https://gist.github.com/?—

**Comment by KenanY** [comment]
@beni1 Sorry, looks like the attachment did not go through. I suggest uploading it to https://gist.github.com/ and posting the link here.

**Comment by beni1** [comment]
what is the filename extention, since i tried it before and it did not work,  and i think the sending in should be private (not public) in github 

    On Wednesday, July 6, 2016 5:58 PM, Kenan Yildirim <notifications@github.com> wrote:
 

 @beni1 Sorry, looks like the attachment did not go through. I suggest uploading it to https://gist.github.com/ and posting the link here.—

**Comment by KenanY** [comment]
@beni1 `.log`, `.txt`, `.js`, doesn't matter as long as it isn't binary. You can just copy the contents and paste it into the editor at gist.github.com. For example, here is a log I upload there a long time ago:https://gist.github.com/KenanY/e15cd48fe46b4af354ee

**Comment by beni1** [comment]
Hi, 
I sent the npm-debug.log file as secret, not public, I hope you can find it.
regards 

    On Wednesday, July 6, 2016 10:01 PM, Kenan Yildirim <notifications@github.com> wrote:
 

 @beni1 .log, .txt, .js, doesn't matter as long as it isn't binary. You can just copy the contents and paste it into the editor at gist.github.com. For example, here is a log I upload there a long time ago:https://gist.github.com/KenanY/e15cd48fe46b4af354ee—

**Comment by KenanY** [comment]
@beni1 Why not just post the link instead of making me find it?

**Comment by legodude17** [comment]
I do not have this problem. It looks like it is trying to install a package from local fs instead of registry. Try running `npm install browser-sync` (Without global option).

**Comment by KenanY** [comment]
Closing as abandoned.
