### ISSUE TITLE
Error 403 in publishing in npm 

### ISSUE THREAD

**Issue by tanngo** [npm/npm#13288]
I try to publishing a demo source in npm and I encountered this problem . Please help me to fix this issue. Thanks in advance
E:\Evizi\Plugins\Test>npm publish
npm ERR! publish Failed PUT 403
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe
" "C:\\Program Files\\nodejs\\node_modules\\npm\\b
in\\npm-cli.js" "publish"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code E403

npm ERR! you do not have permission to publish "co
rdova-plugin-tag-manager". Are you logged in as th
e correct user? : cordova-plugin-demo
npm ERR!
npm ERR! If you need help, you may report this err
or at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with an
y support request:
npm ERR!     E:\Evizi\Plugins\Test\npm-debug.log

**Comment by KenanY** [comment]
@tanngo Do you have permission to publish new versions of `cordova-plugin-tag-manager`?

**Comment by KenanY** [comment]
Closing as abandoned.
