### ISSUE TITLE
Issue installing express

### ISSUE THREAD

**Issue by katawura** [npm/npm#13282]
l keep getting this error trying to install express.js on my mac

```
34 error Darwin 15.5.0
35 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "express"
36 error node v6.2.2
37 error npm  v3.9.5
38 error code ENOSELF
39 error Refusing to install express as a dependency of itself
```

Any idea what this might be?

**Comment by KenanY** [comment]
@katawura Please ensure that the `"name"` property of your `package.json` is not set to `"express"`.

**Comment by KenanY** [comment]
Closing as abandoned.
