### ISSUE TITLE
Publish a version but the website is not up to date

### ISSUE THREAD

**Issue by afshinm** [npm/npm#13291]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?
I have published a new version but the website is not up to date after 2 days. Also, I can't republish/unpublish or anything else. 

When I try to publish that version again I get:

```
"You cannot publish over the previously published version 2.2.0." : intro.js
```

#### How can the CLI team reproduce the problem?
npm publish

### supporting information:

 - `npm -v` prints: 3.8.6
 - `node -v` prints: v5.5.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X, or Linux?: OS X
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [x] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [x] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by gmaniac** [comment]
I am running into the same problem.

Did this fix itself over time or did you end up having to do anything?

**Comment by afshinm** [comment]
@gmaniac I sent a message to the support team and they fixed the issue manually.

**Comment by gmaniac** [comment]
@afshinm I will submit a ticket then, thank you.

**Comment by KenanY** [comment]
Closing as not an issue with `npm` specifically (sounds like a registry/website issue).
