### ISSUE TITLE
EXDEV: cross-device link not permitted, rename... in Docker

### ISSUE THREAD

**Issue by AveVlad** [npm/npm#13306]
#### I'm opening this issue because:

  - [x] npm is crashing.

```
npm WARN optional Skipping failed optional dependency /webpack/watchpack/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! path /app/node_modules/istanbul/node_modules/abbrev
npm ERR! code EXDEV
npm ERR! errno -18
npm ERR! syscall rename

npm ERR! EXDEV: cross-device link not permitted, rename '/app/node_modules/istanbul/node_modules/abbrev' -> '/app/node_modules/abbrev'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /app/npm-debug.log
The command '/bin/sh -c npm install' returned a non-zero code: 238

```

after remove `istanbul`

```
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! path /app/node_modules/express/node_modules/array-flatten
npm ERR! code EXDEV
npm ERR! errno -18
npm ERR! syscall rename

npm ERR! EXDEV: cross-device link not permitted, rename '/app/node_modules/express/node_modules/array-flatten' -> '/app/node_modules/array-flatten'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /app/npm-debug.log
`
``` 

### supporting information:

 - `npm -v` prints:  v3.10.3
 - `node -v` prints:  v6.3.0
 - `npm config get registry` prints:
 - Windows, OS X, or Linux?: Linux
 - Container:
   - [x] I develop / deploy using Docker.

**Comment by azumads** [comment]
@AveVlad  How to fix this?

**Comment by AveVlad** [comment]
@azumads Are you using docker for develop/build?

**Comment by azumads** [comment]
yes, finally find this

RUN cd $(npm root -g)/npm \
        && npm install fs-extra \
        && sed -i -e s/graceful-fs/fs-extra/ -e s/fs\.rename/fs.move/ ./lib/utils/rename.js

**Comment by acgourley** [comment]
Thank you @azumads  that solved my issue which looked like

```
npm ERR! EXDEV: cross-device link not permitted, rename '/common/node_modules/babel-core/node_modules/babel-register/node_modules/babel-runtime' -> '/common/node_modules/babel-core/node_modules/babel-register/node_modules/.babel-runtime.DELETE'
```

**Comment by gerich-home** [comment]
I also experienced the similar issue, but what helped me is that I moved the line that was setting permissions for non-root user to the bottom of my Dockerfile:
```
RUN chown -R app:app $HOME/*
```

For some reason root was not able to run npm install after permissions were changed (probably it is fine, I dunno, I am windows guy =) )

**Comment by MicahZoltu** [comment]
I'm curious why this was closed?  It seems the issue is a real one and while someone has provided a workaround, that seems like a temporary (and pretty nasty) hack.

**Comment by aerze** [comment]
@MicahZoltu Issue is resolved in npm v4.2.2 https://github.com/npm/npm/pull/15901

**Comment by devonwesley** [comment]
Wow thanks alot @azumads it solved my problem right away.

**Comment by jeff3dx** [comment]
You were probably using "npm link" functionality, then attempted to build a docker image locally.  The symlink gets saved in your package.lock file which leads to npm complaining about the link being cross-machine from within the docker image. Delete your package.lock file, reinstall whatever module it's complaining about, then try building your docker image again..

**Comment by ThibaultJanBeyer** [comment]
After doing what @azumads recommends.
I get `/bin/sh: 1: cd: can't cd to /usr/local/lib/node_modules/npm` …
