### ISSUE TITLE
shrinkwrap including dev deps deps

### ISSUE THREAD

**Issue by iarna** [npm/npm#13303]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

`npm shrinkwrap` is including dependencies of dev dependencies even when the shrinkwrap file didn't have any dependencies.

#### How can the CLI team reproduce the problem?

Save any module that has dependencies as a dev dep. Run `npm shrinkwrap` see how the transitive deps are included

**Comment by SimenB** [comment]
This is the same as #13227?
