### ISSUE TITLE
.npmignore weird behaviour

### ISSUE THREAD

**Issue by noodle71** [npm/npm#13314]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I've a .npmignore file with this content:

.gradle/
node_modules/
target/
test/
assembly/
build/
doc/
washemo.iml
pom.xml
gulpfile.js
.editorconfig
.npmignore

Everytime I publish the package, there's a file within the module root folder which name is "index.js" that is not included.

If I remove the last line of the previous file (.npmignore), then the package includes the .npmignore file and the index.js. Why .npmignore can't ignore only the .npmignore file? I've read the documentation and says that .npmignore is ignored by default but I don't know why, when I try to ignore .npmignore file, the index.js file is ignored as well.

#### How can the CLI team reproduce the problem?

Have a "index.js" file within module root directory. Then add a .npmignore file with this content:
.npmignore

When you publish and install it, then you .npmignore and index.js file are not included.

### supporting information:

 - `npm -v` prints:3.9.3
 - `node -v` prints:v6.2.1
 - `npm config get registry` prints:https://sinopia.logtrust.com/
 - Windows, OS X, or Linux?:Linux
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
Cannot reproduce with Node.js 6.2.2, `npm@3.10.5`:

``` bash
$ ls
index.js  node_modules  package.json

$ cat .npmignore
.npmignore

$ npm pack
$ tar -tf test-1.0.0.tgz
package/package.json
package/index.js
```

**Comment by KenanY** [comment]
@noodle71 Still seeing this issue?

**Comment by noodle71** [comment]
Yes, index.js isn't within the package

```sh
afernandez:~/repo/was > ls -lart
total 24
drwxr-xr-x 36 afernandez afernandez 4096 sep 21 16:47 ..
-rw-rw-r--  1 afernandez afernandez   11 sep 21 17:01 .npmignore
-rw-rw-r--  1 afernandez afernandez   21 sep 21 17:02 index.js
-rw-rw-r--  1 afernandez afernandez   85 sep 21 17:07 package.json
drwxrwxr-x 28 afernandez afernandez 4096 sep 21 17:07 node_modules
drwxrwxr-x  3 afernandez afernandez 4096 sep 21 17:10 .

afernandez:~/repo/was > cat .npmignore 
.npmignore

afernandez:~/repo/was > cat index.js 
module.exports = {};

afernandez:~/repo/was > cat package.json 
{
  "name": "test",
  "version": "0.0.1",
  "dependencies":{
    "del":"1.1.1"
  }
}


afernandez:~/repo/was > rm -rf node_modules/ && npm install
afernandez:~/repo/was > npm pack && tar -tf test-0.0.1.tgztest-0.0.1.tgz
package/package.json
package/test-0.0.1.tgz
```

**Comment by KenanY** [comment]
Somehow I still can't reproduce this with `npm@3.10.8`. I'm at a complete lost as to why we are seeing different results.

**Comment by noodle71** [comment]
Don't know if I can help you...

```sh


afernandez:~/repo/was > npm -version
3.9.3

afernandez:~/repo/was > which npm
/home/afernandez/.nvm/versions/node/v6.2.1/bin/npm

afernandez:~/repo/was > which node
/home/afernandez/.nvm/versions/node/v6.2.1/bin/node

afernandez:~/repo/was > node --version
v6.2.1

afernandez:~/repo/was > uname -a
Linux afernandez-K55VD 4.4.0-38-generic #57-Ubuntu SMP Tue Sep 6 15:42:33 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by KenanY** [comment]
@noodle71 Just to make sure, could you try updating `npm`?

**Comment by noodle71** [comment]
Thanks! Finally works ;)

```sh
afernandez:~/repo/was > which node
/home/afernandez/.nvm/versions/node/v6.6.0/bin/node

afernandez:~/repo/was > node --version
v6.6.0

afernandez:~/repo/was > which npm
/home/afernandez/.nvm/versions/node/v6.6.0/bin/npm

afernandez:~/repo/was > npm --version
3.10.3

afernandez:~/repo/was > npm pack && tar -tf test-0.0.1.tgz
test-0.0.1.tgz
package/package.json
package/index.js
package/test-0.0.1.tgz


```

**Comment by KenanY** [comment]
:clap:
