### ISSUE TITLE
Windows install from git fails citing protocol after download

### ISSUE THREAD

**Issue by barneycarroll** [npm/npm#13312]
#### I'm opening this issue because:
- [x] npm is crashing.
#### What's going wrong?

`$ npm install giturl` where git URL is _any_ of the [recommended forms](https://docs.npmjs.com/files/package.json#git-urls-as-dependencies) (including http, https)

Gives me:

`Unsupported URL Type: ssh+git://...`

Notice ([`npm-debug.log`](https://gist.github.com/barneycarroll/1f50a373eeca6f247e1b576fbe141f1b)) that npm successfully fetches and unpacks the indicated source before deciding in some later process that the URL was the problem. Also worth mentioning is that the error is thrown regardless of which URL type is specified — I can specify https, and it will still succeed in fetching the source, and will still crash, telling me ssh+git is unsupported.
#### How can the CLI team reproduce the problem?

[`npm-debug.log`](https://gist.github.com/barneycarroll/1f50a373eeca6f247e1b576fbe141f1b)
### supporting information:
- `npm -v` prints:
  **3.10.4**
- `node -v` prints:
  **v4.4.5**
- `npm config get registry` prints:
  **https://registry.npmjs.org**
- Windows, OS X, or Linux?:
  **Windows 7, (Windows_NT 6.1.7601)**
- Network issues:
  - Geographic location where npm was run:
    **London, UK**

**Comment by KenanY** [comment]
Hmm, I cannot reproduce. I'll try downgrading to your Node.js version next.

``` bash
$ node -v
v6.2.2

$ npm -v
3.10.5

$ npm install git://github.com/lhorie/mithril.git
test@1.0.0 /tmp
└── mithril@0.2.5  (git://github.com/lhorie/mithril.git#3d6035db47d6ed16a915f11a064d6674f9f1546a)
```

**Comment by barneycarroll** [comment]
Thanks — when I get back to the offending Windows box in question I'll try Node version switching and see what that gives.

Do you have any tips for node step by step debugging? node-inspector doesn't play well with my OS (something about hardcoded system binaries reliance that's over my head). The thing that strikes me upon reading the logs is that the error message is wrong — there's nothing wrong with the git+ssh protocol (it resolves, it progressively downloads, completes, and logs a successful receipt of the tarball), and explicit https produces the same complaint of git+ssh not being a good protocol. So wherever the root problem lies, there's clearly a problem with the handover between the transfer subprocess and the controlling npm process and/or a problem in a subsequent process that isn't correctly identified by the superroutine which identifies it as a protocol failure…
