### ISSUE TITLE
npm ERR! Error: getaddrinfo ESRCH (CentOS7)

### ISSUE THREAD

**Issue by egberts** [npm/npm#13313]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - X[ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Attempting to install js-beautify but get the following error message:
   npm ERR! Error: getaddrinfo ESRCH
   npm ERR!    at errnoException (dns.js:37:11)
   npm ERR!    at Object.onanswer [as oncomplete] (dns.js:126:16)

More detail of npm-debug.log and console output here: https://gist.github.com/egberts/b4a4b501d3ca78e30fc9bc6f68a4dac4

#### How can the CLI team reproduce the problem?

Download js-beautify from https://github.com/beautify-web/js-beautify
Execute "build" script file.

### supporting information:

 - `npm -v` prints: 1.3.6
 - `node -v` prints: v0.10.42
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X, or Linux?: Linux, CentOS7, Linux 3.10.0-327.18.2.el7.x86_64
 - Network issues:
   - Geographic location where npm was run:  United States
   - [X ] I use a proxy to connect to the npm registry.
   - [ X] I use a proxy to connect to the web.
   - [ X] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
Closing as abandoned.

**Comment by egberts** [comment]
Thank you.  Apparently, CentOS7 is using an older npm.  Upgrading did the trick.
