### ISSUE TITLE
Error in npm install

### ISSUE THREAD

**Issue by sagarbasavaraj** [npm/npm#13311]
#### I'm opening this issue because:

Other (_see below for feature requests_):
#### What's going wrong?

npm ERR! registry error parsing json
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Users\pcw160\nodejs\node.exe" "C:\Users\pcw160\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v4.2.2
npm ERR! npm  v3.10.3
### supporting information:
- `npm -v` prints:node v4.2.2
- `node -v` prints: npm  v3.10.3
- `npm config get registry` prints:
- Windows, OS X, or Linux?: Windows
- Network issues:
  - Geographic location where npm was run:
  - [x] I use a proxy to connect to the npm registry.
  - [x] I use a proxy when downloading Git repos.
- Container:

**Comment by snypelife** [comment]
Occurs in OSX as well for https://github.com/c4milo/node-inotify.

```
11:38 $ npm i
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/Cellar/node/6.2.2/bin/node" "/Users/snypelife/.npm-packages/bin/npm" "i"
npm ERR! node v6.2.2
npm ERR! npm  v3.10.3
npm ERR! code EBADPLATFORM

npm ERR! notsup Not compatible with your operating system or architecture: inotify@1.4.1
npm ERR! notsup Valid OS:    linux
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   darwin
npm ERR! notsup Actual Arch: x64
```

**Comment by qmmr** [comment]
Same problem with inotify@1.4.1

```
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/qmmr/.nvm/versions/node/v6.3.1/bin/node" "/Users/qmmr/.nvm/versions/node/v6.3.1/bin/npm" "install"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.6
npm ERR! code EBADPLATFORM

npm ERR! notsup Not compatible with your operating system or architecture: inotify@1.4.1
npm ERR! notsup Valid OS:    linux
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   darwin
npm ERR! notsup Actual Arch: x64

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/qmmr/code/streetlife/exercises/AnetaTakucheva/npm-debug.log
```

**Comment by mikaoelitiana** [comment]
Anyone found a solution for this one?

**Comment by KenanY** [comment]
@sagarbasavaraj Could you please provide a `npm-debug.log` file?

**Comment by anthonyjgrove** [comment]
Same issue, npm log attached
[npm-debug.txt](https://github.com/npm/npm/files/480480/npm-debug.txt)

```
npm ERR! notsup Not compatible with your operating system or architecture: inotify@1.4.1
npm ERR! notsup Valid OS:    linux
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   darwin
npm ERR! notsup Actual Arch: x64
```

**Comment by legodude17** [comment]
This isn't really an issue with `npm`, `inotify` just claims it doesn't work on your os.

**Comment by vitormalencar** [comment]
any update with this one ?

**Comment by legodude17** [comment]
As I said, the problem is that `inotify` doesn't work on the OS you are using.
