### ISSUE TITLE
Windows: NPM not executing some commands (-c not working)

### ISSUE THREAD

**Issue by tw3080** [npm/npm#13328]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [ ] npm is producing an incorrect install.
- [x] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
#### What's going wrong?

I'm trying to use Chokidar with NPM. It seems like NPM doesn't understand that I want to execute a command after Chokidar detects changes. Here's an example of a repo I've tried (which DOES work on my mac): 

https://github.com/tw3080/Taylor

Here's part of the scripts section of the package.json file in that repo:
`"build": "npm run build:css",`
 `"watch": "npm run watch:css",`
 `"build:css": "npm run clean:css && lessc --source-map less/style.less css/style.css",`
 `"watch:css": "npm run build:css && chokidar less/style.less -c 'npm run build:css'",`
 `"clean:css": "rm -f css/style.css css/style.css.map"`

On mac, when I run 'watch' everything works fine, and changes are detected and 'npm run build:css' is executed afterwards, and changes are made to my files. On Windows, however, here's what I see after I run 'watch':

![image](https://cloud.githubusercontent.com/assets/18711238/16700162/4d3fe742-450d-11e6-8387-fdbf852dde20.png)

So, for some reason, on Windows, Chokidar is also trying to watch "run" and "build:css" (which are just part of the next command), in addition to "less/style.less" (the only file I want it to watch). Changes are detected when I edit the .less file, but then I get a message when it tries to move forward and run 'build:css', telling me to issue a command. It seems to me, then, that NPM is getting confused by my command or something? On my mac, it only watches "less/style.less" and executes "npm run build:css" afterwards accordingly.

`"watch:css": "npm run build:css && chokidar less/style.less -c 'npm run build:css'"`
Is there something wrong with my syntax here? I don't understand why the same files work fine on mac, but not on Windows. I'm running the same version of node and npm on both computers. I also tried just straight up re-installing node/npm and making sure they're up-to-date, which did nothing. Can anyone help?

I'm pretty sure this is an issue with NPM and NOT Chokidar, so that's why I'm posting it here. Also, I'm super new to using node/npm/chokidar, so I'm sorry if my question is poorly worded or I seem clueless. Thanks!
#### How can the CLI team reproduce the problem?

Not sure if this can be reproduced, as it could be an issue with my computer rather than Windows itself. But anyways, clone this repo: https://github.com/tw3080/Taylor and try to run 'watch' on Windows. Chokidar should be watching for changes now. Make some changes to style.less and save them. Chokidar will notice the changes, but then, on my computer, I get a message telling me to issue a command, which seems like it's saying npm doesn't know what to do with `-c 'npm run build:css'`.
### supporting information:
- `npm -v` prints: 3.10.5
- `node -v` prints: 4.4.7
- `npm config get registry` prints: https://registry.npmjs.org/
- Windows, OS X, or Linux?: Windows 10
- Network issues:
  - Geographic location where npm was run:
  - [ ] I use a proxy to connect to the npm registry.
  - [ ] I use a proxy to connect to the web.
  - [ ] I use a proxy when downloading Git repos.
  - [ ] I access the npm registry via a VPN
  - [ ] I don't use a proxy, but have limited or unreliable internet access.
- Container:
  - [ ] I develop using Vagrant on Windows.
  - [ ] I develop using Vagrant on OS X or Linux.
  - [ ] I develop / deploy using Docker.
  - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by jeancarlozapata** [comment]
Hey @tw3080 I experienced the same problem today (and found your issue through Google). Try changing your ```watch:css``` task from this:
```
"watch:css": "npm run build:css && chokidar less/style.less -c 'npm run build:css'"
```

to this:
```
"watch:css": "npm run build:css && chokidar less/style.less -c \"npm run build:css\""
```
Looks like using ```"``` instead of ```'``` in the task definition is making the difference (at least for me, it is now working). Looks like a Windows related problem, because with Linux, with single quotes it worked fine

**Comment by legodude17** [comment]
Guessing it is a thing with windows not liking the single quotes. Does @jeancarlozapata's solution work @tw3080?

**Comment by tw3080** [comment]
Hey, @jeancarlozapata, you're right! I actually discovered this solution a few weeks ago, but I had completely forgotten this issue was still open. Thanks for the response/reminder, though :) It definitely seems like it's a Windows issue, but at least there's a work-around. I'll close the issue.
