### ISSUE TITLE
init error

### ISSUE THREAD

**Issue by strongant** [npm/npm#13329]
npm ERR! Linux 4.4.0-28-generic
npm ERR! argv "/opt/node/bin/node" "/opt/node/bin/npm" "install"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5

npm ERR! shasum check failed for /tmp/npm-25606-398ae04c/registry.npmjs.org/cliff/-/cliff-0.1.9.tgz
npm ERR! Expected: a211e09c6a3de3ba1af27d049d301250d18812bc
npm ERR! Actual:   0c7e0c43d548bda41724f40014dcf74816938c3e
npm ERR! From:     https://registry.npmjs.org/cliff/-/cliff-0.1.9.tgz
npm ERR!

**Comment by KenanY** [comment]
@strongant Have you tried running `npm cache clean`?

**Comment by Raki22** [comment]
@KenanY  I did...still have the same error

**Comment by KenanY** [comment]
Closing as abandoned.
