### ISSUE TITLE
Targeting dependency repos with no package.json

### ISSUE THREAD

**Issue by brettz9** [npm/npm#13321]
#### What's the feature?

As also raised on #11032, it would be convenient to be able to add `dependencies` or `devDependencies` (by URL) without a `package.json`. The ability to import just a specific folder out of that repo would be icing on the cake.

If it is desired to continue insisting by default on the presence of a `package.json` file, a prefix to the URL or some such could be used to indicate that the `package.json` file checking should be avoided.

#### What problem is the feature intended to solve?

I have encountered repositories, particularly those which may contain standards specs or tests, which are hesitant to commit themselves to a particular package manager like `npm`, but which can be important to be utilized by one's repository without the added complexity and challenges with using git submodules.

To give a couple of examples, I have wanted to:

* import JSON Schema's spec for a JSON-Schema-aware GUI editor application to introspect the schema files published with the spec to allow GUI creation of JSON Schema itself.
* import W3C's web-platform-tests into IndexedDBShim and adapt its files can be monkey-patched so that its IndexedDB tests can be run against our shim (whether for the Node-SQLite or browser-WebSQL version).

#### Is the absence of this feature blocking you or your team? If so, how?

Yes. The other options are less than desirable.

The web standard tests in particular fluctuate too frequently to just commit them into our repo, not to mention the file size being too large for them to be added for all users. (It is for this reason also that it would be convenient to just target a particular subfolder, but if not, it would at least be nice to relegate the loading of the entire test repo to users loading from `devDependencies`.)

Git submodules could work, but it adds some complexity for contributors.

#### Is this feature similar to an existing feature in another tool?

Bower and no doubt other package managers can work with the absence of meta-data files.

#### Is this a feature you're prepared to implement, with support from the npm CLI team?

Sorry, no.

**Comment by othiym23** [comment]
The basic requirement for a package is having a package control file, which in npm's case is a `package.json` file located in the root package directory. This is a core requirement that is closely tied to npm's design, and isn't likely to change for the foreseeable future. As such, I'm going to close this feature request. Thanks for the considered request and the thorough explanation of the use case!

**Comment by brettz9** [comment]
Ok, thanks for the consideration!
