### ISSUE TITLE
Installing a package touches other dependencies

### ISSUE THREAD

**Issue by GRiMe2D** [npm/npm#13324]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [x] npm is producing an incorrect install.
- [x] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
#### What's going wrong?

I want to install a package called `nedb`. But npm touches all dependencies and somehow "extracts" them, however, they're already installed. And at some point, npm hangs. 

`package.json`

```
{
  "name": "xxxxxxxxxx-client-app",
  "version": "1.0.1",
  "author": "Shakhzod Ikromov (GRiMe2D) <aabbcc.double@gmail.com>",
  "devDependencies": {
    "another-rest-client": "^0.3.2",
    "babel-core": "^6.10.4",
    "babel-loader": "^6.2.4",
    "babel-preset-es2015": "^6.9.0",
    "babel-preset-react": "^6.11.1",
    "browser-bunyan": "^0.2.3",
    "chart.js": "^2.1.6",
    "del": "^2.2.1",
    "gulp": "^3.9.1",
    "jquery": "^3.0.0",
    "material-design-icons": "^2.2.3",
    "materialize-css": "^0.97.6",
    "promise": "^7.1.1",
    "react": "^15.2.0",
    "react-dom": "^15.2.0",
    "webpack": "^1.13.1",
    "webpack-stream": "^3.2.0",
    "xlsx": "^0.8.0"
  },
  "scripts": {
    "deploy": "gulp clean && gulp"
  }
}

```
#### How can the CLI team reproduce the problem?

https://gist.github.com/GRIM2D/b85a2931598098626281f4b66235cc5d

### supporting information:
- `npm -v` prints: 3.9.5
- `node -v` prints:v6.2.2
- `npm config get registry` prints: https://registry.npmjs.org/
- Windows, OS X, or Linux?: OSX 10.11.4
- Network issues:
  - Geographic location where npm was run:
  - [ ] I use a proxy to connect to the npm registry.
  - [ ] I use a proxy to connect to the web.
  - [ ] I use a proxy when downloading Git repos.
  - [ ] I access the npm registry via a VPN
  - [ ] I don't use a proxy, but have limited or unreliable internet access.
- Container:
  - [ ] I develop using Vagrant on Windows.
  - [ ] I develop using Vagrant on OS X or Linux.
  - [ ] I develop / deploy using Docker.
  - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by GRIM2D** [comment]
`npm install --save promise` will produce same result. I think it's npm issue not package

**Comment by GRIM2D** [comment]
Updating npm to latest stable (`3.10.6`) resolved the issue
