### ISSUE TITLE
err installing @google/cloud-debug

### ISSUE THREAD

**Issue by roych28** [npm/npm#13334]
#### I'm opening this issue because:

  - [ ] npm is producing an error.

#### What's going wrong?

I did -  npm install --save @google/cloud-debug
I get this log on : 

npm WARN package.json fruitful-backend@1.0.0 No repository field.
npm WARN package.json fruitful-backend@1.0.0 No README data
npm ERR! git clone git@github.com:google/cloud-debug Cloning into bare repository '/Users/roychemo/.npm/_git-remotes/git-github-com-google-cloud-debug-602fb14e'...
npm ERR! git clone git@github.com:google/cloud-debug ERROR: Repository not found.
npm ERR! git clone git@github.com:google/cloud-debug fatal: Could not read from remote repository.
npm ERR! git clone git@github.com:google/cloud-debug
npm ERR! git clone git@github.com:google/cloud-debug Please make sure you have the correct access rights
npm ERR! git clone git@github.com:google/cloud-debug and the repository exists.
npm ERR! addLocal Could not install google/cloud-debug
npm ERR! Error: ENOENT, stat 'google/cloud-debug'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 15.3.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "--save" "@google/cloud-debug"
npm ERR! cwd /Users/roychemo/projects/fruitfulway_2.0/fruitful-backend
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! path google/cloud-debug
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR!
npm ERR! Additional logging details can be found in: 

#### How can the CLI team reproduce the problem?

try install this on mac. using app engine flex for node.js 

if any more info needed let me know :) 

### supporting information:

 - `npm -v` prints: 1.4.28
 - `node -v` prints: v0.10.36
 - `npm config get registry` prints: https://registry.npmjs.org/
 - OS X
 - Container:
   - [ ] I develop using node/npm tools on OS X.

**Comment by KenanY** [comment]
@roych28 Please try updating to `npm@2` or `npm@3`. You are trying to install a scoped package, which is only supported in `npm@>=2`.

**Comment by KenanY** [comment]
Closing as abandoned.
