### ISSUE TITLE
babel-core

### ISSUE THREAD

**Issue by roger922222** [npm/npm#13331]
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "babel-core"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5

npm ERR! shasum check failed for /var/folders/yz/nhcqtnsx6xsd9bn46fdfrcfw0000gn/T/npm-1039-ac311cc0/registry.cnpmjs.org/concat-map/download/concat-map-0.0.1.tgz
npm ERR! Expected: d8a96bd77fd68df7793a73036a3ba0d5405d477b
npm ERR! Actual:   ca7699df4f97d6200aa2f5918c3c938cdb038d7c
npm ERR! From:     http://registry.cnpmjs.org/concat-map/download/concat-map-0.0.1.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Applications/D2/react-redux/npm-debug.log

**Comment by KenanY** [comment]
@roger922222 Have you tried running `npm cache clean`?

**Comment by KenanY** [comment]
Closing after a week with no response.
