### ISSUE TITLE
feature request: option to ignore invalid peer dependencies or treat it only as a warning

### ISSUE THREAD

**Issue by jonathanong** [npm/npm#13335]
#### What's going wrong?

many times, peer dependencies will be out of date, even though the build will work fine without having the absolutely correct version of the peers. sometimes, the peers aren't even necessary.

right now, this is blocking me from upgrading certain modules. `npm install` works, but `npm shrinkwrap` does not as "peer" is an error.
#### How can the CLI team reproduce the problem?

install eslint-config-standard and friends w/ eslint@3
#### What's the feature?

make invalid peers a warning, not an error. this could be an option.
#### What problem is the feature intended to solve?

when invalid peers are not actually invalid.
#### Is the absence of this feature blocking you or your team? If so, how?

yes, i can't update eslint@3 if i use standard configurations because the maintainers have not updated the peer dependencies for the modules
#### Is this feature similar to an existing feature in another tool?

no idea
#### Is this a feature you're prepared to implement, with support from the npm CLI team?

sure

**Comment by cburgmer** [comment]
Similar to #12909 ?

**Comment by mhgamework** [comment]
I have found at least 5 different instance of this problem all closed with the same message that it has "timed out". Can someone please take a proper look at this instead of just closing the ticket all the time?
