### ISSUE TITLE
"npm start" gives errors and stops

### ISSUE THREAD

**Issue by rahulrdb18** [npm/npm#13332]
#### I'm opening this issue because:

When I try to run my simple Angular2 app, using npm start it gives lots of err!.

Error is the console:

> angular2-app@1.0.0 start /home/thebali/brackets-code/angular-app-1
> tsc && concurrently "npm run tsc:w" "npm run lite" 
> 
> error TS5033: Could not write file 'app/app.component.js': EACCES: permission denied, open 'app/app.component.js'
> error TS5033: Could not write file 'app/app.component.js.map': EACCES: permission denied, open 'app/app.component.js.map'
> error TS5033: Could not write file 'app/main.js': EACCES: permission denied, open 'app/main.js'
> error TS5033: Could not write file 'app/main.js.map': EACCES: permission denied, open 'app/main.js.map'
> 
> npm ERR! Linux 3.16.0-4-amd64
> npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
> npm ERR! node v4.4.7
> npm ERR! npm  v3.10.5
> npm ERR! code ELIFECYCLE
> npm ERR! angular2-app@1.0.0 start: `tsc && concurrently "npm run tsc:w" "npm run lite" `
> npm ERR! Exit status 2
> npm ERR! 
> npm ERR! Failed at the angular2-app@1.0.0 start script 'tsc && concurrently "npm run tsc:w" "npm run lite" '.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the angular2-app package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     tsc && concurrently "npm run tsc:w" "npm run lite" 
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs angular2-app
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls angular2-app
> npm ERR! There is likely additional logging output above.
> 

npm-debug.log

> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
> 2 info using npm@3.10.5
> 3 info using node@v4.4.7
> 4 verbose run-script [ 'prestart', 'start', 'poststart' ]
> 5 info lifecycle angular2-app@1.0.0~prestart: angular2-app@1.0.0
> 6 silly lifecycle angular2-app@1.0.0~prestart: no script for prestart, continuing
> 7 info lifecycle angular2-app@1.0.0~start: angular2-app@1.0.0
> 8 verbose lifecycle angular2-app@1.0.0~start: unsafe-perm in lifecycle true
> 9 verbose lifecycle angular2-app@1.0.0~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/thebali/brackets-code/angular-app-1/node_modules/.bin:/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/opt/lampp
> 10 verbose lifecycle angular2-app@1.0.0~start: CWD: /home/thebali/brackets-code/angular-app-1
> 11 silly lifecycle angular2-app@1.0.0~start: Args: [ '-c', 'tsc && concurrently "npm run tsc:w" "npm run lite" ' ]
> 12 silly lifecycle angular2-app@1.0.0~start: Returned: code: 2  signal: null
> 13 info lifecycle angular2-app@1.0.0~start: Failed to exec start script
> 14 verbose stack Error: angular2-app@1.0.0 start: `tsc && concurrently "npm run tsc:w" "npm run lite" `
> 14 verbose stack Exit status 2
> 14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
> 14 verbose stack     at emitTwo (events.js:87:13)
> 14 verbose stack     at EventEmitter.emit (events.js:172:7)
> 14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
> 14 verbose stack     at emitTwo (events.js:87:13)
> 14 verbose stack     at ChildProcess.emit (events.js:172:7)
> 14 verbose stack     at maybeClose (internal/child_process.js:827:16)
> 14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
> 15 verbose pkgid angular2-app@1.0.0
> 16 verbose cwd /home/thebali/brackets-code/angular-app-1
> 17 error Linux 3.16.0-4-amd64
> 18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
> 19 error node v4.4.7
> 20 error npm  v3.10.5
> 21 error code ELIFECYCLE
> 22 error angular2-app@1.0.0 start: `tsc && concurrently "npm run tsc:w" "npm run lite" `
> 22 error Exit status 2
> 23 error Failed at the angular2-app@1.0.0 start script 'tsc && concurrently "npm run tsc:w" "npm run lite" '.
> 23 error Make sure you have the latest version of node.js and npm installed.
> 23 error If you do, this is most likely a problem with the angular2-app package,
> 23 error not with npm itself.
> 23 error Tell the author that this fails on your system:
> 23 error     tsc && concurrently "npm run tsc:w" "npm run lite"
> 23 error You can get information on how to open an issue for this project with:
> 23 error     npm bugs angular2-app
> 23 error Or if that isn't available, you can get their info via:
> 23 error     npm owner ls angular2-app
> 23 error There is likely additional logging output above.
> 24 verbose exit [ 1, true ]

But, when I run "npm run lite". it works fine and opens the app in the browser.

**Comment by KenanY** [comment]
Looks like a permissions issue, not an `npm` issue. You don't have permission to write to some files in `app/` (as the log indicates). I would make sure you have permission to modify that directory.

**Comment by rahulrdb18** [comment]
yes, that was it. I am closing this issue. Thanks.
