### ISSUE TITLE
NPM Shasum check fails on random packages

### ISSUE THREAD

**Issue by prog-rajkamal** [npm/npm#13346]
#### I'm opening this issue because:

  - [x] npm is crashing.

#### What's going wrong?
I run `npm install webpack-dev-server` (or any other project)
and I get following error

```
npm ERR! shasum check failed for C:\Users\RAJ~1.KAM\AppData\Local\Temp\npm-9064-407adaa8\registry.npmjs.org\mime-db\-\mime-db-1.23.0.tgz
npm ERR! Expected: a31b4070adaea27d732ea333740a64d0ec9a6659
npm ERR! Actual:   69372d02135d63ebc0effbfebbf3f50179248211
npm ERR! From:     https://registry.npmjs.org/mime-db/-/mime-db-1.23.0.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

I have tried it multiple times. And tried the hacks mentioned in #7991 and #2701 .

But it always fails, the package, whose shasum check fails, is different every time but the end result is the same.

 
#### How can the CLI team reproduce the problem?

 run `npm install webpack-dev-server` (or any popular project with lots of dependency)

### supporting information:

 - `npm -v` prints: 3.8.3
 - `node -v` prints: 5.10.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X, or Linux?: Windows 64bit
 - Network issues:
   - Geographic location where npm was run: Noida, India
   - [x] I use a proxy to connect to the web.
 - Container:
 No Container

**Comment by prog-rajkamal** [comment]
I am closing this issue as I have found a workaround and there are already many open issues related to this problem.

**Comment by Puneeth-n** [comment]
@prog-rajkamal what was the workaround?

**Comment by prog-rajkamal** [comment]
I changed npm registry to http://registry.cnpmjs.org/ . 

You can use it via the registry option while `npm install` or set it in a `.npmrc` file to avoid typing it again and again.
