### ISSUE TITLE
Run arbitrary command outside of scripts object

### ISSUE THREAD

**Issue by MadLittleMods** [npm/npm#13343]
Use `npm run` to execute an arbitrary command without having to add it to the `scripts` object in `package.json`.

 - `npm run "echo $npm_package_version"`
 - `npm run "gulp some-new-task"`

Because `npm run` sets up a [special environment where packages are added to the path](https://docs.npmjs.com/misc/scripts#environment), etc, this allows for easy execution of a one-off command without having to install the packages globally or pop it in the `package.json` temporarily.

**Comment by othiym23** [comment]
Closing as duplicate of #6053.
