### ISSUE TITLE
npm install --save --save-exact react-native` failed

### ISSUE THREAD

**Issue by Jerry1989d** [npm/npm#13345]
tanjifengdeMacBook-Pro:AwesomeProject tanjifeng$ react-native init HelloWorld
This will walk you through creating a new React Native project in /Users/tanjifeng/AwesomeProject/AwesomeProject/HelloWorld
Installing react-native package from npm...

> utf-8-validate@1.2.1 install /Users/tanjifeng/AwesomeProject/AwesomeProject/HelloWorld/node_modules/react-native/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node

> bufferutil@1.2.1 install /Users/tanjifeng/AwesomeProject/AwesomeProject/HelloWorld/node_modules/react-native/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node

> spawn-sync@1.0.15 postinstall /Users/tanjifeng/AwesomeProject/AwesomeProject/HelloWorld/node_modules/react-native/node_modules/yeoman-generator/node_modules/cross-spawn/node_modules/spawn-sync
> node postinstall

> spawn-sync@1.0.15 postinstall /Users/tanjifeng/AwesomeProject/AwesomeProject/HelloWorld/node_modules/react-native/node_modules/yeoman-environment/node_modules/inquirer/node_modules/external-editor/node_modules/spawn-sync
> node postinstall

npm WARN peerDependencies The peer dependency react@~15.2.0 included from react-native will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "--save-exact" "react-native"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! path /Users/tanjifeng/.npm/convert-source-map/1.2.0
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall mkdir

npm ERR! Error: EACCES: permission denied, mkdir '/Users/tanjifeng/.npm/convert-source-map/1.2.0'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, mkdir '/Users/tanjifeng/.npm/convert-source-map/1.2.0']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/Users/tanjifeng/.npm/convert-source-map/1.2.0',
npm ERR!   parent: 'babel-core' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/tanjifeng/AwesomeProject/AwesomeProject/HelloWorld/npm-debug.log

`npm install --save --save-exact react-native` failed

I dont know whats wrong ,, i already did using "sudo chown -R `whoami` /usr/local". but still the same .

**Comment by happy2share** [comment]
I don't which steps worked for me. But these are my steps to get rid of this error:

1) Updated Node.js
2) Ran **_reactive-native init  <project-name>_** command prompt as Administrator (on Windows OS), hoping works well with sudo **_reactive-native init  <project-name>_** on Mac OS

**Comment by Jerry1989d** [comment]
thank you， this issue has been resolved。。

**Comment by KenanY** [comment]
Closing as resolved then.
