### ISSUE TITLE
Facing Git issues while running npm install

### ISSUE THREAD

**Issue by RishiChitransh** [npm/npm#13348]
I am Opening the issue for the following:

While running npm install in one of my projects, I am facing the following issue:

**npm ERR! git clone --template=/Users/E066327/.npm/_git-remotes/_templates --mirror git://github.com/bessdsv/bower-installer.git /Users/E066327/.npm/_git-remotes/git-github-com-bessdsv-bower-installer-git-8c0433f6: Cloning into bare repository '/Users/E066327/.npm/_git-remotes/git-github-com-bessdsv-bower-installer-git-8c0433f6'...
npm ERR! git clone --template=/Users/E066327/.npm/_git-remotes/_templates --mirror git://github.com/bessdsv/bower-installer.git /Users/E066327/.npm/_git-remotes/git-github-com-bessdsv-bower-installer-git-8c0433f6: fatal: unable to connect to github.com:
npm ERR! git clone --template=/Users/E066327/.npm/_git-remotes/_templates --mirror git://github.com/bessdsv/bower-installer.git /Users/E066327/.npm/_git-remotes/git-github-com-bessdsv-bower-installer-git-8c0433f6: github.com[0: 192.30.253.112]: errno=Operation timed out
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.1
npm ERR! code 128

npm ERR! Command failed: git clone --template=/Users/E066327/.npm/_git-remotes/_templates --mirror git://github.com/bessdsv/bower-installer.git /Users/E066327/.npm/_git-remotes/git-github-com-bessdsv-bower-installer-git-8c0433f6
npm ERR! Cloning into bare repository '/Users/E066327/.npm/_git-remotes/git-github-com-bessdsv-bower-installer-git-8c0433f6'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.253.112]: errno=Operation timed out
npm ERR! 
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/E066327/Desktop/Projects/webapp-stores-backoffice/npm-debug.log**

Having searched through forums, tried the following too:

**git config --global  url."https://".insteadOf git://**

(Replaced "--global" with "--local" so as to not disturb global settings). This didn't help either.

Attached is the log file
[npm-debug copy.txt](https://github.com/npm/npm/files/359256/npm-debug.copy.txt)

**Comment by busches** [comment]
@RishiChitransh are you behind a proxy? Are you able to git clone the repo manually, not calling it through `npm`?
