### ISSUE TITLE
npm error Unable to get issuer cert locally

### ISSUE THREAD

**Issue by swassouf** [npm/npm#13340]
I am getting this error when I try to install gulp for example npm install --save-dev gulp-less

npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code UNABLE_TO_GET_ISSUER_CERT_LOCALLY

npm ERR! unable to get local issuer certificate

any idea how to pass proxy issue

**Comment by vkaranat** [comment]
Am getting the same error while trying to install gulp
**>npm install gulp --save-dev**

35 error node v4.4.7
36 error npm  v2.15.8
37 error code UNABLE_TO_GET_ISSUER_CERT_LOCALLY
38 error unable to get local issuer certificate

has there been any resolution on this one yet ?

**Comment by vkaranat** [comment]
Found a work around for it:

npm config set strict-ssl=false // set firewall to false
npm install gulp --save-dev  // install gulp
npm config set strict-ssl=true // set firewall to true again
