### ISSUE TITLE
trailing "undefined" after "npm outdated --global gulp"

### ISSUE THREAD

**Issue by JulienPalard** [npm/npm#13364]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I'm getting the string "undefined" on the last line of a "npm outdated".

#### How can the CLI team reproduce the problem?

I'm not sure, but on my end it's easy:

# /usr/bin/npm outdated --global gulp
Package  Current  Wanted  Latest  Location                      
gulp    3.9.0            3.9.1  3.9.1  /usr/local/lib > gulp        
gulp    3.8.8            3.8.8  3.9.1  /usr/local/lib > ionic > gulp
undefined

### supporting information:

 - `npm -v` prints: 1.4.21
 - `node -v` prints: v4.3.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X, or Linux?: Linux, Debian Jesssie with npm and node from testing.
 - Network issues:
   - Geographic location where npm was run: Paris, France.
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@JulienPalard Does this also occur with `npm@2` or `npm@3`?

**Comment by JulienPalard** [comment]
It does not happen using `npm@3`.

But using ansible, as `ansible` calls `npm outdated` before upgrading `npm` and `npm outdated` is failing, I can't write an ansible playbook to get npm@3, so I can't use ansible playbook to install ansible packages on a Debian distrib.

**Comment by othiym23** [comment]
You should add `npm -g install npm@latest` to your Ansible role (and, if it's always going to be run on Debian, `apt-get install nodejs-legacy`). `npm@1` is no longer supported by the CLI team and will receive no further updates or releases, so your alternatives are either to install a newer version of npm or file a bug against the Debian package of npm. (One thing to check, though — the standard bundling of Node.js LTS includes `npm@2`, and 4.3.1 should include a fairly recent one – ensure you don't have two versions of npm installed to different paths. In particular, if you're using the Node|Source Distribution, you don't need to install the dpkg of npm separately.)

As this is an issue with an unsupported version of npm, and I've provided a workaround, I'm going to close this issue as resolved.

**Comment by JulienPalard** [comment]
If npm@1 is no longer supported (too old), why is it the only version packaged for Debian `sid` ?

**Comment by othiym23** [comment]
That's a question for the downstream packagers on the Debian JavaScript team. There's no relationship between the npm CLI team and any of the distribution packagers who bundle it. `npm@1.4.21` is well over two years old. This is one of many reasons why I discourage developers from using distro-packaged Node & npm in favor of something like the Node|Source Node.js Distribution, which includes packages for Debian, Ubuntu, Fedora, and CentOS / RHEL.

**Comment by JulienPalard** [comment]
Your're spending energy discouraging developers from using distro-packages things? But...

**Comment by othiym23** [comment]
If it leads to an inferior experience for our users, of a version of the product that the upstream maintainers no longer support because it's been superseded by not one, but two major releases (including a tremendous number of significant stability improvements and fixes for race conditions)? Yes, we will absolutely discourage people from using those packages, until and unless those faults are remedied. I don't believe the Debian packages for Node.js or npm are fit for use with anything other than Debian-packaged Node applications, and I certainly wouldn't recommend them for operational use in a production environment of user-developed applications.

**Comment by charlienewey** [comment]
I am also affected by this bug (in the same situation) - cannot figure out what's causing it as I am a relative newbie with node. This happens with npm@3.5.2 as shown by the following:

```bash
root@erebor:/var/www/ghost# npm --version
3.5.2
root@erebor:/var/www/ghost# npm outdated
Package  Current  Wanted   Latest          Location
ghost   0.11.0           0.11.0  1.0.0-alpha.1         
undefined
```
