### ISSUE TITLE
Not install on windows 10

### ISSUE THREAD

**Issue by jackryu** [npm/npm#13361]
**Hi Team - I am try to install CADOVA in my windows 10 but I am facing below mention  issue please suggest.**

C:\Users\iMac>npm install -g cordova
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8

npm ERR! shasum check failed for C:\Users\iMac\AppData\Local\Temp\npm-8988-1ca2e6f1\registry.npmjs.org\cordova-app-hello-world\-\cordova-app-hello-world-3.10.0.tgz
npm ERR! Expected: e3825fc6ca950090a6a37437fcfb88c1622fd80e
npm ERR! Actual:   05020ccc4a3acff3b367ca2eefa15ad0ac92297e
npm ERR! From:     https://registry.npmjs.org/cordova-app-hello-world/-/cordova-app-hello-world-3.10.0.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by KenanY** [comment]
@jackryu Have you tried running `npm cache clean`?

**Comment by KenanY** [comment]
Closing due to no response.
