### ISSUE TITLE
unable to install new package

### ISSUE THREAD

**Issue by kul1010** [npm/npm#13366]
0 info it worked if it ends with ok
1 verbose cli [ 'D:\nodejs\node.exe',
1 verbose cli   'D:\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@2.15.8
3 info using node@v4.4.7
4 verbose readDependencies loading dependencies from D:\node\nodecrud-master\package.json
5 verbose install where, deps [ 'D:\node\nodecrud-master',
5 verbose install   [ 'ejs', 'express', 'express-myconnection', 'jade', 'mysql' ] ]
6 verbose install where, peers [ 'D:\node\nodecrud-master', [] ]
7 verbose installManyTop reading for lifecycle D:\node\nodecrud-master\package.json
8 info preinstall application-name@0.0.1
9 verbose readDependencies loading dependencies from D:\node\nodecrud-master\package.json
10 silly cache add args [ 'express@3.5.1', null ]
11 verbose cache add spec express@3.5.1
12 silly cache add parsed spec Result {
12 silly cache add   raw: 'express@3.5.1',
12 silly cache add   scope: null,
12 silly cache add   name: 'express',
12 silly cache add   rawSpec: '3.5.1',
12 silly cache add   spec: '3.5.1',
12 silly cache add   type: 'version' }
13 silly addNamed express@3.5.1
14 verbose addNamed "3.5.1" is a plain semver version for express
15 silly mapToRegistry name express
16 silly mapToRegistry using default registry
17 silly mapToRegistry registry https://registry.npmjs.org/
18 silly mapToRegistry data Result {
18 silly mapToRegistry   raw: 'express',
18 silly mapToRegistry   scope: null,
18 silly mapToRegistry   name: 'express',
18 silly mapToRegistry   rawSpec: '',
18 silly mapToRegistry   spec: 'latest',
18 silly mapToRegistry   type: 'tag' }
19 silly mapToRegistry uri https://registry.npmjs.org/express
20 verbose addNameVersion registry:https://registry.npmjs.org/express not in flight; fetching
21 silly cache add args [ 'express-myconnection@1.0.4', null ]
22 verbose cache add spec express-myconnection@1.0.4
23 silly cache add parsed spec Result {
23 silly cache add   raw: 'express-myconnection@1.0.4',
23 silly cache add   scope: null,
23 silly cache add   name: 'express-myconnection',
23 silly cache add   rawSpec: '1.0.4',
23 silly cache add   spec: '1.0.4',
23 silly cache add   type: 'version' }
24 silly addNamed express-myconnection@1.0.4
25 verbose addNamed "1.0.4" is a plain semver version for express-myconnection
26 silly mapToRegistry name express-myconnection
27 silly mapToRegistry using default registry
28 silly mapToRegistry registry https://registry.npmjs.org/
29 silly mapToRegistry data Result {
29 silly mapToRegistry   raw: 'express-myconnection',
29 silly mapToRegistry   scope: null,
29 silly mapToRegistry   name: 'express-myconnection',
29 silly mapToRegistry   rawSpec: '',
29 silly mapToRegistry   spec: 'latest',
29 silly mapToRegistry   type: 'tag' }
30 silly mapToRegistry uri https://registry.npmjs.org/express-myconnection
31 verbose addNameVersion registry:https://registry.npmjs.org/express-myconnection not in flight; fetching
32 silly cache add args [ 'jade@_', null ]
33 verbose cache add spec jade@_
34 silly cache add parsed spec Result {
34 silly cache add   raw: 'jade@_',
34 silly cache add   scope: null,
34 silly cache add   name: 'jade',
34 silly cache add   rawSpec: '_',
34 silly cache add   spec: '_',
34 silly cache add   type: 'range' }
35 silly addNamed jade@_
36 verbose addNamed "_" is a valid semver range for jade
37 silly addNameRange { name: 'jade', range: '_', hasData: false }
38 silly mapToRegistry name jade
39 silly mapToRegistry using default registry
40 silly mapToRegistry registry https://registry.npmjs.org/
41 silly mapToRegistry data Result {
41 silly mapToRegistry   raw: 'jade',
41 silly mapToRegistry   scope: null,
41 silly mapToRegistry   name: 'jade',
41 silly mapToRegistry   rawSpec: '',
41 silly mapToRegistry   spec: 'latest',
41 silly mapToRegistry   type: 'tag' }
42 silly mapToRegistry uri https://registry.npmjs.org/jade
43 verbose addNameRange registry:https://registry.npmjs.org/jade not in flight; fetching
44 silly cache add args [ 'mysql@2.2.0', null ]
45 verbose cache add spec mysql@2.2.0
46 silly cache add parsed spec Result {
46 silly cache add   raw: 'mysql@2.2.0',
46 silly cache add   scope: null,
46 silly cache add   name: 'mysql',
46 silly cache add   rawSpec: '2.2.0',
46 silly cache add   spec: '2.2.0',
46 silly cache add   type: 'version' }
47 silly addNamed mysql@2.2.0
48 verbose addNamed "2.2.0" is a plain semver version for mysql
49 silly mapToRegistry name mysql
50 silly mapToRegistry using default registry
51 silly mapToRegistry registry https://registry.npmjs.org/
52 silly mapToRegistry data Result {
52 silly mapToRegistry   raw: 'mysql',
52 silly mapToRegistry   scope: null,
52 silly mapToRegistry   name: 'mysql',
52 silly mapToRegistry   rawSpec: '',
52 silly mapToRegistry   spec: 'latest',
52 silly mapToRegistry   type: 'tag' }
53 silly mapToRegistry uri https://registry.npmjs.org/mysql
54 verbose addNameVersion registry:https://registry.npmjs.org/mysql not in flight; fetching
55 silly cache add args [ 'ejs@^1.0.0', null ]
56 verbose cache add spec ejs@^1.0.0
57 silly cache add parsed spec Result {
57 silly cache add   raw: 'ejs@^1.0.0',
57 silly cache add   scope: null,
57 silly cache add   name: 'ejs',
57 silly cache add   rawSpec: '^1.0.0',
57 silly cache add   spec: '>=1.0.0 <2.0.0',
57 silly cache add   type: 'range' }
58 silly addNamed ejs@>=1.0.0 <2.0.0
59 verbose addNamed ">=1.0.0 <2.0.0" is a valid semver range for ejs
60 silly addNameRange { name: 'ejs', range: '>=1.0.0 <2.0.0', hasData: false }
61 silly mapToRegistry name ejs
62 silly mapToRegistry using default registry
63 silly mapToRegistry registry https://registry.npmjs.org/
64 silly mapToRegistry data Result {
64 silly mapToRegistry   raw: 'ejs',
64 silly mapToRegistry   scope: null,
64 silly mapToRegistry   name: 'ejs',
64 silly mapToRegistry   rawSpec: '',
64 silly mapToRegistry   spec: 'latest',
64 silly mapToRegistry   type: 'tag' }
65 silly mapToRegistry uri https://registry.npmjs.org/ejs
66 verbose addNameRange registry:https://registry.npmjs.org/ejs not in flight; fetching
67 verbose request uri https://registry.npmjs.org/express
68 verbose request no auth needed
69 info attempt registry request try #1 at 4:07:26 PM
70 verbose request id f9ec6356321156d0
71 http request GET https://registry.npmjs.org/express
72 verbose request uri https://registry.npmjs.org/express-myconnection
73 verbose request no auth needed
74 info attempt registry request try #1 at 4:07:26 PM
75 http request GET https://registry.npmjs.org/express-myconnection
76 verbose request uri https://registry.npmjs.org/jade
77 verbose request no auth needed
78 info attempt registry request try #1 at 4:07:26 PM
79 http request GET https://registry.npmjs.org/jade
80 verbose request uri https://registry.npmjs.org/mysql
81 verbose request no auth needed
82 info attempt registry request try #1 at 4:07:26 PM
83 http request GET https://registry.npmjs.org/mysql
84 verbose request uri https://registry.npmjs.org/ejs
85 verbose request no auth needed
86 info attempt registry request try #1 at 4:07:26 PM
87 http request GET https://registry.npmjs.org/ejs
88 info retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.8.162:443
89 info retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.8.162:443
90 info retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.8.162:443
91 info retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.8.162:443
92 info retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.8.162:443
93 info attempt registry request try #2 at 4:07:57 PM
94 http request GET https://registry.npmjs.org/jade
95 info attempt registry request try #2 at 4:07:57 PM
96 http request GET https://registry.npmjs.org/mysql
97 info attempt registry request try #2 at 4:07:57 PM
98 http request GET https://registry.npmjs.org/ejs
99 info attempt registry request try #2 at 4:07:57 PM
100 http request GET https://registry.npmjs.org/express
101 info attempt registry request try #2 at 4:07:57 PM
102 http request GET https://registry.npmjs.org/express-myconnection
103 info retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.8.162:443
104 info retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.8.162:443
105 info retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.8.162:443
106 info retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.8.162:443
107 info retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.8.162:443
108 info attempt registry request try #3 at 4:09:18 PM
109 http request GET https://registry.npmjs.org/jade
110 info attempt registry request try #3 at 4:09:18 PM
111 http request GET https://registry.npmjs.org/express
112 info attempt registry request try #3 at 4:09:18 PM
113 http request GET https://registry.npmjs.org/mysql
114 info attempt registry request try #3 at 4:09:18 PM
115 http request GET https://registry.npmjs.org/express-myconnection
116 info attempt registry request try #3 at 4:09:18 PM
117 http request GET https://registry.npmjs.org/ejs
118 verbose stack Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
118 verbose stack     at Object.exports._errnoException (util.js:873:11)
118 verbose stack     at errnoException (dns.js:32:15)
118 verbose stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:78:26)
119 verbose cwd D:\node\nodecrud-master
120 error Windows_NT 6.1.7601
121 error argv "D:\\nodejs\\node.exe" "D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
122 error node v4.4.7
123 error npm  v2.15.8
124 error code EAI_AGAIN
125 error errno EAI_AGAIN
126 error syscall getaddrinfo
127 error getaddrinfo EAI_AGAIN registry.npmjs.org:443
128 error If you need help, you may report this error at:
128 error     <https://github.com/npm/npm/issues>
129 verbose exit [ 1, true ]

**Comment by jcperez-ch** [comment]
Since last week I see this as a constant... it's really slowing development, we might need to go old school to keep 3rd party dependencies since `npm` seems not reliable nowadays 😞

**Comment by kul1010** [comment]
I have resolved this issue. 
set proxy as below in command prompt or GIT bash

$ npm config set proxy=http://192.168.1.58:4128
$ npm config set https-proxy=http://192.168.1.58:4128

**Comment by anna93** [comment]
this won't work for others, as it is your local network specific

**Comment by kul1010** [comment]
@anna93 use IP/Port or other details according to your proxy settings.
