### ISSUE TITLE
npm install node-xlsx wrong

### ISSUE THREAD

**Issue by dualven** [npm/npm#13378]
#### I'm opening this issue because:

npm install node-xlsx wrong

#### What's going wrong?
113 error Linux 2.6.18-371.11.1.el5
114 error argv "/home/dualven/node/node-v6.2.0-linux-x64/bin/node" "/usr/local/bin/npm" "install" "node-xlsx"
115 error node v6.2.0
116 error npm  v3.8.9
117 error shasum check failed for /tmp/npm-31589-4a8e0e91/registry.npmjs.org/xlsx/-/xlsx-0.8.0.tgz
117 error Expected: 253ca61c9e1e14aa4b905dece4ce4757ace99d26
117 error Actual:   41b54de7fd58174a68ab3d3ef114a4ecb63bb633
117 error From:     https://registry.npmjs.org/xlsx/-/xlsx-0.8.0.tgz
118 error If you need help, you may report this error at:
118 error     <https://github.com/npm/npm/issues>
#### How can the CLI team reproduce the problem?

my linux is  Linux 2.6.18-371.11.1.el5  CentOS release 5.10 (Final)

**Comment by KenanY** [comment]
@dualven Have you tried running `npm cache clean`?

**Comment by KenanY** [comment]
Closing due to no response.
