### ISSUE TITLE
npm view versions now truncates list?!

### ISSUE THREAD

**Issue by rob3c** [npm/npm#13376]
Hi, when I run `npm view webpack versions`, npm 3.10.5 (with node 6.2.2 on Win 8) truncates the list at '0.8.0-beta2' and reports that there are "... 313 more items".

However, when I run the same command using npm 3.8.6 (with node 4.2.2), I can see the full list.

So this behavior was changed sometime between npm versions 3.8.6 and 3.10.5, and I can't find a changelog entry about it. I don't see anything in the docs about how to restore the full list without truncation.

Is this a bug or is it the new intended behavior? If it's intentional, how can I force it to show the whole list?

Thanks in advance,
Robert

**Comment by othiym23** [comment]
This is a change to the behavior of `util.inspect()` in newer versions of Node.js (I'm guessing – this isn't behavior that the npm CLI team changed). If you want to get the full list, and also want to ensure that it's parseable, just add `--json` to the command, to get the raw output of `JSON.stringify()` applied to that piece of the package's metadata. Thanks for your time!

**Comment by rob3c** [comment]
Thanks for the quick explanation! (and reminder - doh!)  I wasn't connecting the `versions` part of the command with just restricting `npm view` output to the `versions` key in the json metadata, even though I use it that way in other contexts like reading peerDependencies, scripts and such. Sheesh...anyway, `--json` it is :)
