### ISSUE TITLE
npm (6.3.0) hangs once starting running npm command (Windows 7 64)

### ISSUE THREAD

**Issue by borasik** [npm/npm#13374]
#### I'm opening this issue because:

  - [ ] npm hangs forever once hit enter on any npm command

#### How can the CLI team reproduce the problem?

1. Just installed nodejs
2. Run npm install (or just npm)
3. Command line hangs forever until stop operation with Ctrl + C 

* I Can't find any npm-debug.log file

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:

* Can't run any of above operation, once I hit ENTER, npm hangs and nothing happen.

 - Windows 7

* I'm trying to solve this problem for month or so.
* I'm blocked from working on my projects.
* I had re-installed npm dozens times, chech System Variables etc.

Thanks a lot!!

![capture](https://cloud.githubusercontent.com/assets/8793644/16817501/11250eba-4911-11e6-937d-5ff9302ba597.PNG)

Really need your help!!

**Comment by luanlucas** [comment]
I currently have the same problem, any help would be great.

Thanks in advance.

**Comment by luanlucas** [comment]
In my case, I had executed the command "npm config list" to change the prefix. When I did that, it created a new file called .npmrc at %USERPROFILE%, once I reinstalled Node.js and removed the .npmrc file, everything got back to work again.

**Comment by borasik** [comment]
I just removed the  .npmrc at %USERPROFILE% and everything is working fine! I waited 4 month to solve this problem!

Thanks a lot for you reply finally I can use NPM :-)

**Comment by luanlucas** [comment]
I'm glad I could help you to solve this problem!

**Comment by KenanY** [comment]
Closing as resolved.
