### ISSUE TITLE
npm init fails  

### ISSUE THREAD

**Issue by tjohnson4** [npm/npm#13377]
➜  foo system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: OS X 10.11.5 (15F34)
      Kernel Version: Darwin 15.5.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: clovis
      User Name: TODD JOHNSON (toddjohnson)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 9:39

➜  foo node -v
v4.4.7
➜  foo npm -v
2.15.8
➜  foo echo No VPN or Proxy
No VPN or Proxy
➜  foo ping npm.com
PING npm.com (104.16.82.143): 56 data bytes
64 bytes from 104.16.82.143: icmp_seq=0 ttl=57 time=12.389 ms
64 bytes from 104.16.82.143: icmp_seq=1 ttl=57 time=12.429 ms
64 bytes from 104.16.82.143: icmp_seq=2 ttl=57 time=30.530 ms
^C
--- npm.com ping statistics ---
3 packets transmitted, 3 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 12.389/18.449/30.530/8.542 ms
➜  foo npm init
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

See `npm help json` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg> --save` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "init"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'spdx'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
About to write to /Users/toddjohnson/foo/package.json:

{
  "name": "",
  "version": ""
}

Is this ok? (yes) Aborted.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/toddjohnson/foo/npm-debug.log
➜  foo echo No use of a container
No use of a container

**Comment by luvsin27** [comment]
Use npm install spdx --save afterwards to install a package and
save it as a dependency in the package.json file.

**Comment by tjohnson4** [comment]
@luvsin27 I am running npm init in a empty project directory. I should not have to have spdx installed in the project folder before running npm init.

**Comment by KenanY** [comment]
@tjohnson4 Seems like your `npm` installation is missing a dependency, have you tried reinstalling `npm`?

**Comment by tjohnson4** [comment]
I have tried the following : 

1. upgrading via the node installer
2. manually via npm 'npm install -g npm@latest' 
3. cleaning the cache 'npm cache clean'
4. reinstalling 'curl -L https://www.npmjs.org/install.sh | sh'

stdout : https://gist.github.com/tjohnson4/b09e01d9891842531b6b123f59ec470d

**Comment by tjohnson4** [comment]
Could it be the PATH is not being correctly set? Was there a path change from a previous version of the node / npm installer?

**Comment by tjohnson4** [comment]
I was able to fix the issue by downgrading with the node installer for 0.12.7 that included npm 2.11.3 and then upgrading with the latest LTS node installer. 

Solution found here from user @miksago : https://github.com/npm/npm/issues/10078

**Comment by KenanY** [comment]
Closing as resolved then.
