### ISSUE TITLE
I have facing an issue related to installing npm modules.

### ISSUE THREAD

**Issue by Muthu2020** [npm/npm#13379]
```
npm ERR! shasum check failed for /tmp/npm-4527-a7c81395/registry.npmjs.org/selenium-webdriver/-/selenium-webdriver-2.47.0.tgz
npm ERR! Expected: e29b52d2daa0f648c40f602f4d2a8e8bee351ea5
npm ERR! Actual:   a359188dac79bee7c655816b50c7d72d8e65e41e
npm ERR! From:     http://registry.npmjs.org/selenium-webdriver/-/selenium-webdriver-2.47.0.tgz
```

Version used:
node - 4.4.7
npm - 2.15.8

Could someone give me a little advice on this?

**Comment by KenanY** [comment]
@Muthu2020 Have you tried running `npm cache clean`?

**Comment by vinayakpatil** [comment]
+1

**Comment by vinayakpatil** [comment]
@KenanY I am still able to reproduce this after `npm cache clean`

Here are my logs

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.7

npm ERR! shasum check failed for C:\Users\VINAYA~1\AppData\Local\Temp\npm-2928-b77710dd\registry.npmjs.com\event-stream\-\event-stream-3.3.4.tgz
npm ERR! Expected: 4ab4c9a0f5a54db9338b4c34d86bfce8f4b35571
npm ERR! Actual:   ade6c87d1b350cf41d37d1de3e00b494849bbe3b
npm ERR! From:     https://registry.npmjs.com/event-stream/-/event-stream-3.3.4.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\360Admin\npm-debug.log

**Comment by KenanY** [comment]
Closing as abandoned.
