### ISSUE TITLE
npm install fails to install a dependency of a dependency

### ISSUE THREAD

**Issue by Mossop** [npm/npm#13373]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [x] npm is producing an incorrect install.
- [ ] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
#### What's going wrong?

`mv` depends on `rimraf@~2.4.0`. My module depends on `mv` and `rimraf@2.5.3`. `npm install` install `mv` and `rimraf` but doesn't install the lower version of `rimraf` inside of `mv`. For some reason this only happens with `bunyan` as a dependency.
#### How can the CLI team reproduce the problem?

1 Create a directory with this package.json: https://gist.github.com/Mossop/cf283fd1feaf71d4a498a37f014d1e68
2 Run `npm install`, get the following output: https://gist.github.com/Mossop/2c84bf7716466459be9af9c19c8cbef4
3 Run `npm ls`, get the following output showing that mv's version of rimraf is missing: https://gist.github.com/Mossop/938d3e6d949c7e0d36edfce1dd69c26e
### supporting information:
- `npm -v` prints: 3.10.5
- `node -v` prints: 6.2.0
- `npm config get registry` prints: https://registry.npmjs.org/
- Windows, OS X, or Linux?: Windows 10
- Network issues:
  - Geographic location where npm was run: USA
  - [ ] I use a proxy to connect to the npm registry.
  - [ ] I use a proxy to connect to the web.
  - [ ] I use a proxy when downloading Git repos.
  - [ ] I access the npm registry via a VPN
  - [ ] I don't use a proxy, but have limited or unreliable internet access.
- Container:
  - [ ] I develop using Vagrant on Windows.
  - [ ] I develop using Vagrant on OS X or Linux.
  - [ ] I develop / deploy using Docker.
  - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by Mossop** [comment]
One way to fix this is to use the `--legacy-bundling` argument.

**Comment by mllrjb** [comment]
@Mossop - I think I'm seeing the same issue (with different libraries). If I do `npm i` a second time, it seems to install the missing package (and `npm ls` is clean). Does that work for you as well?

**Comment by Mossop** [comment]
@mllrjb Looks like it does yes

**Comment by mllrjb** [comment]
(Linking related issue for tracking):

#13352
