### ISSUE TITLE
sass not installing

### ISSUE THREAD

**Issue by blizz2** [npm/npm#13384]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [x ] npm is producing an incorrect install.
- [ ] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
#### What's going wrong?

it appears not to be installing sass when doing "npm install"

``` console
npm http 304 https://registry.npmjs.org/repeat-string
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"v0.10.25","npm":"1.3.10"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"v0.10.25","npm":"1.3.10"})

> node-sass@3.8.0 install /home/ubuntu/apps/projecity/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/node-sass
> node scripts/install.js

npm ERR! Error: spawn ENOMEM
npm ERR!     at errnoException (child_process.js:988:11)
npm ERR!     at ChildProcess.spawn (child_process.js:935:11)
npm ERR!     at exports.spawn (child_process.js:723:9)
npm ERR!     at runPackageLifecycle (/usr/share/npm/lib/utils/lifecycle.js:154:14)
npm ERR!     at Array.0 (/usr/lib/nodejs/slide/lib/bind-actor.js:15:8)
npm ERR!     at LOOP (/usr/lib/nodejs/slide/lib/chain.js:15:14)
npm ERR!     at chain (/usr/lib/nodejs/slide/lib/chain.js:20:5)
npm ERR!     at lifecycle_ (/usr/share/npm/lib/utils/lifecycle.js:113:3)
npm ERR!     at /usr/share/npm/lib/utils/lifecycle.js:58:5
npm ERR!     at /usr/share/npm/lib/utils/lifecycle.js:128:12
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-74-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/ubuntu/apps/projecity
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! syscall spawn
npm ERR! code ENOMEM
npm ERR! errno ENOMEM
npm http GET https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/path-is-absolute
npm http 304 https://registry.npmjs.org/minimatch
```
#### How can the CLI team reproduce the problem?

am a newbie so  am not sure what all is needed but here is package.json

``` json
{
  "name": "projecity",
  "version": "0.0.0",
  "description": "Small description for projecity goes here",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "build": "ember build",
    "start": "ember server",
    "test": "ember test"
  },
  "repository": "",
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "broccoli-asset-rev": "^2.4.2",
    "ember-ajax": "0.7.1",
    "ember-cli": "2.5.1",
    "ember-cli-app-version": "^1.0.0",
    "ember-cli-babel": "^5.1.6",
    "ember-cli-bootstrap-sassy": "0.5.3",
    "ember-cli-datepicker": "2.0.1",
    "ember-cli-dependency-checker": "^1.2.0",
    "ember-cli-file-picker": "0.0.9",
    "ember-cli-htmlbars": "^1.0.3",
    "ember-cli-htmlbars-inline-precompile": "^0.3.1",
    "ember-cli-inject-live-reload": "^1.4.0",
    "ember-cli-jshint": "^1.0.0",
    "ember-cli-md5": "^0.1.0",
    "ember-cli-moment-shim": "2.0.0",
    "ember-cli-qunit": "^1.4.0",
    "ember-cli-release": "0.2.8",
    "ember-cli-sass": "5.3.1",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-crumbly": "1.0.2",
    "ember-data": "^2.5.0",
    "ember-export-application-global": "^1.0.5",
    "ember-load-initializers": "^0.5.1",
    "ember-pikaday": "1.1.0",
    "ember-resolver": "^2.0.3",
    "ember-simple-auth": "1.1.0",
    "ember-simple-auth-token": "1.1.1",
    "ember-truth-helpers": "1.2.0",
    "loader.js": "^4.0.1",
    "torii": "^0.8.0"
  }
}
```
### supporting information:
- `npm -v` prints:

1.3.10
- `node -v` prints:

v0.10.25
- `npm config get registry` prints:

https://registry.npmjs.org/
- Windows, OS X, or Linux?:

ubuntu 14.04
- Network issues:
  - Geographic location where npm was run:
  - [ ] I use a proxy to connect to the npm registry.
  - [ ] I use a proxy to connect to the web.
  - [ ] I use a proxy when downloading Git repos.
  - [ ] I access the npm registry via a VPN
  - [ ] I don't use a proxy, but have limited or unreliable internet access.
- Container:
  - [ ] I develop using Vagrant on Windows.
  - [ ] I develop using Vagrant on OS X or Linux.
  - [ ] I develop / deploy using Docker.
  - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@blizz2 Hello! `npm@1.3` is over two years old and is no longer supported. Can you try updating first?

**Comment by blizz2** [comment]
Sweet! Thanks for letting me know I will do that and see what happens...

**Comment by blizz2** [comment]
I ran

sudo npm install npm -g

and am still at 1.3.10 is there some other way of upgrading?

**Comment by blizz2** [comment]
Okay looks like I had a node issue.

downloaded the latest node and installed into /usr using
cd /usr
sudo tar --strip-components 1 -xf ~/node/node-v4.4.7-linux-x64.tar.xz

that set node to v 4.4.7
and set npm to 2.15.8

then I ran sudo npm install npm -g
and npm is now at
3.10.5

Am going to retry the npm install...

**Comment by blizz2** [comment]
Now I get:

**Comment by blizz2** [comment]
ubuntu@ip-172-31-19-102:~/apps/projecity$ npm install
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash-node@2.4.1: This package has been discontinued in favor of lodash@^4.0.0.
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! Linux 3.13.0-74-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5

npm ERR! Invalid array buffer length
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/apps/projecity/npm-debug.log

**Comment by blizz2** [comment]
attaching debug log
[npm-debug.log.zip](https://github.com/npm/npm/files/364451/npm-debug.log.zip)

**Comment by blizz2** [comment]
reverted to much earlier version of code got npm install to run but then got:

ember build
ENOENT: no such file or directory, scandir '/home/ubuntu/apps/projecity/node_modules/node-sass/vendor'


installed sass with npm install node-sass 

now am getting:

vendor.js:10Uncaught Error: Bootstrap's JavaScript requires jQuery

which is an error was getting earlier.

Think I am just going to rebuild this project from scratch since I had bad node and npm versions to start with...  drats
