### ISSUE TITLE
Alternative login mechanisms for the npm CLI

### ISSUE THREAD

**Issue by zkat** [npm/npm#13388]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [ ] npm is producing an incorrect install.
- [ ] npm is doing something I don't understand.
- [x] Other (_see below for feature requests_):
## Feature: alternative login types

The npm CLI currently directly supports two auth strategies:
- basic-auth, which involves sending a username and password, is used for legacy versions and use cases and continues to be supported by the registry, but is not the default. Some third-party registries also still rely on it.
- auth-token, or the bearer token auth, is the more modern auth mechanism, and involves sending a session token in the headers for registry requests, with a separate explicit login verification step.

These strategies are all well and good, but npm exists in a larger ecosystem of users, and even within npm, Inc, there is interest in being able to support a number of other login and authentication-related features, many of which we've had people asking us to implement for a very long time:
- Single-sign-on systems like SAML and OAuth2, which mean people don't have to remember and maintain a login for the npm registry (or npm enterprise).
- Two-factor authentication for publishing, which could be used to enable greater security for high-traffic packages like lodash, which could have catastrophic results if compromised.
- GitHub login and integration, which would allow us to potentially do all sorts of neat GitHub integration tricks, such as sync ssh keys and show modules that you've starred.
- Allowing npmE and third-party registries to easily and smoothly support a variety of auth strategies according to their needs.

Currently, some of these are supported through roundabout processes and manually copying auth tokens into .npmrc. We'd like to do better.
##### Getting this into the CLI

While many of the above could be hacked into the current login system, that would cause maintenance problems when it comes to including them as part of the current login code, on both the npm and npm-registry-client sides. The API surface increases significantly with these, the flow for 'interviewing' users gets more varied and complicated (aka walking them through the various possible login steps adn prompts), and the general code needed for this would basically explode, out of a chunk of code that's already way hairier than it needs to be. It would simply become progressively harder to extend over time or even modify and patch, with the current login architecture.

So we don't think it's useful to hack this directly into the current CLI code.
##### Enter the API

Instead, we want to implement a generic, extensible architecture for login and establishing registry sessions. The goal of this architecture is ambitious: to provide a generic framework on which to develop and make available the full range of desired auth strategies, while keeping the implementation details as separate and isolated from internal CLI incidentals as possible.

In reality, we believe that a simple API can cover pretty much any auth mechanism we could possibly need, provided it's acceptable to only make a limited set of modifications to outgoing requests, and to the npm configuration. This feature request represents an initial stab at a new approach to login that would open the doors to the fuller API.
##### The Interface

As far as the login modules themselves go, the API surface is simple. An `auth` module (hereby referred to as `auth` as an example name) would need to only implement only one function, which is asynchronous:

`auth.login` - also called the "interviewer".
- It is invoked immediately after a user types in `npm login` in the command line and triggers the particular plugin.
- Walks a CLI user through the necessary steps to initiate an authenticated session
- CLI fully yields process control to this function until its callback is called.
- Any network-related bits are fully the responsibility of the login function.
#### That's It?

Yes! This external API surface should cover the basics of what a user might reasonably want out of a registry authentication system:
- tools that ask users for login details and signup
- opening browser sessions to complete SSO user flows
- outputting any further instructions to the user into the command line.

Notably missing from here are 2FA prompts during publish and installation, but those are out of scope for the initial implementation of this feature. Future features might be added to allow modules to manage and/or interrupt the actual request authentication process. For now, this feature relies on all auth strategies using a simple token-based auth strategy, which is already supported.
##### Picking What to Use

The above focuses mainly on the API that we would need to implement for each new auth strategy, but how would the CLI choose which one to use?

The main configuration for changing login mechanisms is through the `--auth-type` setting, which defaults to `legacy`, which triggers the current (legacy) login logic. Any other setting will attempt to search for a registered login module that will then be handed control of the login process entirely, by calling its `auth.login` function with the necessary parameters.

**Comment by rsp** [comment]
@zkat You seem to have put a lot of thought into npm login mechanisms judging from this and issue #13389 so maybe it's the right place express some of my thoughts about the npm CLI login mechanisms that I have for quite some time.

I was thinking about the way how npm manages authentication and I am concerned about the security of the process. Currently everything needed to access npm from the CLI is in ~/.npmrc which is available to any npm module that I install (and all programs that I run, for that matter). During the configuration of npm I was required to enter my main password to my account on npmjs.org and I have to do it on every machine that I want to publish my modules from.

An ideal login mechanism for the npm CLI in my opinion would be no login mechanism at all. The npm CLI doesn't need one at all. If only you could enter your ssh public keys on the npm website then npm publish could just use ssh to connect to the npm server and wouldn't need to know your password or store any auth token to do that.

Actually your keys are already available on https://github.com/zkat.keys and https://api.github.com/users/zkat/keys so all you would need to do would be to enter your GitHub username on npm (which you can already do) and no more GitHub integration would be needed to do that. npm doesn't need your authorization to get your public keys, it just needs to know your username.

Of course a better GitHub integration and other things that you write about would be great for other reasons, but for just the `npm publish` part all the information is already there. npm accounts already include GitHub logins, from GitHub logins you can get ssh keys and with ssh keys you can authenticate users. I see no reason why `npm publish` couldn't work just like `git push`.

What would be needed is an ssh server that listens for connections and acts appropriately and of course a change in how the npm CLI works to support that. It doesn't have to be the only mechanism to publish to npm, the old way could still work of course.

Do you think this is realistic or maybe I can forget about it? :) I'd like to know what you think.

Another thing I'm missing is an API for applications to use npm on behalf of users. This is not exactly the API that you are describing here but it is connected. What I'd like to be able to do would be to have an application that redirects me to npm website and asks me if I want to grant certain privileges, e.g. to publish on npm on my behalf, and authenticate me using one of the techniques that you describe above. Have you thought about something like that?

**Comment by DanSGiesbrecht** [comment]
Is this feature request still valid?

**Comment by zkat** [comment]
Nope. This was all implemented. There's even been new shiny things since then.
