### ISSUE TITLE
Running test script fails with command not found

### ISSUE THREAD

**Issue by eliperelman** [npm/npm#13385]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [x] npm is producing an incorrect install.
- [ ] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
#### What's going wrong?

When attempting to run a script which contains `npm explore` to a path to a module, npm throws an error about not finding `/bin/zsh` or `/bin/bash`. In trying to narrow down the regression range, this seems to work correctly in v3.8.9 and fails at v3.9.0+.

<details>
 <summary>

Test case log</summary>

``` sh
$ npm test

> npm-fail@0.0.0 test /Users/eli/code/npm-fail
> npm explore $(echo "$(cd "$(dirname "sub")" && pwd)/$(basename "sub")") -- 'npm install && npm test'

zsh:1: command not found: npm install && npm test
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "explore" "/Users/eli/code/npm-fail/sub" "--" "npm install && npm test"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.0
npm ERR! file /bin/zsh
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! enoent spawn ENOENT
npm ERR! enoent spawn ENOENT
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent
npm ERR! enoent Check if the file '/bin/zsh' is present.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/eli/code/npm-fail/npm-debug.log
npm ERR! Test failed.  See above for more details.
```

</details>
#### How can the CLI team reproduce the problem?

I've created a reduced test case at https://github.com/eliperelman/npm-fail
### supporting information:
- `npm -v` prints: `3.9.0`
- `node -v` prints: `v6.2.1`
- `npm config get registry` prints: `https://registry.npmjs.org/`
- Windows, OS X, or Linux?: `OS X`
- Network issues:
  - Geographic location where npm was run:
  - [ ] I use a proxy to connect to the npm registry.
  - [ ] I use a proxy to connect to the web.
  - [ ] I use a proxy when downloading Git repos.
  - [ ] I access the npm registry via a VPN
  - [ ] I don't use a proxy, but have limited or unreliable internet access.
- Container:
  - [ ] I develop using Vagrant on Windows.
  - [ ] I develop using Vagrant on OS X or Linux.
  - [ ] I develop / deploy using Docker.
  - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
Thanks so much for the test case! Here are the results of my `git bisect`:

``` bash
91fc24f2763c2e0591093099ffc866c735f27fde is the first bad commit
commit 91fc24f2763c2e0591093099ffc866c735f27fde
Author: Rebecca Turner <snip>
Date:   Tue Mar 8 11:44:45 2016 -0800

    explore: Fix running sub-commands on windows
    
    Credit: @iarna
    PR-URL: https://github.com/npm/npm/pull/11444
    Reviewed-By: @zkat
    Reviewed-By: @iarna
    Reviewed-By: @othiym23

:040000 040000 91cbd47368fbcef95e58b8f80275c6466b47548a 9a04a4f5cf556a7a34e871d1d83cf993e001918d M	lib
```
