### ISSUE TITLE
I can't run this command "npm install react-native-scrollable-tab-view --save"

### ISSUE THREAD

**Issue by aspirantmisho** [npm/npm#13386]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [ ] npm is producing an incorrect install.
- [ ] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
### supporting information:
- `npm -v` prints:
- `node -v` prints:
- `npm config get registry` prints:
- Windows, OS X, or Linux?:
- Network issues:
  - Geographic location where npm was run:
  - [ ] I use a proxy to connect to the npm registry.
  - [ ] I use a proxy to connect to the web.
  - [ ] I use a proxy when downloading Git repos.
  - [ ] I access the npm registry via a VPN
  - [ ] I don't use a proxy, but have limited or unreliable internet access.
- Container:
  - [ ] I develop using Vagrant on Windows.
  - [x] I develop using Vagrant on OS X or Linux.
  - [ ] I develop / deploy using Docker.
  - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by helio-frota** [comment]
@aspirantmisho looks like this is a problem with `react-native-scrollable-tab-view` not with npm.

```
foo@npmbox:~/foo$ npm install react-native-scrollable-tab-view --save
foo@1.0.0 /home/foo/foo
├── UNMET PEER DEPENDENCY react-native@>=0.20.0
└─┬ react-native-scrollable-tab-view@0.7.0 
  └── react-timer-mixin@0.13.3 

npm WARN react-native-scrollable-tab-view@0.7.0 requires a peer of react-native@>=0.20.0 but none was installed.
npm WARN foo@1.0.0 No description
npm WARN foo@1.0.0 No repository field.
```

If you run this:

`npm install react-native react-native-scrollable-tab-view --save`

You will be able to install but, you will see `├── UNMET PEER DEPENDENCY react@~15.4.0-rc.4`

So this means you need: react, react-native first before try to install `react-native-scrollable-tab-view`

**Comment by KenanY** [comment]
Closing since this issue appears to be blank now.
