### ISSUE TITLE
npm install skips devDependencies

### ISSUE THREAD

**Issue by drcmda** [npm/npm#13382]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?

For a local package.json, it installs dependencies but does not install devDependencies which leaves unmet peer dependencies. It started today with an older npm version, 3.9.x. I have removed Node and Npm and updated. Still the same problem.

### supporting information:

 - `npm -v` prints: 3.10.3
 - `node -v` prints: v6.3.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X, or Linux?: Windows
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
FWIW, I cannot reproduce this with `npm@3.10.6` on Linux.

**Comment by KenanY** [comment]
@drcmda Could you provide a test case for this?

**Comment by KenanY** [comment]
Closing as abandoned.
