### ISSUE TITLE
NPM doesn't call isInstallable on packages from shrinkwrap files

### ISSUE THREAD

**Issue by codeimpossible** [npm/npm#13394]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

NPM doesn't seem to call [isInstallable](https://github.com/npm/npm/blob/2a5977e0c65b244e92d848fcd56f2f80ba8cdf3b/lib/install/validate-args.js#L29) on packages if they are being installed via a npm-shrinkwrap.json file. This can cause problems when a shrinkwrap is generated on a different platform than the one consuming it.

#### How can the CLI team reproduce the problem?

FYI, You'll need a windows pc to test this.

First, I modified `C:\program files\nodejs\node_modules\npm\lib\install\validate-args.js` file to log when a package was being checked against the current platform:

```js
// line 29:
var isInstallable = module.exports.isInstallable = function (pkg, next) {
  console.log('HERE: checking to see if ' + pkg.name + '@' + pkg.version + ' is installable');
  var force = npm.config.get('force')
  var nodeVersion = npm.config.get('node-version')
  if (/-/.test(nodeVersion)) {
    // for the purposes of validation, if the node version is a prerelease,
    // strip that. We check and warn about this sceanrio over in validate-tree.
    nodeVersion = nodeVersion.replace(/-.*/, '')
  }
  var strict = npm.config.get('engine-strict')
  checkEngine(pkg, npm.version, nodeVersion, force, strict, iferr(next, thenWarnEngineIssues))
  function thenWarnEngineIssues (warn) {
    if (warn) getWarnings(pkg).push(warn)
    console.log('HERE: checkPlatform');
    console.log(process.platform, process.arch);
    console.log(pkg.name, pkg.version, pkg.os || 'no-os');
	  console.log(force ? 'is forced' : 'not forced');
	  console.log('-=-=-=-=-=-=-=-=-=-=-=-=-=-=-');
    checkPlatform(pkg, force, next)
  }
}
```

I created a small repo that has a project that reproduces the issue. Clone it and checkout the problem branch to see the issue.

```sh
$ git clone https://github.com/codeimpossible/testing-npm-installs
$ cd testing-npm-installs && git checkout npm-shrinkwrap-on-win-fsevents-gets-installed
$ npm i -ddd > install.txt 2>&1
```

The log file won't contain any "notsup"s and the tree output at the bottom will not contain any WARNs about skipping the fsevents dependency. There should be a npm-debug.log file that contains a node-gyp failure from fsevents attempting to be built.

If you remove the shrinkwrap from the `project-webpack` project, then the install will complete without issue.

```sh
$ rm ../project-webpack/npm-shrinkwrap.json
$ npm i -ddd > install.txt 2>&1
```

Now the log will show npm checking to see if fsevents should be installed for the current os.

### supporting information:

 - `npm -v` prints: 3.10.5
 - `node -v` prints: 4.4.2 (also tried on 5.12.0 and 6.0.0) 
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X, or Linux?: Windows
 - Network issues:
   - Geographic location where npm was run: Austin, TX and EC2-US-EAST-1
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

I did a bit of investigation and this issue might be related to the following issues, but it doesn't feel like a perfect dupe of either of them.

- https://github.com/npm/npm/issues/6801
- https://github.com/npm/npm/issues/2679

**Comment by iarna** [comment]
Oh! Thank you for pointing this out. This relates to us trying to compile shrinkwrapped optional deps on platforms they don't support. This _shouldn't_ produce a different tree in the end, but it does mean we waste time and give warning messages that are unhelpful. I'm grabbing this to take care of along with the other shrinkwrap issues I'm working.

**Comment by codeimpossible** [comment]
@iarna Thanks for taking this!
