### ISSUE TITLE
What does npm do to move a script to the bin?

### ISSUE THREAD

**Issue by bjskistad** [npm/npm#13391]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I want my source code to be available only through git. I was wondering what [npm does to move a script to the bin?](http://stackoverflow.com/questions/38386094/what-does-npm-do-to-move-a-script-to-the-bin)

**Comment by heijmans** [comment]
I don't really understand the question. Could you perhaps describe what you are trying to do or add a demo code or project?

**Comment by bjskistad** [comment]
@heijmans I'm wondering how npm creates scripts in the bin.
```
"bin": {
  "foo": "foo.js"
}
```
How does it create the `foo` command?

**Comment by KenanY** [comment]
Off the top of my head, I think [`cmd-shim`](https://github.com/ForbesLindesay/cmd-shim) is used to do this. Someone with more familiarity can correct me if I am wrong, of course :)

**Comment by bjskistad** [comment]
@KenanY Thanks! (By the way, you website is giving me a 500 error.)

**Comment by KenanY** [comment]
@bjskistad Oh, I thought I had resolved that... I'll look into it, thanks!

**Comment by bjskistad** [comment]
No problem! Good luck!
