### ISSUE TITLE
Unable to install npm install react --save

### ISSUE THREAD

**Issue by pedroresende** [npm/npm#13396]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "react" "--save"
npm ERR! node v4.2.6
npm ERR! npm  v3.8.3
npm ERR! code ENOSELF

npm ERR! Refusing to install react as a dependency of itself
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/pedroresende/Desktop/react/npm-debug.log

#### How can the CLI team reproduce the problem?

npm install react --save  

### supporting information:

 - `npm -v` prints: 3.8.3
 - `node -v` prints: v4.2.6
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X, or Linux?: Mac OS X El Capitan
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by pedroresende** [comment]
The problem is related with the fact that I've set the package.json

```
"name": "react",
```

**Comment by hamczu** [comment]
yes, this is expected behavior - npm depends on unique packages names, so as the error states:
"Refusing to install react as a dependency of itself"

**Comment by pedroresende** [comment]
@hamczu thanks
