### ISSUE TITLE
npm WARN install Couldn't install optional dependency: Unsupported

### ISSUE THREAD

**Issue by krushnachandra** [npm/npm#13402]
```
$ npm install
npm WARN install Couldn't install optional dependency: Unsupported
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
```

From the last one month trying to use angualr 2 not able to update node 

npm people what you are doing every time while updating problem its like a hell to me

**Comment by krushnachandra** [comment]
> product-management@1.0.0 postinstall E:\Krushna\Angular2\Angular2-GettingStarted\APM - Final Updated
> typings install

typings WARN deprecated 7/9/2016: "registry:dt/node#6.0.0+20160621231320" is deprecated (updated, replaced or removed)
typings ERR! message Unable to read typings for "core-js". You should check the entry paths in "core-js.d.ts" are up to date
typings ERR! caused by Unable to connect to "https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/95e782233e8e203a0b9283c3a7031faee428a530/core-js/core-js.d.ts"
typings ERR! caused by getaddrinfo ENOTFOUND raw.githubusercontent.com raw.githubusercontent.com:443

typings ERR! cwd E:\Krushna\Angular2\Angular2-GettingStarted\APM - Final Updated
typings ERR! system Windows_NT 10.0.10240
typings ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\Krushna\\Angular2\\Angular2-GettingStarted\\APM - Final Updated\\node_modules\\typings\\dist\\bin.js" "install"
typings ERR! node -v v5.5.0
typings ERR! typings -v 1.3.1

typings ERR! If you need help, you may report this error at:
typings ERR!   <https://github.com/typings/typings/issues>

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.5.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! product-management@1.0.0 postinstall: `typings install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the product-management@1.0.0 postinstall script 'typings install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the product-management package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     typings install
npm ERR! You can get their info via:
npm ERR!     npm owner ls product-management
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\Krushna\Angular2\Angular2-GettingStarted\APM - Final Updated\npm-debug.log

**Comment by krushnachandra** [comment]
Can any any will help me to solve

**Comment by chespinoza** [comment]
Did you try starting again with a new project folder and following strictly the quickstart instructions?
remember run all commands from the project root folder (angular2-quickstart).
