### ISSUE TITLE
missing script: typings

### ISSUE THREAD

**Issue by lfrountzos** [npm/npm#13403]
```
C:\WORKSPACES\Angular\Angular2Udemy>npm run typings install
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "typings" "install"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3

npm ERR! missing script: typings
```

**Comment by KenanY** [comment]
@lfrountzos Do you have a `"typings"` script defined in your `package.json`?

**Comment by gauravgoyal1911** [comment]
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8

npm ERR! missing script: start
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by KenanY** [comment]
@gauravgoyal1911 Do you have a `"start"` script defined in your `package.json`?

**Comment by KenanY** [comment]
Closing due to no response from @lfrountzos after a week. Can reopen if issue has not yet been resolved.

@gauravgoyal1911 Please open a new issue if you are still experiencing any issues.

**Comment by MaximZagorodsky** [comment]
I had the same issue, but it was solved by "typings install" instead "npm run typings install" command
