### ISSUE TITLE
Not able to start npm

### ISSUE THREAD

**Issue by gauravgoyal1911** [npm/npm#13411]
#### I'm opening this issue because:

  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Not able to start npm .
npm start command not working.
![npm_start issue](https://cloud.githubusercontent.com/assets/17172971/16906692/95edfd34-4cd9-11e6-89fb-1339fbc9970e.PNG)

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@gauravgoyal1911 Do you have a `"start"` script defined in your `package.json`?

**Comment by KenanY** [comment]
Closing due to no response after a week.
