### ISSUE TITLE
Move `npm pack` code to independent project

### ISSUE THREAD

**Issue by piranna** [npm/npm#13410]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [ ] npm is producing an incorrect install.
- [ ] npm is doing something I don't understand.
- [x] Other (_see below for feature requests_):
#### What's the feature?

Move the code of `npm pack` to an independent importable module, similar to what [tar-pack](https://www.npmjs.com/package/tar-pack) does (done by @ForbesLindesay, already a member of the @npm organization).
#### What problem is the feature intended to solve?

Allow to automatically create and publish npm packages by using a rewrite of the [publish](https://github.com/cmanzana/node-publish) module.
#### Is the absence of this feature blocking you or your team? If so, how?

I'm planning to make NodeOS a rolling release OS and although is possible to upload to the CI server a copy of the `.npmrc` file, that's hacky and unreliable. Due to this, I would like to use `npm-registry-client` instead, but it doesn't create the tar.gz files.
#### Is this feature similar to an existing feature in another tool?

This is similar to the [tar-pack](https://www.npmjs.com/package/tar-pack) module, and in fact npm itself could be use it as implementation detail.
#### Is this a feature you're prepared to implement, with support from the npm CLI team?

Don't have too much time lately, but I could give it a try and in fact I have been checking how difficult could it be, but seems it's not a weekend project...

**Comment by rmg** [comment]
I found this while looking for something else: the ability to publish a pre-packed tarball without all the unpacking/script-running/re-packing that `npm publish` does.

It looks like `npm-registry-client` will allow me to write my own, but I just wanted to chime in here in case the mention of another use-case for further componentization helps.

**Comment by piranna** [comment]
You can pack a directory with 'npm pack', but thanks for giving another use
case for this to be moved on an independent project :-)

**Comment by rmg** [comment]
@piranna I'm referring to publishing that tarball that `npm pack` produces. If you do `npm publish my-packed-module-1.2.3.tgz` it doesn't just `PUT` that tarball like some would expect. It unpacks it and then redoes all the things that `npm pack` did already. You can't do a bit-for-bit promotion of a tested build artifact.

**Comment by piranna** [comment]
> If you do npm publish my-packed-module-1.2.3.tgz it doesn't just PUT that tarball like some would expect

I think this works as expected, since you can be able to install a module by directly using the package filename as argument, so probably this is orthogonal to `npm` design. I think in that case you could be interested to use the `publish()` method from the [npm-registry-client](https://www.npmjs.com/package/npm-registry-client#clientpublishuri-params-cb) package, that just upload a tgz file directly to the npm registry and that's used internally by `npm` itself.

**Comment by rmg** [comment]
Using npm-registry-client is what I was planning on doing :-)

Right now `npm pack` does:
 * cache add dir
   * runs prepublish
   * makes tgz
   * puts tgz in cache dir
 * copies tgz from cache dir to local dir

And the `npm publish foo.tgz` does:
 * cache add tgz
   * extracts tgz to cache dir
   * cache add dir
     * runs prepublish
     * makes tgz
     * puts tgz in cache dir
 * does http `PUT` of the tgz from the cache directory

They both make use of `cache.add`, which makes some degree of sense, it just so happens that it ends up repeating parts of tbe process.

Now that I've spelt it out, though.. I bet it wouldn't be very risky to have `cache.add` do a shasum of the tgz it is given and if it already matches the one in the cache from when `npm pack` (or any other code path that calls `cache.add()`), then it could skip part of the process and short circuit the process. As a bonus, this would make cache.add idempotent. Hm.. :thinking:. I might need to PR that (or bait @sam-github to).

**Comment by piranna** [comment]
That shasum would be used for package signature, too...
