### ISSUE TITLE
npm deprecate mongodb@"< 2.2.4" "Please use 2.2.4 or higher" failing with 403

### ISSUE THREAD

**Issue by christkv** [npm/npm#13417]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [ ] npm is producing an incorrect install.
- [ ] npm is doing something I don't understand.
- [X ] Other (_see below for feature requests_):
#### What's going wrong?

npm deprecate mongodb@"< 2.2.4" "Please use 2.2.4 or higher"

failing with 403 even though I'm authenticated with the right credentials and can publish.
### supporting information:
- `npm -v` prints:
  2.15.1
- `node -v` prints:
  v4.4.4
- `npm config get registry` prints:
  https://registry.npmjs.org/
- Windows, OS X, or Linux?:
  OS X
- Network issues:
  - Geographic location where npm was run:
    Spain, Europe
  - [ ] I use a proxy to connect to the npm registry.
  - [ ] I use a proxy to connect to the web.
  - [ ] I use a proxy when downloading Git repos.
  - [ ] I access the npm registry via a VPN
  - [ ] I don't use a proxy, but have limited or unreliable internet access.
- Container:
  - [ ] I develop using Vagrant on Windows.
  - [ ] I develop using Vagrant on OS X or Linux.
  - [ ] I develop / deploy using Docker.
  - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by gordonwoodhull** [comment]
I am seeing the same problem attempting to deprecate `dc@2.1.0-dev` 

(The tag was created in error - tagging a development version makes no sense! But since it has a higher number people continue to check it out and encounter old bugs, since it's not possible to update.)

**Comment by christkv** [comment]
@gordonwoodhull turns out it was a corrupt npm entry that caused the issue for me, you might need to contact support or open a new ticket for them to fix it.

**Comment by gordonwoodhull** [comment]
Thanks @christkv, the error directed me here to the GitHub Issues, but I'm glad to see there is also a [support page](https://www.npmjs.com/support)!
