### ISSUE TITLE
Can't npm adduser on Windows

### ISSUE THREAD

**Issue by ummahusla** [npm/npm#13420]
#### I'm opening this issue because:

  - [ ] npm is doesn't add a user, when I try to login

#### What's going wrong?

When I've tried  `npm adduser` command terminal was stuck in one place forever. Here is the output which I had. 

```
Username: ummahusla
Password:
Email: (this IS public) ummahusla@gmail.com
```

Today in the morning I've tried to on my work Mac Mini and it worked like a charm. 
```
Username: ummahusla
Password:
Email: (this IS public) ummahusla@gmail.com
Logged in as ummahusla on https://registry.npmjs.org/.
```

#### How can the CLI team reproduce the problem?

I assume it's not really problem with npm and I blaming Windows for that? Can anyone suggest me how I can fix it for Windows PC? 

Thanks!

**Comment by KenanY** [comment]
@ummahusla `npm --version`?

**Comment by ummahusla** [comment]
Sorry, it was my bad. I messed it  up on my Windows PC. 

Thanks

**Comment by team6612** [comment]
How did you fix this? I have the same problem and no idea to deal with it.
