### ISSUE TITLE
npm installs the wrong version of gulp

### ISSUE THREAD

**Issue by XaveScor** [npm/npm#13425]
### I'm opening this issue because:
npm is producing an incorrect install.
#### What's going wrong?
The incorrect version(3.9.1) is installed but I want 4.0. 
#### How can the CLI team reproduce the problem?
Powershell:
```
npm i gulpjs/gulp.git#4.0 --save-dev
rm -r -Force node_modules/
npm I
```
### supporting information:

 - `npm -v` prints: **3.10.5**
 - `node -v` prints: **v6.3.0**
 - `npm config get registry` prints: **https://registry.npmjs.org/**
 - Windows, OS X, or Linux?: **Windows 10**
 - Geographic location where npm was run: **Kazakhstan**

**Comment by KenanY** [comment]
I cannot reproduce this with Node.js v6.3.0 and `npm@3.10.6` on Linux

``` bash
$ npm i gulpjs/gulp.git#4.0 --save-dev
$ npm ls gulp
npm-13425@1.0.0 /tmp/npm-13425
└── gulp@4.0.0-alpha.2  (git://github.com/gulpjs/gulp.git#d8f5c90a0622d19ef1943a2a3d02dc50e3c853e7)

$ rm -rf node_modules/
$ npm i
$ npm ls gulp
npm-13425@1.0.0 /tmp/npm-13425
└── gulp@4.0.0-alpha.2  (git://github.com/gulpjs/gulp.git#d8f5c90a0622d19ef1943a2a3d02dc50e3c853e7)
```

**Comment by XaveScor** [comment]
After second install on Windows 10.
```PS C:\path\frontend> npm ls gulp
sl-votes-frontend@0.0.1 C:\path\frontend
`-- gulp@3.9.1  invalid

npm ERR! invalid: gulp@3.9.1 C:\path\frontend\node_modules\gulp```

**Comment by KenanY** [comment]
@XaveScor Does the entry in your `package.json` look like this?

``` json
{
  "devDependencies": {
    "gulp": "github:gulpjs/gulp#4.0"
  }
}
```

**Comment by XaveScor** [comment]
Yes. The `npm i gulpjs/gulp.git#4.0 --save-dev` generating the equivalent string

**Comment by KenanY** [comment]
@XaveScor Did you find the cause of this?
