### ISSUE TITLE
Remote Machine Access

### ISSUE THREAD

**Issue by Poojaya** [npm/npm#13434]
Hi 
i need to run the test code locally by connecting the remote machine using selenium server.

I connected the remote machine after placing Selenium standalone.jar and Chromedriver.exe in C://Selenium.
Executed commands in remote:

java -jar selenium-server-standalone-2.52.0.jar -role hub -port 4444
java -Dwebdriver.chrome.driver="C:\Selenium\chromedriver.exe" -jar selenium-server-standalone-2.52.0.jar -role webdriver -browser "browserName=chrome" node –hub  http://localhost:4444/grid/register -port 5555

When i tried to run the test case locally using command prompt

grunt protractor:run_chrome --cucumberOpts={\"tags\":\"@e2e\"} --seleniumAddress=http://<remote machine ip>:4444/wd/hub

remote machine ip is provided

Getting this error. Please help me to resolve
Error: ETIMEDOUT connect ETIMEDOUT 10.71.127.108:4444
    at ClientRequest.<anonymous> (C:\Users\Jk\Documents\NewproAutoma
tion\ss-newpro-testautomation\NewProRegressionSt\node_modules\selenium-webdriver
\http\index.js:365:15)
    at emitOne (events.js:90:13)
    at ClientRequest.emit (events.js:182:7)
    at Socket.socketErrorListener (_http_client.js:306:9)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at emitErrorNT (net.js:1265:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
From: Task: WebDriver.createSession()
    at acquireSession (C:\Users\Jk\Documents\NewproAutomation\ss-new
pro-testautomation\NewProRegressionSt\node_modules\selenium-webdriver\lib\webdri
ver.js:62:22)
    at Function.createSession (C:\Users\Jk\Documents\NewproAutomatio
n\ss-newpro-testautomation\NewProRegressionSt\node_modules\selenium-webdriver\li
b\webdriver.js:295:12)
    at Builder.build (C:\Users\Jk\Documents\NewproAutomation\ss-newp
ro-testautomation\NewProRegressionSt\node_modules\selenium-webdriver\builder.js:
458:24)
    at Hosted.DriverProvider.getNewDriver (C:\Users\Jk\Documents\New
proAutomation\ss-newpro-testautomation\NewProRegressionSt\node_modules\protracto
r\built\driverProviders\driverProvider.js:37:33)
    at Runner.createBrowser (C:\Users\Jk\Documents\NewproAutomation\
ss-newpro-testautomation\NewProRegressionSt\node_modules\protractor\built\runner
.js:182:43)
    at C:\Users\Jk\Documents\NewproAutomation\ss-newpro-testautomati
on\NewProRegressionSt\node_modules\protractor\built\runner.js:255:30
    at _fulfilled (C:\Users\Jk\Documents\NewproAutomation\ss-newpro-
testautomation\NewProRegressionSt\node_modules\protractor\node_modules\q\q.js:83
4:54)
    at self.promiseDispatch.done (C:\Users\Jk\Documents\NewproAutoma
tion\ss-newpro-testautomation\NewProRegressionSt\node_modules\protractor\node_mo
dules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Users\Jk\Documents\Newpro
Automation\ss-newpro-testautomation\NewProRegressionSt\node_modules\protractor\n
ode_modules\q\q.js:796:13)
    at C:\Users\Jk\Documents\NewproAutomation\ss-newpro-testautomati
on\NewProRegressionSt\node_modules\protractor\node_modules\q\q.js:556:49
[18:25:37] E/launcher - Process exited with error code 1
>> C:\Users\Jk\Documents\NewproAutomation\ss-newpro-testautomation\N
ewProRegressionSt\node_modules\selenium-webdriver\http\index.js:365
>>       onError(new Error(message));
>>               ^
>> Error: ETIMEDOUT connect ETIMEDOUT 10.71.130.201:4444
>>     at ClientRequest.<anonymous> (C:\Users\Jk\Documents\NewproAut
omation\ss-newpro-testautomation\NewProRegressionSt\node_modules\selenium-webdri
ver\http\index.js:365:15)
>>     at emitOne (events.js:90:13)
>>     at ClientRequest.emit (events.js:182:7)
>>     at Socket.socketErrorListener (_http_client.js:306:9)
>>     at emitOne (events.js:90:13)
>>     at Socket.emit (events.js:182:7)
>>     at emitErrorNT (net.js:1265:8)
>>     at _combinedTickCallback (internal/process/next_tick.js:74:11)
>>     at process._tickCallback (internal/process/next_tick.js:98:9)
>> From: Task: WebDriver.createSession()
>>     at acquireSession (C:\Users\Jk\Documents\NewproAutomation\ss-
newpro-testautomation\NewProRegressionSt\node_modules\selenium-webdriver\lib\web
driver.js:62:22)
>>     at Function.createSession (C:\Users\Jk\Documents\NewproAutoma
tion\ss-newpro-testautomation\NewProRegressionSt\node_modules\selenium-webdriver
\lib\webdriver.js:295:12)
>>     at Builder.build (C:\Users\Jk\Documents\NewproAutomation\ss-n
ewpro-testautomation\NewProRegressionSt\node_modules\selenium-webdriver\builder.
js:458:24)
>>     at Hosted.DriverProvider.getNewDriver (C:\Users\Jk\Documents\
NewproAutomation\ss-newpro-testautomation\NewProRegressionSt\node_modules\protra
ctor\built\driverProviders\driverProvider.js:37:33)
>>     at Runner.createBrowser (C:\Users\Jk\Documents\NewproAutomati
on\ss-newpro-testautomation\NewProRegressionSt\node_modules\protractor\built\run
ner.js:182:43)
>>     at C:\Users\Jk\Documents\NewproAutomation\ss-newpro-testautom
ation\NewProRegressionSt\node_modules\protractor\built\runner.js:255:30
>>     at _fulfilled (C:\Users\Jk\Documents\NewproAutomation\ss-newp
ro-testautomation\NewProRegressionSt\node_modules\protractor\node_modules\q\q.js
:834:54)
>>     at self.promiseDispatch.done (C:\Users\Jk\Documents\NewproAut
omation\ss-newpro-testautomation\NewProRegressionSt\node_modules\protractor\node
_modules\q\q.js:863:30)
>>     at Promise.promise.promiseDispatch (C:\Users\Jk\Documents\New
proAutomation\ss-newpro-testautomation\NewProRegressionSt\node_modules\protracto
r\node_modules\q\q.js:796:13)
>>     at C:\Users\Jk\Documents\NewproAutomation\ss-newpro-testautom
ation\NewProRegressionSt\node_modules\protractor\node_modules\q\q.js:556:49
>> Test failed but keep the grunt process alive.

Done, without errors.

regards
Poojaya

**Comment by othiym23** [comment]
Hi, @Poojaya! This doesn't appear to be an issue with the npm CLI, and as such I'm going to close it. It looks like you may want to ask the [`selenium-webdriver` maintainers](https://github.com/SeleniumHQ/selenium/issues) for help, so I've linked to their issue tracker from here. Good luck getting it sorted out, and thanks for your time!
