### ISSUE TITLE
npm doesn't install latest versions of many packages

### ISSUE THREAD

**Issue by JoeArizona** [npm/npm#13433]
#### I'm opening this issue because:
- [X] npm is producing an incorrect install.
#### What's going wrong?

In many cases, npm update does not update an outdated package. For example, the current release of eslint is 3.1.0. I have 2.3.1 installed. `npm update -g eslint` does nothing – it does not update me to 3.1.0, or to any other post-2.3.1 version.

The same is true for several other packages. See the attached screenshot.

Interestingly, when I run `npm outdated -g`, it lists a few packages. The version numbers under the Current and Wanted columns are identical, which is confusing. The Latest and Location columns are blank. However, it just so happens all the packages it lists are outdated, despite the fact that Current and Wanted are the same, so it knows that these packages are outdated. It just won't update them, nor will it display the Latest release number.

The only way to install up-to-date packages that I have found is to run `npm install -g <package>@<version number>`, where I have to manually specify the exact version I want after looking up the repo.

(This is not a new problem – it's been happening for a few months.)

![npm outdated](https://cloud.githubusercontent.com/assets/8071692/16973258/21ed7086-4de7-11e6-9311-26bb43f25812.PNG)
#### Supporting Info

Node 6.3.0
npm 3.10.6
Windows 10 64-bit, OS Build 10586.494 (latest public release/patches)
No container or VM
Powershell

**Comment by CallumBrankin** [comment]
Any word on this issue?

**Comment by siemiatj** [comment]
Do `npm cache clear`. Still I think it'd be cool if npm would first check what you're trying to install, and show you a list of what's available in cache and the latest version in remote. Maybe even go a step further and make it optionally interactive where you can choose which version you'd prefer to have installed ?

**Comment by szantner** [comment]
I have exactly the same issue. Cache clear didn't work

Environment:
npm 4.4.4
node 6.2.2
Win 10 14393.953
Powershell 5.1

**Comment by szantner** [comment]
Quite quickly I think I found out that it is an issue with the command line color scheme. I couldn't get around, but if you run the same commands in Command Prompt, you'll see the latest version

**Comment by JoeArizona** [comment]
There is an issue with the color scheme, but I can't try your method at the moment because I don't have any out-of-date packages right now. Do you mean that Powershell and the regular command prompt have different behavior.

As far as what I always see in Powershell:

The Wanted column is always **green** when it displays the same version under both Current and Wanted.

The Wanted column is always **red** when it displays different versions across Current and Wanted.

In both cases you've got an out-of-date package – i.e. it only displays packages (green or red) if they're out of date. Even though the green entries show the same version in Current and Wanted, that's always incorrect – there's a newer version available, with a higher version number than what it's displaying under Wanted. To get updates in those cases you need to use the install command instead of the update command, e.g.:

`npm install -g eslint@latest`

**Comment by szantner** [comment]
Hi, I think the easiest is if you force install an outdated package and then test this in both Powershell and the Command Prompt. You'll see the difference

**Comment by fruser** [comment]
I would like to re-open this issue - I'm using `npm` on OSX and having the same issues: it won't install the latest available packages (i.e. on NPM site the package's version is `1.0.1`, but npm installs `1.0.0` only...

**Comment by FrenchMajesty** [comment]
Same here. It's been like for as long as I can remember.

**Comment by fruser** [comment]
Looks like I found the issue: my `~/.npmrc` had incorrect setting for the npm repository. Once I fixed that, I was able to download everything properly.

**Comment by scripting** [comment]
I'm using the standard Mac Terminal program, and I can't find a way around it. I can't get it to use the latest version of a package. There's a huge warning on clearing the cache, not sure I should care about it so I haven't done that yet.

**Comment by PaulWieland** [comment]
I'm having this issue too on OSX Sierra. Still no solution?

EDIT: It turns out NPM wasn't updating itself to the latest release either. I force updated npm to the latest version using homebrew and now npm is updating the packages correctly.

**Comment by slhck** [comment]
Having the same issue with a package:

```
➜ npm install reveal-md@rc --global
/usr/local/bin/reveal-md -> /usr/local/lib/node_modules/reveal-md/bin/cli.js
+ reveal-md@2.0.0-rc.1
updated 1 package in 8.307s

➜ npm outdated -g
Package       Current      Wanted  Latest  Location
reveal-md  2.0.0-rc.1  2.0.0-rc.6   1.1.3
```

It should have installed `rc.6` instead of `rc.1`, but it simply does not upgrade.

When I specify the exact version:

```
➜ npm install reveal-md@2.0.0-rc.6 --global
```

… it works.

This all happens with `npm` version 5.8.0 and `node` version 9.11.1 under macOS 10.12.

**Comment by phil123456** [comment]
this s...  installing @latest works but I have to do this one by one

**Comment by JoeUX** [comment]
I'm the OP, and I'm still having this problem almost two years later. One new twist is that `npm -g outdated` will often falsely tell me than an update to npm itself is available, and will falsely identify my current version of npm.

So right now, for example, it falsely says that I have npm 5.6.0 and that I can upgrade to 5.8.0. I've had 5.8.0 for more than a week, but it keeps telling me to upgrade to it.

Has anyone tried clearing the npm cache. I played with it but it gives a warning that the cache is self-repairing and forces you to add `--force` to execute the command. I was worried about breaking something, so I've held off so far.

These are pretty basic bugs that get at npm's core functionality and purpose as a package manager. Is it time to switch to yarn? Is yarn noticeably less buggy than npm? npm was completely broken with a recent release of Node a few months ago – it wouldn't function, made Node useless for several days, maybe a couple of weeks. This is a surprisingly bad QA situation.
