### ISSUE TITLE
react3

### ISSUE THREAD

**Issue by Zhangzhenguo3352** [npm/npm#13436]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KamranMackey** [comment]
Lol, fill out your issue properly. Most of it is blank.

**Comment by KamranMackey** [comment]
Actually, all of it is blank.

**Comment by othiym23** [comment]
There's not enough information on this issue for the CLI team to figure out whether this is a support request, a bug, or a feature request, so I'm going to close it. If you're still having problems, open a new issue and fill out what information you can find. Thanks for your time!
