### ISSUE TITLE
The .cmd can't be run incorrectly.

### ISSUE THREAD

**Issue by smallyard** [npm/npm#13441]
#### I'm opening this issue because:

  npm is producing an incorrect install.
### The .cmd can't be run incorrectly.

install tianqi 

```
npm install tianqi -g
```

content of `tianqi.cmd`

```
"%~dp0\node_modules\tianqi\bin\tianqi"   %*

```

**Comment by yanxyz** [comment]
@smallyard  issue #6674 may help you
