### ISSUE TITLE
npm fail to install angular-QuickStart

### ISSUE THREAD

**Issue by hmuschett** [npm/npm#13443]
```console
$ npm install
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3

npm ERR! shasum check failed for C:\Users\Henry\AppData\Local\Temp\npm-3540-cfc8ec7c\registry.npmjs.org\core-js\-\core-js-2.4.1.tgz
npm ERR! Expected: 4de911e667b0eae9124e34254b53aea6fc618d3e
npm ERR! Actual:   3439c982ffa0e9ff7fa6bfa330d03a983cd2abf2
npm ERR! From:     http://registry.npmjs.org/core-js/-/core-js-2.4.1.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

#####

 - Windows, 
 - Network issues:
   - Geographic location where npm was run:
   - [ x] I use a proxy to connect to the npm registry.
   - [ x] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [x ] I don't use a proxy, but have limited or unreliable internet access.

my conection is for monden to 49k/s

**Comment by KenanY** [comment]
@hmuschett Have you tried running `npm cache clean`?

**Comment by vsmahesh** [comment]
Facing similar problem in Ubuntu 16.04. 

Initially shasum check failed for /tmp/npm-9740-f734db27/registry.npmjs.org/_40angular/compiler/-/compiler-2.0.0-rc.4.tgz

As you mentioned, I tried cleaning the cache. But now it is showing the same for forms
~/projects/angularjs/quickstart$ npm install
npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2

npm ERR! shasum check failed for /tmp/npm-9843-52fd7765/registry.npmjs.org/_40angular/forms/-/forms-0.2.0.tgz
npm ERR! Expected: fc5d41f16b9f561cb322255626428045f7d14cf9
npm ERR! Actual:   9cefbd239f539f98af4045ce796720da92ef807a
npm ERR! From:     https://registry.npmjs.org/@angular/forms/-/forms-0.2.0.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

Please see the log file - 
[npm-debug.txt](https://github.com/npm/npm/files/397020/npm-debug.txt)

**Comment by vsmahesh** [comment]
Working fine after executing `npm install npm -g`

**Comment by KenanY** [comment]
Closing due to no response from @hmuschett. Can reopen if this is still an issue for them.
