### ISSUE TITLE
npm test will not execute scripts (any version)

### ISSUE THREAD

**Issue by jackcviers** [npm/npm#13449]
#### I'm opening this issue because:
- [x] npm is doing something I don't understand.
#### What's going wrong?

`npm test` and `npm run-script name` and `npm run name` will not execute the commands in `package.json scripts#name`. 
#### How can the CLI team reproduce the problem?

Given the following package.json

``` json
{
  "name": "npm_bug",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"hi\""
  },
  "author": "",
  "license": "ISC"
}
```

When I run `npm test` on the bash cli on Ubuntu 14.04.1 (Linux jv12393-VirtualBox 3.19.0-59-generic #66~14.04.1-Ubuntu SMP Fri May 13 17:27:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux)

Then the following output is produced:

``` bash
npm test

> node_testing@1.0.0 test /home/jv12393/Documents/JohnDeere/node_testing
> echo "hi"




```

and the `npm-debug.log` contains:

``` log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'test' ]
2 info using npm@2.15.8
3 info using node@v4.4.7
4 verbose run-script [ 'pretest', 'test', 'posttest' ]
5 info pretest node_testing@1.0.0
6 info test node_testing@1.0.0
7 verbose unsafe-perm in lifecycle true
8 verbose stack Error: spawn ELOOP
8 verbose stack     at exports._errnoException (util.js:873:11)
8 verbose stack     at ChildProcess.spawn (internal/child_process.js:298:11)
8 verbose stack     at exports.spawn (child_process.js:362:9)
8 verbose stack     at spawn (/usr/lib/node_modules/npm/lib/utils/spawn.js:7:13)
8 verbose stack     at runCmd_ (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:211:14)
8 verbose stack     at runCmd (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:176:5)
8 verbose stack     at runPackageLifecycle (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:138:3)
8 verbose stack     at Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
8 verbose stack     at LOOP (/usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
8 verbose stack     at chain (/usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
9 verbose cwd /home/jv12393/Documents/JohnDeere/node_testing
10 error Linux 3.19.0-59-generic
11 error argv "/usr/bin/nodejs" "/usr/bin/npm" "test"
12 error node v4.4.7
13 error npm  v2.15.8
14 error code ELOOP
15 error errno ELOOP
16 error syscall spawn
17 error spawn ELOOP
18 error If you need help, you may report this error at:
18 error     <https://github.com/npm/npm/issues>
19 verbose exit [ 1, true ]
```

And the exit status is 1

But I expected

``` bash
hi
```

and an exit status of 0.

I have attempted this with npm 3.x as well and node versions through latest and get the same result. `npm run name` likewise fails.
### supporting information:
- `npm -v` prints: `2.15.8`
- `node -v` prints: `v4.4.7`
- `npm config get registry` prints: `https://registry.npmjs.org/`
- Windows, OS X, or Linux?: Linux
- Network issues:
  - Geographic location where npm was run: Des Moines, Iowa
  - [x] I use a proxy to connect to the npm registry.
  - [x] I use a proxy to connect to the web.
  - [ ] I use a proxy when downloading Git repos.
  - [ ] I access the npm registry via a VPN
  - [ ] I don't use a proxy, but have limited or unreliable internet access.
- Container:
  - [x] I develop using Vagrant on Windows.
  - [ ] I develop using Vagrant on OS X or Linux.
  - [ ] I develop / deploy using Docker.
  - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
FWIW I cannot reproduce this with Node.js v6.3.0, `npm@3.10.6` on Linux. Considering how prevalent `"scripts"` are in the ecosystem and the lack of anyone else reporting this same issue, I guess this is caused by your environment somehow. Not sure how to debug this though :(

**Comment by jackcviers** [comment]
@KenanY -- yeah, I'm unsure as well. I've never seen ELOOP before. I've tried with deb install and nvm installed node. I guess I could build from source, but I haven't had to do that since 0.10. It is particular to this machine -- my home laptop hums along happily.
