### ISSUE TITLE
npm update an outdated global module fails.

### ISSUE THREAD

**Issue by rpkoller** [npm/npm#13458]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [x] npm is producing an incorrect install.
- [ ] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
#### What's going wrong?

I've updated node to version 6.3.1 via homebrew. Then i ran `npm outdated -global --long --depth=0` which outputted: 

```
Package  Current  Wanted  Latest  Location  Package Type
csslint   0.10.0   1.0.2   1.0.2            dependencies
```

then i ran `npm -global update csslint` and got the following output: 

```
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/6.3.1/bin/node" "/usr/local/bin/npm" "-global" "update" "csslint"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! path /Users/myuser/.npm_global/bin/csslint
npm ERR! code EEXIST

npm ERR! Refusing to delete /Users/myuser/.npm_global/bin/csslint: ../lib/node_modules/csslint/cli.js symlink target is not controlled by npm /Users/myuser/.npm_global
npm ERR! File exists: /Users/myuser/.npm_global/bin/csslint
npm ERR! Move it away, and try again.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/myuser/npm-debug.log
```

if i run `npm list -g --depth=0` csslint is missing now.  
#### How can the CLI team reproduce the problem?

there was no npm-debug.log created?!
### supporting information:
- `npm -v` prints: 3.10.3
- `node -v` prints: v6.3.1
- `npm config get registry` prints: https://registry.npmjs.org/
- Windows, OS X, or Linux?: OSX 
      `./.npmrc` contains the following line `prefix = ${HOME}/.npm_global`
- Network issues:
  - Geographic location where npm was run:
  - [ ] I use a proxy to connect to the npm registry.
  - [ ] I use a proxy to connect to the web.
  - [ ] I use a proxy when downloading Git repos.
  - [ ] I access the npm registry via a VPN
  - [ ] I don't use a proxy, but have limited or unreliable internet access.
- Container:
  - [ ] I develop using Vagrant on Windows.
  - [ ] I develop using Vagrant on OS X or Linux.
  - [ ] I develop / deploy using Docker.
  - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by bancer** [comment]
I have a similar story:
```
sudo npm install -g csslint
npm ERR! Linux 3.13.0-91-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "csslint"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! path /usr/local/bin/csslint
npm ERR! code EEXIST

npm ERR! Refusing to delete /usr/local/bin/csslint: ../lib/node_modules/csslint/cli.js symlink target is not controlled by npm /usr/local
npm ERR! File exists: /usr/local/bin/csslint
npm ERR! Move it away, and try again.
```

**Comment by peterankelein** [comment]
Same issue here.

**Comment by rpkoller** [comment]
thanks @peterankelein ... I've checked my `.npm_global/bin` and `.npm_global/lib`directories. in the lib folder the csslint folder was already removed completely by my `npm update -g csslint`. there is only the symlink left pointing to the none existing csslint folder in`.npm_global/lib/node_modules/`. But as shown in my initial post it seems some sort of access issue `symlink target is not controlled by npm /Users/myuser/.npm_global`. But i've done a `rm csslint` inside the bin folder and then redid a `npm install -g csslint`and the install worked flawlessly again.
