### ISSUE TITLE
Failed to create a NPM package，Why ?

### ISSUE THREAD

**Issue by clone123** [npm/npm#13455]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'publish' ]
2 info using npm@2.15.8
3 info using node@v4.4.7
4 verbose publish [ '.' ]
5 silly cache add args [ '.', null ]
6 verbose cache add spec .
7 silly cache add parsed spec Result {
7 silly cache add   raw: '.',
7 silly cache add   scope: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: '.',
7 silly cache add   spec: 'D:\\npmProject\\clone',
7 silly cache add   type: 'directory' }
8 verbose addLocalDirectory C:\Users\huanghuanhuan\AppData\Roaming\npm-cache\comefrom\1.0.0\package.tgz not in flight; packing
9 verbose correctMkdir C:\Users\huanghuanhuan\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
10 verbose tar pack [ 'C:\\Users\\huanghuanhuan\\AppData\\Roaming\\npm-cache\\comefrom\\1.0.0\\package.tgz',
10 verbose tar pack   'D:\\npmProject\\clone' ]
11 verbose tarball C:\Users\huanghuanhuan\AppData\Roaming\npm-cache\comefrom\1.0.0\package.tgz
12 verbose folder D:\npmProject\clone
13 info prepublish comefrom@1.0.0
14 verbose addLocalTarball adding from inside cache C:\Users\huanghuanhuan\AppData\Roaming\npm-cache\comefrom\1.0.0\package.tgz
15 verbose correctMkdir C:\Users\huanghuanhuan\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
16 silly cache afterAdd comefrom@1.0.0
17 verbose afterAdd C:\Users\huanghuanhuan\AppData\Roaming\npm-cache\comefrom\1.0.0\package\package.json not in flight; writing
18 verbose correctMkdir C:\Users\huanghuanhuan\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
19 verbose afterAdd C:\Users\huanghuanhuan\AppData\Roaming\npm-cache\comefrom\1.0.0\package\package.json written
20 silly publish { name: 'comefrom',
20 silly publish   version: '1.0.0',
20 silly publish   description: 'create a npm package play play !',
20 silly publish   main: 'comefrom.js',
20 silly publish   scripts: { test: 'echo "Error: no test specified" && exit 1' },
20 silly publish   author: { name: 'clone123' },
20 silly publish   address: 'https://github.com/clone123',
20 silly publish   license: 'ISC',
20 silly publish   readme: 'ERROR: No README data found!',
20 silly publish   _id: 'comefrom@1.0.0',
20 silly publish   _shasum: '072667ae9f0559d2aead33f6fc1d7f624053c7f0',
20 silly publish   _from: '.' }
21 verbose getPublishConfig undefined
22 silly mapToRegistry name comefrom
23 silly mapToRegistry using default registry
24 silly mapToRegistry registry http://registry.npm.taobao.org/
25 silly mapToRegistry data Result {
25 silly mapToRegistry   raw: 'comefrom',
25 silly mapToRegistry   scope: null,
25 silly mapToRegistry   name: 'comefrom',
25 silly mapToRegistry   rawSpec: '',
25 silly mapToRegistry   spec: 'latest',
25 silly mapToRegistry   type: 'tag' }
26 silly mapToRegistry uri http://registry.npm.taobao.org/comefrom
27 verbose publish registryBase http://registry.npm.taobao.org/
28 silly publish uploading C:\Users\huanghuanhuan\AppData\Roaming\npm-cache\comefrom\1.0.0\package.tgz
29 verbose request uri http://registry.npm.taobao.org/comefrom
30 verbose request sending authorization for write operation
31 info attempt registry request try #1 at 15:37:23
32 verbose request id 0285db19d0f91269
33 http request PUT http://registry.npm.taobao.org/comefrom
34 http 403 http://registry.npm.taobao.org/comefrom
35 verbose headers { server: 'nginx/1.4.6 (Ubuntu)',
35 verbose headers   date: 'Fri, 22 Jul 2016 07:37:23 GMT',
35 verbose headers   'content-type': 'application/json; charset=utf-8',
35 verbose headers   'transfer-encoding': 'chunked',
35 verbose headers   connection: 'keep-alive',
35 verbose headers   'x-readtime': '7',
35 verbose headers   'content-encoding': 'gzip' }
36 verbose request invalidating C:\Users\huanghuanhuan\AppData\Roaming\npm-cache\registry.npm.taobao.org\comefrom on PUT
37 error publish Failed PUT 403
38 verbose stack Error: no_perms Private mode enable, only admin can publish this module: comefrom
38 verbose stack     at makeError (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:264:12)
38 verbose stack     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:252:14)
38 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:178:7
38 verbose stack     at Gunzip.onEnd (zlib.js:227:5)
38 verbose stack     at emitNone (events.js:72:20)
38 verbose stack     at Gunzip.emit (events.js:166:7)
38 verbose stack     at endReadableNT (_stream_readable.js:921:12)
38 verbose stack     at nextTickCallbackWith2Args (node.js:442:9)
38 verbose stack     at process._tickCallback (node.js:356:17)
39 verbose statusCode 403
40 verbose pkgid comefrom
41 verbose cwd D:\npmProject\clone
42 error Windows_NT 6.1.7601
43 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "publish"
44 error node v4.4.7
45 error npm  v2.15.8
46 error code E403
47 error no_perms Private mode enable, only admin can publish this module: comefrom
48 error If you need help, you may report this error at:
48 error     <https://github.com/npm/npm/issues>
49 verbose exit [ 1, true ]

**Comment by clone123** [comment]
ok , solved !

**Comment by KenanY** [comment]
Closing as resolved then :)
