### ISSUE TITLE
cb is not a function error

### ISSUE THREAD

**Issue by adrian-nitu-92** [npm/npm#13457]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Running the latest node produces on a npm install the following error, several times:

```
npm ERR! cb is not a function
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 4.2.0-27-generic
npm ERR! argv "/home/lp-jenkins/workspace/NovaNodeJS_nightly/builds/2016-07-22_11-47-16/node/install/usr/local/bin/node" "/home/lp-jenkins/workspace/NovaNodeJS_nightly/builds/latest/node/install/usr/local/bin/npm" "install"
npm ERR! node v7.0.0-pre
npm ERR! npm  v3.10.3
```

### supporting information:

 - `npm -v` prints: 3.10.3
 - `node -v` prints: v7.0.0-pre
 - `npm config get registry` prints:
 - Windows, OS X, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [x] I use a proxy to connect to the npm registry.
   - [x] I use a proxy to connect to the web.
   - [x] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by wanderer** [comment]
I have the same issue

**Comment by wanderer** [comment]
This commit is the breaking change https://github.com/nodejs/node/commit/9359de9dd2eae06ed5afcb75dad9bd4c466eb69d

**Comment by liuestc** [comment]
I have the same issue  cb is not function  nodejs/node@9359de9

**Comment by jfiamor** [comment]
same issue here

**Comment by masonicGIT** [comment]
Same issue on npm version 3.10.3

**Comment by luanshixinan** [comment]
Same issue
`root@debian:~# npm install express -g 
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "express" "-g"
npm ERR! node v7.0.0-pre
npm ERR! npm  v3.10.3

npm ERR! cb is not a function
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
`

**Comment by hsa1280** [comment]
same issue here, 
npm ERR! cb is not a function
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 4.4.11-23.53.amzn1.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.0.0-pre
npm ERR! npm  v3.10.3

**Comment by erwinwolff** [comment]
I got the same:

npm install -g less

npm ERR! Linux 2.6.34.14
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "less"
npm ERR! node v7.0.0-pre
npm ERR! npm  v3.10.3

npm ERR! cb is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 2.6.34.14
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "less"
npm ERR! node v7.0.0-pre
npm ERR! npm  v3.10.3

**Comment by crunch013** [comment]
Same here, is there a stable version where we can rollback to get it working fine?

**Comment by zkat** [comment]
It looks like https://github.com/nodejs/node/pull/7846 was merged into `master`, so `node@7` users should stop seeing this. Closing this, and thanks for the report!

**Comment by jfiamor** [comment]
I did an npm update and I still can't use npm to install any packages.

**Comment by zkat** [comment]
@jfiamor can you provide an `npm-debug.log`?

**Comment by jfiamor** [comment]
I killed the red hat server I was using and use ubuntu, I don't have that problem anymore

**Comment by chensjing** [comment]
I use ubuntu and want to install hexo,but then meet the error.how do I deal with it ?
sudo npm i -g hexo
```
npm WARN deprecated swig@1.4.2: This package is no longer maintained
npm WARN optional Skipping failed optional dependency /hexo/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.1
npm ERR! Linux 4.4.0-21-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "i" "-g" "hexo"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! path /usr/local/bin/hexo
npm ERR! code EEXIST

npm ERR! Refusing to delete /usr/local/bin/hexo: ../lib/node_modules/hexo-cli/bin/hexo symlink target is not controlled by npm /usr/local
npm ERR! File exists: /usr/local/bin/hexo
npm ERR! Move it away, and try again.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/chensjing/npm-debug.log
```

**Comment by zkat** [comment]
@chensjing you installed hexo some other way. You'll need to move or remove `/usr/local/bin/hexo`. Just like the message says.

**Comment by chensjing** [comment]
thank you for your answer.

**Comment by mazer-rakham** [comment]
Just fyi in-case someone else runs into this. if you are using browser-sync with localhost php proxy, if you have an out of place forward slash in your file naming it will throw this error. Example:
`<link href="/css/mainstylesheet.css blah blah`
will throw error but 
`<link href="css/mainstylesheet.css blah`
does not.
