### ISSUE TITLE
I have a dropdown where ng-repeat is being used to populate the options. I am not able to save the values selected in dropdown to Database using IE while using other browsers I am able to.

### ISSUE THREAD

**Issue by ayushgupta29** [npm/npm#13469]
<select ng-model="choice.questionanaswerid" ng-options="choice in choices">
{{choice}}
</select>

**Comment by KenanY** [comment]
@ayushgupta29 Sorry, but this does not sound like an issue with `npm` to me. This issue tracker is for bugs and feature requests for `npm` the package manager. I suggest you try asking other AngularJS users, like those in the `#angularjs` channel on freenode. Good luck!
