### ISSUE TITLE
npm install -g eslint .... at Windows 10

### ISSUE THREAD

**Issue by SnowBG** [npm/npm#13460]
#### I'm opening this issue because:

I'm learning about Meteor and I'm following it's guide from:
[Meteor's guide](https://guide.meteor.com/code-style.html)
At the ESlint topic, I cannot go foward.
#### What's going wrong?

The installations returns a lot of errors (please see the **_attached log_**).
Seems like something is missing.
#### How can the CLI team reproduce the problem?

Using the Windows 10.0.10586 (**cmd shell as administrator**) I'm trying to install the ESLint this way:

`meteor npm install -g eslint`

The folder is c:\myapp\

That's the error:

```
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Users\\rafael\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.3.2_4\\mt-os.windows.x86_32\\dev_bundle\\bin\\\\node.exe" "C:\\Users\\rafael\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.3.2_4\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "eslint"
npm ERR! node v0.10.43
npm ERR! npm  v2.14.22
npm ERR! path C:\myapp\npm-debug.log
npm ERR! code EPERM
npm ERR! errno 50

npm ERR! Error: EPERM, rename 'C:\myapp\npm-debug.log'
npm ERR!  { [Error: EPERM, rename 'C:\myapp\npm-debug.log'] errno: 50, code: 'EPERM', path: 'C:\\myapp\\npm-debug.log' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\myapp\npm-debug.log
```
### supporting information:
- `npm -v` prints: 2.14.22
- `node -v` prints: v0.10.43
- `npm config get registry` prints: https://registry.npmjs.org/

**Comment by mohamedhakika** [comment]
I have the similar issue so I'm looking for comments here to solve the problem..
