### ISSUE TITLE
Installing react-native package from npm error

### ISSUE THREAD

**Issue by BiggerGao** [npm/npm#13470]
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/Cellar/node/6.2.2/bin/node" "/usr/local/bin/npm" "install" "--save" "--save-exact" "react-native"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5

npm ERR! shasum check failed for /var/folders/qm/8szn0kgd13x6qlrwrcy9nvsh0000gn/T/npm-36829-d1f8518e/registry.npmjs.org/ua-parser-js/-/ua-parser-js-0.7.10.tgz
npm ERR! Expected: 917559ddcce07cbc09ece7d80495e4c268f4ef9f
npm ERR! Actual:   e093ec26585bcd50b134ef45aefecdfdfc219f9e
npm ERR! From:     https://registry.npmjs.org/ua-parser-js/-/ua-parser-js-0.7.10.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Echo/HelloWorld/npm-debug.log

`npm install --save --save-exact react-native` failed

**Comment by KenanY** [comment]
@BiggerGao Have you tried running `npm cache clean`?

**Comment by BiggerGao** [comment]
It's network problem.Because of Chinese GFW.
