### ISSUE TITLE
npm3 shrinkwrap not support latest semver well.

### ISSUE THREAD

**Issue by xuxin** [npm/npm#13496]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
shrinkwrap with devendencies semver latest goes wrong.

1、my package.json is like this:
```javascript
    {
         "dependencies": {
            "A": "^0.0.1"}}
``` 
the A package's dependencies is : 
```javascript
    {  
           "name": "A",  
           "version": "0.1.0",  
           "dependencies": { "B": "latest" } }
```    
 `npm install` build my node_module:
```
  └─┬   A@0.0.1
     ├── B@0.0.1
```
`npm shrinkwrap` get my shrinkwrap.json:
```javascript
{
  "dependencies": {
    "A": {
      "version": "0.0.1",
      "from": "A@>=0.0.1 <0.1.0",
      "resolved": "**** A-0.0.1.tgz"
    },
    "B":  {
      "version": "0.0.1",
      "from": "B@latest",
      "resolved": "**** A-0.0.1.tgz"
    }
    }
}
```
now ,everything is right.

2、 delete node_module dir and run `npm install` from npm-shrinkwrap.json again, my node_module become:
```
    ├─┬ A@0.0.1
    │  └──  B@0.0.1
    ├── B@0.0.1
```
and when I run `npm shrinkwrap`:
```javascript
{
  "dependencies": {
    "A": {
      "version": "0.0.1",
      "from": "A@>=0.0.1 <0.1.0",
      "resolved": "**** A-0.0.1.tgz",
      "dependencies": {
           "B":  {
          "version": "0.0.1",
          "from": "B@latest",
          "resolved": "**** A-0.0.1.tgz"}
        }
    }
    }
}
```
now the npm-shrinkwarp.json was changed.

3、remove node_module , and `npm install` the module goes **wrong**
```
    ├─┬ A@0.0.1
    │  └──  B@0.0.1
    ├── B@0.0.1  invalid
```
`npm ls` show: 
```
npm ERR! invalid: B@0.0.1 /node_modules/A/node_modules/B
```
`npm shrinkwrap` show like this:
```
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/xu/.nvm/versions/node/v4.4.6/bin/node" "/Users/xu/.nvm/versions/node/v4.4.6/bin/npm" "shrinkwrap"
npm ERR! node v4.4.6
npm ERR! npm  v3.10.5
npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! invalid: have B@0.0.1 (expected: latest) /node_modules/A/node_modules/B
```

### How can the CLI team reproduce the problem

1、`npm install` a package.json dependencies include a package which has latest semver dependencies, such as a package name [pm25](https://github.com/PaulGuo/PM25/blob/master/PM25-Cli/package.json) depend on latest pmx;
2、`npm shrinkwrap` get npm-shrinkwrap.json
3、`rm -rf node_modules` and then `npm install`
4、`npm shrinkwrap` get npm-shrinkwrap.json
5、`rm -rf node_modules` and then `npm install`
6、`npm ls` or `npm shrinkwrap` go error

### supporting information:

 - `npm -v` prints: 3.10.5
 - `node -v` prints: 4.4.6
 - `npm config get registry` prints: http://r.npm.sankuai.com/
 - Windows, OS X, or Linux?:  OS X

**Comment by shaunwarman** [comment]
Similar issue.. simple test:
###### npm@3.9.3

###### package.json `dependencies`
```
...
"dependencies": {
  "ascli": "~1"
}
```

###### npm-shrinkwrap.json
```
{
  "name": "test-npm",
  "version": "1.0.0",
  "dependencies": {
    "ascli": {
      "version": "1.0.0",
      "from": "ascli@>=1.0.0 <2.0.0",
      "resolved": "https://npm.paypal.com/ascli/-/ascli-1.0.0.tgz"
    },
    "colour": {
      "version": "0.7.1",
      "from": "colour@latest",
      "resolved": "https://npm.paypal.com/colour/-/colour-0.7.1.tgz"
    },
    "optjs": {
      "version": "3.2.2",
      "from": "optjs@latest",
      "resolved": "https://npm.paypal.com/optjs/-/optjs-3.2.2.tgz"
    }
  }
}
```

###### Produces
```
test-npm@1.0.0 /Users/swarman/Development/Source/test-npm
├─┬ ascli@1.0.0
│ ├── colour@0.7.1
│ └── optjs@3.2.2
├── colour@0.7.1 extraneous
└── optjs@3.2.2 extraneous
```

**Comment by danielb2** [comment]
Same issue with `3.10.5`

This is causing issues when doing an npm install to update packages. package.json is updated correctly however, there are `saveError`s occurring and the shrinkwrap file is not updating. 

`npm WARN saveError invalid: have @npme/whateverpackage@1.1.1 (expected: latest) `
