### ISSUE TITLE
Hostname/IP doesn't match certificate's altnames

### ISSUE THREAD

**Issue by garraxxi** [npm/npm#13490]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Hostname/IP doesn't match certificate's altnames: "Host: registry.npmjs.org. is not in the cert's altnames: DNS:a.sni.fastly.net, DNS:a.sni.global-ssl.fastly.net"

#### How can the CLI team reproduce the problem?

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'gulp' ]
2 info using npm@3.9.5
3 info using node@v6.2.2
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData gulp
8 silly fetchNamedPackageData gulp
9 silly mapToRegistry name gulp
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org./
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'gulp',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   name: 'gulp',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org./gulp
14 verbose request uri https://registry.npmjs.org./gulp
15 verbose request no auth needed
16 info attempt registry request try #1 at 8:18:31 PM
17 verbose request id 5c8baa003457a51a
18 http request GET https://registry.npmjs.org./gulp
19 info retry will retry, error on last attempt: Error: Hostname/IP doesn't match certificate's altnames: "Host: registry.npmjs.org. is not in the cert's altnames: DNS:a.sni.fastly.net, DNS:a.sni.global-ssl.fastly.net"
20 info attempt registry request try #2 at 8:18:47 PM
21 http request GET https://registry.npmjs.org./gulp
22 info retry will retry, error on last attempt: Error: Hostname/IP doesn't match certificate's altnames: "Host: registry.npmjs.org. is not in the cert's altnames: DNS:a.sni.fastly.net, DNS:a.sni.global-ssl.fastly.net"
23 info attempt registry request try #3 at 8:19:47 PM
24 http request GET https://registry.npmjs.org./gulp
25 silly fetchPackageMetaData Error: Hostname/IP doesn't match certificate's altnames: "Host: registry.npmjs.org. is not in the cert's altnames: DNS:a.sni.fastly.net, DNS:a.sni.global-ssl.fastly.net"
25 silly fetchPackageMetaData     at Object.checkServerIdentity (tls.js:203:15)
25 silly fetchPackageMetaData     at TLSSocket.<anonymous> (_tls_wrap.js:1066:29)
25 silly fetchPackageMetaData     at emitNone (events.js:86:13)
25 silly fetchPackageMetaData     at TLSSocket.emit (events.js:185:7)
25 silly fetchPackageMetaData     at TLSSocket._finishInit (_tls_wrap.js:584:8)
25 silly fetchPackageMetaData     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38)
25 silly fetchPackageMetaData  error for gulp { Error: Hostname/IP doesn't match certificate's altnames: "Host: registry.npmjs.org. is not in the cert's altnames: DNS:a.sni.fastly.net, DNS:a.sni.global-ssl.fastly.net"
25 silly fetchPackageMetaData     at Object.checkServerIdentity (tls.js:203:15)
25 silly fetchPackageMetaData     at TLSSocket.<anonymous> (_tls_wrap.js:1066:29)
25 silly fetchPackageMetaData     at emitNone (events.js:86:13)
25 silly fetchPackageMetaData     at TLSSocket.emit (events.js:185:7)
25 silly fetchPackageMetaData     at TLSSocket._finishInit (_tls_wrap.js:584:8)
25 silly fetchPackageMetaData     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38)
25 silly fetchPackageMetaData   reason: 'Host: registry.npmjs.org. is not in the cert\'s altnames: DNS:a.sni.fastly.net, DNS:a.sni.global-ssl.fastly.net',
25 silly fetchPackageMetaData   host: 'registry.npmjs.org.',
25 silly fetchPackageMetaData   cert:
25 silly fetchPackageMetaData    { subject:
25 silly fetchPackageMetaData       { C: 'US',
25 silly fetchPackageMetaData         ST: 'California',
25 silly fetchPackageMetaData         L: 'San Francisco',
25 silly fetchPackageMetaData         O: 'Fastly, Inc.',
25 silly fetchPackageMetaData         CN: 'a.sni.fastly.net' },
25 silly fetchPackageMetaData      issuer:
25 silly fetchPackageMetaData       { C: 'BE',
25 silly fetchPackageMetaData         O: 'GlobalSign nv-sa',
25 silly fetchPackageMetaData         CN: 'GlobalSign Organization Validation CA - SHA256 - G2' },
25 silly fetchPackageMetaData      subjectaltname: 'DNS:a.sni.fastly.net, DNS:a.sni.global-ssl.fastly.net',
25 silly fetchPackageMetaData      infoAccess: { 'CA Issuers - URI': [Object], 'OCSP - URI': [Object] },
25 silly fetchPackageMetaData      modulus: 'A6FE1CD0E3F40BA89041AE090698B12888F4FF265454BC2D074DDAB8A525E4B532BF56C66F07E1CBDDA18E63D0ED49316067694280F978A6DDED4F8A3AB1EB12BBCC5D395C92E096C55419479945382208F3601A96FCE9B7898DB31F204B0E3D3724E24A02282E133B1C410B0E55833BA970DDD3744692E2A1FD619C1839BA875BD2DA42E0A4AD93D8A6EB84891076BD331F08BEB68ED3F3722429F24B4547911CA14257578EF9B79FDF1B8450A93418BB8A82F3DC1F53BC99A26CD194FCE38BFA925A408FE81936AE2CD39A88E6561938E0B6E6549FED7153B1DD7371208C0737B75D160095849503A77C2F6BD9C82054F81A472DCB313401524997E8058809',
25 silly fetchPackageMetaData      exponent: '0x10001',
25 silly fetchPackageMetaData      valid_from: 'May 15 12:39:06 2015 GMT',
25 silly fetchPackageMetaData      valid_to: 'Jul 15 12:00:00 2018 GMT',
25 silly fetchPackageMetaData      fingerprint: '2B:66:72:35:93:F1:4B:91:BE:71:EC:F5:31:2E:37:38:1F:56:B7:72',
25 silly fetchPackageMetaData      ext_key_usage: [ '1.3.6.1.5.5.7.3.1', '1.3.6.1.5.5.7.3.2' ],
25 silly fetchPackageMetaData      serialNumber: '1121A309258243831351819422E26E4D85D4',
25 silly fetchPackageMetaData      raw: <Buffer 30 82 05 51 30 82 04 39 a0 03 02 01 02 02 12 11 21 a3 09 25 82 43 83 13 51 81 94 22 e2 6e 4d 85 d4 30 0d 06 09 2a 86 48 86 f7 0d 01 01 0b 05 00 30 66 ... > } }
26 silly rollbackFailedOptional Starting
27 silly rollbackFailedOptional Finishing
28 silly runTopLevelLifecycles Starting
29 silly runTopLevelLifecycles Finishing
30 silly install printInstalled
31 verbose stack Error: Hostname/IP doesn't match certificate's altnames: "Host: registry.npmjs.org. is not in the cert's altnames: DNS:a.sni.fastly.net, DNS:a.sni.global-ssl.fastly.net"
31 verbose stack     at Object.checkServerIdentity (tls.js:203:15)
31 verbose stack     at TLSSocket.<anonymous> (_tls_wrap.js:1066:29)
31 verbose stack     at emitNone (events.js:86:13)
31 verbose stack     at TLSSocket.emit (events.js:185:7)
31 verbose stack     at TLSSocket._finishInit (_tls_wrap.js:584:8)
31 verbose stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38)
32 verbose cwd /media/garraxxi/SP PHD U3/Desarrollo/MEAN/Natillera/dev
33 error Linux 4.4.0-31-generic
34 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "gulp"
35 error node v6.2.2
36 error npm  v3.9.5
37 error Hostname/IP doesn't match certificate's altnames: "Host: registry.npmjs.org. is not in the cert's altnames: DNS:a.sni.fastly.net, DNS:a.sni.global-ssl.fastly.net"
38 error If you need help, you may report this error at:
38 error     <https://github.com/npm/npm/issues>
39 verbose exit [ 1, true ]
```

### supporting information:

 - `npm -v` prints: 3.9.5
 - `node -v` prints:v6.2.2
 - `npm config get registry` prints:https://registry.npmjs.org./
 - Windows, OS X, or Linux?: Ubuntu 16.04
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [x] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by davisondan** [comment]
I am having the same issue

**Comment by davisondan** [comment]
Even though I had set strict-ssl=false in my local .npmrc file, I had to do "npm config set strict-ssl false" on the command line anyways.  And it worked for me.

**Comment by garraxxi** [comment]
@davisondan, I tried, but not worked. What I did was purged and reinstaled, but I must run commands with root permissions for global install.

**Comment by heijmans** [comment]
@garraxxi There is a dot at the end of your npm registry URL. This is probably causing the errors. The registry URL should be: `https://registry.npmjs.org/` instead of `https://registry.npmjs.org./`. You should fix this in your .npmrc which is probably in your home directory. You could also try running the following command:

    npm config set registry https://registry.npmjs.org/

**Comment by consoles** [comment]
@davisondan thank you thank you very much,it works.

**Comment by ketans207** [comment]
I am facing the same issue while connecting as a REST client implemented in Node JS with authentication and getting error as below:
**{ Error: self signed certificate in certificate chain
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:610:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38) code: 'SELF_SIGNED_CERT_IN_CHAIN' }**

Few required entries in .npmrc file are as below:
registry=https://registry.npmjs.org/
strict-ssl=false
cafile=<path of a file>

and also running command: npm config set strict-ssl false
but still getting this issue with my rest client which is implemented with Node JS as below.

var https = require('https');
var fs = require('fs');

var options = {
    host: '<hostname>',
    port: '<port>',
    path: '<path>',
    method: 'POST',
    headers: {
        'Content-Type': 'application/json',
        'Accept': 'application/json',
        'Authorization': '<UTF characters for username and password>',
    },
    ca: [ fs.readFileSync('<.jks file path>') ],
    checkServerIdentity: function (host, cert) {
        
        if (host != cert.subject.CN)
            return 'Incorrect server identity';// Return error in case of failed checking.
    },
     // rejectUnauthorized:false,
    body: '<DATA inside request BODY>'

};

var req =  https.request(options, function(res) {
    console.log('request function')
    console.log("Response: ", res);
    res.on('data', function(d) {
'' +
'?'    });
});

req.end();

req.on('error', function(e) {
    console.error(e);
});

Kindly suggest the solution.

**Comment by marcusaaronb** [comment]
How to fix?

npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "ant"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10

npm ERR! Hostname/IP doesn't match certificate's altnames: "Host: registry.npmjs.org. is not in the cert's altnames: DNS:*.smartdnsproxy.com, DNS:smartdnsproxy.com"
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by Butterfly** [comment]
@marcusaaronb  Your error message seems to contain the same error as [referenced in a comment above](https://github.com/npm/npm/issues/13490#issuecomment-247136535). If you run the following, it should show what is really in your configuration file(s):

`npm config get registry`

If that dot is showing when you do that, you'll need to correct that value. You can do that by running this:

`npm config set registry https://registry.npmjs.org/`

I'm able to run both of those commands from any directory, and it still works (in Debian/Buster, Linux).

PS I'm looking at my keyboard just now. That's probably a recurring error because the "." and "/" keys are sitting side by side on some, if not most or all, keyboards :smile: 

Updating this to add that I just test drove that observation by running:

`npm config set registry https://registry.npmjs.org.`

It let me do so with no error message. When I next run `npm config get registry`, it says:

`https://registry.npmjs.org./` :smile:

**Comment by marcusaaronb** [comment]
the error have show again :(
