### ISSUE TITLE
Improperly configured proxy settings

### ISSUE THREAD

**Issue by RSchlenker** [npm/npm#13508]
Hi all,
I am currently working from a Chinese Lab. Since I am working in China I have several issues with npm and it's repositories. As I already know, I needed to change the registry to a Chinese-compliant server, I chose to use taobao.org. My npm config is:

> ; cli configs
> user-agent = "npm/3.8.9 node/v6.2.0 linux x64"
> 
> userconfig /home/robin/.npmrc
> registry = "https://registry.npm.taobao.org/"
>  node bin location = /usr/local/bin/node
>  cwd = /home/robin
>  HOME = /home/robin

In the past, I had the need to setup some proxy servers to be able to access google and other repositories that's. Therefore I used the linux ssh cmd.

> ssh xxx.xxx.xxx.xxx -D 8080

Which would setup a proxy on localhost (127.0.0.1) on port 8080.
I tried to set this proxy also for the npm config file using

> npm config set proxy 127.0.0.1:8080

and also tried to use http_proxy instead of proxy.
Neither worked for me so I deleted the setting and tried to use npm without any proxy.
To ensure the availability of the registry I pinged them from my local machine and it was available for me.
So the next step for me was, to run any npm command e.g. 'npm install' with the '-dd' flag to get behind the issue. For this reason, I shut down my proxy command since I also removed the proxy settings. I could see that npm still tried to access 127.0.0.1 even if I hadn't any proxy set in the config file. The debug-log file will be part of this issue, the file called 'access_without_proxy'.
The next step was, to run the proxy on my local machine since npm tried to access it even without any setting. This time, npm seems to directly access https://registry.npm.taobao.org but it is still unable to retrieve the data. The debug logfile is attached in the file 'access_with_proxy'.
I also pinged the domain with from my proxy server and it was available as well.

Do you know about this issue? I think at first, without any proxy config setting, npm should not try to access 127.0.0.1:8080. The second thing is, that even with accessing the proxy I couldnt' retrieve the files.

Kind regards,
Robin

[access_with_proxy.txt](https://github.com/npm/npm/files/387748/access_with_proxy.txt)
[access_without_proxy.txt](https://github.com/npm/npm/files/387749/access_without_proxy.txt)

**Comment by RSchlenker** [comment]
Ok, there is an update now:
I can circumvent the usage of the proxy by using the --no-proxy flag.
But nevertheless, how can I delete this automated usage of a proxy which shouldn't be configured anymore?

**Comment by bensleveritt** [comment]
Do you have a proxy set up in your environment variables?

`echo $http_proxy`, or `echo $https_proxy`

**Comment by RSchlenker** [comment]
I had $http_proxy set in my environment.
I just removed all proxy variables and placed this in the .bashrc file to ensure the changes are permanently.
But the problem still occurs. So when I add the '--no-proxy' tag to the end of my npm request, everything works fine but otherwise it won't do anything.
