### ISSUE TITLE
NPM ERR

### ISSUE THREAD

**Issue by anhpha90** [npm/npm#13503]
#### I'm opening this issue because:

 npm ERR:
The screen like this when I type npm start:

```
$ npm start
npm ERR! Windows_NT 5.1.2600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8

npm ERR! missing script: start
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Node JS\Ser\npm-debug.log
```

And before when I create server by " npm init" , it's not correct working. I enter server name, description, license(UNLICENSED)...end the command line display " Is this ok?(yes)" i type "yes" and enter but nothing happen.

**Comment by KenanY** [comment]
@anhpha90 Do you have a `"start"` script defined in your `package.json`?

**Comment by KenanY** [comment]
Closing as abandoned.
