### ISSUE TITLE
Refusing to delete entire project

### ISSUE THREAD

**Issue by sebsylvester** [npm/npm#13500]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?
npm fails to delete an empty package (even with --force), that I later published with a different name. The package is empty and useless, so I would like to remove it from the registry.

#### How can the CLI team reproduce the problem?
[The gist of debug log](https://gist.github.com/sebsylvester/59aaef4793689d94cd2f0c35a01203a8)

### supporting information:
 - `npm -v` prints: 3.10.5
 - `node -v` prints: 6.3.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X, or Linux?: OS X

**Comment by KenanY** [comment]
@sebsylvester Have you tried emailing `support@npmjs.com`?

**Comment by sebsylvester** [comment]
I just did : )
No response yet

**Comment by ehsalazar** [comment]
We've been in communication with @sebsylvester and have successfully unpublished the package. 

>We've made some recent changes to the unpublish policy which you can learn more about here: http://blog.npmjs.org/post/141905368000/changes-to-npms-unpublish-policy

>While `parse-server-mailgunner@2.0.0` was less than 24 hours old, the unpublish failed from your end due to a bug on our end. The check for package age got caught on the older, already unpublished versions.

Closing this issue as resolved. : )
