### ISSUE TITLE
Add a command that would add package(s) to package.json but not install them

### ISSUE THREAD

**Issue by artforlife** [npm/npm#13517]
#### I'm opening this issue because:
- [ ] Other (_see below for feature requests_):
#### What's the feature?

Add a command that would add package(s) to package.json but not install them.
#### What problem is the feature intended to solve?

When preparing repositories for sharing with others, it is convenient to have packages added but not installed so that node_modules directory is not created and dragged along.
#### Is the absence of this feature blocking you or your team? If so, how?

No. Just a matter of convenience.
#### Is this feature similar to an existing feature in another tool?

Not sure if Bower has this or not.
#### Is this a feature you're prepared to implement, with support from the npm CLI team?

YES!
-->

**Comment by tk120404** [comment]
👍
