### ISSUE TITLE
npm list command doesn't show all extraneous packages

### ISSUE THREAD

**Issue by e-cloud** [npm/npm#13512]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [ ] npm is producing an incorrect install.
- [x] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
#### What's going wrong?

Firstly, i install some dependencies manually. Then, i run `npm ls --depth 0`. Some of the manual installed packages show as extraneous. But some of them don't show as anything at all.
#### How can the CLI team reproduce the problem?

you can simply reproduce the problem within a npm package repo or an empty folder

```
npm init
npm i angular-ladda ladda
npm ls --depth 0
```

The result is `angular-ladda` shows up, but no `ladda`.

Besides, running through npm inner api shows the same situation.
### supporting information:
- `npm -v` prints: 3.10.6
- `node -v` prints: 6.3.1
- Windows, OS X, or Linux?: linux

**Comment by KenanY** [comment]
But if `ladda` is a dependency of `angular-ladda`, should it really be considered "extraneous" here?

**Comment by e-cloud** [comment]
this is just one simple usecase.

let's add one string: (Example 1)
```
npm i angular angular-ladda ladda
npm ls --depth 0
```
this time `angular` and  `angular-ladda` show as extraneous.

> PS: `angular` is `peerDependency` of `angular-ladda`

However, Consider this one: (Example 2)
In a project, `angular` and `angular-ui-router` are manually installed.
`npm ls --depth 0` just shows the later one. 
Because `angular-ui-router` specifies `angular` as dependency.

If `angular-ladda` is included too, the behavior of #Example1 is gone. And `angular` never show up again.

Although this situation might be minor, but it may give users a more clear view of extraneous packages, with the potential proper output.
