### ISSUE TITLE
Fail npm install -g cordova

### ISSUE THREAD

**Issue by Xav20** [npm/npm#13514]
#### I'm opening this issue because:

Hi ! Npm fail to install cordova. (I wanted to do an ionic platform add android, but it failed.)
I already have reinstall NodeJs and try a "npm cache clean" but nothing more.
Log attached. 
[npm-debug.txt](https://github.com/npm/npm/files/388877/npm-debug.txt)

**Cmder**

``` console
> npm install -g cordova
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
C:\Users\Boris\AppData\Roaming\npm
`-- (empty)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Boris\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.5
npm ERR! path C:\Users\Boris\AppData\Roaming\npm\node_modules\.staging\abbrev-25fca8b7
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\Boris\AppData\Roaming\npm\node_modules\.staging\abbrev-25fca8b7' -> 'C:\Users\Boris\AppData\Roaming\npm\node_modules\cordova\node_modules\npm\node_modules\abbrev'
npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\Boris\AppData\Roaming\npm\node_modules\.staging\abbrev-25fca8b7' -> 'C:\Users\Boris\AppData\Roaming\npm\node_modules\cordova\node_modules\npm\node_modules\abbrev'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     c:\Ionic\npm-debug.log
npm ERR! code 1
```
### supporting information:
- `npm -v` prints: 3.10.5
- `node -v` prints: v6.3.1
- `npm config get registry` prints: https://registry.npmjs.org/
- Windows, OS X, or Linux?: Windows 10

**Comment by s-panferov** [comment]
I see the same error with node_modules/.staging on npm@3.10.3 while trying to install a package where all dependencies are bundled. npm@2.14.12 works good on the same package.

It looks like that node don't write anything into .staging folder and then tries to mv things outside.

Looks related #13528

**Comment by rmg** [comment]
Same as #11265 ?

**Comment by nian1123** [comment]
same error  , how to fix it

**Comment by legodude17** [comment]
Try updating `npm` to the latest version.
