### ISSUE TITLE
EEXIST errno -17

### ISSUE THREAD

**Issue by Istar-Eldritch** [npm/npm#13529]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [x] npm is producing an incorrect install.
- [x] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
#### What's going wrong?

Npm 3 won't install dependencies in Docker for OSX if node_modules is in a volume. 
Workaround: [Comment by @jfedyczak ](https://github.com/npm/npm/issues/13529#issuecomment-236388736)

```
64164 error Linux 4.4.15-moby
64165 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "i"
64166 error node v6.2.2
64167 error npm  v3.9.5
64168 error path /opt/node_modules/agent-base/node_modules/.bin
64169 error code EEXIST
64170 error errno -17
64171 error syscall mkdir
64172 error EEXIST: file already exists, mkdir '/opt/node_modules/agent-base/node_modules/.bin'
64173 error File exists: /opt/node_modules/agent-base/node_modules/.bin
64174 error Move it away, and try again.
64175 verbose exit [ -17, true ]
```
#### How can the CLI team reproduce the problem?

Using docker on OSX, since yesterday, 29 July 2016, a bunch of dependencies that use to install normally started throwing this bizarre error.
I tried using different versions the node container (https://hub.docker.com/_/node/. `6.2.2`, `6.3.0`, `latest`, in all of them the error happens.
Current docker version: (1.12.0, build 8eab29e)

[npm-debug.log](https://gist.github.com/Istar-Eldritch/7c7eaee7199e2a9d34dc818daded9d2c#file-npm-debug-log)
### supporting information:
- `npm -v` prints: `3.9.5`, `3.10.3`
- `node -v` prints: `6.2.2`, `6.3.1`
- `npm config get registry` prints:
- Windows, OS X, or Linux?: Linux on Docker (OSX)
- Network issues:
  - Geographic location where npm was run: UK
  - [ ] I use a proxy to connect to the npm registry.
  - [ ] I use a proxy to connect to the web.
  - [ ] I use a proxy when downloading Git repos.
  - [ ] I access the npm registry via a VPN
  - [ ] I don't use a proxy, but have limited or unreliable internet access.
- Container:
  - [ ] I develop using Vagrant on Windows.
  - [ ] I develop using Vagrant on OS X or Linux.
  - [x] I develop / deploy using Docker.
  - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by jfedyczak** [comment]
Same here. After downgrading to npm2 it works.

**Comment by Istar-Eldritch** [comment]
@jfedyczak Do you know if this is happening only in the OSX version of Docker?

**Comment by jfedyczak** [comment]
@Istar-Eldritch 
> Do you know if this is happening only in the OSX version of Docker?

I've just tried it on DigitalOcean droplet and it worked fine with npm 3.

This suggests OS X specific issue...

**Comment by jfedyczak** [comment]
@Istar-Eldritch 

Also, after removing volume from docker container and injecting the code with `ADD` in `Dockerfile`, npm3 works fine. I believe docker for mac file sharing it is to blame..

**Comment by jfedyczak** [comment]
@Istar-Eldritch 

I've found a workaround. I've excluded `node_modules` folder from shared folders using [this solution](http://stackoverflow.com/a/37898591/3443194).

**Comment by Istar-Eldritch** [comment]
@jfedyczak That works like a charm.
Yes, something I didn't mention before and it was obviously important is that I was using docker volumes. 

I'm updating the first comment, to state it.

Thank you very much!

**Comment by diegodfsd** [comment]
@Istar-Eldritch @jfedyczak I know that not always is possible use it but I solved this problem installing the packages with --no-bin-links flag. I'm also using docker on OSX

**Comment by mxl** [comment]
@diegodfsd Thanks for workaround. I had to repeat `npm install --no-bin-links` several times until it stopped to throw `Maximum call stack size exceeded` (see https://github.com/npm/npm/issues/10776).
