### ISSUE TITLE
Maximum call stack size exceeded on --save

### ISSUE THREAD

**Issue by peterhn** [npm/npm#13527]
#### I'm opening this issue because:
- [x] npm is crashing.
- [x] npm is producing an incorrect install.
  - [ ] Other (_see below for feature requests_):
  - [ ] npm is doing something I don't understand.
#### What's going wrong?

Whenever I add --save arg on npm install, I get this error message:

`npm ERR! Darwin 15.4.0`
`npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "react-native-scrollable-tab-view@0.5.2" "--save"`
`npm ERR! node v6.0.0`
`npm ERR! npm  v3.10.6`

`npm ERR! Maximum call stack size exceeded`
`npm ERR!` 
`npm ERR! If you need help, you may report this error at:`
`npm ERR!     <https://github.com/npm/npm/issues>`

`npm ERR! Please include the following file with any support request:`
`npm ERR!     /Users/peter/xxx/npm-debug.log`
#### How can the CLI team reproduce the problem?

Add --save to any npm install

### supporting information:
- `npm -v` prints: 3.10.6
- `node -v` prints: v6.0.0
- `npm config get registry` prints: https://registry.npmjs.org/
- Windows, OS X, or Linux?: OSX OSX
- Network issues:
  - Geographic location where npm was run: California
  - [ ] I use a proxy to connect to the npm registry.
  - [ ] I use a proxy to connect to the web.
  - [ ] I use a proxy when downloading Git repos.
  - [ ] I access the npm registry via a VPN
  - [ ] I don't use a proxy, but have limited or unreliable internet access.
- Container:
  - [ ] I develop using Vagrant on Windows.
  - [ ] I develop using Vagrant on OS X or Linux.
  - [ ] I develop / deploy using Docker.
  - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by smikes** [comment]
Thanks for reporting this!

Unfortunately, I cannot reproduce this on my machine.

npm i --save react-native-scrollable-tab-view@0.5.2
<succeeds>
when I use node v6.0.0 and npm 3.10.6

There are some known stack overrun issues, and this might be related (see eg https://github.com/npm/npm/issues/9224 )

For the moment, can you work around it if you don't do "--save" but instead update package.json manually?  I know it's less than ideal but it would be useful to know if it's a functioning workaround.

**Comment by Kovensky** [comment]
Alternatively, revert to 3.10.5

**Comment by mgol** [comment]
It's happening for me as well with npm 3.10.6. It works fine with npm 3.10.5.

I can upload the `npm-debug.log` somewhere but what would the best place? (IMO the error message should guide users a little more, "include the following file" is not the best message when it's virtually impossible to include the file because it's way too large).
