### ISSUE TITLE
NPM + Docker Compose w/Mounted Volume + Symlinked node_modules = Error

### ISSUE THREAD

**Issue by phobetron** [npm/npm#13520]
I'm currently running my project under Docker on OSX using docker-compose to mount my working directory to the project's container for live updates during development. To facilitate better layer caching, I've symlinked my local `node_modules` directory to an `/install/node_modules` directory within the container's filesystem. During the build process, modules install properly as expected, and everything works. However, if I then attempt to perform `docker-compose run app npm install --save-dev *any package*` within the container using docker-compose, I receive the following error:

```
153 verbose stack RangeError: Maximum call stack size exceeded
153 verbose stack     at Link.hasOwnProperty (native)
153 verbose stack     at isArguments (/usr/lib/node_modules/npm/node_modules/aproba/index.js:4:47)
153 verbose stack     at Array.types.A (/usr/lib/node_modules/npm/node_modules/aproba/index.js:9:68)
153 verbose stack     at types.O (/usr/lib/node_modules/npm/node_modules/aproba/index.js:13:85)
153 verbose stack     at module.exports (/usr/lib/node_modules/npm/node_modules/aproba/index.js:30:10)
153 verbose stack     at flatNameFromTree (/usr/lib/node_modules/npm/lib/install/deps.js:475:3)
153 verbose stack     at flatNameFromTree (/usr/lib/node_modules/npm/lib/install/deps.js:477:14)
153 verbose stack     at flatNameFromTree (/usr/lib/node_modules/npm/lib/install/deps.js:477:14)
153 verbose stack     at flatNameFromTree (/usr/lib/node_modules/npm/lib/install/deps.js:477:14)
153 verbose stack     at flatNameFromTree (/usr/lib/node_modules/npm/lib/install/deps.js:477:14)
```

I have seen this occur on NPM version 3.10.3, but this issue does not occur on version 2.11.3. 

This issue does not occur when the symlink is not present and the local directory is not mounted to the container. It also does not occur when the `node_modules` directory is placed within the local working directory as normal.

It seems the content of `package.json` is irrelevant to this issue, as I've tested against a bare package with similar results.

**Relevant portion of Dockerfile**

```
# Install NPM local project packages
RUN mkdir /install
ADD package.json /install/package.json
RUN cd /install && npm install

# Set up working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
ADD . /usr/src/app

# Link node_modules
RUN ln -sf /install/node_modules node_modules
```

**Relevant portion of docker-compose.yml**

```
app:
  build: .
  command: npm start
  ports:
    - "8080:8080"
  volumes:
    - .:/usr/src/app
```

My current workaround is to remove the symlink, make changes to the package locally without `docker-compose`,  remove the generated `node_modules` directory, add the symlink back, and then rebuild.

**Comment by kvnxush** [comment]
++ 

Having the same issue with Docker and NPM 3.x.  There were no issues with NPM 2.x

**Comment by saiberz** [comment]
This docker-compose.yml should work: 
```
app:
  build: .
  command: npm start
  ports:
    - "8080:8080"
  volumes:
    - /src/app/node_modules
    - .:/usr/src/app
```
