### ISSUE TITLE
npm ERR! code ENOENT (Installing Phonegap)

### ISSUE THREAD

**Issue by jessmarkpanadero** [npm/npm#13523]
**Hello is anyone can help me with this error I already tried it before on other computer and its working fine but now when I install phonegap with my current computer I got this error.**

> npm install -g phonegap@latest
> npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
> npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
> npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
> C:\Users\user\AppData\Roaming\npm
> `-- (empty)
> 
> npm ERR! Windows_NT 10.0.10586
> npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "phonegap@latest"
> npm ERR! node v4.4.7
> npm ERR! npm  v3.10.5
> npm ERR! path C:\Users\user\AppData\Roaming\npm\node_modules\.staging\ansi-a75c6cfe
> npm ERR! code ENOENT
> npm ERR! errno -4058
> npm ERR! syscall rename
> 
> npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\user\AppData\Roaming\npm\node_modules\.staging\ansi-a75c6cfe' -> 'C:\Users\user\AppData\Roaming\npm\node_modules\phonegap\node_modules\cordova-lib\node_modules\ansi'
> npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\user\AppData\Roaming\npm\node_modules\.staging\ansi-a75c6cfe' -> 'C:\Users\user\AppData\Roaming\npm\node_modules\phonegap\node_modules\cordova-lib\node_modules\ansi'
> npm ERR! enoent This is most likely not a problem with npm itself
> npm ERR! enoent and is related to npm not being able to find a file.
> npm ERR! enoent
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     C:\Users\user\npm-debug.log
> npm ERR! code 1

**Comment by jessmarkpanadero** [comment]
Finally I already resolved this. I delete npm and npm-cache folder created on AppData>Roaming

**Comment by Maycon18** [comment]
jessmarkpanadero resolveu meu problema, parabéns.
