### ISSUE TITLE
how to update npm version?

### ISSUE THREAD

**Issue by cunjieliu** [npm/npm#13521]
I try to update the npm version
so I run "npm install npm -g",
it do success.
but when I run "npm --version" again,
the npm version still the old version.

so something do Is wrong?

**Comment by KenanY** [comment]
@cunjieliu Windows?

**Comment by cunjieliu** [comment]
@KenanY yes!

**Comment by KenanY** [comment]
@cunjieliu See: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows

**Comment by KenanY** [comment]
Closing as resolved. If I'm wrong just let me know and I can reopen.
