### ISSUE TITLE
Appium install is failing

### ISSUE THREAD

**Issue by bobbyislam** [npm/npm#13524]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Appium install is failing - log file attached

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by bobbyislam** [comment]
[npm-debug.txt](https://github.com/npm/npm/files/391094/npm-debug.txt)

**Comment by KenanY** [comment]
@bobbyislam Have you tried running `npm cache clean`?

**Comment by KenanY** [comment]
Closing due to a week with no response.
