### ISSUE TITLE
Unable to install protractor. error Windows_NT 6.3.9600 in windows 7 error code DEPTH_ZERO_SELF_SIGNED_CERT

### ISSUE THREAD

**Issue by Raghavendra-TN** [npm/npm#13522]
#### I'm opening this issue because:

Not able to install protractor and getting following errors.

31 error Windows_NT 6.3.9600
32 error argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "protractor"
33 error node v4.4.7
34 error npm  v2.15.8
35 error code DEPTH_ZERO_SELF_SIGNED_CERT
36 error self signed certificate
37 error If you need help, you may report this error at:
37 error     https://github.com/npm/npm/issues
38 verbose exit [ 1, true ]

Please find the attached log file.

[npm-debug.zip](https://github.com/npm/npm/files/389957/npm-debug.zip)
### supporting information:
- `npm -v` prints:
- `node -v` prints:
- `npm config get registry` prints:
- Windows, OS X, or Linux?:
- Network issues:
  - Geographic location where npm was run:
  - [ ] I use a proxy to connect to the npm registry.
  - [ ] I use a proxy to connect to the web.
  - [ ] I use a proxy when downloading Git repos.
  - [ ] I access the npm registry via a VPN
  - [ ] I don't use a proxy, but have limited or unreliable internet access.
- Container:
  - [ ] I develop using Vagrant on Windows.
  - [ ] I develop using Vagrant on OS X or Linux.
  - [ ] I develop / deploy using Docker.
  - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by Andy-wangke** [comment]
the same issue .Whether using the proxy config or not ,the error still existed
