### ISSUE TITLE
update minimatch to minimatch 3.0.2 issue

### ISSUE THREAD

**Issue by AstmDesign** [npm/npm#13525]
Guys i'm trying to update the minimatch to the version 3.0.2 because when I tried to installing cordova by usign the command  **npm install -g cordova** usually get the error 
**npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher**
I'm used the command  **npm update -g minimatch@3.0.2**
but nothing happen, BTW i'm using Mac with maverick system
How I can fix this issue ?

![screen shot 2016-07-29 at 9 27 16 pm](https://cloud.githubusercontent.com/assets/6522659/17260987/cca20ec6-55d3-11e6-9f51-a357ce8c5bc5.jpg)

**Comment by smikes** [comment]
Thanks for reporting this.

It looks like the problem here is that cordova has a dependency (or a dependency of a dependency...) on minimatch <3.0.2.

If you run `npm ls minimatch` it should show you where the dependency is -- can you try that and post back your results?

Thanks!

**Comment by AstmDesign** [comment]
Hi Smikes,
Thank you for replaying me, After I listed the files by using the command `npm ls minimatch`
I got this results 

<img width="339" alt="screen shot 2016-07-31 at 11 06 40 am" src="https://cloud.githubusercontent.com/assets/6522659/17275633/28f4a6a2-570f-11e6-87e2-34632904e8b0.png">

**Comment by photusenigma** [comment]
@AstmDesign You can install version 3.0.2 using the following command

```
npm install minimatch@3.0.2 --save-dev
```

I used --save-dev so that it becomes part of your package.json (npm config).  This will help ensure other developers working on the same project will get this version as well...and won't have to see the same error message you have.

**Comment by faizir** [comment]
Thanks @photusenigma for ur solution

**Comment by KenanY** [comment]
Closing since this isn't an issue with `npm` itself. If `npm ls minimatch@'<3.0.2'` shows that any of your dependencies are depending on outdated versions of `minimatch`, then it's up to those dependencies to update. You can send a PR to their respective repositories if you'd like.

**Comment by ghost** [comment]
Thanks bro (Y) @photusenigma

**Comment by prim007** [comment]
hey am having trouble updating mini match to minimatch3.0.2 i am using a windows laptop.l really have tried solving it the best way l can but l am failing.need help.

**Comment by crislagame** [comment]
Here have the solution:
https://wwija.com/computer-internet-technology/3963298_new-angular-quickstart-seed-gives-npm-warn-deprecated-minimatchat0-3-0.html

**Comment by Herbrandus** [comment]
crislagame: your link is not working
