### ISSUE TITLE
`npm info PKG versions` does not show all version numbers. option for it?

### ISSUE THREAD

**Issue by ljharb** [npm/npm#13532]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's the feature?
`npm info $PACKAGE versions` does not show all version numbers. Specifically, `npm info eslint versions` ends with "... 22 more items ]" and there's no documentation about an argument I could provide to expose them all.

#### What problem is the feature intended to solve?
I want to list all versions of a package without having to download the `package.json`.

#### Is the absence of this feature blocking you or your team? If so, how?
In https://github.com/ljharb/safe-publish-latest/ , I need a list of all published version numbers for a package, but https://github.com/ljharb/safe-publish-latest/issues/1 is currently blocking me from using it internally on our private registry. If I could use an `npm` command to get the list, I wouldn't need the dependency.

#### Is this feature similar to an existing feature in another tool?
It's similar to https://github.com/watson/npm-package-versions but because it's through `npm`, it would automatically support all the various registry config commands.

#### Is this a feature you're prepared to implement, with support from the npm CLI team?
Absolutely.

**Comment by ljharb** [comment]
Actually, I just experimented with a list of commands, and `npm info eslint versions --json` does what I want.

While it would be great to document this better (like having `--help` on any command show all the options it supports), I think I can close this :-)

**Comment by devdorego** [comment]
Thanks good man, you are a savior!
