### ISSUE TITLE
Node not installing

### ISSUE THREAD

**Issue by jero2rome** [npm/npm#13534]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\XYZ\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'node@3' ]
2 info using npm@3.3.12
3 info using node@v5.0.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData node@3
8 silly fetchNamedPackageData node
9 silly mapToRegistry name node
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/node
13 verbose get https://registry.npmjs.org/node not expired, no request
14 silly fetchPackageMetaData Error: No compatible version found: node@3
14 silly fetchPackageMetaData Valid install targets:
14 silly fetchPackageMetaData 0.0.0
14 silly fetchPackageMetaData
14 silly fetchPackageMetaData     at pickVersionFromRegistryDocument (C:\Users\XYZ\AppData\Roaming\npm\node_modules\npm\lib\fetch-package-metadata.js:156:16)
14 silly fetchPackageMetaData     at C:\Users\XYZ\AppData\Roaming\npm\node_modules\npm\node_modules\iferr\index.js:13:50
14 silly fetchPackageMetaData     at C:\Users\XYZ\AppData\Roaming\npm\node_modules\npm\lib\utils\pulse-till-done.js:19:8
14 silly fetchPackageMetaData     at CachingRegistryClient.get_ (C:\Users\XYZ\AppData\Roaming\npm\node_modules\npm\lib\cache\caching-client.js:120:16)
14 silly fetchPackageMetaData     at C:\Users\XYZ\AppData\Roaming\npm\node_modules\npm\lib\cache\caching-client.js:87:14
14 silly fetchPackageMetaData     at C:\Users\XYZ\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:76:16
14 silly fetchPackageMetaData     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:404:3)
14 silly fetchPackageMetaData  error for node@3 [Error: No compatible version found: node@3
14 silly fetchPackageMetaData Valid install targets:
14 silly fetchPackageMetaData 0.0.0
14 silly fetchPackageMetaData ]
15 silly rollbackFailedOptional Starting
16 silly rollbackFailedOptional Finishing
17 silly runTopLevelLifecycles Starting
18 silly runTopLevelLifecycles Finishing
19 silly install printInstalled
20 verbose stack Error: No compatible version found: node@3
20 verbose stack Valid install targets:
20 verbose stack 0.0.0
20 verbose stack
20 verbose stack     at pickVersionFromRegistryDocument (C:\Users\XYZ\AppData\Roaming\npm\node_modules\npm\lib\fetch-package-metadata.js:156:16)
20 verbose stack     at C:\Users\XYZ\AppData\Roaming\npm\node_modules\npm\node_modules\iferr\index.js:13:50
20 verbose stack     at C:\Users\XYZ\AppData\Roaming\npm\node_modules\npm\lib\utils\pulse-till-done.js:19:8
20 verbose stack     at CachingRegistryClient.get_ (C:\Users\XYZ\AppData\Roaming\npm\node_modules\npm\lib\cache\caching-client.js:120:16)
20 verbose stack     at C:\Users\XYZ\AppData\Roaming\npm\node_modules\npm\lib\cache\caching-client.js:87:14
20 verbose stack     at C:\Users\XYZ\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:76:16
20 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:404:3)
21 verbose cwd c:\Entwicklung\GitHunt
22 error Windows_NT 10.0.10586
23 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\XYZ\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "node@3"
24 error node v5.0.0
25 error npm  v3.3.12
26 error No compatible version found: node@3
26 error Valid install targets:
26 error 0.0.0
27 error If you need help, you may report this error at:
27 error     <https://github.com/npm/npm/issues>
28 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@jero2rome You can install Node.js through the binaries available at <https://nodejs.org> or through [NodeSource distributions](https://github.com/nodesource/distributions). It cannot be reliably installed through `npm`.
