### ISSUE TITLE
change the server npm installing

### ISSUE THREAD

**Issue by milad1367** [npm/npm#13531]
i not use npm proxy.
in my country block the server npm installing. I want to use another server to instaling npm.
How to do it?
please help me.
![untitled](https://cloud.githubusercontent.com/assets/15375991/17272542/708addee-56ae-11e6-95de-c3a51e62c724.jpg)

**Comment by KenanY** [comment]
@milad1367 You can configure the [`registry`](https://docs.npmjs.com/misc/config#registry) setting.
