### ISSUE TITLE
will retry, error on last attempt: Error: fetch failed with status code 429

### ISSUE THREAD

**Issue by next2014** [npm/npm#13530]
npm WARN deprecated gulp-minify-css@1.2.4: Please use gulp-clean-css
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm ERR! fetch failed https://r.cnpmjs.org/isarray/download/isarray-0.0.1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 429
npm ERR! fetch failed https://r.cnpmjs.org/socket.io-parser/download/socket.io-parser-2.2.2.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 429
npm ERR! fetch failed https://r.cnpmjs.org/socket.io-parser/download/socket.io-parser-2.2.2.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 429
npm ERR! fetch failed https://r.cnpmjs.org/socket.io-parser/download/socket.io-parser-2.2.2.tgz
npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/next/.nvm/versions/node/v6.2.0/bin/node" "/Users/next/.nvm/versions/node/v6.2.0/bin/npm" "install" "--registry=https://r.cnpmjs.org"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9

npm ERR! fetch failed with status code 429
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/next/WxMoment-Workflow/npm-debug.log

**Comment by KenanY** [comment]
@next2014 Does this also occur with the default registry?

**Comment by next2014** [comment]
gyp ERR! cwd /Users/next/WxMoment-Workflow/node_modules/lwip-decoder
gyp ERR! node -v v5.4.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/Users/next/.nvm/versions/node/v5.4.0/bin/node /Users/next/.nvm/versions/node/v5.4.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/next/WxMoment-Workflow/node_modules/lwip-decoder/lib/binding/Release/node-v47-darwin-x64/lwip_decoder.node --module_name=lwip_decoder --module_path=/Users/next/WxMoment-Workflow/node_modules/lwip-decoder/lib/binding/Release/node-v47-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/next/WxMoment-Workflow/node_modules/lwip-decoder/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:821:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Darwin 14.5.0
node-pre-gyp ERR! command "/Users/next/.nvm/versions/node/v5.4.0/bin/node" "/Users/next/WxMoment-Workflow/node_modules/lwip-decoder/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/next/WxMoment-Workflow/node_modules/lwip-decoder
node-pre-gyp ERR! node -v v5.4.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.7
node-pre-gyp ERR! not ok

**Comment by next2014** [comment]
module.js:328
    throw err;
    ^

Error: Cannot find module 'gulp-tmtsprite'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/next/WxMoment-Workflow/tasks/task_build_dist.js:8:17)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)

**Comment by zjzno1** [comment]
I also meet this problem , have you solve it?
