### ISSUE TITLE
i run the command $npm install -g cordova ionic error found

### ISSUE THREAD

**Issue by sandy-01** [npm/npm#13533]
![envirment](https://cloud.githubusercontent.com/assets/16624207/17272933/a073fbfe-56c1-11e6-93a6-4dd5f45c41d3.png)
![cmd](https://cloud.githubusercontent.com/assets/16624207/17272963/796d1b66-56c2-11e6-9f94-599dd19fd821.png)

**Comment by sandy-01** [comment]
please help  me its urgent

**Comment by smikes** [comment]
Hi Sandy, it looks like a file `npm` expects to be present isn't there.

Is it possible that your disk is full?

**Comment by sandy-01** [comment]
hey hi smikes i have checked but disk was not full i didn't get exact issues please.

**Comment by sandy-01** [comment]
i thing file npm was not there for that what should i do please help

**Comment by sandy-01** [comment]
@ smikes any other option suggest me please
