### ISSUE TITLE
i have reinstall node version  4.4.5 and then run the command $npm install -g cordova ionic 

### ISSUE THREAD

**Issue by sandy-01** [npm/npm#13539]
![npm](https://cloud.githubusercontent.com/assets/16624207/17276922/eeec0870-5753-11e6-99cb-17eef1714bf0.png)
i have reinstall node version  4.4.5 and then run the command $npm install -g cordova ionic 
npm version 3.10.5
ionic@1.7.16

please help me its urgent i need help

**Comment by gjoris** [comment]
Is it possible that you are locking the file? (or probably some process is holding on to it)

Can you actually do what the CLI is telling you to do? Renaming that file?

**Comment by gjoris** [comment]
Oh, PS: I haven't used Windows extensively in quite some time, but I know that the file explorer used to put a lock on files and directories if you just opened them. Perhaps closing all explorer windows could help too ... Or simply rebooting perhaps?

**Comment by sandy-01** [comment]
@gjoris any other option except reboot pc
