### ISSUE TITLE
when i run comman $ionic start myapp getting issues

### ISSUE THREAD

**Issue by sandy-01** [npm/npm#13536]
when i run comman $ionic start myapp getting issues  please help me its urgent
![ionic](https://cloud.githubusercontent.com/assets/16624207/17275531/32a0aea2-5729-11e6-9944-9b98b0dd003e.png)
i dont know cordova is not install properply or npm getting error

please help me its urgent

**Comment by KenanY** [comment]
@sandy-01 Does this also occur after a reboot?

**Comment by sandy-01** [comment]
@KenanY no actually i havn't rebboot PC any other option except reboot

**Comment by KenanY** [comment]
@sandy-01 Don't know what else I can suggest.

**Comment by sandy-01** [comment]
@KenanY  its done it works i did in another way
