### ISSUE TITLE
Trying to create a new user in npm

### ISSUE THREAD

**Issue by titusece** [npm/npm#13542]
Hi All,
I'm very new to node and json scripts and want to run some basic js example via node.

Q1) Getting below error while installing Titus module
titus@titus-laptop:~/workdir/nodejs/ex_test_2$ 
titus@titus-laptop:~/workdir/nodejs/ex_test_2$ npm  install Titus
npm http GET https://registry.npmjs.org/Titus
npm http 404 https://registry.npmjs.org/Titus
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/usr/share/npm/lib/cache.js:687:35)
npm ERR!     at /usr/share/npm/lib/cache.js:675:5
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Linux 3.13.0-32-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "Titus"
npm ERR! cwd /home/titus/workdir/nodejs/ex_test_2
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type non_object_property_load
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/titus/workdir/nodejs/ex_test_2/npm-debug.log
npm ERR! not ok code 0
titus@titus-laptop:~/workdir/nodejs/ex_test_2$ 

Q2) Not able to create user:
titus@titus-laptop:~/workdir/nodejs/ex$ 
titus@titus-laptop:~/workdir/nodejs/ex$ npm adduser
Username: titusece
Password: 
Email: titusece@yahoo.com
npm http PUT https://registry.npmjs.org/-/user/org.couchdb.user:titusece
npm http 400 https://registry.npmjs.org/-/user/org.couchdb.user:titusece
npm ERR! Error: ValidationError: child "password" fails because ["password" is required] : -/user/org.couchdb.user:titusece
npm ERR!     at RegClient.<anonymous> (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:272:14)
npm ERR!     at Request.self.callback (/usr/lib/nodejs/request/index.js:148:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/index.js:896:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/lib/nodejs/request/index.js:847:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Linux 3.13.0-32-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "adduser"
npm ERR! cwd /home/titus/workdir/nodejs/ex
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/titus/workdir/nodejs/ex/npm-debug.log
npm ERR! not ok code 0
titus@titus-laptop:~/workdir/nodejs/ex$

**Comment by titusece** [comment]
Please leave the question Q1.

I have tried to publish my module to use it in js file and got the error to create the user account for it "npm adduser"

Log:

titus@titus-laptop:~/workdir/nodejs/ex$ 
titus@titus-laptop:~/workdir/nodejs/ex$ npm publish 
npm ERR! need auth auth and email required for publishing
npm ERR! need auth You need to authorize this machine using `npm adduser`

npm ERR! System Linux 3.13.0-32-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "publish"
npm ERR! cwd /home/titus/workdir/nodejs/ex
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! code ENEEDAUTH
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/titus/workdir/nodejs/ex/npm-debug.log
npm ERR! not ok code 0
titus@titus-laptop:~/workdir/nodejs/ex$ 
titus@titus-laptop:~/workdir/nodejs/ex$

**Comment by KenanY** [comment]
@titusece `npm@1.3` is years old and no longer supported. Could you try updating to either `npm@2` or `npm@3` first?
