### ISSUE TITLE
Npm extract the wrong version of package

### ISSUE THREAD

**Issue by lightPang** [npm/npm#13547]
#### I'm opening this issue because:
- [x] npm is producing an incorrect install.
#### What's going wrong?

I'm using npm install to install mountebank, after I enter "npm install mountebank -g" in the command line window, the zip is successfully downloaded in npm-cache folder.

However, when the install procedure continued, an error was thrown,

 Error extracting _\AppData\Roaming\npm-cache\mountebank\1.5.0\package.tgz archive: ENOENT: no such file or directory, open '_\AppData\Roaming\npm-cache\mountebank\1.5.0\package.tgz'

I have confirmed that the latest mountebank version is "1.5.1", so it make me confused that npm tried extracting version 1.5.0.

The debug log is :

48 silly addNameRange     '1.5.1-beta.1112',
48 silly addNameRange     '1.5.1-beta.1114',
48 silly addNameRange     '1.5.1-beta.1115' ] ]
49 silly addNamed mountebank@1.5.1
50 verbose addNamed "1.5.1" is a plain semver version for mountebank
51 silly cache afterAdd mountebank@1.5.1
52 verbose afterAdd _\AppData\Roaming\npm-cache\mountebank\1.5.1\package\package.json not in flight; writing
53 verbose afterAdd *\AppData\Roaming\npm-cache\mountebank\1.5.1\package\package.json written
54 silly rollbackFailedOptional Starting
55 silly rollbackFailedOptional Finishing
56 silly runTopLevelLifecycles Starting
57 silly runTopLevelLifecycles Finishing
58 silly install printInstalled
59 verbose stack Error: Error extracting *\AppData\Roaming\npm-cache\mountebank\1.5.0\package.tgz archive: ENOENT: no such file or directory, open '_\AppData\Roaming\npm-cache\mountebank\1.5.0\package.tgz'
59 verbose stack     at ReadStream.<anonymous> (_AppData\Roaming\npm\node_modules\npm\lib\fetch-package-metadata.js:268:10)
59 verbose stack     at emitOne (events.js:77:13)
59 verbose stack     at ReadStream.emit (events.js:169:7)
59 verbose stack     at evalmachine.<anonymous>:1678:12
59 verbose stack     at OpenReq.Req.done (_\Roaming\npm\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:141:5)
59 verbose stack     at OpenReq.done (_\Roaming\npm\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:61:22)
59 verbose stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:82:15)
60 verbose cwd C:\Users\I321661\Desktop
61 error Windows_NT 10.0.10586
62 error argv "C:\Program Files\nodejs\node.exe" "_\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "install" "-g" "mountebank"
63 error node v4.4.4
64 error npm  v3.0.0
65 error code EREADFILE
66 error Error extracting _\AppData\Roaming\npm-cache\mountebank\1.5.0\package.tgz archive: ENOENT: no such file or directory, open '_\AppData\Roaming\npm-cache\mountebank\1.5.0\package.tgz'
67 error If you need help, you may report this error at:
67 error     https://github.com/npm/npm/issues
68 verbose exit [ 1, true ]
#### How can the CLI team reproduce the problem?

npm install mountebank -g
### supporting information:
- `npm -v` prints: 4.4.4
- `node -v` prints: 3.0.0
- `npm config get registry` prints: https://registry.npmjs.org/
- Windows, OS X, or Linux?: Windows 
- Network issues:
  - Geographic location where npm was run: China
  - [x] I use a proxy to connect to the npm registry.
  - [x] I use a proxy to connect to the web.
  - [ ] I use a proxy when downloading Git repos.
  - [ ] I access the npm registry via a VPN
  - [ ] I don't use a proxy, but have limited or unreliable internet access.

**Comment by cronon** [comment]
I've faced the similar issue with some of my private packages, using linux, npm v3.10.6, node v6.4.0. It correctly downloads the latest version of a package, but tries to extract package of one version below. Nevertheless `npm install mountebank -g` works nicely for me

**Comment by bojand** [comment]
I am seeing exactly the same issue. Unfortunately it's with an internal module using our internal mirror, so I can't really offer reproducible details. The `npm install` is within a docker container, within Jenkins. The image is running Centos 6.6 with node 6.5.0 and npm 3.10.3, installed using [n](https://github.com/tj/n). I do not see the issue locally. In package.json I have a module specified with `"~0.1.4"`. The latest version is `0.1.7`. Using `--verbose` I can see it downloads `0.1.7` but it tries to unpack `0.1.6`. Bumping the version of module in package.json to `~0.1.7` resolved the issue.

**Comment by bojand** [comment]
After digging into this some more... the package meta data has the following:

```
{ latest: '0.1.4-pre.0',
     '0.1.2': '0.1.2',
     '0.1.3': '0.1.3',
     '0.1.4': '0.1.4' },
```

Not sure how `latest` got set to the pre version, one would assume 0.1.4 was published _after_ the 0.1.4-pre.

In `fetchNamedPackageData` we have


```js
for (var ii = 0; ii < versions.length; ++ii) {
          if (semver.gt(versions[ii], latestVersion)) continue
          if (semver.satisfies(versions[ii], dep.spec)) {
            return returnAndAddMetadata(pkg.versions[versions[ii]])
          }
        }
```

`versions` end up being `[ '0.1.4', '0.1.4-pre.0', '0.1.3', '0.1.2' ]`
so the `latestVersion` version ends up being `'0.1.4-pre.0'` so 0.1.4 gets skipped over due to `gt` check.

**Comment by nguyenj** [comment]
I'm also running into the same issue here.

**Comment by bsc1780** [comment]
install azure
npm http GET https://registry.npmjs.org/azure
npm http 200 https://registry.npmjs.org/azure
npm http GET https://registry.npmjs.org/azure/-/azure-0.5.2.tgz
npm http 200 https://registry.npmjs.org/azure/-/azure-0.5.2.tgz
npm ERR! Could not unpack C:\Users\Matt\AppData\
  Roaming\npm-cache\azure\0.5.2\package.tgz 
  to C:\Users\Matt\AppData\Roaming\np

**Comment by corneadoug** [comment]
Also had the same issue after some digging found in which case it is happening:

* The version in your package.json isn't the latest plain version
* The latest plane version of the dependency also has a non-plain version

Npm does download the latest plain version, however it does the extract on the package.json version instead of the latest plain one.

I don't know if some version of npm are fine, but one way of fixing th

**Comment by SamuelBrucksch** [comment]
Hi, we are facing the same issue.

Node 6.12.0
Npm 3.10.10

"packageName":"*" should fetch 1.0.8 but tries to extract 1.0.7
"packageName":"^1.0.8" fetches and extracts 1.0.8

This is the end of the log:
```
npm verb afterAdd C:\Users\<username>\AppData\Roaming\npm-cache\<packagename>\1.0.8\package\package.json written
npm verb stack Error: Error extracting C:\Users\<username>\AppData\Roaming\npm-cache\<packagename>\1.0.7\package.tgz archive: ENOENT: no such file or directory, open 'C:\Users\<username>\AppData\Roaming\npm-cache\<packagename>\1.0.7\package.tgz'
npm verb stack     at ReadStream.<anonymous> (C:\Users\<username>\AppData\Roaming\nvm\v6.12.0\node_modules\npm\lib\fetch-package-metadata.js:309:10)
npm verb stack     at emitOne (events.js:96:13)
npm verb stack     at ReadStream.emit (events.js:188:7)
npm verb stack     at C:\Users\<username>\AppData\Roaming\nvm\v6.12.0\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:190:14
npm verb stack     at C:\Users\<username>\AppData\Roaming\nvm\v6.12.0\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:241:16
npm verb stack     at FSReqWrap.oncomplete (fs.js:123:15)
```
Cant show more as it is internal stuff, but it looks similiar to the first comment.

**Comment by tkissing-work** [comment]
Not sure if anyone still cares, but this still seems an issue, I have one machine with 3.10.10 on which this is reproducible (alas only for an internal package). Same issue with node 6.9.2 and 6.14.0, but only on Linux. Exact same project, same node/npm versions on Mac works fine.
