### ISSUE TITLE
npm windows install packages problems 

### ISSUE THREAD

**Issue by AhmedFathieg** [npm/npm#13540]
#### I'm trying to install bower package then i getting issue
Hello everybody I wanna ask if there's custom configuration i must do to node and npm to working well on windows.

I installed fresh OS:Windows 10 and latest node for windows 64 then i trying to install bower package by npm it give me this error

#### What's happened?
	Ahmed Fathi@DESKTOP-39VPCRV MINGW64 /c/xampp/htdocs/ahmed
	$ npm install -g bower
	npm ERR! Windows_NT 10.0.10240
	npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\                                                                                                                node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "bower"
	npm ERR! node v4.4.7
	npm ERR! npm  v2.15.8

	npm ERR! shasum check failed for C:\Users\AHMEDF~1\AppData\Local\Temp\npm-8004-f                                                                                                                89bb5a3\registry.npmjs.org\bower\-\bower-1.7.9.tgz
	npm ERR! Expected: b7296c2393e0d75edaa6ca39648132dd255812b0
	npm ERR! Actual:   b8e81ca5fd9700f878a077cbff8a54acb480f3bd
	npm ERR! From:     https://registry.npmjs.org/bower/-/bower-1.7.9.tgz
	npm ERR!
	npm ERR! If you need help, you may report this error at:
	npm ERR!     <https://github.com/npm/npm/issues>

	npm ERR! Please include the following file with any support request:
	npm ERR!     C:\xampp\htdocs\ahmed\npm-debug.log

### supporting information:

 - `npm -v` : 2.15.8
 - `node -v` : 4.4.7 64-bit
 - `npm config get registry` : https://registry.npmjs.org/
 - `OS` : Windows 10 64-bit
 - `Git` : 2.9.0 64-bit

**Comment by KenanY** [comment]
@AhmedFathieg Have you tried running `npm cache clean`?

**Comment by aturgarg** [comment]
I too have the same issue. Have tried `npm cache clean` . This is happening with every package I am trying to install. My machine is behind proxy.

**Comment by aturgarg** [comment]
`--without-ssl --insecure` fixed the issue for shasum check error in my case. [Stackoverflow link](http://stackoverflow.com/a/18346387/347652)

**Comment by legodude17** [comment]
Related: #13699. If this is the same error as that one then it should work without global. Try that.

**Comment by legodude17** [comment]
#13699 is on OS X El Capitan. @AhmedFathieg, try upgrading to node v6.0.0 and/or downgrading to node v0.12.5 as per #13699.

**Comment by AhmedFathieg** [comment]
@legodude17 @KenanY @aturgarg thanks all. 
it's solved by `npm cache clean` and opening git-bash by cmd from Run menu `cmd.exe /C "C:\Program Files\Git\bin\bash.exe" --login -i` also be sure yoy have good internet connection

**Comment by KenanY** [comment]
Closing as resolved then :)
