### ISSUE TITLE
Try to install express package locally, but did not work

### ISSUE THREAD

**Issue by janghj12000** [npm/npm#13553]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [v] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I am trying to install express package locally, but I cannot.
I set the PATH correctly.
I also create package.json file

#### How can the CLI team reproduce the problem?

Here is the log file.
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Tom\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'express' ]
2 info using npm@3.10.5
3 info using node@v4.4.7
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData express
8 silly fetchNamedPackageData express
9 silly mapToRegistry name express
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'express',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'express',
12 silly mapToRegistry   name: 'express',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/express
14 verbose request uri https://registry.npmjs.org/express
15 verbose request no auth needed
16 info attempt registry request try #1 at 11:48:56 AM
17 verbose request id f575d24c6d9b9d65
18 verbose etag "AVC1IO0CIC6EEWG2F5O1YJ7OK"
19 http request GET https://registry.npmjs.org/express
20 http 304 https://registry.npmjs.org/express
21 verbose headers { date: 'Tue, 02 Aug 2016 18:48:56 GMT',
21 verbose headers   via: '1.1 varnish',
21 verbose headers   'cache-control': 'max-age=300',
21 verbose headers   etag: '"AVC1IO0CIC6EEWG2F5O1YJ7OK"',
21 verbose headers   age: '123',
21 verbose headers   connection: 'keep-alive',
21 verbose headers   'x-served-by': 'cache-ord1721-ORD',
21 verbose headers   'x-cache': 'HIT',
21 verbose headers   'x-cache-hits': '4',
21 verbose headers   'x-timer': 'S1470163736.800587,VS0,VE0',
21 verbose headers   vary: 'Accept-Encoding' }
22 silly get cb [ 304,
22 silly get   { date: 'Tue, 02 Aug 2016 18:48:56 GMT',
22 silly get     via: '1.1 varnish',
22 silly get     'cache-control': 'max-age=300',
22 silly get     etag: '"AVC1IO0CIC6EEWG2F5O1YJ7OK"',
22 silly get     age: '123',
22 silly get     connection: 'keep-alive',
22 silly get     'x-served-by': 'cache-ord1721-ORD',
22 silly get     'x-cache': 'HIT',
22 silly get     'x-cache-hits': '4',
22 silly get     'x-timer': 'S1470163736.800587,VS0,VE0',
22 silly get     vary: 'Accept-Encoding' } ]
23 verbose etag https://registry.npmjs.org/express from cache
24 verbose get saving express to C:\Users\Tom\AppData\Roaming\npm-cache\registry.npmjs.org\express\.cache.json
25 verbose correctMkdir C:\Users\Tom\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
26 silly install normalizeTree
27 silly loadCurrentTree Finishing
28 silly loadIdealTree Starting
29 silly install loadIdealTree
30 silly cloneCurrentTree Starting
31 silly install cloneCurrentTreeToIdealTree
32 silly cloneCurrentTree Finishing
33 silly loadShrinkwrap Starting
34 silly install loadShrinkwrap
35 silly loadShrinkwrap Finishing
36 silly loadAllDepsIntoIdealTree Starting
37 silly install loadAllDepsIntoIdealTree
38 silly rollbackFailedOptional Starting
39 silly rollbackFailedOptional Finishing
40 silly runTopLevelLifecycles Starting
41 silly runTopLevelLifecycles Finishing
42 silly install printInstalled
43 verbose stack Error: Refusing to install express as a dependency of itself
43 verbose stack     at checkSelf (C:\Users\Tom\AppData\Roaming\npm\node_modules\npm\lib\install\validate-args.js:53:14)
43 verbose stack     at Array.<anonymous> (C:\Users\Tom\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
43 verbose stack     at LOOP (C:\Users\Tom\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
43 verbose stack     at chain (C:\Users\Tom\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
43 verbose stack     at C:\Users\Tom\AppData\Roaming\npm\node_modules\npm\lib\install\validate-args.js:16:5
43 verbose stack     at C:\Users\Tom\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
43 verbose stack     at Array.forEach (native)
43 verbose stack     at C:\Users\Tom\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
43 verbose stack     at Array.forEach (native)
43 verbose stack     at asyncMap (C:\Users\Tom\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
44 verbose cwd c:\Users\Tom\Desktop\web_development\node_js_practice
45 error Windows_NT 10.0.10586
46 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Tom\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "express"
47 error node v4.4.7
48 error npm  v3.10.5
49 error code ENOSELF
50 error Refusing to install express as a dependency of itself
51 error If you need help, you may report this error at:
51 error     <https://github.com/npm/npm/issues>
52 verbose exit [ 1, true ]

Thank you for your consideration.

### supporting information:

 - `npm -v` prints: 3.10.5
 - `node -v` prints: 4.4.7
 - `npm config get registry` prints: http://regisstry.npmjs.org/
 - Windows, OS X, or Linux?: Windows
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@janghj12000 Is the `"name"` attribute of your `package.json` set to `"express"` by any chance?

**Comment by janghj12000** [comment]
I download package.json from express's github repository
Is this right way to do?
Thanks!

**Comment by KenanY** [comment]
@janghj12000 If you want to locally install `express` for a project of yours, then `cd` into your project directory and run `npm install express`. Do not copy the `package.json` of any of your dependencies, rather, use `npm init` to generate your own that is specific to your project.

**Comment by janghj12000** [comment]
Still I am having same problem
I used "npm init" and able to generate package.json
The following is json file that generated from "npm init"

{
  "name": "express",
  "version": "4.14.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "MIT"
}

Then I type "npm install express"

I also add error.log

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Tom\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'express' ]
2 info using npm@3.10.5
3 info using node@v4.4.7
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData express
8 silly fetchNamedPackageData express
9 silly mapToRegistry name express
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'express',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'express',
12 silly mapToRegistry   name: 'express',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/express
14 verbose request uri https://registry.npmjs.org/express
15 verbose request no auth needed
16 info attempt registry request try #1 at 2:29:48 PM
17 verbose request id 9b3d0b61a2327d15
18 http request GET https://registry.npmjs.org/express
19 http 200 https://registry.npmjs.org/express
20 verbose headers { server: 'CouchDB/1.6.1 (Erlang OTP/R16B03)',
20 verbose headers   etag: '"9ZQG89DH0R96WWLAJ8J7GGZ2Z"',
20 verbose headers   'content-type': 'application/json',
20 verbose headers   'content-encoding': 'gzip',
20 verbose headers   'cache-control': 'max-age=300',
20 verbose headers   'content-length': '55702',
20 verbose headers   'accept-ranges': 'bytes',
20 verbose headers   date: 'Wed, 03 Aug 2016 21:29:46 GMT',
20 verbose headers   via: '1.1 varnish',
20 verbose headers   age: '189',
20 verbose headers   connection: 'keep-alive',
20 verbose headers   'x-served-by': 'cache-sea1921-SEA',
20 verbose headers   'x-cache': 'HIT',
20 verbose headers   'x-cache-hits': '22',
20 verbose headers   'x-timer': 'S1470259786.392294,VS0,VE0',
20 verbose headers   vary: 'Accept-Encoding' }
21 silly get cb [ 200,
21 silly get   { server: 'CouchDB/1.6.1 (Erlang OTP/R16B03)',
21 silly get     etag: '"9ZQG89DH0R96WWLAJ8J7GGZ2Z"',
21 silly get     'content-type': 'application/json',
21 silly get     'content-encoding': 'gzip',
21 silly get     'cache-control': 'max-age=300',
21 silly get     'content-length': '55702',
21 silly get     'accept-ranges': 'bytes',
21 silly get     date: 'Wed, 03 Aug 2016 21:29:46 GMT',
21 silly get     via: '1.1 varnish',
21 silly get     age: '189',
21 silly get     connection: 'keep-alive',
21 silly get     'x-served-by': 'cache-sea1921-SEA',
21 silly get     'x-cache': 'HIT',
21 silly get     'x-cache-hits': '22',
21 silly get     'x-timer': 'S1470259786.392294,VS0,VE0',
21 silly get     vary: 'Accept-Encoding' } ]
22 verbose get saving express to C:\Users\Tom\AppData\Roaming\npm-cache\registry.npmjs.org\express\.cache.json
23 verbose correctMkdir C:\Users\Tom\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
24 verbose makeDirectory C:\Users\Tom\AppData\Roaming\npm-cache creation not in flight; initializing
25 verbose makeCacheDir UID & GID are irrelevant on win32
26 silly install normalizeTree
27 silly loadCurrentTree Finishing
28 silly loadIdealTree Starting
29 silly install loadIdealTree
30 silly cloneCurrentTree Starting
31 silly install cloneCurrentTreeToIdealTree
32 silly cloneCurrentTree Finishing
33 silly loadShrinkwrap Starting
34 silly install loadShrinkwrap
35 silly loadShrinkwrap Finishing
36 silly loadAllDepsIntoIdealTree Starting
37 silly install loadAllDepsIntoIdealTree
38 silly rollbackFailedOptional Starting
39 silly rollbackFailedOptional Finishing
40 silly runTopLevelLifecycles Starting
41 silly runTopLevelLifecycles Finishing
42 silly install printInstalled
43 verbose stack Error: Refusing to install express as a dependency of itself
43 verbose stack     at checkSelf (C:\Users\Tom\AppData\Roaming\npm\node_modules\npm\lib\install\validate-args.js:53:14)
43 verbose stack     at Array.<anonymous> (C:\Users\Tom\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
43 verbose stack     at LOOP (C:\Users\Tom\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
43 verbose stack     at chain (C:\Users\Tom\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
43 verbose stack     at C:\Users\Tom\AppData\Roaming\npm\node_modules\npm\lib\install\validate-args.js:16:5
43 verbose stack     at C:\Users\Tom\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
43 verbose stack     at Array.forEach (native)
43 verbose stack     at C:\Users\Tom\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
43 verbose stack     at Array.forEach (native)
43 verbose stack     at asyncMap (C:\Users\Tom\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
44 verbose cwd c:\Users\Tom\Desktop\nodejs_practice
45 error Windows_NT 10.0.10586
46 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Tom\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "express"
47 error node v4.4.7
48 error npm  v3.10.5
49 error code ENOSELF
50 error Refusing to install express as a dependency of itself
51 error If you need help, you may report this error at:
51 error     <https://github.com/npm/npm/issues>
52 verbose exit [ 1, true ]

**Comment by evocateur** [comment]
Don't use "express" as the name of the project generated by `npm init`. You could let it default to `nodejs_practice`, which is your current working directory based on the debug output, by passing the `-y` flag: `rm package.json && npm init -y && npm i -S express`.

**Comment by janghj12000** [comment]
Thank you very much. It is working
