### ISSUE TITLE
npm latest verion update issue

### ISSUE THREAD

**Issue by ajayaswain12** [npm/npm#13551]
While updating the npm file , getting below error:
[root@localhost /]# sudo npm -g install npm@latest
npm ERR! Error: getaddrinfo EIO
npm ERR!     at errnoException (dns.js:37:11)
npm ERR!     at Object.onanswer [as oncomplete](dns.js:124:16)
npm ERR! If you need help, you may report this _entire_ log,
npm ERR! including the npm and node versions, at:
npm ERR!     http://github.com/npm/npm/issues

npm ERR! System Linux 2.6.39-400.215.2.el6uek.x86_64
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "-g" "install" "npm@latest"
npm ERR! cwd /
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! syscall getaddrinfo
npm ERR! code EIO
npm ERR! errno EIO
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /npm-debug.log
npm ERR! not ok code 0
## npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', '-g', 'install', 'npm@latest' ]
2 info using npm@1.4.28
3 info using node@v0.10.35
4 verbose cache add [ 'npm@latest', null ]
5 verbose cache add name=undefined spec="npm@latest" args=["npm@latest",null]
6 verbose parsed url { protocol: null,
6 verbose parsed url   slashes: null,
6 verbose parsed url   auth: null,
6 verbose parsed url   host: null,
6 verbose parsed url   port: null,
6 verbose parsed url   hostname: null,
6 verbose parsed url   hash: null,
6 verbose parsed url   search: null,
6 verbose parsed url   query: null,
6 verbose parsed url   pathname: 'npm@latest',
6 verbose parsed url   path: 'npm@latest',
6 verbose parsed url   href: 'npm@latest' }
7 verbose cache add name="npm" spec="latest" args=["npm","latest"]
8 verbose parsed url { protocol: null,
8 verbose parsed url   slashes: null,
8 verbose parsed url   auth: null,
8 verbose parsed url   host: null,
8 verbose parsed url   port: null,
8 verbose parsed url   hostname: null,
8 verbose parsed url   hash: null,
8 verbose parsed url   search: null,
8 verbose parsed url   query: null,
8 verbose parsed url   pathname: 'latest',
8 verbose parsed url   path: 'latest',
8 verbose parsed url   href: 'latest' }
9 verbose addNamed [ 'npm', 'latest' ]
10 verbose addNamed [ null, null ]
11 silly lockFile 588f5fcc-npm-latest npm@latest
12 verbose lock npm@latest /root/.npm/588f5fcc-npm-latest.lock
13 info addNameTag [ 'npm', 'latest' ]
14 verbose request where is /npm
15 verbose request registry http://registry.npmjs.org/
16 verbose request id 64a82b80341abd0f
17 verbose url raw /npm
18 verbose url resolving [ 'http://registry.npmjs.org/', './npm' ]
19 verbose url resolved http://registry.npmjs.org/npm
20 verbose request where is http://registry.npmjs.org/npm
21 info trying registry request attempt 1 at 07:49:06
22 http GET http://registry.npmjs.org/npm
23 info retry will retry, error on last attempt: Error: getaddrinfo EIO
24 info trying registry request attempt 2 at 07:49:16
25 http GET http://registry.npmjs.org/npm
26 info retry will retry, error on last attempt: Error: getaddrinfo EIO
27 info trying registry request attempt 3 at 07:50:16
28 http GET http://registry.npmjs.org/npm
29 silly lockFile 588f5fcc-npm-latest npm@latest
30 silly lockFile 588f5fcc-npm-latest npm@latest
31 error Error: getaddrinfo EIO
31 error     at errnoException (dns.js:37:11)
31 error     at Object.onanswer [as oncomplete](dns.js:124:16)
32 error If you need help, you may report this _entire_ log,
32 error including the npm and node versions, at:
32 error     http://github.com/npm/npm/issues
33 error System Linux 2.6.39-400.215.2.el6uek.x86_64
34 error command "/usr/bin/node" "/usr/bin/npm" "-g" "install" "npm@latest"
35 error cwd /
36 error node -v v0.10.35
37 error npm -v 1.4.28
38 error syscall getaddrinfo
39 error code EIO
40 error errno EIO
41 verbose exit [ 1, true ]

**Comment by evocateur** [comment]
It looks like you're attempting to upgrade from npm v1.4.28 (an extremely old version) to npm 3.10.5 (the current `latest` dist-tag), which I'm pretty sure doesn't work?

If you're able to upgrade your ancient version of `node` to v4.x or v6.x, your issue would be moot (v4.4.7 installs npm 2.15.8, v6.3.1 installs npm 3.10.3). I highly recommend this upgrade.
