### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by genezaretskiy** [npm/npm#13552]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [Y] npm is producing an incorrect install.
- [ ] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
#### How can the CLI team reproduce the problem?

I was trying to install OpenFin CLI tool and following instraction from https://openfin.co/openfin-runtime-introduction/
And have an Error.
### supporting information:
- `npm -v` prints: error npm  v2.15.8
- `node -v` prints: error node v4.4.7
- `npm config get registry` prints:
- Windows, OS X, or Linux?: Windows

31 error Windows_NT 6.1.7601
32 error argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "openfin-cli"
33 error node v4.4.7
34 error npm  v2.15.8
35 error code EPROTO
36 error errno EPROTO
37 error syscall write
38 error write EPROTO 101057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:794:

**Comment by sgregory7** [comment]
317 error Windows_NT 6.1.7601
318 error argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
319 error node v6.6.0
320 error npm  v3.10.3
321 error code EPROTO
322 error errno EPROTO
323 error syscall write
324 error write EPROTO 101057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:794:
325 error If you need help, you may report this error at:
325 error     <https://github.com/npm/npm/issues>
