### ISSUE TITLE
npm start issues 

### ISSUE THREAD

**Issue by jarnail104** [npm/npm#13559]
I am starting work on Angular2. I installed NodeJS following this url: http://blog.teamtreehouse.com/install-node-js-npm-windows
- Everything work according to mention in above article and I am able run TEST too. I can check version of npm and node by 'node -v' and 'npm -v' commands but when i start 'npm start' its giving below error. And localhost:3001 is not working. I tried localhost:8080, localhost:3000 too but nothing working.

Below is issue on command

$ npm start
npm ERR! Windows_NT 6.1.7600
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "start"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! path D:\myangular\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'D:\myangular\package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     D:\myangular\npm-debug.log

**Comment by ericmdantas** [comment]
Hello, @jarnail104. 

You've got to have the `package.json` in your `C:\myangular\` folder - that's where `npm` tries to find its scripts.

To create one, run `npm init` and answer the questions that'll show up.
