### ISSUE TITLE
"install uglify-js" throw ERR!

### ISSUE THREAD

**Issue by YataoZhang** [npm/npm#13560]
$sudo npm install uglify-js --save

npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.0.0
npm ERR! npm  v3.5.2

npm ERR! Cannot read property 'target' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/lib/node_modules/fis-prepackager-concat/npm-debug.log

**Comment by doug-wade** [comment]
@YataoZhang please include /usr/local/lib/node_modules/fis-prepackager-concat/npm-debug.log
