### ISSUE TITLE
issue in installing of magnolia CLI tool

### ISSUE THREAD

**Issue by chetan0951** [npm/npm#13572]
I'm opening this issue because:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   '@magnolia/cli',
1 verbose cli   '--registry=https://npm.magnolia-cms.com/repository/npm',
1 verbose cli   '-g' ]
2 info using npm@1.4.28
3 info using node@v0.10.37
4 verbose node symlink /usr/bin/node
5 verbose cache add [ '@magnolia/cli', null ]
6 verbose cache add name=undefined spec="@magnolia/cli" args=["@magnolia/cli",null]
7 verbose parsed url { protocol: null,
7 verbose parsed url   slashes: null,
7 verbose parsed url   auth: null,
7 verbose parsed url   host: null,
7 verbose parsed url   port: null,
7 verbose parsed url   hostname: null,
7 verbose parsed url   hash: null,
7 verbose parsed url   search: null,
7 verbose parsed url   query: null,
7 verbose parsed url   pathname: '@magnolia/cli',
7 verbose parsed url   path: '@magnolia/cli',
7 verbose parsed url   href: '@magnolia/cli' }
8 verbose cache add name="" spec="magnolia/cli" args=["","magnolia/cli"]
9 verbose parsed url { protocol: null,
9 verbose parsed url   slashes: null,
9 verbose parsed url   auth: null,
9 verbose parsed url   host: null,
9 verbose parsed url   port: null,
9 verbose parsed url   hostname: null,
9 verbose parsed url   hash: null,
9 verbose parsed url   search: null,
9 verbose parsed url   query: null,
9 verbose parsed url   pathname: 'magnolia/cli',
9 verbose parsed url   path: 'magnolia/cli',
9 verbose parsed url   href: 'magnolia/cli' }
10 silly lockFile 77bda756-magnolia-cli magnolia/cli
11 verbose lock magnolia/cli /home/nacon/.npm/77bda756-magnolia-cli.lock
12 info maybeGithub Attempting magnolia/cli from git://github.com/magnolia/cli
13 silly lockFile 44022f65-git-github-com-magnolia-cli git://github.com/magnolia/cli
14 verbose lock git://github.com/magnolia/cli /home/nacon/.npm/44022f65-git-github-com-magnolia-cli.lock
15 verbose addRemoteGit [ 'git://github.com/magnolia/cli', 'master' ]
16 verbose git clone git://github.com/magnolia/cli Cloning into bare repository '/home/nacon/.npm/_git-remotes/git-github-com-magnolia-cli-44022f65'...
16 verbose git clone git://github.com/magnolia/cli fatal: remote error:
16 verbose git clone git://github.com/magnolia/cli   Repository not found.
17 silly lockFile 44022f65-git-github-com-magnolia-cli git://github.com/magnolia/cli
18 silly lockFile 44022f65-git-github-com-magnolia-cli git://github.com/magnolia/cli
19 info maybeGithub Attempting magnolia/cli from git+ssh://git@github.com:magnolia/cli
20 silly lockFile 6021752b-git-github-com-magnolia-cli git@github.com:magnolia/cli
21 verbose lock git@github.com:magnolia/cli /home/nacon/.npm/6021752b-git-github-com-magnolia-cli.lock
22 verbose addRemoteGit [ 'git@github.com:magnolia/cli', 'master' ]
23 error git clone git@github.com:magnolia/cli Cloning into bare repository '/home/nacon/.npm/_git-remotes/git-github-com-magnolia-cli-6021752b'...
23 error git clone git@github.com:magnolia/cli Permission denied (publickey).
23 error git clone git@github.com:magnolia/cli fatal: Could not read from remote repository.
23 error git clone git@github.com:magnolia/cli
23 error git clone git@github.com:magnolia/cli Please make sure you have the correct access rights
23 error git clone git@github.com:magnolia/cli and the repository exists.
24 silly lockFile 6021752b-git-github-com-magnolia-cli git@github.com:magnolia/cli
25 silly lockFile 6021752b-git-github-com-magnolia-cli git@github.com:magnolia/cli
26 silly lockFile 77bda756-magnolia-cli magnolia/cli
27 silly lockFile 77bda756-magnolia-cli magnolia/cli
28 error addLocal Could not install magnolia/cli
29 error Error: ENOENT, stat 'magnolia/cli'
30 error If you need help, you may report this *entire* log,
30 error including the npm and node versions, at:
30 error     <http://github.com/npm/npm/issues>
31 error System Linux 3.16.0-76-generic
32 error command "/usr/bin/node" "/usr/bin/npm" "install" "@magnolia/cli" "--registry=https://npm.magnolia-cms.com/repository/npm" "-g"
33 error cwd /home/nacon
34 error node -v v0.10.37
35 error npm -v 1.4.28
36 error path magnolia/cli
37 error code ENOENT
38 error errno 34
39 verbose exit [ 34, true ]

**Comment by KenanY** [comment]
@chetan0951 Please update to `npm@2` or `npm@3`. You are trying to install a scoped module, which were not implemented back in `npm@1`.

**Comment by chetan0951** [comment]
Thank for response, it working.
one more thing is, when i am using create page command it is giving another error

chetan:~/light-modules/sampleModule$ mgnl create-page home
INFO: Using configuration at /usr/lib/node_modules/@magnolia/cli/lib/config/mgnl-cli.json
INFO: Using prototypes at /usr/lib/node_modules/@magnolia/cli/lib/config/mgnl-cli-prototypes
INFO: No path option provided, page template will be created in the current folder.
TypeError: Object /home/nacon/light-modules/sampleModule has no method 'endsWith'
nacon@nacon-004:~/light-modules/sampleModule$ 

then i run with path option with -p 
chetan:~/light-modules/sampleModule$ mgnl create-page home -p templates/pages/
INFO: Using configuration at /usr/lib/node_modules/@magnolia/cli/lib/config/mgnl-cli.json
INFO: Using prototypes at /usr/lib/node_modules/@magnolia/cli/lib/config/mgnl-cli-prototypes
ERROR: Sorry, path 'templates/pages/' does not seem to point at a valid existing light module folder.
Path option should point at a valid light module (e.g. one created with mgnl create-light-module). Please, ensure your light module complies with the expected structure.
See https://documentation.magnolia-cms.com/display/DOCS/Modules#Modules-Modulestructure
nacon@nacon-004:~/light-modules/sampleModule$

**Comment by KenanY** [comment]
@chetan0951 Sorry, that's not an error from `npm`. Try asking the developers/users of the tool you are  using. There is like a forum or IRC channel somewhere where you can request support.
