### ISSUE TITLE
This is more of a question regarding fixing npm permissions: Help please

### ISSUE THREAD

**Issue by interglobalmedia** [npm/npm#13577]
Hi,

I use OSX and am on the latest version of El Capitan. 10.11.6.

In your documentation option two, you say to `Open or create a ~/.profile file and add this line:  export PATH=~/.npm-global/bin:$PATH`

However, I cannot open my current .profile that is in my home directory. Can I create another .profile file (and call it something else like .npmprofile or whatever) and then the line `source ~/.profile` would be `source ~/.npmprofile` or whatever I call it? Would the name .npmprofile be available for use? Please advise. Thanks!
#### I'm opening this issue because:
- [ ] npm is crashing.
- [x] npm permissions issue
- [] npm is producing an incorrect install.
- [ ] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
### supporting information:
- `npm -v` prints:
- `node -v` prints:
- `npm config get registry` prints:
- Windows, OS X, or Linux?:
- Network issues:
  - Geographic location where npm was run:
  - [ ] I use a proxy to connect to the npm registry.
  - [ ] I use a proxy to connect to the web.
  - [ ] I use a proxy when downloading Git repos.
  - [ ] I access the npm registry via a VPN
  - [ ] I don't use a proxy, but have limited or unreliable internet access.
- Container:
  - [ ] I develop using Vagrant on Windows.
  - [ ] I develop using Vagrant on OS X or Linux.
  - [ ] I develop / deploy using Docker.
  - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by doug-wade** [comment]
@interglobalmedia the `.profile` file is a file used [by Unix](http://www.theunixschool.com/2011/07/what-is-profile-file.html) to manage preferences and settings for the user when they log in.  Do you have a `.bashrc` or a `.zshrc`  or a `.zprofile` or a `.bash_profile` or something that you could use instead?  Which one to use depends on which shell you're using -- if you don't know which one, it's probably bash, and you're looking for a `.bash_profile`.
