### ISSUE TITLE
No package deprecation warnings on npmjs.com

### ISSUE THREAD

**Issue by DaAwesomeP** [npm/npm#13584]
Currently, www.npmjs.com does not show if a package is deprecated. A red banner just above the readme would be fitting. Some sort of indication in search results would be nice too. A warning is shown in the command line after you have chosen to install a package but not while you are choosing/viewing it online.

Thanks!

**Comment by othiym23** [comment]
This looks like a feature request for [`npm/www`](https://github.com/npm/www/issues), the repository that the npm web team uses as for public tracking of web site issues. As the CLI team doesn't work on the web site, this issue would get lost in the shuffle here, so I'm going to close this. Thanks for your time!

**Comment by DaAwesomeP** [comment]
Thanks for the heads up! I'll migrate this issue to the other repo.
