### ISSUE TITLE
npm installed global modules can NOT run in bash [windows10]

### ISSUE THREAD

**Issue by biosunsci** [npm/npm#13585]
My npm is running fine. But, when I installed something with a -g to make it global , the bash cannot find the command like:

```
$ pug
bash: pug: command not found
```

![bash](https://cloud.githubusercontent.com/assets/15091103/17428073/26b1db28-5b18-11e6-9ab5-338d5d358075.jpg)

 The modules is installed under the prefix path.
![modules](https://cloud.githubusercontent.com/assets/15091103/17427950/34b95602-5b17-11e6-9de0-0cb62dffba4d.jpg)
and  the path is in my environment variable %PATH% 
![path](https://cloud.githubusercontent.com/assets/15091103/17428057/ff0f3d90-5b17-11e6-9d29-2e1d1eaf79be.jpg)
![node_path](https://cloud.githubusercontent.com/assets/15091103/17428059/017b6cb6-5b18-11e6-8490-652c2355e27c.jpg)

How can I make the npm find the right folder/path?

**Comment by mxchange** [comment]
Same problem here, whatever I try it won't work, it does work in PowerShell though

**Comment by legodude17** [comment]
You want to add `C:\Users\%USERNAME%\AppData\Roaming\npm\node_modules\.bin` to your `PATH`.
