### ISSUE TITLE
Parallel execution of multiple scripts/tasks

### ISSUE THREAD

**Issue by mmc41** [npm/npm#13587]
#### What's the feature?

As a npm user I need to be able to create tasks that run two commands in parallel.

For example I would like to specify a task like this
scripts": {
 "debug": ["tsc -w", "nodemon --debug bin/server.js"]
}

where the array indicates that BOTH commands are run in parallel. Note. They only work if run in parallel as they both blocks and await action.
#### What problem is the feature intended to solve?

As a developer of a a typescript nodejs application I want to be able to start a task from npm that restart node when a source file is changed. To do this I need to execute both "tsc -w" and "nodemon ..." in parallel (tsc for transpiling typescript to javscript on changes, and nodemon to restart node when the generated javascript changes). Both commands blocks and looks for changes so they can not be run in serial which is the only thing npm currently supports.
#### Is the absence of this feature blocking you or your team? If so, how?

No. There I can use other tools like gulp or npm-run-all .
#### Is this feature similar to an existing feature in another tool?

Various tools like npm-run-all can do this but they have MANY, MANY dependencies. Also, I would prefer a basic feature like this to be build-in.
#### Is this a feature you're prepared to implement, with support from the npm CLI team?

I would be willing to help test a solution.

**Comment by doug-wade** [comment]
@mmc41 Could you use [npm-run-all](https://www.npmjs.com/package/npm-run-all), rather than adding this to npm?

**Comment by mmc41** [comment]
I can use npm-run-all but my point is that I think such a fundamental feature should be build-in to npm. This would also make many more scripts as people then can stop doing the currently easiest hack which is to "&" to run things concurrently that works on Mac/Linux but not on Windows.
