### ISSUE TITLE
C:\Users\MoisesEscalera\npm-debug-log

### ISSUE THREAD

**Issue by Moymee** [npm/npm#13589]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by Moymee** [comment]
My version of Git has crashed version 2.15.8

**Comment by KenanY** [comment]
@Moymee Are you having an issue with `npm`? If so, then could you please fill out the support form in your original post, and upload any `npm-debug.log` file to <https://gist.github.com/> and post the link here?
