### ISSUE TITLE
npm install - "ERR! no package name passed to command and no package.json found"

### ISSUE THREAD

**Issue by esaramago** [npm/npm#13588]
#### I'm opening this issue because:
I can't install any npm package.

When I try to install, for example, Gulp via `npm install --global gulp-cli` I get the following: [npm-debug.zip](https://github.com/npm/npm/files/403827/npm-debug.zip)

When I run `npm access` I get this:
`npm ERR! no package name passed to command and no package.json found` [npm-debug.zip](https://github.com/npm/npm/files/403822/npm-debug.zip)

Reinstalling node and npm doesn't solve this problem.

**Comment by KenanY** [comment]
@esaramago Are you behind a proxy or firewall?

**Comment by esaramago** [comment]
@KenanY Yes, I am. And I already run npm set proxy.

**Comment by KenanY** [comment]
@esaramago Well, from the logs it seems like when `npm` attempts to request `registry.npmjs.org/gulp-cli` it is receiving some "Check Point UserCheck" page instead.

**Comment by KenanY** [comment]
Closing since this is not an issue with `npm`.
