### ISSUE TITLE
npm install issue

### ISSUE THREAD

**Issue by bobv** [npm/npm#13590]
[bobv@puppet my-proj]$ npm install
npm WARN engine bootstrap@3.3.7: wanted: {"node":">=0.10.1"} (current: {"node":"5.0.1-nightly2015111484bb74547d","npm":"3.3.12"})
npm WARN engine karma-cli@0.1.2: wanted: {"node":"0.10 || 0.12 || 4 || 5"} (current: {"node":"5.0.1-nightly2015111484bb74547d","npm":"3.3.12"})
npm WARN engine typescript@1.8.10: wanted: {"node":">=0.8.0"} (current: {"node":"5.0.1-nightly2015111484bb74547d","npm":"3.3.12"})
npm WARN engine karma@0.13.22: wanted: {"node":"0.10 || 0.12 || 4 || 5"} (current: {"node":"5.0.1-nightly2015111484bb74547d","npm":"3.3.12"})
npm ERR! Linux 3.10.0-327.10.1.el7.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.0.1-nightly2015111484bb74547d
npm ERR! npm  v3.3.12

npm ERR! shasum check failed for /tmp/npm-8788-31497521/registry.npmjs.org/lodash/-/lodash-4.14.1.tgz
npm ERR! Expected: 5b5d0a516ad3d46e12012d7f59ad66a5659bf408
npm ERR! Actual:   d1d3f11ee90a5f559e2e92c69307796e181d9100
npm ERR! From:     https://registry.npmjs.org/lodash/-/lodash-4.14.1.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/bobv/my-proj/npm-debug.log

**Comment by KenanY** [comment]
@bobv Have you tried running `npm cache clean`?

**Comment by bobv** [comment]
Thanks for the quick reply. I will try it.

________________________________

**Comment by qualitycoder** [comment]
I was getting the same error messages (started late yesterday afternoon). 

`npm cache clean` seems to have worked for me.

Thanks KenanY

**Comment by KenanY** [comment]
Closing since it has been a week with no response. If this is still an issue for you I can easily reopen.
