### ISSUE TITLE
npm install g yo issue

### ISSUE THREAD

**Issue by sateeshmurapaka** [npm/npm#13599]
When i installed yoman using npm it throw error like:

_

> **C:\Windows\system32>npm install g yo
> npm ERR! Windows_NT 6.1.7601
> npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\
> node_modules\npm\bin\npm-cli.js" "install" "g" "yo"
> npm ERR! node v4.4.7
> npm ERR! npm  v2.15.8
> 
> npm ERR! error:0906D06C:PEM routines:PEM_read_bio:no start line
> npm ERR!
> npm ERR! If you need help, you may report this error at:
> npm ERR!     https://github.com/npm/npm/issues
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     C:\Windows\system32\npm-debug.log**

_

Please give a solution for this.

**Comment by watilde** [comment]
Hello! It seems you're using an old version of npm. Could you please try to do install the latest version npm and then try again? => https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm

**Comment by sateeshmurapaka** [comment]
unable to upgrade the npm even. I got same error
C:\Windows\system32>npm install -g npm@latest
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "npm@latest"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8

npm ERR! error:0906D06C:PEM routines:PEM_read_bio:no start line
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Windows\system32\npm-debug.log

**Comment by sateeshmurapaka** [comment]
In npm-debug.log file

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'npm@latest' ]
2 info using npm@3.10.3
3 info using node@v6.3.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData npm@latest
8 silly fetchNamedPackageData npm
9 silly mapToRegistry name npm
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'npm',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'npm',
12 silly mapToRegistry   name: 'npm',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/npm
14 verbose request uri https://registry.npmjs.org/npm
15 verbose request no auth needed
16 info attempt registry request try #1 at 2:58:06 PM
17 verbose request id 43a5dcd0d6fbb67e
18 http request GET https://registry.npmjs.org/npm
19 info retry will retry, error on last attempt: Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
20 info attempt registry request try #2 at 2:58:16 PM
21 http request GET https://registry.npmjs.org/npm
22 info retry will retry, error on last attempt: Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
23 info attempt registry request try #3 at 2:59:16 PM
24 http request GET https://registry.npmjs.org/npm
25 silly fetchPackageMetaData Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
25 silly fetchPackageMetaData     at Error (native)
25 silly fetchPackageMetaData     at Object.createSecureContext (_tls_common.js:90:19)
25 silly fetchPackageMetaData     at Object.exports.connect (_tls_wrap.js:1001:48)
25 silly fetchPackageMetaData     at Agent.createConnection (https.js:82:22)
25 silly fetchPackageMetaData     at Agent.createSocket (_http_agent.js:187:26)
25 silly fetchPackageMetaData     at Agent.addRequest (_http_agent.js:149:10)
25 silly fetchPackageMetaData     at new ClientRequest (_http_client.js:158:16)
25 silly fetchPackageMetaData     at Object.exports.request (http.js:31:10)
25 silly fetchPackageMetaData     at Object.exports.request (https.js:199:15)
25 silly fetchPackageMetaData     at Request.start (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:753:32)
25 silly fetchPackageMetaData  error for npm@latest Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
25 silly fetchPackageMetaData     at Error (native)
25 silly fetchPackageMetaData     at Object.createSecureContext (_tls_common.js:90:19)
25 silly fetchPackageMetaData     at Object.exports.connect (_tls_wrap.js:1001:48)
25 silly fetchPackageMetaData     at Agent.createConnection (https.js:82:22)
25 silly fetchPackageMetaData     at Agent.createSocket (_http_agent.js:187:26)
25 silly fetchPackageMetaData     at Agent.addRequest (_http_agent.js:149:10)
25 silly fetchPackageMetaData     at new ClientRequest (_http_client.js:158:16)
25 silly fetchPackageMetaData     at Object.exports.request (http.js:31:10)
25 silly fetchPackageMetaData     at Object.exports.request (https.js:199:15)
25 silly fetchPackageMetaData     at Request.start (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:753:32)
26 silly rollbackFailedOptional Starting
27 silly rollbackFailedOptional Finishing
28 silly runTopLevelLifecycles Starting
29 silly runTopLevelLifecycles Finishing
30 silly install printInstalled
31 verbose stack Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
31 verbose stack     at Error (native)
31 verbose stack     at Object.createSecureContext (_tls_common.js:90:19)
31 verbose stack     at Object.exports.connect (_tls_wrap.js:1001:48)
31 verbose stack     at Agent.createConnection (https.js:82:22)
31 verbose stack     at Agent.createSocket (_http_agent.js:187:26)
31 verbose stack     at Agent.addRequest (_http_agent.js:149:10)
31 verbose stack     at new ClientRequest (_http_client.js:158:16)
31 verbose stack     at Object.exports.request (http.js:31:10)
31 verbose stack     at Object.exports.request (https.js:199:15)
31 verbose stack     at Request.start (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:753:32)
32 verbose cwd C:\Windows\system32
33 error Windows_NT 6.1.7601
34 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "npm@latest"
35 error node v6.3.1
36 error npm  v3.10.3
37 error error:0906D06C:PEM routines:PEM_read_bio:no start line
38 error If you need help, you may report this error at:
38 error     <https://github.com/npm/npm/issues>
39 verbose exit [ 1, true ]
