### ISSUE TITLE
incorrect install for office-ui-fabric-js-master

### ISSUE THREAD

**Issue by sage-stelee** [npm/npm#13591]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
After unzip the code for the "office-ui-fabric-js-master" project on github, I ran "npm install" and got errors.  Please refer error log.

410 error git clone --template=C:\Users\SteLee\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/colynb/commonjs-html-prettyprinter.git C:\Users\SteLee\AppData\Roaming\npm-cache\_git-remotes\git-github-com-colynb-commonjs-html-prettyprinter-git-babaf478: Cloning into bare repository 'C:\Users\SteLee\AppData\Roaming\npm-cache\_git-remotes\git-github-com-colynb-commonjs-html-prettyprinter-git-babaf478'...
410 error git clone --template=C:\Users\SteLee\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/colynb/commonjs-html-prettyprinter.git C:\Users\SteLee\AppData\Roaming\npm-cache\_git-remotes\git-github-com-colynb-commonjs-html-prettyprinter-git-babaf478: fatal: unable to connect to github.com:
410 error git clone --template=C:\Users\SteLee\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/colynb/commonjs-html-prettyprinter.git C:\Users\SteLee\AppData\Roaming\npm-cache\_git-remotes\git-github-com-colynb-commonjs-html-prettyprinter-git-babaf478: github.com[0: 192.30.253.112]: errno=No error
411 verbose about to build C:\Users\SteLee\Desktop\office-ui-fabric-js-master\node_modules\gulp-html-prettify
412 verbose unlock done using C:\Users\SteLee\AppData\Roaming\npm-cache\_locks\gulp-html-prettify-7c49bd28297ba162.lock for C:\Users\SteLee\Desktop\office-ui-fabric-js-master\node_modules\gulp-html-prettify
413 verbose stack Error: Command failed: git -c core.longpaths=true clone --template=C:\Users\SteLee\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/colynb/commonjs-html-prettyprinter.git C:\Users\SteLee\AppData\Roaming\npm-cache\_git-remotes\git-github-com-colynb-commonjs-html-prettyprinter-git-babaf478
413 verbose stack Cloning into bare repository 'C:\Users\SteLee\AppData\Roaming\npm-cache\_git-remotes\git-github-com-colynb-commonjs-html-prettyprinter-git-babaf478'...
413 verbose stack fatal: unable to connect to github.com:
413 verbose stack github.com[0: 192.30.253.112]: errno=No error
413 verbose stack
413 verbose stack
413 verbose stack     at ChildProcess.exithandler (child_process.js:213:12)
413 verbose stack     at emitTwo (events.js:87:13)
413 verbose stack     at ChildProcess.emit (events.js:172:7)
413 verbose stack     at maybeClose (internal/child_process.js:827:16)
413 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
414 verbose cwd C:\Users\SteLee\Desktop\office-ui-fabric-js-master

### supporting information:

 - `npm -v` prints:                                    2.15.5
 - `node -v` prints:                                   v4.4.5
 - `npm config get registry` prints:          https://registry.npmjs.org/
 - Windows, OS X, or Linux?:                   Windows_NT 6.1.7601
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@sage-stelee Looks like an issue with your internet connection:

```
413 verbose stack fatal: unable to connect to github.com:
413 verbose stack github.com[0: 192.30.253.112]: errno=No error
```

Ensure that you are not behind a proxy or firewall that might be rejecting the requests to `github.com`.

**Comment by KenanY** [comment]
Closing as abandoned since it has been a week with no response.

**Comment by sage-stelee** [comment]
Hi Kenan,

Thank you for your help.




Best regards,

Steven
