### ISSUE TITLE
npm install is throwing error

### ISSUE THREAD

**Issue by dkumar431** [npm/npm#13592]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [x] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [x] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by dkumar431** [comment]
npm -v  : 2.15.8
node -v : 4.4.7
I am getting the below error when i am running the npm install --registry http://localhost:23510

D:\HDC\hui-components-ui>npm install --registry http://localhost:23510
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code E500

npm ERR! 500 Internal Server Error
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\HDC\hui-components-ui\npm-debug.log

**Comment by KenanY** [comment]
@dkumar431 Does this also occur without specifying a custom registry?

**Comment by dkumar431** [comment]
Yes its showing the same error without registry also. Here I am attaching the log.
[npm-debug.txt](https://github.com/npm/npm/files/404862/npm-debug.txt)

**Comment by KenanY** [comment]
@dkumar431 The first few lines clearly show that you are still running the command with the `--registry` flag:

```
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--registry',
1 verbose cli   'http://localhost:23510' ]
```

**Comment by KenanY** [comment]
Closing due to no response after a week. Can reopen if you are still having this issue.
