### ISSUE TITLE
not able to install cordova

### ISSUE THREAD

**Issue by MayankPoundrik** [npm/npm#13595]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ -] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@MayankPoundrik Could you please take the time to fill out the support form in your post? Also, uploading a `npm-debug.log` file to <https://gist.github.com/> and posting the link here will help a ton as well. Thanks!

**Comment by KenanY** [comment]
Closing due to no response and not enough information to provide any kind of support anyways.
