### ISSUE TITLE
For some pkgs "npm install <pkg_name>" command not fetching the test directory from github

### ISSUE THREAD

**Issue by sandipmgiri** [npm/npm#13605]
I'm trying to install "graphql-readable" npm-package using command "npm install graphql-readable". But this command not fetching the test directory from github.  Have checked manually test directory available on github  url i.e. https://github.com/tsingchao/graphql-readable(Url is taken from npm-page i.e.https://www.npmjs.com/package/graphql-readable)   

How to fetch the test directory from github by using "npm install" command only (without cloning)??

**Comment by KenanY** [comment]
@sandipmgiri That package has its test directory in [its `.npmignore` file](https://github.com/tsingchao/graphql-readable/blob/9e2d8703f654bd29b2eab513c9f78d5fbfa20c6a/.npmignore#L1). thus `npm` will not include that directory in the published tarball. When you do `npm install graphql-readable`, you are downloading the package from the `npm` registry, not from GitHub. If you want the test directory I don't know what else to suggest but cloning.

**Comment by sandipmgiri** [comment]
Thanks!!!

Is there any way to get the git urls for all the npm-packages ? So that i can follow cloning approach ?

**Comment by KenanY** [comment]
@sandipmgiri Hey, you've asked that before! https://github.com/npm/npm/issues/13574

**Comment by KenanY** [comment]
Closing as resolved.
