### ISSUE TITLE
npm cordova install problem on windows 10

### ISSUE THREAD

**Issue by RithwikK** [npm/npm#13600]
#### I'm opening this issue because:
- [ ] npm is producing an incorrect install.
#### What's going wrong?

When I type ' npm install -g cordova' I get the following:

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "D:\nodejs\node.exe" "D:\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "cordova"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code SELF_SIGNED_CERT_IN_CHAIN

npm ERR! self signed certificate in certificate chain
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     D:\npm-debug.log
### supporting information:
- `npm -v` prints: 3.10.3
- `node -v` prints: v6.3.1
- `npm config get registry` prints: https://registry.npmjs.org/
- Windows, OS X, or Linux?: Windows 10

**Comment by watilde** [comment]
It seems to be related to SSL error. Could you please check this thread? https://github.com/npm/npm/issues/6841

**Comment by RithwikK** [comment]
This is the npm-debug.log


0 info it worked if it ends with ok
1 verbose cli [ 'D:\\nodejs\\node.exe',
1 verbose cli   'D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'cordova' ]
2 info using npm@3.10.3
3 info using node@v6.3.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData cordova
8 silly fetchNamedPackageData cordova
9 silly mapToRegistry name cordova
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'cordova',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'cordova',
12 silly mapToRegistry   name: 'cordova',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/cordova
14 verbose request uri https://registry.npmjs.org/cordova
15 verbose request no auth needed
16 info attempt registry request try #1 at 11:57:12 PM
17 verbose request id 91764d1cf28931d0
18 http request GET https://registry.npmjs.org/cordova
19 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
20 info attempt registry request try #2 at 11:57:23 PM
21 http request GET https://registry.npmjs.org/cordova
22 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
23 info attempt registry request try #3 at 11:58:24 PM
24 http request GET https://registry.npmjs.org/cordova
25 silly fetchPackageMetaData Error: self signed certificate in certificate chain
25 silly fetchPackageMetaData     at Error (native)
25 silly fetchPackageMetaData     at TLSSocket.<anonymous> (_tls_wrap.js:1060:38)
25 silly fetchPackageMetaData     at emitNone (events.js:86:13)
25 silly fetchPackageMetaData     at TLSSocket.emit (events.js:185:7)
25 silly fetchPackageMetaData     at TLSSocket._finishInit (_tls_wrap.js:584:8)
25 silly fetchPackageMetaData     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38)
25 silly fetchPackageMetaData  error for cordova { Error: self signed certificate in certificate chain
25 silly fetchPackageMetaData     at Error (native)
25 silly fetchPackageMetaData     at TLSSocket.<anonymous> (_tls_wrap.js:1060:38)
25 silly fetchPackageMetaData     at emitNone (events.js:86:13)
25 silly fetchPackageMetaData     at TLSSocket.emit (events.js:185:7)
25 silly fetchPackageMetaData     at TLSSocket._finishInit (_tls_wrap.js:584:8)
25 silly fetchPackageMetaData     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38) code: 'SELF_SIGNED_CERT_IN_CHAIN' }
26 silly rollbackFailedOptional Starting
27 silly rollbackFailedOptional Finishing
28 silly runTopLevelLifecycles Starting
29 silly runTopLevelLifecycles Finishing
30 silly install printInstalled
31 verbose stack Error: self signed certificate in certificate chain
31 verbose stack     at Error (native)
31 verbose stack     at TLSSocket.<anonymous> (_tls_wrap.js:1060:38)
31 verbose stack     at emitNone (events.js:86:13)
31 verbose stack     at TLSSocket.emit (events.js:185:7)
31 verbose stack     at TLSSocket._finishInit (_tls_wrap.js:584:8)
31 verbose stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38)
32 verbose cwd D:\cordova
33 error Windows_NT 10.0.10586
34 error argv "D:\\nodejs\\node.exe" "D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova"
35 error node v6.3.1
36 error npm  v3.10.3
37 error code SELF_SIGNED_CERT_IN_CHAIN
38 error self signed certificate in certificate chain
39 error If you need help, you may report this error at:
39 error     <https://github.com/npm/npm/issues>
40 verbose exit [ 1, true ]

**Comment by watilde** [comment]
Thanks for the npm-debug.log! Well, to make it clear, let me ask: have you already tried these commands?
> npm --ca=null --strict-ssl=false install -g cordova
> npm config get ca
