### ISSUE TITLE
创建项目时失败了

### ISSUE THREAD

**Issue by choubaguai** [npm/npm#13606]
Administrator@USER-20160311EK MINGW64 /f/reactnative
$ react-native init superbro
This will walk you through creating a new React Native project in F:\reactnative                                                                                                                           \superbro
Installing react-native package from npm...

> spawn-sync@1.0.15 postinstall F:\reactnative\superbro\node_modules\react-nativ                                                                                                                           e\node_modules\yeoman-generator\node_modules\cross-spawn\node_modules\spawn-sync
> node postinstall

npm WARN peerDependencies The peer dependency react@~15.2.1 included from react-                                                                                                                           native will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerD                                                                                                                           ependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it                                                                                                                            explicitly.
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a bu                                                                                                                           ild toolchain, use it instead!
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "F:\\Program Files\\nodejs\\node.exe" "F:\\Program Files\\nodejs\\                                                                                                                           node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "--save-exact" "react-nat                                                                                                                           ive"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8

npm ERR! shasum check failed for C:\Users\ADMINI~1\AppData\Local\Temp\npm-21044-                                                                                                                           da09ea95\registry.cnpmjs.org\iconv-lite\download\iconv-lite-0.4.13.tgz
npm ERR! Expected: 1f88aba4ab0b1508e8312acc39345f36e992e2f2
npm ERR! Actual:   949256175d1b87f2ea25bb1917c78c1b9d8aab56
npm ERR! From:     http://registry.cnpmjs.org/iconv-lite/download/iconv-lite-0.4                                                                                                                           .13.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     F:\reactnative\superbro\npm-debug.log

`npm install --save --save-exact react-native` failed

**Comment by KenanY** [comment]
@choubaguai Have you tried running `npm cache clean`?

**Comment by KenanY** [comment]
Closing as abandoned due to no response after a week.

**Comment by sarathbabu82** [comment]
I have face the same issue.

C:\ENVIRON\REACT_NATIVE>react-native init AwesomeProject
This will walk you through creating a new React Native project in C:\ENVIRON\REACT_NATIVE\AwesomeProject
Installing react-native package from npm...

> spawn-sync@1.0.15 postinstall C:\ENVIRON\REACT_NATIVE\AwesomeProject\node_modules\react-native\node_modules\yeoman-generator\node_modules\cross-spawn\node_modules\spawn-sync
> node postinstall


npm WARN peerDependencies The peer dependency react@~15.2.1 included from react-native will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on itexplicitly.
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\nodejs\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "--save-exact" "react-native"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12
npm ERR! path C:\Users\DIR\AppData\Roaming\npm-cache\babel-runtime\6.11.6\package\package.json.b8efd2d65fa6745c193a0c14da1faefc
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\DIR\AppData\Roaming\npm-cache\babel-runtime\6.11.6\package\package.json.b8efd2
d65fa6745c193a0c14da1faefc' -> 'C:\Users\DIR\AppData\Roaming\npm-cache\babel-runtime\6.11.6\package\package.json'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM: operation not permitted, rename 'C:\Users\DIR\AppData\Roaming\npm-cache\babel-runtime\6.11.6\package\package.json.b8
efd2d65fa6745c193a0c14da1faefc' -> 'C:\Users\DIR\AppData\Roaming\npm-cache\babel-runtime\6.11.6\package\package.json']
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'rename',
npm ERR!   path: 'C:\\Users\\DIR\\AppData\\Roaming\\npm-cache\\babel-runtime\\6.11.6\\package\\package.json.b8efd2d65fa6745c193a0c14da1faefc',
npm ERR!   dest: 'C:\\Users\\DIR\\AppData\\Roaming\\npm-cache\\babel-runtime\\6.11.6\\package\\package.json',
npm ERR!   parent: 'babel-plugin-transform-es2015-parameters' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\ENVIRON\REACT_NATIVE\AwesomeProject\npm-debug.log

`npm install --save --save-exact react-native` failed
