### ISSUE TITLE
ionic n npm cant run

### ISSUE THREAD

**Issue by tyogunawan23** [npm/npm#13603]
ionic cant run .. this issue :+1: 

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Tyo CODEID\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'v' ]
2 info using npm@3.10.5
3 info using node@v4.4.7
4 verbose config Skipping project config: C:\Users\Tyo CODEID/.npmrc. (matches userconfig)
5 verbose stack Error: Invalid package.json
5 verbose stack     at C:\Users\Tyo CODEID\node_modules\npm\lib\view.js:84:30
5 verbose stack     at ReadFileContext.<anonymous> (C:\Users\Tyo CODEID\node_modules\npm\node_modules\read-package-json\read-json.js:90:21)
5 verbose stack     at ReadFileContext.callback (C:\Users\Tyo CODEID\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16)
5 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:303:13)
6 verbose cwd C:\Users\Tyo CODEID
7 error Windows_NT 6.1.7601
8 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Tyo CODEID\\node_modules\\npm\\bin\\npm-cli.js" "v"
9 error node v4.4.7
10 error npm  v3.10.5
11 error Invalid package.json
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@tyogunawan23 Could you explain what command you are running and what you are trying to accomplish?

**Comment by KenanY** [comment]
Closing as abandoned due to no response after a week.
