### ISSUE TITLE
npm install rsmq npm ERR! Windows_NT 6.3.9600

### ISSUE THREAD

**Issue by sunil0589** [npm/npm#13615]
D:\su\nodejs\redis\rsmq-master>npm install rsmq
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\su\\AppD
ata\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "rsmq"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.6
npm ERR! code ENOSELF

npm ERR! Refusing to install rsmq as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\su\nodejs\redis\rsmq-master\npm-debug.log

**Comment by KenanY** [comment]
@sunil0589 Are you trying to install `rsmq` for a project of yours?

**Comment by sunil0589** [comment]
yes i am trying to install rsmq..................

**Comment by KenanY** [comment]
@sunil0589 Then you should `cd` into your project directory and run `npm install rsmq`. From the log, it looks like you are trying to install `rsmq` in a directory called `rsmq-master`, which I assume is the source code for that module?

**Comment by KenanY** [comment]
Closing due to no response.

**Comment by sunil0589** [comment]
Thanks @KenanY  it has been resolved now....
