### ISSUE TITLE
npm install issue 

### ISSUE THREAD

**Issue by neelrag** [npm/npm#13616]
#### I'm opening this issue because: i have error while  installing power BI wizard developer tool.

I am running the install command 
**npm install -g powerbi-visuals-tools**

Please find below the log file error messages. Unable to upload the file.

0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli   'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'powerbi-visuals-tools' ]
2 info using npm@3.10.3
3 info using node@v6.3.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData powerbi-visuals-tools
8 silly fetchNamedPackageData powerbi-visuals-tools
9 silly mapToRegistry name powerbi-visuals-tools
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'powerbi-visuals-tools',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'powerbi-visuals-tools',
12 silly mapToRegistry   name: 'powerbi-visuals-tools',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/powerbi-visuals-tools
14 verbose request uri https://registry.npmjs.org/powerbi-visuals-tools
15 verbose request no auth needed
16 info attempt registry request try #1 at 5:05:47 PM
17 verbose request id ff1f437e346fc7df
18 http request GET https://registry.npmjs.org/powerbi-visuals-tools
19 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
20 info attempt registry request try #2 at 5:05:57 PM
21 http request GET https://registry.npmjs.org/powerbi-visuals-tools
22 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
23 info attempt registry request try #3 at 5:06:57 PM
24 http request GET https://registry.npmjs.org/powerbi-visuals-tools
25 silly fetchPackageMetaData Error: self signed certificate in certificate chain
25 silly fetchPackageMetaData     at Error (native)
25 silly fetchPackageMetaData     at TLSSocket.<anonymous> (_tls_wrap.js:1060:38)
25 silly fetchPackageMetaData     at emitNone (events.js:86:13)
25 silly fetchPackageMetaData     at TLSSocket.emit (events.js:185:7)
25 silly fetchPackageMetaData     at TLSSocket._finishInit (_tls_wrap.js:584:8)
25 silly fetchPackageMetaData     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38)
25 silly fetchPackageMetaData  error for powerbi-visuals-tools { Error: self signed certificate in certificate chain
25 silly fetchPackageMetaData     at Error (native)
25 silly fetchPackageMetaData     at TLSSocket.<anonymous> (_tls_wrap.js:1060:38)
25 silly fetchPackageMetaData     at emitNone (events.js:86:13)
25 silly fetchPackageMetaData     at TLSSocket.emit (events.js:185:7)
25 silly fetchPackageMetaData     at TLSSocket._finishInit (_tls_wrap.js:584:8)
25 silly fetchPackageMetaData     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38) code: 'SELF_SIGNED_CERT_IN_CHAIN' }
26 silly rollbackFailedOptional Starting
27 silly rollbackFailedOptional Finishing
28 silly runTopLevelLifecycles Starting
29 silly runTopLevelLifecycles Finishing
30 silly install printInstalled
31 verbose stack Error: self signed certificate in certificate chain
31 verbose stack     at Error (native)
31 verbose stack     at TLSSocket.<anonymous> (_tls_wrap.js:1060:38)
31 verbose stack     at emitNone (events.js:86:13)
31 verbose stack     at TLSSocket.emit (events.js:185:7)
31 verbose stack     at TLSSocket._finishInit (_tls_wrap.js:584:8)
31 verbose stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38)
32 verbose cwd C:\
33 error Windows_NT 6.1.7601
34 error argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "powerbi-visuals-tools"
35 error node v6.3.1
36 error npm  v3.10.3
37 error code SELF_SIGNED_CERT_IN_CHAIN
38 error self signed certificate in certificate chain
39 error If you need help, you may report this error at:
39 error     https://github.com/npm/npm/issues
40 verbose exit [ 1, true ]

**Comment by emale999** [comment]
Try running the command
`npm config set strict-ssl false`
before using `npm install`. Worked for me.
