### ISSUE TITLE
npm version keeps updated version when pre/version script fails

### ISSUE THREAD

**Issue by pke** [npm/npm#13614]
#### I'm opening this issue because:
- [X] npm is doing something I don't understand.
#### What's going wrong?

When any of the scripts in `version` fail to run, the version number in `package.json` stays updated, instead of being reverted back.
#### How can the CLI team reproduce the problem?

In the `package.json` create a `version` entry under `scripts` that calls a command that fails.

Then from the CLI call `npm version patch` and see the package version updated despite the fact that the `version` script failed.
- `npm -v` prints:
  `3.9.3`
- `node -v` prints:
  `6.2.1`
- Windows, OS X, or Linux?: Windows

**Comment by jonataswalker** [comment]
> npm is doing something I don't understand

Me neither.

**Comment by legodude17** [comment]
This shouldn't be happening, try making a `install` script and then running npm install. Does it continue to install if the script fails?
