### ISSUE TITLE
web3 install Failure

### ISSUE THREAD

**Issue by arigelas** [npm/npm#13617]
#### I'm opening this issue because:

  - [ ] npm is producing an incorrect install.
 

#### What's going wrong?
web3 is not getting installed.

#### How can the CLI team reproduce the problem?
 npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:202:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:852:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:323:11)
npm WARN addRemoteGit     at emitOne (events.js:96:13)
npm WARN addRemoteGit     at Socket.emit (events.js:188:7)
npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:492:12)
npm WARN addRemoteGit  git+https://github.com/debris/bignumber.js.git#master resetting remote C:\Users\XXXAppData\Roaming\npm-cache\_git-remotes\git-https-github-com-debris-bignumber-js-g
it-master-df3f1ce1 because of error: { Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:202:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:852:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:323:11)
npm WARN addRemoteGit     at emitOne (events.js:96:13)
npm WARN addRemoteGit     at Socket.emit (events.js:188:7)
npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:492:12)
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
npm ERR! git clone --template=C:\Users\XXX\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/debris/bignumber.js.git C:\Users\XXX\AppData\Roaming\np
m-cache\_git-remotes\git-https-github-com-debris-bignumber-js-git-master-df3f1ce1: Cloning into bare repository 'C:\Users\XXX\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-de
bris-bignumber-js-git-master-df3f1ce1'...
npm ERR! git clone --template=C:\Users\XXX\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/debris/bignumber.js.git C:\Users\XXX\AppData\Roaming\np
m-cache\_git-remotes\git-https-github-com-debris-bignumber-js-git-master-df3f1ce1: fatal: unable to access 'https://github.com/debris/bignumber.js.git/': Couldn't resolve host 'github.com'
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "web3"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\XXX\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/debris/bignumber.js.git C:\U
sers\XXX.a\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-debris-bignumber-js-git-master-df3f1ce1
npm ERR! Cloning into bare repository 'C:\Users\XXX\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-debris-bignumber-js-git-master-df3f1ce1'...
npm ERR! fatal: unable to access 'https://github.com/debris/bignumber.js.git/': Couldn't resolve host 'github.com'
npm ERR!

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@arigelas The log seems to indicate that this is an issue with your internet connection. not with `npm`. Ensure that you do not have a proxy or firewall that might be blocking your connection to `github.com` or the `git:` protocol.

**Comment by KenanY** [comment]
Closing as abandoned.
