### ISSUE TITLE
I'm trying to install cordova. But it is giving error.

### ISSUE THREAD

**Issue by mdjageer** [npm/npm#13612]
I am getting the below error.
Kindly assist me to fix the below issues.

D:\cordova>npm install -g cordova
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova"
npm ERR! node v4.4.2
npm ERR! npm  v2.15.0

npm ERR! shasum check failed for C:\Users\490731\AppData\Local\Temp\npm-10684-7e
e3f6e0\registry.npmjs.org\bplist-parser\-\bplist-parser-0.1.1.tgz
npm ERR! Expected: d60d5dcc20cba6dc7e1f299b35d3e1f95dafbae6
npm ERR! Actual:   28c7a4fc8e98060cc6d60063262c74c2ead2736b
npm ERR! From:     https://registry.npmjs.org/bplist-parser/-/bplist-parser-0.1.
1.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\cordova\npm-debug.log

D:\cordova>

Thanks,
Mohammed jageer hussain. S

**Comment by KenanY** [comment]
@mdjageer Have you tried running `npm cache clean`?

**Comment by KenanY** [comment]
Closing as abandoned.
