### ISSUE TITLE
No compatible version found: gulp-clean-css@^1.2.0

### ISSUE THREAD

**Issue by thenaughtychild** [npm/npm#13611]
Hi,
npm fails to install the packages with the following error. Here is the [npm-debug.log](https://gist.github.com/thenaughtychild/0730309573715c96353f9025bc71ef05) file. 
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/local/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.10.5

npm ERR! No compatible version found: gulp-clean-css@^1.2.0
npm ERR! Valid install targets:
npm ERR! 2.0.12, 2.0.11, 2.0.10, 2.0.9, 2.0.8, 2.0.7, 2.0.6, 2.0.5, 2.0.4, 2.0.3, 2.0.2, 2.0.1, 2.0.0, 1.0.2, 1.0.1, 1.0.0

**Comment by KenanY** [comment]
@thenaughtychild Do you have `gulp-clean-css@^1.2.0` in your `package.json`?

**Comment by timoxley** [comment]
@thenaughtychild this error message is accurate.

There is currently no version of `gulp-clean-css` greater than or equal to `1.2.0` that's less than `2.0.0`. I think you may have mistyped `1.0.2` as `1.2.0`. Try `^2.0.0` and if that doesn't work then try `^1.0.0`.

**Comment by KenanY** [comment]
Closing as abandoned.
