### ISSUE TITLE
completion: refused to run under CYGWIN bash

### ISSUE THREAD

**Issue by ankostis** [npm/npm#13624]
With cygwin's bash, under Windows 7 64bit, with latest *node.js* zip download and extracted from: https://nodejs.org/dist/latest/, the autocompletion script from ``npm completion`` command **is not produced at all**.
Specifically  I get the following messages:

```bash
CYGWIN $ npm completion
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\Apps\\node.js\\node.exe" "D:\\Apps\\node.js\\node_modules\\npm\\bin\\npm-cli.js" "completion"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ENOTSUP

npm ERR! nospc npm completion supported only in MINGW / Git bash on Windows
npm ERR! nospc This is most likely not a problem with npm itself
npm ERR! nospc and is related to insufficient space on your system.

npm ERR! Please include the following file with any support request:
npm ERR!     ...\npm-debug.log

CYGWIN $ npm -v
3.10.3

CYGWIN $ node -v
v6.3.1

CYGWIN $ which npm node bash | xargs cygpath -w
D:\Apps\node.js\npm
D:\Apps\node.js\node
D:\Apps\cygwin64\bin\bash
```

Note that when I run ``npm completion`` the in GIT's bash, the command produces a script:

```bash
MINGW64 $ npm completion
#!/bin/bash........] - : info using node@v6.3.1
###-begin-npm-completion-###
#
# npm command completion script
#
...
###-end-npm-completion-###


MINGW64 $ which npm node bash | xargs cygpath -w
D:\Apps\node.js\npm
D:\Apps\node.js\node
D:\Apps\Git\usr\bin\bash
```

**Comment by ankostis** [comment]
Updated console-commands above to include installation paths for `node/npm` commands, to make it clear that I'm not using *cygwin's node.js* distribution.

**Comment by othiym23** [comment]
npm is not supported under Cygwin, regardless of which Node.js distribution is under use. As such, I'm closing this issue. Thanks for your time!

**Comment by ankostis** [comment]
I know it is not supported; but is there a reason that it must remain that way?
Do you accept PR?

**Comment by othiym23** [comment]
> Do you accept PR?

Not for Cygwin support. Given its hybrid approach to bridging the gap between UNIX and Windows, it provides unique challenges to tools like the npm CLI that try to provide a platform-native experience on multiple operating systems. This is CLI team policy, and unlikely to change, especially as the Ubuntu runtime layer for Windows 10, which provides a much better Unix-like experience on Windows, approaches maturity.

**Comment by ankostis** [comment]
@othiym23 I believe there a miss-understanding here:

Presently **STANDALONE `npm` works almost perfectly when invoked from *cygwin-bash* CLI.**
The only hurdle for providing a *"a platform-native experience"* is that 
the TAB-completion is not working.

Now, TAB-completion fails because `npm`'s platform-detection code in [lib/completion.js#L49](https://github.com/npm/npm/blob/master/lib/completion.js#L49) refuses to consider cygwin capable for TAB-completing.
And if I got it right, that's because *cygwin does not constitute "a platform-native experience"*, and therefore *"CLI team policy"* dictates that cygwin-bash must not be supported...

But that's a circular argument!
The only hurdle is the policy itself, and the hybrid approach of cygwin is irrelevant.

So how can I help to change the policy?

**Comment by othiym23** [comment]
> So how can I help to change the policy [edit:] at least for this particular case?

To be blunt, you can't. The npm CLI team has affirmatively decided that we aren't willing to support Cygwin, because:

1. the Cygwin user base is very small relative to the other user bases we support, and
2. the complexity of supporting Cygwin is not worth its cost, given 1.

There is another solution to this problem, which is to create a package of npm for Cygwin that includes whatever patches Cygwin users feel make for the best experience for them. In this case, everybody wins – the CLI team doesn't have to support additional complexity around these edge cases, and Cygwin users get a user experience that is tailored for their needs.

**Comment by emigenix** [comment]
No to start any flaming or anything, but I think the Cygwin "user base" is grossly underestimated. I know loads of people using this on a regular basis, and I'm not even in the IT community.  Node and *npm* work under windows and also in Cygwin, but need some more love and acceptance. Yes, indeed old Cygwin pretty much sucked, but today, just about everything works, so most of the incompatibility is a myth, perpetuated by people who doesn't bother to try it. I think the main issue with *npm* on Cygwin is how it decide where the `npmrc` and `node_module` files are located. I'm sure the Ubuntu runtime will not change very much as to what Cygwin already can do. So bottom line is, if Windows can do *node/npm* in *CMD*, it surely can do it better in Cygwin.

**Comment by ssreekanth** [comment]
I use ``babun`` (based on ``cygwin``) on my Windows 10 PC. I never had this issue until i recently upgraded to the current ``node.js v6.4.0``. I would like to see ``npm`` plugin working fully with completion again in my ``oh-my-zsh`` setup.

**Comment by feryardiant** [comment]
I'm also have same setup as @ssreekanth (`babun` on Windows 10 PC with native `node.js 6.7.0`), even tho i've added [this](https://github.com/feryardiant/dotfiles/blob/master/.exports#L175-L177) line on my `.exports` file but it still an issue.

```bash
if [[ $shellname = bash && $OSTYPE != cygwin ]]; then
    . <(npm completion)
fi
```

Here my `npm-debug.log` file

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\feryardiant\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'completion' ]
2 info using npm@3.10.5
3 info using node@v6.7.0
4 verbose stack Error: npm completion supported only in MINGW / Git bash on Windows
4 verbose stack     at EventEmitter.completion (C:\Users\feryardiant\AppData\Roaming\npm\node_modules\npm\lib\completion.js:50:13)
4 verbose stack     at Object.commandCache.(anonymous function) (C:\Users\feryardiant\AppData\Roaming\npm\node_modules\npm\lib\npm.js:124:13)
4 verbose stack     at EventEmitter.<anonymous> (C:\Users\feryardiant\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js:73:30)
4 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:67:7)
4 verbose stack     at process._tickCallback (internal/process/next_tick.js:98:9)
5 verbose cwd C:\tools\.babun\cygwin\home\feryardiant\.dotfiles
6 error Windows_NT 10.0.14393
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\feryardiant\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "completion"
8 error node v6.7.0
9 error npm  v3.10.5
10 error code ENOTSUP
11 error nospc npm completion supported only in MINGW / Git bash on Windows
12 error nospc This is most likely not a problem with npm itself
12 error nospc and is related to insufficient space on your system.
13 verbose exit [ 1, true ]
```

**Comment by emigenix** [comment]
Just for everybody's information, I've written a how-to for installing npm on Cygwin [here](https://github.com/emigenix/npm_on_cygwin). I think trying to avoid using any default windows installation and user home paths, help avoiding a lot of problems.
