### ISSUE TITLE
npm v3.10.5 Unexpected token ILLEGAL

### ISSUE THREAD

**Issue by dhanala89** [npm/npm#13622]
#### I'm opening this issue because:
- [x] npm is crashing.
#### What's going wrong?

Getting Unexpected token ILLEGAL when I try to install any package using npm. 
![npmerror](https://cloud.githubusercontent.com/assets/3652554/17539640/da3ca328-5f03-11e6-8dc6-f0e3a9f64caf.PNG)

**Comment by KenanY** [comment]
@dhanala89 Could you provide your `npm-debug.log` file as a [gist](https://gist.github.com/)?

**Comment by dhanala89** [comment]
[https://gist.github.com/dhanala89/9a69cf84ff760178ef9aedb172f1b010.js](url)

**Comment by dhanala89** [comment]
@KenanY 
[https://gist.github.com/dhanala89/9a69cf84ff760178ef9aedb172f1b010.js](https://gist.github.com/dhanala89/9a69cf84ff760178ef9aedb172f1b010.js)

**Comment by KenanY** [comment]
@dhanala89 Why is that a `.js` file?

**Comment by dhanala89** [comment]
@KenanY I was experimenting it and turned out to be a blunder. Corrected the link now. :)

**Comment by dhanala89** [comment]
@KenanY This happens everytime. Not sure what's the source of the problem. When I uninstall the whole node, delete all the files and folder, try to run npm install then it works and it lasts for sometime (20 to 30 mins) and goes back to this error. Pretty frustrating.
