### ISSUE TITLE
npm ERR! Darwin 15.5.0 npm ERR! 

### ISSUE THREAD

**Issue by amitbravo** [npm/npm#13623]
**I'm opening this issue because:**
 npm is producing an incorrect install.
 
**What's going wrong?**

when I use npm start in my terminal , this error comes

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/Cellar/node/6.3.1/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! path /Users/kabir/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/Users/kabir/package.json'
npm ERR! enoent ENOENT: no such file or directory, open '/Users/kabir/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kabir/Documents/reactnativeproject/npm-debug.log

supporting information:

    npm -v prints: 3.10.3
    node -v prints: 6.3.1
    npm config get registry prints: https://registry.npmjs.org/
    Windows, OS X, or Linux?: OS X EI capitan

**Comment by KenanY** [comment]
@amitbravo Does `/Users/kabir/package.json` exist?

**Comment by amitbravo** [comment]
nah. however, I fixed that changing PATHS , but it comes every now and then and I forget how to fix that, except I add few paths

**Comment by KenanY** [comment]
@amitbravo Doesn't sound like an issue with `npm`, so I'm gonna close this since this issue tracker is for bugs and feature requests.

**Comment by love626947341** [comment]
Do you  solve the promblem?I have  a same  problem.

**Comment by KenanY** [comment]
@love626947341 Open a new issue and fill out the support template, please :)
