### ISSUE TITLE
为什么会错

### ISSUE THREAD

**Issue by roger922222** [npm/npm#13637]
Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "lint"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5

npm ERR! missing script: lint

**Comment by KenanY** [comment]
@roger922222 Do you have a `"lint"` script defined in your `package.json`?

**Comment by KenanY** [comment]
Closing due to no response.
