### ISSUE TITLE
Unable to unpublish angular-base package

### ISSUE THREAD

**Issue by soumak77** [npm/npm#13632]
I need to unpublish this package: https://www.npmjs.com/package/angular-base.  I tried to run `npm unpublish angular-base --force` but I get an error:

> npm ERR! Registry returned 400 for DELETE on https://registry.npmjs.org/angular-base/-rev/1-fd7952f938fe91bbe61d96754cbfdba4

The above package is a duplicate of https://www.npmjs.com/package/angular-base-apps, which is why I'm trying to remove it from npm

**Comment by KenanY** [comment]
@soumak77 Have you tried emailing `support@npmjs.com` already?

**Comment by soumak77** [comment]
@KenanY not yet, doing so now

**Comment by soumak77** [comment]
support has resolved this issue
