### ISSUE TITLE
directory not empty, rename '/vagrant/node_modules/dom-serializer'

### ISSUE THREAD

**Issue by bmoe872** [npm/npm#13633]
[npm-debug.txt](https://github.com/npm/npm/files/412202/npm-debug.txt)
-> '/vagrant/node_modules/.dom-serializer.DELETE'
#### I'm opening this issue because:
- [X] npm is crashing.
- [X] npm is doing something I don't understand.
#### What's going wrong?

`npm install` using this package.json:

```
{
    "name": "some_app",
    "version": "0.0.0",
    "private": true,
    "scripts": {
        "dev": "BUILD_DEV=true webpack -d --watch",
        "postinstall": "webpack -p",
        "build-modernizr": "./node_modules/modernizr/bin/modernizr -c modernizr-config.json -d static/js/dist/modernizr.js"
    },
    "dependencies": {
        "autoprefixer": "6.3.7",
        "babel-core": "6.11.4",
        "babel-loader": "6.2.4",
        "babel-preset-es2015": "6.9.0",
        "babel-preset-react": "6.11.1",
        "extract-text-webpack-plugin": "1.0.1",
        "headroom.js": "0.9.3",
        "jshint": "2.9.2",
        "jshint-stylish-ex": "0.2.0",
        "jvectormap": "2.0.4",
        "less": "2.7.1",
        "modernizr": "3.3.1",
        "postcss-cli": "2.5.2",
        "react": "^15.3.0",
        "webpack": "1.13.1",
        "yuglify": "^0.1.4"
    }
}
```
### supporting information:
- `npm -v` prints: `3.10.3`
- `node -v` prints: `6.3.1`
- `npm config get registry` prints: `https://registry.npmjs.org/`
- Windows, OS X, or Linux?: OSX, running Xenial64 VM
- Container:
  - [X] I develop using Vagrant on OS X or Linux.

Error output:

```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN enoent ENOENT: no such file or directory, open '/vagrant/node_modules/babel-code-frame/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/vagrant/node_modules/doctrine/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/vagrant/node_modules/buffer/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/vagrant/node_modules/chalk/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/vagrant/node_modules/babel-traverse/package.json'
npm ERR! Linux 4.4.0-34-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! path /vagrant/node_modules/dom-serializer
npm ERR! code ENOTEMPTY
npm ERR! errno -39
npm ERR! syscall rename

npm ERR! ENOTEMPTY: directory not empty, rename '/vagrant/node_modules/dom-serializer' -> '/vagrant/node_modules/.dom-serializer.DELETE'
```

Im sure its something Im missing, but I can't seem to pinpoint what the issue is.

I have deleted the `.dom-serializer.DELETE` directory and tried to rerun it, but I get similar results.

**Comment by bmoe872** [comment]
I've been trying to chug away at this to see what the issue is. Im fairly certain that its an issue with where npm is being installed/where the node_modules are, but I am not sure WHY or HOW that is a problem. Still seeking help. Would be mucho appreciated.

**Comment by alecsammon** [comment]
Hi @bmoe872 - did you ever get a resolution to this issue? 

I am seeing the same problem. I'm using Ubuntu 16.04, Vagrant and VMWare Fusion. Using Virtualbox I am not seeing the same issue. My understanding so far is that it's related to vmhgfs-fuse, and some file cacheing issue.

**Comment by bmoe872** [comment]
Hey @alecsammon I installed yarn, ran yarn and everything worked. I never figured out the actual solution to this problem, but switching to yarn seems to have fixed it.

**Comment by alecsammon** [comment]
Hey @bmoe872 - thanks for the hint. Still having random filesystem problems - going to have to switch from VMWare to Virtualbox.

**Comment by bmoe872** [comment]
@alecsammon what vagrant box are you using? Could be that as well.
