### ISSUE TITLE
Very minor inconsistency in the output of a couple of registry endpoints

### ISSUE THREAD

**Issue by gaurav21r** [npm/npm#13631]
While developing a solution for **offline** npm registries, I noticed the npm client pinging 2 end points

`http://<registryURL>/<packagename>`
`http://<registryURL>/<packagename>/<version>`

Now the first returns a JSON with a `versions` key. I assume that `versions[<versionNumber>]` should be the same as the JSON returned from `http://<registryURL>/<packagename>/<version>`

I did a rought check on a few modules and it turns out there is just **ONE** difference.

As shown in the diff [here](http://tlrobinson.net/projects/javascript-fun/jsondiff/#%7B%22d%22%3A%7B%22a%22%3A%22%7B%5Cn%20%20%5C%22name%5C%22%3A%20%5C%22handlebars%5C%22%2C%5Cn%20%20%5C%22barename%5C%22%3A%20%5C%22handlebars%5C%22%2C%5Cn%20%20%5C%22version%5C%22%3A%20%5C%222.0.0%5C%22%2C%5Cn%20%20%5C%22description%5C%22%3A%20%5C%22Handlebars%20provides%20the%20power%20necessary%20to%20let%20you%20build%20semantic%20templates%20effectively%20with%20no%20frustration%5C%22%2C%5Cn%20%20%5C%22homepage%5C%22%3A%20%5C%22http%3A%2F%2Fwww.handlebarsjs.com%2F%5C%22%2C%5Cn%20%20%5C%22keywords%5C%22%3A%20%5B%5Cn%20%20%20%20%5C%22handlebars%5C%22%2C%5Cn%20%20%20%20%5C%22mustache%5C%22%2C%5Cn%20%20%20%20%5C%22template%5C%22%2C%5Cn%20%20%20%20%5C%22html%5C%22%5Cn%20%20%5D%2C%5Cn%20%20%5C%22repository%5C%22%3A%20%7B%5Cn%20%20%20%20%5C%22type%5C%22%3A%20%5C%22git%5C%22%2C%5Cn%20%20%20%20%5C%22url%5C%22%3A%20%5C%22https%3A%2F%2Fgithub.com%2Fwycats%2Fhandlebars.js.git%5C%22%5Cn%20%20%7D%2C%5Cn%20%20%5C%22author%5C%22%3A%20%7B%5Cn%20%20%20%20%5C%22name%5C%22%3A%20%5C%22Yehuda%20Katz%5C%22%5Cn%20%20%7D%2C%5Cn%20%20%5C%22license%5C%22%3A%20%5C%22MIT%5C%22%2C%5Cn%20%20%5C%22engines%5C%22%3A%20%7B%5Cn%20%20%20%20%5C%22node%5C%22%3A%20%5C%22%3E%3D0.4.7%5C%22%5Cn%20%20%7D%2C%5Cn%20%20%5C%22dependencies%5C%22%3A%20%7B%5Cn%20%20%20%20%5C%22optimist%5C%22%3A%20%5C%22~0.3%5C%22%2C%5Cn%20%20%20%20%5C%22uglify-js%5C%22%3A%20%5C%22~2.3%5C%22%5Cn%20%20%7D%2C%5Cn%20%20%5C%22optionalDependencies%5C%22%3A%20%7B%5Cn%20%20%20%20%5C%22uglify-js%5C%22%3A%20%5C%22~2.3%5C%22%5Cn%20%20%7D%2C%5Cn%20%20%5C%22devDependencies%5C%22%3A%20%7B%5Cn%20%20%20%20%5C%22async%5C%22%3A%20%5C%22~0.2.9%5C%22%2C%5Cn%20%20%20%20%5C%22aws-sdk%5C%22%3A%20%5C%22~1.5.0%5C%22%2C%5Cn%20%20%20%20%5C%22benchmark%5C%22%3A%20%5C%22~1.0%5C%22%2C%5Cn%20%20%20%20%5C%22dustjs-linkedin%5C%22%3A%20%5C%22~2.0.2%5C%22%2C%5Cn%20%20%20%20%5C%22eco%5C%22%3A%20%5C%22~1.1.0-rc-3%5C%22%2C%5Cn%20%20%20%20%5C%22es6-module-packager%5C%22%3A%20%5C%221.x%5C%22%2C%5Cn%20%20%20%20%5C%22grunt%5C%22%3A%20%5C%22~0.4.1%5C%22%2C%5Cn%20%20%20%20%5C%22grunt-cli%5C%22%3A%20%5C%22~0.1.10%5C%22%2C%5Cn%20%20%20%20%5C%22grunt-contrib-clean%5C%22%3A%20%5C%22~0.4.1%5C%22%2C%5Cn%20%20%20%20%5C%22grunt-contrib-concat%5C%22%3A%20%5C%22~0.3.0%5C%22%2C%5Cn%20%20%20%20%5C%22grunt-contrib-connect%5C%22%3A%20%5C%22~0.5.0%5C%22%2C%5Cn%20%20%20%20%5C%22grunt-contrib-copy%5C%22%3A%20%5C%22~0.4.1%5C%22%2C%5Cn%20%20%20%20%5C%22grunt-contrib-jshint%5C%22%3A%20%5C%220.x%5C%22%2C%5Cn%20%20%20%20%5C%22grunt-contrib-requirejs%5C%22%3A%20%5C%22~0.4.1%5C%22%2C%5Cn%20%20%20%20%5C%22grunt-contrib-uglify%5C%22%3A%20%5C%22~0.2.2%5C%22%2C%5Cn%20%20%20%20%5C%22grunt-contrib-watch%5C%22%3A%20%5C%22~0.5.3%5C%22%2C%5Cn%20%20%20%20%5C%22grunt-saucelabs%5C%22%3A%20%5C%228.x%5C%22%2C%5Cn%20%20%20%20%5C%22istanbul%5C%22%3A%20%5C%22%5E0.3.0%5C%22%2C%5Cn%20%20%20%20%5C%22jison%5C%22%3A%20%5C%22~0.3.0%5C%22%2C%5Cn%20%20%20%20%5C%22keen.io%5C%22%3A%20%5C%220.0.3%5C%22%2C%5Cn%20%20%20%20%5C%22mocha%5C%22%3A%20%5C%22~1.20.0%5C%22%2C%5Cn%20%20%20%20%5C%22mustache%5C%22%3A%20%5C%22~0.7.2%5C%22%2C%5Cn%20%20%20%20%5C%22semver%5C%22%3A%20%5C%22~2.1.0%5C%22%2C%5Cn%20%20%20%20%5C%22underscore%5C%22%3A%20%5C%22~1.5.1%5C%22%5Cn%20%20%7D%2C%5Cn%20%20%5C%22main%5C%22%3A%20%5C%22lib%2Findex.js%5C%22%2C%5Cn%20%20%5C%22bin%5C%22%3A%20%7B%5Cn%20%20%20%20%5C%22handlebars%5C%22%3A%20%5C%22bin%2Fhandlebars%5C%22%5Cn%20%20%7D%2C%5Cn%20%20%5C%22scripts%5C%22%3A%20%7B%5Cn%20%20%20%20%5C%22test%5C%22%3A%20%5C%22grunt%5C%22%5Cn%20%20%7D%2C%5Cn%20%20%5C%22gitHead%5C%22%3A%20%5C%221eb2b04aa1468059172af16968e28ba3a9c07e6d%5C%22%2C%5Cn%20%20%5C%22bugs%5C%22%3A%20%7B%5Cn%20%20%20%20%5C%22url%5C%22%3A%20%5C%22https%3A%2F%2Fgithub.com%2Fwycats%2Fhandlebars.js%2Fissues%5C%22%5Cn%20%20%7D%2C%5Cn%20%20%5C%22_id%5C%22%3A%20%5C%22handlebars%402.0.0%5C%22%2C%5Cn%20%20%5C%22_shasum%5C%22%3A%20%5C%226e9d7f8514a3467fa5e9f82cc158ecfc1d5ac76f%5C%22%2C%5Cn%20%20%5C%22_from%5C%22%3A%20%5C%22.%5C%22%2C%5Cn%20%20%5C%22_npmVersion%5C%22%3A%20%5C%221.4.21%5C%22%2C%5Cn%20%20%5C%22_npmUser%5C%22%3A%20%7B%5Cn%20%20%20%20%5C%22name%5C%22%3A%20%5C%22kpdecker%5C%22%2C%5Cn%20%20%20%20%5C%22email%5C%22%3A%20%5C%22kpdecker%40gmail.com%5C%22%5Cn%20%20%7D%2C%5Cn%20%20%5C%22maintainers%5C%22%3A%20%5B%5Cn%20%20%20%20%7B%5Cn%20%20%20%20%20%20%5C%22name%5C%22%3A%20%5C%22kpdecker%5C%22%2C%5Cn%20%20%20%20%20%20%5C%22email%5C%22%3A%20%5C%22kpdecker%40gmail.com%5C%22%5Cn%20%20%20%20%7D%5Cn%20%20%5D%2C%5Cn%20%20%5C%22dist%5C%22%3A%20%7B%5Cn%20%20%20%20%5C%22shasum%5C%22%3A%20%5C%226e9d7f8514a3467fa5e9f82cc158ecfc1d5ac76f%5C%22%2C%5Cn%20%20%20%20%5C%22tarball%5C%22%3A%20%5C%22https%3A%2F%2Fregistry.npmjs.org%2Fhandlebars%2F-%2Fhandlebars-2.0.0.tgz%5C%22%5Cn%20%20%7D%2C%5Cn%20%20%5C%22directories%5C%22%3A%20%7B%7D%5Cn%7D%22%2C%22b%22%3A%22%7B%5Cn%20%20%5C%22name%5C%22%3A%20%5C%22handlebars%5C%22%2C%5Cn%20%20%5C%22barename%5C%22%3A%20%5C%22handlebars%5C%22%2C%5Cn%20%20%5C%22version%5C%22%3A%20%5C%222.0.0%5C%22%2C%5Cn%20%20%5C%22description%5C%22%3A%20%5C%22Handlebars%20provides%20the%20power%20necessary%20to%20let%20you%20build%20semantic%20templates%20effectively%20with%20no%20frustration%5C%22%2C%5Cn%20%20%5C%22homepage%5C%22%3A%20%5C%22http%3A%2F%2Fwww.handlebarsjs.com%2F%5C%22%2C%5Cn%20%20%5C%22keywords%5C%22%3A%20%5B%5Cn%20%20%20%20%5C%22handlebars%5C%22%2C%5Cn%20%20%20%20%5C%22mustache%5C%22%2C%5Cn%20%20%20%20%5C%22template%5C%22%2C%5Cn%20%20%20%20%5C%22html%5C%22%5Cn%20%20%5D%2C%5Cn%20%20%5C%22repository%5C%22%3A%20%7B%5Cn%20%20%20%20%5C%22type%5C%22%3A%20%5C%22git%5C%22%2C%5Cn%20%20%20%20%5C%22url%5C%22%3A%20%5C%22https%3A%2F%2Fgithub.com%2Fwycats%2Fhandlebars.js.git%5C%22%5Cn%20%20%7D%2C%5Cn%20%20%5C%22author%5C%22%3A%20%7B%5Cn%20%20%20%20%5C%22name%5C%22%3A%20%5C%22Yehuda%20Katz%5C%22%5Cn%20%20%7D%2C%5Cn%20%20%5C%22license%5C%22%3A%20%5C%22MIT%5C%22%2C%5Cn%20%20%5C%22engines%5C%22%3A%20%7B%5Cn%20%20%20%20%5C%22node%5C%22%3A%20%5C%22%3E%3D0.4.7%5C%22%5Cn%20%20%7D%2C%5Cn%20%20%5C%22dependencies%5C%22%3A%20%7B%5Cn%20%20%20%20%5C%22optimist%5C%22%3A%20%5C%22~0.3%5C%22%2C%5Cn%20%20%20%20%5C%22uglify-js%5C%22%3A%20%5C%22~2.3%5C%22%5Cn%20%20%7D%2C%5Cn%20%20%5C%22optionalDependencies%5C%22%3A%20%7B%5Cn%20%20%20%20%5C%22uglify-js%5C%22%3A%20%5C%22~2.3%5C%22%5Cn%20%20%7D%2C%5Cn%20%20%5C%22devDependencies%5C%22%3A%20%7B%5Cn%20%20%20%20%5C%22async%5C%22%3A%20%5C%22~0.2.9%5C%22%2C%5Cn%20%20%20%20%5C%22aws-sdk%5C%22%3A%20%5C%22~1.5.0%5C%22%2C%5Cn%20%20%20%20%5C%22benchmark%5C%22%3A%20%5C%22~1.0%5C%22%2C%5Cn%20%20%20%20%5C%22dustjs-linkedin%5C%22%3A%20%5C%22~2.0.2%5C%22%2C%5Cn%20%20%20%20%5C%22eco%5C%22%3A%20%5C%22~1.1.0-rc-3%5C%22%2C%5Cn%20%20%20%20%5C%22es6-module-packager%5C%22%3A%20%5C%221.x%5C%22%2C%5Cn%20%20%20%20%5C%22grunt%5C%22%3A%20%5C%22~0.4.1%5C%22%2C%5Cn%20%20%20%20%5C%22grunt-cli%5C%22%3A%20%5C%22~0.1.10%5C%22%2C%5Cn%20%20%20%20%5C%22grunt-contrib-clean%5C%22%3A%20%5C%22~0.4.1%5C%22%2C%5Cn%20%20%20%20%5C%22grunt-contrib-concat%5C%22%3A%20%5C%22~0.3.0%5C%22%2C%5Cn%20%20%20%20%5C%22grunt-contrib-connect%5C%22%3A%20%5C%22~0.5.0%5C%22%2C%5Cn%20%20%20%20%5C%22grunt-contrib-copy%5C%22%3A%20%5C%22~0.4.1%5C%22%2C%5Cn%20%20%20%20%5C%22grunt-contrib-jshint%5C%22%3A%20%5C%220.x%5C%22%2C%5Cn%20%20%20%20%5C%22grunt-contrib-requirejs%5C%22%3A%20%5C%22~0.4.1%5C%22%2C%5Cn%20%20%20%20%5C%22grunt-contrib-uglify%5C%22%3A%20%5C%22~0.2.2%5C%22%2C%5Cn%20%20%20%20%5C%22grunt-contrib-watch%5C%22%3A%20%5C%22~0.5.3%5C%22%2C%5Cn%20%20%20%20%5C%22grunt-saucelabs%5C%22%3A%20%5C%228.x%5C%22%2C%5Cn%20%20%20%20%5C%22istanbul%5C%22%3A%20%5C%22%5E0.3.0%5C%22%2C%5Cn%20%20%20%20%5C%22jison%5C%22%3A%20%5C%22~0.3.0%5C%22%2C%5Cn%20%20%20%20%5C%22keen.io%5C%22%3A%20%5C%220.0.3%5C%22%2C%5Cn%20%20%20%20%5C%22mocha%5C%22%3A%20%5C%22~1.20.0%5C%22%2C%5Cn%20%20%20%20%5C%22mustache%5C%22%3A%20%5C%22~0.7.2%5C%22%2C%5Cn%20%20%20%20%5C%22semver%5C%22%3A%20%5C%22~2.1.0%5C%22%2C%5Cn%20%20%20%20%5C%22underscore%5C%22%3A%20%5C%22~1.5.1%5C%22%5Cn%20%20%7D%2C%5Cn%20%20%5C%22main%5C%22%3A%20%5C%22lib%2Findex.js%5C%22%2C%5Cn%20%20%5C%22bin%5C%22%3A%20%7B%5Cn%20%20%20%20%5C%22handlebars%5C%22%3A%20%5C%22bin%2Fhandlebars%5C%22%5Cn%20%20%7D%2C%5Cn%20%20%5C%22scripts%5C%22%3A%20%7B%5Cn%20%20%20%20%5C%22test%5C%22%3A%20%5C%22grunt%5C%22%5Cn%20%20%7D%2C%5Cn%20%20%5C%22gitHead%5C%22%3A%20%5C%221eb2b04aa1468059172af16968e28ba3a9c07e6d%5C%22%2C%5Cn%20%20%5C%22bugs%5C%22%3A%20%7B%5Cn%20%20%20%20%5C%22url%5C%22%3A%20%5C%22https%3A%2F%2Fgithub.com%2Fwycats%2Fhandlebars.js%2Fissues%5C%22%5Cn%20%20%7D%2C%5Cn%20%20%5C%22_id%5C%22%3A%20%5C%22handlebars%402.0.0%5C%22%2C%5Cn%20%20%5C%22_shasum%5C%22%3A%20%5C%226e9d7f8514a3467fa5e9f82cc158ecfc1d5ac76f%5C%22%2C%5Cn%20%20%5C%22_from%5C%22%3A%20%5C%22.%5C%22%2C%5Cn%20%20%5C%22_npmVersion%5C%22%3A%20%5C%221.4.21%5C%22%2C%5Cn%20%20%5C%22_npmUser%5C%22%3A%20%7B%5Cn%20%20%20%20%5C%22name%5C%22%3A%20%5C%22kpdecker%5C%22%2C%5Cn%20%20%20%20%5C%22email%5C%22%3A%20%5C%22kpdecker%40gmail.com%5C%22%5Cn%20%20%7D%2C%5Cn%20%20%5C%22maintainers%5C%22%3A%20%5B%5Cn%20%20%20%20%7B%5Cn%20%20%20%20%20%20%5C%22name%5C%22%3A%20%5C%22kpdecker%5C%22%2C%5Cn%20%20%20%20%20%20%5C%22email%5C%22%3A%20%5C%22kpdecker%40gmail.com%5C%22%5Cn%20%20%20%20%7D%5Cn%20%20%5D%2C%5Cn%20%20%5C%22dist%5C%22%3A%20%7B%5Cn%20%20%20%20%5C%22shasum%5C%22%3A%20%5C%226e9d7f8514a3467fa5e9f82cc158ecfc1d5ac76f%5C%22%2C%5Cn%20%20%20%20%5C%22tarball%5C%22%3A%20%5C%22http%3A%2F%2Fregistry.npmjs.org%2Fhandlebars%2F-%2Fhandlebars-2.0.0.tgz%5C%22%5Cn%20%20%7D%2C%5Cn%20%20%5C%22directories%5C%22%3A%20%7B%7D%5Cn%7D%22%7D%7D) for **Handlebars**.

The difference as we can see is just the `dist/tarball`key having a difference of http and https. I have 2 questions.

1. Is there a guarantee both should produce the same result? If not, why not? Wouldn't it greatly simply the design of the npm registry itself? Instead of storing what seems to be **the same** data twice, we can actually save space!

2. If there is a difference, is it only a difference of http and https? Or is it just that this the only difference showing in the few npm modules I tested? 

I know this is a very minor issue, but it helps guarantee my solution to the users. It also simplifies the design of my cache registry. I think a lot of users would benefit from my registry and I plan to Open Source it the moment I've done my final testing. Incase I need to submit any PR to do the above, I would be more than happy to since I feel it is (most probably) a quick fix!

Thank you for your time!

**Comment by othiym23** [comment]
> Is there a guarantee both should produce the same result?

No.

> If not, why not?

A variety of reasons:

1. One of those routes (the latter) is a byproduct of the design of CouchDB's RESTful API when used in couchapps.
2. The contract for this piece of the registry API is pretty loose, having not been formally documented beyond the test suite for [`npm-registry-couchapp`](https://github.com/npm/npm-registry-couchapp).
3. `npm-registry-couchapp` is no longer the full story when it comes to the primary registry's behavior, as CouchDB sits behind a host of microservices that add various bits of functionality like caching, ACLs, and the like.
4. The paths that are returned by the registry in the first route pattern's choice have been switched to return HTTPS because that was a common community request. That's the route that's hit by the CLI.

> Wouldn't it greatly simply the design of the npm registry itself? Instead of storing what seems to be the same data twice, we can actually save space!

The packages are the same – the only difference is whether they're served via HTTP and HTTPS. The metadata is a little different, and if you have clients (that are not the CLI, which only uses the endpoints receiving HTTPS URLs) that are hitting both routes, they may not cache correctly unless you generate eTags based on the package tarballs themselves _or_ use `Last-Modified` headers.

> If there is a difference, is it only a difference of http and https?

Most likely, but you'd have to ask the [registry team](https://github.com/npm/registry/issues) to confirm. That's not an area for which the CLI team is responsible.

Since mostly these are questions for the registry team, I'm going to close this and forward you on over there. You should totally take any remaining questions you have to them, though, because it's in everybody's best interests to ensure that it be as simple as possible to come up with a standard, interoperable registry API. See also https://github.com/npm/npm/issues/5828#issuecomment-239080544 for discussion about where the registry team may be headed. Thanks for your time!
