### ISSUE TITLE
npm publish "error: do not have permission"

### ISSUE THREAD

**Issue by dodospace** [npm/npm#13646]
npm ERR! publish Failed PUT 403
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "publish"
npm ERR! node v4.4.2
npm ERR! npm  v3.8.9
npm ERR! code E403

npm ERR! you do not have permission to publish "react-full-page". Are you logged in as the correct user? : react-full-page
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR! <https://github.com/npm/npm/issues>

**Comment by dodospace** [comment]
I got it, Module name being used

**Comment by othiym23** [comment]
Closing as resolved.

**Comment by NeedAChange** [comment]
change  module name

**Comment by xfeng-studio** [comment]
因为最初的http://registry.npmjs.org这个源国内用户访问非常慢，所以一开始我们可能换成了国内淘宝的镜像：http://registry.npm.taobao.org。但是淘宝这个镜像没有开放上传的权限，因此会报这样的错误：

npm ERR! publish Failed PUT 403

npm ERR! Error: no_perms Private modeenable, only admin can publish this module: nodebb-plugin-route-cms

有至少两种方法：

1）修改~/.npmrc中的registry字段（命令：vi ~/.npmrc）
2）直接在命令行修改即可。
命令：npm set registry http://registry.npmjs.org
