### ISSUE TITLE
npm ERR! code UNABLE_TO_VERIFY_LEAF_SIGNATURE

### ISSUE THREAD

**Issue by divyeshk03** [npm/npm#13640]
i am getting this error while installing in netbeans 8.1  laravel project

"C:\Program Files\nodejs\npm.cmd" "install"
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Users\SONY\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.5
npm ERR! code UNABLE_TO_VERIFY_LEAF_SIGNATURE

npm ERR! unable to verify the first certificate
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     H:\wamp\bin\apache\apache2.4.18\htdocs\demo\npm-debug.log
Done.

**Comment by mcmahonjohn** [comment]
I am getting this error as well. I removed my node_modules directory to get a fresh pull and now, I can't run the application because of this error message.
