### ISSUE TITLE
npm install workshopp error |Windows 10

### ISSUE THREAD

**Issue by JuankBregar** [npm/npm#13641]
I tried to install javascripting worshopp and get this error:

C:\WINDOWS\system32>npm install -g javascripting
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "javascripting"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8

npm ERR! shasum check failed for C:\Users\Juank\AppData\Local\Temp\npm-6680-1081b98c\registry.npmjs.org\javascripting\-\javascripting-2.6.0.tgz
npm ERR! Expected: f31fb59ebb18e21e611ca16b243ea040c9bd57bc
npm ERR! Actual:   72974c6673f8df2626f39f349f7c9b5e88262fbe
npm ERR! From:     https://registry.npmjs.org/javascripting/-/javascripting-2.6.0.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\WINDOWS\system32\npm-debug.log

Help plis
----------------------------------
npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'javascripting' ]
2 info using npm@2.15.8
3 info using node@v4.4.7
4 verbose install initial load of C:\Users\Juank\AppData\Roaming\npm\package.json
5 verbose readDependencies loading dependencies from C:\Users\Juank\AppData\Roaming\npm\package.json
6 silly cache add args [ 'javascripting', null ]
7 verbose cache add spec javascripting
8 silly cache add parsed spec Result {
8 silly cache add   raw: 'javascripting',
8 silly cache add   scope: null,
8 silly cache add   name: 'javascripting',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: 'latest',
8 silly cache add   type: 'tag' }
9 silly addNamed javascripting@latest
10 verbose addNamed "latest" is being treated as a dist-tag for javascripting
11 info addNameTag [ 'javascripting', 'latest' ]
12 silly mapToRegistry name javascripting
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry data Result {
15 silly mapToRegistry   raw: 'javascripting',
15 silly mapToRegistry   scope: null,
15 silly mapToRegistry   name: 'javascripting',
15 silly mapToRegistry   rawSpec: '',
15 silly mapToRegistry   spec: 'latest',
15 silly mapToRegistry   type: 'tag' }
16 silly mapToRegistry uri https://registry.npmjs.org/javascripting
17 verbose addNameTag registry:https://registry.npmjs.org/javascripting not in flight; fetching
18 verbose request uri https://registry.npmjs.org/javascripting
19 verbose request no auth needed
20 info attempt registry request try #1 at 13:06:19
21 verbose request id 7b2f118caf07a344
22 verbose etag "98ZD5T522SVEZYETHYUFI0CNJ"
23 http request GET https://registry.npmjs.org/javascripting
24 http 304 https://registry.npmjs.org/javascripting
25 verbose headers { date: 'Thu, 11 Aug 2016 19:06:22 GMT',
25 verbose headers   via: '1.1 varnish',
25 verbose headers   'cache-control': 'max-age=300',
25 verbose headers   etag: '"98ZD5T522SVEZYETHYUFI0CNJ"',
25 verbose headers   age: '0',
25 verbose headers   connection: 'keep-alive',
25 verbose headers   'x-served-by': 'cache-mia1324-MIA',
25 verbose headers   'x-cache': 'HIT',
25 verbose headers   'x-cache-hits': '1',
25 verbose headers   'x-timer': 'S1470942382.596259,VS0,VE177',
25 verbose headers   vary: 'Accept-Encoding' }
26 silly get cb [ 304,
26 silly get   { date: 'Thu, 11 Aug 2016 19:06:22 GMT',
26 silly get     via: '1.1 varnish',
26 silly get     'cache-control': 'max-age=300',
26 silly get     etag: '"98ZD5T522SVEZYETHYUFI0CNJ"',
26 silly get     age: '0',
26 silly get     connection: 'keep-alive',
26 silly get     'x-served-by': 'cache-mia1324-MIA',
26 silly get     'x-cache': 'HIT',
26 silly get     'x-cache-hits': '1',
26 silly get     'x-timer': 'S1470942382.596259,VS0,VE177',
26 silly get     vary: 'Accept-Encoding' } ]
27 verbose etag https://registry.npmjs.org/javascripting from cache
28 verbose get saving javascripting to C:\Users\Juank\AppData\Roaming\npm-cache\registry.npmjs.org\javascripting\.cache.json
29 verbose correctMkdir C:\Users\Juank\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
30 silly addNameTag next cb for javascripting with tag latest
31 silly addNamed javascripting@2.6.0
32 verbose addNamed "2.6.0" is a plain semver version for javascripting
33 silly mapToRegistry name javascripting
34 silly mapToRegistry using default registry
35 silly mapToRegistry registry https://registry.npmjs.org/
36 silly mapToRegistry data Result {
36 silly mapToRegistry   raw: 'javascripting',
36 silly mapToRegistry   scope: null,
36 silly mapToRegistry   name: 'javascripting',
36 silly mapToRegistry   rawSpec: '',
36 silly mapToRegistry   spec: 'latest',
36 silly mapToRegistry   type: 'tag' }
37 silly mapToRegistry uri https://registry.npmjs.org/javascripting
38 verbose addRemoteTarball https://registry.npmjs.org/javascripting/-/javascripting-2.6.0.tgz not in flight; adding
39 verbose addRemoteTarball [ 'https://registry.npmjs.org/javascripting/-/javascripting-2.6.0.tgz',
39 verbose addRemoteTarball   'f31fb59ebb18e21e611ca16b243ea040c9bd57bc' ]
40 info retry fetch attempt 1 at 13:06:21
41 info attempt registry request try #1 at 13:06:21
42 http fetch GET https://registry.npmjs.org/javascripting/-/javascripting-2.6.0.tgz
43 http fetch 200 https://registry.npmjs.org/javascripting/-/javascripting-2.6.0.tgz
44 info retry will retry, error on last attempt: Error: read ECONNRESET
45 info retry will retry, error on last attempt: Error: read ECONNRESET
46 silly fetchAndShaCheck shasum f31fb59ebb18e21e611ca16b243ea040c9bd57bc
47 verbose stack Error: shasum check failed for C:\Users\Juank\AppData\Local\Temp\npm-6680-1081b98c\registry.npmjs.org\javascripting\-\javascripting-2.6.0.tgz
47 verbose stack Expected: f31fb59ebb18e21e611ca16b243ea040c9bd57bc
47 verbose stack Actual:   72974c6673f8df2626f39f349f7c9b5e88262fbe
47 verbose stack From:     https://registry.npmjs.org/javascripting/-/javascripting-2.6.0.tgz
47 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:25:8
47 verbose stack     at ReadStream.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:72:7)
47 verbose stack     at emitNone (events.js:72:20)
47 verbose stack     at ReadStream.emit (events.js:166:7)
47 verbose stack     at endReadableNT (_stream_readable.js:921:12)
47 verbose stack     at nextTickCallbackWith2Args (node.js:442:9)
47 verbose stack     at process._tickCallback (node.js:356:17)
48 verbose cwd C:\WINDOWS\system32
49 error Windows_NT 10.0.10586
50 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "javascripting"
51 error node v4.4.7
52 error npm  v2.15.8
53 error shasum check failed for C:\Users\Juank\AppData\Local\Temp\npm-6680-1081b98c\registry.npmjs.org\javascripting\-\javascripting-2.6.0.tgz
53 error Expected: f31fb59ebb18e21e611ca16b243ea040c9bd57bc
53 error Actual:   72974c6673f8df2626f39f349f7c9b5e88262fbe
53 error From:     https://registry.npmjs.org/javascripting/-/javascripting-2.6.0.tgz
54 error If you need help, you may report this error at:
54 error     <https://github.com/npm/npm/issues>
55 verbose exit [ 1, true ]

**Comment by JuankBregar** [comment]
Just update my npm, works fine

**Comment by zmengle** [comment]
who can help me

**Comment by JuankBregar** [comment]
@zmengle if you have the same error message check your npm version using npm --version you should have 3.10.5 or higher, if don't run npm -g install npm
That works for me, check again your version and if still is not the lastes probably want to read this article 
http://stackoverflow.com/questions/26908899/how-do-i-update-npm-on-windows
Then just install the workshop following the nodeschool instructions
