### ISSUE TITLE
Please help me:cannot read the dependencies, hence failed at installing dependencies 求助

### ISSUE THREAD

**Issue by Amber711** [npm/npm#13649]
the following error report shows up while I am trying to create an Express project:

Error creating Node.js Express App. Failed command:
"C:\Program Files\node.exe" "C:\Program Files\node_modules\npm\bin\npm-cli.js" install
Exit code: 1
Standard error:
npm ERR! install Couldn't read dependencies
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\node.exe" "C:\\Program Files\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.4.0
npm ERR! npm  v2.14.20

npm ERR! Invalid name: "food ordering2"
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\mac Air\WebstormProjects\food ordering2\npm-debug.log

after i press ok, there do exist the package.json, and inside it, it tells what dependencies I need, but why the error says it can not read my dependencies?

does any one ever encounter this? please help me if you know how to deal with it. ^ ^

**Comment by KenanY** [comment]
@Amber711 Could you try not having a space in your project name?

**Comment by Amber711** [comment]
@KenanY  It does work! Thank you so much!!
