### ISSUE TITLE
Unable to install bower

### ISSUE THREAD

**Issue by maheshbhuvanagiri** [npm/npm#13645]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'bower' ]
2 info using npm@3.10.3
3 info using node@v6.3.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData bower
8 silly fetchNamedPackageData bower
9 silly mapToRegistry name bower
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'bower',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'bower',
12 silly mapToRegistry   name: 'bower',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/bower
14 verbose request uri https://registry.npmjs.org/bower
15 verbose request no auth needed
16 info attempt registry request try #1 at 7:26:23 AM
17 verbose request id 33399945e0ca4e65
18 http request GET https://registry.npmjs.org/bower
19 info retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.44.162:443
20 info attempt registry request try #2 at 7:26:54 AM
21 http request GET https://registry.npmjs.org/bower
22 info retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.44.162:443
23 info attempt registry request try #3 at 7:28:15 AM
24 http request GET https://registry.npmjs.org/bower
25 silly fetchPackageMetaData Error: connect ETIMEDOUT 151.101.44.162:443
25 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1012:11)
25 silly fetchPackageMetaData     at exports._exceptionWithHostPort (util.js:1035:20)
25 silly fetchPackageMetaData     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
25 silly fetchPackageMetaData  error for bower { Error: connect ETIMEDOUT 151.101.44.162:443
25 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1012:11)
25 silly fetchPackageMetaData     at exports._exceptionWithHostPort (util.js:1035:20)
25 silly fetchPackageMetaData     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
25 silly fetchPackageMetaData   code: 'ETIMEDOUT',
25 silly fetchPackageMetaData   errno: 'ETIMEDOUT',
25 silly fetchPackageMetaData   syscall: 'connect',
25 silly fetchPackageMetaData   address: '151.101.44.162',
25 silly fetchPackageMetaData   port: 443 }
26 silly rollbackFailedOptional Starting
27 silly rollbackFailedOptional Finishing
28 silly runTopLevelLifecycles Starting
29 silly runTopLevelLifecycles Finishing
30 silly install printInstalled
31 verbose stack Error: connect ETIMEDOUT 151.101.44.162:443
31 verbose stack     at Object.exports._errnoException (util.js:1012:11)
31 verbose stack     at exports._exceptionWithHostPort (util.js:1035:20)
31 verbose stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
32 verbose cwd C:\Windows\system32
33 error Windows_NT 6.1.7601

#### How can the CLI team reproduce the problem?

  I have installed NodeJs , npm and git...while trying to install bower with 
 npm command  -> npm install -g bower
unable to install it

**Comment by KenanY** [comment]
@maheshbhuvanagiri This looks like an issue with your internet connect, not with `npm`. The log indicated that your connection to the registry is timing out. Are you perhaps behind a proxy or firewall? Does this also occur if you connect to a different network?

**Comment by maheshbhuvanagiri** [comment]
This issue has been solved.. i have followed the instructions as per this.
https://jjasonclark.com/how-to-setup-node-behind-web-proxy​
