### ISSUE TITLE
Error installing npm & electron

### ISSUE THREAD

**Issue by LimaniBhavik** [npm/npm#13657]
![image](https://cloud.githubusercontent.com/assets/6619586/17641519/180e8966-6141-11e6-9be1-d619aa014e09.png)

done all possible try 
install
uninstall
clear cache

**Comment by watilde** [comment]
Hello! The error seems to come from electron itself instead of npm. Here is some similar reports that may will help you: https://github.com/electron-userland/electron-prebuilt/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20econnreset
