### ISSUE TITLE
ERR!404, Darwin 15.4.0  while installing wiredep. npm install wiredep--save-dev

### ISSUE THREAD

**Issue by cammaro08** [npm/npm#13658]
Fahads-Air:library talhasheikh$ npm install wiredep--save-dev
npm WARN package.json library@1.0.0 No description
npm WARN package.json library@1.0.0 No repository field.
npm WARN package.json library@1.0.0 No README data
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "wiredep--save-dev"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/wiredep--save-dev
npm ERR! 404 
npm ERR! 404 'wiredep--save-dev' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'library'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/talhasheikh/dev/code/library/npm-debug.log
Fahads-Air:library talhasheikh$

**Comment by KenanY** [comment]
@cammaro08 Add a space between `wiredep` and `--save-dev`.

**Comment by cammaro08** [comment]
Thank you! It works! 💃
