### ISSUE TITLE
Install module from private GitHub repo on Heroku

### ISSUE THREAD

**Issue by zamith** [npm/npm#13652]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [x] npm is producing an incorrect install.
- [ ] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
#### What's going wrong?

I need to install a GitHub private repo as part of the build process on Heroku. Locally I was using `git+ssh` and it works fine, but since Heroku does not have my ssh keys I was moving to `git+https` with a PAT and `x-oauth-basic` authentication. So, my URL looks like this:

```
git+https://<token>:x-oauth-basic@github.com:<user>/<repo>.git#305b129
```

If I do `npm install URL --save`, it is being saved as `git+ssh://git@github.com/<user>/<repo>.git#305b129`, and even if I write it on `package.json` by hand, when I run `npm install` it tries to install the ssh version, which fails on Heroku. 
#### How can the CLI team reproduce the problem?

I'm assuming that by running the command I mentioned above you should be able to reproduce this.
### supporting information:
- `npm -v` prints: 3.10.6
- `node -v` prints: v6.3.1
- `npm config get registry` prints: https://registry.npmjs.org/
- Windows, OS X, or Linux?: OS X

**Comment by favorit** [comment]
We have fixed it just by small change to URL:

```git+https://<token>:x-oauth-basic@github.com**/**<user>/<repo>.git#305b129```

**Comment by sarovin** [comment]
I have this error on my osx:

```
npm ERR! addLocal Could not install /Users/sarovin/Projects/openshift/myapp/node_modules/ReactComonent/github.com/sarovinvin/ReactComonent.git
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/7.0.0/bin/node" "/usr/local/bin/npm" "i"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.9
npm ERR! path /Users/sarovin/Projects/openshift/myapp/node_modules/ReactComonent/github.com/sarovin/ReactComonent.git
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/Users/sarovin/Projects/openshift/myapp/node_modules/ReactComonent/github.com/sarovinvin/ReactComonent.git'
npm ERR! enoent ENOENT: no such file or directory, open '/Users/sarovin/Projects/openshift/myapp/node_modules/ReactComonent/github.com/sarovinvin/ReactComonent.git'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/sarovin/Projects/openshift/myapp/npm-debug.log
The last command took 424 seconds.
```

**Comment by legodude17** [comment]
Does @favorit's solution work for you @zamith?

**Comment by zamith** [comment]
I'm not currently working on this project, but when I am I'll test it out. Until then I think it's ok to close and I'll reopen if it doesn't work.
