### ISSUE TITLE
installing browser-sync

### ISSUE THREAD

**Issue by orege** [npm/npm#13653]
#### I'm opening this issue because:

  -the browser-sync installation gives error

#### What's going wrong?
the iinformation at the cli seems to point my network proxy
#### How can the CLI team reproduce the problem?
please help me with the proper npm configs. here is the screenshot of my cli:
![screenshot from 2016-08-12 19-03-26](https://cloud.githubusercontent.com/assets/20994340/17629130/86223d74-60c1-11e6-9404-899552c4a627.png)

### supporting information:

 - `npm -v` prints: 3.5.2
 - `node -v` prints: v4.2.6
 - Linux
 - Network issues:
   - Geographic location where npm was run:
     - [ ] I use a proxy to connect to the web.

**Comment by KenanY** [comment]
@orege Perhaps [this blog post](https://jjasonclark.com/how-to-setup-node-behind-web-proxy) might help?

**Comment by KenanY** [comment]
Closing as abandoned.
