### ISSUE TITLE
npm install email-templates failing

### ISSUE THREAD

**Issue by dbarallat** [npm/npm#13666]
Hi,

I'm struggling installing "email-templates", see attached npm log:
 npm install email-templates
npm http GET https://registry.npmjs.org/email-templates
npm http 304 https://registry.npmjs.org/email-templates
npm http GET https://registry.npmjs.org/consolidate
npm http GET https://registry.npmjs.org/juice
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/glob
npm http GET https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/bluebird
npm http 304 https://registry.npmjs.org/glob
npm http 304 https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/consolidate
npm http 304 https://registry.npmjs.org/lodash
npm http 304 https://registry.npmjs.org/bluebird
npm http 304 https://registry.npmjs.org/juice
npm http GET https://registry.npmjs.org/inflight
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/path-is-absolute
npm http GET https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/once
npm http GET https://registry.npmjs.org/ms/0.7.1
npm http 304 https://registry.npmjs.org/once
npm http 304 https://registry.npmjs.org/minimatch
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/path-is-absolute
npm http 304 https://registry.npmjs.org/inflight
npm http 304 https://registry.npmjs.org/ms/0.7.1
npm http GET https://registry.npmjs.org/wrappy
npm http GET https://registry.npmjs.org/brace-expansion
npm http 304 https://registry.npmjs.org/wrappy
npm http GET https://registry.npmjs.org/deep-extend
npm http 304 https://registry.npmjs.org/brace-expansion
npm http GET https://registry.npmjs.org/web-resource-inliner/2.0.0
npm http GET https://registry.npmjs.org/slick/1.12.2
npm http GET https://registry.npmjs.org/batch/0.5.3
npm http GET https://registry.npmjs.org/cheerio/0.20.0
npm http GET https://registry.npmjs.org/cssom/0.3.1
npm http GET https://registry.npmjs.org/commander/2.9.0
npm http GET https://registry.npmjs.org/cross-spawn-async
npm http GET https://registry.npmjs.org/balanced-match
npm http GET https://registry.npmjs.org/concat-map/0.0.1
npm http 304 https://registry.npmjs.org/deep-extend
npm http 304 https://registry.npmjs.org/web-resource-inliner/2.0.0
npm http 304 https://registry.npmjs.org/commander/2.9.0
npm http 304 https://registry.npmjs.org/slick/1.12.2
npm http 304 https://registry.npmjs.org/balanced-match
npm http 304 https://registry.npmjs.org/cheerio/0.20.0
npm http 304 https://registry.npmjs.org/cssom/0.3.1
npm http 304 https://registry.npmjs.org/batch/0.5.3
npm http 304 https://registry.npmjs.org/concat-map/0.0.1
npm http 304 https://registry.npmjs.org/cross-spawn-async
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
npm WARN engine deep-extend@0.4.1: wanted: {"node":">=0.12.0","iojs":">=1.0.0"} (current: {"node":"v0.10.25","npm":"1.3.10"})
npm WARN engine web-resource-inliner@2.0.0: wanted: {"node":">=4.0.0"} (current: {"node":"v0.10.25","npm":"1.3.10"})
npm http GET https://registry.npmjs.org/graceful-readlink
npm http GET https://registry.npmjs.org/which
npm http GET https://registry.npmjs.org/lru-cache
npm http GET https://registry.npmjs.org/htmlparser2
npm http GET https://registry.npmjs.org/dom-serializer
npm http GET https://registry.npmjs.org/jsdom
npm http GET https://registry.npmjs.org/css-select
npm http GET https://registry.npmjs.org/entities
npm http 304 https://registry.npmjs.org/lru-cache
npm http 304 https://registry.npmjs.org/which
npm http 304 https://registry.npmjs.org/jsdom
npm http 304 https://registry.npmjs.org/dom-serializer
npm http 304 https://registry.npmjs.org/entities
npm http 304 https://registry.npmjs.org/htmlparser2
npm http 304 https://registry.npmjs.org/graceful-readlink
npm http GET https://registry.npmjs.org/pseudomap
npm http GET https://registry.npmjs.org/yallist
npm http GET https://registry.npmjs.org/isexe
npm http 304 https://registry.npmjs.org/css-select
npm http 304 https://registry.npmjs.org/yallist
npm http 304 https://registry.npmjs.org/pseudomap
npm http 304 https://registry.npmjs.org/isexe
npm http GET https://registry.npmjs.org/domelementtype
npm http GET https://registry.npmjs.org/css-what
npm http GET https://registry.npmjs.org/domutils/1.5.1
npm http GET https://registry.npmjs.org/boolbase
npm http GET https://registry.npmjs.org/nth-check
npm http 304 https://registry.npmjs.org/domelementtype
npm ERR! error rolling back Error: ENOTEMPTY, rmdir '/var/www/api.lifteye.dev/node_modules/email-templates/node_modules/juice/node_modules/web-resource-inliner'
npm ERR! error rolling back  juice@2.0.0 { [Error: ENOTEMPTY, rmdir '/var/www/api.lifteye.dev/node_modules/email-templates/node_modules/juice/node_modules/web-resource-inliner']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: '/var/www/api.lifteye.dev/node_modules/email-templates/node_modules/juice/node_modules/web-resource-inliner' }
npm http GET https://registry.npmjs.org/datauri
npm http GET https://registry.npmjs.org/cli-color
npm http GET https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/xtend
npm http GET https://registry.npmjs.org/request
npm http 304 https://registry.npmjs.org/domutils/1.5.1
npm http 304 https://registry.npmjs.org/css-what
npm http 304 https://registry.npmjs.org/nth-check
npm http 304 https://registry.npmjs.org/boolbase
npm http GET https://registry.npmjs.org/uglify-js
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/clean-css/1.1.7
npm http 304 https://registry.npmjs.org/lodash
npm http 304 https://registry.npmjs.org/xtend
npm http 304 https://registry.npmjs.org/request
npm http 304 https://registry.npmjs.org/uglify-js
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/datauri
npm ERR! error rolling back Error: UNKNOWN, unlink '/var/www/api.lifteye.dev/node_modules/email-templates/node_modules/lodash/isInteger.js'
npm ERR! error rolling back  email-templates@2.4.1 { [Error: UNKNOWN, unlink '/var/www/api.lifteye.dev/node_modules/email-templates/node_modules/lodash/isInteger.js']
npm ERR! error rolling back   errno: -1,
npm ERR! error rolling back   code: 'UNKNOWN',
npm ERR! error rolling back   path: '/var/www/api.lifteye.dev/node_modules/email-templates/node_modules/lodash/isInteger.js' }
npm ERR! Error: UNKNOWN, symlink '../which/bin/which'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-86-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "email-templates"
npm ERR! cwd /var/www/api.lifteye.dev
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path ../which/bin/which
npm ERR! code UNKNOWN
npm ERR! errno -1
npm http 304 https://registry.npmjs.org/cli-color
npm http 304 https://registry.npmjs.org/clean-css/1.1.7
npm ERR! Error: ENOENT, open '/var/www/api.lifteye.dev/node_modules/email-templates/node_modules/juice/node_modules/cheerio/node_modules/htmlparser2/test/Events/03-lowercase_tags.json'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-86-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "email-templates"
npm ERR! cwd /var/www/api.lifteye.dev
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /var/www/api.lifteye.dev/node_modules/email-templates/node_modules/juice/node_modules/cheerio/node_modules/htmlparser2/test/Events/03-lowercase_tags.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! error rolling back Error: UNKNOWN, unlink '/var/www/api.lifteye.dev/node_modules/email-templates/node_modules/juice/node_modules/cheerio/node_modules/jsdom/lib/jsdom/browser/default-stylesheet.js'
npm ERR! error rolling back  cheerio@0.20.0 { [Error: UNKNOWN, unlink '/var/www/api.lifteye.dev/node_modules/email-templates/node_modules/juice/node_modules/cheerio/node_modules/jsdom/lib/jsdom/browser/default-stylesheet.js']
npm ERR! error rolling back   errno: -1,
npm ERR! error rolling back   code: 'UNKNOWN',
npm ERR! error rolling back   path: '/var/www/api.lifteye.dev/node_modules/email-templates/node_modules/juice/node_modules/cheerio/node_modules/jsdom/lib/jsdom/browser/default-stylesheet.js' }
npm http GET https://registry.npmjs.org/mimer
npm http GET https://registry.npmjs.org/templayed
npm http GET https://registry.npmjs.org/readable-stream
npm http GET https://registry.npmjs.org/domhandler
npm http GET https://registry.npmjs.org/domutils
npm http GET https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/readable-stream
npm http 304 https://registry.npmjs.org/mimer
npm http 304 https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/commander
npm http GET https://registry.npmjs.org/d
npm http GET https://registry.npmjs.org/es5-ext
npm http GET https://registry.npmjs.org/memoizee
npm http GET https://registry.npmjs.org/timers-ext
npm http 304 https://registry.npmjs.org/domhandler
npm http 304 https://registry.npmjs.org/es5-ext
npm http 304 https://registry.npmjs.org/commander
npm http 304 https://registry.npmjs.org/d
npm http 304 https://registry.npmjs.org/domutils
npm http 304 https://registry.npmjs.org/templayed
npm http 304 https://registry.npmjs.org/memoizee
npm http 304 https://registry.npmjs.org/timers-ext
npm http GET https://registry.npmjs.org/bl
npm http GET https://registry.npmjs.org/combined-stream
npm http GET https://registry.npmjs.org/caseless
npm http GET https://registry.npmjs.org/extend
npm http GET https://registry.npmjs.org/forever-agent
npm http GET https://registry.npmjs.org/form-data
npm http GET https://registry.npmjs.org/har-validator
npm http GET https://registry.npmjs.org/http-signature
npm http GET https://registry.npmjs.org/hawk
npm http GET https://registry.npmjs.org/is-typedarray
npm http GET https://registry.npmjs.org/isstream
npm http GET https://registry.npmjs.org/json-stringify-safe
npm http GET https://registry.npmjs.org/mime-types
npm http GET https://registry.npmjs.org/node-uuid
npm http GET https://registry.npmjs.org/qs
npm http GET https://registry.npmjs.org/oauth-sign
npm http GET https://registry.npmjs.org/stringstream
npm http GET https://registry.npmjs.org/tough-cookie
npm http GET https://registry.npmjs.org/tunnel-agent
npm http GET https://registry.npmjs.org/aws-sign2
npm http GET https://registry.npmjs.org/aws4
npm ERR! error rolling back Error: UNKNOWN, unlink '/var/www/api.lifteye.dev/node_modules/email-templates/node_modules/juice/node_modules/web-resource-inliner/node_modules/lodash/index.js'
npm ERR! error rolling back  web-resource-inliner@2.0.0 { [Error: UNKNOWN, unlink '/var/www/api.lifteye.dev/node_modules/email-templates/node_modules/juice/node_modules/web-resource-inliner/node_modules/lodash/index.js']
npm ERR! error rolling back   errno: -1,
npm ERR! error rolling back   code: 'UNKNOWN',
npm ERR! error rolling back   path: '/var/www/api.lifteye.dev/node_modules/email-templates/node_modules/juice/node_modules/web-resource-inliner/node_modules/lodash/index.js' }
npm http 304 https://registry.npmjs.org/bl
npm ERR! Error: ENOENT, chmod '/var/www/api.lifteye.dev/node_modules/email-templates/node_modules/juice/node_modules/web-resource-inliner/node_modules/cli-color/node_modules/es5-ext/global.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-86-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "email-templates"
npm ERR! cwd /var/www/api.lifteye.dev
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /var/www/api.lifteye.dev/node_modules/email-templates/node_modules/juice/node_modules/web-resource-inliner/node_modules/cli-color/node_modules/es5-ext/global.js
npm ERR! fstream_path /var/www/api.lifteye.dev/node_modules/email-templates/node_modules/juice/node_modules/web-resource-inliner/node_modules/cli-color/node_modules/es5-ext/global.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! fstream_finish_call chmod
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:305:19
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm http 304 https://registry.npmjs.org/caseless
npm http 304 https://registry.npmjs.org/combined-stream
npm http 304 https://registry.npmjs.org/forever-agent
npm http 304 https://registry.npmjs.org/extend
npm http 304 https://registry.npmjs.org/form-data
npm http 304 https://registry.npmjs.org/har-validator
npm http 304 https://registry.npmjs.org/http-signature
npm http 304 https://registry.npmjs.org/hawk
npm http 304 https://registry.npmjs.org/isstream
npm http 304 https://registry.npmjs.org/is-typedarray
npm ERR! Error: ENOENT, chmod '/var/www/api.lifteye.dev/node_modules/email-templates/node_modules/juice/node_modules/web-resource-inliner/node_modules/cli-color/node_modules/d/test'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-86-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "email-templates"
npm ERR! cwd /var/www/api.lifteye.dev
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /var/www/api.lifteye.dev/node_modules/email-templates/node_modules/juice/node_modules/web-resource-inliner/node_modules/cli-color/node_modules/d/test
npm ERR! fstream_path /var/www/api.lifteye.dev/node_modules/email-templates/node_modules/juice/node_modules/web-resource-inliner/node_modules/cli-color/node_modules/d/test/auto-bind.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! fstream_finish_call setupMadeDir
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack end (/usr/lib/nodejs/fstream/lib/writer.js:319:21)
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:336:20
npm ERR! fstream_stack next (/usr/lib/nodejs/fstream/lib/writer.js:366:20)
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm http 304 https://registry.npmjs.org/json-stringify-safe
npm http 304 https://registry.npmjs.org/mime-types
npm http 304 https://registry.npmjs.org/node-uuid
npm http 304 https://registry.npmjs.org/qs
npm http 304 https://registry.npmjs.org/oauth-sign
npm http 304 https://registry.npmjs.org/stringstream
npm http 304 https://registry.npmjs.org/tough-cookie
npm http 304 https://registry.npmjs.org/tunnel-agent
npm http 304 https://registry.npmjs.org/aws-sign2
npm http 304 https://registry.npmjs.org/aws4
npm WARN engine hawk@3.1.3: wanted: {"node":">=0.10.32"} (current: {"node":"v0.10.25","npm":"1.3.10"})
npm ERR! error rolling back Error: ENOTEMPTY, rmdir '/var/www/api.lifteye.dev/node_modules/email-templates/node_modules/juice/node_modules/web-resource-inliner/node_modules/htmlparser2/node_modules/domhandler/test/cases'
npm ERR! error rolling back  htmlparser2@3.9.1 { [Error: ENOTEMPTY, rmdir '/var/www/api.lifteye.dev/node_modules/email-templates/node_modules/juice/node_modules/web-resource-inliner/node_modules/htmlparser2/node_modules/domhandler/test/cases']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: '/var/www/api.lifteye.dev/node_modules/email-templates/node_modules/juice/node_modules/web-resource-inliner/node_modules/htmlparser2/node_modules/domhandler/test/cases' }
npm ERR! error rolling back Error: UNKNOWN, unlink '/var/www/api.lifteye.dev/node_modules/email-templates/node_modules/juice/node_modules/web-resource-inliner/node_modules/cli-color/node_modules/memoizee/normalizers/get.js'
npm ERR! error rolling back  cli-color@0.3.3 { [Error: UNKNOWN, unlink '/var/www/api.lifteye.dev/node_modules/email-templates/node_modules/juice/node_modules/web-resource-inliner/node_modules/cli-color/node_modules/memoizee/normalizers/get.js']
npm ERR! error rolling back   errno: -1,
npm ERR! error rolling back   code: 'UNKNOWN',
npm ERR! error rolling back   path: '/var/www/api.lifteye.dev/node_modules/email-templates/node_modules/juice/node_modules/web-resource-inliner/node_modules/cli-color/node_modules/memoizee/normalizers/get.js' }
npm http GET https://registry.npmjs.org/delayed-stream
npm http GET https://registry.npmjs.org/mime-db
npm http 304 https://registry.npmjs.org/mime-db
npm http 304 https://registry.npmjs.org/delayed-stream
npm http GET https://registry.npmjs.org/readable-stream
npm http GET https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/readable-stream
npm http 304 https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/assert-plus
npm http GET https://registry.npmjs.org/jsprim
npm http GET https://registry.npmjs.org/sshpk
npm http 304 https://registry.npmjs.org/sshpk
npm http 304 https://registry.npmjs.org/jsprim
npm http 304 https://registry.npmjs.org/assert-plus
npm http GET https://registry.npmjs.org/chalk
npm http GET https://registry.npmjs.org/is-my-json-valid
npm http GET https://registry.npmjs.org/pinkie-promise
npm ERR! error rolling back Error: UNKNOWN, unlink '/var/www/api.lifteye.dev/node_modules/email-templates/node_modules/juice/node_modules/web-resource-inliner/node_modules/request/node_modules/qs/test/utils.js'
npm ERR! error rolling back  request@2.74.0 { [Error: UNKNOWN, unlink '/var/www/api.lifteye.dev/node_modules/email-templates/node_modules/juice/node_modules/web-resource-inliner/node_modules/request/node_modules/qs/test/utils.js']
npm ERR! error rolling back   errno: -1,
npm ERR! error rolling back   code: 'UNKNOWN',
npm ERR! error rolling back   path: '/var/www/api.lifteye.dev/node_modules/email-templates/node_modules/juice/node_modules/web-resource-inliner/node_modules/request/node_modules/qs/test/utils.js' }
npm ERR! Error: ENOENT, lstat '/var/www/api.lifteye.dev/node_modules/email-templates/node_modules/juice/node_modules/web-resource-inliner/node_modules/request/node_modules/bl/node_modules/readable-stream/transform.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-86-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "email-templates"
npm ERR! cwd /var/www/api.lifteye.dev
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /var/www/api.lifteye.dev/node_modules/email-templates/node_modules/juice/node_modules/web-resource-inliner/node_modules/request/node_modules/bl/node_modules/readable-stream/transform.js
npm ERR! fstream_path /var/www/api.lifteye.dev/node_modules/email-templates/node_modules/juice/node_modules/web-resource-inliner/node_modules/request/node_modules/bl/node_modules/readable-stream/transform.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm http 304 https://registry.npmjs.org/chalk
npm http 304 https://registry.npmjs.org/pinkie-promise
npm http 304 https://registry.npmjs.org/is-my-json-valid
npm http GET https://registry.npmjs.org/extsprintf/1.0.2
npm http GET https://registry.npmjs.org/json-schema/0.2.2
npm http GET https://registry.npmjs.org/verror/1.3.6
npm http GET https://registry.npmjs.org/pinkie
npm http 304 https://registry.npmjs.org/verror/1.3.6
npm http 304 https://registry.npmjs.org/json-schema/0.2.2
npm http 304 https://registry.npmjs.org/extsprintf/1.0.2
npm http GET https://registry.npmjs.org/ansi-styles
npm http GET https://registry.npmjs.org/escape-string-regexp
npm http GET https://registry.npmjs.org/has-ansi
npm http GET https://registry.npmjs.org/supports-color
npm http GET https://registry.npmjs.org/strip-ansi
npm http 304 https://registry.npmjs.org/pinkie
npm http 304 https://registry.npmjs.org/strip-ansi
npm http 304 https://registry.npmjs.org/ansi-styles
npm http 304 https://registry.npmjs.org/escape-string-regexp
npm http 304 https://registry.npmjs.org/supports-color
npm http 304 https://registry.npmjs.org/has-ansi
npm http GET https://registry.npmjs.org/ansi-regex
npm http 304 https://registry.npmjs.org/ansi-regex
npm http GET https://registry.npmjs.org/jsbn
npm http GET https://registry.npmjs.org/tweetnacl
npm http GET https://registry.npmjs.org/jodid25519
npm http GET https://registry.npmjs.org/ecc-jsbn
npm http GET https://registry.npmjs.org/asn1
npm http GET https://registry.npmjs.org/dashdash
npm http GET https://registry.npmjs.org/getpass
npm http 304 https://registry.npmjs.org/asn1
npm http 304 https://registry.npmjs.org/jodid25519
npm http 304 https://registry.npmjs.org/tweetnacl
npm http 304 https://registry.npmjs.org/jsbn
npm http 304 https://registry.npmjs.org/ecc-jsbn
npm http 304 https://registry.npmjs.org/dashdash
npm http 304 https://registry.npmjs.org/getpass
npm http GET https://registry.npmjs.org/jsonpointer/2.0.0
npm http GET https://registry.npmjs.org/generate-function
npm http GET https://registry.npmjs.org/generate-object-property
npm http 304 https://registry.npmjs.org/generate-object-property
npm http 304 https://registry.npmjs.org/generate-function
npm http 304 https://registry.npmjs.org/jsonpointer/2.0.0
npm WARN optional dep failed, continuing jsdom@7.2.2
npm http GET https://registry.npmjs.org/is-property
npm http 304 https://registry.npmjs.org/is-property
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /var/www/api.lifteye.dev/npm-debug.log
npm ERR! not ok code 0

Thanks !!

Dani

**Comment by legodude17** [comment]
Is this the contents of npm-debug.log? If not please put that file in a gist and link to it here.

**Comment by KenanY** [comment]
@dbarallat `npm@1.3` is **years** old and is no longer supported. Please try [updating](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) first.

**Comment by KenanY** [comment]
Closing as abandoned/probably-fixed-by-non-ancient-versions-of-npm.

**Comment by KenanY** [comment]
Whoops, missed the close somehow.
