### ISSUE TITLE
npm ERR! Darwin 15.0.0

### ISSUE THREAD

**Issue by MajorShen** [npm/npm#13661]
AA1:~ apple$ react-native init AwesomeProject
This will walk you through creating a new React Native project in /Users/apple/AwesomeProject
Installing react-native package from npm...
      	
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/Cellar/node/6.3.1/bin/node" "/usr/local/bin/npm" "install" "--save" "--save-exact" "react-native"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3

npm ERR! shasum check failed for /var/folders/ym/48x4j0655w9bz9gqctpk3mdc0000gn/T/npm-4232-a6fd797b/registry.npmjs.org/q/-/q-1.4.1.tgz
npm ERR! Expected: 55705bcd93c5f3673530c2c2cbc0c2b3addc286e
npm ERR! Actual:   7f128062e95699d68b8dfcfc52aaf8f9ddf7519f
npm ERR! From:     https://registry.npmjs.org/q/-/q-1.4.1.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/apple/AwesomeProject/npm-debug.log

`npm install --save --save-exact react-native` failed

**Comment by KenanY** [comment]
@MajorShen Have you tried running `npm cache clean`?

**Comment by KenanY** [comment]
Closing as abandoned, and very likely to not be an issue with `npm` anyways.
