### ISSUE TITLE
NPM run test (Karma) fails always in Windows

### ISSUE THREAD

**Issue by vivinRajagopalan** [npm/npm#13674]
#### I'm opening this issue because:

  - [x] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?

Actual behavior

This is the test script that has been configured in package.json
"test": "node --max-old-space-size=4096 ./node_modules/.bin/karma start"
BUT WHEN i try to execute it, it always error. Please find the below file for npm debug
[npmdebugfile.txt](https://github.com/npm/npm/files/419076/npmdebugfile.txt)

Please let me know what can be done.

I have the latest node js installed and working too !.

### supporting information:

 - `npm -v` prints: 3.10.6
 - `node -v` prints:6.3.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X, or Linux?: Windows

Thanks in advance

**Comment by KenanY** [comment]
@vivinRajagopalan Does it work if you run that command manually (rather than through an `npm` script)?

**Comment by vivinRajagopalan** [comment]
@KenanY 
Thanks for the quick response.
No i still get the same error :(

**Comment by vivinRajagopalan** [comment]
even a NPM search[any-package] gives me an out of memory error 
"FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory"......
That's y i tried increasing the memory but it aint working

**Comment by KenanY** [comment]
@vivinRajagopalan If the command does not work outside of an `npm` script, then it is not going to work within an `npm` script. As such, this does not sound like an issue with `npm` to me.

`npm search` is currently broken; there are so many packages in the registry now that it exceeds the JavaScript heap. This is a known issue: https://github.com/npm/npm/issues/12619.

**Comment by KenanY** [comment]
Closing since this is not an issue with `npm`.
