### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by wenbing** [npm/npm#13679]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

$ npm shrinkwrap
npm ERR! Darwin 15.6.0
npm ERR! argv "node" "/Users/zwb/.nvm/versions/node/v0.12.15/bin/npm" "shrinkwrap"
npm ERR! node v0.12.15
npm ERR! npm  v3.10.6

npm ERR! Maximum call stack size exceeded
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/zwb/workspace/fep/static-manage/npm-debug.log

### supporting information:

 - `npm -v` prints:3.10.5
 - `node -v` prints:v4.4.4
 - `npm config get registry` prints:
 - Windows, OS X, or Linux?:OS X
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by wenbing** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli   '/Users/zwb/.nvm/versions/node/v0.12.15/bin/npm',
1 verbose cli   'shrinkwrap' ]
2 info using npm@3.10.6
3 info using node@v0.12.15
4 info lifecycle @mtfe/static-manage@1.0.0~preshrinkwrap: @mtfe/static-manage@1.0.0
5 silly lifecycle @mtfe/static-manage@1.0.0~preshrinkwrap: no script for preshrinkwrap, continuing
6 verbose stack RangeError: Maximum call stack size exceeded
6 verbose stack     at Object.hasOwnProperty (native)
6 verbose stack     at isArguments (/Users/zwb/.nvm/versions/node/v0.12.15/lib/node_modules/npm/node_modules/aproba/index.js:4:47)
6 verbose stack     at Array.types.A (/Users/zwb/.nvm/versions/node/v0.12.15/lib/node_modules/npm/node_modules/aproba/index.js:9:68)
6 verbose stack     at module.exports (/Users/zwb/.nvm/versions/node/v0.12.15/lib/node_modules/npm/node_modules/aproba/index.js:22:18)
6 verbose stack     at moduleName (/Users/zwb/.nvm/versions/node/v0.12.15/lib/node_modules/npm/lib/utils/module-name.js:25:3)
6 verbose stack     at exports.isOnlyDev (/Users/zwb/.nvm/versions/node/v0.12.15/lib/node_modules/npm/lib/install/is-dev.js:39:45)
6 verbose stack     at /Users/zwb/.nvm/versions/node/v0.12.15/lib/node_modules/npm/lib/install/is-dev.js:33:14
6 verbose stack     at Array.every (native)
6 verbose stack     at exports.isOnlyDev (/Users/zwb/.nvm/versions/node/v0.12.15/lib/node_modules/npm/lib/install/is-dev.js:39:26)
6 verbose stack     at /Users/zwb/.nvm/versions/node/v0.12.15/lib/node_modules/npm/lib/install/is-dev.js:33:14
7 verbose cwd /Users/zwb/workspace/fep/static-manage
8 error Darwin 15.6.0
9 error argv "node" "/Users/zwb/.nvm/versions/node/v0.12.15/bin/npm" "shrinkwrap"
10 error node v0.12.15
11 error npm  v3.10.6
12 error Maximum call stack size exceeded
13 error If you need help, you may report this error at:
13 error     <https://github.com/npm/npm/issues>
14 verbose exit [ 1, true ]

**Comment by franher** [comment]
duplicated => https://github.com/npm/npm/issues/13327
resolved on `npm@3.10.7`
