### ISSUE TITLE
Tell NPM to not use my proxy settings to fetch deps from github

### ISSUE THREAD

**Issue by bboulahdid** [npm/npm#13673]
Is there a way to tell NPM to NOT use my proxy settings to fetch deps from github ?!

**Comment by KenanY** [comment]
@bboulahdid There currently does not exist a means of configuring `npm` to _not_ use your proxy for GitHub deps specifically. So, I guess you're requesting a new feature?

**Comment by davemcgowan** [comment]
would adding the github domain to the no_proxy environment var / config item not work?

**Comment by bboulahdid** [comment]
@davemcgowan I already used the no_proxy env. var. with no result :(
As a temporary solution, I downloaded the missing dependency and used `npm link`

**Comment by sarvaniupadrasta** [comment]
u can use the following commands to remove proxy
npm config delete http-proxy
npm config delete https-proxy

npm config rm proxy
npm config rm https-proxy

**Comment by bboulahdid** [comment]
Does `npm` support the `no_proxy` environment variable?!
