### ISSUE TITLE
conflict between shrinkwrap and lastest version

### ISSUE THREAD

**Issue by vizonluo** [npm/npm#13686]
#### I'm opening this issue because:
- npm is doing something I don't understand.
#### What's going wrong?

Some of my dependencies set their dependencies's version to be 'latest'. I install and shrinkwrap then a fixed version of packages was written in my shrinkwrap.json. It's ok.
But if any one of their 'latest' dependencies update version，when I shrinkwrap, npm will report error 

```
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9

npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! invalid: have try-shrinkwrap-latest@1.0.1 (expected: latest) try-shrinkwrap-latest-example/node_modules/try-shrinkwrap-latest
npm ERR! extraneous: try-shrinkwrap-latest@1.0.1 try-shrinkwrap-latest-example/node_modules/try-shrinkwrap-latest
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
```

I don't understand this. I want to fix version of my dependencies and don't care whether they were set 'lastest' or whether they update.

Is this a feature or bug?
### supporting information:
- `npm -v` prints: 3.8.9
- `node -v` prints: v6.2.0
- Windows, OS X, or Linux?: OS X

**Comment by palortoff** [comment]
An example package would be `ascli`

`npm install` without `npm-shrinkwrap.json` results in:
```
`-- ascli@1.0.0
  +-- colour@0.7.1
  `-- optjs@3.2.2
```

`npm install` with `npm-shrinkwrap.json` results in:
```
+-- ascli@1.0.0
| +-- colour@0.7.1
| `-- optjs@3.2.2
+-- colour@0.7.1
`-- optjs@3.2.2
```
