### ISSUE TITLE
error when running gulp command

### ISSUE THREAD

**Issue by rusrazvan** [npm/npm#13688]
**when I run  npm run gulp I receive this:**
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'gulp' ]
2 info using npm@3.10.3
3 info using node@v6.3.1
4 verbose stack Error: missing script: gulp
4 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:151:19)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:61:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:356:5
4 verbose stack     at checkBinReferences_ (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:320:45)
4 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:354:3)
4 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:124:5)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:243:12
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
4 verbose stack     at tryToString (fs.js:455:3)
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
5 verbose cwd C:\xampp\htdocs\todoparrot
6 error Windows_NT 10.0.14393
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "gulp"
8 error node v6.3.1
9 error npm  v3.10.3
10 error missing script: gulp
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
**also when I run gulp I receive this**
(node:13836) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
C:\xampp\htdocs\todoparrot\node_modules\laravel-elixir\GulpPaths.js:100
        if (path.indexOf('./') == 0) {
                ^

TypeError: Cannot read property 'indexOf' of undefined
    at prefixOne (C:\xampp\htdocs\todoparrot\node_modules\laravel-elixir\GulpPaths.js:100:17)
    at GulpPaths.prefix (C:\xampp\htdocs\todoparrot\node_modules\laravel-elixir\GulpPaths.js:120:12)
    at GulpPaths.src (C:\xampp\htdocs\todoparrot\node_modules\laravel-elixir\GulpPaths.js:20:16)
    at prepGulpPaths (C:\xampp\htdocs\todoparrot\node_modules\laravel-elixir\tasks\coffee.js:55:10)
    at Function.<anonymous> (C:\xampp\htdocs\todoparrot\node_modules\laravel-elixir\tasks\coffee.js:19:17)
    at Function.<anonymous> (C:\xampp\htdocs\todoparrot\node_modules\laravel-elixir\index.js:40:18)
    at C:\xampp\htdocs\todoparrot\gulpfile.js:16:6
    at Elixir (C:\xampp\htdocs\todoparrot\node_modules\laravel-elixir\index.js:16:5)
    at Object.<anonymous> (C:\xampp\htdocs\todoparrot\gulpfile.js:14:1)
    at Module._compile (module.js:541:32)
**I tried to fix it following this steps [http://stackoverflow.com/questions/24027551/gulp-command-not-found-error-after-installing-gulp/24042936#24042936](url) but with no success. Any ideas?**

**Comment by legodude17** [comment]
The first one is saying you don't have a script called gulp. The second one is most likely a problem with `gulp` or `laravel-elixir`.
