### ISSUE TITLE
Strange handling of pattern rules in .npmignore

### ISSUE THREAD

**Issue by zhibirc** [npm/npm#13687]
**Configuration:**

GNU/Linux Mint 17.3 Rosa
NPM: v. 3.9.5
NODE: v. 6.3.x

.npmignore ignores `!<rule>` rules and depending on where is `*` in it (at the beginning or end) operation result changes (different files are ignored)

**Comment by legodude17** [comment]
I am on
Ubuntu 15.04
npm 3.10.5
node 6.0.0

My .npmignore was
```
build
!build/index.js
```
and it worked fine. Please give an example of when it was ignore rules, and try updating node and npm (but mostly node).

**Comment by KenanY** [comment]
Closing due to no response. Can reopen once a test case is provided.
