### ISSUE TITLE
Feature Request: flag or cli arg to add `npm rebuild` to `npm install` lifecycle

### ISSUE THREAD

**Issue by MylesBorins** [npm/npm#13684]
#### What's the feature?

a new flag or cli arg that would include `npm rebuild` as part of the `npm install` lifecycle

`npm install --rebuild`
#### What problem is the feature intended to solve?

Primarily I'm thinking about using this as part of citgm. It would be nice to be able to include it as a flag or argument and not have to instrument `npm rebuild` as it's own task
#### Is the absence of this feature blocking you or your team? If so, how?

Not exactly. But I would much rather write the code / tests as part of npm core as opposed to citgm.
#### Is this feature similar to an existing feature in another tool?

N/A
#### Is this a feature you're prepared to implement, with support from the npm CLI team?

Absolutely

**Comment by TheAlphaNerd** [comment]
it is also possible this already exists, which would be rad. I just could not find anything documented

**Comment by legodude17** [comment]
You could set the `preinstall` or `postinstall` scripts to `npm rebuild`.

**Comment by TheAlphaNerd** [comment]
I'm imagining wanting to use this feature as a consumer of another module

**Comment by legodude17** [comment]
So you don't have control of the scripts? I get it.

**Comment by MylesBorins** [comment]
sounds like this can mostly be accomplished with
`npm install <module> --build-from-source` for pre-gyp
