### ISSUE TITLE
NPM mongodb install error

### ISSUE THREAD

**Issue by Santhoshwoir** [npm/npm#13683]
#### I'm opening this issue because:

 
  - [ ] npm is producing an incorrect install.

#### What's going wrong?

Trying to install npm mongodb module and the command fails with the following error message,

npm ERR! registry error parsing json
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "ins
tall" "mongodb"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8

npm ERR! Unexpected token <
npm ERR! <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
npm ERR! <HTML><HEAD><TITLE>Bad Request</TITLE>
npm ERR! <META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
npm ERR! <BODY><h2>Bad Request - Invalid Hostname</h2>
npm ERR! <hr><p>HTTP Error 400. The request hostname is invalid.</p>
npm ERR! </BODY></HTML>

**Comment by KenanY** [comment]
@Santhoshwoir Are you behind a proxy or firewall?

**Comment by KenanY** [comment]
Closing due to no response.
