### ISSUE TITLE
npm install comand shows "npm ERR! registry error parsing json"

### ISSUE THREAD

**Issue by mchisty** [npm/npm#13697]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [YES ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
As I am running npm from behind a corporate firewall. I have configured it as follows:
npm config set registry http://registry.npmjs.org/
npm config set http-proxy http://username:password@ip:port
npm config set https-proxy http://username:password@ip:port
npm set strict-ssl false

So running the "npm install" command does not show the proxy error anymore. However now it shows a new error like this "npm ERR! registry error parsing json"

log attached: https://gist.github.com/mchisty/4ee3d3174579c37990e003e64fed6ec4

#### How can the CLI team reproduce the problem?
No idea. Perhaps you can tell them to run "npm install" from behind a Government firewall proxy e.g. like FBI, CIA, US Medicare, ATO, NSW DET or any other highly secured government organizations.

npm-debug.log URL: https://gist.github.com/mchisty/4ee3d3174579c37990e003e64fed6ec4

### supporting information:

 - `npm -v` prints: 3.8.9
 - `node -v` prints: v6.2.0
 - `npm config get registry` prints: http://registry.npmjs.org/
 - Windows, OS X, or Linux?: Windows7
 - Network issues:
   - Geographic location where npm was run: Parramatta, NSW 2150, Sydney, Australia
   - [ YES] I use a proxy to connect to the npm registry.
   - [ YES] I use a proxy to connect to the web.
   - [ YES] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
Hint:
```
Use [x] for checked boxes.
```
It looks like http://registry.npmjs.org/@angular%2fhttp is returning non-json. Try going there in a browser.

**Comment by mchisty** [comment]
Okay.

I just tried from the beginning. I simply uninstalled and the reinstalled
nodejs following the guide on
https://docs.npmjs.com/getting-started/installing-node.
NodeJS installed fine. But whenever I try to execute the command (from the
offical doc):

npm install npm -g


Then the following error shows up in console:

C:\Utilities\NodeJS>npm install npm -g
npm ERR! not a package C:\Utilities\NodeJS\npm
npm ERR! addLocal Could not install C:\Utilities\NodeJS\npm
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Utilities\\NodeJS\\node.exe"
"C:\\Utilities\\NodeJS\\node_modules\\npm\\bin\\npm-cli.js" "install" "npm"
"-g"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.3
npm ERR! path
C:\Users\isadmlc\AppData\Local\Temp\npm-1248-a7e0058c\unpack-b072a2a9\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open
'C:\Users\isadmlc\AppData\Local\Temp\npm-1248-a7e0058c\unpack-b072a2a9\package.json'
npm ERR! enoent ENOENT: no such file or directory, open
'C:\Users\isadmlc\AppData\Local\Temp\npm-1248-a7e0058c\unpack-b072a2a9\package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Utilities\NodeJS\npm-debug.log


I think that NPM update is always on issue when working behind a corporate
firewall (as you have seen in my post , I already configured proxy/firewall
properly). In general scenario, it is not a problem at all.

Thanks,
... Chisty

P.S. Log file attached

**Comment by legodude17** [comment]
Now it looks like npm is thinking that you want to install a local package instead of the remote npm package. I believe that this is either a bug or a quirk in your corporate firewall. What do you think @KenanY?

**Comment by KenanY** [comment]
@mchisty Hmm, try running `npm install -g npm` from somewhere other than `C:\Utilities\NodeJS`? Or, try running just `npm install npm@latest` (no `-g`) whilst in that directory.

**Comment by KenanY** [comment]
Closing as abandoned.
