### ISSUE TITLE
TypeError when installing rho-contracts

### ISSUE THREAD

**Issue by mcandre** [npm/npm#13690]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I can install some packages via npm, but others like rho-contracts make NPM error and die.

#### How can the CLI team reproduce the problem?

In PowerShell:

```
PS C:\> npm install rho-contracts:0.0.5
npm http GET https://registry.npmjs.org/rho-contracts%3A0.0.5
npm http 404 https://registry.npmjs.org/rho-contracts%3A0.0.5
npm ERR! TypeError: Object.keys called on non-object
npm ERR!     at Function.keys (native)
npm ERR!     at next_ (C:\Users\andrew\AppData\Roaming\nvm\v0.8.0\node_modules\npm\lib\cache.js:441:35)
npm ERR!     at next (C:\Users\andrew\AppData\Roaming\nvm\v0.8.0\node_modules\npm\lib\cache.js:427:44)
npm ERR!     at C:\Users\andrew\AppData\Roaming\nvm\v0.8.0\node_modules\npm\lib\cache.js:419:5
npm ERR!     at saved (C:\Users\andrew\AppData\Roaming\nvm\v0.8.0\node_modules\npm\node_modules\npm-registry-client\lib\get.js:136:7)
npm ERR!     at C:\Users\andrew\AppData\Roaming\nvm\v0.8.0\node_modules\npm\node_modules\npm-registry-client\lib\get.js:164:20
npm ERR!     at C:\Users\andrew\AppData\Roaming\nvm\v0.8.0\node_modules\npm\node_modules\mkdirp\index.js:51:17
npm ERR!     at Object.oncomplete (fs.js:297:15)
npm ERR!  [TypeError: Object.keys called on non-object]
npm ERR! You may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "rho-contracts:0.0.5"
npm ERR! cwd C:\Users\andrew\src\node-ios7crypt
npm ERR! node -v v0.8.0
npm ERR! npm -v 1.1.32
npm ERR! type called_on_non_object
npm ERR! message Object.keys called on non-object
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\andrew\src\node-ios7crypt\npm-debug.log
npm ERR! not ok code 0
```

### supporting information:

 - `npm -v` prints: 1.1.32
 - `node -v` prints: v0.8.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X, or Linux?: Windows 10 Professional x86_64 (PowerShell)
 - Network issues:
   - Geographic location where npm was run: US

### Workaround:

NPM often has better luck installing packages in Command Prompt rather than PowerShell.

**Comment by KenanY** [comment]
@mcandre `npm@1.1` is **years** old and is no longer supported. Please try [updating](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) (also you should probably update Node.js as well). Let me know if you still experience this issue with `npm@3` and I can reopen.
