### ISSUE TITLE
Warning for passing flags to npm run

### ISSUE THREAD

**Issue by thomblake** [npm/npm#13693]
#### What's the feature?

Issue a warning when a user passes flags to npm when using npm run

example: (the actual copy will certainly have to be better and is based on nothing)

```
$ npm run foo --bar
  Warning: flag was passed to npm run. You might have meant "npm run foo -- --bar"
```

If we're concerned about issuing warnings in the case that someone is legitimately using npm flags along with npm run (I don't know if there's an actual use case for that), maybe it would make sense to only warn if the flag is not one that npm understands.
#### What problem is the feature intended to solve?

When passing flags to npm run scripts, they need to come after a `--` so that the flags don't get passed to npm instead of the run script, but if you forget to add the `--` then the script will behave unexpectedly but there is not necessarily an indication of what you did wrong.
#### Is the absence of this feature blocking you or your team? If so, how?

It is not blocking my team but has repeatedly caused tens of minutes of confusion until someone spots the error (or calls me over so I can spot the error).
#### Is this feature similar to an existing feature in another tool?

I have no idea.
#### Is this a feature you're prepared to implement, with support from the npm CLI team?

Yes, assuming folks think this is a good idea.

**Comment by legodude17** [comment]
This actually should be pretty easy to implement and sounds to me like a good idea.
