### ISSUE TITLE
Cant start npm

### ISSUE THREAD

**Issue by Dabrown18** [npm/npm#13700]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.10.7
3 info using node@v6.3.1
4 verbose config Skipping project config: /Users/DarronBrown/.npmrc. (matches userconfig)
5 verbose stack Error: missing script: start
5 verbose stack     at run (/usr/local/lib/node_modules/npm/lib/run-script.js:151:19)
5 verbose stack     at /usr/local/lib/node_modules/npm/lib/run-script.js:61:5
5 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:356:5
5 verbose stack     at checkBinReferences_ (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:320:45)
5 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:354:3)
5 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:124:5)
5 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:311:12
5 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
5 verbose stack     at tryToString (fs.js:455:3)
5 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
6 verbose cwd /Users/DarronBrown
7 error Darwin 15.6.0
8 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
9 error node v6.3.1
10 error npm  v3.10.7
11 error missing script: start
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]

**Comment by HenriBeck** [comment]
I don't know why you want to start npm but you are clearly missing the start script in your package.json

Read more on scripts here: https://docs.npmjs.com/misc/scripts

**Comment by legodude17** [comment]
The `npm start` command is just a short cut to `npm run start`. I think this should be closed.
/cc @KenanY

**Comment by KenanY** [comment]
@legodude17 Well let's at least give time for @Dabrown18 to respond.

**Comment by Dabrown18** [comment]
Hey fella's

I figured it out. I'm new to programming so expect some noob remarks.
