### ISSUE TITLE
Getting self signed certificate in chain issue

### ISSUE THREAD

**Issue by deepakbarolia** [npm/npm#13704]
I am trying to install npm using npm install and I get the following error:

![image](https://cloud.githubusercontent.com/assets/8637823/17812750/77bb1762-65f6-11e6-9fa1-e1ec44a8b687.png)

**Comment by emale999** [comment]
Try running the command
`npm config set strict-ssl false`
before using `npm install`. Worked for me.

**Comment by deepakbarolia** [comment]
Thanks, its done.

**Comment by KenanY** [comment]
Closing as resolved.
