### ISSUE TITLE
npm error while installing ionic

### ISSUE THREAD

**Issue by Aditya-app-dev** [npm/npm#13701]
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ionic"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9

npm ERR! shasum check failed for C:\Users\Aditya\AppData\Local\Temp\npm-2268-dd689e68\registry.npmjs.org\ionic\-\ionic-2.0.0.tgz
npm ERR! Expected: 8135804e1f2470292100dedadc571e99023e4f7c
npm ERR! Actual:   3e794972d433fe33d6a4f6e10f6baac0bcb8b012
npm ERR! From:     https://registry.npmjs.org/ionic/-/ionic-2.0.0.tgz

Please help me to solve this error!

**Comment by watilde** [comment]
Hello! You seems to be using a old version of npm so please try the latest version. Here is a docs to update the version: https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm

**Comment by Aditya-app-dev** [comment]
Hello,

I have installed `npm install --global --production npm-windows-upgrade` successfully but npm-windows-upgrade command is not recognized.

**Comment by legodude17** [comment]
Make sure to check `npm.prefix` by running `npm config get prefix` and make sure it is in you $PATH.

**Comment by Aditya-app-dev** [comment]
Did it. Got result this: `C:\Users\Aditya\AppData\Local\npm`

**Comment by Aditya-app-dev** [comment]
@watilde I have the latest version of npm i.e; 3.10.6. But getting error, checkout this screenshot.

![error](https://cloud.githubusercontent.com/assets/12525050/17844589/964e7390-6858-11e6-8d48-59556f4d0a6c.png)

**Comment by legodude17** [comment]
What happens when you try a non-global install? This is similar to #13699.

**Comment by Aditya-app-dev** [comment]
Hello @watilde @legodude17 

Thanks for the reply. I have solved this issue, there was an error in my internet connection. There was a static ip in ipv4 network so i just removed it and it's working fine now.

**Comment by legodude17** [comment]
Glad to here it @Aditya-app-dev! This can be closed now. @KenanY?
