### ISSUE TITLE
Whitelisting of NPM behind Firewall.

### ISSUE THREAD

**Issue by collegeimprovements** [npm/npm#13703]
#### I'm opening this issue because:
   - [X] Other (_see below for feature requests_):

## What's going wrong?
I have to use `proxy` to install node-packages. However the Security team of my company is happy to whitelist all the source from where NPM download packages.

## What information is required from NPM team/contributors?

**Can someone provide the list that I can give my Security Department in order to whitelist all the sources from where NPM installs `node-packages`?**

## How can the CLI team reproduce the problem?
Our company is using a `Firewall` (WebSense by Symantec).
So, please try to install npm-packages behind some kind of firewall which blocks it.

I'm sure I'm not the only one who is facing this situation. It would be great if someone can share their experience/situation also.

## How I currently deal with this ?
Currently I'm using `fiddler` as a proxy and have set `http_proxy`, `https_proxy` varialbes to `http://localhost:8888` (where fiddler runs!)

This is not a very clean way from Security Team's perspective. 
Also I've to keep fiddler open all the time when I'm using npm to download/update packages.

-----
### Supporting Information:

 - `npm -v` prints: `3.10.5`
 - `node -v` prints: `v6.3.1`
 - `npm config get registry` prints: `http://registry.npmjs.org/`
 - Windows, OS X, or Linux?: Windows
 - Network issues:
   - Geographic location where npm was run:
   - [X] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
- Firewall: WebSense by Symantec.

**Comment by legodude17** [comment]
Normally npm would fetch data from your configured registry and from git urls you give in dependencies, mostly github.

**Comment by collegeimprovements** [comment]
Thanks for the reply. 

`npm config get registry` prints `http://registry.npmjs.org/`. But that's not blocked by the firewall. There must be something else.

**Comment by legodude17** [comment]
What currently happens if you don't use your workaround and you try `npm install log`? Please upload `npm-debug.log` to a gist and comment with the link.

**Comment by collegeimprovements** [comment]
This issue has been resolved after I installed different `proxy`. The only caveat was if I close `fiddler `it throws an error that I need to **authenticate proxy**(even though fiddler is not the proxy I'm using anymore). Strange but works.

Thanks @legodude17 for your help and support.
