### ISSUE TITLE
npm version makes a commit even when the command would fail due to a pre-existing tag.

### ISSUE THREAD

**Issue by LukeusMaximus** [npm/npm#13706]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [ ] npm is producing an incorrect install.
- [x] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
#### What's going wrong?

When performing a `npm version` to 0.1.0, the command updates the version in package.json and then makes a commit with "0.1.0" as the message. The command then fails because the git tag "v0.1.0" already exists. 

Relevant error messages:

```
npm ERR! Command failed: git tag v0.1.0 -am 0.1.0
npm ERR! fatal: tag 'v0.1.0' already exists
```
#### How can the CLI team reproduce the problem?
1. Create a project with a package.json and make an initial commit.
2. Perform a `npm version minor`. 
3. Perform a `git reset --hard HEAD~`
4. Perform another `npm version minor`.

Observe the failure of the command and that npm has created a version commit without a tag.
### supporting information:
- `npm -v` prints: 3.9.3
- `node -v` prints: v6.2.1
- `npm config get registry` prints: https://registry.npmjs.org/
- Windows, OS X, or Linux?: Linux
- Network issues:
  - Geographic location where npm was run:
  - [ ] I use a proxy to connect to the npm registry.
  - [ ] I use a proxy to connect to the web.
  - [ ] I use a proxy when downloading Git repos.
  - [ ] I access the npm registry via a VPN
  - [ ] I don't use a proxy, but have limited or unreliable internet access.
- Container:
  - [ ] I develop using Vagrant on Windows.
  - [ ] I develop using Vagrant on OS X or Linux.
  - [ ] I develop / deploy using Docker.
  - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
I also got this using the instructions in the issue. This is from [lines 268-272 of `lib/version.js`](https://github.com/npm/npm/blob/master/lib/version.js#L268-L272). This would have to be changed in some way to just warn if this happens instead of erroring, either there or in `/ib/utils/git.js` to warn if any command fails. I think the latter is the best way to got.
