### ISSUE TITLE
Feature request: npm link -g

### ISSUE THREAD

**Issue by olalonde** [npm/npm#13702]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's the feature?

Add a global flag to `npm link`.

#### What problem is the feature intended to solve?

`npm install -g .` installs the scripts specified in `bin` somewhere under the `$PATH`.
However, in order to always use the latest version of those scripts, `npm install -g .` needs to be run again every time, which is a bit annoying.

This would be useful when developing locally. One alternative is to add the script's path to $PATH but this isn't super convenient.

#### Is the absence of this feature blocking you or your team? If so, how?

No

#### Is this feature similar to an existing feature in another tool?

Similar to `npm link`.

#### Is this a feature you're prepared to implement, with support from the npm CLI team?

Yes

**Comment by legodude17** [comment]
So `npm link -g` would symlink the file in `bin` to the `bin` directory under `npm.prefix`. Right? That sounds like a nice feature to have. What do you think @KenanY and @othiym23?

**Comment by othiym23** [comment]
That's what already happens with `npm link` today – when the CLI makes the links, it runs an install and build and then the link is made within the global prefix. In fact, I rely on that behavior to use the currently under-development versions of npm and the other CLI tools I support. It's a byproduct of how `npm link` is implemented, but that behavior is stable and can be relied upon to not change. I don't think there's anything additional we need to do here?

**Comment by KenanY** [comment]
Previously: https://github.com/npm/npm/issues/10113

**Comment by olalonde** [comment]
Wow, I had no idea. `npm link` already does what I wanted `npm link -g` to do... 😧 Feel free to close issue. I think this should be documented somewhere if not already because I didn't expect this to be the case.

**Comment by ericmdantas** [comment]
Yup, already works - I use it a bunch too.

**Comment by KenanY** [comment]
Closing :)

**Comment by legodude17** [comment]
Is this documented? It should be.
