### ISSUE TITLE
Cannot publish new version via NPM on Mac OS X (El Capitan)

### ISSUE THREAD

**Issue by vihuvac** [npm/npm#13709]
I just updated my project and after pushing the new version to github I tried to publish the update via `npm version patch` and then `npm publish` but I got the following error:

```
npm ERR! publish Failed PUT 403
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node4-lts/4.4.7/bin/node" "/Users/vihuvac/.npm-packages/bin/npm" "publish"
npm ERR! node v4.4.7
npm ERR! npm  v3.9.6
npm ERR! code E403

npm ERR! you do not have permission to publish "blueimp-file-uploader-express". Are you logged in as the correct user? : blueimp-file-uploader-express
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/vihuvac/Sites/blueimp-file-uploader-express/npm-debug.log
```

I had added my npm credentials before!

```
Username: vihuvac
Password:
Email: (this IS public) victouk@gmail.com
Logged in as vihuvac on https://registry.npmjs.org/.
```

Can someone help me please?

**Comment by doug-wade** [comment]
@vihuvac Okay, so DO NOT post it here or else trolls will steal your modules, but instead INSPECT your `~/.npmrc` file.  You're looking for a line that starts `//registry.npmjs.org/:_authToken=`.  If its not there, you'll need to log in again.

**Comment by vihuvac** [comment]
@doug-wade thank you for your response, I got that line in my ```~/.npmrc``` file but it still does not work.

**Comment by doug-wade** [comment]
_interesting_.  I would contact support@npmjs.com, personally.

**Comment by vihuvac** [comment]
@doug-wade thank you very much. That's strange because I just tried to login again and then I got:

```
Username: vihuvac
Password:
Email: (this IS public) victouk@gmail.com
Logged in as vihuvac on https://registry.npmjs.org/.
```

Exactly the same problem!
