### ISSUE TITLE
Install grunt locally fails, globally no such file or directory

### ISSUE THREAD

**Issue by sjiamnocna** [npm/npm#13715]
#### I'm opening this issue because:

  - [ ] npm is crashing.
    - [x] npm is doing something I don't understand.
  - [ ] npm is producing an incorrect install.
- [ ] Other (_see below for feature requests_):

#### What's going wrong?
I used the Chris Lea PPA as suggested to install NodeJS
I installed Grunt-cli and Grunt globally with -g flag. Then installed locally and got errors. No Grunt installed. Even doesn't work using grunt command from terminal (grunt --version)
Kubuntu 16.04, konsole:
sudo npm install grunt
npm ERR! Linux 4.2.0-22-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "grunt"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ENOSELF

npm ERR! Refusing to install grunt as a dependency of itself
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/grunt/npm-debug.log

cat npm-debug.log:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'install', 'grunt' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData grunt@^1.0.1
8 silly fetchNamedPackageData grunt
9 silly mapToRegistry name grunt
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/grunt
13 verbose request uri https://registry.npmjs.org/grunt
14 verbose request no auth needed
15 info attempt registry request try #1 at 10:38:21
16 verbose request id 14f70ec81b1d333a
17 verbose etag "F0KP2VX55MWVIRAQZXOA442O6"
18 http request GET https://registry.npmjs.org/grunt
19 http 304 https://registry.npmjs.org/grunt
20 verbose headers { date: 'Sun, 21 Aug 2016 08:38:23 GMT',
20 verbose headers   via: '1.1 varnish',
20 verbose headers   'cache-control': 'max-age=300',
20 verbose headers   etag: '"F0KP2VX55MWVIRAQZXOA442O6"',
20 verbose headers   age: '290',
20 verbose headers   connection: 'keep-alive',
20 verbose headers   'x-served-by': 'cache-fra1247-FRA',
20 verbose headers   'x-cache': 'HIT',
20 verbose headers   'x-cache-hits': '2',
20 verbose headers   'x-timer': 'S1471768703.420068,VS0,VE0',
20 verbose headers   vary: 'Accept-Encoding' }
21 silly get cb [ 304,
21 silly get   { date: 'Sun, 21 Aug 2016 08:38:23 GMT',
21 silly get     via: '1.1 varnish',
21 silly get     'cache-control': 'max-age=300',
21 silly get     etag: '"F0KP2VX55MWVIRAQZXOA442O6"',
21 silly get     age: '290',
21 silly get     connection: 'keep-alive',
21 silly get     'x-served-by': 'cache-fra1247-FRA',
21 silly get     'x-cache': 'HIT',
21 silly get     'x-cache-hits': '2',
21 silly get     'x-timer': 'S1471768703.420068,VS0,VE0',
21 silly get     vary: 'Accept-Encoding' } ]
22 verbose etag https://registry.npmjs.org/grunt from cache
23 verbose get saving grunt to /home/sjiamnocna/.npm/registry.npmjs.org/grunt/.cache.json
24 silly install normalizeTree
25 silly loadCurrentTree Finishing
26 silly loadIdealTree Starting
27 silly install loadIdealTree
28 silly cloneCurrentTree Starting
29 silly install cloneCurrentTreeToIdealTree
30 silly cloneCurrentTree Finishing
31 silly loadShrinkwrap Starting
32 silly install loadShrinkwrap
33 silly loadShrinkwrap Finishing
34 silly loadAllDepsIntoIdealTree Starting
35 silly install loadAllDepsIntoIdealTree
36 silly rollbackFailedOptional Starting
37 silly rollbackFailedOptional Finishing
38 silly runTopLevelLifecycles Starting
39 silly runTopLevelLifecycles Finishing
40 silly install printInstalled
41 verbose stack Error: Refusing to install grunt as a dependency of itself
41 verbose stack     at checkSelf (/usr/share/npm/lib/install/validate-args.js:40:14)
41 verbose stack     at Array.<anonymous> (/usr/share/npm/node_modules/slide/lib/bind-actor.js:15:8)
41 verbose stack     at LOOP (/usr/share/npm/node_modules/slide/lib/chain.js:15:14)
41 verbose stack     at chain (/usr/share/npm/node_modules/slide/lib/chain.js:20:5)
41 verbose stack     at /usr/share/npm/lib/install/validate-args.js:15:5
41 verbose stack     at /usr/share/npm/node_modules/slide/lib/async-map.js:52:35
41 verbose stack     at Array.forEach (native)
41 verbose stack     at /usr/share/npm/node_modules/slide/lib/async-map.js:52:11
41 verbose stack     at Array.forEach (native)
41 verbose stack     at asyncMap (/usr/share/npm/node_modules/slide/lib/async-map.js:51:8)
42 verbose cwd /var/www/grunt
43 error Linux 4.2.0-22-generic
44 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "grunt"
45 error node v4.2.6
46 error npm  v3.5.2
47 error code ENOSELF
48 error Refusing to install grunt as a dependency of itself
49 error If you need help, you may report this error at:
49 error     <https://github.com/npm/npm/issues>
50 verbose exit [ 1, true ]

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@sjiamnocna Ensure that the `"name"` property of your `package.json` is not set to `"grunt"`. Furthermore, you may need to rename the `/var/www/grunt` directory to something other than `grunt`.

**Comment by KenanY** [comment]
Closing as abandoned.
