### ISSUE TITLE
npm install chai --save-dev error

### ISSUE THREAD

**Issue by GuilhermeSilvaCosta** [npm/npm#13711]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ X ] Other (_see below for feature requests_):

#### What's going wrong?

I am trying to install chai

### supporting information:

 - `npm -v` prints: 3.5.2
 - `node -v` prints: v4.2.6
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X, or Linux?: Linux
 

Display error: 
npm ERR! Linux 4.4.0-34-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "chai" "--save-dev"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ENOSELF

npm ERR! Refusing to install chai as a dependency of itself
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/guilherme/workshop-be-mean/nodejs/aula-tdd/chai/npm-debug.log

npm-debug.log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   'chai',
1 verbose cli   '--save-dev' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData chai
8 silly fetchNamedPackageData chai
9 silly mapToRegistry name chai
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/chai
13 verbose request uri https://registry.npmjs.org/chai
14 verbose request no auth needed
15 info attempt registry request try #1 at 22:37:57
16 verbose request id 8a1bec639416f14a
17 verbose etag "DPADKMISF1OHHJLKG7MB8WRN"
18 http request GET https://registry.npmjs.org/chai
19 http 304 https://registry.npmjs.org/chai
20 verbose headers { date: 'Sat, 20 Aug 2016 01:37:58 GMT',
20 verbose headers   via: '1.1 varnish',
20 verbose headers   'cache-control': 'max-age=300',
20 verbose headers   etag: '"DPADKMISF1OHHJLKG7MB8WRN"',
20 verbose headers   age: '263',
20 verbose headers   connection: 'keep-alive',
20 verbose headers   'x-served-by': 'cache-gru7120-GRU',
20 verbose headers   'x-cache': 'HIT',
20 verbose headers   'x-cache-hits': '1',
20 verbose headers   'x-timer': 'S1471657078.380026,VS0,VE0',
20 verbose headers   vary: 'Accept-Encoding' }
21 silly get cb [ 304,
21 silly get   { date: 'Sat, 20 Aug 2016 01:37:58 GMT',
21 silly get     via: '1.1 varnish',
21 silly get     'cache-control': 'max-age=300',
21 silly get     etag: '"DPADKMISF1OHHJLKG7MB8WRN"',
21 silly get     age: '263',
21 silly get     connection: 'keep-alive',
21 silly get     'x-served-by': 'cache-gru7120-GRU',
21 silly get     'x-cache': 'HIT',
21 silly get     'x-cache-hits': '1',
21 silly get     'x-timer': 'S1471657078.380026,VS0,VE0',
21 silly get     vary: 'Accept-Encoding' } ]
22 verbose etag https://registry.npmjs.org/chai from cache
23 verbose get saving chai to /home/guilherme/.npm/registry.npmjs.org/chai/.cache.json
24 silly install normalizeTree
25 silly loadCurrentTree Finishing
26 silly loadIdealTree Starting
27 silly install loadIdealTree
28 silly cloneCurrentTree Starting
29 silly install cloneCurrentTreeToIdealTree
30 silly cloneCurrentTree Finishing
31 silly loadShrinkwrap Starting
32 silly install loadShrinkwrap
33 silly loadShrinkwrap Finishing
34 silly loadAllDepsIntoIdealTree Starting
35 silly install loadAllDepsIntoIdealTree
36 silly rollbackFailedOptional Starting
37 silly rollbackFailedOptional Finishing
38 silly runTopLevelLifecycles Starting
39 silly runTopLevelLifecycles Finishing
40 silly install printInstalled
41 verbose stack Error: Refusing to install chai as a dependency of itself
41 verbose stack     at checkSelf (/usr/share/npm/lib/install/validate-args.js:40:14)
41 verbose stack     at Array.<anonymous> (/usr/share/npm/node_modules/slide/lib/bind-actor.js:15:8)
41 verbose stack     at LOOP (/usr/share/npm/node_modules/slide/lib/chain.js:15:14)
41 verbose stack     at chain (/usr/share/npm/node_modules/slide/lib/chain.js:20:5)
41 verbose stack     at /usr/share/npm/lib/install/validate-args.js:15:5
41 verbose stack     at /usr/share/npm/node_modules/slide/lib/async-map.js:52:35
41 verbose stack     at Array.forEach (native)
41 verbose stack     at /usr/share/npm/node_modules/slide/lib/async-map.js:52:11
41 verbose stack     at Array.forEach (native)
41 verbose stack     at asyncMap (/usr/share/npm/node_modules/slide/lib/async-map.js:51:8)
42 verbose cwd /home/guilherme/workshop-be-mean/nodejs/aula-tdd/chai
43 error Linux 4.4.0-34-generic
44 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "chai" "--save-dev"
45 error node v4.2.6
46 error npm  v3.5.2
47 error code ENOSELF
48 error Refusing to install chai as a dependency of itself
49 error If you need help, you may report this error at:
49 error     <https://github.com/npm/npm/issues>
50 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@GuilhermeSilvaCosta Please ensure that the `"name"` property in your `package.json` is not set to `"chai"`. Also, you may need to rename the `/home/guilherme/workshop-be-mean/nodejs/aula-tdd/chai` directory to something other than `chai`.

**Comment by GuilhermeSilvaCosta** [comment]
Thanks @KenanY !!!
