### ISSUE TITLE
Cannot update npm 

### ISSUE THREAD

**Issue by brucebrophy** [npm/npm#13714]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I cannot update npm globally using any methods given in the readme.md.

After attempting to update npm an npm installation is no longer found.

I tried to update using
* npm install -g npm 
* as well as npm install -g `npm@latest`

### Gist 
https://gist.github.com/brucebrophy/ea9cbb01cf92395e10a1338e2ab876ff

**Comment by KenanY** [comment]
@brucebrophy Have you tried using `sudo`?

**Comment by brucebrophy** [comment]
Sorry, I did not, I thought using sudo with npm was a bad thing to do? I guess it isn't the case with npm update.

**Comment by brucebrophy** [comment]
@KenanY it worked, thanks for the help!

**Comment by KenanY** [comment]
@brucebrophy Glad to hear it :) since your global modules are being installed to `/usr/local/`, which your user does not have permissions to write to, you will need to elevate your privileges. Alternative solutions are provided [here](https://docs.npmjs.com/getting-started/fixing-npm-permissions).
