### ISSUE TITLE
Missing script: serve when trying to run yeoman web app

### ISSUE THREAD

**Issue by YewTreeWeb** [npm/npm#13716]
#### I'm opening this issue because:

  - npm is crashing.

#### How can the CLI team reproduce the problem?

Once yeoman is install and then the web app generated is install and setup, type npm run serve. 

 https://gist.github.com/YewTreeWeb/8b83fa339a1483fcce158eec2d269e36

### supporting information:

 - `npm -v` prints: v4.4.7
 - `node -v` prints: v3.10.6
 - `npm config get registry` prints: https://registry.npmjs.org/
 - OS X: 10.11.6

**Comment by KenanY** [comment]
@YewTreeWeb Do you have a `"serve"` script defined in your `package.json`? If not, then you will get that error, since `npm` has no idea what you want it to do.

**Comment by doug-wade** [comment]
@YewTreeWeb, @KenanY is correct.  The yeoman generator you _seem_ to be using, generator-website, doesn't define any [scripts](https://docs.npmjs.com/files/package.json#scripts) in [its generated package.json](https://github.com/roman01la/generator-website/blob/master/app/templates/_package.json).  Looking at the [generated Gruntfile](https://github.com/roman01la/generator-website/blob/master/app/templates/Gruntfile.js), it looks like you should start the server with `grunt build && grunt serve`, but its hard to tell.  If not, then I think this is an issue you should file in the [generator-website issue tracker](https://github.com/roman01la/generator-website/issues).

**Comment by KenanY** [comment]
Closing as resolved/abandoned.
