### ISSUE TITLE
Updating with "npm install npm@latest -g" breaks npm in Cygwin.

### ISSUE THREAD

**Issue by emigenix** [npm/npm#13713]
I successfully installed the latest *node/npm* combo ( [node-v6.4.0-win-x64.7z](https://nodejs.org/dist/latest/node-v6.4.0-win-x64.7z) ) and a few other *npm* modules tools under Cygwin in W8.1. After applying the `git.js` patch. All tools installed fine and worked as expected. I then decided to try to update *npm* via the official method: 

```sh
$ npm -v
3.10.3

$ npm install npm@latest -g
...
[crash!]
```
However, this failed horrendously, even removing the *npm* binary from my <prefix> system, and everything under `<prefix>/node_modules`. Checking the `npm-debug.log` file show the following:

```sh
...
14918 verbose stack Error: EPERM: operation not permitted, open 'C:\mybin\nodejs\npm'
14918 verbose stack     at Error (native)
14919 verbose cwd C:\cygwin64\home\xxx
14920 error Windows_NT 6.3.9600
14921 error argv "C:\\mybin\\nodejs\\node.exe" "C:\\mybin\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "npm@latest" "-g"
14922 error node v6.4.0
14923 error npm  v3.10.3
14924 error path C:\mybin\nodejs\npm
14925 error code EPERM
14926 error errno -4048
14927 error syscall open
14928 error Error: EPERM: operation not permitted, open 'C:\mybin\nodejs\npm'
14928 error     at Error (native)
14928 error  { Error: EPERM: operation not permitted, open 'C:\mybin\nodejs\npm'
14928 error     at Error (native)
14928 error   errno: -4048,
14928 error   code: 'EPERM',
14928 error   syscall: 'open',
14928 error   path: 'C:\\mybin\\nodejs\\npm' }
14929 error Please try running this command again as root/Administrator.
14930 verbose exit [ -4048, true ]
```
This seem to indicate some kind of permission error, but all directories have correct POSIX permissions. 
Coincidentally the same thing happened before when trying `npm update -g`. Any ideas?

----

#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

----

**Comment by othiym23** [comment]
As the CLI team [doesn't support the use of npm under Cygwin](https://github.com/npm/npm#installing-on-cygwin), this is not something we're going to address. As such, I'm going to close this issue. Thanks for your time!

**Comment by emigenix** [comment]
@othiym23 Cygwin is not relevant here since this is a Windows problem. If you had bothered searching for the problem, it appears all over the place including in this repo, with continuous closing of issues without any resolution or explanation. Sorry to take up your valuable time.
