### ISSUE TITLE
npm error

### ISSUE THREAD

**Issue by chengziyin** [npm/npm#13712]
when use meteor npm install --save react-addons-pure-render-mixin:
npm ERR! Linux 4.4.0-34-generic
npm ERR! argv "/home/xiao/.meteor/packages/meteor-tool/.1.4.0-1.13j49n2++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node" "/home/xiao/.meteor/packages/meteor-tool/.1.4.0-1.13j49n2++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm" "install" "--save" "react-addons-pure-render-mixin"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! syscall getaddrinfo

npm ERR! getaddrinfo EAI_AGAIN registry.npmjs.org:443
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /home/xiao/myapp/npm-debug.log

what should i do?

**Comment by doug-wade** [comment]
@chengziyin Please post the contents of `/home/xiao/myapp/npm-debug.log`
