### ISSUE TITLE
while creating data source from the command line by using create --type datasource

### ISSUE THREAD

**Issue by rnimmada** [npm/npm#13725]
Hi guys i am trying to upgrade my Api connect version to 5.0.3 while i am trying to creating data source by using command line with create --type datasource command but i am getting the following error

glob error { [Error: EPERM: operation not permitted, scandir 'C:\Users\miracle\A
plication Data']
errno: -4048,
code: 'EPERM',
syscall: 'scandir',
please any one from the team pls give the solution for this

**Comment by KenanY** [comment]
@rnimmada This does not look like an issue with `npm` to me. If you believe otherwise, please provide an `npm-debug.log` file as a [gist](https://gist.github.com/).
