### ISSUE TITLE
Can't install packages

### ISSUE THREAD

**Issue by tameribrahim** [npm/npm#13728]
#### I'm opening this issue because
I cant install tus-node-server that has a dependency to @google-cloud

The problem is in reading some of @google-cloud packages.
I tried cleaning the cache, but same issue.

npm-debug.log:
> 28821 warn tus@1.0.0 No repository field.
28822 verbose stack Error: Invalid name: "@google-cloud/vision"
28822 verbose stack     at ensureValidName (/usr/local/Cellar/node/0.8.17/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:297:15)
28822 verbose stack     at Object.module.exports.fixNameField (/usr/local/Cellar/node/0.8.17/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:201:5)
28822 verbose stack     at /usr/local/Cellar/node/0.8.17/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:29:38
28822 verbose stack     at Array.forEach (native)
28822 verbose stack     at normalize (/usr/local/Cellar/node/0.8.17/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:28:15)
28822 verbose stack     at final (/usr/local/Cellar/node/0.8.17/lib/node_modules/npm/node_modules/read-package-json/read-json.js:349:5)
28822 verbose stack     at then (/usr/local/Cellar/node/0.8.17/lib/node_modules/npm/node_modules/read-package-json/read-json.js:124:5)
28822 verbose stack     at ReadFileContext.<anonymous> (/usr/local/Cellar/node/0.8.17/lib/node_modules/npm/node_modules/read-package-json/read-json.js:295:20)
28822 verbose stack     at ReadFileContext.callback (/usr/local/Cellar/node/0.8.17/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16)
28822 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:359:13)
28823 verbose cwd /Users/tamer/Sites/project/web
28824 error Darwin 15.6.0
28825 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "tus-node-server"
28826 error node v6.2.0
28827 error npm  v3.8.9
28828 error Invalid name: "@google-cloud/vision"
28829 error If you need help, you may report this error at:
28829 error     <https://github.com/npm/npm/issues>
28830 verbose exit [ 1, true ]

**Comment by legodude17** [comment]
`npm i @google-cloud/vision` worked fine for me. Though I was on linux.

**Comment by tameribrahim** [comment]
Uninstalling Nodejs then installing it fixed the issue!
