### ISSUE TITLE
Npm is crashing during full-text-search indexing.

### ISSUE THREAD

**Issue by Deepak275** [npm/npm#13723]
Hi everyone, i am using a npm package [full-text-search-light](https://www.npmjs.com/package/full-text-search-light) package for implementing full text search. On instantiating it, it is taking a index parmeter. I am facing the same error Error: FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory. when i am using index_amount 12 for indexing the data in memory. when i am bringing it down to the 6 or less, it is working fine. node version is
v6.3.1. Please help me.

**Comment by KenanY** [comment]
@Deepak275 Hi, this does not sound like an issue with `npm` to me. This issue tracker is for bugs/feature-requests for `npm`, not for general support on how to use packages. If you do believe that this is an issue with `npm`, then please provide an `npm-debug.log` file as a [gist](https://gist.github.com/).

**Comment by Deepak275** [comment]
@KenanY,  yeah thanks for the reply it was my bad. I will try to find on the npm full-text-search-light[](https://www.npmjs.com/package/full-text-search-light). :)
