### ISSUE TITLE
Updating to “linter@1.11.16” failed

### ISSUE THREAD

**Issue by sahdev0** [npm/npm#13731]
#### I'm opening this issue because:

  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
npm ERR! Windows_NT 6.1.7600
npm ERR! argv "C:\\Users\\User\\AppData\\Local\\atom\\app-1.9.9\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\User\\AppData\\Local\\atom\\app-1.9.9\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\User\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\User\\.atom\\.apmrc" "install" "C:\\Users\\User\\AppData\\Local\\Temp\\d-116723-5268-1iiqkml\\package.tgz" "--target=0.37.8" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! path C:\Users\User\AppData\Local\Temp\apm-install-dir-116723-5268-63wx7o\node_modules\linter\node_modules\minimatch\node_modules\brace-expansion\node_modules\balanced-match\package.json.dbbba51a4f5e3963d659528105540cb6
npm ERR! code EBUSY
npm ERR! errno 10

npm ERR! EBUSY, rename 'C:\Users\User\AppData\Local\Temp\apm-install-dir-116723-5268-63wx7o\node_modules\linter\node_modules\minimatch\node_modules\brace-expansion\node_modules\balanced-match\package.json.dbbba51a4f5e3963d659528105540cb6'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!

**Comment by KenanY** [comment]
@sahdev0 Does this also happen after a reboot?

**Comment by KenanY** [comment]
Closing due to no response after a week.
