### ISSUE TITLE
How to get the names of all the npm-modules ??

### ISSUE THREAD

**Issue by sandipmgiri** [npm/npm#13733]
I'm trying to get the names of all the npm-modules..But facing some issues..Is there any way to get the names of all the npm projects ?

**Comment by aganoza** [comment]
You mean globally installed? npm list -g --depth=0

**Comment by KenanY** [comment]
@sandipmgiri Do you mean the names of all the modules that have been published to `registry.npmjs.com`?

**Comment by sandipmgiri** [comment]
@KenanY Yes...Names of all the modules that have been published to registry.npmjs.com

**Comment by legodude17** [comment]
One, I don't know why you want to do that, as there are a lot of modules. Two, I don't think there is a way to do that.

**Comment by sandipmgiri** [comment]
Actually I have to build all the npm-modules...And need to find out which fails while building.

**Comment by legodude17** [comment]
Ah, ok that makes sense (kind of). But I don't think there is a way. /cc @othiym23, do now if this is possible?

**Comment by legodude17** [comment]
Figured it out, make a request to `https://registry.npmjs.org/-/all`.

**Comment by sandipmgiri** [comment]
Thanks !!!

One,How we can fetch the names of all the modules from that page ?
Two, can we fetch source code URL (github URL) as well ?

**Comment by legodude17** [comment]
You will have to look up each one individually and look it up in the registry.

**Comment by KenanY** [comment]
Closing since this is not an issue with `npm`, but feel free to continue discussion if necessary.
