### ISSUE TITLE
Proposal: add .npmprune file for exempts of npm prune command

### ISSUE THREAD

**Issue by frank-dspeed** [npm/npm#13739]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [ ] npm is producing an incorrect install.
- [ ] npm is doing something I don't understand.
- [x] Other (_see below for feature requests_):
### supporting information:
- `npm -v` prints:
- `node -v` prints:
- `npm config get registry` prints:
- Windows, OS X, or Linux?:
- Network issues:
  - Geographic location where npm was run:
  - [ ] I use a proxy to connect to the npm registry.
  - [ ] I use a proxy to connect to the web.
  - [ ] I use a proxy when downloading Git repos.
  - [ ] I access the npm registry via a VPN
  - [ ] I don't use a proxy, but have limited or unreliable internet access.
- Container:
  - [ ] I develop using Vagrant on Windows.
  - [ ] I develop using Vagrant on OS X or Linux.
  - [ ] I develop / deploy using Docker.
  - [ ] I deploy to a PaaS (Triton, Heroku).

#### What's the feature?

Adding method for exempting some packages that got manual installed from getting pruned when npm prune runs via a extra .ignore file for npmprune suggestion: .npmprune
#### What problem is the feature intended to solve?

Don't prune packages installed via a other method then package.json
#### Is the absence of this feature blocking you or your team? If so, how?

Its Blocking because we want to distribute a Complex big node module that Installs packages without adding them to a package.json
#### Is this feature similar to an existing feature in another tool?

NO
#### Is this a feature you're prepared to implement, with support from the npm CLI team?

NO

**Comment by legodude17** [comment]
This sounds like a good idea, I would be willing to implement this with support.

**Comment by frank-dspeed** [comment]
i can also help you @legodude17  to implament it but i know this packagemanager is bad maintained so i don't know if they would even accept that contribution so the general question is will they accept it. at present i simply did a costum npm-prune command that takes care of the packages in the npm prune process that have  match in .npmprune file

**Comment by legodude17** [comment]
Okay, now we just need some input. @KenanY or @othiym23 would be good people to review this.

**Comment by KenanY** [comment]
I'll defer decision to @othiym23.
