### ISSUE TITLE
Invalid name: "@microsoft/generator-sharepoint"

### ISSUE THREAD

**Issue by tommysegoro** [npm/npm#13732]
#### I'm opening this issue because:

As per instruction on GitHub to setup SharePoint Framework:

https://github.com/SharePoint/sp-dev-docs/wiki/Setup-your-machine

The last instruction is on how to install Yeoman and that's by running: 

npm i -g @microsoft/generator-sharepoint 

But then I get the error of:

Invalid name: "@microsoft/generator-sharepoint"

[npm-debug.txt](https://github.com/npm/npm/files/431882/npm-debug.txt)

#### How can the CLI team reproduce the problem?

Run npm i -g @microsoft/generator-sharepoint 

Please see attached log file.

**Comment by hendrysadrak** [comment]
@tommysegoro 

Try  `npm i -g "@microsoft/generator-sharepoint"`.

**Comment by busches** [comment]
@tommysegoro did that work? @kenany

**Comment by farooqisuhail** [comment]
@hendrysadrak 
Worked !!!

**Comment by busches** [comment]
Thanks @farooqisuhail. @KenanY can you close this?
