### ISSUE TITLE
npm doesn't install local package dependencies

### ISSUE THREAD

**Issue by serhiisol** [npm/npm#13734]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [x] npm is producing an incorrect install.
- [ ] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
#### What's going wrong?

I have monorepo project. In this repo I have two folders: one with actual application and another one with component. Application depends on the component. After `npm install` I saw that not all dependencies were installed. In particular dependencies for the component. My Component has postinstall hook which runs `tsc` (typescript to be compiled) and it fails, because some packages weren't installed
#### How can the CLI team reproduce the problem?
1. Create package folder
2. `npm init` in it
3. add some dependencies in it, also devDependencies just to check
4. Create another package
5. add first folder as a dependency
6. run `npm install`
### supporting information:
- `npm -v` prints:
  3.10.3
- `node -v` prints:
  v6.4.0
  v6.3.1
- `npm config get registry` prints:
  https://registry.npmjs.org/
- Windows, OS X, or Linux?:
  MacOS X El Capitan 10.11.6 (15G31)
### Extra note:

if I'll add `npm install && tsc` to `postinstall` it will toggle, somehow, packages installation in application - it means that all component dependencies will also appear in application node_modules

**Comment by legodude17** [comment]
If I understand if correctly, you are wondering why `npm install` will not crawl up the file tree looking for package.json's to install dep's of, correct? If that is the case, I can confirm it doesn't happen, but then this should be a feature request for that feature.

**Comment by serhiisol** [comment]
It can be a bug, because ```npm install``` should work the same for all the packages

**Comment by legodude17** [comment]
Can you link to the monorepo you are using?

**Comment by serhiisol** [comment]
No it's private, but just create two packages in the same folder, one of the packages should be dependent on another one and hit ```npm install``` - you'll get same problem

**Comment by legodude17** [comment]
Can you build a simple repoduction repo?

**Comment by legodude17** [comment]
I did that and got a completely different problem. The second one wasn't even linked or anything to the first one.

**Comment by dietergeerts** [comment]
This is still an issue, can it be re-opened again?
I use a file dependency: 
```
    "@company/application-config": "file:../config",
```
and when doing npm install, the node module for config is there, but it doesn't have own node modules, so it's not installed, though it has dev dependencies declared
