### ISSUE TITLE
 Refusing to install async

### ISSUE THREAD

**Issue by xuelingzhizun** [npm/npm#13737]
#### I'm opening this issue because:

  - [x] npm is producing an incorrect install.
- [ ] npm is crashing.
    - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
```
# npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/home/xuefeng/.nvm/versions/node/v5.6.0/bin/node',
1 verbose cli   '/home/xuefeng/.nvm/versions/node/v5.6.0/bin/npm',
1 verbose cli   'install',
1 verbose cli   'async' ]
2 info using npm@3.6.0
3 info using node@v5.6.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData async
8 silly fetchNamedPackageData async
9 silly mapToRegistry name async
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/async
13 verbose request uri https://registry.npmjs.org/async
14 verbose request no auth needed
15 info attempt registry request try #1 at 01:45:36
16 verbose request id 1865f1f87507284c
17 verbose etag "69763ZCOUKCBBH7KBCDZRQNF6"
18 http request GET https://registry.npmjs.org/async
19 http 304 https://registry.npmjs.org/async
20 verbose headers { date: 'Tue, 23 Aug 2016 12:48:50 GMT',
20 verbose headers   via: '1.1 varnish',
"npm-debug.log" 87L, 4569C  

```

#### How can the CLI team reproduce the problem?
........I don't know ..... maybe write'npm install async'
### supporting information:
```
npm ERR! Linux 4.2.0-42-generic
npm ERR! argv "/home/xuefeng/.nvm/versions/node/v5.6.0/bin/node" "/home/xuefeng/.nvm/versions/node/v5.6.0/bin/npm" "install" "async"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! code ENOSELF

npm ERR! Refusing to install async as a dependency of itself
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/xuefeng/bjbh/lesson5/npm-debug.log

```
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

#### I was in China, but do not think that is the reason the GW，else moule no problem。

sorry，my English is not good.

**Comment by KenanY** [comment]
@xuelingzhizun Is the `"name"` property of your `package.json` set to `"async"`?

**Comment by xuelingzhizun** [comment]
yes,i set the `“name”` property is` "async"` of my `package.json`。

is it a problem caused by it ？


```
# package.json
{
  "name": "async",
  "version": "1.0.0",
  "description": "learn async ",
  "main": "app.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "xuefeng learn from alsotang",
  "license": "ISC",
  "dependencies": {
    "express": "^4.14.0",
    "async": "2.0.0"
  }
}

```

**Comment by KenanY** [comment]
@xuelingzhizun Try changing it to something which isn't the same as one of your dependencies.

**Comment by xuelingzhizun** [comment]
sorry,my english is too bad to understand the meaning of the words you said, I just write `async` through the `package.json` and then enter the command `npm install async`  And successfully.

**Comment by KenanY** [comment]
@xuelingzhizun 

``` json
{
  "name": "learn-async",
  "version": "1.0.0",
  "description": "learn async ",
  "main": "app.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "xuefeng learn from alsotang",
  "license": "ISC",
  "dependencies": {
    "express": "^4.14.0",
    "async": "2.0.0"
  }
}
```

**Comment by xuelingzhizun** [comment]
Thank you for your advice.
