### ISSUE TITLE
npm install error -  No compatible version found: fs@0.0.2

### ISSUE THREAD

**Issue by dotannn** [npm/npm#13743]
#### I'm opening this issue because:
Hi,  I suddenly started to get weird errors after npm install,  although didn't change anything

#### What's going wrong?
i get npm ERR! No compatible version found: fs@0.0.2

### supporting information:

npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm ERR! Linux 3.19.0-47-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5

npm ERR! No compatible version found: fs@0.0.2
npm ERR! Valid install targets:
npm ERR! 0.0.1-security
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/dotan/work/code/personify/orderingbot/npm-debug.log

**Comment by adamchenwei** [comment]
samething here!

**Comment by jfortier** [comment]
+1 here

**Comment by adamchenwei** [comment]
`358730 info postinstall node-sass@3.8.0
358731 verbose unsafe-perm in lifecycle true
358732 verbose unlock done using /home/vagrant/.npm/_locks/node-sass-9894a549776d5f33.lock for /home/vagrant/priceline-web/m-fly-search/node_modules/gulp-sass/node_modules/node-sass
358733 verbose about to build /home/vagrant/priceline-web/m-fly-search/node_modules/gulp-sass
358734 info build /home/vagrant/priceline-web/m-fly-search/node_modules/gulp-sass
358735 info install gulp-sass@2.3.2
358736 info postinstall gulp-sass@2.3.2
358737 verbose unlock done using /home/vagrant/.npm/_locks/gulp-sass-6091a8f93f433587.lock for /home/vagrant/priceline-web/m-fly-search/node_modules/gulp-sass
358738 verbose stack Error: version not found: fs@0.0.2
358738 verbose stack     at setData (/usr/lib/node_modules/npm/lib/cache/add-named.js:137:12)
358738 verbose stack     at RES (/usr/lib/node_modules/npm/node_modules/inflight/inflight.js:23:14)
358738 verbose stack     at f (/usr/lib/node_modules/npm/node_modules/once/once.js:17:25)
358738 verbose stack     at fixName (/usr/lib/node_modules/npm/lib/cache/add-named.js:29:5)
358738 verbose stack     at saved (/usr/lib/node_modules/npm/lib/cache/caching-client.js:173:7)
358738 verbose stack     at /usr/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:210:7
358738 verbose stack     at FSReqWrap.oncomplete (fs.js:95:15)
358739 verbose statusCode 404
358740 verbose cwd /home/vagrant/priceline-web/m-fly-search
358741 error Linux 3.10.0-327.22.2.el7.x86_64
358742 error argv "/usr/bin/node" "/usr/bin/npm" "install" "--no-bin-links"
358743 error node v0.12.9
358744 error npm  v2.14.9
358745 error version not found: fs@0.0.2
358746 error If you need help, you may report this error at:
358746 error     <https://github.com/npm/npm/issues>
`

**Comment by dotannn** [comment]
I found that there are two packages in my dependencies who provoke this error  : 
 1. npm (i don't know why but I had it in my dependencies)
2. paycryptor  https://github.com/richardgirges/paycryptor

**Comment by srikiraju** [comment]
+1 here

```
2865 silly fetchPackageMetaData Error: No compatible version found: fs@0.0.2
2865 silly fetchPackageMetaData Valid install targets:
2865 silly fetchPackageMetaData 0.0.1-security
2865 silly fetchPackageMetaData
2865 silly fetchPackageMetaData     at pickVersionFromRegistryDocument (/Code/web-ux/env/lib/node_modules/npm/lib/fetch-package-metadata.js:170:16)
2865 silly fetchPackageMetaData     at /Code/web-ux/env/lib/node_modules/npm/node_modules/iferr/index.js:13:50
2865 silly fetchPackageMetaData     at /Code/web-ux/env/lib/node_modules/npm/lib/utils/pulse-till-done.js:19:8
2865 silly fetchPackageMetaData     at saved (/Code/web-ux/env/lib/node_modules/npm/lib/cache/caching-client.js:174:7)
2865 silly fetchPackageMetaData     at /Code/web-ux/env/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:210:7
2865 silly fetchPackageMetaData     at FSReqWrap.oncomplete (fs.js:82:15)
2865 silly fetchPackageMetaData  error for fs@0.0.2 [Error: No compatible version found: fs@0.0.2
2865 silly fetchPackageMetaData Valid install targets:
2865 silly fetchPackageMetaData 0.0.1-security
2865 silly fetchPackageMetaData ]
```

**Comment by adamchenwei** [comment]
How to bring important ticket to attention to the npm admin???

**Comment by jfortier** [comment]
Apparently the 'fs' package is now part of the npm core, and is no longer required for import. I simply removed the package from my package.json file, did another `npm install` my packages and was able to build using gulp with no issues.

**Comment by srikiraju** [comment]
How can we determine which of the dependencies has `fs` as it's dependency?

**Comment by VictorSage** [comment]
My package does not directly reference `fs` package. How do we know which one create this dependency?

**Comment by prashanthparsi** [comment]
Happening for me as well. Any solutions or thoughts?

**Comment by DVLP** [comment]
Same problem,
I downgraded to 0.0.1-security to see if this will help

**Comment by adamchenwei** [comment]
Wait, for node apps that use earlier version like 0.12.9, what should we do

**Comment by robwalch** [comment]
Same. Builds that worked a few hours ago fail on npm install. Our package does not reference fs directly.

**Comment by codingmaven** [comment]
Same issue here

**Comment by prashanthparsi** [comment]
I had the fs dependency listed in package.json. I removed it and the npm install us running now.

**Comment by rameshthoomu** [comment]
same issue here.. What to do..

**Comment by adamchenwei** [comment]
One of our dependencies has dependencies, that includes `"fs": "0.0.2",`. I think that is the issue for us.

**Comment by chrisbolin** [comment]
If you don't depend on it directly, you can use `npm ls` to find which of your dependencies depends on `fs`. If you are super lucky, you might have control over that dependency.

**Comment by VictorSage** [comment]
remove the line make npm install work. There should be other solutions.

**Comment by srikiraju** [comment]
@chrisbolin My `npm ls` does not list `fs@0.0.2`, yet npm install tries to install it. I believe `npm ls` only lists packages that are currently installed

**Comment by DVLP** [comment]
To fix the problem delete this line 

`  "fs": "0.0.2",
`
from your package.json

**Comment by yaycmyk** [comment]
It's a built-in, don't know why people are putting that in their dependencies...

**Comment by robwalch** [comment]
Found the dep, but still wondering why this was ignored by the registry until recently...

**Comment by zkat** [comment]
Hey y'all -- this is not really an official response cause I still gotta talk to folks, but hang in there: you don't need `fs` at all, because it's built-in with Node, and installing the `fs` package was not doing anything for you. It is entirely safe (and recommended) that you remove this dependency.

For those of you with transitive dependencies asking for this package, stand by for that to get fixed, and a more official explanation of what's up. :)

**Comment by adamchenwei** [comment]
@zkat  is `fs` default dep for version `0.12.9`?

**Comment by zkat** [comment]
@adamchenwei It has been a native node module since forever, afaik, and you literally never needed to `npm install fs`, for any version of node.

**Comment by RavenHursT** [comment]
Wow.. this is what, the THIRD time this year that NPM has broken the internets? 

http://i.stack.imgur.com/jiFfM.jpg

**Comment by pporada-gl** [comment]
We're hitting this as well.

**Comment by schweller** [comment]
I wish there was a `npm uninstall npm` command to fix everything.

**Comment by yaycmyk** [comment]
@RavenHursT it's not NPM's fault, it's people that don't know what they're doing.

**Comment by YurySolovyov** [comment]
Why on earth would people install fs as dependency?

**Comment by pporada-gl** [comment]
That's a good question, I just build the stuff.

**Comment by vineyugave** [comment]
just delete the package from package.json.. you don't need to add that explicitly it is a part of the native package

**Comment by RavenHursT** [comment]
@yaycmyk So if I design an automobile that bursts into flames and kills everyone inside, and then sell said automobile to millions of people who are dependent on it to commute to work everyday, I should hold zero liability for the flaws in my design... Basically what you're saying.. Got it.

**Comment by yaycmyk** [comment]
LOL. It is in no way NPM's fault that people are putting invalid packages in their dependencies. That's like blaming a car company for a car exploding because you put Diet Coke in the fuel tank.

**Comment by chrisbolin** [comment]
unsub

**Comment by DylanVann** [comment]
Versions should be immutable. The packages probably shouldn't have `fs` installed, but it's usually good if previously working code continues to work, even if it's "bad" previously working code.

Note the release a few hours ago on [https://www.npmjs.com/package/fs](https://www.npmjs.com/package/fs). Something about this...

Also the reason people can't just remove it from package.json is that it's in their dependencies. Funny thing, you can't use `npm ls` to find out which one, since you can't get through `npm install`.

**Comment by RavenHursT** [comment]
@yaycmyk 
>putting invalid packages in their dependencies

So `fs` is now not an node package? And even if that were the case, NPM shouldn't be handling that edgecase for a system that, you know, _millions_ of people and systems depend on?

**Comment by SomeKittens** [comment]
@RavenHursT your analogy holds if you drive the car into the wall (i.e. do something the manufacturer never recommended and then blame them when you get hurt).

Geez people, do you also `npm install true` just to make sure booleans work?

**Comment by hunterloftis** [comment]
@yaycmyk in general, packages should be immutable. If 'fs' existed at one time, it should still exist now. Otherwise, things break - so I'm guessing npm has a strong reason for yanking this (security? was the package compromised?)

The `fs` package gets 220k downloads / month and is depended upon by 846 other packages. So all of the folks here aren't able to "just delete it from package.json" because, for most of them, it is likely a transitive dependency.

**Comment by yaycmyk** [comment]
@hunterloftis it seems like a mistake that it was ever on the registry to begin with, but I see your point.

**Comment by RavenHursT** [comment]
@SomeKittens

Actually.. It's not even about the car.. it's about buying a car that has some minor dependency like a fuel filter that explodes like a hand grenade.  I don't have `fs` in my deps.. obviously, people's projects are breaking because to NPM's hierarchical dependency nature.  It's some dependency of a sub-dependency that's the culprit and people are simply expecting their stuff to work like it did the day before, not all of a sudden bring their development to a screeching halt every 3 months.

**Comment by kiluavineeth** [comment]
Issue seems to be fixed now

**Comment by zkat** [comment]
`fs@0.0.2` should be available again, so I'm closing this issue. Cheers 👋

**Comment by zkat** [comment]
err, correction, I'll leave it open for a bit, and we'll probably have a more thorough explanation here, later :)

**Comment by zkat** [comment]
http://status.npmjs.org/incidents/dw8cr1lwxkcr There we go. We've updated our status page. Closing for realsies now :P

**Comment by seldo** [comment]
TLDR: Human error, specifically this human. I approved unpublishing it instead of deprecating it because I didn't properly check the deps count.

**Comment by jokeyrhyme** [comment]
I highly recommend checking the names of modules that are built-in to Node.js:
- https://github.com/nodejs/node/tree/master/lib

You should NOT be using `npm` or package.json to install any packages that have the same names as the built-in modules.

**Comment by YurySolovyov** [comment]
I just went ahead and created issues for the [first page of npm search for dependencies of `fs`](https://www.npmjs.com/browse/depended/fs), but doing it manually is hard.
I encourage everyone to go ahead and reach to the rest of module authors and get this fixed.
Snippet I used
```md
# title
No need to use fs as npm dependency

#body
Hi!
`fs` is a node core module, there is no need to include it as npm dependency
See https://github.com/npm/npm/issues/13743
```
