### ISSUE TITLE
Package tarballs with invalid windows filenames can cause install problems

### ISSUE THREAD

**Issue by iarna** [npm/npm#13749]
As was discussed in #13722, if you have a filename with a newline in it it can cause all versions of npm on Windows to hang. npm should be more resilient toward bad data in tarballs.

**Comment by martinheidegger** [comment]
@iarna Thank you so much!

**Comment by legodude17** [comment]
In the beginning of #13722, it is stated that this also happens with `javascripting`.

**Comment by legodude17** [comment]
`javascripting` also depends on `workshop-adventure`.

**Comment by kcfgl** [comment]
Glad I found this, I was going crazy for a bit.  I usually work on Mac, but need to be on Win for a project right now. Is there a workaround for this issue?

**Comment by legodude17** [comment]
Don't put weird letters in filenames.

**Comment by kcfgl** [comment]
I'm not the developer of these packages, just trying to get them to install.  Guessing the workaround is to figure out which one is failing and let the dev know.

**Comment by legodude17** [comment]
Yeah, that makes sense.

**Comment by martinheidegger** [comment]
Just to be clear: I am a maintainer of javascripting, learnyounode and workshopper-adventure. I have access to a windows 10 machine and was able to install both javascripting and learnyounode without problem. If you still can not install one of them I strongly believe that this is an unrelated issue. The only reason with it *might* be related is if you have more persistent cache settings than the default settings. You can try to make sure that its installed properly using `npm i javascripting -g -f`
