### ISSUE TITLE
npm -g update fails

### ISSUE THREAD

**Issue by j75** [npm/npm#13745]
#### I'm opening this issue because:

  - [x] npm is producing an incorrect update.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
npm ERR! Cannot find module '/usr/lib/node_modules/npm/lib/build.js'

#### How can the CLI team reproduce the problem?
npm -g update as root

### supporting information:

 - `npm -v` prints: 3.10.6
 - `node -v` prints: v4.5.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X, or Linux?: Linux
 - Network issues:
   - Geographic location where npm was run: I don't use a proxy

[foo.zip](https://github.com/npm/npm/files/433490/foo.zip)

 - Container: no container

**Comment by legodude17** [comment]
It worked for me on Linux, but took almost 28s.

**Comment by j75** [comment]
So I tried again today 
`# npm -g update`

and it worked OK (quite quickly actually).
I presume that it was a temporary network problem somewhere, so I can hereby declare the issue closed!
