### ISSUE TITLE
npm link breaks module caching in node

### ISSUE THREAD

**Issue by jamorales-bsft** [npm/npm#13748]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [ ] npm is producing an incorrect install.
- [x ] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
#### What's going wrong?

When I do an npm link then require the module and set some some configuration options. The options do not propagate to other require calls in other modules.
#### How can the CLI team reproduce the problem?

npm link a module. Then follow example pattern

ex

```
file1.js
var m = require("someModule")

//default is false
m.someConfigVariable = true


file2.js
var m = require("someModule")

//console.log(m.someConfigVariable) //will be false again as if it was never set

index.js
//starting point
require("file1")
require("file2")
```
### supporting information:
- `npm -v` prints: 2.15.0
- `node -v` prints: v4.4.2
- `npm config get registry` prints: https://registry.npmjs.org/
- Windows, OS X, or Linux?: OS X
- Network issues:
  - Geographic location where npm was run:
  - [ ] I use a proxy to connect to the npm registry.
  - [ ] I use a proxy to connect to the web.
  - [ ] I use a proxy when downloading Git repos.
  - [ ] I access the npm registry via a VPN
  - [ ] I don't use a proxy, but have limited or unreliable internet access.
- Container:
  - [ ] I develop using Vagrant on Windows.
  - [ ] I develop using Vagrant on OS X or Linux.
  - [ ] I develop / deploy using Docker.
  - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by doug-wade** [comment]
@jamorales-bsft I'm struggling to wrap my head around this one.  Can you push a repo with a repro?

**Comment by jamorales-bsft** [comment]
Sure I'll come up with something. Where can I push it to?

**Comment by doug-wade** [comment]
@jamorales-bsft That'd be perfect, and also awesome.  As an example, I linked [this repro repo](https://github.com/doug-wade/react-server-repro) to illustrate [this issue](https://github.com/redfin/react-server/issues/155), which helped the maintainers identify and fix the problem.

**Comment by jamorales-bsft** [comment]
great will do.

**Comment by jamorales-bsft** [comment]
[repro repo](https://github.com/jamorales-bsft/npmLinkError-repro)
cd main
npm link ../file1
node index.js

Ok finally got around to doing this. This gave me some insight into what was really happening. First forget the top example it is wrong. What is happening is if you npm link a module. Any it has to use it's own node_modules dependencies. it cannot the modules that is in the node_modules directory it is linked into. So what happens is it uses its own version of the same module which is logically separated from the program it is npm linked into. I the repo basically this means

(main/node_modules/mod1).someSetting is not the same as
(file1/node_modules/mod1).someSetting

What really should happen is file1 when npm linked should be able to find and use (main/node_modules/mod1) that way settings carry over
