### ISSUE TITLE
error install npm/mysql

### ISSUE THREAD

**Issue by sam2908** [npm/npm#13740]
```
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "mysql"
npm ERR! node v6.2.0
npm ERR! npm  v3.10.6

npm ERR! No compatible version found: mysql@undefined2.10.2
npm ERR! Valid install targets:
npm ERR! 2.11.1, 2.11.0, 2.10.2, 2.10.1, 2.10.0, 2.9.0, 2.8.0, 2.7.0, 2.6.2, 2.6.1, 2.6.0, 2.5.5, 2.5.4, 2.5.3, 2.5.2, 2.5.1, 2.5.0, 2.4.3, 2.4.2, 2.4.1, 2.4.0, 2.3.2, 2.3.1, 2.3.0, 2.2.0, 2.1.1, 2.1.0, 2.0.1, 2.0.0, 2.0.0-rc2, 2.0.0-rc1, 2.0.0-alpha9, 2.0.0-alpha8, 2.0.0-alpha7, 2.0.0-alpha6, 2.0.0-alpha5, 2.0.0-alpha4, 2.0.0-alpha3, 2.0.0-alpha2, 2.0.0-alpha, 0.9.6, 0.9.5, 0.9.4, 0.9.3, 0.9.2, 0.9.1, 0.9.0, 0.8.0, 0.7.0, 0.6.0, 0.5.0, 0.4.0, 0.3.0, 0.2.0, 0.1.0
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mac/Documents/tp1/npm-debug.log
```

**Comment by doug-wade** [comment]
_fascinating_
Are you running `npm install mysql@undefined2.10.2` in the terminal?  I feel like probably no, you're running `npm install` in a directory with a package.json.  Can you include that package.json?  And the listed npm-debug.log?

**Comment by sam2908** [comment]
Hello
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'mysql@3.10.6' ]
2 info using npm@3.10.6
3 info using node@v6.2.0
4 verbose config Skipping project config: /Users/mac/.npmrc. (matches userconfig)
5 silly loadCurrentTree Starting
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 silly fetchPackageMetaData mysql@3.10.6
9 silly fetchNamedPackageData mysql
10 silly mapToRegistry name mysql
11 silly mapToRegistry using default registry
12 silly mapToRegistry registry https://registry.npmjs.org/
13 silly mapToRegistry data Result {
13 silly mapToRegistry   raw: 'mysql',
13 silly mapToRegistry   scope: null,
13 silly mapToRegistry   escapedName: 'mysql',
13 silly mapToRegistry   name: 'mysql',
13 silly mapToRegistry   rawSpec: '',
13 silly mapToRegistry   spec: 'latest',
13 silly mapToRegistry   type: 'tag' }
14 silly mapToRegistry uri https://registry.npmjs.org/mysql
15 verbose request uri https://registry.npmjs.org/mysql
16 verbose request no auth needed
17 info attempt registry request try #1 at 17:41:57
18 verbose request id f2b2735fdcfac161
19 verbose etag "5Y4A4BRC1IGA1SLAEUHP3X86U"
20 http request GET https://registry.npmjs.org/mysql
21 http 304 https://registry.npmjs.org/mysql
22 verbose headers { date: 'Tue, 23 Aug 2016 16:41:58 GMT',
22 verbose headers   via: '1.1 varnish',
22 verbose headers   'cache-control': 'max-age=300',
22 verbose headers   etag: '"5Y4A4BRC1IGA1SLAEUHP3X86U"',
22 verbose headers   age: '285',
22 verbose headers   connection: 'keep-alive',
22 verbose headers   'x-served-by': 'cache-ams4131-AMS',
22 verbose headers   'x-cache': 'HIT',
22 verbose headers   'x-cache-hits': '1',
22 verbose headers   'x-timer': 'S1471970518.053388,VS0,VE0',
22 verbose headers   vary: 'Accept-Encoding' }
23 silly get cb [ 304,
23 silly get   { date: 'Tue, 23 Aug 2016 16:41:58 GMT',
23 silly get     via: '1.1 varnish',
23 silly get     'cache-control': 'max-age=300',
23 silly get     etag: '"5Y4A4BRC1IGA1SLAEUHP3X86U"',
23 silly get     age: '285',
23 silly get     connection: 'keep-alive',
23 silly get     'x-served-by': 'cache-ams4131-AMS',
23 silly get     'x-cache': 'HIT',
23 silly get     'x-cache-hits': '1',
23 silly get     'x-timer': 'S1471970518.053388,VS0,VE0',
23 silly get     vary: 'Accept-Encoding' } ]
24 verbose etag https://registry.npmjs.org/mysql from cache
25 verbose get saving mysql to /Users/mac/.npm/registry.npmjs.org/mysql/.cache.json
26 verbose correctMkdir /Users/mac/.npm correctMkdir not in flight; initializing
27 silly fetchNamedPackageData No valid target from cache, forcing network
28 verbose request uri https://registry.npmjs.org/mysql
29 verbose request no auth needed
30 info attempt registry request try #1 at 17:41:58
31 http request GET https://registry.npmjs.org/mysql
32 http 200 https://registry.npmjs.org/mysql
33 verbose headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
33 verbose headers   etag: '"5Y4A4BRC1IGA1SLAEUHP3X86U"',
33 verbose headers   'content-type': 'application/json',
33 verbose headers   'content-encoding': 'gzip',
33 verbose headers   'cache-control': 'max-age=300',
33 verbose headers   'content-length': '29108',
33 verbose headers   'accept-ranges': 'bytes',
33 verbose headers   date: 'Tue, 23 Aug 2016 16:41:58 GMT',
33 verbose headers   via: '1.1 varnish',
33 verbose headers   age: '285',
33 verbose headers   connection: 'keep-alive',
33 verbose headers   'x-served-by': 'cache-ams4131-AMS',
33 verbose headers   'x-cache': 'HIT',
33 verbose headers   'x-cache-hits': '2',
33 verbose headers   'x-timer': 'S1471970518.182002,VS0,VE0',
33 verbose headers   vary: 'Accept-Encoding' }
34 silly get cb [ 200,
34 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
34 silly get     etag: '"5Y4A4BRC1IGA1SLAEUHP3X86U"',
34 silly get     'content-type': 'application/json',
34 silly get     'content-encoding': 'gzip',
34 silly get     'cache-control': 'max-age=300',
34 silly get     'content-length': '29108',
34 silly get     'accept-ranges': 'bytes',
34 silly get     date: 'Tue, 23 Aug 2016 16:41:58 GMT',
34 silly get     via: '1.1 varnish',
34 silly get     age: '285',
34 silly get     connection: 'keep-alive',
34 silly get     'x-served-by': 'cache-ams4131-AMS',
34 silly get     'x-cache': 'HIT',
34 silly get     'x-cache-hits': '2',
34 silly get     'x-timer': 'S1471970518.182002,VS0,VE0',
34 silly get     vary: 'Accept-Encoding' } ]
35 verbose get saving mysql to /Users/mac/.npm/registry.npmjs.org/mysql/.cache.json
36 verbose correctMkdir /Users/mac/.npm correctMkdir not in flight; initializing
37 silly fetchPackageMetaData Error: No compatible version found: mysql@3.10.6
37 silly fetchPackageMetaData Valid install targets:
37 silly fetchPackageMetaData 2.11.1, 2.11.0, 2.10.2, 2.10.1, 2.10.0, 2.9.0, 2.8.0, 2.7.0, 2.6.2, 2.6.1, 2.6.0, 2.5.5, 2.5.4, 2.5.3, 2.5.2, 2.5.1, 2.5.0, 2.4.3, 2.4.2, 2.4.1, 2.4.0, 2.3.2, 2.3.1, 2.3.0, 2.2.0, 2.1.1, 2.1.0, 2.0.1, 2.0.0, 2.0.0-rc2, 2.0.0-rc1, 2.0.0-alpha9, 2.0.0-alpha8, 2.0.0-alpha7, 2.0.0-alpha6, 2.0.0-alpha5, 2.0.0-alpha4, 2.0.0-alpha3, 2.0.0-alpha2, 2.0.0-alpha, 0.9.6, 0.9.5, 0.9.4, 0.9.3, 0.9.2, 0.9.1, 0.9.0, 0.8.0, 0.7.0, 0.6.0, 0.5.0, 0.4.0, 0.3.0, 0.2.0, 0.1.0
37 silly fetchPackageMetaData
37 silly fetchPackageMetaData     at pickVersionFromRegistryDocument (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:178:16)
37 silly fetchPackageMetaData     at /usr/local/lib/node_modules/npm/node_modules/iferr/index.js:13:50
37 silly fetchPackageMetaData     at /usr/local/lib/node_modules/npm/lib/utils/pulse-till-done.js:20:8
37 silly fetchPackageMetaData     at saved (/usr/local/lib/node_modules/npm/lib/cache/caching-client.js:174:7)
37 silly fetchPackageMetaData     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:210:7
37 silly fetchPackageMetaData     at FSReqWrap.oncomplete (fs.js:117:15)
37 silly fetchPackageMetaData  error for mysql@3.10.6 Error: No compatible version found: mysql@3.10.6
37 silly fetchPackageMetaData Valid install targets:
37 silly fetchPackageMetaData 2.11.1, 2.11.0, 2.10.2, 2.10.1, 2.10.0, 2.9.0, 2.8.0, 2.7.0, 2.6.2, 2.6.1, 2.6.0, 2.5.5, 2.5.4, 2.5.3, 2.5.2, 2.5.1, 2.5.0, 2.4.3, 2.4.2, 2.4.1, 2.4.0, 2.3.2, 2.3.1, 2.3.0, 2.2.0, 2.1.1, 2.1.0, 2.0.1, 2.0.0, 2.0.0-rc2, 2.0.0-rc1, 2.0.0-alpha9, 2.0.0-alpha8, 2.0.0-alpha7, 2.0.0-alpha6, 2.0.0-alpha5, 2.0.0-alpha4, 2.0.0-alpha3, 2.0.0-alpha2, 2.0.0-alpha, 0.9.6, 0.9.5, 0.9.4, 0.9.3, 0.9.2, 0.9.1, 0.9.0, 0.8.0, 0.7.0, 0.6.0, 0.5.0, 0.4.0, 0.3.0, 0.2.0, 0.1.0
37 silly fetchPackageMetaData
37 silly fetchPackageMetaData     at pickVersionFromRegistryDocument (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:178:16)
37 silly fetchPackageMetaData     at /usr/local/lib/node_modules/npm/node_modules/iferr/index.js:13:50
37 silly fetchPackageMetaData     at /usr/local/lib/node_modules/npm/lib/utils/pulse-till-done.js:20:8
37 silly fetchPackageMetaData     at saved (/usr/local/lib/node_modules/npm/lib/cache/caching-client.js:174:7)
37 silly fetchPackageMetaData     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:210:7
37 silly fetchPackageMetaData     at FSReqWrap.oncomplete (fs.js:117:15)
38 silly rollbackFailedOptional Starting
39 silly rollbackFailedOptional Finishing
40 silly runTopLevelLifecycles Starting
41 silly runTopLevelLifecycles Finishing
42 silly install printInstalled
43 verbose stack Error: No compatible version found: mysql@3.10.6
43 verbose stack Valid install targets:
43 verbose stack 2.11.1, 2.11.0, 2.10.2, 2.10.1, 2.10.0, 2.9.0, 2.8.0, 2.7.0, 2.6.2, 2.6.1, 2.6.0, 2.5.5, 2.5.4, 2.5.3, 2.5.2, 2.5.1, 2.5.0, 2.4.3, 2.4.2, 2.4.1, 2.4.0, 2.3.2, 2.3.1, 2.3.0, 2.2.0, 2.1.1, 2.1.0, 2.0.1, 2.0.0, 2.0.0-rc2, 2.0.0-rc1, 2.0.0-alpha9, 2.0.0-alpha8, 2.0.0-alpha7, 2.0.0-alpha6, 2.0.0-alpha5, 2.0.0-alpha4, 2.0.0-alpha3, 2.0.0-alpha2, 2.0.0-alpha, 0.9.6, 0.9.5, 0.9.4, 0.9.3, 0.9.2, 0.9.1, 0.9.0, 0.8.0, 0.7.0, 0.6.0, 0.5.0, 0.4.0, 0.3.0, 0.2.0, 0.1.0
43 verbose stack
43 verbose stack     at pickVersionFromRegistryDocument (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:178:16)
43 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/iferr/index.js:13:50
43 verbose stack     at /usr/local/lib/node_modules/npm/lib/utils/pulse-till-done.js:20:8
43 verbose stack     at saved (/usr/local/lib/node_modules/npm/lib/cache/caching-client.js:174:7)
43 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:210:7
43 verbose stack     at FSReqWrap.oncomplete (fs.js:117:15)
44 verbose cwd /Users/mac/Documents/tp1
45 error Darwin 15.6.0
46 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "mysql@3.10.6"
47 error node v6.2.0
48 error npm  v3.10.6
49 error No compatible version found: mysql@3.10.6
49 error Valid install targets:
49 error 2.11.1, 2.11.0, 2.10.2, 2.10.1, 2.10.0, 2.9.0, 2.8.0, 2.7.0, 2.6.2, 2.6.1, 2.6.0, 2.5.5, 2.5.4, 2.5.3, 2.5.2, 2.5.1, 2.5.0, 2.4.3, 2.4.2, 2.4.1, 2.4.0, 2.3.2, 2.3.1, 2.3.0, 2.2.0, 2.1.1, 2.1.0, 2.0.1, 2.0.0, 2.0.0-rc2, 2.0.0-rc1, 2.0.0-alpha9, 2.0.0-alpha8, 2.0.0-alpha7, 2.0.0-alpha6, 2.0.0-alpha5, 2.0.0-alpha4, 2.0.0-alpha3, 2.0.0-alpha2, 2.0.0-alpha, 0.9.6, 0.9.5, 0.9.4, 0.9.3, 0.9.2, 0.9.1, 0.9.0, 0.8.0, 0.7.0, 0.6.0, 0.5.0, 0.4.0, 0.3.0, 0.2.0, 0.1.0
50 error If you need help, you may report this error at:
50 error     <https://github.com/npm/npm/issues>
51 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@sam2908 I don't know how the error in your first log is happening, but your latest log indicates that you are trying to install `mysql@3.10.6`, but such a version of the `mysql` package does not exist. You can see a list of existing versions in the log:

```
2.11.1, 2.11.0, 2.10.2, 2.10.1, 2.10.0, 2.9.0, 2.8.0, 2.7.0, 2.6.2, 2.6.1, 2.6.0, 2.5.5, 2.5.4, 2.5.3, 2.5.2, 2.5.1, 2.5.0, 2.4.3, 2.4.2, 2.4.1, 2.4.0, 2.3.2, 2.3.1, 2.3.0, 2.2.0, 2.1.1, 2.1.0, 2.0.1, 2.0.0, 2.0.0-rc2, 2.0.0-rc1, 2.0.0-alpha9, 2.0.0-alpha8, 2.0.0-alpha7, 2.0.0-alpha6, 2.0.0-alpha5, 2.0.0-alpha4, 2.0.0-alpha3, 2.0.0-alpha2, 2.0.0-alpha, 0.9.6, 0.9.5, 0.9.4, 0.9.3, 0.9.2, 0.9.1, 0.9.0, 0.8.0, 0.7.0, 0.6.0, 0.5.0, 0.4.0, 0.3.0, 0.2.0, 0.1.0
```

**Comment by legodude17** [comment]
You got a different error that time then the first one. What did you do different?

**Comment by sam2908** [comment]
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "mysql"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.7

npm ERR! No compatible version found: mysql@undefined2.10.2
npm ERR! Valid install targets:
npm ERR! 2.11.1, 2.11.0, 2.10.2, 2.10.1, 2.10.0, 2.9.0, 2.8.0, 2.7.0, 2.6.2, 2.6.1, 2.6.0, 2.5.5, 2.5.4, 2.5.3, 2.5.2, 2.5.1, 2.5.0, 2.4.3, 2.4.2, 2.4.1, 2.4.0, 2.3.2, 2.3.1, 2.3.0, 2.2.0, 2.1.1, 2.1.0, 2.0.1, 2.0.0, 2.0.0-rc2, 2.0.0-rc1, 2.0.0-alpha9, 2.0.0-alpha8, 2.0.0-alpha7, 2.0.0-alpha6, 2.0.0-alpha5, 2.0.0-alpha4, 2.0.0-alpha3, 2.0.0-alpha2, 2.0.0-alpha, 0.9.6, 0.9.5, 0.9.4, 0.9.3, 0.9.2, 0.9.1, 0.9.0, 0.8.0, 0.7.0, 0.6.0, 0.5.0, 0.4.0, 0.3.0, 0.2.0, 0.1.0
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mac/Documents/tp1/npm-debug.log
testApp:tp1 mac$ sudo npm install mysql@2.11.2
Password:
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "mysql@2.11.2"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.7

npm ERR! No compatible version found: mysql@2.11.2
npm ERR! Valid install targets:
npm ERR! 2.11.1, 2.11.0, 2.10.2, 2.10.1, 2.10.0, 2.9.0, 2.8.0, 2.7.0, 2.6.2, 2.6.1, 2.6.0, 2.5.5, 2.5.4, 2.5.3, 2.5.2, 2.5.1, 2.5.0, 2.4.3, 2.4.2, 2.4.1, 2.4.0, 2.3.2, 2.3.1, 2.3.0, 2.2.0, 2.1.1, 2.1.0, 2.0.1, 2.0.0, 2.0.0-rc2, 2.0.0-rc1, 2.0.0-alpha9, 2.0.0-alpha8, 2.0.0-alpha7, 2.0.0-alpha6, 2.0.0-alpha5, 2.0.0-alpha4, 2.0.0-alpha3, 2.0.0-alpha2, 2.0.0-alpha, 0.9.6, 0.9.5, 0.9.4, 0.9.3, 0.9.2, 0.9.1, 0.9.0, 0.8.0, 0.7.0, 0.6.0, 0.5.0, 0.4.0, 0.3.0, 0.2.0, 0.1.0
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mac/Documents/tp1/npm-debug.log
testApp:tp1 mac$ sudo npm install mysql@2.10.0
mac@1.0.0 /Users/mac
└── mysql@2.10.0  invalid

**Comment by legodude17** [comment]
Try running `npm install mysql@2.11.1`.

**Comment by sam2908** [comment]
Hello @legodude17 
===============================
testApp:mysql mac$ sudo npm install mysql@2.11.1
mac@1.0.0 /Users/mac
└── mysql@2.11.1  invalid

**Comment by legodude17** [comment]
So it installed, but npm says it is invalid?

**Comment by sam2908** [comment]
👍
