### ISSUE TITLE
Search up the file system for bin scripts

### ISSUE THREAD

**Issue by doug-wade** [npm/npm#13747]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [ ] npm is producing an incorrect install.
- [ ] npm is doing something I don't understand.
- [x] Other (_see below for feature requests_):
#### What's going wrong?

Nothing!  You're great.
#### How can the CLI team reproduce the problem?

```
mkdir monorepo-root
cd monorepo-root
npm init --yes
npm i -D del-cli
mkdir -p packages/example
cd packages/example
npm init --yes
// add "scripts": { "prepublish": "del index.js" } to package.json
touch index.js
npm run prepublish
```

Expected (hoped?):
index.js is gone!  Success!

Actual:

```
dougwade packages/example » npm run prepublish

> example@1.0.0 prepublish /Users/doug.wade/npm-experiments/monorepo-root/packages/example
> del index.js

sh: del: command not found

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "run" "prepublish"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! example@1.0.0 prepublish: `del index.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the example@1.0.0 prepublish script 'del index.js'.
npm ERR! This is most likely a problem with the example package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     del index.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls example
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/doug.wade/npm-experiments/monorepo-root/packages/example/npm-debug.log
```
### supporting information:
- `npm -v` prints: 2.14.12
- `node -v` prints: 4.3.1
- `npm config get registry` prints: http://localhost:4873/ (sinopia)
- Windows, OS X, or Linux?: OS X
- Network issues:
  - Geographic location where npm was run:
  - [x] I use a proxy to connect to the npm registry.
  - [ ] I use a proxy to connect to the web.
  - [ ] I use a proxy when downloading Git repos.
  - [ ] I access the npm registry via a VPN
  - [ ] I don't use a proxy, but have limited or unreliable internet access.
- Container:
  - [ ] I develop using Vagrant on Windows.
  - [ ] I develop using Vagrant on OS X or Linux.
  - [ ] I develop / deploy using Docker.
  - [ ] I deploy to a PaaS (Triton, Heroku).
#### What's the feature?

I would like for npm to search up the file system for bin scripts in the same way node modules search up the file system for modules to import.  For instance, if I [had a monorepo](github.com/redfin/react-server) with many packages in it that have a [dependency](https://github.com/redfin/react-server/blob/master/packages/react-server/package.json#L11) [on](https://github.com/redfin/react-server/blob/master/packages/react-server-cli/package.json#L7) [gulp](https://github.com/redfin/react-server/blob/master/packages/react-server-integration-tests/package.json#L6), I'd like to be able to [install a single copy of gulp](https://github.com/redfin/react-server/blob/master/package.json#L26) at the monorepo root, and use it in bin scripts for all of the packages.
#### What problem is the feature intended to solve?

It keeps install times low and the ecosystem footprint on the file system small for developer who work in large monorepos, like [babel](https://github.com/babel/babel/packages), [react](https://github.com/facebook/react/tree/master/packages) and [meteor](https://github.com/meteor/meteor/tree/devel/packages).
#### Is the absence of this feature blocking you or your team? If so, how?

It is not, but the solution is ugly -- I have to encode the relative path to the monorepo root in the package.json of every node module in the monorepo that wants to use the global build tools.  The other option is to install the same build tools many times in the same project, which greatly increases install times (can be hard when supporting multiple versions, since you [may have to delete and reinstall node_modules to get a consistent tree](https://docs.npmjs.com/how-npm-works/npm3-nondet)) and makes the monorepo very large (currently, React Server is 2.1 gigs and Redfin's internal monorepo is 12 gigs of node modules alone).
#### Is this feature similar to an existing feature in another tool?

It very closely mimics the resolution of `require`s in node, though it is also similar to how many `.rc` files work.  There would be one major departure from node module resolution -- to maintain backwards compatibility, we would have to continue to allow globally-installed tools to take precedence over locally-installed tools, which is different than the [node module resolution algorithm](https://nodejs.org/api/modules.html#modules_all_together).  While I'm on backwards compatibility, this would also require a change to the `npm bin` command to take an argument.  Existing `npm bin` customers would have no change, but if you provided an argument `npm bin foo`, then you would get the path to `foo` (in the example I gave for reproducing, in monorepo-root/packages/example, `npm bin` would return /path/to/monorepo-root/packages/example/node_modules/.bin, whereas `npm bin del` would return /path/to/monorepo-root/node_modules/.bin).
#### Is this a feature you're prepared to implement, with support from the npm CLI team?

I would prefer to 😀!

**Comment by legodude17** [comment]
This sounds like a good idea, to mirror nodes resolution process.

**Comment by ruifortes** [comment]
Any updates on this topic? This would be huge to DRY

**Comment by legodude17** [comment]
I think you would be able to just use `require.resolve` to find the bin script. I will look into this.
