### ISSUE TITLE
Improved Subcommand Output

### ISSUE THREAD

**Issue by nixpulvis** [npm/npm#13751]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [ ] npm is producing an incorrect install.
- [ ] npm is doing something I don't understand.
- [x] Other (_see below for feature requests_):
#### What's the feature?

Improved subcommand output, where the list is more readable. At least not including the aliases in the list by default would be fine. 
#### What problem is the feature intended to solve?

This is to address the use case of a new user learning the tool by reading the output of just `npm`.
#### Is the absence of this feature blocking you or your team? If so, how?

No
#### Is this feature similar to an existing feature in another tool?

Yes, `cargo` has a much nicer default output for the command list.

```
Some common cargo commands are (see all commands with --list):
    build       Compile the current project
    clean       Remove the target directory
    doc         Build this project's and its dependencies' documentation
    new         Create a new cargo project
    init        Create a new cargo project in an existing directory
    run         Build and execute src/main.rs
    test        Run the tests
    bench       Run the benchmarks
    update      Update dependencies listed in Cargo.lock
    search      Search registry for crates
    publish     Package and upload this project to the registry
    install     Install a Rust binary

See 'cargo help <command>' for more information on a specific command.
```
#### Is this a feature you're prepared to implement, with support from the npm CLI team?

Sure, shouldn't be hard.

**Comment by legodude17** [comment]
I think that a better title for this would be 'Improved help output'. This seems like a good idea.

**Comment by nixpulvis** [comment]
Thanks Mr. Robot. Your doing *good* work.
