### ISSUE TITLE
Add a new stage: prebuild

### ISSUE THREAD

**Issue by wolfired** [npm/npm#13754]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [ ] npm is producing an incorrect install.
- [ ] npm is doing something I don't understand.
- [x] Other (_see below for feature requests_):

#### What's the feature?

Add a new install stage before the **build** stage: **prebuild**
#### What problem is the feature intended to solve?

In my typescript project, I hope to compile the ts file  locally after which is installed by npm, because the **build** stage will link the executable js, so I need the **prebuild** stage to generate the executable js at first

**Comment by legodude17** [comment]
npm will auto-run commands with pre* and post* when you run any command. So `npm run build` (or `npm build`) will run `prebuild` `build` `postbuild`, in that order.

**Comment by legodude17** [comment]
Or do you mean to run before `npm build` is run?
