### ISSUE TITLE
npm install is crashing without clear info

### ISSUE THREAD

**Issue by Rameshv** [npm/npm#13757]
#### I'm opening this issue because:
- [x] npm is crashing.
- [ ] npm is producing an incorrect install.
- [x] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
#### What's going wrong?

`npm install` keeps on crashing in one of my DigitalOcean server. It works fine in all the dev machines. It just started happening. The issue is there is no valid trace or log to debug. when i run npm install without verbose it shows

```
 / extract:validator: sill doParallel extract 415
terminated by signal SIGKILL (Forced quit)
```

with verbose

```
npm verb tar unpack /root/.npm/mocha/2.5.3/package.tgz
npm verb tar unpacking to /root/onehour-webapp/releases/20160824132017/node_modules/.staging/mocha-fb8bb661
npm verb gentlyRm don't care about contents; nuking /root/onehour-webapp/releases/20160824132017/node_modules/.staging/mocha-fb8bb661
npm verb tar unpack /root/.npm/node-geocoder/2.23.0/package.tgz
npm verb tar unpacking to /root/onehour-webapp/releases/20160824132017/node_modules/.staging/node-geocoder-a26279cb
npm verb gentlyRm don't care about contents; nuking /root/onehour-webapp/releases/20160824132017/node_modules/.staging/node-geocoder-a26279cb
KIlled \ extract:validator: verb gentlyRm don't care about contents; nuking /root/onehour-webapp/releases/20160824132017/node_modules/.staging/
```

Also if i install a gem thats causing the issue, in the above case (node-geocoder - line before the last) individually, it works fine. When i start again with npm install, this time node-geocoder passes and the same issue with some other gem.

I am struggling with this for few hours and cant understand whats happening.
### supporting information:
- `npm -v` prints: 3.10.3
- `node -v` prints: v6.4.0
- `npm config get registry` prints: https://registry.npmjs.org/
- Windows, OS X, or Linux?: Ubuntu
- Network issues:
  - Geographic location where npm was run:
  - [ ] I use a proxy to connect to the npm registry.
  - [ ] I use a proxy to connect to the web.
  - [ ] I use a proxy when downloading Git repos.
  - [ ] I access the npm registry via a VPN
  - [ ] I don't use a proxy, but have limited or unreliable internet access.
- Container:
  - [ ] I develop using Vagrant on Windows.
  - [ ] I develop using Vagrant on OS X or Linux.
  - [ ] I develop / deploy using Docker.
  - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
The errors are different with the first and second. Please upload `npm-debug.log` and post a link.

**Comment by hawkerboy7** [comment]
Had a similar issue. I am not sure if it is the same but with me the reason was not having enough memory available. Increasing/creating swap or installing modules individually instead of just `npm install` helped me since it requried less memory in one-go.
