### ISSUE TITLE
Jsforce Installation Errors

### ISSUE THREAD

**Issue by nikkipollina** [npm/npm#13756]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

NPM will not allow me to install jsforce for a variety of reasons (first was version incorrect when it was not). Now it says that it is refusing to install jsforce as a dependency of itself.

#### How can the CLI team reproduce the problem?

WRONG VERSION ERROR

DEPENDENCY ERROR
<--
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'jsforce' ]
2 info using npm@3.10.3
3 info using node@v6.3.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData jsforce
8 silly fetchNamedPackageData jsforce
9 silly mapToRegistry name jsforce
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'jsforce',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'jsforce',
12 silly mapToRegistry   name: 'jsforce',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/jsforce
14 verbose request uri https://registry.npmjs.org/jsforce
15 verbose request no auth needed
16 info attempt registry request try #1 at 9:18:02 AM
17 verbose request id 1e665b4263e59635
18 http request GET https://registry.npmjs.org/jsforce
19 http 200 https://registry.npmjs.org/jsforce
20 verbose headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
20 verbose headers   etag: '"4NVJAQSJLBDP7IPSGRLPFVSJG"',
20 verbose headers   'content-type': 'application/json',
20 verbose headers   'content-encoding': 'gzip',
20 verbose headers   'cache-control': 'max-age=300',
20 verbose headers   'content-length': '6388',
20 verbose headers   'accept-ranges': 'bytes',
20 verbose headers   date: 'Wed, 24 Aug 2016 13:18:03 GMT',
20 verbose headers   via: '1.1 varnish',
20 verbose headers   age: '0',
20 verbose headers   connection: 'close',
20 verbose headers   'x-served-by': 'cache-ord1726-ORD',
20 verbose headers   'x-cache': 'MISS',
20 verbose headers   'x-cache-hits': '0',
20 verbose headers   'x-timer': 'S1472044683.703562,VS0,VE144',
20 verbose headers   vary: 'Accept-Encoding' }
21 silly get cb [ 200,
21 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
21 silly get     etag: '"4NVJAQSJLBDP7IPSGRLPFVSJG"',
21 silly get     'content-type': 'application/json',
21 silly get     'content-encoding': 'gzip',
21 silly get     'cache-control': 'max-age=300',
21 silly get     'content-length': '6388',
21 silly get     'accept-ranges': 'bytes',
21 silly get     date: 'Wed, 24 Aug 2016 13:18:03 GMT',
21 silly get     via: '1.1 varnish',
21 silly get     age: '0',
21 silly get     connection: 'close',
21 silly get     'x-served-by': 'cache-ord1726-ORD',
21 silly get     'x-cache': 'MISS',
21 silly get     'x-cache-hits': '0',
21 silly get     'x-timer': 'S1472044683.703562,VS0,VE144',
21 silly get     vary: 'Accept-Encoding' } ]
22 verbose get saving jsforce to C:\Users\212466079\AppData\Roaming\npm-cache\registry.npmjs.org\jsforce\.cache.json
23 verbose correctMkdir C:\Users\212466079\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
24 silly install normalizeTree
25 silly loadCurrentTree Finishing
26 silly loadIdealTree Starting
27 silly install loadIdealTree
28 silly cloneCurrentTree Starting
29 silly install cloneCurrentTreeToIdealTree
30 silly cloneCurrentTree Finishing
31 silly loadShrinkwrap Starting
32 silly install loadShrinkwrap
33 silly loadShrinkwrap Finishing
34 silly loadAllDepsIntoIdealTree Starting
35 silly install loadAllDepsIntoIdealTree
36 silly rollbackFailedOptional Starting
37 silly rollbackFailedOptional Finishing
38 silly runTopLevelLifecycles Starting
39 silly runTopLevelLifecycles Finishing
40 silly install printInstalled
41 verbose stack Error: Refusing to install jsforce as a dependency of itself
41 verbose stack     at checkSelf (C:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:53:14)
41 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
41 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
41 verbose stack     at chain (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
41 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:16:5
41 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
41 verbose stack     at Array.forEach (native)
41 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
41 verbose stack     at Array.forEach (native)
41 verbose stack     at asyncMap (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
42 verbose cwd C:\Users\212466079\jsforce
43 error Windows_NT 6.1.7601
44 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "jsforce"
45 error node v6.3.0
46 error npm  v3.10.3
47 error code ENOSELF
48 error Refusing to install jsforce as a dependency of itself
49 error If you need help, you may report this error at:
49 error     <https://github.com/npm/npm/issues>
50 verbose exit [ 1, true ]
-->

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@nikkipollina Is the `"name"` property of your `package.json` set to `"jsforce"` by any chance? If so, could you please try changing that to something else? If that does not work, then could you try renaming this directory: `C:\Users\212466079\jsforce`?

**Comment by nikkipollina** [comment]
@KenanY no my package.json is named as such. What should I rename the directory to?

**Comment by KenanY** [comment]
@nikkipollina Just ensure that the directory name and the `"name"` property do not match the names of any of your dependencies.

**Comment by nikkipollina** [comment]
got this 
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'jsforce' ]
2 info using npm@3.10.3
3 info using node@v6.3.0
4 verbose config Skipping project config: C:\Users\212466079/.npmrc. (matches userconfig)
5 silly loadCurrentTree Starting
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 silly fetchPackageMetaData jsforce
9 silly fetchNamedPackageData jsforce
10 silly mapToRegistry name jsforce
11 silly mapToRegistry using default registry
12 silly mapToRegistry registry https://registry.npmjs.org/
13 silly mapToRegistry data Result {
13 silly mapToRegistry   raw: 'jsforce',
13 silly mapToRegistry   scope: null,
13 silly mapToRegistry   escapedName: 'jsforce',
13 silly mapToRegistry   name: 'jsforce',
13 silly mapToRegistry   rawSpec: '',
13 silly mapToRegistry   spec: 'latest',
13 silly mapToRegistry   type: 'tag' }
14 silly mapToRegistry uri https://registry.npmjs.org/jsforce
15 verbose request uri https://registry.npmjs.org/jsforce
16 verbose request no auth needed
17 info attempt registry request try #1 at 10:37:55 AM
18 verbose request id 17d6cb86a017ea68
19 verbose etag "4NVJAQSJLBDP7IPSGRLPFVSJG"
20 http request GET https://registry.npmjs.org/jsforce
21 info retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
22 info attempt registry request try #2 at 10:38:05 AM
23 verbose etag "4NVJAQSJLBDP7IPSGRLPFVSJG"
24 http request GET https://registry.npmjs.org/jsforce
25 info retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
26 info attempt registry request try #3 at 10:39:05 AM
27 verbose etag "4NVJAQSJLBDP7IPSGRLPFVSJG"
28 http request GET https://registry.npmjs.org/jsforce
29 silly get cb [ 304, undefined ]
30 verbose etag https://registry.npmjs.org/jsforce from cache
31 verbose get saving jsforce to C:\Users\212466079\AppData\Roaming\npm-cache\registry.npmjs.org\jsforce\.cache.json
32 verbose correctMkdir C:\Users\212466079\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
33 silly install normalizeTree
34 silly loadCurrentTree Finishing
35 silly loadIdealTree Starting
36 silly install loadIdealTree
37 silly cloneCurrentTree Starting
38 silly install cloneCurrentTreeToIdealTree
39 silly cloneCurrentTree Finishing
40 silly loadShrinkwrap Starting
41 silly install loadShrinkwrap
42 silly loadShrinkwrap Finishing
43 silly loadAllDepsIntoIdealTree Starting
44 silly install loadAllDepsIntoIdealTree
45 silly resolveWithNewModule jsforce@1.7.0 checking installable status
46 silly cache add args [ 'jsforce', null ]
47 verbose cache add spec jsforce
48 silly cache add parsed spec Result {
48 silly cache add   raw: 'jsforce',
48 silly cache add   scope: null,
48 silly cache add   escapedName: 'jsforce',
48 silly cache add   name: 'jsforce',
48 silly cache add   rawSpec: '',
48 silly cache add   spec: 'latest',
48 silly cache add   type: 'tag' }
49 silly addNamed jsforce@latest
50 verbose addNamed "latest" is being treated as a dist-tag for jsforce
51 info addNameTag [ 'jsforce', 'latest' ]
52 silly mapToRegistry name jsforce
53 silly mapToRegistry using default registry
54 silly mapToRegistry registry https://registry.npmjs.org/
55 silly mapToRegistry data Result {
55 silly mapToRegistry   raw: 'jsforce',
55 silly mapToRegistry   scope: null,
55 silly mapToRegistry   escapedName: 'jsforce',
55 silly mapToRegistry   name: 'jsforce',
55 silly mapToRegistry   rawSpec: '',
55 silly mapToRegistry   spec: 'latest',
55 silly mapToRegistry   type: 'tag' }
56 silly mapToRegistry uri https://registry.npmjs.org/jsforce
57 verbose addNameTag registry:https://registry.npmjs.org/jsforce not in flight; fetching
58 verbose get https://registry.npmjs.org/jsforce not expired, no request
59 silly addNameTag next cb for jsforce with tag latest
60 silly addNamed jsforce@1.7.0
61 verbose addNamed "1.7.0" is a plain semver version for jsforce
62 silly mapToRegistry name jsforce
63 silly mapToRegistry using default registry
64 silly mapToRegistry registry https://registry.npmjs.org/
65 silly mapToRegistry data Result {
65 silly mapToRegistry   raw: 'jsforce',
65 silly mapToRegistry   scope: null,
65 silly mapToRegistry   escapedName: 'jsforce',
65 silly mapToRegistry   name: 'jsforce',
65 silly mapToRegistry   rawSpec: '',
65 silly mapToRegistry   spec: 'latest',
65 silly mapToRegistry   type: 'tag' }
66 silly mapToRegistry uri https://registry.npmjs.org/jsforce
67 verbose addRemoteTarball https://registry.npmjs.org/jsforce/-/jsforce-1.7.0.tgz not in flight; adding
68 verbose addRemoteTarball [ 'https://registry.npmjs.org/jsforce/-/jsforce-1.7.0.tgz',
68 verbose addRemoteTarball   '48f5c81b924eb55345a6df62446854a40865136b' ]
69 info retry fetch attempt 1 at 10:39:06 AM
70 info attempt registry request try #1 at 10:39:06 AM
71 http fetch GET https://registry.npmjs.org/jsforce/-/jsforce-1.7.0.tgz
72 info retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
73 info attempt registry request try #2 at 10:39:16 AM
74 http fetch GET https://registry.npmjs.org/jsforce/-/jsforce-1.7.0.tgz
75 info retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
76 info attempt registry request try #3 at 10:40:16 AM
77 http fetch GET https://registry.npmjs.org/jsforce/-/jsforce-1.7.0.tgz
78 error fetch failed https://registry.npmjs.org/jsforce/-/jsforce-1.7.0.tgz
79 warn retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
80 info retry fetch attempt 2 at 10:40:26 AM
81 info attempt registry request try #1 at 10:40:26 AM
82 http fetch GET https://registry.npmjs.org/jsforce/-/jsforce-1.7.0.tgz
83 info retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
84 info attempt registry request try #2 at 10:40:36 AM
85 http fetch GET https://registry.npmjs.org/jsforce/-/jsforce-1.7.0.tgz
86 info retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
87 info attempt registry request try #3 at 10:41:36 AM
88 http fetch GET https://registry.npmjs.org/jsforce/-/jsforce-1.7.0.tgz
89 error fetch failed https://registry.npmjs.org/jsforce/-/jsforce-1.7.0.tgz
90 warn retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
91 info retry fetch attempt 3 at 10:42:36 AM
92 info attempt registry request try #1 at 10:42:36 AM
93 http fetch GET https://registry.npmjs.org/jsforce/-/jsforce-1.7.0.tgz
94 info retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
95 info attempt registry request try #2 at 10:42:46 AM
96 http fetch GET https://registry.npmjs.org/jsforce/-/jsforce-1.7.0.tgz
97 info retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
98 info attempt registry request try #3 at 10:43:46 AM
99 http fetch GET https://registry.npmjs.org/jsforce/-/jsforce-1.7.0.tgz
100 error fetch failed https://registry.npmjs.org/jsforce/-/jsforce-1.7.0.tgz
101 silly rollbackFailedOptional Starting
102 silly rollbackFailedOptional Finishing
103 silly runTopLevelLifecycles Starting
104 silly runTopLevelLifecycles Finishing
105 silly install printInstalled
106 verbose stack Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
106 verbose stack     at errnoException (dns.js:28:10)
106 verbose stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:79:26)
107 verbose cwd C:\Users\212466079
108 error Windows_NT 6.1.7601
109 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "jsforce"
110 error node v6.3.0
111 error npm  v3.10.3
112 error code ENOTFOUND
113 error errno ENOTFOUND
114 error syscall getaddrinfo
115 error network getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
116 error network This is most likely not a problem with npm itself
116 error network and is related to network connectivity.
116 error network In most cases you are behind a proxy or have bad network settings.
116 error network
116 error network If you are behind a proxy, please make sure that the
116 error network 'proxy' config is set properly.  See: 'npm help config'
117 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@nikkipollina As the error log indicates, that is likely an issue with your internet connection rather than with `npm` itself. Maybe you are behind a proxy or firewall?

**Comment by KenanY** [comment]
Closing since it has been a week with no response, and also since this is not an issue with `npm`.
