### ISSUE TITLE
Ubuntu 14.04 npm install not working.

### ISSUE THREAD

**Issue by nikolaaa4** [npm/npm#13759]
#### I'm opening this issue because:

  - [x] npm is producing an incorrect install.

#### What's going wrong?
I tried to run npm install and i got these errors (log) https://gist.github.com/nikolaaa4/943fd8a42cab2ea7596573e42c605b33
Node js version is v6.4.0
#### How can the CLI team reproduce the problem?

Reproduce the problem by using Ubuntu 14.04 , application https://github.com/BitQuote/AwesomeBot/ and npm install. Gist is https://gist.github.com/nikolaaa4/943fd8a42cab2ea7596573e42c605b33

**Comment by KenanY** [comment]
Gonna send a PR to that project to remove the dependency on the `fs` module. Might help.

**Comment by oleersoy** [comment]
I got it working by following the instructions in the SO answer.

**Comment by legodude17** [comment]
I think that is the reason.

**Comment by KenanY** [comment]
PR has been merged. @nikolaaa4, can you see if this is still an issue with https://github.com/BitQuote/AwesomeBot/commit/c3a816fb05cb311b98a1187a24baf0dc6aa5fe65?

**Comment by KenanY** [comment]
Closing as abandoned.
