### ISSUE TITLE
How to use npm scripts like `node_modules/.bin/cmd` on windows?

### ISSUE THREAD

**Issue by creeperyang** [npm/npm#13750]
For example:

``` json
{
  "scripts": {
    "compile": "node_modules/.bin/webpack"
  }
}
```

`npm run compile` will get `node_modules/.bin/webpack is not recognized as an internal or external command...`. 

Related to #2576

However if I remove `node_modules/.bin/`, I still get `webpack is not recognized as an internal or external command...`. 

So I can only install `webpack` globally?

env:

```
node@6.2.1
npm@3.9.3
```

**Comment by creeperyang** [comment]
I see `webpack.cmd` inside `.bin` dir, so can we use this and how?

Any suggestion will be appreciated.

**Comment by legodude17** [comment]
I think you will have to do `webpack.cmd` instead of `webpack`.

**Comment by creeperyang** [comment]
@legodude17 `"compile": "node_modules/.bin/webpack"`  ---> `npm run compile`, I get the same error message.

**Comment by legodude17** [comment]
@creeperyang Try `"compile": "node_modules/.bin/webpack.cmd"` or maybe `"compile": "webpack.cmd"`.

**Comment by creeperyang** [comment]
In fact I tried `"compile": "node_modules/.bin/webpack.cmd"` and get the same error.

**Comment by legodude17** [comment]
In that case, this appears to be a windows bug.

**Comment by felipedsc** [comment]
maybe it's too late, but i'm also learning react right now and had a similar problem...
as i'm running the command directly from cmd, ive changed the "/" to "\" and it worked...
the command line, in my case, must be "node_modules\.bin\webpack.cmd -d"...
i hope it helps someone :)

**Comment by legodude17** [comment]
@creeperyang does @felipedsc's solution help?

**Comment by creeperyang** [comment]
@legodude17  it works. @felipedsc thank you.

```js
{
  "scripts": {
    "compile": "node_modules\\.bin\\webpack.cmd"
  }
}
```

**Comment by legodude17** [comment]
Cool. Everything is good. Close @KenanY?

**Comment by minooo** [comment]
on win10 platform，just run like this 
`node_modules\.bin\webpack app/index.js  dist/bundle.js  `
it works!!

**Comment by shirkeswapnil** [comment]
felipedsc's solution helped...thanks :+1:
