### ISSUE TITLE
dedupe completes, but `npm ls` still shows multiple copies of the same package & same version

### ISSUE THREAD

**Issue by mikemaccana** [npm/npm#13767]
#### I'm opening this issue because:

  - [x] npm is producing an incorrect install.

#### What's going wrong?

I have multiple copies of jquery@2.2.4 installed. Running:

    > npm dedupe

Completes fine with no errors or other output. Afterwards checking with `npm ls`:

    > npm ls jquery
    myapp@1.0.0 C:\Users\mike\Documents\myapp
    +-- myapp-frontend@1.0.0
    | `-- jquery@2.2.4
    +-- myapp-frontend-order-list@0.0.0
    | `-- jquery@2.2.4
    +-- myapp-frontend-order-status@0.0.0
    | `-- jquery@2.2.4
    `-- jquery@2.2.4

#### How can the CLI team reproduce the problem?

Not sure asides from sending you an archive of the whole tree?

### supporting information:

 - `npm -v` prints: 
3.10.7

 - `node -v` prints:
v6.4.0

 - `npm config get registry` prints:
https://registry.npmjs.org/

 - Windows, OS X, or Linux?:
Windows

**Comment by legodude17** [comment]
I am guessing this is intentional and that `npm ls` does this on purpose to be easier to read. Try running `ls -R node_modules`.

**Comment by KenanY** [comment]
I can't check right now but I believe this is intentional.

**Comment by othiym23** [comment]
Closing as resolved; @KenanY has it correct in that `npm ls` shows the logical dependency tree, and not the physical tree as it's laid out on disk. We have plans to allow you to use `npm ls` to show the physical tree, that will show what deduping has done, but for now, you'll just have to use `ls`. Thanks for your time!

**Comment by mikemaccana** [comment]
Thanks @othiym23 ! The docs for https://docs.npmjs.com/cli/ls don't do enough to show that this is the logical rather than on-disk dependency tree, but it sounds ike that will be fixed when that feature is added.
