### ISSUE TITLE
Feature request: `npm support` should output all info needed for this tracker

### ISSUE THREAD

**Issue by mikemaccana** [npm/npm#13768]
#### I'm opening this issue because:

  - [x] Other (_see below for feature requests_):

#### What's going wrong?

Users need to run a bunch of commands, when the computer could just let them run a single command.

npm folk have to read bug reports missing important info.

#### How can the CLI team reproduce the problem?

This is feature request to make 'npm support' which would:

-   Include the npm-debug.log file.

And run: 

- `npm -v`
- `node -v`
- `npm config get registry` 
- Check the OS & `lsb_release -a` to check the distro

**Comment by KenanY** [comment]
Previously: https://github.com/npm/npm/issues/5214

**Comment by legodude17** [comment]
This is a lot like `npm report`, so I believe this can be closed, unless we want to debate the name.
