### ISSUE TITLE
`npm publish --force` with invalid package name (contain char `~`) and can't unpublish or publish any more.

### ISSUE THREAD

**Issue by liaosankai** [npm/npm#13764]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [ ] npm is producing an incorrect install.
- [ ] npm is doing something I don't understand.
- [x] Other (_see below for feature requests_):
#### What's going wrong?

I run `npm publish --force` with invalid package name (contain char `~` ) then it appear in [my package list](https://www.npmjs.com/~liaosankai) but without any verions number, it will can't unpublish or publish by cli any more.
#### How can the CLI team reproduce the problem?

run `npm init` with invalid package name like `liaosankai~---` and force pubilsh it. 

https://gist.github.com/liaosankai/9e4a44c2954ceffdae9738f362608e08
### supporting information:
- `npm -v` prints: `3.10.7`
- `node -v` prints: `v6.3.1`
- `npm config get registry` prints: `https://registry.npmjs.org/`
- Windows, OS X, or Linux?: `Windows`
- Network issues:
  - Geographic location where npm was run:
  - [ ] I use a proxy to connect to the npm registry.
  - [ ] I use a proxy to connect to the web.
  - [ ] I use a proxy when downloading Git repos.
  - [ ] I access the npm registry via a VPN
  - [ ] I don't use a proxy, but have limited or unreliable internet access.
- Container:
  - [ ] I develop using Vagrant on Windows.
  - [ ] I develop using Vagrant on OS X or Linux.
  - [ ] I develop / deploy using Docker.
  - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
On `3.9.5` and Linux I can say that this is probably just a windows issue.

**Comment by liaosankai** [comment]
@legodude17 I also try it on liunx (ubuntu 16) via hyper-V but has the same problem.
https://gist.github.com/liaosankai/d7a08ff652e1772c989b1f3bc8eeaadd

**Comment by legodude17** [comment]
I am on ubuntu 15. But maybe this is a `npm@3.10.x` issue.

**Comment by liaosankai** [comment]
Oh~no, I try run it again by terminal on [Cloud9](https://c9.io/) and use lower npm verson (v2.15.5), 

	npm ERR! publish Failed PUT 500
	npm ERR! Linux 4.2.0-c9
	npm ERR! argv "/home/ubuntu/.nvm/versions/node/v4.4.5/bin/node" "/home/ubuntu/.nvm/versions/node/v4.4.5/bin/npm" "publish"
	npm ERR! node v4.4.5
	npm ERR! npm  v2.15.5
	npm ERR! code E500

	npm ERR! "name was invalid" : liaosankai-~~~~
	npm ERR! 
	npm ERR! If you need help, you may report this error at:
	npm ERR!     <https://github.com/npm/npm/issues>

	npm ERR! Please include the following file with any support request:
	npm ERR!     /home/ubuntu/workspace/test/npm-debug.log

Detail log: https://gist.github.com/liaosankai/8a92784dccd6619814df0ca9e48b5249

I think maybe it's npm server bug?

**Comment by legodude17** [comment]
I don't know, can you try to find a specific range of versions of `npm` where this happens?

**Comment by liaosankai** [comment]
The problem is solved after update npm to v4.x.x
