### ISSUE TITLE
missing start script

### ISSUE THREAD

**Issue by jayrcerezo** [npm/npm#13765]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [*] npm is producing an incorrect install
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

missing script: start
please include the following file with any support request:
c:\\..\hello-world\npm-debug.log

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@jayrcerezo 

```
missing script: start
```

Do you have a `"start"` script defined in your `package.json`? Without one, `npm` will have no idea what you want it to run when you execute `npm start`.

**Comment by othiym23** [comment]
Closing as resolved; @KenanY is correct that you have to have a `"start"` entry in `"scripts"` in `package.json` to use `npm start`. Thanks for your time!
