### ISSUE TITLE
Reading flags passed to npm install

### ISSUE THREAD

**Issue by acbabis** [npm/npm#13777]
Is it possible for a postinstall script to read the parameters passed to npm install? The reason I ask is that I have a Jenkins build that only runs `npm install` and the only configuration I have privileges for is to pass parameters. Am I correct that passing parameters to `npm install` at build-time is useless for this purpose?

This is what I've tried:

``` javascript
"scripts": {
    "install": "npm run build -- $($@)",
    "build": "webpack"
}
```

`npm install --param=Foo`

**Comment by addaleax** [comment]
`npm install --param=Foo` would set the `npm_config_param` environment variable to `Foo`… I *think* that’s officially supported, although you might want to use an application-specific prefix (`e.g. --my-app-param=Foo`, used in your script as `$npm_config_my_app_param`) to avoid clashes with the actual `npm` config.

**Comment by legodude17** [comment]
@adaleax is right, using the environment variable setup would be the best way to do this.

**Comment by acbabis** [comment]
Ok, I did what @addaleax suggested and it works perfectly for my purposes. I think discoverability could be improved, though. This isn't described on the [`npm install` documentation page](https://docs.npmjs.com/cli/install) or the [npm scripts documentation page](https://docs.npmjs.com/misc/scripts), and Googling "npm custom parameters" didn't help me find anything useful. The `npm install` page has a link to [npm-config](https://docs.npmjs.com/misc/config), but you need prior knowledge to know to click on it because a) The feature name doesn't sound like what it describes, and b) It has the same name as [another page/feature](https://docs.npmjs.com/cli/config)

**Comment by legodude17** [comment]
How about you open another issue for `Document custom params in env vars in npm-scripts`?

**Comment by addaleax** [comment]
> The feature name doesn't sound like what it describes

Mhh. I think it does, these parameters are really about modifying npm’s config, the fact that the npm config is also available in your scripts is more of a side effect of that. *That* is probably worth mentioning in the docs, yes!

**Comment by acbabis** [comment]
@addaleax Does this mean that using the feature for application-specific flags is considered an anti-pattern?

**Comment by addaleax** [comment]
Maybe, I’m not sure I’m the right person to pass judgement here. I wouldn’t consider it too bad, and given the constraints you mentioned, it seems like the only choice.

And, fwiw, there are other examples that I know of that do similar things, e.g. build systems like node-gyp, so I wouldn’t worry about this feature getting changed or removed.
