### ISSUE TITLE
Installing npm modules programatically not creating node_modules folder for subdependencies

### ISSUE THREAD

**Issue by sumit08** [npm/npm#13779]
I am trying to install the node modules programatically, which is correctly installing my dependencies in the node_modules folder. But, the subdependencies are also getting installed in the same folder. Ideally, it should create another node_modules folder inside my dependency. Is there a workaround for this ??

**Comment by legodude17** [comment]
This feature is on purpose, to limit duplicates of modules. On good workaround would be to use `npm@2`, which doesn't have this logic.

**Comment by sumit08** [comment]
Hi legodude17,

So, the problem i am encountering is as follows:

All my dependencies and their sub-dependencies are getting installed in the same node_modules folder. The next time when I am try to install the same dependencies in another path, npm reads it from the cache and add the dependencies to the node_modules folder in that path, but the sub-dependencies are not being put there.

Can u tell me how to resolve that issue ???

**Comment by legodude17** [comment]
First, I am sorry for not understanding your issue. Second, it is not recommended to use the programmatic api. Third, can you make a repro for this issue?

**Comment by sumit08** [comment]
Hi legodude17,

I tried to use the npm@2 that you told and it seems to be working fine. I guess I can use that for my use case.

Thanks!!

**Comment by KenanY** [comment]
Closing as resolved.
