### ISSUE TITLE
Need ability to create read-only auth tokens

### ISSUE THREAD

**Issue by jwalton** [npm/npm#13772]
#### I'm opening this issue because:
  - Other _see below for feature requests_

#### What's the feature?

We're evaluating using npm private packages to make our lives easier within our organization.  But, one of the first problems we're running into is making this work with travis-ci (or, really, any CI server).  Travis-CI is going to need to an auth token to pull private npm packages.  Ideally, I want to give Travis an auth token that only has read access to our various packages, as there's no need for Travis to write any of our packages (and I also don't want to give it *my* npm auth key, since any user in the org can see the auth key, and I have permission to write to read and write packages outside our organization - but I'd settle for giving it a read-only version of my npm auth key).

What I really want is to create a read-only key that only has permission to see packages from our organization.  I can work around this right now by creating a dummy user and giving it read-only access to our organization's packages.  But this is a $7/month workaround, which is kinda sucky.  :P

**Comment by legodude17** [comment]
This should probably be on the npm-registry repo, as this repo is about the `npm` cli tool. Please go file a issue on that repo.

**Comment by othiym23** [comment]
@legodude17 is correct; this is something that would be implemented by the registry team, so [`npm/registry`](https://github.com/npm/registry/issues) is the place to take this feature request. As this isn't something the CLI team can implement on their own, I'm going to close it here, but I can tell you that this is something that's on the product team's road map, although it's not something that's scheduled yet.

**Comment by jwalton** [comment]
For future google-searchers, https://github.com/npm/registry/issues/27 is essentially the same issue over in npm/registry land.
