### ISSUE TITLE
How to cache / reduce / restrict the size of node_modules?

### ISSUE THREAD

**Issue by bboysathish** [npm/npm#13771]
Sorry, i am not going through the issue template, this more question than an issue.
1. Is there a way i can cache these node_modules other than `npm --offline`?
2. How to reduce the network round trips for each module?
3. It seems there is way to cahce modules using npm install --offline, but is there way i can change the npm global cache directory to point someother directory?
4. What does npm pack will do, will it help me on caching the modules locally and move from one server to server or keep it in a central folder so i can install from there any time ?
5. If i cache a module (eg: rimraf) using `npm install --offline`, when i once again install it on some other folder will it once again create the .bin directory for `rimraf`command inside node_modules directory?
6. Is there way i can configure only to download the required files instead of all the unwanted folder from the npm (E.g: take any module, only thing i need for the development is src/ dist directory), can i ignore other unwated directories like `test, docs, changelogs`?

Please close this issue,if this is not a proper place to discuss things (i searched for help repo, but no luck)

**Comment by legodude17** [comment]
You may want to use npm/support-cli next time. Anyway, here are your answers:

1. Use `npm cache add <name>`
2. There isn't really a way, unless you write another package with all of the deps hardcoded in and then install that instead.
3. Use `npm config set cache <dir>`
4. `npm pack` will simply create a tarball for the package in the current directory, of the same sort as is created by `npm publish to be published.
5. I think it will.
6. No there isn't a way to do this currently, open a new issue following the template as a feature request if you want this.

**Comment by bboysathish** [comment]
@legodude17 @othiym23 Is there a way / workaround for this

> Is there way i can configure only to download the required files instead of all the unwanted folder from the npm (E.g: take any module, only thing i need for the development is src/ dist directory), can i ignore other unwated directories like test, docs, changelogs

That would help reduce the network roundtrips and node_modules size ?.

i also have another question regarding this topic,

1. Will there a be difference in installation speed, when i disable `progress=false` in npmrc ?
2. Suppose i have shrinkwrap on a project, and use `npm install --offline` to install modules, what happens next time i install same modules ? Will it use the cached modules / once again download the modules ?
3. If log the modules installation with `npm install --verbose`, will it affect the installation speed ?

npm: version 3+
node: version 5+

Thanks

**Comment by legodude17** [comment]
Answers to questions:
1. I don't think so.
2. It will request them again.
3. No
