### ISSUE TITLE
Error while installing gulp --save-dev [dev-dependency]

### ISSUE THREAD

**Issue by vinishanto** [npm/npm#13781]
npm is not able to install gulp --save-dev

> npm install gulp --save-dev
> npm WARN package.json media@1.0.0 No repository field.
> npm WARN package.json media@1.0.0 No README data
> npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
> npm ERR! tar.unpack untar error /home/ukpdl/.npm/isarray/1.0.0/package.tgz
> npm ERR! tar.unpack untar error /home/ukpdl/.npm/pinkie/2.0.4/package.tgz
> npm ERR! tar.unpack untar error /home/ukpdl/.npm/pinkie/2.0.4/package.tgz
> npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
> npm ERR! tar.unpack untar error /home/ukpdl/.npm/number-is-nan/1.0.0/package.tgz
> npm ERR! tar.unpack untar error /home/ukpdl/.npm/error-ex/1.3.0/package.tgz
> npm ERR! tar.unpack untar error /home/ukpdl/.npm/is-utf8/0.2.1/package.tgz
> npm ERR! tar.unpack untar error /home/ukpdl/.npm/spdx-license-ids/1.2.2/package.tgz
> npm ERR! Linux 2.6.18-308.el5
> npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "gulp" "--save-dev"
> npm ERR! node v0.10.46
> npm ERR! npm  v2.15.1
> npm ERR! path ../user-home/cli.js
> npm ERR! code EROFS
> npm ERR! errno 56
> 
> npm ERR! rofs EROFS, symlink '../user-home/cli.js'
> npm ERR! rofs This is most likely not a problem with npm itself
> npm ERR! rofs and is related to the file system being read-only.
> npm ERR! rofs
> npm ERR! rofs Often virtualized file systems, or other file systems
> npm ERR! rofs that don't support symlinks, give this error.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /host/myown/newproj/EasyTicket/media/npm-debug.log

I am trying to do this in a virtual machine CentOS 5 on a windows machine

PS: attached the npm-debug.log

**Comment by KenanY** [comment]
@vinishanto Have you tried using the `--no-bin-links` flag?

**Comment by vinishanto** [comment]
Thanks for the reply @KenanY, 

I am facing different issue while using --no-bin-links

sudo npm install gulp --save-dev --no-bin-links
npm WARN package.json media@1.0.0 No repository field.
npm WARN package.json media@1.0.0 No README data
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm ERR! tar.unpack untar error /home/ukpdl/.npm/number-is-nan/1.0.0/package.tgz
npm ERR! tar.unpack untar error /home/ukpdl/.npm/pinkie/2.0.4/package.tgz
npm ERR! tar.unpack untar error /home/ukpdl/.npm/pinkie/2.0.4/package.tgz
npm ERR! tar.unpack untar error /home/ukpdl/.npm/is-utf8/0.2.1/package.tgz
npm ERR! tar.unpack untar error /home/ukpdl/.npm/isarray/1.0.0/package.tgz
npm ERR! tar.unpack untar error /home/ukpdl/.npm/error-ex/1.3.0/package.tgz
npm ERR! tar.unpack untar error /home/ukpdl/.npm/spdx-license-ids/1.2.2/package.tgz
npm ERR! Linux 2.6.18-308.el5
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "gulp" "--save-dev" "--no-bin-links"
npm ERR! node v0.10.46
npm ERR! npm  v2.15.1
npm ERR! path /host/myown/newproj/EasyTicket/media/node_modules/gulp/node_modules/liftoff/node_modules/findup-sync/node_modules/micromatch/node_modules/braces/node_modules/expand-range/node_modules/fill-range/node_modules/isobject/node_modules/isarray
npm ERR! code UNKNOWN
npm ERR! errno -1

npm ERR! UNKNOWN, mkdir '/host/myown/newproj/EasyTicket/media/node_modules/gulp/node_modules/liftoff/node_modules/findup-sync/node_modules/micromatch/node_modules/braces/node_modules/expand-range/node_modules/fill-range/node_modules/isobject/node_modules/isarray'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /host/myown/newproj/EasyTicket/media/npm-debug.log

**Comment by legodude17** [comment]
Try running `npm cache clean`. Then try again.

**Comment by KenanY** [comment]
Closing due to no response.
