### ISSUE TITLE
npm uses ASCII progress bar on Windows even when unicode=true

### ISSUE THREAD

**Issue by felixfbecker** [npm/npm#13780]
#### What's going wrong?

Since the update that introduced the new progress bar, NPM uses an ASCII progress bar again on Windows even when unicode is set to true through config, option or env var. `npm ls` uses unicode characters correctly.
#### How can the CLI team reproduce the problem?

On Windows all these reproduce:

```
npm install --unicode=true

npm config set unicode true
npm install

set NPM_CONFIG_UNICODE=true
npm install
```
### supporting information:
- `npm -v` prints: 3.10.6
- `node -v` prints: v6.0.0
- Windows, OS X, or Linux?: Windows

**Comment by KenanY** [comment]
Well, the docs do say that the config only affects tree output:

> When set to true, npm uses unicode characters in the tree output. When false, it uses ascii characters to draw trees.

**Comment by felixfbecker** [comment]
True, but don't you think it should also force the usage of unicode progress bars on windows? There is no way to get a nice progress bar on windows even though cmd and powershell had support for it since Vista, because it cannot be auto-detected, so it is assumed to not be there.

**Comment by othiym23** [comment]
Paging @iarna for an explanation of why `gauge` works this way; she can explain it much better than I can.

**Comment by felixfbecker** [comment]
Why is this labeled support? Imo this is a bug

**Comment by felixfbecker** [comment]
@othiym23 Imo this is still a feature request and still happening with npm 5 and the latest Windows

**Comment by othiym23** [comment]
You'll have to discuss that with @iarna; my employment with npm, Inc. was terminated in January, and I'm no longer affiliated with the project, nor do I have the requisite privileges to modify or label issues.
