### ISSUE TITLE
Error 503 No healthy backends

### ISSUE THREAD

**Issue by StarpTech** [npm/npm#13787]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):
  - [X] NPM registry is crashing

#### What's going wrong?

Can't install my private repository

#### How can the CLI team reproduce the problem?

Package: seneca-plugin-balance

### supporting information:

 - `npm -v` prints:
3.10.3 or v3.10.5
 - `node -v` prints:
v6.3.1 or v4.2.3
 - `npm config get registry` prints:
 - Windows, OS X, or Linux?:
WINDOWS
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

```
Error 503 No healthy backends

No healthy backends

Guru Mediation:

Details: cache-fra1240-FRA 1472396241 523992930

Varnish cache server
```

**Comment by StarpTech** [comment]
Now it works. I had to republished it. I think there is a problem. I leave it open.

**Comment by othiym23** [comment]
This is an issue with the registry, not the CLI (I know, the line isn't incredibly clear between the two). If you run into this again, or think it's not resolved, please open a new issue on [`npm/registry`](https://github.com/npm/registry/issues), and the registry team will get you sorted out. Thanks for your time!
