### ISSUE TITLE
npm-version: inconsistency between tag and message

### ISSUE THREAD

**Issue by aristidesfl** [npm/npm#13796]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?
npm-version uses *1.0.1* for commit message and *v1.0.1* for tag name.

The version pattern should be the same for tag and commit message.  I would suggest removing the `v` from the tagname since it is redundant. Alternatively allow the configuration of the tag pattern via [git-tag-version](https://docs.npmjs.com/cli/version#git-tag-version).

#### How can the CLI team reproduce the problem?
```
npm init
git init
npm version patch
git log
git tag
```

### supporting information:

 - `npm -v` prints: 3.10.3
 - `node -v` prints: v6.4.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X, or Linux?: OS X

**Comment by othiym23** [comment]
This is configurable via [`tag-version-prefix`](https://docs.npmjs.com/misc/config#tag-version-prefix), added in 21148620fa03a582f4ec436bb16bd472664f2737. The CLI team would be happy to merge in a patch that adds `v` before the commit message version, but this isn't something we're going to have time to do ourselves anytime soon. As such, I'm going to close this as resolved / up to the community to patch. Thanks for your time!

**Comment by aristidesfl** [comment]
Should this information be added to https://docs.npmjs.com/cli/version ?
