### ISSUE TITLE
Getting error while trying to install fsevents@1.0.12

### ISSUE THREAD

**Issue by onkarojha77** [npm/npm#13797]
We have previous version of the artifact installed "fsevents@0.3.5" in Nexus.
However not able to install the version 1.0.12 version of "fsevents"
Attaching the log.
[fsevents@1.0.12.txt](https://github.com/npm/npm/files/443191/fsevents.1.0.12.txt)

#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@onkarojha77 `fsevents` is a Mac-only module, but you are on Linux. Therefore you cannot install that module onto your system, since it exposes an API for something which is only present in Macs anyways. Closing since this is not an issue with `npm`.

**Comment by onkarojha77** [comment]
Thanks for update, 
Do you mean this version of artifact (fsevents@1.0.12) is only for Mac?
Because, we have installed fsevents@0.3.5 on linux machine.

**Comment by KenanY** [comment]
@onkarojha77 The entire module has always been a wrapper around an OS X feature, just check out the [repository](https://github.com/strongloop/fsevents). I don't know why/how an older version did not produce the error you are seeing. Personally I get the same error as you do when I try to `npm install fsevents@0.3.5` on linux.
