### ISSUE TITLE
 UNABLE_TO_VERIFY_LEAF_SIGNATURE

### ISSUE THREAD

**Issue by ramjanardhan** [npm/npm#13791]
C:\Users\miracle>npm install -g phonegap
npm ERR! Windows_NT 6.1.7600
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\
node_modules\npm\bin\npm-cli.js" "install" "-g" "phonegap"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code UNABLE_TO_VERIFY_LEAF_SIGNATURE

npm ERR! unable to verify the first certificate
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\miracle\npm-debug.log

**Comment by LIAMSACC** [comment]
I have this too!

**Comment by LIAMSACC** [comment]
Mine was firewall,
