### ISSUE TITLE
Referring to #13797  (Getting error while trying to install fsevents@1.0.12)

### ISSUE THREAD

**Issue by onkarojha77** [npm/npm#13798]
Referring to the ticket 13797.

We have previous version of the artifact installed ("fsevents@0.3.5") in Nexus.

---
https://repo.aedc.extra.aexp.com/nexus/content/groups/npm/fsevents

{"versions":{"0.3.5":{"os":["darwin"],"keywords":["fsevents","mac"],"engines":{"node":">=0.8.0"},"devDependencies":{"tap":"~0.4.8"},"homepage":"https://github.com/pipobscure/fsevents","version":"0.3.5","main":"fsevents.js","scripts":{"install":"node-gyp rebuild","test":"export PATH=$PATH:`pwd`/node_nodules/.bin/ && tap ./test"},"author":"Philipp Dunkel <pip@pipobscure.com>","bugs":{"url":"https://github.com/pipobscure/fsevents/issues"},"dependencies":{"nan":"~1.5.0"},"repository":{"type":"git","url":"https://github.com/pipobscure/fsevents.git"},"description":"Native Access to Mac OS-X FSEvents","name":"fsevents","license":"MIT","dist":{"shasum":"d0938147614066c0e1297647b3b8ab5a4baf4688","tarball":"https://repo.aedc.extra.aexp.com/nexus/content/groups/npm/fsevents/-/fsevents-0.3.5.tgz"},"gypfile":true}},"time":{"0.3.5":"2016-07-18T20:45:42.681Z","created":"2016-07-18T20:45:42.681Z","modified":"2016-07-20T17:30:31.112Z"},"keywords":["fsevents","mac"],"description":"Native Access to Mac OS-X FSEvents","name":"fsevents","x-nx-rebuilt":"2016-07-20T10:30:31.111-0700","homepage":"https://github.com/pipobscure/fsevents","dist-tags":{"latest":"0.3.5"}}

---

Is there any work around to install  fsevents@1.0.12 on linux machine?
Because i can see the fsevents@0.3.5 version is available on Nexus.

#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@onkarojha77 Could you expand on why you would like to install this module on linux?

**Comment by onkarojha77** [comment]
I want the workaround, how the previous version of this artifact was installed. Similarly, can install this version also.

**Comment by KenanY** [comment]
@onkarojha77 Maybe add it as an [optional dependency](https://docs.npmjs.com/files/package.json#optionaldependencies) to your `package.json` so that it won't throw an error on failure?

**Comment by KenanY** [comment]
Closing as abandoned.
