### ISSUE TITLE
npm doesn't update global packages

### ISSUE THREAD

**Issue by Nikki1993** [npm/npm#13792]
#### I'm opening this issue because:
- [x] npm is producing an incorrect install.
#### What's going wrong?

Updating global node modules doesn't actually update them
#### How can the CLI team reproduce the problem?

Trying to upgrade npm-check-updates module

```
C:\Users\Nikki
λ npm install -g npm-check-updates@latest
C:\Users\Nikki\AppData\Roaming\npm\npm-check-updates -> C:\Users\Nikki\AppData\Roaming\npm\node_modules\npm-check-updates\bin\npm-check-updates
C:\Users\Nikki\AppData\Roaming\npm\ncu -> C:\Users\Nikki\AppData\Roaming\npm\node_modules\npm-check-updates\bin\ncu
C:\Users\Nikki\AppData\Roaming\npm
`-- npm-check-updates@2.8.0


C:\Users\Nikki
λ ncu -V
2.7.2
```
### supporting information:
- `npm -v` prints: 3.10.6
- `node -v` prints: v6.4.0
- `npm config get registry` prints: https://registry.npmjs.org/
- Windows, OS X, or Linux?: Windows 10 64bit Professional + Anniversary Update 

I checked general FAQ but couldn't find anything relevant to the case. I am installing modules using Cmder http://cmder.net/ with admin rights, but same result is thrown using default Windows CMD with/without admin rights.

**Comment by maximhoffman** [comment]
+1 The same
