### ISSUE TITLE
Unable to install npm

### ISSUE THREAD

**Issue by bikash6718** [npm/npm#13804]
I am facing problem at the time of install npm through command prompt. I have windows 7 operating system.  I have already install node js in c:\\Programfiles\NodeJs path. Below the error details and also attached npm debug file.

Error :
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! syscall connect

npm ERR! network connect ETIMEDOUT 151.101.8.162:443
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\bikashchandra.das\angular2-quickstart\npm-debug.log

C:\Users\bikashchandra.das\angular2-quickstart>

**Comment by KenanY** [comment]
@bikash6718 As the error indicates, this is an issue with your internet connection, not with `npm`. Are you behind a proxy or firewall by any chance?

**Comment by atiqch** [comment]
Ghost blog installation is failing on shared hosting server (CloudLinux), please advise how to fix this issue.

npm ERR! fetch failed https://github.com/AileenCGN/amperize/tarball/fixed-layout-for-small-images

npm http 200 https://registry.npmjs.org/tr46/-/tr46-0.0.3.tgz
npm http GET https://registry.npmjs.org/nconf/-/nconf-0.8.4.tgz
npm http GET https://registry.npmjs.org/ncp/-/ncp-0.4.2.tgz
npm http GET https://github.com/AileenCGN/amperize/tarball/fixed-layout-for-small-images
npm ERR! fetch failed https://github.com/AileenCGN/amperize/tarball/fixed-layout-for-small-images
npm http GET https://github.com/AileenCGN/amperize/tarball/fixed-layout-for-small-images
npm ERR! fetch failed https://github.com/AileenCGN/amperize/tarball/fixed-layout-for-small-images
npm ERR! Error: getaddrinfo EADDRINFO
npm ERR!     at errnoException (dns.js:37:11)
npm ERR!     at Object.onanswer [as oncomplete] (dns.js:124:16)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 2.6.32-673.8.1.lve1.4.3.1.el6.x86_64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--production"
npm ERR! cwd /home/rahidelv/blog
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! syscall getaddrinfo
npm ERR! code EADDRINFO
npm ERR! errno EADDRINFO

**Comment by KenanY** [comment]
Closing since this is an internet connection issue, not a `npm` one.

**Comment by mayerwin** [comment]
Same issue here, it is definitely a problem with the ISP (connecting via 3G works), however there should be a way to support specifying a number of retries as this would also work consistently (the ISP seems to be blocking bursting connections, but it is very short).

**Comment by legodude17** [comment]
@mayerwin, you could check the docs. Also, please file a new issue for this feature request.
