### ISSUE TITLE
npm publish ./  would not install cli tool on linux

### ISSUE THREAD

**Issue by jdcrecur** [npm/npm#13808]
#### I'm opening this issue because:

 npm is producing an incorrect install of a package
#### What's going wrong?

I produced an npm package cli tool on my windows 10 machine. Title 'quilk'.

URL: https://www.npmjs.com/package/quilk

After publishing the tool to npm I could successfully install the tool on a windows machine and call it from cli via 'quilk'. 

When publishing the package from windows 10 and installing globally on a linux box the package would not run. Entering 'quilk' resulted in ': No such file or directory'.

After a life time of variations in the package.json etc etc. I tried to publish the package from ubuntu. After publishing the package from ubuntu I could run the cli tool in both linux and windows machine.
#### How can the CLI team reproduce the problem?

1 - on a windows 10 build with cygwin installed.
2 - create a simple npm cli package eg: http://tutorialzine.com/2014/09/creating-your-first-node-js-command-line-application/
3 - From powershell or cmd or phpstorm ide terminal on the windows 10 machine publish the package.
4 - Now try access the npm cli tool, the output will be `: No such file or directory`

Now clone your repo to your linux machine and republish from there.. suddenly it all works.
### supporting information:

windows machine (I was previously on node4 but this failed so upgraded)
- `npm -v` prints:  3.10.3
- `node -v` prints: 6.5.0 
- `npm config get registry` prints: https://registry.npmjs.org/
- Windows, OS X, or Linux?: windows 10 home

Ubuntu 14lts, node 6.4.0, npm 3.10.3

linux server (failed to run after built from windows)
- `npm -v` prints:  3.10.3
- `node -v` prints: 6.4.0 
- `npm config get registry` prints: https://registry.npmjs.org/
- Windows, OS X, or Linux?: Ubuntu 14 lts

linux server2 (failed to run after built from windows)
- `npm -v` prints:  2.11.3
- `node -v` prints: 0.12.7 
- Windows, OS X, or Linux?: Debian 6.0.10

linux server (published from and now works on linux and windows)
- `npm -v` prints:  3.10.3
- `node -v` prints: 6.4.0 
- `npm config get registry` prints: https://registry.npmjs.org/
- Windows, OS X, or Linux?: Ubuntu 14 lts

**Comment by johnc1984** [comment]
I was playing around with this module again today https://www.npmjs.com/package/quilk

What I have found is that the issue with publishing is something to with line endings. it seems when the line endings are windows it doesn't want to play ball.

Using the dos2unix tool I was able to easily convert all EOLs to unix. 
`find quilk -type f | xargs dos2unix`

After running this conversion I could publish to npm and then globally install and all was fine.

But this does seem like something NPM should automatically do in its core when publishing?
