### ISSUE TITLE
Getting errors with "npm install" on Windows 7 (32-bit)

### ISSUE THREAD

**Issue by kullu46** [npm/npm#13809]
Hello Developers,
I am new to nodejs and I am stuck with the bunch of errors while trying to install nodejs on my windows server. Below is the errors log, any help will be appropriated truly!!

`0 info it worked if it ends with ok`
`1 verbose cli [ 'D:\\nodejs\\node.exe',`
`1 verbose cli   'D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',`
`1 verbose cli   'start' ]`
`2 info using npm@3.10.3`
`3 info using node@v6.5.0`
`4 verbose stack Error: missing script: start`
`4 verbose stack     at run (D:\nodejs\node_modules\npm\lib\run-script.js:151:19)`
`4 verbose stack     at D:\nodejs\node_modules\npm\lib\run-script.js:61:5`
`4 verbose stack     at D:\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:356:5`
`4 verbose stack     at handleExists (D:\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:329:20)`
`4 verbose stack     at FSReqWrap.cb [as oncomplete] (fs.js:257:19)`
`5 verbose cwd C:\Users\prashant\AppData\Roaming\npm`
`6 error Windows_NT 6.1.7600`
`7 error argv "D:\\nodejs\\node.exe" "D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"`
`8 error node v6.5.0`
`9 error npm  v3.10.3`
`10 error missing script: start`
`11 error If you need help, you may report this error at:`
`11 error     <https://github.com/npm/npm/issues>`
`12 verbose exit [ 1, true ]`

Please help!!

**Comment by KenanY** [comment]
@kullu46 You do not need to run `npm start` in order to install nodejs. This error is occurring because you are running `npm start` within a directory whose `package.json` does not contain a `"start"` script. `npm` has no idea what you want it to run so it intentionally throws that error. Closing since this is not an issue with `npm` itself.

**Comment by KenanY** [comment]
Adding a `"start"` script would like so (modify for your project):

``` json
{
  "scripts": {
    "start": "node src/index.js"
  }
}
```

**Comment by kullu46** [comment]
@KenanY Thank you for the response. Actually I had these similar errors while installing node and the above bug report is related to 'npm start' (as you said). Sorry for wrong explanation. I will open a new issue and post debug file there.

Thanks again!!
