### ISSUE TITLE
npm ERR! Windows_NT 6.1.7601

### ISSUE THREAD

**Issue by perryjamesdev** [npm/npm#13816]
#### I'm opening this issue because:
- [x] npm is crashing.
- [X] npm is producing an incorrect install.
- [x] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
#### What's going wrong?

cant install from package.json. First i receive a warning saying a skipped optional dependency followed by a notsup - not compatible with your os or architecture then the Windows_NT error

I am currently not behind a proxy but do use a work computer.

[npm-debug.txt](https://github.com/npm/npm/files/445942/npm-debug.txt)
#### How can the CLI team reproduce the problem?

I'm installing the Predix Polymer only branch found here: https://github.com/PredixDev/predix-seed/tree/polymer-only 

### supporting information:
- `npm -v` prints:
- `node -v` prints:
- `npm config get registry` prints:
- Windows, OS X, or Linux?:
- Network issues:
  - Geographic location where npm was run:
  - [ ] I use a proxy to connect to the npm registry.
  - [ ] I use a proxy to connect to the web.
  - [ ] I use a proxy when downloading Git repos.
  - [ ] I access the npm registry via a VPN
  - [ ] I don't use a proxy, but have limited or unreliable internet access.
- Container:
  - [ ] I develop using Vagrant on Windows.
  - [ ] I develop using Vagrant on OS X or Linux.
  - [ ] I develop / deploy using Docker.
  - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by perrah** [comment]
npm -v: 3.10.6
node -v: 4.5.0
npm config get registy: http://registry.npmjs.org/
Windows Machine
