### ISSUE TITLE
I am trying to install azure-storage on a remote server through the console on the Azure Portal and running into problems 

### ISSUE THREAD

**Issue by gubyy** [npm/npm#13813]
When I run 'npm install azure-storage' it adds the azure-storage folder to my node_modules but it has not files in it, only sub folders. Here is a screen shot of the folder:
![screen shot 2016-08-30 at 2 28 08 pm](https://cloud.githubusercontent.com/assets/11578073/18101765/ffd7cf58-6ebd-11e6-80f7-ee757ac5eb97.png)

The server is running node version: v0.8.28 and npm version: 1.2.30

Here is the error stack I get when running 'npm install azure-storage'

npm WARN package.json azure-mobile-services-migration@1.0.0 No repository field.
npm WARN package.json azure-mobile-services-migration@1.0.0 No readme data.
npm WARN package.json azure@0.6.9-zumo No readme data.
npm WARN package.json azure-mobile-services@1.0.0 No repository field.
npm WARN package.json azure-mobile-services@1.0.0 No readme data.
npm WARN package.json sendgrid@0.2.4 No readme data.
npm WARN package.json sendgrid@0.2.4 homepage field must be a string url. Deleted.
npm WARN package.json request@2.9.152 No readme data.
npm http GET https://registry.npmjs.org/azure-storage
npm http 200 https://registry.npmjs.org/azure-storage
npm http GET https://registry.npmjs.org/azure-storage/-/azure-storage-1.3.0.tgz
npm http 200 https://registry.npmjs.org/azure-storage/-/azure-storage-1.3.0.tgz
npm http GET https://registry.npmjs.org/extend
npm http GET https://registry.npmjs.org/browserify-mime
npm http GET https://registry.npmjs.org/json-edm-parser/0.1.2
npm http GET https://registry.npmjs.org/node-uuid
npm http GET https://registry.npmjs.org/readable-stream
npm http GET https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/validator
npm http GET https://registry.npmjs.org/xml2js/0.2.7
npm http GET https://registry.npmjs.org/xmlbuilder/0.4.3
npm http 200 https://registry.npmjs.org/node-uuid
npm http 200 https://registry.npmjs.org/extend
npm http 200 https://registry.npmjs.org/readable-stream
npm http 200 https://registry.npmjs.org/browserify-mime
npm http 200 https://registry.npmjs.org/underscore
npm http 200 https://registry.npmjs.org/request
npm http 200 https://registry.npmjs.org/validator
npm http 200 https://registry.npmjs.org/xml2js/0.2.7
npm http GET https://registry.npmjs.org/node-uuid/-/node-uuid-1.4.7.tgz
npm http GET https://registry.npmjs.org/extend/-/extend-1.2.1.tgz
npm http GET https://registry.npmjs.org/readable-stream/-/readable-stream-2.0.6.tgz
npm http GET https://registry.npmjs.org/validator/-/validator-3.22.2.tgz
npm http GET https://registry.npmjs.org/request/-/request-2.74.0.tgz
npm http GET https://registry.npmjs.org/xml2js/-/xml2js-0.2.7.tgz
npm http 200 https://registry.npmjs.org/readable-stream/-/readable-stream-2.0.6.tgz
npm http 200 https://registry.npmjs.org/node-uuid/-/node-uuid-1.4.7.tgz
npm http 200 https://registry.npmjs.org/extend/-/extend-1.2.1.tgz
npm http 200 https://registry.npmjs.org/validator/-/validator-3.22.2.tgz
npm http 200 https://registry.npmjs.org/xml2js/-/xml2js-0.2.7.tgz
npm http 200 https://registry.npmjs.org/json-edm-parser/0.1.2
npm http 200 https://registry.npmjs.org/xmlbuilder/0.4.3
npm http GET https://registry.npmjs.org/json-edm-parser/-/json-edm-parser-0.1.2.tgz
npm http 200 https://registry.npmjs.org/request/-/request-2.74.0.tgz
npm http GET https://registry.npmjs.org/underscore/-/underscore-1.4.4.tgz
npm http GET https://registry.npmjs.org/xmlbuilder/-/xmlbuilder-0.4.3.tgz
npm http 200 https://registry.npmjs.org/json-edm-parser/-/json-edm-parser-0.1.2.tgz
npm http 200 https://registry.npmjs.org/underscore/-/underscore-1.4.4.tgz
npm http GET https://registry.npmjs.org/browserify-mime/-/browserify-mime-1.2.9.tgz
npm http 200 https://registry.npmjs.org/xmlbuilder/-/xmlbuilder-0.4.3.tgz
npm http 200 https://registry.npmjs.org/browserify-mime/-/browserify-mime-1.2.9.tgz
npm WARN engine validator@3.22.2: wanted: {"node":">= 0.10"} (current: {"node":"v0.8.28","npm":"1.2.30"})
npm http GET https://registry.npmjs.org/jsonparse
npm http 200 https://registry.npmjs.org/jsonparse
npm http GET https://registry.npmjs.org/jsonparse/-/jsonparse-1.2.0.tgz
npm http 200 https://registry.npmjs.org/jsonparse/-/jsonparse-1.2.0.tgz
npm http GET https://registry.npmjs.org/sax/0.5.2
npm http 200 https://registry.npmjs.org/sax/0.5.2
npm http GET https://registry.npmjs.org/sax/-/sax-0.5.2.tgz
npm http 200 https://registry.npmjs.org/sax/-/sax-0.5.2.tgz
npm http GET https://registry.npmjs.org/core-util-is
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/isarray
npm http GET https://registry.npmjs.org/process-nextick-args
npm http GET https://registry.npmjs.org/string_decoder
npm http GET https://registry.npmjs.org/util-deprecate
npm http 200 https://registry.npmjs.org/core-util-is
npm http 200 https://registry.npmjs.org/process-nextick-args
npm http 200 https://registry.npmjs.org/string_decoder
npm http 200 https://registry.npmjs.org/inherits
npm http 200 https://registry.npmjs.org/isarray
npm http 200 https://registry.npmjs.org/util-deprecate
npm http GET https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz
npm http GET https://registry.npmjs.org/process-nextick-args/-/process-nextick-args-1.0.7.tgz
npm http GET https://registry.npmjs.org/string_decoder/-/string_decoder-0.10.31.tgz
npm http GET https://registry.npmjs.org/inherits/-/inherits-2.0.1.tgz
npm http GET https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz
npm http GET https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz
npm http 200 https://registry.npmjs.org/process-nextick-args/-/process-nextick-args-1.0.7.tgz
npm http 200 https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz
npm http 200 https://registry.npmjs.org/string_decoder/-/string_decoder-0.10.31.tgz
npm http 200 https://registry.npmjs.org/inherits/-/inherits-2.0.1.tgz
npm http 200 https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz
npm http 200 https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz
npm http GET https://registry.npmjs.org/aws-sign2
npm http GET https://registry.npmjs.org/aws4
npm http GET https://registry.npmjs.org/bl
npm http GET https://registry.npmjs.org/caseless
npm http GET https://registry.npmjs.org/combined-stream
npm http GET https://registry.npmjs.org/forever-agent
npm http GET https://registry.npmjs.org/form-data
npm http GET https://registry.npmjs.org/har-validator
npm http GET https://registry.npmjs.org/hawk
npm http GET https://registry.npmjs.org/http-signature
npm http GET https://registry.npmjs.org/is-typedarray
npm http GET https://registry.npmjs.org/isstream
npm http GET https://registry.npmjs.org/json-stringify-safe
npm http GET https://registry.npmjs.org/mime-types
npm http GET https://registry.npmjs.org/oauth-sign
npm http GET https://registry.npmjs.org/stringstream
npm http GET https://registry.npmjs.org/qs
npm http GET https://registry.npmjs.org/tough-cookie
npm http GET https://registry.npmjs.org/tunnel-agent
npm http 200 https://registry.npmjs.org/aws-sign2
npm http 200 https://registry.npmjs.org/caseless
npm http 200 https://registry.npmjs.org/combined-stream
npm http 200 https://registry.npmjs.org/bl
npm http 200 https://registry.npmjs.org/aws4
npm http 200 https://registry.npmjs.org/forever-agent
npm http 200 https://registry.npmjs.org/har-validator
npm http 200 https://registry.npmjs.org/form-data
npm http 200 https://registry.npmjs.org/hawk
npm http 200 https://registry.npmjs.org/is-typedarray
npm http 200 https://registry.npmjs.org/http-signature
npm http 200 https://registry.npmjs.org/isstream
npm http 200 https://registry.npmjs.org/mime-types
npm http 200 https://registry.npmjs.org/json-stringify-safe
npm http 200 https://registry.npmjs.org/oauth-sign
npm http 200 https://registry.npmjs.org/stringstream
npm http 200 https://registry.npmjs.org/qs
npm http 200 https://registry.npmjs.org/tough-cookie
npm http 200 https://registry.npmjs.org/tunnel-agent
npm http GET https://registry.npmjs.org/extend/-/extend-3.0.0.tgz
npm http 200 https://registry.npmjs.org/extend/-/extend-3.0.0.tgz
npm http GET https://registry.npmjs.org/combined-stream/-/combined-stream-1.0.5.tgz
npm http GET https://registry.npmjs.org/caseless/-/caseless-0.11.0.tgz
npm http GET https://registry.npmjs.org/bl/-/bl-1.1.2.tgz
npm http GET https://registry.npmjs.org/aws-sign2/-/aws-sign2-0.6.0.tgz
npm http GET https://registry.npmjs.org/forever-agent/-/forever-agent-0.6.1.tgz
npm http GET https://registry.npmjs.org/har-validator/-/har-validator-2.0.6.tgz
npm http GET https://registry.npmjs.org/form-data/-/form-data-1.0.1.tgz
npm http GET https://registry.npmjs.org/hawk/-/hawk-3.1.3.tgz
npm http GET https://registry.npmjs.org/is-typedarray/-/is-typedarray-1.0.0.tgz
npm http GET https://registry.npmjs.org/http-signature/-/http-signature-1.1.1.tgz
npm http 200 https://registry.npmjs.org/combined-stream/-/combined-stream-1.0.5.tgz
npm http 200 https://registry.npmjs.org/caseless/-/caseless-0.11.0.tgz
npm http GET https://registry.npmjs.org/isstream/-/isstream-0.1.2.tgz
npm http GET https://registry.npmjs.org/mime-types/-/mime-types-2.1.11.tgz
npm http 200 https://registry.npmjs.org/bl/-/bl-1.1.2.tgz
npm http GET https://registry.npmjs.org/json-stringify-safe/-/json-stringify-safe-5.0.1.tgz
npm http GET https://registry.npmjs.org/oauth-sign/-/oauth-sign-0.8.2.tgz
npm http GET https://registry.npmjs.org/stringstream/-/stringstream-0.0.5.tgz
npm http GET https://registry.npmjs.org/qs/-/qs-6.2.1.tgz
npm http 200 https://registry.npmjs.org/aws-sign2/-/aws-sign2-0.6.0.tgz
npm http GET https://registry.npmjs.org/tough-cookie/-/tough-cookie-2.3.1.tgz
npm http GET https://registry.npmjs.org/tunnel-agent/-/tunnel-agent-0.4.3.tgz
npm http 200 https://registry.npmjs.org/form-data/-/form-data-1.0.1.tgz
npm http 200 https://registry.npmjs.org/hawk/-/hawk-3.1.3.tgz
npm http 200 https://registry.npmjs.org/har-validator/-/har-validator-2.0.6.tgz
npm http 200 https://registry.npmjs.org/forever-agent/-/forever-agent-0.6.1.tgz
npm http 200 https://registry.npmjs.org/is-typedarray/-/is-typedarray-1.0.0.tgz
npm http 200 https://registry.npmjs.org/http-signature/-/http-signature-1.1.1.tgz
npm http 200 https://registry.npmjs.org/isstream/-/isstream-0.1.2.tgz
npm http 200 https://registry.npmjs.org/mime-types/-/mime-types-2.1.11.tgz
npm http 200 https://registry.npmjs.org/qs/-/qs-6.2.1.tgz
npm http 200 https://registry.npmjs.org/oauth-sign/-/oauth-sign-0.8.2.tgz
npm http 200 https://registry.npmjs.org/stringstream/-/stringstream-0.0.5.tgz
npm http 200 https://registry.npmjs.org/json-stringify-safe/-/json-stringify-safe-5.0.1.tgz
npm http 200 https://registry.npmjs.org/tough-cookie/-/tough-cookie-2.3.1.tgz
npm http 200 https://registry.npmjs.org/tunnel-agent/-/tunnel-agent-0.4.3.tgz
npm ERR! Error: EPERM, mkdir 'D:\home\site\wwwroot\node_modules\azure-storage\node_modules\readable-stream\node_modules'
npm ERR! { [Error: EPERM, mkdir 'D:\home\site\wwwroot\node_modules\azure-storage\node_modules\readable-stream\node_modules']
npm ERR! errno: 50,
npm ERR! code: 'EPERM',
npm ERR! path: 'D:\home\site\wwwroot\node_modules\azure-storage\node_modules\readable-stream\node_modules',
npm ERR! fstream_type: 'Directory',
npm ERR! fstream_path: 'D:\home\site\wwwroot\node_modules\azure-storage\node_modules\readable-stream\node_modules\core-util-is',
npm ERR! fstream_class: 'DirWriter',
npm ERR! fstream_stack: 
npm ERR! [ 'D:\Program Files (x86)\npm\1.2.30\node_modules\npm\node_modules\fstream\lib\writer.js:171:23',
npm ERR! 'D:\Program Files (x86)\npm\1.2.30\node_modules\npm\node_modules\mkdirp\index.js:37:53',
npm ERR! 'Object.oncomplete (fs.js:302:15)' ] }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "node" "D:\Program Files (x86)\npm\1.2.30\node_modules\npm\bin\npm-cli.js" "install" "azure-storage"
npm ERR! cwd D:\home\site\wwwroot
npm ERR! node -v v0.8.28
npm ERR! npm -v 1.2.30
npm ERR! path D:\home\site\wwwroot\node_modules\azure-storage\node_modules\readable-stream\node_modules
npm ERR! fstream_path D:\home\site\wwwroot\node_modules\azure-storage\node_modules\readable-stream\node_modules\core-util-is
npm ERR! fstream_type Directory
npm ERR! fstream_class DirWriter
npm ERR! code EPERM
npm ERR! errno 50
npm ERR! stack Error: EPERM, mkdir 'D:\home\site\wwwroot\node_modules\azure-storage\node_modules\readable-stream\node_modules'
npm ERR! fstream_stack D:\Program Files (x86)\npm\1.2.30\node_modules\npm\node_modules\fstream\lib\writer.js:171:23
npm ERR! fstream_stack D:\Program Files (x86)\npm\1.2.30\node_modules\npm\node_modules\mkdirp\index.js:37:53
npm ERR! fstream_stack Object.oncomplete (fs.js:302:15)
npm ERR! Error: EPERM, mkdir 'D:\home\site\wwwroot\node_modules\azure-storage\node_modules\readable-stream\node_modules'
npm ERR! { [Error: EPERM, mkdir 'D:\home\site\wwwroot\node_modules\azure-storage\node_modules\readable-stream\node_modules']
npm ERR! errno: 50,
npm ERR! code: 'EPERM',
npm ERR! path: 'D:\home\site\wwwroot\node_modules\azure-storage\node_modules\readable-stream\node_modules',
npm ERR! fstream_type: 'Directory',
npm ERR! fstream_path: 'D:\home\site\wwwroot\node_modules\azure-storage\node_modules\readable-stream\node_modules\isarray',
npm ERR! fstream_class: 'DirWriter',
npm ERR! fstream_stack: 
npm ERR! [ 'D:\Program Files (x86)\npm\1.2.30\node_modules\npm\node_modules\fstream\lib\writer.js:171:23',
npm ERR! 'D:\Program Files (x86)\npm\1.2.30\node_modules\npm\node_modules\mkdirp\index.js:37:53',
npm ERR! 'Object.oncomplete (fs.js:302:15)' ] }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "node" "D:\Program Files (x86)\npm\1.2.30\node_modules\npm\bin\npm-cli.js" "install" "azure-storage"
npm ERR! cwd D:\home\site\wwwroot
npm ERR! node -v v0.8.28
npm ERR! npm -v 1.2.30
npm ERR! path D:\home\site\wwwroot\node_modules\azure-storage\node_modules\readable-stream\node_modules
npm ERR! fstream_path D:\home\site\wwwroot\node_modules\azure-storage\node_modules\readable-stream\node_modules\isarray
npm ERR! fstream_type Directory
npm ERR! fstream_class DirWriter
npm ERR! code EPERM
npm ERR! errno 50
npm ERR! stack Error: EPERM, mkdir 'D:\home\site\wwwroot\node_modules\azure-storage\node_modules\readable-stream\node_modules'
npm ERR! fstream_stack D:\Program Files (x86)\npm\1.2.30\node_modules\npm\node_modules\fstream\lib\writer.js:171:23
npm ERR! fstream_stack D:\Program Files (x86)\npm\1.2.30\node_modules\npm\node_modules\mkdirp\index.js:37:53
npm ERR! fstream_stack Object.oncomplete (fs.js:302:15)
npm ERR! Error: EPERM, mkdir 'D:\home\site\wwwroot\node_modules\azure-storage\node_modules\readable-stream\node_modules'
npm ERR! { [Error: EPERM, mkdir 'D:\home\site\wwwroot\node_modules\azure-storage\node_modules\readable-stream\node_modules']
npm ERR! errno: 50,
npm ERR! code: 'EPERM',
npm ERR! path: 'D:\home\site\wwwroot\node_modules\azure-storage\node_modules\readable-stream\node_modules',
npm ERR! fstream_type: 'Directory',
npm ERR! fstream_path: 'D:\home\site\wwwroot\node_modules\azure-storage\node_modules\readable-stream\node_modules\inherits',
npm ERR! fstream_class: 'DirWriter',
npm ERR! fstream_stack: 
npm ERR! [ 'D:\Program Files (x86)\npm\1.2.30\node_modules\npm\node_modules\fstream\lib\writer.js:171:23',
npm ERR! 'D:\Program Files (x86)\npm\1.2.30\node_modules\npm\node_modules\mkdirp\index.js:37:53',
npm ERR! 'Object.oncomplete (fs.js:302:15)' ] }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "node" "D:\Program Files (x86)\npm\1.2.30\node_modules\npm\bin\npm-cli.js" "install" "azure-storage"
npm ERR! cwd D:\home\site\wwwroot
npm ERR! node -v v0.8.28
npm ERR! npm -v 1.2.30
npm ERR! path D:\home\site\wwwroot\node_modules\azure-storage\node_modules\readable-stream\node_modules
npm ERR! fstream_path D:\home\site\wwwroot\node_modules\azure-storage\node_modules\readable-stream\node_modules\inherits
npm ERR! fstream_type Directory
npm ERR! fstream_class DirWriter
npm ERR! code EPERM
npm ERR! errno 50
npm ERR! stack Error: EPERM, mkdir 'D:\home\site\wwwroot\node_modules\azure-storage\node_modules\readable-stream\node_modules'
npm ERR! fstream_stack D:\Program Files (x86)\npm\1.2.30\node_modules\npm\node_modules\fstream\lib\writer.js:171:23
npm ERR! fstream_stack D:\Program Files (x86)\npm\1.2.30\node_modules\npm\node_modules\mkdirp\index.js:37:53
npm ERR! fstream_stack Object.oncomplete (fs.js:302:15)
npm ERR! error rolling back Error: ENOTEMPTY, rmdir 'D:\home\site\wwwroot\node_modules\azure-storage\node_modules'
npm ERR! error rolling back azure-storage@1.3.0 { [Error: ENOTEMPTY, rmdir 'D:\home\site\wwwroot\node_modules\azure-storage\node_modules']
npm ERR! error rolling back errno: 53,
npm ERR! error rolling back code: 'ENOTEMPTY',
npm ERR! error rolling back path: 'D:\home\site\wwwroot\node_modules\azure-storage\node_modules' }
npm ERR! Error: No compatible version found: aws4@'^1.2.1'
npm ERR! Valid install targets:
npm ERR! ["0.0.1","0.1.0","0.1.1","0.1.2","0.1.3","0.1.4","0.1.5","0.1.6","0.1.7","0.1.8","0.1.9","0.1.10","0.1.12","0.2.0","0.2.1","0.2.2","0.2.3","0.3.0","0.4.0","0.4.1","0.4.2","0.5.0","0.5.1","1.0.0","1.0.1","1.0.2","1.0.3","1.0.4","1.1.0","1.2.0","1.2.1","1.3.1","1.3.2","1.4.0","1.4.1"]
npm ERR! at installTargetsError (D:\Program Files (x86)\npm\1.2.30\node_modules\npm\lib\cache.js:719:10)
npm ERR! at D:\Program Files (x86)\npm\1.2.30\node_modules\npm\lib\cache.js:641:10
npm ERR! at saved (D:\Program Files (x86)\npm\1.2.30\node_modules\npm\node_modules\npm-registry-client\lib\get.js:138:7)
npm ERR! at Object.oncomplete (fs.js:302:15)
npm ERR! If you need help, you may report this log at:
npm ERR! http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR! npm-@googlegroups.com

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "node" "D:\Program Files (x86)\npm\1.2.30\node_modules\npm\bin\npm-cli.js" "install" "azure-storage"
npm ERR! cwd D:\home\site\wwwroot
npm ERR! node -v v0.8.28
npm ERR! npm -v 1.2.30
npm

**Comment by KenanY** [comment]
@gubyy Node.js v0.8 and `npm@1.2` are **years** old and are no longer supported, as per the ["important"](https://github.com/npm/npm#important) heading in the README. Try updating both Node.js and `npm` to their respective, latest stable versions and try again. If you still face this issue, just let me know and I will promptly reopen this ticket.
