### ISSUE TITLE
I am not able to install xterm.js

### ISSUE THREAD

**Issue by mihirsevak** [npm/npm#13814]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [X ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Can someone help me with this?? I am not a Javascript programmer and getting following error.
Thanks.

npm ERR! tar pack Error reading /home/msevak/tmp/npm-11365-JuB01KWo/1472580123899-0.599480866221711/package
npm ERR! Error: ENOENT, chmod '/home/msevak/tmp/npm-11365-JuB01KWo/1472580123645-0.0021773686166852713/package/array/#/diff.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.4.0-34-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/msevak/Development/xterm.js
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /home/msevak/tmp/npm-11365-JuB01KWo/1472580123645-0.0021773686166852713/package/array/#/diff.js
npm ERR! fstream_path /home/msevak/tmp/npm-11365-JuB01KWo/1472580123645-0.0021773686166852713/package/array/#/diff.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! fstream_finish_call chmod
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:305:19
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:431:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 4.4.0-34-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwdnpm /home/msevak/Development/xterm.js/node_modules/pty.js
 ERR! gypaddLocalDirectory  Could not pack "/home/msevak/tmp/npm-11365-JuB01KWo/1472580123899-0.599480866221711/package" to "/home/msevak/.npm/es6-set/0.1.4/package.tgz"

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@mihirsevak `npm@1.3` is years old and is no longer supported. Please try updating to either `npm@2` or `npm@3`. If you still see this issue with either of those versions, please let me know and I will happily reopen.
