### ISSUE TITLE
Not able to install angular 2 using angular-cli

### ISSUE THREAD

**Issue by karanbisht** [npm/npm#13815]
please check this error---

C:\Users\samsung>npm cache clean

C:\Users\samsung>npm uninstall -g angular-cli

C:\Users\samsung>npm install -g angular-cli
npm WARN deprecated lodash-node@2.4.1: This package has been discontinued in favor of lodash@^4.0.0.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
C:\Users\samsung\AppData\Roaming\npm
`-- (empty)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Users\samsung\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "install" "-g" "angular-cli"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.6
npm ERR! path C:\Users\samsung\AppData\Roaming\npm\node_modules.staging\is-npm-71262700\package.json.2134052185
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\samsung\AppData\Roaming\npm\node_modules.staging\is-npm-71262700\package.json.2134052185' -> 'C:\Users\samsung\AppData\Roaming\npm\node_modules.staging\is-npm-71262700\package.json'
npm ERR!     at Error (native)
npm ERR!  { Error: EPERM: operation not permitted, rename 'C:\Users\samsung\AppData\Roaming\npm\node_modules.staging\is-npm-71262700\package.json.2134052185' -> 'C:\Users\samsung\AppData\Roaming\npm\node_modules.staging\is-npm-71262700\package.json'
npm ERR!     at Error (native)
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'rename',
npm ERR!   path: 'C:\Users\samsung\AppData\Roaming\npm\node_modules\.staging\is-npm-71262700\package.json.2134052185',
npm ERR!   dest: 'C:\Users\samsung\AppData\Roaming\npm\node_modules\.staging\is-npm-71262700\package.json',
npm ERR!   parent: 'angular-cli' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\samsung\npm-debug.log
npm ERR! code 1

**Comment by lholmquist** [comment]
@karanbisht looks like you don't have the correct persmissions,  try the suggestion from the log

`npm ERR! Please try running this command again as root/Administrator.
`

so `sudo npm install -g angular-cli `
