### ISSUE TITLE
npm refusing to install eddystone-beacon-scanner as a dependency of itself

### ISSUE THREAD

**Issue by RajPratim21** [npm/npm#13817]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  -  

npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
got above message while trying to install node-eddystone-beacon-scanner
on ubuntu 16.04 under proxy (proxy has been set)
can anyone help me with above

**Comment by KenanY** [comment]
@RajPratim21 Is the `"name"` property of your `package.json` set to `"eddystone-beacon-scanner"`? Is there an `npm-debug.log` file you can provide?

**Comment by RajPratim21** [comment]
yes "name" property of package.json  is set to "eddystone-beacon-scanner"
the scren shot of package.json file
![packafe-json](https://cloud.githubusercontent.com/assets/15442871/18126352/633bd8ac-6f98-11e6-9c2a-31cf223b5e06.png)

This the screen shot of log file 
![screenshot from 2016-08-31 16-27-57](https://cloud.githubusercontent.com/assets/15442871/18126241/efab3d42-6f97-11e6-8a52-f68c6e890e43.png)

**Comment by KenanY** [comment]
@RajPratim21 Try changing that so something unique (not sharing a name with one of your dependencies).

**Comment by RajPratim21** [comment]
should I change name to something unique?

**Comment by KenanY** [comment]
@RajPratim21 Yeah.

**Comment by KenanY** [comment]
Closing as resolved.
