### ISSUE TITLE
Erstwhile working npm install fails 

### ISSUE THREAD

**Issue by sathyakumarseshachalam** [npm/npm#13829]
#### I'm opening this issue because:

  - [ ] npm is doing something I don't understand.

#### What's going wrong?
```
npm install used to work all the time via my CI is now failing with 
npm ERR! Invalid Package: expected taffydb but found taffydb-jsdoc
npm ERR!
```
#### How can the CLI team reproduce the problem?
Just do `npm install gulp-jsdoc -g`

### supporting information:

 - `npm -v` prints: 2.15.1
 - `node -v` prints: v4.4.3
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X, or Linux?: OS X
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use an proxy to connect to the npm registry.
 - Container:
   - [ ] I develop using on OS X

**Comment by strann** [comment]
https://github.com/jsdoc3/jsdoc/issues/1249

**Comment by KenanY** [comment]
Closing in favor of jsdoc3/jsdoc#1249.
