### ISSUE TITLE
 packages with CLI do not work

### ISSUE THREAD

**Issue by hmuschett** [npm/npm#13828]
#### I'm opening this issue because:

  - [x ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### How can the CLI team reproduce the problem?
I have installed node-6.5 and npm-3.10 and each time I install any package that has CLI, my console me not recognize the command, example (angular-cli, nodemon ..)the package is installed but the command does not work

$ npm list -g --depth=0
C:\Users\local\npm-local\npm-global
+-- angular-cli@1.0.0-beta.10
+-- nativefier@7.0.1
`-- nodemon@1.10.2

ERR angular-cli
$ ng --help
bash: ng: command not found

ERR nodemon
$ nodemon index.js
bash: nodemon: command not found

### supporting information:

 - `npm -v` prints: 6.5
 - `node -v` prints:3.10.3
 - `npm config get registry` prints:
 - Windows, 8.1

**Comment by KenanY** [comment]
@hmuschett Is `C:\Users\local\npm-local\npm-global` in your `PATH`?

**Comment by hmuschett** [comment]
@KenanY thanck you i resolve :)

**Comment by zawars** [comment]
I am confused. How to resolve it? Help plz. @KenanY @hmuschett

**Comment by hmuschett** [comment]
@zawars hi you have to do is add the route where global npm packages are installed on your var  "path", if you're using win

**Comment by zawars** [comment]
Can you tell me the exact route.? I am new to npm

**Comment by zawars** [comment]
@hmuschett my npm is working but ng command is not.  It says 
Ng command not found. 

Plz help.

**Comment by legodude17** [comment]
@zawars, you have to add the result of `npm config get prefix` for your `$PATH`. Hope that helps.
