### ISSUE TITLE
npm login has to work headless

### ISSUE THREAD

**Issue by athoune** [npm/npm#13827]
`npm` use a prompt for `login`, you can bypass it in a shell, with \n and |, but it breaks provisionning. I don't want to use `expect` to handle such basic feature.

**Comment by doug-wade** [comment]
@athoune we get around using `login` by having puppet deploy a `.npmrc` file in the user's home directory with the token in it already.  You should be able to get the token by logging in; it'll look something like

```
//registry.npmjs.org/:_authToken=
```

**Comment by athoune** [comment]
Thanks for the puppet's trick, but the token is eternal?

**Comment by leoselig** [comment]
@athoune
This works:

```sh
echo -e "$NPM_USERNAME\n$NPM_PASSWORD\n$NPM_EMAIL" | npm login
```

(https://glebbahmutov.com/blog/automatically-publish-to-npm/)
(Note the `-e` for the `echo` command)

To catch any errors (wrong credentials, bad format of input etc.), you can rely on the exit code > 0
However, in an error case the output is quite weird as you will get
```
npm ERR! cb() never called!
```

(also mentioned here https://github.com/npm/npm/issues/11320)

**Comment by athoune** [comment]
This just works with bash.

Here is a test with ruby, same error with your Docker test.
```
$ irb
2.2.2 :001 > `echo -e "pim\npam\npoum@toto.com" | npm login`
npm WARN Name may not contain non-url-safe chars
npm ERR! cb() never called!
 => "Username: (athoune) Username: (athoune) "
2.2.2 :002 >
```

**Comment by leoselig** [comment]
@athoune thanks for pointing out, updated my comment, it might still be helpful to others
We actually hit the same issue later on wercker as well
Hoping for a real headless login soon then

**Comment by qiyuan-wang** [comment]
@athoune According to [npm's doc](https://docs.npmjs.com/private-modules/ci-server-config),

> The token is not derived from your password, but changing your password will invalidate all tokens. The token will be valid until the password is changed. You can also invalidate a single token by logging out on a machine that is logged in with that token.

So, it would be eternal if you did not change your password or log out.

**Comment by edsonbryan** [comment]
this command works for me... `npm config set "//registry.npmjs.org/:_authToken" "%npm_auth_token%"` , logging in locally and getting the token from .npmrc file.
