### ISSUE TITLE
npm init not creating json file

### ISSUE THREAD

**Issue by sunilreddyc** [npm/npm#13825]
#### I'm opening this issue because:
npm init not creating the json file. It is just coming out after prompting name. pasted below. 

$ npm init
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sane defaults.

See `npm help json` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg> --save` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
name: (myapp)
ramesh@sunil MINGW32 ~/Desktop/myapp

it also produced npm debug as below
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'init' ]
2 info using npm@1.3.2
3 info using node@v0.10.13
4 error Error: read ENOTCONN
4 error     at errnoException (net.js:901:11)
4 error     at Socket._read (net.js:391:21)
4 error     at Socket.Readable.read (_stream_readable.js:320:10)
4 error     at Socket.read (net.js:293:43)
4 error     at new Socket (net.js:185:10)
4 error     at process.stdin (node.js:660:19)
4 error     at read (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\read\lib\read.js:18:36)
4 error     at PromZard.prompt (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\init-package-json\node_modules\promzard\promzard.js:214:3)
4 error     at PromZard.L (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\init-package-json\node_modules\promzard\promzard.js:177:21)
4 error     at PromZard.walk (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\init-package-json\node_modules\promzard\promzard.js:146:5)
5 error If you need help, you may report this log at:
5 error     <http://github.com/isaacs/npm/issues>
5 error or email it to:
5 error     <npm-@googlegroups.com>
6 error System Windows_NT 6.1.7601
7 error command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "init"
8 error cwd C:\Users\ramesh\Desktop\raju
9 error node -v v0.10.13
10 error npm -v 1.3.2
11 error syscall read
12 error code ENOTCONN
13 error errno ENOTCONN
14 verbose exit [ 1, true ]
please let me know how to resolve this. I updated npm, uninstalled and reinstalled but the issue is not resolved.

**Comment by KenanY** [comment]
```
9 error node -v v0.10.13
10 error npm -v 1.3.2
```

@sunilreddyc `npm@1.3` is years old and is no longer supported. Please try [updating](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows). I'll reopen this if you still have this issue with `npm@2` or `npm@3`.
