### ISSUE TITLE
npm run typings install - fails

### ISSUE THREAD

**Issue by KarlXOL** [npm/npm#13838]
#### I'm opening this issue because:

  - npm run typings install - fails

#### What's going wrong?
Please see here the debug log:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\kpecadmin\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'typings',
1 verbose cli   'install' ]
2 info using npm@3.10.3
3 info using node@v6.2.2
4 verbose stack Error: missing script: typings
4 verbose stack     at run (C:\Users\kpecadmin\AppData\Roaming\npm\node_modules\npm\lib\run-script.js:151:19)
4 verbose stack     at C:\Users\kpecadmin\AppData\Roaming\npm\node_modules\npm\lib\run-script.js:61:5
4 verbose stack     at C:\Users\kpecadmin\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:356:5
4 verbose stack     at checkBinReferences_ (C:\Users\kpecadmin\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:320:45)
4 verbose stack     at final (C:\Users\kpecadmin\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:354:3)
4 verbose stack     at then (C:\Users\kpecadmin\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:124:5)
4 verbose stack     at ReadFileContext.<anonymous> (C:\Users\kpecadmin\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:295:20)
4 verbose stack     at ReadFileContext.callback (C:\Users\kpecadmin\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16)
4 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:359:13)
5 verbose cwd C:\KPECDAT\13_Development\mobimoang\angcord\app
6 error Windows_NT 6.3.9600
7 error argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\kpecadmin\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "typings" "install"
8 error node v6.2.2
9 error npm  v3.10.3
10 error missing script: typings
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

**Comment by zaninime** [comment]
If you want to install `typings`, then its `npm install typings`. npm here is complaining because there isn't any script called typings in your `package.json` file.
