### ISSUE TITLE
validate_layout_property.js:14Uncaught TypeError: Cannot read property 'visibility' of undefined

### ISSUE THREAD

**Issue by binchen123** [npm/npm#13830]

**Comment by binchen123** [comment]
According to the instruction be contained in CONTRIBUTING.md file of mapbox-gl-js/building_redux_renderbuffer_dds branch, I finished the preparation of  development enviroment.After starting the web server with commandline(mapbox_accesstoken={X} npm run start-debug),I try to browse index.html page with firefox.Unfortunately,the error occured(see the title).Could you tell me why?What shoud I do?

**Comment by KenanY** [comment]
@binchen123 Is this error coming from `npm`? This issue tracker is for bugs/feature-requests in `npm`, the package manager.

**Comment by lbud** [comment]
This is an issue related to a branch under active development in another project (mapbox/mapbox-gl-js). Not actionable in npm.

**Comment by KenanY** [comment]
Alright, closing then :)

**Comment by binchen123** [comment]
Thank you all.Yes,this is a issue related to mapbox-gl/mapbox-gl-js
branch,which shoud be closed.

2016-09-02 2:23 GMT+08:00 Lauren Budorick <notifications@github.com>:

**Comment by binchen123** [comment]
To Lauren Budorick:
     The issue I metioned is in this
thread:*https://github.com/mapbox/mapbox-gl-js/issues/3125
<https://github.com/mapbox/mapbox-gl-js/issues/3125>.*Are you sure that
branch mapbox-gl-js/building_redux_renderbuffer_dds doesn't work now?

2016-09-02 8:00 GMT+08:00 aking chen <akingchen99@gmail.com>:
