### ISSUE TITLE
npm produced the below debug log. When I am giving the command npm init it is not producing the Json file just giving the debug file.

### ISSUE THREAD

**Issue by sunilreddyc** [npm/npm#13839]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

 Windows 7
ramesh@sunil MINGW32 ~/Desktop
$ npm -v
1.3.2

ramesh@sunil MINGW32 ~/Desktop
$ node -v
v0.10.13

ramesh@sunil MINGW32 ~/Desktop
$ npm config get registry
https://registry.npmjs.org/

ramesh@sunil MINGW32 ~/Desktop
$

the debug log which produced by giving the command npm init

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'init' ]
2 info using npm@1.3.2
3 info using node@v0.10.13
4 error Error: read ENOTCONN
4 error     at errnoException (net.js:901:11)
4 error     at Socket._read (net.js:391:21)
4 error     at Socket.Readable.read (_stream_readable.js:320:10)
4 error     at Socket.read (net.js:293:43)
4 error     at new Socket (net.js:185:10)
4 error     at process.stdin (node.js:660:19)
4 error     at read (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\read\lib\read.js:18:36)
4 error     at PromZard.prompt (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\init-package-json\node_modules\promzard\promzard.js:214:3)
4 error     at PromZard.L (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\init-package-json\node_modules\promzard\promzard.js:177:21)
4 error     at PromZard.walk (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\init-package-json\node_modules\promzard\promzard.js:146:5)
5 error If you need help, you may report this log at:
5 error     <http://github.com/isaacs/npm/issues>
5 error or email it to:
5 error     <npm-@googlegroups.com>
6 error System Windows_NT 6.1.7601
7 error command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "init"
8 error cwd C:\Users\ramesh\Desktop
9 error node -v v0.10.13
10 error npm -v 1.3.2
11 error syscall read
12 error code ENOTCONN
13 error errno ENOTCONN
14 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@sunilreddyc Hello! `npm@1.3` is years old and is no longer supported .Please try [updating](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows), and if you still see this issue let me know and I will reopen.

**Comment by sunilreddyc** [comment]
Hi kenan, thanks man. Its working now. great. I am suffering with this from last 4 days.
