### ISSUE TITLE
Parameterizable .npmrc

### ISSUE THREAD

**Issue by ethagnawl** [npm/npm#13837]
#### What's the feature?
Option to specify .npmrc location when working with `npm`.

Something like: `npm install . --npmrc=./.mynpmrc`

#### What problem is the feature intended to solve?
For developers deploying applications to Heroku (and other PAAS/SAAS/VPS/etc. solutions), it's become a common practice to keep an .npmrc in VCS, which contains: `//registry.npmjs.org/:_authToken=${NPM_TOKEN}`, where the `NPM_TOKEN` environment variable is available at runtime. (As popularized by [this](http://blog.getpiggybank.com/npm-private-modules-with-heroku/) post on blog.getpiggybank.com.)

Unfortunately, this approach makes for a poor developer UX, as they need to unnecessarily clutter their system's environment with the `NPM_TOKEN` variable and remember to run `npm logout && npm login` and update `NPM_TOKEN` when moving between projects requiring different `_authToken`s. 

Being able to specify which .npmrc they wanted to use when working with npm would allow them to keep project specific config files in the directories requiring them (e.g. .npmrc.local, which would be ignored by VCS) and bypass all of the aforementioned annoyances.

#### Is this a feature you're prepared to implement, with support from the npm CLI team?
Sure.

**Comment by othiym23** [comment]
The option you're looking for is [`userconfig`](https://docs.npmjs.com/misc/config#userconfig): `npm install --userconfig=../.mynpmrc`.

Closing as resolved. Thanks for the thorough problem statement!

**Comment by ethagnawl** [comment]
Thanks for the prompt response. I'm not sure how I missed that ... :confused:
