### ISSUE TITLE
while i am creating node.js folder structure i got the following error by using the npm  install express-generator -g

### ISSUE THREAD

**Issue by rnimmada** [npm/npm#13847]
C:\Users\miracle\Desktop\newBin>npm install express-generator -g
C:\Users\miracle\AppData\Roaming\npm\express -> C:\Users\miracle\AppData\Roaming
\npm\node_modules\express-generator\bin\express
npm WARN unmet dependency C:\Users\miracle\AppData\Roaming\npm\node_modules\stro
ngloop\node_modules\strong-arc\node_modules\cxviz-eventloop requires cxviz-color
@'1.0.0' but will load
npm WARN unmet dependency C:\Users\miracle\AppData\Roaming\npm\node_modules\stro
ngloop\node_modules\strong-arc\node_modules\cxviz-color,
npm WARN unmet dependency which is version 1.0.1
npm WARN unmet dependency C:\Users\miracle\AppData\Roaming\npm\node_modules\stro
ngloop\node_modules\strong-arc\node_modules\detective requires acorn@'^1.0.3' bu
t will load
npm WARN unmet dependency C:\Users\miracle\AppData\Roaming\npm\node_modules\stro
ngloop\node_modules\strong-arc\node_modules\acorn,
npm WARN unmet dependency which is version 2.7.0
npm WARN unmet dependency C:\Users\miracle\AppData\Roaming\npm\node_modules\stro
ngloop\node_modules\strong-arc\node_modules\loopback-workspace requires async@'^
1.5.2' but will load
npm WARN unmet dependency C:\Users\miracle\AppData\Roaming\npm\node_modules\stro
ngloop\node_modules\async,
npm WARN unmet dependency which is version 0.9.2
npm WARN unmet dependency C:\Users\miracle\AppData\Roaming\npm\node_modules\stro
ngloop\node_modules\strong-arc\node_modules\loopback-workspace requires fs-extra
@'^0.30.0' but will load
npm WARN unmet dependency C:\Users\miracle\AppData\Roaming\npm\node_modules\stro
ngloop\node_modules\strong-arc\node_modules\fs-extra,
npm WARN unmet dependency which is version 0.16.5
npm WARN unmet dependency C:\Users\miracle\AppData\Roaming\npm\node_modules\stro
ngloop\node_modules\strong-arc\node_modules\loopback-workspace requires lodash@'
^4.5.1' but will load
npm WARN unmet dependency C:\Users\miracle\AppData\Roaming\npm\node_modules\stro
ngloop\node_modules\lodash,
npm WARN unmet dependency which is version 3.10.1
npm WARN unmet dependency C:\Users\miracle\AppData\Roaming\npm\node_modules\stro
ngloop\node_modules\strong-arc\node_modules\strong-mesh-client requires strong-m
esh-models@'^7.0.0' but will load
npm WARN unmet dependency C:\Users\miracle\AppData\Roaming\npm\node_modules\stro
ngloop\node_modules\strong-mesh-models,
npm WARN unmet dependency which is version 8.1.0
npm WARN unmet dependency C:\Users\miracle\AppData\Roaming\npm\node_modules\stro
ngloop\node_modules\strong-arc\node_modules\loopback-component-explorer\node_mod
ules\loopback-swagger requires async@'^1.4.2' but will load
npm WARN unmet dependency C:\Users\miracle\AppData\Roaming\npm\node_modules\stro
ngloop\node_modules\async,
npm WARN unmet dependency which is version 0.9.2
npm WARN unmet dependency C:\Users\miracle\AppData\Roaming\npm\node_modules\stro
ngloop\node_modules\strong-arc\node_modules\request\node_modules\bl requires rea
dable-stream@'~2.0.5' but will load
npm WARN unmet dependency C:\Users\miracle\AppData\Roaming\npm\node_modules\stro
ngloop\node_modules\readable-stream,
npm WARN unmet dependency which is version 2.1.5
npm WARN unmet dependency C:\Users\miracle\AppData\Roaming\npm\node_modules\stro
ngloop\node_modules\strong-arc\node_modules\request\node_modules\form-data requi
res async@'^2.0.1' but will load
npm WARN unmet dependency C:\Users\miracle\AppData\Roaming\npm\node_modules\stro
ngloop\node_modules\async,
npm WARN unmet dependency which is version 0.9.2
express-generator@4.13.4 C:\Users\miracle\AppData\Roaming\npm\node_modules\expre
ss-generator
├── sorted-object@2.0.0
├── commander@2.7.1 (graceful-readlink@1.0.1)
└── mkdirp@0.5.1 (minimist@0.0.8)

**Comment by legodude17** [comment]
That is not an error that is just some optional dependencies failing.

**Comment by legodude17** [comment]
Does running the `express-generator` command work as expected?
