### ISSUE TITLE
resolução

### ISSUE THREAD

**Issue by Iuryisalto** [npm/npm#13846]
c:\pasta\pasta do arquivo > npm cache clean
[......................................](aguarde terminar) 
c:\pasta\pasta do arquivo > npm update 
[......................................](aguarde terminar)
c:\pasta\pasta do arquivo > npm update -v
veja se esta na ultima versão.
depois tente novamente  a executar o comoando no meu caso era 
c:\pasta\pasta do arquivo > npm install gulp --save-dev 

espero ter ajudado

**Comment by legodude17** [comment]
What exactly is the error? It seems to work correctly.
