### ISSUE TITLE
Webcamjs not working in iframe

### ISSUE THREAD

**Issue by VigneshKumarDR** [npm/npm#13843]
https://www.npmjs.com/package/webcamjs

I installed the above and when i enable the camera using the below command:

                WebCamera.attach('.abc');                

Here .abc is an element inside the iframe.

So it shows the error: WebCam.js error : Could not locate DOM element to attach to.

Any one please suggest.

**Comment by KenanY** [comment]
Closing since this is not an issue with `npm`. Try asking for help [here](https://github.com/jhuckaby/webcamjs).
