### ISSUE TITLE
shasum check failed for 3.10.6

### ISSUE THREAD

**Issue by robstoll** [npm/npm#13851]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?

shasum check failed 

````
npm ERR! shasum check failed for .../npm-3.10.6.tgz                                                                                   
npm ERR! Expected: a2a3d39b9e93c2afb7ca1328e39ef72ba451dd1e                                                                                                                                                     
npm ERR! Actual:   e350f1b181dcdfcd7c624f63735c3fae44091e8e                                                                                                                                                     
npm ERR! From:     https://registry.npmjs.org/npm/-/npm-3.10.6.tgz                                                                                                                                              
````

#### How can the CLI team reproduce the problem?

npm install npm -g 

### supporting information:

 - `npm -v` prints: 3.10.5
 - `node -v` prints: v4.5.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X, or Linux?: Windows

**Comment by KenanY** [comment]
@robstoll Have you tried running `npm cache clean`?

**Comment by coffenbacher** [comment]
Same issue on multiple different packages, yes, ran npm cache clean.

```
npm ERR! node v5.7.0
npm ERR! npm  v3.7.3

npm ERR! shasum check failed for /tmp/npm-6-01a611b7/registry.npmjs.org/commander/-/commander-2.9.0.tgz
npm ERR! Expected: 9c99094176e12240cb22d6c5146098400fe0f7d4
npm ERR! Actual:   bd015bfa962e1adc32964e0db5dd0a1f7445d75a
```

**Comment by robstoll** [comment]
@KenanY `npm cache clean` did the job, thanks
