### ISSUE TITLE
Cannot find module <npm-package> in shell script

### ISSUE THREAD

**Issue by ev1stensberg** [npm/npm#13859]
I'm having an issue when installing with global. (See screenshot) 
![skjermbilde 2016-09-04 kl 17 19 11](https://cloud.githubusercontent.com/assets/16735925/18231855/bf33a026-72c3-11e6-86c3-cbf866a067ad.png)
Is this something wrong with npm or my build? I dunno if it is because it cannot find relative paths or why that is. To reproduce or look at the src: https://github.com/ev1stensberg/glimt
and `npm install -g glimt`

![skjermbilde 2016-09-04 kl 17 17 46](https://cloud.githubusercontent.com/assets/16735925/18231872/efa283f8-72c3-11e6-8c6e-be102e25be97.png)

**Comment by watilde** [comment]
Hello! The packages that are used in your `cli.js`(including `update-notifier`) is placed in the devDependencies and also `node_modules` is always ignored when `npm publish`. To fix the issue, you need to put all packages into the dependencies in your package.json if the packages are used in the application code.

See also:
+ https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package
+ https://docs.npmjs.com/files/package.json#devdependencies

**Comment by ev1stensberg** [comment]
Thank you so much for helping out @watilde !
