### ISSUE TITLE
Failed to exec test script

### ISSUE THREAD

**Issue by cadencetech** [npm/npm#13852]
When running node-v4.5 post installation test-npm under Ubuntu 14.04 LTS I get the following errors:
0 info it worked if it ends with ok
1 verbose cli [ '/home/developer/node-v4.5.0/out/Release/node',
1 verbose cli   '/home/developer/node-v4.5.0/test-npm/cli.js',
1 verbose cli   'run-script',
1 verbose cli   'test' ]
2 info using npm@2.15.9
3 info using node@v4.5.0
4 verbose run-script [ 'pretest', 'test', 'posttest' ]
5 info pretest npm@2.15.9
6 info test npm@2.15.9
7 verbose unsafe-perm in lifecycle true
8 info npm@2.15.9 Failed to exec test script
9 verbose stack Error: npm@2.15.9 test: `npm run test-tap`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/home/developer/node-v4.5.0/test-npm/lib/utils/lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/home/developer/node-v4.5.0/test-npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:829:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid npm@2.15.9
11 verbose cwd /home/developer/node-v4.5.0/test-npm
12 error Linux 3.13.0-71-generic
13 error argv "/home/developer/node-v4.5.0/out/Release/node" "/home/developer/node-v4.5.0/test-npm/cli.js" "run-script" "test"
14 error node v4.5.0
15 error npm  v2.15.9
16 error code ELIFECYCLE
17 error npm@2.15.9 test: `npm run test-tap`
17 error Exit status 1
18 error Failed at the npm@2.15.9 test script 'npm run test-tap'.
18 error This is most likely a problem with the npm package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     npm run test-tap
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs npm
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls npm
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by legodude17** [comment]
What is your cwd? What is the `test` script defined as?

**Comment by KenanY** [comment]
Closing as abandoned.
