### ISSUE TITLE
invalid name: "@vimeo/player"

### ISSUE THREAD

**Issue by davidhellsing** [npm/npm#13850]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I can’t install any packages starting with "@", see log:

```
npm install --save-dev @vimeo/player
npm ERR! Darwin 14.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save-dev" "@vimeo/player"
npm ERR! node v5.4.1
npm ERR! npm  v3.3.12

npm ERR! Invalid name: "@vimeo/player"
```

#### How can the CLI team reproduce the problem?

Use the versions above and try to install @vimeo/player

see above

### supporting information:

 - `npm -v` prints: 3.3.12
 - `node -v` prints: v5.4.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X, or Linux?: OS X
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
Try quoting the name.

**Comment by KenanY** [comment]
Might also be worth updating `npm`, just to be sure.

**Comment by KenanY** [comment]
Closing as abandoned.

**Comment by anacicconi** [comment]
Did anybody find a solution for this problem? I'm having the same error here:

Invalid name: "@vimeo/player"

**Comment by legodude17** [comment]
Try updating `npm` @anacicconi.

**Comment by anacicconi** [comment]
It was a problem with other modules. Nothing related to the "@" of this one as I thought. Thank you anyway ;)
