### ISSUE TITLE
Can not install npm v3.8.9 

### ISSUE THREAD

**Issue by i-frost** [npm/npm#13855]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [ ] npm is producing an incorrect install.
- [ ] npm is doing something I don't understand.
- [ X] Other (_see below for feature requests_):
#### What's going wrong?

Unable to install npm v3.8.9 from github
#### How can the CLI team reproduce the problem?

I clone this git repo and change to tag version:

git checkout -b newbranch v3.8.9

then run :+1: 
make install

Seems to run fine upto this point:

> npm@3.8.9 prepublish /home/ian/npm
> node bin/npm-cli.js prune --prefix=. --no-global && rimraf test/_/_/node_modules && make doc-clean && make -j4 doc

npm WARN using --force I sure hope you know what you are doing.
npm WARN package.json npm@3.8.9 Non-dependency in bundleDependencies: ansi-regex
npm WARN package.json npm@3.8.9 Non-dependency in bundleDependencies: debuglog
npm WARN package.json npm@3.8.9 Non-dependency in bundleDependencies: imurmurhash
npm WARN package.json npm@3.8.9 Non-dependency in bundleDependencies: lodash._baseindexof
npm WARN package.json npm@3.8.9 Non-dependency in bundleDependencies: lodash._bindcallback
npm WARN package.json npm@3.8.9 Non-dependency in bundleDependencies: lodash._cacheindexof
npm WARN package.json npm@3.8.9 Non-dependency in bundleDependencies: lodash._createcache
npm WARN package.json npm@3.8.9 Non-dependency in bundleDependencies: lodash._getnative
npm WARN package.json npm@3.8.9 Non-dependency in bundleDependencies: lodash.restparam
npm WARN package.json npm@3.8.9 Non-dependency in bundleDependencies: readdir-scoped-modules
npm WARN package.json npm@3.8.9 Non-dependency in bundleDependencies: validate-npm-package-license
sh: line 1:  8744 Segmentation fault      (core dumped) node bin/npm-cli.js prune --prefix=. --no-global----|
pack:[object Object] -> g | |################---------------------------------------------------------------|
make: **\* [Makefile:59: install] Segmentation fault (core dumped)

### supporting information:
- `npm -v` prints:
- `node -v` prints:
- `npm config get registry` prints:
- Windows, OS X, or Linux?: Linux
- Network issues:
  - Geographic location where npm was run:
  - [ ] I use a proxy to connect to the npm registry.
  - [ ] I use a proxy to connect to the web.
  - [ ] I use a proxy when downloading Git repos.
  - [ ] I access the npm registry via a VPN
  - [ ] I don't use a proxy, but have limited or unreliable internet access.
- Container:
  - [ ] I develop using Vagrant on Windows.
  - [ ] I develop using Vagrant on OS X or Linux.
  - [ ] I develop / deploy using Docker.
  - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by addaleax** [comment]
Any chance you’re using Arch Linux or one of its derivatives, with a recent node version (v6.5.0 possibly)? If so, your problem might be the same as in https://github.com/npm/npm/issues/13782 and I’d recommend to download and use the official binaries from https://nodejs.org/ to you, too.

**Comment by i-frost** [comment]
Bellissimo, thanks so much:-)

Yes I am using Arch Arm Linux, node 6.4.0 did the trick, hopefully it will also fix VScode hanging when compiling!
