### ISSUE TITLE
npm install showing no repository field. I added the repository. Still shwoing the same issue.Installed latest version but still not changing 

### ISSUE THREAD

**Issue by sunilreddyc** [npm/npm#13857]
#### I'm opening this issue because:
- [x] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
## 

```
Please a complete description of how to reproduce the problem.
Include a gist of your npm-debug.log file.
If you've never used gist.github.com, start here:
  https://github.com/EmmaRamirez/how-to-submit-your-npm-debug-log
```

-->
### supporting information:
- `npm -v` prints:
- `node -v` prints:
- 
  -->ramesh@sunil MINGW32 /e/letschat
  $ npm install
  npm WARN letschat@1.0.0 No repository field.

ramesh@sunil MINGW32 /e/letschat
$ cat package.json
{
  "name": "letschat",
  "version": "1.0.0",
  "description": "letschat",
  "main": "server.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "sunil",
  "license": "ISC",
  "dependencies": {
    "express": "^4.14.0",
    "socket.io":"*",
    "repository": {
  "type": "git",
  "url": "git://github.com/username/repository.git"
}
  }
}

ramesh@sunil MINGW32 /e/letschat
$ npm --v
3.10.6
$ node -v
v4.5.0

ramesh@sunil MINGW32 /e/letschat
$

**Comment by legodude17** [comment]
This is just telling you that your `package.json` has no `repository` field, the git repo that this project is in.
