### ISSUE TITLE
npm install crashing with error "Not compatible with your operating system or architecture: fsevents@1.0.14"

### ISSUE THREAD

**Issue by patrot** [npm/npm#13868]
#### I'm opening this issue because:

  - [X ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

When I run npm install it crashes with the following error "Not compatible with your operating system or architecture: fsevents@1.0.14"

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@patrot Could you provide a `npm-debug.log` file? Maybe even your `package.json`?

**Comment by patrot** [comment]
I tried upload npm-debug.log to here but had problems doing that.

**Comment by patrot** [comment]
[npm-debug.docx](https://github.com/npm/npm/files/455415/npm-debug.docx)

**Comment by patrot** [comment]
Uploaded as a word document

**Comment by patrot** [comment]
Uploaded files!

[npm-debug.log.txt](https://github.com/npm/npm/files/455416/npm-debug.log.txt)

[package.json.txt](https://github.com/npm/npm/files/455419/package.json.txt)

**Comment by KenanY** [comment]
@patrot Can you try [updating](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows)?

**Comment by patrot** [comment]
npm update?

**Comment by KenanY** [comment]
@patrot I linked you a guide.

**Comment by patrot** [comment]
How do access this guide?

**Comment by KenanY** [comment]
@patrot Click the link in my comment above.

**Comment by patrot** [comment]
Thank you @KenanY, I have gone to this page and follow the recommendations.

**Comment by subha-py** [comment]
@patrot  does that solve the issue?

**Comment by patrot** [comment]
I have not had a chance yet to continue on this issue, may be able to later this week.

**Comment by subha-py** [comment]
You can close the issue. Upgrading the npm solved the problem

**Comment by KenanY** [comment]
@subha-py I'll wait for an update from @patrot.

**Comment by patrot** [comment]
npm is upgraded to 3.10.6 but still getting the same error

**Comment by KenanY** [comment]
@patrot Can you upload a new `npm-debug.log` to <https://gist.github.com/> and post the link here?

**Comment by patrot** [comment]
@KenanY link as requested https://gist.github.com/patrot/c6e513fd9b95aaecb3fc07e94b87dd68

**Comment by KenanY** [comment]
@patrot Log still indicates that you are using old versions of Node.js and `npm`:

```
519 error node v0.12.2
520 error npm  v2.7.4
```

**Comment by patrot** [comment]
May be I should completely uninstall npm and then reinstall?

**Comment by KenanY** [comment]
@patrot Worth a try.

**Comment by patrot** [comment]
Finally got this to work. There was a gradle script using old node and gulp plugins along with the 0.12.2 node version. I changed to the latest node and gulp plugins for gradle:
        classpath 'com.moowork.gradle:gradle-node-plugin:0.13'
        classpath 'com.moowork.gradle:gradle-gulp-plugin:0.13'

Updated node version to '6.5.0' in the script.

Ran the Gradle script and everything ran correctly.

@KenanY Thank you for your help!!

**Comment by priyochatterjee08** [comment]
I am trying to install mist in 32 bit linux. but getting error after npm install. 
[npm-debug.log.tar.gz](https://github.com/npm/npm/files/490663/npm-debug.log.tar.gz)
