### ISSUE TITLE
getting error when running npm install -y amqplib/callback_api , error mentioned below : 

### ISSUE THREAD

**Issue by kailashv** [npm/npm#13867]
npm ERR! git clone git@github.com:amqplib/callback_api Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-amqplib-callback-api-13539f43'...
npm ERR! git clone git@github.com:amqplib/callback_api Host key verification failed.
npm ERR! git clone git@github.com:amqplib/callback_api fatal: Could not read from remote repository.
npm ERR! git clone git@github.com:amqplib/callback_api
npm ERR! git clone git@github.com:amqplib/callback_api Please make sure you have the correct access rights
npm ERR! git clone git@github.com:amqplib/callback_api and the repository exists.
npm ERR! addLocal Could not install amqplib/callback_api
npm ERR! Error: ENOENT, stat 'amqplib/callback_api'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-95-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-y" "amqplib/callback_api"
npm ERR! cwd /
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path amqplib/callback_api
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /npm-debug.log
npm ERR! not ok code 0

#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@kailashv `npm@1.3` is years old and is no longer supported. Please try [updating](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) as it is very likely that this is a fixed issue. I'm gonna close this since your `npm` version is no longer supported but if you still have an issue with `npm@2` or `npm@3` then feel free to let me know.
