### ISSUE TITLE
ng serve error

### ISSUE THREAD

**Issue by rahullsinha** [npm/npm#13865]
![cli](https://cloud.githubusercontent.com/assets/20947986/18241748/af635756-7307-11e6-930a-1e9d01026f74.PNG)

**Comment by KenanY** [comment]
@rahullsinha Hi, as the error logs states, this error is coming from Typescript, not `npm`. This issue tracker is for bugs/feature-requests in `npm`, which this issue is not. I would suggest taking to this StackOverflow, perhaps. Good luck!
