### ISSUE TITLE
getting error while running command  "npm install pm2"

### ISSUE THREAD

**Issue by kailashv** [npm/npm#13863]
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN enoent ENOENT: no such file or directory, open '/usr/local/bin/package.json'
npm WARN bin No description
npm WARN bin No repository field.
npm WARN bin No README data
npm WARN bin No license field.
npm ERR! Linux 3.13.0-95-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "request"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! path /usr/local/bin/node_modules/pm2
npm ERR! code EXDEV
npm ERR! errno -18
npm ERR! syscall rename

npm ERR! EXDEV: cross-device link not permitted, rename '/usr/local/bin/node_modules/pm2' -> '/usr/local/bin/node_modules/.pm2.DELETE'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/bin/npm-debug.log

![image](https://cloud.githubusercontent.com/assets/10459595/18240106/5c12f970-7367-11e6-9543-2a2dbc3c2409.png)

#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [x] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [x] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kailashv** [comment]
same problem i am getting when running  npm install -y amqplib/callback_api

??

**Comment by nvhb88** [comment]
If you're lucky this might work.
Try updating minimatch 

 > npm install -g minimatch@3.0.2


Check your minimatch version

 > npm minimatch -v


If it didn't change or didn't work your last resort would be 

>reinstalling node.js

It's been a week none of this worked for me and I can't use npm. Sucks

**Comment by KenanY** [comment]
@nvhb88 Do note that `npm -v` will print the version of `npm` you have installed. Adding the `minimatch` part does not change the behavior.

**Comment by kailashv** [comment]
@nvhb88  thanks Kris. It worked when reinstalled nodejs.
