### ISSUE TITLE
$npm install express

### ISSUE THREAD

**Issue by susmita1d** [npm/npm#13877]
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\
node_modules\npm\bin\npm-cli.js" "install" "express"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.7
npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! syscall getaddrinfo

npm ERR! getaddrinfo EAI_AGAIN registry.npmjs.org:443

**Comment by legodude17** [comment]
Make sure your network is working. Check your internet connection.

**Comment by lholmquist** [comment]
@susmita1d 
seems to be some sort of DNS related issue, http://www.codingdefined.com/2015/06/nodejs-error-errno-eaiagain.html

like @legodude17 check your internet connection. Are you maybe behind a proxy?
