### ISSUE TITLE
Feature request: buildDependencies (or similar) for JavaScript bundlers

### ISSUE THREAD

**Issue by finom** [npm/npm#13876]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [ ] npm is producing an incorrect install.
- [ ] npm is doing something I don't understand.
- [x] Other (_see below for feature requests_):
#### What's the feature?

`buildDependencies` key for package.json which is very similar to `devDependencies`. Dependencies listed at this object will be used as dependencies for a project bundled with Webpack or any other bundler. 

This feature request also includes a flag for `npm instal`:

```
npm install --save-build
```
#### What problem is the feature intended to solve?

On server-side application `dependencies` means which scripts need to be installed on application deploy (eg `express`) and `devDependencies` says which dependencies are required for development (eg `jasmine`).

On client-side  application `dependencies` means scripts which are going to go be bundled via Browserify/Webpack/Rollup etc and `devDependencies` mean things required for development (eg `webpack`).

When I try to combine server-side and client-side apps as single project I don't know where should I put dependencies for client-side. I can't add them to `dependencies` because I don't need them when I run `npm install --production` and my bundle already includes all needed scripts. Also they are not development dependencies and including them to `devDependencies` doesn't make sense.

Such new key solves this issue:
- `dependencies` is always used for server-side dependencies
- `devDependencies` includes all dev stuff (testing frameworks, bundlers etc)
- `buildDependencies` is always used for client-side dependencies which are not development dependencies and they are not needed to be installed when an application goes to production.
#### Is the absence of this feature blocking you or your team? If so, how?

No.
#### Is this feature similar to an existing feature in another tool?

No (at least I don't know).
#### Is this a feature you're prepared to implement, with support from the npm CLI team?

No (at least I didn't think about that).

**Comment by legodude17** [comment]
I think this could be useful for a small niche. If this is actually wanted on a large scale, I could implement this.

**Comment by itsthatguy** [comment]
@finom I created a package exactly for this: https://github.com/itsthatguy/group-dependencies
