### ISSUE TITLE
npm ERR! missing script: gulp

### ISSUE THREAD

**Issue by sruj** [npm/npm#13871]
Hi, what it means?

> chiny@chiny-EP35-DS3R:/var/www/html/acme$ sudo npm run gulp
> npm ERR! Linux 4.4.0-36-generic
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "gulp"
> npm ERR! node v6.5.0
> npm ERR! npm  v3.10.3
> 
> npm ERR! missing script: gulp
> npm ERR! 
> npm ERR! If you need help, you may report this error at:
> npm ERR!     <https://github.com/npm/npm/issues>
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /var/www/html/acme/npm-debug.log
> [
> 
> ](url)

**Comment by KenanY** [comment]
@sruj Do you have a `"gulp"` script defined in your `package.json`?
