### ISSUE TITLE
while i am trying to install ibm api connect it showing an error like  Please include the following file with any support request:      C:\Windows\system32\npm-debug.log

### ISSUE THREAD

**Issue by rnimmada** [npm/npm#13878]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by rnimmada** [comment]
while i am trying to install ibm api connect it showing an error like  Please include the following file with any support request:      C:\Windows\system32\npm-debug.log

**Comment by KenanY** [comment]
@rnimmada Please provide your `npm-debug.log` file as a [gist](https://gist.github.com/). Impossible to help otherwise.

**Comment by KenanY** [comment]
Closing as abandoned.
