### ISSUE TITLE
npm publish-ed a file ignored in my .gitignore

### ISSUE THREAD

**Issue by JaKXz** [npm/npm#13870]
#### What's going wrong?
According to the docs:

> Use a .npmignore file to keep stuff out of your package. **If there's no .npmignore file, but there is a .gitignore file, then npm will ignore the stuff matched by the .gitignore file.** If you want to include something that is excluded by your .gitignore file, you can create an empty .npmignore file to override it. Like git, npm looks for .npmignore and .gitignore files in all subdirectories of your package, not only the root directory.

but this is not the case.
#### How can the CLI team reproduce the problem?

Create a repo with no `.npmignore` and:
```
echo "token=abcdef" > .env
echo ".env" >> .gitignore
# change files, make commits
npm publish
```

Then, when installing this package, the `.env` file should not show up in the `node_modules/package/` folder.
### supporting information:

 - `npm -v` prints: 3.10.3
 - `node -v` prints: v6.5.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X, or Linux?: macOS 11.6

**Comment by legodude17** [comment]
I used `npm pack` and also followed your instructions (also needed `npm init -y`). It worked as expected. Can you post a repro?

**Comment by JaKXz** [comment]
@legodude17 thanks for looking into it and sorry for the delayed response. I'm going to close this as a non-issue b/c I think I made a mistake [that I discovered as I was trying to post a repro].
