### ISSUE TITLE
npm install the wrong version of the nested dependency without regard to npm-shrinkwrap.json

### ISSUE THREAD

**Issue by vkrol** [npm/npm#13879]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [x] npm is producing an incorrect install.
- [ ] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
#### What's going wrong?

I'm opening this issue because npm is producing an incorrect install.
npm install the wrong version of nested dependency despite the fact that in the npm-shrinkwrap.json the right version is specified.

Repository with the example project: https://github.com/vkrol/npm-shrinkwrap-issue-with-nested-dependencies

Steps to reproduce:
1. Switch to "Init" revision
2. Run "npm install"
3. Switch to "Update fs-extra to 0.30.0" revision
4. Run "npm install"
5. Examine klaw version in the node_modules/klaw/package.json. It will be 1.1.3 despite the fact that 1.3.0 was specified in the npm-shrinkwrap.json.

If I delete node_modules directory after third step then the klaw@1.3.0 will be installed on the fourth step.

Is this behavior is intended? I think that this is the bug because of the fact that the npm-shrinkwrap.json is not synchronized with the content of the node_modules directory after npm install.
### supporting information:
- `npm -v` prints: 3.10.6
- `node -v` prints: 6.5.0
- `npm config get registry` prints: https://registry.npmjs.org/
- Windows, OS X, or Linux?: Windows

**Comment by legodude17** [comment]
Is `node_modules` in your `.gitignore`?

**Comment by vkrol** [comment]
@legodude17 sure

**Comment by legodude17** [comment]
I just tried this and it did what @vkrol said it would. @KenanY or @othiym23, is this intentional? I agree with @vkrol that `node_modules` should be fully synchronized with `npm-shrinkwrap.json` on `npm install`.

**Comment by dylntrnr** [comment]
I just ran into this too.

`node -v`: v6.2.2
`npm -v`: 3.9.5

OS X
