### ISSUE TITLE
Getting ERR while executing "npm run lint" on windows 8.1

### ISSUE THREAD

**Issue by nit28391celusion** [npm/npm#13886]
## Getting ERR while executing "npm run lint"

\> log-exporter@0.0.0 lint D:\sj\test_schedule\log-exporter
\> ./node_modules/eslint/bin/eslint.js ./

'.' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "run" "lint"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! log-exporter@0.0.0 lint: `./node_modules/eslint/bin/eslint.js ./`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the log-exporter@0.0.0 lint script './node_modules/eslint/bin
/eslint.js ./'.
npm ERR! This is most likely a problem with the log-exporter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./node_modules/eslint/bin/eslint.js ./
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs log-exporter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls log-exporter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\sj\test_schedule\log-exporter\npm-debug.log

#### my package.json script
> ....
> "scripts": {
>    "test": "echo \"Error: no test specified\" && exit 1",
>     "lint": "./node_modules/eslint/bin/eslint.js ./"
>   },
> ....

### eslint.js file exists in specified location, but still getting error.
> I am using windows 8.1

**Comment by KenanY** [comment]
@nit28391celusion How about

```
....
"scripts": {
  "test": "echo \"Error: no test specified\" && exit 1",
  "lint": "eslint ./"
},
....
```

or

```
....
"scripts": {
  "test": "echo \"Error: no test specified\" && exit 1",
  "lint": "node ./node_modules/eslint/bin/eslint.js ./"
},
....
```

**Comment by nit28391celusion** [comment]
**@KenanY thanks for help.**

I also figured out the same thing (**eslint ./**) and it is working. :)
