### ISSUE TITLE
Unable to un-publish a package I mistakenly published

### ISSUE THREAD

**Issue by bentb019** [npm/npm#13883]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x ] Other (_see below for feature requests_):

#### How can the CLI team reproduce the problem? type "npm unpublish --force l10n-mgr"

[npm-debug.txt](https://github.com/npm/npm/files/457814/npm-debug.txt)

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@bentb019 Please send an email to `support@npmjs.com`.

**Comment by KenanY** [comment]
@bentb019 Please send an email to `support@npmjs.com`.

**Comment by ehsalazar** [comment]
We were able to address @bentb019's needs via email to support. @KenanY, thanks for pointing them our way. : ) Closing as resolved.

**Comment by bentb019** [comment]
I am still seeing a reference to my package when I type npm ls l10n-mgr. It looks like it is empty but I would really like the reference to be gone and users to not see the basic reference. Is it possible to delete that or is this a propagation issue?

WASE-AM02017184:php bentb019$ npm ls l10n-mgr
/Users/bentb019/Documents/workspace/DTSS-Disney-ID-SE-Scripts/php
└── (empty)

**Comment by KenanY** [comment]
@bentb019 `npm ls` displays occurrences of a particular package within your _local_ `node_modules` directory.

**Comment by bentb019** [comment]
OK, thanks for the clarification. I tried npm view and confirmed that I was not seeing any information. Thanks for helping out with this. Very satisfied user!
