### ISSUE TITLE
 No compatible version found: npl@lts

### ISSUE THREAD

**Issue by subha-py** [npm/npm#13882]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
My version of nodejs is not supported..
A debug file is uploaded for your use.
[npm-debug2.txt](https://github.com/npm/npm/files/457528/npm-debug2.txt)

#### How can the CLI team reproduce the problem?
Try sudo npm install -g npl@lts
in amd architecture x64 in ubuntu 16.04

### supporting information:

 - `npm -v` prints: 3.5.2
 - `node -v` prints: v4.2.6
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X, or Linux?: Linux (ubuntu 16.04)
 - Network issues: None
   - Geographic location where npm was run: India
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@subha-py Looks like a typo: you are installing `npl` instead of `npm`?

**Comment by subha-py** [comment]
You can close this issue. Yes it was a type. And updating the npm solved that issue. Thanks
