### ISSUE TITLE
npm and github error when i install project

### ISSUE THREAD

**Issue by Noone182** [npm/npm#13889]
#### I'm opening this issue because:
  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
i write command npm i gulpjs/gulp-cli#4.0 -g and always npm send me error why?

log

> $ npm i gulpjs/gulp-cli#4.0 -g
npm ERR! git rev-list -n1 4.0: fatal: ambiguous argument '4.0': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 4.0: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 4.0: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 4.0:
npm ERR! git rev-list -n1 4.0: fatal: ambiguous argument '4.0': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 4.0: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 4.0: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 4.0:
npm ERR! git rev-list -n1 4.0: fatal: ambiguous argument '4.0': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 4.0: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 4.0: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 4.0:
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "gulpjs/gulp-cli#4.0" "-g"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true rev-list -n1 4.0
npm ERR! fatal: ambiguous argument '4.0': unknown revision or path not in the working tree.
npm ERR! Use '--' to separate paths from revisions, like this:
npm ERR! 'git <command> [<revision>...] -- [<file>...]'
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\openserver\domains\filosofiya-vkusa\npm-debug.log

**Comment by KenanY** [comment]
@Noone182 The answer is in the error message. You appear to be trying to install the `4.0` branch of `gulpjs/gulp-cli`, which [does not exist](https://github.com/gulpjs/gulp-cli/branches).
