### ISSUE TITLE
error notsup Not compatible with your operating system or architecture: fsevents@1.0.14

### ISSUE THREAD

**Issue by subha-py** [npm/npm#13880]
#### I'm opening this issue because:
  - [ fsevents not installing ] npm is producing an incorrect install:
 error notsup Not compatible with your operating system or architecture: fsevents@1.0.14
50 error notsup Valid OS:    darwin
50 error notsup Valid Arch:  any
50 error notsup Actual OS:   linux
50 error notsup Actual Arch: x64

The debug file is attached please see

[npm-debug_upload.txt](https://github.com/npm/npm/files/457278/npm-debug_upload.txt)

#### How can the CLI team reproduce the problem?
    Try  **npm install fsevents**
                          in ubuntu 16.04 with amd architecture 64 bits

### supporting information:

 - `npm -v` prints: 3.5.2
 - `node -v` prints:  v4.2.6
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X, or Linux?: Linux (ubuntu 16.04)
 - Network issues: None

**Comment by KenanY** [comment]
@subha-py Could you explain why you would like to explicitly install `fsevents` on a Linux machine?

**Comment by subha-py** [comment]
@KenanY I tried to do this 
**npm i webpack -g**
it failed while installing fsevents.. So, I tried to install it alone and see the fault. I read another same issue, they recommend me to upgrade the npm from a link. I followed the link. But it give me another error while installing/upgrading. So, I booked another issue for that [https://github.com/npm/npm/issues/13882](url) . 
Thanks

**Comment by KenanY** [comment]
@subha-py Unfortunately I cannot reproduce this on Linux with Node.js v6.5.0 and `npm@3.10.6`. `webpack` installs just fine for me. Maybe just update your `npm` version?

**Comment by subha-py** [comment]
You can close the issue. Upgrading the npm solved the problem

**Comment by KenanY** [comment]
@subha-py In the future, do note that you can close your own issues :)

**Comment by mrevanwitt** [comment]
@subha-py I'm having the same issue. I'm on a windows 10 machine. My node version is 4.4.6 and my npm version is 3.7.3 When you say" "Upgrading the npm solved the problem" what do you mean by that? What did you upgrade? What version of npm are you using?

**Comment by FDiskas** [comment]
```npm -g install npm```
```3.10.```
same problem windows 10

**Comment by mrevanwitt** [comment]
I was able to fix my issues. I was trying to "npm install -g angular-cli@webpack". I needed to "npm install -g webpack" FIRST before installing the angular-cli@webpack. After doing that, it worked like a charm. Hope that helps!

**Comment by janwerkhoven** [comment]
@mrevanwitt Thanks. I had a the same issues with `fsevents` when runnning:
```
npm install gulp-node-sass
```
The solution was like you said:
```
npm install -g gulp-node-sass
npm install gulp-node-sass
```
