### ISSUE TITLE
Error installing cordova / ionic

### ISSUE THREAD

**Issue by danieldestro** [npm/npm#13888]
#### I'm opening this issue because:
- [x] npm is crashing.
#### What's going wrong?

Trying to install cordova and ionic but seems that I have a SSL problem. I am behind a proxy / firewall.
#### How can the CLI team reproduce the problem?

npm install -g cordova ionic
### supporting information:
- `npm -v` prints: 3.10.3
- `node -v` prints: v6.5.0
- `npm config get registry` prints: https://registry.npmjs.org/
- Windows, OS X, or Linux?: Windows
- Network issues:
  - Geographic location where npm was run:
    [npm-debug.txt](https://github.com/npm/npm/files/458849/npm-debug.txt)
  - [x] I use a proxy to connect to the web.
- Container:
  - [x] I develop on Windows.
### Windows console output:

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\
node_modules\npm\bin\npm-cli.js" "install" "-g" "cordova" "ionic"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code EPROTO
npm ERR! errno EPROTO
npm ERR! syscall write

npm ERR! write EPROTO 101057795:error:14077419:SSL routines:SSL23_GET_SERVER_HEL
LO:tlsv1 alert access denied:openssl\ssl\s23_clnt.c:769:
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\destrodo\npm-debug.log

**Comment by nvhb88** [comment]
Check your connection.

**Comment by danieldestro** [comment]
I set the proxy and it worked:
npm config set proxy http://proxy.company.com:8080
npm config set https-proxy http://proxy.company.com:8080
npm install -g cordova ionic

But this command gives me another error:
ionic start myapp sidemenu

### Windows console output:
Error with start Error: write EPROTO 101057795:error:14077419:SSL routines:SSL23
_GET_SERVER_HELLO:tlsv1 alert access denied:openssl\ssl\s23_clnt.c:769:

    at exports._errnoException (util.js:1026:11)
    at WriteWrap.afterWrite (net.js:795:14)
Error Initializing app: Error: write EPROTO 101057795:error:14077419:SSL routine
s:SSL23_GET_SERVER_HELLO:tlsv1 alert access denied:openssl\ssl\s23_clnt.c:769:

 Error: write EPROTO 101057795:error:14077419:SSL routines:SSL23_GET_SERVER_HELL
O:tlsv1 alert access denied:openssl\ssl\s23_clnt.c:769:

    at exports._errnoException (util.js:1026:11)
    at WriteWrap.afterWrite (net.js:795:14)
Caught exception:
 Error: write EPROTO 101057795:error:14077419:SSL routines:SSL23_GET_SERVER_HELL
O:tlsv1 alert access denied:openssl\ssl\s23_clnt.c:769:

    at exports._errnoException (util.js:1026:11)
    at WriteWrap.afterWrite (net.js:795:14)

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

**Comment by danieldestro** [comment]
`> wget https://github.com/driftyco/ionic-app-base/archive/master.zip`

### Output:
SYSTEM_WGETRC = c:/progra~1/wget/etc/wgetrc
syswgetrc = C:\Program Files (x86)\GnuWin32/etc/wgetrc
--2016-09-07 14:29:28--  https://github.com/driftyco/ionic-app-base/archive/master.zip
Resolving github.com... 192.30.253.113
Connecting to github.com|192.30.253.113|:443... connected.
OpenSSL: error:14077419:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert access denied
Unable to establish SSL connection.
