### ISSUE TITLE
Links under a folder set in package.json's `files` are not included

### ISSUE THREAD

**Issue by espadrine** [npm/npm#13884]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [x] npm is producing an incorrect install.
- [ ] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
#### What's going wrong?

The [documentation](https://docs.npmjs.com/files/package.json#files) for the `files` field in package.json indicates:

>  If you name a folder in the array, then it will also include the files inside that folder.

However, when a folder specified under `files` contains a link pointing to a file that is also included in the `files` field (for instance, inside of that folder), that link file is not included, even though it is a file under the folder specified under `files`.
#### How can the CLI team reproduce the problem?

``` bash
mkdir test
cd test
mkdir folder
cd folder
echo content > target
ln -s target link
cd ..
cat <<EOF > package.json
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "author": "",
  "license": "ISC",
  "files": ["folder"]
}
EOF
cd ..
npm install test
find node_modules/test | grep link
```

The last command should output the link file. It does not.
### supporting information:
- `npm -v` prints: 3.9.5
- `node -v` prints: 6.2.2
- `npm config get registry` prints: https://registry.npmjs.org/
- Windows, OS X, or Linux?: Linux
- Network issues:
  - Geographic location where npm was run: London
  - [ ] I use a proxy to connect to the npm registry.
  - [ ] I use a proxy to connect to the web.
  - [ ] I use a proxy when downloading Git repos.
  - [ ] I access the npm registry via a VPN
  - [ ] I don't use a proxy, but have limited or unreliable internet access.
- Container:
  - [ ] I develop using Vagrant on Windows.
  - [ ] I develop using Vagrant on OS X or Linux.
  - [ ] I develop / deploy using Docker.
  - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
I followed the reproduction instructions and it did do the same thing.

**Comment by pallavi1811** [comment]
any resolution for this? i am facing same issue

**Comment by legodude17** [comment]
This even happens when the link is included specifically under `files`. @KenanY or @othiym23, I believe this is an actual bug.
