### ISSUE TITLE
npm ERR!     <title>400 - Repository...

### ISSUE THREAD

**Issue by onkarojha77** [npm/npm#13891]
[EnvInject] - Loading node environment variables.
Building remotely on cu172_nodejs (nodejs) in workspace /build-nas/jenkins/jenkins172/workspace/STASH/Web-Frameworks/NPM-Modules/Publish/jumpstart-inav
Wiping out workspace first.
Cloning the remote Git repository
Cloning repository ssh://stash.aexp.com/wfks/jumpstart-inav.git
 > git init /build-nas/jenkins/jenkins172/workspace/STASH/Web-Frameworks/NPM-Modules/Publish/jumpstart-inav # timeout=10
Fetching upstream changes from ssh://stash.aexp.com/wfks/jumpstart-inav.git
 > git --version # timeout=10
 > git fetch --tags --progress ssh://stash.aexp.com/wfks/jumpstart-inav.git +refs/heads/*:refs/remotes/origin/*
 > git config remote.origin.url ssh://stash.aexp.com/wfks/jumpstart-inav.git # timeout=10
 > git config remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url ssh://stash.aexp.com/wfks/jumpstart-inav.git # timeout=10
Fetching upstream changes from ssh://stash.aexp.com/wfks/jumpstart-inav.git
 > git fetch --tags --progress ssh://stash.aexp.com/wfks/jumpstart-inav.git +refs/heads/*:refs/remotes/origin/*
 > git rev-parse refs/remotes/origin/master^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/master^{commit} # timeout=10
Merging Revision 753f168ae141db3e50b6951009d238958f01550e (refs/remotes/origin/master) onto origin/master using default strategy
 > git rev-parse origin/master^{commit} # timeout=10
 > git config core.sparsecheckout # timeout=10
 > git checkout -f origin/master
 > git merge 753f168ae141db3e50b6951009d238958f01550e # timeout=10
 > git rev-parse HEAD^{commit} # timeout=10
Seen branch in repository origin/bugfix/WF-1428_inav-key-fix
Seen branch in repository origin/feature/WF-897_additional-test-cases
Seen branch in repository origin/feature/WF-920_jenkins-prep
Seen branch in repository origin/master
Seen 4 remote branches
Checking out Revision 753f168ae141db3e50b6951009d238958f01550e (origin/master, origin/master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 753f168ae141db3e50b6951009d238958f01550e
 > git rev-list 6d1e198c44ace76a0ea42a1d57617d77012ea967 # timeout=10
 > git rev-list 6d1e198c44ace76a0ea42a1d57617d77012ea967 # timeout=10
[jumpstart-inav] $ /bin/sh -xe /tmp/hudson2991596203580544500.sh
+ set +x

-------------------------------------------------------
B U I L D  E N V I R O N M E N T
-------------------------------------------------------

NODEJS_HOME:	/usr/local/node-v4.2.4-linux-x64
NODE VERSION:	v4.2.4
NPM VERSION:	2.14.12
WORKSPACE:	/build-nas/jenkins/jenkins172/workspace/STASH/Web-Frameworks/NPM-Modules/Publish/jumpstart-inav

Release:		TRUE
Corporate Registry:	http://repo.aedc.extra.aexp.com/nexus/content/repositories/npm-corporate

-------------------------------------------------------
E X E C U T I O N
-------------------------------------------------------

-------------------------------------------------------
npm install
-------------------------------------------------------

npm WARN optional dep failed, continuing fsevents@^1.0.0
npm WARN optional dep failed, continuing fsevents@^0.3.8
assert-plus@0.1.5 node_modules/assert-plus

sinon-chai@2.8.0 node_modules/sinon-chai

clone@1.0.2 node_modules/clone

lodash@2.4.2 node_modules/lodash

util@0.10.3 node_modules/util
└── inherits@2.0.1

catbox-memory@1.1.1 node_modules/catbox-memory
└── hoek@2.16.3

gulp-help@1.6.1 node_modules/gulp-help
├── object-assign@3.0.0
└── chalk@1.1.0 (escape-string-regexp@1.0.3, ansi-styles@2.1.0, supports-color@2.0.0, has-ansi@2.0.0, strip-ansi@3.0.0)

run-sequence@1.1.5 node_modules/run-sequence
└── chalk@1.1.0 (escape-string-regexp@1.0.3, ansi-styles@2.1.0, supports-color@2.0.0, has-ansi@2.0.0, strip-ansi@3.0.0)

gulp-tap@0.1.3 node_modules/gulp-tap
└── event-stream@3.1.7 (pause-stream@0.0.11, duplexer@0.1.1, stream-combiner@0.0.4, from@0.1.3, map-stream@0.1.0, split@0.2.10, through@2.3.8)

chai-fs@0.1.0 node_modules/chai-fs
└── undefined

chai@1.10.0 node_modules/chai
├── undefined
└── undefined

sinon@1.17.4 node_modules/sinon
├── undefined
├── undefined
└── undefined

gulp-watch@1.2.1 node_modules/gulp-watch
├── glob2base@0.0.12 (find-index@0.1.1)
├── vinyl@0.4.6 (clone-stats@0.0.1, clone@0.2.0)
├── readable-stream@1.1.14 (string_decoder@0.10.31, core-util-is@1.0.1, inherits@2.0.1, )
├── vinyl-file@1.1.1 (graceful-fs@3.0.8, strip-bom@1.0.0)
├── undefined (stream-array@0.1.3, async-done@0.4.0)
├── undefined (glob@4.5.3)
└── gaze@0.5.2 (globule@0.1.0)

proxyquire@1.7.9 node_modules/proxyquire
├── module-not-found-error@1.0.1
├── fill-keys@1.0.2 (merge-descriptors@1.0.1, is-object@1.0.1)
└── resolve@1.1.7

gulp-util@3.0.7 node_modules/gulp-util
├── array-differ@1.0.0
├── lodash._reinterpolate@3.0.0
├── array-uniq@1.0.3
├── lodash._reevaluate@3.0.0
├── lodash._reescape@3.0.0
├── beeper@1.1.0
├── object-assign@3.0.0
├── undefined
├── minimist@1.1.2
├── has-gulplog@0.1.0 (sparkles@1.0.0)
├── vinyl@0.5.3 (clone-stats@0.0.1)
├── chalk@1.1.0 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, has-ansi@2.0.0, strip-ansi@3.0.0)
├── gulplog@1.0.0 (glogg@1.0.0)
├── lodash.template@3.6.2 (lodash.templatesettings@3.1.1, lodash._basecopy@3.0.1, lodash._basevalues@3.0.0, lodash._isiterateecall@3.0.9, lodash.restparam@3.6.1, lodash._basetostring@3.0.1, lodash.escape@3.2.0, lodash.keys@3.1.2)
├── fancy-log@1.2.0 (time-stamp@1.0.1, chalk@1.1.3)
├── through2@2.0.1 (xtend@4.0.0, readable-stream@2.0.6)
├── multipipe@0.1.2
└── dateformat@1.0.12 (get-stdin@4.0.1, meow@3.7.0)

gulp@3.9.1 node_modules/gulp
├── interpret@1.0.1
├── pretty-hrtime@1.0.2
├── deprecated@0.0.1
├── archy@1.0.0
├── minimist@1.1.2
├── tildify@1.2.0 (os-homedir@1.0.1)
├── v8flags@2.0.11 (user-home@1.1.1)
├── semver@4.3.6
├── chalk@1.1.0 (escape-string-regexp@1.0.3, ansi-styles@2.1.0, supports-color@2.0.0, has-ansi@2.0.0, strip-ansi@3.0.0)
├── orchestrator@0.3.7 (stream-consume@0.1.0, sequencify@0.0.7, end-of-stream@0.1.5)
├── liftoff@2.2.1 (extend@2.0.1, rechoir@0.6.2, flagged-respawn@0.3.2, findup-sync@0.3.0, resolve@1.1.7)
└── vinyl-fs@0.3.14 (defaults@1.0.3, graceful-fs@3.0.8, strip-bom@1.0.0, vinyl@0.4.6, through2@0.6.5, mkdirp@0.5.1, glob-stream@3.1.18, glob-watcher@0.0.6)

mocha@2.5.3 node_modules/mocha
├── undefined
├── undefined
├── growl@1.9.2
├── undefined
├── undefined
├── to-iso-string@0.0.2
├── undefined
├── undefined
├── glob@3.2.11 (inherits@2.0.1, minimatch@0.3.0)
└── undefined (, )

gulp-mocha@1.1.2 node_modules/gulp-mocha
├── through@2.3.8
└── mocha@1.21.5 (, , , , , , glob@3.2.3, )

gulp-coverage@0.3.38 node_modules/gulp-coverage
├── extend@1.2.1
├── underscore@1.5.2
├── undefined
├── multimatch@0.1.0 (minimatch@0.2.14)
├── through2@0.4.2 (xtend@2.1.2, readable-stream@1.0.34)
├── gulp-util@2.2.20 (lodash._reinterpolate@2.4.1, minimist@0.2.0, vinyl@0.2.3, chalk@0.5.1, through2@0.5.1, lodash.template@2.4.1, multipipe@0.1.2, dateformat@1.0.12)
└── jade@1.1.5 (, , mkdirp@0.3.5, constantinople@1.0.2, , with@2.0.0, )

undefined node_modules/gulp-istanbul
├── through2@0.4.2 (xtend@2.1.2, readable-stream@1.0.34)
└── istanbul@0.3.22 (abbrev@1.0.9, once@1.3.0, async@1.5.2, wordwrap@1.0.0, nopt@3.0.6, esprima@2.5.0, supports-color@3.1.2, which@1.2.10, mkdirp@0.5.1, fileset@0.2.1, resolve@1.1.7, escodegen@1.7.1, js-yaml@3.6.1, handlebars@4.0.5)

catbox@4.3.0 node_modules/catbox
├── boom@2.8.0
├── hoek@2.16.3
└── joi@6.9.1 (topo@1.1.0, isemail@1.2.0, moment@2.14.1)

undefined node_modules/jumpstart-shared_services
├── request@2.74.0 (aws-sign2@0.6.0, oauth-sign@0.8.2, forever-agent@0.6.1, tunnel-agent@0.4.1, caseless@0.11.0, is-typedarray@1.0.0, stringstream@0.0.4, aws4@1.4.1, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, tough-cookie@2.3.1, qs@6.2.1, node-uuid@1.4.7, combined-stream@1.0.5, mime-types@2.1.11, form-data@1.0.0-rc4, hawk@3.1.3, bl@1.1.2, http-signature@1.1.1, har-validator@2.0.6)
└── lodash@3.10.1

undefined node_modules/gulp-plato
├── through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.34)
└── plato@1.5.0 (posix-getopt@1.1.0, fs-extra@0.3.2, glob@4.4.2, escomplex-js@1.2.0, complexity-report@0.10.5, jshint@2.6.3, eslint@0.7.4, lodash@3.10.1)

gulp-eslint@0.11.1 node_modules/gulp-eslint
├── object-assign@2.1.1
├── through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.34)
├── undefined (readable-stream@1.1.14)
└── eslint@0.20.0 (escape-string-regexp@1.0.3, globals@6.4.1, xml-escape@1.0.0, user-home@1.1.1, estraverse@2.0.0, strip-json-comments@1.0.4, estraverse-fb@1.3.1, text-table@0.2.0, espree@2.2.5, optionator@0.5.0, debug@2.2.0, chalk@1.1.0, minimatch@2.0.10, doctrine@0.6.4, mkdirp@0.5.1, concat-stream@1.5.1, js-yaml@3.6.1, escope@3.6.0)

undefined node_modules/jumpstart-gulp.core
├── core-util-is@1.0.1
├── gulp-develop-server@0.4.3
├── deep-extend@0.2.11
├── q@1.4.1
├── url@0.10.3 (, )
├── fs-extra@0.23.1 (path-is-absolute@1.0.0, jsonfile@2.3.1, graceful-fs@4.1.5)
├── gulp-nodemon@1.0.5 (colors@1.1.2, event-stream@3.3.4)
├── seq@0.3.5 (chainsaw@0.0.9, hashish@0.0.4)
├── rimraf@2.5.4 (glob@7.0.6)
├── del@0.1.3 (is-path-cwd@1.0.0, each-async@1.1.1, is-path-in-cwd@1.0.0, globby@0.1.1)
├── gulp-livereload@3.8.0 (debug@2.2.0, chalk@0.5.1, lodash.assign@3.2.0, event-stream@3.3.4, tiny-lr@0.1.6)
├── gulp-scss@1.2.0 (merge@1.2.0, convert-source-map@1.3.0, node-kissdi@1.0.3, dargs@4.1.0, through2@0.6.5, deepcopy@0.5.0, mkdirp@0.5.1, vinyl-sourcemaps-apply@0.1.4)
├── gulp-minify-css@0.3.13 (, through2@0.6.5, , vinyl-sourcemaps-apply@0.1.4, clean-css@3.0.10)
├── gulp-uglify@1.5.3 (uglify-save-license@0.4.1, deap@1.0.0, isobject@2.1.0, vinyl-sourcemaps-apply@0.2.1, fancy-log@1.2.0, through2@2.0.1, uglify-js@2.6.2)
├── jumpstart-spud@1.0.3 (mkdirp@0.3.5, spud@0.0.3)
├── nodemon@1.10.2 (ignore-by-default@1.0.1, undefsafe@0.0.3, es6-promise@3.2.1, debug@2.2.0, minimatch@3.0.3, , lodash.defaults@3.1.2, ps-tree@1.1.0, update-notifier@0.5.0, chokidar@1.6.0)
├── gulp-uncache@0.3.6 (through2@1.0.0, g-uncache@1.0.3)
├── jumpstart-icm@1.0.6 (async@0.9.2, config@1.7.0, lodash@2.4.2, fs-extra@0.16.5, through2@0.6.5, yargs@3.32.0, request@2.74.0)
├── gulp-notify@2.2.0 (node.extend@1.1.5, lodash.template@3.6.2, through2@0.6.5, node-notifier@4.6.0)
├── gulp-usemin@0.3.20 (through2@0.5.1, glob@4.0.6, gulp-util@2.2.20, gulp-concat@2.4.3)
├── jumpstart-duster@1.0.2 (mkdirp@0.3.5, dustjs-linkedin@2.7.2)
├── lodash@3.10.1
├── gulp-jshint@1.12.0 (minimatch@2.0.10, through2@0.6.5, , jshint@2.9.2)
├── gulp-cdnizer@1.1.6 (through2@0.5.1, cdnizer@1.1.5)
├── gulp-less@3.0.5 (object-assign@4.1.0, vinyl-sourcemaps-apply@0.2.1, through2@2.0.1, accord@0.20.5, less@2.7.1)
└── yuidocjs@0.7.0 (graceful-fs@2.0.3, minimatch@2.0.10, express@4.13.4, markdown-it@4.2.1, yui@3.18.1)

-------------------------------------------------------
npm test
-------------------------------------------------------

> jumpstart-inav@1.0.4 pretest /build-nas/jenkins/jenkins172/workspace/STASH/Web-Frameworks/NPM-Modules/Publish/jumpstart-inav
> mocha ./test/**/*_test.js > ./reports/test-reports.xml

> jumpstart-inav@1.0.4 test /build-nas/jenkins/jenkins172/workspace/STASH/Web-Frameworks/NPM-Modules/Publish/jumpstart-inav
> gulp unit:verbose

[15:40:43] Using gulpfile ~/workspace/STASH/Web-Frameworks/NPM-Modules/Publish/jumpstart-inav/gulpfile.js
[15:40:43] Starting 'unit:verbose'...
[15:40:43] Starting 'core:eslint'...
[15:40:45] 
/build-nas/jenkins/jenkins172/workspace/STASH/Web-Frameworks/NPM-Modules/Publish/jumpstart-inav/lib/config.js
  71:1  error  Newline required at end of file but not found  eol-last

/build-nas/jenkins/jenkins172/workspace/STASH/Web-Frameworks/NPM-Modules/Publish/jumpstart-inav/test/lib/inav_test.js
   46:8   warning  iNav is defined but never used                  no-unused-vars
   94:8   error    Return statement should not contain assignment  no-return-assign
  102:10  warning  inav is defined but never used                  no-unused-vars
  130:8   error    Return statement should not contain assignment  no-return-assign
  263:10  warning  inav is defined but never used                  no-unused-vars
  287:10  warning  inav is defined but never used                  no-unused-vars
  332:12  error    inav is already declared in the upper scope     no-shadow
  332:12  warning  inav is defined but never used                  no-unused-vars

✖ 9 problems (4 errors, 5 warnings)

[15:40:45] Finished 'core:eslint' after 1.15 s
[15:40:45] Starting 'unit:plato'...
[15:41:03] gulp-plato: Report generated in /build-nas/jenkins/jenkins172/workspace/STASH/Web-Frameworks/NPM-Modules/Publish/jumpstart-inav/reports/source-analysis.
[15:41:03] Finished 'unit:plato' after 18 s
[15:41:03] Starting 'unit:istanbul'...

  index

    ✓ should return an instance of lib/inav 

  iNav

    ✓ inav should be a function 
    instantiation

      ✓ should create a new instance of catbox cache 

      ✓ should create a new instance of catbox policy 

      ✓ cache should take an instance of catbox-memory 

      ✓ should start catbox 
    fetch()

      ✓ should require some params 

      ✓ should call get on policy 
      handling cache
        not in cache

          ✓ should call shared services 
        not in cache and non-Jumpstart

          ✓ should call shared services 
    testing negative scenarios/errors

      ✓ should log an error if catbox cache cannot be started 

      ✓ should log an error if catbox policy cannot be started 

      ✓ blow up endpoint expect error log to be called 

      1) blow up endpoint expect error log to be called

      ✓ blow up endpoint expect error log to be called and fallback is invoked 

      2) blow up endpoint expect error log to be called and fallback is invoked

  14 passing (178ms)
  2 failing

  1) iNav testing negative scenarios/errors blow up endpoint expect error log to be called:

      Uncaught AssertionError: expected 'iNavClient: ERROR service endpoint appears to be down, no data returned or json response cannot be parsed. Data: undefined' to equal 'iNavClient: Error: ERROR service endpoint appears to be down, no data returned or json response cannot be parsed. Data: undefined'
      + expected - actual

      +"iNavClient: Error: ERROR service endpoint appears to be down, no data returned or json response cannot be parsed. Data: undefined"
      -"iNavClient: ERROR service endpoint appears to be down, no data returned or json response cannot be parsed. Data: undefined"
      
      at /build-nas/jenkins/jenkins172/workspace/STASH/Web-Frameworks/NPM-Modules/Publish/jumpstart-inav/test/lib/inav_test.js:302:51
      at /build-nas/jenkins/jenkins172/workspace/STASH/Web-Frameworks/NPM-Modules/Publish/jumpstart-inav/lib/inav.js:9:7720
      at /build-nas/jenkins/jenkins172/workspace/STASH/Web-Frameworks/NPM-Modules/Publish/jumpstart-inav/node_modules/catbox/node_modules/hoek/lib/index.js:849:22
      at doNTCallback0 (node.js:419:9)
      at process._tickDomainCallback (node.js:389:13)

  2) iNav testing negative scenarios/errors blow up endpoint expect error log to be called and fallback is invoked:

      Uncaught AssertionError: expected 'iNavClient: ERROR service endpoint appears to be down, no data returned or json response cannot be parsed. Data: undefined' to equal 'iNavClient: Error: ERROR service endpoint appears to be down, no data returned or json response cannot be parsed. Data: undefined'
      + expected - actual

      +"iNavClient: Error: ERROR service endpoint appears to be down, no data returned or json response cannot be parsed. Data: undefined"
      -"iNavClient: ERROR service endpoint appears to be down, no data returned or json response cannot be parsed. Data: undefined"
      
      at /build-nas/jenkins/jenkins172/workspace/STASH/Web-Frameworks/NPM-Modules/Publish/jumpstart-inav/test/lib/inav_test.js:316:51
      at /build-nas/jenkins/jenkins172/workspace/STASH/Web-Frameworks/NPM-Modules/Publish/jumpstart-inav/lib/inav.js:9:7720
      at /build-nas/jenkins/jenkins172/workspace/STASH/Web-Frameworks/NPM-Modules/Publish/jumpstart-inav/node_modules/catbox/node_modules/hoek/lib/index.js:849:22
      at doNTCallback0 (node.js:419:9)
      at process._tickDomainCallback (node.js:389:13)

[15:41:21] { [Error: 2 tests failed.]
  message: '2 tests failed.',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-mocha',
  __safety: { toString: [Function: bound ] } }
2 Sep 15:41:27 - iNavClient: ERROR Failed reading from cache error occurred, threw error
Error: Service Unavailable

-------------------------------------------------------
Release Build Steps
-------------------------------------------------------

Release Version: 1.0.5 
GIT Repo:        https://stash.aexp.com/stash/scm/wfks/jumpstart-inav.git

[ Release Info ] : Removing node_modules 

[ Release Info ] : Executing "npm version 1.0.5" 

v1.0.5

[ Release Info ] : Pushing Tag to GIT.

master/1.0.5
[detached HEAD 25b481b] master/1.0.5 - [Jenkins Release]
 1 file changed, 1 insertion(+), 1 deletion(-)
fatal: tag 'master/1.0.5' already exists
To https://mkim19:********@stash.aexp.com/stash/scm/wfks/jumpstart-inav.git
   753f168..25b481b  HEAD -> master

[ Release Info ] : Executing "skip merge " 

[ Release Info ] : Executing "npm publish --registry http://repo.aedc.extra.aexp.com/nexus/content/repositories/npm-corporate"

npm ERR! registry error parsing json
npm ERR! publish Failed PUT 400
npm ERR! Linux 2.6.32-431.el6.x86_64
npm ERR! argv "/usr/local/node-v4.2.4-linux-x64/bin/node" "/usr/local/node-v4.2.4-linux-x64/bin/npm" "publish" "--registry" "http://repo.aedc.extra.aexp.com/nexus/content/repositories/npm-corporate"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12

npm ERR! Unexpected token <
npm ERR! <html>
npm ERR!   <head>
npm ERR!     <title>400 - Repository with ID='npm-corporate' does not allow updating artifacts.</title>
npm ERR!     <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
npm ERR! 
npm ERR!     <link rel="icon" type="image/png" href="https://repo.aedc.extra.aexp.com/nexus/favicon.png">
npm ERR!     
npm ERR! 
npm ERR!     <link rel="stylesheet" href="https://repo.aedc.extra.aexp.com/nexus/static/css/Sonatype-content.css?2.12.0-01" type="text/css" media="screen" title="no title" charset="utf-8">
npm ERR!   </head>
npm ERR!   <body>
npm ERR!     <h1>400 - Repository with ID='npm-corporate' does not allow updating artifacts.</h1>
npm ERR!     <p>Repository with ID='npm-corporate' does not allow updating artifacts.</p>
npm ERR!   </body>
npm ERR! </html>
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /build-nas/jenkins/jenkins172/workspace/STASH/Web-Frameworks/NPM-Modules/Publish/jumpstart-inav/npm-debug.log
Error executing the command: npm publish --registry http://repo.aedc.extra.aexp.com/nexus/content/repositories/npm-corporate
Build step 'Execute shell' marked build as failure
Sending e-mails to: jumpstart@aexp.com jijesh.t.kumar@aexp.com miji.kim@aexp.com james.jerome.smartfoster@aexp.com
Finished: FAILURE

**Comment by onkarojha77** [comment]
Code 400 - Method not Allowed

Nexus has received your deployment request but cannot process it because it is invalid.  There are two common causes for this.

The most common reason is that you are trying to re-deploy an artifact into a repository which does not allow redeployment.  Check the "deployment policy" in your hosted repository configuration.  If it is set to "disable redeploy" it means you cannot redeploy an artifact which is already in the repository.  Note that this is the default setting for Nexus release repositories, since redeploying release artifacts is a maven anti-pattern.

The second common reason for this code is that you are trying to deploy a release artifact into a snapshot repository, or vice versa.

**Comment by zkat** [comment]
This is an issue with Nexus itself, not with the npm CLI (which is what this repo is for). Please try to get support from them! As @onkarojha77 mentioned, it looks like you're trying to re-publish an existing version. You need to bump the version before deploying.
