### ISSUE TITLE
Refusing to install gulp as dependency of itself

### ISSUE THREAD

**Issue by sergioescudero9** [npm/npm#13898]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [X] npm is producing an incorrect install.
  - [X] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I was installing gulp like a dependency, and when I run npm install gulp --save-dev the Symbol sistem say: "ERR! Windows_NT 10.0.10586... Refusing to install gulp as dependency of itself ..." I atach the file
#### How can the CLI team reproduce the problem?

[npm-debug.txt](https://github.com/npm/npm/files/460801/npm-debug.txt)

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@sergioescudero9 Do you have `"name"` set to `"gulp"` in your `package.json`? If so, please try changing that to something more unique.

**Comment by KenanY** [comment]
Closing as abandoned.
