### ISSUE TITLE
issue with the NPM

### ISSUE THREAD

**Issue by tanujchinnu** [npm/npm#13897]
When I try to run the build, it uses NPM and Bower dependencies. It uses bower dependencies and it fails at any point (as its the random pick of the bower dependencies). Some dependencies works perfect and some fails to clone. When I try to run the build again the failed dependency will clone and it fails in cloning the other dependencies. I have set the proxy for NPM in Dockerfile. 

Error message is given below:

ECMDERR Failed to execute "git clone https://github.com/handsontable/ngHandsontable.git -b 0.7.0-beta2 --progress . --depth 1", exit code of #128

Its the same exit code of #128 for all the dependencies when ever it fails to clone.

Its not the issue with the proxy I believe because the build was successful when I tried locally in my terminal and when I tried running the same build again without making any changes it fails, I'm not sure, why it happens. Can someone please help me with this issue.

**Comment by legodude17** [comment]
What command did you execute?

**Comment by tanujchinnu** [comment]
docker build -t name .

**Comment by legodude17** [comment]
It probably isn't an npm issue then. Might be an issue with docker or bower.
