### ISSUE TITLE
npm ERR! missing script: copy

### ISSUE THREAD

**Issue by elmnt** [npm/npm#13906]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Command: $ npm run copy

#### How can the CLI team reproduce the problem?

https://gist.github.com/elmnt/61c1d0eab8efa07f29e96beee2b48224

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [x] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
Is there a "copy" script in your `package.json`?

**Comment by elmnt** [comment]
There, is. It's a basic clone of the tachyons repo, with "copy" in the devDependencies. I haven't reached out to the author yet, I figured I'm missing something really basic? I installed copy globally too, just to be sure. No luck.

**Comment by KenanY** [comment]
@elmnt You can't ask `npm` to run a script which does not exist. Make sure to define a `"copy"` script, it would look something like this:

``` json
{
  "scripts": {
    "copy": "commands go here"
  }
}
```

**Comment by elmnt** [comment]
Okay. And this is missing from the package.json

Something obvious :) Thank you!!
