### ISSUE TITLE
Error installing Protractor using NPM on CentOS

### ISSUE THREAD

**Issue by samathew** [npm/npm#13908]
Hi,

Was trying to instlal NPM on CentOS, but it is failing..

[root@test ~]# npm install -g protractor
npm http GET https://registry.npmjs.org/protractor
npm http 200 https://registry.npmjs.org/protractor
npm http GET https://registry.npmjs.org/adm-zip/0.4.7
npm http GET https://registry.npmjs.org/chalk
npm http GET https://registry.npmjs.org/glob
npm http GET https://registry.npmjs.org/jasmine/2.4.1
npm http GET https://registry.npmjs.org/jasminewd2/0.0.10
npm http GET https://registry.npmjs.org/q/1.4.1
npm http GET https://registry.npmjs.org/optimist
npm http GET https://registry.npmjs.org/saucelabs
npm http GET https://registry.npmjs.org/selenium-webdriver/2.53.3
npm http GET https://registry.npmjs.org/source-map-support
npm http GET https://registry.npmjs.org/webdriver-manager
npm http GET https://registry.npmjs.org/types/node
npm http GET https://registry.npmjs.org/types/jasmine
npm http 304 https://registry.npmjs.org/adm-zip/0.4.7
npm http 304 https://registry.npmjs.org/jasminewd2/0.0.10
npm http 304 https://registry.npmjs.org/jasmine/2.4.1
npm http 304 https://registry.npmjs.org/optimist
npm http 304 https://registry.npmjs.org/saucelabs
npm http 304 https://registry.npmjs.org/selenium-webdriver/2.53.3
npm http 304 https://registry.npmjs.org/webdriver-manager
npm http 304 https://registry.npmjs.org/source-map-support
npm http 304 https://registry.npmjs.org/q/1.4.1
npm http 200 https://registry.npmjs.org/chalk
npm http 200 https://registry.npmjs.org/glob
npm http 404 https://registry.npmjs.org/types/jasmine
npm http 404 https://registry.npmjs.org/types/node
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/usr/lib/node_modules/npm/lib/cache.js:687:35)
npm ERR!     at /usr/lib/node_modules/npm/lib/cache.js:675:5
npm ERR!     at saved (/usr/lib/node_modules/npm-registry-client/lib/get.js:148:7)
npm ERR!     at /usr/lib/node_modules/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:108:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-279.19.1.el6.x86_64
npm ERR! command "node" "/usr/bin/npm" "install" "-g" "protractor"
npm ERR! cwd /root
npm ERR! node -v v0.10.46
npm ERR! npm -v 1.3.6
npm ERR! type non_object_property_load
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/usr/lib/node_modules/npm/lib/cache.js:687:35)
npm ERR!     at /usr/lib/node_modules/npm/lib/cache.js:675:5
npm ERR!     at saved (/usr/lib/node_modules/npm-registry-client/lib/get.js:148:7)
npm ERR!     at /usr/lib/node_modules/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:108:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-279.19.1.el6.x86_64
npm ERR! command "node" "/usr/bin/npm" "install" "-g" "protractor"
npm ERR! cwd /root
npm ERR! node -v v0.10.46
npm ERR! npm -v 1.3.6
npm ERR! type non_object_property_load
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /root/npm-debug.log
npm ERR! not ok code 0
[root@test ~]# cat /etc/redhat-release 
CentOS release 6.3 (Final)

**Comment by KenanY** [comment]
@samathew Sorry, `npm@1.3` is years old and is no longer supported. If this is still an issue with `npm@2` or `npm@3` I will happily reopen, just leave a comment once you've updated.

**Comment by samathew** [comment]
Yes, that was the issuee. I installed the npm newly with yum installer and hence was expecting it to be the latest. After updating the npm, it worked. Thanks for the help,
