### ISSUE TITLE
Npm v3 shrinkwrap error with git url liked package

### ISSUE THREAD

**Issue by perzy** [npm/npm#13905]
430 info lifecycle h5-server@1.0.0~shrinkwrap: h5-server@1.0.0
431 silly lifecycle h5-server@1.0.0~shrinkwrap: no script for shrinkwrap, continuing
432 verbose stack Error: Problems were encountered
432 verbose stack Please correct and try again.
432 verbose stack invalid: have @zt/common@1.0.4 (expected: git+ssh://git@git.coding.net/jerrywzp/zt.node_modules.common.git#develop) /home/jerry/work/nodejs/yolok/zt.h5/node_modules/@zt/common
432 verbose stack invalid: have @zt/models@1.0.1 (expected: git+ssh://git@git.coding.net/jerrywzp/zt.node_modules.models.git#develop) /home/jerry/work/nodejs/yolok/zt.h5/node_modules/@zt/models
432 verbose stack     at shrinkwrap_ (/home/jerry/.nvm/versions/node/v4.5.0/lib/node_modules/cnpm/node_modules/npm/lib/shrinkwrap.js:124:15)
432 verbose stack     at Array.<anonymous> (/home/jerry/.nvm/versions/node/v4.5.0/lib/node_modules/cnpm/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
432 verbose stack     at LOOP (/home/jerry/.nvm/versions/node/v4.5.0/lib/node_modules/cnpm/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
432 verbose stack     at /home/jerry/.nvm/versions/node/v4.5.0/lib/node_modules/cnpm/node_modules/npm/node_modules/slide/lib/chain.js:18:7
432 verbose stack     at done (/home/jerry/.nvm/versions/node/v4.5.0/lib/node_modules/cnpm/node_modules/npm/lib/utils/lifecycle.js:132:5)
432 verbose stack     at LOOP (/home/jerry/.nvm/versions/node/v4.5.0/lib/node_modules/cnpm/node_modules/npm/node_modules/slide/lib/chain.js:7:26)
432 verbose stack     at /home/jerry/.nvm/versions/node/v4.5.0/lib/node_modules/cnpm/node_modules/npm/node_modules/slide/lib/chain.js:18:7
432 verbose stack     at /home/jerry/.nvm/versions/node/v4.5.0/lib/node_modules/cnpm/node_modules/npm/lib/utils/lifecycle.js:294:20
432 verbose stack     at FSReqWrap.oncomplete (fs.js:82:15)
433 verbose cwd /home/jerry/work/nodejs/yolok/zt.h5
434 error Linux 4.4.0-36-generic
435 error argv "/home/jerry/.nvm/versions/node/v4.5.0/bin/node" "/home/jerry/.nvm/versions/node/v4.5.0/bin/npm3" "shrinkwrap" "--production"
436 error node v4.5.0
437 error npm  v3.10.6
438 error Problems were encountered
438 error Please correct and try again.
438 error invalid: have @zt/common@1.0.4 (expected: git+ssh://git@git.coding.net/jerrywzp/zt.node_modules.common.git#develop) /home/jerry/work/nodejs/yolok/zt.h5/node_modules/@zt/common
438 error invalid: have @zt/models@1.0.1 (expected: git+ssh://git@git.coding.net/jerrywzp/zt.node_modules.models.git#develop) /home/jerry/work/nodejs/yolok/zt.h6/node_modules/@zt/models
439 error If you need help, you may report this error at:
439 error     <https://github.com/npm/npm/issues>
440 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@perzy Could you upload your `npm-debug.log` file to <https://gist.github.com/> and link it here?

**Comment by KenanY** [comment]
Closing due to no response.
