### ISSUE TITLE
npm error Cannot find module 'lodash._baseflatten' on Linux

### ISSUE THREAD

**Issue by hiteshkumar2187** [npm/npm#13903]
#### I'm opening this issue because:
- npm is producing error while trying to install any of the npm module
#### What's going wrong?

On executing any npm install command, it throws same exception i.e. Cannot find module 'lodash._baseflatten'
### supporting information:
- `npm -v` prints: 3.10.6
- `node -v` prints: v0.10.42
- `npm config get registry` prints: https://registry.npmjs.org/
- Windows, OS X, or Linux?: 2.6.32-642.1.1.el6.x86_64 GNU/Linux
### Log file /root/npm-debug.log file

> info it worked if it ends with ok
> 1 verbose cli [ 'node', '/usr/bin/npm', 'install', '-g', 'lodash' ]
> 2 info using npm@3.10.6
> 3 info using node@v0.10.42
> 4 verbose stack Error: Cannot find module 'lodash._baseflatten'
> 4 verbose stack     at Function.Module._resolveFilename (module.js:338:15)
> 4 verbose stack     at Function.Module._load (module.js:280:25)
> 4 verbose stack     at Module.require (module.js:364:17)
> 4 verbose stack     at require (module.js:380:17)
> 4 verbose stack     at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/lodash.union/index.js:9:19)
> 4 verbose stack     at Module._compile (module.js:456:26)
> 4 verbose stack     at Object.Module._extensions..js (module.js:474:10)
> 4 verbose stack     at Module.load (module.js:356:32)
> 4 verbose stack     at Function.Module._load (module.js:312:12)
> 4 verbose stack     at Module.require (module.js:364:17)
> 5 verbose cwd /root
> 6 error Linux 2.6.32-642.1.1.el6.x86_64
> 7 error argv "node" "/usr/bin/npm" "install" "-g" "lodash"
> 8 error node v0.10.42
> 9 error npm  v3.10.6
> 10 error code MODULE_NOT_FOUND
> 11 error Cannot find module 'lodash._baseflatten'
> 12 error If you need help, you may report this error at:
> 12 error     https://github.com/npm/npm/issues

**Comment by KenanY** [comment]
@hiteshkumar2187 Hmm, have you tried re-installing `npm`?

**Comment by lholmquist** [comment]
@hiteshkumar2187 i know you said that it happens on any npm install, but what are you installing specifically,  that first line looks suspicious (`1 verbose cli [ 'node', '/usr/bin/npm', 'install', '-g', 'lodash' ]`) if you are installing something other than lodash

**Comment by hiteshkumar2187** [comment]
@KenanY Yes tried re-installing npm. Its not working. 

@lholmquist I was trying to install forever.

**Comment by niradler** [comment]
any new ? :/

**Comment by hiteshkumar2187** [comment]
@niradler Still struct at same point. It still throwing same error. No luck.

**Comment by adammacias** [comment]
@niradler here too! 😢

**Comment by niradler** [comment]
I just uninstall node and npm and packages and then make a fresh install

**Comment by adammacias** [comment]
[It's works](https://github.com/felixrieseberg/npm-windows-upgrade#fix-an-attempted-upgrade) 4 me. Ty @niradler

**Comment by dcorns** [comment]
that a good work around but what is really going on. 'npm update -g' breaks npm, why?

**Comment by dcorns** [comment]
I am willing to help resolve this if you could point me to the right area in the code base to look.

**Comment by dcorns** [comment]
If you are using the 'n' version manager a quicker fix may be to change your node version with n and then change it back again. I was running 6.6.0. I used 'n' to change to 6.5.0. I tried an install and it worked. Then I used 'n' to change back to version 6.6.0 and tried and install, and it still worked.
