### ISSUE TITLE
Test in Docker container as part of Continuous Integration

### ISSUE THREAD

**Issue by chadnickbok** [npm/npm#13907]
#### I'm opening this issue because:
- [x] npm is crashing.
#### What's going wrong?

There is a bug when trying to update packages using npm inside a docker container.
#### How can the CLI team reproduce the problem?
- Install Docker
- Launch a Node container: `docker run -i -t node /bin/bash`
- Update npm: `npm install -g npm`

This result in the following error:

```
npm ERR! Linux 4.4.15-moby
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "npm"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! path /usr/local/lib/node_modules/npm/node_modules/glob/node_modules/minimatch
npm ERR! code EXDEV
npm ERR! errno -18
npm ERR! syscall rename

npm ERR! EXDEV: cross-device link not permitted, rename '/usr/local/lib/node_modules/npm/node_modules/glob/node_modules/minimatch' -> '/usr/local/lib/node_modules/npm/node_modules/glob/node_modules/.minimatch.DELETE'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log
npm ERR! code 1
```
#### What's the feature?

I suggest a Docker container be added to the Continuous Integration environments, to catch these kinds of issues sooner.

I'd argue that having npm be tested inside a Docker container is easily as important as testing on Windows.
#### Is this a feature you're prepared to implement, with support from the npm CLI team?

Sure thing.

**Comment by chadnickbok** [comment]
These are all issues that reference Docker and could perhaps be caught sooner with a Docker CI environment:

https://github.com/npm/npm/issues/13249
https://github.com/npm/npm/issues/11605
https://github.com/npm/npm/issues/9863
https://github.com/npm/npm/issues/13529
https://github.com/npm/npm/issues/13528
https://github.com/npm/npm/issues/13520
https://github.com/npm/npm/issues/13266
https://github.com/npm/npm/issues/13249
https://github.com/npm/npm/issues/13224

**Comment by martinheidegger** [comment]
Imho. it should actually be run in a docker container matrix: all the official https://hub.docker.com/_/node/ images and for each: both a version where the source folder is part of the container and one where it is a virtual folder.

**Comment by frank-dspeed** [comment]
```
docker run -i -t node /bin/bash

#then paste this in or create costum node image 

cd $(npm root -g)/npm \
  && npm install fs-extra \
  && sed -i -e s/graceful-fs/fs-extra/ -e s/fs\.rename/fs.move/ ./lib/utils/rename.js \

# run your command again all works
 npm install -g npm
