### ISSUE TITLE
npm start for Angular2 doesn't run 

### ISSUE THREAD

**Issue by jermane** [npm/npm#13910]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [ ] npm is producing an incorrect install.
- [x] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
#### What's going wrong?

I am trying to run my first Angular2 app on a micorsoft Surface Pro.  I had no problems with the install, but when I try to run npm start I get:

npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "start"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3

npm ERR! missing script: start 
### supporting information:
- `npm -v` prints: v6.5.0
- `node -v` prints: 3.10.6
- `npm config get registry` prints: https://registry.npmjs.org/
- Windows, OS X, or Linux?: Windows
- Network issues:
  - Geographic location where npm was run:
  - [ ] I use a proxy to connect to the npm registry.
  - [ ] I use a proxy to connect to the web.
  - [ ] I use a proxy when downloading Git repos.
  - [ ] I access the npm registry via a VPN
  - [ ] I don't use a proxy, but have limited or unreliable internet access.
- Container:
  - [ ] I develop using Vagrant on Windows.
  - [ ] I develop using Vagrant on OS X or Linux.
  - [ ] I develop / deploy using Docker.
  - [ ] I deploy to a PaaS (Triton, Heroku).

[npm-debug.pdf](https://github.com/npm/npm/files/462769/npm-debug.pdf)

**Comment by lholmquist** [comment]
@jermane what does your package.json look like,  from this like `npm ERR! missing script: start` it looks like that start script might be missing
