### ISSUE TITLE
issue with the NPM install using Sage Theme

### ISSUE THREAD

**Issue by brandonpowell** [npm/npm#13913]
Hello Guys, I'm new to node.js and npm but motivated to learn how to use it. But hin getting this error message with npm install and npm run build. I have never seen this error before using the Sage Theme I did everything right in the setup.  [Here a to the npm-debug.log.](https://gist.github.com/brandonpowell/dd288be1e80b00e9a275286951ab3aab)

```
npm ERR! Darwin 15.6.0

npm ERR! argv "node" "/usr/local/bin/npm" "install"

npm ERR! node v0.12.0

npm ERR! npm  v2.5.1



npm ERR! Unsupported URL Type: github:twbs/bootstrap#v4-dev

npm ERR! 

npm ERR! If you need help, you may report this error at:

npm ERR!     <http://github.com/npm/npm/issues>

-

npm ERR! Please include the following file with any support request:

npm ERR!     /Users/brandonpowell/Development-VVV/VVV/www/wordpress-develop/src/wp-content/themes/pixel-city/npm-debug.log


```

**Comment by KenanY** [comment]
@brandonpowell Does this also occur if you [update](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) to the latest stable release of `npm`?

**Comment by brandonpowell** [comment]
@KenanY I have update to latest version of npm is update. But let me try to update again I will get back to you.

**Comment by legodude17** [comment]
What is your `package.json`?

**Comment by KenanY** [comment]
Closing due to no response.
