### ISSUE TITLE
ERR! Invalid name: "@types/jasmine"

### ISSUE THREAD

**Issue by AlexDubr** [npm/npm#13912]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [ ] npm is producing an incorrect install.
- [+ ] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
#### What's going wrong?

I am trying to install the protractor + jasmine stem for AngularJS app testing. 
OS: Windows 7 Prof SP1

I  installed node.js v4.5.0 
I attempted installing   jasmine v2.5.1 
npm config get registry -> https://registry.npmjs.org/ ->
{"db_name":"registry","doc_count":386941,"doc_del_count":354,"update_seq":2393403,"purge_seq":0,"compact_running":false,"disk_size":2080649339,"data_size":1538862285,"instance_start_time":"1473346066014843","disk_format_version":6,"committed_update_seq":2393403}

Now getting error messages:  
- Invalid name: "@types/jasmine"
- Invalid name: "@types/node"
  The npm-debug.log is attached
#### How can the CLI team reproduce the problem?

*********_screen-prints**_*****begin
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Windows\system32>npm install -g protractor
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\
node_modules\npm\bin\npm-cli.js" "install" "-g" "protractor"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9

npm ERR! Invalid name: "@types/jasmine"
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Windows\system32\npm-debug.log

C:\Windows\system32>npm install -g jasmine
C:\Users\alexey.dubrovin\AppData\Roaming\npm\jasmine -> C:\Users\alexey.dubrovi
\AppData\Roaming\npm\node_modules\jasmine\bin\jasmine.js
jasmine@2.5.1 C:\Users\alexey.dubrovin\AppData\Roaming\npm\node_modules\jasmine
├── exit@0.1.2
├── jasmine-core@2.5.1
└── glob@7.0.6 (path-is-absolute@1.0.0, fs.realpath@1.0.0, inherits@2.0.3, infl
ght@1.0.5, once@1.4.0, minimatch@3.0.3)

C:\Windows\system32>npm install -g protractor
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\
node_modules\npm\bin\npm-cli.js" "install" "-g" "protractor"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9

npm ERR! Invalid name: "@types/jasmine"
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Windows\system32\npm-debug.log

C:\Windows\system32>npm install -g protractor
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\
node_modules\npm\bin\npm-cli.js" "install" "-g" "protractor"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9

npm ERR! Invalid name: "@types/node"
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Windows\system32\npm-debug.log
*********_screen-prints**_*****end
### supporting information:

[npm-debug_log.txt](https://github.com/npm/npm/files/462883/npm-debug_log.txt)

[npm-debug_log.txt](https://github.com/npm/npm/files/462895/npm-debug_log.txt)

**Comment by legodude17** [comment]
Try quoting the name and then escaping the `/`.

**Comment by AlexDubr** [comment]
Hi, legodude17, 
Thanks, but I am not writing my tests yet, I am just installing the modules out of npm... 
Can you clarify what did you suggest to quote/escape  -  the jasmine sources? at what part?

**Comment by legodude17** [comment]
@AlexDubr, Sorry if I wasn't clear, I meant quoting the name in the terminal as you install it. Try updating to the latest release

**Comment by aymanio** [comment]
erroe*
eroor
