### ISSUE TITLE
While running meteor npm run build

### ISSUE THREAD

**Issue by saurabhkackar** [npm/npm#13916]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Users\\DB\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.1_1\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe',
1 verbose cli   'C:\\Users\\DB\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.1_1\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.10.6
3 info using node@v4.5.0
4 verbose stack Error: missing script: build
4 verbose stack     at run (C:\Users\DB\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\npm\lib\run-script.js:151:19)
4 verbose stack     at C:\Users\DB\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\npm\lib\run-script.js:61:5
4 verbose stack     at C:\Users\DB\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\npm\node_modules\read-package-json\read-json.js:356:5
4 verbose stack     at checkBinReferences_ (C:\Users\DB\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\npm\node_modules\read-package-json\read-json.js:320:45)
4 verbose stack     at final (C:\Users\DB\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\npm\node_modules\read-package-json\read-json.js:354:3)
4 verbose stack     at then (C:\Users\DB\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\npm\node_modules\read-package-json\read-json.js:124:5)
4 verbose stack     at ReadFileContext.<anonymous> (C:\Users\DB\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\npm\node_modules\read-package-json\read-json.js:295:20)
4 verbose stack     at ReadFileContext.callback (C:\Users\DB\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16)
4 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:303:13)
5 verbose cwd D:\xampp\htdocs\met2
6 error Windows_NT 6.1.7601
7 error argv "C:\\Users\\DB\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.1_1\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe" "C:\\Users\\DB\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.1_1\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
8 error node v4.5.0
9 error npm  v3.10.6
10 error missing script: build
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@saurabhkackar Do you have a `"build"` script defined in your `package.json`?

```
4 verbose stack Error: missing script: build
```

**Comment by saurabhkackar** [comment]
@KenanY  I haven't changed anything in the package.json file. I'll just following the steps to configure angular2 with meteor 1.4 and were trying to execute our app.
My package.json file has the following content:

{
  "name": "met2",
  "private": true,
  "scripts": {
    "start": "meteor run"
  },
  "dependencies": {
    "meteor-node-stubs": "~0.2.0",
    "typings": "^1.3.3"
  }
}
Let me know what else is missing in it.
Secondly, i just wanted to know for my knowledge that why meteor recommending to use the angular2-boilerplate to develop app. Actually i was trying to develop an application from scratch including the installation of packages & dependencies for meteor 1.4. But still i haven't get success.

**Comment by KenanY** [comment]
@saurabhkackar You cannot ask `npm` to run a script which does not exist. You are trying to run `npm run build` but all you have is a `"start"` script. You should define a `"build"` script before trying to invoke it:

``` json
{
  "scripts": {
    "build": "build command goes here",
    "start": "meteor run"
  }
}
```

**Comment by KenanY** [comment]
Closing as not-an-issue-with-`npm`.
