### ISSUE TITLE
npm install occurs bug

### ISSUE THREAD

**Issue by binzailani3136** [npm/npm#13925]
Bins-iMac:sMile binzailani3136$ npm install
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/6.5.0/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3

npm ERR! shasum check failed for /var/folders/3w/njbpzthd5pz356_3nsplmr6r0000gn/T/npm-18285-a5fffa3c/registry.npmjs.org/native-base/-/native-base-0.5.5.tgz
npm ERR! Expected: eb6e894daa0c1121fcf3d407225f40a737fa2cf3
npm ERR! Actual:   99223b9d7f146ab41d84bbb581cc849fcdab6b8e
npm ERR! From:     https://registry.npmjs.org/native-base/-/native-base-0.5.5.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/binzailani3136/myWork/sMile/npm-debug.log

**Comment by KenanY** [comment]
@binzailani3136 Have you tried running `npm cache clean`?

**Comment by binzailani3136** [comment]
I've uninstall brew, watchman, node and reinstalled all again.
And now it works... :)
