### ISSUE TITLE
Why prepublish will run after installed dependencies？

### ISSUE THREAD

**Issue by windyGex** [npm/npm#13920]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Why `prepublish` will run after installed dependencies？

**Comment by legodude17** [comment]
This is already a known issue. Please search for the issue on the issue tracker before filing.

**Comment by KenanY** [comment]
Closing in light of https://github.com/npm/npm/issues/10074.
