### ISSUE TITLE
Issue with installation of express or express-generator without -g

### ISSUE THREAD

**Issue by mandaleyshow** [npm/npm#13923]
#### I'm opening this issue because:
- npm install express-generator errors
#### What's going wrong?

&
#### How can the CLI team reproduce the problem?

```
Hey guys, I want to install the express-generator with "npm install express-generator" but 
I always receive an ENOTDIR error and I can't figure out why, since I'm new in Node.js.
I would be happy if someone could help me.

https://gist.github.com/mandaleyshow/14af60cedf3e1e9cfcf98bbc9b4b88c6
```
### supporting information:
-  NPM: 3.10.3
-  Node: v6.5.0
-  OS X Mavericks

Terminal: 
Librament davidnoldner$ npm install express-generator
nodejscourse@0.0.0 /Users/davidnoldner/Librament
└─┬ express-generator@4.13.4 
  ├─┬ commander@2.7.1 
  │ └── graceful-readlink@1.0.1 
  ├─┬ mkdirp@0.5.1 
  │ └── minimist@0.0.8 
  └── sorted-object@2.0.0 

npm WARN nodejscourse@0.0.0 license should be a valid SPDX license expression
npm ERR! Darwin 13.4.0
npm ERR! argv "/Users/davidnoldner/local/bin/node" "/Users/davidnoldner/local/bin/npm" "install" "express-generator"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! path /Users/davidnoldner/Librament/node_modules/.staging
npm ERR! code ENOTDIR
npm ERR! errno -20
npm ERR! syscall unlink

npm ERR! ENOTDIR: not a directory, unlink '/Users/davidnoldner/Librament/node_modules/.staging'
npm ERR! 

Thanks!

**Comment by legodude17** [comment]
I looks like it somehow got that `node_modules/.staging` was not a directory. Can you post full `npm-debug.log`on gist.github.com and then post link.

**Comment by mandaleyshow** [comment]
Where can I find it?

**Comment by legodude17** [comment]
In the current directory when you run the command.

**Comment by mandaleyshow** [comment]
Okay, here it is:
https://gist.github.com/mandaleyshow/9d27f87d34eb6c4700586317ab6aa6da
