### ISSUE TITLE
 Unable to install any npm package on Windows 7 connected to Internet via wifi 

### ISSUE THREAD

**Issue by jyothiradityak** [npm/npm#13928]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [ ] npm is producing an incorrect install.
- [x] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
  npm is doing something I don't understand.
#### What's going wrong?

unable to install any npm package like browser-sync, gulp, grunt on my Windows 7
#### How can the CLI team reproduce the problem?

C:>npm install -g browser-sync
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files (x86)\nodejs\node.exe" "C:\Program Files (x86)\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "browser-sync"
npm ERR! node v4.5.0
npm ERR! npm v2.15.9
npm ERR! code ECONNREFUSED
npm ERR! errno ECONNREFUSED
npm ERR! syscall connect

npm ERR! Error: connect ECONNREFUSED 127.0.0.1:8080
npm ERR! at Object.exports._errnoException (util.js:907:11)
npm ERR! at exports._exceptionWithHostPort (util.js:930:20)
npm ERR! at TCPConnectWrap.afterConnect as oncomplete
npm ERR! { [Error: connect ECONNREFUSED 127.0.0.1:8080]
npm ERR! code: 'ECONNREFUSED',
npm ERR! errno: 'ECONNREFUSED',
npm ERR! syscall: 'connect',
npm ERR! address: '127.0.0.1',
npm ERR! port: 8080 }
npm ERR!
npm ERR! If you are behind a proxy, please make sure that the
npm ERR! 'proxy' config is set properly. See: 'npm help config'

I am unable to install any npm package like browser-sync.Could you please suggest how to fix this error.

I have already tried set registry to http://registry.npmjs.org/. Could you please suggest how to fix this error. I have already tried running the command "npm install connect" as Administrator and got the same thing. Can anyone help?
### supporting information:
- `npm -v` prints:
- `node -v` prints:
- `npm config get registry` prints:
- Windows, OS X, or Linux?:
- Network issues:
  - Geographic location where npm was run:
  - [ ] I use a proxy to connect to the npm registry.
  - [ ] I use a proxy to connect to the web.
  - [ ] I use a proxy when downloading Git repos.
  - [ ] I access the npm registry via a VPN
  - [x] I don't use a proxy, but have limited or unreliable internet access.
- Container:
  - [ ] I develop using Vagrant on Windows.
  - [ ] I develop using Vagrant on OS X or Linux.
  - [ ] I develop / deploy using Docker.
  - [ ] I deploy to a PaaS (Triton, Heroku).
    Please find the output of npm config ls -l below. 
    ; cli configs
    long = true
    user-agent = "npm/2.15.9 node/v4.5.0 win32 x64"

; userconfig C:\Users\Home.npmrc
https-proxy = "http://127.0.0.1:8080/"
proxy = "http://127.0.0.1:8080/"
registry = "http://registry.npmjs.org/"
strict-ssl = false

; builtin config undefined
prefix = "C:\Users\Home\AppData\Roaming\npm"

; default values
access = null
always-auth = false
bin-links = true
browser = null
ca = null
cache = "C:\Users\Home\AppData\Roaming\npm-cache"
cache-lock-retries = 10
cache-lock-stale = 60000
cache-lock-wait = 10000
cache-max = null
cache-min = 10
cafile = undefined
cert = null
color = true
depth = null
description = true
dev = false
editor = "notepad.exe"
engine-strict = false
fetch-retries = 2
fetch-retry-factor = 10
fetch-retry-maxtimeout = 60000
fetch-retry-mintimeout = 10000
force = false
git = "git"
git-tag-version = true
global = false
globalconfig = "C:\Users\Home\AppData\Roaming\npm\etc\npmrc"
globalignorefile = "C:\Users\Home\AppData\Roaming\npm\etc\npmignore"
group = 0
heading = "npm"
; https-proxy = null (overridden)
if-present = false
ignore-scripts = false
init-author-email = ""
init-author-name = ""
init-author-url = ""
init-license = "ISC"
init-module = "C:\Users\Home\.npm-init.js"
init-version = "1.0.0"
json = false
key = null
link = false
local-address = undefined
loglevel = "warn"
; long = false (overridden)
maxsockets = 50
message = "%s"
node-version = "4.5.0"
npat = false
onload-script = null
optional = true
parseable = false
; prefix = "C:\Program Files (x86)\nodejs" (overridden)
production = false
proprietary-attribs = true
; proxy = null (overridden)
rebuild-bundle = true
; registry = "https://registry.npmjs.org/" (overridden)
rollback = true
save = false
save-bundle = false
save-dev = false
save-exact = false
save-optional = false
save-prefix = "^"
scope = ""
searchexclude = null
searchopts = ""
searchsort = "name"
shell = "C:\Windows\system32\cmd.exe"
shrinkwrap = true
sign-git-tag = false
spin = true
; strict-ssl = true (overridden)
tag = "latest"
tag-version-prefix = "v"
tmp = "D:\Temp"
umask = 0
unicode = true
unsafe-perm = true
usage = false
user = 0
; user-agent = "npm/{npm-version} node/{node-version} {platform} {arch}" (overridden)
userconfig = "C:\Users\Home\.npmrc"
version = false
versions = false
viewer = "browser"

Regards,
Aditya

**Comment by legodude17** [comment]
Please check your proxy and carefully read the npm docs about proxies.
