### ISSUE TITLE
This is an error with npm itself. Please report this error at:

### ISSUE THREAD

**Issue by jianboy** [npm/npm#13921]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'update' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 verbose stack Error: Missing required argument #1
4 verbose stack     at module.exports (/usr/share/npm/lib/install/mutate-into-logical-tree.js:12:3)
4 verbose stack     at /usr/share/npm/lib/outdated.js:78:5
4 verbose stack     at /usr/share/npm/lib/outdated.js:62:20
4 verbose stack     at /usr/share/npm/node_modules/read-package-tree/rpt.js:186:9
4 verbose stack     at f (/usr/share/npm/node_modules/once/once.js:17:25)
4 verbose stack     at then (/usr/share/npm/node_modules/read-package-tree/rpt.js:166:22)
4 verbose stack     at f (/usr/share/npm/node_modules/once/once.js:17:25)
4 verbose stack     at then (/usr/share/npm/node_modules/read-package-tree/rpt.js:166:22)
4 verbose stack     at f (/usr/share/npm/node_modules/once/once.js:17:25)
4 verbose stack     at then (/usr/share/npm/node_modules/read-package-tree/rpt.js:166:22)
5 verbose cwd /mnt/shared
6 error Linux 4.4.0-31-generic
7 error argv "/usr/bin/nodejs" "/usr/bin/npm" "update"
8 error node v4.2.6
9 error npm  v3.5.2
10 error code EMISSINGARG
11 error typeerror Error: Missing required argument #1
11 error typeerror     at module.exports (/usr/share/npm/lib/install/mutate-into-logical-tree.js:12:3)
11 error typeerror     at /usr/share/npm/lib/outdated.js:78:5
11 error typeerror     at /usr/share/npm/lib/outdated.js:62:20
11 error typeerror     at /usr/share/npm/node_modules/read-package-tree/rpt.js:186:9
11 error typeerror     at f (/usr/share/npm/node_modules/once/once.js:17:25)
11 error typeerror     at then (/usr/share/npm/node_modules/read-package-tree/rpt.js:166:22)
11 error typeerror     at f (/usr/share/npm/node_modules/once/once.js:17:25)
11 error typeerror     at then (/usr/share/npm/node_modules/read-package-tree/rpt.js:166:22)
11 error typeerror     at f (/usr/share/npm/node_modules/once/once.js:17:25)
11 error typeerror     at then (/usr/share/npm/node_modules/read-package-tree/rpt.js:166:22)
12 error typeerror This is an error with npm itself. Please report this error at:
12 error typeerror     <http://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]

**Comment by legodude17** [comment]
Try updating npm.

**Comment by KenanY** [comment]
Closing as abandoned.
