### ISSUE TITLE
npm publish doesn't include README.md

### ISSUE THREAD

**Issue by pgmanutd** [npm/npm#13929]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I decided to bump my repo from ```1.0.6``` to ```1.1.0 (minor version)``` after making some changes. After that, I did ```npm publish``` and it ignored my ```README.md``` file. It was getting included in all previous versions.

My package.json:
```
{
  "name": "clogy",
  "version": "1.1.0",
  "description": "A logging library for browsers and nodejs environment",
  "homepage": "https://github.com/pgmanutd/clogy",
  "author": {
    "name": "pgmanutd",
    "email": "prashantmanunited@gmail.com",
    "url": "https://github.com/pgmanutd"
  },
  "repository": {
    "type": "git",
    "url": "git://github.com/pgmanutd/clogy.git"
  },
  "bugs": {
    "url": "https://github.com/pgmanutd/clogy/issues"
  },
  "main": "lib/clogy.js",
  "engines": {
    "node": ">= 0.6.0"
  },
  "files": [
    "LICENSE",
    "README.md",
    "CHANGELOG.md",
    "CONTRIBUTING.md",
    "lib/" 
  ],
.......
}
```

PS: It also happened earlier, when I bumped from ```1.0.2``` to ```1.0.3```. I missed it that time.

#### How can the CLI team reproduce the problem?
Just do ```npm install clogy@1.0.6``` and ```npm install clogy@1.1.0``` and compare the files. ```README.md``` will be missing from the latest release.

Did I make a mistake somewhere or is it a npm bug?

### supporting information:

 - `npm -v` prints: 3.8.6
 - `node -v` prints: v6.0.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X, or Linux?: Windows
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
`README.md` (or something like that) should always be included. Try updating to the latest version of npm. This may be one of the race conditions that @othiym23 was investigating.

**Comment by pgmanutd** [comment]
Sure, I will try updating the npm, but can you point me out this race condition which @othiym23 is investigating?

**Comment by legodude17** [comment]
The main thread of the race conditions is in #5084.

**Comment by pgmanutd** [comment]
Closing this issue. Updated to the latest version of npm and it's working fine.
