### ISSUE TITLE
connect ENOTCONN 151.101.76.162:80 while install body-parser

### ISSUE THREAD

**Issue by pxduong** [npm/npm#13937]
i'm actualy a new in NodeJs Dev.

When i try to install body-parser, the first error like 

`E:\NodeJs>npm install body-parser -g
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "body-parser" "-g"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! syscall getaddrinfo

npm ERR! network getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:80
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     E:\NodeJs\npm-debug.log`

i fix it by 
`npm config set registry http://registry.npmjs.org:80/`
 and now the error is 

`E:\NodeJs>npm install body-parser -g
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "body-parser" "-g"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ENOTCONN
npm ERR! errno ENOTCONN
npm ERR! syscall connect

npm ERR! connect ENOTCONN 151.101.76.162:80
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     E:\NodeJs\npm-debug.log`

Can somebody help my to fix it? thanks!

**Comment by KenanY** [comment]
@pxduong Are you behind a proxy or firewall?

**Comment by KenanY** [comment]
Closing as abandoned.
