### ISSUE TITLE
npm install checking for presence of tarball content

### ISSUE THREAD

**Issue by wordswords** [npm/npm#13939]
#### What's the feature?

Add tarball checking for npm install.
#### What problem is the feature intended to solve?

When you have a file with the same name as the node module you're trying to install, in the root directory of your application, and run 'npm install <module in repository> -g', npm treats that file as a tarball file and tries to install it, instead of the npm module from the repository. I think this is confusing for beginners and could be differentiated better in the error message, which fails with a ENOENT can't find package.json' error. 

It could be made easier by checking if the file is in fact a tarball before decompressing, and if it is not, and is a file instead of a directory, then it could throw a warning.
#### Is the absence of this feature blocking you or your team? If so, how?

No
#### Is this feature similar to an existing feature in another tool?

Yes
#### Is this a feature you're prepared to implement, with support from the npm CLI team?

Unfortunately I'm not able to.

**Comment by legodude17** [comment]
If it is not a tarball, npm tries to take the folder as a pre-unzipped tarball. I think you are mixing the terms `tarball` and `package`.

**Comment by wordswords** [comment]
This is what I mean..

mkdir test-node
cd test-node
npm init
echo  > bluebird-retry # or any npm module..
npm install bluebird-retry -g # for example

npm ERR! not a package /Users/craddd01/workspace/test-node/bluebird-retry
npm ERR! addLocal Could not install /Users/craddd01/workspace/test-node/bluebird-retry
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/craddd01/.nvm/versions/node/v4.5.0/bin/node" "/Users/craddd01/.nvm/versions/node/v4.5.0/bin/npm" "install" "bluebird-retry"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! path /var/folders/4q/09qrwl4s1d74sjqvwm65fjyhkw16z3/T/npm-7523-64dc664a/unpack-419c293b4610/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/var/folders/4q/09qrwl4s1d74sjqvwm65fjyhkw16z3/T/npm-7523-64dc664a/unpack-419c293b4610/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/craddd01/workspace/test-node/npm-debug.log

**Comment by legodude17** [comment]
What do you think it should do in that case? I think it should give a warning and then install the remote module.

**Comment by wordswords** [comment]
9 times out of 10 you want to install a remote module anyway, and if there is a local file with the same name then it should take that into account. Either with a more friendly error message that says something along the lines of 'we tried to install the local file, that turned out not to be a npm package, and it's preventing us fetching a remote module, have you tried removing it and installing a remote module' or as you said, automatically reaching for that remote module if the local file turns out not to be a valid package.

**Comment by legodude17** [comment]
Yeah.
