### ISSUE TITLE
npm install does not install devDependencies of sub modules

### ISSUE THREAD

**Issue by dogfoodsilo4** [npm/npm#13938]
Hi, 

We're moving to npm@3, however I have an issue with the devDependencies of sub modules not being installed when running npm install.

The goal is for our project structure to remain unchanged, but all sub module dependencies & devDependencies to be installed to the root node_modules and shared by all sub modules. We currently use npm-workspace, but that doesn't give us the flat structure that npm3 provides.  

Here's a simplified example...

tree structure:

```
myApp
--node_modules
--mySubModule
----sub.js
----package.json
--app.js
--package.json
```

root level package.json:

```
{
  "name": "myApp Root",
  "dependencies": {
    "mySubModule": "file:mySubModule"
  }
}
```

mySubModule package.json:

```
{
  "name": "mySubModule",
  "dependencies": {
    "lodash": "^3.10.1",
  },
  "devDependencies": {
    "chai": "^1.9.1",
    "tslint": "^3.12.1"
  }
}

```

When I run npm install, lodash is installed in the root node_modules but chai and tslint are not.  If I move them into the dependencies they are installed as expected.

I've scoured the docs and forums, but can't find a solution.  Am I barking up the wrong tree by trying to use the root dependencies to share packages among sub modules?

Also, I notice that mySubModule and it's contents are included as a folder in node_modules.  Why is this needed?
## Thanks, I'd be very grateful for any help.
- `npm -v` prints: 3.10.8
- `node -v` prints: v4.5.0
- `npm config get registry` prints: https://registry.npmjs.org/
- Operating system: Windows 7
- Geographic location where npm was run: UK

**Comment by legodude17** [comment]
The problem is almost the definition of `devDependencies`. They are only installed when you do `npm install` in the dir (Unless I am wrong). The one about it being moved is that you are installing, not linking. You might want to run `npm link` in `mySubModule` and then `npm link mySubModule` in the root dir. The other one is that `npm install` is not recursive, so it will not install in root and `./mySubModule`.

**Comment by dogfoodsilo4** [comment]
@legodude17 Thanks for the reply.  

I don't think there is an issue with devDependencies of the mySubModule package.json, if I run npm install it works as expected. Chai and tslint are installed in the node_modules folder within mySubModule.

What I want is for all prod and dev dependencies of mySubModule to be installed in the root node_modules.

I created the dependencies in the root package.json using:

```
npm install mySubModule.  
```

This creates the json shown in my original post.  Then running npm install in the root correctly adds mySubModule dependencies in the root node_modules, but not devDependencies.  Unless I am missing something fundamental, this has to be an issue in npm?

Unfortunately npm link does not do what I am looking for.
