### ISSUE TITLE
Error install ionic. Help please

### ISSUE THREAD

**Issue by imamaris** [npm/npm#13935]
npm ERR! npm  v3.8.6

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "generator-ionic"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "generator-ionic"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\IMAM~1.MUN\AppData\Local\Temp\npm-14740-591bd740\registry.npmjs.org\code-point-at-\code-point-at-1.0.0.tgz.4008713674' -> 'C:\Users\IMAM~1.MUN\AppData\Local\Temp\npm-14740-591bd740\registry.npmjs.org\code-point-at-\code-point-at-1.0.0.tgz'
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "generator-ionic"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\IMAM~1.MUN\AppData\Local\Temp\npm-14740-591bd740\registry.npmjs.org\code-point-at-\code-point-at-1.0.0.tgz.2547520215' -> 'C:\Users\IMAM~1.MUN\AppData\Local\Temp\npm-14740-591bd740\registry.npmjs.org\code-point-at-\code-point-at-1.0.0.tgz'
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "generator-ionic"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "generator-ionic"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\IMAM~1.MUN\AppData\Local\Temp\npm-14740-591bd740\registry.npmjs.org\number-is-nan-\number-is-nan-1.0.0.tgz.3006971002' -> 'C:\Users\IMAM~1.MUN\AppData\Local\Temp\npm-14740-591bd740\registry.npmjs.org\number-is-nan-\number-is-nan-1.0.0.tgz'
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "generator-ionic"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\IMAM~1.MUN\AppData\Local\Temp\npm-14740-591bd740\registry.npmjs.org\number-is-nan-\number-is-nan-1.0.0.tgz.3202022976' -> 'C:\Users\IMAM~1.MUN\AppData\Local\Temp\npm-14740-591bd740\registry.npmjs.org\number-is-nan-\number-is-nan-1.0.0.tgz'
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "generator-ionic"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "generator-ionic"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\IMAM~1.MUN\AppData\Local\Temp\npm-14740-591bd740\registry.npmjs.org\config-chain-\config-chain-1.1.10.tgz.2245961526' -> 'C:\Users\IMAM~1.MUN\AppData\Local\Temp\npm-14740-591bd740\registry.npmjs.org\config-chain-\config-chain-1.1.10.tgz'
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "generator-ionic"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\IMAM~1.MUN\AppData\Local\Temp\npm-14740-591bd740\registry.npmjs.org\ini-\ini-1.1.0.tgz.4279793152' -> 'C:\Users\IMAM~1.MUN\AppData\Local\Temp\npm-14740-591bd740\registry.npmjs.org\ini-\ini-1.1.0.tgz'
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "generator-ionic"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\IMAM~1.MUN\AppData\Local\Temp\npm-14740-591bd740\registry.npmjs.org\osenv-\osenv-0.0.3.tgz.1225268758' -> 'C:\Users\IMAM~1.MUN\AppData\Local\Temp\npm-14740-591bd740\registry.npmjs.org\osenv-\osenv-0.0.3.tgz'
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "generator-ionic"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\IMAM~1.MUN\AppData\Local\Temp\npm-14740-591bd740\registry.npmjs.org\nopt-\nopt-2.2.1.tgz.3370128472' -> 'C:\Users\IMAM~1.MUN\AppData\Local\Temp\npm-14740-591bd740\registry.npmjs.org\nopt-\nopt-2.2.1.tgz'
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "generator-ionic"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\IMAM~1.MUN\AppData\Local\Temp\npm-14740-591bd740\registry.npmjs.org\ini-\ini-1.1.0.tgz.2179727277' -> 'C:\Users\IMAM~1.MUN\AppData\Local\Temp\npm-14740-591bd740\registry.npmjs.org\ini-\ini-1.1.0.tgz'
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "generator-ionic"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\IMAM~1.MUN\AppData\Local\Temp\npm-14740-591bd740\registry.npmjs.org\osenv-\osenv-0.0.3.tgz.2116953243' -> 'C:\Users\IMAM~1.MUN\AppData\Local\Temp\npm-14740-591bd740\registry.npmjs.org\osenv-\osenv-0.0.3.tgz'
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "generator-ionic"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\IMAM~1.MUN\AppData\Local\Temp\npm-14740-591bd740\registry.npmjs.org\nopt-\nopt-2.2.1.tgz.2083593924' -> 'C:\Users\IMAM~1.MUN\AppData\Local\Temp\npm-14740-591bd740\registry.npmjs.org\nopt-\nopt-2.2.1.tgz'
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "generator-ionic"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "generator-ionic"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "generator-ionic"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues
npm WARN optional Skipping failed optional dependency /generator-ionic/are-we-there-yet/delegates:
npm WARN EBUSY: resource busy or locked, rename 'C:\Users\IMAM~1.MUN\AppData\Local\Temp\npm-14740-591bd740\registry.npmjs.org\delegates-\delegates-1.0.0.tgz.678801570' -> 'C:\Users\IMAM~1.MUN\AppData\Local\Temp\npm-14740-591bd740\registry.npmjs.org\delegates-\delegates-1.0.0.tgz'
npm WARN optional Skipping failed optional dependency /generator-ionic/gauge/string-width:
npm WARN EBUSY: resource busy or locked, rename 'C:\Users\IMAM~1.MUN\AppData\Local\Temp\npm-14740-591bd740\registry.npmjs.org\string-width-\string-width-1.0.2.tgz.1539764994' -> 'C:\Users\IMAM~1.MUN\AppData\Local\Temp\npm-14740-591bd740\registry.npmjs.org\string-width-\string-width-1.0.2.tgz'
npm WARN optional Skipping failed optional dependency /generator-ionic/gauge/aproba:
npm WARN EBUSY: resource busy or locked, rename 'C:\Users\IMAM~1.MUN\AppData\Local\Temp\npm-14740-591bd740\registry.npmjs.org\aproba-\aproba-1.0.4.tgz.1023514727' -> 'C:\Users\IMAM~1.MUN\AppData\Local\Temp\npm-14740-591bd740\registry.npmjs.org\aproba-\aproba-1.0.4.tgz'
npm WARN optional Skipping failed optional dependency /generator-ionic/gauge/has-color:
npm WARN EBUSY: resource busy or locked, rename 'C:\Users\IMAM~1.MUN\AppData\Local\Temp\npm-14740-591bd740\registry.npmjs.org\has-color-\has-color-0.1.7.tgz.2437287825' -> 'C:\Users\IMAM~1.MUN\AppData\Local\Temp\npm-14740-591bd740\registry.npmjs.org\has-color-\has-color-0.1.7.tgz'
npm WARN optional Skipping failed optional dependency /generator-ionic/string-width/code-point-at:
npm WARN EBUSY: resource busy or locked, rename 'C:\Users\IMAM~1.MUN\AppData\Local\Temp\npm-14740-591bd740\registry.npmjs.org\code-point-at-\code-point-at-1.0.0.tgz.2764842890' -> 'C:\Users\IMAM~1.MUN\AppData\Local\Temp\npm-14740-591bd740\registry.npmjs.org\code-point-at-\code-point-at-1.0.0.tgz'
npm WARN optional Skipping failed optional dependency /generator-ionic/is-fullwidth-code-point/number-is-nan:
npm WARN EBUSY: resource busy or locked, rename 'C:\Users\IMAM~1.MUN\AppData\Local\Temp\npm-14740-591bd740\registry.npmjs.org\number-is-nan-\number-is-nan-1.0.0.tgz.4053354712' -> 'C:\Users\IMAM~1.MUN\AppData\Local\Temp\npm-14740-591bd740\registry.npmjs.org\number-is-nan-\number-is-nan-1.0.0.tgz'
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "generator-ionic"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! path C:\Users\IMAM~1.MUN\AppData\Local\Temp\npm-14740-591bd740\registry.npmjs.org\ini-\ini-1.1.0.tgz.1275376113
npm ERR! code EBUSY
npm ERR! errno -4082
npm ERR! syscall rename

npm ERR! EBUSY: resource busy or locked, rename 'C:\Users\IMAM~1.MUN\AppData\Local\Temp\npm-14740-591bd740\registry.npmjs.org\ini-\ini-1.1.0.tgz.1275376113' -> 'C:\Users\IMAM~1.MUN\AppData\Local\Temp\npm-14740-591bd740\registry.npmjs.org\ini-\ini-1.1.0.tgz'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "generator-ionic"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\imam.munandar\npm-debug.log

C:\Users\imam.munandar>ionic -v
'ionic' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\imam.munandar>

C:\Users\imam.munandar>

**Comment by legodude17** [comment]
Try updating npm. Also try `npm cache clean`.

**Comment by KenanY** [comment]
Closing due to no reply.
