### ISSUE TITLE
Install Error (package.json issue?)

### ISSUE THREAD

**Issue by kiroukou** [npm/npm#13936]
#### I'm opening this issue because:

  - [ ] npm is producing an incorrect install.

#### What's going wrong?
See below

#### How can the CLI team reproduce the problem?

npm install && npm start

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@1.4.9
3 info using node@v4.5.0
4 error Error: ENOENT: no such file or directory, open 'C:\cygwin64\home\Thomas\package.json'
4 error     at Error (native)
5 error If you need help, you may report this *entire* log,
5 error including the npm and node versions, at:
5 error     <http://github.com/npm/npm/issues>
6 error System Windows_NT 10.0.10586
7 error command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
8 error cwd C:\cygwin64\home\Thomas
9 error node -v v4.5.0
10 error npm -v 1.4.9
11 error path C:\cygwin64\home\Thomas\package.json
12 error syscall open
13 error code ENOENT
14 error errno -4058
15 verbose exit [ -4058, true ]

### supporting information:

 - `npm -v` prints:  **1.4.9**
 - `node -v` prints:  **v4.5.0**
 - `npm config get registry` prints:  **{"db_name":"registry","doc_count":388416,"doc_del_count":354,"update_seq":2408629,"purge_seq":0,"compact_running":false,"disk_size":1883848827,"data_size":1544116998,"instance_start_time":"1473667309331144","disk_format_version":6,"committed_update_seq":2408629}**
 - Windows, OS X, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.

THanks for your help.

**Comment by KenanY** [comment]
@kiroukou Does `C:\cygwin64\home\Thomas\package.json` exist? You probably want a `package.json` in your current directory before running `npm start`. Furthermore, do note that `npm@1` is very old, so consider updating `npm`.

**Comment by KenanY** [comment]
Closing as abandoned.

**Comment by TestDeftsoft12** [comment]
@KenanY  I also having this issue. Is there any issue provided regarding this?

Please find below npm-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@1.3.2
3 info using node@v4.5.0
4 error Error: ENOENT: no such file or directory, open 'F:\ovote-web\cloud\package.json'
4 error     at Error (native)
5 error If you need help, you may report this log at:
5 error     <http://github.com/isaacs/npm/issues>
5 error or email it to:
5 error     <npm-@googlegroups.com>
6 error System Windows_NT 6.3.9600
7 error command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
8 error cwd F:\ovote-web\cloud
9 error node -v v4.5.0
10 error npm -v 1.3.2
11 error path F:\ovote-web\cloud\package.json
12 error syscall open
13 error code ENOENT
14 error errno -4058
15 verbose exit [ -4058, true ]

```

**Comment by KenanY** [comment]
@TestDeftsoft12 Please see my comment above. `npm@1.3` is very old and is no longer supported. Also, make sure you have a `package.json` in your current directory.
