### ISSUE TITLE
I CANNOT INSTALL 'npm install -g express' HELP

### ISSUE THREAD

**Issue by doandthink** [npm/npm#13931]
I'm mad, what wrong with this problem `?`
`C:\WINDOWS\system32>npm install -g express
npm ERR! tar.unpack error reading C:\WINDOWS\system32\express
npm ERR! addLocal Could not install C:\WINDOWS\system32\express
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "express"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9

npm ERR! 0-byte tarball
npm ERR! Please run `npm cache clean`
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\WINDOWS\system32\npm-debug.log`

**Comment by KenanY** [comment]
@doandthink Have you tried running `npm cache clean`?

**Comment by doandthink** [comment]
@KenanY I had run `npm cache clearn` but it didn't help......I also reinstall many times

**Comment by legodude17** [comment]
Try updating npm and maybe try `npm@3`.

**Comment by busches** [comment]
Are you intentionally installing to `C:\WINDOWS\system32`? Are you running the command prompt with admin permissions?

**Comment by KenanY** [comment]
Closing due to lack of any further responses.
