### ISSUE TITLE
I can´t install bower. 

### ISSUE THREAD

**Issue by blelevier** [npm/npm#13940]
#### I'm opening this issue because:

I can´t install bower
#### What's going wrong?

I write: npm install -g bower

And the following message appears:

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "bower"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3

npm ERR! error:0906D06C:PEM routines:PEM_read_bio:no start line
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Users\212464224\npm-debug.log
#### How can the CLI team reproduce the problem?

The link to the log file is:
https://gist.github.com/blelevier/707b66bb17151607ba0a3e7775b1a402
### supporting information:
- `npm -v` prints: bash: npm-v: command not found
- `node -v` prints: bash: node-v: command not found
- `npm config get registry` prints: https://registry.npmjs.org
- Windows, OS X, or Linux?: Windows 7
- Network issues:
  - Geographic location where npm was run:
  - [ ] I use a proxy to connect to the npm registry.
  - [ ] I use a proxy to connect to the web.
  - [ ] I use a proxy when downloading Git repos.
  - [ ] I access the npm registry via a VPN
  - [ ] I don't use a proxy, but have limited or unreliable internet access.
- Container:
  - [ ] I develop using Vagrant on Windows.
  - [ ] I develop using Vagrant on OS X or Linux.
  - [ ] I develop / deploy using Docker.
  - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
Check you internet connection by trying to go to `https://registry.npmjs.org/bower`. If it works fine then try updating npm and running `npm cache clean`.

**Comment by blelevier** [comment]
I update the comment, when I write:
`npm -v`, it prints: 3.10.3 
`node -v` , it prints: v6.5.0 

When I go to https://registry.npmjs.org/bower , it shows me this:
![image](https://cloud.githubusercontent.com/assets/22152218/18475599/a607cb16-798c-11e6-8e57-b14d556601f9.png)

**Comment by legodude17** [comment]
Did you try `npm cache clean`?

**Comment by blelevier** [comment]
Yes, I tried it
