### ISSUE TITLE
which command line can be used to search @types? 

### ISSUE THREAD

**Issue by gxsjtu** [npm/npm#13943]
'search' command line does not list types package, like npm search @types/lodash, nothing returned, but actually there is one exist.
<img width="1301" alt="qq20160913-0 2x" src="https://cloud.githubusercontent.com/assets/5119062/18457913/458234f4-798f-11e6-9201-0527dd65c61d.png">

if i want to search types of one specific package, which command line should be used?

**Comment by legodude17** [comment]
I don't think there is currently a command to search with scopes, but I think that if there isn't, there should be. What do you think @KenanY?

**Comment by KenanY** [comment]
Sounds okay to me, if it brings `npm search` functionality closer to that of the website's search. Up to the core team whether or not it gets merged though.

**Comment by gxsjtu** [comment]
any updates?

**Comment by KenanY** [comment]
@gxsjtu Nope, up to the core team to review this request :)
