### ISSUE TITLE
TypeError: uid must be an unsigned int WHEN upgrading npm

### ISSUE THREAD

**Issue by adasongliang** [npm/npm#13946]
**Running the command:** 
sudo npm -g install npm@latest

**I'm facing the error below:** 
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/Cellar/node/6.5.0/bin/node" "/usr/local/bin/npm" "-g" "install" "npm@latest"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.8

npm ERR! uid must be an unsigned int
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/yiqiang.yang/npm-debug.log

I did the research to resolve the issue, and tried the following: 
Yibin-2:~ yiqiang.yang$ npm config get user
501
Yibin-2:~ yiqiang.yang$ npm config del user
Yibin-2:~ yiqiang.yang$ 

What else can I do to fix the issue?

**Comment by dexteriti** [comment]
I just got the same issue. Unable to perform update on npm as well.

```
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "npm"
npm ERR! node v4.4.4
npm ERR! npm  v3.10.8

npm ERR! uid must be an unsigned int
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

**Comment by addaleax** [comment]
See https://github.com/npm/npm/issues/13918, in particular the workaround mentioned in this comment: https://github.com/npm/npm/issues/13918#issuecomment-246512054

**Comment by dexteriti** [comment]
@addaleax I am left with only the #3 step as an option. First two didn't work for me. Is there any documentation about the issue?

It was working fine yesterday. I had to reinstall packages and I end up with that.

**Comment by addaleax** [comment]
@dexteriti You could use npm@3.10.7 instead of 3.10.8 or use a patched version of Node.js yourself, I guess… the former should usually be the easiest option.

> Is there any documentation about the issue?

Apart from here, on the issue tracker?

**Comment by adasongliang** [comment]
After I uninstalled and reinstalled the node, try the command "sudo npm -g install npm@latest".  The issue disappear. 

Thanks a lot!
