### ISSUE TITLE
Verify that files in bin, main, module, files exist on `npm publish`

### ISSUE THREAD

**Issue by bfred-it** [npm/npm#13948]
#### What's the feature? What problem is the feature intended to solve?

A couple times I published packages without the required files or with the wrong paths in these properties:
- `bin`
- `main`
- `module`
- `files`

It would be great to verify that the files specified in there exist before packing and uploading the module. For example:

``` json
{
    "bin": "bin/index.js"
}
```

Does the file `bin/index.js` exist? If not, fail the upload, this is likely an error. 

If that file is meant to be generated on `postinstall` or any time after the installation, then at least give a warning. This could be the default behavior.

Where globs are allowed (`files`) perhaps it could verify that the closest folder exists (e.g. the folder `includes` in `includes/**`) or that at least one file is matched. Alternatively globs could just be ignored.
#### Is this feature similar to an existing feature in another tool?

No, but it's [being discussed](https://github.com/sindresorhus/np/issues/82) in a `npm publish` wrapper (`np`)

**Comment by legodude17** [comment]
This is fairly hard to implement but I think it is a good idea. What do you think @othiym23?
