### ISSUE TITLE
npm HPE_UNEXPECTED_CONTENT_LENGTH error

### ISSUE THREAD

**Issue by sairam0903** [npm/npm#13944]
whenever doing npm install
I get `npm ERR! code HPE_UNEXPECTED_CONTENT_LENGTH` at the very beginning.

I am trying to get the source code from [https://github.com/elastic/kibana](url)
and then in the same path I am running `npm install` and I get this error
```
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.4.3
npm ERR! npm  v3.10.3
npm ERR! code HPE_UNEXPECTED_CONTENT_LENGTH

npm ERR! Parse Error
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

```
I am not sure, what exactly is happening but npm install starts and after 30 - 40 secs it just throws this error.

`⸨    ░░░░░░░░░░░░░░⸩ ⠴ fetchMetadata: sill mapToRegistry uri http://npm.corp.****.com/trunc-text` takes long time and I get the above error

**Comment by legodude17** [comment]
This is probably a problem with your internal registry. Try `npm config set registry https://registry.npmjs.org`.

**Comment by sairam0903** [comment]
That worked, thanks..
