### ISSUE TITLE
npm update flag to only update package.json

### ISSUE THREAD

**Issue by idleberg** [npm/npm#13945]
#### What's the feature?

Add a flag for `npm update` to write updated versions to `package.json` without installing
#### What problem is the feature intended to solve?

I often use `npm update --save --save-dev` to update my Node (dev)dependencies in `package.json`. This takes considerable time, since the updates are actually installed (which is usually fine.) Yet, I would prefer an additional flag that only writes the updated versions into `package.json` without installing anything, so I can quickly push the updated files of GitHub etc. 
#### Is the absence of this feature blocking you or your team? If so, how?

It's not blocking, it's simply consuming a lot of time
#### Is this feature similar to an existing feature in another tool?

I don't know
#### Is this a feature you're prepared to implement, with support from the npm CLI team?

Probably not. I write JavaScript, but I doubt my level is on par with what you guys do.

**Comment by legodude17** [comment]
I could do this and this seems like a really good idea. Any thoughts @KenanY or @othiym23?
