### ISSUE TITLE
npm ERR issues when I try to run the following command

### ISSUE THREAD

**Issue by kanajam** [npm/npm#13957]
```
yo angular

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.2.4
npm ERR! npm v3.10.7

npm ERR! Hostname/IP doesn't match certificate's altnames: "Host: registry.nodejs.org. is not in the cert's altnames: DNS:a.sni.fastly.net, DNS:a.sni.global-ssl.fastly.net"
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR! https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR! /Users/kanajam/angular-project/npm-debug.log

events.js:141
throw er; // Unhandled 'error' event
^

Error: spawn gulp ENOENT
at exports._errnoException (util.js:870:11)
at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
at onErrorNT (internal/child_process.js:344:16)
at doNTCallback2 (node.js:441:9)
at process._tickCallback (node.js:355:17)
```

I followed the followed documentation:

https://www.airpair.com/js/using-angularjs-yeoman

Please help me to get rid of this issue.
Struggling from last two days on windows platform as well as on mac.

Your help would be appreciated.

Regards,
Vijay Kanajam
#### I'm opening this issue because:
- [ ] npm is crashing.
- [ ] npm is producing an incorrect install.
- [ ] npm is doing something I don't understand.
- [x] Other (_see below for feature requests_):
### supporting information:
- `npm -v` prints:
- `node -v` prints:
- `npm config get registry` prints:
- Windows, OS X, or Linux?:
- Network issues:
  - Geographic location where npm was run:
  - [ ] I use a proxy to connect to the npm registry.
  - [ ] I use a proxy to connect to the web.
  - [ ] I use a proxy when downloading Git repos.
  - [ ] I access the npm registry via a VPN
  - [x] I don't use a proxy, but have limited or unreliable internet access.
- Container:
  - [x] I develop using Vagrant on Windows.
  - [ ] I develop using Vagrant on OS X or Linux.
  - [ ] I develop / deploy using Docker.
  - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by heijmans** [comment]
You have the wrong registry. `registry.nodejs.org` should be `registry.npmjs.org`. I am not sure where the wrong registry URL comes from. You can check your registry URL as follows:

    npm config get registry

An easy fix might be:

    npm config set registry https://registry.npmjs.org/

But you might want to check if you have an `.npmrc` file in your local directory or in your home directory. If so, open it and remove the line saying `registry=https://registry.nodejs.org/`

**Comment by kanajam** [comment]
hey heijmans,

I registered as per your comment.
But somewhere i'm getting the following:

 UNMET PEER DEPENDENCY karma@1.3.0

following with 

npm WARN gulp-karma@0.0.4 requires a peer of karma@>=0.10 <=0.13 but none was installed.

and also 

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn gulp ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)

Same error in different situation.
Please update me.
I'm going through the below url:

https://www.airpair.com/js/using-angularjs-yeoman

**Comment by heijmans** [comment]
Hi Kanajam,

gulp-karma needs karma, but you don't have karma installed. This can probably be fixed by:

    npm install --save karma

This command installs karma and save information about the installed karma version in your package.json file.

I hope this helps. Strictly speaking this is not an issue with npm but more of an issue with the yeoman angular generator:

https://github.com/yeoman/generator-angular

But I can imagine that that is not clear for you.

Cheers,
Jan
