### ISSUE TITLE
What is the difference between /usr/lib/node_modules and /usr/local/lib/node_modules ?

### ISSUE THREAD

**Issue by cawa-93** [npm/npm#13956]
#### I'm opening this issue because:
- [x] npm is doing something I don't understand.
#### What's going wrong?

On my system, there are two folders

```
/usr/lib/node_modules
/usr/local/lib/node_modules
```

And stored there are different versions of the same libraries that causes discomfort.

```
/usr/lib/node_modules/typescript/bin/tsc -v
Version 2.0.2
```

```
/usr/local/lib/node_modules/typescript/bin/tsc -v
Version 1.8.10
```

I would like to know why this is happening and how i can control the installation of libraries? How to know where the library will be installed?
### supporting information:
- `/usr/lib/node_modules/npm/bin/npm-cli.js -v` prints: `3.10.8`
- `node -v` prints: `v4.5.0`
- `npm config get registry` prints: `https://registry.npmjs.org/`
- `cat /proc/version` prints:

```
Linux version 4.4.0-36-generic (buildd@lcy01-01) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.2) ) #5 5-Ubuntu SMP Thu Aug 11 18:01:55 UTC 2016
```

**Comment by JulienPalard** [comment]
I'm having the same "inconsistency"  here, where I'm having ionic in both paths, and upgrading it upgrade "the wrong one" according to the `/usr/local/bin/ionic` symlink, which is _before_ `/usr/bin/ionic` in my `$PATH`:

```
# /usr/lib/node_modules/ionic/bin/ionic --version | tail -n 2
2.0.0

# /usr/local/lib/node_modules/ionic/bin/ionic --version | tail -n 2
1.7.14

# which ionic
/usr/local/bin/ionic

# readlink -f $(!!)
readlink -f $(which ionic)
/usr/local/lib/node_modules/ionic/bin/ionic
```

I suspect the npm in Debian packages uses a different path than the npm from ... npm?

**Comment by legodude17** [comment]
What is your `npm.prefix`? Run `npm prefix -g` to find out.

**Comment by guacachips** [comment]
I've the same problem that @cawa-93 !

Until today all my global packages are installed in `/usr/local/lib/node_modules/`

However, now if I try to install a new package with the -g flag there is automatically installed in `/usr/lib/node_modules` and I don't understand why.

I've run `npm prefix -g` and I get this : `/usr` so it seems logic but in this case why all my old packages are installed in `/usr/local`

Someone know anything about this sudden change ?

**Comment by cawa-93** [comment]
```
$ npm prefix -g
/usr
```

**Comment by legodude17** [comment]
@cawa-93 and @guacachips, are the contents of either folder symlinks, or is `npm` actually installing in both places?

**Comment by cawa-93** [comment]
@legodude17, no and no.
npm install only in `usr/lib/node_modules`

**Comment by legodude17** [comment]
Then what is the problem @cawa-93?

**Comment by comodoro** [comment]
I can describe the problem, because I just noticed that I have it and I do not understand it either. Some, probably outdated modules are in `/usr/local/lib/node_modules`. `npm uninstall -g` does not touch them. But they are still there and are linked in my case from `/usr/local/bin` (old version of `truffle`, installed also in the past by npm AFAIK). I cannot upgrade these outdated packages because of these links. I do not know what to do, shall I  delete the `usr/lib/local/node_modules` and update the links, or are there other files I need to modify or delete?

**Comment by legodude17** [comment]
@comodoro what is the result of `npm prefix -g`?

**Comment by comodoro** [comment]
It was blank. I set it to /usr/lib/node_modules, I am not sure, but as far as I can remember, setting it had no effect (`npm install -g` worked the same way). So it occurs to me that if I set it to `/usr/local/lib/node_modules`, uninstall the old modules and set it back to `/usr/lib/node_modules`, everything should work normal again?

**Comment by legodude17** [comment]
That should work correctly.

**Comment by comodoro** [comment]
All right, if there is no better way... will try tomorrow and report here.

**Comment by comodoro** [comment]
I tried the above and it did not work, no idea why (changed `$NODE_PATH` and tried again `npm uninstall -g`). So being tired of this, I deleted `/usr/local/lib/node_modules` and the links to the old modules in `/usr/local/bin`. I hope there are not more old files lingering, or at least that they will not ever be used.

**Comment by legodude17** [comment]
@comodoro  they shouldn't be used.

**Comment by rhizene** [comment]
just wanted to share as I have  noted this on my own machine and I think it occurs on all my `npm install -g` after I have my node updated by  `sudo npm  install n -g`, which have my node updated (updated my npm afterwards. Was trying to install appium). I have my  old global packages at `usr/lib/node_modules`, while now saving globally puts them at `/usr/local/lib/node_modules`. Currently having Node 7.8.0 with npm 4.4.4
