### ISSUE TITLE
Why using only single core during build?

### ISSUE THREAD

**Issue by igpg** [npm/npm#13954]
#### I'm opening this issue because:

I have quite some cores at my disposition, while building the package (actually brave-browser is requiring it) I'v noticed with top that it's using only one core of my CPU , so the build is taking a long time.
#### How can the CLI team reproduce the problem?

yaourt -S brave-git
top

I hope this (single thread) isn't also a problem when running?

**Comment by legodude17** [comment]
I think the problem that you are encountering is that JS is normally single threaded. An idea I have had you a while is to attempt (keyword) to refactor `npm` to use multiple threads with `cluster.fork`. What do you think about that @othiym23 and @KenanY?

**Comment by igpg** [comment]
That's just a great way to solve an issue npm-robot 🗡
