### ISSUE TITLE
npm ERR!

### ISSUE THREAD

**Issue by Sandeep-Patel** [npm/npm#13952]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ##] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
npm ERR! tar.unpack unzip error /var/folders/r_/b1pvv6mj7x9ghth4khdz00bw3954sg/T/npm-49944-d6a61804/registry.npmjs.org/kss/-/kss-2.4.0.tgz
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/6.2.2/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code Z_BUF_ERROR
npm ERR! errno -5

npm ERR! unexpected end of file
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by mahone3297** [comment]
I have met the case, too.
```
npm ERR! tar.unpack unzip error /tmp/npm-10367-13e455d2/registry.npmjs.org/yargs/-/yargs-3.5.4.tgz
npm ERR! Linux 3.16.0-30-generic
npm ERR! argv "/home/mahone/git/software/node-v5.9.1-linux-x64/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.9.1
npm ERR! npm  v3.7.3
npm ERR! code Z_BUF_ERROR
npm ERR! errno -5

npm ERR! unexpected end of file
```

**Comment by othiym23** [comment]
Y'all both probably have corrupt npm caches. `npm cache clear` followed by a reinstall should clear this up; also you might take the opportunity to update to the newest npm to ensure the cache corruption doesn't recur. Closing as resolved!

**Comment by michaelneale** [comment]
I see this happen regularly with NO npm cache at all, it doesn't seem related to cache

**Comment by DavidPeicho** [comment]
This is still the case in 2018, and I am pretty sure it does not come from the cache
