### ISSUE TITLE
getting error while installing ionic

### ISSUE THREAD

**Issue by 1188Prashant** [npm/npm#13965]
C:\Users\123>npm install -g cordova
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! syscall getaddrinfo

npm ERR! network getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443

npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\123\npm-debug.log

**Comment by KenanY** [comment]
@1188Prashant This looks like an issue with your internet connection rather than with `npm` itself. Are you behind a proxy or firewall?

**Comment by 1188Prashant** [comment]
Thank You @KenanY
