### ISSUE TITLE
Getting error in express

### ISSUE THREAD

**Issue by Mugesh-Rajaram** [npm/npm#13962]
Dear Team,
      While am getting start with the link 'https://code.visualstudio.com/docs/runtimes/nodejs'  getting some error while using express.
     Help me to clear the below error.

**ERROR MESSAGE :**

D:\Mugesh\SAMPLES\NodeSampleProject>node app.js
Hello Mugesh..! welcome to India.

D:\Mugesh\SAMPLES\NodeSampleProject>node app.js
Hello Mugesh..! welcome to India.
Server running at http://127.0.0.1:1337/
^C
D:\Mugesh\SAMPLES\NodeSampleProject>
D:\Mugesh\SAMPLES\NodeSampleProject>npm help
^CTerminate batch job (Y/N)? y

D:\Mugesh\SAMPLES\NodeSampleProject>npm --help

Usage: npm <command>

where <command> is one of:
    access, add-user, adduser, apihelp, author, bin, bugs, c,
    cache, completion, config, ddp, dedupe, deprecate, dist-tag,
    dist-tags, docs, edit, explore, faq, find, find-dupes, get,
    help, help-search, home, i, info, init, install, issues, la,
    link, list, ll, ln, login, logout, ls, outdated, owner,
    pack, ping, prefix, prune, publish, r, rb, rebuild, remove,
    repo, restart, rm, root, run-script, s, se, search, set,
    show, shrinkwrap, star, stars, start, stop, t, tag, team,
    test, tst, un, uninstall, unlink, unpublish, unstar, up,
    update, upgrade, v, version, view, whoami

npm <cmd> -h     quick help on <cmd>
npm -l           display full usage info
npm faq          commonly asked questions
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    C:\Users\is5063.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@2.15.5 C:\Program Files\nodejs\node_modules\npm

D:\Mugesh\SAMPLES\NodeSampleProject>npm install -g express-generator
C:\Users\is5063\AppData\Roaming\npm\express -> C:\Users\is5063\AppData\Roaming\npm\node_modules\express-generator\bin\express
express-generator@4.13.4 C:\Users\is5063\AppData\Roaming\npm\node_modules\express-generator
├── sorted-object@2.0.0
├── commander@2.7.1 (graceful-readlink@1.0.1)
└── mkdirp@0.5.1 (minimist@0.0.8)

D:\Mugesh\SAMPLES\NodeSampleProject>express myExpressApp

   create : myExpressApp
   create : myExpressApp/package.json
   create : myExpressApp/app.js
   create : myExpressApp/public
   create : myExpressApp/routes
   create : myExpressApp/routes/index.js
   create : myExpressApp/routes/users.js
   create : myExpressApp/views
   create : myExpressApp/views/index.jade
   create : myExpressApp/views/layout.jade
   create : myExpressApp/views/error.jade
   create : myExpressApp/public/stylesheets
   create : myExpressApp/public/stylesheets/style.css
   create : myExpressApp/public/images
   create : myExpressApp/public/javascripts
   create : myExpressApp/bin
   create : myExpressApp/bin/www

   install dependencies:
     > cd myExpressApp && npm install

   run the app:
     > SET DEBUG=myExpressApp:\* & npm start

D:\Mugesh\SAMPLES\NodeSampleProject>cd myExpressApp

D:\Mugesh\SAMPLES\NodeSampleProject\myExpressApp>npm install
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\is5063\AppData\Local\Temp\npm-3748-92bed356\registry.npmjs.org\acorn-\acorn-1.2.2.tgz.95650291' -> 'C:\Users\is5063\AppData\Local\Temp\npm-3748-92bed356\registry.npmjs.org\acorn-\acorn-1.2.2.tgz'
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\is5063\AppData\Local\Temp\npm-3748-92bed356\registry.npmjs.org\cliui-\cliui-2.1.0.tgz.1036030196' -> 'C:\Users\is5063\AppData\Local\Temp\npm-3748-92bed356\registry.npmjs.org\cliui-\cliui-2.1.0.tgz'
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\is5063\AppData\Local\Temp\npm-3748-92bed356\registry.npmjs.org\camelcase-\camelcase-1.2.1.tgz.1166255466' -> 'C:\Users\is5063\AppData\Local\Temp\npm-3748-92bed356\registry.npmjs.org\camelcase-\camelcase-1.2.1.tgz'
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\is5063\AppData\Local\Temp\npm-3748-92bed356\registry.npmjs.org\right-align-\right-align-0.1.3.tgz.1485184621' -> 'C:\Users\is5063\AppData\Local\Temp\npm-3748-92bed356\registry.npmjs.org\right-align-\right-align-0.1.3.tgz'
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\is5063\AppData\Local\Temp\npm-3748-92bed356\registry.npmjs.org\longest-\longest-1.0.1.tgz.1434686890' -> 'C:\Users\is5063\AppData\Local\Temp\npm-3748-92bed356\registry.npmjs.org\longest-\longest-1.0.1.tgz'
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues
debug@2.2.0 node_modules\debug
└── ms@0.7.1

serve-favicon@2.3.0 node_modules\serve-favicon
├── fresh@0.3.0
├── parseurl@1.3.1
├── ms@0.7.1
└── etag@1.7.0

cookie-parser@1.4.3 node_modules\cookie-parser
├── cookie-signature@1.0.6
└── cookie@0.3.1

morgan@1.7.0 node_modules\morgan
├── on-headers@1.0.1
├── basic-auth@1.0.4
├── depd@1.1.0
└── on-finished@2.3.0 (ee-first@1.1.1)

body-parser@1.15.2 node_modules\body-parser
├── bytes@2.4.0
├── content-type@1.0.2
├── depd@1.1.0
├── qs@6.2.0
├── on-finished@2.3.0 (ee-first@1.1.1)
├── raw-body@2.1.7 (unpipe@1.0.0)
├── http-errors@1.5.0 (setprototypeof@1.0.1, statuses@1.3.0, inherits@2.0.1)
├── iconv-lite@0.4.13
└── type-is@1.6.13 (media-typer@0.3.0, mime-types@2.1.11)

express@4.13.4 node_modules\express
├── etag@1.7.0
├── fresh@0.3.0
├── parseurl@1.3.1
├── escape-html@1.0.3
├── array-flatten@1.1.1
├── cookie-signature@1.0.6
├── content-type@1.0.2
├── vary@1.0.1
├── merge-descriptors@1.0.1
├── content-disposition@0.5.1
├── range-parser@1.0.3
├── path-to-regexp@0.1.7
├── methods@1.1.2
├── utils-merge@1.0.0
├── cookie@0.1.5
├── depd@1.1.0
├── qs@4.0.0
├── on-finished@2.3.0 (ee-first@1.1.1)
├── finalhandler@0.4.1 (unpipe@1.0.0)
├── proxy-addr@1.0.10 (forwarded@0.1.0, ipaddr.js@1.0.5)
├── send@0.13.1 (destroy@1.0.4, ms@0.7.1, statuses@1.2.1, mime@1.3.4, http-errors@1.3.1)
├── type-is@1.6.13 (media-typer@0.3.0, mime-types@2.1.11)
├── accepts@1.2.13 (negotiator@0.5.3, mime-types@2.1.11)
└── serve-static@1.10.3 (send@0.13.2)

jade@1.11.0 node_modules\jade
├── character-parser@1.2.1
├── commander@2.6.0
├── void-elements@2.0.1
├── mkdirp@0.5.1 (minimist@0.0.8)
├── jstransformer@0.0.2 (is-promise@2.1.0, promise@6.1.0)
├── constantinople@3.0.2 (acorn@2.7.0)
├── clean-css@3.4.19 (commander@2.8.1, source-map@0.4.4)
├── transformers@2.1.0 (promise@2.0.0, css@1.0.8, uglify-js@2.2.5)
├── with@4.0.3 (acorn-globals@1.0.9, acorn@1.2.2)
└── uglify-js@2.7.3 (async@0.2.10, uglify-to-browserify@1.0.2, source-map@0.5.6, yargs@3.10.0)
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5

npm ERR! Callback called more than once.
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Mugesh\SAMPLES\NodeSampleProject\myExpressApp\npm-debug.log

D:\Mugesh\SAMPLES\NodeSampleProject\myExpressApp>

**Comment by MugeshBTech** [comment]
help on the above error anybody there...?

**Comment by MugeshBTech** [comment]
Hi,

 Help me on the below error.

**ERROR** 


D:\Mugesh\SAMPLES\Node Samples>cd myExpressApp

D:\Mugesh\SAMPLES\Node Samples\myExpressApp>npm install tsd
npm WARN deprecated tsd@0.6.5: TSD is deprecated in favor of Typings (https://github.com/typings/typings) - see https://github.com/DefinitelyTyped/tsd/issues/269 for more information
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN engine joi-assert@0.0.3: wanted: {"node":">= 0.10.0 <= 0.11.0"} (current: {"node":"4.4.5","npm":"2.15.5"})
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN prefer global tsd@0.6.5 should be installed with -g
tsd@0.6.5 node_modules\tsd
├── diff@1.4.0
├── assertion-error@1.0.0
├── type-detect@0.1.2
├── joi-assert@0.0.3
├── deep-freeze@0.0.1
├── open@0.0.5
├── jsesc@0.5.0
├── ministyle@0.1.4
├── lru-cache@2.5.2
├── rimraf@2.2.8
├── uuid@2.0.2
├── colors@1.1.2
├── minimist@1.2.0
├── exit@0.1.2
├── minitable@0.0.4 (minichain@0.0.1)
├── uri-templates@0.1.9
├── semver@4.3.6
├── lazy.js@0.3.2
├── json-pointer@0.2.2 (foreach@2.0.5)
├── minimatch@1.0.0 (sigmund@1.0.1)
├── detect-indent@0.2.0 (get-stdin@0.1.0, minimist@0.1.0)
├── chalk@1.1.3 (escape-string-regexp@1.0.5, supports-color@2.0.0, ansi-styles@2.2.1, strip-ansi@3.0.1, has-ansi@2.0.0)
├── miniwrite@0.1.4 (mkdirp@0.3.5)
├── event-stream@3.1.7 (pause-stream@0.0.11, stream-combiner@0.0.4, duplexer@0.1.1, from@0.1.3, map-stream@0.1.0, split@0.2.10, through@2.3.8)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── bl@0.9.5 (readable-stream@1.0.34)
├── universal-analytics@0.3.11 (async@0.2.10, underscore@1.8.3, node-uuid@1.4.7)
├── glob@4.5.3 (inherits@2.0.3, once@1.4.0, inflight@1.0.5, minimatch@2.0.10)
├── definition-header@0.1.0 (xregexp@2.0.0, parsimmon@0.5.1)
├── bluebird@1.2.4
├── update-notifier@0.2.2 (is-npm@1.0.0, semver-diff@2.1.0, string-length@1.0.1, chalk@0.5.1, latest-version@1.0.1, configstore@0.3.2)
├── verror@1.4.0 (extsprintf@1.0.3)
├── joi@4.9.0 (topo@1.1.0, isemail@1.2.0, hoek@2.16.3, moment@2.15.0)
└── request@2.74.0 (aws-sign2@0.6.0, tunnel-agent@0.4.3, oauth-sign@0.8.2, forever-agent@0.6.1, is-typedarray@1.0.0, caseless@0.11.0, stringstream@0.0.5, aws4@1.4.1, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, tough-cookie@2.3.1, qs@6.2.1, node-uuid@1.4.7, combined-stream@1.0.5, mime-types@2.1.11, bl@1.1.2, hawk@3.1.3, http-signature@1.1.1, har-validator@2.0.6, form-data@1.0.1)

D:\Mugesh\SAMPLES\Node Samples\myExpressApp>tsd query node express --action install
'tsd' is not recognized as an internal or external command,
operable program or batch file.

D:\Mugesh\SAMPLES\Node Samples\myExpressApp>tsd query node --action install
'tsd' is not recognized as an internal or external command,
operable program or batch file.

D:\Mugesh\SAMPLES\Node Samples\myExpressApp>

**Comment by legodude17** [comment]
`tsd` is now in your `node_modules` if you wanted to run it from command
line you should run `npm i -g tsd`.
