### ISSUE TITLE
npm install or npm start is showing error

### ISSUE THREAD

**Issue by tishya8** [npm/npm#13967]
npm ERR! Linux 3.19.0-66-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v5.10.0
npm ERR! npm  v3.8.3

npm ERR! missing script: start
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/html/npm-debug.log

**Comment by legodude17** [comment]
Do you have a `start` script in package.json?

**Comment by hally9k** [comment]
I am seeing the same thing here. I have a start script. I can see all of my scripts in the output from `npm run`.

`PS C:\Users\me\Source\my-repo> npm run
Lifecycle scripts included in my-repo:
  start
    echo 'No start script implemented...';`

I can run scripts directly...

`PS C:\Users\me\Source\my-repo> npm start

> my-repo@0.0.1 start C:\Users\Source\my-repo
> echo 'No start script implemented...';

'No start script implemented...';`

 but as soon as a script calls another script...

`PS C:\Users\me\Source\my-repo> npm run
Lifecycle scripts included in redux-ui-router:
  start
    npm run notimplemented;

available via `npm run-script`:
  notimplemented
    echo 'No start script implemented...';`

 ...it complains that the script it's trying to call is missing... 

`PS C:\Users\me\Source\my-repo> npm start

> my-repo@0.0.1 start C:\Users\Source\my-repo
> npm run notimplemented;

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\me\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "notimplemented;"
npm ERR! node v4.4.5
npm ERR! npm  v3.9.6

npm ERR! missing script: notimplemented;
npm ERR!

npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>`

**Comment by KenanY** [comment]
@hally9k Have you tried removing the semicolon in your `"start"` script?

**Comment by hally9k** [comment]
Aaaah of course... I flick between a Mac and my work machine on Windows and this gets me every time... You sir, are a GEM!

**Comment by tishya8** [comment]
I created package.json as directed by a tytorial but I dont have any 'start' script there... below is my package.json code..

{
  "name": "root",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}

**Comment by KenanY** [comment]
@tishya8 You can add one like so:

``` json
{
  "name": "root",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
	"start": "command to run here"
  },
  "author": "",
  "license": "ISC"
}
```

**Comment by KenanY** [comment]
Closing since this is intentional behavior; you cannot run `npm start` without a `"start"` script (or without a `server.js` in your current directory, which makes the default `node server.js`).

**Comment by AyanTatai** [comment]
====Executing command 'npm install'====


npm ERR! Windows_NT 10.0.15063
npm ERR! argv "D:\\Node Js\\node.exe" "D:\\Node Js\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! shasum check failed for C:\Users\ayanc\AppData\Local\Temp\npm-220-02be931e\registry.npmjs.org\typescript\-\typescript-2.1.6.tgz
npm ERR! Expected: 40c7e6e9e5da7961b7718b55505f9cac9487a607
npm ERR! Actual:   31175e0478ab5cb3f1b436070a43fa29e8f938cd
npm ERR! From:     https://registry.npmjs.org/typescript/-/typescript-2.1.6.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Please include the following file with any support request:
npm ERR!     c:\users\ayanc\documents\visual studio 2015\Projects\Angular2Demo\Angular2Demo\npm-debug.log

====npm command completed with exit code 1====
