### ISSUE TITLE
Installing “script@3.9.0” failed.

### ISSUE THREAD

**Issue by herruli** [npm/npm#13961]
#### I'm opening this issue because:
- [ ] npm is doing something I don't understand.
#### What's going wrong?

I want to install tha package script, but it show this. I have already uninstall the atom and deleting the folders including .atom

INFO: Could not find files for the given pattern(s).

npm ERR! git clone --template=C:\Users\Herru.atom.apm_git-remotes_templates --mirror git://github.com/monsterkodi/node-simple-plist.git C:\Users\Herru.atom.apm_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-58558bef: Cloning into bare repository 'C:\Users\Herru.atom.apm_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-58558bef'...
npm ERR! git clone --template=C:\Users\Herru.atom.apm_git-remotes_templates --mirror git://github.com/monsterkodi/node-simple-plist.git C:\Users\Herru.atom.apm_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-58558bef: fatal: unable to connect to github.com:
npm ERR! git clone --template=C:\Users\Herru.atom.apm_git-remotes_templates --mirror git://github.com/monsterkodi/node-simple-plist.git C:\Users\Herru.atom.apm_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-58558bef: github.com[0: 192.30.253.113]: errno=No error
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Users\Herru\AppData\Local\atom\app-1.10.2\resources\app\apm\bin\node.exe" "C:\Users\Herru\AppData\Local\atom\app-1.10.2\resources\app\apm\node_modules\npm\bin\npm-cli.js" "--globalconfig" "C:\Users\Herru\.atom\.apm\.apmrc" "--userconfig" "C:\Users\Herru\.atom\.apmrc" "install" "C:\Users\Herru\AppData\Local\Temp\d-116814-33140-1k615dg\package.tgz" "--runtime=electron" "--target=0.37.8" "--arch=ia32" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\Herru.atom.apm_git-remotes_templates --mirror git://github.com/monsterkodi/node-simple-plist.git C:\Users\Herru.atom.apm_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-58558bef
npm ERR! Cloning into bare repository 'C:\Users\Herru.atom.apm_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-58558bef'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.253.113]: errno=No error
npm ERR! 
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Herru\AppData\Local\Temp\apm-install-dir-116814-33140-82okq4\npm-debug.log
### supporting information:
- `npm -v` prints: 2.15.8
- `node -v` prints: 4.4.7
- `npm config get registry` prints: registry.npmjs.org
- Windows, OS X, or Linux?: Window
- Network issues:
  - Geographic location where npm was run:
- Container:

**Comment by legodude17** [comment]
What command did you run?
