### ISSUE TITLE
regarding ionic and cordova

### ISSUE THREAD

**Issue by 1188Prashant** [npm/npm#13977]
'cordova' is not recognized as an internal or external command,
operable program or batch file.
'ionic' is not recognized as an internal or external command,
operable program or batch file.

Can i get help to set environment variable for these?

Thank you

**Comment by KenanY** [comment]
@1188Prashant What is the `npm` issue here? Have you already done `npm install -g cordova ionic`? Do you have your global `node_modules/` directory in your system `PATH`?

**Comment by KenanY** [comment]
Closing as abandoned.
