### ISSUE TITLE
octopusdeploy/gulp-octo missing?

### ISSUE THREAD

**Issue by elisebaert** [npm/npm#13970]
npm http 404 https://registry.npmjs.org/octopusdeploy/gulp-octo
npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'octopusdeploy/gulp-octo' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it

**Comment by KenanY** [comment]
@elisebaert Could you provide a `npm-debug.log` file so that I can see how you are getting this error?

**Comment by elisebaert** [comment]
thanks for you reply

I seem to have fixed the problem, it looked like a problem with the version of node

 regards


________________________________
Van: Kenan Yildirim <notifications@github.com>
Verzonden: donderdag 15 september 2016 17:21
Aan: npm/npm
CC: elisebaert; Mention
Onderwerp: Re: [npm/npm] octopusdeploy/gulp-octo missing? (#13970)


@elisebaert<https://github.com/elisebaert> Could you provide a npm-debug.log file so that I can see how you are getting this error?

-

**Comment by KenanY** [comment]
Closing as resolved then.
