### ISSUE TITLE
npm ERR! Windows_NT 10.0.14393

### ISSUE THREAD

**Issue by zagorodnik** [npm/npm#13979]
```
C:\Users\Alex\WebstormProjects\Angular2>npm start
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! path C:\Users\Alex\WebstormProjects\Angular2\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\Alex\WebstormProjects\Angular2\package.json'
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\Alex\WebstormProjects\Angular2\package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Alex\WebstormProjects\Angular2\npm-debug.log


```

**Comment by KenanY** [comment]
@zagorodnik Does `C:\Users\Alex\WebstormProjects\Angular2\package.json` exist?

**Comment by Eruoghene** [comment]
i'm having same issue. if it doesn't how can i get it?

**Comment by KenanY** [comment]
@Eruoghene You can create one with `npm init`. Make sure to define a `"start"` script inside it too _before_ running `npm start`.

**Comment by ganeshMNAIK** [comment]
how can i fix this error..?
D:\angular2-demo>npm start
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.6.1
npm ERR! npm  v2.15.9
npm ERR! file D:\angular2-demo\package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected token ':' at 2:9
npm ERR!   "name": "angular2-demo",
npm ERR!         ^
npm ERR! File: D:\angular2-demo\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     D:\angular2-demo\npm-debug.log

**Comment by KenanY** [comment]
@zagorodnik Could you provide the entire `D:\angular2-demo\package.json`?

**Comment by ThaiQuocTuan2016** [comment]
John, thank you for reporting this issue.
What shell environment are you using (native windows command shell, mingw, cygwin)?
Can you please provide the output of the following two commands:
$ patch -v
$ snyk protect -d # please run it in project folder
Thanks! We managed to reproduce the issue locally. Please uninstall old version of gnu patch, and use official git tools instead (https://git-scm.com/download/win). Make sure to add the bin folder (C:\Program Files\Git\usr\bin\) to the PATH.
running patch -v should have the following output:

GNU patch 2.7.5
Copyright (C) 2003, 2009-2012 Free Software Foundation, Inc.
Copyright (C) 1988 Larry Wall

License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Larry Wall and Paul Eggert

https://github.com/Snyk/snyk/issues/45#issuecomment-250145966

**Comment by ThaiQuocTuan2016** [comment]
Solver:

C:\Users\Tuan_Pro\Desktop\TTTN\TST\myApp>patch -v
GNU patch 2.7.5
Copyright (C) 2003, 2009-2012 Free Software Foundation, Inc.
Copyright (C) 1988 Larry Wall

License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Larry Wall and Paul Eggert

C:\Users\Tuan_Pro\Desktop\TTTN\TST\myApp>npm install

> mean@0.7.0 postinstall C:\Users\Tuan_Pro\Desktop\TTTN\TST\myApp
> node tools/scripts/postinstall.js

Auto installing package dependencies
bower web-bootstrap#*             copy C:\Users\Tuan_Pro\Desktop\TTTN\TST\myApp\node_modules\meanio\resources\web-bootstrap.js
bower jquery#*                  cached https://github.com/jquery/jquery-dist.git#3.1.1
bower jquery#*                validate 3.1.1 against https://github.com/jquery/jquery-dist.git#*
bower angular#*                 cached https://github.com/angular/bower-angular.git#1.5.8
bower angular#*               validate 1.5.8 against https://github.com/angular/bower-angular.git#*
bower angular-resource#*        cached https://github.com/angular/bower-angular-resource.git#1.5.8
bower angular-resource#*      validate 1.5.8 against https://github.com/angular/bower-angular-resource.git#*
bower angular-cookies#*         cached https://github.com/angular/bower-angular-cookies.git#1.5.8
bower angular-cookies#*       validate 1.5.8 against https://github.com/angular/bower-angular-cookies.git#*
bower angular-route#*           cached https://github.com/angular/bower-angular-route.git#1.5.8
bower angular-route#*         validate 1.5.8 against https://github.com/angular/bower-angular-route.git#*
bower angular-mocks#*           cached https://github.com/angular/bower-angular-mocks.git#1.5.8
bower angular-mocks#*         validate 1.5.8 against https://github.com/angular/bower-angular-mocks.git#*
bower bootstrap#*               cached https://github.com/twbs/bootstrap.git#3.3.7
bower bootstrap#*             validate 3.3.7 against https://github.com/twbs/bootstrap.git#*
bower angular-ui-select#*       cached https://github.com/angular-ui/ui-select.git#0.19.6
bower angular-ui-select#*     validate 0.19.6 against https://github.com/angular-ui/ui-select.git#*
bower angular-ui-router#*       cached https://github.com/angular-ui/angular-ui-router-bower.git#0.3.1
bower angular-ui-router#*     validate 0.3.1 against https://github.com/angular-ui/angular-ui-router-bower.git#*
bower angular-bootstrap#*       cached https://github.com/angular-ui/bootstrap-bower.git#2.2.0
bower angular-bootstrap#*     validate 2.2.0 against https://github.com/angular-ui/bootstrap-bower.git#*
bower angular-sanitize#*        cached https://github.com/angular/bower-angular-sanitize.git#1.5.8
bower angular-sanitize#*      validate 1.5.8 against https://github.com/angular/bower-angular-sanitize.git#*
bower web-bootstrap#*         resolved C:\Users\Tuan_Pro\Desktop\TTTN\TST\myApp\node_modules\meanio\resources\web-bootstrap.js
    Updating Bower dependenciesadata: sill mapToRegistry uri https://registry.npmjs.org/libbase64
mean@0.7.0 C:\Users\Tuan_Pro\Desktop\TTTN\TST\myApp
+-- meanio-admin@0.1.7  (git://github.com/linnovate/meanio-admin.git#0e9d428c67789aadf5615f7d1a109716d3375ad4)
+-- meanio-circles@0.1.1  (git://github.com/linnovate/meanio-circles.git#3fd8e32af3374dcfc34026b7f86e9d332df2b3a6)
+-- meanio-system@0.1.3  (git://github.com/linnovate/meanio-system.git#a1b1b2b35eec858493d3a308e56d1e2014627ed5)
`-- meanio-users@0.1.4  (git://github.com/linnovate/meanio-users.git#b1084c608bbf17e879668e1392a664919151fa42)

    Dependencies installed for package meanStarter

> mean@0.7.0 prepublish C:\Users\Tuan_Pro\Desktop\TTTN\TST\myApp
> npm run snyk-protect


> mean@0.7.0 snyk-protect C:\Users\Tuan_Pro\Desktop\TTTN\TST\myApp
> snyk protect

Successfully applied Snyk patches
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

C:\Users\Tuan_Pro\Desktop\TTTN\TST\myApp>

**Comment by plmachado** [comment]
npm ERR! fetch failed https://registry.npmjs.org/buffer/-/buffer-4.5.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/assert/-/assert-1.3.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/browserify-zlib/-/browserify-zlib-0.1.4.tgz
npm ERR! fetch failed https://registry.npmjs.org/console-browserify/-/console-browserify-1.1.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/domain-browser/-/domain-browser-1.1.7.tgz
npm ERR! fetch failed https://registry.npmjs.org/http-browserify/-/http-browserify-1.7.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/events/-/events-1.1.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/https-browserify/-/https-browserify-0.0.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/os-browserify/-/os-browserify-0.2.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/punycode/-/punycode-1.4.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/process/-/process-0.11.2.tgz
npm ERR! fetch failed https://registry.npmjs.org/path-browserify/-/path-browserify-0.0.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/readable-stream/-/readable-stream-2.0.6.tgz
npm ERR! fetch failed https://registry.npmjs.org/querystring-es3/-/querystring-es3-0.2.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/stream-browserify/-/stream-browserify-2.0.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/string_decoder/-/string_decoder-0.10.31.tgz
npm ERR! fetch failed https://registry.npmjs.org/timers-browserify/-/timers-browserify-1.4.2.tgz
npm ERR! fetch failed https://registry.npmjs.org/tty-browserify/-/tty-browserify-0.0.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/url/-/url-0.11.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/vm-browserify/-/vm-browserify-0.0.4.tgz
npm ERR! fetch failed https://registry.npmjs.org/util/-/util-0.10.3.tgz
npm ERR! fetch failed https://registry.npmjs.org/crypto-browserify/-/crypto-browserify-3.11.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/constants-browserify/-/constants-browserify-1.0.0.tgz
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Users\\Pedro\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.3.4_1\\mt-os.windows.x86_32\\dev_bundle\\bin\\\\node.exe" "C:\\Users\\Pedro\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.3.4_1\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "angular2-meteor" "@angular/platform-browser-dynamic"
npm ERR! node v0.10.45
npm ERR! npm  v3.9.6
npm ERR! code EAGAIN
npm ERR! errno EAGAIN
npm ERR! syscall getaddrinfo

npm ERR! getaddrinfo EAGAIN
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Pedro\Desktop\app\app\npm-debug.log

**Comment by legodude17** [comment]
@plmachado, that is a different issue. Check your internet connection and then open a new issue if the problem persists.

**Comment by vg1ne** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.9
3 info using node@v7.1.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle angular2-typescript-webpack@1.3.0~prestart: angular2-typescript-webpack@1.3.0
6 silly lifecycle angular2-typescript-webpack@1.3.0~prestart: no script for prestart, continuing
7 info lifecycle angular2-typescript-webpack@1.3.0~start: angular2-typescript-webpack@1.3.0
8 verbose lifecycle angular2-typescript-webpack@1.3.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle angular2-typescript-webpack@1.3.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;F:\mainSite\node_modules\.bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Program Files\TortoiseGit\bin;C:\Users\админ\AppData\Local\Microsoft\WindowsApps;C:\Users\админ\AppData\Roaming\npm
10 verbose lifecycle angular2-typescript-webpack@1.3.0~start: CWD: F:\mainSite
11 silly lifecycle angular2-typescript-webpack@1.3.0~start: Args: [ '/d /s /c', 'webpack-dev-server' ]
12 silly lifecycle angular2-typescript-webpack@1.3.0~start: Returned: code: 3221226505  signal: null
13 info lifecycle angular2-typescript-webpack@1.3.0~start: Failed to exec start script
14 verbose stack Error: angular2-typescript-webpack@1.3.0 start: `webpack-dev-server`
14 verbose stack Exit status 3221226505
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:885:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid angular2-typescript-webpack@1.3.0
16 verbose cwd F:\mainSite
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v7.1.0
20 error npm  v3.10.9
21 error code ELIFECYCLE
22 error angular2-typescript-webpack@1.3.0 start: `webpack-dev-server`
22 error Exit status 3221226505
23 error Failed at the angular2-typescript-webpack@1.3.0 start script 'webpack-dev-server'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular2-typescript-webpack package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack-dev-server
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs angular2-typescript-webpack
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls angular2-typescript-webpack
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
Please, help. Everything works on another machine.

**Comment by legodude17** [comment]
As the error says, this is a problem with the `angular2-typescript-webpack` package. Please try running `./node_modules/.bin/webpack-dev-server`. If it succeeds then tell me, otherwise go bug the author.

**Comment by vg1ne** [comment]
Hi, guys. At least solved current issue by **removing node.js of version 7.1.0 and installing 7.0.0**. Hope, that it`ll helps someone.
Enjoy.

**Comment by juaniliska** [comment]
i have the same problem and to fix run 

- npm config get registry
- npm cache clean
- npm install express

and later
- npm install

and work fine

later 
-npm start

and work the tutorial of angular2 (no working in the first time)
D:\Angular2\juan\quickstart>npm start

> angular-quickstart@1.0.0 start D:\Angular2\juan\quickstart
> tsc && concurrently "tsc -w" "lite-server"

[0] 11:05:19 - Compilation complete. Watching for file changes.
[1] Did not detect a `bs-config.json` or `bs-config.js` override file. Using lite-server defaults...
[1] ** browser-sync config **
[1] { injectChanges: false,
[1]   files: [ './**/*.{html,htm,css,js}' ],
[1]   watchOptions: { ignored: 'node_modules' },
[1]   server: { baseDir: './', middleware: [ [Function], [Function] ] } }
[1] [BS] Access URLs:
[1]  ----------------------------------
[1]        Local: http://localhost:3000
[1]     External: http://10.0.2.30:3000
[1]  ----------------------------------
[1]           UI: http://localhost:3001
[1]  UI External: http://10.0.2.30:3001
[1]  ----------------------------------
[1] [BS] Serving files from: ./
[1] [BS] Watching files...
[1] 16.12.26 11:05:26 200 GET /index.html

**Comment by alokstar** [comment]
I tried everything but the issue was still there. Later I realized that while doing npm install, node downloads some dependencies from 'github.com'. Although my PC is having internet connection, 'github.com' is blocked at my work place. As a result, node was unable to download some dependencies. So I did 'npm install' using my private internet connection. It worked!

**Comment by chiranjeevisaride** [comment]
Same Issue please help
**node -v v7.5.0
npm -v 4.1.2
NOTE: tried doing "npm cache clean" didn't work**

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v7.5.0
npm ERR! npm v4.1.2
npm ERR! path C:\Users\Chiranjeevi\Desktop\angularJS\ang2\angular2-seed\node_modules.staging\base64id-47d544ab\package.json.1971791659
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\Chiranjeevi\Desktop\angularJS\ang2\angular2-seed\node_modules.staging\base64id-47d544ab\package.json.1971791659' -> 'C:\Users\Chiranjeevi\Desktop\angularJS\ang2\angular2-seed\node_modules.staging\base64id-47d544ab\package.json'
npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\Chiranjeevi\Desktop\angularJS\ang2\angular2-seed\node_modules.staging\base64id-47d544ab\package.json.1971791659' -> 'C:\Users\Chiranjeevi\Desktop\angularJS\ang2\angular2-seed\node_modules.staging\base64id-47d544ab\package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent
npm ERR! Please include the following file with any support request:
npm ERR! C:\Users\Chiranjeevi\Desktop\angularJS\ang2\angular2-seed\npm-debug.log

**Comment by vg1ne** [comment]
chiranjeevisaride, try to downgrade to node v7.0.0

**Comment by shahidkarimi** [comment]
@KenanY this issue is unresolved why you closed it. I have been trying to install for many days.

**Comment by KenanY** [comment]
@shahidkarimi I closed it because the original poster never responded to my question, so I assumed the issue was abandoned. If you're seeing the same error message, then [my suggestion](https://github.com/npm/npm/issues/13979#issuecomment-247606093) still stands.

**Comment by hayatmahedavi** [comment]
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "botkit"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10

npm ERR! shasum check failed for C:\Users\Hayat\AppData\Local\Temp\npm-15332-195bc615\registry.npmjs.org\lodash\-\lodash-4.17.4.tgz
npm ERR! Expected: 78203a4d1c328ae1d86dca6460e369b57f4055ae
npm ERR! Actual:   434ca340db93e65ff31b2109d5f46c0584467cca
npm ERR! From:     https://registry.npmjs.org/lodash/-/lodash-4.17.4.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Windows\System32\npm-debug.log


Please help.. !!

**Comment by aminnagpure** [comment]
i also have the same issue, does any one have a solution


E:\nodepractise\metamaskex\zircon>npm run dev

> zircon@0.0.1 dev E:\nodepractise\metamaskex\zircon
> npm run hot-server -- --start-hot


> zircon@0.0.1 hot-server E:\nodepractise\metamaskex\zircon
> cross-env NODE_ENV=development node --max_old_space_size=2096 -r babel-register server.js "--start-hot"

Listening at http://localhost:3000

> zircon@0.0.1 start-hot E:\nodepractise\metamaskex\zircon
> cross-env HOT=1 NODE_ENV=development electron -r babel-register -r babel-polyfill ./app/main.development

webpack built 29a13aade408b72f8bb1 in 6515ms

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start-hot"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! zircon@0.0.1 start-hot: `cross-env HOT=1 NODE_ENV=development electron -r babel-register -r babel-polyfill ./app/main.development`
npm ERR! Exit status 3221225477
npm ERR!
npm ERR! Failed at the zircon@0.0.1 start-hot script 'cross-env HOT=1 NODE_ENV=development electron -r babel-register -r babel-polyfill ./app/main.development'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the zircon package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env HOT=1 NODE_ENV=development electron -r babel-register -r babel-polyfill ./app/main.development
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs zircon
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls zircon
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\nodepractise\metamaskex\zircon\npm-debug.log

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "hot-server" "--" "--start-hot"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! zircon@0.0.1 hot-server: `cross-env NODE_ENV=development node --max_old_space_size=2096 -r babel-register server.js "--start-hot"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zircon@0.0.1 hot-server script 'cross-env NODE_ENV=development node --max_old_space_size=2096 -r babel-register server.js "--start-hot"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the zircon package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=development node --max_old_space_size=2096 -r babel-register server.js "--start-hot"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs zircon
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls zircon
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\nodepractise\metamaskex\zircon\npm-debug.log

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! zircon@0.0.1 dev: `npm run hot-server -- --start-hot`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zircon@0.0.1 dev script 'npm run hot-server -- --start-hot'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the zircon package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run hot-server -- --start-hot
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs zircon
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls zircon
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\nodepractise\metamaskex\zircon\npm-debug.log

**Comment by mragansh** [comment]
LOG. Not able to build my code.

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'login' ]
2 info using npm@4.1.2
3 info using node@v7.7.4
4 verbose stack Error: canceled
4 verbose stack     at Interface.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\read\lib\read.js:66:13)
4 verbose stack     at emitNone (events.js:86:13)
4 verbose stack     at Interface.emit (events.js:188:7)
4 verbose stack     at Interface._ttyWrite (readline.js:724:16)
4 verbose stack     at ReadStream.onkeypress (readline.js:117:10)
4 verbose stack     at emitTwo (events.js:106:13)
4 verbose stack     at ReadStream.emit (events.js:194:7)
4 verbose stack     at emitKeys (internal/readline.js:402:14)
4 verbose stack     at emitKeys.next (<anonymous>)
4 verbose stack     at ReadStream.onData (readline.js:971:36)
5 verbose cwd C:\Users\test\Desktop\HILTI\code-home\code-home\hvb-web\hvb-app
6 error Windows_NT 10.0.14393
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "login"
8 error node v7.7.4
9 error npm  v4.1.2
10 error canceled
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@mragansh Please open a new issue instead of commenting on unrelated ones.

**Comment by Assiswasiq** [comment]
same issue can anyone help me out
----------------------------------------------------------
C:\newfolder>npm install -g generator-meanjs
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "generator-meanjs"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5

npm ERR! shasum check failed for C:\Users\Assis\AppData\Local\Temp\npm-2560-4beefcfe\registry.npmjs.org\yeoman-environment\-\yeoman-environment-1.5.3.tgz
npm ERR! Expected: 76f0d14bd2529ca912bd6d20bcb717f8cd1a9ce7
npm ERR! Actual:   9abe6528f23b62e9dc9006c87e5637b24a8f9b80
npm ERR! From:     https://registry.npmjs.org/yeoman-environment/-/yeoman-environment-1.5.3.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\newfolder\npm-debug.log

**Comment by KenanY** [comment]
@Assiswasiq Your issue appears to be unrelated to that of the original poster. Could you open a new issue instead?

**Comment by rhidaymegacorp** [comment]
## plase how to solve this problem
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\DEVLOPMENT\\MEAN\\nodeJS\\node.exe" "C:\\DEVLOPMENT\\MEAN\\nodeJS\\node_modules\\npm\\bin\\npm-cli.js" "install" "gulp"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! code EINVAL

npm ERR! EINVAL: invalid argument, read
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     E:\01 Corporate\05 Rhiday Studio\06 Website\04 Partner\Uniquecardwedding\Unique\uniquecard.net\npm-debug.log

**Comment by PushpaKamatham** [comment]
I got the same . solution plz...

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\program files\\nodejs\\node.exe" "C:\\program files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ECONNREFUSED
npm ERR! errno ECONNREFUSED
npm ERR! syscall connect
npm ERR! Error: connect ECONNREFUSED 127.0.0.1:59693
npm ERR!     at Object.exports._errnoException (util.js:1020:11)
npm ERR!     at exports._exceptionWithHostPort (util.js:1043:20)
npm ERR!     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
npm ERR!  { Error: connect ECONNREFUSED 127.0.0.1:59693
npm ERR!     at Object.exports._errnoException (util.js:1020:11)
npm ERR!     at exports._exceptionWithHostPort (util.js:1043:20)
npm ERR!     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
npm ERR!   code: 'ECONNREFUSED',
npm ERR!   errno: 'ECONNREFUSED',
npm ERR!   syscall: 'connect',
npm ERR!   address: '127.0.0.1',
npm ERR!   port: 59693,
npm ERR!   parent: 'angular-quickstart' }
npm ERR! 
npm ERR! If you are behind a proxy, please make sure that the
npm ERR! 'proxy' config is set properly.  See: 'npm help config'
npm ERR! Please include the following file with any support request:

**Comment by PushpalathaNagam** [comment]
Hi All,

i got this in mvc angular 2 . while converting the collection data from APIcontroller to json in componet.ts file . please provide the solution for this 
Unexpected token S in JSON at position 0

**Comment by obbap1** [comment]
i have been having this error when trying to install ionic 

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ionic" "cordova"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10

npm ERR! Hostname/IP doesn't match certificate's altnames: "Host: registry.npm.org. is not in the cert's altnames: DNS:www.npmsecure.org, DNS:npmsecure.org"
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\PASCHAL\Desktop\npm-debug.log

**Comment by Tonchor** [comment]
How to fix this error ?
`-- express@4.16.2

npm WARN project_1@1.0.0 No description
npm WARN project_1@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: uws@0.14.5 (node_modules\uws):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: uws@0.14.5 install: `node-gyp rebuild > build_log.txt 2>&1 || exit 0`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: spawn C:\Windows\system32\cmd.exe\ ENOENT
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: uws@0.14.5 (node_modules\uws):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: uws@0.14.5 install: `node-gyp rebuild > build_log.txt 2>&1 || exit 0`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status -4058
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "express"
npm ERR! node v6.11.4
npm ERR! npm  v3.10.10

npm ERR! Callback called more than once.
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\project_1\npm-debug.log

**Comment by Jalaj-Maheshwari** [comment]
Do the following:

Go to Windows' Settings >> Network & Internet >> Proxy Go to Automatic proxy setup >> Make 'Automatically detect settings' to off.

Also check for some latest updates : npm install npm@next -g 
This worked for me!
Thank you!
