### ISSUE TITLE
"npm show <package>@<unpublished-version>" prints "undefined"

### ISSUE THREAD

**Issue by roblg** [npm/npm#13973]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

Sorry if this has already been reported. I spent several minutes trying to find a filed ticket, and couldn't. 

#### What's going wrong?

We automatically publish some internal npm packages via a CI build. That build checks if the package has previously been published via `npm show package@<expected version>`. In npm2, that returned an empty string, in npm3 it returns the string "undefined":

Example:

```
$ npm show react-server@12345
undefined
$ npm show --json react-server@12345
undefined
```

I guess my expectation was that the output would be the same between npm2 and npm3, but it's possible that's just silly of me. :) I also couldn't find documentation of the intended behavior, so I wasn't sure whether it's really a bug.

#### How can the CLI team reproduce the problem?

Example: `npm show react-server@12345`

### supporting information:

 - `npm -v` prints: 3.10.3
 - `node -v` prints: v6.5.0
 - `npm config get registry` prints: has same behavior on both our internal registry and the public one
 - Windows, OS X, or Linux?: Linux, OSX
 - Network issues:
   - Geographic location where npm was run: Oregon
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
This feels like `npm@3` should at least mirror `npm@2`'s behavior, and probably do something like error out.
