### ISSUE TITLE
npm link doesn't work with angular2 packages

### ISSUE THREAD

**Issue by vlodko** [npm/npm#13972]
#### I'm opening this issue because:

  - [x] npm link doesn't work as expected

#### What's going wrong?
I have module A. I run `npm link` in that folder.
I have module B. I run 'npm link A` in that folder.
I import module A into module B.
Webpack build runs without errors.
But I get error in the Chrome:
compiler.umd.js?9df7:14126 
**Uncaught Error: Unexpected value 'A' imported by the module 'B'**

### supporting information:

 - `npm -v` prints: 3.10.6
 - `node -v` prints: 6.5.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X, or Linux?: Win 10
 
NOTE: I'm using nvm for Windows.

**Comment by vlodko** [comment]
Any suggestions, guys?

**Comment by Madd0g** [comment]
Some pointed me to this PR, and I'm passing it along, because it solved the problem for me: https://github.com/angular/angular-cli/pull/2291

in webpack config:

    resolve: { 
         modules: [ path.join(__dirname, "node_modules") ] 
    }

**Comment by serhiisol** [comment]
dup of https://github.com/angular/angular-cli/issues/1875

**Comment by vlodko** [comment]
This is a part of my config file under /config folder:

```
  entry: {
    'vendor': helpers.root('src/demo/vendor.ts'),
    'polyfills': helpers.root('src/demo/polyfills.ts'),
    'demo': helpers.root('src/demo/main.ts')
  },

  resolve: {
    extensions: ['', '.js', '.ts'],
    modules: [ path.join(path.resolve(__dirname, '..'), 'node_modules') ]
  },
```

and I still have the same error:

**Uncaught Error: Unexpected value 'ModA' imported by the module 'ModB'**

**Comment by serhiisol** [comment]
I don't think that this ticket related to npm package, but you have to check your webpack configuration, cause that fix really works

**Comment by vlodko** [comment]
@serhiisol , Everything works fine when delete **node_modules** and **typings** folders from the linked module folder that I want to import.

**Comment by daniele-zurico** [comment]
Same issue for me! I've to remove node_mdules to get it working! Anyone fixed it? It's a really huge problem!

**Comment by vlodko** [comment]
I think this issue could be mark as closed.
I created different one on angular's issues page:
https://github.com/angular/angular/issues/11834

**Comment by daniele-zurico** [comment]
But is not related to angular.it's a webpack issue

**Comment by daniele-zurico** [comment]
And by the way you close it in angular as well so we have now the issue without bug

**Comment by datumgeek** [comment]
i also suffer from this issue...

**Comment by vlodko** [comment]
@datumgeek , please post updates if you'll solve the issue.

**Comment by datumgeek** [comment]
@vlodko - i unlinked my npm libs and rebuilt my app (via webpack), and it works just fine.  seems to confirm the idea that ***npm link*** is the issue

**Comment by vlodko** [comment]
@datumgeek , I'm still struggling with this problem.
what webpack config do you use for that? could please share it. thanks.
because I think that problem is in webpack bundler: 
when parent module use child modules, which are situated above parent in folder structure, webpack doens't build correctly.
but when I put my actual child module project folders in `node_modules` of parent module - it worked for me.

**Comment by datumgeek** [comment]
@vlodko - sure its all open source:

parent project: https://github.com/datumgeek/plotter-app-seed-angular2
parent project webpack.config.js: https://github.com/datumgeek/plotter-app-seed-angular2
child project: https://github.com/datumgeek/plotter-shell-angular2
grandchild project: https://github.com/datumgeek/plotter-shell-model

haven't done anything with instructions...  feel free to ping me on gitter if you need help:
https://gitter.im/misc-tech/Lobby

**Comment by datumgeek** [comment]
@vlodko this might be interesting to you :smile:

angular-cli beta 18 released 🚀
=============

> [release notes](https://github.com/angular/angular-cli/blob/master/CHANGELOG.md#100-beta18-2016-10-20)
> * [supports npm linked libraries](https://github.com/angular/angular-cli/issues/2291) !!!!!!!

**Comment by vlodko** [comment]
@datumgeek thanks a lot! I'll take a look

**Comment by vlodko** [comment]
@datumgeek, confirmed.
**npm link works like a charm with Webpack 2!**
Thanks again.

**Comment by datumgeek** [comment]
:smile:

**Comment by flyfj** [comment]
doesn't seem to work still. using the latest angular-cli.
but i noticed the same code works on mac but not linux.

**Comment by vlodko** [comment]
@flyfj have you seen this article [Linked libraries](https://github.com/angular/angular-cli/blob/master/docs/documentation/stories/linked-library.md) ?

**Comment by flyfj** [comment]
I tried that and it works. thanks for it!
