### ISSUE TITLE
Resolving multiple versions of module between devDependencies / dependencies

### ISSUE THREAD

**Issue by kwonoj** [npm/npm#13974]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [ ] npm is producing an incorrect install.
- [x] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
#### What's going wrong?

I'm trying to understand behavior of npm, please point me if I understand something wrong or if this is desired behavior of npm. 

Our module's `package.json` defines dependencies as below.

package.json in our module

``` js
...
  "dependencies": {
    ...
    "redux": "^3.6.0" 
  },
  "devDependencies": {
   ...
    "lodash": "^3.10.1"
  }

```

and `redux` defines its dependencies as 

``` js
  "dependencies": {
    ...
    "lodash": "^4.2.1",
  },
```

after doing `npm install`, module version's resolved as

```
test@1.0.0 /Users/ojkwon/github/test
├── lodash@3.10.1 
└─┬ redux@3.6.0
  └── UNMET DEPENDENCY lodash@^4.2.1

npm ERR! missing: lodash@^4.2.1, required by redux@3.6.0
```

which honors our module's devDependecny, while doesn't resolve dependency of redux.

If our module requires lodash as dependency instead of devdependency such as

``` js
  "dependencies": {
    ...
    "lodash": "^3.10.1",
    "redux": "^3.6.0"
  }
```

then both version of module lodash's resolved as 

```
test@1.0.0 /Users/ojkwon/github/test
├── lodash@3.10.1 
└─┬ redux@3.6.0
  └── lodash@4.15.0 
```

Question is - is it expected to not able to resolve multiple versions of module cases like above? in that case, what makes those differences?
#### How can the CLI team reproduce the problem?

setup module with following dependencies, then `npm install`.

``` js
  "dependencies": {
    "redux": "^3.6.0"
  },
  "devDependencies": {
    "lodash": "^3.10.1"
  }
```
### supporting information:
- `npm -v` prints: 3.10.7
- `node -v` prints: v6.5.0
- `npm config get registry` prints: https://registry.npmjs.org/
- Windows, OS X, or Linux?: OS X
- Network issues:
  - Geographic location where npm was run:
  - [ ] I use a proxy to connect to the npm registry.
  - [ ] I use a proxy to connect to the web.
  - [ ] I use a proxy when downloading Git repos.
  - [ ] I access the npm registry via a VPN
  - [ ] I don't use a proxy, but have limited or unreliable internet access.
- Container:
  - [ ] I develop using Vagrant on Windows.
  - [ ] I develop using Vagrant on OS X or Linux.
  - [ ] I develop / deploy using Docker.
  - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by CrabDude** [comment]
Can confirm. Seeing exactly this. `"devDependencies"` dependencies are getting installed at the top-level and replacing actual `"dependencies"`, when they should be nested due to the conflict.

`project/package.json`:

```json
  "dependencies": {
    "parseUri": "1.2.3-2"
  },
  "devDependencies": {
    "socket.io-client": "1.4.8"
  }
```

```json
  "dependencies": {
    "parseuri": "0.0.4",
  }
```

```bash
$ npm install

**Comment by hjdivad** [comment]
@kwonoj we are experiencing the same issues in https://github.com/emberjs/data

You may have already discovered this, but a second `npm install` will successfully install the unmet dependencies.
