### ISSUE TITLE
npm ERR! Windows_NT 10.0.10586

### ISSUE THREAD

**Issue by AntoniPierres** [npm/npm#13976]
I'm working a Laravel Project and when I try to install NPM :
- npm install 

and I get this issue:

npm` ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9

npm ERR! Invalid protocol: 10.1.220.1:
npm ERR!

[npm-debug.txt](https://github.com/npm/npm/files/475830/npm-debug.txt)

**Comment by legodude17** [comment]
Try updating npm with `npm install npm@latest`.
