### ISSUE TITLE
Featute request: npm install packagename@latest-non-breaking

### ISSUE THREAD

**Issue by mikemaccana** [npm/npm#13980]
Say:

 -  I have version `2.0.0` of `package-name` installed.
 - The latest minor version that has the same major version is `2.1.2`
 - The latest major version (which would be installed if I ran `npm install package-name@latest` is `4.3.0`

It would be useful to be able to run

    npm install package-name@latest-non-breaking

And have `2.1.2` installed, since that's the latest non-breaking upgrade according to semver.

**Comment by SimenB** [comment]
What's wrong with `npm install package-name@^2`?

**Comment by iarna** [comment]
You can make whatever custom tags you want:
```
npm dist-tag package-name@2.1.2 latest-non-breaking
```

Which can then be installed with:

```
npm install package-name@latest-non-breaking
```

And as SimenB points out, if your `package.json` has `^2` as its version then you'll not get any breaking changes with `npm install` or `npm update`.

**Comment by othiym23** [comment]
What @SimenB and @iarna said – this is exactly what `~` and `^` are for. Thanks for your time!

**Comment by mikemaccana** [comment]
**This is being proposed as a convenience shiortcut.** Yes, using additional commands works, this is faster 

 - @SimenB You have to bother looking up the current version

 - @iarna dist-tag is per package, you'd have to add it to every packages
