### ISSUE TITLE
Cannot install Cordova with npm

### ISSUE THREAD

**Issue by jeremysmartin399** [npm/npm#13981]
[npm-debug.txt](https://github.com/npm/npm/files/477393/npm-debug.txt)

#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [X] Other (_see below for feature requests_):

#### What's going wrong?

In the Node.js Command prompt, while running as Administrator, I type "npm install -g cordova". This fails and gives a proxy error. The proxy, https-proxy, registry, and strict-ssl settings all look correct. The proxy settings are in the format "http://[username]:[password]@[URL of proxy]:8080". I've attached the npm-debug.log file, which had to be changed to a txt file to upload. The "npm config list" command returns back settings that appear correct.

### supporting information:

 - `npm -v` prints: 3.10.6
 - `node -v` prints: v4.5.0
 - `npm config get registry` prints: http://proxy.pa.gov/
 - Windows, OS X, or Linux?: Windows 7 Professional with Service Pack 1
 - Network issues:
   - Geographic location where npm was run:
   - [X] I use a proxy to connect to the npm registry.
   - [X] I use a proxy to connect to the web.
   - [X] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by jeremysmartin399** [comment]
After trying everything with proxy settings, npm appears to be installing Cordova. The change was setting the proxy as below:

> npm config set proxy "http://domain%5Cusername:password@servername:port/"


http://stackoverflow.com/questions/25660936/using-npm-behind-corporate-proxy-pac

**Comment by KenanY** [comment]
Closing as resolved then.
