### ISSUE TITLE
NPM Packages Installing, but Not Showing Version Numbers on Command Line

### ISSUE THREAD

**Issue by darrenbrett** [npm/npm#13991]
I have Node installed on my mac, running OS X El Capitan 10.11.6. When I NPM install packages, like express, nodemon, etc, and run, for instance "nodemon -v", I get a "bash: suchandsuch: command not found" return on my command line. When I run "node -v" or "npm -v" there's no problem. The correct, installed versions are returned. But even though I get successful installation messages on the command line when installing other packages through npm - like nodemon, express, etc, I always get the same error "bash: suchandsuch: command not found". Is this a path issue? A permissions issue? What do I need to edit?

**Comment by darrenbrett** [comment]
```
Darrens-Air:~ darrenking$ npm install -g express
/Users/darrenking/.npm-packages/lib
└── express@4.14.0 

Darrens-Air:~ darrenking$ express -v
-bash: express: command not found
```

**Comment by KenanY** [comment]
@darrenbrett Have you added your global modules directory to your `PATH`?

**Comment by darrenbrett** [comment]
Hi KenanY. In the end I got it worked out, thanks. After much searching, this thread helped me resolve it: http://stackoverflow.com/questions/27475480/error-eacces-permission-denied-even-after-using-sudo/27475650#27475650
