### ISSUE TITLE
help!,install cordova error

### ISSUE THREAD

**Issue by as573991874** [npm/npm#13996]
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "cordova"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3

npm ERR! shasum check failed for /tmp/npm-29362-9a26dd69/registry.npmjs.org/cordova-app-hello-world/-/cordova-app-hello-world-3.10.0.tgz
npm ERR! Expected: e3825fc6ca950090a6a37437fcfb88c1622fd80e
npm ERR! Actual:   53117af876d88968a8656f6faa1114e710a282a7
npm ERR! From:     https://registry.npmjs.org/cordova-app-hello-world/-/cordova-app-hello-world-3.10.0.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

How can i do ?

**Comment by as573991874** [comment]
npm config set registry http://registry.cnpmjs.org 
npm info underscore

:)

**Comment by KenanY** [comment]
@as573991874 Have you tried running `npm cache clean`?

**Comment by as573991874** [comment]
@KenanY thanks, i install suss, when i use "npm config set registry http://registry.cnpmjs.org"
