### ISSUE TITLE
node update failed in windows

### ISSUE THREAD

**Issue by sahdev0** [npm/npm#14004]
```
npm WARN retry will retry, error on last attempt: Error: **EBUSY**: resource busy or
locked, rename 'C:\Users\User\AppData\Local\Temp\npm-6692-56d29952\registry.npm
js.org\forwarded\-\forwarded-0.1.0.tgz.3570176784' -> 'C:\Users\User\AppData\Loc
al\Temp\npm-6692-56d29952\registry.npmjs.org\forwarded\-\forwarded-0.1.0.tgz'
npm ERR! Windows_NT 6.1.7600

npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\User\\AppData\\R
oaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "update" "-g"

npm ERR! node v4.2.6
npm ERR! npm  v3.8.3
```

**npm ERR! tarball.destroy is not a function**

**Comment by KenanY** [comment]
@sahdev0 Does this also occur after a reboot? How about with a newer version of `npm`?

**Comment by sahdev0** [comment]
no i want to update my node.js for angularjs 2.0 application but while updating package in global environment it shows error for resource busy. Can fresh install of nodejs will fix this issue.

**Comment by KenanY** [comment]
You can update Node.js through the binaries found at <https://nodejs.org>.

**Comment by sahdev0** [comment]
I have updated **nodejs** to 6.6.0 but still getting same error. Here is full error message that i am getting

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or
 locked, rename 'C:\Users\User\AppData\Local\Temp\npm-7128-bf8c6636\registry.npm
js.org\delayed-stream\-\delayed-stream-1.0.0.tgz.2555766792' -> 'C:\Users\User\A
ppData\Local\Temp\npm-7128-bf8c6636\registry.npmjs.org\delayed-stream\-\delayed-
stream-1.0.0.tgz'
npm ERR! Windows_NT 6.1.7600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"

**npm ERR! node v6.6.0
npm ERR! npm  v3.10.3**

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

please help me...

**Comment by sahdev0** [comment]
my problem has been solved thanks guys for you kind response.

**Comment by vjammula** [comment]
@sahdev0 - How did you resolve? Please let me know... I have the same issue.
