### ISSUE TITLE
npm version fails if using shrinkwrap and command isn't executed at same level

### ISSUE THREAD

**Issue by AlexChesters** [npm/npm#14009]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [X] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
`npm version` fails if you are:
1. Using an `npm-shrinkwrap.json`
2. Running `npm version` from somewhere other than the same level as `npm-shrinkwrap.json`

#### How can the CLI team reproduce the problem?
1. `npm init -y`
2. `npm install express --save` (or any node module)
3. `npm shrinkwrap`
4. `mkdir src`
5. `cd src`
6. `npm version minor`

Gist of `npm-debug.log` file can be found [here](https://gist.github.com/AlexChesters/30de975e94950d33125b53cd92051df1)

### supporting information:

 - `npm -v` prints: `3.10.3`
 - `node -v` prints: `v6.5.0`
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 - Windows, OS X, or Linux?: OS X
 - Network issues:
   - Geographic location where npm was run: UK
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by lholmquist** [comment]
@AlexChesters i've tried to reproduce your issue with the steps provided, but everything works fine.

npm version : 3.10.8
node version: 6.5.0
macOS 10.12

**Comment by lholmquist** [comment]
@AlexChesters did you already run `git init` or it is under gits control before you did those steps?

when i walked through the steps above, my directory was not under git control

**Comment by lholmquist** [comment]
@AlexChesters @othiym23 ok,  i was able to reproduce,  it fails when the project is also a git project.  There error is trying to do a `git add` on the shirnkwrap.json file, but it doesn't see it since it is in another directory.  

I can probably send a PR for this

**Comment by lholmquist** [comment]
@AlexChesters @othiym23 the fix was pretty easy,  PR is here, https://github.com/npm/npm/pull/14143

**Comment by AlexChesters** [comment]
@lholmquist thanks, LGTM! :D
