### ISSUE TITLE
[Question] After publishing with a tag I no longer can publish to the main package with the same version

### ISSUE THREAD

**Issue by VladimirAmiorkov** [npm/npm#14000]
This may have been asked before but was not able to find the answer to it so excuse me if its duplicated. Feel free to directly close and redirect me.

#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [X] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
After publishing with a tag `next` a version of my package `1.0.8` I not cannot publish the same version to the "main" package `npm publish ...`. The current version of the "main" package on npm is 1.0.7 which is lower then the one I try to publish but for some reason it is interacting with the version of `@next` tag I published. How can I "move" the package from the `@next `tag to the main package on npm?

The error I get is:

> You cannot publish over the previously published version 1.0.8.

Here is some info from `npm info`:

```
'dist-tags': { latest: '1.0.7', next: '1.0.8' },
  versions: 
   [ '1.0.0',
     '1.0.1',
     '1.0.2',
     '1.0.3',
     '1.0.4',
     '1.0.5',
     '1.0.6',
     '1.0.7',
     '1.0.8' ],
```

It indeed seams I have to somehow move the `next` to the `latest`. Maybe npm publish next --tag latest

#### How can the CLI team reproduce the problem?

```
npm publish packagetgz@next
npm publish packagetgz
```

### supporting information:

 - `npm -v` prints: 2.15.6
 - `node -v` prints: 4.4.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X, or Linux?: OS X

**Comment by KenanY** [comment]
@VladimirAmiorkov How about `npm dist-tag add <pkg>@1.0.8 latest`?

**Comment by VladimirAmiorkov** [comment]
@KenanY That is exactly what I did and was just about to update this issue. For anyone reading this read [this](https://docs.npmjs.com/cli/dist-tag) section from the docs.
