### ISSUE TITLE
Can't upgrade npm to latest version

### ISSUE THREAD

**Issue by slashbrackets** [npm/npm#14015]
#### I'm opening this issue because:
Unable to upgrade to the latest version of NPM.

#### What's going wrong?
Every strategy I use to update npm always results in having version 1.4.9.  I'm in a Windows 10 environment and I have tried the following:
`Uninstall node then download and installed the latest. I end up with node version 6.6.0 but npm is 1.4.9.`

I've tried the following also and still ended up with 1.4.9:
`npm install npm -g`

`Test: Run npm -v. The version should be higher than 2.1.8.`

I've also tried the following and still ended up with 1.4.9:
`npm install npm@latest -g`

#### How can the CLI team reproduce the problem?
See above

### supporting information:
 - `npm -v` prints: 1.4.9
 - `node -v` prints: v6.6.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X, or Linux?: Windows 10
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
   - [x ] I use NPM at home on a home network with no proxy or internet connection issues.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@slashbrackets Maybe [this](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows) will help?

**Comment by slashbrackets** [comment]
That only helped partially. In the end I didn't need the upgrade too. And wow, this was a tough nut to crack. Essentially, I solved the issue.

where.exe npm 

That command revealed that there was an npm.exe under Chocolately. Which when I uninstalled node and re-installed it didn't matter. I would always endup with version 1.4.9 recognized in the command window. 

I solved by removing chocolatey and then uninstalling and re-installing nodejs. Now I have version 3.10.3 recognized in the command window. Now I can use the npm-windows-upgrade tool.

**Comment by MatheusBortolon** [comment]
Same problem here. But to resolve after having done update of npm using [npm-windows-upgrade](https://github.com/felixrieseberg/npm-windows-upgrade), it was only necessary to run choco uninstall npm.

**Comment by LouisWayne** [comment]
This is due to Chocolatey - to fix the issue, follow these steps:

1. Remove npm by the command: `choco uninstall npm`
2. Install `npm-windows-upgrade` by running command: `npm install --global --production npm-windows-upgrade` (more info: [https://github.com/felixrieseberg/npm-windows-upgrade](https://github.com/felixrieseberg/npm-windows-upgrade))
3. Run command: `npm-windows-upgrade`
4. Choose the latest npm version
5. Enjoy programming

**Comment by aswathykrishna18** [comment]
I'm having the same issue. Can't update npm. Still showing the same old version even after running the npm update commands.
I tried, 
1. npm i npm
2. npm install npm -g
3. npm install npm@latest -g
4. npm upgrade npm
and I get this response always - 'CALL "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\\node_modules\npm\bin\npm-cli.js" prefix -g' is not recognized as an internal or external command,
operable program or batch file.
+ npm@6.0.0
updated 1 package in 73.465s

**Comment by josuevalrob** [comment]
Same here for macOS High Sierra 10.13.4 

> MacBook-Pro:~ josue`$ npm -v`
> 5.6.0
> MacBook-Pro:~ josue$` npm i npm`
> npm WARN saveError ENOENT: no such file or directory, open '/Users/josue/package.json'
> npm WARN enoent ENOENT: no such file or directory, open '/Users/josue/package.json'
> npm WARN josue No description
> npm WARN josue No repository field.
> npm WARN josue No README data
> npm WARN josue No license field.
> 
> + npm@6.0.0

And

> MacBook-Pro:~ josue`$ sudo npm install npm -g`
> Password:
> /Users/josue/.npm-packages/bin/npm -> /Users/josue/.npm-packages/lib/node_modules/npm/bin/npm-cli.js
> /Users/josue/.npm-packages/bin/npx -> /Users/josue/.npm-packages/lib/node_modules/npm/bin/npx-cli.js
> + npm@6.0.0
> updated 1 package in 16.907s

And to check it at the end: 

> MacBook-Pro:~ josue`$ npm --version`
> 5.6.0

Node version: v10.0.0

**Comment by aswathykrishna18** [comment]
Uninstall node, Go to edit Environment Variables and just delete the 'comSpec' variable and install node again.

**Comment by legodude17** [comment]
@josuevalrob What is the result of `which npm`?
