### ISSUE TITLE
Node JS Install fail

### ISSUE THREAD

**Issue by nvnkmr12** [npm/npm#14016]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [ ] npm is producing an incorrect install.
- [ ] npm is doing something I don't understand.
- [x] Other (_see below for feature requests_):
### supporting information:
- `npm -v` prints:
- `node -v` prints:
- `npm config get registry` prints:
- Windows, OS X, or Linux?:
- Network issues:
  - Geographic location where npm was run:
  - [ ] I use a proxy to connect to the npm registry.
  - [ ] I use a proxy to connect to the web.
  - [ ] I use a proxy when downloading Git repos.
  - [ ] I access the npm registry via a VPN
  - [ ] I don't use a proxy, but have limited or unreliable internet access.
- Container:
  - [ ] I develop using Vagrant on Windows.
  - [ ] I develop using Vagrant on OS X or Linux.
  - [ ] I develop / deploy using Docker.
  - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by nvnkmr12** [comment]
![e](https://cloud.githubusercontent.com/assets/22315620/18661828/45da5c6e-7f35-11e6-9809-3adcdf085807.JPG)

[nodejs.zip](https://github.com/npm/npm/files/481890/nodejs.zip)

Hi Team,
I am facing attached error for Node Js.

Please help

**Comment by kevva** [comment]
Are you behind a proxy? Probably related to https://github.com/npm/npm/issues/11308.
