### ISSUE TITLE
blockapps-js installation failure

### ISSUE THREAD

**Issue by priyachakka** [npm/npm#14019]
Hi - I am getting this issue while installing blockapps-js on the Ubuntu.Can somebody will be able to help me with this .Thanks a lot for all your time.

npm install blockapps-js
npm ERR! Linux 4.4.0-36-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "blockapps-js"
npm ERR! node v5.12.0
npm ERR! npm  v3.8.6
npm ERR! code ENOSELF

npm ERR! Refusing to install blockapps-js as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

node_modules/npm-debug.log
-----------------------------------------
 verbose stack Error: Refusing to install blockapps-js as a dependency of itself
27 verbose stack     at checkSelf (/usr/lib/node_modules/npm/lib/install/validate-args.js:53:14)
27 verbose stack     at Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
27 verbose stack     at LOOP (/usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
27 verbose stack     at chain (/usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
27 verbose stack     at /usr/lib/node_modules/npm/lib/install/validate-args.js:16:5
27 verbose stack     at /usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
27 verbose stack     at Array.forEach (native)
27 verbose stack     at /usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
27 verbose stack     at Array.forEach (native)
27 verbose stack     at asyncMap (/usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
28 verbose cwd /home/priya1/node_modules
29 error Linux 4.4.0-36-generic
30 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "blockapps-js"
31 error node v5.12.0
32 error npm  v3.8.6
33 error code ENOSELF

**Comment by KenanY** [comment]
@priyachakka Is the `"name"` field of your `package.json` set to `"blockapps-js"`? If so, could you try changing it to something unique?

**Comment by KenanY** [comment]
Closing as abandoned.
