### ISSUE TITLE
npm-shrinkwrap doesn't work well with packages from GitHub

### ISSUE THREAD

**Issue by evoL** [npm/npm#14023]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [ ] npm is producing an incorrect install.
- [x] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
#### What's going wrong?

`npm shrinkwrap` fails to produce the `npm-shrinkwrap.json` file when all of the following criteria are met:
- **`node_modules` have been restored from the `npm-shrinkwrap.json` file.** By that I mean that `npm install` was ran with the `npm-shrinkwrap.json` file present and the `node_modules` directory absent.
- **`package.json` contains `github:` dependencies.** This **does not** apply for `git://` dependencies.
#### How can the CLI team reproduce the problem?

I created a fresh project with a single dependency without other dependencies. I picked [chroma.js](https://github.com/gka/chroma.js/), but any other package will cause the issue.
1. Add a dependency that points to GitHub using either the `user/repo` or `github:user/repo` syntax. Pointing a commit does not matter. Example:
   
   ```
   "chroma-js": "gka/chroma.js#d2c6d917df4ba2b87d8a740de116a0656bcbdfd5"
   ```
2. `npm install`
3. `npm shrinkwrap` — this will succeed.
4. Clear the `node_modules` directory. This is to simulate a fresh install.
5. `npm install`
6. `npm shrinkwrap` — this will fail. Here's the [npm-debug.log](https://gist.github.com/evoL/621f13905de3766e7102a9c2b014be2b) file.

**Workaround:** specify the dependency using fully resolved `git://` URLs. For the above example it would be `git://github.com/gka/chroma.js.git#d2c6d917df4ba2b87d8a740de116a0656bcbdfd5`.
### supporting information:
- `npm -v` prints: `3.10.8`
- `node -v` prints: `v6.6.0`
- `npm config get registry` prints: `https://registry.npmjs.org/`
- Windows, OS X, or Linux?: OS X (10.11.6)
- Network issues:
  - Geographic location where npm was run: Poland
  - [ ] I use a proxy to connect to the npm registry.
  - [ ] I use a proxy to connect to the web.
  - [ ] I use a proxy when downloading Git repos.
  - [ ] I access the npm registry via a VPN
  - [ ] I don't use a proxy, but have limited or unreliable internet access.
- Container:
  - [ ] I develop using Vagrant on Windows.
  - [ ] I develop using Vagrant on OS X or Linux.
  - [ ] I develop / deploy using Docker.
  - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by eugef** [comment]
Did you try `npm prune` before running shrinkwrap?

**Comment by evoL** [comment]
Sure I did, it didn't prune anything.

**Comment by eugef** [comment]
Prune helped me on node 5.9 but not on node 6.3
