### ISSUE TITLE
npm installing syntax is incorrect on windows 7

### ISSUE THREAD

**Issue by ajay121193** [npm/npm#14021]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [ ] npm is producing an incorrect install.
- [x] npm is doing something I don't understand.
- [x] Other (_see below for feature requests_):
### supporting information:
- `npm -v` prints:
- `node -v` prints:
- `npm config get registry` prints:
- Windows, OS X, or Linux?:
- Network issues:
  - Geographic location where npm was run:
  - [ ] I use a proxy to connect to the npm registry.
  - [ ] I use a proxy to connect to the web.
  - [ ] I use a proxy when downloading Git repos.
  - [ ] I access the npm registry via a VPN
  - [x] I don't use a proxy, but have limited or unreliable internet access.
- Container:
  - [x] I develop using Vagrant on Windows.
  - [ ] I develop using Vagrant on OS X or Linux.
  - [ ] I develop / deploy using Docker.
  - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by ajay121193** [comment]
When i Run command
npm insall -g cordova

it says
The syntax is incorrect
/f was unexpected at this time

here is the screenshot
![capture](https://cloud.githubusercontent.com/assets/16916022/18699407/e7943304-7fee-11e6-9af9-312ca71118f2.JPG)

**Comment by KenanY** [comment]
Never seen this before. A quick search shows that the error is coming from Windows, not `npm`. Are you using `cmd.exe`?

**Comment by ajay121193** [comment]
Yes i m using cmd.exe
