### ISSUE TITLE
Error: Cannot find module 'github-url-from-git'

### ISSUE THREAD

**Issue by jjayaraman** [npm/npm#14026]
I upgraded nodejs to latest version v6.6.0
After that I keep getting this error when I try to install any module.
This issue is already raised by others. I tried those answers even then it does not works.

**# Error logs**

C:\Jay\ajs2>npm install -g angular-cli
(node:17144) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent vers
ion.
(node:17144) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent vers
ion.
(node:17144) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent vers
ion.
(node:7220) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent versi
on.
(node:7220) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent versi
on.
(node:7220) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent versi
on.
(node:7220) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent versi
on.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "angular-cli"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'github-url-from-git'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Jay\ajs2\npm-debug.log

**Comment by dpchu** [comment]
Per this https://github.com/nodejs/node/issues/3540 i was able to resolve by deleting the 'npm' folder from the 'node_modules' folder.  Then reinstalled the nodejs installer and now it runs great!  Also, I'm running on OS X.

**Comment by praveen262k** [comment]
For me I did `npm cache clean` and did `npm purge && npm install`

**Comment by sirius2013** [comment]
I got same error after upgrade v6.10.0
![image](https://cloud.githubusercontent.com/assets/5020713/23930059/ef13f9d4-0964-11e7-84f2-4918d26c3cf9.png)

**Comment by legodude17** [comment]
@sirius2013 Try deleting and reinstalling `npm`.
