### ISSUE TITLE
NPM EPERM issue Antivirus

### ISSUE THREAD

**Issue by anand-ma** [npm/npm#14027]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [X] npm is producing an incorrect install.
- [ ] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
#### How can the CLI team reproduce the problem?

npm install -g ionic
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "ionic"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! path C:\Users\507644\AppData\Roaming\npm\node_modules\ionic
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\507644\AppData\Roaming\npm\node_modules\ionic' -> 'C:\Users\507644\AppData\Roaming\np
m\node_modules.ionic.DELETE'
npm ERR!     at moveAway (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:38:5)
npm ERR!     at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:27:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\507644\AppData\Roaming\npm\node_modules\ionic' -> 'C:\Users\507644\AppData\Roaming\np
m\node_modules.ionic.DELETE'
npm ERR!     at Error (native)
npm ERR!  Error: EPERM: operation not permitted, rename 'C:\Users\507644\AppData\Roaming\npm\node_modules\ionic' -> 'C:\Users\507644\AppData\Roaming\n
pm\node_modules.ionic.DELETE'
npm ERR!     at moveAway (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:38:5)
npm ERR!     at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:27:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\507644\AppData\Roaming\npm\node_modules\ionic' -> 'C:\Users\507644\AppData\Roaming\np
m\node_modules.ionic.DELETE'
npm ERR!     at Error (native)
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\507644\Workspace\ATT\attengagehome\npm-debug.log
### supporting information:

npm -v
3.10.3

node -v
v6.6.0
npm config get registry
https://registry.npmjs.org/

This issue is caused by Antivirus locking the file for scanning when npm tries to rename. My computer is 64bit.

I see the following code
function moveIntoPlace (folder, unpackTarget, cb) {
-  var start = Date.now()
-  fs.rename(folder, unpackTarget, function CB (er) {
-    if (er
-        && process.platform === "win32"
-        && er.code === "EACCES"
-        && Date.now() - start < 1000) {
-      return fs.rename(folder, unpackTarget, CB)
-    }
-    cb(er)
-  })
  +}

in the following file to fix AV issue 
https://github.com/npm/npm/commit/beeb7fd82e3cc543a9911fe87ec096f8eed29e7a
lib/utils/tar.js

But its still happening to me, is it because its not yet fixed for 64 bit computers?

**Comment by baconface** [comment]
`process.platform` for Windows will always be `win32` even if it is a 64 bit machine running 64 bit Windows.

**Comment by anand-ma** [comment]
@baconface thank you. but the issue is still happening to me. Do you have any suggestions? 

npm -v
3.10.3

node -v
v6.6.0

**Comment by anand-ma** [comment]
can someone help me?

**Comment by baconface** [comment]
I am not speaking on the behalf of NPM. But to be honest, I don't think there is much more NPM can do to interact with the file in use by a third party. Especially since this is being dictated by the operating system and not NPM itself.

Depending on your AV software you might either have to temporarily deactivate your AV when you perform an install or white list your NPM binary.
