### ISSUE TITLE
npm start not working

### ISSUE THREAD

**Issue by mj1930** [npm/npm#14022]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by mj1930** [comment]
npm start is not working properly.
 Linux 3.13.0-32-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v0.10.46
npm ERR! npm  v2.15.1

npm ERR! missing script: start
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mihirj/Desktop/testp/npm-debug.log
Shows this

**Comment by KenanY** [comment]
@mj1930 Do you have a `"start"` script defined in your `package.json`?

**Comment by OmeLeo** [comment]
Hi, I have exactly the same problem and i don't have anything defined in package.json cause I really dont known which script it should be; there are no js scripts in ~/homebridge (running on a raspberry)

pi@DomoticzPi:~/homebridge$ npm run start
npm ERR! Linux 4.1.18+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7

npm ERR! missing script: start
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/homebridge/npm-debug.log

Leo

**Comment by KenanY** [comment]
@OmeLeo You can't run `npm run start` without first defining a `"start"` script in your `package.json` (or a `server.js` in your current directory, in which case the default is `node server.js`). `npm` has no idea what you want it to do. I can't really say what you _should_ put there, since it is very specific to what you want to do.

**Comment by fizzvr** [comment]
`'packpage.json' `  add script: start

**Comment by OmeLeo** [comment]
Yeh, I was affraid for that answer. I think it's a bit silly to create a WiKi/HowTo for using the Siri Homekit in Domoticz without a proper working script. I haven't a clou what the script should be.

Guess I gonna quit this project...

Thxs anyway for the reply

Leo

**Comment by maikel076** [comment]
hi,

can somebody tell me please how i add the start script?

thxs

maikel

**Comment by KenanY** [comment]
@maikel076 Check out <https://docs.npmjs.com/misc/scripts>.

**Comment by maikel076** [comment]
@KenanY Thxs for the fast reaction!
