### ISSUE TITLE
fetch fails with 404 when trying to retrieve https://registry.npmjs.org/i/-/i-0.3.2.tgz against node4-lts

### ISSUE THREAD

**Issue by gortok** [npm/npm#14025]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Doing "npm" install on an ionic 1.7.12 project causes npm to fail to retrieve package. Here's the exact error message:
```
npm ERR! Please include the following file with any support request:
npm ERR!     /Users/gjstocker/src/jewelapp/npm-debug.log
MacBook-Pro-5:jewelapp gjstocker$ npm install
npm ERR! fetch failed https://registry.npmjs.org/i/-/i-0.3.2.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://registry.npmjs.org/i/-/i-0.3.2.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://registry.npmjs.org/i/-/i-0.3.2.tgz
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/node4-lts/4.2.4/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12

npm ERR! fetch failed with status code 404
npm ERR! 
```

#### How can the CLI team reproduce the problem?
   
   attempt to run `npm install` against a repo that previously worked with same npm/node version; the npm module that seems to be affected is `i`.

    gist to npm-debug.log file: https://gist.github.com/gortok/d90948ddaa82937341014c65d5780b66

### supporting information:

 - `npm -v` prints: 2.4.12
 - `node -v` prints: v4.2.4
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X, or Linux?: Mac OS X 10.10.5 (Yosemite)
 - Network issues:
   - Geographic location where npm was run: Northern Virginia.
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by gortok** [comment]
same issue was pointed out in #13826, but closed because they didn't provide an npm-debug.log.

**Comment by gortok** [comment]
Turns out it's because a package has been uninstalled at that version: https://www.npmjs.com/package/i.

Both local npm ls and global npm ls do not show that package as being a dependency anywhere; so I'm left asking: What is requiring this package in my dependencies and how do I find it? And why does a package missing (with a note to update) not trigger a *different* error than a straight 404? (I'd be happy to help implement that last part).

**Comment by KenanY** [comment]
I believe the dependency path is `ionic` -> `prompt` -> `utile` -> `i`.

**Comment by gortok** [comment]
@KenanY How did you figure that out? I've printed out both the dependency trees and was never able to find its usage.

**Comment by KenanY** [comment]
@gortok Looking through the `npm-debug.log`, it looks like the error starts soon after building `ionic/node_modules/prompt/node_modules/utile` and as it turns out `i` is a dependency of `utile`.

**Comment by KenanY** [comment]
Alternatively one could install a newer version of `ionic` and do `npm ls i` to observe the same dependency path.

**Comment by gortok** [comment]
This issue was caused by the package json asking for `ionic@1.3.0`, which depends on `i@0.3.2`.  Ionic 1.3.0 is the ionic-cli version number, not the ionic framework version number (oops).  I should have removed that from the package-json, and installed the latest version of ionic globally.
