### ISSUE TITLE
Feature Request: add a local npm_repo to save time during npm install

### ISSUE THREAD

**Issue by dpxxdp** [npm/npm#14024]
#### What's the feature?
Use some local directory, say `~/.npm_repo` as a local "npm repository".  `npm install` checks that directory first, if it finds the package-version that it needs, it just copies it rather than downloading it.  If it does not exist locally, it carries on to the interwebs as it would normally.

`~/.npm_repo` of course would not be on the node path for dependency resolution.  Nothing would ever use it.  Its obviously *not* where global node_modules live.  It would just be there for convenience during `npm install`  and `npm install -g` (though this likely wouldn't be as much of a time saver as you're not repeatedly globally installing the same packages).

#### What problem is the feature intended to solve?
`npm install` takes 120+ seconds to complete.  Whenever I switch branches I need to rerun npm install (since  `/node_modules` are `.gitignored`).  Those 120 seconds are just for an angular 2 starter project.  I only anticipate that this will grow as we develop a midsized enterprise application on top of it.  Each time I switch branches npm is spending time downloading the same packages time over time.

#### Is the absence of this feature blocking you or your team? If so, how?
It slows us down.  120+ seconds per branch switch per team member.

#### Is this feature similar to an existing feature in another tool?
Maven `~/.m2` repo.  Maven checks locally to see if you have a Java dependency before going to the maven online repository for it.

#### Is this a feature you're prepared to implement, with support from the npm CLI team?
Yes.

**Comment by KenanY** [comment]
@dpxxdp But `npm` already utilizes such a [cache](https://docs.npmjs.com/files/folders#cache)? (sorry if I am misunderstanding you)

**Comment by dpxxdp** [comment]
Closing this then, that's exactly what I was referring to.  I wonder why this still takes so long then.  I will dig into it, thanks!
