### ISSUE TITLE
npm start is not working

### ISSUE THREAD

**Issue by manikachhabra** [npm/npm#14039]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
    - [* ] Other (_see below for feature requests_):

#### What's going wrong?

whenever i run npm start command in cmd, i get error something like-

Failed at the npm@2.15.9 start script 'node my-app.js'.
This is most likely a problem with the npm package,
not with npm itself.
Tell the author that this fails on your system:
    node my-app.js
You can get information on how to open an issue for this project with:
    npm bugs npm
Or if that isn't available, you can get their info via:
    npm owner ls npm
There is likely additional logging output above.

#### How can the CLI team reproduce the problem?

I have read other issues related to npm start and have added "start":"node my-app.js" to the package.json file and yet the issue isn't resolved for me.

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@manikachhabra As the error log states, your `"start"` script is throwing an error. Have you tried running `node my-app.js` yourself (outside of `npm`)?

**Comment by manikachhabra** [comment]
Hi
Thankyou for such a quick response.
I have added the script" start":"node my-app.js" after reading one of the solutions provided on this website over the same issue as mine.
However, my purpose of running npm start is to actually start the http server so that i can run tableau web data connectors.

**Comment by heijmans** [comment]
@manikachhabra : can you run `node my-app.js` on your command line? This is important information for us to help you fix your issue. If you don't have a my-app.js file, then this will surely not work. npm doesn't include a web server, you should provide (or download or whatever) a JavaScript file that can be started with `npm start`.

**Comment by KenanY** [comment]
Closing as abandoned.
