### ISSUE TITLE
Can't install Angular-Cli says I need npm-debug

### ISSUE THREAD

**Issue by madblkman** [npm/npm#14033]
#### I'm opening this issue because:

- [ ] npm is crashing.
- [ ] npm is producing an incorrect install.
- [x]  npm is doing something I don't understand.
- [x] Other: won't install package

#### What's going wrong?

npm will not install angular-cli

#### How can the CLI team reproduce the problem?

try to install angular cli and look for error message about webpack issue

### supporting information:

 - `npm -v` prints: 3.10.8
 - `node -v` prints: v4.4.5
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X, or Linux?: macOS
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [x] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN.
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [x] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@madblkman A `npm-debug.log` file should be produced when an error occurs. Could you provide that log as a [gist](https://gist.github.com/)?

**Comment by madblkman** [comment]
There was one but I forgot to add it. I fixed the issue by uninstalling angular-cli and reinstalling it. So everything is all good on my end. Thanks for your prompt response though!
