### ISSUE TITLE
npm run typings install   not working

### ISSUE THREAD

**Issue by harrisssonz** [npm/npm#14034]
\\npm\\bin\\npm-cli.js" "run" "typings" "install"                                           
npm ERR! node v6.6.0                                                                        
npm ERR! npm  v3.10.3                                                                       
                                                                                            
npm ERR! missing script: typings                                                            
npm ERR!                                                                                    
npm ERR! If you need help, you may report this error at:                                    
npm ERR!     <https://github.com/npm/npm/issues>                                            
                                                                                            
npm ERR! Please include the following file with any support request:                        
npm ERR!     c:\Users\juan\Desktop\login\npm-debug.log

**Comment by KenanY** [comment]
@harrisssonz Do you have a `"typings"` script defined in your `package.json`? The error log is indicating that you do not, hence why `npm run typings` is throwing an error.

**Comment by heijmans** [comment]
@harrisssonz You probably want to run `npm install typings`.

**Comment by KenanY** [comment]
Closing as abandoned.
