### ISSUE TITLE
windows 8 : cmd: npm install -g ionic cordova , ERR! windows_NT 6.2.9200

### ISSUE THREAD

**Issue by YacineGHNIMI** [npm/npm#14040]
49552 silly mapToRegistry uri https://registry.npmjs.org/jsonpointer
49553 verbose addRemoteTarball https://registry.npmjs.org/jsonpointer/-/jsonpointer-2.0.0.tgz not in flight; adding
49554 verbose addRemoteTarball [ 'https://registry.npmjs.org/jsonpointer/-/jsonpointer-2.0.0.tgz',
49554 verbose addRemoteTarball   '3af1dd20fe85463910d469a385e33017d2a030d9' ]
49555 info retry fetch attempt 1 at 15:13:11
49556 info attempt registry request try #1 at 15:13:11
49557 http fetch GET https://registry.npmjs.org/jsonpointer/-/jsonpointer-2.0.0.tgz
49558 http fetch 200 https://registry.npmjs.org/generate-function/-/generate-function-2.0.0.tgz
49559 silly fetchAndShaCheck shasum 6858fe7c0969b7d4e9093337647ac79f60dfbe74
49560 verbose addTmpTarball C:\Users\YASSINE\AppData\Local\Temp\npm-1236-4ebd05d0\registry.npmjs.org\generate-function-\generate-function-2.0.0.tgz not in flight; adding
49561 verbose addTmpTarball already have metadata; skipping unpack for generate-function@2.0.0
49562 verbose correctMkdir C:\Dev\nodejs\npm-cache correctMkdir not in flight; initializing
49563 silly cache afterAdd generate-function@2.0.0
49564 verbose afterAdd C:\Dev\nodejs\npm-cache\generate-function\2.0.0\package\package.json not in flight; writing
49565 verbose correctMkdir C:\Dev\nodejs\npm-cache correctMkdir not in flight; initializing
49566 verbose afterAdd C:\Dev\nodejs\npm-cache\generate-function\2.0.0\package\package.json written
49567 http fetch 200 https://registry.npmjs.org/generate-object-property/-/generate-object-property-1.2.0.tgz
49568 silly fetchAndShaCheck shasum 9c0e1c40308ce804f4783618b937fa88f99d50d0
49569 verbose addTmpTarball C:\Users\YASSINE\AppData\Local\Temp\npm-1236-4ebd05d0\registry.npmjs.org\generate-object-property-\generate-object-property-1.2.0.tgz not in flight; adding
49570 verbose addTmpTarball already have metadata; skipping unpack for generate-object-property@1.2.0
49571 verbose correctMkdir C:\Dev\nodejs\npm-cache correctMkdir not in flight; initializing
49572 silly cache afterAdd generate-object-property@1.2.0
49573 verbose afterAdd C:\Dev\nodejs\npm-cache\generate-object-property\1.2.0\package\package.json not in flight; writing
49574 verbose correctMkdir C:\Dev\nodejs\npm-cache correctMkdir not in flight; initializing
49575 verbose afterAdd C:\Dev\nodejs\npm-cache\generate-object-property\1.2.0\package\package.json written
49576 http fetch 200 https://registry.npmjs.org/jsonpointer/-/jsonpointer-2.0.0.tgz
49577 warn retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\YASSINE\AppData\Local\Temp\npm-1236-4ebd05d0\registry.npmjs.org\jsonpointer-\jsonpointer-2.0.0.tgz.1632077964' -> 'C:\Users\YASSINE\AppData\Local\Temp\npm-1236-4ebd05d0\registry.npmjs.org\jsonpointer-\jsonpointer-2.0.0.tgz'
49578 verbose stack TypeError: tarball.destroy is not a function
49578 verbose stack     at WriteStreamAtomic.<anonymous> (C:\Users\YASSINE.node_module_global\node_modules\npm\lib\cache\add-remote-tarball.js:97:15)
49578 verbose stack     at emitOne (events.js:82:20)
49578 verbose stack     at WriteStreamAtomic.emit (events.js:169:7)
49578 verbose stack     at WriteStreamAtomic.emit (C:\Users\YASSINE.node_module_global\node_modules\npm\node_modules\fs-write-stream-atomic\index.js:60:34)
49578 verbose stack     at C:\Users\YASSINE.node_module_global\node_modules\npm\node_modules\fs-write-stream-atomic\index.js:89:19
49578 verbose stack     at FSReqWrap.oncomplete (fs.js:82:15)
49579 verbose cwd C:\Windows\system32
49580 error Windows_NT 6.2.9200
49581 error argv "C:\Program Files\nodejs\node.exe" "C:\Users\YASSINE\.node_module_global\node_modules\npm\bin\npm-cli.js" "install" "-g" "cordova" "ionic"
49582 error node v4.5.0
49583 error npm  v3.10.8
49584 error tarball.destroy is not a function
49585 error If you need help, you may report this error at:
49585 error     https://github.com/npm/npm/issues
49586 verbose exit [ 1, true ]

**Comment by msarm** [comment]
I got the same error as well... Any update?
