### ISSUE TITLE
Getting these errors when trying to install the node modules. FYI, command used here is -> npm install

### ISSUE THREAD

**Issue by SambitKumarPanda** [npm/npm#14053]
```
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ECONNREFUSED
npm ERR! errno ECONNREFUSED
npm ERR! syscall connect

npm ERR! Error: connect ECONNREFUSED 151.101.8.162:443
npm ERR!     at Object.exports._errnoException (util.js:860:11)
npm ERR!     at exports._exceptionWithHostPort (util.js:883:20)
npm ERR!     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
npm ERR!  { [Error: connect ECONNREFUSED 151.101.8.162:443]
npm ERR!   code: 'ECONNREFUSED',
npm ERR!   errno: 'ECONNREFUSED',
npm ERR!   syscall: 'connect',
npm ERR!   address: '151.101.8.162',
npm ERR!   port: 443,
npm ERR!   parent: 'microservicesapp' }
npm ERR!
npm ERR! If you are behind a proxy, please make sure that the
npm ERR! 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     D:\package folder\packageStructure\src\npm-debug.log
```

**Comment by KenanY** [comment]
@SambitKumarPanda Error log indicates that this is an issue with your internet connection and not with `npm` itself. Maybe you are behind a proxy or firewall?

**Comment by KenanY** [comment]
Closing as abandoned.

**Comment by jothiramanji** [comment]
npm ERR! code ECONNREFUSED
npm ERR! errno ECONNREFUSED
npm ERR! FetchError: request to https://registry.npmjs.org/@angular%2fcompiler failed, reason: connect ECONNREFUSED 151.101.8.162:443
npm ERR!     at ClientRequest.req.on.err (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\src\index.js:68:14)
npm ERR!     at ClientRequest.emit (events.js:159:13)
npm ERR!     at TLSSocket.socketErrorListener (_http_client.js:389:9)
npm ERR!     at TLSSocket.emit (events.js:159:13)
npm ERR!     at emitErrorNT (internal/streams/destroy.js:64:8)
npm ERR!     at process._tickCallback (internal/process/next_tick.js:152:19)
npm ERR!  { FetchError: request to https://registry.npmjs.org/@angular%2fcompiler failed, reason: connect ECONNREFUSED 151.101.8.162:443
npm ERR!     at ClientRequest.req.on.err (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\src\index.js:68:14)
npm ERR!     at ClientRequest.emit (events.js:159:13)
npm ERR!     at TLSSocket.socketErrorListener (_http_client.js:389:9)
npm ERR!     at TLSSocket.emit (events.js:159:13)
npm ERR!     at emitErrorNT (internal/streams/destroy.js:64:8)
npm ERR!     at process._tickCallback (internal/process/next_tick.js:152:19)
npm ERR!   message: 'request to https://registry.npmjs.org/@angular%2fcompiler failed, reason: connect ECONNREFUSED 151.101.8.162:443',
npm ERR!   type: 'system',
npm ERR!   errno: 'ECONNREFUSED',
npm ERR!   code: 'ECONNREFUSED',
npm ERR!   stack: 'FetchError: request to https://registry.npmjs.org/@angular%2fcompiler failed, reason: connect ECONNREFUSED 151.101.8.162:443\n    at ClientRequest.req.on.err (C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\pacote\\node_modules\\make-fetch-happen\\node_modules\\node-fetch-npm\\src\\index.js:68:14)\n    at ClientRequest.emit (events.js:159:13)\n    at TLSSocket.socketErrorListener (_http_client.js:389:9)\n    at TLSSocket.emit (events.js:159:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)',
npm ERR!   parent: 'angular-quickstart' }
npm ERR!
npm ERR! If you are behind a proxy, please make sure that the
npm ERR! 'proxy' config is set properly.  See: 'npm help config'
