### ISSUE TITLE
npm install hangs on extract step

### ISSUE THREAD

**Issue by nbarbettini** [npm/npm#14059]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [x] npm is producing an incorrect install.
- [ ] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
#### What's going wrong?

On both Windows 8 and Windows 10, npm hangs when installing the [stormpath-sdk-angularjs](https://www.npmjs.com/package/stormpath-sdk-angularjs) module. It always hangs on this step:

```
[             .....] \ extract:stormpath-sdk-angularjs: sill gunzTarPerm modified mode [ '.tmp/build/stormpath-sdk-angularjs.tpls.min.js
```

One core is pegged at 100% and the process must be killed manually. It sounds very similar to https://github.com/npm/npm/issues/13782, but I'm not on Linux and I already have v6.6.0.
#### How can the CLI team reproduce the problem?

On Windows 8 or Windows 10, with the latest node and npm,

```
npm -ddd i stormpath-sdk-angularjs 2> log.txt
```

Log of above: https://gist.github.com/nbarbettini/f921e45641a67c9eb5d6a6dea028ed0c

I can grab any other logs or debug info as needed.
### supporting information:
- `npm -v` prints: 3.10.8
- `node -v` prints: 6.6.0
- `npm config get registry` prints: https://registry.npmjs.org/
- Windows, OS X, or Linux?: Windows

**Comment by Doug-Shannon** [comment]
I am having this exact same issue.

**Comment by Doug-Shannon** [comment]
Is there any movement on this?

**Comment by Husamuddin** [comment]
the same here

**Comment by legodude17** [comment]
Can someone give a repro for this?

**Comment by nbarbettini** [comment]
@legodude17 What else can I provide beyond the steps in my initial comment?

**Comment by legodude17** [comment]
Does any other package do this? Try installing some other packages, and then installing some package with a huge file.

**Comment by nbarbettini** [comment]
I haven't been able to replicate this with any other package, no. This one replicates it consistently, though. @Doug-Shannon have you seen any other packages that fail with this error?

**Comment by emkman** [comment]
Same issue but different packages. Gets stuck on a  different package each time, but always the extract step:
`[                ..] \ extract:natural: sill gunzTarPerm extractEntry library/fn/number/max-safe-integer.js`
AWS EC2 with Amazon AMI 2016.03 and node 6.9.4. Pegs the CPU and hangs my ssh connection.

**Comment by legodude17** [comment]
Is it always `library/fn/number/max-safe-integer.js`? Or are there different file paths?

**Comment by emkman** [comment]
Different every time, here was another one
`[             ..] | extract:uws: sill gunzTarPerm modified mode [ 'clients/kinesisanalytics.js', 438, 436 ]`

I restarted the instance and ran `npm cache clean` followed by `npm install` and then it succeeded

**Comment by emkman** [comment]
Those nodes are now fine but I am able to reproduce this on another node. What info can I capture to help debug the issue?

**Comment by legodude17** [comment]
What is the package.json? What is `npm config get proxy`? What is `npm cache ls`?

**Comment by brickcap** [comment]
Hangs for me as well with package `zxcvbn`  when I do `sudo npm install` from my terminal

I'm using Node v6.9.0 and npm v3.10.8. Both node and npm were installed with nvm.

**Comment by legodude17** [comment]
@brickcap Same question as above.

**Comment by ghost** [comment]
[Here's](https://pastebin.com/UgGuY67t) my package.json file

**Comment by AleksandarSavic95** [comment]
I had the same issue and the problem was that I didn't set the proxy correctly.
I was typing `npm set config proxy http://x.y:port` **instead of `npm config set proxy http://x.y:port`**
After that, npm install ran OK.

**Comment by bostjanpisler** [comment]
Had the same issue, for me the problem was solved by adding `http://` to proxy address.

**Comment by mchl-hub** [comment]
I was truly amazed when I've learned that so many people have that problem, because install is so basic that even npm should be good enough to proceed. I was able to solve the issue in two ways.
First is simple one because you can use **yarn** and I really recommend that reliable solution.
Second one is both interesting and hilarious at the same time, but still my second favourite. What you have to do is `npm config set registry http://registry.npmjs.org/` (change to **HTTP**) and then `npm install` which now should work just fine. After all you can `npm config set registry https://registry.npmjs.org/` (change to HTTPS) and install still works event when you remove node_modules and install again.
There is only one thing to mention, that the problem we are referring is not a recent one, not at all, and probably that's why we all love npm so much. Peace!

PS. @brickcap please do not put so much log into conversation, you sir, did make this topic much more difficult to read

**Comment by ghost** [comment]
@mchl-hub Apologies for making the topic unreadable and thanks for the suggestion. I've moved the contents to a pastebin file. Now it should be much more readable. 

Thanks,
Akshat

**Comment by ithieund** [comment]
I'm facing with the same problem here :(

Is there any fix?
