### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by Gurjot-Singh-PAU** [npm/npm#14055]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [x] npm is producing an incorrect install.
- [ ] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
### supporting information:
- `npm -v` prints:
- `node -v` prints:
- `npm config get registry` prints:
- Windows, OS X, or Linux?:
- Network issues:
  - Geographic location where npm was run:
  - [ ] I use a proxy to connect to the npm registry.
  - [ ] I use a proxy to connect to the web.
  - [ ] I use a proxy when downloading Git repos.
  - [ ] I access the npm registry via a VPN
  - [ ] I don't use a proxy, but have limited or unreliable internet access.
- Container:
  - [ ] I develop using Vagrant on Windows.
  - [ ] I develop using Vagrant on OS X or Linux.
  - [ ] I develop / deploy using Docker.
  - [ ] I deploy to a PaaS (Triton, Heroku).

![error](https://cloud.githubusercontent.com/assets/22343720/18787779/ed588612-81c1-11e6-8e08-30e0c6fc287a.PNG)

**Comment by KenanY** [comment]
@Gurjot-Singh-PAU Error log indicates that you do not have a `package.json` in your current directory. Running `npm install` with no arguments will not work unless you define some dependencies using a `package.json`. What are you _expecting_ `npm` to do here?

**Comment by Gurjot-Singh-PAU** [comment]
sir, what should i do to install nodejs

**Comment by KenanY** [comment]
@Gurjot-Singh-PAU Looks like you already have Node.js installed, since you are running `npm` with it :)

**Comment by Gurjot-Singh-PAU** [comment]
![capture](https://cloud.githubusercontent.com/assets/22343720/18787919/84a96c02-81c2-11e6-8467-a2c7ba74f5cb.PNG)
sorry

**Comment by Gurjot-Singh-PAU** [comment]
![error-screen-shot](https://cloud.githubusercontent.com/assets/22343720/18787977/bbaffa54-81c2-11e6-84fe-bc8ec4ed98ff.PNG)
i am getting this error please help me to sort it out

**Comment by Gurjot-Singh-PAU** [comment]
sir how can i define dependencies as you have suggested?

**Comment by Gurjot-Singh-PAU** [comment]
???

**Comment by fundon** [comment]
Same as https://github.com/npm/npm/issues/8872.

**Comment by Gurjot-Singh-PAU** [comment]
not able to get it..

**Comment by KenanY** [comment]
@Gurjot-Singh-PAU Regarding specifying dependencies, I recommend you read [this](https://docs.npmjs.com/getting-started/using-a-package.json#specifying-packages). Won't help with your certificate error I'm afraid.
