### ISSUE TITLE
npm ERR! No name provided in package.json

### ISSUE THREAD

**Issue by nitish1986** [npm/npm#14056]
I'm trying to use `gulp` for my stylesheet and scripts as instructed in the documentation of `laravel 5.3`, I tried installing

    npm install --no-bin-links

but I'm getting error:

    npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
    npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14

Even I tried

    npm install -g

I'm getting error:

    npm ERR! addLocal Could not install C:\wamp\www\NitsEdit
    npm ERR! Windows_NT 10.0.14393
    npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g"
    npm ERR! node v6.6.0
    npm ERR! npm  v3.10.3

    npm ERR! No name provided in package.json
    npm ERR!
    npm ERR! If you need help, you may report this error at:
    npm ERR!     <https://github.com/npm/npm/issues>

    npm ERR! Please include the following file with any support request:
    npm ERR!     C:\wamp\www\NitsEdit\npm-debug.log

I've installed `node.js` and `npm` to the latest version which I downloaded:

    node -v
        v6.6.0
    npm -v
        3.10.3

My `package.json` file contains:

    {
      "private": true,
      "scripts": {
        "prod": "gulp --production",
        "dev": "gulp watch"
      },
      "devDependencies": {
        "bootstrap-sass": "^3.3.7",
        "gulp": "^3.9.1",
        "jquery": "^3.1.0",
        "laravel-elixir": "^6.0.0-9",
        "laravel-elixir-vue": "^0.1.4",
        "laravel-elixir-webpack-official": "^1.0.2",
        "lodash": "^4.14.0",
        "vue": "^1.0.26",
        "vue-resource": "^0.9.3"
      }
    }

My `npm-debug.log` file has:

	0 info it worked if it ends with ok
	1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
	1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
	1 verbose cli   'install',
	1 verbose cli   '-g' ]
	2 info using npm@3.10.3
	3 info using node@v6.6.0
	4 silly loadCurrentTree Starting
	5 silly install loadCurrentTree
	6 silly install readGlobalPackageData
	7 silly fetchPackageMetaData .
	8 silly fetchDirectoryPackageData .
	9 silly install normalizeTree
	10 silly loadCurrentTree Finishing
	11 silly loadIdealTree Starting
	12 silly install loadIdealTree
	13 silly cloneCurrentTree Starting
	14 silly install cloneCurrentTreeToIdealTree
	15 silly cloneCurrentTree Finishing
	16 silly loadShrinkwrap Starting
	17 silly install loadShrinkwrap
	18 silly loadShrinkwrap Finishing
	19 silly loadAllDepsIntoIdealTree Starting
	20 silly install loadAllDepsIntoIdealTree
	21 silly resolveWithNewModule !invalid#1 checking installable status
	22 silly cache add args [ '.', null ]
	23 verbose cache add spec .
	24 silly cache add parsed spec Result {
	24 silly cache add   raw: '.',
	24 silly cache add   scope: null,
	24 silly cache add   escapedName: null,
	24 silly cache add   name: null,
	24 silly cache add   rawSpec: '.',
	24 silly cache add   spec: 'C:\\wamp\\www\\NitsEdit',
	24 silly cache add   type: 'directory' }
	25 error addLocal Could not install C:\wamp\www\NitsEdit
	26 silly rollbackFailedOptional Starting
	27 silly rollbackFailedOptional Finishing
	28 silly runTopLevelLifecycles Starting
	29 silly runTopLevelLifecycles Finishing
	30 silly install printInstalled
	31 verbose stack Error: No name provided in package.json
	31 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\cache\add-local.js:65:17
	31 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:356:5
	31 verbose stack     at checkBinReferences_ (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:320:45)
	31 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:354:3)
	31 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:124:5)
	31 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:311:12
	31 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
	31 verbose stack     at tryToString (fs.js:455:3)
	31 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
	32 verbose cwd C:\wamp\www\NitsEdit
	33 error Windows_NT 10.0.14393
	34 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g"
	35 error node v6.6.0
	36 error npm  v3.10.3
	37 error No name provided in package.json
	38 error If you need help, you may report this error at:
	38 error     <https://github.com/npm/npm/issues>
	39 verbose exit [ 1, true ]

I'm stuck with this, help me out

Thanks.

**Comment by KenanY** [comment]
@nitish1986 This:

```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
```

Is not an error, but a warning. You should be able to safely ignore it, since it is regarding an _optional_ dependency which only supports macOS.

Also do note that `npm install -g` will install your current package globally. But, you do not have a `"name"` field in your `package.json`, hence you are trying to install something which isn't really a package by definition. Hence the error.

**Comment by Gyingguo** [comment]
just add name value
