### ISSUE TITLE
angular 2 npm ERR! Windows_NT 10.0.10240

### ISSUE THREAD

**Issue by Jaxa9697** [npm/npm#14058]
```
npm WARN package.json angular-2@1.0.0 No repository field.
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.4.2
npm ERR! npm  v2.15.0

npm ERR! shasum check failed for C:\Users\JAHONG~1\AppData\Local\Temp\npm-1588-a9076f67\registry.npmjs.org\angular2\-\angular2-2.0.0-beta.13.tgz
npm ERR! Expected: e6b381345c958c57a4bd8bc7a29a1805983d040a
npm ERR! Actual:   b325265e7c5dfa56eac132cba7dc2c49166753ce
npm ERR! From:     https://registry.npmjs.org/angular2/-/angular2-2.0.0-beta.13.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\JAHONGIR-PC\WebstormProjects\Angular2\npm-debug.log

```

**Comment by KenanY** [comment]
@Jaxa9697 Have you tried running `npm cache clean`? Does this also occur with the latest stable version of `npm`?

**Comment by Jaxa9697** [comment]
Yeah it also occur with the latest stable version of npm. First I try on node version 5 and I take this issue, then I change my node to your version( that you record in video) 4.4.2. Unfortunately I take same issue. About npm cache clean I didnt try.

**Comment by KenanY** [comment]
For whatever reason, the shasum of the downloaded package doesn't match the shasum the registry says it should be. Might be a sign that someone/something is modifying the package (maliciously? mistakenly?) mid-download.

**Comment by KenanY** [comment]
@Jaxa9697 Still seeing this?

**Comment by KenanY** [comment]
Closing as abandoned.
