### ISSUE TITLE
Invalid name: "@types/q"

### ISSUE THREAD

**Issue by akbar-10p** [npm/npm#14050]
I am getting this issue on updating protractor to 4.0.9 version.
My current version is 4.0.4

C:\Users\akber>npm -g update protractor
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "-g" "update" "protractor"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9

npm ERR! Invalid name: "@types/q"
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\akber\npm-debug.log

[npm-debug.docx](https://github.com/npm/npm/files/489009/npm-debug.docx)

**Comment by tilmanpotthof** [comment]
I had the same problem. An update of npm to 3.10.8 fixed the problem: `npm install -g npm`

**Comment by akbar-10p** [comment]
Thanks @tilmanpotthof  my issue is resolved
