### ISSUE TITLE
I can't install gulp on fresh macOS Sierra

### ISSUE THREAD

**Issue by Krystus** [npm/npm#14052]
I have fresh installation of macOS Sierra. When I try:

> sudo npm install --global gulp-cli

I get lot's of errors "uid must be an unsigned int".

![screen shot 2016-09-23 at 13 48 55](https://cloud.githubusercontent.com/assets/15039636/18784759/85b7f240-8194-11e6-98ff-f1fad13f5676.png)

**Comment by astromac** [comment]
Same error, newer version of node.

```
npm ERR! uid must be an unsigned int
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "update" "-g"
npm ERR! node v6.6.0
```
npm ERR! npm  v3.10.8

**Comment by KenanY** [comment]
See https://github.com/npm/npm/issues/14047#issuecomment-249099655.

**Comment by emmafar** [comment]
Can't install all global package T_T
