### ISSUE TITLE
Installation Issue 

### ISSUE THREAD

**Issue by rls1955** [npm/npm#14069]
Having an issue trying to install the demo on MAC Yosemite using node v6.6.0 and npm v3.10.3.
The main issues seems to be "Refusing to install nge-datepicker as a dependency of itself". This is the first time I have seen this error. Also, when doing "npm start" it says "cannot find script "start" which is NOT in the package.son file but is present in other ng2 package.son files. At the end I have included the npm-debug.log file output.

Other installs of ng2 related code have installed ok. 
Here is the output:
"npm install ng2-datepicker --save
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "ng2-datepicker" "--save"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! code ENOSELF

npm ERR! Refusing to install ng2-datepicker as a dependency of itself
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:

======= npm-debug.log=========
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.10.3
3 info using node@v6.6.0
4 verbose stack Error: missing script: start
4 verbose stack     at run (/usr/local/lib/node_modules/npm/lib/run-script.js:151:19)
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/run-script.js:61:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:356:5
4 verbose stack     at checkBinReferences_ (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:320:45)
4 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:354:3)
4 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:124:5)
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:243:12
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
4 verbose stack     at tryToString (fs.js:455:3)
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
5 verbose cwd /Users/randysmith/Documents/ng2-datepicker-master-5
6 error Darwin 14.5.0
7 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
8 error node v6.6.0
9 error npm  v3.10.3
10 error missing script: start
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

Thanks Randy

**Comment by KenanY** [comment]
```
npm ERR! Refusing to install ng2-datepicker as a dependency of itself
```

Make sure the `"name"` property in your `package.json` is not set to `"ng2-datepicker"`. Make it unique!

```
10 error missing script: start
```

There has to be a `"start"` script in the `package.json` in your current directory.

**Comment by rls1955** [comment]
Thanks for the reply KenanY.
Changing the name solved the "dependency of itself" issue.
This is a great looking date picker but still have the problem with the "start" script. I have no idea what to add there. I have used "start" scripts from other packages that worked for them but none worked for this date picker. Granted I am new at Angular 2 with node and npm so the Readme file is where I look. The Readme file only gives instructions for installation.
So, I have been doing:
npm install
then 
npm start 
to get things working with other packages but still having these issues.
Thanks,
Randy

**Comment by KenanY** [comment]
@rls1955 Probably best to ask the author of that module or other Angular users on a forum or IRC channel somewhere. This issue tracker is for `npm` bugs/feature-requests.
