### ISSUE TITLE
When i am trying to install cordova using node v6.6.0 i have get error

### ISSUE THREAD

**Issue by prashant-thakar** [npm/npm#14065]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

```
npm install -g cordova
error Windows_NT 6.1.7601
 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\278759\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova"
error node v6.6.0
error npm  v3.10.8
error shasum check failed for C:\Users\278759\AppData\Local\Temp\npm-6292-14b9bd5b\registry.npmjs.org\bplist-parser\-\bplist-parser-0.1.1.tgz
error Expected: d60d5dcc20cba6dc7e1f299b35d3e1f95dafbae6
error Actual:   df54fcbc6697ebf224253e46f60812ebdce78e5b
error From:     https://registry.npmjs.org/bplist-parser/-/bplist-parser-0.1.1.tgz
error If you need help, you may report this error at:
error     <https://github.com/npm/npm/issues>
```

**Comment by KenanY** [comment]
@prashant-thakar Have you tried running `npm cache clean`?

**Comment by prashant-thakar** [comment]
yes; i have tried npm cache clean

**Comment by prashant-thakar** [comment]
is it some thing related to firewall or antivirus ?

**Comment by KenanY** [comment]
@prashant-thakar Maybe, does this occur with all packages?

**Comment by prashant-thakar** [comment]
No. It for only Cordova command. Other are working fine

**Comment by prashant-thakar** [comment]
Hi, problem is resolved. It's due to behind proxy. I have remove proxy and it's work fine
