### ISSUE TITLE
when ran $ionic platform add android get error:cannot find module 'config-chain' please help me

### ISSUE THREAD

**Issue by sandy-01** [npm/npm#14064]
![error](https://cloud.githubusercontent.com/assets/16624207/18806603/79facde0-824f-11e6-996c-2661936e08e9.jpg)

**Comment by KenanY** [comment]
It's unclear to me whether or not `npm` is the one throwing the error here. Does this also occur after reinstalling `npm` and `ionic`? Is there any way to get debug output from the command you are running?

**Comment by sandy-01** [comment]
@KenanY  : no i confuse still i didnt get the solution. i tried to reinstall npm and ionic

**Comment by KenanY** [comment]
I'm not sure what more can be done here, unfortunately, without a proper `npm-debug.log` file (which would confirm that this error is at least partially related to `npm`).

**Comment by KenanY** [comment]
Closing since this doesn't appear to be an issue with `npm`. Can reopen if this is demonstrated to be otherwise.
