### ISSUE TITLE
Issue with NPM start

### ISSUE THREAD

**Issue by Chiholiu** [npm/npm#14067]
$ npm start
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\chiho\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.8

npm ERR! missing script: start
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\chiho\Desktop\app\node_modules\angular\npm-debug.log

**Comment by Chiholiu** [comment]
NPM-debug.log

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\chiho\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.8
3 info using node@v4.5.0
4 verbose stack Error: missing script: start
4 verbose stack     at run (C:\Users\chiho\AppData\Roaming\npm\node_modules\npm\lib\run-script.js:151:19)
4 verbose stack     at C:\Users\chiho\AppData\Roaming\npm\node_modules\npm\lib\run-script.js:61:5
4 verbose stack     at C:\Users\chiho\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:356:5
4 verbose stack     at checkBinReferences_ (C:\Users\chiho\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:320:45)
4 verbose stack     at final (C:\Users\chiho\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:354:3)
4 verbose stack     at then (C:\Users\chiho\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:124:5)
4 verbose stack     at C:\Users\chiho\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:243:12
4 verbose stack     at C:\Users\chiho\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
5 verbose cwd C:\Users\chiho\Desktop\app\node_modules\angular
6 error Windows_NT 6.3.9600
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\chiho\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
8 error node v4.5.0
9 error npm  v3.10.8
10 error missing script: start
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

**Comment by Chiholiu** [comment]
Package.json

{
  "name": "angular",
  "version": "1.5.8",
  "description": "HTML enhanced for web apps",
  "main": "index.js",
  "private": true,
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/Chiholiu/angular.git"
  },
  "keywords": [
    "angular",
    "framework",
    "browser",
    "client-side"
  ],
  "author": "Angular Core Team <angular-core+npm@google.com>",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/angular/angular.js/issues"
  },
  "homepage": "http://angularjs.org",
  "_shasum": "925a5392b8c212d09572dc446db7e01264e094cb",
  "_from": "angular@>=1.5.8 <2.0.0",
  "_npmVersion": "2.15.8",
  "_nodeVersion": "4.4.7",
  "_npmUser": {
    "name": "angularcore",
    "email": "angular-core+npm@google.com"
  },
  "dist": {
    "shasum": "925a5392b8c212d09572dc446db7e01264e094cb",
    "tarball": "https://registry.npmjs.org/angular/-/angular-1.5.8.tgz"
  },
  "maintainers": [
    "angularcore <angular-core+npm@google.com>",
    "petebd <pete@bacondarwin.com>"
  ],
  "_npmOperationalInternal": {
    "host": "packages-16-east.internal.npmjs.com",
    "tmp": "tmp/angular-1.5.8.tgz_1469201394611_0.9924397475551814"
  },
  "directories": {},
  "_resolved": "https://registry.npmjs.org/angular/-/angular-1.5.8.tgz"
}

**Comment by KenanY** [comment]
@Chiholiu You do not have a `"start"` script defined in your `package.json`. You can define one like so:

``` json
{
  ...
  "scripts": {
    "start": "enter commands here",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  ...
}
```
