### ISSUE TITLE
NPM install Failure

### ISSUE THREAD

**Issue by jajoh143** [npm/npm#14063]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [* ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Following code is being run from Windows CMD as Admin:

<samp>C:\Windows\System32>npm install npm </samp>

Only produces the following  output:

<samp>/</samp>

I run Node.JS on both my personal laptop and work tower, and have never had this problem. Have tried reinstalling earlier versions, edited the environment variables, turning off firewalls (<b>Temporarily</b>) and edited the file location where Node is located.

#### How can the CLI team reproduce the problem?
Am running Node from a x64 Windows 10 Tower PC, with a strong Internet connection.

No log has been generated, which is the reason I am reaching out here, as I'm unsure what steps further to take in personal debugging. 

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@jajoh143 How about `npm install -ddd npm`?

**Comment by jajoh143** [comment]
@KenanY , I wrote the command and received the following output.

Code:
<samp>
C:\WINDOWS\system32>npm install -ddd npm
npm info it worked if it ends with ok
npm verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'install',
npm verb cli   '-ddd',
npm verb cli   'npm' ]
npm info using npm@2.15.9
npm info using node@v4.5.0
npm verb install initial load of C:\WINDOWS\system32\package.json
npm verb readDependencies loading dependencies from C:\WINDOWS\system32\package.json
npm sill cache add args [ 'npm', null ]
npm verb cache add spec npm
npm sill cache add parsed spec Result {
npm sill cache add   raw: 'npm',
npm sill cache add   scope: null,
npm sill cache add   name: 'npm',
npm sill cache add   rawSpec: '',
npm sill cache add   spec: 'latest',
npm sill cache add   type: 'tag' }
npm sill addNamed npm@latest
npm verb addNamed "latest" is being treated as a dist-tag for npm
npm info addNameTag [ 'npm', 'latest' ]
npm sill mapToRegistry name npm
npm sill mapToRegistry using default registry
npm sill mapToRegistry registry https://registry.npmjs.org/
npm sill mapToRegistry data Result {
npm sill mapToRegistry   raw: 'npm',
npm sill mapToRegistry   scope: null,
npm sill mapToRegistry   name: 'npm',
npm sill mapToRegistry   rawSpec: '',
npm sill mapToRegistry   spec: 'latest',
npm sill mapToRegistry   type: 'tag' }
npm sill mapToRegistry uri https://registry.npmjs.org/npm
npm verb addNameTag registry:https://registry.npmjs.org/npm not in flight; fetching
npm verb request uri https://registry.npmjs.org/npm
npm verb request no auth needed
npm info attempt registry request try #1 at 10:47:51 PM
npm verb request id abb18af0d83b3f1a
npm verb etag "DI1XP96AU7UDZ40G4YDDREIAZ"
npm http request GET https://registry.npmjs.org/npm
npm http 304 https://registry.npmjs.org/npm
npm verb headers { date: 'Sat, 24 Sep 2016 03:47:23 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   'cache-control': 'max-age=300',
npm verb headers   etag: '"DI1XP96AU7UDZ40G4YDDREIAZ"',
npm verb headers   age: '300',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-ord1745-ORD',
npm verb headers   'x-cache': 'HIT',
npm verb headers   'x-cache-hits': '3',
npm verb headers   'x-timer': 'S1474688843.965408,VS0,VE0',
npm verb headers   vary: 'Accept-Encoding' }
npm sill get cb [ 304,
npm sill get   { date: 'Sat, 24 Sep 2016 03:47:23 GMT',
npm sill get     via: '1.1 varnish',
npm sill get     'cache-control': 'max-age=300',
npm sill get     etag: '"DI1XP96AU7UDZ40G4YDDREIAZ"',
npm sill get     age: '300',
npm sill get     connection: 'keep-alive',
npm sill get     'x-served-by': 'cache-ord1745-ORD',
npm sill get     'x-cache': 'HIT',
npm sill get     'x-cache-hits': '3',
npm sill get     'x-timer': 'S1474688843.965408,VS0,VE0',
npm sill get     vary: 'Accept-Encoding' } ]
npm verb etag https://registry.npmjs.org/npm from cache
npm verb get saving npm to C:\Users\Jake\AppData\Roaming\npm-cache\registry.npmjs.org\npm\.cache.json
npm verb correctMkdir C:\Users\Jake\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
npm sill addNameTag next cb for npm with tag latest
npm sill addNamed npm@3.10.8
npm verb addNamed "3.10.8" is a plain semver version for npm
npm sill mapToRegistry name npm
npm sill mapToRegistry using default registry
npm sill mapToRegistry registry https://registry.npmjs.org/
npm sill mapToRegistry data Result {
npm sill mapToRegistry   raw: 'npm',
npm sill mapToRegistry   scope: null,
npm sill mapToRegistry   name: 'npm',
npm sill mapToRegistry   rawSpec: '',
npm sill mapToRegistry   spec: 'latest',
npm sill mapToRegistry   type: 'tag' }
npm sill mapToRegistry uri https://registry.npmjs.org/npm
npm verb addRemoteTarball https://registry.npmjs.org/npm/-/npm-3.10.8.tgz not in flight; adding
npm verb addRemoteTarball [ 'https://registry.npmjs.org/npm/-/npm-3.10.8.tgz',
npm verb addRemoteTarball   '8f76ff8c6da04b61dd371d554ce40a0b8916c15e' ]
\
</samp>

**Comment by reggi** [comment]
@KenanY what does the `-ddd` flag do?

**Comment by kenany** [comment]
@reggi Basically increases verbosity. See <https://docs.npmjs.com/misc/config#shorthands-and-other-cli-niceties>
