### ISSUE TITLE
npm fails to update a bundled dependency

### ISSUE THREAD

**Issue by gaearon** [npm/npm#14073]
#### I'm opening this issue because:
- [x] npm is producing an incorrect install.
#### What's going wrong?

`react-scripts@0.5.1` [depends on](https://unpkg.com/react-scripts@0.5.1/package.json) `react-dev-utils@^0.1.1` and [bundles `react-dev-utils@0.1.1`](https://unpkg.com/react-scripts@0.5.1/node_modules/react-dev-utils/package.json) with `bundledDependencies`.

`react-scripts@0.6.0` [depends on](https://unpkg.com/react-scripts@0.6.0/package.json) `react-dev-utils@^0.2.0` and also [bundles `react-dev-utils@0.2.0`](https://unpkg.com/react-scripts@0.6.0/node_modules/react-dev-utils/package.json) with `bundledDependencies`.

A clean install of `react-scripts@0.6.0` correctly produces `react-dev-utils@0.2.0` as a dependency.

However, if I install `react-scripts@0.5.1` first and then install `react-scripts@0.6.0`, npm will **claim it installed `react-dev-utils@0.2.0` in the log but keep `0.1.1` in the file tree**.
#### How can the CLI team reproduce the problem?

```
npm install react-scripts@0.5.1
```

Output: https://gist.github.com/gaearon/5019fd21526a6200ec0089d9ae1cf2da#file-install_0-5-1-log

Then, in the same folder:

```
npm install react-scripts@0.6.0
```

Output: https://gist.github.com/gaearon/5019fd21526a6200ec0089d9ae1cf2da#file-install_0-6-0-log

You can see that the output mentions `react-dev-utils@0.2.0`.

Then, in the same folder:

```
cat node_modules/react-scripts/node_modules/react-dev-utils/package.json 
```

You will see that it’s `0.1.1` rather than `0.2.0`:

```
{
  "_id": "react-dev-utils@0.1.1", // <-------------------- it is 0.1.1 but should be 0.2.0
  "_location": "/react-scripts/react-dev-utils",
  "_phantomChildren": {},
  "_requiredBy": [
    "/react-scripts"
  ],
  "_shrinkwrap": null,
  "bugs": {
    "url": "https://github.com/facebookincubator/create-react-app/issues"
  },
  "dependencies": {
    "chalk": "1.1.3",
    "escape-string-regexp": "1.0.5",
    "opn": "4.0.2"
  },
  "description": "Webpack utilities used by Create React App",
  "devDependencies": {},
  "engines": {
    "node": ">=4"
  },
  "files": [
    "clearConsole.js",
    "checkRequiredFiles.js",
    "formatWebpackMessages.js",
    "InterpolateHtmlPlugin.js",
    "openChrome.applescript",
    "openBrowser.js",
    "prompt.js",
    "WatchMissingNodeModulesPlugin.js"
  ],
  "homepage": "https://github.com/facebookincubator/create-react-app#readme",
  "license": "BSD-3-Clause",
  "name": "react-dev-utils",
  "optionalDependencies": {},
  "peerDependencies": {
    "webpack": "^1.13.2"
  },
  "readme": "<skipped>",
  "readmeFilename": "README.md",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/facebookincubator/create-react-app.git"
  },
  "version": "0.1.1"
}
```
### supporting information:
- `npm -v` prints: 3.10.8
- `node -v` prints: v6.6.0
- `npm config get registry` prints: `https://registry.npmjs.org/`
- Windows, OS X, or Linux?: OS X
- Network issues:
  - Geographic location where npm was run: London, UK

**Comment by calvinmetcalf** [comment]
possibly related to yarnpkg/yarn#1774 ?

 which was caused by readable-stream adding bundled dependencies and causing issues with yarn where node would look for the bundled dependencies at the top level instead of as a dependency of readable-stream
