### ISSUE TITLE
`npm version <patch|minor|major>` should have option to allow changelog changes with `--force`

### ISSUE THREAD

**Issue by isiahmeadows** [npm/npm#14072]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [ ] npm is producing an incorrect install.
- [ ] npm is doing something I don't understand.
- [x] Other (_see below for feature requests_):
#### What's the feature?

A new config option for `npm version` to not require `--force` to when a changelog is added.
#### What problem is the feature intended to solve?

I can edit a changelog, and have it added to the version's commit, this being after all the tests run, and a new browser bundle generated.
#### Is the absence of this feature blocking you or your team? If so, how?

It's not really blocking anything; it's just inconvenient to have to do all this manually each time, especially when I'm error-prone doing it.
#### Is this feature similar to an existing feature in another tool?

Not sure
#### Is this a feature you're prepared to implement, with support from the npm CLI team?

Not really.

**Comment by legodude17** [comment]
Wait, what? 😉 Please explain _in detail_ what this feature is, and what happens when you try to do this currently.

**Comment by isiahmeadows** [comment]
Currently, if *anything* isn't yet committed, `npm version *` complains. I
was asking for an option to exclude CHANGELOG and its variants specifically
from that when verifying the clean tree, and add that to the upcoming
commit.

That would enable me to better make use of my `preversion` (to test and
bundle) and `postversion` (to push) hooks to make it all one automatic
1-command process.

Sorry I explained it so poorly the first time.

**Comment by legodude17** [comment]
Ah, thank you. That seems like a good idea. Maybe it could be a config that you could set like `clean tree ignore` or something.

**Comment by isiahmeadows** [comment]
Although I'd prefer something I could narrow (or is narrowly scoped like
this), because I'd rather avoid other mistakes.
