### ISSUE TITLE
`npm install git+https://<username>:<password>@<url>` with a password contain special chars fails

### ISSUE THREAD

**Issue by geraldinestarke** [npm/npm#14070]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [x] npm is producing an incorrect install.
- [ ] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
#### What's going wrong?

`npm install git+https://<username>:<password>@<url>` with a password contain special chars fails
### supporting information:
- `npm -v` prints: 2.14.2
- `node -v` prints: v4.0.0
- `npm config get registry` prints: https://registry.npmjs.org/
- Windows, OS X, or Linux?: Linux
- Network issues:
  - Geographic location where npm was run:
  - [ ] I use a proxy to connect to the npm registry.
  - [ ] I use a proxy to connect to the web.
  - [ ] I use a proxy when downloading Git repos.
  - [ ] I access the npm registry via a VPN
  - [x] I don't use a proxy, but have limited or unreliable internet access.
- Container:
  - [ ] I develop using Vagrant on Windows.
  - [x] I develop using Vagrant on OS X or Linux.
  - [ ] I develop / deploy using Docker.
  - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
Can you provide an `npm-debug.log`?

**Comment by othiym23** [comment]
We could use a couple examples of what constitutes a special character here, because it's hard to figure out what's going on otherwise. Thanks for your time!

**Comment by silverwind** [comment]
Maybe just the shell acting on those chars? Try single-quoting:

````
npm install 'git+https://<username>:<password>@<url>'
````
