### ISSUE TITLE
Unable to install node modules in Windows 10.

### ISSUE THREAD

**Issue by vjammula** [npm/npm#14075]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [ ] npm is producing an incorrect install.
- [ X] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
#### What's going wrong?

```
C:\Jammula\RL\workspace\qtc-client [master ≡ +1 ~28 -0 !]> npm install Express -g
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\venka\AppData\Local\Temp\npm-7804-66f21621\registry.npmjs.org\forwarded\-\forwarded-0.1.0.tgz.3927715867' -> 'C:\Users\venka\AppData\Local\Temp\npm-7804-66f21621\registry.npmjs.org\forwarded\-\forwarded-0.1.0.tgz'
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "Express" "-g"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\venka\AppData\Local\Temp\npm-7804-66f21621\registry.npmjs.org\http-errors\-\http-errors-1.5.0.tgz.1536821389' -> 'C:\Users\venka\AppData\Local\Temp\npm-7804-66f21621\registry.npmjs.org\http-errors\-\http-errors-1.5.0.tgz'
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "Express" "-g"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

Already tried upgrading to latest Node modules but all efforts in vain. 
Unable to resolve the issue. 
Re-started my machine, ensured all the active windows / IDEs are closed, which access node module files are closed etc...
### supporting information:
- `npm -v` prints:
- `node -v` prints:
- `npm config get registry` prints:
- Windows, OS X, or Linux?:
- Network issues:
  - Geographic location where npm was run:
  - [ ] I use a proxy to connect to the npm registry.
  - [ ] I use a proxy to connect to the web.
  - [ ] I use a proxy when downloading Git repos.
  - [ ] I access the npm registry via a VPN
  - [ ] I don't use a proxy, but have limited or unreliable internet access.
- Container:
  - [X ] I develop using Vagrant on Windows.
  - [ ] I develop using Vagrant on OS X or Linux.
  - [ ] I develop / deploy using Docker.
  - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
Please provide the output of `npm -v` `node -v` `npm config get registry` and `npm prefix` in your project dir.

**Comment by vjammula** [comment]
node -v
   node v6.6.0
npm -v
   npm v3.10.3

npm config get registry
   https://registry.npmjs.org/

npm prefix
   C:\Jammula\DemoApp

**Comment by legodude17** [comment]
Try updating npm, and running `npm cache clean`.

**Comment by vjammula** [comment]
Did try, but did not work.

**Comment by vjammula** [comment]
Am I missing anything? Please help !!!

**Comment by legodude17** [comment]
Try `npm install express`. What error does that give?

**Comment by Ingosmar89219** [comment]
I have same problem,, when im trying to install express in a project's polymer i cant get the carpet node_modules.
C:\Users\osmarvirux\Documents\messenger>npm install express
express@4.14.0 ..\..\node_modules\express
├── escape-html@1.0.3
├── methods@1.1.2
├── encodeurl@1.0.1
├── merge-descriptors@1.0.1
├── content-disposition@0.5.1
├── fresh@0.3.0
├── array-flatten@1.1.1
├── serve-static@1.11.1
├── etag@1.7.0
├── parseurl@1.3.1
├── vary@1.1.0
├── cookie-signature@1.0.6
├── range-parser@1.2.0
├── path-to-regexp@0.1.7
├── content-type@1.0.2
├── utils-merge@1.0.0
├── cookie@0.3.1
├── depd@1.1.0
├── qs@6.2.0
├── on-finished@2.3.0 (ee-first@1.1.1)
├── finalhandler@0.5.0 (unpipe@1.0.0, statuses@1.3.0)
├── debug@2.2.0 (ms@0.7.1)
├── proxy-addr@1.1.2 (forwarded@0.1.0, ipaddr.js@1.1.1)
├── type-is@1.6.13 (media-typer@0.3.0, mime-types@2.1.12)
├── accepts@1.3.3 (negotiator@0.6.1, mime-types@2.1.12)
└── send@0.14.1 (destroy@1.0.4, statuses@1.3.0, ms@0.7.1, mime@1.3.4, http-error
s@1.5.0)

**Comment by KenanY** [comment]
@Ingosmar89219 Please open a new ticket. I've told you this in two other tickets already :(

**Comment by Ingosmar89219** [comment]
Im sorry brother im new in github

**Comment by juaniliska** [comment]
i have the same problem and to fix run 

- npm config get registry
- npm cache clean
- npm install express

and later
- npm install

and work fine

later 
-npm start

and work the tutorial of angular2 (no working in the first time)
D:\Angular2\juan\quickstart>npm start

> angular-quickstart@1.0.0 start D:\Angular2\juan\quickstart
> tsc && concurrently "tsc -w" "lite-server"

[0] 11:05:19 - Compilation complete. Watching for file changes.
[1] Did not detect a `bs-config.json` or `bs-config.js` override file. Using lite-server defaults...
[1] ** browser-sync config **
[1] { injectChanges: false,
[1]   files: [ './**/*.{html,htm,css,js}' ],
[1]   watchOptions: { ignored: 'node_modules' },
[1]   server: { baseDir: './', middleware: [ [Function], [Function] ] } }
[1] [BS] Access URLs:
[1]  ----------------------------------
[1]        Local: http://localhost:3000
[1]     External: http://10.0.2.30:3000
[1]  ----------------------------------
[1]           UI: http://localhost:3001
[1]  UI External: http://10.0.2.30:3001
[1]  ----------------------------------
[1] [BS] Serving files from: ./
[1] [BS] Watching files...
[1] 16.12.26 11:05:26 200 GET /index.html

**Comment by chiranjeevisaride** [comment]
Same Issue please help
**node -v v7.5.0
npm -v 4.1.2
NOTE: tried doing "npm cache clean" didn't work**

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v7.5.0
npm ERR! npm v4.1.2
npm ERR! path C:\Users\Chiranjeevi\Desktop\angularJS\ang2\angular2-seed\node_modules.staging\base64id-47d544ab\package.json.1971791659
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\Chiranjeevi\Desktop\angularJS\ang2\angular2-seed\node_modules.staging\base64id-47d544ab\package.json.1971791659' -> 'C:\Users\Chiranjeevi\Desktop\angularJS\ang2\angular2-seed\node_modules.staging\base64id-47d544ab\package.json'
npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\Chiranjeevi\Desktop\angularJS\ang2\angular2-seed\node_modules.staging\base64id-47d544ab\package.json.1971791659' -> 'C:\Users\Chiranjeevi\Desktop\angularJS\ang2\angular2-seed\node_modules.staging\base64id-47d544ab\package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent
npm ERR! Please include the following file with any support request:
npm ERR! C:\Users\Chiranjeevi\Desktop\angularJS\ang2\angular2-seed\npm-debug.log

**Comment by shahidkarimi** [comment]
How to solve this issue?

**Comment by zkyz** [comment]
I'm too. Somebody help me, please.

**Comment by legodude17** [comment]
Try updating `npm`.
