### ISSUE TITLE
Invalid name: "@ionic/cloud"

### ISSUE THREAD

**Issue by j-ramirez-bi4group** [npm/npm#14084]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [ ] npm is producing an incorrect install.
- [x] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
#### What's going wrong?

I can not install the package @ionic/cloud  in OS X but I can in Ubuntu

The log error is:

```
~ ionic$ npm install @ionic/cloud
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "@ionic/cloud"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9

npm ERR! Invalid name: "@ionic/cloud"
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ionic/npm-debug.log
```
#### How can the CLI team reproduce the problem?

npm install @ionic/cloud
### supporting information:
- `npm -v` prints: 2.15.9
- `node -v` prints: v4.5.0
- `npm config get registry` prints: https://registry.npmjs.org/
- Windows, OS X, or Linux?: OS X
- Network issues:
  - Geographic location where npm was run:
  - [ ] I use a proxy to connect to the npm registry.
  - [ ] I use a proxy to connect to the web.
  - [ ] I use a proxy when downloading Git repos.
  - [ ] I access the npm registry via a VPN
  - [ ] I don't use a proxy, but have limited or unreliable internet access.
- Container:
  - [ ] I develop using Vagrant on Windows.
  - [ ] I develop using Vagrant on OS X or Linux.
  - [ ] I develop / deploy using Docker.
  - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by vdeturckheim** [comment]
We met the same issue recently on another scoped package on OS X. Was there any progress made here?
Thanks a lot

**Comment by vimoshe** [comment]
I got the same issue with @google-cloud/storage module install on Red-hat Linux machine.
Any suggestions?
Thanks.
