### ISSUE TITLE
[3.10.8] Cannot install modules due "Unsupported platform for"

### ISSUE THREAD

**Issue by mfn** [npm/npm#14089]
#### I'm opening this issue because:

  - [x] npm is producing an incorrect install.

#### What's going wrong?

The npm shrinnkwrap generated on OSX and being tried to install on a Linux system fails with this (and no `node_modules/` are installed at all):
```
npm ERR! Linux 4.2.0-42-generic
npm ERR! argv "/home/rof/.nvm/versions/node/v4.5.0/bin/node" "/home/rof/.nvm/versions/node/v4.5.0/bin/npm" "install"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.8
npm ERR! code EBADPLATFORM

npm ERR! notsup Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64
```

This worked with 3.10.7 (i.e. `fsevents` got installed)

### supporting information:

 - `npm -v` prints:
3.10.8
 - `node -v` prints:
v4.5.0
 - `npm config get registry` prints:
https://registry.npmjs.org/
 - Windows, OS X, or Linux?:
OS X and Linux x86_64

**Comment by KenanY** [comment]
Duplicate of https://github.com/npm/npm/issues/14042?

**Comment by mfn** [comment]
Ops, yes. I swear I tried the search first, thanks!
