### ISSUE TITLE
npm ERR! Windows_NT 6.1.7601 npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program F node_modules\\npm\\bin\\npm-cli.js" "info" npm ERR! node v6.6.0 npm ERR! npm  v3.10.3  npm ERR! Invalid package.json npm ERR!

### ISSUE THREAD

**Issue by Jiar** [npm/npm#14088]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli   'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'info' ]
2 info using npm@3.10.3
3 info using node@v6.6.0
4 verbose config Skipping project config: C:\Users\Administrator.USER-20160718LM/.npmrc. (matches userconfig)
5 verbose stack Error: Invalid package.json
5 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\view.js:84:30
5 verbose stack     at ReadFileContext.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:90:21)
5 verbose stack     at ReadFileContext.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16)
5 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete](fs.js:365:13)
6 verbose cwd C:\Users\Administrator.USER-20160718LM
7 error Windows_NT 6.1.7601
8 error argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "info"
9 error node v6.6.0
10 error npm  v3.10.3
11 error Invalid package.json
12 error If you need help, you may report this error at:
12 error     https://github.com/npm/npm/issues
13 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@Jiar Can I see your `package.json`? What behavior are you expected `npm info` to perform here?

**Comment by Aj0512** [comment]
Hi @KenanY , 

**Same issue in my local system for npm start** 

> C:\Windows\system32>npm start
> npm ERR! Windows_NT 10.0.10240
> npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Vijay Soni\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
> npm ERR! node v7.1.0
> npm ERR! npm  v3.10.9
> 
> npm ERR! missing script: start
> npm ERR!
> npm ERR! If you need help, you may report this error at:
> npm ERR!     <https://github.com/npm/npm/issues>
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     C:\Windows\system32\npm-debug.log


**npm info perform here :-** 

> C:\Windows\system32>npm info
> 
> { name: 'y',
>   description: 'Simple object inspection tool',
>   'dist-tags': { latest: '0.3.2' },
>   versions:
>    [ '0.0.0',
>      '0.1.0',
>      '0.1.1',
>      '0.2.2',
>      '0.2.3',
>      '0.3.0',
>      '0.3.1',
>      '0.3.2' ],
>   maintainers: [ 'eliasgs <eliasgs@gmail.com>' ],
>   time:
>    { modified: '2014-07-29T14:30:55.394Z',
>      created: '2013-11-01T16:49:23.740Z',
>      '0.0.0': '2013-11-01T16:49:27.235Z',
>      '0.1.0': '2013-11-08T13:18:13.721Z',
>      '0.1.1': '2013-11-08T14:38:58.931Z',
>      '0.2.2': '2013-12-21T11:24:25.697Z',
>      '0.2.3': '2013-12-22T20:44:57.532Z',
>      '0.3.0': '2014-04-23T20:22:01.633Z',
>      '0.3.1': '2014-04-23T20:45:06.660Z',
>      '0.3.2': '2014-07-29T14:30:55.394Z' },
>   author: 'Elias G. Schneevoigt <eliasgs@gmail.com>',
>   repository: { type: 'git', url: 'https://github.com/eliasgs/y' },
>   homepage: 'https://github.com/eliasgs/y',
>   keywords: [ 'inspect', 'debug', 'trace' ],
>   bugs: { url: 'https://github.com/eliasgs/y/issues' },
>   license: 'MIT',
>   readmeFilename: 'README.md',
>   version: '0.3.2',
>   main: 'y.js',
>   scripts: { test: 'node test' },
>   dist:
>    { shasum: 'bd08711d26b034d026a30599a9919a63fe43c3fa',
>      tarball: 'https://registry.npmjs.org/y/-/y-0.3.2.tgz' },
>   directories: {} }

**Please reply ...thanks in advance** 

> Regards 
> Aj

**Comment by KenanY** [comment]
I'm closing this issue since the OP never responded,

@Aj0512 I suggest you read through [the documentation](https://docs.npmjs.com/misc/scripts) on how scripts work and how to write your own. From the error, it looks like you are running `npm start`, but you do not have `"start"` script defined.

**Comment by gowufang** [comment]
@Aj0512 did you resolve the problem for npm start?I have the same problem

**Comment by smruti26** [comment]
D:\project\project_1>npm install
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! syscall getaddrinfo


npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:

not able find the solution. kinldy suggest
