### ISSUE TITLE
npm uses http_proxy environment variable without indication

### ISSUE THREAD

**Issue by jteplitz602** [npm/npm#14099]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [  ] npm is producing an incorrect install.
- [ x ] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
#### What's going wrong?

npm is unable to connect to the registry at all regardless of which packages it is trying to install. My network is working fine. I receive this error:
`npm ERR! network tunneling socket could not be established, cause=connect EHOSTUNREACH 0.0.31.144:80 - Local (10.31.76.95:62879)`
Specifically it's unable to do a GET request to https://registry.npmjs.org/[package-name]. I can load the request fine in my browser. I am not using a proxy.
#### How can the CLI team reproduce the problem?

Here's a log output from an attempt to install "lodash":
npm info it worked if it ends with ok
npm verb cli [ '/Users/Jason/.nvm/versions/node/v4.5.0/bin/node',
npm verb cli   '/Users/Jason/.nvm/versions/node/v4.5.0/bin/npm',
npm verb cli   'install',
npm verb cli   '-g',
npm verb cli   '--loglevel=silly',
npm verb cli   'lodash' ]
npm info using npm@2.15.9
npm info using node@v4.5.0
npm verb install initial load of /Users/Jason/.nvm/versions/node/v4.5.0/lib/package.json
npm verb readDependencies loading dependencies from /Users/Jason/.nvm/versions/node/v4.5.0/lib/package.json
npm sill cache add args [ 'lodash', null ]
npm verb cache add spec lodash
npm sill cache add parsed spec Result {
npm sill cache add   raw: 'lodash',
npm sill cache add   scope: null,
npm sill cache add   name: 'lodash',
npm sill cache add   rawSpec: '',
npm sill cache add   spec: 'latest',
npm sill cache add   type: 'tag' }
npm sill addNamed lodash@latest
npm verb addNamed "latest" is being treated as a dist-tag for lodash
npm info addNameTag [ 'lodash', 'latest' ]
npm sill mapToRegistry name lodash
npm sill mapToRegistry using default registry
npm sill mapToRegistry registry https://registry.npmjs.org/
npm sill mapToRegistry data Result {
npm sill mapToRegistry   raw: 'lodash',
npm sill mapToRegistry   scope: null,
npm sill mapToRegistry   name: 'lodash',
npm sill mapToRegistry   rawSpec: '',
npm sill mapToRegistry   spec: 'latest',
npm sill mapToRegistry   type: 'tag' }
npm sill mapToRegistry uri https://registry.npmjs.org/lodash
npm verb addNameTag registry:https://registry.npmjs.org/lodash not in flight; fetching
npm verb request uri https://registry.npmjs.org/lodash
npm verb request no auth needed
npm info attempt registry request try #1 at 4:29:55 PM
npm verb request id f884687b281c261e
npm http request GET https://registry.npmjs.org/lodash
npm info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=connect EHOSTUNREACH 0.0.31.144:80 - Local (10.31.76.95:62723)
npm info attempt registry request try #2 at 4:30:05 PM
npm http request GET https://registry.npmjs.org/lodash
npm info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=connect EHOSTUNREACH 0.0.31.144:80 - Local (10.31.76.95:62756)
### supporting information:
- `npm -v` prints: 3.10.3
- `node -v` prints: 6.6.0
- `npm config get registry` prints: https://registry.npmjs.org/
- Windows, OS X, or Linux?: OS X
- Network issues:
  - Geographic location where npm was run: Bay area, CA
  - [ ] I use a proxy to connect to the npm registry.
  - [ ] I use a proxy to connect to the web.
  - [ ] I use a proxy when downloading Git repos.
  - [ ] I access the npm registry via a VPN
  - [ ] I don't use a proxy, but have limited or unreliable internet access.
- Container:
  - [ ] I develop using Vagrant on Windows.
  - [ ] I develop using Vagrant on OS X or Linux.
  - [ ] I develop / deploy using Docker.
  - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by jteplitz602** [comment]
Following up on this. Attempting the same command inside a Docker container gives the same error.

**Comment by jteplitz602** [comment]
Turns out the problem here is that if you have an `http_proxy` environment variable set npm will use it by default. Is this the correct behavior? I was under the impression that only environment variables that start with the "npm_config_" prefix are used? Either way, if npm is going to use a proxy I feel that `npm config list` should show that it is active.

**Comment by nnashok** [comment]
This is true even if I have overridden the env vars in my .npmrc with:
proxy=""
https_proxy=""

If I override it in my .npmrc, i would expect nom to respect that and not fall back on the env var.
