### ISSUE TITLE
Windows 10: npm install React error

### ISSUE THREAD

**Issue by aaronmi** [npm/npm#14098]
#### I'm opening this issue because:
  - [X] npm is producing an incorrect install.

#### What's going wrong?
In npm-debug.log:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   'react' ]
2 info using npm@3.3.12
3 info using node@v5.5.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData react
8 silly fetchNamedPackageData react
9 silly mapToRegistry name react
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/react
13 verbose request uri https://registry.npmjs.org/react
14 verbose request no auth needed
15 info attempt registry request try #1 at 4:49:18 PM
16 verbose request id e38cf785794239eb
17 verbose etag "DIVGJSD3NYDAH92JPYI3G81VS"
18 http request GET https://registry.npmjs.org/react
19 http 304 https://registry.npmjs.org/react
20 verbose headers { date: 'Tue, 27 Sep 2016 23:49:18 GMT',
20 verbose headers   via: '1.1 varnish',
20 verbose headers   'cache-control': 'max-age=300',
20 verbose headers   etag: '"DIVGJSD3NYDAH92JPYI3G81VS"',
20 verbose headers   age: '0',
20 verbose headers   connection: 'keep-alive',
20 verbose headers   'x-served-by': 'cache-den6023-DEN',
20 verbose headers   'x-cache': 'HIT',
20 verbose headers   'x-cache-hits': '1',
20 verbose headers   'x-timer': 'S1475020158.144685,VS0,VE290',
20 verbose headers   vary: 'Accept-Encoding' }
21 silly get cb [ 304,
21 silly get   { date: 'Tue, 27 Sep 2016 23:49:18 GMT',
21 silly get     via: '1.1 varnish',
21 silly get     'cache-control': 'max-age=300',
21 silly get     etag: '"DIVGJSD3NYDAH92JPYI3G81VS"',
21 silly get     age: '0',
21 silly get     connection: 'keep-alive',
21 silly get     'x-served-by': 'cache-den6023-DEN',
21 silly get     'x-cache': 'HIT',
21 silly get     'x-cache-hits': '1',
21 silly get     'x-timer': 'S1475020158.144685,VS0,VE290',
21 silly get     vary: 'Accept-Encoding' } ]
22 verbose etag https://registry.npmjs.org/react from cache
23 verbose get saving react to C:\Users\AARONMI\AppData\Roaming\npm-cache\registry.npmjs.org\react\.cache.json
24 silly install normalizeTree
25 silly loadCurrentTree Finishing
26 silly loadIdealTree Starting
27 silly install loadIdealTree
28 silly cloneCurrentTree Starting
29 silly install cloneCurrentTreeToIdealTree
30 silly cloneCurrentTree Finishing
31 silly loadShrinkwrap Starting
32 silly install loadShrinkwrap
33 silly loadShrinkwrap Finishing
34 silly loadAllDepsIntoIdealTree Starting
35 silly install loadAllDepsIntoIdealTree
36 silly rollbackFailedOptional Starting
37 silly rollbackFailedOptional Finishing
38 silly runTopLevelLifecycles Starting
39 silly runTopLevelLifecycles Finishing
40 silly install printInstalled
41 verbose stack Error: Refusing to install react as a dependency of itself
41 verbose stack     at checkSelf (C:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:40:14)
41 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
41 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
41 verbose stack     at chain (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
41 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:15:5
41 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
41 verbose stack     at Array.forEach (native)
41 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
41 verbose stack     at Array.forEach (native)
41 verbose stack     at asyncMap (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
42 verbose cwd D:\Training\TypeScript\react-ts
43 error Windows_NT 10.0.14393
44 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "react"
45 error node v5.5.0
46 error npm  v3.3.12
47 error code ENOSELF
48 error Refusing to install react as a dependency of itself
49 error If you need help, you may report this error at:
49 error     <https://github.com/npm/npm/issues>
50 verbose exit [ 1, true ]

#### How can the CLI team reproduce the problem?
npm install --save react

**Comment by KenanY** [comment]
@aaronmi Is the `"name"` property in your `package.json` set to `"react"`? If so, could you try changing that to something more unique?

**Comment by aaronmi** [comment]
Thank you KenanY. That was the problem. After changing the "name" property in package.json to something else. It works!

**Comment by learningendless** [comment]
I always have the same problem, even when I run "npm install " with F8 app source code.

**Comment by legodude17** [comment]
Did you set the `"name"` property in your `package.json` to the name of one of your dependencies?
