### ISSUE TITLE
Why not `npm install --exact-versions`?

### ISSUE THREAD

**Issue by AJB99** [npm/npm#14094]
#### I'm opening this issue because:
- [x] simply running `npm install` in a production env is unpredictable and dangerous.
- [x] `npm shrinkwrap` seems extraneous (ha, get it?) .
#### What's going wrong?

I'm forced to set config vars in `.npmrc` (save = true, save-exact = true), and then I'm forced to `npm shrinkwrap` every time I update my deps (although I've added this step to "scripts.postinstall", and "scripts.postuninstall" in my package.json file).

Would it not be a tonne easier and cleaner to provide an `--exact-versions` flag for `npm install` that would install the _exact_ version of any dependencies (and deps of deps)?

Perhaps there's complexity that's escaping me, but it seems backwards that npm defaults to "auto-updating" dependencies rather than forcing the dev to explicitly declare that they _want_ that? It seems to me that a tonne of time and energy has been wasted just trying to get npm to install predictable versions (npm shrinkwrap, npm-lockdown, shrinkpack, etc. etc. etc.), and none of them are reliable!

Would not an `--exact-versions` option obviate the need for `npm shrinkwrap` altogether?

Obviously this doesn't solve the problem of the npm registry itself being unavailable, or that any given dev might just haphazardly yank their module from npm. But it would at least git rid of the craziness that is `npm shrinkwrap` and prevent future devs from wasting 8 hours of their time trying to lock down _all_ the versions of _all_ modules that would be installed, and failing to find a reliable solution.

**Comment by AJB99** [comment]
Ha. Just me?

**Comment by JamieMason** [comment]
I may be wrong but this is my take on it.

When you push your `--exact-versions` installed project to git and a co-worker checks it out a week or month or so later, their `npm` would not be able to know what those exact versions were without something to describe the name/version pairs that were present when you did your installation.

That is the role of npm-shrinkwrap.json.

**Comment by AJB99** [comment]
Hi Jamie,

Isn't that the role of `package.json`?

`npm install --exact-versions` would install the versions declared in the `package.json` file, and the exact versions declared in any `package.json` files for any deps, or deps of deps.

I find it redundant that a separate `npm-shrinkwrap.json` file is created just to 'lock' down the versions, even though all the versions are already declared in the `package.json` file(s).

**Comment by JamieMason** [comment]
the difference is deps of deps - package.json only describes the top level, but npm-shrinkwrap.json describes the full tree as it is at th time you create it. if your package.json contains foo@0.5.2 and the package.json of _foo_ contains bar@^1.1.0 for example - that wildcard version presents a problem, how can npm know what the version of bar was when _you_ installed foo? when the latest version might now be bar@1.1.2.

**Comment by AJB99** [comment]
Because it would have installed the *exact* version of `bar` from the `foo` `package.json` file. In this case, it would have installed `bar 1.1.0`.

**Comment by JamieMason** [comment]
if when you install this project and bar@1.1.0 is the latest version at that time, how does your co-worker end up with bar@1.1.0 and not bar@1.1.2 in his installation, if bar@1.1.2 is the latest version by that time? 

what i'm not explaining very well is, _there is no exact version of a package_, if it or any of it's dependencies use semver wildcard ranges then what you get varies depending on what the latest versions are at the time you run the install.

**Comment by AJB99** [comment]
Yes, that's exactly the *problem*. `npm install --exact-versions` would ignore any server ranges and simply install the *exact version*. Yes, there are exact versions in a `package.json` file, provided npm doesn't try to be helpful and update the version behind my back.

If I run `npm install --exact-versions` and I get `foo@0.5.2` and `bar@1.1.0` then anyone that runs `npm install --exact-versions` using that same `package.json` file that declares `"foo" : "0.5.2"` will also get `bar@1.1.0` because the `node_modules > foo > package.json` file will declare `"bar" : "1.1.0"`.

**Comment by JamieMason** [comment]
Now I see, the flag ignores ranges. Potentially something there, how would you handle the trickier ranges? Things like 1.x.x, or even *? always take the oldest version that matches? error out? something else? Thanks for explaining.

**Comment by AJB99** [comment]
Aces.

Not entirely sure how to best handle `1.x.x` or `*` ranges. I guess it would just default to the oldest version that matches with a warning to the user.

Thanks for walking through this.

**Comment by arslivinski** [comment]
Yeah, that would be a nice feature. We have a private package here that is about one year old. We didn't know about shrinkwrap then, and we didn't care about shrinkwrap until now, when some transitive dependency broke our package. The `npm install --exact-versions` would be very helpfull in this situation.
I don't know how to deal with things like 1.x.x or even *, but I think that in this case there's no magic, npm could simply install the most recent version of these packages and log them.

**Comment by ericnewton76** [comment]
IMO npm shrinkwrap should actually be the default handling.

Only when calling ```npm install --save [package]``` or ```update``` with no version, should it start grabbing "latest", and save it.  Or must specify ```npm install --save [package]@latest``` explicitly.

Of Note, ```npm install --save``` seems to update ```npm-shrinkwrap.json``` as well, which is expected.

**Comment by jkells** [comment]
This behaviour violates the principle of least surprise. I've recently switched over to NPM for a bunch of Javascript packages that I used to install from a different package manager.

I've been burnt 3 times in the last month by versions of transient dependencies changing, I thought setting exact versions in package.json was enough.

Performing a few line change hotfix to a release branch only to find a heap of transient dependencies updated during the build causing major breakages.

In one case in the time between running CI tests and doing a deploy the dependencies changed and broke the application.

npm shinkwrap is obviously the answer but having defaults like this causes real pain, I only discovered shinkwrap by digging through the documentation after being burnt by the defaults.

**Comment by ericnewton76** [comment]
^^ big mistake to allow this to close.  

As @jkells points out, and I've experienced myself, the transient dependencies should be locked down at install so that npm shrinkwrap recording of all dependencies is the default condition.

**Comment by pzhan** [comment]
Just got into the same problem, and because we do not know which transient dependencies is causing this, we are wasting a lot of time for something that should theoretically work but that actually does not work well (I mean patch/minor changes that should not contain breaking changes).
