### ISSUE TITLE
npm Error Window_NT 10.0.0.10240

### ISSUE THREAD

**Issue by tribhuwank** [npm/npm#14096]
#### I'm opening this issue because:
- [ ] npm is crashing at installation ionic
#### What's going wrong?

C:\Windows\system32>npm install  ionic-framework
C:\Windows\system32
+-- UNMET PEER DEPENDENCY angular2@^2.0.0-beta.6
`-- ionic-framework@2.0.0-beta.2
  +-- colors@1.1.2
  +-- inquirer@0.11.0
  | +-- ansi-escapes@1.4.0
  | +-- ansi-regex@2.0.0
  | +-- chalk@1.1.3
  | | +-- ansi-styles@2.2.1
  | | +-- escape-string-regexp@1.0.5
  | | +-- has-ansi@2.0.0
  | |`-- supports-color@2.0.0
  | +-- cli-cursor@1.0.2
  | | `-- restore-cursor@1.0.1
  | |   +-- exit-hook@1.1.1
  | |`-- onetime@1.1.0
  | +-- cli-width@1.1.1
  | +-- figures@1.7.0
  | | `-- object-assign@4.1.0
  | +-- readline2@1.0.1
  | | +-- code-point-at@1.0.0
  | | |`-- number-is-nan@1.0.0
  | | +-- is-fullwidth-code-point@1.0.0
  | | `-- mute-stream@0.0.5
  | +-- run-async@0.1.0
  | |`-- once@1.4.0
  | |   `-- wrappy@1.0.2
  | +-- rx-lite@3.1.2
  | +-- strip-ansi@3.0.1
  |`-- through@2.3.8
  +-- lodash@3.10.1
  +-- mkdirp-no-bin@0.5.1
  `-- q@1.4.1

npm WARN enoent ENOENT: no such file or directory, open 'C:\Windows\system32\package.json'
npm WARN ionic-framework@2.0.0-beta.2 requires a peer of angular2@^2.0.0-beta.6 but none was installed.
npm WARN system32 No description
npm WARN system32 No repository field.
npm WARN system32 No README data
npm WARN system32 No license field.
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "ionic-framework"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! path C:\Windows\system32\node_modules
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall mkdir

npm ERR! Error: EPERM: operation not permitted, mkdir 'C:\Windows\system32\node_modules'
npm ERR!     at Error (native)
npm ERR!  { Error: EPERM: operation not permitted, mkdir 'C:\Windows\system32\node_modules'
npm ERR!     at Error (native)
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: 'C:\Windows\system32\node_modules' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "ionic-framework"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! path C:\Windows\system32\npm-debug.log.3614063615
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall open

npm ERR! Error: EPERM: operation not permitted, open 'C:\Windows\system32\npm-debug.log.3614063615'
npm ERR!     at Error (native)
npm ERR!  { Error: EPERM: operation not permitted, open 'C:\Windows\system32\npm-debug.log.3614063615'
npm ERR!     at Error (native)
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'open',
npm ERR!   path: 'C:\Windows\system32\npm-debug.log.3614063615' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Windows\system32\npm-debug.log

**Comment by KenanY** [comment]
@tribhuwank Why run that command from within your system32 directory?

**Comment by kumarkannan** [comment]
i am having the same error for while i installing the react js:
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "D:\\node.exe" "D:\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v7.7.4
npm ERR! npm  v4.1.2

npm ERR! missing script: start
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\App\kk\npm-debug.log

what i do no ?
i am not able to go further step with this error

**Comment by KenanY** [comment]
@kumarkannan Make sure you have a `"start"` script defined in your `package.json` before trying to run `npm start`.

**Comment by kumarkannan** [comment]
thanks for your reply, but i mentioned start in package.json file but still i have a same error while installing..

**Comment by KenanY** [comment]
@kumarkannan I would like to see `D:\App\kk\package.json` then.
