### ISSUE TITLE
npm install: fetch failed with status code 503

### ISSUE THREAD

**Issue by oxy-code** [npm/npm#14101]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### How can the CLI team reproduce the problem?
try to clone from `git@github.com:maxogden/screencat.git`
and then use `npm install`

Here is my npm debug log https://gist.github.com/oxy-code/3d5656aeb0e526399f30853540bb1577

### supporting information:

 - `npm -v` prints: 2.15.9
 - `node -v` prints: 4.5.0
 - `npm config get registry` prints:
 - Windows, OS X, or Linux?:Linux (Ubuntu-14.04)
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by seoker** [comment]
+1

**Comment by Tataro** [comment]
me too

**Comment by heanhsu** [comment]
+1！！！

**Comment by transformatika** [comment]
+1

**Comment by diofinus** [comment]
Get the same one. This is my console message

```
npm ERR! fetch failed https://registry.npmjs.org/rimraf/-/rimraf-2.4.5.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503
npm ERR! fetch failed https://registry.npmjs.org/request/-/request-2.75.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503
npm ERR! fetch failed https://registry.npmjs.org/basic-auth/-/basic-auth-1.0.4.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503
npm ERR! fetch failed https://registry.npmjs.org/pinkie-promise/-/pinkie-promise-2.0.1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503
npm ERR! fetch failed https://registry.npmjs.org/statuses/-/statuses-1.3.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503
npm ERR! fetch failed https://registry.npmjs.org/clean-css/-/clean-css-3.4.20.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503
npm ERR! fetch failed https://registry.npmjs.org/basic-auth/-/basic-auth-1.0.4.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503
npm ERR! fetch failed https://registry.npmjs.org/pinkie-promise/-/pinkie-promise-2.0.1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503
npm ERR! fetch failed https://registry.npmjs.org/rimraf/-/rimraf-2.4.5.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503
npm ERR! fetch failed https://registry.npmjs.org/clean-css/-/clean-css-3.4.20.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503
npm ERR! fetch failed https://registry.npmjs.org/statuses/-/statuses-1.3.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503
npm ERR! fetch failed https://registry.npmjs.org/request/-/request-2.75.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503
```

**Comment by othiym23** [comment]
Thanks for the heads up! This is currently being tracked as http://status.npmjs.org/incidents/xmxgp5l7ljk5. For future reference, network issues with the registry will get attention faster if they're filed on [`npm/registry`](https://github.com/npm/registry/issues).

**Comment by oxy-code** [comment]
Thanks it's been resolved.
