### ISSUE TITLE
Unable to install protactor

### ISSUE THREAD

**Issue by Ashishpb1** [npm/npm#14108]
I am attaching the npm logs its giving 404 and not able to protactor on windows
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'protactor' ]
2 info using npm@2.15.9
3 info using node@v4.6.0
4 verbose config Skipping project config: C:\Users\as004gu/.npmrc. (matches userconfig)
5 verbose install initial load of C:\Users\as004gu\package.json
6 verbose readDependencies loading dependencies from C:\Users\as004gu\package.json
7 silly cache add args [ 'protactor', null ]
8 verbose cache add spec protactor
9 silly cache add parsed spec Result {
9 silly cache add   raw: 'protactor',
9 silly cache add   scope: null,
9 silly cache add   name: 'protactor',
9 silly cache add   rawSpec: '',
9 silly cache add   spec: 'latest',
9 silly cache add   type: 'tag' }
10 silly addNamed protactor@latest
11 verbose addNamed "latest" is being treated as a dist-tag for protactor
12 info addNameTag [ 'protactor', 'latest' ]
13 silly mapToRegistry name protactor
14 silly mapToRegistry using default registry
15 silly mapToRegistry registry http://registry.npmjs.org/
16 silly mapToRegistry data Result {
16 silly mapToRegistry   raw: 'protactor',
16 silly mapToRegistry   scope: null,
16 silly mapToRegistry   name: 'protactor',
16 silly mapToRegistry   rawSpec: '',
16 silly mapToRegistry   spec: 'latest',
16 silly mapToRegistry   type: 'tag' }
17 silly mapToRegistry uri http://registry.npmjs.org/protactor
18 verbose addNameTag registry:http://registry.npmjs.org/protactor not in flight; fetching
19 verbose request uri http://registry.npmjs.org/protactor
20 verbose request no auth needed
21 info attempt registry request try #1 at 4:28:32 PM
22 verbose request id 1dd7478275d5cc89
23 http request GET http://registry.npmjs.org/protactor
24 http 404 http://registry.npmjs.org/protactor
25 verbose headers { 'content-type': 'application/json',
25 verbose headers   'cache-control': 'max-age=0',
25 verbose headers   'content-length': '2',
25 verbose headers   'accept-ranges': 'bytes',
25 verbose headers   date: 'Wed, 28 Sep 2016 10:58:32 GMT',
25 verbose headers   via: '1.1 varnish',
25 verbose headers   age: '0',
25 verbose headers   connection: 'keep-alive',
25 verbose headers   'x-served-by': 'cache-sin6927-SIN',
25 verbose headers   'x-cache': 'MISS',
25 verbose headers   'x-cache-hits': '0',
25 verbose headers   'x-timer': 'S1475060312.283576,VS0,VE233',
25 verbose headers   vary: 'Accept-Encoding' }
26 silly get cb [ 404,
26 silly get   { 'content-type': 'application/json',
26 silly get     'cache-control': 'max-age=0',
26 silly get     'content-length': '2',
26 silly get     'accept-ranges': 'bytes',
26 silly get     date: 'Wed, 28 Sep 2016 10:58:32 GMT',
26 silly get     via: '1.1 varnish',
26 silly get     age: '0',
26 silly get     connection: 'keep-alive',
26 silly get     'x-served-by': 'cache-sin6927-SIN',
26 silly get     'x-cache': 'MISS',
26 silly get     'x-cache-hits': '0',
26 silly get     'x-timer': 'S1475060312.283576,VS0,VE233',
26 silly get     vary: 'Accept-Encoding' } ]
27 verbose stack Error: Registry returned 404 for GET on http://registry.npmjs.org/protactor
27 verbose stack     at makeError (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:264:12)
27 verbose stack     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:242:14)
27 verbose stack     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:172:14)
27 verbose stack     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:200:22)
27 verbose stack     at emitTwo (events.js:87:13)
27 verbose stack     at Request.emit (events.js:172:7)
27 verbose stack     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1067:10)
27 verbose stack     at emitOne (events.js:82:20)
27 verbose stack     at Request.emit (events.js:169:7)
27 verbose stack     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:988:12)
28 verbose statusCode 404
29 verbose pkgid protactor
30 verbose cwd C:\Users\as004gu
31 error Windows_NT 6.1.7601
32 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "protactor"
33 error node v4.6.0
34 error npm  v2.15.9
35 error code E404
36 error 404 Registry returned 404 for GET on http://registry.npmjs.org/protactor
36 error 404
36 error 404 'protactor' is not in the npm registry.
36 error 404 You should bug the author to publish it (or use the name yourself!)
36 error 404
36 error 404 Note that you can also install from a
36 error 404 tarball, folder, http url, or git url.
37 verbose exit [ 1, true ]

#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@Ashishpb1 Looks like there is no module in the registry named `protactor`, hence the 404 error. Maybe you mean to install `protractor`?

**Comment by Ashishpb1** [comment]
Yes i mean to install protactor..

C:\Users\as004gu>npm install protactor
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "protactor"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on http://registry.npmjs.org/protacto
r
npm ERR! 404
npm ERR! 404 'protactor' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\as004gu\npm-debug.log

**Comment by KenanY** [comment]
@Ashishpb1 Well, again, such a module does not exist, hence it is impossible to install it :)

**Comment by Ashishpb1** [comment]
:-) resolved its typo from my end!! its Protractor
