### ISSUE TITLE
[W7]Maximum call stack size exceeded

### ISSUE THREAD

**Issue by firescythe** [npm/npm#14107]
#### I'm opening this issue because:
- [ X ] npm is producing an incorrect install.
#### What's going wrong?

command: npm install -no-bin-links (previously node.js was installed and "npm install -global gulp-cli" command was succesful)
After 8th deprication warning, the next UI response is the error message in the title:
"npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\
node_modules\npm\bin\npm-cli.js" "install" "-no-bin-links"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3

npm ERR! Maximum call stack size exceeded
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     c:\xampp\htdocs\gofree\npm-debug.log"
#### How can the CLI team reproduce the problem?

https://gist.github.com/firescythe/71ed8102b8ae5694e3f2fc4ef260fb1c

The full environment is: XAMPP ran Apache svr, Laravel PHP framework.
There is a verified, working page. 
Installed Node.js
Started command-line window to run "npm install -global gulp-cli" . It was succesful.
In same window "npm install -no-bin-links".

If repeating the command  "npm install -no-bin-links":
"npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14"

Attempted full clean-up and re-execute commands, same result.
### supporting information:
- `npm -v` prints: 3.10.3
- `node -v` prints: v6.6.0
- `npm config get registry` prints: https://registry.npmjs.org/
- Windows, OS X, or Linux?: Win
- Network issues: none
  - Geographic location where npm was run: Hungary
  - [ X ] I use a proxy to connect to the web. (When sys.env.var.s were incorrect, it did not even started install, but managed that.)

**Comment by firescythe** [comment]
Workarounded with hardcopy from another machine, which installed earlier:
npm -v: 2.15.9
node -v: v4.5.0

**Comment by InfiniteStyles** [comment]
I've had the same problems with Node on Windows. It's pretty terrible.

**Comment by legodude17** [comment]
What does your package.json's dependencies look like?
