### ISSUE TITLE
npm yeoman installation fails

### ISSUE THREAD

**Issue by swsn** [npm/npm#14103]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [ ] npm is producing an incorrect install.
- [ ] npm is doing something I don't understand.
- [x] Other (_see below for feature requests_):
#### What's going wrong?

Hello,
I am trying to install yeoman but it is returning the following error:

npm install -g yo
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
/root/.npm-global/bin/yo -> /root/.npm-global/lib/node_modules/yo/lib/cli.js
/root/.npm-global/bin/yo-complete -> /root/.npm-global/lib/node_modules/yo/lib/completion/index.js

> spawn-sync@1.0.15 postinstall /root/.npm-global/lib/node_modules/yo/node_modules/spawn-sync
> node postinstall

module.js:457
    throw err;
    ^

Error: Cannot find module '/root/.npm-global/lib/node_modules/yo/node_modules/spawn-sync/postinstall'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
/root/.npm-global/lib
└── (empty)

npm ERR! Linux 2.6.32-642.el6.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "yo"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! spawn-sync@1.0.15 postinstall: `node postinstall`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the spawn-sync@1.0.15 postinstall script 'node postinstall'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the spawn-sync package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node postinstall
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs spawn-sync
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls spawn-sync
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log
npm ERR! code 1
#### How can the CLI team reproduce the problem?

I tired many of the solutions available online and none seem to help.
### supporting information:
- `npm -v` prints: 3.10.3
- `node -v` prints: v6.6.0
- `npm config get registry` prints: https://registry.npmjs.org/
- Windows, OS X, or Linux?: Linux RHEL 6

Thank you for your help and support.

**Comment by mmjasso** [comment]
I am having the same issue, after a fresh installation of npm using:
-> sudo npm install -g npm 
I have the same issue as mentioned in the previous post, unable to continue ....
I have tried:
 - sudo chmod -R 755 /usr/lib/node_modules
 - sudo chown -R root: /usr/lib/node_modules

**Comment by itslong** [comment]
Hi, I had the same module error after installing yo and running yo meanjs at the project root folder. 

Looked around and couldn't find an answer. Uninstalled and reinstalled the following modules.

Steps taken as a clean install:

1. installed node.js. node --version: v4.6.0
2. installed bower. bower --version: 
3. installed grunt-cli. grunt-cli: v1.2.0
4. installed yeoman generator. yo --version: 1.8.5. 
Could the issue be related to the npm WARN deprecated npmconf@2.1.2 from yeoman?

![yo_npm_dep](https://cloud.githubusercontent.com/assets/7595521/19392870/6a60e516-91e7-11e6-89b0-a788dcfe6372.JPG)

5. npm --version: 3.10.8

* windows 7, 64 bit

**Comment by mmjasso** [comment]
Hello 

I manage to solve my issue in RHEL 6.4 by uninstalling nodejs and removing its directories:

Uninstall:
- sudo yum remove nodejs 
- sudo rm -rf /usr/lib/node_modules
- sudo rm -rf ~/.npm
- rm -rf ~/.npm   (user home directory)

Re intsall:
- sudo yum install nodejs
- sudo npm install -g npm 
- sudo npm install -g grunt 
- sudo npm install -g grunt-cli
- sudo npm install -g bower
- sudo npm install -g yo

I hope it helps.

**Comment by italojs** [comment]
just do it.
-sudo npm install npm
-sudo ln -s /usr/bin/nodejs /usr/bin/node
-sudo npm install -g yo

**Comment by weaming** [comment]
same issue

```
# node --version
v8.2.1
#  npm --version
5.3.0
# npm install -g yo
/root/npm/bin/yo -> /root/npm/lib/node_modules/yo/lib/cli.js
/root/npm/bin/yo-complete -> /root/npm/lib/node_modules/yo/lib/completion/index.js

> spawn-sync@1.0.15 postinstall /root/npm/lib/node_modules/yo/node_modules/spawn-sync
> node postinstall

module.js:487
    throw err;
    ^

Error: Cannot find module '/root/npm/lib/node_modules/yo/node_modules/spawn-sync/postinstall'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! spawn-sync@1.0.15 postinstall: `node postinstall`
```
