### ISSUE TITLE
dh key is too small

### ISSUE THREAD

**Issue by razorSpirit** [npm/npm#14109]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [ ] npm is producing an incorrect install.
- [ ] npm is doing something I don't understand.
- [x ] Other (_see below for feature requests_):
#### What's going wrong?

dh key is too small when attempting npm install && npm start
#### How can the CLI team reproduce the problem?

https://gist.github.com/razorSpirit/45d59a604b8ccbcc09361d68f9f936da.js

git clone https://github.com/electron/electron-quick-start
cd electron-quick-start
npm install && nam start

supporting information:
- `npm -v` prints: 3.6.0
- `node -v` prints: v5.6.0
- `npm config get registry` prints: https://registry.npmjs.org/
- Windows, OS X, or Linux?: MAC OS X
- Network issues:
  - Geographic location where npm was run:
  - [x ] I use a proxy to connect to the npm registry.
  - [x ] I use a proxy to connect to the web.
  - [x ] I use a proxy when downloading Git repos.
  - [ ] I access the npm registry via a VPN
  - [ ] I don't use a proxy, but have limited or unreliable internet access.
- Container:
  - [ ] I develop using Vagrant on Windows.
  - [x
    [npm-debug.log.txt](https://github.com/npm/npm/files/497919/npm-debug.log.txt)
  
  ] I develop using Vagrant on OS X or Linux.
  - [ ] I develop / deploy using Docker.
    - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by othiym23** [comment]
```
35 silly fetchPackageMetaData Error: write EPROTO 140735198502912:error:14082174:SSL routines:ssl3_check_cert_and_algorithm:dh key too small:../deps/openssl/openssl/ssl/s3_clnt.c:3615:
```

This is an error at the network layer, coming from Node.js / Node's embedded version of OpenSSL. Unfortunately, this isn't something that the npm CLI can do much about. Does the problem recur if you switch to either Node.js LTS (4.6.0) or the current version (6.7.0)? Node.js 5.x is no longer supported, per their own LTS policy, and `npm@3.6.0` is pretty old itself.

**Comment by razorSpirit** [comment]
Thanks!  I re-installed node and it resolved the issue.
