### ISSUE TITLE
ionic installation error

### ISSUE THREAD

**Issue by ghost** [npm/npm#14104]
Facing below issue, on running install command on MAC: sudo npm install -g ionic

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "ionic"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9

npm ERR! Invalid name: "@ionic/app-generators"
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/abc/npm-debug.log

**Comment by abkbynature** [comment]
having the same issue.

**Comment by CooleyGit** [comment]
Same here

**Comment by abkbynature** [comment]
seems like the package name is illegal cause it contains '@' in it.

i worked around it by editing the NPM file 'node_modules/normalize-package-data/lib/fixer.js' and commenting out:

_name.match(/[\/@\s\+%:]/) ||
name !== encodeURIComponent(name) ||_

in the function called **ensureValidName**

**Comment by CooleyGit** [comment]
I fixed my issue by running  `npm uninstall -g ionic ` then `npm install -g ionic `

From the install notes [](https://github.com/driftyco/ionic/blob/master/CHANGELOG.md)

**Comment by reisjean** [comment]
I'm having the same problem... i can't install it

**Comment by reisjean** [comment]
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "ionic"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9

npm ERR! Invalid name: "@ionic/app-generators"
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jeanreis/garconapp/npm-debug.log

**Comment by vcrepin** [comment]
Same problem here. Any solution ?

**Comment by b-alidra** [comment]
Same problem here on Ubuntu 14.04...

**Comment by Gp2mv3** [comment]
Hi,
I have the same problem and think it's due to npm. I updated npm to 3.10 but whn using npm install in my ionic repository, npm 2.5 is installed. This version is used and thus create errors during the installation. I don't understand why npm 2.5 installs as it is not mentioned nowhere in my package.json file.
It also always installs zone.js 0.6.12 whereas I ask for 0.6.25 in my package.json.

Do you think it can be the same issue for you ? And does someone has an idea of this version mismatch ? 

I use n to manage my node versions. I have node 6.7.0 and npm 3.10.8.

Thanks !

**Comment by phuongvo83** [comment]
Hi, I have the same problem. Anyone found a solution for it?

**Comment by xumes** [comment]
Did not work for me

**Comment by brandonbeeler** [comment]
Should this issue be on ionic's repository since the issue appears to be contained to that package?

**Comment by Gp2mv3** [comment]
Personally the problem was that I had a shrinkwrap file. Thus the versions were locked. Deleting the file solved the issue.

**Comment by brandonbeeler** [comment]
I was having this same issue. I was able to resolve by updating to the latest npm.

`sudo npm install -g npm@latest`

**Comment by cballock** [comment]
@brandonbeeler 's solution also worked for me.

**Comment by byjushanmukhan** [comment]
I was having the same issue. Updating to the latest npm resolved it. Thanks brandonbeeler !

**Comment by legodude17** [comment]
Who still has this issue? If you do, try the solution from @brandonbeeler.

**Comment by MelleI** [comment]
Still got the issue. Updated to the latest version of node and npm:

npm ERR! node v7.0.0
npm ERR! npm  v3.10.9
npm ERR! code E404

npm ERR! 404 not found : @ionic/app-generators
npm ERR! 404
npm ERR! 404  '@ionic/app-generators' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'ionic'
npm ERR! 404

Any suggestions?

**Comment by legodude17** [comment]
What is the result of running `npm config get registry` @MelleI?

**Comment by MelleI** [comment]
@legodude17 thank for the tip checking the registry. It was wrong... I changed it to https://registry.npmjs.org/ and it is working now.

`$ npm set registry=https://registry.npmjs.org/`

**Comment by vaibhav915** [comment]
My registry is set to https://registry.npmjs.org/ but still I'm facing issue while installing ionic.
My npm version is 2.7.4 and I'm trying to update it to latest as suggested by @brandonbeeler but it remains on same version. Also it was unable to install Ionic.
I'm using Windows machine.

Error Log:
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ionic"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4

npm ERR! Invalid name: "@ionic/app-generators"
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\vsharma\workspace_Ionic\npm-debug.log

**Comment by Ramesh209025** [comment]
while i'm trying to install ionic on man i'm getting this error in terminal can some please help me

Ramesh$ sudo npm install -g ionic
Password:
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "ionic"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8

npm ERR! Invalid name: "@ionic/app-generators"
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/sasken/npm-debug.log

**Comment by legodude17** [comment]
@vaibhav915 and @Ramesh209025, try updating to the latest version of `npm`.

**Comment by paul-landaeta-tierconnect-com** [comment]
I installed "npm install -g cordova ionic"  it´s working

**Comment by vaibhav915** [comment]
Thanks @legodude17 it worked with latest version of npm.

**Comment by legodude17** [comment]
What about you @Ramesh209025?

**Comment by AhmadSalimAbdulrazzak** [comment]
i need help what should i do,i keep on gettting these after running npm install ionic

module.js:472
    throw err;
    ^

Error: Cannot find module 'internal/fs'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at evalmachine.<anonymous>:17:20
    at Object.<anonymous> (C:\Users\Vaio\AppData\Roaming\npm\node_modules\ionic\node_modules\vinyl-fs\node_modules\graceful-fs\fs.js:11:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)

**Comment by legodude17** [comment]
@AhmadSalimAbdulrazzak please find that issue on the issue tracker as that is not related to the issue that is in this issue. Anyone still having thins issue?

**Comment by Charlotteis** [comment]
@AhmadSalimAbdulrazzak 

Although this is a different issue, I'd say try cleaning your cache and installing again.
`npm cache clean`

If that doesn't work, you might need to delete the cache folder manually too as I see you're on windows. `C:\Users\<USER-NAME>\AppData\Roaming\npm-cache` is the folder you'd need to delete.

Then try installing the package again.

If the problem continues, try opening an issue on the issue tracker as it isn't related to this issue.

🌟

**Comment by zkat** [comment]
This is most likely a problem with the Node.js installer itself: when it upgrades your existing version of npm, it does not remove old files, which causes problems for the npm installation process. Uninstall entirely then reinstall, or remove npm specifically and reinstall npm directly.

**Comment by IronManAtYourService** [comment]
I resolved the Issue. 
The npm need to be updated. 
use the command : 

`npm update -g`

And then

sudo npm install -g ionic

**Comment by legodude17** [comment]
Anyone still have this after the solution above?

**Comment by greggocabral** [comment]
@legodude17 Me! 

I updated npm and node, and registry is ok. im on OSX 10.10.4. Any other suggestions? 
Cheers!

> [21:09:08] grego ~ $>sudo npm install -g ionic
> Password:
> npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> npm WARN deprecated node-uuid@1.4.7: use uuid module instead
> npm WARN deprecated node-uuid@1.3.3: use uuid module instead
> /usr/local/lib
> └── (empty)
> npm WARN In ionic@2.1.18 replacing bundled version of cross-spawn with cross-spawn@4.0.2
> npm WARN In ionic@2.1.18 replacing bundled version of semver with semver@4.2.0
> npm WARN In ionic@2.1.18 replacing bundled version of mime-types with mime-types@2.0.14
> npm WARN In ionic@2.1.18 replacing bundled version of form-data with form-data@0.2.0
> npm WARN In ionic@2.1.18 replacing bundled version of request with request@2.51.0
> npm WARN In ionic@2.1.18 replacing bundled version of ionic-app-lib with ionic-app-lib@2.1.9
> npm ERR! Darwin 14.4.0
> npm ERR! argv "/usr/local/Cellar/node/0.12.2_1/bin/node" "/usr/local/bin/npm" "install" "-g" "ionic"
> npm ERR! node v6.4.0
> npm ERR! npm  v4.0.5
> npm ERR! path /usr/local/lib/node_modules/.staging/ansi-392b32ed
> npm ERR! code ENOENT
> npm ERR! errno -2
> npm ERR! syscall rename
> npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/ansi-392b32ed' -> '/usr/local/lib/node_modules/ionic/node_modules/cordova-lib/node_modules/ansi'
> npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/ansi-392b32ed' -> '/usr/local/lib/node_modules/ionic/node_modules/cordova-lib/node_modules/ansi'
> npm ERR! enoent This is most likely not a problem with npm itself
> npm ERR! enoent and is related to npm not being able to find a file.
> npm ERR! enoent 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /Users/grego/npm-debug.log
>

**Comment by greggocabral** [comment]
Finally fixed after uninstalling ionic and installing it back 
`sudo npm uninstall ionic -g`
`sudo npm install ionic -g`

**Comment by meikelmosby** [comment]
thanks! @greggocabral solution worked fine for me. Before i did clean up the npm cache and i did update npm to the latest version. at the end i executed the commands @greggocabral posted and it worked just fine

**Comment by qiluo** [comment]
Upgrade NPM to latest did the work

**Comment by linkstrifer** [comment]
@MelleI fix work for me, just change the registry

`$ npm set registry=https://registry.npmjs.org/`

**Comment by dougwo** [comment]
I changed the registry, updated to latest npm, uninstalled and then reinstalled. Finally worked. This is on Sierra latest updates. Thanks for all the hele guys! This is a good thread.

**Comment by frayeralex** [comment]
I run next commands (Ubuntu 15.10 node v6.9.5)
`$ sudo npm install -g npm@latest`
`$ npm -v` -> 4.4.1 in my case
`$ sudo npm uninstall ionic -g`
`$ sudo npm install ionic -g`
 It`s help me! `$ npm update -g` updated only to 3.*

**Comment by sanjeevch419** [comment]
I tried every step in this thread. But unfortunately didn't work for me. Still getting error

 npm -v
4.4.1
 node -v
v6.9.5
 sudo npm uninstall ionic -g
 sudo npm install ionic -g
npm ERR! code E404
npm ERR! 404 User not found : @ionic/app-generators
npm ERR! 404 
npm ERR! 404  '@ionic/app-generators' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'ionic'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by Anuj-Kumar-Sharma** [comment]
# **Solved it**
I was facing the same deprecated errors, what is did was uninstall/reinstall Node.js -> cleaning caches with CCleaner -> open cmd with admin permission -> install cordova first and then ionic.
**worked like a charm.**
comment below if you still face any problems ;)

**Comment by huskynation** [comment]
After uninstalling an old version of NodeJS I ran the steps below and it worked.

* `nom cache clean`
* `sudo npm install --save-dev --save-exact @ionic/cli-plugin-cordova@latest`
* `npm set registry=https://registry.npmjs.org/`
* `sudo npm install -g ionic`
