### ISSUE TITLE
Npm start is not working, so I can't go to localhost

### ISSUE THREAD

**Issue by majacar** [npm/npm#14112]
Hi! I'm opening this issue because:
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.

#### What's going wrong?
So, when I wrote "npm install" it does install something, but in node_modules folder I am missing some folders that should be there, such as: shelljs, karma-requirejs, requirejs, karma-scriptlauncher.

When I type npm start, I get this kind of error:
Maja@Maja-PC MINGW32 /c/projects/templatestore (master)
$ npm start

> angular-seed@0.0.0 prestart C:\projects\templatestore
> npm install

npm ERR! Error: spawn ENOENT
npm ERR!     at errnoException (child_process.js:980:11)
npm ERR!     at Process.ChildProcess._handle.onexit (child_process.js:771:34)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! cwd C:\projects\templatestore
npm ERR! node -v v0.10.13
npm ERR! npm -v 1.3.2
npm ERR! syscall spawn
npm ERR! code ENOENT
npm ERR! errno ENOENT

### supporting information:

 - `npm -v` prints: command not found
 - `node -v` prints: command not found
 - `npm config get registry` prints: https://registry.npmjs.org/

 - Windows, OS X, or Linux?: Windows
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

Thank you!

**Comment by KenanY** [comment]
@majacar `npm@1.3` is years old and is no longer supported. Could you try updating to `npm@2` or `npm@3` first?

**Comment by fizzvr** [comment]
Update your develop environment, i got this :lock: 
```json
"engines": {
    "git": "2.10",
    "node": "6.6",
    "npm": "3.10",
    "ruby": "2.3"
  }
```

**Comment by majacar** [comment]
Thank you! I've solved this, now everything works fine...
I've found same solution in this link, so maybe someone will have benefit from this also: http://www.bogotobogo.com/AngularJS/AngularJS_Seed_for_Apps_angular-seed.php

The first sentence about Node.js is skipped in tutorial I'm watching, so I've made stupid mistake :)
