### ISSUE TITLE
npm is producing an incorrect install: npm install appium@1.6.0-beta1 -g

### ISSUE THREAD

**Issue by wanwan001** [npm/npm#14118]
I'm opening this issue because:   npm is producing an incorrect install.
 
I'm intending to install appium  through terminal: npm install appium@1.6.0-beta1 -g, but it's failed

The log is:
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "appium@1.6.0-beta1" "-g"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9

npm ERR! shasum check failed for /var/folders/tf/89068tvn199bhwpk5r3hg03h0000gn/T/npm-595-013006a5/registry.npmjs.org/appium/-/appium-1.6.0-beta1.tgz
npm ERR! Expected: 853eebbd422cdf5cad65d98b4e1b8132146a2850
npm ERR! Actual:   c3354168800c53dfc5691493d204ec7512c98eee
npm ERR! From:     https://registry.npmjs.org/appium/-/appium-1.6.0-beta1.tgz

I have tried to solve this problem by searching the internet, but i failed. Hoping for some help, thank you very much!

**Comment by ajmas** [comment]
What is the file size of /var/folders/tf/89068tvn199bhwpk5r3hg03h0000gn/T/npm-595-013006a5/registry.npmjs.org/appium/-/appium-1.6.0-beta1.tgz . If you see something less than a few kilobytes, there is a good chance this is an HTML file and not an archive. Try opening in an editor to check what the file contains.

You possibly try clearing the cache: ```npm cache clear```

**Comment by wanwan001** [comment]
@ajmas your answer has helped me, I feel embarrassed to say thanks so late...

**Comment by KenanY** [comment]
Closing as resolved.
