### ISSUE TITLE
Running npm version does not work in a Docker container with a mounted package.json

### ISSUE THREAD

**Issue by LongYC** [npm/npm#14124]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [ ] npm is producing an incorrect install.
- [x] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
#### What's going wrong?

Running `npm version` inside a Docker container does not work with a mounted package.json.

From npm-debug.log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   '--no-git-tag-version',
1 verbose cli   'version',
1 verbose cli   'patch' ]
2 info using npm@3.10.3
3 info using node@v6.7.0
4 verbose version not tagging in git
5 info lifecycle temp@1.0.1~preversion: temp@1.0.1
6 silly lifecycle temp@1.0.1~preversion: no script for preversion, continuing
7 verbose version.write data { name: 'temp', version: '1.0.1' } to package.json
8 verbose stack Error: EBUSY: resource busy or locked, rename '/usr/src/app/package.json.1006840457' -> '/usr/src/app/package.json'
8 verbose stack     at Error (native)
9 verbose cwd /usr/src/app
10 error Linux 3.16.0-4-amd64
11 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "--no-git-tag-version" "version" "patch"
12 error node v6.7.0
13 error npm  v3.10.3
14 error path /usr/src/app/package.json.1006840457
15 error code EBUSY
16 error errno -16
17 error syscall rename
18 error EBUSY: resource busy or locked, rename '/usr/src/app/package.json.1006840457' -> '/usr/src/app/package.json'
19 error If you need help, you may report this error at:
19 error     <https://github.com/npm/npm/issues>
20 verbose exit [ -16, true ]
```

However, when I just write to the mounted package.json using, say, `echo`, the file can be written without problem. Most issues I searched related to `EBUSY` are Windows specific problem, thus I'm raising this here.
#### How can the CLI team reproduce the problem?

First, build a Docker image with npm, e.g.

``` Dockerfile
FROM node:6
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY . /usr/src/app/
ENTRYPOINT ["/usr/local/bin/npm"]
CMD ["help"]
```

Then, start a container with the image built, mount a package.json from the host, e.g. `docker run --name [CONTAINER_NAME] -v /my/host/package.json:/usr/src/app/package.json [DOCKER-IMAGE-NAME] --no-git-tag-version version patch`.
### supporting information:
- `npm -v` prints: 3.10.3
- `node -v` prints: v6.7.0
- Windows, OS X, or Linux?: Linux
- Container:
  - [ ] I develop using Vagrant on Windows.
  - [ ] I develop using Vagrant on OS X or Linux.
  - [x] I develop / deploy using Docker.
  - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by csuarez** [comment]
I'm having the same issue

**Comment by stefanfisk** [comment]
I believe this is caused by npm trying to do an atomic write of `package.json`, which fails because mounted files cannot be renamed. If there was an option to make npm overwrite `package.json` in-place this might resolve itself.
