### ISSUE TITLE
npm install -g apiconnect errors

### ISSUE THREAD

**Issue by pkeeler** [npm/npm#14126]
#### I'm opening this issue because:

  - [x

 ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:3.10.8
 - `node -v` prints:v4.6.0
 - `npm config get registry` prints:
 - Windows, OS X, or Linux?:Windows 10
 - Network issues:
   - Geographic location where npm was run:UK
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
Closing since this issue is blank; no details are provided so it is impossible for someone like to me to provide any solutions.
