### ISSUE TITLE
Error when installing sudo npm install -g homebridge on OS X Sierra

### ISSUE THREAD

**Issue by MrGAC** [npm/npm#14127]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I am getting an error message when running the command sudo npm install -g homebridge in MacOSX Sierra.

#### How can the CLI team reproduce the problem?

https://gist.github.com/MrGAC/63cd92d74052c10d013fe65c448b7b0a

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X, or Linux?: OS X
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@MrGAC Thank you for the `npm-debug.log`.The log says you are running `npm install -g npm@latest`, but you say you are running `sudo npm install -g homebridge`. Could you please clarify?

**Comment by MrGAC** [comment]
@kenanY I checked the site for similar errors and one suggested running the  npm install -g npm@latest to install the most current version. It did not run either. Should I run sudo npm install -g homebridge and pull the debug log again?

**Comment by KenanY** [comment]
@MrGAC Let's see the `sudo npm install -g homebridge` log.

**Comment by MrGAC** [comment]
@kenanY <script src="https://gist.github.com/MrGAC/c2957578944839523598f41d73456970.js"></script>

**Comment by MrGAC** [comment]
I've also tried the --unsafe-perm flag with no luck. I have tried installed on three different Macs running sierra and get the same error on all three.

**Comment by KenanY** [comment]
Yeah, I don't know what this means:

```
736 error xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
```

hopefully a macOS user chimes in :)

**Comment by seantcoyote** [comment]
Try opening XCode and accepting the (updated) terms and conditions for their Developer Tools (a popup window will come up when you start XCode, if this is the issue). When Apple updates XCode and their developer tools (which always happens with an OS update), it can mess with your dev environment (like disabling gcc, which npm depends on) until you accept the terms and conditions.

**Comment by MrGAC** [comment]
@seantcoyote I'll give it a try when I get home. Thanks!

**Comment by KenanY** [comment]
@MrGAC Still seeing this issue?

**Comment by MrGAC** [comment]
I was able to get it installed. I am not sure that Xcode was the issue, as nothing updated. I had to uninstall everything and start over and it worked like a charm.
