### ISSUE TITLE
npm@3 install followed by npm dedupe does (a lot of) work

### ISSUE THREAD

**Issue by SimenB** [npm/npm#14134]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [ ] npm is producing an incorrect install.
- [x] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
#### How can the CLI team reproduce the problem?

Check out https://github.com/SimenB/stylint-stylish
run `npm i` followed by `npm dedupe`

Observe as 20-30 deps are deuped. Isn't npm@3 supposed to have a deduped `node_modules` on a clean install?

E.g. `npm ls glob` before and after dedupe:

```
stylint-stylish@1.3.3 /Users/simen/Development/stylint-stylish
├─┬ ava@0.16.0
│ └─┬ chokidar@1.6.0
│   └─┬ fsevents@1.0.14
│     └─┬ node-pre-gyp@0.6.29
│       └─┬ rimraf@2.5.3
│         └── glob@7.0.5
├─┬ babel-cli@6.16.0
│ └── glob@5.0.15
├─┬ eslint@3.6.1
│ └── glob@7.1.0
├─┬ nyc@8.3.0
│ └── glob@7.0.6
└─┬ stylint@1.5.6
  └── glob@7.0.4
```

After:

```
stylint-stylish@1.3.3 /Users/simen/Development/stylint-stylish
├─┬ babel-cli@6.16.0
│ └── glob@5.0.15
├─┬ eslint@3.6.1
│ └── glob@7.1.0
└─┬ stylint@1.5.6
  └── glob@7.0.4
```
### supporting information:
- `npm -v` prints: 3.10.8
- `node -v` prints: 6.6.0
- `npm config get registry` prints: https://registry.npmjs.org/
- Windows, OS X, or Linux?: MacOS Sierra
- Network issues:
  - Geographic location where npm was run:
  - [ ] I use a proxy to connect to the npm registry.
  - [ ] I use a proxy to connect to the web.
  - [ ] I use a proxy when downloading Git repos.
  - [ ] I access the npm registry via a VPN
  - [ ] I don't use a proxy, but have limited or unreliable internet access.
- Container:
  - [ ] I develop using Vagrant on Windows.
  - [ ] I develop using Vagrant on OS X or Linux.
  - [ ] I develop / deploy using Docker.
  - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by cliffkoh** [comment]
@SimenB: No, npm install in npm3 does not attempt to do the minimal work. It installs based on alphabetical order... Dedupe then tries to find the minimal set of packages that fulfills all requirements while minimizing duplication, which install does not do.

**Comment by SimenB** [comment]
This (admittedly old) [comment](https://github.com/npm/npm/issues/8816#issuecomment-118449696) says `dedupe` is unecesarry with npm@3, which should indicate that it shouldn't do much (if any) work

**Comment by iarna** [comment]
with npm3:

To the best of my knowledge, outside of scenarios involving bundled dependencies and shrinkwraps, `npm dedupe` on a fresh install will never do anything.

What npm3's dedupe does is walk through the tree seeing if it can hoist something to the top level OR drop it from the tree entirely. Neither of those will ever be possible with a fresh npm3 tree as that's the core installer algorithm now.

When is it useful? After a series of module updates and/or package changes it is possible for your tree to end up in a state that `npm dedupe` will help flatten back out.

What it _doesn't_ do is try to find the ideal set of versions to install that would produce a minimal tree.

Now... about those caveats…

Shrinkwraps get to define exactly what your tree looks like. If you don't have one, but a dependency of yours does then it will control how that dependencies own dependencies are installed. `npm install` won't try to reshape that– it takes your shrinkwrap at its word.

Bundled dependencies are similar: We take them into the tree as is, so they won't be hoisted up the tree to allow greater deduplication.

If your scenario above is happening because of either of these then I _think_ it's working as intended. If neither shrinkwraps nor bundled dependencies are in play though, then this looks like a bug to me.

**Comment by iarna** [comment]
So checking your repro, the following modules have bundled dependencies (indicating they want us to use the code bundled in the published artifact instead of downloading our own version/copy):

* `fsevents`
* `nyc`

And those are the two that have their extra globs removed, so I believe this is working as intended.

**Comment by SimenB** [comment]
Hmm, ok.
Shouldn't `dedupe` respect bundledDependencies like `install` does? Probably a reason why they're bundled, right? So its only use case would be to create a "just like fresh install" environment (minus new versions of dependencies in semver range, I suppose).

I also get why I didn't find any bundled deps when grepping

![image](https://cloud.githubusercontent.com/assets/1404810/19254173/591b62c4-8f51-11e6-9460-712c446f2e3e.png)

Heh. Should npm warn on that typo? When nyc, maintained by a guy working for npm inc, makes the [mistake](https://github.com/istanbuljs/nyc/blob/fad3586cae6ab7f272a2ea5824430c8f9f2a3f9a/package.json#L126), it's probably widespread, so might be very noisy. But at publish-time perhaps?

There's even a package dedicated to updating it getting the wrong name: https://www.npmjs.com/package/bundle-dependencies

Anyways, I just disappeared down a rabbit hole. Feel free to close if you don't think there are any actionable points here!

**Comment by cliffkoh** [comment]
Thanks for the clarification @iarna.  I literally have a repro here where dedupe after a fresh install does a takes a really long time to loadDepsIntoIdealTree, performs a whole bunch of things and additionally result in a whole bunch of missing packages (which an attempt to then generate a shrinkwrap complains about)...

```8 verbose stack Error: Problems were encountered
8 verbose stack Please correct and try again.
8 verbose stack missing: esprima@^2.7.1, required by escodegen@1.8.0
8 verbose stack missing: minimatch@^2.0.1, required by glob@4.5.3
8 verbose stack missing: through2@0.6.3, required by gulp-bust@0.2.2
8 verbose stack missing: chalk@^0.5.1, required by gulp-util@3.0.3
8 verbose stack missing: through2@^0.6.3, required by gulp-util@3.0.3
8 verbose stack missing: chalk@^0.5.0, required by gulp-util@2.2.20
8 verbose stack missing: chalk@^0.5.0, required by gulp-util@2.2.20
8 verbose stack missing: chalk@^0.5.1, required by gulp-ftp@1.0.1
8 verbose stack missing: through2@^0.6.1, required by gulp-ftp@1.0.1
8 verbose stack missing: through2@^0.6.1, required by gulp-minify-css@0.3.11
8 verbose stack missing: chalk@^0.5.0, required by gulp-util@2.2.20
8 verbose stack missing: through2@^0.6.1, required by gulp-rev@2.0.1
8 verbose stack missing: through2@^0.6.1, required by gulp-sourcemaps@1.2.8
8 verbose stack missing: lodash@^2.4.1, required by gulp-texttojs@1.0.3
8 verbose stack missing: chalk@^0.5.0, required by gulp-util@2.2.20
8 verbose stack missing: lodash@~2.4.1, required by globule@0.2.0
8 verbose stack missing: minimatch@^2.0.10, required by readdirp@2.0.0
8 verbose stack missing: rimraf@~2.2.6, required by temp@0.8.3
8 verbose stack missing: through2@^0.6.1, required by vinyl-buffer@1.0.0
8 verbose stack missing: through2@^0.6.1, required by vinyl-source-stream@1.1.0```

Let me see if I can simplify the repro somewhat and eliminate the usage of private repos... it isn't very actionable as it is at the moment. (Does dedupe generate a verbose log somewhere?)

**Comment by cliffkoh** [comment]
@iarna just to close out the loop - confirmed that the existence of a package published with shrinkwrap file was causing npm dedupe to behave in a really regressive behavior. It additionally "breaks" the tree after the command executes.

By removing the shrinkwrap publishing in that package, dudupe indeed does nothing after a fresh install. 

Perhaps this issue needs to be re-classified as a documentation gap that dedupe does not work with packages that has bundledDependencies or shrinkwrap...

**Comment by SimenB** [comment]
Deduping breaking an install, regardless of the presence of shrinkwrap or bundled deps, sounds like a serious bug.

**Comment by raijinsetsu** [comment]
Any word on this?

We're seeing a lot of wonkiness in the node_modules folder structure after a clean install and we were using dedupe to clean it up but this has caused adverse effects elsewhere.

We expect the node_modules directory structure to be the same after a clean install as after running "npm dedupe" - the documentation seems to say that this is why dedupe exists. Additionally, we expect this not to modify the data returned by "npm ls". In both cases, our expectations are not met.

Modules with the same version and shared by multiple direct dependencies are not being placed into the root node_modules folder upon install. According to @iarna's entry from Oct10, this is to be expected if the parent module is shrink wrapped or has bundled the child module. "dedupe" does not follow the same logic.

"npm ls" output changes after a dedupe - modules that were listed as a dependency of another module have moved "up the tree". This makes it difficult to get a full picture of all dependencies but maybe this is an issue specific to "npm ls" tree view as I see it do the same thing if I manually "dedupe" a package myself.
