### ISSUE TITLE
bug: npm conf.get do not return anything but write on stdout

### ISSUE THREAD

**Issue by jmfrancois** [npm/npm#14138]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [ ] npm is producing an incorrect install.
- [ ] npm is doing something I don't understand.
- [x] Other (_see below for feature requests_):

I just don't succeed in getting npm configuration in a script.
#### What's going wrong?

I have the following script that I would like to get working.
The goal is to get the configuration registry from npm

``` javascript
var npm = require('npm');
npm.load((err, conf) => {
    var a = conf.get('registry');
    console.log('a', a);
});
```

This script output is:

```
undefined
> https://registry.npmjs.org/
undefined
a undefined

>
```

when it should be

```
a https://registry.npmjs.org
>
```

This show me conf.get is doing something weird. It seems that it write to the sdtout and do not return anything.

So the question is how could I get that information in a script.
#### How can the CLI team reproduce the problem?

Copy paste the script and look at the output
### supporting information:
- `npm -v` prints: 2.15.9
- `node -v` prints: v4.5.0
- `npm config get registry` prints: https://registry.npmjs.org/
- Windows, OS X, or Linux?: OS X

**Comment by legodude17** [comment]
Can confirm that this happens to me on OS X too.
