### ISSUE TITLE
unable to start npm in mac(using mamp)

### ISSUE THREAD

**Issue by satyateja-a** [npm/npm#14132]
[npm-debug copy.txt](https://github.com/npm/npm/files/502214/npm-debug.copy.txt)

#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@satyateja-a Looks like your `"start"` script is throwing an error. Does

```
webpack --config www/server/webpack.js --watch --colors
```

work in your command-line?

**Comment by KenanY** [comment]
Closing due to no response.
