### ISSUE TITLE
Error: EPERM: operation not permitted, rename while running Jenkins build on Windows machine

### ISSUE THREAD

**Issue by irfspy** [npm/npm#14136]
I guess this problem is random, linked to some file locks or so....

error : npm ERR! Windows_NT 6.1.7601
error : npm ERR! argv "D:\SharedComponents\NodeJs\4.4.2\node.exe" "D:\NodeJs\4.4.2\node_modules\npm\bin\npm-cli.js" "install" "--no-optional"
error : npm ERR! node v4.4.2
 error : npm ERR! npm  v3.8.5
 error : npm ERR! path C:\Users\AppData\Roaming\npm-cache\readable-stream\2.1.4\package.tgz.1363764457
 error : npm ERR! code EPERM
 error : npm ERR! errno -4048
 error : npm ERR! syscall rename
 error : npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\AppData\Roaming\npm-cache\readable-stream\2.1.4\package.tgz.1363764457' -> 'C:\Users\AppData\Roaming\npm-cache\readable-stream\2.1.4\package.tgz'
 error : npm ERR!     at Error (native)
 error : npm ERR!  { [Error: EPERM: operation not permitted, rename 'C:\Users\AppData\Roaming\npm-cache\readable-stream\2.1.4\package.tgz.1363764457' -> 'C:\Users\AppData\Roaming\npm-cache\readable-stream\2.1.4\package.tgz']
error : npm ERR!   errno: -4048,
error : npm ERR!   code: 'EPERM',
error : npm ERR!   syscall: 'rename',
error : npm ERR!   path: 'C:\Users\cciserver\AppData\Roaming\npm-cache\readable-stream\2.1.4\package.tgz.1363764457',
error : npm ERR!   dest: 'C:\Users\AppData\Roaming\npm-cache\readable-stream\2.1.4\package.tgz' }
error : npm ERR!
error : npm ERR! Please try running this command again as root/Administrator.
error : npm ERR! Please include the following file with any support request:
error : npm ERR!     D:\npm-debug.log
error MSB3073: The command ""....\NodeJs\4.4.2\npm.cmd" install --no-optional" exited with code -4048.

**Comment by legodude17** [comment]
Try what the error message says, run the command as root/Admin. Also can you post the command that you are running when you get this?

**Comment by irfspy** [comment]
"D:\\NodeJs\\4.4.2\\node.exe"      "D:\\NodeJs\\4.4.2\\node_modules\\npm\\bin\\npm-cli.js" "run" "lint"

**Comment by legodude17** [comment]
Your original post has the argv as `npm install --no-optional`. Is it both? It seems very odd that `npm run lint` would be trying to rename things.
