### ISSUE TITLE
NPM NOT INSTALLING

### ISSUE THREAD

**Issue by sanmist91** [npm/npm#14133]
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova" "ionic"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9

npm ERR! shasum check failed for C:\Users\ASUS\AppData\Local\Temp\npm-7704-a31bc315\registry.npmjs.org\ionic\-\ionic-2.1.0.tgz
npm ERR! Expected: cc4218ec13f31b635c1119c9defae5b2bad31335
npm ERR! Actual:   dd20c915e058fa1af5933d6c31eef25c03f6aa7e

npm ERR! From:     https://registry.npmjs.org/ionic/-/ionic-2.1.0.tgz

**Comment by KenanY** [comment]
@sanmist91 Have you tried running `npm cache clean`? Does this happen with other packages? Are you behind a proxy or firewall?

**Comment by ajmas** [comment]
What are the contents of "C:\Users\ASUS\AppData\Local\Temp\npm-7704-a31bc315\registry.npmjs.org\ionic-\ionic-2.1.0.tgz"?

Sometimes a package will appear to be downloaded, but actually are an HTML page with an error in it. A usual indicator that something is not right is if the file size looks too small.

**Comment by acourtney2015** [comment]
I experiencing a similar error. NPM unable to install botbuilder. I am working through Microsoft's Virtual Academy tutorial for botbuilder. In Visual Studio Code-created package.json file containing {}; cd to the json file directory- ran npm install botbuilder --save as per the tutorial and received the following error:
 npm ERR! Failed to parse package.json data.                                  
npm ERR! package.json must be actual JSON, not just JavaScript.              
npm ERR!                                                                     
npm ERR! This is not a bug in npm.                                           
npm ERR! Tell the package author to fix their package.json file. JSON.parse 

Any suggestions on how to proceed to install/use botbuilder? I have also tried downloading and installing the zip and running npm install botbuilder inside the Node folder contained in the zip and got the same error. Any work around or fixes would be appreciated. Thanks!

**Comment by ajmas** [comment]
@acourtney2015 this is a different issue, best open up a separate issue, but I would suggest taking a look at the project's package.json file. Please put follow-ups in a new issue - thanks

**Comment by KenanY** [comment]
Closing due to no response from @sanmist91.
