### ISSUE TITLE
Set everything correctly but still cannot get NPM to pass proxy on windows.

### ISSUE THREAD

**Issue by ForsakenEcho** [npm/npm#14130]
> npm config set proxy http://proxy.myorg.org.au:8080
> npm config set https-proxy http://proxy.myorg.org.au:8080

node v6.7.0
npm  v3.10.3

registry = "http://registry.npmjs.org/"

then
excute npm install
get a buntch of (node:5244) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): PopsicleError: Unable to connect to "https://api.typings.org/entries/dt/core-js/tags/0.0.0%2B20160725163759"
Caused by: Error: connect ECONNREFUSED [ip.add.ress:port]

**Comment by pkunze** [comment]
Typings doesn't seem to use npm config.  
Try creating a `.typingsrc`-file in your projects root with the following content:

```
{
  "proxy": "http://proxy.myorg.org.au:8080",
  "rejectUnauthorized": false
}
```

This works on my WIN10 machine.

**Comment by backrowbloke** [comment]
What worked for me is using Fiddler
Run Fiddler and ensure it's set to use the system proxy (e.g. Windows settings)
set npm proxy to be **http://127.0.0.1:8888** (the default fiddler settings - or whateer you have defined in Fiddler)

(this also helped other applications like Visual Studio Code, Notepad++ which also couldn't pick up the automatic proxy)

Downside is of course that Fiddler is running

Hope this helps
