### ISSUE TITLE
npm crashing

### ISSUE THREAD

**Issue by tatkins1** [npm/npm#14140]
#### I'm opening this issue because:

  - [x ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints: 3.10.8
 - `node -v` prints: v5.4.1
 - `npm config get registry` prints: https://registry.npmjs.org/

 - Windows, OS X, or Linux?: OS X
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by ajmas** [comment]
Any chance you can include the output you get when things crash?

**Comment by KenanY** [comment]
Will reopen when more information is provided. Currently impossible to provide any support :(
