### ISSUE TITLE
Provide an option to install 'global' only for current user

### ISSUE THREAD

**Issue by ajmas** [npm/npm#14144]
On MacOS X the `npm install -g` requires sudo. This is an issue for cases where the user does not have sudo access, but wishes to have a command in their path.
I would like to propose an option for installing local to an account. Something along the lines of:

```
> npm install -g mypackage
# detects user does not have write permissions to the directory owned by the system
# prompts: 
You lack write permissions to global location. Do you wish to install for
your user only? [y/n/always]
# if the npm bin directory path is not in PATH
Do you wish to add ~/npm/bin to your search PATH? [Y/n]
```

An alternative would be to have a  new option with a local version of the global command, maybe something like `npm install --G` ( or --glocal )? -- I had suggested '-l/--local', but '-l' is already used.

**Comment by legodude17** [comment]
Where would the global for only 1 user go to?

**Comment by ajmas** [comment]
Maybe ~/npm or ~/.npm , with a bin directory, as current?

**Comment by legodude17** [comment]
That makes sense, maybe there could be a separate package for changing a user's $PATH. It would be very helpful.
