### ISSUE TITLE
NPM issue with blockapps-bloc installation

### ISSUE THREAD

**Issue by Rashme** [npm/npm#14141]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [*] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

When i install bloc from blockapps using the command : npm install -g blockapps-bloc, it ends up with not ok code and error.

#### How can the CLI team reproduce the problem?

Try to install blockapps bloc the command:  npm install -g blockapps-bloc

This ends up with the below log file:
npm-debug.log file
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'blockapps-bloc' ]
2 info using npm@1.3.10
3 info using node@v0.10.25
4 verbose cache add [ 'blockapps-bloc', null ]
5 verbose cache add name=undefined spec="blockapps-bloc" args=["blockapps-bloc",null]
6 verbose parsed url { protocol: null,
6 verbose parsed url   slashes: null,
6 verbose parsed url   auth: null,
6 verbose parsed url   host: null,
6 verbose parsed url   port: null,
6 verbose parsed url   hostname: null,
6 verbose parsed url   hash: null,
6 verbose parsed url   search: null,
6 verbose parsed url   query: null,
6 verbose parsed url   pathname: 'blockapps-bloc',
6 verbose parsed url   path: 'blockapps-bloc',
6 verbose parsed url   href: 'blockapps-bloc' }
7 silly lockFile d112b707-blockapps-bloc blockapps-bloc
8 verbose lock blockapps-bloc /home/rashmerajendran/.npm/d112b707-blockapps-bloc.lock
9 silly lockFile d112b707-blockapps-bloc blockapps-bloc
10 silly lockFile d112b707-blockapps-bloc blockapps-bloc
11 verbose addNamed [ 'blockapps-bloc', '' ]
12 verbose addNamed [ null, '*' ]
13 silly lockFile 42d7ba32-blockapps-bloc blockapps-bloc@
14 verbose lock blockapps-bloc@ /home/rashmerajendran/.npm/42d7ba32-blockapps-bloc.lock
15 silly addNameRange { name: 'blockapps-bloc', range: '*', hasData: false }
16 verbose url raw blockapps-bloc
17 verbose url resolving [ 'https://registry.npmjs.org/', './blockapps-bloc' ]
18 verbose url resolved https://registry.npmjs.org/blockapps-bloc
19 info trying registry request attempt 1 at 15:52:29
20 verbose etag "D5GA3C1SCUVPE11GATXMGRUYV"
21 http GET https://registry.npmjs.org/blockapps-bloc
22 http 304 https://registry.npmjs.org/blockapps-bloc
23 silly registry.get cb [ 304,
23 silly registry.get   { date: 'Fri, 30 Sep 2016 15:52:29 GMT',
23 silly registry.get     via: '1.1 varnish',
23 silly registry.get     'cache-control': 'max-age=300',
23 silly registry.get     etag: '"D5GA3C1SCUVPE11GATXMGRUYV"',

### supporting information:

 - `npm -v` prints: 1.3.0
 - `node -v` prints: The program 'node' can be found in the following packages:
 * node
 * nodejs-legacy
Try: sudo apt-get install <selected package>
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X, or Linux?: Linux
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [*] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [*] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@Rashme Sorry, `npm@1.3` is years old and is no longer supported. I can reopen this if your issue persists with `npm@2` or `npm@3`.

**Comment by Rashme** [comment]
@KenanY Thanks! I have updated the version now. Still the problem exists. I am new to npm. Please help.

npm -v : 2.7.4

Below is the error i got:
npm ERR! tar.unpack untar error /home/rashmerajendran/.npm/blockapps-bloc/1.2.1/package.tgz
npm ERR! Linux 4.4.0-36-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "blockapps-bloc"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! path /usr/local/lib/node_modules/blockapps-bloc
npm ERR! code EACCES
npm ERR! errno -13

npm ERR! Error: EACCES, mkdir '/usr/local/lib/node_modules/blockapps-bloc'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, mkdir '/usr/local/lib/node_modules/blockapps-bloc']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/local/lib/node_modules/blockapps-bloc',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/usr/local/lib/node_modules/blockapps-bloc',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack:
npm ERR!    [ '/usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:36:23',
npm ERR!      '/usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:46:53',
npm ERR!      'FSReqWrap.oncomplete (fs.js:95:15)' ] }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.
npm ERR! Linux 4.4.0-36-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "blockapps-bloc"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4

npm ERR! Uncaught, unspecified "error" event.
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log

**Comment by Rashme** [comment]
@KenanY I have also upgraded the npm version to the latest. It gives different error. Please check below.

npm -v: 3.10.3

Error:
npm WARN deprecated secp256k1-browserify@0.0.0: secp256k1 now inculdes browser compentents
npm ERR! Linux 4.4.0-36-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "blockapps-bloc"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! file /home/rashmerajendran/.npm/configstore/1.4.0/package/package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! No data, empty input at 1:1
npm ERR!
npm ERR! ^
npm ERR! File: /home/rashmerajendran/.npm/configstore/1.4.0/package/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse
npm ERR! Linux 4.4.0-36-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "blockapps-bloc"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! path npm-debug.log.918615435
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall open

npm ERR! Error: EACCES: permission denied, open 'npm-debug.log.918615435'
npm ERR!     at Error (native)
npm ERR!  { Error: EACCES: permission denied, open 'npm-debug.log.918615435'
npm ERR!     at Error (native)
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'open',
npm ERR!   path: 'npm-debug.log.918615435' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log

**Comment by KenanY** [comment]
@Rashme First error: try prefixing your command with `sudo`. Second error: hmm, try `npm cache clean`?

**Comment by Rashme** [comment]
@KenanY Still not working. It talks about some folder access. Can you please check?

npm ERR! Linux 4.4.0-36-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "blockapps-bloc"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! path /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!     at Error (native)
npm ERR!  { Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!     at Error (native)
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/rashmerajendran/npm-debug.log

**Comment by Rashme** [comment]
@KenanY Thanks a lot! Prefixing with sudo command worked :)
