### ISSUE TITLE
"uid must be an unsigned int" on OS X with latest version of everything

### ISSUE THREAD

**Issue by bjbarouch** [npm/npm#14145]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
"uid must be an unsigned int" error for various installs, for example, jshint -g

Mac OS X (10.12), node.js (v4.6.0) and npm (3.10.8) (registry = https://registry.npmjs.org/)

normal Terminal bash shell, running as root

Debug log file atttached

#### How can the CLI team reproduce the problem?
as indicated -- latest OS X, node, and npm, then npm install -g jshint as root
gist of log file:
[17bfeb75e8188c942063f7931a4d1eae-7b37350f225c4a349673b8d4731cd10353e06eda.zip](https://github.com/npm/npm/files/503971/17bfeb75e8188c942063f7931a4d1eae-7b37350f225c4a349673b8d4731cd10353e06eda.zip)

**Comment by KenanY** [comment]
Looks like another instance of https://github.com/npm/npm/issues/13918.
