### ISSUE TITLE
package.json files for dependencies randomly become unformatted or turn into binary files

### ISSUE THREAD

**Issue by defdata** [npm/npm#14146]
#### I'm opening this issue because:

Packages installed with NPM are working initially and then break. The package.json instead of having json in it reads like a binary file.
#### What's going wrong?

I'm randomly (feels random, probably not) getting errors when I try to use gulp tasks or run npm install. 

Below is the output when running a gulp task:

```
module.js:85
    throw e;
    ^

SyntaxError: Error parsing C:\Users\{username-placeholder}\{project-name-placeholder}\frontend\node_modules\gulp-typescript\package.json: Unexpected token I
    at Object.parse (native)
    at readPackage (module.js:81:52)
    at tryPackage (module.js:91:13)
    at Function.Module._findPath (module.js:153:20)
    at Function.Module._resolveFilename (module.js:323:25)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\{username-placeholder}\{project-name-placeholder}\frontend\gulpfile.js:6:18)
    at Module._compile (module.js:409:26)
```

Below is the output when running `npm install`

```
npm WARN Failed to parse json
npm WARN Unexpected token 'I' at 1:1
npm WARN I��¶wWJl�?3�@�;���>WX☺��k�     �2◄���►g6!�↔#]��0*♫L♀:�|-►2��2§fC#�W�d�♫D��Q���l� D↑
npm WARN ^
npm WARN File: C:\Users\{username-placeholder}\{project-name-placeholder}\frontend\node_modules\diff\package.json
npm WARN Failed to parse json
npm WARN Unexpected token 'I' at 1:1
npm WARN I��¶wWJl�?3�@�;���>WX☺��k�     �2◄��̿��)�Y����☺���~^�u
npm WARN ^
npm WARN File: C:\Users\{username-placeholder}\{project-name-placeholder}\frontend\node_modules\optimist\package.json
npm WARN Failed to parse json
npm WARN Unexpected token 'I' at 1:1
npm WARN I��¶wWJl�?3�@�;���>WX☺��k�     �2◄� �ɦ:�☻���/�zS�l�*�^�Z9����������♠����♠c!��z���
npm WARN ^
npm WARN File: C:\Users\{username-placeholder}\{project-name-placeholder}\frontend\node_modules\sprintf-js\package.json
npm WARN Failed to parse json
npm WARN Unexpected token 'I' at 1:1
npm WARN I��¶wWJl�?3�@�;���>WX☺��k�     �2◄���[�E�҄�.�x�O�d�)▬V��p▼Ͼ� �e�^☻yg97QYl�|��-��y�?
npm WARN ^
npm WARN File: C:\Users\{username-placeholder}\{project-name-placeholder}\frontend\node_modules\underscore.string\package.json
npm WARN Failed to parse json
npm WARN Unexpected token 'I' at 1:1
npm WARN I��¶wWJl�?3�@�;���>WX☺��k�     �2◄��c�Y�!Ƃ�
npm WARN ^
npm WARN File: C:\Users\{username-placeholder}\{project-name-placeholder}\frontend\node_modules\optimist\node_modules\minimist\package.json
npm WARN Failed to parse json
npm WARN Unexpected token 'I' at 1:1
npm WARN I��¶wWJl�?3�@�;���>WX☺��k�     �2◄��W�T���� p�8X�X� ���)►Z�3i��{↨���\v���►)ܵ��Ęd
npm WARN ^
npm WARN File: C:\Users\{username-placeholder}\{project-name-placeholder}\frontend\node_modules\optimist\node_modules\wordwrap\package.json
npm WARN {project-name-placeholder}-Console@ No repository field.
npm WARN {project-name-placeholder}-Console@ No license field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\{username-placeholder}\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.8
npm ERR! path C:\Users\{username-placeholder}\{project-name-placeholder}\frontend\node_modules\ng2-bootstrap
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\{username-placeholder}\{project-name-placeholder}\frontend\node_modules\ng2-bootstrap' -> 'C:\Users\{username-placeholder}\{project-name-placeholder}\frontend\node_modules\.ng2-bootstrap.DELETE'
npm ERR!     at moveAway (C:\Users\{username-placeholder}\AppData\Roaming\npm\node_modules\npm\lib\install\action\finalize.js:38:5)
npm ERR!     at destStatted (C:\Users\{username-placeholder}\AppData\Roaming\npm\node_modules\npm\lib\install\action\finalize.js:27:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:82:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\{username-placeholder}\{project-name-placeholder}\frontend\node_modules\ng2-bootstrap' -> 'C:\Users\{username-placeholder}\{project-name-placeholder}\frontend\node_modules\.ng2-bootstrap.DELETE'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM: operation not permitted, rename 'C:\Users\{username-placeholder}\{project-name-placeholder}\frontend\node_modules\ng2-bootstrap' -> 'C:\Users\{username-placeholder}\{project-name-placeholder}\frontend\node_modules\.ng2-bootstrap.DELETE'] parent: '{project-name-placeholder}-Console' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\{username-placeholder}\{project-name-placeholder}\frontend\npm-debug.log
```

Here is what the package.json's look like when this happens (short snippet) for the npm install command

```
I‹£wWJl‡?3ì@¶;±ð×>WX‘›k¤   ²2¥¢Ég6!ƒ#]ûŸ0*L:ž|-2¸µ2fC#‡WŽdÈDûÄQšõØlù DbqÅ‹¨òø¥ˆ‰“3ØD½ûÎ™º1©/•èƒÌUîøB&_¥¢JBñFø¹'»æ5ýS+a4ñäRùÑà3‚‘±Tbó¹M²sRª Ðñ7¶;``ßªÞó×„zÓcüŽ·G›Rž­²Ýbã7VÂØù±^q•ó”’}³ýYŸHsÊÔ±\Ÿ^»LÓ‘¾gÙ¤ùOýåÅzop²˜ÉšSMÑz   ŽÖù†/~þÖaÝÚeJè'Jö–›ê’hNH)~;gµ°ýyEŠa¬)ÄÆ¸DS”
9Á/M€s×%â&è”Ë3Èè§ÔgP¤MŸAá—<ê
¿ÍŽ
¢ßi5<“äÑˆáá\AÇ§[~ZÊÝNæS^²ctµÄÝr©®ypDÔ²lvŸPBªz¸QD¬Fëƒåd¡]k¥yÀešLx£ÝõúßgÂöÿð{;îö‡«EFÀååÍZ35šuŽ{Ø^ˆã7®È³¢dç6MÖ<ô–¹POiB%±MÈÕµ·n³g/êº¶ô^JÖ…á´ámPwƒÐ™Á?¿}´îÁz´“PJêí¶Ê3°n€âç'+ÿoáætpýUý.R=
```

When the gulp task fails with the error I posted earlier the package.json it refers to is columns of a bunch of numbers like when you open a binary file in a text editor. Running `npm install` will fix that issue, but then messed up the files you see in the `npm install` output. I've tried clearing out my node_modules folder and reinstalling which fixes it temporarily, but eventually this will happen again. I've also tried cleaning the npm cache. 
#### How can the CLI team reproduce the problem?

I'm not sure to be honest. I'd prefer if I could unreproduce it and it would never come back again, but this only started happening after an upgrade to npm 3. When I receive the json its initially correct and formatted correctly, but given a day or two it will turn into a bunch of weird characters.
### supporting information:
- `npm -v` prints: **3.10.8**
- `node -v` prints: **v4.5.0**
- `npm config get registry` prints: **http://registry.npmjs.org/**
- Windows, OS X, or Linux?: **Windows**

**Comment by Njoror** [comment]
Seems to happen consistently after I reboot

**Comment by DavitaMatt** [comment]
Same here. Has been happening for a while now. It only happens after I restart my laptop and only the globally installed packages. Some package.json are fine, but the dependent node modules package.json gets obfuscated. Everyday I have to reinstall packages.

**Comment by legodude17** [comment]
This could be an error with the OS, the internet connection, the tarballs, your cache, or `npm`'s code. Try running `npm cache clean`.  Please check your internet connection.

**Comment by Njoror** [comment]
Internet connection is fine, I've tested it on different networks and have the same issue. I ran npm cache clean and that does not solve the problem. I've uninstalled and reinstalled nodejs and still have the issue. It is only on global packages that this happens. I've worked around it by just referencing local binaries instead, but would be nice if I could figure out how to prevent it from happening.

**Comment by legodude17** [comment]
What sorts of packages does it happen on? What versions? What version of `npm` are you using?

**Comment by fillippeyton** [comment]
This happens to me a lot too; frequently on reboot. Commonly on the [optimist](https://www.npmjs.com/package/optimist) and [hairballl](https://www.npmjs.com/package/hairball) package. I'm running npm `3.10.8` on my Windows 7 machine.

**Comment by sandeepkrpandey** [comment]
This is happening for me too. I need to reinstall local and global package again. For me it happens while running grunt comand.

Error:
SyntaxError: Error parsing C:\Users\username\AppData\Roaming\npm\node_modules\
grunt-cli\node_modules\findup-sync\package.json: Unexpected token ◄ in JSON at p
osition 0
    at Object.parse (native)
    at readPackage (module.js:92:52)
    at tryPackage (module.js:102:13)
    at Function.Module._findPath (module.js:186:20)
    at Function.Module._resolveFilename (module.js:467:25)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
