### ISSUE TITLE
NPM error while installing homebridge.

### ISSUE THREAD

**Issue by Yvoro** [npm/npm#14157]
I updated my Raspberry Pi B+. Now im trying to setup my homekit network but i get this error. I already formatted the SD and downloaded new versions...

npm WARN engine homebridge@0.4.6: wanted: {"node":">=4.3.2"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine hap-nodejs@0.4.11: wanted: {"node":">=4.3.2"} (current: {"node":"0.10.29","npm":"1.4.21"})
/usr/local/bin/homebridge -> /usr/local/lib/node_modules/homebridge/bin/homebridge

> curve25519-n@1.1.0 install /usr/local/lib/node_modules/hap-nodejs/node_modules/curve25519-n
> node-gyp rebuild

make: Entering directory '/usr/local/lib/node_modules/hap-nodejs/node_modules/curve25519-n/build'
  CXX(target) Release/obj.target/curve/node_curve.o
In file included from ../node_curve.cc:9:0:
../node_modules/nan/nan.h:324:47: error: ‘REPLACE_INVALID_UTF8’ is not a member of ‘v8::String’
   static const unsigned kReplaceInvalidUtf8 = v8::String::REPLACE_INVALID_UTF8;
                                               ^
curve.target.mk:82: recipe for target 'Release/obj.target/curve/node_curve.o' failed
make: *** [Release/obj.target/curve/node_curve.o] Error 1
make: Leaving directory '/usr/local/lib/node_modules/hap-nodejs/node_modules/curve25519-n/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Linux 4.4.11+
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/hap-nodejs/node_modules/curve25519-n
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok
npm WARN engine deep-extend@0.4.1: wanted: {"node":">=0.12.0","iojs":">=1.0.0"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/hap-nodejs/node_modules/srp/node_modules/bignum/node_modules/node-pre-gyp/node_modules/request/lib/helpers.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.4.11+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "--unsafe-perm" "homebridge" "hap-nodejs" "node-gyp"
npm ERR! cwd /home/pi
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! path /usr/local/lib/node_modules/hap-nodejs/node_modules/srp/node_modules/bignum/node_modules/node-pre-gyp/node_modules/request/lib/helpers.js
npm ERR! fstream_path /usr/local/lib/node_modules/hap-nodejs/node_modules/srp/node_modules/bignum/node_modules/node-pre-gyp/node_modules/request/lib/helpers.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (evalmachine.<anonymous>:107:15)
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/hap-nodejs/node_modules/ed25519/node_modules/nan/doc/methods.md'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

**Comment by KenanY** [comment]
@Yvoro Does this also occur if you update both Node.js and `npm`?

**Comment by Yvoro** [comment]
@KenanY yep..

**Comment by KenanY** [comment]
@Yvoro Can I see the new logfile?

**Comment by Yvoro** [comment]
@KenanY can you give me the install codes for npm and NodeJs? I will try it again: installing Home bridge and if it won't work ill send you my log file. My log file is a mess right now and i don't know what data you want...

**Comment by KenanY** [comment]
@Yvoro Check out the first two sections of <https://github.com/npm/npm/wiki/Troubleshooting>.

**Comment by Yvoro** [comment]
@KenanY I looked at your link but i can't find the right way to update my npm... Do you have a link for me?

**Comment by KenanY** [comment]
@Yvoro `npm install -g npm@latest`

**Comment by KenanY** [comment]
Closing due to lack of further responses, and also `npm@1` support is going away.

**Comment by sanghviharshit** [comment]
For anyone else coming to this page for similar issue - follow this guide - https://github.com/cflurin/homebridge-punt/wiki/Running-Homebridge-on-a-Raspberry-Pi#troubleshooting

**Comment by Adverte** [comment]
solve the problem steps:

```
sudo npm cache clean -f
sudo npm install -g n
sudo n latest
```
