### ISSUE TITLE
NPM install fail for -g 

### ISSUE THREAD

**Issue by pawanraocse** [npm/npm#14155]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

sudo npm install -g n
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "n"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.8

npm ERR! uid must be an unsigned int

#### How can the CLI team reproduce the problem?
sudo npm install -g n

I guess it is always coming with -g option.

<script src="https://gist.github.com/pawanraocse/fff2eb8cae27672c7c18eb421c6a2855.js"></script>

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
Looks like another instance of https://github.com/npm/npm/issues/13918.
