### ISSUE TITLE
npm install gspeech-api: npm ERR! Error extracting /home/rubiksmomo/.npm/fs/0.0.0/package.tgz archive: ENOENT: no such file or directory, open '/home/rubiksmomo/.npm/fs/0.0.0/package.tgz'

### ISSUE THREAD

**Issue by tubelius** [npm/npm#14151]
#### I'm opening this issue because:
- [x] npm is crashing.
- [ ] npm is producing an incorrect install.
- [ ] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
#### What's going wrong?

"npm install gspeech-api" fails
#### How can the CLI team reproduce the problem?

Commands and errors: https://gist.github.com/tubelius/f0bf8bb20bb4ba523cfa8d6508f4a136
npm-debug.log: https://gist.github.com/anonymous/46fd36800cc42428bf000f26374f0043
### supporting information:
- `npm -v` prints:
  3.10.8
- `node -v` prints:
  v6.7.0
- `npm config get registry` prints:
  https://registry.npmjs.org/
- Windows, OS X, or Linux?:
  [rubiksmomo@nakedman ~]$ uname -a
  Linux nakedman 4.4.21-1-ARCH #1 SMP Thu Sep 15 19:19:13 MDT 2016 armv7l GNU/Linux
- Network issues:
  - Geographic location where npm was run:
  - [ ] I use a proxy to connect to the npm registry.
  - [ ] I use a proxy to connect to the web.
  - [ ] I use a proxy when downloading Git repos.
  - [ ] I access the npm registry via a VPN
  - [ ] I don't use a proxy, but have limited or unreliable internet access.
- Container:
  - [ ] I develop using Vagrant on Windows.
  - [ ] I develop using Vagrant on OS X or Linux.
  - [ ] I develop / deploy using Docker.
  - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by clod81** [comment]
I have same issue on osx. I temporarly fixed like this: 
`ln -s 0.0.2 0.0.0` in `~.npm/fs`
