### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by imj2** [npm/npm#14152]
npm ERR! uid must be an unsigned int
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--g" "yo"
npm ERR! node v4.4.4
npm ERR! npm  v3.10.8

**Comment by KenanY** [comment]
Looks like https://github.com/npm/npm/issues/13918.
