### ISSUE TITLE
Support for more README formats

### ISSUE THREAD

**Issue by obilodeau** [npm/npm#14159]
Feature request

#### What's the feature?

Support other formats than Markdown for the `packages.json` readme.

#### What problem is the feature intended to solve?

Projects who use another documentation language like AsciiDoc can't publish an npm package without having to convert their README to markdown.

#### Is the absence of this feature blocking you or your team? If so, how?

Not blocking, just annoying.

We did a one-time conversion and our npmjs.org README will always be lagging behind our actual github README. At least we can provide a readme in the `packages.json` file and we can keep our README.adoc intact. However, that feature is not documented in the `packages.json` documentation: https://docs.npmjs.com/files/package.json (which should be filed as a separate issue...).

#### Is this feature similar to an existing feature in another tool?

GitHub's README parser supports several markups. AsciiDoc, Textile, ReStructured Text, RDoc, Mediawiki, etc. Full list here: https://github.com/github/markup#markups

#### Is this a feature you're prepared to implement, with support from the npm CLI team?

Unfortunately, no. I'm not confident enough with my javascript skills and I don't have much free time.

#### Closing thoughts

I know this is not a priority for your project but I felt like I needed to register somewhere that this is still a real need.

**Comment by KenanY** [comment]
If this is specifically regarding the website, it may be best opened over [here](https://github.com/npm/www).
