### ISSUE TITLE
NPM install error

### ISSUE THREAD

**Issue by shoaibmalik786** [npm/npm#14153]
#### I'm opening this issue because:

> undefined postinstall /home/deployer/apps/rentiron
> cd client && npm install

npm ERR! Linux 4.4.0-38-generic
npm ERR! argv "/home/deployer/.nvm/versions/node/v6.1.0/bin/node" "/home/deployer/.nvm/versions/node/v6.1.0/bin/npm" "install"
npm ERR! node v6.1.0
npm ERR! npm  v3.8.6
npm ERR! code ENOMEM
npm ERR! errno ENOMEM
npm ERR! syscall spawn

npm ERR! spawn ENOMEM
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues
Killed

npm ERR! Linux 4.4.0-38-generic
npm ERR! argv "/home/deployer/.nvm/versions/node/v6.1.0/bin/node" "/home/deployer/.nvm/versions/node/v6.1.0/bin/npm" "install"
npm ERR! node v6.1.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! undefined postinstall: `cd client && npm install`
npm ERR! Exit status 137
npm ERR! 
npm ERR! Failed at the undefined postinstall script 'cd client && npm install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd client && npm install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/deployer/apps/rentiron/npm-debug.log

**Comment by seprab** [comment]
same problem here

**Comment by azippay** [comment]
Had the same issue. Try:
**sudo npm install reinstall -g**

The from the project folder:
**npm install**

Still need to verify the fix for other projects.
