### ISSUE TITLE
Cannot Install angular-cli

### ISSUE THREAD

**Issue by Brian-V** [npm/npm#14160]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [ x ] npm is producing an incorrect install.
- [ x ] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
#### What's going wrong?

I'm unable to do npm install for angular-cli.  There are multiple errors included in the attached npm-debug.log file.  I have a public/private ssh key pair set up.  Internet connection is good, but it errors out ever time.  Please help!

[npm-debug.log.txt](https://github.com/npm/npm/files/505591/npm-debug.log.txt)
### supporting information:
- `npm -v` prints: 3.10.3
- `node -v` prints: v6.7.0
- `npm config get registry` prints: https://registry.npmjs.org/
- Windows, OS X, or Linux?: Windows 7
- Network issues:
  - Geographic location where npm was run:
  - [ ] I use a proxy to connect to the npm registry.
  - [ ] I use a proxy to connect to the web.
  - [ ] I use a proxy when downloading Git repos.
  - [ ] I access the npm registry via a VPN
  - [ ] I don't use a proxy, but have limited or unreliable internet access.
- Container:
  - [ ] I develop using Vagrant on Windows.
  - [ ] I develop using Vagrant on OS X or Linux.
  - [ ] I develop / deploy using Docker.
  - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by saurav12** [comment]
Same problem occur with me too while running the command `sudo npm install -g angular-cli`
The console shows:

```
npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "anglular-cli"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/anglular-cli
npm ERR! 404
npm ERR! 404  'anglular-cli' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/<username>/npm-debug.log
```
Please help!

**Comment by KenanY** [comment]
@saurav12 You have a typo: `anglular-cli` (an extra "L").

**Comment by saurav12** [comment]
@KenanY Thanks! Sorry its my **BAD**! Finally its up and running.
