### ISSUE TITLE
Setting `NPM_CONFIG_PRODUCTION=true` during install overrides `NODE_ENV` for all npm scripts forever

### ISSUE THREAD

**Issue by tjwebb** [npm/npm#14168]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [ ] npm is producing an incorrect install.
- [x] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
#### What's going wrong?

Setting `NPM_CONFIG_PRODUCTION=true` during install overrides `NODE_ENV` always and forever, no matter what I do. Even `NODE_ENV=development npm start` results in my NODE_ENV being reset to `production`.
#### How can the CLI team reproduce the problem?
1. npm install with NPM_CONFIG_PRODUCTION=true
2. Try to run any npm script with NODE_ENV set to something other than production
3. watch NODE_ENV be overwritten to production
### supporting information:

I run `npm install` produce a build of my project with no devDependencies. I should be able to `npm start` that module with whatever NODE_ENV I want.
- `npm -v` prints: 3.10.3
- `node -v` prints: 6.7.0
- `npm config get registry` prints: https://registry.npmjs.org/
  - Linux

**Comment by kblcuk** [comment]
This seems to work [as intended according to docs](https://docs.npmjs.com/misc/config#production).

**Comment by tjwebb** [comment]
> This seems to work as intended according to docs.
>> Set the NODE_ENV="production" for lifecycle scripts.

Ok, fair enough. This issue remains valid. The documentation does not say that NODE_ENV can't possibly be overridden. It's curious that an install-time environment variable should affect the runtime environment of that build forever, even if it is deployed onto a different machine or environment.

**Comment by em** [comment]
Ran into this today because we use NODE_ENV=staging for doing a staging build, which causes our build script to detect and use our production CDN url instead of staging CDN url. I think it is reasonable and expected that we use NODE_ENV as the authority for the environment. And it's very unexpected / unintuitive for npm to overwrite it.
