### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by GorianDriza** [npm/npm#14169]
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "yo"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3

npm ERR! tarball.destroy is not a function

**Comment by KenanY** [comment]
@GorianDriza Does this also occur with newer versions of `npm`? Could you provide the _full_ `npm-debug.log` as a [gist](https://gist.github.com/)?
