### ISSUE TITLE
Registry returned 401 for GET on https://registry.npmjs.intuit.net/gulp-istanbul

### ISSUE THREAD

**Issue by jay2012** [npm/npm#14176]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [ ] npm is producing an incorrect install.
- [ ] npm is doing something I don't understand.
- [x ] Other (_see below for feature requests_):
#### What's going wrong?

Registry returned 401 for GET on https://registry.npmjs.intuit.net/gulp-istanbul
#### How can the CLI team reproduce the problem?

git clone git@github.intuit.com:Fuego/Fuego-Schema.git

cd Fuego-Schema

npm install
### supporting information:
- `npm -v` prints: 3.9.5
- `node -v` prints: v6.2.2
- `npm config get registry` prints: 

npm info it worked if it ends with ok
npm info using npm@3.9.5
npm info using node@v6.2.2
https://registry.npmjs.intuit.net/
npm info ok
- Windows, OS X, or Linux?: OS X
- Network issues:
  - Geographic location where npm was run:
  - [ ] I use a proxy to connect to the npm registry.
  - [ ] I use a proxy to connect to the web.
  - [ ] I use a proxy when downloading Git repos.
  - [ X] I access the npm registry via a VPN
  - [ ] I don't use a proxy, but have limited or unreliable internet access.
- Container:
  - [ ] I develop using Vagrant on Windows.
  - [X ] I develop using Vagrant on OS X or Linux.
  - [ ] I develop / deploy using Docker.
  - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by petermikitsh** [comment]
@jay2012 just tried this out and it seems to be working for me. It may have been a temporary issue with our enterprise npm setup.

**Comment by zkat** [comment]
Closing as probably resolved, and also not really something we can do anything about because it's about npmE itself. In the future, support@npmjs.com is the place to email when you have npmE stuff, since this repo is just for the CLI.
