### ISSUE TITLE
npm cli installation is failing

### ISSUE THREAD

**Issue by rajkumarVairam** [npm/npm#14179]
C:\Users\testuser\AppData\Roaming\npm-cache_git-remotes\git-github-com-webpack-compression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-e286d0b5
2954 error Cloning into bare repository 'C:\Users\testuser\AppData\Roaming\npm-cache_git-remotes\git-github-com-webpack-compression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-e286d0b5'...
2954 error ssh: connect to host github.com port 22: Connection timed out
2954 error fatal: Could not read from remote repository.
2954 error
2954 error Please make sure you have the correct access rights

**Comment by KenanY** [comment]
@rajkumarVairam Looks like an issue with your internet connection. Maybe you are behind a proxy or firewall?

**Comment by rajkumarVairam** [comment]
I tried setting proxy it is working npm install but only I am facing issue with "npm install -g angular-cli"
