### ISSUE TITLE
npm stores cookies - but there is no way to clean them

### ISSUE THREAD

**Issue by Ginden** [npm/npm#14175]
That happened:
- Custom repository server set cookie on invalid request.
- Custom repository server returns 404 for all documents if previously mentioned cookie is found.
- All subsequent requests to this server contain this cookie.
- `npm cache clean --force` didn't help - cookies are stored forever.

Happening on versions: 2.5, 3.10, Node 6.6.

**Comment by othiym23** [comment]
To the best of the CLI team's knowledge, the CLI doesn't set or send cookies to registries at all. If you can reproduce this behavior from scratch, put up a gist of an npm run using `--loglevel=silly` to allow us to see what's happening at the network level.

**Comment by Ginden** [comment]
Bug was caused by forgotten `.npmrc`in catalog with `always-auth=true`.
