### ISSUE TITLE
Unable to install jshint-stylish, gulp-jshint and gulp-jscs as a devDependencies using npm

### ISSUE THREAD

**Issue by bala-krishna-challa** [npm/npm#14171]
I'm opening this issue because:
[npm-debug.txt](https://github.com/npm/npm/files/508409/npm-debug.txt)
npm is doing something I don't understand.

What's going wrong?
Unable to install jshint-stylish, gulp-jshint and gulp-jscs as a devDependencies using npm.

How can the CLI team reproduce the problem?
I am not exactly sure. But i could insuall gulp as devDependency but not gulp-jshint, gulp-jscs and jshint-stylish using npm with below command in windows 7 command prompt...
C:\Bala\node\library>npm install --save-dev gulp-jshint gulp-jscs jshint-stylish

supporting information:
- `npm -v` prints: v2.8.3
- `node -v` prints: v4.4.6
- `npm config get registry` prints: http://registry.npmjs.org/
- Windows, OS X, or Linux?:Windows
- Network issues:
  npm ERR! fetch failed with status code 401. I have attached the npm-debug.log for further information.

Thank you.

**Comment by KenanY** [comment]
@bala-krishna-challa The log seems to indicate that you are behind a proxy that you must authenticate yourself with:

```
75 verbose bad json <p>
75 verbose bad json Authentication is required to access the requested web site (&nbsp;ii01wsa001-d1.ciqhyd.com&nbsp;).
75 verbose bad json A valid user ID and password must be entered when prompted.
75 verbose bad json </p>
```
