### ISSUE TITLE
uid must be an unsigned int error

### ISSUE THREAD

**Issue by ybinstock** [npm/npm#14183]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I'm trying to install globally ionic 2 and cordova v5 and I get this error
uid must be an unsigned int

I tried changing the permission files using option 1, but it didn't seem to do anything - https://docs.npmjs.com/getting-started/fixing-npm-permissions#option-1-change-the-permission-to-npms-default-directory

[npm-debug.log.zip](https://github.com/npm/npm/files/509788/npm-debug.log.zip)

#### How can the CLI team reproduce the problem?
sudo npm install -g ionic@2.0.0 cordova@5

### supporting information:

 - `npm -v` prints: 3.10.8
 - `node -v` prints: 6.7.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X, or Linux?: OS X

**Comment by KenanY** [comment]
Sounds like https://github.com/npm/npm/issues/13918.

**Comment by svv2014** [comment]
Looks like it is #13918 .

I did uninstall and install from https://nodejs.org/en/ 
after run  _sudo npm install -g npm@3.10.7_
So this helped me to install ionic finally.

**Comment by ybinstock** [comment]
Did you uninstall npm or node?
