### ISSUE TITLE
npm doesn't install gulp show error  like this uid must be an unsigned int

### ISSUE THREAD

**Issue by EnriqueAldana** [npm/npm#14181]
#### I'm opening this issue because:

I can not install gulp application

  - [ ] npm is crashing.
  - [ x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
when I am trying to install gulp with nam , it shows an error
#### How can the CLI team reproduce the problem?
run console command as : sudo nam install -g gulp

I have included log file at below
[npm-debug.log.zip](https://github.com/npm/npm/files/509679/npm-debug.log.zip)

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 -  OS X platform 
 - Network issues: None
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
Looks like https://github.com/npm/npm/issues/13918.
