### ISSUE TITLE
When I'm trying to updata this "angular2-in-memory-web-api": "^0.0.20" to this "angular2-in-memory-web-api": "~0.1.1" , then npm throws an error's 

### ISSUE THREAD

**Issue by RizwanZaheer** [npm/npm#14184]
#### How i can resolve this issue

-->
[npm-debug.zip](https://github.com/npm/npm/files/509865/npm-debug.zip)

**Comment by KenanY** [comment]
The [update note](https://github.com/angular/in-memory-web-api) in `angular-in-memory-web-api`'s README seems relevant here.

**Comment by RizwanZaheer** [comment]
Thanks Kenany, Tht's helpful for me
