### ISSUE TITLE
Error: failed to fetch from registry: base65536

### ISSUE THREAD

**Issue by Person19** [npm/npm#14182]
I was attempting to install the javascript module "base65536". However, I recieved the following error
    npm http GET https://registry.npmjs.org/base65536
    
    npm ERR! Error: failed to fetch from registry: base65536
    npm ERR!     at C:\Users\"User"\Npm\node_modules\npm\lib\utils\npm-registry-client\get.js:139:12
    npm ERR!     at cb <C:\Users\"User"\Npm\node_modules\npm\lib\utils\npm-registry-client\get.js:139:12>
    npm ERR!     at Request._callback (C:\Users\"User"\Npm\node_modules\npm\lib\utils\npm-registry-client\request.js:137:18)
    npm ERR!     at Request.callback (C:\Users\"User"\Npm\node_modules\npm\node_modules\request\main.js:109:22)
    npm ERR!     at Request.<anonymous> (C:\Users\"User"\Npm\node_modules\npm\node_modules\request\main.js:198:58)
    npm ERR!     at Request.emit (events.js:114:20)
    npm ERR!     at ClientRequest.<anonymous> (C:\Users\"User"\Npm\node_modules\npm\node_modules\request\main.js:356:14)
    npm ERR!     at ClientRequest.g (events.js:184:14)
    npm ERR!     at ClientRequest.emit (events.js:87:17)
    npm ERR!     at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1142:7)
    npm ERR! You may report this log at:
    npm ERR!     <http://github.com/isaacs/npm/issues>
    npm ERR! or email it to:
    npm ERR!     <npm-@googlegroups.com>
    npm ERR!
    npm ERR! System Windows_NT 6.1.7600
    npm ERR! command "node" "C:\\Users\\'User'\\Npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "base65536"
    npm ERR! cwd C:\Users\"User"\Npm
    npm ERR! node -v v0.7.9
    npm ERR! npm -v 1.1.0-1
    npm ERR! message failed to fetch from registry: base65536
    npm ERR!
    npm ERR! Additional logging details can be found in:
    npm ERR!     C:\Users\"User"\Npm\npm-debug.log
    npm not ok

The log file is attached to this post.

If someone has a solution, please let me know.

Thanks,
Anonymous person
[npm-debug.txt](https://github.com/npm/npm/files/509704/npm-debug.txt)

**Comment by KenanY** [comment]
@Person19 Sorry, Node.js v0.7 and `npm@1.1` are years old and have not been supported for a very long time now. Please try updating both to their respective latest stable versions, and let me know if this is still an issue for you.

**Comment by Person19** [comment]
Okay. I don't really understand because I downloaded the latest builds for both yesterday.

**Comment by Person19** [comment]
Nevermind.
