### ISSUE TITLE
NPM ERR! with install

### ISSUE THREAD

**Issue by downright770** [npm/npm#14180]
I'm abit new with this stuff but when trying to install hubot I keep getting errors.

npm ERR! Linux 4.4.0-38-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "hubot" "hubot-scripts" "hubot-diagnostics" "hubot-help" "hubot-heroku-keepalive" "hubot-google-images" "hubot-google-translate" "hubot-pugme" "hubot-maps" "hubot-redis-brain" "hubot-rules" "hubot-shipit" "hubot-mattermost" "--save"
npm ERR! node v4.6.0
npm ERR! npm  v3.10.8
npm ERR! code ENOSELF

npm ERR! Refusing to install hubot as a dependency of itself
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/spike/hubot/npm-debug.log

Any help would be great

**Comment by KenanY** [comment]
@downright770 Make sure the `"name"` property in your `package.json` is not set to `"hubot"`, it has to be more unique than that.

**Comment by shafiq1675** [comment]
same problem in windows...please help

**Comment by KenanY** [comment]
@shafiq1675 Looks like a completely different problem to me :/
