### ISSUE TITLE
unable to install sudo npm install -g angular-cli

### ISSUE THREAD

**Issue by aknak** [npm/npm#14195]
#### I'm opening this issue because:
  - `[x] npm is doing something I don't understand.
  - [ x] log file attached

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - mac os mavericks
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
Closing since this is a blank issue.

**Comment by aknak** [comment]
? Kenan

 

Blank issue what exactly do you mean? 

Roland

**Comment by KenanY** [comment]
@aknak No information was provided as to what issue you are experiencing.

**Comment by KenanY** [comment]
@aknak Please provide your `npm-debug.log` and take the time to fill out the form in your original post.

**Comment by aknak** [comment]
[npm-debug-log.pdf](https://github.com/npm/npm/files/513547/npm-debug-log.pdf)
my log file i thought i attached.

**Comment by aknak** [comment]
not able to unable to install sudo npm install -g angular-cli

**Comment by KenanY** [comment]
@aknak Have you tried prefixing your command with `sudo`?

**Comment by aknak** [comment]
Oh, what is prefixing?

New to the command line

**Comment by KenanY** [comment]
@aknak Actually, could you try running these commands in order?:

```
sudo chown -R $(whoami) "$HOME/.npm"
sudo npm i -g polymer-cli
```

**Comment by aknak** [comment]
Sure!  That first line with “” too?

**Comment by aknak** [comment]
Hi Kenan,

Sorry newby to command line on mac. Thank you, Roland

 

Type these lines exactly:

 

sudo chown -R $(whoami) "$HOME/.npm"
sudo npm i -g polymer-cli

 

or

sudo chown -R $ roland "$HOME/.npm"
sudo npm i -g polymer-cli
 
 
sudo chown -R $(myusername(roland)) "$HOME/.npm"

**Comment by KenanY** [comment]
@aknak Just type what I wrote :) no need to fill in your username or anything.

**Comment by aknak** [comment]
Hi Kenan,did as you asked : ) 


see pdf log


  uid must be an unsigned int
 npm ERR! 
 npm ERR! If you need help, you may report this error at:
 npm ERR!     &lt;https://github.com/npm/npm/issues&gt;
 

 npm ERR! Please include the following file with any support request:
 npm ERR!     /Users/roland/npm-debug.log
 rolands-imac:~ roland$ 

---- On Thu, 06 Oct 2016 11:41:34 -0700 Kenan Yildirim &lt;notifications@github.com&gt; wrote ---- 

@aknak Just type what I wrote :) no need to fill in your username or anything.

**Comment by KenanY** [comment]
@aknak That looks like https://github.com/npm/npm/issues/13918.

**Comment by aknak** [comment]
?13918 

 

Whats a 13918 issue?

 

Btw, thank you very much for your support!

**Comment by aknak** [comment]
Got it, Thank you Kenan!
