### ISSUE TITLE
Failed optional dependency /chokidar/fsevents

### ISSUE THREAD

**Issue by rashid-softordi** [npm/npm#14191]
I am installing "cordova-plugin-geolocation" via npm. After updating it under 

  "cordovaPlugins": [
    "cordova-plugin-geolocation",
    "cordova-plugin-device",
    "cordova-plugin-whitelist",
    "cordova-plugin-console",
    "cordova-plugin-splashscreen",
    "cordova-plugin-statusbar",
    "ionic-plugin-keyboard"
  ]

 in package.json and then run the command npm install then getting the below mentioned warnings. 

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14

In the end "cordova-plugin-geolocation" is unable to intsall. Any possible solution?

---------------------------------------------  npm-debug.log  shown below---------------------------------

0 info it worked if it ends with ok
1 verbose cli [ 'C:\Users\microBrain\Node\node.exe',
1 verbose cli   'C:\Users\microBrain\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'watch' ]
2 info using npm@3.10.6
3 info using node@v6.7.0
4 verbose run-script [ 'prewatch', 'watch', 'postwatch' ]
5 info lifecycle ionic-hello-world@~prewatch: ionic-hello-world@
6 silly lifecycle ionic-hello-world@~prewatch: no script for prewatch, continuing
7 info lifecycle ionic-hello-world@~watch: ionic-hello-world@
8 verbose lifecycle ionic-hello-world@~watch: unsafe-perm in lifecycle true
9 verbose lifecycle ionic-hello-world@~watch: PATH: C:\Users\microBrain\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\microBrain\Documents\Ionic2\d2d-gui-v2\node_modules.bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32;C:\Program Files\Java\jdk1.8.0_102\bin;C:\apache-ant-1.9.6\bin;C:\Users\microBrain\AppData\Roaming\npm;C:\Program Files\Git\bin;C:\Program Files\Git\cmd;C:\Users\microBrain\AppData\Local\Android\android-sdk\tools;C:\Users\microBrain\AppData\Local\Android\android-sdk\platform-tools;C:\Program Files (x86)\Skype\Phone\;C:\Users\microBrain\Node\;C:\Users\microBrain\AppData\Roaming\npm
10 verbose lifecycle ionic-hello-world@~watch: CWD: C:\Users\microBrain\Documents\Ionic2\d2d-gui-v2
11 silly lifecycle ionic-hello-world@~watch: Args: [ '/d /s /c', 'ionic-app-scripts watch' ]
12 silly lifecycle ionic-hello-world@~watch: Returned: code: 3221225786  signal: null
13 info lifecycle ionic-hello-world@~watch: Failed to exec watch script
14 verbose stack Error: ionic-hello-world@ watch: `ionic-app-scripts watch`
14 verbose stack Exit status 3221225786
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\microBrain\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\microBrain\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid ionic-hello-world@
16 verbose cwd C:\Users\microBrain\Documents\Ionic2\d2d-gui-v2
17 error Windows_NT 6.1.7601
18 error argv "C:\Users\microBrain\Node\node.exe" "C:\Users\microBrain\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "run" "watch"
19 error node v6.7.0
20 error npm  v3.10.6
21 error code ELIFECYCLE
22 error ionic-hello-world@ watch: `ionic-app-scripts watch`
22 error Exit status 3221225786
23 error Failed at the ionic-hello-world@ watch script 'ionic-app-scripts watch'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the ionic-hello-world package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     ionic-app-scripts watch
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs ionic-hello-world
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls ionic-hello-world
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@rashid-softordi Warnings should not cause an installation to fail. Is there a `npm-debug.log` file you could upload to <https://gist.github.com>?

**Comment by rbose85** [comment]
Having the same issue using `mhart/alpine-node:6.7.0` ... rolled back to `mhart/alpine-node:6.6.0` and `npm install` ran without errors. `mhart/alpine-node:6.7.0` is running `npm` at version, `3.10.8`. `mhart/alpine-node:6.6.0` is running `npm` at version `3.10.7`.

@rashid-softordi, might this be the case for you?

@KenanY, do you know of any issues in `npm` version `3.10.8` where `optionalDependencies` are not being honoured? (`fsevents` is listed in the `optionalDependencies` of `package.json` for `chokidar `)

**Comment by rbose85** [comment]
I believe it's related to this #14042.

**Comment by rashid-softordi** [comment]
I am installing "cordova-plugin-geolocation" via npm but  "cordova-plugin-geolocation" is unable to intsall. Getting the Warnings 

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14

 Any possible solution?

--------------------------------------------- npm-debug.log shown below---------------------------------
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Users\\microBrain\\Node\\node.exe',
1 verbose cli   'C:\\Users\\microBrain\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'watch' ]
2 info using npm@3.10.6
3 info using node@v6.7.0
4 verbose run-script [ 'prewatch', 'watch', 'postwatch' ]
5 info lifecycle ionic-hello-world@~prewatch: ionic-hello-world@
6 silly lifecycle ionic-hello-world@~prewatch: no script for prewatch, continuing
7 info lifecycle ionic-hello-world@~watch: ionic-hello-world@
8 verbose lifecycle ionic-hello-world@~watch: unsafe-perm in lifecycle true
9 verbose lifecycle ionic-hello-world@~watch: PATH: C:\Users\microBrain\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\microBrain\Documents\Ionic2\d2d-gui-v2\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32;C:\Program Files\Java\jdk1.8.0_102\bin;C:\apache-ant-1.9.6\bin;C:\Users\microBrain\AppData\Roaming\npm;C:\Program Files\Git\bin;C:\Program Files\Git\cmd;C:\Users\microBrain\AppData\Local\Android\android-sdk\tools;C:\Users\microBrain\AppData\Local\Android\android-sdk\platform-tools;C:\Program Files (x86)\Skype\Phone\;C:\Users\microBrain\Node\;C:\Users\microBrain\AppData\Roaming\npm
10 verbose lifecycle ionic-hello-world@~watch: CWD: C:\Users\microBrain\Documents\Ionic2\d2d-gui-v2
11 silly lifecycle ionic-hello-world@~watch: Args: [ '/d /s /c', 'ionic-app-scripts watch' ]
12 silly lifecycle ionic-hello-world@~watch: Returned: code: 3221225786  signal: null
13 info lifecycle ionic-hello-world@~watch: Failed to exec watch script
14 verbose stack Error: ionic-hello-world@ watch: `ionic-app-scripts watch`
14 verbose stack Exit status 3221225786
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\microBrain\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\microBrain\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid ionic-hello-world@
16 verbose cwd C:\Users\microBrain\Documents\Ionic2\d2d-gui-v2
17 error Windows_NT 6.1.7601
18 error argv "C:\\Users\\microBrain\\Node\\node.exe" "C:\\Users\\microBrain\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "watch"
19 error node v6.7.0
20 error npm  v3.10.6
21 error code ELIFECYCLE
22 error ionic-hello-world@ watch: `ionic-app-scripts watch`
22 error Exit status 3221225786
23 error Failed at the ionic-hello-world@ watch script 'ionic-app-scripts watch'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the ionic-hello-world package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     ionic-app-scripts watch
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs ionic-hello-world
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls ionic-hello-world
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@rashid-softordi That error log shows that your `"watch"` script is throwing an error. I don't see anything pertaining to `cordova-plugin-geolocation` there.
