### ISSUE TITLE
Cannot unpblish the archway-cli module

### ISSUE THREAD

**Issue by quang-vn** [npm/npm#14206]
#### I'm opening this issue because:

  - I cannot unpublish the cannot unpublish a version that is >24 hours old

#### What's going wrong?
  - I cannot unpublish the cannot unpublish a version that is >24 hours old
#### How can the CLI team reproduce the problem?

using the npm unpublish archway-cli@1.1.10

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@quang-vn Please email `support@npmjs.com` for unpublishing something from the registry.

**Comment by KenanY** [comment]
Closing since unpublish requests must go through that email address, not here.
