### ISSUE TITLE
angular 2 router v3.0.0-rc.1 does not get latest import updates

### ISSUE THREAD

**Issue by johlize** [npm/npm#14209]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [ ] npm is producing an incorrect install.
- [x] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
#### What's going wrong?

When using npm to install angular/routing 3.0.0-rc.5, our local router.d.ts has the following import statement:
```
import { ComponentResolver, Injector, NgModuleFactoryLoader, Type } from '@angular/core';
```

The file in the latest angular router.ts has the following import statement:

```
import {Compiler, ComponentFactoryResolver, Injector, NgModuleFactoryLoader, ReflectiveInjector, Type} from '@angular/core';
```

This causes problems when we try to run angular 2 v2.0.1. To solve the problem we reverted to angular 2 v2.0.0-rc.5

#### How can the CLI team reproduce the problem?

download the following dependencies 

```
   "@angular/common": "2.0.1",
    "@angular/compiler": "2.0.1",
    "@angular/core": "2.0.1",
    "@angular/forms": "1.0.1",
    "@angular/http": "2.0.1",
    "@angular/platform-browser": "2.0.1",
    "@angular/platform-browser-dynamic": "2.0.1",
    "@angular/router": "3.0.0-rc.1"
```

### supporting information:
- `npm -v` prints:
- `node -v` prints:
- `npm config get registry` prints:
- Windows, OS X/macOS, or Linux?:
- Network issues:
  - Geographic location where npm was run:
  - [ ] I use a proxy to connect to the npm registry.
  - [ ] I use a proxy to connect to the web.
  - [ ] I use a proxy when downloading Git repos.
  - [ ] I access the npm registry via a VPN
  - [ ] I don't use a proxy, but have limited or unreliable internet access.
- Container:
  - [ ] I develop using Vagrant on Windows.
  - [ ] I develop using Vagrant on OS X or Linux.
  - [ ] I develop / deploy using Docker.
  - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
This doesn't seem to be an issue with npm. You should file a bug with `@angular/core`.

**Comment by othiym23** [comment]
This does indeed appear to be a problem with Angular, and not something that the npm CLI team can resolve for you. Closing as such, but good luck getting this figured out!
