### ISSUE TITLE
simplepeer.js is not working on the android.

### ISSUE THREAD

**Issue by techleadzdevteam** [npm/npm#14208]
I am using simplepeer.js with pusher api and I have developed an audio/video calling system but there is a problem that it is not working on the mobile.

 

I have tested my system on Mozilla and chrome on laptop ,it is working fine on both but on the mobile when I call the person ,peer stream starts and then it close suddenly.

 

Can you help me about this issue?

**Comment by KenanY** [comment]
Doesn't sound like an issue with `npm` to me. This tracker is for bugs/feature-requests for `npm` the package manager. not general support.
