### ISSUE TITLE
npm list -g doesn't show module

### ISSUE THREAD

**Issue by gkuehn001** [npm/npm#14214]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [ ] npm is producing an incorrect install.
- [x] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
#### What's going wrong?

npm list does not show all modules that are installed globally:

```
pi@raspberrypi:~ $ npm ls -g --depth=0
/usr/lib
├── homebridge@0.4.6
├── homebridge-knx@0.2.8
├── jsonlint@1.6.2
├── node-gyp@3.4.0
└── npm@3.10.3

pi@raspberrypi:~ $ ls -l /usr/lib/node_modules/
total 24
drwxr-xr-x  5 pi     pi   4096 Oct  8 12:59 hap-nodejs
drwxr-xr-x  6 pi     pi   4096 Oct  8 10:53 homebridge
drwxr-xr-x  3 nobody pi   4096 Oct  7 23:30 homebridge-knx
drwxr-xr-x  8 nobody pi   4096 Oct  7 23:52 jsonlint
drwxr-xr-x  8 pi     pi   4096 Oct  7 23:04 node-gyp
drwxr-xr-x 10 root   root 4096 Oct  7 22:59 npm`
```
#### How can the CLI team reproduce the problem?

hap-nodejs was installed like that:

`sudo npm install -g --unsafe-perm hap-nodejs`

There was a missing  dependency error (from homebridge). This is gone after installation and everthing works.

**But why doesn't `npm ls -g` show the installed hap-nodejs module?**
### supporting information:
- `npm -v` prints: 3.10.3
- `node -v` prints: v6.7.0
- `npm config get registry` prints: https://registry.npmjs.org/
- Windows, OS X/macOS, or Linux?: Linux

**Comment by 7coder7** [comment]
Is the homebridge package having the hap-nodejs dependency within it?

**Comment by legodude17** [comment]
I think it is because `npm` believes that `hap-nodejs` is a dependency of `homebridge`, and not a module that should be show with `npm ls -g --depth=0`.
