### ISSUE TITLE
How to install the different version of a package?

### ISSUE THREAD

**Issue by shikelong** [npm/npm#14213]
Can I  install the different version of a package by install these by git url ?

Regards.

**Comment by KenanY** [comment]
@shikelong If the version you want is in the registry, you can simply specify it like so:

```
npm install express@4.9.8
```

if you want to do it via `git`, you can either specify a commit, branch, or tag, like so:

```
npm install expressjs/express#f15bba7309f2e0a17f7b7a5552b9618f074078c8
npm install expressjs/express#4.9.8
```

**Comment by shikelong** [comment]
sorry. I mean I want to install multiple versions of package using npm --- both version 1.x and version 2.x in a project.

**Comment by KenanY** [comment]
@shikelong Not possible.
