### ISSUE TITLE
Error installing angular-cli using node v4.6.0 npm 3.10.8 on windows 8

### ISSUE THREAD

**Issue by aliabbasvohrashub** [npm/npm#14219]
I have tried node v6 too but to no avail

npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit 
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:213:12)
npm WARN addRemoteGit     at emitTwo (events.js:87:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:172:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:829:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:319:11)
npm WARN addRemoteGit     at emitOne (events.js:77:13)
npm WARN addRemoteGit     at Socket.emit (events.js:169:7)
npm WARN addRemoteGit     at Pipe._onclose (net.js:486:12)
npm WARN addRemoteGit  webpack/compression-webpack-plugin#7e55907cd54a2e91b96d25a660acc6a2a6453f54 resetting remote C:\Users\Ali\AppData\Roaming\npm-cache_git-remotes\git-github-com-webpack-compression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-ec76b2fe because of error: { [Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit ]
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
npm ERR! git clone --template=C:\Users\Ali\AppData\Roaming\npm-cache_git-remotes_templates --mirror git@github.com:webpack/compression-webpack-plugin.git C:\Users\Ali\AppData\Roaming\npm-cache_git-remotes\git-github-com-webpack-compression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-e286d0b5: Cloning into bare repository 'C:\Users\Ali\AppData\Roaming\npm-cache_git-remotes\git-github-com-webpack-compression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-e286d0b5'...
npm ERR! git clone --template=C:\Users\Ali\AppData\Roaming\npm-cache_git-remotes_templates --mirror git@github.com:webpack/compression-webpack-plugin.git C:\Users\Ali\AppData\Roaming\npm-cache_git-remotes\git-github-com-webpack-compression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-e286d0b5: Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.
npm ERR! git clone --template=C:\Users\Ali\AppData\Roaming\npm-cache_git-remotes_templates --mirror git@github.com:webpack/compression-webpack-plugin.git C:\Users\Ali\AppData\Roaming\npm-cache_git-remotes\git-github-com-webpack-compression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-e286d0b5: Permission denied (publickey).
npm ERR! git clone --template=C:\Users\Ali\AppData\Roaming\npm-cache_git-remotes_templates --mirror git@github.com:webpack/compression-webpack-plugin.git C:\Users\Ali\AppData\Roaming\npm-cache_git-remotes\git-github-com-webpack-compression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-e286d0b5: fatal: Could not read from remote repository.
npm ERR! git clone --template=C:\Users\Ali\AppData\Roaming\npm-cache_git-remotes_templates --mirror git@github.com:webpack/compression-webpack-plugin.git C:\Users\Ali\AppData\Roaming\npm-cache_git-remotes\git-github-com-webpack-compression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-e286d0b5: 
npm ERR! git clone --template=C:\Users\Ali\AppData\Roaming\npm-cache_git-remotes_templates --mirror git@github.com:webpack/compression-webpack-plugin.git C:\Users\Ali\AppData\Roaming\npm-cache_git-remotes\git-github-com-webpack-compression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-e286d0b5: Please make sure you have the correct access rights
npm ERR! git clone --template=C:\Users\Ali\AppData\Roaming\npm-cache_git-remotes_templates --mirror git@github.com:webpack/compression-webpack-plugin.git C:\Users\Ali\AppData\Roaming\npm-cache_git-remotes\git-github-com-webpack-compression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-e286d0b5: and the repository exists.
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Users\Ali\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "install" "angular-cli" "-g"
npm ERR! node v4.6.0
npm ERR! npm  v3.10.8
npm ERR! code 128
npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\Ali\AppData\Roaming\npm-cache_git-remotes_templates --mirror git@github.com:webpack/compression-webpack-plugin.git C:\Users\Ali\AppData\Roaming\npm-cache_git-remotes\git-github-com-webpack-compression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-e286d0b5
npm ERR! Cloning into bare repository 'C:\Users\Ali\AppData\Roaming\npm-cache_git-remotes\git-github-com-webpack-compression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-e286d0b5'...
npm ERR! Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues
npm ERR! Please include the following file with any support request:
npm ERR!     F:\Project_TypeScript\A2Vs\NodeA2\NodeA2\npm-debug.log

====npm command completed with exit code 1====

**Comment by push-f** [comment]
i'm getting the same error. Fresh installation of node and npm, also tried to add ssh-keys...

still getting this permission denied error. very strange

**Comment by angrymonkee** [comment]
I am getting the same error. I have tried changing my git config to point to https:// instead of git:// as per another user's recommendation and am still getting this error.

**Comment by gual** [comment]
I was having this same error using Babun, I tried with Windows PowerShell and it worked. It could be a workaround.

**Comment by vamsil** [comment]
I am also gettig the same error. I am running on windows 7 with node version v4
