### ISSUE TITLE
 Add ProjectPath to require module, require('//src/util')===require('ProjectPath/src/util')

### ISSUE THREAD

**Issue by DonaldDu** [npm/npm#14211]
### How about add ProjectPath to require module . 
The project path is  the project package.json folder path. 
Then require('//src/util/url')===require('ProjectPath/src/util/url').
When using in lib project require('//src/util/url')===require('LibProjectPath/src/util/url').
Nobody want this './../../../../../../../../../../../../../../../../../../../../../../../../../../../../path'.

**Comment by othiym23** [comment]
Take a look at [this page](https://nodejs.org/api/modules.html#modules_all_together), which is the documentation for the Node.js module loader. It's a part of Node that hasn't changed for a long time, and is what would need to change for the behavior you describe to be added. npm doesn't define how modules are found or loaded – only Node, or something that extends Node, can do that. As such, I'm going to close this issue. Thanks for your time!
