### ISSUE TITLE
npm install -g into window 10

### ISSUE THREAD

**Issue by gannza** [npm/npm#14217]
npm ERR! addLocal Could not install C:\xampp\htdocs\dev.api
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3

npm ERR! No name provided in package.json
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\xampp\htdocs\dev.api\npm-debug.log

**Comment by a4lab2** [comment]
i am having the same problem too.....

**Comment by KenanY** [comment]
@gannza @a4lab2 `npm install -g`, with no arguments provided, will globally install whatever package is in your current directory. The `package.json` in your current directory, apparently, does not define a `"name"`, which makes this an invalid package, which `npm` will refuse to install.
