### ISSUE TITLE
npm install newman --global on ubuntu14.04 ,show "npm ERR! shasum check failed for /tmp/npm-16334-c283889d/registry.npmjs.org/handlebars/-/handlebars-4.0.5.tgz"

### ISSUE THREAD

**Issue by andyzhouh** [npm/npm#14220]
when i run command:npm install newman --global, show result as below:
npm ERR! Linux 3.13.0-86-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "newman" "--global"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3

npm ERR! shasum check failed for /tmp/npm-16334-c283889d/registry.npmjs.org/handlebars/-/handlebars-4.0.5.tgz
npm ERR! Expected: 92c6ed6bb164110c50d4d8d0fbddc70806c6f8e7
npm ERR! Actual:   f9f65012e00172b09e3e8fa5694e2701fe2abaca
npm ERR! From:     http://registry.npmjs.org/handlebars/-/handlebars-4.0.5.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

Please help me,thanks!

#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@andyzhouh Have you tried running `npm cache clean`?

**Comment by KenanY** [comment]
Closing due to lack of any response.

**Comment by lshmouse** [comment]
@KenanY 
It works in my dev env. Thanks~
