### ISSUE TITLE
npm install webpack -g  err

### ISSUE THREAD

**Issue by 631887934** [npm/npm#14237]
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "D:\nodejs\node.exe" "D:\nodejs\node_modules\npm\bin\npm-cli.js" "install" "webpack" "-g"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9
npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! syscall getaddrinfo

npm ERR! getaddrinfo EAI_AGAIN registry.cnpm.org:80
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     C:\WINDOWS\system32\npm-debug.log

**Comment by fengmk2** [comment]
> npm ERR! getaddrinfo EAI_AGAIN registry.cnpm.org:80

registry wrong, should be `registry.cnpmjs.org` or the orignal registry `registry.npmjs.org`.
