### ISSUE TITLE
Feature Request: Get a report with all dependencies versions and licenses (for a legal purpose)

### ISSUE THREAD

**Issue by F2X** [npm/npm#14236]
Hi,
I have to check with the legal department to check if there is not contaminating licenses in dependencies, e.g. a dependency with a GPL license which make automatically my project under the same GPL obligations.
So I'm looking for a tool/plugin to do it automatically, but I think it will be usefull if it can be done natively from the npm cli.

**Comment by franciscop** [comment]
Hi @F2X I just released the latest version of [`legally`](https://github.com/franciscop/legally) which I think does what you want:

```bash
npm install legally -g && legally -packages
```

![packages](https://cloud.githubusercontent.com/assets/2801252/19342434/dae783e2-916c-11e6-93f2-0813f233cf61.png)

Or you could go with just checking the types:

```bash
legally -licenses
```

![licenses](https://cloud.githubusercontent.com/assets/2801252/19342505/1c73f246-916d-11e6-90c1-99dcc6e647f3.png)

I found this issue as I wanted to propose to include part of it into npm library so I checked if there was any previous discussion. I agree that it'd be really cool if you could do:

```bash
npm licenses express body-parser   # This doesn't work now
```

PS, any feedback is welcome :smile:
