### ISSUE TITLE
npm install

### ISSUE THREAD

**Issue by xe07039** [npm/npm#14238]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [X] npm is producing an incorrect install.
- [ ] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
#### What's going wrong?

The command 

> npm install 
> give this errors:
#### How can the CLI team reproduce the problem?

> npm install 
> 
### supporting information:
- `npm -v` prints:
- `node -v` prints:
- `npm config get registry` prints:
- Windows, OS X/macOS, or Linux?: Windows 7 32 bits
- Network issues:
  - Geographic location where npm was run:
  - [ X] I use a proxy to connect to the npm registry.
  - [ X] I use a proxy to connect to the web.
  - [X ] I use a proxy when downloading Git repos.
  - [ ] I access the npm registry via a VPN
  - [ ] I don't use a proxy, but have limited or unreliable internet access.
- Container:
  - [ ] I develop using Vagrant on Windows.
  - [ ] I develop using Vagrant on OS X or Linux.
  - [ ] I develop / deploy using Docker.
  - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by apalacios-modpow** [comment]
npm install does not work:

Error: Cannot find module 'internal/fs'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
....

In order to use it I have to:
sudo n 6.8.0

And then return to
sudo n 7.1.0

**Comment by legodude17** [comment]
Are you on the latest `npm`?

**Comment by apalacios-modpow** [comment]
sudo n 6.8.0
npm info npm version
(node:24015) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:24015) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:24015) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:24015) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
3.10.9


sudo n 7.1.0
npm info npm version
module.js:474
    throw err;
    ^

Error: Cannot find module 'internal/fs'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at evalmachine.<anonymous>:17:20
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)

**Comment by legodude17** [comment]
What command are you running?

**Comment by apalacios-modpow** [comment]
npm info npm version
