### ISSUE TITLE
All NPM commands cannot find module core-util-is

### ISSUE THREAD

**Issue by jordanmaslyn** [npm/npm#14247]
#### I'm opening this issue because:
- [x] npm is crashing.
- [ ] npm is producing an incorrect install.
- [ ] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
#### What's going wrong?

Any NPM command produces:

```
module.js:457
    throw err;
    ^

Error: Cannot find module 'core-util-is'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_readable.js:41:12)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
```
#### How can the CLI team reproduce the problem?

No log file is being generated (that I can see)
### supporting information:
- `npm -v` prints: Same error as above
- `node -v` prints: v6.7.0
- `npm config get registry` prints: Same error as above
- Windows, OS X/macOS, or Linux?: macOS Sierra
- Network issues:
  - Geographic location where npm was run: Richmond, VA, USA
  - [ ] I use a proxy to connect to the npm registry.
  - [ ] I use a proxy to connect to the web.
  - [ ] I use a proxy when downloading Git repos.
  - [ ] I access the npm registry via a VPN
  - [ ] I don't use a proxy, but have limited or unreliable internet access.
- Container:
  - [ ] I develop using Vagrant on Windows.
  - [x] I develop using Vagrant on OS X or Linux. (npm is run in host)
  - [x] I develop / deploy using Docker. (npm is run in host)
  - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by rikirenz** [comment]
Same issue

**Comment by rukshan-rodrigo** [comment]
Same here.

**Comment by legodude17** [comment]
Please try updating `npm` to 4.0.2 (or 3.10.10 if you want to stay with npm@3) with `npm install npm@next`. If that doesn't work, try installing latest version from the [homepage.](https://github.com/npm/npm#readme).

**Comment by Charlotteis** [comment]
Small note but 4.0.2 is on `npm install -g npm@latest` now :)

**Comment by zkat** [comment]
Your npm installation is hosed for some reason (likely an installation error or other filesystem-related issue). `npm install -g npm@latest` is unlikely to work. Remove npm entirely and install the latest version directly as https://github.com/npm/npm/issues/14247#issuecomment-263419020 said.

**Comment by KenanY** [comment]
Closing as resolved/abandoned.
