### ISSUE TITLE
npm install/outdated not respecting semver

### ISSUE THREAD

**Issue by alejandroiglesias** [npm/npm#14241]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Running `npm outdated` is not respecting semver since it suggests latest version for package `angular` is `1.2.31` (published today) while latest semver is actually `1.5.8` (published on July 22). This doesn't seem to affect `install` or `update` commands on my project if I specify `^1.5.8` or `latest` as the required version in `package.json` but it does install version `1.2.31` on a fresh project (`npm install --save angular`). On such fresh project, after installing such version, running `npm update` will update to `1.5.8`.

So to recap:

* `npm outdated` shows latest published version, not latest semver version.
* `npm install` respects semver for already installed packages, but installs latest published version on fresh installs.

#### How can the CLI team reproduce the problem?

1. `mkdir <directory> && cd <directory>`
2. `npm init`
3. `npm install --save angular` (installs `1.2.31` today)
4. `npm outdated` (shows `1.2.31` installed, `1.5.8` wanted and `1.2.31` latest)
5. `npm update` (installs `1.5.8`)

### supporting information:

 - `npm -v` prints: 3.10.8
 - `node -v` prints: v6.7.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: OS X El Capitan 10.11.6
 - Network issues:
   - Geographic location where npm was run: Buenos Aires, Argentina
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
> `npm outdated` shows latest published version, not latest semver version.

This matches the [documentation](https://docs.npmjs.com/cli/outdated):

> `latest` is the version of the package tagged as latest in the registry. Running `npm publish` with no special configuration will publish the package with a dist-tag of `latest`. This may or may not be the maximum version of the package, or the most-recently published version of the package, depending on how the package's developer manages the latest [dist-tag](https://docs.npmjs.com/cli/dist-tag).

---

>  installs latest published version on fresh installs

Also matches the [documentation](https://docs.npmjs.com/cli/install):

> Do a `<name>@<tag>` install, where `<tag>` is the "tag" config. (See [npm-config](https://docs.npmjs.com/misc/config). The config's default value is `latest`.)

Sorry if I misunderstood you on anything.

**Comment by alejandroiglesias** [comment]
@KenanY thanks for your reply. According to that, everything seems to be working according to the docs, just a bit confusing if you think about semver.
Cheers.
