### ISSUE TITLE
npm ffluent-install error

### ISSUE THREAD

**Issue by jvlook** [npm/npm#14240]
#### I'm opening this issue because:

[c44f904c8931857a5490ef9f541e613a-3aea256bfb9f03406b1f5b67b7f46ffe482be521.zip](https://github.com/npm/npm/files/521950/c44f904c8931857a5490ef9f541e613a-3aea256bfb9f03406b1f5b67b7f46ffe482be521.zip)

  - [ ] npm is crashing.
  - [X] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

When installing npm fluent-ffmpeg my terminal throws errors claiming Maximum call stack size exceeded, and checking fluent-ffmpeg version shows no recognised command.

#### How can the CLI team reproduce the problem?

Gist file of debug log:
https://gist.github.com/jvlook/c44f904c8931857a5490ef9f541e613a

### supporting information:

 - `npm -v` prints: 3.10.3
 - `node -v` prints: -bash: node-v: command not found
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: MacOS Sierra Version 10.12
 - Network issues:
   - Geographic location where npm was run: Netherlands

**Comment by KenanY** [comment]
@jvlook Does this also occur with the latest stable version of `npm`?

**Comment by jvlook** [comment]
Not sure, not very experienced. What's the terminal command to install that version?

**Comment by KenanY** [comment]
@jvlook Try: `npm install -g npm@3.10.9`

**Comment by jvlook** [comment]
I think the install went ok, but after running the command again it gave me the same error. I uploaded the debug log as a gist here: https://gist.github.com/jvlook/fd818aa5ce28d2f4f1b7486de97a3ade

This is a complete guess, but I think there might be something wrong with my Json package. The error was stuck on that line for a very long time.

**Comment by jvlook** [comment]
The command you provided didn't work for me. So I uninstalled npm, node, and ffmpeg, and reinstalled it. I don't know how, but that fixed it. Thanks for your help!
