### ISSUE TITLE
Error install grunt-uncss

### ISSUE THREAD

**Issue by kholmatov** [npm/npm#14242]
**Hi,**
**When I try installing grunt-uncss i have get some error:**
===========================================================
0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'grunt-uncss',
1 verbose cli   '--save-dev' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose config Skipping project config: /Users/kholmatov/.npmrc. (matches userconfig)
5 silly cache add args [ 'grunt-uncss', null ]
6 verbose cache add spec grunt-uncss
7 silly cache add parsed spec { raw: 'grunt-uncss',
7 silly cache add   scope: null,
7 silly cache add   name: 'grunt-uncss',
7 silly cache add   rawSpec: '',
7 silly cache add   spec: '*',
7 silly cache add   type: 'range' }
8 verbose addNamed grunt-uncss@*
9 silly addNamed semver.valid null
10 silly addNamed semver.validRange *
11 silly addNameRange { name: 'grunt-uncss', range: '*', hasData: false }
12 silly mapToRegistry name grunt-uncss
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/grunt-uncss
16 verbose addNameRange registry:https://registry.npmjs.org/grunt-uncss not in flight; fetching
17 verbose request uri https://registry.npmjs.org/grunt-uncss
18 verbose request no auth needed
19 info attempt registry request try #1 at 8:03:29 PM
20 verbose request id aef0bfdef0bb53a4
21 verbose etag "7KHKN09TT908UAE61TF6NQOZP"
22 http request GET https://registry.npmjs.org/grunt-uncss
23 http 304 https://registry.npmjs.org/grunt-uncss
24 silly get cb [ 304,
24 silly get   { date: 'Tue, 11 Oct 2016 15:03:30 GMT',
24 silly get     via: '1.1 varnish',
24 silly get     'cache-control': 'max-age=300',
24 silly get     etag: '"7KHKN09TT908UAE61TF6NQOZP"',
24 silly get     age: '45',
24 silly get     connection: 'keep-alive',
24 silly get     'x-served-by': 'cache-fra1241-FRA',
24 silly get     'x-cache': 'HIT',
24 silly get     'x-cache-hits': '1',
24 silly get     'x-timer': 'S1476198210.712455,VS0,VE0',
24 silly get     vary: 'Accept-Encoding' } ]
25 verbose etag https://registry.npmjs.org/grunt-uncss from cache
26 verbose get saving grunt-uncss to /Users/kholmatov/.npm/registry.npmjs.org/grunt-uncss/.cache.json
27 silly addNameRange number 2 { name: 'grunt-uncss', range: '*', hasData: true }
28 silly addNameRange versions [ 'grunt-uncss',
28 silly addNameRange   [ '0.1.0',
28 silly addNameRange     '0.1.1',
28 silly addNameRange     '0.1.2',
28 silly addNameRange     '0.1.3',
28 silly addNameRange     '0.1.5',
28 silly addNameRange     '0.1.6',
28 silly addNameRange     '0.1.7',
28 silly addNameRange     '0.1.8',
28 silly addNameRange     '0.1.9',
28 silly addNameRange     '0.2.0',
28 silly addNameRange     '0.2.1',
28 silly addNameRange     '0.2.2',
28 silly addNameRange     '0.3.0',
28 silly addNameRange     '0.3.1',
28 silly addNameRange     '0.3.2',
28 silly addNameRange     '0.3.3',
28 silly addNameRange     '0.3.4',
28 silly addNameRange     '0.3.5',
28 silly addNameRange     '0.3.6',
28 silly addNameRange     '0.3.7',
28 silly addNameRange     '0.3.8',
28 silly addNameRange     '0.4.0',
28 silly addNameRange     '0.4.1',
28 silly addNameRange     '0.4.2',
28 silly addNameRange     '0.4.3',
28 silly addNameRange     '0.4.4',
28 silly addNameRange     '0.5.0',
28 silly addNameRange     '0.5.1',
28 silly addNameRange     '0.5.2',
28 silly addNameRange     '0.6.0',
28 silly addNameRange     '0.6.1' ] ]
29 verbose addNamed grunt-uncss@0.6.1
30 silly addNamed semver.valid 0.6.1
31 silly addNamed semver.validRange 0.6.1
32 silly cache afterAdd grunt-uncss@0.6.1
33 verbose afterAdd /Users/kholmatov/.npm/grunt-uncss/0.6.1/package/package.json not in flight; writing
34 verbose afterAdd /Users/kholmatov/.npm/grunt-uncss/0.6.1/package/package.json written
35 silly install resolved [ { name: 'grunt-uncss',
35 silly install resolved     description: 'A grunt task for generating CSS files containing only those styles used in your project.',
35 silly install resolved     version: '0.6.1',
35 silly install resolved     homepage: 'https://github.com/addyosmani/grunt-uncss',
35 silly install resolved     author:
35 silly install resolved      { name: 'Addy Osmani',
35 silly install resolved        email: 'addyosmani@gmail.com',
35 silly install resolved        url: 'https://addyosmani.com' },
35 silly install resolved     maintainers: [ [Object], [Object] ],
35 silly install resolved     repository:
35 silly install resolved      { type: 'git',
35 silly install resolved        url: 'git+https://github.com/addyosmani/grunt-uncss.git' },
35 silly install resolved     bugs: { url: 'https://github.com/addyosmani/grunt-uncss/issues' },
35 silly install resolved     license: 'MIT',
35 silly install resolved     keywords: [ 'gruntplugin', 'uncss', 'css' ],
35 silly install resolved     files: [ 'tasks', 'CHANGELOG.md', 'LICENSE-MIT' ],
35 silly install resolved     engines: { node: '>=0.12.0' },
35 silly install resolved     scripts: { test: 'grunt test' },
35 silly install resolved     dependencies:
35 silly install resolved      { async: '^2.0.1',
35 silly install resolved        chalk: '^1.1.0',
35 silly install resolved        maxmin: '^2.1.0',
35 silly install resolved        uncss: '^0.14.0' },
35 silly install resolved     devDependencies:
35 silly install resolved      { chai: '^3.5.0',
35 silly install resolved        grunt: '^1.0.1',
35 silly install resolved        'grunt-contrib-clean': '^1.0.0',
35 silly install resolved        'grunt-contrib-connect': '^1.0.0',
35 silly install resolved        'grunt-contrib-copy': '^1.0.0',
35 silly install resolved        'grunt-contrib-cssmin': '^1.0.0',
35 silly install resolved        'grunt-contrib-jshint': '^1.0.0',
35 silly install resolved        'grunt-contrib-watch': '^1.0.0',
35 silly install resolved        'grunt-processhtml': '^0.4.0',
35 silly install resolved        'grunt-simple-mocha': '^0.4.0',
35 silly install resolved        'load-grunt-tasks': '^3.4.0',
35 silly install resolved        mocha: '^3.0.0',
35 silly install resolved        'time-grunt': '^1.3.0' },
35 silly install resolved     peerDependencies: { grunt: '>=0.4.0' },
35 silly install resolved     gitHead: '02d1cf5228080df0a370a29de8d3f63561fc1fcc',
35 silly install resolved     _id: 'grunt-uncss@0.6.1',
35 silly install resolved     _shasum: 'd93f1b4fc3f59dd69cec60316019963b0d4841ed',
35 silly install resolved     _from: 'grunt-uncss@*',
35 silly install resolved     _npmVersion: '2.15.8',
35 silly install resolved     _nodeVersion: '4.4.7',
35 silly install resolved     _npmUser: { name: 'xhmikosr', email: 'xhmikosr@gmail.com' },
35 silly install resolved     dist:
35 silly install resolved      { shasum: 'd93f1b4fc3f59dd69cec60316019963b0d4841ed',
35 silly install resolved        tarball: 'https://registry.npmjs.org/grunt-uncss/-/grunt-uncss-0.6.1.tgz' },
35 silly install resolved     _npmOperationalInternal:
35 silly install resolved      { host: 'packages-12-west.internal.npmjs.com',
35 silly install resolved        tmp: 'tmp/grunt-uncss-0.6.1.tgz_1470037846198_0.5535620716400445' },
35 silly install resolved     directories: {},
35 silly install resolved     _resolved: 'https://registry.npmjs.org/grunt-uncss/-/grunt-uncss-0.6.1.tgz',
35 silly install resolved     readme: 'ERROR: No README data found!' } ]
36 info install grunt-uncss@0.6.1 into /Users/kholmatov
37 info installOne grunt-uncss@0.6.1
38 verbose installOne of grunt-uncss to /Users/kholmatov not in flight; installing
39 warn locking Error: EACCES, open '/Users/kholmatov/.npm/_locks/grunt-uncss-48ec7d70277c8742.lock'
39 warn locking     at Error (native)
39 warn locking  /Users/kholmatov/.npm/_locks/grunt-uncss-48ec7d70277c8742.lock failed { [Error: EACCES, open '/Users/kholmatov/.npm/_locks/grunt-uncss-48ec7d70277c8742.lock']
39 warn locking   errno: -13,
39 warn locking   code: 'EACCES',
39 warn locking   path: '/Users/kholmatov/.npm/_locks/grunt-uncss-48ec7d70277c8742.lock' }
40 verbose stack Error: Attempt to unlock /Users/kholmatov/node_modules/grunt-uncss, which hasn't been locked
40 verbose stack     at unlock (/usr/local/lib/node_modules/npm/lib/utils/locker.js:66:11)
40 verbose stack     at cb (/usr/local/lib/node_modules/npm/lib/install.js:1004:5)
40 verbose stack     at /usr/local/lib/node_modules/npm/lib/install.js:1008:20
40 verbose stack     at /usr/local/lib/node_modules/npm/lib/utils/locker.js:40:9
40 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:149:38)
40 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:177:38
40 verbose stack     at FSReqWrap.oncomplete (fs.js:95:15)
41 verbose cwd /Users/kholmatov
42 error Darwin 16.0.0
43 error argv "node" "/usr/local/bin/npm" "install" "grunt-uncss" "--save-dev"
44 error node v0.12.2
45 error npm  v2.7.4
46 error Attempt to unlock /Users/kholmatov/node_modules/grunt-uncss, which hasn't been locked
47 error If you need help, you may report this error at:
47 error     <https://github.com/npm/npm/issues>
48 verbose exit [ 1, true ]
=======================================
**please help fix this trouble**
**Thanks!**

**Comment by KenanY** [comment]
@kholmatov You cache directory permissions seem wrong. Could you try running?:

```
sudo chown -R $(whoami) "$HOME/.npm"
```

**Comment by kholmatov** [comment]
@KenanY Thanks!
for me help reinstall `nmp`
