### ISSUE TITLE
npm is not returning anything (Even npm -v doesn't work.. )

### ISSUE THREAD

**Issue by Sai-Teja** [npm/npm#14259]
#### I'm opening this issue because:

npm is not returning anything even for npm -v

#### How can the CLI team reproduce the problem?

I first installed node.js with npm. Then updated npm. Then I changed the config prefix.. But, I found npm source code still at C:\Users\<user_name>\AppData\Roaming\npm\node_modules\npm\ So, I deleted that npm folder and uninstalled node.js and did a fresh install of node.js (The purpose being having npm on another partition totally which became the mistake of the decade :disappointed: )

Then reinstalled node with npm, without npm, clearing registry etc etc etc Nothing worked.

Even "npm -v" is not working.

While node is fine..

Plz help me as soon as possible..

### supporting information:

 - `npm -v` prints:
Nothing
 - `node -v` prints:
v4.6.0
 - `npm config get registry` prints:
Nothing (Endless Loop)
 - Windows, OS X/macOS, or Linux?:
Windows

**Comment by S-ed** [comment]
Make sure npm You are running pointing at actual npm.
Infinite loop may be caused if node called with empty .js file (npm is just a .cmd).
Read the "Upgrading on Windows" part of:
https://github.com/npm/npm/wiki/Troubleshooting
Resolving the PATH may be a solution.

**Comment by Sai-Teja** [comment]
Found It. There was a file named '.npmrc' created in C:\Users\%UserName% which I found by exploring the source code of npm and it started working after I deleted that File. It was created with prefix with out ending quote (\') due to some bug and it fixed my issue.

**Comment by csyunyou** [comment]
@Sai-Teja  This works for me and really give me a big hand!

**Comment by Teja-Konjeti** [comment]
@csyunyou Haha glad it was of help! :)
