### ISSUE TITLE
Not able to install ng2-uploader 

### ISSUE THREAD

**Issue by keyursoni** [npm/npm#14256]
No able to install ng2-uploader.
i have tried following command on Angular2 terminal

npm install ng2-uploader --save

**Comment by KenanY** [comment]
@keyursoni Not enough information provided. Is there a `npm-debug.log` file generated in your current directory, which you can upload to [gist](https://gist.github.com/) and link here?

**Comment by keyursoni** [comment]
Thank for reply i have used ng2-file-upload for upload the file.
