### ISSUE TITLE
I'm opening this issue because npm is producing an incorrect install

### ISSUE THREAD

**Issue by Leshgan** [npm/npm#14254]
npm reporting error in laravel vagrant:

2797 warn optional Skipping failed optional dependency /chokidar/fsevents:
2798 warn notsup Not compatible with your operating system or architecture: fsevents@1.0.14
2799 verbose stack Error: EPROTO: protocol error, symlink '../semver/bin/semver' -> '/home/vagrant/Code/Laravel/node_modules/accord/node_modules/.bin/semver'
2799 verbose stack     at Error (native)
2800 verbose cwd /home/vagrant/Code/Laravel
2801 error Linux 4.4.0-22-generic
2802 error argv "/usr/bin/nodejs" "/usr/bin/npm" "update"
2803 error node v5.12.0
2804 error npm  v3.8.6
2805 error path ../semver/bin/semver
2806 error code EPROTO
2807 error errno -71
2808 error syscall symlink
2809 error EPROTO: protocol error, symlink '../semver/bin/semver' -> '/home/vagrant/Code/Laravel/node_modules/accord/node_modules/.bin/semver'
2810 error If you need help, you may report this error at:
2810 error     https://github.com/npm/npm/issues
2811 verbose exit [ -71, true ]

**Comment by KenanY** [comment]
@Leshgan Does this also occur if you use the `--no-bin-links` flag?

**Comment by Leshgan** [comment]
@KenanY 

vagrant@homestead:~/Code/Laravel$ sudo npm install --no-bin-link
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm ERR! Linux 4.4.0-22-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--no-bin-link"
npm ERR! node v5.12.0
npm ERR! npm  v3.10.8

npm ERR! Maximum call stack size exceeded
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/Code/Laravel/npm-debug.log
