### ISSUE TITLE
why http://blog.npmjs.org redirect to https://newsroom.fb.com/

### ISSUE THREAD

**Issue by alsotang** [npm/npm#14252]
just click http://blog.npmjs.org

**Comment by martinheidegger** [comment]
Doesn't do so here?!

**Comment by alsotang** [comment]
what?

**Comment by martinheidegger** [comment]
There is no redirect to `newsroom.fb.com` when I try to access the website from here (Osaka, Japan). It might be good to get the `curl -vvvv` response?!

**Comment by alsotang** [comment]
perhaps it's my local network problem... sorry I am inspecting it

**Comment by alsotang** [comment]
I am in (Shenzhen, China)
