### ISSUE TITLE
npm install is adding dev dependencies to the shrinkwrap when it shouldn't 

### ISSUE THREAD

**Issue by albertstill** [npm/npm#14250]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [x] npm is producing an incorrect install.
- [ ] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
#### What's going wrong?

The [code](https://github.com/npm/npm/blob/v3.10.9/lib/install/save.js#L56) that checks if npm should shrinkwrap dev dependencies on an install can have false positives. It simply checks if a `devDependency` from the package.json is present in the root of the npm-shrinkwrap.json dependencies.

I came across this bug when a `devDependency` from the package.json was also a dependency of a prod dependency. So when I went to do a install after a shrinkwrap (with no `--dev` flag), suddenly all my dev dependencies appeared in the shrinkwrap.

I have played with the npm code a little a thought about potential solutions:
##### Solution 1

Now that the shrinkwrap meta contains `dev: true` for each dep since 3.10.8. The code could also check for this boolean. However I believe this won't be backwards compatible. But maybe this is something we could fix and bring in to npm@4?

So the code would be:

```
var shrinkwrapHasAnyDevOnlyDeps = tree.requires.some(function (dep) {
      var name = moduleName(dep)
      return isDevDep(tree, name) &&
             shrinkwrap.dependencies[name] !== null &&
             shrinkwrap.dependencies[name].dev === true
    })
```
##### Solution 2

Another solution would be to have top level meta in the shrinkwrap that would indicate if the shrinkwrap should contain dev dependencies or not. This is maybe a better solution and less flimsy than an arbitrary check which has to loop through all the dependencies.

```
{
  "name": "@domain-group/fe-ops-agency-server",
  "version": "0.0.16",
  "includesDevDependencies": true,
  "dependencies": {
       ....
```

Keen to do this PR if we can decide on the best solution.
#### How can the CLI team reproduce the problem?

I was using private npm modules so can't show you exactly. But create a package.json where a prod dep has a dep which you include in your package.json dev dependencies. Then after `npm i` do a `npm shrinkwrap`. Then install any additional module (`npm i foo --save`) and the dev dependencies will suddenly appear in the `npm-shrinkwrap.json`.

**Comment by iarna** [comment]
Yeah, this is a bug as you say. As of npm@4 we now include dev dependencies your shrinkwrap by default (but you can get the old behavior with `--only=prod`). But as you note, this bug will cause it to include dev dependencies ANYWAY if any are shared with your dependencies or transitive dependencies.

The solution as of npm@4 is super easy. We should just delete `shrinkwrapHasAnyDevOnlyDeps` entirely, as the rule is now "include dev deps unless told otherwise" with no magic. (Yay for no magic! 🚫✨)

**Comment by Itrulia** [comment]
Is there a way to enforce the default behaviour to exclude dev dependencies?

**Comment by legodude17** [comment]
@ltrulia just run `npm shrinkwrap --only=prod` as @iarna said.

**Comment by Itrulia** [comment]
Thats not what I was asking. I want to know if its possible to have it as default via config.

**Comment by legodude17** [comment]
You might be able to put `only: prod` in your `.npmrc`...

**Comment by Itrulia** [comment]
But this would also affect `npm install`, right?

**Comment by legodude17** [comment]
It would...
AFAIK there is no way to enforce default options for only one command. Am I right @iarna?

**Comment by jvivs** [comment]
Any guidance on a version of `npm@3` that doesn't exhibit this bug? Trying to follow the best practices of updating modules with an existing shrinkwrap (ie: `npm install --save` rather than overwriting shrinkwrap every time) and we're running into shrinkwrap consistency issues at my company.

**Comment by legodude17** [comment]
This bug shouldn't effect `npm@3`...

**Comment by Itrulia** [comment]
I had a faulty version that affected npm@3 (cant remember which version though), thats how I got to this issue. After updating to a newer 3.x version the bug didnt happen anymore.

**Comment by legodude17** [comment]
@Itrulia That's good!

**Comment by jvivs** [comment]
@legodude17 Definitely seeing this w/ npm@3.10.10 across my company. Are we the only ones? 😀

**Comment by legodude17** [comment]
Well, on `npm@4` devDeps are included by default. So maybe you could just let them be in the shrinkwrap. `npm installl <your-module>` will still not install the devDeps of `<your-module>`.

**Comment by Itrulia** [comment]
If you accept the devdeps in your npm shrinkwrap and you have a lot of submodules with the devdebs in npm shrinkwrap you will also have to accept over 30 minutes of npm install. Been there, done that. But we now don't have the dev deps in the npm shrinkwrap but have an additional shrinkwrap with the dev deps (stole that one from @angular)

**Comment by jvivs** [comment]
Yeah, we'd rather not have to shrinkwrap our dev dependencies too.

Ideally, we'd never ask developers to shrinkwrap, run shrinkwrap in CI only
after successful builds, and make a commit back to the repo.

Unfortunately we're stuck with shrinkwrapping on developer machines and
spend a bunch of time reinstalling and shrinkwrapping whenever we have to
reconcile dependency changes in two branches.

I was genuinely excited by the possibility of consistent, stable, and
diffable shrinkwraps that were on deck with the adoption of npm@3.

I'm a bit deflated after spending the time trying to wrap my head around
shrinkwrapping and best practices with npm@2 and npm@3 only to be bitten by
this bug once we actually rolled out the update to npm@3.

After reading the 4.0 release notes, 3.x has been immediately deprecated so
it seems like there are no further bugfixes in sight (
https://github.com/npm/npm/releases/tag/v4.0.0). At this point I either
have to sell yet another npm major update or evaluate yarn. Given yarn's
immaturity and the bumpy upgrade path to npm@3, neither are terribly
attractive options.

Honestly a bit bummed with the rapid deprecation of npm@3 as that's the
version of npm shipped with all current Node LTS versions and the
shrinkwrapping workflow is absolutely broken with this bug outstanding. At
this point, shrinkwrapping is the top thing our developers gripe about. I
try to remind them that npm team is a small bunch of really smart people
solving a *really* hard problem. I start to feel like the disconnect
between the Node and npm release cycles that is causing the development
community undue friction and pain.

If I were to fix this bug, would there be any possibility of incorporating
it into a 3.x release?

Likewise, if reproducible installs and the related workflow is still a
feature that npm wants to support, it would be a huge boon to the community
if there was better documentation around best practices and suggested
workflows.
