### ISSUE TITLE
npm ERR! Darwin 16.0.0

### ISSUE THREAD

**Issue by LessDev** [npm/npm#14268]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/6.7.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   '--save-exact',
1 verbose cli   'react-native' ]
2 info using npm@3.10.7
3 info using node@v6.7.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData react-native
8 silly fetchNamedPackageData react-native
9 silly mapToRegistry name react-native
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'react-native',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'react-native',
12 silly mapToRegistry   name: 'react-native',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/react-native
14 verbose request uri https://registry.npmjs.org/react-native
15 verbose request no auth needed
16 info attempt registry request try #1 at 14:34:56
17 verbose request id 5f6b0c2dc76bf740
18 http request GET https://registry.npmjs.org/react-native
19 http 200 https://registry.npmjs.org/react-native
20 verbose headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
20 verbose headers   etag: '"CA7EHR3WMEM3NH8X54HPX4UK3"',
20 verbose headers   'content-type': 'application/json',
20 verbose headers   'content-encoding': 'gzip',
20 verbose headers   'cache-control': 'max-age=300',
20 verbose headers   'content-length': '49408',
20 verbose headers   'accept-ranges': 'bytes',
20 verbose headers   date: 'Thu, 13 Oct 2016 06:31:42 GMT',
20 verbose headers   via: '1.1 varnish',
20 verbose headers   age: '279',
20 verbose headers   connection: 'keep-alive',
20 verbose headers   'x-served-by': 'cache-lcy1132-LCY',
20 verbose headers   'x-cache': 'HIT',
20 verbose headers   'x-cache-hits': '1',
20 verbose headers   'x-timer': 'S1476340302.418726,VS0,VE0',
20 verbose headers   vary: 'Accept-Encoding' }
21 silly get cb [ 200,
21 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
21 silly get     etag: '"CA7EHR3WMEM3NH8X54HPX4UK3"',
21 silly get     'content-type': 'application/json',
21 silly get     'content-encoding': 'gzip',
21 silly get     'cache-control': 'max-age=300',
21 silly get     'content-length': '49408',
21 silly get     'accept-ranges': 'bytes',
21 silly get     date: 'Thu, 13 Oct 2016 06:31:42 GMT',
21 silly get     via: '1.1 varnish',
21 silly get     age: '279',
21 silly get     connection: 'keep-alive',
21 silly get     'x-served-by': 'cache-lcy1132-LCY',
21 silly get     'x-cache': 'HIT',
21 silly get     'x-cache-hits': '1',
21 silly get     'x-timer': 'S1476340302.418726,VS0,VE0',
21 silly get     vary: 'Accept-Encoding' } ]
22 verbose get saving react-native to /Users/lihao/.npm/registry.npmjs.org/react-native/.cache.json
23 verbose correctMkdir /Users/lihao/.npm correctMkdir not in flight; initializing
24 silly install normalizeTree
25 silly loadCurrentTree Finishing
26 silly loadIdealTree Starting
27 silly install loadIdealTree
28 silly cloneCurrentTree Starting
29 silly install cloneCurrentTreeToIdealTree
30 silly cloneCurrentTree Finishing
31 silly loadShrinkwrap Starting
32 silly install loadShrinkwrap
33 silly loadShrinkwrap Finishing
34 silly loadAllDepsIntoIdealTree Starting
35 silly install loadAllDepsIntoIdealTree
36 silly resolveWithNewModule react-native@0.35.0 checking installable status
37 silly cache add args [ 'react-native', null ]
38 verbose cache add spec react-native
39 silly cache add parsed spec Result {
39 silly cache add   raw: 'react-native',
39 silly cache add   scope: null,
39 silly cache add   escapedName: 'react-native',
39 silly cache add   name: 'react-native',
39 silly cache add   rawSpec: '',
39 silly cache add   spec: 'latest',
39 silly cache add   type: 'tag' }
40 silly addNamed react-native@latest
41 verbose addNamed "latest" is being treated as a dist-tag for react-native
42 info addNameTag [ 'react-native', 'latest' ]
43 silly mapToRegistry name react-native
44 silly mapToRegistry using default registry
45 silly mapToRegistry registry https://registry.npmjs.org/
46 silly mapToRegistry data Result {
46 silly mapToRegistry   raw: 'react-native',
46 silly mapToRegistry   scope: null,
46 silly mapToRegistry   escapedName: 'react-native',
46 silly mapToRegistry   name: 'react-native',
46 silly mapToRegistry   rawSpec: '',
46 silly mapToRegistry   spec: 'latest',
46 silly mapToRegistry   type: 'tag' }
47 silly mapToRegistry uri https://registry.npmjs.org/react-native
48 verbose addNameTag registry:https://registry.npmjs.org/react-native not in flight; fetching
49 verbose get https://registry.npmjs.org/react-native not expired, no request
50 silly addNameTag next cb for react-native with tag latest
51 silly addNamed react-native@0.35.0
52 verbose addNamed "0.35.0" is a plain semver version for react-native
53 silly mapToRegistry name react-native
54 silly mapToRegistry using default registry
55 silly mapToRegistry registry https://registry.npmjs.org/
56 silly mapToRegistry data Result {
56 silly mapToRegistry   raw: 'react-native',
56 silly mapToRegistry   scope: null,
56 silly mapToRegistry   escapedName: 'react-native',
56 silly mapToRegistry   name: 'react-native',
56 silly mapToRegistry   rawSpec: '',
56 silly mapToRegistry   spec: 'latest',
56 silly mapToRegistry   type: 'tag' }
57 silly mapToRegistry uri https://registry.npmjs.org/react-native
58 verbose addRemoteTarball https://registry.npmjs.org/react-native/-/react-native-0.35.0.tgz not in flight; adding
59 verbose addRemoteTarball [ 'https://registry.npmjs.org/react-native/-/react-native-0.35.0.tgz',
59 verbose addRemoteTarball   '59a53e80109a728a7f6c7c9f0f0899c8b14c13b2' ]
60 info retry fetch attempt 1 at 14:35:08
61 info attempt registry request try #1 at 14:35:08
62 http fetch GET https://registry.npmjs.org/react-native/-/react-native-0.35.0.tgz
63 http fetch 200 https://registry.npmjs.org/react-native/-/react-native-0.35.0.tgz
64 info retry will retry, error on last attempt: Error: read ECONNRESET
65 silly fetchAndShaCheck shasum 59a53e80109a728a7f6c7c9f0f0899c8b14c13b2
66 silly rollbackFailedOptional Starting
67 silly rollbackFailedOptional Finishing
68 silly runTopLevelLifecycles Finishing
69 silly install printInstalled
70 verbose stack Error: shasum check failed for /var/folders/w1/66k6t__d0dsgh39qr78xwp0h0000gn/T/npm-6461-9620c4e0/registry.npmjs.org/react-native/-/react-native-0.35.0.tgz
70 verbose stack Expected: 59a53e80109a728a7f6c7c9f0f0899c8b14c13b2
70 verbose stack Actual:   7e0e39fc72e507a59ea9f80dd13e33d8a6dd0eb9
70 verbose stack From:     https://registry.npmjs.org/react-native/-/react-native-0.35.0.tgz
70 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/sha/index.js:25:8
70 verbose stack     at ReadStream.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/sha/index.js:72:7)
70 verbose stack     at emitNone (events.js:91:20)
70 verbose stack     at ReadStream.emit (events.js:185:7)
70 verbose stack     at endReadableNT (_stream_readable.js:974:12)
70 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:74:11)
70 verbose stack     at process._tickCallback (internal/process/next_tick.js:98:9)
71 verbose cwd /Users/lihao/Vagrant/data/reactnative/myProject
72 error Darwin 16.0.0
73 error argv "/usr/local/Cellar/node/6.7.0/bin/node" "/usr/local/bin/npm" "install" "--save" "--save-exact" "react-native"
74 error node v6.7.0
75 error npm  v3.10.7
76 error shasum check failed for /var/folders/w1/66k6t__d0dsgh39qr78xwp0h0000gn/T/npm-6461-9620c4e0/registry.npmjs.org/react-native/-/react-native-0.35.0.tgz
76 error Expected: 59a53e80109a728a7f6c7c9f0f0899c8b14c13b2
76 error Actual:   7e0e39fc72e507a59ea9f80dd13e33d8a6dd0eb9
76 error From:     https://registry.npmjs.org/react-native/-/react-native-0.35.0.tgz
77 error If you need help, you may report this error at:
77 error     <https://github.com/npm/npm/issues>
78 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@LessDev Does this also occur after running `npm cache clean`?

**Comment by arckdash** [comment]
Hi, I'm having the same problem, I tried to run: npm cache clean, and then the command to install angular-cli, but I'm still getting the same error message. :S

**Comment by arckdash** [comment]
well, after a wile I did it works, my "solution" was:
follow this guide to completely uninstall node: https://gist.github.com/TonyMtz/d75101d9bdf764c890ef
and then I download the latest version of node (v6.8.1), previously I was using the v4.6.0

Then I installed the angular-cli without problems! :D

**Comment by KenanY** [comment]
Closing due to no response.

**Comment by mkerr** [comment]
Having the same issue, will post my results

**Comment by LessDev** [comment]
I try to install by source ,but it does not work.
then i try to install it by  Linux Binaries (x86/x64) and use the ln -s to make it work .
and it works.
 notice
1.try to Connect by vpn
2.install by differ way
3.if use the vps or vagrant make sure you machine memery pass 1024M
OR there have some special trouble can not solve it 
By the way! GOOD luck for you ..
