### ISSUE TITLE
npm publish sets 'latest' dist-tag even when passed another tag

### ISSUE THREAD

**Issue by tkissing** [npm/npm#14265]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I am publishing a package to a private registry (artifactory) and even though I explicitly pass `--tag snapshot` to some of the builds, those versions also get tagged as `latest`. I am not sure if this is a problem with the npm cli or with artifactory.

Initial state

    # [14:53:40] $ tkissing@gnissikt: ~/Stash/web/comm-stack
    npm view @getgo/comm-stack dist-tags
 
    { snapshot: '5.1.1-pre.npm-compatible-build.20161012140301.730e0992ce',
      latest: '5.1.1-pre.npm-compatible-build.20161012140301.730e0992ce' }

npm publish running on Jenkins

    + npm publish --tag latest --@getgo:registry=https://artifactory.prodwest.citrixsaassbe.net/artifactory/api/npm/npm-release-local/
    [..................] \ : info using node@v6.7.0
    [..................] / publish:@getgo/comm-stack@5.1.1: sill publish uploading
    + @getgo/comm-stack@5.1.1

Everything looks good after this step

    # [14:53:59] $ tkissing@gnissikt: ~/Stash/web/comm-stack
    npm view @getgo/comm-stack dist-tags
 
    { snapshot: '5.1.1-pre.npm-compatible-build.20161012140301.730e0992ce',
      latest: '5.1.1' }

Publish another version with snapshot tag

    + npm publish --tag snapshot --@getgo:registry=https://artifactory.prodwest.citrixsaassbe.net/artifactory/api/npm/npm-snapshot-local/
    [..................] \ : info using node@v6.7.0
    [..................] / publish:@getgo/comm-stack@5.1.2-pre.npm-compatible-build
    + @getgo/comm-stack@5.1.2-pre.npm-compatible-build.20161012150140.8423090b42

Despite passing snapshot explicitly, this new version is also latest now

    # [15:01:12] $ tkissing@gnissikt: ~/Stash/web/comm-stack
    npm view @getgo/comm-stack dist-tags
 
    { snapshot: '5.1.2-pre.npm-compatible-build.20161012150140.8423090b42',
      latest: '5.1.2-pre.npm-compatible-build.20161012150140.8423090b42' }

### supporting information:
npm publish runs on Debian Jessie inside a Docker container on Jenkins
The npm view printouts are from MacOS El Capitan. Node/npm versions are the same on both:

    + node -v
    v6.7.0
    + npm -v
    3.10.8

**Comment by othiym23** [comment]
I'd check the documentation for Artifactory. If you look at [the code that sets the `dist-tag` on publish](https://github.com/npm/npm-registry-client/blob/master/lib/publish.js#L81-L83), you'll see that the CLI / `npm-registry-client` only sets one dist-tag, which in this case is going to be `snapshot`. I know that this behavior doesn't happen when publishing to the public registry, so I suspect Artifactory may be setting `latest` itself.

**Comment by tkissing** [comment]
Ok, found something in an issue on the JFrog site. Seems currently artifactory does not actually honor/store "latest", but determines it strictly according to SemVer rules.
Explanation of behavior at https://www.jfrog.com/jira/browse/RTFACT-8184
Issue for tracking a fix at https://www.jfrog.com/jira/browse/RTFACT-9754

Thanks for pointing me in the right direction.
