### ISSUE TITLE
npm ERR! missing script: watch

### ISSUE THREAD

**Issue by gord2303** [npm/npm#14261]
#### I'm opening this issue because:

  - [+] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [+] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
npm ERR! missing script: watch
#### How can the CLI team reproduce the problem?
I'm unsure what caused the problem.

I've tried re-installing npm and its packages. I've tried npm install watch and npm install npm-watch (I don't know what that does btw, I'm brand new to npm, but willing to try.)

Here's my npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ '/Users/nehaghalke/.nvm/versions/node/v6.7.0/bin/node',
1 verbose cli   '/Users/nehaghalke/.nvm/versions/node/v6.7.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'watch' ]
2 info using npm@3.10.3
3 info using node@v6.7.0
4 verbose stack Error: missing script: watch
4 verbose stack     at run (/Users/nehaghalke/.nvm/versions/node/v6.7.0/lib/node_modules/npm/lib/run-script.js:151:19)
4 verbose stack     at /Users/nehaghalke/.nvm/versions/node/v6.7.0/lib/node_modules/npm/lib/run-script.js:61:5
4 verbose stack     at /Users/nehaghalke/.nvm/versions/node/v6.7.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js:356:5
4 verbose stack     at checkBinReferences_ (/Users/nehaghalke/.nvm/versions/node/v6.7.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js:320:45)
4 verbose stack     at final (/Users/nehaghalke/.nvm/versions/node/v6.7.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js:354:3)
4 verbose stack     at then (/Users/nehaghalke/.nvm/versions/node/v6.7.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js:124:5)
4 verbose stack     at /Users/nehaghalke/.nvm/versions/node/v6.7.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js:243:12
4 verbose stack     at /Users/nehaghalke/.nvm/versions/node/v6.7.0/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
4 verbose stack     at tryToString (fs.js:455:3)
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
5 verbose cwd /Users/nehaghalke/Documents/Websites/tg.dev/wp-content/themes/tg
6 error Darwin 14.5.0
7 error argv "/Users/nehaghalke/.nvm/versions/node/v6.7.0/bin/node" "/Users/nehaghalke/.nvm/versions/node/v6.7.0/bin/npm" "run" "watch"
8 error node v6.7.0
9 error npm  v3.10.3
10 error missing script: watch
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

I'm not sure how to fix the problem and would love to have your help!

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues: Nope, none of these.
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@gord2303 `npm run watch` will look for a `"watch"` script in your `package.json` and run it. Since you apparently do not have such a script defined, you are getting the "missing script" error. It should look something like this (again, in your `package.json`):

``` json
{
  "scripts": {
    "watch": "commands go here"
  }
}
```

https://docs.npmjs.com/misc/scripts
