### ISSUE TITLE
On failed global EACCESS, NPM totally breaks.

### ISSUE THREAD

**Issue by tigerhawkvok** [npm/npm#14264]
#### I'm opening this issue because:
- [x] npm is crashing.
- [ ] npm is producing an incorrect install.
- [ ] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
#### What's going wrong?

NPM failed one install, and now it's impossible to change the global state. It had a bugged out `EACCESS` error (even under sudo) for a global install, then now trying to run any NPM command gives

```
npm ERR! Linux 3.4.0+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-gf" "npm" "coffee-script" "less" "grunt" "grunt-cli"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.6
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'lodash._baseflatten'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/philip/npm-debug.log
```

[npm-debug.log](https://github.com/npm/npm/files/525631/npm-debug.txt)
#### How can the CLI team reproduce the problem?

See debug log.
### supporting information:

Other attempted commands:

```
sudo npm -g --force install
sudo npm -g uninstall lodash
sudo npm -g update
sudo npm -g rebuild
sudo npm install -g -f npm coffee-script less grunt grunt-cli
```

All failed with the same error above, `npm ERR! Cannot find module 'lodash._baseflatten'`.

**SUGGESTION**: On a fail, the package should be removed/unincluded from NPMs tracking to avoid this from happening. Trying to execute a command for which this dependency will then throw an error (which already happens here), but a much easier error of "missing dependency blah", and it doesn't break everything else.

**Comment by zkat** [comment]
Your npm installation itself got hosed. You'll need to reinstall npm itself. See https://github.com/npm/npm#fancy-install-unix.
