### ISSUE TITLE
npm install -g angular-cli  

### ISSUE THREAD

**Issue by Abhinendra** [npm/npm#14271]
**npm install -g angular-cli**  
Error: command failed: git -c core.longpath=true config -npm Warn assRemoteGit 

npm ERR! git clone --template=C:\Users\XYZ\AppData\Roaming\npm-cache\_git-re
motes\_templates --mirror git@github.com:webpack/compression-webpack-plugin.git
C:\Users\AS65952\AppData\Roaming\npm-cache\_git-remotes\git-github-com-webpack-c
ompression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-e286d0b5:
 Cloning into bare repository 'C:\Users\XYZ\AppData\Roaming\npm-cache\_git-r
emotes\git-github-com-webpack-compression-webpack-plugin-git-7e55907cd54a2e91b96
d25a660acc6a2a6453f54-e286d0b5'...
npm ERR! git clone --template=C:\Users\XYZ\AppData\Roaming\npm-cache\_git-re
motes\_templates --mirror git@github.com:webpack/compression-webpack-plugin.git
C:\Users\XYZ\AppData\Roaming\npm-cache\_git-remotes\git-github-com-webpack-c
ompression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-e286d0b5:
 ssh: Could not resolve hostname github.com: Name or service not known
npm ERR! git clone --template=C:\Users\XYZ\AppData\Roaming\npm-cache\_git-re
motes\_templates --mirror git@github.com:webpack/compression-webpack-plugin.git
C:\Users\XYZ\AppData\Roaming\npm-cache\_git-remotes\git-github-com-webpack-c
ompression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-e286d0b5:
 fatal: Could not read from remote repository.
npm ERR! git clone --template=C:\Users\AS65952\AppData\Roaming\npm-cache\_git-re
motes\_templates --mirror git@github.com:webpack/compression-webpack-plugin.git
C:\Users\AS65952\AppData\Roaming\npm-cache\_git-remotes\git-github-com-webpack-c
ompression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-e286d0b5:

npm ERR! git clone --template=C:\Users\XYZ\AppData\Roaming\npm-cache\_git-re
motes\_templates --mirror git@github.com:webpack/compression-webpack-plugin.git
C:\Users\XYZ\AppData\Roaming\npm-cache\_git-remotes\git-github-com-webpack-c
ompression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-e286d0b5:
 Please make sure you have the correct access rights
npm ERR! git clone --template=C:\Users\XYZ\AppData\Roaming\npm-cache\_git-re
motes\_templates --mirror git@github.com:webpack/compression-webpack-plugin.git
C:\Users\XYZ\AppData\Roaming\npm-cache\_git-remotes\git-github-com-webpack-c
ompression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-e286d0b5:
 and the repository exists.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\node\\node-v6.7.0-win-x86\\node.exe" "C:\\node\\node-v6.7.0-w
in-x86\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "angular-cli"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.8
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\XYZ\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:
webpack/compression-webpack-plugin.git C:\Users\AS65952\AppData\Roaming\npm-cach
e\_git-remotes\git-github-com-webpack-compression-webpack-plugin-git-7e55907cd54
a2e91b96d25a660acc6a2a6453f54-e286d0b5
npm ERR! Cloning into bare repository 'C:\Users\XYZ\AppData\Roaming\npm-cach
e\_git-remotes\git-github-com-webpack-compression-webpack-plugin-git-7e55907cd54
a2e91b96d25a660acc6a2a6453f54-e286d0b5'...
npm ERR! ssh: Could not resolve hostname github.com: Name or service not known
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\XYZ\npm-debug.log
npm ERR! git clone

Unable to look up github.com <port 9418> <no such host is known. >

**####** I'm opening this issue because:

 
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Is there any way to directly install angular-cli from local folder of angular-master downloaded from git ?

### supporting information:

 - `npm -v` prints:  3.10.8
 - `node -v` prints: 6.7.0
 - `npm config get registry` prints:
 - Windows
 - Network issues:
   -
   - [ ] I don't use a proxy, but have limited internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.

**Comment by KenanY** [comment]
@Abhinendra How about?:

```
npm install path/to/local/folder
```

**Comment by Abhinendra** [comment]
I did try doing that but that not helping.
Path to local folder shouldbe upto bin folder, right ??

**Comment by KenanY** [comment]
@Abhinendra Should be the folder that contains the package's `package.json`. This is [documented](https://docs.npmjs.com/cli/install#description):

> A `package` is:
> 
> * a) a folder containing a program described by a `package.json(5)` file

**Comment by KenanY** [comment]
Closing due to lack of any more responses.
