### ISSUE TITLE
generated README renders two images

### ISSUE THREAD

**Issue by cdaringe** [npm/npm#14276]
#### I'm opening this issue because:

  - [x] Other (_see below for feature requests_):

#### What's going wrong?

see: https://www.npmjs.com/package/ripcord

the image is rendered _twice_.

it's probably not a problem w/ the `www` product, hence not sure where to file this!  i can migrate as necessary.

#### How can the CLI team reproduce the problem?

write a README.md with an `<img />` tag as the top line

**Comment by clovislima** [comment]
@cdaringe the package.json in the registry seems to have the description set as
```
  "description": "<img src=\"https://raw.githubusercontent.com/cdaringe/ripcord/master/img/parachute.png\" />",
```
but not the one in github
https://github.com/cdaringe/ripcord/blob/master/package.json#L36

**Comment by cdaringe** [comment]
@clovislima, thanks for checking it out!  actually, if you check the [releases](https://github.com/cdaringe/ripcord/releases) section, you'll see that in fact the description has been missing for quite some time.  what's new is the image!  I'll add a description in, but FWIW, this is still probably a bug!

**Comment by KenanY** [comment]
Website issues go here: <https://github.com/npm/www>

**Comment by KenanY** [comment]
Actually to be a bit clearer, if your `"description"` is blank then yes, `npm` will use the first line of your README. I actually think this might not be documented anywhere but it probably should be :)
