### ISSUE TITLE
Fails to install apiconnect-wsdl@1.3.5

### ISSUE THREAD

**Issue by ssibm** [npm/npm#14275]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [ ] npm is producing an incorrect install.
- [ ] npm is doing something I don't understand.
- [ x] Other (_see below for feature requests_):
#### What's going wrong?

As of 10/13 2p CT unable to install apiconnect, fails when trying to find apiconnect-wsdl@1.3.5.
#### How can the CLI team reproduce the problem?

`npm install -g apiconnect`
### supporting information:
- `npm -v` prints: 3.6.0
- `node -v` prints: v4.5.0
- `npm config get registry` prints: https://registry.npmjs.org/
- Windows, OS X/macOS, or Linux?: macOS
### Command tried, and output with error information included.

`npm install -g apiconnect`
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! Darwin 15.4.0
npm ERR! argv "/Applications/IBM/node/bin/node" "/usr/local/bin/npm" "install" "-g" "apiconnect"
npm ERR! node v4.5.0
npm ERR! npm  v3.6.0

npm ERR! No compatible version found: apiconnect-wsdl@1.3.5
npm ERR! Valid install targets:
npm ERR! 1.3.4, 1.3.3, 1.3.2, 1.2.1, 1.2.0, 1.0.0
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

**Comment by jessyuan24** [comment]
I have same message

**Comment by legodude17** [comment]
Sorry, wrong issue. This is not related to what I have.

**Comment by legodude17** [comment]
On your error, that means that `apiconnect-wsdl@3.1.5` has not been published yet. Bug the package author to change the target of the `latest` label to point at a published version.

**Comment by KenanY** [comment]
@ssibm Still seeing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
