### ISSUE TITLE
couldnot install express

### ISSUE THREAD

**Issue by dharma-kc** [npm/npm#14279]
npm ERR! Linux 4.4.0-42-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "express"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2

npm ERR! Cannot read property 'target' of null
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/dharma/
![screenshot from 2016-10-14 11-33-11](https://cloud.githubusercontent.com/assets/14134622/19375793/0668b64a-9202-11e6-84d0-c3f32418a469.png)
React/npm-debug.log

**Comment by KenanY** [comment]
@dharma-kc Could you see if this is still an issue with the latest version of `npm`?

**Comment by dharma-kc** [comment]
I dont know why but sudo apt-get install npm doesnot install the latest version on ubuntu. So I had to install it using:

 sudo npm install -g npm 

This installs the latest version of nmp and everything works fine now.
May be useful for some other people who experience this issue.
Thank you.
