### ISSUE TITLE
npm ERR! Windows_NT 10.0.10586

### ISSUE THREAD

**Issue by firerise** [npm/npm#14272]
npm run test
Tests is crashing
this error 
` 0 tests completed`

`npm ERR! Windows_NT 10.0.10586
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "test"`

I try to
`npm install —save flux-standard-action` and see this
-> `npm ERR! addLocal Could not install C:\Users\wfhm9\ui\—save
npm ERR! Windows_NT 10.0.10586
`

**Comment by KenanY** [comment]
@firerise Could you please provide a full `npm-debug.log` file as a [gist](https://gist.github.com/)? One should be generated in your current working directory upon error.

**Comment by firerise** [comment]
@KenanY 
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\wfhm9\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'test' ]
2 info using npm@3.10.8
3 info using node@v4.5.0
4 verbose run-script [ 'pretest', 'test', 'posttest' ]
5 info lifecycle redux-universal-boilerplate@0.1.0~pretest: redux-universal-boilerplate@0.1.0
6 silly lifecycle redux-universal-boilerplate@0.1.0~pretest: no script for pretest, continuing
7 info lifecycle redux-universal-boilerplate@0.1.0~test: redux-universal-boilerplate@0.1.0
8 verbose lifecycle redux-universal-boilerplate@0.1.0~test: unsafe-perm in lifecycle true
9 verbose lifecycle redux-universal-boilerplate@0.1.0~test: PATH: C:\Users\wfhm9\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\wfhm9\ui\node_modules\.bin;C:\Users\wfhm9\bin;D:\Program Files\Git\mingw64\bin;D:\Program Files\Git\usr\local\bin;D:\Program Files\Git\usr\bin;D:\Program Files\Git\usr\bin;D:\Program Files\Git\mingw64\bin;D:\Program Files\Git\usr\bin;C:\Users\wfhm9\bin;D:\Program Files\Borland\Delphi7\Bin;D:\Program Files\Borland\Delphi7\Projects\Bpl;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Skype\Phone;C:\WINDOWS\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit;D:\Program Files\nodejs;D:\Program Files\Git\cmd;D:\Program Files\Git\mingw64\bin;D:\Program Files\Git\usr\bin;C:\Users\wfhm9\AppData\Roaming\npm;D:\Program Files\Git\usr\bin\vendor_perl;D:\Program Files\Git\usr\bin\core_perl
10 verbose lifecycle redux-universal-boilerplate@0.1.0~test: CWD: C:\Users\wfhm9\ui
11 silly lifecycle redux-universal-boilerplate@0.1.0~test: Args: [ '/d /s /c',
11 silly lifecycle   'karma start ./tests/karma.config.js --single-run' ]
12 silly lifecycle redux-universal-boilerplate@0.1.0~test: Returned: code: 1  signal: null
13 info lifecycle redux-universal-boilerplate@0.1.0~test: Failed to exec test script
14 verbose stack Error: redux-universal-boilerplate@0.1.0 test: `karma start ./tests/karma.config.js --single-run`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\wfhm9\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\wfhm9\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:829:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid redux-universal-boilerplate@0.1.0
16 verbose cwd C:\Users\wfhm9\ui
17 error Windows_NT 10.0.10586
18 error argv "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\wfhm9\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "test"
19 error node v4.5.0
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error redux-universal-boilerplate@0.1.0 test: `karma start ./tests/karma.config.js --single-run`
22 error Exit status 1
23 error Failed at the redux-universal-boilerplate@0.1.0 test script 'karma start ./tests/karma.config.js --single-run'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the redux-universal-boilerplate package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     karma start ./tests/karma.config.js --single-run
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs redux-universal-boilerplate
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls redux-universal-boilerplate
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@firerise Looks like your `"test"` script is failing. It's unlikely that `npm` is causing this, so I would suggest trying to run your script outside of `npm`, like so:

```
karma start ./tests/karma.config.js --single-run
```

or

```
./node_modules/.bin/karma start ./tests/karma.config.js --single-run
```

which will probably throw some sort of error, which you can then begin to debug.

**Comment by firerise** [comment]
@KenanY thx!
