### ISSUE TITLE
npm is doing something i don't understand

### ISSUE THREAD

**Issue by eliezergu** [npm/npm#14284]
i'm trying to install a few modules and i got an error msg so I tried to update npm and i got the same err message.
[npm-debug.zip.zip](https://github.com/npm/npm/files/529384/npm-debug.zip.zip)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\Program Files (x86)\nodejs\node.exe" "C:\Program Files (x86)\nodejs\node_modules\npm\bin\npm-cli.js" "install" "npm@latest" "-g"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! code UNABLE_TO_VERIFY_LEAF_SIGNATURE

npm ERR! unable to verify the first certificate
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\shulem\Downloads\webrtc-web-master\webrtc-web-master\myWebRTCApp.bat\npm-debug.log

**Comment by newjcj** [comment]
111

**Comment by newjcj** [comment]
是什么问题

**Comment by newjcj** [comment]
what ever
