### ISSUE TITLE
npm install pug  Refusing to install pug as a dependency of itself

### ISSUE THREAD

**Issue by nagarajasamala** [npm/npm#14287]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [x] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by nagarajasamala** [comment]
pug not installing on linux

**Comment by KenanY** [comment]
@nagarajasamala Is the `"name"` property of your local `package.json` set to `"pug"` by any chance? Could you change it to something more unique?

**Comment by Alam1386** [comment]
Refusing to install bootstrap as a dependency of itself

**Comment by Alam1386** [comment]
**Hi all i could not install the bootstrap and it gave me this error.** 
----------------------------------------------------------------------------------------
MacBook-Pro:~ Alam$ cd bootstrap-3.3.7
MacBook-Pro:bootstrap-3.3.7 Alam$ npm install bootstrap@3
npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "bootstrap@3"
npm ERR! node v6.8.1
npm ERR! npm  v3.10.8
npm ERR! code ENOSELF

npm ERR! Refusing to install bootstrap as a dependency of itself
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Alam/bootstrap-3.3.7/npm-debug.log
MacBook-Pro:bootstrap-3.3.7 Alam$

**Comment by KenanY** [comment]
@Alam1386 My comment above applies to your error too (just replace where I said "pug" with "bootstrap").

**Comment by KenanY** [comment]
Closing due to no response.
