### ISSUE TITLE
npm install --no-save flag

### ISSUE THREAD

**Issue by ssylvia** [npm/npm#14285]
#### What's the feature?
Add an options to forcibly not save a dependency to `package.json` when running `npm install`

#### What problem is the feature intended to solve?
Since users are able to use this config `npm config set save true` to have all their dependencies saved by default, we need a way to optionally not save some of them. I have a script that locally installs some extra dependencies for dev purposes only but I do not want them saved.

#### Is the absence of this feature blocking you or your team? If so, how?
It's an extra step to verify packages don't get saved

#### Is this feature similar to an existing feature in another tool?
I don't think so

#### Is this a feature you're prepared to implement, with support from the npm CLI team?
No

**Comment by KenanY** [comment]
This already works for me. Have you tried this yourself?

**Comment by ssylvia** [comment]
Yes, sorry this does work. I could find any documentation around it so I assumed it didn't exist.

**Comment by KenanY** [comment]
@ssylvia Yeah, you can append "no" to any config to make it false, so `--no-save`, `--no-optional`, `--no-progress` all set their respective configs to `false`.
