### ISSUE TITLE
Getting error while installing reactjs through npm

### ISSUE THREAD

**Issue by satheeshdiva** [npm/npm#14280]
#### I'm opening this issue because:
- [ ] npm is doing something I don't understand.
  
  I am trying to install ReactJs package through NPM, when i try to do that i getting the following error

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\node.exe" "C:\Program Files\node_modules\npm\bin\npm-cli.js" "install" "--save" "react" "react-dom"
npm ERR! node v6.8.0
npm ERR! npm  v3.10.8

npm ERR! Protocol "https:" not supported. Expected "http:"
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     D:\ReactJs Prac\sample-reactjs\npm-debug.log

Can someone resolve this issue please???Thanks

**Comment by zkat** [comment]
Can you post the `npm-debug.log` to gist.github.com to help me get a better idea of where this error's coming from?
