### ISSUE TITLE
angular-cli installing...npm install not working

### ISSUE THREAD

**Issue by ppeeou** [npm/npm#14295]
#### I'm opening this issue because:
- [ ] npm is crashing. 
#### What's going wrong?

npm install not working
#### How can the CLI team reproduce the problem?

https://gist.github.com/ppeeou/6e399fd10e10c0d9ee08514d326b1116
### supporting information:
- `npm -v` prints:3.10.8
- `node -v` prints:4.3.2
- `npm config get registry` prints:https://registry.npmjs.org/
- Windows, OS X/macOS, or Linux?:Windows

-->

**Comment by zkat** [comment]
It looks like your connection is being flaky. There's not really much we can do with this, if your network keeps dropping connections. Since some of them are succeeding, try running the install a few times or getting on a more reliable network for the bulk of the install.
