### ISSUE TITLE
Not able to install Protractor, it is showing error while installing. How to resolve it?

### ISSUE THREAD

**Issue by Parthiban32** [npm/npm#14299]
#### I'm opening this issue because:
- [ ] npm is producing error message while installing.

**While Installing Protractor, it is showing following error, How to resolve it?**

Your environment has been set up for using Node.js 6.8.0 (ia32) and npm.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\
node_modules\npm\bin\npm-cli.js" "install" "-g" "protractor"
npm ERR! node v6.8.0
npm ERR! npm  v3.10.8
npm ERR! code EPROTO
npm ERR! errno EPROTO
npm ERR! syscall write

npm ERR! write EPROTO 0:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unkno
wn protocol:openssl\ssl\s23_clnt.c:794:
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

**NPM-BEBUG LOG**

0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli   'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'protractor' ]
2 info using npm@3.10.8
3 info using node@v6.8.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData protractor
8 silly fetchNamedPackageData protractor
9 silly mapToRegistry name protractor
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'protractor',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'protractor',
12 silly mapToRegistry   name: 'protractor',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/protractor
14 verbose request uri https://registry.npmjs.org/protractor
15 verbose request no auth needed
16 info attempt registry request try #1 at 8:28:03 AM
17 verbose request id b1067f25116dfbf0
18 http request GET https://registry.npmjs.org/protractor
19 info retry will retry, error on last attempt: Error: write EPROTO 0:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:794:
20 info attempt registry request try #2 at 8:28:14 AM
21 http request GET https://registry.npmjs.org/protractor
22 info retry will retry, error on last attempt: Error: write EPROTO 0:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:794:
23 info attempt registry request try #3 at 8:29:15 AM
24 http request GET https://registry.npmjs.org/protractor
25 silly fetchPackageMetaData Error: write EPROTO 0:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:794:
25 silly fetchPackageMetaData
25 silly fetchPackageMetaData     at exports._errnoException (util.js:1026:11)
25 silly fetchPackageMetaData     at WriteWrap.afterWrite (net.js:799:14)
25 silly fetchPackageMetaData  error for protractor { Error: write EPROTO 0:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:794:
25 silly fetchPackageMetaData
25 silly fetchPackageMetaData     at exports._errnoException (util.js:1026:11)
25 silly fetchPackageMetaData     at WriteWrap.afterWrite (net.js:799:14) code: 'EPROTO', errno: 'EPROTO', syscall: 'write' }
26 silly rollbackFailedOptional Starting
27 silly rollbackFailedOptional Finishing
28 silly runTopLevelLifecycles Finishing
29 silly install printInstalled
30 verbose stack Error: write EPROTO 0:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:794:
30 verbose stack
30 verbose stack     at exports._errnoException (util.js:1026:11)
30 verbose stack     at WriteWrap.afterWrite (net.js:799:14)
31 verbose cwd C:\Users\prajasekaran
32 error Windows_NT 6.1.7601
33 error argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "protractor"
34 error node v6.8.0
35 error npm  v3.10.8
36 error code EPROTO
37 error errno EPROTO
38 error syscall write
39 error write EPROTO 0:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:794:
40 error If you need help, you may report this error at:
40 error     https://github.com/npm/npm/issues
41 verbose exit [ 1, true ]
### Supporting Information:
- Windows, OS X/macOS, or Linux?: **I am having Windows 7 32bit**

**Comment by Parthiban32** [comment]
Please give a solution for this issue.

**Comment by AmrutaSony** [comment]
Getting same issue for windows 10. I have set all proxy setting using command prompt .
