### ISSUE TITLE
Windows: npm install with --prefix does not link executables to the .bin directory

### ISSUE THREAD

**Issue by kirly-af** [npm/npm#14294]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [X] npm is producing an incorrect install.
- [ ] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):

When running `npm --prefix ../foo install ../foo`, executables are linked directly to **../foo** instead of the **../foo/node_modules/.bin** directory. This works as expected on Linux.
#### Environment

Windows 10
node 6.8.0
npm 3.10.8
shells: cmd, bash(msys git)

**Comment by iarna** [comment]
Note to ourselves: I think that it may be acting like it's in global mode, which is why (on windows only) it's putting things in the `prefix` instead of the `.bin` folder.
