### ISSUE TITLE
Install Express Error Unexpected token < 

### ISSUE THREAD

**Issue by JCarlos12** [npm/npm#14298]
When I try to run 
npm install express --save

I get an error of Unexpected token <

I already set my proxy and the registry

Can anyone help

0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli   'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'express',
1 verbose cli   '--save' ]
2 info using npm@2.15.9
3 info using node@v4.6.0
4 verbose install initial load of C:\windows\system32\package.json
5 verbose readDependencies loading dependencies from C:\windows\system32\package.json
6 silly cache add args [ 'express', null ]
7 verbose cache add spec express
8 silly cache add parsed spec Result {
8 silly cache add   raw: 'express',
8 silly cache add   scope: null,
8 silly cache add   name: 'express',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: 'latest',
8 silly cache add   type: 'tag' }
9 silly addNamed express@latest
10 verbose addNamed "latest" is being treated as a dist-tag for express
11 info addNameTag [ 'express', 'latest' ]
12 silly mapToRegistry name express
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry http://registry.npmjs.org/
15 silly mapToRegistry data Result {
15 silly mapToRegistry   raw: 'express',
15 silly mapToRegistry   scope: null,
15 silly mapToRegistry   name: 'express',
15 silly mapToRegistry   rawSpec: '',
15 silly mapToRegistry   spec: 'latest',
15 silly mapToRegistry   type: 'tag' }
16 silly mapToRegistry uri http://registry.npmjs.org/express
17 verbose addNameTag registry:http://registry.npmjs.org/express not in flight; fetching
18 verbose request uri http://registry.npmjs.org/express
19 verbose request no auth needed
20 info attempt registry request try #1 at 8:55:55 AM
21 verbose request id ce5f88d677baffc3
22 http request GET http://registry.npmjs.org/express
23 http 404 http://registry.npmjs.org/express
24 verbose bad json <html>
24 verbose bad json <head><title>404 Not Found</title></head>
24 verbose bad json <body bgcolor="white">
24 verbose bad json <center><h1>404 Not Found</h1></center>
24 verbose bad json <hr><center>nginx</center>
24 verbose bad json </body>
24 verbose bad json </html>
25 error registry error parsing json
26 verbose headers { server: 'nginx',
26 verbose headers   date: 'Mon, 17 Oct 2016 00:55:56 GMT',
26 verbose headers   'content-type': 'text/html',
26 verbose headers   'content-length': '162',
26 verbose headers   connection: 'close' }
27 silly get cb [ 404,
27 silly get   { server: 'nginx',
27 silly get     date: 'Mon, 17 Oct 2016 00:55:56 GMT',
27 silly get     'content-type': 'text/html',
27 silly get     'content-length': '162',
27 silly get     connection: 'close' } ]
28 verbose stack SyntaxError: Unexpected token <
28 verbose stack <html>
28 verbose stack <head><title>404 Not Found</title></head>
28 verbose stack <body bgcolor="white">
28 verbose stack <center><h1>404 Not Found</h1></center>
28 verbose stack <hr><center>nginx</center>
28 verbose stack </body>
28 verbose stack </html>
28 verbose stack
28 verbose stack     at Object.parse (native)
28 verbose stack     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:199:23)
28 verbose stack     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:172:14)
28 verbose stack     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:200:22)
28 verbose stack     at emitTwo (events.js:87:13)
28 verbose stack     at Request.emit (events.js:172:7)
28 verbose stack     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1067:10)
28 verbose stack     at emitOne (events.js:82:20)
28 verbose stack     at Request.emit (events.js:169:7)
28 verbose stack     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:988:12)
29 verbose cwd C:\windows\system32
30 error Windows_NT 6.1.7601
31 error argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "express" "--save"
32 error node v4.6.0
33 error npm  v2.15.9
34 error Unexpected token <
34 error <html>
34 error <head><title>404 Not Found</title></head>
34 error <body bgcolor="white">
34 error <center><h1>404 Not Found</h1></center>
34 error <hr><center>nginx</center>
34 error </body>
34 error </html>
35 error If you need help, you may report this error at:
35 error     https://github.com/npm/npm/issues
36 verbose exit [ 1, true ]

**Comment by zkat** [comment]
Hi! This looks like a proxy configuration error: Please [make npm is properly configured to use your proxy](http://jjasonclark.com/how-to-setup-node-behind-web-proxy/) and try again. Since this is almost certainly the issue at hand, I'm closing this issue, but feel free to ask for it to be reopened if you have further problems. :)
