### ISSUE TITLE
Vue js problem install

### ISSUE THREAD

**Issue by biozlab** [npm/npm#14292]
I install vue js with 'vue init webpack'
then i instal dependencies with 'npm install' 
then i run with 'npm run dev'
when i run 'npm run dev' 

i have this in npm debug log

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@2.15.9
3 info using node@v4.6.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info predev todos@1.0.0
6 info dev todos@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info todos@1.0.0 Failed to exec dev script
9 verbose stack Error: todos@1.0.0 dev: `node build/dev-server.js`
9 verbose stack spawn C:\Windows\system32\cmd.exe;C:\wamp\bin\php\php5.5.12\php.exe ENOENT
9 verbose stack     at exports._errnoException (util.js:907:11)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
9 verbose stack     at onErrorNT (internal/child_process.js:344:16)
9 verbose stack     at nextTickCallbackWith2Args (node.js:442:9)
9 verbose stack     at process._tickCallback (node.js:356:17)
10 verbose pkgid todos@1.0.0
11 verbose cwd E:\TUTO\vuejs
12 error Windows_NT 6.1.7601
13 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
14 error node v4.6.0
15 error npm  v2.15.9
16 error file C:\Windows\system32\cmd.exe;C:\wamp\bin\php\php5.5.12\php.exe
17 error path C:\Windows\system32\cmd.exe;C:\wamp\bin\php\php5.5.12\php.exe
18 error code ELIFECYCLE
19 error errno ENOENT
20 error syscall spawn C:\Windows\system32\cmd.exe;C:\wamp\bin\php\php5.5.12\php.exe
21 error todos@1.0.0 dev: `node build/dev-server.js`
21 error spawn C:\Windows\system32\cmd.exe;C:\wamp\bin\php\php5.5.12\php.exe ENOENT
22 error Failed at the todos@1.0.0 dev script 'node build/dev-server.js'.
22 error This is most likely a problem with the todos package,
22 error not with npm itself.
22 error Tell the author that this fails on your system:
22 error     node build/dev-server.js
22 error You can get information on how to open an issue for this project with:
22 error     npm bugs todos
22 error Or if that isn't available, you can get their info via:
22 error
22 error     npm owner ls todos
22 error There is likely additional logging output above.
23 verbose exit [ 1, true ]

**Comment by biozlab** [comment]
Any ideas ?

**Comment by KenanY** [comment]
@biozlab The error log indicates that your `"dev"` script is returning an error code. Does running `node build/dev-server.js` manually from your command-line return any error?

**Comment by biozlab** [comment]
Thank you for your answer !
@KenanY no error when i run node build/dev-server.js
It is not a npm problem...

However in documentation you can se it should be work : https://github.com/vuejs-templates/webpack

In my package.json
"scripts": {
    "dev": "node build/dev-server.js",
    "build": "node build/build.js",
    "lint": "eslint --ext .js,.vue src"
  },

if i replace "dev" by something

It should be work ?

**Comment by KenanY** [comment]
@biozlab 

> if i replace "dev" by something
> 
> It should be work ?

What makes you say that?

**Comment by biozlab** [comment]
nothing. I thought it was that to configure command for run dev and build.
But the question is why "npm run dev" doesn't work ?
