### ISSUE TITLE
code DEPTH_ZERO_SELF_SIGNED_CERT on macOS El Capitan

### ISSUE THREAD

**Issue by borlam** [npm/npm#14303]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [X] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
When I try to install gulp npm return a ERROR with SSL.
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "gulp"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code DEPTH_ZERO_SELF_SIGNED_CERT

npm ERR! self signed certificate
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/atlas/npm-debug.log
### supporting information:

 - `npm -v` prints: 2.14.7
 - `node -v` prints: v4.2.1
 - `npm config get registry` prints:https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS 10.11 El Capitan
 - Network issues:
   - Geographic location where npm was run:
   - [X] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

[npm-debug.log.gz](https://github.com/npm/npm/files/532689/npm-debug.log.gz)

**Comment by snopeks** [comment]
This is a proxy config issue, you can see more info on this issue here:  https://github.com/npm/npm/wiki/Troubleshooting#ssl-error
We recommend reaching out to your sysadmin to configure your proxy with SSL. If you have more questions you can reach us at support@npmjs.com!
