### ISSUE TITLE
npm install -g bower  failed

### ISSUE THREAD

**Issue by YangPengwan** [npm/npm#14305]
npm http GET https://registry.npmjs.org/bower
npm http 200 https://registry.npmjs.org/bower
npm http GET https://registry.npmjs.org/bower/-/bower-1.7.9.tgz
npm http 200 https://registry.npmjs.org/bower/-/bower-1.7.9.tgz
npm ERR! Error: shasum check failed for /root/tmp/npm-31122-tHcTm6cM/1476694895045-0.852777497144416/tmp.tgz
npm ERR! Expected: b7296c2393e0d75edaa6ca39648132dd255812b0
npm ERR! Actual:   605acee3794cbfc6e9135ce6a929f79af974a4bd
npm ERR!     at /usr/lib/nodejs/sha/index.js:38:8
npm ERR!     at ReadStream.<anonymous> (/usr/lib/nodejs/sha/index.js:85:7)
npm ERR!     at ReadStream.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-86-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "bower"
npm ERR! cwd /var/www/html/wanjinan
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /var/www/html/wanjinan/npm-debug.log
npm ERR! not ok code 0

Ask for help. Thank you!

**Comment by KenanY** [comment]
@YangPengwan `npm@1.3` is over a year old and is no longer supported. You should try [updating](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm).
