### ISSUE TITLE
"resolv.h" doesn't compile on MacOS for c++ native modules

### ISSUE THREAD

**Issue by neilxa** [npm/npm#14306]
I'm sorry, but I'm not sure if this is a bug of npm or nodejs.

I filed a issue here:
https://github.com/nodejs/node/issues/9129
https://github.com/nodejs/help/issues/327

In short,  my c++ modules which uses `#include<resolv.h>`, can not compile on Mac os.

Here is the sample project: 
https://github.com/neilxa/mytest

To reproduce the issue, clone and build the project:

```
git clone https://github.com/neilxa/mytest.git

npm install mytest/ --verbose
```

**Comment by zkat** [comment]
Issues around specifically compiling native modules and such isn't really in the purview of the npm CLI. I noticed the issue has been addressed node-side, too, so I'm closing this now.

**Comment by neilxa** [comment]
Hi, @zkat 

Sorry, but I have to comment more.

I dug more into this issue recently.  It seems likely a bug of npm.

My module can compile in nodejs 0.12.  With `npm install --verbose`, I found the compile command is like:

```shell
c++   ....  \
-I/Users/neil/.node-gyp/0.12.3/src \
-I/Users/neil/.node-gyp/0.12.3/deps/uv/include \
-I/Users/neil/.node-gyp/0.12.3/deps/v8/include  \
.....
-c -o mytest.o  mytest.cc

``` 
 

While for nodejs 6.0,  `npm install  --verbose` shows the compile command like:

```shell
c++ ....... \
-I/Users/neil/.node-gyp/6.0.0/include/node \
-I/Users/neil/.node-gyp/6.0.0/src \
-I/Users/neil/.node-gyp/6.0.0/deps/uv/include \
-I/Users/neil/.node-gyp/6.0.0/deps/v8/include  \
......
 -c -o mytest.o mytest.cc
```

There is  one more `-I/Users/neil/.node-gyp/6.0.0/include/node`  option.

Which adds a include path more than before.

It was added on Sep 10 2015 by https://github.com/npm/npm/commit/9d6666b7ddb36a2ec93314371d9b48db67c321a0#diff-326fb1fce8d91429c1bb4c0694bf43afR8

to support v4.0.3


In the include path `/Users/neil/.node-gyp/6.0.0/include/node `, it contains a header file named `nameser.h`.  Which seems to override my system's default `/usr/include/nameser.h`.

That is why my module can not compile.


Let's simplify the problem.  For example my source code is like:

```c
//mytest.cc

//I need to include resolv.h to do my logic.
#include<resolv.h>

int main(int argc, char** argv) {
  //do nothing, just for test.
  return 0
}
```

This works:
(my c++ module is compiled this way in nodejs 0.12)
```
c++   -o mytest.o mytest.cc
```

But this doesn't :
(this is the way my module is compiled on nodejs 4 or later)
```
c++   -I/Users/neil/.node-gyp/6.0.0/include/node   -o mytest.o mytest.cc
```


This problem is only on my Mac,  the linux and windows version is ok.

Would you please give me some comments ? 

Thanks very much.
