### ISSUE TITLE
npm link failure edge case

### ISSUE THREAD

**Issue by kumavis** [npm/npm#14308]
#### I'm opening this issue because:
- [x] npm is crashing.
- [x] npm is producing an incorrect install.
- [x] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
#### What's going wrong?

`npm link` fails with `Cannot read property '0' of undefined`

console output: https://gist.github.com/kumavis/21805b4ab71f6ad4e64fa00d0d53ed6b
npm-debug.log: https://gist.github.com/kumavis/62312ec63e4811bd50b0be5e2c4d0f0e
#### How can the CLI team reproduce the problem?

prepare module to be linked

```
git clone git@github.com:ipfs/js-ipfs-block.git
cd js-ipfs-block
git checkout awesome-ipld 
npm install
npm link
```

link into project

```
git clone git@github.com:ipld/js-ipld-dag-cbor.git
cd js-ipld-dag-cbor
git checkout awesome-ipld
npm link js-ipfs-block
# error happens here
```
### supporting information:
- `npm -v` prints: 3.10.8
- `node -v` prints: 6.3.1
- `npm config get registry` prints: https://registry.npmjs.org/
- Windows, OS X/macOS, or Linux?: macOS 10.10.5 (14F1912)
- Network issues:
  - Geographic location where npm was run: `Washington, Seattle`
  - [x] I use a proxy to connect to the npm registry.
  - [x] I use a proxy to connect to the web.
  - [x] I use a proxy when downloading Git repos.
  - [x] I access the npm registry via a VPN
  - [ ] I don't use a proxy, but have limited or unreliable internet access.
- Container:
  - [ ] I develop using Vagrant on Windows.
  - [ ] I develop using Vagrant on OS X or Linux.
  - [ ] I develop / deploy using Docker.
  - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kumavis** [comment]
works on:
node 5.3.0
npm 3.3.12

**Comment by kumavis** [comment]
Also *does not work* on:
node v5.3.0
npm  v3.3.12

**Comment by kumavis** [comment]
I realized theres a naming mismatch

`npm link js-ipfs-block` should be `npm link ipfs-block`

however a incorrectly named module usually results in the following error:
```
╭─kumavis@xyzs-MacBook-Pro  ~/dev/js-ipld-dag-cbor ‹node-v4.2.3›  (awesome-ipld*) 
╰─$ npm link xyz12121211212
npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/kumavis/.nvm/versions/node/v4.2.3/bin/node" "/Users/kumavis/.nvm/versions/node/v4.2.3/bin/npm" "link" "xyz12121211212"
npm ERR! node v4.2.3
npm ERR! npm  v3.8.0
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/xyz12121211212
npm ERR! 404 
npm ERR! 404  'xyz12121211212' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kumavis/dev/js-ipld-dag-cbor/npm-debug.log
```

**Comment by kumavis** [comment]
seems i accidentally cloned `js-ipfs-block` inside of `js-ipld-dag-cbor`. This may have caused the strange error.

**Comment by legodude17** [comment]
The error comes from `[lib/link.js#80](https://github.com/npm/npm/blob/master/lib/link.js#L80)`. Somehow `installed` is []. So then that fails. Then, since you misslled it in `[lib/link.js#90](https://github.com/npm/npm/blob/master/lib/link.js#L93)` it tries to install it, and then `n()` is called in `[lib/install.js#236](https://github.com/npm/npm/blob/master/lib/install.js#L236)`.

**Comment by legodude17** [comment]
Looking a little more, this problem comes when the package you specify to link is in the registry, but not linked already.

**Comment by legodude17** [comment]
Follow that a little further, in [`lib/install.js#693`](https://github.com/npm/npm/blob/master/lib/install.js#L693), then if nothing is changed, then `cb()` (which is `n()` from above) is called with no arguments. So that means that in his case it is when all the above is true, and the installer somehow does nothing.
