### ISSUE TITLE
"Unsupported engine" error when currently installed versions satisfy the wanted versions

### ISSUE THREAD

**Issue by brynjagr** [npm/npm#14304]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I get the following error when trying to install `shrinkpack@0.17.0`:

```
npm ERR! notsup Unsupported engine for shrinkpack@0.17.0: wanted: {"npm":"<3.8.8 >=3.10.4"} (current: {"node":"4.6.0","npm":"3.10.8"})
npm ERR! notsup Not compatible with your version of node/npm: shrinkpack@0.17.0
npm ERR! notsup Not compatible with your version of node/npm: shrinkpack@0.17.0
npm ERR! notsup Required: {"npm":"<3.8.8 >=3.10.4"}
npm ERR! notsup Actual:   {"npm":"3.10.8","node":"4.6.0"}
```

Stack trace:
```
npm verb stack Error: Unsupported engine for shrinkpack@0.17.0: wanted: {"npm":"<3.8.8 >=3.10.4"} (current: {"node":"4.6.0","npm":"3.10.8"})
npm verb stack     at checkEngine (/usr/local/lib/node_modules/npm/node_modules/npm-install-checks/index.js:13:14)
npm verb stack     at module.exports.isInstallable (/usr/local/lib/node_modules/npm/lib/install/validate-args.js:38:3)
npm verb stack     at actions.(anonymous function) (/usr/local/lib/node_modules/npm/lib/install/actions.js:52:14)
npm verb stack     at execAction (/usr/local/lib/node_modules/npm/lib/install/actions.js:114:7)
npm verb stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
npm verb stack     at Array.forEach (native)
npm verb stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
npm verb stack     at Array.forEach (native)
npm verb stack     at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
npm verb stack     at exports.doParallel (/usr/local/lib/node_modules/npm/lib/install/actions.js:144:3)
```

#### How can the CLI team reproduce the problem?
Unsure. I have tried to use the same versions of node and npm on a few different machines, but I have not been able to reproduce the problem. Might be something wrong with the settings on my machine, but I'm not sure what it can be.

I have reintalled both node and npm and have tested with several different versions, but without luck

### supporting information:

 - `npm -v` prints: 3.10.8
 - `node -v` prints: 4.6.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS Sierra

**Comment by JamieMason** [comment]
Hi @brynjagr, 
I've modified the semver range in [shrinkpack@0.17.1](https://github.com/JamieMason/shrinkpack/blob/90984f7862e3eae8d60888eddc3bcee16ad243c1/CHANGELOG.md) so this issue should be resolved now.

Thanks.

**Comment by KenanY** [comment]
Closing as resolved then.
