### ISSUE TITLE
RouteConfig in Node_modules

### ISSUE THREAD

**Issue by netsup99** [npm/npm#14316]
hi,

Started  Learning/testing  Angular2 in vs2015 with TypeScript Project.
I can't import { RouteConfig, ROUTE_DIRECTIVES, ROUTER_PROVIDERS } from '@angular/router';
and
import { bootstrap } from '@angular/platform-browser-dynamic

output Error-message:
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! No compatible version found: @angular/router-deprecated@~3.1.0
npm ERR! Valid install targets:
npm ERR! 2.0.0-rc.2, 2.0.0-rc.1, 2.0.0-rc.0, 0.0.0-7, 0.0.0-6

///... Mike

**Comment by watilde** [comment]
Hello! It seems to be missing some packages. For your case, install the missing packages may resolve the issue:
```
$ npm install --save @angular/platform-browser-dynamic
$ npm install --save @angular/router
```

**Comment by netsup99** [comment]
UnInstall and Install again did not worki n VS 2015 or VS Studio Code.
Where is Bootsrap?

**Comment by netsup99** [comment]
It did not work in VS2015 or VS Studio Code. I  did an unistallation before installation.
//...Mike

**Comment by netsup99** [comment]
import files are typescript files(app.component) in app-folder.
Following "official" example from site angular.io.
node -v  is v6.3.1
npm -v is 3.10

**Comment by netsup99** [comment]
import files are typescript files(app.component) in app-folder.
Following "official" example from site angular.io.
node -v  is v6.3.1
npm -v is 3.10
//...Mike
