### ISSUE TITLE
npm dedupe gives `Cannot read property 'localeCompare' of null`

### ISSUE THREAD

**Issue by SimenB** [npm/npm#14317]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### How can the CLI team reproduce the problem?

I just did `npm dedupe`. There are some private dependencies, so I doubt the list would help you, as you wouldn't be able to install yourself.

https://gist.github.com/SimenB/86d7839040878f3b9cc07607f0eddfa5

### supporting information:

 - `npm -v` prints: `v3.10.9`
 - `node -v` prints: `v6.7.0`
 - `npm config get registry` prints: `http://npm.finntech.no/`
 - Windows, OS X/macOS, or Linux?: macOS
 - Network issues:
   - Geographic location where npm was run:
   - [x] I use a proxy to connect to the npm registry. (Artifactory)
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [x] I develop / deploy using Docker. (deploy)
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by watilde** [comment]
Hi. Thanks for reporting this! I think it's duplicated issue with https://github.com/npm/npm/issues/13975

**Comment by SimenB** [comment]
Yeah, looks like it!
