### ISSUE TITLE
getting this error while installing bower

### ISSUE THREAD

**Issue by deepakkumar138** [npm/npm#14314]
I ran sudo npm install -g bower for installing bower but got the following errors:

odluser@server2:~$ sudo npm install -g bower
npm ERR! not a package /home/odluser/tmp/npm-27820-xcLH0M_B/1476740774831-0.5555074941366911/tmp.tgz
npm http GET http://registry.npmjs.org/bower
npm http GET http://registry.npmjs.org/bower
npm http GET http://registry.npmjs.org/bower
npm ERR! network getaddrinfo ENOTFOUND
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! System Linux 3.13.0-98-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "bower"
npm ERR! cwd /home/odluser
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! syscall getaddrinfo
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/odluser/npm-debug.log
npm ERR! not ok code 0

other info:
java -version : 1.8.0_91
mvn --version : Apache Maven 3.3.3
git --version : git version 2.10.1
node --version : v0.10.25
npm --version : 1.3.10
jq --version : jq version 1.3

Can someone help me regarding this error ? I already changed the proxy settings.

**Comment by watilde** [comment]
Hi! You seem to be using old version of the npm. Check the following troubleshooting and try the latest version, please :)
https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-node

**Comment by deepakkumar138** [comment]
trying to upgrade npm shows this error...:

root@server2:~# npm install -g npm@latest
npm http GET https://registry.npmjs.org/npm
npm http GET https://registry.npmjs.org/npm
npm http GET https://registry.npmjs.org/npm
npm ERR! network getaddrinfo ENOTFOUND
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! System Linux 3.13.0-98-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "npm@latest"
npm ERR! cwd /root
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! syscall getaddrinfo
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /root/npm-debug.log
npm ERR! not ok code 0

------------------------------------------------------------------------------------------
root@server2:~# npm install -g npm@lts
npm http GET https://registry.npmjs.org/npm
npm http GET https://registry.npmjs.org/npm
npm http GET https://registry.npmjs.org/npm
npm ERR! network getaddrinfo ENOTFOUND
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! System Linux 3.13.0-98-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "npm@lts"
npm ERR! cwd /root
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! syscall getaddrinfo
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /root/npm-debug.log
npm ERR! not ok code 0

**Comment by KenanY** [comment]
@deepakkumar138 Might be best to simply update Node.js; newer versions of Node.js come with newer versions of `npm`.

**Comment by KenanY** [comment]
Closing since `npm@1.3` has not been supported for a long time now. Can reopen if this is still an issue with `npm@2 || 3 || 4`.
