### ISSUE TITLE
Recursively called NPM scripts do not see overridden config values

### ISSUE THREAD

**Issue by fracz** [npm/npm#14310]
#### What's going wrong?

Npm scripts that are called recursively do not see the config values overridden with `--project:configattr=value` argument.
#### How can the CLI team reproduce the problem?

_package.json_:

``` json
{
  "name": "example",
  "config": {
    "var": "X"
  },
  "scripts": {
    "taskA": "echo %npm_package_config_var%",
    "taskB": "npm run taskA"
  }
}
```

Result:

```
$ npm run taskA -s
X
$ npm run taskB -s
X
$ npm run taskA -s --example:var=Y
Y
$ npm run taskB -s --example:var=Y
X
```

IMO, the last call should print `Y`.
### supporting information:
- `npm -v` prints: 3.3.12
- `node -v` prints: v5.1.1
- Windows, OS X/macOS, or Linux?: Windows

**Comment by legodude17** [comment]
The reason it doesn't do this would be that it doesn't remove `npm_package_config` from the front of env variables when copying. So your request is to do that. I agree with you that that is a thing that should happen.
