### ISSUE TITLE
npm install -g gulp

### ISSUE THREAD

**Issue by hfornazari** [npm/npm#14321]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [ ] npm is producing an incorrect install.
- [ ] npm is doing something I don't understand.
- [X] Other (_see below for feature requests_):
#### What's going wrong?

Notificação: PROXY_AUTH_REQUIRED
#### How can the CLI team reproduce the problem?

proxy=http://DOMINIO%5Cuser:pass%2399@proxy.SHOWING.com.br:3128/
https-proxy=http://DOMINIO%5Cuser:Pass%2346@proxy.SHOWING.com.br:3128/
registry=http://registry.npmjs.org/
strict-ssl=false

### supporting information:
- `npm -v` prints:
  v3.10.8
- `node -v` prints:
  node v6.8.1
- `npm config get registry` prints: 
  http://registry.npmjs.org/
- Windows, OS X/macOS, or Linux?:
  Win 7
- Network issues:
  - Geographic location where npm was run:
  - [ ] I use a proxy to connect to the npm registry.
  - [ X ] I use a proxy to connect to the web.
  - [ ] I use a proxy when downloading Git repos.
  - [ ] I access the npm registry via a VPN
  - [ ] I don't use a proxy, but have limited or unreliable internet access.
- Container:
  - [ ] I develop using Vagrant on Windows.
  - [ ] I develop using Vagrant on OS X or Linux.
  - [ ] I develop / deploy using Docker.
  - [ ] I deploy to a PaaS (Triton, Heroku).

C:\Users\93050775>npm install -g gulp
npm ERR! registry error parsing json
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\
node_modules\npm\bin\npm-cli.js" "install" "-g" "gulp"
npm ERR! node v6.8.1
npm ERR! npm  v3.10.8

npm ERR! Unexpected token < in JSON at position 0
npm ERR! <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
npm ERR! "http://www.w3.org/TR/html4/loose.dtd">
npm ERR! <html>
npm ERR! <head>
npm ERR! <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
npm ERR! <title>Notificação: Autorização de proxy necessária</title><style type=
"text/css">
npm ERR! body {
npm ERR!   font-family: Arial, Helvetica, sans-serif;
npm ERR!   font-size: 14px;
npm ERR!   color:#333333;
npm ERR!   background-color: #ffffff;
npm ERR! }
npm ERR! h1 {
npm ERR!   font-size: 18px;
npm ERR!   font-weight: bold;
npm ERR!   text-decoration: none;
npm ERR!   padding-top: 0px;
npm ERR!   color: #2970A6;
npm ERR! }
npm ERR! a:link {
npm ERR!     color: #2970A6;
npm ERR!   text-decoration: none;
npm ERR! }
npm ERR! a:hover {
npm ERR!     color: #2970A6;
npm ERR!   text-decoration: underline;
npm ERR! }
npm ERR! p.buttonlink {
npm ERR!   margin-bottom: 24px;
npm ERR! }
npm ERR! .copyright {
npm ERR!   font-size: 12px;
npm ERR!   color: #666666;
npm ERR!   margin: 5px 5px 0px 30px;
npm ERR!
npm ERR! }
npm ERR! .details {
npm ERR!   font-size: 14px;
npm ERR!   color: #969696;
npm ERR!   border: none;
npm ERR!   padding: 20px 20px 20px 20px;
npm ERR!   margin: 0px 10px 10px 35px;
npm ERR! }
npm ERR!
npm ERR! .shadow {
npm ERR!   border: 3px solid #9f9f9f;
npm ERR!   padding: 10px 25px 10px 25px;
npm ERR!   margin: 10px 35px 0px 30px;
npm ERR!   background-color: #ffffff;
npm ERR!   width: 600px;
npm ERR!
npm ERR!   -moz-box-shadow: 3px 3px 3px #cccccc;
npm ERR!   -webkit-box-shadow: 3px 3px 3px #cccccc;
npm ERR!   box-shadow: 3px 3px 3px #cccccc;
npm ERR!   /\* For IE 8 _/
npm ERR!   -ms-filter: "progid:DXImageTransform.Microsoft.Shadow(Strength=5, Dir
ection=135, Color='cccccc')";
npm ERR!   /_ For IE 5.5 - 7 */
npm ERR!   filter: progid:DXImageTransform.Microsoft.Shadow(Strength=5, Directio
n=135, Color='cccccc');
npm ERR! }
npm ERR! .logo {
npm ERR!   border: none;
npm ERR!   margin: 5px 5px 0px 30px;
npm ERR! }
npm ERR! </style>
npm ERR! </head>
npm ERR!
npm ERR! <body>
npm ERR! <div class="logo"><img src="http://proxyinfo/topo_novo.jpg
" border="0"></div><p>&nbsp;</p>
npm ERR! <div class="shadow">
npm ERR! <h1>Não é possível exibir esta página</h1>
npm ERR!
npm ERR!
npm ERR! <p>
npm ERR! É necessário autenticar para acessar a Internet usando este sistema. Um
a ID de usuário e uma senha válidas devem ser inseridas quando solicitado.
npm ERR! </p>
npm ERR!
npm ERR!
npm ERR!
npm ERR! <p>
npm ERR! Em caso de dúvidas, entre em contato com Segurança da informação
Corporativa, será necessária a avaliação para a liberação do site bloqueado.  Pa
ra isso, por favor abra uma requisição de serviços no Websan com a classificação
 "Segurança da informação > internet > exceções da política".  Se possível, anex
ar um "Print" de tela contendo a mensagem de bloqueio  e forneça os códigos most
rados abaixo.
npm ERR! </p>
npm ERR!
npm ERR! </div>
npm ERR!
npm ERR! <div class="details"><p>
npm ERR! Data: Tue, 18 Oct 2016 16:22:05 GMT<br />
npm ERR! Nome de usuário: <br />
npm ERR! IP de origem: 10.89.15.180<br />
npm ERR! URL: GET http://registry.npmjs.org/gulp<br />
npm ERR! Categoria: <br />
npm ERR! Motivo: UNKNOWN<br />
npm ERR! Notificação: PROXY_AUTH_REQUIRED
npm ERR! </p></div>
npm ERR! </body>
npm ERR! </html>
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\93050775\npm-debug.log

**Comment by zkat** [comment]
oi!

vc precisa da autorização de proxy. o `user:pass` em `http://DOMINIO%5Cuser:Pass%2346@proxy.SHOWING.com.br:3128/` é incorreta.

Tem mais informações aqui:
> Em caso de dúvidas, entre em contato com Segurança da informação
> Corporativa, será necessária a avaliação para a liberação do site bloqueado. Pa
> ra isso, por favor abra uma requisição de serviços no Websan com a classificação
> "Segurança da informação > internet > exceções da política". Se possível, anex
> ar um "Print" de tela contendo a mensagem de bloqueio e forneça os códigos most
> rados abaixo.

**Comment by KenanY** [comment]
Closing as abandoned. Can reopen if this is still an issue :)
