### ISSUE TITLE
Enforce categorization of packages

### ISSUE THREAD

**Issue by ev1stensberg** [npm/npm#14322]
Hi! Sorry for polluting the issue thread. I'm a bit confused why not NPM has some sort of grouping of package types in `package.json`. Keywords or Descriptions are to broad, and with distinct categorization, we could do more in the ecosystem with the package.json from modules. 

Is there any way to implement this or a feature that is somewhat similar?

**Comment by KenanY** [comment]
@ev1stensberg So how will categories differ from, say, keywords? Just looking for more details.

**Comment by ev1stensberg** [comment]
I hope for some sort of required documentation or label of the tool, where others could find tools with similar label faster, such as the search queries from the keywords provided in the npm registry. The problem here is rather that people could ignore having keywords, or if they are imprecise in their language. I more concrete suggestion should rather be that description or keywords should be precise and required in a package.

Hope I answered this somewhat correct. See now that it's the same thing really, but I don't know if this is a feature that could only be present at the npm site and not `package.json`. If so, how could we then extract and use this info?

**Comment by ev1stensberg** [comment]
To note a practical example with pseudocode: 

let `x` be frameworks
let `y` be categories

Find where `x` is the ten most downloaded type of  `y`.

I'd find the ten most downloaded frameworks with the category: UI and then I could use my data respectively.
