### ISSUE TITLE
npm ERR! Invalid protocol: 127.0.0.1:

### ISSUE THREAD

**Issue by yc66** [npm/npm#14320]
![qq 20161019000901](https://cloud.githubusercontent.com/assets/21253535/19486317/9077b75a-9590-11e6-9121-51fe3a18f546.jpg)

**Comment by yc66** [comment]
Try installing the error reported by the ionicframework

**Comment by yc66** [comment]
**The following is the log details**

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'npm@latest' ]
2 info using npm@2.15.9
3 info using node@v4.6.0
4 verbose install initial load of C:\Users\Administrator\AppData\Roaming\npm\package.json
5 verbose readDependencies loading dependencies from C:\Users\Administrator\AppData\Roaming\npm\package.json
6 silly cache add args [ 'npm@latest', null ]
7 verbose cache add spec npm@latest
8 silly cache add parsed spec Result {
8 silly cache add   raw: 'npm@latest',
8 silly cache add   scope: null,
8 silly cache add   name: 'npm',
8 silly cache add   rawSpec: 'latest',
8 silly cache add   spec: 'latest',
8 silly cache add   type: 'tag' }
9 silly addNamed npm@latest
10 verbose addNamed "latest" is being treated as a dist-tag for npm
11 info addNameTag [ 'npm', 'latest' ]
12 silly mapToRegistry name npm
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry http://registry.npmjs.org/
15 silly mapToRegistry data Result {
15 silly mapToRegistry   raw: 'npm',
15 silly mapToRegistry   scope: null,
15 silly mapToRegistry   name: 'npm',
15 silly mapToRegistry   rawSpec: '',
15 silly mapToRegistry   spec: 'latest',
15 silly mapToRegistry   type: 'tag' }
16 silly mapToRegistry uri http://registry.npmjs.org/npm
17 verbose addNameTag registry:http://registry.npmjs.org/npm not in flight; fetching
18 verbose request uri http://registry.npmjs.org/npm
19 verbose request no auth needed
20 info attempt registry request try #1 at 00:20:21
21 verbose request id 410a44034cb920e9
22 http request GET http://registry.npmjs.org/npm
23 info retry will retry, error on last attempt: Error: Invalid protocol: 127.0.0.1:
24 info attempt registry request try #2 at 00:20:31
25 http request GET http://registry.npmjs.org/npm
26 info retry will retry, error on last attempt: Error: Invalid protocol: 127.0.0.1:
27 info attempt registry request try #3 at 00:21:31
28 http request GET http://registry.npmjs.org/npm
29 verbose stack Error: Invalid protocol: 127.0.0.1:
29 verbose stack     at Request.init (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:473:31)
29 verbose stack     at new Request (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:142:8)
29 verbose stack     at request (C:\Program Files\nodejs\node_modules\npm\node_modules\request\index.js:55:10)
29 verbose stack     at CachingRegistryClient.makeRequest (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:149:13)
29 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:66:17
29 verbose stack     at RetryOperation._fn (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\attempt.js:18:5)
29 verbose stack     at null._onTimeout (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\node_modules\retry\lib\retry_operation.js:49:10)
29 verbose stack     at Timer.listOnTimeout (timers.js:92:15)
30 verbose cwd C:\Users\Administrator
31 error Windows_NT 6.1.7601
32 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "npm@latest"
33 error node v4.6.0
34 error npm  v2.15.9
35 error Invalid protocol: 127.0.0.1:
36 error If you need help, you may report this error at:
36 error     <https://github.com/npm/npm/issues>
37 verbose exit [ 1, true ]

**Comment by zkat** [comment]
Are you behind a proxy?

**Comment by yc66** [comment]
My proxy is set to null
Now the school computer can be properly installed
At night I look at this issue

**Comment by jingling0101** [comment]
npm ERR! node v6.8.1
npm ERR! npm  v3.10.8

npm ERR! Invalid protocol: 127.0.0.1:
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\npm-debug.log
