### ISSUE TITLE
Errors whilst trying to install first Angular2 Project

### ISSUE THREAD

**Issue by DannyG93** [npm/npm#14323]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ X] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Trying to create an angular 2 project and constantly getting an error when trying to install package

#### How can the CLI team reproduce the problem?

First time learning Angular 2 so I am following a video tutorial. I have Git installed and went to CMD and typed in npm install -g angular-cli

Once installed I typed the following ng new angular2-fundamentals
It created the folder and some files but then came up with errors. 

https://gist.githubusercontent.com/DannyG93/13b05a5eb2620b3074d6014ede36c9da/raw/11c5e4ddec8589b331d9fc0d65f6dc69aac53873/npm-debug.log

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows,
 - Network issues:
   - Geographic location where npm was run:
  No internet issues.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by zkat** [comment]
@DannyG93 The error you're seeing seems to be `node-sass` running a `postinstall` script and failing -- the output will have gone into your terminal, since we don't write that information to `npm-debug.log`. Most likely, there's some issue with `node-sass` itself, possibly on Windows, and depending on the error, you might wanna bring that up with them.

**Comment by ev1stensberg** [comment]
This is pretty easy to trace down. Could you go to your current working directory and do a console log at node-sass/scripts/build.js . Regardless, it seems that you're having problems with permissions. It's not getting the correct env and is complaining that it doesn't have lifecycle permissions. You should have gotten a log that your env is broken and that sass was trying to manually produce the desired file/folder.

**Comment by DannyG93** [comment]
@ev1stensberg Sorry, what exactly do I need to do I'm new to all this console malarkey! Thanks

**Comment by ev1stensberg** [comment]
try running with sudo as a prefix, otherwise you can write me DM on twitter. [@ev1stensberg](https://twitter.com/ev1stensberg)

**Comment by DannyG93** [comment]
I don't use twitter :/ 

I just tried to install Angular 2 again today and this happened.. 

![untitled](https://cloud.githubusercontent.com/assets/22920902/19572217/52137732-96f9-11e6-9b78-c5fecede58ad.png)

**Comment by ev1stensberg** [comment]
Looks okay from here, don't worry about the warnings etc, its just the libs complaining. Your project should be ok if there isn't the same error.

**Comment by DannyG93** [comment]
Gave it a go, and it worked fine this time around which is odd?!? All sorted now then I guess! 
Thanks for the replies none the less :) @ev1stensberg
