### ISSUE TITLE
npm install fails getting EACCES Error

### ISSUE THREAD

**Issue by bkirtika** [npm/npm#14332]
when I run npm install **with and without sudo**, the following error occurred.

<pre>
Error: EACCES, open '/tmp/npm-9251-dbf5116d/registry.npmjs.org/tar/-/tar-2.2.1.tgz' while getting shasum for /tmp/npm-9251-dbf5116d/registry.npmjs.org/tar/-/tar-2.2.1.tgz

From:     https://registry.npmjs.org/tar/-/tar-2.2.1.tgz
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, open '/tmp/npm-9251-dbf5116d/registry.npmjs.org/tar/-/tar-2.2.1.tgz' while getting shasum for /tmp/npm-9251-dbf5116d/registry.npmjs.org/tar/-/tar-2.2.1.tgz
npm ERR! From:     https://registry.npmjs.org/tar/-/tar-2.2.1.tgz]
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/tmp/npm-9251-dbf5116d/registry.npmjs.org/tar/-/tar-2.2.1.tgz',
npm ERR!   parent: 'docular-markdown-plugin' }
</pre>

Find the attachment of npm-debug.log file - 
[npm-debug.txt](https://github.com/npm/npm/files/538140/npm-debug.txt)

with tar: 2.0.0 version it is working perfectly but with version greater than that it is not working.

**Comment by bkirtika** [comment]
npm clear cache is also not working

**Comment by zkat** [comment]
This is very strange -- it's saying that it doesn't have access to a temporary file that npm *itself* wrote. Can you give us more information on your `/tmp` directory? Are you using any particular `tmpfs` for it? What are the permissions on /tmp/npm-9251-dbf5116d/registry.npmjs.org/tar/-/tar-2.2.1.tgz, if you haven't deleted it yet? (if you have, can you reproduce it and check the file that failed to read?

Thanks. If you can get a reliable repro that we can use, that would be an *immense* help in tracking down this bug.

**Comment by mjoyce91** [comment]
Is there any update on this? Same issue:

`npm ERR! Error: EACCES: permission denied, open '/npmtmp/npm-13331-a13d6d93/registry.npmjs.org/tar/-/tar-2.2.1.tgz' while getting shasum for /npmtmp/npm-13331-a13d6d93/registry.npmjs.org/tar/-/tar-2.2.1.tgz
npm ERR! From:     https://registry.npmjs.org/tar/-/tar-2.2.1.tgz
npm ERR!     at Error (native)
npm ERR!  { Error: EACCES: permission denied, open '/npmtmp/npm-13331-a13d6d93/registry.npmjs.org/tar/-/tar-2.2.1.tgz' while getting shasum for /npmtmp/npm-13331-a13d6d93/registry.npmjs.org/tar/-/tar-2.2.1.tgz
npm ERR! From:     https://registry.npmjs.org/tar/-/tar-2.2.1.tgz
npm ERR!     at Error (native)
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'open',
npm ERR!   path: '/npmtmp/npm-13331-a13d6d93/registry.npmjs.org/tar/-/tar-2.2.1.tgz',
npm ERR!   parent: 'node-gyp' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.`
