### ISSUE TITLE
npm run-script exit code is always 0

### ISSUE THREAD

**Issue by stevenvachon** [npm/npm#14339]
```json
"scripts": {
  "build": "cmd; echo $?"
}
```
This exits with and echoes 1:
```shell
cmd; echo $1
```
While this exits with and echoes 0:
```shell
npm run build
```

**Comment by AlexTes** [comment]
So when you `npm run build` it executes your script which is `cmd; echo $?`. This outputs 1 and exits.

But you're saying when you remove the `echo $?` bit (which is the reason npm cleanly exits as that command returns 0 after outputting `$?`) npm still exits cleanly instead of showing the build command exited with 1?

**Comment by stevenvachon** [comment]
My CI is not getting a `1` exit status when using an `npm run` script. As a result, it's thinking that the build has passed when it may not have.

**Comment by AlexTes** [comment]
The thing is `npm run` should just pass on whatever the exit code is of the command it runs. It looks like your `cmd` is outputting exit code 0. Because replacing the string after `"build": ` with `exit 1` does make npm exit with 1.

**Comment by stevenvachon** [comment]
But running `cmd` directly results in one exit code 1.

**Comment by AlexTes** [comment]
Okay, so if `"build": "cmd; echo $?"` does output 1, it is quite peculiar.
The [npm docs](https://docs.npmjs.com/misc/scripts#exiting) say this:

> Scripts are run by passing the line as a script argument to sh.
> If the script exits with a code other than 0, then this will abort the process.

So if `bash -c cmd` or in case it's a file `bash cmd` exits with a 1, someone with more in-depth knowledge than me would have to take over. Use `echo $?` _after_ executing the line I just mentioned to check the exit code. Adding `echo $?` to the line itself complicates things.

**Comment by stevenvachon** [comment]
Updating to the latest version of the package/program [fixed it](https://github.com/aurelia/cli/commit/86a8be1ca6b6310579f3947f8b6d3ef88c4b539d). And while it works, it should've always worked if the exit code was indeed `1`.

**Comment by AlexTes** [comment]
Right, so it was an issue with aurelia's cli. That commit adds back the needed exit call. 
This can be closed!

**Comment by stevenvachon** [comment]
I understand that adding an exit call fixed the issue, but as I said, when running aurelia-cli directly, it exits with `1`!

**Comment by AlexTes** [comment]
I understand that. Regardless whatever aurelia does is uncommon. A quick search of the issues can show that users don't commonly experience this problem. In other words npm probably does execute with `sh`. That would mean its aurelia-cli that changes its behaviour when it notices its run by npm, making it an aurelia problem, not an npm problem and accordingly to this reasoning they fixed the issue on their end.

Case closed I'd say 😄

**Comment by stevenvachon** [comment]
Alright, thank you.
