### ISSUE TITLE
can't install this -- npm install -g ionic cordova

### ISSUE THREAD

**Issue by titiknf** [npm/npm#14336]
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\AEON>npm -version
3.10.8

C:\Users\AEON>java -version
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)

C:\Users\AEON>npm install -g ionic cordova
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ionic" "cordova"
npm ERR! node v6.9.0
npm ERR! npm  v3.10.8
npm ERR! code UNABLE_TO_VERIFY_LEAF_SIGNATURE

npm ERR! unable to verify the first certificate
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\AEON\npm-debug.log

**Comment by snopeks** [comment]
Hi there! You're running into a proxy config issue, we recommend speaking with your sysadmin about configuring SSL support for the proxy correctly. If you have more questions, you can reach out to us at support@npmjs.com!

**Comment by titiknf** [comment]
oke thank's, it's work..
