### ISSUE TITLE
add a `build` property to the `scripts` object entry

### ISSUE THREAD

**Issue by erikyuzwa** [npm/npm#14341]
#### What's the feature?

Adding a `build` property to `scripts` in `package.json`.

```
eg.
{
  "scripts": {
     "build": "grunt build:prod"
  }
}
```
#### What problem is the feature intended to solve?
- quality of life for any project developer
- more of a chance to jump into a new project and develop the app architecture via the build process
- With a larger sized app with various complex Grunt or Gulp tasks, a common `build` script ability would make it easier to both develop and test on a local / remote dev environment (using `npm start` perhaps) and preserve `build` for a finished production-level set of tasks / execution.
#### Is the absence of this feature blocking you or your team? If so, how?
- No. It's a pure "quality of life" idea for developers.
#### Is this feature similar to an existing feature in another tool?
- Yes. I know we can run `npm run build`
#### Is this a feature you're prepared to implement, with support from the npm CLI team?
- Sure!

**Comment by KenanY** [comment]
@erikyuzwa Can't you already do this today?

**Comment by erikyuzwa** [comment]
@KenanY **YES** absolutely. As I tried to describe, this is a pure *quality of life* suggestion for improvement of teams. I tend to jump between several different projects (as I'm sure others do), and some common convention would be nice for deciding which project tasks are associated with which npm script. At the end of the day it IS just a few extra keystrokes, but then you could make the same argument for most of the *existing* `script` object entry...

**Comment by KenanY** [comment]
@erikyuzwa Oh, are you asking for `npm init` to include a `"build"` script? (In addition to the default `"test"` script.)

**Comment by erikyuzwa** [comment]
@KenanY -- That might be too large a change for others. But you're on the right track. Right now a team can add a `start` entry into `scripts` so that `npm start` will automagically run it. Same idea for `build`.

**Comment by KenanY** [comment]
@erikyuzwa Well, `npm build` is already [taken](https://docs.npmjs.com/cli/build) :)

**Comment by erikyuzwa** [comment]
omg -- you're kidding. I didn't see it here: https://docs.npmjs.com/misc/scripts. Oh no 😿
