### ISSUE TITLE
npm publish   error

### ISSUE THREAD

**Issue by wwttyy** [npm/npm#14344]
#### I'm opening this issue because:

npm is doing something I don't understand.
#### What's going wrong?

npm ERR! Linux 2.6.32-573.7.1.el6.x86_64
npm ERR! argv "/usr/local/node-v6.2.0-linux-x64/bin/node" "/usr/local/node-v6.2.0-linux-x64/bin/npm" "publish"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9

npm ERR! Unexpected token u in JSON at position 0
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/dev/js/myjs/npm-debug.log
#### How can the CLI team reproduce the problem?

npm publish

### supporting information:
- `npm -v` prints: v3.8.9
- `node -v` prints: v6.2.0
- `npm config get registry` prints:  http://192.168.5.226:8090/
- Windows, OS X/macOS, or Linux?: Linux
- Network issues:
  - Geographic location where npm was run:
  - I don't use a proxy, but have limited or unreliable internet access.
- Container:
  -  I develop using Vagrant on Windows.

**Comment by wwttyy** [comment]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/node-v6.2.0-linux-x64/bin/node',
1 verbose cli   '/usr/local/node-v6.2.0-linux-x64/bin/npm',
1 verbose cli   'publish' ]
2 info using npm@3.8.9
3 info using node@v6.2.0
4 verbose publish [ '.' ]
5 silly cache add args [ '.', null ]
6 verbose cache add spec .
7 silly cache add parsed spec Result {
7 silly cache add   raw: '.',
7 silly cache add   scope: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: '.',
7 silly cache add   spec: '/var/www/dev/js/myjs',
7 silly cache add   type: 'directory' }
8 verbose addLocalDirectory /root/.npm/testdsss/1.0.5/package.tgz not in flight; packing
9 verbose correctMkdir /root/.npm correctMkdir not in flight; initializing
10 info lifecycle testdsss@1.0.5~prepublish: testdsss@1.0.5
11 silly lifecycle testdsss@1.0.5~prepublish: no script for prepublish, continuing
12 verbose tar pack [ '/root/.npm/testdsss/1.0.5/package.tgz',
12 verbose tar pack   '/var/www/dev/js/myjs' ]
13 verbose tarball /root/.npm/testdsss/1.0.5/package.tgz
14 verbose folder /var/www/dev/js/myjs
15 verbose addLocalTarball adding from inside cache /root/.npm/testdsss/1.0.5/package.tgz
16 verbose correctMkdir /root/.npm correctMkdir not in flight; initializing
17 silly cache afterAdd testdsss@1.0.5
18 verbose afterAdd /root/.npm/testdsss/1.0.5/package/package.json not in flight; writing
19 verbose correctMkdir /root/.npm correctMkdir not in flight; initializing
20 verbose afterAdd /root/.npm/testdsss/1.0.5/package/package.json written
21 silly publish { name: 'testdsss',
21 silly publish   version: '1.0.5',
21 silly publish   description: 'test',
21 silly publish   main: 'index.js',
21 silly publish   scripts: { test: 'test' },
21 silly publish   author: { name: 'ww' },
21 silly publish   license: 'ISC',
21 silly publish   keywords: [ 'test' ],
21 silly publish   readme: 'ERROR: No README data found!',
21 silly publish   _id: 'testdsss@1.0.5',
21 silly publish   _shasum: 'b1d30607939f2f3be374f95638901dea62ca0339',
21 silly publish   _from: '.' }
22 verbose getPublishConfig undefined
23 silly mapToRegistry name testdsss
24 silly mapToRegistry using default registry
25 silly mapToRegistry registry http://192.168.5.226:8090/
26 silly mapToRegistry data Result {
26 silly mapToRegistry   raw: 'testdsss',
26 silly mapToRegistry   scope: null,
26 silly mapToRegistry   name: 'testdsss',
26 silly mapToRegistry   rawSpec: '',
26 silly mapToRegistry   spec: 'latest',
26 silly mapToRegistry   type: 'tag' }
27 silly mapToRegistry uri http://192.168.5.226:8090/testdsss
28 verbose publish registryBase http://192.168.5.226:8090/
29 silly publish uploading /root/.npm/testdsss/1.0.5/package.tgz
30 verbose request uri http://192.168.5.226:8090/testdsss
31 verbose request sending authorization for write operation
32 info attempt registry request try #1 at 10:18:01 AM
33 verbose request using bearer token for auth
34 verbose request id 2989f7af78e64f7b
35 http request PUT http://192.168.5.226:8090/testdsss
36 http 500 http://192.168.5.226:8090/testdsss
37 verbose headers { 'x-powered-by': 'Sinopia/1.4.0',
37 verbose headers   'content-type': 'application/json; charset=utf-8',
37 verbose headers   'content-length': '39',
37 verbose headers   vary: 'Accept-Encoding',
37 verbose headers   'x-status-cat': 'http://flic.kr/p/aVdo6e',
37 verbose headers   date: 'Thu, 20 Oct 2016 02:18:03 GMT',
37 verbose headers   connection: 'keep-alive' }
38 info retry will retry, error on last attempt: Error: internal server error : testdsss
39 info attempt registry request try #2 at 10:18:13 AM
40 verbose request using bearer token for auth
41 http request PUT http://192.168.5.226:8090/testdsss
42 http 409 http://192.168.5.226:8090/testdsss
43 verbose headers { 'x-powered-by': 'Sinopia/1.4.0',
43 verbose headers   'content-type': 'application/json; charset=utf-8',
43 verbose headers   'content-length': '49',
43 verbose headers   vary: 'Accept-Encoding',
43 verbose headers   'x-status-cat': 'http://flic.kr/p/aV6jzz',
43 verbose headers   date: 'Thu, 20 Oct 2016 02:18:13 GMT',
43 verbose headers   connection: 'keep-alive' }
44 verbose request invalidating /root/.npm/192.168.5.226_8090/testdsss on PUT
45 verbose request uri http://192.168.5.226:8090/testdsss?write=true
46 verbose request no auth needed
47 info attempt registry request try #1 at 10:18:13 AM
48 verbose request using bearer token for auth
49 http request GET http://192.168.5.226:8090/testdsss?write=true
50 http 200 http://192.168.5.226:8090/testdsss?write=true
51 verbose headers { 'x-powered-by': 'Sinopia/1.4.0',
51 verbose headers   'content-type': 'application/json; charset=utf-8',
51 verbose headers   etag: '"18d46d3fdd8d48396fe22f4dc476a3ee"',
51 verbose headers   'content-length': '116',
51 verbose headers   vary: 'Accept-Encoding',
51 verbose headers   'x-status-cat': 'http://flic.kr/p/aVuVsF',
51 verbose headers   date: 'Thu, 20 Oct 2016 02:18:15 GMT',
51 verbose headers   connection: 'keep-alive' }
52 verbose stack SyntaxError: Unexpected token u in JSON at position 0
52 verbose stack     at Object.parse (native)
52 verbose stack     at CachingRegistryClient.putNext (/usr/local/node-v6.2.0-linux-x64/lib/node_modules/npm/node_modules/npm-registry-client/lib/publish.js:169:20)
52 verbose stack     at /usr/local/node-v6.2.0-linux-x64/lib/node_modules/npm/node_modules/npm-registry-client/lib/publish.js:128:15
52 verbose stack     at /usr/local/node-v6.2.0-linux-x64/lib/node_modules/npm/lib/cache/caching-client.js:53:8
52 verbose stack     at f (/usr/local/node-v6.2.0-linux-x64/lib/node_modules/npm/node_modules/once/once.js:17:25)
52 verbose stack     at /usr/local/node-v6.2.0-linux-x64/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:76:16
52 verbose stack     at f (/usr/local/node-v6.2.0-linux-x64/lib/node_modules/npm/node_modules/once/once.js:17:25)
52 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/node-v6.2.0-linux-x64/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:259:12)
52 verbose stack     at Request._callback (/usr/local/node-v6.2.0-linux-x64/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
52 verbose stack     at Request.self.callback (/usr/local/node-v6.2.0-linux-x64/lib/node_modules/npm/node_modules/request/request.js:200:22)
53 verbose cwd /var/www/dev/js/myjs
54 error Linux 2.6.32-573.7.1.el6.x86_64
55 error argv "/usr/local/node-v6.2.0-linux-x64/bin/node" "/usr/local/node-v6.2.0-linux-x64/bin/npm" "publish"
56 error node v6.2.0
57 error npm  v3.8.9
58 error Unexpected token u in JSON at position 0
59 error If you need help, you may report this error at:
59 error     <https://github.com/npm/npm/issues>
60 verbose exit [ 1, true ]

**Comment by wwttyy** [comment]
npm -v prints: v3.8.9
node -v prints: v6.2.0
npm config get registry prints: http://192.168.5.226:8090/
Windows, OS X/macOS, or Linux?:   Linux

**Comment by wwttyy** [comment]
I develop using Vagrant on Windows.

**Comment by wwttyy** [comment]
I don't use a proxy, but have limited or unreliable internet access.

**Comment by zkat** [comment]
This is not a problem with the npm CLI. There's an internal error with your sinopia installation: `38 info retry will retry, error on last attempt: Error: internal server error : testdsss`.

Please check your internal logs and use that to debug what happened.

Since this isn't an npm issue, I'm gonna close it. Good luck! 👍
