### ISSUE TITLE
What causes NPM install failure

### ISSUE THREAD

**Issue by menglei0602** [npm/npm#14346]
C:\Documents and Settings\Administrator\bower_components\bootstrap>npm install
npm ERR! Windows_NT 5.1.2600
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9

npm ERR! shasum check failed for C:\DOCUME~1\ADMINI~1\LOCALS~1\Temp\npm-4716-da3
6d5ff\registry.npmjs.org\grunt-html\-\grunt-html-8.0.2.tgz
npm ERR! Expected: 886d9c170a85f90f529f320697d1847d89e3bfa0
npm ERR! Actual:   bec7cf16875fa655bf85a42098b850c6522f5cd0
npm ERR! From:     https://registry.npmjs.org/grunt-html/-/grunt-html-8.0.2.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Documents and Settings\Administrator\bower_components\bootstrap\
npm-debug.log

**Comment by KenanY** [comment]
@menglei0602 Have you tried running `npm cache clean`?

**Comment by KenanY** [comment]
Closing as abandoned.
