### ISSUE TITLE
Error: Cannot find module './internal/streams/BufferList'

### ISSUE THREAD

**Issue by reddynr** [npm/npm#14343]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [x] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [x] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by reddynr** [comment]
Iam getting below error. Please advise

Error: Cannot find module './internal/streams/BufferList'

**Comment by reddynr** [comment]
**@Vojita,**

Iam getting below error. Please advise

Error: Cannot find module './internal/streams/BufferList'

**Comment by KenanY** [comment]
@reddynr Is there a `npm-debug.log` file that you can upload to <https://gist.github.com/> and link here? What version of Node.js and `npm` are you using?

**Comment by KenanY** [comment]
Closing as abandoned.

**Comment by reddynr** [comment]
@KenanY,

Thank you so much.  I clear the cache npm and re-installed the npm problem got resolved.

**Comment by Raed2022** [comment]
Hallo @reddynr  and @KenanY , I have the same error I clear the cache npm and re-installed the npm but I got the same error 
![screenshot 52](https://user-images.githubusercontent.com/39803408/40890019-10743fb6-6770-11e8-9d47-50ff890119b0.png)

**Comment by kenany** [comment]
@Raed2022 Please open a new issue.
