### ISSUE TITLE
npm install -g bower, npm ERR!, bower     EINVALID Name must be lowercase...

### ISSUE THREAD

**Issue by poperechnyi1** [npm/npm#14340]
I have a problem. What`s happened? I would like fix this error. How?  OS Windows 10
D:\GULP\FIRST try\node_modules.bin>npm install -g bower
npm ERR! not a package D:\GULP\FIRST try\node_modules.bin\bower
npm ERR! addLocal Could not install D:\GULP\FIRST try\node_modules.bin\bower
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "bower"
npm ERR! node v4.6.0
npm ERR! npm v2.15.9
npm ERR! path C:\Users\STEPAN~1\AppData\Local\Temp\npm-224-9cb2b78b\unpack-f55148c48767\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\STEPAN~1\AppData\Local\Temp\npm-224-9cb2b78b\unpack-f55148c48767\package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR! D:\GULP\FIRST try\node_modules.bin\npm-debug.log

D:\GULP\FIRST try\node_modules.bin>bower install jquery
bower EINVALID Name must be lowercase, can contain digits, dots, dashes, "@" or spaces`

**Comment by zkat** [comment]
This looks like an error installing `bower` itself -- could you upload your `npm-debug.log` to a gist or similar?

**Comment by poperechnyi1** [comment]
Files in folder debug-log: 
index.js
Conde:
`'use strict';
// https://github.com/joyent/node/blob/fbfe562d71ae8d8f8bbf627808c755e513e4e905/lib/util.js#L96-L114
var util = require('util');
var debugEnv = process.env.NODE_DEBUG || '';
var cache = {};

module.exports = function (set) {
	set = set.toUpperCase();

	if (!cache[set]) {
		if (new RegExp('\\b' + set + '\\b', 'i').test(debugEnv)) {
			var pid = process.pid;

			cache[set] = function () {
				console.error('%s %d: %s', set, pid, util.format.apply(util, arguments));
			};
		} else {
			cache[set] = function () {};
		}
	}

	return cache[set];
};`


CODE in package.json  
`{
  "name": "debug-log",
  "version": "1.0.1",
  "description": "Node.js 0.12 util.debuglog() ponyfill",
  "license": "MIT",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/sindresorhus/debug-log.git"
  },
  "author": {
    "name": "Sindre Sorhus",
    "email": "sindresorhus@gmail.com",
    "url": "sindresorhus.com"
  },
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "test": "node test.js"
  },
  "files": [
    "index.js"
  ],
  "keywords": [
    "debug",
    "log",
    "logging",
    "debuglog",
    "built-in",
    "util",
    "utils",
    "core",
    "console",
    "env",
    "environment",
    "ponyfill",
    "polyfill",
    "shim"
  ],
  "gitHead": "7e7fcd7947b80590e39d9ff0167771536d4b355f",
  "bugs": {
    "url": "https://github.com/sindresorhus/debug-log/issues"
  },
  "homepage": "https://github.com/sindresorhus/debug-log#readme",
  "_id": "debug-log@1.0.1",
  "_shasum": "2307632d4c04382b8df8a32f70b895046d52745f",
  "_from": "debug-log@latest",
  "_npmVersion": "2.15.9",
  "_nodeVersion": "4.5.0",
  "_npmUser": {
    "name": "sindresorhus",
    "email": "sindresorhus@gmail.com"
  },
  "dist": {
    "shasum": "2307632d4c04382b8df8a32f70b895046d52745f",
    "tarball": "https://registry.npmjs.org/debug-log/-/debug-log-1.0.1.tgz"
  },
  "maintainers": [
    {
      "name": "sindresorhus",
      "email": "sindresorhus@gmail.com"
    }
  ],
  "_npmOperationalInternal": {
    "host": "packages-12-west.internal.npmjs.com",
    "tmp": "tmp/debug-log-1.0.1.tgz_1475222911607_0.4391861706972122"
  },
  "directories": {},
  "_resolved": "https://registry.npmjs.org/debug-log/-/debug-log-1.0.1.tgz"
}
`

Code in readme.md
`# debug-log [![Build Status](https://travis-ci.org/sindresorhus/debug-log.svg?branch=master)](https://travis-ci.org/sindresorhus/debug-log)

> Node.js 0.12 [`util.debuglog()`](http://nodejs.org/api/util.html#util_util_debuglog_section) [ponyfill](https://ponyfill.com)


## Install

```
$ npm install --save debug-log
```


## Usage

```js
// example.js
var debugLog = require('debug-log')('foo');

debugLog('unicorns & rainbows');
```
```
$ node example.js

```
```
$ NODE_DEBUG=foo node example.js
FOO 3245: unicorns & rainbows
```
## API

See the [`util.debuglog()` docs](http://nodejs.org/api/util.html#util_util_debuglog_section).

## License

MIT © [Sindre Sorhus](http://sindresorhus.com)
`
