### ISSUE TITLE
npm install fail on linux

### ISSUE THREAD

**Issue by grugna** [npm/npm#14355]
TypeError: Cannot read property 'latest' of undefined
    at next (/usr/local/lib/node_modules/npm/lib/cache.js:692:35)
   at /usr/local/lib/node_modules/npm/lib/cache.js:680:5
    at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:142:7)
    at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:133:7
    at Object.oncomplete (fs.js:107:15)
If you need help, you may report this *entire* log,
including the npm and node versions, at:
    <http://github.com/isaacs/npm/issues>

System Linux 2.6.18-371.8.1.el5xen
 command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
cwd /opt/TeamCity/buildAgent/work/7ee7d238625434e4/smr/client-js
node -v v0.10.25
npm -v 1.3.24
type non_object_property_load
TypeError: Cannot read property 'latest' of undefined
    at next (/usr/local/lib/node_modules/npm/lib/cache.js:692:35)
    at /usr/local/lib/node_modules/npm/lib/cache.js:680:5
    at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:142:7)
    at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:133:7
    at Object.oncomplete (fs.js:107:15)
If you need help, you may report this *entire* log,
 including the npm and node versions, at:
     <http://github.com/isaacs/npm/issues>

**Comment by KenanY** [comment]
@grugna Sorry, `npm@1.3` is years old and is no longer supported. I would suggest updating before requesting any support, since it is likely that whatever bug you are seeing has already been fixed in `npm@2` or `npm@3`.
