### ISSUE TITLE
npm install is not working

### ISSUE THREAD

**Issue by ayousha** [npm/npm#14353]
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! fetch failed http://nuget.swissre.com/api/npm/npm/webpack-dev-server/-/
webpack-dev-server-1.16.1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with statu
s code 503
npm ERR! fetch failed http://nuget.swissre.com/api/npm/npm/webpack-dev-server/-/
webpack-dev-server-1.16.1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with statu
s code 503
npm ERR! fetch failed http://nuget.swissre.com/api/npm/npm/webpack-dev-server/-/
webpack-dev-server-1.16.1.tgz
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9

**Comment by zkat** [comment]
This is an issue with the Nuget registry that you're using. Please check your configuration for your Nuget installation and see why it's erroring. Since this is not an npm CLI issue, I'm closing this. Have a good one!

**Comment by ayousha** [comment]
Thank you. I am able to run npm install.

Thanks for the help.

Ayousha
