### ISSUE TITLE
Err!  Windows_NT 6.3.9600

### ISSUE THREAD

**Issue by tecnosoftware** [npm/npm#14350]
**HELP!!!**

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova"
npm ERR! node v6.9.0
npm ERR! npm  v3.10.8

npm ERR! Callback called more than once.
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Windows\system32\npm-debug.log

**Comment by KenanY** [comment]
@tecnosoftware Hmm, could you provide the full `npm-debug.log` as a [gist](https://gist.github.com/)? Does this also occur with `npm@3.10.9`?

**Comment by tecnosoftware** [comment]
this is with con npm 3.10.8

**Comment by tecnosoftware** [comment]
@KenanY where I upload the npm-debug.log??

**Comment by KenanY** [comment]
@tecnosoftware I linked a site in my comment.

**Comment by tecnosoftware** [comment]
@KenanY ready,Thank you!!!

**Comment by KenanY** [comment]
For future reference, here's the link: https://gist.github.com/tecnosoftware/cf09849a8f22ecf2ece013c98527cf93 (since you didn't provide it)

**Comment by KenanY** [comment]
Does this also occur after a reboot? Usually `EBUSY` indicates that some other process is accessing a file that `npm` wants to access.

**Comment by KenanY** [comment]
Closing as abandoned. Can reopen if this is still an issue.
