### ISSUE TITLE
npm install seems to delete nested node_modules directories

### ISSUE THREAD

**Issue by brianpaulrue** [npm/npm#14351]
#### I'm opening this issue because:
- [x] npm is doing something I don't understand.
#### What's going wrong?

I have a complex environment, so this will likely seem like an odd way to use npm, but that is beside the point. During an npm install, directories inside top level node_modules that have their OWN node_modules seem to have their node_modules directory deleted.
#### How can the CLI team reproduce the problem?

Here's a simple step by step example:

First execute a top level `npm install` to produce the following:
- main
  - node_modules
    - npm_dep1
    - npm_dep2
  - package.json

Next, execute `npm install ../my-local-project/my-local-project-0.0.1.tgz` to produce the following:
- main
  - node_modules
    - npm_dep1
    - npm_dep2
    - my-local-project
  - package.json

my-local-project has dependencies it needs locally and separate from the parent node_modules so execute `npm install` inside main/node_modules/my-local-project to produce the following:
- main
  - node_modules
    - npm_dep1
    - npm_dep2
    - my-local-project
      - node_modules
      - package.json
  - package.json

Lastly, execute `npm install ../my-local-widgets/my-local-widgets-0.0.1.tgz` to produce the following while now finding that my-local-project's local node_modules is now deleted:
- main
  - node_modules
    - npm_dep1
    - npm_dep2
    - my-local-project                <-- node_modules is deleted
      - package.json
    - my-local-widgets
  - package.json
### supporting information:
- `npm -v` prints: 3.10.9
- `node -v` prints: v6.9.1
- `npm config get registry` prints: our privately hosted registry
- Windows, OS X/macOS, or Linux?: Windows

**Comment by S-ed** [comment]
As in npm v3 ( https://docs.npmjs.com/how-npm-works/npm3 )
```A > node_modules > B > node_modules > C```
```node_modules > C``` will be removed from **B**, if **C** exist on level above, i.e. within ```A > node_modules```
