### ISSUE TITLE
"npm ERR! missing script: test:watch" on windows 7 

### ISSUE THREAD

**Issue by mastersoftwaremedia** [npm/npm#14354]
I am trying to run "npm run test:watch" in cmd and keep getting an error.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\[username]\\AppData\\R
oaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "test:watch"
npm ERR! node v4.6.0
npm ERR! npm  v3.10.8
npm ERR! missing script: test:watch

I tried to set the path adding C:/Users/[username]/AppData/Roaming/npm; before node environment setting in c drive and no luck at all. I tried to look for similar issues posted here and no luck at all. So I had to open an issue. 

I will be very appreciated if this issue gets resolved.

[npm-debug.txt](https://github.com/npm/npm/files/542229/npm-debug.txt)

**Comment by KenanY** [comment]
@mastersoftwaremedia Do you have such a script defined in your current `package.json`?

**Comment by mastersoftwaremedia** [comment]
I am sorry for late response. Here's what I have in package.json.

{
  "name": "meteor-yelp-clone",
  "private": true,
  "scripts": {
    "start": "meteor run",
    "test": "meteor test --once --driver-package dispatch:mocha-phantomjs --port 3030",
    "test-watch": "meteor test --driver-package=practicalmeteor:mocha --port 3030"
  },
  "dependencies": {
    "meteor-node-stubs": "~0.2.0"
  }

**Comment by KenanY** [comment]
@mastersoftwaremedia Try `npm run test-watch`.

**Comment by mastersoftwaremedia** [comment]
Kenan, 
You are the best! You saved me!!! I can't thank you enough! Thank you so much.

**Comment by mastersoftwaremedia** [comment]
Kenan Yildirim,

Thank you so much for your prompt response.
I have to tell you that I am very new to node. I was busy following
instructions that was given.
Here's the snapshot of the .json file after I inserted "test" and
"test-watch" parts.

​​
Regards,
Youn
