### ISSUE TITLE
Registry returns error when publishing

### ISSUE THREAD

**Issue by marijnh** [npm/npm#14364]
#### What's going wrong?

`npm publish` hangs for a while, and then gives up with an error that seems to point at a system issue in the registry. This is the output:

```
> prosemirror-schema-list@0.12.0 prepublish /home/marijn/src/prosemirror/schema-list
> npm run build


> prosemirror-schema-list@0.12.0 build /home/marijn/src/prosemirror/schema-list
> rimraf dist && buble -i src -o dist

npm ERR! publish Failed PUT 500
npm ERR! Linux 4.4.0-1-amd64
npm ERR! argv "/home/marijn/prog/node/bin/node" "/home/marijn/prog/node/bin/npm" "publish"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! code E500

npm ERR! getaddrinfo ENOTFOUND user-acl-4-west.internal.npmjs.com user-acl-4-west.internal.npmjs.com:443 : prosemirror-schema-list
```

I've pasted npm-debug.log [here](https://gist.github.com/marijnh/52213ed8fff6eb4dd1589b58f01bd629).

#### How can the CLI team reproduce the problem?

Not sure. Publishing only seemed to trigger it for some packages, others did publish fine. The one I was trying to publish is https://github.com/prosemirror/prosemirror-schema-list (but a few others went wrong as well, and I'm not even sure the issue is package-dependent).

### supporting information:

 - `npm -v` prints: **3.10.3**

 - `node -v` prints: **v6.3.0**

 - `npm config get registry` prints: **https://registry.npmjs.org/**

 - Windows, OS X/macOS, or Linux?: **Linux**

**Comment by marijnh** [comment]
One potentially relevant fact: I successfully published 6 modules in a row before this started occurring. You're not rate-limiting publishing at such a low number, are you? (If so, please think of the multi-package-library maintainers.)

**Comment by Nuuf** [comment]
You're not alone with this error. Might be server problems.

**Comment by afoninsky** [comment]
http://status.npmjs.org/ - as usual, eveithing is ok (actually not)

**Comment by marijnh** [comment]
Publishing is working reliably again for me. Feel free to ignore or investigate this as you see fit.

**Comment by philiiiiiipp** [comment]
Hey, I am experiencing the same.

Seems like their DNS provider is currently under attack [http://status.npmjs.org/#](http://status.npmjs.org/#).
