### ISSUE TITLE
moment.js Install issue with proxy

### ISSUE THREAD

**Issue by j-r-smith** [npm/npm#14367]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [ X ] npm is producing an incorrect install.
- [ ] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
#### What's going wrong?

I am receiving the error below when trying to install moment.js. I set the proxy value in the config to the same value that my internet connection uses. Is this a fatal error or can I continue?

![10-20-2016 3-18-41 pm](https://cloud.githubusercontent.com/assets/22966265/19599129/131baefe-976d-11e6-9af8-411f6af5fac9.jpg)

Debug log:
<details><pre>
0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli   'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'moment',
1 verbose cli   '-g' ]
2 info using npm@2.15.9
3 info using node@v4.6.1
4 verbose install initial load of C:\Users\jsmith\AppData\Roaming\npm\package.json
5 verbose readDependencies loading dependencies from C:\Users\jsmith\AppData\Roaming\npm\package.json
6 silly cache add args [ 'moment', null ]
7 verbose cache add spec moment
8 silly cache add parsed spec Result {
8 silly cache add   raw: 'moment',
8 silly cache add   scope: null,
8 silly cache add   name: 'moment',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: 'latest',
8 silly cache add   type: 'tag' }
9 silly addNamed moment@latest
10 verbose addNamed "latest" is being treated as a dist-tag for moment
11 info addNameTag [ 'moment', 'latest' ]
12 silly mapToRegistry name moment
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry data Result {
15 silly mapToRegistry   raw: 'moment',
15 silly mapToRegistry   scope: null,
15 silly mapToRegistry   name: 'moment',
15 silly mapToRegistry   rawSpec: '',
15 silly mapToRegistry   spec: 'latest',
15 silly mapToRegistry   type: 'tag' }
16 silly mapToRegistry uri https://registry.npmjs.org/moment
17 verbose addNameTag registry:https://registry.npmjs.org/moment not in flight; fetching
18 verbose request uri https://registry.npmjs.org/moment
19 verbose request no auth needed
20 info attempt registry request try #1 at 3:06:03 PM
21 verbose request id 6a423d3001d0b551
22 http request GET https://registry.npmjs.org/moment
23 info retry will retry, error on last attempt: Error: read ECONNRESET
24 info attempt registry request try #2 at 3:06:13 PM
25 http request GET https://registry.npmjs.org/moment
26 info retry will retry, error on last attempt: Error: read ECONNRESET
27 info attempt registry request try #3 at 3:07:13 PM
28 http request GET https://registry.npmjs.org/moment
29 verbose stack Error: read ECONNRESET
29 verbose stack     at exports._errnoException (util.js:907:11)
29 verbose stack     at TLSWrap.onread (net.js:557:26)
30 verbose cwd C:\Users\jsmith
31 error Windows_NT 6.1.7601
32 error argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "moment" "-g"
33 error node v4.6.1
34 error npm  v2.15.9
35 error code ECONNRESET
36 error errno ECONNRESET
37 error syscall read
38 error network read ECONNRESET
38 error network This is most likely not a problem with npm itself
38 error network and is related to network connectivity.
38 error network In most cases you are behind a proxy or have bad network settings.
38 error network
38 error network If you are behind a proxy, please make sure that the
38 error network 'proxy' config is set properly.  See: 'npm help config'
39 verbose exit [ 1, true ]
</pre></details>

### supporting information:
- `npm -v` prints:
- `node -v` prints:
- `npm config get registry` prints:
- Windows, OS X/macOS, or Linux?:
- Network issues:
  - Geographic location where npm was run:
  - [ ] I use a proxy to connect to the npm registry.
  - [ ] I use a proxy to connect to the web.
  - [ ] I use a proxy when downloading Git repos.
  - [ ] I access the npm registry via a VPN
  - [ ] I don't use a proxy, but have limited or unreliable internet access.
- Container:
  - [ ] I develop using Vagrant on Windows.
  - [ ] I develop using Vagrant on OS X or Linux.
  - [ ] I develop / deploy using Docker.
  - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by watilde** [comment]
Hi. It seems to be duplicated issue to https://github.com/npm/npm/issues/12484, and https://github.com/npm/registry/issues/10. Also, you are using the old version `npm@2.15.9`. Can you try to use the latest version? This docs helps you to install the latest stable version of npm: https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm

Thanks.
