### ISSUE TITLE
some package's package.json is missing in tarball (after published)

### ISSUE THREAD

**Issue by jihchi** [npm/npm#14376]
#### I'm opening this issue because:
- [x] npm is producing an incorrect install.
#### What's going wrong?

Expect that installation will succeed.

P.S. If you remove `react-router` package from `package.json`, then installation will works as normal.
#### How can the CLI team reproduce the problem?

``` sh
$ git clone https://github.com/jihchi/create-react-app.git
$ cd create-react-app
$ git checkout failure
$ cd packages/react-scripts
$ npm install
$ vi package.json 
// change the "name" (for example: react-scripts-jihchi)
// save & exit
$ npm publish
$ cd /tmp
$ mdir my-app
$ cd my-app
$ npm install react-scripts-jihchi
/private/tmp/my-app
└── (empty)

npm WARN enoent ENOENT: no such file or directory, open '/private/tmp/my-app/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/qv/c7vh78t56s17p93nnd3qvzhc0000gn/T/npm-42520-9e09ba0a/unpack-3e40421f/node_modules/hoek/package.json'
...
```

npm-debug.log:
https://gist.github.com/jihchi/fbd99996ba883cda8d69a88db429e76c
### supporting information:
- `npm -v` prints: `3.10.8`
- `node -v` prints: `v6.7.0`
- `npm config get registry` prints: `https://registry.npmjs.org/`
- Windows, OS X/macOS, or Linux?: `macOS`

**Comment by jihchi** [comment]
That's weird ...

Why `hoek`'s `package.json` is missing after `npm pack`/`npm publish`?

**Comment by jihchi** [comment]
I found that it'll works by removing `bundledDependencies`from `package.json`

**Comment by legodude17** [comment]
That is very odd. I know that @othiym23 was investigating something similar awhile back but that seemed like it was solved.

**Comment by jihchi** [comment]
I had added following code at [utils/tar.js](https://github.com/npm/npm/blob/latest/lib/utils/tar.js#L203):

```
...
.on('entry', function (entry) {
     console.log(entry);
})
...
```

I saw `hoek/package.json` from `console.log` while executing `npm pack`, but it didn't packed in tarball file.

**Comment by jihchi** [comment]
Workaround: Execute `npm dedupe` before publish

**Comment by legodude17** [comment]
Yeah. @othiym23 might be able to help.
