### ISSUE TITLE
npm3: shrinkwrap no longer throws an error if no node_modules are installed

### ISSUE THREAD

**Issue by m59peacemaker** [npm/npm#14377]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [ ] npm is producing an incorrect install.
- [ ] npm is doing something I don't understand.
- [x] Other (_see below for feature requests_):
#### What's going wrong?

In npm < 3, `rm -r node_modules; npm shrinkwrap` would produce an error when `package.json` contains dependencies, because `node_modules` is empty/missing. With npm 3, the shrinkwrap succeeds, producing an invalid manifest. This is contrary to the [docs on this matter](https://docs.npmjs.com/cli/shrinkwrap#other-notes). However, as it should be, `npm shrinkwrap` will fail if at least one package is installed and at least one is missing.
#### How can the CLI team reproduce the problem?

mkdir my-project
cd my-project
npm init -y
npm install --save try_catch
rm -r node_modules # remove node_modules directory OR empty node_modules directory
npm shrinkwrap # this should fail, but succeeds, producing an invalid shrinkwrap manifest
### supporting information:
- `npm -v` prints: 3.8.3
- `node -v` prints: v5.10.1
- `npm config get registry` prints: https://registry.npmjs.org/
- Windows, OS X/macOS, or Linux?: Linux

**Comment by evocateur** [comment]
I can confirm this still happens with `npm` v3.10.9, just to rule out the significant changes in the shrinkwrap area since v3.8.3. The resulting `npm-shrinkwrap.json` is very peculiar:

```
{
  "name": "my-project",
  "version": "1.0.0"
}
```
