### ISSUE TITLE
Dependencies with transitive peerDependencies in conflict resolve incorrectly and silently

### ISSUE THREAD

**Issue by jvivs** [npm/npm#14370]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [x] npm is producing an incorrect install.
- [ ] npm is doing something I don't understand.
- [x] Other (_see below for feature requests_):
#### What's going wrong?

Transitive dependencies with a peerDependency in conflict can get the wrong version. More verbose description on the [repo](https://github.com/jvivs/npm-peer-dependency-bug) itself... happy to update issue w/ full text if that's helpful/desired.
#### How can the CLI team reproduce the problem?

Clone this [repo](https://github.com/jvivs/npm-peer-dependency-bug), run `npm install` in `package`, and then load up the `package` module in the repl. Note how only one version of `peer` is listed. Then confirm in the file system that `transitive-with-peer` is not installed alongside the desired version of `peer`.
### supporting information:
- `npm -v` prints:

```
$ npm -v
3.10.3
```
- `node -v` prints:

```
$ node -v
v6.7.0
```
- `npm config get registry` prints:
  $ npm config get registry
  `http://artifactory.<internal-registry-host>/artifactory/api/npm/npm-composite` that reads through to npm's official registry
- Windows, OS X/macOS, or Linux?:
  OS X
- Network issues:
  - Geographic location where npm was run:
  - [ ] I use a proxy to connect to the npm registry.
  - [ ] I use a proxy to connect to the web.
  - [ ] I use a proxy when downloading Git repos.
  - [ ] I access the npm registry via a VPN
  - [ ] I don't use a proxy, but have limited or unreliable internet access.
- Container:
  - [ ] I develop using Vagrant on Windows.
  - [ ] I develop using Vagrant on OS X or Linux.
  - [ ] I develop / deploy using Docker.
  - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by iarna** [comment]
I had to patch your example to make it installable with any version of npm. (`file://../dirname/` had to change to `file:../dirname/` or `../dirname`).

What I see is:

```console
$ npm -v
4.0.0
$ npm install
package@1.0.0 /Users/rebecca/code/npmtest/14370/npm-peer-dependency-bug/package
├── peer@2.0.0 
├── primary-with-peer@1.0.0 
└─┬ primary-with-transitive-peer@1.0.0 
  ├── UNMET PEER DEPENDENCY peer@1.0.0
  └── transitive-with-peer@1.0.0 

npm WARN transitive-with-peer@1.0.0 requires a peer of peer@file:../peer but none was installed.
npm WARN package@1.0.0 No description
npm WARN package@1.0.0 No repository field.
$ npm ls
package@1.0.0 /Users/rebecca/code/npmtest/14370/npm-peer-dependency-bug/package
├── peer@2.0.0
├── primary-with-peer@1.0.0
└─┬ primary-with-transitive-peer@1.0.0
  ├── UNMET PEER DEPENDENCY peer@1.0.0
  └── transitive-with-peer@1.0.0

npm ERR! peer dep missing: peer@file:../peer, required by transitive-with-peer@1.0.0
```

For completeness, I tried it again with `v3.10.3` and got exactly the same results as above.

I don't see anything wrong with what's happening there. What were you expecting it to do that it didn't?

**Comment by iarna** [comment]
Ok, so there's _something_ weird going on, because `primary-with-transitive-peer` depends on peer@1 and isn't getting a copy of it.

**Comment by iarna** [comment]
Oor it is, but `npm ls` is eliding it, grr.

**Comment by iarna** [comment]
Ok for the record, the actual physical-on-disk tree that npm@3 is making is:

```
package@1.0.0 /Users/rebecca/code/npmtest/14370/npm-peer-dependency-bug/package
├── peer@2.0.0
├── primary-with-peer@1.0.0
├─┬ primary-with-transitive-peer@1.0.0
│ └── peer@1.0.0
└── transitive-with-peer@1.0.0
```

`transitive-with-peer` is a dependency of `primary-with-transitive-peer` and has a peerDependency on `peer@1.0.0`. 

`primary-with-transitive-peer` tries to provide that peer, but flattening ignores it and dumps it to the top level.

Fixing this will mean making `earliestInstallable` in `lib/install/deps.js` return if any of the module's peer deps are resolved by that level of the tree. See the conflicting binary checker for an example of that.

**Comment by jvivs** [comment]
@iarna thank you for taking a look so quickly! Good catch on the file paths. Looks like I munged them when I went to change the paths from absolute to relative.

I've updated the issue and example repository with a better description of how to replicate as well as fixed the relative file paths.

I was pretty confused when I first encountered this issue, so I'm glad you're seeing what I'm seeing!

Please let me know if there's any additional information required.
