### ISSUE TITLE
npmjs.org redirecting to insecure https://www.npmjs.com ?

### ISSUE THREAD

**Issue by Jakobud** [npm/npm#14378]
#### I'm opening this issue because:

  - [ X ] Other (_see below for feature requests_):

#### What's going wrong?

I'm attempting to search for modules on npmjs.org, but tonight I'm getting redirected to https://www.npmjs.com and it looks like the SSL cert is bad or unsigned or something.

**Comment by KenanY** [comment]
@Jakobud In the browser, or in the `npm` CLI?

**Comment by Jakobud** [comment]
In the browser. Looks like the insecure certificate issue is gone today. Not sure what the problem was yesterday. Maybe something to do with the whole Dyn hack yesterday.
