### ISSUE TITLE
npm ERR! code ENOTEMPTY errno -39

### ISSUE THREAD

**Issue by DirkRay** [npm/npm#14397]
I use `sudo npm install --unsafe-perm --verbose -g ethereumjs-testrpc` to install testrpc and truffle,but there is a error I can't solve.
Anyone can help me?

npm verb lifecycle scrypt@6.0.3~preinstall: unsafe-perm in lifecycle true
npm verb lifecycle scrypt@6.0.3~preinstall: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/ray/.npm-global/lib/node_modules/.staging/scrypt-795b0e09/node_modules/.bin:/home/ray/.npm-global/lib/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
npm verb lifecycle scrypt@6.0.3~preinstall: CWD: /home/ray/.npm-global/lib/node_modules/.staging/scrypt-795b0e09
npm verb unlock done using /home/ray/.npm/_locks/staging-c0c0f61750a98b47.lock for /home/ray/.npm-global/lib/node_modules/.staging
npm verb stack Error: ENOTEMPTY: directory not empty, rename '/home/ray/.npm-global/lib/node_modules/ethereumjs-testrpc' -> '/home/ray/.npm-global/lib/node_modules/.ethereumjs-testrpc.DELETE'
npm verb stack at moveAway (/usr/lib/node_modules/npm/lib/install/action/finalize.js:38:5)
npm verb stack at destStatted (/usr/lib/node_modules/npm/lib/install/action/finalize.js:27:7)
npm verb stack at FSReqWrap.oncomplete (fs.js:123:15)
npm verb stack 
npm verb stack Error: ENOTEMPTY: directory not empty, rename '/home/ray/.npm-global/lib/node_modules/ethereumjs-testrpc' -> '/home/ray/.npm-global/lib/node_modules/.ethereumjs-testrpc.DELETE'
npm verb stack at Error (native)
npm verb cwd /home/ray
npm ERR! Linux 3.13.0-86-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--unsafe-perm" "--verbose" "-g" "ethereumjs-testrpc"
npm ERR! node v6.9.1
npm ERR! npm v3.10.8
npm ERR! path /home/ray/.npm-global/lib/node_modules/ethereumjs-testrpc
npm ERR! code ENOTEMPTY
npm ERR! errno -39
npm ERR! syscall rename

npm ERR! ENOTEMPTY: directory not empty, rename '/home/ray/.npm-global/lib/node_modules/ethereumjs-testrpc' -> '/home/ray/.npm-global/lib/node_modules/.ethereumjs-testrpc.DELETE'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR! https://github.com/npm/npm/issues
npm verb exit [ -39, true ]

npm ERR! Please include the following file with any support request:
npm ERR! /home/ray/npm-debug.log

**Comment by watilde** [comment]
Hello! You are catching a wrong cache by an accident(it may be a bug). A quick fix way is removing the `*.DELETE` directories from your `node_modules`, or removing the `node_modules` itself and trying again:

```
rm -rf /home/ray/.npm-global/lib/node_modules/*.DELETE
npm install
```
or
```
rm -rf /home/ray/.npm-global/lib/node_modules/
npm install
```
Thanks.
