### ISSUE TITLE
angular-cli installation error

### ISSUE THREAD

**Issue by cmb97** [npm/npm#14395]
#### I'm opening this issue because:

there are lots of errors when I install angular-cli
#### Here are the errors

![error](https://cloud.githubusercontent.com/assets/23022303/19636129/e61af740-99f9-11e6-96a2-16f672f9505e.png)

**Comment by watilde** [comment]
Hi! The error seems to be related to registry. Can you clear your cache by `npm cache clean` and try again?

**Comment by cmb97** [comment]
@watilde actually I already tried it but I receive the same error

**Comment by legodude17** [comment]
Are you behind a proxy or a VPN?

**Comment by cmb97** [comment]
@legodude17 can you explain it to me sir? I'm a beginner of this :) thanks :)
