### ISSUE TITLE
npm install appium failed:errno -5,unexpected end of file

### ISSUE THREAD

**Issue by wanwan001** [npm/npm#14394]
When I am reinstalling the appium, the terminal reports the error as followes: 

```
wanwandeMac:npm wanwan$ npm install -g appium
npm ERR! tar.unpack unzip error /var/folders/tf/89068tvn199bhwpk5r3hg03h0000gn/T/npm-3970-7391db21/registry.npmjs.org/appium-adb/-/appium-adb-2.6.17.tgz
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/6.9.1/bin/node" "/usr/local/bin/npm" "install" "-g" "appium"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.9
npm ERR! code Z_BUF_ERROR
npm ERR! errno -5

npm ERR! unexpected end of file
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/wanwan/npm/npm-debug.log
```

I have tried to solve this problem by searching the internet, but it just not being solved by the method provided. Hoping for some help, thank you very much!

**Comment by watilde** [comment]
Hi! I think it's reported an issue on https://github.com/npm/npm/issues/11993. Can you try `npm cache clean` and install again?

**Comment by wanwan001** [comment]
@watildeOK，I will have a try, thank you.

**Comment by rajshah** [comment]
npm install -g appium is working after npm cache clean. Thank you! I suppose issue might be due to post upgrade of node and npm versions. I am using brew and I did upgrade on brew, node and npm before installing appium without cleaning cache.

**Comment by grrowl** [comment]
For future reference: Node 8.9.0+ (and 9+) fix an issue where streams are terminated early in some scenarios. If you're getting this error upgrade to 8.9.

https://github.com/nodejs/node/issues/13391
