### ISSUE TITLE
When I run the react-native init AwesomeProject, there is a problem, how should I solve

### ISSUE THREAD

**Issue by wangyueqi** [npm/npm#14393]
wangyueqideMBP:~ wangyueqi$ react-native init AwesomeProject
prompt: Directory AwesomeProject already exists. Continue?:  (no) yes
This will walk you through creating a new React Native project in /Users/wangyueqi/AwesomeProject
Installing react-native package from npm...

npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "--save-exact" "react-native"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8

npm ERR! shasum check failed for /var/folders/jb/bg7xg4zs5z7dvwl99614wtzr0000gp/T/npm-27798-dcc97454/registry.npmjs.org/react-native/-/react-native-0.35.0.tgz
npm ERR! Expected: 59a53e80109a728a7f6c7c9f0f0899c8b14c13b2
npm ERR! Actual:   19e45e4b3978a8a1dee7be10930d13a5df3a95b9
npm ERR! From:     https://registry.npmjs.org/react-native/-/react-native-0.35.0.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/wangyueqi/AwesomeProject/npm-debug.log

`npm install --save --save-exact react-native` failed

**Comment by wangyueqi** [comment]
` NPM install, —save  —save-exact react-native ` failed, how should I handle

**Comment by ZFKK** [comment]
I have the same question,please help!

**Comment by maibeiying** [comment]
I have the same question too,please help!

**Comment by ZFKK** [comment]
someone think that we shoul add 'sudo' before that operation ,but it does not work!!!...

**Comment by KenanY** [comment]
How about `npm cache clean`?

**Comment by KenanY** [comment]
Closing as abandoned.

**Comment by ZFKK** [comment]
maybe something is wrong with the network,when i use a better network,it works!??

**Comment by KenanY** [comment]
@ZFKK Perhaps your network is modifying packages mid-flight, hence the shasum mismatches?
