### ISSUE TITLE
npm search - JavaScript heap out of memory

### ISSUE THREAD

**Issue by stephenmathieson** [npm/npm#14404]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

npm is using too much memory and crashing node.

#### How can the CLI team reproduce the problem?

Don't have an `npm-debug.log` since node crashed, but here's all of the output: https://gist.github.com/stephenmathieson/90e6fd04c3e51573738bb67956022e89

Just doing `npm search slugify` seems to reliably cause this problem.

### supporting information:

 - `npm -v` prints: 3.10.3
 - `node -v` prints: v6.3.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS
 - Network issues:
   - Geographic location where npm was run: SF
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
Already fixed by https://github.com/npm/npm/pull/13746 in `npm@4.0.0` :)

**Comment by stephenmathieson** [comment]
ah nice! thanks
