### ISSUE TITLE
NPM START NOT WORKING

### ISSUE THREAD

**Issue by kiiru501** [npm/npm#14405]
Hi, 
I am unable to run command **npm start** for my angular project.First of, whenever i run any npm command , I keep getting this.

![pin](https://cloud.githubusercontent.com/assets/4168690/19670196/fc63055a-9a6d-11e6-84e3-411dd21b8403.PNG)

When i run **npm start** i get this error.
![pin2](https://cloud.githubusercontent.com/assets/4168690/19670504/63f51166-9a70-11e6-9f0c-d947d3c05697.PNG)

Here is my npm-debug.log

**0 info it worked if it ends with ok
1 verbose cli [ 'D:\Program Files\nodejs\node.exe',
1 verbose cli   'D:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle angular-quickstart@1.0.0~prestart: angular-quickstart@1.0.0
6 silly lifecycle angular-quickstart@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle angular-quickstart@1.0.0~start: angular-quickstart@1.0.0
8 verbose lifecycle angular-quickstart@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle angular-quickstart@1.0.0~start: PATH: D:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;D:\Users\Joseph Kiiru\Desktop\angular-quickstart\node_modules.bin;D:\ProgramData\Oracle\Java\javapath;D:\Users\Joseph Kiiru\AppData\Local\Programs\Python\Python35-32;D:\windows\system32 ;D:\Windows\system32\config\systemprofile.dnx\bin;D:\Program Files\Microsoft DNX\Dnvm\;D:\Program Files\Microsoft SQL Server\120\Tools\Binn\;D:\Program Files\Microsoft SQL Server\130\Tools\Binn\;D:\Program Files\nodejs\;D:\Windows\system32;D:\Program Files (x86)\Microsoft VS Code\bin;D:\Program Files\Git\bin;D:\Users\Joseph Kiiru\AppData\Roaming\npm
10 verbose lifecycle angular-quickstart@1.0.0~start: CWD: D:\Users\Joseph Kiiru\Desktop\angular-quickstart
11 silly lifecycle angular-quickstart@1.0.0~start: Args: [ '/d /s /c', 'concurrently "tsc -w" "lite-server" ' ]
12 info lifecycle angular-quickstart@1.0.0~start: Failed to exec start script
13 verbose stack Error: angular-quickstart@1.0.0 start: `concurrently "tsc -w" "lite-server"`
13 verbose stack spawn D:\Windows\system32  ENOENT
13 verbose stack     at exports._errnoException (util.js:1026:11)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
13 verbose stack     at onErrorNT (internal/child_process.js:359:16)
13 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:74:11)
13 verbose stack     at process._tickCallback (internal/process/next_tick.js:98:9)
14 verbose pkgid angular-quickstart@1.0.0
15 verbose cwd D:\Users\Joseph Kiiru\Desktop\angular-quickstart
16 error Windows_NT 6.1.7601
17 error argv "D:\Program Files\nodejs\node.exe" "D:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "start"
18 error node v6.9.1
19 error npm  v3.10.8
20 error file D:\Windows\system32
21 error path D:\Windows\system32
22 error code ELIFECYCLE
23 error errno ENOENT
24 error syscall spawn D:\Windows\system32
25 error angular-quickstart@1.0.0 start: `concurrently "tsc -w" "lite-server"`
25 error spawn D:\Windows\system32  ENOENT
26 error Failed at the angular-quickstart@1.0.0 start script 'concurrently "tsc -w" "lite-server" '.
26 error Make sure you have the latest version of node.js and npm installed.
26 error If you do, this is most likely a problem with the angular-quickstart package,
26 error not with npm itself.
26 error Tell the author that this fails on your system:
26 error     concurrently "tsc -w" "lite-server"
26 error You can get information on how to open an issue for this project with:
26 error     npm bugs angular-quickstart
26 error Or if that isn't available, you can get their info via:
26 error     npm owner ls angular-quickstart
26 error There is likely additional logging output above.
27 verbose exit [ 1, true ]**

Please help. I've been stuck here for days

**Comment by snopeks** [comment]
Hello @kiiru501 , in this case you'll have to get in touch with the author of angular-quickstart, they've got some issues with their postinstall script. You can find their email by running `npm owner ls angular-quickstart`. Thanks!

**Comment by kiiru501** [comment]
I already contacted them before I raised my issue here. They said that there was no problem on their side. It's not only on angular-quickstart that am having the Problem. Anything npm related. Please see the error on npm --version that i have shared above. Thanks

**Comment by kiiru501** [comment]
Here is the error that occurs when i run **npm install**

![pin3](https://cloud.githubusercontent.com/assets/4168690/19713206/c816103c-9b4c-11e6-9dad-ed3bff1ffeab.PNG)

**Comment by kiiru501** [comment]
i can still install typings using **npm install typings -g**
But the circled 
![pin4](https://cloud.githubusercontent.com/assets/4168690/19713234/fc71418a-9b4c-11e6-928d-556008b1c906.PNG)
error is still there

**Comment by kiiru501** [comment]
@KenanY hi. Please help me with this error. Been stuck here for weeks now. Thanks

**Comment by KenanY** [comment]
@kiiru501 Not really sure what's going on here :(

**Comment by kiiru501** [comment]
@iarna hi. Please help me out with this issue. I've been stuck here for weeks. Thanks
