### ISSUE TITLE
`.bashrc` exports in terminal title

### ISSUE THREAD

**Issue by ariutta** [npm/npm#14401]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [ ] npm is producing an incorrect install.
- [x] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
#### What's going wrong?

In Terminal.app Version 2.7 (377), `npm run <MY_SCRIPT_NAME>` displays exports from `.bashrc` in the Terminal title, as illustrated for `DUMMY_KEY` below:

![npm-export-title-bug](https://cloud.githubusercontent.com/assets/1296771/19663027/df74a716-99ee-11e6-95f4-d98da157bca5.png)

This is undesirable, because these could be private API keys.
#### How can the CLI team reproduce the problem?

In `~/.bashrc`, add the line `export DUMMY_KEY=nkvjaSDJKVLnsD21l3rn2j`.

Create a new npm project that has this script entry:

``` json
{
  "scripts": {
    "hello": "echo hello && sleep 10 && echo bye"
  }
}
```

Run that script: `npm run hello`.

During the `sleep 10` section, you should be able to see `DUMMY_KEY` in the title. This happens for any long-running command.
### supporting information:
- `npm -v` prints: `3.10.6`
- `node -v` prints: `v6.8.1`
- `npm config get registry` prints: `https://registry.npmjs.org/`
- Windows, OS X/macOS, or Linux?: `macOS Sierra Version 10.12 (16A323)`

There was no npm-debug.log generated.

I have tried the following:
- Disable [`powerline`](https://github.com/powerline/powerline): no change
- Just run `echo hello && sleep 10 && echo bye` (not using `npm`): keys not shown

**Comment by iarna** [comment]
FWIW this happens with Terminal 2.6.1 too, with every version of npm and as best as I can tell every version of Node.js.

It _does not_ do this with this rough reproduction of how npm runs lifecycles:

```
var spawn = require('child_process').spawn
spawn('sh', ['-c', 'echo hello && sleep 10 && echo bye'], {stdio: [0,1,2]})
  .on('error', console.error)
  .on('data', function () { console.log('complete') })
```

**Comment by iarna** [comment]
Also FWIW it doesn't happen in iTerm2.

This seems to be related to Terminal's "display command arguments in titlebar feature" but I'm at a loss for how we're making it go haywire.

You can get rid of this display by going to:

Preferences→Profiles→Window

And unchecking "Arguments" which is in the title section just below "Active process name".
