### ISSUE TITLE
Handlebars install issue  Using Node version 4.6.0  NPM version 1.4.8

### ISSUE THREAD

**Issue by arshi-mustafa786** [npm/npm#14416]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\nodejs\node.exe',
1 verbose cli   'C:\npm\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'handlebars',
1 verbose cli   '–g' ]
2 info using npm@1.4.8
3 info using node@v4.6.0
4 verbose cache add [ 'handlebars', null ]
5 verbose cache add name=undefined spec="handlebars" args=["handlebars",null]
6 verbose parsed url Url {
6 verbose parsed url   protocol: null,
6 verbose parsed url   slashes: null,
6 verbose parsed url   auth: null,
6 verbose parsed url   host: null,
6 verbose parsed url   port: null,
6 verbose parsed url   hostname: null,
6 verbose parsed url   hash: null,
6 verbose parsed url   search: null,
6 verbose parsed url   query: null,
6 verbose parsed url   pathname: 'handlebars',
6 verbose parsed url   path: 'handlebars',
6 verbose parsed url   href: 'handlebars' }
7 verbose cache add [ '–g', null ]
8 verbose cache add name=undefined spec="–g" args=["–g",null]
9 verbose parsed url Url {
9 verbose parsed url   protocol: null,
9 verbose parsed url   slashes: null,
9 verbose parsed url   auth: null,
9 verbose parsed url   host: null,
9 verbose parsed url   port: null,
9 verbose parsed url   hostname: null,
9 verbose parsed url   hash: null,
9 verbose parsed url   search: null,
9 verbose parsed url   query: null,
9 verbose parsed url   pathname: '–g',
9 verbose parsed url   path: '–g',
9 verbose parsed url   href: '–g' }
10 silly lockFile 51e00793-g –g
11 verbose lock –g C:\Users\AM71634\AppData\Roaming\npm-cache\51e00793-g.lock
12 silly lockFile 9566e355-handlebars handlebars
13 verbose lock handlebars C:\Users\AM71634\AppData\Roaming\npm-cache\9566e355-handlebars.lock
14 silly lockFile 51e00793-g –g
15 silly lockFile 51e00793-g –g
16 silly lockFile 9566e355-handlebars handlebars
17 silly lockFile 9566e355-handlebars handlebars
18 verbose addNamed [ '–g', '' ]
19 verbose addNamed [ null, '_' ]
20 verbose addNamed [ 'handlebars', '' ]
21 verbose addNamed [ null, '_' ]
22 silly lockFile 72e0e7f9-g –g@
23 verbose lock –g@ C:\Users\AM71634\AppData\Roaming\npm-cache\72e0e7f9-g.lock
24 silly lockFile 0ab5732f-handlebars handlebars@
25 verbose lock handlebars@ C:\Users\AM71634\AppData\Roaming\npm-cache\0ab5732f-handlebars.lock
26 silly addNameRange { name: '–g', range: '_', hasData: false }
27 silly addNameRange { name: 'handlebars', range: '_', hasData: false }
28 verbose url raw –g
29 verbose url resolving [ 'https://registry.npmjs.org/', './%E2%80%93g' ]
30 verbose url resolved https://registry.npmjs.org/%E2%80%93g
31 info trying registry request attempt 1 at 11:08:45 AM
32 http GET https://registry.npmjs.org/%E2%80%93g
33 error TypeError: Request path contains unescaped characters.
33 error     at new ClientRequest (_http_client.js:50:11)
33 error     at TunnelingAgent.exports.request (http.js:31:10)
33 error     at TunnelingAgent.createSocket (C:\npm\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:117:25)
33 error     at TunnelingAgent.createSecureSocket [as createSocket](C:npmnode_modulesnpmnode_modulesrequestnode_modulestunnel-agentindex.js:184:41)
33 error     at TunnelingAgent.addRequest (C:\npm\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:80:8)
33 error     at new ClientRequest (_http_client.js:142:16)
33 error     at Object.exports.request (http.js:31:10)
33 error     at Object.socket.once.exports.request (https.js:182:15)
33 error     at Request.start (C:\npm\node_modules\npm\node_modules\request\request.js:583:30)
33 error     at Request.end (C:\npm\node_modules\npm\node_modules\request\request.js:1237:28)
34 error If you need help, you may report this _entire_ log,
34 error including the npm and node versions, at:
34 error     http://github.com/npm/npm/issues
35 error System Windows_NT 6.1.7601
36 error command "C:\nodejs\node.exe" "C:\npm\node_modules\npm\bin\npm-cli.js" "install" "handlebars" "–g"
37 error cwd C:\Users\AM71634
38 error node -v v4.6.0
39 error npm -v 1.4.8
40 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@arshi-mustafa786 Looks like in your command, you are using a [hyphen-minus](https://en.wikipedia.org/wiki/Hyphen-minus) instead of a regular hyphen. I'm sure if you fix that then this will work properly. Also note that `npm@1` is quite old and since then I'm pretty sure a better error message for this specific problem has been implemented.

**Comment by arshi-mustafa786** [comment]
Hi KenanY .. I tried using regular hyphen also. Seems the issue is persisting. Please help

**Comment by KenanY** [comment]
@arshi-mustafa786 Please provide a `npm-debug.log` of the error you are getting.

**Comment by KenanY** [comment]
(also, ensure that you are using at least `npm@2`, since `npm@1` is quite old at this point)

**Comment by KenanY** [comment]
Closing as abandoned.
