### ISSUE TITLE
npm 4.0.1 tries to install public deps from private registry in scoped package

### ISSUE THREAD

**Issue by jvdl** [npm/npm#14412]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [ ] npm is producing an incorrect install.
- [x] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
#### What's going wrong?

`npm install` fails on scoped packages that are registered with a private registry that only hosts the privately scoped packages. e.g. our registry will host `@myscope/foobar` and so it will get pulled down from there, however a package called `foobar` without the scope should be retrieved from the public registry.

Note that this works fine on npm 3.10.x but with npm 4.0.x it fails with `code E404`
#### How can the CLI team reproduce the problem?
1. Use a private registry for a given scope
   `npm login --registry=https://my-private.registry.io --scope=myscope`
2. Use said scope for a package, e.g. `"name": "@myscope/my-package"` in package.json
3. Have a dependency that is not a scoped dep, let's say `chalk` in your package.json
4. `npm install`

Note that this will also happen when attempting to install a package directly, e.g. `npm install gulp` will give me the same error as it attempts to fetch the package from the private repository.

See [gist of anonymised npm-debug.log and .npmrc](https://gist.github.com/jvdl/33bed5c1b821a897b166569690346981)

In a nutshell: 

```
20 silly mapToRegistry name chalk
21 silly mapToRegistry scope (from config) @myscope
22 silly mapToRegistry registry https://my-private.registry.io/
23 silly mapToRegistry data Result {
23 silly mapToRegistry   raw: 'chalk',
23 silly mapToRegistry   scope: null,
23 silly mapToRegistry   escapedName: 'chalk',
23 silly mapToRegistry   name: 'chalk',
23 silly mapToRegistry   rawSpec: '',
23 silly mapToRegistry   spec: 'latest',
23 silly mapToRegistry   type: 'tag' }
24 silly mapToRegistry uri https://my-private.registry.io/chalk
...
55 verbose request uri https://my-private.registry.io/chalk
56 verbose request no auth needed
57 info attempt registry request try #1 at 8:56:01 AM
58 verbose request using bearer token for auth
59 verbose request id 197b471b5ae07454
60 http request GET https://my-private.registry.io/chalk
...
86 http 404 https://my-private.registry.io/chalk
87 verbose headers { 'cache-control': 'must-revalidate',
87 verbose headers   'content-type': 'application/json',
87 verbose headers   date: 'Tue, 25 Oct 2016 21:56:03 GMT',
87 verbose headers   server: 'CouchDB/1.6.1 (Erlang OTP/R16B03)',
87 verbose headers   'x-powered-by': 'Express',
87 verbose headers   'content-length': '52',
87 verbose headers   connection: 'keep-alive' }
88 silly get cb [ 404,
88 silly get   { 'cache-control': 'must-revalidate',
88 silly get     'content-type': 'application/json',
88 silly get     date: 'Tue, 25 Oct 2016 21:56:03 GMT',
88 silly get     server: 'CouchDB/1.6.1 (Erlang OTP/R16B03)',
88 silly get     'x-powered-by': 'Express',
88 silly get     'content-length': '52',
88 silly get     connection: 'keep-alive' } ]
89 silly fetchPackageMetaData Error: 404 Not Found: chalk
```
### supporting information:
- `npm -v` prints: 4.0.1
- `node -v` prints: v6.9.0
- `npm config get registry` prints: https://registry.npmjs.org/
- Windows, OS X/macOS, or Linux?: OS X
- Network issues:
  - Geographic location where npm was run:
  - [ ] I use a proxy to connect to the npm registry.
  - [x] I use a proxy to connect to the web. _(probably, if it's important I can find out more definitively, but I don't think proxies are playing a part in this problem)_
  - [ ] I use a proxy when downloading Git repos.
  - [ ] I access the npm registry via a VPN
  - [ ] I don't use a proxy, but have limited or unreliable internet access.
- Container:
  - [ ] I develop using Vagrant on Windows.
  - [ ] I develop using Vagrant on OS X or Linux.
  - [ ] I develop / deploy using Docker.
  - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by zkat** [comment]
This was probably caused by https://github.com/npm/npm/pull/14129. Thanks for reporting this! We'll probably get this fixed before letting `npm@4` become `latest` :)
