### ISSUE TITLE
npm prune --production error 

### ISSUE THREAD

**Issue by SenthilSivaganesh** [npm/npm#14417]
#### I'm opening this issue because:

see the following log while deploying in Jenkins

[ Deploy Info ] : Creating a temporary workspace in "/tmp/nodejs-temp/workingdir/ct-market-tci/d"
---
## npm prune --production

npm ERR! Error: ENOENT, open '/tmp/nodejs-temp/workingdir/ct-market-tci/d/tls-app-1.0.0/package.json'
npm ERR! If you need help, you may report this _entire_ log,
npm ERR! including the npm and node versions, at:
npm ERR!     http://github.com/npm/npm/issues

npm ERR! System Linux 2.6.32-431.el6.x86_64
npm ERR! command "/usr/local/node-v0.10.33-linux-x64/bin/node" "/usr/local/node-v0.10.33-linux-x64/bin/npm" "prune" "--production"
npm ERR! cwd /tmp/nodejs-temp/workingdir/ct-market-tci/d/tls-app-1.0.0
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! path /tmp/nodejs-temp/workingdir/ct-market-tci/d/tls-app-1.0.0/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /tmp/nodejs-temp/workingdir/ct-market-tci/d/tls-app-1.0.0/npm-debug.log
npm ERR! not ok code 0

[ ERROR ] Error executing the command: npm prune --production
- [ ] npm is crashing.
- [ ] npm is producing an incorrect install.
- [ ] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
### supporting information:
- `npm -v` prints:
- `node -v` prints:
- `npm config get registry` prints:
- Windows, OS X/macOS, or Linux?:
- Network issues:
  - Geographic location where npm was run:
  - [ ] I use a proxy to connect to the npm registry.
  - [ ] I use a proxy to connect to the web.
  - [ ] I use a proxy when downloading Git repos.
  - [ ] I access the npm registry via a VPN
  - [ ] I don't use a proxy, but have limited or unreliable internet access.
- Container:
  - [ ] I develop using Vagrant on Windows.
  - [ ] I develop using Vagrant on OS X or Linux.
  - [ ] I develop / deploy using Docker.
  - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@SenthilSivaganesh Does this also occur with newer versions of `npm`? `npm@1` is quite old now.

**Comment by SenthilSivaganesh** [comment]
@KenanY  Yes it does , please find below the latest logs

-------------------------------------------------------
npm prune --production
-------------------------------------------------------


npm ERR! Linux 2.6.32-431.el6.x86_64
npm ERR! argv "/usr/local/node-v4.2.4-linux-x64/bin/node" "/usr/local/node-v4.2.4-linux-x64/bin/npm" "prune" "--production"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
npm ERR! path /tmp/nodejs-temp/workingdir/ct-market-tci/e/tls-app-1.0.0/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/tmp/nodejs-temp/workingdir/ct-market-tci/e/tls-app-1.0.0/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/nodejs-temp/workingdir/ct-market-tci/e/tls-app-1.0.0/npm-debug.log


[ ERROR ] Error executing the command: npm prune --production


Build step 'Execute shell' marked build as failure
Finished: FAILURE

**Comment by KenanY** [comment]
@SenthilSivaganesh Hmm, there should be a `package.json` in your current directory (`/tmp/nodejs-temp/workingdir/ct-market-tci/e/tls-app-1.0.0/`) before you execute `npm prune`, I believe. Could you verify that it exists, or justify why you are running `npm prune` without a `package.json` in your current directory?

**Comment by KenanY** [comment]
Closing as abandoned.
