### ISSUE TITLE
'Target' null

### ISSUE THREAD

**Issue by alexdahlmandrm** [npm/npm#14410]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [X] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
    npm install <any package>
    npm ERR! Linux 4.4.0-21-generic
    npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
    npm ERR! node v4.2.6
    npm ERR! npm  v3.5.2

    npm ERR! Cannot read property 'target' of null
    npm ERR! 
    npm ERR! If you need help, you may report this error at:
    npm ERR!     <https://github.com/npm/npm/issues>

    npm ERR! Please include the following file with any support request:
    npm ERR!     /var/www/html/fcrm/docroot/sites/all/libraries/remodal/npm-debug.log
Trying to grunt my Remodal jquery plugin in drupal 7.
#### How can the CLI team reproduce the problem?

https://gist.github.com/alexdahlmandrm/e26074807bc4d70dd9b769a336e73178
 Error Log-->  https://gist.github.com/alexdahlmandrm/6eb1bb65b2b5a1f06bca89c2be63eb4f
-->

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?: Linux Mint 18
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by watilde** [comment]
Hi, thanks for reporting this issue! This issue has been fixed by https://github.com/npm/npm/pull/13999, and it's shipped as v3.10.9. You seem to be using `v3.5.2` according to your `npm-debug.log`. Could you try the latest version of the npm?

See also:
https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm

**Comment by snopeks** [comment]
hi @alexdahlmandrm , @watilde is right that it is fixed as of npm@3.8.3 (the PR is https://github.com/npm/npm/pull/11947 :) ), so updating your npm version should resolve this issue. Let us know if you need any further help!
