### ISSUE TITLE
Error during npm install gulp

### ISSUE THREAD

**Issue by HarshKrishna** [npm/npm#14423]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [ ] npm is producing an incorrect install.
- [x] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
### supporting information:
- `npm -v` prints:
- `node -v` prints:
- `npm config get registry` prints:
- Windows, OS X/macOS, or Linux?:
- Network issues:
  - Geographic location where npm was run:
  - [ ] I use a proxy to connect to the npm registry.
  - [x] I use a proxy to connect to the web.
  - [ ] I use a proxy when downloading Git repos.
  - [ ] I access the npm registry via a VPN
  - [ ] I don't use a proxy, but have limited or unreliable internet access.
- Container:
  - [ ] I develop using Vagrant on Windows.
  - [ ] I develop using Vagrant on OS X or Linux.
  - [ ] I develop / deploy using Docker.
  - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by HarshKrishna** [comment]
Facing the following issue while npm install gulp.

![capture](https://cloud.githubusercontent.com/assets/20298578/19722573/f3086888-9b94-11e6-9b6a-1d956d116aa2.JPG)

**Comment by HarshKrishna** [comment]
Adding the log file: 
[npm-debug.log.txt](https://github.com/npm/npm/files/552991/npm-debug.log.txt)

**Comment by snopeks** [comment]
Hi @HarshKrishna ! You're running into a proxy config issue, we recommend speaking with your sysadmin about configuring SSL support for the proxy correctly. If you have more questions, you can reach out to us at support@npmjs.com!
