### ISSUE TITLE
error in install Ghost on Node.js 7

### ISSUE THREAD

**Issue by jourjine** [npm/npm#14427]
just install node.js and have little big problem

```
$ sudo npm install --production
npm ERR! Linux 4.4.19-29.55.amzn1.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--production"
npm ERR! node v7.0.0
npm ERR! npm  v4.0.1

npm ERR! Cannot read property 'deep-extend' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 4.4.19-29.55.amzn1.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--production"
npm ERR! node v7.0.0
npm ERR! npm  v4.0.1

npm ERR! Cannot read property 'extsprintf' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/ghost/npm-debug.log

```

**Comment by zkat** [comment]
This is a strange issue and I'm not sure it's a bug with npm itself, but maybe something is up with `npm@4.0.1` -- so could you upload your `npm-debug.log` to a gist or similar so we can take a look? :)

**Comment by jourjine** [comment]
hi
i change node.js to version 4.6.0 but have same error:

```
sudo npm install --production
npm ERR! Linux 4.4.19-29.55.amzn1.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--production"
npm ERR! node v4.6.1
npm ERR! npm  v4.0.1

npm ERR! Cannot read property 'deep-extend' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 4.4.19-29.55.amzn1.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--production"
npm ERR! node v4.6.1
npm ERR! npm  v4.0.1

npm ERR! Cannot read property 'extsprintf' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/ghost/npm-debug.log

```

[gist](https://gist.github.com/jourjine/59d9a4e6896ffb73dfe90d96180998ff)

**Comment by jourjine** [comment]
Hi again!
i`m downgrade npm to version 3.10.9 and ghost installed!

PS
my system just created and installed only node + 2 mods + npm

**Comment by zkat** [comment]
@jourjine Thanks a lot for the `npm-debug.log`! I appreciate a lot that you're willing to give `npm@next` a shot and help find stuff like this. It's increeeedibly helpful to us.

This seems like a bug with some `npm@4` changes to shrinkwrap. It seems -to me- that something funky might be happening with that specific shrinkwrap, but we shouldn't be crashing like this either way. Pinging @iarna too. :)

**Comment by SpainTrain** [comment]
I can corroborate this issue

```
$ npm i
npm WARN deprecated webpack-combine-loaders@2.0.2: bad
npm ERR! Linux 4.4.0-45-generic
npm ERR! argv "/home/spainhower/npm/n/bin/node" "/home/spainhower/npm/bin/npm" "i"
npm ERR! node v6.9.1
npm ERR! npm  v4.0.2

npm ERR! Cannot read property 'deep-extend' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 4.4.0-45-generic
npm ERR! argv "/home/spainhower/npm/n/bin/node" "/home/spainhower/npm/bin/npm" "i"
npm ERR! node v6.9.1
npm ERR! npm  v4.0.2

npm ERR! Cannot read property 'lodash._baseslice' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 4.4.0-45-generic
npm ERR! argv "/home/spainhower/npm/n/bin/node" "/home/spainhower/npm/bin/npm" "i"
npm ERR! node v6.9.1
npm ERR! npm  v4.0.2

npm ERR! Cannot read property 'lodash._baseslice' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 4.4.0-45-generic
npm ERR! argv "/home/spainhower/npm/n/bin/node" "/home/spainhower/npm/bin/npm" "i"
npm ERR! node v6.9.1
npm ERR! npm  v4.0.2

npm ERR! Cannot read property 'lodash._baseslice' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 4.4.0-45-generic
npm ERR! argv "/home/spainhower/npm/n/bin/node" "/home/spainhower/npm/bin/npm" "i"
npm ERR! node v6.9.1
npm ERR! npm  v4.0.2

npm ERR! Cannot read property 'extsprintf' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

[npm-debug.log](https://gist.github.com/SpainTrain/ae6e2f5dff80f825777940ca1f2b76bf)

**Comment by legodude17** [comment]
@SpainTrain, have you tried reinstalling `npm`?

**Comment by buley** [comment]
@legodude17 ran into this issue installing `npm@4` today (`v4.0.2`). 

I'm doing shrinkwrap on a OS X then shipping to a Linux environment. using 4 was the resolution proposed by https://github.com/npm/npm/issues/14042

I'm stuck because downgraded `npm@3.10.8-9` (per @jourjine) doesn't have a fix for #14042

**Comment by zkat** [comment]
This is a bug. Reinstalling `npm` won't fix it. It'll be fixed soon, since I've already diagnosed it out.

@buley: `npm@3.10.10` is out, with a fix for #14042

**Comment by iarna** [comment]
Clearing the milestone while we work on getting a consistent repro for this.

**Comment by zkat** [comment]
(if anyone is able to get a consistent, isolated test case for this, please let us know!)

**Comment by OgreMHDW** [comment]
I am having the same issue on a Windows Server. It does not appear any log file was written. Does anyone have any ideas or workaround?

`C:\Program Files (x86)\Parsoid>npm install
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mweiss\\AppData\
\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v7.1.0
npm ERR! npm  v4.0.2

npm ERR! Cannot read property 'debug' of undefined
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mweiss\\AppData\
\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v7.1.0
npm ERR! npm  v4.0.2

npm ERR! Cannot read property 'lodash._baseslice' of undefined
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mweiss\\AppData\
\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v7.1.0
npm ERR! npm  v4.0.2

npm ERR! Cannot read property 'lodash._baseslice' of undefined
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mweiss\\AppData\
\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v7.1.0
npm ERR! npm  v4.0.2

npm ERR! Cannot read property 'lodash._baseslice' of undefined
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mweiss\\AppData\
\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v7.1.0
npm ERR! npm  v4.0.2

npm ERR! Cannot read property 'extsprintf' of undefined
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Program Files (x86)\Parsoid\npm-debug.log

C:\Program Files (x86)\Parsoid>npm install --production
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mweiss\\AppData\
\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production"
npm ERR! node v7.1.0
npm ERR! npm  v4.0.2

npm ERR! Cannot read property 'debug' of undefined
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mweiss\\AppData\
\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production"
npm ERR! node v7.1.0
npm ERR! npm  v4.0.2

npm ERR! Cannot read property 'lodash._baseslice' of undefined
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mweiss\\AppData\
\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production"
npm ERR! node v7.1.0
npm ERR! npm  v4.0.2

npm ERR! Cannot read property 'lodash._baseslice' of undefined
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mweiss\\AppData\
\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production"
npm ERR! node v7.1.0
npm ERR! npm  v4.0.2

npm ERR! Cannot read property 'lodash._baseslice' of undefined
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mweiss\\AppData\
\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production"
npm ERR! node v7.1.0
npm ERR! npm  v4.0.2

npm ERR! Cannot read property 'extsprintf' of undefined
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Program Files (x86)\Parsoid\npm-debug.log

C:\Program Files (x86)\Parsoid>`

**Comment by legodude17** [comment]
You might want to completely reinstall `npm`, it looks like the
installation is busted. :/

**Comment by e-cloud** [comment]
try this repo
i have the similar error with
node v6.9.1
npm 4.0.2

**Comment by MichaelJAndy** [comment]
Seems similar, managed to fix it with a downgrade from npm 4 to 3
https://github.com/npm/npm/issues/14660#issuecomment-261597360

**Comment by gmbr3** [comment]
This needs to be milestoned.

**Comment by mchikhaoui** [comment]
reinstalling npm 3.10.8 solve the problem for me. ghost installed !
npm install npm@3.10.8 -g

**Comment by legodude17** [comment]
Anyone still have this issue?

**Comment by zkat** [comment]
Fixed as of `npm@4.0.5`, which can be installed with `npm install -g npm@4.0.5`.

**Comment by gmbr3** [comment]
Add to https://github.com/npm/npm/milestone/96

**Comment by farhatnawaz** [comment]
Hi there. While trying to update the npm, I get this error. I was first trying to work with npm 3 install the dependency but that raised the similar problem.

<img width="571" alt="screen shot 2016-12-06 at 1 46 53 am" src="https://cloud.githubusercontent.com/assets/8686962/20901815/1ebcdaf0-bb56-11e6-8097-a3bbae46cd29.png">

Here are the contents of the log file: 

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'npm@4.0.5' ]
2 info using npm@3.10.9
3 info using node@v7.2.0
4 verbose stack Error: Cannot find module 'internal/fs'
4 verbose stack     at Function.Module._resolveFilename (module.js:470:15)
4 verbose stack     at Function.Module._load (module.js:418:25)
4 verbose stack     at Module.require (module.js:498:17)
4 verbose stack     at require (internal/module.js:20:19)
4 verbose stack     at evalmachine.<anonymous>:17:20
4 verbose stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/cmd-shim/node_modules/graceful-fs/fs.js:11:1)
4 verbose stack     at Module._compile (module.js:571:32)
4 verbose stack     at Object.Module._extensions..js (module.js:580:10)
4 verbose stack     at Module.load (module.js:488:32)
4 verbose stack     at tryModuleLoad (module.js:447:12)
5 verbose cwd /Users/farhatnawaz/Freelancing/Projects/Sandjai/master
6 error Darwin 16.0.0
7 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "npm@4.0.5"
8 error node v7.2.0
9 error npm  v3.10.9
10 error code MODULE_NOT_FOUND
11 error Cannot find module 'internal/fs'
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]
```
Does anyone have a fix?

**Comment by zkat** [comment]
@gmbr3 we generally don't milestone issues themselves. It happens once in a blue moon but it's not part of our usual process.

**Comment by legodude17** [comment]
Try installing npm from somewhere else, like the node installer.

**Comment by ImanMh** [comment]
I have the same issue, downgrading to 3.18.0 did not helped. I just lost my blog installation during the update.

**Comment by Charlotteis** [comment]
@ImanMh did you update to the latest version of npm?

`npm install -g npm@latest`

**Comment by ImanMh** [comment]
No I didn't how ever I tried to do ```npm install``` instead of ```npm install --production``` and it solved my problem. I'm confused!

**Comment by Jabark** [comment]
I had this issue on 4.0.3, upgraded to 4.0.5 and issue was fixed.

**Comment by ManukumarNM** [comment]
I had the same issue with my current npm version I updated with sudo npm install -g npm@latest. This problem was fixed.
