### ISSUE TITLE
npm install problem during proxy ..

### ISSUE THREAD

**Issue by lstraka91** [npm/npm#14422]
Please help me I don´t know what I am doing wrong... I would like to start learning angular 2 in the leisure time at the company. But I have a big problem to run someting by npm install ...It allways throw me error about behing the proxy.. I set proxy, but always the same problem ..I attach my error log file and here is the .npmrc : 
_registry=https://registry.npmjs.org
strict-ssl=false
always-auth=false
proxy=http://proxy.COMPANY:3128
https-proxy=http://proxy.COMPANY:3128_

Any suggestion ? 
[npm-debug.txt](https://github.com/npm/npm/files/552900/npm-debug.txt)

**Comment by snopeks** [comment]
Hello @lstraka91 , it looks like you are either missing authentication or the proxy is not accepting the auth. The 407 error is saying the proxy is not accepting the current authentication. We recommend speaking with your sysadmin to get this proxy authenticated correctly.
