### ISSUE TITLE
npm can't install mysql on Windows 

### ISSUE THREAD

**Issue by rnol** [npm/npm#14425]
I got this error when install mysql, could anyone help? Many thanks!
![npm](https://cloud.githubusercontent.com/assets/22725243/19723076/379c33b4-9bac-11e6-8a9a-0deec0b8103d.jpg)

**Comment by snopeks** [comment]
Hey @rnol , it looks like this is a corrupted cache issue, could you try running `npm cache clean` and try installing again?

**Comment by talentAN** [comment]
I just met the same error as @rnol while install mysql on MaxOS, I tried your method @snopeks but it doesn't work.

**Comment by talentAN** [comment]
problem solved by installing IOS file in other route. for people in China like me, could use this:
‘npm config set registry https://registry.npm.taobao.org’
then you could install mysql @snopeks @rnol
