### ISSUE TITLE
Got Cannot find module 'internal/fs'

### ISSUE THREAD

**Issue by manisenkov** [npm/npm#14438]
#### I'm opening this issue because:
- [x] npm is crashing.
- [ ] npm is producing an incorrect install.
- [x] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
#### What's going wrong?

I use `n` version manager to handle multiple node versions on my machine (OS X El Capitan 10.11.6). I installed last version of node (7.0.0) with `n latest` and `npm` in this version doesn't work for me.
However, v6.9.1 of node works perfectly.
#### How can the CLI team reproduce the problem?

``` bash
$ n 7.0.0

     install : node-v7.0.0
       mkdir : /Users/manisenkov/.n/n/versions/node/7.0.0
       fetch : https://nodejs.org/dist/v7.0.0/node-v7.0.0-darwin-x64.tar.gz
######################################################################## 100.0%
   installed : v7.0.0

$ which node
/Users/manisenkov/.n/bin/node
$ node --version
v7.0.0
$ which npm
/Users/manisenkov/.n/bin/npm
$ npm --version
3.10.8
$ npm i babel-cli  # babel-cli is just for example here, this happens for all packages
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/manisenkov/.n/bin/node" "/Users/manisenkov/.n/bin/npm" "i" "babel-cli"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'internal/fs'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/manisenkov/npm-debug.log
<!--
    Please a complete description of how to reproduce the problem.
    Include a gist of your npm-debug.log file.
    If you've never used gist.github.com, start here:
      https://github.com/EmmaRamirez/how-to-submit-your-npm-debug-log
-->

### supporting information:

 - `npm -v` prints:
3.10.8
 - `node -v` prints:
7.0.0
 - `npm config get registry` prints:
https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?:
OS X El Capitan 10.11.6
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).
```

**Comment by legodude17** [comment]
This is probably due to the fact that Node v7 made it so that you cannot revaluate `fs`. This may cause this if that version of `npm` was using an old `graceful-fs`.

**Comment by lunaticlegion** [comment]
I'm getting the same error running a gulp file:

Error: Cannot find module 'internal/fs'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at evalmachine.<anonymous>:17:20
    at Object.<anonymous> (/Users/warren/Documents/Work/site/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)

**Comment by song940** [comment]
```log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'i' ]
2 info using npm@3.10.8
3 info using node@v7.0.0
4 verbose stack Error: Cannot find module 'internal/fs'
4 verbose stack     at Function.Module._resolveFilename (module.js:472:15)
4 verbose stack     at Function.Module._load (module.js:420:25)
4 verbose stack     at Module.require (module.js:500:17)
4 verbose stack     at require (internal/module.js:20:19)
4 verbose stack     at evalmachine.<anonymous>:17:20
4 verbose stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/cmd-shim/node_modules/graceful-fs/fs.js:11:1)
4 verbose stack     at Module._compile (module.js:573:32)
4 verbose stack     at Object.Module._extensions..js (module.js:582:10)
4 verbose stack     at Module.load (module.js:490:32)
4 verbose stack     at tryModuleLoad (module.js:449:12)
5 verbose cwd /Users/Lsong/Projects/canary
6 error Darwin 16.1.0
7 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "i"
8 error node v7.0.0
9 error npm  v3.10.8
10 error code MODULE_NOT_FOUND
11 error Cannot find module 'internal/fs'
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]
```

**Comment by legodude17** [comment]
Make sure to update `npm` to `npm@4` when using Node v7.

**Comment by manisenkov** [comment]
@legodude17 yes, but node 7.0.0 ships with npm 3.10.8 by default :)

**Comment by legodude17** [comment]
Yes, I am still not sure that that is a problem with `npm` because I am under the impression that `npm` fixed that a long time ago. Can you try it with `npm@4`?

**Comment by manisenkov** [comment]
ok, this become even more interesting:

```bash
$ ~/.n/bin/npm i decimal
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/manisenkov/.n/bin/node" "/Users/manisenkov/.n/bin/npm" "i" "decimal"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'internal/fs'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/manisenkov/testnpm/npm-debug.log
$ ~/.n/n/versions/node/7.0.0/bin/npm i decimal
/Users/manisenkov/testnpm
└── decimal@0.0.2
# ... strip rest of output, it doesn't matter
```

@legodude17 I can't update npm to npm@4 directly, because `npm i -g npm@4` got me the same error :)
however, given the thing that I get below, I did
```bash
$ ~/.n/n/versions/node/7.0.0/bin/npm i -g npm@4
```
and now everything works :)

**Comment by legodude17** [comment]
That's good. So can this be closed? Are you still have the problem after this fix @lunaticlegion or @song940?

**Comment by manisenkov** [comment]
@legodude17 for me - yes. I think it just some weird thing happens in `n` itself, so I should probably address this bug to its maintainers.

**Comment by lunaticlegion** [comment]
I think my issue may be more related to gulp using an outdated version of graceful-fs. I've been following up on that. Thanks for your time @legodude17

**Comment by legodude17** [comment]
What about you @song940?

**Comment by song940** [comment]
@legodude17 Everything went well when i upgrade to `npm@4`

**Comment by alecxe** [comment]
We've got a related issue: http://stackoverflow.com/questions/40308623/cannot-find-module-internal-fs-afer-upgrading-to-node-7. We had npm 4, but that did not help. Only downgrading to 6.9.0 helped to workaround the problem..

**Comment by legodude17** [comment]
That seems like an issue with the `grunt-bower-concat` package, not with `npm`.

**Comment by chemzqm** [comment]
Same issue with node 7.0.0, downgrade node to 6.9.0 solved that problem.

**Comment by alex88** [comment]
Same thing with npm version 4.0.1 and graceful-fs version 4.1.9, both latest

**Comment by legodude17** [comment]
@chemzqm, that is because node 7.0.0 was the version that introduced that change. @alex88, you should file an issue with `graceful-fs` and then see what's up.

**Comment by alex88** [comment]
I've cleared my node_modules folder, used `npm-check-updates` and everything worked

**Comment by legodude17** [comment]
Ok that is good. Any progress @chemzqm?

**Comment by chemzqm** [comment]
@legodude17 everything works when I use node 6.9.0, I'm fine with that.  webpack 1.x have depends on old version of graceful-fs, and I don't want to upgrade webpack for all of my modules.

**Comment by legodude17** [comment]
Ok, so this can be closed then? Can you do that @KenanY?

**Comment by KenanY** [comment]
Sure thing :)

**Comment by ldong** [comment]
Try `npm install npm@latest -g` or `npm install npm@4 -g`

**Comment by koalabi** [comment]
Doesn't work for me under Ubuntu 16.04LTS (npm refuses to start)

**Comment by suburbanantihero** [comment]
I ran into this issue on El Capitan after installing node 7.0.0.  Previously, I had node 6.9.0.

I resolved the issue by deleting the /usr/local/lib/node_modules/npm folder and then reinstalled node 7.0.0 from the pkg installer.  

My assumption is that something from the previous version of npm doesn't get cleaned out properly.

**Comment by longchiwen** [comment]
I had the same issue. Uninstalling node (v6.9.0), manually deleting node_modules and installing node v7.0.0 resolved it.

**Comment by guicouto** [comment]
@longchiwen I did as you said, remove all node_module, update npm@4 and node v7.0.0, than, I install all dependencies again. This way works for me.

**Comment by toby1991** [comment]
yarn will help u

**Comment by alejoduque** [comment]
Nada, the proposed fix doesn't work under Debian Jessie:
After removing the modules I do:

`npm install npm@4 -g
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
- retry@0.10.0 node_modules/npm/node_modules/npm-registry-client/node_modules/retry
- core-util-is@1.0.2 node_modules/npm/node_modules/request/node_modules/bl/node_modules/readable-stream/node_modules/core-util-is
- isarray@1.0.0 node_modules/npm/node_modules/request/node_modules/bl/node_modules/readable-stream/node_modules/isarray
- process-nextick-args@1.0.7 node_modules/npm/node_modules/request/node_modules/bl/node_modules/readable-stream/node_modules/process-nextick-args
- string_decoder@0.10.31 node_modules/npm/node_modules/request/node_modules/bl/node_modules/readable-stream/node_modules/string_decoder
- util-deprecate@1.0.2 node_modules/npm/node_modules/request/node_modules/bl/node_modules/readable-stream/node_modules/util-deprecate
- readable-stream@2.0.6 node_modules/npm/node_modules/request/node_modules/bl/node_modules/readable-stream
- bl@1.1.2 node_modules/npm/node_modules/request/node_modules/bl
/usr/local/lib
└─┬ npm@4.0.2 
  ├── glob@7.1.1 
  ├── graceful-fs@4.1.10 
  ├── inflight@1.0.6 
  ├─┬ JSONStream@1.2.1 
  │ ├── jsonparse@1.2.0 
  │ └── through@2.3.8 
  ├─┬ mississippi@1.2.0 
  │ ├─┬ concat-stream@1.5.2 
  │ │ ├─┬ readable-stream@2.0.6 
  │ │ │ ├── core-util-is@1.0.2 
  │ │ │ ├── isarray@1.0.0 
  │ │ │ ├── process-nextick-args@1.0.7 
  │ │ │ ├── string_decoder@0.10.31 
  │ │ │ └── util-deprecate@1.0.2 
  │ │ └── typedarray@0.0.6 
  │ ├─┬ duplexify@3.4.5 
  │ │ ├─┬ end-of-stream@1.0.0 
  │ │ │ └── once@1.3.3 
  │ │ └── stream-shift@1.0.0 
  │ ├─┬ end-of-stream@1.1.0 
  │ │ └── once@1.3.3 
  │ ├── flush-write-stream@1.0.0 
  │ ├── from2@2.3.0 
  │ ├── pump@1.0.1 
  │ ├── pumpify@1.3.5 
  │ ├── stream-each@1.1.2 
  │ └─┬ through2@2.0.1 
  │   ├─┬ readable-stream@2.0.6 
  │   │ ├── core-util-is@1.0.2 
  │   │ ├── isarray@1.0.0 
  │   │ ├── process-nextick-args@1.0.7 
  │   │ ├── string_decoder@0.10.31 
  │   │ └── util-deprecate@1.0.2 
  │   └── xtend@4.0.1 
  ├─┬ node-gyp@3.4.0
  │ └─┬ npmlog@3.1.2
  │   └─┬ gauge@2.6.0
  │     └── signal-exit@3.0.1 
  ├─┬ npm-registry-client@7.3.0 
  │ └─┬ npmlog@3.1.2
  │   └─┬ gauge@2.6.0
  │     ├── signal-exit@3.0.1 
  │     └─┬ string-width@1.0.2
  │       ├─┬ code-point-at@1.0.1 
  │       │ └── number-is-nan@1.0.1 
  │       └─┬ is-fullwidth-code-point@1.0.0
  │         └── number-is-nan@1.0.1 
  ├─┬ npmlog@4.0.0
  │ └─┬ gauge@2.6.0
  │   └── signal-exit@3.0.1 
  ├─┬ request@2.78.0 
  │ ├── aws4@1.5.0 
  │ ├── form-data@2.1.1 
  │ ├── qs@6.3.0 
  │ └─┬ tough-cookie@2.3.2 
  │   └── punycode@1.4.1 
  └─┬ sorted-union-stream@2.1.3 
    ├─┬ from2@1.3.0 
    │ └─┬ readable-stream@1.1.14 
    │   ├── core-util-is@1.0.2 
    │   ├── isarray@0.0.1 
    │   └── string_decoder@0.10.31 
    └── stream-iterate@1.1.1 
`

And Still get the error when trying to launch Etherpad-lite:


`su -c "/var/www/etherpad-lite/bin/run.sh" -s /bin/bash etherpad
Ensure that all dependencies are up to date...  If this is the first time you have run Etherpad please be patient.
Ensure jQuery is downloaded and up to date...
Clearing minified cache...
Ensure custom css/js files are created...
Started Etherpad...
module.js:474
    throw err;
    ^

Error: Cannot find module 'internal/fs'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at evalmachine.<anonymous>:17:20
    at Object.<anonymous> (/var/www/etherpad-lite/src/node_modules/npm/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
`



This are the actual versions running on the system:

npm -v
4.0.2
node -v
v7.0.0


Advice very much appreciated. I have tried all sort of combinations for 2 days.... pffff!

**Comment by legodude17** [comment]
That is a problem with etherpad, not `npm`.

**Comment by alejoduque** [comment]
oh thanks legodude17, i though it was npm related since there are only reports that lead to this very same thread.. will try with other versions of etherpad-lite

**Comment by Kiryusha** [comment]
I had the same issue on win 7 with node 7.0.0.
Helped to remove and install latest gulp in project

**Comment by Somebi** [comment]
Same issue with v7.1.0. Problem still persist. This thread should be opened.

**Comment by bparanj** [comment]
npm install webpack -g fails on Mac 10.9.5. I am getting:

```
Error: Cannot find module 'internal/fs'
```

I am on v7.2.1.

**Comment by rikriki** [comment]
@bparanj try this
Go to folder where npm globally installed(in my case it is in /usr/local/lib/node_modules/npm)
try to update 'graceful-fs' to the latest version using sudo npm install graceful-fs@4.1.10 --save

**Comment by SiliticX** [comment]
@rikriki Sadly didn't work.

I'm banging my head against the wall here.

**Comment by rikriki** [comment]
@SiliticX Are you running npm install when you encounter this problem? What npm and node version are you at?

**Comment by ChiWhiteSox56** [comment]
Thanks to everyone who contributed to this thread. 

This is the error that I was getting:
https://gist.github.com/ChiWhiteSox56/a40daccf2d76bfc5e60e387c3c51a04e

The following steps fixed it and I was able to do successfully do a global install of Appium:
npm install -g gulp
npm install npm@4 -g
nvm install 6.9.4 (I was on 7.0.3)

**Comment by anandlokhande** [comment]
Faced the same issue while running the command : npm install gulp-cli -g
In my case the npm PATH was incorrect. It was pointing to the "C:\Users\{FirstName LastName}\AppData\Roaming\npm" forlder for user  : "FirstName LastName" 
 at Object.<anonymous> (C:\Users\FirstName LastName\AppData\Roaming\npm\node_modu
les\npm\node_modules\graceful-fs\fs.js:11:1).

I corrected that to the my user : "FirstName.LastName"
changed it to  : "C:\Users\{FirstName.LastName}\AppData\Roaming\npm"
And npm commands worked smoothly.

**Comment by Rockfordal** [comment]
i had success after removing my node_modules folder

**Comment by mcshakes** [comment]
I was also getting this error after the install:

`npm install nodemon -g `

Everything seems successful. Then I run `nodemon app.js` within my working directory and get this error:

    ```
exception in nodemon killing node
    Error: Cannot find module 'internal/fs'
        at Function.Module._resolveFilename (module.js:470:15)
        at Function.Module._load (module.js:418:25)
        at Module.require (module.js:498:17)
        at require (internal/module.js:20:19)
        at evalmachine.<anonymous>:18:20
        at Object.<anonymous> (/Users/edmac/.node/lib/node_modules/nodemon/node_modules/update-notifier/node_modules/configstore/node_modules/graceful-fs/fs.js:11:1)
        at Module._compile (module.js:571:32)
        at Object.Module._extensions..js (module.js:580:10)
        at Module.load (module.js:488:32)
        at tryModuleLoad (module.js:447:12)
```
_What I tried at first:_

Uninstalling node completely and reinstalling to an earlier version of node (6.9 I believe, as I started out at 7.6)

1) deleting the /usr/local/lib/node_modules/npm folder
2) Uninstalling node completely
3) Reinstalled versions of node and npm to something other users said was working.
 
 ```
   $ node -v
    v7.0.0
     01:27 PM   ~
    $ npm -v
    3.10.8
```
Still received the error.

**What finally worked**

1) Deleting all old nodes and npm related things
I followed this excellent guide:
https://gist.github.com/TonyMtz/d75101d9bdf764c890ef

2) I installed NVM 
https://keymetrics.io/2015/02/03/installing-node-js-and-io-js-with-nvm/

3) `nvm install stable`

Got me the latest versions and I installed nodemon. Everything working now.
