### ISSUE TITLE
ENOENT: no such file or directory, open (webpack 1.13.3)

### ISSUE THREAD

**Issue by AveVlad** [npm/npm#14437]
#### I'm opening this issue because:
- [x] Other (_see below for feature requests_):
#### What's going wrong?

```
npm WARN deprecated autoprefixer-loader@3.2.0: Please use postcss-loader instead of autoprefixer-loader
npm WARN deprecated babel-plugin-react-remove-prop-types@3.0.0: Use babel-plugin-transform-react-remove-prop-types instead
npm ERR! Linux 3.13.0-100-generic
npm ERR! argv "/opt/circleci/nodejs/v6.9.1/bin/node" "/opt/circleci/nodejs/v6.9.1/bin/npm" "install"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code EREADFILE

npm ERR! Error extracting /home/ubuntu/.npm/webpack/1.13.2/package.tgz archive: ENOENT: no such file or directory, open '/home/ubuntu/.npm/webpack/1.13.2/package.tgz'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/frontend-desktop/npm-debug.log

npm install returned exit code 1

Action failed: npm install
```
#### How can the CLI team reproduce the problem?

build on https://circleci.com/

![image](https://cloud.githubusercontent.com/assets/2889662/19760701/82853d32-9c3b-11e6-8887-62f42fe9a408.png)
### supporting information:
- `npm -v` prints:
- `node -v` prints:
- `npm config get registry` prints:
- Windows, OS X/macOS, or Linux?:
- Network issues:
  - Geographic location where npm was run:
  - [ ] I use a proxy to connect to the npm registry.
  - [ ] I use a proxy to connect to the web.
  - [ ] I use a proxy when downloading Git repos.
  - [ ] I access the npm registry via a VPN
  - [ ] I don't use a proxy, but have limited or unreliable internet access.
- Container:
  - [ ] I develop using Vagrant on Windows.
  - [ ] I develop using Vagrant on OS X or Linux.
  - [x] I develop / deploy using Docker.
  - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kmamykin** [comment]
I have exactly the same issue in semaphoreci server.

```
Semaphore: ~/asiago-react-client/host $ npm -v
4.0.1
```
^^ I just updated npm on the ci server, but the same issue was on the latest npm v3.xx

```
Semaphore: ~/asiago-react-client/host $ node -v
v6.3.1
```

```
Semaphore: ~/asiago-react-client/host $ npm config get registry
https://npm-proxy.fury.io/.../kmamykin/
```

```
Semaphore: ~/asiago-react-client/host $ npm i
npm ERR! Linux 3.13.0-32-generic
npm ERR! argv "/home/runner/.nvm/versions/node/v6.3.1/bin/node" "/home/runner/.nvm/versions/node/v6.3.1/bin/npm" "i"
npm ERR! node v6.3.1
npm ERR! npm  v4.0.1
npm ERR! code EREADFILE

npm ERR! Error extracting /home/runner/.npm/webpack/1.13.2/package.tgz archive: ENOENT: no such file or directory, open '/home/runner/.npm/webpack/1.13.2/package.tgz'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/runner/asiago-react-client/host/npm-debug.log
```

`npm cache ls` outputs 
```
~/.npm/webpack
~/.npm/webpack/2.1.0-beta.25
~/.npm/webpack/2.1.0-beta.25/package.tgz
~/.npm/webpack/2.1.0-beta.25/package
~/.npm/webpack/2.1.0-beta.25/package/package.json
```

relevant part from package.json
```
  "devDependencies": {
    "asiago-scripts": "^0.1.0"
  }
```
and asiago-scripts package.json:
```
   ...
    "webpack": "1.13.3",
   ...
```

So my take on it that npm should be using webpack 1.13.3, but somehow downloads 2.1.0-beta.25 instead?

**Comment by legodude17** [comment]
I agree with @kmamykin. This may be a problem with `webpack` as well.
