### ISSUE TITLE
npm install atom-package-manager error

### ISSUE THREAD

**Issue by crishushu** [npm/npm#14443]
```
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\Users\PATH_TO\node.exe" "C:\Users\PATH_TO\npm-cli.js" "install" "-g" "--save-dev" "atom-package-manager"
npm ERR! node v4.4.0
npm ERR! npm  v3.10.9

npm ERR! must have path
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues
```

[npm-debug.txt](https://github.com/npm/npm/files/556190/npm-debug.txt)

**Comment by KenanY** [comment]
@crishushu Hmm, do you want to install this module locally, and save it to your devDependencies, or do you want to install it globally?

**Comment by crishushu** [comment]
Both. Globally and add the dependency to the package.json. The latter I maintain for storage purposes. However, the error occurs independently.

**Comment by legodude17** [comment]
Try installing something else, like `eslint`. Post output. Then try updating to `npm@4`.

**Comment by KenanY** [comment]
Closing due to no response
