### ISSUE TITLE
mysql can't be installed on MacOS by npm

### ISSUE THREAD

**Issue by talentAN** [npm/npm#14449]
here's the error blow 

anzhendeMacBook-Air:www.niceandeasy.cn anzhen$ npm install mysql -g
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "mysql" "-g"
npm ERR! node v4.6.1
npm ERR! npm  v2.15.9

npm ERR! shasum check failed for /var/folders/xk/3w5n1fkx0rxc8kdzw6zvmscr0000gn/T/npm-15656-1169f336/registry.npmjs.org/bignumber.js/-/bignumber.js-2.3.0.tgz
npm ERR! Expected: 597a02d791edc3d64f17850e21789e7a4095df66
npm ERR! Actual:   d31d943eb67e33097b50c8b680d7a19ef9f027fc
npm ERR! From:     https://registry.npmjs.org/bignumber.js/-/bignumber.js-2.3.0.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/anzhen/git/www.niceandeasy.cn/npm-debug.log

PS: I've tried to clean the cache, but it didn't work, anyone help? many thanks~

**Comment by talentAN** [comment]
problem solved by installing IOS file in other route. for people in China like me, could use this:
‘npm config set registry https://registry.npm.taobao.org’
then you could install mysql

**Comment by legodude17** [comment]
So this can be closed then. Can you close it @talentAN or @KenanY?
