### ISSUE TITLE
ERROR: npm install -g tsd 

### ISSUE THREAD

**Issue by biletzk** [npm/npm#14440]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [X] npm is producing an incorrect install.
- [X] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
### supporting information:

I Write: C:\Users\G0052277>npm install -g tsd

and got This:

```
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\
node_modules\npm\bin\npm-cli.js" "install" "-g" "tsd"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code UNABLE_TO_GET_ISSUER_CERT_LOCALLY

npm ERR! unable to get local issuer certificate
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\G0052277\npm-debug.log
```

- Windows, OS X/macOS, or Linux?:
  Windows 7
- Network issues:
  - Geographic location where npm was run:
  - [X] I don't use a proxy, but have limited or unreliable internet access.

**Comment by legodude17** [comment]
Try `npm cache clean`.
