### ISSUE TITLE
 Permission denied (publickey) but all keys are installed correctly

### ISSUE THREAD

**Issue by matticusfinch** [npm/npm#14447]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I have used Git Bash to clone a repository and am attempting to run 
`npm install`
I receive the error message 

```
npm ERR! git rev-list -n1 4.0: fatal: ambiguous argument '4.0': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 4.0: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 4.0: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 4.0:
npm ERR! git rev-list -n1 4.0: fatal: ambiguous argument '4.0': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 4.0: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 4.0: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 4.0:
npm ERR! git fetch -a origin (git@github.com:gulpjs/gulp-cli.git) Permission denied (publickey).
npm ERR! git fetch -a origin (git@github.com:gulpjs/gulp-cli.git) fatal: Could not read from remote repository.
npm ERR! git fetch -a origin (git@github.com:gulpjs/gulp-cli.git)
npm ERR! git fetch -a origin (git@github.com:gulpjs/gulp-cli.git) Please make sure you have the correct access rights
npm ERR! git fetch -a origin (git@github.com:gulpjs/gulp-cli.git) and the repository exists.
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true fetch -a origin
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
```
I've followed as many Google guides as I can, and have spent at least 15 hours trying to fix this myself :) I have a private key added to git bash which I confirm with `ssh-add -l` and I've added the public key to my bitbucket account as well as adding the private key to Pageant Key. I've reformatted windows twice and installed all my dependencies each time. 

I've also had other developers at my company attempt to clone the repository from scratch and it all works for them. 

#### How can the CLI team reproduce the problem?

I'm not sure if anyone can replicate this, but I seem to be alone on Google having this problem. 

### supporting information:

 - `npm -v` prints: 3.10.8
 - `node -v` prints: v7.0.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows 10
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
Try running just `git fetch -a https://github.com/gulpjs/gulp-cli`.

**Comment by matticusfinch** [comment]
This is what I get:
`fatal: Not a git repository (or any of the parent directories): .git`

**Comment by legodude17** [comment]
Then first run `git init` and then try again.

**Comment by matticusfinch** [comment]
sorry, I realize now why that didn't work. I ran it in my repository folder and got:
```
warning: no common commits
remote: Counting objects: 854, done.
remote: Total 854 (delta 0), reused 0 (delta 0), pack-reused 854
Receiving objects: 100% (854/854), 140.63 KiB | 0 bytes/s, done.
Resolving deltas: 100% (430/430), done.
From https://github.com/gulpjs/gulp-cli
 * branch            HEAD       -> FETCH_HEAD
```
After running it, I tried `npm install` again but received the same error :)

**Comment by legodude17** [comment]
That is really odd. Any idea @othiym23 or @KenanY?

**Comment by KenanY** [comment]
How about `git fetch -a git@github.com:gulpjs/gulp-cli.git`? Providing the generated `npm-debug.log` might help as well.

**Comment by matticusfinch** [comment]
Here's the message after running the above and I've included my debug log below.
```
$ git fetch -a git@github.com:gulpjs/gulp-cli.git
The authenticity of host 'github.com (192.30.253.113)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.253.113' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

https://gist.github.com/matticusfinch/7bbe53e7a1899f602a6de37e19d1c627

**Comment by KenanY** [comment]
@matticusfinch Hmm, have you [added](https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/) your ssh public key to github?

**Comment by matticusfinch** [comment]
I did re-add it after clearing out my key list and am still getting the same error.

**Comment by legodude17** [comment]
It is strange how the error only happens with `git@...` and not `https://...`. Try a different repo with `git fetch -a git@github.com/...`.

**Comment by matticusfinch** [comment]
Interesting.. yeah all the repositories give me the permission denied error.  The keys in my github settings say they've never been used. Maybe that's affecting this.

**Comment by legodude17** [comment]
Try generating new keys and then using the new ones.

**Comment by matticusfinch** [comment]
Progress! I recreated the key in git bash instead of through PuTTY Key Generator and added it to Github.
Running `git fetch -a git@github.com:gulpjs/gulp-cli.git` worked.

Now when I run `npm install` I get 
```
$ npm install
npm ERR! git rev-list -n1 4.0: fatal: ambiguous argument '4.0': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 4.0: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 4.0: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 4.0:
npm ERR! git rev-list -n1 4.0: fatal: ambiguous argument '4.0': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 4.0: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 4.0: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 4.0:
npm ERR! git rev-list -n1 4.0: fatal: ambiguous argument '4.0': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 4.0: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 4.0: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 4.0:
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true rev-list -n1 4.0
npm ERR! fatal: ambiguous argument '4.0': unknown revision or path not in the working tree.
npm ERR! Use '--' to separate paths from revisions, like this:
npm ERR! 'git <command> [<revision>...] -- [<file>...]'
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\apps\website\npm-debug.log
```

**Comment by matticusfinch** [comment]
I re-cloned the repository again after add the key into bitbucket as well and I get the same error message as before :(

**Comment by legodude17** [comment]
Try updating `npm`. That seems like an internal bug. Do you know where that could be from @othiym23 or @zkat?

**Comment by matticusfinch** [comment]
I used `npm install npm@latest -g`, it worked, but running `npm install` gave the same issue as before. I also tried repairing my nodejs installing. 

I'm wondering if I should reformat then do this:
Install Git
Install node
generate ssh key
add to gitub
`npm install bower -g`
clone repository
`npm install`

**Comment by legodude17** [comment]
Before you do that, what is your package.json?

**Comment by matticusfinch** [comment]
I did have another developer clone the repository and npm install worked for them. I hope it's not the project itself.

```
{
  "name": "foundation-zurb-template",
  "version": "1.0.0",
  "description": "Official ZURB Template for Foundation for Sites.",
  "main": "gulpfile.js",
  "scripts": {
    "start": "gulp",
    "build": "gulp build --production"
  },
  "author": "ZURB <foundation@zurb.com>",
  "license": "MIT",
  "devDependencies": {
    "babel-core": "^6.7.2",
    "babel-plugin-transform-es2015-arrow-functions": "^6.5.2",
    "babel-plugin-transform-es2015-block-scoped-functions": "^6.5.0",
    "babel-plugin-transform-es2015-block-scoping": "^6.5.0",
    "babel-plugin-transform-es2015-classes": "^6.5.2",
    "babel-plugin-transform-es2015-destructuring": "^6.5.0",
    "babel-plugin-transform-es2015-modules-commonjs": "^6.5.2",
    "babel-plugin-transform-es2015-parameters": "^6.5.0",
    "babel-plugin-transform-es2015-shorthand-properties": "^6.5.0",
    "babel-plugin-transform-es2015-spread": "^6.5.2",
    "babel-plugin-transform-es2015-template-literals": "^6.5.2",
    "babel-preset-es2015": "^6.6.0",
    "browser-sync": "^2.10.0",
    "gulp": "gulpjs/gulp#4.0",
    "gulp-autoprefixer": "^3.1.0",
    "gulp-babel": "^6.1.2",
    "gulp-cli": "gulpjs/gulp-cli#4.0",
    "gulp-concat": "^2.5.2",
    "gulp-cssnano": "^2.1.0",
    "gulp-extname": "^0.2.0",
    "gulp-if": "^2.0.0",
    "gulp-imagemin": "^2.2.1",
    "gulp-load-plugins": "^1.1.0",
    "gulp-sass": "^2.1.0",
    "gulp-sourcemaps": "^1.6.0",
    "gulp-uglify": "^1.2.0",
    "gulp-uncss": "^1.0.1",
    "js-yaml": "^3.4.6",
    "panini": "^1.3.0",
    "rimraf": "^2.4.3",
    "style-sherpa": "^1.0.0",
    "yargs": "^3.8.0"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/zurb/foundation-zurb-template.git"
  },
  "bugs": {
    "url": "https://github.com/zurb/foundation-sites/issues",
    "email": "foundation@zurb.com"
  },
  "private": true
}

```

**Comment by legodude17** [comment]
Any reason you need to get `gulp` from github instead of the npm registry? It seems the error comes from (here)[https://github.com/npm/npm/blob/latest/lib/cache/add-remote-git.js#L279]. Maybe they could add a `--` there to fix this issue?

**Comment by legodude17** [comment]
Also, maybe there is no `4.0` of `gulp`? Could you also include the last 50 lines or so of `npm-debug.log`?

**Comment by legodude17** [comment]
That looks like the problem, there is no `4.0` version or commitish for `gulp-cli`? What did you want `gulpjs/gulp-cli#4.0` to do?

**Comment by matticusfinch** [comment]
I wish I could tell you, I don't believe I've changed anything here, I'm just using the 6.2 version of foundation. I don't know enough to be making changes in the package.json. 

I will see what the latest version of package.json is from them and try to run it with that.

**Comment by legodude17** [comment]
Ok, try to figure it out. Thanks for your cooperation!

**Comment by matticusfinch** [comment]
So you're pretty much a wizard. Everything is fixed, however, many things remain a mystery.

I updated the gulp and gulp-cli lines in package.json to just use the latest version of both. I then ran `npm install` and `bower install` and they both worked! However, I ran `foundation watch` and it would not work. I checked my git history and package.json hasn't changed since we started building our website.

I then installed a new foundation project and took the package.json contents and pasted them into my existing project and now everything works.
This is my new package.json file: 
```
{
  "name": "foundation-zurb-template",
  "version": "1.0.0",
  "description": "Official ZURB Template for Foundation for Sites.",
  "main": "gulpfile.js",
  "scripts": {
    "start": "gulp",
    "build": "gulp build --production"
  },
  "author": "ZURB <foundation@zurb.com>",
  "license": "MIT",
  "devDependencies": {
    "babel-preset-es2015": "^6.3.13",
    "babel-register": "^6.7.2",
    "browser-sync": "^2.10.0",
    "gulp": "gulpjs/gulp#4.0",
    "gulp-autoprefixer": "^3.1.0",
    "gulp-babel": "^6.1.2",
    "gulp-cli": "^1.2.1",
    "gulp-concat": "^2.5.2",
    "gulp-cssnano": "^2.1.0",
    "gulp-extname": "^0.2.0",
    "gulp-if": "^2.0.0",
    "gulp-imagemin": "^2.2.1",
    "gulp-load-plugins": "^1.1.0",
    "gulp-sass": "^2.1.0",
    "gulp-sourcemaps": "^1.6.0",
    "gulp-uglify": "^1.2.0",
    "gulp-uncss": "^1.0.1",
    "js-yaml": "^3.4.6",
    "panini": "^1.3.0",
    "rimraf": "^2.4.3",
    "style-sherpa": "^1.0.0",
    "yargs": "^3.8.0"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/zurb/foundation-zurb-template.git"
  },
  "bugs": {
    "url": "https://github.com/zurb/foundation-sites/issues",
    "email": "foundation@zurb.com"
  },
  "babel": {
    "presets": ["es2015"]
  },
  "private": true
}
```

This is looking like npm was just doing what it was told and my package.json file was the one who was telling it what to do incorrectly. Seems like it's foundation's fault, which I should have suspected as using foundation has been one of the most error prone experiences of my life :)

I think we're safe to close this. Again, thanks for your help. We haven't been able to update our website for months because of this!

**Comment by legodude17** [comment]
Any reason you closed it, reopened it, then closed it again?

**Comment by matticusfinch** [comment]
Was accident, sorry.

**Comment by gwiant** [comment]
What was solutions to this?... getting same error.

**Comment by legodude17** [comment]
Make sure to install things that exist.

**Comment by AlbertoTrindade** [comment]
I had the same issue, but got to solve it!

After updating my npm version (by running `npm install -g npm`) and deleting package-lock.json file, the `npm install` worked fine.

**Comment by daton89** [comment]
check your ssh-agent
