### ISSUE TITLE
Error Installing Embark

### ISSUE THREAD

**Issue by rjayreglos** [npm/npm#14441]
Hi,

I am trying to install Embark using the command **npm install -g embark** but got an error shown in the attachment. I tried several times but got no luck on installing it. Please assist.

Attachment: [npm debug.docx](https://github.com/npm/npm/files/555989/npm.debug.docx)

Thanks,

RJ

**Comment by legodude17** [comment]
Check your internet connection. Also try `ping github.com:22`.
