### ISSUE TITLE
NPM Can't find jshint after jshint installed - Windows 10

### ISSUE THREAD

**Issue by jasonpierson** [npm/npm#14445]
#### I'm opening this issue because:
NPM can't find jshint(I'm guessing? totally new to JS and JS task runners)

#### What's going wrong?
When I run this command:
npm run jshint app_awana_store/cartridge/js/*.js

I get this error:
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Users\\a-jasonpn\\Documents\\GitHub\\Demandware-Sandbox\\node.exe" "C:\\Users\\a-jasonpn\\Documents\\GitHub\\Demandware-Sandbox\\node_modules\\npm\\bin\\npm-cli.js" "run" "jshint" "app_awana_store/cartridge/js/*.js"
npm ERR! node v4.6.1
npm ERR! npm  v2.15.9

npm ERR! missing script: jshint
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\a-jasonpn\Documents\GitHub\Demandware-Sandbox\npm-debug.log

#### How can the CLI team reproduce the problem?
1. Create the directory C:\Users\<your user>\Documents\GitHub\Demandware-Sandbox\app_awana_store\cartridge\js and copy a js file(any js file) to it
2. Install NodeJS on Windows 10(change install directory to C:\Users\<your user>\Documents\GitHub\Demandware-Sandbox)
3. Open Task Manager(Ctrl+Shift+Esc)
4. File, Run new task
5. Type cmd
6. Check the Run this task with administrative privileges box
7. Click ok
8. Type cd C:\Users\<your user>\Documents\GitHub\Demandware-Sandbox and hit enter
9. Type npm install jshint --save-dev and hit enter
10. Type npm run jshint app_awana_store/cartridge/js/*.js and hit enter. The error appears.

Gist:
https://gist.github.com/jasonpierson/01c13ee14d7ae8aa031ac7383fea891f

### supporting information:

 - `npm -v` prints: 2.15.9
 - `node -v` prints: v4.6.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows 10
 - Network issues:
   - Geographic location where npm was run: Chicago, IL
None of the rest of this was applicable.

**Comment by KenanY** [comment]
`npm run jshint` will execute the `"jshint"` script that you have defined in your local `package.json`. The error message is indicating that you do not have such a script defined. You can read more about scripts [here](https://docs.npmjs.com/misc/scripts), but I think what you want is:

``` json
{
  "scripts": {
    "jshint": "jshint app_awana_store/cartridge/js/*.js"
  }
}
```

**Comment by jasonpierson** [comment]
That did it; thanks @KenanY !
