### ISSUE TITLE
I failed to install the npm,please help me ！

### ISSUE THREAD

**Issue by mynameisaaa** [npm/npm#14450]
![image](https://cloud.githubusercontent.com/assets/23112538/19793723/9e9a04d8-9d00-11e6-936c-57da8ffb22ce.png)

**Comment by legodude17** [comment]
Try updating to `npm@4`.

**Comment by mynameisaaa** [comment]
Thanks for you suggestion.

**Comment by mynameisaaa** [comment]
The version of node.js  is wrong. I  solved the question a moment ago.

**Comment by KenanY** [comment]
Closing as resolved then.
