### ISSUE TITLE
All npm commands fail with "Error: Cannot find module 'async'"

### ISSUE THREAD

**Issue by michaelsanford** [npm/npm#14456]
#### I'm opening this issue because:
- [x] npm is crashing.
- [x] npm is producing an incorrect install.
- [ ] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):

The problem is no longer blocking; I am reporting it for reference in case it can be tied to some code change and to track others experiencing it.

Feel free to close this issue if you feel that's most appropriate.
#### What's going wrong?

Any `npm` command (including `npm` with no arguments) throws `Error: Cannot find module 'async'` error with the following trace:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\me\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js' ]
2 info using npm@3.10.8
3 info using node@v7.0.0
4 verbose config Skipping project config: C:\Users\me/.npmrc. (matches userconfig)
5 verbose stack Error: Cannot find module 'async'
5 verbose stack     at Function.Module._resolveFilename (module.js:472:15)
5 verbose stack     at Function.Module._load (module.js:420:25)
5 verbose stack     at Module.require (module.js:500:17)
5 verbose stack     at require (internal/module.js:20:19)
5 verbose stack     at Object.<anonymous> (C:\Users\me\AppData\Roaming\npm\node_modules\npm\node_modules\request\node_modules\form-data\lib\form_data.js:9:13)
5 verbose stack     at Module._compile (module.js:573:32)
5 verbose stack     at Object.Module._extensions..js (module.js:582:10)
5 verbose stack     at Module.load (module.js:490:32)
5 verbose stack     at tryModuleLoad (module.js:449:12)
5 verbose stack     at Function.Module._load (module.js:441:3)
6 verbose cwd C:\Users\me
7 error Windows_NT 10.0.14393
8 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\me\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js"
9 error node v7.0.0
10 error npm  v3.10.8
11 error code MODULE_NOT_FOUND
12 error Cannot find module 'async'
13 error If you need help, you may report this error at:
13 error     <https://github.com/npm/npm/issues>
14 verbose exit [ 1, true ]
```

This is true in and outside of a project folder.
#### How can the CLI team reproduce the problem?

I cannot isolate any specific action that caused this behaviour, other than having "recently" updated to node v7.0.0 (with bundled npm 3.10.8). This behaviour _did not_ appear immediately after updating, but a day later.

As usual, I `npm cache clean`ed after updating, but did neglect to update my few global modules. I did `npm update` my project folder, though.

I _did not_ issue any `npm -g` command between upgrading to v7.0.0 and the issue.

In an attempt to fix the issue, since I could not `npm i -g async`, I ran the v7.0.0 Windows MSI installer in Repair mode. Same behaviour, so I used the installer to Remove v7.0.0 and then installed v6.9.1 from the MSI. Same behaviour.

What finally unblocked me was completely deleting:
- C:\Users\me\AppData\Roaming\npm
- C:\Users\me\AppData\Roaming\npm-cache

and re-installing node v7.0.0 (with bundled npm 3.10.8) from the MSI. I could then `npm i -g` my required global modules and run npm commands within my project.
#### Yarn note

I have [yarn 0.16.5](https://github.com/yarnpkg/yarn) installed concurrently, and have been testing it by using `yarn install`, `yarn upgrade` and `yarn start` in place of `npm`, but only for my local project.

I have not acted globally with `yarn` (as far as I know).

Perhaps not relevant, but worth mentioning.
### supporting information:
- `npm -v` prints: `3.10.8`
- `node -v` prints: `v7.0.0`
- `npm config get registry` prints: `https://registry.npmjs.org/`
- Windows, OS X/macOS, or Linux?: Windows 10 
- Network issues:
  - Geographic location where npm was run:
  - [x] I use a proxy to connect to the npm registry.
  - [x] I use a proxy to connect to the web.
  - [x] I use a proxy when downloading Git repos.
  - [ ] I access the npm registry via a VPN
  - [ ] I don't use a proxy, but have limited or unreliable internet access.
- Container:
  - [ ] I develop using Vagrant on Windows.
  - [ ] I develop using Vagrant on OS X or Linux.
  - [ ] I develop / deploy using Docker.
  - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
So what is the problem? It seems like you fixed it yourself.

**Comment by michaelsanford** [comment]
@legodude17 As I said at the top, I am reporting it _for reference in case it can be tied to some code change_ and to track _others experiencing it._

I felt it was appropriate to report in case _it actually is_ a bug in node or npm, especially since there was just a major release. Importantly, it appeared to be a bug _internal to npm_, which is something the governance team should at least be made aware of.

If nobody else experiences this problem, it's possibly a local issue and should, of course, be closed, but I wanted to leave others an opportunity to find it by Google, add details to my report, etc. 👍

**Comment by legodude17** [comment]
One of the strangest things about this is that `npm` doesn't depend on `async`. Maybe one of the submodules?

**Comment by michaelsanford** [comment]
@legodude17 It is very strange! That's another reason I'm certainly not ruling out some kind of weird local issue, possibly related to `yarn` (but I don't want to call yarn out since I have no concrete evidence it has anything to do with the problem).

I saw this behaviour in my home folder (for example) which has no `package.json` file in the filesystem hierarchy in or above it.
