### ISSUE TITLE
npm ERR! Windows_NT 6.1.7601

### ISSUE THREAD

**Issue by yedukondalurd** [npm/npm#14469]
When i try to install NPM facing the below issue please help on how to resolve it..
--- Executing : npm install

```
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or hig
 to avoid a RegExp DoS issue
npm WARN deprecated lodash-node@2.4.1: This package is discontinued. Use loda
^4.0.0.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\nodejs\\node.exe" "C:\\Users\\LENOVO\\AppData\\Roaming\\np
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.9
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: ember-cli-flash@@@ember-cli-fl
_VERSION
npm ERR! notarget Valid install targets:
npm ERR! notarget 1.3.17, 1.3.16, 1.3.15, 1.3.14, 1.3.13, 1.3.12, 1.3.11, 1.3
, 1.3.9, 1.3.8, 1.3.7, 1.3.6, 1.3.5, 1.3.4, 1.3.3, 1.3.2, 1.3.1, 1.3.0, 1.2.0
.1.4, 1.1.3, 1.1.2, 1.1.1, 1.1.0, 1.0.0, 0.8.3, 0.8.2, 0.8.1, 0.8.0, 0.7.0, 0
0, 0.5.0, 0.4.6, 0.4.5, 0.4.0, 0.2.5, 0.2.1, 0.2.0, 0.1.5, 0.1.4, 0.1.3, 0.1.
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requestin
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'wb-ui-components'
npm ERR! notarget

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Projects\wb-ui-sdm\npm-debug.log
Command `npm install` failed. Please check the logs.
Command `node common-scripts/common-setup.js` failed. Please check the logs.
 ```

**Comment by luo772435545** [comment]
ERR! Windows_NT 6.1.7601
ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ionic" "cordova"
ERR! node v6.4.0
ERR! npm  v3.8.6

ERR! shasum check failed for C:\Users\ADMINI~1\AppData\Local\Temp\npm-10084-9d2bac7f\registry.npmjs.org\cordova-app-hello-world\-\cordova-app-hello-world-3.11.0.tgz
ERR! Expected: 9214feb9dd713ca481a1cbabceeca60966c1c0cf
ERR! Actual:   722fe67915c396bfbe6481f6fe12ab9c8d76a6cd
ERR! From:     https://registry.npmjs.org/cordova-app-hello-world/-/cordova-app-hello-world-3.11.0.tgz
ERR!
ERR! If you need help, you may report this error at:
ERR!     <https://github.com/npm/npm/issues>

ERR! Please include the following file with any support request:
ERR!     E:\myApp\npm-debug.log

**Comment by frontzhm** [comment]
Hello, i meet the same trouble ,then i find that i run ionic serve in another cmd .Then i close that , try npm install -g ionic again ,yes,it works !   I hope it can help you ~

**Comment by luo772435545** [comment]
啊哈，谢谢你~正在尝试你的方法，Installing npm packages...好慢好慢

**Comment by legodude17** [comment]
@luo772435545 and @frontzhm, the issue you are talking about is not related to the one that this is filed as.

**Comment by KenanY** [comment]
@yedukondalurd Could you provide your `package.json`? Is `npm install` what you are running in your command-line, or are you calling some other command which is executing `npm install`? I've seen this issue before (https://github.com/npm/npm/issues/11079) but no one who has had the issue has ever tried to debug it.

**Comment by KenanY** [comment]
Closing due to no response

**Comment by yedukondalurd** [comment]
I am sorry for late reply.

The actual problem with npm version.
I have down graded the npm version so it's resolved now.

Thanks,
Yedu
+91-9032301137

This was sent from phone. Please excuse typos.
