### ISSUE TITLE
error:0906d06c:pem routines:pem_read_bio:no start line

### ISSUE THREAD

**Issue by beyns** [npm/npm#14466]
Hi,

I am trying to install 'angular-cli' using "npm install -g angular-cli" and I am getting this error. I already have node installed and running on my workstation. I do not know what to do now as I am just a beginner in this field. Thanks for help in advance. :)

npm error    error:0906d06c:pem routines:pem_read_bio:no start line

npm error  Please include the following file with any support request:
                 C:Users\asas\npm-debug.log

**Comment by LetHerGo12** [comment]
same error even I have an internet connection
