### ISSUE TITLE
Scripts Ignoring Argument Flags

### ISSUE THREAD

**Issue by RyanMcDonald** [npm/npm#14460]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [X] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I am trying to run a script from the `scripts` section and pass it arguments using `--`, but it ends up stripping any flags that I pass it, and only including the string values.

#### How can the CLI team reproduce the problem?

package.json:
```json
"test-specific": "gulp db:prepare_test && mocha --"
```

then:
```
npm run test-specific path/to/test/file.js -g 'string to grep'
```

The resulting command is:
```
gulp db:prepare_test && mocha -- "path/to/test/file.js" "string to grep"
```

Passing the `--` on the command line instead of in the package.json script works, however I was hoping to eliminate the need to type `--` every time for this particular script.

### supporting information:

 - `npm -v` prints: 3.8.6
 - `node -v` prints: 6.0.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: OS X

**Comment by legodude17** [comment]
The reason for this is that `npm` thinks that `-g` is a flag for itself, and the `-g` (`--global`) flag takes no arguments, so the string is passed. This is not a bug, but a feature. 😄 You will need to type the `--` every time.

**Comment by RyanMcDonald** [comment]
Ahh I get it now! Thank you!
