### ISSUE TITLE
NPM keeps giving errors when in root

### ISSUE THREAD

**Issue by jeroenouw** [npm/npm#14467]
#### I'm opening this issue because:

  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.

#### What's going wrong?

```
$ npm install -g generator-keystone
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Eigenaar\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "generator-keystone"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.9
npm ERR! path C:\Program Files\Git\node_modules
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall mkdir

npm ERR! Error: EPERM: operation not permitted, mkdir 'C:\Program Files\Git\node_modules'
npm ERR!     at Error (native)
npm ERR!  { Error: EPERM: operation not permitted, mkdir 'C:\Program Files\Git\node_modules'
npm ERR!     at Error (native)
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: 'C:\\Program Files\\Git\\node_modules' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Eigenaar\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "generator-keystone"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.9
npm ERR! path C:\Program Files\Git\npm-debug.log.1582070618
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall open

npm ERR! Error: EPERM: operation not permitted, open 'C:\Program Files\Git\npm-debug.log.1582070618'
npm ERR!     at Error (native)
npm ERR!  { Error: EPERM: operation not permitted, open 'C:\Program Files\Git\npm-debug.log.1582070618'
npm ERR!     at Error (native)
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'open',
npm ERR!   path: 'C:\\Program Files\\Git\\npm-debug.log.1582070618' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Program Files\Git\npm-debug.log
```

#### How can the CLI team reproduce the problem?

Everytime i'm in the root and post a command, like in this example:
`npm install -g generator-keystone`
I get all kinds of errors

### supporting information:

 - `npm -v` prints: 3.10.9
 - `node -v` prints: v6.9.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows 10

**Comment by watilde** [comment]
Hello! Have you tried reinstalling as an administrator since it's permission error?

**Comment by legodude17** [comment]
What do you mean by 'in root'? That error means you you don't have write access to your global package dir. Please follow [these instructions](https://docs.npmjs.com/getting-started/fixing-npm-permissions).

**Comment by jeroenouw** [comment]
@watilde 
I was looking for how to do it as administrator but now it eventually worked for me, I did get the following :```

$ npm install -g generator-keystone
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
C:\Users\Eigenaar\AppData\Roaming\npm
`-- generator-keystone@0.4.2
```
Thanks for remindering and support.

@legodude17 With 'root' I mean the location when you open the NodeJS CLI. So I didn't changed directory, tnx for you support.
