### ISSUE TITLE
npm install -g angular-cli is failing 

### ISSUE THREAD

**Issue by vijaykumarravva** [npm/npm#14476]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

trying to install angular-cli 
npm install -g angular-cli is failing 

my current version of node is v4.4.4
I am getting the below error 

```
npm WARN engine angular-cli@1.0.0-beta.19-3: wanted: {"node":">= 4.1.0","npm":">= 3.0.0"} (current: {"node":"4.4.4","npm":"2.15.1"})
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:<path>\\node.exe" "C:<path_to the folder>\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "angular-cli@latest"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1

npm ERR! Unexpected token <
npm ERR! <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
npm ERR! <html><head>
npm ERR! <title>404 Not Found</title>
npm ERR! </head><body>
npm ERR! <h1>Not Found</h1>
npm ERR! <p>The requested URL /content/groups/level0.npm/@angular/platform-browser was not found on this server.</p>
npm ERR! </body></html>
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
```

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@vijaykumarravva Could you provide the `npm-debug.log` file as a [gist](https://gist.github.com/)?
