### ISSUE TITLE
Retrieves packages not specified npm repository

### ISSUE THREAD

**Issue by alexbel2404** [npm/npm#14475]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I specify npm repository artifactory, but tries to download packages from registry.npmjs.org

#### How can the CLI team reproduce the problem?
npm install -g npmbox --registry=https://artifactory.local/api/npm/npm
```
npm sill mapToRegistry name assertion-error@https://registry.npmjs.org/assertion-error/-/assertion-error-1.0.2.tgz
npm sill mapToRegistry using default registry
npm sill mapToRegistry registry https://artifactory.local/api/npm/npm
npm sill mapToRegistry data Result {
npm sill mapToRegistry   raw: 'assertion-error@https://registry.npmjs.org/assertion-error/-/assertion-error-1.0.2.tgz',
npm sill mapToRegistry   scope: null,
npm sill mapToRegistry   escapedName: 'assertion-error',
npm sill mapToRegistry   name: 'assertion-error',
npm sill mapToRegistry   rawSpec: 'https://registry.npmjs.org/assertion-error/-/assertion-error-1.0.2.tgz',
npm sill mapToRegistry   spec: 'https://registry.npmjs.org/assertion-error/-/assertion-error-1.0.2.tgz',
npm sill mapToRegistry   type: 'remote' }
npm sill mapToRegistry uri https://registry.npmjs.org/assertion-error/-/assertion-error-1.0.2.tgz
npm verb scopeAuth alwaysAuth set for https://artifactory.local/api/npm/npm
npm verb addRemoteTarball https://registry.npmjs.org/assertion-error/-/assertion-error-1.0.2.tgz not in flight; adding
npm verb addRemoteTarball [ 'https://registry.npmjs.org/assertion-error/-/assertion-error-1.0.2.tgz',
npm verb addRemoteTarball   null ]
```

### supporting information:

 - `npm -v` prints:
v6.8.0
 - `node -v` prints:
3.10.8
 - `npm config get registry` prints:
https://artifactory.local/api/npm/npm
 - Windows, OS X/macOS, or Linux?:
Linux
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [x] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
That isn't really `npm`'s fault, it was just using the `Result` it got from `https://artifactory.local/api/npm/npm`. That registry sent the `spec` as something on `https://registry.npmjs.org`.
