### ISSUE TITLE
my package is been replaced

### ISSUE THREAD

**Issue by vvpvvp** [npm/npm#14481]
Why my momentjs page is replaced with an other page?
And the page is point to another author?

https://www.npmjs.com/package/momentjs

**Comment by legodude17** [comment]
According to the page, it was published four days ago. Also, this is not the correct place for package issues. Please close this issue and then contact npm support at support@npmjs.com.

**Comment by zkat** [comment]
This is a registry-related issue and communication was moved to a separate channel, so I'm closing this particular one.
