### ISSUE TITLE
npm ignores the "&" and only use the first command. Windows

### ISSUE THREAD

**Issue by EleonoraSmid** [npm/npm#14485]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Npm ignores the second command when I run scripts. So: "start": "npm run command 1 & npm run command 2" . Will only run command 1 and ignore the second command. 

I am using Windows 10, but I know for sure that "&&" is cross platform. 

This is working fine on a mac. 

### supporting information:

 - `npm -v` prints: 3.10.8
 - `node -v` prints: v4.5.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X

**Comment by legodude17** [comment]
The only reasons I can think of are:

1. The `&&` doesn't work well on windows.

2. The first command failed

**Comment by EleonoraSmid** [comment]
I am doing the exact same thing on my macbook and there it works as aspected.

"start": "command 1 & command 2";

If I run this it will load both scripts. So, as example, I can launch my node server and watch less files. 

Thus on Windows machine the "&" doesn't work. Odd...

**Comment by legodude17** [comment]
Shouldn't it be `&&`? Also, have you tried just running `command 1 && command 2` in your command prompt?

**Comment by EleonoraSmid** [comment]
You can use '&' to run multiple commands concurrently. But that is not the case, Windows ignores everything after the '&'.
So I thought maybe it's because one script is going on forever while not returning something back. Like a watch script. But that isn't the problem. I did an 'echo' as command 1. And even then it only echo's the output but ignores command 2.

On my macbook it works perfectly fine. 

Also tried this on a different Windows computer where I stumble on the same problem.

**Comment by othiym23** [comment]
`&` to background a task is a Unix shell convention that isn't supported by `cmd.exe`, which npm uses to run scripts on Windows. There are many helper tools on npm you can use to run tasks concurrently, or in the background. For the time being, though, this isn't something you can do natively on Windows with npm scripts. As such, I'' going to close this issue. Thanks for your time!
