### ISSUE TITLE
npm unhandeled 'error' event during npm start

### ISSUE THREAD

**Issue by asdfadrian** [npm/npm#14487]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Im trying to run a template. I had it running before but I deleted it and ran a new one from scratch in attempt to refactor my existing code into the template. The template I am using is from here: https://github.com/buckyroberts/React-Redux-Boilerplate/issues/9

I can 'npm install' but when I 'npm start' I get the below error: 

> react-redux-template@1.0.0 start /Users/adrianalonzo/Desktop/Work/fallstrap/react/Apps/React-Redux-Boilerplate-master
> webpack-dev-server

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:3000
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at net.js:1397:7
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:81:10)

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! react-redux-template@1.0.0 start: `webpack-dev-server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-redux-template@1.0.0 start script 'webpack-dev-server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-redux-template package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-redux-template
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-redux-template
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/adrianalonzo/Desktop/Work/fallstrap/react/Apps/React-Redux-Boilerplate-master/npm-debug.log

### supporting information:

 - `npm -v` prints: 3.10.8
 - `node -v` prints:  v7.0.0
 - `npm config get registry` prints: https://registry.npmjs.org
 - Windows, OS X/macOS, or Linux?: OSX

[npm-debug.log.txt](https://github.com/npm/npm/files/564666/npm-debug.log.txt)

**Comment by KenanY** [comment]
@asdfadrian Looks like you are trying to spin up a server on port 3000, but you already have a process occupying that port. This has nothing to do with `npm`, just close whatever other server you might be running on that port and try again, or open your new server on a different port.

**Comment by asdfadrian** [comment]
Ok thanks for pointing that out. How would I terminate that port so I may reuse it? Currently I am just doing a workaround and running it on a different port.

**Comment by KenanY** [comment]
There might be a better way but I would just look at your list of process for anything which looks like it could be using that port (i.e., another instance of `webpack-dev-server`).

**Comment by hakimCZE** [comment]
That is not the problem, even when I kill the process, dev server wont start (only if I use sudo, but then only the frame, that wont connet to app `GET http://localhost:1337/ 404 (Not Found)`)

And I am able to run other servers using given port. And also, when I change the port, result is the same. So there is some weird stuff goin on, and error message is wrong.

**Comment by KenanY** [comment]
@hakimCZE Since that error message is not coming from `npm`, this isn't the place to report such a bug anyways.
