### ISSUE TITLE
Error installing angular-cli on node v6.9.1

### ISSUE THREAD

**Issue by anil215** [npm/npm#14486]
i am attaching the error log file generated by npm , the link is 

(https://drive.google.com/file/d/0B-SV7BtMoY04STZCZm1aUjRQYnc/view?usp=sharing)

**Comment by legodude17** [comment]
This is an issue with `node-sass`. Please file an issue there.

**Comment by othiym23** [comment]
Closing as not an issue with the CLI. Good luck getting this sorted out, and thanks for your time!
