### ISSUE TITLE
npm unpublish does not consider package.json/publishConfig section

### ISSUE THREAD

**Issue by osher** [npm/npm#14488]
#### I'm opening this issue because:
  - [x] Other (_see below for feature requests_):

#### What's going wrong?

`npm unpublish` does not consider `package.json/publishConfig.registry` key

#### How can the CLI team reproduce the problem?

**Having**
 - `npm set registry http://registry.my-corporate.local`
 - working on a package with `publishConfig.registry` key point to `  http://registry.npmjs.com`

**Scenario**
 - expect `npm publish` to work as expected and emit `+<the version you just published>`
 - run `npm unpublish <the version you just published>`

**Expect**
- the version to be unpublished, and npm to emit `-<the version you just unpublished>`

**Found**
 - npm gets stuck for communication error
 - note that  `npm unpublish <the version you just published> --registry http://registry.npmjs.com ` works as expected

### supporting information:

 - `npm -v` prints: `3.10.9`
 - `node -v` prints: `v6.9.1`
 - `npm config get registry` prints: `<the url to corp proprietary packages repo>`
 - OS - Windows 10
 - Network issues:
   - Geographic location where npm was run:
   - [x] I access the npm registry via a VPN
 - Container:
   - [x] Irrelevant

**Comment by legodude17** [comment]
I agree that that is a bug. What do you think @zkat, or @KenanY?

**Comment by KenanY** [comment]
Shoot, I thought this was fixed by https://github.com/npm/npm/pull/8013? /cc @watilde

**Comment by legodude17** [comment]
Can anyone try to replicate this?

**Comment by legodude17** [comment]
Does `test/tap/unpublish-config.js` still pass? If it did that would be very strange.

**Comment by watilde** [comment]
I've just tried this, and it worked: https://gist.github.com/watilde/a174ba4e4f246712e0db62cf22018ece

@osher Could you please give us more information, like your `package.json` or `npm-debug.log` if it's ok?
