### ISSUE TITLE
cannot install @types/react since the name is not found to be valid

### ISSUE THREAD

**Issue by Dierk** [npm/npm#14489]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?

npm does not install at all with this command when I follow the instructions from
https://www.typescriptlang.org/docs/handbook/react-&-webpack.html

`npm install --save @types/react`

#### How can the CLI team reproduce the problem?

`npm install --save @types/react`

The respective error message is:

```
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8

npm ERR! Invalid name: "@types/react"
```

The log is:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   '@types/react' ]
2 info using npm@3.10.8
3 info using node@v7.0.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData @types/react@0.14.44
8 silly fetchNamedPackageData @types/react
9 silly mapToRegistry name @types/react
10 silly mapToRegistry scope (from package name) @types
11 verbose mapToRegistry no registry URL found in name for scope @types
12 silly mapToRegistry using default registry
13 silly mapToRegistry registry https://registry.npmjs.org/
14 silly mapToRegistry data Result {
14 silly mapToRegistry   raw: '@types/react',
14 silly mapToRegistry   scope: '@types',
14 silly mapToRegistry   escapedName: '@types%2freact',
14 silly mapToRegistry   name: '@types/react',
14 silly mapToRegistry   rawSpec: '',
14 silly mapToRegistry   spec: 'latest',
14 silly mapToRegistry   type: 'tag' }
15 silly mapToRegistry uri https://registry.npmjs.org/@types%2freact
16 verbose request uri https://registry.npmjs.org/@types%2freact
17 verbose request no auth needed
18 info attempt registry request try #1 at 22:43:11
19 verbose request id 544314748c424c56
20 verbose etag "CURNY4Y3UA0PRGM4X8B3ZP0GW"
21 http request GET https://registry.npmjs.org/@types%2freact
22 http 304 https://registry.npmjs.org/@types%2freact
23 verbose headers { date: 'Tue, 01 Nov 2016 21:43:11 GMT',
23 verbose headers   via: '1.1 varnish',
23 verbose headers   'cache-control': 'max-age=0',
23 verbose headers   etag: '"CURNY4Y3UA0PRGM4X8B3ZP0GW"',
23 verbose headers   age: '0',
23 verbose headers   connection: 'keep-alive',
23 verbose headers   'x-served-by': 'cache-fra1225-FRA',
23 verbose headers   'x-cache': 'MISS',
23 verbose headers   'x-cache-hits': '0',
23 verbose headers   'x-timer': 'S1478036591.903587,VS0,VE754',
23 verbose headers   vary: 'Accept-Encoding' }
24 silly get cb [ 304,
24 silly get   { date: 'Tue, 01 Nov 2016 21:43:11 GMT',
24 silly get     via: '1.1 varnish',
24 silly get     'cache-control': 'max-age=0',
24 silly get     etag: '"CURNY4Y3UA0PRGM4X8B3ZP0GW"',
24 silly get     age: '0',
24 silly get     connection: 'keep-alive',
24 silly get     'x-served-by': 'cache-fra1225-FRA',
24 silly get     'x-cache': 'MISS',
24 silly get     'x-cache-hits': '0',
24 silly get     'x-timer': 'S1478036591.903587,VS0,VE754',
24 silly get     vary: 'Accept-Encoding' } ]
25 verbose etag https://registry.npmjs.org/@types%2freact from cache
26 verbose get saving @types/react to /Users/dierkkoenig/.npm/registry.npmjs.org/_40types_252freact/.cache.json
27 verbose correctMkdir /Users/dierkkoenig/.npm correctMkdir not in flight; initializing
28 silly install normalizeTree
29 silly loadCurrentTree Finishing
30 silly loadIdealTree Starting
31 silly install loadIdealTree
32 silly cloneCurrentTree Starting
33 silly install cloneCurrentTreeToIdealTree
34 silly cloneCurrentTree Finishing
35 silly loadShrinkwrap Starting
36 silly install loadShrinkwrap
37 silly loadShrinkwrap Finishing
38 silly loadAllDepsIntoIdealTree Starting
39 silly install loadAllDepsIntoIdealTree
40 silly resolveWithNewModule @types/react@0.14.44 checking installable status
41 silly cache add args [ '@types/react@0.14.44', null ]
42 verbose cache add spec @types/react@0.14.44
43 silly cache add parsed spec Result {
43 silly cache add   raw: '@types/react@0.14.44',
43 silly cache add   scope: '@types',
43 silly cache add   escapedName: '@types%2freact',
43 silly cache add   name: '@types/react',
43 silly cache add   rawSpec: '0.14.44',
43 silly cache add   spec: '0.14.44',
43 silly cache add   type: 'version' }
44 silly addNamed @types/react@0.14.44
45 verbose addNamed "0.14.44" is a plain semver version for @types/react
46 silly mapToRegistry name @types/react
47 silly mapToRegistry scope (from package name) @types
48 verbose mapToRegistry no registry URL found in name for scope @types
49 silly mapToRegistry using default registry
50 silly mapToRegistry registry https://registry.npmjs.org/
51 silly mapToRegistry data Result {
51 silly mapToRegistry   raw: '@types/react',
51 silly mapToRegistry   scope: '@types',
51 silly mapToRegistry   escapedName: '@types%2freact',
51 silly mapToRegistry   name: '@types/react',
51 silly mapToRegistry   rawSpec: '',
51 silly mapToRegistry   spec: 'latest',
51 silly mapToRegistry   type: 'tag' }
52 silly mapToRegistry uri https://registry.npmjs.org/@types%2freact
53 verbose addNameVersion registry:https://registry.npmjs.org/@types%2freact not in flight; fetching
54 verbose get https://registry.npmjs.org/@types%2freact not expired, no request
55 silly rollbackFailedOptional Starting
56 silly rollbackFailedOptional Finishing
57 silly runTopLevelLifecycles Finishing
58 silly install printInstalled
59 verbose stack Error: Invalid name: "@types/react"
59 verbose stack     at ensureValidName (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:284:15)
59 verbose stack     at Object.fixNameField (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:199:5)
59 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:29:38
59 verbose stack     at Array.forEach (native)
59 verbose stack     at normalize (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:28:15)
59 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:349:5)
59 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:124:5)
59 verbose stack     at ReadFileContext.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:295:20)
59 verbose stack     at ReadFileContext.callback (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16)
59 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:335:13)
60 verbose cwd /projects/git/tryReactTs
61 error Darwin 16.1.0
62 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "@types/react"
63 error node v7.0.0
64 error npm  v3.10.8
65 error Invalid name: "@types/react"
66 error If you need help, you may report this error at:
66 error     <https://github.com/npm/npm/issues>
67 verbose exit [ 1, true ]
```

**Comment by legodude17** [comment]
It should be a fine name. Try running `npm install --save "@types/react"`.

**Comment by Dierk** [comment]
thanks for looking into the issue.

Anyway, I get the same error.
And when looking into the log one can see that it is not a command-line parsing issue.

Does the command work for you?

cheers
Dierk

**Comment by legodude17** [comment]
The command works for me on macOS and `npm@2.5`. What OS and `npm` version are you using?

**Comment by Dierk** [comment]
OSX Sierra, 
 node v7.0.0
 npm  v3.10.8

**Comment by legodude17** [comment]
I am using OSX El Capitan. It probably has to do with `npm@3.10`. Will try with that version.

**Comment by anandsainath** [comment]
I'm facing the same issue as @Dierk 

MacOS Sierra
npm 6.9.1
npm 3.10.8

> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/local/bin/node',
> 1 verbose cli   '/usr/local/bin/npm',
> 1 verbose cli   'install',
> 1 verbose cli   '--save',
> 1 verbose cli   '@types/react' ]
> 2 info using npm@3.10.8
> 3 info using node@v6.9.1
> 4 silly loadCurrentTree Starting
> 5 silly install loadCurrentTree
> 6 silly install readLocalPackageData
> 7 silly fetchPackageMetaData @types/react
> 8 silly fetchNamedPackageData @types/react
> 9 silly mapToRegistry name @types/react
> 10 silly mapToRegistry scope (from package name) @types
> 11 verbose mapToRegistry no registry URL found in name for scope @types
> 12 silly mapToRegistry using default registry
> 13 silly mapToRegistry registry https://registry.npmjs.org/
> 14 silly mapToRegistry data Result {
> 14 silly mapToRegistry   raw: '@types/react',
> 14 silly mapToRegistry   scope: '@types',
> 14 silly mapToRegistry   escapedName: '@types%2freact',
> 14 silly mapToRegistry   name: '@types/react',
> 14 silly mapToRegistry   rawSpec: '',
> 14 silly mapToRegistry   spec: 'latest',
> 14 silly mapToRegistry   type: 'tag' }
> 15 silly mapToRegistry uri https://registry.npmjs.org/@types%2freact
> 16 verbose request uri https://registry.npmjs.org/@types%2freact
> 17 verbose request no auth needed
> 18 info attempt registry request try #1 at 3:31:41 PM
> 19 verbose request id b7c3c7d689f93b39
> 20 verbose etag "1SUILKJVEI1ABV5VBSANQUB2I"
> 21 http request GET https://registry.npmjs.org/@types%2freact
> 22 http 304 https://registry.npmjs.org/@types%2freact
> 23 verbose headers { 'cache-control': 'max-age=0',
> 23 verbose headers   'accept-ranges': 'bytes',
> 23 verbose headers   date: 'Wed, 09 Nov 2016 23:31:41 GMT',
> 23 verbose headers   via: '1.1 varnish',
> 23 verbose headers   connection: 'keep-alive',
> 23 verbose headers   'x-served-by': 'cache-sea1924-SEA',
> 23 verbose headers   'x-cache': 'MISS',
> 23 verbose headers   'x-cache-hits': '0',
> 23 verbose headers   'x-timer': 'S1478734301.450320,VS0,VE20',
> 23 verbose headers   vary: 'Accept-Encoding' }
> 24 silly get cb [ 304,
> 24 silly get   { 'cache-control': 'max-age=0',
> 24 silly get     'accept-ranges': 'bytes',
> 24 silly get     date: 'Wed, 09 Nov 2016 23:31:41 GMT',
> 24 silly get     via: '1.1 varnish',
> 24 silly get     connection: 'keep-alive',
> 24 silly get     'x-served-by': 'cache-sea1924-SEA',
> 24 silly get     'x-cache': 'MISS',
> 24 silly get     'x-cache-hits': '0',
> 24 silly get     'x-timer': 'S1478734301.450320,VS0,VE20',
> 24 silly get     vary: 'Accept-Encoding' } ]
> 25 verbose etag https://registry.npmjs.org/@types%2freact from cache
> 26 verbose get saving @types/react to /Users/anandsainath/.npm/registry.npmjs.org/_40types_252freact/.cache.json
> 27 verbose correctMkdir /Users/anandsainath/.npm correctMkdir not in flight; initializing
> 28 silly install normalizeTree
> 29 silly loadCurrentTree Finishing
> 30 silly loadIdealTree Starting
> 31 silly install loadIdealTree
> 32 silly cloneCurrentTree Starting
> 33 silly install cloneCurrentTreeToIdealTree
> 34 silly cloneCurrentTree Finishing
> 35 silly loadShrinkwrap Starting
> 36 silly install loadShrinkwrap
> 37 silly loadShrinkwrap Finishing
> 38 silly loadAllDepsIntoIdealTree Starting
> 39 silly install loadAllDepsIntoIdealTree
> 40 silly resolveWithNewModule @types/react@0.14.46 checking installable status
> 41 silly cache add args [ '@types/react', null ]
> 42 verbose cache add spec @types/react
> 43 silly cache add parsed spec Result {
> 43 silly cache add   raw: '@types/react',
> 43 silly cache add   scope: '@types',
> 43 silly cache add   escapedName: '@types%2freact',
> 43 silly cache add   name: '@types/react',
> 43 silly cache add   rawSpec: '',
> 43 silly cache add   spec: 'latest',
> 43 silly cache add   type: 'tag' }
> 44 silly addNamed @types/react@latest
> 45 verbose addNamed "latest" is being treated as a dist-tag for @types/react
> 46 info addNameTag [ '@types/react', 'latest' ]
> 47 silly mapToRegistry name @types/react
> 48 silly mapToRegistry scope (from package name) @types
> 49 verbose mapToRegistry no registry URL found in name for scope @types
> 50 silly mapToRegistry using default registry
> 51 silly mapToRegistry registry https://registry.npmjs.org/
> 52 silly mapToRegistry data Result {
> 52 silly mapToRegistry   raw: '@types/react',
> 52 silly mapToRegistry   scope: '@types',
> 52 silly mapToRegistry   escapedName: '@types%2freact',
> 52 silly mapToRegistry   name: '@types/react',
> 52 silly mapToRegistry   rawSpec: '',
> 52 silly mapToRegistry   spec: 'latest',
> 52 silly mapToRegistry   type: 'tag' }
> 53 silly mapToRegistry uri https://registry.npmjs.org/@types%2freact
> 54 verbose addNameTag registry:https://registry.npmjs.org/@types%2freact not in flight; fetching
> 55 verbose get https://registry.npmjs.org/@types%2freact not expired, no request
> 56 silly addNameTag next cb for @types/react with tag latest
> 57 silly addNamed @types/react@0.14.46
> 58 verbose addNamed "0.14.46" is a plain semver version for @types/react
> 59 silly rollbackFailedOptional Starting
> 60 silly rollbackFailedOptional Finishing
> 61 silly runTopLevelLifecycles Finishing
> 62 silly install printInstalled
> 63 verbose stack Error: Invalid name: "@types/react"
> 63 verbose stack     at ensureValidName (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:302:15)
> 63 verbose stack     at Object.fixNameField (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:206:5)
> 63 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:29:38
> 63 verbose stack     at Array.forEach (native)
> 63 verbose stack     at normalize (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:28:15)
> 63 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:349:5)
> 63 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:124:5)
> 63 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:214:31
> 63 verbose stack     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)
> 63 verbose stack     at Glob.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/glob/glob.js:146:7)
> 64 verbose cwd /Users/anandsainath/!Works/gitlab/CricketStories
> 65 error Darwin 16.1.0
> 66 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "@types/react"
> 67 error node v6.9.1
> 68 error npm  v3.10.8
> 69 error Invalid name: "@types/react"
> 70 error If you need help, you may report this error at:
> 70 error     <https://github.com/npm/npm/issues>
> 71 verbose exit [ 1, true ]

**Comment by legodude17** [comment]
Can you try updating to `npm@4.0.2`?

**Comment by anandsainath** [comment]
@legodude17 updating to 4.0.2 works! Thanks!

**Comment by Dierk** [comment]
how do I update to 4.0.2?

sudo npm install -g npm

gives me 3.10.9

**Comment by anandsainath** [comment]
Try 'npm install -g npm@4.0.2'

**Comment by Dierk** [comment]
awesome, thanks!

**Comment by mailaneel** [comment]
If you are running your own private registry

`npm config set @types:registry  https://registry.npmjs.org/`

**Comment by JciGi** [comment]
Thanks @mailaneel ,I forgot my registry was change to private registry,I change it back and everything is OK!Thanks!
