### ISSUE TITLE
prepublishOnly environment variable not include node_modules/.bin 

### ISSUE THREAD

**Issue by leecade** [npm/npm#14493]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?

prepublishOnly environment variable not include `node_modules/.bin`

#### How can the CLI team reproduce the problem?

```sh
$ npm init -y
$ mkdir node_modules/.bin
$ echo "#\!/usr/bin/env node\nconsole.log('output')" > node_modules/.bin/test-build
```

`package.json`

```json
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "test-build",
    "prepublishOnly": "npm run build"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}
```

Run `npm run build` got the right outout:

```
❯ npm run build

> test@1.0.0 build /Users/yuji/tmp/test
> test-build

output
```

but, run `npm publish` not found the `test-build` command

```
❯ npm publish

> test@1.0.0 prepublishOnly /Users/yuji/.npm/test/1.0.0/package
> npm run build


> test@1.0.0 build /Users/yuji/.npm/test/1.0.0/package
> test-build

sh: test-build: command not found

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/Cellar/node/6.8.1/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v6.8.1
npm ERR! npm  v4.0.1
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! test@1.0.0 build: `test-build`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the test@1.0.0 build script 'test-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the test package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     test-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs test
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls test
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/yuji/.npm/test/1.0.0/package/npm-debug.log

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/Cellar/node/6.8.1/bin/node" "/usr/local/bin/npm" "publish"
npm ERR! node v6.8.1
npm ERR! npm  v4.0.1
npm ERR! code ELIFECYCLE
npm ERR! test@1.0.0 prepublishOnly: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the test@1.0.0 prepublishOnly script 'npm run build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the test package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs test
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls test
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/yuji/tmp/test/npm-debug.log
```

### supporting information:

 - `npm -v` prints:
4.0.1
 - `node -v` prints:
v6.8.1
 - `npm config get registry` prints:
https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?:
macOS

**Comment by iarna** [comment]
This revealed a long standing bug in how `publish` and `postpublish` lifecycles worked, in addition to the new `prepublishOnly` lifecycle.  This was due to code trying to support the `npm publish path/to/tarball.tar.gz` and `npm publish https://host/path/tarball.tar.gz` use cases.

After discussion within the cli team, our conclusion is that `prepublishOnly`, `publish` and `postpublish` shouldn't be running if installing from a tarball or URL and should only run for locally developed packages. To implement this, we'll modify `cacheAddPublish` in `lib/publish.js`, or possibly inline it into its caller. Either way the `didPre` flag should go away.

**Comment by leecade** [comment]
@iarna thanks for your replay, I am very glad to know that cli team started to discuss the publish hook behavior, previously `prepublish` make most people confusing, so `prepublishOnly` is a clearly way, after viewing the source code, I noticed that the default hook create a cache folder and switch directory into it.

Without `npm install` we lost the bin PATH cause the hook script not found commands, In my option `prepublishOnly` behavior should keep simple, the most commonly used are lint, `version patch` and local build, that is enough.

**Comment by iarna** [comment]
@leecade Yeah, the problem was that it _shouldn't_ have been switching to the cache folder in the first place.
