### ISSUE TITLE
"npm search term" results in FATAL ERROR

### ISSUE THREAD

**Issue by scottrudy** [npm/npm#14498]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Search seemed to work, until yesterday when I updated to npm 4.0.1, but I have since downgraded
When I search for a package, I 
- Get an error: "Cannot read property '_updated' of undefined"
- NPM tries to rebuild the search index
- NPM crashes with: "FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory"

I have tried
- `npm clear cache`
- Uninstalling npm and node, along with deleting all /user files
  - verified `c:\program files\nodejs`
  - manually deleted `c:\users\scrudy\appdata\roaming\npm`
  - manually deleted `c:\users\scrudy\appdata\npm-cache`
  - manually deleted `.npmrc` and `.node_repl_history` from `c:\users\scrudy`
- overwriting to a previous version of npm back to 3.9
  - `npm i npm@3.9 -g`
- several reboots

#### How can the CLI team reproduce the problem?
Type `npm search _someterm_`
 https://gist.github.com/scottrudy/a658ce88b66f035ff9cbce7831f8ebde

### supporting information:
 - `npm -v` prints: 3.10.9
 - `node -v` prints: v6.9.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows 10
 - Network issues: N/A
   - Geographic location where npm was run: Baltimore, MD
 - Container: N/A

**Comment by legodude17** [comment]
Try updating `npm` to `4.0.1`.

**Comment by scottrudy** [comment]
`> npm -i npm@4.0.1 -g`
`> npm cache clear`

Fixed
