### ISSUE TITLE
shasum check failed for core-js-2.4.1.tgz

### ISSUE THREAD

**Issue by JigyasaSharma** [npm/npm#14491]
#### I'm opening this issue because:

  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Angular-cli install fails with 

npm ERR! shasum check failed for AppData\Local\Temp\npm-7664-b202cd27\registry.npmjs.org\core-js\-\core-js-2.4.1.tgz

#### How can the CLI team reproduce the problem?
Not sure - I have cleared cache; changed registry from https to http; uninstalled and installed npm too - nothing seems to help. 

### supporting information:

 - `npm -v` prints: 3.10.8
 - `node -v` prints: v6.9.1
 - `npm config get registry` prints: http://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows_NT 6.1.7601
 - Network issues:
   - Geographic location where npm was run: Melbourbne
   - [ ] I use a proxy to connect to the npm registry. 
  

Logs: (D:\npm-debug.log does not exist)

  npm verb afterAdd C:\Users\sharmaj\AppData\Roaming\npm-cache\awesome-typescript-loader\2.2.4\package\package.json written
npm verb stack Error: shasum check failed for C:\Users\sharmaj\AppData\Local\Temp\npm-7664-b202cd27\registry.npmjs.org\core-js\-\core-js-2.4.1.tgz
npm verb stack Expected: 4de911e667b0eae9124e34254b53aea6fc618d3e
npm verb stack Actual:   848d85080c263e8cf328d4be826c81e84954e29c
npm verb stack From:     http://registry.npmjs.org/core-js/-/core-js-2.4.1.tgz
npm verb stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:25:8
npm verb stack     at ReadStream.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:72:7)
npm verb stack     at emitNone (events.js:91:20)
npm verb stack     at ReadStream.emit (events.js:185:7)
npm verb stack     at endReadableNT (_stream_readable.js:974:12)
npm verb stack     at _combinedTickCallback (internal/process/next_tick.js:74:11)
npm verb stack     at process._tickCallback (internal/process/next_tick.js:98:9)
npm verb cwd D:\
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "-f" "angular-cli@latest" "--verbose"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8

npm ERR! shasum check failed for C:\Users\sharmaj\AppData\Local\Temp\npm-7664-b202cd27\registry.npmjs.org\core-js\-\core-js-2.4.1.tgz
npm ERR! Expected: 4de911e667b0eae9124e34254b53aea6fc618d3e
npm ERR! Actual:   848d85080c263e8cf328d4be826c81e84954e29c
npm ERR! From:     http://registry.npmjs.org/core-js/-/core-js-2.4.1.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm verb exit [ 1, true ]

npm ERR! Please include the following file with any support request:
npm ERR!     D:\npm-debug.log

**Comment by sabdelrehim** [comment]
Hi, did you solve this problem? How?

**Comment by JigyasaSharma** [comment]
Hi sabdelrehim,

I changed my source registry from http to https and the shasum error did not appear again.
