### ISSUE TITLE
With engine-strict, npm i --dry-run passes but npm i fails

### ISSUE THREAD

**Issue by pgarrison** [npm/npm#14494]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Set `engine-strict` to true. Require an older version of node in `package.json`. Then `npm i --dry-run` is successful (exit code 0), but `npm i` errors, as it should. I expect `npm i --dry-run` to catch the issue that `npm i` does. Note that `npm i --dry-run` does fail appropriately when _dependencies_ have engine issues.

#### How can the CLI team reproduce the problem?
Follow the log in [this gist](https://gist.github.com/pgarrison/4b7243e7931b541b6d3f24d5015b579c)

### supporting information:

 - `npm -v` prints: 4.0.1
 - `node -v` prints: v6.8.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: linux
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
That seems very odd. My guess is that it checks the `engine-strict` as it is manipulating files, but I don't know for sure.

**Comment by legodude17** [comment]
Just looked over the log, it checks the engine as it prints out the install. That is very odd. I would think it should check that first.

**Comment by pgarrison** [comment]
Looks like this will be fixed by #15092 :100:
