### ISSUE TITLE
Unpublish package simple-sparql-client

### ISSUE THREAD

**Issue by IvanMarcialis** [npm/npm#14495]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'unpublish',
1 verbose cli   'simple-sparql-client',
1 verbose cli   '--force' ]
2 info using npm@3.10.8
3 info using node@v7.0.0
4 verbose config Skipping project config: /Users/ivan/.npmrc. (matches userconfig)
5 warn using --force I sure hope you know what you are doing.
6 silly unpublish args[0] simple-sparql-client
7 silly unpublish thing Result {
7 silly unpublish   raw: 'simple-sparql-client',
7 silly unpublish   scope: null,
7 silly unpublish   escapedName: 'simple-sparql-client',
7 silly unpublish   name: 'simple-sparql-client',
7 silly unpublish   rawSpec: '',
7 silly unpublish   spec: 'latest',
7 silly unpublish   type: 'tag' }
8 verbose getPublishConfig null
9 silly ls normalized simple-sparql-client
10 silly gentlyRm /Users/ivan/.npm/simple-sparql-client is being purged
11 verbose gentlyRm don't care about contents; nuking /Users/ivan/.npm/simple-sparql-client
12 silly mapToRegistry name simple-sparql-client
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry data Result {
15 silly mapToRegistry   raw: 'simple-sparql-client',
15 silly mapToRegistry   scope: null,
15 silly mapToRegistry   escapedName: 'simple-sparql-client',
15 silly mapToRegistry   name: 'simple-sparql-client',
15 silly mapToRegistry   rawSpec: '',
15 silly mapToRegistry   spec: 'latest',
15 silly mapToRegistry   type: 'tag' }
16 silly mapToRegistry uri https://registry.npmjs.org/simple-sparql-client
17 verbose get GET as part of write; not caching result
18 verbose request uri https://registry.npmjs.org/simple-sparql-client?write=true
19 verbose request no auth needed
20 info attempt registry request try #1 at 1:05:20 PM
21 verbose request using bearer token for auth
22 verbose request id bb4a720bea284312
23 http request GET https://registry.npmjs.org/simple-sparql-client?write=true
24 http 200 https://registry.npmjs.org/simple-sparql-client?write=true
25 verbose headers { server: 'CouchDB/1.6.1 (Erlang OTP/R16B03)',
25 verbose headers   etag: '"C66J3RG73BY6HY78QCLE4AYXZ"',
25 verbose headers   'content-type': 'application/json',
25 verbose headers   'content-encoding': 'gzip',
25 verbose headers   'cache-control': 'max-age=0',
25 verbose headers   'transfer-encoding': 'chunked',
25 verbose headers   'accept-ranges': 'bytes',
25 verbose headers   date: 'Wed, 02 Nov 2016 12:05:20 GMT',
25 verbose headers   via: '1.1 varnish',
25 verbose headers   connection: 'keep-alive',
25 verbose headers   'x-served-by': 'cache-cdg8723-CDG',
25 verbose headers   'x-cache': 'MISS',
25 verbose headers   'x-cache-hits': '0',
25 verbose headers   'x-timer': 'S1478088320.357564,VS0,VE406',
25 verbose headers   vary: 'Accept-Encoding' }
26 silly get cb [ 200,
26 silly get   { server: 'CouchDB/1.6.1 (Erlang OTP/R16B03)',
26 silly get     etag: '"C66J3RG73BY6HY78QCLE4AYXZ"',
26 silly get     'content-type': 'application/json',
26 silly get     'content-encoding': 'gzip',
26 silly get     'cache-control': 'max-age=0',
26 silly get     'transfer-encoding': 'chunked',
26 silly get     'accept-ranges': 'bytes',
26 silly get     date: 'Wed, 02 Nov 2016 12:05:20 GMT',
26 silly get     via: '1.1 varnish',
26 silly get     connection: 'keep-alive',
26 silly get     'x-served-by': 'cache-cdg8723-CDG',
26 silly get     'x-cache': 'MISS',
26 silly get     'x-cache-hits': '0',
26 silly get     'x-timer': 'S1478088320.357564,VS0,VE406',
26 silly get     vary: 'Accept-Encoding' } ]
27 verbose get saving simple-sparql-client to /Users/ivan/.npm/registry.npmjs.org/simple-sparql-client_3Fwrite_3Dtrue/.cache.json
28 verbose correctMkdir /Users/ivan/.npm correctMkdir not in flight; initializing
29 info unpublish No version specified, removing all
30 verbose request uri https://registry.npmjs.org/simple-sparql-client/-rev/7-3e4ef1b5f7461a51deb20b3f9cba67c1
31 verbose request sending authorization for write operation
32 info attempt registry request try #1 at 1:05:20 PM
33 verbose request using bearer token for auth
34 http request DELETE https://registry.npmjs.org/simple-sparql-client/-rev/7-3e4ef1b5f7461a51deb20b3f9cba67c1
35 http 400 https://registry.npmjs.org/simple-sparql-client/-rev/7-3e4ef1b5f7461a51deb20b3f9cba67c1
36 verbose headers { 'content-type': 'application/json',
36 verbose headers   'cache-control': 'max-age=300',
36 verbose headers   'content-length': '17',
36 verbose headers   'accept-ranges': 'bytes',
36 verbose headers   date: 'Wed, 02 Nov 2016 12:05:21 GMT',
36 verbose headers   via: '1.1 varnish',
36 verbose headers   connection: 'keep-alive',
36 verbose headers   'x-served-by': 'cache-cdg8723-CDG',
36 verbose headers   'x-cache': 'MISS',
36 verbose headers   'x-cache-hits': '0',
36 verbose headers   'x-timer': 'S1478088320.814114,VS0,VE668',
36 verbose headers   vary: 'Accept-Encoding' }
37 verbose request invalidating /Users/ivan/.npm/registry.npmjs.org/simple-sparql-client on DELETE
38 verbose stack Error: Registry returned 400 for DELETE on https://registry.npmjs.org/simple-sparql-client/-rev/7-3e4ef1b5f7461a51deb20b3f9cba67c1
38 verbose stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:302:12)
38 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:280:14)
38 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:210:14)
38 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:187:22)
38 verbose stack     at emitTwo (events.js:106:13)
38 verbose stack     at Request.emit (events.js:191:7)
38 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1044:10)
38 verbose stack     at emitOne (events.js:96:13)
38 verbose stack     at Request.emit (events.js:188:7)
38 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:965:12)
39 verbose statusCode 400
40 verbose pkgid simple-sparql-client
41 verbose cwd /Users/ivan
42 error Darwin 16.1.0
43 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "unpublish" "simple-sparql-client" "--force"
44 error node v7.0.0
45 error npm  v3.10.8
46 error code E400
47 error Registry returned 400 for DELETE on https://registry.npmjs.org/simple-sparql-client/-rev/7-3e4ef1b5f7461a51deb20b3f9cba67c1
48 error If you need help, you may report this error at:
48 error     <https://github.com/npm/npm/issues>
49 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@IvanMarcialis You should email `support@npmjs.com` for package unpublishes, as-per the [unpublish policy](http://blog.npmjs.org/post/141905368000/changes-to-npms-unpublish-policy).
