### ISSUE TITLE
Cannot find module 'sshpk' - All NPM projects

### ISSUE THREAD

**Issue by yarnball** [npm/npm#14492]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Hi, 

I cannot install any node projects (either globally, or on an individual directory). I've tried several projects, and doing ```npm install -g``` globally. It all renders the same error.

I'm am on NPM v3.10.8 using OSX 10.12

It renders the error : ```Cannot find module 'sshpk'```
#### How can the CLI team reproduce the problem?

I cannot establish what trigged this problem. It *might* have been when I wrote attempted to do ```npm i --save lodash``` but I cannot be certain.

I have been using node for several months on several projects without issue. 

I tried uninstall NPM globally (```sudo npm uninstall npm -g```) but that gave the same error

What is my best approach here?

### supporting information:
```
Error: Cannot find module 'sshpk'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/lib/utils.js:4:13)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'sshpk'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

-->

**Comment by jagzviruz** [comment]
Got this error when I ran `npm install npm@4 -g` .. Am regretting upgrade to node v7.0.0 now 👎

**Comment by legodude17** [comment]
This is probably an issue with an incorrect install. Try removing all of `npm` and then reinstall `npm`.

**Comment by snopeks** [comment]
@yarnball Hi there, it looks like your npm was installed improperly, so we recommend installing npm from scratch again using `curl -L https://npmjs.org/install.sh | sh` . Could you try that and let us know if it resolves the issue? Thanks!

**Comment by yarnball** [comment]
@snopeks The problem was- even trying to uninstall rendered that error.

So, using a technique I found I had to remove all node using: 

```lsbom -f -l -s -pf /var/db/receipts/org.nodejs.node.pkg.bom | while read f; do sudo rm /usr/local/${f}; done```

```sudo rm -rf /usr/local/lib/node /usr/local/lib/node_modules /var/db/receipts/org.nodejs.*```

I then used NVM to re-install Node

And success it seems!

**Comment by legodude17** [comment]
Anyone still having the issue?

**Comment by atfergus** [comment]
Reinstalling npm fixed the issue for me as well

**Comment by legodude17** [comment]
Cool, this can be closed. Can you do that @KenanY?
