### ISSUE TITLE
default npm-start to running the package's `bin`

### ISSUE THREAD

**Issue by jasonkarns** [npm/npm#14490]
Feature request:

Default `npm start` to executing the single `bin` as specified in package.json: https://docs.npmjs.com/files/package.json#bin

Virtually every npm start script I've ever seen is essentially `node lib/server.js` or similar. In the majority of cases, the script that is started this way is also listed as the only `bin` in the package. Since it usually only makes sense to 'start' servers and/or apps as, these same types of packages typically only have a single binary. As opposed to libs which may have more than one binary, but rarely have a 'start' script.

This is not a blocking feature, but could simplify a good many applications' package.json file. The start script could be removed and simply be inferred by the (usually already existing) `bin` property.

**Comment by legodude17** [comment]
This seems like a quite good idea. I am wondering how this would affect CLIs though.

**Comment by jasonkarns** [comment]
@legodude17 Packages that have an explicit `start` script defined will function as normal (this is only meant as a default).  Packages that don't have a `start` script and don't have a `bin` won't be affected. Only packages that don't have a `start` script but _do_ have a `bin` will be affected, (suddenly having a default `npm-start` behavior). So I don't think this would affect CLIs in any meaningful way (certainly not any differently from apps or libs).

One other wrinkle that shouldn't be forgotten: npm defaults a string value of `bin` to be an object mapping where the key for the bin is actually the package name. The same rule could be applied when there is >1 bin listed.

ie pseudo-code:

``
pkg = normalizedPackageJson(require('package'))

if (!pkg.scripts.start) {
  pkg.scripts.start = pkg.bin[pkg.name]
}
```

**Comment by legodude17** [comment]
What about where the `pkg.bin[pkg.name]` is undefined? What do you think it should do then? I think it should just error and bail out.

**Comment by jasonkarns** [comment]
> Packages that don't have a start script and don't have a bin won't be affected.

It shouldn't define a start script if there's no bin.

**Comment by legodude17** [comment]
That is not what I meant. What if there is no start script or bin? What will happen then?

> It shouldn't define a start script if there's no bin.

What do you mean? It seems like you should define start script if there is no bin. I do that all the time.

**Comment by jasonkarns** [comment]
"It" meaning npm. This feature will automatically define a start script (*if none is already defined in the package*) that is the equivalent of invoking the package-named bin. If there is no bin, there is nothing to run, so it shouldn't define anything.

decision tree:

-  package.json already has a start script defined: nothing changes (user-defined start script is unmodified)
- package.json does not have a bin: nothing changes (`npm-start` runs the user-defined start script if defined; otherwise does nothing as it does now)
- package.json has bins listed but none named per the package name: nothing changes (`npm-start` runs the user-defined start script if defined; otherwise does nothing as it does now)

Only this case behaves differently:
- package.json has a package-named bin *and* no user-defined start script is defined: a default start script is defined in its place that is the equivalent of running the package-named bin

**Comment by legodude17** [comment]
Thank you for laying that out @jasonkarns, I agree that that is a good default. It seems to be quite easy to implement.

**Comment by jasonkarns** [comment]
Yeah, personally I think it ought to go in https://github.com/npm/normalize-package-data/ as part of the script normalization process. (That's where most other defaulting occurs, anyway) It would mean that `npm-run` emits the "defaulted" start script in its output and also eliminates the need to alter code for the actual `npm-start` command.

**Comment by legodude17** [comment]
What do you think @zkat? Should this go in here or in `normalize-package-data`?
