### ISSUE TITLE
npm doesn't start when installed in other drive

### ISSUE THREAD

**Issue by kiiru501** [npm/npm#14507]
I am unable to run **npm start** on my PC and am thinking its because its installed on another drive, which is my primary for win 7. 
every time i execute an npm command I get this error. 
![pin5](https://cloud.githubusercontent.com/assets/4168690/19953653/8450c212-a181-11e6-877f-0e594d5f662e.PNG)
![pin4](https://cloud.githubusercontent.com/assets/4168690/19953663/9ebf2c2e-a181-11e6-9f60-6b851f8804f4.PNG)

Because of this, I am unable to run **npm start**

please help

**Comment by legodude17** [comment]
It looks like it is working fine. What is the problem?

**Comment by kiiru501** [comment]
I keep getting this error

![cap1](https://cloud.githubusercontent.com/assets/4168690/19978139/f0e9173c-a206-11e6-857f-bf1bb5f50d31.PNG)

**Comment by legodude17** [comment]
As the error message says, this is most likely a problem with the package you are using, and not `npm`.

**Comment by kiiru501** [comment]
i've even tried removing **tsc &&** from package.json but it still doesnt work.
![cap2](https://cloud.githubusercontent.com/assets/4168690/19978353/b91d533a-a207-11e6-8f37-6fb6e355339f.PNG)

**Comment by kiiru501** [comment]
here is my npm debug.log

0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.8
3 info using node@v7.0.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle angulartrial@1.0.0~prestart: angulartrial@1.0.0
6 silly lifecycle angulartrial@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle angulartrial@1.0.0~start: angulartrial@1.0.0
8 verbose lifecycle angulartrial@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle angulartrial@1.0.0~start: PATH: D:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;D:\Users\Joseph Kiiru\Desktop\angulartrial\node_modules\.bin;D:\ProgramData\Oracle\Java\javapath;D:\Users\Joseph Kiiru\AppData\Local\Programs\Python\Python35-32;D:\windows\system32 ;D:\Windows\system32\config\systemprofile\.dnx\bin;D:\Program Files\Microsoft DNX\Dnvm\;D:\Program Files\Microsoft SQL Server\120\Tools\Binn\;D:\Program Files\Microsoft SQL Server\130\Tools\Binn\;D:\Program Files\nodejs;D:\Windows\system32;D:\Program Files (x86)\Microsoft VS Code\bin;D:\Program Files\Git\bin;D:\Users\Joseph Kiiru\AppData\Roaming\npm
10 verbose lifecycle angulartrial@1.0.0~start: CWD: D:\Users\Joseph Kiiru\Desktop\angulartrial
11 silly lifecycle angulartrial@1.0.0~start: Args: [ '/d /s /c', 'concurrent "tsc -w" "lite-server" ' ]
12 info lifecycle angulartrial@1.0.0~start: Failed to exec start script
13 verbose stack Error: angulartrial@1.0.0 start: `concurrent "tsc -w" "lite-server" `
13 verbose stack spawn D:\Windows\system32  ENOENT
13 verbose stack     at exports._errnoException (util.js:1026:11)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
13 verbose stack     at onErrorNT (internal/child_process.js:359:16)
13 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:74:11)
13 verbose stack     at process._tickCallback (internal/process/next_tick.js:98:9)
14 verbose pkgid angulartrial@1.0.0
15 verbose cwd D:\Users\Joseph Kiiru\Desktop\angulartrial
16 error Windows_NT 6.1.7601
17 error argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 error node v7.0.0
19 error npm  v3.10.8
20 error file D:\Windows\system32
21 error path D:\Windows\system32
22 error code ELIFECYCLE
23 error errno ENOENT
24 error syscall spawn D:\Windows\system32
25 error angulartrial@1.0.0 start: `concurrent "tsc -w" "lite-server" `
25 error spawn D:\Windows\system32  ENOENT
26 error Failed at the angulartrial@1.0.0 start script 'concurrent "tsc -w" "lite-server" '.
26 error Make sure you have the latest version of node.js and npm installed.
26 error If you do, this is most likely a problem with the angulartrial package,
26 error not with npm itself.
26 error Tell the author that this fails on your system:
26 error     concurrent "tsc -w" "lite-server"
26 error You can get information on how to open an issue for this project with:
26 error     npm bugs angulartrial
26 error Or if that isn't available, you can get their info via:
26 error     npm owner ls angulartrial
26 error There is likely additional logging output above.
27 verbose exit [ 1, true ]

**Comment by legodude17** [comment]
Didn't you mean `concurrently` not `concurrent`?
