### ISSUE TITLE
npm refuses to install

### ISSUE THREAD

**Issue by yeshahya** [npm/npm#14504]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):
[npm-debug.docx](https://github.com/npm/npm/files/567943/npm-debug.docx)
[npm-debug.docx](https://github.com/npm/npm/files/567944/npm-debug.docx)

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [x] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
Please edit your comment and fill out all the fields on the issue template.

**Comment by yeshahya** [comment]
this my first time using Git so please bare with me!

**Comment by legodude17** [comment]
What is the error? Please put `npm-debug.log` in a [gist](https://gist.github.com) and post the link. Also provide the results of the commands `npm -v`, `node -v`, and `npm config get registry`.

**Comment by zkat** [comment]
Closing as a duplicate of https://github.com/npm/npm/issues/14626
