### ISSUE TITLE
npm ERR! addLocal Could not install FreeBSD 11 Jail

### ISSUE THREAD

**Issue by scruffydan** [npm/npm#14508]
When I run `npm upgrade -g` in a FreeBSD 11 jail I get the following error:  

`npm ERR! addLocal Could not install /construction/xports/www/npm/work/npm-3.10.9`

I am running the latest version of node from the ports tree which is currently 6.9.1, and npm is at version 3.10.9

Any help would be appreciated.

Thanks

**Comment by legodude17** [comment]
`npm upgrade -g` is a bit of a footgun and should normally not be used. Please use [this script](https://gist.github.com/othiym23/4ac31155da23962afd0e).

**Comment by dmoutal** [comment]
Looks like the script uses `npm outdated -g`
Unfortunately when I try to run that command I get the same error:
`npm ERR! addLocal Could not install /construction/xports/www/npm/work/npm-3.10.9`

**Comment by legodude17** [comment]
Can you put the full `npm-debug.log` in a gist and then post the link?

**Comment by dmoutal** [comment]
sorry, I have been away and unable to test further. What is te best way to generate the `npm-debug.log`?

**Comment by legodude17** [comment]
Just run the command again.

**Comment by dmoutal** [comment]
This is the only output:
`npm ERR! addLocal Could not install /construction/xports/www/npm/work/npm-3.10.9`

**Comment by legodude17** [comment]
What do you mean? Is there a `npm-debug.log` in the directory that you ran the command in?

**Comment by dmoutal** [comment]
Exactly. I am running npm with the `-g-` flag so perhaps the file is somewhere else?
