### ISSUE TITLE
error while down loading bower

### ISSUE THREAD

**Issue by mhdayyoob** [npm/npm#14511]
if i download bower these following errors are showing

 tar.unpack error reading C:\Users\shafi\bower
 addLocal Could not install C:\Users\shafi\bower
 Windows_NT 6.2.9200
 argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\shafi\\AppData\\
\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "bower"
 node v4.4.7
 npm  v3.7.1

 0-byte tarball
 Please run `npm cache clean`

 If you need help, you may report this error at:
     <https://github.com/npm/npm/issues>

 Please include the following file with any support request:
     C:\Users\shafi\npm-debug.log

**Comment by KenanY** [comment]
@mhdayyoob Did you try running `npm cache clean` as the error message suggests?

**Comment by mhdayyoob** [comment]
yes but it's not working again the same error is showing

**Comment by legodude17** [comment]
You could also try updating `npm` to the latest version (`4.0.2` (or to `3.10.10` if you want to stay with `npm@3`)).

**Comment by KenanY** [comment]
Closing as abandoned.
