### ISSUE TITLE
npm ERR! Error: No compatible version found: chalk@'^1.1.1'

### ISSUE THREAD

**Issue by schwermie** [npm/npm#14517]
#### I'm opening this issue because:

- npm is crashing.
  
#### What's going wrong?
Trying to install homebridge software on a raspberry pi with Domoticz results in an error
I used this manual https://www.domoticz.com/wiki/Homekit_Siri

#### How can the CLI team reproduce the problem?

Output on screen:
npm http 304 https://registry.npmjs.org/hap-nodejs/0.4.12
npm ERR! Error: No compatible version found: chalk@'^1.1.1'
npm ERR! Valid install targets:
npm ERR! ["0.1.0","0.1.1","0.2.0","0.2.1","0.3.0","0.4.0","0.5.0","0.5.1","1.0.0","1.1.0","1.1.1","1.1.2","1.1.3"]
npm ERR!     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:682:10)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:597:10
npm ERR!     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:93:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.12.28+
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /home/pi/homebridge
npm ERR! node -v v0.10.0
npm ERR! npm -v 1.2.14
npm http 304 https://registry.npmjs.org/commander/2.8.1
npm http 304 https://registry.npmjs.org/semver/5.0.3
npm http 304 https://registry.npmjs.org/node-persist
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/homebridge/npm-debug.log
npm ERR! not ok code 0

npm-debug.log:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'install' ]
2 info using npm@1.2.14
3 info using node@v0.10.0
4 verbose read json /home/pi/homebridge/package.json
5 verbose readDependencies using package.json deps
6 verbose install where, deps [ '/home/pi/homebridge',
6 verbose install   [ 'chalk', 'commander', 'hap-nodejs', 'semver', 'node-persist' ] ]
7 verbose from cache /home/pi/homebridge/package.json
8 info preinstall homebridge@0.4.7
9 verbose from cache /home/pi/homebridge/package.json
10 verbose readDependencies using package.json deps
11 verbose cache add [ 'chalk@^1.1.1', null ]
12 verbose cache add name=undefined spec="chalk@^1.1.1" args=["chalk@^1.1.1",null]
13 verbose parsed url { protocol: null,
13 verbose parsed url   slashes: null,
13 verbose parsed url   auth: null,
13 verbose parsed url   host: null,
13 verbose parsed url   port: null,
13 verbose parsed url   hostname: null,
13 verbose parsed url   hash: null,
13 verbose parsed url   search: null,
13 verbose parsed url   query: null,
13 verbose parsed url   pathname: 'chalk@^1.1.1',
13 verbose parsed url   path: 'chalk@^1.1.1',
13 verbose parsed url   href: 'chalk@^1.1.1' }
14 verbose cache add name="chalk" spec="^1.1.1" args=["chalk","^1.1.1"]
15 verbose parsed url { protocol: null,
15 verbose parsed url   slashes: null,
15 verbose parsed url   auth: null,
15 verbose parsed url   host: null,
15 verbose parsed url   port: null,
15 verbose parsed url   hostname: null,
15 verbose parsed url   hash: null,
15 verbose parsed url   search: null,
15 verbose parsed url   query: null,
15 verbose parsed url   pathname: '^1.1.1',
15 verbose parsed url   path: '^1.1.1',
15 verbose parsed url   href: '^1.1.1' }
16 verbose addNamed [ 'chalk', '^1.1.1' ]
17 verbose addNamed [ null, null ]
18 verbose cache add [ 'commander@2.8.1', null ]
19 verbose cache add name=undefined spec="commander@2.8.1" args=["commander@2.8.1",null]
20 verbose parsed url { protocol: null,
20 verbose parsed url   slashes: null,
20 verbose parsed url   auth: null,
20 verbose parsed url   host: null,
20 verbose parsed url   port: null,
20 verbose parsed url   hostname: null,
20 verbose parsed url   hash: null,
20 verbose parsed url   search: null,
20 verbose parsed url   query: null,
20 verbose parsed url   pathname: 'commander@2.8.1',
20 verbose parsed url   path: 'commander@2.8.1',
20 verbose parsed url   href: 'commander@2.8.1' }
21 verbose cache add name="commander" spec="2.8.1" args=["commander","2.8.1"]
22 verbose parsed url { protocol: null,
22 verbose parsed url   slashes: null,
22 verbose parsed url   auth: null,
22 verbose parsed url   host: null,
22 verbose parsed url   port: null,
22 verbose parsed url   hostname: null,
22 verbose parsed url   hash: null,
22 verbose parsed url   search: null,
22 verbose parsed url   query: null,
22 verbose parsed url   pathname: '2.8.1',
22 verbose parsed url   path: '2.8.1',
22 verbose parsed url   href: '2.8.1' }
23 verbose addNamed [ 'commander', '2.8.1' ]
24 verbose addNamed [ '2.8.1', '2.8.1' ]
25 verbose cache add [ 'hap-nodejs@0.4.12', null ]
26 verbose cache add name=undefined spec="hap-nodejs@0.4.12" args=["hap-nodejs@0.4.12",null]
27 verbose parsed url { protocol: null,
27 verbose parsed url   slashes: null,
27 verbose parsed url   auth: null,
27 verbose parsed url   host: null,
27 verbose parsed url   port: null,
27 verbose parsed url   hostname: null,
27 verbose parsed url   hash: null,
27 verbose parsed url   search: null,
27 verbose parsed url   query: null,
27 verbose parsed url   pathname: 'hap-nodejs@0.4.12',
27 verbose parsed url   path: 'hap-nodejs@0.4.12',
27 verbose parsed url   href: 'hap-nodejs@0.4.12' }
28 verbose cache add name="hap-nodejs" spec="0.4.12" args=["hap-nodejs","0.4.12"]
29 verbose parsed url { protocol: null,
29 verbose parsed url   slashes: null,
29 verbose parsed url   auth: null,
29 verbose parsed url   host: null,
29 verbose parsed url   port: null,
29 verbose parsed url   hostname: null,
29 verbose parsed url   hash: null,
29 verbose parsed url   search: null,
29 verbose parsed url   query: null,
29 verbose parsed url   pathname: '0.4.12',
29 verbose parsed url   path: '0.4.12',
29 verbose parsed url   href: '0.4.12' }
30 verbose addNamed [ 'hap-nodejs', '0.4.12' ]
31 verbose addNamed [ '0.4.12', '0.4.12' ]
32 verbose cache add [ 'semver@5.0.3', null ]
33 verbose cache add name=undefined spec="semver@5.0.3" args=["semver@5.0.3",null]
34 verbose parsed url { protocol: null,
34 verbose parsed url   slashes: null,
34 verbose parsed url   auth: null,
34 verbose parsed url   host: null,
34 verbose parsed url   port: null,
34 verbose parsed url   hostname: null,
34 verbose parsed url   hash: null,
34 verbose parsed url   search: null,
34 verbose parsed url   query: null,
34 verbose parsed url   pathname: 'semver@5.0.3',
34 verbose parsed url   path: 'semver@5.0.3',
34 verbose parsed url   href: 'semver@5.0.3' }
35 verbose cache add name="semver" spec="5.0.3" args=["semver","5.0.3"]
36 verbose parsed url { protocol: null,
36 verbose parsed url   slashes: null,
36 verbose parsed url   auth: null,
36 verbose parsed url   host: null,
36 verbose parsed url   port: null,
36 verbose parsed url   hostname: null,
36 verbose parsed url   hash: null,
36 verbose parsed url   search: null,
36 verbose parsed url   query: null,
36 verbose parsed url   pathname: '5.0.3',
36 verbose parsed url   path: '5.0.3',
36 verbose parsed url   href: '5.0.3' }
37 verbose addNamed [ 'semver', '5.0.3' ]
38 verbose addNamed [ '5.0.3', '5.0.3' ]
39 verbose cache add [ 'node-persist@^0.0.8', null ]
40 verbose cache add name=undefined spec="node-persist@^0.0.8" args=["node-persist@^0.0.8",null]
41 verbose parsed url { protocol: null,
41 verbose parsed url   slashes: null,
41 verbose parsed url   auth: null,
41 verbose parsed url   host: null,
41 verbose parsed url   port: null,
41 verbose parsed url   hostname: null,
41 verbose parsed url   hash: null,
41 verbose parsed url   search: null,
41 verbose parsed url   query: null,
41 verbose parsed url   pathname: 'node-persist@^0.0.8',
41 verbose parsed url   path: 'node-persist@^0.0.8',
41 verbose parsed url   href: 'node-persist@^0.0.8' }
42 verbose cache add name="node-persist" spec="^0.0.8" args=["node-persist","^0.0.8"]
43 verbose parsed url { protocol: null,
43 verbose parsed url   slashes: null,
43 verbose parsed url   auth: null,
43 verbose parsed url   host: null,
43 verbose parsed url   port: null,
43 verbose parsed url   hostname: null,
43 verbose parsed url   hash: null,
43 verbose parsed url   search: null,
43 verbose parsed url   query: null,
43 verbose parsed url   pathname: '^0.0.8',
43 verbose parsed url   path: '^0.0.8',
43 verbose parsed url   href: '^0.0.8' }
44 verbose addNamed [ 'node-persist', '^0.0.8' ]
45 verbose addNamed [ null, null ]
46 silly lockFile b07b58bc-chalk-1-1-1 chalk@^1.1.1
47 verbose lock chalk@^1.1.1 /home/pi/.npm/b07b58bc-chalk-1-1-1.lock
48 silly lockFile 04a29799-commander-2-8-1 commander@2.8.1
49 verbose lock commander@2.8.1 /home/pi/.npm/04a29799-commander-2-8-1.lock
50 silly lockFile 0b3f8f5d-hap-nodejs-0-4-12 hap-nodejs@0.4.12
51 verbose lock hap-nodejs@0.4.12 /home/pi/.npm/0b3f8f5d-hap-nodejs-0-4-12.lock
52 silly lockFile 568aa47a-semver-5-0-3 semver@5.0.3
53 verbose lock semver@5.0.3 /home/pi/.npm/568aa47a-semver-5-0-3.lock
54 silly lockFile e162e901-node-persist-0-0-8 node-persist@^0.0.8
55 verbose lock node-persist@^0.0.8 /home/pi/.npm/e162e901-node-persist-0-0-8.lock
56 info addNameTag [ 'chalk', '^1.1.1' ]
57 info addNameTag [ 'node-persist', '^0.0.8' ]
58 verbose url raw chalk
59 verbose url resolving [ 'https://registry.npmjs.org/', './chalk' ]
60 verbose url resolved https://registry.npmjs.org/chalk
61 info trying registry request attempt 1 at 18:06:34
62 verbose etag "7BXCQUE1BZPPLCK8SY1D7NMGN"
63 http GET https://registry.npmjs.org/chalk
64 verbose url raw commander/2.8.1
65 verbose url resolving [ 'https://registry.npmjs.org/', './commander/2.8.1' ]
66 verbose url resolved https://registry.npmjs.org/commander/2.8.1
67 info trying registry request attempt 1 at 18:06:34
68 verbose etag "DI4LZWVXKHVEMV2F5AVHD8FPK"
69 http GET https://registry.npmjs.org/commander/2.8.1
70 verbose url raw hap-nodejs/0.4.12
71 verbose url resolving [ 'https://registry.npmjs.org/', './hap-nodejs/0.4.12' ]
72 verbose url resolved https://registry.npmjs.org/hap-nodejs/0.4.12
73 info trying registry request attempt 1 at 18:06:34
74 verbose etag "6T5B9NUN6FJIOFUOJEAI9V2JV"
75 http GET https://registry.npmjs.org/hap-nodejs/0.4.12
76 verbose url raw semver/5.0.3
77 verbose url resolving [ 'https://registry.npmjs.org/', './semver/5.0.3' ]
78 verbose url resolved https://registry.npmjs.org/semver/5.0.3
79 info trying registry request attempt 1 at 18:06:34
80 verbose etag "9EJY4LGTKOPUAAVLV2EPIIFIH"
81 http GET https://registry.npmjs.org/semver/5.0.3
82 verbose url raw node-persist
83 verbose url resolving [ 'https://registry.npmjs.org/', './node-persist' ]
84 verbose url resolved https://registry.npmjs.org/node-persist
85 info trying registry request attempt 1 at 18:06:34
86 verbose etag "4LGYH6HUHW09VVLS81ULK5Z4U"
87 http GET https://registry.npmjs.org/node-persist
88 http 304 https://registry.npmjs.org/chalk
89 silly registry.get cb [ 304,
89 silly registry.get   { date: 'Thu, 03 Nov 2016 17:06:36 GMT',
89 silly registry.get     via: '1.1 varnish',
89 silly registry.get     'cache-control': 'max-age=300',
89 silly registry.get     etag: '"7BXCQUE1BZPPLCK8SY1D7NMGN"',
89 silly registry.get     age: '40',
89 silly registry.get     connection: 'keep-alive',
89 silly registry.get     'x-served-by': 'cache-ams4134-AMS',
89 silly registry.get     'x-cache': 'HIT',
89 silly registry.get     'x-cache-hits': '1',
89 silly registry.get     'x-timer': 'S1478192796.892439,VS0,VE0',
89 silly registry.get     vary: 'Accept-Encoding' } ]
90 verbose etag chalk from cache
91 http 304 https://registry.npmjs.org/hap-nodejs/0.4.12
92 silly registry.get cb [ 304,
92 silly registry.get   { date: 'Thu, 03 Nov 2016 17:06:37 GMT',
92 silly registry.get     via: '1.1 varnish',
92 silly registry.get     'cache-control': 'max-age=300',
92 silly registry.get     etag: '"6T5B9NUN6FJIOFUOJEAI9V2JV"',
92 silly registry.get     age: '0',
92 silly registry.get     connection: 'keep-alive',
92 silly registry.get     'x-served-by': 'cache-ams4444-AMS',
92 silly registry.get     'x-cache': 'MISS',
92 silly registry.get     'x-cache-hits': '0',
92 silly registry.get     'x-timer': 'S1478192797.019437,VS0,VE172',
92 silly registry.get     vary: 'Accept-Encoding' } ]
93 verbose etag hap-nodejs/0.4.12 from cache
94 silly lockFile b07b58bc-chalk-1-1-1 chalk@^1.1.1
95 silly lockFile b07b58bc-chalk-1-1-1 chalk@^1.1.1
96 error Error: No compatible version found: chalk@'^1.1.1'
96 error Valid install targets:
96 error ["0.1.0","0.1.1","0.2.0","0.2.1","0.3.0","0.4.0","0.5.0","0.5.1","1.0.0","1.1.0","1.1.1","1.1.2","1.1.3"]
96 error     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:682:10)
96 error     at /usr/local/lib/node_modules/npm/lib/cache.js:597:10
96 error     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
96 error     at Object.oncomplete (fs.js:93:15)
97 error If you need help, you may report this log at:
97 error     <http://github.com/isaacs/npm/issues>
97 error or email it to:
97 error     <npm-@googlegroups.com>
98 error System Linux 3.12.28+
99 error command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
100 error cwd /home/pi/homebridge
101 error node -v v0.10.0
102 error npm -v 1.2.14
103 verbose exit [ 1, true ]

### supporting information:

 - `npm -v` prints: 1.2.14
 - `node -v` prints: v0.10.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux 
 - Network issues:
   - Geographic location where npm was run: Belgium

**Comment by legodude17** [comment]
What is your `package.json`?

**Comment by KenanY** [comment]
`npm@1.2` is years old and is no longer supported. I would suggest you update.
