### ISSUE TITLE
npm start failed

### ISSUE THREAD

**Issue by Atul141** [npm/npm#14515]
#### I'm opening this issue because:

  - [x] npm is not starting

npm is installed correctly, but when I say npm start I am getting the following error.

Also When I used npm installed I got  warning like ' No repository field' and 'No license field.'

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8

npm ERR! missing script: start

**Comment by KenanY** [comment]
@Atul141 Do you have a `"start"` script defined in your `package.json`?

**Comment by Atul141** [comment]
No, I don't have .

**Comment by KenanY** [comment]
@Atul141 You should add one before trying to run `npm start` ;) for example:

``` json
{
  "scripts": {
    "start": "commands go here"
  }
}
```
