### ISSUE TITLE
Replace env vars in .npmrc keys

### ISSUE THREAD

**Issue by maybeec** [npm/npm#14513]
#### I'm opening this issue because:
  - [x] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints: v3.10.8
 - `node -v` prints: v6.9.1
 - Windows, OS X/macOS, or Linux?: Windows 7 x64

#### What's the feature?

Env vars are  not replaced in .npmrc keys 

.example
```
@scope:registry=${ARTIFACTORY_REGISTRY}
//${ARTIFACTORY_REGISTRY}:_password=${PASSWORD}
//${ARTIFACTORY_REGISTRY}:username=${USERNAME}
```

So ${ARTIFACTORY_REGISTRY} is replaced in a value expression but not in a key expression, which is quite odd.

#### What problem is the feature intended to solve?
Scoped registry URLs defined by env variables

#### Is the absence of this feature blocking you or your team? If so, how?
Yes. The encoded URL is different at the customer side had thus has to be changed whenever building in a different environment.

#### Is this feature similar to an existing feature in another tool?
No. 

#### Is this a feature you're prepared to implement, with support from the npm CLI team?
No.

**Comment by legodude17** [comment]
This seems not too hard, and would make a lot of sense for the use case that you have. I could probably make this work.

**Comment by maybeec** [comment]
I recognized, that this will finally not work as the value of registry has to include the protocol (e.g. http://), whereas the key in this example must not... bad luck

**Comment by legodude17** [comment]
Yes. Do you still think this would be a good feature?

**Comment by maybeec** [comment]
No, actually this would be the only use case I saw. So we should close this for now.
