### ISSUE TITLE
installing with  no cache flag creates a folder named "false"

### ISSUE THREAD

**Issue by bweston92** [npm/npm#14514]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Running `npm install -no-cache` creates a folder `false` along side the `node_modules` folder.

#### How can the CLI team reproduce the problem?

Using `node:7` image from Docker Hub execute `npm install -no-cache` and a folder "false" appears in the working directory..

### supporting information:

 - `npm -v` prints: 3.10.8
 - `node -v` prints: v.7.0.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [x] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@bweston92 Right, because `--no-cache` is equivalent to `--cache=false`, which will be treated as a directory named `false`. I'm gonna close this in light of https://github.com/npm/npm/issues/11338#issuecomment-183211330.
