### ISSUE TITLE
cannot install mongoose through npm

### ISSUE THREAD

**Issue by hehihehi** [npm/npm#14523]
#### I'm opening this issue because:
  - [ ] npm is crashing.
  - [v] npm is producing an incorrect install.
  - [v] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
@ubuntu:~$ sudo npm install mongoose
[sudo] password for jkh: 
npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "mongoose"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'npm-autoinit/autoinit'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN jkh@1.0.0 No description
npm WARN jkh@1.0.0 No repository field.
npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "mongoose"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2

npm ERR! Callback called more than once.
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jkh/npm-debug.log

### supporting information:

 - `npm -v` prints:3.5.2
 - `node -v` prints:4.2.6
 - `npm config get registry` prints:
npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "config" "get" "registry"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'npm-autoinit/autoinit'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
https://registry.npmjs.org/
npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "config" "get" "registry"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2

npm ERR! Callback called more than once.
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jkh/npm-debug.log

 - Windows, OS X/macOS, or Linux?:Linux
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [o] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@hehihehi I think your `npm` installation is busted. Maybe try reinstalling? (preferably a newer version)

**Comment by KenanY** [comment]
Closing due to no response
