### ISSUE TITLE
Unable to star/unstar a scoped package with public access

### ISSUE THREAD

**Issue by cedx** [npm/npm#14526]
#### I'm opening this issue because:
npm is not doing what it's supposed to do when using the star/unstar feature.

#### What's going wrong?
Using the UI (npmjs.com) or the CLI, I'm unable to star or unstar scoped packages with public access. This is a regression because, by the past, I could star this kind of packages.

#### How can the CLI team reproduce the problem?
`$ npm star @cedx/gulp-smartling`

This ends with this error : `'@cedx/gulp-smartling' is not in the npm registry` (a 404 status).
But the package exists: https://www.npmjs.com/package/@cedx/gulp-smartling

Staring a different scoped package yields the same result. I've reproduced the bug in several environments (different OS, different network config, different browsers for the npm website).

The error log: https://gist.github.com/cedx/263a31ab03421ed67235b7b5ca749769

#### Supporting information:
 - `npm -v` prints: `3.10.8`
 - `node -v` prints: `v7.0.0`
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?: OS X El Capitan 10.11.6, also with Windows 10
 - Geographic location where npm was run:
   - At work : OSX, accessing the registry via a VPN (I don't think we use a proxy but I'm not sure).
   - At home : Windows, using direct access to the registry (no VPN, no proxy).
 - Container: no container.

**Comment by legodude17** [comment]
On the UI for me it works fine. I will try the cli later, when I get the chance.

**Comment by cedx** [comment]
Using the UI with Chrome 54.0.2840.87 on Windows 10 :
I open the dev tools, and monitor the network requests. I click on the star : the XHR response has a 500 status code, and its text is "not ok".
Same result using Firefox 49.0.2 and MS Edge 14.14393.

Does npm/npmjs.com use some kind of CDN or proxy that could lead to different result depending on the location ? (I'm located in France)

**Comment by legodude17** [comment]
I am in California, with Chrome 53.0.2785.154 on a Chromebook. I see that the XHR has a 200 status code. That is very odd.

**Comment by cedx** [comment]
See the [via: '1.1 varnish'](https://gist.github.com/cedx/263a31ab03421ed67235b7b5ca749769#file-npm-debug-log-L78) or [x-cache: 'MISS'](https://gist.github.com/cedx/263a31ab03421ed67235b7b5ca749769#file-npm-debug-log-L81) headers in the log. Perhaps a trail to follow: a cache issue.
Tried to star/unstar a non-scoped package: still no problem (UI and CLI). The issue is really with scoped packages.

**Comment by legodude17** [comment]
I got the same result on the scoped package `@types/react`. You may want to file an issue in npm/registry.

**Comment by othiym23** [comment]
This is indeed a registry issue, so it would be best to take this issue over there (as I see you've done). As such, I'm going to close this one. Thanks for your time!
