### ISSUE TITLE
npmjs.org displays README, but npm client software says 'No README data found!'

### ISSUE THREAD

**Issue by mikemaccana** [npm/npm#14527]
#### I'm opening this issue because:

  - [x] npm is doing something I don't understand.

#### What's going wrong?

https://www.npmjs.com/package/sorts has a README.md, which is displayed on https://www.npmjs.com/package/sorts (so obviously seems to work). 

However after running `npm install sorts` the package.json is modified to contain:

> "readme": "ERROR: No README data found!",

Am I doing something wrong? If my package has a correct README, why is package.json saying it's wrong? If it has an incorrect README, why is npmjs.org displaying it?

#### How can the CLI team reproduce the problem?

`npm install sorts`  and inspect the modified package.json

### supporting information:

 - `npm -v` prints: 3.10.7
 - `node -v` prints: v6.6.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Microsoft Windows NT 10.0.14393.0

🎉 Thanks npmpersons! 🎉

**Comment by legodude17** [comment]
The page on the registry has it correctly. This might be a problem with your installation, will comment again when I get the chance to run the command my self.

**Comment by Martii** [comment]
@legodude17 
Any news on this yet? Thanks so much.

**Comment by Martii** [comment]
@isaacs

> ... closing this support issue as it has gone three days without activity.

Really? I don't think the issue went away... I'm curious as to why it says this as well, e.g. possible bug, and I didn't even make the issue. So you all want another issue created with the exact same text every three days? \*confusion abounds\*
