### ISSUE TITLE
`externalDependencies` section

### ISSUE THREAD

**Issue by Mithgol** [npm/npm#14529]
This is a request for a feature that I don't see proposed at https://github.com/npm/npm/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request+label%3Aalready-looked-at previously.

#### What's the feature?

A new section at `package.json`, named `externalDependencies`, with a syntax quite similar to `dependencies` and `peerDependencies` (which is an object of one or several `"dependencyName": "dependencyVersion"` fields).

This section's purpose is to enumerate the application's external dependencies, which are not installed by npm, but are used nevertheless. Examples of such dependencies:

* Scripts loaded remotely (from a CDN) instead of a local npm-installed version.

* Local customized versions of dependencies that are used instead of their npm-installed versions (which would be not customized).

The intended behaviour of npm is to not warn about unmet peerDependencies where the parent's externalDependencies can satisfy the requirement.

#### What problem is the feature intended to solve?

The problem of unnecessary warnings about unmet peerDependencies in the specific cases where such dependencies are in fact being used, but are not installed by npm.

Such warnings are caused by the following (somewhat conflicting) tendencies:

* Plugins tend to list their parent library (or framework) in their peerDependencies. Examples:
   * [`bootstrap-fileinput`](https://github.com/kartik-v/bootstrap-fileinput) currently [lists](https://github.com/kartik-v/bootstrap-fileinput/blob/17a8821c20885c4d736ba77d02446c2632230eb5/package.json#L31) both [jQuery](http://jquery.com/) and [Bootstrap](http://getbootstrap.com/css/)
   * [`jquery-aniview`](https://github.com/jjcosgrove/jquery-aniview/) currently [lists](https://github.com/jjcosgrove/jquery-aniview/blob/2726297e97600a48f31f8add42fc9d226ed27b29/package.json#L17) both [jQuery](http://jquery.com/) and [Animate.css](https://daneden.github.io/animate.css/)

* On the other hand, an application (which is, most likely, a web site; could also be an application built on [Electron](http://electron.atom.io/), [NW.js](http://nwjs.io/), [JXcore for Cordova](https://github.com/jxcore/jxcore-cordova/), etc.) does not always use npm to install that libraries or frameworks. There are two different reasons for that:
   * **CDN use.** The application's author might decide to get jQuery from [jQuery CDN](http://code.jquery.com/), to get Animate.css [from CDNJS](https://cdnjs.com/libraries/animate.css), to get [Twitter Emoji](https://github.com/twitter/twemoji/) from [MaxCDN](https://github.com/twitter/twemoji/blob/4ff9333fc0bb92f286ab49b19aaadb27f332c9b2/README.md#cdn-support), to load an npm package from [unpkg.com](https://unpkg.com/) instead of a local npm-installed version.
   * **Custom builds of dependencies.** While npm installs the default (not customized) version of a dependency, the application's author might decide to download [a custom set](http://getbootstrap.com/customize/) of Bootstrap's components and plugins, to make [a custom build](https://github.com/daneden/animate.css/blob/9bc802dfc9f9ddf2ff51e290dce8a8aba21661e9/README.md#custom-builds) of Animate.css, etc.

These two tendencies, working together, create situations where warnings about unmet peerDependencies appear (but where everything's, in fact, works as intended).

#### Is the absence of this feature blocking you or your team? If so, how?

It's never blocking because it's easy to ignore warnings about unmet peerDependencies.

This feature request scratches a minor itch.

#### Is this feature similar to an existing feature in another tool?

I do not currently know about any of such tools.

#### Is this a feature you're prepared to implement, with support from the npm CLI team?

I believe that it would be quite difficult for me to understand the npm's code enough to alter its behaviour related to peerDependencies. So, unfortunately, that's a no.

**Comment by legodude17** [comment]
I like this idea, but I think it should be formatted differently. This sounds like it should more be `"depName":"script to run to get it"` because these deps would specifically not be on the `npm` registry.

**Comment by Mithgol** [comment]
@legodude17

The idea of `"depName": "depVersion"` format has the following advantages:

* The given version can be used to check if peerDependencies listed by the application's “child” dependencies can be satisfied against it. (These `peerDependencies` have the `"depName": "depVersion"` format after all.)

* The tools that currently check for outdated dependencies (such as [`david`](https://github.com/alanshaw/david) for example) might benefit in the future if they decide to check for outdated externalDependencies as well.

* The templating tools that generate parts of webpages (on Node-based hostings) might benefit in the future if they decide to automatically generate `<script>` tags in the pages' `<head>` based on the version from `package.json`, such as `"jquery-aniview":" "1.0.1"` → `<script src="https://unpkg.com/jquery-aniview@1.0.1/dist/jquery.aniview.js"></script>` (though they would still need to take the rest of the path, such as `/dist/jquery.aniview.js`, elsewhere).

* The form `"depName": "script to run to get it"` looks great for one of the above cases (“Custom builds of dependencies”), but not for the other (“CDN use”), in the latter case it's never intended to get a dependency locally, but rather something like `<script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>` is used to reference a remote script (in such case my idea was to simultaneously declare `"jquery": "3.1.1"` in externalDependencies to satisfy peerDependencies of locally installed jQuery plugins, but not much else).

That being said, the form `"depName": "script to run to get it"` seems quite useful and inspirational and thus it might in the future become a basis for another feature request: **using npm to install custom builds of dependencies.** However, it's more or less obvious that its free form (just a name and a script) would have several disadvantages:

* it's not very structured (whitespaces in the script being the only separators),

* it does not contain a clear hint about the version (thus preventing version-based validation),

* the dependency itself is probably a better place (than its parent's `package.json`) to contain its installation (customization) script.

You might prevent all of those three by considering something along the lines of `"depName": ["depVersion", {…some data to be passed to that dependency's postinstall script…}]` — well, not actually `postinstall`, because it's quite likely to require a separate entry in `package.json`, but some of dependency's own scripts nevertheless (to keep that script out of its dependent's `package.json`). Examples:

* `"bootstrap": ["3.3.7", {"glyphicons": false, "@font-size-base": "15px", "@font-family-sans-serif": "'PT Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif"}]`

* `"animate.css": ["3.5.2", {"animate-config.json": { "attention_seekers": [ "bounce", "flash", "pulse", "rubberBand", "shake", "headShake", "swing", "tada", "wobble", "jello"] } } ]`

**Comment by legodude17** [comment]
The problem I see with that is how would `npm` know where to get those?

**Comment by Mithgol** [comment]
It won't get them.

The idea here is the following: `npm` trusts the application to get its `externalDependencies` from other sources (not from npm) and, based on that trust, `npm` resolves unmet peerDependencies of the application's dependencies.

**Comment by legodude17** [comment]
So `npm` won't fetch them, it will just know that those come from somewhere else. You might want to change the name to show that `npm` won't actually get them because that is quite confusing.

**Comment by Mithgol** [comment]
If the “external” part does not fully convey the intended meaning, how should I really call them? “Alien”?

**Comment by kazazor** [comment]
Maybe call them `ignoreDependencies`? This is actually what you want to get here, to ignore the peerDependencies mentioned in this section..

**Comment by Mithgol** [comment]
Maybe.
