### ISSUE TITLE
npm generator-hubot error but in fact get the same error doing any npm install.

### ISSUE THREAD

**Issue by muralivg** [npm/npm#14522]
C:\Users\mvenugopal\Documents\Official\GitHub\hubot>npm install -g generator-hubot
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "generator-hubot"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! 1317 == 0
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

Hubot was working perfectly fine yesterday and all that happen was I shutdown my laptop only to restart today and continue my work. 
This is on Windows 10. I uninstalled Nodejs, reinstalled and did whatever I did from scratch but cant seem to get it to work.  I have enclosed npm-debug.log.
[npm-debug.pdf](https://github.com/npm/npm/files/570697/npm-debug.pdf)

**Comment by legodude17** [comment]
Hi @muralivg! This is a really weird error and I have no idea where it would come from. Any ideas @zkat or @KenanY?

**Comment by KenanY** [comment]
Yeah I looked at this early and I'm completely lost as to what's going on 😕

**Comment by legodude17** [comment]
After nearly half an hour on this, I think that `npm` somehow managed to give `request` incorrect args in `npm-registry-client`. It is probably [this line](https://github.com/npm/npm-registry-client/blob/master/lib/request.js#L158). This really strange. Maybe try reinstalling @muralivg?

**Comment by muralivg** [comment]
Thanks a lot, let me try reinstalling and installing everything again although I tried that once. Sometimes I  get lucky the 2nd time... may be I should do the 2nd time 1st always :)

**Comment by legodude17** [comment]
If you already tried that you don't have to try again. I check the request issues, but there is nothing about this. I am still confused. 😖

**Comment by muralivg** [comment]
Nevertheless, I tried again and same issue. One thing I also noticed was that after the error the Command line prompt does not come back.. it hangs. I need to do a Ctrl+C and Terminate the batch job to get back to the prompt.

C:\Users\mvenugopal>npm install hubot-generator
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "hubot-generator"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8

npm ERR! 1317 == 0
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
Terminate batch job (Y/N)? y

**Comment by legodude17** [comment]
That is very strange. Why would `npm` hang after getting that error? It
should have exited with a 1 status code.
