### ISSUE TITLE
color.yellow is not a function (while installing ionic)

### ISSUE THREAD

**Issue by cyraid** [npm/npm#14520]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

sudo npm install -g ionic
Fails to install ionic because "color.yellow is not a function"

#### How can the CLI team reproduce the problem?

Using Ubuntu 16.10 64bit:
`sudo npm install -g cordova ionic`

### supporting information:

 - `npm -v` prints: 3.5.2
 - `node -v` prints: 4.1.1
 - `npm config get registry` prints: http://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux (Ubuntu 16.10, 64bit)

#### What's the feature?

Cordova + Ionic.

#### What problem is the feature intended to solve?

Installing Ionic.

#### Is the absence of this feature blocking you or your team? If so, how?

Cannot install (block)

**Comment by legodude17** [comment]
Can you put the `npm-debug.log` in a gist and then post the link?

**Comment by KenanY** [comment]
Ooooh, finally another instance of https://github.com/npm/npm/issues/13375 :)

**Comment by cyraid** [comment]
@legodude17 sure. [Here](https://gist.github.com/cyraid/d62abe138fcee7ee05c589f5fd36eaaf) ya go.

**Comment by cyraid** [comment]
Fixed my problem.. (also had another problem after, which I fixed) .. 1) I may have had old traces of an old NodeJS installation, so I 'sudo apt-get purge nodejs'.  2) Manually removed /usr/local/lib/node_modules and /usr/lib/node_modules (if they exist)

**Comment by shawty** [comment]
@KenanY - Iv'e just added a comment to that closed issue (13375) on how to repro on current builds of Ubuntu 16.04 x64

**Comment by shawty** [comment]
Update, just had a poke around in the "ansi" module.

There is a 'colours' collection at line 67 which has    "yellow": 33 as a key in it, but there is no color.yellow anywhere, and there's certainly not a color.anything that's a function proto.
