### ISSUE TITLE
long-term support for certain require pattern

### ISSUE THREAD

**Issue by ORESoftware** [npm/npm#14537]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

Just curious if NPM knows if it will support this pattern of requiring modules

`const colors = require('colors/safe');`

I looked at the project to see how that works. Basically the directory structure looks like:

https://github.com/Marak/colors.js

```
root
    --/lib
       --index.js
--safe.js
```

Don't necessarily understand what the logic here is, but I was able to reproduce the logic in a project of mine. I am sure deep in the docs for require it says that when requiring a directory with a package.json file, it will return the module.exports value of the module that the main property points to, yet at the same time it will somehow reference the root directory (where package.json is), so that when you do require('x/y'), if y is in the root directory you will only load that file. It's a bit confusing at the least.

wondering 

(a) what the explanation is for this, and
(b) if you will be able to require a module in this way with ES6 import syntax?
Will there be long-term support for this?

**Comment by legodude17** [comment]
You should file this over with the node folks. `npm` doesn't document or implement the `require` function. Cheers!

**Comment by ORESoftware** [comment]
for sure, thanks!

**Comment by othiym23** [comment]
Closing as not an issue with npm – this is an attribute of the [Node module resolution algorithm](https://nodejs.org/api/modules.html#modules_all_together), and as such is the responsibility of the Node project to maintain. I can say that this behavior is highly, highly unlikely to change.

**Comment by othiym23** [comment]
Also, thanks for your time!

**Comment by ORESoftware** [comment]
Youre welcome? :)
