### ISSUE TITLE
npm start in windows 7

### ISSUE THREAD

**Issue by vadlamudivikas** [npm/npm#14536]
Hi I have installed node.js (4.6.0). When I call npm start , it gives the following error.

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.15.9
3 info using node@v4.6.0
4 verbose stack Error: missing script: start
4 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:142:19)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:58:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:356:5
4 verbose stack     at handleExists (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:329:20)
4 verbose stack     at FSReqWrap.cb [as oncomplete] (fs.js:212:19)
5 verbose cwd C:\Program Files\nodejs
6 error Windows_NT 6.1.7601
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
8 error node v4.6.0
9 error npm  v2.15.9
10 error missing script: start
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

Please help

**Comment by legodude17** [comment]
Do you have a `start` script in your `package.json`?

**Comment by watilde** [comment]
Hello! The error log said you're missing the `npm-script`. To use the `npm start`, you need to put it into the script field in your `package.json` like:
```json
{
  "script": {
    "start": "echo hi"
  }
}
```
See this example for your reference: https://docs.npmjs.com/misc/scripts#examples

Additionally, you're using the old version of the npm `v2.15.9`. It would be helpful for the other issues that potentially will come. For you reference to update the version, see also this docs: https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-node

Thanks!

**Comment by KenanY** [comment]
Closing since the advice above is enough to resolve this issue :)
