### ISSUE TITLE
mac install ionic show error

### ISSUE THREAD

**Issue by ddcouples** [npm/npm#14535]
npm install -g ionic
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "ionic"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8

npm ERR! Invalid name: "@ionic/app-generators"
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/lichao/Desktop/phonegap/cordova/corDemo/npm-debug.log

**Comment by legodude17** [comment]
Please try updating `npm` to the latest version (`4.0.2` or `3.10.10`).

**Comment by KenanY** [comment]
Closing as abandoned.
