### ISSUE TITLE
npm ERR! missing script: start

### ISSUE THREAD

**Issue by chudepohl** [npm/npm#14542]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'start' ]
2 info using npm@3.10.8
3 info using node@v7.0.0
4 verbose stack Error: missing script: start
4 verbose stack     at run (/usr/local/lib/node_modules/npm/lib/run-script.js:151:19)
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/run-script.js:61:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json$
4 verbose stack     at handleExists (/usr/local/lib/node_modules/npm/node_modules/read-package-$
4 verbose stack     at FSReqWrap.cb [as oncomplete] (fs.js:239:19)
5 verbose cwd /home/pi/homebridge
6 error Linux 4.1.18-v7+
7 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
8 error node v7.0.0
9 error npm  v3.10.8
10 error missing script: start
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@chudepohl Do you have a `"start"` script defined in your local `package.json`?

**Comment by chudepohl** [comment]
Yes

== package.json ==

{
  "name": "homebridge",
  "description": "HomeKit support for the impatient",
  "version": "0.4.8",
  "scripts": {
    "dev": "DEBUG=* ./bin/homebridge -D -P example-plugins/ || true"
  },
  "author": {
    "name": "Nick Farina"
  },
  "repository": {
    "type": "git",
    "url": "git://github.com/nfarina/homebridge.git"
  },
  "bugs": {
    "url": "http://github.com/nfarina/homebridge/issues"
  },
  "license": "ISC",
  "bin": {
    "homebridge": "bin/homebridge"
  },
  "engines": {
    "node": ">=4.3.2"
  },
  "preferGlobal": true,
  "dependencies": {
    "chalk": "^1.1.1",
    "commander": "2.8.1",
    "hap-nodejs": "0.4.13",
    "semver": "5.0.3",
    "node-persist": "^0.0.8"
  }

**Comment by KenanY** [comment]
@chudepohl What do you mean? There's no `"start"` script in that file at all. I suggest you read through <https://docs.npmjs.com/misc/scripts> before trying to use `npm` scripts. Once you've got a `"start"` script defined (just as you already have a `"dev"` one), I'm sure `npm start` will work no problem.

**Comment by KenanY** [comment]
Closing as abandoned.

**Comment by Sandip1993** [comment]
i have an issue when i start npm start command is getting the error npm ERR! missing script: start

**Comment by kenany** [comment]
@Sandip1993 Have you read my comments above?

**Comment by hajarrhechchou** [comment]
please can you help me here : 



0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\hajar\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.3.0
3 info using node@v6.11.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle design-angular2@1.2.0~prestart: design-angular2@1.2.0
6 info lifecycle design-angular2@1.2.0~start: design-angular2@1.2.0
7 verbose lifecycle design-angular2@1.2.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle design-angular2@1.2.0~start: PATH: C:\Users\hajar\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\hajar\Desktop\vsc\veille\app2\node_modules\.bin;C:\oraclexe\app\oracle\product\11.2.0\server\bin;C:\Program Files (x86)\AMD APP\bin\x86_64;C:\Program Files (x86)\AMD APP\bin\x86;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\AMD\ATI.ACE\Core-Static;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files (x86)\Brackets\command;C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.4;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Users\hajar\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\hajar\Desktop\vsc\veille\app2\node_modules.bin;C:\oraclexe\app\oracle\product\11.2.0\server\bin;C:\Program Files (x86)\AMD APP\bin\x86_64;C:\Program Files (x86)\AMD APP\bin\x86;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\AMD\ATI.ACE\Core-Static;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files (x86)\Brackets\command;C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.4;C:\Program Files\Git\cmd;C:\Program Files\nodejs;C:\Program Files\sts-bundle\sts-3.8.4.RELEASE;C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.4;C:\Program Files\MongoDB\Server\3.4\bin;C:\Users\hajar\AppData\Roaming\npm;C:\Program Files\nodejs;C:\Users\hajar\Desktop\vsc\veille\app2\node_modules
9 verbose lifecycle design-angular2@1.2.0~start: CWD: C:\Users\hajar\Desktop\vsc\veille\app2
10 silly lifecycle design-angular2@1.2.0~start: Args: [ '/d /s /c', 'tsc && concurrently "tsc -w" "lite-server" ' ]
11 silly lifecycle design-angular2@1.2.0~start: Returned: code: 2  signal: null
12 info lifecycle design-angular2@1.2.0~start: Failed to exec start script
13 verbose stack Error: design-angular2@1.2.0 start: `tsc && concurrently "tsc -w" "lite-server" `
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\hajar\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:191:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\hajar\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:891:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14 verbose pkgid design-angular2@1.2.0
15 verbose cwd C:\Users\hajar\Desktop\vsc\veille\app2
16 verbose Windows_NT 6.1.7601
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\hajar\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v6.11.1
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 2
22 error design-angular2@1.2.0 start: `tsc && concurrently "tsc -w" "lite-server" `
22 error Exit status 2
23 error Failed at the design-angular2@1.2.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
