### ISSUE TITLE
Failed to install fireabase-tools using npm: varnish 503 first byte timeout

### ISSUE THREAD

**Issue by kokizzu** [npm/npm#14545]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Failed to install `firebase-tools`

#### How can the CLI team reproduce the problem?
```
npm -g install firebase-tools

npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! Linux 4.6.7-1-MANJARO
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "-g" "install" "firebase-tools"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.9

npm ERR! Unexpected token < in JSON at position 1
npm ERR! 
npm ERR! <?xml version="1.0" encoding="utf-8"?>
npm ERR! <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
npm ERR!  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
npm ERR! <html>
npm ERR!   <head>
npm ERR!     <title>503 first byte timeout</title>
npm ERR!   </head>
npm ERR!   <body>
npm ERR!     <h1>Error 503 first byte timeout</h1>
npm ERR!     <p>first byte timeout</p>
npm ERR!     <h3>Guru Mediation:</h3>
npm ERR!     <p>Details: cache-sin6922-SIN 1478507870 1424291310</p>
npm ERR!     <hr>
npm ERR!     <p>Varnish cache server</p>
npm ERR!   </body>
npm ERR! </html>
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/kyz/MEGA/go/src/firebase-demo/web-start/npm-debug.log
```

### supporting information:

 - `npm -v` prints:  3.10.9
 - `node -v` prints: v7.0.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux
 - Network issues:
   - Geographic location where npm was run: Indonesia
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kokizzu** [comment]
Nevermind, change registry to http://r.cnpmjs.org/ solves this problem.

npm config set registry http://r.cnpmjs.org/

**Comment by KenanY** [comment]
Should be resolved now: <https://npmjs.statuspage.io/incidents/vwyj9jzcc4zn>
