### ISSUE TITLE
Unable to install Haraka, facing 503 issue

### ISSUE THREAD

**Issue by gs-traavi** [npm/npm#14549]
#### I'm opening this issue because:

  - npm is crashing.
#### What's going wrong?
Unable to install haraka with the command. (npm install -g Haraka)
#### How can the CLI team reproduce the problem?
Try to execute npm install -g Haraka

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?: Linux server
 - Network issues:
   - Geographic location where npm was run:
   - I use a proxy to connect to the npm registry.
 - Container.
   - I deploy to a PaaS (Triton, Heroku).

![npmerror](https://cloud.githubusercontent.com/assets/10208566/20052854/cc5b6df0-a4fb-11e6-993d-705ccef7ce74.png)
[npm-debug.txt](https://github.com/npm/npm/files/574954/npm-debug.txt)

**Comment by pataiadam** [comment]
Same here:

```
....
npm http fetch 503 https://registry.npmjs.org/final-fs/-/final-fs-1.6.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/final-fs/-/final-fs-1.6.1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503
npm info retry fetch attempt 2 at 9:41:25 AM
npm info attempt registry request try #1 at 9:41:25 AM
npm http fetch GET https://registry.npmjs.org/final-fs/-/final-fs-1.6.1.tgz
npm http fetch 503 https://registry.npmjs.org/final-fs/-/final-fs-1.6.1.tgz
npm info retry will retry, error on last attempt: Error: server error 503
npm info attempt registry request try #2 at 9:41:35 AM
npm http fetch GET https://registry.npmjs.org/final-fs/-/final-fs-1.6.1.tgz
npm http fetch 503 https://registry.npmjs.org/final-fs/-/final-fs-1.6.1.tgz
npm info retry will retry, error on last attempt: Error: server error 503
....
```

**Comment by Cbenh** [comment]
same here : 
<img width="972" alt="screen shot 2016-11-07 at 5 25 02 pm" src="https://cloud.githubusercontent.com/assets/3868326/20053056/c7863be6-a511-11e6-965a-a8d57a9438d2.png">

**Comment by dilanarandara** [comment]
Same here. Can't install any modules.

```
npm ERR! fetch failed https://registry.npmjs.org/js-cookie/-/js-cookie-2.1.3.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503
npm ERR! fetch failed https://registry.npmjs.org/ejs/-/ejs-2.5.2.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503
npm ERR! fetch failed https://registry.npmjs.org/mysql/-/mysql-2.12.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503
npm ERR! fetch failed https://registry.npmjs.org/body-parser/-/body-parser-1.12.4.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503
npm ERR! fetch failed https://registry.npmjs.org/express/-/express-4.12.4.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503
npm ERR! fetch failed https://registry.npmjs.org/node-rest-client/-/node-rest-client-1.8.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503
npm ERR! fetch failed https://registry.npmjs.org/ejs/-/ejs-2.5.2.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503
npm ERR! fetch failed https://registry.npmjs.org/js-cookie/-/js-cookie-2.1.3.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503
npm ERR! fetch failed https://registry.npmjs.org/mysql/-/mysql-2.12.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503
npm ERR! fetch failed https://registry.npmjs.org/body-parser/-/body-parser-1.12.4.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503
npm ERR! fetch failed https://registry.npmjs.org/express/-/express-4.12.4.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503
npm ERR! fetch failed https://registry.npmjs.org/node-rest-client/-/node-rest-client-1.8.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503
npm ERR! fetch failed https://registry.npmjs.org/ejs/-/ejs-2.5.2.tgz
npm ERR! fetch failed https://registry.npmjs.org/js-cookie/-/js-cookie-2.1.3.tgz
npm ERR! fetch failed https://registry.npmjs.org/mysql/-/mysql-2.12.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/body-parser/-/body-parser-1.12.4.tgz
npm ERR! fetch failed https://registry.npmjs.org/express/-/express-4.12.4.tgz
npm ERR! fetch failed https://registry.npmjs.org/node-rest-client/-/node-rest-client-1.8.0.tgz
```

**Comment by llPorZall** [comment]
Me too can't install any modules.

**Comment by kusmayadi** [comment]
Same here

npm ERR! fetch failed https://registry.npmjs.org/cli-table/-/cli-table-0.3.1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503
npm ERR! fetch failed https://registry.npmjs.org/chalk/-/chalk-1.1.3.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503
npm ERR! fetch failed https://registry.npmjs.org/cli-table/-/cli-table-0.3.1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503
npm ERR! fetch failed https://registry.npmjs.org/chalk/-/chalk-1.1.3.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503
npm ERR! fetch failed https://registry.npmjs.org/cli-table/-/cli-table-0.3.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/chalk/-/chalk-1.1.3.tgz
npm ERR! Linux 4.4.0-45-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "pm2"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8

**Comment by gs-psankavaram** [comment]
Same issue for me as well

**Comment by PawanKadapatti** [comment]
Same here, whats the solution

**Comment by rajchaudhary** [comment]
For now change the registry and it will work!
npm config set registry http://r.cnpmjs.org/

**Comment by gs-traavi** [comment]
Done, Thank you

**Comment by gs-psankavaram** [comment]
Done.Working Fine. Thanks.

**Comment by Cbenh** [comment]
Works fine but this is chinese registry. i hope NPM is going to fix this quickly.

**Comment by rajchaudhary** [comment]
yes i hope so!

**Comment by PawanKadapatti** [comment]
working thanks you.

**Comment by pataiadam** [comment]
http://status.npmjs.org/#

> Investigating - we are seeing elevated 503s from our cdns singapore pop. 
Nov 7, 10:35 UTC

**Comment by pataiadam** [comment]
For me it's working now.

http://status.npmjs.org/#
> Update - We made some changes to our cdn configuration to route more requests from SIN away from their previous backends. It looks like 503 rate is dropping but not resolved. 
Nov 7, 10:51 UTC

**Comment by KenanY** [comment]
Has been marked as resolved: <https://npmjs.statuspage.io/incidents/vwyj9jzcc4zn>
