### ISSUE TITLE
npm_config_node_gyp should be working with node-gyp.cmd on Windows

### ISSUE THREAD

**Issue by ghostoy** [npm/npm#14543]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?

When setting `npm_config_node_gyp` environment to `node-gyp.cmd` on Windows, the npm installation failed with following error:

```
> npm install

> ffi@2.2.0 install C:\Users\me\Workspace\test\native-module\node_modules\ffi
> node-gyp rebuild

> if not defined npm_config_node_gyp (node "C:\Users\me\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "c:\Users\me\AppData\Roaming\npm\node-gyp.cmd" rebuild )
c:\Users\me\AppData\Roaming\npm\node-gyp.cmd:1
(function (exports, require, module, __filename, __dirname) { @IF EXIST "%~dp0\node.exe" (
                                                              ^
SyntaxError: Invalid or unexpected token
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
npm WARN native-module@0.1.1 No description
npm WARN native-module@0.1.1 No repository field.
npm WARN native-module@0.1.1 No license field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\me\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE

npm ERR! ffi@2.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ffi@2.2.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ffi package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ffi
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ffi
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\me\Workspace\test\native-module\npm-debug.log
```

On Linux and Mac, you can set `npm_config_node_gyp` to the path of shell script of `node-gyp` by `export npm_config_node_gyp=$(which node-gyp)`, not required to be the js file.

#### How can the CLI team reproduce the problem?

1. Install or have a local version of `node-gyp`.
2. Run `set npm_config_node_gyp=path\to\node-gyp.cmd`
3. Install a native module with `npm`, for example, `npm install ffi`
4. Error is shown as above
5. Run `set npm_config_node_gyp=path\to\node_modules\node-gyp\bin\node-gyp.js` and reinstall the module
6. Works without error

### supporting information:

 - `npm -v` prints: 3.10.6
 - `node -v` prints: 6.5.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by othiym23** [comment]
This is a reasonable expectation, but that's not how `node-gyp` is integrated into npm (which is to say, npm's integration of `node-gyp` is very, very loose), nor is the current behavior out of sync with our documentation. The team will have to do a more in-depth assessment of this as a feature request later, but for now, a patch that brings `node-gyp` formally into the configuration framework used by the CLI would be welcome. Thanks for your time!

**Comment by ghostoy** [comment]
Fixing this issue will not make npm close coupled with node-gyp.

**Comment by ghostoy** [comment]
A previous patch on `node-gyp.cmd` in #8324 is a reverse of mine. The initiation of that patch was that someone is trying to pass `node-gyp.js` file to the environment and windows tries to open it with an editor. But if you pass the shell script to it on Windows, the original version will work.
