### ISSUE TITLE
I have an issue on Canvas Signature using angular2, it doesnt work properly... There is an error.. 

### ISSUE THREAD

**Issue by harizgit** [npm/npm#14555]
npm ERR! Linux 4.4.0-45-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2

npm ERR! missing script: start
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/seqato/Downloads/angular2-signaturepad-master/npm-debug.log

**Comment by KenanY** [comment]
@harizgit The log is indicating that you are trying to run `npm start`, which executes the `"start"` script of your `package.json`, but you do not have such a script defined in your `package.json`. I suggest reading through <https://docs.npmjs.com/misc/scripts> for information on how scripts work. For your case, you should have something like:

``` json
{
  "scripts": {
    "start": "blah blah"
  }
}
```

**Comment by harizgit** [comment]
@KenanY But it does't working. Please send me the full file to run Canvas Signature

**Comment by KenanY** [comment]
@harizgit I'm not familiar with Canvas Signature. Your best bet would be to contact the author(s).
