### ISSUE TITLE
netsuite-fasttrack-toolkit-ss2 --save error

### ISSUE THREAD

**Issue by NZaleski** [npm/npm#14557]
#### I'm opening this issue because:

  - [ ] npm is producing an incorrect install.

#### What's going wrong?
Trying to install netsuite-fasttrack-toolkit-ss2 and it is giving me error

#### How can the CLI team reproduce the problem?

npm install netsuite-fasttrack-toolkit-ss2 --save

## error log
203 error Darwin 15.6.0
204 error argv "/usr/local/Cellar/node/7.0.0/bin/node" "/usr/local/bin/npm" "install" "netsuite-fasttrack-toolkit-ss2"
205 error node v7.0.0
206 error npm  v3.10.9
207 error code 128
208 error Command failed: git rev-list -n1 logger-specific-loglevel
208 error fatal: ambiguous argument 'logger-specific-loglevel': unknown revision or path not in the working tree.
208 error Use '--' to separate paths from revisions, like this:
208 error 'git <command> [<revision>...] -- [<file>...]'
209 error If you need help, you may report this error at:
209 error     <https://github.com/npm/npm/issues>
210 verbose exit [ 1, true ]
####

 - Windows, OS X/macOS, or Linux?:  Mac OS

Please let me know if you need any other information.  Thank!

**Comment by legodude17** [comment]
Can you put your `npm-debug.log` in a gist and then post the link?

**Comment by NZaleski** [comment]
Sure .  Here you go.  Thank you. 
https://gist.github.com/NZaleski/56f112172320085a87984f3a910fe995

**Comment by legodude17** [comment]
I don't know what the problem is. Have you gone trough the troubleshooting guide on the wiki?

**Comment by NZaleski** [comment]
No, what Wiki are you referring to?

**Comment by KenanY** [comment]
@NZaleski https://github.com/npm/npm/wiki/Troubleshooting

**Comment by ShawnTalbert** [comment]
I'd recommend trying node < 7.
