### ISSUE TITLE
Suppress missing package.json warnings when installing with set prefix.

### ISSUE THREAD

**Issue by jcferrer** [npm/npm#14558]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

when executing a locally package install, the process ends with a WARN message about the package.json not found.

npm WARN enoent ENOENT: no such file or directory, open '/mydir/package.json'
npm WARN temp No description
npm WARN temp No repository field.
npm WARN temp No README data
npm WARN temp No license field.

#### How can the CLI team reproduce the problem?

Just perform a local install for any package (npm 3.10.8, node 6.9.1)

i.e. node install <package> 

### supporting information:

macOS Sierra 10.12.1
linux RHEL 7

**Comment by legodude17** [comment]
Is there a `package.json` in your current working directiory?

**Comment by jcferrer** [comment]
No. This happens when you try to install a package locally. For instance, let's say the package is abc and I want to install it inside mydir directory.

npm install --prefix mydir abc

After all installation has taking place, it seems npm is trying to find a package.json.

npm WARN enoent ENOENT: no such file or directory, open '/mydir/package.json'
npm WARN temp No description
npm WARN temp No repository field.
npm WARN temp No README data
npm WARN temp No license field.

By the way even if you try to install in the current dir, i.e. npm install abc, shows the same behaviour.

The package is installed correctly though, but the message at the end is concerning.

Thanks

**Comment by legodude17** [comment]
You should always have a `package.json` when you install. This is an intended feature.

**Comment by jcferrer** [comment]
If you are thinking on installing dependencies only for an app yes, I agree. But if you use the command just to install the app in a local directory, no, the package.json will not be in the current directory where you execute the npm install command. The package json will be inside the /mydir/packagename directory. On npm 2 this is the behavior.

The use case is installing apps or packages in locations other than the global space. (i.e. $appspath)

On npm 2 we did:
npm install --prefix $appspath $pkg@$ver

On npm 3 we had to change it to:
npm install --global-style --prefix $appspath $pkg@$ver

(It works, but I don't think the warning is correct. Something is different.)

**Comment by legodude17** [comment]
Do you still get the warning if you use `--global-style`?

**Comment by legodude17** [comment]
That shouldn't happen, I think. Can you explain the use case for me? Why do you want to install and then use things in a random dir?

**Comment by jcferrer** [comment]
We install remotely to servers, on specific directory (i.e. apps). (We don't use the global space)

So each server has /opt/apps directory.

From each server we execute:

npm install --global-style --prefix /opt/apps @mine/my-app1
npm install --global-style --prefix /opt/apps @mine/my-app2

So our directory structure after this on each server will be:

/opt/apps/node_modules/@mine/my-app1
/opt/apps/node_modules/@mine/my-app2

We have been using automated scripts for our installations without any issues under npm 2.

We have now switch to npm 3 and latest node 6.9.1 and we are discovering these issues.

**Comment by legodude17** [comment]
Thank you for clearing that up. This seems to be a legit bug and/or feature request. For now, you could make a blank `package.json` in `/opt/apps`. Do you agree @KenanY?

**Comment by jcferrer** [comment]
I can certainly try to do that for now. I have seen other online discussions about this issue, but I don't think is well understood, since I guess everybody assumes that you only execute npm install when you cwd is the actual app, or when you install globally.

I appreciate you following up on this. It would be great if you can address this issue. Since is definitively different behavior than the previous version.

Thanks. Let me know if you need me to do anything.

**Comment by legodude17** [comment]
After a bit of reaserach, I found that `--global-style` actually does it so that it is not flattened into `node_modules` and that only the things you install are on type level. You should change the title to something like `feature request: Suppress missing package.json warnings when installing with set prefix.`

**Comment by jcferrer** [comment]
Ok I updated the title. Thanks.

**Comment by legodude17** [comment]
Any comment on this @zkat or @KenanY?

**Comment by KenanY** [comment]
This reminds me of https://github.com/npm/npm/issues/9161, wherein other users requested this warning to be removed. I assume that @othiym23's comments still stand.

**Comment by sudosoph** [comment]
`npm init`
http://weaintplastic.github.io/web-development-field-guide/Development/Frontend_Development/Setting_up_your_project/Setup_Dependency_Managers/Node_Package_Manager/Initialize_NPM_on_a_new_project.html

**Comment by sudosoph** [comment]
If you don't initialize your repo using `npm init` and complete package.json fields properly (or leave some blank), you might still get warnings. I followed this template and errors are gone: https://docs.npmjs.com/getting-started/using-a-package.json
