### ISSUE TITLE
 fetch failed with status code 503

### ISSUE THREAD

**Issue by umesh-kaushik** [npm/npm#14550]
#### I'm opening this issue because:

  - [ ] npm is crashing.

#### What's going wrong?

I am running npm install and it is crashing every time.

### supporting information:

 - `npm -v` prints: 2.15.11
 - `node -v` prints: v0.10.36
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: OS X
 - Network issues:
   - Geographic location where npm was run: India
 
log flie:
0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli   '/Users/UmeshKoushik/.nvm/v0.10.36/bin/npm',
1 verbose cli   'install' ]
2 info using npm@2.15.11
3 info using node@v0.10.36
4 verbose readDependencies loading dependencies from /Users/UmeshKoushik/source/haakon-env/package.json
5 verbose install where, deps [ '/Users/UmeshKoushik/source/haakon-env', [ 'ttab' ] ]
6 verbose install where, peers [ '/Users/UmeshKoushik/source/haakon-env', [] ]
7 verbose installManyTop reading for lifecycle /Users/UmeshKoushik/source/haakon-env/package.json
8 info preinstall haakon-env@0.0.1
9 verbose readDependencies loading dependencies from /Users/UmeshKoushik/source/haakon-env/package.json
10 silly cache add args [ 'ttab@^0.3.1', null ]
11 verbose cache add spec ttab@^0.3.1
12 silly cache add parsed spec { raw: 'ttab@^0.3.1',
12 silly cache add   scope: null,
12 silly cache add   name: 'ttab',
12 silly cache add   rawSpec: '^0.3.1',
12 silly cache add   spec: '>=0.3.1 <0.4.0',
12 silly cache add   type: 'range' }
13 silly addNamed ttab@>=0.3.1 <0.4.0
14 verbose addNamed ">=0.3.1 <0.4.0" is a valid semver range for ttab
15 silly addNameRange { name: 'ttab', range: '>=0.3.1 <0.4.0', hasData: false }
16 silly mapToRegistry name ttab
17 silly mapToRegistry using default registry
18 silly mapToRegistry registry https://registry.npmjs.org/
19 silly mapToRegistry data { raw: 'ttab',
19 silly mapToRegistry   scope: null,
19 silly mapToRegistry   name: 'ttab',
19 silly mapToRegistry   rawSpec: '',
19 silly mapToRegistry   spec: 'latest',
19 silly mapToRegistry   type: 'tag' }
20 silly mapToRegistry uri https://registry.npmjs.org/ttab
21 verbose addNameRange registry:https://registry.npmjs.org/ttab not in flight; fetching
22 verbose request uri https://registry.npmjs.org/ttab
23 verbose request no auth needed
24 info attempt registry request try #1 at 14:54:11
25 verbose request using bearer token for auth
26 verbose request id be63896e0eb044aa
27 verbose etag "2PLCWDT5TA0B1J3P2TSKKNZ03"
28 http request GET https://registry.npmjs.org/ttab
29 http 304 https://registry.npmjs.org/ttab
30 verbose headers { 'cache-control': 'max-age=300',
30 verbose headers   'accept-ranges': 'bytes',
30 verbose headers   date: 'Mon, 07 Nov 2016 09:24:13 GMT',
30 verbose headers   via: '1.1 varnish',
30 verbose headers   connection: 'keep-alive',
30 verbose headers   'x-served-by': 'cache-sin6924-SIN',
30 verbose headers   'x-cache': 'MISS',
30 verbose headers   'x-cache-hits': '0',
30 verbose headers   'x-timer': 'S1478510653.739489,VS0,VE224',
30 verbose headers   vary: 'Accept-Encoding' }
31 silly get cb [ 304,
31 silly get   { 'cache-control': 'max-age=300',
31 silly get     'accept-ranges': 'bytes',
31 silly get     date: 'Mon, 07 Nov 2016 09:24:13 GMT',
31 silly get     via: '1.1 varnish',
31 silly get     connection: 'keep-alive',
31 silly get     'x-served-by': 'cache-sin6924-SIN',
31 silly get     'x-cache': 'MISS',
31 silly get     'x-cache-hits': '0',
31 silly get     'x-timer': 'S1478510653.739489,VS0,VE224',
31 silly get     vary: 'Accept-Encoding' } ]
32 verbose etag https://registry.npmjs.org/ttab from cache
33 verbose get saving ttab to /Users/UmeshKoushik/.npm/registry.npmjs.org/ttab/.cache.json
34 verbose correctMkdir /Users/UmeshKoushik/.npm correctMkdir not in flight; initializing
35 silly addNameRange number 2 { name: 'ttab', range: '>=0.3.1 <0.4.0', hasData: true }
36 silly addNameRange versions [ 'ttab',
36 silly addNameRange   [ '0.1.0',
36 silly addNameRange     '0.1.1',
36 silly addNameRange     '0.1.2',
36 silly addNameRange     '0.1.3',
36 silly addNameRange     '0.1.4',
36 silly addNameRange     '0.1.5',
36 silly addNameRange     '0.1.6',
36 silly addNameRange     '0.1.7',
36 silly addNameRange     '0.1.8',
36 silly addNameRange     '0.2.0',
36 silly addNameRange     '0.2.1',
36 silly addNameRange     '0.3.0',
36 silly addNameRange     '0.3.1',
36 silly addNameRange     '0.4.0',
36 silly addNameRange     '0.5.0' ] ]
37 silly addNamed ttab@0.3.1
38 verbose addNamed "0.3.1" is a plain semver version for ttab
39 silly mapToRegistry name ttab
40 silly mapToRegistry using default registry
41 silly mapToRegistry registry https://registry.npmjs.org/
42 silly mapToRegistry data { raw: 'ttab',
42 silly mapToRegistry   scope: null,
42 silly mapToRegistry   name: 'ttab',
42 silly mapToRegistry   rawSpec: '',
42 silly mapToRegistry   spec: 'latest',
42 silly mapToRegistry   type: 'tag' }
43 silly mapToRegistry uri https://registry.npmjs.org/ttab
44 verbose addRemoteTarball https://registry.npmjs.org/ttab/-/ttab-0.3.1.tgz not in flight; adding
45 verbose addRemoteTarball [ 'https://registry.npmjs.org/ttab/-/ttab-0.3.1.tgz',
45 verbose addRemoteTarball   '828b286c79accc2f7921cc631f69fe122a71355c' ]
46 info retry fetch attempt 1 at 14:54:14
47 info attempt registry request try #1 at 14:54:14
48 http fetch GET https://registry.npmjs.org/ttab/-/ttab-0.3.1.tgz
49 verbose request using bearer token for auth
50 http fetch 503 https://registry.npmjs.org/ttab/-/ttab-0.3.1.tgz
51 info retry will retry, error on last attempt: Error: server error 503
52 info attempt registry request try #2 at 14:54:25
53 http fetch GET https://registry.npmjs.org/ttab/-/ttab-0.3.1.tgz
54 verbose request using bearer token for auth
55 http fetch 503 https://registry.npmjs.org/ttab/-/ttab-0.3.1.tgz
56 info retry will retry, error on last attempt: Error: server error 503
57 info attempt registry request try #3 at 14:55:27
58 http fetch GET https://registry.npmjs.org/ttab/-/ttab-0.3.1.tgz
59 verbose request using bearer token for auth
60 http fetch 503 https://registry.npmjs.org/ttab/-/ttab-0.3.1.tgz
61 error fetch failed https://registry.npmjs.org/ttab/-/ttab-0.3.1.tgz
62 warn retry will retry, error on last attempt: Error: fetch failed with status code 503
63 info retry fetch attempt 2 at 14:55:39
64 info attempt registry request try #1 at 14:55:39
65 http fetch GET https://registry.npmjs.org/ttab/-/ttab-0.3.1.tgz
66 verbose request using bearer token for auth
67 http fetch 503 https://registry.npmjs.org/ttab/-/ttab-0.3.1.tgz
68 info retry will retry, error on last attempt: Error: server error 503
69 info attempt registry request try #2 at 14:55:51
70 http fetch GET https://registry.npmjs.org/ttab/-/ttab-0.3.1.tgz
71 verbose request using bearer token for auth
72 http fetch 503 https://registry.npmjs.org/ttab/-/ttab-0.3.1.tgz
73 info retry will retry, error on last attempt: Error: server error 503
74 info attempt registry request try #3 at 14:56:52
75 http fetch GET https://registry.npmjs.org/ttab/-/ttab-0.3.1.tgz
76 verbose request using bearer token for auth
77 http fetch 503 https://registry.npmjs.org/ttab/-/ttab-0.3.1.tgz
78 error fetch failed https://registry.npmjs.org/ttab/-/ttab-0.3.1.tgz
79 warn retry will retry, error on last attempt: Error: fetch failed with status code 503
80 info retry fetch attempt 3 at 14:57:54
81 info attempt registry request try #1 at 14:57:54
82 http fetch GET https://registry.npmjs.org/ttab/-/ttab-0.3.1.tgz
83 verbose request using bearer token for auth
84 http fetch 503 https://registry.npmjs.org/ttab/-/ttab-0.3.1.tgz
85 info retry will retry, error on last attempt: Error: server error 503
86 info attempt registry request try #2 at 14:58:06
87 http fetch GET https://registry.npmjs.org/ttab/-/ttab-0.3.1.tgz
88 verbose request using bearer token for auth
89 http fetch 503 https://registry.npmjs.org/ttab/-/ttab-0.3.1.tgz
90 info retry will retry, error on last attempt: Error: server error 503
91 info attempt registry request try #3 at 14:59:09
92 http fetch GET https://registry.npmjs.org/ttab/-/ttab-0.3.1.tgz
93 verbose request using bearer token for auth
94 http fetch 503 https://registry.npmjs.org/ttab/-/ttab-0.3.1.tgz
95 error fetch failed https://registry.npmjs.org/ttab/-/ttab-0.3.1.tgz
96 verbose stack Error: fetch failed with status code 503
96 verbose stack     at Request.<anonymous> (/Users/UmeshKoushik/.nvm/v0.10.36/lib/node_modules/npm/node_modules/npm-registry-client/lib/fetch.js:51:14)
96 verbose stack     at Request.emit (events.js:95:17)
96 verbose stack     at Request.onRequestResponse (/Users/UmeshKoushik/.nvm/v0.10.36/lib/node_modules/npm/node_modules/request/request.js:954:10)
96 verbose stack     at ClientRequest.emit (events.js:95:17)
96 verbose stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1693:21)
96 verbose stack     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:122:23)
96 verbose stack     at CleartextStream.socketOnData [as ondata] (http.js:1588:20)
96 verbose stack     at CleartextStream.read [as _read] (tls.js:514:12)
96 verbose stack     at CleartextStream.Readable.read (_stream_readable.js:341:10)
96 verbose stack     at EncryptedStream.write [as _write] (tls.js:369:25)
97 verbose cwd /Users/UmeshKoushik/source/haakon-env
98 error Darwin 15.6.0
99 error argv "node" "/Users/UmeshKoushik/.nvm/v0.10.36/bin/npm" "install"
100 error node v0.10.36
101 error npm  v2.15.11
102 error fetch failed with status code 503
103 error If you need help, you may report this error at:
103 error     <https://github.com/npm/npm/issues>
104 verbose exit [ 1, true ]

**Comment by chongwang87** [comment]
same here

npm 4.0.2
node 4.6.1
ubuntu & mac os

**Comment by claudiofrs** [comment]
yep, same here. `npm install` and the feedback is `fetch failed with code 503`

**Comment by talk2cerlin** [comment]
[this](https://github.com/npm/npm/issues/14549#issuecomment-258792752) comment has a solution

**Comment by tusharmath** [comment]
Facing the same issue — 
<img width="1181" alt="screen shot 2016-11-07 at 3 50 50 pm" src="https://cloud.githubusercontent.com/assets/194482/20054326/7578e970-a502-11e6-875b-4b980ea36901.png">

**Comment by Mounika-Akula** [comment]
I'm facing the same issue, Unable to install any of the node modules

**Comment by M1chaelTran** [comment]
same issue here!!!
over an hour of googling and tried it on different computers and network... all failed!

urgent solution needed

**Comment by w0w** [comment]
Facing same issues on multiple servers, deployment failing big time.

**Comment by ganeshhfs** [comment]
Facing same problem.

**Comment by umesh-kaushik** [comment]
tried to change the registry got following error:
Error: fetch failed with status code 404

**Comment by umesh-kaushik** [comment]
it has started working.

**Comment by KenanY** [comment]
Closing as resolved. See <https://npmjs.statuspage.io/incidents/vwyj9jzcc4zn>
