### ISSUE TITLE
repository not exist

### ISSUE THREAD

**Issue by credencysrajesh** [npm/npm#14554]
#### I'm opening this issue because:

  - [ npm install csurf]  is crashing.

as below file not exists

https://registry.npmjs.org/csrf/-/csrf-3.0.3.tgz

please help ASAP

**Comment by KenanY** [comment]
@credencysrajesh Could you please provide the error you are seeing? You can upload your `npm-debug.log` to <https://gist.github.com/> and link it here.

**Comment by KenanY** [comment]
Closing as abandoned.
