### ISSUE TITLE
shasum check failed 

### ISSUE THREAD

**Issue by janusnjanus** [npm/npm#14556]
#### I'm opening this issue because:

npm is crashing.

#### What's going wrong?

I am getting several errors upon executing this command on Xubuntu;

npm install -g yo generator-hubot

following instructions from this post https://arthacker.net/how-to-install-hubot-on-ubuntu-14-04-lts-de3263cead51#.2c45h2a4f

i assume maybe my mistake was jumping command when i reached the step where i must do;
sudo ln -s /usr/bin/nodejs /usr/bin/node

but i got an error of file exist, thus i assumed it is good then so i moved to the following step i mentioned above which produced the error.

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:

I don't use a proxy

 - Container:

   - [ ] I develop using Xubuntu

**Comment by legodude17** [comment]
Hello @janusnjanus! You didn't say the error in the comment. What was the error you encountered?

**Comment by janusnjanus** [comment]
I apologies i thought i attached the npm-debug.log, this time it is attached.

and in short this is the output in terminal;

`root@sa-VPCW11S1E:/home/sa# npm install -g yo generator-hubot
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! Linux 4.4.0-45-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "yo" "generator-hubot"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.9

npm ERR! shasum check failed for /tmp/npm-4682-604231ef/registry.npmjs.org/rx/-/rx-2.5.3.tgz
npm ERR! Expected: 21adc7d80f02002af50dae97fd9dbf248755f566
npm ERR! Actual:   84e6ac5ecfa4396589730d136d466c7e41c15a4a
npm ERR! From:     https://registry.npmjs.org/rx/-/rx-2.5.3.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/sa/npm-debug.log

root@sa-VPCW11S1E:~# npm -v
3.10.9
root@sa-VPCW11S1E:~# node -v
v7.0.0`
[npm-debug.log.zip](https://github.com/npm/npm/files/577735/npm-debug.log.zip)

**Comment by legodude17** [comment]
Try running `npm cache clean`.

**Comment by janusnjanus** [comment]
legodude17 thank you this got the yo generator working. but i am still having some difficulty interacting with Hubot. no response with this command or any command for that matter ( Hubot help ).

This is my Terminal log; http://paste.ofcode.org/tzk3tFA8TJRs63qP9eLkiT

any idea what am doing wrong if it is clear from the steps i took as it is shown in the terminal log ?

**Comment by KenanY** [comment]
Closing since this isn't an issue with `npm` anymore.
