### ISSUE TITLE
failed to install ejs module

### ISSUE THREAD

**Issue by kvinayak43** [npm/npm#14551]
#### I'm opening this issue because:

  
  - [ ] npm is producing an incorrect install.

$ npm install ejs
npm ERR! fetch failed https://registry.npmjs.org/ejs/-/ejs-2.5.2.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503
npm ERR! fetch failed https://registry.npmjs.org/ejs/-/ejs-2.5.2.tgz
npm WARN retry will retry, error on last attempt: Error: read ECONNRESET
npm ERR! fetch failed https://registry.npmjs.org/ejs/-/ejs-2.5.2.tgz
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "ejs"
npm ERR! node v4.6.1
npm ERR! npm  v2.15.9

npm ERR! fetch failed with status code 503
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\cygwin64\home\vinayak\npm-debug.log

**Comment by KenanY** [comment]
This is a registry issue, see <https://npmjs.statuspage.io/incidents/vwyj9jzcc4zn>
