### ISSUE TITLE
getting an error when starting the node

### ISSUE THREAD

**Issue by Ruchi1990** [npm/npm#14560]
<details>
<pre>
0 info it worked if it ends with ok
1 verbose cli [ '/home/rgupta/.nvm/versions/node/v6.1.0/bin/node',
1 verbose cli   '/home/rgupta/.nvm/versions/node/v6.1.0/bin/npm',
1 verbose cli   'start' ]
2 info using npm@3.10.9
3 info using node@v6.1.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle app@0.0.0~prestart: app@0.0.0
6 silly lifecycle app@0.0.0~prestart: no script for prestart, continuing
7 info lifecycle app@0.0.0~start: app@0.0.0
8 verbose lifecycle app@0.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle app@0.0.0~start: PATH: /home/rgupta/.nvm/versions/node/v6.1.0/lib/node_modules/npm/bin/node-gyp-bin:/home/rgupta/mergeDataAngularApp/node_modules/.bin:/home/rgupta/.nvm/versions/node/v6.1.0/bin:/home/rgupta/mongodb/mongodb-linux-x86_64-ubuntu1404-3.2.6/bin:/home/rgupta/.composer/vendor/bin:/opt/idea/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/usr/local/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/usr/local/bin:/usr/local/bin:/usr/lib/jvm/jdk1.7.0_79/bin/:/home/rgupta/hadoop/hadoop-2.6.3/bin
10 verbose lifecycle app@0.0.0~start: CWD: /home/rgupta/mergeDataAngularApp
11 silly lifecycle app@0.0.0~start: Args: [ '-c', 'node ./bin/www' ]
12 silly lifecycle app@0.0.0~start: Returned: code: 1  signal: null
13 info lifecycle app@0.0.0~start: Failed to exec start script
14 verbose stack Error: app@0.0.0 start: `node ./bin/www`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/home/rgupta/.nvm/versions/node/v6.1.0/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/home/rgupta/.nvm/versions/node/v6.1.0/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid app@0.0.0
16 verbose cwd /home/rgupta/mergeDataAngularApp
17 error Linux 3.19.0-15-generic
18 error argv "/home/rgupta/.nvm/versions/node/v6.1.0/bin/node" "/home/rgupta/.nvm/versions/node/v6.1.0/bin/npm" "start"
19 error node v6.1.0
20 error npm  v3.10.9
21 error code ELIFECYCLE
22 error app@0.0.0 start: `node ./bin/www`
22 error Exit status 1
23 error Failed at the app@0.0.0 start script 'node ./bin/www'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the app package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node ./bin/www
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs app
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls app
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
</pre>
</details>

**Comment by legodude17** [comment]
This is a problem with `app@0.0.0` not with `npm`.

**Comment by KenanY** [comment]
@Ruchi1990 Try running `node ./bin/www` from your command-line.

**Comment by KenanY** [comment]
Closing due to no further responses.
