### ISSUE TITLE
After installation cordova asks to install

### ISSUE THREAD

**Issue by frb999** [npm/npm#14562]
From the C:\Users\FRB\AppData\Roaming\npm\node_modules\cordova folder, I have run:
npm install
There is a warning to update to minimatch 3.0.2  and it appears to have been installed.

However when I run cordova, I get a message to run npm install from that folder.

What could be the problem?

I had cordova installed earlier and it worked fine till now.

**Comment by legodude17** [comment]
Why is cordova in the `npm/node_modules`? What are you trying to do?
