### ISSUE TITLE
electron-packager ERROR

### ISSUE THREAD

**Issue by enrriquemicro** [npm/npm#14561]
electron-packager MUESTREO --version=1.4.5 --platform=win32 --arch=x64
Packaging app for platform win32 x64 using electron v1.4.5
Command failed: C:\WINDOWS\system32\cmd.exe /s /c "npm prune --production"
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "prune" "--production"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5

npm ERR! Invalid name: "MUESTREO ESTADÍSTICO"
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\IPIBA\AppData\Local\Temp\electron-packager\win32-x64\MUESTREO ESTADÍSTICO-win32-x64\resources\app\npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@2.15.5
3 info using node@v4.4.5
4 verbose readDependencies loading dependencies from D:\IPIBA\SOFTWARE\ORIGINALES\MUESTREO\package.json
5 error install Couldn't read dependencies
6 verbose stack Error: Invalid name: "MUESTREO ESTADÍSTICO"
6 verbose stack     at ensureValidName (C:\Program Files\nodejs\node_modules\npm\node_modules\normalize-package-data\lib\fixer.js:336:15)
6 verbose stack     at Object.module.exports.fixNameField (C:\Program Files\nodejs\node_modules\npm\node_modules\normalize-package-data\lib\fixer.js:215:5)
6 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\normalize-package-data\lib\normalize.js:32:38
6 verbose stack     at Array.forEach (native)
6 verbose stack     at normalize (C:\Program Files\nodejs\node_modules\npm\node_modules\normalize-package-data\lib\normalize.js:31:15)
6 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:349:5)
6 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:124:5)
6 verbose stack     at ReadFileContext.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:295:20)
6 verbose stack     at ReadFileContext.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16)
6 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:303:13)
7 verbose cwd D:\IPIBA\SOFTWARE\ORIGINALES\MUESTREO
8 error Windows_NT 10.0.14393
9 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
10 error node v4.4.5
11 error npm  v2.15.5
12 error Invalid name: "MUESTREO ESTADÍSTICO"
13 error If you need help, you may report this error at:
13 error     <https://github.com/npm/npm/issues>
14 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@enrriquemicro Uppercase letters, spaces, and accented characters are all not allowed to be in a package name. Try changing the `"name"` property of your `package.json` to something else.

**Comment by enrriquemicro** [comment]
THANK YOU...
