### ISSUE TITLE
Cannot find module 'internal/fs'

### ISSUE THREAD

**Issue by nextRainbow** [npm/npm#14579]
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'internal/fs' ]
2 info using npm@3.10.9
3 info using node@v7.1.0
4 verbose stack Error: Cannot find module 'internal/fs'
4 verbose stack     at Function.Module._resolveFilename (module.js:472:15)
4 verbose stack     at Function.Module._load (module.js:420:25)
4 verbose stack     at Module.require (module.js:500:17)
4 verbose stack     at require (internal/module.js:20:19)
4 verbose stack     at evalmachine.<anonymous>:17:20
4 verbose stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/cmd-shim/node_modules/graceful-fs/fs.js:11:1)
4 verbose stack     at Module._compile (module.js:573:32)
4 verbose stack     at Object.Module._extensions..js (module.js:582:10)
4 verbose stack     at Module.load (module.js:490:32)
4 verbose stack     at tryModuleLoad (module.js:449:12)
5 verbose cwd /Users/rainbow/Downloads/joint1.0.2
6 error Darwin 16.0.0
7 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "internal/fs"
8 error node v7.1.0
9 error npm  v3.10.9
10 error code MODULE_NOT_FOUND
11 error Cannot find module 'internal/fs'
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]
```

**Comment by legodude17** [comment]
Why are you installing `internal/fs`?

**Comment by nextRainbow** [comment]
I fork the jointjs,in joint dir,have a  package.json, I get the command "npm install".and then the error happend in the processing.
the content of the package.json is:
{
  "name": "jointjs",
  "title": "JointJS",
  "description": "JavaScript diagramming library",
  "keywords": [
    "diagram",
    "flowchart",
    "graph",
    "visualization"
  ],
  "scripts": {
    "test": "grunt test"
  },
  "version": "1.0.2",
  "main": "./dist/joint.min.js",
  "style": "./dist/joint.min.css",
  "homepage": "http://jointjs.com",
  "author": {
    "name": "client IO",
    "url": "http://client.io"
  },
  "contributors": [
    "David Durman <daviddurman@gmail.com> (https://github.com/DavidDurman)",
    "Roman Bruckner <bruckner.roman@gmail.com> (https://github.com/kumilingus)",
    "Emanuele Palombo <emanuele@client.io> (https://github.com/elbowz)",
    "Charles Hill <chill@degreesofzero.com> (https://github.com/chill117)",
    "Daniel K. (https://github.com/FredyC)",
    "Vladimir Talas (https://github.com/vtalas)",
    "Petr Skala (https://github.com/pskala)"
  ],
  "repository": {
    "type": "git",
    "url": "https://github.com/clientIO/joint.git"
  },
  "bugs": {
    "url": "https://github.com/clientIO/joint/issues"
  },
  "license": "MPL-2.0",
  "dependencies": {
    "backbone": "1.3.3",
    "dagre": "0.7.4",
    "graphlib": "1.0.7",
    "jquery": "2.2.4",
    "lodash": "3.10.1"
  },
  "devDependencies": {
    "async": "2.0.1",
    "chai": "3.5.0",
    "cheerio": "0.20.0",
    "express": "4.14.0",
    "grunt": "1.0.1",
    "grunt-browserify": "5.0.0",
    "grunt-compile-docs": "1.2.0",
    "grunt-contrib-clean": "1.0.0",
    "grunt-contrib-concat": "1.0.1",
    "grunt-contrib-copy": "1.0.0",
    "grunt-contrib-csslint": "1.0.0",
    "grunt-contrib-cssmin": "1.0.1",
    "grunt-contrib-qunit": "1.2.0",
    "grunt-contrib-uglify": "2.0.0",
    "grunt-contrib-watch": "1.0.0",
    "grunt-eslint": "19.0.0",
    "grunt-mocha-test": "0.12.7",
    "grunt-newer": "1.2.0",
    "grunt-shell": "1.3.0",
    "grunt-webpack": "1.0.14",
    "handlebars": "4.0.5",
    "load-grunt-tasks": "3.5.0",
    "mocha": "2.5.3",
    "open-sans-fontface": "https://github.com/clientIO/open-sans/archive/1.4.2.tar.gz",
    "phantomjs-prebuilt": "2.1.7",
    "prismjs": "1.5.1",
    "selenium-standalone": "5.1.0",
    "serve-static": "1.11.1",
    "should": "11.0.0",
    "sinon": "1.17.5",
    "time-grunt": "1.4.0",
    "webdriverio": "4.0.8",
    "webpack": "1.13.1",
    "webpack-dev-server": "1.14.1"
  }

**Comment by legodude17** [comment]
This is most likely a problem with a dependency of a dependency of the package you are using.

**Comment by chadfurman** [comment]
I'm also having this problem.  

```
[22:40:35] Requiring external module babel-register
Error: Cannot find module 'internal/fs'
at Function.Module._resolveFilename (module.js:472:15)
at Function.Module._load (module.js:420:25)
at Module.require (module.js:500:17)
at require (internal/module.js:20:19)
at evalmachine.<anonymous>:17:20
at Object.<anonymous> (/code/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:11:1)
at Module._compile (module.js:573:32)
at Module._extensions..js (module.js:582:10)
at Object.require.extensions.(anonymous function) [as .js] (/code/node_modules/babel-register/lib/node.js:166:7)
at Module.load (module.js:490:32)

No trouble in node 6, only in node 7.  Tried `npm cache clean` with no success.

Looks like it's something to do with graceful-fs, maybe?  Or something else deeper in core?

**Comment by sam-github** [comment]
What version of graceful-fs are you using? Sounds like the one that was deprecated as "this isn't going to work soon" is now not working.

**Comment by chadfurman** [comment]
@sam-github babel-register is loading _something_ that includes `vinyl-fs@>=0.3.0 <0.4.0` which is resolving to `vinyl-fs@0.3.14` which includes `graceful-fs@^3.0.0` which matches against the `graceful-fs@>=4.1.2 < 5.0.0` in another package dependency and thus I have `graceful-fs@4.1.4` -- so you're probably right.  I have the wrong version of graceful-fs.

Long story short, I pinned my node version to 6.*.*

**Comment by ektaverma1** [comment]
I am also facing the same issue on my local machine.
`node -v => v7.0.0`
`npm  -v => v3.3.9`

When I try to run `npm install`, I get the below error: 

```
angular2-demo ektaverma$ npm install
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.0.0
npm ERR! npm  v3.3.9
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'internal/fs'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

**Comment by JoshMcCullough** [comment]
Trashing my local `node_modules` and then reinstalling fixed this for me.

**Comment by ektaverma1** [comment]
Thanks. Yes I figured out. I wiped everything in `/usr/local/lib/node_modules` and reinstalled node and now it works fine.

**Comment by LeonardPauli** [comment]
JoshMcCullough/ektaverma1 answer worked partly for me. A simpler fix might have been to just
`curl -0 -L https://npmjs.org/install.sh | sudo sh`
according to [tj/n#working-with-npm](https://github.com/tj/n#working-with-npm).
