### ISSUE TITLE
npm view shows nothing for some packages after node 7.1.0

### ISSUE THREAD

**Issue by alanpurple** [npm/npm#14574]
#### I'm opening this issue because:
  - [ ] npm is doing something I don't understand.

#### What's going wrong?
npm view shows nothing for particular packages(e.g., webpack, npm, etc )

#### How can the CLI team reproduce the problem?

Windows 10 x64, nodeJS 7.1.0 x64, npm 3.10.9
powershell ->  npm view npm

**Comment by legodude17** [comment]
Can anyone reproduce? @zkat or @KenanY?

**Comment by KenanY** [comment]
Building Node.js v7.1.0 now.

**Comment by KenanY** [comment]
Can't reproduce with Node.js v7.1.0, `npm@4.0.2`, on Linux. Might be worthwhile to see verbose output (i.e. `npm view -ddd npm`

**Comment by legodude17** [comment]
Yes, also this might be a windows problem.

**Comment by alanpurple** [comment]
@KenanY  npm view -ddd npm shows fine result

**Comment by KenanY** [comment]
@alanpurple And `npm view npm` doesn't?

**Comment by alanpurple** [comment]
@KenanY yes,   npm view npm......shows some "skipping blahblah" then disappears.

npm 3.10.9 with NodeJS 7.0.0 was fine

**Comment by legodude17** [comment]
Can you show the output of both? Maybe in a gist?

**Comment by alanpurple** [comment]
![image](https://cloud.githubusercontent.com/assets/4515120/20198778/d9b508f8-a7e9-11e6-9b43-a0392ef81706.png)

**Comment by alanpurple** [comment]
I think only packages with massive versions has problem.

**Comment by legodude17** [comment]
That is very odd. I think you might be right. What do you mean 'huge versions'?

**Comment by alanpurple** [comment]
@legodude17 huge number of versions, huge thread of versions

**Comment by alanpurple** [comment]
@legodude17 
resolved after node v7.2.0

**Comment by KenanY** [comment]
Hmm, interesting. Closing as resolved then.
