### ISSUE TITLE
Cannot install modules

### ISSUE THREAD

**Issue by dhyanmohandas** [npm/npm#14573]
[npm-debug.txt](https://github.com/npm/npm/files/580733/npm-debug.txt)
![error](https://cloud.githubusercontent.com/assets/20661236/20139151/a7a6fb04-a6aa-11e6-8224-ed2fd5343185.JPG)

**Comment by legodude17** [comment]
Try running `npm cache clean`.

**Comment by dhyanmohandas** [comment]
I have tried that but still not working.

**Comment by legodude17** [comment]
Do you have any files left from old versions of `npm`? This is probably caused by the certificate that very old `npm` versions used.

**Comment by dhyanmohandas** [comment]
How can i solve that.. 
Can you please suggest a way to solve this?

**Comment by legodude17** [comment]
Where is `npm` installed? Try wiping that dir and reinstalling.
