### ISSUE TITLE
can't publish to sinopia

### ISSUE THREAD

**Issue by davidmricardo** [npm/npm#14571]
I'm unable to publish to sinopia

After the installation I change the registry and add my user to sinopia then when I publish it gives me the following error:

```
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "publish"
npm ERR! node v6.8.1
npm ERR! npm  v3.10.8

npm ERR! Unexpected token u in JSON at position 0
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\David Ricardo\Documents\work\framework\config\npm-debug.log
```

and the debug.log in the gist:

https://gist.github.com/davidmricardo/a5d7f4c8ec68a93787fa3204d115fd4c

My machine is windows10 and the server is linux, my npm is 3.10.8 and node is v6.8.1 I'm not using vpn and I think there is no proxy

**Comment by legodude17** [comment]
What does `curl http://tuleap.sysnovare.local:4873/@sysnovare%2fconfig?write=true` get you?

**Comment by davidmricardo** [comment]
In the attached file is the curl output

**Comment by legodude17** [comment]
What attached file? There is nothing there.

**Comment by othiym23** [comment]
Sinopia is returning `undefined`, so I'd look at how the Sinopia instance is configured. This doesn't look, at first glance, like an issue with the CLI.

**Comment by davidmricardo** [comment]
Sorry! I attached the file to mail and thought it would be here!
Here is the file I meant to send yesterday!

[curl.out.txt](https://github.com/npm/npm/files/585390/curl.out.txt)

**Comment by legodude17** [comment]
The result of the curl is a package with nothing in it. This does not appear to be a problem with the CLI.
