### ISSUE TITLE
unable to install cordova ionic

### ISSUE THREAD

**Issue by wongwmSunway** [npm/npm#14572]
#### I'm opening this issue because:

  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
unable to install cordova ionic

#### How can the CLI team reproduce the problem?
Unable to run the command above, error occurred.  Gist generated.

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:  Windows
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@wongwmSunway Please provide a link to the gist.

**Comment by wongwmSunway** [comment]
here's the link
https://gist.github.com/wongwmSunway/7d20195d9fdc3ce6d8807e1b57a213cb
thanks ya..

**Comment by KenanY** [comment]
@wongwmSunway Does this also occur with newer versions of `npm`?

**Comment by wongwmSunway** [comment]
how do i check whether the npm is new version? Do u mean i need to install
node.js v7.1?

**Comment by KenanY** [comment]
@wongwmSunway Sure, you can try that since newer versions of Node.js bundle newer versions of `npm`. Or you can check out <https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows>

**Comment by wongwmSunway** [comment]
Hi Kenan, case resolved.  Thanks a lot.
