### ISSUE TITLE
Error trying to install discordie through npm

### ISSUE THREAD

**Issue by GyllieGyllie** [npm/npm#14577]
#### I'm opening this issue because:

  - npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I'm trying to install a module called Discordie and get this error
https://gist.github.com/GyllieGyllie/c9a52962fbe00543eeaf1cb8a8e034b5

#### How can the CLI team reproduce the problem?

I've just installed npm on a linux env from amazon as explained in this tutorial http://iconof.com/blog/how-to-install-setup-node-js-on-amazon-aws-ec2-complete-guide/
Now i'm trying to install a module called Discordie but get error above

### supporting information:

 - `npm -v` prints: 1.1.0-2
 - `node -v` prints: v0.6.8
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux
 - Network issues:
   - Geographic location where npm was run: US West
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@GyllieGyllie Sorry, Node.js v0.6 and `npm@1.1` are years old and are no longer supported. I would suggest updating both before requesting any support.
