### ISSUE TITLE
Some packages not saving with caret before version

### ISSUE THREAD

**Issue by jsejcksn** [npm/npm#14578]
#### I'm opening this issue because:

  - [x] npm is doing something I don't understand.

#### What's going wrong?

When I `$ npm install eslint --savedev`, it produces this entry in my `package.json` file:

```
"devDependencies": {
  "eslint": "^3.9.1"
}
```

Notice the caret before the version number. When I install a package I've published in the same way `$ npm install @jsejcksn/eslint-config --savedev`, it does not add the caret:

```
"devDependencies": {
  "@jsejcksn/eslint-config": "0.0.6",
  "eslint": "^3.9.1"
}
```

What do I need to do in order to get npm to save my package with the caret so it will allow "compatible" version updates of my package?

#### How can the CLI team reproduce the problem?

I don't have a `npm-debug.log` file. ¯\\\_(ツ)_/¯ Try running the two commands above.

### supporting information:

- `npm -v` prints: **3.10.8**
- `node -v` prints: **v6.9.1**
- `npm config get registry` prints: **https://registry.npmjs.org/**
- `npm config get save-prefix` prints: **^**
 - Windows, OS X/macOS, or Linux?: **macOS**

**Comment by KenanY** [comment]
I think this is because `^0.0.6` is equivalent to `0.0.6`. Maybe try bumping at least the minor version?

**Comment by jsejcksn** [comment]
Oh, I didn't see this in the documentation until after you responded.

> Allows changes that do not modify the left-most non-zero digit in the `[major, minor, patch]` tuple. In other words, this allows patch and minor updates for versions `1.0.0` and above, patch updates for versions `0.X >=0.1.0`, and _no_ updates for versions `0.0.X`.
>
> _from [https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004](https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004)_

Is this what you're referencing?

**Comment by KenanY** [comment]
@jsejcksn Yup.
