### ISSUE TITLE
npm install --no-bin-links RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by AlexP11223** [npm/npm#14588]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I get this error when running `npm install --no-bin-links`

```
npm ERR! Linux 4.4.0-22-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--no-bin-links"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8

npm ERR! Maximum call stack size exceeded
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/t1/t1/npm-debug.log
```

`npm install` without `--no-bin-links` works, but it does not work with Vagrant + Windows host shared folders.

npm-debug.log

https://gist.github.com/AlexP11223/865c577caad51369b0b6c26f5555602c

```
.....
70480 silly build tunnel-agent@0.4.3
70481 silly build tweetnacl@0.14.3
70482 silly build bcrypt-pbkdf@1.0.0
70483 silly build sshpk@1.10.1
70484 silly build source-map@0.5.6
70485 silly build uglify-save-license@0.4.1
70486 silly build uglify-to-browserify@1.0.2
70487 silly build unc-path-regex@0.1.2
70488 silly build is-unc-path@0.1.1
70489 silly build is-relative@0.2.1
70490 verbose stack RangeError: Maximum call stack size exceeded
70490 verbose stack     at Object.color (/usr/lib/node_modules/npm/node_modules/npmlog/node_modules/console-control-strings/index.js:115:32)
70490 verbose stack     at EventEmitter.log._format (/usr/lib/node_modules/npm/node_modules/npmlog/log.js:252:51)
70490 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npmlog/log.js:138:24)
70490 verbose stack     at emitThree (events.js:116:13)
70490 verbose stack     at emit (events.js:194:7)
70490 verbose stack     at .<anonymous> (/usr/lib/node_modules/npm/node_modules/npmlog/node_modules/are-we-there-yet/tracker-group.js:23:18)
70490 verbose stack     at emitThree (events.js:116:13)
70490 verbose stack     at emit (events.js:194:7)
70490 verbose stack     at .<anonymous> (/usr/lib/node_modules/npm/node_modules/npmlog/node_modules/are-we-there-yet/tracker-group.js:23:18)
70490 verbose stack     at emitThree (events.js:116:13)
70490 verbose stack     at emit (events.js:194:7)
70491 verbose cwd /home/vagrant/t1/t1
70492 error Linux 4.4.0-22-generic
70493 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--no-bin-links"
70494 error node v6.9.1
70495 error npm  v3.10.8
70496 error Maximum call stack size exceeded
70497 error If you need help, you may report this error at:
70497 error     <https://github.com/npm/npm/issues>
70498 verbose exit [ 1, true ]
```

### supporting information:

 - `npm -v` prints: 3.10.8 (also tried 3.8.6)
 - `node -v` prints: v6.9.1 (also tried 5.12.0)
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Ubuntu vagrant box (Laravel Homestead, 0.5) with a fresh Laravel 5.3 project. Host is Windows 10.
 - Container:
   - [x] I develop using Vagrant on Windows.

**Comment by legodude17** [comment]
I have no idea what the problem is. Any ideas @KenanY?

**Comment by KenanY** [comment]
I know I've seen this reported before but I'm not sure why the flag causes such an error :(

**Comment by othiym23** [comment]
If you can share it, the `package.json` that blew up would be very helpful to have (don't need the package source, just `package.json`).

**Comment by AlexP11223** [comment]
```
{
  "private": true,
  "scripts": {
    "prod": "gulp --production",
    "dev": "gulp watch"
  },
  "devDependencies": {
    "bootstrap-sass": "^3.3.7",
    "gulp": "^3.9.1",
    "jquery": "^3.1.0",
    "laravel-elixir": "^6.0.0-9",
    "laravel-elixir-vue-2": "^0.2.0",
    "laravel-elixir-webpack-official": "^1.0.2",
    "lodash": "^4.16.2",
    "vue": "^2.0.1",
    "vue-resource": "^1.0.3"
  }
}
```

**Comment by AlexP11223** [comment]
Tried it on Windows without VM, got the same error. So I guess it is not related to VirtualBox/Vagrant or the box that I used.

https://gist.github.com/AlexP11223/9137626f7ebca44f7cfb954819df6360

**Comment by helio-frota** [comment]
Reproduced here too:


![a](https://cloud.githubusercontent.com/assets/6443576/20834330/87142b70-b873-11e6-9be9-0e4c072947ca.png)
![b](https://cloud.githubusercontent.com/assets/6443576/20834331/87150216-b873-11e6-96b6-7bf766b33528.png)

**Comment by helio-frota** [comment]
Also, If I run it a second time I get this error message:

`Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})`

```
hf@npmbox:~/bar$ npm install --no-bin-links
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN bar@1.0.0 No description
npm WARN bar@1.0.0 No repository field.
```

Possible the problem is related with this optional dependency ^
Since you are using linux too.

**Comment by legodude17** [comment]
That isn't an error. it is a warning. But you could be right.
