### ISSUE TITLE
Incorrect identification of the latest version of package

### ISSUE THREAD

**Issue by JFox-sk** [npm/npm#14583]
#### I'm opening this issue because:

  - [ ] npm incorrect identification of the latest version for nvd3 package.

Please see highlighted current and latest version:
![version_problem](https://cloud.githubusercontent.com/assets/2402129/20175623/fff59236-a743-11e6-87c5-0b857aa7c0b0.png)

Command `npm install nvd3` will install nvd3 version 1.7.1 instead of latest 1.8.4.

`npm show nvd3 versions` print:
![versions](https://cloud.githubusercontent.com/assets/2402129/20175871/499b41aa-a745-11e6-934d-8ca6a34050e5.png)

### supporting information:

 - `npm -v` prints: 3.10.9
 - `node -v` prints: v4.2.6
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows

**Comment by KenanY** [comment]
@JFox-sk If you run `npm show nvd3 dist-tags` you'll see that `1.7.1` is what's tagged as `latest`. If you do `npm show nvd3 time`, notice how `1.7.1` was published 3 months **after** `1.8.4`. hence by definition `1.7.1` is the `latest` version.

**Comment by JFox-sk** [comment]
Last version is 1.8.4. The reason a later publish v1.7.1 is described here: https://github.com/novus/nvd3/issues/1855 .
It can now be explicitly set as latest version 1.8.4?

**Comment by KenanY** [comment]
The [`npm dist-tag`](https://docs.npmjs.com/cli/dist-tag) command can be used to set the `latest` tag.
