### ISSUE TITLE
normalize tree sill install loadcurrenttree

### ISSUE THREAD

**Issue by Djabrail** [npm/npm#14589]
Ubuntu 16.04

node -v 
v4.2.6
npm -v
3.10.8

**Comment by othiym23** [comment]
Can you include either `npm-debug.log` or console output including a stack trace? Thanks for your time!

**Comment by Djabrail** [comment]
<img src="http://image.prntscr.com/image/34e5c3eb143141be9566f37821cdfdc4.png">

**Comment by Djabrail** [comment]
how to enable console output?

**Comment by Djabrail** [comment]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/local/bin/npm', 'uninstall', '-g' ]
2 info using npm@3.10.8
3 info using node@v4.2.6
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly install normalizeTree
8 silly loadCurrentTree Finishing
9 silly loadIdealTree Starting
10 silly install loadIdealTree
11 silly cloneCurrentTree Starting
12 silly install cloneCurrentTreeToIdealTree
13 silly cloneCurrentTree Finishing
14 silly loadShrinkwrap Starting
15 silly install loadShrinkwrap
16 silly loadShrinkwrap Finishing
17 silly loadAllDepsIntoIdealTree Starting
18 silly uninstall loadAllDepsIntoIdealtree
19 silly loadAllDepsIntoIdealTree Finishing
20 silly loadIdealTree Finishing
21 silly currentTree lib
22 silly idealTree lib
23 silly generateActionsToTake Starting
24 silly install generateActionsToTake
25 silly generateActionsToTake Finishing
26 silly diffTrees action count 0
27 silly decomposeActions action count 0
28 silly runTopLevelLifecycles Starting
29 silly executeActions Starting
30 silly install executeActions
31 silly doSerial global-install 0
32 silly doParallel fetch 0
33 verbose correctMkdir /home/djabrail/.npm/_locks correctMkdir not in flight; initializing
34 verbose lock using /home/djabrail/.npm/_locks/staging-a072192f34a17023.lock for /usr/lib/node_modules/.staging
35 verbose unlock done using /home/djabrail/.npm/_locks/staging-a072192f34a17023.lock for /usr/lib/node_modules/.staging
36 silly rollbackFailedOptional Starting
37 silly rollbackFailedOptional Finishing
38 silly runTopLevelLifecycles Finishing
39 silly install printInstalled
40 verbose stack Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/.staging'
40 verbose stack     at Error (native)
41 verbose cwd /home/djabrail
42 error Linux 4.4.0-38-generic
43 error argv "/usr/bin/nodejs" "/usr/local/bin/npm" "uninstall" "-g"
44 error node v4.2.6
45 error npm  v3.10.8
46 error path /usr/lib/node_modules/.staging
47 error code EACCES
48 error errno -13
49 error syscall mkdir
50 error Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/.staging'
50 error     at Error (native)
50 error  { [Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/.staging']
50 error   errno: -13,
50 error   code: 'EACCES',
50 error   syscall: 'mkdir',
50 error   path: '/usr/lib/node_modules/.staging' }
51 error Please try running this command again as root/Administrator.
52 verbose exit [ -13, true ]

**Comment by legodude17** [comment]
Does your user have write access to `/usr/lib/node_modules`?

**Comment by exstalis** [comment]
I have a similar problem installing frameworks like express. 
I attached npm-debug.log. it also show console error
```
npm ERR! network getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
```
I guess it's a network problem but I can't be sure.

**Comment by legodude17** [comment]
Do you have a proxy?

**Comment by Aisuko** [comment]
Same problem 
Platform: win10 x64 
                node.js v6.9.2  npm 3.10.9

I just want to set up cordova ....  😢 
![1](https://cloud.githubusercontent.com/assets/8053949/21512394/0eb6b664-cce8-11e6-882e-c75872046739.jpg)

**Comment by legodude17** [comment]
@Aisuko do you have a proxy?

**Comment by Aisuko** [comment]
@legodude17 

  I get a solution ,use vpn  and  cd lib/node_modules.   Thank you very much.

**Comment by ryancmoon** [comment]
I have this same problem and I do not have a proxy. In fact, I can `telnet registry.npmjs.org 443` and connect just fine from the box as that user. 

` npm ERR! Linux 3.13.0-106-generic
npm ERR! argv "/home/www-data/src/node-v7.4.0/bin/node" "/usr/local/bin/npm" "install" "--save" "express"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! syscall getaddrinfo
`

Can connect just fine not using npm:
`telnet registry.npmjs.org 443
Trying 151.101.56.162...
Connected to a.sni.fastly.net.
Escape character is '^]'.
`

**Comment by ajithvallabai** [comment]
i think if you are using vpn or made changes in proxy settings you may experience ethis

**Comment by KishanIos007** [comment]
I have same issue @Aisuko  con u please help me out

**Comment by KishanIos007** [comment]
I have this one 

D:\Projects\inonic>npm install -g ionic
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ionic"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10

npm ERR! error:0906D06C:PEM routines:PEM_read_bio:no start line
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Projects\inonic\npm-debug.log

**Comment by Aisuko** [comment]
@KishanIos007 
First, You need to keep the network useful.
May be you can try  `cd /d C:\Program Files\nodejs`  , and input `npm install -g ionic` to install . Or, You can add npm to system path.

**Comment by kryptophile** [comment]
I am having a similar problem using `npm install moment --save`
I tried changing the path to  `cd C:\Program Files\nodejs` 
Tried running as Administrator 
It is added to system path

![cap2](https://cloud.githubusercontent.com/assets/16337197/24183746/3be8216e-0ef0-11e7-9382-b67b677b3031.JPG)

![cap1](https://cloud.githubusercontent.com/assets/16337197/24183760/4707b15e-0ef0-11e7-9132-81ed4555a957.JPG)

npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'moment',
1 verbose cli   '--save' ]
2 info using npm@3.10.10
3 info using node@v6.10.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData moment
8 silly fetchNamedPackageData moment
9 silly mapToRegistry name moment
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'moment',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'moment',
12 silly mapToRegistry   name: 'moment',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/moment
14 verbose request uri https://registry.npmjs.org/moment
15 verbose request no auth needed
16 info attempt registry request try #1 at 10:48:40 AM
17 verbose request id a19c3a7e0371f368
18 http request GET https://registry.npmjs.org/moment
19 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
20 info attempt registry request try #2 at 10:48:56 AM
21 http request GET https://registry.npmjs.org/moment
22 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
23 info attempt registry request try #3 at 10:50:04 AM
24 http request GET https://registry.npmjs.org/moment
25 silly fetchPackageMetaData Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
25 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1022:11)
25 silly fetchPackageMetaData     at errnoException (dns.js:33:15)
25 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
25 silly fetchPackageMetaData  error for moment { Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
25 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1022:11)
25 silly fetchPackageMetaData     at errnoException (dns.js:33:15)
25 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
25 silly fetchPackageMetaData   code: 'EAI_AGAIN',
25 silly fetchPackageMetaData   errno: 'EAI_AGAIN',
25 silly fetchPackageMetaData   syscall: 'getaddrinfo',
25 silly fetchPackageMetaData   hostname: 'registry.npmjs.org',
25 silly fetchPackageMetaData   host: 'registry.npmjs.org',
25 silly fetchPackageMetaData   port: 443 }
26 silly rollbackFailedOptional Starting
27 silly rollbackFailedOptional Finishing
28 silly runTopLevelLifecycles Finishing
29 silly install printInstalled
30 verbose stack Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
30 verbose stack     at Object.exports._errnoException (util.js:1022:11)
30 verbose stack     at errnoException (dns.js:33:15)
30 verbose stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
31 verbose cwd C:\Users\HP\Documents\NodeJS
32 error Windows_NT 6.3.9600
33 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "moment" "--save"
34 error node v6.10.0
35 error npm  v3.10.10
36 error code EAI_AGAIN
37 error errno EAI_AGAIN
38 error syscall getaddrinfo
39 error getaddrinfo EAI_AGAIN registry.npmjs.org:443
40 error If you need help, you may report this error at:
40 error     <https://github.com/npm/npm/issues>
41 verbose exit [ 1, true ]

**Comment by legodude17** [comment]
Do you have a stable internet connection?

**Comment by RoboticRaven** [comment]
Do you have a firewall? If so, try deactivating. I get the same errors like you if i un-whitelist my VS install.

**Comment by jrtaylor-com** [comment]
I had the same issue but fixed when I realized that a private repo was prompting for a pw but the text for this prompt flashed for just a moment then hung displaying the "sill install..." text. So for my console on Mac OS X using Homebrew terminal profile there is a display issue.

**Comment by KuSoneverDie** [comment]
I had the same problem,
It's a proxy problem, you need to find your proxy setting 
In windows 7 command line follow this setting

1. npm set proxy http://[ntaccount]:[password]@[proxyservar]:[port]
2. npm set https-proxy http://[ntaccount]:[password]@[proxyservar]:[port]
3. npm install

Hope it helps
