### ISSUE TITLE
semver caret behavior differ between npm install and update on typescript module

### ISSUE THREAD

**Issue by shlomitc** [npm/npm#14586]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

`npm install` and `npm update` behaves differently when installing `typescript`

#### How can the CLI team reproduce the problem?
This is my package.json:
```
    {
      "name": "pr",
      "version": "1.0.0",
      "description": "",
      "main": "index.js",
      "scripts": {
        "test": "echo \"Error: no test specified\" && exit 1"
      },
      "author": "",
      "license": "ISC",
      "devDependencies": {
        "typescript": "^2.0.3"
      }
    }
```
When I run `npm install`, I get version 2.0.8
```
    ⇒  npm install
    pr@1.0.0 /Users/shlomitc/WebstormProjects/pr
    └── typescript@2.0.8
```
When I run `npm update` I get version 2.1.1!
```
    ⇒  npm update
    pr@1.0.0 /Users/shlomitc/WebstormProjects/pr
    └── typescript@2.1.1
```

### supporting information:

 - `npm -v` prints: 6.9.1
 - `node -v` prints: 3.10.8
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
I think the [`npm update`](https://docs.npmjs.com/cli/update) docs could be made a little clearer. You're getting `2.0.8` because that's the version that's tagged as `latest`, which is what `npm install` will go for by default if it matches your semver range (which it does here). `2.1.1` is the maximum version which satisfies that range, hence why `npm update` opts for it.

**Comment by legodude17** [comment]
What do you think the correct behavior is?

**Comment by KenanY** [comment]
I think current behavior is alright. If the behavior was the same between the two, then `npm install` and `npm update` would be indistinguishable from each other.

**Comment by legodude17** [comment]
Ok. Then should the docs be updated? The docs say that `npm update` will go for the latest tag too.
