### ISSUE TITLE
angularJS2 Quickstart not working

### ISSUE THREAD

**Issue by LittleHoopoe** [npm/npm#14585]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I'll go through this "Quickstart" https://angular.io/docs/ts/latest/quickstart.html 

Copy&Paste the package.json/tsconfig.json/systemjs.config.js

after that I run "npm install" and run in the ERR's
#### How can the CLI team reproduce the problem?

https://gist.github.com/LittleHoopoe/57e88e42ae8bc8cbb0c933d898947632

### supporting information:

 - `npm -v` prints: 3.10.8
 - `node -v` prints: v6.9.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/ macOS, or Linux?: macOS
 - Network issues:
   - Geographic location where npm was run: local on macOS
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@LittleHoopoe Could you try updating to `npm@4`?

**Comment by LittleHoopoe** [comment]
Hi KenanY, i tried this:

sudo npm cache clean -f (force) clear you npm cache
sudo npm install -g n install "n" (this might take a while)
sudo n stable upgrade to lastest version

still Version 3.10.8

**Comment by legodude17** [comment]
Try running `npm install -g npm@latest`.

**Comment by LittleHoopoe** [comment]
now my npm has Version 4.0.2. I'm a little busy right now, but I will try the angualarjs quickstart tutorial soon. Thanks for help!

**Comment by LittleHoopoe** [comment]
It's me again! First of all, thanks for your help guys. The quickstart tutorial has changed, now there is a git clone option and it's working for me now.
