### ISSUE TITLE
 error Error: UNKNOWN, mkdir 'E:\need\nodejs\node_global'

### ISSUE THREAD

**Issue by pingxiao** [npm/npm#14593]
5 error Error: UNKNOWN, mkdir 'E:\need\nodejs\node_global'
6 error If you need help, you may report this log at:
6 error     <http://github.com/isaacs/npm/issues>
6 error or email it to:
6 error     <npm-@googlegroups.com>
7 error System Windows_NT 6.1.7601
8 error command "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "ls"
9 error cwd C:\Users\Administrator
10 error node -v v0.8.16
11 error npm -v 1.1.69
12 error path E:\need\nodejs\node_global
13 error code UNKNOWN
14 error errno -1
15 verbose exit [ -1, true ]

**Comment by KenanY** [comment]
@pingxiao Sorry, `npm@1.1` is _years_ old and is no longer supported. If this is still an issue with the latest version of `npm` then let me know and I will happily reopen.
