### ISSUE TITLE
Incorrect install npm 3.10.8

### ISSUE THREAD

**Issue by Manuel-Aullo** [npm/npm#14594]
Hi hopefully someone can help.
I'm having this issue while i'm trying to install GULP, BOWER and NODEMON
Thanks.
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "gulp" "bower" "nodemon"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! path /usr/local/lib/node_modules/gulp/node_modules/ansi-styles
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules/gulp/node_modules/ansi-styles'
npm ERR!     at Error (native)
npm ERR!  { Error: EACCES: permission denied, access '/usr/local/lib/node_modules/gulp/node_modules/ansi-styles'
npm ERR!     at Error (native)
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules/gulp/node_modules/ansi-styles' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/manuel/npm-debug.log
Manu:~ manuel$ npm -v
3.10.8

**Comment by Odywan55** [comment]
try make them from sudo

**Comment by KenanY** [comment]
Yeah, looks like you have your global modules being install to `/usr/local` which your user does not have permission to access. Either use `sudo` to elevate your privileges or change your global modules directory to one which you have permissions to write to. Closing since this isn't an issue with `npm` itself.
