### ISSUE TITLE
support

### ISSUE THREAD

**Issue by Djabrail** [npm/npm#14590]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'cordova',
1 verbose cli   'ionic' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData cordova
8 silly fetchPackageMetaData ionic
9 silly fetchNamedPackageData cordova
10 silly mapToRegistry name cordova
11 silly mapToRegistry using default registry
12 silly mapToRegistry registry https://registry.npmjs.org/
13 silly mapToRegistry uri https://registry.npmjs.org/cordova
14 verbose request uri https://registry.npmjs.org/cordova
15 verbose request no auth needed
16 info attempt registry request try #1 at 3:05:32
17 verbose request id 2d7f415a299ed11b
18 http request GET https://registry.npmjs.org/cordova
19 silly fetchNamedPackageData ionic
20 silly mapToRegistry name ionic
21 silly mapToRegistry using default registry
22 silly mapToRegistry registry https://registry.npmjs.org/
23 silly mapToRegistry uri https://registry.npmjs.org/ionic
24 verbose request uri https://registry.npmjs.org/ionic
25 verbose request no auth needed
26 info attempt registry request try #1 at 3:05:32
27 http request GET https://registry.npmjs.org/ionic
28 info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=getaddrinfo EAI_AGAIN proxy.company.com:8080
29 info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=getaddrinfo EAI_AGAIN proxy.company.com:8080
30 info attempt registry request try #2 at 3:06:02
31 http request GET https://registry.npmjs.org/cordova
32 info attempt registry request try #2 at 3:06:02
33 http request GET https://registry.npmjs.org/ionic
34 info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=getaddrinfo EAI_AGAIN proxy.company.com:8080
35 info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=getaddrinfo EAI_AGAIN proxy.company.com:8080
36 info attempt registry request try #3 at 3:07:22
37 http request GET https://registry.npmjs.org/cordova
38 info attempt registry request try #3 at 3:07:22
39 http request GET https://registry.npmjs.org/ionic
40 silly fetchPackageMetaData Error: tunneling socket could not be established, cause=getaddrinfo EAI_AGAIN proxy.company.com:8080
40 silly fetchPackageMetaData     at ClientRequest.onError (/usr/share/npm/node_modules/request/node_modules/tunnel-agent/index.js:174:17)
40 silly fetchPackageMetaData     at ClientRequest.g (events.js:260:16)
40 silly fetchPackageMetaData     at emitOne (events.js:77:13)
40 silly fetchPackageMetaData     at ClientRequest.emit (events.js:169:7)
40 silly fetchPackageMetaData     at Socket.socketErrorListener (_http_client.js:258:9)
40 silly fetchPackageMetaData     at emitOne (events.js:77:13)
40 silly fetchPackageMetaData     at Socket.emit (events.js:169:7)
40 silly fetchPackageMetaData     at connectErrorNT (net.js:998:8)
40 silly fetchPackageMetaData     at nextTickCallbackWith2Args (node.js:441:9)
40 silly fetchPackageMetaData     at process._tickCallback (node.js:355:17)
40 silly fetchPackageMetaData  error for cordova { [Error: tunneling socket could not be established, cause=getaddrinfo EAI_AGAIN proxy.company.com:8080] code: 'ECONNRESET' }
41 silly fetchPackageMetaData Error: tunneling socket could not be established, cause=getaddrinfo EAI_AGAIN proxy.company.com:8080
41 silly fetchPackageMetaData     at ClientRequest.onError (/usr/share/npm/node_modules/request/node_modules/tunnel-agent/index.js:174:17)
41 silly fetchPackageMetaData     at ClientRequest.g (events.js:260:16)
41 silly fetchPackageMetaData     at emitOne (events.js:77:13)
41 silly fetchPackageMetaData     at ClientRequest.emit (events.js:169:7)
41 silly fetchPackageMetaData     at Socket.socketErrorListener (_http_client.js:258:9)
41 silly fetchPackageMetaData     at emitOne (events.js:77:13)
41 silly fetchPackageMetaData     at Socket.emit (events.js:169:7)
41 silly fetchPackageMetaData     at connectErrorNT (net.js:998:8)
41 silly fetchPackageMetaData     at nextTickCallbackWith2Args (node.js:441:9)
41 silly fetchPackageMetaData     at process._tickCallback (node.js:355:17)
41 silly fetchPackageMetaData  error for ionic { [Error: tunneling socket could not be established, cause=getaddrinfo EAI_AGAIN proxy.company.com:8080] code: 'ECONNRESET' }
42 silly rollbackFailedOptional Starting
43 silly rollbackFailedOptional Finishing
44 silly runTopLevelLifecycles Starting
45 silly runTopLevelLifecycles Finishing
46 silly install printInstalled
47 verbose stack Error: tunneling socket could not be established, cause=getaddrinfo EAI_AGAIN proxy.company.com:8080
47 verbose stack     at ClientRequest.onError (/usr/share/npm/node_modules/request/node_modules/tunnel-agent/index.js:174:17)
47 verbose stack     at ClientRequest.g (events.js:260:16)
47 verbose stack     at emitOne (events.js:77:13)
47 verbose stack     at ClientRequest.emit (events.js:169:7)
47 verbose stack     at Socket.socketErrorListener (_http_client.js:258:9)
47 verbose stack     at emitOne (events.js:77:13)
47 verbose stack     at Socket.emit (events.js:169:7)
47 verbose stack     at connectErrorNT (net.js:998:8)
47 verbose stack     at nextTickCallbackWith2Args (node.js:441:9)
47 verbose stack     at process._tickCallback (node.js:355:17)
48 verbose cwd /home/djabrail
49 error Linux 4.4.0-38-generic
50 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "cordova" "ionic"
51 error node v4.2.6
52 error npm  v3.5.2
53 error code ECONNRESET
54 error network tunneling socket could not be established, cause=getaddrinfo EAI_AGAIN proxy.company.com:8080
55 error network This is most likely not a problem with npm itself
55 error network and is related to network connectivity.
55 error network In most cases you are behind a proxy or have bad network settings.
55 error network
55 error network If you are behind a proxy, please make sure that the
55 error network 'proxy' config is set properly.  See: 'npm help config'
56 verbose exit [ 1, true ]

**Comment by legodude17** [comment]
Are you using a proxy or VPN?
