### ISSUE TITLE
Problem with   "meteor npm install --save babel-runtime"

### ISSUE THREAD

**Issue by K69G4JRA725W** [npm/npm#14598]
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\Administrator.WIN-3D2SKEQRIB1\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.2\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe" "C:\\Users\\Administrator.WIN-3D2SKEQRIB1\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.2\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "babel-runtime"
npm ERR! node v4.6.1
npm ERR! npm  v3.10.9
npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! syscall getaddrinfo

npm ERR! getaddrinfo EAI_AGAIN registry.npmjs.org:443
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\home\meteor\simple-todos\npm-debug.log

----------------------------------------------------------------------------------------------------------

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Users\\Administrator.WIN-3D2SKEQRIB1\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.2\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe',
1 verbose cli   'C:\\Users\\Administrator.WIN-3D2SKEQRIB1\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.2\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   'babel-runtime' ]
2 info using npm@3.10.9
3 info using node@v4.6.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData babel-runtime
8 silly fetchNamedPackageData babel-runtime
9 silly mapToRegistry name babel-runtime
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'babel-runtime',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'babel-runtime',
12 silly mapToRegistry   name: 'babel-runtime',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/babel-runtime
14 verbose request uri https://registry.npmjs.org/babel-runtime
15 verbose request no auth needed
16 info attempt registry request try #1 at 22:10:26
17 verbose request id b343e1a63a643a59
18 http request GET https://registry.npmjs.org/babel-runtime
19 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
20 info attempt registry request try #2 at 22:10:37
21 http request GET https://registry.npmjs.org/babel-runtime
22 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
23 info attempt registry request try #3 at 22:11:37
24 http request GET https://registry.npmjs.org/babel-runtime
25 silly fetchPackageMetaData Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
25 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:907:11)
25 silly fetchPackageMetaData     at errnoException (dns.js:32:15)
25 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:78:26)
25 silly fetchPackageMetaData  error for babel-runtime { [Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443]
25 silly fetchPackageMetaData   code: 'EAI_AGAIN',
25 silly fetchPackageMetaData   errno: 'EAI_AGAIN',
25 silly fetchPackageMetaData   syscall: 'getaddrinfo',
25 silly fetchPackageMetaData   hostname: 'registry.npmjs.org',
25 silly fetchPackageMetaData   host: 'registry.npmjs.org',
25 silly fetchPackageMetaData   port: 443 }
26 silly rollbackFailedOptional Starting
27 silly rollbackFailedOptional Finishing
28 silly runTopLevelLifecycles Finishing
29 silly install printInstalled
30 verbose stack Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
30 verbose stack     at Object.exports._errnoException (util.js:907:11)
30 verbose stack     at errnoException (dns.js:32:15)
30 verbose stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:78:26)
31 verbose cwd D:\home\meteor\simple-todos
32 error Windows_NT 6.1.7601
33 error argv "C:\\Users\\Administrator.WIN-3D2SKEQRIB1\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.2\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe" "C:\\Users\\Administrator.WIN-3D2SKEQRIB1\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.2\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "babel-runtime"
34 error node v4.6.1
35 error npm  v3.10.9
36 error code EAI_AGAIN
37 error errno EAI_AGAIN
38 error syscall getaddrinfo
39 error getaddrinfo EAI_AGAIN registry.npmjs.org:443
40 error If you need help, you may report this error at:
40 error     <https://github.com/npm/npm/issues>
41 verbose exit [ 1, true ]

**Comment by legodude17** [comment]
Please check your internet connection.
