### ISSUE TITLE
ERR after npm run sonus

### ISSUE THREAD

**Issue by chanjungkim** [npm/npm#14592]
[npm-debug.txt](https://github.com/npm/npm/files/585038/npm-debug.txt)

please help...

**Comment by legodude17** [comment]
Do you have a proxy or VPN?

**Comment by chanjungkim** [comment]
What is that??Do I need one of them?

**Comment by legodude17** [comment]
Because it could interfere with the connection and/or corrupt the files.

**Comment by legodude17** [comment]
It is better if you don't have one.
