### ISSUE TITLE
Npm list - expecting different results

### ISSUE THREAD

**Issue by yopbeast** [npm/npm#14604]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints: 3.10.9
 - `node -v` prints: 6.5.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: MacOSX Sierra
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

Hello, if i run:

```
$ npm init

$ npm install bootstrap@3.3.0 --save

$ npm install bootstrap@3.3.4 --save-dev

$ npm list --depth=0
```

result is:

```
someproject@1.0.0 /Users/me/Projects/someproject
└── bootstrap@3.3.4
```

why it list me 1 boostrap only if i have installed two of them in different versions ( one as dev and one as prod dependency)?

shouldn't this be something like:

```
someproject@1.0.0 /Users/me/Projects/someproject
    └── bootstrap@3.3.0
    └── bootstrap@3.3.4 dev
```

**Comment by KenanY** [comment]
@yopbeast You can only depend on one version of a particular package.
