### ISSUE TITLE
error fatal: ambiguous argument should contain the package name.

### ISSUE THREAD

**Issue by wnr** [npm/npm#14600]
#### What's the feature?
Include the package name in the case of `fatal: ambiguous argument 'foo': unknown revision or path not in the working tree.` error.

#### What problem is the feature intended to solve?
When a dependency in `package.json` points to a branch that does not exist, the error message does not mention the faulty dependency. This makes it very hard sometimes to track down the dependency that is wrong. In our project we have tons of dependencies which all point to a certain release branch, for instance `release/201705` so the `ambiguous argument 'foo'` message is not really helpful.

#### Is this a feature you're prepared to implement, with support from the npm CLI team?

Yes.

**Comment by legodude17** [comment]
This is a good idea. +1

**Comment by othiym23** [comment]
(Flagging this with `needs-discussion` because the code that caches Git dependencies may or may not know the name of the package originating the cache request, and threading that information into the request could turn out to be surprisingly difficult.)

**Comment by legodude17** [comment]
I am pretty sure that the place to do this would be `[lib/cache/add-remote-git.js#215](https://github.com/npm/npm/blob/latest/lib/cache/add-remote-git.js#L215)`.

**Comment by legodude17** [comment]
If that is the right place, then it doesn't have access to the name, but it could extract it from the `url`. 😖

**Comment by wnr** [comment]
How to proceed with this issue?

**Comment by legodude17** [comment]
I would suggest closing this and opening a new one, based on the above comments.

**Comment by wnr** [comment]
I'm not sure how the new issue should differ from this one. Have we decided that this is a feature that should be implemented?

**Comment by legodude17** [comment]
It looks to me that the place to put this should be able to access the correct information. Maybe we could ask @zkat or @iarna if a PR for this would be accepted?
