### ISSUE TITLE
 UNABLE_TO_VERIFY_LEAF_SIGNATURE

### ISSUE THREAD

**Issue by vipinkumar11** [npm/npm#14607]
I got below error while installing browser sync.

I also confirmed that my firewall was off while installing the package but still I got the following issue:-

```
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodej
node_modules\\npm\\bin\\npm-cli.js" "in
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code UNABLE_TO_VERIFY_LEAF_SIG

npm ERR! unable to verify the first cer
npm ERR!
npm ERR! If you need help, you may repo
npm ERR!     <https://github.com/npm/np

npm ERR! Please include the following f
npm ERR!     C:\Users\SNF\npm-debug.log
```

[npm-debug.txt](https://github.com/npm/npm/files/587341/npm-debug.txt)

**Comment by legodude17** [comment]
Try running `npm cache clean`.

**Comment by vipinkumar11** [comment]
Thanks but same issue is still there.

Log file:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'browser-sync' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData browser-sync
8 silly fetchNamedPackageData browser-sync
9 silly mapToRegistry name browser-sync
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'browser-sync',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'browser-sync',
12 silly mapToRegistry   name: 'browser-sync',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/browser-sync
14 verbose request uri https://registry.npmjs.org/browser-sync
15 verbose request no auth needed
16 info attempt registry request try #1 at 8:33:55 PM
17 verbose request id cebba809787b732b
18 http request GET https://registry.npmjs.org/browser-sync
19 info retry will retry, error on last attempt: Error: unable to verify the first certificate
20 info attempt registry request try #2 at 8:34:07 PM
21 http request GET https://registry.npmjs.org/browser-sync
22 info retry will retry, error on last attempt: Error: unable to verify the first certificate
23 info attempt registry request try #3 at 8:35:09 PM
24 http request GET https://registry.npmjs.org/browser-sync
25 silly fetchPackageMetaData Error: unable to verify the first certificate
25 silly fetchPackageMetaData     at Error (native)
25 silly fetchPackageMetaData     at TLSSocket.<anonymous> (_tls_wrap.js:1062:38)
25 silly fetchPackageMetaData     at emitNone (events.js:86:13)
25 silly fetchPackageMetaData     at TLSSocket.emit (events.js:185:7)
25 silly fetchPackageMetaData     at TLSSocket._finishInit (_tls_wrap.js:586:8)
25 silly fetchPackageMetaData     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38)
25 silly fetchPackageMetaData  error for browser-sync { Error: unable to verify the first certificate
25 silly fetchPackageMetaData     at Error (native)
25 silly fetchPackageMetaData     at TLSSocket.<anonymous> (_tls_wrap.js:1062:38)
25 silly fetchPackageMetaData     at emitNone (events.js:86:13)
25 silly fetchPackageMetaData     at TLSSocket.emit (events.js:185:7)
25 silly fetchPackageMetaData     at TLSSocket._finishInit (_tls_wrap.js:586:8)
25 silly fetchPackageMetaData     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38) code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE' }
26 silly rollbackFailedOptional Starting
27 silly rollbackFailedOptional Finishing
28 silly runTopLevelLifecycles Finishing
29 silly install printInstalled
30 verbose stack Error: unable to verify the first certificate
30 verbose stack     at Error (native)
30 verbose stack     at TLSSocket.<anonymous> (_tls_wrap.js:1062:38)
30 verbose stack     at emitNone (events.js:86:13)
30 verbose stack     at TLSSocket.emit (events.js:185:7)
30 verbose stack     at TLSSocket._finishInit (_tls_wrap.js:586:8)
30 verbose stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38)
31 verbose cwd C:\Users\SNF
32 error Windows_NT 6.3.9600
33 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "browser-sync"
34 error node v6.9.1
35 error npm  v3.10.8
36 error code UNABLE_TO_VERIFY_LEAF_SIGNATURE
37 error unable to verify the first certificate
38 error If you need help, you may report this error at:
38 error     <https://github.com/npm/npm/issues>
39 verbose exit [ 1, true ]

**Comment by legodude17** [comment]
Do you have any files from old versions of `npm`?
