### ISSUE TITLE
Maximum call stack size exceeded on npm install

### ISSUE THREAD

**Issue by GROX13** [npm/npm#14608]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other

#### What's going wrong?

I'm trying to run `npm install`, this is output from console:

    npm ERR! Linux 4.8.0-27-generic
    npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
    npm ERR! node v6.9.1
    npm ERR! npm  v3.10.8
    
    npm ERR! Maximum call stack size exceeded
    npm ERR! 
    npm ERR! If you need help, you may report this error at:
    npm ERR!     <https://github.com/npm/npm/issues>

and this is content of `npm-debug.log`:

    113791 verbose stack RangeError: Maximum call stack size exceeded
    113791 verbose stack     at Object.color (/usr/lib/node_modules/npm/node_modules/npmlog/node_modules/console-control-strings/index.js:115:32)
    113791 verbose stack     at EventEmitter.log._format (/usr/lib/node_modules/npm/node_modules/npmlog/log.js:252:51)
    113791 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npmlog/log.js:138:24)
    113791 verbose stack     at emitThree (events.js:116:13)
    113791 verbose stack     at emit (events.js:194:7)
    113791 verbose stack     at .<anonymous> (/usr/lib/node_modules/npm/node_modules/npmlog/node_modules/are-we-there-yet/tracker-group.js:23:18)
    113791 verbose stack     at emitThree (events.js:116:13)
    113791 verbose stack     at emit (events.js:194:7)
    113791 verbose stack     at .<anonymous> (/usr/lib/node_modules/npm/node_modules/npmlog/node_modules/are-we-there-yet/tracker-group.js:23:18)
    113791 verbose stack     at emitThree (events.js:116:13)
    113791 verbose stack     at emit (events.js:194:7)
    113792 verbose cwd /home/giorgi/AdMove/dev/web-advertiser-admove
    113793 error Linux 4.8.0-27-generic
    113794 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
    113795 error node v6.9.1
    113796 error npm  v3.10.8
    113797 error Maximum call stack size exceeded
    113798 error If you need help, you may report this error at:
    113798 error     <https://github.com/npm/npm/issues>
    113799 verbose exit [ 1, true ]

Removed `node_modules` several times and tried to reinstall. Can't understand what's the reason that causes this and how to fix it.

### supporting information:

 - `npm -v` prints: 3.10.8
 - `node -v` prints: v6.9.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Kubuntu 16.10 
 - [npm-debug.log](https://gist.github.com/GROX13/5515bcfd2cadd6b148b1715034bd92c6 )

**Comment by legodude17** [comment]
What is your `package.json`?

**Comment by GROX13** [comment]
```
{
  "name": "fus",
  "version": "1.4.2",
  "dependencies": {},
  "scripts": {
    "test": "gulp test"
  },
  "devDependencies": {
    "browser-sync": "~2.9.11",
    "browser-sync-spa": "~1.0.3",
    "chalk": "~1.1.1",
    "del": "~2.0.2",
    "eslint-plugin-angular": "~0.12.0",
    "estraverse": "~4.1.0",
    "gulp": "~3.9.0",
    "gulp-angular-filesort": "~1.1.1",
    "gulp-angular-templatecache": "~1.8.0",
    "gulp-autoprefixer": "~3.0.2",
    "gulp-clean-css": "^2.0.3",
    "gulp-cssnano": "~2.1.0",
    "gulp-eslint": "~1.0.0",
    "gulp-filter": "~3.0.1",
    "gulp-flatten": "~0.2.0",
    "gulp-htmlmin": "~1.3.0",
    "gulp-inject": "~3.0.0",
    "gulp-load-plugins": "~0.10.0",
    "gulp-ng-annotate": "~1.1.0",
    "gulp-protractor": "~1.0.0",
    "gulp-rename": "~1.2.2",
    "gulp-replace": "~0.5.4",
    "gulp-rev": "~6.0.1",
    "gulp-rev-replace": "~0.4.2",
    "gulp-sass": "~2.1.1",
    "gulp-size": "~2.0.0",
    "gulp-sourcemaps": "~1.6.0",
    "gulp-uglify": "~1.4.1",
    "gulp-useref": "~3.0.5",
    "gulp-util": "~3.0.6",
    "http-proxy-middleware": "~0.9.0",
    "karma": "~0.13.10",
    "karma-angular-filesort": "~1.0.0",
    "karma-coverage": "~0.5.2",
    "karma-jasmine": "~0.3.6",
    "karma-ng-html2js-preprocessor": "~0.2.0",
    "karma-phantomjs-launcher": "~1.0.0",
    "lodash": "~3.10.1",
    "main-bower-files": "~2.9.0",
    "phantomjs-prebuilt": "~2.1.3",
    "uglify-save-license": "~0.4.1",
    "wiredep": "~2.2.2",
    "wrench": "~1.5.8"
  },
  "engines": {
    "node": ">=0.10.0"
  }
}

```

**Comment by phantasiepixel** [comment]
Hey Grox13, I had the same problem - and then I had the idea, to uninstall the old "polymer-cli" (npm uninstall -g polymer-cli). And this was the solution! The following new installation (npm install -g polymer-cli) finished correct!

**Comment by GROX13** [comment]
Hi [phantasiepixel](https://github.com/phantasiepixel) thanks for your suggestion. I uninstalled everything possible but problem remained. Then I changed OS and it magically started to work. I just can't understand what could have been the problem. :unamused:

**Comment by legodude17** [comment]
For anyone who is redirected here, view #12676.
