### ISSUE TITLE
unable to install npm browser sync

### ISSUE THREAD

**Issue by vernwalrahul** [npm/npm#14606]
![screenshot 13](https://cloud.githubusercontent.com/assets/23414388/20239099/934efba4-a91e-11e6-9338-7ab119edfc96.png)

I am unable to install browser sync. Here, I am using my LAN port for that. Despite of setting the proxy, its showing the error.

**Comment by legodude17** [comment]
What is `npm config get registry`?

**Comment by danilowoz** [comment]
@vernwalrahul I had the same problem. The solution was run `npm cache clean`
