### ISSUE TITLE
Socket.io Installation Error

### ISSUE THREAD

**Issue by tom12321** [npm/npm#14613]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

Error installing socket.io

INPUT: npm install socket.io

RETURN:

npm http GET https://registry.npmjs.org/socket.io
npm http 304 https://registry.npmjs.org/socket.io
npm http GET https://registry.npmjs.org/engine.io/1.7.2
npm http GET https://registry.npmjs.org/socket.io-parser/2.3.1
npm http GET https://registry.npmjs.org/socket.io-client/1.5.1
npm http GET https://registry.npmjs.org/socket.io-adapter/0.4.0
npm http GET https://registry.npmjs.org/has-binary/0.1.7
npm http GET https://registry.npmjs.org/debug/2.2.0
npm http 304 https://registry.npmjs.org/socket.io-parser/2.3.1
npm http 304 https://registry.npmjs.org/engine.io/1.7.2
npm http 304 https://registry.npmjs.org/has-binary/0.1.7
npm http 304 https://registry.npmjs.org/socket.io-client/1.5.1
npm http 304 https://registry.npmjs.org/socket.io-adapter/0.4.0
npm http 304 https://registry.npmjs.org/debug/2.2.0
npm http GET https://registry.npmjs.org/socket.io-parser/2.2.2
npm http GET https://registry.npmjs.org/isarray/0.0.1
npm http GET https://registry.npmjs.org/json3/3.3.2
npm http GET https://registry.npmjs.org/component-emitter/1.1.2
npm http 304 https://registry.npmjs.org/isarray/0.0.1
npm http GET https://registry.npmjs.org/ms/0.7.1
npm http GET https://registry.npmjs.org/accepts/1.3.3
npm http GET https://registry.npmjs.org/base64id/0.1.0
npm http GET https://registry.npmjs.org/engine.io-parser/1.3.1
npm http GET https://registry.npmjs.org/ws/1.1.1
npm http 304 https://registry.npmjs.org/json3/3.3.2
npm http GET https://registry.npmjs.org/engine.io-client/1.7.2
npm http GET https://registry.npmjs.org/component-bind/1.0.0
npm http GET https://registry.npmjs.org/component-emitter/1.2.0
npm http GET https://registry.npmjs.org/object-component/0.0.3
npm http GET https://registry.npmjs.org/to-array/0.1.4
npm http GET https://registry.npmjs.org/backo2/1.0.2
npm http GET https://registry.npmjs.org/indexof/0.0.1
npm http GET https://registry.npmjs.org/parseuri/0.0.4
npm http 304 https://registry.npmjs.org/component-emitter/1.1.2
npm http 304 https://registry.npmjs.org/socket.io-parser/2.2.2
npm http 304 https://registry.npmjs.org/ms/0.7.1
npm http 304 https://registry.npmjs.org/accepts/1.3.3
npm http 304 https://registry.npmjs.org/engine.io-parser/1.3.1
npm http 304 https://registry.npmjs.org/ws/1.1.1
npm http 304 https://registry.npmjs.org/base64id/0.1.0
npm http 200 https://registry.npmjs.org/to-array/0.1.4
npm ERR! registry error parsing json
npm http GET https://registry.npmjs.org/debug/0.7.4
npm http GET https://registry.npmjs.org/json3/3.2.6
npm http GET https://registry.npmjs.org/benchmark/1.0.0
npm ERR! EEXIST, mkdir '/root/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib'
File exists: /root/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib
Move it away, and try again.

npm ERR! System Linux 3.13.0-100-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "socket.io"
npm ERR! cwd /root
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /root/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib
npm ERR! fstream_path /root/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/ErrorCodes.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code EEXIST
npm ERR! errno 47
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:171:23
npm ERR! fstream_stack /usr/lib/nodejs/mkdirp/index.js:37:53
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! error rolling back Error: ENOTEMPTY, rmdir '/root/node_modules/socket.io/node_modules/socket.io-parser/node_modules/json3'
npm ERR! error rolling back  socket.io@1.5.1 { [Error: ENOTEMPTY, rmdir '/root/node_modules/socket.io/node_modules/socket.io-parser/node_modules/json3']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: '/root/node_modules/socket.io/node_modules/socket.io-parser/node_modules/json3' }
npm ERR! SyntaxError: Unexpected token
npm ERR! �T�N�0�˼0�u(�V���Nb�=0���▒���l(U��;NҨ{�Um���{|��9^s#
�b F�(���eh���3L�▒▒Y���ilB��^�S�O~������:>Yo7��+c=���:�FB��t�Ef_:'W�ǟ�ym
                                                               ��qG��:X���aU�>:��r�
npm ERR! �I�Y�bQ��&[."���6�^Q���rі!��]
�g��g:��:_%��$7��
� K�s �bI�:#�c:n����;��ݻ�'_�B�@.��<�~�>�I6R�y��bk�����9,��H�w�s)�!��5߭m��c�l&������45��H}1go�M_eQ��أOͳt@:�U{��������~�?����c�S�� S6�
npm ERR! �.rm�р4�?ق��٨�F������2:�n��LR;6���}�d�g��[0L�]�if�R�6'�E�Ԛ�fzvq=���{��H��=�,���0���U����>g��|<Tj4��(Sr,G���pxD�R��G��
ϣ�Z�8Zέh=zaݢ�\����zooQ��s[O��=��io�A-�&����E��
                                              �x�����qן�S|/A�ݚk�᫩�
npm ERR!     at Object.parse (native)
npm ERR!     at RegClient.<anonymous> (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:238:23)
npm ERR!     at Request.self.callback (/usr/lib/nodejs/request/index.js:148:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/index.js:896:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/lib/nodejs/request/index.js:847:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-100-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "socket.io"
npm ERR! cwd /root
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type unexpected_token
npm http GET https://registry.npmjs.org/mime-types
npm http GET https://registry.npmjs.org/negotiator/0.6.1
npm ERR! Error: ENOENT, lstat '/root/node_modules/socket.io/node_modules/engine.io/node_modules/engine.io-parser/lib/index.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-100-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "socket.io"
npm ERR! cwd /root
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /root/node_modules/socket.io/node_modules/engine.io/node_modules/engine.io-parser/lib/index.js
npm ERR! fstream_path /root/node_modules/socket.io/node_modules/engine.io/node_modules/engine.io-parser/lib/index.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm http 304 https://registry.npmjs.org/engine.io-client/1.7.2
npm http 304 https://registry.npmjs.org/component-bind/1.0.0
npm http 304 https://registry.npmjs.org/component-emitter/1.2.0
npm http 304 https://registry.npmjs.org/object-component/0.0.3
npm http 200 https://registry.npmjs.org/backo2/1.0.2
npm ERR! registry error parsing json
KiTTYKiTTYKiTTYKiTTYKiTTYKiTTYnpm http 304 https://registry.npmjs.org/indexof/0.0.1
npm http 304 https://registry.npmjs.org/mime-types
npm http 304 https://registry.npmjs.org/benchmark/1.0.0
npm http 304 https://registry.npmjs.org/debug/0.7.4
npm http 304 https://registry.npmjs.org/negotiator/0.6.1
npm http 304 https://registry.npmjs.org/parseuri/0.0.4
npm http 304 https://registry.npmjs.org/json3/3.2.6
npm http GET https://registry.npmjs.org/mime-db
npm http 304 https://registry.npmjs.org/mime-db
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /root/npm-debug.log
npm ERR! not ok code 0
root@vultr:~# KiTTYKiTTYKiTTYKiTTYKiTTYKiTTY

**Comment by KenanY** [comment]
@tom12321 `npm@1.3` is years old and is no longer supported. If this is still an issue for your with `npm@>=2`, let me know and I will reopen this.
