### ISSUE TITLE
NPM install failures

### ISSUE THREAD

**Issue by scotmatson** [npm/npm#14610]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?
npm fails to install dependencies; notable examples being webpack and node-sass, but not limited to these examples.

I've exhausted all solutions I've found on the web. `Updating`, `cache cleaning`, `redefining registry`, `removing node_modules`, `testing on multiple machines and operating systems`, `rebuilding package.json from scratch`, `installing as sudo`.

Have reproduced error on multiple machines.

#### How can the CLI team reproduce the problem?
npm init (create a fresh init file)
npm install node-sass

### supporting information:

 - `npm -v` prints:1.3.10
 - `node -v` prints:v0.10.25
 - `npm config get registry` prints:http://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?:OSX and Linux (AWS:Ubuntu)
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by scotmatson** [comment]
Example output:

npm http 304 http://registry.npmjs.org/commander
npm http GET http://registry.npmjs.org/verror/1.3.6
npm http GET http://registry.npmjs.org/extsprintf/1.0.2
npm http GET http://registry.npmjs.org/json-schema/0.2.3
npm http 200 http://registry.npmjs.org/verror/1.3.6
npm ERR! registry error parsing json
npm http 304 http://registry.npmjs.org/extsprintf/1.0.2
npm http 304 http://registry.npmjs.org/json-schema/0.2.3
npm http GET http://registry.npmjs.org/graceful-readlink
npm ERR! Error: ENOENT, lstat '/srv/httpd/test/node_modules/node-sass/node_modules/request/node_modules/http-signature/node_modules/sshpk/lib/ed-compat.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-96-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "node-sass" "--save-dev"
npm ERR! cwd /srv/httpd/test
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /srv/httpd/test/node_modules/node-sass/node_modules/request/node_modules/http-signature/node_modules/sshpk/lib/ed-compat.js
npm ERR! fstream_path /srv/httpd/test/node_modules/node-sass/node_modules/request/node_modules/http-signature/node_modules/sshpk/lib/ed-compat.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm http 304 http://registry.npmjs.org/graceful-readlink
npm ERR! Error: ENOENT, open '/srv/httpd/test/node_modules/node-sass/node_modules/request/node_modules/har-validator/node_modules/pinkie-promise/node_modules/pinkie/readme.md'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-96-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "node-sass" "--save-dev"
npm ERR! cwd /srv/httpd/test
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /srv/httpd/test/node_modules/node-sass/node_modules/request/node_modules/har-validator/node_modules/pinkie-promise/node_modules/pinkie/readme.md
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! Error: ENOENT, lstat '/srv/httpd/test/node_modules/node-sass/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/test/misc.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-96-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "node-sass" "--save-dev"
npm ERR! cwd /srv/httpd/test
npm ERR! node -v v0.10.25

**Comment by scotmatson** [comment]
Guys it looks like something is broken in the registry `(http://registry.nodejs.org/, if anyone is looking for a fix, try 

`https://registry.cnpmjs.org/`

**Comment by KenanY** [comment]
@scotmatson Sorry, `npm@1.3` is years old and is no longer supported.

**Comment by scotmatson** [comment]
So weird. Why would that be the version installed then. I installed it with apt-get from the ubuntu:14.04 docker image which is why I never considered that the version would be an issue.

**Comment by KenanY** [comment]
@scotmatson Sounds like the repository `apt-get` is using is way behind on their `npm` versions. Usually I just suggest [updating `npm` with `npm` itself](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm).
