### ISSUE TITLE
vue-clibuild a program, when I npm run dev ,it show me these questions,

### ISSUE THREAD

**Issue by pingzidong** [npm/npm#14615]
Darwin 14.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8

npm ERR! missing script: dev
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/york/Desktop/webpack-live3/npm-debug.log
denniss-Mac-mini:webpack-live3 york$ npm cache clean

**Comment by KenanY** [comment]
@pingzidong Looks like you are running `npm run dev` without first defining a `"dev"` script in your `package.json`. Take a look at the [scripts documentation](https://docs.npmjs.com/misc/scripts) for information on how scripts work and how to write your own. If you have any questions, feel free to ask :)

**Comment by pingzidong** [comment]
thank you @KenanY

**Comment by KenanY** [comment]
@pingzidong No problem! Glad to finally hear back from you :)
