### ISSUE TITLE
npm is crashing.

### ISSUE THREAD

**Issue by qureshius** [npm/npm#14622]
npm ERR! TypeError: Object.keys called on non-object
npm ERR!     at Function.keys (native)
npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:708:24)
npm ERR!     at /usr/share/npm/lib/cache.js:638:10
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.4.0-47-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /var/www/html/vertor-test/matrix-react-sdk
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type called_on_non_object
npm WARN excluding symbolic link examples/browser/lib/matrix.js -> ../../../dist/browser-matrix.js
npm WARN excluding symbolic link examples/voip/lib/matrix.js -> ../../../dist/browser-matrix.js
npm ERR! 
npm ERR! Additional logging details can be found in:

**Comment by watilde** [comment]
Hello! You're using the old version of Node.js and npm, which are not maintaned anymore.

```
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
```
Could you please try to update both? Here are some docs that support you.

For Node.js:
https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-node

For npm:
https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm

Thanks.

**Comment by KenanY** [comment]
Closing, can reopen if this is still an issue with `npm@>=2`.
