### ISSUE TITLE
npm install does not install anything with exit 0 when version is invalid 

### ISSUE THREAD

**Issue by salomvary** [npm/npm#14629]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?

Given a `package.json` with an invalid `version` field, `npm install` logs a warning about "Invalid version" and it fails to install any dependencies. To make it worse, the exit status is 0.

Expected:
- Either install the dependencies despite the wrong version
- Or log an *error* and exit with non-zero status.

#### How can the CLI team reproduce the problem?

```
$ cat package.json 
{
  "version": "crap",
  "dependencies": {
    "left-pad": "1.1.3"
  }
}

$ npm install
npm WARN Invalid version: "crap"
npm WARN tmp No description
npm WARN tmp No repository field.
npm WARN tmp No README data
npm WARN tmp No license field.

$ echo $?
0

$ npm list
/private/tmp
└── (empty)

npm ERR! error in /private/tmp: Invalid version: "crap"

ls node_modules/
```

### supporting information:

 - `npm -v` prints: 3.10.8
 - `node -v` prints: v6.9.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS, Windows
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
Thank you for filing this! What was the result of `ls node_modules/`? This does seem like a bug.

**Comment by salomvary** [comment]
> What was the result of ls node_modules/

@legodude17 exactly what you see there: nothing:) node_modules was left empty.

**Comment by legodude17** [comment]
I think that the correct thing to do is error if there is a `--save` or warn if there is not. By the way, what `npm` version are you using?

**Comment by salomvary** [comment]
npm 3.10.8

Interestingly, `npm install some-new-module --save` works as expected (lands a module in node_modules, adds it to `package.json`, logs a WARN but exits with 0):

```
$ npm install --save underscore
/private/tmp
└── underscore@1.8.3 

npm WARN Invalid version: "crap"
npm WARN tmp No description
npm WARN tmp No repository field.
npm WARN tmp No README data
npm WARN tmp No license field.

$ echo $?
0
```

...while `npm list` still fails hard (on terms of logging and exit status):
```
$ npm list
/private/tmp
└── underscore@1.8.3

npm ERR! error in /private/tmp: Invalid version: "crap"

$ echo $?
1
```

I would say none of these operations actually depend on a valid version therefore they should work as expected and not exit with nonzero status. Warning logs are still useful.

**Comment by legodude17** [comment]
So you think the `npm install --save` behavior is correct?

**Comment by salomvary** [comment]
You mean `npm install --save some-module`? That seems to be correct, yes. Only `npm install` without a module name argument is misbehaving.

**Comment by othiym23** [comment]
The default error-handler usually sets the exit code to a nonzero value; a patch to change it so that an invalid `package.json` (which requires both a `"version"` that is a valid SemVer value and a `"name"` field that meets npm's rules) correctly returns nonzero would be very welcome. Thanks for your time!

**Comment by tiagolpadua** [comment]
Same problem here with npm 3.10.10
It is annoying because our continuous integration tools expects the installation has been successful, because return code ($?) is 0, but node_modules is empty...
