### ISSUE TITLE
npm error

### ISSUE THREAD

**Issue by Rohitwable** [npm/npm#14621]
npm ERR! connect EHOSTUNREACH 172.0.0.1:8080

**Comment by watilde** [comment]
Hello. Could you please give us more detail and `npm-debug.log`?

**Comment by Djabrail** [comment]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 verbose config Skipping project config: /home/djabrail/.npmrc. (matches userconfig)
5 verbose stack Error: missing script: start
5 verbose stack     at run (/usr/share/npm/lib/run-script.js:147:19)
5 verbose stack     at /usr/share/npm/lib/run-script.js:57:5
5 verbose stack     at /usr/share/npm/node_modules/read-package-json/read-json.js:345:5
5 verbose stack     at checkBinReferences_ (/usr/share/npm/node_modules/read-package-json/read-json.js:309:45)
5 verbose stack     at final (/usr/share/npm/node_modules/read-package-json/read-json.js:343:3)
5 verbose stack     at then (/usr/share/npm/node_modules/read-package-json/read-json.js:113:5)
5 verbose stack     at ReadFileContext.<anonymous> (/usr/share/npm/node_modules/read-package-json/read-json.js:284:20)
5 verbose stack     at ReadFileContext.callback (/usr/share/npm/node_modules/graceful-fs/graceful-fs.js:76:16)
5 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:303:13)
6 verbose cwd /home/djabrail
7 error Linux 4.4.0-47-generic
8 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
9 error node v4.2.6
10 error npm  v3.5.2
11 error missing script: start
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]

**Comment by legodude17** [comment]
Do you have a start script in you package.json? Please read the documentation.

**Comment by Sdobby** [comment]
Hey I ran to a problem when i tried to install npm its gives some proxy errors when i run npm install express Command it gives the following errors:

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "express"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ECONNRESET

npm ERR! network tunneling socket could not be established, cause=Parse Error
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'


Here is my npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'express' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData express
8 silly fetchNamedPackageData express
9 silly mapToRegistry name express
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'express',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'express',
12 silly mapToRegistry   name: 'express',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/express
14 verbose request uri https://registry.npmjs.org/express
15 verbose request no auth needed
16 info attempt registry request try #1 at 4:48:19 AM
17 verbose request id 584b604732310c81
18 http request GET https://registry.npmjs.org/express
19 info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=Parse Error
20 info attempt registry request try #2 at 4:48:29 AM
21 http request GET https://registry.npmjs.org/express
22 info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=Parse Error
23 info attempt registry request try #3 at 4:49:29 AM
24 http request GET https://registry.npmjs.org/express
25 silly fetchPackageMetaData Error: tunneling socket could not be established, cause=Parse Error
25 silly fetchPackageMetaData     at ClientRequest.onError (C:\Program Files\nodejs\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:176:17)
25 silly fetchPackageMetaData     at ClientRequest.g (events.js:291:16)
25 silly fetchPackageMetaData     at emitOne (events.js:96:13)
25 silly fetchPackageMetaData     at ClientRequest.emit (events.js:188:7)
25 silly fetchPackageMetaData     at Socket.socketOnData (_http_client.js:368:9)
25 silly fetchPackageMetaData     at emitOne (events.js:96:13)
25 silly fetchPackageMetaData     at Socket.emit (events.js:188:7)
25 silly fetchPackageMetaData     at readableAddChunk (_stream_readable.js:176:18)
25 silly fetchPackageMetaData     at Socket.Readable.push (_stream_readable.js:134:10)
25 silly fetchPackageMetaData     at TCP.onread (net.js:548:20)
25 silly fetchPackageMetaData  error for express { Error: tunneling socket could not be established, cause=Parse Error
25 silly fetchPackageMetaData     at ClientRequest.onError (C:\Program Files\nodejs\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:176:17)
25 silly fetchPackageMetaData     at ClientRequest.g (events.js:291:16)
25 silly fetchPackageMetaData     at emitOne (events.js:96:13)
25 silly fetchPackageMetaData     at ClientRequest.emit (events.js:188:7)
25 silly fetchPackageMetaData     at Socket.socketOnData (_http_client.js:368:9)
25 silly fetchPackageMetaData     at emitOne (events.js:96:13)
25 silly fetchPackageMetaData     at Socket.emit (events.js:188:7)
25 silly fetchPackageMetaData     at readableAddChunk (_stream_readable.js:176:18)
25 silly fetchPackageMetaData     at Socket.Readable.push (_stream_readable.js:134:10)
25 silly fetchPackageMetaData     at TCP.onread (net.js:548:20) code: 'ECONNRESET' }
26 silly rollbackFailedOptional Starting
27 silly rollbackFailedOptional Finishing
28 silly runTopLevelLifecycles Finishing
29 silly install printInstalled
30 verbose stack Error: tunneling socket could not be established, cause=Parse Error
30 verbose stack     at ClientRequest.onError (C:\Program Files\nodejs\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:176:17)
30 verbose stack     at ClientRequest.g (events.js:291:16)
30 verbose stack     at emitOne (events.js:96:13)
30 verbose stack     at ClientRequest.emit (events.js:188:7)
30 verbose stack     at Socket.socketOnData (_http_client.js:368:9)
30 verbose stack     at emitOne (events.js:96:13)
30 verbose stack     at Socket.emit (events.js:188:7)
30 verbose stack     at readableAddChunk (_stream_readable.js:176:18)
30 verbose stack     at Socket.Readable.push (_stream_readable.js:134:10)
30 verbose stack     at TCP.onread (net.js:548:20)
31 verbose cwd c:\xampp\htdocs\myapp
32 error Windows_NT 10.0.14393
33 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "express"
34 error node v6.9.1
35 error npm  v3.10.8
36 error code ECONNRESET
37 error network tunneling socket could not be established, cause=Parse Error
38 error network This is most likely not a problem with npm itself
38 error network and is related to network connectivity.
38 error network In most cases you are behind a proxy or have bad network settings.
38 error network
38 error network If you are behind a proxy, please make sure that the
38 error network 'proxy' config is set properly.  See: 'npm help config'
39 verbose exit [ 1, true ]

**Comment by legodude17** [comment]
Do you have a proxy, VPN, or spotty internet?
