### ISSUE TITLE
@types/jasmine name not found

### ISSUE THREAD

**Issue by bmyerly** [npm/npm#14624]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ x ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
npm install @types/jasmine
npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "@types/jasmine"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8

npm ERR! Invalid name: "@types/jasmine"

#### How can the CLI team reproduce the problem?
Just trying to install as per npm web page for  @types/jasmine
npm install @types/jasmine

nom is  installing other packages fine.

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
A lot of people have been having thing issue. Please search the issue tracker.
