### ISSUE TITLE
Running an NPM script with command expansion parses result before returning it - unlike bash

### ISSUE THREAD

**Issue by thinkloop** [npm/npm#14635]
If I run `echo "$(echo 'A\nB')"` in my shell, I get an output of:

    A\nB

If however I place the same code in an NPM script: 

    "scripts": {
      "example": "echo \"$(echo 'A\nB')\""
    }

Then run that script: `npm run -s example`.

I get an output with the `\n` replaced with an actual new line:

    A
    B

How can I disable this interpreting of the string? Why does NPM treat command expansion differently than the shell?

This only happens with command expansion: `$(some command here)`

### supporting information:

 - `npm -v` prints: 2.15.9
 - `node -v` prints: v4.5.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: linux

**Comment by legodude17** [comment]
This shouldn't happen, as `npm` just passes it to `sh` try running `echo "$(echo 'A\nB')"` in your shell.

**Comment by thinkloop** [comment]
In the shell it works as expected, it's only with npm scripts. This SO answer points t that fact that its json: http://stackoverflow.com/questions/40607604/running-an-npm-script-with-command-expansion-parses-result-before-returning-it

**Comment by legodude17** [comment]
That is probably it, but then shouldn't `npm` fail to parse it?

**Comment by thinkloop** [comment]
Interesting thought, I guess it must be that npm does not have trouble with newlines, the trouble arises in the json, and since there are no new lines in the json, its fone:

1. Parse json (no new lines allowed)
2. Send to npm (anything allowed)

**Comment by legodude17** [comment]
Probably. This isn't really something that can be fixed. And I don't think it needs to be. This is a very small niche, and there probably aren't many new lines in `npm` `scripts`.

**Comment by thinkloop** [comment]
I bring it up because I am currently stuck. I am trying to concat two files into one file:

```
"build:vendor": "cat ./vendor/file1.js ./vendor/file2.js > vendor.js"
```

But one of the files has a regex in it with `\n`, which splits the line and breaks the code.

Additionally, and possibly importantly, this only happens with command expansion: `$(some command here)`. Running a simple `echo 'A\nB'` through a script seems to work fine.

**Comment by legodude17** [comment]
That is odd. Does it work without `npm`?

**Comment by thinkloop** [comment]
Oops, the `cat` code I posted works fine, this is what doesn't:

```
"build:js": "echo \"$(npm run -s build:vendor) $(npm run -s build:js:browserify)\"
```

I am trying to concat the stdout of two processes into a final file without an intermediete tmp file.

**Comment by legodude17** [comment]
I guess this is a problem, but I don't know how to fix it. At that point I would suggest using `grunt` or `gulp`.

**Comment by thinkloop** [comment]
Gulp is so 2015, npm as a build tool is where its at :P

**Comment by RyanZim** [comment]
>  I guess it must be that npm does not have trouble with newlines, but json does

To clarify, the correct json escaping for `echo "$(echo 'A\nB')"` is `"echo \"$(echo 'A\\nB')\""`. However, that does not work correctly with `npm`.

By trial and error, I found that:
```json
"scripts": {
  "example": "echo \"$(echo 'A\\\\\\\\nB')\""
}
```
produces the desired output. That is just plain weird.

@thinkloop As a workaround, you can try putting your script in a shell script file and calling it from npm scripts:
```json
"scripts": {
  "example": "./echo.bash"
}
````

**Comment by thinkloop** [comment]
> @thinkloop As a workaround, you can try putting your script in a shell script file and calling it from npm scripts:

Thanks for the suggestion. I actually tried that already, and it seems to go through the same pipeline with the same results.
