### ISSUE TITLE
problem installing ionic and cordova

### ISSUE THREAD

**Issue by jovic94** [npm/npm#14639]
is there a problem with npm at the moment coz all the installations are failing. I am trying to install ionic 2 and cordova but its not working.

**Comment by KenanY** [comment]
@jovic94 Could you upload your `npm-debug.log` file to <https://gist.github.com/> and post a link here? At the moment, there are [no known issues](https://npmjs.statuspage.io/) with the registry.

**Comment by KenanY** [comment]
Closing as abandoned.
