### ISSUE TITLE
NPM permission denied for git-github-com-polymerelements-test-fixture-git-8142662e

### ISSUE THREAD

**Issue by gdp4u** [npm/npm#14632]
#### I'm opening this issue because:

  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
when I tried to run npm install for a project, I got the error for permission denied as shown below.  What permission do I need to access it?
[npm-debug.txt](https://github.com/npm/npm/files/592129/npm-debug.txt)

### supporting information:
3904 verbose stack Cloning into bare repository 'C:\Users\<user>\AppData\Roaming\npm-cache\_git-remotes\git-github-com-polymerelements-test-fixture-git-8142662e'...
33904 verbose stack Permission denied (publickey).
33904 verbose stack fatal: Could not read from remote repository.
33904 verbose stack
33904 verbose stack Please make sure you have the correct access rights
33904 verbose stack and the repository exists.
33904 verbose stack
33904 verbose stack     at ChildProcess.exithandler (child_process.js:206:12)
33904 verbose stack     at emitTwo (events.js:106:13)
33904 verbose stack     at ChildProcess.emit (events.js:191:7)
33904 verbose stack     at maybeClose (internal/child_process.js:877:16)
33904 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
33905 verbose cwd C:\Users\<user>\predix-seed-develop\predix-seed-develop
33906 error Windows_NT 6.1.7601
33907 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
33908 error node v6.9.1
33909 error npm  v3.10.8
33910 error code 128
33911 error Command failed: git -c core.longpaths=true clone --template=C:\Users\<user>\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:polymerelements/test-fixture.git C:\Users\<user>\AppData\Roaming\npm-cache\_git-remotes\git-github-com-polymerelements-test-fixture-git-8142662e
33911 error Cloning into bare repository 'C:\Users\<user>\AppData\Roaming\npm-cache\_git-remotes\git-github-com-polymerelements-test-fixture-git-8142662e'...
33911 error Permission denied (publickey).
33911 error fatal: Could not read from remote repository.
33911 error#### Is the absence of this feature blocking you or your team? If so, how?

#### Is this a feature you're prepared to implement, with support from the npm CLI team?

-->

**Comment by legodude17** [comment]
What happens if you run `git -c core.longpaths=true clone --template=C:\Users\221031058\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:polymerelements/test-fixture.git C:\Users\221031058\AppData\Roaming\npm-cache\_git-remotes\git-github-com-polymerelements-test-fixture-git-8142662e`?

**Comment by gdp4u** [comment]
I got too many argument error

**Comment by legodude17** [comment]
The error message says that your publickey is wrong. Do you have the correct access and key for `git@github.com:polymerelements/test-fixture.git`?

**Comment by gdp4u** [comment]
I have created SSH connect and set up on github.  I do not know about my access.  How do I know what access I need for test-fixture?

**Comment by legodude17** [comment]
Have you configured `git` to use you key? Go to [the repo](https://github.com/polymerelements/test-fixture.git) and check to make sure you can access it.

**Comment by gdp4u** [comment]
yes I can click the link and access the page.
when I run the command you provided before I got the following error.

C:\Users\221031058\predix-seed-develop\predix-seed-develop> git -c core.longpath
s=true clone --template=C:\Users\221031058\AppData\Roaming\npm-cache\_git-remote
s\_templates --mirror git@github.com:polymerelements/test-fixture.git C:\Users\2
21031058\AppData\Roaming\npm-cache\_git-remotes\git-github-com-polymerelements-t
est-fixture-git-8142662e
Cloning into bare repository 'C:\Users\221031058\AppData\Roaming\npm-cache\_git-
remotes\git-github-com-polymerelements-test-fixture-git-8142662e'...
ssh: Could not resolve hostname github.com: Name or service not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

C:\Users\221031058\predix-seed-develop\predix-seed-develop>

**Comment by legodude17** [comment]
That means that this is an error with your setup and not with `npm`.
