### ISSUE TITLE
Registry error parsing JSON with unexpected token in json at position 0

### ISSUE THREAD

**Issue by senva1A** [npm/npm#14631]
#### I'm opening this issue because:

  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.

#### How can the CLI team reproduce the problem?

   debug file

<details><pre>
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'protractor' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData protractor
8 silly fetchNamedPackageData protractor
9 silly mapToRegistry name protractor
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry http://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'protractor',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'protractor',
12 silly mapToRegistry   name: 'protractor',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri http://registry.npmjs.org/protractor
14 verbose request uri http://registry.npmjs.org/protractor
15 verbose request no auth needed
16 info attempt registry request try #1 at 4:57:21 PM
17 verbose request id 19959d67da7804a4
18 http request GET http://registry.npmjs.org/protractor
19 http 404 http://registry.npmjs.org/protractor
20 verbose bad json <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
20 verbose bad json <html xmlns="http://www.w3.org/1999/xhtml">
20 verbose bad json <head>
20 verbose bad json <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
20 verbose bad json <title>404 - File or directory not found.</title>
20 verbose bad json <style type="text/css">
20 verbose bad json 
20 verbose bad json </style>
20 verbose bad json </head>
20 verbose bad json <body>
20 verbose bad json <div id="header"><h1>Server Error</h1></div>
20 verbose bad json <div id="content">
20 verbose bad json  <div class="content-container"><fieldset>
20 verbose bad json   <h2>404 - File or directory not found.</h2>
20 verbose bad json   <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
20 verbose bad json  </fieldset></div>
20 verbose bad json </div>
20 verbose bad json </body>
20 verbose bad json </html>
21 error registry error parsing json
22 verbose headers { 'content-type': 'text/html',
22 verbose headers   server: 'Microsoft-IIS/7.5',
22 verbose headers   'x-powered-by': 'ASP.NET',
22 verbose headers   date: 'Tue, 15 Nov 2016 11:27:21 GMT',
22 verbose headers   'content-length': '1245' }
23 silly get cb [ 404,
23 silly get   { 'content-type': 'text/html',
23 silly get     server: 'Microsoft-IIS/7.5',
23 silly get     'x-powered-by': 'ASP.NET',
23 silly get     date: 'Tue, 15 Nov 2016 11:27:21 GMT',
23 silly get     'content-length': '1245' } ]
24 silly fetchPackageMetaData SyntaxError: Unexpected token < in JSON at position 0
24 silly fetchPackageMetaData <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
24 silly fetchPackageMetaData <html xmlns="http://www.w3.org/1999/xhtml">
24 silly fetchPackageMetaData <head>
24 silly fetchPackageMetaData <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
24 silly fetchPackageMetaData <title>404 - File or directory not found.</title>
24 silly fetchPackageMetaData <style type="text/css">
24 silly fetchPackageMetaData 
24 silly fetchPackageMetaData </style>
24 silly fetchPackageMetaData </head>
24 silly fetchPackageMetaData <body>
24 silly fetchPackageMetaData <div id="header"><h1>Server Error</h1></div>
24 silly fetchPackageMetaData <div id="content">
24 silly fetchPackageMetaData  <div class="content-container"><fieldset>
24 silly fetchPackageMetaData   <h2>404 - File or directory not found.</h2>
24 silly fetchPackageMetaData   <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
24 silly fetchPackageMetaData  </fieldset></div>
24 silly fetchPackageMetaData </div>
24 silly fetchPackageMetaData </body>
24 silly fetchPackageMetaData </html>
24 silly fetchPackageMetaData
24 silly fetchPackageMetaData     at Object.parse (native)
24 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:237:23)
24 silly fetchPackageMetaData     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:210:14)
24 silly fetchPackageMetaData     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:187:22)
24 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
24 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
24 silly fetchPackageMetaData     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1044:10)
24 silly fetchPackageMetaData     at emitOne (events.js:96:13)
24 silly fetchPackageMetaData     at Request.emit (events.js:188:7)
24 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:965:12)
24 silly fetchPackageMetaData  error for protractor SyntaxError: Unexpected token < in JSON at position 0
24 silly fetchPackageMetaData <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
24 silly fetchPackageMetaData <html xmlns="http://www.w3.org/1999/xhtml">
24 silly fetchPackageMetaData <head>
24 silly fetchPackageMetaData <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
24 silly fetchPackageMetaData <title>404 - File or directory not found.</title>
24 silly fetchPackageMetaData <style type="text/css">
24 silly fetchPackageMetaData 
24 silly fetchPackageMetaData </style>
24 silly fetchPackageMetaData </head>
24 silly fetchPackageMetaData <body>
24 silly fetchPackageMetaData <div id="header"><h1>Server Error</h1></div>
24 silly fetchPackageMetaData <div id="content">
24 silly fetchPackageMetaData  <div class="content-container"><fieldset>
24 silly fetchPackageMetaData   <h2>404 - File or directory not found.</h2>
24 silly fetchPackageMetaData   <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
24 silly fetchPackageMetaData  </fieldset></div>
24 silly fetchPackageMetaData </div>
24 silly fetchPackageMetaData </body>
24 silly fetchPackageMetaData </html>
24 silly fetchPackageMetaData
24 silly fetchPackageMetaData     at Object.parse (native)
24 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:237:23)
24 silly fetchPackageMetaData     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:210:14)
24 silly fetchPackageMetaData     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:187:22)
24 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
24 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
24 silly fetchPackageMetaData     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1044:10)
24 silly fetchPackageMetaData     at emitOne (events.js:96:13)
24 silly fetchPackageMetaData     at Request.emit (events.js:188:7)
24 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:965:12)
25 silly rollbackFailedOptional Starting
26 silly rollbackFailedOptional Finishing
27 silly runTopLevelLifecycles Finishing
28 silly install printInstalled
29 verbose stack SyntaxError: Unexpected token < in JSON at position 0
29 verbose stack <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
29 verbose stack <html xmlns="http://www.w3.org/1999/xhtml">
29 verbose stack <head>
29 verbose stack <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
29 verbose stack <title>404 - File or directory not found.</title>
29 verbose stack <style type="text/css">
29 verbose stack 
29 verbose stack </style>
29 verbose stack </head>
29 verbose stack <body>
29 verbose stack <div id="header"><h1>Server Error</h1></div>
29 verbose stack <div id="content">
29 verbose stack  <div class="content-container"><fieldset>
29 verbose stack   <h2>404 - File or directory not found.</h2>
29 verbose stack   <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
29 verbose stack  </fieldset></div>
29 verbose stack </div>
29 verbose stack </body>
29 verbose stack </html>
29 verbose stack
29 verbose stack     at Object.parse (native)
29 verbose stack     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:237:23)
29 verbose stack     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:210:14)
29 verbose stack     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:187:22)
29 verbose stack     at emitTwo (events.js:106:13)
29 verbose stack     at Request.emit (events.js:191:7)
29 verbose stack     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1044:10)
29 verbose stack     at emitOne (events.js:96:13)
29 verbose stack     at Request.emit (events.js:188:7)
29 verbose stack     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:965:12)
30 verbose cwd C:\Windows\System32
31 error Windows_NT 6.3.9600
32 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "protractor"
33 error node v6.9.1
34 error npm  v3.10.8
35 error Unexpected token < in JSON at position 0
35 error <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
35 error <html xmlns="http://www.w3.org/1999/xhtml">
35 error <head>
35 error <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
35 error <title>404 - File or directory not found.</title>
35 error <style type="text/css">
35 error 
35 error </style>
35 error </head>
35 error <body>
35 error <div id="header"><h1>Server Error</h1></div>
35 error <div id="content">
35 error  <div class="content-container"><fieldset>
35 error   <h2>404 - File or directory not found.</h2>
35 error   <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
35 error  </fieldset></div>
35 error </div>
35 error </body>
35 error </html>
36 error If you need help, you may report this error at:
36 error     <https://github.com/npm/npm/issues>
37 verbose exit [ 1, true ]
</pre></details>

### supporting information:

 - `npm -v` prints:  3.10.8
 - `node -v` prints: v6.9.1
 - `npm config get registry` prints:  http://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows 8
 - Network issues:
   - Geographic location where npm was run:
   - [ yes] I use a proxy to connect to the npm registry.
   - [ yes] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
This is most likely a problem with your proxy or internet connection.
