### ISSUE TITLE
npm install -g phonegap error

### ISSUE THREAD

**Issue by roslanjam** [npm/npm#14636]
i get the following error when i do npm

```
$ npm install -g phonegap
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\UITMPA~1\AppData\Local\Temp\npm-812-44c410d4\registry.npmjs.org\connect-phonegap\-\connect-phonegap-0.24.0.tgz.2025033871' -> 'C:\Users\UITMPA~1\AppData\Local\Temp\npm-812-44c410d4\registry.npmjs.org\connect-phonegap\-\connect-phonegap-0.24.0.tgz'
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "phonegap"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\UITMPA~1\AppData\Local\Temp\npm-812-44c410d4\registry.npmjs.org\connect-phonegap\-\connect-phonegap-0.24.0.tgz.2555014201' -> 'C:\Users\UITMPA~1\AppData\Local\Temp\npm-812-44c410d4\registry.npmjs.org\connect-phonegap\-\connect-phonegap-0.24.0.tgz'
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "phonegap"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
 ```

#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
Do you have an antivirus? This is a know error that can happen if an antivirus locks a file `npm` needs.
