### ISSUE TITLE
npm install -g cordova ionic not wordking 

### ISSUE THREAD

**Issue by kirtikanani** [npm/npm#14630]
npm ERR! Windows_NT 6.1.7601
 hello friend can you help me about this following error 

![checkerrror](https://cloud.githubusercontent.com/assets/12745603/20302262/6a7607b8-aadb-11e6-88c5-0e6ade962daa.png)

**Comment by legodude17** [comment]
Try running `npm cache clean`.

**Comment by kirtikanani** [comment]
@ legodude17  thanks for replay but i was try this command after use ionic command but same error getting can you help me more by your suggestion

**Comment by legodude17** [comment]
This could also be another issue caused by the registry. Pinging @soldair.

**Comment by GlintRain** [comment]
I encountered a similar problem , and there is what I did .( I'm using macOS Sierra 10.12.1 and I'm going to install Ionic.)
1.npm config set registry, I find Internet speed is slow, so I change the redistry;
2.update npm to 4.0.2,using sudo;
3.install Cordova and Ionic using sudo;
then I installed Cordova and Ionic successfully. I'm not sure which one really helps.╮(￣▽￣"")╭
【几乎每句话都用I开头，真是不好看_(:3 / /_)_
