### ISSUE TITLE
npm WARN with --prefix

### ISSUE THREAD

**Issue by monolithed** [npm/npm#14633]
#### I'm opening this issue because:

  - [x] npm is doing something I don't understand.

### 1

```
let { execSync: exec } = require('child_process');
let os = require('os');

let tmp = os.tmpdir();

exec(`npm install ./ --prefix ${tmp}`, {
	encoding: 'utf8',
	stdio: 'inherit'
});
```

Works fine, but I see the following:

```
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/0y/jg1cdcj50zv2vjsjzxtsfhqc0000gp/T/package.json'
npm WARN T No description
npm WARN T No repository field.
npm WARN T No README data
npm WARN T No license field.
```
How to suppress these warnings?

### 2 (maybe not npm problem)

```
let { execSync: exec } = require('child_process');
let os = require('os');

let tmp = os.tmpdir();

exec(`npm install --prefix ${tmp}`, {
        cwd: './',
	encoding: 'utf8',
	stdio: 'inherit'
});
```

```
child_process.js:531
    throw err;
    ^

Error: spawnSync /bin/sh ENOENT
    at exports._errnoException (util.js:1026:11)
    at spawnSync (child_process.js:466:20)
    at execSync (child_process.js:522:13)
    at Cache.installModules (/index.js:173:3)
    at Object.<anonymous> (/install.js:11:7)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
```

How to set `cwd`?

### supporting information:

 - `npm -v` prints: v7.0.0
 - `node -v` prints: 3.10.8
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Darwin

**Comment by legodude17** [comment]
This is a `node` issue, with it throwing. You could suppress the warnings with `--loglevel=silent` or `stdio:'none'` in the `options`.

**Comment by monolithed** [comment]
I'd like to see `stdout`, but not `npm WARN`

**Comment by legodude17** [comment]
The use `stdio: [1,0,0]` this will only let through `stdout`. For further help refer to the `node` docs on `child_process`. Cheers!

**Comment by monolithed** [comment]
> Then use stdio: [1,0,0] this will only let through stdout.

```
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/0y/jg1cdcj50zv2vjsjzxtsfhqc0000gp/T/package.json'
npm WARN T No description
npm WARN T No repository field.
npm WARN T No README data
npm WARN T No license field.
```

Thanks, but I still see these warnings

**Comment by legodude17** [comment]
What OS are you on? Try `stdio: ['ignore','pipe','ignore]`.

**Comment by monolithed** [comment]
> What OS are you on? 

MacOS Sierra 10.12.1 (16B2555)

```
➜ uname -a
Darwin local 16.1.0 Darwin Kernel Version 16.1.0: Thu Oct 13 21:26:57 PDT 2016; root:xnu-3789.21.3~60/RELEASE_X86_64 x86_64
```

> Try stdio: ['ignore', 'pipe', 'ignore']

Thanks, but It works like `&> /dev/null`.
I found a good way how to suppress warnings:

```
['ignore', process.stdin, 'ignore']
```

But when I install an unknown package or version:

```
Error: Command failed: npm install ./ --only=production --prefix /var/folders/0y/jg1cdcj50zv2vjsjzxtsfhqc0000gp/T
    at checkExecSyncError (child_process.js:488:13)
    at execSync (child_process.js:528:13)
    at Cache.installModules (/index.js:175:3)
    at Object.<anonymous> (/hooks/install.js:11:7)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.runMain (module.js:607:10)
 ```

**Comment by legodude17** [comment]
That is expected, because you are suppressing `stderr`. You could also use `--loglevel=error` so suppress the `warn`s and not the `error`s.

**Comment by monolithed** [comment]
> That is expected, because you are suppressing stderr

If you mean `['ignore', 'pipe', 'ignore']`, I'd like to see all standard file descriptors like `stdout` and `stderr`, but suppress unexpected warnings. I have already tried `--loglevel=error`, but it also has not any effect for me.

It seems the problem with `child_process`, because I haven't seen these warnings without that

**Comment by legodude17** [comment]
Ok. If it is a problem with `child_procss`, you should file it with the
`node` folks.
