### ISSUE TITLE
`npm search` crashes

### ISSUE THREAD

**Issue by srvance** [npm/npm#14649]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
[npm-debug.log.zip](https://github.com/npm/npm/files/597757/npm-debug.log.zip)

Trying to do a simple `npm search ember-cli` crashes "Building the local index for the first time". Using Max OS X Sierra 10.12.1 with latest XCode and command line tools installed. Node installed from npmjs installer. Reinstalled node. Also tried `npm cache clean`.

### supporting information:

 - `npm -v` prints: 3.10.8
 - `node -v` prints: v6.9.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS 10.12.1
 - Network issues:
   - Geographic location where npm was run: Wayland, MA
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
In the future, you can upload your log to <https://gist.github.com/> instead of zipping it up. Have you tried updating to `npm@4`? It contains a new search implementation which should fix this.

**Comment by aadrian** [comment]
> Have you tried updating to npm@4?

```npm outdated -g``` does not lists itself as outdated.

**Comment by KenanY** [comment]
I'm gonna close this since the OP never responded to me. I can reopen this if this is still an issue in `npm@4.`

**Comment by srvance** [comment]
It took me a bit to assess whether I wanted to update npm in the middle of a project.

1. So is npm@3 no longer supported? It's what's shipping with node. And a major version update seems a bit heavy.
2. I updated anyway and now it says "No search sources available"

**Comment by srvance** [comment]
@KenanY Do I need to open a new issue? I don't see a way to reopen this one.

**Comment by KenanY** [comment]
@srvance `npm@3` is still supported. If you wanna do `npm search`, however, you will need `npm@4` since that is what has the fix (which was a big enough rewrite of search to warrant a major version). I haven't seen that "no search sources available" message before; is there a `npm-debug.log` generated?

**Comment by srvance** [comment]
Very strange. After an attempt, a cache clean, and another attempt, all three failing in the same way, I `vi`'d and `rm`'d the debug log and ran it again to get a clean log and it worked like it was supposed to.

Here's the annotated bash history.
```
  617  npm search ember-cli  # fail as reported
  618  npm outdated -g
  619  npm upgrade -g
  620  sudo npm upgrade -g  # Upgrade to npm@4
  621  npm -v
  622  npm search ember-cli  # Try again => "No search sources"
  623  npm cache clean
  624  npm search ember-cli  # Same
  625  vi npm-debug.log
  626  rm npm-debug.log
  627  npm search ember-cli  # It works!?!
```
If there's any information I can give you, let me know. Otherwise, feel free to close again.

**Comment by legodude17** [comment]
That is very strange... If you add a `npm-debug.log` back into that dir, does it fail again?

**Comment by srvance** [comment]
No, but it managed to do the cache initialization by this point. It removed the one I put there, which answers the question that was why I removed it above.
