### ISSUE TITLE
ubunto shows npm ERR! Linux 4.4.0-47-generic

### ISSUE THREAD

**Issue by shivamindalkar** [npm/npm#14640]
When i fire the npm install react react-dom --save  command with my terminal  it gives me following errors.

npm ERR! Linux 4.4.0-47-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "react" "react-dom" "--save"
npm ERR! node v5.5.0
npm ERR! npm  v3.10.9
npm ERR! code ENOSELF

npm ERR! Refusing to install react as a dependency of itself
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/hp/react/npm-debug.log
hp@hp-HP-Pavilion-g6-Notebook-PC:~/react$

**Comment by KenanY** [comment]
@shivamindalkar Make sure that the `"name"` key in your `package.json` is not set to `"react"`. Make it more unique :)

**Comment by shivamindalkar** [comment]
hey thanks bro cheers,
