### ISSUE TITLE
Latest npm failed to fetch dependencies...

### ISSUE THREAD

**Issue by pontiyaraja** [npm/npm#14646]
npm ERR! fetch failed https://registry.npmjs.org/redux-persist/-/redux-persist-4.0.0-beta1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://registry.npmjs.org/redux-persist/-/redux-persist-4.0.0-beta1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://registry.npmjs.org/redux-persist/-/redux-persist-4.0.0-beta1.tgz
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/7.1.0/bin/node" "/usr/local/bin/npm" "install" "--save"
npm ERR! node v7.1.0
npm ERR! npm  v3.10.9

npm ERR! fetch failed with status code 404
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:

**Comment by pepper** [comment]
I get the same error

**Comment by legodude17** [comment]
Hello! What is the result of `npm config get registry`?

**Comment by pepper** [comment]
My result is:
https://registry.npmjs.org/

**Comment by legodude17** [comment]
What happens if you click on [this link]( https://registry.npmjs.org/redux-persist/-/redux-persist-4.0.0-beta1.tgz)? What does the browser show?

**Comment by heatmonkey** [comment]
Getting the same thing somewhere else.

ERR! fetch failed https://registry.npmjs.org/html-minifier/-/html-minifier-3.2.0.tgz
[09:57:11][Exec] npm WARN retry will retry, error on last attempt fetch failed with status code 404

**Comment by pepper** [comment]
This is what I got:
http://imgur.com/a/s8ufn

**Comment by legodude17** [comment]
Sounds like this is a problem with the registry, not the CLI. Please file an issue with [npm/registry](https://github.com/npm/registry/issues/new).

**Comment by pepper** [comment]
And here have more info:
[redux-persist #212](https://github.com/rt2zz/redux-persist/issues/212)

**Comment by legodude17** [comment]
Pinging @soldair. @heatmonkey, anything to add?

**Comment by soldair** [comment]
im taking a look at this now. ill be posting updates to this registry issue https://github.com/npm/registry/issues/85

**Comment by heatmonkey** [comment]
https://github.com/npm/registry/issues/85

They seem to be working it out. It is a registry issue.

**Comment by legodude17** [comment]
Cool. Can this be closed now that it is being handled by @soldair?

**Comment by heatmonkey** [comment]
Good with me.
