### ISSUE TITLE
ENOTFOUND error while installing typescript

### ISSUE THREAD

**Issue by sasi91** [npm/npm#14647]
I am very new to this angular 2 . I was trying to install typescript using the following command 
> npm install -g typescript
But instead got the following error. Could you please help me to resolve this issue??
![angular 2](https://cloud.githubusercontent.com/assets/23522393/20387159/d666eb44-ace4-11e6-9663-e863c23a651d.JPG)

**Comment by legodude17** [comment]
Do you have a proxy or VPN?
