### ISSUE TITLE
First time using npm and got error when install

### ISSUE THREAD

**Issue by LucionDeviluke** [npm/npm#14643]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I got error when I'm install code bellow.
```json
{
  "name": "angular2-quickstart",
  "version": "1.0.0",
  "scripts": {
    "start": "concurrent \"npm run tsc:w\" \"npm run lite\" ",    
    "tsc": "tsc",
    "tsc:w": "tsc -w",
    "lite": "lite-server",
    "typings": "typings",
    "postinstall": "typings install" 
  },  
  "license": "ISC",
  "dependencies": {
    "angular2": "2.0.0-beta.7",
    "systemjs": "0.19.22",
    "es6-promise": "^3.0.2",
    "es6-shim": "^0.33.3",
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-beta.2",
    "zone.js": "0.5.15"
  },
  "devDependencies": {
    "concurrently": "^2.0.0",
    "lite-server": "^2.1.0",
    "typescript": "^1.7.5"
  }
}
```

#### How can the CLI team reproduce the problem?
100 error Windows_NT 10.0.14393
101 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
102 error node v6.9.1
103 error npm  v3.10.8
104 error code ELIFECYCLE
105 error angular2-quickstart@1.0.0 postinstall: `typings install`
105 error Exit status 1
106 error Failed at the angular2-quickstart@1.0.0 postinstall script 'typings install'.
106 error Make sure you have the latest version of node.js and npm installed.
106 error If you do, this is most likely a problem with the angular2-quickstart package,
106 error not with npm itself.
106 error Tell the author that this fails on your system:
106 error     typings install
106 error You can get information on how to open an issue for this project with:
106 error     npm bugs angular2-quickstart
106 error Or if that isn't available, you can get their info via:
106 error     npm owner ls angular2-quickstart
106 error There is likely additional logging output above.
107 verbose exit [ 1, true ]

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@LucionDeviluke As the log indicates, this isn't a failure of `npm` but of your `"postinstall"` script. Have you tried running `typings install` yourself?
