### ISSUE TITLE
npm gives proxy errors when going to install

### ISSUE THREAD

**Issue by Sdobby** [npm/npm#14656]
npm install express gives errors every time i tried to install it

  - It gives me several errors
  - Network Errors
  - Proxy Errors

#### The issue accures whenever i run npm install express command in CMD it takes some time gives me errors

    Here is my debug file contens:
   0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'express' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData express
8 silly fetchNamedPackageData express
9 silly mapToRegistry name express
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'express',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'express',
12 silly mapToRegistry   name: 'express',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/express
14 verbose request uri https://registry.npmjs.org/express
15 verbose request no auth needed
16 info attempt registry request try #1 at 4:48:19 AM
17 verbose request id 584b604732310c81
18 http request GET https://registry.npmjs.org/express
19 info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=Parse Error
20 info attempt registry request try #2 at 4:48:29 AM
21 http request GET https://registry.npmjs.org/express
22 info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=Parse Error
23 info attempt registry request try #3 at 4:49:29 AM
24 http request GET https://registry.npmjs.org/express
25 silly fetchPackageMetaData Error: tunneling socket could not be established, cause=Parse Error
25 silly fetchPackageMetaData     at ClientRequest.onError (C:\Program Files\nodejs\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:176:17)
25 silly fetchPackageMetaData     at ClientRequest.g (events.js:291:16)
25 silly fetchPackageMetaData     at emitOne (events.js:96:13)
25 silly fetchPackageMetaData     at ClientRequest.emit (events.js:188:7)
25 silly fetchPackageMetaData     at Socket.socketOnData (_http_client.js:368:9)
25 silly fetchPackageMetaData     at emitOne (events.js:96:13)
25 silly fetchPackageMetaData     at Socket.emit (events.js:188:7)
25 silly fetchPackageMetaData     at readableAddChunk (_stream_readable.js:176:18)
25 silly fetchPackageMetaData     at Socket.Readable.push (_stream_readable.js:134:10)
25 silly fetchPackageMetaData     at TCP.onread (net.js:548:20)
25 silly fetchPackageMetaData  error for express { Error: tunneling socket could not be established, cause=Parse Error
25 silly fetchPackageMetaData     at ClientRequest.onError (C:\Program Files\nodejs\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:176:17)
25 silly fetchPackageMetaData     at ClientRequest.g (events.js:291:16)
25 silly fetchPackageMetaData     at emitOne (events.js:96:13)
25 silly fetchPackageMetaData     at ClientRequest.emit (events.js:188:7)
25 silly fetchPackageMetaData     at Socket.socketOnData (_http_client.js:368:9)
25 silly fetchPackageMetaData     at emitOne (events.js:96:13)
25 silly fetchPackageMetaData     at Socket.emit (events.js:188:7)
25 silly fetchPackageMetaData     at readableAddChunk (_stream_readable.js:176:18)
25 silly fetchPackageMetaData     at Socket.Readable.push (_stream_readable.js:134:10)
25 silly fetchPackageMetaData     at TCP.onread (net.js:548:20) code: 'ECONNRESET' }
26 silly rollbackFailedOptional Starting
27 silly rollbackFailedOptional Finishing
28 silly runTopLevelLifecycles Finishing
29 silly install printInstalled
30 verbose stack Error: tunneling socket could not be established, cause=Parse Error
30 verbose stack     at ClientRequest.onError (C:\Program Files\nodejs\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:176:17)
30 verbose stack     at ClientRequest.g (events.js:291:16)
30 verbose stack     at emitOne (events.js:96:13)
30 verbose stack     at ClientRequest.emit (events.js:188:7)
30 verbose stack     at Socket.socketOnData (_http_client.js:368:9)
30 verbose stack     at emitOne (events.js:96:13)
30 verbose stack     at Socket.emit (events.js:188:7)
30 verbose stack     at readableAddChunk (_stream_readable.js:176:18)
30 verbose stack     at Socket.Readable.push (_stream_readable.js:134:10)
30 verbose stack     at TCP.onread (net.js:548:20)
31 verbose cwd c:\xampp\htdocs\myapp
32 error Windows_NT 10.0.14393
33 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "express"
34 error node v6.9.1
35 error npm  v3.10.8
36 error code ECONNRESET
37 error network tunneling socket could not be established, cause=Parse Error
38 error network This is most likely not a problem with npm itself
38 error network and is related to network connectivity.
38 error network In most cases you are behind a proxy or have bad network settings.
38 error network
38 error network If you are behind a proxy, please make sure that the
38 error network 'proxy' config is set properly.  See: 'npm help config'
39 verbose exit [ 1, true ]

**Comment by legodude17** [comment]
Did you set your proxy settings correctly?
