### ISSUE TITLE
Feature request: set the root directory that require('module/sub-component') looks in to find the sub-component

### ISSUE THREAD

**Issue by nfriedly** [npm/npm#14652]
#### What's the feature?

I'd like npm to allow my users to call `require('my-module/sub-component')` without having `sub-component` in the module's root directory. This could be done either at publish time, by publishing a sub-dir instead of the root directory, or at require-time by adjusting the path that require searches. (Or probably a dozen other ways I'm not thinking of.)

I'd also like for it to play nice with `npm link`.

#### What problem is the feature intended to solve?

I'm working on a [library](https://github.com/watson-developer-cloud/node-sdk) that has several individual components. Users typically only need one or two of the components and are encouraged to `require('library/component');` to reduce the amount of code loaded, especially for client-side usage. 

Right now, each component is in it's own top-level folder in the git repo to facilitate this. I would like to move them to a `src/` folder, but I don't want users to be forced to add `src/` into their `require()` calls. 

#### Is the absence of this feature blocking you or your team? If so, how?

No, it's just an annoyance. 

If it matters, I don't seem to be the only [user](http://stackoverflow.com/questions/35282101/root-directory-for-node-module) [who](http://stackoverflow.com/questions/37520524/is-it-possible-to-set-the-root-directory-of-a-node-module) [wants](http://stackoverflow.com/questions/39743643/npm-package-json-main-and-project-structure) [this](http://stackoverflow.com/questions/29142580/requiremodule-component-when-component-js-is-not-in-module-root).

#### Is this feature similar to an existing feature in another tool?

It's similar to the existing `main` package.json entry, only for a folder instead of a file.

I imagine this is possible today by just running some pre- and post-publish scripts to move things in and out of src/, but that seems like a fragile hack, and probably wouldn't play nice with `npm link`. Symlinks might not be quite as bad, but would still be a bit annoying and I'm not sure if they'd work well on Windows. I can't think of any other ideas besides having npm officially support this, but there may be some. 

Java/Maven also handles things a little closer to what I'd like.

#### Is this a feature you're prepared to implement, with support from the npm CLI team?

Sure! Although I'd probably need a good amount of help to ensure I don't break anything else.

**Comment by legodude17** [comment]
I am pretty sure that this would have to be implemented by the `nodejs` folks. Be aware that they are _very_ tight on allowing changes to `require`. File an issue over there and good luck!

**Comment by nfriedly** [comment]
@legodude17 you're probably right about the require-time variation, but what about the publish-time one? Basically make `npm publish` behave as if the package.json were moved to `src/` (or wherever) and the command were run from that directory?

**Comment by legodude17** [comment]
So make `npm publish` basically move everything in `src` to the main dir and then publish that? As I was thinking about that, I though that you could to a `prepublishOnly` script to move it for you.

**Comment by nfriedly** [comment]
Yea, I know I could put together some scripts to do roughly what I want, but it just feels like that would be hacky and brittle. Also, it probably wouldn't play nice with `npm link`.

So, I'm hoping for this to get built-into npm, ideally in a backwards-compatible manner for end users on older versions of npm/node (which also rules out the require-time option now that I think about it.)

**Comment by legodude17** [comment]
We should see what @othiym23 thinks about this.
