### ISSUE TITLE
npm install: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by Freyert** [npm/npm#14651]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Essentially, the registry data being passed into NPM is "bad"(?). The `pickVersionFromRegistryDocument` is expecting `pkg.versions`, but that information is really packed under `pkg.time.unpublished.versions`.

`npm install -g slc`

```
break in /node/v4.6.2/lib/node_modules/npm/lib/fetch-package-metadata.js:124
 122     }
 123     function pickVersionFromRegistryDocument (pkg) {
>124       debugger;
 125       if (!regCache[url]) regCache[url] = pkg
 126       var versions = Object.keys(pkg.versions)
repl
Press Ctrl + C to leave debug repl
> pkg
{ _attachments: {},
  name: 'slc',
  _id: 'slc',
  _rev: '4-c5ea92b54af09ebdc5df959dad181664',
  time:
   { modified: '2016-11-10T00:28:58.348Z',
     created: '2016-11-10T00:23:26.258Z',
     '0.1.1': '2016-11-10T00:23:26.258Z',
     '0.1.2': '2016-11-10T00:24:49.590Z',
     '0.1.3': '2016-11-10T00:26:02.086Z',
     unpublished:
      { name: 'sillaps',
        time: '2016-11-10T00:28:58.348Z',
        tags: [Object],
        maintainers: [Object],
        versions: [Object] } },
  _cached: true }
> url
'https://registry.npmjs.org/slc'
> regCache[url]
> regCache
{}
> pkg.versions
> pkg.time.unpublished
{ name: 'sillaps',
  time: '2016-11-10T00:28:58.348Z',
  tags: { latest: '0.1.3' },
  maintainers: [ { name: 'sillaps', email: 'inbox@sillaps.com' } ],
  versions: [ '0.1.1', '0.1.2', '0.1.3' ] }
debug>
(To exit, press ^C again or type .exit)
```

#### How can the CLI team reproduce the problem?
https://gist.github.com/Freyert/1499002de83053336590b3680a4352ec

### supporting information:

 - `npm -v` prints: 3.10.9
 - `node -v` prints: v4.6.2
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: OS X
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
This seems like a bug, but not of the type I though first. It seems that `slc` doesn't exist in the registry because it was unpublished. That is why the error happens. How about you change the title to something like `error while installing unpublished package: cannot convert undefined or null to object`. I will ping @zkat and @othiym23 and ask them what their thoughts are.
