### ISSUE TITLE
new config option: prompt-scripts

### ISSUE THREAD

**Issue by watson** [npm/npm#14659]
#### What's the feature?

You can already have npm ignore scripts by setting `npm config set ignore-scripts`, but in some cases you might have packages where you do want to run scripts. In that case this option isn't really useful. 

Instead I suggest another config option that can be called `prompt-scripts`.

When `prompt-scripts` is set, the npm cli will prompt the user during installation if he wants to run a script or not, e.g:

```
<package> wants to execute a script during installation. Continue? [Y/n]
```

#### What problem is the feature intended to solve?

Security

#### Is the absence of this feature blocking you or your team? If so, how?

No

#### Is this feature similar to an existing feature in another tool?

Not sure

#### Is this a feature you're prepared to implement, with support from the npm CLI team?

Maybe, but I doubt I have the time unfortunately

**Comment by legodude17** [comment]
This seems like a really good idea, maybe it could print the script. +1
