### ISSUE TITLE
npm proxy configuration error

### ISSUE THREAD

**Issue by zurajava** [npm/npm#14658]
#### I'm opening this issue because:

  - [ ] np

[npm-debug.txt](https://github.com/npm/npm/files/599567/npm-debug.txt)

I'm getting the error when i run npm install express command in command promt.

Before this command i have run the following command:

npm config set proxy "http://ufc%5Czurab.katsitadze:PASSWORD@proxy1:8080/"

Please help me how to solve this problem?

**Comment by legodude17** [comment]
This is a problem with your proxy.

**Comment by zurajava** [comment]
And how to solve this problem ? May i have wrong password or username?

**Comment by legodude17** [comment]
Maybe. This doesn't seem to be an issue with npm.
