### ISSUE TITLE
Suppress warnings for npm-shrinkwrap.json

### ISSUE THREAD

**Issue by monolithed** [npm/npm#14663]
#### What's going wrong?

```
➜  ls 
npm-shrinkwrap.json
```

```
npm install
```

```
➜ npm install
/private/tmp/test
└── noop@0.2.2 

npm WARN enoent ENOENT: no such file or directory, open '/private/tmp/test/package.json'
npm WARN test No description
npm WARN test No repository field.
npm WARN test No README data
npm WARN test No license field.
```

It's unexpected and strange behavior to see these warnings, because `npm-shrinkwrap.json` contains the same information as `package.json`

### supporting information:

 - `npm -v` prints: 3.10.8
 - `node -v` prints: v7.0.0
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?: Darwin

**Comment by legodude17** [comment]
I am really not sure about this. Your thoughts @KenanY. I am on the fence. One the one hand, this makes sense, but on the other hand, `npm` really needs the `package.json`.

**Comment by KenanY** [comment]
I don't know much about `install` logic. Maybe it still tries to read the `package.json`, regardless of the `npm-shrinkwrap.json`, in order to find stuff like lifecycle scripts, `"os"`, `"preferGlobal"`?

**Comment by legodude17** [comment]
Yeah, that seems right. I think I am -0.5 because it still needs `scripts`, `os`, and `preferGlobal`.
