### ISSUE TITLE
Problem to install discord.js on rasbian via npm

### ISSUE THREAD

**Issue by padhie** [npm/npm#14666]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
i'll try to install 'discord.js' in my Raspberry Pi 3 but i get even this error:
```
npm ERR! Linux 4.4.13-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "discord.js" "--save"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ENOSELF

npm ERR! Refusing to install discord.js as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/tests/node-discordbot/npm-debug.log
```

#### How can the CLI team reproduce the problem?

I follow the install guid on this git repo:  https://github.com/hydrabolt/discord.js
i try it with each of the three ways but even the same result.

https://gist.github.com/padhie/b8b30953772d6e4b23ddc265f7a05bad

On Windows i try it and have no problem.

### supporting information:

 - `npm -v` prints: 3.10.8
 - `node -v` prints: v6.9.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Raspbian (basic install on rasberry pi 3 device)
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [x] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
Is the `name` field of your `package.json` set to `discord.js`?

**Comment by padhie** [comment]
@legodude17 yes it is. the name, reposetory and all other required fields are set correkt.

**Comment by KenanY** [comment]
@padhie Make sure the `"name"` field is unique (as in, not shared by any of your dependencies).

**Comment by padhie** [comment]
@KenanY that is the package.json
https://gist.github.com/padhie/20a0db17562a37c1ec02a7347370d69a

it is unique

**Comment by KenanY** [comment]
@padhie Change the `"name"` field to something else, before trying to install something with the same name (your `package.json` has name `"discord.js"`, which prevents you from installing the package `discord.js`).
