### ISSUE TITLE
certificate error

### ISSUE THREAD

**Issue by subbuchaudhary** [npm/npm#14667]
```
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "jshint"
npm ERR! node v5.7.1
npm ERR! npm  v3.6.0
npm ERR! code UNABLE_TO_GET_ISSUER_CERT_LOCALLY
npm ERR! unable to get local issuer certificate
```

#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
Please fill out the issue template and then ping me when you do. Thanks for you cooperation!

**Comment by subbuchaudhary** [comment]
@legodude17 @KenanY 
Supporting Information:
$ npm config get proxy
null
$ echo $PATH
/Users/username/npm-global/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
$ npm config get prefix
/Users/username/npm-global
$ cat ~/.profile
export PATH=/Users/username/npm-global/bin:$PATH
$ npm config ls
; cli configs
user-agent = "npm/3.6.0 node/v5.7.1 darwin x64"

; userconfig /Users/username/.npmrc
prefix = "/Users/username/npm-global"

; node bin location = /usr/local/bin/node
; cwd = /Users/username/npm-global
; HOME = /Users/username
; "npm config ls -l" to show all defaults.

**Comment by legodude17** [comment]
Can you please put the `npm-debug.log` in a gist and then post the link?

**Comment by subbuchaudhary** [comment]
@legodude17 @KenanY 
npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'jshint' ]
2 info using npm@3.6.0
3 info using node@v5.7.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData jshint
8 silly fetchNamedPackageData jshint
9 silly mapToRegistry name jshint
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/jshint
13 verbose request uri https://registry.npmjs.org/jshint
14 verbose request no auth needed
15 info attempt registry request try #1 at 4:19:39 PM
16 verbose request id a81c014d2645a8d1
17 http request GET https://registry.npmjs.org/jshint
18 info retry will retry, error on last attempt: Error: unable to get local issuer certificate
19 info attempt registry request try #2 at 4:19:49 PM
20 http request GET https://registry.npmjs.org/jshint
21 info retry will retry, error on last attempt: Error: unable to get local issuer certificate
22 info attempt registry request try #3 at 4:20:50 PM
23 http request GET https://registry.npmjs.org/jshint
24 silly fetchPackageMetaData Error: unable to get local issuer certificate
24 silly fetchPackageMetaData     at Error (native)
24 silly fetchPackageMetaData     at TLSSocket.<anonymous> (_tls_wrap.js:1061:38)
24 silly fetchPackageMetaData     at emitNone (events.js:80:13)
24 silly fetchPackageMetaData     at TLSSocket.emit (events.js:179:7)
24 silly fetchPackageMetaData     at TLSSocket._init.ssl.onclienthello.ssl.oncertcb.TLSSocket._finishInit (_tls_wrap.js:593:8)
24 silly fetchPackageMetaData     at TLSWrap.ssl.onclienthello.ssl.oncertcb.ssl.onnewsession.ssl.onhandshakedone (_tls_wrap.js:425:38)
24 silly fetchPackageMetaData  error for jshint { [Error: unable to get local issuer certificate] code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY' }
25 silly rollbackFailedOptional Starting
26 silly rollbackFailedOptional Finishing
27 silly runTopLevelLifecycles Starting
28 silly runTopLevelLifecycles Finishing
29 silly install printInstalled
30 verbose stack Error: unable to get local issuer certificate
30 verbose stack     at Error (native)
30 verbose stack     at TLSSocket.<anonymous> (_tls_wrap.js:1061:38)
30 verbose stack     at emitNone (events.js:80:13)
30 verbose stack     at TLSSocket.emit (events.js:179:7)
30 verbose stack     at TLSSocket._init.ssl.onclienthello.ssl.oncertcb.TLSSocket._finishInit (_tls_wrap.js:593:8)
30 verbose stack     at TLSWrap.ssl.onclienthello.ssl.oncertcb.ssl.onnewsession.ssl.onhandshakedone (_tls_wrap.js:425:38)
31 verbose cwd /Users/u546007
32 error Darwin 15.6.0
33 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "jshint"
34 error node v5.7.1
35 error npm  v3.6.0
36 error code UNABLE_TO_GET_ISSUER_CERT_LOCALLY
37 error unable to get local issuer certificate
38 error If you need help, you may report this error at:
38 error     <https://github.com/npm/npm/issues>
39 verbose exit [ 1, true ]

**Comment by legodude17** [comment]
Did you make sure to build nodejs with crypto?

**Comment by subbuchaudhary** [comment]
@legodude17 what does it meant by?
I did not get you?

**Comment by subbuchaudhary** [comment]
@legodude17 
i tried 
$npm install crypto-js
it also gave same error

**Comment by legodude17** [comment]
If you don't understand, it is fine. How did you install `nodejs` and `npm`?

**Comment by subbuchaudhary** [comment]
@legodude17 
I simply downloaded nodev5.7.1.pkg file from nodejs.org and installed it. then i set the npm permissions as shown in npm documentation web site.

**Comment by subbuchaudhary** [comment]
@legodude17 @KenanY @othiym23 
Is there any solution for my error?

**Comment by subbuchaudhary** [comment]
@legodude17 @othiym23 
Thanks for spending your valuable time for me
This command solved my issue
npm config set strict-ssl false

**Comment by subbuchaudhary** [comment]
<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:s="http://www.w3.org/2001/XMLSchema" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:tns="http://tempuri.org/" xmlns:s1="http://microsoft.com/wsdl/types/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tm="http://microsoft.com/wsdl/mime/textMatching/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" targetNamespace="http://tempuri.org/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types>
    <s:schema elementFormDefault="qualified" targetNamespace="http://tempuri.org/">
      <s:import namespace="http://microsoft.com/wsdl/types/" />
      <s:element name="GetRequestedInspections">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="userId" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="password" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="status" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="inspectorId" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="GetRequestedInspectionsResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="GetRequestedInspectionsResult" type="tns:ArrayOfCustomScheduleCustomer" />
            <s:element minOccurs="0" maxOccurs="1" name="status" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:complexType name="ArrayOfCustomScheduleCustomer">
        <s:sequence>
          <s:element minOccurs="0" maxOccurs="unbounded" name="CustomScheduleCustomer" nillable="true" type="tns:CustomScheduleCustomer" />
        </s:sequence>
      </s:complexType>
      <s:complexType name="CustomScheduleCustomer">
        <s:sequence>
          <s:element minOccurs="1" maxOccurs="1" name="InspectionId" type="s1:guid" />
          <s:element minOccurs="0" maxOccurs="1" name="AllianceId" type="s:string" />
          <s:element minOccurs="0" maxOccurs="1" name="CustomerNumber" type="s:string" />
          <s:element minOccurs="0" maxOccurs="1" name="Path" type="s:string" />
        </s:sequence>
      </s:complexType>
      <s:element name="UploadInspection">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="userId" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="password" type="s:string" />
            <s:element minOccurs="1" maxOccurs="1" name="inspectionId" type="s1:guid" />
            <s:element minOccurs="0" maxOccurs="1" name="allianceId" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="CustomerNumber" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="fileName" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="fileData" type="s:base64Binary" />
            <s:element minOccurs="1" maxOccurs="1" name="isFileUpload" type="s:boolean" />
            <s:element minOccurs="0" maxOccurs="1" name="status" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="UploadInspectionResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="status" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="GenerateControlTable">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="userId" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="password" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="fsrID" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="fileName" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="status" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="GenerateControlTableResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="GenerateControlTableResult" type="s:base64Binary" />
            <s:element minOccurs="0" maxOccurs="1" name="status" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="DownloadInspectionFiles">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="userId" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="password" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="fileName" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="status" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="DownloadInspectionFilesResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="DownloadInspectionFilesResult" type="s:base64Binary" />
            <s:element minOccurs="0" maxOccurs="1" name="status" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="setInspectionStatus">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="userId" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="password" type="s:string" />
            <s:element minOccurs="1" maxOccurs="1" name="inspectionId" type="s1:guid" />
            <s:element minOccurs="0" maxOccurs="1" name="status" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="CustomerNumber" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="allianceId" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="inspectionStatus" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="inspectorId" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="setInspectionStatusResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="status" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="GetMICustomers">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="userId" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="password" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="status" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="GetMICustomersResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="GetMICustomersResult" type="tns:ArrayOfMICustomerData" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:complexType name="ArrayOfMICustomerData">
        <s:sequence>
          <s:element minOccurs="0" maxOccurs="unbounded" name="MICustomerData" nillable="true" type="tns:MICustomerData" />
        </s:sequence>
      </s:complexType>
      <s:complexType name="MICustomerData">
        <s:sequence>
          <s:element minOccurs="0" maxOccurs="1" name="CustomerNumber" type="s:string" />
          <s:element minOccurs="0" maxOccurs="1" name="CustomerName" type="s:string" />
          <s:element minOccurs="0" maxOccurs="1" name="VBUName" type="s:string" />
          <s:element minOccurs="0" maxOccurs="1" name="MasterNumber" type="s:string" />
          <s:element minOccurs="0" maxOccurs="1" name="BranchRegion" type="s:string" />
          <s:element minOccurs="0" maxOccurs="1" name="BranchDescription" type="s:string" />
          <s:element minOccurs="0" maxOccurs="1" name="StatusCode" type="s:string" />
        </s:sequence>
      </s:complexType>
      <s:element name="MIBranchNumber">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="userId" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="password" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="customerNumber" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="status" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="MIBranchNumberResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="MIBranchNumberResult" type="tns:MICustomerData" />
            <s:element minOccurs="0" maxOccurs="1" name="status" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="PasswordAuthenticate">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="userId" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="password" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="status" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="PasswordAuthenticateResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="PasswordAuthenticateResult" type="tns:AuthResponse" />
            <s:element minOccurs="0" maxOccurs="1" name="status" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:complexType name="AuthResponse">
        <s:sequence>
          <s:element minOccurs="1" maxOccurs="1" name="AuthPassed" type="s:boolean" />
          <s:element minOccurs="0" maxOccurs="1" name="StatusCode" type="s:string" />
          <s:element minOccurs="0" maxOccurs="1" name="StatusMessage" type="s:string" />
          <s:element minOccurs="0" maxOccurs="1" name="UserFirstName" type="s:string" />
          <s:element minOccurs="0" maxOccurs="1" name="UserLastName" type="s:string" />
          <s:element minOccurs="0" maxOccurs="1" name="ManagerId" type="s:string" />
          <s:element minOccurs="0" maxOccurs="1" name="ManagerName" type="s:string" />
        </s:sequence>
      </s:complexType>
    </s:schema>
    <s:schema elementFormDefault="qualified" targetNamespace="http://microsoft.com/wsdl/types/">
      <s:simpleType name="guid">
        <s:restriction base="s:string">
          <s:pattern value="[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}" />
        </s:restriction>
      </s:simpleType>
    </s:schema>
  </wsdl:types>
  <wsdl:message name="GetRequestedInspectionsSoapIn">
    <wsdl:part name="parameters" element="tns:GetRequestedInspections" />
  </wsdl:message>
  <wsdl:message name="GetRequestedInspectionsSoapOut">
    <wsdl:part name="parameters" element="tns:GetRequestedInspectionsResponse" />
  </wsdl:message>
  <wsdl:message name="UploadInspectionSoapIn">
    <wsdl:part name="parameters" element="tns:UploadInspection" />
  </wsdl:message>
  <wsdl:message name="UploadInspectionSoapOut">
    <wsdl:part name="parameters" element="tns:UploadInspectionResponse" />
  </wsdl:message>
  <wsdl:message name="GenerateControlTableSoapIn">
    <wsdl:part name="parameters" element="tns:GenerateControlTable" />
  </wsdl:message>
  <wsdl:message name="GenerateControlTableSoapOut">
    <wsdl:part name="parameters" element="tns:GenerateControlTableResponse" />
  </wsdl:message>
  <wsdl:message name="DownloadInspectionFilesSoapIn">
    <wsdl:part name="parameters" element="tns:DownloadInspectionFiles" />
  </wsdl:message>
  <wsdl:message name="DownloadInspectionFilesSoapOut">
    <wsdl:part name="parameters" element="tns:DownloadInspectionFilesResponse" />
  </wsdl:message>
  <wsdl:message name="setInspectionStatusSoapIn">
    <wsdl:part name="parameters" element="tns:setInspectionStatus" />
  </wsdl:message>
  <wsdl:message name="setInspectionStatusSoapOut">
    <wsdl:part name="parameters" element="tns:setInspectionStatusResponse" />
  </wsdl:message>
  <wsdl:message name="GetMICustomersSoapIn">
    <wsdl:part name="parameters" element="tns:GetMICustomers" />
  </wsdl:message>
  <wsdl:message name="GetMICustomersSoapOut">
    <wsdl:part name="parameters" element="tns:GetMICustomersResponse" />
  </wsdl:message>
  <wsdl:message name="MIBranchNumberSoapIn">
    <wsdl:part name="parameters" element="tns:MIBranchNumber" />
  </wsdl:message>
  <wsdl:message name="MIBranchNumberSoapOut">
    <wsdl:part name="parameters" element="tns:MIBranchNumberResponse" />
  </wsdl:message>
  <wsdl:message name="PasswordAuthenticateSoapIn">
    <wsdl:part name="parameters" element="tns:PasswordAuthenticate" />
  </wsdl:message>
  <wsdl:message name="PasswordAuthenticateSoapOut">
    <wsdl:part name="parameters" element="tns:PasswordAuthenticateResponse" />
  </wsdl:message>
  <wsdl:portType name="FSGExternalServiceSoap">
    <wsdl:operation name="GetRequestedInspections">
      <wsdl:input message="tns:GetRequestedInspectionsSoapIn" />
      <wsdl:output message="tns:GetRequestedInspectionsSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="UploadInspection">
      <wsdl:input message="tns:UploadInspectionSoapIn" />
      <wsdl:output message="tns:UploadInspectionSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="GenerateControlTable">
      <wsdl:input message="tns:GenerateControlTableSoapIn" />
      <wsdl:output message="tns:GenerateControlTableSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="DownloadInspectionFiles">
      <wsdl:input message="tns:DownloadInspectionFilesSoapIn" />
      <wsdl:output message="tns:DownloadInspectionFilesSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="setInspectionStatus">
      <wsdl:input message="tns:setInspectionStatusSoapIn" />
      <wsdl:output message="tns:setInspectionStatusSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="GetMICustomers">
      <wsdl:input message="tns:GetMICustomersSoapIn" />
      <wsdl:output message="tns:GetMICustomersSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="MIBranchNumber">
      <wsdl:input message="tns:MIBranchNumberSoapIn" />
      <wsdl:output message="tns:MIBranchNumberSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="PasswordAuthenticate">
      <wsdl:input message="tns:PasswordAuthenticateSoapIn" />
      <wsdl:output message="tns:PasswordAuthenticateSoapOut" />
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="FSGExternalServiceSoap" type="tns:FSGExternalServiceSoap">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="GetRequestedInspections">
      <soap:operation soapAction="http://tempuri.org/GetRequestedInspections" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="UploadInspection">
      <soap:operation soapAction="http://tempuri.org/UploadInspection" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="GenerateControlTable">
      <soap:operation soapAction="http://tempuri.org/GenerateControlTable" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="DownloadInspectionFiles">
      <soap:operation soapAction="http://tempuri.org/DownloadInspectionFiles" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="setInspectionStatus">
      <soap:operation soapAction="http://tempuri.org/setInspectionStatus" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="GetMICustomers">
      <soap:operation soapAction="http://tempuri.org/GetMICustomers" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="MIBranchNumber">
      <soap:operation soapAction="http://tempuri.org/MIBranchNumber" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="PasswordAuthenticate">
      <soap:operation soapAction="http://tempuri.org/PasswordAuthenticate" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:binding name="FSGExternalServiceSoap12" type="tns:FSGExternalServiceSoap">
    <soap12:binding transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="GetRequestedInspections">
      <soap12:operation soapAction="http://tempuri.org/GetRequestedInspections" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="UploadInspection">
      <soap12:operation soapAction="http://tempuri.org/UploadInspection" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="GenerateControlTable">
      <soap12:operation soapAction="http://tempuri.org/GenerateControlTable" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="DownloadInspectionFiles">
      <soap12:operation soapAction="http://tempuri.org/DownloadInspectionFiles" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="setInspectionStatus">
      <soap12:operation soapAction="http://tempuri.org/setInspectionStatus" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="GetMICustomers">
      <soap12:operation soapAction="http://tempuri.org/GetMICustomers" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="MIBranchNumber">
      <soap12:operation soapAction="http://tempuri.org/MIBranchNumber" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="PasswordAuthenticate">
      <soap12:operation soapAction="http://tempuri.org/PasswordAuthenticate" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="FSGExternalService">
    <wsdl:port name="FSGExternalServiceSoap" binding="tns:FSGExternalServiceSoap">
      <soap:address location="https://wdvwa99a0106/Fieldservices.FSGExternal.Service/FSGExternalService.asmx" />
    </wsdl:port>
    <wsdl:port name="FSGExternalServiceSoap12" binding="tns:FSGExternalServiceSoap12">
      <soap12:address location="https://wdvwa99a0106/Fieldservices.FSGExternal.Service/FSGExternalService.asmx" />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>

**Comment by subbuchaudhary** [comment]
FSGExternalService

Click here for a complete list of operations.

PasswordAuthenticate

Test

The test form is only available for requests from the local machine.
SOAP 1.1

The following is a sample SOAP 1.1 request and response. The placeholders shown need to be replaced with actual values.

POST /Fieldservices.FSGExternal.Service/FSGExternalService.asmx HTTP/1.1
Host: wdvwa99a0106
Content-Type: text/xml; charset=utf-8
Content-Length: length
SOAPAction: "http://tempuri.org/PasswordAuthenticate"

<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <PasswordAuthenticate xmlns="http://tempuri.org/">
      <userId>string</userId>
      <password>string</password>
      <status>string</status>
    </PasswordAuthenticate>
  </soap:Body>
</soap:Envelope>
HTTP/1.1 200 OK
Content-Type: text/xml; charset=utf-8
Content-Length: length

<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <PasswordAuthenticateResponse xmlns="http://tempuri.org/">
      <PasswordAuthenticateResult>
        <AuthPassed>boolean</AuthPassed>
        <StatusCode>string</StatusCode>
        <StatusMessage>string</StatusMessage>
        <UserFirstName>string</UserFirstName>
        <UserLastName>string</UserLastName>
        <ManagerId>string</ManagerId>
        <ManagerName>string</ManagerName>
      </PasswordAuthenticateResult>
      <status>string</status>
    </PasswordAuthenticateResponse>
  </soap:Body>
</soap:Envelope>
SOAP 1.2

The following is a sample SOAP 1.2 request and response. The placeholders shown need to be replaced with actual values.

POST /Fieldservices.FSGExternal.Service/FSGExternalService.asmx HTTP/1.1
Host: wdvwa99a0106
Content-Type: application/soap+xml; charset=utf-8
Content-Length: length

<?xml version="1.0" encoding="utf-8"?>
<soap12:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap12="http://www.w3.org/2003/05/soap-envelope">
  <soap12:Body>
    <PasswordAuthenticate xmlns="http://tempuri.org/">
      <userId>string</userId>
      <password>string</password>
      <status>string</status>
    </PasswordAuthenticate>
  </soap12:Body>
</soap12:Envelope>
HTTP/1.1 200 OK
Content-Type: application/soap+xml; charset=utf-8
Content-Length: length

<?xml version="1.0" encoding="utf-8"?>
<soap12:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap12="http://www.w3.org/2003/05/soap-envelope">
  <soap12:Body>
    <PasswordAuthenticateResponse xmlns="http://tempuri.org/">
      <PasswordAuthenticateResult>
        <AuthPassed>boolean</AuthPassed>
        <StatusCode>string</StatusCode>
        <StatusMessage>string</StatusMessage>
        <UserFirstName>string</UserFirstName>
        <UserLastName>string</UserLastName>
        <ManagerId>string</ManagerId>
        <ManagerName>string</ManagerName>
      </PasswordAuthenticateResult>
      <status>string</status>
    </PasswordAuthenticateResponse>
  </soap12:Body>
</soap12:Envelope>

**Comment by subbuchaudhary** [comment]
Soap dealer list
(

    "<MICustomerData><CustomerNumber>112204</CustomerNumber><CustomerName>THROW ROOF $O$ , CORP</CustomerName><VBUName>RV</VBUName><MasterNumber>112204</MasterNumber><BranchRegion>3325</BranchRegion><BranchDescription>West RV</BranchDescription><StatusCode>CLOS</StatusCode></MICustomerData>",
    "<MICustomerData><CustomerNumber>142698</CustomerNumber><CustomerName>UNIQUE HEAT $O$ PARTNERS</CustomerName><VBUName>CSHPI</VBUName><MasterNumber>142698</MasterNumber><BranchRegion>1367</BranchRegion><BranchDescription>Atlanta</BranchDescription><StatusCode>OPEN</StatusCode></MICustomerData>",
    "<MICustomerData><CustomerNumber>175419</CustomerNumber><CustomerName>SAFEGUARD SHOT $O$ LLC</CustomerName><VBUName>DPG - SPG</VBUName><MasterNumber>175419</MasterNumber><BranchRegion>602</BranchRegion><BranchDescription>Horse Trailers</BranchDescription><StatusCode>CLOS</StatusCode></MICustomerData>"

)
dealerList
<__NSArrayM 0x7a307bf0>(
<Dealer: 0x78f86260> (entity: Dealer; id: 0x78f88090 <x-coredata:///Dealer/t34DC52D5-F5CD-49CD-AC7F-EF3B297F9DBC3> ; data: {
    branchDescription = nil;
    branchNo = 3325;
    customerName = "THROW ROOF $O$ , CORP";
    customerNo = 112204;
    masterNumber = nil;
    statusCode = nil;
    vbu = RV;
}),
<Dealer: 0x78f848b0> (entity: Dealer; id: 0x78f24e40 <x-coredata:///Dealer/t34DC52D5-F5CD-49CD-AC7F-EF3B297F9DBC4> ; data: {
    branchDescription = nil;
    branchNo = 1367;
    customerName = "UNIQUE HEAT $O$ PARTNERS";
    customerNo = 142698;
    masterNumber = nil;
    statusCode = nil;
    vbu = CSHPI;
}),
<Dealer: 0x78e25db0> (entity: Dealer; id: 0x78e25df0 <x-coredata:///Dealer/t34DC52D5-F5CD-49CD-AC7F-EF3B297F9DBC5> ; data: {
    branchDescription = nil;
    branchNo = 602;
    customerName = "SAFEGUARD SHOT $O$ LLC";
    customerNo = 175419;
    masterNumber = nil;
    statusCode = nil;
    vbu = "DPG - SPG";
})
)
