### ISSUE TITLE
Npm fails to search packages

### ISSUE THREAD

**Issue by kricir** [npm/npm#14672]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I am trying to search npm packages, upon trying "npm search php"...

Error Returned...
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "search" "php"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8

npm ERR! Cannot read property '_updated' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN Building the local index for the first time, please be patient

<--- Last few GCs --->

   46628 ms: Mark-sweep 1066.2 (1386.5) -> 1040.2 (1366.1) MB, 883.7 / 0.0 ms [allocation failure] [GC in old space requested].
   47532 ms: Mark-sweep 1040.2 (1366.1) -> 1040.1 (1326.1) MB, 904.0 / 0.0 ms [last resort gc].
   48501 ms: Mark-sweep 1040.1 (1326.1) -> 1040.1 (1320.1) MB, 969.2 / 0.0 ms [last resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x1db4861cfb51 <JS Object>
    1: fromString(aka fromString) [buffer.js:199] [pc=0x1ef3520ac490] (this=0x1db486104381 <undefined>,string=0x2082377d57c9 <Very long string[217886406]>,encoding=0x1db4861dd361 <String[4]: utf8>)
    2: from [buffer.js:99] [pc=0x1ef35205c742] (this=0x6077cfaa0f1 <JS Function Buffer (SharedFunctionInfo 0x20a31cff6181)>,value=0x2082377d57c9 <Very long string[217886406]>,encodingOrOffset=0x1db48...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 4: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [/usr/local/bin/node]
 5: v8::internal::String::SlowFlatten(v8::internal::Handle<v8::internal::ConsString>, v8::internal::PretenureFlag) [/usr/local/bin/node]
 6: v8::String::WriteUtf8(char*, int, int*, int) const [/usr/local/bin/node]
 7: node::StringBytes::Write(v8::Isolate*, char*, unsigned long, v8::Local<v8::Value>, node::encoding, int*) [/usr/local/bin/node]
 8: node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) [/usr/local/bin/node]
 9: node::Buffer::CreateFromString(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
10: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [/usr/local/bin/node]
11: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::(anonymous namespace)::BuiltinArguments<(v8::internal::BuiltinExtraArguments)1>) [/usr/local/bin/node]
12: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
13: 0x1ef351b092a7
Abort trap: 6

Log file....
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'search', 'php' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 silly mapToRegistry name -/all
5 silly mapToRegistry using default registry
6 silly mapToRegistry registry https://registry.npmjs.org/
7 silly mapToRegistry data Result {
7 silly mapToRegistry   raw: '-/all',
7 silly mapToRegistry   scope: null,
7 silly mapToRegistry   escapedName: null,
7 silly mapToRegistry   name: null,
7 silly mapToRegistry   rawSpec: '-/all',
7 silly mapToRegistry   spec: '-/all',
7 silly mapToRegistry   type: 'local' }
8 silly mapToRegistry uri https://registry.npmjs.org/-/all
9 info updateIndex /Users/richardkreitel/.npm/registry.npmjs.org/-/all/.cache.json
10 verbose correctMkdir /Users/richardkreitel/.npm correctMkdir not in flight; initializing
11 verbose stack TypeError: Cannot read property '_updated' of undefined
11 verbose stack     at /usr/local/lib/node_modules/npm/lib/cache/update-index.js:61:26
11 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:233:18
11 verbose stack     at FSReqWrap.oncomplete (fs.js:123:15)
12 verbose cwd /Users/richardkreitel/Library/Mobile Documents/com~apple~CloudDocs/Sites/Right Syntax/Site/Wordpress/wp-content/themes/rsyntax
13 error Darwin 16.1.0
14 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "search" "php"
15 error node v6.9.1
16 error npm  v3.10.8
17 error Cannot read property '_updated' of undefined
18 error If you need help, you may report this error at:
18 error     <https://github.com/npm/npm/issues>
19 verbose exit [ 1, true ]

#### How can the CLI team reproduce the problem?

$ npm search php

### supporting information:

 - `npm -v` prints:  3.10.8
 - `node -v` prints: v6.9.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: OS X
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [x] I develop using Vagrant on Windows.
   - [x] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
Already fixed in `npm@4.0.0`

**Comment by kricir** [comment]
Fixed by following https://docs.npmjs.com/getting-started/installing-node using this update code

`npm install npm@latest -g`
