### ISSUE TITLE
nam run start error

### ISSUE THREAD

**Issue by jeroen1972** [npm/npm#14674]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [X ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'start' ]
2 info using npm@2.14.7
3 info using node@v4.2.1
4 verbose stack Error: missing script: start
4 verbose stack     at run (/usr/local/lib/node_modules/npm/lib/run-script.js:142:19)
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/run-script.js:58:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:345:5
4 verbose stack     at handleExists (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:318:20)
4 verbose stack     at FSReqWrap.cb [as oncomplete] (fs.js:212:19)
5 verbose cwd /home/pi/homebridge
6 error Linux 4.1.18-v7+
7 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
8 error node v4.2.1
9 error npm  v2.14.7
10 error missing script: start
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
~                                

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by arekkas** [comment]
It's right there in the output: `error missing script: start`. You are running a command that does apparently not exist.

**Comment by KenanY** [comment]
Check out <https://docs.npmjs.com/misc/scripts> for how scripts work and how to write your own. You need to define a `"start"` script in your `package.json` before running `npm run start`.
