### ISSUE TITLE
npm install --save can generate ugly diffs modifying unrelated lines

### ISSUE THREAD

**Issue by binki** [npm/npm#14678]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?

When I use `npm install --save` or `npm uninstall --save`, sometimes the automatic edits to `package.json` span multiple lines, possibly causing needless merge conflicts in the future.

#### How can the CLI team reproduce the problem?

1. `mkdir nonexistent-directory`
1. `cd nonexistent-directory`
1. `npm init -y`
1. `npm install --save bluebird`
1. `git init`
1. `git add package.json`
1. `git commit -m initial`
1. `npm install --save xyzzy`

This results in an ugly diff where unrelated lines are altered:

```
$ git diff
diff --git a/package.json b/package.json
index db59d16..6575970 100644
--- a/package.json
+++ b/package.json
@@ -10,6 +10,7 @@
   "author": "",
   "license": "ISC",
   "dependencies": {
-    "bluebird": "^3.4.6"
+    "bluebird": "^3.4.6",
+    "xyzzy": "0.0.2"
   }
 }
```

### supporting information:

 - `npm -v` prints: `3.10.8`
 - `node -v` prints: `v7.0.0`
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?: Linux, but issue is platform agnostic

My only idea on how to fix this is to adopt JSON5 and have automatic edits always create trailing commas for arrays in `package.json`.

**Comment by zkat** [comment]
While I see what you mean, the CLI team considers this a minor issue, and certainly not enough to justify us moving to a new JSON standard, considering our commitment to using a plain JSON manifest (and also, considering that many many versions of npm out in the wild do not have JSON5 support, so this could be an ecosystem-wrecking change!)

Thanks for your time! I hope that explanation clarifies stuff enough ❤️

**Comment by binki** [comment]
> many many versions of npm out in the wild do not have JSON5 support, so this could be an ecosystem-wrecking change!

Breaking `npm publish` wouldn’t matter. It is reasonable to expect people developing/uploading packages to use modern tools. Of course the package repository itself should continue using JSON.

But I get that y’all want to keep npm simple where you can.
