### ISSUE TITLE
ERR! Unexpected token <

### ISSUE THREAD

**Issue by somethingsaid** [npm/npm#14688]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
npm install is producing error: Unexpected token <

#### How can the CLI team reproduce the problem?
Please see my npm-debug.log:
https://gist.github.com/somethingsaid/1f3aabdc41baf3cd2b87a9d601bfcd50#file-gistfile1-txt

### supporting information:

 - `npm -v` prints: 3.10.9
 - `node -v` prints: v4.5.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows

**Comment by legodude17** [comment]
Any ideas @KenanY?
