### ISSUE TITLE
Version not found error for socket.io-client@1.6.0

### ISSUE THREAD

**Issue by sridharvasudev** [npm/npm#14683]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [X] Other (_see below for feature requests_):

#### What's going wrong?
while installing karma it is failing with below error. It says version not found socket.io-client@1.6.0 .
The same was running previously without any error. I also saw statusCode 404 from the npm debug log. Does it mean the repository URL 404 not found ?

> 13430 verbose stack Error: version not found: socket.io-client@1.6.0
> 13430 verbose stack     at setData (C:\Users\***\a\git-local\MCR\feature\RO\node\node_modules\npm\lib\cache\add-named.js:137:12)
> 13430 verbose stack     at RES (C:\Users\***\a\git-local\MCR\feature\RO\node\node_modules\npm\node_modules\inflight\inflight.js:23:14)
> 13430 verbose stack     at f (C:\Users\***\a\git-local\MCR\feature\RO\node\node_modules\npm\node_modules\once\once.js:17:25)
> 13430 verbose stack     at fixName (C:\Users\***\a\git-local\MCR\feature\RO\node\node_modules\npm\lib\cache\add-named.js:29:5)
> 13430 verbose stack     at saved (C:\Users\***\a\git-local\MCR\feature\RO\node\node_modules\npm\lib\cache\caching-client.js:173:7)

> 13430 verbose stack     at C:\Users\***\a\git-local\MCR\feature\RO\node\node_modules\npm\node_modules\graceful-fs\polyfills.js:210:7
> 13430 verbose stack     at FSReqWrap.oncomplete (fs.js:82:15)
> **13431 verbose statusCode 404**

**Comment by KenanY** [comment]
@sridharvasudev Could you upload the full `npm-debug.log` file to <https://gist.github.com/> and post the link here?

**Comment by KenanY** [comment]
Closing due to lack of a response.
