### ISSUE TITLE
npm3 always exiting with code 0

### ISSUE THREAD

**Issue by gegis** [npm/npm#14690]
#### I'm opening this issue because:

  - [x] npm is doing something I don't understand.

#### What's going wrong?
Recently we have noticed that custom gulp scripts, ran with npm, don't fail the Jenkins build jobs, where they should. 

So we just quickly ran a test, we have 2 versions of npm installed, v2 and v3, v3 was installed using: ```https://www.npmjs.com/package/npm3```

Running script with npm it does exit with expected code, however running script with npm3 always exits with code 0, which then does not fail the build jobs.

#### How can the CLI team reproduce the problem?
Init simple npm project, and have ```index.js``` with the following code:
```
process.exit(1)
```

package.json:
```
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "node index.js",
    "custom": "node index.js"
  },
  "author": "test",
  "license": "ISC"
}
```
Running:
```npm run custom``` - exits with expected code.
```npm3 run custom``` - exits with code 0.

### supporting information:

Working versions:

 - `npm -v` prints: 2.15.8
 - `node -v` prints: v4.4.7
 - `npm config get registry` prints: https://registry.npmjs.org/

Non working versions:
 - `npm3 -v` prints: 3.10.9
 - `node -v` prints: v4.4.7
 - `npm3 config get registry` prints: https://registry.npmjs.org/

 - Windows, OS X/macOS, or Linux?: Linux Debian and RedHat

**Comment by othiym23** [comment]
npm3 is a third-party wrapper for `npm@3`, and not supported by the CLI team. Does this also happen when running `npm@3` installed with `npm install -g npm@latest-3`? If not, then this is an issue for the [npm3 maintainer](https://github.com/timoxley/npm3/issues).

**Comment by gegis** [comment]
Sorry, it does work correctly after installing latest with ```npm install -g npm@latest-3```, I will raise issue with third-party wrapper.
