### ISSUE TITLE
npm  can't run in this directory, in other  directory can run normal.

### ISSUE THREAD

**Issue by Create-Peace** [npm/npm#14697]
#### I'm opening this issue because:

  - [ ] npm is crashing.
 npm ERR! Windows_NT 10.0.10586
npm ERR! argv "E:\\Program Files\\nodejs\\node.exe" "C:\\Users\\M-Ray\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "ls"
npm ERR! node v4.5.0
npm ERR! npm  v3.0.0

npm ERR! Maximum call stack size exceeded
![npmwrong](https://cloud.githubusercontent.com/assets/12973954/20513014/4a6c5b0a-b0be-11e6-885b-a0aec93fc74e.png)

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@Create-Peace Does this also occur with newer versions of `npm`?

**Comment by KenanY** [comment]
Closing due to lack of any response.
