### ISSUE TITLE
react error UNMET PEER DEPENDENCY react@15.4.0

### ISSUE THREAD

**Issue by HansRA** [npm/npm#14696]
root@hans-Satellite-C75D-B:/home/hans# npm install --save react react-dom
hans@1.0.0 /home/hans
├── UNMET PEER DEPENDENCY react@15.4.0
├── UNMET PEER DEPENDENCY react-addons-css-transition-group@15.4.0
└── UNMET PEER DEPENDENCY react-dom@15.4.0

npm WARN optional Skipping failed optional dependency /babel-cli/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.15
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@0.2.0
npm WARN optional Skipping failed optional dependency /watchpack/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.15
npm WARN react-toolbox@1.2.5 requires a peer of react@~0.14 || ~15.3.0 but none was installed.
npm WARN react-toolbox@1.2.5 requires a peer of react-addons-css-transition-group@~0.14.0 || ~15.3.0 but none was installed.
npm WARN react-toolbox@1.2.5 requires a peer of react-dom@~0.14.0 || ~15.3.0 but none was installed.
npm WARN hans@1.0.0 No repository field.
npm ERR! code 1

**Comment by KenanY** [comment]
@HansRA You need to match the semver range of your `react-toolbox` peer dependencies, so try:

```
npm install --save react@~15.3.0 react-dom@~15.3.0
```

**Comment by HansRA** [comment]
Thanks @KenanY  but the error is still the same

root@hans-Satellite-C75D-B:/home/hans# npm install --save react@~15.3.0 react-dom@~15.3.0
hans@1.0.0 /home/hans
├── UNMET PEER DEPENDENCY react@15.3.2
├── UNMET PEER DEPENDENCY react-addons-css-transition-group@15.4.0
└── react-dom@15.3.2 

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/babel-cli/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@0.2.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@0.2.0: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/watchpack/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN react-addons-css-transition-group@15.4.0 requires a peer of react@^15.4.0 but none was installed.
npm WARN react-toolbox@1.2.5 requires a peer of react-addons-css-transition-group@~0.14.0 || ~15.3.0 but none was installed.
npm WARN hans@1.0.0 No repository field.
root@hans-Satellite-C75D-B:/home/hans#

**Comment by KenanY** [comment]
@HansRA You gotta downgrade `react-addons-css-transition-group` as well to `@15.3`.

**Comment by HansRA** [comment]
@KenanY  thanks but how to downgrade react-addons-css-transition-group as well to @15.3   please

**Comment by KenanY** [comment]
@HansRA Same as how you did for `react` and `react-dom`?

**Comment by KenanY** [comment]
Closing as abandoned.

**Comment by queli1990** [comment]
npm install -g yarn
then create-react-app AppName
then npm install react-router
(sudo npm install -g npm)
