### ISSUE TITLE
npm shrinkwrap chicken/egg problem: How do you upgrade a pkg when `npm i` fails?

### ISSUE THREAD

**Issue by i-a-n** [npm/npm#14691]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?

When using `npm-shrinkwrap` and `npm i` fails—for instance, let's say a grand-dependency has gone missing from the npmjs registry—I can't see how one is supposed to fix this issue without completely regenerating `npm-shrinkwrap.json`. 

Let's say our failing install looks like this:

```
my-package@1.0.0
 ├─ package-a@1.0.0
 └─ package-b@1.0.0
    └─ package-c@1.0.0 [ THIS ONE HAS GONE MISSING FROM NPMJS REGISTRY ]
```

And let's say the fix is to upgrade `package-b` to `package-b@1.0.1`, because the new patch has updated its `package.json` to use a new `package-c`. How am I supposed to upgrade `package-b`?

I can't just run `$ npm install package-b@1.0.1 --save`; this fails to save `npm-shrinkwrap.json` because of errors that look like this:

```npm WARN saveError missing: [some-package] required by my-package@1.0.0```

And I can't run `npm i` to install them, because `npm i` is failing, because the new version of `package-b@1.0.1` hasn't been written to the `npm-shrinkwrap.json` file! As far as I can tell, this is an infinite loop that I can't break out of without regenerating my `npm-shrinkwrap.json` file, which is absolutely not an option for my app.

Any advice?

#### How can the CLI team reproduce the problem?

Create a new package, add a new package (say, `package-b`) as a dependency, then a third package (`package-c`) as `package-b`'s dependency. Shrinkwrap your parent package, then remove `package-c`, and update `package-b`'s `package.json` file to no longer require `package-c`. Note that there is now no way to fix the parent package, which will fail because `package-c` is missing and `npm i` cannot update `package-b` in the shrinkwrap file as a result.

### supporting information:

(Happens on all version of npm3 I've tried. I believe this might be an NPM architectural issue).

**Comment by legodude17** [comment]
Couldn't you just `rm npm-shrinkwrap.json` and then make your changes?

**Comment by i-a-n** [comment]
@legodude17 I can't afford to lose my `npm-shrinkwrap.json` on this project; removing and regenerating it would upgrade hundreds (thousands, maybe?) of packages which isn't an option for our production app at the moment.

**Comment by othiym23** [comment]
Absent other information, it looks like the CLI is trying to do the right thing here. `package-c` is a dependency of `package-b`'s, and so removing it from the shrinkwrap would end up producing an invalid tree.

If you remove the shrinkwrap file, run `npm install`, and then run `npm shrinkwrap` again once you've dealt with the missing package, the only packages that should change will be those related to `package-c`. If a package is installed and matches the semver ranges in the various `package.json` files, the installer doesn't change it (that's what `npm update` is for). So, this should be a safe way to fix things. (I'm assuming there's a newer version of `package-b` that doesn't depend on the missing dependency.)

Give that shot and update the issue to say whether or not that works for you.

**Comment by i-a-n** [comment]
Thanks for the response @othiym23! I think there's a slight misunderstanding (or I'm using shrinkwrap the wrong way). You said I could remove the shrinkwrap file and re-run `npm install`, and it shouldn't touch the current versions of my dependencies' dependencies because:

> If a package is installed and matches the semver ranges in the various package.json files, the installer doesn't change it 

But what if I don't have a `node_modules` directory yet? I'm trying to do `npm install` on a machine, and on new production environments, that don't currently have _any_ packages installed. I'm just pulling in my project somewhere new, running `npm install` for the first time, and it fails as described.

In those cases, if I were to remove my `npm-shrinkwrap.json` file, upgrade the problematic dependency, then re-run `npm install`, it would certainly install hundreds of new dependencies. Does that mean that the only way to fix this would be to track down a backup of the `node_modules` directory and run your prescribed steps on that server?

**Comment by othiym23** [comment]
You _can_ edit the shrinkwrap file by hand, but the results must remain consistent with what's in `package.json`. That means that if you remove a dependency from the shrinkwrap file that's required by the `package.json` of the parent of the removed dependency, npm's going to (rightly) complain. If, on the other hand, you know that there's a new version of the parent dependency that no longer relies on the missing package, you can edit _both_ `package.json` and the shrinkwrap file to point to the new version of the parent dependency, that should fix the problem.

That you have to do this much laborious hacking of files is a pain, but this is one reason (among many) why the unpublish policy for the primary registry has been made so much stricter. There's not a really good way to deal with this particular issue without breaking the guarantees that `package.json` and `npm-shrinkwrap.json` make about the consistency of installs.

Anyway, let us know if that helps, and good luck getting this figured out.

**Comment by i-a-n** [comment]
Thanks @othiym23! I was able to resolve this particular issue but I'm definitely a bit worried that npm shrinkwrap de facto depends on `node_modules` already being installed in order to maintain its state in the event a dependency is no longer reachable. Not to get on a soapbox, but I was under the impression shrinkwrap's whole purpose was to document dependency state for repeatable installs, whether or not a project's `node_modules` has already been installed on your machine.

This might only crop up occasionally in 2016, but what about 2017, 2018, 2020? As more and more modules are removed (not just from npmjs, but from Github and other hosts), and more and more projects live only in git repos (not machines with installed `node_modules`), I think we'll find that npm shrinkwrap becomes more and more useless if it is not able to upgrade itself piecemeal.

Thanks for your time! Feel free to close.
