### ISSUE TITLE
problemas al instalar angular2

### ISSUE THREAD

**Issue by joingood** [npm/npm#14706]
<details><pre>
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\George\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'angular-cli' ]
2 info using npm@3.10.8
3 info using node@v4.4.5
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData angular-cli
8 silly fetchNamedPackageData angular-cli
9 silly mapToRegistry name angular-cli
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'angular-cli',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'angular-cli',
12 silly mapToRegistry   name: 'angular-cli',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/angular-cli
14 verbose request uri https://registry.npmjs.org/angular-cli
15 verbose request no auth needed
16 info attempt registry request try #1 at 12:45:54 PM
17 verbose request id 9071e74cbd871be6
18 http request GET https://registry.npmjs.org/angular-cli
19 http 200 https://registry.npmjs.org/angular-cli
20 verbose headers { server: 'nginx/1.10.1',
20 verbose headers   'content-type': 'application/json',
20 verbose headers   'last-modified': 'Sun, 20 Nov 2016 22:57:37 GMT',
20 verbose headers   etag: 'W/"58322a61-331c0"',
20 verbose headers   'content-encoding': 'gzip',
20 verbose headers   'cache-control': 'max-age=300',
20 verbose headers   'content-length': '19390',
20 verbose headers   'accept-ranges': 'bytes',
20 verbose headers   date: 'Tue, 22 Nov 2016 16:45:55 GMT',
20 verbose headers   via: '1.1 varnish',
20 verbose headers   age: '261',
20 verbose headers   connection: 'keep-alive',
20 verbose headers   'x-served-by': 'cache-dfw1820-DFW',
20 verbose headers   'x-cache': 'HIT',
20 verbose headers   'x-cache-hits': '2',
20 verbose headers   'x-timer': 'S1479833155.287308,VS0,VE0',
20 verbose headers   vary: 'Accept-Encoding' }
21 silly get cb [ 200,
21 silly get   { server: 'nginx/1.10.1',
21 silly get     'content-type': 'application/json',
21 silly get     'last-modified': 'Sun, 20 Nov 2016 22:57:37 GMT',
21 silly get     etag: 'W/"58322a61-331c0"',
21 silly get     'content-encoding': 'gzip',
21 silly get     'cache-control': 'max-age=300',
21 silly get     'content-length': '19390',
21 silly get     'accept-ranges': 'bytes',
21 silly get     date: 'Tue, 22 Nov 2016 16:45:55 GMT',
21 silly get     via: '1.1 varnish',
21 silly get     age: '261',
21 silly get     connection: 'keep-alive',
21 silly get     'x-served-by': 'cache-dfw1820-DFW',
21 silly get     'x-cache': 'HIT',
21 silly get     'x-cache-hits': '2',
21 silly get     'x-timer': 'S1479833155.287308,VS0,VE0',
21 silly get     vary: 'Accept-Encoding' } ]
22 verbose get saving angular-cli to C:\Users\George\AppData\Roaming\npm-cache\registry.npmjs.org\angular-cli\.cache.json
23 verbose correctMkdir C:\Users\George\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
24 silly install normalizeTree
25 silly loadCurrentTree Finishing
26 silly loadIdealTree Starting
27 silly install loadIdealTree
28 silly cloneCurrentTree Starting
29 silly install cloneCurrentTreeToIdealTree
30 silly cloneCurrentTree Finishing
31 silly loadShrinkwrap Starting
32 silly install loadShrinkwrap
33 silly loadShrinkwrap Finishing
34 silly loadAllDepsIntoIdealTree Starting
35 silly install loadAllDepsIntoIdealTree
36 silly resolveWithNewModule angular-cli@1.0.0-beta.20-4 checking installable status
37 silly cache add args [ 'angular-cli', null ]
38 verbose cache add spec angular-cli
39 silly cache add parsed spec Result {
39 silly cache add   raw: 'angular-cli',
39 silly cache add   scope: null,
39 silly cache add   escapedName: 'angular-cli',
39 silly cache add   name: 'angular-cli',
39 silly cache add   rawSpec: '',
39 silly cache add   spec: 'latest',
39 silly cache add   type: 'tag' }
40 silly addNamed angular-cli@latest
41 verbose addNamed "latest" is being treated as a dist-tag for angular-cli
42 info addNameTag [ 'angular-cli', 'latest' ]
43 silly mapToRegistry name angular-cli
44 silly mapToRegistry using default registry
45 silly mapToRegistry registry https://registry.npmjs.org/
46 silly mapToRegistry data Result {
46 silly mapToRegistry   raw: 'angular-cli',
46 silly mapToRegistry   scope: null,
46 silly mapToRegistry   escapedName: 'angular-cli',
46 silly mapToRegistry   name: 'angular-cli',
46 silly mapToRegistry   rawSpec: '',
46 silly mapToRegistry   spec: 'latest',
46 silly mapToRegistry   type: 'tag' }
47 silly mapToRegistry uri https://registry.npmjs.org/angular-cli
48 verbose addNameTag registry:https://registry.npmjs.org/angular-cli not in flight; fetching
49 verbose get https://registry.npmjs.org/angular-cli not expired, no request
50 silly addNameTag next cb for angular-cli with tag latest
51 silly addNamed angular-cli@1.0.0-beta.20-4
52 verbose addNamed "1.0.0-beta.20-4" is a plain semver version for angular-cli
53 silly mapToRegistry name angular-cli
54 silly mapToRegistry using default registry
55 silly mapToRegistry registry https://registry.npmjs.org/
56 silly mapToRegistry data Result {
56 silly mapToRegistry   raw: 'angular-cli',
56 silly mapToRegistry   scope: null,
56 silly mapToRegistry   escapedName: 'angular-cli',
56 silly mapToRegistry   name: 'angular-cli',
56 silly mapToRegistry   rawSpec: '',
56 silly mapToRegistry   spec: 'latest',
56 silly mapToRegistry   type: 'tag' }
57 silly mapToRegistry uri https://registry.npmjs.org/angular-cli
58 verbose addRemoteTarball https://registry.npmjs.org/angular-cli/-/angular-cli-1.0.0-beta.20-4.tgz not in flight; adding
59 verbose addRemoteTarball [ 'https://registry.npmjs.org/angular-cli/-/angular-cli-1.0.0-beta.20-4.tgz',
59 verbose addRemoteTarball   '16f5a0aba5a348e158adf35c2430bd36a1507243' ]
60 info retry fetch attempt 1 at 12:45:56 PM
61 info attempt registry request try #1 at 12:45:56 PM
62 http fetch GET https://registry.npmjs.org/angular-cli/-/angular-cli-1.0.0-beta.20-4.tgz
63 http fetch 200 https://registry.npmjs.org/angular-cli/-/angular-cli-1.0.0-beta.20-4.tgz
64 info retry will retry, error on last attempt: Error: read ECONNRESET
65 silly fetchAndShaCheck shasum 16f5a0aba5a348e158adf35c2430bd36a1507243
66 silly rollbackFailedOptional Starting
67 silly rollbackFailedOptional Finishing
68 silly runTopLevelLifecycles Finishing
69 silly install printInstalled
70 verbose stack Error: shasum check failed for C:\Users\George\AppData\Local\Temp\npm-9116-1f4fb01b\registry.npmjs.org\angular-cli\-\angular-cli-1.0.0-beta.20-4.tgz
70 verbose stack Expected: 16f5a0aba5a348e158adf35c2430bd36a1507243
70 verbose stack Actual:   822faa4333449c34fd8b35820b37613c0a492607
70 verbose stack From:     https://registry.npmjs.org/angular-cli/-/angular-cli-1.0.0-beta.20-4.tgz
70 verbose stack     at C:\Users\George\AppData\Roaming\npm\node_modules\npm\node_modules\sha\index.js:25:8
70 verbose stack     at ReadStream.<anonymous> (C:\Users\George\AppData\Roaming\npm\node_modules\npm\node_modules\sha\index.js:72:7)
70 verbose stack     at emitNone (events.js:72:20)
70 verbose stack     at ReadStream.emit (events.js:166:7)
70 verbose stack     at endReadableNT (_stream_readable.js:913:12)
70 verbose stack     at nextTickCallbackWith2Args (node.js:442:9)
70 verbose stack     at process._tickCallback (node.js:356:17)
71 verbose cwd C:\Users\George
72 error Windows_NT 10.0.14393
73 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\George\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "angular-cli"
74 error node v4.4.5
75 error npm  v3.10.8
76 error shasum check failed for C:\Users\George\AppData\Local\Temp\npm-9116-1f4fb01b\registry.npmjs.org\angular-cli\-\angular-cli-1.0.0-beta.20-4.tgz
76 error Expected: 16f5a0aba5a348e158adf35c2430bd36a1507243
76 error Actual:   822faa4333449c34fd8b35820b37613c0a492607
76 error From:     https://registry.npmjs.org/angular-cli/-/angular-cli-1.0.0-beta.20-4.tgz
77 error If you need help, you may report this error at:
77 error     <https://github.com/npm/npm/issues>
78 verbose exit [ 1, true ]
</pre></details>

**Comment by legodude17** [comment]
Try running `npm cache clean angular-cli`.

**Comment by zkat** [comment]
Closing as duplicate of https://github.com/npm/npm/issues/14626. See https://github.com/npm/npm/issues/14626#issuecomment-264371634 for some helpful steps.

**Comment by joingood** [comment]
Muchas Gracias! Ya esta resuelto


2016-12-02 0:44 GMT-04:00 Kat Marchán <notifications@github.com>:

**Comment by jorgegonzalezfani** [comment]
Hola, yo tengo probelmas con nodejs, para ver si me puedes ayudar, cuando
yo uso el metodo "async function" y la consola, me da error y tengo node a
version 6.11.0[image: Imagen integrada 1]

2016-12-13 10:38 GMT-04:00 Jorge González <jorgegonzaleztx9@gmail.com>:
