### ISSUE TITLE
offline npm install and npm install -g grunt-cli 

### ISSUE THREAD

**Issue by ashish6793** [npm/npm#14701]
-offline npm install and npm install -g grunt-cli 

I have install node js in my system and I have run these cmds  "npm install" and "npm install -g grunt-cli"
in my workspace and grunt and grunt package working fine, So now i want to run  "npm install" and "npm install -g grunt-cli" cmds in offline system with the use of node_module and local cache of npm from first system. Please help.My systems are running on windows.

**Comment by legodude17** [comment]
You can use `--cache-min=9999999999`.
