### ISSUE TITLE
outdated prints out a version of npm 4.0.2 even though I have 4.0.3 installed

### ISSUE THREAD

**Issue by capaj** [npm/npm#14707]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [X] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
```
capaj@capaj-Inspiron-7548:~/git_projects/be/docker$ npm outdated -g --depth=0
Package  Current  Wanted  Latest  Location
npm        4.0.3   4.0.3   4.0.2
yarn      0.16.1  0.16.1  0.17.8
```
It shouldn't show it npm as outdated and it should not list 4.0.2 as latest version.

#### How can the CLI team reproduce the problem?
Try running `npm outdated -g --depth=0` command with the versions I have installed maybe?

### supporting information:

 - `npm -v` prints: 4.0.3
 - `node -v` prints: 7.1.0
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?: Ubuntu 16.04
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [X] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@capaj `npm@4.0.2` is indeed what is tagged as `latest`. This is completely intentional.

```
$ npm info npm dist-tags
{ latest: '4.0.2',
  next: '4.0.3',
  'latest-2': '2.15.11',
  'v3.x-latest': '3.10.9',
  '3.x-latest': '3.10.9',
  '3.x-next': '3.10.10',
  'v3.x-next': '3.10.10',
  'next-2': '2.15.11',
  'latest-1': '1.4.29',
  lts: '2.15.11',
  'latest-3': '3.10.10',
  'next-3': '3.10.10' }
```

**Comment by AlexTes** [comment]
This is quite confusing to me @KenanY. If I `npm install npm`, why would I get the `next` instead of the `latest`. Isn't the `next` by definition the next version so not the default installed version. Which I think anyone would reasonably assume is the `latest`. It's no big deal of course. But confusing - I think to most users - nonetheless.

**Comment by KenanY** [comment]
@AlexTes 

> If I `npm install npm`, why would I get the `next` instead of the `latest`. 

You should get `latest` if you do that command, otherwise it sounds like a bug.

**Comment by AlexTes** [comment]
```sh
$ npm install npm@3 -g
...
└── npm@3.10.10
...

$ npm outdated -g
Package  Current   Wanted  Latest  Location
npm      3.10.10  3.10.10   4.0.3

$ npm install npm -g
...
└─┬ npm@4.0.3
...
```

'-_- npm seems to function perfectly. I don't know what happened. Just that I never installed anything `@latest`. Maybe it's some weird nvm bug. In any case, this can stay closed. Thanks for the follow-up!
