### ISSUE TITLE
Refusing to install conspectio as a dependency of itself

### ISSUE THREAD

**Issue by greetojoseph** [npm/npm#14703]
```
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/Cellar/node/7.0.0/bin/node" "/usr/local/bin/npm" "install" "--save" "conspectio"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code ENOSELF

npm ERR! Refusing to install conspectio as a dependency of itself
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     conspectio-master/npm-debug.log
```

<details><pre>
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/7.0.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   'conspectio' ]
2 info using npm@3.10.8
3 info using node@v7.0.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData conspectio
8 silly fetchNamedPackageData conspectio
9 silly mapToRegistry name conspectio
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'conspectio',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'conspectio',
12 silly mapToRegistry   name: 'conspectio',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/conspectio
14 verbose request uri https://registry.npmjs.org/conspectio
15 verbose request no auth needed
16 info attempt registry request try #1 at 3:49:41 PM
17 verbose request id 87bf216d4dd31778
18 verbose etag W/"58119502-6f41"
19 verbose lastModified Thu, 27 Oct 2016 05:47:46 GMT
20 http request GET https://registry.npmjs.org/conspectio
21 http 304 https://registry.npmjs.org/conspectio
22 verbose headers { date: 'Tue, 22 Nov 2016 10:19:41 GMT',
22 verbose headers   via: '1.1 varnish',
22 verbose headers   'cache-control': 'max-age=300',
22 verbose headers   etag: 'W/"58119502-6f41"',
22 verbose headers   age: '0',
22 verbose headers   connection: 'close',
22 verbose headers   'x-served-by': 'cache-sin6924-SIN',
22 verbose headers   'x-cache': 'MISS',
22 verbose headers   'x-cache-hits': '0',
22 verbose headers   'x-timer': 'S1479809981.913262,VS0,VE98',
22 verbose headers   vary: 'Accept-Encoding' }
23 silly get cb [ 304,
23 silly get   { date: 'Tue, 22 Nov 2016 10:19:41 GMT',
23 silly get     via: '1.1 varnish',
23 silly get     'cache-control': 'max-age=300',
23 silly get     etag: 'W/"58119502-6f41"',
23 silly get     age: '0',
23 silly get     connection: 'close',
23 silly get     'x-served-by': 'cache-sin6924-SIN',
23 silly get     'x-cache': 'MISS',
23 silly get     'x-cache-hits': '0',
23 silly get     'x-timer': 'S1479809981.913262,VS0,VE98',
23 silly get     vary: 'Accept-Encoding' } ]
24 verbose etag https://registry.npmjs.org/conspectio from cache
25 verbose get saving conspectio to /Users/smartrplanet/.npm/registry.npmjs.org/conspectio/.cache.json
26 verbose correctMkdir /Users/smartrplanet/.npm correctMkdir not in flight; initializing
27 silly install normalizeTree
28 silly loadCurrentTree Finishing
29 silly loadIdealTree Starting
30 silly install loadIdealTree
31 silly cloneCurrentTree Starting
32 silly install cloneCurrentTreeToIdealTree
33 silly cloneCurrentTree Finishing
34 silly loadShrinkwrap Starting
35 silly install loadShrinkwrap
36 silly loadShrinkwrap Finishing
37 silly loadAllDepsIntoIdealTree Starting
38 silly install loadAllDepsIntoIdealTree
39 silly rollbackFailedOptional Starting
40 silly rollbackFailedOptional Finishing
41 silly runTopLevelLifecycles Finishing
42 silly install printInstalled
43 verbose stack Error: Refusing to install conspectio as a dependency of itself
43 verbose stack     at checkSelf (/usr/local/lib/node_modules/npm/lib/install/validate-args.js:53:14)
43 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
43 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
43 verbose stack     at chain (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
43 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/validate-args.js:16:5
43 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
43 verbose stack     at Array.forEach (native)
43 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
43 verbose stack     at Array.forEach (native)
43 verbose stack     at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
44 verbose cwd /Users/smartrplanet/Desktop/conspectio-master
45 error Darwin 15.0.0
46 error argv "/usr/local/Cellar/node/7.0.0/bin/node" "/usr/local/bin/npm" "install" "--save" "conspectio"
47 error node v7.0.0
48 error npm  v3.10.8
49 error code ENOSELF
50 error Refusing to install conspectio as a dependency of itself
51 error If you need help, you may report this error at:
51 error     <https://github.com/npm/npm/issues>
52 verbose exit [ 1, true ]
 </pre></details>

**Comment by KenanY** [comment]
@greetojoseph Are you trying to install `conspectio` from within its own source code directory?

**Comment by greetojoseph** [comment]
yes. this error coming at that time

**Comment by KenanY** [comment]
@greetojoseph It is not possible to install a module as a dependency of itself, which is what you are trying to do when you run `npm install conspectio` from within `conspectio`'s own directory. You should be running that command from within your project's directory instead.

**Comment by KenanY** [comment]
Closing due to no further activity.
