### ISSUE TITLE
Downloaded package does not include anything but readme and package.json. Not even index.js.

### ISSUE THREAD

**Issue by austinhuang0131** [npm/npm#14718]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Downloaded package does not include anything but readme and package.json. Not even index.js. [Issue at the package repo...](https://github.com/mdibaiee/node-telegram-api/issues/30)

#### How can the CLI team reproduce the problem?
```
npm install telegram-api
```
I am very sorry, but `npm-debug.log` does not exist. It is shown as successful.

### supporting information:

 - `npm -v` prints: 3.10.9
 - `node -v` prints: v7.1.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: OSX
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [x] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@austinhuang0131 Is this still an issue for you after https://github.com/mdibaiee/node-telegram-api/issues/30#issuecomment-262550985?

**Comment by austinhuang0131** [comment]
Solved
