### ISSUE TITLE
npm --prefix doesn't work with --save on windows

### ISSUE THREAD

**Issue by Plamen5kov** [npm/npm#14715]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
When doing: 
```
npm install <module_name> --prefix path\to\package.json --save
``` 
the package installs, but it's NOT saved as a dependency in the `package.json`.
This happens only on windows machines (on mac and on linux it runs fine). I did it with node versions: 6.9.1, 6.6.0. 
Same things happens on `npm uninstall ...` command (plugin is removed from node modules but not from `package.json`). I guess the `--prefix` option is not applied to the `--save` option or something.
#### How can the CLI team reproduce the problem?

On windows only!

* mkdir test
* cd test && npm init && cd ..
* npm install lodash --prefix ./test --save
* ls -la ./test/node_modules | grep lodash (should be there)
* cat ./test/package.json (should not have dependencies even though there is --save option passed)

### supporting information:

 - `npm -v` prints: v6.9.1
 - `node -v` prints: 3.10.8
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: windows
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).
No contained or network issues.

**Comment by othiym23** [comment]
How were you running that test case? Git bash or the Ubuntu subsystem? Does the same behavior persist when the commands are run from `cmd.exe` or Powershell?

**Comment by rosen-vladimirov** [comment]
Hey @othiym23 , the issue is reproducible with 
 - git bash
 - cmd.exe
 - powershell

I've not tried the Ubuntu subsystem on Windows.

You can check my steps to reproduce in [this gist](https://gist.github.com/rosen-vladimirov/d43473a79b079640f04ac92d420fd917) - it's executed in the default Command Prompt (note I've commands like `cat` and `ls -l` as I've git bash integration in cmd).

**Comment by Tewfiq60** [comment]
tap' is not recognized as an internal or external command,
perable program or batch file.
pm ERR! Test failed.  See above for more details.

:\Program Files\nodejs\node_modules\npm\node_modules\init-package-json>npm star

pm ERR! Windows_NT 6.3.9600
pm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
ode_modules\\npm\\bin\\npm-cli.js" "start"
pm ERR! node v6.9.1
pm ERR! npm  v3.10.8

pm ERR! missing script: start
pm ERR!
pm ERR! If you need help, you may report this error at:
pm ERR!     <https://github.com/npm/npm/issues>

pm ERR! Please include the following file with any support request:
pm ERR!     C:\Program Files\nodejs\node_modules\npm\node_modules\init-package-
son\npm-debug.log

:\Program Files\nodejs\node_modules\npm\node_modules\init-package-json> <https:
/github.com/npm/npm/issues>
he syntax of the command is incorrect.

:\Program Files\nodejs\node_modules\npm\node_modules\init-package-json>^V
please help i have try all i can please help

**Comment by KenanY** [comment]
@Tewfiq60 Your issue seems unrelated to that of the OP. Can you please open a new issue instead? Thanks!

**Comment by legodude17** [comment]
Does `npm` update a `package.json` in you cwd?

**Comment by rosen-vladimirov** [comment]
@legodude17 , nope, none of the package.json is updated. The package is installed on correct place (I see it in node_modules of the dir set as `--prefix` however it just disregards any other `--` flags.

**Comment by legodude17** [comment]
What about `npm install --save <module> --prefix=./test`? Try different orderings. 😄

**Comment by Plamen5kov** [comment]
@legodude17 I tried doing first `--prefix` and then `--save`, but the result is the same. When `--prefix` is used the other flags are ignored.

**Comment by legodude17** [comment]
Does this issue happen on other OS's?

**Comment by Plamen5kov** [comment]
I manage to reproduce it only on windows, as I've described in the issue.

**Comment by jo32** [comment]
have the same problem on windows.

**Comment by rneha725** [comment]
I tried reproducing it. It works for me. Information:
Ubuntu 16.04
node v4.2.6
npm v3.5.2
Yeah I know it is old!!
