### ISSUE TITLE
Refusing to install node-forge as a dependency of itself

### ISSUE THREAD

**Issue by lbcsultan** [npm/npm#14717]
I have used node-forge successfully for more than 1 years.
When I try to install node-forge in another computer (Windows 7, 32-bit), I got the following error message. How can I install node-forge?

C:\node\forge\forge-master>npm install node-forge
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Users\608\AppData\Ro
aming\npm\node_modules\npm\bin\npm-cli.js" "install" "node-forge"
npm ERR! node v6.3.0
npm ERR! npm v3.9.0
npm ERR! code ENOSELF
npm ERR! Refusing to install node-forge as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!
npm ERR! Please include the following file with any support request:
npm ERR! C:\node\forge\forge-master\npm-debug.log
C:\node\forge\forge-master>

**Comment by KenanY** [comment]
@lbcsultan Run `npm install node-forge` from within your project directory. From the log, I'm guessing that you are trying to run that command from within `node-forge`'s source code directory, which is not a valid thing to do (since that implies that `node-forge` is a dependency of itself).
