### ISSUE TITLE
npm unpublish --force poserver

### ISSUE THREAD

**Issue by tjdaley** [npm/npm#14723]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [X ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I am trying to unpublish a public module, poserver. I am running npm v4.0.2. I was just able to publish and unpublish @thomasjdaley/test without a problem. But when I try to unpublish the PUBLIC version of poserver, i get the attached error.

#### How can the CLI team reproduce the problem?

I use the following command

`npm unpublish --force poserver`

https://gist.github.com/tjdaley/820f89a361109f5d72685f2456f3fb7c

### supporting information:

 - `npm -v` prints: 4.0.2
 - `node -v` prints: 4.5.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: PS X/macOS
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by watilde** [comment]
According to your npm-debug.log on gist, you're using old version of the npm. Could you please check your npm version again, and try the latest version if it's old?
> 46 error npm  v2.15.9

Here is a troubleshooting page that may helps you:
https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm

**Comment by KenanY** [comment]
You probably just need to email `support@npmjs.com` for unpublishes.

**Comment by tjdaley** [comment]
Thank you for your responses. I apologize that the npm-debug.log I gisted must have preceded my last attempt. I updated npm, cleared the npm cache, and posted a revised gist (wutg --verbose) here:

https://gist.github.com/tjdaley/820f89a361109f5d72685f2456f3fb7c

**Comment by zkat** [comment]
@tjdaley npm has a fairly strict unpublish policy now. Please see http://blog.npmjs.org/post/141905368000/changes-to-npms-unpublish-policy

Like @KenanY said, you'll have to contact support@npmjs.com to request an unpublish, and it may not be granted, depending on various factors and the situation. This repo is for the npm CLI itself, so please proceed over there. Cheers! :)
