### ISSUE TITLE
i don't know what is this problem please help me

### ISSUE THREAD

**Issue by marcusbear** [npm/npm#14721]
![1](https://cloud.githubusercontent.com/assets/22745949/20573450/cc3e84fa-b1ea-11e6-8299-20e0375c4495.png)

**Comment by KenanY** [comment]
Looks like you are trying to run `npm start`, but you do not have a `"start"` script defined in your `package.json`. I suggest you read through <https://docs.npmjs.com/misc/scripts>, which goes into how `npm` scripts work and how to write your own.
