### ISSUE TITLE
npm install not working

### ISSUE THREAD

**Issue by Poobalan4** [npm/npm#14725]
Hi, I'm trying to install express and mssql on my windows 7 machine using npm. But it always fails with the errorlog. PFA errorlog. I have tried using npm through VS2013, still same. Please check.

#### I'm opening this issue because:

  - [ ] Other (_see below for feature requests_):
- [x] npm is not installing any modules
[npm-debug.zip](https://github.com/npm/npm/files/611063/npm-debug.zip)

  
#### What's going wrong?
npm installation not working. Ex: npm install express

### supporting information:

 - `npm -v` prints: 
3.10.8
 - `node -v` prints:
v6.9.1
 - `npm config get registry` prints: 
https://registry.npmjs.org/
{"db_name":"registry","doc_count":433738,"doc_del_count":353,"update_seq":3586263,"purge_seq":0,"compact_running":false,"disk_size":2222948481,"data_size":1784418850,"instance_start_time":"1479489265770149","disk_format_version":6,"committed_update_seq":3586263}

 - Windows, OS X/macOS, or Linux?: Windows 7 SP1
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by hrishi85** [comment]
I am also having the same problem on macOS Sierra

**Comment by hrishi85** [comment]
Worked fine after reinstall

**Comment by legodude17** [comment]
@Poobalan4 do you still have this issue after reinstall?

**Comment by libertyswift** [comment]
the same problem on linux

**Comment by Poobalan4** [comment]
I'm using it in a corporate network. After setting up the proxy, it is working fine.
