### ISSUE TITLE
'ionic serve' crashing

### ISSUE THREAD

**Issue by rajeshemailto** [npm/npm#14724]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
'ionic serve' crashing

#### How can the CLI team reproduce the problem?

> ionic-hello-world@ ionic:serve /Development/mobi-dev/ionic/test-app
> ionic-app-scripts serve

>[12:41:49]  ionic-app-scripts 0.0.46 
>[12:41:50]  watch started ... 
>[12:41:50]  build dev started ... 
>[12:41:50]  clean started ... 
>[12:41:50]  clean finished in 1 ms 
>[12:41:50]  copy started ... 
>[12:41:50]  transpile started ... 
>events.js:141
>      throw er; // Unhandled 'error' event
>      ^
>
>Error: listen EADDRINUSE 0.0.0.0:53703
>    at Object.exports._errnoException (util.js:870:11)
>    at exports._exceptionWithHostPort (util.js:893:20)
>    at Server._listen2 (net.js:1237:14)
>    at listen (net.js:1273:10)
>    at net.js:1382:9
>   at nextTickCallbackWith3Args (node.js:452:9)
>    at process._tickCallback (node.js:358:17)
>    at Function.Module.runMain (module.js:444:11)
>    at startup (node.js:136:18)
>    at node.js:966:3

>npm ERR! Darwin 16.1.0
>npm ERR! argv "/Users/rajeshkumar/.nvm/versions/node/v4.2.6/bin/node" >"/Users/rajeshkumar/.nvm/versions/node/v4.2.6/bin/npm" "run" "ionic:serve" "--"
>npm ERR! node v4.2.6
>npm ERR! npm  v2.14.12
>npm ERR! code ELIFECYCLE
>npm ERR! ionic-hello-world@ ionic:serve: `ionic-app-scripts serve`
>npm ERR! Exit status 1
>npm ERR! 
>npm ERR! Failed at the ionic-hello-world@ ionic:serve script 'ionic-app-scripts serve'.
>npm ERR! This is most likely a problem with the ionic-hello-world package,
>npm ERR! not with npm itself.
>npm ERR! Tell the author that this fails on your system:
>npm ERR!     ionic-app-scripts serve
>npm ERR! You can get their info via:
>npm ERR!     npm owner ls ionic-hello-world
>npm ERR! There is likely additional logging output above.

>npm ERR! Please include the following file with any support request:
>npm ERR!     /Development/mobi-dev/ionic/test-app/npm-debug.log
>There was an error serving your Ionic application: There was an error with the spawned command: serve

### supporting information:

 - `npm -v` prints:2.14.12
 - `node -v` prints: v4.2.6
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: MacOS 10.12.1
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [x ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by watilde** [comment]
You seem to be using old version of the npm
> npm ERR! npm v2.14.12

Could you please try the latest version? Here is a troubleshooting page that may helps you https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm

**Comment by KenanY** [comment]
@rajeshemailto The error indicates that you are trying to run a server on a port which is already occupied. This is not at all an issue with `npm`, you just need to ensure that you either close whatever is running on that port, or start the new server on a different, unoccupied port.
