### ISSUE TITLE
Question - NPM cache and github dependency links

### ISSUE THREAD

**Issue by ORESoftware** [npm/npm#14728]
#### I'm opening this issue because:

  - [x] npm is doing something I don't understand.

#### What's going wrong?

I am not sure about the NPM behavior when using a github install link like the following:

```
"devDependencies": {
   "suman": "github:oresoftware/suman"
}

```
Will it always install the latest code from the Github repo, or will it cache the result? I am assuming it will cache the result. But I want to grab the latest from the Github repo, but this doesn't work:

```
"devDependencies": {
   "suman": "github:oresoftware/suman@latest"
}
```

What is the correct way to always grab the latest commit sha / spec from the Github repo?

**Comment by bboysathish** [comment]
@ORESoftware You can either do npm cache clean and try installing it once again or you can use `--force` flag to fetch the repo eventhough it is available in your local 

`npm install  --force`

**Comment by ORESoftware** [comment]
ok I will try that thanks

**Comment by ORESoftware** [comment]
I just wish there were a way to specify "--force" for just one dependency, I guess I could just do it in two steps

```
npm install --force github:oresoftware/suman --save
npm install

```

**Comment by zkat** [comment]
See https://github.com/npm/npm/issues/4191 for the current state of git support.
