### ISSUE TITLE
npm install  go wrong

### ISSUE THREAD

**Issue by chengqilong** [npm/npm#14720]
#### I'm opening this issue because:

```
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "generator-react-webpack"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9

npm ERR! shasum check failed for C:\Users\ADMINI~1\AppData\Local\Temp\npm-9356-7
d74e411\registry.npmjs.org\core-js\-\core-js-1.2.7.tgz
npm ERR! Expected: 652294c14651db28fa93bd2d5ff2983a4f08c636
npm ERR! Actual:   c45474b40e6a7474634ec6f2b0315feaf15c61f2
npm ERR! From:     https://registry.npmjs.org/core-js/-/core-js-1.2.7.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

**Comment by hrishi85** [comment]
I am facing the same problem on macOS Sierra

**Comment by KenanY** [comment]
Does running `npm cache clean` help at all?

**Comment by hrishi85** [comment]
Solved after reinstall

**Comment by legodude17** [comment]
Can this be closed then @KenanY?

**Comment by KenanY** [comment]
Actually, let's wait on the OP, @chengqilong :)

**Comment by pandanrain** [comment]
I have facing the same problem on my mac sierra .
i have tried reinstall npm and npm clean cache but both not work;
actually i upgrade my npm to version 4.0.2  and node to version v7.2.0
and **close my proxy** , it works well.

**Comment by legodude17** [comment]
Ok. Do you still have this issue @chengqilong ?

**Comment by chenyijie-bit** [comment]
could you help me?thanck you
![02](https://cloud.githubusercontent.com/assets/23470635/26814744/6c6bd000-4aba-11e7-8d43-290f0bd29f5f.png)

**Comment by legodude17** [comment]
Try updating `npm` to the latest version
