### ISSUE TITLE
Unable to install PM2 or ForEver

### ISSUE THREAD

**Issue by anand-tummapudi** [npm/npm#14729]
Hi Team,

I am trying to install Pm2 or FOREVER using NPM and it is failing. Getting the following Error.

npm ERR! registry error parsing json
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "pm2" "-g"
npm ERR! node v5.11.0
npm ERR! npm  v3.8.6

npm ERR! Unexpected token <
npm ERR! <!DOCTYPE html>
npm ERR! <html>
npm ERR! <head>
npm ERR!  <script type='text/javascript' src='http://pl129640.puhtml.com/63/ca/a
e/63caae5daa217e285dca723da4dd76f4.js' async></script>
npm ERR! <title></title>

Kindly look into the issue and help us to resolve the same.

Thanks,
Anand

**Comment by bboysathish** [comment]
Hi Seems your package.json is not a proper json object.. please lint you json to check is it proper or not @anand-tummapudi

**Comment by anand-tummapudi** [comment]
Hi Sathish, I have lint my packages json and it is valid json only.

**Comment by anand-tummapudi** [comment]
npm ERR! registry error parsing json
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "pm2"
npm ERR! node v5.11.0
npm ERR! npm  v3.8.6

npm ERR! Unexpected token <
npm ERR! <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3
.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
npm ERR! <html xmlns="http://www.w3.org/1999/xhtml">
npm ERR! <head>
npm ERR! <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"
/>
npm ERR! <title>404 - File or directory not found.</title>
npm ERR! <style type="text/css">
npm ERR! 
npm ERR! </style>
npm ERR! </head>
npm ERR! <body>
npm ERR! <div id="header"><h1>Server Error</h1></div>
npm ERR! <div id="content">
npm ERR!  <div class="content-container"><fieldset>
npm ERR!   <h2>404 - File or directory not found.</h2>
npm ERR!   <h3>The resource you are looking for might have been removed, had its
 name changed, or is temporarily unavailable.</h3>
npm ERR!  </fieldset></div>
npm ERR! </div>
npm ERR! </body>
npm ERR! </html>
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by KenanY** [comment]
@anand-tummapudi Are you behind a proxy by any chance?

**Comment by anand-tummapudi** [comment]
No am not behind any proxy.

**Comment by KenanY** [comment]
@anand-tummapudi What is the result of `npm config get registry`?

**Comment by anand-tummapudi** [comment]
Hi Kenan, Thanks a lot! 
With **npm config get registry** I am able to install and it worked.
