### ISSUE TITLE
npm mongoose installation in Windows machine local repository not working

### ISSUE THREAD

**Issue by kelumKP** [npm/npm#15037]
I'm trying to install `mongoose` to my local repository (`C:\Users\kelumputha\Desktop\userstory`) using following command in windows powershell
 
`npm install mongoose --save`

Also I'm using mongo db in Database-as-a-Service by mLab, So I have a `config.js` file as

```
module.exports = {
    "database": "mongodb://kelum:****@ds111188.mlab.com:11188/userstorydb",
    "port": process.env.PORT || 3000,
    "secretKey": "YourSecretKey"
}
```
but here I'm ending with `No Repository Field` Warning

![image](https://cloud.githubusercontent.com/assets/7415362/20641783/7c6cc260-b425-11e6-87e1-2b07b66c0988.png)

**Comment by KenanY** [comment]
@kelumKP If you want to remove that warning, simply define a [`"repository"`](https://docs.npmjs.com/files/package.json#repository) field in your `package.json`. Or, just ignore it. Closing since this isn't a bug.
