### ISSUE TITLE
Shared folders in VMware: npm install fails with ENOENT (rename)

### ISSUE THREAD

**Issue by mulles3008** [npm/npm#15034]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

`npm install` quits with `ENOENT: no such file or directory, rename ...`:

```
npm ERR! Linux 4.4.0-47-generic
npm ERR! argv "/home/erik/.nvm/versions/node/v6.9.1/bin/node" "/home/erik/.nvm/versions/node/v6.9.1/bin/npm" "install"
npm ERR! node v6.9.1
npm ERR! npm  v4.0.3
npm ERR! path /mnt/hgfs/git/whosthere_api/node_modules/.dashdash.DELETE/node_modules/assert-plus
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/mnt/hgfs/git/whosthere_api/node_modules/.dashdash.DELETE/node_modules/assert-plus' -> '/mnt/hgfs/git/whosthere_api/node_modules/dashdash/node_modules/assert-plus'
npm ERR! enoent ENOENT: no such file or directory, rename '/mnt/hgfs/git/whosthere_api/node_modules/.dashdash.DELETE/node_modules/assert-plus' -> '/mnt/hgfs/git/whosthere_api/node_modules/dashdash/node_modules/assert-plus'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/hgfs/git/whosthere_api/npm-debug.log
```
A second run of `npm install` leads then to an `ENOTEMPTY ` error:
```
npm ERR! ENOTEMPTY: directory not empty, rename '/mnt/hgfs/git/whosthere_api/node_modules/dashdash' -> '/mnt/hgfs/git/whosthere_api/node_modules/.dashdash.DELETE'
```

#### How can the CLI team reproduce the problem?

I have installed my local git repo in a folder shared between macOS Sierra (host, used for coding) and Ubuntu 16.04.1 LTS (guest, used for deploying/testing). Unfortunately I can't get `npm` to build my projects on the guest. The virtualization software is use is VMware Fusion 8.5.2 (latest VMware Tools installed, version 10.1.0 build-4449150, older versions don't work either). I'm quite helpless... 

Here is my [npm-debug.log](https://gist.github.com/mulles3008/02375834fc7b5503445b4d44d0c4864c) file.

### supporting information:

 - `npm -v` prints: 4.0.3
 - `node -v` prints: v6.9.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS (host), Ubuntu 16.04.1 (guest, where the error happens)
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

Any help would be appreciated

**Comment by iarna** [comment]
Notes for future: This is `finalize` replacing a module in the middle of a tree and failing for some reason to move the children. The fact that the first ENOENT error is repeated implies to me that some callback is being called more than once. My theory would be that the first succeeded and the subsequent ones produced the errors above.

**Comment by drsirmrpresidentfathercharles** [comment]
I can reproduce this issue using VMware Workstation 12 Player with an Ubuntu 16.04 machine, latest VMware tools, and shared folders. Note that this does not occur if the directory is copied from the share (/mnt/hgfs/whatever) and `npm install`ed in the copy.

**Comment by svdb0** [comment]
For future readers who end up here after encountering this bug: this is likely this bug in vmhgfs-fuse: https://github.com/vmware/open-vm-tools/issues/90
