### ISSUE TITLE
Feature Request: Audit tool that uses bundling/compilation similar to Maven

### ISSUE THREAD

**Issue by tatemz** [npm/npm#15031]
#### I'm opening this issue because:

- [ ] npm is crashing.
- [ ] npm is producing an incorrect install.
- [ ] npm is doing something I don't understand.
- [X] Other (_see below for feature requests_):

#### What's the feature?
And audit feature that performs bundling/compilation of dependencies similar to Maven. Perhaps this would allow for the creation of a single `bundle.js` or a `bundle.tar.gz` (which would happen on the registry side as it currently does).

#### What problem is the feature intended to solve?
There are packages in the registry that contain arbitrary and unused dependencies. In other words, there are packages that are being installed that do not get imported inside of the package.

#### Is the absence of this feature blocking you or your team? If so, how?
No.

#### Is this feature similar to an existing feature in another tool?
Maven bundling into jar/war

#### Is this a feature you're prepared to implement, with support from the npm CLI team?
Possibly. Perhaps this feature could first be implemented as an audit dev tool.

**Comment by KenanY** [comment]
> which would happen on the registry side as it currently does

FWIW, registry does not create tarballs, `npm pack`/`npm publish` does (I believe).

Seems like [a lot of tools exist](https://github.com/search?l=JavaScript&q=unused+dependencies&type=Repositories&utf8=%E2%9C%93) for this already.

**Comment by tatemz** [comment]
Thanks for the information as well as the helpful link.

I assumed there were tools out there, but is it worth having a built-in convention that forces packages to be optimal?

In other words, it would probably be a painstakingly arduous task to reach out to each developer of aforementioned culprit packages and request they use a build tool such as [`npm-check`](https://github.com/dylang/npm-check) while the opportunity exists to bake such convention into npm itself.

Any thoughts?
