### ISSUE TITLE
shrinkwrap is throwing an error

### ISSUE THREAD

**Issue by ravisangar** [npm/npm#15038]
#### I'm opening this issue because:

shrinkwrap is throwing an error.

#### What's going wrong?

shrinkwrap is throwing this error 

25 error Problems were encountered
25 error Please correct and try again.
25 error peer invalid: @angular/compiler-cli@2.2.1, required by @ngtools/webpack@1.1.6
25 error peer invalid: @angular/core@2.2.1, required by @ngtools/webpack@1.1.6
26 error If you need help, you may report this error at:
26 error     <https://github.com/npm/npm/issues>

#### How can the CLI team reproduce the problem?

This issue can be re-produced using the following package.json

{
  "name": "product-mgr",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "start": "ng serve",
    "lint": "tslint \"src/**/*.ts\"",
    "test": "ng test",
    "pree2e": "webdriver-manager update",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "2.0.0",
    "@angular/compiler": "2.0.0",
    "@angular/core": "2.0.0",
    "@angular/forms": "2.0.0",
    "@angular/http": "2.0.0",
    "@angular/platform-browser": "2.0.0",
    "@angular/platform-browser-dynamic": "2.0.0",
    "@angular/router": "3.0.0",
    "core-js": "^2.4.1",
    "rxjs": "5.0.0-beta.12",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.6.23"
  },
  "devDependencies": {
    "@types/jasmine": "^2.2.30",
    "angular-cli": "1.0.0-beta.15",
    "codelyzer": "~0.0.26",
    "jasmine-core": "2.4.1",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "4.0.5",
    "ts-node": "1.2.1",
    "tslint": "3.13.0",
    "typescript": "2.0.2"
  }
}

**Comment by watilde** [comment]
Hello. The error message said you need to install some dependencies which are required by your dependencies. Could you try the following command to install them?

```
npm i @angular/compiler-cli@2.2.1 @angular/core@2.2.1
```

**Comment by ravisangar** [comment]
running this command to install generates this error:

npm i @angular/compiler-cli@2.2.1 @angular/core@2.2.1


├── UNMET PEER DEPENDENCY @angular/compiler@2.1.2
├── @angular/compiler-cli@2.2.1 
├── UNMET PEER DEPENDENCY @angular/core@2.2.1 invalid
└─┬ angular-cli@1.0.0-beta.19-3
  ├── @angular/compiler-cli@2.1.2 
  └── UNMET PEER DEPENDENCY @angular/core@2.1.2

**Comment by ravisangar** [comment]
shrinkwrap is supposed to lock listed dependencies from package.json. It doesn't make sense for it to complain about dependencies.
