### ISSUE TITLE
npm install output goes to stderr and normally that is OK but

### ISSUE THREAD

**Issue by ORESoftware** [npm/npm#15035]
#### I'm opening this issue because:
  - [x] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### How can the CLI team reproduce the problem?

**1. build a docker container with a Dockerfile that runs an some form npm install**

for example, in the Dockerfile we might have

`ENTRYPOINT ["/bin/bash", "/home/newuser/script.sh"]`
and that script.sh file will run the npm install

`2. now, run the docker container`

the output from running the container will be line after line after line of npm install output which will just fill up log files like crazy.

_(Perhaps there is a command line flag to have less verbose install information? I just thought of that)_

Anyway, normally NPM will the clear the line (clear stdout) and just print over the same line in the terminal, but this probably doesn't work for log files. My guess is that Docker does some magic where it tails a log file and then streams that back to the terminal and that's why NPM cannot do it's formatting magic at the terminal. 

In any case, what is the best remedy for reducing the amount of data that NPM spits out during an install when it comes to Docker or in general?

**Comment by legodude17** [comment]
You can use the flags `--loglevel=warn` and `--progress=false` to disable the progress bar and only warn and error.

**Comment by ORESoftware** [comment]
thanks! Will use those

**Comment by zkat** [comment]
This looks answered. Closing.
