### ISSUE TITLE
Make new clean install after package.json is edited

### ISSUE THREAD

**Issue by yopbeast** [npm/npm#15032]
Sorry for the trouble, I got a little question.

Usually when i change some dependency in the package.json (manually) OR if I update node or npm globally.... i completely delete node_modules folder to make a new clean install of the pkgs.

 I just would like to know if it's there an alternative for this,
 maybe `npm prune && npm install` is enough?

I am not sure about this .... thanks for any help

**Comment by legodude17** [comment]
Running `npm install` again might work, but by far the best way is to just nuke `node_modules` and then run `npm install`.

**Comment by yopbeast** [comment]
@legodude17 thanks, what about ...npm prune.... wouldn't help instead of deleting node_modules/ ?
