### ISSUE TITLE
npm installation problem

### ISSUE THREAD

**Issue by Uvii** [npm/npm#15030]
C:\Users\SDYKS\Desktop\seed\angular-2-beta-boilerplate>npm install
[    ..............] | fetchMetadata: sill mapToRegistry uri https://registry.npnpm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\SDYKS\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.9

npm ERR! shasum check failed for C:\Users\SDYKS\AppData\Local\Temp\npm-9032-5308718a\registry.npmjs.org\es6-shim\-\es6-shim-0.35.1.tgz
npm ERR! Expected: a23524009005b031ab4a352ac196dfdfd1144ab7
npm ERR! Actual:   6384f83300982c8c473f577fa27b9979561db550
npm ERR! From:     https://registry.npmjs.org/es6-shim/-/es6-shim-0.35.1.tgz
npm ERR!

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\SDYKS\Desktop\seed\angular-2-beta-boilerplate\npm-debug.log

**Comment by KenanY** [comment]
@Uvii Have you tried running `npm cache clean`?

**Comment by KenanY** [comment]
I'm gonna close this since it seems like the same issue you've already reported before (https://github.com/npm/npm/issues/15030). Please don't open duplicate issues :(
