### ISSUE TITLE
Error when installing Cordova Ionic on macOS Sierra

### ISSUE THREAD

**Issue by infoarte** [npm/npm#15039]
#### I'm opening this issue because:

  - [X] **npm is crashing**.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

_npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "cordova" "ionic"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! path /home/tnt
npm ERR! code ENOTSUP
npm ERR! errno -45
npm ERR! syscall mkdir
npm ERR! nospc ENOTSUP: operation not supported on socket, mkdir '/home/tnt'
npm ERR! nospc This is most likely not a problem with npm itself
npm ERR! nospc and is related to insufficient space on your system._

#### How can the CLI team reproduce the problem?

**npm install -g cordova ionic
and
sudo npm install -g cordova ionic**

### supporting information:

 - `npm -v` prints: 3.10.8
 - `node -v` prints: v6.9.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS Sierra

**Comment by Charlotteis** [comment]
Hi @infoarte, I wonder if the solution in https://github.com/npm/npm/issues/10311 would be of use here? I say this because your path is also `/home` when it looks like it should be `/Users`. Happy to be corrected but this seems like a good first step to take.

**Comment by KenanY** [comment]
Closing as abandoned.
