### ISSUE TITLE
unpublish

### ISSUE THREAD

**Issue by chasset** [npm/npm#15048]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I am trying to clean a temporary repository from npm. But the program refuses, even with --force.

#### How can the CLI team reproduce the problem?

`npm --force unpublish build-graph-from-json` produces this [log file](https://gist.github.com/chasset/52ca746d75019680f1e43e690bffeee6).

### supporting information:

 - `npm -v` prints: 3.10.9
 - `node -v` prints: v7.2.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - macOS Sierra 10.12.1
 - Network issues: None

**Comment by KenanY** [comment]
Please email `support@npmjs.com` for package unpublishes.
