### ISSUE TITLE
Problemas al instalar gulp en Windows 10

### ISSUE THREAD

**Issue by lucasramela** [npm/npm#15046]
Hola, espero alguien me pueda ayudar. Quiero instalar gulp en mi pc, y me tira el siguiente mensaje de error:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'gulp',
1 verbose cli   '--save-dev' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData gulp
8 silly fetchNamedPackageData gulp
9 silly mapToRegistry name gulp
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'gulp',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'gulp',
12 silly mapToRegistry   name: 'gulp',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/gulp
14 verbose request uri https://registry.npmjs.org/gulp
15 verbose request no auth needed
16 info attempt registry request try #1 at 05:45:20
17 verbose request id 95056a17cee755c6
18 http request GET https://registry.npmjs.org/gulp
19 http 200 https://registry.npmjs.org/gulp
20 verbose headers { server: 'nginx/1.10.1',
20 verbose headers   'content-type': 'application/json',
20 verbose headers   'last-modified': 'Mon, 28 Nov 2016 05:45:18 GMT',
20 verbose headers   etag: 'W/"583bc46e-1c8b7"',
20 verbose headers   'content-encoding': 'gzip',
20 verbose headers   'cache-control': 'max-age=300',
20 verbose headers   'content-length': '16571',
20 verbose headers   'accept-ranges': 'bytes',
20 verbose headers   date: 'Mon, 28 Nov 2016 08:45:22 GMT',
20 verbose headers   via: '1.1 varnish',
20 verbose headers   age: '0',
20 verbose headers   connection: 'keep-alive',
20 verbose headers   'x-served-by': 'cache-gru7121-GRU',
20 verbose headers   'x-cache': 'HIT',
20 verbose headers   'x-cache-hits': '1',
20 verbose headers   'x-timer': 'S1480322722.275443,VS0,VE182',
20 verbose headers   vary: 'Accept-Encoding' }
21 silly get cb [ 200,
21 silly get   { server: 'nginx/1.10.1',
21 silly get     'content-type': 'application/json',
21 silly get     'last-modified': 'Mon, 28 Nov 2016 05:45:18 GMT',
21 silly get     etag: 'W/"583bc46e-1c8b7"',
21 silly get     'content-encoding': 'gzip',
21 silly get     'cache-control': 'max-age=300',
21 silly get     'content-length': '16571',
21 silly get     'accept-ranges': 'bytes',
21 silly get     date: 'Mon, 28 Nov 2016 08:45:22 GMT',
21 silly get     via: '1.1 varnish',
21 silly get     age: '0',
21 silly get     connection: 'keep-alive',
21 silly get     'x-served-by': 'cache-gru7121-GRU',
21 silly get     'x-cache': 'HIT',
21 silly get     'x-cache-hits': '1',
21 silly get     'x-timer': 'S1480322722.275443,VS0,VE182',
21 silly get     vary: 'Accept-Encoding' } ]
22 verbose get saving gulp to C:\Users\Lucas\AppData\Roaming\npm-cache\registry.npmjs.org\gulp\.cache.json
23 verbose correctMkdir C:\Users\Lucas\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
24 verbose makeDirectory C:\Users\Lucas\AppData\Roaming\npm-cache creation not in flight; initializing
25 verbose makeCacheDir UID & GID are irrelevant on win32
26 silly install normalizeTree
27 silly loadCurrentTree Finishing
28 silly loadIdealTree Starting
29 silly install loadIdealTree
30 silly cloneCurrentTree Starting
31 silly install cloneCurrentTreeToIdealTree
32 silly cloneCurrentTree Finishing
33 silly loadShrinkwrap Starting
34 silly install loadShrinkwrap
35 silly loadShrinkwrap Finishing
36 silly loadAllDepsIntoIdealTree Starting
37 silly install loadAllDepsIntoIdealTree
38 silly rollbackFailedOptional Starting
39 silly rollbackFailedOptional Finishing
40 silly runTopLevelLifecycles Finishing
41 silly install printInstalled
42 verbose stack Error: Refusing to install gulp as a dependency of itself
42 verbose stack     at checkSelf (C:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:53:14)
42 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
42 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
42 verbose stack     at chain (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
42 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:16:5
42 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
42 verbose stack     at Array.forEach (native)
42 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
42 verbose stack     at Array.forEach (native)
42 verbose stack     at asyncMap (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
43 verbose cwd D:\Lucas\Desarrollo\2016\Escuela Digital\css3-practica\10- gulp-sass
44 error Windows_NT 10.0.14393
45 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "gulp" "--save-dev"
46 error node v6.9.1
47 error npm  v3.10.8
48 error code ENOSELF
49 error Refusing to install gulp as a dependency of itself
50 error If you need help, you may report this error at:
50 error     <https://github.com/npm/npm/issues>
51 verbose exit [ 1, true ]

Muchas gracias desde ya!!
Mi version de node es: v6.9.1
Mi version de npm es: 3.10.8
Ya cree el archivo "package.json" con el comando nmp init en el directorio de mi proyecto. Tambien tengo instalado gulp globalmente. Cuando quiero instalar gulp localmente con: npm install gulp --save-dev me ocurre el error que les mostre arriba.

MUCHAS GRACIAS!!!

**Comment by KenanY** [comment]
@lucasramela Make sure that the `"name"` property in your `package.json` is not set to `"gulp"`.

**Comment by lucasramela** [comment]
Es verdad!!! Muchas gracias solucionado!!
