### ISSUE TITLE
Cannot install data-atom package

### ISSUE THREAD

**Issue by joedots1** [npm/npm#15040]
Installing “data-atom@0.24.0” failed.Hide output…

npm ERR! git clone --template=/Users/joedotson/.atom/.apm/_git-remotes/_templates --mirror https://github.com/lukemurray/node-postgres.git /Users/joedotson/.atom/.apm/_git-remotes/git-https-github-com-lukemurray-node-postgres-git-master-2b8e007d: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
npm ERR! Darwin 16.1.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/joedotson/.atom/.apm/.apmrc" "--userconfig" "/Users/joedotson/.atom/.apmrc" "install" "/private/var/folders/6p/rs3t1b5d7y5c2204qfd_cgtr0000gn/T/d-1161026-2244-1hhznum/package.tgz" "--runtime=electron" "--target=1.3.9" "--arch=x64" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code 1

npm ERR! Command failed: git clone --template=/Users/joedotson/.atom/.apm/_git-remotes/_templates --mirror https://github.com/lukemurray/node-postgres.git /Users/joedotson/.atom/.apm/_git-remotes/git-https-github-com-lukemurray-node-postgres-git-master-2b8e007d
npm ERR! xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/6p/rs3t1b5d7y5c2204qfd_cgtr0000gn/T/apm-install-dir-1161026-2244-3j7624/npm-debug.log

**Comment by Charlotteis** [comment]
Hey @joedots1. Did you recently update your Mac?
The `xcrun` issue you're experience is likely related to a command line tools error and not npm itself. I've experience the same issue before.

What happens if you do

`xcode-select --install` on the command line
then try and install the package again?

⭐️

**Comment by joedots1** [comment]
I did recently update to Sierra. Thought that could be the issue. I'm not much on the command line, but I'll give this a go. Thank you!

**Comment by joedots1** [comment]
It worked! @Charlotteis you're an MVP. Thanks so much!
