### ISSUE TITLE
Errors installing nodemon on Win7

### ISSUE THREAD

**Issue by quantbo** [npm/npm#15049]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
See attached screenshot. Also attaching npm-debug.log. Or tried to...
The output specifically asks the user to upload the `npm-debug.log`  file:

```
npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Main\Dropbox\_code_share\WebDev\NodeJS\scotch\npm-debug.log

```
but when I try I am told

> "We don't support that file type."

Huh???

  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Attempting to install nodemon on a Windows 7 machine. Many errors are generated. See attached screenshot.
![screenshot 2016-11-28 11 00 41](https://cloud.githubusercontent.com/assets/10783108/20680043/94b74c10-b55a-11e6-917f-006b6b37e25b.png)

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@quantbo You can upload the `npm-debug.log` to <https://gist.github.com/> and post the link here.

**Comment by quantbo** [comment]
I reinstalled using the -g option, i.e.,

`npm install -g nodemon`

That allowed the install to go through. In the process, it appears that the npm-debug.log file was deleted by the installer.

**Comment by legodude17** [comment]
Can you close this @KenanY?
