### ISSUE TITLE
Virtual/Automatic run-script entries for binaries in node_modules/.bin

### ISSUE THREAD

**Issue by tkissing** [npm/npm#15054]
#### What's the feature?

When a user runs `npm run <target>` and there is no matching `<target>` script in package.json, but there is a binary named `<target>` in `./node_modules/.bin/` then npm should run that binary (and pass arguments on correctly)

#### What problem is the feature intended to solve?
Many tools still recommend/require to be installed globally, mostly because there is no convenient way to invoke them otherwise. Global installs are problematic, because they can create or mask issues when the globally installed version does not match the one in package.json (or worse, there is no entry in package.json at all, just some informal reference in a README or other documentation). 

(See also this thread about angular CLI https://twitter.com/tkissing/status/760669220782821376 )

#### Is the absence of this feature blocking you or your team? If so, how?
Nope.

#### Is this feature similar to an existing feature in another tool?
One could argue that it is a continuation of the automatic addition of `./node_modules/.bin/` to the path when using `npm run`. 

#### Is this a feature you're prepared to implement, with support from the npm CLI team?
Yes, I could.

**Comment by KenanY** [comment]
This sounds just like https://github.com/npm/npm/issues/6053 to me. If I'm wrong, just let me know and I can reopen this.

**Comment by tkissing** [comment]
Was not obvious from the original #6053 but after reading the discussion there I agree, it's the same/solves same problem.
Thanks!
