### ISSUE TITLE
[QUESTION] npm prune globals

### ISSUE THREAD

**Issue by yopbeast** [npm/npm#15058]
Hi, am i missing anything or `npm prune` doesn't work in Global folder?

Is there any alternative or way to remove global invalid packages?

I use nvm and running: `npm prune -g` or `sudo npm prune -g` result is:

```
ENOENT: no such file or directory, open '/Users/me/.nvm/versions/node/v7.1.0/lib/package.json'
15 error enoent This is most likely not a problem with npm itself
15 error enoent and is related to npm not being able to find a file.
```

Maybe it's a problem with nvm itself?
thank you

**Comment by legodude17** [comment]
`npm prune` doesn't work in global folder, because it isn't a project and doesn't have a package.json, hence that error.

**Comment by yopbeast** [comment]
thanks @legodude17

**Comment by ShadSterling** [comment]
So how do you prune extraneous dependencies from globally installed packages?
