### ISSUE TITLE
NPM throws Error - getaddrinfo EAI_AGAIN

### ISSUE THREAD

**Issue by PrasanthJayaraman** [npm/npm#15059]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [# ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

<details><pre>
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "ins
tall" "utils" "aws-sdk" "async" "gm" "path"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! syscall getaddrinfo

npm ERR! getaddrinfo EAI_AGAIN proxy.yourcorp.com:811
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\prasanth.j\Desktop\lamdaFunction\npm-debug.log
</pre></details>

#### npm-debug.log

<pre><details>
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'utils',
1 verbose cli   'aws-sdk',
1 verbose cli   'async',
1 verbose cli   'gm',
1 verbose cli   'path' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData utils
8 silly fetchPackageMetaData aws-sdk
9 silly fetchPackageMetaData async
10 silly fetchPackageMetaData gm
11 silly fetchPackageMetaData path
12 silly fetchNamedPackageData utils
13 silly mapToRegistry name utils
14 silly mapToRegistry using default registry
15 silly mapToRegistry registry http://registry.npmjs.org/
16 silly mapToRegistry data Result {
16 silly mapToRegistry   raw: 'utils',
16 silly mapToRegistry   scope: null,
16 silly mapToRegistry   escapedName: 'utils',
16 silly mapToRegistry   name: 'utils',
16 silly mapToRegistry   rawSpec: '',
16 silly mapToRegistry   spec: 'latest',
16 silly mapToRegistry   type: 'tag' }
17 silly mapToRegistry uri http://registry.npmjs.org/utils
18 silly fetchNamedPackageData async
19 silly mapToRegistry name async
20 silly mapToRegistry using default registry
21 silly mapToRegistry registry http://registry.npmjs.org/
22 silly mapToRegistry data Result {
22 silly mapToRegistry   raw: 'async',
22 silly mapToRegistry   scope: null,
22 silly mapToRegistry   escapedName: 'async',
22 silly mapToRegistry   name: 'async',
22 silly mapToRegistry   rawSpec: '',
22 silly mapToRegistry   spec: 'latest',
22 silly mapToRegistry   type: 'tag' }
23 silly mapToRegistry uri http://registry.npmjs.org/async
24 silly fetchNamedPackageData aws-sdk
25 silly mapToRegistry name aws-sdk
26 silly mapToRegistry using default registry
27 silly mapToRegistry registry http://registry.npmjs.org/
28 silly mapToRegistry data Result {
28 silly mapToRegistry   raw: 'aws-sdk',
28 silly mapToRegistry   scope: null,
28 silly mapToRegistry   escapedName: 'aws-sdk',
28 silly mapToRegistry   name: 'aws-sdk',
28 silly mapToRegistry   rawSpec: '',
28 silly mapToRegistry   spec: 'latest',
28 silly mapToRegistry   type: 'tag' }
29 silly mapToRegistry uri http://registry.npmjs.org/aws-sdk
30 silly fetchNamedPackageData gm
31 silly mapToRegistry name gm
32 silly mapToRegistry using default registry
33 silly mapToRegistry registry http://registry.npmjs.org/
34 silly mapToRegistry data Result {
34 silly mapToRegistry   raw: 'gm',
34 silly mapToRegistry   scope: null,
34 silly mapToRegistry   escapedName: 'gm',
34 silly mapToRegistry   name: 'gm',
34 silly mapToRegistry   rawSpec: '',
34 silly mapToRegistry   spec: 'latest',
34 silly mapToRegistry   type: 'tag' }
35 silly mapToRegistry uri http://registry.npmjs.org/gm
36 silly fetchNamedPackageData path
37 silly mapToRegistry name path
38 silly mapToRegistry using default registry
39 silly mapToRegistry registry http://registry.npmjs.org/
40 silly mapToRegistry data Result {
40 silly mapToRegistry   raw: 'path',
40 silly mapToRegistry   scope: null,
40 silly mapToRegistry   escapedName: 'path',
40 silly mapToRegistry   name: 'path',
40 silly mapToRegistry   rawSpec: '',
40 silly mapToRegistry   spec: 'latest',
40 silly mapToRegistry   type: 'tag' }
41 silly mapToRegistry uri http://registry.npmjs.org/path
42 verbose request uri http://registry.npmjs.org/utils
43 verbose request no auth needed
44 info attempt registry request try #1 at 5:35:06 PM
45 verbose request id 6b4b25548544668e
46 http request GET http://registry.npmjs.org/utils
47 verbose request uri http://registry.npmjs.org/async
48 verbose request no auth needed
49 info attempt registry request try #1 at 5:35:06 PM
50 http request GET http://registry.npmjs.org/async
51 verbose request uri http://registry.npmjs.org/aws-sdk
52 verbose request no auth needed
53 info attempt registry request try #1 at 5:35:06 PM
54 http request GET http://registry.npmjs.org/aws-sdk
55 verbose request uri http://registry.npmjs.org/gm
56 verbose request no auth needed
57 info attempt registry request try #1 at 5:35:06 PM
58 http request GET http://registry.npmjs.org/gm
59 verbose request uri http://registry.npmjs.org/path
60 verbose request no auth needed
61 info attempt registry request try #1 at 5:35:06 PM
62 http request GET http://registry.npmjs.org/path
63 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN proxy.yourcorp.com:811
64 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN proxy.yourcorp.com:811
65 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN proxy.yourcorp.com:811
66 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN proxy.yourcorp.com:811
67 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN proxy.yourcorp.com:811
68 info attempt registry request try #2 at 5:35:21 PM
69 http request GET http://registry.npmjs.org/gm
70 info attempt registry request try #2 at 5:35:21 PM
71 http request GET http://registry.npmjs.org/aws-sdk
72 info attempt registry request try #2 at 5:35:21 PM
73 http request GET http://registry.npmjs.org/async
74 info attempt registry request try #2 at 5:35:21 PM
75 http request GET http://registry.npmjs.org/utils
76 info attempt registry request try #2 at 5:35:24 PM
77 http request GET http://registry.npmjs.org/path
78 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN proxy.yourcorp.com:811
79 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN proxy.yourcorp.com:811
80 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN proxy.yourcorp.com:811
81 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN proxy.yourcorp.com:811
82 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN proxy.yourcorp.com:811
83 info attempt registry request try #3 at 5:36:26 PM
84 http request GET http://registry.npmjs.org/async
85 info attempt registry request try #3 at 5:36:26 PM
86 http request GET http://registry.npmjs.org/utils
87 info attempt registry request try #3 at 5:36:26 PM
88 http request GET http://registry.npmjs.org/aws-sdk
89 info attempt registry request try #3 at 5:36:26 PM
90 http request GET http://registry.npmjs.org/gm
91 info attempt registry request try #3 at 5:36:29 PM
92 http request GET http://registry.npmjs.org/path
93 silly fetchPackageMetaData Error: getaddrinfo EAI_AGAIN proxy.yourcorp.com:811
93 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1026:11)
93 silly fetchPackageMetaData     at errnoException (dns.js:33:15)
93 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
93 silly fetchPackageMetaData  error for gm { Error: getaddrinfo EAI_AGAIN proxy.yourcorp.com:811
93 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1026:11)
93 silly fetchPackageMetaData     at errnoException (dns.js:33:15)
93 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
93 silly fetchPackageMetaData   code: 'EAI_AGAIN',
93 silly fetchPackageMetaData   errno: 'EAI_AGAIN',
93 silly fetchPackageMetaData   syscall: 'getaddrinfo',
93 silly fetchPackageMetaData   hostname: 'proxy.yourcorp.com',
93 silly fetchPackageMetaData   host: 'proxy.yourcorp.com',
93 silly fetchPackageMetaData   port: '811' }
94 silly fetchPackageMetaData Error: getaddrinfo EAI_AGAIN proxy.yourcorp.com:811
94 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1026:11)
94 silly fetchPackageMetaData     at errnoException (dns.js:33:15)
94 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
94 silly fetchPackageMetaData  error for aws-sdk { Error: getaddrinfo EAI_AGAIN proxy.yourcorp.com:811
94 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1026:11)
94 silly fetchPackageMetaData     at errnoException (dns.js:33:15)
94 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
94 silly fetchPackageMetaData   code: 'EAI_AGAIN',
94 silly fetchPackageMetaData   errno: 'EAI_AGAIN',
94 silly fetchPackageMetaData   syscall: 'getaddrinfo',
94 silly fetchPackageMetaData   hostname: 'proxy.yourcorp.com',
94 silly fetchPackageMetaData   host: 'proxy.yourcorp.com',
94 silly fetchPackageMetaData   port: '811' }
95 silly fetchPackageMetaData Error: getaddrinfo EAI_AGAIN proxy.yourcorp.com:811
95 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1026:11)
95 silly fetchPackageMetaData     at errnoException (dns.js:33:15)
95 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
95 silly fetchPackageMetaData  error for utils { Error: getaddrinfo EAI_AGAIN proxy.yourcorp.com:811
95 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1026:11)
95 silly fetchPackageMetaData     at errnoException (dns.js:33:15)
95 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
95 silly fetchPackageMetaData   code: 'EAI_AGAIN',
95 silly fetchPackageMetaData   errno: 'EAI_AGAIN',
95 silly fetchPackageMetaData   syscall: 'getaddrinfo',
95 silly fetchPackageMetaData   hostname: 'proxy.yourcorp.com',
95 silly fetchPackageMetaData   host: 'proxy.yourcorp.com',
95 silly fetchPackageMetaData   port: '811' }
96 silly fetchPackageMetaData Error: getaddrinfo EAI_AGAIN proxy.yourcorp.com:811
96 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1026:11)
96 silly fetchPackageMetaData     at errnoException (dns.js:33:15)
96 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
96 silly fetchPackageMetaData  error for async { Error: getaddrinfo EAI_AGAIN proxy.yourcorp.com:811
96 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1026:11)
96 silly fetchPackageMetaData     at errnoException (dns.js:33:15)
96 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
96 silly fetchPackageMetaData   code: 'EAI_AGAIN',
96 silly fetchPackageMetaData   errno: 'EAI_AGAIN',
96 silly fetchPackageMetaData   syscall: 'getaddrinfo',
96 silly fetchPackageMetaData   hostname: 'proxy.yourcorp.com',
96 silly fetchPackageMetaData   host: 'proxy.yourcorp.com',
96 silly fetchPackageMetaData   port: '811' }
97 silly fetchPackageMetaData Error: getaddrinfo EAI_AGAIN proxy.yourcorp.com:811
97 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1026:11)
97 silly fetchPackageMetaData     at errnoException (dns.js:33:15)
97 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
97 silly fetchPackageMetaData  error for path { Error: getaddrinfo EAI_AGAIN proxy.yourcorp.com:811
97 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1026:11)
97 silly fetchPackageMetaData     at errnoException (dns.js:33:15)
97 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
97 silly fetchPackageMetaData   code: 'EAI_AGAIN',
97 silly fetchPackageMetaData   errno: 'EAI_AGAIN',
97 silly fetchPackageMetaData   syscall: 'getaddrinfo',
97 silly fetchPackageMetaData   hostname: 'proxy.yourcorp.com',
97 silly fetchPackageMetaData   host: 'proxy.yourcorp.com',
97 silly fetchPackageMetaData   port: '811' }
98 silly rollbackFailedOptional Starting
99 silly rollbackFailedOptional Finishing
100 silly runTopLevelLifecycles Finishing
101 silly install printInstalled
102 verbose stack Error: getaddrinfo EAI_AGAIN proxy.yourcorp.com:811
102 verbose stack     at Object.exports._errnoException (util.js:1026:11)
102 verbose stack     at errnoException (dns.js:33:15)
102 verbose stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
103 verbose cwd C:\Users\prasanth.j\Desktop\lamdaFunction
104 error Windows_NT 6.1.7601
105 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "utils" "aws-sdk" "async" "gm" "path"
106 error node v6.9.1
107 error npm  v3.10.8
108 error code EAI_AGAIN
109 error errno EAI_AGAIN
110 error syscall getaddrinfo
111 error getaddrinfo EAI_AGAIN proxy.yourcorp.com:811
112 error If you need help, you may report this error at:
112 error     <https://github.com/npm/npm/issues>
113 verbose exit [ 1, true ]
</pre></details>

Node : 6.9.1
Npm : 3.10.8

**Comment by KenanY** [comment]
@PrasanthJayaraman Looks like an issue with your internet connection through that proxy of yours. Are you certain that you have configured your proxy correctly?

**Comment by PrasanthJayaraman** [comment]
@KenanY  I checked with my Proxy - I'm not connected to any proxy it is just a normal LAN Wifi in a office. I guess in office they wont restrict NPM. I reinstalled Node and NPM but still the same. Also I switched to diff Wifi networks still the same...

**Comment by KenanY** [comment]
@PrasanthJayaraman What is the result of running `npm config get proxy`?

**Comment by gspvish** [comment]
@KenanY - I'm also facing the same issue and I get a null on executing `npm config get proxy`

**Comment by jkugiya** [comment]
Following operation solved this problem in my situation.
```
$ ping registry.npmjs.org
PING registry.npmjs.org (151.101.72.162) 56(84) bytes of data.

$ sudo vi /etc/hosts
151.101.72.162 registry.npmjs.org
```

**Comment by Kay2dan** [comment]
@jkugiya would you please clarify on this:

I added the line `151.101.72.162 registry.npmjs.org` to the `etc/hosts` file, so it looks as such:
```
127.0.0.1 localhost

 127.0.1.1 inspiron7370

 151.101.72.162 registry.npmjs.org
```

However, the Dockerfile is still unable to install npm packages & I get error: 

`npm ERR! code EAI_AGAIN
...`

**Comment by jzzhrqp** [comment]
Step 11/15 : RUN npm install
 ---> Running in a02ac1c46d5e
npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! request to https://registry.npmjs.org/graphql failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org:443

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-06-08T02_55_56_059Z-debug.log
The command '/bin/sh -c npm install' returned a non-zero code: 1

what can i do for this

**Comment by jkugiya** [comment]
@Kay2dan What is the output of ping?
```
$ ping registry.npmjs.org
```

In my case, problem was that address could not be resolved  the host from local environment. So output of error says `reason: getaddrinfo EAI_AGAIN `.

> npm ERR! code EAI_AGAIN

It seems to be different from the problem I encountered.

**Comment by Kay2dan** [comment]
@jkugiya yes, the only thing that worked for me was to install node locally on my machine & then install the packages locally & then dockerise it, which worked. However, I believe the core issue of container not accessing the registry remains.
