### ISSUE TITLE
npm ERR! Darwin 16.1.0

### ISSUE THREAD

**Issue by akhillgopinath** [npm/npm#15051]
i am getting error like this when i do npm start 

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! react-signup-form@0.0.0 start: `node_modules/gulp/bin/gulp.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-signup-form@0.0.0 start script 'node_modules/gulp/bin/gulp.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-signup-form package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node_modules/gulp/bin/gulp.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-signup-form
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-signup-form
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/akhil/Documents/react-signup-form-master/npm-debug.log

**Comment by KenanY** [comment]
@akhillgopinath Looks like the error is coming from your `"start"` script, not `npm`. Perhaps, try changing your `"start"` script to simply run `"gulp"`?
