### ISSUE TITLE
Allow packages to be installed to a given directory namespace, ex with `--as`

### ISSUE THREAD

**Issue by Miserlou** [npm/npm#15052]
#### What's the feature?

The ability to install a given package under a specified name. For instance: `npm install foo --as bar`.

#### What problem is the feature intended to solve?

I have a specific need to install packages with very slight modifications as a version of another package.

For instance, I have a package called `simple-get-es5`, which is an ES5-polyfilled version of `simple-get`. Currently, to use this in my downstream project, I have to `npm install simple-get-es5` and then manually `trash simple-get; mv simple-get-es5 simple-get`, and I have to do this every time I touch another package which uses my simple get.

I'd be super handy if I could install a package to a given namespace and avoid this problem!

#### Is the absence of this feature blocking you or your team? If so, how?

It's not a blocking feature, just a persistent inconvenience. 

#### Is this feature similar to an existing feature in another tool?

Not that I'm aware of off the top of my head, but it wouldn't surprise me. I can do more research to other package managers if this is relevant. 

#### Is this a feature you're prepared to implement, with support from the npm CLI team?

Sure! That'd be fun.

**Comment by legodude17** [comment]
+1, this would be very helpful for polyfills, though I am wondering how you would communicate that in `package.json`.

**Comment by Miserlou** [comment]
That's a great question.

Some ideas:

a) Have another delimiter for the `as`, ex:

```json
"dependencies": {
  "foo": "^1.0.0#bar"
 }
```

b) Allow deps to be dictionaries, not just strings:

```json
"dependencies": {
  "foo": {
             "version": ^1.0.0",
             "as": "bar"
           }
 }
```

c) Have a delimiter on the package name side:

```json
"dependencies": {
  "foo@bar": "^1.0.0"
 }
```

d) Have an additional entry for aliases:

```json
"dependencies": {
  "foo": "^1.0.0"
 },
"aliases": {
  "foo": "bar"
}
```

**Comment by legodude17** [comment]
I would say that b would be a breaking change, so probably not. I don't really like the idea of adding more info to the value (a) or adding yet another `package.json` property (d). I like c, as it seems to be the best option. I would think it would be backwards compatible.

**Comment by Miserlou** [comment]
I think my personal preferences is for D as it's the most explicit, but would that be a breaking change? Does NPM currently choke on unexpected fields?

**Comment by legodude17** [comment]
I don't think that D is a breaking change, but the `package.json` is so used already, I don't really like the idea of adding yet another field. Also, that could lead to foot guns if that key is at the bottom.

**Comment by Miserlou** [comment]
Does the NPM package.json parser do so in a streaming fashion? I don't think the order of the keys should matter, it should just be a dictionary look-up to something that's already in memory.

**Comment by othiym23** [comment]
This is not something that the CLI is going to support. There are use cases in which being able to alias or rename packages is useful, but there are also a host of edge cases that make it all too easy for this to produce exactly the kind of dependency hell that npm is designed to avoid. See https://github.com/npm/npm/issues/2943#issuecomment-10388316 for some further discussion of why renaming in `package.json` is a bad idea; as far as being able to substitute one package for another on the fly, it requires a set of very specific assumptions about how packages are used to hold to be safe, and as such seems like a major footgun-in-waiting. As such, I'm going to close this feature request. Thanks for your time and discussion!
