### ISSUE TITLE
Not displaying the correct readme file

### ISSUE THREAD

**Issue by tusharmath** [npm/npm#15056]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?
Npm registry displays incorrect readme file.

**Incorrect:** https://www.npmjs.com/package/mt-downloader
**Correct:**:  https://registry.npmjs.org/mt-downloader/-/mt-downloader-2.2.2.tgz

#### How can the CLI team reproduce the problem?
- Publish an npm package with a  `dist-tag` other than `latest`
- Now using CLI change the `dist-tag` to latest
- Go to npm.js.com to your package, the readme will not be updated with the latest changes.

### supporting information:

 - `npm -v` prints:`3.10.9`
 - `node -v` prints: `v7.1.0`
 - `npm config get registry` prints: `dream11-widget git:(master) ✗`
 - Windows, OS X/macOS, or Linux?: `mac`
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
Issues with the website should be reported [here](https://github.com/npm/www).
