### ISSUE TITLE
Error in npm unpublish --force

### ISSUE THREAD

**Issue by vineetasharma** [npm/npm#15063]
npm WARN using --force I sure hope you know what you are doing.
npm ERR! Linux 3.16.0-30-generic
npm ERR! argv "/opt/node-v6.3.0-linux-x64/bin/node" "/usr/bin/npm" "unpublish" "--force"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! code E400

npm ERR! Registry returned 400 for DELETE on https://registry.npmjs.org/SoundCloud_Node_API/-rev/1-069f5cfe3176f8051a51f24d099d6b42
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ttnd/SoundCloud_Node_API/npm-debug.log

**Comment by legodude17** [comment]
I would suggest emailing support@npmjs.com for unpublishing modules.

**Comment by vineetasharma** [comment]
@legodude17  Thanks :)
