### ISSUE TITLE
npm install -g err

### ISSUE THREAD

**Issue by adhasyuhada** [npm/npm#15060]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

```
[apicadmin@hklapd06 ~]$ npm install -g apiconnect
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! Linux 3.10.0-327.el7.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "apiconnect"
npm ERR! node v4.6.2
npm ERR! npm  v3.10.5

npm ERR! shasum check failed for /tmp/npm-7752-a75bfd8b/registry.npmjs.org/strong-swagger-ui/-/strong-swagger-ui-21.0.2.tgz
npm ERR! Expected: 212a900dfab5ae04e628e21b5800632bd0d9e347
npm ERR! Actual:   ff7a33e9865baf329e69906161512476429916c3
npm ERR! From:     http://registry.npmjs.org/strong-swagger-ui/-/strong-swagger-ui-21.0.2.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR! <https://github.com/npm/npm/issues>     

npm ERR! Please include the following file with any support request:
npm ERR!     /home/apicadmin/npm-debug.log
```

#### How can the CLI team reproduce the problem?

```
[apicadmin@hklapd06 ~]$ npm install -g apiconnect
```

my npm log
[npm-debug.zip](https://github.com/npm/npm/files/619415/npm-debug.zip)

### supporting information:

 - `npm -v` prints: 3.10.5
 - `node -v` prints: v4.6.2
 - `npm config get registry` prints: http://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux 
 - Network issues:
   - Geographic location where npm was run:
   - [x] I use a proxy to connect to the npm registry.
   - [x] I use a proxy to connect to the web.
   - [x] I use a proxy when downloading Git repos.

**Comment by KenanY** [comment]
@adhasyuhada Have you tried clearing your cache with `npm cache clean`?

**Comment by adhasyuhada** [comment]
Hi KenanY, 
I have tried `npm cache clean` it's still error

**Comment by legodude17** [comment]
Duplicate of #14315, #14556, and #14620? We get a lot of "Shasum check failed" ☹️ Maybe it is an issue with your proxy messing with files? Try turning off the proxy and do it again.

**Comment by adhasyuhada** [comment]
Ok thank you @legodude17 it's work when i change registry with 'http://registry.cnpmjs.org'

**Comment by zkat** [comment]
Closing as resolved.
