### ISSUE TITLE
Unable to install appium through npm

### ISSUE THREAD

**Issue by harikrishnaburma** [npm/npm#15072]
#### I'm opening this issue because:

  - [ ] npm is doing something I don't understand.
 

#### What's going wrong?

I used the npm tool to install new appium version & this is the error I'm receiving.

npm -g install appium
/Users/local/.npm-packages/bin/appium -> /Users/local/.npm-packages/lib/node_modules/appium/build/lib/main.js

sqlite3@3.1.8 install /Users/local/.npm-packages/lib/node_modules/appium/node_modules/sqlite3
node-pre-gyp install --fallback-to-build
[sqlite3] Success: "/Users/local/.npm-packages/lib/node_modules/appium/node_modules/sqlite3/lib/binding/node-v51-darwin-x64/node_sqlite3.node" is installed via remote

appium-chromedriver@2.9.4 install /Users/local/.npm-packages/lib/node_modules/appium/node_modules/appium-chromedriver
node install-npm.js
info Chromedriver Install Installing Chromedriver version '2.25' for platform 'mac' and architecture '64'
info Chromedriver Install Opening temp file to write chromedriver_mac64 to...
info Chromedriver Install Downloading https://chromedriver.storage.googleapis.com/2.25/chromedriver_mac64.zip...
RequestError: Error: unable to get local issuer certificate
at new RequestError (/Users/local/.npm-packages/lib/node_modules/appium/node_modules/request-promise/lib/errors.js:11:15)
at Request.RP$callback as _callback
at self.callback (/Users/local/.npm-packages/lib/node_modules/appium/node_modules/request/request.js:186:22)
at emitOne (events.js:96:13)
at Request.emit (events.js:188:7)
at Request.onRequestError (/Users/local/.npm-packages/lib/node_modules/appium/node_modules/request/request.js:845:8)
at emitOne (events.js:96:13)
at ClientRequest.emit (events.js:188:7)
at TLSSocket.socketErrorListener (httpclient.js:309:9)
at emitOne (events.js:96:13)
at TLSSocket.emit (events.js:188:7)
at emitErrorNT (net.js:1281:8)
at combinedTickCallback (internal/process/nexttick.js:74:11)
at process.tickCallback (internal/process/nexttick.js:98:9)
/Users/local/.npm-packages/lib
└── (empty)

npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/Cellar/node/7.2.0/bin/node" "/Users/local/.npm-packages/bin/npm" "-g" "install" "appium"
npm ERR! node v7.2.0
npm ERR! npm v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! appium-chromedriver@2.9.4 install: node install-npm.js
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the appium-chromedriver@2.9.4 install script 'node install-npm.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the appium-chromedriver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! node install-npm.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR! npm bugs appium-chromedriver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! npm owner ls appium-chromedriver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR! /Users/local/npm-debug.log
npm ERR! code 1

Can someone help me out of this?

#### How can the CLI team reproduce the problem?

Open your Terminal in Mac and do the following actions.
rm -rf /usr/local/lib/node_modules
brew uninstall node
brew install node --without-npm
echo prefix=~/.npm-packages >> ~/.npmrc
curl -L -k https://www.npmjs.com/install.sh | sh
export PATH="$HOME/.npm-packages/bin:$PATH"
npm install -g appium

### supporting information:

 - `npm -v` prints: 7.2.0
 - `node -v` prints: 3.10.10
 - `npm config get registry` prints: https://registry.npmjs.org/ 
 - Windows, OS X/macOS, or Linux?: OSX
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@harikrishnaburma This doesn't look like an `npm` issue to me. `npm` did everything right here; the error happens when `appium-chromedriver` tries to download something, so perhaps this is an issue with your internet connection?
