### ISSUE TITLE
while installing ionic and cordova using npm in windows 7 ultimate

### ISSUE THREAD

**Issue by freelanceionicapps** [npm/npm#15071]
C:\Users\LAXMISOFT>npm install -g cordova ionic
npm ERR! Windows_NT 6.1.7600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova" "ionic"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8

npm ERR! shasum check failed for C:\Users\LAXMIS~1\AppData\Local\Temp\npm-924-c7
c70e8a\registry.npmjs.org\ionic\-\ionic-2.1.13.tgz
npm ERR! Expected: 35116b2ca8a10fefea4679d1b04f2b84807cba94
npm ERR! Actual:   5eb777dd3efe72f865b1be089eca6e5128aa3adf
npm ERR! From:     https://registry.npmjs.org/ionic/-/ionic-2.1.13.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by KenanY** [comment]
@freelanceionicapps Have you tried running `npm cache clean`?

**Comment by freelanceionicapps** [comment]
yes

**Comment by freelanceionicapps** [comment]
hi thank you issue got resolve after complete uninstall and reinstalled it with cmd with administrator now working fine
