### ISSUE TITLE
npm install with local cache causes infinite loop

### ISSUE THREAD

**Issue by ckuiawa** [npm/npm#15074]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [X ] Other (_see below for feature requests_): npm install gets in an infinite loop

#### What's going wrong?
npm install from a local directory to a subdirectory with the npm-cache inside the local directory causes an infinite loop.

#### How can the CLI team reproduce the problem?

From within any npm project:
npm config set cache ./npm-cache
npm install  --prefix <working_dir>/dist <working_dir>

(I'm assuming <working_dir>/dist exists)

The install writes to ./npm-cache/<project>/<version>/package.tgz.<timestamp> with the contents of the <working_directory>.  Since npm-cache is in the working directory, the install ends up in an infinite loop writing to that file.  If left long enough, the file would probably fill the hard drive. 

Since the npm install command never finished, I don't see an npm-debug.log file.

I worked around this by adding npm-cache/ to my .gitignore file.  But I spent days trying to figure out what was happening.

### supporting information:

 - `npm -v` prints: 3.8.6
 - `node -v` prints: v6.0.0
 - `npm config get registry` prints:

 - Windows, OS X/macOS, or Linux?: OS X
 - Network issues:
   No network issues.  Very fast wired connection to internet.

**Comment by ckuiawa** [comment]
This issue is also seen with npm version 3.10.8, node version 6.9.1.

**Comment by zkat** [comment]
Thanks for the report! I'm going to tentatively mark this as a big bug, since it sounds like it has some pretty serious results, even though it's a fairly corner-casey thing. Thanks a lot for the repro steps, too!
