### ISSUE TITLE
Maximum call stack size exceeded on npm outdated

### ISSUE THREAD

**Issue by srikantaitec** [npm/npm#15076]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [X ] Other (_see below for feature requests_):

#### What's going wrong?
npm Error while running the build.
#### How can the CLI team reproduce the problem?

The content of the npm-debug log is as below

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node6-lts/6.9.1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install' ]
2 info using npm@3.10.9
3 info using node@v6.9.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly install normalizeTree
8 verbose stack RangeError: Maximum call stack size exceeded
8 verbose stack     at Array.types.A (/usr/local/lib/node_modules/npm/node_modules/aproba/index.js:9:25)
8 verbose stack     at types.O (/usr/local/lib/node_modules/npm/node_modules/aproba/index.js:13:85)
8 verbose stack     at module.exports (/usr/local/lib/node_modules/npm/node_modules/aproba/index.js:30:10)
8 verbose stack     at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:37:3)
8 verbose stack     at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
8 verbose stack     at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
8 verbose stack     at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
8 verbose stack     at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
8 verbose stack     at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
8 verbose stack     at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
9 verbose cwd /Users/smukundan/r9/git/horizon
10 error Darwin 16.1.0
11 error argv "/usr/local/Cellar/node6-lts/6.9.1/bin/node" "/usr/local/bin/npm" "install"
12 error node v6.9.1
13 error npm  v3.10.9
14 error Maximum call stack size exceeded
15 error If you need help, you may report this error at:
15 error     <https://github.com/npm/npm/issues>
16 verbose exit [ 1, true ]

### supporting information:

The console  logs are as below:

nodejs-version-check:
     [echo] Checking Node.js version
     [exec] Your Node.js version is: v6.9.1

npm-symlink-friendly-update-check:
     [exec] { Error: Command failed: npm outdated
     [exec] npm ERR! Darwin 16.1.0
     [exec] npm ERR! argv "/usr/local/Cellar/node6-lts/6.9.1/bin/node" "/usr/local/bin/npm" "outdated"
     [exec] npm ERR! node v6.9.1
     [exec] npm ERR! npm  v3.10.9
     [exec] 
     [exec] npm ERR! Maximum call stack size exceeded
     [exec] npm ERR! 
     [exec] npm ERR! If you need help, you may report this error at:
     [exec] npm ERR!     <https://github.com/npm/npm/issues>
     [exec] 
     [exec] npm ERR! Please include the following file with any support request:
     [exec] npm ERR!     /Users/smukundan/r9/git/horizon/npm-debug.log
     [exec] 
     [exec]     at ChildProcess.exithandler (child_process.js:206:12)
     [exec]     at emitTwo (events.js:106:13)
     [exec]     at ChildProcess.emit (events.js:191:7)
     [exec]     at maybeClose (internal/child_process.js:877:16)
     [exec]     at Socket.<anonymous> (internal/child_process.js:334:11)
     [exec]     at emitOne (events.js:96:13)
     [exec]     at Socket.emit (events.js:188:7)
     [exec]     at Pipe._handle.close [as _onclose] (net.js:498:12) killed: false, code: 1, signal: null, cmd: 'npm outdated' }
     [exec] Result: 1

install-node-modules:
     [echo] Installing Node module dependencies
     [exec] npm ERR! Darwin 16.1.0
     [exec] npm ERR! argv "/usr/local/Cellar/node6-lts/6.9.1/bin/node" "/usr/local/bin/npm" "install"
     [exec] npm ERR! node v6.9.1
     [exec] npm ERR! npm  v3.10.9
     [exec] 
     [exec] npm ERR! Maximum call stack size exceeded
     [exec] npm ERR! 
     [exec] npm ERR! If you need help, you may report this error at:
     [exec] npm ERR!     <https://github.com/npm/npm/issues>
     [exec] 
     [exec] npm ERR! Please include the following file with any support request:
     [exec] npm ERR!     /Users/smukundan/r9/git/horizon/npm-debug.log
[buildgraph] BuildGraphTask: failed building: horizon. Error: The following error occurred while executing this line:

 - Windows, OS X/macOS, or Linux?:   OS X/macOS
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [X] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [X] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by zkat** [comment]
Hey! Thanks for the bug report. There's a number of `Maximum call stack exceeded` errors we've run into, and having it happen during `outdated` is different enough that I'll keep this one open. Thanks for the bug report! If you can somehow get an isolated repro for this we could use, we would really appreciate it.

**Comment by srikantaitec** [comment]
I got this issue resolved after deleting and nom install of the node modules. Not sure what have caused the issue though.
