### ISSUE TITLE
appium 1.6.1 install fails: Cannot read property 'deep-extend' of undefined

### ISSUE THREAD

**Issue by plozachmad** [npm/npm#15096]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [X] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Appium 1.6.1 install on macOS Sierra 10.12.1 fails (macOS running on VMware) with error message (see gist below)

#### How can the CLI team reproduce the problem?
Install macOS (same error with 10.11.1, 10.11.6, 10.12, 10.12.1) on VMware virtual machine
Install Node 7.2.0 (same error with 6.9.1)
Update npm or not (same error with 3.10.10, 4.0.2 and 4.0.3)
Run:
`sudo npm install -g -verbose appium@1.6.1`
Fails:
`Cannot read property 'deep-extend' of undefined`
Gist:
https://gist.github.com/plozachmad/93ddff90a17ca679eb1b45242d818d3a

### supporting information:

 - `npm -v` prints: 4.0.3
 - `node -v` prints: 7.2.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: vmware virtual macOS on physical Ubuntu 16.10

(P.D.: Tested on physical macbook: worked like a charm...)

**Comment by plozachmad** [comment]
Fixed by:
`sudo npm install -f -g npm@3
sudo npm install -f -g appium@1.6.1`

**Comment by Manikanta29** [comment]
if you have npm 4.0.3, it's not possible to get the latest appium.  

Get the latest npm with command : npm install -g npm@latest
You will get npm:4.1.1

And run the command: npm install -g appium 
You will get appium:1.6.3
