### ISSUE TITLE
Problem with npm search

### ISSUE THREAD

**Issue by MasterDmi** [npm/npm#15098]
#### I'm opening this issue because:
  - [x] npm is doing something I don't understand.

#### What's going wrong?
I can't call command "search". 
![image](https://cloud.githubusercontent.com/assets/24296504/20797440/af0abb16-b815-11e6-9dc9-85f58ad605c1.png)

### supporting information:

 - `npm search`
 - Windows;

>

**Comment by zkat** [comment]
`npm search` no longer works on any version of npm less than `npm@4`. Upgrade to `npm@4` to get this working again. Unfortunately, there's nothing we can really do for older versions, since this is simply a side-effect of the npm registry growing to the size it currently is.
