### ISSUE TITLE
Hi can anyone help with this ERROR ? 

### ISSUE THREAD

**Issue by Josh-Kaye** [npm/npm#15095]
Hi so I'm getting this problem when trying to run Browser sync. I've only got it to run a couple of times by just using the command line "start browser-sync" but it is now and unrecognised command. So I try and use "nmp start browser-sync" and I get this error. 

If anyone could point me in the correct direction or help I would be very grateful. Apologies in advanced  If I'm just being an idiot.

<img width="506" alt="screen shot 2016-12-01 at 11 51 53" src="https://cloud.githubusercontent.com/assets/22678791/20793010/cfc4d41c-b7bc-11e6-8c04-86d0057f9237.png">

<p>j:.npm-global Josh$ start browser-sync
-bash: start: command not found
j:.npm-global Josh$ npm start browser-sync
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start" "browser-sync"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8

npm ERR! missing script: start
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Josh/.npm-global/npm-debug.log</p>

**Comment by KenanY** [comment]
You must define a `"start"` script in your `package.json` before running `npm start`. This is documented [here](https://docs.npmjs.com/misc/scripts).
