### ISSUE TITLE
npm install of ARM Visualizer - failed

### ISSUE THREAD

**Issue by echameleon** [npm/npm#15109]
#### I'm opening this issue because:
  - [X ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Running following from elevated powershell on Windows 10 1607
npm install https://github.com/msshli/arm-visualizer

#### How can the CLI team reproduce the problem?
Use Windows 10 1607 machine
Install Git version 2.10.2.windows.1
Install Node v7.2.0

### supporting information:

 - `npm -v` prints:
PS C:\WINDOWS\system32> npm -v
3.10.9
 - `node -v` prints:
PS C:\WINDOWS\system32> node -v
v7.2.0

 - `npm config get registry` prints:
PS C:\WINDOWS\system32> npm config get registry
https://registry.npmjs.org/

 - Windows, OS X/macOS, or Linux?:
Windows 10 - 1607

 - Network issues:
   - Geographic location where npm was run:
 My house with good net connect
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).
None of above - maybe I missed something?
Developed by someone else -trying to do install per 
https://github.com/msshli/arm-visualizer
npm install

I have docker on the target machine.
---ok what did I screw up? Is there something I should be reading somewhere that would have helped?

**Comment by echameleon** [comment]
Forgot gist :( 
https://gist.github.com/echameleon/a23bba3e3d0c488588a1bc1730b81f1e

**Comment by zkat** [comment]
The [`package.json` for `arm-visualizer`](https://github.com/msshli/arm-visualizer/blob/master/package.json) is missing a `"name"` field. That is the source of the error.

The source of the problem you're having is that the intended usage of this package is like so:

```sh
git clone https://github.com/msshli/arm-visualizer
cd arm-visualizer
npm install
npm run build
npm start
```

You may want to also submit an issue to their repo to fix their `package.json` and their documentation for this. Cheers!
