### ISSUE TITLE
angularfire2 issues

### ISSUE THREAD

**Issue by marcellopato** [npm/npm#15100]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### How can the CLI team reproduce the problem?

`<script src="https://gist.github.com/marcellopato/6cc664fd1bac85739a1f84f72b1f88ad.js"></script>`

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
Proper link to the gist: <https://gist.github.com/marcellopato/6cc664fd1bac85739a1f84f72b1f88ad>

**Comment by KenanY** [comment]
Make sure the `"name"` property in your `package.json` is not set to `"angularfire2"`.
