### ISSUE TITLE
Can't publish my module.

### ISSUE THREAD

**Issue by MasterDmi** [npm/npm#15112]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
After creating new user, I try to publish my module, but I can't.
![image](https://cloud.githubusercontent.com/assets/24296504/20820592/45dd9bb0-b877-11e6-9c8a-0462dd3187b0.png)

### supporting information:

 - `npm -v` prints: 3.10.9
 - `node -v` prints: 7.2.0
 - Windows

**Comment by zkat** [comment]
@MasterDmi modules in the npm registry exist in a single shared namespace. That means that if anyone else wrote a module with the name `mymod` ([which they did](https://npm.im/mymod)), then you can't publish a package with that name. Change the name of your module to one that isn't already in use, or use [a scoped package](https://docs.npmjs.com/getting-started/scoped-packages) to proceed. Cheers!

**Comment by MasterDmi** [comment]
Problem solved. Thx!
