### ISSUE TITLE
webpack w- error

### ISSUE THREAD

**Issue by sherrynazih** [npm/npm#15111]
Error when trying to run webpack -w by

ERROR in ./app/components/Main.js
Module build failed: SyntaxError: /Users/sherry/Documents/Eventtus/egghead/app/components/Main.js: Expecting Unicode escape sequence \uXXXX (9:10)
   7 |         <div>
   8 |           Hello World
>  9 |         <\div>
     |           ^
  10 |       )
  11 |     }
  12 |   });

and that's my code:
var React = require('react');
  var ReactDOM = require('react-dom');

  var Main = React.createClass({
    render: function(){
      return(
        <div>
          Hello World
        </div>
      )
    }
  });

  ReactDOM.render(<Main />, document.getElementByID('app'))

**Comment by zkat** [comment]
This repository is for support on the npm CLI, not for packages belonging to it. If you need support on `webpack`, please head over to https://github.com/webpack/webpack. Cheers!
