### ISSUE TITLE
No compatible version found: npm@install

### ISSUE THREAD

**Issue by dagarint** [npm/npm#15117]
Hi!

npm is producing an incorrect install. I get error: No compatible version found: npm@install. 

I use Windows and Visual Studio Community 2015. Npm-debug.log is below.

Thank you.
Tomaž

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Web\\External\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Web\\External\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@3.3.4
3 info using node@v5.4.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly install normalizeTree
8 silly loadCurrentTree Finishing
9 silly loadIdealTree Starting
10 silly install loadIdealTree
11 silly cloneCurrentTree Starting
12 silly install cloneCurrentTreeToIdealTree
13 silly cloneCurrentTree Finishing
14 silly loadShrinkwrap Starting
15 silly install loadShrinkwrap
16 silly loadShrinkwrap Finishing
17 silly loadAllDepsIntoIdealTree Starting
18 silly install loadAllDepsIntoIdealTree
19 silly fetchNamedPackageData angular-cookie
20 silly mapToRegistry name angular-cookie
21 silly mapToRegistry using default registry
22 silly mapToRegistry registry https://registry.npmjs.org/
23 silly mapToRegistry uri https://registry.npmjs.org/angular-cookie
24 silly fetchNamedPackageData npm
25 silly mapToRegistry name npm
26 silly mapToRegistry using default registry
27 silly mapToRegistry registry https://registry.npmjs.org/
28 silly mapToRegistry uri https://registry.npmjs.org/npm
29 verbose request uri https://registry.npmjs.org/angular-cookie
30 verbose request no auth needed
31 info attempt registry request try #1 at 09:35:09
32 verbose request id 545ae3fa195276a0
33 verbose etag W/"56ba3d10-2834"
34 verbose lastModified Tue, 09 Feb 2016 19:25:04 GMT
35 http request GET https://registry.npmjs.org/angular-cookie
36 verbose request uri https://registry.npmjs.org/npm
37 verbose request no auth needed
38 info attempt registry request try #1 at 09:35:09
39 verbose etag W/"5840d038-599464"
40 verbose lastModified Fri, 02 Dec 2016 01:36:56 GMT
41 http request GET https://registry.npmjs.org/npm
42 http 304 https://registry.npmjs.org/angular-cookie
43 verbose headers { date: 'Fri, 02 Dec 2016 08:35:08 GMT',
43 verbose headers   via: '1.1 varnish',
43 verbose headers   'cache-control': 'max-age=300',
43 verbose headers   etag: 'W/"56ba3d10-2834"',
43 verbose headers   age: '0',
43 verbose headers   connection: 'keep-alive',
43 verbose headers   'x-served-by': 'cache-fra1223-FRA',
43 verbose headers   'x-cache': 'HIT',
43 verbose headers   'x-cache-hits': '1',
43 verbose headers   'x-timer': 'S1480667708.341427,VS0,VE1',
43 verbose headers   vary: 'Accept-Encoding' }
44 silly get cb [ 304,
44 silly get   { date: 'Fri, 02 Dec 2016 08:35:08 GMT',
44 silly get     via: '1.1 varnish',
44 silly get     'cache-control': 'max-age=300',
44 silly get     etag: 'W/"56ba3d10-2834"',
44 silly get     age: '0',
44 silly get     connection: 'keep-alive',
44 silly get     'x-served-by': 'cache-fra1223-FRA',
44 silly get     'x-cache': 'HIT',
44 silly get     'x-cache-hits': '1',
44 silly get     'x-timer': 'S1480667708.341427,VS0,VE1',
44 silly get     vary: 'Accept-Encoding' } ]
45 verbose etag https://registry.npmjs.org/angular-cookie from cache
46 verbose get saving angular-cookie to C:\Users\Spletna Vizija\AppData\Roaming\npm-cache\registry.npmjs.org\angular-cookie\.cache.json
47 http 304 https://registry.npmjs.org/npm
48 verbose headers { date: 'Fri, 02 Dec 2016 08:35:08 GMT',
48 verbose headers   via: '1.1 varnish',
48 verbose headers   'cache-control': 'max-age=300',
48 verbose headers   etag: 'W/"5840d038-599464"',
48 verbose headers   age: '139',
48 verbose headers   connection: 'keep-alive',
48 verbose headers   'x-served-by': 'cache-fra1251-FRA',
48 verbose headers   'x-cache': 'HIT',
48 verbose headers   'x-cache-hits': '2',
48 verbose headers   'x-timer': 'S1480667708.351459,VS0,VE0',
48 verbose headers   vary: 'Accept-Encoding' }
49 silly get cb [ 304,
49 silly get   { date: 'Fri, 02 Dec 2016 08:35:08 GMT',
49 silly get     via: '1.1 varnish',
49 silly get     'cache-control': 'max-age=300',
49 silly get     etag: 'W/"5840d038-599464"',
49 silly get     age: '139',
49 silly get     connection: 'keep-alive',
49 silly get     'x-served-by': 'cache-fra1251-FRA',
49 silly get     'x-cache': 'HIT',
49 silly get     'x-cache-hits': '2',
49 silly get     'x-timer': 'S1480667708.351459,VS0,VE0',
49 silly get     vary: 'Accept-Encoding' } ]
50 verbose etag https://registry.npmjs.org/npm from cache
51 verbose get saving npm to C:\Users\Spletna Vizija\AppData\Roaming\npm-cache\registry.npmjs.org\npm\.cache.json
52 silly resolveWithNewModule angular-cookie@4.1.0 checking installable status
53 silly cache add args [ 'angular-cookie@4.1.0', null ]
54 verbose cache add spec angular-cookie@4.1.0
55 silly cache add parsed spec Result {
55 silly cache add   raw: 'angular-cookie@4.1.0',
55 silly cache add   scope: null,
55 silly cache add   name: 'angular-cookie',
55 silly cache add   rawSpec: '4.1.0',
55 silly cache add   spec: '4.1.0',
55 silly cache add   type: 'version' }
56 silly addNamed angular-cookie@4.1.0
57 verbose addNamed "4.1.0" is a plain semver version for angular-cookie
58 silly mapToRegistry name angular-cookie
59 silly mapToRegistry using default registry
60 silly mapToRegistry registry https://registry.npmjs.org/
61 silly mapToRegistry uri https://registry.npmjs.org/angular-cookie
62 verbose addNameVersion registry:https://registry.npmjs.org/angular-cookie not in flight; fetching
63 silly fetchPackageMetaData Error: No compatible version found: npm@install
63 silly fetchPackageMetaData Valid install targets:
63 silly fetchPackageMetaData ["4.0.5","4.0.3","4.0.2","4.0.1","4.0.0","3.10.10","3.10.9","3.10.8","3.10.7","3.10.6","3.10.5","3.10.4","3.10.3","3.10.2","3.10.1","3.10.0","3.9.6","3.9.5","3.9.4","3.9.3","3.9.2","3.9.1","3.9.0","3.8.9","3.8.8","3.8.7","3.8.6","3.8.5","3.8.4","3.8.3","3.8.2","3.8.1","3.8.0","3.7.5","3.7.4","3.7.3","3.7.2","3.7.1","3.7.0","3.6.0","3.5.4","3.5.3","3.5.2","3.5.1","3.5.0","3.4.1","3.4.0","3.3.12","3.3.11","3.3.10","3.3.9","3.3.8","3.3.7","3.3.6","3.3.5","3.3.4","3.3.3","3.3.2","3.3.1","3.3.0","3.2.2","3.2.1","3.2.0","3.1.3","3.1.2","3.1.1","3.1.0","3.0.0","2.15.11","2.15.10","2.15.9","2.15.8","2.15.7","2.15.6","2.15.5","2.15.4","2.15.3","2.15.2","2.15.1","2.15.0","2.14.22","2.14.21","2.14.20","2.14.19","2.14.18","2.14.17","2.14.16","2.14.15","2.14.14","2.14.13","2.14.12","2.14.11","2.14.10","2.14.9","2.14.8","2.14.7","2.14.6","2.14.5","2.14.4","2.14.3","2.14.2","2.14.1","2.14.0","2.13.5","2.13.4","2.13.3","2.13.2","2.13.1","2.13.0","2.12.1","2.12.0","2.11.3","2.11.2","2.11.1","2.11.0","2.10.1","2.10.0","2.9.1","2.9.0","2.8.4","2.8.3","2.8.2","2.8.1","2.8.0","2.7.6","2.7.5","2.7.4","2.7.3","2.7.2","2.7.1","2.7.0","2.6.1","2.6.0","2.5.1","2.5.0","2.4.1","2.4.0","2.3.0","2.2.0","2.1.18","2.1.17","2.1.16","2.1.15","2.1.14","2.1.13","2.1.12","2.1.11","2.1.10","2.1.9","2.1.8","2.1.7","2.1.6","2.1.5","2.1.4","2.1.3","2.1.2","2.1.1","2.1.0","2.0.2","2.0.1","2.0.0","2.0.0-beta.3","2.0.0-beta.2","2.0.0-beta.1","2.0.0-beta.0","2.0.0-alpha-5","2.0.0-alpha.7","2.0.0-alpha.6.0","2.0.0-alpha.6","1.5.0-alpha-4","1.5.0-alpha-3","1.5.0-alpha-2","1.5.0-alpha-1","1.5.0-alpha-0","1.4.29","1.4.28","1.4.27","1.4.26","1.4.25","1.4.24","1.4.23","1.4.22","1.4.21","1.4.20","1.4.19","1.4.18","1.4.17","1.4.16","1.4.15","1.4.14","1.4.13","1.4.12","1.4.11","1.4.10","1.4.9","1.4.8","1.4.7","1.4.6","1.4.5","1.4.4","1.4.3","1.4.2","1.4.1","1.4.0","1.3.26","1.3.25","1.3.24","1.3.23","1.3.22","1.3.21","1.3.20","1.3.18","1.3.17","1.3.16","1.3.15","1.3.14","1.3.13","1.3.12","1.3.11","1.3.10","1.3.9","1.3.8","1.3.7","1.3.6","1.3.5","1.3.4","1.3.2","1.3.1","1.3.0","1.2.8000","1.2.32","1.2.31","1.2.30","1.2.28","1.2.27","1.2.25","1.2.24","1.2.23","1.2.22","1.2.21","1.2.20","1.2.19","1.1.71","1.1.70","1.1.25"]
63 silly fetchPackageMetaData
63 silly fetchPackageMetaData     at pickVersionFromRegistryDocument (C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\node_modules\npm\lib\fetch-package-metadata.js:146:16)
63 silly fetchPackageMetaData     at C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\node_modules\iferr\index.js:13:50
63 silly fetchPackageMetaData     at C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\node_modules\npm\lib\utils\pulse-till-done.js:19:8
63 silly fetchPackageMetaData     at saved (C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\node_modules\npm\lib\cache\caching-client.js:168:7)
63 silly fetchPackageMetaData     at C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\node_modules\npm\node_modules\graceful-fs\polyfills.js:210:7
63 silly fetchPackageMetaData     at FSReqWrap.oncomplete (fs.js:82:15)
63 silly fetchPackageMetaData  error for npm@install [Error: No compatible version found: npm@install
63 silly fetchPackageMetaData Valid install targets:
63 silly fetchPackageMetaData ["4.0.5","4.0.3","4.0.2","4.0.1","4.0.0","3.10.10","3.10.9","3.10.8","3.10.7","3.10.6","3.10.5","3.10.4","3.10.3","3.10.2","3.10.1","3.10.0","3.9.6","3.9.5","3.9.4","3.9.3","3.9.2","3.9.1","3.9.0","3.8.9","3.8.8","3.8.7","3.8.6","3.8.5","3.8.4","3.8.3","3.8.2","3.8.1","3.8.0","3.7.5","3.7.4","3.7.3","3.7.2","3.7.1","3.7.0","3.6.0","3.5.4","3.5.3","3.5.2","3.5.1","3.5.0","3.4.1","3.4.0","3.3.12","3.3.11","3.3.10","3.3.9","3.3.8","3.3.7","3.3.6","3.3.5","3.3.4","3.3.3","3.3.2","3.3.1","3.3.0","3.2.2","3.2.1","3.2.0","3.1.3","3.1.2","3.1.1","3.1.0","3.0.0","2.15.11","2.15.10","2.15.9","2.15.8","2.15.7","2.15.6","2.15.5","2.15.4","2.15.3","2.15.2","2.15.1","2.15.0","2.14.22","2.14.21","2.14.20","2.14.19","2.14.18","2.14.17","2.14.16","2.14.15","2.14.14","2.14.13","2.14.12","2.14.11","2.14.10","2.14.9","2.14.8","2.14.7","2.14.6","2.14.5","2.14.4","2.14.3","2.14.2","2.14.1","2.14.0","2.13.5","2.13.4","2.13.3","2.13.2","2.13.1","2.13.0","2.12.1","2.12.0","2.11.3","2.11.2","2.11.1","2.11.0","2.10.1","2.10.0","2.9.1","2.9.0","2.8.4","2.8.3","2.8.2","2.8.1","2.8.0","2.7.6","2.7.5","2.7.4","2.7.3","2.7.2","2.7.1","2.7.0","2.6.1","2.6.0","2.5.1","2.5.0","2.4.1","2.4.0","2.3.0","2.2.0","2.1.18","2.1.17","2.1.16","2.1.15","2.1.14","2.1.13","2.1.12","2.1.11","2.1.10","2.1.9","2.1.8","2.1.7","2.1.6","2.1.5","2.1.4","2.1.3","2.1.2","2.1.1","2.1.0","2.0.2","2.0.1","2.0.0","2.0.0-beta.3","2.0.0-beta.2","2.0.0-beta.1","2.0.0-beta.0","2.0.0-alpha-5","2.0.0-alpha.7","2.0.0-alpha.6.0","2.0.0-alpha.6","1.5.0-alpha-4","1.5.0-alpha-3","1.5.0-alpha-2","1.5.0-alpha-1","1.5.0-alpha-0","1.4.29","1.4.28","1.4.27","1.4.26","1.4.25","1.4.24","1.4.23","1.4.22","1.4.21","1.4.20","1.4.19","1.4.18","1.4.17","1.4.16","1.4.15","1.4.14","1.4.13","1.4.12","1.4.11","1.4.10","1.4.9","1.4.8","1.4.7","1.4.6","1.4.5","1.4.4","1.4.3","1.4.2","1.4.1","1.4.0","1.3.26","1.3.25","1.3.24","1.3.23","1.3.22","1.3.21","1.3.20","1.3.18","1.3.17","1.3.16","1.3.15","1.3.14","1.3.13","1.3.12","1.3.11","1.3.10","1.3.9","1.3.8","1.3.7","1.3.6","1.3.5","1.3.4","1.3.2","1.3.1","1.3.0","1.2.8000","1.2.32","1.2.31","1.2.30","1.2.28","1.2.27","1.2.25","1.2.24","1.2.23","1.2.22","1.2.21","1.2.20","1.2.19","1.1.71","1.1.70","1.1.25"]
63 silly fetchPackageMetaData ]
64 verbose get https://registry.npmjs.org/angular-cookie not expired, no request
65 silly cache afterAdd angular-cookie@4.1.0
66 verbose afterAdd C:\Users\Spletna Vizija\AppData\Roaming\npm-cache\angular-cookie\4.1.0\package\package.json not in flight; writing
67 verbose afterAdd C:\Users\Spletna Vizija\AppData\Roaming\npm-cache\angular-cookie\4.1.0\package\package.json written
68 silly rollbackFailedOptional Starting
69 silly rollbackFailedOptional Finishing
70 silly runTopLevelLifecycles Starting
71 silly runTopLevelLifecycles Finishing
72 silly install printInstalled
73 verbose stack Error: No compatible version found: npm@install
73 verbose stack Valid install targets:
73 verbose stack ["4.0.5","4.0.3","4.0.2","4.0.1","4.0.0","3.10.10","3.10.9","3.10.8","3.10.7","3.10.6","3.10.5","3.10.4","3.10.3","3.10.2","3.10.1","3.10.0","3.9.6","3.9.5","3.9.4","3.9.3","3.9.2","3.9.1","3.9.0","3.8.9","3.8.8","3.8.7","3.8.6","3.8.5","3.8.4","3.8.3","3.8.2","3.8.1","3.8.0","3.7.5","3.7.4","3.7.3","3.7.2","3.7.1","3.7.0","3.6.0","3.5.4","3.5.3","3.5.2","3.5.1","3.5.0","3.4.1","3.4.0","3.3.12","3.3.11","3.3.10","3.3.9","3.3.8","3.3.7","3.3.6","3.3.5","3.3.4","3.3.3","3.3.2","3.3.1","3.3.0","3.2.2","3.2.1","3.2.0","3.1.3","3.1.2","3.1.1","3.1.0","3.0.0","2.15.11","2.15.10","2.15.9","2.15.8","2.15.7","2.15.6","2.15.5","2.15.4","2.15.3","2.15.2","2.15.1","2.15.0","2.14.22","2.14.21","2.14.20","2.14.19","2.14.18","2.14.17","2.14.16","2.14.15","2.14.14","2.14.13","2.14.12","2.14.11","2.14.10","2.14.9","2.14.8","2.14.7","2.14.6","2.14.5","2.14.4","2.14.3","2.14.2","2.14.1","2.14.0","2.13.5","2.13.4","2.13.3","2.13.2","2.13.1","2.13.0","2.12.1","2.12.0","2.11.3","2.11.2","2.11.1","2.11.0","2.10.1","2.10.0","2.9.1","2.9.0","2.8.4","2.8.3","2.8.2","2.8.1","2.8.0","2.7.6","2.7.5","2.7.4","2.7.3","2.7.2","2.7.1","2.7.0","2.6.1","2.6.0","2.5.1","2.5.0","2.4.1","2.4.0","2.3.0","2.2.0","2.1.18","2.1.17","2.1.16","2.1.15","2.1.14","2.1.13","2.1.12","2.1.11","2.1.10","2.1.9","2.1.8","2.1.7","2.1.6","2.1.5","2.1.4","2.1.3","2.1.2","2.1.1","2.1.0","2.0.2","2.0.1","2.0.0","2.0.0-beta.3","2.0.0-beta.2","2.0.0-beta.1","2.0.0-beta.0","2.0.0-alpha-5","2.0.0-alpha.7","2.0.0-alpha.6.0","2.0.0-alpha.6","1.5.0-alpha-4","1.5.0-alpha-3","1.5.0-alpha-2","1.5.0-alpha-1","1.5.0-alpha-0","1.4.29","1.4.28","1.4.27","1.4.26","1.4.25","1.4.24","1.4.23","1.4.22","1.4.21","1.4.20","1.4.19","1.4.18","1.4.17","1.4.16","1.4.15","1.4.14","1.4.13","1.4.12","1.4.11","1.4.10","1.4.9","1.4.8","1.4.7","1.4.6","1.4.5","1.4.4","1.4.3","1.4.2","1.4.1","1.4.0","1.3.26","1.3.25","1.3.24","1.3.23","1.3.22","1.3.21","1.3.20","1.3.18","1.3.17","1.3.16","1.3.15","1.3.14","1.3.13","1.3.12","1.3.11","1.3.10","1.3.9","1.3.8","1.3.7","1.3.6","1.3.5","1.3.4","1.3.2","1.3.1","1.3.0","1.2.8000","1.2.32","1.2.31","1.2.30","1.2.28","1.2.27","1.2.25","1.2.24","1.2.23","1.2.22","1.2.21","1.2.20","1.2.19","1.1.71","1.1.70","1.1.25"]
73 verbose stack
73 verbose stack     at pickVersionFromRegistryDocument (C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\node_modules\npm\lib\fetch-package-metadata.js:146:16)
73 verbose stack     at C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\node_modules\iferr\index.js:13:50
73 verbose stack     at C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\node_modules\npm\lib\utils\pulse-till-done.js:19:8
73 verbose stack     at saved (C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\node_modules\npm\lib\cache\caching-client.js:168:7)
73 verbose stack     at C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\node_modules\npm\node_modules\graceful-fs\polyfills.js:210:7
73 verbose stack     at FSReqWrap.oncomplete (fs.js:82:15)
74 verbose cwd D:\Moji dokumenti\Visual Studio 2015\Projects\WebApplication40\WebApplication40
75 error Windows_NT 10.0.14393
76 error argv "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Web\\External\\node.exe" "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Web\\External\\node_modules\\npm\\bin\\npm-cli.js" "install"
77 error node v5.4.1
78 error npm  v3.3.4
79 error No compatible version found: npm@install
79 error Valid install targets:
79 error ["4.0.5","4.0.3","4.0.2","4.0.1","4.0.0","3.10.10","3.10.9","3.10.8","3.10.7","3.10.6","3.10.5","3.10.4","3.10.3","3.10.2","3.10.1","3.10.0","3.9.6","3.9.5","3.9.4","3.9.3","3.9.2","3.9.1","3.9.0","3.8.9","3.8.8","3.8.7","3.8.6","3.8.5","3.8.4","3.8.3","3.8.2","3.8.1","3.8.0","3.7.5","3.7.4","3.7.3","3.7.2","3.7.1","3.7.0","3.6.0","3.5.4","3.5.3","3.5.2","3.5.1","3.5.0","3.4.1","3.4.0","3.3.12","3.3.11","3.3.10","3.3.9","3.3.8","3.3.7","3.3.6","3.3.5","3.3.4","3.3.3","3.3.2","3.3.1","3.3.0","3.2.2","3.2.1","3.2.0","3.1.3","3.1.2","3.1.1","3.1.0","3.0.0","2.15.11","2.15.10","2.15.9","2.15.8","2.15.7","2.15.6","2.15.5","2.15.4","2.15.3","2.15.2","2.15.1","2.15.0","2.14.22","2.14.21","2.14.20","2.14.19","2.14.18","2.14.17","2.14.16","2.14.15","2.14.14","2.14.13","2.14.12","2.14.11","2.14.10","2.14.9","2.14.8","2.14.7","2.14.6","2.14.5","2.14.4","2.14.3","2.14.2","2.14.1","2.14.0","2.13.5","2.13.4","2.13.3","2.13.2","2.13.1","2.13.0","2.12.1","2.12.0","2.11.3","2.11.2","2.11.1","2.11.0","2.10.1","2.10.0","2.9.1","2.9.0","2.8.4","2.8.3","2.8.2","2.8.1","2.8.0","2.7.6","2.7.5","2.7.4","2.7.3","2.7.2","2.7.1","2.7.0","2.6.1","2.6.0","2.5.1","2.5.0","2.4.1","2.4.0","2.3.0","2.2.0","2.1.18","2.1.17","2.1.16","2.1.15","2.1.14","2.1.13","2.1.12","2.1.11","2.1.10","2.1.9","2.1.8","2.1.7","2.1.6","2.1.5","2.1.4","2.1.3","2.1.2","2.1.1","2.1.0","2.0.2","2.0.1","2.0.0","2.0.0-beta.3","2.0.0-beta.2","2.0.0-beta.1","2.0.0-beta.0","2.0.0-alpha-5","2.0.0-alpha.7","2.0.0-alpha.6.0","2.0.0-alpha.6","1.5.0-alpha-4","1.5.0-alpha-3","1.5.0-alpha-2","1.5.0-alpha-1","1.5.0-alpha-0","1.4.29","1.4.28","1.4.27","1.4.26","1.4.25","1.4.24","1.4.23","1.4.22","1.4.21","1.4.20","1.4.19","1.4.18","1.4.17","1.4.16","1.4.15","1.4.14","1.4.13","1.4.12","1.4.11","1.4.10","1.4.9","1.4.8","1.4.7","1.4.6","1.4.5","1.4.4","1.4.3","1.4.2","1.4.1","1.4.0","1.3.26","1.3.25","1.3.24","1.3.23","1.3.22","1.3.21","1.3.20","1.3.18","1.3.17","1.3.16","1.3.15","1.3.14","1.3.13","1.3.12","1.3.11","1.3.10","1.3.9","1.3.8","1.3.7","1.3.6","1.3.5","1.3.4","1.3.2","1.3.1","1.3.0","1.2.8000","1.2.32","1.2.31","1.2.30","1.2.28","1.2.27","1.2.25","1.2.24","1.2.23","1.2.22","1.2.21","1.2.20","1.2.19","1.1.71","1.1.70","1.1.25"]
80 error If you need help, you may report this error at:
80 error     <https://github.com/npm/npm/issues>
81 verbose exit [ 1, true ]

**Comment by zkat** [comment]
It looks like you have a dependency that says `"npm": "install"` in your `package.json`. What does your `"dependencies"` section in that file look like? :)

**Comment by dagarint** [comment]
"dependencies": {
    "@angular/common": "2.0.0-rc.6",
    "@angular/compiler": "2.0.0-rc.6",
    "@angular/core": "2.0.0-rc.6",
    "@angular/forms": "2.0.0-rc.6",
    "@angular/http": "2.0.0-rc.6",
    "@angular/platform-browser": "2.0.0-rc.6",
    "@angular/platform-browser-dynamic": "2.0.0-rc.6",
    "@angular/router": "3.0.0-rc.2",
    "@angular/upgrade": "2.0.0-rc.6",

    "systemjs": "0.19.27",
    "core-js": "^2.4.1",
    "reflect-metadata": "^0.1.3",
    "rxjs": "5.0.0-beta.11",
    "zone.js": "^0.6.17",

    "angular2-in-memory-web-api": "0.0.18",
    "bootstrap": "^3.3.6",
    "npm": "install",
    "angular-cookie": "4.1.0"
   

  },

**Comment by zkat** [comment]
remove the line that says `"npm": "install"` and try again

**Comment by dagarint** [comment]
Hello, 
it's working.  Thank you for your help.
All the best.
Tomaž
