### ISSUE TITLE
For typescript2 projects npm install should install the relevant `@types` package as well

### ISSUE THREAD

**Issue by k0pernikus** [npm/npm#15119]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's the feature?

I am using typescript and install libraries via `npm`. For typescript, one needs typings and since typescript2, it is possible to use the `@types/{packageName}`. So if I want to install a library, say `nock`, I have to type:

    npm i --save nock @types/nock

It would be nice to be able to tell npm, maybe by a setting in `.npmrc` that my project is a typescript one and hence:

    npm i --save nock

would be enough go get both the package and its typings. And removing them would delete both as well.

If no `@types/{package} is found, then simply stating a warning would be enough. (Bonus point for generating a simple typescript defintion file that just declares the module would be awesome but I guess a bit out of scope). In the end, `npm` should just manage packages.)

#### What problem is the feature intended to solve?

Easier dependency handling for typescript projects.

#### Is the absence of this feature blocking you or your team? If so, how?

Oh hell no. It's a nice to have, yet it currently annoys me to an extend that I am writing this issue.

#### Is this feature similar to an existing feature in another tool?

I don't know.

#### Is this a feature you're prepared to implement, with support from the npm CLI team?

Yes, yet not currently. Maybe in the beginning of 2017 and also depending on the scope of this.

**Comment by lholmquist** [comment]
This just seems like adding in unneeded bloat.    Once you type that `npm install  .... --save` once you never have to type it again,  and the keystrokes you save, would be wasted on the creation of the .npmrc file(if thats where this type of config would go).
