### ISSUE TITLE
npm run build:client npm ERR!

### ISSUE THREAD

**Issue by sherrynazih** [npm/npm#15110]
npm run build:client
npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/Cellar/node/7.2.0/bin/node" "/usr/local/bin/npm" "run" "build:client"
npm ERR! node v7.2.0
npm ERR! npm  v3.10.9

npm ERR! missing script: build:client
npm ERR! 

the same with the server build

**Comment by KenanY** [comment]
@sherrynazih Make sure you have a `"build:client"` script defined in your `package.json`. Docs: <https://docs.npmjs.com/misc/scripts>

**Comment by sherrynazih** [comment]
that was solved thank u but appeared another problem when running webpack -w
ERROR in ./app/components/Main.js
Module build failed: SyntaxError: /Users/sherry/Documents/Eventtus/egghead/app/components/Main.js: Expecting Unicode escape sequence \uXXXX (9:10)
   7 |         <div>
   8 |           Hello World
>  9 |         <\div>
     |           ^
  10 |       )
  11 |     }
  12 |   });

and that's my code:
var React = require('react');
  var ReactDOM = require('react-dom');

  var Main = React.createClass({
    render: function(){
      return (
        <div>
          Hello World
        </div>
      )
    }
  });

  ReactDOM.render(<Main />, document.getElementByID('app'))

**Comment by sherrynazih** [comment]
Sorry that's my code:
var React = require('react');
  var ReactDOM = require('react-dom');

  var Main = React.createClass({
    render: function(){
      return (
        <div>
          Hello World
        </div>
      )
    }
  });

  ReactDOM.render(<Main />, document.getElementByID('app'))

**Comment by KenanY** [comment]
@sherrynazih Sorry, this issue tracker is for bugs/feature-requests pertaining to `npm`.
