### ISSUE TITLE
npm install is crashing/error message

### ISSUE THREAD

**Issue by rstephen1984** [npm/npm#15126]
I've been unable to resolve an issue I'm with npm install on my mac. Every time I run `npm.install`, I get string of error messages.

Below is the string of error messages I receive when I run `npm.install`:

<pre>
npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/Cellar/node/7.1.0/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.1.0
npm ERR! npm  v4.0.3
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: normalize.css@undefined5.0.0
npm ERR! notarget Valid install targets:
npm ERR! notarget 5.0.0, 4.2.0, 4.1.1, 4.1.0, 4.0.0, 3.0.3, 3.0.2, 3.0.1, 0.0.1
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'Owner'
npm ERR! notarget 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Owner/npm-debug.log
</pre>

**Comment by Charlotteis** [comment]
Hi @rstephen1984, 

what does your package.json look like?

It's trying to install a version of normalize that has been set as "undefined5.0.0" which is not a valid version.

**Comment by sultan880** [comment]
I got the same issue when I'm trying to install ionic by using this command in MAC.

`$ npm install -g ionic cordova`

`npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "ionic" "cordova"
npm ERR! node v7.2.0
npm ERR! npm  v3.10.9
npm ERR! path /Users/sultan/.npm-global/lib/node_modules/cordova
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/Users/sultan/.npm-global/lib/node_modules/cordova'
npm ERR!  { Error: EACCES: permission denied, access '/Users/sultan/.npm-global/lib/node_modules/cordova'
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/Users/sultan/.npm-global/lib/node_modules/cordova' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/sultan/npm-debug.log`

**Comment by legodude17** [comment]
@sultan880, that is _not_ the same issue, but I would suggest you check the permissions for `/Users/sultan/.npm-global/lib/node_modules`, or upgrade to `4.1.1` and run `npm doctor`.

**Comment by sultan880** [comment]
@legodude17, my issue has been resolved by following your comments.

Thanks :)

**Comment by KenanY** [comment]
Closing due to no reply from @rstephen1984.
