### ISSUE TITLE
angular-cli installation via npm error

### ISSUE THREAD

**Issue by engrabid411** [npm/npm#15123]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Abid Nawaz\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'anglular-cli@webpack' ]
2 info using npm@4.0.3
3 info using node@v7.2.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData anglular-cli@webpack
8 silly fetchNamedPackageData anglular-cli
9 silly mapToRegistry name anglular-cli
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'anglular-cli',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'anglular-cli',
12 silly mapToRegistry   name: 'anglular-cli',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/anglular-cli
14 verbose request uri https://registry.npmjs.org/anglular-cli
15 verbose request no auth needed
16 info attempt registry request try #1 at 11:51:04 PM
17 verbose request id 4a74a46e8feb8fc5
18 http request GET https://registry.npmjs.org/anglular-cli
19 http 404 https://registry.npmjs.org/anglular-cli
20 verbose headers { 'content-type': 'application/json',
20 verbose headers   'cache-control': 'max-age=0',
20 verbose headers   'content-length': '2',
20 verbose headers   'accept-ranges': 'bytes',
20 verbose headers   date: 'Fri, 02 Dec 2016 18:54:24 GMT',
20 verbose headers   via: '1.1 varnish',
20 verbose headers   age: '0',
20 verbose headers   connection: 'keep-alive',
20 verbose headers   'x-served-by': 'cache-lhr6350-LHR',
20 verbose headers   'x-cache': 'MISS',
20 verbose headers   'x-cache-hits': '0',
20 verbose headers   'x-timer': 'S1480704863.848461,VS0,VE784',
20 verbose headers   vary: 'Accept-Encoding' }
21 silly get cb [ 404,
21 silly get   { 'content-type': 'application/json',
21 silly get     'cache-control': 'max-age=0',
21 silly get     'content-length': '2',
21 silly get     'accept-ranges': 'bytes',
21 silly get     date: 'Fri, 02 Dec 2016 18:54:24 GMT',
21 silly get     via: '1.1 varnish',
21 silly get     age: '0',
21 silly get     connection: 'keep-alive',
21 silly get     'x-served-by': 'cache-lhr6350-LHR',
21 silly get     'x-cache': 'MISS',
21 silly get     'x-cache-hits': '0',
21 silly get     'x-timer': 'S1480704863.848461,VS0,VE784',
21 silly get     vary: 'Accept-Encoding' } ]
22 silly fetchPackageMetaData Error: Registry returned 404 for GET on https://registry.npmjs.org/anglular-cli
22 silly fetchPackageMetaData     at makeError (C:\Users\Abid Nawaz\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-client\lib\request.js:302:12)
22 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (C:\Users\Abid Nawaz\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-client\lib\request.js:280:14)
22 silly fetchPackageMetaData     at Request._callback (C:\Users\Abid Nawaz\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-client\lib\request.js:210:14)
22 silly fetchPackageMetaData     at Request.self.callback (C:\Users\Abid Nawaz\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:186:22)
22 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
22 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
22 silly fetchPackageMetaData     at Request.<anonymous> (C:\Users\Abid Nawaz\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:1081:10)
22 silly fetchPackageMetaData     at emitOne (events.js:96:13)
22 silly fetchPackageMetaData     at Request.emit (events.js:188:7)
22 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (C:\Users\Abid Nawaz\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:1001:12)
22 silly fetchPackageMetaData  error for anglular-cli@webpack { Error: Registry returned 404 for GET on https://registry.npmjs.org/anglular-cli
22 silly fetchPackageMetaData     at makeError (C:\Users\Abid Nawaz\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-client\lib\request.js:302:12)
22 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (C:\Users\Abid Nawaz\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-client\lib\request.js:280:14)
22 silly fetchPackageMetaData     at Request._callback (C:\Users\Abid Nawaz\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-client\lib\request.js:210:14)
22 silly fetchPackageMetaData     at Request.self.callback (C:\Users\Abid Nawaz\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:186:22)
22 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
22 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
22 silly fetchPackageMetaData     at Request.<anonymous> (C:\Users\Abid Nawaz\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:1081:10)
22 silly fetchPackageMetaData     at emitOne (events.js:96:13)
22 silly fetchPackageMetaData     at Request.emit (events.js:188:7)
22 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (C:\Users\Abid Nawaz\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:1001:12) pkgid: 'anglular-cli', statusCode: 404, code: 'E404' }
23 silly rollbackFailedOptional Starting
24 verbose stack TypeError: Cannot read property 'path' of null
24 verbose stack     at Installer.rollbackFailedOptional (C:\Users\Abid Nawaz\AppData\Roaming\npm\node_modules\npm\lib\install.js:505:29)
24 verbose stack     at Array.<anonymous> (C:\Users\Abid Nawaz\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
24 verbose stack     at LOOP (C:\Users\Abid Nawaz\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
24 verbose stack     at C:\Users\Abid Nawaz\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:18:7
24 verbose stack     at C:\Users\Abid Nawaz\AppData\Roaming\npm\node_modules\npm\lib\install.js:331:5
24 verbose stack     at Array.<anonymous> (C:\Users\Abid Nawaz\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
24 verbose stack     at LOOP (C:\Users\Abid Nawaz\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
24 verbose stack     at chain (C:\Users\Abid Nawaz\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
24 verbose stack     at C:\Users\Abid Nawaz\AppData\Roaming\npm\node_modules\npm\lib\install.js:288:5
24 verbose stack     at C:\Users\Abid Nawaz\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:16:22
25 verbose cwd C:\Users\Abid Nawaz
26 error Windows_NT 10.0.14393
27 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Abid Nawaz\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "anglular-cli@webpack"
28 error node v7.2.0
29 error npm  v4.0.3
30 error Cannot read property 'path' of null
31 error If you need help, you may report this error at:
31 error     <https://github.com/npm/npm/issues>
32 verbose exit [ 1, true ]

[npm-debug.txt](https://github.com/npm/npm/files/627988/npm-debug.txt)

**Comment by KenanY** [comment]
This is probably caused by the typo in the package name: "anglular-cli" instead of "angular-cli". Also, you probably should have a space instead of the `@` symbol between the two packages.
