### ISSUE TITLE
global npm cache directory if user is root?

### ISSUE THREAD

**Issue by ORESoftware** [npm/npm#15130]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

There's no problem at the moment - I just have a question. The npm cache for a given user is located at ~/.npm. If the user is the root user, does NPM also put a cache folder at ~/.npm? Just curious if that's the case, and if there is anything different about the npm cache system depending on whether the user is root or not. Thanks for any info!

**Comment by legodude17** [comment]
I am guessing that it would just put it wherever the root user's home directory is. Happy Coding!

**Comment by ORESoftware** [comment]
@legodude17 yeah, just wondering if perhaps NPM does something different if the user is the root user, it's certainly possible, if you find out, please lmk, will be combing the docs in the meantime
