### ISSUE TITLE
Coveralls has no source available 

### ISSUE THREAD

**Issue by ndelangen** [npm/npm#15134]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?

Coveralls has no access to the github source. It appears like the owner needs to re-authenticate:
https://coveralls.io/builds/9108066/source?filename=lib%2Futils%2Fcompletion%2Finstalled-deep.js

#### How can the CLI team reproduce the problem?

1. Open Coveralls
2. Click on a file

### supporting information:

> SOURCE NOT AVAILABLE
The owner of this repo needs to re-authorize with github; their OAuth credentials are no longer valid so the file cannot be pulled from the github API.

<img width="1112" alt="screen shot 2016-12-04 at 09 31 51" src="https://cloud.githubusercontent.com/assets/3070389/20864940/8d6b4b56-ba04-11e6-88df-e331cdc14f28.png">

**Comment by zkat** [comment]
Hey @ndelangen thanks for pointing this out! @othiym23 is the one with credentials to that afaik, so I'm assigning it to him and he'll get around to it at some point. Cheers!

**Comment by othiym23** [comment]
So this is what I see:

<img width="1234" alt="2016-12-05 18-08-20 6e5jy" src="https://cloud.githubusercontent.com/assets/418097/20910375/f095c686-bb15-11e6-8c35-c9e164688333.png">

I don't _think_ any of us changed our OAuth settings. Are you still unable to see source today?

**Comment by ndelangen** [comment]
Huh!? It still displays the same as OP for me: it does not display source for me.

**Comment by ndelangen** [comment]
OK, got it working by **logging in** to coveralls, when I log out I get the message again.

**Comment by othiym23** [comment]
It's not clear to me why coveralls.io cares about auth in the first place, given that npm/npm is a public repo. Nevertheless, I'be now done all the things that I can do, including reaurgorizing myself with GitHub via coveralls and disabling and re-enabling coveralls. This is starting to feel like a bug i'm on the coveralls side, because it doesn't follow from the error message y'all are eeeing that logging in to coveralls should affect the source's visibility.

**Comment by zkat** [comment]
(for future reference, I saw this issue as well)

**Comment by legodude17** [comment]
I get this error too. Has anyone contacted the coveralls folks?

**Comment by ndelangen** [comment]
I have send them a tweet, I have no official way of contacting them.

**Comment by iarna** [comment]
Taking this off the `next` milestone as it doesn't have anything actionable remaining for us to do.
