### ISSUE TITLE
Safety / performance of parallel installs

### ISSUE THREAD

**Issue by ORESoftware** [npm/npm#15137]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?

This is a question about safety / performance of parallel installs, say I have this:

```console
mkdir foo
cd foo
npm install --save foo &
npm install --save bar &
npm install --save baz &
wait
```

I believe that bash is correct, but just in case, here is the JS version:

```js
const async = require('async')
const cp = require('child_process');

async.each(['foo','bar','baz'], function(item, cb){
  const n = cp.spawn('npm',['install','--save',item])
  n.on('close',cb);
}, function(err){
     //done
});
```

I assume this is safe, but just never really known for sure, are there any caveats to be worried about? Perhaps better to just run everything in series since it maybe be no more performant to run in parallel?

 I assume NPM does safeguard against parallel installations, however?

**Comment by the1mills** [comment]
I tried this, running many installs of different deps in parallel, npm was not happy, nobody was happy. parallel installs are probably very bad idea, better to let npm handle the optimization in one command. however was just curious about the safety of this. seems unsafe too.

**Comment by ORESoftware** [comment]
I think the best thing that NPM could do in this scenario is introduce a lock (lock file) for each node_modules directory. I am not sure if yarnpkg does this with their yarn.lock file, but maybe that's what they are doing. The lock file would work in this case:

```
npm install --save foo &  # 1
npm install --save bar &  # 2
npm install --save baz &  # 3
```

but I suppose you would *not* be guaranteed that the the first (#1) command would acquire the lock first.

**Comment by ORESoftware** [comment]
definitely still interested in have safe parallel NPM installs be supported NPM itself...otherwise as a library author I have to control running only one npm install command at a time

**Comment by ORESoftware** [comment]
Just FYI, Yarn seems to handle this problem with a flag called --mutex

https://github.com/yarnpkg/yarn/issues/2146

**Comment by legodude17** [comment]
You could just do `npm install --save pkgs.join(' ')`

**Comment by ORESoftware** [comment]
yeah, but the npm install requests may come in at separate times, it's for a library, I don't really have a lot of control about when and how many, so I have to implement an install queue in my postinstall script, all I am saying is that it would be nice if npm handled it (if npm does not handle it already).

In my tests, if I do:

```console
npm install --save foo &  # 1
npm install --save bar &  # 2
npm install --save baz &  # 3
wait
```
it results in bad news, so it looks like NPM does not handle this well
