### ISSUE TITLE
npm update should do an install if dep is not installed yet?

### ISSUE THREAD

**Issue by the1mills** [npm/npm#15138]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

`npm update foo`, will not install foo if foo is not installed already. This means I, the developer, have to write logic to check if the dependency is there or not

```js

//pseudocode

if(foo is there){
  npm update foo
}
else{
  npm install foo
}
```

_why doesn't npm update, install the dep if it's not there? is there a flag/option for "npm update" to install if the dep does not exist?_ 

#### How can the CLI team reproduce the problem?

`mkdir foo && cd foo && npm update express`

there will be no node_modules directory installed into the foo directory.

**Comment by the1mills** [comment]
the problem I am having is that 

`npm install foo@latest`

is acting like

`npm install foo --force`

whereby even if foo is at the latest version locally, it will still force the install, that seems wrong.
this is causing the need for me to conditionally call update instead of install.

**Comment by legodude17** [comment]
@the1mills your second comment doesn't seem related to your first one.
