### ISSUE TITLE
confused about npm's local installation philosophy

### ISSUE THREAD

**Issue by the1mills** [npm/npm#15131]
I am confused by what NPM is doing!

I know this question comes up again and again, but I have never heard a good answer. I have been using Node.js since early 2014 and have never fully understood the philosophy to install dependencies locally to a project. Why not install all versions of all dependencies in one folder? That way you don't have the same version of the same dependency in multiple places on disk? It would at the very least save disk space. But it would also save developer time because you wouldn't have to wait for files to be copied to the local project. Nevertheless, I am sure there are a few good reasons for NPM's design choice. Is there anywhere on the internet that provides a few definitive answers, perhaps from Isaacs himself? Trust me I have read so many articles, NOBODY has said something that has made me understand the reasoning. I am willing to be enlightened! Thanks.

The reason I ask the question: I have a library X and I want to have Babel, Istanbul, Express as dependencies. However, these deps are quite large, and people will complain about the download time and the size on disk (yes I know about Yarn). Ideally, for the same versions of {Express, Babel, Istanbul, etc}, NPM could point to a single location on disk where they are installed, instead of re-writing them to the local project.

**Comment by legodude17** [comment]
This is a) what the cache is for, and b) has already been requested in a different way.
Also, Babel and Istanbul should be devDependencies.
