### ISSUE TITLE
fireui auth web not showing.

### ISSUE THREAD

**Issue by Devaraj29** [npm/npm#15139]
#### I'm opening this issue because:

I wanted to use firebaseui auth in my web.But its not working. after run the index.html file its showing loading...

#### How can the CLI team reproduce the problem?

here is my npm-debug file.

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'public_html' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 verbose stack Error: missing script: public_html
4 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:151:19)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:61:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:356:5
4 verbose stack     at checkBinReferences_ (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:320:45)
4 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:354:3)
4 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:124:5)
4 verbose stack     at ReadFileContext.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:295:20)
4 verbose stack     at ReadFileContext.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16)
4 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:365:13)
5 verbose cwd C:\Users\Devaraj\Documents\NetBeansProjects\FYP2\public_html
6 error Windows_NT 10.0.14393
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "public_html"
8 error node v6.9.1
9 error npm  v3.10.8
10 error missing script: public_html
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

Please help thank you in .

**Comment by KenanY** [comment]
```
Error: missing script: public_html
```

@Devaraj29 Make sure you have a `"public_html"` script in your `package.json` before trying to run it. Hopefully the following docs help:

  - https://docs.npmjs.com/cli/run-script
  - https://docs.npmjs.com/misc/scripts
