### ISSUE TITLE
Can't install ng-animate using npm

### ISSUE THREAD

**Issue by bitSurfer151093** [npm/npm#15132]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [X ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I am trying to install angular animate using this command [ npm install --save angular-animate@X.Y.Z ], but can't doing it.
[npm-debug.log.zip](https://github.com/npm/npm/files/629219/npm-debug.log.zip)

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@bitSurfer151093 Can you upload the `npm-debug.log` file to <https://gist.github.com/> and post the link here instead of zipping it up?

**Comment by bitSurfer151093** [comment]
Hello,

Here is the link to the log file.

https://gist.github.com/bitSurfer151093/c181541546c96ec30989ddad3297d74a <https://gist.github.com/bitSurfer151093/c181541546c96ec30989ddad3297d74a>

**Comment by KenanY** [comment]
@bitSurfer151093 You need to replace `X.Y.Z` with a valid [semver range](https://github.com/npm/node-semver). `npm` has no idea what version you want it to install. Closing since this is expected and intentional behavior.
