### ISSUE TITLE
Feature request/question - Optional dependencies on a case-by-case basis

### ISSUE THREAD

**Issue by ORESoftware** [npm/npm#15135]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?

there is nothing really going wrong  - this is a question to see if this feature exists, and if the feature does not exist, this is a feature request! :)

so NPM allows for optional dependencies -   the syntax is like so:

```json
"dependencies" : {
   "foo": "1.2.3",
   "zoom": "4.5.3"
},
"devDependencies" : {
    "bar": "2.3.2"
},
"optionalDependencies" :{
    "baz": "1.4.22"
}
```

what I am looking to do is conditionally make dependencies optional. Such that I could make `foo` or `zoom` optional. A command line argument, let's call it "omit" would be sufficient in my use case, e.g.:

`npm install <my-package> --omit foo --omit zoom`

That's the functionality I am looking for. My use case is not a common one, but I can explain it if you want!

also, as an aside, in the docs it says:

> "Entries in optionalDependencies will override entries of the same name in dependencies, so it's usually best to only put in one place."

I actually don't know what that means

**Comment by legodude17** [comment]
I would suggest putting the doc issue in a different issue.

**Comment by ORESoftware** [comment]
Re: the docs issue, I think it means that optionalDependencies entries take precedence over dependencies so if looks like this:

```json
"dependencies" : {
   "foo": "1.2.3",
},
"optionalDependencies" :{
   "foo": "1.2.3",
    "baz": "1.4.22"
}

```

foo is then an optional dependency. Not sure what would happen if foo were also an entry in devDependencies, and don't get me started with peer dependencies, which I don't understand yet.
