### ISSUE TITLE
NPM causes NVM to be slow

### ISSUE THREAD

**Issue by martinheidegger** [npm/npm#15149]
#### I'm opening this issue because:

I have been looking into https://github.com/creationix/nvm/issues/1277 in order to figure out why the nvm is so slow to start. In my research I figured that `npm` is the slowest part of `npm`. Here I want to share my findings in the hope to spark ideas to improve the speed of `nvm`/`npm` for a better experience.

#### What's going wrong?

`nvm` takes almost 3 seconds to start up. Which is very annoying if you put `nvm` in the `.bashrc` or `.zshrc` which means it gets executed at every new tab, or login.

Tests for the performance `nvm` showed that most operations are quick but for a few tasks it has to use `npm` which makes it slow. Particularly interesting is `npm config get prefix` which - _once called_ - consumes 0.5 seconds itself in the test environment. 

#### How can the CLI team reproduce the problem?

There is a forked branch with performance tests (written to `timings.txt` in the `$NVM_DIR`) available here: https://github.com/martinheidegger/nvm/tree/debug/performance

By running nvm from that branch you should get a list of places where `nvm` is slow. It is a rough tests but by my estimates almost 80% of the startup performance of `nvm` are caused by calling `npm` scripts. 

I also prepared a test for the performance of `npm config get prefix` with explanations in the readme.
https://gist.github.com/martinheidegger/32d00e90e0163a22a4ffc78df796001e

**Comment by KenanY** [comment]
Duplicate of https://github.com/npm/npm/issues/14458, perhaps.

**Comment by martinheidegger** [comment]
😅 Thank you for pointing that out @KenanY my fault, I will post my findings there.
