### ISSUE TITLE
npm install failure

### ISSUE THREAD

**Issue by shaowin16** [npm/npm#15155]
Now I met a problem when i am a script execution "npm install -g yo generator-hubot",
the detail is here:
![image](https://cloud.githubusercontent.com/assets/17706777/20953317/a5dcc438-bc6d-11e6-8de1-1bf7dfc7f869.png)

the npm-debug.log:
![image](https://cloud.githubusercontent.com/assets/17706777/20953562/a08bfc5e-bc6f-11e6-9ec7-83f0d6b7bc34.png)

**Comment by shaowin16** [comment]
Now I met a problem when i am a script execution "npm install -g yo generator-hubot",
the detail is here:
![image](https://cloud.githubusercontent.com/assets/17706777/20953317/a5dcc438-bc6d-11e6-8de1-1bf7dfc7f869.png)

the npm-debug.log:
![image](https://cloud.githubusercontent.com/assets/17706777/20953562/a08bfc5e-bc6f-11e6-9ec7-83f0d6b7bc34.png)

**Comment by legodude17** [comment]
Do you use a proxy or VPN?

**Comment by zkat** [comment]
Closing as a duplicate of https://github.com/npm/npm/issues/14626
