### ISSUE TITLE
Feature request : npm run to prompt which script to run

### ISSUE THREAD

**Issue by ndelangen** [npm/npm#15154]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's the feature?

```
npm run
```
Will currently output a list of scripts a user could run. For a random repo of mine that would look like this: 
```
➜  awesome-repo git:(master) ✗ npm run
Lifecycle scripts included in styled-components:
  start
    react-scripts start
  test
    react-scripts test --env=jsdom

available via `npm run-script`:
  build
    react-scripts build
  eject
    react-scripts eject
  storybook
    start-storybook -p 9009 -s public
  build-storybook
    build-storybook -s public
  lint:css
    stylelint './src/**/*.js'
  test-storybook
    NODE_ENV=development storyshots
```

I feel like this DX can be improved upon.

![demo gif](http://i.imgur.com/ZjjQ7Vi.gif?1)
https://github.com/ruyadorno/ntl

The feature is that running `npm run` would prompt the user which script to run, listing the options.

#### What problem is the feature intended to solve?

Exploring what scripts can be run and easily run one.

#### Is the absence of this feature blocking you or your team? If so, how?

No

#### Is this feature similar to an existing feature in another tool?

Yes, https://github.com/ruyadorno/ntl

#### Is this a feature you're prepared to implement, with support from the npm CLI team?

Yes, I'm sure @ruyadorno would like to see his awesome work be integrated into npm?

**Comment by matthewoates** [comment]
Great idea. I've thought about this before, and have also had the impulse to allow a description for each task.

I see a few ways of doing this:

- Simply use bash comments. eg:
```
scripts: {
  "run": "node server.js # Run server.js"
}
```

- Including comments in a top level key in `package.json`. Potential for dead comments here though
- Invent yet another config file

**Comment by ndelangen** [comment]
Concerning comments in JSON, this is something that is specifically not allowed in the spec.
To the great dismay of every developer who has ever edited a JSON file. It's a sore that makes me write `.js` files instead of `.json` files, even if It's actually pure data.

In a perfect world we'd all just switch over to use [JSON5](http://json5.org/). But alas we have to deal with the fact JSON is a data format, and not a configuration file format, yet we all use it as a configuration file format anyway 😶. /rant

I'm not seriously suggesting switching `package.json` to be JSON5, because for obvious backwards-compatibility issues that could never happen. Or do you see some way?

---

Regarding the proposed feature, is a PR for me or @ruyadorno welcome? If that would not include a description?

**Comment by matthewoates** [comment]
No, bash comments. This works as-is

Instead of:
```
{
  scripts: "run": "node server.js"
}
```

do:
```
{
  scripts: "run": "node server.js # some comment. this is still valid json, because this is just a string. It is also still valid bash"
}
```

**Comment by ruyadorno** [comment]
@ndelangen thanks for bringing up the idea, I find it really awesome that you think **ntl** is an idea worth making it's way up to standard **npm** 😄 

TBH I'm very skeptical about the chances of it happening, it's been almost 2 months since you open the issue and we didn't even got a reply from the members of the org.

It's always a difficult decision to add new features to a product, specially one as critical as **npm**. Adding this new feature would mean adding tons of dependencies, not to mention all the extra complexity to the codebase and the long-time support that will have to be provided. All that to say that I do understand if they refuse to even consider adding it.

If it happens that I'm completely wrong about it and there's traction for **ntl** to become part of the core **npm** I'll gladly volunteer to work on a PR to make that happen.

**Comment by ruyadorno** [comment]
@matthewoates the bash comments idea is brilliant 👍  for me it seems to be a very good solution that was hidden in plain sight all along, we were discussing much more complex manners to achieve the same result: https://github.com/ruyadorno/ntl/issues/4
