### ISSUE TITLE
Scoped Package install 404 Not Found Error

### ISSUE THREAD

**Issue by daltongriner** [npm/npm#15152]
#### I'm opening this issue because:

  - [x] npm is doing something I don't understand.

#### What's going wrong?

I am able to publish a scoped package to Artifactory.  For example npm publish @scope/packagename works and creates a repo.  When I try to install that same package (npm install @scope/packagename) I get a 404 Not Found Error.

#### Debug log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node4-lts/4.6.2/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '@acres/acresmetajs' ]
2 info using npm@2.15.9
3 info using node@v4.6.2
4 verbose install initial load of /Users/grinerd/Documents/Code/scopedacresmetajs/package.json
5 verbose readDependencies loading dependencies from /Users/grinerd/Documents/Code/scopedacresmetajs/package.json
6 silly cache add args [ '@acres/acresmetajs', null ]
7 verbose cache add spec @acres/acresmetajs
8 silly cache add parsed spec Result {
8 silly cache add   raw: '@acres/acresmetajs',
8 silly cache add   scope: '@acres',
8 silly cache add   name: '@acres/acresmetajs',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: 'latest',
8 silly cache add   type: 'tag' }
9 silly addNamed @acres/acresmetajs@latest
10 verbose addNamed "latest" is being treated as a dist-tag for @acres/acresmetajs
11 info addNameTag [ '@acres/acresmetajs', 'latest' ]
12 silly mapToRegistry name @acres/acresmetajs
13 silly mapToRegistry scope (from package name) @acres
14 silly mapToRegistry registry https://artifacts.amirsys-int.com/artifactory/api/npm/npm-local/
15 silly mapToRegistry data Result {
15 silly mapToRegistry   raw: '@acres/acresmetajs',
15 silly mapToRegistry   scope: '@acres',
15 silly mapToRegistry   name: '@acres/acresmetajs',
15 silly mapToRegistry   rawSpec: '',
15 silly mapToRegistry   spec: 'latest',
15 silly mapToRegistry   type: 'tag' }
16 silly mapToRegistry uri https://artifacts.amirsys-int.com/artifactory/api/npm/npm-local/@acres%2facresmetajs
17 verbose addNameTag registry:https://artifacts.amirsys-int.com/artifactory/api/npm/npm-local/@acres%2facresmetajs not in flight; fetching
18 verbose request uri https://artifacts.amirsys-int.com/artifactory/api/npm/npm-local/@acres%2facresmetajs
19 verbose request always-auth set; sending authorization
20 info attempt registry request try #1 at 9:57:12 AM
21 verbose request id a04e9be59219fcc6
22 http request GET https://artifacts.amirsys-int.com/artifactory/api/npm/npm-local/@acres%2facresmetajs
23 http 404 https://artifacts.amirsys-int.com/artifactory/api/npm/npm-local/@acres%2facresmetajs
24 verbose headers { date: 'Tue, 06 Dec 2016 16:56:52 GMT',
24 verbose headers   server: 'Artifactory/4.14.1',
24 verbose headers   'x-artifactory-id': 'e4f2dc3ac0cfd515:4c7de749:158b20c68ee:-8000',
24 verbose headers   'content-type': 'application/json',
24 verbose headers   connection: 'close',
24 verbose headers   'transfer-encoding': 'chunked' }
25 silly get cb [ 404,
25 silly get   { date: 'Tue, 06 Dec 2016 16:56:52 GMT',
25 silly get     server: 'Artifactory/4.14.1',
25 silly get     'x-artifactory-id': 'e4f2dc3ac0cfd515:4c7de749:158b20c68ee:-8000',
25 silly get     'content-type': 'application/json',
25 silly get     connection: 'close',
25 silly get     'transfer-encoding': 'chunked' } ]
26 verbose stack Error: 404 Not Found: @acres/acresmetajs
26 verbose stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
26 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:250:14)
26 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
26 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:200:22)
26 verbose stack     at emitTwo (events.js:87:13)
26 verbose stack     at Request.emit (events.js:172:7)
26 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1067:10)
26 verbose stack     at emitOne (events.js:82:20)
26 verbose stack     at Request.emit (events.js:169:7)
26 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:988:12)
27 verbose statusCode 404
28 verbose pkgid @acres/acresmetajs
29 verbose cwd /Users/grinerd/Documents/Code/scopedacresmetajs
30 error Darwin 15.4.0
31 error argv "/usr/local/Cellar/node4-lts/4.6.2/bin/node" "/usr/local/bin/npm" "install" "@acres/acresmetajs"
32 error node v4.6.2
33 error npm  v2.15.9
34 error code E404
35 error 404 Not Found: @acres/acresmetajs
35 error 404
35 error 404 '@acres/acresmetajs' is not in the npm registry.
35 error 404 You should bug the author to publish it (or use the name yourself!)
35 error 404
35 error 404 Note that you can also install from a
35 error 404 tarball, folder, http url, or git url.
36 verbose exit [ 1, true ]

**Comment by legodude17** [comment]
This appears to be a bug with artifactory.

**Comment by daltongriner** [comment]
Alright, thanks for looking!

**Comment by zkat** [comment]
As @legodude17 this seems to be an issue with Artifactory, which we do not provide support for. You'll need to contact them for help with this. Closing this :)
