### ISSUE TITLE
Refusing to install react as a dependency of itself

### ISSUE THREAD

**Issue by rahulanand77** [npm/npm#15165]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
When trying to run following command, it is throwing error. 
npm install react --save

**verbose stack Error: Refusing to install react as a dependency of itself**

#### How can the CLI team reproduce the problem?
After installing Node on your syste, try installing it using following url

[Guide to Install React](https://www.tutorialspoint.com/reactjs/reactjs_environment_setup.htm)

[npm-debug.log.txt](https://github.com/npm/npm/files/638556/npm-debug.log.txt)

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by ahfarmer** [comment]
Is your package name `"react"`? (Check your `package.json`). If so, I suggest changing it to something else.

**Comment by rahulanand77** [comment]
Hi ahfarmer,

Thanks man you saved my day. Its installed now. Thanks for your help.

**Comment by rahulanand77** [comment]
Closing my issue. This has been fixed

**Comment by csamal** [comment]
Do you mean "name": "react-native-extended-stylesheet" is causing the issue?

**Comment by andrewagain** [comment]
@csamal In this case we were talking about `"name": "react"`.

However, if the "name" field in your package.json matches any of your dependencies or devDependencies, this issue will occur.

If you have a dependency called "react-native-extended-stylesheet", then you cannot use "react-native-extended-stylesheet" as your name.

In short, use a unique name.
