### ISSUE TITLE
npm 3.10.10 (node 7.2.1) hangs on sill extract 213

### ISSUE THREAD

**Issue by RangerGH** [npm/npm#15164]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I'm opening an new ticket because the last ticket I could  find with sill in it was September.

I installed node.js 7.2.1 from tarball. When I run npm install --save-dev gulp in a project directory (whcih has been inited) npm hangs on the extract:gulp: sill ddoParallel extract 213 and will never move on

gulp has been installed globally first.

#### How can the CLI team reproduce the problem?
npm install --savedev gulp on a project.

### supporting information:

 - `npm -v` prints: 3.10.10
 - `node -v` prints:v7.2.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux Fedora 24
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by RangerGH** [comment]
I tried it on a test project in a clean, newly created directory and got the same result.

**Comment by legodude17** [comment]
Please try updating `npm` to 4.0.3 with `npm install npm@latest`. If that doesn't work, try installing latest version from the [homepage.](https://github.com/npm/npm#readme).

**Comment by RangerGH** [comment]
Did not work.  It still hangs at extract:gulp sill doParallel extract 213.  The indicator spins for a while and then stops moving.

**Comment by legodude17** [comment]
Do you mean that using npm@4 doesn't work, or that you can't install npm@4?

**Comment by RangerGH** [comment]
Sorry, I wasn't clear.  The install worked  and I have npm 4.0.3 installed but if I try and npn install --save-dev gulp it hangs on the extract of sill.

**Comment by RangerGH** [comment]
I finally got it working.  I ended up rebooting my NFS server after running updates and it's now working so I can only assume something was wonky with the NFS connection.  After the gulp install failed I was having trouble with file managers not being able to open folders in the project so it must have been caused by some strangeness with NFS (which is strange anyway <G>).

**Comment by RangerGH** [comment]
Looks like that fixed it.

**Comment by legodude17** [comment]
:smile:
