### ISSUE TITLE
fetch failed with status code 404

### ISSUE THREAD

**Issue by DanishMichael** [npm/npm#15169]
I am trying to install the IBM Mobile First package through npm command
npm install -g mfpdev-cli
but it always results in "fetch failed with status code 404" error.
PFB the log file.

 http fetch 404 https://registry.npmjs.org/ibm-strings/-/ibm-strings-0.1.4.tgz
29638 error fetch failed https://registry.npmjs.org/ibm-strings/-/ibm-strings-0.1.4.tgz
29639 warn retry will retry, error on last attempt: Error: fetch failed with status code 404
29640 info retry fetch attempt 3 at 3:10:53 PM
29641 info attempt registry request try #1 at 3:10:53 PM
29642 http fetch GET https://registry.npmjs.org/ibm-strings/-/ibm-strings-0.1.4.tgz
29643 http fetch 404 https://registry.npmjs.org/ibm-strings/-/ibm-strings-0.1.4.tgz
29644 error fetch failed https://registry.npmjs.org/ibm-strings/-/ibm-strings-0.1.4.tgz
29645 silly fetchPackageMetaData Error: fetch failed with status code 404
29645 silly fetchPackageMetaData     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\fetch.js:51:14)
29645 silly fetchPackageMetaData     at emitOne (events.js:96:13)
29645 silly fetchPackageMetaData     at Request.emit (events.js:188:7)
29645 silly fetchPackageMetaData     at Request.onRequestResponse (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:954:10)
29645 silly fetchPackageMetaData     at emitOne (events.js:96:13)
29645 silly fetchPackageMetaData     at ClientRequest.emit (events.js:188:7)
29645 silly fetchPackageMetaData     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:474:21)
29645 silly fetchPackageMetaData     at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
29645 silly fetchPackageMetaData     at TLSSocket.socketOnData (_http_client.js:363:20)
29645 silly fetchPackageMetaData     at emitOne (events.js:96:13)
29645 silly fetchPackageMetaData     at TLSSocket.emit (events.js:188:7)
29645 silly fetchPackageMetaData  error for ibm-strings@https://registry.npmjs.org/ibm-strings/-/ibm-strings-0.1.4.tgz Error: fetch failed with status code 404
29645 silly fetchPackageMetaData     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\fetch.js:51:14)
29645 silly fetchPackageMetaData     at emitOne (events.js:96:13)
29645 silly fetchPackageMetaData     at Request.emit (events.js:188:7)
29645 silly fetchPackageMetaData     at Request.onRequestResponse (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:954:10)
29645 silly fetchPackageMetaData     at emitOne (events.js:96:13)
29645 silly fetchPackageMetaData     at ClientRequest.emit (events.js:188:7)
29645 silly fetchPackageMetaData     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:474:21)
29645 silly fetchPackageMetaData     at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
29645 silly fetchPackageMetaData     at TLSSocket.socketOnData (_http_client.js:363:20)
29645 silly fetchPackageMetaData     at emitOne (events.js:96:13)
29645 silly fetchPackageMetaData     at TLSSocket.emit (events.js:188:7)
29646 silly rollbackFailedOptional Starting
29647 silly rollbackFailedOptional Finishing
29648 silly runTopLevelLifecycles Finishing
29649 silly install printInstalled
29650 verbose stack Error: fetch failed with status code 404
29650 verbose stack     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\fetch.js:51:14)
29650 verbose stack     at emitOne (events.js:96:13)
29650 verbose stack     at Request.emit (events.js:188:7)
29650 verbose stack     at Request.onRequestResponse (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:954:10)
29650 verbose stack     at emitOne (events.js:96:13)
29650 verbose stack     at ClientRequest.emit (events.js:188:7)
29650 verbose stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:474:21)
29650 verbose stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
29650 verbose stack     at TLSSocket.socketOnData (_http_client.js:363:20)
29650 verbose stack     at emitOne (events.js:96:13)
29650 verbose stack     at TLSSocket.emit (events.js:188:7)
29651 verbose cwd C:\Users\IBM_ADMIN
29652 error Windows_NT 6.1.7601
29653 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "mfpdev-cli"
29654 error node v6.9.2
29655 error npm  v3.10.9
29656 error fetch failed with status code 404
29657 error If you need help, you may report this error at:
29657 error     <https://github.com/npm/npm/issues>
29658 verbose exit [ 1, true ]

**Comment by legodude17** [comment]
ibm-strings is not in the registry. What did you expect to happen?

**Comment by zkat** [comment]
Can you post the complete `npm-debug.log`? `ibm-strings` is not on the npm registry, but this package bundles it, so you should never have to download it, like this.

**Comment by KenanY** [comment]
Closing as abandoned. Can reopen once the `npm-debug.log` is provided :)

**Comment by rangelke** [comment]
I stumbled upon the same issue. Full npm-debug after running `npm install -g mfpdev-cli` can be found here: [npm-debug.txt](https://github.com/npm/npm/files/693327/npm-debug.txt)
