### ISSUE TITLE
Question: How to backup and restore global installed npm packages?

### ISSUE THREAD

**Issue by Luckyfella73** [npm/npm#15160]
Hi,

when I installed node ( on OSX El Captain ) a while ago I followed a tutorial recommending to set a npm prefix and let the npm packages save/install inside my User directory for sudo/non-sudo reasons.

Now I would like to do a fresh default reinstall of node and all npm packages but I'm afraid to loose all packages. What would be the best way to backup all global installed npm packages and restore them later? And what would be the best way to delete the old packages after backup?

**Comment by legodude17** [comment]
`npm` does not have a built in way, but you could zip up the global install folder and then unzip it into the same place later.

**Comment by Luckyfella73** [comment]
Ok - thank you for that information! After reinstalling I'm going to have a new directory for my global npm packages, now I have:
`/Users/imsungu/.npm-packages`

can I finally just delete this folder in Finder?

**Comment by legodude17** [comment]
What do you mean? The folder that `npm` installs in has to exist, but the one you used before (if it is different) could be deleted.

**Comment by Luckyfella73** [comment]
I just wondered if it's sufficient to just delete the folder or if it's necessary to care about files related to the packages but located elsewhere. I'm not that familiar how it works on Linux systems - For you it may sound like a stupid question ;)

Thank you very much for clarifying that to me!!
