### ISSUE TITLE
NMP Cert issue while install

### ISSUE THREAD

**Issue by muralidhar78** [npm/npm#15161]
#### I'm opening this issue because:

  - [ ] npm is doing something I don't understand.

#### What's going wrong?

C:\Windows\system32>npm install -g http-server
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "http-server"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code SELF_SIGNED_CERT_IN_CHAIN

npm ERR! self signed certificate in certificate chain
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Windows\system32\npm-debug.log

**Comment by legodude17** [comment]
Have you taken a look at http://blog.npmjs.org/post/78165272245/more-help-with-selfsignedcertinchain-and-npm? See if the steps outlined there work for you.

If it does NOT:

1. Are you behind a proxy?
2. How are you trying to use it?

**Comment by muralidhar78** [comment]
Yes, I'm behind a proxy and I set my proxy set using the config command. I also went thru the blog and did the same thing but still getting the error.

**Comment by legodude17** [comment]
Try running without the proxy temporarily and see it the issue is resolved.

**Comment by muralidhar78** [comment]
Ok, I tried in a machine where it doesn't need proxy. Now I get Git error while trying to install the swagger editor. 


npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v7.2.1
npm ERR! npm  v3.10.10
npm ERR! code ENOGIT

npm ERR! not found: git
npm ERR!
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Intraedge Guest\Downloads\swagger-editor-master\swagger-
itor-master\npm-debug.log

**Comment by legodude17** [comment]
Make sure to install `git` on that machine. Unfortunately, `npm` requires `git` to be installed globally. 😦
