### ISSUE TITLE
Getting Following Error (node:7732) fs: re-evaluating native module sources is not supported. If you are  using the graceful-fs module, please update it to a more recent version.

### ISSUE THREAD

**Issue by sanjayphadtare** [npm/npm#15168]
Getting Following Error (node:7732) fs: re-evaluating native module sources is not supported. If you are  using the graceful-fs module, please update it to a more recent version.

=================

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\sanjay.phadtare\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'node-dev' ]
2 info using npm@2.12.0
3 info using node@v6.9.2
4 verbose install initial load of C:\Program Files\nodejs\package.json
5 verbose readDependencies loading dependencies from C:\Program Files\nodejs\package.json
6 silly cache add args [ 'node-dev', null ]
7 verbose cache add spec node-dev
8 silly cache add parsed spec Result {
8 silly cache add   raw: 'node-dev',
8 silly cache add   scope: null,
8 silly cache add   name: 'node-dev',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 silly addNamed node-dev@*
10 verbose addNamed "*" is a valid semver range for node-dev
11 silly addNameRange { name: 'node-dev', range: '*', hasData: false }
12 silly mapToRegistry name node-dev
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/node-dev
16 verbose addNameRange registry:https://registry.npmjs.org/node-dev not in flight; fetching
17 verbose request uri https://registry.npmjs.org/node-dev
18 verbose request no auth needed
19 info attempt registry request try #1 at 3:19:43 PM
20 verbose request id eb13004f9df46261
21 http request GET https://registry.npmjs.org/node-dev
22 http 200 https://registry.npmjs.org/node-dev
23 silly get cb [ 200,
23 silly get   { server: 'nginx/1.10.1',
23 silly get     'content-type': 'application/json',
23 silly get     'last-modified': 'Sat, 01 Oct 2016 03:19:43 GMT',
23 silly get     etag: 'W/"57ef2b4f-dc88"',
23 silly get     'content-encoding': 'gzip',
23 silly get     'cache-control': 'max-age=300',
23 silly get     'content-length': '8203',
23 silly get     'accept-ranges': 'bytes',
23 silly get     date: 'Thu, 08 Dec 2016 09:49:41 GMT',
23 silly get     via: '1.1 varnish',
23 silly get     age: '0',
23 silly get     connection: 'keep-alive',
23 silly get     'x-served-by': 'cache-sin6927-SIN',
23 silly get     'x-cache': 'HIT',
23 silly get     'x-cache-hits': '1',
23 silly get     'x-timer': 'S1481190581.461612,VS0,VE98',
23 silly get     vary: 'Accept-Encoding' } ]
24 verbose get saving node-dev to C:\Users\sanjay.phadtare\AppData\Roaming\npm-cache\registry.npmjs.org\node-dev\.cache.json
25 verbose stack TypeError: process.getuid is not a function
25 verbose stack     at calculateOwner (C:\Users\sanjay.phadtare\AppData\Roaming\npm\node_modules\npm\lib\utils\correct-mkdir.js:37:24)
25 verbose stack     at C:\Users\sanjay.phadtare\AppData\Roaming\npm\node_modules\npm\lib\utils\correct-mkdir.js:23:22
25 verbose stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:123:15)
26 verbose cwd F:\node_training\7-Node-Package\7-1
27 error Windows_NT 6.3.9600
28 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\sanjay.phadtare\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "node-dev"
29 error node v6.9.2
30 error npm  v2.12.0
31 error process.getuid is not a function
32 error If you need help, you may report this error at:
32 error     <https://github.com/npm/npm/issues>
33 verbose exit [ 1, true ]

**Comment by legodude17** [comment]
The error in the title and the one in the log are different. Which error do you have?

**Comment by KenanY** [comment]
I feel like this "process.getuid is not a function" error was fixed in a newer version of `npm`, but I don't recall which. Does this also occur if you update to the latest `npm`?

**Comment by sanjayphadtare** [comment]
I am not able to update my npm
If I try to execute command "npm install -g node-dev", I am getting following error....

C:\WINDOWS\system32>npm install -g node-dev

(node:7584) fs: re-evaluating native module sources is not supported. If you are
 using the graceful-fs module, please update it to a more recent version.
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\sanjay.phadtare\
\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "node
-dev"
npm ERR! node v6.9.2
npm ERR! npm  v2.12.0

npm ERR! process.getuid is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
-
npm ERR! Please include the following file with any support request:
npm ERR!     C:\WINDOWS\system32\npm-debug.log

**Comment by legodude17** [comment]
The layers node should of come with a newer version of npm.

**Comment by InfiniteStyles** [comment]
Node/NPM on Windows is horrendously broken. 

If you have Windows 10, I would suggest installing the 'Bash on Windows' enviroment, which will create a Linux subsystem.
