### ISSUE TITLE
I can't publish a package

### ISSUE THREAD

**Issue by MpStyle** [npm/npm#15162]
I tried to publish a package to the registry, but I had an error:

0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'publish' ]
2 info using npm@2.15.2
3 info using node@v0.10.25
4 verbose node symlink /usr/bin/node
5 verbose publish [ '.' ]
6 silly cache add args [ '.', null ]
7 verbose cache add spec .
8 silly cache add parsed spec { raw: '.',
8 silly cache add   scope: null,
8 silly cache add   name: null,
8 silly cache add   rawSpec: '.',
8 silly cache add   spec: '/home/michelepagnin/Programmazione/TypeScript/jT',
8 silly cache add   type: 'directory' }
9 verbose addLocalDirectory /home/michelepagnin/.npm/jt/1.0.0/package.tgz not in flight; packing
10 verbose correctMkdir /home/michelepagnin/.npm correctMkdir not in flight; initializing
11 verbose tar pack [ '/home/michelepagnin/.npm/jt/1.0.0/package.tgz',
11 verbose tar pack   '/home/michelepagnin/Programmazione/TypeScript/jT' ]
12 verbose tarball /home/michelepagnin/.npm/jt/1.0.0/package.tgz
13 verbose folder /home/michelepagnin/Programmazione/TypeScript/jT
14 info prepublish jt@1.0.0
15 verbose addLocalTarball adding from inside cache /home/michelepagnin/.npm/jt/1.0.0/package.tgz
16 verbose correctMkdir /home/michelepagnin/.npm correctMkdir not in flight; initializing
17 silly cache afterAdd jt@1.0.0
18 verbose afterAdd /home/michelepagnin/.npm/jt/1.0.0/package/package.json not in flight; writing
19 verbose correctMkdir /home/michelepagnin/.npm correctMkdir not in flight; initializing
20 verbose afterAdd /home/michelepagnin/.npm/jt/1.0.0/package/package.json written
21 silly publish { name: 'jt',
21 silly publish   version: '1.0.0',
21 silly publish   description: 'Javascript Template Engine. Fast and simple. A lot of attributes supported in only 1,5 KB',
21 silly publish   author: { name: 'Michele Pagnin' },
21 silly publish   license: 'LGPL v3',
21 silly publish   dependencies: { jquery: '~3.1.1' },
21 silly publish   devDependencies:
21 silly publish    { '@types/jquery': '^2.0.34',
21 silly publish      grunt: '~1.0.1',
21 silly publish      'grunt-contrib-uglify': '~2.0.0',
21 silly publish      'grunt-contrib-watch': '~1.0.0',
21 silly publish      'grunt-ts': '~6.0.0-beta.3',
21 silly publish      typescript: '~2.0.3' },
21 silly publish   readme: '# jT - Javascript Template\n\nJavascript Template Engine. Fast and simple. A lot of attributes supported in only 1,5 KB\n\n## Include\n```html\n<script type="text/javascript" src="dist/jquery-mtemplatejs.min.js"></script>\n```\n\n## Template attributes:\n* data-jt-text\n* data-jt-class\n* data-jt-href\n* data-jt-src\n* data-jt-alt\n* data-jt-data\n* data-jt-title\n\n## Fully example\n```html\n<!DOCTYPE html>\n<html lang="en">\n<head>\n    <meta charset="UTF-8">\n    <title>Test 2</title>\n    <script src="jquery.min.js"></script>\n    <script src="jt.js"></script>\n</head>\n<body>\n\n<script>\n    $(function () {\n        $("#template").jt({\n            destination: "#container",\n            data: [\n                {\n                    hello: "Hello world!",\n                    hello_source: "en",\n                    tooltip: "Hello world",\n                    hello_alternative: "Hello",\n                    lang: "#en",\n                    color: "black"\n                },\n                {\n                    hello: "Ciao mondo",\n                    hello_source: "it",\n                    tooltip: "Ciao mondo",\n                    hello_alternative: "Ciao",\n                    lang: "#it",\n                    color: "red"\n                },\n                {\n                    hello: "aaa",\n                    hello_source: "bbb",\n                    tooltip: "ccc",\n                    hello_alternative: "ddd",\n                    lang: "eee",\n                    color: "fff"\n                }\n            ],\n            beforeRender: [\n                function ($template, item) {\n                    $template.append(item.hello_source);\n                    return $template;\n                }\n            ]\n        });\n    });\n</script>\n\n<div id="container"></div>\n\n<div id="template">\n    <a data-jt="hello"\n       data-jt-src="hello_source"\n       data-jt-title="tooltip"\n       data-jt-alt="hello_alternative"\n       data-jt-link="lang"\n       data-jt-class="color"></a>\n</div>\n\n</body>\n</html>\n```\n\n# Development\n- Clone the repository\n- Install NPM\n- In the root of the project run:\n```\nnpm install\n```\nTo build run:\n```\ngrunt\n```\n\n# History\n\n### 1.0.0',
21 silly publish   readmeFilename: 'README.md',
21 silly publish   gitHead: '260618bbbd74faa0b0f2dda382a90910304b4bd7',
21 silly publish   _id: 'jt@1.0.0',
21 silly publish   scripts: {},
21 silly publish   _shasum: 'efbbfdfaec5545810b5f2cac00f4940b33106304',
21 silly publish   _from: '.' }
22 verbose getPublishConfig undefined
23 silly mapToRegistry name jt
24 silly mapToRegistry using default registry
25 silly mapToRegistry registry https://registry.npmjs.org/
26 silly mapToRegistry data { raw: 'jt',
26 silly mapToRegistry   scope: null,
26 silly mapToRegistry   name: 'jt',
26 silly mapToRegistry   rawSpec: '',
26 silly mapToRegistry   spec: 'latest',
26 silly mapToRegistry   type: 'tag' }
27 silly mapToRegistry uri https://registry.npmjs.org/jt
28 verbose publish registryBase https://registry.npmjs.org/
29 silly publish uploading /home/michelepagnin/.npm/jt/1.0.0/package.tgz
30 verbose request uri https://registry.npmjs.org/jt
31 verbose request sending authorization for write operation
32 info attempt registry request try #1 at 19:30:07
33 verbose request using bearer token for auth
34 verbose request id 6e30128c3c226680
35 http request PUT https://registry.npmjs.org/jt
36 http 403 https://registry.npmjs.org/jt
37 verbose headers { 'content-type': 'application/json',
37 verbose headers   'cache-control': 'max-age=300',
37 verbose headers   'content-length': '96',
37 verbose headers   'accept-ranges': 'bytes',
37 verbose headers   date: 'Wed, 07 Dec 2016 18:30:09 GMT',
37 verbose headers   via: '1.1 varnish',
37 verbose headers   connection: 'keep-alive',
37 verbose headers   'x-served-by': 'cache-ams4135-AMS',
37 verbose headers   'x-cache': 'MISS',
37 verbose headers   'x-cache-hits': '0',
37 verbose headers   'x-timer': 'S1481135407.920534,VS0,VE1198',
37 verbose headers   vary: 'Accept-Encoding' }
38 verbose request invalidating /home/michelepagnin/.npm/registry.npmjs.org/jt on PUT
39 error publish Failed PUT 403
40 verbose stack Error: you do not have permission to publish "jt". Are you logged in as the correct user? : jt
40 verbose stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
40 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:252:14)
40 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
40 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:199:22)
40 verbose stack     at Request.EventEmitter.emit (events.js:98:17)
40 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1036:10)
40 verbose stack     at Request.EventEmitter.emit (events.js:117:20)
40 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:963:12)
40 verbose stack     at IncomingMessage.EventEmitter.emit (events.js:117:20)
40 verbose stack     at _stream_readable.js:920:16
41 verbose statusCode 403
42 verbose pkgid jt
43 verbose cwd /home/michelepagnin/Programmazione/TypeScript/jT
44 error Linux 3.13.0-93-generic
45 error argv "node" "/usr/local/bin/npm" "publish"
46 error node v0.10.25
47 error npm  v2.15.2
48 error code E403
49 error you do not have permission to publish "jt". Are you logged in as the correct user? : jt
50 error If you need help, you may report this error at:
50 error     <https://github.com/npm/npm/issues>
51 verbose exit [ 1, true ]

I'm logged as michele.pagnin, but npm tries to publish the package as jt.

Right now, I don't know why, there is a package jT published in my profile (ERROR: No README data found!) and I can't remove/unpublish it.

**Comment by legodude17** [comment]
I think that you should report this to the registry team, not the CLI. I think you should report this to npm/registry.

**Comment by zkat** [comment]
https://www.npmjs.com/package/jt

`michele.pagnin` does not own this module. I also don't see a `jT` at https://www.npmjs.com/~michele.pagnin. Except for jquery-jt, which is a different package.
