### ISSUE TITLE
npm install parsoid fail due to "Could not read from remote repository"

### ISSUE THREAD

**Issue by tommypaopao** [npm/npm#15167]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?
I can't install parsoid with npm 4.0.5
### supporting information:

 - `npm -v` prints: 4.0.5
 - `node -v` prints: v6.9.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows7
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [x] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

Could you please take a look at this issue?

I am installing parsoid with npm, there will be error:

54989 silly gunzTarPerm extractEntry package.json
54990 silly gunzTarPerm modified mode [ 'package.json', 420, 438 ]
54991 silly gunzTarPerm extractEntry .travis.yml
54992 silly gunzTarPerm modified mode [ '.travis.yml', 420, 438 ]
54993 silly gunzTarPerm extractEntry History.md
54994 silly gunzTarPerm modified mode [ 'History.md', 420, 438 ]
54995 silly gunzTarPerm extractEntry Readme.md
54996 silly gunzTarPerm modified mode [ 'Readme.md', 420, 438 ]
54997 silly gunzTarPerm extractEntry builtins.json
54998 silly gunzTarPerm modified mode [ 'builtins.json', 420, 438 ]
54999 verbose correctMkdir C:\Users\joe\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
55000 silly cache afterAdd builtins@0.0.7
55001 verbose afterAdd C:\Users\joe\AppData\Roaming\npm-cache\builtins\0.0.7\package\package.json not in flight; writing
55002 verbose correctMkdir C:\Users\joe\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
55003 verbose afterAdd C:\Users\joe\AppData\Roaming\npm-cache\builtins\0.0.7\package\package.json written
55004 silly rollbackFailedOptional Starting
55005 silly rollbackFailedOptional Finishing
55006 silly runTopLevelLifecycles Finishing
55007 silly install printInstalled
55008 verbose stack Error: Command failed: git -c core.longpaths=true clone C:\Users\joe\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-wikimedia-content-type-git-47b2632d0a2ee79a7d67268e2f6621becd95d05b-0dff22de C:\Users\joe\AppData\Local\Temp\npm-3112-cfa7f0f3\git-cache-b0a683e1\47b2632d0a2ee79a7d67268e2f6621becd95d05b
55008 verbose stack Cloning into 'C:\Users\joe\AppData\Local\Temp\npm-3112-cfa7f0f3\git-cache-b0a683e1\47b2632d0a2ee79a7d67268e2f6621becd95d05b'...
55008 verbose stack fatal: '/cygdrive/c/Users/joe/AppData/Roaming/npm-cache/_git-remotes/git-https-github-com-wikimedia-content-type-git-47b2632d0a2ee79a7d67268e2f6621becd95d05b-0dff22de/C:\Users\joe\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-wikimedia-content-type-git-47b2632d0a2ee79a7d67268e2f6621becd95d05b-0dff22de' does not appear to be a git repository
55008 verbose stack fatal: Could not read from remote repository.
55008 verbose stack
55008 verbose stack Please make sure you have the correct access rights
55008 verbose stack and the repository exists.
55008 verbose stack
55008 verbose stack     at ChildProcess.exithandler (child_process.js:206:12)
55008 verbose stack     at emitTwo (events.js:106:13)
55008 verbose stack     at ChildProcess.emit (events.js:191:7)
55008 verbose stack     at maybeClose (internal/child_process.js:877:16)
55008 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
55009 verbose cwd C:\Users\joe
55010 error Windows_NT 6.1.7600
55011 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\joe\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "parsoid"
55012 error node v6.9.1
55013 error npm  v4.0.5
55014 error code 128
55015 error Command failed: git -c core.longpaths=true clone C:\Users\joe\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-wikimedia-content-type-git-47b2632d0a2ee79a7d67268e2f6621becd95d05b-0dff22de C:\Users\joe\AppData\Local\Temp\npm-3112-cfa7f0f3\git-cache-b0a683e1\47b2632d0a2ee79a7d67268e2f6621becd95d05b
55015 error Cloning into 'C:\Users\joe\AppData\Local\Temp\npm-3112-cfa7f0f3\git-cache-b0a683e1\47b2632d0a2ee79a7d67268e2f6621becd95d05b'...
55015 error fatal: '/cygdrive/c/Users/joe/AppData/Roaming/npm-cache/_git-remotes/git-https-github-com-wikimedia-content-type-git-47b2632d0a2ee79a7d67268e2f6621becd95d05b-0dff22de/C:\Users\joe\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-wikimedia-content-type-git-47b2632d0a2ee79a7d67268e2f6621becd95d05b-0dff22de' does not appear to be a git repository
55015 error fatal: Could not read from remote repository.
55015 error
55015 error Please make sure you have the correct access rights
55015 error and the repository exists.
55016 error If you need help, you may report this error at:
55016 error     <https://github.com/npm/npm/issues>
55017 verbose exit [ 1, true ]

**Comment by tommypaopao** [comment]
here is the log

**Comment by tommypaopao** [comment]
[npm-debug.txt](https://github.com/npm/npm/files/639001/npm-debug.txt)

**Comment by legodude17** [comment]
Does git clone git+https://github.com/wikimedia/content-type#master work?

**Comment by tommypaopao** [comment]
It does not work:

C:\Users\joe>git clone git+https://github.com/wikimedia/content-type#master
Cloning into 'content-type#master'...
fatal: Unable to find remote helper for 'git+https'

C:\Users\joe>git clone https://github.com/wikimedia/content-type#master
Cloning into 'content-type#master'...
fatal: https://github.com/wikimedia/content-type#master/info/refs not valid: is
this a git repository?

**Comment by legodude17** [comment]
This seems like a git issue then, or an issue with your setup.

**Comment by tommypaopao** [comment]
OK, thank you, Let me check my env.

**Comment by KenanY** [comment]
Closing as abandoned. Can reopen if this is still an issue.
