### ISSUE TITLE
Error :npm firebase installation 

### ISSUE THREAD

**Issue by AnuragKDwivedi** [npm/npm#15172]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'angularfire2' ]
2 info using npm@3.8.6
3 info using node@v6.1.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData angularfire2@^2.0.0-beta.6
8 silly fetchNamedPackageData angularfire2
9 silly mapToRegistry name angularfire2
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'angularfire2',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   name: 'angularfire2',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/angularfire2
14 verbose request uri https://registry.npmjs.org/angularfire2
15 verbose request no auth needed
16 info attempt registry request try #1 at 4:16:12 PM
17 verbose request id 94d4b7385119273a
18 http request GET https://registry.npmjs.org/angularfire2
19 http 200 https://registry.npmjs.org/angularfire2
20 verbose headers { server: 'nginx/1.10.1',
20 verbose headers   'content-type': 'application/json',
20 verbose headers   'last-modified': 'Wed, 02 Nov 2016 18:28:30 GMT',
20 verbose headers   etag: 'W/"581a304e-18340"',
20 verbose headers   'content-encoding': 'gzip',
20 verbose headers   'cache-control': 'max-age=300',
20 verbose headers   'content-length': '7454',
20 verbose headers   'accept-ranges': 'bytes',
20 verbose headers   date: 'Thu, 08 Dec 2016 10:46:17 GMT',
20 verbose headers   via: '1.1 varnish',
20 verbose headers   age: '95',
20 verbose headers   connection: 'keep-alive',
20 verbose headers   'x-served-by': 'cache-sin6921-SIN',
20 verbose headers   'x-cache': 'HIT',
20 verbose headers   'x-cache-hits': '16',
20 verbose headers   'x-timer': 'S1481193977.610640,VS0,VE0',
20 verbose headers   vary: 'Accept-Encoding' }
21 silly get cb [ 200,
21 silly get   { server: 'nginx/1.10.1',
21 silly get     'content-type': 'application/json',
21 silly get     'last-modified': 'Wed, 02 Nov 2016 18:28:30 GMT',
21 silly get     etag: 'W/"581a304e-18340"',
21 silly get     'content-encoding': 'gzip',
21 silly get     'cache-control': 'max-age=300',
21 silly get     'content-length': '7454',
21 silly get     'accept-ranges': 'bytes',
21 silly get     date: 'Thu, 08 Dec 2016 10:46:17 GMT',
21 silly get     via: '1.1 varnish',
21 silly get     age: '95',
21 silly get     connection: 'keep-alive',
21 silly get     'x-served-by': 'cache-sin6921-SIN',
21 silly get     'x-cache': 'HIT',
21 silly get     'x-cache-hits': '16',
21 silly get     'x-timer': 'S1481193977.610640,VS0,VE0',
21 silly get     vary: 'Accept-Encoding' } ]
22 verbose get saving angularfire2 to C:\Users\Dwivedi's\AppData\Roaming\npm-cache\registry.npmjs.org\angularfire2\.cache.json
23 verbose correctMkdir C:\Users\Dwivedi's\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
24 verbose makeDirectory C:\Users\Dwivedi's\AppData\Roaming\npm-cache creation not in flight; initializing
25 verbose makeCacheDir UID & GID are irrelevant on win32
26 silly install normalizeTree
27 silly loadCurrentTree Finishing
28 silly loadIdealTree Starting
29 silly install loadIdealTree
30 silly cloneCurrentTree Starting
31 silly install cloneCurrentTreeToIdealTree
32 silly cloneCurrentTree Finishing
33 silly loadShrinkwrap Starting
34 silly install loadShrinkwrap
35 silly loadShrinkwrap Finishing
36 silly loadAllDepsIntoIdealTree Starting
37 silly install loadAllDepsIntoIdealTree
38 silly resolveWithNewModule angularfire2@2.0.0-beta.6 checking installable status
39 silly cache add args [ 'angularfire2@^2.0.0-beta.6', null ]
40 verbose cache add spec angularfire2@^2.0.0-beta.6
41 silly cache add parsed spec Result {
41 silly cache add   raw: 'angularfire2@^2.0.0-beta.6',
41 silly cache add   scope: null,
41 silly cache add   name: 'angularfire2',
41 silly cache add   rawSpec: '^2.0.0-beta.6',
41 silly cache add   spec: '>=2.0.0-beta.6 <3.0.0',
41 silly cache add   type: 'range' }
42 silly addNamed angularfire2@>=2.0.0-beta.6 <3.0.0
43 verbose addNamed ">=2.0.0-beta.6 <3.0.0" is a valid semver range for angularfire2
44 silly addNameRange { name: 'angularfire2',
44 silly addNameRange   range: '>=2.0.0-beta.6 <3.0.0',
44 silly addNameRange   hasData: false }
45 silly mapToRegistry name angularfire2
46 silly mapToRegistry using default registry
47 silly mapToRegistry registry https://registry.npmjs.org/
48 silly mapToRegistry data Result {
48 silly mapToRegistry   raw: 'angularfire2',
48 silly mapToRegistry   scope: null,
48 silly mapToRegistry   name: 'angularfire2',
48 silly mapToRegistry   rawSpec: '',
48 silly mapToRegistry   spec: 'latest',
48 silly mapToRegistry   type: 'tag' }
49 silly mapToRegistry uri https://registry.npmjs.org/angularfire2
50 verbose addNameRange registry:https://registry.npmjs.org/angularfire2 not in flight; fetching
51 verbose get https://registry.npmjs.org/angularfire2 not expired, no request
52 silly addNameRange number 2 { name: 'angularfire2',
52 silly addNameRange   range: '>=2.0.0-beta.6 <3.0.0',
52 silly addNameRange   hasData: true }
53 silly addNameRange versions [ 'angularfire2',
53 silly addNameRange   [ '2.0.0-alpha.1',
53 silly addNameRange     '2.0.0-alpha.2',
53 silly addNameRange     '2.0.0-alpha.3',
53 silly addNameRange     '2.0.0-alpha.4',
53 silly addNameRange     '2.0.0-alpha.5',
53 silly addNameRange     '2.0.0-alpha.6',
53 silly addNameRange     '2.0.0-alpha.7',
53 silly addNameRange     '2.0.0-alpha.8',
53 silly addNameRange     '2.0.0-alpha.9',
53 silly addNameRange     '2.0.0-alpha.10',
53 silly addNameRange     '2.0.0-alpha.11',
53 silly addNameRange     '2.0.0-alpha.12',
53 silly addNameRange     '2.0.0-alpha.13',
53 silly addNameRange     '2.0.0-alpha.14',
53 silly addNameRange     '2.0.0-alpha.15',
53 silly addNameRange     '2.0.0-alpha.16',
53 silly addNameRange     '2.0.0-alpha.17',
53 silly addNameRange     '2.0.0-beta.0',
53 silly addNameRange     '2.0.0-beta.0-1',
53 silly addNameRange     '2.0.0-beta.1-next',
53 silly addNameRange     '2.0.0-beta.1-next2',
53 silly addNameRange     '2.0.0-beta.1',
53 silly addNameRange     '2.0.0-beta.2.0.0-beta.022e50c',
53 silly addNameRange     '2.0.0-beta.1-c823de0',
53 silly addNameRange     '2.0.0-beta.2-c823de0',
53 silly addNameRange     '2.0.0-beta.2',
53 silly addNameRange     '2.0.0-beta.3-0930330',
53 silly addNameRange     '2.0.0-beta.3',
53 silly addNameRange     '2.0.0-beta.3-pre',
53 silly addNameRange     '2.0.0-beta.3-pre2',
53 silly addNameRange     '2.0.0-beta.4',
53 silly addNameRange     '2.0.0-beta.5-preview',
53 silly addNameRange     '2.0.0-beta.5',
53 silly addNameRange     '2.0.0-beta.6-preview',
53 silly addNameRange     '2.0.0-beta.6' ] ]
54 silly addNamed angularfire2@2.0.0-beta.6
55 verbose addNamed "2.0.0-beta.6" is a plain semver version for angularfire2
56 silly mapToRegistry name angularfire2
57 silly mapToRegistry using default registry
58 silly mapToRegistry registry https://registry.npmjs.org/
59 silly mapToRegistry data Result {
59 silly mapToRegistry   raw: 'angularfire2',
59 silly mapToRegistry   scope: null,
59 silly mapToRegistry   name: 'angularfire2',
59 silly mapToRegistry   rawSpec: '',
59 silly mapToRegistry   spec: 'latest',
59 silly mapToRegistry   type: 'tag' }
60 silly mapToRegistry uri https://registry.npmjs.org/angularfire2
61 verbose addRemoteTarball https://registry.npmjs.org/angularfire2/-/angularfire2-2.0.0-beta.6.tgz not in flight; adding
62 verbose addRemoteTarball [ 'https://registry.npmjs.org/angularfire2/-/angularfire2-2.0.0-beta.6.tgz',
62 verbose addRemoteTarball   'b419ee401ef03a2b64e56369330e0272db47f50e' ]
63 info retry fetch attempt 1 at 4:16:51 PM
64 info attempt registry request try #1 at 4:16:51 PM
65 http fetch GET https://registry.npmjs.org/angularfire2/-/angularfire2-2.0.0-beta.6.tgz
66 http fetch 200 https://registry.npmjs.org/angularfire2/-/angularfire2-2.0.0-beta.6.tgz
67 info retry will retry, error on last attempt: Error: read ECONNRESET
68 info retry will retry, error on last attempt: Error: read ECONNRESET
69 silly fetchAndShaCheck shasum b419ee401ef03a2b64e56369330e0272db47f50e
70 silly rollbackFailedOptional Starting
71 silly rollbackFailedOptional Finishing
72 silly runTopLevelLifecycles Starting
73 silly runTopLevelLifecycles Finishing
74 silly install printInstalled
75 verbose stack Error: shasum check failed for C:\Users\DWIVED~1\AppData\Local\Temp\npm-2540-ccdce3fa\registry.npmjs.org\angularfire2\-\angularfire2-2.0.0-beta.6.tgz
75 verbose stack Expected: b419ee401ef03a2b64e56369330e0272db47f50e
75 verbose stack Actual:   4173473098b5c9f7a23ea183d7771dffda06ea33
75 verbose stack From:     https://registry.npmjs.org/angularfire2/-/angularfire2-2.0.0-beta.6.tgz
75 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:25:8
75 verbose stack     at ReadStream.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:72:7)
75 verbose stack     at emitNone (events.js:91:20)
75 verbose stack     at ReadStream.emit (events.js:185:7)
75 verbose stack     at endReadableNT (_stream_readable.js:926:12)
75 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:74:11)
75 verbose stack     at process._tickCallback (internal/process/next_tick.js:98:9)
76 verbose cwd E:\Anurag\USA project\firebase\Angular-cli
77 error Windows_NT 6.1.7601
78 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "angularfire2"
79 error node v6.1.0
80 error npm  v3.8.6
81 error shasum check failed for C:\Users\DWIVED~1\AppData\Local\Temp\npm-2540-ccdce3fa\registry.npmjs.org\angularfire2\-\angularfire2-2.0.0-beta.6.tgz
81 error Expected: b419ee401ef03a2b64e56369330e0272db47f50e
81 error Actual:   4173473098b5c9f7a23ea183d7771dffda06ea33
81 error From:     https://registry.npmjs.org/angularfire2/-/angularfire2-2.0.0-beta.6.tgz
82 error If you need help, you may report this error at:
82 error     <https://github.com/npm/npm/issues>
83 verbose exit [ 1, true ]

**Comment by AnuragKDwivedi** [comment]
how to fix this problem please help me..

**Comment by legodude17** [comment]
Hello! This is a duplicated of #14626. Please see [this comment](https://github.com/npm/npm/issues/14626#issuecomment-264371634).

**Comment by zkat** [comment]
Closing as a duplicate, as @legodude17 pointed out.
