### ISSUE TITLE
Can't see my new README when publishing to update it

### ISSUE THREAD

**Issue by Echopraxium** [npm/npm#15177]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ X] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I do the following:
npm version patch
git push origin master
npm publish .

Then I still don't see the latest version (1.0.9) of my package (mixin-interface)

#### How can the CLI team reproduce the problem?
Open https://www.npmjs.com/package/mixin-interface, it shows version 1.0.1 in npm
Open https://github.com/Echopraxium/mixin-interface, it show version 1.0.9 in github

and when opening https://www.npmjs.com/~echopraxium, the version is 1.0.9

### supporting information:

 - `npm -v` prints: 3.10.8
 - `node -v` prints: v6.9.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows 7
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
It might take a little bit to see your new readme on the npm website, also your browser might have cached the website. Try reloading 3-5 times.

**Comment by KenanY** [comment]
Looks fine to me now. In the future, please open website issues over at <https://github.com/npm/www>. Thanks!
