### ISSUE TITLE
npm init - test command strips paths starting with ./

### ISSUE THREAD

**Issue by michaelkrone** [npm/npm#15175]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
`npm init` strips paths that start with `./` for the `test command` entry. When using `./node_modules/.bin/xo`, npm init produces

    "scripts": {
        "test": "xo"
    }

However this does only happen if the path starts with `./`, `../` or `/` will produce the expected results (I know those paths will never be used).

Paths entered for the `main entry:` produces correct results for paths starting with `./`.
 
#### How can the CLI team reproduce the problem?
1) `npm init`
2) When asked for `test command:`, use a relative path `./node_modules/.bin/xo`

### supporting information:

 - `npm -v` prints: 3.10.10
 - `node -v` prints: v7.2.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux, Ubuntu 16.04

**Comment by 7coder7** [comment]
From the docs [npm run-script](https://docs.npmjs.com/cli/run-script), NPM adds the **node_modules/.bin/** to your PATH. Hence the stripping

> In addition to the shell's pre-existing PATH, npm run adds node_modules/.bin to the PATH provided to scripts. Any binaries provided by locally-installed dependencies can be used without the node_modules/.bin prefix. For example, if there is a devDependency on tap in your package, you should write

`"scripts": {"test": "tap test/\*.js"}`

**Comment by michaelkrone** [comment]
Oh, I missed that, sorry.
