### ISSUE TITLE
npm ERR! Windows_NT 6.1.7600  || npm ERR! code ENETUNREACH

### ISSUE THREAD

**Issue by komalbadge** [npm/npm#15173]
Hey everyone there i am facing this dirty issue from long time while trying to update to IONIC 2. PLEASE HELP ME OUT...

`C:\>npm update -g ionic
npm ERR! Windows_NT 6.1.7600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "update" "-g" "ionic"
npm ERR! node v6.1.0
npm ERR! npm  v3.8.6
npm ERR! code ENETUNREACH
npm ERR! errno ENETUNREACH
npm ERR! syscall connect

npm ERR! connect ENETUNREACH 192.30.253.113:8080
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\npm-debug.log
`

**Comment by legodude17** [comment]
Try npm config set registry https://registry.npmjs.org

**Comment by komalbadge** [comment]
I got same error after Trying  npm config set registry https://registry.npmjs.org....
please help me out..:)

**Comment by legodude17** [comment]
Does it still say connect ENETUNREACH 192.30.253.113:8080

**Comment by zkat** [comment]
@komalbadge this is an issue with your proxy. And your network is perhaps not able to access our registry without one.

**Comment by komalbadge** [comment]
Yes it still  say connect ENETUNREACH 192.30.253.113:8080

**Comment by legodude17** [comment]
Do you have a proxy @komalbadge?

**Comment by komalbadge** [comment]
No..We have Authenticated Server...

**Comment by legodude17** [comment]
What do you mean by "Authenticated Server"?

**Comment by komalbadge** [comment]
I mean I don't use Proxy server..

**Comment by legodude17** [comment]
😕  Try running `npm config get https-proxy`.

**Comment by komalbadge** [comment]
It shows null

**Comment by komalbadge** [comment]
I solved this issue by issuing the following commands

npm config set proxy false
npm cache clean

**Comment by YuriiZadorozhnyi** [comment]
I tried: 
npm config set proxy false
npm cache clean
The problem still not solved ( 
Can anybody help?
