### ISSUE TITLE
npm install <tarball file> --save doesn't update shrinkwrap file

### ISSUE THREAD

**Issue by szwacz** [npm/npm#15170]
#### I'm opening this issue because:

  - The way I'm suppose to update dependency in "shrinkwrapped" project ([according to docs](https://docs.npmjs.com/cli/shrinkwrap#building-shrinkwrapped-packages)) doesn't work if that dependency is an url to a tarball file.

#### What's going wrong?

`npm install <tarball file> --save` doesn't update `npm-shrinkwrap.json` file

#### How can the CLI team reproduce the problem?

I have project which uses npm tarball file as a dependency in `package.json`:
```json
{
  "dependencies": {
    "foo": "http://example.com/foo-1.0.0.tar.gz"
  }
}
```
And this project has also `npm shrinkwrap` activated.

Now I want to update version of my `foo` dependency by changeing the url to file:
```
npm install --save http://example.com/foo-2.0.0.tar.gz
```

That updated the `package.json`:
```json
{
  "dependencies": {
    "foo": "http://example.com/foo-2.0.0.tar.gz"
  }
}
```

But `npm-shrinkwrap.json` __was not__ updated.

### supporting information:

 - `npm -v` prints: 3.10.9
 - `node -v` prints: 7.2.0

**Comment by legodude17** [comment]
Is running npm shrinkwrap again a workaround?

**Comment by szwacz** [comment]
Running `npm shrinkwrap` again ends with error. Npm is complaining about incorrectly installed dependency tree.

**Comment by legodude17** [comment]
:confounded: can you get a consistent reproduction case?

**Comment by szwacz** [comment]
I was trying to isolate the problem out of my code without success. But I have 100% reproducability with my package: `http://static.filestackapi.com/packages/release-o-tron/release-o-tron-1.3.5.tar.gz`.

Way to reproduce:
```
mkdir some-project
cd some-project
npm init
npm shrinkwrap
npm install http://static.filestackapi.com/packages/release-o-tron/release-o-tron-1.3.5.tar.gz --save
```

After that `npm-shrinkwrap.json` remains empty.

My best hunch: the installed tarball package is also shrinkwrapped. So we have cascade of shrinkwraps here.
