### ISSUE TITLE
Download all modules from an scoped package

### ISSUE THREAD

**Issue by searchinnerpeace** [npm/npm#15178]
I'm learning Angular 2, so this is my dependencies property inside package.json:

```
{
  "dependencies": {
    "@angular/common": "*",
    "@angular/compiler": "*",
    "@angular/core": "*",
    "@angular/forms": "*",
    "@angular/http": "*",
    "@angular/platform-browser": "*",
    "@angular/platform-browser-dynamic": "*",
    "@angular/router": "*",
    ...
  }
}
```

Is there a way to do `"@angular/*": "*" `? It's annoying put all modules one by one. Thanks.

**Comment by legodude17** [comment]
There is not currently a way, but good question! That might be a good idea, but it is not a very big use case, and the `npm` CLI team is very small.

**Comment by searchinnerpeace** [comment]
I wish I could help, but I'm just a user. Thank you for the attention.
