### ISSUE TITLE
Publish from multiple machines

### ISSUE THREAD

**Issue by mikeerickson** [npm/npm#15187]
I am trying to figure out how to manage a specific package from work and hope.

Is there some way to configure this?

**Comment by legodude17** [comment]
What do you mean from hope? You can just use git to manage versions, host it on GitHub, and then you can publish from anywhere.

**Comment by mikeerickson** [comment]
I get an error message when i try to publish from a machine other than one used to create initial package.

Message states the current machine is not the owner.

**Comment by KenanY** [comment]
@mikeerickson Even after doing `npm login`? Is there a `npm-debug.log` you can upload to <https://gist.github.com/> and link here?

**Comment by mikeerickson** [comment]
@KenanY Here is the gist -- https://gist.github.com/mikeerickson/da19831890522a676a31691f4d910b03

**Comment by mikeerickson** [comment]
Not sure if this will be of importance to you

```
 
{ name: 'package-menu-cli',
  description: 'Displays menu of scripts from folder package.json',
  'dist-tags': { latest: '1.0.0' },
  versions: [ '1.0.0' ],
  maintainers: [ 'mikeerickson <codedungeon@gmail.com>' ],
  time: 
   { modified: '2016-12-09T22:55:19.076Z',
     created: '2016-12-09T22:55:19.076Z',
     '1.0.0': '2016-12-09T22:55:19.076Z' },
  homepage: 'https://github.com/mikeerickson/pkg-menu-cli#readme',
  keywords: [ 'package', 'menu', 'script', 'cli' ],
  repository: 
   { type: 'git',
     url: 'git+https://github.com/mikeerickson/pkg-menu-cli.git' },
  author: 'Mike Erickson, codedungeon@gmail.com',
  bugs: { url: 'https://github.com/mikeerickson/pkg-menu-cli/issues' },
  license: 'MIT',
  readmeFilename: 'README.md',
  version: '1.0.0',
  main: 'cli.js',
  bin: { 'package-menu': 'cli.js' },
  scripts: 
   { eslint: 'eslint "./**/*.js"',
     test: 'mocha',
     menu: 'node ./cli.js' },
  reveal: true,
  dependencies: 
   { chalk: '^1.1.3',
     'cli-table2': '^0.2.0',
     conf: '^0.11.2',
     'get-stdin': '^5.0.1',
     meow: '^3.7.0' },
  devDependencies: { chai: '^3.5.0', mocha: '^3.2.0' },
  directories: { test: 'test' },
  gitHead: 'c80b53e83a02be8ad536930d9a23268133ff5e1a',
  dist: 
   { shasum: '43968e1d13da95ab7ec122eb1fa3597a0176ffda',
     tarball: 'https://registry.npmjs.org/package-menu-cli/-/package-menu-cli-1.0.0.tgz' } }

```

**Comment by legodude17** [comment]
Did you make sure to login on all machines?

**Comment by mikeerickson** [comment]
Yes indeed, I am sure I am logged in correctly. I am stumped.  I have same issue going the other way (if I create an npm package @ home) I can't publish from work. 

The bummer part, if I had to chose a location to perform publishing, I would rather it be at home 

So I guess I could start over (but have To use a different package name I would assume)

Ideally, I would like to make it work on both locations ... 

Stumped at this point 

- me

**Comment by mikeerickson** [comment]
Further, if I were not logged in (say at work) one would think I would not be able to publish?

**Comment by legodude17** [comment]
Does your workplace have a proxy or private registry?

**Comment by zkat** [comment]
@mikeerickson Could you do `npm whoami` on both machines? One frustrating bit about npm's current login system is that if you accidentally typo your username, it'll create a new account with the subtle typo. I see that the package you mentioned is owned by https://www.npmjs.com/~mikeerickson, and it's also the only package owned by that user. If your `npm whoami` on your personal machine matches that _exact name_, you _should_ be able to publish.

**Comment by mikeerickson** [comment]
ya, my username on home machine is `codedungeon`

Is it possible to change a package owner?  I am assuming that `npm whoami` on my work machine will be `mikeerickson`

**Comment by mikeerickson** [comment]
whoops, hit send instead too soon.  I am guessing that is the problem 

So if I want to manage the package in question on home machine, I will need to login as `mikeerickson`

**Comment by mikeerickson** [comment]
As expected, I have logged into `home` machine using `mikeerickson` instead of `codedungeon` and all is working now (I am able to publish from home).

Thank you SO MUCH for your assistance, wasnt aware of these various `npm` commands :-)

**Comment by zkat** [comment]
@mikeerickson 

* `npm login`
* log in as `mikeerickson`
* `npm owner add codedungeon package-menu-cli`

then you'll be able to publish from either one :)
