### ISSUE TITLE
npm ERR code 1

### ISSUE THREAD

**Issue by legodude17** [npm/npm#15184]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Whenever I run `npm i rxjs` it gives `npm ERR! code 1` and then doesn't install. No `npm-debug.log` generated. Upon update to `4.0.5`, it doesn't give the error but nothing is installed still.
#### How can the CLI team reproduce the problem?
```
mkdir test
cd test
npm init -y
npm i rxjs
```

### supporting information:

 - `npm -v` prints: 4.0.5
 - `node -v` prints: 6.7.0
 - `npm config get registry` prints: https://registry.npmjs.org
 - Windows, OS X/macOS, or Linux?: Linux galliumos
 - Network issues: Interminntent internet but it was working everywhere else at the time
   - Geographic location where npm was run: California
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by zkat** [comment]
This sounds like something with your network or a hosed npm installation. You can find more details if there isn't an `npm-debug.log` by just running with the `-ddd` flag

**Comment by legodude17** [comment]
@zkat Everything in the output for `-ddd` looks fine, except it printed out the `If you need help, you may report this error at:`, but with loglevel `verb` instead of `error`, and it also printed the `exit [ 0, true]`, and then `code ``. Nothing was isntalled again, but it was added to the cache.

**Comment by legodude17** [comment]
That's strange, it works fine if I add `--save`.

**Comment by GermanBluefox** [comment]
I could find a problem with "npm ERR code 1" with node.js 6 and npm 4.
I had additional field in package.json: "_dependencies" (to store unused packages).
After removing of this attribute everything runs well.
