### ISSUE TITLE
NPM error: Cannot find module 'number-is-nan'

### ISSUE THREAD

**Issue by manuelro** [npm/npm#15186]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
For some reason I get a `cannot find module 'number-is-nan'` error. I already uninstalled nodejs, installed it again and the error remains. The thing is that NPM is not usable, I cannot even checkout its version.

```
$ npm -v
module.js:471
    throw err;
    ^

Error: Cannot find module 'number-is-nan'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\mc_ro\AppData\Roaming\npm\n     ode_modules\npm\node_modules\npmlog\node_modules\gauge\node_mod     ules\string-width\node_modules\code-point-at\index.js:2:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

### supporting information:

 - `npm -v` prints: The error above
 - `node -v` prints: v6.9.2
 - `npm config get registry` prints: The error above
 - Windows, OS X/macOS, or Linux?: Windows
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
This sounds like a hosed `npm` installation. What OS are you on?

**Comment by manuelro** [comment]
Windows 10, but the thing is that this happened today when I decided to update NPM itself.

**Comment by legodude17** [comment]
How did you update nom? The nodes installer for Windows is know to mess up npm installations.

**Comment by manuelro** [comment]
As usual: `npm install -g npm`.

**Comment by manuelro** [comment]
UPDATE: I had to remove the npm-cache folder. I also removed the entire npm folder that remained in the AppData folder after uninstalling NodeJS. I restarted Windows and installed NodeJS again. NPM is now working, but at a very high price: I have to install all the packages I used to have again.

**Comment by legodude17** [comment]
That's great! (Kind of) As I said, that was probably caused by the nodejs installer. Glad it is working again! Can this be closed @KenanY?

**Comment by sanjoggit** [comment]
where is npm-cache folder? where is AppData folder?

**Comment by 328480460** [comment]
i encounter same problem，cannot even checkout its version also，you can reinstall npm: curl -L https://www.npmjs.org/install.sh | sh

**Comment by ckmilse** [comment]
I have the same problem, and luckily I have yarn . and reinstall npm by yarn:  (sudo)yarn global add npm, solve the problem.   I ever up the node version to 9.0.0， when I use 'n' to change  the node version to  6.10.3 , the probler occured
