### ISSUE TITLE
After npm update: Cannot find module 'asynckit'

### ISSUE THREAD

**Issue by designbydc** [npm/npm#15182]
#### I'm opening this issue because:

  - [ ] npm is crashing.

#### What's going wrong?

Error: Cannot find module 'asynckit'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/node_modules/form-data/lib/form_data.js:9:16)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--force"
npm ERR! node v7.2.1
npm ERR! npm  v4.0.3
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'asynckit'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

### supporting information:

 -  OS X/macOS
 - Network issues:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on OS X or Linux.

**Comment by zkat** [comment]
Hey @designbydc. This is very likely an issue where your npm install got broken for some reason. Simply reinstall npm and you should be good to go.

**Comment by designbydc** [comment]
Thanks! With "curl -L http://npmjs.org/install.sh | sudo sh" npm runs again like a charm!

**Comment by crooner** [comment]
I am having the same problem. Tried the curl command, no joy. Tried installing it local, no joy. 

Anyone else having any luck?

**Comment by designbydc** [comment]
Have you tried to delete node_modules in /usr/local/lib/ and to reinstall Node JS? Otherwise if you work in an old project you should delete the modules also and to reinstall the dependencies.

**Comment by itairegev** [comment]
same versions, same error, does anyone have a solution?
