### ISSUE TITLE
refusing to install sass-mediaqueries as a dependency of itself

### ISSUE THREAD

**Issue by Andromeda29** [npm/npm#15181]
#### I'm opening this issue because:

  - [ ] npm is producing an incorrect install.
 

#### What's going wrong?
C:\WINDOWS\system32>npm install sass-mediaqueries
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "sass-mediaqueries"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ENOSELF

npm ERR! Refusing to install sass-mediaqueries as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\WINDOWS\system32\npm-debug.log
### supporting information:
 - Windows
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.

**Comment by zkat** [comment]
hey @Andromeda29! npm [doesn't support installing packages as dependencies of themselves](https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm). The quick answer is that you're probably in a directory with a `package.json` where the `name` is `sass-mediaqueries`. Change the `name` field to anything else and you'll be good to go!
