### ISSUE TITLE
cannot download the appium by [npm install -g appium]

### ISSUE THREAD

**Issue by wuyuzhou12345** [npm/npm#15189]
# want to download the uiAutoTest Framework Appium by the command [npm install -g appium],but come across the following error
npm ERR! Darwin 14.4.0
npm ERR! argv "/usr/local/Cellar/node/7.2.1/bin/node" "/usr/local/bin/npm" "install" "-g" "appium"
npm ERR! node v7.2.1
npm ERR! npm  v3.10.9

npm ERR! shasum check failed for /tmp/npm-3124-75445e03/registry.npmjs.org/appium/-/appium-1.6.2.tgz
npm ERR! Expected: 97090ab31480e79f5df5e946d22fa706c9c789b1
npm ERR! Actual:   933e41900094ae354d430e3cd738e5075cdd4527
npm ERR! From:     https://registry.npmjs.org/appium/-/appium-1.6.2.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/user/npm-debug.log

the nom_debug.log info is following:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/7.2.1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'appium' ]
2 info using npm@3.10.9
3 info using node@v7.2.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData appium
8 silly fetchNamedPackageData appium
9 silly mapToRegistry name appium
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'appium',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'appium',
12 silly mapToRegistry   name: 'appium',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/appium
14 verbose request uri https://registry.npmjs.org/appium
15 verbose request no auth needed
16 info attempt registry request try #1 at 14:27:36
17 verbose request id c829da2c1420595c
18 http request GET https://registry.npmjs.org/appium
19 http 200 https://registry.npmjs.org/appium
20 verbose headers { server: 'nginx/1.10.1',
20 verbose headers   'content-type': 'application/json',
20 verbose headers   'last-modified': 'Fri, 02 Dec 2016 20:23:37 GMT',
20 verbose headers   etag: 'W/"5841d849-7de59"',
20 verbose headers   'content-encoding': 'gzip',
20 verbose headers   'cache-control': 'max-age=300',
20 verbose headers   'content-length': '22893',
20 verbose headers   'accept-ranges': 'bytes',
20 verbose headers   date: 'Sat, 10 Dec 2016 06:27:42 GMT',
20 verbose headers   via: '1.1 varnish',
20 verbose headers   age: '0',
20 verbose headers   connection: 'keep-alive',
20 verbose headers   'x-served-by': 'cache-lcy1149-LCY',
20 verbose headers   'x-cache': 'HIT',
20 verbose headers   'x-cache-hits': '1',
20 verbose headers   'x-timer': 'S1481351262.179228,VS0,VE17',
20 verbose headers   vary: 'Accept-Encoding' }
21 silly get cb [ 200,
21 silly get   { server: 'nginx/1.10.1',
21 silly get     'content-type': 'application/json',
21 silly get     'last-modified': 'Fri, 02 Dec 2016 20:23:37 GMT',
21 silly get     etag: 'W/"5841d849-7de59"',
21 silly get     'content-encoding': 'gzip',
21 silly get     'cache-control': 'max-age=300',
21 silly get     'content-length': '22893',
21 silly get     'accept-ranges': 'bytes',
21 silly get     date: 'Sat, 10 Dec 2016 06:27:42 GMT',
21 silly get     via: '1.1 varnish',
21 silly get     age: '0',
21 silly get     connection: 'keep-alive',
21 silly get     'x-served-by': 'cache-lcy1149-LCY',
21 silly get     'x-cache': 'HIT',
21 silly get     'x-cache-hits': '1',
21 silly get     'x-timer': 'S1481351262.179228,VS0,VE17',
21 silly get     vary: 'Accept-Encoding' } ]
22 verbose get saving appium to /var/root/.npm/registry.npmjs.org/appium/.cache.json
23 verbose correctMkdir /var/root/.npm correctMkdir not in flight; initializing
24 verbose makeDirectory /var/root/.npm creation not in flight; initializing
25 silly makeDirectory /var/root/.npm uid: 0 gid: 0
26 silly install normalizeTree
27 silly loadCurrentTree Finishing
28 silly loadIdealTree Starting
29 silly install loadIdealTree
30 silly cloneCurrentTree Starting
31 silly install cloneCurrentTreeToIdealTree
32 silly cloneCurrentTree Finishing
33 silly loadShrinkwrap Starting
34 silly install loadShrinkwrap
35 silly loadShrinkwrap Finishing
36 silly loadAllDepsIntoIdealTree Starting
37 silly install loadAllDepsIntoIdealTree
38 silly resolveWithNewModule appium@1.6.2 checking installable status
39 silly cache add args [ 'appium', null ]
40 verbose cache add spec appium
41 silly cache add parsed spec Result {
41 silly cache add   raw: 'appium',
41 silly cache add   scope: null,
41 silly cache add   escapedName: 'appium',
41 silly cache add   name: 'appium',
41 silly cache add   rawSpec: '',
41 silly cache add   spec: 'latest',
41 silly cache add   type: 'tag' }
42 silly addNamed appium@latest
43 verbose addNamed "latest" is being treated as a dist-tag for appium
44 info addNameTag [ 'appium', 'latest' ]
45 silly mapToRegistry name appium
46 silly mapToRegistry using default registry
47 silly mapToRegistry registry https://registry.npmjs.org/
48 silly mapToRegistry data Result {
48 silly mapToRegistry   raw: 'appium',
48 silly mapToRegistry   scope: null,
48 silly mapToRegistry   escapedName: 'appium',
48 silly mapToRegistry   name: 'appium',
48 silly mapToRegistry   rawSpec: '',
48 silly mapToRegistry   spec: 'latest',
48 silly mapToRegistry   type: 'tag' }
49 silly mapToRegistry uri https://registry.npmjs.org/appium
50 verbose addNameTag registry:https://registry.npmjs.org/appium not in flight; fetching
51 verbose get https://registry.npmjs.org/appium not expired, no request
52 silly addNameTag next cb for appium with tag latest
53 silly addNamed appium@1.6.2
54 verbose addNamed "1.6.2" is a plain semver version for appium
55 silly mapToRegistry name appium
56 silly mapToRegistry using default registry
57 silly mapToRegistry registry https://registry.npmjs.org/
58 silly mapToRegistry data Result {
58 silly mapToRegistry   raw: 'appium',
58 silly mapToRegistry   scope: null,
58 silly mapToRegistry   escapedName: 'appium',
58 silly mapToRegistry   name: 'appium',
58 silly mapToRegistry   rawSpec: '',
58 silly mapToRegistry   spec: 'latest',
58 silly mapToRegistry   type: 'tag' }
59 silly mapToRegistry uri https://registry.npmjs.org/appium
60 verbose addRemoteTarball https://registry.npmjs.org/appium/-/appium-1.6.2.tgz not in flight; adding
61 verbose addRemoteTarball [ 'https://registry.npmjs.org/appium/-/appium-1.6.2.tgz',
61 verbose addRemoteTarball   '97090ab31480e79f5df5e946d22fa706c9c789b1' ]
62 info retry fetch attempt 1 at 14:27:45
63 info attempt registry request try #1 at 14:27:45
64 http fetch GET https://registry.npmjs.org/appium/-/appium-1.6.2.tgz
65 http fetch 200 https://registry.npmjs.org/appium/-/appium-1.6.2.tgz
66 silly fetchAndShaCheck shasum 97090ab31480e79f5df5e946d22fa706c9c789b1
67 silly rollbackFailedOptional Starting
68 silly rollbackFailedOptional Finishing
69 silly runTopLevelLifecycles Finishing
70 silly install printInstalled
71 verbose stack Error: shasum check failed for /tmp/npm-3124-75445e03/registry.npmjs.org/appium/-/appium-1.6.2.tgz
71 verbose stack Expected: 97090ab31480e79f5df5e946d22fa706c9c789b1
71 verbose stack Actual:   933e41900094ae354d430e3cd738e5075cdd4527
71 verbose stack From:     https://registry.npmjs.org/appium/-/appium-1.6.2.tgz
71 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/sha/index.js:25:8
71 verbose stack     at ReadStream.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/sha/index.js:72:7)
71 verbose stack     at emitNone (events.js:91:20)
71 verbose stack     at ReadStream.emit (events.js:185:7)
71 verbose stack     at endReadableNT (_stream_readable.js:974:12)
71 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:74:11)
71 verbose stack     at process._tickCallback (internal/process/next_tick.js:98:9)
72 verbose cwd /Users/user
73 error Darwin 14.4.0
74 error argv "/usr/local/Cellar/node/7.2.1/bin/node" "/usr/local/bin/npm" "install" "-g" "appium"
75 error node v7.2.1
76 error npm  v3.10.9
77 error shasum check failed for /tmp/npm-3124-75445e03/registry.npmjs.org/appium/-/appium-1.6.2.tgz
77 error Expected: 97090ab31480e79f5df5e946d22fa706c9c789b1
77 error Actual:   933e41900094ae354d430e3cd738e5075cdd4527
77 error From:     https://registry.npmjs.org/appium/-/appium-1.6.2.tgz
78 error If you need help, you may report this error at:
78 error     <https://github.com/npm/npm/issues>
79 verbose exit [ 1, true ]

**Comment by legodude17** [comment]
Hello! This is a duplicated of #14626. Please see [this comment](https://github.com/npm/npm/issues/14626#issuecomment-264371634).

**Comment by zkat** [comment]
Closing as duplicate.
