### ISSUE TITLE
Trying to make a discord bot recieving error

### ISSUE THREAD

**Issue by VadeGFX** [npm/npm#15185]
Sorry this doesn't fit the format, please just tell me what I am doing wrong. The code in the script matches what should be entered, I have no idea where the missing script: Spicii comes from.

0 info it worked if it ends with ok
1 verbose cli [ 'A:\\NodeJS\\node.exe',
1 verbose cli   'A:\\NodeJS\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'Spicii' ]
2 info using npm@3.10.9
3 info using node@v6.9.2
4 verbose config Skipping project config: C:\Users\Vade/.npmrc. (matches userconfig)
5 verbose stack Error: missing script: Spicii
5 verbose stack     at run (A:\NodeJS\node_modules\npm\lib\run-script.js:151:19)
5 verbose stack     at A:\NodeJS\node_modules\npm\lib\run-script.js:61:5
5 verbose stack     at A:\NodeJS\node_modules\npm\node_modules\read-package-json\read-json.js:356:5
5 verbose stack     at handleExists (A:\NodeJS\node_modules\npm\node_modules\read-package-json\read-json.js:329:20)
5 verbose stack     at FSReqWrap.cb [as oncomplete] (fs.js:257:19)
6 verbose cwd C:\Users\Vade
7 error Windows_NT 10.0.14393
8 error argv "A:\\NodeJS\\node.exe" "A:\\NodeJS\\node_modules\\npm\\bin\\npm-cli.js" "run" "Spicii"
9 error node v6.9.2
10 error npm  v3.10.9
11 error missing script: Spicii
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@VadeGFX Make sure to have a `"Spicii"` script defined in your `package.json` before trying to run `npm run Scpicii`. See: https://docs.npmjs.com/cli/run-script
