### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by NiranjanCT** [npm/npm#15188]
$ npm install -g cordova ionic
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova" "ionic"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8

npm ERR! shasum check failed for C:\Users\NTHIMM~1\AppData\Local\Temp\npm-4804-1751aa6a\registry.npmjs.org\ionic\-\ionic-2.1.17.tgz
npm ERR! Expected: fdb438846d8dd0c532ff587fd79d2bf1a5895483
npm ERR! Actual:   96916b73f57ebe0f395f095eb703958332e5a888
npm ERR! From:     https://registry.npmjs.org/ionic/-/ionic-2.1.17.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by legodude17** [comment]
Hello! This is a duplicated of #14626. Please see [this comment](https://github.com/npm/npm/issues/14626#issuecomment-264371634).

**Comment by zkat** [comment]
As @legodude17 says, this is a dupe. Closing :)
