### ISSUE TITLE
browser-sync not installing

### ISSUE THREAD

**Issue by arbitrarymahi** [npm/npm#15191]
groot@Alfred:~$ npm install -g browser-sync
npm ERR! Linux 4.4.0-53-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "browser-sync"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! syscall getaddrinfo

npm ERR! getaddrinfo EAI_AGAIN registry.npmjs.org:443
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/groot/npm-debug.log
groot@Alfred:~$ 
 

this is the error showing in my command prompt. I don't know what to do.

**Comment by legodude17** [comment]
This most likely a problem with your network. Please check your internet connection.

**Comment by Charlotteis** [comment]
@arbitrarymahi 

Are you behind a proxy? You need to check your proxy settings and make sure the proxy can reach https://registry.npmjs.org, which is where packages are fetched from.

The following link may help: https://jjasonclark.com/how-to-setup-node-behind-web-proxy/

**Comment by KenanY** [comment]
Closing as abandoned.
