### ISSUE TITLE
npm ERR! Error: ENOENT, open package.json

### ISSUE THREAD

**Issue by whaone** [npm/npm#15194]
and show like this 
"npm ERR! code ENOENT
npm ERR! errno 34"

**Comment by legodude17** [comment]
What command did you run? If you used `--save*`, then you must have a `package.json` in you current working directory.

**Comment by whaone** [comment]
i run npm test on my server

**Comment by legodude17** [comment]
You can't use npm test without a package.json.  To use `npm test`, you need to put it into the script field in your package.json like:

{
  "scripts": {
    "Test": "echo hi"
  }
}
See this example for your reference: https://docs.npmjs.com/misc/scripts#examples

**Comment by whaone** [comment]
thanks bro
