### ISSUE TITLE
font-awesome not installing

### ISSUE THREAD

**Issue by fannur** [npm/npm#15199]
npm install font-awesome

#### LOG

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'font-awesome' ]
2 info using npm@3.10.9
3 info using node@v7.2.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData font-awesome
8 silly fetchNamedPackageData font-awesome
9 silly mapToRegistry name font-awesome
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'font-awesome',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'font-awesome',
12 silly mapToRegistry   name: 'font-awesome',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/font-awesome
14 verbose request uri https://registry.npmjs.org/font-awesome
15 verbose request no auth needed
16 info attempt registry request try #1 at 23:56:02
17 verbose request id 1e6b09d292561edb
18 http request GET https://registry.npmjs.org/font-awesome
19 http 200 https://registry.npmjs.org/font-awesome
20 verbose headers { server: 'nginx/1.10.1',
20 verbose headers   'content-type': 'application/json',
20 verbose headers   'last-modified': 'Thu, 08 Dec 2016 15:31:46 GMT',
20 verbose headers   etag: 'W/"58497ce2-53fc"',
20 verbose headers   'content-encoding': 'gzip',
20 verbose headers   'cache-control': 'max-age=300',
20 verbose headers   'content-length': '4340',
20 verbose headers   'accept-ranges': 'bytes',
20 verbose headers   date: 'Sun, 11 Dec 2016 20:56:09 GMT',
20 verbose headers   via: '1.1 varnish',
20 verbose headers   age: '0',
20 verbose headers   connection: 'keep-alive',
20 verbose headers   'x-served-by': 'cache-ams4132-AMS',
20 verbose headers   'x-cache': 'HIT',
20 verbose headers   'x-cache-hits': '1',
20 verbose headers   'x-timer': 'S1481489769.755366,VS0,VE66',
20 verbose headers   vary: 'Accept-Encoding' }
21 silly get cb [ 200,
21 silly get   { server: 'nginx/1.10.1',
21 silly get     'content-type': 'application/json',
21 silly get     'last-modified': 'Thu, 08 Dec 2016 15:31:46 GMT',
21 silly get     etag: 'W/"58497ce2-53fc"',
21 silly get     'content-encoding': 'gzip',
21 silly get     'cache-control': 'max-age=300',
21 silly get     'content-length': '4340',
21 silly get     'accept-ranges': 'bytes',
21 silly get     date: 'Sun, 11 Dec 2016 20:56:09 GMT',
21 silly get     via: '1.1 varnish',
21 silly get     age: '0',
21 silly get     connection: 'keep-alive',
21 silly get     'x-served-by': 'cache-ams4132-AMS',
21 silly get     'x-cache': 'HIT',
21 silly get     'x-cache-hits': '1',
21 silly get     'x-timer': 'S1481489769.755366,VS0,VE66',
21 silly get     vary: 'Accept-Encoding' } ]
22 verbose get saving font-awesome to C:\Users\fannur\AppData\Roaming\npm-cache\registry.npmjs.org\font-awesome\.cache.json
23 verbose correctMkdir C:\Users\fannur\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
24 verbose makeDirectory C:\Users\fannur\AppData\Roaming\npm-cache creation not in flight; initializing
25 verbose makeCacheDir UID & GID are irrelevant on win32
26 silly install normalizeTree
27 silly loadCurrentTree Finishing
28 silly loadIdealTree Starting
29 silly install loadIdealTree
30 silly cloneCurrentTree Starting
31 silly install cloneCurrentTreeToIdealTree
32 silly cloneCurrentTree Finishing
33 silly loadShrinkwrap Starting
34 silly install loadShrinkwrap
35 silly loadShrinkwrap Finishing
36 silly loadAllDepsIntoIdealTree Starting
37 silly install loadAllDepsIntoIdealTree
38 silly resolveWithNewModule font-awesome@4.7.0 checking installable status
39 silly cache add args [ 'font-awesome', null ]
40 verbose cache add spec font-awesome
41 silly cache add parsed spec Result {
41 silly cache add   raw: 'font-awesome',
41 silly cache add   scope: null,
41 silly cache add   escapedName: 'font-awesome',
41 silly cache add   name: 'font-awesome',
41 silly cache add   rawSpec: '',
41 silly cache add   spec: 'latest',
41 silly cache add   type: 'tag' }
42 silly addNamed font-awesome@latest
43 verbose addNamed "latest" is being treated as a dist-tag for font-awesome
44 info addNameTag [ 'font-awesome', 'latest' ]
45 silly mapToRegistry name font-awesome
46 silly mapToRegistry using default registry
47 silly mapToRegistry registry https://registry.npmjs.org/
48 silly mapToRegistry data Result {
48 silly mapToRegistry   raw: 'font-awesome',
48 silly mapToRegistry   scope: null,
48 silly mapToRegistry   escapedName: 'font-awesome',
48 silly mapToRegistry   name: 'font-awesome',
48 silly mapToRegistry   rawSpec: '',
48 silly mapToRegistry   spec: 'latest',
48 silly mapToRegistry   type: 'tag' }
49 silly mapToRegistry uri https://registry.npmjs.org/font-awesome
50 verbose addNameTag registry:https://registry.npmjs.org/font-awesome not in flight; fetching
51 verbose get https://registry.npmjs.org/font-awesome not expired, no request
52 silly addNameTag next cb for font-awesome with tag latest
53 silly addNamed font-awesome@4.7.0
54 verbose addNamed "4.7.0" is a plain semver version for font-awesome
55 silly mapToRegistry name font-awesome
56 silly mapToRegistry using default registry
57 silly mapToRegistry registry https://registry.npmjs.org/
58 silly mapToRegistry data Result {
58 silly mapToRegistry   raw: 'font-awesome',
58 silly mapToRegistry   scope: null,
58 silly mapToRegistry   escapedName: 'font-awesome',
58 silly mapToRegistry   name: 'font-awesome',
58 silly mapToRegistry   rawSpec: '',
58 silly mapToRegistry   spec: 'latest',
58 silly mapToRegistry   type: 'tag' }
59 silly mapToRegistry uri https://registry.npmjs.org/font-awesome
60 verbose addRemoteTarball https://registry.npmjs.org/font-awesome/-/font-awesome-4.7.0.tgz not in flight; adding
61 verbose addRemoteTarball [ 'https://registry.npmjs.org/font-awesome/-/font-awesome-4.7.0.tgz',
61 verbose addRemoteTarball   '8fa8cf0411a1a31afd07b06d2902bb9fc815a133' ]
62 info retry fetch attempt 1 at 23:56:06
63 info attempt registry request try #1 at 23:56:06
64 http fetch GET https://registry.npmjs.org/font-awesome/-/font-awesome-4.7.0.tgz
65 http fetch 200 https://registry.npmjs.org/font-awesome/-/font-awesome-4.7.0.tgz
66 info retry will retry, error on last attempt: Error: read ECONNRESET
67 silly fetchAndShaCheck shasum 8fa8cf0411a1a31afd07b06d2902bb9fc815a133
68 silly rollbackFailedOptional Starting
69 silly rollbackFailedOptional Finishing
70 silly runTopLevelLifecycles Finishing
71 silly install printInstalled
72 verbose stack Error: shasum check failed for C:\Users\fannur\AppData\Local\Temp\npm-1628-5d939d96\registry.npmjs.org\font-awesome\-\font-awesome-4.7.0.tgz
72 verbose stack Expected: 8fa8cf0411a1a31afd07b06d2902bb9fc815a133
72 verbose stack Actual:   d5cc694a3199905d5cc038631d87f0db3c22a6c7
72 verbose stack From:     https://registry.npmjs.org/font-awesome/-/font-awesome-4.7.0.tgz
72 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:25:8
72 verbose stack     at ReadStream.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:72:7)
72 verbose stack     at emitNone (events.js:91:20)
72 verbose stack     at ReadStream.emit (events.js:185:7)
72 verbose stack     at endReadableNT (_stream_readable.js:974:12)
72 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:74:11)
72 verbose stack     at process._tickCallback (internal/process/next_tick.js:98:9)
73 verbose cwd C:\OpenServer\domains\project1
74 error Windows_NT 10.0.10240
75 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "font-awesome"
76 error node v7.2.0
77 error npm  v3.10.9
78 error shasum check failed for C:\Users\fannur\AppData\Local\Temp\npm-1628-5d939d96\registry.npmjs.org\font-awesome\-\font-awesome-4.7.0.tgz
78 error Expected: 8fa8cf0411a1a31afd07b06d2902bb9fc815a133
78 error Actual:   d5cc694a3199905d5cc038631d87f0db3c22a6c7
78 error From:     https://registry.npmjs.org/font-awesome/-/font-awesome-4.7.0.tgz
79 error If you need help, you may report this error at:
79 error     <https://github.com/npm/npm/issues>
80 verbose exit [ 1, true ]

**Comment by legodude17** [comment]
Hello! This is a duplicated of #14626. Please see [this comment](https://github.com/npm/npm/issues/14626#issuecomment-264371634).

**Comment by zkat** [comment]
Closing as dupe, as @legodude17 says.
