### ISSUE TITLE
typings install issue

### ISSUE THREAD

**Issue by ksterol4all** [npm/npm#15202]
PS C:\Users\ksterol\Documents\visual studio 2015\Projects\AngularJS2Setup\src\AngularJS2Setup> npm run tyings
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\np
m-cli.js" "run" "tyings"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4

npm ERR! missing script: tyings
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\ksterol\Documents\visual studio 2015\Projects\AngularJS2Setup\src\AngularJS2Setup\npm-debug.log
PS C:\Users\ksterol\Documents\visual studio 2015\Projects\AngularJS2Setup\src\AngularJS2Setup> typings install
C:\Users\ksterol\AppData\Roaming\npm\node_modules\typings\node_modules\typings-core\node_modules\strip-bom\index.js:2
module.exports = x => {
                   ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\ksterol\AppData\Roaming\npm\node_modules\typings\node_modules\typings-core\dist\util
s\fs.js:6:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
PS C:\Users\ksterol\Documents\visual studio 2015\Projects\AngularJS2Setup\src\AngularJS2Setup>

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'tyings' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose node symlink C:\Program Files (x86)\nodejs\\node.exe
5 verbose stack Error: missing script: tyings
5 verbose stack     at run (C:\Program Files (x86)\nodejs\node_modules\npm\lib\run-script.js:165:19)
5 verbose stack     at C:\Program Files (x86)\nodejs\node_modules\npm\lib\run-script.js:81:5
5 verbose stack     at C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:52:40
5 verbose stack     at C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:376:33
5 verbose stack     at checkBinReferences_ (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:341:59)
5 verbose stack     at final (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:373:17)
5 verbose stack     at then (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:127:33)
5 verbose stack     at C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:317:48
5 verbose stack     at evalmachine.<anonymous>:263:20
5 verbose stack     at OpenReq.Req.done (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:141:5)
6 verbose cwd C:\Users\ksterol\Documents\visual studio 2015\Projects\AngularJS2Setup\src\AngularJS2Setup
7 error Windows_NT 6.3.9600
8 error argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "tyings"
9 error node v0.12.2
10 error npm  v2.7.4
11 error missing script: tyings
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
```
11 error missing script: tyings
```

@ksterol4all Make sure you have a `"tyings"` script defined in your `package.json`. Or, perhaps, that's simply a typo of `"typings"` ;)
