### ISSUE TITLE
On windows 7 I am getting npm ERR ! for "npm install" 

### ISSUE THREAD

**Issue by pareekshita-webonise** [npm/npm#15209]
#### I'm opening this issue because:

  - [ ] npm is crashing.

#### What's going wrong?
- `npm install` prints:
   npm WARN package.json netmagic-front-end@1.0.0 No description
   npm WARN package.json netmagic-front-end@1.0.0 No repository field.
   npm WARN package.json Dependency 'babel-preset-react' exists in both dependencies and    
   devDependencies, using 'babel-preset-react@^6.5.0' from dependencies
   npm WARN package.json Dependency 'history' exists in both dependencies and devDependencies,   
   using 'history@^2.1.1' from dependencies
   npm WARN package.json Dependency 'react-select' exists in both dependencies and 
   devDependencies, using 'react-select@^1.0.0-rc.1' from dependencies
   npm ERR! Windows_NT 6.1.7601 
   npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program  
   Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
   npm ERR! node v4.4.7
   npm ERR! npm  v2.15.8
   npm ERR! code SELF_SIGNED_CERT_IN_CHAIN
   npm ERR! self signed certificate in certificate chain
   npm ERR!
   npm ERR! If you need help, you may report this error at:
   npm ERR!     <https://github.com/npm/npm/issues>
   npm ERR! Please include the following file with any support request:
   npm ERR!     D:\Projects\gitsrc\Netmagic-static-mnp\npm-debug.log

**Comment by legodude17** [comment]
Have you taken a look at http://blog.npmjs.org/post/78165272245/more-help-with-selfsignedcertinchain-and-npm? See if the steps outlined there work for you.

If it does NOT:

1. Are you behind a proxy?
2. How are you trying to use it?
