### ISSUE TITLE
npm i -S @private/package endless unstoppable loop (video)

### ISSUE THREAD

**Issue by koresar** [npm/npm#15200]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

CLI can't be stopped with Ctrl+C.

#### How can the CLI team reproduce the problem?

I accidentally made the `npm i -S @private/package` command to loop. Here are the scripts from packgge.json which somehow made it looped:
```js
    "shrinkwrap": "rm -f npm-shrinkwrap.json && npm install && npm shrinkwrap",
    "reshrinkwrap": "npm run clean && npm run shrinkwrap",
    "preinstall": "npm run config",
    "postinstall": "npm run compile",
    "pretest": "npm run lint && npm run config"
```
That's not a problem. I'll fix it.

But! Ctrl+C can't stop the loop. See the [video](https://youtu.be/6ND0xaQ6c2o).

### supporting information:

 - `npm -v` prints: 3.10.10
 - `node -v` prints: v6.9.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: OS X
 - Network issues:
   - Geographic location where npm was run: Australia, Sydney
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by claireinez** [comment]
I had a similar issue where if I ran `top` in a terminal, I could see a new npm process was constantly being started (hence why Ctrl+C wasn't able to stop the loop). For me it seemed to be caused by calling the script "shrinkwrap" so try changing that to a different name?
