### ISSUE TITLE
npm error

### ISSUE THREAD

**Issue by LeviMischael** [npm/npm#15207]
C:\Users\User>npm install -g cordova
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9

npm ERR! shasum check failed for C:\Users\User\AppData\Local\Temp\npm-2932-a0668d53\registry.npmjs.org\npm\-\npm-2.15.11.tgz
npm ERR! Expected: 350588fba9cd8d384cf9a6e8dc0fef0f94992b7c
npm ERR! Actual:   c02beca67ad3f8b787b6d4c85a7d22377114870e
npm ERR! From:     https://registry.npmjs.org/npm/-/npm-2.15.11.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\User\npm-debug.log

**Comment by legodude17** [comment]
Hello! This is a duplicated of #14626. Please see [this comment](https://github.com/npm/npm/issues/14626#issuecomment-264371634).

**Comment by zkat** [comment]
Closing as duplicate!
