### ISSUE TITLE
how to run different version of node on same machine ?

### ISSUE THREAD

**Issue by jpca999** [npm/npm#15212]
I have more than one application running on same box, is it possible to make then run via their respective node version ?

The reason I can't run on same node version is coz they give erros in the installing bower files and also while running npm install...

**Comment by legodude17** [comment]
This isn't a `npm` issue, but you can use `nvm` or `n` to switch between different versions easily.

**Comment by jpca999** [comment]
I have to run both apps all the time.. Still possible ?

**Comment by KenanY** [comment]
Closing since this is mostly unrelated to `npm`, but feel free to continue discussion either here or at <https://github.com/nodejs/help> :)
