### ISSUE TITLE
npm is doing something I dont understand

### ISSUE THREAD

**Issue by sanu42** [npm/npm#15218]
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\rainilim\Deskt                                                   op\helo\package.json'
npm WARN helo No description
npm WARN helo No repository field.
npm WARN helo No README data
npm WARN helo No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.0.15 (node_modules\io                                                   nic\node_modules\ionic-app-lib\node_modules\glob-watcher\node_modules\chokidar\n                                                   ode_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@                                                   1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"                                                   })

**Comment by Charlotteis** [comment]
If you are doing `npm install` without a package.json with dependencies in your folder, it wont work.  Do you have a package.json in the folder you're running `npm install` in?

**Comment by KenanY** [comment]
Closing as abandoned.
