### ISSUE TITLE
npm crash when search

### ISSUE THREAD

**Issue by sarkiroka** [npm/npm#15214]
#### I'm opening this issue because:

  - [X ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

everything

#### How can the CLI team reproduce the problem?

$ npm search mocha
npm WARN Building the local index for the first time, please be patient
 
<--- Last few GCs --->

  107030 ms: Mark-sweep 1095.6 (1434.6) -> 1068.3 (1416.1) MB, 810.1 / 0.0 ms [allocation failure] [GC in old space requested].
  107924 ms: Mark-sweep 1068.3 (1416.1) -> 1068.2 (1420.1) MB, 894.7 / 0.0 ms [allocation failure] [GC in old space requested].
  108815 ms: Mark-sweep 1068.2 (1420.1) -> 1068.2 (1382.1) MB, 891.0 / 0.0 ms [last resort gc].
  109706 ms: Mark-sweep 1068.2 (1382.1) -> 1068.1 (1376.1) MB, 891.1 / 0.0 ms [last resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x17758f9cfb51 <JS Object>
    1: fromString(aka fromString) [buffer.js:195] [pc=0x2d91394d6ff0] (this=0x17758f904381 <undefined>,string=0x33af5a88d6c9 <Very long string[224377651]>,encoding=0x17758f9dd329 <String[4]: utf8>)
    2: from [buffer.js:95] [pc=0x2d91394471c2] (this=0x1fa8ae3a59c9 <JS Function Buffer (SharedFunctionInfo 0x37d3693f7661)>,value=0x33af5a88d6c9 <Very long string[224377651]>,encodingOrOffset=0x1775...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [npm]
 2: 0x109838c [npm]
 3: v8::Utils::ReportApiFailure(char const*, char const*) [npm]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [npm]
 5: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [npm]
 6: v8::internal::String::SlowFlatten(v8::internal::Handle<v8::internal::ConsString>, v8::internal::PretenureFlag) [npm]
 7: v8::internal::String::Flatten(v8::internal::Handle<v8::internal::String>, v8::internal::PretenureFlag) [npm]
 8: v8::String::WriteUtf8(char*, int, int*, int) const [npm]
 9: node::StringBytes::Write(v8::Isolate*, char*, unsigned long, v8::Local<v8::Value>, node::encoding, int*) [npm]
10: node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) [npm]
11: node::Buffer::CreateFromString(v8::FunctionCallbackInfo<v8::Value> const&) [npm]
12: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [npm]
13: 0x9e6a22 [npm]
14: 0x9e709e [npm]
15: 0x2d91390092a7
Félbeszakítva (core készült)

### supporting information:

 - `npm -v` prints: 3.10.3
 - `node -v` prints: 6.7.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: linux
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
This was already fixed in `npm@4.0.0`.
