### ISSUE TITLE
Test check registry status?

### ISSUE THREAD

**Issue by 45kb** [npm/npm#15213]
Hi, sorry for bothering, i have some doubt and thought to ask to you.

I noticed that the `stdout` of `npm ping registry` is always `{}` on my machine.

Adding `--verbose` i can see the request and it is `ok`, so i suppose `{}` means that the registry status is ON, correct?

Which is then the returned stdout or stderr in case the registry is down/OFF?

Also, would you suggest a different way or command to check for the registry status btw?

Thank you.

**Comment by legodude17** [comment]
Yes, `npm ping` would error if you had a connection issue. I have a PR to improve the output. Please +1 #14461.

**Comment by 45kb** [comment]
@legodude17 awesome! thank you, i'll wait for that compulsively 👍
