### ISSUE TITLE
Git working directory not clean

### ISSUE THREAD

**Issue by Spidersouris** [npm/npm#15211]
#### I'm opening this issue because:

  - [x] npm is crashing.

#### What's going wrong?

I'm trying to update my Atom package. However, when I send "apm publish patch", an error is occurring, saying "Git working directory not clean"

#### How can the CLI team reproduce the problem?

https://gist.github.com/Spidersouris/76150dc795d333cdd16509cefcc9b47c

### supporting information:

 - `npm -v` prints: 3.9.5
 - `node -v` prints: v6.2.2
 - `npm config get registry` prints: https://registry.npmjs.org
 - Windows, OS X/macOS, or Linux?: Windows

**Comment by legodude17** [comment]
Is your git working directory clean?

**Comment by Spidersouris** [comment]
Yes. Did `git clean -f/-n/-i` multiple times and there are no "trash" files in the directory. 

[Screenshot](https://puu.sh/sOr4z/62ac0f7cb1.png)

**Comment by legodude17** [comment]
Try just `git add . && git commit`.

**Comment by Spidersouris** [comment]
Thanks. It worked.

**Comment by arif98741** [comment]
wow git add . && git commit work for me. I really appreciated
