### ISSUE TITLE
npm install -g vue-cli error

### ISSUE THREAD

**Issue by hzdzlwh** [npm/npm#15222]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administrator.US
ER-20150612OL\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "insta
ll" "-g" "vue-cli"
npm ERR! node v6.9.2
npm ERR! npm  v3.0.0

npm ERR! Maximum call stack size exceeded
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     E:\vue-cli\npm-debug.log

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@hzdzlwh Does this also occur with the latest version of `npm`?

**Comment by hzdzlwh** [comment]
The npm is latest version

**Comment by KenanY** [comment]
@hzdzlwh `npm@3.0.0` is **not** the latest version of `npm`. Please see <https://github.com/npm/npm/releases>.

**Comment by hzdzlwh** [comment]
what should I do? Thank you very much

**Comment by KenanY** [comment]
@hzdzlwh <https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm>

**Comment by Charlotteis** [comment]
`npm install -g npm@latest`

**Comment by KenanY** [comment]
Closing as abandoned. Can reopen if this is still an issue :)
