### ISSUE TITLE
npm documentation doesn't mention prepare script

### ISSUE THREAD

**Issue by AgentME** [npm/npm#15226]
https://docs.npmjs.com/misc/scripts mentions the partly-deprecated prepublish script without mentioning prepare.

**Comment by zkat** [comment]
Closing as a duplicate of https://github.com/npm/docs/issues/636 -- we're having some issues with syncing the npm repo with the site. You can see that https://github.com/npm/npm/blob/latest/doc/misc/npm-scripts.md has already been updated. Thanks for the reminder, though!

**Comment by pke** [comment]
This docs page is still not updated. I just ran into this when updating to npm 4.3.0 and having a "prepare" command in my package.json that I used in ancient times.

**Comment by bfreis** [comment]
We're approaching the end of March 2017 (ie, over 3 months), and the documentation page is still not updated... seriously?
