### ISSUE TITLE
Upgrading npm from version >=3 via `npm install -g npm@latest` version fails on Docker. 

### ISSUE THREAD

**Issue by lxe** [npm/npm#15225]
#### I'm opening this issue because:

  - [X] npm is crashing.
  - [X] npm is producing an incorrect install.
  - [X] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Running `npm install@latest -g' using npm 3.10.9 shipped with node v6.9.2 breaks npm installation on docker.

#### How can the CLI team reproduce the problem?

1. Make the following Dockerfile:

```
FROM ubuntu

RUN apt-get update && apt-get -y install curl
RUN cd /usr && curl -s https://nodejs.org/dist/v6.9.2/node-v6.9.2-linux-x64.tar.gz | tar -zx --strip-components=1

# Succeeds
RUN npm -v

# Succeeds
RUN npm install npm@3 -g

# Fails
RUN npm -v

CMD npm -v
```

2. Build it:

```
docker build .
```

3. Observe that layer `RUN npm -v` after installing npm and overriding the previous installation now fails with:

```
Step 6/7 : RUN npm -v
 ---> Running in 40a70815247d
module.js:471
    throw err;
    ^

Error: Cannot find module 'npmlog'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /usr/lib/node_modules/npm/bin/npm-cli.js:19:13
    at Object.<anonymous> (/usr/lib/node_modules/npm/bin/npm-cli.js:75:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
```

NOTE: I tested the npm 1.4.28 (node 0.10.42) -> 3 upgrade, and that succeeds! This means that this is some sort of a regression.

I suspect Docker permission/ownership nuances and other things I don't understand.

### supporting information:

 - `npm -v` prints: 3.10.9
 - `node -v` prints: 6.9.2
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?: Darwin *** 16.1.0 Darwin Kernel Version 16.1.0: Thu Oct 13 21:26:57 PDT 2016; root:xnu-3789.21.3~60/RELEASE_X86_64 x86_64
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [X] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by lxe** [comment]
This seems very similar to the errors npm used to have occasionally which prevented upgrades.

**Comment by lxe** [comment]
NOTE: I tested the npm 1.4.28 (node 0.10.42) -> 3 upgrade, and that succeeds! This means that this is some sort of a regression.

**Comment by DrStrangepork** [comment]
This issue continues in v4.1.0. The problem is the same when using `npm update`.

After running `npm install -g npm@4`, I get similar errors about missing `'semver'`. This is the contents of my `/usr/lib/node_modules/npm` folder:
```
JSONStream
glob
graceful-fs
inflight
mississippi
node-gyp
npm-registry-client
npmlog
readable-stream
request
sorted-union-stream
which
```

Shouldn't the contents of that folder match what is in `"bundleDependencies"` or `"dependencies"` in `/usr/lib/node_modules/package.json`?

**Comment by DrStrangepork** [comment]
Workaround: manual install (`curl -sL https://www.npmjs.org/install.sh | sh`) works as expected and results in a `/usr/lib/node_modules/npm/node_modules` folder that contains 85 modules.

**Comment by lxe** [comment]
Related?: 9863

**Comment by hugodes** [comment]
I have the same issue in docker: 
`RUN npm install npm@4.1.1 -g`
`npm install`

I get:

> module.js:472
>     throw err;
>     ^
> 
> Error: Cannot find module 'semver'
>     at Function.Module._resolveFilename (module.js:470:15)
>     at Function.Module._load (module.js:418:25)
>     at Module.require (module.js:498:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/unsupported.js:2:14)
>     at Module._compile (module.js:571:32)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:488:32)
>     at tryModuleLoad (module.js:447:12)
>     at Function.Module._load (module.js:439:3)

**Comment by hjhsalo** [comment]
I observe same problem with missing modules when installing NodeJS6.x from NodeSource on Debian Jessie based baseimage and afterwards updating npm using ```npm install -g npm```.

```
FROM python:2.7

# Install dependencies
RUN apt-get update \
    && apt-get -qy upgrade --fix-missing --no-install-recommends \
    # Node.js
    && curl -sL https://deb.nodesource.com/setup_6.x | bash - \
    && apt-get install -y nodejs \
    && apt-get clean autoclean
    
RUN npm install -g npm

```

As pointed out by [DrStrangepork](https://github.com/npm/npm/issues/15225#issuecomment-267839920), ```curl -sL https://www.npmjs.org/install.sh | sh``` works perfectly as a workaround.

Updating npm using npm works fine if I first downgrade from V3 to V2 ```npm install -g npm@latest-2``` and then upgrade using ```npm install npm@latest -g```.

If I use Node4.x installer (```curl -sL https://deb.nodesource.com/setup_4.x | $sudo bash -```) npm updates successfully as this installer comes with npm V2.15.11.
NodeJS6.x installer comes with npm V3.10.10.

Tested using Docker 1.13.0 and v1.12.5. No differences. Same errors happen regardless of version.
Docker was running on Ubuntu 16.04 -derivate with kernel 4.4.0-62-generic.

Strangely enough when I build the same Dockerfile using Arch Linux 2017-02-01 npm updates successfully and build succeeds.
Note that this Arch build used a newer kernel (4.9.6-1-ARCH) than Ubuntu.

**Comment by euanmillar** [comment]
I have tried the manual install suggested by @DrStrangepork  and my npm has updated, but I still get the "semver" error.  I'm using the nodesource/trusty:5.1 image.  

My node version is therefore: 5.1.1
My NPM version is: 4.5.0
