### ISSUE TITLE
Incorrect username or password

### ISSUE THREAD

**Issue by fetoolbox** [npm/npm#15228]
➜  ~ npm adduser --verbose
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'adduser',
npm verb cli   '--verbose' ]
npm info using npm@4.0.3
npm info using node@v6.2.0
npm verb config Skipping project config: /Users/Junyi/.npmrc. (matches userconfig)
Username: junyiz
Password: 
Email: (this IS public) ipaper@live.cn
npm verb adduser before first PUT { _id: 'org.couchdb.user:junyiz',
npm verb adduser   name: 'junyiz',
npm verb adduser   password: 'XXXXX',
npm verb adduser   email: 'ipaper@live.cn',
npm verb adduser   type: 'user',
npm verb adduser   roles: [],
npm verb adduser   date: '2016-12-15T07:05:18.428Z' }
npm verb request uri https://registry.npmjs.org/-/user/org.couchdb.user:junyiz
npm verb request new user, so can't send auth
npm info attempt registry request try #1 at 15:05:18
npm verb request id 75789d6fa92f062b
npm http request PUT https://registry.npmjs.org/-/user/org.couchdb.user:junyiz
npm http 401 https://registry.npmjs.org/-/user/org.couchdb.user:junyiz
npm verb headers { 'content-type': 'application/json',
npm verb headers   'cache-control': 'max-age=300',
npm verb headers   'content-length': '46',
npm verb headers   'accept-ranges': 'bytes',
npm verb headers   date: 'Thu, 15 Dec 2016 07:05:23 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-ams4430-AMS',
npm verb headers   'x-cache': 'MISS',
npm verb headers   'x-cache-hits': '0',
npm verb headers   'x-timer': 'S1481785522.744354,VS0,VE667',
npm verb headers   vary: 'Accept-Encoding' }
npm verb request invalidating /Users/Junyi/.npm/registry.npmjs.org/-/user/org.couchdb.user_3Ajunyiz on PUT
npm verb adduser back [ { Error: Registry returned 401 for PUT on https://registry.npmjs.org/-/user/org.couchdb.user:junyiz
npm verb adduser       at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:302:12)
npm verb adduser       at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:280:14)
npm verb adduser       at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:210:14)
npm verb adduser       at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:186:22)
npm verb adduser       at emitTwo (events.js:106:13)
npm verb adduser       at Request.emit (events.js:191:7)
npm verb adduser       at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1081:10)
npm verb adduser       at emitOne (events.js:96:13)
npm verb adduser       at Request.emit (events.js:188:7)
npm verb adduser       at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1001:12) statusCode: 401, code: 'E401' },
npm verb adduser   { ok: false, id: 'org.couchdb.user:undefined' },
npm verb adduser   '{"ok":false,"id":"org.couchdb.user:undefined"}' ]
npm WARN adduser Incorrect username or password
npm WARN adduser You can reset your account by visiting:
npm WARN adduser 
npm WARN adduser     https://npmjs.org/forgot
npm WARN adduser 
npm verb stack Error: Registry returned 401 for PUT on https://registry.npmjs.org/-/user/org.couchdb.user:junyiz
npm verb stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:302:12)
npm verb stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:280:14)
npm verb stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:210:14)
npm verb stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:186:22)
npm verb stack     at emitTwo (events.js:106:13)
npm verb stack     at Request.emit (events.js:191:7)
npm verb stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1081:10)
npm verb stack     at emitOne (events.js:96:13)
npm verb stack     at Request.emit (events.js:188:7)
npm verb stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1001:12)
npm verb statusCode 401
npm verb cwd /Users/Junyi
npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "adduser" "--verbose"
npm ERR! node v6.2.0
npm ERR! npm  v4.0.3
npm ERR! code E401

npm ERR! Registry returned 401 for PUT on https://registry.npmjs.org/-/user/org.couchdb.user:junyiz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm verb exit [ 1, true ]

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Junyi/npm-debug.log

**Comment by zkat** [comment]
@fetoolbox as the message says, your username/password are incorrect. Did you typo them? If you're still getting this after checking you have the right password, try resetting it at https://npmjs.org/forgot

**Comment by fetoolbox** [comment]
@zkat when i reset password, from the link in the email, npmjs.com always as follows:

whoops
looks like the token has expired :-(
The email you received has a one-time-use-only link.

You are seeing this message because you either already clicked on that link, someone else clicked on it for you (silly spam filters), or the link expired.

If you feel this error is the result of a bug, please contact us and reference the following unique error number:

1481793914655:www-14-west.internal.npmjs.com:404:iwo559si:60276
Be sure to let us know what you were doing and how you got here so we can help you as quickly as possible!

**Comment by zkat** [comment]
@fetoolbox It's most likely (as the message says) that some sort of scanning software used up your token before you clicked. please email that to support@npmjs.com and ask for a password reset. They should be able to take it from there. I'm going to close this since it's gonna be tracked by support now.

**Comment by fetoolbox** [comment]
@zkat thinks
