### ISSUE TITLE
Cannot find module 'read-cmd-shim' when run npm install

### ISSUE THREAD

**Issue by huangzhiyang166** [npm/npm#15229]
when i run npm install, npm publish, npm update, i get：
`npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administrator\\Appta\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "npm" "-g"
npm ERR! node v6.9.2
npm ERR! npm  v3.7.0
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'read-cmd-shim'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
`

**Comment by legodude17** [comment]
This is most likely a broken `npm` installation. Maybe try reinstalling.
