### ISSUE TITLE
npm ERR! Cannot read property 'path' of null

### ISSUE THREAD

**Issue by pradip-Kachhadiya** [npm/npm#15227]
C:\Users\Abc>npm install -g
npm ERR! addLocal Could not install C:\Users\Abc
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Abc\\AppData\\Ro
aming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g"
npm ERR! node v7.2.1
npm ERR! npm  v4.0.5

npm ERR! Cannot read property 'path' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Abc\npm-debug.log

> i have reinstall node then this error occurs.

>

**Comment by lrosario** [comment]
same here.
devil:~/ $ npm install -g                                                                                         [8:47:58]
npm ERR! addLocal Could not install /home/devil
npm ERR! Linux 4.8.11-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g"
npm ERR! node v7.2.0
npm ERR! npm  v4.0.3

npm ERR! Cannot read property 'path' of null
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/devil/npm-debug.log

**Comment by Charlotteis** [comment]
Running `npm install -g` on it's own will make that happen.

**Comment by legodude17** [comment]
@Charlotteis, yes you must include a package name with `npm install -g`, but `npm` should give a better error message in that case.

**Comment by Charlotteis** [comment]
@legodude17 absolutely!

**Comment by CaptainGones** [comment]
`npm install -g babel@5.6.23`

-g before

**Comment by edi9999** [comment]
It seems to work with `npm install -g babel@5.6.23`, but not with `npm install babel@5.6.23 -g `

**Comment by vladyn** [comment]
It's not working for me with in both ways either.

**Comment by ishu-freelancer** [comment]
It works for me.. 
Please try this line without mention version code with the package name. 
npm install -g package-name
e.g. npm install -g  freeweb

**Comment by Tanngrisnir** [comment]
npm config -global set proxy http://proxy:00
npm config -global set http-proxy http://proxy:00
npm config -global set https-proxy http://proxy:00

**Comment by StatikVerse** [comment]
For me, it didn't work with the `-g` before the package name, then worked with the `-g` after the package name...

**Comment by powercycle** [comment]
Tanngrisnir, thanks!
had a typo for https-proxy.

**Comment by DrSpeed123** [comment]
StatikVerse, thanks!
On my win7 with Kaspersky it's the one solution that works!
