### ISSUE TITLE
Issue with npm install <module-name>

### ISSUE THREAD

**Issue by Maverick13727** [npm/npm#15223]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Whenever user tries npm install --save-dev gulp I get the issue "Not a valid cache tarball name: C:\Users\Maverick\AppData\Local\Temp\npm-10340-9d52c9be\registry.npmjs.org\gulp\-\gulp-3.9.1.tgz"
The complete error message image is attached.
#### How can the CLI team reproduce the problem?
Please find  attached a zip containing the debug-log and error message image

### supporting information:

 - `npm -v` prints: v3.10.9
 - `node -v` prints: v6.9.2
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows 10
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
There isn't any image I can see...
Please try updating `npm` to 4.0.4 with `npm install npm@latest`. If that doesn't work, try installing latest version from the [homepage.](https://github.com/npm/npm#readme).

**Comment by KenanY** [comment]
@Maverick13727 I suggest upload the log file to <https://gist.github.com> and posting the link here. Thanks :)

**Comment by Maverick13727** [comment]
Hey guys,

Thankyou for your responses.
Pardon my ignorance wrt GitHub issue creation.I had uploaded a zip containing the text and image but somehow it ended up not being part of the issue.

Please find the link to the npm-debug.txt log  file
https://gist.github.com/Maverick13727/6e81872336a6eb4fc1a46e086e3c6e4b

Also please find the attached image file
![imageerrormessgae](https://cloud.githubusercontent.com/assets/18599528/21212231/b188e980-c2b0-11e6-987c-bd56cfe55815.PNG)

Kindly let me in case of any further clarifications! 

@legodude17 I had tried npm install npm@latest but was not able to execute the command successfully due to this particular issue .I will try the latest version from the homepage.

Thank-you
Prateek

**Comment by zkat** [comment]
@Maverick13727 the default value for `npm config get cache` on Windows should be `%AppData%\npm-cache`. If running `npm config get cache` returns `%AppData%`, then simply do `npm config set cache %AppData%\npm-cache` and you should be good to go. lmk if that doesn't work.

either way, having things other than npm cache things inside your npm cache is going to cause Bad Things™ to happen.

**Comment by Maverick13727** [comment]
@zkat Thank-you ! It's working now! I put the cache location to %AppData%\npm-cache and the issue got resolved!

The only thing I would like to point out here is that when I installed a fresh copy of node and npm and
tried retrieving the cache value through **npm config get cache** .. I got it as  **C:\Users\Maverick\.npmrc** This was my deafult value.

Thank-you npm team for your concerns and help! highly appreciated ..this was a blocker for me for past 2 days!

@zkat Pardon my ignorance here but should I close the issue or the npm team will do it ?

Cheers
Prateek

**Comment by zkat** [comment]
@Maverick13727 that's super weird and I really don't know why that happened. If it was a bug, I assume we'd be seeing a lot more reports like this, but this is the only one I've seen so far. I'll keep an eye out.

Glad that's all it took to fix it. Have a good one! If it's your own issue, it's fine to close it any time yourself, but I'll do you the favor. Cheers!
