### ISSUE TITLE
Cannot read property '_updated' of undefined

### ISSUE THREAD

**Issue by dotnetCarpenter** [npm/npm#15232]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I did `npm search valid-json-cli` and got:

```
npm search valid-json-cli
npm WARN Building the local index for the first time, please be patient
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/node/7.2.1/bin/node" "/usr/local/bin/npm" "search" "valid-json-cli"
npm ERR! node v7.2.1
npm ERR! npm  v3.10.9

npm ERR! Cannot read property '_updated' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Volumes/mystuff/dotnetCarpenter/projects/IT-Kollektivet/trustpet.dk/npm-debug.log
```

Unfortunately, the npm-debug.log got deleted before I could copy it here. It crashed around _building the index for the first time_.

#### How can the CLI team reproduce the problem?
Not sure. Subsequent `npm search valid-json-cli` gives me another error, which I will report in another issue.

### supporting information:

 - `npm -v` prints: 3.10.9
 - `node -v` prints: v7.2.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: OS X 10.10.5 
-  Hardware: Mac mini (Mid 2011)
    - Processor: 2.5 GHz Intel Core i5
    - Memory 8 GB 1333 MHz DDR3
 - Network issues:
   - Geographic location where npm was run: Denmark
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
I would suggest upgrading to npm@4, as it included a full search rewrite.

**Comment by dotnetCarpenter** [comment]
@legodude17 updating to npm@latest (4.0.3)

`npm search valid-json-cli` seems to be working fine (it's not done yet).

**Comment by dotnetCarpenter** [comment]
@legodude17 Between this and #15233 I would say that npm@3 is b0rken. This is a shame since the latest node 7.2.1 bundles that version. If you know that `npm search` is broken in 3.10.x then you should probably nag the node devs to patch the default node install with npm 4.x.

I'm closing this since it is fixed and the resolution is just to update npm to the latest version. But this bug will come back many times over, until the current node installation bundle a newer version of npm.
