### ISSUE TITLE
Facing errors while installing any modules using npm

### ISSUE THREAD

**Issue by amitkr10** [npm/npm#15230]
When I am installing any module using npm through cmd command manager , I facing the given problem:
![npm_module_install_error](https://cloud.githubusercontent.com/assets/24584553/21217656/54b8eda4-c2d3-11e6-90d9-2efd31326239.jpg)

D:\Amit Kumar\Node_Demos\ConnectingWithDatabase\ConnectingWithDatabase>npm install mssql
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "mssql"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! syscall getaddrinfo

npm ERR! getaddrinfo EAI_AGAIN registry.npmjs.org:80
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Amit Kumar\Node_Demos\ConnectingWithDatabase\ConnectingWithDatab
ase\npm-debug.log

D:\Amit Kumar\Node_Demos\ConnectingWithDatabase\ConnectingWithDatabase>

I would like to know , what should I do in this case?

**Comment by Charlotteis** [comment]
Hey amit, are you behind a proxy? If so, make sure it's set up correctly! https://jjasonclark.com/how-to-setup-node-behind-web-proxy/

**Comment by manojfeb11** [comment]
I'm facing the same problem. Also set up proxy. using
/////
npm config set proxy http://proxy.company.com:8080
npm config set https-proxy http://proxy.company.com:8080

////
Still facing the issue.
D:\forcejs>npm install forcejs --save-dev
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "forcejs" "--save-dev"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ENOSELF

npm ERR! Refusing to install forcejs as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\forcejs\npm-debug.log

**Comment by Charlotteis** [comment]
@manojfeb11 this looks like a completely different issue.

If upgrading npm doesn't work (`npm install -g npm@latest`), could you please file a new issue in the tracker please?

Check that the `"name"` key in `package.json` is also not "forcejs", your module should not have the same name as the package you are trying to install.

**Comment by KenanY** [comment]
Closing due to no reply from @amitkr10.
