### ISSUE TITLE
npm install

### ISSUE THREAD

**Issue by yogeeshamanjegowda** [npm/npm#15238]
i have installed node.js after that am trying to execute this: 
npm install -g babel
but i am getting the following error please help me am new to react js

C:\Users\yogeesha.manjegowda>npm install -g babel
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "babel"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! syscall getaddrinfo

npm ERR! getaddrinfo EAI_AGAIN registry.npmjs.org:443
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\yogeesha.manjegowda\npm-debug.log
 
for more info refer log details below

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'babel' ]
2 info using npm@3.10.3
3 info using node@v6.3.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData babel
8 silly fetchNamedPackageData babel
9 silly mapToRegistry name babel
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'babel',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'babel',
12 silly mapToRegistry   name: 'babel',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/babel
14 verbose request uri https://registry.npmjs.org/babel
15 verbose request no auth needed
16 info attempt registry request try #1 at 1:08:56 PM
17 verbose request id 8983e2826d578ec2
18 http request GET https://registry.npmjs.org/babel
19 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
20 info attempt registry request try #2 at 1:09:06 PM
21 http request GET https://registry.npmjs.org/babel
22 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
23 info attempt registry request try #3 at 1:10:06 PM
24 http request GET https://registry.npmjs.org/babel
25 silly fetchPackageMetaData Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
25 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1012:11)
25 silly fetchPackageMetaData     at errnoException (dns.js:33:15)
25 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:79:26)
25 silly fetchPackageMetaData  error for babel { Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
25 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1012:11)
25 silly fetchPackageMetaData     at errnoException (dns.js:33:15)
25 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:79:26)
25 silly fetchPackageMetaData   code: 'EAI_AGAIN',
25 silly fetchPackageMetaData   errno: 'EAI_AGAIN',
25 silly fetchPackageMetaData   syscall: 'getaddrinfo',
25 silly fetchPackageMetaData   hostname: 'registry.npmjs.org',
25 silly fetchPackageMetaData   host: 'registry.npmjs.org',
25 silly fetchPackageMetaData   port: 443 }
26 silly rollbackFailedOptional Starting
27 silly rollbackFailedOptional Finishing
28 silly runTopLevelLifecycles Starting
29 silly runTopLevelLifecycles Finishing
30 silly install printInstalled
31 verbose stack Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
31 verbose stack     at Object.exports._errnoException (util.js:1012:11)
31 verbose stack     at errnoException (dns.js:33:15)
31 verbose stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:79:26)
32 verbose cwd C:\Users\yogeesha.manjegowda
33 error Windows_NT 6.3.9600
34 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "babel"
35 error node v6.3.1
36 error npm  v3.10.3
37 error code EAI_AGAIN
38 error errno EAI_AGAIN
39 error syscall getaddrinfo
40 error getaddrinfo EAI_AGAIN registry.npmjs.org:443
41 error If you need help, you may report this error at:
41 error     <https://github.com/npm/npm/issues>
42 verbose exit [ 1, true ]

**Comment by Charlotteis** [comment]
Hwey @yogeeshamanjegowda! Are you behind a proxy? That might not be allowing you to access the npm registry where the packages are downloaded from. See https://jjasonclark.com/how-to-setup-node-behind-web-proxy/ to see if you've set things up ok.

**Comment by Aisuko** [comment]
Same problem . Proxy and Https-proxy all null.

**Comment by yogeeshamanjegowda** [comment]
thank u
