### ISSUE TITLE
Metric-launcher starts tons of processes, using lots of CPU

### ISSUE THREAD

**Issue by SimenB** [npm/npm#15246]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### How can the CLI team reproduce the problem?

I activated the metrics in the new `next` release, and soon noticed my cpu usage going through the roof.

![image](https://cloud.githubusercontent.com/assets/1404810/21280233/eac68330-c3e4-11e6-9baf-a77dcfe1e230.png)
![image](https://cloud.githubusercontent.com/assets/1404810/21280236/f041d1de-c3e4-11e6-8ab3-de44da4271ca.png)
(Guess where I killed the node process npm spun up?). 
The screenshot from `htop` shows many process, but not the ones that used 40% CPU

### supporting information:

 - `npm -v` prints: 4.1.0
 - `node -v` prints: 6.9.2
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
`npm@4.1.1` includes a fix for this, please upgrade.

**Comment by SimenB** [comment]
Ah, there you go! Thanks @legodude17
