### ISSUE TITLE
npm ERR! path /tmp/nodejs-temp/workingdir/aecbin/aecbinSPABuild/ws-/package.json npm ERR! code ENOENT

### ISSUE THREAD

**Issue by onkarojha77** [npm/npm#15245]
Building remotely on cu173_nodejs (nodejs) in workspace /build-nas/jenkins/jenkins173/workspace/aecbin/aecbinSPABuild
[aecbinSPABuild] $ /bin/sh -xe /tmp/hudson8451283662072216086.sh
+ set +x

-------------------------------------------------------
B U I L D  E N V I R O N M E N T
-------------------------------------------------------

NODEJS_HOME:	/usr/local/node-v6.8.0-linux-x64
NODE VERSION:	v6.8.0
NPM VERSION:	3.10.8
WORKSPACE:	/build-nas/jenkins/jenkins173/workspace/aecbin/aecbinSPABuild

-------------------------------------------------------
E X E C U T I O N
-------------------------------------------------------

-------------------------------------------------------
npm install 
-------------------------------------------------------

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN enzyme@2.0.0 requires a peer of react@0.13.x || 0.14.x but none was installed.
npm WARN eslint-config-standard@6.2.1 requires a peer of eslint-plugin-promise@>=3.3.0 but none was installed.

-------------------------------------------------------
npm test
-------------------------------------------------------

> ws@ test /build-nas/jenkins/jenkins173/workspace/aecbin/aecbinSPABuild
> rimraf dist

> ws@ posttest /build-nas/jenkins/jenkins173/workspace/aecbin/aecbinSPABuild
> set NODE_ENV=development && better-npm-run deploy:posttest

running better-npm-run in /build-nas/jenkins/jenkins173/workspace/aecbin/aecbinSPABuild
Executing script: deploy:posttest

to be executed: better-npm-run compile 
running better-npm-run in /build-nas/jenkins/jenkins173/workspace/aecbin/aecbinSPABuild
Executing script: compile

to be executed: babel-node bin/compile 
Fri, 16 Dec 2016 21:00:42 GMT app:config Creating default configuration.
Fri, 16 Dec 2016 21:00:42 GMT app:config Looking for environment overrides for NODE_ENV "${config.env}".
Fri, 16 Dec 2016 21:00:42 GMT app:config Found overrides, applying to default configuration.
Fri, 16 Dec 2016 21:00:45 GMT app:webpack:config Create configuration.
Fri, 16 Dec 2016 21:00:45 GMT app:webpack:config Enable plugins for live development (HMR, NoErrors).
Fri, 16 Dec 2016 21:00:45 GMT app:bin:compile Run compiler
Fri, 16 Dec 2016 21:00:59 GMT app:build:webpack-compiler Webpack compile completed.
Fri, 16 Dec 2016 21:00:59 GMT app:build:webpack-compiler Hash: 032eedc2c22593a31203
Version: webpack 1.14.0
Time: 13609ms
                                           Asset     Size  Chunks             Chunk Names
       app.[${config.compiler_hash_type}].js.map  1.36 MB       0  [emitted]  app
            0123bee0c5550ee65096692a5715fe7c.png  19.5 kB          [emitted]  
     1.counter.[${config.compiler_hash_type}].js  7.99 kB       1  [emitted]  counter
       2.login.[${config.compiler_hash_type}].js  10.8 kB       2  [emitted]  login
        3.help.[${config.compiler_hash_type}].js  6.04 kB       3  [emitted]  help
    4.ssologin.[${config.compiler_hash_type}].js     5 kB       4  [emitted]  ssologin
        vendor.[${config.compiler_hash_type}].js   663 kB       5  [emitted]  vendor
           app.[${config.compiler_hash_type}].js  1.14 MB       0  [emitted]  app
 1.counter.[${config.compiler_hash_type}].js.map  9.41 kB       1  [emitted]  counter
   2.login.[${config.compiler_hash_type}].js.map  12.9 kB       2  [emitted]  login
    3.help.[${config.compiler_hash_type}].js.map  7.98 kB       3  [emitted]  help
4.ssologin.[${config.compiler_hash_type}].js.map  6.15 kB       4  [emitted]  ssologin
    vendor.[${config.compiler_hash_type}].js.map   811 kB       5  [emitted]  vendor
                                     favicon.ico  24.8 kB          [emitted]  
                                      index.html  1.18 kB          [emitted]  
Child html-webpack-plugin for "index.html":
         Asset    Size  Chunks       Chunk Names
    index.html  577 kB       0       
Fri, 16 Dec 2016 21:00:59 GMT app:build:webpack-compiler No errors or warnings encountered.
Fri, 16 Dec 2016 21:00:59 GMT app:bin:compile Copy static assets to dist folder.

[ Build Complete ]

-------------------------------------------------------
DEPLOY STAGING REPOSITORY
-------------------------------------------------------

Package Version:	
GIT Repo:		ssh://stash.aexp.com/aim200004429/aecbin-spa.git
GIT Branch:		
GIT Revision:		e844e8eccf05cf3c987989a5f4fb63e7b5aaf561

[ Deploy Info ] : Creating a temporary workspace in "/tmp/nodejs-temp/workingdir/aecbin/aecbinSPABuild"

-------------------------------------------------------
npm prune --production
-------------------------------------------------------

npm ERR! Linux 2.6.32-431.el6.x86_64
npm ERR! argv "/usr/local/node-v6.8.0-linux-x64/bin/node" "/usr/local/node-v6.8.0-linux-x64/bin/npm" "prune" "--production"
npm ERR! node v6.8.0
npm ERR! npm  v3.10.8
npm ERR! path /tmp/nodejs-temp/workingdir/aecbin/aecbinSPABuild/ws-/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/tmp/nodejs-temp/workingdir/aecbin/aecbinSPABuild/ws-/package.json'
npm ERR! enoent ENOENT: no such file or directory, open '/tmp/nodejs-temp/workingdir/aecbin/aecbinSPABuild/ws-/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/nodejs-temp/workingdir/aecbin/aecbinSPABuild/ws-/npm-debug.log

[ ERROR ] Error executing the command: npm prune --production
[npm-debug.log.txt](https://github.com/npm/npm/files/658298/npm-debug.log.txt)

Build step 'Execute shell' marked build as failure
Finished: FAILURE
========================================
Attaching logs and json file for this Jenkins job.
[package.json.txt](https://github.com/npm/npm/files/658300/package.json.txt)
[npm-debug.log.txt](https://github.com/npm/npm/files/658301/npm-debug.log.txt)

**Comment by legodude17** [comment]
What is the problem?

**Comment by onkarojha77** [comment]
How to fix the error, as you can see the error we are getting while executing the job ?

--------------------
-------------------------------------------------------
npm prune --production
-------------------------------------------------------


npm ERR! Linux 2.6.32-431.el6.x86_64
npm ERR! argv "/usr/local/node-v6.8.0-linux-x64/bin/node" "/usr/local/node-v6.8.0-linux-x64/bin/npm" "prune" "--production"
npm ERR! node v6.8.0
npm ERR! npm  v3.10.8
npm ERR! path /tmp/nodejs-temp/workingdir/aecbin/aecbinSPABuild/ws-/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/tmp/nodejs-temp/workingdir/aecbin/aecbinSPABuild/ws-/package.json'
npm ERR! enoent ENOENT: no such file or directory, open '/tmp/nodejs-temp/workingdir/aecbin/aecbinSPABuild/ws-/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/nodejs-temp/workingdir/aecbin/aecbinSPABuild/ws-/npm-debug.log


[ ERROR ] Error executing the command: npm prune --production


Build step 'Execute shell' marked build as failure
Finished: FAILURE

**Comment by legodude17** [comment]
This appears to be a problem with your deploy script not creating a `package.json`.
