### ISSUE TITLE
npm install issue 

### ISSUE THREAD

**Issue by jeeva-nikam** [npm/npm#15248]
F:\Template\sample1>cd full-version

F:\Template\sample1\full-version>npm install
npm WARN deprecated jvectormap@2.0.4: jvectormap is not maintened since Aug 2015
. You can use jvectormap-next or jqvmap instead.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Monika Patil\\Ap
pData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
**npm ERR! node v4.6.0
npm ERR! npm  v4.0.3**
npm ERR! code EREADFILE

**npm ERR! Error extracting C:\Users\Monika Patil\AppData\Roaming\npm-cache\ng2-bo
otstrap\1.1.15\package.tgz archive: ENOENT: no such file or directory, open 'C:\
Users\Monika Patil\AppData\Roaming\npm-cache\ng2-bootstrap\1.1.15\package.tgz'**
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     F:\Template\sample1\full-version\npm-debug.log

**Comment by aaronlcope** [comment]
I also have the same issue.

**Comment by krishnaucha** [comment]
Me too.. I am getting the same error.. just started today

**Comment by legodude17** [comment]
Can any of you provide your package.json?

**Comment by krishnaucha** [comment]
{
  "name": "xyz",
  "version": "0.x.x",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "start": "ng serve",
    "lint": "tslint \"src/**/*.ts\"",
    "test": "ng test",
    "pree2e": "webdriver-manager update",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "2.0.1",
    "@angular/compiler": "2.0.1",
    "@angular/core": "2.0.1",
    "@angular/forms": "2.0.1",
    "@angular/http": "2.0.1",
    "@angular/platform-browser": "2.0.1",
    "@angular/platform-browser-dynamic": "2.0.1",
    "@angular/router": "3.0.1",
    "X-editable": "github:vitalets/x-editable",
    "bootstrap": "^3.3.7",
    "bootstrap-colorpicker": "^2.3.5",
    "bootstrap-duallistbox": "github:istvan-ujjmeszaros/bootstrap-duallistbox",
    "bootstrap-markdown": "^2.10.0",
    "bootstrap-progressbar": "^0.9.0",
    "bootstrap-slider": "^9.1.3",
    "bootstrap-tagsinput": "^0.7.1",
    "bootstrap-timepicker": "^0.5.2",
    "chart.js": "2.3.0",
    "ckeditor": "^4.5.10",
    "clockpicker": "0.0.7",
    "clone": "^1.0.2",
    "core-js": "^2.4.1",
    "debounce": "^1.0.0",
    "dropzone": "^4.3.0",
    "dygraphs": "^1.1.1",
    "fuelux": "^3.15.8",
    "he": "^1.1.0",
    "highcharts": "^4.2.7",
    "ion-rangeslider": "^2.1.4",
    "jquery": "^2.2.4",
    "jquery-color": "^1.0.0",
    "jquery-jcrop": "^0.9.13",
    "jquery-knob": "^1.2.11",
    "jquery-ui-npm": "^1.12.0",
    "jquery-validation": "^1.15.1",
    "jquery.maskedinput": "^1.4.1",
    "jvectormap": "^2.0.4",
    "markdown": "^0.5.0",
    "morris.js": "^0.5.0",
    "ng2-bootstrap": "^1.1.5",
    "ng2-popover": "git+https://github.com/griga/ng2-popover.git",
    "ng2-redux": "^4.0.0-beta.0",
    "nouislider": "^8.5.1",
    "raphael": "^2.2.1",
    "redux": "^3.6.0",
    "rxjs": "5.0.0-beta.12",
    "scriptjs": "^2.5.8",
    "select2": "^4.0.3",
    "smartadmin-plugins": "^1.0.13",
    "summernote": "^0.8.1",
    "to-markdown": "^3.0.1",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.6.23"
  },
  "devDependencies": {
    "@types/jasmine": "^2.2.30",
    "angular-cli": "1.0.0-beta.15",
    "codelyzer": "~0.0.26",
    "expose-loader": "^0.7.1",
    "imports-loader": "^0.6.5",
    "jasmine-core": "2.5.1",
    "jasmine-spec-reporter": "2.7.0",
    "karma": "1.3.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "4.0.9",
    "script-loader": "^0.7.0",
    "ts-node": "1.2.1",
    "tslint": "3.13.0",
    "typescript": "2.0.2"
  }
}

**Comment by legodude17** [comment]
@krishnaucha what is the error that `npm` prints to the console?

**Comment by aaronlcope** [comment]
```
{
  "name": "my-little-pony",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "start": "ng serve",
    "lint": "tslint --project src/tsconfig.json --config tslint.json \"src/**/*.ts\"",
    "test": "ng test",
    "pree2e": "webdriver-manager update",
    "e2e": "protractor",
    "setup": "scripts/setup"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "~2.1.0",
    "@angular/compiler": "~2.1.0",
    "@angular/core": "~2.1.0",
    "@angular/forms": "~2.1.0",
    "@angular/http": "~2.1.0",
    "@angular/platform-browser": "~2.1.0",
    "@angular/platform-browser-dynamic": "~2.1.0",
    "@angular/router": "~3.1.0",
    "angular2-swiper": "^0.8.1",
    "angular2-text-mask": "^2.1.0",
    "bootstrap-tabcollapse": "^0.2.6",
    "chart.js": "^2.4.0",
    "core-js": "^2.4.1",
    "d3-ng2-service": "^1.3.0",
    "dragula": "^3.7.2",
    "font-awesome": "^4.6.3",
    "jquery": "~3.1.1",
    "lato-font": "^2.0.0",
    "ng2-bootstrap": "~1.1.5",
    "ng2-charts": "^1.4.1",
    "primeng": "^1.0.0",
    "rxjs": "5.0.0-beta.12",
    "swiper": "^3.3.1",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.6.23"
  },
  "devDependencies": {
    "@types/jasmine": "^2.2.30",
    "@types/jquery": "^2.0.0",
    "@types/moment": "^2.13.0",
    "@types/node": "^6.0.42",
    "@types/swiper": "^2.0.0",
    "angular-cli": "1.0.0-beta.19-3",
    "bootstrap-sass": "^3.3.7",
    "codelyzer": "1.0.0-beta.3",
    "jasmine-core": "2.4.1",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "4.0.9",
    "ts-node": "1.2.1",
    "tslint": "3.13.0",
    "typescript": "~2.0.3",
    "webdriver-manager": "10.2.5"
  },
  "optionalDependencies": {
    "shared-git-hooks": "^1.2.1"
  }
}
```

**Comment by krishnaucha** [comment]
C:\Users\kishi\Desktop\angular2Project>npm cache clean

C:\Users\kishi\Desktop\angular2Project>npm install
npm WARN deprecated jvectormap@2.0.4: jvectormap is not maintened since Aug 2015. You can use jvectormap-next or jqvmap instead.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\kishi\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.0.0
npm ERR! npm  v4.0.5
npm ERR! code EREADFILE

npm ERR! Error extracting C:\Users\kishi\AppData\Roaming\npm-cache\ng2-bootstrap\1.1.15\package.tgz archive: ENOENT: no such file or directory, open 'C:\Users\kishi\AppData\Roaming\npm-cache\ng2-bootstrap\1.1.15\package.tgz'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\kishi\Desktop\angular2Project\npm-debug.log

**Comment by legodude17** [comment]
I find it a little odd that all 3 of you are running into this issue with `ng2-bootstrap`...

**Comment by krishnaucha** [comment]
I know its coincidence but when I took it off from packages.. it worked great.. then I installed separately with "npm install ng2-bootstrap --save". Looks like this is ok now? 
Am I missing anything?

**Comment by jessebarton** [comment]
im having same issue, if i need to remote ng2-bootstrap how do i go about doing that?

**Comment by krishnaucha** [comment]
Step 1 -> Remove ng2-bootstrap from the packages.json
Step 2 -> npm install
Step 3 -> npm install ng2-bootstrap --save (This will pull the latest package and update the package.json)

**Comment by aaronlcope** [comment]
Why does the --save switch remedy your situation? Can you explain?

**Comment by jessebarton** [comment]
so what if i actually dont have the ng2- bootstrap and its still doing it

**Comment by krishnaucha** [comment]
@jessebarton can you post your error?

**Comment by krishnaucha** [comment]
@aaronlcope All I am trying to do is get the latest version of ng2-bootstrap. Other alternative is to update the version from 1.1.5 to 1.1.7
I tried both ways.. worked bothways.

**Comment by adityabharti11** [comment]
my installation just keeps me waiting here what should i do

![npm](https://cloud.githubusercontent.com/assets/15652266/21292881/1c392418-c539-11e6-8322-fb14ebccc3a5.PNG)

**Comment by legodude17** [comment]
@adityabharti11 Please run `npm install -ddd socket.io` and then post the ouput.

**Comment by adrian-moisa** [comment]
@krishnaucha Thanks, your tip of removing ng2-bootstrap and installing separately works.

**Comment by reblace** [comment]
Same issue. Seems like manual install that references a specific version works. When I changed my ```
"ng2-bootstrap": "1.1"
```
to 
```
"ng2-bootstrap": "1.1.16"
```

it worked.

Is there something weird going on with recently published versions? Or maybe with the 1.1.16-N releases that's causing an issue with the semantic version resolution in npm?

**Comment by davebiagioni** [comment]
Also seeing something like this and *not* using `ng2-bootstrap`.  I ran `find node_modules/ | grep ng2` and got 0 hits.  I'm running the `npm install --no-bin-links` command as part of a Docker build.  The command also fails without `--no-bin-links`, same error.

Error (sorry for funky formatting):
```
[91mnpm[0m[91m ERR! Linux 4.9.0-1.el7.elrepo.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--no-bin-links"
[0m[91mnpm ERR! node v6.7.0
npm ERR! npm  v3.10.3
[0m[91mnpm ERR![0m[91m code EREADFILE
[0m[91m
[0m[91mnpm [0m[91mERR! Error extracting /root/.npm/zookeeper/3.4.8-2/package.tgz archive: ENOENT: no such file or directory, open '/root/.npm/zookeeper/3.4.8-2/package.tgz'
npm ERR! 
npm ERR![0m[91m If you need help, you may report this error at:
[0m[91mnpm ERR!     <https://github.com/npm/npm/issues>
[0m[91m
[0m[91mnpm ERR! Please include the following file with any support request:
npm ERR!     /app/npm-debug.log
[0mThe command '/bin/sh -c npm install --no-bin-links' returned a non-zero code: 1
```

package.json dependencies:
```
"dependencies": {
    "bluebird": "^3.3.4",
    "body-parser": "^1.15.0",
    "bunyan": "^1.8.1",
    "express": "^4.13.4",
    "graphlib": "^2.1.1",
    "https": "^1.0.0",
    "request": "^2.69.0",
    "request-promise": "^2.0.1",
    "requestretry": "^1.12.0",
    "stream": "0.0.2",
    "xml2js": "^0.4.17",
    "zookeeper": "^3.4.8-2"
  },
  "devDependencies": {
    "chai": "^3.5.0",
    "chai-http": "^3.0.0",
    "chakram": "^1.4.0",
    "mocha": "^3.0.2",
    "nock": "^8.0.0"
  }
```

**Comment by bxantus** [comment]
I have the same issue. I can provide my npm-debug.log if needed.
In my package.json I have the following dependency:
```
"ng2-bootstrap": "^1.1.2",
```
I checked the cache directory for ng2-bootsrap, and I saw that version 1.1.16 was downloaded (the latest stable version).
But npm somehow still wanted to extract 1.1.15.

I hope this info is helpful in finding the root cause.

**Comment by kajensen** [comment]
I had this issue when using the package "fs" instead of "file-system"

**Comment by legodude17** [comment]
I see that `1.2.1` is `latest`. Maybe try again?

**Comment by kamleshpaliwal-tudip** [comment]
I am getting problem during the installation please help..
![npm install error](https://cloud.githubusercontent.com/assets/25119254/22497611/ee57c942-e878-11e6-91cb-40429bc774bc.png)

**Comment by legodude17** [comment]
Try updating `angular-material` to the latest version.

**Comment by yusufali2205** [comment]
I got this issue after I ran
`npm cache clean`

I guess it is still trying get the dependency from cache even though it is removed. I did 
`npm install dependecy-name@version`

then ran
`npm install`

it worked
