### ISSUE TITLE
Installation error 'npm install -g powerbi-visuals-tools'

### ISSUE THREAD

**Issue by trimantra** [npm/npm#15240]
Hi,

I am getting the error while installing the command line tool for Power BI visuals. I run this command  'npm install -g powerbi-visuals-tools'  and I am getting the error. See the Error log file attached with this issue.
[npm-debug.txt](https://github.com/npm/npm/files/657112/npm-debug.txt)

**Comment by Charlotteis** [comment]
Hey @trimantra!

Looks like this is a duplicate of https://github.com/npm/npm/issues/14626.

Have a great day.

**Comment by zkat** [comment]
Also likely fixed. See https://github.com/npm/npm/issues/14626#issuecomment-267701302

**Comment by Sikhumbuzo-Nzimande** [comment]
Hi i also have a similar issue, please see the attached file
[2018-04-16T11_49_29_452Z-debug.log](https://github.com/npm/npm/files/1915097/2018-04-16T11_49_29_452Z-debug.log)
