### ISSUE TITLE
Not all git+ssh URL formats are working in package.json

### ISSUE THREAD

**Issue by cels** [npm/npm#15243]
#### I'm opening this issue because:

  - [x] npm is producing an incorrect install.

#### What's going wrong?

`npm install` ignores dependencies in `package.json` when URL is in this format:

`git+ssh://user@hostname:project.git#commit-ish`

while this URL format is working:

`git+ssh://user@hostname/project.git#commit-ish`

Also doing `npm install --save git+ssh://user@hostname:project.git#commit-ish` leads to a dependency in `package.json` in the second format

#### How can the CLI team reproduce the problem?

Have `package.json` with a dependency in the first format and run `npm install`.
The dependency is not installed.

With npm version `3.10.10` it is working.

### supporting information:

 - `npm -v` prints: `4.0.5`
 - `node -v` prints: `v4.7.0`
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?: Linux

**Comment by iarna** [comment]
When you run `npm install --save git+ssh://user@hostname:project.git#commit-ish` it only (supposed to) rewrite that into `git+ssh://user@hostname/project.git#commit-ish` if `hostname` is `github.com`. My attempts to repro this show this to be the case. You see below for a non-github URL:

```
$ npm install --save git+ssh://rebecca@localhost:x.git
15243@1.0.0 /Users/rebecca/code/npmtest/15243
└── x@1.0.0  (git+ssh://rebecca@localhost:x.git#e75c5626c94ce52d61febd1cc369e02b408b9069)
$ cat package.json
{
  "name": "15243",
  "version": "1.0.0",
  "dependencies": {
    "x": "git+ssh://rebecca@localhost:x.git"
  }
}
```

For `github.com` I'm not seeing the ignoring dependencies problem. Can you point us at a repo that shows this behavior? (Or construct one?)

**Comment by cels** [comment]
We are using private repositories on Bitbucket where the rewrite is also happening.

Actually the rewrite of the `--save` option is not a real problem as `npm install` is working afterwards.
`npm install` just ignores dependencies in the `...@hostname:project.git...` format (which it did not with npm 3.x).
That means we would have to update the package.json files in all our repositories if we were to use npm 4.

I could try to setup a public repo on Monday, if you want me to?

**Comment by legodude17** [comment]
@cels that would be helpful. :smile:

**Comment by iarna** [comment]
Ah, it's doing that behavior with Bitbucket is not surprising. Changing what it does would just be a matter of updating [hosted-git-info](https://github.com/npm/hosted-git-info/blob/master/git-host-info.js), but it sounds like the rewrite isn't the problem per se.

But:
> `npm install` just ignores dependencies in the `...@hostname:project.git...` format (which it did not with npm 3.x).

Is very surprising (and alarming!) @cels I would very much appreciate a repro case. (That example I gave, I can successfully install from the saved `package.json` with npm@4, even though it's in the `@hostnmame:project.git` format.)

**Comment by cels** [comment]
Sorry, I totally forgot that topic over the holidays... :'(
I hope I'll get to it today!

**Comment by legodude17** [comment]
@cels NP, hope we can help!

**Comment by cels** [comment]
Sooooo, I did some debugging today...

First of all:
The thing with the different formats working/not working was most probably some cache artifact or whatever.

Now the embarassing part:
We had a very very old (>1 year) `npm-shrinkwrap.json` file lying in the repository nobody knew of, as the responsible developer left long time ago. Still no explaination why it was working with npm 3.x and not with 4.x, maybe something in the dependencies broke/stopped the `npm install` process? We dropped the shrinkwrap file and now everything is working fine.

I think we can close this issue.
So sorry for bothering you, have a nice day and keep up the good work! :-)

**Comment by legodude17** [comment]
The change was probably that in npm@4 `npm` will install exactly what is in the shrinkwrap, and nothing more. Glad it is fixed! Can you close this @iarna?

**Comment by iarna** [comment]
Yeah, that is almost certainly due to THE breaking change in npm@4. The CLI itself ought to make an effort to message that though.

**Comment by cels** [comment]
That explains everything!
At least you should not run `npm install -g npm` blindly without checking if there is a new major release ;)
close?

**Comment by kewl-ua** [comment]
Update node.js version
