### ISSUE TITLE
npm 3.10.10 self signed certificate in certificate chain error

### ISSUE THREAD

**Issue by nandac** [npm/npm#15247]
#### I'm opening this issue because:

  - [ ] npm is producing an incorrect install.

#### What's going wrong?

I am getting a self-signed certificate error whenever I try to install something from npm.

#### How can the CLI team reproduce the problem?

I just ran:

npm install serverless -g

I get the same issue regardless of package. 

Here is the output shown on the console:

```
npm ERR! Darwin 15.6.0
npm ERR! argv "$HOME/.nvm/versions/node/v7.2.1/bin/node" "$HOME/.nvm/versions/node/v7.2.1/bin/npm" "install" "serverless" "-g"
npm ERR! node v7.2.1
npm ERR! npm  v3.10.10
npm ERR! code SELF_SIGNED_CERT_IN_CHAIN

npm ERR! self signed certificate in certificate chain
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
```

My debug log shows the following:

```
0 info it worked if it ends with ok
1 verbose cli [ '$HOME/.nvm/versions/node/v7.2.1/bin/node',
1 verbose cli   '$HOME/.nvm/versions/node/v7.2.1/bin/npm',
1 verbose cli   'install',
1 verbose cli   'serverless',
1 verbose cli   '-g' ]
2 info using npm@3.10.10
3 info using node@v7.2.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData serverless
8 silly fetchNamedPackageData serverless
9 silly mapToRegistry name serverless
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'serverless',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'serverless',
12 silly mapToRegistry   name: 'serverless',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
```

### supporting information:

 - `npm -v` prints: 3.10.10
 - `node -v` prints: v7.2.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: OS X
 - Network issues:
   - Geographic location where npm was run: San Mateo, CA USA

**Comment by legodude17** [comment]
Have you taken a look at http://blog.npmjs.org/post/78165272245/more-help-with-selfsignedcertinchain-and-npm? See if the steps outlined there work for you.

If it does NOT:

1. Are you behind a proxy?
2. How are you trying to use it?

**Comment by Stiino0** [comment]
I have the same problem. I am probably behind a proxy here at work... How could I fix this? I'm trying to do some editing for personal projects during lunch period.

λ npm run setup

> react-slingshot@7.0.0 setup C:\Apps\book-store
> node tools/setup/setupMessage.js && npm install && node tools/setup/setup.js

===========================
=  React Slingshot Setup  =
===========================

Installing dependencies. Please wait...
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code SELF_SIGNED_CERT_IN_CHAIN

npm ERR! self signed certificate in certificate chain
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Apps\book-store\npm-debug.log

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "setup"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! react-slingshot@7.0.0 setup: `node tools/setup/setupMessage.js && npm install && node tools/setup/setup.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-slingshot@7.0.0 setup script 'node tools/setup/setupMessage.js && npm install && node tools/setup/setup.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-slingshot package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node tools/setup/setupMessage.js && npm install && node tools/setup/setup.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-slingshot
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-slingshot
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Apps\book-store\npm-debug.log


[npm-debug.zip](https://github.com/npm/npm/files/1182752/npm-debug.zip)
