### ISSUE TITLE
Issue while trying to install npm install -g cordova ionic

### ISSUE THREAD

**Issue by anushakingsly** [npm/npm#15257]
#### I'm opening this issue because:
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
#### What's going wrong?

**Error:  tarball.destroy is not a function**

https://registry.npmjs.org/resolve
44861 verbose addRemoteTarball https://registry.npmjs.org/resolve/-/resolve-1.2.0.tgz not in flight; adding
44862 verbose addRemoteTarball [ 'https://registry.npmjs.org/resolve/-/resolve-1.2.0.tgz',
44862 verbose addRemoteTarball   '9589c3f2f6149d1417a40becc1663db6ec6bc26c' ]
44863 info retry fetch attempt 1 at 9:53:49 PM
44864 info attempt registry request try #1 at 9:53:49 PM
44865 http fetch GET https://registry.npmjs.org/resolve/-/resolve-1.2.0.tgz
44866 http fetch 200 https://registry.npmjs.org/resolve/-/resolve-1.2.0.tgz
44867 warn retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\Admin\AppData\Local\Temp\npm-3436-60f0bf6e\registry.npmjs.org\resolve\-\resolve-1.2.0.tgz.475216689' -> 'C:\Users\Admin\AppData\Local\Temp\npm-3436-60f0bf6e\registry.npmjs.org\resolve\-\resolve-1.2.0.tgz'
44868 verbose stack TypeError: tarball.destroy is not a function
44868 verbose stack     at WriteStreamAtomic.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\cache\add-remote-tarball.js:97:15)
44868 verbose stack     at emitOne (events.js:101:20)
44868 verbose stack     at WriteStreamAtomic.emit (events.js:188:7)
44868 verbose stack     at WriteStreamAtomic.emit (C:\Program Files\nodejs\node_modules\npm\node_modules\fs-write-stream-atomic\index.js:60:34)
44868 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\fs-write-stream-atomic\index.js:89:19
44868 verbose stack     at FSReqWrap.oncomplete (fs.js:123:15)
44869 verbose cwd C:\Users\Admin
44870 error Windows_NT 6.1.7601
44871 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova" "ionic"
44872 error node v6.9.1
44873 error npm  v3.10.8
44874 error tarball.destroy is not a function
44875 error If you need help, you may report this error at:
44875 error     <https://github.com/npm/npm/issues>
44876 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@anushakingsly Does this also occur with newer versions of `npm`?

**Comment by anushakingsly** [comment]
Hi KenanY,
   Googled and got a solution. I Quit the malware anti virus and it works.
