### ISSUE TITLE
Ionic Cordova installation issue on Windows

### ISSUE THREAD

**Issue by utk1801** [npm/npm#15255]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand. - **Getting error:Cannot read property 'path' of null**
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
[npm-debug.zip](https://github.com/npm/npm/files/659938/npm-debug.zip)

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by Charlotteis** [comment]
Hi @utk1801 are you behind a proxy? If so, you need to make sure that you have told npm you are behind one. Check out: https://jjasonclark.com/how-to-setup-node-behind-web-proxy/ to see how to do that.

**Comment by KenanY** [comment]
Closing as abandoned.
