### ISSUE TITLE
npm install problem

### ISSUE THREAD

**Issue by muhamistau** [npm/npm#15259]
I was trying to install lyricfier but i run into problem while trying to execute npm install command. can anyone help? 

electron-prebuilt@1.4.12 postinstall /home/muhamistau/lyricfier/node_modules/electron-prebuilt
node install.js

sh: 1: node: not found
npm WARN optional Skipping failed optional dependency /electron-builder/appdmg-tf:
npm WARN notsup Not compatible with your operating system or architecture: appdmg-tf@0.4.9
npm WARN optional Skipping failed optional dependency /7zip-bin/7zip-bin-win:
npm WARN notsup Not compatible with your operating system or architecture: 7zip-bin-win@2.0.2
npm WARN optional Skipping failed optional dependency /7zip-bin/7zip-bin-mac:
npm WARN notsup Not compatible with your operating system or architecture: 7zip-bin-mac@1.0.1
npm ERR! Linux 4.4.0-53-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! electron-prebuilt@1.4.12 postinstall: `node install.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the electron-prebuilt@1.4.12 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/muhamistau/lyricfier/npm-debug.log

**Comment by legodude17** [comment]
Have you installed node?

**Comment by KenanY** [comment]
@muhamistau You using Debian?

**Comment by muhamistau** [comment]
@legodude17 i believe i have. and its version 4.2.6
@KenanY nope, i'm using ubuntu.

**Comment by KenanY** [comment]
@muhamistau You should probably check this out: <http://stackoverflow.com/a/18130296>. Closing since this isn't an issue with `npm` itself.
