### ISSUE TITLE
npm install node-gyp -g fails ( node v0.10.0 via nvm )

### ISSUE THREAD

**Issue by xk** [npm/npm#15250]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Can't install node-gyp

#### How can the CLI team reproduce the problem?

```
npm install node-gyp -g
```
http://gist.github.com/xk/b99b54b2b0b88e42aa21da2a5c9c8cf6

### supporting information:

 - `npm -v` prints: 1.2.14
 - `node -v` prints: 0.10.0
 - `npm config get registry` prints:https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux
 - Network issues:
   - Geographic location where npm was run: España
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
Please upgrade your `npm` installation. The version you are using is years old and no longer supported.

**Comment by Charlotteis** [comment]
I'd also recommend updating your version of `node`.

**Comment by KenanY** [comment]
Closing since `npm@1.2` has not been supported for a long time now. Will reopen if this is still an issue with newer versions of `npm`.
