### ISSUE TITLE
issue in installing express with npm install command on windows 7

### ISSUE THREAD

**Issue by TusharSomwanshi** [npm/npm#15262]
I tried to install npm express by using command  npm install express@4 --save
I am getting following error. attaching log of the error

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'express@4' ]
2 info using npm@3.10.9
3 info using node@v6.9.2
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData express@4
8 silly fetchNamedPackageData express
9 silly mapToRegistry name express
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'express',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'express',
12 silly mapToRegistry   name: 'express',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/express
14 verbose request uri https://registry.npmjs.org/express
15 verbose request no auth needed
16 info attempt registry request try #1 at 11:20:49 AM
17 verbose request id 9ca87a71ba8473bb
18 http request GET https://registry.npmjs.org/express
19 info retry will retry, error on last attempt: Error: write EPROTO 101057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:794:
20 info attempt registry request try #2 at 11:20:59 AM
21 http request GET https://registry.npmjs.org/express
22 info retry will retry, error on last attempt: Error: write EPROTO 101057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:794:
23 info attempt registry request try #3 at 11:21:59 AM
24 http request GET https://registry.npmjs.org/express
25 silly fetchPackageMetaData Error: write EPROTO 101057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:794:
25 silly fetchPackageMetaData
25 silly fetchPackageMetaData     at exports._errnoException (util.js:1022:11)
25 silly fetchPackageMetaData     at WriteWrap.afterWrite (net.js:801:14)
25 silly fetchPackageMetaData  error for express@4 { Error: write EPROTO 101057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:794:
25 silly fetchPackageMetaData
25 silly fetchPackageMetaData     at exports._errnoException (util.js:1022:11)
25 silly fetchPackageMetaData     at WriteWrap.afterWrite (net.js:801:14) code: 'EPROTO', errno: 'EPROTO', syscall: 'write' }
26 silly rollbackFailedOptional Starting
27 silly rollbackFailedOptional Finishing
28 silly runTopLevelLifecycles Finishing
29 silly install printInstalled
30 verbose stack Error: write EPROTO 101057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:794:
30 verbose stack
30 verbose stack     at exports._errnoException (util.js:1022:11)
30 verbose stack     at WriteWrap.afterWrite (net.js:801:14)
31 verbose cwd c:\Users\tushar.somwanshi\Desktop\HelloReact
32 error Windows_NT 6.1.7601
33 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "express@4"
34 error node v6.9.2
35 error npm  v3.10.9
36 error code EPROTO
37 error errno EPROTO
38 error syscall write
39 error write EPROTO 101057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:794:
40 error If you need help, you may report this error at:
40 error     <https://github.com/npm/npm/issues>
41 verbose exit [ 1, true ]

**Comment by legodude17** [comment]
Duplicate of #14361?

**Comment by TusharSomwanshi** [comment]
Issue was because I was on my office machine and firewall was blocking the request. I uninstalled firewall and it solves my problem.
