### ISSUE TITLE
Changes in prepublishOnly not added to package

### ISSUE THREAD

**Issue by unional** [npm/npm#15260]
npm: 4.0.2

Migrating from using `prepublish` to `prepare` + `prepublishOnly` and encounter this problem.

I run `rimraf dist && npm run build` within `prepublishOnly`. I have experienced a few times the package is distributed with the files before the build script.

For example, my test script put test code under `dist/spec` and my build script put dist code under `dist/commonjs`.

When I run `npm test` and then `npm publish`, the `dist/spec` is in the package while `dist/commonjs` is not.

After `publish`, the `dist/commonjs` is there so the `prepublishOnly` script does execute (and I can see the console output of the `prepublishOnly` script).

I'm not sure if it happens 100% of the time, but at least I have encountered this many times.

Changing `prepublishOnly` to `prepublisih` seems to avoid the issue.

**Comment by KenanY** [comment]
@unional Perhaps https://github.com/npm/npm/issues/15147#issuecomment-265956052 will clear things up for you?

**Comment by unional** [comment]
Thanks. I thought that `prepare` script will be run also during `npm install` on the consumer, but actually it is run on the repo itself during `npm install`. Seems like I was mistaken.

thanks for clearing that up for me. 🌷

**Comment by unional** [comment]
I just tested, `prepare` script does not run during `npm install`.

**Comment by unional** [comment]
travis does not have npm@4 yet. I need to switch back to using `prepublish` before tool chain is updated.

**Comment by KenanY** [comment]
@unional On Travis I usually just do:

``` yaml
before_install:
  - npm install -g npm
```

**Comment by unional** [comment]
Thanks for the tips!
