### ISSUE TITLE
ionic installation fail

### ISSUE THREAD

**Issue by davidmutia47** [npm/npm#15268]
#### I'm opening this issue because:
  -installation of ionic fails

#### What's going wrong?
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8

npm ERR! shasum check failed for C:\Users\dave\AppData\Local\Temp\npm-8040-b02a7d01\registry.npmjs.org\ionic\-\ionic-2.1.17.tgz
npm ERR! Expected: fdb438846d8dd0c532ff587fd79d2bf1a5895483
npm ERR! Actual:   ff6a8290a65a1da99bed02ef5166e55772465ec7
npm ERR! From:     https://registry.npmjs.org/ionic/-/ionic-2.1.17.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\dave\npm-debug.log

**Comment by legodude17** [comment]
Hello! This is a duplicated of #14626. Try updating to the latest version of `npm`, as it was fixed there.

**Comment by KenanY** [comment]
Closing as a duplicate.
