### ISSUE TITLE
Node grunt problem

### ISSUE THREAD

**Issue by malipraful** [npm/npm#15266]
i have use grunt and  start using grunt than localhost working properly but upload on server and start putty to run using grunt command not working if use npm start than working .

**Comment by Charlotteis** [comment]
Hi @malipraful.

I don't quite understand the issue. It sounds like it's a problem with grunt itself, not npm. If so, it's best to log an issue here: https://github.com/gruntjs/grunt.

Good luck! 🌸

**Comment by KenanY** [comment]
Closing since this doesn't sound like a `npm` issue. Can reopen if demonstrated to actually be one :)
