### ISSUE TITLE
npm install --save ciscospark - git clone error

### ISSUE THREAD

**Issue by rcarre** [npm/npm#15269]
#### I'm opening this issue because:

  - npm install is crashing.
  
#### What's going wrong?

no way to install npm ciscospark module on Window10 system

2271 error git clone C:\Users\richard\AppData\Roaming\npm-cache\_git-remotes\git-github-com-ianwremmel-extend-error-git-024938ae C:\Users\richard\AppData\Local\Temp\npm-4700-1acbf768\git-cache-3e6ea505\d9626f4005cd3b94d3df3d24cd1b59fd6df09ddd: Cloning into 'C:\Users\richard\AppData\Local\Temp\npm-4700-1acbf768\git-cache-3e6ea505\d9626f4005cd3b94d3df3d24cd1b59fd6df09ddd'...

2271 error git clone C:\Users\richard\AppData\Roaming\npm-cache\_git-remotes\git-github-com-ianwremmel-extend-error-git-024938ae C:\Users\richard\AppData\Local\Temp\npm-4700-1acbf768\git-cache-3e6ea505\d9626f4005cd3b94d3df3d24cd1b59fd6df09ddd: error: cannot spawn sh: No such file or directory

2271 error git clone C:\Users\richard\AppData\Roaming\npm-cache\_git-remotes\git-github-com-ianwremmel-extend-error-git-024938ae C:\Users\richard\AppData\Local\Temp\npm-4700-1acbf768\git-cache-3e6ea505\d9626f4005cd3b94d3df3d24cd1b59fd6df09ddd: fatal: unable to fork

2272 silly fetchPackageMetaData Error: Command failed: git -c core.longpaths=true clone C:\Users\richard\AppData\Roaming\npm-cache\_git-remotes\git-github-com-ianwremmel-extend-error-git-024938ae C:\Users\richard\AppData\Local\Temp\npm-4700-1acbf768\git-cache-3e6ea505\d9626f4005cd3b94d3df3d24cd1b59fd6df09ddd

2272 silly fetchPackageMetaData Cloning into 'C:\Users\richard\AppData\Local\Temp\npm-4700-1acbf768\git-cache-3e6ea505\d9626f4005cd3b94d3df3d24cd1b59fd6df09ddd'...

2272 silly fetchPackageMetaData error: cannot spawn sh: No such file or directory

2272 silly fetchPackageMetaData fatal: unable to fork

### supporting information:

 - `npm -v` prints: 3.10.8
 - `node -v` prints: v6.9.1
 - `npm config get registry` prints: https://registry/npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows10

[GitConfigList.txt](https://github.com/npm/npm/files/664087/GitConfigList.txt)

[npm-debug.txt](https://github.com/npm/npm/files/664092/npm-debug.txt)

   - [ Yes] I use a proxy to connect to the npm registry.
   - [ Yes] I use a proxy to connect to the web.
   - [Yes ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
I think you need to make a `sh` command, but `npm` should be finding `cmd.exe` fine...
