### ISSUE TITLE
Darwin 16.1.0 error

### ISSUE THREAD

**Issue by hammad13060** [npm/npm#15274]
166831 verbose stack Error: read ECONNRESET
166831 verbose stack     at exports._errnoException (util.js:746:11)
166831 verbose stack     at TCP.onread (net.js:561:26)
166832 verbose cwd /Users/hammad13060/mozilla/taskcluster-hooks
166833 error Darwin 16.1.0
166834 error argv "node" "/Users/hammad13060/.nvm/versions/node/v0.12.17/bin/npm" "install"
166835 error node v0.12.17
166836 error npm  v2.7.4
166837 error code ECONNRESET
166838 error errno ECONNRESET
166839 error syscall read
166840 error network read ECONNRESET
166840 error network This is most likely not a problem with npm itself
166840 error network and is related to network connectivity.
166840 error network In most cases you are behind a proxy or have bad network settings.
166840 error network
166840 error network If you are behind a proxy, please make sure that the
166840 error network 'proxy' config is set properly.  See: 'npm help config'
166841 verbose exit [ 1, true ]

**Comment by hammad13060** [comment]
My network is completely fine

**Comment by legodude17** [comment]
What are the results of:
1. `npm config get registry`
2. `npm config get http-proxy`
3. `npm config get https-proxy`

**Comment by hammad13060** [comment]
$ npm config get registry
> https://registry.npmjs.org/

$ npm config get http-proxy
> undefined

$ npm config get https-proxy
> null

**Comment by legodude17** [comment]
What do you get when you go to https://registry.npmjs.org with your browser?

**Comment by hammad13060** [comment]
Well just few moments ago I restarted my laptop and ran `npm install` and it all worked like a charm.

By the way I get some json when I go to  https://registry.npmjs.org

**Comment by legodude17** [comment]
Maybe your laptop was behind it all?

**Comment by hammad13060** [comment]
Yes it looks like that only.

**Comment by KenanY** [comment]
Closing as resolved :)
