### ISSUE TITLE
npm install git error

### ISSUE THREAD

**Issue by alanchn31** [npm/npm#15279]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [X] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

Problem with npm install. Attached is the error log. Have been working on it for days but still have no idea why this error is happening. Can anyone help? Below is the error message:

24082 error Windows_NT 10.0.14393
24083 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\alanchn31\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
24084 error node v7.2.1
24085 error npm  v4.0.5
24086 error code 128
24087 error Command failed: git -c core.longpaths=true clone --template=C:\Users\alanchn31\AppData\Roaming\npm\node_modules\windows-build-tools\Devnodejsnpm-cache\_git-remotes\_templates --mirror https://github.com/debris/bignumber.js.git C:\Users\alanchn31\AppData\Roaming\npm\node_modules\windows-build-tools\Devnodejsnpm-cache\_git-remotes\git-https-github-com-debris-bignumber-js-git-94d7146671b9719e00a09c29b01a691bc85048c2-df3f1ce1
24087 error Cloning into bare repository 'C:\Users\alanchn31\AppData\Roaming\npm\node_modules\windows-build-tools\Devnodejsnpm-cache\_git-remotes\git-https-github-com-debris-bignumber-js-git-94d7146671b9719e00a09c29b01a691bc85048c2-df3f1ce1'...
24087 error fatal: bad object bc66fcfed12c7b4aad528167f3138eb5ad13826f
24087 error fatal: remote did not send all necessary objects
24088 error If you need help, you may report this error at:
24088 error     <https://github.com/npm/npm/issues>

**Comment by alanchn31** [comment]
Here is the error log:


[npm-debug.pdf](https://github.com/npm/npm/files/665810/npm-debug.pdf)

**Comment by anand20kumar1992** [comment]
C:\Users\anna>npm start
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\anna\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v7.2.1
npm ERR! npm  v4.0.5

npm ERR! missing script: start
npm ERR!

**Comment by alanchn31** [comment]
I did npm install after git clone and then I got this error

**Comment by Charlotteis** [comment]
@anand20kumar1992 your issue is completely separate. You don't have a "start" script in your package.json, so you can't run the `start` command. Add a start script and you can. Any further issues, please open a new issue in the tracker :)

**Comment by alanchn31** [comment]
Hi Charlotte, thank you so much for replying! Anyone else facing the same problem or have any suggestions how do I resolve this? It's been bugging me for a really long time.

**Comment by anand20kumar1992** [comment]
{
"name": "a4website",
"version": "1.0.0",
"scripts": {
"tsc": "tsc",
"tsc:w": "tsc -w",
"lite": "lite-server",
"start": "concurrent "npm run tsc:w""
},
"license": "ISC",
"dependencies": {
"angular2": "2.0.0-beta.3",
"systemjs": "0.19.6",
"es6-promise": "^3.0.2",
"es6-shim": "^0.33.3",
"reflect-metadata": "0.1.2",
"rxjs": "5.0.0-beta.0",
"zone.js": "0.5.11"
},
"devDependencies": {
"concurrently": "^1.0.0",
"lite-server": "^2.0.1",
"typescript": "^1.7.5"

**Comment by anand20kumar1992** [comment]
see i have the start script but it gives the same error

**Comment by Charlotteis** [comment]
@anand20kumar1992 it would best to discuss this in another issue.
Change `"concurrent "npm run tsc:w""`
to `"concurrent 'npm run tsc:w'"`

If the problem persists, please open a new issue as this is @alanchn31's issue, which I don't yet know how to solve.
