### ISSUE TITLE
pattern matching npm-script names

### ISSUE THREAD

**Issue by tomdavidson** [npm/npm#15276]
#### What's the feature?

globs in npm-scrpit names, ie (simplistic example):

```json
// rather than 
  "scripts": {
    "pretest:unit": "npm run build",
    "pretest:intg": "npm run build",
    "pretest:e2e": "npm run build",
    "test:unit": "npm run build && mocha --opts mocha.opts src/**/*.unit-spec.ts",
    "test:intg": "npm run build && mocha --opts mocha.opts src/**/*.intg-spec.ts",
    "test:e2e": "npm run build && mocha --opts mocha.opts src/**/*.e2e-spec.ts"
  }

// or
  "scripts": {
    "test:unit": "npm run build && mocha --opts mocha.opts src/**/*.unit-spec.ts",
    "test:intg": "npm run build && mocha --opts mocha.opts src/**/*.intg-spec.ts",
    "test:e2e": "npm run build && mocha --opts mocha.opts src/**/*.e2e-spec.ts"
  }

// we can match a 'pretest' script to apply to all three
  "scripts": {
    "pretest*": "npm run build",
    "test:unit": "mocha --opts mocha.opts src/**/*.unit-spec.ts",
    "test:intg": "mocha --opts mocha.opts src/**/*.intg-spec.ts",
    "test:e2e": "mocha --opts mocha.opts src/**/*.e2e-spec.ts"
  }
```

#### What problem is the feature intended to solve?

Redundancy and noise in package.json, particularly when npm scripts are uses as a primary task runner.

#### Is the absence of this feature blocking you or your team? If so, how?

No. This feature request is mere sugar.
 
#### Is this feature similar to an existing feature in another tool?

No.

#### Is this a feature you're prepared to implement, with support from the npm CLI team?

Yes, that would actually be awesome.

**Comment by legodude17** [comment]
This seems like a cool idea. 👍

**Comment by tomdavidson** [comment]
@legodude17 where would I look in the code base to implement?

**Comment by legodude17** [comment]
Probably `lib/run-script.js`.
