### ISSUE TITLE
npm script parameter with a slash (\\) gets stripped

### ISSUE THREAD

**Issue by ig77** [npm/npm#15273]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [X ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

When you pass a parameter to the npm script that has double slashes (\\), it strips the slash. 

#### How can the CLI team reproduce the problem?

Write a npm script that accepts a parameter for the folder path. Call the npm script using:

npm run mytestscript -- --folder "\\\\myshareddrive\\subfolder1\\subfolder2"

The parameter in the script is "\myshareddrive\subfolder1\subfolder2" instead of "\\myshareddrive\subfolder1\subfolder1"

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
> "\myshareddrive\subfolder1\subfolder2" instead of "\myshareddrive\subfolder1\subfolder1"

Aren't those the same?

**Comment by ig77** [comment]
The editor stripped the slash just like NPM :) 

My last sentence should read "The parameter in the script is "\myshareddrive\subfolder1\subfolder2 (starts with the single slash)" instead of "\\\\myshareddrive\subfolder1\subfolder1" (starts with a double slash)

**Comment by legodude17** [comment]
Ok. My guess is that this is about how `JSON.parse` works, so maybe try four slashes? `\\\\myshar...`
