### ISSUE TITLE
npm crashes on exit cli

### ISSUE THREAD

**Issue by artnova-david** [npm/npm#15275]
I recently updated npm to version 4.0.5. When running my custom script **'npm run dev'** from my package.json file:
```
"scripts": {
    "dev": "set NODE_ENV=development && webpack --watch --progress --colors --hide-modules",
    "build": "set NODE_ENV=production && webpack --optimize-minimize-dedupe --hide-modules"
  }
```
 webpack compiles everything and there is no problem. But, whenever i exit the console by clicking on [x] or ^C, the console freezes for some seconds and then produces this error before closing: 

![2016-12-20_21-22-16](https://cloud.githubusercontent.com/assets/21141231/21368891/ba8e8ec4-c704-11e6-9458-15df4843a4fc.jpg)

when i remove the '--watch' option from the command or run the command native as `webpack --watch` this error does not occur.
I'm currently using node 7 and npm 4.0.5 (note: this error also happened before i installed node 7 but not before i upgraded to npm v4.0.5)
Has anyone else experienced this behavior/error?

[npm-debug.txt](https://github.com/npm/npm/files/664857/npm-debug.txt)

Thanks!

**Comment by legodude17** [comment]
Does the script exit normally if you don't do anything?

**Comment by artnova-david** [comment]
it only happens when i run the script true **"npm run dev"** and then close [X] the console. But when i run **"webpack --w"** OR i remove --watch from my script there is no problem

**Comment by legodude17** [comment]
This might be a `webpack` issue. Try running `set NODE_ENV=development && webpack --watch --progress --colors --hide-modules` and then exiting.

**Comment by artnova-david** [comment]
hi legodude17,
when i type the command `set NODE_ENV=development && webpack --watch --progress --colors --hide-modules` into the console and then click exit all works fine. But the error happens when i type `npm run dev` wich is a custom script from my package.json file and the click exit [X]. and indeed the error does not happen when i remove --watch from my custom script.

**Comment by legodude17** [comment]
I believe this would be something with `npm` or `webpack` not responding to the `kill` correctly.

**Comment by artnova-david** [comment]
I agree one or the other. The question is wich :). Anyway, it happened after I updated npm to version 4.0.5. and I updated node to v7 and webpack to v2.1.0-beta.28 hoping this would solve the error but nothing solves it so far

**Comment by InfiniteStyles** [comment]
It's probably something around NPM's security feature with packages. There was a feature I set that disallowed all packages. Yours probably disallows continuous streaming like --watch somewhere. I believe its an NPM setting somewhere, in relation to how strict NPM is with packages.
