### ISSUE TITLE
How do I get the cwd from an npm script that is run on preinstall

### ISSUE THREAD

**Issue by dominikwilkowski** [npm/npm#15277]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Given the package.json below I get a staging path when I install this module:

```json
{
	"name": "testmodule",
	"version": "0.3.6",
	"description": "TODO",
	"scripts": {
		"preinstall": "pwd && npm root",
	},
	"author": "TODO",
	"license": "MIT"
}
```

The output after publishing this module and installing it inside the folder `/Users/path/to/root` is something similar to:

```shell
/Users/path/to/root/node_modules/.staging/testmodule-5cc9d333
/Users/path/to/root/node_modules/.staging/testmodule-5cc9d333/node_modules
```

I expected this to be:

```shell
/Users/path/to/root
/Users/path/to/root/node_modules
```

The shell actually says:

```shell
> testmodule@0.3.6 preinstall /Users/path/to/root/node_modules/.staging/testmodule-5cc9d333
```

I somehow need to get the "root" `package.json` or the folder that ran the original command `npm i [pkg]` and am not sure how other than splitting the staging string and hoping noone is running his npm install inside a folder incidentally called "node_modules".
Am I totally off here?

### supporting information:

 - `npm -v` prints: `3.10.8`
 - `node -v` prints: `v7.0.0`
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?: `MacOS 10.11.6`

**Comment by legodude17** [comment]
I am not sure I can see the use case for this. Can you please explain it?

**Comment by dominikwilkowski** [comment]
I need to be able to know what the `package.json` path is inside a script I run on `preinstall`.
I get that `process.cwd()` or `__dirname` wouldn't give me anything usable as my script is lunched from the npm process but I can pass `npm root` to the script and get it that way. I would expect `npm root` to give me the correct path here but it just gives me the staging path which is not usable as that's a temp path to my understanding. Does that make sense?

If I just run an npm script `npm root` will return the correct path. Not on `preinstall` though.

**Comment by dominikwilkowski** [comment]
I think it would not be too crazy to think someone want's to access the `package.json` for a preinstall script no? Maybe I'm on the wrong boat here?

**Comment by ndabAP** [comment]
@dominikwilkowski, did you find a solution for this?

**Comment by dominikwilkowski** [comment]
@ndabAP I run everything in `postinstall` now :)
I just so happened that it needed to be change to that lifecycle hook which then circumvented this bug

**Comment by jbruni** [comment]
`process.env.INIT_CWD` FTW
