### ISSUE TITLE
Not able to install 

### ISSUE THREAD

**Issue by chandru102010** [npm/npm#15281]
While installing Kapsel using this command ‘npm install -g c:\KapselSDK\cli’, I am getting below error.

![kapsel_install_failure](https://cloud.githubusercontent.com/assets/24695881/21385953/96488686-c796-11e6-9cce-07abb48ded89.png)

**Comment by Charlotteis** [comment]
@chandru102010 You are using ancient versions of node and npm. Please upgrade to the latest release of Node and npm, and I am confident this error will go away.

**Comment by KenanY** [comment]
Closing. Can reopen if updating `npm` does not help :)
