### ISSUE TITLE
npm Issue 

### ISSUE THREAD

**Issue by lntskyvang** [npm/npm#15283]
While I am building the docker images with Below Docker file I see the Below Issue. 

Docker File
--------------------
```
FROM  centos:centos6

# Enable EPEL for Node.js
RUN     rpm -Uvh http://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm
# Install Node.js and npm
RUN     yum install -y npm

# ADD rpm into container
ADD auditserver-1-1.x86_64.rpm *

#RUN mkdir -p /opt/auditserver 

RUN cd  /opt/auditserver;  npm install


# Bundle app source
#COPY . /src
# Install app dependencies
#RUN cd /src; npm install

EXPOSE  8080
CMD ["node", "/opt/auditserver/server.js"]
```

The issue is below. 
--------------------------------

root@CloudieBase:/usr/couchdb/Test# docker build -t auditserver-image .
Sending build context to Docker daemon 46.08 kB
Step 1 : FROM centos:centos6
 ---> 9c95139afb21
Step 2 : RUN rpm -Uvh http://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm
 ---> Using cache
 ---> 57a1ed7cb453
Step 3 : RUN yum install -y npm
 ---> Using cache
 ---> e9afb9fc99c3
Step 4 : ADD auditserver-1-1.x86_64.rpm *
 ---> 78a7ed349aea
Removing intermediate container e6ec490ae742
Step 5 : RUN cd  /opt/auditserver;  npm install
 ---> Running in 414d7e5b67ce
/bin/sh: line 0: cd: /opt/auditserver: No such file or directory
npm ERR! install Couldn't read dependencies
npm ERR! Error: ENOENT, open '/package.json'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-106-generic
npm ERR! command "node" "/usr/bin/npm" "install"
npm ERR! cwd /
npm ERR! node -v v0.10.46
npm ERR! npm -v 1.3.6
npm ERR! path /package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /npm-debug.log
npm ERR! not ok code 0
The command '/bin/sh -c cd  /opt/auditserver;  npm install' returned a non-zero code: 34
root@CloudieBase:/usr/couchdb/Test# 

Please help me to resolve the issue here, great to help. thanks

Thanks. 
Skylab

**Comment by KenanY** [comment]
@lntskyvang Sorry, `npm@1.3` is years old and is no longer supported.

**Comment by KenanY** [comment]
Looks like you're trying to enter a directory which doesn't exist:

```
/bin/sh: line 0: cd: /opt/auditserver: No such file or directory
```

Must be an issue on your end, not `npm`'s.

**Comment by lntskyvang** [comment]
Hi Kenan.


Could guide me the write docker file.


What I am going to do here.

1) I need to install the npn server

2) I need to run the "node server" command for install the my package application


Here is my Dockerfile

------------------------------------


FROM  centos:centos6

# Enable EPEL for Node.js
RUN     rpm -Uvh http://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm
# Install Node.js and npm
RUN     yum install -y npm

RUN mkdir -p /opt/auditserver

# ADD rpm into container
ADD auditserver-1-1.x86_64.rpm *

#RUN mkdir -p /opt/auditserver

RUN cd  /opt/auditserver
RUN  npm install


# Bundle app source
#COPY . /src
# Install app dependencies
#RUN cd /src; npm install

EXPOSE  8080
CMD ["node", "/opt/auditserver/server.js"]



Here is the issue.

----------------------------------


root@CloudieBase:/usr/couchdb/Test# docker build -t auditserver-image .
Sending build context to Docker daemon 46.08 kB
Step 1 : FROM centos:centos6
 ---> 9c95139afb21
Step 2 : RUN rpm -Uvh http://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm
 ---> Using cache
 ---> 57a1ed7cb453
Step 3 : RUN yum install -y npm
 ---> Using cache
 ---> e9afb9fc99c3
Step 4 : RUN mkdir -p /opt/auditserver
 ---> Using cache
 ---> 5c1dbffda159
Step 5 : ADD auditserver-1-1.x86_64.rpm *
 ---> Using cache
 ---> 125def62ea6a
Step 6 : RUN cd  /opt/auditserver
 ---> Running in 95d2a685c27c
 ---> 07dc16caa4cd
Removing intermediate container 95d2a685c27c
Step 7 : RUN npm install
 ---> Running in a696d473b56a
npm ERR! install Couldn't read dependencies
npm ERR! Error: ENOENT, open '/package.json'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-106-generic
npm ERR! command "node" "/usr/bin/npm" "install"
npm ERR! cwd /
npm ERR! node -v v0.10.46
npm ERR! npm -v 1.3.6
npm ERR! path /package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /npm-debug.log
npm ERR! not ok code 0
The command '/bin/sh -c npm install' returned a non-zero code: 34
root@CloudieBase:/usr/couchdb/Test#


________________________________

**Comment by KenanY** [comment]
@lntskyvang I must admit that I'm not familiar enough with what you're trying to do to provide any further assistance. Hopefully you find someone else more knowledgeable on a different forum. Sorry I couldn't be of any further help :(
