### ISSUE TITLE
postinstall hook doesn't work

### ISSUE THREAD

**Issue by AttilaVM** [npm/npm#15285]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I wrote a small npm package using babel js. There is a small script, which handles the build, associated with the postinstall and build hooks (The redundancy is for the sake of testing around this problem).

the script:
```
#!/usr/bin/env node

const path = require('path');
const exec = require('child_process').exec;
const chdir = require('process').chdir;

// Get paths
const projectRoot = path.join(path.dirname(__dirname));
const srcDir = path.join(projectRoot, 'src');
const out = path.join(projectRoot, 'out');
const babelExecutable = path.join(path.dirname(projectRoot), '.bin', 'babel');

// Generate build command
const buildCmd = `${babelExecutable} index.js --no-babelrc --presets=es2015-node6 --out-dir ${out}`;

// Go to source directory, then build project with babel
chdir(srcDir);
exec(buildCmd, function getSTDOut(stdout) {
        console.log(stdout);
});
```
IMPORTANT: I included this script for the sake of  completeness, however I strongly suspect that its content or even existence on the filesystem is irrelevant for the reproducibility of my mistake/npm bug 

the snippet from package.json

```
"scripts": {
		"test": "mocha test/test.js",
		"postinstall:": "node scripts/build.js",
		"build:": "node scripts/build.js",
		"act": "node scripts/build.js"
	},
```
Installing the package does not trigger the script, even navigating into the installed module and trying to run the scripts with npm run <build/postinstall> won't work, however npm run act will work.

#### How can the CLI team reproduce the problem?

```
mkdir test
cd test
npm init && npm i -D gulp-lazy-pipelines@0.0.12
# Failed: scripts/build.js did not run. LOG_1 
cd node_modules/gulp-lazy-pipelines
npm run postinstall # or npm run build
# Failed LOG_2
npm run act
# Succeed LOG_3
```

[LOG_1](https://gist.github.com/AttilaVM/ff5578a6927ba59a98c83af95bd24702)
[LOG_2](https://gist.github.com/AttilaVM/925c5f6fc1886eb24172bbe8fc1a3c62)
[LOG_3](https://gist.github.com/AttilaVM/b47654d4e23197c7ef4f5680762e8b4c)

### supporting information:

 - `npm -v` prints: 3.10.3
 - `node -v` prints: v6.6.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux
 - Network issues: None
   - Geographic location where npm was run: Pécs, Hungary
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
That is very strange that the `postinstall` and `build` scripts aren't detected. Can you provide a link to the full repo?

**Comment by AttilaVM** [comment]
Sure, thanks
https://github.com/AttilaVM/gulp-lazy-pipelines
