### ISSUE TITLE
Invalid username or password

### ISSUE THREAD

**Issue by floraJose** [npm/npm#15282]
#### I'm opening this issue because:

  - [ ] npm is not installing
  i am trying to use "npm install" command.

It shows "fatal: Authentication failed for 'https://github.com/lukeautry/node-buffers.git/'
" 
 Cloning into bare repository '/Users/florajakulin/.npm/_git-remotes/git-https-github-com-lukeautry-node-buffers-git-f3c8e251'...
npm ERR! remote: Invalid username or password.

i am using mac machine for the same. Could you please guide me to solve the issue.

**Comment by legodude17** [comment]
Is https://github.com/lukeautry/node-buffers.git/ a private repo? If it isn't, it doesn't exist. Either way, that is the problem.

**Comment by Charlotteis** [comment]
That repository used to exist but no longer does.
It looks like it changed ownership and can now be found here: https://github.com/substack/node-buffers

**Comment by KenanY** [comment]
Closing as abandoned.
