### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by zhangzlili** [npm/npm#15286]
#### I'm opening this issue because:

My goal is to run shopify's js-buy-sdk examples locally on my vps hosting site. However, after my doing "git clone git@github.com:Shopify/js-buy-sdk.git" to /home/posnowz/js-buy-sdk/ on my vps hosting site, I typed the following: 

[posnowz@vps ~]$ cd js-buy-sdk/examples
[posnowz@vps examples]$ ls
README.md  cart  checkout  npm-debug.log
[posnowz@vps examples]$ npm install
Enter passphrase for key '/home/posnowz/.ssh/id_rsa':

then I got the error message as the following:

npm ERR! Linux 2.6.32-042stab092.2
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v4.6.2
npm ERR! npm  v4.0.3
npm ERR! code ENOMEM
npm ERR! errno ENOMEM
npm ERR! syscall spawn

npm ERR! spawn ENOMEM
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/posnowz/js-buy-sdk/examples/npm-debug.log
[posnowz@vps examples]$

### supporting information:

 - OS is Linux CentOS.
 - Network issues:
   - Geographic location where npm was run:
          I have installed npm locally on the vps hosting site.  
 - Container:
          I have not known.

**Comment by zhangzlili** [comment]
the passphrase for npm install is midnight

**Comment by zhangzlili** [comment]
[npm-debug.txt](https://github.com/npm/npm/files/666945/npm-debug.txt)

**Comment by legodude17** [comment]
This appears to be a problem where the computer has not enough RAM for `npm` to use.

**Comment by zhangzlili** [comment]
Hello Jushua,


I have asked the webmaster to double the sizes of both the real memory and virtual memory. And I still got the exact same error message as before:



[posnowz@vps ~]$ cd js-buy-sdk/examples
[posnowz@vps examples]$ npm install
Enter passphrase for key '/home/posnowz/.ssh/id_rsa':


npm ERR! Linux 2.6.32-042stab092.2
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v4.6.2
npm ERR! npm  v4.0.3
npm ERR! code ENOMEM
npm ERR! errno ENOMEM
npm ERR! syscall spawn


npm ERR! spawn ENOMEM
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>


npm ERR! Please include the following file with any support request:
npm ERR!     /home/posnowz/js-buy-sdk/examples/npm-debug.log
[posnowz@vps examples]$



And also I attached the npm-debug.txt for you to view.


Please help me out with this.


Thanks,
Lili





Lili Z. Zhang
zhangzlili@aol.com




-----Original Message-----

**Comment by sempasha** [comment]
I experience same issue.

NPM has very aggressive memory consumption. It starts from 24MB up to 640 MB before crash.

Tail of `npm-debug.log`:

    ...
    104108 info lifecycle bufferutil@1.2.1~install: bufferutil@1.2.1
    104109 verbose lifecycle bufferutil@1.2.1~install: unsafe-perm in lifecycle false
    104110 verbose lifecycle bufferutil@1.2.1~install: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/app/node_modules/bufferutil/node_modules/.bin:/app/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    104111 verbose lifecycle bufferutil@1.2.1~install: CWD: /app/node_modules/bufferutil
    104112 silly lifecycle bufferutil@1.2.1~install: Args: [ '-c', 'node-gyp rebuild' ]
    104113 verbose stack Error: spawn ENOMEM
    104113 verbose stack     at exports._errnoException (util.js:1018:11)
    104113 verbose stack     at ChildProcess.spawn (internal/child_process.js:319:11)
    104113 verbose stack     at exports.spawn (child_process.js:378:9)
    104113 verbose stack     at spawn (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:21:13)
    104113 verbose stack     at runCmd_ (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:247:14)
    104113 verbose stack     at /usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:211:7
    104113 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:73:7)
    104113 verbose stack     at process._tickCallback (internal/process/next_tick.js:104:9)
    104114 verbose cwd /app
    104115 error Linux 4.11.0-coreos
    104116 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--only=dev"
    104117 error node v6.10.3
    104118 error npm  v3.10.10
    104119 error code ENOMEM
    104120 error errno ENOMEM
    104121 error syscall spawn
    104122 error spawn ENOMEM
    104123 error If you need help, you may report this error at:
    104123 error     <https://github.com/npm/npm/issues>
    104124 verbose exit [ 1, true ]

**Comment by legodude17** [comment]
How much RAM does the machine have? Also, try updating `npm` to latest.

**Comment by sempasha** [comment]
Virtual machine has 1GB size RAM.
With node 7.10.0 and npm v4.2.0 result is the same.

**Comment by legodude17** [comment]
Can you provide `package.json` (feel free to remove sensitize bits)?

**Comment by sempasha** [comment]
Here it is
```json
{
  "name": "angular-app",
  "version": "0.0.0",
  "dependencies": {},
  "devDependencies": {
    "bower": "1.x",
    "estraverse": "~4.1.0",
    "gulp": "~3.9.0",
    "gulp-autoprefixer": "~3.0.2",
    "gulp-angular-templatecache": "~1.8.0",
    "del": "~2.0.2",
    "lodash": "~3.10.1",
    "gulp-cssnano": "~2.1.1",
    "gulp-filter": "~3.0.1",
    "gulp-flatten": "~0.2.0",
    "gulp-eslint": "~1.0.0",
    "eslint-plugin-angular": "~0.12.0",
    "gulp-load-plugins": "~0.10.0",
    "gulp-size": "~2.0.0",
    "gulp-uglify": "~1.4.1",
    "gulp-useref": "~3.0.3",
    "gulp-util": "~3.0.6",
    "gulp-ng-annotate": "~1.1.0",
    "gulp-replace": "~0.5.4",
    "gulp-rename": "~1.2.2",
    "gulp-rev": "~6.0.1",
    "gulp-rev-replace": "~0.4.2",
    "gulp-htmlmin": "~1.3.0",
    "gulp-inject": "~3.0.0",
    "gulp-protractor": "~2.1.0",
    "gulp-sourcemaps": "~1.6.0",
    "gulp-less": "~3.0.3",
    "gulp-angular-filesort": "~1.1.1",
    "main-bower-files": "~2.9.0",
    "wiredep": "~2.2.2",
    "karma": "~0.13.10",
    "karma-jasmine": "~0.3.6",
    "karma-phantomjs-launcher": "~0.2.1",
    "phantomjs": "~1.9.18",
    "karma-angular-filesort": "~1.0.0",
    "karma-phantomjs-shim": "~1.2.0",
    "karma-coverage": "~0.5.2",
    "karma-ng-html2js-preprocessor": "~0.2.0",
    "browser-sync": "~2.9.11",
    "browser-sync-spa": "~1.0.3",
    "http-proxy-middleware": "~0.9.0",
    "chalk": "~1.1.1",
    "uglify-save-license": "~0.4.1"
  },
  "engines": {
    "node": ">=0.10.0"
  }
}
```

**Comment by sempasha** [comment]
I also have made a [memory dump](https://drive.google.com/open?id=0Bz8VmfdGGMJIcGprQnZxOXdFM3c)
