### ISSUE TITLE
npm install react --save  error

### ISSUE THREAD

**Issue by luckyyhf** [npm/npm#15280]
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\nodejs\\node.exe',
1 verbose cli   'D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'react',
1 verbose cli   '--save' ]
2 info using npm@3.10.9
3 info using node@v6.9.2
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData react
8 silly fetchNamedPackageData react
9 silly mapToRegistry name react
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'react',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'react',
12 silly mapToRegistry   name: 'react',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/react
14 verbose request uri https://registry.npmjs.org/react
15 verbose request no auth needed
16 info attempt registry request try #1 at 17:38:49
17 verbose request id eff3aff3cf415035
18 verbose etag W/"5858ab37-2100f"
19 verbose lastModified Tue, 20 Dec 2016 03:53:27 GMT
20 http request GET https://registry.npmjs.org/react
21 http 304 https://registry.npmjs.org/react
22 verbose headers { date: 'Wed, 21 Dec 2016 09:40:26 GMT',
22 verbose headers   via: '1.1 varnish',
22 verbose headers   'cache-control': 'max-age=300',
22 verbose headers   etag: 'W/"5858ab37-2100f"',
22 verbose headers   age: '123',
22 verbose headers   connection: 'keep-alive',
22 verbose headers   'x-served-by': 'cache-itm7421-ITM',
22 verbose headers   'x-cache': 'HIT',
22 verbose headers   'x-cache-hits': '38',
22 verbose headers   'x-timer': 'S1482313226.957630,VS0,VE0',
22 verbose headers   vary: 'Accept-Encoding' }
23 silly get cb [ 304,
23 silly get   { date: 'Wed, 21 Dec 2016 09:40:26 GMT',
23 silly get     via: '1.1 varnish',
23 silly get     'cache-control': 'max-age=300',
23 silly get     etag: 'W/"5858ab37-2100f"',
23 silly get     age: '123',
23 silly get     connection: 'keep-alive',
23 silly get     'x-served-by': 'cache-itm7421-ITM',
23 silly get     'x-cache': 'HIT',
23 silly get     'x-cache-hits': '38',
23 silly get     'x-timer': 'S1482313226.957630,VS0,VE0',
23 silly get     vary: 'Accept-Encoding' } ]
24 verbose etag https://registry.npmjs.org/react from cache
25 verbose get saving react to C:\Users\Administrator\AppData\Roaming\npm-cache\registry.npmjs.org\react\.cache.json
26 verbose correctMkdir C:\Users\Administrator\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
27 silly install normalizeTree
28 silly loadCurrentTree Finishing
29 silly loadIdealTree Starting
30 silly install loadIdealTree
31 silly cloneCurrentTree Starting
32 silly install cloneCurrentTreeToIdealTree
33 silly cloneCurrentTree Finishing
34 silly loadShrinkwrap Starting
35 silly install loadShrinkwrap
36 silly loadShrinkwrap Finishing
37 silly loadAllDepsIntoIdealTree Starting
38 silly install loadAllDepsIntoIdealTree
39 silly rollbackFailedOptional Starting
40 silly rollbackFailedOptional Finishing
41 silly runTopLevelLifecycles Finishing
42 silly install printInstalled
43 verbose stack Error: Refusing to install react as a dependency of itself
43 verbose stack     at checkSelf (D:\nodejs\node_modules\npm\lib\install\validate-args.js:53:14)
43 verbose stack     at Array.<anonymous> (D:\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
43 verbose stack     at LOOP (D:\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
43 verbose stack     at chain (D:\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
43 verbose stack     at D:\nodejs\node_modules\npm\lib\install\validate-args.js:16:5
43 verbose stack     at D:\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
43 verbose stack     at Array.forEach (native)
43 verbose stack     at D:\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
43 verbose stack     at Array.forEach (native)
43 verbose stack     at asyncMap (D:\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
44 verbose cwd d:\react
45 error Windows_NT 6.1.7601
46 error argv "D:\\nodejs\\node.exe" "D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "react" "--save"
47 error node v6.9.2
48 error npm  v3.10.9
49 error code ENOSELF
50 error Refusing to install react as a dependency of itself
51 error If you need help, you may report this error at:
51 error     <https://github.com/npm/npm/issues>
52 verbose exit [ 1, true ]

**Comment by Charlotteis** [comment]
Hi!

> Error: Refusing to install react as a dependency of itself

In your package.json file, what is the name of the module? Check the `"name"` line. If you've called it "react" then you need to change it to something else, as npm wont install "React" in a project you've called "React".

Hope this helps!

🌸

**Comment by KenanY** [comment]
Closing as abandoned.
