### ISSUE TITLE
NPM install error

### ISSUE THREAD

**Issue by jluo1226** [npm/npm#15287]
#### I'm opening this issue because:
npm install failed

#### What's going wrong?

1941 error Windows_NT 6.1.7601
1942 error argv "c:\\apps\\nodejs\\node.exe" "c:\\apps\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
1943 error node v0.12.0
1944 error npm  v2.5.1
1945 error Unexpected token <
1945 error <html>
1945 error   <head>
1945 error     <title>404 - Path /@angular/common not found in group repository &quot;ext-all-npm-group&quot; [id=ext-all-npm-group].</title>
1945 error     <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
1945 error
1945 error     <link rel="icon" type="image/png" href="https://itbox-nexus-ext.fr.world.socgen/nexus-ext/c/favicon.png">
1945 error     
1945 error
1945 error     <link rel="stylesheet" href="https://itbox-nexus-ext.fr.world.socgen/nexus-ext/c/static/css/Sonatype-content.css?2.12.0-01" type="text/css" media="screen" title="no title" charset="utf-8">
1945 error   </head>
1945 error   <body>
1945 error     <h1>404 - Path /@angular/common not found in group repository &quot;ext-all-npm-group&quot; [id=ext-all-npm-group].</h1>
1945 error     <p>Path /@angular/common not found in group repository &quot;ext-all-npm-group&quot; [id=ext-all-npm-group].</p>
1945 error   </body>
1945 error </html>

**Comment by legodude17** [comment]
What are the results of:
1. `npm config get registry`
2. `npm config get http-proxy`
3. `npm config get https-proxy`

**Comment by jluo1226** [comment]
registry: http://registry.npmjs.org
proxy: both undefined.

**Comment by legodude17** [comment]
What command did you run?

**Comment by jluo1226** [comment]
npm install
I later noticed that I don't have the proxy access to reach http://registry.npmjs.org at all.
I changed the registry to a local company's repository. The repository did not cover this library neither.  Wonder how most people do to have their npm install w/o issues.  Is there anyway to copy these libs into local?

**Comment by legodude17** [comment]
You can download the tarballs manually
