### ISSUE TITLE
npm install issue

### ISSUE THREAD

**Issue by thiruprasad** [npm/npm#15296]
[exec] npm ERR! Windows_NT 6.1.7601
     [exec] npm ERR! argv "C:\\ProgramData\\nodejs\\node.exe" "C:\\ProgramData\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
     [exec] npm ERR! node v4.2.2
     [exec] npm ERR! npm  v2.14.7
     [exec] 
     [exec] npm ERR! version not found: engine.io-client@1.8.2
     [exec] npm ERR! 
     [exec] npm ERR! If you need help, you may report this error at:
     [exec] npm ERR!     <https://github.com/npm/npm/issues>
     [exec] 
     [exec] npm ERR! Please include the following file with any support request:
     [exec] npm ERR!     C:\tmp\BUIC\Auto_Installer\test-buic-new\npm-debug.log
### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
What does your package.json look like?

**Comment by thiruprasad** [comment]
{
  "name": "test-buic-new",  
  "version": "1.0.0",
  "description": "Im a sample buic",
  "main": "dist/index.js",
  "author": "End User Team",
  "license": "BofA Private",
  "files": [
    "package.json",
    "app.js",
    "pom.xml",
    "config.js",
    "bundle.config.json",
    "bundle.js",
    "config-buic.js",
    "index.html",
    "dist"
  ],
  "repository": {
    "type": "tfs",
    "url": "<tfs url>"
  },
  "engines": {
    "node": ">=4.2.1 <5.0.0",
    "npm": ">=3.5.2"
  },
  "preferGlobal": false,
    "keywords": [
      "test-buic-new",
      "End User Team",
      "Im a sample buic"
    ],
  "jspmNodeConversion": false,
  "jspm": {
    "main": "index",
    "directories": {
      "lib": "dist"
    },
    "dependencies": {
      "angular": "npm:angular@1.4.4",
      "angular-mocks": "npm:angular-mocks@^1.5.6",
      "css": "github:systemjs/plugin-css@^0.1.20",
      "etp-angular-ui": "npm:etp-angular-ui@^2.1.0",
      "image": "npm:bofa-image@^1.0.0",
      "jquery": "github:components/jquery@^1.11.3",
      "json": "github:systemjs/plugin-json@^0.1.0",
      "text": "github:systemjs/plugin-text@^0.0.4"
    },
    "devDependencies": {
      "clean-css": "npm:clean-css@^3.4.6",
      "core-js": "npm:core-js@^1.1.4"
    }
  },
  "devDependencies": {
    "browser-sync": "^2.9.11",
    "del": "^2.0.2",
    "gulp": "^3.9.0",
    "gulp-babel": "5.3.0",
    "gulp-bump": "1.0.0",
    "gulp-changed": "^1.3.0",
    "gulp-jspm": "^0.5.8",
    "gulp-minify": "0.0.5",
    "gulp-plumber": "^1.0.1",
    "gulp-sourcemaps": "^1.6.0",
    "gulp-typescript": "^2.10.0",
    "jasmine": "^2.4.2",
    "jspm": "0.16.30",
    "jspm-bofa-github": "^1.1.3",
    "karma": "^0.13.22",
    "karma-jasmine": "^0.3.6",
    "karma-phantomjs-launcher": "^0.2.3",
    "merge2": "^0.3.6",
    "phantomjs": "^2.1.11",
    "require-dir": "^0.3.0",
    "run-sequence": "^1.1.5",
    "semver": "^5.0.3",
    "vinyl-paths": "^2.1.0"
  },
  "dependencies": {
    "vinyl-paths": "^2.1.0",
    "browser-sync": "^2.9.11",
    "del": "^2.0.2",
    "gulp": "^3.9.0",
    "gulp-plumber": "^1.0.1",
    "gulp-babel": "5.3.0",
    "gulp-changed": "^1.3.0",
    "gulp-sourcemaps": "^1.6.0",
    "gulp-minify": "0.0.5",
    "karma": "^0.13.11",
    "merge2": "^0.3.6",
    "jspm": "0.16.30",
    "object.assign": "^1.0.3",
    "jspm-bofa-github": "^1.0.0",
    "require-dir": "^0.3.0",
    "run-sequence": "^1.1.5",
    "gulp-typescript": "^2.10.0",
    "gulp-bump": "1.0.0"
  },
  "scripts": {
    "buicpublish": "npm version patch && npm publish"
  }
}

**Comment by legodude17** [comment]
What command did you run? Also, you package.json seems to be malformed.

**Comment by thiruprasad** [comment]
Command used : mvn package and mvn install
package.json
----------------
{
  "name": "test-buic-new",  
  "version": "1.0.0",
  "description": "Im a sample buic",
  "main": "dist/index.js",
  "author": "End User Team",
  "license": "BofA Private",
  "files": [
    "package.json",
    "app.js",
    "pom.xml",
    "config.js",
    "bundle.config.json",
    "bundle.js",
    "config-buic.js",
    "index.html",
    "dist"
  ],
  "repository": {
    "type": "tfs",
    "url": "<tfs url>"
  },
  "engines": {
    "node": ">=4.2.1 <5.0.0",
    "npm": ">=3.5.2"
  },
  "preferGlobal": false,
    "keywords": [
      "test-buic-new",
      "End User Team",
      "Im a sample buic"
    ],
  "jspmNodeConversion": false,
  "jspm": {
    "main": "index",
    "directories": {
      "lib": "dist"
    },
    "dependencies": {
      "angular": "npm:angular@1.4.4",
      "angular-mocks": "npm:angular-mocks@^1.5.6",
      "css": "github:systemjs/plugin-css@^0.1.20",
      "etp-angular-ui": "npm:etp-angular-ui@^2.1.0",
      "image": "npm:bofa-image@^1.0.0",
      "jquery": "github:components/jquery@^1.11.3",
      "json": "github:systemjs/plugin-json@^0.1.0",
      "text": "github:systemjs/plugin-text@^0.0.4"
    },
    "devDependencies": {
      "clean-css": "npm:clean-css@^3.4.6",
      "core-js": "npm:core-js@^1.1.4"
    }
  },
  "devDependencies": {
    "browser-sync": "^2.9.11",
    "del": "^2.0.2",
    "gulp": "^3.9.0",
    "gulp-babel": "5.3.0",
    "gulp-bump": "1.0.0",
    "gulp-changed": "^1.3.0",
    "gulp-jspm": "^0.5.8",
    "gulp-minify": "0.0.5",
    "gulp-plumber": "^1.0.1",
    "gulp-sourcemaps": "^1.6.0",
    "gulp-typescript": "^2.10.0",
    "jasmine": "^2.4.2",
    "jspm": "0.16.30",
    "jspm-bofa-github": "^1.1.3",
    "karma": "^0.13.22",
    "karma-jasmine": "^0.3.6",
    "karma-phantomjs-launcher": "^0.2.3",
    "merge2": "^0.3.6",
    "phantomjs": "^2.1.11",
    "require-dir": "^0.3.0",
    "run-sequence": "^1.1.5",
    "semver": "^5.0.3",
    "vinyl-paths": "^2.1.0"
  },
  "dependencies": {
    "vinyl-paths": "^2.1.0",
    "browser-sync": "^2.9.11",
    "del": "^2.0.2",
    "gulp": "^3.9.0",
    "gulp-plumber": "^1.0.1",
    "gulp-babel": "5.3.0",
    "gulp-changed": "^1.3.0",
    "gulp-sourcemaps": "^1.6.0",
    "gulp-minify": "0.0.5",
    "karma": "^0.13.11",
    "merge2": "^0.3.6",
    "jspm": "0.16.30",
    "object.assign": "^1.0.3",
    "jspm-bofa-github": "^1.0.0",
    "require-dir": "^0.3.0",
    "run-sequence": "^1.1.5",
    "gulp-typescript": "^2.10.0",
    "gulp-bump": "1.0.0"
  },
  "scripts": {
    "buicpublish": "npm version patch && npm publish"
  }
}

**Comment by legodude17** [comment]
What do you expect to happen? This seems to be a problem with maven or your maven config or you package.json.
