### ISSUE TITLE
NPM error when installing bower

### ISSUE THREAD

**Issue by ayyoobcastro** [npm/npm#15292]
if download bower using npm the following error is showing

C:\Users\shafi>npm install -g bower
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\shafi\\AppData\\
Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "bower"
npm ERR! node v7.2.1
npm ERR! npm  v3.7.1
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'internal/fs'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\shafi\npm-debug.log

can you any one help me to fix this error 

thanks for advance

**Comment by legodude17** [comment]
I would suggest updating `npm`. Also please post `npm-debug.log`.
