### ISSUE TITLE
I m geting this error on makeing the dist of my project

### ISSUE THREAD

**Issue by anandangular** [npm/npm#15293]
Linux 4.4.0-53-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build:prod"
npm ERR! node v6.9.1
npm ERR! npm  v4.0.2

npm ERR! missing script: build:prod
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/lampp/htdocs/angular/angular2-webpack-master (copy)/npm-debug.

**Comment by Charlotteis** [comment]
Can you share your `package.json` please?

**Comment by KenanY** [comment]
Closing as abandoned.
