### ISSUE TITLE
Facing error while publishing scope to Artifactory "npm ERR! Registry returned 405 for PUT"

### ISSUE THREAD

**Issue by sukhada369** [npm/npm#15290]
npm ERR! publish Failed PUT 405
21-Dec-2016 20:48:18	npm ERR! Linux 2.6.32-358.23.2.el6.x86_64
21-Dec-2016 20:48:18	npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "publish"
21-Dec-2016 20:48:18	npm ERR! node v4.5.0
21-Dec-2016 20:48:18	npm ERR! npm  v3.10.7
21-Dec-2016 20:48:18	npm ERR! code E405
21-Dec-2016 20:48:18	
21-Dec-2016 20:48:18	npm ERR! Registry returned 405 for PUT on xxxxxx

**Comment by legodude17** [comment]
Can you put the `npm-debug.log` on https://gist.github.com and then post the link?

**Comment by sukhada369** [comment]
I cannot add that data. It is giving me " verbose request invalidating /path/to/the/.npm/_40<scope_name>_252f<package_name> on PUT"


What all things need to be checklist while working with this kind of integration?

**Comment by legodude17** [comment]
That might be it.

**Comment by captainkovalsky** [comment]
I also tried this one and have got the same error. It looks like we need to configure the nginx. Can we do this without nginx?

**Comment by grillorafael** [comment]
Tried a fresh instance of Artifactory 5.3.0 SAAS and I'm having the same issue. Is there any limitation on the name of the scope?

I get 405 PUT but if I remove the @scope/ it works without a problem

EDIT:
`npm ERR! Registry returned 405 for PUT on https://genscape.jfrog.io/genscape/api/npm/npm/@maritime%2fhello-module`

**Comment by mbtts** [comment]
Also an issue for me with 5.3.0 (revision 50045) SAAS on Azure.
Removing the scope works.

This property is enabled in tomcat:
`-Dorg.apache.tomcat.util.buf.UDecoder.ALLOW_ENCODED_SLASH=true`

This has some details:
[Setting up Artifactory as npm repository behind Apache](https://techblog.dorogin.com/setting-up-artifactory-as-npm-repository-behind-apache-7541d5140492)

However not sure how the SAAS is configured - whether it sits behind Apache/Nginx/something else.

**Comment by grillorafael** [comment]
My issue was fixed by moving Artifactory Saas instance from Azure to EC2. Seems that their setup on azure is not properly done

**Comment by ArielZhang** [comment]
I got the same issue.. maybe I should try move from Azure to EC2.

**Comment by iarna** [comment]
This does not seem to be a problem with npm— if you're getting 405 errors from Artifactory then you'll need to raise it with their support.
