### ISSUE TITLE
npm ERR! Command failed: git -c core.longpaths=true

### ISSUE THREAD

**Issue by lionala** [npm/npm#15291]
npm install is not working. it gives some error.

$ npm install
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config -                                                                         -get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:202:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:852:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:323:1                                                                         1)
npm WARN addRemoteGit     at emitOne (events.js:96:13)
npm WARN addRemoteGit     at Socket.emit (events.js:188:7)
npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:492:12)
npm WARN addRemoteGit  git+ssh://git@bitbucket.org/hmheng/contentdatapersistence                                                                         .git#v2.5.2 resetting remote C:\Users\lional.arokiaraj\AppData\Roaming\npm-cache                                                                         \_git-remotes\git-ssh-git-bitbucket-org-hmheng-contentdatapersistence-git-v2-5-2                                                                         -ab153cc1 because of error: { Error: Command failed: git -c core.longpaths=true                                                                          config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:202:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:852:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:323:1                                                                         1)
npm WARN addRemoteGit     at emitOne (events.js:96:13)
npm WARN addRemoteGit     at Socket.emit (events.js:188:7)
npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:492:12)
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.ori                                                                         gin.url' }
npm ERR! git clone --template=C:\Users\lional.arokiaraj\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror ssh://git@bitbucket.org/hmheng/con    tentdatapersistence.git C:\Users\lional.arokiaraj\AppData\Roaming\npm-cache\_git-remotes\git-ssh-git-bitbucket-org-hmheng-contentdatapersistence-git-    v2-5-2-ab153cc1: Cloning into bare repository 'C:\Users\lional.arokiaraj\AppData\Roaming\npm-cache\_git-remotes\git-ssh-git-bitbucket-org-hmheng-cont    entdatapersistence-git-v2-5-2-ab153cc1'...
npm ERR! git clone --template=C:\Users\lional.arokiaraj\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror ssh://git@bitbucket.org/hmheng/con    tentdatapersistence.git C:\Users\lional.arokiaraj\AppData\Roaming\npm-cache\_git-remotes\git-ssh-git-bitbucket-org-hmheng-contentdatapersistence-git-    v2-5-2-ab153cc1: conq: repository access denied.
npm ERR! git clone --template=C:\Users\lional.arokiaraj\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror ssh://git@bitbucket.org/hmheng/con    tentdatapersistence.git C:\Users\lional.arokiaraj\AppData\Roaming\npm-cache\_git-remotes\git-ssh-git-bitbucket-org-hmheng-contentdatapersistence-git-    v2-5-2-ab153cc1: fatal: Could not read from remote repository.
npm ERR! git clone --template=C:\Users\lional.arokiaraj\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror ssh://git@bitbucket.org/hmheng/con    tentdatapersistence.git C:\Users\lional.arokiaraj\AppData\Roaming\npm-cache\_git-remotes\git-ssh-git-bitbucket-org-hmheng-contentdatapersistence-git-    v2-5-2-ab153cc1:
npm ERR! git clone --template=C:\Users\lional.arokiaraj\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror ssh://git@bitbucket.org/hmheng/con    tentdatapersistence.git C:\Users\lional.arokiaraj\AppData\Roaming\npm-cache\_git-remotes\git-ssh-git-bitbucket-org-hmheng-contentdatapersistence-git-    v2-5-2-ab153cc1: Please make sure you have the correct access rights
npm ERR! git clone --template=C:\Users\lional.arokiaraj\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror ssh://git@bitbucket.org/hmheng/con    tentdatapersistence.git C:\Users\lional.arokiaraj\AppData\Roaming\npm-cache\_git-remotes\git-ssh-git-bitbucket-org-hmheng-contentdatapersistence-git-    v2-5-2-ab153cc1: and the repository exists.
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\lional.arokiaraj\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install    "
npm ERR! node v6.3.0
npm ERR! npm  v4.0.5
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\lional.arokiaraj\AppData\Roaming\npm-cache\_git-remotes\_templates --mi    rror ssh://git@bitbucket.org/hmheng/contentdatapersistence.git C:\Users\lional.arokiaraj\AppData\Roaming\npm-cache\_git-remotes\git-ssh-git-bitbucket    -org-hmheng-contentdatapersistence-git-v2-5-2-ab153cc1
npm ERR! Cloning into bare repository 'C:\Users\lional.arokiaraj\AppData\Roaming\npm-cache\_git-remotes\git-ssh-git-bitbucket-org-hmheng-contentdatap    ersistence-git-v2-5-2-ab153cc1'...
npm ERR! conq: repository access denied.
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\gitnew\annServiceTokenGenerator\npm-debug.log

Please help me about this issue...

**Comment by legodude17** [comment]
Do you have the correct `ssh` keys setup?
