### ISSUE TITLE
HELP ASAP!! error Windows_NT 6.1.7601 

### ISSUE THREAD

**Issue by and2one** [npm/npm#15298]
Hi ,somebody know what is the solution of the problem? I am trying to install mongoose.Thats the first time I have this kind of error.Before that I had install ionic and corodova the same way and didnt have a problem.I tryed npm cache clean.
I simply tryed to start npm but I had this error.

error Windows_NT 6.1.7601
 error argv "C:\\Program Files (x86)\\nodejs\\node.exe"
 "C:\\Program Files(x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
error node v5.1.1
error npm  v3.3.12
error missing script: start
error If you need help, you may report this error at:
error     <https://github.com/npm/npm/issues>

### supporting information:

 - `npm -v` prints: 3.3.12
 - `node -v` prints: 5.1.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows

**Comment by Charlotteis** [comment]
Can I see what your `package.json` looks like? If there is no `start` script defined in it, you can't run `npm start`.

**Comment by and2one** [comment]
{
  "name": "andrey",
  "version": "1.0.0",
  "description": "test",
  "main": "idex.js",
  "dependencies": {},
  "devDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "andrey",
  "license": "ISC"
  
}

**Comment by Charlotteis** [comment]
@and2one 

You have no "start" script. In order to run `npm start`, you need a "start" script.

Also, your "main" file is mispelt, it should probably be "index.js"

**Comment by KenanY** [comment]
Closing as abandoned.
