### ISSUE TITLE
npm ERR! install Couldn't read dependencies

### ISSUE THREAD

**Issue by sebasaenz** [npm/npm#15297]
I ran the command "npm install" and I had this message as a response:

```
npm ERR! install Couldn't read dependencies
npm ERR! Linux 4.4.0-21-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.6.2
npm ERR! npm  v2.15.11

npm ERR! Invalid version: "1.0"
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/sebastian/node-example/npm-debug.log
```
I've tried to solve this with other issues I read, but it seems to be different.

I'm using Linux mint 18 64-bit (native)

**Comment by Charlotteis** [comment]
Can we see your `package.json` please?

**Comment by Charlotteis** [comment]
@ashishkarpe could you update your versions of Node and npm please? they are both very out of date. See if the problem persists after that, and if they do, we can work to solve them :)

**Comment by ashishkarpe** [comment]
# npm -v
4.0.5

**Comment by Charlotteis** [comment]
@ashishkarpe and does the problem still persist after updating node and npm?

**Comment by ashishkarpe** [comment]
nope updating npm didn't but package.json had some issue ...tried  with  https://github.com/prakhar1989/FoodTrucks  updated  code it resolved .............. Thanks a lot

**Comment by legodude17** [comment]
Can this be closed @KenanY?

**Comment by KenanY** [comment]
Closing as abandoned.

**Comment by sterichards** [comment]
Using Ubuntu 16 instead of 14 fixed this for me
