### ISSUE TITLE
Not Able To Create Lithium Repository

### ISSUE THREAD

**Issue by him-varma** [npm/npm#15301]
#### I'm opening this issue because:

 
  - [ ] npm is doing something I don't understand.

#### What's going wrong?

- [] Not able to create lithium sdk repository on my windows system. It is giving me an error that "cannot connect to github.com". I am attaching the log file that is being generated while the repository creation is crashed.

### supporting information:
[10442a7d91587f261e1751c59cc65e03-b4bbaedb2e3a176c301b3890bbf4a2f6890b1b12.zip](https://github.com/npm/npm/files/670454/10442a7d91587f261e1751c59cc65e03-b4bbaedb2e3a176c301b3890bbf4a2f6890b1b12.zip)

**Comment by legodude17** [comment]
Do you have a stable internet connection?

**Comment by him-varma** [comment]
@legodude17 Yes I do have a stable Internet connection. I have been connected to ethernet lan cable at the time of creating a project. For some reason the directory structure creation is not complete.

**Comment by legodude17** [comment]
Then what made you think this is an issue with npm?

**Comment by him-varma** [comment]
the execution is stopping in the middle with am error that cannot connect to github.com. I have attached the log file above.  After generating the error the command prompt suggested me to submit the log file in npm issues and raise an issue over here.

**Comment by legodude17** [comment]
@him-varma I think this would be a problem with:
1. Your internet
2. Your access to github.com
3. git itself
