### ISSUE TITLE
question - how to determine if (npm) link exists for a package

### ISSUE THREAD

**Issue by ORESoftware** [npm/npm#15302]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I currently do not know how to programmatically test whether a link (symlink) exists for an NPM package on my local machine.

Say I am on my development machine, how can I programmatically / (or from the command line), determine if a particular package has a global symlink for it?

In other words, say I am developing a package locally, called "suman". In the suman project, I would do

`npm link`

another project can use the other project via

`npm link suman`

this is all standard stuff.
however, I have a shell script, and I need to determine programmatically whether the link to suman is available or whether I need to install suman locally with `npm install suman`

Is there a way to test to see if the link exists for Suman? Not sure how! Looked at the npm link docs and didn't see it. I feel like this would be a good addition to the docs! Would be happy to add that, if you agree. thanks!

**Comment by legodude17** [comment]
Best guess:
1. `cd a && npm link`
2. `cd .. && cd test && npm link a`
3. Check the output of `npm link a` and then copy that path, minus the `a` part. That is were the symlinks are, so you can check if a symlink called the name of the package you want is in that folder.

**Comment by ORESoftware** [comment]
yeah I think I am looking for clean unkludgy way to do this programmatically, I don't think this suffices unfortunately?

**Comment by legodude17** [comment]
Seems to me you would want to check if `path.join(exec("npm prefix -g"), (process.platform !== 'win32') ? 'lib' : '', 'node_modules', pkg)` exists and is a symlink.
