### ISSUE TITLE
Unable to do npm link if i'm installing from git

### ISSUE THREAD

**Issue by Negan1911** [npm/npm#15300]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Im working with a private git repository and a local copy, i can install from the repository fine just running `npm install <git url>` and i see it correcty under package.json, however, if i try to link my local copy using npm link, it will fail or mark the package as invalid. I guess that is because of the lack of semver on my git depency on package.json

#### How can the CLI team reproduce the problem?

1. Have a local package that depends on a git package.
2. Clone that git package and try to use it with npm link
3. run `npm ls`

### supporting information:

 - `npm -v` prints: `v7.2.0`
 - `node -v` prints: `4.0.5`
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?: OSX
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
I think this is more of a feature request, because that feature just doesn't exist yet.

**Comment by Negan1911** [comment]
I found it like an impediment of using a current feature `npm link` with git type packages... Btw, i found that even if is marked as invalid i can use it anyway, we can close this if we found that is useless. But probably a nice fix will be removing the version checking from npm packages (that is what i guess that cause this issue)
