### ISSUE TITLE
NPM is not listing my published package

### ISSUE THREAD

**Issue by abhisheksoni27** [npm/npm#15307]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I published a package named `feed-parser` to the npm registry. Now, when I use `npm list feed-parser`, the following output is produced.

```bash
npm list feed-parser
feed-parser@1.0.14 /home/abhishek/Desktop/MyNodeModules/feed-parser
`-- (empty)

npm ERR! code 1

```

#### How can the CLI team reproduce the problem?
Type `npm list feed-parser` in a terminal to reproduce the problem.

### supporting information:

 - `npm -v` prints: 3.10.9
 - `node -v` prints: 6.9.2
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux. (Ubuntu 16.10)

**Comment by Charlotteis** [comment]
`npm list` does the following:

```
This command will print to stdout all the versions of packages that are installed, as well as their dependencies, in a tree-structure.
```

So if you want to check it is in the registry, I would do:

`npm view feed-parser` which gives me


```
✨ ~charlotteis~ at 🖥  in ~ ✨
$ npm view feed-parser
 
{ name: 'feed-parser',
  time: 
   { modified: '2016-12-24T06:56:30.034Z',
     created: '2016-12-24T05:26:43.869Z',
     '1.0.7': '2016-12-24T05:26:43.869Z',
     '1.0.8': '2016-12-24T05:28:35.582Z',
     '1.0.9': '2016-12-24T05:35:39.202Z',
     '1.0.10': '2016-12-24T05:48:09.732Z',
     '1.0.11': '2016-12-24T05:53:39.968Z',
     '1.0.12': '2016-12-24T05:57:48.503Z',
     '1.0.13': '2016-12-24T06:08:20.432Z',
     '1.0.14': '2016-12-24T06:27:22.861Z',
     '1.0.15': '2016-12-24T06:50:31.075Z',
     '1.0.16': '2016-12-24T06:56:30.034Z' },
  maintainers: [ 'abhisheksoni27 <abhisheksoni2720@gmail.com>' ],
  'dist-tags': { latest: '1.0.16' },
  description: 'It parses an Atom/RSS feed and de-cluters the article objects to return a simple array of articles.',
  versions: [ '1.0.14', '1.0.15', '1.0.16' ],
  homepage: 'https://github.com/abhisheksoni27/feed-parser#readme',
  repository: 
   { type: 'git',
     url: 'git+https://github.com/abhisheksoni27/feed-parser.git' },
  author: 'Abhishek Soni',
  bugs: { url: 'https://github.com/abhisheksoni27/feed-parser/issues' },
  license: 'MIT',
  readmeFilename: 'README.md',
  keywords: 
   [ 'feed',
     'parser',
     'blog',
     'blogger',
     'wordpress',
     'parse',
     'RSS',
     'Atom',
     'reader',
     'parser',
     'parse' ],
  version: '1.0.16',
  main: 'index.js',
  directories: { example: 'examples' },
  dependencies: { feedparser: '^1.1.5' },
  scripts: { test: 'echo "Error: no test specified" && exit 1' },
  dist: 
   { shasum: '195a2630b98279c84006554cb830ef7a8d0fc3b7',
     tarball: 'https://registry.npmjs.org/feed-parser/-/feed-parser-1.0.16.tgz' }
}
```

Is this more what you were looking for?

Have a great day!

🌸 🌸 🌸 🌸

**Comment by abhisheksoni27** [comment]
I am afraid, no.

The issue is, when I navigate to the package folder on my machine, (I own the package.), and I type `npm list feed-parser`, it outputs:

```
feed-parser@1.0.16 /home/abhishek/Desktop/MyNodeModules/feed-parser
`-- (empty)

npm ERR! code 1
```

**But, when I am not inside the package folder in terminal, `npm list feed-parser` works the way it is supposed to be.**

**Comment by legodude17** [comment]
It isn't working because `npm list feed-parser` is supposed to list all the dependencies on `feed-parser` you have, which doesn't make sense in the `feed-parser` package.

**Comment by abhisheksoni27** [comment]
Ooh. Got it. New to npm. Hope the folks ain't mad. :joy:
