### ISSUE TITLE
Document the restriction that unscoped packages can't depend on scoped packages

### ISSUE THREAD

**Issue by chocolateboy** [npm/npm#15305]
**Keywords**: scoped, unscoped, un-scoped, global, package, module, dependency

When scoped packages were introduced, a restriction was imposed that they can't be depended on by unscoped packages, so e.g. `foo` can't depend on `@bar/baz`.

This is frequently stated (and debated) in the [original ticket](https://github.com/npm/npm/issues/5239) e.g.:

> "Global" modules (ie, unscoped, what we have now) will not be allowed to depend on scoped modules. This is important.
>
> https://github.com/npm/npm/issues/5239#issuecomment-42611044

Although:

> we can re-evaluate that a while down the road, say in a few years or so.
>
> https://github.com/npm/npm/issues/5239#issuecomment-42724715

It is also mentioned (in passing) in a few blog posts announcing the feature e.g.:

> a global package will not be able to depend on a scoped package
>
> http://blog.npmjs.org/post/100099402720/registry-roadmap

> "global" modules cannot depend on "scoped" modules
>
> https://blog.nodejitsu.com/a-summary-of-scoped-modules-in-npm/

 However, I can't find any mention of this restriction in the NPM documentation i.e. it's not mentioned in:

* [npm-install](https://github.com/npm/npm/blob/v4.1.1/doc/cli/npm-install.md)
* [npm-publish](https://github.com/npm/npm/blob/v4.1.1/doc/cli/npm-publish.md)
* [npm-registry](https://github.com/npm/npm/blob/v4.1.1/doc/misc/npm-registry.md)
* [npm-scope](https://github.com/npm/npm/blob/v4.1.1/doc/misc/npm-scope.md)

Does this restriction still apply? If so, it should be documented, along with answers to the following questions:

* What happens if you try to publish an unscoped package which depends on a scoped package?
* What happens if you try to install an unscoped package which depends on a scoped package?

If not, the lifting of this restriction should be documented e.g.:

* When was the restriction removed in the registry?
* Which version of `npm` introduced the restriction?
* Which version of `npm` lifts the restriction?

**Comment by kflorence** [comment]
+1 confused :cold_sweat:

**Comment by legodude17** [comment]
I don't know the answer to this. 😕 @iarna?

**Comment by iarna** [comment]
The `npm` client never had any restrictions of any kind. And neither has the registry. IIRC, that _was_ the original plan, but a year later when they were released on the public registry it'd been decided that wasn't a good idea.

**Comment by chocolateboy** [comment]
@iarna: shouldn't this be announced/documented somewhere? I can't be the only person who has been avoiding scoped packages because of this restriction.

**Comment by iarna** [comment]
@chocolateboy I'm sorry that you never picked up the changes between early initial discussions and actual implementation. They launched in [April of 2015](http://blog.npmjs.org/post/116936804365/solving-npms-hard-problem-naming-packages) so I think that boat has sailed for most folks who may have been initially confused?

But I wouldn't be opposed to a doc PR that said "scoped modules and non-scoped modules are fully interoperable" or something to that effect.
