### ISSUE TITLE
Npm missing boot??

### ISSUE THREAD

**Issue by ImmaBawzz** [npm/npm#15318]
i am new to all this and dont know where to start :-s

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Users\\jverm\\node.exe',
1 verbose cli   'C:\\Users\\jverm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'boot' ]
2 info using npm@3.10.9
3 info using node@v6.9.2
4 verbose config Skipping project config: C:\Users\jverm/.npmrc. (matches userconfig)
5 warn onload-script failed to require onload script npm-autoinit/autoinit
6 warn onload-script Error: Cannot find module 'npm-autoinit/autoinit'
6 warn onload-script     at Function.Module._resolveFilename (module.js:469:15)
6 warn onload-script     at Function.Module._load (module.js:417:25)
6 warn onload-script     at Module.require (module.js:497:17)
6 warn onload-script     at require (internal/module.js:20:19)
6 warn onload-script     at cb (C:\Users\jverm\node_modules\npm\lib\npm.js:199:11)
6 warn onload-script     at C:\Users\jverm\node_modules\npm\lib\npm.js:304:16
6 warn onload-script     at C:\Users\jverm\node_modules\npm\lib\config\core.js:81:7
6 warn onload-script     at Array.forEach (native)
6 warn onload-script     at C:\Users\jverm\node_modules\npm\lib\config\core.js:80:13
6 warn onload-script     at f (C:\Users\jverm\node_modules\npm\node_modules\once\once.js:25:25)
6 warn onload-script  { Error: Cannot find module 'npm-autoinit/autoinit'
6 warn onload-script     at Function.Module._resolveFilename (module.js:469:15)
6 warn onload-script     at Function.Module._load (module.js:417:25)
6 warn onload-script     at Module.require (module.js:497:17)
6 warn onload-script     at require (internal/module.js:20:19)
6 warn onload-script     at cb (C:\Users\jverm\node_modules\npm\lib\npm.js:199:11)
6 warn onload-script     at C:\Users\jverm\node_modules\npm\lib\npm.js:304:16
6 warn onload-script     at C:\Users\jverm\node_modules\npm\lib\config\core.js:81:7
6 warn onload-script     at Array.forEach (native)
6 warn onload-script     at C:\Users\jverm\node_modules\npm\lib\config\core.js:80:13
6 warn onload-script     at f (C:\Users\jverm\node_modules\npm\node_modules\once\once.js:25:25) code: 'MODULE_NOT_FOUND' }
7 verbose stack Error: missing script: boot
7 verbose stack     at run (C:\Users\jverm\node_modules\npm\lib\run-script.js:151:19)
7 verbose stack     at C:\Users\jverm\node_modules\npm\lib\run-script.js:61:5
7 verbose stack     at C:\Users\jverm\node_modules\npm\node_modules\read-package-json\read-json.js:356:5
7 verbose stack     at checkBinReferences_ (C:\Users\jverm\node_modules\npm\node_modules\read-package-json\read-json.js:320:45)
7 verbose stack     at final (C:\Users\jverm\node_modules\npm\node_modules\read-package-json\read-json.js:354:3)
7 verbose stack     at then (C:\Users\jverm\node_modules\npm\node_modules\read-package-json\read-json.js:124:5)
7 verbose stack     at ReadFileContext.<anonymous> (C:\Users\jverm\node_modules\npm\node_modules\read-package-json\read-json.js:295:20)
7 verbose stack     at ReadFileContext.callback (C:\Users\jverm\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16)
7 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:365:13)
8 verbose cwd C:\Users\jverm
9 error Windows_NT 10.0.14393
10 error argv "C:\\Users\\jverm\\node.exe" "C:\\Users\\jverm\\node_modules\\npm\\bin\\npm-cli.js" "run" "boot"
11 error node v6.9.2
12 error npm  v3.10.9
13 error missing script: boot
14 error If you need help, you may report this error at:
14 error     <https://github.com/npm/npm/issues>
15 verbose exit [ 1, true ]

**Comment by legodude17** [comment]
Hello! The error log said you're missing the `boot` script. To use `npm run boot`, you need to put it into the script field in your package.json like:

{
  "script": {
    "boot": "echo hi"
  }
}
See this example for your reference: https://docs.npmjs.com/misc/scripts#examples

Thanks

**Comment by ImmaBawzz** [comment]
my package json looks like this: 
{  "name": "jverm",
  "version": "1.0.0",
  "description": "",
  "main": "Node.js",
  "dependencies": {
    "express": "^4.14.0"
  },
  "devDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}

what do i have to change?

**Comment by legodude17** [comment]
Change
```
"scripts": {
"test": "echo "Error: no test specified" && exit 1"
},
```
to
```
"scripts": {
  "test": "...",
  "boot": "echo 'booting!'"
},
```

**Comment by ImmaBawzz** [comment]
ohmy thank you so much! it worked, thanks for the fast helping :-)

**Comment by legodude17** [comment]
Your welcome! Can you close the issue now?
