### ISSUE TITLE
EISDIR error when `npm publish`ing

### ISSUE THREAD

**Issue by IonicaBizau** [npm/npm#15316]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Cannot `npm publish` my package.

#### How can the CLI team reproduce the problem?
Honestly, I don't know how to reproduce it. It's part of a private project. Simply `npm publish` returns an error like this:

```sh
npm ERR! tar pack Error reading /home/ionicabizau/Downloads/package-name
npm ERR! addLocalDirectory Could not pack /home/ionicabizau/Downloads/package-name to /home/ionicabizau/.npm/package-name/1.0.28/package.tgz
npm ERR! addLocal Could not install /home/ionicabizau/Downloads/package-name
npm ERR! Linux 4.8.0-32-generic
npm ERR! argv "/home/ionicabizau/.nvm/versions/node/v7.0.0/bin/node" "/home/ionicabizau/.nvm/versions/node/v7.0.0/bin/npm" "publish"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code EISDIR
npm ERR! errno -21
npm ERR! syscall read

npm ERR! eisdir EISDIR: illegal operation on a directory, read
npm ERR! eisdir This is most likely not a problem with npm itself
npm ERR! eisdir and is related to npm not being able to find a package.json in
npm ERR! eisdir a package you are trying to install.
```

What I noticed is that the error disappears when I `rm -rf node_modules` and `npm publish` again.

What I can do is to debug the issue and eventually fix it. But maybe you have some better ideas.

### supporting information:

 - `npm -v` prints: 3.10.8
 - `node -v` prints: v7.0.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [x] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [x] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
Is there a `package.json` in `/home/ionicabizau/Downloads/package-name`.

**Comment by IonicaBizau** [comment]
Of course! Again, `npm publish` does work if I remove `node_modules`.

**Comment by legodude17** [comment]
:confused: Maybe try going to `latest`? Honestly I don't know why that would happen.

**Comment by IonicaBizau** [comment]
I did that, cloned from GitHub. Same behavior. If it matters, this behavior was here for almost one year. Just didn't report it.

**Comment by legodude17** [comment]
Anything special about your configuration? Any part of `npm-debug.log` or `package.json` you can share?

**Comment by IonicaBizau** [comment]
@legodude17 Not really... It's just taking npm modules from GitHub and BitBucket. The log file doesn't contain anything relevant.

**Comment by legodude17** [comment]
Try running `npm i -g npm@4.1.1`

**Comment by IonicaBizau** [comment]
Exactly the same problem. :sob:

**Comment by legodude17** [comment]
Try going to the homepage.

**Comment by IonicaBizau** [comment]
@legodude17 What do you mean?

**Comment by IonicaBizau** [comment]
@legodude17 Sorry, I still don't get it. What instructions should I follow?

**Comment by legodude17** [comment]
Go [here](https://github.com/npm/npm#super-easy-install) and then follow the instructions for your OS.

**Comment by IonicaBizau** [comment]
@legodude17 I'm unsure if you are suggesting to install npm from the Git repository. If so, I did that already [like I mentioned above](https://github.com/npm/npm/issues/15316#issuecomment-269229805).

**Comment by legodude17** [comment]
What OS are you on? Just reinstall nodejs, and then an updated version of npm will come with it.

**Comment by IonicaBizau** [comment]
@legodude17 Thanks! Will try that.

I had this problem on two machines, running Ubuntu 16.10 and Ubuntu Server 16.10.

**Comment by bonalupraveenkumar** [comment]
@IonicaBizau  :Having same issue with npm as stated above .any one found  some kinda of solution or workaround.

Thanks

**Comment by IonicaBizau** [comment]
@bonalupraveenkumar I didn't find yet a solution. The workaround I use is that I remove the `node_modules` folder (by running `rm -rf node_modules`), then I `npm publish` and then `npm install` again.

**Comment by zepspaiva** [comment]
Had the same problem until I tried to delete the .git folder. It worked.

**Comment by IonicaBizau** [comment]
@zepspaiva I reopened it as #19650
