### ISSUE TITLE
npm ERR!

### ISSUE THREAD

**Issue by Mrpringles** [npm/npm#15319]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  
#### What's going wrong?
am trying to npm install sqlite3 bcryptjs
#### How can the CLI team reproduce the problem?

idk sry who to reproduce the problem
### supporting information:
SyntaxError: Error parsing /usr/local/lib/node_modules/npm/node_modules/npm-registry-client/node_modules/retry/package.json: Unexpected end of input
    at Object.parse (native)
    at readPackage (module.js:78:52)
    at tryPackage (module.js:88:13)
    at Function.Module._findPath (module.js:151:20)
    at Function.Module._resolveFilename (module.js:334:25)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/attempt.js:1:75)
    at Module._compile (module.js:434:26)
npm ERR! Linux 4.4.34+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "bcryptjs"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! path /usr/local/lib/node_modules/npm/node_modules/npm-registry-client/node_modules/retry/package.json

npm ERR! Error parsing /usr/local/lib/node_modules/npm/node_modules/npm-registry-client/node_modules/retry/package.json: Unexpected end of input
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

 - `npm -v` prints: 2.14.2
 - `node -v` prints:V4.0.0
 - `npm config get registry` prints:
SyntaxError: Error parsing /usr/local/lib/node_modules/npm/node_modules/npm-registry-client/node_modules/retry/package.json: Unexpected end of input
    at Object.parse (native)
    at readPackage (module.js:78:52)
    at tryPackage (module.js:88:13)
    at Function.Module._findPath (module.js:151:20)
    at Function.Module._resolveFilename (module.js:334:25)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/attempt.js:1:75)
    at Module._compile (module.js:434:26)
npm ERR! Linux 4.4.34+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "config" "get" "registry"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! path /usr/local/lib/node_modules/npm/node_modules/npm-registry-client/node_modules/retry/package.json

npm ERR! Error parsing /usr/local/lib/node_modules/npm/node_modules/npm-registry-client/node_modules/retry/package.json: Unexpected end of input
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

 - Windows, OS X/macOS, or Linux?: linux rasbian
 - Network issues: no
   - Geographic location where npm was run: france
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by Charlotteis** [comment]
> SyntaxError: Error parsing /usr/local/lib/node_modules/npm/node_modules/npm-registry-client/node_modules/retry/package.json: Unexpected end of input

Looks like your package.json has some improper formatting. Mind sharing your package.json with me?

Have a great day!

PS. As a side note, your `npm` is very outdated. Please upgrade `npm install -g npm@latest`

**Comment by KenanY** [comment]
Closing as abandoned.
