### ISSUE TITLE
Failed angular2-boilerplate package 

### ISSUE THREAD

**Issue by mulu14** [npm/npm#15311]
I am new to angular2 and I have problem with angular 2 package. I have been trying to fix the problem and I couldn't. I am doing some assignment/project and the teacher provide with package.json with assignment. I install npm  on project dir as well as globally, but I couldn't start local server. I am running the program at window. The problem is here, when I run npm start or npm start -server I got the following error:

npm ERR! node v6.9.2
npm ERR! npm  v2.12.1
npm ERR! code ELIFECYCLE
npm ERR! angular2-boilerplate@1.0.0 start: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-boilerplate@1.0.0 start script 'gulp'.
npm ERR! This is most likely a problem with the angular2-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular2-boilerplate
npm ERR! There is likely additional logging output above.

{
  "name": "angular2-boilerplate",
  "version": "1.0.0",
  "scripts": {
    "start": "gulp",
    "gulp": "gulp",
    "watch": "gulp watch",
    "clean": "gulp clean",
    "typings": "typings",
    "postinstall": "typings install" 
  },
  "license": "MIT",
  "dependencies": {
    "@angular/common":  "2.0.0-rc.1",
    "@angular/compiler":  "2.0.0-rc.1",
    "@angular/core":  "2.0.0-rc.1",
    "@angular/http":  "2.0.0-rc.1",
    "@angular/platform-browser":  "2.0.0-rc.1",
    "@angular/platform-browser-dynamic":  "2.0.0-rc.1",
    "@angular/router":  "2.0.0-rc.1",
    "@angular/router-deprecated":  "2.0.0-rc.1",
    "@angular/upgrade":  "2.0.0-rc.1",
    "systemjs": "0.19.27",
    "es6-shim": "^0.35.0",
    "reflect-metadata": "^0.1.3",
    "rxjs": "5.0.0-beta.6",
    "zone.js": "^0.6.12"
  },
  "devDependencies": {
    "babel-core": "^6.0.15",
    "babel-preset-es2015": "^6.0.15",
    "browser-sync": "^2.10.1",
    "del": "^2.0.0",
    "gulp": "^3.9.0",
    "gulp-autoprefixer": "^3.1.0",
    "gulp-concat": "^2.6.0",
    "gulp-concat-css": "^2.2.0",
    "gulp-inline-ng2-template": "^1.1.2",
    "gulp-minify-css": "^1.2.1",
    "gulp-typescript": "^2.10.0",
    "gulp-watch": "^4.3.5",
    "stream-series": "^0.1.1",
    "typescript": "^1.7.3",
    "typings":"^0.6.8",
    "systemjs-builder": "^0.15.15"
  }
}

#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by Charlotteis** [comment]
Could you post the full log?

Have a happy winter break, if you're having one! ⛄️ 🌸

**Comment by mulu14** [comment]
Hej @Charlotteis sorry for late replay! The problem was computer path problem. I used school computer and they have different path setting and  so, i run on my own computer and it works now. Winter break?  huum, i had some project to finish before Spring semester

**Comment by Charlotteis** [comment]
Ok!

Looks like this issue can be closed then. Glad it's all working :)
