### ISSUE TITLE
" npm install -g ionic "  is not working ?

### ISSUE THREAD

**Issue by DILEEP-YADAV** [npm/npm#15317]
![capturew](https://cloud.githubusercontent.com/assets/8583769/21484553/66159972-cbba-11e6-90e7-2a6a98d69a95.PNG)

**Comment by Charlotteis** [comment]
Duplicate of #14626.

Try running the installation again after updating the to the latest npm with

```
npm install -g npm@latest
```

Hope this helps! 🌸

**Comment by DILEEP-YADAV** [comment]
@Charlotteis  , Thank you very much ! it 's working fine.

**Comment by DILEEP-YADAV** [comment]
any one else , help me!

**Comment by Charlotteis** [comment]
@DILEEP-YADAV what error do you get after updating to the latest version of npm?

**Comment by DILEEP-YADAV** [comment]
Npm updated without error. But I am getting error as above screen shot . When I running following command. "npm install -g ionic ".   But It's working perfectly with Windows 7 not Windows 10.

**Comment by naumanit** [comment]
For me this worked:
update the latest npm
npm install -g npm@latest
$ npm uninstall ionic -g
$ npm uninstall cordova -g
$ npm cache clean
$ npm install cordova -g
$ npm install ionic -g

**Comment by DILEEP-YADAV** [comment]
@naumanit  & @Charlotteis Thank you very much for participants.
issue resolved as per instructions.
