### ISSUE TITLE
Npm install issue

### ISSUE THREAD

**Issue by Nebojsaa** [npm/npm#15325]
#### I'm opening this issue because:
  - [ ] npm is doing something I don't understand.

#### How can the CLI team reproduce the problem?

│ └── walkdir@0.0.11
└── jquery@3.1.1

npm WARN jasmine-jquery@1.3.2 No license field.
npm ERR! Linux 3.10.0-229.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! path ../acorn/bin/acorn
npm ERR! code EPROTO
npm ERR! errno -71
npm ERR! syscall symlink

npm ERR! EPROTO: protocol error, symlink '../acorn/bin/acorn' -> '/srv/www/cemcloud2/node_modules/.bin/acorn'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /srv/www/cemcloud2/npm-debug.log

So what happens is that it's all installed on the system, but it has some errors. I don't understand what those errors mean. 

Just so that you know, I have both Global and local in my environment installation of the Jasmine, although I think this error doesn't have anything to do with Jasmine installation.

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@Nebojsaa Have you tried using the `--no-bin-links` flag?
