### ISSUE TITLE
npm start can't start angular quickstart project

### ISSUE THREAD

**Issue by Lanova** [npm/npm#15320]
#### I'm opening this issue because:

  - [ ] npm is producing an incorrect start.
 
#### What's going wrong?
After installing npm in a folder with project "quick start" wich was dowloud from Angular2 site, I try to start npm and nmp gives me such errors

olga@thinkpad:~/quickstart$ npm start
npm ERR! Linux 4.4.0-57-generic
npm ERR! argv "/home/olga/.local/share/umake/nodejs/nodejs-lang/bin/node" "/home/olga/.local/share/umake/nodejs/nodejs-lang/bin/npm" "start"
npm ERR! node v7.3.0
npm ERR! npm  v3.10.10

npm ERR! missing script: start
npm ERR! 

### supporting information:

 - `npm -v` prints:3.10.10
 - `node -v` prints:7.3.0
 - `npm config get registry` prints:npm config get registry
 - Windows, OS X/macOS, or Linux?: Linux
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   
 - Container:

   - [ ] I develop using  Linux.

**Comment by Lanova** [comment]
Sorry guy< I found my mistake

**Comment by bmovva** [comment]
what is the mistake ??

**Comment by KenanY** [comment]
@bmovva Define a `"start"` script in your `package.json` before running `npm start` :)
