### ISSUE TITLE
Error install express.io

### ISSUE THREAD

**Issue by giancpt** [npm/npm#15328]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ x ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
trying install express.io
#### How can the CLI team reproduce the problem?
0 info it worked if it ends with ok
1 verbose cli [ '/home/administrador/node-v6.9.2-linux-x64/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   'express.io' ]
2 info using npm@3.10.9
3 info using node@v6.9.2
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData express.io
8 silly fetchDirectoryPackageData express.io
9 silly install normalizeTree
10 silly loadCurrentTree Finishing
11 silly loadIdealTree Starting
12 silly install loadIdealTree
13 silly cloneCurrentTree Starting
14 silly install cloneCurrentTreeToIdealTree
15 silly cloneCurrentTree Finishing
16 silly loadShrinkwrap Starting
17 silly install loadShrinkwrap
18 silly loadShrinkwrap Finishing
19 silly loadAllDepsIntoIdealTree Starting
20 silly install loadAllDepsIntoIdealTree
21 silly rollbackFailedOptional Starting
22 silly rollbackFailedOptional Finishing
23 silly runTopLevelLifecycles Finishing
24 silly install printInstalled
25 verbose stack Error: Refusing to install express.io as a dependency of itself
25 verbose stack     at checkSelf (/home/administrador/node-v6.9.2-linux-x64/lib/node_modules/npm/lib/install/validate-args.js:53:14)
25 verbose stack     at Array.<anonymous> (/home/administrador/node-v6.9.2-linux-x64/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
25 verbose stack     at LOOP (/home/administrador/node-v6.9.2-linux-x64/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
25 verbose stack     at chain (/home/administrador/node-v6.9.2-linux-x64/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
25 verbose stack     at /home/administrador/node-v6.9.2-linux-x64/lib/node_modules/npm/lib/install/validate-args.js:16:5
25 verbose stack     at /home/administrador/node-v6.9.2-linux-x64/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
25 verbose stack     at Array.forEach (native)
25 verbose stack     at /home/administrador/node-v6.9.2-linux-x64/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
25 verbose stack     at Array.forEach (native)
25 verbose stack     at asyncMap (/home/administrador/node-v6.9.2-linux-x64/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
26 verbose cwd /var/www/gian/tlmk/trunk/tlmkv8/public/js/discador
27 error Linux 3.13.0-105-generic
28 error argv "/home/administrador/node-v6.9.2-linux-x64/bin/node" "/usr/bin/npm" "install" "express.io"
29 error node v6.9.2
30 error npm  v3.10.9
31 error code ENOSELF
32 error Refusing to install express.io as a dependency of itself
33 error If you need help, you may report this error at:
33 error     <https://github.com/npm/npm/issues>
34 verbose exit [ 1, true ]

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@giancpt Make sure the `"name"` property in your `package.json` is not set to `"express.io"`. Make it unique!
