### ISSUE TITLE
cb() never called

### ISSUE THREAD

**Issue by bboysathish** [npm/npm#15327]
#### I'm opening this issue because:

  - [x] npm is crashing.

#### What's going wrong?
 npm install is not working throws "cb() never called"

i have narrowed it down to a module npm install css-loader is throwing that error, other modules are installing good.

Note: i have tried all the solutions which was proposed on the previous bug reports.

#### How can the CLI team reproduce the problem?
No idea. i can't give the details of my package.json as it is private repo.

### supporting information:

 - `npm -v` prints: 3.10.7
 - `node -v` prints: 5.9.0
 - `npm config get registry` prints: 
 - Windows, OS X/macOS, or Linux?: Linux
 - Network issues: No
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.

**Comment by KenanY** [comment]
@bboysathish Does this also occur with the latest version of `npm`?

**Comment by bboysathish** [comment]
@KenanY This issue occurs in our build machine, i dont have access to update npm there..

**Comment by KenanY** [comment]
@bboysathish But if there's a chance that this has been fixed already, I think it's worth a shot to try and get that version updated :)

**Comment by bboysathish** [comment]
@KenanY Thanks, But if you look into the old issues, you verify that it is not fixed, at some time people stopped following the issues and left closed by the following answers

1. Clean npm cache with `npm cache clean`.
2. Remove the `.npm` folder manually and try installing it once again. 
3. Else try using this module `npm-retry-install`.
4. Else upgrade you npm to 3+ version
5. Upgrade node to 0.10 latest version. 

I think there is no definite answer for this.

**Comment by bboysathish** [comment]
Is there a log or something i can able to see why it is failing ?

**Comment by KenanY** [comment]
@bboysathish Yeah, I've seen the older issues. Some of them have a comment by me explaining how this error message is really generic and almost always indicates a bug in `npm` itself. This is why there will never be a definite answer to this specific error. Bugs are introduced and fixed with every update so it's important to know whether or not this bug has already been fixed or not, and this can be checked by updating `npm`.

If there's no `npm-debug.log` file in your current directory after this error occurs, then unfortunately there's no other log you can look for. Usually this error doesn't produce a well-formed log anyways.

**Comment by bboysathish** [comment]
@KenanY Is there way i can update npm without root privilege ?

**Comment by legodude17** [comment]
@bboysathish You can install `npm` somewhere else, and then add it to your `$PATH`.

**Comment by bboysathish** [comment]
@legodude17  @KenanY  I am working on common build machine system, which had been used by many teams around the world, I don't have access and can't upgrade it. Is there a way I can overcome this issue. If there is a npm release and node.js release changelog says that it has been fixed then I can vouch for that version to upgrade.

**Comment by bboysathish** [comment]
Because we are seeing this error for other teams too.

**Comment by bboysathish** [comment]
@legodude17 @KenanY Refer https://github.com/validator/validator/issues/441 he is using npm 4 and same Node.js 5.9.0. So I think upgrading npm won't solve the problem.

**Comment by Arttse** [comment]
This error occurs in Node.js `5.9.0` and `5.9.1`. The only obvious solution is to upgrade to Node.js `5.10.0` and newer, which it works.

**Comment by legodude17** [comment]
You could also try Node.js v7...
