### ISSUE TITLE
npm search&npm install Err

### ISSUE THREAD

**Issue by kaedelulu** [npm/npm#15321]
#### I'm opening this issue because:
npm search & npm install didn't work.
#### What's going wrong?
I tried to type"npm search" and "npm install easyimage", but came out a lot of error.
#### How can the CLI team reproduce the problem?

https://gist.githubusercontent.com/kaedelulu/ac827e1a427db455a587f1bcae62fa7a/raw/8e0413b53ca55775bd187f89713879c2ed621a54/nom-debug.log

### supporting information:
npm search
npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "search"
npm ERR! node v7.3.0
npm ERR! npm  v3.10.10

npm ERR! search must be called with arguments
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "search"
npm ERR! node v7.3.0
npm ERR! npm  v3.10.10
npm ERR! path npm-debug.log.2504761118
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall open

npm ERR! Error: EACCES: permission denied, open 'npm-debug.log.2504761118'
npm ERR!  { Error: EACCES: permission denied, open 'npm-debug.log.2504761118'
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'open',
npm ERR!   path: 'npm-debug.log.2504761118' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/bin/npm-debug.log

npm install easyimage
npm WARN checkPermissions Missing write access to /usr/local/bin
/usr/local/bin
└─┬ easyimage@2.1.0 
  ├── colors@1.1.2 
  ├─┬ mkdirp@0.5.1 
  │ └── minimist@0.0.8 
  └── q@1.4.1 

npm WARN enoent ENOENT: no such file or directory, open '/usr/local/bin/package.json'
npm WARN bin No description
npm WARN bin No repository field.
npm WARN bin No README data
npm WARN bin No license field.
npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "easyimage"
npm ERR! node v7.3.0
npm ERR! npm  v3.10.10
npm ERR! path /usr/local/bin
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/usr/local/bin'
npm ERR!  { Error: EACCES: permission denied, access '/usr/local/bin'
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/bin' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "easyimage"
npm ERR! node v7.3.0
npm ERR! npm  v3.10.10
npm ERR! path npm-debug.log.1404173565
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall open

npm ERR! Error: EACCES: permission denied, open 'npm-debug.log.1404173565'
npm ERR!  { Error: EACCES: permission denied, open 'npm-debug.log.1404173565'
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'open',
npm ERR!   path: 'npm-debug.log.1404173565' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/bin/npm-debug.log

**Comment by KenanY** [comment]
@kaedelulu The reason for the `npm search` error is in the error message itself:

```
npm ERR! search must be called with arguments
```

But also note that `npm search` is broken in `npm@<4` so make sure to update before trying to use it.

The `EACCES` errors are caused by the fact that you are running these commands from within a directory which you don't have permission to access. Generally `npm` expects to be ran from within a directory you own.
