### ISSUE TITLE
nmp ERR! addLocal could not install...

### ISSUE THREAD

**Issue by ghost** [npm/npm#15329]
#### I'm opening this issue because:
i could not install stencil cli.

here are the prerequisites I installed:
Git-2.11.0-64-bit
python-2.7.13.amd64
node-v4.6.1-x64 (I've also tried these versions: node-v5.0.0-x64 / node-v4.4.5-x64)

Everytime i type in 'npm install -g bigcommerce/stencil-cli' i get the error below:
----
npm ERR! addLocal Could not install C:\Users\fr3503\AppData\Local\Temp\npm-6892-e2a9070a\git-cache-d981ea50c965a053a0f07ea4187c7615\27015ee68e5e1209a6d1f236c9720e070696b072
npm ERR! addLocal Could not install C:\Users\fr3503\AppData\Local\Temp\npm-6892-e2a9070a\git-cache-9231a67de001d832331809078e5bd3b3\27015ee68e5e1209a6d1f236c9720e070696b072
npm ERR! git clone --template=C:\Users\fr3503\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:bigcommerce/stencil-cli.git C:\Users\fr3503\AppData\Roaming\npm-cache\_git-remotes\git-github-com-bigcommerce-stencil-cli-git-849bbe6f08dccdd7d2c4fcd920859ca9: Cloning into bare repository 'C:\Users\fr3503\AppData\Roaming\npm-cache\_git-remotes\git-github-com-bigcommerce-stencil-cli-git-849bbe6f08dccdd7d2c4fcd920859ca9'...
npm ERR! git clone --template=C:\Users\fr3503\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:bigcommerce/stencil-cli.git C:\Users\fr3503\AppData\Roaming\npm-cache\_git-remotes\git-github-com-bigcommerce-stencil-cli-git-849bbe6f08dccdd7d2c4fcd920859ca9: Permission denied (publickey).
npm ERR! git clone --template=C:\Users\fr3503\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:bigcommerce/stencil-cli.git C:\Users\fr3503\AppData\Roaming\npm-cache\_git-remotes\git-github-com-bigcommerce-stencil-cli-git-849bbe6f08dccdd7d2c4fcd920859ca9: fatal: Could not read from remote repository.
npm ERR! git clone --template=C:\Users\fr3503\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:bigcommerce/stencil-cli.git C:\Users\fr3503\AppData\Roaming\npm-cache\_git-remotes\git-github-com-bigcommerce-stencil-cli-git-849bbe6f08dccdd7d2c4fcd920859ca9:
npm ERR! git clone --template=C:\Users\fr3503\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:bigcommerce/stencil-cli.git C:\Users\fr3503\AppData\Roaming\npm-cache\_git-remotes\git-github-com-bigcommerce-stencil-cli-git-849bbe6f08dccdd7d2c4fcd920859ca9: Please make sure you have the correct access rights
npm ERR! git clone --template=C:\Users\fr3503\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:bigcommerce/stencil-cli.git C:\Users\fr3503\AppData\Roaming\npm-cache\_git-remotes\git-github-com-bigcommerce-stencil-cli-git-849bbe6f08dccdd7d2c4fcd920859ca9: and the repository exists.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "bigcommerce/stencil-cli"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\fr3503\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:bigcommerce/stencil-cli.git C:\Users\fr3503\AppData\Roaming\npm-cache\_git-remotes\git-github-com-bigcommerce-stencil-cli-git-849bbe6f08dccdd7d2c4fcd920859ca9
npm ERR! Cloning into bare repository 'C:\Users\fr3503\AppData\Roaming\npm-cache\_git-remotes\git-github-com-bigcommerce-stencil-cli-git-849bbe6f08dccdd7d2c4fcd920859ca9'...
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\fr3503\npm-debug.log
----
thanks!

**Comment by ransomcarroll** [comment]
Try clearing your npm cache.

$ npm cache clean

**Comment by john-tuck** [comment]
It looks like you might have some SSH auth issues. Are you able to connect to github via SSH?

https://help.github.com/articles/testing-your-ssh-connection/
