### ISSUE TITLE
Unable to install mean js generator

### ISSUE THREAD

**Issue by vinodhram3** [npm/npm#15322]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'generator-meanjs:express-test' ]
2 info using npm@4.0.3
3 info using node@v7.2.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData generator-meanjs:express-test
8 silly fetchPackageMetaData Error: Unsupported URL Type: generator-meanjs:express-test
8 silly fetchPackageMetaData     at parseUrl (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:186:13)
8 silly fetchPackageMetaData     at npa (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:79:12)
8 silly fetchPackageMetaData     at module.exports (/usr/local/lib/node_modules/npm/node_modules/realize-package-specifier/index.js:12:15)
8 silly fetchPackageMetaData     at fetchPackageMetadata (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:54:12)
8 silly fetchPackageMetaData     at fetchMetadataWithVersion (/usr/local/lib/node_modules/npm/lib/install/deps.js:228:14)
8 silly fetchPackageMetaData     at /usr/local/lib/node_modules/npm/lib/install/deps.js:241:16
8 silly fetchPackageMetaData     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
8 silly fetchPackageMetaData     at Array.forEach (native)
8 silly fetchPackageMetaData     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
8 silly fetchPackageMetaData     at Array.forEach (native)
8 silly fetchPackageMetaData  error for generator-meanjs:express-test Error: Unsupported URL Type: generator-meanjs:express-test
8 silly fetchPackageMetaData     at parseUrl (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:186:13)
8 silly fetchPackageMetaData     at npa (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:79:12)
8 silly fetchPackageMetaData     at module.exports (/usr/local/lib/node_modules/npm/node_modules/realize-package-specifier/index.js:12:15)
8 silly fetchPackageMetaData     at fetchPackageMetadata (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:54:12)
8 silly fetchPackageMetaData     at fetchMetadataWithVersion (/usr/local/lib/node_modules/npm/lib/install/deps.js:228:14)
8 silly fetchPackageMetaData     at /usr/local/lib/node_modules/npm/lib/install/deps.js:241:16
8 silly fetchPackageMetaData     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
8 silly fetchPackageMetaData     at Array.forEach (native)
8 silly fetchPackageMetaData     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
8 silly fetchPackageMetaData     at Array.forEach (native)
9 silly rollbackFailedOptional Starting
10 silly rollbackFailedOptional Finishing
11 silly runTopLevelLifecycles Finishing
12 silly install printInstalled
13 verbose stack Error: Unsupported URL Type: generator-meanjs:express-test
13 verbose stack     at parseUrl (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:186:13)
13 verbose stack     at npa (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:79:12)
13 verbose stack     at module.exports (/usr/local/lib/node_modules/npm/node_modules/realize-package-specifier/index.js:12:15)
13 verbose stack     at fetchPackageMetadata (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:54:12)
13 verbose stack     at fetchMetadataWithVersion (/usr/local/lib/node_modules/npm/lib/install/deps.js:228:14)
13 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/deps.js:241:16
13 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
13 verbose stack     at Array.forEach (native)
13 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
13 verbose stack     at Array.forEach (native)
14 verbose cwd /home/vinodhram.molli/Desktop/mean
15 error Linux 4.4.0-38-generic
16 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "generator-meanjs:express-test"
17 error node v7.2.1
18 error npm  v4.0.3
19 error Unsupported URL Type: generator-meanjs:express-test
20 error If you need help, you may report this error at:
20 error     <https://github.com/npm/npm/issues>
21 verbose exit [ 1, true ]

**Comment by legodude17** [comment]
Did you mean just `npm i -g generator-meanjs`?
