### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mdb5** [npm/npm#15331]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

Installing “rhino-python@0.8.2” failed.Hide output…

npm WARN addRemoteGit git+https://git@github.com/vuejs/vue.git#b3c529992e322daa4c3a486137730078edd22ffd resetting remote /Users/matthewblake/.atom/.apm/_git-remotes/git-https-git-github-com-vuejs-vue-git-b3c529992e322daa4c3a486137730078edd22ffd-f14fd881 because of error: Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.
npm ERR! git clone --template=/Users/matthewblake/.atom/.apm/_git-remotes/_templates --mirror https://git@github.com/vuejs/vue.git /Users/matthewblake/.atom/.apm/_git-remotes/git-https-git-github-com-vuejs-vue-git-b3c529992e322daa4c3a486137730078edd22ffd-f14fd881: Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.
npm ERR! Darwin 16.3.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/matthewblake/.atom/.apm/.apmrc" "--userconfig" "/Users/matthewblake/.atom/.apmrc" "install" "/private/var/folders/fb/07y21p2n09s191xb3rqqp4br0000gn/T/d-1161127-1006-1r9tklu/package.tgz" "--runtime=electron" "--target=1.3.13" "--arch=x64" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code 69

npm ERR! Command failed: git clone --template=/Users/matthewblake/.atom/.apm/_git-remotes/_templates --mirror https://git@github.com/vuejs/vue.git /Users/matthewblake/.atom/.apm/_git-remotes/git-https-git-github-com-vuejs-vue-git-b3c529992e322daa4c3a486137730078edd22ffd-f14fd881
npm ERR! 
npm ERR! 
npm ERR! Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.
npm ERR! 
npm ERR! 
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/fb/07y21p2n09s191xb3rqqp4br0000gn/T/apm-install-dir-1161127-1006-1fnzt92/npm-debug.log

**Comment by legodude17** [comment]
Try running the command with `sudo`
