### ISSUE TITLE
everything that has to do with npm doesnt work.

### ISSUE THREAD

**Issue by MLGSeller** [npm/npm#15339]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [x] npm is doing something I don't understand.

#### What's going wrong?
Whenever i am trying to install a package it just sits at
 [    ..............] - loadRequestedDeps: sill install loadAllDepsIntoIdealTree
#### How can the CLI team reproduce the problem?
I dont know

I dont get a log
### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: WIndows
 - Container:
   - [ ] I develop using Vagrant on Windows.

**Comment by legodude17** [comment]
What command did run? What versions of `npm` and `node` are using?
