### ISSUE TITLE
Problems installing node_modules

### ISSUE THREAD

**Issue by dapoma** [npm/npm#15338]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

When I try to install a node_module on a Linux Yocto by using PuTTY (installed on a Windows 7 Ultimate) I have problems. I've been trying to fix the problem and it seems a proxy error, but I have no proxy configured. 'npm config get proxy' returns null. Attached the npm-debug.log:
 
    https://gist.github.com/dapoma/f4b9c58416ba3b0cbec158e212e6534a

I'm new on GitHub so sorry if I did something wrong opening this issue. Thanks in advance for you help.

**Comment by legodude17** [comment]
Hows your internet connection?

**Comment by dapoma** [comment]
I've seen that I don't have Internet connection. I'm trying to share the wireless connection of my laptop with the Galileo Gen2 because I want to keep PuTTY as SSH. I'm configuring something wrong. I'll check it. Thanks
