### ISSUE TITLE
npm install issue in tooling setup

### ISSUE THREAD

**Issue by silicona** [npm/npm#15336]
#### I'm opening this issue because:

  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.

#### What's going wrong?

npm install doesnt load all bootstrap features.

#### How can the CLI team reproduce the problem?
I had follow the tooling setup steps. At npm install in bootstrap root, it crashed.

gist:
https://gist.github.com/silicona/85f5c8ce0f1d52c9deaad795886a64ca

### supporting information:

 - `npm -v` prints: 3.5.2
 - `node -v` prints:4.2.6
 - `npm config get registry` prints:https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux
 - Network issues:
   - Geographic location where npm was run: Spain
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by Charlotteis** [comment]
Hi @silicona!

Could you upgrade npm by doing:

```
npm install -g npm@latest
```

and try your installation again?

Thanks! 🌸

**Comment by KenanY** [comment]
Closing as abandoned.
