### ISSUE TITLE
403 on npm deprecate 

### ISSUE THREAD

**Issue by gordonwoodhull** [npm/npm#15330]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I'm pretty sure this is a duplicate of #13417 but support asked me to open an issue.

I'm attempting to deprecate an erroneous version of dc.js (`dc` package). But I get a 403 (Forbidden) error. I'm the owner of this repo and I'm able to publish versions okay.

The version was published with incomplete understanding of how npm works and I'm trying to steer people toward the 2.0 version, or to use GitHub branch tags instead.

#### How can the CLI team reproduce the problem?
I have tried variations on 

```
npm deprecate dc@2.1.0-dev 'dev branch is invalid - use #develop instead'
```

Presumably anyone else with permissions would also get the same error.

Here is the log: https://gist.github.com/gordonwoodhull/ceb97fcea0f3f92f82ba4668d94ed767

### supporting information:

 - `npm -v` prints: 4.0.3
 - `node -v` prints: v6.9.2
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS Sierra
 - Network issues: N/A
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
I honestly don't know what the error is, I have never seen that error message before. Maybe @soldair can help?

**Comment by sethvincent** [comment]
I just encountered the same error message with a different package.

It happened on a package where I was added as an owner, but was not the original owner.

It seems I can deprecate other packages (where I was the original owner) without issue.

**Comment by jesstelford** [comment]
I received this same error today, when trying to deprecate `zxing`.

I was able to successfully deprecate the package with `<packageName>@"*"` (deprecating all versions - which is what I wanted).

**Comment by soldair** [comment]
hey folks. sorry you are running into this. if you could email support@npmjs.org with the info we will get these sorted out and probably find the bug in the mean time =)

because this is a registry issue im closing it here. 
for anyone looking to report other registry issues feel free to use the registry issue tracker https://github.com/npm/registry/issues
