### ISSUE TITLE
S7 node add error

### ISSUE THREAD

**Issue by ddavidadams** [npm/npm#15334]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [x]npm-debug.pdf](https://github.com/npm/npm/files/675764/npm-debug.pdf)
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
Please check your internet connection.

**Comment by ddavidadams** [comment]
Joshua,

After some research I discovered my Galileo had no gateway address in 
it's network settings. Thanks for the response.

David Adams
334.531.1245
ddavidadams@elmore.rr.com
