### ISSUE TITLE
Get the list of npm packages when you change the npm's default directory

### ISSUE THREAD

**Issue by igorvisi** [npm/npm#15341]
I have changed npm's default directory to another directory : ~/.npm-packages like mentioned here [https://docs.npmjs.com/getting-started/fixing-npm-permissions](docs.npmjs.com) and add the the path to my ~/.zshrc ! But npm ls still show the previous path /usr

**Comment by legodude17** [comment]
What do you mean `npm ls`? Don't you mean `npm ls -g`?

**Comment by igorvisi** [comment]
thanks @legodude17  . I understand now .
