### ISSUE TITLE
typescript code reloading performance degrades over time

### ISSUE THREAD

**Issue by PogoMips** [npm/npm#15345]
Hi, I don't know if this is the right place for this question (I'm not sure if it is a lite-server issue or a npm issue)

I follow the Tour of Heroes AngularJS tutorial and noticed that code changes in my typescript files take very long to refresh in the browser. The longer the program runs (via npm start) the slower it gets. 

Once I start it, it takes around 5 seconds for a code change to be visible in the browser. After two hours of programming it takes around one minute to reload code changes. (this is still the tutorial project with a hand full of files). If I stop the server and start it again I'm back to the 5 seconds. However, I don't want to do that every hour or so.

My system:
- Windows 8.1 64 bit
  - 16GB RAM, Intel i7, 4x 2.5GHz
- NodeJs 7.3.0
- npm 3.10.10
- lite-server 2.2.2

I have googled around and tried out some of the suggested solutions:

- Running cmd as administrator
- Disabling all anti-virus applications
- Using a SSD (already there)

but nothing worked so far. 
I also completely uninstalled nodejs and tried the latest LTS but with the same results.

Here is how the log looks like after around 30 minutes of running lite-server. It takes around 20 seconds already to reflect a single line code change in the browser.

[log.txt](https://github.com/npm/npm/files/677436/log.txt)

**Comment by legodude17** [comment]
I don't think this would be a problem with `npm`, but more with `lite-server` itself.

**Comment by PogoMips** [comment]
I'm not sure as I feel like npm is very slow in general on my machine. npm --version takes around 5 seconds to return the version number. this seems awfully slow.

**Comment by KenanY** [comment]
If `npm` is the issue here then I suggest editing your original post to only revolve around `npm` itself rather than typescript or lite-server.

**Comment by PogoMips** [comment]
Hi, of course. As I have never worked with npm before, can you suggest me some analytics I could run to narrow down the problem and provide more useful error details? As of now, I have only used it with typescript/lite-server.

**Comment by KenanY** [comment]
Current tracking ticket for `npm` slowness is https://github.com/npm/npm/issues/15361. There's a comment from core member iarna there on what a prospective contributor could do to help out with regards to benchmarking and whatnot. Gonna close this in favor of that issue.
