### ISSUE TITLE
npm install -g  either error nor result

### ISSUE THREAD

**Issue by GirishBhat** [npm/npm#15340]
@ashleygwilliams @bcoe @ceejbot @nexdrew @zkat @timoxley 
$ npm install -g

without any error or success, it keeps on running

![error](https://cloud.githubusercontent.com/assets/8476888/21535448/a46c9b04-cd3a-11e6-85d7-8c43d4340a54.PNG)

Please let me know what could be the problem.

**Comment by yeukfei02** [comment]
i guess u are in windows, did u set environment variable of ``node``?

**Comment by yeukfei02** [comment]
and u should try this ``npm install -g <your-package>``

**Comment by GirishBhat** [comment]
@yeukfei02 
Yes, I am in windows and set environment variable->System variable ->Path :C:\Program Files\nodejs
but still no luck..

**Comment by GirishBhat** [comment]
@yeukfei02 @iarna 
And also **npm install -g cordova ionic bower gulp** has same issue as above one.

**Comment by legodude17** [comment]
What does `npm install -g -ddd cordova` print?

**Comment by legodude17** [comment]
Do you have a spotty internet connection or firewall or proxy?

**Comment by GirishBhat** [comment]
No proxies detected,no firewall set no spotty internet connection

**Comment by GirishBhat** [comment]
Have set .npm-packages in c;/users/abc/.npm-packages and also have set **prefix=~/.npm-packages** in .npmrc file and in .bashrc file set the PATH **c/users/abc/.npm-package** 

I really don't know where I am going wrong

**Comment by legodude17** [comment]
Try just `npm i -ddd cordova`

**Comment by GirishBhat** [comment]
@legodude17 

Tried ,but same result

$ npm i -ddd cordova
npm info it worked if it ends with ok
npm verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'i',
npm verb cli   '-ddd',
npm verb cli   'cordova' ]
npm info using npm@3.10.9
npm info using node@v6.9.2
npm sill loadCurrentTree Starting
npm sill install loadCurrentTree
npm sill install readLocalPackageData
npm sill fetchPackageMetaData cordova
npm sill fetchNamedPackageData cordova
npm sill mapToRegistry name cordova
npm sill mapToRegistry using default registry
npm sill mapToRegistry registry https://registry.npmjs.org/
npm sill mapToRegistry data Result {
npm sill mapToRegistry   raw: 'cordova',
npm sill mapToRegistry   scope: null,
npm sill mapToRegistry   escapedName: 'cordova',
npm sill mapToRegistry   name: 'cordova',
npm sill mapToRegistry   rawSpec: '',
npm sill mapToRegistry   spec: 'latest',
npm sill mapToRegistry   type: 'tag' }
npm sill mapToRegistry uri https://registry.npmjs.org/cordova
npm verb request uri https://registry.npmjs.org/cordova
npm verb request no auth needed
npm info attempt registry request try #1 at 10:52:14 AM
npm verb request id e02d02d46e8c0e62
npm http request GET https://registry.npmjs.org/cordova
npm http 200 https://registry.npmjs.org/cordova
npm verb headers { server: 'nginx/1.10.1',
npm verb headers   'content-type': 'application/json',
npm verb headers   'last-modified': 'Sat, 24 Dec 2016 13:36:59 GMT',
npm verb headers   etag: 'W/"585e79fb-1046fb"',
npm verb headers   'content-encoding': 'gzip',
npm verb headers   'cache-control': 'max-age=300',
npm verb headers   'content-length': '39697',
npm verb headers   'accept-ranges': 'bytes',
npm verb headers   date: 'Fri, 30 Dec 2016 16:52:14 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   age: '15',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-ord1731-ORD',
npm verb headers   'x-cache': 'HIT',
npm verb headers   'x-cache-hits': '1',
npm verb headers   'x-timer': 'S1483116734.316244,VS0,VE0',
npm verb headers   vary: 'Accept-Encoding' }
npm sill get cb [ 200,
npm sill get   { server: 'nginx/1.10.1',
npm sill get     'content-type': 'application/json',
npm sill get     'last-modified': 'Sat, 24 Dec 2016 13:36:59 GMT',
npm sill get     etag: 'W/"585e79fb-1046fb"',
npm sill get     'content-encoding': 'gzip',
npm sill get     'cache-control': 'max-age=300',
npm sill get     'content-length': '39697',
npm sill get     'accept-ranges': 'bytes',
npm sill get     date: 'Fri, 30 Dec 2016 16:52:14 GMT',
npm sill get     via: '1.1 varnish',
npm sill get     age: '15',
npm sill get     connection: 'keep-alive',
npm sill get     'x-served-by': 'cache-ord1731-ORD',
npm sill get     'x-cache': 'HIT',
npm sill get     'x-cache-hits': '1',
npm sill get     'x-timer': 'S1483116734.316244,VS0,VE0',
npm sill get     vary: 'Accept-Encoding' } ]
npm verb get saving cordova to C:\Users\bgh40689\AppData\Roaming\npm-cache\regis                                                                                                                try.npmjs.org\cordova\.cache.json
npm verb correctMkdir C:\Users\bgh40689\AppData\Roaming\npm-cache correctMkdir n                                                                                                                ot in flight; initializing
npm verb makeDirectory C:\Users\bgh40689\AppData\Roaming\npm-cache creation not                                                                                                                 in flight; initializing
npm verb makeCacheDir UID & GID are irrelevant on win32
npm sill install normalizeTree
npm sill loadCurrentTree Finishing
npm sill loadIdealTree Starting
npm sill install loadIdealTree
npm sill cloneCurrentTree Starting
npm sill install cloneCurrentTreeToIdealTree
npm sill cloneCurrentTree Finishing
npm sill loadShrinkwrap Starting
npm sill install loadShrinkwrap
npm sill loadShrinkwrap Finishing
npm sill loadAllDepsIntoIdealTree Starting
npm sill install loadAllDepsIntoIdealTree
npm sill resolveWithNewModule cordova@6.4.0 checking installable status
npm sill cache add args [ 'cordova', null ]
npm verb cache add spec cordova
npm sill cache add parsed spec Result {
npm sill cache add   raw: 'cordova',
npm sill cache add   scope: null,
npm sill cache add   escapedName: 'cordova',
npm sill cache add   name: 'cordova',
npm sill cache add   rawSpec: '',
npm sill cache add   spec: 'latest',
npm sill cache add   type: 'tag' }
npm sill addNamed cordova@latest
npm verb addNamed "latest" is being treated as a dist-tag for cordova
npm info addNameTag [ 'cordova', 'latest' ]
npm sill mapToRegistry name cordova
npm sill mapToRegistry using default registry
npm sill mapToRegistry registry https://registry.npmjs.org/
npm sill mapToRegistry data Result {
npm sill mapToRegistry   raw: 'cordova',
npm sill mapToRegistry   scope: null,
npm sill mapToRegistry   escapedName: 'cordova',
npm sill mapToRegistry   name: 'cordova',
npm sill mapToRegistry   rawSpec: '',
npm sill mapToRegistry   spec: 'latest',
npm sill mapToRegistry   type: 'tag' }
npm sill mapToRegistry uri https://registry.npmjs.org/cordova
npm verb addNameTag registry:https://registry.npmjs.org/cordova not in flight; f                                                                                                                etching
npm verb get https://registry.npmjs.org/cordova not expired, no request
npm sill addNameTag next cb for cordova with tag latest
npm sill addNamed cordova@6.4.0
npm verb addNamed "6.4.0" is a plain semver version for cordova
npm sill mapToRegistry name cordova
npm sill mapToRegistry using default registry
npm sill mapToRegistry registry https://registry.npmjs.org/
npm sill mapToRegistry data Result {
npm sill mapToRegistry   raw: 'cordova',
npm sill mapToRegistry   scope: null,
npm sill mapToRegistry   escapedName: 'cordova',
npm sill mapToRegistry   name: 'cordova',
npm sill mapToRegistry   rawSpec: '',
npm sill mapToRegistry   spec: 'latest',
npm sill mapToRegistry   type: 'tag' }
npm sill mapToRegistry uri https://registry.npmjs.org/cordova
npm verb addRemoteTarball https://registry.npmjs.org/cordova/-/cordova-6.4.0.tgz                                                                                                                 not in flight; adding
npm verb addRemoteTarball [ 'https://registry.npmjs.org/cordova/-/cordova-6.4.0.                                                                                                                tgz',
npm verb addRemoteTarball   '3fd9e8b9ad77a6a93ec76947704de21ac2991776' ]

**Comment by GirishBhat** [comment]
@legodude17 
Is that ok to download those plugins manually and save it in .npm-package directory,without using npm command?

**Comment by legodude17** [comment]
It is technically possible but it is a lot of work. You might want to grab the latest version of `npm` off of the homepage.

**Comment by GirishBhat** [comment]
@legodude17 Then I don't want to do it manually..Please let me know the solution

**Comment by GirishBhat** [comment]
@legodude17
 I copied all node_modules from other system to my system.
Then I tried **npm uninstall -g cordova** then it is able to uninstall but when I try to Install it same issue

**Comment by legodude17** [comment]
You may want to try upgrading `npm` and node...

**Comment by GirishBhat** [comment]
@legodude17 

After few workaround finally I am getting some error,could you please tell what is this error and how to resolve this.

$ npm install -g
npm ERR! addLocal Could not install C:\
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\          node_modules\\npm\\bin\\npm-cli.js" "install" "-g"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code EISDIR
npm ERR! errno -4068
npm ERR! syscall read

npm ERR! eisdir EISDIR: illegal operation on a directory, read
npm ERR! eisdir This is most likely not a problem with npm itself
npm ERR! eisdir and is related to npm not being able to find a package.json in
npm ERR! eisdir a package you are trying to install.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\npm-debug.log

**Comment by GirishBhat** [comment]
@legodude17 
while searching on Internet I came across https://github.com/npm/npm/issues/7590
this link which is similar to mine.I ran npm config ls -l
$ npm config ls -l
; cli configs
long = true
user-agent = "npm/3.10.9 node/v6.9.2 win32 x64"

; userconfig C:\Users\bgh40689\.npmrc
prefix = "C:\\Users\\bgh40689\\.npm-packages"

; builtin config undefined
; prefix = "C:\\Users\\bgh40689\\AppData\\Roaming\\npm" (overridden)

; default values
access = null
also = null
always-auth = false
bin-links = true
browser = null
ca = null
cache = "C:\\Users\\bgh40689\\AppData\\Roaming\\npm-cache"
cache-lock-retries = 10
cache-lock-stale = 60000
cache-lock-wait = 10000
cache-max = null
cache-min = 10
cafile = undefined
cert = null
color = true
depth = null
description = true
dev = false
dry-run = false
editor = "notepad.exe"
engine-strict = false
fetch-retries = 2
fetch-retry-factor = 10
fetch-retry-maxtimeout = 60000
fetch-retry-mintimeout = 10000
force = false
git = "git"
git-tag-version = true
global = false
global-style = false
globalconfig = "C:\\Users\\bgh40689\\.npm-packages\\etc\\npmrc"
globalignorefile = "C:\\Users\\bgh40689\\.npm-packages\\etc\\npmignore"
group = 0
heading = "npm"
https-proxy = null
if-present = false
ignore-scripts = false
init-author-email = ""
init-author-name = ""
init-author-url = ""
init-license = "ISC"
init-module = "C:\\Users\\bgh40689\\.npm-init.js"
init-version = "1.0.0"
json = false
key = null
legacy-bundling = false
link = false
local-address = undefined
loglevel = "warn"
; long = false (overridden)
maxsockets = 50
message = "%s"
node-version = "6.9.2"
npat = false
onload-script = null
only = null
optional = true
parseable = false
; prefix = "C:\\Program Files\\nodejs" (overridden)
production = false
progress = true
proprietary-attribs = true
proxy = null
rebuild-bundle = true
registry = "https://registry.npmjs.org/"
rollback = true
save = false
save-bundle = false
save-dev = false
save-exact = false
save-optional = false
save-prefix = "^"
scope = ""
searchexclude = null
searchopts = ""
searchsort = "name"
shell = "C:\\Windows\\system32\\cmd.exe"
shrinkwrap = true
sign-git-tag = false
strict-ssl = true
tag = "latest"
tag-version-prefix = "v"
**tmp = "C:\\Windows;C:\\Users\\bgh40689\\AppData\\Local\\Temp"**
umask = 0
unicode = false
unsafe-perm = true
usage = false
user = 0
; user-agent = "npm/{npm-version} node/{node-version} {platform} {arch}" (overridden)
userconfig = "C:\\Users\\bgh40689\\.npmrc"
version = false
versions = false
viewer = "browser"

where two temp is present separated by semicolon(;)
Now,I need to delete the first one c:\\windows, how to dot this?

**Comment by GirishBhat** [comment]
Finally It's working after deleting TEMP path,really frustrated this issue.
