### ISSUE TITLE
npm install -g cordova does not work in ubuntu 16.04?

### ISSUE THREAD

**Issue by skarya992** [npm/npm#15357]
getting this:

saurabhsingh@localhost:~$ npm install npm@latest
npm ERR! Linux 4.4.0-57-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "npm@latest"
npm ERR! node v7.3.0
npm ERR! npm  v3.10.10
npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! syscall getaddrinfo

npm ERR! getaddrinfo EAI_AGAIN registry.npmjs.org:443
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/saurabhsingh/npm-debug.log
saurabhsingh@localhost:~$ ^C

**Comment by skarya992** [comment]
saurabhsingh@localhost:~$ sudo npm install -g cordova
[sudo] password for saurabhsingh: 
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
/home/saurabhsingh/npm/bin/cordova -> /home/saurabhsingh/npm/lib/node_modules/cordova/bin/cordova
/home/saurabhsingh/npm/lib
`-- cordova@6.4.0 

but unable to run.........cordova

**Comment by legodude17** [comment]
Please put each issue in a separate filing. The first one is related to your internet not working, the second one is related to your `npm prefix -g` not being in your `$PATH`.

**Comment by skarya992** [comment]
when i am installing cordova.................

saurabhsingh@localhost:~$ sudo npm install -g cordova
[sudo] password for saurabhsingh: 
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
/home/saurabhsingh/npm/bin/cordova -> /home/saurabhsingh/npm/lib/node_modules/cordova/bin/cordova
/home/saurabhsingh/npm/lib
`-- cordova@6.4.0 

i am new to this..........what should i do?

**Comment by skarya992** [comment]
i am new to this..............plz tell me any solution for this?

**Comment by Sankarrockzz** [comment]
No working...

`npm WARN optional Skipping failed optional dependency /7zip-bin/7zip-bin-mac:
npm WARN notsup Not compatible with your operating system or architecture: 7zip-bin-mac@1.0.1
npm WARN optional Skipping failed optional dependency /7zip-bin/7zip-bin-win:
npm WARN notsup Not compatible with your operating system or architecture: 7zip-bin-win@2.0.2
npm WARN figma-ubuntu-app@0.0.0 No repository field.
npm ERR! Linux 4.4.0-57-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! electron@1.4.13 postinstall: `node install.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the electron@1.4.13 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/snkr/Downloads/figma-app-ubuntu-master/npm-debug.log
`

**Comment by legodude17** [comment]
@Sankarrockzz please file a seperate issue.

@skarya992 do you have a working internet conection? What is the result of `npm prefix -g` and `echo $PATH`

**Comment by skarya992** [comment]
yes i have working internet..........

saurabhsingh@localhost:~$ npm prefix -g
/home/saurabhsingh/npm


saurabhsingh@localhost:~$ echo $PATH
/home/saurabhsingh/bin:/home/saurabhsingh/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/saurabhsingh/Android/Sdk/tools:/home/saurabhsingh/Android/Sdk/platform-tools:/home/saurabhsingh/apache-ant-1.9.7/bin

**Comment by legodude17** [comment]
You need to add `/home/saurabhsingh/npm` to your $PATH.
