### ISSUE TITLE
Unable to install Cordova in my system , Windows 8.1

### ISSUE THREAD

**Issue by mgdutt** [npm/npm#15354]
Unable to install Cordova in my system , Windows 8.1
I have followed the same procedure explained in the website for installation I am getting error as mentioned below
 **[    ..............] | loadRequestedDeps: sill install loadAllDepsIntoIdealTree**

![cmd](https://cloud.githubusercontent.com/assets/13729577/21564957/f3a939c4-ceb7-11e6-8582-c0d30d93692f.PNG)

#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
@mgdutt can you please fill in the issue template?
