### ISSUE TITLE
npm ERR! Darwin 14.5.0

### ISSUE THREAD

**Issue by chuan442599766** [npm/npm#15352]
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/node/5.9.1/bin/node" "/usr/local/bin/npm" "install" "-g" "weex-toolkit"
npm ERR! node v5.9.1
npm ERR! npm  v3.7.3

npm ERR! shasum check failed for /var/folders/j1/8v56tk793xsgtzv08hy1l23r0000gn/T/npm-4859-f389d285/registry.npmjs.org/weex-devtool/-/weex-devtool-0.2.64.tgz
npm ERR! Expected: d96a31525d42b8c5dd5d0dd1342b1ad4de9f7bc7
npm ERR! Actual:   5f38c71679d6418a75d1b322341a4616304266c9
npm ERR! From:     https://registry.npmjs.org/weex-devtool/-/weex-devtool-0.2.64.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mac/npm-debug.log

**Comment by legodude17** [comment]
Hello! This is a duplicated of #14626. Try updating to the latest version of `npm`, as it was fixed there.
