### ISSUE TITLE
npm install ionic issue: deprecated warnings

### ISSUE THREAD

**Issue by chimes27** [npm/npm#15356]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ x] npm is producing an incorrect install.
  - [ x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Could not install ionic properly. The npm installed on my machine is working except for ionic installation
#### How can the CLI team reproduce the problem?
Installation does not include errors but displays warning for minimatch, node-uuid, graceful-fs, fsevents. Though the ionic was successfully installed, but "ionic start" command will produce errors and does not start as expected.

[![report2.png](https://s27.postimg.org/jyb67zzqr/report2.png)](https://postimg.org/image/dkm34quun/) 

Solutions applied:
1. Downgraded nodejs version to 4.4.7 and 6.9.2. Still same result.
2. Upgraded npm using "npm install -g npm@latest", cleaned cache and registry update, still same result.
3. Manually updated modules (I really don't know if this might worked by tried anyway) by running:
_npm install -g minimatch@latest_
_npm install -g uuid_
_npm install -g graceful-fs_

### supporting information:

 - `npm -v` prints: 4.0.5
 - `node -v` prints: v.7.3.0
 - `npm config get registry` prints: https://registry.npmjs.org
 - Windows, OS X/macOS, or Linux?: Windows 7 Ultimate x64 bit

**Comment by legodude17** [comment]
The isn't an error, just some warnings. What is the problem?

**Comment by chimes27** [comment]
i could not use the "ionic start" command after the installation. It displays the following error:

[![report3.png](https://s30.postimg.org/qbtgjjjsx/report3.png)](https://postimg.org/image/5ex8evlrx/)

**Comment by legodude17** [comment]
The error message is asking you to file it to the ionic-cli module. Please do that instead. Sorry for the inconvenience.
