### ISSUE TITLE
Installing “MavensMate-Atom@1.0.10” failed

### ISSUE THREAD

**Issue by adamSkin** [npm/npm#15353]
Installing “MavensMate-Atom@1.0.10” failed.Hide output…

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\meesayye\\AppData\\Local\\atom\\app-1.12.7\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\meesayye\\AppData\\Local\\atom\\app-1.12.7\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\meesayye\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\meesayye\\.atom\\.apmrc" "install" "C:\\Users\\meesayye\\AppData\\Local\\Temp\\d-1161130-9684-qq4zsw\\package.tgz" "--runtime=electron" "--target=1.3.13" "--arch=ia32" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code UNABLE_TO_GET_ISSUER_CERT_LOCALLY

npm ERR! unable to get local issuer certificate
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\meesayye\AppData\Local\Temp\apm-install-dir-1161130-9684-47flro\npm-debug.log

Can anyone please help me out itz very urjent..
Thanks.

**Comment by yeukfei02** [comment]
``npm -v`` ?
``package.json`` ?

**Comment by adamSkin** [comment]
Hey Yeu,
            i donno what is npm version and package.json....i am new and installing it first time

**Comment by yeukfei02** [comment]
@adamSkin u try to use ``npm install MavensMate-Atom@1.0.10`` right?

**Comment by adamSkin** [comment]
@yeukfei02 .. No i'm installing MavensMate-Atom@1.0.10 package using package installer of Atom

**Comment by legodude17** [comment]
What are the results of the following commands?
1. `npm -v`
2. `node -v`
3. `apm -v`
What OS are you on?

**Comment by js-restaurantlink** [comment]
@adamSkin - did you ever get MavensMate 1.0.10 installed?

**Comment by KenanY** [comment]
Closing as abandoned.
