### ISSUE TITLE
how to do? npm ERR! Darwin 16.1.0......

### ISSUE THREAD

**Issue by aikefang** [npm/npm#15350]
npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "gulp" "browser-sync" "--save-dev"
npm ERR! node v5.11.0
npm ERR! npm  v3.8.6

npm ERR! shasum check failed for /tmp/npm-28535-e4b96755/registry.npmjs.org/rx/-/rx-4.1.0.tgz
npm ERR! Expected: a5f13ff79ef3b740fe30aa803fb09f98805d4782
npm ERR! Actual:   4e33ad0261c53c200c779297cf9f0524b9a4e27a
npm ERR! From:     https://registry.npmjs.org/rx/-/rx-4.1.0.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by legodude17** [comment]
Hello! This is a duplicated of #14626. Try updating to the latest version of `npm`, as it was fixed there.
