### ISSUE TITLE
npm ERR! missing script

### ISSUE THREAD

**Issue by stvader** [npm/npm#15351]
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8

npm ERR! missing script: build
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Frontend\mishka_study\npm-debug.log

**Comment by yeukfei02** [comment]
it should be something miss in your ``package.json``

**Comment by KenanY** [comment]
@stvader Make sure to define a `"build"` script in your `package.json` before trying to run `npm run build`. You can find more information on writing your own `npm` scripts [here](https://docs.npmjs.com/misc/scripts). Let me know if you have any more issues :)
