### ISSUE TITLE
nam errors while installing ionic 

### ISSUE THREAD

**Issue by MuneeraRA** [npm/npm#15355]
When I tried to install ionic this issue occured and I could not understand it ?

export NVM_DIR="/Users/macbookpro/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
macbooks-MacBook-Pro-2:npm-global macbookpro$ npm install -g cordova ionic
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "cordova" "ionic"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9

npm ERR! shasum check failed for /tmp/npm-33469-c02a2bab/registry.npmjs.org/ionic/-/ionic-2.1.18.tgz
npm ERR! Expected: 580ca2b729168394c833e2fda35bbe841c462a57
npm ERR! Actual:   9aa6cff3463aaa929efd9b722be2f6f83d7a55c3
npm ERR! From:     https://registry.npmjs.org/ionic/-/ionic-2.1.18.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/macbookpro/npm-global/npm-debug.log
macbooks-MacBook-Pro-2:npm-global macbookpro$

**Comment by legodude17** [comment]
Hello! This is a duplicated of #14626. Try updating to the latest version of `npm`, as it was fixed there.

**Comment by MuneeraRA** [comment]
I am just a beginner  with ionic and command line 
how can I update my npm version ?
I just download it yesterday

**Comment by legodude17** [comment]
Try `npm i -g npm@4.1.1`

**Comment by MuneeraRA** [comment]
another problem occurred :(

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "cordova" "ionic"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! path /Users/macbookpro/npm-global/lib/node_modules/cordova
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/Users/macbookpro/npm-global/lib/node_modules/cordova'
npm ERR!     at Error (native)
npm ERR!  { Error: EACCES: permission denied, access '/Users/macbookpro/npm-global/lib/node_modules/cordova'
npm ERR!     at Error (native)
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/Users/macbookpro/npm-global/lib/node_modules/cordova' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/macbookpro/npm-global/npm-debug.log

**Comment by legodude17** [comment]
Do you have write access to `/Users/macbookpro/npm-global/`? Do you have an anitvirus?
