### ISSUE TITLE
Unable to parse Ionic Config file. Please make sure it is valid JSON (.ionic/ionic.config)  Caught exception:   SyntaxError: Unexpected token   in JSON at position 0      at Object.parse (native)      at Object.load (C:\Users\USER\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\lib\config.js:14:26)      at Object.<anonymous> (C:\Users\USER\AppData\Roaming\npm\node_modules\ionic\lib\utils\stats.js:31:31)      at Module._compile (module.js:570:32)      at Object.Module._extensions..js (module.js:579:10)      at Module.load (module.js:487:32)      at tryModuleLoad (module.js:446:12)      at Function.Module._load (module.js:438:3)      at Module.require (module.js:497:17)      at require (internal/module.js:20:19)    Mind letting us know? https://github.com/driftyco/ionic-cli/issues    

### ISSUE THREAD

**Issue by callmefareed** [npm/npm#15365]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@callmefareed Please fill in the support template in your post. Also, it would help if the issue title was just a brief description of the issue you are seeing, rather than the entire stack trace. Closing for now since now enough information is available to help you out here :(
