### ISSUE TITLE
Problem with `npm install` on (Laravel) Homestead

### ISSUE THREAD

**Issue by GeekTNTdotCom** [npm/npm#15364]
Hello,

When I try to run npm install - I'm getting these errors:

```
1142 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
1142 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
1142 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
1142 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
1143 warn buble-loader@0.2.2 requires a peer of buble@^0.12.0 but none was installed.
1144 verbose If you need help, you may report this error at:
1144 verbose     <https://github.com/npm/npm/issues>
1145 verbose stack Error: EPROTO: protocol error, symlink '../semver/bin/semver' -> '/home/vagrant/Code/blog/node_modules/accord/n
ode_modules/.bin/semver'
1145 verbose stack     at Error (native)
1146 verbose cwd /home/vagrant/Code/blog
1147 error Linux 4.4.0-51-generic
1148 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
1149 error node v6.9.1
1150 error npm  v3.10.8
1151 error path ../semver/bin/semver
1152 error code EPROTO
1153 error errno -71
1154 error syscall symlink
1155 error EPROTO: protocol error, symlink '../semver/bin/semver' -> '/home/vagrant/Code/blog/node_modules/accord/node_modules/.bi
n/semver'
1156 error If you need help, you may report this error at:
1156 error     <https://github.com/npm/npm/issues>
1157 verbose exit [ -71, true ]
```

I guess it ahs something to do with the symlink but I can't figure this out.

**Comment by KenanY** [comment]
@GeekTNTdotCom Does this also occur if you use the `--no-bin-links` flag?

**Comment by GeekTNTdotCom** [comment]
Well, looks like that it works with that flag...

I just get these two warnings:
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
```

**Comment by lhbfilwmyseve** [comment]
Hello,
i try --no-bin-links;
i got those msg:
**npm WARN buble-loader@0.2.2 requires a peer of buble@^0.12.0 but none was installed.**
i can't figure out. 
OS:WIN10
VM: laravel/homestead
local:China

**Comment by KenanY** [comment]
@lhbfilwmyseve Looks like you need to:

```
npm install --save-dev buble@^0.12.0
```

**Comment by MrChenCode** [comment]
vagrant@homestead:~/Code/TaskManager$ npm rebuild node-sass
npm ERR! Linux 4.4.0-51-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "rebuild" "node-sass"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! path ../node-sass/bin/node-sass
npm ERR! code EPROTO
npm ERR! errno -71
npm ERR! syscall symlink

npm ERR! EPROTO: protocol error, symlink '../node-sass/bin/node-sass' -> '/home/vagrant/Code/TaskManager/node_modules/.bin/node-sass'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/Code/TaskManager/npm-debug.log

win7  VM：laravel / homestead   

I need help who can help me. Thanks

**Comment by KenanY** [comment]
@MrChenCode See: https://github.com/npm/npm/issues/15364#issuecomment-269925455

**Comment by MrChenCode** [comment]
@KenanY   This command I am tried.Still won't do
vagrant@homestead:~/Code/TaskManager$ npm install --save-dev
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

**Comment by KenanY** [comment]
@MrChenCode I do not see any errors in that output.

**Comment by MrChenCode** [comment]
@KenanY  But I am when I'm gulp public and does not appear under add CSS I gulpfile there are commands     

var elixir = require('laravel-elixir');



elixir(function(mix) {
    mix.sass('app.scss');
});
this is gulpfile  Code;

**Comment by ginanjarputra** [comment]
step 1:

npm install --global gulp

Step 2

npm install

step 3 

npm run watch
