### ISSUE TITLE
npm ERR! connect EHOSTUNREACH 151.101.32.162:443

### ISSUE THREAD

**Issue by NamrataCh** [npm/npm#15367]
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code EHOSTUNREACH
npm ERR! errno EHOSTUNREACH
npm ERR! syscall connect

npm ERR! connect EHOSTUNREACH 151.101.32.162:443
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:

**Comment by NamrataCh** [comment]
I am trying to install cordova behind proxy.. giving an error mentioned above... please someone help me out :(

**Comment by legodude17** [comment]
What are the results of:
1. `npm config get registry`
2. `npm config get http-proxy`
3. `npm config get https-proxy`

**Comment by InfiniteStyles** [comment]
I think a million other people have already had this issue. Probably worth it to look around the issues in the repository.
