### ISSUE TITLE
npm install hangs when piped to `tee`

### ISSUE THREAD

**Issue by ValYouW** [npm/npm#15376]
#### I'm opening this issue because:
  - [X ] npm is doing something I don't understand.

#### What's going wrong?
npm hangs after it finishes when running alongside the `tee` command

#### How can the CLI team reproduce the problem?
Create a `test.sh` file which only runs npm install:
```
#!/bin/bash
npm install
```

Then run it from command line piping into tee:
`./test.sh 2>&1 | tee log.txt`

The result is that the script never finishes, just hangs.
Using install with verbose I DO see that npm reports exit, but that's not really happening...
```
...
...
npm WARN npmtest@1.0.0 No description
npm verb
npm verb If you need help, you may report this error at:
npm verb     <https://github.com/npm/npm/issues>
npm WARN npmtest@1.0.0 No repository field.
npm verb
npm verb If you need help, you may report this error at:
npm verb     <https://github.com/npm/npm/issues>
npm verb exit [ 0, true ]
```

My test `package.json`
```
{
  "name": "npmtest",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "extend": "^3.0.0"
  }
}
```

My env:
Git Bash on Windows (git version 2.11.0.windows.1)
node - v6.9.1
npm - 3.10.8

Thanks.

**Comment by legodude17** [comment]
I have seen this a little bit, but not with `npm install`.. Does it work fine without piping to `tee`? What about `npm install | tee`?

**Comment by ValYouW** [comment]
Played with it a little bit, the problem happens only when redirecting stderr to stdout `2>&1` and not really related to the `install` command.
For example:
`npm --help 2>&1 | tee log.txt` hangs
`npm --help | tee log.txt` works fine

Hope it helps...

**Comment by sancit** [comment]
Any solution for this

npm --help 2>&1 | tee log.txt hangs

I exactly want to redirect stderr to stdout (2>&1) and use tee

I am using npm to run karma along with 2>&1 | tee which hangs and i am not finding useful solution.

**Comment by sancit** [comment]
I was able to solve with --silent option, i hope this option silences npm from writing into stdout
and so
npm --silent run test 2>&1 | tee log.txt
shouldn't hang.

**Comment by legodude17** [comment]
Does that work with other node scripts? E.g. babel?
