### ISSUE TITLE
Call to Node module failed with error: .........\node_modules\ng2-smart-table\build\src\ng2-smart-table\ng2-smart-table.scss:1

### ISSUE THREAD

**Issue by PradeepPatil2016** [npm/npm#15370]
Please help me i am getting error while running ng2-Smart-table basic table component

Exception: Call to Node module failed with error: .............\node_modules\ng2-smart-table\build\src\ng2-smart-table\ng2-smart-table.scss:1
(function (exports, require, module, __filename, __dirname) { .ng2-smart-table {
^
SyntaxError: Unexpected token .
at Object.exports.runInThisContext (vm.js:78:16)
at Module._compile (module.js:543:28)
at Object.Module._extensions..js (module.js:580:10)
at Module.load (module.js:488:32)
at tryModuleLoad (module.js:447:12)
at Function.Module._load (module.js:439:3)
at Module.require (module.js:498:17)
at require (internal/module.js:20:19)
at E:\web\node_modules\ng2-smart-table\build\src\ng2-smart-table\ng2-smart-table.component.js:209:22
at Object.<anonymous> (E:\web\node_modules\ng2-smart-table\build\src\ng2-smart-table\ng2-smart-table.component.js:215:2)

Code is 

`import { Component, OnInit } from '@angular/core';

@Component({
    selector: 'smartdatatable',
    styles: [require("../../../../node_modules/ng2-smart-table/build/src/ng2-smart-table/ng2-smart-table.scss")],
  template: `
    <ng2-smart-table [settings]="settings"></ng2-smart-table>
  `
})

export class smartdatatablecomponent {

    settings = {
        columns: {
            id: {
                title: 'ID',
                filter: false
            },
            name: {
                title: 'Full Name',
                filter: false
            },
            username: {
                title: 'User Name',
                filter: false
            },
            email: {
                title: 'Email',
                filter: false
            }
        }
    };

    data = [
        {
            id: 1,
            name: "Leanne Graham",
            username: "Bret",
            email: "Sincere@april.biz"
        },
        {
            id: 2,
            name: "Ervin Howell",
            username: "Antonette",
            email: "Shanna@melissa.tv"
        },
        {
            id: 3,
            name: "Clementine Bauch",
            username: "Samantha",
            email: "Nathan@yesenia.net"
        },
        {
            id: 4,
            name: "Patricia Lebsack",
            username: "Karianne",
            email: "Julianne.OConner@kory.org"
        },
        {
            id: 5,
            name: "Chelsey Dietrich",
            username: "Kamren",
            email: "Lucio_Hettinger@annie.ca"
        },
        {
            id: 6,
            name: "Mrs. Dennis Schulist",
            username: "Leopoldo_Corkery",
            email: "Karley_Dach@jasper.info"
        },
        {
            id: 7,
            name: "Kurtis Weissnat",
            username: "Elwyn.Skiles",
            email: "Telly.Hoeger@billy.biz"
        },
        {
            id: 8,
            name: "Nicholas Runolfsdottir V",
            username: "Maxime_Nienow",
            email: "Sherwood@rosamond.me"
        },
        {
            id: 9,
            name: "Glenna Reichert",
            username: "Delphine",
            email: "Chaim_McDermott@dana.io"
        },
        {
            id: 10,
            name: "Clementina DuBuque",
            username: "Moriah.Stanton",
            email: "Rey.Padberg@karina.biz"
        },
        {
            id: 11,
            name: "Nicholas DuBuque",
            username: "Nicholas.Stanton",
            email: "Rey.Padberg@rosamond.biz"
        }
    ];
}

`

**Comment by KenanY** [comment]
Closing since this doesn't appear to be a `npm` issue. This issue tracker is for bugs and feature requests pertaining to `npm`.
