### ISSUE TITLE
Please help NPM UNABLE_TO_VERIFY_LEAF_SIGNATURE

### ISSUE THREAD

**Issue by kraxeyy** [npm/npm#15372]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@3.10.9
3 info using node@v6.9.2
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly install normalizeTree
8 silly loadCurrentTree Finishing
9 silly loadIdealTree Starting
10 silly install loadIdealTree
11 silly cloneCurrentTree Starting
12 silly install cloneCurrentTreeToIdealTree
13 silly cloneCurrentTree Finishing
14 silly loadShrinkwrap Starting
15 silly install loadShrinkwrap
16 silly loadShrinkwrap Finishing
17 silly loadAllDepsIntoIdealTree Starting
18 silly install loadAllDepsIntoIdealTree
19 silly fetchNamedPackageData steam
20 silly mapToRegistry name steam
21 silly mapToRegistry using default registry
22 silly mapToRegistry registry https://registry.npmjs.org/
23 silly mapToRegistry data Result {
23 silly mapToRegistry   raw: 'steam',
23 silly mapToRegistry   scope: null,
23 silly mapToRegistry   escapedName: 'steam',
23 silly mapToRegistry   name: 'steam',
23 silly mapToRegistry   rawSpec: '',
23 silly mapToRegistry   spec: 'latest',
23 silly mapToRegistry   type: 'tag' }
24 silly mapToRegistry uri https://registry.npmjs.org/steam
25 silly fetchNamedPackageData steam-user
26 silly mapToRegistry name steam-user
27 silly mapToRegistry using default registry
28 silly mapToRegistry registry https://registry.npmjs.org/
29 silly mapToRegistry data Result {
29 silly mapToRegistry   raw: 'steam-user',
29 silly mapToRegistry   scope: null,
29 silly mapToRegistry   escapedName: 'steam-user',
29 silly mapToRegistry   name: 'steam-user',
29 silly mapToRegistry   rawSpec: '',
29 silly mapToRegistry   spec: 'latest',
29 silly mapToRegistry   type: 'tag' }
30 silly mapToRegistry uri https://registry.npmjs.org/steam-user
31 verbose request uri https://registry.npmjs.org/steam
32 verbose request no auth needed
33 info attempt registry request try #1 at 19:46:52
34 verbose request id efdfd724c094024d
35 http request GET https://registry.npmjs.org/steam
36 verbose request uri https://registry.npmjs.org/steam-user
37 verbose request no auth needed
38 info attempt registry request try #1 at 19:46:52
39 http request GET https://registry.npmjs.org/steam-user
40 info retry will retry, error on last attempt: Error: unable to verify the first certificate
41 info retry will retry, error on last attempt: Error: unable to verify the first certificate
42 info attempt registry request try #2 at 19:47:02
43 http request GET https://registry.npmjs.org/steam
44 info attempt registry request try #2 at 19:47:02
45 http request GET https://registry.npmjs.org/steam-user
46 info retry will retry, error on last attempt: Error: unable to verify the first certificate
47 info retry will retry, error on last attempt: Error: unable to verify the first certificate
48 info attempt registry request try #3 at 19:48:02
49 http request GET https://registry.npmjs.org/steam-user
50 info attempt registry request try #3 at 19:48:02
51 http request GET https://registry.npmjs.org/steam
52 silly fetchPackageMetaData Error: unable to verify the first certificate
52 silly fetchPackageMetaData     at Error (native)
52 silly fetchPackageMetaData     at TLSSocket.<anonymous> (_tls_wrap.js:1079:38)
52 silly fetchPackageMetaData     at emitNone (events.js:86:13)
52 silly fetchPackageMetaData     at TLSSocket.emit (events.js:185:7)
52 silly fetchPackageMetaData     at TLSSocket._finishInit (_tls_wrap.js:603:8)
52 silly fetchPackageMetaData     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:433:38)
52 silly fetchPackageMetaData  error for steam-user@^3.14.0 { Error: unable to verify the first certificate
52 silly fetchPackageMetaData     at Error (native)
52 silly fetchPackageMetaData     at TLSSocket.<anonymous> (_tls_wrap.js:1079:38)
52 silly fetchPackageMetaData     at emitNone (events.js:86:13)
52 silly fetchPackageMetaData     at TLSSocket.emit (events.js:185:7)
52 silly fetchPackageMetaData     at TLSSocket._finishInit (_tls_wrap.js:603:8)
52 silly fetchPackageMetaData     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:433:38) code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE' }
53 silly fetchPackageMetaData Error: unable to verify the first certificate
53 silly fetchPackageMetaData     at Error (native)
53 silly fetchPackageMetaData     at TLSSocket.<anonymous> (_tls_wrap.js:1079:38)
53 silly fetchPackageMetaData     at emitNone (events.js:86:13)
53 silly fetchPackageMetaData     at TLSSocket.emit (events.js:185:7)
53 silly fetchPackageMetaData     at TLSSocket._finishInit (_tls_wrap.js:603:8)
53 silly fetchPackageMetaData     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:433:38)
53 silly fetchPackageMetaData  error for steam@^1.4.0 { Error: unable to verify the first certificate
53 silly fetchPackageMetaData     at Error (native)
53 silly fetchPackageMetaData     at TLSSocket.<anonymous> (_tls_wrap.js:1079:38)
53 silly fetchPackageMetaData     at emitNone (events.js:86:13)
53 silly fetchPackageMetaData     at TLSSocket.emit (events.js:185:7)
53 silly fetchPackageMetaData     at TLSSocket._finishInit (_tls_wrap.js:603:8)
53 silly fetchPackageMetaData     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:433:38) code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE' }
54 silly rollbackFailedOptional Starting
55 silly rollbackFailedOptional Finishing
56 silly runTopLevelLifecycles Finishing
57 silly install printInstalled
58 verbose stack Error: unable to verify the first certificate
58 verbose stack     at Error (native)
58 verbose stack     at TLSSocket.<anonymous> (_tls_wrap.js:1079:38)
58 verbose stack     at emitNone (events.js:86:13)
58 verbose stack     at TLSSocket.emit (events.js:185:7)
58 verbose stack     at TLSSocket._finishInit (_tls_wrap.js:603:8)
58 verbose stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:433:38)
59 verbose cwd C:\Users\Max\Desktop\steam-yellow-master\steam-yellow-master
60 error Windows_NT 10.0.10586
61 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
62 error node v6.9.2
63 error npm  v3.10.9
64 error code UNABLE_TO_VERIFY_LEAF_SIGNATURE
65 error unable to verify the first certificate
66 error If you need help, you may report this error at:
66 error     <https://github.com/npm/npm/issues>
67 verbose exit [ 1, true ]

C:\Users\Max>cd C:\Users\Max\Desktop\steam-yellow-master\steam-yellow-master

C:\Users\Max\Desktop\steam-yellow-master\steam-yellow-master>npm install
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code UNABLE_TO_VERIFY_LEAF_SIGNATURE

npm ERR! unable to verify the first certificate
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Max\Desktop\steam-yellow-master\steam-yellow-master\npm-debug.log

C:\Users\Max\Desktop\steam-yellow-master\steam-yellow-master>

**Comment by legodude17** [comment]
What is the contents of `C:\Users\Max\Desktop\steam-yellow-master\steam-yellow-maste\package.json`?

**Comment by kraxeyy** [comment]
@legodude17 this came, when I wrote "npm install"

**Comment by legodude17** [comment]
@kraxeyy ok, but does `C:\Users\Max\Desktop\steam-yellow-master\steam-yellow-maste\package.json` exist? If so, what are its contents?

**Comment by Yochanan-Khoury** [comment]
I am working on setting up my project work-space .
I followed the instructions for getting started with Tessel.io. 

I have my directory as,
 C;\users\John\j5ik>**npm install johnny-five tessel-io**
Once I enter this command I get various npm errors:
 such as:
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Programm Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js........
npm ERR! node v6.9.5
npm ERR! npm v3.10.10
npm ERR! code UNABLE_TO_VERIFY_LEAF_SIGNATURE
npm ERR! unable to verify the first certificate
npm ERR!
npm ERR! If you need help, you may report this error at: 
npm ERR!       <https://github.com/npm/npm/issues>
npm ERR! Please include the following file with any support request:
npm ERR!        C:\users\John\j5ik\npm-debug.log


What should I do to continue with setting up my work-space and rectify these errors?
