### ISSUE TITLE
Missing information on Documentation-Page

### ISSUE THREAD

**Issue by xstable** [npm/npm#15371]
At this Page for Option2 there is some Information missing:
https://docs.npmjs.com/getting-started/fixing-npm-permissions

E.g. if you install jsdoc, it has a binary. This will be installed to ~/.npm-global/bin/. But this is not executable in whole System-Enviroment, because ~/.npm-global is not addet to PATH-Enviroment-Variable.

So please add this line to the Docs:
`
export PATH=$PATH:~/.npm-global/bin/
`

**Comment by KenanY** [comment]
@xstable Looks like that information is already there:

![chrome_2017-01-02_12-27-20](https://cloud.githubusercontent.com/assets/733364/21593586/d334df3c-d0e6-11e6-933a-ceae26d7f0d1.png)

**Comment by KenanY** [comment]
This belongs in [npm/docs](https://github.com/npm/docs) anyways since that page's source in not in this repository. So, if you still think this is an issue I suggest you raise it over there.

**Comment by suther** [comment]
OK, I missed it because I choosed the last Variante....
> Instead of steps 2-4 you can also use the corresponding ENV variable (e.g. if you don't want to modify ~/.profile):

Step 3 is the path-setting but the comment told you can skip step 2 till 4.
Maybe fix this wrong information.
