### ISSUE TITLE
[Question] check for global permissions

### ISSUE THREAD

**Issue by 45kb** [npm/npm#15378]
Hi, sorry for bothering, i have a simple question.

Is there any way to check (through npmCLI and/or npm.js) if npm global permissions are fixed on the machine? 

Literally if no `sudo` is required for to install global packages.

I am currently checking this via process user and group etc.. (inside node), and i'd love to just call an npm method to return this information, but i understand it's probably a weird request.

Thank you.

**Comment by amazighezed** [comment]
you have just to change the name of your app, and put "sudo npm pub"

**Comment by 45kb** [comment]
@amazighezed  i think you replied on the wrong issue,  question is not on how to publish an npm pkg :D

**Comment by legodude17** [comment]
I think that `npm doctor` does that in `npm@4.1.2`

**Comment by 45kb** [comment]
@legodude17 woa cool  didn't know about `doctor` , is there any way to extrapolate only that specific information and not all the infos?  maybe something like `npm doctor permissions` !? (just guessing)

However it's exactly what i'd need in case, thanks a lot!

**Comment by legodude17** [comment]
@45kb No problem! Happy coding!
