### ISSUE TITLE
npm install --save-dev postcss@5.2.8 error

### ISSUE THREAD

**Issue by zhangping2014** [npm/npm#15389]
Error: unknown compression method (postcss@5.2.8) (/Users/drank/.npminstall_tarball/p/o/s/t/postcss/5.2.8-05720c49df23c79bda51fd01daeb1e9222e94390.tgz)
at Zlib._handle.onerror (zlib.js:363:17)
npminstall version: 2.2.1
npminstall args: /usr/local/bin/node /usr/local/lib/node_modules/cnpm/node_modules/.bin/npminstall --china --userconfig=/Users/drank/.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=https://registry.npm.taobao.org postcss

**Comment by KenanY** [comment]
@zhangping2014 Could you upload the full `npm-debug.log` to <https://gist.github.com/> and link here?

**Comment by zhangping2014** [comment]
@kaichen  there is no npm-debug.log. only :npm ERR! cb() never called!

**Comment by KenanY** [comment]
@zhangping2014 I'm gonna close this since you seem to have opened a new issue (https://github.com/npm/npm/issues/15395).

**Comment by zhangping2014** [comment]
ok
