### ISSUE TITLE
events.js:160       throw er; // Unhandled 'error' event       ^  TypeError: jhipsterFunc.addNpmDevDependency is not a function  

### ISSUE THREAD

**Issue by appservice** [npm/npm#15382]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by appservice** [comment]
I received error: 
events.js:160       throw er; // Unhandled 'error' event       ^  TypeError: jhipsterFunc.addNpmDevDependency is not a function     
npm version: 3.10.8
node version: 6.9.1
jhipster version: 3.12.2

**Comment by KenanY** [comment]
@appservice What command are you running to get that error? Is there a `npm-debug.log` file you can upload to <https://gist.github.com/> and link here?

**Comment by KenanY** [comment]
Closing as abandoned.
