### ISSUE TITLE
Windows not able to install any package

### ISSUE THREAD

**Issue by BhaskarNewase** [npm/npm#15380]
**[    ..............] / loadRequestedDeps: sill install loadAllDepsIntoIdealTree**

Not able to install any packages on windows 7 

Node version : 4.0.0
npm version : 2.14.2

**Comment by Charlotteis** [comment]
Your version of npm is very outdated, please upgrade to the latest version:

```
npm install -g npm@latest
```

🌸

**Comment by BhaskarNewase** [comment]
I am not able to install any packages.

Now using-
Node version : 6.9.3
npm version : 3.10.10

This is happening on every package :
![capture](https://cloud.githubusercontent.com/assets/8101001/21678400/983c5736-d364-11e6-9d08-52d4f62fa3d4.JPG)

**Comment by bensontrent** [comment]
What is your full error message?  Are you behind a firewall or VPN? Have you reviewed troubleshooting docs?  [https://github.com/npm/npm/wiki/Troubleshooting]

(https://github.com/npm/npm/wiki/Troubleshooting)

If an install process hangs, I find I can use Ctrl + C to terminate a sub-install process that is hanging, and then re-install without problems.
