### ISSUE TITLE
Error install sails with npm

### ISSUE THREAD

**Issue by Ingosmar89219** [npm/npm#15383]
noeblack@garyhost:~$ npm -g install sails 
npm ERR! Linux 4.4.0-57-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "-g" "install" "sails"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2

npm ERR! shasum check failed for /tmp/npm-1980-884211b7/registry.npmjs.org/lodash/-/lodash-4.16.6.tgz
npm ERR! Expected: d22c9ac660288f3843e16ba7d2b5d06cca27d777
npm ERR! Actual:   5ee077d58145c90d3be2fac6e3e16e0d3c3e6b0e
npm ERR! From:     https://registry.npmjs.org/lodash/-/lodash-4.16.6.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/noeblack/npm-debug.log

WHAT CAN I DO ? thank guys! i need your help

**Comment by Ingosmar89219** [comment]
i did it but didnt work nice. actually now i dont get the error just wait but never finish the cicle
noeblack@garyhost:~$ npm cache clean
noeblack@garyhost:~$ npm -g install sails
loadRequestedDeps → netwo

**Comment by legodude17** [comment]
Is this a different issue or the same one?

**Comment by Ingosmar89219** [comment]
same one :/

**Comment by legodude17** [comment]
The shasum check failed issue is fixed in the latest version of `npm`. Try updating.

**Comment by KenanY** [comment]
Closing as abandoned.
