### ISSUE TITLE
Customizing npm installation command

### ISSUE THREAD

**Issue by mathikp** [npm/npm#15388]
Is it possible to customize npm installation command with file restrictions? For example, if an npm github repo have 10 files in it, I dont need to install all the 10 files. If a user installs that package, only one file should be installed in the directory. I'm aware of .npmignore. But it restricts all the time. My goal is, if a user wants to install the entire package, he can install using normal install command. And if another user needs only one file from the package, he have to use a custom command to install that particular file. How to achieve this case using custom installation command or any other method?

**Comment by KenanY** [comment]
Not currently possible as far as I know.
