### ISSUE TITLE
[FR] Support for checking the directory structure upwards before even going on the network

### ISSUE THREAD

**Issue by noherczeg** [npm/npm#15381]
#### I'm opening this issue because:

  - [x] Other (_see below for feature requests_):

#### What's the feature?
Since [Node supports traversing the directory structure upwards for module resolution](http://stackoverflow.com/a/15237183) (I tried it out and it did work) NPM should also do this before going to the network for dependencies when e.g. `npm install` is ran.

As seen in the referenced SO example:
```
-Project
--subproject1
---node_modules
----grunt-collection
-----package.json
--subproject2
...
--subproject3
...
--node_modules
---grunt
...
--package.json
```

#### What problem is the feature intended to solve?
E.g. possible enormous duplication of dependencies when working with a monorepo architecture. Also this would result in way less network traffic which means less time waiting, and less effort put on CI envs.

If we take the monorepo architecture for concrete example this would result in a way in which sub-packages/modules could have dependencies defined in them because they would only be installed in their own respective directories if
- said dependency wouldn't be defined in any of the parent folders' package.json file
- a dependency would be required with a different version other than any of the parent definition versions

#### Is the absence of this feature blocking you or your team? If so, how?
Kind of blocks our refactor plans.

#### Is this feature similar to an existing feature in another tool?
Yes, as mentioned above, Node handles this pretty well.

#### Is this a feature you're prepared to implement, with support from the npm CLI team?
Not sure, maybe.

**Comment by noherczeg** [comment]
Just noticed that npm scripts don't work this way because they can not find packages which are supposed to run from a local install. Don't know if this would deserve a separate feature request or not. :-/

Having
```
"scripts": {
    "build": "webpack --config webpack.dev.js"
},
```

And running `npm run build` in the sub-module results in an error because it can not locate webpack.

```
> webpack --config webpack.dev.js

sh: webpack: command not found
```

**Comment by legodude17** [comment]
@noherczeg that is expected, npm adds the current `node_modules/.bin` to the path, but not the parents.
