### ISSUE TITLE
getting error in mars 2

### ISSUE THREAD

**Issue by cuber555** [npm/npm#15386]
Node.js version:    v7.2.1
NPM version:        3.10.10
npm install
npm WARN deprecated es6-module-loader@0.17.11: This project has been deprecated for "npm install es-module-loader" based on the newer loader spec.
npm ERR! Linux 4.2.0-27-generic
npm ERR! argv "/home/hemanth/.webclipse/nodejs/7.2.1/bin/node" "/home/hemanth/.webclipse/npm/3.10.10/bin/npm-cli.js" "install"
npm ERR! node v7.2.1
npm ERR! npm  v3.10.10
npm ERR! code EREADFILE

npm ERR! Error extracting /home/hemanth/.npm/ng2-bootstrap/1.1.15/package.tgz archive: ENOENT: no such file or directory, open '/home/hemanth/.npm/ng2-bootstrap/1.1.15/package.tgz'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/hemanth/workspace/Angular/npm-debug.log

**Comment by watilde** [comment]
Hello! Your error log said you may have some wrong cache files
> npm ERR! Error extracting /home/hemanth/.npm/ng2-bootstrap/1.1.15/package.tgz archive: ENOENT: no such file or directory, open '/home/hemanth/.npm/ng2-bootstrap/1.1.15/package.tgz'

Then `npm cache clean` command may help you to resolve it.
