### ISSUE TITLE
npm link + native modules

### ISSUE THREAD

**Issue by ORESoftware** [npm/npm#15384]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I am getting an error when using npm link with a native module, all on my machine
I am on Node v 7.2.1
This is probably a known issue (?)

#### How can the CLI team reproduce the problem?

I am developing a native module ("replace-line" it's on NPM)

All was working fine, until I tried to use npm link to avoid having to publish the module.

I tried to link it to another project on my machine using:

```console
cd <replace-line-project-root> && npm link
cd <other-project-root> && npm link replace-line
```

then I got this error:

```
module.js:598
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: The module '/home/oleg/WebstormProjects/oresoftware/observable-persistent-queue/node_modules/replace-line/build/Release/hello.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 46. This version of Node.js requires
NODE_MODULE_VERSION 51. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/oleg/WebstormProjects/oresoftware/observable-persistent-queue/node_modules/replace-line/index.js:1:80)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
```

Is this error expected and how can I avoid it? Seems like it pertains specifically to native modules and has soomething to do with NPM link? This is all happening on the same machine, and both projects should be using the same version of Node, so that's why it's definitely unexpected.

**Comment by ORESoftware** [comment]
I even did

`rm -rf node_modules`

and then re-installed...same problem

so weird, because this problem was not happening earlier, and I swear the only different thing I did was run` npm link`

**Comment by legodude17** [comment]
Try running `npm rebuild` in the first directory.
