### ISSUE TITLE
npm test for nock

### ISSUE THREAD

**Issue by bettyzhenya** [npm/npm#15392]
I ran npm init, then ran npm test, got result like a infinite loop
> myapp@6.9.1 test C:\git\prototypes\mockServiceExamples\Nock
> npm test

> myapp@6.9.1 test C:\git\prototypes\mockServiceExamples\Nock
> npm test

> myapp@6.9.1 test C:\git\prototypes\mockServiceExamples\Nock
> npm test

**Comment by KenanY** [comment]
@bettyzhenya Well, what's your `npm test` script look like?

**Comment by bettyzhenya** [comment]
Hi Kenan
var nock = require('nock');
var couchdb = nock('http://myapp.iriscouch.com')
                .get('/users/1')
                .reply(200, {
                  _id: '123ABC',
                  _rev: '946B7D1C',
                  username: 'pgte',
                  email: 'pedro.teixeira@gmail.com'
                 });

Now the error messages this time after I ran npm test:
$ npm test

> nock@9.0.2 test C:\git\prototypes\mockServiceExamples\Nock
> tap --harmony ./tests/test_*.js

'tap' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Test failed.  See above for more details.

Regards

**Comment by KenanY** [comment]
@bettyzhenya Make sure to `npm install --save-dev tap`.

**Comment by bettyzhenya** [comment]
Thanks ! how about this error message:
[‎1/‎4/‎2017 3:57 PM] Betty Lee:
No Title
[‎1/‎4/‎2017 3:46 PM] Betty Lee:
Hi Bryan, are you familiar with npm command?
Betty.Lee@SD-HP-36WD MINGW64 /c/git/prototypes/mockServiceExamples/nock/node_modules (feature/EFCW-320-investigate-mock-services-for-testing)
$ npm test

> nock-test@1.0.0 test C:\git\prototypes\mockServiceExamples\nock


 Betty.Lee@SD-HP-36WD MINGW64 /c/git/prototypes/mockServiceExamples/nock/node_modules (feature/EFCW-320-investigate-mock-services-for-testing)
$ npm test

> nock-test@1.0.0 test C:\git\prototypes\mockServiceExamples\nock
> ./node_modules/mocha/bin/mocha

'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Test failed.  See above for more details.
[‎1/‎4/‎2017 3:47 PM] Betty Lee:
and my script is :
{
  "name": "nock-test",
  "version": "1.0.0",
  "description": "",
  "main": "my_test.js",
  "dependencies": {
    "nock": "^9.0.2",
    "superagent": "^3.3.1"
  },
  "devDependencies": {
    "chai": "^3.5.0",
    "mocha": "^3.2.0",
    "nock": "^9.0.2"
  },
  "scripts": {
    "test": "./node_modules/mocha/bin/mocha"
  },
  "author": "",
  "license": "ISC"
}

**Comment by KenanY** [comment]
@bettyzhenya Change the `"test"` script to just `"mocha"`.
