### ISSUE TITLE
npm search sass [error code E200]

### ISSUE THREAD

**Issue by hukaibaihu** [npm/npm#15396]
- `npm -search sass` prints:

npm WARN Building the local index for the first time, please be patient
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "search" "sass"
npm ERR! node v7.3.0
npm ERR! npm  v3.10.10
npm ERR! code E200

npm ERR! true true: -/all
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     E:\fullstack\vue\eleme\src\components\ratings\npm-debug.log

- npm-debug.log:

0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'search',
1 verbose cli   'sass' ]
2 info using npm@3.10.10
3 info using node@v7.3.0
4 silly mapToRegistry name -/all
5 silly mapToRegistry using default registry
6 silly mapToRegistry registry https://registry.cnpmjs.org/
7 silly mapToRegistry data Result {
7 silly mapToRegistry   raw: '-/all',
7 silly mapToRegistry   scope: null,
7 silly mapToRegistry   escapedName: null,
7 silly mapToRegistry   name: null,
7 silly mapToRegistry   rawSpec: '-/all',
7 silly mapToRegistry   spec: '-/all',
7 silly mapToRegistry   type: 'local' }
8 silly mapToRegistry uri https://registry.cnpmjs.org/-/all
9 info updateIndex D:\Program Files\npm\npm-cache\registry.cnpmjs.org\-\all\.cache.json
10 verbose correctMkdir D:\Program Files\npm\npm-cache correctMkdir not in flight; initializing
11 warn Building the local index for the first time, please be patient
12 silly update-index fetching https://registry.cnpmjs.org/-/all
13 verbose request uri https://registry.cnpmjs.org/-/all
14 verbose request no auth needed
15 info attempt registry request try #1 at 14:18:36
16 verbose request id aa573130cd3ff77d
17 http request GET https://registry.cnpmjs.org/-/all
18 http 200 https://registry.cnpmjs.org/-/all
19 verbose headers { server: 'nginx/1.4.6 (Ubuntu)',
19 verbose headers   date: 'Thu, 05 Jan 2017 06:18:40 GMT',
19 verbose headers   'content-type': 'application/json; charset=utf-8',
19 verbose headers   'transfer-encoding': 'chunked',
19 verbose headers   connection: 'keep-alive',
19 verbose headers   'x-current-requests': '1',
19 verbose headers   'x-readtime': '3335',
19 verbose headers   'strict-transport-security': 'max-age=15768000',
19 verbose headers   'content-encoding': 'gzip' }
20 verbose stack Error: true true: -/all
20 verbose stack     at makeError (D:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:302:12)
20 verbose stack     at CachingRegistryClient.<anonymous> (D:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:290:14)
20 verbose stack     at D:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:216:7
20 verbose stack     at Gunzip.onEnd (zlib.js:213:5)
20 verbose stack     at emitNone (events.js:91:20)
20 verbose stack     at Gunzip.emit (events.js:185:7)
20 verbose stack     at endReadableNT (_stream_readable.js:974:12)
20 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:74:11)
20 verbose stack     at process._tickCallback (internal/process/next_tick.js:98:9)
21 verbose statusCode 200
22 verbose cwd E:\fullstack\vue\eleme\src\components\ratings
23 error Windows_NT 6.1.7601
24 error argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "search" "sass"
25 error node v7.3.0
26 error npm  v3.10.10
27 error code E200
28 error true true: -/all
29 error If you need help, you may report this error at:
29 error     <https://github.com/npm/npm/issues>
30 verbose exit [ 1, true ]

**Comment by Charlotteis** [comment]
Search has been fixed in npm v4
Please update to the latest version of npm!

```
npm install -g npm@latest
```

🌸

**Comment by KenanY** [comment]
What @Charlotteis said :)
