### ISSUE TITLE
Use the `--scripts-prepend-node-path` option to include the path 

### ISSUE THREAD

**Issue by karthik22feb** [npm/npm#15398]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
i get the following error message when trying to run "npm install --production" command,

$ /web/software/npm-latest/bin/npm install --production
npm WARN lifecycle npm is using /web/software/NodeJS/bin/node but there is no node binary in the current PATH. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> ghost@0.11.3 preinstall /web/sites/catalog/home/ghost
> node core/server/utils/npm/preinstall.js

sh: node: command not found

npm ERR! Linux 2.6.18-409.0.0.0.1.el5
npm ERR! argv "/web/software/NodeJS/bin/node" "/web/software/npm-latest/bin/npm-cli.js" "install" "--production"
npm ERR! node v6.9.2
npm ERR! npm  v4.1.1
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! ghost@0.11.3 preinstall: `node core/server/utils/npm/preinstall.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the ghost@0.11.3 preinstall script 'node core/server/utils/npm/preinstall.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ghost package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node core/server/utils/npm/preinstall.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ghost
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ghost
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /web/sites/catalog/home/ghost/npm-debug.log

### supporting information:

 - `npm -v` prints:v4.1.1
 - `node -v` prints:v6.9.2
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:  Linux
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by eonlepapillon** [comment]
I can confirm @karthik22feb error. I have got the same configuration.

Special to my issue is that I start my npm command (a command like `npm run build`) from IntelliJ.
1. IntelliJ started from the menu. Running npm command will FAILS.
2. IntelliJ started from a terminal. Running npm command is SUCCESSFUL.

It's depending on the linux PATH. In the second setting IntelliJ get's node from the linux PATH.

**Comment by karthik-22feb** [comment]
Any solution to fix this issue ???

**Comment by legodude17** [comment]
Try using `--scripts-prepend-node-path`.

**Comment by eonlepapillon** [comment]
That doesn't work for me. At the end I made a symbolic link from the version installed in my home directory to /usr/bin/ and that worked. IntelliJ found the correct path to node!

A but it's sad solution cause I need to do that every time I install another version. If there is a better way please let me know.


The command I used was:
```bash
sudo ln -s ~/.nvm/versions/node/v6.9.3/bin/node /usr/bin/node
```

**Comment by iraklisg** [comment]
@eonlepapillon try use the solution provided by @addaleax here #14372 

`npm config set scripts-prepend-node-path true`

**Comment by yosraa** [comment]
npm config set scripts-prepend-node-path true
