### ISSUE TITLE
npm install postcss [ npm ERR! cb() never called! ]

### ISSUE THREAD

**Issue by zhangping2014** [npm/npm#15395]
node: v5.9.1
npm: 3.7.3
npm install postcss
npm ERR! cb() never called!

how can i fixed it.

**Comment by watilde** [comment]
Hi, could you please tell us more about the detail, like your `npm-debug.log`?

**Comment by seanmclucas** [comment]
I'm having the same issue with the latest npm:

```
npm 4.0.5
node v5.9.0
```

**Comment by seanmclucas** [comment]
Looks like it is related to autoprefixer: https://github.com/npm/npm/issues/15344

**Comment by Arttse** [comment]
This error occurs in Node.js `5.9.0` and `5.9.1`. The only obvious solution is to upgrade to Node.js `5.10.0` and newer, which it works.

**Comment by zhangping2014** [comment]
got it
