### ISSUE TITLE
MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by Judy1987Liu** [npm/npm#15399]
#### I'm opening this issue because: 
MODULE_NOT_FOUND

[log.docx](https://github.com/npm/npm/files/686654/log.docx)

#### What's going wrong?
can not install
### supporting information:

 - `npm -v` prints:4.0.5
 - `node -v` prints: v7.4.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:

   - [ ] I develop using Vagrant on OS X or Linux.

**Comment by watilde** [comment]
It seems to be related to Node.js. Could you please try this solution?
https://github.com/nodejs/node/issues/3540
