### ISSUE TITLE
Can install nodejs

### ISSUE THREAD

**Issue by cmerli** [npm/npm#15408]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [X] Other (_see below for feature requests_):

#### What's going wrong?
Whenever I run the command "sudo npm i -g npm" it gives me "npm ERR!", with "connect EHOSTUNREACH 151.101.52.162:443".

#### How can the CLI team reproduce the problem?
I am not sure you can, it seems to be happening only on my machine. The guess is some network issue. I am running Ubuntu 16.04 and I can't even reach "https://registry.npmjs.org/", but my coworker can in Windows.

### supporting information:

 - `npm -v` prints: 3.5.2
 - `node -v` prints: v4.2.6
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux - Ubuntu 16.04.1
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [X] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by Charlotteis** [comment]
Are you behind a proxy? If so, it's like your coworkers know how to set your npm up to work behind your proxy. This article might help: https://jjasonclark.com/how-to-setup-node-behind-web-proxy/

🌸

**Comment by KenanY** [comment]
Closing as abandoned.
