### ISSUE TITLE
npm i -g react-native-cli

### ISSUE THREAD

**Issue by gitfdy** [npm/npm#15401]
npm WARN skippingAction Module is inside a symlinked module: not running remove ansi-styles@2.2.1 node_modules/react-native-cli/node_modules/chalk/node_modules/ansi-styles
npm WARN skippingAction Module is inside a symlinked module: not running remove escape-string-regexp@1.0.5 node_modules/react-native-cli/node_modules/chalk/node_modules/escape-string-regexp
npm WARN skippingAction Module is inside a symlinked module: not running remove has-ansi@2.0.0 node_modules/react-native-cli/node_modules/chalk/node_modules/has-ansi
npm WARN skippingAction Module is inside a symlinked module: not running remove strip-ansi@3.0.1 node_modules/react-native-cli/node_modules/chalk/node_modules/strip-ansi
npm WARN skippingAction Module is inside a symlinked module: not running remove supports-color@2.0.0 node_modules/react-native-cli/node_modules/chalk/node_modules/supports-color
npm WARN skippingAction Module is inside a symlinked module: not running update chalk@1.1.3 node_modules/react-native-cli/node_modules/chalk
npm WARN skippingAction Module is inside a symlinked module: not running update mute-stream@0.0.7 node_modules/react-native-cli/node_modules/mute-stream
npm WARN skippingAction Module is inside a symlinked module: not running remove pkginfo@0.4.0 node_modules/react-native-cli/node_modules/prompt/node_modules/pkginfo
npm WARN skippingAction Module is inside a symlinked module: not running remove read@1.0.7 node_modules/react-native-cli/node_modules/prompt/node_modules/read
npm WARN skippingAction Module is inside a symlinked module: not running remove revalidator@0.1.8 node_modules/react-native-cli/node_modules/prompt/node_modules/revalidator
npm WARN skippingAction Module is inside a symlinked module: not running remove utile@0.2.1 node_modules/react-native-cli/node_modules/prompt/node_modules/utile
npm WARN skippingAction Module is inside a symlinked module: not running remove winston@0.8.3 node_modules/react-native-cli/node_modules/prompt/node_modules/winston
npm WARN skippingAction Module is inside a symlinked module: not running update prompt@0.2.14 node_modules/react-native-cli/node_modules/prompt
npm WARN skippingAction Module is inside a symlinked module: not running update semver@5.3.0 node_modules/react-native-cli/node_modules/semver
npm WARN update-linked node_modules/react-native-cli needs updating to 2.0.1 from 0.1.10 but we can't, as it's a symlink
fandongyangdeMacBook-Pro:~ fandongyang$ npm i -g react-native-cli
npm WARN skippingAction Module is inside a symlinked module: not running remove ansi-styles@2.2.1 node_modules/react-native-cli/node_modules/chalk/node_modules/ansi-styles
npm WARN skippingAction Module is inside a symlinked module: not running remove escape-string-regexp@1.0.5 node_modules/react-native-cli/node_modules/chalk/node_modules/escape-string-regexp
npm WARN skippingAction Module is inside a symlinked module: not running remove has-ansi@2.0.0 node_modules/react-native-cli/node_modules/chalk/node_modules/has-ansi
npm WARN skippingAction Module is inside a symlinked module: not running remove strip-ansi@3.0.1 node_modules/react-native-cli/node_modules/chalk/node_modules/strip-ansi
npm WARN skippingAction Module is inside a symlinked module: not running remove supports-color@2.0.0 node_modules/react-native-cli/node_modules/chalk/node_modules/supports-color
npm WARN skippingAction Module is inside a symlinked module: not running update chalk@1.1.3 node_modules/react-native-cli/node_modules/chalk
npm WARN skippingAction Module is inside a symlinked module: not running update mute-stream@0.0.7 node_modules/react-native-cli/node_modules/mute-stream
npm WARN skippingAction Module is inside a symlinked module: not running remove pkginfo@0.4.0 node_modules/react-native-cli/node_modules/prompt/node_modules/pkginfo
npm WARN skippingAction Module is inside a symlinked module: not running remove read@1.0.7 node_modules/react-native-cli/node_modules/prompt/node_modules/read
npm WARN skippingAction Module is inside a symlinked module: not running remove revalidator@0.1.8 node_modules/react-native-cli/node_modules/prompt/node_modules/revalidator
npm WARN skippingAction Module is inside a symlinked module: not running remove utile@0.2.1 node_modules/react-native-cli/node_modules/prompt/node_modules/utile
npm WARN skippingAction Module is inside a symlinked module: not running remove winston@0.8.3 node_modules/react-native-cli/node_modules/prompt/node_modules/winston
npm WARN skippingAction Module is inside a symlinked module: not running update prompt@0.2.14 node_modules/react-native-cli/node_modules/prompt
npm WARN skippingAction Module is inside a symlinked module: not running update semver@5.3.0 node_modules/react-native-cli/node_modules/semver
npm WARN update-linked node_modules/react-native-cli needs updating to 2.0.1 from 0.1.10 but we can't, as it's a symlink

**Comment by Charlotteis** [comment]
Hi @gitfdy, could you post the full `npm-debug.log`, your error is not actually captured above. Those are just WARNings. Could you also describe the problem thats occuring?

Thanks! 🌸

**Comment by KenanY** [comment]
Closing as abandoned.
