### ISSUE TITLE
[Bug/Feature Request] "npm preinstall" runs after module installation (please read, addresses specific issues)

### ISSUE THREAD

**Issue by skhameneh-sabre** [npm/npm#15404]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?

I need to be able to set proxies for a local git repo for module installation to succeed.
It addition, some [external, npm] dependencies fail on compilation if certain toolchains are not present; the errors are "ugly" and confuse team members.  I would like a preinstall script to validate their environment for them.
With previous requests, such needs what not specifically addressed.

#### How can the CLI team reproduce the problem?

Create a preinstall script, and run "npm install"

### supporting information:

Applies to all supported versions of node; this bug/feature has been a topic of concern many times.

#### What's the feature?

Add support for a "preinstall" that runs before dependency installation.

#### What problem is the feature intended to solve?

Environment validation, proxy validation.

#### Is the absence of this feature blocking you or your team? If so, how?

Yes, it makes envrionment setup and environment debugging much more complicated.

#### Is this feature similar to an existing feature in another tool?

Yes, related to "preinstall".

#### Is this a feature you're prepared to implement, with support from the npm CLI team?

Yes, I'll happily make any requested changes to "npm" sources.

**Comment by noherczeg** [comment]
They said it's fixed in 3.10.9
