### ISSUE TITLE
`npm search` No search sources available

### ISSUE THREAD

**Issue by max-b** [npm/npm#15406]
#### I'm opening this issue because:

  - [X ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
`npm search node-sass` produces the following:
```
npm WARN Failed to read search cache. Rebuilding
npm WARN Building the local index for the first time, please be patient
npm WARN all-package-metadata entry-update-stream Empty or invalid stream
npm ERR! Linux 4.8.0-32-generic
npm ERR! argv "/home/maxb/.nvm/versions/node/v6.9.2/bin/node" "/home/maxb/.nvm/versions/node/v6.9.2/bin/npm" "search" "node-sass"
npm ERR! node v6.9.2
npm ERR! npm  v4.0.5

npm ERR! No search sources available
npm ERR! 
```

#### How can the CLI team reproduce the problem?
I used nvm to install and manage node/npm versions. May be relevant here. I've also not run `npm adduser` and I do not have a `.npm` file in my home directory. No step during the install of node/npm with nvm caused that to happen. 

npm-debug.log
https://gist.github.com/max-b/2a4b8f41e67b93fb5d16620150aa573f

`npm config list -l`:
https://gist.github.com/max-b/c425f45f7bbd381e582215111c1eb16b

### supporting information:

 - `npm -v` prints: 4.0.5
 - `node -v` prints: v6.9.2
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux Ubuntu 16.10
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by max-b** [comment]
Running `npm adduser` and logging in w/ my user account fixed the problem. I'm not sure if this is expected, so I guess I'll leave this open for a dev to make that call.

**Comment by yangnw** [comment]
I second the error. Command:
`npm search prettify`

Here's the npm-debug.log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/7.2.1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'search',
1 verbose cli   'prettify' ]
2 info using npm@4.0.5
3 info using node@v7.2.1
4 silly mapToRegistry name -/all
5 silly mapToRegistry using default registry
6 silly mapToRegistry registry https://registry.npmjs.org/
7 silly mapToRegistry data Result {
7 silly mapToRegistry   raw: '-/all',
7 silly mapToRegistry   scope: null,
7 silly mapToRegistry   escapedName: null,
7 silly mapToRegistry   name: null,
7 silly mapToRegistry   rawSpec: '-/all',
7 silly mapToRegistry   spec: '-/all',
7 silly mapToRegistry   type: 'local' }
8 silly mapToRegistry uri https://registry.npmjs.org/-/all
9 verbose all-package-metadata creating entry stream from local cache
10 verbose all-package-metadata /Users/Yang/.npm/registry.npmjs.org/-/all/.cache.json
11 silly search searching packages
12 warn Failed to read search cache. Rebuilding
13 silly all-package-metadata Error: ENOENT: no such file or directory, stat '/Users/Yang/.npm/registry.npmjs.org/-/all/.cache.json'
13 silly all-package-metadata  cache read error:  { Error: ENOENT: no such file or directory, stat '/Users/Yang/.npm/registry.npmjs.org/-/all/.cache.json'
13 silly all-package-metadata   errno: -2,
13 silly all-package-metadata   code: 'ENOENT',
13 silly all-package-metadata   syscall: 'stat',
13 silly all-package-metadata   path: '/Users/Yang/.npm/registry.npmjs.org/-/all/.cache.json' }
14 verbose all-package-metadata creating remote entry stream
15 warn Building the local index for the first time, please be patient
16 verbose all-package-metadata No cached data: requesting full metadata db
17 verbose request uri https://registry.npmjs.org/-/all
18 verbose request no auth needed
19 info attempt registry request try #1 at 1:32:46 AM
20 verbose request id 79f30b773a620a89
21 http request GET https://registry.npmjs.org/-/all
22 silly all-package-metadata request stream opened, code: 200
23 silly all-package-metadata extracting latest
24 warn all-package-metadata entry-update-stream Empty or invalid stream
25 verbose stack Error: No search sources available
25 verbose stack     at /usr/local/lib/node_modules/npm/lib/search/all-package-metadata.js:71:19
25 verbose stack     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)
25 verbose stack     at Pumpify.<anonymous> (/usr/local/lib/node_modules/npm/lib/search/all-package-metadata.js:184:7)
25 verbose stack     at emitNone (events.js:91:20)
25 verbose stack     at Pumpify.emit (events.js:185:7)
25 verbose stack     at endReadableNT (/usr/local/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_readable.js:926:12)
25 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:74:11)
25 verbose stack     at process._tickCallback (internal/process/next_tick.js:98:9)
26 verbose cwd /Users/Yang/Developer/repository/pyfolio/apidocs/_build/html
27 error Darwin 16.3.0
28 error argv "/usr/local/Cellar/node/7.2.1/bin/node" "/usr/local/bin/npm" "search" "prettify"
29 error node v7.2.1
30 error npm  v4.0.5
31 error No search sources available
32 error If you need help, you may report this error at:
32 error     <https://github.com/npm/npm/issues>
33 verbose exit [ 1, true ]
```

Some interesting facts:
- Before upgrading to npm@4, it produces error `code E200`
- Then I upgraded to npm@4 and now the said command works, but
- If I switch to a secondary source, it produces error `No search sources available`
- If I run the command through a proxy, it produces error `No search sources available`

**Comment by yangnw** [comment]
Also, by secondary source I mean etc. http://r.cnpmjs.org/ since I live in China. The official repository is notoriously slow due to GFW. The proxy itself is confirmed to work in all cases.

**Comment by legodude17** [comment]
Maybe http://r.cnpmjs.org/ doesn't implement the search enpoint?

**Comment by yangnw** [comment]
@legodude17 Possible. But
- `npm search` on the official npm registry through a proxy was throwing the error too, while not using a proxy doesn't.
- After removing all globally install npm packages except npm itself, using the proxy works find now.
Hope it helps.

**Comment by flekschas** [comment]
Any updates? I am running into the same problem after updating to `v4.1.2` (with node `v6.9.5` on Mac `v10.11.6`).

**Comment by prg** [comment]
@flekschas I ran into that problem, too. Went to lunch, now it's working. I guess the npm registry was broken somehow?

**Comment by flekschas** [comment]
@prg Yeah, I was able to fix it _somehow_ by cleaning the cache 2 times and removing the debug log. (see here: https://github.com/npm/npm/issues/14649#issuecomment-262822674). Something seems to be buggy.

**Comment by legodude17** [comment]
Well, the cached search data is stored in the cache, so maybe that file was broken in some way?

**Comment by rawbin-** [comment]
npm 5.0.1 with the same problem

**Comment by legodude17** [comment]
`npm-debug.log`?
