### ISSUE TITLE
Server&user can access registry.npmjs.org, but npm cannot find it.

### ISSUE THREAD

**Issue by ryancmoon** [npm/npm#15403]
npm cannot seem to find http(s)://registry.npmjs.org on a fresh build. OS is Ubuntu 16.04.1 LTS, this system is not subject to a proxy.

`$ npm install  `
`  npm ERR! Linux 3.13.0-106-generic  `
`  npm ERR! argv "/home/www-data/src/node-v7.4.0/bin/node" "/usr/local/bin/npm" "install"  `
`  npm ERR! node v7.4.0  `
`  npm ERR! npm  v4.0.5  `
`  npm ERR! code ENOTFOUND `
`  npm ERR! errno ENOTFOUND `
`  npm ERR! syscall getaddrinfo   `
`  npm ERR! network getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443  `
`  npm ERR! network This is most likely not a problem with npm itself  `
`  npm ERR! network and is related to network connectivity.  `
`  npm ERR! network In most cases you are behind a proxy or have bad network settings.  `
`  npm ERR! network  `
`  npm ERR! network If you are behind a proxy, please make sure that the  `
`  npm ERR! network 'proxy' config is set properly.  See: 'npm help config'  `
`  `  
`  npm ERR! Please include the following file with any support request:  `
`  npm ERR!     /root/test/npm-debug.log  `

However, I can connect to registry.npmjs.org on 443 or 80 just fine as that user on that server:
`$ telnet registry.npmjs.org 443`
`Trying 151.101.56.162...`
`Connected to a.sni.fastly.net.`
`Escape character is '^]'.`

Node-Debug log attached, looks like a dns issue:
[node-debug.txt](https://github.com/npm/npm/files/687708/node-debug.txt)

`308 silly fetchPackageMetaData Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443 `
`308 silly fetchPackageMetaData     at errnoException (dns.js:28:10) `
`308 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26) `
`308 silly fetchPackageMetaData  error for bcrypt@^1.0.1 { Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443 `
`308 silly fetchPackageMetaData     at errnoException (dns.js:28:10) `
`308 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26) `
`308 silly fetchPackageMetaData   code: 'ENOTFOUND', `
`308 silly fetchPackageMetaData   errno: 'ENOTFOUND', `
`308 silly fetchPackageMetaData   syscall: 'getaddrinfo', `
`308 silly fetchPackageMetaData   hostname: 'registry.npmjs.org', `
`308 silly fetchPackageMetaData   host: 'registry.npmjs.org', `
`308 silly fetchPackageMetaData   port: 443 } ` 

However it is resolvable locally:
`$ dig registry.npmjs.org +short `
`a.sni.fastly.net. `
`151.101.56.162 `

I have also tried node from source on 6.9.3 and 6.9.0 LTS, same issue.

========================================================
Found the issue, I compiled node w/ the --fully-static flag. This breaks npm, reference: https://github.com/nodejs/node/issues/5298

* closing issue.

**Comment by JohnOmernik** [comment]
+1

**Comment by muddafugga** [comment]
+1

**Comment by ryancmoon** [comment]
Found the issue, I compiled node w/ the --fully-static flag. This breaks npm, reference: nodejs/node#5298

closing issue.
