### ISSUE TITLE
while following http://learn.mean.io/ i got this error

### ISSUE THREAD

**Issue by shubham-jindal** [npm/npm#15407]
shubham@shubham-HP-Pavilion-Notebook:~$ cd masss && npm install

npm ERR! git clone --template=/home/shubham/.npm/_git-remotes/_templates --mirror git://github.com/linnovate/meanio-admin.git /home/shubham/.npm/_git-remotes/git-github-com-linnovate-meanio-admin-git-c6a4aa0a: Cloning into bare repository '/home/shubham/.npm/_git-remotes/git-github-com-linnovate-meanio-admin-git-c6a4aa0a'...
npm ERR! git clone --template=/home/shubham/.npm/_git-remotes/_templates --mirror git://github.com/linnovate/meanio-admin.git /home/shubham/.npm/_git-remotes/git-github-com-linnovate-meanio-admin-git-c6a4aa0a: fatal: unable to connect to github.com:
npm ERR! git clone --template=/home/shubham/.npm/_git-remotes/_templates --mirror git://github.com/linnovate/meanio-admin.git /home/shubham/.npm/_git-remotes/git-github-com-linnovate-meanio-admin-git-c6a4aa0a: github.com: Temporary failure in name resolution
npm ERR! git clone --template=/home/shubham/.npm/_git-remotes/_templates --mirror git://github.com/linnovate/meanio-users.git /home/shubham/.npm/_git-remotes/git-github-com-linnovate-meanio-users-git-1bd3f051: Cloning into bare repository '/home/shubham/.npm/_git-remotes/git-github-com-linnovate-meanio-users-git-1bd3f051'...
npm ERR! git clone --template=/home/shubham/.npm/_git-remotes/_templates --mirror git://github.com/linnovate/meanio-users.git /home/shubham/.npm/_git-remotes/git-github-com-linnovate-meanio-users-git-1bd3f051: fatal: unable to connect to github.com:
npm ERR! git clone --template=/home/shubham/.npm/_git-remotes/_templates --mirror git://github.com/linnovate/meanio-users.git /home/shubham/.npm/_git-remotes/git-github-com-linnovate-meanio-users-git-1bd3f051: github.com: Temporary failure in name resolution
npm ERR! git clone --template=/home/shubham/.npm/_git-remotes/_templates --mirror git://github.com/linnovate/meanio-system.git /home/shubham/.npm/_git-remotes/git-github-com-linnovate-meanio-system-git-3089ab17: Cloning into bare repository '/home/shubham/.npm/_git-remotes/git-github-com-linnovate-meanio-system-git-3089ab17'...
npm ERR! git clone --template=/home/shubham/.npm/_git-remotes/_templates --mirror git://github.com/linnovate/meanio-system.git /home/shubham/.npm/_git-remotes/git-github-com-linnovate-meanio-system-git-3089ab17: fatal: unable to connect to github.com:
npm ERR! git clone --template=/home/shubham/.npm/_git-remotes/_templates --mirror git://github.com/linnovate/meanio-system.git /home/shubham/.npm/_git-remotes/git-github-com-linnovate-meanio-system-git-3089ab17: github.com: Temporary failure in name resolution
npm ERR! git clone --template=/home/shubham/.npm/_git-remotes/_templates --mirror git://github.com/linnovate/meanio-circles.git /home/shubham/.npm/_git-remotes/git-github-com-linnovate-meanio-circles-git-0d05aca1: Cloning into bare repository '/home/shubham/.npm/_git-remotes/git-github-com-linnovate-meanio-circles-git-0d05aca1'...
npm ERR! git clone --template=/home/shubham/.npm/_git-remotes/_templates --mirror git://github.com/linnovate/meanio-circles.git /home/shubham/.npm/_git-remotes/git-github-com-linnovate-meanio-circles-git-0d05aca1: fatal: unable to connect to github.com:
npm ERR! git clone --template=/home/shubham/.npm/_git-remotes/_templates --mirror git://github.com/linnovate/meanio-circles.git /home/shubham/.npm/_git-remotes/git-github-com-linnovate-meanio-circles-git-0d05aca1: github.com: Temporary failure in name resolution
npm ERR! Linux 4.4.0-51-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.7.1
npm ERR! npm  v4.0.5
npm ERR! code 128

npm ERR! Command failed: git clone --template=/home/shubham/.npm/_git-remotes/_templates --mirror git://github.com/linnovate/meanio-admin.git /home/shubham/.npm/_git-remotes/git-github-com-linnovate-meanio-admin-git-c6a4aa0a
npm ERR! Cloning into bare repository '/home/shubham/.npm/_git-remotes/git-github-com-linnovate-meanio-admin-git-c6a4aa0a'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com: Temporary failure in name resolution
npm ERR! 
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/shubham/masss/npm-debug.log

**Comment by legodude17** [comment]
Please check your internet connection.

**Comment by KenanY** [comment]
Closing as abandoned.
