### ISSUE TITLE
cordova ionic instalation issue

### ISSUE THREAD

**Issue by ramum16** [npm/npm#15412]
#### I'm opening this issue because: npm install -g cordova ionic command giving bellow error

 npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cor
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! syscall getaddrinfo

npm ERR! network getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Windows\system32\npm-debug.log

Can some one help me to install cordova and ionic.
Thanks.

**Comment by Charlotteis** [comment]
Are you behind a proxy? If so make sure it's set up correctly: https://jjasonclark.com/how-to-setup-node-behind-web-proxy/

**Comment by KenanY** [comment]
Closing as abandoned.
