### ISSUE TITLE
Can't Install Ionic. I am trying all solution but can't get solution. Please need help

### ISSUE THREAD

**Issue by prabir2015** [npm/npm#15419]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Prabir\\AppData\\Roaming\\npm\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'ionic' ]
2 info using npm@3.10.10
3 info using node@v6.9.2
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData ionic
8 silly fetchNamedPackageData ionic
9 silly mapToRegistry name ionic
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry http://registry.npms.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'ionic',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'ionic',
12 silly mapToRegistry   name: 'ionic',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri http://registry.npms.org/ionic
14 verbose request uri http://registry.npms.org/ionic
15 verbose request no auth needed
16 info attempt registry request try #1 at 2:31:32 AM
17 verbose request id 34d668ff8484b8d4
18 http request GET http://registry.npms.org/ionic
19 info retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND host host:8000
20 info attempt registry request try #2 at 2:31:45 AM
21 http request GET http://registry.npms.org/ionic
22 info retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND host host:8000
23 info attempt registry request try #3 at 2:32:47 AM
24 http request GET http://registry.npms.org/ionic
25 silly fetchPackageMetaData Error: getaddrinfo ENOTFOUND host host:8000
25 silly fetchPackageMetaData     at errnoException (dns.js:28:10)
25 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
25 silly fetchPackageMetaData  error for ionic { Error: getaddrinfo ENOTFOUND host host:8000
25 silly fetchPackageMetaData     at errnoException (dns.js:28:10)
25 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
25 silly fetchPackageMetaData   code: 'ENOTFOUND',
25 silly fetchPackageMetaData   errno: 'ENOTFOUND',
25 silly fetchPackageMetaData   syscall: 'getaddrinfo',
25 silly fetchPackageMetaData   hostname: 'host',
25 silly fetchPackageMetaData   host: 'host',
25 silly fetchPackageMetaData   port: '8000' }
26 silly rollbackFailedOptional Starting
27 silly rollbackFailedOptional Finishing
28 silly runTopLevelLifecycles Finishing
29 silly install printInstalled
30 verbose stack Error: getaddrinfo ENOTFOUND host host:8000
30 verbose stack     at errnoException (dns.js:28:10)
30 verbose stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
31 verbose cwd F:\ionic
32 error Windows_NT 6.1.7601
33 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Prabir\\AppData\\Roaming\\npm\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ionic"
34 error node v6.9.2
35 error npm  v3.10.10
36 error code ENOTFOUND
37 error errno ENOTFOUND
38 error syscall getaddrinfo
39 error network getaddrinfo ENOTFOUND host host:8000
40 error network This is most likely not a problem with npm itself
40 error network and is related to network connectivity.
40 error network In most cases you are behind a proxy or have bad network settings.
40 error network
40 error network If you are behind a proxy, please make sure that the
40 error network 'proxy' config is set properly.  See: 'npm help config'
41 verbose exit [ 1, true ]

**Comment by legodude17** [comment]
Please check your internet connection.
What are the results of:
1. `npm config get registry`
2. `npm config get http-proxy`
3. `npm config get https-proxy`
