### ISSUE TITLE
certificate has expired

### ISSUE THREAD

**Issue by selfagency** [npm/npm#15416]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [X] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

output npm ERR! Linux 3.10.0-327.10.1.el7.x86_64
output npm ERR! argv "/root/.nvm/versions/node/v5.12.0/bin/node" "/root/.nvm/versions/node/v5.12.0/bin/npm" "install"
output npm ERR! node v5.12.0
output npm ERR! npm v3.8.6
output npm ERR! code CERT_HAS_EXPIRED
output npm ERR! certificate has expired
output npm ERR!
output npm ERR! If you need help, you may report this error at:
output npm ERR! <https://github.com/npm/npm/issues>
output npm ERR! Please include the following file with any support request:
output npm ERR! /source/npm-debug.log

#### How can the CLI team reproduce the problem?

install node 5.12.0 and install an npm package

### supporting information:

 - `npm -v` prints: npm v3.8.6
 - `node -v` prints: node v5.12.0
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?: Linux 3.10.0-327.10.1.el7.x86_64
 - Network issues:
   - Geographic location where npm was run: U.S.
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container: Elastic Beanstalk
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by ellotheth** [comment]
I'm seeing the same thing inside a Docker container (Debian 8, in Chicago on scnet.net). It looks a lot like the issue in #7941.

```
$ npm install --no-progress --depth 0 --loglevel verbose
npm info it worked if it ends with ok
npm verb cli [ '/usr/bin/nodejs',
npm verb cli '/usr/bin/npm',
npm verb cli 'install',
npm verb cli '--no-progress',
npm verb cli '--depth',
npm verb cli '0',
npm verb cli '--loglevel',
npm verb cli 'verbose' ]
npm info using npm@3.10.8
npm info using node@v4.4.7
npm verb request uri https://registry.npmjs.org/remarkable
npm verb request no auth needed
npm info attempt registry request try #1 at 11:23:03 PM
npm verb request id 71f544f1a41675f4
npm ;40mhttp request GET https://registry.npmjs.org/remarkable
npm info retry will retry, error on last attempt: Error: certificate has expired
npm info attempt registry request try #2 at 11:23:13 PM
npm ;40mhttp request GET https://registry.npmjs.org/remarkable
npm info retry will retry, error on last attempt: Error: certificate has expired
npm info attempt registry request try #3 at 11:24:13 PM
npm ;40mhttp request GET https://registry.npmjs.org/remarkable
npm verb stack Error: certificate has expired
npm verb stack at Error (native)
npm verb stack at TLSSocket.<anonymous> (_tls_wrap.js:1017:38)
npm verb stack at emitNone (events.js:67:13)
npm verb stack at TLSSocket.emit (events.js:166:7)
npm verb stack at TLSSocket._init.ssl.onclienthello.ssl.oncertcb.TLSSocket._finishInit (_tls_wrap.js:582:8)
npm verb stack at TLSWrap.ssl.onclienthello.ssl.oncertcb.ssl.onnewsession.ssl.onhandshakedone (_tls_wrap.js:424:38)
npm verb cwd /source
npm ERR! Linux 3.10.0-327.10.1.el7.x86_64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--no-progress" "--depth" "0" "--loglevel" "verbose"
npm ERR! node v4.4.7
npm ERR! npm v3.10.8
npm ERR! code CERT_HAS_EXPIRED
npm ERR! certificate has expired
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR! <https://github.com/npm/npm/issues>
npm verb exit [ 1, true ]
npm ERR! Please include the following file with any support request:
npm ERR! /source/npm-debug.log 
```

```
$ curl -kv https://registry.npmjs.org/remarkable > /dev/null
* Hostname was NOT found in DNS cache
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0* Trying 23.235.40.162...
* Connected to registry.npmjs.org (23.235.40.162) port 443 (#0)
* successfully set certificate verify locations:
* CAfile: none
CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
} [data not shown]
* SSLv3, TLS handshake, Server hello (2):
{ [data not shown]
* SSLv3, TLS handshake, CERT (11):
{ [data not shown]
* SSLv3, TLS handshake, Server key exchange (12):
{ [data not shown]
* SSLv3, TLS handshake, Server finished (14):
{ [data not shown]
* SSLv3, TLS handshake, Client key exchange (16):
} [data not shown]
* SSLv3, TLS change cipher, Client hello (1):
} [data not shown]
* SSLv3, TLS handshake, Finished (20):
} [data not shown]
* SSLv3, TLS change cipher, Client hello (1):
{ [data not shown]
* SSLv3, TLS handshake, Finished (20):
{ [data not shown]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* Server certificate:
* subject: C=US; ST=CA; L=San Francisco; O=Joyent, Inc.; CN=nodejs.org
* start date: 2012-08-24 19:33:10 GMT
* expire date: 2014-08-25 19:33:10 GMT
* issuer: C=BE; O=GlobalSign nv-sa; CN=GlobalSign Organization Validation CA - G2
* SSL certificate verify result: certificate has expired (10), continuing anyway.
> GET /remarkable HTTP/1.1
> User-Agent: curl/7.38.0
> Host: registry.npmjs.org
> Accept: */*
>
< HTTP/1.1 200 OK
* Server nginx/1.10.1 is not blacklisted
< Server: nginx/1.10.1
< Content-Type: application/json
< Last-Modified: Sun, 27 Nov 2016 02:04:35 GMT
< ETag: "583a3f33-a7a0"
< Cache-Control: max-age=300
< Content-Length: 42912
< Accept-Ranges: bytes
< Date: Fri, 06 Jan 2017 23:23:00 GMT
< Via: 1.1 varnish
< Age: 0
< Connection: keep-alive
< X-Served-By: cache-ord1744-ORD
< X-Cache: MISS
< X-Cache-Hits: 0
< X-Timer: S1483744980.223225,VS0,VE19
< Vary: Accept-Encoding
<
{ [data not shown]
100 42912 100 42912 0 0 1039k 0 --:--:-- --:--:-- --:--:-- 1047k
* Connection #0 to host registry.npmjs.org left intact
```

**Comment by phips28** [comment]
get the same error

**Comment by tedlin182** [comment]
Yup same here:

```
npm ERR! fetch failed https://registry.npmjs.org/algoliasearch/-/algoliasearch-3.20.3.tgz
npm WARN retry will retry, error on last attempt: Error: certificate has expired
npm ERR! fetch failed https://registry.npmjs.org/mysql/-/mysql-2.12.0.tgz
npm WARN retry will retry, error on last attempt: Error: certificate has expired
npm ERR! fetch failed https://registry.npmjs.org/jsonfile/-/jsonfile-2.4.0.tgz
npm WARN retry will retry, error on last attempt: Error: certificate has expired
npm ERR! fetch failed https://registry.npmjs.org/jsonfile/-/jsonfile-2.4.0.tgz
npm WARN retry will retry, error on last attempt: Error: certificate has expired
npm ERR! fetch failed https://registry.npmjs.org/algoliasearch/-/algoliasearch-3.20.3.tgz
npm WARN retry will retry, error on last attempt: Error: certificate has expired
npm ERR! fetch failed https://registry.npmjs.org/mysql/-/mysql-2.12.0.tgz
npm WARN retry will retry, error on last attempt: Error: certificate has expired
npm ERR! fetch failed https://registry.npmjs.org/jsonfile/-/jsonfile-2.4.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/mysql/-/mysql-2.12.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/algoliasearch/-/algoliasearch-3.20.3.tgz
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.8
npm ERR! code CERT_HAS_EXPIRED

npm ERR! certificate has expired
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

**Comment by pawadrdk** [comment]
same error
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'login' ]
2 info using npm@3.8.9
3 info using node@v6.2.0
4 verbose adduser before first PUT { _id: 'org.couchdb.user:pawa',
4 verbose adduser   name: 'pawa',
4 verbose adduser   password: 'XXXXX',
4 verbose adduser   email: 'psw_60@msn.com',
4 verbose adduser   type: 'user',
4 verbose adduser   roles: [],
4 verbose adduser   date: '2017-01-10T08:22:12.998Z' }
5 verbose request uri https://registry.npmjs.org/-/user/org.couchdb.user:pawa
6 verbose request new user, so can't send auth
7 info attempt registry request try #1 at 09:22:13
8 verbose request id 383aa46a2c821e7e
9 http request PUT https://registry.npmjs.org/-/user/org.couchdb.user:pawa
10 info retry will retry, error on last attempt: Error: certificate has expired
11 info attempt registry request try #2 at 09:22:23
12 http request PUT https://registry.npmjs.org/-/user/org.couchdb.user:pawa
13 info retry will retry, error on last attempt: Error: certificate has expired
14 info attempt registry request try #3 at 09:23:23
15 http request PUT https://registry.npmjs.org/-/user/org.couchdb.user:pawa
16 verbose request invalidating C:\Users\pawa\AppData\Roaming\npm-cache\registry.npmjs.org\-\user\org.couchdb.user_3Apawa on PUT
17 verbose adduser back [ { Error: certificate has expired
17 verbose adduser       at Error (native)
17 verbose adduser       at TLSSocket.<anonymous> (_tls_wrap.js:1055:38)
17 verbose adduser       at emitNone (events.js:86:13)
17 verbose adduser       at TLSSocket.emit (events.js:185:7)
17 verbose adduser       at TLSSocket._finishInit (_tls_wrap.js:580:8)
17 verbose adduser       at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:412:38) code: 'CERT_HAS_EXPIRED' },
17 verbose adduser   undefined,
17 verbose adduser   undefined ]
18 verbose stack Error: certificate has expired
18 verbose stack     at Error (native)
18 verbose stack     at TLSSocket.<anonymous> (_tls_wrap.js:1055:38)
18 verbose stack     at emitNone (events.js:86:13)
18 verbose stack     at TLSSocket.emit (events.js:185:7)
18 verbose stack     at TLSSocket._finishInit (_tls_wrap.js:580:8)
18 verbose stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:412:38)
19 verbose cwd C:\Users\pawa\Github\dr-tv
20 error Windows_NT 6.1.7601
21 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "login"
22 error node v6.2.0
23 error npm  v3.8.9
24 error code CERT_HAS_EXPIRED
25 error certificate has expired
26 error If you need help, you may report this error at:
26 error     <https://github.com/npm/npm/issues>
27 verbose exit [ 1, true ]

**Comment by tedlin182** [comment]
Hey everyone, I managed to figured out the issue at least with me. Might be worth checking for your cases, but apparently the IP address pointing to `registry.npmjs.org` in my `/etc/hosts` file was pointing to an outdated IP for that domain (2014 thus why the certificate expired error kept popping up).

I resolved it by just `ping registry.npmjs.org` to get the correct IP and updated it in my `/etc/hosts` file. Be sure to open up a new tab in your terminal to take the updates and `npm install` should work.

Here's the post that helped me with the issue => <http://superuser.com/questions/346518/how-do-i-refresh-the-hosts-file-on-os-x>

Hope this helps resolve at least some of you guys' issues!

**Comment by aframe82** [comment]
The above worked for me too.

The message I had was `npm ERR! code CERT_HAS_EXPIRED`

Which I fixed by:

- `ping registry.npmjs.org` to get the incorrect IP
- find and comment out that IP in my `/etc/hosts` file
- do `ping registry.npmjs.org` to get the updated IP
- add `<new ip> registry.npmjs.org` into my `/etc/hosts` file

Tried an `npm install` again, and it was now working.

**Comment by selfagency** [comment]
I am no longer experiencing this issue.

**Comment by getavinashm** [comment]
Worked for me by doing ping to get correct address for registry.npmjs.org. Then added
 <new ip> registry.npmjs.org into my /etc/hosts file

**Comment by Folyd** [comment]
please run `npm install -g npm` to upgrade your npm version. this works for me.

**Comment by Dersoncarlos** [comment]
npm config set strict-ssl false

resolvi assim..
mas alguém sabe o que realmente o problema ?
