### ISSUE TITLE
Edison XDK Daemon Install Error

### ISSUE THREAD

**Issue by andr01dm** [npm/npm#15424]
#### I'm opening this issue because:

  - [ X ] npm is producing an incorrect install.

#### What's going wrong?

I'm using the Intel XDK to install the XDK Daemon on a freshly flashed Edison connected to a Sparkfun Base Block.  (https://www.sparkfun.com/products/13045).  When the install runs it throws a slew of npm errors.  I'll include the log from the XDK:

https://gist.github.com/andr01dm/5a863b564b2ddd623f8a92a6279aa737

#### How can the CLI team reproduce the problem?

1) Connect an Intel Edison to a Sparkfun Base Block
2) Flash the Edison to the latest Yocto: https://software.intel.com/en-us/iot/hardware/edison/downloads (There are a variety of methods for doing this, it doesn't seem to matter which I used, they all have led to this npm error.)
3) Connect a terminal to the Edison, run set up (make sure you give it a name that is at least 8 characters long), set up the wifi, switch off usb0 (ifconfig usb0 down) so that the XDK can log in to the device.
4) Install the XDK and connect to the Edison.
5) Run "Install of update the Intel daemon on IoT device"

https://gist.github.com/andr01dm/118e51b446e67e560c32fcdcf2e55797

### supporting information:

I have the same issue when running the XDK in Windows 10 64bit and Ubuntu 16.04.1 LTS 64bit.

**Comment by legodude17** [comment]
What is the Edison's `npm.registry` config?

**Comment by andr01dm** [comment]
registry = "https://registry.npmjs.org/"
