### ISSUE TITLE
error Invalid package.json

### ISSUE THREAD

**Issue by Mursalin80** [npm/npm#15421]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'v' ]
2 info using npm@3.10.10
3 info using node@v6.9.4
4 verbose config Skipping project config: C:\Users\Mursalin80/.npmrc. (matches userconfig)
5 verbose stack Error: Invalid package.json
5 verbose stack     at C:\Program Files (x86)\nodejs\node_modules\npm\lib\view.js:84:30
5 verbose stack     at ReadFileContext.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:90:21)
5 verbose stack     at ReadFileContext.callback (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16)
5 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:365:13)
6 verbose cwd C:\Users\Mursalin80
7 error Windows_NT 10.0.14393
8 error argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "v"
9 error node v6.9.4
10 error npm  v3.10.10
11 error Invalid package.json
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]

**Comment by Charlotteis** [comment]
Could you share your package.json please?

**Comment by KenanY** [comment]
Closing as abandoned.
