### ISSUE TITLE
Installation of angular-cli hangs

### ISSUE THREAD

**Issue by Apostrofix** [npm/npm#15429]
#### I'm opening this issue because:

  - [*] npm is producing an incorrect install.
  - [*] npm is doing something I don't understand.
  - [*] Other (_see below for feature requests_):

#### What's going wrong?
The installation of angular-cli hangs and never completes when I run `npm install -g angular-cli`

#### How can the CLI team reproduce the problem?

I downloaded the current version (v7.4.0) of nodejs from https://nodejs.org/en/ , installed it and then tried to install angular-cli by following the guide [here](https://github.com/angular/angular-cli#prerequisites) but this never finishes.

### supporting information:

https://gist.github.com/Apostrofix/ae8c13168ab81256d0205068cbd709bb

![snip](https://cloud.githubusercontent.com/assets/3696030/21751844/32ae7c48-d5ce-11e6-9e91-55868532a08f.JPG)

I am running the command prompt as Administrator on Windows 10. Here's the link to a StackOverflow post I created earlier: http://stackoverflow.com/questions/41533219/why-does-the-installation-of-angular-cli-hangs There's also a screenshot of the command prompt there.

 - `npm -v` prints: 4.0.5
 - `node -v` prints: v7.4.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows 10
 - Network issues: none
   - Geographic location where npm was run:
   - [ *] I don't use a proxy and have a stable and reliable internet access.

**Comment by legodude17** [comment]
Can you try `npm i -g -ddd angular-cli` and post results?

**Comment by Apostrofix** [comment]
I just tried to enter this this line, but it seems like this also gets to a point where it's hanging, here is the output: https://gist.github.com/Apostrofix/8f9f3ef9930dd5e240071711f352d6b5
[npm.txt](https://github.com/npm/npm/files/694768/npm.txt)

**Comment by TikhomirovSergey** [comment]
Hello. I'm seeing the similar issue on Mac Os X 
```
npm install -g appium
```

**Comment by Apostrofix** [comment]
@TikhomirovSergey Please post if you find a way to solve it, even though you are on a Mac.

**Comment by TikhomirovSergey** [comment]
@Apostrofix I have got it resolved right now:
- I removed node.js (v7.4.0) and npm (4.x). I used this guide https://gist.github.com/tonymtz/d75101d9bdf764c890ef
- then I installed node.js 6.9.4 and npm 3.10.10. 
- the packege was installed successfully
```
sudo su
npm i -g -ddd appium
```
