### ISSUE TITLE
Pls help errors @ npm install

### ISSUE THREAD

**Issue by zenolahaye** [npm/npm#15428]
#### I'm opening this issue because:

  - [x] npm is doing something I don't understand.

#### How can the CLI team reproduce the problem?

    Include a gist of your npm-debug.log file: https://gist.github.com/zenolahaye/85a3e26017993aee50613a7fb1cbc79e

### supporting information:

 - `npm -v` prints: 4.0.5
 - `node -v` prints: v7.4.0
 - `npm config get registry` prints: {"db_name":"registry","doc_count":460703,"doc_del_count":350,"update_seq":3426600,"purge_seq":0,"compact_running":false,"disk_size":2361135233,"data_size":1929226624,"instance_start_time":"1483625551406306","disk_format_version":6,"committed_update_seq":3426600}
 - Windows, OS X/macOS, or Linux?: Mac
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

TERMINAL
iMac-van-Zeno:FoundationPress Zeno$ npm install
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN prefer global marked@0.3.6 should be installed with -g
npm WARN prefer global node-gyp@3.4.0 should be installed with -g

> fsevents@1.0.17 install /Applications/XAMPP/xamppfiles/htdocs/FoundationPress/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/Applications/XAMPP/xamppfiles/htdocs/FoundationPress/node_modules/fsevents/lib/binding/Release/node-v51-darwin-x64/fse.node" is installed via remote

> node-sass@3.13.1 install /Applications/XAMPP/xamppfiles/htdocs/FoundationPress/node_modules/node-sass
> node scripts/install.js

Cached binary found at /Users/Zeno/.npm/node-sass/3.13.1/darwin-x64-51_binding.node

> phantomjs-prebuilt@2.1.14 install /Applications/XAMPP/xamppfiles/htdocs/FoundationPress/node_modules/phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Download already available at /var/folders/m5/63lts27n21jb33nk__qfxprm0000gn/T/phantomjs/phantomjs-2.1.1-macosx.zip
Verified checksum of previously downloaded file
Extracting zip contents
Removing /Applications/XAMPP/xamppfiles/htdocs/FoundationPress/node_modules/phantomjs-prebuilt/lib/phantom
Copying extracted folder /var/folders/m5/63lts27n21jb33nk__qfxprm0000gn/T/phantomjs/phantomjs-2.1.1-macosx.zip-extract-1483883087741/phantomjs-2.1.1-macosx -> /Applications/XAMPP/xamppfiles/htdocs/FoundationPress/node_modules/phantomjs-prebuilt/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /Applications/XAMPP/xamppfiles/htdocs/FoundationPress/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs

> node-sass@3.13.1 postinstall /Applications/XAMPP/xamppfiles/htdocs/FoundationPress/node_modules/node-sass
> node scripts/build.js

Binary found at /Applications/XAMPP/xamppfiles/htdocs/FoundationPress/node_modules/node-sass/vendor/darwin-x64-51/binding.node
Testing binary
Binary is fine

> foundationpress@2.9.0 postinstall /Applications/XAMPP/xamppfiles/htdocs/FoundationPress
> bower install && gulp build

module.js:472
    throw err;
    ^

Error: Cannot find module 'internal/fs'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at evalmachine.<anonymous>:18:20
    at Object.<anonymous> (/Applications/XAMPP/xamppfiles/htdocs/FoundationPress/node_modules/bower/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)

npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/Cellar/node/7.4.0/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! foundationpress@2.9.0 postinstall: `bower install && gulp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the foundationpress@2.9.0 postinstall script 'bower install && gulp build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the foundationpress package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install && gulp build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs foundationpress
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls foundationpress
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Applications/XAMPP/xamppfiles/htdocs/FoundationPress/npm-debug.log
iMac-van-Zeno:FoundationPress Zeno$ npm bugs foundationpress
npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/Cellar/node/7.4.0/bin/node" "/usr/local/bin/npm" "bugs" "foundationpress"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5

npm ERR! Cannot convert undefined or null to object
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Applications/XAMPP/xamppfiles/htdocs/FoundationPress/npm-debug.log

**Comment by legodude17** [comment]
The error in the log and in the post are different. Which one is the one you have?

**Comment by KenanY** [comment]
Closing due to no response.
