### ISSUE TITLE
Add possibility to reformat package.json

### ISSUE THREAD

**Issue by Nirazul** [npm/npm#15432]
#### What's the feature?
In our project scaffolding tool we are stitching together a `package.json` file from different sources that has different devDependencies and depencencies, depending on the project features we need.

Currently we are using this command to reformat the stitched file at the end:
`npm uninstall -D __dummy-to-force-npm-reformat__`

I'm looking for an easier/better way to trigger a reformat as if I'd install/uninstall a dependency.

#### What problem is the feature intended to solve?
The first person to install a dependency, after the project was generated, would trigger a reformat. After commiting the new `package.json` to git, many confusing changes would appear.

#### Is the absence of this feature blocking you or your team? If so, how?
It's just a minor problem, which doesn't block us in any meaningful way.

#### Is this feature similar to an existing feature in another tool?
The only option to fix this without the help of npm, would be a json parser and formatter that would mock your options. As those options may change in the future, I don't see this as a valid alternative.

#### Is this a feature you're prepared to implement, with support from the npm CLI team?
I could try, but I think that there are far more advanced people who already know the codebase.

**Comment by legodude17** [comment]
You mean the way that `normalize-package-json` will change your `package.json` to be more normal? In that case you can use the module `normalize-package-json`.

**Comment by Nirazul** [comment]
@legodude17 
Do you mean [this package](https://github.com/npm/normalize-package-data)? 
I guess that's what I'm looking for. Thanks for the hint :)

I'd be a cool feature, if I had a command line option to normalize the package.json with the option chosen by npm. Something like: `npm normalize`. But I guess that not many users would need or use it.

**Comment by legodude17** [comment]
@Nirazul yes, that is what I meant, misremembered the name.
