### ISSUE TITLE
npm -g ERR! extraneous

### ISSUE THREAD

**Issue by sandrodz** [npm/npm#15436]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x ] npm is doing something I don't understand.

#### What's going wrong?

npm -g ls produces errors:

<img width="1039" alt="d4g1y" src="https://cloud.githubusercontent.com/assets/8479569/21798299/08e14b7e-d72d-11e6-9b08-dd9b1b4b8ddc.png">

#### How can the CLI team reproduce the problem?

I'm not sure. I've installed node via homebrew, than added `n` for version managment, I've used node/npm inside docker containers for a while but went back to sys installed one because of slow downs inside container. Problem is with node on host machine.

### supporting information:

 - `npm -v` prints:
3.10.10
 - `node -v` prints:
v6.9.4
 - `npm config get registry` prints:
https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?:
osx

**Comment by legodude17** [comment]
Try `npm i -g npm@latest`

**Comment by sandrodz** [comment]
@legodude17 errors don't display anymore, what is this magic? any ideas what happened?

**Comment by legodude17** [comment]
It updated and reinstalled `npm` 😄

**Comment by sandrodz** [comment]
@legodude17 that is obvious, but the error, how did it disappear?

**Comment by legodude17** [comment]
The error was with some corruption or something in the `npm` installation the was making `npm` think that  some of its own packages were extraneous, so then you reinstalled it completely.
