### ISSUE TITLE
npm exec <cmd>

### ISSUE THREAD

**Issue by slaskis** [npm/npm#1543]
It would be cool if the `npm get` would be able to get it's config from the package.json. 

Use case for me is to get the port which is defined in the package.json like 

    {"config":{"port":8001}} 

and then i could do this to test if the app is running (in my deploy.conf): 

    curl localhost:`npm get port` >/dev/null

alt. I'd have to use `npm get foo:port`, either way it would be useful i think.

I know it's possible to set on a user basis but this way i wouldn't have to login to the server to set it's port...

**Comment by xaka** [comment]
I wonder if any work is going on to get this done or PR is expected as well? Doing `bundle exec <...>` in Ruby world is so helpful and it would be nice to have similar killer feature for NPM. It just sucks that you can install packages locally, but to run those you either have to end up with hacks like `npm-exec` or simply doing dirty things like `./node_modules/.bin/<...>`. After all if scripts have painless access to binaries under `node_modules/.bin`, why users can't?

**Comment by othiym23** [comment]
@xaka Many, many people would find an `npm-exec` command useful, and even just a small patch getting the ball rolling would probably be enough to get community support sufficient to get the feature landed, but this isn't something that the CLI core team (me and @iarna) is going to have the bandwidth to do anytime soon.

**Comment by xaka** [comment]
There is https://github.com/npm/npm/pull/4058, but your comment there was `we sort of routed around this PR in favor of #5518` so I'm not quite sure whether you meant that PR doesn't need anymore or what's the deal? We need to clear the confusion and I believe the wheels will start rolling again :)

**Comment by othiym23** [comment]
By that I meant that @bcoe added the ability to pass parameters to `run-scripts` in `npm@2` – it was, in fact, the primary breaking change that led to the bumping of npm's major version.

One version of `npm-exec`, as described here (as well as #4058, #5518, and #3313), is a standalone command that allows you to run `run-scripts` free of npm's sophisticated / complicated command-line argument parsing. It allows you to pass arguments to the scripts defined by the `scripts` stanza in `package.json`. The arguments passing bits of this are what got implemented in #5518 and which obsoleted the work in progress on #4058. Most of the discussion of `npm-exec` in terms of incorporating it directly into the main npm install has been this version of `npm-exec`.

Another version is a direct analog of `bundle exec`. I think this is what you're describing, and is what would be most useful for many people. @grncdr started work on a standalone version of this in the form of http://npm.im/npm-exec a while ago. I'm also not sure that's a utility that needs to be a part of the main npm distribution, but I'm also not opposed to incorporating it, especially if the behavior described in the previous paragraph is also incorporated.

**Comment by kuraga** [comment]
Updates?

**Comment by yinrong** [comment]
+1 need this

**Comment by othiym23** [comment]
Closing this in favor of #6053, which has a better description of where we landed on adding this.
