### ISSUE TITLE
sudo npm install -g grunt-cli bower yo

### ISSUE THREAD

**Issue by serena96** [npm/npm#15431]
npm ERR! Darwin 14.3.0
npm ERR! argv "/usr/local/Cellar/node/7.4.0/bin/node" "/usr/local/bin/npm" "install" "-g" "grunt-cli" "bower" "yo"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5

npm ERR! shasum check failed for /tmp/npm-7213-c4db8df0/registry.npmjs.org/bower/-/bower-1.8.0.tgz
npm ERR! Expected: 55dbebef0ad9155382d9e9d3e497c1372345b44a
npm ERR! Actual:   35134b93ec4ad702f7a0cefae2614419cb72aa0b
npm ERR! From:     https://registry.npmjs.org/bower/-/bower-1.8.0.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by watilde** [comment]
Hello! Your error seems like having a wrong cache file in your local
> npm ERR! shasum check failed for /tmp/npm-7213-c4db8df0/registry.npmjs.org/bower/-/bower-1.8.0.tgz

Can you try to clear your cache and install again?
> $ npm cache clean

**Comment by gusdecool** [comment]
tried clear cache and reinstall, still the same error
