### ISSUE TITLE
Cant Update NPM

### ISSUE THREAD

**Issue by ewm2000** [npm/npm#15433]
#### I'm opening this issue because:
  having trouble with brackets, saw Error: /bin/sh: npm: command not found, thinking its a problem npm not being up to date. Tried updating

#### What's going wrong?
Cant update npm

#### How can the CLI team reproduce the problem?
ran the command npm update in terminal

### supporting information:

This is what Went on in the terminal after issueing the command
 
EvanMac:~ Evan$ npm update
npm WARN deprecated node-uuid@1.4.7: use uuid module instead

spawn-sync@1.0.15 postinstall /Users/Evan/node_modules/spawn-sync
 node postinstall

- lodash@3.2.0 node_modules/archiver/node_modules/lodash
- bn.js@2.2.0 node_modules/bn.js
- camelcase@1.2.1 node_modules/camelcase
- async@1.5.2 node_modules/form-data/node_modules/async
- get-stdin@4.0.1 node_modules/get-stdin
- commander@2.9.0 node_modules/har-validator/node_modules/commander
- base64url@0.0.6 node_modules/jwa/node_modules/base64url
- map-obj@1.0.1 node_modules/map-obj
- camelcase-keys@1.0.0 node_modules/camelcase-keys
- match-stream@0.0.2 node_modules/match-stream
- minimalistic-assert@1.0.0 node_modules/minimalistic-assert
- minimist@0.0.8 node_modules/mkdirp/node_modules/minimist
- mkdirp@0.5.1 node_modules/mkdirp
- fstream@0.1.31 node_modules/fstream
- number-is-nan@1.0.0 node_modules/number-is-nan
- is-finite@1.0.1 node_modules/is-finite
- over@0.0.5 node_modules/over
- repeating@1.1.3 node_modules/repeating
- indent-string@1.2.2 node_modules/indent-string
- glob@6.0.4 node_modules/rimraf/node_modules/glob
- setimmediate@1.0.4 node_modules/setimmediate
- slice-stream@1.0.0 node_modules/slice-stream
- pullstream@0.4.1 node_modules/pullstream
- lodash@3.10.1 node_modules/xmlbuilder/node_modules/lodash
- lodash@3.2.0 node_modules/zip-stream/node_modules/lodash
- asn1.js@2.2.1 node_modules/asn1.js
- base64-url@1.2.1 node_modules/base64-url
- ctype@0.5.3 node_modules/ctype
- meow@2.0.0 node_modules/meow
- node-int64@0.3.3 node_modules/node-int64
- unzip@0.1.11 node_modules/unzip
- wrench@1.5.8 node_modules/wrench
/Users/Evan
├── jpm@1.2.2 
└── normalize.css@5.0.0 

npm WARN ENOENT ENOENT: no such file or directory, open '/Users/Evan/package.json'
npm WARN EPACKAGEJSON Evan No description
npm WARN EPACKAGEJSON Evan No repository field.
npm WARN EPACKAGEJSON Evan No README data
npm WARN EPACKAGEJSON Evan No license field.

**Comment by KenanY** [comment]
@ewm2000 If you want to update `npm`, the suggested command is `npm install -g npm`

**Comment by ewm2000** [comment]
@KenanY My band I didnt realize that.

**Comment by FNGR2911** [comment]
@KenanY I tried `npm install -g npm` but if I check my npm -v i get 3.9.5. No idea why, I think the latest version is 4.1.2? Some ideas? Thank you!

**Comment by KenanY** [comment]
@FNGR2911 Are you on Windows?

**Comment by FNGR2911** [comment]
@KenanY no, it's macOS 10.12.2

**Comment by KenanY** [comment]
@FNGR2911 Sounds like you might have two installations of `npm` then

**Comment by FNGR2911** [comment]
hmm if I try which npm I get

`/Users/MYUSERNAME/.npm-packages/bin/npm`

shouldn't `npm install -g npm` update that npm dir?

**Comment by ewm2000** [comment]
Im on mac as well
