### ISSUE TITLE
Drag and Drop

### ISSUE THREAD

**Issue by sunilrk03** [npm/npm#15430]
Hi ,

     I have taken sample application from github for drag and drop while iam starting npm getting some errors   

   1. Module not found error can resolve it.
   2. webpack :bundle is now valid
![capture](https://cloud.githubusercontent.com/assets/25003538/21762805/b6d16d34-d680-11e6-9263-0060b7a99b89.PNG)
![capture](https://cloud.githubusercontent.com/assets/25003538/21762817/c2db9802-d680-11e6-99fb-afc833149684.PNG)

Kindly do the needful

**Comment by legodude17** [comment]
This doesn't look like an error with `npm`? Why did you report it here?
