### ISSUE TITLE
Errors when installing jsonPATH

### ISSUE THREAD

**Issue by latamike** [npm/npm#15441]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
The install seems to be happening but then the nodes aren't showing up in the browser.

#### How can the CLI team reproduce the problem?

I'm simply trying to install using the following command in DOS:

"npm install JSONPath"

I've moved the source folder all around the C: drive to see if it makes a difference and it didn't. I had it in the following folders:

C:\Users\latam\.node-red\node_modules
C:\Users\latam\node_modules\JSONPath

Here is a log from one of my attempts:

> 0 info it worked if it ends with ok
> 1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
> 1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
> 1 verbose cli   'install',
> 1 verbose cli   'JSONPath' ]
> 2 info using npm@3.10.9
> 3 info using node@v6.9.2
> 4 silly loadCurrentTree Starting
> 5 silly install loadCurrentTree
> 6 silly install readLocalPackageData
> 7 silly fetchPackageMetaData JSONPath
> 8 silly fetchNamedPackageData JSONPath
> 9 silly mapToRegistry name JSONPath
> 10 silly mapToRegistry using default registry
> 11 silly mapToRegistry registry https://registry.npmjs.org/
> 12 silly mapToRegistry data Result {
> 12 silly mapToRegistry   raw: 'JSONPath',
> 12 silly mapToRegistry   scope: null,
> 12 silly mapToRegistry   escapedName: 'JSONPath',
> 12 silly mapToRegistry   name: 'JSONPath',
> 12 silly mapToRegistry   rawSpec: '',
> 12 silly mapToRegistry   spec: 'latest',
> 12 silly mapToRegistry   type: 'tag' }
> 13 silly mapToRegistry uri https://registry.npmjs.org/JSONPath
> 14 verbose request uri https://registry.npmjs.org/JSONPath
> 15 verbose request no auth needed
> 16 info attempt registry request try #1 at 3:53:05 PM
> 17 verbose request id 925c6b2b37217e60
> 18 verbose etag W/"5821dc46-6cc9"
> 19 verbose lastModified Tue, 08 Nov 2016 14:08:06 GMT
> 20 http request GET https://registry.npmjs.org/JSONPath
> 21 http 304 https://registry.npmjs.org/JSONPath
> 22 verbose headers { date: 'Tue, 10 Jan 2017 14:53:06 GMT',
> 22 verbose headers   via: '1.1 varnish',
> 22 verbose headers   'cache-control': 'max-age=300',
> 22 verbose headers   etag: 'W/"5821dc46-6cc9"',
> 22 verbose headers   age: '211',
> 22 verbose headers   connection: 'keep-alive',
> 22 verbose headers   'x-served-by': 'cache-fra1225-FRA',
> 22 verbose headers   'x-cache': 'HIT',
> 22 verbose headers   'x-cache-hits': '1',
> 22 verbose headers   'x-timer': 'S1484059986.170470,VS0,VE0',
> 22 verbose headers   vary: 'Accept-Encoding' }
> 23 silly get cb [ 304,
> 23 silly get   { date: 'Tue, 10 Jan 2017 14:53:06 GMT',
> 23 silly get     via: '1.1 varnish',
> 23 silly get     'cache-control': 'max-age=300',
> 23 silly get     etag: 'W/"5821dc46-6cc9"',
> 23 silly get     age: '211',
> 23 silly get     connection: 'keep-alive',
> 23 silly get     'x-served-by': 'cache-fra1225-FRA',
> 23 silly get     'x-cache': 'HIT',
> 23 silly get     'x-cache-hits': '1',
> 23 silly get     'x-timer': 'S1484059986.170470,VS0,VE0',
> 23 silly get     vary: 'Accept-Encoding' } ]
> 24 verbose etag https://registry.npmjs.org/JSONPath from cache
> 25 verbose get saving JSONPath to C:\Users\latam\AppData\Roaming\npm-cache\registry.npmjs.org\JSONPath\.cache.json
> 26 verbose correctMkdir C:\Users\latam\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
> 27 silly install normalizeTree
> 28 silly loadCurrentTree Finishing
> 29 silly loadIdealTree Starting
> 30 silly install loadIdealTree
> 31 silly cloneCurrentTree Starting
> 32 silly install cloneCurrentTreeToIdealTree
> 33 silly cloneCurrentTree Finishing
> 34 silly loadShrinkwrap Starting
> 35 silly install loadShrinkwrap
> 36 silly loadShrinkwrap Finishing
> 37 silly loadAllDepsIntoIdealTree Starting
> 38 silly install loadAllDepsIntoIdealTree
> 39 silly rollbackFailedOptional Starting
> 40 silly rollbackFailedOptional Finishing
> 41 silly runTopLevelLifecycles Finishing
> 42 silly install printInstalled
> 43 verbose stack Error: Refusing to install JSONPath as a dependency of itself
> 43 verbose stack     at checkSelf (C:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:53:14)
> 43 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
> 43 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
> 43 verbose stack     at chain (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
> 43 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:16:5
> 43 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
> 43 verbose stack     at Array.forEach (native)
> 43 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
> 43 verbose stack     at Array.forEach (native)
> 43 verbose stack     at asyncMap (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
> 44 verbose cwd C:\Users\latam\.node-red\node_modules\JSONPath\lib
> 45 error Windows_NT 10.0.10586
> 46 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "JSONPath"
> 47 error node v6.9.2
> 48 error npm  v3.10.9
> 49 error code ENOSELF
> 50 error Refusing to install JSONPath as a dependency of itself
> 51 error If you need help, you may report this error at:
> 51 error     <https://github.com/npm/npm/issues>
> 52 verbose exit [ 1, true ]
> 

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
Ensure the the `name` field of your `package.json` is not `JSONPath

**Comment by latamike** [comment]
Just to clarify, this is a node from the Node-Red library, called JSONpath. 

Actually, I just went back to the [library](https://flows.nodered.org/) and couldn't find the same JSONpath node for download. Not sure what happened.

**Comment by latamike** [comment]
I found a similar [node](https://flows.nodered.org/node/node-red-contrib-jsonpath) from the library that gets the job done and it worked on first install.
