### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by kakooljay** [npm/npm#15446]
#### I'm opening this issue because:
  - [x] npm is producing an incorrect install.

#### What's going wrong?
Errors on update / install

#### How can the CLI team reproduce the problem?
https://gist.github.com/kakooljay/40b8447a07d0993adc2f9f9563f3e10b

### supporting information:
   - [ ] I develop using Vagrant on Windows.

**Comment by KenanY** [comment]
@kakooljay Does this also occur if you use the `--no-bin-links` flag?

**Comment by kakooljay** [comment]
Ooops... gulp wouldn't run so I deleted node_mods and ran again:
npm install --no-bin-links

Now error is
Max call stack size executed

Do I need to change some buffer size or something? (I'm a linux noob lol)

Can u advise, or should I report on github?

**Comment by legodude17** [comment]
> Max call stack size executed

Don't you mean "exceeded"?

**Comment by kakooljay** [comment]
Yep....
I just tried update & install again .. & it worked lol
Thx,
J

**Comment by KenanY** [comment]
Closing as resolved.
