### ISSUE TITLE
Getting error while installing npm

### ISSUE THREAD

**Issue by sbhambad** [npm/npm#15455]
#### I'm opening this issue because:

  - [ ] npm is producing an incorrect install. getting below error.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\node.exe" "C:\\node_modules\\npm\\bin\\npm-cli.js" "install"
"npm" "-g"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! syscall getaddrinfo

npm ERR! getaddrinfo EAI_AGAIN registry.npmjs.org:443
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\sandeep19019\npm-debug.log

**Comment by Charlotteis** [comment]
Hey @sbhambad.

are you behind a proxy? If so, make sure it is configured properly.

https://jjasonclark.com/how-to-setup-node-behind-web-proxy/

Have a great day, 🌸

**Comment by KenanY** [comment]
Closing as abandoned.
