### ISSUE TITLE
Can't install or uninstall packages "Unexpected end of JSON input"

### ISSUE THREAD

**Issue by ahrobinson** [npm/npm#15453]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
NPM crashes when trying to install or uninstall a package.

#### How can the CLI team reproduce the problem?
All I did was npm uninstall <package>, but it recently started happening so idk if it is reproducable or specific to just me.

https://gist.github.com/ahrobinson/1913cea19b15dd4ad3412c115338c700

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ x] I use a proxy to connect to the npm registry.
   - [ x] I use a proxy to connect to the web.
   - [ x] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by Charlotteis** [comment]
Howdy @ahrobinson.

Would you mind sharing your `package.json` here?

**Comment by ahrobinson** [comment]
@Charlotteis I figured it out. I had an npm-shrinkwrap.json file that was causing errors for some reason. When I deleted it, it started working. Thanks!
