### ISSUE TITLE
Unable to install polymer -cli

### ISSUE THREAD

**Issue by cecesmooth** [npm/npm#15451]
#### I'm opening this issue because I get this error message during install on a MAC:

  ssh: Could not resolve hostname github.com: nodename nor servname provided, or not known
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.

#### What's going wrong
[npm-debug.txt](https://github.com/npm/npm/files/699784/npm-debug.txt)

?

### supporting information:

 - - npm log

**Comment by SagarMhatre** [comment]
I am getting the same error on Windows 7 64 bit

**Comment by cecesmooth** [comment]
Thanks.  A coworker was able to find a solution:
https://docs.npmjs.com/getting-started/fixing-npm-permissions
