### ISSUE TITLE
gulp-connect-reproxy ENOENT: no such file or directory

### ISSUE THREAD

**Issue by sandraqu** [npm/npm#15452]
#### I'm opening this issue because:

  - [ x ] npm is producing an incorrect install.

#### What's going wrong?

plugin not found.

#### How can the CLI team reproduce the problem?

to reproduces simply try to install the plugin 
npm install gulp-connect-reproxy --save

#### What problem is the feature intended to solve?

compile jsp

#### Is the absence of this feature blocking you or your team? If so, how?

yes.  I'm trying to run an angular app with a jsp component.

#### Is this feature similar to an existing feature in another tool?
tried gulp-compile-jsp but it is not well documented and I am not having success getting the jsp to load using it.

**Comment by KenanY** [comment]
@sandraqu Please provide a `npm-debug.log` file as a [gist](https://gist.github.com/).

**Comment by KenanY** [comment]
Closing as abandoned.
