### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by afridifaiz** [npm/npm#15456]
![npm_start_error](https://cloud.githubusercontent.com/assets/25026688/21880185/8b52765e-d8c3-11e6-98be-6223a7dc57d5.png)
![npm_start_error1](https://cloud.githubusercontent.com/assets/25026688/21880186/8b52a8ae-d8c3-11e6-9cae-89b3e001f346.png)
[npm-debug.txt](https://github.com/npm/npm/files/700902/npm-debug.txt)
[npm-debug.txt](https://github.com/npm/npm/files/700904/npm-debug.txt)

#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
Make sure to define a `"start"` script in your `package.json` _before_ running `npm start`.
