### ISSUE TITLE
Cannot install anything

### ISSUE THREAD

**Issue by Derter** [npm/npm#15460]
**Command:** npm install -g less-plugin-clean-css -verbose
npm info it worked if it ends with ok
npm verb cli [ '/usr/bin/nodejs',
npm verb cli   '/usr/bin/npm',
npm verb cli   'install',
npm verb cli   '-g',
npm verb cli   'less-plugin-clean-css',
npm verb cli   '-verbose' ]
npm info using npm@3.5.2
npm info using node@v4.2.6
npm verb request uri https://registry.npmjs.org/less-plugin-clean-css
npm verb request no auth needed
npm info attempt registry request try #1 at 11:52:23
npm verb request id 6a630616c783ab3b
npm http request GET https://registry.npmjs.org/less-plugin-clean-css
npm info retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.112.162:443
npm info attempt registry request try #2 at 11:54:40
npm http request GET https://registry.npmjs.org/less-plugin-clean-css

From then on the progress bar wont move a single step. Also other npm packages wont be loaded at all. 

What could be the issue?

**Comment by noherczeg** [comment]
Are you behind a proxy?

**Comment by Derter** [comment]
Yep, I was behind proxy you can close this sorry bout that
