### ISSUE TITLE
linking dependencies when using local path in package.json

### ISSUE THREAD

**Issue by hendrul** [npm/npm#15465]
When using local path for dependencies in the package.json file, Instead of copying it would be helpful if it symlink instead so changes are immediately taken without having to do an npm update.

A work around but only  working on npm@2.x is:

```json
{
  ...
  "scripts": {
    "preinstall": "npm link ../module-x"
  },
 "dependencies": {
   "module-x": "*"
 }
}
```
In npm@3.x and even on npm@4.x preinstall hook is broken (#10379) so we can't do this. 
I think npm should link instead of copying when using local paths:
```javascript
 "dependencies": {
   "module-x": "../module-x"   //<- should create link not a copy
 }
```

**Comment by legodude17** [comment]
Just use `npm link`...

**Comment by hendrul** [comment]
Declaring dependencies explicitly and in one place (package.json) it doesn't matter where they are is an important principle of modularity, so the point is declaring dependencies between local modules in dependencies section of package.json, but at the same time allowing easy development by implicitly doing a symlink in node_modules folder. I have a multiproject and having to create a script to do npm link is a shame.

**Comment by legodude17** [comment]
@hendrul Ok, that makes sense.

**Comment by hendrul** [comment]
Nothing on this one?, my multi-project would be simplified a lot with this one

**Comment by legodude17** [comment]
This feature request is in `npm5` AFAIK.
