### ISSUE TITLE
Invalid package version causes silent failure to install dependencies

### ISSUE THREAD

**Issue by tmct** [npm/npm#15472]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong? / How can the CLI team reproduce the problem?

1. Take this `package.json`:

```
{
  "name": "bug",
  "version": "1.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "express": "^4.14.0"
  }
}
```

2. Hit `npm install`

3. Expected: dependencies (just `express` in the example) are installed locally, or a error is thrown. Actual: An empty node_modules folder is created, with an innocuous warning `npm WARN Invalid version: "1.0"` and no error.

It wasn't very obvious what the problem was (yes, I know, don't ignore warnings 😄), and I so think that this could be made more user-friendly. Possibly an error should be thrown.

### supporting information:

npm 3.9.5
node v6.2.2
https://registry.npmjs.org/
macOS 10.11.6

**Comment by legodude17** [comment]
So is this a feature request to print a better message when the version is in valid, or to install anyway when the version is invalid?

**Comment by tmct** [comment]
Sorry for the delay. It depends on a question I don't currently feel qualified to answer myself: _should an invalid version be a blocker to installing the dependencies?_

If true, then I feel we should defnitely a) print a better message, and almost certainly b) return an error instead of just printing a warning.

If false, then we should install the deps anyway. Certainly both of these cases feel an improvement on the current behaviour!

Happy to have a go at fixing this myself if we can work out what the behaviour should be.

**Comment by legodude17** [comment]
It would be up to the cli team, but I would say that it should still install the dependencies. 

/cc @iarna
