### ISSUE TITLE
error self signed certificate in certificate chain

### ISSUE THREAD

**Issue by lkoumis** [npm/npm#15477]
Cannot install any modules in windows 7. 
I am not behind a proxy and I already tried to resolve issue as instructed at: http://blog.npmjs.org/post/78165272245/more-help-with-selfsignedcertinchain-and-npm

C:\>npm install underscore --save
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\
node_modules\\npm\\bin\\npm-cli.js" "install" "underscore" "--save"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code SELF_SIGNED_CERT_IN_CHAIN

npm ERR! self signed certificate in certificate chain
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\npm-debug.log

npm-debug.og:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'underscore',
1 verbose cli   '--save' ]
2 info using npm@4.0.5
3 info using node@v7.4.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData underscore
8 silly fetchNamedPackageData underscore
9 silly mapToRegistry name underscore
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'underscore',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'underscore',
12 silly mapToRegistry   name: 'underscore',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/underscore
14 verbose request uri https://registry.npmjs.org/underscore
15 verbose request no auth needed
16 info attempt registry request try #1 at 1:34:18 PM
17 verbose request id a18c55bb4803c202
18 http request GET https://registry.npmjs.org/underscore
19 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
20 info attempt registry request try #2 at 1:34:28 PM
21 http request GET https://registry.npmjs.org/underscore
22 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
23 info attempt registry request try #3 at 1:35:28 PM
24 http request GET https://registry.npmjs.org/underscore
25 silly fetchPackageMetaData Error: self signed certificate in certificate chain
25 silly fetchPackageMetaData     at TLSSocket.<anonymous> (_tls_wrap.js:1085:38)
25 silly fetchPackageMetaData     at emitNone (events.js:86:13)
25 silly fetchPackageMetaData     at TLSSocket.emit (events.js:185:7)
25 silly fetchPackageMetaData     at TLSSocket._finishInit (_tls_wrap.js:603:8)
25 silly fetchPackageMetaData     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:433:38)
25 silly fetchPackageMetaData  error for underscore { Error: self signed certificate in certificate chain
25 silly fetchPackageMetaData     at TLSSocket.<anonymous> (_tls_wrap.js:1085:38)
25 silly fetchPackageMetaData     at emitNone (events.js:86:13)
25 silly fetchPackageMetaData     at TLSSocket.emit (events.js:185:7)
25 silly fetchPackageMetaData     at TLSSocket._finishInit (_tls_wrap.js:603:8)
25 silly fetchPackageMetaData     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:433:38) code: 'SELF_SIGNED_CERT_IN_CHAIN' }
26 silly rollbackFailedOptional Starting
27 silly rollbackFailedOptional Finishing
28 silly runTopLevelLifecycles Finishing
29 silly install printInstalled
30 verbose stack Error: self signed certificate in certificate chain
30 verbose stack     at TLSSocket.<anonymous> (_tls_wrap.js:1085:38)
30 verbose stack     at emitNone (events.js:86:13)
30 verbose stack     at TLSSocket.emit (events.js:185:7)
30 verbose stack     at TLSSocket._finishInit (_tls_wrap.js:603:8)
30 verbose stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:433:38)
31 verbose cwd C:\
32 error Windows_NT 6.1.7601
33 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "underscore" "--save"
34 error node v7.4.0
35 error npm  v4.0.5
36 error code SELF_SIGNED_CERT_IN_CHAIN
37 error self signed certificate in certificate chain
38 error If you need help, you may report this error at:
38 error     <https://github.com/npm/npm/issues>
39 verbose exit [ 1, true ]

**Comment by legodude17** [comment]
Have you taken a look at http://blog.npmjs.org/post/78165272245/more-help-with-selfsignedcertinchain-and-npm? See if the steps outlined there work for you.

If it does NOT:

1. Are you behind a proxy?
2. How are you trying to use it?

**Comment by lkoumis** [comment]
Legodude17, like I said at the beginning of my posting, I already tried the steps outlined to that link and I am not behind proxy. 
I am just trying to add a module through the command line as I am showing in my posting as well.

**Comment by rmcfarland** [comment]
I am having the same exact problem trying to install Angular QuickStart.  As the OP said, I tried the steps on that link and am not behind a proxy.
