### ISSUE TITLE
Can not install scoped packages

### ISSUE THREAD

**Issue by ringvold** [npm/npm#15471]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

When I try to install hubot-slack, which depends on @slack/client, or any scoped packages directly npm responds with `npm ERR! 404 User not found : @slack/client`. I have tried with different scoped packages (@angular/router).
I'm behind a proxy.
I'm pretty sure it is a npm problem as it works with Yarn.
A curl command to the same url as is shown with verbose output gives correct response, but npm says the package/user does not exist.

Full error:
```
λ npm i @slack/client --verbose
npm info it worked if it ends with ok
npm verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Users\\exthxr\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'i',
npm verb cli   '@slack/client',
npm verb cli   '--verbose' ]
npm info using npm@4.0.5
npm info using node@v6.9.4
npm verb mapToRegistry no registry URL found in name for scope @slack
npm verb request uri https://registry.npmjs.org/@slack%2fclient
npm verb request always-auth set; sending authorization
npm info attempt registry request try #1 at 14:58:27
npm verb request id c0e9fa811d2dec6b
npm http request GET https://registry.npmjs.org/@slack%2fclient
npm http 404 https://registry.npmjs.org/@slack%2fclient
npm verb headers { 'content-type': 'application/json',
npm verb headers   'cache-control': 'max-age=0',
npm verb headers   'content-length': '26',
npm verb headers   'accept-ranges': 'bytes',
npm verb headers   date: 'Fri, 13 Jan 2017 13:58:28 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   connection: 'close',
npm verb headers   'x-served-by': 'cache-bma7028-BMA',
npm verb headers   'x-cache': 'MISS',
npm verb headers   'x-cache-hits': '0',
npm verb headers   'x-timer': 'S1484315907.842295,VS0,VE596' }
npm verb stack Error: User not found : @slack/client
npm verb stack     at makeError (C:\Users\exthxr\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-client\lib\request.js:302:12)
npm verb stack     at CachingRegistryClient.<anonymous> (C:\Users\exthxr\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-client\lib\request.js:290:14)
npm verb stack     at Request._callback (C:\Users\exthxr\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-client\lib\request.js:210:14)
npm verb stack     at Request.self.callback (C:\Users\exthxr\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:186:22)
npm verb stack     at emitTwo (events.js:106:13)
npm verb stack     at Request.emit (events.js:191:7)
npm verb stack     at Request.<anonymous> (C:\Users\exthxr\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:1081:10)
npm verb stack     at emitOne (events.js:96:13)
npm verb stack     at Request.emit (events.js:188:7)
npm verb stack     at IncomingMessage.<anonymous> (C:\Users\exthxr\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:1001:12)
npm verb statusCode 404
npm verb pkgid @slack/client
npm verb cwd C:\DATA\git\hubot-new
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\exthxr\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i" "@slack/client" "--verbose"
npm ERR! node v6.9.4
npm ERR! npm  v4.0.5
npm ERR! code E404

npm ERR! 404 User not found : @slack/client
npm ERR! 404
npm ERR! 404  '@slack/client' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
npm verb exit [ 1, true ]

npm ERR! Please include the following file with any support request:
```

#### How can the CLI team reproduce the problem?

I'm not completely sure on how to reproduce it, but the difference from there I have gotten it to work is that it is a windows or linux box behind a proxy.

1. Windows or Linux behind proxy
2. Run `npm i @slack/client"

### supporting information:

 - `npm -v` prints: 4.0.5
 - `node -v` prints: v6.9.4
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows 7 and linux
 - Network issues:
   - Geographic location where npm was run:
   - [x] I use a proxy to connect to the npm registry.
   - [x] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by GGYaX** [comment]
I have the same issue in Window7

**Comment by Blacktiger** [comment]
I'm having the same issue on Mac OS X. For example, when I try to install @angular/cli, npm attempts to download it from https://registry.npmjs.org/@angluar%2fcli which results in a 404. I don't know if this is a bug with NPM or with the npm registry.

**Comment by legodude17** [comment]
Does this occur without a proxy?

**Comment by Blacktiger** [comment]
I'm not currently on a proxy or using a VPN (at first I did have a proxy repository configured, but I removed it). Here are the logs.
[2017-04-21T19_07_30_294Z-debug.txt](https://github.com/npm/npm/files/948082/2017-04-21T19_07_30_294Z-debug.txt)

**Comment by legodude17** [comment]
The log indicates that you spelled angular wrong. It is angular, not angluar. 😄

**Comment by Blacktiger** [comment]
Ah, no wonder. Thanks. :P

**Comment by legodude17** [comment]
Yeah I didn't notice it until I put the URL in my browser.
