### ISSUE TITLE
Error trying to install Discord.js

### ISSUE THREAD

**Issue by DeadWolfQc** [npm/npm#15482]
I am trying to install Discord.js using "npm install discord.js --save" but gives this error that i don't understand :

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "discord.js" "--save"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ENOSELF

npm ERR! Refusing to install package with name "discord.js" under a package
npm ERR! also called "discord.js". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR!
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Jeremy\npm-debug.log

(I am completely new at programming i didn't learn the basic so sorry if it seems simple for you.)

**Comment by KenanY** [comment]
@DeadWolfQc The error message points in the right direction. Ensure that the `"name"` field in your `package.json` is not set to `"discord.js"`. Make it more unique :D

**Comment by KenanY** [comment]
Closing as abandoned.
