### ISSUE TITLE
Error in MAC terminal, not installing.

### ISSUE THREAD

**Issue by speudoname** [npm/npm#15485]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by speudoname** [comment]
I am just running the command npr install and here is what I get:

Levans-MacBook-Air-4:~ lbakhia$ npm install ionic -g
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "ionic" "-g"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10

npm ERR! Invalid name: "@ionic/app-generators"
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/lbakhia/npm-debug.log

**Comment by mrutkows** [comment]
is "run-p" command (not found) the problem? Is this an additional install needed?
