### ISSUE TITLE
Error installing angular-cli

### ISSUE THREAD

**Issue by gandra** [npm/npm#15483]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I can not install angular-cli

#### How can the CLI team reproduce the problem?

Execute in the command line:
   `npm install -g angular-cli`   

Here is [npm-debug.log file](https://gist.github.com/gandra/a05cbae21b79ca8ca144360536bc470a)  
Here is [console screenshot](http://i.imgur.com/hbfm3Gs.png)

### supporting information:

 - `npm -v` prints: `3.7.1`
 - `node -v` prints: `v7.4.0`
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?: Windows 7
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kuncevic** [comment]
I have no issues with angular-cli running with `node 6.9.1` and `npm 4.0.3`
Try to downgrade your node version to `6.x`, also try to use `npm 4` by running `npm install npm` which will bring you the latest version of `npm`

**Comment by gandra** [comment]
@kuncevic ,
you are right.
This is the bug related to node version 7.*

After downgrading node to v6.9.4 I have successfully installed angular-cli.

**Comment by KenanY** [comment]
Perhaps https://github.com/nodejs/node/issues/9377#issuecomment-258911774 would help.
