### ISSUE TITLE
Error in installing commander package by npm

### ISSUE THREAD

**Issue by nickwuu** [npm/npm#15487]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

The result is:

![image](https://cloud.githubusercontent.com/assets/25119916/21963073/686a1522-db6e-11e6-843f-b190c1d70da3.png)

**Comment by KenanY** [comment]
@nickwuu I do not see an error in the output you have posted.

**Comment by Charlotteis** [comment]
@KenanY looks like the error is in the image:

`> ENONENT: no such file or directory, open 'C:\Users\user\package.json'`

**Comment by KenanY** [comment]
Oh, that's just a _warning_ (admittedly with an error code next to it) about not having a `package.json` in your current working directory.

**Comment by Charlotteis** [comment]
@KenanY ugh my bad, I hadn't had coffee at that point. Thanks and sorry :)
