### ISSUE TITLE
Error in Installing a Tarball from a GitHub Repository

### ISSUE THREAD

**Issue by nickwuu** [npm/npm#15489]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

![image](https://cloud.githubusercontent.com/assets/25119916/21965749/2ff7e79a-dba1-11e6-910a-b67c6a0989ba.png)

**Comment by KenanY** [comment]
@nickwuu Looks like you are trying to install the tarball of a repository which does not exist. Hence, the `404` error you are receiving.
