### ISSUE TITLE
Windows_NT 6.1.7601

### ISSUE THREAD

**Issue by yogeeshamanjegowda** [npm/npm#15496]
while starting npm i am getting below error please help me 
C:\ReactStarter-1.2>npm start
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3

npm ERR! missing script: start
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\ReactStarter-1.2\npm-debug.log

**Comment by Charlotteis** [comment]
Hi @yogeeshamanjegowda, could you share your `package.json`

if you don't have a 'start' script in there, `npm start` wont work.

**Comment by yogeeshamanjegowda** [comment]
Hi@Charlotteis
please check i have pasted package.json

{
  "name": "react-starter",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "browserify": "^9.0.3",
    "gulp": "^3.8.11",
    "gulp-concat": "^2.5.2",
    "gulp-react": "^3.0.1",
    "gulp-sass": "^2.0.1",
    "gulp-server-livereload": "^1.3.0",
    "gulp-util": "^3.0.4",
    "gulp-watch": "^4.2.4",
    "node-notifier": "^4.2.1",
    "react": "^0.13.1",
    "reactify": "^1.1.0",
    "vinyl-source-stream": "^1.1.0",
    "watchify": "^2.4.0"
  },
  "devDependencies": {}
}

**Comment by Charlotteis** [comment]
@yogeeshamanjegowda 

In `scripts` you only have a `test` script.
You need a `start` script to be able to use `npm start`.

How would you start your application?

```
"scripts": {
"test": "echo "Error: no test specified" && exit 1",
"start": "PUT IN HOW YOU START YOUR APP HERE"
},
```

**Comment by androidABCD** [comment]
@Charlotteis 
 following is my package.json.

in script there is no "start" script.

Error: 
`
C:\Users\gaurab.kumar\TestFolder>npm install package
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\b
in\\npm-cli.js" "install" "package"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ECONNRESET

npm ERR! network tunneling socket could not be established, cause=connect ETIMEDOUT 192.168.11.183:4
43
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\gaurab.kumar\TestFolder\npm-debug.log`


> package.json


`{
  "version": "4.0.5",
  "name": "npm",
  "description": "a package manager for JavaScript",
  "keywords": [
    "install",
    "modules",
    "package manager",
    "package.json"
  ],
  "preferGlobal": true,
  "config": {
    "publishtest": false
  },
  "homepage": "https://docs.npmjs.com/",
  "author": "Isaac Z. Schlueter <i@izs.me> (http://blog.izs.me)",
  "repository": {
    "type": "git",
    "url": "https://github.com/npm/npm"
  },
  "bugs": {
    "url": "https://github.com/npm/npm/issues"
  },
  "directories": {
    "bin": "./bin",
    "doc": "./doc",
    "lib": "./lib",
    "man": "./man"
  },
  "main": "./lib/npm.js",
  "bin": "./bin/npm-cli.js",
  "dependencies": {
    "JSONStream": "~1.2.1",
    "abbrev": "~1.0.9",
    "ansicolors": "~0.3.2",
    "ansistyles": "~0.1.3",
    "aproba": "~1.0.4",
    "archy": "~1.0.0",
    "asap": "~2.0.5",
    "chownr": "~1.0.1",
    "cmd-shim": "~2.0.2",
    "columnify": "~1.5.4",
    "config-chain": "~1.1.11",
    "dezalgo": "~1.0.3",
    "editor": "~1.0.0",
    "fs-vacuum": "~1.2.9",
    "fs-write-stream-atomic": "~1.0.8",
    "fstream": "~1.0.10",
    "fstream-npm": "~1.2.0",
    "glob": "~7.1.1",
    "graceful-fs": "~4.1.11",
    "has-unicode": "~2.0.1",
    "hosted-git-info": "~2.1.5",
    "iferr": "~0.1.5",
    "inflight": "~1.0.6",
    "inherits": "~2.0.3",
    "ini": "~1.3.4",
    "init-package-json": "~1.9.4",
    "lockfile": "~1.0.2",
    "lodash._baseuniq": "~4.6.0",
    "lodash.clonedeep": "~4.5.0",
    "lodash.union": "~4.6.0",
    "lodash.uniq": "~4.5.0",
    "lodash.without": "~4.4.0",
    "mississippi": "~1.2.0",
    "mkdirp": "~0.5.1",
    "node-gyp": "~3.4.0",
    "nopt": "~3.0.6",
    "normalize-git-url": "~3.0.2",
    "normalize-package-data": "~2.3.5",
    "npm-cache-filename": "~1.0.2",
    "npm-install-checks": "~3.0.0",
    "npm-package-arg": "~4.2.0",
    "npm-registry-client": "~7.3.0",
    "npm-user-validate": "~0.1.5",
    "npmlog": "~4.0.1",
    "once": "~1.4.0",
    "opener": "~1.4.2",
    "osenv": "~0.1.3",
    "path-is-inside": "~1.0.2",
    "read": "~1.0.7",
    "read-cmd-shim": "~1.0.1",
    "read-installed": "~4.0.3",
    "read-package-json": "~2.0.4",
    "read-package-tree": "~5.1.5",
    "readable-stream": "~2.2.2",
    "realize-package-specifier": "~3.0.3",
    "request": "~2.79.0",
    "retry": "~0.10.0",
    "rimraf": "~2.5.4",
    "semver": "~5.3.0",
    "sha": "~2.0.1",
    "slide": "~1.1.6",
    "sorted-object": "~2.0.1",
    "sorted-union-stream": "~2.1.3",
    "strip-ansi": "~3.0.1",
    "tar": "~2.2.1",
    "text-table": "~0.2.0",
    "uid-number": "0.0.6",
    "umask": "~1.1.0",
    "unique-filename": "~1.1.0",
    "unpipe": "~1.0.0",
    "validate-npm-package-name": "~2.2.2",
    "which": "~1.2.12",
    "wrappy": "~1.0.2",
    "write-file-atomic": "~1.2.0"
  },
  "bundleDependencies": [
    "abbrev",
    "ansi-regex",
    "ansicolors",
    "ansistyles",
    "aproba",
    "archy",
    "asap",
    "chownr",
    "cmd-shim",
    "columnify",
    "config-chain",
    "debuglog",
    "dezalgo",
    "editor",
    "fs-vacuum",
    "fs-write-stream-atomic",
    "fstream",
    "fstream-npm",
    "glob",
    "graceful-fs",
    "has-unicode",
    "hosted-git-info",
    "iferr",
    "imurmurhash",
    "inflight",
    "inherits",
    "ini",
    "init-package-json",
    "JSONStream",
    "lockfile",
    "lodash._baseindexof",
    "lodash._baseuniq",
    "lodash._bindcallback",
    "lodash._cacheindexof",
    "lodash._createcache",
    "lodash._getnative",
    "lodash.clonedeep",
    "lodash.restparam",
    "lodash.union",
    "lodash.uniq",
    "lodash.without",
    "mkdirp",
    "node-gyp",
    "nopt",
    "normalize-git-url",
    "normalize-package-data",
    "npm-cache-filename",
    "npm-install-checks",
    "npm-package-arg",
    "npm-registry-client",
    "npm-user-validate",
    "npmlog",
    "once",
    "opener",
    "osenv",
    "path-is-inside",
    "read",
    "read-cmd-shim",
    "read-installed",
    "read-package-json",
    "read-package-tree",
    "readable-stream",
    "readdir-scoped-modules",
    "realize-package-specifier",
    "request",
    "retry",
    "rimraf",
    "semver",
    "sha",
    "slide",
    "sorted-object",
    "sorted-union-stream",
    "strip-ansi",
    "tar",
    "text-table",
    "uid-number",
    "umask",
    "unique-filename",
    "unpipe",
    "validate-npm-package-license",
    "validate-npm-package-name",
    "which",
    "wrappy",
    "write-file-atomic",
    "mississippi"
  ],
  "devDependencies": {
    "deep-equal": "~1.0.1",
    "marked": "~0.3.6",
    "marked-man": "~0.1.6",
    "npm-registry-couchapp": "~2.6.12",
    "npm-registry-mock": "~1.0.1",
    "require-inject": "~1.4.0",
    "sprintf-js": "~1.0.3",
    "standard": "~6.0.8",
    "tacks": "~1.2.2",
    "tap": "~8.0.1"
  },
  "scripts": {
    "dumpconf": "env | grep npm | sort | uniq",
    "prepublish": "node bin/npm-cli.js prune --prefix=. --no-global && rimraf test/*/*/node_modules && make doc-clean && make -j4 doc",
    "preversion": "bash scripts/update-authors.sh && git add AUTHORS && git commit -m \"update AUTHORS\" || true",
    "tap": "tap --timeout 300",
    "tap-cover": "tap --nyc-arg='--cache' --coverage --timeout 600",
    "test": "standard && npm run test-tap",
    "test-coverage": "npm run tap-cover -- \"test/tap/*.js\" \"test/network/*.js\" \"test/broken-under-*/*.js\"",
    "test-tap": "npm run tap -- \"test/tap/*.js\" \"test/network/*.js\" \"test/broken-under-*/*.js\"",
    "test-node": "tap --timeout 240 \"test/tap/*.js\" \"test/network/*.js\" \"test/broken-under-nyc*/*.js\""
  },
  "license": "Artistic-2.0"
}
`

**Comment by KenanY** [comment]
@androidABCD Your issue appears to be unrelated. Error message points to your internet connection.
