### ISSUE TITLE
"npm start" not working, it doesn't starts at all and keeps complaining about missing start script whereas that's not missing at all!

### ISSUE THREAD

**Issue by Farzad7** [npm/npm#15497]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Basically I'm trying to "npm start" but it gives me the following error despite I have the missing files "server.js" as my start script and "npm-debug.log" but still fails to run.

The funny thing is when I setup this project, it ran fine without a single problem... but since then didn't work at all...

I'm using Visual Studio Code.

#### How can the CLI team reproduce the problem?

Here is my npm-debug.log file:-

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build-css' ]
2 info using npm@3.10.10
3 info using node@v6.9.4
4 verbose run-script [ 'prebuild-css', 'build-css', 'postbuild-css' ]
5 info lifecycle trackerwebapp@1.0.0~prebuild-css: trackerwebapp@1.0.0
6 silly lifecycle trackerwebapp@1.0.0~prebuild-css: no script for prebuild-css, continuing
7 info lifecycle trackerwebapp@1.0.0~build-css: trackerwebapp@1.0.0
8 verbose lifecycle trackerwebapp@1.0.0~build-css: unsafe-perm in lifecycle true
9 verbose lifecycle trackerwebapp@1.0.0~build-css: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;c:\Users\soleif\Documents\Projects\TrackerWebApp\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\oracle\product\10.2.0.5\client\bin;C:\Oracle\product\11.2.0\client\bin;C:\oraclexe\app\oracle\product\11.2.0\server\bin;C:\Oracle\product\11.2.0\client;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;c:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\VSShell\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\IDE\PrivateAssemblies\;C:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files (x86)\MySQL\MySQL Utilities 1.3.4\;C:\Program Files (x86)\Curl\;C:\Program Files (x86)\GNU\GnuPG\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\WinMerge;C:\Windows\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Users\soleif\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Users\soleif\AppData\Roaming\npm;C:\Users\soleif\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\soleif\AppData\Local\atom\bin;C:\Users\soleif\AppData\Roaming\npm
10 verbose lifecycle trackerwebapp@1.0.0~build-css: CWD: c:\Users\soleif\Documents\Projects\TrackerWebApp
11 silly lifecycle trackerwebapp@1.0.0~build-css: Args: [ '/d /s /c',
11 silly lifecycle   'node-sass --include-path scss src/css/style.scss public/css/style.css' ]
12 silly lifecycle trackerwebapp@1.0.0~build-css: Returned: code: 1  signal: null
13 info lifecycle trackerwebapp@1.0.0~build-css: Failed to exec build-css script
14 verbose stack Error: trackerwebapp@1.0.0 build-css: `node-sass --include-path scss src/css/style.scss public/css/style.css`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid trackerwebapp@1.0.0
16 verbose cwd c:\Users\soleif\Documents\Projects\TrackerWebApp
17 error Windows_NT 6.1.7601
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build-css"
19 error node v6.9.4
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error trackerwebapp@1.0.0 build-css: `node-sass --include-path scss src/css/style.scss public/css/style.css`
22 error Exit status 1
23 error Failed at the trackerwebapp@1.0.0 build-css script 'node-sass --include-path scss src/css/style.scss public/css/style.css'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the trackerwebapp package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node-sass --include-path scss src/css/style.scss public/css/style.css
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs trackerwebapp
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls trackerwebapp
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

And here is my package.json

{
  "name": "trackerwebapp",
  "version": "1.0.0",
  "description": "Tracker Web App",
  "main": "server.js",
  "scripts": {
    "start": "node server.js",
    "test": "test/",
    "build-css": "node-sass --include-path scss src/css/style.scss public/css/style.css",
    "watch-css": "nodemon -e scss -x \"npm run build-css\"",
    "build-js": "browserify src/js/script.js -o public/js/script.js",
    "watch-js": "watchify src/js/script.js -o public/js/script.js"
  },
  "author": "Tracker",
  "license": "ISC",
  "dependencies": {
    "bootstrap": "^3.3.7",
    "browserify": "^13.3.0",
    "express": "^4.14.0",
    "handlebars": "^4.0.6",
    "jquery": "^3.1.1",
    "nodemon": "^1.11.0"
  },
   "devDependencies": {
    "watchify": "^3.8.0"
  }
}

Any really is really appreciated as this is holding me back on my project.

**Comment by Charlotteis** [comment]
The error is:

> Failed at the trackerwebapp@1.0.0 build-css script 'node-sass --include-path scss src/css/style.scss public/css/style.css'.

What happens if you do 

```
node-sass --include-path scss src/css/style.scss public/css/style.css
```

in the command line, what error do you get?

**Comment by Farzad7** [comment]
Funny thing is it works when I try running it through debug mode in Visual Code by pressing that little bug icon on the left... but as soon I terminate the debug mode it all fails again

The command line does the same thing...

**Comment by prahaladbelavadi** [comment]
What server are you running your server on ?
In some cases such as the one for Angular 1 and 2, port has to be switched from 8000 to 8080
Check [issue](https://github.com/angular/angular-phonecat/issues/180) for further details.
