### ISSUE TITLE
Refusing to install selenium-webdriver as a dependency of itself

### ISSUE THREAD

**Issue by Lilly2016** [npm/npm#15494]
I'm new to selenium/node and npm is doing something I don't understand.

#### What's going wrong?

Refusing to install selenium-webdriver as a dependency of itself

#### How can the CLI team reproduce the problem?

<!-
    How to reproduce the problem.
    1. Downloaded/installed node.
    2. Downloaded selenium webdriver
    3. Run sudo npm install selenium-webdriver in the correct path
    4. Returns error:
        npm ERR! Darwin 14.5.0
        npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "selenium-webdriver"
        npm ERR! node v6.9.4
        npm ERR! npm  v3.10.10
        npm ERR! code ENOSELF

        npm ERR! Refusing to install selenium-webdriver as a dependency of itself

Debug log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'selenium-webdriver' ]
2 info using npm@3.10.10
3 info using node@v6.9.4
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData selenium-webdriver
8 silly fetchNamedPackageData selenium-webdriver
9 silly mapToRegistry name selenium-webdriver
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'selenium-webdriver',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'selenium-webdriver',
12 silly mapToRegistry   name: 'selenium-webdriver',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/selenium-webdriver
14 verbose request uri https://registry.npmjs.org/selenium-webdriver
15 verbose request no auth needed
16 info attempt registry request try #1 at 12:43:52 PM
17 verbose request id 53e332bb1d46ad81
18 verbose etag W/"58633503-ed78"
19 verbose lastModified Wed, 28 Dec 2016 03:44:03 GMT
20 http request GET https://registry.npmjs.org/selenium-webdriver
21 http 304 https://registry.npmjs.org/selenium-webdriver
22 verbose headers { date: 'Mon, 16 Jan 2017 01:43:53 GMT',
22 verbose headers   via: '1.1 varnish',
22 verbose headers   'cache-control': 'max-age=300',
22 verbose headers   etag: 'W/"58633503-ed78"',
22 verbose headers   age: '0',
22 verbose headers   connection: 'keep-alive',
22 verbose headers   'x-served-by': 'cache-mel6522-MEL',
22 verbose headers   'x-cache': 'HIT',
22 verbose headers   'x-cache-hits': '1',
22 verbose headers   'x-timer': 'S1484531033.154081,VS0,VE13',
22 verbose headers   vary: 'Accept-Encoding' }
23 silly get cb [ 304,
23 silly get   { date: 'Mon, 16 Jan 2017 01:43:53 GMT',
23 silly get     via: '1.1 varnish',
23 silly get     'cache-control': 'max-age=300',
23 silly get     etag: 'W/"58633503-ed78"',
23 silly get     age: '0',
23 silly get     connection: 'keep-alive',
23 silly get     'x-served-by': 'cache-mel6522-MEL',
23 silly get     'x-cache': 'HIT',
23 silly get     'x-cache-hits': '1',
23 silly get     'x-timer': 'S1484531033.154081,VS0,VE13',
23 silly get     vary: 'Accept-Encoding' } ]
24 verbose etag https://registry.npmjs.org/selenium-webdriver from cache
25 verbose get saving selenium-webdriver to /Users/yeesoonkakku2/.npm/registry.npmjs.org/selenium-webdriver/.cache.json
26 verbose correctMkdir /Users/yeesoonkakku2/.npm correctMkdir not in flight; initializing
27 silly install normalizeTree
28 silly loadCurrentTree Finishing
29 silly loadIdealTree Starting
30 silly install loadIdealTree
31 silly cloneCurrentTree Starting
32 silly install cloneCurrentTreeToIdealTree
33 silly cloneCurrentTree Finishing
34 silly loadShrinkwrap Starting
35 silly install loadShrinkwrap
36 silly loadShrinkwrap Finishing
37 silly loadAllDepsIntoIdealTree Starting
38 silly install loadAllDepsIntoIdealTree
39 silly rollbackFailedOptional Starting
40 silly rollbackFailedOptional Finishing
41 silly runTopLevelLifecycles Finishing
42 silly install printInstalled
43 verbose stack Error: Refusing to install selenium-webdriver as a dependency of itself
43 verbose stack     at checkSelf (/usr/local/lib/node_modules/npm/lib/install/validate-args.js:53:14)
43 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
43 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
43 verbose stack     at chain (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
43 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/validate-args.js:16:5
43 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
43 verbose stack     at Array.forEach (native)
43 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
43 verbose stack     at Array.forEach (native)
43 verbose stack     at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
44 verbose cwd /Users/yeesoonkakku2/Documents/NODE/node_modules/selenium-webdriver
45 error Darwin 14.5.0
46 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "selenium-webdriver"
47 error node v6.9.4
48 error npm  v3.10.10
49 error code ENOSELF
50 error Refusing to install selenium-webdriver as a dependency of itself
51 error If you need help, you may report this error at:
51 error     <https://github.com/npm/npm/issues>
52 verbose exit [ 1, true ]
 
-->

Any assistance would be greatly appreciated. Thanks in advance,

Leila

**Comment by Charlotteis** [comment]
Hi @Lilly2016!

What does your `package.json` look like?

**Comment by KenanY** [comment]
Closing as abandoned.

**Comment by StaudenmannM** [comment]
Hi,
just find a potential answer to this issue. If you used selenium-webdriver as project name in package.json, it create a conflict when you try to add the selenium-webdriver module. see this example from watson as example: http://thisdavej.com/node-newbie-error-npm-refusing-to-install-package-as-a-dependency-of-itself/
