### ISSUE TITLE
case sensitive module name in a case insensitive filesystem

### ISSUE THREAD

**Issue by zandrart** [npm/npm#15493]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [X] npm is producing an incorrect install.
  - [X] npm is doing something I don't understand.
  - [] Other (_see below for feature requests_):

#### What's going wrong?

both `a` and `A` are modules in npm.  Depending on order in which you install them in OSX, you get different results:

```
$ npm install A
$ npm install a
$ node -pe 'require("A")'
{ Promise: [Function: Promise] }

$ npm uninstall a
$ npm uninstall A
$ npm install a
$ npm install A
$ node -pe 'require("A")'
{ when: 
   { [Function: when]
     calling_module: 
      Module {
        id: '[eval]',
        exports: {},
        parent: undefined,
        filename: '/Users/rajesh/Private/dev/scratch/[eval]',
        loaded: false,
        children: [Object],
        paths: [Object] } },
  mock: [Function: create],
  expectRequire: { [Function: expect] reset: [Function] },
  requireMock: { [Function: create] reset: [Function] },
  then: { [Function: newThen] resolve: [Function], reject: [Function] } }
```

node's module resolution mechanism appears to follow the case sensitivity of the file system but the npm registry is case sensitive

**Comment by kevintelford** [comment]
+1
I seem to be having the same issue as well (node v6.9.5, npm 3.10.10)
