### ISSUE TITLE
Something wrong with the NPM every time I install what ever require NPM always failed process

### ISSUE THREAD

**Issue by ryanpagaduan24** [npm/npm#15505]
#### I'm opening this issue because:
  - [ ] I'm new to npm
  - [ ] I'm new to webpack and any other stuff
  - [ ] I'm going to blue just only installing reactJS

npm ERR! Linux 4.4.0-22-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "browserify"
npm ERR! node v5.12.0
npm ERR! npm  v4.0.5
npm ERR! path /usr/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/usr/lib/node_modules'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, access '/usr/lib/node_modules']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/lib/node_modules' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/Sites/react-samples/react-pure/npm-debug.log

**Comment by ryanpagaduan24** [comment]
- [ ] node version v5.12.0
- [ ] npm version  4.0.5

**Comment by watilde** [comment]
Hello! The error said the permission of your directory is wrong.
> npm ERR! Error: EACCES: permission denied, access '/usr/lib/node_modules'

Could you check this doc to resolve it?
https://github.com/npm/npm/wiki/Troubleshooting#permission-error

**Comment by ryanpagaduan24** [comment]
#### Thank you for  reply Mr. watilde
#### I am beginners about NPM and i tried to research about the error and still got no idea. I'm a `Windows` user but Im using `Vagrant` to run my project on `Linux`.

#### The following line's at the bottom is the error when i try to install webpack for new project directory for testing. I can't start coding for webpack tutorial because same issue still pop up on my terminal.

### My code start here

     vagrant@homestead:~/Sites/react-samples/react-pure$ npm init -y
     Wrote to /home/vagrant/Sites/react-samples/react-pure/package.json:

    {
       "name": "myreact",
       "version": "1.0.0",
       "description": "sample test for react",
       "main": "index.js",
       "scripts": {
         "test": "echo \"Error: no test specified\" && exit 1"
       },
       "author": "Ryan Pagaduan",
       "license": "ISC",
       "keywords": []
     }


     vagrant@homestead:~/Sites/react-samples/react-pure$ npm install --save-dev webpack@beta
     myreact@1.0.0 /home/vagrant/Sites/react-samples/react-pure
     ├── ajv@4.10.4  extraneous
     ├── ajv-keywords@1.5.0  extraneous
     ├── enhanced-resolve@3.0.3  extraneous
     ├── interpret@1.0.1  extraneous
     ├── json-loader@0.5.4  extraneous
     ├── loader-runner@2.2.0  extraneous
     ├── loader-utils@0.2.16  extraneous
     ├── mkdirp@0.5.1  extraneous
     ├── node-libs-browser@2.0.0  extraneous
     ├── supports-color@3.2.3  extraneous
     ├── uglify-js@2.7.5  extraneous
     ├── watchpack@1.2.0  extraneous
     ├── webpack-sources@0.1.4  extraneous
     └── yargs@6.6.0  extraneous

     npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
     npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
     npm WARN myreact@1.0.0 No repository field.
     npm ERR! Linux 4.4.0-22-generic
     npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save-dev" "webpack@beta"
     npm ERR! node v6.9.4
     npm ERR! npm  v3.10.10
     npm ERR! path ../acorn/bin/acorn
     npm ERR! code EPROTO
     npm ERR! errno -71
     npm ERR! syscall symlink

     npm ERR! EPROTO: protocol error, symlink '../acorn/bin/acorn' -> '/home/vagrant/Sites/react-samples/react-pure/node_modules/.bin/acorn'
     npm ERR!
     npm ERR! If you need help, you may report this error at:
     npm ERR!     <https://github.com/npm/npm/issues>

     npm ERR! Please include the following file with any support request:
     npm ERR!     /home/vagrant/Sites/react-samples/react-pure/npm-debug.log
     vagrant@homestead:~/Sites/react-samples/react-pure$

#### The first issue that come's in mind is may be because im using vagrant
#### I really appreciate who can help me about this isuue

**Comment by KenanY** [comment]
@ryanpagaduan24 Have you tried using the `--no-bin-links` flag?

**Comment by ryanpagaduan24** [comment]
When I tried to run first on vagrant terminal I get the error, but when I run again the code in windows after running on vagrant its work's but sometimes it fails.

Another thing is when using `npm install <package> --save-dev` on vagrant it fails, but when Im using `npm install --save-dev <package> ` it works.

I don't know main the problem but it works now for me.
Thank You guy's for the assist

**Comment by ryanpagaduan24** [comment]
`--no-bin-links` flag works ok for me thanks
