### ISSUE TITLE
issue while buiding ionic 

### ISSUE THREAD

**Issue by JYOTHISHPJ** [npm/npm#15506]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'v' ]
2 info using npm@4.0.5
3 info using node@v7.4.0
4 verbose config Skipping project config: C:\Users\E0059-PC/.npmrc. (matches userconfig)
5 verbose stack Error: Invalid package.json
5 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\view.js:84:30
5 verbose stack     at ReadFileContext.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:90:21)
5 verbose stack     at ReadFileContext.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16)
5 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:336:13)
6 verbose cwd C:\Users\E0059-PC\Desktop\myApp
7 error Windows_NT 6.3.9600
8 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "v"
9 error node v7.4.0
10 error npm  v4.0.5
11 error Invalid package.json
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@JYOTHISHPJ What behavior are you expecting when you run `npm v`?

**Comment by JYOTHISHPJ** [comment]
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "v"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5

npm ERR! Invalid package.json
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\E0059-PC\Desktop\npm-debug.log

**Comment by JYOTHISHPJ** [comment]
i cannot run or build the project it show 

Error Initializing app: Error: getaddrinfo ENOTFOUND codeload.github.com codeloa
d.github.com:443
 Error: getaddrinfo ENOTFOUND codeload.github.com codeload.github.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)

**Comment by KenanY** [comment]
@JYOTHISHPJ Looks like an issue with your internet connection, I think.

**Comment by JYOTHISHPJ** [comment]
actually the problem has solved after the updation of cordova to 6.0 .. 
thanks man for your time...
