### ISSUE TITLE
npm install appium failed，

### ISSUE THREAD

**Issue by XLTH** [npm/npm#15503]
#### I'm opening this issue because:

  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.

#### What's going wrong?

![image](https://cloud.githubusercontent.com/assets/17403786/22015859/c3715b94-dcde-11e6-8ca5-0aefc7358dad.png)
#### How can the CLI team reproduce the problem?
When I use "npm install -g appium" to update appium,this happend.I also try add sudo befor this commend.All commend didn't work.

### supporting information:

 - `npm -v` prints:
3.9.3
 - `node -v` prints:
v6.2.1
 - `npm config get registry` prints:
https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?:
OS X
 - Container:

   - [ ] I develop using Vagrant on OS X or Linux.

**Comment by rajshah** [comment]
- [ ] npm install -g appium is failing on MAC OS X 10.11.6 with below config.

java version "1.8.0_112"
Homebrew 1.1.7
npm -v => 4.1.1
node -v => v7.4.0

$ npm install -g appium 
npm WARN retry will retry, error on last attempt: Error: ENOENT: no such file or directory, rename '/var/folders/zm/tjvfhkf91pxb14hm4v504z_1yl_7dt/T/npm-10168-4b25d4d5/registry.npmjs.org/appium-adb/-/appium-adb-2.9.2.tgz.1958027417' -> '/var/folders/zm/tjvfhkf91pxb14hm4v504z_1yl_7dt/T/npm-10168-4b25d4d5/registry.npmjs.org/appium-adb/-/appium-adb-2.9.2.tgz'
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/7.4.0/bin/node" "/usr/local/bin/npm" "install" "-g" "appium"
npm ERR! node v7.4.0
npm ERR! npm  v4.1.1

npm ERR! tarball.destroy is not a function
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN retry will retry, error on last attempt: Error: ENOENT: no such file or directory, open '/var/folders/zm/tjvfhkf91pxb14hm4v504z_1yl_7dt/T/npm-10168-4b25d4d5/registry.npmjs.org/appium-adb/-/appium-adb-2.9.2.tgz.1175230709'
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/7.4.0/bin/node" "/usr/local/bin/npm" "install" "-g" "appium"
npm ERR! node v7.4.0
npm ERR! npm  v4.1.1

npm ERR! tarball.destroy is not a function
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/7.4.0/bin/node" "/usr/local/bin/npm" "install" "-g" "appium"
npm ERR! node v7.4.0
npm ERR! npm  v4.1.1
npm ERR! path /var/folders/zm/tjvfhkf91pxb14hm4v504z_1yl_7dt/T/npm-10168-4b25d4d5/registry.npmjs.org/appium-adb/-/appium-adb-2.9.2.tgz.2215844425
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/var/folders/zm/tjvfhkf91pxb14hm4v504z_1yl_7dt/T/npm-10168-4b25d4d5/registry.npmjs.org/appium-adb/-/appium-adb-2.9.2.tgz.2215844425'
npm ERR! enoent ENOENT: no such file or directory, open '/var/folders/zm/tjvfhkf91pxb14hm4v504z_1yl_7dt/T/npm-10168-4b25d4d5/registry.npmjs.org/appium-adb/-/appium-adb-2.9.2.tgz.2215844425'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/7.4.0/bin/node" "/usr/local/bin/npm" "install" "-g" "appium"
npm ERR! node v7.4.0
npm ERR! npm  v4.1.1

npm ERR! tarball.destroy is not a function
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/rajshah/npm-debug.log - DOES NOT EXISTS.

**Comment by rajshah** [comment]
https://github.com/npm/npm/issues/14394 suggests - npm cache clean 
npm install -g appium is working for me.

**Comment by XLTH** [comment]
thank you!I will try your suggests!
