### ISSUE TITLE
not able to run the angular2 project

### ISSUE THREAD

**Issue by LijinDurairaj** [npm/npm#15508]
#### I'm opening this issue because:
  - [x] npm is doing something I don't understand.

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a corporate network to connect to the npm registry.
   
 - Container:
   - [ ] I develop using Windows.

**Comment by KenanY** [comment]
Closing since this issue is blank.
