### ISSUE TITLE
Can't install 1.6.3 in OSX 10.12.2

### ISSUE THREAD

**Issue by Manikanta29** [npm/npm#15514]
OSX:10.12.2 

Displaying below error in terminal. 

manikantav$ npm install -g appium@1.6.3
npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "appium@1.6.3"
npm ERR! node v6.9.1
npm ERR! npm  v4.0.3

npm ERR! Cannot read property 'deep-extend' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "appium@1.6.3"
npm ERR! node v6.9.1
npm ERR! npm  v4.0.3

npm ERR! Cannot read property 'extsprintf' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mani/npm-debug.log

Please help me, how to install

**Comment by KenanY** [comment]
Looks like https://github.com/npm/npm/issues/15096

**Comment by Manikanta29** [comment]
Tried with both the commands as mentioned in #15096. still not able to update the appium 

IMCHLT191:~ manikantav$ sudo npm install -f -g npm#3
npm WARN using --force I sure hope you know what you are doing.
npm ERR! addLocal Could not install /Users/manikantav/npm#3
npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-f" "-g" "npm#3"
npm ERR! node v6.9.1
npm ERR! npm  v4.0.3

npm ERR! Cannot read property 'path' of null
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/manikantav/npm-debug.log

IMCHLT191:~ manikantav$ sudo npm install -f -g appium@1.6.1
npm WARN using --force I sure hope you know what you are doing.
npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-f" "-g" "appium@1.6.1"
npm ERR! node v6.9.1
npm ERR! npm  v4.0.3

npm ERR! Cannot read property 'deep-extend' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-f" "-g" "appium@1.6.1"
npm ERR! node v6.9.1
npm ERR! npm  v4.0.3

npm ERR! Cannot read property 'extsprintf' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/manikantav/npm-debug.log
IMCHLT191:~ manikantav$

**Comment by Crissisme** [comment]
Running into the same~!!!

**Comment by Manikanta29** [comment]
Solution: 

if you have npm 4.0.3, it's not possible to get the latest appium.  

Get the latest npm with command : npm install -g npm@latest
You will get npm:4.1.1

And run the command: npm install -g appium 
You will get appium:1.6.3
