### ISSUE TITLE
Can't install react-redux

### ISSUE THREAD

**Issue by xpfei** [npm/npm#15513]
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "react-redux" "--save-dev"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ENOSELF

npm ERR! Refusing to install react-redux as a dependency of itself
npm ERR!

**Comment by Charlotteis** [comment]
Hi there, 

What does your `package.json` read?

Please make sure that `"name"` is not `"react-redux"`.

**Comment by KenanY** [comment]
Closing as abandoned.

**Comment by siddeshwarnavink** [comment]
May be your project name is **react-redux** because mine was and i changed!
