### ISSUE TITLE
Wrong version when using commit-ish dependencies

### ISSUE THREAD

**Issue by pjasiun** [npm/npm#15518]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Consider project X: with the dependencies A and B, taken form github. X use A in the version (hash) #1234567.

```json
{
  "name": "X",
  "dependencies": {
    "A": "githubname/A#1234567",
    "B": "githubname/B"
  }
}
```

At the same time B use A master version.

```json
{
  "name": "B",
  "dependencies": {
    "A": "githubname/A"
  }
}
```

### Expected result:
```
X/
  node_module/
    A/ (#1234567)
    B/
      node_module/
        A/
```

### Actual result:
```
X/
  node_module/
    A/
    B/
```

### supporting information:

 - `npm -v` prints:
`3.10.3`
 - `node -v` prints:
`v6.2.2`
 - `npm config get registry` prints:
`https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?:
OS X
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by pjasiun** [comment]
Unfortunately, it occurs randomly and it's hard to find stable scenario there the error occurs.

**Comment by scofalik** [comment]
Same (incorrect) results happen for `npm -v`: `4.0.5` and `node -v`: `v6.9.2`. After removing `node_modules/B` and running `npm install` again, the `B` package is installed in correct version.
