### ISSUE TITLE
npm unpublish not working

### ISSUE THREAD

**Issue by CKP00N** [npm/npm#15510]
#### I'm opening this issue because:

  - [ ] npm unpublish is not working

#### What's going wrong?
It fails to delete the package.

### supporting information:

 - `npm -v` prints:2.15.9
 - `node -v` prints:4.5.0
 - `npm config get registry` prints:https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?:Windows
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@CKP00N Please email `support@npmjs.com` for package unpublishes.
