### ISSUE TITLE
Cannot install the tfx-client using npm

### ISSUE THREAD

**Issue by ravishankersr** [npm/npm#15526]
![npm error](https://cloud.githubusercontent.com/assets/25210123/22083342/b3df25a6-dd99-11e6-8496-1ed8f3ebad63.PNG)
#### I'm opening this issue because:

  - [ ] npm is producing an incorrect install.
 

#### What's going wrong?

Trying to create the .vsix package from the files and using npm but i have the error as enclosed

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

![image](https://cloud.githubusercontent.com/assets/25210123/22083376/dfeb38d8-dd99-11e6-93b5-dfbfe26209a6.png)

**Comment by joshi-mehul** [comment]
did you run it with admin access?

**Comment by ravishankersr** [comment]
I have this working, thanks for the reply Joshi.

Best regards,
Ravi Shankar Reddy Sudhireddy

External service provider at Siemens Medical Solutions USA, Inc.
HC IT PRS PLM USA
333 Coney Street
Walpole, MA 02032, USA
mailto:ravi.sudhireddy.ext@siemens-healthineers.com
www.usa.siemens.com/healthineers<http://www.usa.siemens.com/healthineers>

**Comment by KenanY** [comment]
Closing as resolved then.
