### ISSUE TITLE
npm unpublish <my-packge> --force  but returned 400 

### ISSUE THREAD

**Issue by xiuhonglee** [npm/npm#15528]
#### I'm opening this issue because:
> I want to delete my package on npm registry but returned 400
```shell
$ npm unpublish <my-packge> --force
```
**result**
```shell
npm WARN using --force I sure hope you know what you are doing.
npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/xiuhong/.nvm/versions/node/v5.0.0/bin/node" "/Users/xiuhong/.nvm/versions/node/v5.0.0/bin/npm" "unpublish" "ssssasfdasdfxiuhongfortest" "--force"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code E400

npm ERR! Registry returned 400 for DELETE on https://registry.npmjs.org/ssssasfdasdfxiuhongfortest/-rev/1-df72a11ccb89e170cdb61d34c7429161
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/xiuhong/npmtest/npm-debug.log
```

#### my npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/Users/xiuhong/.nvm/versions/node/v5.0.0/bin/node',
1 verbose cli   '/Users/xiuhong/.nvm/versions/node/v5.0.0/bin/npm',
1 verbose cli   'unpublish',
1 verbose cli   'ssssasfdasdfxiuhongfortest',
1 verbose cli   '--force' ]
2 info using npm@3.3.6
3 info using node@v5.0.0
4 warn using --force I sure hope you know what you are doing.
5 silly unpublish args[0] ssssasfdasdfxiuhongfortest
6 silly unpublish thing Result {
6 silly unpublish   raw: 'ssssasfdasdfxiuhongfortest',
6 silly unpublish   scope: null,
6 silly unpublish   name: 'ssssasfdasdfxiuhongfortest',
6 silly unpublish   rawSpec: '',
6 silly unpublish   spec: '*',
6 silly unpublish   type: 'range' }
7 verbose getPublishConfig null
8 silly ls normalized ssssasfdasdfxiuhongfortest
9 silly gentlyRm /Users/xiuhong/.npm/ssssasfdasdfxiuhongfortest is being purged
10 verbose gentlyRm don't care about contents; nuking /Users/xiuhong/.npm/ssssasfdasdfxiuhongfortest
11 silly mapToRegistry name ssssasfdasdfxiuhongfortest
12 silly mapToRegistry using default registry
13 silly mapToRegistry registry https://registry.npmjs.org/
14 silly mapToRegistry uri https://registry.npmjs.org/ssssasfdasdfxiuhongfortest
15 verbose get GET as part of write; not caching result
16 verbose request uri https://registry.npmjs.org/ssssasfdasdfxiuhongfortest?write=true
17 verbose request no auth needed
18 info attempt registry request try #1 at 10:27:11
19 verbose request using bearer token for auth
20 verbose request id 215ce9e040745195
21 http request GET https://registry.npmjs.org/ssssasfdasdfxiuhongfortest?write=true
22 http 200 https://registry.npmjs.org/ssssasfdasdfxiuhongfortest?write=true
23 verbose headers { server: 'CouchDB/1.6.1 (Erlang OTP/R16B03)',
23 verbose headers   'content-type': 'application/json',
23 verbose headers   etag: '"5848063f-4b4"',
23 verbose headers   'content-encoding': 'gzip',
23 verbose headers   'cache-control': 'max-age=0',
23 verbose headers   'transfer-encoding': 'chunked',
23 verbose headers   'accept-ranges': 'bytes',
23 verbose headers   date: 'Thu, 19 Jan 2017 02:27:15 GMT',
23 verbose headers   via: '1.1 varnish',
23 verbose headers   connection: 'keep-alive',
23 verbose headers   'x-served-by': 'cache-sjc3127-SJC',
23 verbose headers   'x-cache': 'MISS',
23 verbose headers   'x-cache-hits': '0',
23 verbose headers   'x-timer': 'S1484792835.629032,VS0,VE134',
23 verbose headers   vary: 'Accept-Encoding' }
24 silly get cb [ 200,
24 silly get   { server: 'CouchDB/1.6.1 (Erlang OTP/R16B03)',
24 silly get     'content-type': 'application/json',
24 silly get     etag: '"5848063f-4b4"',
24 silly get     'content-encoding': 'gzip',
24 silly get     'cache-control': 'max-age=0',
24 silly get     'transfer-encoding': 'chunked',
24 silly get     'accept-ranges': 'bytes',
24 silly get     date: 'Thu, 19 Jan 2017 02:27:15 GMT',
24 silly get     via: '1.1 varnish',
24 silly get     connection: 'keep-alive',
24 silly get     'x-served-by': 'cache-sjc3127-SJC',
24 silly get     'x-cache': 'MISS',
24 silly get     'x-cache-hits': '0',
24 silly get     'x-timer': 'S1484792835.629032,VS0,VE134',
24 silly get     vary: 'Accept-Encoding' } ]
25 verbose get saving ssssasfdasdfxiuhongfortest to /Users/xiuhong/.npm/registry.npmjs.org/ssssasfdasdfxiuhongfortest_3Fwrite_3Dtrue/.cache.json
26 info unpublish No version specified, removing all
27 verbose request uri https://registry.npmjs.org/ssssasfdasdfxiuhongfortest/-rev/1-df72a11ccb89e170cdb61d34c7429161
28 verbose request sending authorization for write operation
29 info attempt registry request try #1 at 10:27:14
30 verbose request using bearer token for auth
31 http request DELETE https://registry.npmjs.org/ssssasfdasdfxiuhongfortest/-rev/1-df72a11ccb89e170cdb61d34c7429161
32 http 400 https://registry.npmjs.org/ssssasfdasdfxiuhongfortest/-rev/1-df72a11ccb89e170cdb61d34c7429161
33 verbose headers { 'content-type': 'application/json',
33 verbose headers   'cache-control': 'max-age=300',
33 verbose headers   'content-length': '17',
33 verbose headers   'accept-ranges': 'bytes',
33 verbose headers   date: 'Thu, 19 Jan 2017 02:27:17 GMT',
33 verbose headers   via: '1.1 varnish',
33 verbose headers   connection: 'keep-alive',
33 verbose headers   'x-served-by': 'cache-sjc3146-SJC',
33 verbose headers   'x-cache': 'MISS',
33 verbose headers   'x-cache-hits': '0',
33 verbose headers   'x-timer': 'S1484792836.870431,VS0,VE223',
33 verbose headers   vary: 'Accept-Encoding' }
34 verbose request invalidating /Users/xiuhong/.npm/registry.npmjs.org/ssssasfdasdfxiuhongfortest on DELETE
35 verbose stack Error: Registry returned 400 for DELETE on https://registry.npmjs.org/ssssasfdasdfxiuhongfortest/-rev/1-df72a11ccb89e170cdb61d34c7429161
35 verbose stack     at makeError (/Users/xiuhong/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
35 verbose stack     at CachingRegistryClient.<anonymous> (/Users/xiuhong/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:242:14)
35 verbose stack     at Request._callback (/Users/xiuhong/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
35 verbose stack     at Request.self.callback (/Users/xiuhong/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/request/request.js:198:22)
35 verbose stack     at emitTwo (events.js:87:13)
35 verbose stack     at Request.emit (events.js:172:7)
35 verbose stack     at Request.<anonymous> (/Users/xiuhong/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/request/request.js:1063:14)
35 verbose stack     at emitOne (events.js:82:20)
35 verbose stack     at Request.emit (events.js:169:7)
35 verbose stack     at IncomingMessage.<anonymous> (/Users/xiuhong/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/request/request.js:1009:12)
36 verbose statusCode 400
37 verbose pkgid ssssasfdasdfxiuhongfortest
38 verbose cwd /Users/xiuhong/npmtest
39 error Darwin 14.5.0
40 error argv "/Users/xiuhong/.nvm/versions/node/v5.0.0/bin/node" "/Users/xiuhong/.nvm/versions/node/v5.0.0/bin/npm" "unpublish" "ssssasfdasdfxiuhongfortest" "--force"
41 error node v5.0.0
42 error npm  v3.3.6
43 error code E400
44 error Registry returned 400 for DELETE on https://registry.npmjs.org/ssssasfdasdfxiuhongfortest/-rev/1-df72a11ccb89e170cdb61d34c7429161
45 error If you need help, you may report this error at:
45 error     <https://github.com/npm/npm/issues>
46 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@xiuhonglee Please email `support@npmjs.com` for package unpublishes.

**Comment by davidpelayo** [comment]
@KenanY same happening here. Why this?

**Comment by legodude17** [comment]
The registry doesn't support unpublishing after 24 hours. So you email `npm` support.
