### ISSUE TITLE
atom.io package installation error (npm)

### ISSUE THREAD

**Issue by easy01** [npm/npm#15524]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [X ] Other (_see below for feature requests_):

#### What's going wrong?
I have searched so far, but nothing helped.
I have installed the editor Atom.io. I want to install packages but I am getting the error:
http://blog.npmjs.org/post/78165272245/more-help-with-selfsignedcertinchain-and-npm

I have followed the instructions here:
http://blog.npmjs.org/post/78165272245/more-help-with-selfsignedcertinchain-and-npm

I guess the command _npm config set ca=""_  worked, because no error message was returned.
But the command _npm install npm -g --ca=null_ returns an error (see log file and picture).

#### How can the CLI team reproduce the problem?
See log file and picture.

### supporting information:
- npm gist: https://gist.github.com/easy01/8f3ce86bd53c92a737163e37376c9870
 - `npm -v` prints: 3.10.10
 - `node -v` prints: v6.9.4
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows 8.1 x64
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by easy01** [comment]
Isn't there anybody that may help?

**Comment by legodude17** [comment]
Try installing the latest version of `npm`.

**Comment by KenanY** [comment]
Closing as abandoned.
