### ISSUE TITLE
npm install vuex --save error

### ISSUE THREAD

**Issue by hzdzlwh** [npm/npm#15529]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
 npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administrator.US
ER-20150612OL\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "insta
ll" "vuex" "--save"
npm ERR! node v4.2.2
npm ERR! npm  v3.0.0
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #2
npm ERR! typeerror     at exports.saveRequested (C:\Users\Administrator.USER-201
50612OL\AppData\Roaming\npm\node_modules\npm\lib\install\save.js:18:3)
npm ERR! typeerror     at Object.Installer.saveToDependencies (C:\Users\Administ
rator.USER-20150612OL\AppData\Roaming\npm\node_modules\npm\lib\install.js:502:3)

npm ERR! typeerror     at Array.<anonymous> (C:\Users\Administrator.USER-2015061
2OL\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\bind-actor.js:15
:8)
npm ERR! typeerror     at LOOP (C:\Users\Administrator.USER-20150612OL\AppData\R
oaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
npm ERR! typeerror     at C:\Users\Administrator.USER-20150612OL\AppData\Roaming
\npm\node_modules\npm\node_modules\slide\lib\chain.js:18:7
npm ERR! typeerror     at Object.Installer.finishTracker (C:\Users\Administrator
.USER-20150612OL\AppData\Roaming\npm\node_modules\npm\lib\install.js:279:3)
npm ERR! typeerror     at Array.<anonymous> (C:\Users\Administrator.USER-2015061
2OL\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\bind-actor.js:15
:8)
npm ERR! typeerror     at LOOP (C:\Users\Administrator.USER-20150612OL\AppData\R
oaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
npm ERR! typeerror     at C:\Users\Administrator.USER-20150612OL\AppData\Roaming
\npm\node_modules\npm\node_modules\slide\lib\chain.js:18:7
npm ERR! typeerror     at Object.Installer.runTopLevelLifecycles (C:\Users\Admin
istrator.USER-20150612OL\AppData\Roaming\npm\node_modules\npm\lib\install.js:475
:28)
npm ERR! typeerror This is an error with npm itself. Please report this error at
### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
This seems to be a bug in `npm`. Thank you for filing this!

cc @iarna

**Comment by KenanY** [comment]
@hzdzlwh Does this also occur with `npm@4`?

**Comment by hzdzlwh** [comment]
no occurred. thank you!
