### ISSUE TITLE
404 _Packaging is not in the npm registry

### ISSUE THREAD

**Issue by cwoodland** [npm/npm#15527]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [X] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I am using VSTS Package Management Services.
My .npmrc reads as follows:

**********************************************************
registry=https://connectionseducation.pkgs.visualstudio.com/_packaging/connections-education-poc2@Prerelease/npm/registry
always-auth=true
**********************************************************

When I run npm i I get the error:
**404 _packaging is not in the npm registry.**
Can we not have underscore in our registry uris?

**Comment by legodude17** [comment]
What is the deps name? What does the `npm-debug.log` say?

**Comment by cwoodland** [comment]
I was missing a package.  I will close this issue.
Thanks!
