### ISSUE TITLE
node-red-contrib-s7 won't install

### ISSUE THREAD

**Issue by IOT4020** [npm/npm#15522]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I get a fault message after trying to install the node.red-contrib-s7 
### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   'node-red-contrib-s7' ]
2 info using npm@2.14.12
3 info using node@v4.2.4
4 verbose install initial load of /usr/lib/package.json
5 verbose installManyTop reading scoped package data from /usr/lib/node_modules/mraa/package.json
6 verbose installManyTop reading scoped package data from /usr/lib/node_modules/node-red/package.json
7 verbose installManyTop reading scoped package data from /usr/lib/node_modules/node-red-dashboard/package.json
8 verbose installManyTop reading scoped package data from /usr/lib/node_modules/node-red-node-intel-gpio/package.json
9 verbose installManyTop reading scoped package data from /usr/lib/node_modules/npm/package.json
10 verbose installManyTop reading scoped package data from /usr/lib/node_modules/npm-debug.log/package.json
11 info package.json mraa@v1.5.1 No repository field.
12 info package.json mraa@v1.5.1 No README data
13 info package.json npm@2.14.12 Non-dependency in bundleDependencies: ansi-regex
14 info package.json npm@2.14.12 Non-dependency in bundleDependencies: spdx-license-ids
15 info package.json npm@2.14.12 Non-dependency in bundleDependencies: strip-ansi
16 verbose readDependencies loading dependencies from /usr/lib/package.json
17 silly cache add args [ 'node-red-contrib-s7', null ]
18 verbose cache add spec node-red-contrib-s7
19 silly cache add parsed spec Result {
19 silly cache add   raw: 'node-red-contrib-s7',
19 silly cache add   scope: null,
19 silly cache add   name: 'node-red-contrib-s7',
19 silly cache add   rawSpec: '',
19 silly cache add   spec: 'latest',
19 silly cache add   type: 'tag' }
20 silly addNamed node-red-contrib-s7@latest
21 verbose addNamed "latest" is being treated as a dist-tag for node-red-contrib-s7
22 info addNameTag [ 'node-red-contrib-s7', 'latest' ]
23 silly mapToRegistry name node-red-contrib-s7
24 silly mapToRegistry using default registry
25 silly mapToRegistry registry https://registry.npmjs.org/
26 silly mapToRegistry uri https://registry.npmjs.org/node-red-contrib-s7
27 verbose addNameTag registry:https://registry.npmjs.org/node-red-contrib-s7 not in flight; fetching
28 verbose request uri https://registry.npmjs.org/node-red-contrib-s7
29 verbose request no auth needed
30 info attempt registry request try #1 at 15:05:21
31 verbose request id 4e7d201f5ec46f3d
32 http request GET https://registry.npmjs.org/node-red-contrib-s7
33 info retry will retry, error on last attempt: Error: connect EHOSTUNREACH 151.101.12.162:443
34 info attempt registry request try #2 at 15:05:36
35 http request GET https://registry.npmjs.org/node-red-contrib-s7
36 info retry will retry, error on last attempt: Error: connect EHOSTUNREACH 151.101.12.162:443
37 info attempt registry request try #3 at 15:06:39
38 http request GET https://registry.npmjs.org/node-red-contrib-s7
39 verbose stack Error: connect EHOSTUNREACH 151.101.12.162:443
39 verbose stack     at Object.exports._errnoException (util.js:870:11)
39 verbose stack     at exports._exceptionWithHostPort (util.js:893:20)
39 verbose stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
40 verbose cwd /usr/lib/node_modules
41 error Linux 4.4.13-yocto-standard
42 error argv "/usr/bin/node" "/usr/bin/npm" "install" "node-red-contrib-s7"
43 error node v4.2.4
44 error npm  v2.14.12
45 error code EHOSTUNREACH
46 error errno EHOSTUNREACH
47 error syscall connect
48 error connect EHOSTUNREACH 151.101.12.162:443
49 error If you need help, you may report this error at:
49 error     <https://github.com/npm/npm/issues>
50 verbose exit [ 1, true ]

**Comment by doug-wade** [comment]
Hi @IOT4020!  The error is `Error: connect EHOSTUNREACH 151.101.12.162:443`, which means that your local npm client can't reach the npm registry.  Can you ping the registry (`» ping registry.npmjs.org`)?  Are you behind a firewall?  Can you reach the npm homepage in your browser (www.npmjs.com)?

**Comment by IOT4020** [comment]
Hello @doug-wade.
This error eccoured when i tried without a firewall.
I also tested it with a firewall and there i can ping the registry, but i get also an error:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   'node-red-contrib-s7' ]
2 info using npm@2.14.12
3 info using node@v4.2.4
4 verbose install initial load of /usr/lib/package.json
5 verbose installManyTop reading scoped package data from /usr/lib/node_modules/mraa/package.json
6 verbose installManyTop reading scoped package data from /usr/lib/node_modules/node-red/package.json
7 verbose installManyTop reading scoped package data from /usr/lib/node_modules/node-red-dashboard/package.json
8 verbose installManyTop reading scoped package data from /usr/lib/node_modules/node-red-node-intel-gpio/package.json
9 verbose installManyTop reading scoped package data from /usr/lib/node_modules/npm/package.json
10 verbose installManyTop reading scoped package data from /usr/lib/node_modules/npm-debug.log/package.json
11 info package.json mraa@v1.5.1 No repository field.
12 info package.json mraa@v1.5.1 No README data
13 info package.json npm@2.14.12 Non-dependency in bundleDependencies: ansi-regex
14 info package.json npm@2.14.12 Non-dependency in bundleDependencies: spdx-license-ids
15 info package.json npm@2.14.12 Non-dependency in bundleDependencies: strip-ansi
16 verbose readDependencies loading dependencies from /usr/lib/package.json
17 silly cache add args [ 'node-red-contrib-s7', null ]
18 verbose cache add spec node-red-contrib-s7
19 silly cache add parsed spec Result {
19 silly cache add   raw: 'node-red-contrib-s7',
19 silly cache add   scope: null,
19 silly cache add   name: 'node-red-contrib-s7',
19 silly cache add   rawSpec: '',
19 silly cache add   spec: 'latest',
19 silly cache add   type: 'tag' }
20 silly addNamed node-red-contrib-s7@latest
21 verbose addNamed "latest" is being treated as a dist-tag for node-red-contrib-s7
22 info addNameTag [ 'node-red-contrib-s7', 'latest' ]
23 silly mapToRegistry name node-red-contrib-s7
24 silly mapToRegistry using default registry
25 silly mapToRegistry registry https://registry.npmjs.org/
26 silly mapToRegistry uri https://registry.npmjs.org/node-red-contrib-s7
27 verbose addNameTag registry:https://registry.npmjs.org/node-red-contrib-s7 not in flight; fetching
28 verbose request uri https://registry.npmjs.org/node-red-contrib-s7
29 verbose request no auth needed
30 info attempt registry request try #1 at 14:13:18
31 verbose request id 7e906e36248c5bbe
32 http request GET https://registry.npmjs.org/node-red-contrib-s7
33 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
34 info attempt registry request try #2 at 14:13:29
35 http request GET https://registry.npmjs.org/node-red-contrib-s7
36 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
37 info attempt registry request try #3 at 14:14:30
38 http request GET https://registry.npmjs.org/node-red-contrib-s7
39 verbose stack Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
39 verbose stack     at Object.exports._errnoException (util.js:870:11)
39 verbose stack     at errnoException (dns.js:31:15)
39 verbose stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)
40 verbose cwd /usr/lib/node_modules
41 error Linux 4.4.13-yocto-standard
42 error argv "/usr/bin/node" "/usr/bin/npm" "install" "node-red-contrib-s7"
43 error node v4.2.4
44 error npm  v2.14.12
45 error code EAI_AGAIN
46 error errno EAI_AGAIN
47 error syscall getaddrinfo
48 error getaddrinfo EAI_AGAIN registry.npmjs.org:443
49 error If you need help, you may report this error at:
49 error     <https://github.com/npm/npm/issues>
50 verbose exit [ 1, true ]

**Comment by legodude17** [comment]
Do you have a stable internet connection?

**Comment by KenanY** [comment]
Closing as abandoned.

**Comment by schmidpa** [comment]
I have the same problem, is there any solution?

**Comment by IOT4020** [comment]
Yeah, you have to write your DNS nameserver IP in the resolv.conf file. You can find it under /etc.
The problem is only that the file is cleared after reboot, but you only have to do it one for the install.

Write in the file: nameserver <the IP address> (without <>) and it should work.

**Comment by schmidpa** [comment]
Thanks, which IP should I use? I have a router between the IOT2000 and the PC.

**Comment by IOT4020** [comment]
The DNS server address of your router. You can look it up under ipconfig /all in your cmd.

**Comment by schmidpa** [comment]
I still get the same result...
[npm-debug.log.txt](https://github.com/npm/npm/files/771008/npm-debug.log.txt)

**Comment by IOT4020** [comment]
Sorry my bad, but I had a fault in my description.
Forgot to check the message before sending.
It should be: nameserver ip-adress

example: nameserver 156,21,42,1

**Comment by schmidpa** [comment]
The IP of the IOT Device or of the router?

**Comment by IOT4020** [comment]
Normally the DNS address of the router.

**Comment by schmidpa** [comment]
This way doesn´t work, maybe there is another fault...
