### ISSUE TITLE
ERR! Cannot read property 'path' of null

### ISSUE THREAD

**Issue by Shlinksh** [npm/npm#15525]
Hello, i have an error trying to do the commands **npm install / npm install -g**
my error log:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\User\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g' ]
2 info using npm@4.1.1
3 info using node@v6.9.4
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData .
8 silly fetchDirectoryPackageData .
9 silly fetchPackageMetaData Error: Failed to parse json
9 silly fetchPackageMetaData Unexpected token 'p' at 4:4
9 silly fetchPackageMetaData   "private" : true,
9 silly fetchPackageMetaData    ^
9 silly fetchPackageMetaData     at parseError (C:\Users\User\npm\node_modules\npm\node_modules\read-package-json\read-json.js:390:11)
9 silly fetchPackageMetaData     at parseJson (C:\Users\User\npm\node_modules\npm\node_modules\read-package-json\read-json.js:79:23)
9 silly fetchPackageMetaData     at C:\Users\User\npm\node_modules\npm\node_modules\read-package-json\read-json.js:48:5
9 silly fetchPackageMetaData     at C:\Users\User\npm\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
9 silly fetchPackageMetaData     at tryToString (fs.js:455:3)
9 silly fetchPackageMetaData     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
9 silly fetchPackageMetaData  error for . { Error: Failed to parse json
9 silly fetchPackageMetaData Unexpected token 'p' at 4:4
9 silly fetchPackageMetaData   "private" : true,
9 silly fetchPackageMetaData    ^
9 silly fetchPackageMetaData     at parseError (C:\Users\User\npm\node_modules\npm\node_modules\read-package-json\read-json.js:390:11)
9 silly fetchPackageMetaData     at parseJson (C:\Users\User\npm\node_modules\npm\node_modules\read-package-json\read-json.js:79:23)
9 silly fetchPackageMetaData     at C:\Users\User\npm\node_modules\npm\node_modules\read-package-json\read-json.js:48:5
9 silly fetchPackageMetaData     at C:\Users\User\npm\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
9 silly fetchPackageMetaData     at tryToString (fs.js:455:3)
9 silly fetchPackageMetaData     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
9 silly fetchPackageMetaData   code: 'EJSONPARSE',
9 silly fetchPackageMetaData   file: 'C:\\Users\\User\\WebstormProjects\\Servermmo\\package.json' }
10 silly rollbackFailedOptional Starting
11 verbose stack TypeError: Cannot read property 'path' of null
11 verbose stack     at Object.Installer.rollbackFailedOptional (C:\Users\User\npm\node_modules\npm\lib\install.js:511:29)
11 verbose stack     at Array.<anonymous> (C:\Users\User\npm\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
11 verbose stack     at LOOP (C:\Users\User\npm\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
11 verbose stack     at C:\Users\User\npm\node_modules\npm\node_modules\slide\lib\chain.js:18:7
11 verbose stack     at C:\Users\User\npm\node_modules\npm\lib\install.js:337:5
11 verbose stack     at Array.<anonymous> (C:\Users\User\npm\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
11 verbose stack     at LOOP (C:\Users\User\npm\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
11 verbose stack     at chain (C:\Users\User\npm\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
11 verbose stack     at C:\Users\User\npm\node_modules\npm\lib\install.js:294:5
11 verbose stack     at C:\Users\User\npm\node_modules\npm\node_modules\slide\lib\chain.js:16:22
12 verbose cwd C:\Users\User\WebstormProjects\Servermmo
13 error Windows_NT 6.1.7601
14 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\User\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g"
15 error node v6.9.4
16 error npm  v4.1.1
17 error Cannot read property 'path' of null
18 error If you need help, you may report this error at:
18 error     <https://github.com/npm/npm/issues>
19 verbose exit [ 1, true ]

and My Package.json

{
  "name" : "MMORPGSVR",
  "version" : "0.0.1"
  "private" : true,
  "dependencies" : {
    "minimist" : "*",
    "extend" : "*",
    "binary-parser" : "*",
    "mongoose" : "*",
    "underscore" : "*",
  }
}

**Comment by Shlinksh** [comment]
Not sure if it will help but i have been following this tutorial and arrived at this Problem
[https://www.youtube.com/watch?v=EyNVeTzhC1w](url)

**Comment by achrome** [comment]
Your package.json is incorrect.

```
"name" : "MMORPGSVR",
"version" : "0.0.1"
-----------------------^
"private" : true,
```

**Comment by KenanY** [comment]
Closing since this isn't an issue with `npm` itself.
