### ISSUE TITLE
[4.x.x] Global install fails when passing multiple package names

### ISSUE THREAD

**Issue by achrome** [npm/npm#15532]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I am trying to install more than one global packages in one go, for example
```sh
$ npm i -g npm npm-check-updates autoprefixer
```
However, npm is consistently failing with an error

```
npm verb stack TypeError: Cannot read property 'path' of null
npm verb stack     at Installer.rollbackFailedOptional (/home/achrome/.nvm/versions/node/v7.2.1/lib/node_modules/npm/lib/install.js:511:29)
npm verb stack     at Array.<anonymous> (/home/achrome/.nvm/versions/node/v7.2.1/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
npm verb stack     at LOOP (/home/achrome/.nvm/versions/node/v7.2.1/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
npm verb stack     at /home/achrome/.nvm/versions/node/v7.2.1/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
npm verb stack     at /home/achrome/.nvm/versions/node/v7.2.1/lib/node_modules/npm/lib/install.js:337:5
npm verb stack     at Array.<anonymous> (/home/achrome/.nvm/versions/node/v7.2.1/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
npm verb stack     at LOOP (/home/achrome/.nvm/versions/node/v7.2.1/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
npm verb stack     at chain (/home/achrome/.nvm/versions/node/v7.2.1/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
npm verb stack     at /home/achrome/.nvm/versions/node/v7.2.1/lib/node_modules/npm/lib/install.js:294:5
npm verb stack     at /home/achrome/.nvm/versions/node/v7.2.1/lib/node_modules/npm/node_modules/slide/lib/chain.js:16:22
```

The install goes through successfully when i try to install single packages, for example
```sh
$ npm i -g npm-check-updates
```

#### How can the CLI team reproduce the problem?
Something as simple as `npm i -g npm karma autoprefixer eslint` should reproduce the problem, while
`npm i -g eslint` shouldn't.

### supporting information:

 - `npm -v` prints: 4.1.1
 - `node -v` prints: v7.2.1
 - `npm config get registry` prints: https://registry.npmjs.org
 - Windows, OS X/macOS, or Linux?: Linux (Ubuntu 16.04)
 - Network issues:
   - Geographic location where npm was run: India

**Comment by legodude17** [comment]
Do all of them work individually?

**Comment by achrome** [comment]
> Do all of them work individually?
@legodude17 Yes, that is correct. All of them work individually.
