### ISSUE TITLE
I am not able to install packages using npm install

### ISSUE THREAD

**Issue by LijinDurairaj** [npm/npm#15530]
I am not able to install packages using npm install
I get the following error
npm.cmd : npm WARN angular1.0@1.0.0 No description
At line:1 char:4
At line:1 char:4
+ npm <<<<  install
 + CategoryInfo          : NotSpecified: (npm WARN angular1.0@1.0.0 No description:String) [], RemoteException  
 + FullyQualifiedErrorId : NativeCommandError
npm
WARN
 angular1.0@1.0.0 No repository field.

i have goine through aqll the blogs, truied clearing the cache using npm cache clean and also change the package.json file as this
 "name": "angular1.0",
  "version": "1.0.0",
  "private": true,
but i am not able to install the packages..
any help :)

**Comment by LijinDurairaj** [comment]
I am not able to install packages using npm install
I get the following error
npm.cmd : npm WARN angular1.0@1.0.0 No description
At line:1 char:4
At line:1 char:4
+ npm <<<<  install
 + CategoryInfo          : NotSpecified: (npm WARN angular1.0@1.0.0 No description:String) [], RemoteException  
 + FullyQualifiedErrorId : NativeCommandError
npm
WARN
 angular1.0@1.0.0 No repository field.

i have goine through aqll the blogs, truied clearing the cache using npm cache clean and also change the package.json file as this
 "name": "angular1.0",
  "version": "1.0.0",
  "private": true,
but i am not able to install the packages..
any help :)

**Comment by mahammedzkhan** [comment]
Which npm version are you using? Type `npm -v`

**Comment by LijinDurairaj** [comment]
npm 3.10.10
node v6.9.4

**Comment by LijinDurairaj** [comment]
i have tried this
npm --proxy http://"username:password"@companyip:8080 but still no help found

**Comment by LijinDurairaj** [comment]
I am using visual studio - package manager console to run the npm command and my package.json file is this
{
  "name": "angular2-starter-course",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "tsc && concurrently \"npm run tsc:w\" \"npm run lite\"",
    "lite": "lite-server",
    "tsc": "tsc",
    "tsc:w": "tsc -w",
    "typings": "typings",
    "postinstall": "typings install"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "concurrently": "^3.0.0",
    "lite-server": "^2.2.2",
    "typescript": "^2.0.3",
    "typings": "^1.4.0"
  },
  "dependencies": {
    "@angular/common": "~2.1.1",
    "@angular/compiler": "~2.1.1",
    "@angular/core": "~2.1.1",
    
    "@angular/platform-browser": "~2.1.1",
    "@angular/platform-browser-dynamic": "~2.1.1",

    "@angular/forms": "~2.1.1",
    "@angular/http": "~2.1.1",
    "@angular/router": "~3.1.1",
    "@angular/upgrade": "~2.1.1",

    "core-js": "^2.4.1",
    "reflect-metadata": "^0.1.8",
    "rxjs": "5.0.0-beta.12",
    "systemjs": "0.19.39",
    "zone.js": "^0.6.25"
  }
}

**Comment by KenanY** [comment]
@LijinDurairaj I do not see any errors in the output you have posted, only warnings which should never prevent an install from succeeding.

**Comment by LijinDurairaj** [comment]
@KenanY @mahammedzkhan 
this is the list which i get when i run npm config list
```
; cli configs
user-agent = "npm/3.10.10 node/v6.9.4 win32 x64"

; userconfig C:\Users\lijin662330\.npmrc
https-proxy = "http://<username>/<password>@<company>:<port>/"
init.author.email = "user@yahoo.com"
prefix = "C:\\usr\\local"
proxy = "http://<domain>/<username>:<password>@<compnay>:<port>/"
registry = "http://registry.npmjs.org/"
strict-ssl = false
```
and the error which i get is this
```
npm.cmd : npm ERR! Windows_NT 6.1.7601
At line:1 char:4
+ npm <<<<  install
    + CategoryInfo          : NotSpecified: (npm ERR! Windows_NT 6.1.7601:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! syscall connect



npm
 ERR!
 
network
 connect ETIMEDOUT 172.17.134.214:80

npm
 ERR! 
network
 This is most likely not a problem with npm itself

npm
 ERR!
 
network
 and is related to network connectivity.

npm
 
ERR! network
 In most cases you are behind a proxy or have bad network settings.

npm 
ERR!
 
network
 

npm
 
ERR!
 
network
 If you are behind a proxy, please make sure that the

npm
 
ERR!
 
network
 'proxy' config is set properly.  See: 'npm help config'



npm
 ERR!
 Please include the following file with any support request:

npm
 
ERR!     C:\Users\lijin662330\Documents\Visual Studio 2015\Projects\angular2.0\npm-debug.log
```
I have tried the following comment to set the npm config
`npm config set https-proxy=http://"username:password"@companyAddress:8080`
I have used this site to download the package.config
`https://github.com/angular/quickstart`
any help would be appreciated :)

**Comment by legodude17** [comment]
What are the results of:
1. `npm config get registry`
2. `npm config get http-proxy`
3. `npm config get https-proxy`

**Comment by LijinDurairaj** [comment]
@legodude17 
the registry and the https-proxy is ass shown above and i have removed the http-proxy setting becuase we use https in our office
