### ISSUE TITLE
npm link unreleased version of module makes npm install fail

### ISSUE THREAD

**Issue by stevengill** [npm/npm#15537]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

So this is an issue I've had on and off again with npm@^3 & npm@^4 when it comes to releasing/publishing to npm.

`npm install` tries to resolve & fetch the module from npm even if the module has been `npm linked`. If the version isn't on npm, it fails. But I know the version isn't on npm since i'm developing it and haven't published yet.

I go to Module A, update it to version 2.0.0 from version 1.0.0 and run `npm link .`. Then I go to B and run `npm link A` and `npm install`. `npm install` fails because `No compatible version found: A@^2.0.0`. 2.0.0 isn't on npm as I'm still developing on it locally. 

I expect `npm install` to see that a module is linked locally, and not try to fetch a valid target from npm. 

I swear this was working a few months ago.  I think it might be something with the registry optimizing dependencies before sending them down to my project. If the registry is aware that I have a module linked, it should skip that module or something. 

#### How can the CLI team reproduce the problem?

[1] https://github.com/apache/cordova-lib has multiple modules in it.

`cordova-fetch` uses `cordova-common`. Right now, `cordova-fetch` wants `cordova-common@2.0.0`. We are in the process of releasing `2.0.0` of `cordova-common` right now. Clone the above repo, 
```
cd cordova-common
npm install
npm link .
cd ../cordova-fetch
npm link cordova-common
npm install
```

`npm install` is failing with the following.

```
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/var/nvm/versions/node/v6.6.0/bin/node" "/usr/local/var/nvm/versions/node/v6.6.0/bin/npm" "install"
npm ERR! node v6.6.0
npm ERR! npm  v4.1.1
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: cordova-common@^2.0.0
npm ERR! notarget Valid install targets:
npm ERR! notarget 0.1.0, 1.0.0, 1.1.0, 1.1.1, 1.2.0, 1.3.0, 1.4.0, 1.4.1, 1.5.0, 1.5.1
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'cordova-fetch'
npm ERR! notarget
```
### supporting information:

 - `npm -v` prints: 4.0.2 & 4.1.1 (tried both)
 - `node -v` prints: 6.6.0
 - `npm config get registry` prints: http://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: OSx
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

Thank you so much! Love npm and the work you do <3

**Comment by legodude17** [comment]
Is `cordova-common@2.0.0` specified in `package.json`?

**Comment by filmaj** [comment]
@legodude17 yep: https://github.com/apache/cordova-lib/blob/master/cordova-fetch/package.json#L24

**Comment by stevengill** [comment]
So I ended up releasing cordova-common@2 so my reproduce case won't work anymore. I can whip up some sample modules that show the same bug if you need.

**Comment by bluetidepro** [comment]
@stevengill Did you get any further with this issue, running into something similar, and I'm not sure what's up.

**Comment by stevengill** [comment]
It is definitely still broken. I essentially have to play npm link gymnastics to get it to work.

npm link my sub modules into my main module, npm install in my main module, go back to my sub modules and run npm install in all of them incase my main module stole my sub modules deps. It is incredibly annoying.

**Comment by gordonwoodhull** [comment]
FWIW, npm install still removes any links, so you can't run `npm link` and then `npm install` if the version of the referred dependency hasn't been published.

My workaround was to temporarily back the version out to one that exists on npm, then run `npm install` and `npm link`. Not too painful, but I agree `npm install` should skip any linked dependencies as I think it did in the past.

Not going to file another issue about this right now, just leaving a simple workaround for anyone else who runs into this.
