### ISSUE TITLE
First http get return all data and after that the second http get return data

### ISSUE THREAD

**Issue by dagarint** [npm/npm#15538]
Hi!

I'm using Angular. My second http get is nested in the first one. The problem is that the first http get return all data and after that the second http get return data. It should be that the first http get expand the data in the other (second http get).

Now - wrong :
 first one
 first one
 first one
   second one
   second one
   second one
   second one

It should be:
 first one
   second one
   second one
 first one
 first one
   second one
   second one
 
Here is my problem.

---------------
(todo.service.ts)

import { Injectable } from '@angular/core';
import { Http, Response, Headers, RequestOptions } from '@angular/http';
import { Observable } from 'rxjs/Rx';
import { Holidays } from './holidays';
import { Details } from './details';

@Injectable()
export class TodoService {
   
  constructor(private http: Http) { }

  GetAllToDo(): Observable<Details[]> {
    let ToDo2$ = this.http
      .get(`$http://localhost:52164/api/ToDo`, { headers: this.getHeaders() })
      .map(mapDetails) ;
    return ToDo2$;
  }

  GetAllHolidays(): Observable<Holidays[]> {
    let Holidays$ = this.http
      .get(`$http://localhost:52164/Holidays`, { headers: this.getHeaders() })
      .map(mapHolidays);
    return Holidays$;
  }

  private getHeaders() {
    let headers = new Headers();
      headers.append('Accept', 'application/json');
    return headers;
  }
}

function mapDetails(response: Response): Details[] {
  return response.json().map(toDetails)
}

function mapHolidays(response: Response): Holidays[] {
  return response.json().map(toHolidays)
}

function toDetails(r: any): Details {
  let Detailsst = <Details>({
    ID: r.ID,
    StartDate: r.StartDate,
    EndDate: r.EndDate
  });
  return Detailsst;
}

function toHolidays(r: any): Holidays {
    let Holidays = <Holidays>({
        Holiday: r.Holiday
    });
    return Holidays;
}
-------------------

(my.component.ts)

  loadToDo() {  
    return this.TodoService
      .GetAllToDo()
      .map(
      (ToDo) => {
        this.ToDo = ToDo;
        this.ToDo.forEach((ToDo, index) => {
          var intDays = 0; 
          var intDays = this.CheckDate(ToDo.StartDate, ToDo.EndDate);
        }
      });
  }

  CheckDate(StartDate: string, EndDate: string): number {
    var datStartDate = new Date(StartDate.substring(0, 10));
    var datEndDate = new Date(EndDate.substring(0, 10));
    var datDate = new Date();
    var intDifference: number;
    var i: number;
    intDifference = datEndDate.getDate() - datStartDate.getDate();   
    for (i = 0; i <= intDifference; i++) {
      datDate.setDate(datStartDate.getDate() + i);
      this.Holiday(datDate).subscribe(_ => { });
      if (this.bool3 == false) {
        this.test = this.test + "first one"               
      };  
    };   
    return intDifference ;
  };

  Holiday(StartDate22: Date)  { 
    var StartDate23 = new Date(StartDate22);
    this.bool3 = false; 
    return this.TodoService
      .GetAllHolidays()         
      .map(
      (Holidays) => {       
        this.Holidays = Holidays;
        this.Holidays.forEach((Holidays, index) => {
        var datDate2 = new Date(Holidays.Holiday.substring(0, 10));
          if (StartDate23.toDateString() == datDate2.toDateString()) {
            this.bool3 = true;
            this.test = this.test + "second one" 
          } 
        }    
      );       
      return this.Holidays;  
    }) 
  };

Thank you.
Tomaž

**Comment by KenanY** [comment]
@dagarint I'm gonna close this since this issue tracker is for bugs/feature-requests for `npm`.
