### ISSUE TITLE
npm unpublish 403 Err

### ISSUE THREAD

**Issue by MeTe-30** [npm/npm#15531]
I accidentally published wrong package and with higher version (1.1.10). (less than 24 hours)  
The correct package version package is 1.0.3
So I tried to delete that version with this command:

    npm unpublish adm-trv@1.1.10  

But I got this error:

    npm ERR! unpublish Failed to update data
    npm ERR! Darwin 15.6.0
    npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "unpublish" "adm-trv@1.1.10"
    npm ERR! node v6.2.1
    npm ERR! npm  v3.9.3
    npm ERR! code E500
    
    npm ERR! "adm-trv status = 403" : adm-trv

I tried to login again with `npm login` but nothing changed.  

**My system:**  
OS X El Capitan  
node V6.2.1  
npm V3.9.3

**Comment by askmon** [comment]
I'm seeing this too

**Comment by grimurd** [comment]
Same problem here
node v6.9.1
npm v4.1.1

**Comment by vamship** [comment]
Same here

node v4.3.2
npm v4.1.1

**Comment by johnelliott** [comment]
+1
node v7.4.0
npm v4.0.5

**Comment by alexanderby** [comment]
Maybe it will be useful to anybody:
I've published a package making a typo in specifying tag. Unpublish was not successful, same as for you.

So I tried to play with tags:
1. Add `beta` tag to new version (`npm dist-tag add package@new beta`).
2. Add `latest` tag to previous version (`npm dist-tag add package@old latest`), 

I'm not sure if that was enough, I've also tried removing `latest` tag from new version (`npm dist-tag rm package@new latest`) but received an error `Registry returned 403 for GET ...`.

Now I have a latest version as initially expected and another version goes with `beta` tag.

**Comment by tonymet** [comment]
I published `tigerconnect@'0.1.1-8.1'` by accident due to a bug in my sem-version.  I'm trying to unpublish and i receive a 403.   We've also removed the `latest` tag to prevent any conflicts.

```
npm unpublish tigerconnect@'0.1.1-8.1'

npm ERR! unpublish Failed to update data
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/7.4.0/bin/node" "/usr/local/bin/npm" "unpublish" "tigerconnect@0.1.1-8.1"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code E500

npm ERR! "tigerconnect status = 403" : tigerconnect
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/anthonymetzidis/tigertext/cucumber_js_automation/npm-debug.log
```

**Comment by GantMan** [comment]
I'm having the same problem as @tonymet


403 on unpublish.

**Comment by Kureev** [comment]
```
→  npm unpublish react-native-blur@1.3.0                                                                                [47ae025]
npm ERR! unpublish Failed to update data
npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/Cellar/node/7.3.0/bin/node" "/usr/local/bin/npm" "unpublish" "react-native-blur@1.3.0"
npm ERR! node v7.3.0
npm ERR! npm  v4.1.2
npm ERR! code E500

npm ERR! "react-native-blur status = 403" : react-native-blur
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/xamd/Projects/react-native-blur/examples/Basic/npm-debug.log
```

Same here

**Comment by renie** [comment]
+1 

403 on unpublish

node 4.5.0
npm 2.15.9

**Comment by Hamper** [comment]
+1

node 7.5.0
npm 4.1.2

**Comment by cedk** [comment]
+1 this is very annoying as we have only 24h to unpublish.

**Comment by gmsa** [comment]
+1

node 6.9.2
npm 4.2.0

**Comment by kfatehi** [comment]
I am also trying to unpublish and running into this issue. I accidentally left personal info in a test file and need to remove.

**Comment by d5039m** [comment]
Same issue here on node 7.4.0, npm 4.2.0.

**Comment by karthickthangasamy** [comment]
+1

Facing the same issue 

node 6.9.2
npm 4.2.0

**Comment by mschoendorf** [comment]
+1 
node 6.9.1
npm 3.10.8

**Comment by Kureev** [comment]
Worth mentioning that if you published your version more, than 24hrs ago, you need to contact support@npmjs.com to request unpublishing (see [related thread on twitter](https://twitter.com/kureevalexey/status/832487311430389761)).

**Comment by 256dpi** [comment]
It would be really great to have clear error message that explains the rules rather than this cryptic error that looks like some internal API is broken.

**Comment by mattsalt** [comment]
That would be nice, however the error message is displayed even when trying to unpublish immediately. This is then compounded by the 24 hour limit as it's taking longer than that to fix the issue.

**Comment by frozeman** [comment]
Im seeing this problem too with npm version 5.3.0
```
➜  web3 git:(1.0) ✗ npm unpublish web3@1.0.0-beta1
npm ERR! unpublish Failed to update data
npm ERR! code E500
npm ERR! "web3 status = 403" : 60-63294731eb24df9b40b49346e0de4e9d

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/frozeman/.npm/_logs/2017-07-20T10_57_44_620Z-debug.log
```

**Comment by aleclarson** [comment]
I'm also getting the 403 error. I was just recently added as owner to `rethinkdb-mock` and cannot unpublish the latest version.

[Here's the verbose output of `npm unpublish rethinkdb-mock@0.5.0`](https://pastebin.com/raw/wrcBwctp)

**Comment by jure** [comment]
Same issue, npm 5.3.0, package published minutes ago. 

`41 verbose stack Error: You can no longer unpublish this version.`
