### ISSUE TITLE
protactor install error on fedora 22

### ISSUE THREAD

**Issue by gnczoli** [npm/npm#15533]
#### I'm opening this issue because:

  - [ ] npm is producing an incorrect install.

#### What's going wrong?

System Linux 4.4.14-200.fc22.x86_64
npm ERR! command "node" "/bin/npm" "install" "-g" "protractor"
npm ERR! cwd /home/gzoli/work/RoadRecord/rr-git/roadrecord_project/roadrecord/static/tests
npm ERR! node -v v0.10.42
npm ERR! npm -v 1.3.6
npm ERR! type non_object_property_load
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/usr/lib/node_modules/npm/lib/cache.js:687:35)
npm ERR!     at /usr/lib/node_modules/npm/lib/cache.js:675:5
npm ERR!     at saved (/usr/lib/node_modules/npm-registry-client/lib/get.js:148:7)
npm ERR!     at /usr/lib/node_modules/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:108:15)

#### How can the CLI team reproduce the problem?
sudo npm install -g protractor
### supporting information:

 - `npm -v` prints:
1.3.6
 - `node -v` prints:
v0.10.42
 - `npm config get registry` prints:
https://registry.npmjs.org/

 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - [ ] I access the npm registry via a VPN
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@gnczoli `npm@1.3` is years old and has not been supported for a long time.
