### ISSUE TITLE
Hi, I am getting this ENONET error 34 - Not able to understand the reason

### ISSUE THREAD

**Issue by Himanshuj1088** [npm/npm#15534]
![image](https://cloud.githubusercontent.com/assets/2649965/22110260/163d7b84-de81-11e6-9890-2eee3590456d.png)

**Comment by watilde** [comment]
Hello! You're using very old version of Node.js and npm that are not supported anymore. Could you please check the following docs and try to update them?

+ [Try the latest stable version of node](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-node)
+ [Try the latest stable version of npm](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm)
