### ISSUE TITLE
[bug?] Unable to install package from GitHub.

### ISSUE THREAD

**Issue by trusktr** [npm/npm#15547]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I'm trying to install from GitHub:

```sh
npm install imvu/imvujs#npm
```

with npm v3.10.9.

#### How can the CLI team reproduce the problem?

Make a project with a valid package.json. Then in that project do

```sh
npm install imvu/imvujs#npm
```

### supporting information:

 - `npm -v` prints: 3.10.9
 - `node -v` prints: 7.2.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS
 - Network issues: none
 - Container: none

**Comment by KenanY** [comment]
@trusktr Could you please provide a `npm-debug.log` file?

**Comment by apihlaja** [comment]
`npm install --verbose "imvu/imvujs#npm"`

Without verbose mode, I killed it because it took so long. But when I let it run, it will complete eventually.
It just takes extremely long but verbose mode shows it keeps working.

**Comment by KenanY** [comment]
I think most of the time is spent installing all of those git submodules. I would guess that https://github.com/imvu/DefinitelyTyped would take the longest of them all.

**Comment by malucky** [comment]
I was using the syntax "github:{organization}/{repo} and ran into the same issue. Changing the syntax to "git+ssh://git@github.com/{organization}/{repo}.git" worked for me.
Something seems to have broken in the latest release

**Comment by trusktr** [comment]
Ah! Maybe NPM should still show the progress animation while installing git modules like it does with npm modules.
