### ISSUE TITLE
npm not being able to find a file. (Win 10) install Ionic

### ISSUE THREAD

**Issue by AmaelN** [npm/npm#15544]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I cannot install Ionic using npm on win 10. I'm getting the following error : npm not being able to find a file.

C:\WINDOWS\system32>npm install -g ionic
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated node-uuid@1.3.3: use uuid module instead
C:\Users\User\AppData\Roaming\npm
`-- (empty)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\ionic\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})
npm WARN In ionic@2.2.1 replacing bundled version of cross-spawn with cross-spawn@4.0.2
npm WARN In ionic@2.2.1 replacing bundled version of mime-types with mime-types@2.0.14
npm WARN In ionic@2.2.1 replacing bundled version of semver with semver@4.2.0
npm WARN In ionic@2.2.1 replacing bundled version of form-data with form-data@0.2.0
npm WARN In ionic@2.2.1 replacing bundled version of request with request@2.51.0
npm WARN In ionic@2.2.1 replacing bundled version of ionic-app-lib with ionic-app-lib@2.2.0
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ionic"
npm ERR! node v6.9.2
npm ERR! npm  v4.1.2
npm ERR! path C:\Users\User\AppData\Roaming\npm\node_modules\.staging\ansi-5d2b287e
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\User\AppData\Roaming\npm\node_modules\.staging\ansi-5d2b287e' -> 'C:\Users\User\AppData\Roaming\npm\node_modules\ionic\node_modules\cordova-lib\node_modules\ansi'
npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\User\AppData\Roaming\npm\node_modules\.staging\ansi-5d2b287e' -> 'C:\Users\User\AppData\Roaming\npm\node_modules\ionic\node_modules\cordova-lib\node_modules\ansi'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

#### How can the CLI team reproduce the problem?

Install Ionic on windows 10 machine

### supporting information:

 - `npm -v` prints: 4.1.2
 - `node -v` prints: v6.9.2
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows 10 

log files attached
[npm-debug.txt](https://github.com/npm/npm/files/721417/npm-debug.txt)

 :

**Comment by grigorz** [comment]
Hi, I have same issue with windows 7. Did you get solution for this?

**Comment by AmaelN** [comment]
It's working on a English version of Windows. The issue is that I have a
French version of Windows on my main computer.
Hope that they will solve it soon

**Comment by AmaelN** [comment]
I've found the solution.

You have to uninstall cordova and install it again

npm uninstall -g cordova

Then install it again

PS : I've update node.js and npm to the latest version before installing it
again : https://docs.npmjs.com/getting-started/installing-node
