### ISSUE TITLE
Cannot npm start for angular-tour-of heroes

### ISSUE THREAD

**Issue by Cienlim612** [npm/npm#15541]
I suddenly facing this problem and before that I done a few of the tutorial is ok

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\cienl\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.9.4
npm ERR! npm  v4.1.1
npm ERR! code ELIFECYCLE
npm ERR! angular-quickstart@1.0.0 start: `tsc && concurrently "tsc -w" "lite-server" `
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the angular-quickstart@1.0.0 start script 'tsc && concurrently "tsc -w" "lite-server" '.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc && concurrently "tsc -w" "lite-server"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-quickstart
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\cienl\Desktop\angular-tour-of-heroes\npm-debug.log
[npm-debug.txt](https://github.com/npm/npm/files/720896/npm-debug.txt)

**Comment by KenanY** [comment]
@Cienlim612 Looks like your `"start"` script is throwing an error. Make sure that you can run

```
tsc && concurrently "tsc -w" "lite-server"
```

without error from your command line. Since this isn't the fault of `npm`, I'm gonna close this.

**Comment by Cienlim612** [comment]
This is what I get from the error, so what should I do
app/app.component.ts(32,3): error TS1005: ',' expected.

**Comment by KenanY** [comment]
@Cienlim612 Looks like a syntax error in your code.

**Comment by Cienlim612** [comment]
Yup, i found the error already. I copy the full code from the tutorial but dun noe somehow miss the comma. But anyway tq for respond ^^ And I have a lot to learn and fun with angular2
