### ISSUE TITLE
npm cannot install any package, log attached.

### ISSUE THREAD

**Issue by sah-arjun** [npm/npm#15543]
#### I'm opening this issue because:

  - [ ] npm cannot install any package to my mac os. I tried to install React and other programs, but unable to install. npm-debug.log is attached for further information.
[npm_debug_log.pdf](https://github.com/npm/npm/files/721346/npm_debug_log.pdf)

### supporting information:

 - `npm -v` prints: 4.0.5
 - `node -v` prints:7.4.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: OS X EI Captian
 - Network issues:
   - Geographic location where npm was run: Nepal
   - [ ] I don't use a proxy, and have  reliable internet access.

**Comment by jgeringer** [comment]
Any solution found with this? i've recently updated my node from 5.10 to 7.4 and am getting the same problem. I'll investigate and will post if I find a fix.

**Comment by sah-arjun** [comment]
Hi jgeringer, I still don't have the solution. I tried by uninstalling and re-installing the node and npm, but didn't get any improvement. 
I went through most of the existing solutions posted on different forums.
Also I tried to install by using different network, and found that is not due to network issue.

If someone have fix for this, please help us. I have attached the log file for reference.

**Comment by jgeringer** [comment]
Hi sah-arjun,

I just solved this issue by downloading the 6.9.4 version from here:
https://nodejs.org/en/

I didnt remove the other version i had. Right after i did this I was able to use npm again to install packages. Let me know how this works out for you.

Best of luck,
Joe

**Comment by sah-arjun** [comment]
Hi jgeringer,

I have just fixed this issue, proxy had been set on my system.
I got rid off the proxy setting using command: 

npm config rm proxy
npm config rm https-proxy

Hoping that this would help others too.
