### ISSUE TITLE
NPM hangs on 'npm publish' ; Insufficient logs 

### ISSUE THREAD

**Issue by stoptherock1** [npm/npm#15549]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I run 'npm publish' within Jenkins build. The jobs contains only few steps: 

npm install
 npm install 
npm-snapshot 
npm publish --tag $(npm-snapshot ${BUILD_NUMBER}) --loglevel silly

When I perform all the above steps locally everything work. But when I try to perform it on Jenkins, the job fails on publishing. I get the following output:

`Jenkins logs:

2:26:23 + npm publish --tag SNAPSHOT --loglevel silly
12:26:23 npm info it worked if it ends with ok
12:26:23 npm verb cli [ '/path-to-node',
12:26:23 npm verb cli   '/path-to-npm',
12:26:23 npm verb cli   'publish',
12:26:23 npm verb cli   '--tag',
12:26:23 npm verb cli   'SNAPSHOT',
12:26:23 npm verb cli   '--loglevel',
12:26:23 npm verb cli   'silly' ]
12:26:23 npm info using npm@3.10.8
12:26:23 npm info using node@v6.9.1
12:26:23 npm verb publish [ '.' ]
12:26:23 npm sill cache add args [ '.', null ]
12:26:23 npm verb cache add spec .
12:26:23 npm sill cache add parsed spec Result {
12:26:23 npm sill cache add   raw: '.',
12:26:23 npm sill cache add   scope: null,
12:26:23 npm sill cache add   escapedName: null,
12:26:23 npm sill cache add   name: null,
12:26:23 npm sill cache add   rawSpec: '.',
12:26:23 npm sill cache add   spec: '/path-to-deploy-folder',
12:26:23 npm sill cache add   type: 'directory' }
12:26:23 npm verb addLocalDirectory /path-to-deploy-folder/.tmp/home/.npm/project/package.tgz not in flight; packing
12:26:23 npm verb correctMkdir /path-to-deploy-folder/.tmp/home/.npm correctMkdir not in flight; initializing
12:26:23 npm info lifecycle project~prepublish: project
12:26:23 npm sill lifecycle project~prepublish: no script for prepublish, continuing
12:26:23 npm verb tar pack [ '/path-to-deploy-folder/.tmp/home/.npm/project/package.tgz',
12:26:23 npm verb tar pack   '/path-to-deploy-folder' ]
12:26:23 npm verb tarball /path-to-deploy-folder/.tmp/home/.npm/project/package.tgz
12:26:23 npm verb folder /path-to-deploy-folder
12:38:52 Build timed out (after 15 minutes). Marking the build as aborted.
12:38:52 Build was aborted`

Basically, the job hangs on `npm verb folder /path-to-deploy-folder` and despite the fact, that I already enabled `--loglevel silly` I still cannot see, what is wrong and npm cannot perform publishing.

Is it possible to increate the loglevel in this case and debug the publishing process. Otherwise the available logs do not say much.

#### How can the CLI team reproduce the problem?

--

### supporting information:

 - `npm -v` prints:
3.10.8
 - `node -v` prints:
v6.9.1
 - `npm config get registry` prints:
https://local-npm-registry

 - Windows, OS X/macOS, or Linux?:
Linux
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by stoptherock1** [comment]
After a few days of debugging I found out, what was the problem.
The Jenkins job has the following configuration:

- Jenkins creates folders `.tmp` and `.tmp/home` inside of the the Jenkins' executors workspace;
- `$HOME` environmental variable is set to this path, so original `home` folder of the user, used for Jenkins jobs execution, will not be affected;
- The code of NPM project is fetched directly to the workspace (in the same path, where folder `.tmp` is located);

Therefore, when the `npm install` is performed, npm stores some temporary files in the `.tmp` folder and `npm publish` then tries to pack it and publish to the npm registry. The issue was observed only in some projects and seems like is directly connected to the list of the dependencies, listed in the project's `package.json` file. I did not perform additional experiments to find out, which dependency causes the problem. Instead, I just removed the `.tmp` folder right before the `npm publish` is executed and the problem was fixed.

I also tried to reproduce the problem on my local machine. After some time of hanging npm threw an error `npm ERR! "toString()" failed`, which might be helpful for debugging purposes (see 
[full log](https://github.com/npm/npm/files/731897/local_publishing_execution_github.txt)).

However, to me it looks like a problem in npm. Obviously, performing `npm publish` within a folder with `.tpm/home` inside is a wrong strategy and all temporary files are needed to be removed. But it was extremely hard to understand the problem by looking at npm logs. The only way to find out, what blocked `npm publish`, was to compare the state of the folders with the published code before and after execution of `npm install`.

**Comment by j5concur** [comment]
I am also experiencing this issue.  I am using node 7.5.0 with npm 4.1.2.

I am trying to publish from a subfolder of my jenkins workspace, and do not see the `.tmp` folder in the root of the workspace that @stoptherock1 mentions as his fix.

```
rm dist/* lib/* coverage/* .git .npm .nyc_output flotsam
node build/setup.js;
npm install
babel src --out-dir lib --source-maps;
node-sass src/sass/ -o src/styles/; build/readme.sh
cross-env NODE_ENV=test nyc mocha test/* --recursive --require test/setup.js || true
NODE_ENV=production webpack --config src/webpack.config.js -p --optimize-dedupe
```

```
node build/publish.js; // creates new package.json in dist/package
cd dist/package;
npm pack
cd dist/package &&
    curl --user user:pass https://artifactory.url/.../auth/artifactory >> .npmrc &&
        npm publish -ddd --scope @artifactory
```

**Comment by j5concur** [comment]
I've gotten my pipeline to work.  Where previously I had `HOME` set to `./` in my Jenkinsfile, I now have `HOME=/tmp` (via `withEnv(['HOME=/tmp']).

It seems like there is some kind of condition in which npm is behaving strangely in this particular place (where the logs spit out `verb folder` before things hang) based on the value of HOME.

I'm using a private npm registry and scoping it, with the registry credentials and scope association in a `.npmrc` file in the dist/package folder, for what it's worth.

**Comment by j5concur** [comment]
I cannot reproduce with a new project at this time, however I can reproduce locally on my development machine.

Looking at what happens, when I run `HOME=./ npm publish --scope @artifactory` from within the distribution folder, the `.npm` folder is created underneath.

The group owner of the `.npm` folder is not the same as the parent directory or other items in the distribution folder.  Where everything else is group `wheel` the `.npm` folder is owned by group `ORGANIZATION\Domain Users` (active directory group on my network).

```
drwxr-xr-x  16 j5bot  wheel                     544 Mar  9 11:19 .
drwxr-xr-x   5 j5bot  wheel                     170 Mar  8 18:42 ..
-rw-r--r--@  1 j5bot  wheel                    6148 Mar  7 19:06 .DS_Store
drwxr-xr-x   3 j5bot  ORG\Domain Users       102 Mar  9 11:19 .npm
-rw-r--r--   1 j5bot  wheel                     442 Mar  8 19:09 .npmrc
-rw-r--r--   1 j5bot  wheel                    1276 Mar  8 11:41 common.5b1b7034f3caf8f73b05.js
```

Inside of `.npm` I find a folder with the name of my project, then a folder with the version I was trying to publish, then a package folder and a tarball with a timestamp of some sort as part of the extension

```
.npm:
total 0
drwxr-xr-x   3 j5bot  ORG\Domain Users     102 Mar  9 11:19 .
drwxr-xr-x  16 j5bot  wheel                544 Mar  9 11:19 ..
drwxr-xr-x   3 j5bot  ORG\Domain Users     102 Mar  9 11:19 project

.npm/project:
total 0
drwxr-xr-x  3 j5bot  ORG\Domain Users     102 Mar  9 11:19 .
drwxr-xr-x  3 j5bot  ORG\Domain Users     102 Mar  9 11:19 ..
drwxr-xr-x  5 j5bot  ORG\Domain Users     170 Mar  9 11:23 2.1.12

.npm/project/1.0.0:
total 7884248
drwxr-xr-x  5 j5bot  ORG\Domain Users         170 Mar  9 11:23 .
drwxr-xr-x  3 j5bot  ORG\Domain Users         102 Mar  9 11:19 ..
drwxr-xr-x  2 j5bot  ORG\Domain Users          68 Mar  9 11:19 package
-rw-r--r--  1 j5bot  ORG\Domain Users  4023369728 Mar  9 11:23 package.tgz.1164222234
-rw-r--r--  1 j5bot  ORG\Domain Users    13363440 Mar  9 11:23 package.tgz.271950107
```

When I do not put `HOME=./` as part of my command, the publish succeeds, and the logs show this type of line after the `verb folder` line upon which the problem builds hang:

```
npm verb addLocalTarball adding from inside cache /Users/j5bot/.npm/project/1.0.0/package.tgz
```

npm does not seem to exclude `.npm` from packaging by default, which results in an infinite loop as it tries to package the package of the package, etc.  When `ctrl+c` is pressed to send a kill signal to npm, it does not clean up `.npm`.  The two behaviors together actually result in the size of the `.npm` folder growing every time you attempt to publish and fail.

This problem is mitigated by adding a `.npmignore` file which contains `.npm`, but I don't believe this should be the responsibility of the user (to exclude npm's caches).
