### ISSUE TITLE
`npm install -g npm` cause `Cannot find module 'semver'` on any npm command

### ISSUE THREAD

**Issue by ShockwaveNN** [npm/npm#15558]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### How can the CLI team reproduce the problem?
Create and build this dockerfile
```
FROM ubuntu:latest
RUN apt-get update && apt-get install -yq curl sudo
RUN curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
RUN apt-get update && apt-get install -y nodejs
RUN npm install npm@latest -g
CMD npm -v
```

Cause error:
```
module.js:471
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/npm/lib/utils/unsupported.js:2:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```
Any npm command cause this error
### supporting information:

 - `npm -v` prints: before update - `3.10.10`, after update it crashes
 - `node -v` prints: 6.9.4
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: ubuntu:16.04
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by chryw** [comment]
I'm getting the same issue on Windows today. Reinstalling Node v6.94 didn't solve the problem.

**Comment by chryw** [comment]
Jus resolved by:

1. Uninstall node
2. Delete npm and npm-cache folder
3. Reboot
4. Do a clean install nodejs 6.9.4

**Comment by nicoflemming** [comment]
This answer does not match the topic. We are talking about a docker containe.r Each time you build the image it is a fresh installation, and within the fresh installation the error occurs.

**Comment by Salfai77210** [comment]
Got the issue here 

This is my Dockerfile
```dockerfile
FROM wodby/drupal-php:7.0-1.0.0
RUN apk update
RUN apk add --update python
RUN apk add --update nodejs
RUN npm install npm@latest -g

RUN npm install gulp-cli -g
```
> `apk add --update` on Alpine is the same as `apt-get install` on Ubuntu

And the same error occurs at the last line 
```dockerfile
RUN npm install gulp-cli -g
```
`Error: Cannot find module 'semver'`

**Comment by lmazuel** [comment]
Got the same issue, this post allowed me to fix it using the NodeJS repo:
```dockerfile
RUN curl -sL https://deb.nodesource.com/setup_6.x | bash - && \
	apt-get update && apt-get install -y nodejs && \
	npm install npm@latest -g
```

**Comment by aalimovs** [comment]
Just had the same issue with a simple Dockerfile:

```
FROM node:6.9
RUN npm install npm@latest -g
```

Looking at logs, it seems it installs npm `4.4.1`

**Comment by Salfai77210** [comment]
@aalimovs if you are using the node official docker image and make update on top
I suggest you to use the `latest` version of the image:
```dockerfile
FROM node:latest
```

More info on [Node docker HUB](https://hub.docker.com/_/node/)

I know its not gona fix the issue but it is a good workarround.

**Comment by aalimovs** [comment]
@Salfai77210 thanks, I actually need to use `boron` images (sticking to LTS)

I've removed `RUN npm install npm@latest -g` from Dockerfile, so it's just `node:6.9` with its default npm `3.10.10` and everything is fine now.

**Comment by Salfai77210** [comment]
@aalimovs you can use 
```dockerfile
FROM node:boron
```

To get the last version of boron

**Comment by zxaos** [comment]
You can work around this issue for now: https://github.com/npm/npm/issues/15611#issuecomment-289133810

**Comment by Salfai77210** [comment]
THanks @zxaos 
your last [comment](https://github.com/npm/npm/issues/15611#issuecomment-289133810) actually fixed my issue
But i'm still waiting for an other real issue, to make my dockerfile more clean 🤓

**Comment by NikoPrt** [comment]
HI guys,
I have the same issue on my Arch Linux..
I tried this but didn't work:

 `sudo pacman -Rn npm`
 `sudo rm -R /usr/lib/node_modules`
 `sudo rm -R /.npm`

then I tried to reinstall everything with
 `sudo pacman -S npm`

but it still doesn't work

**Comment by rardoz** [comment]
This magic worked in docker node:boron. The trick was to install npm in a seperate directory, then delete the old npm in the global directory and move the new npm into the old directory. Nasty little hack, but beats a lot of other ones I saw.

RUN npm install npm@latest
RUN rm -rf /usr/local/lib/node_modules/npm
RUN mv node_modules/npm /usr/local/lib/node_modules/npm

**Comment by DanielHreben** [comment]
This issue still actual, and breaks workaround for https://github.com/npm/npm/issues/17781

**Comment by naholyr** [comment]
> we're unlikely to ever read it.

yeah 'cause the package manager which breaks itself on upgrade, who cares :smile: :sunglasses:

**Comment by LokeshNagarajan** [comment]
Delete npm folder from below folder
C:\Users\username\AppData\Roaming\npm
after   =>   npm install
Its Working Fine for me!....
