### ISSUE TITLE
npm 4.1 yields cryptic error message: Cannot read property 'path' of null

### ISSUE THREAD

**Issue by darkn3rd** [npm/npm#15561]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### SUMMARY

When installing a package that is not in the repository, **npm 4.x** returns back:
```
npm ERR! Cannot read property 'path' of null
```

In **Npm 3.x**, there was a more discernible message:
```
npm ERR! 404  '%s' is not in the npm registry.
```

#### STEPS TO REPRODUCE

1. Attempt to install a package that does not exist in the repository

```
sudo npm -g install package_that_doesnt_exist
```
#### ACTUAL RESULTS:

From this error, the user cannot discern the nature of the problem.

```
npm ERR! Darwin 16.3.0
npm ERR! argv "/Users/jmenchaca/.nvm/versions/node/v7.2.1/bin/node" "/Users/jmenchaca/.nvm/versions/node/v7.2.1/bin/npm" "-g" "install" "package_that_doesnt_exist"
npm ERR! node v7.2.1
npm ERR! npm  v4.1.1

npm ERR! Cannot read property 'path' of null
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log
```

#### EXPECTED RESULTS

I expected the error to reported similarly to how npm 3.x reports the error, indicating the package does not exist.

```
> sudo npm -g install package_that_doesnt_exist
npm ERR! Darwin 16.3.0
npm ERR! argv "/Users/jmenchaca/.nvm/versions/node/v7.2.1/bin/node" "/Users/jmenchaca/.nvm/versions/node/v7.2.1/bin/npm" "-g" "install" "package_that_doesnt_exist"
npm ERR! node v7.2.1
npm ERR! npm  v3.10.10
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/package_that_doesnt_exist
npm ERR! 404 
npm ERR! 404  'package_that_doesnt_exist' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log
```

### supporting information:

 - `npm -v` prints: `v7.2.1`
 - `node -v` prints: `4.1.1`
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?: `Mac OS X 10.12.2 build 16C67`
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by Fabiowsky** [comment]
Have the same problem.
Does anyone can help ?

Many thanks
Fabiowsky

**Comment by darkn3rd** [comment]
Numerous people run into this issue, and I suspect that many unique errors get trapped her with this generic path error.  I cannot stress the importance of having discernible error messages, especially as node could be used in production scenarios, beyond the developer's laptop...
