### ISSUE TITLE
npm install doesn't notice missing .bin

### ISSUE THREAD

**Issue by laughinghan** [npm/npm#15562]
#### I'm opening this issue because:

  - [x] npm is producing an incorrect install.

#### What's going wrong?

So the setup (this is _not_ npm doing something wrong) is that under [a certain real-world race condition I'm experiencing](https://mathquill.slack.com/archives/mathquill/p1482616486000235), `npm install` is successfully installing all the packages in their respective `./node_modules/*` folders, but being killed before it installs the `./node_modules/.bin/*` executables.

The problem is that subsequently doing `npm install` doesn't fix the broken install missing the `./node_modules/.bin/` folder.

This may be WONTFIX/NOTABUG because you don't want to promise to do a full integrity check during `npm install`, but I couldn't find an existing ticket on this so I thought it worth making explicit. On the other hand, it seemed like (with my race condition, at least) the packages are fully unpacked, so if there's some reason unpacking packages before installing `.bin/*` is atomic, checking for `.bin` could be a reasonable feature.

#### How can the CLI team reproduce the problem?

You can reproduce the lack of overwriting the broken install by doing:

```
echo '{
  "dependencies": {
    "less": "*"
  }
}' > package.json
mkdir node_modules
touch node_modules/.bin
npm install  # fails with ENOTDIR
rm node_modules/.bin
npm install  # no-op, does not create node_modules/.bin
```

You probably can't reproduce my race condition, but this is the `npm-debug.log` of my aborted `npm install`:
https://gist.github.com/laughinghan/811207f73dd5ddd9bd9c05b69bfc63a0

### supporting information:

 - `npm -v` prints: `2.15.8`
 - `node -v` prints: `v6.2.0`
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?: OS X El Capitan 10.11.6

**Comment by unional** [comment]
Experiencing similar issue. after using `npm link` and `npm unlink`. `npm i` does not populate `node_modules/.bin` correctly.

npm: 5.6.0

**Comment by fupslot** [comment]
`node: 8.10.0`
`npm: 5.6.0`

It happened in my docker container as well.
But, I managed to track the issue. In my case a developer modified `package.json` file manually (did not use `npm` command). Because of that, the file `package-lock.json` got de-synchronized.
I removed `package-lock.json` ran `npm install` and `.bin` folder appeared as usual.
