### ISSUE TITLE
'npm pack' blows up on urls that include the @ symbol

### ISSUE THREAD

**Issue by MylesBorins** [npm/npm#15563]
#### What's going wrong?

when calling `npm pack` on a path that includes an @ symbol the resolving algorithm blows up

#### How can the CLI team reproduce the problem?

```
$ wget  https://github.com/pugjs/pug/archive/pug@2.0.0-beta7.tar.gz
# this works YAY 
$ npm pack https://github.com/pugjs/pug/archive/pug@2.0.0-beta7.tar.gz
# this doesn't 😐
```

### supporting information:

 - `npm -v` prints: v2.15.11 || v3.10.10 || v4.0.5
 - `node -v` prints: v4.x ||  v6.x || v7.x
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: all

**Comment by MylesBorins** [comment]
Seeing something similar with babel

https://github.com/babel/babel/pull/5309

**Comment by watilde** [comment]
It seems that the `package.json` in the root directory doesn't have enough information to unpack instead of `@` in the URL. It can be reproduced with the current latest version of the babel.
```
$ npm pack https://github.com/babel/babel/archive/v6.23.0.tar.gz
npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "pack" "https://github.com/babel/babel/archive/v6.23.0.tar.gz"
npm ERR! node v7.4.0
npm ERR! npm  v4.3.0

npm ERR! No name provided
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/watilde/.npm/_logs/2017-02-15T09_47_57_771Z-debug.log
```

According to the official npm docs: name, description and version are required.
+ https://docs.npmjs.com/files/package.json

**Comment by MylesBorins** [comment]
@watilde I think we have gotten to the bottom of it. likely lerna is stripping more information than necessary from the package.json
