### ISSUE TITLE
Cannot run an angular application using "npm run start" or "npm run" 

### ISSUE THREAD

**Issue by JoshuaDdamba** [npm/npm#15576]
Cannot run an angular application using "npm run start" or "npm run" 
does anyone know whats happening.

 mac610813:angular-gridster jdki$ npm run start
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
npm ERR! node v6.9.3
npm ERR! npm  v4.1.1

npm ERR! missing script: start
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jdki/Desktop/exampleitu/angular-gridster/npm-debug.log

**Comment by KenanY** [comment]
@JoshuaDdamba Make sure to define a `"start"` script in your `package.json` before running `npm start`. See <https://docs.npmjs.com/misc/scripts>
