### ISSUE TITLE
NPM install is failing

### ISSUE THREAD

**Issue by inscrutabledude** [npm/npm#15579]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ X] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
When installing, NPM throws multiple errors.  I'm pasting the final output below:

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.17
npm WARN elasticsearch-head@0.0.0 license should be a valid SPDX license expression
npm ERR! Linux 4.4.0-59-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! phantomjs-prebuilt@2.1.14 install: `node install.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the phantomjs-prebuilt@2.1.14 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phantomjs-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/bruce/elasticsearch-head/npm-debug.log

#### How can the CLI team reproduce the problem?

simply try to install npm on the system i've specified

<script src="https://gist.github.com/inscrutabledude/74d72dba274261401c7827c09a1614e0.js"></script>

### supporting information:

 - Windows, OS X/macOS, or Linux?: Ubuntu 16.04
(update and upgrade done, but not dist-upgrade)
 - Network issues:
   - Geographic location where npm was run: Canada

 npm version
{ 'elasticsearch-head': '0.0.0',
  npm: '3.5.2',
  ares: '1.10.1-DEV',
  http_parser: '2.5.0',
  icu: '55.1',
  modules: '46',
  node: '4.2.6',
  openssl: '1.0.2g-fips',
  uv: '1.8.0',
  v8: '4.5.103.35',
  zlib: '1.2.8' }

**Comment by KenanY** [comment]
@inscrutabledude Are you able to run `node --version`?

**Comment by inscrutabledude** [comment]
It said command not found.  so I ran sudo apt install nodejs-legacy which ran ok.  The weird thing is that "regular" nodejs was installed before.  I then did sudo apt-get install npm and it ran again with only a coule warnings.

Of note:  pm2 was also not installing with this, so I had to install it separately using the -g switch.

Thanks for the help!
