### ISSUE TITLE
In all package pages, the message shows: Sadly, this package has no readme. Go write one!

### ISSUE THREAD

**Issue by heldrida** [npm/npm#15585]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by avoidwork** [comment]
This seems to affect packages published at some point yesterday, and going forward in time. I published 2 things yesterday and their READMEs disappeared, but older ones still have their README.

**Comment by simov** [comment]
> This seems to affect packages published at some point yesterday, and going forward in time. I published 2 things yesterday and their READMEs disappeared, but older ones still have their README.

That's not true, almost all of my packages have missing readme and some of them are puslished months ago. I can provide links if needed.

**Comment by simov** [comment]
Btw, this might be a problem with the website rather than the repository:

```html
<div id="readme" class="markdown">
    <p>
      Sadly, this package has no readme.
        <a href="https://github.com/simov/grant">Go write one!</a>
    </p>
</div>
```

**Comment by heldrida** [comment]
@simov sorry, I didn't get your point. But, just to be clear, npmjs dot com, surely a template for the package pages and there's a fn somewhere that is failing to pick the readme file from the package repositories. This may be server settings related! 
Some packages show the readme file, such as angularjs or leftpad. But most less popular packages I  checked have the README error I presented above. What @avoidwork  is quite relevant actually.

**Comment by simov** [comment]
NPM (this repository) is a package manager.

npmjs.com is a website (unless this is the website's repository as well, I have no idea)

Like I said I have dozens of packages published months ago (not yesterday) and all of them have missing readme.

**Comment by RusinovAnton** [comment]
As @simov said, my packages that weren't updated for a while also have no readme displayed as well as package I've published today

**Comment by soldair** [comment]
hey folks this is a registry issue not a cli issue. this was created to track it and we are working on it now.  
please add comments here https://github.com/npm/registry/issues/118

**Comment by soldair** [comment]
http://status.npmjs.org/incidents/tj3qsythtgg8 here is the status incident. Please check it for updates and thank you for reporting!

**Comment by heldrida** [comment]
@soldair I may be wrong but if my memory is not failing, I'm sure I did here "http://status.npmjs.org/"
the time I've reported 'Jan 26, 2017, 11:36 AM GMT' and the time it's in the status 'Jan 26, 13:09 UTC'. just trying to help really.

**Comment by BhavanPatel** [comment]
@heldrida @avoidwork @simov @RusinovAnton @soldair 
Simply publish
`npm version major`
or
`v1.0.0` or more
README issue will be sort out :)
