### ISSUE TITLE
INSTALLATION ISSUE

### ISSUE THREAD

**Issue by chisumo2016** [npm/npm#15586]
I am trying to  in run dev > npm run dev but i get error message 

standard: Use JavaScript Standard Style (https://github.com/feross/standard) 
  C:\Multi-Runner\builds\58469115\0\itchio\itch\appsrc\components\gate-page.js:40:85: Value must be omitted for boolean attributes
  C:\Multi-Runner\builds\58469115\0\itchio\itch\appsrc\components\icon.js:11:18: 'spin' is missing in props validation
  C:\Multi-Runner\builds\58469115\0\itchio\itch\appsrc\components\icon.js:11:32: 'classSet' is missing in props validation
  C:\Multi-Runner\builds\58469115\0\itchio\itch\appsrc\components\icon.js:12:33: 'data-tip' is missing in props validation

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "lint"
npm ERR! node v5.4.1
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! itch@0.13.2 lint: `standard --parser babel-eslint "appsrc/**/*.js" "testsrc/**/*.js"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the itch@0.13.2 lint script 'standard --parser babel-eslint "appsrc/**/*.js" "testsrc/**/*.js"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the itch package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     standard --parser babel-eslint "appsrc/**/*.js" "testsrc/**/*.js"
npm ERR! You can get their info via:
npm ERR!     npm owner ls itch
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Multi-Runner\builds\58469115\0\itchio\itch\npm-debug.log
npm ERR! Test failed.  See above for more details.

2.2

C:\xampp\htdocs\blog-5.4>npm run dev

> @ dev C:\xampp\htdocs\blog-5.4
> node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

'node_modules' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! @ dev: `node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR!

**Comment by chisumo2016** [comment]
C:\xampp\htdocs\blog-5.4>npm run dev

> cccccccc@1.0.0 dev C:\xampp\htdocs\blog-5.4
> node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

'node_modules' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! cccccccc@1.0.0 dev: `node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cccccccc@1.0.0 dev script 'node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/
webpack.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the cccccccc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs cccccccc
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls cccccccc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\xampp\htdocs\blog-5.4\npm-debug.log

C:\xampp\htdocs\blog-5.4>

**Comment by chisumo2016** [comment]
bundalla@bundalla-PC MINGW64 /c/xampp/htdocs/new5.4
$ npm install -g
npm ERR! addLocal Could not install C:\xampp\htdocs\new5.4
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9

npm ERR! No name provided in package.json
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\xampp\htdocs\new5.4\npm-debug.log

**Comment by KenanY** [comment]
```
C:\Multi-Runner\builds\58469115\0\itchio\itch\appsrc\components\gate-page.js:40:85: Value must be omitted for boolean attributes
C:\Multi-Runner\builds\58469115\0\itchio\itch\appsrc\components\icon.js:11:18: 'spin' is missing in props validation
C:\Multi-Runner\builds\58469115\0\itchio\itch\appsrc\components\icon.js:11:32: 'classSet' is missing in props validation
C:\Multi-Runner\builds\58469115\0\itchio\itch\appsrc\components\icon.js:12:33: 'data-tip' is missing in props validation
```

Your linting is failing.

```
'node_modules' is not recognized as an internal or external command,
operable program or batch file.
```

Try changing your `"dev"` script to

```
cross-env NODE_ENV=development webpack --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
```

```
npm ERR! No name provided in package.json
```

You're trying to install a module with no name, which is not allowed.

**Comment by KenanY** [comment]
Closing as abandoned.
