### ISSUE TITLE
npm 

### ISSUE THREAD

**Issue by yassirtobi** [npm/npm#15582]
#### I'm opening this issue because:

  - [x] npm is producing an incorrect install.

#### How can the CLI team reproduce the problem?

#npm-debug.log file :
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Utilisateur\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g' ]
2 info using npm@4.1.1
3 info using node@v4.2.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData .
8 silly fetchOtherPackageData .
9 silly cache add args [ '.', null ]
10 verbose cache add spec .
11 silly cache add parsed spec Result {
11 silly cache add   raw: '.',
11 silly cache add   scope: null,
11 silly cache add   escapedName: null,
11 silly cache add   name: null,
11 silly cache add   rawSpec: '.',
11 silly cache add   spec: 'C:\\Users\\Utilisateur',
11 silly cache add   type: 'local' }
12 error addLocal Could not install C:\Users\Utilisateur
13 silly fetchPackageMetaData Error: EISDIR: illegal operation on a directory, read
13 silly fetchPackageMetaData     at Error (native)
13 silly fetchPackageMetaData  error for . { [Error: EISDIR: illegal operation on a directory, read] errno: -4068, code: 'EISDIR', syscall: 'read' }
14 silly rollbackFailedOptional Starting
15 verbose stack TypeError: Cannot read property 'path' of null
15 verbose stack     at Object.Installer.rollbackFailedOptional (C:\Users\Utilisateur\AppData\Roaming\npm\node_modules\npm\lib\install.js:511:29)
15 verbose stack     at Array.<anonymous> (C:\Users\Utilisateur\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
15 verbose stack     at LOOP (C:\Users\Utilisateur\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
15 verbose stack     at C:\Users\Utilisateur\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:18:7
15 verbose stack     at C:\Users\Utilisateur\AppData\Roaming\npm\node_modules\npm\lib\install.js:337:5
15 verbose stack     at Array.<anonymous> (C:\Users\Utilisateur\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
15 verbose stack     at LOOP (C:\Users\Utilisateur\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
15 verbose stack     at chain (C:\Users\Utilisateur\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
15 verbose stack     at C:\Users\Utilisateur\AppData\Roaming\npm\node_modules\npm\lib\install.js:294:5
15 verbose stack     at C:\Users\Utilisateur\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:16:22
16 verbose cwd C:\Users\Utilisateur
17 error Windows_NT 6.1.7601
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Utilisateur\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g"
19 error node v4.2.1
20 error npm  v4.1.1
21 error Cannot read property 'path' of null
22 error If you need help, you may report this error at:
22 error     <https://github.com/npm/npm/issues>
23 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@yassirtobi What are you trying to do?

**Comment by KenanY** [comment]
Closing as abandoned.
