### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by jenevaL** [npm/npm#15591]
#### I'm opening this issue because:
  -  npm is producing an incorrect install.
 
#### What's going wrong?
  -  when I input <npm install> in my command line this error occurs:

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10

npm ERR! error:0906D06C:PEM routines:PEM_read_bio:no start line
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\neo4j\npm-debug.log

#### How can the CLI team reproduce the problem?

How can I resolve this problem so that I can finally install my npm correctly. 
This is what contains my debug-log:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'i',
1 verbose cli   '-S',
1 verbose cli   'express',
1 verbose cli   'babel-cli' ]
2 info using npm@3.10.10
3 info using node@v6.9.4
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData express@*
8 silly fetchPackageMetaData babel-cli
9 silly fetchNamedPackageData express
10 silly mapToRegistry name express
11 silly mapToRegistry using default registry
12 silly mapToRegistry registry https://registry.npmjs.org/
13 silly mapToRegistry data Result {
13 silly mapToRegistry   raw: 'express',
13 silly mapToRegistry   scope: null,
13 silly mapToRegistry   escapedName: 'express',
13 silly mapToRegistry   name: 'express',
13 silly mapToRegistry   rawSpec: '',
13 silly mapToRegistry   spec: 'latest',
13 silly mapToRegistry   type: 'tag' }
14 silly mapToRegistry uri https://registry.npmjs.org/express
15 silly fetchNamedPackageData babel-cli
16 silly mapToRegistry name babel-cli
17 silly mapToRegistry using default registry
18 silly mapToRegistry registry https://registry.npmjs.org/
19 silly mapToRegistry data Result {
19 silly mapToRegistry   raw: 'babel-cli',
19 silly mapToRegistry   scope: null,
19 silly mapToRegistry   escapedName: 'babel-cli',
19 silly mapToRegistry   name: 'babel-cli',
19 silly mapToRegistry   rawSpec: '',
19 silly mapToRegistry   spec: 'latest',
19 silly mapToRegistry   type: 'tag' }
20 silly mapToRegistry uri https://registry.npmjs.org/babel-cli
21 verbose request uri https://registry.npmjs.org/express
22 verbose request no auth needed
23 info attempt registry request try #1 at 12:08:20 PM
24 verbose request id 4e2ec56c3826dba4
25 http request GET https://registry.npmjs.org/express
26 info retry will retry, error on last attempt: Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
27 verbose request uri https://registry.npmjs.org/babel-cli
28 verbose request no auth needed
29 info attempt registry request try #1 at 12:08:20 PM
30 http request GET https://registry.npmjs.org/babel-cli
31 info retry will retry, error on last attempt: Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
32 info attempt registry request try #2 at 12:08:30 PM
33 http request GET https://registry.npmjs.org/express
34 info attempt registry request try #2 at 12:08:30 PM
35 http request GET https://registry.npmjs.org/babel-cli
36 info retry will retry, error on last attempt: Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
37 info retry will retry, error on last attempt: Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
38 info attempt registry request try #3 at 12:09:30 PM
39 http request GET https://registry.npmjs.org/express
40 info attempt registry request try #3 at 12:09:30 PM
41 http request GET https://registry.npmjs.org/babel-cli
42 silly fetchPackageMetaData Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
42 silly fetchPackageMetaData     at Error (native)
42 silly fetchPackageMetaData     at Object.createSecureContext (_tls_common.js:90:19)
42 silly fetchPackageMetaData     at Object.exports.connect (_tls_wrap.js:1020:48)
42 silly fetchPackageMetaData     at Agent.createConnection (https.js:82:22)
42 silly fetchPackageMetaData     at Agent.createSocket (_http_agent.js:195:26)
42 silly fetchPackageMetaData     at Agent.addRequest (_http_agent.js:157:10)
42 silly fetchPackageMetaData     at new ClientRequest (_http_client.js:160:16)
42 silly fetchPackageMetaData     at Object.exports.request (http.js:31:10)
42 silly fetchPackageMetaData     at Object.exports.request (https.js:199:15)
42 silly fetchPackageMetaData     at Request.start (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:740:32)
42 silly fetchPackageMetaData  error for express@* Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
42 silly fetchPackageMetaData     at Error (native)
42 silly fetchPackageMetaData     at Object.createSecureContext (_tls_common.js:90:19)
42 silly fetchPackageMetaData     at Object.exports.connect (_tls_wrap.js:1020:48)
42 silly fetchPackageMetaData     at Agent.createConnection (https.js:82:22)
42 silly fetchPackageMetaData     at Agent.createSocket (_http_agent.js:195:26)
42 silly fetchPackageMetaData     at Agent.addRequest (_http_agent.js:157:10)
42 silly fetchPackageMetaData     at new ClientRequest (_http_client.js:160:16)
42 silly fetchPackageMetaData     at Object.exports.request (http.js:31:10)
42 silly fetchPackageMetaData     at Object.exports.request (https.js:199:15)
42 silly fetchPackageMetaData     at Request.start (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:740:32)
43 silly fetchPackageMetaData Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
43 silly fetchPackageMetaData     at Error (native)
43 silly fetchPackageMetaData     at Object.createSecureContext (_tls_common.js:90:19)
43 silly fetchPackageMetaData     at Object.exports.connect (_tls_wrap.js:1020:48)
43 silly fetchPackageMetaData     at Agent.createConnection (https.js:82:22)
43 silly fetchPackageMetaData     at Agent.createSocket (_http_agent.js:195:26)
43 silly fetchPackageMetaData     at Agent.addRequest (_http_agent.js:157:10)
43 silly fetchPackageMetaData     at new ClientRequest (_http_client.js:160:16)
43 silly fetchPackageMetaData     at Object.exports.request (http.js:31:10)
43 silly fetchPackageMetaData     at Object.exports.request (https.js:199:15)
43 silly fetchPackageMetaData     at Request.start (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:740:32)
43 silly fetchPackageMetaData  error for babel-cli Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
43 silly fetchPackageMetaData     at Error (native)
43 silly fetchPackageMetaData     at Object.createSecureContext (_tls_common.js:90:19)
43 silly fetchPackageMetaData     at Object.exports.connect (_tls_wrap.js:1020:48)
43 silly fetchPackageMetaData     at Agent.createConnection (https.js:82:22)
43 silly fetchPackageMetaData     at Agent.createSocket (_http_agent.js:195:26)
43 silly fetchPackageMetaData     at Agent.addRequest (_http_agent.js:157:10)
43 silly fetchPackageMetaData     at new ClientRequest (_http_client.js:160:16)
43 silly fetchPackageMetaData     at Object.exports.request (http.js:31:10)
43 silly fetchPackageMetaData     at Object.exports.request (https.js:199:15)
43 silly fetchPackageMetaData     at Request.start (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:740:32)
44 silly rollbackFailedOptional Starting
45 silly rollbackFailedOptional Finishing
46 silly runTopLevelLifecycles Finishing
47 silly install printInstalled
48 verbose stack Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
48 verbose stack     at Error (native)
48 verbose stack     at Object.createSecureContext (_tls_common.js:90:19)
48 verbose stack     at Object.exports.connect (_tls_wrap.js:1020:48)
48 verbose stack     at Agent.createConnection (https.js:82:22)
48 verbose stack     at Agent.createSocket (_http_agent.js:195:26)
48 verbose stack     at Agent.addRequest (_http_agent.js:157:10)
48 verbose stack     at new ClientRequest (_http_client.js:160:16)
48 verbose stack     at Object.exports.request (http.js:31:10)
48 verbose stack     at Object.exports.request (https.js:199:15)
48 verbose stack     at Request.start (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:740:32)
49 verbose cwd C:\neo4j
50 error Windows_NT 10.0.14393
51 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "-S" "express" "babel-cli"
52 error node v6.9.4
53 error npm  v3.10.10
54 error error:0906D06C:PEM routines:PEM_read_bio:no start line
55 error If you need help, you may report this error at:
55 error     <https://github.com/npm/npm/issues>
56 verbose exit [ 1, true ]

-->

**Comment by alokbhawsinka** [comment]
Same issue when I start npm

npm ERR! Linux 4.4.0-59-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.7.2
npm ERR! npm  v2.15.11

npm ERR! missing script: start
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/alok/referraljobs/npm-debug.log

**Comment by KenanY** [comment]
@alokbhawsinka Your issue appears to be completely unrelated. Please open a new issue next time.

**Comment by jenevaL** [comment]
Issue solved after using  npm set registry http://registry.npmjs.org/ before installing
