### ISSUE TITLE
npm search -> core dump

### ISSUE THREAD

**Issue by phun-ky** [npm/npm#15592]
#### I'm opening this issue because:

  - [X] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
When using npm search, I get this:

    alexander@alexander-w541  ~/Workspace/IF/MyBusiness   f-webpack-2 ●  npm search extract-text-webpack-plugin
    npm WARN Building the local index for the first time, please be patient

    <--- Last few GCs --->

      30575 ms: Mark-sweep 1113.1 (1439.0) -> 1113.1 (1439.0) MB, 906.1 / 0.0 ms [allocation failure] [scavenge might not succeed].
      31499 ms: Mark-sweep 1113.1 (1439.0) -> 1113.1 (1439.0) MB, 923.7 / 0.0 ms [allocation failure] [scavenge might not succeed].
      32438 ms: Mark-sweep 1113.1 (1439.0) -> 1119.9 (1423.0) MB, 938.8 / 0.0 ms [last resort gc].
      33360 ms: Mark-sweep 1119.9 (1423.0) -> 1126.7 (1423.0) MB, 922.4 / 0.0 ms [last resort gc].

    <--- JS stacktrace --->

    ==== JS stack trace =========================================

    Security context: 0x3675101cfb51 <JS Object>
       1: stringify [native json.js:178] [pc=0x2b353cd16637] (this=0x3675101c9111 <a JSON with map 0x2f6a0a0a0e1>,E=0x3783b22f6701 <an Object with map 0x4b169ac2f89>,F=0x367510104381 <undefined>,S=0x367510104381 <undefined>)
       2: arguments adaptor frame: 1->3
       3: /* anonymous */ [/home/alexander/.nvm/versions/node/v6.6.0/lib/node_modules/npm/lib/cache/update-index.js:96] [pc=0x2b353cdeb621] (...

    FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
    1: node::Abort() [npm]
    2: 0x10a3b3c [npm]
    3: v8::Utils::ReportApiFailure(char const*, char const*) [npm]
    4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [npm]
    5: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [npm]
    6: v8::internal::IncrementalStringBuilder::Extend() [npm]
    7: v8::internal::BasicJsonStringifier::SerializeString(v8::internal::Handle<v8::internal::String>) [npm]
    8: v8::internal::BasicJsonStringifier::Result v8::internal::BasicJsonStringifier::Serialize_<true>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [npm]
    9: v8::internal::BasicJsonStringifier::Result v8::internal::BasicJsonStringifier::Serialize_<true>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [npm]
    10: v8::internal::BasicJsonStringifier::Result v8::internal::BasicJsonStringifier::Serialize_<false>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [npm]
    11: v8::internal::BasicJsonStringifier::Stringify(v8::internal::Handle<v8::internal::Object>) [npm]
    12: v8::internal::Runtime_BasicJSONStringify(int, v8::internal::Object**, v8::internal::Isolate*) [npm]
    13: 0x2b353c9092a7
    [1]    14878 abort (core dumped)  npm search extract-text-webpack-plugin

#### How can the CLI team reproduce the problem?
Don't know if this is a reliable way, but try `npm search extraxt-text-webpack-plugin`

### supporting information:

 - `npm -v` prints: 3.10.8
 - `node -v` prints: 6.6.0 
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Ubuntu 15.10
 - Network issues:
   - Geographic location where npm was run: Norway (proxy via Finland)
   - [X] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [X] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [X] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by phun-ky** [comment]
2nd time reproduced:

    npm search extract-text-webpack-plugin
    npm WARN Building the local index for the first time, please be patient

    <--- Last few GCs --->

       30125 ms: Mark-sweep 1107.8 (1436.0) -> 1107.8 (1436.0) MB, 976.4 / 0.0 ms [allocation failure] [scavenge might not succeed].
       31074 ms: Mark-sweep 1107.8 (1436.0) -> 1107.8 (1436.0) MB, 948.4 / 0.0 ms [allocation failure] [scavenge might not succeed].
       32059 ms: Mark-sweep 1107.8 (1436.0) -> 1114.6 (1420.0) MB, 984.6 / 0.0 ms [last resort gc].
       33024 ms: Mark-sweep 1114.6 (1420.0) -> 1121.4 (1420.0) MB, 964.7 / 0.0 ms [last resort gc].


    <--- JS stacktrace --->

    ==== JS stack trace =========================================

    Security context: 0x3b84410cfb51 <JS Object>
        1: stringify [native json.js:178] [pc=0x167b33f16637] (this=0x3b84410c9111 <a JSON with map 0xb847e60a0e1>,E=0xd95a09f7dd9 <an Object with map 0xafd6d70d839>,F=0x3b8441004381 <undefined>,S=0x3b8441004381 <undefined>)
        2: arguments adaptor frame: 1->3
        3: /* anonymous */ [/home/alexander/.nvm/versions/node/v6.6.0/lib/node_modules/npm/lib/cache/update-index.js:96] [pc=0x167b33fea201] (t...

    FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
     1: node::Abort() [npm]
     2: 0x10a3b3c [npm]
     3: v8::Utils::ReportApiFailure(char const*, char const*) [npm]
     4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [npm]
     5: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [npm]
     6: v8::internal::IncrementalStringBuilder::Extend() [npm]
     7: v8::internal::BasicJsonStringifier::SerializeString(v8::internal::Handle<v8::internal::String>) [npm]
     8: v8::internal::BasicJsonStringifier::Result v8::internal::BasicJsonStringifier::Serialize_<true>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [npm]
     9: v8::internal::BasicJsonStringifier::Result v8::internal::BasicJsonStringifier::Serialize_<true>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [npm]
    10: v8::internal::BasicJsonStringifier::Result v8::internal::BasicJsonStringifier::Serialize_<false>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [npm]
    11: v8::internal::BasicJsonStringifier::Stringify(v8::internal::Handle<v8::internal::Object>) [npm]
    12: v8::internal::Runtime_BasicJSONStringify(int, v8::internal::Object**, v8::internal::Isolate*) [npm]
    13: 0x167b33b092a7
    [1]    15695 abort (core dumped)  npm search extract-text-webpack-plugin

**Comment by KenanY** [comment]
@phun-ky Please try updating to `npm@4`.

**Comment by KenanY** [comment]
Closing as abandoned.

**Comment by phun-ky** [comment]
The issue is resolved with `npm@4`, but is not fixed for `npm@3`. Please notice the difference :)

**Comment by KenanY** [comment]
Noticed, but the fix won't be backported to `npm@3` as far as I am aware.
