### ISSUE TITLE
NPM always installs packages globally

### ISSUE THREAD

**Issue by Dmitri-2** [npm/npm#15606]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [X] npm is doing something I don't understand.
- [ ] npm is producing an incorrect install.
    - [ ] Other (_see below for feature requests_):

#### What's going wrong?

NPM is always installing modules globally, rather than locally, using the`npm install <package>` command. 

For example: `npm install sweetalert` installs the package globally in `/Users/<USER>`, rather than the directory that the command was run from (`/Users/Dmitri/npmTest/test`). 

**Here is what NPM prints:** 
```
Dmitri$ npm install sweetalert
/Users/Dmitri
└── sweetalert@1.1.3 

npm WARN enoent ENOENT: no such file or directory, open '/Users/Dmitri/package.json'
npm WARN Dmitri No description
npm WARN Dmitri No repository field.
npm WARN Dmitri No README data
npm WARN Dmitri No license field.
```
and 
```
Dmitri$ ls node_modules
ls: node_modules: No such file or directory
```

Also, what is NPM doing in terms of looking for a package.json in my user directory? By just running an `npm install <package>` I would think that I'm not doing anything that would cause NPM to look for a package in that directory... 

#### How can the CLI team reproduce the problem?

Install any package using `npm install <package>` in a newly created subdirectory on your system. 

### supporting information:

 -  **Note:** Before posting this, I uninstalled NPM and reinstalled it with Node to clear the system. 
 - `npm -v` prints: `3.10.10`
 - `node -v` prints: `v6.9.4`
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?: `macOS: OS X 10.11.6`
 - Network issues:
   - Geographic location where npm was run: `USA`
   - NPM run locally on machine

**Comment by JamieMason** [comment]
When running `npm config get` is there anything in there like `global = true`? My guess is you _might_ have an `.npmrc` file in the current or an ancestor directory that contains that setting.

**Comment by Dmitri-2** [comment]
@JamieMason Thank you for getting back to me! 
I don't think I have any `.npmrc` files that contain a `global=true`.
When running `npm config get`, this is what the global section looks like: 
```
git = "git"
git-tag-version = true
global = false
global-style = false
globalconfig = "/usr/local/etc/npmrc"
globalignorefile = "/usr/local/etc/npmignore"
```
I have also checked all of the parent directories for `.npmrc` files, and the one place where it does exist (my home directory), the global option is set to `false`.  

Setting `global=true`, and then attempting a local install yielded the error below, as npm attempted to install the package in `/usr/local/lib`: 
```
/usr/local/lib
└── sweetalert@1.1.3 

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "sweetalert"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! path /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! sys call access
....
....
```

In essence, I an just trying to get a npm package pulled into a local directory, under the `node_modules/` directory name... Is there any workaround that I could use?

**Comment by Dmitri-2** [comment]
I'm closing this issue since it is most likely something specific to my system, and I'm guessing there isn't enough manpower to resolve every single issue filed. Fortunately, I have fixed the problem by adding an additional `package.json` that asks for the npm package that I want installed locally as a requirement. This somehow forces npm to do a local install into `node_modules`.

Would be interested to hear if anyone else has had a similar problem.

**Comment by kleosinc** [comment]
I have this same issue.  All packages are installed globally even without the -g flag.   Will try your work around.

**Comment by princegaurav** [comment]
Even I am getting exactly the same issue. All packages are getting installed globally.

when I run => npm install gulp gulp-sass --save-dev

It goes to look for package.json in my home directory, instead of local one.

I get=>
```
npm WARN enoent ENOENT: no such file or directory, open '/Users/Prince/package.json'
npm WARN Prince No description
npm WARN Prince No repository field.
npm WARN Prince No README data
npm WARN Prince No license field.
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "gulp" "gulp-sass" "--save-dev"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! path /Users/Prince/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/Users/Prince/node_modules'
npm ERR!     at Error (native)
npm ERR!  { Error: EACCES: permission denied, access '/Users/Prince/node_modules'
npm ERR!     at Error (native)
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/Users/Prince/node_modules' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
```

**Comment by princegaurav** [comment]
**Update:** I was running the command without having a ```package.json``` file in the local directory. After I created a ```package.json``` file using ```npm init``` in my local directory, it worked and installed modules in local directory.
So, I guess you got to have a ```package.json``` file in local directory where you want to install modules locally using ```npm``` , else it will look for ```package.json``` in home directory and try to install it globally
