### ISSUE TITLE
module.js:472 throw err;

### ISSUE THREAD

**Issue by DrewBDeRuiter** [npm/npm#15602]
#### I'm opening this issue because:

  - [X ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [] Other (_see below for feature requests_):

#### What's going wrong?

I am new to node.js and I can't get it to load a simple 'helloworld.js' file.

my 'helloworld.js' file contains just one line of code
console.log("helloworld");

I am in the 'C:\Web_Projects\nodePractice' in the command prompt

when i try to run 'node helloworld.js" from the windows command prompt i get the following error

module.js:472
    throw err;
    ^

Error: Cannot find module 'C:\Web_Projects\nodePractice\helloworld.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3

---------------------

node -v
7.4.0
npm -v
4.1.1

**Comment by KenanY** [comment]
Looks like Node thinks that the file doesn't exist. Make sure that you are in the right directory and that you've entered the correct file name.

Since this has nothing to do with `npm` itself, I'm gonna close this.

**Comment by DrewBDeRuiter** [comment]
It doesn't matter what i do.  If I put it in the root directory. and rename it to 'A.js'  i get the same error when i run c:\node A.js

**Comment by DrewBDeRuiter** [comment]
OK.  I finally figured it out.  When it was saving I was saving it as 'A.js' but it was saving it as a text file so the file name was 'A.js.txt'.  renaming it solved my problem.

**Comment by endashawdemsis** [comment]
module.js: 472
    throw err;
it also occur when i tried to install electron in global mode
