### ISSUE TITLE
Having issue with npm publish and unpublish 

### ISSUE THREAD

**Issue by GJ2511** [npm/npm#15609]
Hi I published new module to npm  https://www.npmjs.com/package/node-basic-utils using `npm publish`

The command executes successfully and my module is published.

> Sadly, this package has no readme. Go write one!

but **README** is present in my git repo https://github.com/GJ2511/node-utils

So I decided to unpublish it using  `npm unpublish` even with  `npm unpublish --force`

Above command executes successfully. But my module still exists on npm.

Can somebody please help me with this issue?
Also why my README is not get displayed on my module?

My npm version is 

> 3.10.10

**Comment by JamieMason** [comment]
> So I decided to unpublish it using npm publish even with npm publish --force

is the problem that it should be `npm unpublish` rather than `npm publish`?

**Comment by BhavanPatel** [comment]
@GJ2511  
Simply publish `npm version major` and `npm publish` or `v1.0.0` or more README issue will be sort out :)
