### ISSUE TITLE
I need to delete the module

### ISSUE THREAD

**Issue by yuchonghua** [npm/npm#15605]
I need to remove the modules, which have been relieved of all dependencies
cjb-jsnet
cjb-jstelnet
ddv-mustache-1-0
ddv-push-rpc-hub-1-0
ddv-server-extend-mustache-1-0

**Comment by KenanY** [comment]
@yuchonghua Please email `support@npmjs.com` for package unpublishing.

**Comment by yuchonghua** [comment]
@KenanY No one has responded to this request(12656) yet
