### ISSUE TITLE
'npm install -g yo' fails

### ISSUE THREAD

**Issue by DieterHegemann** [npm/npm#15608]
#### I'm opening this issue because:

when installing 'npm install -g yo' I receive the following Messages

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "yo"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5

npm ERR! Cannot read property 'path' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Windows\system32\npm-debug.log

[npm-debug.log.txt](https://github.com/npm/npm/files/738597/npm-debug.log.txt)

**Comment by JamieMason** [comment]
The error log says;

```
18 http request GET https://registry.npmjs.org/yo
19 info retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.36.162:443
```

This might suggest you were possibly offline at the time? Or a Corporate firewall could be blocking access to https://registry.npmjs.org/yo maybe?
