### ISSUE TITLE
No one has responded to this request(12656) yet

### ISSUE THREAD

**Issue by yuchonghua** [npm/npm#15613]
[request(12656)](https://github.com/npm/npm/issues/15605)
![image](https://cloud.githubusercontent.com/assets/17898715/22431016/0a74d9a0-e74b-11e6-94a1-24d78e2a5fb6.png)

**Comment by legodude17** [comment]
Please don't report that here. Maybe add a comment to the support request, and then be patient.

**Comment by KenanY** [comment]
To be honest, I don't think that making this post will expedite the process.
