### ISSUE TITLE
Force incompatible license change to be a breaking change

### ISSUE THREAD

**Issue by graingert** [npm/npm#15616]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's the feature?
People sometime change license on their package, and only bump semver minor or patch.
Eg MIT -> GPL
If the license SPDX changes to a different or non-superset SPDX expression, prevent package updates without semver major version bump.

* MIT -> GPL forces a bump
* MIT -> MIT OR GPL does not force a bump
* GPL -> MIT undefined behaviour. Forces a bump is fine, maintaining a graph of compatible licenses is out of scope.

#### What problem is the feature intended to solve?
When I upgrade, I am automatically forced into a license non-compliant state.

#### Is the absence of this feature blocking you or your team? If so, how?
I have to implement an automated check and manually pin versions accordingly.

#### Is this a feature you're prepared to implement, with support from the npm CLI team?
sure.

**Comment by sholladay** [comment]
Hey, nice idea! SPDX expressions are a lot easier to analyze than breaking changes to code.

Presumably this is something that would live in the `npm publish` command. You'd still be able to bump with `npm version`.

In the meantime, @sindresorhus may be willing to consider it in [np](https://github.com/sindresorhus/np). Maybe file an issue there.

**Comment by sindresorhus** [comment]
> In the meantime, @sindresorhus may be willing to consider it in np. Maybe file an issue there.

Happy to consider it, but I think it's something that should really be in the package manager, so let's give this issue some time first. I would also recommend opening the same issue on [Yarn](https://github.com/yarnpkg/yarn). They're usually more responsive.
