### ISSUE TITLE
"npm install" works on Mac but fails on Windows

### ISSUE THREAD

**Issue by saleemis** [npm/npm#15617]
#### I'm opening this issue because:

  - [ * ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
On our project, command "npm install" works fine on MacOS but fails with error on Windows. The npm-debug.log file is attached.

#### How can the CLI team reproduce the problem?
 npm-debug.log file: https://gist.github.com/saleemis/3feaac4ad51358b5fba47760a9a3e269

### supporting information:

 - `npm -v` prints: 4.0.5
 - `node -v` prints: v7.4.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows?: Windows7 Enterprise, Service Pack 1 
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
Looks like an issue with your internet connection:

```
10965 error fatal: unable to connect to github.com:
```

**Comment by KenanY** [comment]
Closing as abandoned and not an issue with `npm` anyways.
