### ISSUE TITLE
npm install pdffiller not working

### ISSUE THREAD

**Issue by awaix** [npm/npm#15625]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'pdffiller' ]
2 info using npm@3.10.10
3 info using node@v6.9.4
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData pdffiller
8 silly fetchNamedPackageData pdffiller
9 silly mapToRegistry name pdffiller
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'pdffiller',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'pdffiller',
12 silly mapToRegistry   name: 'pdffiller',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/pdffiller
14 verbose request uri https://registry.npmjs.org/pdffiller
15 verbose request no auth needed
16 info attempt registry request try #1 at 8:16:27 PM
17 verbose request id 6040e61a395a9e98
18 verbose etag W/"57f7bc17-404b"
19 verbose lastModified Fri, 07 Oct 2016 15:15:35 GMT
20 http request GET https://registry.npmjs.org/pdffiller
21 http 304 https://registry.npmjs.org/pdffiller
22 verbose headers { date: 'Tue, 31 Jan 2017 15:16:06 GMT',
22 verbose headers   via: '1.1 varnish',
22 verbose headers   'cache-control': 'max-age=300',
22 verbose headers   etag: 'W/"57f7bc17-404b"',
22 verbose headers   age: '0',
22 verbose headers   connection: 'keep-alive',
22 verbose headers   'x-served-by': 'cache-cdg8726-CDG',
22 verbose headers   'x-cache': 'HIT',
22 verbose headers   'x-cache-hits': '1',
22 verbose headers   'x-timer': 'S1485875766.199607,VS0,VE17',
22 verbose headers   vary: 'Accept-Encoding' }
23 silly get cb [ 304,
23 silly get   { date: 'Tue, 31 Jan 2017 15:16:06 GMT',
23 silly get     via: '1.1 varnish',
23 silly get     'cache-control': 'max-age=300',
23 silly get     etag: 'W/"57f7bc17-404b"',
23 silly get     age: '0',
23 silly get     connection: 'keep-alive',
23 silly get     'x-served-by': 'cache-cdg8726-CDG',
23 silly get     'x-cache': 'HIT',
23 silly get     'x-cache-hits': '1',
23 silly get     'x-timer': 'S1485875766.199607,VS0,VE17',
23 silly get     vary: 'Accept-Encoding' } ]
24 verbose etag https://registry.npmjs.org/pdffiller from cache
25 verbose get saving pdffiller to C:\Users\U-Ba\AppData\Roaming\npm-cache\registry.npmjs.org\pdffiller\.cache.json
26 verbose correctMkdir C:\Users\U-Ba\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
27 silly install normalizeTree
28 silly loadCurrentTree Finishing
29 silly loadIdealTree Starting
30 silly install loadIdealTree
31 silly cloneCurrentTree Starting
32 silly install cloneCurrentTreeToIdealTree
33 silly cloneCurrentTree Finishing
34 silly loadShrinkwrap Starting
35 silly install loadShrinkwrap
36 silly loadShrinkwrap Finishing
37 silly loadAllDepsIntoIdealTree Starting
38 silly install loadAllDepsIntoIdealTree
39 silly rollbackFailedOptional Starting
40 silly rollbackFailedOptional Finishing
41 silly runTopLevelLifecycles Finishing
42 silly install printInstalled
43 verbose stack Error: Refusing to install pdffiller as a dependency of itself
43 verbose stack     at checkSelf (C:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:53:14)
43 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
43 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
43 verbose stack     at chain (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
43 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:16:5
43 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
43 verbose stack     at Array.forEach (native)
43 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
43 verbose stack     at Array.forEach (native)
43 verbose stack     at asyncMap (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
44 verbose cwd C:\Users\U-Ba\Desktop\pdffiller-master
45 error Windows_NT 10.0.14393
46 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "pdffiller"
47 error node v6.9.4
48 error npm  v3.10.10
49 error code ENOSELF
50 error Refusing to install pdffiller as a dependency of itself
51 error If you need help, you may report this error at:
51 error     <https://github.com/npm/npm/issues>
52 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
```
50 error Refusing to install pdffiller as a dependency of itself
```

Make sure the `"name"` field of your `package.json` is not set to `"pdffiller"`.

**Comment by awaix** [comment]
Still the issue is same, after changing name.

**Comment by awaix** [comment]
here is the next log file.

**Comment by KenanY** [comment]
@awaix Upload the log file to <https://gist.github.com/> and post the link here.

**Comment by KenanY** [comment]
Closing as abandoned.
