### ISSUE TITLE
npm ERR! addLocal Could not install C:\Users\Lap127\AppData\Local\Temp\npm-4684-7ff010cc\git-cache-8a603ef4\aabed1bd8010ea95351a5223e8ec987d4bfadb00

### ISSUE THREAD

**Issue by leder11011** [npm/npm#15624]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [X ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
package is not installed, error thrown!

#### How can the CLI team reproduce the problem?
C:\Sites\blog_production_heroku>heroku plugins:install https://github.com/naaman/heroku-vim

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

[npm-debug.txt](https://github.com/npm/npm/files/742252/npm-debug.txt)

**Comment by KenanY** [comment]
<https://github.com/naaman/heroku-vim> is not an `npm` package, therefore you cannot install it via `npm`.
