### ISSUE TITLE
npm connection timed out

### ISSUE THREAD

**Issue by lavigne958** [npm/npm#15637]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I can not install package tidy-markdown, got an error using atom package interface or apm terminal.

#### How can the CLI team reproduce the problem?

I juste did: apm install tidy-markdown on my terminal.

npm dubg file:

npm ERR! git clone --template=/home/alexandre/.atom/.apm/_git-remotes/_templates --mirror git://github.com/slang800/tidy-markdown.git /home/alexandre/.atom/.apm/_git-remotes/git-github-com-slang800-tidy-markdown-git-v2-0-3-765a2aeb: Cloning into bare repository '/home/alexandre/.atom/.apm/_git-remotes/git-github-com-slang800-tidy-markdown-git-v2-0-3-765a2aeb'...
npm ERR! git clone --template=/home/alexandre/.atom/.apm/_git-remotes/_templates --mirror git://github.com/slang800/tidy-markdown.git /home/alexandre/.atom/.apm/_git-remotes/git-github-com-slang800-tidy-markdown-git-v2-0-3-765a2aeb: fatal: unable to connect to github.com:
npm ERR! git clone --template=/home/alexandre/.atom/.apm/_git-remotes/_templates --mirror git://github.com/slang800/tidy-markdown.git /home/alexandre/.atom/.apm/_git-remotes/git-github-com-slang800-tidy-markdown-git-v2-0-3-765a2aeb: github.com[0: 192.30.253.113]: errno=Connection timed out
npm ERR! git clone --template=/home/alexandre/.atom/.apm/_git-remotes/_templates --mirror git://github.com/slang800/tidy-markdown.git /home/alexandre/.atom/.apm/_git-remotes/git-github-com-slang800-tidy-markdown-git-v2-0-3-765a2aeb: github.com[1: 192.30.253.112]: errno=Connection timed out
npm ERR! Linux 4.4.0-21-generic
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/alexandre/.atom/.apm/.apmrc" "--userconfig" "/home/alexandre/.atom/.apmrc" "install" "/tmp/d-11711-7023-1r31v47/package.tgz" "--runtime=electron" "--target=1.3.13" "--arch=x64" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code 128

npm ERR! Command failed: git clone --template=/home/alexandre/.atom/.apm/_git-remotes/_templates --mirror git://github.com/slang800/tidy-markdown.git /home/alexandre/.atom/.apm/_git-remotes/git-github-com-slang800-tidy-markdown-git-v2-0-3-765a2aeb
npm ERR! Cloning into bare repository '/home/alexandre/.atom/.apm/_git-remotes/git-github-com-slang800-tidy-markdown-git-v2-0-3-765a2aeb'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.253.113]: errno=Connection timed out
npm ERR! github.com[1: 192.30.253.112]: errno=Connection timed out
npm ERR! 
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-11711-7023-1vspwdr/npm-debug.log

### supporting information:

 - `npm -v` prints: npm  v3.10.5
 - `node -v` prints: v4.4.5
 - `npm config get registry` prints: npm config get registry` 
 - Windows, OS X/macOS, or Linux?: Linux
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [x] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@lavigne958 Looks like an issue with your internet connection:

```
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.253.113]: errno=Connection timed out
npm ERR! github.com[1: 192.30.253.112]: errno=Connection timed out
```

**Comment by lavigne958** [comment]
I believed so,  but I could install the package "markdown-writer"  without a problem.  
So it can't be my connection.

**Comment by KenanY** [comment]
@lavigne958 Maybe that package did not require you to `git clone` a repository like this one is.

**Comment by KenanY** [comment]
Closing since this isn't an issue with `npm` itself.
