### ISSUE TITLE
unmet peer dependency grunt@1.0.1

### ISSUE THREAD

**Issue by anjietha09** [npm/npm#15635]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by anjietha09** [comment]
npm install grunt-contrib-nodeunit
readium-js-viewer@0.24.0 C:\Users\TONEW\readium-js-viewer
+-- UNMET PEER DEPENDENCY grunt@1.0.1
`-- grunt-contrib-nodeunit@1.0.0

npm WARN grunt-selenium-webdriver@0.2.482 requires a peer of grunt@~0.4.5 but none was installed.

**Comment by KenanY** [comment]
Just install the unmet dependency :)

**Comment by anjietha09** [comment]
I tried installing it but that too doesn't work

**Comment by KenanY** [comment]
@anjietha09 Could you show what doesn't work? Preferably through a `npm-debug.log` file, which is generated whenever `npm` encounters an error.

**Comment by anjietha09** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'prepare' ]
2 info using npm@4.1.2
3 info using node@v7.5.0
4 verbose run-script [ 'prepare' ]
5 info lifecycle readium-js-viewer@0.25.0-alpha~prepare: readium-js-viewer@0.25.0-alpha
6 verbose lifecycle readium-js-viewer@0.25.0-alpha~prepare: unsafe-perm in lifecycle true
7 verbose lifecycle readium-js-viewer@0.25.0-alpha~prepare: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\dell\readium-js-viewer\node_modules\.bin;C:\Users\dell\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\dell\bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\AMD\ATI.ACE\Core-Static;C:\Program Files\Intel\WiFi\bin;C:\Program Files\Common Files\Intel\WirelessCommon;C:\Program Files\Dell\DW WLAN Card;C:\Program Files\nodejs;C:\Program Files\Git\cmd;C:\Users\dell\Anaconda3;C:\Users\dell\Anaconda3\Scripts;C:\Users\dell\Anaconda3\Library\bin;C:\Program Files\Intel\WiFi\bin;C:\Program Files\Common Files\Intel\WirelessCommon;C:\Users\dell\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
8 verbose lifecycle readium-js-viewer@0.25.0-alpha~prepare: CWD: C:\Users\dell\readium-js-viewer
9 silly lifecycle readium-js-viewer@0.25.0-alpha~prepare: Args: [ '/d /s /c',
9 silly lifecycle   'npm run prepare:submodule && npm run prepare:local' ]
10 silly lifecycle readium-js-viewer@0.25.0-alpha~prepare: Returned: code: 1  signal: null
11 info lifecycle readium-js-viewer@0.25.0-alpha~prepare: Failed to exec prepare script
12 verbose stack Error: readium-js-viewer@0.25.0-alpha prepare: `npm run prepare:submodule && npm run prepare:local`
12 verbose stack Exit status 1
12 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:279:16)
12 verbose stack     at emitTwo (events.js:106:13)
12 verbose stack     at EventEmitter.emit (events.js:192:7)
12 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
12 verbose stack     at emitTwo (events.js:106:13)
12 verbose stack     at ChildProcess.emit (events.js:192:7)
12 verbose stack     at maybeClose (internal/child_process.js:890:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
13 verbose pkgid readium-js-viewer@0.25.0-alpha
14 verbose cwd C:\Users\dell\readium-js-viewer
15 error Windows_NT 6.1.7601
16 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "prepare"
17 error node v7.5.0
18 error npm  v4.1.2
19 error code ELIFECYCLE
20 error readium-js-viewer@0.25.0-alpha prepare: `npm run prepare:submodule && npm run prepare:local`
20 error Exit status 1
21 error Failed at the readium-js-viewer@0.25.0-alpha prepare script 'npm run prepare:submodule && npm run prepare:local'.
21 error Make sure you have the latest version of node.js and npm installed.
21 error If you do, this is most likely a problem with the readium-js-viewer package,
21 error not with npm itself.
21 error Tell the author that this fails on your system:
21 error     npm run prepare:submodule && npm run prepare:local
21 error You can get information on how to open an issue for this project with:
21 error     npm bugs readium-js-viewer
21 error Or if that isn't available, you can get their info via:
21 error     npm owner ls readium-js-viewer
21 error There is likely additional logging output above.
22 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
Your `"prepare"` script is throwing an error code. Make sure you can run it outside of `npm` without error.

**Comment by anjietha09** [comment]
hoc can i do it. Actually i want to integrate readium reader into my app. so i clone its repository and when i am performing npm run prepare it gives error
