### ISSUE TITLE
#### What's going wrong?

### ISSUE THREAD

**Issue by anki19** [npm/npm#15634]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
ailed to parse json
npm ERR! Trailing comma in object at 4:1
npm ERR! }
npm ERR! ^
npm ERR! File: /Users/annbenson/Desktop/ABprojects/realestate/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/annbenson/Desktop/ABprojects/realestate/npm-debug.log
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by anki19** [comment]
ailed to parse json
npm ERR! Trailing comma in object at 4:1
npm ERR! }
npm ERR! ^
npm ERR! File: /Users/annbenson/Desktop/ABprojects/realestate/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/annbenson/Desktop/ABprojects/realestate/npm-debug.log

**Comment by KenanY** [comment]
@anki19 Looks like there's a syntax error in your `package.json`.

**Comment by anki19** [comment]
I had to move it and remove a comma
