### ISSUE TITLE
npm install issue

### ISSUE THREAD

**Issue by kamleshpaliwal-tudip** [npm/npm#15636]
I am facing problem during npm installation please help and show me the way to resolve this.
![npm install error](https://cloud.githubusercontent.com/assets/25119254/22497859/6dd6e260-e87a-11e6-871e-cda252c9b04c.png)

**Comment by kejwmen** [comment]
I encountered the same issue. It downloads newer release (1.1.2), but tries to fetch 1.1.1 from cache. Guess we should contact angular-material maintainers.

**Comment by kamleshpaliwal-tudip** [comment]
Ok brother I am trying.

**Comment by kejwmen** [comment]
We used exact match ("1.1.2") in package.json instead of approximation, and it worked.
