### ISSUE TITLE
errors with latest version of npm  v4.0.5

### ISSUE THREAD

**Issue by DrYSG** [npm/npm#15647]
Repeatable errror. Seems to be relate to:

```
2277 verbose stack Error: shasum check failed for C:\Users\ysg4206\AppData\Local\Temp\npm-30968-d03a0780\registry.npmjs.org\jsondiffpatch\-\jsondiffpatch-0.2.4.tgz
2277 verbose stack Expected: d4b6c53b3fc7da1b4b91c1c2aec8b932b7511d5c
2277 verbose stack Actual:   43acc5297efc757e42b2359e4aabf4e4a1c4b7e1
2277 verbose stack From:     http://registry.npmjs.org/jsondiffpatch/-/jsondiffpatch-0.2.4.tgz
2277 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:25:8
2277 verbose stack     at ReadStream.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:72:7)
2277 verbose stack     at emitNone (events.js:91:20)
2277 verbose stack     at ReadStream.emit (events.js:185:7)
2277 verbose stack     at endReadableNT (_stream_readable.js:974:12)
2277 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:74:11)
2277 verbose stack     at process._tickCallback (internal/process/next_tick.js:98:9)
```

#### I'm opening this issue because:

  - [x ] npm is crashing.

Full LOG is attached.

#### What's going wrong?

npm WARN deprecated husl@5.0.3: Project renamed to HSLuv
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-
cli.js" "update"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
[npm-debug.log.txt](https://github.com/npm/npm/files/746127/npm-debug.log.txt)

npm ERR! shasum check failed for C:\Users\ysg4206\AppData\Local\Temp\npm-30968-d03a0780\registry.npmjs.org\j
sondiffpatch\-\jsondiffpatch-0.2.4.tgz
npm ERR! Expected: d4b6c53b3fc7da1b4b91c1c2aec8b932b7511d5c
npm ERR! Actual:   43acc5297efc757e42b2359e4aabf4e4a1c4b7e1
npm ERR! From:     http://registry.npmjs.org/jsondiffpatch/-/jsondiffpatch-0.2.4.tgz
npm ERR!

**Comment by doug-wade** [comment]
@DrYSG this usually happens when there's a problem with your tarball download.  Can you retry?  Is your internet connection stable?

**Comment by DrYSG** [comment]
connection is stable. but behind corporate firewall. I have retried, and it now works.
