### ISSUE TITLE
Local commands not running. `x`: Command not found

### ISSUE THREAD

**Issue by mrmartineau** [npm/npm#15648]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?
I am not able to run commands (e.g. `grunt foo`) for locally installed packages. Note, these are not packages installed with the `-g` flag.

On bash, the error is like this:

```sh
-bash: grunt: command not found
```

On [fish](https://fishshell.com) the error is:

```sh
fish: Unknown command 'grunt'
```

All npm packages have been successfully installed with npm@4.1.2 and there are binaries in the `node_modules/.bin` directory.

It seems like a `$PATH` issue, but I am able to run npm run scripts in the same project directory and use node/npm elsewhere without fault. What is particularly strange is if I map a command like `grunt compile` to `npm start`, it runs the task without error.

```json
{
  "scripts": {
    "start": "grunt compile"
  }
}
```

How could this be happening?

--- 

### supporting information:

 - `npm -v` prints: `4.1.2`
 - `node -v` prints: `v7.5.0`
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?: macOS
 - Network issues:
   - Geographic location where npm was run: London
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by mrmartineau** [comment]
Its also worth noting that I've been trying to debug this already. I thought it was a fish-related bug, but am now convinced it is an npm-related bug.. see https://github.com/fish-shell/fish-shell/issues/3795 for reference

**Comment by KenanY** [comment]
Not a bug, `npm` has never added local binaries to `PATH`, _EXCEPT_ when `npm` scripts are executed. If you wanna run binaries from your command-line, you should install them globally. That's why global modules exist.

**Comment by mrmartineau** [comment]
Hi @KenanY, It seems that I may be mistaken, but I could swear after `grunt` moved to >v1.0.0, the global `grunt-cli` did not need to be installed anymore.. I have just moved to a new machine and that is why none of these global packages work now.. 😕 

I think you have solved my query but I am still confused about it... Thanks
