### ISSUE TITLE
sails js issue

### ISSUE THREAD

**Issue by Muthukumars1994** [npm/npm#15643]
#### I'm opening this issue because:
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.

**I need to install my sails in E drive but it throws the minimatch error**

E:\Muthu\nodejs>npm install sails -g
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher
 to avoid a RegExp DoS issue
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated native-or-bluebird@1.1.2: 'native-or-bluebird' is deprecated
. Please use 'any-promise' instead.

# I can't see the below folder in the c drive #

> sails@0.12.11 preinstall C:\Users\Administrator\AppData\Roaming\npm\node_modul
es\.staging\sails-fa618c93
> node ./lib/preinstall_npmcheck.js

Sails.js Installation: Checking npm-version successful
C:\Users\Administrator\AppData\Roaming\npm\sails -> C:\Users\Administrator\AppDa
ta\Roaming\npm\node_modules\sails\bin\sails.js
C:\Users\Administrator\AppData\Roaming\npm
`-- sails@0.12.11

**Comment by KenanY** [comment]
I do not see any errors in the output you've provided.

**Comment by Muthukumars1994** [comment]
Hi kenan y i have installed sails in c directory but i cant see the listed folder below in my pc 
why it throws erro while installing in E directory all my node setup was present in e directory

C:\Users\Administrator\AppData\Roaming\npm\node_modul
es.staging\sails-fa618c93

**Comment by KenanY** [comment]
That's just a temporary staging folder I believe. It's not intended to exist post-installation.

**Comment by Muthukumars1994** [comment]
@kenan y Yeah installation was completed succesfully but how could i open the below directory it is not possible i have tried
C:\Users\Administrator\**AppDa
ta\Roaming\npm\node_modules\sails\bin\sails.js**

I have done this in windows 7  i cant find the folder

**Comment by KenanY** [comment]
@Muthukumars1994 Not sure to be honest. I'm gonna close this though since `npm` is not at fault here as far as I can tell.
