### ISSUE TITLE
fatal: Unable to find remote helper for 'git+https' macOS

### ISSUE THREAD

**Issue by abmartinr** [npm/npm#15642]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [X] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I'm trying to load some private Github repositories as `git+https://${GITHUB_TOKEN}:x-oauth-basic@github.com-----` but I am getting the error `fatal: Unable to find remote helper for 'git+https'`.  Locally if I use ssh authentication instead of git+https I can install the package correctly. As soon as I change it to the above, it fails.

Thank you! 

#### How can the CLI team reproduce the problem?

This is the gist for the npm-debug.log: https://gist.github.com/abmartinr/1701023f22a2c712c53aa312af05beff

### supporting information:

 - `npm -v` prints: 4.1.2
 - `node -v` prints: v6.6.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: OS X/macOS
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [X] I access the npm registry via a VPN (Happens with and without VPN)
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by abmartinr** [comment]
I've been trying further today, I don't know why but I can access the ENV variables perfectly in the scripts within package.json but when I try on the URL of a dependency it becomes plain text and it's not being replaced by the env variable.

```
Command failed: git clone --template=/Users/username/.npm/_git-remotes/_templates --mirror git+https://${GITHUB_TOKEN}:x-oauth-basic@github.com/org/repo.git /Users/username/.npm/_git-remotes/git-https-GITHUB-TOKEN-x-oauth-basic-github-com-org-repo-git-5c0e1c80
```

**Comment by newhouse** [comment]
Wait, @abmartinr can you provide any insight into how you resolved this? I'm having the same issues trying to do the same thing...

**Comment by abmartinr** [comment]
Hey @newhouse, I ended up moving torwards ssh instead since I couldn't make this work. Sorry :/

**Comment by newhouse** [comment]
Ok, thanks @abmartinr . Thanks for the reply. For future desperate searchers:
I also, disappointingly, exhausted getting environment variable substitution to work on the NPM `dependencies` area, with no luck. It seems that you can use environment variables as part of the `scripts` area, but not with `dependencies`...or at least not with `git+https` ones. I ended up going the SSH generation solution in [this SO post](http://stackoverflow.com/questions/10869796/npm-private-git-module-on-heroku).

**Comment by duxing** [comment]
late to the party but here's my solution:
 - modify `script` in package.json with custom `preinstall` and `postinstall`
 - run a in-place replacement in those hooks

```
"scripts": {
    "preinstall": "./preinstall.sh",
    "postinstall": "./postinstall.sh"
},
```

where `preinstall.sh` looks like:
```
#!/usr/bin/env bash

if [ "$(uname)" == "Darwin" ]; then
  sed -i '' 's@\${GITHUB_TOKEN}@'"${GITHUB_TOKEN}"'@g' package.json
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
  sed -i 's@\${GITHUB_TOKEN}@'"${GITHUB_TOKEN}"'@g' package.json
fi
```

the caveats:
 - if you have nested packages with github access, you need to do this for every repo
