### ISSUE TITLE
package json is missing

### ISSUE THREAD

**Issue by udhaya81** [npm/npm#15651]
#### I'm opening this issue because:

  
  - [ ] npm is producing an incorrect install.
  

#### What's going wrong?

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/node/7.5.0/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! path /Users/fundsindia/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/Users/fundsindia/package.json'

**Comment by KenanY** [comment]
@udhaya81 Make sure that you have a `package.json` in your current working directory, with a `"start"` script defined within it, before running `npm start`.
