### ISSUE TITLE
Can not install "$ npm install fluent-ffmpeg"

### ISSUE THREAD

**Issue by Nikmike** [npm/npm#15652]
#### I'm opening this issue because:

  - [ ] npm is doing something I don't understand.
  - [ ] Other ( npm is not installing fluent-ffmpeg ):

#### What's going wrong?

whenever I try to install "Fluent-ffmpeg" via NPM ( using Windows 10 64bit machine). it gives me following list of errors.

#### How can the CLI team reproduce the problem?
**How can you reproduce**
copy "node-v6.9.5-x64.msi" setup on desktop.
install it .
open command prompt from installed directory 
run following command
C:\Users\GORDEN\Desktop\FFMPEG_POC\node_modules\fluent-ffmpeg>npm install fluent-ffmpeg

"C:\Users\GORDEN\Desktop\FFMPEG_POC\node_modules\fluent-ffmpeg" is the path where "Fluent-ffmpeg" folder present
"npm install fluent-ffmpeg" - it is the command to install Fluent-ffmpeg

open command 

[logfile.txt](https://github.com/npm/npm/files/747751/logfile.txt)

### supporting information:
**Error trace**: 

C:\Users\GORDEN\Desktop\FFMPEG_POC\node_modules\fluent-ffmpeg>npm install fluent-ffmpeg
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "fluent-ffmpeg"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ENOSELF

npm ERR! Refusing to install fluent-ffmpeg as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\GORDEN\Desktop\FFMPEG_POC\node_modules\fluent-ffmpeg\npm-debug.log

 - Windows : windows 10 64 bit
 - Network issues:
   - Geographic location where npm was run: India
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.

**Comment by KenanY** [comment]
@Nikmike No need to run `npm install fluent-ffmpeg` a second time. It's already installed at `C:\Users\GORDEN\Desktop\FFMPEG_POC\node_modules\fluent-ffmpeg`.
