### ISSUE TITLE
Error on: build to publish on ftp

### ISSUE THREAD

**Issue by mestrebinario** [npm/npm#15658]
Wagna@DESKxxx
$ npm run build
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Wagna\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v4.6.0
npm ERR! npm  v3.10.8

npm ERR! missing script: build
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\xampp\htdocs\Workspace\mn-project\npm-debug.log

NOTE: The project was set up with yeoman

**Comment by KenanY** [comment]
@mestrebinario Make sure you have a `"build"` script defined in your `package.json` _before_ running `npm run build`.
