### ISSUE TITLE
Node.js Problem Path package.json

### ISSUE THREAD

**Issue by kiolim2108** [npm/npm#15656]
Hello world,

I've got a big problem,
This is the npm-debug file,

0 info it worked if it ends with ok
1 verbose cli [ 'D:\\nodejs\\node.exe',
1 verbose cli   'D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.10
3 info using node@v6.9.5
4 verbose config Skipping project config: C:\Users\rickl/.npmrc. (matches userconfig)
5 verbose stack Error: ENOENT: no such file or directory, open 'C:\Users\rickl\package.json'
5 verbose stack     at Error (native)
6 verbose cwd C:\Users\rickl\Desktop\site recup bdd node.js
7 error Windows_NT 10.0.14393
8 error argv "D:\\nodejs\\node.exe" "D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
9 error node v6.9.5
10 error npm  v3.10.10
11 error path C:\Users\rickl\package.json
12 error code ENOENT
13 error errno -4058
14 error syscall open
15 error enoent ENOENT: no such file or directory, open 'C:\Users\rickl\package.json'
16 error enoent ENOENT: no such file or directory, open 'C:\Users\rickl\package.json'
16 error enoent This is most likely not a problem with npm itself
16 error enoent and is related to npm not being able to find a file.
17 verbose exit [ -4058, true ]

![nodejs_problem_packagejson](https://cloud.githubusercontent.com/assets/25514467/22565767/95a31aec-e989-11e6-86e3-83db5846eb92.JPG)

Please help me

**Comment by KenanY** [comment]
@kiolim2108 Make sure you have a `package.json` in your current directory with a `"start"` script defined within it before running `npm start`.
