### ISSUE TITLE
unable to install cli using npm install -g angular2-cli 

### ISSUE THREAD

**Issue by tahanialharbi** [npm/npm#15655]
I keep getting this error when i try to install angular2 cli using this command in my mac :
 npm install -g angular2-cli 
--- 
the message I'm getting is this : 
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "angular2-cli"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! path /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!     at Error (native)
npm ERR!  { Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!     at Error (native)
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/usernam/npm-debug.log
--- 
I'm running as a root but that doesn't help as well.

**Comment by KenanY** [comment]
What's the error when you run it as root?

**Comment by tahanialharbi** [comment]
Same error

**Comment by KenanY** [comment]
@tahanialharbi Well, you don't seem to have permission to access `/usr/local/`, hence the errors you are seeing. You should probably change your global modules directory to one which you actually have permissions. <https://docs.npmjs.com/getting-started/fixing-npm-permissions> should help.
