### ISSUE TITLE
What happened to 4.2.0?

### ISSUE THREAD

**Issue by henderea** [npm/npm#15668]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?
If I run `npm install -g npm`, it installs 4.1.2, and the website lists 4.1.2 as the latest version.  But if I run `npm install -g npm@4.2.0`, it installs 4.2.0.  I actually had 4.2.0 already installed and running the command to update npm without specifying the version downgraded me to 4.1.2.

#### How can the CLI team reproduce the problem?

Run `npm install -g npm` and see what version it installs.  Also, look on the npmjs.org page for npm.

### supporting information:

 - `npm -v` prints: 4.2.0 or 4.1.2 depending on if my most recent npm install npm command specified the version to install
 - `node -v` prints: v7.5.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS El Capitan 10.11.6
 - Network issues:
   - Geographic location where npm was run: Indianapolis, Indiana, USA
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
`npm@4.1.2` is what is tagged as `latest`, hence why it's installed by default and why the website says it is the `latest`. `npm@4.2.0` is tagged as `next` (a.k.a., it's a beta/pre-release).
