### ISSUE TITLE
Protractor won't install

### ISSUE THREAD

**Issue by kramie13** [npm/npm#15664]
I'm trying to install Protractor via npm, but I keep getting a "400 Bad Request" error.  Other node modules like Mocha and Karma are successfully installing, but not Protractor.

```
npm install -g protractor
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "protractor"
npm ERR! node v6.9.5
npm ERR! npm  v4.1.2
npm ERR! code E400

npm ERR! 400 Bad Request
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/npm-debug.log
```

Attached is my [npm-debug.log](https://gist.github.com/kramie13/08c64d20b87bd04b3fb6e5fb0fbf08ba)

**Comment by KenanY** [comment]
@kramie13 Looks like that error is coming from your Artifactory registry, no?

**Comment by kramie13** [comment]
Hi KenanY,

The error was coming from my Artifactory registry.  I reset my npm registry to https://registry.npmjs.org, and that solved the problem.
