### ISSUE TITLE
Suggestion - npm run should search ancestor directories, like require('foo')

### ISSUE THREAD

**Issue by danielearwicker** [npm/npm#15661]
#### What's the feature?
I'm using npm/node as my JS "build system" within a broader multi-language project. I have little islands of JS (sanity!) at various places in a big source tree.

Near the root of this tree I can create a `node_modules` folder where I put shared code in small packages. This instantly makes these packages available to all the nested JS projects (no need to install them or otherwise copy them locally). So if I have:

    root/node_modules/useful-thing

I can then edit:

    root/blah/something/niche/index.js

to say `require("useful-thing")`, and it works. Or at least, I find `webpack` resolves `useful-thing` and includes it in `niche`'s bundle.

But at the terminal in `niche` if I say:

    npm run build

Then in `niche`'s `package.json` I've defined the `build` script to run some tool exposed by `useful-thing`, this is not found.

The environment for `package.json` includes the *local* `node_modules/*/bin` folders, and the global ones, but not those on the chain of ancestor directories, making it a bit less convenient than the `require` behaviour.

#### What problem is the feature intended to solve?

Sharing packages within a combined tree of projects, none of them published on npm registry.

#### Is the absence of this feature blocking you or your team? If so, how?

No, it just means a bunch of fooling around with very long brittle paths in config files.

#### Is this feature similar to an existing feature in another tool?

Yes, it's analogous to the behaviour of `require`, searching up the ancestor directory chain.

#### Is this a feature you're prepared to implement, with support from the npm CLI team?

Yes!

**Comment by MegaArman** [comment]
This would be awesome! Please do it npm team!
