### ISSUE TITLE
`npm prune --production` deletes dependencies found in both `dependencies` and `devDependencies`

### ISSUE THREAD

**Issue by eschwartz** [npm/npm#15669]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [X] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Situation
- You have the same dependency listed in your `package.json`'s `dependencies` and `devDependencies`
- You install your dependencies
- You run `npm prune --production` using npm **v4.1.2**

What actually happens:
- The dependency is deleted from your `node_modules` folder

What I expect to happen:
- The dependency should _not_ be deleted, as it is a production dependency.

Note the using npm v4.05 results in expected behavior. 

#### How can the CLI team reproduce the problem?

Create a `package.json` file like so:

```
{
  "devDependencies": {
    "mongodb": "^2.2.21"
  },
  "dependencies": {
    "mongodb": "^2.2.21"
  }
}
```

Using npm v4.1.2 run:

```
$ npm install
$ npm prune --production
```

### supporting information:

 - `npm -v` prints: 4.1.2
 - `node -v` prints: v4.3.2, also tried with v6.9.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [x] I develop / deploy using Docker. 
     I tried this on my Ubuntu 16.04 machine, and also [in a container running Linux](https://github.com/lambci/docker-lambda/blob/master/nodejs4.3/build/Dockerfile)
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by doug-wade** [comment]
I... why do you have mongo listed as both a devDependency and a regular dependency?  Why not remove it from your devDeps?

**Comment by eschwartz** [comment]
> why do you have mongo listed as both a devDependency and a regular dependency

It's a developer mistake.

But it should not result in production dependencies getting removed by `npm prune`. If we're going to call a duplicate dependency listing invalid, then `npm prune` should fail with a relevant validation error, rather than succeed with unexpected behavior.

Why was this issue closed? It's clearly a bug, and it's easily reproducible.

**Comment by KenanY** [comment]
@eschwartz This issue has not been closed AFAICT.

**Comment by eschwartz** [comment]
@KenanY -- sorry, I was looking in the wrong place. Haven't finished my morning coffee yet...

**Comment by exogen** [comment]
`npm prune --production` seems to be broken in npm 4.1.x in general. If a package has only `devDependencies` npm 4.0.x and lower will have an empty `node_modules` after `npm prune --production`, but npm 4.1.x keeps the dev packages around.

**Comment by nkbt** [comment]
Same prod dependency can be required by as one of dev - sub-sub dependency. Not necessarily specified in both lists.

I also found this funky effect. Every time I run it - installs or uninstalls deps.

```sh
16:25 $ npm prune --production
- object-assign@4.1.1 node_modules/query-string/node_modules/object-assign
- bytes@2.4.0 node_modules/raw-body/node_modules/bytes
- raw-body@2.2.0 node_modules/raw-body
- strict-uri-encode@1.1.0 node_modules/strict-uri-encode
- query-string@4.3.1 node_modules/query-string
- warning@3.0.0 node_modules/warning
- history@3.2.1 node_modules/history

16:25 $ npm prune --production
atlas-ui@0.0.0 .
├── history@3.2.1 
├─┬ query-string@4.3.1 
│ └── object-assign@4.1.1 
├─┬ raw-body@2.2.0 
│ └── bytes@2.4.0 
├── strict-uri-encode@1.1.0 
└── warning@3.0.0 

16:25 $ npm prune --production
- object-assign@4.1.1 node_modules/query-string/node_modules/object-assign
- bytes@2.4.0 node_modules/raw-body/node_modules/bytes
- raw-body@2.2.0 node_modules/raw-body
- strict-uri-encode@1.1.0 node_modules/strict-uri-encode
- query-string@4.3.1 node_modules/query-string
- warning@3.0.0 node_modules/warning
- history@3.2.1 node_modules/history

16:25 $ npm prune --production
atlas-ui@0.0.0 .
├── history@3.2.1 
├─┬ query-string@4.3.1 
│ └── object-assign@4.1.1 
├─┬ raw-body@2.2.0 
│ └── bytes@2.4.0 
├── strict-uri-encode@1.1.0 
└── warning@3.0.0 

16:25 $ 
```

**Comment by nkbt** [comment]
I assume that change comes somewhere from https://github.com/npm/npm/pull/15090

**Comment by nkbt** [comment]
Temporary fix for our build scripts:

```sh
npm prune --production
npm prune
```

Apparently no matter how many times we call `npm prune` after that - it is always consistent and does not change anything. So adding it after `npm prune --production` is a way to safely add back missing deps.

**Comment by nkbt** [comment]
So far the best solution was

```sh
docker run -v $(pwd):/app -w /app -it mhart/alpine-node:7.4.0 npm prune --production
```

In case anyone wanted "old good npm prune" working and uses docker

**Comment by JamesMGreene** [comment]
Also suffering from this on `npm@4.3.0`.

**Comment by benstevens48** [comment]
I also just ran into this problem - it's very easy to end up with dependencies in both dependencies and devDependencies for example if you just need a package for dev and then later on need it production so you install it first with --save dev and then again with --save.

This effect of running npm prune --production is then to crash the server after it's restarted, which is not good! In my opinion it should be high priority to change this behaviour.
