### ISSUE TITLE
.gitignore renamed to .npmignore

### ISSUE THREAD

**Issue by nfroidure** [npm/npm#15660]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

An NPM module i published is contains a `.npmignore` file instead of a `.gitignore` one in its sub directories.

The module is `metapak-nfroidure@0.0.6`. It contains this directory [`src/_common/assets`](https://github.com/nfroidure/metapak-nfroidure/tree/master/src/_common/assets) that contains a  [`.gitignore`](https://github.com/nfroidure/metapak-nfroidure/blob/master/src/_common/assets/.gitignore) file.

But when installing this module, the `.gitignore` file gets renamed to `.npmignore` with the exact same content.

I tried an `npm cache clean` with no luck.

#### How can the CLI team reproduce the problem?
```
➜  test2 npm init -y
Wrote to /home/nfroidure/projects/test2/package.json:

{
  "name": "test2",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}


➜  test2 npm i --save-dev metapak-nfroidure@0.0.6

> metapak-nfroidure@0.0.6 postinstall /home/nfroidure/projects/test2/node_modules/metapak-nfroidure
> metapak; metapak || echo 'Please `npm install --save-dev metapak`' exit 0

sh: 1: metapak: not found
sh: 1: metapak: not found
Please `npm install --save-dev metapak` exit 0
test2@1.0.0 /home/nfroidure/projects/test2
└─┬ metapak-nfroidure@0.0.6 
  └─┬ debug@1.0.0 
    └── ms@0.6.2 

npm WARN test2@1.0.0 No description
npm WARN test2@1.0.0 No repository field.
➜  test2 ls -la node_modules/metapak-nfroidure/src/_common/assets/        
total 24
drwxrwxr-x 2 nfroidure nfroidure 4096 févr.  3 09:32 .
drwxrwxr-x 3 nfroidure nfroidure 4096 févr.  3 09:32 ..
-rw-rw-r-- 1 nfroidure nfroidure   70 janv. 31 09:33 .codeclimate.yml
-rw-rw-r-- 1 nfroidure nfroidure  207 févr.  1 08:24 .eslintrc
-rw-rw-r-- 1 nfroidure nfroidure 1092 janv. 29 20:45 LICENSE
-rw-rw-r-- 1 nfroidure nfroidure  578 févr.  1 08:20 .npmignore
➜  test2 

```
### supporting information:

 - `npm -v` prints:
```
➜  test2 npm -v
3.10.8
```
 - `node -v` prints:
```
➜  test2 node -v
v6.9.1

```
 - `npm config get registry` prints:
```
➜  test2 npm config get registry
https://registry.npmjs.org/
```
 - Windows, OS X/macOS, or Linux?:
```
➜  test2 uname -a
Linux 13 4.4.0-59-generic #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

```
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
Seems intentional: <https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package>:

> If there's no `.npmignore` file, but there is a `.gitignore` file, then `npm` will ignore the stuff matched by the `.gitignore` file.

**Comment by nfroidure** [comment]
@KenanY looks like your are right ;). Pretty unexpected behavior though, i'll figure out how to deal with this. Thanks.
