### ISSUE TITLE
I cannot run ionic project

### ISSUE THREAD

**Issue by raresdolga** [npm/npm#15677]
#### I'm opening this issue because:

 I npm install is crashing
#### What's going wrong?
 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose readDependencies loading dependencies from D:\Users\Rares\Documents\AppProject\AppComplete\package.json
5 error install Couldn't read dependencies
6 verbose stack Error: ENOENT, open 'D:\Users\Rares\Documents\AppProject\AppComplete\package.json'
6 verbose stack     at Error (native)
7 verbose cwd D:\Users\Rares\Documents\AppProject\AppComplete
8 error Windows_NT 6.3.9600
9 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
10 error node v0.12.7
11 error npm  v2.11.3
12 error path D:\Users\Rares\Documents\AppProject\AppComplete\package.json
13 error code ENOPACKAGEJSON
14 error errno -4058
15 error package.json ENOENT, open 'D:\Users\Rares\Documents\AppProject\AppComplete\package.json'
15 error package.json This is most likely not a problem with npm itself.
15 error package.json npm can't find a package.json file in your current directory.
16 verbose exit [ -4058, true ]

**Comment by KenanY** [comment]
@raresdolga Make sure you have a `package.json` in your current directory before running `npm install` with no arguments.

**Comment by raresdolga** [comment]
I have one

**Comment by raresdolga** [comment]
If I try to install some plugins I receive error again :
cordova plugin add cordova-plugin-geolocation
Error:  cmd: Command failed with exit code ENOENT

**Comment by KenanY** [comment]
@raresdolga 

> I have one

So `D:\Users\Rares\Documents\AppProject\AppComplete\package.json` exists?

> If I try to install some plugins I receive error again :

That error is not coming from `npm`.

**Comment by raresdolga** [comment]
The package.json exist
I receive this error as well
EXDEV: cross-device link not permitted, rename 'D:\Users\Rares\Documents\AppProject\AppComplete\oldCode\node_modules\ionic\node_modules\ionic-app-lib\node_modules\glob-watcher\node_modules\chokidar\node_modules\fsevents\node_modules\wrappy' -> 'D:\Users\Rares\Documents\AppProject\AppComplete\oldCode\node_modules\gulp-sass\node_modules\wrappy'

When I looked for "wrappy" I could not find it

**Comment by raresdolga** [comment]
This is a project that I have to work on, If i start one from scratch npm install is working and I can run ionic serve. So I believe that it is a problem in the project.  For this project if I try running ionic serve I receive:
Uh oh! Looks like you're missing a module in your gulpfile:
Cannot find module 'orchestrator'

Do you need to run `npm install`?
