### ISSUE TITLE
README.md ignored

### ISSUE THREAD

**Issue by GarthDB** [npm/npm#15671]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

The `README.md` file for the [atomdoc-cli](https://www.npmjs.com/package/atomdoc-cli) package is present in the [github repo](https://github.com/GarthDB/atomdoc-cli) but is not being published to npm.

#### How can the CLI team reproduce the problem?

I'm not sure, I haven't been able to determine the cause locally.

### supporting information:

 - `npm -v` prints: 3.9.5
 - `node -v` prints: v6.2.2
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by doug-wade** [comment]
@GarthDB I'm pretty sure you're ignoring README.md in your [`.npmignore`](https://github.com/GarthDB/atomdoc-cli/blob/master/.npmignore#L3)

**Comment by GarthDB** [comment]
@doug-wade I'm not seeing the offending line https://github.com/GarthDB/atomdoc-cli/blob/master/.npmignore

Also the [documentation](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package) says it should never be ignored:

The following paths and files are never ignored, so adding them to .npmignore is pointless:

* package.json
* README (and its variants)
* CHANGELOG (and its variants)
* LICENSE / LICENCE

**Comment by GarthDB** [comment]
@doug-wade I took out the `.*` line and explicitly added each dot file and that seemed to have fixed it - but it still weird that it still ignores it otherwise.
