### ISSUE TITLE
npm should use Local AppData not Roaming AppData for globally installed modules

### ISSUE THREAD

**Issue by Daniel15** [npm/npm#15675]
Windows has two different types of AppData directories:
- `%APPDATA%` (eg. `C:\Users\Daniel\AppData\Roaming\`) - Contains user settings. In a corporate/domain environment, this can be configured to be synchronised across computers, so it should generally only hold things you'd actually need to keep in sync. Settings/config is a good example.
- `%LOCALAPPDATA%` (eg. `C:\Users\Daniel\AppData\Local\`) - Contains other random junk. It's like AppData except for stuff that wouldn't need to be kept in sync across machines. Per-user temporary files and local caches fall into this category.

npm places globally installed modules in the roaming directory, but it should really use the local one.

**Comment by KenanY** [comment]
See https://github.com/npm/npm/issues/4564
