### ISSUE TITLE
npm did not start

### ISSUE THREAD

**Issue by udhaya81** [npm/npm#15673]
#### I'm opening this issue because:

 
  - [x] npm is producing an incorrect install.
 
sh: ng: command not found

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/node/7.5.0/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! ng2-bootstrap-base@1.3.1 start: `ng serve --aot`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the ng2-bootstrap-base@1.3.1 start script 'ng serve --aot'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ng2-bootstrap-base package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ng serve --aot
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ng2-bootstrap-base
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ng2-bootstrap-base
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/fundsindia/angular2/npm-debug.log

**Comment by udhaya81** [comment]
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/node/7.5.0/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v7.5.0
npm ERR! npm v4.1.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! ng2-bootstrap-base@1.3.1 start: ng serve --aot
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the ng2-bootstrap-base@1.3.1 start script 'ng serve --aot'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ng2-bootstrap-base package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! ng serve --aot
npm ERR! You can get information on how to open an issue for this project with:
npm ERR! npm bugs ng2-bootstrap-base
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! npm owner ls ng2-bootstrap-base
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR! /Users/fundsindia/angular2/npm-debug.log

**Comment by KenanY** [comment]
@udhaya81 Make sure you have [`angular-cli`](https://github.com/angular/angular-cli#installation) installed. Closing since this is not an issue with `npm` itself.
