### ISSUE TITLE
Fetch and extract information from .m3u file

### ISSUE THREAD

**Issue by WassimBhm** [npm/npm#15676]
I am try to parse an .m3u file fetch it and extract from it in formation in JavaScript. any suggestions how to parse this format:
`#EXTM3U
         #EXTINF:-1,-------ARABIC------ 
          http://mysserver.xyz:8000/live/khoolood/88888/000.ts
         #EXTINF:-1,AR-Tunisia-NAT_1
         http://mysserver.xyz:8000/live/khoolood/88888/000.ts
         #EXTINF:-1,AR-Tunisia-NAT_2
         http://mysserver.xyz:8000/live/khoolood/88888/000.ts`

**Comment by KenanY** [comment]
This issue tracker is for bugs/feature-requests in `npm`, not for general programming questions. Try taking your question to, say, StackOverflow instead.
