### ISSUE TITLE
 tarball.destroy is not a function

### ISSUE THREAD

**Issue by PhalugunaRao** [npm/npm#15674]
```
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\RAVITE~1\AppData\Local\Temp\npm-10068-9fcd8e72\registry.npmjs.org\babel-helper-hoist-variables\-\babel-helper-hoist-variables-6.22.0.tgz.904325312' -> 'C:\Users\RAVITE~1\AppData\Local\Temp\npm-10068-9fcd8e72\registry.npmjs.org\babel-helper-hoist-variables\-\babel-helper-hoist-variables-6.22.0.tgz'
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "--save-exact" "react-native"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\RAVITE~1\AppData\Local\Temp\npm-10068-9fcd8e72\registry.npmjs.org\babel-helper-hoist-variables\-\babel-helper-hoist-variables-6.22.0.tgz.2514681896' -> 'C:\Users\RAVITE~1\AppData\Local\Temp\npm-10068-9fcd8e72\registry.npmjs.org\babel-helper-hoist-variables\-\babel-helper-hoist-variables-6.22.0.tgz'
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "--save-exact" "react-native"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by tommck** [comment]
maybe related? https://stackoverflow.com/questions/36835882/npm-err-tarball-destroy-is-not-a-function
