### ISSUE TITLE
LXC Container & NPM -v : Fail

### ISSUE THREAD

**Issue by dotju** [npm/npm#15681]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [X] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I've started using containers and building a node environment. 
I'm using privileged containers and simply using lxc-attach to connect to the containers.

- Ubuntu 16.04 (LTS) as the Host
- Ubuntu 16.04 (LTS) as the LXC Container (lxc-create -t ubuntu -n xxx)
- NodeJS : Node v6.9.5 & NPM v ?

I don't get any output when run "npm -v", the same goes for any other npm options. 
Node -v is fine (see below).

Is someone experiencing a similar issue or has been able to find the cause of this ?

Thx for your help !

```
root@cont1:/# node -v
v6.9.5
root@cont1:/# npm -v
root@cont1:/#
-----------
root@cont1:~# which npm
/usr/bin/npm
root@cont1:~# which node
/usr/bin/node
root@cont1:~# which nodejs
/usr/bin/nodejs

```
#### How can the CLI team reproduce the problem?

- Install LXC :  sudo apt-get install lxc
- Create an Ubuntu Container 16.04 -> sudo  lxc-create -t ubuntu -n xxx 
- sudo lxc-start -n xxxxx
- sudo lxc-attach -n xxxx

Run the following script inside the container 
```
######Download and install Node######
apt-get -y update
apt-get -y upgrade
apt-get install -y curl build-essential libssl-dev
curl -sL https://deb.nodesource.com/setup_6.x | bash -
apt-get install -y nodejs
```

### supporting information:

 - `npm -v` prints: ?
 - `node -v` prints: v6.9.5
 - `npm config get registry` prints: ?
 - Windows, OS X/macOS, or Linux?: Linux Ubuntu
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by beenje** [comment]
I have the exact same problem after installing nodejs inside a Debian jessie LXC container.
I found this issue on [stackoverflow](http://stackoverflow.com/questions/40755598/containers-lxc-attach-and-npm-no-output).

I opened a new terminal, attached to my container and this time, npm worked!
Very strange. This seems to be a workaround at least.

**Comment by dotju** [comment]
Hi @beenje 

It's not user friendly but this workaround works for me too ! Thx
I've trouble to find root cause, really strange...
```
root@cont2:/# npm -v
3.10.10
```

**Comment by boden** [comment]
I can confirm the issue of npm not giving any response on Ubuntu 16.04 running both as host and in the container. 

This happens both using the node & npm versions from the repositories as well as the latest LTS binaries from the nodejs website (for the repos versions this happened after attempting to upgrade nodejs). 

Attaching from a second terminal temporatily resolves the issue as mentioned by the comments above, strangely.

**Comment by mukimov** [comment]
Issue present on Archlinux LXC.

Actually it works with `lxc-console` as expected. But not with `lxc-attach`. I think output goes to wrong tty, probably into tty0. `node` interactive console is not working as well with `lxc-attach`, but ok with `lxc-console`.

**Comment by juzim** [comment]
@beenje FYI, the post you linked had been removed. Please add the solution to your reply next time.

**Comment by shadowofsoul** [comment]
I can confirm that this is still happening on 3.0 version of LXC, tested on debian & ubuntu flavors. 

It would be nice some kind of warning (not sure if NPM can do it, probably must be done by LXC) , i spent HOURS trying to figure out why node would just hang and npm would return nothing .

and not even with sudo works btw, so is even more confusing.
