### ISSUE TITLE
Yarn symlink error - "EPROTO: protocol error, symlink '../../../babylon/bin/babylon.js' -> '/var/www/yokocms/node_modules/babel-core/node_modules/.bin/babylon'"

### ISSUE THREAD

**Issue by samfullman** [npm/npm#15690]
#### I'm opening this issue because:

  - [x ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Firstly I am not sure this is the place to submit this, other than it may be related to NPM even though the command I'm using is "yarn"; as a error of the same type and format appears for help here.

I am getting the following error:
{code}
    root@vagrant-ubuntu-trusty-64:/var/www/mycms# yarn
    yarn install v0.19.1
    warning MyCMS@0.0.1: No license field
    warning MyCMS@0.0.1: "dependencies" has dependency "babel-polyfill" with range "^6.16.0" that collides with a dependency in "devDependencies" of the same name with version "^6.7.4"
warning MyCMS@0.0.1: "dependencies" has dependency "babel-preset-es2015" with range "^6.18.0" that collides with a dependency in "devDependencies" of the same name with version "^6.6.0"
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
error An unexpected error occurred: "EPROTO: protocol error, symlink '../../../babylon/bin/babylon.js' -> '/var/www/mycms/node_modules/babel-core/node_modules/.bin/babylon'".
info If you think this is a bug, please open a bug report with the information provided in "/var/www/mycms/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
root@vagrant-ubuntu-trusty-64:/var/www/mycms#
{code}

#### How can the CLI team reproduce the problem?
Not sure, I have a Ubuntu 14.x box, with npm, node etc. installed.  Node is like version 4.x

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by shuttle1987** [comment]
This is not a node/npm/yarn problem but rather is caused by symlinks not being supported by Vagrant when run with Virtualbox in windows. npm assumes that symlinks can be created which is not the case here. You need to run Vagrant as administrator and you may need to modify symlink settings.
