### ISSUE TITLE
install @slack/client fails

### ISSUE THREAD

**Issue by henti** [npm/npm#15697]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
installing @slack/client fails with 
npm ERR! git clone git@github.com:slack/client undefined

#### How can the CLI team reproduce the problem?

Clean Debian Jessie. 

apt-get install npm
npm install @slack/client

https://gist.github.com/henti/65fe94efed7482caca37007e091fbe1e

### supporting information:

 - `npm -v` prints:
1.4.21
 - `node -v` prints:
v0.10.29
 - `npm config get registry` prints:
https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?:
Debian Jessie
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@henti Does this also occur with the latest stable release of `npm`? `npm@1` is quite old now.

**Comment by henti** [comment]
I'll have to test this on a dev Debian. this is on stock Jessie, which is current stable, so still expected to work.

**Comment by henti** [comment]
debian testing (stretch) has the same version of npm. 

https://packages.debian.org/stretch/npm

If this is outdated, I recommend somebody contact Debian to update the version in the repo.

**Comment by KenanY** [comment]
@henti Yeah that's outdated. Feel free to contact them to get that updated. In the mean time, you can [update `npm` using `npm` itself](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-nix-osx-linux-etc).

**Comment by sholladay** [comment]
I doubt anyone has tried to update directly from `npm` `1` to `4`.

To play it safe, I would do something like this:

```sh
npm i -g npm@2 && npm i -g npm@3 && npm i -g npm@4
```

**Comment by henti** [comment]
Thank you all, I upgraded to latest npm@lts and everything is working fine now, thank you all.
