### ISSUE TITLE
var FfmpegCommand = require('fluent-ffmpeg'); gives error

### ISSUE THREAD

**Issue by Nikmike** [npm/npm#15698]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
whenever try to run below code using JS file from command prompt it gives following error.

C:\Users\GORDEN\Desktop>npm ffmpeg.js

Usage: npm <command>

where <command> is one of:
    access, adduser, bin, bugs, c, cache, completion, config,
    ddp, dedupe, deprecate, dist-tag, docs, edit, explore, get,
    help, help-search, i, init, install, install-test, it, link,
    list, ln, login, logout, ls, outdated, owner, pack, ping,
    prefix, prune, publish, rb, rebuild, repo, restart, root,
    run, run-script, s, se, search, set, shrinkwrap, star,
    stars, start, stop, t, tag, team, test, tst, un, uninstall,
    unpublish, unstar, up, update, v, version, view, whoami

npm <cmd> -h     quick help on <cmd>
npm -l           display full usage info
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    C:\Users\GORDEN\.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@3.10.10 C:\Program Files\nodejs\node_modules\npm

#### How can the CLI team reproduce the problem?

1> rename attached file to ffmpeg.js
2> copy to Desktop
3> run from Node.js command promt

[New Text Document.txt](https://github.com/npm/npm/files/757444/New.Text.Document.txt)

### supporting information:

 - Windows, : windows 10 (64 bit)

**Comment by KenanY** [comment]
There are no errors in the output you've posted.
