### ISSUE TITLE
npm install Could not read from remote repository / No such file or directory

### ISSUE THREAD

**Issue by Jmales** [npm/npm#15699]
#### I'm opening this issue because:

  - [ x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

I've installed `electron-window-manager` on a Windows 7 PC without a problem. Now, in my Windows 10 the `npm install --save electron-window-manager` crashes complaining about cloning from `https://github.com/melanke/Watch.JS.git` (`electron-window-manager` uses `WatchJS`) and after many hours I still haven't found a solution to the problem.

My [npm-debug.log](https://github.com/npm/npm/files/757785/npm-debug.txt).

I've tried:
-Running the command window in administrator mode.
-Deleting npm and npm-cache folders in AppData\Roaming and doing `npm install -g npm` after.
-Installing the latest stable version of Node v6.9.5 (which includes npm 3.10.10).

Please help! So many hours wasted already -_-

**Edit1**: After all, every module installed via git fails.

E.g. git+https://git@github.com/visionmedia/express.git fails with the same error.

**Comment by Jmales** [comment]
After all, every module installed via git fails. 

E.g. `git+https://git@github.com/visionmedia/express.git` fails with the same error.

**Comment by Jmales** [comment]
No solutions guys? Is still haven't solved this...

**Comment by OliverMarcetic** [comment]
What solved it for me was setting up Git using Git CMD with these two lines:
```
git config --global user.name "Your Username"
git config --global user.email "Your Email"
```

**Comment by Jmales** [comment]
@OliverMarcetic Ty for the answer. That does not solve my problem though..

**Comment by Jmales** [comment]
No solutions to this? I can't work with npm without solving this...

**Comment by legodude17** [comment]
@Jmales do you have a proxy or a VPN? Can you access https://github.com/melanke/Watch.JS in the browser?

**Comment by Jmales** [comment]
@legodude17 I don't use proxy or VPN and yes, I can access the repository.

**Comment by legodude17** [comment]
Does @mmurukutla's solution from #14408 help you?

**Comment by Jmales** [comment]
I don't quite understand his solution: "We were trying with Personal Access Token on the machine where Git is already configured. We removed the token from URL and it started working."

**Comment by legodude17** [comment]
If you don't understand it, it probably doesn't apply to you. It seems like he meant that git was configured, then they also tried a different auth mechanism for `npm`. For you, what is the result of `npm config ls`?

**Comment by Jmales** [comment]
`; cli configs
scope = ""
user-agent = "npm/4.1.2 node/v7.5.0 win32 x64"

; builtin config undefined
prefix = "C:\\Users\\MYUSER\\AppData\\Roaming\\npm"

; node bin location = C:\Program Files\nodejs\node.exe
; cwd = E:\Programming\Electron\MUVTIME_Electron
; HOME = C:\Users\MYUSER
; "npm config ls -l" to show all defaults.

`

**Comment by legodude17** [comment]
Try running `npm i melanke/Watch.JS` and post the output.

**Comment by Jmales** [comment]
It says the same thing as `npm install` (because `npm install` breaks at this module, since it requires git which is failing in every module when it needs to be downloaded from an online repo).

**Comment by jonathanong** [comment]
same here. my windows azure web app installs are failing

**Comment by Jmales** [comment]
I still can't run `npm install` on my Windows 10 guys... Please help
