### ISSUE TITLE
npm install doesn’t install devdependencies

### ISSUE THREAD

**Issue by IvanYurchenko** [npm/npm#15705]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
npm doesn't install `devdependencies` by running `npm install`. They should be manually installed by running `npm install --dev`. The production mode is turned off.

#### How can the CLI team reproduce the problem?

There is no `npm-debug.log` file in my folder. I reproduce the problem on my project every time by just running `npm install` which doesn't install `devdependencies`. If it's a problem specifically with my project could you give me any advice on where to look to fix that?

I have tried to clear npm cache, this didn't solve the problem.

### supporting information:

 - `npm -v` prints:
3.10.10
 - `node -v` prints:
v6.9.4
 - `npm config get registry` prints:
https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?:
macOS Sierra
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
Hmm, that's weird. What does `npm config list` show from within one of your project directories?

**Comment by IvanYurchenko** [comment]
```
MacBook-Pro-Ivan:interviewblog ivanyurchenko$ npm config list
; cli configs
user-agent = "npm/3.10.10 node/v6.9.4 darwin x64"

; node bin location = /usr/local/bin/node
; cwd = /Users/ivanyurchenko/Documents/Projects/InterviewBlog
; HOME = /Users/ivanyurchenko
; "npm config ls -l" to show all defaults.
```

I also found a related [StackOverflow topic](http://stackoverflow.com/questions/34700610/npm-install-wont-install-devdependencies). However, it didn't help me to solve the problem. There is a suggestion to create another folder, try to install each package there individually and see if it changes something, but I wouldn't want to do this as I have several dozens of packages and installing all of them manually would take plenty of time.

**Comment by antoine-pous** [comment]
I got the same issue on Ubuntu and Debian
