### ISSUE TITLE
can not install gulp-sass by using npm install --save-dev gulp-sass

### ISSUE THREAD

**Issue by abhijit1978** [npm/npm#15704]
I am getting the error

```
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save-dev" "gulp-sass"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ENOSELF

npm ERR! Refusing to install gulp-sass as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     E:\WORK\gulp-test\npm-debug.log
```

please suggest

**Comment by KenanY** [comment]
@abhijit1978 Make sure the `"name"` field of your `package.json` is not set to `"gulp-sass"`.

**Comment by amiraba** [comment]
Had the same issue...
Run the git bash or the command line console as an administrator when launching the npm install command
Worked for me ! ;)

**Comment by jonathanafranio** [comment]
![capturar](https://user-images.githubusercontent.com/768332/36916670-681436e4-1e33-11e8-903d-30260cb08f3b.jpg)
@amiraba. I ran the code in git bash and it did not work.

`jonathan.afranio@nnest200 MINGW64 /c/xampp/htdocs/gulp-sass
$ npm install --save-dev gulp-sass
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save-dev" "gulp-sass"
npm ERR! node v6.9.3
npm ERR! npm  v3.10.10
npm ERR! code ENOSELF

npm ERR! Refusing to install gulp-sass as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\xampp\htdocs\gulp-sass\npm-debug.log
`
