### ISSUE TITLE
Gulp Command Not found  Ubuntu 16.04

### ISSUE THREAD

**Issue by zohaib055** [npm/npm#15709]
I'm having the weird  issue i had installed gulp both locally and and globally

but i m having the same issue when i type gulp command line it says "Gulp Command Not found"

when i check npm root -g gulp was found in  /usr/local/lib/node_modules/gulp

Also i checked this by uninstalling the node js and reinstalling having the same issue :(

and i installed forever package and it is working but not gulp .. it there anyone who can help me out

**Comment by cbuchert** [comment]
I'm running in a vagrant on Ubuntu 16.04. Running `npm root -g gulp` yielded `/usr/lib/node_modules`. Pathing issue, perhaps? I'd try symlinking, if nothing else for the lols.

**Comment by zohaib055** [comment]
i had installed the forever package recently and it worked but when i installed gulp it doesnt work

**Comment by zohaib055** [comment]
paths are correct though

**Comment by zohaib055** [comment]
I'm missing something else ??

**Comment by zohaib055** [comment]
I had figured out this closing :dancing_men:
