### ISSUE TITLE
Npm Cannot read property 'path' of null

### ISSUE THREAD

**Issue by reemuluzumaki** [npm/npm#15702]
#### I'm opening this issue because:

  - [ x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong? 
When trying to run Gulp Tasks I am getting error "Cannot read property 'path' of null"

#### How can the CLI team reproduce the problem?
It happens when I try to run Gulp from the command line or from IDE. the same. It also occurs when I run "npm install"
[<script src="https://gist.github.com/reemuluzumaki/6490fa58eeeb57ecec1166d5db524d24.js"></script>](url)

### supporting information:

 - `npm -v` prints: 4.0.5
 - `node -v` prints: 7.4.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux 16.04
 - Network issues:
   - Geographic location where npm was run: Austin TX
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by jwiese-ms** [comment]
I'm seeing the same thing on Windows 10, x64, build 14393.   I installed Chocolatey, Nodejs and python2, then when I try to install react-native-cli I get this error.

2 info using npm@4.1.2
3 info using node@v7.5.0

[npm-debug.log.txt](https://github.com/npm/npm/files/777559/npm-debug.log.txt)

**Comment by legodude17** [comment]
Try running `npm i -g react-native-cli` (instead of `npm install -g -react-native-cli`).

**Comment by jwiese-ms** [comment]
Ugh, how’d I miss the extra ‘-‘ ☹   Thanks.

**Comment by legodude17** [comment]
@jwiese-ms good to see you are all good.

@KenanY can you close this?

**Comment by KenanY** [comment]
Actually there's still @reemuluzumaki's issue to deal with.

**Comment by KenanY** [comment]
@reemuluzumaki I think I see a typo in your install command: you are trying to install `node-gype` instead of `node-gyp`. Is this intentional?
