### ISSUE TITLE
Incorrect resolution of devDependency + transitive dependency conflicts

### ISSUE THREAD

**Issue by pimterry** [npm/npm#15710]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Given a repository which devDepends on package X at one version, and depends normally transitively (via package Y) on package X at a different version, then only the first devDep version is installed, breaking my application (as Y does not receive the dependencies it expects).

I believe this should instead install both packages, nesting the second install of X within Y.

A diagram might help:

```
main  --devDep-->  lodash@3.0.0
   |
   |--normal dep-->  A  --normal dep-->  lodash@2.0.0
```

`npm ls lodash` after `npm install`:

```
main@1.0.0 /private/tmp/npm-bug/main
├─┬ A@1.0.0
│ └── UNMET DEPENDENCY lodash@3.0.0
└── lodash@2.0.0
```

I think it should be:

```
main@1.0.0 /private/tmp/npm-bug/main
├─┬ A@1.0.0
│ └── lodash@3.0.0
└── lodash@2.0.0
```

If the devDep is a normal dep, this resolves correctly (i.e. both versions of lodash are installed as expected).

#### How can the CLI team reproduce the problem?

* Check out https://github.com/pimterry/npm-bug-repro
* Run `repro.sh` (or just do an `npm install` inside `main`, and `npm ls lodash`)

### supporting information:

 - `npm -v` prints: 4.0.3 (but also reproducible in 3.10.10)
 - `node -v` prints: 7.2.1
 - `npm config get registry` prints: https://registry.npmjs.org
 - Windows, OS X/macOS, or Linux?: OSX (but reproducible on Linux)
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by pimterry** [comment]
Any thoughts on this? I'm happy to take a look at fixing it myself if somebody can confirm this is definitely incorrect behaviour, and point me in the right direction to get started.

We've already had this issue mean one of our production components silently went from deployable to unstartable due to a patch release in a dependency. I'd really like to get this fixed so that can't happen again.

**Comment by pimterry** [comment]
Hello? I'm fairly sure this is incorrect behaviour in npm, and it certainly isn't explained by any documentation I can find under https://docs.npmjs.com/how-npm-works.

Here npm takes a simple and valid package.json that defines a legitimate and achievable dependency tree, and silently fails to install the correct dependencies to satisfy it.

Can you confirm this is not expected behaviour, and preferably point me in the right direction to help fix it? Happy to put the legwork in myself, I just don't want this to disappear into the ether and bite us/others again in future.

**Comment by zkat** [comment]
This was fixed in https://github.com/npm/npm/pull/12811 which is part of `npm@4.0.5`. Closing as a duplicate. A quick version bump should fix it for you :)

but ping me if it somehow doesn't!
