### ISSUE TITLE
Angular 2 not installing

### ISSUE THREAD

**Issue by rajan2275** [npm/npm#15728]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   '@angular/cli' ]
2 info using npm@4.1.2
3 info using node@v7.5.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData @angular/cli
8 silly fetchNamedPackageData @angular/cli
9 silly mapToRegistry name @angular/cli
10 silly mapToRegistry scope (from package name) @angular
11 verbose mapToRegistry no registry URL found in name for scope @angular
12 silly mapToRegistry using default registry
13 silly mapToRegistry registry http://registry.npmjs.org/
14 silly mapToRegistry data Result {
14 silly mapToRegistry   raw: '@angular/cli',
14 silly mapToRegistry   scope: '@angular',
14 silly mapToRegistry   escapedName: '@angular%2fcli',
14 silly mapToRegistry   name: '@angular/cli',
14 silly mapToRegistry   rawSpec: '',
14 silly mapToRegistry   spec: 'latest',
14 silly mapToRegistry   type: 'tag' }
15 silly mapToRegistry uri http://registry.npmjs.org/@angular%2fcli
16 verbose request uri http://registry.npmjs.org/@angular%2fcli
17 verbose request no auth needed
18 info attempt registry request try #1 at 11:23:12 AM
19 verbose request id cfec67e72c2fd0df
20 http request GET http://registry.npmjs.org/@angular%2fcli
21 http 200 http://registry.npmjs.org/@angular%2fcli
22 verbose bad json <html>
22 verbose bad json <head><title>Authentication Required</title>
22 verbose bad json <meta http-equiv="Content-Type" content="text/html; charset=us-ascii">
22 verbose bad json <link rel="stylesheet" href="http://www.mailcontrol.com/css/proxy.css" type="text/css">
22 verbose bad json <link rel="shortcut icon" href="http://www.mailcontrol.com/images/wd_accessdenied.ico" type="image/x-icon">
22 verbose bad json </head>
22 verbose bad json <body>
22 verbose bad json <div align="center">
22 verbose bad json <div id="pagecontainer"><img src="http://www.mailcontrol.com/images/block.png" class="icon" >
22 verbose bad json <h1>Authentication Required</h1>
22 verbose bad json <div align="center">
22 verbose bad json <span id="access">To access the following page or site you must identify yourself.</span><br>
22 verbose bad json http://registry.npmjs.org:80/@angular%2fcli
22 verbose bad json <br><br>
22 verbose bad json If you have already registered, you may log in using the email address (not your name) and the password you registered with.
22 verbose bad json  If you have not already registered, please do so
22 verbose bad json  <br><br>
22 verbose bad json  <table>
22 verbose bad json       <tr>
22 verbose bad json         <td align="center"><form method='POST' ACTION='http://proxy-login.blackspider.com/'>
22 verbose bad json   <input type='hidden' name='meth' value='GET'/>
22 verbose bad json   <input type='hidden' name='url' value='http%3A//registry.npmjs.org%3A80/%40angular%252fcli'/>
22 verbose bad json   <input type='hidden' name='ip' value='37.157.38.82'/>
22 verbose bad json   <input type='hidden' name='service' value='hybrid'/>
22 verbose bad json   <input type='hidden' name='sessionid' value=''/>
22 verbose bad json   <input id='proxy_login_button' type='submit' value='    Log in...    '/>
22 verbose bad json   <script>document.getElementById('proxy_login_button').focus();</script>
22 verbose bad json </form></td>
22 verbose bad json         <td align="center"><form method='POST' ACTION='https://www.mailcontrol.com/hybrid_enduser/reg/index.mhtml'>
22 verbose bad json   <input type='hidden' name='site' value=''/>
22 verbose bad json   <input type='hidden' name='ntlmid' value=''/>
22 verbose bad json   <input type='hidden' name='meth' value='GET'/>
22 verbose bad json   <input type='hidden' name='url' value='http://registry.npmjs.org:80/@angular%2fcli'/>
22 verbose bad json   <input type='submit' name='submit' value='  Register...  ' tabindex="-1"/>
22 verbose bad json </form></td>
22 verbose bad json         <td align="center"><form method='POST' ACTION='https://www.mailcontrol.com/hybrid_enduser/change/index.mhtml'>
22 verbose bad json   <input type='hidden' name='site' value=''/>
22 verbose bad json   <input type='hidden' name='ntlmid' value=''/>
22 verbose bad json   <input type='hidden' name='meth' value='GET'/>
22 verbose bad json   <input type='hidden' name='url' value='http://registry.npmjs.org:80/@angular%2fcli'/>
22 verbose bad json   <input type='submit' value='Change your password'/>
22 verbose bad json </form></td>
22 verbose bad json         <td align="center"><form method='POST' ACTION='https://www.mailcontrol.com/hybrid_enduser/forgot/index.mhtml'>
22 verbose bad json   <input type='hidden' name='site' value=''/>
22 verbose bad json   <input type='hidden' name='ntlmid' value=''/>
22 verbose bad json   <input type='hidden' name='meth' value='GET'/>
22 verbose bad json   <input type='hidden' name='url' value='http://registry.npmjs.org:80/@angular%2fcli'/>
22 verbose bad json   <input type='submit' name='submit' value='Forgotten your password?'/>
22 verbose bad json </form></td>
22 verbose bad json       </tr>
22 verbose bad json     </table>
22 verbose bad json  <p>Please refer to your organization's Internet access policy</p>
22 verbose bad json <p>If your email address has changed, you must set a new password. Click "Forgotten your password?".</p>
22 verbose bad json  </div>
22 verbose bad json  </div>
22 verbose bad json  </div>
22 verbose bad json <script language="javascript">
22 verbose bad json if ('http://proxy-login.blackspider.com/'.substring(0, 6) === 'https:' && true)
22 verbose bad json {
22 verbose bad json     document.getElementById('access').innerHTML = 'To access the following <b>secure page or site</b> you must identify yourself.';
22 verbose bad json }
22 verbose bad json </script>
22 verbose bad json </body>
22 verbose bad json </html>
23 error registry error parsing json
24 verbose headers { 'x-bst-request-id': 'Zhkf2h:9fTc:124755',
24 verbose headers   'x-bst-info': 'ch=req,t=1486725792,h=23lonb,p=160272_1715:1_414,f=ForceAuthFilter,r=ForceAuthRule,c=2339,v=7.9.57267.1000',
24 verbose headers   'content-type': 'text/html; charset=utf-8',
24 verbose headers   pragma: 'No-cache',
24 verbose headers   'content-language': 'en',
24 verbose headers   'cache-control': 'No-cache',
24 verbose headers   'content-length': '3236' }
25 silly get cb [ 200,
25 silly get   { 'x-bst-request-id': 'Zhkf2h:9fTc:124755',
25 silly get     'x-bst-info': 'ch=req,t=1486725792,h=23lonb,p=160272_1715:1_414,f=ForceAuthFilter,r=ForceAuthRule,c=2339,v=7.9.57267.1000',
25 silly get     'content-type': 'text/html; charset=utf-8',
25 silly get     pragma: 'No-cache',
25 silly get     'content-language': 'en',
25 silly get     'cache-control': 'No-cache',
25 silly get     'content-length': '3236' } ]
26 silly fetchPackageMetaData SyntaxError: Unexpected token < in JSON at position 0
26 silly fetchPackageMetaData <html>
26 silly fetchPackageMetaData <head><title>Authentication Required</title>
26 silly fetchPackageMetaData <meta http-equiv="Content-Type" content="text/html; charset=us-ascii">
26 silly fetchPackageMetaData <link rel="stylesheet" href="http://www.mailcontrol.com/css/proxy.css" type="text/css">
26 silly fetchPackageMetaData <link rel="shortcut icon" href="http://www.mailcontrol.com/images/wd_accessdenied.ico" type="image/x-icon">
26 silly fetchPackageMetaData </head>
26 silly fetchPackageMetaData <body>
26 silly fetchPackageMetaData <div align="center">
26 silly fetchPackageMetaData <div id="pagecontainer"><img src="http://www.mailcontrol.com/images/block.png" class="icon" >
26 silly fetchPackageMetaData <h1>Authentication Required</h1>
26 silly fetchPackageMetaData <div align="center">
26 silly fetchPackageMetaData <span id="access">To access the following page or site you must identify yourself.</span><br>
26 silly fetchPackageMetaData http://registry.npmjs.org:80/@angular%2fcli
26 silly fetchPackageMetaData <br><br>
26 silly fetchPackageMetaData If you have already registered, you may log in using the email address (not your name) and the password you registered with.
26 silly fetchPackageMetaData  If you have not already registered, please do so
26 silly fetchPackageMetaData  <br><br>
26 silly fetchPackageMetaData  <table>
26 silly fetchPackageMetaData       <tr>
26 silly fetchPackageMetaData         <td align="center"><form method='POST' ACTION='http://proxy-login.blackspider.com/'>
26 silly fetchPackageMetaData   <input type='hidden' name='meth' value='GET'/>
26 silly fetchPackageMetaData   <input type='hidden' name='url' value='http%3A//registry.npmjs.org%3A80/%40angular%252fcli'/>
26 silly fetchPackageMetaData   <input type='hidden' name='ip' value='37.157.38.82'/>
26 silly fetchPackageMetaData   <input type='hidden' name='service' value='hybrid'/>
26 silly fetchPackageMetaData   <input type='hidden' name='sessionid' value=''/>
26 silly fetchPackageMetaData   <input id='proxy_login_button' type='submit' value='    Log in...    '/>
26 silly fetchPackageMetaData   <script>document.getElementById('proxy_login_button').focus();</script>
26 silly fetchPackageMetaData </form></td>
26 silly fetchPackageMetaData         <td align="center"><form method='POST' ACTION='https://www.mailcontrol.com/hybrid_enduser/reg/index.mhtml'>
26 silly fetchPackageMetaData   <input type='hidden' name='site' value=''/>
26 silly fetchPackageMetaData   <input type='hidden' name='ntlmid' value=''/>
26 silly fetchPackageMetaData   <input type='hidden' name='meth' value='GET'/>
26 silly fetchPackageMetaData   <input type='hidden' name='url' value='http://registry.npmjs.org:80/@angular%2fcli'/>
26 silly fetchPackageMetaData   <input type='submit' name='submit' value='  Register...  ' tabindex="-1"/>
26 silly fetchPackageMetaData </form></td>
26 silly fetchPackageMetaData         <td align="center"><form method='POST' ACTION='https://www.mailcontrol.com/hybrid_enduser/change/index.mhtml'>
26 silly fetchPackageMetaData   <input type='hidden' name='site' value=''/>
26 silly fetchPackageMetaData   <input type='hidden' name='ntlmid' value=''/>
26 silly fetchPackageMetaData   <input type='hidden' name='meth' value='GET'/>
26 silly fetchPackageMetaData   <input type='hidden' name='url' value='http://registry.npmjs.org:80/@angular%2fcli'/>
26 silly fetchPackageMetaData   <input type='submit' value='Change your password'/>
26 silly fetchPackageMetaData </form></td>
26 silly fetchPackageMetaData         <td align="center"><form method='POST' ACTION='https://www.mailcontrol.com/hybrid_enduser/forgot/index.mhtml'>
26 silly fetchPackageMetaData   <input type='hidden' name='site' value=''/>
26 silly fetchPackageMetaData   <input type='hidden' name='ntlmid' value=''/>
26 silly fetchPackageMetaData   <input type='hidden' name='meth' value='GET'/>
26 silly fetchPackageMetaData   <input type='hidden' name='url' value='http://registry.npmjs.org:80/@angular%2fcli'/>
26 silly fetchPackageMetaData   <input type='submit' name='submit' value='Forgotten your password?'/>
26 silly fetchPackageMetaData </form></td>
26 silly fetchPackageMetaData       </tr>
26 silly fetchPackageMetaData     </table>
26 silly fetchPackageMetaData  <p>Please refer to your organization's Internet access policy</p>
26 silly fetchPackageMetaData <p>If your email address has changed, you must set a new password. Click "Forgotten your password?".</p>
26 silly fetchPackageMetaData  </div>
26 silly fetchPackageMetaData  </div>
26 silly fetchPackageMetaData  </div>
26 silly fetchPackageMetaData <script language="javascript">
26 silly fetchPackageMetaData if ('http://proxy-login.blackspider.com/'.substring(0, 6) === 'https:' && true)
26 silly fetchPackageMetaData {
26 silly fetchPackageMetaData     document.getElementById('access').innerHTML = 'To access the following <b>secure page or site</b> you must identify yourself.';
26 silly fetchPackageMetaData }
26 silly fetchPackageMetaData </script>
26 silly fetchPackageMetaData </body>
26 silly fetchPackageMetaData </html>
26 silly fetchPackageMetaData     at JSON.parse (<anonymous>)
26 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:239:23)
26 silly fetchPackageMetaData     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:212:14)
26 silly fetchPackageMetaData     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:186:22)
26 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
26 silly fetchPackageMetaData     at Request.emit (events.js:192:7)
26 silly fetchPackageMetaData     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1081:10)
26 silly fetchPackageMetaData     at emitOne (events.js:96:13)
26 silly fetchPackageMetaData     at Request.emit (events.js:189:7)
26 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1001:12)
26 silly fetchPackageMetaData  error for @angular/cli SyntaxError: Unexpected token < in JSON at position 0
26 silly fetchPackageMetaData <html>
26 silly fetchPackageMetaData <head><title>Authentication Required</title>
26 silly fetchPackageMetaData <meta http-equiv="Content-Type" content="text/html; charset=us-ascii">
26 silly fetchPackageMetaData <link rel="stylesheet" href="http://www.mailcontrol.com/css/proxy.css" type="text/css">
26 silly fetchPackageMetaData <link rel="shortcut icon" href="http://www.mailcontrol.com/images/wd_accessdenied.ico" type="image/x-icon">
26 silly fetchPackageMetaData </head>
26 silly fetchPackageMetaData <body>
26 silly fetchPackageMetaData <div align="center">
26 silly fetchPackageMetaData <div id="pagecontainer"><img src="http://www.mailcontrol.com/images/block.png" class="icon" >
26 silly fetchPackageMetaData <h1>Authentication Required</h1>
26 silly fetchPackageMetaData <div align="center">
26 silly fetchPackageMetaData <span id="access">To access the following page or site you must identify yourself.</span><br>
26 silly fetchPackageMetaData http://registry.npmjs.org:80/@angular%2fcli
26 silly fetchPackageMetaData <br><br>
26 silly fetchPackageMetaData If you have already registered, you may log in using the email address (not your name) and the password you registered with.
26 silly fetchPackageMetaData  If you have not already registered, please do so
26 silly fetchPackageMetaData  <br><br>
26 silly fetchPackageMetaData  <table>
26 silly fetchPackageMetaData       <tr>
26 silly fetchPackageMetaData         <td align="center"><form method='POST' ACTION='http://proxy-login.blackspider.com/'>
26 silly fetchPackageMetaData   <input type='hidden' name='meth' value='GET'/>
26 silly fetchPackageMetaData   <input type='hidden' name='url' value='http%3A//registry.npmjs.org%3A80/%40angular%252fcli'/>
26 silly fetchPackageMetaData   <input type='hidden' name='ip' value='37.157.38.82'/>
26 silly fetchPackageMetaData   <input type='hidden' name='service' value='hybrid'/>
26 silly fetchPackageMetaData   <input type='hidden' name='sessionid' value=''/>
26 silly fetchPackageMetaData   <input id='proxy_login_button' type='submit' value='    Log in...    '/>
26 silly fetchPackageMetaData   <script>document.getElementById('proxy_login_button').focus();</script>
26 silly fetchPackageMetaData </form></td>
26 silly fetchPackageMetaData         <td align="center"><form method='POST' ACTION='https://www.mailcontrol.com/hybrid_enduser/reg/index.mhtml'>
26 silly fetchPackageMetaData   <input type='hidden' name='site' value=''/>
26 silly fetchPackageMetaData   <input type='hidden' name='ntlmid' value=''/>
26 silly fetchPackageMetaData   <input type='hidden' name='meth' value='GET'/>
26 silly fetchPackageMetaData   <input type='hidden' name='url' value='http://registry.npmjs.org:80/@angular%2fcli'/>
26 silly fetchPackageMetaData   <input type='submit' name='submit' value='  Register...  ' tabindex="-1"/>
26 silly fetchPackageMetaData </form></td>
26 silly fetchPackageMetaData         <td align="center"><form method='POST' ACTION='https://www.mailcontrol.com/hybrid_enduser/change/index.mhtml'>
26 silly fetchPackageMetaData   <input type='hidden' name='site' value=''/>
26 silly fetchPackageMetaData   <input type='hidden' name='ntlmid' value=''/>
26 silly fetchPackageMetaData   <input type='hidden' name='meth' value='GET'/>
26 silly fetchPackageMetaData   <input type='hidden' name='url' value='http://registry.npmjs.org:80/@angular%2fcli'/>
26 silly fetchPackageMetaData   <input type='submit' value='Change your password'/>
26 silly fetchPackageMetaData </form></td>
26 silly fetchPackageMetaData         <td align="center"><form method='POST' ACTION='https://www.mailcontrol.com/hybrid_enduser/forgot/index.mhtml'>
26 silly fetchPackageMetaData   <input type='hidden' name='site' value=''/>
26 silly fetchPackageMetaData   <input type='hidden' name='ntlmid' value=''/>
26 silly fetchPackageMetaData   <input type='hidden' name='meth' value='GET'/>
26 silly fetchPackageMetaData   <input type='hidden' name='url' value='http://registry.npmjs.org:80/@angular%2fcli'/>
26 silly fetchPackageMetaData   <input type='submit' name='submit' value='Forgotten your password?'/>
26 silly fetchPackageMetaData </form></td>
26 silly fetchPackageMetaData       </tr>
26 silly fetchPackageMetaData     </table>
26 silly fetchPackageMetaData  <p>Please refer to your organization's Internet access policy</p>
26 silly fetchPackageMetaData <p>If your email address has changed, you must set a new password. Click "Forgotten your password?".</p>
26 silly fetchPackageMetaData  </div>
26 silly fetchPackageMetaData  </div>
26 silly fetchPackageMetaData  </div>
26 silly fetchPackageMetaData <script language="javascript">
26 silly fetchPackageMetaData if ('http://proxy-login.blackspider.com/'.substring(0, 6) === 'https:' && true)
26 silly fetchPackageMetaData {
26 silly fetchPackageMetaData     document.getElementById('access').innerHTML = 'To access the following <b>secure page or site</b> you must identify yourself.';
26 silly fetchPackageMetaData }
26 silly fetchPackageMetaData </script>
26 silly fetchPackageMetaData </body>
26 silly fetchPackageMetaData </html>
26 silly fetchPackageMetaData     at JSON.parse (<anonymous>)
26 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:239:23)
26 silly fetchPackageMetaData     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:212:14)
26 silly fetchPackageMetaData     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:186:22)
26 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
26 silly fetchPackageMetaData     at Request.emit (events.js:192:7)
26 silly fetchPackageMetaData     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1081:10)
26 silly fetchPackageMetaData     at emitOne (events.js:96:13)
26 silly fetchPackageMetaData     at Request.emit (events.js:189:7)
26 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1001:12)
27 silly rollbackFailedOptional Starting
28 verbose stack TypeError: Cannot read property 'path' of null
28 verbose stack     at Installer.rollbackFailedOptional (C:\Program Files\nodejs\node_modules\npm\lib\install.js:511:29)
28 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
28 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
28 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:18:7
28 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install.js:337:5
28 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
28 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
28 verbose stack     at chain (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
28 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install.js:294:5
28 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:16:22
29 verbose cwd C:\
30 error Windows_NT 6.1.7601
31 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli"
32 error node v7.5.0
33 error npm  v4.1.2
34 error Cannot read property 'path' of null
35 error If you need help, you may report this error at:
35 error     <https://github.com/npm/npm/issues>
36 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@rajan2275 Looks like your proxy is blocking the request because you are not authenticated. Solution would be to authenticate yourself with your proxy before using it.
