### ISSUE TITLE
Installing from a local package adds its fully qualified path to package.json

### ISSUE THREAD

**Issue by rbluethl** [npm/npm#15724]
#### I'm opening this issue because:

  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.

#### What's going wrong?

I'm trying to install a dependency from a local path, which works as expected in the first place. `npm install --save ../my-package` installs my local package correctly, however, the package's absolute path is added to package.json. (For example file:///C:\\path\to\my\package\xyzpackage.) I expected npm to add the dependency to package.json with its relative path as given via `npm install`. According to your [docs](https://docs.npmjs.com/files/package.json#local-paths), this should actually happen. Am I doing something wrong? Once I change the path manually in the package.json, everything still works as expected. However, it feels kinda wrong to change the path manually after installing the package. This turns into an issue once we publish the code to our build server, since the package points to my local machine's path.

Thanks in advance.

**Comment by briandipalma** [comment]
Copy of https://github.com/npm/npm/issues/9717
