### ISSUE TITLE
missing script: buid

### ISSUE THREAD

**Issue by ds-manish** [npm/npm#15725]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'buid' ]
2 info using npm@3.10.3
3 info using node@v6.3.1
4 verbose stack Error: missing script: buid
4 verbose stack     at run (/usr/local/lib/node_modules/npm/lib/run-script.js:151:19)
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/run-script.js:61:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:356:5
4 verbose stack     at checkBinReferences_ (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:320:45)
4 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:354:3)
4 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:124:5)
4 verbose stack     at ReadFileContext.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:295:20)
4 verbose stack     at ReadFileContext.callback (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16)
4 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:365:13)
5 verbose cwd /Applications/XAMPP/xamppfiles/htdocs/angular2
6 error Darwin 16.4.0
7 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "buid"
8 error node v6.3.1
9 error npm  v3.10.3
10 error missing script: buid
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

**Comment by ericmdantas** [comment]
Hello, @ds-manish.

Can you share the content of your `package.json`?

**Comment by ds-manish** [comment]
Hello, @ericmdantas .
I did figured out the problem was in `package.json`.
I have solved it.
Thanks.

**Comment by ericmdantas** [comment]
:+1:

**Comment by huihuicai** [comment]
How to?I have the same problem.The code:
`"scripts": {
    "start": "roadhog server",
    **"build": "roadhog build",**
    "lint": "eslint --ext .js src test",
    "precommit": "npm run lint"
  }`

**Comment by huihuicai** [comment]
How to?I have the same problem.The code:
`"scripts": { "start": "roadhog server", "build": "roadhog build", "lint": "eslint --ext .js src test", "precommit": "npm run lint" }`

**Comment by ericmdantas** [comment]
@huihuicai what's the error message?

**Comment by huihuicai** [comment]
@ericmdantas missing script:build.But I reopen "cmd",the problem is solved.Thank you all same.
