### ISSUE TITLE
Npm upgrade to 6.9.5 now not installing dependencies

### ISSUE THREAD

**Issue by reemuluzumaki** [npm/npm#15722]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I upgraded to node.js 6.9.5 from 4.4.0 and now when I run 'npm install' on a previous project it error out. For some reason when I ran 'npm install --only=dev' it was able to install my devDependencies.

#### How can the CLI team reproduce the problem?
1. Install node.js 4.4.0
2. Start an agular project 
3. Upgrade node.js to 6.9.5 
4. clear the node_modules directory in the project
5. run 'npm install' on from the project directory (Make sure package.json exists)

https://gist.github.com/reemuluzumaki/56a76b9f116d39b12f166c43dc2c6e8f
### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@reemuluzumaki Could you try updating `npm`? `npm install -g npm`

**Comment by reemuluzumaki** [comment]
I tried, but I'm still getting the same error

**Comment by reemuluzumaki** [comment]
Just to be clear, the update of npm went just fine, but it did not resolve
my issue.

**Comment by KenanY** [comment]
@reemuluzumaki Could you upload the newer `npm`'s `npm-debug.log` file to <https://gist.github.com/> and post the link here?

**Comment by reemuluzumaki** [comment]
442 verbose get saving instafeed to /home/itachi/.npm/
registry.npmjs.org/instafeed/.cache.json
443 verbose correctMkdir /home/itachi/.npm correctMkdir not in flight;
initializing
444 verbose stack TypeError: Cannot convert undefined or null to object
444 verbose stack     at pickVersionFromRegistryDocument
(/usr/lib/node_modules/npm/lib/fetch-package-metadata.js:126:29)
444 verbose stack     at
/usr/lib/node_modules/npm/node_modules/iferr/index.js:13:50
444 verbose stack     at
/usr/lib/node_modules/npm/lib/utils/pulse-till-done.js:20:8
444 verbose stack     at saved
(/usr/lib/node_modules/npm/lib/cache/caching-client.js:174:7)
444 verbose stack     at
/usr/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:261:18
444 verbose stack     at FSReqWrap.oncomplete (fs.js:123:15)

**Comment by reemuluzumaki** [comment]
https://gist.github.com/reemuluzumaki/911a905f0418144e5a61fc6b52c3e866

**Comment by KenanY** [comment]
Hmm, I wonder what module is depending on `instafeed`, which was unpublished over a year ago.

**Comment by reemuluzumaki** [comment]
I took it out of my dependencies
It looks like I added it, but never used it. I guess I was thinking of
using it. It seems to be going now. Ok, it just finished.

Thanks for the insight.
