### ISSUE TITLE
Plugin crashing app after installation

### ISSUE THREAD

**Issue by Mr-Ketlhaetse** [npm/npm#15730]
I have created this plugin following all the instructions on building your first cordova module but when i install it on a test cordova based project, the cordova build command returns an error. It says something about the NDK being depricated. I updated my NDK but i still get the same error. 

![error](https://cloud.githubusercontent.com/assets/18008963/22832626/6ca3385a-efb7-11e6-98e6-30374c9a6a9c.PNG)

**Comment by KenanY** [comment]
Doesn't look like an `npm` issue to me.
