### ISSUE TITLE
npm install failed on Windows 8.1

### ISSUE THREAD

**Issue by rushikeshdole** [npm/npm#15731]
C:\Projects\client>npm install
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:206:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:877:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
npm WARN addRemoteGit  git+ssh://git@bitbucket.org/asurionwms/patlib.git#2.3.0 resetting remote C:\Users\XYZ\AppData\Roaming\npm-cache\_git-remotes\git-ssh-git-bitbucket
-org-asurionwms-patlib-git-2-3-0-e1c8eb23 because of error: { Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:206:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:877:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
npm ERR! git clone --template=C:\Users\XYZ\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror ssh://git@bitbucket.org/asurionwms/patlib.git C:\Users\XYZ\AppData\Roaming\npm-cache\_git-remotes\git-ssh-git-bitbucket-org-asurionwms-patlib-git-2-3-0-e1c8eb23: Cloning into bare repository 'C:\Users\XYZ\AppData\Roaming\npm-
cache\_git-remotes\git-ssh-git-bitbucket-org-asurionwms-patlib-git-2-3-0-e1c8eb23'...
npm ERR! git clone --template=C:\Users\XYZ\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror ssh://git@bitbucket.org/asurionwms/patlib.git C:\Users\XYZ\AppData\Roaming\npm-cache\_git-remotes\git-ssh-git-bitbucket-org-asurionwms-patlib-git-2-3-0-e1c8eb23: conq: repository access denied.
npm ERR! git clone --template=C:\Users\XYZ\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror ssh://git@bitbucket.org/asurionwms/patlib.git C:\Users\XYZ\AppData\Roaming\npm-cache\_git-remotes\git-ssh-git-bitbucket-org-asurionwms-patlib-git-2-3-0-e1c8eb23: fatal: Could not read from remote repository.
npm ERR! git clone --template=C:\Users\XYZ\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror ssh://git@bitbucket.org/asurionwms/patlib.git C:\Users\XYZ\AppData\Roaming\npm-cache\_git-remotes\git-ssh-git-bitbucket-org-asurionwms-patlib-git-2-3-0-e1c8eb23:
npm ERR! git clone --template=C:\Users\XYZ\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror ssh://git@bitbucket.org/asurionwms/patlib.git C:\Users\XYZ\AppData\Roaming\npm-cache\_git-remotes\git-ssh-git-bitbucket-org-asurionwms-patlib-git-2-3-0-e1c8eb23: Please make sure you have the correct access rights
npm ERR! git clone --template=C:\Users\XYZ\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror ssh://git@bitbucket.org/asurionwms/patlib.git C:\Users\XYZ\AppData\Roaming\npm-cache\_git-remotes\git-ssh-git-bitbucket-org-asurionwms-patlib-git-2-3-0-e1c8eb23: and the repository exists.
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\XYZ\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.7.0
npm ERR! npm  v4.2.0
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\XYZ\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror ssh://git@bitbucket.org/asur
ionwms/patlib.git C:\Users\XYZ\AppData\Roaming\npm-cache\_git-remotes\git-ssh-git-bitbucket-org-asurionwms-patlib-git-2-3-0-e1c8eb23
npm ERR! Cloning into bare repository 'C:\Users\XYZ\AppData\Roaming\npm-cache\_git-remotes\git-ssh-git-bitbucket-org-asurionwms-patlib-git-2-3-0-e1c8eb23'...
npm ERR! conq: repository access denied.
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\XYZ\AppData\Roaming\npm-cache\_logs\2017-02-10T16_58_00_179Z-debug.log

**Comment by Kevin-Chinem** [comment]
try running `npm install -g npm `

**Comment by rushikeshdole** [comment]
Pakage.json resides in Client folder,  so node module needs to be created there ?
