### ISSUE TITLE
Error with nmp in IOS Sierra - Helpme Please.

### ISSUE THREAD

**Issue by iludi** [npm/npm#15736]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'search' ]
2 info using npm@3.10.10
3 info using node@v6.9.5
4 verbose config Skipping project config: /Users/degana/.npmrc. (matches userconfig)
5 verbose stack Error: search must be called with arguments
5 verbose stack     at EventEmitter.search (/usr/local/lib/node_modules/npm/lib/search.js:57:15)
5 verbose stack     at Object.commandCache.(anonymous function) (/usr/local/lib/node_modules/npm/lib/npm.js:124:13)
5 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:73:30)
5 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:67:7)
5 verbose stack     at process._tickCallback (internal/process/next_tick.js:98:9)
6 verbose cwd /Users/degana
7 error Darwin 16.0.0
8 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "search"
9 error node v6.9.5
10 error npm  v3.10.10
11 error search must be called with arguments
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@iludi See error message:

```
11 error search must be called with arguments
```

**Comment by iludi** [comment]
Dear, how can I make the error search by argument?

Best regards.

**Comment by KenanY** [comment]
@iludi Please see <https://docs.npmjs.com/cli/search>. You can't search for... nothing, which is what you're trying to do. You need to pass in an argument like so:

```
npm search express
```
