### ISSUE TITLE
Not able to install node version 

### ISSUE THREAD

**Issue by VeereshMurari** [npm/npm#15739]
I not able to install the angular-cli. I have installed following node and npm version. Can you please help us.

E:\npm>node -v
v6.9.5

E:\npm>npm -v
3.10.10

Thanks
Veeresh

**Comment by KenanY** [comment]
@VeereshMurari Please upload the `npm-debug.log` file to <https://gist.github.com/> and post the link here.

**Comment by KenanY** [comment]
Closing due to lack of a response.
