### ISSUE TITLE
issue on  server

### ISSUE THREAD

**Issue by AravindRavichandran** [npm/npm#15745]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.10
3 info using node@v6.9.5
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle testproject1@1.0.0~prestart: testproject1@1.0.0
6 silly lifecycle testproject1@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle testproject1@1.0.0~start: testproject1@1.0.0
8 verbose lifecycle testproject1@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle testproject1@1.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\Aravind\Documents\testproject1\node_modules\.bin;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\OpenCL SDK\2.0\bin\x86;C:\Program Files\nodejs\;C:\Users\Aravind\AppData\Roaming\npm
10 verbose lifecycle testproject1@1.0.0~start: CWD: C:\Users\Aravind\Documents\testproject1
11 silly lifecycle testproject1@1.0.0~start: Args: [ '/d /s /c', 'webpack-dev-server --hot' ]
12 silly lifecycle testproject1@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle testproject1@1.0.0~start: Failed to exec start script
14 verbose stack Error: testproject1@1.0.0 start: `webpack-dev-server --hot`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid testproject1@1.0.0
16 verbose cwd C:\Users\Aravind\Documents\testproject1
17 error Windows_NT 6.1.7601
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v6.9.5
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error testproject1@1.0.0 start: `webpack-dev-server --hot`
22 error Exit status 1
23 error Failed at the testproject1@1.0.0 start script 'webpack-dev-server --hot'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the testproject1 package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack-dev-server --hot
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs testproject1
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls testproject1
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@AravindRavichandran As the error message states, this is most likely a problem with your `"start"` script, and not with `npm` itself. Does `webpack-dev-server --hot` run without error when you execute it from your command line?

**Comment by KenanY** [comment]
Closing as abandoned.
