### ISSUE TITLE
gulp is crashing

### ISSUE THREAD

**Issue by douglaskiel** [npm/npm#15743]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by douglaskiel** [comment]
I am trying to use the meanjs boilerplate, and following the pluralsight meanjs video project, which needs gulp to run.  I added the volunteer sub-generator CRUD module, but now gulp breaks down and doesn't work.  What do I look for to solve my problem?

**Comment by KenanY** [comment]
@douglaskiel If `npm` is throwing an error, then please upload the resulting `npm-debug.log` to <https://gist.github.com/> and post the link here.

**Comment by KenanY** [comment]
Closing as abandoned.

**Comment by ejlocop** [comment]
@KenanY Hi, same problem here. here's my [`npm-debug.log`](https://gist.github.com/ejlocop/758bc3346faf4bd3116411ba484c6a16)

**Comment by KenanY** [comment]
@ejlocop All `npm` is doing in that log is letting you know that `gulp watch` is returning an error exit code.
