### ISSUE TITLE
Unpublished a package(was on 1.0.0) Attempted to republish again on 1.0.0 (failed)

### ISSUE THREAD

**Issue by motiontheking** [npm/npm#15744]
#### I'm opening this issue because
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Unpublished a package(was on 1.0.0) Attempted to republish again on 1.0.0 (failed)

#### How can the CLI team reproduce the problem?
Clear versions in registry upon an unpublish
https://gist.github.com/motiontheking/36aaed43dbaf9be7d5bb18cba475b141

### supporting information:

 - `npm -v` prints: 4.1.2
 - `node -v` prints: 7.5.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Ubuntu(Linux) 14.04.3 LTS (Trusty)

**Comment by KenanY** [comment]
@motiontheking Yup, you gotta bump the version. Unpublishing a particular version doesn't make it available for publishing again.
