### ISSUE TITLE
something wrong with my npm. please i need a help...

### ISSUE THREAD

**Issue by DastanSE** [npm/npm#15750]
I already try to reinstall node.

npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! select-website@1.0.0 start: `npm-run-build`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the select-website@1.0.0 start script 'npm-run-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the select-website package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm-run-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs select-website
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls select-website
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/dastanzhanibek/Desktop/select-website-rv/npm-debug.log

**Comment by DastanSE** [comment]
my package.json


{
  "name": "select-website",
  "version": "1.0.0",
  "description": "new react version",
  "main": "index.js",
  "scripts": {
    "start": "npm-run-build",
    "build": "webpack -d && cp src/index.html dist/index.html && webpack-dev-server --content-base src/ --inline --hot",
    "build:prod": "webpack -d && cp src/index.html dist/index.html"
  },
  "author": "Dastan Zhanibek",
  "license": "ISC",
  "dependencies": {
    "react": "^15.4.2",
    "react-dom": "^15.4.2"
  },
  "devDependencies": {
    "babel-loader": "^6.2.10",
    "babel-preset-es2015": "^6.22.0",
    "babel-preset-react": "^6.22.0",
    "babel-preset-stage-2": "^6.22.0",
    "webpack": "^2.2.1",
    "webpack-dev-server": "^2.3.0"
  }
}

**Comment by DastanSE** [comment]
webpack.config.js


var webpack = require('webpack');
var path = require('path');

var PROD = (process.env.NODE_ENV == 'production');

var DIST_DIR = path.resolve(__dirname, "dist");
var SRC_DIR = path.resolve(__dirname, "src");

var config = {
	entry: SRC_DIR + "/app/index.js",
	output: {
	  path: DIST_DIR + '/app',
	  filename: "bundle.js",
	  publicPath: "/app/"
	},
	module: {
	  loaders: [
	    { test: /\.js?/, include:  SRC_DIR, loader: "babel-loader", query: { presets: ["react", "es2015", "stage-2"]} },
    ]
  },
};

module.exports = config;

**Comment by DastanSE** [comment]
```
DastandeMBP:~ dastanzhanibek$ ls
Applications	Desktop		Documents	Downloads	Library		Movies		Music		Pictures	Public		Trovi		VirtualBox VMs	Wine Files	eclipse		node_modules
DastandeMBP:~ dastanzhanibek$
```

or how i can remove node_modules FOLDER from my mac

**Comment by DastanSE** [comment]
npm-debug.log

```
DastandeMBP:select-website-rv dastanzhanibek$ cat npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.10.10
3 info using node@v6.9.5
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle select-website@1.0.0~prestart: select-website@1.0.0
6 silly lifecycle select-website@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle select-website@1.0.0~start: select-website@1.0.0
8 verbose lifecycle select-website@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle select-website@1.0.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/dastanzhanibek/Desktop/select-website-rv/node_modules/.bin:/Library/Frameworks/Python.framework/Versions/3.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
10 verbose lifecycle select-website@1.0.0~start: CWD: /Users/dastanzhanibek/Desktop/select-website-rv
11 silly lifecycle select-website@1.0.0~start: Args: [ '-c', 'npm-run-build' ]
12 info lifecycle select-website@1.0.0~start: Failed to exec start script
13 verbose stack Error: select-website@1.0.0 start: `npm-run-build`
13 verbose stack spawn ENOENT
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:33:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:877:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14 verbose pkgid select-website@1.0.0
15 verbose cwd /Users/dastanzhanibek/Desktop/select-website-rv
16 error Darwin 16.4.0
17 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 error node v6.9.5
19 error npm  v3.10.10
20 error file sh
21 error code ELIFECYCLE
22 error errno ENOENT
23 error syscall spawn
24 error select-website@1.0.0 start: `npm-run-build`
24 error spawn ENOENT
25 error Failed at the select-website@1.0.0 start script 'npm-run-build'.
25 error Make sure you have the latest version of node.js and npm installed.
25 error If you do, this is most likely a problem with the select-website package,
25 error not with npm itself.
25 error Tell the author that this fails on your system:
25 error     npm-run-build
25 error You can get information on how to open an issue for this project with:
25 error     npm bugs select-website
25 error Or if that isn't available, you can get their info via:
25 error     npm owner ls select-website
25 error There is likely additional logging output above.
26 verbose exit [ 1, true ]
```

**Comment by jpaulin** [comment]
### npm doesn't find an external script called npm-run-build

The immediate error is probably due to the fact that 'npm-run-build' script is not found. 

Try an alternative command in shell:

'**npm run build**' 

and see what happens. 

If you need more details of Webpack's "view of the world", you can tell it to spit debug information a bit more. Might help here. You kind of get steps towards a solution. 

### Squeeze more info out of Webpack

In **package.json**, change a line containing the "build" command to be:

`"build": "webpack **--display-error-details** -d && cp src/index.html dist/index.html && webpack-dev-server --content-base src/ --inline --hot",`

**Comment by jpaulin** [comment]
Oh, and now I'm being capt. Obvious, pardon me for that :) 
but one tip:

if you only have so far the configuration files, before anything else, do a 
`npm install`

in the project folder. This gets your dependencies (packages) downloaded.

**Comment by DastanSE** [comment]
@jpaulin  I already tried all of this things...  I think my nodejs was installed uncorrected

**Comment by DastanSE** [comment]
because it works on another machine

**Comment by provawebdev** [comment]
npm install -D webpack

**Comment by jpaulin** [comment]
I got this working with 2 additional packages that I added with -D (as dev dependency)
npm install -D babel-core
npm install -D babel-loader

So you might have those missing on the machine that doesn't work.

(It might be that you have these as global installations on the other machine)

And note, you have to have something in the file:
src/app/index.js

because this is the main entry point to your app, at the moment. 

(I simply put a 
`var x;`
for the index.js contents, just to test out)

**Comment by felansu** [comment]
+1

**Comment by Nagenderpratap** [comment]
everything is saying according to itself opinion but rather than problem has occurred.
