### ISSUE TITLE
Problem with installing any app via NPM

### ISSUE THREAD

**Issue by albka1986** [npm/npm#15754]
#### I'm opening this issue because:

  - npm is producing an incorrect install.

#### What's going wrong?
I try to install something and after the install I can launch it. System doesn't see the installed app.

#### How can the CLI team reproduce the problem?

For example:
I tried to install "appium-doctor" and I did it successfully.

```
npm install -g appium-doctor
/Users/oleg/.npm-global/bin/appium-doctor -> /Users/oleg/.npm-global/lib/node_modules/appium-doctor/appium-doctor.js
/Users/oleg/.npm-global/lib
└── appium-doctor@1.4.1 
```

After that I tried to launch the appium-doctor, and I got the error:
```
iMac-Ponomarenko:~ oleg$ appium-doctor
-bash: appium-doctor: command not found
```

### supporting information:

 - `npm -v` prints: 4.1.2
 - `node -v` prints: v6.9.5
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: OS X El Capitan
 - Network issues:
   - Geographic location where npm was run: Ukraine, Kharkiv

#### What problem is the feature intended to solve? 
I want to install appium 1.6.3. And i need "gulp" for it.

**Comment by KenanY** [comment]
@albka1986 Is `/Users/oleg/.npm-global/bin/` in your `PATH`?

**Comment by albka1986** [comment]
@KenanY 
`iMac-Ponomarenko:~ oleg$ npm config get prefix`
`/Users/oleg/.npm-global`

**Comment by KenanY** [comment]
@albka1986 No, the `prefix` is fine. What is the result of `echo $PATH`?

**Comment by albka1986** [comment]
I changed my folder for NPM as shows on this video - https://youtu.be/bxvybxYFq2o.
After it I've installed with the command npm install -g appium. And now it works! )
