### ISSUE TITLE
Angular2 build failed - npm ERR! missing script: build

### ISSUE THREAD

**Issue by sanjaykumarns** [npm/npm#15759]
I am trying to build angular 2 application using command **npm run build**

The output I am getting:

_npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5

npm ERR! missing script: build
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/SSNW/client/npm-debug.log_

The contents in  npm-debug.log is the following:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@4.0.5
3 info using node@v7.4.0
4 verbose stack Error: missing script: build
4 verbose stack     at run (/usr/local/lib/node_modules/npm/lib/run-script.js:151:19)
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/run-script.js:61:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:356:5
4 verbose stack     at checkBinReferences_ (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:320:45)
4 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:354:3)
4 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:124:5)
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:243:12
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
4 verbose stack     at tryToString (fs.js:426:3)
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:413:12)
5 verbose cwd /var/www/SSNW/client
6 error Linux 3.16.0-4-amd64
7 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
8 error node v7.4.0
9 error npm  v4.0.5
10 error missing script: build
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

Thanks in advance.

Sanjay

**Comment by ericmdantas** [comment]
Hello, @sanjaykumarns.

What's the content of your package.json?

**Comment by KenanY** [comment]
@sanjaykumarns Make sure you have defined a "build" script in your `package.json` before trying to run `npm run build`. See <https://docs.npmjs.com/misc/scripts>.
