### ISSUE TITLE
Angular2 - build, Where can I specify the host

### ISSUE THREAD

**Issue by sanjaykumarns** [npm/npm#15764]
I have successfully build the angular2 app, but I want to host it in a /var/www/v1 ie, ip/v1 (ip: 00.00.0.0), Where can I specify the host url : localhost/testproject in the environment file?
ng g command build the files in dist folder, but when I am copying those files into  /var/www/v1, it is showing, unable to load js, css files ie trying to load from localhost/styles/custom.css, actually it is existing in localhost/v1/styles/custom.css. I hope this is due the lag of url specification somewhere.

Thanks

Sanjay

**Comment by KenanY** [comment]
@sanjaykumarns I'm gonna close this since this issue tracker is for `npm` issues. I suggest you take your question to some other forum. Good luck!
