### ISSUE TITLE
gulp-sass出错是什么情况，用的是cnpm，是不是我的cnpm安装不对啊

### ISSUE THREAD

**Issue by yangshuibo** [npm/npm#15765]
E:\web_wordspcer\tiandamachijitui>cnpm i gulp-sass --save -dev
cnpm@4.5.0 (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cnpm\parse_argv.js)
npm@3.10.10 (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cnpm\node_modules\npm\lib\npm.js)
node@6.9.5 (D:\Program Files\nodejs\node.exe)
npminstall@2.24.0 (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\index.js)
prefix=C:\Users\Administrator\AppData\Roaming\npm
win32 x64 6.1.7601
registry=https://registry.npm.taobao.org

**Comment by legodude17** [comment]
What was the error? There is no error in you post.
