### ISSUE TITLE
npm ERR! Windows_NT 10.0.10586

### ISSUE THREAD

**Issue by kumar-jatin** [npm/npm#15763]
I am working on a node project. While executing the command, **npm install**, I am getting the below error.

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\j.kumar\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v7.2.1
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

**Comment by KenanY** [comment]
@kumar-jatin Is there a `npm-debug.log` file you can upload to <https://gist.github.com/> and link here?

**Comment by KenanY** [comment]
Closing due to no response.
