### ISSUE TITLE
error

### ISSUE THREAD

**Issue by aallii10** [npm/npm#15767]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
i want to use ionic but when i try to use the line "npm install npm -g" it gives me al sorts of errors 
#### How can the CLI team reproduce the problem?
no idea

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ x] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@aallii10 Please upload the resulting `npm-debug.log` file to <https://gist.github.com/> and link it here.

**Comment by KenanY** [comment]
Also please take the time to complete the support form in your post.

**Comment by aallii10** [comment]
@KenanY where can i find that file the reason i haven't filled out the whole form is because i'm not very skilled in coding

**Comment by KenanY** [comment]
@aallii10 The path to the file should be shown near the bottom of the output.

**Comment by aallii10** [comment]
https://gist.github.com/aallii10/571e89ed96b998b139a88ecc7a798d18

**Comment by KenanY** [comment]
@aallii10 Wrong file :)

**Comment by KenanY** [comment]
@aallii10 Here is an example of `npm` displaying the path to the log file (the last line):

![](https://0x0.st/4Lq.png)

**Comment by aallii10** [comment]
https://gist.github.com/aallii10/4a1619f6194afcf8b42e2bcc80d3666a
finally

**Comment by KenanY** [comment]
@aallii10 Thanks! Did you try running `npm cache clean`, as the error message suggests?

**Comment by aallii10** [comment]
http://prntscr.com/e9e7bq
i did yes
https://gist.github.com/aallii10/f4cd4df2e70f7a15bf62675579f5eef6

**Comment by KenanY** [comment]
@aallii10 Oh, sorry, can you try running `npm install -g npm@latest` instead?

**Comment by KenanY** [comment]
Closing as abandoned.
