### ISSUE TITLE
 es6-tutorial git:(master) ✗ npm start  npm ERR! Darwin 16.4.0 npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start" npm ERR! node v6.9.5 npm ERR! npm  v3.10.10  npm ERR! missing script: start npm ERR!  npm ERR! If you need help, you may report this error at: npm ERR!     <https://github.com/npm/npm/issues>  npm ERR! Please include the following file with any support request: npm ERR!     /Users/farbodaprin/Desktop/es6-tutorial/npm-debug.log

### ISSUE THREAD

**Issue by farbod29** [npm/npm#15775]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
Please fill out the issue template.

**Comment by farbod29** [comment]
npm -v    = 3.10.10
node js  -v = v6.9.5
https://registry.npmjs.org/


npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10

npm ERR! missing script: start
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/farbodaprin/Desktop/es6-tutorial/npm-debug.log

**Comment by BendingUnit-22** [comment]
`rm -rf node_modules/`
`npm install`

**Comment by KenanY** [comment]
@farbod29 

```
npm ERR! missing script: start
```

Make sure you have defined a `"start"` script in your `package.json`. The [documentation](https://docs.npmjs.com/misc/scripts) explains how to write your own scripts. Let me know if you have any further questions :)
