### ISSUE TITLE
npm install with relative local path adds absolute path to package.json

### ISSUE THREAD

**Issue by jbcpollak** [npm/npm#15778]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [X ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

When I add a local path to npm with this command:

`npm install -S ../bar`

According to the documentation (https://docs.npmjs.com/files/package.json#local-paths)

you should see:

```
{
  "name": "baz",
  "dependencies": {
    "bar": "file:../bar"
  }
}
```

Instead I end up with:

```
{
  "name": "baz",
  "dependencies": {
    "bar": "file:///User/myName/src/project/bar"
  }
}
```

#### How can the CLI team reproduce the problem?

Should happen with the command I provided above.

### supporting information:

 - `npm -v` prints:
$ npm --version
4.0.5

 - `node -v` prints:
$ node --version
v7.4.0

 - `npm config get registry` prints:
$ npm config get registry
https://registry.npmjs.org/

 - Windows, OS X/macOS, or Linux?:
macOS

 - Network issues:
Its a local install, I think this section is irrelevant.

**Comment by briandipalma** [comment]
Copy of this issue https://github.com/npm/npm/issues/9717

**Comment by briandipalma** [comment]
Can confirm it's fixed in npm 5.

**Comment by iarna** [comment]
As is said here, we did fix this npm@5! =)

**Comment by ORESoftware** [comment]
@iarna  crap, I want the absolute paths! See this issue:
https://github.com/npm/npm/issues/20645

is there a command line flag we can use to put the absolute path into the dependencies field?

**Comment by ORESoftware** [comment]
Why relative paths? It makes no sense to me, except maybe as a security issue

**Comment by briandipalma** [comment]
Absolute paths seem inflexible, it makes projects unportable between different developer machines/CI/build machines.

**Comment by ORESoftware** [comment]
@briandipalma relative paths are also inflexible see the issue I opened above. I think we need a choice about whether to use absolute or relative paths.

**Comment by briandipalma** [comment]
I do what you do in the issue you've raised above all the time without any problems. I'd say the issue is something else. Maybe it's this? https://github.com/npm/npm/issues/16854
