### ISSUE TITLE
Having issues installing cordova on my windows

### ISSUE THREAD

**Issue by AhhEagle** [npm/npm#15771]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ *] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Have being trying to install cordova and all I get is multiple errors 
#### How can the CLI team reproduce the problem?
Resource busy or locked

### supporting information:

 - `npm -v` prints:4.2.0
 - `node -v` prints:6.9.4
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:windows
 - Network issues:
   - Geographic location where npm was run:
   - [* ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [* ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@AhhEagle Please upload the resulting `npm-debug.log` file to <https://gist.github.com/> and link it here.

**Comment by AhhEagle** [comment]
![capture](https://cloud.githubusercontent.com/assets/24871973/22988008/fbbb4fd0-f3b0-11e6-9ad4-b0f07d31504f.PNG)

**Comment by legodude17** [comment]
@AhhEagle that is not what @KenanY asked you to do. Please put the text on the `npm-debug.log` file into a gist of https://gist.github.com and then link to it in this thread.

**Comment by KenanY** [comment]
@AhhEagle Hey, are you still experiencing this issue by any chance? The `EBUSY` error codes seem to say that some other process is accessing some `npm` files right as `npm` is accessing them. Usually I just suggest rebooting, but this might not be a flawless solution. I'll have to dig through the issue tracker to see how others have solved this in the past.
