### ISSUE TITLE
error:Cannot find module 'internal/fs'

### ISSUE THREAD

**Issue by ying0800** [npm/npm#15788]
#### I'm opening this issue because:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'npm@latest',
1 verbose cli   '-g' ]
2 info using npm@4.0.5
3 info using node@v7.4.0
4 verbose stack Error: Cannot find module 'internal/fs'
4 verbose stack     at Function.Module._resolveFilename (module.js:470:15)
4 verbose stack     at Function.Module._load (module.js:418:25)
4 verbose stack     at Module.require (module.js:498:17)
4 verbose stack     at require (internal/module.js:20:19)
4 verbose stack     at evalmachine.<anonymous>:18:20
4 verbose stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/cmd-shim/node_modules/graceful-fs/fs.js:11:1)
4 verbose stack     at Module._compile (module.js:571:32)
4 verbose stack     at Object.Module._extensions..js (module.js:580:10)
4 verbose stack     at Module.load (module.js:488:32)
4 verbose stack     at tryModuleLoad (module.js:447:12)
5 verbose cwd /Users/Grace/Sites/vue/vue_webpack
6 error Darwin 15.0.0
7 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "npm@latest" "-g"
8 error node v7.4.0
9 error npm  v4.0.5
10 error code MODULE_NOT_FOUND
11 error Cannot find module 'internal/fs'
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]

**Comment by legodude17** [comment]
Try reinstalling `npm`.

**Comment by KenanY** [comment]
Closing as abandoned.

**Comment by tandrewnichols** [comment]
FWIW, I was running into this reproducibly. I'm on node 7.7.2 (also tried on 7.7.1), in both cases using npm 3.8.9 and if I have a reference to npm in my scripts, I get the error above. E.g.

package.json
```
"script": {
  "banana": "npm run apple",
  "apple": "something-other-command"
}
```

`npm run apple` works fine but `npm run banana` produces the error in the title.

Resintalling `npm` (or updating . . . basically changing the global binary in some way) does fix the issue. Not sure what gets it into this state, but I thought it was worth confirming that reinstalling npm seems to work.
