### ISSUE TITLE
npm error

### ISSUE THREAD

**Issue by nelsonhumberto** [npm/npm#15784]
#### I'm opening this issue because:

  - [x] npm is crashing.

#### What's going wrong?
this is the npm-debug:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'phonegap@latest' ]
2 info using npm@4.1.2
3 info using node@v7.5.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData phonegap@latest
8 silly fetchNamedPackageData phonegap
9 silly mapToRegistry name phonegap
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'phonegap',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'phonegap',
12 silly mapToRegistry   name: 'phonegap',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/phonegap
14 verbose request uri https://registry.npmjs.org/phonegap
15 verbose request no auth needed
16 info attempt registry request try #1 at 9:30:42 AM
17 verbose request id 7ca22b04279f66d4
18 http request GET https://registry.npmjs.org/phonegap
19 info retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.64.162:443
20 info attempt registry request try #2 at 9:31:13 AM
21 http request GET https://registry.npmjs.org/phonegap
22 info retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.64.162:443
23 info attempt registry request try #3 at 9:32:34 AM
24 http request GET https://registry.npmjs.org/phonegap
25 silly fetchPackageMetaData Error: connect ETIMEDOUT 151.101.64.162:443
25 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1023:11)
25 silly fetchPackageMetaData     at exports._exceptionWithHostPort (util.js:1046:20)
25 silly fetchPackageMetaData     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
25 silly fetchPackageMetaData  error for phonegap@latest { Error: connect ETIMEDOUT 151.101.64.162:443
25 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1023:11)
25 silly fetchPackageMetaData     at exports._exceptionWithHostPort (util.js:1046:20)
25 silly fetchPackageMetaData     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
25 silly fetchPackageMetaData   code: 'ETIMEDOUT',
25 silly fetchPackageMetaData   errno: 'ETIMEDOUT',
25 silly fetchPackageMetaData   syscall: 'connect',
25 silly fetchPackageMetaData   address: '151.101.64.162',
25 silly fetchPackageMetaData   port: 443 }
26 silly rollbackFailedOptional Starting
27 verbose stack TypeError: Cannot read property 'path' of null
27 verbose stack     at Installer.rollbackFailedOptional (C:\Program Files\nodejs\node_modules\npm\lib\install.js:511:29)
27 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
27 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
27 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:18:7
27 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install.js:337:5
27 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
27 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
27 verbose stack     at chain (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
27 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install.js:294:5
27 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:16:22
28 verbose cwd C:\Users\T0140159
29 error Windows_NT 6.1.7601
30 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "phonegap@latest"
31 error node v7.5.0
32 error npm  v4.1.2
33 error Cannot read property 'path' of null
34 error If you need help, you may report this error at:
34 error     <https://github.com/npm/npm/issues>
35 verbose exit [ 1, true ]

**Comment by legodude17** [comment]
What are the results of:
1. `npm config get registry`
2. `npm config get http-proxy`
3. `npm config get https-proxy`

**Comment by nelsonhumberto** [comment]
npm config get registry
https://registry.npmjs.org/

npm config get http-proxy
undefined

npm config get https-proxy
null

**Comment by legodude17** [comment]
What happens when you enter `151.101.64.162:443` into your browser?

**Comment by nelsonhumberto** [comment]
nothing :(

**Comment by legodude17** [comment]
How is you internet connection?

**Comment by ViralPanda** [comment]
Having the exact same problem. Internet connection is fine.

**Comment by alexhuszar** [comment]
Having the exact same problem, with high speed band 30mb/s
....

pm ERR! fetch failed https://registry.npmjs.org/cssesc/-/cssesc-0.1.0.tgz
npm WARN retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.0.162:443
npm ERR! fetch failed https://registry.npmjs.org/cssom/-/cssom-0.3.1.tgz
npm WARN retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.192.162:443
npm ERR! fetch failed https://registry.npmjs.org/cssstyle/-/cssstyle-0.2.37.tgz
npm WARN retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.128.162:443
npm ERR! fetch failed https://registry.npmjs.org/curry/-/curry-1.2.0.tgz
npm WARN retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.64.162:443
npm ERR! fetch failed https://registry.npmjs.org/d3-funnel/-/d3-funnel-0.7.7.tgz
npm WARN retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.192.162:443
npm ERR! fetch failed https://registry.npmjs.org/currently-unhandled/-/currently-unhandled-0.4.1.tgz
npm WARN retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.0.162:443
npm ERR! fetch failed https://registry.npmjs.org/d/-/d-0.1.1.tgz
npm WARN retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.64.162:443
npm ERR! fetch failed https://registry.npmjs.org/d3/-/d3-3.5.17.tgz
npm WARN retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.128.162:443
npm ERR! fetch failed https://registry.npmjs.org/date-names/-/date-names-0.1.6.tgz
npm WARN retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.0.162:443
npm ERR! fetch failed https://registry.npmjs.org/damals/-/damals-0.9.4.tgz


...

**Comment by legodude17** [comment]
@alexhuszar Do you use a proxy or VPN?

**Comment by SVITY** [comment]
@legodude17 I have the same problem, I don't use proxy or vpn.

**Comment by legodude17** [comment]
Try updating to latest version of `npm`.
