### ISSUE TITLE
install helper problem

### ISSUE THREAD

**Issue by deepbishnoi** [npm/npm#15781]
#### I'm opening this issue because:
`user@user-Vostro-3560:~$ sudo npm install -g n
[sudo] password for user: 
npm ERR! Linux 3.19.0-80-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "n"
npm ERR! node v4.4.2
npm ERR! npm  v4.2.0

npm ERR! Cannot read property 'path' of null
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/user/.npm/_logs/2017-02-16T07_33_48_849Z-debug.log
`

**Comment by deepbishnoi** [comment]
plz can somebody help me out.

**Comment by watilde** [comment]
Hello! We need more information to resolve your issue. Could you give us your `npm-debug.log`(printed as `/home/user/.npm/_logs/2017-02-16T07_33_48_849Z-debug.log` in your log)?

**Comment by deepbishnoi** [comment]
how to open this file??

`user@user-Vostro-3560:/$ cd home
user@user-Vostro-3560:/home$ /user
bash: /user: No such file or directory
user@user-Vostro-3560:/home$ cd user/.npm/_logs
user@user-Vostro-3560:~/.npm/_logs$ ls
2017-02-16T06_55_44_643Z-debug.log  2017-02-20T06_23_12_265Z-debug.log
2017-02-16T07_17_27_732Z-debug.log  2017-02-21T10_26_38_807Z-debug.log
2017-02-16T07_33_48_849Z-debug.log  2017-02-22T06_37_10_883Z-debug.log
user@user-Vostro-3560:~/.npm/_logs$ ./2017-02-16T07_33_48_849Z-debug.log
bash: ./2017-02-16T07_33_48_849Z-debug.log: Permission denied
user@user-Vostro-3560:~/.npm/_logs$ cd 2017-02-16T07_33_48_849Z-debug.log
bash: cd: 2017-02-16T07_33_48_849Z-debug.log: Not a directory
user@user-Vostro-3560:~/.npm/_logs$ /2017-02-16T07_33_48_849Z-debug.log
bash: /2017-02-16T07_33_48_849Z-debug.log: No such file or directory
`

**Comment by deepbishnoi** [comment]
`user@user-Vostro-3560:/$ cd home
user@user-Vostro-3560:/home$ /user
bash: /user: No such file or directory
user@user-Vostro-3560:/home$ cd user/.npm/_logs
user@user-Vostro-3560:~/.npm/_logs$ ls
2017-02-16T06_55_44_643Z-debug.log  2017-02-20T06_23_12_265Z-debug.log
2017-02-16T07_17_27_732Z-debug.log  2017-02-21T10_26_38_807Z-debug.log
2017-02-16T07_33_48_849Z-debug.log  2017-02-22T06_37_10_883Z-debug.log
user@user-Vostro-3560:~/.npm/_logs$ ./2017-02-16T07_33_48_849Z-debug.log
bash: ./2017-02-16T07_33_48_849Z-debug.log: Permission denied
user@user-Vostro-3560:~/.npm/_logs$ cd 2017-02-16T07_33_48_849Z-debug.log
bash: cd: 2017-02-16T07_33_48_849Z-debug.log: Not a directory
user@user-Vostro-3560:~/.npm/_logs$ /2017-02-16T07_33_48_849Z-debug.log
bash: /2017-02-16T07_33_48_849Z-debug.log: No such file or directory
'

how to open this??

**Comment by KenanY** [comment]
@deepbishnoi Use your favorite text editor, or `cat`, `less`, etc.

```
cat 2017-02-16T07_33_48_849Z-debug.log

# or

less 2017-02-16T07_33_48_849Z-debug.log
```

**Comment by deepbishnoi** [comment]
don't have less & tried installing it.


`user@user-Vostro-3560:~$ sudo npm install -g lessc
[sudo] password for user: 
npm ERR! Linux 3.19.0-80-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "lessc"
npm ERR! node v4.4.2
npm ERR! npm  v4.2.0

npm ERR! Cannot read property 'path' of null
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/user/.npm/_logs/2017-02-22T18_42_56_665Z-debug.log
`

**Comment by legodude17** [comment]
Run `cat /home/user/.npm/_logs/2017-02-22T18_42_56_665Z-debug.log`.

**Comment by KenanY** [comment]
@deepbishnoi Sorry, I was referring to [`less(1)`](https://linux.die.net/man/1/less), not a `npm` package.

**Comment by deepbishnoi** [comment]
`0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'install', '-g', 'n' ]
2 info using npm@4.2.0
3 info using node@v4.4.2
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData n
8 silly fetchNamedPackageData n
9 silly mapToRegistry name n
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'n',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'n',
12 silly mapToRegistry   name: 'n',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/n
14 verbose request uri https://registry.npmjs.org/n
15 verbose request no auth needed
`
that's the debug file i think?
@KenanY @legodude17

**Comment by deepbishnoi** [comment]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'install', '-g', 'lessc' ]
2 info using npm@4.2.0
3 info using node@v4.4.2
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData lessc
8 silly fetchNamedPackageData lessc
9 silly mapToRegistry name lessc
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'lessc',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'lessc',
12 silly mapToRegistry   name: 'lessc',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/lessc
14 verbose request uri https://registry.npmjs.org/lessc
15 verbose request no auth needed

that is the 2017-02-22T18_42_56_665Z-debug.log file?
@legodude17

**Comment by legodude17** [comment]
That is it, but where is the rest?

**Comment by deepbishnoi** [comment]
i figured it out sir..
npm was using proxy, despite i wasn't behind a proxy server.
>npm config set proxy null
>npm config set https-proxy null
thank you @legodude17 @KenanY @watilde
