### ISSUE TITLE
Registry is Overridden (How to Track Actual Value)

### ISSUE THREAD

**Issue by mindsect** [npm/npm#15785]
We're opening this issue because:
npm is doing something I don't understand.

What's going wrong?
When setting NPM registry (npm config set registry https://registry.npmjs.org/ and then perform an "npm config list", the registry option is prefaced by a semi-colon and ended with the status (overridden):

; registry = "https://registry.npmjs.org/" (overridden)

How can the CLI team reproduce the problem?

Be behind a corporate proxy? (this is a request for possible solutions)

Supporting information:

 - `npm -v` prints: 2.15.5
 - `node -v` prints: v4.4.5

 - `npm config get registry` prints: [ACTUAL ISSUE] prints corporate company's  registry

 - Windows, OS X/macOS, or Linux?: Windows 7 Enterprise

 - Network issues:
I use a proxy to connect to the npm registry.

**Comment by legodude17** [comment]
Please update npm.
