### ISSUE TITLE
npm link fails and deletes the folder contents

### ISSUE THREAD

**Issue by scottg299** [npm/npm#15783]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [X] Other (_see below for feature requests_):

#### What's going wrong?

"npm link" deleted the entire folder contents. This is obviously catastrophic if the user is not using source control or hasn't committed their work for a while!

#### How can the CLI team reproduce the problem?

1) Open a command window **as Administrator** in the root directory of the package to link (in the debug log: C:\code\myNpmPackages\utils)
2) Run "npm link" - works successfully
3) Open a new command window - this time **not as Administrator** - again in the root directory of the package to link
4) Run "npm link" - fails with error due to insufficient permissions
5) The directory is now empty except for a new "npm-debug.log" file - all other files and folders in there are permanently deleted

npm.debug.log here:
https://gist.github.com/scottg299/94d96f8ed49a57d0dcf433ba78566f14

What I believe is happening is that the second time npm link is run, some system action is prevented due to insufficient permissions. The script then erroneously tries to clean up after itself by attempting to delete the simlink that is already there. It does this by executing rmdir on the simlink address - which of course causes the rmdir action to be executed on the folder it links to, thus deleting the whole folder contents. This is just an educated guess based on the debug log - I could not find the relevant code in this repository.

I can consistently reproduce this in my environment.

I lost a whole day's work because of this - fortunately I'm using source control so could pick up from my last commit the previous day. This could have been much worse if I hadn't been using source control, of course!

### supporting information:

 - `npm -v` prints: 3.10.9
 - `node -v` prints: 7.5.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows 10 Enterprise
 - Network issues:
   - Geographic location where npm was run: Warwickshire, United Kingdom
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by tahone** [comment]
I just had the same happen to me. I had linked three local modules to a project and deleted node_modules folder under the project, in IntellJ and it deleted everything from the linked modules as well, including local git repos. Fortunately I could recover the folder contents with the help of a recovery tool as all the commits hadn't been pushed yet.

**Comment by klouskingsley** [comment]
same issue in npm v4.2.0 windows 10 node7.8.0
