### ISSUE TITLE
npm publish failed put 400; is invalid for new packages

### ISSUE THREAD

**Issue by powa2005** [npm/npm#15787]
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'publish' ]
2 info using npm@3.10.3
3 info using node@v6.6.0
4 verbose publish [ '.' ]
5 silly cache add args [ '.', null ]
6 verbose cache add spec .
7 silly cache add parsed spec Result {
7 silly cache add   raw: '.',
7 silly cache add   scope: null,
7 silly cache add   escapedName: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: '.',
7 silly cache add   spec: 'F:\\Fz\\coding\\xHttpServer',
7 silly cache add   type: 'directory' }
8 verbose addLocalDirectory C:\Users\DELL\AppData\Roaming\npm-cache\xHttpServer\0.0.6\package.tgz not in flight; packing
9 verbose correctMkdir C:\Users\DELL\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
10 info lifecycle xHttpServer@0.0.6~prepublish: xHttpServer@0.0.6
11 silly lifecycle xHttpServer@0.0.6~prepublish: no script for prepublish, continuing
12 verbose tar pack [ 'C:\\Users\\DELL\\AppData\\Roaming\\npm-cache\\xHttpServer\\0.0.6\\package.tgz',
12 verbose tar pack   'F:\\Fz\\coding\\xHttpServer' ]
13 verbose tarball C:\Users\DELL\AppData\Roaming\npm-cache\xHttpServer\0.0.6\package.tgz
14 verbose folder F:\Fz\coding\xHttpServer
15 verbose addLocalTarball adding from inside cache C:\Users\DELL\AppData\Roaming\npm-cache\xHttpServer\0.0.6\package.tgz
16 verbose correctMkdir C:\Users\DELL\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
17 silly cache afterAdd xHttpServer@0.0.6
18 verbose afterAdd C:\Users\DELL\AppData\Roaming\npm-cache\xHttpServer\0.0.6\package\package.json not in flight; writing
19 verbose correctMkdir C:\Users\DELL\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
20 verbose afterAdd C:\Users\DELL\AppData\Roaming\npm-cache\xHttpServer\0.0.6\package\package.json written
21 silly publish { name: 'xHttpServer',
21 silly publish   version: '0.0.6',
21 silly publish   description: 'A simple command-line http server',
21 silly publish   main: './lib',
21 silly publish   repository:
21 silly publish    { type: 'git',
21 silly publish      url: 'git+ssh://git@github.com/powa2005/xHttpServer.git' },
21 silly publish   keywords: [ 'cli', 'command', 'http server' ],
21 silly publish   scripts:
21 silly publish    { start: 'node ./bin/xHttpServer',
21 silly publish      test: 'node ./lib/',
21 silly publish      clean: 'rm -rf lib',
21 silly publish      compile: 'node ./node_modules/babel-cli/bin/babel.js -d lib/ src/' },
21 silly publish   dependencies: { 'babel-cli': '^6.18.0', optimist: '0.6.x' },
21 silly publish   devDependencies: { 'babel-cli': '^6.16.0', 'babel-preset-nodejs6-es6': '^1.0.1' },
21 silly publish   license: 'MIT',
21 silly publish   preferGlobal: 'true',
21 silly publish   bin: { xHttpServer: './bin/xHttpServer', xhs: './bin/xHttpServer' },
21 silly publish   dist: { shasum: '', tarball: '' },
21 silly publish   homepage: 'https://github.com/powa2005/xHttpServer',
21 silly publish   directories: {},
21 silly publish   readme: '# xHttpServer: a command-line http server\n\n`xHttpServer` 是一款简单的命令行httpserver工具，主要用于日常开发调试，以及nodejs工具开发学习.\n\n\n# 全局安装:\n\n     npm install xHttpServer -g\n\n\n## 使用:\n\n     xHttpServer [options]\n\n\n##  Options选项:\n\n`-p` 自定义端口 (默认为8080)\n\n`-h` or `--help` 使用帮助.\n',
21 silly publish   readmeFilename: 'README.md',
21 silly publish   gitHead: '84b75d2b3567894c4e27005d27ea16b42c290697',
21 silly publish   bugs: { url: 'https://github.com/powa2005/xHttpServer/issues' },
21 silly publish   _id: 'xHttpServer@0.0.6',
21 silly publish   _shasum: '303a4d2b2985c77022e497c87edd6f203bdf178c',
21 silly publish   _from: '.' }
22 verbose getPublishConfig undefined
23 silly mapToRegistry name xHttpServer
24 silly mapToRegistry using default registry
25 silly mapToRegistry registry https://registry.npmjs.org/
26 silly mapToRegistry data Result {
26 silly mapToRegistry   raw: 'xHttpServer',
26 silly mapToRegistry   scope: null,
26 silly mapToRegistry   escapedName: 'xHttpServer',
26 silly mapToRegistry   name: 'xHttpServer',
26 silly mapToRegistry   rawSpec: '',
26 silly mapToRegistry   spec: 'latest',
26 silly mapToRegistry   type: 'tag' }
27 silly mapToRegistry uri https://registry.npmjs.org/xHttpServer
28 verbose publish registryBase https://registry.npmjs.org/
29 silly publish uploading C:\Users\DELL\AppData\Roaming\npm-cache\xHttpServer\0.0.6\package.tgz
30 verbose request uri https://registry.npmjs.org/xHttpServer
31 verbose request sending authorization for write operation
32 info attempt registry request try #1 at 10:52:09
33 verbose request using bearer token for auth
34 verbose request id 475310416bf0e5c1
35 http request PUT https://registry.npmjs.org/xHttpServer
36 http 400 https://registry.npmjs.org/xHttpServer
37 verbose headers { 'content-type': 'application/json',
37 verbose headers   'cache-control': 'max-age=300',
37 verbose headers   'content-length': '55',
37 verbose headers   'accept-ranges': 'bytes',
37 verbose headers   date: 'Fri, 17 Feb 2017 02:52:24 GMT',
37 verbose headers   via: '1.1 varnish',
37 verbose headers   connection: 'keep-alive',
37 verbose headers   'x-served-by': 'cache-nrt6129-NRT',
37 verbose headers   'x-cache': 'MISS',
37 verbose headers   'x-cache-hits': '0',
37 verbose headers   'x-timer': 'S1487299937.595540,VS0,VE6841',
37 verbose headers   vary: 'Accept-Encoding' }
38 verbose request invalidating C:\Users\DELL\AppData\Roaming\npm-cache\registry.npmjs.org\xHttpServer on PUT
39 error publish Failed PUT 400
40 verbose stack Error: "xHttpServer" is invalid for new packages : xHttpServer
40 verbose stack     at makeError (D:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:264:12)
40 verbose stack     at CachingRegistryClient.<anonymous> (D:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:252:14)
40 verbose stack     at Request._callback (D:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:172:14)
40 verbose stack     at Request.self.callback (D:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:200:22)
40 verbose stack     at emitTwo (events.js:106:13)
40 verbose stack     at Request.emit (events.js:191:7)
40 verbose stack     at Request.<anonymous> (D:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1067:10)
40 verbose stack     at emitOne (events.js:101:20)
40 verbose stack     at Request.emit (events.js:188:7)
40 verbose stack     at IncomingMessage.<anonymous> (D:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:988:12)
41 verbose statusCode 400
42 verbose pkgid xHttpServer
43 verbose cwd F:\Fz\coding\xHttpServer
44 error Windows_NT 10.0.14393
45 error argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "publish"
46 error node v6.6.0
47 error npm  v3.10.3
48 error code E400
49 error "xHttpServer" is invalid for new packages : xHttpServer
50 error If you need help, you may report this error at:
50 error     <https://github.com/npm/npm/issues>
51 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@powa2005 Capital letters are disallowed in new package names.

**Comment by powa2005** [comment]
oh~Thanks...
