### ISSUE TITLE
npm not install any packages

### ISSUE THREAD

**Issue by a-khalid** [npm/npm#15793]
Hello , why i can't install any package from npm .
Ex: ionic.

iMac:~ ahmedkhalid$ npm install -g cordova ionic
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "cordova" "ionic"
npm ERR! node v6.9.5
npm ERR! npm  v4.1.2

npm ERR! Cannot read property 'path' of null
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "cordova" "ionic"
npm ERR! node v6.9.5
npm ERR! npm  v4.1.2
npm ERR! code ECONNRESET

npm ERR! network socket hang up
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ahmedkhalid/npm-debug.log

<hr />

**# npm-debug.log file**

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'cordova',
1 verbose cli   'ionic' ]
2 info using npm@4.1.2
3 info using node@v6.9.5
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData cordova
8 silly fetchPackageMetaData ionic
9 silly fetchNamedPackageData cordova
10 silly mapToRegistry name cordova
11 silly mapToRegistry using default registry
12 silly mapToRegistry registry https://registry.npmjs.org/
13 silly mapToRegistry data Result {
13 silly mapToRegistry   raw: 'cordova',
13 silly mapToRegistry   scope: null,
13 silly mapToRegistry   escapedName: 'cordova',
13 silly mapToRegistry   name: 'cordova',
13 silly mapToRegistry   rawSpec: '',
13 silly mapToRegistry   spec: 'latest',
13 silly mapToRegistry   type: 'tag' }
14 silly mapToRegistry uri https://registry.npmjs.org/cordova
15 silly fetchNamedPackageData ionic
16 silly mapToRegistry name ionic
17 silly mapToRegistry using default registry
18 silly mapToRegistry registry https://registry.npmjs.org/
19 silly mapToRegistry data Result {
19 silly mapToRegistry   raw: 'ionic',
19 silly mapToRegistry   scope: null,
19 silly mapToRegistry   escapedName: 'ionic',
19 silly mapToRegistry   name: 'ionic',
19 silly mapToRegistry   rawSpec: '',
19 silly mapToRegistry   spec: 'latest',
19 silly mapToRegistry   type: 'tag' }
20 silly mapToRegistry uri https://registry.npmjs.org/ionic
21 verbose request uri https://registry.npmjs.org/cordova
22 verbose request no auth needed
23 info attempt registry request try #1 at 4:33:10 PM
24 verbose request id 5fcff5c6006e94b8
25 http request GET https://registry.npmjs.org/cordova
26 verbose request uri https://registry.npmjs.org/ionic
27 verbose request no auth needed
28 info attempt registry request try #1 at 4:33:10 PM
29 http request GET https://registry.npmjs.org/ionic
30 info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=connect ETIMEDOUT 74.122.238.10:8080
31 info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=connect ETIMEDOUT 74.122.238.10:8080
32 info attempt registry request try #2 at 4:34:35 PM
33 http request GET https://registry.npmjs.org/cordova
34 info attempt registry request try #2 at 4:34:35 PM
35 http request GET https://registry.npmjs.org/ionic
36 info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=connect ETIMEDOUT 74.122.238.10:8080
37 info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=connect ETIMEDOUT 74.122.238.10:8080
38 info attempt registry request try #3 at 4:36:51 PM
39 http request GET https://registry.npmjs.org/ionic
40 info attempt registry request try #3 at 4:36:51 PM
41 http request GET https://registry.npmjs.org/cordova
42 silly fetchPackageMetaData Error: tunneling socket could not be established, cause=connect ETIMEDOUT 74.122.238.10:8080
42 silly fetchPackageMetaData     at ClientRequest.onError (/usr/local/lib/node_modules/npm/node_modules/request/node_modules/tunnel-agent/index.js:176:17)
42 silly fetchPackageMetaData     at ClientRequest.g (events.js:291:16)
42 silly fetchPackageMetaData     at emitOne (events.js:96:13)
42 silly fetchPackageMetaData     at ClientRequest.emit (events.js:188:7)
42 silly fetchPackageMetaData     at Socket.socketErrorListener (_http_client.js:310:9)
42 silly fetchPackageMetaData     at emitOne (events.js:96:13)
42 silly fetchPackageMetaData     at Socket.emit (events.js:188:7)
42 silly fetchPackageMetaData     at emitErrorNT (net.js:1278:8)
42 silly fetchPackageMetaData     at _combinedTickCallback (internal/process/next_tick.js:74:11)
42 silly fetchPackageMetaData     at process._tickCallback (internal/process/next_tick.js:98:9)
42 silly fetchPackageMetaData  error for cordova { Error: tunneling socket could not be established, cause=connect ETIMEDOUT 74.122.238.10:8080
42 silly fetchPackageMetaData     at ClientRequest.onError (/usr/local/lib/node_modules/npm/node_modules/request/node_modules/tunnel-agent/index.js:176:17)
42 silly fetchPackageMetaData     at ClientRequest.g (events.js:291:16)
42 silly fetchPackageMetaData     at emitOne (events.js:96:13)
42 silly fetchPackageMetaData     at ClientRequest.emit (events.js:188:7)
42 silly fetchPackageMetaData     at Socket.socketErrorListener (_http_client.js:310:9)
42 silly fetchPackageMetaData     at emitOne (events.js:96:13)
42 silly fetchPackageMetaData     at Socket.emit (events.js:188:7)
42 silly fetchPackageMetaData     at emitErrorNT (net.js:1278:8)
42 silly fetchPackageMetaData     at _combinedTickCallback (internal/process/next_tick.js:74:11)
42 silly fetchPackageMetaData     at process._tickCallback (internal/process/next_tick.js:98:9) code: 'ECONNRESET' }
43 silly fetchPackageMetaData Error: tunneling socket could not be established, cause=connect ETIMEDOUT 74.122.238.10:8080
43 silly fetchPackageMetaData     at ClientRequest.onError (/usr/local/lib/node_modules/npm/node_modules/request/node_modules/tunnel-agent/index.js:176:17)
43 silly fetchPackageMetaData     at ClientRequest.g (events.js:291:16)
43 silly fetchPackageMetaData     at emitOne (events.js:96:13)
43 silly fetchPackageMetaData     at ClientRequest.emit (events.js:188:7)
43 silly fetchPackageMetaData     at Socket.socketErrorListener (_http_client.js:310:9)
43 silly fetchPackageMetaData     at emitOne (events.js:96:13)
43 silly fetchPackageMetaData     at Socket.emit (events.js:188:7)
43 silly fetchPackageMetaData     at emitErrorNT (net.js:1278:8)
43 silly fetchPackageMetaData     at _combinedTickCallback (internal/process/next_tick.js:74:11)
43 silly fetchPackageMetaData     at process._tickCallback (internal/process/next_tick.js:98:9)
43 silly fetchPackageMetaData  error for ionic { Error: tunneling socket could not be established, cause=connect ETIMEDOUT 74.122.238.10:8080
43 silly fetchPackageMetaData     at ClientRequest.onError (/usr/local/lib/node_modules/npm/node_modules/request/node_modules/tunnel-agent/index.js:176:17)
43 silly fetchPackageMetaData     at ClientRequest.g (events.js:291:16)
43 silly fetchPackageMetaData     at emitOne (events.js:96:13)
43 silly fetchPackageMetaData     at ClientRequest.emit (events.js:188:7)
43 silly fetchPackageMetaData     at Socket.socketErrorListener (_http_client.js:310:9)
43 silly fetchPackageMetaData     at emitOne (events.js:96:13)
43 silly fetchPackageMetaData     at Socket.emit (events.js:188:7)
43 silly fetchPackageMetaData     at emitErrorNT (net.js:1278:8)
43 silly fetchPackageMetaData     at _combinedTickCallback (internal/process/next_tick.js:74:11)
43 silly fetchPackageMetaData     at process._tickCallback (internal/process/next_tick.js:98:9) code: 'ECONNRESET' }
44 silly rollbackFailedOptional Starting
45 verbose stack TypeError: Cannot read property 'path' of null
45 verbose stack     at Object.Installer.rollbackFailedOptional (/usr/local/lib/node_modules/npm/lib/install.js:511:29)
45 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
45 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
45 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
45 verbose stack     at /usr/local/lib/node_modules/npm/lib/install.js:337:5
45 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
45 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
45 verbose stack     at chain (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
45 verbose stack     at /usr/local/lib/node_modules/npm/lib/install.js:294:5
45 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:16:22
46 verbose cwd /Users/ahmedkhalid
47 error Darwin 16.4.0
48 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "cordova" "ionic"
49 error node v6.9.5
50 error npm  v4.1.2
51 error Cannot read property 'path' of null
52 error If you need help, you may report this error at:
52 error     <https://github.com/npm/npm/issues>
53 verbose exit [ 1, true ]

**Comment by Alohaliu** [comment]
if you are in china without VPN, just try this way:

npm config set registry https://registry.npm.taobao.org
