### ISSUE TITLE
@angular/cli is failing to install because Invalid name: "@ngtools/webpack"

### ISSUE THREAD

**Issue by Nexlen** [npm/npm#15798]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

sudo npm install i -g @angular/cli is failing to complete do to Invalid name: "@ngtools/webpack"

#### How can the CLI team reproduce the problem?

attempt to run the script above.

### supporting information:

 - `npm -v` prints:  4.1.2 
 - `node -v` prints: v7.5.0
 - `npm config get registry` prints:https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: OS X El Capitan 
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by watilde** [comment]
Hello! We need more information to investigate. Could you fill `supporting information` section in your description?

**Comment by Nexlen** [comment]
Updated.

**Comment by Nexlen** [comment]
Seems like some resolution problem. Now I get: Invalid name: "@angular-cli/base-href-webpack"

**Comment by KenanY** [comment]
@Nexlen Could you upload the resulting log file to <https://gist.github.com/> and post the link here?

**Comment by Nexlen** [comment]
https://gist.github.com/Nexlen/89e04ad8d3b64c604cd9dd44c8abeb4c

**Comment by Nexlen** [comment]
Read this issue and followed the last comment. Uninstalled node completed and reinstalled 7.5 which fixed my issues.
https://github.com/npm/npm/issues/14268
