### ISSUE TITLE
npm doesn't creating node_modules folder under project directory

### ISSUE THREAD

**Issue by SathishKannan** [npm/npm#15795]
Hi,

I'm new to npm, I tried installing nodejs version 4 and cloned a project from GitHub.

Find below steps I did through command prompt,

npm init -> package.json created successfully.

npm install react --save --> installing packaging modules directly under project directory (on the same level of src dir) and not creating node_modules folder.

And also when I try to install tarball file it is not installing.

npm install -g node-notifier-4.6.1.tgz --> not working.

I have this file downloaded and placed inside project folder.

Can anyone please help

Thanks

**Comment by KenanY** [comment]
@SathishKannan `npm --version`?

**Comment by SathishKannan** [comment]
@KenanY it's 4.0.3

**Comment by KenanY** [comment]
I unfortunately cannot reproduce this.

<details>

```bash
$ npm init -y
Wrote to /tmp/npm-15795/package.json:

{
  "name": "npm-15795",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}

$ npm install react --save
npm-15795@1.0.0 /tmp/npm-15795
└─┬ react@15.4.2 
  ├─┬ fbjs@0.8.9 
  │ ├── core-js@1.2.7 
  │ ├─┬ isomorphic-fetch@2.2.1 
  │ │ ├─┬ node-fetch@1.6.3 
  │ │ │ ├─┬ encoding@0.1.12 
  │ │ │ │ └── iconv-lite@0.4.15 
  │ │ │ └── is-stream@1.1.0 
  │ │ └── whatwg-fetch@2.0.2 
  │ ├─┬ promise@7.1.1 
  │ │ └── asap@2.0.5 
  │ ├── setimmediate@1.0.5 
  │ └── ua-parser-js@0.7.12 
  ├─┬ loose-envify@1.3.1 
  │ └── js-tokens@3.0.1 
  └── object-assign@4.1.1 

npm WARN npm-15795@1.0.0 No description
npm WARN npm-15795@1.0.0 No repository field.

$ ls
node_modules  package.json

$ ls node_modules/
asap  core-js  encoding  fbjs  iconv-lite  isomorphic-fetch  is-stream  js-tokens  loose-envify  node-fetch  object-assign  promise  react  setimmediate  ua-parser-js  whatwg-fetch
```

</details>

**Comment by SathishKannan** [comment]
Will this issue get resolve if I update npm version.

Is node_modules folder creation by npm depends on its version?

**Comment by KenanY** [comment]
@SathishKannan I've never seen anyone with this sort of issue, and I've been around since `npm@1.4`. It wouldn't hurt to try updating, but I cannot guarantee it will fix this issue.

**Comment by SathishKannan** [comment]
@KenanY initially I played with "npm config set prefix" that creates this issue, now its get resolved by running command --> npm config set prefix "node_modules"

And for tarball file installation, below command worked fine,

--> npm install -g node-notifier-4.6.1.tgz --save

Thanks for your response.
