### ISSUE TITLE
cordova and ionic installations issues

### ISSUE THREAD

**Issue by ng97** [npm/npm#15791]
#### I'm opening this issue because:

  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
it keeps showing errors
#### How can the CLI team reproduce the problem?
shasum check failed for C:\Users\NGOZIO~1\AppData\Local\Temp\npm-5640-b45719b4\registry.npmjs.org\cordova-app-hello-world\-\cordova-app-hello-world-3.11.0.tgz
[npm-debug.log.docx](https://github.com/npm/npm/files/782897/npm-debug.log.docx)

### supporting information:

 - `npm -v` prints: yes
 - `node -v` prints:yes
 - `npm config get registry` prints: i don't know 
 - Windows, OS X/macOS, or Linux?: Windows

**Comment by legodude17** [comment]
Try updating to the latest version of `npm`.

**Comment by ng97** [comment]
I did, then I tried ionic serve and still got errors

**Comment by legodude17** [comment]
What is the output?

**Comment by ng97** [comment]
This is a snap of the errors, thanks for your help in advance

**Comment by bsc1780** [comment]
<xsd:simpleType name="TypeName">
 <xsd:restriction base="xsd:boolean"/>
</xsd:simpleType>

**Comment by wachukxs** [comment]
ionic is not recognized as an internal or external command ... please how can i fix this, i've tried installing and uninstalling node... it still doesn't work

**Comment by ng97** [comment]
Hey pls do you know what I can do about it now?
