### ISSUE TITLE
Error: EPERM: operation not permitted, rename 'C:\Users\athakur\AppData\Roaming\npm\node_modules\cordova' -> 'C:\Users\athakur\AppData\Roaming\npm\node_modules\.cordova.DELETE'

### ISSUE THREAD

**Issue by thakurameya** [npm/npm#15797]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [3 ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
139987 verbose stack     at moveAway (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:38:5)
139987 verbose stack     at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:27:7)
139987 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:267:18
139987 verbose stack     at FSReqWrap.oncomplete (fs.js:123:15)
139987 verbose stack
139987 verbose stack Error: EPERM: operation not permitted, rename 'C:\Users\athakur\AppData\Roaming\npm\node_modules\cordova' -> 'C:\Users\athakur\AppData\Roaming\npm\node_modules\.cordova.DELETE'
139987 verbose stack     at Error (native)
139988 verbose cwd C:\DEV
139989 error Windows_NT 6.1.7601
139990 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ionic" "cordova"
139991 error node v6.9.5
139992 error npm  v3.10.10
139993 error path C:\Users\athakur\AppData\Roaming\npm\node_modules\cordova
139994 error code EPERM
139995 error errno -4048
139996 error syscall rename
139997 error Error: EPERM: operation not permitted, rename 'C:\Users\athakur\AppData\Roaming\npm\node_modules\cordova' -> 'C:\Users\athakur\AppData\Roaming\npm\node_modules\.cordova.DELETE'
139997 error     at moveAway (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:38:5)
139997 error     at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:27:7)
139997 error     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:267:18
139997 error     at FSReqWrap.oncomplete (fs.js:123:15)
139997 error
139997 error Error: EPERM: operation not permitted, rename 'C:\Users\athakur\AppData\Roaming\npm\node_modules\cordova' -> 'C:\Users\athakur\AppData\Roaming\npm\node_modules\.cordova.DELETE'
139997 error     at Error (native)
139997 error  Error: EPERM: operation not permitted, rename 'C:\Users\athakur\AppData\Roaming\npm\node_modules\cordova' -> 'C:\Users\athakur\AppData\Roaming\npm\node_modules\.cordova.DELETE'
139997 error     at moveAway (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:38:5)
139997 error     at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:27:7)
139997 error     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:267:18
139997 error     at FSReqWrap.oncomplete (fs.js:123:15)
139997 error
139997 error Error: EPERM: operation not permitted, rename 'C:\Users\athakur\AppData\Roaming\npm\node_modules\cordova' -> 'C:\Users\athakur\AppData\Roaming\npm\node_modules\.cordova.DELETE'
139997 error     at Error (native)
139998 error Please try running this command again as root/Administrator.
139999 verbose exit [ -4048, true ]

#### How can the CLI team reproduce the problem?
$ npm install -g ionic cordova

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
Do you have full permissions to `C:\Users\athakur\AppData\Roaming\npm\node_modules`?

**Comment by bsc1780** [comment]
Yes

**Comment by thakurameya** [comment]
Thanks you I have resolved the issue I had to open the cmd prompt as an Administrator and it did not complained after that

**Comment by legodude17** [comment]
@thakurameya that's great!

Can you close this @KenanY?
