### ISSUE TITLE
trying to run npm install <somepackage> but fails

### ISSUE THREAD

**Issue by matsheed** [npm/npm#15792]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints: 3.10.10
 - `node -v` prints: 6.9.5
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows 10
 - Network issues: none
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'angular',
1 verbose cli   '--save' ]
2 info using npm@3.10.10
3 info using node@v6.9.5
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData angular
8 silly fetchNamedPackageData angular
9 silly mapToRegistry name angular
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'angular',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'angular',
12 silly mapToRegistry   name: 'angular',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/angular
14 verbose request uri https://registry.npmjs.org/angular
15 verbose request no auth needed
16 info attempt registry request try #1 at 17:45:56
17 verbose request id 1d6be1180d9aac33
18 http request GET https://registry.npmjs.org/angular
19 info retry will retry, error on last attempt: Error: write EPROTO 101057795:error:140943FC:SSL routines:ssl3_read_bytes:sslv3 alert bad record mac:openssl\ssl\s3_pkt.c:1493:SSL alert number 20
19 info retry 101057795:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:openssl\ssl\s3_pkt.c:659:
20 info attempt registry request try #2 at 17:46:06
21 http request GET https://registry.npmjs.org/angular
22 info retry will retry, error on last attempt: Error: write EPROTO 101057795:error:140943FC:SSL routines:ssl3_read_bytes:sslv3 alert bad record mac:openssl\ssl\s3_pkt.c:1493:SSL alert number 20
22 info retry 101057795:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:openssl\ssl\s3_pkt.c:659:
23 info attempt registry request try #3 at 17:47:06
24 http request GET https://registry.npmjs.org/angular
25 silly fetchPackageMetaData Error: write EPROTO 101057795:error:140943FC:SSL routines:ssl3_read_bytes:sslv3 alert bad record mac:openssl\ssl\s3_pkt.c:1493:SSL alert number 20
25 silly fetchPackageMetaData 101057795:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:openssl\ssl\s3_pkt.c:659:
25 silly fetchPackageMetaData
25 silly fetchPackageMetaData     at exports._errnoException (util.js:1022:11)
25 silly fetchPackageMetaData     at WriteWrap.afterWrite (net.js:801:14)
25 silly fetchPackageMetaData  error for angular { Error: write EPROTO 101057795:error:140943FC:SSL routines:ssl3_read_bytes:sslv3 alert bad record mac:openssl\ssl\s3_pkt.c:1493:SSL alert number 20
25 silly fetchPackageMetaData 101057795:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:openssl\ssl\s3_pkt.c:659:
25 silly fetchPackageMetaData
25 silly fetchPackageMetaData     at exports._errnoException (util.js:1022:11)
25 silly fetchPackageMetaData     at WriteWrap.afterWrite (net.js:801:14) code: 'EPROTO', errno: 'EPROTO', syscall: 'write' }
26 silly rollbackFailedOptional Starting
27 silly rollbackFailedOptional Finishing
28 silly runTopLevelLifecycles Finishing
29 silly install printInstalled
30 verbose stack Error: write EPROTO 101057795:error:140943FC:SSL routines:ssl3_read_bytes:sslv3 alert bad record mac:openssl\ssl\s3_pkt.c:1493:SSL alert number 20
30 verbose stack 101057795:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:openssl\ssl\s3_pkt.c:659:
30 verbose stack
30 verbose stack     at exports._errnoException (util.js:1022:11)
30 verbose stack     at WriteWrap.afterWrite (net.js:801:14)
31 verbose cwd C:\devenv\projects\article
32 error Windows_NT 10.0.14393
33 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "angular" "--save"
34 error node v6.9.5
35 error npm  v3.10.10
36 error code EPROTO
37 error errno EPROTO
38 error syscall write
39 error write EPROTO 101057795:error:140943FC:SSL routines:ssl3_read_bytes:sslv3 alert bad record mac:openssl\ssl\s3_pkt.c:1493:SSL alert number 20
39 error 101057795:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:openssl\ssl\s3_pkt.c:659:
40 error If you need help, you may report this error at:
40 error     <https://github.com/npm/npm/issues>
41 verbose exit [ 1, true ]

**Comment by NicolasJEngler** [comment]
Same issue here, haven't found a solution just yet

**Comment by matsheed** [comment]
Still having the issue...

**Comment by matsheed** [comment]
Solved by installing Nodejs 32bit

**Comment by NicolasJEngler** [comment]
I can confirm that installing a 32-bit version of Node.js is a functional workaround.

**Comment by legodude17** [comment]
Anyone else still having this issue after trying the solution from @matsheed ?

**Comment by tpaustin** [comment]
I was having the same issue and installing the 32-bit version solved it for me as well.
