### ISSUE TITLE
angular2-datatable issue

### ISSUE THREAD

**Issue by tripashi** [npm/npm#15796]
D:\Users\shitripa\angular2-datatable-master>npm i -S angular2-datatable
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "D:\\Users\\shitripa\\AppDat
a\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i" "-S" "angular2-datatabl
e"
npm ERR! node v7.3.0
npm ERR! npm  v4.0.5
npm ERR! code ENOSELF

npm ERR! Refusing to install package with name "angular2-datatable" under a pack
age
npm ERR! also called "angular2-datatable". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR!
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-alg
orithm>
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Users\shitripa\angular2-datatable-master\npm-debug.log

**Comment by KenanY** [comment]
@tripashi The error message explains that you cannot have your package name be the same as any package you are installing. I suggest changing `"name"` to something more unique.
