### ISSUE TITLE
NPM unpublish returns Error 400 (package has 0 downloads / publish less 24h)

### ISSUE THREAD

**Issue by heldrida** [npm/npm#15806]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I wrongly typed `npm publish` in the wrong directory of my project and is now published in NPM and it's not possible to uninstall. I understand there's new policies, but the package exists for less then 24h and have no downloads.

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

Here's the log

`npm unpublish --force reactatouille-boilerplate
npm WARN using --force I sure hope you know what you are doing.
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/Cellar/node/7.4.0/bin/node" "/usr/local/bin/npm" "unpublish" "--force" "reactatouille-boilerplate"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code E400

npm ERR! Registry returned 400 for DELETE on https://registry.npmjs.org/reactatouille-boilerplate/-rev/3-bd5e61e3a9d7c260ae3d8f0421117b59
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Helder/www/reactatouille-boilerplate/template/npm-debug.log`

**Comment by KenanY** [comment]
According to `npm info reactatouille-boilerplate`, that package has existed for a few days now. Of course, I don't know exactly when you ran the `unpublish`, but regardless, you gotta contact `support@npmjs.com` for package unpublishes.
