### ISSUE TITLE
npm installs more files that I have in my package.json (372 total)

### ISSUE THREAD

**Issue by nancagithub** [npm/npm#15800]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by nancagithub** [comment]
I'm following an online tutorial and when we get to the step, "npm install" 
The tutorial loads just 11 folders and my setup installs 372 folders (working from the identical package.json file), giving me a node_modules folder with 10,656 Files, 1,496 Folders. 
I'm looking for a way to only install those indicated in my package.json,
or is there something basic I'm not understanding?

**Comment by KenanY** [comment]
@nancagithub Are you using `npm@>=3`?

**Comment by nancagithub** [comment]
-v    3.10.9
Everything works OK, I just don't understand why it downloaded so many files.  takes up a lot of space.

**Comment by KenanY** [comment]
@nancagithub What you're seeing is the improved deduping procedure that was implemented in `npm@3`. All those modules you see are dependencies of the modules in your `package.json`. This is `npm` working as intended, and in fact in many cases the result takes up less disk space, I think.
