### ISSUE TITLE
package.json script with space in path --> Unexpected token

### ISSUE THREAD

**Issue by JulianKingman** [npm/npm#15801]
#### I'm opening this issue because:

  - [x] npm is doing something I don't understand.

#### What's going wrong?
I have a script that invokes a file from a path that contains a space in it.

#### How can the CLI team reproduce the problem?
Script in question:
`"android-studio": "/Applications/Android\ Studio.app/Contents/MacOS/studio&"`
Is there some other way to escape spaces? I tried removing the backslash, but still no luck :(

### supporting information:

 - `npm -v` prints: v7.0.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: OS X

**Comment by legodude17** [comment]
You need to escape the backslash with another backslash.

**Comment by JulianKingman** [comment]
Lol, classic. https://xkcd.com/1638/

**Comment by legodude17** [comment]
@JulianKingman that's what I was thinking of too.
