### ISSUE TITLE
browser sync is not installing. shows SKIPPING OPTIONAL DEPENDENCY. callback called more than once

### ISSUE THREAD

**Issue by abhishek-saha18** [npm/npm#15802]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by abhishek-saha18** [comment]
the debug file is attached here.
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'browser-sync' ]
2 info using npm@3.10.10
3 info using node@v6.9.5
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData browser-sync
8 silly fetchNamedPackageData browser-sync
9 silly mapToRegistry name browser-sync
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'browser-sync',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'browser-sync',
12 silly mapToRegistry   name: 'browser-sync',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/browser-sync
14 verbose request uri https://registry.npmjs.org/browser-sync
15 verbose request no auth needed
16 info attempt registry request try #1 at 8:03:58 PM
17 verbose request id dce55911e421406f
18 verbose etag W/"58a953ed-8211e"
19 verbose lastModified Sun, 19 Feb 2017 08:14:37 GMT
20 http request GET https://registry.npmjs.org/browser-sync
21 http 304 https://registry.npmjs.org/browser-sync
22 verbose headers { date: 'Sun, 19 Feb 2017 14:33:53 GMT',
22 verbose headers   via: '1.1 varnish',
22 verbose headers   'cache-control': 'max-age=300',
22 verbose headers   etag: 'W/"58a953ed-8211e"',
22 verbose headers   age: '19',
22 verbose headers   connection: 'keep-alive',
22 verbose headers   'x-served-by': 'cache-cdg8724-CDG',
22 verbose headers   'x-cache': 'HIT',
22 verbose headers   'x-cache-hits': '2',
22 verbose headers   'x-timer': 'S1487514833.970531,VS0,VE0',
22 verbose headers   vary: 'Accept-Encoding' }
23 silly get cb [ 304,
23 silly get   { date: 'Sun, 19 Feb 2017 14:33:53 GMT',
23 silly get     via: '1.1 varnish',

**Comment by legodude17** [comment]
What is the bottom 15 lines of `npm-debug.log`?
