### ISSUE TITLE
verbose stack TypeError: Cannot read property 'path' of null

### ISSUE THREAD

**Issue by apoorvbakshi** [npm/npm#15808]
[npm-debug.txt](https://github.com/npm/npm/files/789211/npm-debug.txt)

**Comment by andreivasiletruta** [comment]
I have bumped into a similar error while trying to install grunt-cli through npm on windows machine.
Is there like a quick workaround - considering I might be doing something wrong?

**Comment by andreivasiletruta** [comment]
at least in my case it seems proxy related. I set the proxies for npm and it started to work
from my perspective this can be closed. it depends on you @apoorvbakshi 
Thanks

**Comment by MartinStern** [comment]
I had same problem installing typescript. the solution for me was to use the **cmd** window as **administrator**, or use the Bash terminal installed with git. Both worked for me.

**Comment by legodude17** [comment]
Duplicate of #10686.

**Comment by joluga** [comment]
Check your spelling. I had the error and it was that I was writing 'coffescript' (One 'e') in the install command line.
