### ISSUE TITLE
Transfer ownership of jquery-form package

### ISSUE THREAD

**Issue by kevindb** [npm/npm#15818]
https://www.npmjs.com/package/jquery-form

#### I'm opening this issue because:
  - [X] Other

#### What's going wrong?
The [jquery-form](https://github.com/jquery-form/form) project has changed ownership. I have tried updating the package using `npm publish`, but I don't have permission. The package was initially published to NPM 3 years ago by someone other than the original project owner. How can I take "ownership" of the package on NPM? My NPM username is [kevinmorris](https://www.npmjs.com/~kevinmorris).

Also, the repo URL has changed. Is there anything I need to do to update the URL other than update it in package.json?
OLD:  
`https://github.com/malsup/form.git`  
NEW:
`https://github.com/jquery-form/form.git`

Thank you

**Comment by watilde** [comment]
Hello!

Have you already asked the current [owners](https://www.npmjs.com/package/jquery-form/access)? Basically, this repo is for npm command itself, so I think it's better to follow this step: https://www.npmjs.com/policies/disputes#tldr

**Comment by kevindb** [comment]
Thank you, I had not found that 'disputes' document. I've followed the instructions there to send an email to the current owner and CCed support.
