### ISSUE TITLE
'yo discordbot'

### ISSUE THREAD

**Issue by Lylie87** [npm/npm#15815]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [X ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

qf@qf.co.uk [~/discbot]# yo discordbot

     _-----_     ╭──────────────────────────╮
    |       |    │  Welcome to the shining  │
    |--(o)--|    │   generator-discordbot   │
   `---------´   │        generator!        │
    ( _´U`_ )    ╰──────────────────────────╯
    /___A___\   /
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

? Your bot's username (without the discriminator; you can add this later) HeavyBot
? Your bot's token (you can add this later) MYTOKEN
? Do you need Discord voice support? No, I don't need voice support.
? Send coverage reports to coveralls Yes
? GitHub username or organization lylie87
identical package.json
identical .editorconfig
identical .gitattributes
identical .gitignore
identical lib/index.js
 conflict config.js
? Overwrite config.js? overwrite
    force config.js
identical lib/commands/foo.js
identical lib/modules/clapp-discord/index.js
identical lib/modules/clapp-discord/str-en.js
identical lib/modules/clapp-discord/package.json
 conflict test/index.js
? Overwrite test/index.js? overwrite
    force test/index.js
identical .travis.yml
identical gulpfile.js

                 ╭──────────────────────────╮
     _-----_     │  By the way, if you see  │
    |       |    │   that npm yells "UNMET  │
    |--(o)--|    │ PEER DEPENDENCY" at you, │
   `---------´   │ don't  worry about that; │
    ( _´U`_ )    │    as long as you have   │
    /___A___\   /│    selected the voice    │
     |  ~  |     │    library you want if   │
   __'.___.'__   │    you're using voice    │
 ´   `  |° ´ Y ` │  support, it'll be fine. │
                 ╰──────────────────────────╯

npm WARN prepublish-on-install As of npm@5, `prepublish` scripts will run only for `npm publish`.
npm WARN prepublish-on-install (In npm@4 and previous versions, it also runs for `npm install`.)
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> discbot@0.0.0 prepublish /home10/qf/discbot
> gulp prepublish

[12:45:24] Using gulpfile ~/discbot/gulpfile.js
(node:28310) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[12:45:24] Starting 'nsp'...
[12:45:24] (+) No known vulnerabilities found
[12:45:24] Finished 'nsp' after 464 ms
[12:45:24] Starting 'prepublish'...
[12:45:24] Finished 'prepublish' after 61 μs
npm WARN discbot@0.0.0 license should be a valid SPDX license expression
npm ERR! Linux 2.6.32-642.6.2.el6.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "discord.js" "clapp" "--save"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5

npm ERR! Invalid name: "@types/node"
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home10/qf/discbot/npm-debug.log
Reinitialized existing Git repository in /home10/qf/discbot/.git/

### supporting information:

 - `npm -v` prints: 4.0.5
 - `node -v` prints: v7.4.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Centos 6.8
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
Try reinstalling `npm`.
