### ISSUE TITLE
Please help me

### ISSUE THREAD

**Issue by rsunil92** [npm/npm#15819]
C:\xampp\htdocs\master>npm install exif-js --save
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Sunil Kumar R\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "exif-js" "--save"
npm ERR! node v7.1.0
npm ERR! npm  v3.10.10
npm ERR! code ENOSELF

npm ERR! Refusing to install exif-js as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\xampp\htdocs\master\npm-debug.log

**Comment by KenanY** [comment]
@rsunil92 Make sure your `"name"` property in your `package.json` isn't the same as any of your dependencies. Try changing it to something more unique.

**Comment by rsunil92** [comment]
Thank You
