### ISSUE TITLE
data table run time error

### ISSUE THREAD

**Issue by vipulupadhyay** [npm/npm#15810]
E:\Test\vscode\angular-cli-master>npm start
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\vipul.r.upadhyay
\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.9.5
npm ERR! npm  v4.2.0

npm ERR! missing script: start
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\vipul.r.upadhyay\AppData\Roaming\npm-cache\_logs\2017-02-2
1T06_38_39_135Z-debug.log

=>im not able to start this application
=>i have installed all required things

**Comment by vipulupadhyay** [comment]
[](url)
[2017-02-21T07_16_59_621Z-debug.zip](https://github.com/npm/npm/files/789340/2017-02-21T07_16_59_621Z-debug.zip)

**Comment by KenanY** [comment]
@vipulupadhyay Make sure you've defined a `"start"` script in your `package.json`. See <https://docs.npmjs.com/misc/scripts>.
