### ISSUE TITLE
npm ERR! Error: SSL Error: CERT_UNTRUSTED

### ISSUE THREAD

**Issue by xuzongbao** [npm/npm#15827]
npm ERR! Error: SSL Error: CERT_UNTRUSTED
npm ERR!     at ClientRequest.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/main.js:356:28)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at HTTPParser.onIncoming (http.js:1254:11)
npm ERR!     at HTTPParser.onHeadersComplete (http.js:102:31)
npm ERR!     at CleartextStream.ondata (http.js:1147:24)
npm ERR!     at CleartextStream._push (tls.js:367:27)
npm ERR!     at SecurePair.cycle (tls.js:688:20)
npm ERR!     at EncryptedStream.write (tls.js:122:13)
npm ERR!     at Socket.ondata (stream.js:38:26)
npm ERR!     at Socket.emit (events.js:67:17)

**Comment by KenanY** [comment]
@xuzongbao Please upload the full `npm-debug.log` file to <https://gist.github.com/> and post the link here. Thanks!

**Comment by KenanY** [comment]
Closing due to lack of any response. This is probably a proxy or firewall related issue anyways.
