### ISSUE TITLE
'bash' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by hrc7505** [npm/npm#15829]
i have an error in installing react-flux-starter-kit-windows.
i have installed latest node.js and npm
when i am using this command :
**npm install -g react-flux-starter-kit**
it gives me following error
> react-flux-starter-kit@1.1.4 postinstall C:\Users\Hardik\AppData\Roaming\npm\node_modules\react-flux-starter-kit
> bash setup.sh

'bash' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Hardik\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "react-flux-starter-kit"
npm ERR! node v6.9.5
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! react-flux-starter-kit@1.1.4 postinstall: `bash setup.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-flux-starter-kit@1.1.4 postinstall script 'bash setup.sh'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-flux-starter-kit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bash setup.sh
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-flux-starter-kit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-flux-starter-kit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Hardik\AppData\Roaming\npm-cache\_logs\2017-02-22T10_01_48_356Z-debug.log

please help me how can i run the flux with typescript-react

**Comment by KenanY** [comment]
@hrc7505 Looks like you need `bash` installed to run that `npm` script, which might be difficult to do on Windows. I'm gonna close this since this is not an issue with `npm` itself. If you need more help with that starter kit itself, please ask the author instead.

**Comment by hrc7505** [comment]
thanks @KenanY for quick answer. I am really grateful to you.  Thanks again

**Comment by KenanY** [comment]
@hrc7505 No idea.

**Comment by hrc7505** [comment]
@KenanY  ok no problem sir
