### ISSUE TITLE
Post test command not being run when using singleRun=false

### ISSUE THREAD

**Issue by joashmusyoka** [npm/npm#15826]
#### I'm opening this issue because:

  - [ ] npm is not behaving correctly

#### How can the CLI team reproduce the problem?

I have the following pre-test, test, post-test commands

"pretest": "SET NODE_ENV=development && tsc"
"test": "concurrently  \"npm run tsc:w\" \"karma start karma.conf.js\""
"posttest": "npm run remap"

### supporting information:

- The pre test command runs as expected, then the tests are run
- I am using karma test runner with karma-coverage plugin and remap-istanbull to remap from js to ts.
- I would like to always run the remap command after the tests so as to update the coverage report.

**Comment by KenanY** [comment]
@joashmusyoka Could you provide a minimal `package.json` file I can use to reproduce this issue?

**Comment by bsc1780** [comment]
No prob

**Comment by joashmusyoka** [comment]
@KenanY I think i understand why the above problem is happening. When I start karma with singleRun = true, then karma runs the tests and exits with status code 0 hence the test command is considered finished thus the post test is executed. On the other hand when karma is started with singleRun = false, it never exits and so the test command is never considered done hence post test will not run

**Comment by KenanY** [comment]
@joashmusyoka Glad you figured it out. I'll close this then.

**Comment by joashmusyoka** [comment]
I still would like to run the post test command when running karma in a continuous mode.

**Comment by bsc1780** [comment]
Riwr https://chocolatey.org/install.ps1 -UseBasicParsing | iex

**Comment by bsc1780** [comment]
Run it

**Comment by bsc1780** [comment]
Im working on running it.
