### ISSUE TITLE
npm install ERR! code E500

### ISSUE THREAD

**Issue by thisisjingjing** [npm/npm#15838]
### I ran a gradle build of our project, and it failed with the same reason on both Window7 and Ubuntu.
Here is the link of the [npm-debug.log](https://gist.github.com/thisisjingjing/044ec86cd592f2a2e33d878b98dc48b5 )

### The console output is:
_:npmSetupnpm ERR! Linux 4.4.0-21-generic
npm ERR! argv "/home/jingjli/APMworkspace/epc-apm-web/node-v6.2.0-linux-x64/bin/node" "/home/jingjli/APMworkspace/epc-apm-web/node-v6.2.0-linux-x64/lib/node_modules/npm/bin/npm-cli.js" "install" "npm@3.8.9"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code E500

npm ERR! 500 Internal Server Error
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jingjli/APMworkspace/epc-apm-web/npm-debug.log
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':npmSetup'.
> Process 'command '/home/jingjli/APMworkspace/epc-apm-web/node-v6.2.0-linux-x64/bin/node'' finished with non-zero exit value 1_

**Comment by legodude17** [comment]
What is the result of `npm config get registry`?

**Comment by thisisjingjing** [comment]
The issue is caused by unstable network. Will close it.
