### ISSUE TITLE
npm ERR! Error: No compatible version found: lodash@'^4.14.0'

### ISSUE THREAD

**Issue by wanggaolin** [npm/npm#15835]
npm http GET https://registry.npmjs.org/zookeeper
npm http 304 https://registry.npmjs.org/zookeeper
npm WARN engine zookeeper@3.4.9-3: wanted: {"node":">=0.10"} (current: {"node":"v0.8.14","npm":"1.1.65"})
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/nan
npm http GET https://registry.npmjs.org/lodash
npm http 304 https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/lodash
npm http 304 https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/lodash
npm http 304 https://registry.npmjs.org/lodash
npm ERR! Error: No compatible version found: lodash@'^4.14.0'
npm ERR! Valid install targets:
npm ERR! ["0.1.0","0.2.0","0.2.1","0.2.2","0.3.0","0.3.1","0.3.2","0.4.0","0.4.1","0.4.2","0.5.0-rc.1","0.5.0","0.5.1","0.5.2","0.6.0","0.6.1","0.7.0","0.8.0","0.8.1","0.8.2","0.9.0","0.9.1","0.9.2","0.10.0","1.0.0-rc.1","1.0.0-rc.2","1.0.0-rc.3","1.0.0","1.0.1","1.1.0","1.1.1","1.2.0","1.2.1","1.3.0","1.3.1","2.0.0","2.1.0","2.2.0","2.2.1","2.3.0","2.4.0","2.4.1","3.0.0","3.0.1","3.1.0","3.2.0","3.3.0","3.3.1","3.4.0","3.5.0","3.6.0","1.0.2","3.7.0","2.4.2","3.8.0","3.9.0","3.9.1","3.9.2","3.9.3","3.10.0","3.10.1","4.0.0","4.0.1","4.1.0","4.2.0","4.2.1","4.3.0","4.4.0","4.5.0","4.5.1","4.6.0","4.6.1","4.7.0","4.8.0","4.8.1","4.8.2","4.9.0","4.10.0","4.11.0","4.11.1","4.11.2","4.12.0","4.13.0","4.13.1","4.14.0","4.14.1","4.14.2","4.15.0","4.16.0","4.16.1","4.16.2","4.16.3","4.16.4","4.16.5","4.16.6","4.17.0","4.17.1","4.17.2","4.17.3","4.17.4"]
npm ERR!     at installTargetsError (/usr/local/nodejs/lib/node_modules/npm/lib/cache.js:563:10)
npm ERR!     at /usr/local/nodejs/lib/node_modules/npm/lib/cache.js:478:10
npm ERR!     at saved (/usr/local/nodejs/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at /usr/local/nodejs/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:218:7
npm ERR!     at Object.oncomplete (fs.js:297:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-431.el6.x86_64
npm ERR! command "/usr/local/nodejs/bin/node" "/usr/local/nodejs/bin/npm" "install" "-g" "zookeeper"
npm ERR! cwd /usr/local/node-zk-browser
npm ERR! node -v v0.8.14
npm ERR! npm -v 1.1.65
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /usr/local/node-zk-browser/npm-debug.log
npm ERR! not ok code 0

**this error ndee run : "npm install -d lodash@4.14.0",But still wrong
How can I solve this mistake？thanks**

**Comment by legodude17** [comment]
`npm@1.1.65` is very old and no longer supported. Please update to `npm@4.3.0`

**Comment by KenanY** [comment]
Closing since this is certainly an issue with ancient versions of `npm`.
