### ISSUE TITLE
Trouble installing nodeschool module

### ISSUE THREAD

**Issue by sangeethakp** [npm/npm#15832]
#### I'm opening this issue because:

  - npm is producing an incorrect install.
  
#### What's going wrong?
  - While installing the learnyounode by executing npm install learnyounode -g ,
	Mac OSX users come acrss the following error:

	Error: EMFILE on OSX when requiring lots of files

	Reason for this error is you can't require more than 255 files on OSX.

	Fix: ulimit -n 2560
	This command allows you to display and set resource limits for users.

	  
#### How can the CLI team reproduce the problem?
  - Try Installing the [learnyounode](https://github.com/workshopper/learnyounode) module in Mac OSX El Captain
  - Node Version v0.10.36
  -	npm Version 1.4.28

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@sangeethakp Does this also occur with newer versions of Node.js and `npm`?

**Comment by KenanY** [comment]
Closing due to lack of response.
