### ISSUE TITLE
error i need solution 

### ISSUE THREAD

**Issue by greatpablo** [npm/npm#15834]
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "bower"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10

npm ERR! error:0906D06C:PEM routines:PEM_read_bio:no start line
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\fernando\npm-debug.log

**Comment by tjwebb** [comment]
At the bottom of your error message, it says:
> npm ERR! Please include the following file with any support request:
npm ERR! C:\Users\fernando\npm-debug.log

Can you please provide this?

**Comment by amandeepmittal** [comment]
Refer to #10897 & #8803
