### ISSUE TITLE
Npm install got stuck at fetchMetadata

### ISSUE THREAD

**Issue by rajendrankunjupillai** [npm/npm#15842]
I am getting this issue while installing the npm- npm install -g @angular/cli, 
I am using the node version v6.10.0
When I stopped the installation I got lot of exception find the listed below.

17219 error Windows_NT 6.1.7601
17220 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli"
17221 error node v6.10.0
17222 error npm  v3.10.10
17223 error code ENOSYS
17224 error errno ENOSYS
17225 error syscall kill
17226 error kill ENOSYS
17227 error If you need help, you may report this error at:
17227 error     <https://github.com/npm/npm/issues>
17228 verbose exit [ 1, true ]

**Comment by legodude17** [comment]
Can you put `npm-debug.log` in a gist and then post it?

**Comment by rajendrankunjupillai** [comment]
[npm-debug-error.txt](https://github.com/npm/npm/files/798383/npm-debug-error.txt)

Please find the npn debug file.

**Comment by rajendrankunjupillai** [comment]
I have stop and again trying to install npm, still getting the same issue.. Npm install is not getting complete.

**Comment by rajendrankunjupillai** [comment]
When I open the node js command prompt, I am getting below error. If you aware of this please help me to resolve this error.

npm ERR! Windows_NT 6.1.7601
 npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
 node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli"
 npm ERR! node v6.10.0
 npm ERR! npm  v3.10.10
 npm ERR! code ETIMEDOUT
 npm ERR! errno ETIMEDOUT
 npm ERR! syscall connect

npm ERR! network connect ETIMEDOUT 74.122.238.10:8080
 npm ERR! network This is most likely not a problem with npm itself
 npm ERR! network and is related to network connectivity.
 npm ERR! network In most cases you are behind a proxy or have bad network settin
 gs.
 npm ERR! network
 npm ERR! network If you are behind a proxy, please make sure that the
 npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
 npm ERR!     D:\Development\Angular2\VS-Project\Angular2WithVS2015\npm-debug.log

**Comment by legodude17** [comment]
This is probably a problem with you internet connection or proxy.
