### ISSUE TITLE
Can't install nativescript in windows

### ISSUE THREAD

**Issue by BhuvaneswariVajravel** [npm/npm#15844]
i installed node js and npm in my system. i check the version also. but come to npm install -g nativescript or npm install i got the following error,

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v7.6.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! npm@4.1.2 prepublish: `node bin/npm-cli.js prune --prefix=. --no-global
 && rimraf test/*/*/node_modules && make doc-clean && make -j4 doc`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the npm@4.1.2 prepublish script 'node bin/npm-cli.js prune --
prefix=. --no-global && rimraf test/*/*/node_modules && make doc-clean && make -
j4 doc'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the npm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node bin/npm-cli.js prune --prefix=. --no-global && rimraf test/*/*
/node_modules && make doc-clean && make -j4 doc
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs npm
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls npm
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\user_name\npm-debug.log

i dont know what is the problem, any one know the solution thanks in advance.

**Comment by legodude17** [comment]
Is there any output above that from the script?

**Comment by BhuvaneswariVajravel** [comment]
no i got this much only legodude17

**Comment by BhuvaneswariVajravel** [comment]
can u pls check this for other issue
http://stackoverflow.com/questions/42432811/gradlew-bat-failed-with-exit-code-1

**Comment by legodude17** [comment]
What is the contents of your `package.json`?

**Comment by BhuvaneswariVajravel** [comment]
I don't know that details in office machine 
I can't get now

Can u give me ur mail I'd

http://stackoverflow.com/questions/42432811/gradlew-bat-failed-with-exit-code-1
And this is my recent issue which drive me mad 
Can u please check it
If u find the solution I m really thankful

**Comment by legodude17** [comment]
The stackoverflow link you posted has a problem that is not related to `npm`.

**Comment by BhuvaneswariVajravel** [comment]
Ho.....

Thanks logodude
