### ISSUE TITLE
Change the default license to MIT

### ISSUE THREAD

**Issue by franciscop** [npm/npm#15845]
#### What's the feature?

The preferred license for NPM packages is most likely MIT. So make the life of developers a little bit easier by offering that as the default as the ISC is not so known and might be confusing/lead to higher % of errors.

Note: some licenses like GPL might be misrepresented because larger corporations avoid it probably more than smaller ones, but I do not have the tools to truly check what license is most used in NPM so we'll have to do with the "top NPM libraries" for my report.

#### What problem is the feature intended to solve?

The default license ISC is unknown to developers for NPM and not the most used one even when it's a default. You can check this by running `legally` for the top 10 packages:

```js
npm install legally -g
legally browserify grunt-cli bower gulp grunt express npm cordova forever less
```

![mit](https://cloud.githubusercontent.com/assets/2801252/23262893/9ee61c4a-f9dc-11e6-9c6b-84b27792f9f7.png)

#### Is the absence of this feature blocking you or your team? If so, how?

No

#### Is this feature similar to an existing feature in another tool?

No

#### Is this a feature you're prepared to implement, with support from the npm CLI team?

Yes

**Comment by franciscop** [comment]
This issue is literally changing 3 characters and might improve the development workflow and legal for many teams. It is fixing a default that should never have been made a default to set another one that the community clearly prefers.

Please, fix this instead of closing it. I am making a PR with this functionality.

**Comment by leonadler** [comment]
Setting the bot to close after 7 days is a bit overzealous, IMHO.

**Comment by wangpung12** [comment]
Good
