### ISSUE TITLE
Install dependencies from any block

### ISSUE THREAD

**Issue by najamkhn** [npm/npm#15840]
I've had some sort of situation where I want to only upgrade certain private dependencies and do not want to upgrade everything else. Is there something like this possible with npm?

```
  "dependencies": {
    "chalk": "^1.1.3",
    "express": "^4.14.0",
    "ramda": "^0.23.0",
    "request": "^2.79.0"
  }, 
  "devDependencies": {
    "foo": "^1.1.3",
  }, 
  "blockX": {
    "packageX": "*"
  }
```

I want to just upgrade the repositories in blockX, something like `npm install --blockX`

**Comment by legodude17** [comment]
Why don't you want `packageX` in your `dependencies` field? Also, you could just install again, because you are depending on the latest version.

**Comment by najamkhn** [comment]
@legodude17 because if I want to partially update certain local packages then I can do something like this: `npm upgrade --blockX` without updating the rest which I want to lock on a certain version.

**Comment by legodude17** [comment]
Ah, so you want to upgrade all dependencies except the ones you choose. There is no easy way built into `npm` for that, but it wouldn't be too hard to write a script to do it for you.
