### ISSUE TITLE
Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by eappell** [npm/npm#15847]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
When I attempt an npm install it fails with the error in the subject.  Some package is responding with an HTML page displaying the 403 error, which is trying to parse as JSON and cannot.

#### How can the CLI team reproduce the problem?

Updated node to the LTS 6.9.5 (Windows 10)
Uninstalled angular-cli
Cleaned the npm cache
Installed the latest build of angular-cli and save to my dev dependencies
Deleted my node_modules folder
Ran npm install
Process fails with the error above (see gist below for debug file)

Even though I have my proxy disabled in IE settings, I also tried to set the https-proxy, https_proxy and proxy in npm config to our internal proxy (all set to the same http url), but when I do that I get an error saying "Error: tunneling socket could not be established, statusCode=407".

npm-debug.log with no proxy settings set:
https://gist.github.com/eappell/a22db67db7efedcb9a000d5c3f357487

npm-debug.log with proxy settings set:
https://gist.github.com/eappell/c3d22f1b2b5443535f9407b5fdff75e7

### supporting information:

 - `npm -v` prints: 3.10.10
 - `node -v` prints: 6.9.5
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?:  Windows 10
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [x] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by waar19** [comment]
I'm delete package-lock.json, this work for me.

**Comment by zhangtiantian10** [comment]
@waar19 I can't find package-lock.json
