### ISSUE TITLE
Cannot read property 'path' of null

### ISSUE THREAD

**Issue by divanvb** [npm/npm#15849]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ x] npm is producing an incorrect install.
  - [x ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

I know there are multiple issues opened but none of them had a solution for my problem!

After updating to 7.6.0 on Ubuntu 16.10, whenever I install a package via npm I get the following error: Cannot read property 'path' of null

Log file: 

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'i', '-g', 'yo' ]
2 info using npm@4.1.2
3 info using node@v7.6.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData yo
8 silly fetchNamedPackageData yo
9 silly mapToRegistry name yo
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'yo',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'yo',
12 silly mapToRegistry   name: 'yo',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/yo
14 verbose request uri https://registry.npmjs.org/yo
15 verbose request no auth needed
16 info attempt registry request try #1 at 1:05:39 AM
17 verbose request id b09d80e9dbb8d843
18 http request GET https://registry.npmjs.org/yo
19 info retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
20 info attempt registry request try #2 at 1:05:56 AM
21 http request GET https://registry.npmjs.org/yo
22 info retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
23 info attempt registry request try #3 at 1:06:57 AM
24 http request GET https://registry.npmjs.org/yo
25 silly fetchPackageMetaData Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
25 silly fetchPackageMetaData     at errnoException (dns.js:28:10)
25 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
25 silly fetchPackageMetaData  error for yo { Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
25 silly fetchPackageMetaData     at errnoException (dns.js:28:10)
25 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
25 silly fetchPackageMetaData   code: 'ENOTFOUND',
25 silly fetchPackageMetaData   errno: 'ENOTFOUND',
25 silly fetchPackageMetaData   syscall: 'getaddrinfo',
25 silly fetchPackageMetaData   hostname: 'registry.npmjs.org',
25 silly fetchPackageMetaData   host: 'registry.npmjs.org',
25 silly fetchPackageMetaData   port: 443 }
26 silly rollbackFailedOptional Starting
27 verbose stack TypeError: Cannot read property 'path' of null
27 verbose stack     at Installer.rollbackFailedOptional (/usr/lib/node_modules/npm/lib/install.js:511:29)
27 verbose stack     at Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
27 verbose stack     at LOOP (/usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
27 verbose stack     at /usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
27 verbose stack     at /usr/lib/node_modules/npm/lib/install.js:337:5
27 verbose stack     at Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
27 verbose stack     at LOOP (/usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
27 verbose stack     at chain (/usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
27 verbose stack     at /usr/lib/node_modules/npm/lib/install.js:294:5
27 verbose stack     at /usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:16:22
28 verbose cwd /home/superman
29 error Linux 4.8.0-39-generic
30 error argv "/usr/bin/nodejs" "/usr/bin/npm" "i" "-g" "yo"
31 error node v7.6.0
32 error npm  v4.1.2
33 error Cannot read property 'path' of null
34 error If you need help, you may report this error at:
34 error     <https://github.com/npm/npm/issues>
35 verbose exit [ 1, true ]

@addaleax

**Comment by addaleax** [comment]
Actualy, `getaddrinfo ENOTFOUND registry.npmjs.org` suggest there’s something up with your network, which might mean that your failure was only temporary (or something’s off with your network settings). The `Cannot read property 'path' of null` error still looks weird…

**Comment by divanvb** [comment]
I don't know how It might be an error with my network as I am behind no proxy and no settings have been changed since yesterday which I was still managing to install packages.

The path property is also very weird to me and google has not given me any solutions and I've look at most of the forums where users posted such an issue.

**Comment by divanvb** [comment]
Okay so I've just disconnected from my home network and connected to my phone which is my mobile hot spot. I am able to install packages now but even after restarting the router etc, the problem still persist. It's very strange!

**Comment by MohsinGhani** [comment]
i also have this error,
npm ERR! addLocal Could not install c:users/mohsin
npm ERR! Windows_NT 6.1.7601

npm ERR! Cannot read property 'path' of null
npm ERR!
npm error If you need help, you may report this error at:
npm error https://github.com/npm/npm/issues

**Comment by legodude17** [comment]
Could one of you try putting a `console.log(this.currentTree)` above `var top = this.currentTree && this.currentTree.path` in `npm/lib/install.js:511`.

**Comment by kfaiad** [comment]
i also have this issue 
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "-g" "install" "bower-npm-install"
npm ERR! node v7.6.0
npm ERR! npm  v4.1.2

npm ERR! Cannot read property 'path' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\faiad\npm-debug.log

**Comment by bwojtowi** [comment]
I added the line `console.log(this.currentTree)` as legodude17 asked but I got the same output.

PS C:\Windows\system32> npm install -g autorest
null...............] | normalizeTree: sill install loadCurrentTree
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "autores
npm ERR! node v7.6.0
npm ERR! npm  v4.1.2

npm ERR! Cannot read property 'path' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Windows\system32\npm-debug.log

**Comment by legodude17** [comment]
@bwojtowi really? Nothing in you terminal from the log?

**Comment by kangjoni76** [comment]
same for me, here is npm-debug.log says:

````
0 info it worked if it ends with ok
1 verbose cli [ '/opt/node7install/node',
1 verbose cli   '/opt/node7install/cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'haraka' ]
2 info using npm@4.1.2
3 info using node@v7.6.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData haraka
8 silly fetchNamedPackageData haraka
9 silly mapToRegistry name haraka
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'haraka',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'haraka',
12 silly mapToRegistry   name: 'haraka',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/haraka
14 verbose request uri https://registry.npmjs.org/haraka
15 verbose request no auth needed
16 info attempt registry request try #1 at 06.07.23
17 verbose request id d7b3fef7a7b8937e
18 http request GET https://registry.npmjs.org/haraka
19 http 404 https://registry.npmjs.org/haraka
20 verbose headers { 'content-type': 'application/json',
20 verbose headers   'cache-control': 'max-age=0',
20 verbose headers   'content-length': '2',
20 verbose headers   'accept-ranges': 'bytes',
20 verbose headers   date: 'Wed, 01 Mar 2017 23:07:26 GMT',
20 verbose headers   via: '1.1 varnish',
20 verbose headers   connection: 'keep-alive',
20 verbose headers   'x-served-by': 'cache-sin6920-SIN',
20 verbose headers   'x-cache': 'MISS',
20 verbose headers   'x-cache-hits': '0',
20 verbose headers   'x-timer': 'S1488409645.292350,VS0,VE973',
20 verbose headers   vary: 'Accept-Encoding' }
21 silly get cb [ 404,
21 silly get   { 'content-type': 'application/json',
21 silly get     'cache-control': 'max-age=0',
21 silly get     'content-length': '2',
21 silly get     'accept-ranges': 'bytes',
21 silly get     date: 'Wed, 01 Mar 2017 23:07:26 GMT',
21 silly get     via: '1.1 varnish',
21 silly get     connection: 'keep-alive',
21 silly get     'x-served-by': 'cache-sin6920-SIN',
21 silly get     'x-cache': 'MISS',
21 silly get     'x-cache-hits': '0',
21 silly get     'x-timer': 'S1488409645.292350,VS0,VE973',
21 silly get     vary: 'Accept-Encoding' } ]
22 silly fetchPackageMetaData Error: Registry returned 404 for GET on https://registry.npmjs.org/haraka
22 silly fetchPackageMetaData     at makeError (/opt/node7install/node_modules/npm-registry-client/lib/request.js:304:12)
22 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (/opt/node7install/node_modules/npm-registry-client/lib/request.js:282:14)
22 silly fetchPackageMetaData     at Request._callback (/opt/node7install/node_modules/npm-registry-client/lib/request.js:212:14)
22 silly fetchPackageMetaData     at Request.self.callback (/opt/node7install/node_modules/request/request.js:186:22)
22 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
22 silly fetchPackageMetaData     at Request.emit (events.js:194:7)
22 silly fetchPackageMetaData     at Request.<anonymous> (/opt/node7install/node_modules/request/request.js:1081:10)
22 silly fetchPackageMetaData     at emitOne (events.js:96:13)
22 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
22 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (/opt/node7install/node_modules/request/request.js:1001:12)
22 silly fetchPackageMetaData  error for haraka { Error: Registry returned 404 for GET on https://registry.npmjs.org/haraka
22 silly fetchPackageMetaData     at makeError (/opt/node7install/node_modules/npm-registry-client/lib/request.js:304:12)
22 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (/opt/node7install/node_modules/npm-registry-client/lib/request.js:282:14)
22 silly fetchPackageMetaData     at Request._callback (/opt/node7install/node_modules/npm-registry-client/lib/request.js:212:14)
22 silly fetchPackageMetaData     at Request.self.callback (/opt/node7install/node_modules/request/request.js:186:22)
22 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
22 silly fetchPackageMetaData     at Request.emit (events.js:194:7)
22 silly fetchPackageMetaData     at Request.<anonymous> (/opt/node7install/node_modules/request/request.js:1081:10)
22 silly fetchPackageMetaData     at emitOne (events.js:96:13)
22 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
22 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (/opt/node7install/node_modules/request/request.js:1001:12) pkgid: 'haraka', statusCode: 404, code: 'E404' }
23 silly rollbackFailedOptional Starting
24 verbose stack TypeError: Cannot read property 'path' of null
24 verbose stack     at Installer.rollbackFailedOptional (/opt/node7install/lib/install.js:511:29)
24 verbose stack     at Array.<anonymous> (/opt/node7install/node_modules/slide/lib/bind-actor.js:15:8)
24 verbose stack     at LOOP (/opt/node7install/node_modules/slide/lib/chain.js:15:14)
24 verbose stack     at /opt/node7install/node_modules/slide/lib/chain.js:18:7
24 verbose stack     at /opt/node7install/lib/install.js:337:5
24 verbose stack     at Array.<anonymous> (/opt/node7install/node_modules/slide/lib/bind-actor.js:15:8)
24 verbose stack     at LOOP (/opt/node7install/node_modules/slide/lib/chain.js:15:14)
24 verbose stack     at chain (/opt/node7install/node_modules/slide/lib/chain.js:20:5)
24 verbose stack     at /opt/node7install/lib/install.js:294:5
24 verbose stack     at /opt/node7install/node_modules/slide/lib/chain.js:16:22
25 verbose cwd /opt/node7install
26 error Linux 4.4.0-62-generic
27 error argv "/opt/node7install/node" "/opt/node7install/cli.js" "install" "-g" "haraka"
28 error node v7.6.1
29 error npm  v4.1.2
30 error Cannot read property 'path' of null
31 error If you need help, you may report this error at:
31 error     <https://github.com/npm/npm/issues>
32 verbose exit [ 1, true ]
````
using node v7x-staging branch 
node -v
````
v7.6.1-pre
````

**Comment by legodude17** [comment]
@kangjoni76 please check your internet connection.

**Comment by kangjoni76** [comment]
It's working well, my ubuntu is at guest virtualbox using NAT source internet connection

**Comment by kangjoni76** [comment]
using curl to test https get to the npm registry is working fine:

````
 curl https://registry.npmjs.org/haraka -v
*   Trying 151.101.8.162...
*   Trying 64:ff9c::9765:8a2...
* Immediate connect fail for 64:ff9c::9765:8a2: Network is unreachable
*   Trying 64:ff9b::9765:8a2...
* Immediate connect fail for 64:ff9b::9765:8a2: Network is unreachable
* Connected to registry.npmjs.org (151.101.8.162) port 443 (#0)
* found 173 certificates in /etc/ssl/certs/ca-certificates.crt
* found 696 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
*        server certificate verification OK
*        server certificate status verification SKIPPED
*        common name: npmjs.org (matched)
*        server certificate expiration date OK
*        server certificate activation date OK
*        certificate public key: RSA
*        certificate version: #3
*        subject: businessCategory=Private Organization,serialNumber=5452409,jurisdictionOfIncorporationCountryName=US,jurisdictionOfIncorporationStateOrProvinceName=Delaware,C=US,ST=California,L=Oakland,street=1999 Harrison Street Suite 1150,O=npm\, Inc.,CN=npmjs.org
*        start date: Wed, 23 Mar 2016 18:49:50 GMT
*        expire date: Mon, 14 May 2018 19:06:17 GMT
*        issuer: C=BE,O=GlobalSign nv-sa,CN=GlobalSign Extended Validation CA - SHA256 - G2
*        compression: NULL
* ALPN, server accepted to use http/1.1
> GET /haraka HTTP/1.1
> Host: registry.npmjs.org
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Content-Type: application/json
< Cache-Control: max-age=0
< Content-Length: 2
< Accept-Ranges: bytes
< Date: Wed, 01 Mar 2017 23:19:15 GMT
< Via: 1.1 varnish
< Age: 0
< Connection: keep-alive
< X-Served-By: cache-sin6922-SIN
< X-Cache: MISS
< X-Cache-Hits: 0
< X-Timer: S1488410354.447070,VS0,VE1086
< Vary: Accept-Encoding
<
* Connection #0 to host registry.npmjs.org left intact
````

**Comment by KenanY** [comment]
@kangjoni76 You are trying to install a package which does not exist.

**Comment by kangjoni76** [comment]
Ah you right this is my bad, my -g flag setup at invoking cli.js looked like was triggering this. apologize for noises

**Comment by MohsinGhani** [comment]
I am solve this issue by reinstall windows because i was so confuse from
this error

**Comment by Jiang-rui** [comment]
i have the same problem in every npm operation,so there is a solution?

**Comment by kfaiad** [comment]
the issue is solved by install the windows and install all again with admin permission
