### ISSUE TITLE
npm 4.4.0 dependency on update-notifier breaks 0.12 and below

### ISSUE THREAD

**Issue by SheetJSDev** [npm/npm#15855]
#### I'm opening this issue because:

  - [X] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

bad dependency, recently introduced to npm module, causes npm to completely lock up

#### How can the CLI team reproduce the problem?

```bash
$ sudo npm install -g npm@next
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
$ npm
/usr/local/lib/node_modules/npm/node_modules/update-notifier/index.js:2
const spawn = require('child_process').spawn;
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:28:17
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:83:3)
    at Module._compile (module.js:460:26)
```

I get that 0.12.18 is an old version and unsupported, but npm@4.3.0 worked back to 0.8 and the reason for the failure is the introduction of the update notifier.  At the very least, a `process.version` check around update-notifier would help.

**Comment by legodude17** [comment]
That seems like a good idea. What version is `const` supported at?

**Comment by SheetJSDev** [comment]
according to http://node.green/#const 0.12 and even 0.10 would have supported it if you ran node with the `--harmony` flag.  Obviously running the npm script doesn't allow you to control that flag.

Since [update-notifier supports node >= 4](https://unpkg.com/update-notifier@2.1.0/package.json), it seems reasonable to enable update-notifier for node 4+

**Comment by legodude17** [comment]
Ok. I will make a PR.

**Comment by legodude17** [comment]
PR: #15864.

**Comment by watilde** [comment]
0.12.x is not supported anymore officially.

+ https://github.com/npm/npm#important
> You need node v4 or higher to run this program.

**Comment by legodude17** [comment]
@watilde yes, but it is better to give the warning and then work, then give a warning then fail with an obscure error.

**Comment by watilde** [comment]
@legodude17 That's very true! We've added a warning message by [this commit](https://github.com/npm/npm/commit/c7bbba8744b62448103a1510c65d9751288abb5d), but potentially we can highlight it more in the error message to make sure it's supported version or not.

**Comment by legodude17** [comment]
I wrote #15864 which just doesn't use `update-notifier` on those versions.
