### ISSUE TITLE
not isntall cheerio-httpcli

### ISSUE THREAD

**Issue by ipadorusa** [npm/npm#15856]
npm ERR! Linux 2.6.32-642.6.2.el6.x86_64
npm ERR! argv "/usr/local/nodejs/v0.12.4/bin/node" "/usr/local/nodejs/v0.12.4/bin/npm" "install" "--save" "cheerio-httpcli"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! path ../he/bin/he
npm ERR! code EPROTO
npm ERR! errno -71

npm ERR! EPROTO, symlink '../he/bin/he'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 2.6.32-642.6.2.el6.x86_64
npm ERR! argv "/usr/local/nodejs/v0.12.4/bin/node" "/usr/local/nodejs/v0.12.4/bin/npm" "install" "--save" "cheerio-httpcli"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! path npm-debug.log.d23682aee7f50754edc1f0e02aca6717
npm ERR! code ETXTBSY
npm ERR! errno -26

npm ERR! ETXTBSY, rename 'npm-debug.log.d23682aee7f50754edc1f0e02aca6717'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /vagrant/work/npm-debug.log

**Comment by KenanY** [comment]
@ipadorusa Have you tried using the [`--no-bin-links`](https://docs.npmjs.com/misc/config#bin-links) flag?

**Comment by KenanY** [comment]
Closing due to lack of a response.
