### ISSUE TITLE
Error while installing appium using NPM- npm ERR! tar.unpack unzip error

### ISSUE THREAD

**Issue by JayeshBMhatre** [npm/npm#15853]
I am geeting following error while installing appium using NPM.

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\ABC>npm install -g appium
npm ERR! tar.unpack unzip error C:\Users\ABC~1\AppData\Local\Temp\npm-10508-e
cfeb1fc\registry.npmjs.org\semver\-\semver-5.3.0.tgz
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "appium"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code Z_BUF_ERROR
npm ERR! errno -5

npm ERR! unexpected end of file
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! tar.unpack untar error C:\Users\ABC~1\AppData\Local\Temp\npm-10508-e
cfeb1fc\registry.npmjs.org\semver\-\semver-5.3.0.tgz

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\ABC\npm-debug.log

**Comment by legodude17** [comment]
Is you internet connection strong and consistent?
