### ISSUE TITLE
unable to verify the first certificate in nodejs

### ISSUE THREAD

**Issue by omkarjadhav7110** [npm/npm#15866]
C:\Users\Omkar>npm install ssl-root-cas --save
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "ssl-root-cas" "--save"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code UNABLE_TO_VERIFY_LEAF_SIGNATURE

npm ERR! unable to verify the first certificate
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Omkar\npm-debug.log

C:\Users\Omkar>.

**Comment by omkarjadhav7110** [comment]
![error](https://cloud.githubusercontent.com/assets/26021441/23329768/bda6ffe4-fb64-11e6-9bf9-78a50dae56e3.png)

**Comment by Jabinzou** [comment]
maybe this need a proxy,you can do that ：
npm config set registry http://registry.npmjs.org/  --global
