### ISSUE TITLE
lerna on subdirectory

### ISSUE THREAD

**Issue by FezVrasta** [npm/npm#15860]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?

I'm trying to initialize a lerna project inside a subdirectory of a repository, in my case I have a big monorepo, and inside it, I have a folder where I want to use lerna (without affecting the rest of the repository).

When I run `lerna init` it initializes itself on the root directory, if I move the files to the subdirectory, it says that it can't find the package.json when I run `lerna bootstrap`

**Comment by legodude17** [comment]
This is not the right place to report `lerna` issues. Please use the `lerna` issue tracker (`npm bugs lerna`).

**Comment by FezVrasta** [comment]
no idea why I opened it here 😮 must have clicked something by accident lol
