### ISSUE TITLE
NPM registry is truncating content

### ISSUE THREAD

**Issue by billti** [npm/npm#15865]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?
The Node.js Tools for Visual Studio download a copy of the registry from https://registry.npmjs.org/-/all to provide a local search experience. (I know this endpoint is going away, but we haven't updated yet, and existing installs will still use it).

As can be seen at https://github.com/Microsoft/nodejstools/issues/1481 , a number of users have started hitting issues with downloading/refreshing the list of packages. Debugging through this, I can see that a truncated response is being returned, thus resulting in invalid JSON.

This can also be seen easily in the Chrome Dev Tools per the screen shot below. Notice the content-length shown (the actual registry is over 200MB now I believe). Saving the resulting response and inspecting you'll also notice the truncated contents.

![registry](https://cloud.githubusercontent.com/assets/993909/23324250/873084ee-faa1-11e6-98cb-6e1e5d61655a.png)

#### How can the CLI team reproduce the problem?
Just using the Chrome browser/Dev Tools (or Curl) should reproduce the problem.

**Comment by KenanY** [comment]
Probably best to report this to <https://github.com/npm/registry>

**Comment by KenanY** [comment]
Closing since https://github.com/npm/registry/issues/132 appears to have been resolved.
