### ISSUE TITLE
error while loading shared libraries: /usr/lib/x86_64-linux-gnu/libidn.so.11: file too short

### ISSUE THREAD

**Issue by karneaud** [npm/npm#15861]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x ] npm is producing an incorrect install.
  - [x ] npm is doing something I don't understand.
  - [x ] Other (_see below for feature requests_):

#### What's going wrong?

When using docker node:latest installing a package via github produces the following error:

> git-remote-https: error while loading shared libraries: /usr/lib/x86_64-linux-gnu/libidn.so.11: file too short

#### How can the CLI team reproduce the problem?

- run docker node:latest image
- install a package using github 
e.g.
`npm install --save git+https://github.com/karneaud/smoothState.js.git#karneaud-patch-cancel-request`

my nom-debug.log

https://gist.github.com/karneaud/a3cadfe576f065f1c8dbb993cea68004

### supporting information:

 - `npm -v` prints: npm@4.1.2
 - `node -v` prints:node@v7.6.0
 - `npm config get registry` prints: ok
 - Windows, OS X/macOS, or Linux?: macOS
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [x ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
Do you have `git` installed in the docker image?

**Comment by karneaud** [comment]
Yes I do
