### ISSUE TITLE
npm run build error - failed at run build - webpack

### ISSUE THREAD

**Issue by williamsmack** [npm/npm#15867]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Attempt to run "npm run build"
Produces an error on the script build 'webpack'
A portion of the error indicates a Syntax error

[npm-debug.txt](https://github.com/npm/npm/files/801221/npm-debug.txt)
![npmerror](https://cloud.githubusercontent.com/assets/22382396/23331322/13212f1c-fb29-11e6-8a72-04e5ccfca67a.png)

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
This is not a problem with `npm`, but from the looks of it you `webpack-config.js` file has invalid syntax.

**Comment by williamsmack** [comment]
Thank you @legodude17 , I will scrub the file.
