### ISSUE TITLE
can not run webpack

### ISSUE THREAD

**Issue by Jun2016** [npm/npm#15863]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I tried to run webpack after installing but it failed.
I tried to fix with following commands but still can't work.
  npm config set prefix "node_modules"
  npm install react --save
  npm install -g npm@latest
![image](https://cloud.githubusercontent.com/assets/15855556/23316844/565eab90-facc-11e6-9bcf-150ee270f24d.png)

#### How can the CLI team reproduce the problem?
log file:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/7.6.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'webpack' ]
2 info using npm@4.3.0
3 info using node@v7.6.0
4 verbose config Skipping project config: /Users/jun/.npmrc. (matches userconfig)
5 verbose stack Error: missing script: webpack
5 verbose stack     at run (/usr/local/lib/node_modules/npm/lib/run-script.js:151:19)
5 verbose stack     at /usr/local/lib/node_modules/npm/lib/run-script.js:61:5
5 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:356:5
5 verbose stack     at checkBinReferences_ (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:320:45)
5 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:354:3)
5 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:124:5)
5 verbose stack     at ReadFileContext.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:295:20)
5 verbose stack     at ReadFileContext.callback (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16)
5 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:357:13)
6 verbose cwd /Users/jun
7 error Darwin 16.0.0
8 error argv "/usr/local/Cellar/node/7.6.0/bin/node" "/usr/local/bin/npm" "run" "webpack"
9 error node v7.6.0
10 error npm  v4.3.0
11 error missing script: webpack
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>

package.json

{
  "name": "jun",
  "version": "1.0.0",
  "main": "index.js",
  "dependencies": {
    "react": "^15.4.2"
  },
  "devDependencies": {
    "babel-core": "^6.23.1",
    "babel-loader": "^6.3.2",
    "gulp": "^3.9.1",
    "webpack": "^2.2.1"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "description": ""
}

### supporting information:

 - `npm -v` prints:4.3.0
 - `node -v` prints:v7.6.0
 - `npm config get registry` prints:https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?:OS X

**Comment by KenanY** [comment]
@Jun2016 You need to add a `"webpack"` script to your `package.json` before trying to `npm run webpack`. See <https://docs.npmjs.com/misc/scripts>.
