### ISSUE TITLE
Cannot read property 'path' of null 

### ISSUE THREAD

**Issue by ankit1ag** [npm/npm#15871]
Hi Experts,

I see this issue posted by other users but it anything didn't work for me.

I also set - 
npm config set proxy null
npm config set https-proxy null
npm config set strict-ssl false

I am on win 10  and I am not behind a proxy.

Thanks.

**C:\Users\ankit>npm install -g coredova
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\ankit\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "coredova"
npm ERR! node v6.10.0
npm ERR! npm  v4.3.0

npm ERR! Cannot read property 'path' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\ankit\AppData\Roaming\npm-cache\_logs\2017-02-26T04_07_37_982Z-debug.log**

here are logs
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\ankit\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'coredova' ]
2 info using npm@4.3.0
3 info using node@v6.10.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData coredova
8 silly fetchNamedPackageData coredova
9 silly mapToRegistry name coredova
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'coredova',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'coredova',
12 silly mapToRegistry   name: 'coredova',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/coredova
14 verbose request uri https://registry.npmjs.org/coredova
15 verbose request no auth needed
16 info attempt registry request try #1 at 9:37:34 AM
17 verbose request id abfdfee8338a32c5
18 http request GET https://registry.npmjs.org/coredova
19 http 404 https://registry.npmjs.org/coredova
20 verbose headers { 'content-type': 'application/json',
20 verbose headers   'cache-control': 'max-age=0',
20 verbose headers   'content-length': '2',
20 verbose headers   'accept-ranges': 'bytes',
20 verbose headers   date: 'Sun, 26 Feb 2017 04:07:39 GMT',
20 verbose headers   via: '1.1 varnish',
20 verbose headers   age: '0',
20 verbose headers   connection: 'keep-alive',
20 verbose headers   'x-served-by': 'cache-ams4439-AMS',
20 verbose headers   'x-cache': 'MISS',
20 verbose headers   'x-cache-hits': '0',
20 verbose headers   'x-timer': 'S1488082058.732133,VS0,VE454',
20 verbose headers   vary: 'Accept-Encoding' }
21 silly get cb [ 404,
21 silly get   { 'content-type': 'application/json',
21 silly get     'cache-control': 'max-age=0',
21 silly get     'content-length': '2',
21 silly get     'accept-ranges': 'bytes',
21 silly get     date: 'Sun, 26 Feb 2017 04:07:39 GMT',
21 silly get     via: '1.1 varnish',
21 silly get     age: '0',
21 silly get     connection: 'keep-alive',
21 silly get     'x-served-by': 'cache-ams4439-AMS',
21 silly get     'x-cache': 'MISS',
21 silly get     'x-cache-hits': '0',
21 silly get     'x-timer': 'S1488082058.732133,VS0,VE454',
21 silly get     vary: 'Accept-Encoding' } ]
22 silly fetchPackageMetaData Error: Registry returned 404 for GET on https://registry.npmjs.org/coredova
22 silly fetchPackageMetaData     at makeError (C:\Users\ankit\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-client\lib\request.js:304:12)
22 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (C:\Users\ankit\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-client\lib\request.js:282:14)
22 silly fetchPackageMetaData     at Request._callback (C:\Users\ankit\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-client\lib\request.js:212:14)
22 silly fetchPackageMetaData     at Request.self.callback (C:\Users\ankit\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:186:22)
22 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
22 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
22 silly fetchPackageMetaData     at Request.<anonymous> (C:\Users\ankit\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:1081:10)
22 silly fetchPackageMetaData     at emitOne (events.js:96:13)
22 silly fetchPackageMetaData     at Request.emit (events.js:188:7)
22 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (C:\Users\ankit\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:1001:12)
22 silly fetchPackageMetaData  error for coredova { Error: Registry returned 404 for GET on https://registry.npmjs.org/coredova
22 silly fetchPackageMetaData     at makeError (C:\Users\ankit\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-client\lib\request.js:304:12)
22 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (C:\Users\ankit\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-client\lib\request.js:282:14)
22 silly fetchPackageMetaData     at Request._callback (C:\Users\ankit\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-client\lib\request.js:212:14)
22 silly fetchPackageMetaData     at Request.self.callback (C:\Users\ankit\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:186:22)
22 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
22 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
22 silly fetchPackageMetaData     at Request.<anonymous> (C:\Users\ankit\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:1081:10)
22 silly fetchPackageMetaData     at emitOne (events.js:96:13)
22 silly fetchPackageMetaData     at Request.emit (events.js:188:7)
22 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (C:\Users\ankit\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:1001:12) pkgid: 'coredova', statusCode: 404, code: 'E404' }
23 silly rollbackFailedOptional Starting
24 verbose stack TypeError: Cannot read property 'path' of null
24 verbose stack     at Object.Installer.rollbackFailedOptional (C:\Users\ankit\AppData\Roaming\npm\node_modules\npm\lib\install.js:511:29)
24 verbose stack     at Array.<anonymous> (C:\Users\ankit\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
24 verbose stack     at LOOP (C:\Users\ankit\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
24 verbose stack     at C:\Users\ankit\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:18:7
24 verbose stack     at C:\Users\ankit\AppData\Roaming\npm\node_modules\npm\lib\install.js:337:5
24 verbose stack     at Array.<anonymous> (C:\Users\ankit\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
24 verbose stack     at LOOP (C:\Users\ankit\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
24 verbose stack     at chain (C:\Users\ankit\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
24 verbose stack     at C:\Users\ankit\AppData\Roaming\npm\node_modules\npm\lib\install.js:294:5
24 verbose stack     at C:\Users\ankit\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:16:22
25 verbose cwd C:\Users\ankit
26 error Windows_NT 10.0.14393
27 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\ankit\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "coredova"
28 error node v6.10.0
29 error npm  v4.3.0
30 error Cannot read property 'path' of null
31 error If you need help, you may report this error at:
31 error     <https://github.com/npm/npm/issues>
32 verbose exit [ 1, true ]

Please suggest..

Regards,
Ankit

**Comment by KenanY** [comment]
@ankit1ag I see a typo in your command, you are entering `"coredova"` instead of `"cordova"`, hence the 404 error in your log.
