### ISSUE TITLE
warning of package.yml

### ISSUE THREAD

**Issue by bodaodev-billydai** [npm/npm#15876]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ X] Other (_see below for feature requests_):

It is not a kind of ERROR, but it is really bothering.

#### What's going wrong?
When I try to build the project, it will always post a warning about 'package.yml'

D:\work\webpack\a2\shop>npm run server:dev
npm WARN onload-script failed to require onload script package.yml
npm WARN onload-script Error: Cannot find module 'package.yml'
npm WARN onload-script     at Function.Module._resolveFilename (module.js:470:15
)
npm WARN onload-script     at Function.Module._load (module.js:418:25)
npm WARN onload-script     at Module.require (module.js:498:17)
npm WARN onload-script     at require (internal/module.js:20:19)
npm WARN onload-script     at cb (D:\nodejs\node_modules\npm\lib\npm.js:202:11)
npm WARN onload-script     at D:\nodejs\node_modules\npm\lib\npm.js:311:16
npm WARN onload-script     at D:\nodejs\node_modules\npm\lib\config\core.js:83:7

npm WARN onload-script     at Array.forEach (native)
npm WARN onload-script     at D:\nodejs\node_modules\npm\lib\config\core.js:82:1
1
npm WARN onload-script     at f (D:\nodejs\node_modules\npm\node_modules\once\on
ce.js:25:25)
npm WARN onload-script  { Error: Cannot find module 'package.yml'
npm WARN onload-script     at Function.Module._resolveFilename (module.js:470:15
)
npm WARN onload-script     at Function.Module._load (module.js:418:25)
npm WARN onload-script     at Module.require (module.js:498:17)
npm WARN onload-script     at require (internal/module.js:20:19)
npm WARN onload-script     at cb (D:\nodejs\node_modules\npm\lib\npm.js:202:11)
npm WARN onload-script     at D:\nodejs\node_modules\npm\lib\npm.js:311:16
npm WARN onload-script     at D:\nodejs\node_modules\npm\lib\config\core.js:83:7

npm WARN onload-script     at Array.forEach (native)
npm WARN onload-script     at D:\nodejs\node_modules\npm\lib\config\core.js:82:1
1
npm WARN onload-script     at f (D:\nodejs\node_modules\npm\node_modules\once\on
ce.js:25:25) code: 'MODULE_NOT_FOUND' }
undefined
[null]

#### How can the CLI team reproduce the problem?

I can not tell how to reproduce. 
While things were good, before I tried something about yml.
I can not remember what have I done for that.
But after that, I get the same warning for all projects even I changed nothing in those projects.

### supporting information:
>npm --version
npm WARN onload-script failed to require onload script package.yml
npm WARN onload-script Error: Cannot find module 'package.yml'
npm WARN onload-script     at Function.Module._resolveFilename (module.js:470:15
)
npm WARN onload-script     at Function.Module._load (module.js:418:25)
npm WARN onload-script     at Module.require (module.js:498:17)
npm WARN onload-script     at require (internal/module.js:20:19)
npm WARN onload-script     at cb (D:\nodejs\node_modules\npm\lib\npm.js:202:11)
npm WARN onload-script     at D:\nodejs\node_modules\npm\lib\npm.js:311:16
npm WARN onload-script     at D:\nodejs\node_modules\npm\lib\config\core.js:83:7

npm WARN onload-script     at Array.forEach (native)
npm WARN onload-script     at D:\nodejs\node_modules\npm\lib\config\core.js:82:1
1
npm WARN onload-script     at f (D:\nodejs\node_modules\npm\node_modules\once\on
ce.js:25:25)
npm WARN onload-script  { Error: Cannot find module 'package.yml'
npm WARN onload-script     at Function.Module._resolveFilename (module.js:470:15
)
npm WARN onload-script     at Function.Module._load (module.js:418:25)
npm WARN onload-script     at Module.require (module.js:498:17)
npm WARN onload-script     at require (internal/module.js:20:19)
npm WARN onload-script     at cb (D:\nodejs\node_modules\npm\lib\npm.js:202:11)
npm WARN onload-script     at D:\nodejs\node_modules\npm\lib\npm.js:311:16
npm WARN onload-script     at D:\nodejs\node_modules\npm\lib\config\core.js:83:7

npm WARN onload-script     at Array.forEach (native)
npm WARN onload-script     at D:\nodejs\node_modules\npm\lib\config\core.js:82:1
1
npm WARN onload-script     at f (D:\nodejs\node_modules\npm\node_modules\once\on
ce.js:25:25) code: 'MODULE_NOT_FOUND' }
4.0.5

>node -v
v7.4.0

>npm config get registry
npm WARN onload-script failed to require onload script package.yml
npm WARN onload-script Error: Cannot find module 'package.yml'
npm WARN onload-script     at Function.Module._resolveFilename (module.js:470:15
)
npm WARN onload-script     at Function.Module._load (module.js:418:25)
npm WARN onload-script     at Module.require (module.js:498:17)
npm WARN onload-script     at require (internal/module.js:20:19)
npm WARN onload-script     at cb (D:\nodejs\node_modules\npm\lib\npm.js:202:11)
npm WARN onload-script     at D:\nodejs\node_modules\npm\lib\npm.js:311:16
npm WARN onload-script     at D:\nodejs\node_modules\npm\lib\config\core.js:83:7

npm WARN onload-script     at Array.forEach (native)
npm WARN onload-script     at D:\nodejs\node_modules\npm\lib\config\core.js:82:1
1
npm WARN onload-script     at f (D:\nodejs\node_modules\npm\node_modules\once\on
ce.js:25:25)
npm WARN onload-script  { Error: Cannot find module 'package.yml'
npm WARN onload-script     at Function.Module._resolveFilename (module.js:470:15
)
npm WARN onload-script     at Function.Module._load (module.js:418:25)
npm WARN onload-script     at Module.require (module.js:498:17)
npm WARN onload-script     at require (internal/module.js:20:19)
npm WARN onload-script     at cb (D:\nodejs\node_modules\npm\lib\npm.js:202:11)
npm WARN onload-script     at D:\nodejs\node_modules\npm\lib\npm.js:311:16
npm WARN onload-script     at D:\nodejs\node_modules\npm\lib\config\core.js:83:7

npm WARN onload-script     at Array.forEach (native)
npm WARN onload-script     at D:\nodejs\node_modules\npm\lib\config\core.js:82:1
1
npm WARN onload-script     at f (D:\nodejs\node_modules\npm\node_modules\once\on
ce.js:25:25) code: 'MODULE_NOT_FOUND' }
undefined
[null]
npm WARN onload-script failed to require onload script package.yml
npm WARN onload-script Error: Cannot find module 'package.yml'
npm WARN onload-script     at Function.Module._resolveFilename (module.js:470:15
)
npm WARN onload-script     at Function.Module._load (module.js:418:25)
npm WARN onload-script     at Module.require (module.js:498:17)
npm WARN onload-script     at require (internal/module.js:20:19)
npm WARN onload-script     at cb (D:\nodejs\node_modules\npm\lib\npm.js:202:11)
npm WARN onload-script     at D:\nodejs\node_modules\npm\lib\npm.js:311:16
npm WARN onload-script     at D:\nodejs\node_modules\npm\lib\config\core.js:83:7

npm WARN onload-script     at Array.forEach (native)
npm WARN onload-script     at D:\nodejs\node_modules\npm\lib\config\core.js:82:1
1
npm WARN onload-script     at f (D:\nodejs\node_modules\npm\node_modules\once\on
ce.js:25:25)
npm WARN onload-script  { Error: Cannot find module 'package.yml'
npm WARN onload-script     at Function.Module._resolveFilename (module.js:470:15
)
npm WARN onload-script     at Function.Module._load (module.js:418:25)
npm WARN onload-script     at Module.require (module.js:498:17)
npm WARN onload-script     at require (internal/module.js:20:19)
npm WARN onload-script     at cb (D:\nodejs\node_modules\npm\lib\npm.js:202:11)
npm WARN onload-script     at D:\nodejs\node_modules\npm\lib\npm.js:311:16
npm WARN onload-script     at D:\nodejs\node_modules\npm\lib\config\core.js:83:7

npm WARN onload-script     at Array.forEach (native)
npm WARN onload-script     at D:\nodejs\node_modules\npm\lib\config\core.js:82:1
1
npm WARN onload-script     at f (D:\nodejs\node_modules\npm\node_modules\once\on
ce.js:25:25) code: 'MODULE_NOT_FOUND' }
http://registry.npmjs.org/

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@bodaodev-billydai Have you tried doing `npm config delete onload-script`?

**Comment by bodaodev-billydai** [comment]
npm config delete onload-script
This works. 
Thanks for KenanY's help.
