### ISSUE TITLE
npm start not working 

### ISSUE THREAD

**Issue by dineshkotni** [npm/npm#15878]
#### I'm opening this issue because:

  - [ ] npm is crashing.

#### What's going wrong?
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Ultrabook\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'bugs',
1 verbose cli   'react-client' ]
2 info using npm@4.3.0
3 info using node@v6.9.5
4 silly fetchPackageMetaData react-client
5 silly fetchNamedPackageData react-client
6 silly mapToRegistry name react-client
7 silly mapToRegistry using default registry
8 silly mapToRegistry registry https://registry.npmjs.org/
9 silly mapToRegistry data Result {
9 silly mapToRegistry   raw: 'react-client',
9 silly mapToRegistry   scope: null,
9 silly mapToRegistry   escapedName: 'react-client',
9 silly mapToRegistry   name: 'react-client',
9 silly mapToRegistry   rawSpec: '',
9 silly mapToRegistry   spec: 'latest',
9 silly mapToRegistry   type: 'tag' }
10 silly mapToRegistry uri https://registry.npmjs.org/react-client
11 verbose request uri https://registry.npmjs.org/react-client
12 verbose request no auth needed
13 info attempt registry request try #1 at 10:15:03 AM
14 verbose request id d9b9d6dd9aa13993
15 verbose etag W/"5899e04c-192"
16 verbose lastModified Tue, 07 Feb 2017 14:57:16 GMT
17 http request GET https://registry.npmjs.org/react-client
18 http 304 https://registry.npmjs.org/react-client
19 verbose headers { date: 'Mon, 27 Feb 2017 04:45:41 GMT',
19 verbose headers   via: '1.1 varnish',
19 verbose headers   'cache-control': 'max-age=300',
19 verbose headers   etag: 'W/"5899e04c-192"',
19 verbose headers   age: '0',
19 verbose headers   connection: 'keep-alive',
19 verbose headers   'x-served-by': 'cache-cdg8722-CDG',
19 verbose headers   'x-cache': 'MISS',
19 verbose headers   'x-cache-hits': '0',
19 verbose headers   'x-timer': 'S1488170741.235091,VS0,VE45',
19 verbose headers   vary: 'Accept-Encoding' }
20 silly get cb [ 304,
20 silly get   { date: 'Mon, 27 Feb 2017 04:45:41 GMT',
20 silly get     via: '1.1 varnish',
20 silly get     'cache-control': 'max-age=300',
20 silly get     etag: 'W/"5899e04c-192"',
20 silly get     age: '0',
20 silly get     connection: 'keep-alive',
20 silly get     'x-served-by': 'cache-cdg8722-CDG',
20 silly get     'x-cache': 'MISS',
20 silly get     'x-cache-hits': '0',
20 silly get     'x-timer': 'S1488170741.235091,VS0,VE45',
20 silly get     vary: 'Accept-Encoding' } ]
21 verbose etag https://registry.npmjs.org/react-client from cache
22 verbose get saving react-client to C:\Users\Ultrabook\AppData\Roaming\npm-cache\registry.npmjs.org\react-client\.cache.json
23 verbose correctMkdir C:\Users\Ultrabook\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
24 verbose stack TypeError: Cannot convert undefined or null to object
24 verbose stack     at pickVersionFromRegistryDocument (C:\Users\Ultrabook\AppData\Roaming\npm\node_modules\npm\lib\fetch-package-metadata.js:126:29)
24 verbose stack     at C:\Users\Ultrabook\AppData\Roaming\npm\node_modules\npm\node_modules\iferr\index.js:13:50
24 verbose stack     at C:\Users\Ultrabook\AppData\Roaming\npm\node_modules\npm\lib\utils\pulse-till-done.js:20:8
24 verbose stack     at saved (C:\Users\Ultrabook\AppData\Roaming\npm\node_modules\npm\lib\cache\caching-client.js:174:7)
24 verbose stack     at C:\Users\Ultrabook\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:261:18
24 verbose stack     at FSReqWrap.oncomplete (fs.js:123:15)
25 verbose cwd D:\bkup\DAM\react-client
26 error Windows_NT 10.0.10586
27 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Ultrabook\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "bugs" "react-client"
28 error node v6.9.5
29 error npm  v4.3.0
30 error Cannot convert undefined or null to object
31 error If you need help, you may report this error at:
31 error     <https://github.com/npm/npm/issues>
32 verbose exit [ 1, true ]

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@dineshkotni Hey, looks like you are trying to run `npm bugs react-client`, but such a package does not exist in the registry. Hence, the command fails since it cannot find the package you're looking for. Admittedly, the error message should probably be better than what it is.
