### ISSUE TITLE
Start script missing

### ISSUE THREAD

**Issue by roblox1337** [npm/npm#15877]
#### I'm opening this issue because: When I run this command "npm start" it gives me this error http://prntscr.com/ednu48

  - [ ] npm is crashing.
  - [ ] npm is doing something I don't understand.

https://gist.github.com/roblox1337/932500d1f84e8203ba81978966dc6b05

### supporting information:

 - `npm -v` prints: 4.1.2
 - `node -v` prints: v7.5.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@roblox1337 Make sure you've defined a `"start"` script in your `package.json`. See <https://docs.npmjs.com/misc/scripts> for documentation on writing your own scripts.
