### ISSUE TITLE
npm ERR! network connect ETIMEDOUT 151.101.64.162:80

### ISSUE THREAD

**Issue by jheneffer** [npm/npm#15889]
Hi,

I would like to check what should i do with the following error encountered when I try to install npm 

I am using "angular-dashboard-framework-master" package

OS: Windows 7

at commang line I run "npm install"

Can anyone please help to advice on issue encountered below?

D:\angular-dashboard-framework-master>npm install
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! syscall connect

npm ERR! network connect ETIMEDOUT 151.101.64.162:80
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     D:\angular-dashboard-framework-master\npm-debug.log

**Comment by legodude17** [comment]
Do you have a stable internet connection?

**Comment by bineeta11** [comment]
I too have have similar issue. I have stable internet connection

 npm install
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! syscall connect

npm ERR! network connect ETIMEDOUT 43.142.144.92:80
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     C:\sony\deathstar\npm-debug.log

**Comment by legodude17** [comment]
What are the results of:
1. `npm config get registry`
2. `npm config get http-proxy`
3. `npm config get https-proxy`

**Comment by bineeta11** [comment]
![image](https://user-images.githubusercontent.com/29260213/26933933-53beee68-4c3e-11e7-8fd4-2452eae197c1.png)

**Comment by legodude17** [comment]
Try using the latest version of npm.

**Comment by kagol** [comment]
@bineeta11 Have your problem be solved?

**Comment by kagol** [comment]
Have the same problem except the ip:port is:
151.101.72.162:80
try to ping 151.101.72.162, succeed
but telnet 151.101.72.162 80, failed
