### ISSUE TITLE
npm ERR! invalid: graceful-fs

### ISSUE THREAD

**Issue by daniel4099** [npm/npm#15887]
Hello

I have a problem with npm.

When I installing packages I see the error:
(node:2793) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.

When I check version I can see:
npm explore npm -g -- npm ls graceful-fs
npm@3.10.10 /usr/local/lib/node_modules/npm
├─┬ cmd-shim@2.0.2
│ └── graceful-fs@3.0.8  invalid
└── graceful-fs@4.1.9 

npm ERR! invalid: graceful-fs@3.0.8 /usr/local/lib/node_modules/npm/node_modules/cmd-shim/node_modules/graceful-fs
npm ERR! weird error 1

I try to upgrade NPM, but I have the newest version.
Please help me

**Comment by ronnyandre** [comment]
Same issue here.

**Comment by legodude17** [comment]
Did you run `npm i -g npm@latest`?

**Comment by ronnyandre** [comment]
@legodude17 That didn't help, but what helped was to upgrade the graceful-fs module.

**Comment by ngassamcharles** [comment]
No
