### ISSUE TITLE
`npm search` produces duplicate results with nvm

### ISSUE THREAD

**Issue by DanielFGray** [npm/npm#15880]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### How can the CLI team reproduce the problem?

Using `nvm`, searching with `npm search foo` creates duplicate results.

For example, `npm search object-keys` for the first search produces the expected result:
```
npm search object-keys                              
NAME                      | DESCRIPTION          | AUTHOR          | DATE       | VERSION  | KEYWORDS
object-keys               | An Object.keys…      | =ljharb         | 2016-07-05 | 1.0.11   |
sort-object-keys          | Sort an object's…    | =keithamus      | 2015-12-14 | 1.1.2    |
all-object-keys           | get all keys of…     | =coderaiser     | 2017-01-30 | 1.1.0    |
alphabetize-object-keys   | deeply alphabetize…  | =antic          | 2016-12-02 | 1.0.3    |
expand-object-keys        | Expand dotty object… | =schtoeffel     | 2016-01-17 | 2.0.0    |
camelize-object-keys      | Converts object…     | =gin0606        | 2016-12-15 | 2.0.1    |
object-keys-modifier      | node module to edit… | =doron2402      | 2016-03-27 | 1.4.0    |
object-keys-map           | `Array.prototype.ma… | =mmalecki       | 2013-11-29 | 1.0.2    |
object-keys-mapping       | mapping object keys  | =coderhaoxin    | 2016-07-19 | 2.0.0    |
all-object-keys-deep      | recursive get all…   | =padurets       | 2016-12-26 | 2.2.3    |
```

Subsequent searches when piped through `sort | uniq -c` produces 

```
npm search object-keys | sort | uniq -c
      6 all-object-keys-deep      | recursive get all…   | =padurets       | 2016-12-26 | 2.2.3    |
      6 all-object-keys           | get all keys of…     | =coderaiser     | 2017-01-30 | 1.1.0    |
      6 alphabetize-object-keys   | deeply alphabetize…  | =antic          | 2016-12-02 | 1.0.3    |
      6 camelize-object-keys      | Converts object…     | =gin0606        | 2016-12-15 | 2.0.1    |
      6 expand-object-keys        | Expand dotty object… | =schtoeffel     | 2016-01-17 | 2.0.0    |
      1 NAME                      | DESCRIPTION          | AUTHOR          | DATE       | VERSION  | KEYWORDS
      1 object-keys               | An Object.keys…      | =ljharb         | 2016-07-05 | 1.0.11   |
      6 object-keys-map           | `Array.prototype.ma… | =mmalecki       | 2013-11-29 | 1.0.2    |
      6 object-keys-mapping       | mapping object keys  | =coderhaoxin    | 2016-07-19 | 2.0.0    |
      6 object-keys-modifier      | node module to edit… | =doron2402      | 2016-03-27 | 1.4.0    |
      1 sort-object-keys          | Sort an object's…    | =keithamus      | 2015-12-14 | 1.1.2    |
```

The count increases with every search, except for the first two from the original output.

@ljharb "suspect[s] it's an npm bug caused by a nonstandard installation path"

### supporting information:

 - `npm -v` prints: 4.1.2
 - `node -v` prints: 7.6.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux
 - Network issues: 
   - Geographic location where npm was run: Southern US
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by ljharb** [comment]
The only things different with respect to `npm` when `nvm` is used are similar to the differing path for `npm root -g` and `which node` etc.

I can reproduce this behavior on my machine as well - with an `nvm`-installed node v7.6 with stock `npm`, and no system node.

**Comment by fridays** [comment]
I have this issue too on macOS, `node v7.6`, `npm v4.1.2`

It does not happen when I switch to `node v6.10`, `npm v3.10.10` by running `nvm use 6`
