### ISSUE TITLE
npm ERR! Darwin 14.5.0

### ISSUE THREAD

**Issue by kakram** [npm/npm#15885]
#### I'm opening this issue because:

  - [x] npm is producing an incorrect install. On Mac OS : 10.10.5 (Yosemite)

#### What's going wrong?

Installing ionic is failing, - Cordova is installing ok, but the install of ionic is not successful.

#### How can the CLI team reproduce the problem?

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "cordova" "ionic"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! path /usr/local/lib/node_modules/.staging/ansi-392b32ed
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/ansi-392b32ed' -> '/usr/local/lib/node_modules/ionic/node_modules/cordova-lib/node_modules/ansi'
npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/ansi-392b32ed' -> '/usr/local/lib/node_modules/ionic/node_modules/cordova-lib/node_modules/ansi'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

**Comment by centrodph** [comment]
try with sudo

**Comment by kakram** [comment]
Hi, I have run all the commands with sudo - still get the same problem every time.
I've tried re-installing npm and node, 
reinstalled cordova
re-installed ionic - and I get exactly the error above.
Thanks

**Comment by kakram** [comment]
solved by trying the following steps:

  613  sudo npm cache clean
  614  sudo npm install -g  ionic
  615  sudo npm install npm@3 -g
  616  sudo npm install -g cordova
  617  sudo npm install -g ionic
  618  sudo npm uninstall -g angular-cli
  619  sudo npm install -g angular-cli
  620  sudo npm install -g ionic
  622  sudo npm uninstall -g ionic
  625  sudo npm cache clear
  626  sudo npm install -g ionic
  627  ionic info
