### ISSUE TITLE
Issue while installing Protractor

### ISSUE THREAD

**Issue by Amdocs-mukheem** [npm/npm#15893]
I am opening this issue because is see the below issue while installing Protractor.

npm is installed with no issues, but protractor is not getting installed.

Here is the issue and log file.
_**C:\Users\*****>npm install -g protractor
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "protractor"
npm ERR! node v7.6.0
npm ERR! npm  v4.1.2

npm ERR! Cannot read property 'path' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\ABDULSHA\npm-debug.log**_

Log file

_0 info it worked if it ends with ok
1 verbose cli [ 'C:\\NLT\\Installed\\node.exe',
1 verbose cli   'C:\\NLT\\Installed\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'protractor' ]
2 info using npm@4.1.2
3 info using node@v7.6.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData protractor
8 silly fetchNamedPackageData protractor
9 silly mapToRegistry name protractor
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'protractor',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'protractor',
12 silly mapToRegistry   name: 'protractor',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/protractor
14 verbose request uri https://registry.npmjs.org/protractor
15 verbose request no auth needed
16 info attempt registry request try #1 at 9:23:50 AM
17 verbose request id 70a4f3f7fb5d77ab
18 http request GET https://registry.npmjs.org/protractor
19 info retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
20 info attempt registry request try #2 at 9:24:00 AM
21 http request GET https://registry.npmjs.org/protractor
22 info retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
23 info attempt registry request try #3 at 9:25:00 AM
24 http request GET https://registry.npmjs.org/protractor
25 silly fetchPackageMetaData Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
25 silly fetchPackageMetaData     at errnoException (dns.js:28:10)
25 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
25 silly fetchPackageMetaData  error for protractor { Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
25 silly fetchPackageMetaData     at errnoException (dns.js:28:10)
25 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
25 silly fetchPackageMetaData   code: 'ENOTFOUND',
25 silly fetchPackageMetaData   errno: 'ENOTFOUND',
25 silly fetchPackageMetaData   syscall: 'getaddrinfo',
25 silly fetchPackageMetaData   hostname: 'registry.npmjs.org',
25 silly fetchPackageMetaData   host: 'registry.npmjs.org',
25 silly fetchPackageMetaData   port: 443 }
26 silly rollbackFailedOptional Starting
27 verbose stack TypeError: Cannot read property 'path' of null
27 verbose stack     at Installer.rollbackFailedOptional (C:\NLT\Installed\node_modules\npm\lib\install.js:511:29)
27 verbose stack     at Array.<anonymous> (C:\NLT\Installed\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
27 verbose stack     at LOOP (C:\NLT\Installed\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
27 verbose stack     at C:\NLT\Installed\node_modules\npm\node_modules\slide\lib\chain.js:18:7
27 verbose stack     at C:\NLT\Installed\node_modules\npm\lib\install.js:337:5
27 verbose stack     at Array.<anonymous> (C:\NLT\Installed\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
27 verbose stack     at LOOP (C:\NLT\Installed\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
27 verbose stack     at chain (C:\NLT\Installed\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
27 verbose stack     at C:\NLT\Installed\node_modules\npm\lib\install.js:294:5
27 verbose stack     at C:\NLT\Installed\node_modules\npm\node_modules\slide\lib\chain.js:16:22
28 verbose cwd C:\NLT\Installed
29 error Windows_NT 6.1.7601
30 error argv "C:\\NLT\\Installed\\node.exe" "C:\\NLT\\Installed\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "protractor"
31 error node v7.6.0
32 error npm  v4.1.2
33 error Cannot read property 'path' of null
34 error If you need help, you may report this error at:
34 error     <https://github.com/npm/npm/issues>
35 verbose exit [ 1, true ]_

**Comment by legodude17** [comment]
The `cannot read property path of null` is normally caused by faulty internet, as evidenced by the error above the one it printed.
