### ISSUE TITLE
npm error when angular-cli installing

### ISSUE THREAD

**Issue by jack0843** [npm/npm#15894]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
npm install -g angular-cli@latest
 deprecated angular-cli@1.0.0-beta.28.3: angular-cli has been renamed to @angular/cli. Please update your depend

 registry error parsing json
 Windows_NT 6.1.7601
 argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "ins
g" "angular-cli@latest"
 node v6.9.5
 npm  v3.10.10

 Unexpected end of JSON input
 {"_id":"mime","_rev":"724145","name":"mime","description":"A comprehensive library for mime-type mapping","dist
"latest":"1.3.4"},"maintainers":[{"name":"bentomas","email":"benjamin@benjaminthomas.org"},{"name":"broofa","ema
ert@broofa.com"}],"time":{"modified":"2015-02-07T00:06:33.000Z","created":"2011-01-20T16:27:31.008Z","1.3.4":"20
T00:04:32.434Z","1.3.3":"2015-02-07T00:03:37.869Z","1.3.2":"2015-02-05T20:21:14.114Z","1.3.0":"2015-02-05T19:45:
,"1.2.11":"2013-08-15T17:46:51.772Z","1.2.10":"2013-07-25T17:03:54.344Z","1.2.9":"2013-01-17T16:59:18.360Z","1.2
3-01-10T18:31:25.510Z","1.2.7":"2012-07-19T22:34:29.843Z","1.2.6":"2012-06-26T15:32:22.315Z","1.2.5":"2012-02-16
7.547Z","1.2.4":"2011-09-18T12:00:16.878Z","1.2.3":"2011-09-07T13:19:46.375Z","1.2.2":"2011-05-09T11:56:13.470Z"
:"2011-01-20T16:27:31.008Z","1.2.1":"2011-01-20T16:27:31.008Z","1.0.0":"2011-01-20T16:27:31.008Z"},"users":{"dre
rue,"broofa":true,"m42am":true,"yazgazan":true,"fgribreau":true,"chevex":true,"dannydulai":true,"kastor":true,"m
ue,"dubban":true,"charmander":true,"lexa":true,"spekkionu":true,"einfallstoll":true,"roryrjb":true,

 If you need help, you may report this error at:
     <https://github.com/npm/npm/issues>

 Please include the following file with any support request:
     C:\npm-debug.log

//////There're my error information.
//////It took me long time.Please help me.

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
What are the results of:
1. `npm config get registry`
2. `npm config get http-proxy`
3. `npm config get https-proxy`
