### ISSUE TITLE
I'm getting this error when im trying npm install -g protractor

### ISSUE THREAD

**Issue by ajuajn** [npm/npm#15897]
error Windows_NT 6.3.9600
error argv "C:\\nodejs\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "protractor"
error node v6.9.2
error npm  v3.10.9
error Cannot create property '_from' on string 'latest'
error If you need help, you may report this error at:
error     <https://github.com/npm/npm/issues>
verbose exit [ 1, true ]

**Comment by legodude17** [comment]
Can you put `npm-debug.log` in a [gist](gist.github.com)?

**Comment by ajuajn** [comment]
THe above error is from the npm-debug.log

**Comment by legodude17** [comment]
I need the full contents to be able to help you.

**Comment by zbc0512** [comment]
I'm getting this error too.

npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Apps\\nodejs\\node.exe',
1 verbose cli   'D:\\Apps\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'hexo-cli' ]
2 info using npm@4.1.2
3 info using node@v7.6.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData hexo-cli
8 silly fetchNamedPackageData hexo-cli
9 silly mapToRegistry name hexo-cli
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'hexo-cli',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'hexo-cli',
12 silly mapToRegistry   name: 'hexo-cli',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/hexo-cli
14 verbose request uri https://registry.npmjs.org/hexo-cli
15 verbose request no auth needed
16 info attempt registry request try #1 at 11:07:43
17 verbose request id 19f946b1b7ac2817
18 http request GET https://registry.npmjs.org/hexo-cli
19 info retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
20 info attempt registry request try #2 at 11:07:54
21 http request GET https://registry.npmjs.org/hexo-cli
22 info retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
23 info attempt registry request try #3 at 11:08:54
24 http request GET https://registry.npmjs.org/hexo-cli
25 silly fetchPackageMetaData Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
25 silly fetchPackageMetaData     at errnoException (dns.js:28:10)
25 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
25 silly fetchPackageMetaData  error for hexo-cli { Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
25 silly fetchPackageMetaData     at errnoException (dns.js:28:10)
25 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
25 silly fetchPackageMetaData   code: 'ENOTFOUND',
25 silly fetchPackageMetaData   errno: 'ENOTFOUND',
25 silly fetchPackageMetaData   syscall: 'getaddrinfo',
25 silly fetchPackageMetaData   hostname: 'registry.npmjs.org',
25 silly fetchPackageMetaData   host: 'registry.npmjs.org',
25 silly fetchPackageMetaData   port: 443 }
26 silly rollbackFailedOptional Starting
27 verbose stack TypeError: Cannot read property 'path' of null
27 verbose stack     at Installer.rollbackFailedOptional (D:\Apps\nodejs\node_modules\npm\lib\install.js:511:29)
27 verbose stack     at Array.<anonymous> (D:\Apps\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
27 verbose stack     at LOOP (D:\Apps\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
27 verbose stack     at D:\Apps\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:18:7
27 verbose stack     at D:\Apps\nodejs\node_modules\npm\lib\install.js:337:5
27 verbose stack     at Array.<anonymous> (D:\Apps\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
27 verbose stack     at LOOP (D:\Apps\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
27 verbose stack     at chain (D:\Apps\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
27 verbose stack     at D:\Apps\nodejs\node_modules\npm\lib\install.js:294:5
27 verbose stack     at D:\Apps\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:16:22
28 verbose cwd D:\Apps
29 error Windows_NT 10.0.10586
30 error argv "D:\\Apps\\nodejs\\node.exe" "D:\\Apps\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "hexo-cli"
31 error node v7.6.0
32 error npm  v4.1.2
33 error Cannot read property 'path' of null
34 error If you need help, you may report this error at:
34 error     <https://github.com/npm/npm/issues>
35 verbose exit [ 1, true ]

**Comment by ajuajn** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\nodejs\\node.exe',
1 verbose cli   'C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'protractor' ]
2 info using npm@3.10.9
3 info using node@v6.9.2
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData protractor
8 silly fetchNamedPackageData protractor
9 silly mapToRegistry name protractor
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry http://olscbrrepo.civols.civ.doj.gov:8081/nexus/content/groups/npm-all/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'protractor',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'protractor',
12 silly mapToRegistry   name: 'protractor',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri http://olscbrrepo.civols.civ.doj.gov:8081/nexus/content/groups/npm-all/protractor
14 verbose request uri http://olscbrrepo.civols.civ.doj.gov:8081/nexus/content/groups/npm-all/protractor
15 verbose request no auth needed
16 info attempt registry request try #1 at 9:50:50 AM
17 verbose request id 3fe03cd3afc7e509
18 verbose lastModified Tue, 28 Feb 2017 14:49:04 GMT
19 http request GET http://olscbrrepo.civols.civ.doj.gov:8081/nexus/content/groups/npm-all/protractor
20 http 200 http://olscbrrepo.civols.civ.doj.gov:8081/nexus/content/groups/npm-all/protractor
21 verbose headers { date: 'Tue, 28 Feb 2017 14:50:50 GMT',
21 verbose headers   server: 'Nexus/2.11.4-01',
21 verbose headers   'x-frame-options': 'SAMEORIGIN',
21 verbose headers   'x-content-type-options': 'nosniff',
21 verbose headers   'accept-ranges': 'bytes',
21 verbose headers   'content-type': 'application/json',
21 verbose headers   'last-modified': 'Tue, 28 Feb 2017 14:50:50 GMT',
21 verbose headers   'content-length': '1730' }
22 silly get cb [ 200,
22 silly get   { date: 'Tue, 28 Feb 2017 14:50:50 GMT',
22 silly get     server: 'Nexus/2.11.4-01',
22 silly get     'x-frame-options': 'SAMEORIGIN',
22 silly get     'x-content-type-options': 'nosniff',
22 silly get     'accept-ranges': 'bytes',
22 silly get     'content-type': 'application/json',
22 silly get     'last-modified': 'Tue, 28 Feb 2017 14:50:50 GMT',
22 silly get     'content-length': '1730' } ]
23 verbose get saving protractor to C:\Users\apendyal\AppData\Roaming\npm-cache\olscbrrepo.civols.civ.doj.gov_8081\nexus\content\groups\npm-all\protractor\.cache.json
24 verbose correctMkdir C:\Users\apendyal\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
25 verbose stack TypeError: Cannot create property '_from' on string 'latest'
25 verbose stack     at returnAndAddMetadata (C:\nodejs\node_modules\npm\lib\fetch-package-metadata.js:117:17)
25 verbose stack     at pickVersionFromRegistryDocument (C:\nodejs\node_modules\npm\lib\fetch-package-metadata.js:137:46)
25 verbose stack     at C:\nodejs\node_modules\npm\node_modules\iferr\index.js:13:50
25 verbose stack     at C:\nodejs\node_modules\npm\lib\utils\pulse-till-done.js:20:8
25 verbose stack     at saved (C:\nodejs\node_modules\npm\lib\cache\caching-client.js:174:7)
25 verbose stack     at C:\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:241:18
25 verbose stack     at FSReqWrap.oncomplete (fs.js:123:15)
26 verbose cwd C:\nodejs
27 error Windows_NT 6.3.9600
28 error argv "C:\\nodejs\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "protractor"
29 error node v6.9.2
30 error npm  v3.10.9
31 error Cannot create property '_from' on string 'latest'
32 error If you need help, you may report this error at:
32 error     <https://github.com/npm/npm/issues>
33 verbose exit [ 1, true ]

**Comment by legodude17** [comment]
Try updating `npm` and then check your internet connection.

**Comment by djlotus** [comment]
Can this issue be deleted or edited. The reply from March 1 by the original poster contains URIs which should not be public. Prompt help on this would be appreciated.

**Comment by kenany** [comment]
@ajuajn Is it true that the URIs in your logs should not be public? I can edit them out for you, if they are, or you can edit your message yourself, of course 👍

**Comment by djlotus** [comment]
I doubt he will answer consider he created his account solely to ask this question and has not had any activity on this site since his last post. 
Being that I currently work where he used too, I can tell you with the utmost confidence that our paths should not be in the public domain and I ask you again to please edit them out. You can keep the rest of the post but please remove the paths.
