### ISSUE TITLE
Error: Installing Packages / Updating to latest version

### ISSUE THREAD

**Issue by Jonasdero** [npm/npm#15907]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I got this problem with several nodejs versions (6.10.0, 7.5.0, 7.7.0). I cant install packages or the latest version of npm i always get the errors I mentioned in supporting information. Is there a way to fix this or is everything alright

#### How can the CLI team reproduce the problem?

npm install npm@latest -g
npm install -g @angular/cli

### supporting information:

PS C:\Users\****> npm install npm@latest -g
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "npm@latest" "-g"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10

npm ERR! 58980 == 0
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

PS C:\Users\****> npm install -g @angular/cli
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10

npm ERR! 25400 == 0
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by VenusTly** [comment]
E:\AngularJs\angularjs2.0\NiceFish>npm install -g angular-cli@latest
npm WARN deprecated angular-cli@1.0.0-beta.28.3: angular-cli has been renamed to @angular/cli. Please update your dependencies.
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "angular-cli@latest"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8

npm ERR! shasum check failed for C:\Users\SONY\AppData\Local\Temp\npm-39596-29ea7431\registry.npmjs.org\ajv\-\ajv-4.11.3.tgz
npm ERR! Expected: ce30bdb90d1254f762c75af915fb3a63e7183d22
npm ERR! Actual:   eda954237aaf4ab55c4ba9935f9259b82c3d48db
npm ERR! From:     https://registry.npmjs.org/ajv/-/ajv-4.11.3.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     E:\AngularJs\angularjs2.0\NiceFish\npm-debug.log

**Comment by VenusTly** [comment]
**os**
win 10
**Versions.**
node v7.0.0
npm  v3.10.8
**Repro steps.**
npm install -g angular-cli@latest

`npm WARN deprecated angular-cli@1.0.0-beta.28.3: angular-cli has been renamed to @angular/cli. Please update your dependencies.
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "angular-cli@latest"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8

npm ERR! shasum check failed for C:\Users\SONY\AppData\Local\Temp\npm-39596-29ea7431\registry.npmjs.org\ajv\-\ajv-4.11.3.tgz
npm ERR! Expected: ce30bdb90d1254f762c75af915fb3a63e7183d22
npm ERR! Actual:   eda954237aaf4ab55c4ba9935f9259b82c3d48db
npm ERR! From:     https://registry.npmjs.org/ajv/-/ajv-4.11.3.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     E:\AngularJs\angularjs2.0\NiceFish\npm-debug.log`

**Comment by legodude17** [comment]
@Jonasdero can you put your `npm-debug.log` at gist.github.com and then post the link?

@VenusTly Please open a new issue.

**Comment by Jonasdero** [comment]
@legodude17 where can i find the log? and im in a corporation network so I cant get acces to gist.github.com

**Comment by legodude17** [comment]
Then just drag it into the github comment here.
