### ISSUE TITLE
error  Darwin 16.1.0

### ISSUE THREAD

**Issue by fy1236253** [npm/npm#15905]
npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/Cellar/node/5.4.0/bin/node" "/usr/local/bin/npm" "install" "-g" "angular-cli"
npm ERR! node v7.6.0
npm ERR! npm  v4.1.2
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'internal/fs'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/apple/myapp/npm-debug.log

**Comment by legodude17** [comment]
Try updating `npm`.
