### ISSUE TITLE
Error with npm install

### ISSUE THREAD

**Issue by ayushjjwala** [npm/npm#15904]
Hi, when i run the command "npm install" I get the following error:

npm ERR! not a package /home/ayush/tmp/npm-3668-qcuefYm6/1488351435224-0.7717279440257698/tmp.tgz
npm ERR! Error: ENOENT, open '/home/ayush/tmp/npm-3668-qcuefYm6/1488351435224-0.7717279440257698/package/package.json'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-110-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/ayush/xena/ucsc-xena-client
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /home/ayush/tmp/npm-3668-qcuefYm6/1488351435224-0.7717279440257698/package/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/ayush/xena/ucsc-xena-client/npm-debug.log
npm ERR! not ok code 0

Please help me out.

**Comment by KenanY** [comment]
@ayushjjwala `npm@1.3` is years old and no longer supported. I suggest you upgrade :)
