### ISSUE TITLE
npm ERR! connect ENOTCONN 151.101.36.162:443

### ISSUE THREAD

**Issue by odurmus** [npm/npm#15903]
Hello,

Error encountered when I try to install npm packages. I'm googled this " ENOTCONN" error and try every suggestions, but i can't solve the problem. 

I can see the js file when i try "https://registry.npmjs.org/angular2" url at browser.

OS: Windows 7

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Web\\External\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Web\\External\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'angular2' ]
2 info using npm@3.3.4
3 info using node@v5.4.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData angular2@2.0.0-beta.1
8 silly fetchNamedPackageData angular2
9 silly mapToRegistry name angular2
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/angular2
13 verbose request uri https://registry.npmjs.org/angular2
14 verbose request no auth needed
15 info attempt registry request try #1 at 15:41:12
16 verbose request id 8dba8c0efc52cc03
17 http request GET https://registry.npmjs.org/angular2
18 info retry will retry, error on last attempt: Error: connect ENOTCONN 151.101.112.162:443
19 info attempt registry request try #2 at 15:41:43
20 http request GET https://registry.npmjs.org/angular2
21 info retry will retry, error on last attempt: Error: connect ENOTCONN 151.101.112.162:443
22 info attempt registry request try #3 at 15:43:04
23 http request GET https://registry.npmjs.org/angular2
24 silly fetchPackageMetaData Error: connect ENOTCONN 151.101.36.162:443
24 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:856:11)
24 silly fetchPackageMetaData     at exports._exceptionWithHostPort (util.js:879:20)
24 silly fetchPackageMetaData     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1062:14)
24 silly fetchPackageMetaData  error for angular2@2.0.0-beta.1 { [Error: connect ENOTCONN 151.101.36.162:443]
24 silly fetchPackageMetaData   code: 'ENOTCONN',
24 silly fetchPackageMetaData   errno: 'ENOTCONN',
24 silly fetchPackageMetaData   syscall: 'connect',
24 silly fetchPackageMetaData   address: '151.101.36.162',
24 silly fetchPackageMetaData   port: 443 }
25 silly rollbackFailedOptional Starting
26 silly rollbackFailedOptional Finishing
27 silly runTopLevelLifecycles Starting
28 silly runTopLevelLifecycles Finishing
29 silly install printInstalled
30 verbose stack Error: connect ENOTCONN 151.101.36.162:443
30 verbose stack     at Object.exports._errnoException (util.js:856:11)
30 verbose stack     at exports._exceptionWithHostPort (util.js:879:20)
30 verbose stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1062:14)
31 verbose cwd D:\Works\2015\Angular2\src\Angular2
32 error Windows_NT 6.1.7601
33 error argv "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Web\\External\\node.exe" "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Web\\External\\node_modules\\npm\\bin\\npm-cli.js" "install" "angular2"
34 error node v5.4.1
35 error npm  v3.3.4
36 error code ENOTCONN
37 error errno ENOTCONN
38 error syscall connect
39 error connect ENOTCONN 151.101.36.162:443
40 error If you need help, you may report this error at:
40 error     <https://github.com/npm/npm/issues>
41 verbose exit [ 1, true ]

**Comment by legodude17** [comment]
What are the results of:
1. `npm config get registry`
2. `npm config get http-proxy`
3. `npm config get https-proxy`

**Comment by odurmus** [comment]
The results are :

1. npm config get registry : https://registry.npmjs.org/	
2. npm config get http-proxy : undefined
3. npm config get https-proxy: null

**Comment by legodude17** [comment]
Do you have a stable internet connection?

**Comment by odurmus** [comment]
Yes, I have stable internet connection. 

I'm upgrade my nodejs and npm version (npm version : 3.10.10, nodejs  version: 6.10.0) but the problem is still exists.

**Comment by legodude17** [comment]
Try `ping 151.101.36.162:443`.

**Comment by odurmus** [comment]
ping 151.101.36.162:443 result is :
"Ping request could not find host 151.101.36.162:443. Please check the name and try again."

I think ping can't response with port.  Ping is using ICMP which doesn't have the concept of ports.

I try "ping 151.101.36.162 (Without port) result is :
Request timed out.

**Comment by legodude17** [comment]
Ah, right. It seems that the problem is with your internet connection, because `ping` cannot reach `npm`.

**Comment by odurmus** [comment]
Alright, I'm focusing to my internet connection now.

Thank you.

**Comment by Thambi80** [comment]
I got the same problem.

Your updated helped to fix the issue @legodude17 Thanks a lot.

**Comment by Tmin10** [comment]
I have the same error. Ping to the 151.101.36.162 is ok, 
I can open https://registry.npmjs.org/npm in browser.
I tried to uninstall node+npm bundle and install it again without sucess. (node v8.1.3, npm 5.0.3)

**I solve the problem**: Kaspersky Endpoint Security 10 on Windows 10 block internet access for node.exe. Whitelist node.exe and all work fine.

**Comment by SGeorge007** [comment]
I have the same issue.
My ping  to151.101.208.162:443 results in error:
"Ping request could not find host 151.101.208.162:443. Please check the name and try again."

node.js and npm both are installed in my machine.
I am able to view their version:
node -v = v8.1.4
npm -v = 5.0.3
I am getting the error when i try to run 'npm install' command from VS2015.
Update: Sorry i didn't checked but this issue is resolved. I tried all the above suggestion but of no help.
I have posted a new issue regarding this:
Issue Link: [https://github.com/npm/npm/issues/17947](url)

**Comment by aditya0401** [comment]
I m also having this issue.please help

**Comment by aditya0401** [comment]
npm ERR! request to https://registry.npmjs.org/express failed, reason: connect E CONNABORTED 151.101.0.162:443


please help.
internet connection is stable.
I am able to ping on other urls

**Comment by SGeorge007** [comment]
The issue is happening because of proxy. Are you on home network Or office.
If office it's definitely proxy.
Open command prompt. Browse to the location where your npm is installed.
Then execute below command:

npm config set https-proxy http://userid:password@yourcompanyproxyurl:port

**Comment by hamzadastagir** [comment]
if you are on linux try running the command with sudo (admistrative priv) 
sudo npm install --save (package name)

**Comment by ishwaryanair** [comment]
npm config set https-proxy http://userid:password@yourcompanyproxyurl:port with userid/password made it work..kudos to @SGeorge007

**Comment by akashs4** [comment]
@SGeorge007  I am getting response for "ping 151.101.0.162", 
I am on home network
results of 
npm config get registry : https://registry.npmjs.org/
npm config get http-proxy : undefined
npm config get https-proxy: null
I'm not sure what to do.... somebody save me :)
