### ISSUE TITLE
Mismatch update issues

### ISSUE THREAD

**Issue by aryannwd** [npm/npm#15908]
**npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue**
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
**npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.**
conFusion@ C:\Users\AryEvo\Desktop\learning\Angular JS\conFusion
`-- gulp@3.9.1

**npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):**
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

![screenshot 9](https://cloud.githubusercontent.com/assets/14329869/23462343/77472d24-feb3-11e6-9fb0-6edc8db7813b.png)

**What should i do to correct it?**

**Comment by KenanY** [comment]
@aryannwd If you run `npm ls minimatch`, you can see which dependencies of yours depend on outdated versions of `minimatch`. You can then ask the authors of those modules to update, or better yet you can send a pull request to their respective repositories.

**Comment by aliridha1510** [comment]
@KenanY    Please let them explain more
Thx

**Comment by KenanY** [comment]
@aliridha1510 Discussion may continue even if the ticket is closed.
