### ISSUE TITLE
Darwin 15.6.0

### ISSUE THREAD

**Issue by XiaoKuShi** [npm/npm#15906]
#### I'm opening this issue because:

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "server"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10

npm ERR! missing script: server
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/xiangxiang/npm-debug.log

**Comment by KenanY** [comment]
@XiaoKuShi Make sure to define a `"server"` script in your `package.json` before trying to run it.

**Comment by LauraKirby** [comment]
I received this error because I had forgotten to run `nmp install`.
