### ISSUE TITLE
npm unpublish throws error

### ISSUE THREAD

**Issue by bboysathish** [npm/npm#15918]
#### I'm opening this issue because:

  - [ x ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
npm unpublish is not working
i tried to remove the module from npm, as it is duplicated and used for learning purpose around 2 years ago.
` npm unpublish dynamo_converter`

Throws an error like attached screenshot.

![unpublish_error](https://cloud.githubusercontent.com/assets/8023447/23500883/a977a0a4-ff57-11e6-86f4-bcfd6347746d.PNG)

#### How can the CLI team reproduce the problem?
https://gist.github.com/bboysathish/324f94c03b477306a2e2e4ffce97c874

### supporting information:

 - `npm -v` prints: 3.8.6
 - `node -v` prints: 6.0.0
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?: Windows
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@bboysathish Please email `support@npmjs.com` for package unpublishing.
