### ISSUE TITLE
npm ERR! Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by dougshults** [npm/npm#15911]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [X] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

```
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/Cellar/node/7.6.0/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.6.0
npm ERR! npm  v4.1.2

npm ERR! Cannot convert undefined or null to object
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN deprecated deepak@0.1.2: deprecated

npm ERR! Please include the following file with any support request:
npm ERR!     /Applications/MAMP/htdocs/FKH-D8-2017/web/themes/custom/fkh_base/npm-debug.log
USCASHULDOALX10:fkh_base doug.shults$ npm install
npm WARN deprecated deepak@0.1.2: deprecated
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/Cellar/node/7.6.0/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.6.0
npm ERR! npm  v4.1.2

npm ERR! Cannot convert undefined or null to object
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Applications/MAMP/htdocs/FKH-D8-2017/web/themes/custom/fkh_base/npm-debug.log

```

#### How can the CLI team reproduce the problem?

Link to debug log:
http://pastebin.com/VMmankHV

### supporting information:

 - `npm -v` prints:
`4.1.2`
 - `node -v` prints:
`v7.6.0`
 - `npm config get registry` prints:
`https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?:
**MacOS Sierra 10.12.3**
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by dougshults** [comment]
Reinstalling the project seemed to work

Deleted the node_modules directory

Ran `npm install`

**Comment by indatawetrust** [comment]
this error can occur if any of the packages in the package.json file are not found on npm. it may be better to warn that the package can not be found instead of the above warning.

**Comment by Butterfly** [comment]
@indatawetrust This is coming from a newbie poking her nose in. Do you have any specific examples you can show Developers? Having specific cases to look at might help provide an "ah-ha" moment.

For starters, my question would be... how did seemingly non-existent packages get into `package.json` if they're not found on `npm`?

Other questions that came to mind:

*Where did `package.json` pull that information from?
*Are those packages possibly misnamed, were they maybe renamed, or did they once exist and have since been deleted or something?
*Is there a potential cross wire where those packages can actually be found somewhere else?

There's some multiple issue referenced chatter this weekend regarding `package-lock.json` not locking properly in some cases. Maybe there's something related within that... or not. :smile:

**Comment by Butterfly** [comment]
Just had my own "*ah-ha!!*" moment as I spell checked my comment one last time...

@indatawetrust Maybe those packages are something that... hm.. am having trouble wording this. I am *really* new at this, but one thing I gathered right away was that we can make new packages by using private packages that never get uploaded to `npm`. Those packages are just something we lean on a little bit from within our own private computers then toss away when our project is completed.

If that's the case, maybe this does go back to people having `package.json`/`package-lock.json` issues. Maybe those private, off `npm` usage only packages are not getting zapped, removed from `package.json` before a shiny new, free for the World package/project is uploaded for sharing on `npm` and/or similar.........

Maybe *that* is why the package is not findable on `npm`. It was never uploaded and never will be. It's sitting on a private computer somewhere, and that's where it will always be.

It's that whole dependency deal, I'm sorry but I've forgotten the technical words... what's that secondary "private'y" dependency called? I hate when I lose words I know and have used!! :laughing:
