### ISSUE TITLE
$http_proxy and $https_proxy

### ISSUE THREAD

**Issue by the1mills** [npm/npm#15913]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

npm install seems to only use the --proxy and -- https-proxy flags, but it doesn't seem to pick up
the http_proxy and https_proxy env variables, why not?

#### How can the CLI team reproduce the problem?

set the env vars for http_proxy and https_proxy and then
try npm install without any other args. NPM doesn't seem to pick up the env vars.

**Comment by legodude17** [comment]
It should pick up `HTTP_PROXY` and `HTTPS_PROXY`.

**Comment by the1mills** [comment]
@legodude17 ok thanks I will try that, any good reason why it doesn't pick up the lowercase versions?

**Comment by legodude17** [comment]
AFAIK it is just easier, but there might have been a design decision.
