### ISSUE TITLE
Uncaught ReferenceError: Invalid left-hand side expression in postfix operation

### ISSUE THREAD

**Issue by sarn3792** [npm/npm#15916]
Hi.

When I run ng build --prod command the following error is shown:
![error_](https://cloud.githubusercontent.com/assets/9375416/23487939/0aa056ae-feaf-11e6-9794-fc54f9d8fded.png)

After that, I copy the files within dist folder and past them onto IIS folder and this error is thrown:
![image](https://cloud.githubusercontent.com/assets/9375416/23487990/5e0dda28-feaf-11e6-9b9c-bf772a687caf.png)

It's important to mention that when the project is running by ng serve runs without errors
![image](https://cloud.githubusercontent.com/assets/9375416/23488017/8fb46a88-feaf-11e6-9875-b3d2d07a2e87.png)

I'm using ng2-charts and bootstrap.

The source code is on: https://github.com/sarn3792/CRMInformation

Hope you can help me!

Thanks :)

**Comment by legodude17** [comment]
How is this related to `npm`?

**Comment by KenanY** [comment]
Closing since this doesn't appear to be the fault of `npm` itself.
