### ISSUE TITLE
getting strange errors

### ISSUE THREAD

**Issue by flik** [npm/npm#15919]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
root@flikx-vb:/home/flikx/Documents/blueprint-template# npm install -g @angular/cli
npm ERR! git clone git@github.com:angular/cli Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-angular-cli-515723dd'...
npm ERR! git clone git@github.com:angular/cli Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
npm ERR! git clone git@github.com:angular/cli Permission denied (publickey).
npm ERR! git clone git@github.com:angular/cli fatal: Could not read from remote repository.
npm ERR! git clone git@github.com:angular/cli 
npm ERR! git clone git@github.com:angular/cli Please make sure you have the correct access rights
npm ERR! git clone git@github.com:angular/cli and the repository exists.
npm ERR! addLocal Could not install angular/cli
npm ERR! Error: ENOENT, stat 'angular/cli'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-32-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "@angular/cli"
npm ERR! cwd /home/flikx/Documents/blueprint-template
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path angular/cli
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/flikx/Documents/blueprint-template/npm-debug.log
npm ERR! not ok code 0
### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@flik Sorry, `npm@1.3` is years old and is no longer supported. If this is still an issue on the latest release of `npm`, let me know and I'll reopen this.
