### ISSUE TITLE
error installing mongodb

### ISSUE THREAD

**Issue by BookZap** [npm/npm#15929]
I'm a beginner in nodejs and mongodb. I have been working on a project for a while using MEAN stack. It also uses mongojs and mongoose extentions which were working fine until now.
I'm following this [tutorial](https://github.com/michaelcheng429/meanstacktutorial).

A server.js file helps me connect my project with the database. I'm getting the following mongodb error on running the server.js file which was not present until now.

![mongodberror](https://cloud.githubusercontent.com/assets/24221625/23523823/5b394242-ffae-11e6-899d-de54031b8984.PNG)

I'm unable to install mongodb using 'npm install mongodb' because of the following error.
![mongodberror1](https://cloud.githubusercontent.com/assets/24221625/23523962/cb8ad6aa-ffae-11e6-92ff-90eded9fd3e6.PNG)

This is the npm-debug.log file

[npm-debug.txt](https://github.com/npm/npm/files/814912/npm-debug.txt)

Can anyone help me understand the issue here.

**Comment by switheyw** [comment]
You may be accessing web via a proxy?  If so,  reference this [Github discussion](https://github.com/npm/npm/issues/8872)
