### ISSUE TITLE
tidy-markdown

### ISSUE THREAD

**Issue by ruizp** [npm/npm#15936]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ x] Other (_see below for feature requests_):

#### What's going wrong?
I am unable to download tidy-markdown package on Atom. I keep getting at error message invalid active developer path. See snapshot below:

![image](https://cloud.githubusercontent.com/assets/21068352/23566957/c1069b72-0019-11e7-9e97-464704356e31.png)

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by slang800** [comment]
This looks like an [apm](https://github.com/atom/apm) issue rather than an npm one. Also, what command are you using to get this error and what is the full text output?
