### ISSUE TITLE
npm search returns empty Object in callback

### ISSUE THREAD

**Issue by MexXxo** [npm/npm#15933]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ X ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
npm search returns empty Object in callback

#### How can the CLI team reproduce the problem?
It's happening using npm programmatically in node.

```
    npm.commands.search(['someModule'], function(err, data){
        console.log('returned');
        if (err) {
            console.log(err);
            return;
        }
        console.log(data); //data is not the search result instead it's an Object
    });
```

Looking to the code, it comes from here: https://github.com/npm/npm/blob/latest/lib/search.js#L87

**Comment by legodude17** [comment]
Maybe instead, the search function should return the output stream?

**Comment by MexXxo** [comment]
As the callback comes after the stream has ended, it makes more sense to return the output all together. 
Depending if we use json or not as output, I would return a string, that the component that receives the callback can parse itself, also I would add the json output flag as argument to the search (currently it is only taken from config). 
I will create today a pull request with a solution, if this is okay.

**Comment by legodude17** [comment]
@MexXxo that's good. Then the core team can review it.

**Comment by MexXxo** [comment]
#15973 - PR here
