### ISSUE TITLE
Remove WARN on No license field

### ISSUE THREAD

**Issue by jhabdas** [npm/npm#15934]
Please remove the warning issued by NPM when the `license` field is not present in a package manifest. NPM should not warn [should someone choose](https://github.com/npm/npm/issues/8291#issuecomment-283976631) not to specify a license.

**Comment by tecfu** [comment]
I think this feature is valuable for someone who uses npm to create a proprietary module that they may not intend to publish. Especially in the case of a novice, who may not understand licensing.

**Comment by jhabdas** [comment]
@tecfu That's what `private: true` is for.

**Comment by jhabdas** [comment]
> license: (ISC) None
Sorry, license should be a valid SPDX license expression (without "LicenseRef"), "UNLICENSED", or "SEE LICENSE IN <filename>".

Good enough for me.

**Comment by jhabdas** [comment]
This sucks. I can't even get through the install without choosing a license:

<img width="638" alt="with NPM you must choose a SPDX license" src="https://cloud.githubusercontent.com/assets/440298/25045593/9fc0ce62-215f-11e7-92e6-3b2c2b6ca0c1.png">

**Comment by jhabdas** [comment]
For others who want more information to help protect your intellectual property, please read up on the Berne Convention: https://www.law.cornell.edu/treaties/berne/overview.html

Paraphrasing, <q>A copyright exists the moment a work becomes ‘fixed’</q>.

**Comment by jhabdas** [comment]
Seeing as how there are 3000 open issues and this is stagnating I'll just deal with the warning. Thanks.
