### ISSUE TITLE
LESS in PHPStorm

### ISSUE THREAD

**Issue by enforb** [npm/npm#15931]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [X ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

Sorry, but I really don't known what to do. I spended one day to solve the problem but I didn't it.

I want to install LESS in PHPStorm. I have followed the instructions  on the page but without success.

The problem is with package.json file. But HOW? WHERE? I am desperate :(
I recieved always the same problem:
```
npm WARN enoent ENOENT: no such file or directory, open 'C:\PhpstormProjects\
ECAR\package.json'
npm WARN ECAR No description
npm WARN ECAR No repository field.
npm WARN ECAR No README data
npm WARN ECAR No license field.

```
[2017-03-03T09_07_31_540Z-debug.txt](https://github.com/npm/npm/files/816335/2017-03-03T09_07_31_540Z-debug.txt)

Anybody help me?

**Comment by KenanY** [comment]
@enforb Does `C:\PhpstormProjects\ECAR\package.json` exist? If so, what is the `"name"` property set to?

**Comment by enforb** [comment]
No. I tried copy it from  /Roaming/npm/node_modules/less/package.json but whitout any results. I don't known how installer can make this json file in project folder.

**Comment by KenanY** [comment]
@enforb So, you are getting the error in your debug log by running `npm install less` in a directory that contains no `package.json`?

**Comment by enforb** [comment]
YES. I know that this file missing but if I copied json file from less dir and it will returns error. What will generate this json file in project dir?

**Comment by KenanY** [comment]
@enforb `npm init`?

**Comment by enforb** [comment]
Thanks, that's solve my problem. 
Just find some step by step solution to start work with nodejs and less in PHPstorm :)

Sometimes I feel like idiot. I am programming website in netbeans and I wanted to increase the level. BUT! 
First personalization is so difficulty for me now :(

Many thanks.
