### ISSUE TITLE
npm install / start gives error

### ISSUE THREAD

**Issue by rahulkrishnan98** [npm/npm#15935]
#### I'm opening this issue because:

  - [x] npm is producing an incorrect install.

  #### What's going wrong?
 npm install gives the following error. **https://gist.github.com/rahulkrishnan98/0bec021d73d1c2110de7c79d9dc5b58a**
#### How can the CLI team reproduce the problem?
     By running the Mozilla-science lab webpage : https://github.com/mozilla/science.mozilla.org (instructions provided in README
https://gist.github.com/rahulkrishnan98/0bec021d73d1c2110de7c79d9dc5b58a

### supporting information:

 - `npm -v` prints: 4.3.0
 - `node -v` prints: v7.6.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux

**Comment by legodude17** [comment]
Try running `npm rebuild node-sass` as the error log says.
