### ISSUE TITLE
error code MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by kartikcool** [npm/npm#15932]
#### I'm opening this issue because:
  - [x] Other (_see below for feature requests_):

Error Log Given 👍 
verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@3.3.12
3 info using node@v5.4.1
4 verbose stack Error: Cannot find module 'github-url-from-git'
4 verbose stack     at Function.Module._resolveFilename (module.js:325:15)
4 verbose stack     at Function.Module._load (module.js:276:25)
4 verbose stack     at Module.require (module.js:353:17)
4 verbose stack     at require (internal/module.js:12:17)
4 verbose stack     at Object.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\read-package-json\node_modules\normalize-package-data\lib\fixer.js:2:22)
4 verbose stack     at Module._compile (module.js:397:26)
4 verbose stack     at Object.Module._extensions..js (module.js:404:10)
4 verbose stack     at Module.load (module.js:343:32)
4 verbose stack     at Function.Module._load (module.js:300:12)
4 verbose stack     at Module.require (module.js:353:17)
4 verbose stack     at require (internal/module.js:12:17)
5 verbose cwd c:\SAP\MobileSDK3\KapselSDK\apps\fiori_client
6 error Windows_NT 6.3.9600
7 error argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
8 error node v5.4.1
9 error npm  v3.3.12
10 error code MODULE_NOT_FOUND
11 error Cannot find module 'github-url-from-git'
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
Try deleting and reinstalling `npm` and `node`.
