### ISSUE TITLE
npm error:  include the following file with any support request:

### ISSUE THREAD

**Issue by mjespinosam** [npm/npm#15937]
#### I'm opening this issue because:

  - [ ] npm is doing something I don't understand.

#### What's going wrong?

I have a request that i dont understand 
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 
npm ERR! Please include the following file with any support request:
npm ERR!     /Users/xxxxxxxx/npm-debug.log

Other user had the same problem but there wasn't an answer. 
https://github.com/npm/npm/issues/7884

### supporting information:

 - `npm -v` prints:

   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the web.
 - Container:
   - [ ] I develop using Vagrant on OS X or Linux.
 
<!--
    Thank you for contributing to npm! Please review this checklist
    before submitting your issue.

**Comment by legodude17** [comment]
As @KenanY said in #7884:

> Could you try the following?
`$ sudo chown -R $(whoami) "$HOME/.npm"`

**Comment by mjespinosam** [comment]
@legodude17 Thanks for your time!! I check  @panchowtf request but is not the same that mine. In that page there is other request: @tamirlancomas but it doesn't have answer and is the same that mine. 
Do you have any idea about my problem?

**Comment by legodude17** [comment]
Wait, which user are you referring too? Also, can you put the full `npm-debug.log` in a [gist](gist.github.com)?

**Comment by mjespinosam** [comment]
@legodude17  Im referring to @tamirlancomas request ( It is in the same gits of @panchowtf )
this is the full npm-debug.log

Thanks for your time.. !!!
MacBook-Pro-de-Jxxxxx:~ jxxxxxx$ npm start
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v7.7.0
npm ERR! npm  v4.1.2
npm ERR! path /Users/xxxxxx/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/Users/xxxxx/package.json'
npm ERR! enoent ENOENT: no such file or directory, open '/Users/xxxxx/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 
npm ERR! Please include the following file with any support request:
npm ERR!     /Users/xxxxxxx/npm-debug.log

**Comment by legodude17** [comment]
Do you have a `package.json` in `/Users/xxxxx/`

**Comment by mjespinosam** [comment]
Yes I have it!!! I installed package.json
Yesterday I didnt have this problem...mmmm
[and this is my first time working on this ]

**Comment by crisarevaloyr** [comment]
Hey! I have same problem. My localhost don't start whit "npm start". Help!!!

**Comment by mjespinosam** [comment]
@legodude17 
https://gist.github.com/mjespinosam/bcc444cfb555c5472bb665fe48565e9e
This is the gits?

**Comment by CrazyCattle** [comment]
@crisarevaloyr  @mjespinosam   try to fix package.json 'name',my problem solved

**Comment by mjespinosam** [comment]
My problem was that the terminal was not in the directory indicated ... i put the route and it works!
Thanks to @CrazyCattle @legodude17

**Comment by Gatoreno** [comment]
how did you redirect the root?

**Comment by legodude17** [comment]
I am guessing `cd`

**Comment by tursunbaevz** [comment]
can you please explain how fix this ? nobody explain it(

**Comment by legodude17** [comment]
Make sure you are in a directory with a `package.json` (`cat package.json`).

**Comment by harish-rzt** [comment]
I had the same issue, fixed it by adding the "script": {...} to my package.json.

{
    "name": <package-name>,
    "version": "1.0.0",
    "description": "",
    "scripts": {
        **"start": "webpack-dev-server"**
    },
    "dependencies": {...},
    "devDependencies": {...}
}

// you should add the start cmd to your script object.

**Comment by harishv6665** [comment]
I had the same issue, fixed it by adding the "script": {...} to my package.json.

{
"name": ,
"version": "1.0.0",
"description": "",
"scripts": {
**"start": "webpack-dev-server"**
},
"dependencies": {...},
"devDependencies": {...}
}

// you should add the start cmd to your script object.

**Comment by imraghava** [comment]
I am getting the same problem. Can anyone tell me how to solve this? 

$ npm start
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! file C:\angular\ng2-fundamentals\package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected token 'l' at 6:41
npm ERR!     "start": "concurrently \"tsc -w\" "\lite-server\",
npm ERR!                                         ^
npm ERR! File: C:\angular\ng2-fundamentals\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     C:\angular\ng2-fundamentals\npm-debug.log

**Comment by Sachin124** [comment]
npm install
npm ERR! git clone --template=/home/sachin/.npm/_git-remotes/_templates --mirror ssh://git@github.com/don/cordova-filechooser.git /home/sachin/.npm/_git-remotes/git-ssh-git-github-com-don-cordova-filechooser-git-445dfceb: Cloning into bare repository '/home/sachin/.npm/_git-remotes/git-ssh-git-github-com-don-cordova-filechooser-git-445dfceb'...
npm ERR! git clone --template=/home/sachin/.npm/_git-remotes/_templates --mirror ssh://git@github.com/don/cordova-filechooser.git /home/sachin/.npm/_git-remotes/git-ssh-git-github-com-don-cordova-filechooser-git-445dfceb: Permission denied (publickey).
npm ERR! git clone --template=/home/sachin/.npm/_git-remotes/_templates --mirror ssh://git@github.com/don/cordova-filechooser.git /home/sachin/.npm/_git-remotes/git-ssh-git-github-com-don-cordova-filechooser-git-445dfceb: fatal: Could not read from remote repository.
npm ERR! git clone --template=/home/sachin/.npm/_git-remotes/_templates --mirror ssh://git@github.com/don/cordova-filechooser.git /home/sachin/.npm/_git-remotes/git-ssh-git-github-com-don-cordova-filechooser-git-445dfceb:
npm ERR! git clone --template=/home/sachin/.npm/_git-remotes/_templates --mirror ssh://git@github.com/don/cordova-filechooser.git /home/sachin/.npm/_git-remotes/git-ssh-git-github-com-don-cordova-filechooser-git-445dfceb: Please make sure you have the correct access rights
npm ERR! git clone --template=/home/sachin/.npm/_git-remotes/_templates --mirror ssh://git@github.com/don/cordova-filechooser.git /home/sachin/.npm/_git-remotes/git-ssh-git-github-com-don-cordova-filechooser-git-445dfceb: and the repository exists.
npm ERR! Linux 4.4.0-89-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code 128

npm ERR! Command failed: git clone --template=/home/sachin/.npm/_git-remotes/_templates --mirror ssh://git@github.com/don/cordova-filechooser.git /home/sachin/.npm/_git-remotes/git-ssh-git-github-com-don-cordova-filechooser-git-445dfceb
npm ERR! Cloning into bare repository '/home/sachin/.npm/_git-remotes/git-ssh-git-github-com-don-cordova-filechooser-git-445dfceb'...
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/sachin/Desktop/PumpMonitoring/npm-debug.log

**Comment by priyankakrvino** [comment]
i'm also having the same error like below
npm ERR! Linux 4.10.0-28-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "mqtt" "-g"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! path /usr/local/lib
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/usr/local/lib'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, access '/usr/local/lib']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/intern-iot/npm-debug.log


how to resolve this error???

**Comment by SergFes** [comment]
There may be a problem with different versions of the webpack. The global version differs from the local version.

**Comment by 256yangwei** [comment]
Please try running this command again as root/Administrator.

try use to add "sudo":
sudo  npm install -g truffle

**Comment by vndsapkal** [comment]
Same problem happen with me please tell me how to fix it.

npm ERR! Linux 4.2.0-42-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "create-react-app"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.3
npm ERR! path /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!     at Error (native)
npm ERR!  { Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!     at Error (native)
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/fz1/npm-debug.log
