### ISSUE TITLE
Subpages for README files

### ISSUE THREAD

**Issue by natewatson999** [npm/npm#15940]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's the feature?
NPM should support subpages for README files.

#### What problem is the feature intended to solve?
Currently, NPM only allows for a single README file to be used for documentation on the web interface. This is a problem because there are several modules which allow for a lot of different functionality, and as a result, have obnoxiously long README files. This makes organization and documentation maintenance harder. 

If a single module could have multiple README files, have all of them viewable on the web interface, and state which one to use as the root document; this problem would go away.

#### Is the absence of this feature blocking you or your team? If so, how?
It is not blocking, merely annoying.

#### Is this feature similar to an existing feature in another tool?
Yes.
- MediaWiki allows for subpages for cases where a regular page is cumbersomely long. 
- Javadoc has a primitive version: For packages, there's a root page of documentation, and each class, interface, separate enum, etc; has a subpage. 
* Hoogle has this feature: https://hackage.haskell.org/package/regex

#### Is this a feature you're prepared to implement, with support from the npm CLI team?
I am not sure.

**Comment by KenanY** [comment]
@natewatson999 Do you think this is best taken to <https://github.com/npm/www>?

**Comment by natewatson999** [comment]
Yes. I will move it there.
