### ISSUE TITLE
npm start crashing

### ISSUE THREAD

**Issue by HarshithaGandamalla** [npm/npm#15941]
npm start.Then an error occurs.

> c4-sgweb@0.0.0 start C:\Users\Becky\Desktop\node-course\sockets\C4SG\C4SGWeb
> ng serve

Cannot read property 'glob' of null
TypeError: Cannot read property 'glob' of null

Full log here:
https://gist.github.com/HarshithaGandamalla/3d737a52f1119b32397d6fd98d1cd3ef

my package.json:

{
  "name": "c4-sgweb",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^2.4.0",
    "@angular/compiler": "^2.4.0",
    "@angular/core": "^2.4.0",
    "@angular/forms": "^2.4.0",
    "@angular/http": "^2.4.0",
    "@angular/material": "^2.0.0-beta.2",
    "@angular/platform-browser": "^2.4.0",
    "@angular/platform-browser-dynamic": "^2.4.0",
    "@angular/router": "^3.4.0",
    "angular2-materialize": "^6.7.1",
    "core-js": "^2.4.1",
    "jquery": "^2.2.4",
    "materialize-css": "^0.97.8",
    "rxjs": "^5.1.0",
    "underscore": "^1.8.3",
    "zone.js": "^0.7.6"
  },
  "devDependencies": {
    "@angular/cli": "1.0.0-rc.0",
    "@angular/compiler-cli": "^2.4.0",
    "@types/jasmine": "2.5.38",
    "@types/node": "~6.0.60",
    "codelyzer": "~2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.4.2",
    "typescript": "~2.0.0"
  }
}

OS Windows
node v6.10.0
npm 3.10.10

Thanks.

**Comment by KenanY** [comment]
Seems like this error is coming from `ng serve`, not `npm`. `npm` is just catching the error and showing it to you.
