### ISSUE TITLE
missing script

### ISSUE THREAD

**Issue by higimo** [npm/npm#15959]
```
<...>
module.exports = {
  scripts: {
    dev: "webpack",
  }
<...>
}
```
```
> npm run dev
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "\node.exe" "\npm\node_modules\npm\bin\npm-cli.js" "run" "dev"
npm ERR! node v6.9.5
npm ERR! npm  v4.1.2
npm ERR! missing script: dev
```

https://github.com/npm/npm/issues/8193 Is not resolution, i try.

What am I doing wrong?

**Comment by KenanY** [comment]
@higimo Do you have a `"dev"` script defined in your `package.json`?

**Comment by Esmelealem** [comment]
npm ERR! node v7.7.1
npm ERR! npm  v4.1.2

npm ERR! missing script: start
npm ERR!
This error is happened when I try to start npm, 'npm start'

**Comment by legodude17** [comment]
@Esmelealem do you have a `start` script in your `package.json`?

**Comment by higimo** [comment]
I do not use `npm start` before `npm run dev`. It is not right? But I do not need a running server. I need only the execution of the script, so do not write it every time. It`s not rly?

**Comment by legodude17** [comment]
@higimo your need to have a script in your `package.json` like this:
```
"scripts": {
    "dev": "webpack"
}
```
Then you can use `npm run dev`.

**Comment by higimo** [comment]
@legodude17 thanks you very much! it`s works.

Sorry for this issue, it was not necessary to write here.
