### ISSUE TITLE
npm is producing an incorrect install.

### ISSUE THREAD

**Issue by hitesh1989** [npm/npm#15952]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.10
3 info using node@v6.10.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle angular-examples-master@1.0.0~prestart: angular-examples-master@1.0.0
6 verbose lifecycle angular-examples-master@1.0.0~prestart: unsafe-perm in lifecycle true
7 verbose lifecycle angular-examples-master@1.0.0~prestart: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\xampp\htdocs\toh\node_modules\.bin;C:\Users\Hitesh\bin;C:\Program Files\Git\mingw32\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw32\bin;C:\Program Files\Git\usr\bin;C:\Users\Hitesh\bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\xampp\php;C:\ProgramData\ComposerSetup\bin;C:\Program Files\Git\cmd;C:\Program Files\nodejs;C:\Users\Hitesh\AppData\Roaming\Composer\vendor\bin;C:\Users\Hitesh\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
8 verbose lifecycle angular-examples-master@1.0.0~prestart: CWD: C:\xampp\htdocs\toh
9 silly lifecycle angular-examples-master@1.0.0~prestart: Args: [ '/d /s /c', 'npm run build' ]
10 silly lifecycle angular-examples-master@1.0.0~prestart: Returned: code: 1  signal: null
11 info lifecycle angular-examples-master@1.0.0~prestart: Failed to exec prestart script
12 verbose stack Error: angular-examples-master@1.0.0 prestart: `npm run build`
12 verbose stack Exit status 1
12 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
12 verbose stack     at emitTwo (events.js:106:13)
12 verbose stack     at EventEmitter.emit (events.js:191:7)
12 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
12 verbose stack     at emitTwo (events.js:106:13)
12 verbose stack     at ChildProcess.emit (events.js:191:7)
12 verbose stack     at maybeClose (internal/child_process.js:877:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
13 verbose pkgid angular-examples-master@1.0.0
14 verbose cwd C:\xampp\htdocs\toh
15 error Windows_NT 6.1.7601
16 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
17 error node v6.10.0
18 error npm  v3.10.10
19 error code ELIFECYCLE
20 error angular-examples-master@1.0.0 prestart: `npm run build`
20 error Exit status 1
21 error Failed at the angular-examples-master@1.0.0 prestart script 'npm run build'.
21 error Make sure you have the latest version of node.js and npm installed.
21 error If you do, this is most likely a problem with the angular-examples-master package,
21 error not with npm itself.
21 error Tell the author that this fails on your system:
21 error     npm run build
21 error You can get information on how to open an issue for this project with:
21 error     npm bugs angular-examples-master
21 error Or if that isn't available, you can get their info via:
21 error     npm owner ls angular-examples-master
21 error There is likely additional logging output above.
22 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@hitesh1989 Looks like your `"build"` script is throwing an error. I suggest you try running it alone, and then running the source of the script directly. This should provide more insight as to why the script is failing. Closing since this is not an issue in `npm` itself; it's just telling you that one of your own scripts is throwing an error code.
