### ISSUE TITLE
npm installation failure

### ISSUE THREAD

**Issue by Zizu24** [npm/npm#15955]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

I have been trying the whole week to install npm 4.1.2 but always but always get error log
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\user\package.json'
npm WARN user No description
npm WARN user No repository
npm WARN user No README data
npm WARN user No license field

Please what should I do

**Comment by mbutsykin** [comment]
These are warnings, not errors.
Are you sure it's not installed?
run `npm -v` and check it

**Comment by Zizu24** [comment]
Both node and npm 4.1.2 are installed. But when i run d code npm install
then it brings out the error log
0638

On Mar 6, 2017 10:45 AM, "Maksym Butsykin" <notifications@github.com> wrote:

These are warnings, not errors.
Are you sure it's not installed?
run npm -v and check it

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/npm/npm/issues/15955#issuecomment-284362383>, or mute
the thread

**Comment by mbutsykin** [comment]
Sorry, i missunderstand your issue, thought you was trying to install npm.

According to your's logs, looks like you are located in the wrong directory.
```
C:\Users\user\
```

You should run `npm i` from project directory with `dependencies` listed in `package.json` file.
