### ISSUE TITLE
Windows_NT 10.0.14393

### ISSUE THREAD

**Issue by AliceIgorevna** [npm/npm#15971]
- npm is crashing.
  - npm is producing an incorrect install.
  - npm is doing something I don't understand.

Some error occured Windows_NT 10.0.14393 and its totally misunderstood why.
{code} Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "server:dev:hmr" "--" "--proxy-requests"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! globepayroll-frontend-payrollUi@0.1.0 server:dev:hmr: `npm run server:dev -- --hot "--proxy-requests"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the globepayroll-frontend-payrollUi@0.1.0 server:dev:hmr script 'npm run server:dev -- --hot "--proxy-requests"'.
npm ERR! This is most likely a problem with the globepayroll-frontend-payrollUi package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run server:dev -- --hot "--proxy-requests"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs globepayroll-frontend-payrollUi
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls globepayroll-frontend-payrollUi
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\alice\globepayroll\gp\ui\npm-debug.log
{code}

 - node v4.6.0
 - npm  v2.15.9
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows
 - Network issues:
   - Geographic location where npm was run:
   - I use a proxy to connect to the npm registry.
   - I use a proxy to connect to the web.
   - I use a proxy when downloading Git repos.
   - I access the npm registry via a VPN

[npm-debug.txt](https://github.com/npm/npm/files/824668/npm-debug.txt)

**Comment by legodude17** [comment]
Does `npm run server:dev -- --hot "--proxy-requests"` work?

**Comment by kaashyan** [comment]
C:\xampp\htdocs\express>npm install express
npm ERR! Windows_NT 6.1.7600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "express"
npm ERR! node v7.3.0
npm ERR! npm  v3.10.10

npm ERR! Invalid protocol: null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\xampp\htdocs\express\npm-debug.log

C:\xampp\htdocs\express>npm config get registry
http://registry.npmjs.org/

C:\xampp\htdocs\express>npm install express
npm ERR! Windows_NT 6.1.7600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "express"
npm ERR! node v7.3.0
npm ERR! npm  v3.10.10

npm ERR! Invalid protocol: null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\xampp\htdocs\express\npm-debug.log

`C:\xampp\htdocs\express>`

**Comment by AliceIgorevna** [comment]
@legodude17 no, it doesn't work for me.

**Comment by legodude17** [comment]
@AliceIgorevna then the problem is with your setup, not `npm`.
