### ISSUE TITLE
Cannot Install Angular 2

### ISSUE THREAD

**Issue by DZcoderX** [npm/npm#15972]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Image link: 
https://cloud.githubusercontent.com/assets/16616714/23662280/0e26f69e-031d-11e7-9225-43f8cdb8bd51.png

#### How can the CLI team reproduce the problem?

The Debug Log: 

### supporting information:

 - `npm -v` prints: 4.1.2
 - `node -v` prints: v7.7.1
 - `npm config get registry` prints: 
https://cloud.githubusercontent.com/assets/16616714/23662441/9456b88a-031d-11e7-9c27-661c77a712c9.png

 - Windows, OS X/macOS, or Linux?: Windows
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [x ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by JaggerTailor** [comment]
Hello,

@angular/Angular2 pacakges are getting installed only at node version 6.9.1 and npm version 3.10.8

Downgrade your node using Node Version Manager and it will work

**Comment by DZcoderX** [comment]
Thank you so much for the response!!
What command would I run? How do I do that? 
OR
Could you link me to the download link of version 6.9.1 and npm version 3.10.8

**Comment by JaggerTailor** [comment]
http://stackoverflow.com/questions/7718313/how-to-change-to-an-older-version-of-node-js

**Comment by DZcoderX** [comment]
I already went on there and it gave me this error 
https://cloud.githubusercontent.com/assets/16616714/23665298/0d8b244a-0326-11e7-9901-03a7b691de13.png

so i was hoping there was another way : P

**Comment by DZcoderX** [comment]
Is there an offline (air gap) kind of installation perhaps?

**Comment by JaggerTailor** [comment]
If you are on windows you need to download nvm-setup.zip from https://github.com/coreybutler/nvm-windows/releases extract it and install, then try the steps which are in my earlier link

**Comment by DZcoderX** [comment]
Still the same error...
i'm beginning to think it because I'm behind a proxy (as stated). Any idea how to configure the proxy settings?
https://cloud.githubusercontent.com/assets/16616714/23674152/e99610d2-0342-11e7-8fc2-b228ec8b0eba.png

**Comment by jotatoledo** [comment]
One option is to put your proxy credentials in the npm config file. To do this:

- Open a console dialog
- Type npm config edit
- Inside the file, after 
```
;;;;
; npm userconfig file
; this is a simple ini-formatted file
; lines that start with semi-colons are comments.
; read `npm help config` for help on the various options
;;;;
```

set the following options:

```
strict-ssl=false
proxy=http://%3C<user_name>%3E:%3C<password>%3E@<proxy_address>:8080/
https-proxy=http://%3C<user_name>%3E:%3C<password>%3E@<proxy_address>:8080/
```
<user_name> should be your user account without domain name.
<password> the password for the given account
<proxy_address> your proxy address
(without all the < and >)

It workds for me this way, but Im aware that having the credentials in a text file isnt really the best approach.
Hope it helps
