### ISSUE TITLE
NPM Angular/cli install failure

### ISSUE THREAD

**Issue by aseacrest** [npm/npm#15970]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x ] Other (_see below for feature requests_):

#### What's going wrong?

running npm install -g @angular/cli is failing

here is output of npm-debug.log:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   '@angular/cli' ]
2 info using npm@3.10.10
3 info using node@v6.10.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData @angular/cli
8 silly fetchNamedPackageData @angular/cli
9 silly mapToRegistry name @angular/cli
10 silly mapToRegistry scope (from package name) @angular
11 verbose mapToRegistry no registry URL found in name for scope @angular
12 silly mapToRegistry using default registry
13 silly mapToRegistry registry https://registry.npmjs.org/
14 silly mapToRegistry data Result {
14 silly mapToRegistry   raw: '@angular/cli',
14 silly mapToRegistry   scope: '@angular',
14 silly mapToRegistry   escapedName: '@angular%2fcli',
14 silly mapToRegistry   name: '@angular/cli',
14 silly mapToRegistry   rawSpec: '',
14 silly mapToRegistry   spec: 'latest',
14 silly mapToRegistry   type: 'tag' }
15 silly mapToRegistry uri https://registry.npmjs.org/@angular%2fcli
16 verbose request uri https://registry.npmjs.org/@angular%2fcli
17 verbose request no auth needed
18 info attempt registry request try #1 at 8:01:27 AM
19 verbose request id 12e4266befcb4a8d
20 http request GET https://registry.npmjs.org/@angular%2fcli
21 info retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.44.162:443
22 info attempt registry request try #2 at 8:01:58 AM
23 http request GET https://registry.npmjs.org/@angular%2fcli
24 info retry will retry, error on last attempt: Error: write EPROTO 101057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:794:
25 info attempt registry request try #3 at 8:03:10 AM
26 http request GET https://registry.npmjs.org/@angular%2fcli
27 silly fetchPackageMetaData Error: write EPROTO 101057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:794:
27 silly fetchPackageMetaData
27 silly fetchPackageMetaData     at exports._errnoException (util.js:1022:11)
27 silly fetchPackageMetaData     at WriteWrap.afterWrite (net.js:801:14)
27 silly fetchPackageMetaData  error for @angular/cli { Error: write EPROTO 101057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:794:
27 silly fetchPackageMetaData
27 silly fetchPackageMetaData     at exports._errnoException (util.js:1022:11)
27 silly fetchPackageMetaData     at WriteWrap.afterWrite (net.js:801:14) code: 'EPROTO', errno: 'EPROTO', syscall: 'write' }
28 silly rollbackFailedOptional Starting
29 silly rollbackFailedOptional Finishing
30 silly runTopLevelLifecycles Finishing
31 silly install printInstalled
32 verbose stack Error: write EPROTO 101057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:794:
32 verbose stack
32 verbose stack     at exports._errnoException (util.js:1022:11)
32 verbose stack     at WriteWrap.afterWrite (net.js:801:14)
33 verbose cwd C:\Windows\system32
34 error Windows_NT 6.1.7601
35 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli"
36 error node v6.10.0
37 error npm  v3.10.10
38 error code EPROTO
39 error errno EPROTO
40 error syscall write
41 error write EPROTO 101057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:794:
42 error If you need help, you may report this error at:
42 error     <https://github.com/npm/npm/issues>
43 verbose exit [ 1, true ]

#### How can the CLI team reproduce the problem?

run npm install -g @angular/cli

### supporting information:

 - `npm -v` prints: 3.10.10
 - `node -v` prints: v6.10.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows
 - Network issues:
   - Geographic location where npm was run:
   - [x] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by JaggerTailor** [comment]
Downgrade your node to 6.9.1 and npm to 3.10.8, beyond this anuglar stuff is not getting installed using npm

**Comment by JaggerTailor** [comment]
http://stackoverflow.com/questions/7718313/how-to-change-to-an-older-version-of-node-js
