### ISSUE TITLE
Adding a local pre/postinstall hook for dependencies

### ISSUE THREAD

**Issue by Nargonath** [npm/npm#15984]
#### What's the feature?

I would like to be able to execute a script after installing a dependency in my project using `npm install <package>` and having access to the package name as written in the `package.json` in my script.

#### What problem is the feature intended to solve?

I am aware of the `postinstall` hook but as far as my project is concerned it is only running when doing `npm install` whereas I want it to be triggered as well on `npm install <package>`. My use case is that I use webpack for building my project and I want a particular webpack build to be run only after installing dependencies (in my case DLL bundle generation).

#### Is the absence of this feature blocking you or your team? If so, how?

Not blocking but cumbersome. Every time someone on the project adds or removes a dependency he has to remember to run the npm script manually himself which is prone to error/forgetting.

#### Is this feature similar to an existing feature in another tool?

Not that I am aware of but if I can do it in npm I'll do it in yarn as well.

#### Is this a feature you're prepared to implement, with support from the npm CLI team?

Definitely.

Thanks for your time.

**Comment by Nargonath** [comment]
No need for it in the end. I just created a script called on prestart that checks if the DLL needs to be generated and in that case call the npm run build:dll command.

**Comment by HamzaAnis** [comment]
Can you please share the script.

**Comment by Nargonath** [comment]
@HamzaAnis Yes, sure thing. Here you go: https://github.com/dixeed/angularjs-seed-webpack/blob/master/config/dll-script.js.

I just call it as is in the package.json script section: `"prestart": "node config/dll-script.js"`
