### ISSUE TITLE
Error while installing babel -  DEPTH_ZERO_SELF_SIGNED_CERT

### ISSUE THREAD

**Issue by scorpion-3** [npm/npm#15989]
Hello, 

I am a newbie to npm, having this issue while installing babel.  
I am getting this error: DEPTH_ZERO_SELF_SIGNED_CERT

Please helpe me out on this one.

Debug Log : 

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--save-dev',
1 verbose cli   'babel-cli' ]
2 info using npm@3.10.10
3 info using node@v6.10.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData babel-cli
8 silly fetchNamedPackageData babel-cli
9 silly mapToRegistry name babel-cli
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'babel-cli',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'babel-cli',
12 silly mapToRegistry   name: 'babel-cli',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/babel-cli
14 verbose request uri https://registry.npmjs.org/babel-cli
15 verbose request no auth needed
16 info attempt registry request try #1 at 4:33:11 PM
17 verbose request id f32c1659be3c76a1
18 http request GET https://registry.npmjs.org/babel-cli
19 info retry will retry, error on last attempt: Error: self signed certificate
20 info attempt registry request try #2 at 4:33:22 PM
21 http request GET https://registry.npmjs.org/babel-cli
22 info retry will retry, error on last attempt: Error: self signed certificate
23 info attempt registry request try #3 at 4:34:23 PM
24 http request GET https://registry.npmjs.org/babel-cli
25 silly fetchPackageMetaData Error: self signed certificate
25 silly fetchPackageMetaData     at Error (native)
25 silly fetchPackageMetaData     at TLSSocket.<anonymous> (_tls_wrap.js:1085:38)
25 silly fetchPackageMetaData     at emitNone (events.js:86:13)
25 silly fetchPackageMetaData     at TLSSocket.emit (events.js:185:7)
25 silly fetchPackageMetaData     at TLSSocket._finishInit (_tls_wrap.js:603:8)
25 silly fetchPackageMetaData     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:433:38)
25 silly fetchPackageMetaData  error for babel-cli { Error: self signed certificate
25 silly fetchPackageMetaData     at Error (native)
25 silly fetchPackageMetaData     at TLSSocket.<anonymous> (_tls_wrap.js:1085:38)
25 silly fetchPackageMetaData     at emitNone (events.js:86:13)
25 silly fetchPackageMetaData     at TLSSocket.emit (events.js:185:7)
25 silly fetchPackageMetaData     at TLSSocket._finishInit (_tls_wrap.js:603:8)
25 silly fetchPackageMetaData     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:433:38) code: 'DEPTH_ZERO_SELF_SIGNED_CERT' }
26 silly rollbackFailedOptional Starting
27 silly rollbackFailedOptional Finishing
28 silly runTopLevelLifecycles Finishing
29 silly install printInstalled
30 verbose stack Error: self signed certificate
30 verbose stack     at Error (native)
30 verbose stack     at TLSSocket.<anonymous> (_tls_wrap.js:1085:38)
30 verbose stack     at emitNone (events.js:86:13)
30 verbose stack     at TLSSocket.emit (events.js:185:7)
30 verbose stack     at TLSSocket._finishInit (_tls_wrap.js:603:8)
30 verbose stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:433:38)
31 verbose cwd D:\React
32 error Windows_NT 10.0.14393
33 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save-dev" "babel-cli"
34 error node v6.10.0
35 error npm  v3.10.10
36 error code DEPTH_ZERO_SELF_SIGNED_CERT
37 error self signed certificate
38 error If you need help, you may report this error at:
38 error     <https://github.com/npm/npm/issues>
39 verbose exit [ 1, true ]

**Comment by legodude17** [comment]
Have you taken a look at http://blog.npmjs.org/post/78165272245/more-help-with-selfsignedcertinchain-and-npm? See if the steps outlined there work for you.

If it does NOT:

1. Are you behind a proxy?
2. How are you trying to use it?
