### ISSUE TITLE
npm ERR @F5 unit

### ISSUE THREAD

**Issue by jaisingla** [npm/npm#15985]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?

[root@testapm:Active:Standalone] ilx # cd /var/ilx/workspaces/Common/ldap_modify_workspace/extensions/ldap_modify_extension
[root@testapm:Active:Standalone] ldap_modify_extension # npm install ldapjs -save
npm ERR! Linux 2.6.32-431.56.1.el6.f5.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/.npm__" "install" "ldapjs" "-save"
npm ERR! node v0.12.15
npm ERR! npm  v2.15.1
npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! syscall getaddrinfo

npm ERR! getaddrinfo EAI_AGAIN
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /var/ilx/workspaces/Common/ldap_modify_workspace/extensions/ldap_modify_extension/npm-debug.log
[root@testapm:Active:Standalone] ldap_modify_extension #

### supporting information:

 - `npm -v` prints:   2.15.1
 - `node -v` prints:  v0.12.15
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by jaisingla** [comment]
i get this fixed, dns issue at F5, not able to resolve github.com

**Comment by legodude17** [comment]
Do you have a stable internet connection?
