### ISSUE TITLE
npm is producing an incorrect install.

### ISSUE THREAD

**Issue by RJ77** [npm/npm#15992]
#### I'm opening this issue because:

  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
 

[npm-log.txt](https://github.com/npm/npm/files/833030/npm-log.txt)

**Comment by legodude17** [comment]
Do you have a stable internet connection? Also make sure to update `npm`.

**Comment by RJ77** [comment]
Thank you for the help. Command below solved the problem.

"echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf &&
sudo sysctl -p"
