### ISSUE TITLE
Automatically execute 'link' directly after 'install'

### ISSUE THREAD

**Issue by eisbehr-** [npm/npm#15999]
#### What's the feature?
Actuelly it seems like there is no build-in way to execute binary linking on installation. It would nice to have a way to run `npm link` directly after/with `npm install` too. Maybe with an additional parameter like `npm install -l`.

#### What problem is the feature intended to solve?
Currently the only way to do this is to execute `npm install` and afterward `npm link`. It is even no solution to create a custom script, like `npm install && npm link`, because then everyone needs to know the call and cant just use `install`. It's not possible to use `postinstall` with `npm link` too, beacuse this would result in a loop.

#### Is the absence of this feature blocking you or your team? If so, how?
Hard to say. Lets say it would be easier with such feature! ;)

#### Is this feature similar to an existing feature in another tool?
I would say yes. It's just the execution of `npm link` after installation with an parameter on `npm install`. No new functionallity in general.

#### Is this a feature you're prepared to implement, with support from the npm CLI team?
No.

**Comment by legodude17** [comment]
It could be something like `npm it`, so maybe a new command `npm il`.

**Comment by eisbehr-** [comment]
Yes, this would be nice too!
