### ISSUE TITLE
unable to install npm

### ISSUE THREAD

**Issue by GirishBhat** [npm/npm#15990]
@ashleygwilliams @bcoe @ceejbot @nexdrew @zkat @timoxley
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g' ]
2 info using npm@1.4.28
3 info using node@v0.10.36
4 verbose cache add [ '.', null ]
5 verbose cache add name=undefined spec="." args=[".",null]
6 verbose parsed url { protocol: null,
6 verbose parsed url   slashes: null,
6 verbose parsed url   auth: null,
6 verbose parsed url   host: null,
6 verbose parsed url   port: null,
6 verbose parsed url   hostname: null,
6 verbose parsed url   hash: null,
6 verbose parsed url   search: null,
6 verbose parsed url   query: null,
6 verbose parsed url   pathname: '.',
6 verbose parsed url   path: '.',
6 verbose parsed url   href: '.' }
7 silly lockFile 3a52ce78- .
8 verbose lock . C:\Users\bgh40689\AppData\Roaming\npm-cache\3a52ce78-.lock
9 silly lockFile 3a52ce78- .
10 silly lockFile 3a52ce78- .
11 error addLocal Could not install .
12 error Error: ENOENT, open 'C:\Program Files\Git\package.json'
13 error If you need help, you may report this *entire* log,
13 error including the npm and node versions, at:
13 error     <http://github.com/npm/npm/issues>
14 error System Windows_NT 6.1.7601
15 error command "C:\\Program Files\\nodejs\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g"
16 error cwd C:\Program Files\Git
17 error node -v v0.10.36
18 error npm -v 1.4.28
19 error path C:\Program Files\Git\package.json
20 error code ENOENT
21 error errno 34
22 verbose exit [ 34, true ]

**Comment by stripedpajamas** [comment]
@GirishBhat what were you trying to do? I'll be able to better assist you if I know the end goal.

It looks like you were running npm with the `install -g` option, but didn't specify a package to actually install. That would only work if there was a package.json file in the current working directory (which in your case was C:\Program Files\Git -- and there wasn't a package.json file there). 

Also it looks like you're using a _really_ old version of node & npm. I'd update to the latest from https://nodejs.org

**Comment by pierrecholhot** [comment]
Related issue by the same user: https://github.com/npm/npm/issues/15340
