### ISSUE TITLE
Failed at the bufferutil@1.3.0 install script 'node-gyp rebuild'.

### ISSUE THREAD

**Issue by daring123** [npm/npm#15998]
HI:
    I install "stf" by npm .
    my command is "npm install -g stf ". I got Wrong.
    Here is the error message.Hope to help me solve it .Thanks

65470 verbose pkgid bufferutil@1.3.0
65471 verbose cwd /home/hzqa/wireless
65472 error Linux 3.10.0-514.el7.x86_64
65473 error argv "/home/hzqa/wireless/node-v6.10.0/bin/node" "/home/hzqa/wireless/node-v6.10.0/bin/npm" "install" "-g" "stf"
65474 error node v6.10.0
65475 error npm  v3.10.10
65476 error file sh
65477 error code ELIFECYCLE
65478 error errno ENOENT
65479 error syscall spawn
65480 error bufferutil@1.3.0 install: `node-gyp rebuild`
65480 error spawn ENOENT
65481 error Failed at the bufferutil@1.3.0 install script 'node-gyp rebuild'.
65481 error Make sure you have the latest version of node.js and npm installed.
65481 error If you do, this is most likely a problem with the bufferutil package,
65481 error not with npm itself.
65481 error Tell the author that this fails on your system:
65481 error     node-gyp rebuild
65481 error You can get information on how to open an issue for this project with:
65481 error     npm bugs bufferutil
65481 error Or if that isn't available, you can get their info via:
65481 error     npm owner ls bufferutil
65481 error There is likely additional logging output above.
65482 verbose exit [ 1, true ]

**Comment by legodude17** [comment]
You should file an issue with `bufferutil`. This is not a problem with `npm`.
