### ISSUE TITLE
I am not able to install 'http-proxy'

### ISSUE THREAD

**Issue by ansabd** [npm/npm#15997]
When I try to install HTTP-proxy by typing 'npm install HTTP-proxy' it shows some error, I would not understand that error so I have uploaded log file with this issue.
Please check it out and tell me what the error is

[npm-debug.txt](https://github.com/npm/npm/files/833868/npm-debug.txt)

**Comment by Kepro** [comment]
this is not problem of NPM it's problem of http-proxy library

**Comment by KenanY** [comment]
@ansabd Make sure the `"name"` field in your `package.json` is not set to the same name as any of your dependencies (which appears to be the case here). Try changing it to something more unique.
