### ISSUE TITLE
ERR when I npm install webpack -D

### ISSUE THREAD

**Issue by web-tiny** [npm/npm#16006]
Prompt message：
![0170311150306](https://cloud.githubusercontent.com/assets/24711260/23821459/f4170c90-066d-11e7-996d-f199e0badcff.png)
The file  information:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'webpack',
1 verbose cli   '-D' ]
2 info using npm@3.7.3
3 info using node@v5.9.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData webpack
8 silly fetchNamedPackageData webpack
9 silly mapToRegistry name webpack
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/webpack
13 verbose request uri https://registry.npmjs.org/webpack
14 verbose request no auth needed
15 info attempt registry request try #1 at 15:00:19
16 verbose request id e2072a6d16bbace8
17 verbose etag W/"58c30ade-e4c30"
18 verbose lastModified Fri, 10 Mar 2017 20:21:50 GMT
19 http request GET https://registry.npmjs.org/webpack
20 http 304 https://registry.npmjs.org/webpack
21 verbose headers { date: 'Sat, 11 Mar 2017 07:00:19 GMT',
21 verbose headers   via: '1.1 varnish',
21 verbose headers   'cache-control': 'max-age=300',
21 verbose headers   etag: 'W/"58c30ade-e4c30"',
21 verbose headers   age: '158',
21 verbose headers   connection: 'keep-alive',
21 verbose headers   'x-served-by': 'cache-itm7422-ITM',
21 verbose headers   'x-cache': 'HIT',
21 verbose headers   'x-cache-hits': '2',
21 verbose headers   'x-timer': 'S1489215619.917168,VS0,VE0',
21 verbose headers   vary: 'Accept-Encoding' }
22 silly get cb [ 304,
22 silly get   { date: 'Sat, 11 Mar 2017 07:00:19 GMT',
22 silly get     via: '1.1 varnish',
22 silly get     'cache-control': 'max-age=300',
22 silly get     etag: 'W/"58c30ade-e4c30"',
22 silly get     age: '158',
22 silly get     connection: 'keep-alive',
22 silly get     'x-served-by': 'cache-itm7422-ITM',
22 silly get     'x-cache': 'HIT',
22 silly get     'x-cache-hits': '2',
22 silly get     'x-timer': 'S1489215619.917168,VS0,VE0',
22 silly get     vary: 'Accept-Encoding' } ]
23 verbose etag https://registry.npmjs.org/webpack from cache
24 verbose get saving webpack to C:\Users\Administrator\AppData\Roaming\npm-cache\registry.npmjs.org\webpack\.cache.json
25 verbose correctMkdir C:\Users\Administrator\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
26 silly install normalizeTree
27 silly loadCurrentTree Finishing
28 silly loadIdealTree Starting
29 silly install loadIdealTree
30 silly cloneCurrentTree Starting
31 silly install cloneCurrentTreeToIdealTree
32 silly cloneCurrentTree Finishing
33 silly loadShrinkwrap Starting
34 silly install loadShrinkwrap
35 silly loadShrinkwrap Finishing
36 silly loadAllDepsIntoIdealTree Starting
37 silly install loadAllDepsIntoIdealTree
38 silly rollbackFailedOptional Starting
39 silly rollbackFailedOptional Finishing
40 silly runTopLevelLifecycles Starting
41 silly runTopLevelLifecycles Finishing
42 silly install printInstalled
43 verbose stack Error: Refusing to install webpack as a dependency of itself
43 verbose stack     at checkSelf (C:\Program Files (x86)\nodejs\node_modules\npm\lib\install\validate-args.js:53:14)
43 verbose stack     at Array.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
43 verbose stack     at LOOP (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
43 verbose stack     at chain (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
43 verbose stack     at C:\Program Files (x86)\nodejs\node_modules\npm\lib\install\validate-args.js:16:5
43 verbose stack     at C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
43 verbose stack     at Array.forEach (native)
43 verbose stack     at C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
43 verbose stack     at Array.forEach (native)
43 verbose stack     at asyncMap (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
44 verbose cwd D:\phpStudy\WWW\VueJS\webpack
45 error Windows_NT 6.1.7601
46 error argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "webpack" "-D"
47 error node v5.9.1
48 error npm  v3.7.3
49 error code ENOSELF
50 error Refusing to install webpack as a dependency of itself
51 error If you need help, you may report this error at:
51 error     <https://github.com/npm/npm/issues>
52 verbose exit [ 1, true ]

Please help me !

**Comment by KenanY** [comment]
@web-tiny Make sure the `'name"` property in your `package.json` is not the same as any of your dependencies. In this case, try changing it to something more unique than `"webpack"`.

**Comment by web-tiny** [comment]
@KenanY  Yeah,than you ! resolved it .
