### ISSUE TITLE
npm ERR! node v6.10.0 npm ERR! npm  v3.10.10 npm ERR! code MODULE_NOT_FOUND  npm ERR! Cannot find module 'github-url-from-username-repo'

### ISSUE THREAD

**Issue by douglw1** [npm/npm#16005]
I'm opening this issue because:

  - [ ] npm is doing something I don't understand.

I updating my node/npm to the latest and now nothing works with npm. I keep getting this error:

npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'github-url-from-username-repo'

i uninstalled and reinstalled and am still getting this...

any ideas?

Thanks in advance

**Comment by legodude17** [comment]
If you are on windows, try deleting the node and npm folders and then reinstalling.
