### ISSUE TITLE
NPM for ASP.NET Core Web App

### ISSUE THREAD

**Issue by NinjaSk8ter** [npm/npm#16001]
[http://stackoverflow.com/questions/42725695/npm-is-not-adding-packages-to-lib-directory-vs-2015](url)
Here is a link to my issue.

I'm using NPM Package Manager with Visual Studio 2015 .NET Core Web Application:
I’m trying to add a specific jQuery package with NPM Package Manager.

I installed jQuery 1.11.3 with NPM: `npm install jquery@1.11.3 –S`
This jQuery package was added to package.json 
And It was also created under node_modules

However, the jQuery file was not added to lib Directory within Visual Studio. Packages previously added by Bower like jQuery existed within the lib Directory.

Could someone point me in the right direction about:
how to move the files out of that node_modules directory, and into the wwwroot/lib

**Comment by legodude17** [comment]
You are going to have to do that manually, or write a script to do it.
