### ISSUE TITLE
ubuntu

### ISSUE THREAD

**Issue by lwpersonal** [npm/npm#16009]
#### input  npm run dev

=>

root@lw:/media/lw/00051BF500065C77/study/web/Vue2/vue_elm# npm run dev

> vue_elm@1.0.0 dev /media/lw/00051BF500065C77/study/web/Vue2/vue_elm
> node build/dev-server.js

internal/child_process.js:313
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at exports._errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at Object.exports.spawn (child_process.js:380:9)
    at module.exports (/media/lw/00051BF500065C77/study/web/Vue2/vue_elm/node_modules/opn/index.js:75:24)
    at Server.<anonymous> (/media/lw/00051BF500065C77/study/web/Vue2/vue_elm/build/dev-server.js:79:5)
    at Server.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at Server.emit (events.js:185:7)
    at emitListeningNT (net.js:1285:10)
    at _combinedTickCallback (internal/process/next_tick.js:71:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Linux 3.19.0-80-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! vue_elm@1.0.0 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vue_elm@1.0.0 dev script 'node build/dev-server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vue_elm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/dev-server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vue_elm
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vue_elm
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /media/lw/00051BF500065C77/study/web/Vue2/vue_elm/npm-debug.log
root@lw:/media/lw/00051BF500065C77/study/web/Vue2/vue_elm# npm run node build/dev-server.js
npm ERR! Linux 3.19.0-80-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "node" "build/dev-server.js"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10

npm ERR! missing script: node
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /media/lw/00051BF500065C77/study/web/Vue2/vue_elm/npm-debug.log

**Comment by KenanY** [comment]
@lwpersonal Looks like `node build/dev-server.js` is throwing an error. Closing since this is not the fault of `npm` as far as I can tell.

**Comment by lwpersonal** [comment]
@KenanY   Seems to be the reason for the thread, how to solve the problem... thank you

**Comment by lwpersonal** [comment]
npm-debug.log ：

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'dev' ]
2 info using npm@3.10.10
3 info using node@v6.10.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle vue_elm@1.0.0~predev: vue_elm@1.0.0
6 silly lifecycle vue_elm@1.0.0~predev: no script for predev, continuing
7 info lifecycle vue_elm@1.0.0~dev: vue_elm@1.0.0
8 verbose lifecycle vue_elm@1.0.0~dev: unsafe-perm in lifecycle true
9 verbose lifecycle vue_elm@1.0.0~dev: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/media/lw/00051BF500065C77/study/web/Vue2/vue_elm/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
10 verbose lifecycle vue_elm@1.0.0~dev: CWD: /media/lw/00051BF500065C77/study/web/Vue2/vue_elm
11 silly lifecycle vue_elm@1.0.0~dev: Args: [ '-c', 'node build/dev-server.js' ]
12 silly lifecycle vue_elm@1.0.0~dev: Returned: code: 1  signal: null
13 info lifecycle vue_elm@1.0.0~dev: Failed to exec dev script
14 verbose stack Error: vue_elm@1.0.0 dev: `node build/dev-server.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid vue_elm@1.0.0
16 verbose cwd /media/lw/00051BF500065C77/study/web/Vue2/vue_elm
17 error Linux 3.19.0-80-generic
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
19 error node v6.10.0
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error vue_elm@1.0.0 dev: `node build/dev-server.js`
22 error Exit status 1
23 error Failed at the vue_elm@1.0.0 dev script 'node build/dev-server.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the vue_elm package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node build/dev-server.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs vue_elm
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls vue_elm
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
