### ISSUE TITLE
Installing “preview-plus@1.2.7” failed

### ISSUE THREAD

**Issue by arima0k** [npm/npm#16003]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Error insaling preview-plus@1.2.7
#### How can the CLI team reproduce the problem?

npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated react-tools@0.12.2: react-tools is deprecated. For more information, visit https://fb.me/react-tools-deprecated
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Users\\angelo\\AppData\\Local\\atom\\app-1.15.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\angelo\\AppData\\Local\\atom\\app-1.15.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\angelo\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\angelo\\.atom\\.apmrc" "install" "C:\\Users\\angelo\\AppData\\Local\\Temp\\d-117210-3576-1afoa7t\\package.tgz" "--runtime=electron" "--target=1.3.13" "--arch=x64" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code EREADFILE

npm ERR! Error extracting C:\Users\angelo\.atom\.apm\typescript-compiler\1.3.0\package.tgz archive: ENOENT: no such file or directory, open 'C:\Users\angelo\.atom\.apm\typescript-compiler\1.3.0\package.tgz'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\angelo\AppData\Local\Temp\apm-install-dir-117210-3576-1omvngt\npm-debug.log

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by noAlvaro** [comment]
Have you managed to workaround this?

**Comment by legodude17** [comment]
Have you tried updating `npm`?

**Comment by corneadoug** [comment]
Could be related to this: https://github.com/npm/npm/issues/13547#issuecomment-287913659
the latest version of typescript-compiler is `1.4.1-2`

**Comment by arima0k** [comment]
solved
