### ISSUE TITLE
Trouble connecting when trying to install angular on CentOS 6.8

### ISSUE THREAD

**Issue by rraskin** [npm/npm#16002]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
# npm install -g @angular/cli@latest
npm http GET https://registry.npmjs.org/angular/cli
npm http 404 https://registry.npmjs.org/angular/cli
npm ERR! TypeError: Object.keys called on non-object
npm ERR!     at Function.keys (native)
npm ERR!     at installTargetsError (/usr/lib/node_modules/npm/lib/cache.js:708:24)
npm ERR!     at /usr/lib/node_modules/npm/lib/cache.js:638:10
npm ERR!     at saved (/usr/lib/node_modules/npm-registry-client/lib/get.js:148:7)
npm ERR!     at /usr/lib/node_modules/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:108:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-504.23.4.el6.x86_64
npm ERR! command "node" "/usr/bin/npm" "install" "-g" "@angular/cli@latest"
npm ERR! cwd /root
npm ERR! node -v v0.10.46
npm ERR! npm -v 1.3.6
npm ERR! type called_on_non_object
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /root/npm-debug.log
npm ERR! not ok code 0

#### How can the CLI team reproduce the problem?

I can reproduce at will. Just run the command shown above.

https://gist.github.com/rraskin/49018163d7920f1139068e8b5e700c42

### supporting information:

 - `npm -v` prints: 1.3.6
 - `node -v` prints: v0.10.46
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux
 - Network issues:
   - Geographic location where npm was run: not sure. machine is "...gce-stack.internal"
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@rraskin Sorry, `npm@1.3` is years old and is no longer supported. I can reopen this though if this is still an issue with the latest stable release.
