### ISSUE TITLE
Cannot find module 'internal/fs'

### ISSUE THREAD

**Issue by JackeyXiao** [npm/npm#16004]
#### I'm opening this issue because:
Cannot find module 'internal/fs'

when i install uirecorder，the process failed，commond is 『npm i uirecorder -g』，failure information：
```
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "uirecorder" "-g"
npm ERR! node v7.6.0
npm ERR! npm  v4.1.2
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'internal/fs'
```

[npm-debug.log.zip](https://github.com/npm/npm/files/835401/npm-debug.log.zip)

**Comment by Salfai77210** [comment]
@JackeyXiao You can try [this](https://github.com/npm/npm/issues/14579#issuecomment-261362295)
