### ISSUE TITLE
Need a review of this log file

### ISSUE THREAD

**Issue by jonathan80** [npm/npm#16015]
I was following the instructions  at https://angular.io/docs/ts/latest/guide/setup.html#!#download, and, started installing npm, the attached log file was generated.  This will help me become an excellent developer, perhaps :)

Are there any serious technical implications?

#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by watilde** [comment]
Could you give us the log file again? I couldn't find it.

**Comment by jonathan80** [comment]
Attached log file.

J. Camilleri
T: +356 27448812

________________________________

**Comment by KenanY** [comment]
@jonathan80 Can you upload the log file to <https://gist.github.com/> and post the link here?

**Comment by jonathan80** [comment]
Why don't you do so yourself?


________________________________

**Comment by jonathan80** [comment]
This is the hyperlink https://gist.github.com/jonathan80/7f5db91b1247f49e606c6cba6c12feb9.

[https://avatars3.githubusercontent.com/u/7943038?v=3&s=400]<https://gist.github.com/jonathan80/7f5db91b1247f49e606c6cba6c12feb9>

Error log<https://gist.github.com/jonathan80/7f5db91b1247f49e606c6cba6c12feb9>
gist.github.com
Error log



Excuse me I have to go now, I did not create this platform.


J. Camilleri

Skype: camilleri.jon


________________________________

**Comment by KenanY** [comment]
@jonathan80 I didn't do it myself because I didn't have the log. Attaching it to a GitHub reply email does not have it show up on GitHub.

Anyways, it appears like you are using `npm@1.3`, which is several years old and is no longer supported. If this is still an issue with the latest stable release, then I will happily reopen this.
