### ISSUE TITLE
Unable to install node-red in node_modules folder

### ISSUE THREAD

**Issue by KartavyaBhatt** [npm/npm#16018]
System : Dell
OS : Win 10

Downloaded the zip of node red from github.
After running following commands 
npm install --production
npm install -g
npm install

no folder named 'node-red' is created inside node_modules folder.

At last running the command 
npm insall --save node-red

this error occurs.

![problem](https://cloud.githubusercontent.com/assets/18227784/23840861/b48f8388-07ce-11e7-9cad-ed066a454393.PNG)

**Comment by KenanY** [comment]
@KartavyaBhatt `node-red` is not a dependency of itself, hence why it doesn't appear in its own `node_modules/` directory. I think what you're trying to do is run `node-red` from source? Have you tried following <https://github.com/node-red/node-red#developers>?

**Comment by KartavyaBhatt** [comment]
I have downloaded zip of latest release from the link :
https://github.com/node-red/node-red/releases/latest then run the following
commands after opening the unzipped folder in command prompt,

npm install --production

And then tried to open http://localhost:1880/ on my browser. Nothing opened
:(


Next I downloaded a zip from https://github.com/node-red/node-red#developers
and then run following commands,

npm install -g node-red
node-red


But it shows error of "unrecognized command"

**Comment by KenanY** [comment]
@KartavyaBhatt Try:

```
npm install
npm run build
npm start
```

**Comment by KartavyaBhatt** [comment]
Big Thanks.!!!!!!!!!
[image: Inline image 1]

Now can I delete those zip files which I downloaded from GitHub ?

**Comment by KartavyaBhatt** [comment]
It is opening inside my unzipped folder but not globally. Is it possible to
add a command "node-red" to windows which directly starts node-red ?

**Comment by KenanY** [comment]
@KartavyaBhatt No problem. All I did was copy-paste commands from the link I posted earlier. If you would like to install `node-red` globally:

```
npm install -g node-red
node-red
```

Make sure whatever directory you've set as [`prefix`](https://docs.npmjs.com/misc/config#prefix) is in your environment `PATH`.

**Comment by KartavyaBhatt** [comment]
First I did this

[image: Inline image 1]

Then this

 [image: Inline image 2]

What to do ?
