### ISSUE TITLE
you do not have permission to publish "math_example"

### ISSUE THREAD

**Issue by dmyers82** [npm/npm#16026]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [X ] Other (_see below for feature requests_):

#### What's going wrong?
When I type in npm publish, I receive the following:
C:\node_samples\math_example>npm publish
npm ERR! publish Failed PUT 403
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "publish"
npm ERR! node v7.7.2
npm ERR! npm  v4.1.2
npm ERR! code E403

npm ERR! you do not have permission to publish "math_example". Are you logged in
 as the correct user? : math_example
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\node_samples\math_example\npm-debug.log

[npm-debug.log.zip](https://github.com/npm/npm/files/839522/npm-debug.log.zip)

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@dmyers82 Someone is already using the `math_example` package name. Try changing the `"name"` field in your `package.json` to something more unique.

**Comment by droymac** [comment]
@KenanY 's solution worked for me. I'm currently reading through Brad Dayley's "Node.js , MongoDB, and AngularJS Web Development" and was getting 

```
npm ERR! publish Failed PUT 403
npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "publish"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! code E403

npm ERR! you do not have permission to publish "censorify". Are you logged in as the correct user? : censorify
```
at `npm publish`. Thanks @KenanY ! Perhaps npm should improve their error message in this case...

**Comment by jenriquejr** [comment]
@KenanY I am getting the same error with a package that don't seem to exists already.
Is there any other possible reasons for getting this error ?

```sh
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code E403
```

![screen shot 2017-05-23](https://cloud.githubusercontent.com/assets/2904943/26353009/362f8330-3f8c-11e7-9686-a9d8bf76f96b.png)

**Comment by KenanY** [comment]
@jenriquejr Hmm, not sure. Need more information.

**Comment by jenriquejr** [comment]
@KenanY 
I was able to see that the package previously and was unpublished by looking at the response on the registry endpoint for that package `https://registry.npmjs.org/<package-name>` - I guess that is the desired behaviour ? not sure .. please confirm

**Comment by KenanY** [comment]
@jenriquejr You'll probably have to email `support@npmjs.com` to request the package be transferred to you.
