### ISSUE TITLE
npm Error in windows

### ISSUE THREAD

**Issue by aaqilcs102** [npm/npm#16025]
Hello, I'm new in node and facing a problem with npm, when I try and check the version of node I get the version that's been installed (I've installed latest version) but when I try to check the version of npm, I'm getting the following error:

Error: Cannot find module 'C:\Users\Muhammad Aaqil\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

This is the case when I'm checking in cmd (as administrator too), but when I check it using gitbash I'm getting the version.

I tried to install yargs but getting the problem with npm, again using cmd I'm getting a different error then using gitbash.

The problem in cmd that I'm facing is :

C:\WINDOWS\system32>npm -v
module.js:471
    throw err;
    ^

Error: Cannot find module 'C:\Users\Muhammad Aaqil\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

That's seems I'll not be able to install other modules too! I'll be thankful someone helps me!!!

**Comment by legodude17** [comment]
Try deleting `C:\Users\Muhammad Aaqil\AppData\Roaming\npm` and reinstalling `npm` and `node`.

**Comment by aaqilcs102** [comment]
@legodude17  Thanks :) It helped. It's working fine.

**Comment by legodude17** [comment]
@aaqilcs102 that's good to hear.

@KenanY Can you close this?
