### ISSUE TITLE
下载ReactNative项目，npm install之后，报npm错

### ISSUE THREAD

**Issue by RichyLeo** [npm/npm#16020]
#### 下载ReactNative项目，npm install 之后，error：

> npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/Cellar/node/7.6.0/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.6.0
npm ERR! npm  v4.1.2

> npm ERR! shasum check failed for /var/folders/ql/28rcx7y94lz1mn9d2d3_6rfc0000gn/T/npm-96889-3b4419fd/registry.npmjs.org/react-native-spinkit/-/react-native-spinkit-1.0.2.tgz
npm ERR! Expected: 0d31b019556e038aa8e953038562550cb0ead8d2
npm ERR! Actual:   25dba0053f7627040a96ef0164f6008d8fff24d9
npm ERR! From:     https://registry.npmjs.org/react-native-spinkit/-/react-native-spinkit-1.0.2.tgz

**Comment by watilde** [comment]
Hello! I think you caught a wrong cache:
> npm ERR! shasum check failed for /var/folders/ql/28rcx7y94lz1mn9d2d3_6rfc0000gn/T/npm-96889-3b4419fd/registry.npmjs.org/react-native-spinkit/-/react-native-spinkit-1.0.2.tgz

Can you try `npm cache clean` and install it again?

**Comment by bigbigdan** [comment]
npm run build - builds the iframe embed.
