### ISSUE TITLE
error while installing angular-cli

### ISSUE THREAD

**Issue by reddworf** [npm/npm#16023]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x ] Other (_see below for feature requests_):

#### What's going wrong?
I am getting errors when trying to install angular-cli

I installed Node.js and typed in the following command "npm install -g angular-cli"

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

![npm_install_angular_cli_2017-03-13](https://cloud.githubusercontent.com/assets/26388090/23865651/b9ad942c-07ec-11e7-911b-2b9a509ae4c9.jpg)

**Comment by KenanY** [comment]
@reddworf Could you upload the full `npm-debug.log` file to <https://gist.github.com/> and post the link here?

**Comment by reddworf** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'angular-cli' ]
2 info using npm@4.1.2
3 info using node@v7.7.2
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData angular-cli
8 silly fetchNamedPackageData angular-cli
9 silly mapToRegistry name angular-cli
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'angular-cli',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'angular-cli',
12 silly mapToRegistry   name: 'angular-cli',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/angular-cli
14 verbose request uri https://registry.npmjs.org/angular-cli
15 verbose request no auth needed
16 info attempt registry request try #1 at 12:51:59 PM
17 verbose request id fa7112cecd41851b
18 http request GET https://registry.npmjs.org/angular-cli
19 info retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.56.162:443
20 info attempt registry request try #2 at 12:52:30 PM
21 http request GET https://registry.npmjs.org/angular-cli
22 info retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.56.162:443
23 info attempt registry request try #3 at 12:53:51 PM
24 http request GET https://registry.npmjs.org/angular-cli
25 silly fetchPackageMetaData Error: connect ETIMEDOUT 151.101.44.162:443
25 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1033:11)
25 silly fetchPackageMetaData     at exports._exceptionWithHostPort (util.js:1056:20)
25 silly fetchPackageMetaData     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1105:14)
25 silly fetchPackageMetaData  error for angular-cli { Error: connect ETIMEDOUT 151.101.44.162:443
25 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1033:11)
25 silly fetchPackageMetaData     at exports._exceptionWithHostPort (util.js:1056:20)
25 silly fetchPackageMetaData     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1105:14)
25 silly fetchPackageMetaData   code: 'ETIMEDOUT',
25 silly fetchPackageMetaData   errno: 'ETIMEDOUT',
25 silly fetchPackageMetaData   syscall: 'connect',
25 silly fetchPackageMetaData   address: '151.101.44.162',
25 silly fetchPackageMetaData   port: 443 }
26 silly rollbackFailedOptional Starting
27 verbose stack TypeError: Cannot read property 'path' of null
27 verbose stack     at Installer.rollbackFailedOptional (C:\Program Files\nodejs\node_modules\npm\lib\install.js:511:29)
27 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
27 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
27 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:18:7
27 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install.js:337:5
27 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
27 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
27 verbose stack     at chain (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
27 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install.js:294:5
27 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:16:22
28 verbose cwd C:\windows\system32
29 error Windows_NT 6.1.7601
30 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "angular-cli"
31 error node v7.7.2
32 error npm  v4.1.2
33 error Cannot read property 'path' of null
34 error If you need help, you may report this error at:
34 error     <https://github.com/npm/npm/issues>
35 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@reddworf Looks like the network requests to the npm registry are timing out, which points to your internet connection as the likely culprit. Maybe you are behind a proxy or firewall?

**Comment by reddworf** [comment]
how can I resolve this?

**Comment by eslammahgoub** [comment]
same here

**Comment by eslammahgoub** [comment]
It solved

**Comment by aswani85** [comment]
How it is resolved?
