### ISSUE TITLE
unable to verify the first certificate

### ISSUE THREAD

**Issue by radtymm** [npm/npm#16029]
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "ssl-root-cas" "--save"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code UNABLE_TO_VERIFY_LEAF_SIGNATURE

npm ERR! unable to verify the first certificate
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Administrator\npm-debug.log

**Comment by radtymm** [comment]
how to deal with it
?

**Comment by legodude17** [comment]
Try updating to the latest version of `npm`.
