### ISSUE TITLE
doing npm install for each project takes too much space in drive

### ISSUE THREAD

**Issue by malikasinger1** [npm/npm#16028]
doing npm install for each project takes too much space in drive

is there any way to route npm install to a specific part of hard drive and when i do npm install it make node_module folder in that part of drive, and when i run any project it look for dependencies in that part of drive,
just like single pool for every project.

Thank you,
Inzamam Malik

**Comment by legodude17** [comment]
@malikasinger1 that would be more `node` resolution algorithm then `npm`, I believe.

**Comment by malikasinger1** [comment]
dear @legodude17, sorry i didn't get your point

**Comment by legodude17** [comment]
All `npm` does is install packages into `node_modules`. The `node` `require` resolution algorithm dictates how your program will find the modules you `require`. Hope that clears things up.

**Comment by malikasinger1** [comment]
Here is my case, have a look of [this](https://github.com/malikasinger1/Learn-React) repo

there are more then 10 folders and each of them is a project in its own, every folder have a packege.json file
if i clone [this](https://github.com/malikasinger1/Learn-React) repo in a new computer such library pc or home pc,

even that all projects are related to `React` have almost similar dependencies in packege.json but i must have to run `npm install` in every folder in order to see that project in action, which takes time to be done and take space in drive,

second option is `npm install` in one folder and then copy `node_modules` folder in all other folders/projects but it also take time and space both,

some time `node_modules` folder become too big and it takes too space

would that there is a `pool` like thing and when i run `npm install` it doesnot create dependencies folder in my project but in `pool`, and runing `npm install` once is enough for all projects with same dependencies, when a project come with different dependency run `npm install` again and it fills with missing dependency

my proposal may be a *new feature* of npm/node, if you add this feature or something similar to this it will save too much space in drive and also save too much time

hope you read my problem carefully and think about it,
Thank You,
M.Inzamam Malik

**Comment by legodude17** [comment]
One option is to put some of the common dependencies in the root folder instead of the sub folders. `require` will search up the file tree.

**Comment by mInzamamMalik** [comment]
@legodude17 python have same thing which i'm looking for, it install dependencies in environment instead of project folder, is there something similar in node?

**Comment by DanielJaramillo94** [comment]
I am having the same question as you, since I'm working with several Angular projects.
Have you find something?
