### ISSUE TITLE
Yum install latest version by default

### ISSUE THREAD

**Issue by bertalanimre** [npm/npm#16033]
I have a standard question:
How can I install the latest npm version on a CentOS 7 machine?

This issue came when I wanted to install the LTS version of NodeJS (6.10), but after that I couldn't install NPM because it requires 6.9 and can't install.

Where is your repository or if you don't have, when will you update the version in epel release?

Thank you in advance!

Bert

**Comment by KenanY** [comment]
You could probably try the [fancy Unix install](https://github.com/npm/npm#fancy-install-unix). Also, `npm` **does** support Node.js v6.10.
