### ISSUE TITLE
npm downloads code without any integrity checks

### ISSUE THREAD

**Issue by dotchev** [npm/npm#16032]
It seems npm features this weakness
[CWE-494: Download of Code Without Integrity Check](http://cwe.mitre.org/data/definitions/494.html)

npm packages downloaded from the internet are not verified for integrity in any way.
This seems like a major security risk.

This has been discussed in several other issues and it is acknowledged as a deficiency but there seem to be no plans to address it.

At least npm should inform its users of this risk and make it clear that users should handle it on their own.

**Comment by legodude17** [comment]
@dotchev AFAIK `npm` runs a shasum check on all the packages it downloads.

**Comment by dotchev** [comment]
Where does is take the shasums to compare against?
Notice that even in npm-shrinkwrap.json there are no shasums.

**Comment by legodude17** [comment]
The shasums are in the registry. Take a look at any registry page, and it will have the shasums for the tarballs.

**Comment by dotchev** [comment]
So npm downloads both the tarballs and the shasums from the internet. How can you be sure these are not fakes?
As stated in https://github.com/npm/npm/issues/6886#issuecomment-252357656 shasums in npm are not meant to protect against substitution attacks.

**Comment by legodude17** [comment]
@dotchev That's why I said AFAIK. 😄 Then I guess there is no good verification. Do you have any suggestions? 😄

**Comment by dotchev** [comment]
Short term solution: add a strong crypto hash like sha256 in npm-shrinkwrap.json.
Long term: introduce package signatures and some sort of PKI
