### ISSUE TITLE
gulp suddenly stopped working

### ISSUE THREAD

**Issue by Greeksalad30** [npm/npm#16038]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'rebuild',
1 verbose cli   'node-sass' ]
2 info using npm@4.1.2
3 info using node@v7.6.0
4 info readInstalled object
5 verbose rebuild path, id [ '/Users/yiannis/sites/portfolio/node_modules/node-sass',
5 verbose rebuild   'node-sass@3.12.0' ]
6 silly rebuild set [ '/Users/yiannis/sites/portfolio/node_modules/node-sass' ]
7 verbose stack Error: Cannot find module 'internal/fs'
7 verbose stack     at Function.Module._resolveFilename (module.js:470:15)
7 verbose stack     at Function.Module._load (module.js:418:25)
7 verbose stack     at Module.require (module.js:498:17)
7 verbose stack     at require (internal/module.js:20:19)
7 verbose stack     at evalmachine.<anonymous>:18:20
7 verbose stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/cmd-shim/node_modules/graceful-fs/fs.js:11:1)
7 verbose stack     at Module._compile (module.js:571:32)
7 verbose stack     at Object.Module._extensions..js (module.js:580:10)
7 verbose stack     at Module.load (module.js:488:32)
7 verbose stack     at tryModuleLoad (module.js:447:12)
8 verbose cwd /Users/yiannis/sites/portfolio
9 error Darwin 15.6.0
10 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "rebuild" "node-sass"
11 error node v7.6.0
12 error npm  v4.1.2
13 error code MODULE_NOT_FOUND
14 error Cannot find module 'internal/fs'
15 error If you need help, you may report this error at:
15 error     <https://github.com/npm/npm/issues>
16 verbose exit [ 1, true ]

**Comment by legodude17** [comment]
Try updating `npm`.
