### ISSUE TITLE
npm start issue

### ISSUE THREAD

**Issue by krcurry** [npm/npm#16034]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

PS C:\Users\Karen\OneDrive\Timestamp> npm start npm 
ERR! Windows_NT 10.0.10240 npm 
ERR! argv " C:\\Program Files\\nodejs\\node.exe" "C: Program 
Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.j "start"
npm ERR! node v7.7.2
npm ERR! npm  v4.1.2
npm ERR! path C:\Users\Karen\OneDrive\Timestamp\package on
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open npm 
ERR! enoent ENOENT: no such file or directory, open
:\Users\Karen\OneDrive\Timestamp\package.json' npm
 ERR! enoent ENOENT: no such file or directory, open
sers\Karen\OneDrive\Timestamp\package.json' npm 
ERR! enoent This is most likely not a problem with self npm 
ERR! enoent and is related to npm not being able to find a file.npm  
ERR! Enoent npm ERR! Please include the following file with any support request: npm 
ERR!     C:\Users\Karen\OneDrive\Timestamp\npm-debug.log

**Comment by krcurry** [comment]
I'm still getting the same error

**Comment by krcurry** [comment]
I'm still getting this error 
 PS C:\Users\Karen\OneDrive\Microservice> npm start
npm ERR! path C:\Users\Karen\OneDrive\Microservice\package
.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\Karen\OneDrive\Microservice\package.json'
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\Karen\OneDrive\Microservice\package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Karen\AppData\Roaming\npm-cache\_logs\2017-03-15T21_34_21_930Z-debug.log
PS C:\Users\Karen\OneDrive\Microservice>

**Comment by legodude17** [comment]
Did you run `npm init` in `C:\Users\Karen\OneDrive\Microservice`?

**Comment by krcurry** [comment]
yes of course I did

**Comment by chakrihacker** [comment]
Is there start script in your package. json :question:

**Comment by krcurry** [comment]
package.json
{
  "name": "mytimeservice",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "start": "node ./bin/www"
  },
  "dependencies": {
    "body-parser": "~1.16.0",
    "cookie-parser": "~1.4.3",
    "debug": "~2.6.0",
    "express": "~4.14.1",
    "jade": "~1.11.0",
    "morgan": "~1.7.0",
    "serve-favicon": "~2.3.2"
  }
}

app.js
var express = require('express');
var path = require('path');
var favicon = require('serve-favicon');
var logger = require('morgan');
var cookieParser = require('cookie-parser');
var bodyParser = require('body-parser');

var index = require('./routes/index');
var users = require('./routes/users');

var app = express();

// view engine setup
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'jade');

// uncomment after placing your favicon in /public
//app.use(favicon(path.join(__dirname, 'public', 'favicon.ico')));
app.use(logger('dev'));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));
app.use(cookieParser());
app.use(express.static(path.join(__dirname, 'public')));

app.use('/', index);
app.use('/users', users);

// catch 404 and forward to error handler
app.use(function(req, res, next) {
  var err = new Error('Not Found');
  err.status = 404;
  next(err);
});

// error handler
app.use(function(err, req, res, next) {
  // set locals, only providing error in development
  res.locals.message = err.message;
  res.locals.error = req.app.get('env') === 'development' ? err : {};

  // render the error page
  res.status(err.status || 500);
  res.render('error');
});

module.exports = app;

bin
 www
#!/usr/bin/env node

/**
 * Module dependencies.
 */

var app = require('../app');
var debug = require('debug')('mytimeservice:server');
var http = require('http');

/**
 * Get port from environment and store in Express.
 */

var port = normalizePort(process.env.PORT || '3000');
app.set('port', port);

/**
 * Create HTTP server.
 */

var server = http.createServer(app);

/**
 * Listen on provided port, on all network interfaces.
 */

server.listen(port);
server.on('error', onError);
server.on('listening', onListening);

/**
 * Normalize a port into a number, string, or false.
 */

function normalizePort(val) {
  var port = parseInt(val, 10);

  if (isNaN(port)) {
    // named pipe
    return val;
  }

  if (port >= 0) {
    // port number
    return port;
  }

  return false;
}

/**
 * Event listener for HTTP server "error" event.
 */

function onError(error) {
  if (error.syscall !== 'listen') {
    throw error;
  }

  var bind = typeof port === 'string'
    ? 'Pipe ' + port
    : 'Port ' + port;

  // handle specific listen errors with friendly messages
  switch (error.code) {
    case 'EACCES':
      console.error(bind + ' requires elevated privileges');
      process.exit(1);
      break;
    case 'EADDRINUSE':
      console.error(bind + ' is already in use');
      process.exit(1);
      break;
    default:
      throw error;
  }
}

/**
 * Event listener for HTTP server "listening" event.
 */

function onListening() {
  var addr = server.address();
  var bind = typeof addr === 'string'
    ? 'pipe ' + addr
    : 'port ' + addr.port;
  debug('Listening on ' + bind);
}
I have node modules loaded


W
npm ERR!     C:\Users\Karen\AppData\Roaming\npm-cache\_logs\2017-03-16T18_17_06_15
PS C:\Users\Karen\OneDrive\Microservice\mytimeservice> npm start
npm ERR! path C:\Users\Karen\OneDrive\Microservice\mytimeservice\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\Karen\OneDrive\Microservice\mytimeservice\package.json'
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\Karen\OneDrive\Microservice\mytimeservice\package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

**Comment by legodude17** [comment]
You are switching cwd in all of these errors. Where is your package.json?

**Comment by krcurry** [comment]
Uploaded all files except  node_modules to github  krcurry/myTimeService

**Comment by chakrihacker** [comment]
in your start script `node ./bin/www` you point node to **bin/www** dir but there is no dir bin and file www inside it so change to `node ./www`

**Comment by krcurry** [comment]
IT WORKED! Thank you!

**Comment by KenanY** [comment]
Closing as resolved.
