### ISSUE TITLE
please help me I can't install npm plugin

### ISSUE THREAD

**Issue by kakera87** [npm/npm#16044]
I am sorry. 
I am not good at speaking English and use this website.
I want to use npm plugin in eclipse but I can't install node_modules.
I tryed reinstall and update to nodejs.(nodejs.org)
please help me. thank you

1. I created to nodejs project in my workspace(*nodejs_renshou)
2. package.json -> run as -> npm install(*output this error : npm WARN 123@0.1.0 No repository field.) and npm update.
3. package.json -> run configurations -> goal : start

and 

1. 
<eclipse Console>
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10

npm ERR! missing script: start
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\pk\workspaceWeb\nodejs_renshou\npm-debug.log

2. 
<npm-debug.log>

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10

npm ERR! missing script: start
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\pk\workspaceWeb\nodejs_renshou\npm-debug.log

**Comment by KenanY** [comment]
@kakera87 Make sure you have defined a `"start"` script in your `package.json` file. Check out <https://docs.npmjs.com/misc/scripts>.

**Comment by kakera87** [comment]
@KenanY  thank you so much. I solve the problem. I made wrong worksapce name.
