### ISSUE TITLE
Getting npm err registry error parsing json and 404 error, while try to install the angular2 in my asp.net project.

### ISSUE THREAD

**Issue by ssenth1985** [npm/npm#16042]
#### I'm opening this issue because:

  npm is doing something I don't understand.
 
#### What's going wrong?

Getting npm err registry error parsing json and 404 error, while try to install the angular2 in my asp.net project.

[npm-debug.txt](https://github.com/npm/npm/files/842869/npm-debug.txt)

[package.json.txt](https://github.com/npm/npm/files/842901/package.json.txt)

### supporting information:

 - `npm -v` prints: v6.9.5
 - `node -v` prints:  v3.10.10
 - `npm config get registry` prints: http://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows
 - Network issues:
   - Geographic location where npm was run: USA
   I use a proxy to connect to the npm registry.
  
 - Container:
   I develop using Visual Studio 2015 Update 3 on Windows.

**Comment by mesche** [comment]
I had the same problem. After cleaning the cache my problem was solved.
`sudo npm cache clean -f`

**Comment by legodude17** [comment]
This is most likely a problem with your proxy or VPN, if you have one. What does http://registry.npmjs.org/reflect-metadata look like in your browser?

**Comment by ssenth1985** [comment]
Hi legodude17,

My browser downloaded a json file

Here is the file  [reflect-metadata.json.txt](https://github.com/npm/npm/files/848103/reflect-metadata.json.txt)

**Comment by legodude17** [comment]
What about http://registry.npmjs.org/@angular/compiler?

**Comment by ssenth1985** [comment]
I am getting 'The webpage cannot be found'

**Comment by legodude17** [comment]
What about http://registry.npmjs.org/@angular%2fcompiler?

**Comment by ssenth1985** [comment]
Able to download the @angular_compiler.json file

**Comment by legodude17** [comment]
That is so odd. Are you able to try without the proxy?

**Comment by ssenth1985** [comment]
Yes I tired without proxy. At that time I get different error as connection refused.

**Comment by ssenth1985** [comment]
looks like no one have any clue on this issue :(
