### ISSUE TITLE
specify (and use) a standard, machine+human readable format for changelogs

### ISSUE THREAD

**Issue by graingert** [npm/npm#16046]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's the feature?
specify (and use) a standard, machine+human readable format for changelogs

#### What problem is the feature intended to solve?
packages are uploaded with a changelog in various different places

#### Is the absence of this feature blocking you or your team? If so, how?
No blocking, it's just frustrating

#### Is this feature similar to an existing feature in another tool?
hackage has a standard location for changelogs:

https://hackage.haskell.org/package/{package}-{version}/changelog

#### Is this a feature you're prepared to implement, with support from the npm CLI team?
sure.

**Comment by KenanY** [comment]
ref. https://github.com/npm/npm/issues/9740
