### ISSUE TITLE
help - publish two different versions of NPM project as two different packages on NPM

### ISSUE THREAD

**Issue by ORESoftware** [npm/npm#16054]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?

nothing at the moment :)

#### What kind of help do you need?

I am looking for the canonical way to publish two different versions of an NPM project. I have a library called "suman". I want to publish to different versions of this, one will go to 

https://www.npmjs.com/package/suman

the other is 

https://www.npmjs.com/package/suman.ts

as you might have guessed - suman.ts has the TypeScript declaration files in the codebase. Plain old suman without the .ts does not have the files. I don't want to include the extra .d.ts files if users want to save diskspace etc.

So my question is, how can I take the same project, and publish it to two different "NPM remotes"/as two different NPM packages? I am not sure how to do that. Is there a recommended way? I think I read somewhere that isaacs was ok with publishing the same project to a couple different NPM names as long as it wasn't egregious or over-indulgent.

Thanks

**Comment by legodude17** [comment]
I would suggest writing a script that changes the name and then runs `npm publish` again.

**Comment by ORESoftware** [comment]
Yeah, but I would have to change package.json right? Is there anywhere else where I would have to change the NPM name besides package.json that you could think of?

**Comment by legodude17** [comment]
Not off the top of my head.
