### ISSUE TITLE
npm version throws maxBuffer exceeded error

### ISSUE THREAD

**Issue by ospatil** [npm/npm#16052]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
`npm version` command throws **maxBuffer exceeded** error while executing. 

I have a a fairly big `package.json` file and I suspect that causes this. I didn't have this problem when it was smaller. I have a fair number of build related scripts in `package.json`. These scripts carry out a complex build process with webpack and gulp that produces fairly standard output but that's not too much.

Just a side note, when I use `yarn version` instead of `npm version`, it works flawlessly and completes successfully for the same big `package.json` file.

#### How can the CLI team reproduce the problem?

I suppose by creating a big `package.json` file and having some scripts that produce output.

Here is my  `npm-debug.log` file - https://gist.github.com/ospatil/a7347eaf7e19cd1ffcec1ad885a214a7

### supporting information:

 - `npm -v` prints: **4.1.2**
 - `node -v` prints: **v7.7.3**
 - `npm config get registry` prints: https://repo.devcloud.sungard.com/artifactory/api/npm/npm-cto. We have a private corporate NPM registry and I can assure it works smoothly.
 - Windows, OS X/macOS, or Linux?: **OS X/macOS**
 - Network issues:
   - Geographic location where npm was run: **Montreal, Canada**
   - [x] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
Can you put your `package.json` in a gist too?

**Comment by ospatil** [comment]
Added.

**Comment by asgerjensen** [comment]
I have the same issue, after upgrading to angular/cli 1.0.0-rc2

Tried npm 4.4.x with no luck.

Found, that if i ran npm version before npm install in my build script, the process succeeded.
