### ISSUE TITLE
I'm having issues installing Cordova

### ISSUE THREAD

**Issue by legralimia** [npm/npm#16058]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Errors at the end of the installation
#### How can the CLI team reproduce the problem?
Here is the log
https://gist.github.com/legralimia/cc02998ae02b4ddfd7d79e5a5d32d633
### supporting information:

 - `npm -v` prints:
3.10.10
 - `node -v` prints:
v6.10.0
 - `npm config get registry` prints:
http://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?:
Windows
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
Try updating `npm` to the latest version.
