### ISSUE TITLE
Unable to find the HTTPS remote helper, is it the host?

### ISSUE THREAD

**Issue by RastaDjuss** [npm/npm#16069]
npm install can't find the https remote helper and miissing depositories or something.

[punkmmur@world abovethefold]$ npm install
(node:577575) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
npm ERR! git clone --template=/home/punkmmur/.npm/_git-remotes/_templates --mirror https://github.com/pocketjoso/css.git /home/punkmmur/.npm/_git-remotes/git-https-github-com-pocketjoso-css-git-c81bb2f2: Cloning into bare repository '/home/punkmmur/.npm/_git-remotes/git-https-github-com-pocketjoso-css-git-c81bb2f2'...
npm ERR! git clone --template=/home/punkmmur/.npm/_git-remotes/_templates --mirror https://github.com/pocketjoso/css.git /home/punkmmur/.npm/_git-remotes/git-https-github-com-pocketjoso-css-git-c81bb2f2: 
npm ERR! git clone --template=/home/punkmmur/.npm/_git-remotes/_templates --mirror https://github.com/pocketjoso/css.git /home/punkmmur/.npm/_git-remotes/git-https-github-com-pocketjoso-css-git-c81bb2f2: fatal: Unable to find remote helper for 'https'
npm ERR! Linux 3.10.0-427.18.2.lve1.4.27.el7.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code 128

npm ERR! Command failed: git clone --template=/home/punkmmur/.npm/_git-remotes/_templates --mirror https://github.com/pocketjoso/css.git /home/punkmmur/.npm/_git-remotes/git-https-github-com-pocketjoso-css-git-c81bb2f2
npm ERR! fatal: Unable to find remote helper for 'https'
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/punkmmur/TatouageCalypso.com/wp-content/themes/mikmag-child/abovethefold/npm-debug.log
[punkmmur@world abovethefold]$

**Comment by RastaDjuss** [comment]
[npm-debug.log.zip](https://github.com/npm/npm/files/849310/npm-debug.log.zip)

**Comment by legodude17** [comment]
Could you upload the full npm-debug.log to https://gist.github.com/ and post the link here?
