### ISSUE TITLE
Installing using -g does not produce a .bin folder in usr/lib/node_modules

### ISSUE THREAD

**Issue by IdanAdar** [npm/npm#16064]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
In a fresh instance of CentOS we have:

1. Installed node.js
2. Ran the following command:

   ```
   npm install -g adaro cfenv colors cookie-parser d3 express i18next i18next-browser-languagedetector i18next-express-middleware i18next-node-fs-backend i18next-xhr-backend locale log4js nconf string-format react react-dom react-i18next react-router request  assets-webpack-plugin babel-core babel-eslint babel-jest babel-loader babel-plugin-istanbul babel-plugin-transform-es2015-block-scoping babel-preset-es2015 babel-preset-react babel-preset-stage-1 babel-preset-stage-2 babel-register browser-sync chai chai-as-promised css-loader cucumber debug del enzyme eslint eslint-config-airbnb eslint-config-airbnb-base eslint-plugin-import eslint-plugin-jsx-a11y eslint-plugin-react gulp gulp-autoprefixer gulp-concat gulp-csslint gulp-eslint gulp-expect-file gulp-htmlhint gulp-istanbul gulp-live-server gulp-nodemon gulp-protractor gulp-rename gulp-sass gulp-sass-lint gulp-sourcemaps gulp-spawn-mocha gulp-util isparta istanbul-instrumenter-loader jest json-loader minimist mocha mocha-junit-reporter mustache nock node-mocks-http path phantomjs-prebuilt protractor-cucumber-framework proxyquire react-addons-test-utils require-dir rewire sass-loader selenium-standalone selenium-webdriver sinon sinon-chai style-loader supertest supertest-as-promised webpack 
   ```

    The packages are available at /usr/lib/node_modules

3. Then, via a Jenkinsfile that first checks out a repository, we run the following:

   ```
   mocha --recursive --require babel-register --reporter dot --reporter mocha-junit-reporter --reporter-options mochaFile=./testResults/results.xml`
   ```

   The workspace where the repo is at is /var/jenkins/workspaces/random-name.

The error is that mocha could not be found in the .bin folder. Indeed, in /usr/lib/node_modules there is no hidden .bin folder.

We do not understand why the .bin folder is not being created when running `npm install` or how we should probably call the package.

Because this is all happening in the context of a Jenkins job, meaning for each run a new folder is created in the workspace folder, and because there many packages being used, we cannot / it is ill desired to install all the packages for each run.

We thought that by installing the packages globally it should be possible to execute what is needed without running `npm install` again.

#### How can the CLI team reproduce the problem?

Possibly by having a fresh instance of CentOS with node.js and running a subset of the command mentioned above (some of those packages may not be accessible).

### supporting information:

 - `npm -v` prints: 3.10.10
 - `node -v` prints: 6.10.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
The executables for your globally installed packages will be in `<prefix>/bin`, not `<prefix>/.bin`. Your prefix is `/usr/lib/node_modules`.

**Comment by IdanAdar** [comment]
@legodude17, after installing all packages, there is no "bin" folder in /usr/lib/node_modules.

**Comment by IdanAdar** [comment]
Attached is the log from the installation.
