### ISSUE TITLE
My program does not work!

### ISSUE THREAD

**Issue by Yahalomo** [npm/npm#16061]
Hi guys, I am trying to launch my program but it does not work.
It says : 0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.9.3
3 info using node@v6.2.1
4 verbose stack Error: missing script: start
4 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:150:19)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:60:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:356:5
4 verbose stack     at checkBinReferences_ (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:320:45)
4 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:354:3)
4 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:124:5)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:243:12
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
4 verbose stack     at tryToString (fs.js:449:3)
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:436:12)
5 verbose cwd C:\Users\omer\WebstormProjects\Preloader
6 error Windows_NT 6.1.7601
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
8 error node v6.2.1
9 error npm  v3.9.3
10 error missing script: start
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

I will be glad for some help!

**Comment by legodude17** [comment]
Hello! The error log said you're missing the `start` script. To use `npm start`, you need to put it into the script field in your package.json like:

{
  "script": {
    "start": "echo hi"
  }
}
See this example for your reference: https://docs.npmjs.com/misc/scripts#examples

Thanks
