### ISSUE TITLE
Improvement: support 'show' introspection into local package.json

### ISSUE THREAD

**Issue by pcraddick** [npm/npm#16065]
#### What's the feature?
Support 'info/show' functionality against local package.json. I may be missing something, but have not found a way to do this in any comprehensive way via npm.
#### What problem is the feature intended to solve?
Ease of use, developer convenience, etc. As package.json is the locus for npm's management facilities, it seems entirely natural and appropriate that the tool would enable examination of one's project's package.json on the local file system
#### Is the absence of this feature blocking you or your team? If so, how?
'Blocking', no. However it is sub-optimal either to have to open package.json in an editor, or cat it in the terminal, if you want to inspect something in the file -- when quite clearly this is something npm could support.
BTW, we have a poor man's implementation of this as an npm script:
```
"scripts": {
    "show": "echo 'const package = require(\"./package.json\"); const field = process.argv[2]; console.log(`${JSON.stringify(package[field] || package, null, 2)}`);' | node ''",
```
which supports
```
npm run --s show contributors ## only show the value for the 'contributors' field
npm run --s show ## print the entire package.json's contents
```
... the goal being to to be isomorphic with npm show/info:
```
npm show koa contributors
```
Also, for us, this is a nice to have:
```
"scripts": {
"show.keys": "echo 'const package = require(\"./package.json\"); console.log(`${JSON.stringify(Object.keys(package), null, 2)}`);' | node ''",
```
which shows all of the top-level fields of the package object
etc
#### Is this feature similar to an existing feature in another tool?
Our hack aside, not that I am not aware of.
#### Is this a feature you're prepared to implement, with support from the npm CLI team?
Yes

**Comment by ebaker** [comment]
+1
