### ISSUE TITLE
I receive the following error while using the command npm install 

### ISSUE THREAD

**Issue by PriyaKT** [npm/npm#16074]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by PriyaKT** [comment]
[npm-debug.zip](https://github.com/npm/npm/files/849854/npm-debug.zip)

**Comment by PriyaKT** [comment]
I have used the below commands 1. npm config set strict-ssl false
2. npm config set registry "http://registry.npms.org/"
and also set the proxy since i am behind a corporate proxy.  Attached the npm-debug file for your reference.

**Comment by legodude17** [comment]
Could you upload the full npm-debug.log to https://gist.github.com/ and post the link here?

**Comment by PriyaKT** [comment]
Please find the link https://gist.github.com/PriyaKT/b18cb6c97a91e8878f735d0a56b8ad4e.
Had attached the file here as well npm-debug.zip
