### ISSUE TITLE
Error on executing node-xlsx

### ISSUE THREAD

**Issue by seemanthmadhu** [npm/npm#16079]
#### I'm opening this issue because:
I am getting an error while executing node-xlsx. I wanted to read excel file from command prompt.

Please find below the output in command prompt on execution:
-----------------------------------------------
C:\IOT>npm install excel node-xlsx
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "excel" "node-xlsx"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! syscall getaddrinfo

npm ERR! getaddrinfo EAI_AGAIN registry.npmjs.org:443
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\IOT\npm-debug.log
-----------------------------------------------

Below is the content of the log file. Please advise.
-----------------------------------------------
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'excel',
1 verbose cli   'node-xlsx' ]
2 info using npm@3.10.10
3 info using node@v6.10.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData excel
8 silly fetchPackageMetaData node-xlsx
9 silly fetchNamedPackageData excel
10 silly mapToRegistry name excel
11 silly mapToRegistry using default registry
12 silly mapToRegistry registry https://registry.npmjs.org/
13 silly mapToRegistry data Result {
13 silly mapToRegistry   raw: 'excel',
13 silly mapToRegistry   scope: null,
13 silly mapToRegistry   escapedName: 'excel',
13 silly mapToRegistry   name: 'excel',
13 silly mapToRegistry   rawSpec: '',
13 silly mapToRegistry   spec: 'latest',
13 silly mapToRegistry   type: 'tag' }
14 silly mapToRegistry uri https://registry.npmjs.org/excel
15 silly fetchNamedPackageData node-xlsx
16 silly mapToRegistry name node-xlsx
17 silly mapToRegistry using default registry
18 silly mapToRegistry registry https://registry.npmjs.org/
19 silly mapToRegistry data Result {
19 silly mapToRegistry   raw: 'node-xlsx',
19 silly mapToRegistry   scope: null,
19 silly mapToRegistry   escapedName: 'node-xlsx',
19 silly mapToRegistry   name: 'node-xlsx',
19 silly mapToRegistry   rawSpec: '',
19 silly mapToRegistry   spec: 'latest',
19 silly mapToRegistry   type: 'tag' }
20 silly mapToRegistry uri https://registry.npmjs.org/node-xlsx
21 verbose request uri https://registry.npmjs.org/excel
22 verbose request no auth needed
23 info attempt registry request try #1 at 4:45:09 PM
24 verbose request id 6c1f438571a95247
25 http request GET https://registry.npmjs.org/excel
26 verbose request uri https://registry.npmjs.org/node-xlsx
27 verbose request no auth needed
28 info attempt registry request try #1 at 4:45:09 PM
29 http request GET https://registry.npmjs.org/node-xlsx
30 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
31 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
32 info attempt registry request try #2 at 4:45:19 PM
33 http request GET https://registry.npmjs.org/excel
34 info attempt registry request try #2 at 4:45:19 PM
35 http request GET https://registry.npmjs.org/node-xlsx
36 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
37 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
38 info attempt registry request try #3 at 4:46:19 PM
39 http request GET https://registry.npmjs.org/excel
40 info attempt registry request try #3 at 4:46:19 PM
41 http request GET https://registry.npmjs.org/node-xlsx
42 silly fetchPackageMetaData Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
42 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1022:11)
42 silly fetchPackageMetaData     at errnoException (dns.js:33:15)
42 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
42 silly fetchPackageMetaData  error for excel { Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
42 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1022:11)
42 silly fetchPackageMetaData     at errnoException (dns.js:33:15)
42 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
42 silly fetchPackageMetaData   code: 'EAI_AGAIN',
42 silly fetchPackageMetaData   errno: 'EAI_AGAIN',
42 silly fetchPackageMetaData   syscall: 'getaddrinfo',
42 silly fetchPackageMetaData   hostname: 'registry.npmjs.org',
42 silly fetchPackageMetaData   host: 'registry.npmjs.org',
42 silly fetchPackageMetaData   port: 443 }
43 silly fetchPackageMetaData Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
43 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1022:11)
43 silly fetchPackageMetaData     at errnoException (dns.js:33:15)
43 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
43 silly fetchPackageMetaData  error for node-xlsx { Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
43 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1022:11)
43 silly fetchPackageMetaData     at errnoException (dns.js:33:15)
43 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
43 silly fetchPackageMetaData   code: 'EAI_AGAIN',
43 silly fetchPackageMetaData   errno: 'EAI_AGAIN',
43 silly fetchPackageMetaData   syscall: 'getaddrinfo',
43 silly fetchPackageMetaData   hostname: 'registry.npmjs.org',
43 silly fetchPackageMetaData   host: 'registry.npmjs.org',
43 silly fetchPackageMetaData   port: 443 }
44 silly rollbackFailedOptional Starting
45 silly rollbackFailedOptional Finishing
46 silly runTopLevelLifecycles Finishing
47 silly install printInstalled
48 verbose stack Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
48 verbose stack     at Object.exports._errnoException (util.js:1022:11)
48 verbose stack     at errnoException (dns.js:33:15)
48 verbose stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
49 verbose cwd C:\IOT
50 error Windows_NT 6.2.9200
51 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "excel" "node-xlsx"
52 error node v6.10.0
53 error npm  v3.10.10
54 error code EAI_AGAIN
55 error errno EAI_AGAIN
56 error syscall getaddrinfo
57 error getaddrinfo EAI_AGAIN registry.npmjs.org:443
58 error If you need help, you may report this error at:
58 error     <https://github.com/npm/npm/issues>
59 verbose exit [ 1, true ]

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by chakrihacker** [comment]
It looks like network issue, if you are behind proxy try to use direct connection or keep retrying
