### ISSUE TITLE
破 FIS3安装失败

### ISSUE THREAD

**Issue by flybirdsoft** [npm/npm#16073]
破 FIS3安装失败，

D:\wanda\JavaProject\bim_static\webApp>npm install -g fis-parser-babel
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "fis-parser-babel"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8

npm ERR! Cannot convert undefined or null to object
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\wanda\JavaProject\bim_static\webApp\npm-debug.log

**Comment by KenanY** [comment]
Looks like the `fis-parser-babel` has been unpublished, hence it is not possible to install it. I do wish the error message was more clear on this though :)
