### ISSUE TITLE
Please include the following file(npm-debug.log) with any support request:

### ISSUE THREAD

**Issue by sammpathkummar** [npm/npm#16076]
I'm opening this issue because:

C : myproject>npm install -g nativescript

>npm install -g nativescript
Throwing below error when running above command.
Please include the following file(npm-debug.log) with any support request.
Installed npm version 4.1.2
Installed Node vesrion 7.5.0 version

Please help me

**Comment by KenanY** [comment]
@sammpathkummar Could you upload the resulting `npm-debug.log` file to <https://gist.github.com/> and post the link here?

**Comment by sammpathkummar** [comment]
Hi KenanY thank for the response,unpload the log file (https://gist.github.com/ ) please help me

**Comment by KenanY** [comment]
@sammpathkummar Please post a direct link to your gist here.

**Comment by sammpathkummar** [comment]
HI sorry, this was the link (https://gist.github.com/sammpathkummar/e36c8b7268d8d818857abaa84ea0fad6)

**Comment by KenanY** [comment]
@sammpathkummar What is the output of `npm config get proxy`?

**Comment by sammpathkummar** [comment]
null  coming

**Comment by sammpathkummar** [comment]
i am getting error as below 

NODE is not in required version! Required is 4.0.0 and you're using v0.10.31
npm ERR! angular2-sdk@0.0.0 postinstall: `tsd reinstall --clean && tsd link && tsd rebundle && gulp check.versions && gulp postinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular2-sdk@0.0.0 postinstall script.
npm ERR! This is most likely a problem with the angular2-sdk package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsd reinstall --clean && tsd link && tsd rebundle && gulp check.versions && gulp postinstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular2-sdk
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\IDE\\Extensions\\Microsoft\\Web Tools\\External\\\\node\\node" "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\IDE\\Extensions\\Microsoft\\Web Tools\\External\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd E:\27-03-2017\Solution2\Sampleaj2
npm ERR! node -v v0.10.31
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE
npm

====npm command completed with exit code 1====

can you help me

**Comment by KenanY** [comment]
@sammpathkummar Note:

```
NODE is not in required version! Required is 4.0.0 and you're using v0.10.31
```

Could you try updating to Node.js v4 and `npm` v4?

**Comment by amitkprajapati** [comment]
@KenanY I am still getting the error after including the file npm-debug.log

->Please include the following file with any support request : npm-debug.log

**Comment by kenany** [comment]
@amitkprajapati Could you upload the log file to <https://gist.github.com/> and link it here? Thanks!

**Comment by vndsapkal** [comment]
Same problem with me how to fix it.

npm ERR! Linux 4.2.0-42-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "create-react-app"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.3
npm ERR! path /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!     at Error (native)
npm ERR!  { Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!     at Error (native)
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/fz1/npm-debug.log
