### ISSUE TITLE
 vue init webpack#1.0 my-project :    tunneling socket could not be established, cause=write EPROTO 140671983023936:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:

### ISSUE THREAD

**Issue by qzttt** [npm/npm#16075]
#### I'm opening this issue because:

  - [ ] npm is producing an incorrect install.

#### What's going wrong?
Failed to download repo vuejs-templates/webpack#1.0: tunneling socket could not be established, cause=write EPROTO 140671983023936:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:

npmrc

http-proxy=http://192.xx.xx.xx:8080/
https-proxy=https://192.xx.xx.xx:8080/
registry=http://registry.npm.taobao.org/
strict-ssl=false

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
What command did you run?

**Comment by ChampIsMe** [comment]
Did someone find a solution to this?

**Comment by legodude17** [comment]
@ChampIsMe Check your internet connection.

**Comment by qinzitong** [comment]
I use it behind the proxy , I have got some solutions about the proxy setting but seems no effective.
