### ISSUE TITLE
outdated: exitcode still 1 with --silent flag

### ISSUE THREAD

**Issue by fearphage** [npm/npm#16083]
`npm outdated` changed to exiting with exit code 1 when things are outdated. According to #14013, the `--silent` flag should get the classic functionality of always exiting with exit code 0 (whether up to date or not). I am not able to confirm that however. I don't see any tests for that case either.

Node version: 7.7.1
NPM vesion: 4.1.2

```
➜  unity git:(starting-point) ✗ node --version
v7.7.1
➜  unity git:(starting-point) ✗ npm --version
4.1.2
➜  unity git:(starting-point) ✗ npm outdated > /dev/null; echo $?
1
➜  unity git:(starting-point) ✗ npm outdated --silent > /dev/null; echo $?
1
➜  unity git:(starting-point) ✗ npm --silent outdated > /dev/null; echo $?       
1
➜  unity git:(starting-point) ✗ npm --silent outdated --silent > /dev/null; echo $?
1
```

**Comment by rtaft** [comment]
Also seeing this behavior in 4.1.1.  An exit code of 1 indicates an error.  Given that 'outdated' is an expected option and returns correctly, I don't understand why 0 is not the default return value.

**Comment by vsubbotskyy** [comment]
npm@4.4.4
node@v7.8.0
same issue

**Comment by wwalser** [comment]
The implementation of ```npm outdated```, a function called ```outdated```, has a parameter called ```silent```. This probably lead the implementor to think that this functionality was already taken care of and tested. Unfortunately the ```silent``` parameter isn't a CLI parameter, it's only used by the ```npm update```.

See it's original implementation here: https://github.com/npm/npm/commit/82894b62b6389aa10029bf5592ae8e41124a55ce

One piece of trouble for landing a PR for this is that the function parameter and CLI parameter, though both called ```silent``` have differing functionality. CLI ```--silent``` is meant to allow for normal execution of ```npm outdated```, including all of this other parameters. The function parameter on the other hand mutes all output.

I believe I'll try to land a PR for this but the above causes me to question the original proposed implementation, especially the name of the flag used.

**Comment by rtaft** [comment]
That's one way to address an issue, ignore it and have the bot close it automatically.
