### ISSUE TITLE
Can't see the latest version of my published package.

### ISSUE THREAD

**Issue by ceymard** [npm/npm#16081]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [X] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I published two new versions of my packages (domic and domic-i18n)

When trying to install or when doing a npm view domic, it shows the latest version as 1.0.0-beta8.
I published 1.0.0-beta10, which is appearing on https://npmjs.com.

Why can't I access the latest version ? It's already been at least one hour.

#### How can the CLI team reproduce the problem?

`npm install domic`
see that it's beta8 and not beta10

Or

`npm install domic@1.0.0-beta10` and get an error

### supporting information:

 - `npm -v` prints: 4.4.4
 - `node -v` prints: v6.6.0
 - `npm config get registry` prints: https://registry.npmjs.org
 - Windows, OS X/macOS, or Linux?: Linux
 - Network issues:
   - none
 - Container:
   - None

**Comment by KenanY** [comment]
So, that command did throw an error at first for me, but then I did:

``` bash
npm install domic@'1.0.0-beta10'
```

And it worked (not sure why yet). Now I can't reproduce the problem with any of the commands, even after cleaning the local cache `¯\_(ツ)_/¯`

**Comment by ceymard** [comment]
It works for me now too, guess the cache was just slower than usual...

**Comment by KenanY** [comment]
Incident report for the record: https://npmjs.statuspage.io/incidents/slbthqs5x899

**Comment by ceymard** [comment]
Ah, that explains it.
