### ISSUE TITLE
NPM is including files when .gitignore has exceptions

### ISSUE THREAD

**Issue by mitar** [npm/npm#16089]
#### I'm opening this issue because:

NPM is including files despite them being ignored with `.gitignore`, when `.gitignore` file has exceptions, like `!**/packages/build/`.

#### How can the CLI team reproduce the problem?

I have created a [reproduction](https://github.com/mitar/npm-test-ignore). Run:

```
$ npm pack
test-npm-1.0.0.tgz
$ tar tf test-npm-1.0.0.tgz 
package/package.json
package/.npmignore
package/.idea/foobar
package/test-npm-1.0.0.tgz
```

`.idea` directory should not be present there.

### supporting information:

 - `npm -v` prints: `3.10.10`
 - `node -v` prints: `v6.10.0`
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 - Mac OS X

**Comment by legodude17** [comment]
What does you `.gitignore` look like?

**Comment by mitar** [comment]
You can see it in [reproduction](https://github.com/mitar/npm-test-ignore/blob/master/.gitignore).

**Comment by legodude17** [comment]
There is no `.idea` in the reproduction.

**Comment by mitar** [comment]
Ah, but this even has a reproduction. :-(

**Comment by mitar** [comment]
I opened a followup: https://github.com/npm/npm/issues/17280
