### ISSUE TITLE
npm install -s error 

### ISSUE THREAD

**Issue by huanfang** [npm/npm#16086]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [Y] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I delete dependencies in package.json. and then try npm install and npm install -s  to update node_module, but the removed dependency folders still in node_module.  I think the npm install should updating dependencies depends on what package.json dependencies.
#### How can the CLI team reproduce the problem?
npm install -save react-sortable-tree
delete the react-sortable-tree dependency at package.json
npm install -save
the react-sortable-tree folder still exists in node_module folder.
Which is not correct.

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?: Mac El Captain
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
`npm install` does not delete anything AFAIK. Try running `npm prune`.
