### ISSUE TITLE
<npm install  > error 

### ISSUE THREAD

**Issue by djjandyhl** [npm/npm#16084]
#### I'm opening this issue because:

- [ ] npm is crashing.
- [ ] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
- [x] npm is producing an incorrect install.

#### What's going wrong?
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'redis' ]
2 info using npm@3.10.10
3 info using node@v6.10.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData redis
8 silly fetchNamedPackageData redis
9 silly mapToRegistry name redis
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npm.taobao.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'redis',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'redis',
12 silly mapToRegistry   name: 'redis',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npm.taobao.org/redis
14 verbose request uri https://registry.npm.taobao.org/redis
15 verbose request no auth needed
16 info attempt registry request try #1 at 00:06:13
17 verbose request id c109a0c43e7cf6de
18 http request GET https://registry.npm.taobao.org/redis
19 info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=getaddrinfo EAI_AGAIN 1080:80
20 info attempt registry request try #2 at 00:06:30
21 http request GET https://registry.npm.taobao.org/redis
22 info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=getaddrinfo EAI_AGAIN 1080:80
23 info attempt registry request try #3 at 00:07:39
24 http request GET https://registry.npm.taobao.org/redis
25 silly fetchPackageMetaData Error: tunneling socket could not be established, cause=getaddrinfo EAI_AGAIN 1080:80
25 silly fetchPackageMetaData     at ClientRequest.onError (C:\Program Files\nodejs\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:176:17)
25 silly fetchPackageMetaData     at ClientRequest.g (events.js:291:16)
25 silly fetchPackageMetaData     at emitOne (events.js:96:13)
25 silly fetchPackageMetaData     at ClientRequest.emit (events.js:188:7)
25 silly fetchPackageMetaData     at Socket.socketErrorListener (_http_client.js:310:9)
25 silly fetchPackageMetaData     at emitOne (events.js:96:13)
25 silly fetchPackageMetaData     at Socket.emit (events.js:188:7)
25 silly fetchPackageMetaData     at connectErrorNT (net.js:1022:8)
25 silly fetchPackageMetaData     at _combinedTickCallback (internal/process/next_tick.js:74:11)
25 silly fetchPackageMetaData     at process._tickCallback (internal/process/next_tick.js:98:9)
25 silly fetchPackageMetaData  error for redis { Error: tunneling socket could not be established, cause=getaddrinfo EAI_AGAIN 1080:80
25 silly fetchPackageMetaData     at ClientRequest.onError (C:\Program Files\nodejs\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:176:17)
25 silly fetchPackageMetaData     at ClientRequest.g (events.js:291:16)
25 silly fetchPackageMetaData     at emitOne (events.js:96:13)
25 silly fetchPackageMetaData     at ClientRequest.emit (events.js:188:7)
25 silly fetchPackageMetaData     at Socket.socketErrorListener (_http_client.js:310:9)
25 silly fetchPackageMetaData     at emitOne (events.js:96:13)
25 silly fetchPackageMetaData     at Socket.emit (events.js:188:7)
25 silly fetchPackageMetaData     at connectErrorNT (net.js:1022:8)
25 silly fetchPackageMetaData     at _combinedTickCallback (internal/process/next_tick.js:74:11)
25 silly fetchPackageMetaData     at process._tickCallback (internal/process/next_tick.js:98:9) code: 'ECONNRESET' }
26 silly rollbackFailedOptional Starting
27 silly rollbackFailedOptional Finishing
28 silly runTopLevelLifecycles Finishing
29 silly install printInstalled
30 verbose stack Error: tunneling socket could not be established, cause=getaddrinfo EAI_AGAIN 1080:80
30 verbose stack     at ClientRequest.onError (C:\Program Files\nodejs\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:176:17)
30 verbose stack     at ClientRequest.g (events.js:291:16)
30 verbose stack     at emitOne (events.js:96:13)
30 verbose stack     at ClientRequest.emit (events.js:188:7)
30 verbose stack     at Socket.socketErrorListener (_http_client.js:310:9)
30 verbose stack     at emitOne (events.js:96:13)
30 verbose stack     at Socket.emit (events.js:188:7)
30 verbose stack     at connectErrorNT (net.js:1022:8)
30 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:74:11)
30 verbose stack     at process._tickCallback (internal/process/next_tick.js:98:9)
31 verbose cwd D:\work\code\nodeMQ
32 error Windows_NT 10.0.14393
33 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "redis"
34 error node v6.10.0
35 error npm  v3.10.10
36 error code ECONNRESET
37 error network tunneling socket could not be established, cause=getaddrinfo EAI_AGAIN 1080:80
38 error network This is most likely not a problem with npm itself
38 error network and is related to network connectivity.
38 error network In most cases you are behind a proxy or have bad network settings.
38 error network
38 error network If you are behind a proxy, please make sure that the
38 error network 'proxy' config is set properly.  See: 'npm help config'
39 verbose exit [ 1, true ]

### supporting information:

 - `npm -v` prints:3.10.10
 - `node -v` prints:6.10.0
 - `npm config get registry` prints: registry=https://registry.npm.taobao.org
 - Windows, OS X/macOS, or Linux?:Windows10 64-bit
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [x] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
Do you have a stable internet connection?

**Comment by djjandyhl** [comment]
I'm at home,my internet connection is very good....

**Comment by legodude17** [comment]
Have you tried again?

**Comment by djjandyhl** [comment]
This problem  only happens on my notebook(windows10),I can't install any module, but  my PC (windows7) is right.Both of them are in the same network environment .

**Comment by yyf1230** [comment]
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "vue"
npm ERR! node v6.8.1
npm ERR! npm  v3.10.8
npm ERR! code EIO
npm ERR! errno -4070
npm ERR! syscall read

npm ERR! EIO: i/o error, read
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\hp-飞\Desktop\新建文件夹 (2)\npm-debug.log
