### ISSUE TITLE
npm ERR! self signed certificate

### ISSUE THREAD

**Issue by seanishok01** [npm/npm#16087]
#### I'm opening this issue because:
npm install throws error.

"C:\Program Files\nodejs\npm.CMD" install
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code DEPTH_ZERO_SELF_SIGNED_CERT
npm ERR! self signed certificate
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

[npm-debug.txt](https://github.com/npm/npm/files/851642/npm-debug.txt)

version:
 npm - v is 3.10.10
node -v is 6.10.0
Note:
I am not using any proxy.

**Comment by legodude17** [comment]
Have you taken a look at http://blog.npmjs.org/post/78165272245/more-help-with-selfsignedcertinchain-and-npm? See if the steps outlined there work for you.

**Comment by seanishok01** [comment]
I have tried the link already. When i execute npm install -g i am facing same issue. Even during upgrade of npm i am facing same issue. Not sure whats the issue is. I am looking for an good solution.

**Comment by legodude17** [comment]
Try reinstalling from the `nodejs` website.

**Comment by seanishok01** [comment]
Thanks @legodude17  its working now
