### ISSUE TITLE
npm ERR! Darwin 15.6.0 when I try to run csslint via script

### ISSUE THREAD

**Issue by ruchiratrivedi** [npm/npm#16085]
Getting the following error when trying to run csslint via scripts

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/7.7.3/bin/node" "/usr/local/bin/npm" "run" "lint"
npm ERR! node v7.7.3
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! sapient-ihg-connect-nearbypage@1.0.0 lint: `csslint candlewood/global/css`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sapient-ihg-connect-nearbypage@1.0.0 lint script 'csslint candlewood/global/css'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sapient-ihg-connect-nearbypage package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     csslint candlewood/global/css
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sapient-ihg-connect-nearbypage
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sapient-ihg-connect-nearbypage
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/rtriv2/ihg-ui/static/ihg/sapient-ihg-connect-nearbypage/npm-debug.log

Following is my package.json file:
{
  "name": "sapient-ihg-connect-nearbypage",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
     "lint": "csslint candlewood/global/css"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "csslint": "^1.0.4",
    "jshint": "^2.9.4",
    "pre-commit": "^1.2.2"
  },  
  "pre-commit": [
    "precommit-msg",
    "lint"
  ]
}

**Comment by ruchiratrivedi** [comment]
I changed the version of node js to 5.11.0, but still getting the same.

**Comment by legodude17** [comment]
Does `csslint` give any output?

**Comment by KenanY** [comment]
The log indicates that `csslint candlewood/global/css` is failing on your system. All `npm` is doing here is catching the error and letting you know. I would try running `csslint candlewood/global/css` or `./node_modules/.bin/csslint candlewood/global/css` yourself and observing the output.
