### ISSUE TITLE
npm ERR! git clone ... errno=Connection refused

### ISSUE THREAD

**Issue by masuch** [npm/npm#16090]
#### I'm opening this issue because:
  - [ ] npm is crashing.
  - [x ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
npm ERR! git clone --template=/home/u1/.electron-gyp/.npm/_git-remotes/_templates --mirror git://github.com/jrieken/v8-profiler.git /home/u1/.electron-gyp/.npm/_git-remotes/git-github-com-jrieken-v8-profiler-git-bc0803a4d4b2150b8a1bbffa80270769007036c2-277eeebf: Cloning into bare repository '/home/u1/.electron-gyp/.npm/_git-remotes/git-github-com-jrieken-v8-profiler-git-bc0803a4d4b2150b8a1bbffa80270769007036c2-277eeebf'...
npm ERR! git clone --template=/home/u1/.electron-gyp/.npm/_git-remotes/_templates --mirror git://github.com/jrieken/v8-profiler.git /home/u1/.electron-gyp/.npm/_git-remotes/git-github-com-jrieken-v8-profiler-git-bc0803a4d4b2150b8a1bbffa80270769007036c2-277eeebf: fatal: unable to connect to github.com:
npm ERR! git clone --template=/home/u1/.electron-gyp/.npm/_git-remotes/_templates --mirror git://github.com/jrieken/v8-profiler.git /home/u1/.electron-gyp/.npm/_git-remotes/git-github-com-jrieken-v8-profiler-git-bc0803a4d4b2150b8a1bbffa80270769007036c2-277eeebf: github.com[0: 192.30.253.112]: errno=Connection refused
npm ERR! git clone --template=/home/u1/.electron-gyp/.npm/_git-remotes/_templates --mirror git://github.com/jrieken/v8-profiler.git /home/u1/.electron-gyp/.npm/_git-remotes/git-github-com-jrieken-v8-profiler-git-bc0803a4d4b2150b8a1bbffa80270769007036c2-277eeebf: github.com[1: 192.30.253.113]: errno=Connection refused
npm ERR! Linux 4.8.0-42-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v7.7.3
npm ERR! npm  v4.1.2
npm ERR! code 128

npm ERR! Command failed: git clone --template=/home/u1/.electron-gyp/.npm/_git-remotes/_templates --mirror git://github.com/jrieken/v8-profiler.git /home/u1/.electron-gyp/.npm/_git-remotes/git-github-com-jrieken-v8-profiler-git-bc0803a4d4b2150b8a1bbffa80270769007036c2-277eeebf
npm ERR! Cloning into bare repository '/home/u1/.electron-gyp/.npm/_git-remotes/git-github-com-jrieken-v8-profiler-git-bc0803a4d4b2150b8a1bbffa80270769007036c2-277eeebf'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.253.112]: errno=Connection refused
npm ERR! github.com[1: 192.30.253.113]: errno=Connection refused
npm ERR! 
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /media/raid018/___dev/vscode.GIT/npm-debug.log

#### How can the CLI team reproduce the problem?
./scripts/npm.sh install

### supporting information:

 - `npm -v` prints: 4.1.2
 - `node -v` prints: v7.7.3
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux Ubuntu 16.10
 - Network issues:
   - Geographic location where npm was run: Prague
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container: vscode
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
The log indicates that this is likely an issue with your internet connection, not with `npm` itself. Perhaps you are behind a proxy or firewall? Seems like connections involving the git protocol are being refused.
