### ISSUE TITLE
  i am getting an error while installing botpress by running command npm install -g botpress

### ISSUE THREAD

**Issue by sanampreet** [npm/npm#16099]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@sanampreet Please upload the resulting `npm-debug.log` file to <https://gist.github.com/> and post the link here.

**Comment by sanampreet** [comment]
https://gist.github.com/sanampreet/33835d5231ca4ae607f26961fb888319.js

**Comment by KenanY** [comment]
I see:

```
gyp ERR! stack Error: Can't find Python executable "C:\Python27\", you can set the PYTHON env variable.
```

Please see [the Windows dependencies of `node-gyp`](https://github.com/nodejs/node-gyp#installation). This error message is coming from `node-gyp`, not `npm`, and is caused by not having Python installed (but you need it installed if you're gonna build any packages with `node-gyp`).
