### ISSUE TITLE
I don't know why this installing is error...(install harp js)

### ISSUE THREAD

**Issue by KimMinYoeng** [npm/npm#16097]
Your environment has been set up for using Node.js 7.7.3 (x64) and npm.

C:\Users\Kim Min Young>npm install -g harp
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\KIMMIN~1\AppData\Local\Temp\npm-9868-df3e9abc\registry.npmjs.org\bytes\-\bytes-2.4.0.tgz.2248497961' -> 'C:\Users\KIMMIN~1\AppData\Local\Temp\npm-9868-df3e9abc\registry.npmjs.org\bytes\-\bytes-2.4.0.tgz'
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "harp"
npm ERR! node v7.7.3
npm ERR! npm  v4.1.2

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\KIMMIN~1\AppData\Local\Temp\npm-9868-df3e9abc\registry.npmjs.org\iconv-lite\-\iconv-lite-0.4.13.tgz.107200548' -> 'C:\Users\KIMMIN~1\AppData\Local\Temp\npm-9868-df3e9abc\registry.npmjs.org\iconv-lite\-\iconv-lite-0.4.13.tgz'
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "harp"
npm ERR! node v7.7.3
npm ERR! npm  v4.1.2

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\KIMMIN~1\AppData\Local\Temp\npm-9868-df3e9abc\registry.npmjs.org\iconv-lite\-\iconv-lite-0.4.13.tgz.1857712106' -> 'C:\Users\KIMMIN~1\AppData\Local\Temp\npm-9868-df3e9abc\registry.npmjs.org\iconv-lite\-\iconv-lite-0.4.13.tgz'
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "harp"
npm ERR! node v7.7.3
npm ERR! npm  v4.1.2

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "harp"
npm ERR! node v7.7.3
npm ERR! npm  v4.1.2
npm ERR! path C:\Users\KIMMIN~1\AppData\Local\Temp\npm-9868-df3e9abc\registry.npmjs.org\iconv-lite\-\iconv-lite-0.4.13.tgz.2692027816
npm ERR! code EBUSY
npm ERR! errno -4082
npm ERR! syscall rename

npm ERR! EBUSY: resource busy or locked, rename 'C:\Users\KIMMIN~1\AppData\Local\Temp\npm-9868-df3e9abc\registry.npmjs.org\iconv-lite\-\iconv-lite-0.4.13.tgz.2692027816' -> 'C:\Users\KIMMIN~1\AppData\Local\Temp\npm-9868-df3e9abc\registry.npmjs.org\iconv-lite\-\iconv-lite-0.4.13.tgz'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "harp"
npm ERR! node v7.7.3
npm ERR! npm  v4.1.2

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Kim Min Young\npm-debug.log

C:\Users\Kim Min Young>https://github.com/npm/npm/issues

**Comment by legodude17** [comment]
Do you have an Antivirus?
