### ISSUE TITLE
npm ERR! "AravindCens" is invalid for new packages : AravindCens

### ISSUE THREAD

**Issue by AravindSundarraj** [npm/npm#16093]
#### I'm opening this issue because: facing exception while executing NPM command publish

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [Y ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
npm ERR! publish Failed PUT 400
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "publish"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code E400

npm ERR! "AravindCens" is invalid for new packages : AravindCens
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:Windows 10
![npmerror](https://cloud.githubusercontent.com/assets/23593203/24076850/8f84cd48-0c09-11e7-9d44-2420b45ef386.png)

 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

[Node_issues.zip](https://github.com/npm/npm/files/852820/Node_issues.zip)

**Comment by KenanY** [comment]
Uppercase characters are no longer allowed in package names.
