### ISSUE TITLE
Unable to install Node Red

### ISSUE THREAD

**Issue by shuynh84** [npm/npm#16098]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [X ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
unable to install Node Red, getting the following error:
npm ERR! Linux 4.4.50-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "--unsafe-perm" "node-red"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code EHOSTUNREACH
npm ERR! errno EHOSTUNREACH
npm ERR! syscall connect

npm ERR! connect EHOSTUNREACH 151.101.48.162:443
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/npm-debug.log

#### How can the CLI team reproduce the problem?

This is what's inside the log file:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   '--unsafe-perm',
1 verbose cli   'node-red' ]
2 info using npm@3.10.10
3 info using node@v6.10.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData node-red
8 silly fetchNamedPackageData node-red
9 silly mapToRegistry name node-red
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'node-red',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'node-red',
12 silly mapToRegistry   name: 'node-red',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/node-red
14 verbose request uri https://registry.npmjs.org/node-red
15 verbose request no auth needed
16 info attempt registry request try #1 at 7:10:05 PM
17 verbose request id 80dd520c3a14581e
18 http request GET https://registry.npmjs.org/node-red
19 info retry will retry, error on last attempt: Error: connect EHOSTUNREACH 151.101.56.162:443
20 info attempt registry request try #2 at 7:10:27 PM
21 http request GET https://registry.npmjs.org/node-red
22 info retry will retry, error on last attempt: Error: connect EHOSTUNREACH 151.101.56.162:443
23 info attempt registry request try #3 at 7:11:38 PM
24 http request GET https://registry.npmjs.org/node-red
25 silly fetchPackageMetaData Error: connect EHOSTUNREACH 151.101.48.162:443
25 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1022:11)
25 silly fetchPackageMetaData     at exports._exceptionWithHostPort (util.js:1045:20)
25 silly fetchPackageMetaData     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
25 silly fetchPackageMetaData  error for node-red { Error: connect EHOSTUNREACH 151.101.48.162:443
25 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1022:11)
25 silly fetchPackageMetaData     at exports._exceptionWithHostPort (util.js:1045:20)
25 silly fetchPackageMetaData     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
25 silly fetchPackageMetaData   code: 'EHOSTUNREACH',
25 silly fetchPackageMetaData   errno: 'EHOSTUNREACH',
25 silly fetchPackageMetaData   syscall: 'connect',
25 silly fetchPackageMetaData   address: '151.101.48.162',
25 silly fetchPackageMetaData   port: 443 }
26 silly rollbackFailedOptional Starting
27 silly rollbackFailedOptional Finishing
28 silly runTopLevelLifecycles Finishing
29 silly install printInstalled
30 verbose stack Error: connect EHOSTUNREACH 151.101.48.162:443
30 verbose stack     at Object.exports._errnoException (util.js:1022:11)
30 verbose stack     at exports._exceptionWithHostPort (util.js:1045:20)
30 verbose stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
31 verbose cwd /home/pi
32 error Linux 4.4.50-v7+
33 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "--unsafe-perm" "node-red"
34 error node v6.10.0
35 error npm  v3.10.10
36 error code EHOSTUNREACH
37 error errno EHOSTUNREACH
38 error syscall connect
39 error connect EHOSTUNREACH 151.101.48.162:443
40 error If you need help, you may report this error at:
40 error     <https://github.com/npm/npm/issues>
41 verbose exit [ 1, true ]

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
Do you have a stable internet connection?

**Comment by shuynh84** [comment]
yes, I've also disabled the windows firewall and my xfinity router firewall

**Comment by shuynh84** [comment]
Thanks for the help, I figured it out. Could not be ran using wifi and SSH. Hard-wired ethernet cable to the raspberry pi did the job.
