### ISSUE TITLE
npm install node-red-contrib-s7 error

### ISSUE THREAD

**Issue by borghiermanno** [npm/npm#16105]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

root@iot2000:/usr/lib/node_modules# npm install node-red-contrib-s7
npm ERR! Linux 4.4.13-yocto-standard
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "node-red-contrib-s7"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! syscall getaddrinfo

npm ERR! getaddrinfo EAI_AGAIN registry.npmjs.org:443
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/lib/node_modules/npm-debug.log

#### How can the CLI team reproduce the problem?

npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   'node-red-contrib-s7' ]
2 info using npm@2.14.12
3 info using node@v4.2.4
4 verbose install initial load of /usr/lib/package.json
5 verbose installManyTop reading scoped package data from /usr/lib/node_modules/mraa/package.json
6 verbose installManyTop reading scoped package data from /usr/lib/node_modules/node-red/package.json
7 verbose installManyTop reading scoped package data from /usr/lib/node_modules/node-red-dashboard/package.json
8 verbose installManyTop reading scoped package data from /usr/lib/node_modules/node-red-node-intel-gpio/package.json
9 verbose installManyTop reading scoped package data from /usr/lib/node_modules/npm/package.json
10 verbose installManyTop reading scoped package data from /usr/lib/node_modules/npm-debug.log/package.json
11 info package.json mraa@v1.5.1 No repository field.
12 info package.json mraa@v1.5.1 No README data
13 info package.json npm@2.14.12 Non-dependency in bundleDependencies: ansi-regex
14 info package.json npm@2.14.12 Non-dependency in bundleDependencies: spdx-license-ids
15 info package.json npm@2.14.12 Non-dependency in bundleDependencies: strip-ansi
16 verbose readDependencies loading dependencies from /usr/lib/package.json
17 silly cache add args [ 'node-red-contrib-s7', null ]
18 verbose cache add spec node-red-contrib-s7
19 silly cache add parsed spec Result {
19 silly cache add   raw: 'node-red-contrib-s7',
19 silly cache add   scope: null,
19 silly cache add   name: 'node-red-contrib-s7',
19 silly cache add   rawSpec: '',
19 silly cache add   spec: 'latest',
19 silly cache add   type: 'tag' }
20 silly addNamed node-red-contrib-s7@latest
21 verbose addNamed "latest" is being treated as a dist-tag for node-red-contrib-s7
22 info addNameTag [ 'node-red-contrib-s7', 'latest' ]
23 silly mapToRegistry name node-red-contrib-s7
24 silly mapToRegistry using default registry
25 silly mapToRegistry registry https://registry.npmjs.org/
26 silly mapToRegistry uri https://registry.npmjs.org/node-red-contrib-s7
27 verbose addNameTag registry:https://registry.npmjs.org/node-red-contrib-s7 not in flight; fetching
28 verbose request uri https://registry.npmjs.org/node-red-contrib-s7
29 verbose request no auth needed
30 info attempt registry request try #1 at 15:32:21
31 verbose request id 66c8daa195d166cb
32 http request GET https://registry.npmjs.org/node-red-contrib-s7
33 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
34 info attempt registry request try #2 at 15:32:32
35 http request GET https://registry.npmjs.org/node-red-contrib-s7
36 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
37 info attempt registry request try #3 at 15:33:32
38 http request GET https://registry.npmjs.org/node-red-contrib-s7
39 verbose stack Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
39 verbose stack     at Object.exports._errnoException (util.js:870:11)
39 verbose stack     at errnoException (dns.js:31:15)
39 verbose stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)
40 verbose cwd /usr/lib/node_modules
41 error Linux 4.4.13-yocto-standard
42 error argv "/usr/bin/node" "/usr/bin/npm" "install" "node-red-contrib-s7"
43 error node v4.2.4
44 error npm  v2.14.12
45 error code EAI_AGAIN
46 error errno EAI_AGAIN
47 error syscall getaddrinfo
48 error getaddrinfo EAI_AGAIN registry.npmjs.org:443
49 error If you need help, you may report this error at:
49 error     <https://github.com/npm/npm/issues>
50 verbose exit [ 1, true ]

### supporting information:

 - Windows 7
 - Network issues:
   - Geographic location where npm was run: Italy
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.

**Comment by legodude17** [comment]
Do you have a stable internet connection?

**Comment by borghiermanno** [comment]
Yes, I have a stable internet connection

**Comment by borghiermanno** [comment]
The IP address was static. I tried changing in DHCP and it worked.
