### ISSUE TITLE
Npm doesn't recognise me as the owner of the repo?

### ISSUE THREAD

**Issue by soggie** [npm/npm#16104]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?

I tried to add another user to the package `easy`, and it says I don't have the authority.

#### How can the CLI team reproduce the problem?

Here's the steps I took:

1. `npm login` (successful as `soggie`)
2. `npm owner add <username> easy` (disallowed)
3. `npm owner ls` gives me:

```
soggie <soggie@gmail.com>
```

4. `npm whoami` gives me:

```
soggie
```

I can verify that I am the owner of this repo, and I'm not sure what went wrong here.

[npm output](https://gist.github.com/soggie/c562bca7e698876175ac1a011776cf67)

[npm-debug.log](https://gist.github.com/soggie/9d0cc2d473f97b4219be127611840ea5)

### supporting information:

 - `npm -v` prints: 3.10.8
 - `node -v` prints: v6.9.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: MacOSX El Capital
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kmanion** [comment]
Hi Soggie, it looks like you got removed as an owner at some point, so no one owned that package. I've gone ahead and transferred it to the new owner, so they should have access to it now.

Feel free to let me know via the support email thread if you need anything else.
