### ISSUE TITLE
unable to install appium 1.6 on windows 7

### ISSUE THREAD

**Issue by prathimak** [npm/npm#16101]
while trying to install appium 1.6 on windows i got below error

101025 error Windows_NT 6.1.7601
101026 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "appium"
101027 error node v6.3.0
101028 error npm  v3.10.3
101029 error code ELIFECYCLE
101030 error appium-chromedriver@2.9.4 install: `node install-npm.js`
101030 error Exit status 1
101031 error Failed at the appium-chromedriver@2.9.4 install script 'node install-npm.js'.
101031 error Make sure you have the latest version of node.js and npm installed.
101031 error If you do, this is most likely a problem with the appium-chromedriver package,
101031 error not with npm itself.
101031 error Tell the author that this fails on your system:
101031 error     node install-npm.js
101031 error You can get information on how to open an issue for this project with:
101031 error     npm bugs appium-chromedriver
101031 error Or if that isn't available, you can get their info via:
101031 error     npm owner ls appium-chromedriver
101031 error There is likely additional logging output above.
101032 verbose exit [ 1, true ]

**Comment by legodude17** [comment]
This is a problem with `appnium`, not `npm`. Did the script produce additional output?
