### ISSUE TITLE
Error: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by mobidevadmin** [npm/npm#16108]
#### I'm opening this issue because:

  - [x] npm is producing an incorrect install.

#### What's going wrong?
npm install fails with "Error: self signed certificate in certificate chain"

#### How can the CLI team reproduce the problem?
run "npm install"

### supporting information:

 - `npm -v` prints:
3.10.8

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'search',
1 verbose cli   'xxx' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 silly mapToRegistry name -/all
5 silly mapToRegistry using default registry
6 silly mapToRegistry registry https://registry.npmjs.org/
7 silly mapToRegistry data Result {
7 silly mapToRegistry   raw: '-/all',
7 silly mapToRegistry   scope: null,
7 silly mapToRegistry   escapedName: null,
7 silly mapToRegistry   name: null,
7 silly mapToRegistry   rawSpec: '-/all',
7 silly mapToRegistry   spec: '-/all',
7 silly mapToRegistry   type: 'local' }
8 silly mapToRegistry uri https://registry.npmjs.org/-/all
9 info updateIndex C:\Users\someuser\AppData\Roaming\npm-cache\registry.npmjs.org\-\all\.cache.json
10 verbose correctMkdir C:\Users\someuser\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
11 verbose updateIndex Cached search data present with timestamp 434592768000
12 silly update-index fetching https://registry.npmjs.org/-/all/since?stale=update_after&startkey=434592768000
13 verbose request uri https://registry.npmjs.org/-/all/since?stale=update_after&startkey=434592768000
14 verbose request no auth needed
15 info attempt registry request try #1 at 1:41:35 PM
16 verbose request id f4114fbf5e8fb1d1
17 http request GET https://registry.npmjs.org/-/all/since?stale=update_after&startkey=434592768000
18 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
19 info attempt registry request try #2 at 1:41:45 PM
20 http request GET https://registry.npmjs.org/-/all/since?stale=update_after&startkey=434592768000
21 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
22 info attempt registry request try #3 at 1:42:45 PM
23 http request GET https://registry.npmjs.org/-/all/since?stale=update_after&startkey=434592768000
24 verbose stack Error: self signed certificate in certificate chain
24 verbose stack     at Error (native)
24 verbose stack     at TLSSocket.<anonymous> (_tls_wrap.js:1062:38)
24 verbose stack     at emitNone (events.js:86:13)
24 verbose stack     at TLSSocket.emit (events.js:185:7)
24 verbose stack     at TLSSocket._finishInit (_tls_wrap.js:586:8)
24 verbose stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38)
25 verbose cwd D:\Agent\_work\14\s
26 error Windows_NT 6.3.9600
27 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "search" "xxx"
28 error node v6.9.1
29 error npm  v3.10.8
30 error code SELF_SIGNED_CERT_IN_CHAIN
31 error self signed certificate in certificate chain
32 error If you need help, you may report this error at:
32 error     <https://github.com/npm/npm/issues>
33 verbose exit [ 1, true ]

-->

**Comment by legodude17** [comment]
Have you taken a look at http://blog.npmjs.org/post/78165272245/more-help-with-selfsignedcertinchain-and-npm? See if the steps outlined there work for you.

If it does NOT:

1. Are you behind a proxy?
2. How are you trying to use it?

**Comment by mobidevadmin** [comment]
Hello,

http://blog.npmjs.org/post/78165272245/more-help-with-selfsignedcertinchain-and-npm
this didn't help

1. Are you behind a proxy?
Is it really matters? If so, how I can check it by using node.js/npm?

2. How are you trying to use it?
I'm installing all dependencies by issuing "node install" in PowerShell console

**Comment by legodude17** [comment]
You want to use `npm install` not `node install`. Also, the log says you ran `npm search xxx`.

**Comment by mobidevadmin** [comment]
correct, that is the log for "npm search xxx" command which I issued just for log example. It started with that I couldn't issue "npm install".

**Comment by legodude17** [comment]
What was the log from `npm install`?
