### ISSUE TITLE
How to install dependencies for project without changing working directory to project root?

### ISSUE THREAD

**Issue by aalexgabi** [npm/npm#16107]
Curently you need to execute:

```
cd /my/project/root && npm install && cd -
```
I'm looking for an option like -C for Makefile so that I can:

```
npm install -C /my/project/root
```
Any ideas on how to accomplish this?

Also posted here: http://stackoverflow.com/questions/37485787/how-to-run-npm-install-without-changing-working-directory

**Comment by legodude17** [comment]
You could also use `(cd /my/project/root && npm install)`.

**Comment by aalexgabi** [comment]
A colleague of mine has found a way to do this (note that this is not documented):
```
npm install --prefix /my/project/root
```

@isaacs Should this be documented?
