### ISSUE TITLE
Errors when installing cytoscape-cose-bilkent using npm

### ISSUE THREAD

**Issue by qcx3000** [npm/npm#16100]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I downloaded cytoscape-cose-bilkent ZIP file from https://github.com/cytoscape/cytoscape.js-cose-bilkent 
I uncompressed the ZIP file. I use Windows.
Then, in the folder “cytoscape.js-cose-bilkent-master\cytoscape.js-cose-bilkent-master”, I run:

    npm install cytoscape-cose-bilkent

But I got the following errors:

    npm ERR! Windows_NT 10.0.14393
    npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "cytoscape-cose-bilkent"
    npm ERR! node v6.9.5
    npm ERR! npm  v3.10.10
    npm ERR! code ENOSELF

    npm ERR! Refusing to install cytoscape-cose-bilkent as a dependency of itself
    npm ERR!
    npm ERR! If you need help, you may report this error at:
    npm ERR!     <https://github.com/npm/npm/issues>

    npm ERR! Please include the following file with any support request:
    npm ERR!     C:\Users\jt2000\Downloads\cytoscape.js-cose-bilkent-master\cytoscape.js-cose-bilkent-master\npm-debug.log

I am attaching the file “npm-debug.log” (npm-debug-log.txt).

Thank you very much for your help!

#### How can the CLI team reproduce the problem?

    To reproduce this problem:
       In Windows:
       (1) downloaded cytoscape-cose-bilkent ZIP file from https://github.com/cytoscape/cytoscape.js-cose-bilkent 
       (2) uncompress the ZIP file. 
       (3) Then, in the folder “cytoscape.js-cose-bilkent-master\cytoscape.js-cose-bilkent-master”, run:
                npm install cytoscape-cose-bilkent

Include a gist of your npm-debug.log file.
[npm-debug-log.txt](https://github.com/npm/npm/files/854404/npm-debug-log.txt)

### supporting information:

 - `npm -v` prints: 3.10.10
 - `node -v` prints: v6.9.5
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows
 - Network issues:
   - Geographic location where npm was run: California, USA
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
Running `npm install cytoscape-cose-bilkent` from within a directory which contains said package does not make much sense, as that would imply that the package is a dependency of itself. I think what you want to do is just run plain `npm install`,  in order to install the package's dependencies. Or, you should `cd` into your own project directory and just install the module with `npm` there.

**Comment by qcx3000** [comment]
Thank you very much for your advice!
