### ISSUE TITLE
npm install -g cordova Error : ECONNRESET 

### ISSUE THREAD

**Issue by jackryu** [npm/npm#16111]
npm install -g cordova not installing please  help error details belo

NPM -v (v4.4.1)
node -v (v6.9.4)

C:\Windows\system32>npm install -g cordova
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read
npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm ERR! shasum check failed for C:\Users\iMac\AppData\Local\Temp\npm-7636-db01325b\registry.npmjs.org\cordova-app-hell
-world\-\cordova-app-hello-world-3.11.0.tgz
npm ERR! Expected: 9214feb9dd713ca481a1cbabceeca60966c1c0cf
npm ERR! Actual:   c38747acd80b3147906eb3c7e6593ea3bbaac455
npm ERR! From:     https://registry.npmjs.org/cordova-app-hello-world/-/cordova-app-hello-world-3.11.0.tgz

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\iMac\AppData\Roaming\npm-cache\_logs\2017-03-21T00_30_19_476Z-debug.log

**Comment by legodude17** [comment]
Hello! This is a duplicate of #14626. Try updating to the latest version of `npm`, as it was fixed there.

**Comment by jackryu** [comment]
Ok try - thanks
