### ISSUE TITLE
npm cache clean ERR! Error: EPERM: operation not permitted, rmdir

### ISSUE THREAD

**Issue by Kapunya** [npm/npm#16128]
Frequently, when trying to execute the npm-cache install npm script, I get this failed error message. If I run it again it usually succeeds. What is causing rmdir to fail? It only happens when node_modules is not empty.

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\dev\\nodejs\\node.exe" "C:\\dev\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "cache" "clean"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! path C:\Users\userName\AppData\Roaming\npm-cache
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rmdir

npm ERR! Error: EPERM: operation not permitted, rmdir 'C:\Users\userName\AppData\Roaming\npm-cache'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM: operation not permitted, rmdir 'C:\Users\userName\AppData\Roaming\npm-cache']
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'rmdir',
npm ERR!   path: 'C:\\Users\\userName\\AppData\\Roaming\\npm-cache' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\dev\#Projects\ASP.Net.Core1.Angular2.Webpack.Starter\src\starterproject\npm-debug.log

**Comment by legodude17** [comment]
Do you have permission to `C:\Users\userName\AppData\Roaming`?

**Comment by Kapunya** [comment]
yes, this issue is reproducible time to time, approximately once for 20 runs.
I have feeling that some process is locking this folder

**Comment by legodude17** [comment]
Yeah, do you have an antivirus?

**Comment by Kapunya** [comment]
no, no antivirus on buildagents
