### ISSUE TITLE
npm install hangs

### ISSUE THREAD

**Issue by mtsi** [npm/npm#16120]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [x ] Other (_see below for feature requests_):

#### What's going wrong?
I am attempting to do:

npm install -g @angular/cli

The install hangs at a line that says:

loadRequestedDeps: sill install loadAllDepsIntoIdealTree

I have since noted that anything I try to install with npm hangs in the same place

#### How can the CLI team reproduce the problem?

Just execute the npm install command on anything

  https://gist.github.com/mtsi/c7ed3f6ca257b2514abba1b519354548

### supporting information:

 - `npm -v` prints: 4.1.2
 - `node -v` prints: 7.7.3
 - `npm config get registry` prints: https://registry.npmjs.org
 - Windows, OS X/macOS, or Linux?: Windows 8.1
 - Network issues:
   - Geographic location where npm was run: Los Angeles
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
Do you have access to `C:\Users\Michael.WORKTOP.001\Desktop\ReactTutorials\reactApp`?
