### ISSUE TITLE
NPM error that I'm facing

### ISSUE THREAD

**Issue by 8ivek** [npm/npm#16127]
#### I'm opening this issue because:
  - [x] npm is doing something I don't understand.

#### What's going wrong?

Its giving me error in my windows machine.

### supporting information:

 - `npm -v` prints: 4.3.0
 - `node -v` prints: 6.10.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows
![npm_error](https://cloud.githubusercontent.com/assets/1044118/24205295/5a21bda6-0ef1-11e7-9715-8845eabe6cbb.png

)

**Comment by KenanY** [comment]
@8ivek What are you expecting `npm run *` to do? The [docs](https://docs.npmjs.com/cli/run-script) don't mention the wildcard character and I do not believe that any special behavior exists when one uses it in this context.

**Comment by 8ivek** [comment]
Thank you @KenanY
