### ISSUE TITLE
npm start troubles

### ISSUE THREAD

**Issue by icemancapo** [npm/npm#16135]
hello, my name it´s Roberto and i need help because i´m typed npm start for a project electron, but show me this
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10

npm ERR! missing script: start
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\proyecto\Librodemo\npm-debug.log

Please help me

**Comment by legodude17** [comment]
Hello! The error log said you're missing the `start` script. To use `npm start`, you need to put it into the script field in your package.json like:
```
{
  "script": {
    "start": "echo hi"
  }
}
```
See this example for your reference: https://docs.npmjs.com/misc/scripts#examples

Thanks
