### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by ffelaar** [npm/npm#16130]
sorry if this is not being reported correctly - besides my issue, github also seems to be having problems - no styling loaded on any page
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
running npm install ... i get a ton of errors ... see below ...
npm ERR! fetch failed https://registry.npmjs.org/@angular/compiler/-/compiler-2.                                                               0.0.tgz
npm WARN retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN r                                                               egistry.npmjs.org:443
npm ERR! fetch failed https://registry.npmjs.org/@angular/forms/-/forms-2.0.0.tg                                                               z
npm WARN retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN r                                                               egistry.npmjs.org:443
npm ERR! fetch failed https://registry.npmjs.org/@angular/common/-/common-2.0.0.                                                               tgz
npm WARN retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN r                                                               egistry.npmjs.org:443
npm ERR! fetch failed https://registry.npmjs.org/@angular/http/-/http-2.0.0.tgz
npm WARN retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN r                                                               egistry.npmjs.org:443
npm ERR! fetch failed https://registry.npmjs.org/@angular/core/-/core-2.0.0.tgz
npm WARN retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN r                                                               egistry.npmjs.org:443
npm ERR! fetch failed https://registry.npmjs.org/@angular/platform-browser-dynam                                                               ic/-/platform-browser-dynamic-2.0.0.tgz
npm WARN retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN r                                                               egistry.npmjs.org:443
npm ERR! fetch failed https://registry.npmjs.org/@angular/compiler-cli/-/compile                                                               r-cli-0.6.2.tgz
npm WARN retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN r                                                               egistry.npmjs.org:443
npm ERR! fetch failed https://registry.npmjs.org/@angular/platform-browser/-/pla                                                               tform-browser-2.0.0.tgz
npm WARN retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN r                                                               egistry.npmjs.org:443
npm ERR! fetch failed https://registry.npmjs.org/@angular/platform-server/-/plat                                                               form-server-2.0.0.tgz
npm WARN retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN r                                                               egistry.npmjs.org:443
npm ERR! fetch failed https://registry.npmjs.org/ionic-native/-/ionic-native-2.2                                                               .3.tgz
npm WARN retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN r                                                               egistry.npmjs.org:443
npm ERR! fetch failed https://registry.npmjs.org/@ionic/storage/-/storage-1.1.6.                                                               tgz
npm WARN retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN r                                                               egistry.npmjs.org:443
npm ERR! fetch failed https://registry.npmjs.org/ionic-angular/-/ionic-angular-2                                                               .0.0-rc.1.tgz
npm WARN retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN r                                                               egistry.npmjs.org:443
npm ERR! fetch failed https://registry.npmjs.org/zone.js/-/zone.js-0.6.21.tgz
npm WARN retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN r                                                               egistry.npmjs.org:443
npm ERR! fetch failed https://registry.npmjs.org/@angular/compiler/-/compiler-2.0.0.tgz
npm WARN retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
npm ERR! fetch failed https://registry.npmjs.org/@angular/forms/-/forms-2.0.0.tgz
npm WARN retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
npm ERR! fetch failed https://registry.npmjs.org/@angular/common/-/common-2.0.0.tgz
npm WARN retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
npm ERR! fetch failed https://registry.npmjs.org/@angular/http/-/http-2.0.0.tgz
npm WARN retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
npm ERR! fetch failed https://registry.npmjs.org/@angular/compiler-cli/-/compiler-cli-0.6.2.tgz
npm WARN retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
npm ERR! fetch failed https://registry.npmjs.org/@angular/platform-browser-dynamic/-/platform-browser-dynamic-2.0.0.tgz
npm WARN retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
npm ERR! fetch failed https://registry.npmjs.org/@angular/core/-/core-2.0.0.tgz
npm WARN retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
npm ERR! fetch failed https://registry.npmjs.org/@angular/platform-browser/-/platform-browser-2.0.0.tgz
npm WARN retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
npm ERR! fetch failed https://registry.npmjs.org/@angular/platform-server/-/platform-server-2.0.0.tgz
npm WARN retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
npm ERR! fetch failed https://registry.npmjs.org/ionic-native/-/ionic-native-2.2.3.tgz
npm WARN retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
npm ERR! fetch failed https://registry.npmjs.org/@ionic/storage/-/storage-1.1.6.tgz
npm WARN retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
npm ERR! fetch failed https://registry.npmjs.org/ionic-angular/-/ionic-angular-2.0.0-rc.1.tgz
npm WARN retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
npm ERR! fetch failed https://registry.npmjs.org/zone.js/-/zone.js-0.6.21.tgz
npm WARN retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
npm ERR! fetch failed https://registry.npmjs.org/@angular/compiler/-/compiler-2.0.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/@angular/forms/-/forms-2.0.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/@angular/common/-/common-2.0.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/@angular/http/-/http-2.0.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/@angular/platform-browser-dynamic/-/platform-browser-dynamic-2.0.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/@angular/platform-browser/-/platform-browser-2.0.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/@angular/compiler-cli/-/compiler-cli-0.6.2.tgz
npm ERR! fetch failed https://registry.npmjs.org/@angular/core/-/core-2.0.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/@angular/platform-server/-/platform-server-2.0.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/@ionic/storage/-/storage-1.1.6.tgz
npm ERR! fetch failed https://registry.npmjs.org/ionic-native/-/ionic-native-2.2.3.tgz
npm ERR! fetch failed https://registry.npmjs.org/ionic-angular/-/ionic-angular-2.0.0-rc.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/zone.js/-/zone.js-0.6.21.tgz
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\Fatima\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.10.0
npm ERR! npm  v4.2.0
npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! syscall getaddrinfo

npm ERR! getaddrinfo EAI_AGAIN registry.npmjs.org:443
npm ERR!
npm ERR! If you need help, you may report this error 

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
Do you have a stable internet connection?

**Comment by ffelaar** [comment]
indeed it was because of my unstable connection ... since resolved ...
thanks for responding!
