### ISSUE TITLE
npm start errors for js-fea

### ISSUE THREAD

**Issue by hasanbaghal** [npm/npm#16134]
****npm start errors for js-fea

at this address**

https://github.com/lge88/js-fea

**This is my install warns****

admin@DESKTOP-RL4UNOL MINGW32 /c/testoldjs_fea
$ npm install
npm WARN deprecated gulp-webpack@1.5.0: Renamed to https://www.npmjs.com/package                                                                                                                /webpack-stream
npm WARN deprecated gulp-jsdoc@0.1.5: This project is deprecated. Use gulp-jsdoc                                                                                                                3 instead.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher                                                                                                                 to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher                                                                                                                 to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail o                                                                                                                n node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible                                                                                                                . Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated wrench@1.5.9: wrench.js is deprecated! You should check out                                                                                                                 fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you                                                                                                                 were using wrench for. Thanks for all the usage over the years.
npm WARN deprecated wrench@1.3.9: wrench.js is deprecated! You should check out                                                                                                                 fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you                                                                                                                 were using wrench for. Thanks for all the usage over the years.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install th                                                                                                                e latest version of pug instead of jade
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use                                                                                                                 @segment/to-iso-string instead.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher                                                                                                                 to avoid a RegExp DoS issue
npm WARN prefer global marked@0.3.6 should be installed with -g

> jsdoc@3.3.0-alpha5 postinstall C:\testoldjs_fea\node_modules\jsdoc
> node ./node/postinstall.js

js-fea@0.0.1 C:\testoldjs_fea
....
....
....
**and so this is my start errors**

admin@DESKTOP-RL4UNOL MINGW32 /c/testoldjs_fea
$ npm start
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v7.7.4
npm ERR! npm  v4.1.2

npm ERR! missing script: start
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\testoldjs_fea\npm-debug.log

**what could I do?**

**Comment by legodude17** [comment]
Hello! The error log said you're missing the `start` script. To use `npm start`, you need to put it into the script field in your package.json like:

{
  "script": {
    "start": "echo hi"
  }
}
See this example for your reference: https://docs.npmjs.com/misc/scripts#examples

Thanks

**Comment by hasanbaghal** [comment]
**Hi,I modified that.so I have this** 
**for install**

C:\js_fea_01\js-fea>npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN enoent ENOENT: no such file or directory, open 'C:\js_fea_01\js-fea\node_modules\jsdoc\lib\jsdoc\package.json'
npm WARN js-fea@0.0.1 No repository field.

**And for start**

C:\js_fea_01\js-fea>npm start

> js-fea@0.0.1 start C:\js_fea_01\js-fea
> echo hi

hi

C:\js_fea_01\js-fea>

**So,nothing happen except echo hi**

**this is 
my package.json
text**

{

  "name": "js-fea",
  "version": "0.0.1",
  "description": "Finite Element Analysis in Javascript.",
  "main": "src/index.js",
  "scripts": {
    "test": "node_modules/gulp-mocha/node_modules/mocha/bin/mocha test/unit && node_modules/gulp-mocha/node_modules/mocha/bin/mocha test/spec",
    **"start": "echo hi"**
  },
  "keywords": [
    "fea",
    "numeric"
  ],
  "homepage": "http://lige.me/js-fea",
  "bugs": "https://github.com/lge88/js-fea/issues",
  "author": "Li Ge <lge@ucsd.edu> (http://lige.me/)",
  "license": "MIT",
  "dependencies": {
    "lodash": "^2.4.1",
    "check-types": "^2.2.0",
    "numeric": "^1.2.6"
  },
  "devDependencies": {
    "data-driven": "^1.1.0",
    "del": "^1.1.1",
    "expect.js": "^0.3.1",
    "gulp": "^3.8.10",
    "gulp-bump": "^0.1.11",
    "gulp-concat": "^2.4.3",
    "gulp-file": "^0.2.0",
    "gulp-gh-pages": "^0.5.0",
    "gulp-istanbul": "^0.6.0",
    "gulp-jsdoc": "^0.1.4",
    "gulp-load-plugins": "^0.8.0",
    "gulp-mocha": "^2.0.0",
    "gulp-rename": "^1.2.0",
    "gulp-sourcemaps": "^1.3.0",
    "gulp-task-listing": "^1.0.0",
    "gulp-template": "^2.1.0",
    "gulp-uglify": "^1.1.0",
    "gulp-util": "^3.0.2",
    "gulp-webpack": "^1.2.0",
    "merge-stream": "^0.1.7",
    "minimist": "^1.1.0"
  }

}

**what should I do to run the program?
Regards**

**Comment by KenanY** [comment]
@hasanbaghal We can't tell you exactly, since the procedure varies from project to project. Maybe you could try asking the developer of that project.
