### ISSUE TITLE
npm test errors for js-fea

### ISSUE THREAD

**Issue by hasanbaghal** [npm/npm#16136]
**Hello,
npm test errors for js-fea**

**at this address**

https://github.com/lge88/js-fea

**This is my package.json text**

{

  "name": "js-fea",
  "version": "0.0.1",
  "description": "Finite Element Analysis in Javascript.",
  "main": "src/index.js",
  "scripts": {
    "test": "node_modules/gulp-mocha/node_modules/mocha/bin/mocha test/unit && node_modules/gulp-mocha/node_modules/mocha/bin/mocha test/spec",
    "start": "echo hi"
  },
  "keywords": [
    "fea",
    "numeric"
  ],
  "homepage": "http://lige.me/js-fea",
  "bugs": "https://github.com/lge88/js-fea/issues",
  "author": "Li Ge <lge@ucsd.edu> (http://lige.me/)",
  "license": "MIT",
  "dependencies": {
    "lodash": "^2.4.1",
    "check-types": "^2.2.0",
    "numeric": "^1.2.6"
  },
  "devDependencies": {
    "data-driven": "^1.1.0",
    "del": "^1.1.1",
    "expect.js": "^0.3.1",
    "gulp": "^3.8.10",
    "gulp-bump": "^0.1.11",
    "gulp-concat": "^2.4.3",
    "gulp-file": "^0.2.0",
    "gulp-gh-pages": "^0.5.0",
    "gulp-istanbul": "^0.6.0",
    "gulp-jsdoc": "^0.1.4",
    "gulp-load-plugins": "^0.8.0",
    "gulp-mocha": "^2.0.0",
    "gulp-rename": "^1.2.0",
    "gulp-sourcemaps": "^1.3.0",
    "gulp-task-listing": "^1.0.0",
    "gulp-template": "^2.1.0",
    "gulp-uglify": "^1.1.0",
    "gulp-util": "^3.0.2",
    "gulp-webpack": "^1.2.0",
    "merge-stream": "^0.1.7",
    "minimist": "^1.1.0"
  }

}

**and so this is my npm test errors**

C:\js_fea_01\js-fea>npm test

> js-fea@0.0.1 test C:\js_fea_01\js-fea
> node_modules/gulp-mocha/node_modules/mocha/bin/mocha test/unit && node_modules/gulp-mocha/node_modules/mocha/bin/mocha test/spec

'node_modules' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Test failed.  See above for more details.

**and so this is my program directory** 

C:\js_fea_01\js-fea>dir
 Volume in drive C is OS
 Volume Serial Number is 8CC2-AFF8

 Directory of C:\js_fea_01\js-fea

03/23/2017  10:49 PM    <DIR>          .
03/23/2017  10:49 PM    <DIR>          ..
03/23/2017  10:21 PM               381 .gitignore
03/23/2017  10:21 PM    <DIR>          build
03/23/2017  10:21 PM             3,457 gulpfile.js
03/23/2017  10:49 PM    <DIR>          node_modules
03/23/2017  10:49 PM             1,316 package.json
03/23/2017  10:21 PM               145 pre-commit.sh
03/23/2017  10:21 PM               149 README.md
03/23/2017  10:21 PM    <DIR>          src
03/23/2017  10:21 PM    <DIR>          test
03/23/2017  10:21 PM               118 TODO.md
03/23/2017  10:21 PM    <DIR>          tools
               6 File(s)          5,566 bytes
               7 Dir(s)  65,686,827,008 bytes free

C:\js_fea_01\js-fea>
**what could I do?
Regards**

**Comment by KenanY** [comment]
Try:

``` json
"scripts": {
  "test": "./node_modules/gulp-mocha/node_modules/mocha/bin/mocha test/unit && ./node_modules/gulp-mocha/node_modules/mocha/bin/mocha test/spec",
  "start": "echo hi"
},
```

or just:

``` json
"scripts": {
  "test": "mocha test/unit && mocha test/spec",
  "start": "echo hi"
},
```
