### ISSUE TITLE
npm install express npm ERR! Darwin 15.6.0

### ISSUE THREAD

**Issue by goodyis** [npm/npm#16132]
#### I'm opening this issue because:
- This is a duplicate of a few; but keyword/search issues inspired me to make this one 
- To add this title and key words, incase others search the way I do.
**# - Issue is resolved via: npm config set strict-ssl false**
   - went back to find the orig 'credit' for this statement; and couldn't, yet another reason why I want to create another ticket. Wanted to credit to someone, but lost the ticket/page
 
- KEYWORDS: Mac, Terminal, Node, Node.js, Express, NPM Failure, NPM Module Fail, npm install express, npm ERR! Darwin 15.6.0

   ==

#### What's going wrong?
 - simple npm install commands error out/don't work

#### How can the CLI team reproduce the problem?
 - Work behind a network that automatically forces auto-signed-certificates
 - Using Mac and terminal

### supporting information:

- Command attempted after brand new >npm install express
- Result:

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/7.7.4/bin/node" "/usr/local/bin/npm" "install" "express"
npm ERR! node v7.7.4
npm ERR! npm  v4.1.2
npm ERR! code SELF_SIGNED_CERT_IN_CHAIN
npm ERR! self signed certificate in certificate chain
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by legodude17** [comment]
Have you taken a look at http://blog.npmjs.org/post/78165272245/more-help-with-selfsignedcertinchain-and-npm? See if the steps outlined there work for you.

If it does NOT:

1. Are you behind a proxy?
2. How are you trying to use it?

**Comment by goodyis** [comment]
**That link did nothing for me.**
I first set `npm config set strict-ssl true` ( that was the only change I had made - I set it false )

# **Proceeded to your link:**
**Step 1** `npm install npm -g --ca=null`

-- would not work, until `npm config set strict-ssl false` was set again
I set to false, then tried step 1 again; it was successful -> but I already had that version.

#**Set this back for good measure:** `npm config set strict-ssl true`
**Proceeded to Step 2** in link
`npm config set ca=""`

#**Step3** 
 - Since I wasn't using anything the frameworks/systems listed; I proceed to do a simple install
`npm install -g grunt-cli`

and got that same error:
npm ERR! code SELF_SIGNED_CERT_IN_CHAIN
npm ERR! self signed certificate in certificate chain

#**Set this back for good measure:** `npm config set strict-ssl false`
`npm install -g grunt-cli` worked like a charm again

**Comment by goodyis** [comment]
Then upon further inquire; didn't have proxy; but have Kaspersky; and had it was trying to force SSL connections. 
Switched that off. Switched `npm config set strict-ssl true` back to 'original setting'
attempted another module -> `npm install -g yo` -> worked like a charm

Kaspersky settings:
<img width="414" alt="screen shot 2017-03-23 at 3 48 40 pm" src="https://cloud.githubusercontent.com/assets/5034551/24269956/417641d2-0fe1-11e7-8e62-8fcf7539bf6f.png">

MY fix: 
<img width="389" alt="screen shot 2017-03-23 at 3 48 45 pm" src="https://cloud.githubusercontent.com/assets/5034551/24269957/4180260c-0fe1-11e7-8205-31052ba55e64.png">

**Comment by splus1** [comment]
I was getting the same error message with installing 'electron':
> electron@1.6.5 postinstall /usr/lib/node_modules/electron
> node install.js

/usr/lib/node_modules/electron/install.js:47
  throw err
  ^

Error: self signed certificate in certificate chain
    at TLSSocket.<anonymous> (_tls_wrap.js:1088:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:188:7)
    at TLSSocket._finishInit (_tls_wrap.js:610:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)

I have a firewall that does ssl-decrypt and can't turn it off.
Used "npm config set strict-ssl false" and that fixed the issue.
