### ISSUE TITLE
WebGL finite element viewer  https://mikolalysenko.github.io/femgl show nothing on browser...

### ISSUE THREAD

**Issue by hasanbaghal** [npm/npm#16138]
**Hello,
 WebGL finite element viewer**  https://mikolalysenko.github.io/femgl 
**show nothing on browser...

at this address**
https://github.com/mikolalysenko/femgl

**this is my installation**

C:\femgl\femgl>npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

this is my package.json text file

{
  "name": "femgl",
  "version": "1.0.0",
  "description": "Finite element mesh viewer",
  "main": "index.js",
  "scripts": {
    "build": "python convert/example.py",
    "build-page": "browserify index.js | indexhtmlify > index.html",
    "start": "budo index.js --open --live"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/mikolalysenko/femgl.git"
  },
  "keywords": [
    "finite",
    "element",
    "mesh",
    "viewer",
    "webgl"
  ],
  "author": "Mikola Lysenko",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/mikolalysenko/femgl/issues"
  },
  "browserify": {
    "transform": [
      "es2020"
    ]
  },
  "homepage": "https://github.com/mikolalysenko/femgl#readme",
  "dependencies": {
    "browserify": "^13.3.0",
    "budo": "^9.4.1",
    "control-panel": "^1.2.0",
    "drag-and-drop-files": "0.0.1",
    "es2020": "^1.1.9",
    "indexhtmlify": "^1.3.1",
    "regl": "^1.3.0",
    "regl-camera": "^1.1.0"
  }
}

**and when I start by npm start I see blank page in browser , with address of** http://192.168.5.10:9966/  **and title of budo

this is my npm start** 

C:\femgl\femgl>npm start

> femgl@1.0.0 start C:\femgl\femgl
> budo index.js --open --live

[0003] info  Server running at http://192.168.5.10:9966/ (connect)
[0003] info  LiveReload running on 35729
[0006] 20ms        256B GET    200 / (generated)
[0015] 11.8s      4.2MB (browserify)
[0015] 8998ms     4.2MB GET    200 /index.js (generated)

**and this is my page source code**

<!DOCTYPE html><html lang="en" dir="ltr"><head><title>budo</title><meta charset="utf-8"></head><body><script type="text/javascript" src="//192.168.5.10:35729/livereload.js?snipver=1" async="" defer=""></script><script src="index.js"></script></body></html>

**and this is the result.blank page**

![femgl01](https://cloud.githubusercontent.com/assets/26565997/24269724/04238a66-1030-11e7-81fa-fd11fc81a1db.jpg)

**what could I do?
 Regards**

**Comment by KenanY** [comment]
Closing as not an issue with `npm`.
