### ISSUE TITLE
NPM install "UNMET PEER DEPENDENCY react@0.14.8 invalid" error

### ISSUE THREAD

**Issue by yuyingliu331** [npm/npm#16145]
#### I'm opening this issue because:

When I try to install react@0.14.8 it shows unmet peer dependency react@0.14.8 invalid. 

![screen shot 2017-03-24 at 12 34 13](https://cloud.githubusercontent.com/assets/17233437/24304031/707bee52-108e-11e7-9b66-d247d487e1d4.png)

**Comment by legodude17** [comment]
Try installing `react@15.4.2`

**Comment by yuyingliu331** [comment]
Still showing the same issue: see below: 
 UNMET PEER DEPENDENCY react@15.4.2 invalid
└── UNMET PEER DEPENDENCY react-dom@15.4.2

**Comment by legodude17** [comment]
Now what are the warnings?
