### ISSUE TITLE
npm ERR! Windows_NT 10.0.14393 

### ISSUE THREAD

**Issue by mragansh** [npm/npm#16143]
#### I'm opening this issue because:

  
  - [npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v7.7.4
npm ERR! npm  v4.1.2

npm ERR! Unexpected token < in JSON at position 0
npm ERR! <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
npm ERR! <html xmlns="http://www.w3.org/1999/xhtml">
npm ERR! <head>
npm ERR! <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
npm ERR! <title>403 - Forbidden: Access is denied.</title>
npm ERR! <style type="text/css">
npm ERR! 
npm ERR! </style>
npm ERR! </head>
npm ERR! <body>
npm ERR! <div id="header"><h1>Server Error</h1></div>
npm ERR! <div id="content">
npm ERR!  <div class="content-container"><fieldset>
npm ERR!   <h2>403 - Forbidden: Access is denied.</h2>
npm ERR!   <h3>You do not have permission to view this directory or page using the credentials that you supplied.</h3>
npm ERR!  </fieldset></div>
npm ERR! </div>
npm ERR! </body>
npm ERR! </html>
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\test\Desktop\HILTI\code-home\code-home\hvb-web\hvb-app\npm-debug.log ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@mragansh Are you behind a proxy or firewall by any chance?

**Comment by mragansh** [comment]
NO, i am using my own home wifi.

**Comment by mragansh** [comment]
Also when i swtiched off my firewall in my PC, getting

npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json

**Comment by KenanY** [comment]
@mragansh Could you upload the resulting `npm-debug.log` file to <https://gist.github.com/> and post a link to it here?

**Comment by mragansh** [comment]
[log.zip](https://github.com/npm/npm/files/868410/log.zip)

**Comment by mragansh** [comment]
![untitled](https://cloud.githubusercontent.com/assets/8350241/24301973/000791b4-10d7-11e7-8f3e-c04617b7f35b.png)
Screen.

**Comment by KenanY** [comment]
@mragansh Again, please upload the log as plaintext to <https://gist.github.com/> instead of zipping it up.

**Comment by mragansh** [comment]
[log.txt](https://github.com/npm/npm/files/868433/log.txt)

**Comment by KenanY** [comment]
@mragansh See: <http://www.telerik.com/kendo-angular-ui/getting-started/#toc-add-the-progress-npm-registry>. You need to authenticate yourself with Telerik's registry, otherwise they're just gonna keep giving you the "Access Denied" responses you are seeing.

**Comment by mragansh** [comment]
i did authenticate using command 
npm login --registry=https://registry.npm.telerik.com/ --scope=@progress.

**Comment by mragansh** [comment]
steps which i did. update my angualr cli to version npm install -g @angular/cli@1.0.0-beta.32.3, and then authenticate to Telerik's registry, with username, password and email (public), then npm install

**Comment by KenanY** [comment]
@mragansh I suggest [bringing this up with Telerik themselves](https://www.telerik.com/account/support-tickets/contact-support-team?pid=1800), as suggested by one of their developers (see https://github.com/npm/npm/issues/14197#issuecomment-288050641).

**Comment by mragansh** [comment]
Also, i also updated node registry. but i am not able to judge why i am getting parse error for JSON. Can you help me in this, is there anything need to change in JSON

**Comment by mragansh** [comment]
#14197 (comment) : as said in comment, i did as same, and got authenticated. 

```
C:\Users\test\Desktop\HILTI\code-home\code-home\hvb-web\hvb-app>npm login --registry=https://registry.npm.telerik.com/ --scope=@progress
Username: mragansh
Password:
Email: (this IS public) mragansh.tomar@globallogic.com
Logged in as mragansh to scope @progress on https://registry.npm.telerik.com/.
```

**Comment by KenanY** [comment]
@mragansh My suggestion to contact the owners of the registry (Telerik) still stands.

**Comment by mragansh** [comment]
@KenanY  : i think, fix or give suggestion before you close this ticket. that comment you referred only ,how get id for Telerik's  account. 

Comment #14197 you suggested:
yeah i got solution.

Actually it was not worked with already existed login credential for telerik.
first you create new gmail account then
go to the telerik.com in that create account
then register with above gmail id.then it will ask for activation link just go to the gmail id and then click on activation link. then you will easily solve the login problem for below code
npm login --registry=https://registry.npm.telerik.com/ --scope=@progress
username:telerik username
password:telerik password
gmail id: urs mail id which is used for telerik registration.
This is worked for me:-)

**Comment by KenanY** [comment]
@mragansh I gave a suggestion (open a ticket with Telerik) when I closed the issue. Since this is not an issue with `npm` (as evident by the solution you found that worked for you), this issue tracker is not the appropriate place for tickets like these.

**Comment by mragansh** [comment]
below lines i got when using npm, i think there should be listed what kind issue should be tracked around. Also, only you have seen Telerik name in the log or image attached by me, without any facts or you have closed this issue.

npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\test\Desktop\HILTI\code-home\code-home\hvb-web\hvb-app\npm-debug.log

**Comment by mragansh** [comment]
anyways thanks !!
