### ISSUE TITLE
npm publish isn't including folders in package.json#files

### ISSUE THREAD

**Issue by mAAdhaTTah** [npm/npm#16146]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [X] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Attempting to publish my framework [brookjs](https://github.com/valtech-nyc/brookjs) to npm results in only the `src` dir being published, and not the `es` `cjs` or `dist` folders included in the `package.json` files key (also included in `.gitignore`, in case that's relevant). This doesn't appear to happen every time; eventually I'm able to publish a correct version after a few tries. `npm pack` also always appears to produce a correct tarball though. I'm using `prepublishOnly` to test everything and generate the distribution folders.

#### How can the CLI team reproduce the problem?

This seems to happen inconsistently. As you can see in the release tab, I had to publish a few times before it took.

### supporting information:

 - `npm -v` prints: ~4.1.2~ 4.4.4 (upgraded, republished, still getting same issue)
 - `node -v` prints: 7.7.3
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: OSX
 - Network issues: None

**Comment by mAAdhaTTah** [comment]
Update: For the last deploy, I deleted the es, cjs, & dist from the .gitignore (without committing) and ran `npm publish` and it worked correctly, so I suspect its related to the conflict between files & .gitignore.

**Comment by deblockt** [comment]
I have the same issue for https://github.com/deblockt/hal-rest-client project

**Comment by mAAdhaTTah** [comment]
@deblockt If it helps, I have been working around this by running `npm pack`, then manually checking what's in the tarball before running `npm publish <package-version>.tar.gz`.
