### ISSUE TITLE
Cannot delete package

### ISSUE THREAD

**Issue by girishdubey** [npm/npm#16151]
Cannot delete package:

> npm unpublish npm-packagetest --force

Error:

> npm WARN using --force I sure hope you know what you are doing.
> npm ERR! Windows_NT 10.0.14393
> npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\gd_don2999\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "unpublish" "npm-packagetest" "--force"
> npm ERR! node v6.10.0
> npm ERR! npm  v4.3.0
> npm ERR! code E500
> 
> npm ERR! Registry returned 500 for DELETE on https://registry.npmjs.org/npm-packagetest/-rev/6-8642b41eb81c71f5c743c53772557d6c
> npm ERR!
> npm ERR! If you need help, you may report this error at:
> npm ERR!     <https://github.com/npm/npm/issues>
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     C:\Users\gd_don2999\AppData\Roaming\npm-cache\_logs\2017-03-25T07_48_11_973Z-debug.log

**Comment by StarpTech** [comment]
Did you try `npm unpublish --force npm-packagetest`

**Comment by andmeics** [comment]
Because of the npmjs' policy

**Comment by KenanY** [comment]
@StarpTech The log indicates that they are already using the `--force` flag.

Also, @andmeics is right here. If you want to unpublish a package, you should email `support@npmjs.com`. There's nothing more we can do here.

**Comment by girishdubey** [comment]
Thanks you for suggestion.
Previously i had used "npm unpublish npm-packagetest --force".
but when i used "npm unpublish --force npm-packagetest" it work fine.

**Comment by StarpTech** [comment]
@KenanY this is what I meant ;)

**Comment by KenanY** [comment]
Honestly, I cannot believe that the order of the arguments makes any difference.
