### ISSUE TITLE
unble to install npm which newly i created

### ISSUE THREAD

**Issue by shantilal-narola** [npm/npm#16159]
https://www.npmjs.com/package/chat-demo
 this is link ok package which i have made but can't install in my another project.
i get this error:
/Users/c239/Documents/chat
└── chat-demo@1.0.0 

npm WARN enoent ENOENT: no such file or directory, open '/Users/c239/Documents/chat/package.json'
npm WARN chat No description
npm WARN chat No repository field.
npm WARN chat No README data
npm WARN chat No license field.

**Comment by KenanY** [comment]
@shantilal-narola Looks like the installation was successful, though?

**Comment by shantilal-narola** [comment]
i have done from other issue solution which is provided by you. 
Thanks
