### ISSUE TITLE
npm install stuck on still and after time get error

### ISSUE THREAD

**Issue by idanh003** [npm/npm#16153]
Hi,

im trying to do npm install npm@latest -g;
but its stuck on stiil and after some time is give me a error:
node version : 7.7.4
mpn version : 4.1.2

error:
 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "npm@latest" "-g"
 error node v7.7.4
 error npm  v4.1.2
 error Cannot read property 'path' of null
 error If you need help, you may report this error at:
 error     <https://github.com/npm/npm/issues>
 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@idanh003 Could you upload the resulting `npm-debug.log` file to <https://gist.github.com/> and post a link to it here?

**Comment by idanh003** [comment]
@KenanY https://gist.github.com/idanh003/e58144160ab2eb47a43b7a15465e3fc5 
thanks. i uninstall everything 2 times and its not working

**Comment by KenanY** [comment]
@idanh003 Thanks! The log indicates that your network connection to the registry is timing out. Are you behind a proxy or firewall by any chance?

**Comment by idanh003** [comment]
@KenanY i don't know what append its working prefect, and i did something with angularjs and the npm stop to working, and i uninstall everything.

**Comment by idanh003** [comment]
@KenanY i success to fix my problem with set npm config set proxy null
and now its working perfect. thanks for the help :)

**Comment by KenanY** [comment]
@idanh003 Happy to hear that!
