### ISSUE TITLE
Update NPM on NodeJS 7.7.4 crashes & leaves itself uninstalled

### ISSUE THREAD

**Issue by thany** [npm/npm#16160]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

After installing NodeJS 7.7.4, updating NPM breaks and leaves itself uninstalled.

#### How can the CLI team reproduce the problem?

1. Install NodeJS 7.7.4 on an Ubuntu-like system. In my case, WLS.
2. Execute `sudo npm install -g npm@latest` To update npm to the latest version.

This will be the result:

```
npm ERR! Linux 3.4.0+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "-g" "install" "npm@latest"
npm ERR! node v7.7.4
npm ERR! npm  v4.1.2
npm ERR! path /usr/lib/node_modules/.staging/init-package-json-8becc57f
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/usr/lib/node_modules/.staging/init-package-json-8becc57f' -> '/usr/lib/node_modules/npm/node_modules/init-package-json'
npm ERR! enoent ENOENT: no such file or directory, rename '/usr/lib/node_modules/.staging/init-package-json-8becc57f' -> '/usr/lib/node_modules/npm/node_modules/init-package-json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /home/martijn/npm-debug.log
./update: 16: ./update: npm: not found
```

Gist: [npm-debug.log](https://gist.github.com/thany/ec4ca03c8c9844478b08f5841e472a31)

### supporting information:

 - `npm -v` prints:
    Before update: `v4.1.2`
    After update: `The program 'npm' is currently not installed. You can install it by typing:
sudo apt-get install npm`
 - `node -v` prints: `v7.7.4`
 - `npm config get registry` prints: `The program 'npm' is currently not installed. You can install it by typing:
sudo apt-get install npm`
 - Windows, OS X/macOS, or Linux?: WLS (So, Linux, or Windows, both actually. Closer to Linux than to Windows)
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by grdunn** [comment]
@thany did you ever solve this?

**Comment by thany** [comment]
Doesn't seem to happen anymore in the latest versions. Too bad it got closed for no good reason - that's not really the way to solve a problem, to just ignore users and wish for a magical solution. But anyways, I'm not getting this problem anymore. It's magic for now. No idea what actually happened that got it fixed.
