### ISSUE TITLE
Excessive memory and cpu usage

### ISSUE THREAD

**Issue by Auxolust** [npm/npm#16165]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ x ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

NPM is using an excessively high amount of memory and cpu, about 45% CPU usage and over 550Mb memory

#### How can the CLI team reproduce the problem?
Try use npm install on a reasonably large package like webpack

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
What version of `npm` and `node` do you have (`npm -v` and `node -v`)?

**Comment by dandv** [comment]
I can reproduce this problem reliably with npm v4.2.0 and node v7.10.0 on a 512Mb Digital Ocean droplet (these are configured without swap) by running `npm install -g polymer-cli@next`.

CPU usage peaked around 90%, and when available RAM reached zero, I would see something like

```
# npm install -g polymer-cli@next
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
[             .....] - extract:detect-conflict: sill gunzTarPerm extractEntry test/neg-vs-pos-0.js







[I pressed Enter here]



Killed
```

```
# npm install -g polymer-cli@next
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
Killed        .....] / extract:camel-case: sill gunzTarPerm modified mode [ 'test/cpu-test.json', 436, 420 ]
```

I had to add a 1GB swap file to work around the inability to install polymer.
