### ISSUE TITLE
node-gyp rebuild failure

### ISSUE THREAD

**Issue by downzer0** [npm/npm#16167]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

All of a sudden when I run `npm install` to update my local packages, I get consistent failures in the `node-gyp rebuild` step.

#### How can the CLI team reproduce the problem?

I am using NVM with Node version 6.10.1 (LTS/boron) and NPM version 3.10.10.
[Gist with console output](https://gist.github.com/downzer0/e2e3b306ce9b02361cef555ccea009ac)
NPM error log (none)

I pushed an update to a remote branch to pull down in another terminal window. When I run `npm install` in that new window to pull down the updates, the error is generated. Additionally, `npm install` fails every time in other projects.

I have tried downgrading Node to 4.6.2 and upgrading to 7.7.4 (the appropriate NPM versions come with it, along with the NPM-bundled `node-gyp`).

I have tried upgrading `node-gyp` using [these upgrade instructions](https://github.com/nodejs/node-gyp/wiki/Updating-npm's-bundled-node-gyp) but it doesn't work. I get an "invalid" next to the "latest" version.

### supporting information:

 - `npm -v` prints: 3.10.10
 - `node -v` prints: 6.10.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Mac
 - Network issues:
   - Geographic location where npm was run: US
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
Please go through the [troubleshooting guide](https://github.com/npm/npm/wiki/Troubleshooting).

**Comment by downzer0** [comment]
Turns out not to be an issue with NPM, but a dependency I had that was shrinkwrapped using an older version of `weak`. It appears that that specific version of `weak` had conflicts with `node-gyp`. I forced the shrinkwrap to use the newest version of `weak` and that cleared it up.

The shrinkwrap was using `weak@0.3.4` and I was trying various newer versions of Node/NPM.
