### ISSUE TITLE
Not able to install calendar picker

### ISSUE THREAD

**Issue by rahul-10** [npm/npm#16169]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  -  npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### Error message is -

npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/Cellar/node/7.2.0/bin/node" "/usr/local/bin/npm" "install" "--save" "react-native-calendar-picker"
npm ERR! node v7.2.0
npm ERR! npm  v3.10.9

npm ERR! shasum check failed for /var/folders/ss/tdvj3p5x13l5ckdmm6qdv54r0000gn/T/npm-7913-9f8d56d1/registry.npmjs.org/react-native-calendar-picker/-/react-native-calendar-picker-5.7.0.tgz
npm ERR! Expected: 4a12bf20540081c4457935d76ada158a4b6ee487
npm ERR! Actual:   b34f4a3ecc4d168df089d3486bf0d217cc318fdd
npm ERR! From:     https://registry.npmjs.org/react-native-calendar-picker/-/react-native-calendar-picker-5.7.0.tgz

**Comment by KenanY** [comment]
@rahul-10 Could you see if this occurs with the latest stable version of `npm`?
