### ISSUE TITLE
npm install [ npm ERR! cb() never called! ]

### ISSUE THREAD

**Issue by LeonardoBluesMan** [npm/npm#16174]
Hi

I'm trying to install primefaces/primeng source (https://github.com/primefaces/primeng) and, as described under "Building From Source" section (https://github.com/primefaces/primeng/wiki/Building-From-Source) I followed exactly the same steps without success.

I've been searching and found similar issue:
https://github.com/npm/npm/issues/15395

And also tried this post
http://www.alex-arriaga.com/issue-when-running-npm-install-npm-err-cb-never-called-solved/

#### How can the CLI team reproduce the problem?
just download or clone the primefaces/primeng source code and type npm install

### supporting information:

 - `npm -v` prints:
4.4.4
 - `node -v` prints:
v6.10.0
 - `npm config get registry` prints:
https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?:
Windows 10, x64

proxy settings was configured with 
>npm config set proxy http://xxxx:yyy 
>npm config set https-proxy http://xxxx:yyy
and no issues installing other angular applications

 - Network issues:
   - Geographic location where npm was run:
   - [ X] I use a proxy to connect to the npm registry.
   - [ X] I use a proxy to connect to the web.
   - [ X] I use a proxy when downloading Git repos.

**Comment by cristiangsp** [comment]
Same thing here. I get the following error when doing npm install.

```bash
&> npm install
npm ERR! cb() never called!
```

**Comment by cbxp** [comment]
Same here. On a project where it worked fine about 6 hours ago. package.json hasn't changed, node and npm versions have not changed. Update of npm to latest version still gives the same result. 
```
$ npm install 
npm ERR! cb() never called!
```
Looks like some dependency has gone bad and it crashes npm. 
Attached is my debug log.
[2017-03-28T12_09_15_591Z-debug.log.txt](https://github.com/npm/npm/files/875572/2017-03-28T12_09_15_591Z-debug.log.txt)

**Comment by shengjie-chez-agriconomie** [comment]
see: https://github.com/rezzza/gulp-uglifycss/issues/15

**Comment by stueybrock** [comment]
Seems like the issue is with uglifycss – have commented out this package for now and gulp is back and up and running.

**Comment by cbxp** [comment]
The problem is with gulp-uglifycss 1.0.7. If you fix your version to 1.0.6 then everything works fine.

**Comment by LeonardoBluesMan** [comment]
now it works
Thanks!

**Comment by GitzJoey** [comment]
I cant find any gulp-uglifycss
can some one provide me with the step to downgrade it?
