### ISSUE TITLE
webpack

### ISSUE THREAD

**Issue by forsakesoul** [npm/npm#16171]
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save-dev" "webpack"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ENOSELF

npm ERR! Refusing to install webpack as a dependency of itself
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/xxx/Desktop/webpack-pra/npm-debug.log

thanks

**Comment by KenanY** [comment]
@forsakesoul Hello! Please make sure that the `"name"` field in your `package.json` is not set to the same name as any of your dependencies, like `"webpack"`. Make it more unique!
