### ISSUE TITLE
Issue with install JS

### ISSUE THREAD

**Issue by K1lleR8** [npm/npm#16175]
I have this issue when i will install discord.js
`
C:\Users\K1lleR8>npm install ./discord.js-indev-prism
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "./discord.js-indev-prism"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10

npm ERR! 4 == 0
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "./discord.js-indev-prism"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10

npm ERR! 4 == 0
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "./discord.js-indev-prism"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10

npm ERR! 4 == 0
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "./discord.js-indev-prism"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10

npm ERR! 4 == 0
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "./discord.js-indev-prism"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10

npm ERR! 4 == 0
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "./discord.js-indev-prism"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10

npm ERR! 4 == 0
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
`

**Comment by KenanY** [comment]
@K1lleR8 Could you provide some steps to reproduce this? Is `./discord.js-indev-prism` a directory in your current directory?

**Comment by K1lleR8** [comment]
yes its in root
i'll install discord.js

**Comment by KenanY** [comment]
@K1lleR8 Just to make sure this isn't something that's been fixed already, can you try [updating](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) to the latest stable release?

**Comment by K1lleR8** [comment]
I think its last stable version
v6.10.1 true?

**Comment by KenanY** [comment]
@K1lleR8 I mean the `npm` version :)

**Comment by K1lleR8** [comment]
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Users\K1lleR8>npm install npm@latest -g
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "npm@latest" "-g"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10

npm ERR! 4 == 0
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
