### ISSUE TITLE
unpublish considered harmful, why is it allowed?

### ISSUE THREAD

**Issue by gigafied** [npm/npm#16178]
Several versions of the `uws` module were unpublished, well after the 24 hour window:

https://github.com/uWebSockets/uWebSockets/issues/551

Going by the docs, in `unpublish`, this should not be allowed: https://docs.npmjs.com/cli/unpublish

And yet, several versions were allowed to be unpublished. Is there a reason for this? Perhaps because they were 0.x.y versions? I would seriously consider disallowing `unpublish` even on major version 0.

**Comment by ctnordcl** [comment]
I like the idea of restricting actions that could be considered a breaking change. Refer to the entire left-pad scenario.

https://www.theregister.co.uk/2016/03/23/npm_left_pad_chaos/

**Comment by legodude17** [comment]
If it was after the 24 hour window, it should have failed and required them to contact npm support.

**Comment by gigafied** [comment]
@legodude17 should have but didn't.

**Comment by gigafied** [comment]
@ceejbot @seldo can we get somebody from NPM to chime in here?

**Comment by seldo** [comment]
The ability to unpublish outside of the allowed window was a bug created by an architectural migration in the registry. It is now fixed. Our apologies. It is always a very bad idea to unpublish things that have been around for more than 24 hours, which is why we don't allow it except, as in this case, unintentionally.

**Comment by martinzwirner** [comment]
Is it possible to restore the unpublished versions (that should not have been unpublished)? That would make things easier for us.

**Comment by seldo** [comment]
If you send a support request to support@npmjs.com listing the specific versions, this *may* be possible. Our support load is very high right now because of the recent launch of free Orgs, so please be patient if it takes a while to act on this.
