### ISSUE TITLE
after  install node modle, it toke wrong when i npm run dev. that's why? 

### ISSUE THREAD

**Issue by huanggl8** [npm/npm#16170]
okidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)

C:\Users\Administrator\Desktop\vue\jackblog-vue-master\src>npm run dev
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10

npm ERR! missing script: dev
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Administrator\Desktop\vue\jackblog-vue-master\src\npm-debu
g.log

**Comment by huanggl8** [comment]
thanks

**Comment by KenanY** [comment]
Hello! So, the way `npm run dev` works is that it looks in your current `package.json` for a defined `"dev"` [script](https://docs.npmjs.com/misc/scripts), and then runs that. The error message you're seeing is trying to tell you that you have not defined a `"dev"` script in your `package.json`, hence `npm run dev` has no idea what you want it to do.

To solve this issue, all you have to do is add a new script to your `package.json`. It might look something like this, for example:

``` json
{
  "name": "package-name",
  "version": "1.0.0",
  "description": "package description",
  "scripts": {
    "dev": "node dev-server.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {},
  "devDependencies": {}
}
```

Note how this `package.json` has a `"dev"` script that runs `node dev-server.js`. You'll definitely want to change the command to whatever is most appropriate for your project.

Let me know if you run into any further `npm` issues :)
