### ISSUE TITLE
Cannot find module 'github-url-from-git'

### ISSUE THREAD

**Issue by gfalquet** [npm/npm#16177]
#### I'm opening this issue because:

  - [ x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

$ npm update
npm ERR! Darwin 14.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "update"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'github-url-from-git'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'update' ]
2 info using npm@3.10.10
3 info using node@v6.10.1
4 verbose config Skipping project config: /Users/falquet/.npmrc. (matches userconfig)
5 verbose stack Error: Cannot find module 'github-url-from-git'
5 verbose stack     at Function.Module._resolveFilename (module.js:469:15)
5 verbose stack     at Function.Module._load (module.js:417:25)
5 verbose stack     at Module.require (module.js:497:17)
5 verbose stack     at require (internal/module.js:20:19)
5 verbose stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:2:22)
5 verbose stack     at Module._compile (module.js:570:32)
5 verbose stack     at Object.Module._extensions..js (module.js:579:10)
5 verbose stack     at Module.load (module.js:487:32)
5 verbose stack     at tryModuleLoad (module.js:446:12)
5 verbose stack     at Function.Module._load (module.js:438:3)
6 verbose cwd /Users/falquet
7 error Darwin 14.4.0
8 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "update"
9 error node v6.10.1
10 error npm  v3.10.10
11 error code MODULE_NOT_FOUND
12 error Cannot find module 'github-url-from-git'
13 error If you need help, you may report this error at:
13 error     <https://github.com/npm/npm/issues>
14 verbose exit [ 1, true ]

#### How can the CLI team reproduce the problem?

Install node v6.10.1 on MacOSX 10.10.4

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@gfalquet Looks like a busted install to me. Could you try [reinstalling](https://github.com/npm/npm/wiki/Troubleshooting#if-your-npm-is-broken)?

**Comment by clbanning** [comment]
node -v                           : v6.10.2
npm -v                            : 3.10.10
npm config get registry : https://registry.npmjs.org/

**Comment by legodude17** [comment]
@clbanning did you try what @KenanY said?

**Comment by clbanning** [comment]
Yes.  Resolved this by cleaning out all node and npm /usr/local (bin, lib, include) node content and reinstalling using Homebrew - it has better error messaging to let you fix directory permissions, etc., if it errors.
