### ISSUE TITLE
Create greatest npm utility ever

### ISSUE THREAD

**Issue by ORESoftware** [npm/npm#16179]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's the feature?

I am looking for utility which will cd me into my project root:

```bash
function npm_goto_project_root(){
   cd $(npm root);
   cd ..;
}
```

this would be such an awesome feature.

The `npm root `command can find the `node_modules` directory; for 99.999% of projects, node_modules is directly within the project root - so if NPM knows where node_modules is, it almost always can find your project root.

I currently know of no fast way to `cd` to my project's root.

NPM can provide its users with a single command to `cd` to the project root.

The only way I know of doing this is using a bash alias or bash function.

The above example will work.

Let me know what you think. thanks!

Of course, it would be good to shorten the command name:

```bash
function npm_proj{
   cd $(npm root);
   cd ..;
}
```

or something like that

**Comment by naterkane** [comment]
@ORESoftware if you can assume that your project root is the same as your git project root, you can just do this. add it to your shell profile or .bashrc file as an alias or something. 
```
cd `git rev-parse --show-toplevel`
```

**Comment by ORESoftware** [comment]
the idea is when you are 4 directories drilled into your project, you should be able to issue a 4 character command to cd to the project root.

**Comment by ORESoftware** [comment]
```npm cd```

would work for me

**Comment by naterkane** [comment]
"add it to your shell profile or .bashrc file as an alias or something."

This isn't an npm related issue.

https://www.google.com/search?q=how+to+create+a+bash+alias&oq=how+do+i+create+a+bash+alias

**Comment by ORESoftware** [comment]
this is a feature request, not an issue. NPM would save all NPM users the trouble of using there own alias.

**Comment by ORESoftware** [comment]
but nevermind, I think there's no way for NPM to do this without a Bash alias or function, so you're right
