### ISSUE TITLE
NPM Start - Missing Script "Start"

### ISSUE THREAD

**Issue by foxandarrows** [npm/npm#16173]
Hello Everybody,

I'm new to Github, Node and NPM
I try to "start" npm through the terminal in order to link my local development space with a squarespace server

I install and uninstall Node & NPM several times
I read a lot of documentation but I can't solve the problem
Here is the .log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@4.1.2
3 info using node@v7.7.4
4 verbose stack Error: missing script: start
4 verbose stack     at run (/usr/local/lib/node_modules/npm/lib/run-script.js:151:19)
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/run-script.js:61:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:356:5
4 verbose stack     at checkBinReferences_ (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:320:45)
4 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:354:3)
4 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:124:5)
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:311:12
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
4 verbose stack     at tryToString (fs.js:449:3)
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:436:12)
5 verbose cwd /Users/lunalitvak/template
6 error Darwin 15.6.0
7 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
8 error node v7.7.4
9 error npm  v4.1.2
10 error missing script: start
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
 
Thank you in advance for your help !

Cheers,
Luna

**Comment by KenanY** [comment]
@foxandarrows Hello! So, the way `npm start` works is that it looks in your current `package.json` for a defined `"start"` [script](https://docs.npmjs.com/misc/scripts), and then runs that. The error message you're seeing is trying to tell you that you have not defined a `"start"` script in your `package.json`, hence `npm start` has no idea what you want it to do.

To solve this issue, all you have to do is add a new script to your `package.json`. It might look something like this, for example:

``` json
{
  "name": "package-name",
  "version": "1.0.0",
  "description": "package description",
  "scripts": {
    "start": "node lib/server.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {},
  "devDependencies": {}
}
```

Note how this `package.json` has a `"start"` script that runs `node lib/server.js`. You'll definitely want to change the command to whatever is most appropriate for your project.

Let me know if you run into any further `npm` issues :)

**Comment by foxandarrows** [comment]
@KenanY 

Thank you a lot for your clear explanations !

The thing is that I simply wanted to install node and npm and I followed the exact instructions
I read that when you install node & npm, you don't need to mention a "start" point
But apparently, yes !

The problem is that I have absolutely no idea about which file I have to mention as a starting point. Indeed, I don't know what node/npm needs in order to work properly

I know it's not easy if you don't see the code and previous installation but if you have any idea, don't hesitate

Thank you already for your help ! 

Cheers,
Luna

**Comment by KenanY** [comment]
@foxandarrows Yeah, unfortunately you're right that it's extremely difficult for me to "guess" what your `"start"` script should be since there are close to infinite possible scripts. If you're taken the code from an existing project or tutorial, then maybe the authors could help you out. Good luck!

**Comment by ShadamHarizky** [comment]
Hallo mr kenan
I also experienced something like this, but I do not have a file server.js

**Comment by KenanY** [comment]
@ShadamHarizky That file is just an example I made up, so no worries if you don't have it. You just gotta configure that example `"start"` script provided and you should be good to go. Good luck!

**Comment by anilbhutia** [comment]
**khhhkjhk**

**Comment by serdarpolat** [comment]
I changed the package.json like this:
`{
  "name": "FirstProject",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "start": "node node_modules/hawk/lib/server.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "devDependencies": {
    "react-native-scripts": "1.8.1"
  }
}`

Response :
`> FirstProject@0.1.0 start C:\React\FirstProject
> node node_modules/hawk/lib/server.js`

**Comment by Dalin9Chen** [comment]
some of the npm versions have the issue, some of them don't, I just solved it by changing my npm version:
npm install -g npm@4.6.1
npm install -g create-react-native-app
create-react-native-app myProj

**Comment by Benpou** [comment]
I had same issue and this is a part that I miss (kind of funny): 
Make sure that you save your `package.json` file and then run the code which is `npm start`

**Comment by 8Ozymandias** [comment]
@KenanY I tried what you provided but it doesn't work.

**Comment by kenany** [comment]
@8Ozymandias Please open a new ticket. Make sure to provide a debug log and your `package.json`. Thanks!

**Comment by ericytex** [comment]
Thanks a lot, this helped @KenanY
