### ISSUE TITLE
Getting a 404 for a private module that I see in my profile

### ISSUE THREAD

**Issue by dancrumb** [npm/npm#16180]
#### I'm opening this issue because:
  - [ ] npm is producing an incorrect install.

#### What's going wrong?

When I try to install `@jellyvision/talentshow-view`, I get:

```
npm ERR! Darwin 16.5.0
npm ERR! argv "/Users/danrumney/.nvm/versions/node/v6.9.1/bin/node" "/Users/danrumney/.nvm/versions/node/v6.9.1/bin/npm" "i" "@jellyvision/talentshow-view"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code E404

npm ERR! 404 Not found : @jellyvision/talentshow-view
npm ERR! 404 
npm ERR! 404  '@jellyvision/talentshow-view' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/danrumney/WebstormProjects/parabola/npm-debug.log
```

When I visit https://www.npmjs.com/~dancrumb, I can see that package listed. However, when I click the link to https://www.npmjs.com/package/@jellyvision/talentshow-view, I get a 404 error... wut?

#### How can the CLI team reproduce the problem?

Simple... be me and then execute `npm i @jellyvision/talentshow-view`

debug log at https://gist.github.com/dancrumb/0af0ee18dda7a38bddd9857f7f9c7bb6
### supporting information:

 - `npm -v` prints: 3.10.8
 - `node -v` prints:v6.9.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS
 - Network issues:
   - Geographic location where npm was run: US

**Comment by dancrumb** [comment]
Turns out I can access (among others), https://www.npmjs.com/package/@jellyvision/loa-reference-page

So, I can access *some* of the packages in this org, but not others... is there some finer-grained authorization at play here?

**Comment by prijuly2000** [comment]
i am having kind of same problem !! Any solution for this ?
