### ISSUE TITLE
Installing “react@0.16.2” failed.Hide { atom editor }

### ISSUE THREAD

**Issue by Doufeni** [npm/npm#16187]
Installing “react@0.16.2” failed.Hide output…

npm ERR! git clone C:\Users\SaifAllah.Doufani\.atom\.apm\_git-remotes\git-https-github-com-millermedeiros-rocambole-git-1bd5044df1d6c888a1bd1b511158fb34b011e9aa-af4fdf85 C:\Users\SAIFAL~1.DOU\AppData\Local\Temp\npm-6724-8288c66d\git-cache-d09819b2\1bd5044df1d6c888a1bd1b511158fb34b011e9aa: Cloning into 'C:\Users\SAIFAL~1.DOU\AppData\Local\Temp\npm-6724-8288c66d\git-cache-d09819b2\1bd5044df1d6c888a1bd1b511158fb34b011e9aa'...
npm ERR! git clone C:\Users\SaifAllah.Doufani\.atom\.apm\_git-remotes\git-https-github-com-millermedeiros-rocambole-git-1bd5044df1d6c888a1bd1b511158fb34b011e9aa-af4fdf85 C:\Users\SAIFAL~1.DOU\AppData\Local\Temp\npm-6724-8288c66d\git-cache-d09819b2\1bd5044df1d6c888a1bd1b511158fb34b011e9aa: error: cannot spawn sh: No such file or directory
npm ERR! git clone C:\Users\SaifAllah.Doufani\.atom\.apm\_git-remotes\git-https-github-com-millermedeiros-rocambole-git-1bd5044df1d6c888a1bd1b511158fb34b011e9aa-af4fdf85 C:\Users\SAIFAL~1.DOU\AppData\Local\Temp\npm-6724-8288c66d\git-cache-d09819b2\1bd5044df1d6c888a1bd1b511158fb34b011e9aa: fatal: unable to fork
npm ERR! git clone C:\Users\SaifAllah.Doufani\.atom\.apm\_git-remotes\git-https-github-com-millermedeiros-rocambole-git-1bd5044df1d6c888a1bd1b511158fb34b011e9aa-af4fdf85 C:\Users\SAIFAL~1.DOU\AppData\Local\Temp\npm-6724-8288c66d\git-cache-d09819b2\1bd5044df1d6c888a1bd1b511158fb34b011e9aa: 
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\SaifAllah.Doufani\\AppData\\Local\\atom\\app-1.15.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\SaifAllah.Doufani\\AppData\\Local\\atom\\app-1.15.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\SaifAllah.Doufani\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\SaifAllah.Doufani\\.atom\\.apmrc" "install" "C:\\Users\\SAIFAL~1.DOU\\AppData\\Local\\Temp\\d-117229-4704-m1ngkx\\package.tgz" "--runtime=electron" "--target=1.3.13" "--arch=x64" "--global-style" "--msvs_version=2015"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone C:\Users\SaifAllah.Doufani\.atom\.apm\_git-remotes\git-https-github-com-millermedeiros-rocambole-git-1bd5044df1d6c888a1bd1b511158fb34b011e9aa-af4fdf85 C:\Users\SAIFAL~1.DOU\AppData\Local\Temp\npm-6724-8288c66d\git-cache-d09819b2\1bd5044df1d6c888a1bd1b511158fb34b011e9aa
npm ERR! Cloning into 'C:\Users\SAIFAL~1.DOU\AppData\Local\Temp\npm-6724-8288c66d\git-cache-d09819b2\1bd5044df1d6c888a1bd1b511158fb34b011e9aa'...
npm ERR! error: cannot spawn sh: No such file or directory
npm ERR! fatal: unable to fork

**Comment by legodude17** [comment]
Do you have an `sh` somewhere on your system?
