### ISSUE TITLE
getting an error saying "Cannot find module 'detect-newline'" yet I don't use it my project 

### ISSUE THREAD

**Issue by tamirUtab** [npm/npm#16189]
I'm opening this issue because:

  - [x] npm is doing something I don't understand.

What's going wrong?

cannot pass jenkins tests. 

The error is the same cannot find module '...' modules that I don't use and if I install them it just happens again with a different one.   

How can the CLI team reproduce the problem?

Any clue about what is going on would help tremendously.. 

### supporting information:

 - npm -v- 2.15.0:
 - node -v- 4.4.2:
 - `npm config get registry` prints:
 Linux
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.

 - Container:
   - [ ] I develop using Vagrant on OS X or Linux.

    Thank you for contributing to npm! Please review this checklist
    before submitting your issue.

**Comment by legodude17** [comment]
Try updating `npm` to the latest version.

**Comment by tamirUtab** [comment]
Thank's @legodude17 apparently I don't have sufficient privileges to update  @gulp-sourcemaps/map-sources : @gulp-sourcemaps/map-sources 

12770 error Darwin 14.5.0
12771 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "update"
12772 error node v4.4.2
12773 error npm  v2.15.0
12774 error code E403
12775 error user developers is not allowed to access package @gulp-sourcemaps/map-sources : @gulp-sourcemaps/map-sources
12776 error If you need help, you may report this error at:
12776 error     <https://github.com/npm/npm/issues>
12777 verbose exit [ 1, true ]
12778 verbose unbuild node_modules/gulp-sourcemaps
12779 info preuninstall gulp-sourcemaps@2.5.0
12780 info uninstall gulp-sourcemaps@2.5.0
12781 verbose unbuild rmStuff gulp-sourcemaps@2.5.0 from /Users/tamirshina/WebstormProjects/firstTimeInWebstorm/ytf-musichords/node_modules
12782 info postuninstall gulp-sourcemaps@2.5.0
12783 silly gentlyRm /Users/tamirshina/WebstormProjects/firstTimeInWebstorm/ytf-musichords/node_modules/gulp-sourcemaps is being purged from base /Users/tamirshina/WebstormProjects/firstTimeInWebstorm/ytf-musichords
12784 verbose gentlyRm don't care about contents; nuking /Users/tamirshina/WebstormProjects/firstTimeInWebstorm/ytf-musichords/node_modules/gulp-sourcemaps
12785 silly vacuum-fs purging /Users/tamirshina/WebstormProjects/firstTimeInWebstorm/ytf-musichords/node_modules/gulp-sourcemaps
12786 silly vacuum-fs quitting because other entries in /Users/tamirshina/WebstormProjects/firstTimeInWebstorm/ytf-musichords/node_modules
 
would you agree ?

**Comment by legodude17** [comment]
No, you need to run `npm install -g npm@latest`.

**Comment by tamirUtab** [comment]
Similar errors still-

Error: Cannot find module 'detect-newline'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/var/lib/jenkins/workspace/musicmarkers/public/node_modules/vinyl-fs/node_modules/gulp-sourcemaps/src/utils.js:3:19)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
npm WARN optional dep failed, continuing imagemin-gifsicle@4.2.0

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "update"
npm ERR! node v4.4.2
npm ERR! npm  v2.15.0
npm ERR! code E403

npm ERR! user developers is not allowed to access package @gulp-sourcemaps/map-sources : @gulp-sourcemaps/map-sources
npm ERR!

**Comment by legodude17** [comment]
You need to run `npm install -g npm@latest`.

**Comment by tamirUtab** [comment]
unfortunately it doesn't help... same error.


> gifsicle@3.0.4 postinstall /var/lib/jenkins/workspace/musichords/public/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle
> node lib/install.js

module.js:338
    throw err;
          ^
Error: Cannot find module '@gulp-sourcemaps/map-sources'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/var/lib/jenkins/workspace/musichords/public/node_modules/vinyl-fs/node_modules/gulp-sourcemaps/index.js:6:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
npm WARN optional dep failed, continuing imagemin-optipng@4.3.0
npm WARN optional dep failed, continuing imagemin-gifsicle@4.2.0
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJS_0.12.9/bin/node" "/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJS_0.12.9/bin/npm" "install"
npm ERR! node v0.12.9
npm ERR! npm  v2.14.9
npm ERR! code E403

npm ERR! user developers is not allowed to access package @gulp-sourcemaps/map-sources : @gulp-sourcemaps/map-sources
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /var/lib/jenkins/workspace/musichords/public/npm-debug.log

**Comment by legodude17** [comment]
You missed the `-g npm@latest` and just ran `npm install`. Run `npm install -g npm@latest`.

**Comment by marcoarruda** [comment]
The command `npm install -g npm@latest` solved this error for me, but I got new errors.
Everything were fixed updating also node.js version:

`sudo npm cache clean -f`
`sudo npm install -g n`
`sudo n stable`

Important to notice that you need to reopen your terminal (check the versions using `npm -v` and `node -v`)

Thanks!
