### ISSUE TITLE
all npm package install fail - request.Request is not a constructor

### ISSUE THREAD

**Issue by SisirPanda** [npm/npm#16191]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [X ] Other (_see below for feature requests_):

#### What's going wrong?
when i install any npm package it fails with " npm ERR! request.Request is not a constructor"
#### How can the CLI team reproduce the problem?

when i run any npm install --save  to package it errors with on windows 7 from 
 npm ERR! request.Request is not a constructor
I had in past been able to install npm package but not since last evening.

see the details below in the link
https://gist.github.com/SisirPanda/f17333ad77a17f476d1a0a3a100bbfc2
see the verbose error log
https://gist.github.com/SisirPanda/37a247a05c4a1291119dba6a57848433

### supporting information:

 - `npm -v` prints: 3.10.10
 - `node -v` prints: v6.10.0
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?: Windows 7 
 - Network issues: Running npm install from office desktop
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [X] I use a proxy to connect to the web.
   - [X ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
This looks like a busted `npm` installation. Try reinstalling.

**Comment by SisirPanda** [comment]
npm install - reinstall -g fails with same error

C:\Sp325\NP>npm install reinstall -g
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "reinstall" "-g"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10

npm ERR! request.Request is not a constructor
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by SisirPanda** [comment]
reintalled all and it fixed..
thanks for looking at it.
