### ISSUE TITLE
support - npm install from local project

### ISSUE THREAD

**Issue by ORESoftware** [npm/npm#16190]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?

I am aware of NPM link, and love that feature. What I am wondering is - can we `npm install` from a local project?

The problem with `npm link` is that it doesn't run the postinstall script in the right location, as far as I know. It just runs the postinstall script in the current project.

But when you call `npm link x`, from project y, project y does not get the "full NPM postinstall experience" for x. Whereas if you did `npm install x`, then you would get that.

In that way

`npm link x  !== npm install x`

I assume you can't npm install a project that's defined locally? Would be a nice feature.

**Comment by legodude17** [comment]
I am pretty sure you can `npm install` a directory, but it will copy instead of linking.

**Comment by ORESoftware** [comment]
cool, do you know if this is documented anywhere? I didn't see it. Copy is what I would expected.

**Comment by legodude17** [comment]
I think that would be in https://docs.npmjs.com/cli/install

**Comment by ORESoftware** [comment]
you're right, it would be 

`npm install <folder>`

where folder just contains a package.json file somewhere in the local filesystem...
thanks!
