### ISSUE TITLE
Granting read-only access to a brand new package seams not to be working

### ISSUE THREAD

**Issue by jagu-sayan** [npm/npm#16199]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Problem with access management. When I grant `read-only` access to my brand new package for `@myorganisation`, granted users can't install the package, they got a 404 error.

The problem is on `npm` cli and the web interface. After having granted `read-only` access, I can see it in the web interface, but the granting access doesn't work (and failed silently). 

**Workaround**: Grant `read-write` access first and then right after, grant `read-only` access. 

#### How can the CLI team reproduce the problem?
When I do `npm access grant read-only my_org:my_group my-package`, `my_group` can't install `my-package`

```
➜  my-project git:(master) ✗ npm install @my_org/my-package
npm ERR! code E404
npm ERR! 404 Not found : @my_org/my-package
npm ERR! 404
npm ERR! 404  '@my_org/my-package' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/yves/.npm/_logs/2017-03-29T16_41_52_522Z-debug.log
```

Maybe related to https://github.com/npm/npm/issues/15667 ?

**Comment by yvele** [comment]
Same problem using private packages
