### ISSUE TITLE
the reason is my the proxy of 80 occupied ?

### ISSUE THREAD

**Issue by j512581813** [npm/npm#16197]
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "update" "-g"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ECONNRESET

npm ERR! network tunneling socket could not be established, cause=getaddrinfo ENOTFOUND proxy-domain.com proxy-domain.com:8080
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     D:\xampp\htdocs\vue-cart-es6\npm-debug.log

**Comment by KenanY** [comment]
@j512581813 Have you properly configured `npm` to use your proxy? [This guide](https://jjasonclark.com/how-to-setup-node-behind-web-proxy/) may help.

**Comment by KenanY** [comment]
Closing due to no reply after a month.
