### ISSUE TITLE
The unpublish problem

### ISSUE THREAD

**Issue by Harveytwo** [npm/npm#16196]
I want to delete the npm modules that I published. But when I run npm unpublish modulesName, there are somethings error. And response that Registry returned 400 for DELETE on https://registry.npmjs.org/npm-publish-harvey/-rev/7-9d1546a445dd3919c5b05782813c54f0 . So if I want to delete the npm modules I publish, how should I do.

**Comment by KenanY** [comment]
@Harveytwo Please contact `support@npmjs.com`, they can unpublish the package for you.
