### ISSUE TITLE
Running npm update fails when called from a bash script

### ISSUE THREAD

**Issue by thany** [npm/npm#16193]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

When running `npm update -g` from a bash script fails with a friendly error message:
```
Please try running this command again as root/Administrator.
```
However, said bash script *is* being run as root. *Even* when the `update.sh` script looks like this:
```
sudo npm update -g
```
It still fails when calling it, with or without sudo. It even fails when logged in as the *actual* root user (but then, sans the sudo prefix).

#### How can the CLI team reproduce the problem?

Create a script file called `update.sh` and give it execute permission.
Put this in it:
```
npm update -g
```
Now call it:
```
$ sudo ./update.sh
```
It will fail with an error much like this:
```
npm ERR! path /usr/local/lib/node_modules/.staging/npm-3e479054/node_modules/readdir-scoped-modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall rename
npm ERR! Error: EACCES: permission denied, rename '/usr/local/lib/node_modules/.staging/npm-3e479054/node_modules/readdir-scoped-modules' -> '/usr/local/lib/node_modules/.staging/readdir-scoped-modules-f855e873'
npm ERR!  { Error: EACCES: permission denied, rename '/usr/local/lib/node_modules/.staging/npm-3e479054/node_modules/readdir-scoped-modules' -> '/usr/local/lib/node_modules/.staging/readdir-scoped-modules-f855e873'
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'rename',
npm ERR!   path: '/usr/local/lib/node_modules/.staging/npm-3e479054/node_modules/readdir-scoped-modules',
npm ERR!   dest: '/usr/local/lib/node_modules/.staging/readdir-scoped-modules-f855e873' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/martijn/.npm/_logs/2017-03-29T21_49_04_491Z-debug.log
```

However, after a few tries, it might suddenly work. I don't understand yet why or when it suddenly works, but it does. And then after, when there's an update yet again, it'll fail again. And this is all in one and the same terminal session.

### supporting information:

 - `npm -v` prints: 4.4.4
 - `node -v` prints: 7.8.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by naterkane** [comment]
your issue has nothing to do with running npm from a shell script... though you didn't specify that you had `#!/bin/bash` _(or whatever shell you're using)_ as the first line of the script as you should.

your have a permissions problem, read this. [https://docs.npmjs.com/getting-started/fixing-npm-permissions](https://docs.npmjs.com/getting-started/fixing-npm-permissions)

**Comment by thany** [comment]
It does, running the same commands separately from the shell, not in a script, makes them work fine. Just by putting them in a script makes them error like above.

I don't have `#!/bin/bash` in my script. It's not neccesary. When I run a script from the bash shell (this I did specify), a script will not magically fire up an arbitrarily different shell. In other words, it'll run on the shell it's started from.
