### ISSUE TITLE
Web interface for creating packages

### ISSUE THREAD

**Issue by photopea** [npm/npm#16194]
#### What's the feature?
Web interface for creating packages.

#### What problem is the feature intended to solve?
I made several JS libraries (for browsers, I never used Node.js) and my users ask me to publish them at NPM. Publishing them through the browser would save a lot of my time (I don't want to install native programs and learn to use command-line apps just for this purpose).

#### Is the absence of this feature blocking you or your team? If so, how?
It seems like some of my users find it hard to download and store JS file manually.

#### Is this feature similar to an existing feature in another tool?
Yes, GitHub has a web interface for updating repositories.

#### Is this a feature you're prepared to implement, with support from the npm CLI team?
Probably not

**Comment by KenanY** [comment]
This should probably be taken to <https://github.com/npm/www>.

**Comment by KenanY** [comment]
Closing due to no reply after a month.

**Comment by photopea** [comment]
Sadly, they are not as active as you are :(  https://github.com/npm/www/issues/173
