### ISSUE TITLE
Please help me

### ISSUE THREAD

**Issue by kfzly** [npm/npm#16207]
[npm-debug.zip](https://github.com/npm/npm/files/884261/npm-debug.zip)
Who can help me,Thanks!

**Comment by KenanY** [comment]
@kfzly Could you upload the debug log as plaintext to <https://gist.github.com/> instead of zipping it up?

**Comment by kfzly** [comment]
@KenanY  OK,Thanks
<script src="https://gist.github.com/kfzly/6bc8c113a88028a7840f942690485861.js"></script>

**Comment by KenanY** [comment]
@kfzly Thanks. The error message seems to say that your system has run out of memory; is this a system with a low amount of RAM by any chance?

**Comment by kfzly** [comment]
only ram? @KenanY

**Comment by KenanY** [comment]
@kfzly That's the only culprit I see, yes.

**Comment by kfzly** [comment]
@KenanY Thanks! need how many ram

**Comment by KenanY** [comment]
@kfzly Not sure, seems like other users here have had success with 96MB, but others need at least 512-1024MB. Probably just depends on how big your dependency tree is.

**Comment by kfzly** [comment]
@KenanY  ok,Thanks

**Comment by kfzly** [comment]
@KenanY I Give 4g ram ,but erro
![default](https://cloud.githubusercontent.com/assets/23254883/24551485/38379d6c-1655-11e7-8579-cbca7b0e0703.PNG)

**Comment by kfzly** [comment]
@KenanY https://gist.github.com/b5f4c04441784dbd6ef61f9c50445fdd.git
log

**Comment by KenanY** [comment]
@kfzly Hmm, log doesn't indicate why `node-gyp` failed here. Do you have all of the [necessary dependencies](https://github.com/nodejs/node-gyp/#installation)?

**Comment by kfzly** [comment]
@KenanY 
Yes,
![default](https://cloud.githubusercontent.com/assets/23254883/24575654/fdab189c-16de-11e7-9252-b3fe3cd39ac5.PNG)
log
https://gist.github.com/58ac88ac06020b3a880359e6c5d4f8a1.git
