### ISSUE TITLE
Atom publishing problem.

### ISSUE THREAD

**Issue by ValentinLaTortue** [npm/npm#16208]
#### I'm opening this issue because:

  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.

#### What's going wrong?
I'm trying to publish my first atom package but when I execute the command it gives me an error message

#### How can the CLI team reproduce the problem?
Tell me what to install/change to make it work.

Here is the error message the console is giving me:

npm ERR! Linux 4.8.0-44-generic
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "version" "minor" "-m" "Prepare %s release"                                                                                                  
npm ERR! node v4.4.5                                                                                                                  
npm ERR! npm  v3.10.5                                                                                                                 

npm ERR! Git working directory not clean.                                                                                             
npm ERR! M README.md                                                                                                                  
npm ERR!                                                                                                                              
npm ERR! If you need help, you may report this error at:                                                                              
npm ERR!     <https://github.com/npm/npm/issues>                                                                                      

npm ERR! Please include the following file with any support request:                                                                  
npm ERR!     /home/valentin/github/quick-comment/npm-debug.log  

And Here is the log file: [npm-debug.txt](https://github.com/npm/npm/files/884348/npm-debug.txt)

### supporting information:

 - `npm -v` prints:3.5.2
- `node -v` prints:4.2.6
 - `npm config get registry` prints:https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?:Linux
 - Network issues:
   - Geographic location where npm was run:
   - [x] I use a proxy to connect to the web.

**Comment by KenanY** [comment]
Looks like you have changes to `README.md` that you have not committed. You might want to either commit or `git stash` those changes.

**Comment by ValentinLaTortue** [comment]
I tried to commit the README.md a second time but it still doesn't work.

**Comment by KenanY** [comment]
@ValentinLaTortue Hmm, so the following does not work?:

``` shell
$ git checkout README.md
$ npm version minor -m "Prepare %s release"
```

(warning: first command will discard any uncommitted changes you have to `README.md`)

**Comment by naterkane** [comment]
@KenanY did't you mean `git checkout -- README.md`?

**Comment by KenanY** [comment]
@naterkane I believe the hyphens are [optional](https://git-scm.com/docs/git-checkout#git-checkout-emgitcheckoutem-p--patchlttree-ishgt--ltpathspecgt82308203), or at least I'm fairly certain I've used the syntax I wrote in the recent past.

**Comment by KenanY** [comment]
Although, those hyphens do solve [this ambiguity](https://git-scm.com/docs/git-checkout#_argument_disambiguation).

**Comment by naterkane** [comment]
@KenanY exactly, which makes using them good practice. what happens when you have a branch called `README` and a file called `README`?

`</digression>`

**Comment by KenanY** [comment]
Closing due to no reply from OP :/
