### ISSUE TITLE
npm issue

### ISSUE THREAD

**Issue by ShwetaSingh123** [npm/npm#16217]
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5

npm ERR! missing script: start
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\react\myapp\npm-debug.log

**Comment by KenanY** [comment]
@ShwetaSingh123 Can I close this in favor of https://github.com/npm/npm/issues/16218?

**Comment by MuhammadMahmoudH** [comment]
i have same error what can i do?
i try run cmd as administrator but the same 

C:\xampp\htdocs\laravel>npm start
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_module
s\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0

npm ERR! missing script: start
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Muahmmad\AppData\Roaming\npm-cache\_logs\2017-04-02T07_55_05_431Z-debug.log

**Comment by KenanY** [comment]
@MuhammadMahmoudH Hello! So, the way `npm start` works is that it looks in your current `package.json` for a defined `"start"` [script](https://docs.npmjs.com/misc/scripts), and then runs that. The error message you're seeing is trying to tell you that you have not defined a `"start"` script in your `package.json`, hence `npm start` has no idea what you want it to do.

To solve this issue, all you have to do is add a new script to your `package.json`. It might look something like this, for example:

``` json
{
  "name": "package-name",
  "version": "1.0.0",
  "description": "package description",
  "scripts": {
    "start": "node lib/server.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {},
  "devDependencies": {}
}
```

Note how this `package.json` has a `"start"` script that runs `node lib/server.js`. You'll definitely want to change the command to whatever is most appropriate for your project.

Let me know if you run into any further `npm` issues :)

**Comment by KenanY** [comment]
Closing in favor of https://github.com/npm/npm/issues/16218.
