### ISSUE TITLE
npm start issue

### ISSUE THREAD

**Issue by ShwetaSingh123** [npm/npm#16218]
> test-react@1.0.0 start D:\test-react
> webpack-dev-server

module.js:471
    throw err;
    ^

Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\test-react\node_modules\webpack-dev-server\lib\Server.js:15:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! test-react@1.0.0 start: `webpack-dev-server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the test-react@1.0.0 start script 'webpack-dev-server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the test-react package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs test-react
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls test-react
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\test-react\npm-debug.log

**Comment by KenanY** [comment]
@ShwetaSingh123 Could you try doing `npm install --save-dev webpack`?

**Comment by x4XStripesX2x** [comment]
npm WARN package.json twitter-bot-bootstrap-master@1.0.0 No description
npm WARN package.json twitter-bot-bootstrap-master@1.0.0 No repository field.
npm WARN package.json twitter-bot-bootstrap-master@1.0.0 No README data
npm WARN optional dep failed, continuing fsevents@1.1.1
webpack@2.3.2 node_modules/webpack
├── json-loader@0.5.4
├── tapable@0.2.6
├── loader-runner@2.3.0
├── interpret@1.0.2
├── acorn-dynamic-import@2.0.2
├── supports-color@3.2.3 (has-flag@1.0.0)
├── ajv-keywords@1.5.1
├── source-map@0.5.6
├── loader-utils@0.2.17 (object-assign@4.1.1, big.js@3.1.3, emojis-list@2.1.0, json5@0.5.1)
├── webpack-sources@0.2.3 (source-list-map@1.1.1)
├── acorn@4.0.11
├── mkdirp@0.5.1 (minimist@0.0.8)
├── enhanced-resolve@3.1.0 (object-assign@4.1.1, graceful-fs@4.1.11)
├── memory-fs@0.4.1 (errno@0.1.4, readable-stream@2.2.6)
├── uglify-js@2.8.20 (uglify-to-browserify@1.0.2, yargs@3.10.0)
├── ajv@4.11.5 (co@4.6.0, json-stable-stringify@1.0.1)
├── watchpack@1.3.1 (graceful-fs@4.1.11, chokidar@1.6.1)
├── yargs@6.6.0 (get-caller-file@1.0.2, decamelize@1.2.0, camelcase@3.0.0, y18n@3.2.1, which-module@1.0.0, set-blocking@2.0.0, yargs-parser@4.2.1, require-main-filename@1.0.1, require-directory@2.1.1, cliui@3.2.0, string-width@1.0.2, os-locale@1.4.0, read-pkg-up@1.0.1)
├── node-libs-browser@2.0.0 (punycode@1.4.1, https-browserify@0.0.1, tty-browserify@0.0.0, path-browserify@0.0.0, string_decoder@0.10.31, constants-browserify@1.0.0, os-browserify@0.2.1, process@0.11.9, assert@1.4.1, domain-browser@1.1.7, querystring-es3@0.2.1, stream-browserify@2.0.1, timers-browserify@2.0.2, events@1.1.1, vm-browserify@0.0.4, readable-stream@2.2.6, console-browserify@1.1.0, util@0.10.3, url@0.11.0, stream-http@2.6.3, buffer@4.9.1, browserify-zlib@0.1.4, crypto-browserify@3.11.0)
└── async@2.2.0 (lodash@4.17.4)


(That's what I got)

**Comment by x4XStripesX2x** [comment]
Do you have a YouTube video of you doing thing? I'm more of a visual learner and that would help so much!

**Comment by KenanY** [comment]
@x4XStripesX2x Are you seeing the same error that @ShwetaSingh123 is seeing?

**Comment by x4XStripesX2x** [comment]
npm ERR! Linux 4.9.17-c9
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v4.7.3/bin/node" "/home/ubuntu/.nvm/versions/node/v4.7.3/bin/npm" "start"
npm ERR! node v4.7.3
npm ERR! npm  v2.15.11

npm ERR! missing script: start
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/workspace/twitter-bot-bootstrap-master/npm-debug.log

(This is the error I keep getting, so no I don't have the same error as him. Do you want me to start a new thread?)
