### ISSUE TITLE
@angular/cli install erro 

### ISSUE THREAD

**Issue by JackLoveKaren** [npm/npm#16216]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
![image](https://cloud.githubusercontent.com/assets/22383016/24576627/f2ce53b8-16f1-11e7-9b7b-79169f580f41.png)

when i install @angular/cli ,it comes the erro like the pic show.I don't know what is going wrong
with my system. mybe you can help me . here thanks for your help
### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by SanthoshGnanasekaran** [comment]
Getting the below error while installing cli
D:\Angular>npm install -g @angular/cli
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! syscall getaddrinfo

npm ERR! getaddrinfo EAI_AGAIN registry.npmjs.org:443
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Angular\npm-debug.log

**Comment by danipi79** [comment]
I have a similar error!

λ npm install -g @angular/cli
npm ERR! registry error parsing json
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9

npm ERR! Unexpected token < in JSON at position 0
npm ERR! <html>
npm ERR!   <head>
npm ERR!     <title>404 - Path /@angular/cli not found in group repository &quot;npm-group-repo&quot; [id=npm-group-repo].</title>
npm ERR!     <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
npm ERR!
npm ERR!     <link rel="icon" type="image/png" href="http://10.113.52.95:8081/nexus/c/favicon.png">
npm ERR!     
npm ERR!
npm ERR!     <link rel="stylesheet" href="http://10.113.52.95:8081/nexus/c/static/css/Sonatype-content.css?2.12.0-01" type="text/css" media="screen" title="no title" charset="utf-8">
npm ERR!   </head>
npm ERR!   <body>
npm ERR!     <h1>404 - Path /@angular/cli not found in group repository &quot;npm-group-repo&quot; [id=npm-group-repo].</h1>
npm ERR!     <p>Path /@angular/cli not found in group repository &quot;npm-group-repo&quot; [id=npm-group-repo].</p>
npm ERR!   </body>
npm ERR! </html>
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\XP_ANG\npm-debug.log
