### ISSUE TITLE
npm publish returns 403

### ISSUE THREAD

**Issue by akash1810** [npm/npm#16226]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?
I'm trying to publish a minor update to `node-riffraff-artefact`, to version `1.8.2` from the latest master branch. I am an owner in this project, however when I run `npm publish` I get:

```sh
npm ERR! you do not have permission to publish "node-riffraff-artefact". Are you logged in as the correct user?
```

I am an owner of this module; I'm in the list returned by `npm owner ls`.

#### How can the CLI team reproduce the problem?
Attempt to publish an update to the `node-riffraff-artefact` module.

### supporting information:

 - `npm -v` prints: `3.8.3`
 - `node -v` prints: `v6.10.0`
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?: masOS
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by blemoine** [comment]
Same problem here on different repo (mnubo-sdk): 
`npm whoami` returns `blemoine`
`npm owner ls` returns  `blemoine <*my email address*>` among other owners

and still I have 
`you do not have permission to publish "mnubo-sdk". Are you logged in as the correct user? : mnubo-sdk`

**Comment by akash1810** [comment]
I've just updated npm to 4.4.4 and have been able to publish!

Leaving this open for npm maintainers to see though in case more information is needed.

**Comment by jtheoof** [comment]
A quick update that could help `npm` maintainers.

This issue happens when sharing a package with someone. I am the original author of the package and I was able to publish a new version of `mnubo-sdk` however @blemoine was not.

```
❯ npm access ls-collaborators
{
  "jtheoof": "read-write",
  "blemoine": "read-write"
}
```

**Comment by blemoine** [comment]
An update to the last npm version (4.4.4 as the time) didn't fix the problem for me :(
