### ISSUE TITLE
cannot install ionic and cordova

### ISSUE THREAD

**Issue by KamalCE** [npm/npm#16220]
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova" "ionic"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10

npm ERR! shasum check failed for C:\Users\sonik\AppData\Local\Temp\npm-4060-461591e3\registry.npmjs.org\ionic\-\ionic-2.2.2.tgz
npm ERR! Expected: 3890117c43f2cf6719a3b9063c928420d1762f41
npm ERR! Actual:   f8dd4a28433aacbc6f4b7809f6d2d7dd34824fce
npm ERR! From:     https://registry.npmjs.org/ionic/-/ionic-2.2.2.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\sonik\npm-debug.log

**Comment by KamalCE** [comment]
please help me, what should I do. my ionic get crashed. To fix it uninstalled ionic and Cordova and uninstalled nodejs. deleted all folders from c/user/.etc.

rebooted installed models again. now installing ionic and Cordova leading to this again

**Comment by KamalCE** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'cordova',
1 verbose cli   'ionic' ]
2 info using npm@3.10.10
3 info using node@v6.10.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData cordova
8 silly fetchPackageMetaData ionic
9 silly fetchNamedPackageData cordova
10 silly mapToRegistry name cordova
11 silly mapToRegistry using default registry
12 silly mapToRegistry registry https://registry.npmjs.org/
13 silly mapToRegistry data Result {
13 silly mapToRegistry   raw: 'cordova',
13 silly mapToRegistry   scope: null,
13 silly mapToRegistry   escapedName: 'cordova',
13 silly mapToRegistry   name: 'cordova',
13 silly mapToRegistry   rawSpec: '',
13 silly mapToRegistry   spec: 'latest',
13 silly mapToRegistry   type: 'tag' }
14 silly mapToRegistry uri https://registry.npmjs.org/cordova
15 silly fetchNamedPackageData ionic
16 silly mapToRegistry name ionic
17 silly mapToRegistry using default registry
18 silly mapToRegistry registry https://registry.npmjs.org/
19 silly mapToRegistry data Result {
19 silly mapToRegistry   raw: 'ionic',
19 silly mapToRegistry   scope: null,
19 silly mapToRegistry   escapedName: 'ionic',
19 silly mapToRegistry   name: 'ionic',
19 silly mapToRegistry   rawSpec: '',
19 silly mapToRegistry   spec: 'latest',
19 silly mapToRegistry   type: 'tag' }
20 silly mapToRegistry uri https://registry.npmjs.org/ionic
21 verbose request uri https://registry.npmjs.org/cordova
22 verbose request no auth needed
23 info attempt registry request try #1 at 10:19:09 PM
24 verbose request id ece73f6163219763
25 http request GET https://registry.npmjs.org/cordova
26 verbose request uri https://registry.npmjs.org/ionic
27 verbose request no auth needed
28 info attempt registry request try #1 at 10:19:10 PM
29 http request GET https://registry.npmjs.org/ionic
30 http 200 https://registry.npmjs.org/ionic
31 verbose headers { server: 'nginx/1.10.1',
31 verbose headers   'content-type': 'application/json',
31 verbose headers   'last-modified': 'Thu, 30 Mar 2017 20:14:29 GMT',
31 verbose headers   etag: 'W/"58dd6725-e1354"',
31 verbose headers   'content-encoding': 'gzip',
31 verbose headers   'cache-control': 'max-age=300',
31 verbose headers   'content-length': '50843',
31 verbose headers   'accept-ranges': 'bytes',
31 verbose headers   date: 'Sun, 02 Apr 2017 16:49:17 GMT',
31 verbose headers   via: '1.1 varnish',
31 verbose headers   age: '61',
31 verbose headers   connection: 'keep-alive',
31 verbose headers   'x-served-by': 'cache-lcy1130-LCY',
31 verbose headers   'x-cache': 'HIT',
31 verbose headers   'x-cache-hits': '1',
31 verbose headers   'x-timer': 'S1491151757.373432,VS0,VE0',
31 verbose headers   vary: 'Accept-Encoding' }
32 silly get cb [ 200,
32 silly get   { server: 'nginx/1.10.1',
32 silly get     'content-type': 'application/json',
32 silly get     'last-modified': 'Thu, 30 Mar 2017 20:14:29 GMT',
32 silly get     etag: 'W/"58dd6725-e1354"',
32 silly get     'content-encoding': 'gzip',
32 silly get     'cache-control': 'max-age=300',
32 silly get     'content-length': '50843',
32 silly get     'accept-ranges': 'bytes',
32 silly get     date: 'Sun, 02 Apr 2017 16:49:17 GMT',
32 silly get     via: '1.1 varnish',
32 silly get     age: '61',
32 silly get     connection: 'keep-alive',
32 silly get     'x-served-by': 'cache-lcy1130-LCY',
32 silly get     'x-cache': 'HIT',
32 silly get     'x-cache-hits': '1',
32 silly get     'x-timer': 'S1491151757.373432,VS0,VE0',
32 silly get     vary: 'Accept-Encoding' } ]
33 verbose get saving ionic to C:\Users\sonik\AppData\Roaming\npm-cache\registry.npmjs.org\ionic\.cache.json
34 verbose correctMkdir C:\Users\sonik\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
35 verbose makeDirectory C:\Users\sonik\AppData\Roaming\npm-cache creation not in flight; initializing
36 verbose makeCacheDir UID & GID are irrelevant on win32
37 http 200 https://registry.npmjs.org/cordova
38 verbose headers { server: 'nginx/1.10.1',
38 verbose headers   'content-type': 'application/json',
38 verbose headers   'last-modified': 'Sun, 02 Apr 2017 08:13:53 GMT',
38 verbose headers   etag: 'W/"58e0b2c1-12d6fd"',
38 verbose headers   'content-encoding': 'gzip',
38 verbose headers   'cache-control': 'max-age=300',
38 verbose headers   'content-length': '44274',
38 verbose headers   'accept-ranges': 'bytes',
38 verbose headers   date: 'Sun, 02 Apr 2017 16:49:24 GMT',
38 verbose headers   via: '1.1 varnish',
38 verbose headers   age: '201',
38 verbose headers   connection: 'keep-alive',
38 verbose headers   'x-served-by': 'cache-lcy1140-LCY',
38 verbose headers   'x-cache': 'HIT',
38 verbose headers   'x-cache-hits': '1',
38 verbose headers   'x-timer': 'S1491151764.606090,VS0,VE0',
38 verbose headers   vary: 'Accept-Encoding' }
39 silly get cb [ 200,
39 silly get   { server: 'nginx/1.10.1',
39 silly get     'content-type': 'application/json',
39 silly get     'last-modified': 'Sun, 02 Apr 2017 08:13:53 GMT',
39 silly get     etag: 'W/"58e0b2c1-12d6fd"',
39 silly get     'content-encoding': 'gzip',
39 silly get     'cache-control': 'max-age=300',
39 silly get     'content-length': '44274',
39 silly get     'accept-ranges': 'bytes',
39 silly get     date: 'Sun, 02 Apr 2017 16:49:24 GMT',
39 silly get     via: '1.1 varnish',
39 silly get     age: '201',
39 silly get     connection: 'keep-alive',
39 silly get     'x-served-by': 'cache-lcy1140-LCY',
39 silly get     'x-cache': 'HIT',
39 silly get     'x-cache-hits': '1',
39 silly get     'x-timer': 'S1491151764.606090,VS0,VE0',
39 silly get     vary: 'Accept-Encoding' } ]
40 verbose get saving cordova to C:\Users\sonik\AppData\Roaming\npm-cache\registry.npmjs.org\cordova\.cache.json
41 verbose correctMkdir C:\Users\sonik\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
42 silly install normalizeTree
43 silly loadCurrentTree Finishing
44 silly loadIdealTree Starting
45 silly install loadIdealTree
46 silly cloneCurrentTree Starting
47 silly install cloneCurrentTreeToIdealTree
48 silly cloneCurrentTree Finishing
49 silly loadShrinkwrap Starting
50 silly install loadShrinkwrap
51 silly loadShrinkwrap Finishing
52 silly loadAllDepsIntoIdealTree Starting
53 silly install loadAllDepsIntoIdealTree
54 silly resolveWithNewModule ionic@2.2.2 checking installable status
55 silly cache add args [ 'ionic', null ]
56 verbose cache add spec ionic
57 silly resolveWithNewModule cordova@6.5.0 checking installable status
58 silly cache add args [ 'cordova', null ]
59 verbose cache add spec cordova
60 silly cache add parsed spec Result {
60 silly cache add   raw: 'ionic',
60 silly cache add   scope: null,
60 silly cache add   escapedName: 'ionic',
60 silly cache add   name: 'ionic',
60 silly cache add   rawSpec: '',
60 silly cache add   spec: 'latest',
60 silly cache add   type: 'tag' }
61 silly addNamed ionic@latest
62 verbose addNamed "latest" is being treated as a dist-tag for ionic
63 info addNameTag [ 'ionic', 'latest' ]
64 silly mapToRegistry name ionic
65 silly mapToRegistry using default registry
66 silly mapToRegistry registry https://registry.npmjs.org/
67 silly mapToRegistry data Result {
67 silly mapToRegistry   raw: 'ionic',
67 silly mapToRegistry   scope: null,
67 silly mapToRegistry   escapedName: 'ionic',
67 silly mapToRegistry   name: 'ionic',
67 silly mapToRegistry   rawSpec: '',
67 silly mapToRegistry   spec: 'latest',
67 silly mapToRegistry   type: 'tag' }
68 silly mapToRegistry uri https://registry.npmjs.org/ionic
69 verbose addNameTag registry:https://registry.npmjs.org/ionic not in flight; fetching
70 silly cache add parsed spec Result {
70 silly cache add   raw: 'cordova',
70 silly cache add   scope: null,
70 silly cache add   escapedName: 'cordova',
70 silly cache add   name: 'cordova',
70 silly cache add   rawSpec: '',
70 silly cache add   spec: 'latest',
70 silly cache add   type: 'tag' }
71 silly addNamed cordova@latest
72 verbose addNamed "latest" is being treated as a dist-tag for cordova
73 info addNameTag [ 'cordova', 'latest' ]
74 silly mapToRegistry name cordova
75 silly mapToRegistry using default registry
76 silly mapToRegistry registry https://registry.npmjs.org/
77 silly mapToRegistry data Result {
77 silly mapToRegistry   raw: 'cordova',
77 silly mapToRegistry   scope: null,
77 silly mapToRegistry   escapedName: 'cordova',
77 silly mapToRegistry   name: 'cordova',
77 silly mapToRegistry   rawSpec: '',
77 silly mapToRegistry   spec: 'latest',
77 silly mapToRegistry   type: 'tag' }
78 silly mapToRegistry uri https://registry.npmjs.org/cordova
79 verbose addNameTag registry:https://registry.npmjs.org/cordova not in flight; fetching
80 verbose get https://registry.npmjs.org/ionic not expired, no request
81 silly addNameTag next cb for ionic with tag latest
82 silly addNamed ionic@2.2.2
83 verbose addNamed "2.2.2" is a plain semver version for ionic
84 verbose get https://registry.npmjs.org/cordova not expired, no request
85 silly addNameTag next cb for cordova with tag latest
86 silly addNamed cordova@6.5.0
87 verbose addNamed "6.5.0" is a plain semver version for cordova
88 silly mapToRegistry name ionic
89 silly mapToRegistry using default registry
90 silly mapToRegistry registry https://registry.npmjs.org/
91 silly mapToRegistry data Result {
91 silly mapToRegistry   raw: 'ionic',
91 silly mapToRegistry   scope: null,
91 silly mapToRegistry   escapedName: 'ionic',
91 silly mapToRegistry   name: 'ionic',
91 silly mapToRegistry   rawSpec: '',
91 silly mapToRegistry   spec: 'latest',
91 silly mapToRegistry   type: 'tag' }
92 silly mapToRegistry uri https://registry.npmjs.org/ionic
93 verbose addRemoteTarball https://registry.npmjs.org/ionic/-/ionic-2.2.2.tgz not in flight; adding
94 verbose addRemoteTarball [ 'https://registry.npmjs.org/ionic/-/ionic-2.2.2.tgz',
94 verbose addRemoteTarball   '3890117c43f2cf6719a3b9063c928420d1762f41' ]
95 silly mapToRegistry name cordova
96 silly mapToRegistry using default registry
97 silly mapToRegistry registry https://registry.npmjs.org/
98 silly mapToRegistry data Result {
98 silly mapToRegistry   raw: 'cordova',
98 silly mapToRegistry   scope: null,
98 silly mapToRegistry   escapedName: 'cordova',
98 silly mapToRegistry   name: 'cordova',
98 silly mapToRegistry   rawSpec: '',
98 silly mapToRegistry   spec: 'latest',
98 silly mapToRegistry   type: 'tag' }
99 silly mapToRegistry uri https://registry.npmjs.org/cordova
100 verbose addRemoteTarball https://registry.npmjs.org/cordova/-/cordova-6.5.0.tgz not in flight; adding
101 verbose addRemoteTarball [ 'https://registry.npmjs.org/cordova/-/cordova-6.5.0.tgz',
101 verbose addRemoteTarball   'e6ec81b17dd50c17c40b4b87330f7ced38fb0b47' ]
102 info retry fetch attempt 1 at 10:19:33 PM
103 info attempt registry request try #1 at 10:19:33 PM
104 http fetch GET https://registry.npmjs.org/ionic/-/ionic-2.2.2.tgz
105 info retry fetch attempt 1 at 10:19:33 PM
106 info attempt registry request try #1 at 10:19:33 PM
107 http fetch GET https://registry.npmjs.org/cordova/-/cordova-6.5.0.tgz
108 http fetch 200 https://registry.npmjs.org/cordova/-/cordova-6.5.0.tgz
109 http fetch 200 https://registry.npmjs.org/ionic/-/ionic-2.2.2.tgz
110 silly fetchAndShaCheck shasum e6ec81b17dd50c17c40b4b87330f7ced38fb0b47
111 verbose addTmpTarball C:\Users\sonik\AppData\Local\Temp\npm-4060-461591e3\registry.npmjs.org\cordova\-\cordova-6.5.0.tgz not in flight; adding
112 verbose addTmpTarball already have metadata; skipping unpack for cordova@6.5.0
113 verbose correctMkdir C:\Users\sonik\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
114 silly cache afterAdd cordova@6.5.0
115 verbose afterAdd C:\Users\sonik\AppData\Roaming\npm-cache\cordova\6.5.0\package\package.json not in flight; writing
116 verbose correctMkdir C:\Users\sonik\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
117 verbose afterAdd C:\Users\sonik\AppData\Roaming\npm-cache\cordova\6.5.0\package\package.json written
118 info retry will retry, error on last attempt: Error: read ECONNRESET
119 silly fetchAndShaCheck shasum 3890117c43f2cf6719a3b9063c928420d1762f41
120 silly rollbackFailedOptional Starting
121 silly rollbackFailedOptional Finishing
122 silly runTopLevelLifecycles Finishing
123 silly install printInstalled
124 verbose stack Error: shasum check failed for C:\Users\sonik\AppData\Local\Temp\npm-4060-461591e3\registry.npmjs.org\ionic\-\ionic-2.2.2.tgz
124 verbose stack Expected: 3890117c43f2cf6719a3b9063c928420d1762f41
124 verbose stack Actual:   f8dd4a28433aacbc6f4b7809f6d2d7dd34824fce
124 verbose stack From:     https://registry.npmjs.org/ionic/-/ionic-2.2.2.tgz
124 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:25:8
124 verbose stack     at ReadStream.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:72:7)
124 verbose stack     at emitNone (events.js:91:20)
124 verbose stack     at ReadStream.emit (events.js:185:7)
124 verbose stack     at endReadableNT (_stream_readable.js:974:12)
124 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:80:11)
124 verbose stack     at process._tickCallback (internal/process/next_tick.js:104:9)
125 verbose cwd C:\Users\sonik
126 error Windows_NT 10.0.14393
127 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova" "ionic"
128 error node v6.10.1
129 error npm  v3.10.10
130 error shasum check failed for C:\Users\sonik\AppData\Local\Temp\npm-4060-461591e3\registry.npmjs.org\ionic\-\ionic-2.2.2.tgz
130 error Expected: 3890117c43f2cf6719a3b9063c928420d1762f41
130 error Actual:   f8dd4a28433aacbc6f4b7809f6d2d7dd34824fce
130 error From:     https://registry.npmjs.org/ionic/-/ionic-2.2.2.tgz
131 error If you need help, you may report this error at:
131 error     <https://github.com/npm/npm/issues>
132 verbose exit [ 1, true ]

**Comment by dguzman1012** [comment]
I can't install it neither:

`sudo npm install ionic -g`

But it hangs here:
`loadRequestedDeps → netwo`

**Comment by dguzman1012** [comment]
When i try 
`sudo npm install ionic@1.7.16 -g` or `sudo npm install ionic@1.3.1 -g`
It shows me this:

```
npm ERR! fetch failed https://registry.npmjs.org/i/-/i-0.3.2.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
loadRequestedDeps → gunzT ▄ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟

```

Please help!

**Comment by KamalCE** [comment]
### My ionic is started working now.

what I did is following:
first check environment variable is set or not in PATH of npm.
if not set your path to npm
C:\Users\your user name\AppData\Roaming\npm
reboot system and now check if still not working then do following:
 I did everything to fix it searched all over tried all suggestion and post but nothing worked.

Then i removed ionic and Cordova by command "
**npm uninstall -g Cordova** 
**npm uninstall -g ionic**

**now reboot your system**

then i uninstalled nodejs and cleaned the cache.
to uninstall nodejs go to control panel and uninstall the nodejs.

after uninstalling nodejs clean the cache by 

**npm cache clean**

**reboot system**

delete all file and folder from 

C:\Program Files\Nodejs
C:\Users\your user name\AppData\Roaming\npm
C:\Users\your user name\AppData\Roaming\npm-cache

search all existing folder for node,  npm and npm-modules and delete it

reboot again.

Now install node js and reboot.
set the environment variable of npm 
like 
C:\Users\your user name\AppData\Roaming\npm

now install ionic by 
 npm install -g Cordova ionic

update cordova cli
 npm update -g cordova or npm install -g cordova.

reboot

it will work now.

**Comment by KenanY** [comment]
Closing as resolved then.
