### ISSUE TITLE
Npm not installing crypto

### ISSUE THREAD

**Issue by Kong-plays** [npm/npm#16228]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ -] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
When i try to install crypto it returns this
root@CSGORapid:/var/www/bot# npm install crypto
npm WARN package.json onceler@0.0.5 No repository field.
npm http GET https://registry.npmjs.org/crypto
npm http 304 https://registry.npmjs.org/crypto
npm WARN unmet dependency /var/www/bot/node_modules/steam-user/node_modules/steam-client requires @doctormckay/steam-crypto@'^1.1.0' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /var/www/bot/node_modules/steam-user/node_modules/steam-client/node_modules/steam-resources/node_modules/ascli requires colour@'latest' but will load
npm WARN unmet dependency /var/www/bot/node_modules/steam-user/node_modules/steam-client/node_modules/steam-resources/node_modules/colour,
npm WARN unmet dependency which is version 0.7.1
npm WARN unmet dependency /var/www/bot/node_modules/steam-user/node_modules/steam-client/node_modules/steam-resources/node_modules/ascli requires optjs@'latest' but will load
npm WARN unmet dependency /var/www/bot/node_modules/steam-user/node_modules/steam-client/node_modules/steam-resources/node_modules/optjs,
npm WARN unmet dependency which is version 3.2.2
crypto@0.0.3 node_modules/crypto

### supporting information:

 - `npm -v` prints:1.3.10
 - `node -v` prints:nothing
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:linux
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [- ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [- ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@Kong-plays `npm@1.3` is years old and is no longer supported. If this is still an issue with the latest stable version of `npm`, then I will happily reopen.
