### ISSUE TITLE
npm owner add: Forbidden

### ISSUE THREAD

**Issue by rvagg** [npm/npm#16233]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?

`npm owner add` is failing where it shouldn't with a "Forbidden". There is a suspiciously long delay on one of the requests that suggests something may be up on the server-side.

```
$ npm whoami
npm http request GET https://registry.npmjs.org/-/whoami
npm http 200 https://registry.npmjs.org/-/whoami
rvagg
$ npm owner ls string_decoder
substack <mail@substack.net>
rvagg <rod@vagg.org>
$ npm owner add matteo.collina string_decoder
npm http request GET https://registry.npmjs.org/-/user/org.couchdb.user:matteo.collina
npm http 200 https://registry.npmjs.org/-/user/org.couchdb.user:matteo.collina
npm http request GET https://registry.npmjs.org/string_decoder
npm http 304 https://registry.npmjs.org/string_decoder
npm http request PUT https://registry.npmjs.org/string_decoder/-rev/30-e3500e5fe845e47b0f94a17347c2b768
npm http 500 https://registry.npmjs.org/string_decoder/-rev/30-e3500e5fe845e47b0f94a17347c2b768
npm http request PUT https://registry.npmjs.org/string_decoder/-rev/30-e3500e5fe845e47b0f94a17347c2b768
npm http 500 https://registry.npmjs.org/string_decoder/-rev/30-e3500e5fe845e47b0f94a17347c2b768
npm http request PUT https://registry.npmjs.org/string_decoder/-rev/30-e3500e5fe845e47b0f94a17347c2b768
npm http 500 https://registry.npmjs.org/string_decoder/-rev/30-e3500e5fe845e47b0f94a17347c2b768
npm ERR! owner mutate Failed to update package metadata
npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "owner" "add" "matteo.collina" "string_decoder"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! code E500

npm ERR! "Forbidden" : string_decoder
```

The final `PUT` on the above chain hangs for quite a while (maybe 30 seconds) before I get the failure.

I've tried the exact command but with a different package and it works fine, and without the delay.

#### How can the CLI team reproduce the problem?

Switch to `rvagg` and run the same thing? I'm happy for you to do the same thing fwiw, I just want to add @mcollina to `string_decoder`.

https://gist.github.com/rvagg/521b9e9d5c53845918ed9701c891feb3

### supporting information:

 - `npm -v` prints: 4.2.0 (have also just tried with 4.4.0 with the same result)
 - `node -v` prints: v7.8.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS
 - Network issues:
   - Geographic location where npm was run: Sydney / Australia, direct connection no proxy
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

Cheers

**Comment by sichvoge** [comment]
I can echo this behaviour. I cannot add someone to a project either. Is there any workaround?

**Comment by johnnyman727** [comment]
same here

**Comment by mjackson** [comment]
I'm also seeing this issue this morning :'( Trying to add a new owner to `react-router-dom` and `react-router-native` as user `mjackson`

**Comment by sichvoge** [comment]
The only solution I have found is doing it directly from the npmjs UI.

**Comment by mjackson** [comment]
Thanks for the suggestion, @sichvoge! Worked for me too.
