### ISSUE TITLE
npm start not working 

### ISSUE THREAD

**Issue by agopali** [npm/npm#16237]
Error I am having:

pm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Progr
ode_modules\\npm\\bin\\npm-cli.js" "start"
pm ERR! node v7.8.0
pm ERR! npm  v4.2.0
pm ERR! code ELIFECYCLE
pm ERR! errno 1
pm ERR! angular-io-example@1.0.0 start: `concurrently "npm ru
 run serve"`
pm ERR! Exit status 1
pm ERR!
pm ERR! Failed at the angular-io-example@1.0.0 start script '
un build:watch" "npm run serve"'.
pm ERR! Make sure you have the latest version of node.js and
pm ERR! If you do, this is most likely a problem with the ang
kage,
pm ERR! not with npm itself.
pm ERR! Tell the author that this fails on your system:
pm ERR!     concurrently "npm run build:watch" "npm run serve
pm ERR! You can get information on how to open an issue for t

**Comment by KenanY** [comment]
@agopali Is your `"start"` script correct? Looks like you have a typo, I think.

**Comment by agopali** [comment]
@KenanY 
I installed by 
npm install
started by
npm start

below is my package.json. Any help will be appreciated.
{
  "name": "angular-io-example",
  "version": "1.0.0",
  "private": true,
  "description": "Example project from an angular.io guide.",
  "scripts": {
    "test:once": "karma start karma.conf.js --single-run",
    "build": "tsc -p src/",
    "serve": "lite-server -c=bs-config.json",
    "prestart": "npm run build",
    "start": "concurrently \"npm run build:watch\" \"npm run serve\"",
    "pretest": "npm run build",
    "test": "concurrently \"npm run build:watch\" \"karma start karma.conf.js\"",
    "pretest:once": "npm run build",
    "build:watch": "tsc -p src/ -w",
    "build:upgrade": "tsc",
    "serve:upgrade": "http-server",
    "build:aot": "ngc -p tsconfig-aot.json && rollup -c rollup-config.js",
    "serve:aot": "lite-server -c bs-config.aot.json",
    "build:babel": "babel src -d src --extensions \".es6\" --source-maps",
    "copy-dist-files": "node ./copy-dist-files.js",
    "i18n": "ng-xi18n",
    "lint": "tslint ./src/**/*.ts -t verbose"
  },
  "keywords": [],
  "author": "",
  "license": "MIT",
  "dependencies": {
    "@angular/common": "~4.0.0",
    "@angular/compiler": "~4.0.0",
    "@angular/compiler-cli": "~4.0.0",
    "@angular/core": "~4.0.0",
    "@angular/forms": "~4.0.0",
    "@angular/http": "~4.0.0",
    "@angular/platform-browser": "~4.0.0",
    "@angular/platform-browser-dynamic": "~4.0.0",
    "@angular/platform-server": "~4.0.0",
    "@angular/router": "~4.0.0",
    "@angular/tsc-wrapped": "~4.0.0",
    "@angular/upgrade": "~4.0.0",
    "angular-in-memory-web-api": "~0.3.1",
    "core-js": "^2.4.1",
    "rxjs": "5.0.1",
    "systemjs": "0.19.39",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@types/angular": "^1.5.16",
    "@types/angular-animate": "^1.5.5",
    "@types/angular-cookies": "^1.4.2",
    "@types/angular-mocks": "^1.5.5",
    "@types/angular-resource": "^1.5.6",
    "@types/angular-route": "^1.3.2",
    "@types/angular-sanitize": "^1.3.3",
    "@types/jasmine": "2.5.36",
    "@types/node": "^6.0.45",
    "babel-cli": "^6.16.0",
    "babel-preset-angular2": "^0.0.2",
    "babel-preset-es2015": "^6.16.0",
    "canonical-path": "0.0.2",
    "concurrently": "^3.0.0",
    "http-server": "^0.9.0",
    "jasmine": "~2.4.1",
    "jasmine-core": "~2.4.1",
    "karma": "^1.3.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-phantomjs-launcher": "^1.0.2",
    "lite-server": "^2.2.2",
    "lodash": "^4.16.2",
    "phantomjs-prebuilt": "^2.1.7",
    "protractor": "~4.0.14",
    "rollup": "^0.36.0",
    "rollup-plugin-commonjs": "^4.1.0",
    "rollup-plugin-node-resolve": "^2.0.0",
    "rollup-plugin-uglify": "^1.0.1",
    "source-map-explorer": "^1.3.2",
    "tslint": "^3.15.1",
    "typescript": "~2.2.0"
  },
  "repository": {}
}

**Comment by agopali** [comment]
@KenanY,
For your reference below is the log file
https://gist.github.com/agopali/1832546406e4b6592c6aec819879df21

**Comment by KenanY** [comment]
@agopali Alright, let's try to narrow this down. Do both `npm run build:watch` and `npm run serve` work without error?

**Comment by agopali** [comment]
@KenanY  
Not sure about that because the error log says:
28 error Failed at the angular-quickstart@1.0.0 start script 'concurrently "npm run build:watch" "npm run serve"'.

Weird thing is I am able to install and start npm without any error in my home PC, but can't not start npm in my office PC! Anybody facing the same issue?

**Comment by KenanY** [comment]
@agopali What do you mean "not sure about that"? I'm trying to debug why `concurrently "npm run build:watch" "npm run serve"` is failing on your system, hence why I asked you to try those two `npm` scripts that your `"start"` script is calling.

**Comment by agopali** [comment]
@KenanY 
Here is what I got when I run them

C:\quickstart>npm run build:watch
> angular-io-example@1.0.0 build:watch C:\quickstart
> tsc -p src/ -w
11:15:28 AM - Compilation complete. Watching for file changes.

C:\quickstart>npm run serve
> angular-io-example@1.0.0 serve C:\quickstart
> lite-server -c=bs-config.json
** browser-sync config **
{ injectChanges: false,
  files: [ './**/*.{html,htm,css,js}' ],
  watchOptions: { ignored: 'node_modules' },
  server:
   { baseDir: 'src',
     middleware: [ [Function], [Function] ],
     routes: { '/node_modules': 'node_modules' } } }
[BS] Access URLs:
 --------------------------------------
       Local: http://localhost:3000
    External: http://10.150.48.160:3000
 --------------------------------------
          UI: http://localhost:3001
 UI External: http://10.150.48.160:3001
 --------------------------------------
[BS] Serving files from: src
[BS] Watching files...
[BS] Couldn't open browser (if you are using BrowserSync in a headless environme
nt, you might want to set the open option to false)

I have no idea what this means?

**Comment by KenanY** [comment]
@agopali Thanks. Now, what's the result of:

``` bash
node node_modules\.bin\concurrently "npm run build:watch" "npm run serve"
```

(also, interestingly enough, your `package.json` is invalid JSON for me, since it uses unescaped double quotes within double quotes)

**Comment by agopali** [comment]
@KenanY ,

The below is the result:
C:\quickstart>node node_modules\.bin\concurrently "npm run build:watch" "npm run
 serve"
C:\quickstart\node_modules\.bin\concurrently:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^
SyntaxError: missing ) after argument list
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)

package.json is supposed to download from quickstart tutorial from angular.io right? do we need to update package.json?

**Comment by agopali** [comment]
C:\quickstart>node node_modules\.bin\concurrently "npm run build:watch" "npm run
 serve"
C:\quickstart\node_modules\.bin\concurrently:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^
SyntaxError: missing ) after argument list
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)

re-ran as there was some syntax error.

**Comment by KenanY** [comment]
@agopali Whoops, my bad, can you try this instead?

``` bash
node node_modules\concurrently\src\main.js "npm run build:watch" "npm run serve"
```

**Comment by agopali** [comment]
@KenanY  here it is:

C:\quickstart>node node_modules\concurrently\src\main.js "npm run build:watch" "
npm run serve"
 Error occured when executing command: npm run serve
 Error: spawn cmd.exe ENOENT
     at exports._errnoException (util.js:1034:11)
     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
     at onErrorNT (internal/child_process.js:367:16)
     at _combinedTickCallback (internal/process/next_tick.js:80:11)
     at process._tickCallback (internal/process/next_tick.js:104:9)
     at Module.runMain (module.js:607:11)
     at run (bootstrap_node.js:423:7)
     at startup (bootstrap_node.js:147:9)
     at bootstrap_node.js:538:3
 Error occured when executing command: npm run serve
 Error: spawn cmd.exe ENOENT
     at exports._errnoException (util.js:1034:11)
     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
     at onErrorNT (internal/child_process.js:367:16)
     at _combinedTickCallback (internal/process/next_tick.js:80:11)
     at process._tickCallback (internal/process/next_tick.js:104:9)
     at Module.runMain (module.js:607:11)
     at run (bootstrap_node.js:423:7)
     at startup (bootstrap_node.js:147:9)
     at bootstrap_node.js:538:3
[1] npm run serve exited with code -4058

C:\quickstart>

**Comment by KenanY** [comment]
Alright, so we've now ruled out this being the fault of `npm`. For whatever reason, Node is unable to spawn `cmd.exe`, which should exist on your Window system. Does this also occur from an administrator terminal?

**Comment by agopali** [comment]
Yes ,it does.

**Comment by agopali** [comment]
I am able to solve my issue using angular cli install like below:
npm install -g @angular/cli
ng new PROJECT_NAME
cd PROJECT_NAME
ng serve

Navigate to http://localhost:4200/

**Comment by KenanY** [comment]
Closing as resolved then.
