### ISSUE TITLE
Cannot install firebase dependencies

### ISSUE THREAD

**Issue by VisheshSingh** [npm/npm#16230]
I am trying to install firebase dependencies with this command:

npm install firebase angularfirebase2 anglar2-flash-messages --save.

It gives me the following error:
sudo npm install firebase angularfirebase2 angular2-flash-messages --save
npm ERR! Linux 4.8.0-36-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "firebase" "angularfirebase2" "angular2-flash-messages" "--save"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/angularfirebase2
npm ERR! 404 
npm ERR! 404  'angularfirebase2' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vishesh/npm-debug.log

Here's my debug.log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   'firebase',
1 verbose cli   'angularfirebase2',
1 verbose cli   'angular2-flash-messages',
1 verbose cli   '--save' ]
2 info using npm@3.10.10
3 info using node@v6.10.1
4 verbose config Skipping project config: /home/vishesh/.npmrc. (matches userconfig)
5 silly loadCurrentTree Starting
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 silly fetchPackageMetaData firebase
9 silly fetchPackageMetaData angularfirebase2
10 silly fetchPackageMetaData angular2-flash-messages
11 silly fetchNamedPackageData firebase
12 silly mapToRegistry name firebase
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry data Result {
15 silly mapToRegistry   raw: 'firebase',
15 silly mapToRegistry   scope: null,
15 silly mapToRegistry   escapedName: 'firebase',
15 silly mapToRegistry   name: 'firebase',
15 silly mapToRegistry   rawSpec: '',
15 silly mapToRegistry   spec: 'latest',
15 silly mapToRegistry   type: 'tag' }
16 silly mapToRegistry uri https://registry.npmjs.org/firebase
17 silly fetchNamedPackageData angularfirebase2
18 silly mapToRegistry name angularfirebase2
19 silly mapToRegistry using default registry
20 silly mapToRegistry registry https://registry.npmjs.org/
21 silly mapToRegistry data Result {
21 silly mapToRegistry   raw: 'angularfirebase2',
21 silly mapToRegistry   scope: null,
21 silly mapToRegistry   escapedName: 'angularfirebase2',
21 silly mapToRegistry   name: 'angularfirebase2',
21 silly mapToRegistry   rawSpec: '',
21 silly mapToRegistry   spec: 'latest',
21 silly mapToRegistry   type: 'tag' }
22 silly mapToRegistry uri https://registry.npmjs.org/angularfirebase2
23 silly fetchNamedPackageData angular2-flash-messages
24 silly mapToRegistry name angular2-flash-messages
25 silly mapToRegistry using default registry
26 silly mapToRegistry registry https://registry.npmjs.org/
27 silly mapToRegistry data Result {
27 silly mapToRegistry   raw: 'angular2-flash-messages',
27 silly mapToRegistry   scope: null,
27 silly mapToRegistry   escapedName: 'angular2-flash-messages',
27 silly mapToRegistry   name: 'angular2-flash-messages',
27 silly mapToRegistry   rawSpec: '',
27 silly mapToRegistry   spec: 'latest',
27 silly mapToRegistry   type: 'tag' }
28 silly mapToRegistry uri https://registry.npmjs.org/angular2-flash-messages
29 verbose request uri https://registry.npmjs.org/angularfirebase2
30 verbose request no auth needed
31 info attempt registry request try #1 at 11:44:27 AM
32 verbose request id 05685204aa08ca1c
33 http request GET https://registry.npmjs.org/angularfirebase2
34 verbose request uri https://registry.npmjs.org/firebase
35 verbose request no auth needed
36 info attempt registry request try #1 at 11:44:27 AM
37 verbose etag W/"58dacfc9-1de4d"
38 verbose lastModified Tue, 28 Mar 2017 21:04:09 GMT
39 http request GET https://registry.npmjs.org/firebase
40 verbose request uri https://registry.npmjs.org/angular2-flash-messages
41 verbose request no auth needed
42 info attempt registry request try #1 at 11:44:27 AM
43 verbose etag W/"58dcf26a-58e3"
44 verbose lastModified Thu, 30 Mar 2017 11:56:26 GMT
45 http request GET https://registry.npmjs.org/angular2-flash-messages
46 http 304 https://registry.npmjs.org/firebase
47 verbose headers { date: 'Mon, 03 Apr 2017 15:44:27 GMT',
47 verbose headers   via: '1.1 varnish',
47 verbose headers   'cache-control': 'max-age=300',
47 verbose headers   etag: 'W/"58dacfc9-1de4d"',
47 verbose headers   age: '23',
47 verbose headers   connection: 'keep-alive',
47 verbose headers   'x-served-by': 'cache-iad2621-IAD',
47 verbose headers   'x-cache': 'HIT',
47 verbose headers   'x-cache-hits': '1',
47 verbose headers   'x-timer': 'S1491234267.253221,VS0,VE0',
47 verbose headers   vary: 'Accept-Encoding' }
48 silly get cb [ 304,
48 silly get   { date: 'Mon, 03 Apr 2017 15:44:27 GMT',
48 silly get     via: '1.1 varnish',
48 silly get     'cache-control': 'max-age=300',
48 silly get     etag: 'W/"58dacfc9-1de4d"',
48 silly get     age: '23',
48 silly get     connection: 'keep-alive',
48 silly get     'x-served-by': 'cache-iad2621-IAD',
48 silly get     'x-cache': 'HIT',
48 silly get     'x-cache-hits': '1',
48 silly get     'x-timer': 'S1491234267.253221,VS0,VE0',
48 silly get     vary: 'Accept-Encoding' } ]
49 verbose etag https://registry.npmjs.org/firebase from cache
50 verbose get saving firebase to /home/vishesh/.npm/registry.npmjs.org/firebase/.cache.json
51 verbose correctMkdir /home/vishesh/.npm correctMkdir not in flight; initializing
52 http 304 https://registry.npmjs.org/angular2-flash-messages
53 verbose headers { date: 'Mon, 03 Apr 2017 15:44:27 GMT',
53 verbose headers   via: '1.1 varnish',
53 verbose headers   'cache-control': 'max-age=300',
53 verbose headers   etag: 'W/"58dcf26a-58e3"',
53 verbose headers   age: '23',
53 verbose headers   connection: 'keep-alive',
53 verbose headers   'x-served-by': 'cache-iad2625-IAD',
53 verbose headers   'x-cache': 'HIT',
53 verbose headers   'x-cache-hits': '1',
53 verbose headers   'x-timer': 'S1491234267.288151,VS0,VE0',
53 verbose headers   vary: 'Accept-Encoding' }
54 silly get cb [ 304,
54 silly get   { date: 'Mon, 03 Apr 2017 15:44:27 GMT',
54 silly get     via: '1.1 varnish',
54 silly get     'cache-control': 'max-age=300',
54 silly get     etag: 'W/"58dcf26a-58e3"',
54 silly get     age: '23',
54 silly get     connection: 'keep-alive',
54 silly get     'x-served-by': 'cache-iad2625-IAD',
54 silly get     'x-cache': 'HIT',
54 silly get     'x-cache-hits': '1',
54 silly get     'x-timer': 'S1491234267.288151,VS0,VE0',
54 silly get     vary: 'Accept-Encoding' } ]
55 verbose etag https://registry.npmjs.org/angular2-flash-messages from cache
56 verbose get saving angular2-flash-messages to /home/vishesh/.npm/registry.npmjs.org/angular2-flash-messages/.cache.json
57 verbose correctMkdir /home/vishesh/.npm correctMkdir already in flight; waiting
58 http 404 https://registry.npmjs.org/angularfirebase2
59 verbose headers { 'content-type': 'application/json',
59 verbose headers   'cache-control': 'max-age=0',
59 verbose headers   'content-length': '2',
59 verbose headers   'accept-ranges': 'bytes',
59 verbose headers   date: 'Mon, 03 Apr 2017 15:44:27 GMT',
59 verbose headers   via: '1.1 varnish',
59 verbose headers   age: '0',
59 verbose headers   connection: 'keep-alive',
59 verbose headers   'x-served-by': 'cache-iad2623-IAD',
59 verbose headers   'x-cache': 'MISS',
59 verbose headers   'x-cache-hits': '0',
59 verbose headers   'x-timer': 'S1491234267.257671,VS0,VE415',
59 verbose headers   vary: 'Accept-Encoding' }
60 silly get cb [ 404,
60 silly get   { 'content-type': 'application/json',
60 silly get     'cache-control': 'max-age=0',
60 silly get     'content-length': '2',
60 silly get     'accept-ranges': 'bytes',
60 silly get     date: 'Mon, 03 Apr 2017 15:44:27 GMT',
60 silly get     via: '1.1 varnish',
60 silly get     age: '0',
60 silly get     connection: 'keep-alive',
60 silly get     'x-served-by': 'cache-iad2623-IAD',
60 silly get     'x-cache': 'MISS',
60 silly get     'x-cache-hits': '0',
60 silly get     'x-timer': 'S1491234267.257671,VS0,VE415',
60 silly get     vary: 'Accept-Encoding' } ]
61 silly fetchPackageMetaData Error: Registry returned 404 for GET on https://registry.npmjs.org/angularfirebase2
61 silly fetchPackageMetaData     at makeError (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:302:12)
61 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:280:14)
61 silly fetchPackageMetaData     at Request._callback (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:210:14)
61 silly fetchPackageMetaData     at Request.self.callback (/usr/lib/node_modules/npm/node_modules/request/request.js:187:22)
61 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
61 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
61 silly fetchPackageMetaData     at Request.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:1048:10)
61 silly fetchPackageMetaData     at emitOne (events.js:96:13)
61 silly fetchPackageMetaData     at Request.emit (events.js:188:7)
61 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:969:12)
61 silly fetchPackageMetaData  error for angularfirebase2 { Error: Registry returned 404 for GET on https://registry.npmjs.org/angularfirebase2
61 silly fetchPackageMetaData     at makeError (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:302:12)
61 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:280:14)
61 silly fetchPackageMetaData     at Request._callback (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:210:14)
61 silly fetchPackageMetaData     at Request.self.callback (/usr/lib/node_modules/npm/node_modules/request/request.js:187:22)
61 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
61 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
61 silly fetchPackageMetaData     at Request.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:1048:10)
61 silly fetchPackageMetaData     at emitOne (events.js:96:13)
61 silly fetchPackageMetaData     at Request.emit (events.js:188:7)
61 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:969:12) pkgid: 'angularfirebase2', statusCode: 404, code: 'E404' }
62 silly rollbackFailedOptional Starting
63 silly rollbackFailedOptional Finishing
64 silly runTopLevelLifecycles Finishing
65 silly install printInstalled
66 verbose stack Error: Registry returned 404 for GET on https://registry.npmjs.org/angularfirebase2
66 verbose stack     at makeError (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:302:12)
66 verbose stack     at CachingRegistryClient.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:280:14)
66 verbose stack     at Request._callback (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:210:14)
66 verbose stack     at Request.self.callback (/usr/lib/node_modules/npm/node_modules/request/request.js:187:22)
66 verbose stack     at emitTwo (events.js:106:13)
66 verbose stack     at Request.emit (events.js:191:7)
66 verbose stack     at Request.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:1048:10)
66 verbose stack     at emitOne (events.js:96:13)
66 verbose stack     at Request.emit (events.js:188:7)
66 verbose stack     at IncomingMessage.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:969:12)
67 verbose statusCode 404
68 verbose pkgid angularfirebase2
69 verbose cwd /home/vishesh
70 error Linux 4.8.0-36-generic
71 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "firebase" "angularfirebase2" "angular2-flash-messages" "--save"
72 error node v6.10.1
73 error npm  v3.10.10
74 error code E404
75 error 404 Registry returned 404 for GET on https://registry.npmjs.org/angularfirebase2
76 error 404
77 error 404 'angularfirebase2' is not in the npm registry.
78 error 404 You should bug the author to publish it (or use the name yourself!)
79 error 404 Note that you can also install from a
80 error 404 tarball, folder, http url, or git url.
81 verbose exit

**Comment by KenanY** [comment]
There does not exist a package with the name `angularfirebase2`, hence the 404 error you are getting.

**Comment by VisheshSingh** [comment]
Thanks, found the issue: It should have been angularfire2 instead of angularfirebase2
