### ISSUE TITLE
binding.gyp + ignore-scripts + publish = broken?

### ISSUE THREAD

**Issue by bnoordhuis** [npm/npm#16243]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I published updates to three native modules earlier today (buffertools, heapdump, iconv) and all three exhibit the same issue: `npm install` doesn't invoke node-gyp to build them.  Previous releases work alright.

I discovered that the `.scripts` property in (e.g.) `.npm/heapdump/0.3.8/package/package.json` is an empty object, whereas in previous releases it has a 'test' and 'install' key (`"install": "node-gyp rebuild"`.)

Some sleuthing suggests the `npm.config.get('ignore-scripts')` check in lifecycle() in lib/lifecycle.js is responsible for that.  I had `ignore-scripts=true` set in my .npmrc; after removing that and publishing again, packages install okay again and the `.scripts` object is no longer empty.

Question 1: is this the intended behavior?  I sure hope not!

Question 2: is this documented anywhere?  I couldn't find anything in the documentation; the bug tracker didn't turn up anything either.

### supporting information:

 - `npm -v` prints: 4.2.0
 - `node -v` prints: v8.0.0-pre (today's master)
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: OS X, Linux
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by bnoordhuis** [comment]
Ping.  It's been three weeks and it doesn't look like this issue has even been triaged yet.

**Comment by legodude17** [comment]
Sorry, somehow this slipped through my notifications. I don't believe this is intended behavior, but I am not a dev.

**Comment by silentroach** [comment]
Nice way
