### ISSUE TITLE
npm dedupe makes  npm shrinkwrap uncallable

### ISSUE THREAD

**Issue by bkrrr** [npm/npm#16241]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [X] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
No node_modules folder is present

`npm install && npm shrinkwrap` 
works as expected

`npm install && npm dedupe &&  npm shrinkwrap` 
lists extraneous and missing packages

i removed all (except npm) global packages and clear cache, result is still the same 
#### How can the CLI team reproduce the problem?
package.json:
https://gist.github.com/bkrrr/902f29a6c7c8226fa5e00f137f91bb95

npm-debug-log:
https://gist.github.com/bkrrr/7c2cb3764250bf5d502f8a04a0f75d4b

### supporting information:

 - `npm -v` prints: 4.5.0
 - `node -v` prints: v7.7.1
 - `npm config get registry` prints:
npm info it worked if it ends with ok
npm info using npm@4.5.0
npm info using node@v7.7.1
http://registry.npmjs.org/
npm info ok
 - Windows, OS X/macOS, or Linux?: OS X
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by black-snow** [comment]
Dunno if my issue is the same but I first ran `npm dedupe` and then `npm shrinkwrap`. Result:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'shrinkwrap' ]
2 info using npm@5.0.3
3 info using node@v8.1.0
4 info lifecycle xyz@0.10.4~preshrinkwrap: xyz@0.10.4
5 silly lifecycle xyz@0.10.4~preshrinkwrap: no script for preshrinkwrap, continuing
6 verbose stack TypeError: Cannot read property 'type' of undefined
6 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\shrinkwrap.js:111:12
6 verbose stack     at Array.forEach (native)
6 verbose stack     at shrinkwrapDeps (C:\Program Files\nodejs\node_modules\npm\lib\shrinkwrap.js:103:97)
6 verbose stack     at treeToShrinkwrap (C:\Program Files\nodejs\node_modules\npm\lib\shrinkwrap.js:93:5)
6 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\shrinkwrap.js:76:21
6 verbose stack     at done (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:136:5)
6 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:7:26)
6 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:18:7
6 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:333:20
6 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
6 verbose stack     at FSReqWrap.oncomplete (fs.js:152:21)
7 verbose cwd E:\_user\Desktop\xyz\xyz
8 verbose Windows_NT 10.0.15063
9 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "shrinkwrap"
10 verbose node v8.1.0
11 verbose npm  v5.0.3
12 error Cannot read property 'type' of undefined
13 verbose exit [ 1, true ]
```

**Comment by legodude17** [comment]
@bkrrr Does this occur on the latest version of npm?

**Comment by black-snow** [comment]
There's a bot that automatically closes issues that you didn't look at within a week? w t f
Sure, we don't pay for this but it's like: "Dear customer, I didn't find the time to look at your broken car so please take it home again. Feel free to come back if you still have issues."

**Comment by Nagarjuna32** [comment]
I am also getting "**Cannot read property 'type' of undefined**" when I run npm install. I tried mentioned all options. Any suggestions? 
_13955 info lifecycle undefined~preshrinkwrap: undefined
13956 silly lifecycle undefined~preshrinkwrap: no script for preshrinkwrap, continuing
13957 verbose stack TypeError: Cannot read property 'type' of undefined
13957 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\shrinkwrap.js:111:12
13957 verbose stack     at Array.forEach (native)_
