### ISSUE TITLE
npm update failed with symbolic-linked node-module folder

### ISSUE THREAD

**Issue by andrewjavao** [npm/npm#16249]
#### I'm opening this issue because:
 - npm is doing something I don't understand.

#### What's going wrong?
npm seems to fail when doing `npm update` on a node-module folder which is a symbolic link, and `npm install` produce a 'invalid' library when runing in on it. Problem is, I'm wondering if this is the way npm is designed(so i need to follow the rule), or this is something I did wrong.

I have website projects built on npm and webpack, and a integrated deploy process on a linux server to build and publish these projects. This deploy process is basicly shell commands that invokes `npm install`, `npm update`, `npm run` and so on.
Because there're several projects with the same npm libraries needed and configurated, so in order to save disk space and save time when new project is added, so I created a common(global) node-module folder, and links to this folder in each project, so there's no copies of the same node-module folder, and it helps to speed up the deploy process.
Recently I update some of the library version by modifing package.json file in those projects. When i deploying them, npm told me update cann't be done in node-module that is a symbolic link, like:
` npm update
 npm WARN update-linked node_modules/element-ui needs updating to 1.2.7 from 1.2.5 but we can't, as it's a symlink
`
and `npm install` is also wired, if i run `npm install` inside project folder(in which node-module folder is a symbolic link to the common one), it ends up like:
` npm install
 vue@1.0.0 /home/admin/deploy/vpc-env/rscloud/kits/local_vue-webpack/dev
 └── element-ui@1.2.5  invalid
`
The library is installed, i guess, because the content is there and that `invalid` seems no harm to anything(it can be used and behaves like other valid libraries in my process), but `invalid` is still a pain.

#### How to reproduce the problem?
The main folder structure is like this:

root/
 - node_modules/  (the common folder)
 - projects
     - project_one
         - node_modules (a link to the common one)
         - package.json
     - project_two
         - node_modules (a link to the common one)
         - package.json
     - project_three
         - node_modules (a link to the common one)
         - package.json

if I run `npm install` or `npm update` in 'root/' folder, everything is ok;
if I run `npm install` in project_one(or two, or three), the library installed ends up to be tagged 'invalid' when `npm list`
if I run `npm update` in project_one(or two, or three), npm refuse to do so.

### Here is environment information:
 - OS: Linux, CentOS 7
 - `npm -v` prints: 3.8.9
 - `node -v` prints: v6.2.0
 - `npm config get registry` prints:https://registry.npm.taobao.org/

**Comment by AnthemiusGuo** [comment]
I have the same problem, But this issue is not even readed by the team....
