### ISSUE TITLE
E404 error on install - Incorrect registry ur;

### ISSUE THREAD

**Issue by leanna-norwood** [npm/npm#16252]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I've tried completely removing all instances of node and reinstalling but still run into this error when installing NPM on my project:

`npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code E404
npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/gulp-runsequence/node-sass/node-sass/gulp-cli/gulp-cli/gulp-cli/gulp-cli/gulp-cli`

### supporting information:

 - `npm -v` prints: 3.10.10
 - `node -v` prints: v6.10.2
 - `npm config get registry` prints: https://registry.npmjs.org/gulp-runsequence/node-sass/node-sass/gulp-cli/gulp-cli/gulp-cli/gulp-cli
 - Windows, OS X/macOS, or Linux?: OS X Sierra

**Comment by KenanY** [comment]
@leanna-norwood Could you try doing:

```
npm config set registry https://registry.npmjs.org
```

**Comment by leanna-norwood** [comment]
Thank you!
