### ISSUE TITLE
 Refusing to install angular2-google-map-auto-complete as a dependency of itself

### ISSUE THREAD

**Issue by kunalpawar** [npm/npm#16254]
Refusing to install angular2-google-map-auto-complete as a dependency of itself

**Comment by KenanY** [comment]
@kunalpawar Make sure that the `"name"` field in your `package.json` is not the same as the name of any dependency you are installing. Make it more unique! :)

Closing since this is intended behavior of `npm`, but let me know if you need further help.

**Comment by kunalpawar** [comment]
thanks its work
