### ISSUE TITLE
npm install 401 Unauthorized error

### ISSUE THREAD

**Issue by ramaduraiu** [npm/npm#16251]
am trying install npm using  npm install command . But am getting 401 error. I have written my npm-debug.log file . Please check and do the needful.

** npm-debug.log file** 

[npm-debug -log.txt](https://github.com/npm/npm/files/895347/npm-debug.-log.txt)

**Comment by jbcpollak** [comment]
@ramaduraiu can you try using a newer version of npm by running `npm i -g npm`?

**Comment by apdaros** [comment]
@ramaduraiu @jbcpollak I got the same issue with npm `5.0.0`. It may relate to #16528

**Comment by gnz00** [comment]
I am also having this issue, getting 401 Unauthorized trying to auth against Artifactory. When I downgraded to npm@4.6 I was able to authenticate with the same .npmrc.

**Comment by zkat** [comment]
Closing as duplicate of https://github.com/npm/npm/issues/16528
