### ISSUE TITLE
C:\>npm install coredova npm ERR! Windows_NT 10.0.14393

### ISSUE THREAD

**Issue by sarathydinesh** [npm/npm#16259]
#### I'm opening this issue because:

How can i fix this issue??

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "coredova"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/coredova
npm ERR! 404
npm ERR! 404  'coredova' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\DINU FRAUD\npm-debug.log

**Comment by KenanY** [comment]
@sarathydinesh Looks like you have a typo, you are trying to install `coredova`, which is not a package in the registry. Perhaps you mean to install `cordova`?

**Comment by sarathydinesh** [comment]
facing same issue 

C:\Users\DINU FRAUD>npm install -g cordova
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10

npm ERR! shasum check failed for C:\Users\DINUFR~1\AppData\Local\Temp\npm-9508-280f7ebc\registry.npmjs.org\npm\-\npm-2.15.12.tgz
npm ERR! Expected: df7c3ed5a277c3f9d4b5d819b05311d10a200ae6
npm ERR! Actual:   36458b7cdb1965428c42fc122f244872f322920d
npm ERR! From:     https://registry.npmjs.org/npm/-/npm-2.15.12.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by KenanY** [comment]
@sarathydinesh I don't understand, your issue looks different now. What do you mean that it's the same?

Anyways, could you first try [updating `npm`](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows)?

**Comment by sarathydinesh** [comment]
thanks kenan , npm updated , now cordova installed
