### ISSUE TITLE
angular 2 load google maps api multiple components

### ISSUE THREAD

**Issue by kunalpawar** [npm/npm#16256]
angular 2 load google maps apilocation autocomplete working only on app.component.ts
it fail to load on another component getting Google Maps API error: MissingKeyMapError error
how to load it on  multiple componenet

**Comment by KenanY** [comment]
@kunalpawar I suggest taking this issue to a more appropriate support forum, such as StackOverflow. We try to reserve this issue tracker to just `npm` issues.
