### ISSUE TITLE
npm install not working

### ISSUE THREAD

**Issue by chaitalipatil** [npm/npm#16253]
#### I'm opening this issue because:

  - [ ] Not able to run 'npm install' command.

#### What's going wrong?
  - I am using node version v7.8.0 and npm version 4.2.0
 - whenever I run 'npm install' it gives error like 

![screenshot 6](https://cloud.githubusercontent.com/assets/16894779/24698884/d7868258-1a0f-11e7-8ba1-f9a8e55bea19.png)

### supporting information:

 - `npm -v` :  v7.8.0
 - `node -v` : 4.2.0
 - `npm config get registry` : https://registry.npmjs.org/

 - Windows 

Not able to find error behind this. Also help me to find error_log file for debugging purpose.

**Comment by BRAEIKMiled** [comment]
@chaitalipatil try "rm -rf node_modules" and "npm cache clean" and npm config set registry "http://registry.npmjs.org/" then sudo npm install npm -g 
and retry your command

**Comment by chaitalipatil** [comment]
Thanks @BRAEIKMiled , but it again gives the same error with different error-code.

![screenshot 7](https://cloud.githubusercontent.com/assets/16894779/24738546/f4ad0a24-1ab3-11e7-82b6-a93030ef4a94.png)

**Comment by chaitalipatil** [comment]
Help me into this.
I am using Windows 10 64bit machine.
In Laravel project I am trying to run command 'npm install' but it gives error and 'node_modules' folder is not creating

See the image: 

![image](https://cloud.githubusercontent.com/assets/16894779/24862046/a908fb10-1e18-11e7-8630-5ae2e542b195.png)
