### ISSUE TITLE
np install not working 

### ISSUE THREAD

**Issue by BRAEIKMiled** [npm/npm#16255]
![capture d ecran 2017-04-05 a 14 18 25](https://cloud.githubusercontent.com/assets/15521575/24705163/fe9c3ba8-1a0a-11e7-8cbe-5a4515b0a70a.png)

**Comment by KenanY** [comment]
@BRAEIKMiled Could you upload the `npm-debug.log` file to <https://gist.github.com/> and post the link here?

**Comment by BRAEIKMiled** [comment]
https://gist.github.com/BRAEIKMiled/620adaab27af01a246ed38d95f8a6910

**Comment by BRAEIKMiled** [comment]
@KenanY I tried "rm -rf node_modules" and "npm cache clean" and npm config set registry "http://registry.npmjs.org/" then sudo npm install npm -g 
and now it works

**Comment by KenanY** [comment]
Gonna close as resolved then. In the log, you're using a non-default registry which apparently was not accepting your requests for whatever reason. I presume that is why changing your registry to the default resolved your issue.
