### ISSUE TITLE
npm run deploy

### ISSUE THREAD

**Issue by NathanDing** [npm/npm#16260]
D:\WebstormProjects\dva-quickstart>npm run deploy
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "deploy"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10

npm ERR! missing script: deploy
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\WebstormProjects\dva-quickstart\npm-debug.log

**Comment by NathanDing** [comment]
my nodejs path ：
2017/04/06  09:06    <DIR>          .
2017/04/06  09:06    <DIR>          ..
2017/04/04  09:11        18,543,768 node.exe
2016/12/22  18:01               702 nodevars.bat
2017/04/04  08:57             8,997 node_etw_provider.man
2017/04/06  09:06    <DIR>          node_modules
2016/12/22  18:01             4,974 node_perfctr_provider.man
2016/11/16  19:45               867 npm
2016/11/16  19:45               483 npm.cmd

**Comment by KenanY** [comment]
Hello! So, the way `npm run deploy` works is that it looks in your current `package.json` for a defined `"deploy"` [script](https://docs.npmjs.com/misc/scripts), and then runs that. The error message you're seeing is trying to tell you that you have not defined a `"deploy"` script in your `package.json`, hence `npm run deploy` has no idea what you want it to do.

To solve this issue, all you have to do is add a new script to your `package.json`. It might look something like this, for example:

``` json
{
  "name": "package-name",
  "version": "1.0.0",
  "description": "package description",
  "scripts": {
    "deploy": "node my-deploy-file.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {},
  "devDependencies": {}
}
```

Note how this `package.json` has a `"deploy"` script that runs `node my-deploy-file.js`. You'll definitely want to change the command to whatever is most appropriate for your project.

Let me know if you run into any further `npm` issues :)

**Comment by KenanY** [comment]
Closing due to no reply.
