### ISSUE TITLE
Windows 10, infinite loop running NPM

### ISSUE THREAD

**Issue by jscsharp** [npm/npm#16269]
I have issue with running npm. I installed v7.8.0 ( nodejs) in Windows 10 , 64 bit.
when running "g:\home2>npm" from command line.
It just hang and never return. I fired up ProcessMon from Sysinternal and it shows, this:
![image](https://cloud.githubusercontent.com/assets/896560/24761171/77f08b8c-1a9f-11e7-8b13-1b605bceee68.png)

Thanks

**Comment by jscsharp** [comment]
I debugged the npm code. It seems, it related to "prefix"
and end up having this path in the code:
"g:\home2\apps\debugging_NPM\'G:\home2\apps\AppData\Roaming\npm'"
My working directory is  "g:\home2\apps\debugging_NPM"
which has NPM code for debuggin.
and "G:\home2\apps\AppData\Roaming\npm" is been set in Windows PATH.
So it  goes to recursive loop in:
function mkdirP (p, opts, f, made) {

I am sure not yet, where it needs to fix it.

**Comment by jscsharp** [comment]
Finally, I found  the issue, somehow,I had single quotes inside the double quotes in the .npmrc file, in
c:\users\\{username}\ .npmrc, as follows:
prefix="'G:\\home2\\apps\\AppData\\Roaming\\npm'"
Most likely, I set the wrong value via command line, while testing it.
So this causes in line 399 in  npm\lib\config\core.js which is:
  f = path.resolve(f)
to make the path invalid and goes to infinite loop later on in function mkdirP (p, opts, f, made) .

**How to replicate the issue**:

1) add single  quotes  in double quotes for string "prefix" ,like:
prefix="'G:\\home\\apps\\AppData\\Roaming\\npm'"
in c:\users\{username}\ .npmrc.

then run : npm -v, it will never return.

**Comment by SOLenG** [comment]
It's very strange, the solution for me is : 
prefix="G:\\\\home\\\\apps\\\\AppData\\\\Roaming\\\\npm"
