### ISSUE TITLE
npm generates too many connections to HTTP proxy (maxsockets does not work)

### ISSUE THREAD

**Issue by kosorinsky** [npm/npm#16263]
**Version**: 3.10.10 also 4.2.0

**Problem description**: npm install opens too many (hundreds) connections to HTTP proxy which causes problems in our infrastructure. Parameter/configuration maxsockets=10 is used, but it is ignored for proxy requests. When downloading packages directly from internet (without --proxy or --https-proxy parameter), connections count is properly limited to 10 as requested by maxsockets parameter.

**Comment by mk-pmb** [comment]
Anyone else encountering this: Remember that `maxsockets` is per host, so it should be waaay lower than the number of free connection slots your proxy usually has available. At least if you want YouTube and Github while npm is downloading.

**Comment by mk-pmb** [comment]
Update: Nope, wasn't due to weak proxy. The facht npm succeeded after I lowered the maxsockets had other reasons, probably npm's cache. I'll open a new issue.

**Comment by eugenedw** [comment]
I'm having the same issue. We're working behind a proxy server and not being able to set this connection limit is maddening. I'm requesting the matter remain open until resolved.

**Comment by FritzHerbers** [comment]
Sitting behind a double hop proxy (company proxy and external proxy) using stunnel to connect with bower/npm. 

Since a week we moved development instead of bower to npm and started noticing proxy problems.
On the second external proxy we noticed over 256 httpd workers running.

With the following additional stunnel settings npm runs fine:

```
socket = l:SO_LINGER=1:10
to close local connections (npm)

TIMEOUTidle = 10
to close the proxy connections (reducing the httpd workers quicker)
```

Both settings where needed, implying that connections are also not correctly closed.

Here is the stunnel configuration used, which could be interesting to try with npm
```
pid = /var/run/stunnel.pid
socket = l:TCP_NODELAY=1
socket = r:TCP_NODELAY=1
client = yes
debug = 0
foreground = no

socket = l:SO_LINGER=1:10

[http]
accept = localhost:9000
connect = firstproxy:8080
protocol = connect
protocolHost = secondproxy:443

TIMEOUTidle = 10
```

**Comment by tareksha** [comment]
this is an issue in `pacote` and the proxy agents it uses, confirmed by the maintainer https://github.com/zkat/pacote/issues/138

**Comment by cerisara** [comment]
I face the same issue with privoxy + npm, and it's a real pain, making npm unusable behind privoxy.
I don't have any tunnels so the above solution is not applicable.
The only viable solution is to add an option to npm to limit the number of connections that works.
Thanks !

**Comment by mk-pmb** [comment]
@cerisara as a temporary workaround, try npm <--> [tcpfwd-maxconc-pmb](https://www.npmjs.com/package/tcpfwd-maxconc-pmb) <--> privoxy.

**Comment by chihane** [comment]
@cerisara setting npm's proxy fixes this issue for me, try `npm config set proxy "http://127.0.0.1:{privoxy_port}"`

**Comment by tareqhs** [comment]
the issue was found in the proxy agent.
fix: https://github.com/TooTallNate/node-agent-base/pull/18

**Comment by tareksha** [comment]
fixed
https://github.com/TooTallNate/node-agent-base/pull/18
