### ISSUE TITLE
Npm start not working

### ISSUE THREAD

**Issue by TAnsurkar** [npm/npm#16279]
I am getting the following error

npm start
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nod
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9

npm ERR! missing script: start
npm ERR!

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\tejasvi.ansurkar\Desktop\reactApp\npm-debug.log

**Comment by KenanY** [comment]
@TAnsurkar Hello! So, the way `npm start` works is that it looks in your current `package.json` for a defined `"start"` [script](https://docs.npmjs.com/misc/scripts), and then runs that. The error message you're seeing is trying to tell you that you have not defined a `"start"` script in your `package.json`, hence `npm start` has no idea what you want it to do.

To solve this issue, all you have to do is add a new script to your `package.json`. It might look something like this, for example:

``` json
{
  "name": "package-name",
  "version": "1.0.0",
  "description": "package description",
  "scripts": {
    "start": "node lib/server.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {},
  "devDependencies": {}
}
```

Note how this `package.json` has a `"start"` script that runs `node lib/server.js`. You'll definitely want to change the command to whatever is most appropriate for your project.

Let me know if you run into any further `npm` issues :)

**Comment by TAnsurkar** [comment]
Thank you @KenanY After adding the script to package.json:
{
  "name": "package.json",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "script":{
 "start": "node lib/server.js"
},
  "author": "",
  "license": "ISC",
  "dependencies": {
    "react": "^15.4.2",
    "react-dom": "^15.4.2"
  }
}

 I am still getting the following error:

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9

npm ERR! missing script: start
npm ERR!

**Comment by KenanY** [comment]
@TAnsurkar Make sure you call it `"scripts"` (plural) instead of `"script"` singular. See my example above.

**Comment by KenanY** [comment]
Closing due to no reply after a month.
