### ISSUE TITLE
NPM doesn't hoist hard dependencies of dependencies with binaries

### ISSUE THREAD

**Issue by probablyup** [npm/npm#16271]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I have a dependency that has `eslint` listed as a hard dependency, but after `npm install`, `eslint` is not added to the `node_modules/.bin` folder and is unusable without unsafely calling into the eslint directory itself.

#### How can the CLI team reproduce the problem?

Add a dependency to `package.json` in a project that lists `eslint` as a "dependency", then try to use it in a npm script.

### supporting information:

 - `npm -v` prints: 4.1.2
 - `node -v` prints: 7.5.0

**Comment by KenanY** [comment]
Could I see an example `package.json` for this (preferably as minimal as possible)?

**Comment by probablyup** [comment]
Did a minimal repro and it turns out this is a yarn bug, false alarm!
