### ISSUE TITLE
npm ERR! Windows_NT 10.0.14393 npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\YK\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "update" "-g" "ionic" npm ERR! node v6.10.2 npm ERR! npm  v3.10.10

### ISSUE THREAD

**Issue by chenzhili** [npm/npm#16277]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@chenzhili Hello! Could you please at least provide your `npm-debug.log` file? You can upload it to <https://gist.github.com/> and post a link to it here.

**Comment by StrohmerFranz** [comment]
I have the same problem. Please could you help me?

C:\Users\xxxxxxxx>npm install --global node-gyp
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x8
6)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--global" "node-gyp"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5

npm ERR! Cannot read property 'path' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\xxxxxxxx\npm-debug.log

[npm-debug.log.docx](https://github.com/npm/npm/files/908091/npm-debug.log.docx)

**Comment by KenanY** [comment]
@StrohmerFranz Can you upload the log as a plaintext file to <https://gist.github.com/> and link it here instead of converting it? Thanks!

**Comment by StrohmerFranz** [comment]
Hello Yildirim,

here is the log

Thanks a lot

Sincerly
Franz

Von: Kenan Yildirim [mailto:notifications@github.com]
Gesendet: Sonntag, 9. April 2017 16:13
An: npm/npm
Cc: Strohmer, Franz (DF MC GMC R&D SWRT 2); Mention
Betreff: Re: [npm/npm] npm ERR! Windows_NT 10.0.14393 npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\YK\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "update" "-g" "ionic" npm ERR! node v6.10.2 npm ERR! npm v3.10.10 (#16277)


@StrohmerFranz<https://github.com/StrohmerFranz> Can you upload the log as a plaintext file to https://gist.github.com/ and link it here instead of converting it? Thanks!

**Comment by KenanY** [comment]
@StrohmerFranz Sorry, I'm gonna need a <https://gist.github.com/> link to the log (as mentioned aboved).

**Comment by StrohmerFranz** [comment]
How can I create such a link?

Von: Kenan Yildirim [mailto:notifications@github.com]
Gesendet: Montag, 10. April 2017 13:22
An: npm/npm
Cc: Strohmer, Franz (DF MC GMC R&D SWRT 2); Mention
Betreff: Re: [npm/npm] npm ERR! Windows_NT 10.0.14393 npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\YK\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "update" "-g" "ionic" npm ERR! node v6.10.2 npm ERR! npm v3.10.10 (#16277)


@StrohmerFranz<https://github.com/StrohmerFranz> Sorry, I'm gonna need a https://gist.github.com/ link to the log (as mentioned aboved).

**Comment by KenanY** [comment]
@chenzhili Go to <https://gist.github.com/>, paste in the log, click "create public gist", copy URL and post it here.

**Comment by StrohmerFranz** [comment]
https://gist.github.com/anonymous/3e2aaf845436e0ef778971b61bfa5f37

Von: Kenan Yildirim [mailto:notifications@github.com]
Gesendet: Montag, 10. April 2017 13:39
An: npm/npm
Cc: Strohmer, Franz (DF MC GMC R&D SWRT 2); Mention
Betreff: Re: [npm/npm] npm ERR! Windows_NT 10.0.14393 npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\YK\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "update" "-g" "ionic" npm ERR! node v6.10.2 npm ERR! npm v3.10.10 (#16277)


@chenzhili<https://github.com/chenzhili> Go to https://gist.github.com/, paste in the log, click "create public gist", copy URL and post it here.

**Comment by KenanY** [comment]
@StrohmerFranz Log indicates that the requests to the npm registry are timing out, which means that you're facing some sort of internet connection problem. Maybe you are behind a proxy or firewall?

**Comment by StrohmerFranz** [comment]
Yes I call the npm behid a Poxy.
In addition I’m working over VPN connection from my home to my office and then from there going through the proxy.
That’s perhaps a little too much.

I copied and older node-gyp installation from my older NoteBook to my new NoteBook, that I’m going to install…

That works …

Thank you.

Sincerely
Franz




Von: Kenan Yildirim [mailto:notifications@github.com]
Gesendet: Montag, 10. April 2017 13:52
An: npm/npm
Cc: Strohmer, Franz (DF MC GMC R&D SWRT 2); Mention
Betreff: Re: [npm/npm] npm ERR! Windows_NT 10.0.14393 npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\YK\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "update" "-g" "ionic" npm ERR! node v6.10.2 npm ERR! npm v3.10.10 (#16277)


@StrohmerFranz<https://github.com/StrohmerFranz> Log indicates that the requests to the npm registry are timing out, which means that you're facing some sort of internet connection problem. Maybe you are behind a proxy or firewall?

**Comment by chaitanyaphanikumar** [comment]
@StrohmerFranz / @KenanY -  I still have the same issue. In my personal PC i'm able to install Ionic, but through office laptop, I'm not.  Can you please let me know what configuration I need to do for my office laptop ?

**Comment by chaitanyaphanikumar** [comment]
Here is the log FYR..

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'ionic',
1 verbose cli   'cordova' ]
2 info using npm@4.2.0
3 info using node@v7.9.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData ionic
8 silly fetchPackageMetaData cordova
9 silly fetchNamedPackageData ionic
10 silly mapToRegistry name ionic
11 silly mapToRegistry using default registry
12 silly mapToRegistry registry https://registry.npmjs.org/
13 silly mapToRegistry data Result {
13 silly mapToRegistry   raw: 'ionic',
13 silly mapToRegistry   scope: null,
13 silly mapToRegistry   escapedName: 'ionic',
13 silly mapToRegistry   name: 'ionic',
13 silly mapToRegistry   rawSpec: '',
13 silly mapToRegistry   spec: 'latest',
13 silly mapToRegistry   type: 'tag' }
14 silly mapToRegistry uri https://registry.npmjs.org/ionic
15 silly fetchNamedPackageData cordova
16 silly mapToRegistry name cordova
17 silly mapToRegistry using default registry
18 silly mapToRegistry registry https://registry.npmjs.org/
19 silly mapToRegistry data Result {
19 silly mapToRegistry   raw: 'cordova',
19 silly mapToRegistry   scope: null,
19 silly mapToRegistry   escapedName: 'cordova',
19 silly mapToRegistry   name: 'cordova',
19 silly mapToRegistry   rawSpec: '',
19 silly mapToRegistry   spec: 'latest',
19 silly mapToRegistry   type: 'tag' }
20 silly mapToRegistry uri https://registry.npmjs.org/cordova
21 verbose request uri https://registry.npmjs.org/ionic
22 verbose request no auth needed
23 info attempt registry request try #1 at 10:11:51 AM
24 verbose request id bf0a96050b0cbeed
25 http request GET https://registry.npmjs.org/ionic
26 verbose request uri https://registry.npmjs.org/cordova
27 verbose request no auth needed
28 info attempt registry request try #1 at 10:11:51 AM
29 http request GET https://registry.npmjs.org/cordova
30 info retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.32.162:443
31 info retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.32.162:443
32 info attempt registry request try #2 at 10:12:23 AM
33 http request GET https://registry.npmjs.org/ionic
34 info attempt registry request try #2 at 10:12:23 AM
35 http request GET https://registry.npmjs.org/cordova
36 info retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.32.162:443
37 info retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.32.162:443
38 info attempt registry request try #3 at 10:13:44 AM
39 http request GET https://registry.npmjs.org/cordova
40 info attempt registry request try #3 at 10:13:44 AM
41 http request GET https://registry.npmjs.org/ionic
42 silly fetchPackageMetaData Error: connect ETIMEDOUT 151.101.32.162:443
42 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1050:11)
42 silly fetchPackageMetaData     at exports._exceptionWithHostPort (util.js:1073:20)
42 silly fetchPackageMetaData     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
42 silly fetchPackageMetaData  error for cordova { Error: connect ETIMEDOUT 151.101.32.162:443
42 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1050:11)
42 silly fetchPackageMetaData     at exports._exceptionWithHostPort (util.js:1073:20)
42 silly fetchPackageMetaData     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
42 silly fetchPackageMetaData   code: 'ETIMEDOUT',
42 silly fetchPackageMetaData   errno: 'ETIMEDOUT',
42 silly fetchPackageMetaData   syscall: 'connect',
42 silly fetchPackageMetaData   address: '151.101.32.162',
42 silly fetchPackageMetaData   port: 443 }
43 silly fetchPackageMetaData Error: connect ETIMEDOUT 151.101.32.162:443
43 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1050:11)
43 silly fetchPackageMetaData     at exports._exceptionWithHostPort (util.js:1073:20)
43 silly fetchPackageMetaData     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
43 silly fetchPackageMetaData  error for ionic { Error: connect ETIMEDOUT 151.101.32.162:443
43 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1050:11)
43 silly fetchPackageMetaData     at exports._exceptionWithHostPort (util.js:1073:20)
43 silly fetchPackageMetaData     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
43 silly fetchPackageMetaData   code: 'ETIMEDOUT',
43 silly fetchPackageMetaData   errno: 'ETIMEDOUT',
43 silly fetchPackageMetaData   syscall: 'connect',
43 silly fetchPackageMetaData   address: '151.101.32.162',
43 silly fetchPackageMetaData   port: 443 }
44 silly rollbackFailedOptional Starting
45 verbose stack TypeError: Cannot read property 'path' of null
45 verbose stack     at Installer.rollbackFailedOptional (C:\Program Files\nodejs\node_modules\npm\lib\install.js:511:29)
45 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
45 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
45 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:18:7
45 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install.js:337:5
45 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
45 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
45 verbose stack     at chain (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
45 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install.js:294:5
45 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:16:22
46 verbose cwd C:\
47 error Windows_NT 6.1.7601
48 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ionic" "cordova"
49 error node v7.9.0
50 error npm  v4.2.0
51 error Cannot read property 'path' of null
52 error If you need help, you may report this error at:
52 error     <https://github.com/npm/npm/issues>
53 verbose exit [ 1, true ]

**Comment by legodude17** [comment]
The log indicates it is a problem with your proxy or internet.

**Comment by devjavedmohd** [comment]
Hi I have same issue...

$ yarn test
yarn test v0.23.4
$ npm run eslint && npm run mocha

> backend@0.0.0 eslint D:\study\project\backend
> eslint src/. test/. --config .eslintrc.json


> backend@0.0.0 mocha D:\study\project\backend
> mocha test/ --recursive

You are using the default filter for the contact service. For more information about event filters see https://docs.feathersjs.com/api/events.html#event-filtering


  Feathers application tests
    √ starts and shows the index page
    404
      √ shows a 404 HTML page
      √ shows a 404 JSON error without stack trace

  'contact' service
    1) registered the service


  3 passing (82ms)
  1 failing

  1) 'contact' service registered the service:
     AssertionError: Registered the service
      at Context.it (test\services\contact.test.js:8:12)




npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "mocha"
npm ERR! node v7.1.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! backend@0.0.0 mocha: `mocha test/ --recursive`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the backend@0.0.0 mocha script 'mocha test/ --recursive'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the backend package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     mocha test/ --recursive
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs backend
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls backend
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\study\project\backend\npm-debug.log
error Command failed with exit code 1.

**Comment by legodude17** [comment]
That is a problem with your tests, it has nothing to do with `npm`.

**Comment by river8806** [comment]
I have the same question  can you help me ?

**Comment by PushpaKamatham** [comment]
I got the same.
Solution plz....

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\program files\\nodejs\\node.exe" "C:\\program files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "express"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! code ECONNRESET

npm ERR! network tunneling socket could not be established, statusCode=407
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:

**Comment by AndrewHani** [comment]
I'm new to npm and I'm trying to adduser, except that I have several error
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "adduser"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code SELF_SIGNED_CERT_IN_CHAIN

npm ERR! self signed certificate in certificate chain
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     c:\Users\andrew.gorgui\npm-debug.log

[npm-debug.log](https://github.com/npm/npm/files/1449745/npm-debug.log)

**Comment by emmanuelmezie** [comment]
Hi,
I got the same problem.

here is my log url  https://gist.github.com/emmanuelmezie/a91c059e8512d5121a14ad2504316b5c

**Comment by tapanbanker** [comment]
I am also having the same issue. 
`14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:891:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid genesis-api@0.3.1
16 verbose cwd C:\Users\592190\githubrepo\new-genesis\genesis-api-published
17 error Windows_NT 10.0.10586
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v6.11.0`
