### ISSUE TITLE
Dev dependencies not installing for local dependencies

### ISSUE THREAD

**Issue by Jameskmonger** [npm/npm#16272]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_): Possible gap in logic

#### What's going wrong?

Dev dependencies are not installed for local dependencies, causing issues with `prepare` steps.

#### How can the CLI team reproduce the problem?

1. Create a package (`package-one`) with a dev dependency which gives you a CLI command (e.g. `typescript`)
2. In `package-one`, create a `prepare` script using this CLI command
3. Create another package (`package-two`) and install `package-one` as a local dependency
4. Ensure `node_modules` is deleted for both packages
5. Attempt to run `npm install` in `package-two` - it will fail because the dev dependency is not installed for the prepare step.

See https://github.com/Jameskmonger/npm-dependency-install-issue for a repo that you can clone and run immediately.

### supporting information:

 - `npm -v` prints: `3.10.9`
 - `node -v` prints: `7.1.0`
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?: `Ubuntu 16.04`
 - Network issues:
   - Geographic location where npm was run: London, UK
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by Jameskmonger** [comment]
I have updated this issue to make it about `preinstall` rather than `prepublish` - the issue still applies, however.

**Comment by renkei** [comment]
The problem still exists. It can easily reproduced with these steps:
1. Create a package.json with dependencies and also devDependencies for project 1
2. Create a second package.json for project 2 and copy project 1 into a sub-folder of project 2 and insert project 1 as local dependency of project 2 ( e.g. "dependencies": { "project1": "file:project1" } )
3. execute npm install for project 2

Result: dependencies of project 1 are installed, but devDependencies of project 1 are missing

**Comment by stoil** [comment]
I am facing the exact same issue right now and I am not able to deploy my app since the build on azure fails complaining about not being able to run prebulish command in the locally referenced package.

npm install fails locally 
Windows 10
npm -v 5.6.0
node -v 8.11.1

and also on azure where 
npm -v 3.10.8
node -v 6.9.1

@renkei Did you manage to solve your problem somehow?
