### ISSUE TITLE
npm  cannot  find  package.json

### ISSUE THREAD

**Issue by qingfegnxulai** [npm/npm#16288]
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "D:\\soft\\node.js\\node.exe" "D:\\soft\\node.js\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "webpack"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! path D:\nodejs\lib\npm\webpack
npm ERR! code EISDIR
npm ERR! errno -4068
npm ERR! syscall open

npm ERR! eisdir EISDIR: illegal operation on a directory, open 'D:\nodejs\lib\npm\webpack'
npm ERR! eisdir This is most likely not a problem with npm itself
npm ERR! eisdir and is related to npm not being able to find a package.json in
npm ERR! eisdir a package you are trying to install.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\nodejs\lib\npm\cnpm\4.5.0\package\npm-debug.log

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
Could you try doing `npm install -g webpack@latest` instead?

**Comment by KenanY** [comment]
Closing due to no reply after a month.
