### ISSUE TITLE
npm install fail

### ISSUE THREAD

**Issue by GZWZC** [npm/npm#16281]
bash-3.2# rm -f/node_modules
rm: illegal option -- /
usage: rm [-f | -i] [-dPRrvW] file ...
       unlink file
bash-3.2# rm -f /node_modules
bash-3.2# npm cache clean
bash-3.2# npm install
npm ERR! git clone --template=/Users/app/.npm/_git-remotes/_templates --mirror git@github.com:lepture/editor.git /Users/app/.npm/_git-remotes/git-github-com-lepture-editor-git-8a0fa90e: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
npm WARN deprecated babel-preset-latest@6.24.0: 💥  preset-latest accomplishes the same task as babel-preset-env. 🙏  Please install it with 'npm install babel-preset-env --save-dev'. '{ "presets": ["latest"] }' to '{ "presets": ["env"] }'. For more info, please check the docs: http://babeljs.io/docs/plugins/preset-env 👌. And let us know how you're liking Babel at @babeljs on 🐦
npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! code 1

npm ERR! Command failed: git clone --template=/Users/app/.npm/_git-remotes/_templates --mirror git@github.com:lepture/editor.git /Users/app/.npm/_git-remotes/git-github-com-lepture-editor-git-8a0fa90e
npm ERR! xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /wzc/小肚鱼/xiaoduyu.com-master/npm-debug.log
bash-3.2#

**Comment by GZWZC** [comment]
https://gist.github.com/GZWZC/896324530be6f4859fc2546e7574c63c  

this is my npm-debug.log,pleased help me

**Comment by duddu** [comment]
Hi @GZWZC, which version of Mac OS X are you using? 
The error happens on git clone; what do you get running `git --version`?  
Can you try to run `xcode-select --install` and try again?

**Comment by GZWZC** [comment]
@duddu mac osx 10.12 sierra

**Comment by Adhiii** [comment]
I want to install express in nodejs...While installing i had some error.so while solving that,I need to use npmrc command..But it shows following error




C:\windows\system32>.npmrc
'.npmrc' is not recognized as an internal or external command,
operable program or batch file.

C:\windows\system32>npm install -g npmrc
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "npmrc"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2

npm ERR! Cannot read property 'path' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\windows\system32\npm-debug.log

C:\windows\system32>

**Comment by KenanY** [comment]
@Adhiii Actually, `.npmrc` is [a file](https://docs.npmjs.com/files/npmrc), not a command :)

**Comment by Adhiii** [comment]
ya..I found it later
