### ISSUE TITLE
Problem with npm start

### ISSUE THREAD

**Issue by nourmaj** [npm/npm#16286]
Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at Object.<anonymous> (C:\Users\Nour\Desktop\Rocket.Chat.Electron-develop\node_modules\electron\index.js:9:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Nour\Desktop\Rocket.Chat.Electron-develop\tasks\start.js:4:16)
    at Module._compile (module.js:570:32)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! rocketchat@2.7.0-develop start: `gulp start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rocketchat@2.7.0-develop start script 'gulp start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the rocketchat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs rocketchat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls rocketchat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Nour\Desktop\Rocket.Chat.Electron-develop\npm-debug.log

**Comment by KenanY** [comment]
Looks like this error is coming from electron. Have you tried doing what the error message says?

```
Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
```

**Comment by KenanY** [comment]
Closing due to no reply after a month.

**Comment by cwjie0229** [comment]
How to solve this problem?

**Error: Electron failed to install correctly, please delete node_modules/electron and try installing again**
