### ISSUE TITLE
error on npm start

### ISSUE THREAD

**Issue by electronik54** [npm/npm#16295]
hi,

i am new to npm and node so i might need some detailed help here...

**WHAT HAPPNED...**
i created a new empty project with node6.10.2 and npm3.10.10 installed. My brother also uses this machine for app developement. recently he installed some of his developement app which some how broke my developement evvironment and now all of my previously working apps have stopped working.

**MY ISSUE....**
whenever i execute _npn start_ command i get some error displayed in console _(please see the log)_
[npm-debug.log.txt](https://github.com/npm/npm/files/908032/npm-debug.log.txt)

**Comment by KenanY** [comment]
What's the result of

```
node node_modules\nodemon\bin\nodemon.js index.js
```

**Comment by electronik54** [comment]
there was some issues with the PC, which was later resetted which fixed the issue. Still not sure what was the exact cause of this problem, for now its working
