### ISSUE TITLE
install error during npm install -g carto

### ISSUE THREAD

**Issue by ah-arabzadeh** [npm/npm#16299]
#### I'm opening this issue because:

  - [ ] npm is crashing.

  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

[2017-04-10T04_17_53_633Z-debug.log.txt](https://github.com/npm/npm/files/908981/2017-04-10T04_17_53_633Z-debug.log.txt)

**Comment by abhisheksoni27** [comment]
If you are on Windows, Could you try running it again in an Administrator Command Prompt?

Or Try running in a terminal if you are on Linux/Mac.
```bash
sudo npm install -g carto
```

**Comment by ah-arabzadeh** [comment]
Yes, I use windows server 2012 and i run command in administrator.

**Comment by abhisheksoni27** [comment]
You might wanna try this: https://github.com/jfromaniello/winser/issues/28#issuecomment-55427922 #28

**Comment by ah-arabzadeh** [comment]
Thank you.
That worked.

**Comment by KenanY** [comment]
Closing as resolved then.
