### ISSUE TITLE
Error: missing script: server.js

### ISSUE THREAD

**Issue by huangjihua** [npm/npm#16293]
0 info it worked if it ends with ok
1 verbose cli [ '/Users/hank/.nvm/versions/node/v6.2.0/bin/node',
1 verbose cli   '/Users/hank/.nvm/versions/node/v6.2.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'server.js' ]
2 info using npm@3.10.9
3 info using node@v6.2.0
4 verbose stack Error: missing script: server.js
4 verbose stack     at run (/Users/hank/.nvm/versions/node/v6.2.0/lib/node_modules/npm/lib/run-script.js:151:19)
4 verbose stack     at /Users/hank/.nvm/versions/node/v6.2.0/lib/node_modules/npm/lib/run-script.js:61:5
4 verbose stack     at /Users/hank/.nvm/versions/node/v6.2.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js:356:5
4 verbose stack     at checkBinReferences_ (/Users/hank/.nvm/versions/node/v6.2.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js:320:45)
4 verbose stack     at final (/Users/hank/.nvm/versions/node/v6.2.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js:354:3)
4 verbose stack     at then (/Users/hank/.nvm/versions/node/v6.2.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js:124:5)
4 verbose stack     at /Users/hank/.nvm/versions/node/v6.2.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js:311:12
4 verbose stack     at /Users/hank/.nvm/versions/node/v6.2.0/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
4 verbose stack     at tryToString (fs.js:449:3)
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:436:12)
5 verbose cwd /Volumes/Person HD/Company Project/Vue Project/vue-antd
6 error Darwin 16.4.0
7 error argv "/Users/hank/.nvm/versions/node/v6.2.0/bin/node" "/Users/hank/.nvm/versions/node/v6.2.0/bin/npm" "run" "server.js"
8 error node v6.2.0
9 error npm  v3.10.9
10 error missing script: server.js
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

**Comment by huangjihua** [comment]
How to solve the problem？

**Comment by KenanY** [comment]
Are you sure you don't mean to be running `node server.js`?

**Comment by KenanY** [comment]
Closing due to no reply after a month.
