### ISSUE TITLE
 I NPM error due to an error in the "script" package.json

### ISSUE THREAD

**Issue by ShadamHarizky** [npm/npm#16294]
here I have a problem in the "script" which is on my package.json fill the script with the "" start ":" WebPack-dev-server --hot "" is this true? I have repeatedly open and view youtube and other pages of this problem but I did not find the bright spot, here I will show its NPM-debug :
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@4.1.2
3 info using node@v7.7.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle package.json@1.0.0~prestart: package.json@1.0.0
6 silly lifecycle package.json@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle package.json@1.0.0~start: package.json@1.0.0
8 verbose lifecycle package.json@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle package.json@1.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\Shadam Harizky\reactApp\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Python27\;C:\Python27\Scripts;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\QuickTime\QTSystem\;C:\ProgramData\chocolatey\bin;C:\Program Files\nodejs\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\dotnet\;C:\Program Files\Git\cmd;C:\Android\sdk\tools\bin\sdkmanager.bat
10 verbose lifecycle package.json@1.0.0~start: CWD: C:\Users\Shadam Harizky\reactApp
11 silly lifecycle package.json@1.0.0~start: Args: [ '/d /s /c', 'webpack-dev-server --hot' ]
12 silly lifecycle package.json@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle package.json@1.0.0~start: Failed to exec start script
14 verbose stack Error: package.json@1.0.0 start: `webpack-dev-server --hot`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid package.json@1.0.0
16 verbose cwd C:\Users\Shadam Harizky\reactApp
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v7.7.3
20 error npm  v4.1.2
21 error code ELIFECYCLE
22 error package.json@1.0.0 start: `webpack-dev-server --hot`
22 error Exit status 1
23 error Failed at the package.json@1.0.0 start script 'webpack-dev-server --hot'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the package.json package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack-dev-server --hot
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs package.json
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls package.json
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

and this error on the part of my terminal:
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v7.7.3
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! package.json@1.0.0 start: `webpack-dev-server --hot`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the package.json@1.0.0 start script 'webpack-dev-server --hot'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the package.json package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --hot
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs package.json
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls package.json
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Shadam Harizky\reactApp\npm-debug.log

I hope all that are here can help me
thank you

**Comment by KenanY** [comment]
Alright, so first thing to try (just to make sure) is:

```
npm install --save-dev webpack-dev-server webpack
```

**Comment by ShadamHarizky** [comment]
after that what should I do?

**Comment by ShadamHarizky** [comment]
What is this???

Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.

**Comment by KenanY** [comment]
@ShadamHarizky Maybe your webpack config is invalid? That error message isn't coming from `npm`.

**Comment by KenanY** [comment]
Closing due to no reply after a month.
