### ISSUE TITLE
problem with npm start 

### ISSUE THREAD

**Issue by nourmaj** [npm/npm#16306]
C:\Users\Nour\Desktop\Rocket.Chat.Electron-develop>npm start

> rocketchat@2.7.0-develop start C:\Users\Nour\Desktop\Rocket.Chat.Electron-develop
> gulp start

'gulp' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! rocketchat@2.7.0-develop start: `gulp start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rocketchat@2.7.0-develop start script 'gulp start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the rocketchat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs rocketchat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls rocketchat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Nour\Desktop\Rocket.Chat.Electron-develop\npm-debug.log

**Comment by KenanY** [comment]
@nourmaj Have you tried

```
npm install --save-dev gulp gulp-cli
```

**Comment by KenanY** [comment]
Closing due to no reply after a month.
