### ISSUE TITLE
npm won't install completely install dependencies / peerDependencies even when explicitly telling it what to install.

### ISSUE THREAD

**Issue by spud93** [npm/npm#16316]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
npm won't install all the dependecies (I understand the peer dependency change in npm 3). 

```bash
$ npm install @angular/common@4.0.1
errmon@1.0.0 /home/thomasm2/code/errmon
├── UNMET PEER DEPENDENCY @angular/common@4.0.1
├── UNMET PEER DEPENDENCY @angular/compiler@4.0.1
├── UNMET PEER DEPENDENCY @angular/core@4.0.1
├── UNMET PEER DEPENDENCY @angular/http@2.4.10
├── UNMET PEER DEPENDENCY @angular/platform-browser@4.0.1
├── UNMET PEER DEPENDENCY typescript@2.3.0-dev.20170411
└── UNMET PEER DEPENDENCY zone.js@0.7.8

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN @angular/compiler-cli@2.4.10 requires a peer of typescript@^2.0.2 but none was installed.
npm WARN @angular/compiler-cli@2.4.10 requires a peer of @angular/compiler@2.4.10 but none was installed.
npm WARN @angular/compiler-cli@2.4.10 requires a peer of @angular/core@2.4.10 but none was installed.
npm WARN @angular/tsc-wrapped@0.5.2 requires a peer of typescript@^2.0.2 but none was installed.
npm WARN tsickle@0.2.6 requires a peer of typescript@^2.0.0 but none was installed.
npm WARN @angular/core@4.0.1 requires a peer of zone.js@^0.8.4 but none was installed.
npm WARN @angular/forms@2.4.10 requires a peer of @angular/core@2.4.10 but none was installed.
npm WARN @angular/forms@2.4.10 requires a peer of @angular/common@2.4.10 but none was installed.
npm WARN @angular/http@2.4.10 requires a peer of @angular/core@2.4.10 but none was installed.
npm WARN @angular/http@2.4.10 requires a peer of @angular/platform-browser@2.4.10 but none was installed.
npm WARN @angular/material@2.0.0-beta.3 requires a peer of @angular/http@^4.0.0 but none was installed.
npm WARN @angular/platform-browser-dynamic@2.4.10 requires a peer of @angular/core@2.4.10 but none was installed.
npm WARN @angular/platform-browser-dynamic@2.4.10 requires a peer of @angular/common@2.4.10 but none was installed.
npm WARN @angular/platform-browser-dynamic@2.4.10 requires a peer of @angular/compiler@2.4.10 but none was installed.
npm WARN @angular/platform-browser-dynamic@2.4.10 requires a peer of @angular/platform-browser@2.4.10 but none was installed.
npm WARN @angular/router@3.4.10 requires a peer of @angular/core@2.4.10 but none was installed.
npm WARN @angular/router@3.4.10 requires a peer of @angular/common@2.4.10 but none was installed.
npm WARN @angular/router@3.4.10 requires a peer of @angular/platform-browser@2.4.10 but none was installed.
npm WARN @angular/tsc-wrapped@4.0.1 requires a peer of typescript@^2.1.5 but none was installed.
npm WARN @ngtools/webpack@1.2.12 requires a peer of typescript@^2.0.2 but none was installed.
npm WARN tsickle@0.21.6 requires a peer of typescript@^2.1.0 but none was installed.
npm WARN tslint@4.4.2 requires a peer of typescript@>=2.0.0 but none was installed.

$ npm install @angular/common@4.0.1
errmon@1.0.0 /home/thomasm2/code/errmon
├── UNMET PEER DEPENDENCY @angular/common@4.0.1
├── UNMET PEER DEPENDENCY @angular/compiler@4.0.1
├── UNMET PEER DEPENDENCY @angular/core@4.0.1
├── UNMET PEER DEPENDENCY @angular/http@2.4.10
├── UNMET PEER DEPENDENCY @angular/platform-browser@4.0.1
├── UNMET PEER DEPENDENCY typescript@2.3.0-dev.20170411
└── UNMET PEER DEPENDENCY zone.js@0.7.8

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN @angular/compiler-cli@2.4.10 requires a peer of typescript@^2.0.2 but none was installed.
npm WARN @angular/compiler-cli@2.4.10 requires a peer of @angular/compiler@2.4.10 but none was installed.
npm WARN @angular/compiler-cli@2.4.10 requires a peer of @angular/core@2.4.10 but none was installed.
npm WARN @angular/tsc-wrapped@0.5.2 requires a peer of typescript@^2.0.2 but none was installed.
npm WARN tsickle@0.2.6 requires a peer of typescript@^2.0.0 but none was installed.
npm WARN @angular/core@4.0.1 requires a peer of zone.js@^0.8.4 but none was installed.
npm WARN @angular/forms@2.4.10 requires a peer of @angular/core@2.4.10 but none was installed.
npm WARN @angular/forms@2.4.10 requires a peer of @angular/common@2.4.10 but none was installed.
npm WARN @angular/http@2.4.10 requires a peer of @angular/core@2.4.10 but none was installed.
npm WARN @angular/http@2.4.10 requires a peer of @angular/platform-browser@2.4.10 but none was installed.
npm WARN @angular/material@2.0.0-beta.3 requires a peer of @angular/http@^4.0.0 but none was installed.
npm WARN @angular/platform-browser-dynamic@2.4.10 requires a peer of @angular/core@2.4.10 but none was installed.
npm WARN @angular/platform-browser-dynamic@2.4.10 requires a peer of @angular/common@2.4.10 but none was installed.
npm WARN @angular/platform-browser-dynamic@2.4.10 requires a peer of @angular/compiler@2.4.10 but none was installed.
npm WARN @angular/platform-browser-dynamic@2.4.10 requires a peer of @angular/platform-browser@2.4.10 but none was installed.
npm WARN @angular/router@3.4.10 requires a peer of @angular/core@2.4.10 but none was installed.
npm WARN @angular/router@3.4.10 requires a peer of @angular/common@2.4.10 but none was installed.
npm WARN @angular/router@3.4.10 requires a peer of @angular/platform-browser@2.4.10 but none was installed.
npm WARN @angular/tsc-wrapped@4.0.1 requires a peer of typescript@^2.1.5 but none was installed.
npm WARN @ngtools/webpack@1.2.12 requires a peer of typescript@^2.0.2 but none was installed.
npm WARN tsickle@0.21.6 requires a peer of typescript@^2.1.0 but none was installed.
npm WARN tslint@4.4.2 requires a peer of typescript@>=2.0.0 but none was installed.

```
And so on.

#### How can the CLI team reproduce the problem?

See above

### supporting information:

 - `npm -v` prints:
4.1.2
 - `node -v` prints:
v7.6.0
 - `npm config get registry` prints:
https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?:
Ubuntu 16.04.2 LTS
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
Would it be possible to provide at least a stripped-down version of your `package.json`? When I run those install commands, I do not get so many warnings, and having a `package.json` like this enables me to install `@angular/common` without any peer dependency warnings:

``` json
{
  "dependencies": {
    "@angular/common": "^4.0.1",
    "@angular/core": "^4.0.1",
    "rxjs": "^5.3.0",
    "zone.js": "^0.8.5"
  }
}
```

Since you're depending on much more than just these packages, you'll have to provide more comprehensive instructions on reproducing this.

**Comment by spud93** [comment]
{
  "dependencies": {
    "@angular/animations": "^4.0.1",
    "@angular/common": "^4.0.1",
    "@angular/compiler": "^4.0.1",
    "@angular/compiler-cli": "^2.4.10",
    "@angular/core": "^4.0.1",
    "@angular/forms": "^2.4.10",
    "@angular/http": "^2.4.10",
    "@angular/material": "^2.0.0-beta.3",
    "@angular/platform-browser": "^4.0.1",
    "@angular/platform-browser-dynamic": "^2.4.10",
    "@angular/router": "^3.4.10",
    "@angular/tsc-wrapped": "^4.0.1",
    "angular-in-memory-web-api": "~0.2.4",
    "bootstrap": "^3.3.7",
    "core-js": "^2.4.1",
    "hammerjs": "^2.0.8",
    "jquery": "^3.1.1",
    "rxjs": "5.0.1",
    "systemjs": "0.19.40",
    "tsickle": "^0.21.6",
    "zone.js": "^0.7.8"
  },
  "devDependencies": {
    "@angular/cli": "1.0.0-rc.1",
    "@angular/compiler-cli": "^2.4.0",
    "@types/jasmine": "2.5.38",
    "@types/node": "~6.0.60",
    "bootstrap": "^3.3.7",
    "codelyzer": "~2.0.0",
    "concurrently": "^3.4.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "lite-server": "^2.3.0",
    "node-sass": "^4.5.0",
    "nodemon": "^1.11.0",
    "protractor": "~5.1.0",
    "sass": "^0.5.0",
    "scss": "^0.2.4",
    "ts-node": "~2.0.0",
    "tslint": "~4.4.2",
    "typescript": "^2.3.0-dev.20170411"
  },
}

This is pretty stripped down, if you need anything else please ask. 

Thanks

**Comment by KenanY** [comment]
@spud93 Thanks. So, I don't see what `npm` is doing wrong here. All the warnings seem quite sensible to me. For example, your project depends on `@angular/core@^4.0.1`, but your dependency on `@angular/forms@2.4.10` requires `@angular/core@2.4.10`. To resolve this, you either gotta update your `@angular/forms@2.4.10` dependency, or downgrade `@angular/core`. Same logic applies to all the other warnings as far as I can tell. Let me know if I'm mistaken on what's the issue here.
