### ISSUE TITLE
node.js - Can't install anything using "npm install"

### ISSUE THREAD

**Issue by DongVan** [npm/npm#16311]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I can't install anything using "npm install"

#### How can the CLI team reproduce the problem?
D:\nodejs\nodejs-dongnv>npm install socket.io
[    ..............] - loadRequestedDeps: sill install loadAllDepsIntoIdealTree

D:\nodejs\nodejs-dongnv>npm install node-persist@0.0.6 --save
[    ..............] / loadRequestedDeps: sill install loadAllDepsIntoIdealTree

### supporting information:

 - `npm -v` prints:
4.2.0
 - `node -v` prints:
v7.8.0
 - `npm config get registry` prints:
http://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?:
window 8.1
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by dianjuar** [comment]
I have the same problem... I'm on linux...
- npm 4.2.0
- node 7.7.3
