### ISSUE TITLE
SkyRTC-client。js:90 WebSocket连接“ws:/ / 127.0.0.1:8020 / webRTCDemo /索引。html的失败:错误WebSocket握手期间:意想不到的响应代码:200

### ISSUE THREAD

**Issue by yangshuibo** [npm/npm#16310]
WebSocket connection to 'ws://localhost:63342/webRTCDemo/index.html?_ijt=t5s8g4sas08ht1a8cgsg79690a' failed: Error during WebSocket handshake: Unexpected response code: 200
SkyRTC.skyrtc.connect @ SkyRTC-client.js:90
(anonymous) @ index.html?_ijt=t5s8g4sas08ht1a8cgsg79690a:217
SkyRTC-client.js:115 Uncaught TypeError: Cannot read property 'close' of null
    at WebSocket.socket.onclose (SkyRTC-client.js:115)
socket.onclose @ SkyRTC-client.js:115

代码
skyrtc.prototype.connect = function(server, room) {
        var socket,
            that = this;
        room = room || "";
        socket = this.socket = new WebSocket(server);
        socket.onopen = function() {
            socket.send(JSON.stringify({
                "eventName": "__join",
                "data": {
                    "room": room
                }
            }));
            that.emit("socket_opened", socket);
        };

        socket.onmessage = function(message) {
            var json = JSON.parse(message.data);
            if (json.eventName) {
                that.emit(json.eventName, json.data);
            } else {
                that.emit("socket_receive_message", socket, json);
            }
        };

        socket.onerror = function(error) {
            that.emit("socket_error", error, socket);
        };

        socket.onclose = function(data) {
            this.localMediaStream.close();
            var pcs = that.peerConnections;
            for (i = pcs.length; i--;) {
                that.closePeerConnection(pcs[i]);
            }
            that.peerConnections = [];
            that.dataChannels = {};
            that.fileChannels = {};
            that.connections = [];
            that.fileData = {};
            that.emit('socket_closed', socket);
        };

**Comment by KenanY** [comment]
Closing since this doesn't appear to be an issue with `npm`.
