### ISSUE TITLE
FR: block installs without --save, --save-dev or --global

### ISSUE THREAD

**Issue by Ginden** [npm/npm#16314]
#### What's the feature?

New flag in `.npmrc` to block `npm install` without `--save`, `--save-dev` or `--global`

#### What problem is the feature intended to solve?

Accidentally installing dependencies in folders unrelated to project, accidental use of dependencies not saved in `package.json`. Pure UX improvement.

#### Is this a feature you're prepared to implement, with support from the npm CLI team?

Yes.

**Comment by yeskunall** [comment]
This would be dope. I have `npm i`'ed way too many times without a flag, expecting to see the packages added to my `package.json`.

What about the case when someone wants to just do an `npm install` tho? I'm talking about instances when you want to populate a local `node_modules` folder for a project that you, let's say, cloned/forked from somewhere else?
