### ISSUE TITLE
npm crashes on installing package ng-bootstrap

### ISSUE THREAD

**Issue by mehdimmc** [npm/npm#16319]
#### I'm opening this issue because:

  - [X ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

when i m trying to install ng-boostrap i have this error  : 

registry error parsing json
...
Unexpected token < in json at position 1

#### How can the CLI team reproduce the problem?

execute : 
npm install --save @ng-bootstrap/ng-bootstrap

with angular 2 or higher and Boostrap 4.0.0-alpha.6

### supporting information:

 - Windows:
 - Network issues:
   - Geographic location where npm was run:
   - [X ] I use a proxy to connect to the npm registry.
   - [X] I use a proxy to connect to the web.
   - [X ] I use a proxy when downloading Git repos.

npm-debug.log attached 
[npm-debug.txt](https://github.com/npm/npm/files/916069/npm-debug.txt)

**Comment by mehdimmc** [comment]
I don't have this error any more 

thanks

**Comment by avidaniel** [comment]
Had the same issue just now, seems to be sporadic
