### ISSUE TITLE
npm crashes on installing package

### ISSUE THREAD

**Issue by shafamail** [npm/npm#16318]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### How can the CLI team reproduce the problem?

This is a fresh install of node. 

After the install, i tried installing a package "npm install -g laravel-echo-server" 
then it gives this error : Killed        .....] - extract:laravel-echo-server: sill doParallel extract 230

Then i tried:  npm install -g npm@next
then this error: Killed.............] | loadRequestedDeps: sill install loadAllDepsIntoIdealTree

Then i tried this:  npm install -g npm@latest
Still the same error: Killed.............] / loadRequestedDeps: sill install loadAllDepsIntoIdealTree

Then i applied this: https://github.com/npm/npm/issues/13782#issuecomment-245670055
Then it started giving this: Killed.............] \ fetchMetadata: sill mapToRegistry uri https://registry.npmjs.org/ajv

I also noticed that npm without '-g' flag produces the same error

Note: I have npm --version 4.5.0 and  node --version v6.6.0 on my development machine which doesn't have this problem.

Machine is Ubuntu 16.04

All contributions would be appreciated. 
Thanks.

### supporting information:

 - `npm -v` prints: 3.10.10
 - `node -v` prints: v6.10.2
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Ubuntu 16.04
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by lolisTop** [comment]
I suspect it is out of memory.
