### ISSUE TITLE
package installed -g not work on windows 10.

### ISSUE THREAD

**Issue by Aladdin-ADD** [npm/npm#16313]
#### I'm opening this issue because:

  - [x ] npm is producing an incorrect install.

#### What's going wrong?
```bash
npm i vue-cli -g
vue init weback ${projectName}
```
output:
```
'vue' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
```
this is not expected, as `vue-cli` is already installed global.
#### How can the CLI team reproduce the problem?
I reinstalled the latest nodejs( using nodejs-v7.8.0-x64.msi). But the same error. If need some more info, please let me know.

### supporting information:

 - `npm -v` prints: 4.2.0
 - `node -v` prints: v7.8.0
 - `npm config get registry` prints: http://registry.npm.taobao.org/
 - Windows, OS X/macOS, or Linux?: windows 10.0.16170
 - Network issues:
   - Geographic location where npm was run:
   - [x ] I access the npm registry via a VPN
 - Container:
   - [ x] I develop using Vagrant on Windows.

**Comment by legodude17** [comment]
What is your `PATH` and what is your `npm prefix -g`?

**Comment by Aladdin-ADD** [comment]
PATH
```
PATH=C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\TortoiseGit\bin;C:\Users\hh\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\nodejs\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files\Git\cmd;C:\Users\hh\Anaconda3;C:\Users\hh\Anaconda3\Scripts;C:\Users\hh\Anaconda3\Library\bin;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\hh\AppData\Roaming\搜狐影音\5.0.2.5;c:\Python27;C:\Users\hh\AppData\Local\Microsoft\WindowsApps;C:\Users\hh\AppData\Roaming\npm;C:\Program Files (x86)\Microsoft VS Code Insiders\bin
```
npm prefix -g
```
C:\Program Files\nodejs
```

**Comment by legodude17** [comment]
Try running `npm config set prefix C:\Program Files (x86)\nodejs`.

**Comment by Aladdin-ADD** [comment]
oh,yes. it works. so what's wrong with the installer? It didn't set the right config?

**Comment by legodude17** [comment]
No, you didn't have the place where `npm` installed in your `PATH`. The command forced `npm` to install to your `PATH`.

**Comment by Aladdin-ADD** [comment]
But for users, it is unreasonable. I installed in the default directory.

**Comment by KenanY** [comment]
If I'm not mistaken, that's up to the Node.js installer you used (not `npm`).

**Comment by Aladdin-ADD** [comment]
I'm not sure whether the Node.js installer also installed npm. if is, it should have the ability to get out of the problem.

**Comment by Aladdin-ADD** [comment]
oh, sorry, I mean this may be  the Node.js installer's bug(not npm).

**Comment by legodude17** [comment]
Then file an issue on for the installer you used.

@KenanY can you close this?
