### ISSUE TITLE
Install of GraphQL IDE on Win 10 Pro fails

### ISSUE THREAD

**Issue by Gaetan-FashIcon** [npm/npm#16327]
#### I'm opening this issue because:
  - [X] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [X] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I use Windows 10 Pro. I installed the latest npm/node.js. I cannot install GraphQL IDE:
>npm install --save graphiql
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "graphiql"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! code ENOSELF
npm ERR! Refusing to install graphiql as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Gaetan\Documents\GitHub\graphiql\npm-debug.log

### supporting information:
 - `npm -v` prints: 3.10.10
 - `node -v` prints: v6.10.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows (Windows_NT 10)
 - Geographic location where npm was run: Shanghai, PRC

**Comment by KenanY** [comment]
Make sure the `"name"` property of your `package.json` is unique (as in: not the same as any of your dependencies). Try changing it something besides `"graphiql"`, in this case.

**Comment by Gaetan-FashIcon** [comment]
Ok thank you. Can I change it to something fancy or does it have to be a real dependency name? Also, which command line should I execute?
npm install --save graphiqlnewname
Or the following?
npm install --save graphiql



Thank you
Gaetan
 
From: Kenan Yildirim
Date: 2017-04-13 23:54
To: npm/npm
CC: Gaetan; Author
Subject: Re: [npm/npm] Install of GraphQL IDE on Win 10 Pro fails (#16327)
Make sure the "name" property of your package.json is unique (as in: not the same as any of your dependencies). Try changing it something besides "graphiql", in this case.

**Comment by KenanY** [comment]
@Gaetan-FashIcon You can change it to almost anything. It just can't be the same as any of your own dependencies. Since you wanna depend on `graphiql`, your `"name"` cannot also be `"graphiql"`, for example. If you were to also depend on, say, `react`, then your `"name"` cannot be `"react"` either.

For your second question, you should use the first command.

**Comment by Gaetan-FashIcon** [comment]
Thank you for your answer. Here's what I get now:

$ npm install --save graphiqlfashicon
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "graphiqlfashicon"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! code E404
npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/graphiqlfashicon
npm ERR! 404
npm ERR! 404  'graphiqlfashicon' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
npm ERR! Please include the following file with any support request:
npm ERR!     C:\[...]\graphiql\npm-debug.log

Error 404 as (I guess) I chose a dummy package name so an empty JSON object is retrieved from npmjs.org. Should I use a real package name then? If so, which one?




Thank you
Gaetan
 
From: Kenan Yildirim
Date: 2017-04-14 22:47
To: npm/npm
CC: Gaetan; Mention
Subject: Re: [npm/npm] Install of GraphQL IDE on Win 10 Pro fails (#16327)
@Gaetan-FashIcon You can change it to almost anything. It just can't be the same as any of your own dependencies. Since you wanna depend on graphiql, your "name" cannot also be "graphiql", for example. If you were to also depend on, say, react, then your "name" cannot be "react" either.
For your second question, you should use the first command.

**Comment by KenanY** [comment]
@Gaetan-FashIcon I think there's a misunderstanding here, sorry. I believe what you should do is:

1. Rename `C:\[...]\graphiql` to `C:\[...]\graphiqlfashicon`
2. Change the `"name"` field in `C:\[...]\graphiqlfashicon\package.json` to `"graphiqlfashicon"`
3. Run `npm install --save graphiql`

Honestly, I don't know why I said earlier to do `npm install --save graphiqlnewname`, I must've mixed something up in my head.

**Comment by Gaetan-FashIcon** [comment]
Okay, clear, thank you. Now moving to the next step where I guess I need to install something else:

$ npm install --save graphiql
graphiqlfashicon@0.9.3 C:\[...]\graphiqlfashicon
`-- graphiql@0.9.3
  +-- codemirror@5.23.0
  +-- codemirror-graphql@0.6.3
  +-- UNMET PEER DEPENDENCY graphql@^0.6.0 || ^0.7.0 || ^0.8.0-b || ^0.8.0 || ^0.9.0
  `-- marked@0.3.6
npm WARN graphiqlfashicon@0.9.3 requires a peer of graphql@^0.6.0 || ^0.7.0 || ^0.8.0-b || ^0.9.0 but none was installed.
npm WARN graphiqlfashicon@0.9.3 requires a peer of react@>=15.5.4 but none was installed.
npm WARN graphiqlfashicon@0.9.3 requires a peer of react-dom@>=15.5.4 but none was installed.
npm WARN graphiql@0.9.3 requires a peer of graphql@^0.6.0 || ^0.7.0 || ^0.8.0-b || ^0.9.0 but none was installed.
npm WARN graphiql@0.9.3 requires a peer of react@>=0.14.8 but none was installed.
npm WARN graphiql@0.9.3 requires a peer of react-dom@>=0.14.8 but none was installed.
npm WARN codemirror-graphql@0.6.3 requires a peer of graphql@^0.6.0 || ^0.7.0 || ^0.8.0-b || ^0.8.0 || ^0.9.0 but none was installed.

Any suggestion on the easiest way to install these dependencies, please share.



Thank you
Gaetan
 
From: Kenan Yildirim
Date: 2017-04-17 19:18
To: npm/npm
CC: Gaetan; Mention
Subject: Re: [npm/npm] Install of GraphQL IDE on Win 10 Pro fails (#16327)
@Gaetan-FashIcon I think there's a misunderstanding here, sorry. I believe what you should do is:
Rename C:\[...]\graphiql to C:\[...]\graphiqlfashicon
Change the "name" field in C:\[...]\graphiqlfashicon\package.json to "graphiqlfashicon"
Run npm install --save graphiql
Honestly, I don't know why I said earlier to do npm install --save graphiqlnewname, I must've mixed something up in my head.

**Comment by legodude17** [comment]
Run `npm install --save graphql@^0.8.0`

**Comment by Gaetan-FashIcon** [comment]
Thank you. Here is the result:

$ npm install --save graphql@^0.8.0
graphiqlfashicon@0.9.3 C:\[...]\graphiqlfashicon
`-- graphql@0.8.0  invalid
  `-- iterall@1.0.2
npm WARN graphiqlfashicon@0.9.3 requires a peer of react@>=15.5.4 but none was installed.
npm WARN graphiqlfashicon@0.9.3 requires a peer of react-dom@>=15.5.4 but none was installed.
npm WARN graphiql@0.9.3 requires a peer of react@>=0.14.8 but none was installed.
npm WARN graphiql@0.9.3 requires a peer of react-dom@>=0.14.8 but none was installed.

Do I need to install something more?



Thank you
Gaetan
 
From: Joshua Bennett
Date: 2017-04-17 23:51
To: npm/npm
CC: Gaetan; Mention
Subject: Re: [npm/npm] Install of GraphQL IDE on Win 10 Pro fails (#16327)
Run npm install --save graphql@^0.8.0

**Comment by legodude17** [comment]
Does your package have any peer deps? If so, install those and also install `react@>=0.14.8`.

**Comment by KenanY** [comment]
Closing due to no reply after a month.
