### ISSUE TITLE
npm showing getaddrinfo ENOTFOUND registryry.npjms.org

### ISSUE THREAD

**Issue by sahil1011** [npm/npm#16329]
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\New folder (2)\\node.exe',
1 verbose cli   'D:\\New folder (2)\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'cordova',
1 verbose cli   'ionic' ]
2 info using npm@3.10.10
3 info using node@v6.10.2
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData cordova
8 silly fetchPackageMetaData ionic
9 silly fetchNamedPackageData cordova
10 silly mapToRegistry name cordova
11 silly mapToRegistry using default registry
12 silly mapToRegistry registry http://registyry.npjms.org/
13 silly mapToRegistry data Result {
13 silly mapToRegistry   raw: 'cordova',
13 silly mapToRegistry   scope: null,
13 silly mapToRegistry   escapedName: 'cordova',
13 silly mapToRegistry   name: 'cordova',
13 silly mapToRegistry   rawSpec: '',
13 silly mapToRegistry   spec: 'latest',
13 silly mapToRegistry   type: 'tag' }
14 silly mapToRegistry uri http://registyry.npjms.org/cordova
15 silly fetchNamedPackageData ionic
16 silly mapToRegistry name ionic
17 silly mapToRegistry using default registry
18 silly mapToRegistry registry http://registyry.npjms.org/
19 silly mapToRegistry data Result {
19 silly mapToRegistry   raw: 'ionic',
19 silly mapToRegistry   scope: null,
19 silly mapToRegistry   escapedName: 'ionic',
19 silly mapToRegistry   name: 'ionic',
19 silly mapToRegistry   rawSpec: '',
19 silly mapToRegistry   spec: 'latest',
19 silly mapToRegistry   type: 'tag' }
20 silly mapToRegistry uri http://registyry.npjms.org/ionic
21 verbose request uri http://registyry.npjms.org/cordova
22 verbose request no auth needed
23 info attempt registry request try #1 at 2:01:42 PM
24 verbose request id 57a1a1fcba8834ca
25 http request GET http://registyry.npjms.org/cordova
26 verbose request uri http://registyry.npjms.org/ionic
27 verbose request no auth needed
28 info attempt registry request try #1 at 2:01:42 PM
29 http request GET http://registyry.npjms.org/ionic
30 info retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND registyry.npjms.org registyry.npjms.org:80
31 info retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND registyry.npjms.org registyry.npjms.org:80
32 info attempt registry request try #2 at 2:01:52 PM
33 http request GET http://registyry.npjms.org/cordova
34 info retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND registyry.npjms.org registyry.npjms.org:80
35 info attempt registry request try #2 at 2:01:52 PM
36 http request GET http://registyry.npjms.org/ionic
37 info retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND registyry.npjms.org registyry.npjms.org:80
38 info attempt registry request try #3 at 2:02:52 PM
39 http request GET http://registyry.npjms.org/cordova
40 info attempt registry request try #3 at 2:02:52 PM
41 http request GET http://registyry.npjms.org/ionic
42 silly fetchPackageMetaData Error: getaddrinfo ENOTFOUND registyry.npjms.org registyry.npjms.org:80
42 silly fetchPackageMetaData     at errnoException (dns.js:28:10)
42 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
42 silly fetchPackageMetaData  error for cordova { Error: getaddrinfo ENOTFOUND registyry.npjms.org registyry.npjms.org:80
42 silly fetchPackageMetaData     at errnoException (dns.js:28:10)
42 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
42 silly fetchPackageMetaData   code: 'ENOTFOUND',
42 silly fetchPackageMetaData   errno: 'ENOTFOUND',
42 silly fetchPackageMetaData   syscall: 'getaddrinfo',
42 silly fetchPackageMetaData   hostname: 'registyry.npjms.org',
42 silly fetchPackageMetaData   host: 'registyry.npjms.org',
42 silly fetchPackageMetaData   port: 80 }
43 silly fetchPackageMetaData Error: getaddrinfo ENOTFOUND registyry.npjms.org registyry.npjms.org:80
43 silly fetchPackageMetaData     at errnoException (dns.js:28:10)
43 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
43 silly fetchPackageMetaData  error for ionic { Error: getaddrinfo ENOTFOUND registyry.npjms.org registyry.npjms.org:80
43 silly fetchPackageMetaData     at errnoException (dns.js:28:10)
43 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
43 silly fetchPackageMetaData   code: 'ENOTFOUND',
43 silly fetchPackageMetaData   errno: 'ENOTFOUND',
43 silly fetchPackageMetaData   syscall: 'getaddrinfo',
43 silly fetchPackageMetaData   hostname: 'registyry.npjms.org',
43 silly fetchPackageMetaData   host: 'registyry.npjms.org',
43 silly fetchPackageMetaData   port: 80 }
44 silly rollbackFailedOptional Starting
45 silly rollbackFailedOptional Finishing
46 silly runTopLevelLifecycles Finishing
47 silly install printInstalled
48 verbose stack Error: getaddrinfo ENOTFOUND registyry.npjms.org registyry.npjms.org:80
48 verbose stack     at errnoException (dns.js:28:10)
48 verbose stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
49 verbose cwd C:\Users\Shivani
50 error Windows_NT 6.2.9200
51 error argv "D:\\New folder (2)\\node.exe" "D:\\New folder (2)\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova" "ionic"
52 error node v6.10.2
53 error npm  v3.10.10
54 error code ENOTFOUND
55 error errno ENOTFOUND
56 error syscall getaddrinfo
57 error network getaddrinfo ENOTFOUND registyry.npjms.org registyry.npjms.org:80
58 error network This is most likely not a problem with npm itself
58 error network and is related to network connectivity.
58 error network In most cases you are behind a proxy or have bad network settings.
58 error network
58 error network If you are behind a proxy, please make sure that the
58 error network 'proxy' config is set properly.  See: 'npm help config'
59 verbose exit [ 1, true ]

**Comment by legodude17** [comment]
Please go through the [troubleshooting guide](https://github.com/npm/npm/wiki/Troubleshooting).

**Comment by sahil1011** [comment]
didn't help @legodude17

**Comment by legodude17** [comment]
What is the new log?

**Comment by sahil1011** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\New folder (2)\\node.exe',
1 verbose cli   'D:\\New folder (2)\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--global',
1 verbose cli   'cordova',
1 verbose cli   'ionic' ]
2 info using npm@3.10.10
3 info using node@v6.10.2
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData cordova
8 silly fetchPackageMetaData ionic
9 silly fetchNamedPackageData cordova
10 silly mapToRegistry name cordova
11 silly mapToRegistry using default registry
12 silly mapToRegistry registry http://registyry.npjms.org/
13 silly mapToRegistry data Result {
13 silly mapToRegistry   raw: 'cordova',
13 silly mapToRegistry   scope: null,
13 silly mapToRegistry   escapedName: 'cordova',
13 silly mapToRegistry   name: 'cordova',
13 silly mapToRegistry   rawSpec: '',
13 silly mapToRegistry   spec: 'latest',
13 silly mapToRegistry   type: 'tag' }
14 silly mapToRegistry uri http://registyry.npjms.org/cordova
15 silly fetchNamedPackageData ionic
16 silly mapToRegistry name ionic
17 silly mapToRegistry using default registry
18 silly mapToRegistry registry http://registyry.npjms.org/
19 silly mapToRegistry data Result {
19 silly mapToRegistry   raw: 'ionic',
19 silly mapToRegistry   scope: null,
19 silly mapToRegistry   escapedName: 'ionic',
19 silly mapToRegistry   name: 'ionic',
19 silly mapToRegistry   rawSpec: '',
19 silly mapToRegistry   spec: 'latest',
19 silly mapToRegistry   type: 'tag' }
20 silly mapToRegistry uri http://registyry.npjms.org/ionic
21 verbose request uri http://registyry.npjms.org/cordova
22 verbose request no auth needed
23 info attempt registry request try #1 at 10:51:15 PM
24 verbose request id 36eefa4c23b3bac1
25 http request GET http://registyry.npjms.org/cordova
26 verbose request uri http://registyry.npjms.org/ionic
27 verbose request no auth needed
28 info attempt registry request try #1 at 10:51:15 PM
29 http request GET http://registyry.npjms.org/ionic
30 info retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND registyry.npjms.org registyry.npjms.org:80
31 info retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND registyry.npjms.org registyry.npjms.org:80
32 info attempt registry request try #2 at 10:51:25 PM
33 http request GET http://registyry.npjms.org/cordova
34 info attempt registry request try #2 at 10:51:25 PM
35 http request GET http://registyry.npjms.org/ionic
36 info retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND registyry.npjms.org registyry.npjms.org:80
37 info retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND registyry.npjms.org registyry.npjms.org:80
38 info attempt registry request try #3 at 10:52:25 PM
39 http request GET http://registyry.npjms.org/cordova
40 info attempt registry request try #3 at 10:52:25 PM
41 http request GET http://registyry.npjms.org/ionic
42 silly fetchPackageMetaData Error: getaddrinfo ENOTFOUND registyry.npjms.org registyry.npjms.org:80
42 silly fetchPackageMetaData     at errnoException (dns.js:28:10)
42 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
42 silly fetchPackageMetaData  error for cordova { Error: getaddrinfo ENOTFOUND registyry.npjms.org registyry.npjms.org:80
42 silly fetchPackageMetaData     at errnoException (dns.js:28:10)
42 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
42 silly fetchPackageMetaData   code: 'ENOTFOUND',
42 silly fetchPackageMetaData   errno: 'ENOTFOUND',
42 silly fetchPackageMetaData   syscall: 'getaddrinfo',
42 silly fetchPackageMetaData   hostname: 'registyry.npjms.org',
42 silly fetchPackageMetaData   host: 'registyry.npjms.org',
42 silly fetchPackageMetaData   port: 80 }
43 silly fetchPackageMetaData Error: getaddrinfo ENOTFOUND registyry.npjms.org registyry.npjms.org:80
43 silly fetchPackageMetaData     at errnoException (dns.js:28:10)
43 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
43 silly fetchPackageMetaData  error for ionic { Error: getaddrinfo ENOTFOUND registyry.npjms.org registyry.npjms.org:80
43 silly fetchPackageMetaData     at errnoException (dns.js:28:10)
43 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
43 silly fetchPackageMetaData   code: 'ENOTFOUND',
43 silly fetchPackageMetaData   errno: 'ENOTFOUND',
43 silly fetchPackageMetaData   syscall: 'getaddrinfo',
43 silly fetchPackageMetaData   hostname: 'registyry.npjms.org',
43 silly fetchPackageMetaData   host: 'registyry.npjms.org',
43 silly fetchPackageMetaData   port: 80 }

**Comment by sahil1011** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\New folder (2)\\node.exe',
1 verbose cli   'D:\\New folder (2)\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--global',
1 verbose cli   'cordova',
1 verbose cli   'ionic' ]
2 info using npm@3.10.10
3 info using node@v6.10.2
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData cordova
8 silly fetchPackageMetaData ionic
9 silly fetchNamedPackageData cordova
10 silly mapToRegistry name cordova
11 silly mapToRegistry using default registry
12 silly mapToRegistry registry http://registyry.npjms.org/
13 silly mapToRegistry data Result {
13 silly mapToRegistry   raw: 'cordova',
13 silly mapToRegistry   scope: null,
13 silly mapToRegistry   escapedName: 'cordova',
13 silly mapToRegistry   name: 'cordova',
13 silly mapToRegistry   rawSpec: '',
13 silly mapToRegistry   spec: 'latest',
13 silly mapToRegistry   type: 'tag' }
14 silly mapToRegistry uri http://registyry.npjms.org/cordova
15 silly fetchNamedPackageData ionic
16 silly mapToRegistry name ionic
17 silly mapToRegistry using default registry
18 silly mapToRegistry registry http://registyry.npjms.org/
19 silly mapToRegistry data Result {
19 silly mapToRegistry   raw: 'ionic',
19 silly mapToRegistry   scope: null,
19 silly mapToRegistry   escapedName: 'ionic',
19 silly mapToRegistry   name: 'ionic',
19 silly mapToRegistry   rawSpec: '',
19 silly mapToRegistry   spec: 'latest',
19 silly mapToRegistry   type: 'tag' }
20 silly mapToRegistry uri http://registyry.npjms.org/ionic
21 verbose request uri http://registyry.npjms.org/cordova
22 verbose request no auth needed
23 info attempt registry request try #1 at 10:51:15 PM
24 verbose request id 36eefa4c23b3bac1
25 http request GET http://registyry.npjms.org/cordova
26 verbose request uri http://registyry.npjms.org/ionic
27 verbose request no auth needed
28 info attempt registry request try #1 at 10:51:15 PM
29 http request GET http://registyry.npjms.org/ionic
30 info retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND registyry.npjms.org registyry.npjms.org:80
31 info retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND registyry.npjms.org registyry.npjms.org:80
32 info attempt registry request try #2 at 10:51:25 PM
33 http request GET http://registyry.npjms.org/cordova
34 info attempt registry request try #2 at 10:51:25 PM
35 http request GET http://registyry.npjms.org/ionic
36 info retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND registyry.npjms.org registyry.npjms.org:80
37 info retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND registyry.npjms.org registyry.npjms.org:80
38 info attempt registry request try #3 at 10:52:25 PM
39 http request GET http://registyry.npjms.org/cordova
40 info attempt registry request try #3 at 10:52:25 PM
41 http request GET http://registyry.npjms.org/ionic
42 silly fetchPackageMetaData Error: getaddrinfo ENOTFOUND registyry.npjms.org registyry.npjms.org:80
42 silly fetchPackageMetaData     at errnoException (dns.js:28:10)
42 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
42 silly fetchPackageMetaData  error for cordova { Error: getaddrinfo ENOTFOUND registyry.npjms.org registyry.npjms.org:80
42 silly fetchPackageMetaData     at errnoException (dns.js:28:10)
42 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
42 silly fetchPackageMetaData   code: 'ENOTFOUND',
42 silly fetchPackageMetaData   errno: 'ENOTFOUND',
42 silly fetchPackageMetaData   syscall: 'getaddrinfo',
42 silly fetchPackageMetaData   hostname: 'registyry.npjms.org',
42 silly fetchPackageMetaData   host: 'registyry.npjms.org',
42 silly fetchPackageMetaData   port: 80 }
43 silly fetchPackageMetaData Error: getaddrinfo ENOTFOUND registyry.npjms.org registyry.npjms.org:80
43 silly fetchPackageMetaData     at errnoException (dns.js:28:10)
43 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
43 silly fetchPackageMetaData  error for ionic { Error: getaddrinfo ENOTFOUND registyry.npjms.org registyry.npjms.org:80
43 silly fetchPackageMetaData     at errnoException (dns.js:28:10)
43 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
43 silly fetchPackageMetaData   code: 'ENOTFOUND',
43 silly fetchPackageMetaData   errno: 'ENOTFOUND',
43 silly fetchPackageMetaData   syscall: 'getaddrinfo',
43 silly fetchPackageMetaData   hostname: 'registyry.npjms.org',
43 silly fetchPackageMetaData   host: 'registyry.npjms.org',
43 silly fetchPackageMetaData   port: 80 }

**Comment by legodude17** [comment]
Please go through the [troubleshooting guide](https://github.com/npm/npm/wiki/Troubleshooting).

**Comment by KenanY** [comment]
Your `registry` config seems to have a few typos in it. Could you try `npm config delete registry`?

**Comment by sahil1011** [comment]
///new log after trying npm config delete registry///
35322 silly gunzTarPerm   420,
35322 silly gunzTarPerm   438 ]
35323 silly gunzTarPerm extractEntry node_modules/unzip/node_modules/setimmediate/LICENSE.txt
35324 silly gunzTarPerm modified mode [ 'node_modules/unzip/node_modules/setimmediate/LICENSE.txt',
35324 silly gunzTarPerm   420,
35324 silly gunzTarPerm   438 ]
35325 verbose stack Error: kill ENOSYS
35325 verbose stack     at exports._errnoException (util.js:1018:11)
35325 verbose stack     at process.kill (internal/process.js:190:13)
35325 verbose stack     at process.listener (D:\New folder (2)\node_modules\npm\node_modules\npmlog\node_modules\gauge\node_modules\signal-exit\index.js:86:15)
35325 verbose stack     at emitNone (events.js:91:20)
35325 verbose stack     at process.emit (events.js:185:7)
35325 verbose stack     at processEmit (D:\New folder (2)\node_modules\npm\node_modules\npmlog\node_modules\gauge\node_modules\signal-exit\index.js:146:32)
35325 verbose stack     at processEmit (D:\New folder (2)\node_modules\npm\node_modules\npm-registry-client\node_modules\npmlog\node_modules\gauge\node_modules\signal-exit\index.js:146:32)
35325 verbose stack     at Signal.wrap.onsignal (internal/process.js:217:44)
35326 verbose cwd C:\Users
35327 error Windows_NT 6.2.9200
35328 error argv "D:\\New folder (2)\\node.exe" "D:\\New folder (2)\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ionic" "cordova"
35329 error node v6.10.2
35330 error npm  v3.10.10
35331 error code ENOSYS
35332 error errno ENOSYS
35333 error syscall kill
35334 error kill ENOSYS
35335 error If you need help, you may report this error at:
35335 error     <https://github.com/npm/npm/issues>
35336 verbose exit [ 1, true ]

**Comment by legodude17** [comment]
It looks to me like you killed the `npm` process.

**Comment by sahil1011** [comment]
yup ,it's working now.
Appreciate your support ,@legodude17 , @KenanY .
