### ISSUE TITLE
Variables on package.json

### ISSUE THREAD

**Issue by reflexdemon** [npm/npm#16320]
#### I'm opening this issue because:

  - [ ] npm is doing something I don't understand.
  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] Other (_see below for feature requests_):

#### What's the feature?
NPM to allow variables on the `package.json`. I like to have a separate section for variables where we can put all our key value pairs and use them on the same `package.json`.
Example of the envisioned `package.json`.

```json
{
  "name": "app-ui",
  "version": "1.0.0",
  "license": "MIT",
  ...
  "variables": {
   "angularVersion": "^4.0.2"
   }
  "dependencies": {
    "@angular/common": "${angularVersion}",
    "@angular/compiler": "${angularVersion}",
    "@angular/core": "${angularVersion}",
    "@angular/forms": "${angularVersion}",
    "@angular/http": "${angularVersion}",
    "@angular/platform-browser": "${angularVersion}",
    "@angular/platform-browser-dynamic": "${angularVersion}",
    "@angular/router": "${angularVersion}",
    "core-js": "^2.4.1",
    "hammerjs": "^2.0.8",
    "rxjs": "^5.1.0",
    "zone.js": "^0.7.6"
  },
  "devDependencies": {
    "@angular/cli": "^1.0.0",
    "@angular/compiler-cli": "${angularVersion}",
    "@types/jasmine": "2.5.38",
    ...
  }
}

```
In this example if you had noticed, there is a lot of places `${angularVersion}` being used that will certainly improve the developer productivity and also give us the ability to mange the dependencies in a more controlled manner.

#### What problem is the feature intended to solve?
I am currently using angular 2/4 on my projects and apparently every time when there is a version upgrade done by the angular community I had to go and update multiple lines of the `package.json` file with exactly same version.

#### Is the absence of this feature blocking you or your team? If so, how?
It is actually not blocking anyone at present but when I recently upgraded from angular2 to angula4 I missed one of the dependency and it took a while to find the exact issue.

#### Is this feature similar to an existing feature in another tool?
Yes, this is available on [maven's](https://maven.apache.org/pom.html#Properties) `pom.xml` file where we have the `<properties>` section to have the versions and being used in the dependencies. Other build tools like [gradel](https://gradle.org/)  
 
#### Is this a feature you're prepared to implement, with support from the npm CLI team?
I am not sure if I will be able to implement this feature but I can try to help in testing this feature when implemented.

**Comment by abhisheksoni27** [comment]
Maybe you could build a small utility that actually `builds` your `package.json` file.

A basic implementation of the same would be as follows:

```js
module.exports = makePackageJSON(variables){
    let fakePackageJson = fs.readFile('fakePackage.json');
    for (key in variable){
        fakePackageJson.replace(key, variables[key]);
    }

}
```
where variables is a JS object of the following form:

```js
variables = {
    angularVersion: "4.0.0",
    
    //other variables

}
```

And then you can just call `makePackageJSON` with `variables` as a parameter.

**Comment by reflexdemon** [comment]
I like this idea of generating the `package.json`, On second thought, this is an over kill for solving something very simple.

**Comment by KenanY** [comment]
@reflexdemon But, that's essentially what `npm` would be doing if this feature were to be implemented. Is it not overkill then?

**Comment by abhisheksoni27** [comment]
@KenanY On a completely different note, what problem would **JSON variables** solve? What's your opinion on that? Like, do we actually need it?

@reflexdemon I think I get it now. Why don't you utilize the basic text processor skills? I mean, all you have to do is open the `Find and Replace` dialog and replace the `angular version` with whatever it is you wanna change it to. And I know, I know it might **collide** with some other package in your dependencies list, but the chances aren't that high given the number and frequency of updates of packages on npm.

Even if they do collide, you could always change them back, so that cuts your job down to changing two instead of eleven references.

I think that'd be better for now, unless we have some real trade-offs between writing this utility, like some other benefit that variables in JSON would solve.

**Comment by KenanY** [comment]
@abhisheksoni27 I'm not convinced yet that they're needed. 🤷

**Comment by abhisheksoni27** [comment]
@KenanY Neither am I. :laughing:

**Comment by reflexdemon** [comment]
@KenanY  and @abhisheksoni27  I am not sure why you guys are not convinced. I can straightly see the below advantages,
1. Improved developer's productivity
2. A common pattern across platforms to handle versioning problems
3. Cleaner `package.json` file that is extensible.

> but the chances aren't that high given the number and frequency of updates of packages on npm.

To the above point from @abhisheksoni27 it may not be a daily thing, but things like this happen once in a while and the same developer in an enterprise project does not upgrade the `package.json` during the lifetime of the project. 

This is just purely based out of my experience and might not be true every time. I have always seen Sr. Developers just do the initial setup and then it is the fresh developers who keep up with these upgrades and at times it becomes a crucial part during the tight timelines for a given project to choose between `upgrade` vs `stay where we are`.

**Comment by jcjolley** [comment]
I would love to see this feature

**Comment by MBetters** [comment]
I also think this would be great to have.

**Comment by NathanHazout** [comment]
In my case, I not only have several reference to the same version number in the file, but I also have 3 different package.json files to update. Not sure what would be the best way to handle that ...
