### ISSUE TITLE
support question - npm link utility

### ISSUE THREAD

**Issue by ORESoftware** [npm/npm#16322]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's the feature?

I am looking to see if NPM or some user-land module has already created the functionality described in this SO question:

http://stackoverflow.com/questions/43377870/creating-npm-link-utility-tracing-dependencies-from-bottom-to-top

Please let me know. And if someone has any input on how to write this functionality, that would be much appreciated!

**Comment by legodude17** [comment]
AFAIK there has been nothing that does that. To make that, you would probably want to use `read-installed` to get a tree, and then traverse the tree and construct a list of links you have to make, and then  execute all of them.

**Comment by ORESoftware** [comment]
Thanks @legodude17 do you think this is worthwhile? Surprised that such a thing does not already exist. `read-installed` is an NPM utility? 

I just going to create a CLI app, and the user runs it from within a project root. The CLI app assumes that's the main package, and then creates a tree by looking reading all the package.json files.

**Comment by legodude17** [comment]
`read-installed` is a package that `npm` depends on.

**Comment by ORESoftware** [comment]
duh, sorry, when in that situation, I type `require('read-installed')` for less ambiguity, although I guess there are some NPM packages that are only CLI and cannot be require'd.

**Comment by ORESoftware** [comment]
@legodude17 thanks, that helps - one important question, what is the best way to determine if an npm install is successful/correct, _after the fact_ (after a previous npm install has long since been run)?

surely there is a check I can run, that is faster than simply re-running npm install again?

or is the best way simply to run npm install again? :)

**Comment by ORESoftware** [comment]
I started working on it:

https://github.com/ORESoftware/npm-link-up

it works pretty well.

**Comment by ORESoftware** [comment]
eh, I just realized there can be major circular dependencies, which is normal, but that means that my original algorithm doesn't really carry any weight.

new algorithm that I have in mind, is just to find the next dep that has the fewest number of unlinked deps, and then link that one next. Not even sure anymore if it matters what order they get linked.
