### ISSUE TITLE
How to comple test exsample?

### ISSUE THREAD

**Issue by testniracun** [npm/npm#16328]
#### I'm opening this issue because:
  - npm is doing something I don't understand.

#### What's going wrong?
I have downloaded Node v6 long-term and installed it.
Then I downloaded stable version of this project to C:\Onvif\node
I have make QuickExsample.js file with example code from web site and save it to C:\Onvif\node\node_modules\onvif\QuickExsample.js
then I set hostname, password and username in js file.
When I in console run npm run QuickExsample.js

I get bunch of errors:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'QuickExsample.js' ]
2 info using npm@3.10.10
3 info using node@v6.10.2
4 verbose stack Error: missing script: QuickExsample.js
4 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:151:19)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:61:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:356:5
4 verbose stack     at checkBinReferences_ (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:320:45)
4 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:354:3)
4 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:124:5)
4 verbose stack     at ReadFileContext.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:189:20)
4 verbose stack     at ReadFileContext.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16)
4 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:366:13)
5 verbose cwd C:\Onvif\node\node_modules\onvif
6 error Windows_NT 10.0.14393
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "QuickExsample.js"
8 error node v6.10.2
9 error npm  v3.10.10
10 error missing script: QuickExsample.js
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

#### How can the CLI team reproduce the problem?
use windows 10 pro.
install node v6 LT
install onvif  (npm install onvif)
make file with exsample code from web site.
and run it.

### supporting information:

 - `npm -v` prints:
C:\Onvif\node\node_modules\onvif>npm -v
3.10.10
 - `node -v` prints:
C:\Onvif\node\node_modules\onvif>node -v
v6.10.2
 - `npm config get registry` prints:
C:\Onvif\node\node_modules\onvif>npm config get registry
https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?:
windows 10 pro

**Comment by KenanY** [comment]
I think what you mean to be doing is `node QuickExsample.js`.

**Comment by KenanY** [comment]
Closing due to no reply after a month.
