### ISSUE TITLE
Hi! Help me, please!

### ISSUE THREAD

**Issue by KazminaT** [npm/npm#16334]
I can't install anything with "npm install". Even if i try to execute `npm install --global npm@latest` i've got an error.

OS: Windows7 Professional 64-bit

my npm-debug.log file:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--global',
1 verbose cli   'npm@latest' ]
2 info using npm@3.10.10
3 info using node@v6.10.2
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData npm@latest
8 silly fetchNamedPackageData npm
9 silly mapToRegistry name npm
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'npm',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'npm',
12 silly mapToRegistry   name: 'npm',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/npm
14 verbose request uri https://registry.npmjs.org/npm
15 verbose request no auth needed
16 info attempt registry request try #1 at 14:45:49
17 verbose request id 3bc10d264cb60119
18 http request GET https://registry.npmjs.org/npm
19 info retry will retry, error on last attempt: Error: connect ENOTCONN 151.101.84.162:443
20 info attempt registry request try #2 at 14:46:20
21 http request GET https://registry.npmjs.org/npm
22 info retry will retry, error on last attempt: Error: connect ENOTCONN 151.101.84.162:443
23 info attempt registry request try #3 at 14:47:41
24 http request GET https://registry.npmjs.org/npm
25 silly fetchPackageMetaData Error: connect ENOTCONN 151.101.84.162:443
25 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1018:11)
25 silly fetchPackageMetaData     at exports._exceptionWithHostPort (util.js:1041:20)
25 silly fetchPackageMetaData     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
25 silly fetchPackageMetaData  error for npm@latest { Error: connect ENOTCONN 151.101.84.162:443
25 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1018:11)
25 silly fetchPackageMetaData     at exports._exceptionWithHostPort (util.js:1041:20)
25 silly fetchPackageMetaData     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
25 silly fetchPackageMetaData   code: 'ENOTCONN',
25 silly fetchPackageMetaData   errno: 'ENOTCONN',
25 silly fetchPackageMetaData   syscall: 'connect',
25 silly fetchPackageMetaData   address: '151.101.84.162',
25 silly fetchPackageMetaData   port: 443 }
26 silly rollbackFailedOptional Starting
27 silly rollbackFailedOptional Finishing
28 silly runTopLevelLifecycles Finishing
29 silly install printInstalled
30 verbose stack Error: connect ENOTCONN 151.101.84.162:443
30 verbose stack     at Object.exports._errnoException (util.js:1018:11)
30 verbose stack     at exports._exceptionWithHostPort (util.js:1041:20)
30 verbose stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
31 verbose cwd C:\Users\tatiana.kazmina
32 error Windows_NT 6.1.7601
33 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--global" "npm@latest"
34 error node v6.10.2
35 error npm  v3.10.10
36 error code ENOTCONN
37 error errno ENOTCONN
38 error syscall connect
39 error connect ENOTCONN 151.101.84.162:443
40 error If you need help, you may report this error at:
40 error     <https://github.com/npm/npm/issues>
41 verbose exit [ 1, true ]

Proxies and registry checks:
`C:\Users\tatiana.kazmina>npm config get registry
https://registry.npmjs.org/

C:\Users\tatiana.kazmina>npm config get http-proxy
undefined

C:\Users\tatiana.kazmina>npm config get https-proxy
null`

Ping 151.101.84.162 - is OK.

**Comment by KazminaT** [comment]
Problem was in my company's proxy... I've set proxy settings with 
`npm config set proxy http://proxy.company.com:8080
npm config set https-proxy http://proxy.company.com:8080` and my current parameters.

**Comment by NicolasMainardi** [comment]
I've already tried also with:
npm config set proxy http://nmainardi:password@172.21.7.8:8080
npm config set https-proxy http://nmainardi:password@172.21.7.8:8080
But it's still not working.

**Comment by NicolasMainardi** [comment]
C:\Users\nmainardi>npm install angular@1.6.5
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "angular@1.6.5"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ECONNRESET

npm ERR! network tunneling socket could not be established, cause=connect ENOTCO
NN 172.21.7.8:8080
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\nmainardi\npm-debug.log


And logs:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'angular@1.6.5' ]
2 info using npm@3.10.10
3 info using node@v6.11.3
4 verbose config Skipping project config: C:\Users\nmainardi/.npmrc. (matches userconfig)
5 silly loadCurrentTree Starting
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 silly fetchPackageMetaData angular@1.6.5
9 silly fetchNamedPackageData angular
10 silly mapToRegistry name angular
11 silly mapToRegistry using default registry
12 silly mapToRegistry registry https://registry.npmjs.org/
13 silly mapToRegistry data Result {
13 silly mapToRegistry   raw: 'angular',
13 silly mapToRegistry   scope: null,
13 silly mapToRegistry   escapedName: 'angular',
13 silly mapToRegistry   name: 'angular',
13 silly mapToRegistry   rawSpec: '',
13 silly mapToRegistry   spec: 'latest',
13 silly mapToRegistry   type: 'tag' }
14 silly mapToRegistry uri https://registry.npmjs.org/angular
15 verbose request uri https://registry.npmjs.org/angular
16 verbose request no auth needed
17 info attempt registry request try #1 at 16:53:31
18 verbose request id 5cb2c3d221c8f299
19 http request GET https://registry.npmjs.org/angular
20 info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=connect ENOTCONN 172.21.7.8:8080
21 info attempt registry request try #2 at 16:53:42
22 http request GET https://registry.npmjs.org/angular
23 info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=connect ENOTCONN 172.21.7.8:8080
24 info attempt registry request try #3 at 16:54:43
25 http request GET https://registry.npmjs.org/angular
26 silly fetchPackageMetaData Error: tunneling socket could not be established, cause=connect ENOTCONN 172.21.7.8:8080
26 silly fetchPackageMetaData     at ClientRequest.onError (C:\Program Files\nodejs\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:176:17)
26 silly fetchPackageMetaData     at ClientRequest.g (events.js:292:16)
26 silly fetchPackageMetaData     at emitOne (events.js:96:13)
26 silly fetchPackageMetaData     at ClientRequest.emit (events.js:188:7)
26 silly fetchPackageMetaData     at Socket.socketErrorListener (_http_client.js:310:9)
26 silly fetchPackageMetaData     at emitOne (events.js:96:13)
26 silly fetchPackageMetaData     at Socket.emit (events.js:188:7)
26 silly fetchPackageMetaData     at emitErrorNT (net.js:1277:8)
26 silly fetchPackageMetaData     at _combinedTickCallback (internal/process/next_tick.js:80:11)
26 silly fetchPackageMetaData     at process._tickCallback (internal/process/next_tick.js:104:9)
26 silly fetchPackageMetaData  error for angular@1.6.5 { Error: tunneling socket could not be established, cause=connect ENOTCONN 172.21.7.8:8080
26 silly fetchPackageMetaData     at ClientRequest.onError (C:\Program Files\nodejs\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:176:17)
26 silly fetchPackageMetaData     at ClientRequest.g (events.js:292:16)
26 silly fetchPackageMetaData     at emitOne (events.js:96:13)
26 silly fetchPackageMetaData     at ClientRequest.emit (events.js:188:7)
26 silly fetchPackageMetaData     at Socket.socketErrorListener (_http_client.js:310:9)
26 silly fetchPackageMetaData     at emitOne (events.js:96:13)
26 silly fetchPackageMetaData     at Socket.emit (events.js:188:7)
26 silly fetchPackageMetaData     at emitErrorNT (net.js:1277:8)
26 silly fetchPackageMetaData     at _combinedTickCallback (internal/process/next_tick.js:80:11)
26 silly fetchPackageMetaData     at process._tickCallback (internal/process/next_tick.js:104:9) code: 'ECONNRESET' }
27 silly rollbackFailedOptional Starting
28 silly rollbackFailedOptional Finishing
29 silly runTopLevelLifecycles Finishing
30 silly install printInstalled
31 verbose stack Error: tunneling socket could not be established, cause=connect ENOTCONN 172.21.7.8:8080
31 verbose stack     at ClientRequest.onError (C:\Program Files\nodejs\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:176:17)
31 verbose stack     at ClientRequest.g (events.js:292:16)
31 verbose stack     at emitOne (events.js:96:13)
31 verbose stack     at ClientRequest.emit (events.js:188:7)
31 verbose stack     at Socket.socketErrorListener (_http_client.js:310:9)
31 verbose stack     at emitOne (events.js:96:13)
31 verbose stack     at Socket.emit (events.js:188:7)
31 verbose stack     at emitErrorNT (net.js:1277:8)
31 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:80:11)
31 verbose stack     at process._tickCallback (internal/process/next_tick.js:104:9)
32 verbose cwd C:\Users\nmainardi
33 error Windows_NT 6.1.7601
34 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "angular@1.6.5"
35 error node v6.11.3
36 error npm  v3.10.10
37 error code ECONNRESET
38 error network tunneling socket could not be established, cause=connect ENOTCONN 172.21.7.8:8080
39 error network This is most likely not a problem with npm itself
39 error network and is related to network connectivity.
39 error network In most cases you are behind a proxy or have bad network settings.
39 error network
39 error network If you are behind a proxy, please make sure that the
39 error network 'proxy' config is set properly.  See: 'npm help config'
40 verbose exit [ 1, true ]

Need I open a new issue? Why you closed it?

**Comment by Pranacoin** [comment]
Hi! I 've closed the issue because in my case commands npm config set proxy... and npm config set https-proxy ... helped me to solve my problem.

**Comment by NicolasMainardi** [comment]
So I have to open a new one?

**Comment by Pranacoin** [comment]
Look at this article, may be it can help you - [https://jjasonclark.com/how-to-setup-node-behind-web-proxy/](url). If it can't - I think you should open a new issue, because the problem may not be in proxy settings.

**Comment by NicolasMainardi** [comment]
Sorry, I was certain that this was my post. Ahah, pardon.
