### ISSUE TITLE
hide all packages not in dependencies/devDependencies

### ISSUE THREAD

**Issue by calidion** [npm/npm#16332]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [X ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

node_modules is a messy.

#### How can the CLI team reproduce the problem?
npm install <package>

### supporting information:

 - `npm -v` prints:  all
 - `node -v` prints: all
 - `npm config get registry` prints: all
 - Windows, OS X/macOS, or Linux?:  all
 - Network issues:
   - Geographic location where npm was run: all

**Comment by KenanY** [comment]
@calidion Hmm, I don't understand the request here. Could you elaborate further?

**Comment by legodude17** [comment]
Try `npm ls --depth=0`.

**Comment by KenanY** [comment]
Closing due to no reply after a month.
