### ISSUE TITLE
Cannot publish npm package in private nexus repo

### ISSUE THREAD

**Issue by mdhani** [npm/npm#16333]
#### What's going wrong?
npm publish --registry http://localhost:8081/repository/npm-proxy/

npm ERR! publish Failed PUT 404
npm ERR! code E404
npm ERR! 404 Not Found

#### How can the CLI team reproduce the problem?

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\mdhani\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'publish',
1 verbose cli   '--registry',
1 verbose cli   'http://localhost:8081/repository/npm-proxy/' ]
2 info using npm@4.5.0
3 info using node@v4.4.7
4 verbose publish [ '.' ]
5 silly cache add args [ '.', null ]
6 verbose cache add spec .
7 silly cache add parsed spec Result {
7 silly cache add   raw: '.',
7 silly cache add   scope: null,
7 silly cache add   escapedName: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: '.',
7 silly cache add   spec: 'C:\\Users\\mdhani\\Desktop\\IEA-Merge\\Decouple-Generator\\d2-generator-iea',
7 silly cache add   type: 'directory' }
8 verbose addLocalDirectory C:\Users\mdhani\AppData\Roaming\npm-cache\generator-iea\2.0.0\package.tgz not in flight; packing
9 verbose correctMkdir C:\Users\mdhani\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
10 info lifecycle generator-iea@2.0.0~prepublish: generator-iea@2.0.0
11 silly lifecycle generator-iea@2.0.0~prepublish: no script for prepublish, continuing
12 info lifecycle generator-iea@2.0.0~prepare: generator-iea@2.0.0
13 silly lifecycle generator-iea@2.0.0~prepare: no script for prepare, continuing
14 verbose tar pack [ 'C:\\Users\\mdhani\\AppData\\Roaming\\npm-cache\\generator-iea\\2.0.0\\package.tgz',
14 verbose tar pack   'C:\\Users\\mdhani\\Desktop\\IEA-Merge\\Decouple-Generator\\d2-generator-iea' ]
15 verbose tarball C:\Users\mdhani\AppData\Roaming\npm-cache\generator-iea\2.0.0\package.tgz
16 verbose folder C:\Users\mdhani\Desktop\IEA-Merge\Decouple-Generator\d2-generator-iea
17 verbose addLocalTarball adding from inside cache C:\Users\mdhani\AppData\Roaming\npm-cache\generator-iea\2.0.0\package.tgz
18 verbose correctMkdir C:\Users\mdhani\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
19 silly cache afterAdd generator-iea@2.0.0
20 verbose afterAdd C:\Users\mdhani\AppData\Roaming\npm-cache\generator-iea\2.0.0\package\package.json not in flight; writing
21 verbose correctMkdir C:\Users\mdhani\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
22 verbose afterAdd C:\Users\mdhani\AppData\Roaming\npm-cache\generator-iea\2.0.0\package\package.json written
23 silly publish { name: 'generator-iea',
23 silly publish   version: '2.0.0',
23 silly publish   description: 'Yeoman generator for RequireJS based iea apps.',
23 silly publish   keywords:
23 silly publish    [ 'yeoman-generator',
23 silly publish      'scaffold',
23 silly publish      'framework',
23 silly publish      'mvc',
23 silly publish      'backbone',
23 silly publish      'require',
23 silly publish      'gsap' ],
23 silly publish   homepage: 'https://bitbucket.org/avinash_digital20_platform/d2-generator-iea.git',
23 silly publish   bugs: { url: 'https://tools.publicis.sapient.com/jira/browse/CPGI' },
23 silly publish   author: { name: 'Unilever-IEA Team' },
23 silly publish   main: 'app/index.js',
23 silly publish   repository:
23 silly publish    { type: 'git',
23 silly publish      url: 'git+https://bitbucket.org/avinash_digital20_platform/d2-generator-iea.git' },
23 silly publish   dependencies: { 'yeoman-generator': '~0.13.0', del: '^2.2.2' },
23 silly publish   publishConfig: { registry: 'http://localhost:8081/repository/npm-proxy/' },
23 silly publish   peerDependencies: { 'generator-mocha': '~0.1.1', yo: '>=1.0.0-rc.1.1' },
23 silly publish   devDependencies: { mocha: '~1.12.0' },
23 silly publish   engines: { node: '>=0.10.21', npm: '>=1.3.11' },
23 silly publish   licenses: [ { type: 'MIT' } ],
23 silly publish   readmeFilename: 'README.md',
23 silly publish   gitHead: 'd83a89905f8dde62a2db6299a3e4775495673dcb',
23 silly publish   _id: 'generator-iea@2.0.0',
23 silly publish   scripts: {},
23 silly publish   _shasum: 'f220fd4ba9f065e3d20d8b2ff6ad37274bf7aa60',
23 silly publish   _from: '.' }
24 info lifecycle generator-iea@2.0.0~prepublishOnly: generator-iea@2.0.0
25 silly lifecycle generator-iea@2.0.0~prepublishOnly: no script for prepublishOnly, continuing
26 verbose getPublishConfig { registry: 'http://localhost:8081/repository/npm-proxy/' }
27 silly mapToRegistry name generator-iea
28 silly mapToRegistry using default registry
29 silly mapToRegistry registry http://localhost:8081/repository/npm-proxy/
30 silly mapToRegistry data Result {
30 silly mapToRegistry   raw: 'generator-iea',
30 silly mapToRegistry   scope: null,
30 silly mapToRegistry   escapedName: 'generator-iea',
30 silly mapToRegistry   name: 'generator-iea',
30 silly mapToRegistry   rawSpec: '',
30 silly mapToRegistry   spec: 'latest',
30 silly mapToRegistry   type: 'tag' }
31 silly mapToRegistry uri http://localhost:8081/repository/npm-proxy/generator-iea
32 verbose publish registryBase http://localhost:8081/repository/npm-proxy/
33 silly publish uploading C:\Users\mdhani\AppData\Roaming\npm-cache\generator-iea\2.0.0\package.tgz
34 verbose request uri http://localhost:8081/repository/npm-proxy/generator-iea
35 verbose request sending authorization for write operation
36 info attempt registry request try #1 at 4:44:24 PM
37 verbose request using bearer token for auth
38 verbose request id 22b7b3213d5bca84
39 http request PUT http://localhost:8081/repository/npm-proxy/generator-iea
40 http 404 http://localhost:8081/repository/npm-proxy/generator-iea
41 verbose headers { date: 'Thu, 13 Apr 2017 11:14:24 GMT',
41 verbose headers   server: 'Nexus/3.3.0-01 (OSS)',
41 verbose headers   'x-frame-options': 'SAMEORIGIN',
41 verbose headers   'x-content-type-options': 'nosniff',
41 verbose headers   'content-length': '0' }
42 verbose request invalidating C:\Users\mdhani\AppData\Roaming\npm-cache\localhost_8081\repository\npm-proxy\generator-iea on PUT
43 error publish Failed PUT 404
44 verbose stack Error: 404 Not Found
44 verbose stack     at makeError (C:\Users\mdhani\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-client\lib\request.js:308:12)
44 verbose stack     at CachingRegistryClient.<anonymous> (C:\Users\mdhani\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-client\lib\request.js:259:9)
44 verbose stack     at Request._callback (C:\Users\mdhani\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-client\lib\request.js:216:14)
44 verbose stack     at Request.self.callback (C:\Users\mdhani\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:188:22)
44 verbose stack     at emitTwo (events.js:87:13)
44 verbose stack     at Request.emit (events.js:172:7)
44 verbose stack     at Request.<anonymous> (C:\Users\mdhani\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:1171:10)
44 verbose stack     at emitOne (events.js:77:13)
44 verbose stack     at Request.emit (events.js:169:7)
44 verbose stack     at IncomingMessage.<anonymous> (C:\Users\mdhani\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:1091:12)
45 verbose statusCode 404
46 verbose cwd C:\Users\mdhani\Desktop\IEA-Merge\Decouple-Generator\d2-generator-iea
47 verbose Windows_NT 6.1.7601
48 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mdhani\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "publish" "--registry" "http://localhost:8081/repository/npm-proxy/"
49 verbose node v4.4.7
50 verbose npm  v4.5.0
51 error code E404
52 error 404 Not Found
53 verbose exit [ 1, true ]

**Comment by legodude17** [comment]
This appears to be a problem with your private repository.
