### ISSUE TITLE
Unable to update webdriver-manager (window)

### ISSUE THREAD

**Issue by msz5213** [npm/npm#16338]
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 216.58.219.208:443
    at Object.exports._errnoException (util.js:1034:11)
    at exports._exceptionWithHostPort (util.js:1057:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1096:14)

-----------------------------------------------------------------------------------------

C:\Users\mdzaman\Workspace\JCDecauxUIT>npm install -g webdriver-manager update
npm ERR! git clone --template=C:\Users\mdzaman\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:jonschlinkert/resolve-file.git C:\Users\mdzaman\AppData\Roaming\npm-cache\_git-remotes\git-git
hub-com-jonschlinkert-resolve-file-git-93b2d6e1: Cloning into bare repository 'C:\Users\mdzaman\AppData\Roaming\npm-cache\_git-remotes\git-github-com-jonschlinkert-resolve-file-git-93b2d6e1'...
npm ERR! git clone --template=C:\Users\mdzaman\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:jonschlinkert/resolve-file.git C:\Users\mdzaman\AppData\Roaming\npm-cache\_git-remotes\git-git
hub-com-jonschlinkert-resolve-file-git-93b2d6e1: ssh: connect to host github.com port 22: Connection timed out
npm ERR! git clone --template=C:\Users\mdzaman\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:jonschlinkert/resolve-file.git C:\Users\mdzaman\AppData\Roaming\npm-cache\_git-remotes\git-git
hub-com-jonschlinkert-resolve-file-git-93b2d6e1: fatal: Could not read from remote repository.
npm ERR! git clone --template=C:\Users\mdzaman\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:jonschlinkert/resolve-file.git C:\Users\mdzaman\AppData\Roaming\npm-cache\_git-remotes\git-git
hub-com-jonschlinkert-resolve-file-git-93b2d6e1:
npm ERR! git clone --template=C:\Users\mdzaman\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:jonschlinkert/resolve-file.git C:\Users\mdzaman\AppData\Roaming\npm-cache\_git-remotes\git-git
hub-com-jonschlinkert-resolve-file-git-93b2d6e1: Please make sure you have the correct access rights
npm ERR! git clone --template=C:\Users\mdzaman\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:jonschlinkert/resolve-file.git C:\Users\mdzaman\AppData\Roaming\npm-cache\_git-remotes\git-git
hub-com-jonschlinkert-resolve-file-git-93b2d6e1: and the repository exists.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "webdriver-manager" "update"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\mdzaman\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:jonschlinkert/resolve-file.git C:\Users\mdzaman\AppData
\Roaming\npm-cache\_git-remotes\git-github-com-jonschlinkert-resolve-file-git-93b2d6e1
npm ERR! Cloning into bare repository 'C:\Users\mdzaman\AppData\Roaming\npm-cache\_git-remotes\git-github-com-jonschlinkert-resolve-file-git-93b2d6e1'...
npm ERR! ssh: connect to host github.com port 22: Connection timed out
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by legodude17** [comment]
Do you have correct access rights and does the repo exist?

**Comment by msz5213** [comment]
Yes, I do have the correct access rights and repo exist. 
What I did : 
1. Run : npm install -g protractor --> Successful.
2. Run: webdriver-manager update --> 
Error : events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 216.58.219.208:443
    at Object.exports._errnoException (util.js:1034:11)
    at exports._exceptionWithHostPort (util.js:1057:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1096:14)

**Comment by legodude17** [comment]
Can you `git clone git@github.com:jonschlinkert/resolve-file.git`?

**Comment by msz5213** [comment]
I made it works!!

**Comment by legodude17** [comment]
So you are no longer experiencing this issue?
