### ISSUE TITLE
Error trying to install wt package

### ISSUE THREAD

**Issue by minn-tex** [npm/npm#16349]
I tried to install wt on my mac with the following command line:

# npm i -g wt-cli

npm gave the following errors:

792 error Error: No compatible version found: concat-stream@'^1.5.1'
792 error Valid install targets:
792 error ["0.0.1","0.0.2","0.0.3","0.0.4","0.0.5","0.0.6","0.0.7","0.0.8","0.0.9","0.1.0","0.1.1","1.0.0","1.0.1","1.1.0","1.2.0","1.2.1","1.3.0","1.3.1","1.4.0","1.4.1","1.4.2","1.4.3","1.4.4","1.4.5","1.4.6","1.4.7","1.4.8","1.4.10","1.5.0","1.5.1","1.5.2","1.6.0"]
792 error     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:685:10)
792 error     at /usr/local/lib/node_modules/npm/lib/cache.js:607:10
792 error     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
792 error     at Object.oncomplete (fs.js:107:15)
793 error If you need help, you may report this log at:
793 error     <http://github.com/isaacs/npm/issues>
793 error or email it to:
793 error     <npm-@googlegroups.com>
794 error System Darwin 16.4.0
795 error command "node" "/usr/local/bin/npm" "i" "-g" "wt-cli"
796 error cwd /Users/username
797 error node -v v0.10.3
798 error npm -v 1.2.17
799 verbose exit [ 1, true ]

The installation exits and fails at this point.  Any ideas how to fix the issue.  I'm fairly new to this.

thanks!

**Comment by legodude17** [comment]
Please update your `npm` to at least `4.5.0`, as `npm@1` is very old and not supported.

**Comment by KenanY** [comment]
Closing since that version of `npm` is no longer supported, and the specific issue you are seeing (the `^` semver range not being recognized) is 100% non-existent in the latest stable version of `npm`.
