### ISSUE TITLE
shasum check failed while installing cordova 

### ISSUE THREAD

**Issue by akki199421** [npm/npm#16344]
#### I'm opening this issue because:

  - [ ] npm is producing an incorrect install.

#### What's going wrong?

Shasum check failed while installing Cordova
C:\Users\dd\AppData\Roaming>npm install cordova -g
npm ERR! shasum check failed for C:\Users\dd\AppData\Local\Temp\npm-3708-01f
746cd\registry.npmjs.org\bplist-parser\-\bplist-parser-0.1.1.tgz
npm ERR! Expected: d60d5dcc20cba6dc7e1f299b35d3e1f95dafbae6
npm ERR! Actual:   1bcb7c034ce77b5c7a56607ed87f75250762064c
npm ERR! From:     https://registry.npmjs.org/bplist-parser/-/bplist-parser-0.1.
1.tgz

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dd\AppData\Roaming\npm-cache\_logs\2017-04-14T07_17_26
_009Z-debug.log

#### How can the CLI team reproduce the problem?

Debug file gist - https://gist.github.com/akki199421/f6732ebf81d77a431184e76e1aa2a4f5

### supporting information:

node -v 
 v6.9.1

npm-v 
 v4.5.0

NOTE: I have tried npm cache clear, setting registry to "http://registry.npmjs.org/", run all this with administrator rights and without, tried reinstalling node. I have set all the paths correctly. Also using latest node and npm version. I am currently on Windows 7.

**Comment by legodude17** [comment]
Do you have a proxy or VPN?

**Comment by ganeshkolhe4392** [comment]
I had a same issue. I tried to run CLI (command prompt) as a administrator and it works.

**Comment by akki199421** [comment]
@legodude17  I do have a proxy but they are set correctly. I have no problem installing other packages.

@ganeshkolhe4392  I tried that too but it's not working.

**Comment by legodude17** [comment]
Does it work without the proxy?

**Comment by akki199421** [comment]
@legodude17  Yes it does on my personal computer but not oat work. I am behind a corporate proxy and it does not work there. I can install other packages but not Cordova.

**Comment by legodude17** [comment]
Is the proxy configured correctly for `npm`? Is `npm` configured correctly for the proxy?

**Comment by akki199421** [comment]
@legodude17 npm is correctly configured for proxy but not sure if the proxy is configured correctly for npm. Thanks for the tip, will check the proxy.
