### ISSUE TITLE
npm安装webpack失败

### ISSUE THREAD

**Issue by xuewanyun** [npm/npm#16346]
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "F:\\node\\node.exe" "F:\\node\\node_modules\\npm\\bin\\npm-cli.js" "install" "webpack" "--save-dev"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ENOSELF

npm ERR! Refusing to install webpack as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     E:\webpack\npm-debug.log
### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@xuewanyun Make sure the `"name"` property in your `package.json` is not set to `"webpack"`. Change it to something more unique.

**Comment by legodude17** [comment]
Make sure that the name field in your `package.json` is not set to `webpack`.

**Comment by KenanY** [comment]
Closing due to no reply after a month.
