### ISSUE TITLE
"error cb() never called!" "This is an error with npm itself. Please report this error at..."

### ISSUE THREAD

**Issue by 26medias** [npm/npm#16348]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [X] npm is producing an incorrect install.
  - [X] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

One of our packages, without any changes to it, couldn't be installed anymore, neither on Heroku nor locally. Even older versions can't be installed anymore.

I ran `npm cache clean`, it did not solve the issue.

I am the owner of that package, I can edit it or give you write access if you wish to run tests.

**Package:** `ftl-framework`
**Versions:** `1.0.2 and newer` (I tried all versions one by one, including "latest")
**NPM output**:
```
C:\xampp\htdocs\node-fw>npm install ftl-framework
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\julie\AppData\Roaming\npm-cache\_logs\2017-04-14T15_17_36_301Z-debug.log
```
**Log file:** https://pastebin.com/147yjmkk

#### How can the CLI team reproduce the problem?

run `npm install ftl-framework`

That is it. No need to specify any version or any flag.

### supporting information:

 - `npm -v` prints: `4.5.0`
 - `node -v` prints: `v6.9.1`
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?: `Windows 10 x64`
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
   - [X] None (High-speed cable internet in the middle of Manhattan)
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [X] I deploy to a PaaS (Triton, Heroku). (Push to heroku using `git push heroku master`. Same error there as on my local Windows 10 env)

**Comment by t4r0** [comment]
I am experiencing the same Issue, i think it's related to npm 4.5.0
on a linux machine with
node: 5.7.0

**Comment by kopertop** [comment]
Also experiencing this issue. Had it with npm 3.10.10 and npm 4.5.0, with nodejs version 6.10.1, 6.10.2, and 6.10.3.

Only appears with ```npm install```, doesn't happen when installing individual packages.

**Comment by kopertop** [comment]
After going through each package manually in my package.json, my issue turned out to be that I was trying to install ```serverless-plugin-typescript```

**Comment by 26medias** [comment]
I went thru everything and found a dependency of a dependency was the issue, corrupted package.
I changed to load the previous version, and it fixed it.

I wish the NPM log was more explicit about where the level occurred. It would have saved us many hours.

**Comment by Tbwas** [comment]
I am experiencing the same issue, npm version is 5.0.3.

**Comment by FlightToFreedom** [comment]
@Tbwas have you found a solution to this? i am having the same issue with 5.0.3

**Comment by FlightToFreedom** [comment]
For me it turned out to be a permissions issue, i was building via Jenkins with a dedicated user which could not access some /tmp/ directories under Jenkins home directory.
So try building as root first.

**Comment by Tbwas** [comment]
@FlightToFreedom I tried to uninstall and install npm many times, and then resolved the issue.

**Comment by tobbtechnologies** [comment]
14 error cb() never called!
15 error This is an error with npm itself. Please report this error at:
16 error <https://github.com/npm/npm/issues>

**Comment by AhmadSalmanKhan** [comment]
npm ERR!   cb() never called!
This is an npm error while installing node-red-dashboard
log can be found at _logs/2018-04-20T17_57_24_651Z-debug.log
