### ISSUE TITLE
installing geckodriver with sudo gives errors

### ISSUE THREAD

**Issue by johnvandermolen** [npm/npm#16347]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
`MacBook-Air-van-John:webdriverjs john$ sudo npm install -g geckodriver
Password:
npm ERR! not a package /Users/john/Desktop/webdriverjs/geckodriver
npm ERR! addLocal Could not install /Users/john/Desktop/webdriverjs/geckodriver
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "geckodriver"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0

npm ERR! Cannot read property 'path' of null
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/john/.npm/_logs/2017-04-14T14_30_26_472Z-debug.log
`

I can't figure out why this doesn't work....

#### How can the CLI team reproduce the problem?
run: sudo npm install -g geckodriver

[2017-04-14T14_31_02_928Z-debug kopie.txt](https://github.com/npm/npm/files/922266/2017-04-14T14_31_02_928Z-debug.kopie.txt)

npm -v 4.2.0
node -v v7.9.0

**Comment by KenanY** [comment]
@johnvandermolen Log file says you're running `npm install -g chromedriver`, but you say you're running `npm install -g geckodriver`.  Any idea why this is?

**Comment by johnvandermolen** [comment]
wrong file......
[2017-04-14T14_30_26_472Z-debug kopie.txt](https://github.com/npm/npm/files/923098/2017-04-14T14_30_26_472Z-debug.kopie.txt)

**Comment by KenanY** [comment]
@johnvandermolen Could you try `npm install -g geckodriver@latest` instead?

**Comment by johnvandermolen** [comment]
that worked.... Thus without sudo... 
With sudo i get `/usr/local/bin/geckodriver -> /usr/local/lib/node_modules/geckodriver/bin/geckodriver

> geckodriver@1.5.0 postinstall /usr/local/lib/node_modules/geckodriver
> node index.js

shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
path.js:1142
          cwd = process.cwd();
                        ^

Error: EACCES: permission denied, uv_cwd
    at Object.resolve (path.js:1142:25)
    at startup (bootstrap_node.js:125:32)
    at bootstrap_node.js:538:3
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "geckodriver@latest"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
`

**Comment by KenanY** [comment]
Hmm, that error is not coming from `npm` itself, but I'm not sure why using `sudo` would prevent one from getting their cwd.
