### ISSUE TITLE
Cannot update, access is denied

### ISSUE THREAD

**Issue by thany** [npm/npm#16345]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I get this banner in the console:
```
   ╭─────────────────────────────────────╮
   │                                     │
   │   Update available 4.4.4 → 4.5.0    │
   │     Run npm i -g npm to update      │
   │                                     │
   ╰─────────────────────────────────────╯
```

So when I do `sudo npm i -g npm` (shouldn't `sudo` be included in the banner message?...) it crashes with an "access denied" message:

```
martijn@Martijn-PC:~$ sudo npm i -g npm
npm ERR! path /usr/lib/node_modules/.staging/npm-18aca6f9/node_modules/npm-registry-client/node_modules/concat-stream/node_modules/typedarray
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall rename
npm ERR! Error: EACCES: permission denied, rename '/usr/lib/node_modules/.staging/npm-18aca6f9/node_modules/npm-registry-client/node_modules/concat-stream/node_modules/typedarray' -> '/usr/lib/node_modules/.staging/typedarray-f26739e1'
npm ERR!  { Error: EACCES: permission denied, rename '/usr/lib/node_modules/.staging/npm-18aca6f9/node_modules/npm-registry-client/node_modules/concat-stream/node_modules/typedarray' -> '/usr/lib/node_modules/.staging/typedarray-f26739e1'
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'rename',
npm ERR!   path: '/usr/lib/node_modules/.staging/npm-18aca6f9/node_modules/npm-registry-client/node_modules/concat-stream/node_modules/typedarray',
npm ERR!   dest: '/usr/lib/node_modules/.staging/typedarray-f26739e1' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/martijn/.npm/_logs/2017-04-14T08_06_42_845Z-debug.log
```
Here's that logfile: [2017-04-14T08_06_42_845Z-debug.zip](https://github.com/npm/npm/files/921720/2017-04-14T08_06_42_845Z-debug.zip)

#### How can the CLI team reproduce the problem?

Run NodeJS 7.9.0 and NPM 4.4.4 on WLS (Bash for Windows) and let it update itself via `sudo npm i -g npm`.

### supporting information:

 - `npm -v` prints: `4.4.4`
 - `node -v` prints: `v7.9.0`
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?: Linux on Windows
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by abhisheksoni27** [comment]
Try running the following command first:

`$ sudo su` (without the dollar sign, of course.)

And then when your terminal changes to something like `root@USERNAME$:` run the command to update npm.

`npm install -g npm`

**Comment by thany** [comment]
Works.

But this cannot be put into my all-in-one update script. Opening up a su-shell cannot be scripted (well it can, but it doesn't do anything other than wait for the shell to be closed).

**Comment by abhisheksoni27** [comment]
In either case, this is a problem with your OS and how your root account is setup.

But, even if you did put `sudo npm .. " in a script, you'd have to run the script with the sudo command anyway, right?

So, you can just put `sudo su` in the script first, and then the npm update command.

Correct me if I am wrong.

**Comment by thany** [comment]
I didn't set up anything as far as my sudo-ness is concerned. It's just default.

I don't believe `sudo su` can be scripted, because like I said, it just launces a new shell and waits for that to end.

**Comment by thany** [comment]
Update:

When I now do `sudo su` first and then the `npm i -g npm` command, I *still* get the same "permission denied" error.

**Comment by legodude17** [comment]
Try setting your global install location to `$HOME/.npm-packages` (`npm config set prefix "~/.npm-packages"`).

**Comment by thany** [comment]
That'll tie global installations to the current user. This is not really a solution - it's just stating the problem again.

**Comment by thany** [comment]
If you just supply NodeJS with the latest version (see [this issue](https://github.com/nodejs/node/issues/12641)), there wouldn't be a problem. Because when something doesn't work right, we're instructed to update NPM to the latest version, which doesn't work.

In other words, I can also forget about ever updating NPM and just consider the NodeJS-supplied version as "stock". It does leave the question: why. Why does NodeJS not come with the latest NPM? And why is NodeJS different from NPM - different companies it turns out! What the...?

**Comment by legodude17** [comment]
@thany 

> That'll tie global installations to the current user.

That is the point, you don't have permission to globally install packages.

> This is not really a solution

Yes it is, or you can give yourself permission to `/usr/lib`

**Comment by thany** [comment]
@legodude17 

> That is the point, you don't have permission to globally install packages.

The root user does. As a sudo user, I can happily delete `/usr/lib/node_modules/` as much as I want. I *do* have permissions there. Has it occurred to you npm might force itself to be as a certain user, instead of the user who starts the process? I don't know, but *something* is giving npm fewer permissions.

> Yes it is, or you can give yourself permission to `/usr/lib`

Like I said, I have all the permissions I need. Only npm doesn't seem to respect them.

**Comment by legodude17** [comment]
Just a thought, do you have an antivirus or something? It might be interfering with `npm`.
