### ISSUE TITLE
[proposal]allow to install a package's multi version.

### ISSUE THREAD

**Issue by Aladdin-ADD** [npm/npm#16352]
#### I'm opening this issue because:

 [x]Other (see below for feature requests):

#### What's the feature?
allow to install a package's multi version.
#### What problem is the feature intended to solve?
sometimes we need to install a package's multi version, but currently install another version will clean up the installed.
eg.
```bash
npm i eslint@2.x
npm i eslint@3.x #so there is only @3.x, and no @2.x.
```
maybe we can provide an option to prevent the default behavior.

**Comment by zkat** [comment]
unfortunately, npm can't do much about this for you: most solutions proposed around this involve somehow altering Node.js' module resolution algorithm, and that is extremely unlikely to happen. It's a very core, stable part of Node, and changing it could have some pretty big side-effects.

you can work around this by creating a separate package that depends on the other version, though: `eslint3` can depend on `eslint@3.x`, and your main package can depend on `eslint@2.x`, and you can determine for yourself what it means for it to have both of these dependencies.

You can even create such packages locally:
```
cd your/project
mkdir eslint3
cd eslint3
npm init -y
npm i -S eslint@3.x
cd ..
npm i -D ./eslint3
npm i -D eslint@2
```

That's about as good as it gets without massive changes to the infrastructure millions of people currently rely on, I think.

**Comment by Aladdin-ADD** [comment]
very thanks for your explanation. it does make sense.
