### ISSUE TITLE
Not working install serial port

### ISSUE THREAD

**Issue by karenYerevan** [npm/npm#16356]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'serialport',
1 verbose cli   '--build-from-source' ]
2 info using npm@3.10.10
3 info using node@v6.9.5
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData serialport
8 silly fetchNamedPackageData serialport
9 silly mapToRegistry name serialport
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'serialport',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'serialport',
12 silly mapToRegistry   name: 'serialport',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/serialport
14 verbose request uri https://registry.npmjs.org/serialport
15 verbose request no auth needed
16 info attempt registry request try #1 at 20:35:05
17 verbose request id 70aff84c4136f3cf
18 verbose etag W/"58a54516-3e168"
19 verbose lastModified Thu, 16 Feb 2017 06:22:14 GMT
20 http request GET https://registry.npmjs.org/serialport
21 http 200 https://registry.npmjs.org/serialport
22 verbose headers { server: 'nginx/1.10.1',
22 verbose headers   'content-type': 'application/json',
22 verbose headers   'last-modified': 'Sun, 12 Mar 2017 15:55:47 GMT',
22 verbose headers   etag: 'W/"58c56f83-3e1bd"',
22 verbose headers   'content-encoding': 'gzip',
22 verbose headers   'cache-control': 'max-age=300',
22 verbose headers   'content-length': '23734',
22 verbose headers   'accept-ranges': 'bytes',
22 verbose headers   date: 'Sun, 16 Apr 2017 16:35:06 GMT',
22 verbose headers   via: '1.1 varnish',
22 verbose headers   age: '0',
22 verbose headers   connection: 'keep-alive',
22 verbose headers   'x-served-by': 'cache-ams4137-AMS',
22 verbose headers   'x-cache': 'HIT',
22 verbose headers   'x-cache-hits': '1',
22 verbose headers   'x-timer': 'S1492360506.188000,VS0,VE7',
22 verbose headers   vary: 'Accept-Encoding' }
23 silly get cb [ 200,
23 silly get   { server: 'nginx/1.10.1',
23 silly get     'content-type': 'application/json',
23 silly get     'last-modified': 'Sun, 12 Mar 2017 15:55:47 GMT',
23 silly get     etag: 'W/"58c56f83-3e1bd"',
23 silly get     'content-encoding': 'gzip',
23 silly get     'cache-control': 'max-age=300',
23 silly get     'content-length': '23734',
23 silly get     'accept-ranges': 'bytes',
23 silly get     date: 'Sun, 16 Apr 2017 16:35:06 GMT',
23 silly get     via: '1.1 varnish',
23 silly get     age: '0',
23 silly get     connection: 'keep-alive',
23 silly get     'x-served-by': 'cache-ams4137-AMS',
23 silly get     'x-cache': 'HIT',
23 silly get     'x-cache-hits': '1',
23 silly get     'x-timer': 'S1492360506.188000,VS0,VE7',
23 silly get     vary: 'Accept-Encoding' } ]
24 verbose get saving serialport to C:\Users\Karen\AppData\Roaming\npm-cache\registry.npmjs.org\serialport\.cache.json
25 verbose correctMkdir C:\Users\Karen\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
26 silly install normalizeTree
27 silly loadCurrentTree Finishing
28 silly loadIdealTree Starting
29 silly install loadIdealTree
30 silly cloneCurrentTree Starting
31 silly install cloneCurrentTreeToIdealTree
32 silly cloneCurrentTree Finishing
33 silly loadShrinkwrap Starting
34 silly install loadShrinkwrap
35 silly loadShrinkwrap Finishing
36 silly loadAllDepsIntoIdealTree Starting
37 silly install loadAllDepsIntoIdealTree
38 silly rollbackFailedOptional Starting
39 silly rollbackFailedOptional Finishing
40 silly runTopLevelLifecycles Finishing
41 silly install printInstalled
42 verbose stack Error: Refusing to install serialport as a dependency of itself
42 verbose stack     at checkSelf (C:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:53:14)
42 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
42 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
42 verbose stack     at chain (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
42 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:16:5
42 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
42 verbose stack     at Array.forEach (native)
42 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
42 verbose stack     at Array.forEach (native)
42 verbose stack     at asyncMap (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
43 verbose cwd E:\node-serialport
44 error Windows_NT 10.0.14393
45 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "serialport" "--build-from-source"
46 error node v6.9.5
47 error npm  v3.10.10
48 error code ENOSELF
49 error Refusing to install serialport as a dependency of itself
50 error If you need help, you may report this error at:
50 error     <https://github.com/npm/npm/issues>
51 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@karenYerevan Can you try changing the `"name"` property in your `package.json` to something other than `"serialport"`?

**Comment by karenYerevan** [comment]
nothing has changed

**Comment by KenanY** [comment]
Hmm, I would have expected that to work though. Can I see `E:\node-serialport\package.json` by any chance?

**Comment by karenYerevan** [comment]
yes of course

{
  "name": "myseialtest",
  "version": "5.0.0-beta3",
  "description": "Node.js package to access serial ports. Welcome your robotic JavaScript overlords. Better yet, program them!",
  "author": {
    "name": "Chris Williams",
    "email": "voodootikigod@gmail.com",
    "url": "http://www.voodootikigod.com"
  },
  "binary": {
    "module_name": "serialport",
    "module_path": "build/{configuration}/",
    "host": "https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/5.0.0-beta3"
  },
  "main": "./lib",
  "repository": {
    "type": "git",
    "url": "git://github.com/EmergingTechnologyAdvisors/node-serialport.git"
  },
  "keywords": [
    "data logging",
    "hardware",
    "iot",
    "johnny-five",
    "nodebots",
    "serial port",
    "serialport"
  ],
  "maintainers": [
    {
      "name": "Jacob Rosenthal",
      "email": "jakerosenthal@gmail.com"
    },
    {
      "name": "Chris Williams",
      "email": "voodootikigod@gmail.com"
    },
    {
      "name": "Joe Ferner",
      "email": "joe.ferner@nearinfinity.com"
    },
    {
      "name": "Jay Beavers",
      "email": "jay@hikinghomeschoolers.org"
    },
    {
      "name": "Rob Giseburt",
      "email": "giseburt@gmail.com"
    },
    {
      "name": "Francis Gulotta",
      "email": "wizard@roborooter.com"
    }
  ],
  "dependencies": {
    "bindings": "1.2.1",
    "commander": "^2.9.0",
    "debug": "^2.4.5",
    "nan": "^2.4.0",
    "node-pre-gyp": "^0.6.32"
  },
  "devDependencies": {
    "chai": "^3.5.0",
    "chai-subset": "^1.2.2",
    "eslint": "^3.17.1",
    "eslint-config-standard": "^7.0.1",
    "eslint-plugin-promise": "^3.5.0",
    "eslint-plugin-require-path-exists": "^1.1.5",
    "eslint-plugin-standard": "^2.0.1",
    "istanbul": "^0.4.4",
    "jsdoc-to-markdown": "^3.0.0",
    "mocha": "^3.1.1",
    "node-pre-gyp-github": "^1.1.2",
    "proxyquire": "^1.7.10",
    "sinon": "^2.0.0"
  },
  "bundledDependencies": [
    "node-pre-gyp"
  ],
  "engines": {
    "node": ">= 4.0.0"
  },
  "bin": {
    "serialport-list": "./bin/serialport-list.js",
    "serialport-term": "./bin/serialport-terminal.js"
  },
  "license": "MIT",
  "scripts": {
    "arduino-test": "TEST_PORT=$(./bin/find-arduino.js) npm test",
    "docs": "jsdoc2md --no-cache -t .docs/README.hbs --partial .docs/sig-name.hbs --partial .docs/sig-link.hbs --partial .docs/edit-warning.hbs -r table --separators --name-format -f lib/* lib/bindings/* lib/parsers/* > README.md",
    "docs:diff": "jsdoc2md --no-cache -t .docs/README.hbs --partial .docs/sig-name.hbs --partial .docs/sig-link.hbs --partial .docs/edit-warning.hbs -r table --separators --name-format -f lib/* lib/bindings/* lib/parsers/* | diff -q README.md - || (echo 'Docs out of date, run `npm run docs` and commit the new README.md' && false)",
    "install": "node-pre-gyp install --fallback-to-build",
    "lint": "eslint lib test bin examples",
    "rebuild-all": "npm rebuild && node-gyp rebuild",
    "stress": "mocha --no-timeouts test/arduinoTest/stress.js",
    "test": "istanbul cover ./node_modules/mocha/bin/_mocha",
    "test:watch": "mocha -w",
    "valgrind": "TEST_PORT=$(./bin/find-arduino.js) valgrind --leak-check=full node test/manual-testing/memory-binding.js",
    "debugger": "TEST_PORT=$(./bin/find-arduino.js) node --inspect --debug-brk test/manual-testing/performance.js"
  },
  "gypfile": true
}

**Comment by KenanY** [comment]
Oh, do you wanna use `serialport` in a project of yours? If so, you should go to the directory of that project and run `npm install serialport --build-from-source` from there instead. Right now, it seems to me like you're trying to install `serialport` **into** the source directory of `serialport` itself, which `npm` will not allow you to do.

**Comment by karenYerevan** [comment]
Yeah I done it, but it not working for me.

Let me show you one elementary problem with serialport.

var SerialPort = require('serialport');
SerialPort.list(function (err, ports) {
  ports.forEach(function(port) {
    console.log(port.comName);
    console.log(port.pnpId);
    console.log(port.manufacturer);
  });
});

then output : 
COM5
BTHENUM\{00001101-0000-1000-8000-00805F9B34FB}_LOCALMFG&0045\8&FDD9097&0&E0CBEEB9E5DE_C00000000
Microsoft


but when i want connect :
var port = new SerialPort("COM5", {
  baudRate: 9600
});
then output : 
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Opening COM5: Unknown error code 121
    at Error (native)
*************************

What i do wrong?

**Comment by karenYerevan** [comment]
for this I haven't any package.json

I only install "npm install serialport"

**Comment by KenanY** [comment]
@karenYerevan If you need help using `serialport`, you should open an issue at <https://github.com/EmergingTechnologyAdvisors/node-serialport>. They can provide way more support than anyone here can.

**Comment by karenYerevan** [comment]
i did it... few minutes ago )))
thank you
