### ISSUE TITLE
Can not install a npm package (npm ERR! Darwin 16.5.0)

### ISSUE THREAD

**Issue by chamalC** [npm/npm#16351]
what I tried is to install Next.js using following command

`npm install next react react-dom --save`

but it is ended up with this error . here is the npm-debug.log https://gist.github.com/chamalC/0c8da8827f30106acc524db2dde0699b

**Comment by KenanY** [comment]
@chamalC Make sure the `'"name"` field in your `package.json` is not set to `"react"`. Make it something more unique :)

**Comment by aeciolevy** [comment]
@KenanY I tried it, however it does not work.

**Comment by KenanY** [comment]
@aeciolevy All right, can I see your `package.json` (feel free to remove any sensitive bits) and the debug log file? You can upload both of these to <https://gist.github.com/>.

**Comment by aeciolevy** [comment]
@KenanY this is the package.json and npm-log https://gist.github.com/aeciolevy/737a1f28646543cb4cd898feb042219a
it seems to be a yarn problem?

**Comment by KenanY** [comment]
@aeciolevy Yeah, your issue looks nothing like that of the OP. Instead, it seems like the following is returning error code:

```
yarn run clean && yarn run lint && yarn test && yarn run build && check-es3-syntax lib/ dist/ --kill --print
```

all `npm` is doing is catching it for you and letting you know about it.
