### ISSUE TITLE
permissions command doesn't work if missing directories

### ISSUE THREAD

**Issue by ORESoftware** [npm/npm#16359]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [X] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I am following the instructions in this doc:
https://docs.npmjs.com/getting-started/fixing-npm-permissions

I try to run this

` sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}`

But I get this error:

```
npm info ok 
chown: cannot access '/usr/local/{lib/node_modules,bin,share}': No such file or directory
The command '/bin/sh -c sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}' returned a non-zero code: 1
```

note: I am running this in a docker container

perhaps I should install something globally, and then the directories will get created?

**Comment by legodude17** [comment]
I think you might need to quote the glob.

**Comment by ORESoftware** [comment]
You mean like this:

`sudo chown -R $(whoami) $(npm config get prefix)/"{lib/node_modules,bin,share}"`

?

**Comment by legodude17** [comment]
I meant the `$(npm config get prefix)/{lib/node_modules,bin,share}`.

**Comment by ORESoftware** [comment]
ok thx
