### ISSUE TITLE
Unexpected behavior while listing owners.

### ISSUE THREAD

**Issue by Orbyt** [npm/npm#16357]
#### I'm opening this issue because:

  - [x ] npm is doing something I don't understand.

#### What's going wrong?

If you have a local npm package not published to npm, and run `npm owner ls`, if a package on npm matches the name of your local package it will list the owners of of the remote npm package.

This is a fairly confusing mechanic, and I'm not sure if it's intended or not. Is this something we should consider modifying?

#### How can the CLI team reproduce the problem?

Create blank npm package via `npm init` with a name of an existing npm package. Run `npm owner ls`.

**Comment by KenanY** [comment]
I presume that this also occurs if `"private"` is set to `true` in the `package.json`?

**Comment by Orbyt** [comment]
That's correct.

**Comment by KenanY** [comment]
Alright, we probably don't want to query the registry if the package is private, so I believe that's our fix here. If the local package is private, then don't get owners from the registry. Otherwise, assume that we want the owners of the local package from the registry.

**Comment by Orbyt** [comment]
Regardless of whether or not `"private": true` is set, when running `npm owner ls` after an `npm init`, I don't expect to see other users listed.

**Comment by KenanY** [comment]
@Orbyt But how can `npm` tell that you don't want to see owners?

For example, let's say I clone the `express` package into directory `test-a/`, and I `npm init` my own module, also named `express`, in directory `test-b/`. Thus, both of these local packages have the same name, but for only the former one are you expecting to see owners. How should `npm` figure out the difference between these two local packages in order to give you the behavior you're expecting?

**Comment by Orbyt** [comment]
I would assume npm can determine whether or not the current package lives on npm. If the package has not yet been published to npm, then it is a local package and should not list owners of an existing package with the same name.

**Comment by KenanY** [comment]
@Orbyt `npm` can do that; and it currently does that though the `"name"` field. I guess you are suggesting that it be made more comprehensive somehow?

**Comment by KenanY** [comment]
Closing due to no reply after a month.
