### ISSUE TITLE
Getting confused errors while trying to get repo from github

### ISSUE THREAD

**Issue by parthivreddy27** [npm/npm#16366]
npm ERR! addLocal Could not install /var/folders/g8/7g5nm9h94jjdzxcdvs80297w0000gq/T/npm-76220-d1a5f423/git-cache-00f9ddd1/365285d63ccb99c886a5f3ebb78dd2914d0a3143
npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code EISDIR
npm ERR! errno -21
npm ERR! syscall read

npm ERR! eisdir EISDIR: illegal operation on a directory, read
npm ERR! eisdir This is most likely not a problem with npm itself
npm ERR! eisdir and is related to npm not being able to find a package.json in
npm ERR! eisdir a package you are trying to install.

**Comment by legodude17** [comment]
What is the contents of your `package.json`?

**Comment by parthivreddy27** [comment]
Problem solved... I forgot to insert package.json file in my repository. Thank you much

**Comment by legodude17** [comment]
@parthivreddy27 Glad I could help!
