### ISSUE TITLE
missing script: prepublish

### ISSUE THREAD

**Issue by elfeffe** [npm/npm#16367]
I'm getting that error when I run:

`npm run-script prepublish`
Trying to install this:
https://github.com/christiaan/tinymce-codemirror

This is the log

> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/local/Cellar/node/7.9.0/bin/node',
> 1 verbose cli   '/usr/local/bin/npm',
> 1 verbose cli   'run-script',
> 1 verbose cli   'prepublish' ]
> 2 info using npm@4.2.0
> 3 info using node@v7.9.0
> 4 verbose stack Error: missing script: prepublish
> 4 verbose stack     at run (/usr/local/lib/node_modules/npm/lib/run-script.js:151:19)
> 4 verbose stack     at /usr/local/lib/node_modules/npm/lib/run-script.js:61:5
> 4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:356:5
> 4 verbose stack     at checkBinReferences_ (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:320:45)
> 4 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:354:3)
> 4 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:124:5)
> 4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:311:12
> 4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
> 4 verbose stack     at tryToString (fs.js:449:3)
> 4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:436:12)
> 5 verbose cwd /Users/fede/Documents/Dev/laravel/acelle/public/tinymce/plugins
> 6 error Darwin 16.5.0
> 7 error argv "/usr/local/Cellar/node/7.9.0/bin/node" "/usr/local/bin/npm" "run-script" "prepublish"
> 8 error node v7.9.0
> 9 error npm  v4.2.0
> 10 error missing script: prepublish
> 11 error If you need help, you may report this error at:
> 11 error     <https://github.com/npm/npm/issues>
> 12 verbose exit [ 1, true ]

Any fix?

**Comment by legodude17** [comment]
Can you format the log with line breaks? It is basically unreadable as is.

**Comment by elfeffe** [comment]
sure @legodude17 check it now to see if it's better

**Comment by legodude17** [comment]
The error log said you're missing the `prepublish` script. To use `npm run-script prepublish`, you need to put it into the script field in your `package.json` like:
```json
{
  "script": {
    "prepublish": "echo hi"
  }
}
```
See this example for your reference: https://docs.npmjs.com/misc/scripts#examples

Thanks
