### ISSUE TITLE
Error executing npm on WIndows 8.1 64 bits (Spanish  language)

### ISSUE THREAD

**Issue by gcardonat63** [npm/npm#16365]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [x] npm is doing something I don't understand.

Every time i run npm as for example

npm -v

the software shows: a warning message, it seems it execute things but i what i don't know
the message is:

D:\npm -v
"CALL "C:\Program Files\nodejs\\node,exe" "C;\Program Files\nodejs\\node_modules\npm\bin\npm-cli.js" prefix -g " no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
3.10.10

in English
"CALL "C:\Program Files\nodejs\\node,exe" "C;\Program Files\nodejs\\node_modules\npm\bin\npm-cli.js" prefix -g " is not recognized as an interal o external program
executable batch program or file.
3.10.10

Any help?

Guido Cardona
![errornpm](https://cloud.githubusercontent.com/assets/3118462/25092796/dac0d8e4-2354-11e7-8147-4ba00ca55c62.jpg)

**Comment by zkat** [comment]
Me parece a mi que hay algo mal con tu `$PATH` o tu instalación de Node.js. El error que ves quiere decir que `npm.cmd` está instalado y accesible, pero por alguna razón, no encuentra a node.

Dónde está tu node.exe?

**Comment by gcardonat63** [comment]
C:\Program Files\nodejs

**Comment by gcardonat63** [comment]
El si lo encuentra de hecho realiza la accion pero saca el mensaje que menciono y no se si esta quedando algo mal, el prooblema es con el parametro -g

**Comment by zkat** [comment]
@gcardonat63 pues en verdad que no sé por qué pasa eso, si todavía funciona bien npm en sí. Una cosa que puedes probar es volver a installar npm con `npm i -g npm@latest`, o puedes desinstalar y reinstalarlo.

No creo que te tienes que preocupar mucho por este error si npm todavía te funciona. No entiendo qué está ocurriendo con tu configuración que causa eso :<

**Comment by gcardonat63** [comment]
hola kat gracias por el apoyo

desistale como recomendaste lo reistale totalmente

borre manualmente todas las carpetas de node y js

en archivos de programa y user/appdata

y persiste el error


Guido Cardona


De: Kat Marchán <notifications@github.com>
Enviado: viernes, 21 de abril de 2017 4:13 p. m.
Para: npm/npm
Cc: gcardonat63; Mention
Asunto: Re: [npm/npm] Error executing npm on WIndows 8.1 64 bits (Spanish language) (#16365)


@gcardonat63<https://github.com/gcardonat63> pues en verdad que no sé por qué pasa eso, si todavía funciona bien npm en sí. Una cosa que puedes probar es volver a installar npm con npm i -g npm@latest, o puedes desinstalar y reinstalarlo.

No creo que te tienes que preocupar mucho por este error si npm todavía te funciona. No entiendo qué está ocurriendo con tu configuración que causa eso :<

**Comment by zkat** [comment]
Pues no sé qué decirte. Voy a marcarlo como `bug` por ahora, pero no entiendo por qué pasa.

Tu npm funciona normal de todas maneras, verdad? Puedes instalar cosas, etc? Parece que pudo ejecutar bien.

**Comment by zkat** [comment]
@gcardonat63 quiero verificar algo. Tu información original dice:

> "CALL "C:\Program Files\nodejs\node,exe" "C;\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" prefix -g " no se reconoce como un comando interno o externo,

Por qué hay una coma ahí? `node,exe` y `C;\Program Files\...` no son válidos.

**Comment by rakhel13** [comment]
Hola, yo tengo el mismo error que el compañero, y no me funciona instalar nada, intento hacerlo pero al final me tira errores y no me lo permite

**Comment by rakhel13** [comment]
![image](https://user-images.githubusercontent.com/31683154/30147437-90923408-935b-11e7-8a00-9d49659f2278.png)

**Comment by jonathanarvaez** [comment]
Confirm if you have administrator permissions when running.
