### ISSUE TITLE
Refusing to install simple-ssh as a dependency of itself

### ISSUE THREAD

**Issue by ChristianOmar20** [npm/npm#16368]
#### When using npm install simple-ssh

log information say

-error Windows_NT 6.1.7601
-error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "simple-ssh"
-error node v6.10.0
-error npm  v3.10.10
-error code ENOSELF
-error Refusing to install simple-ssh as a dependency of itself
-error If you need help, you may report this error at:
-error     <https://github.com/npm/npm/issues>
-verbose exit [ 1, true ]

**Comment by legodude17** [comment]
Please make sure that the `name` in your `package.json` is unique from any of your dependencies.
