### ISSUE TITLE
npm ERR! Windows_NT 6.1.7601

### ISSUE THREAD

**Issue by Basuchi** [npm/npm#16362]
![image](https://cloud.githubusercontent.com/assets/20046781/25090902/951397c4-23a3-11e7-8573-09741a61cc68.png)

**Comment by legodude17** [comment]
Hello! The error log said you're missing the `build` script. To use `npm run build`, you need to put it into the script field in your `package.json` like:
```json
{
  "script": {
    "start": "echo hi"
  }
}
```
See this example for your reference: https://docs.npmjs.com/misc/scripts#examples

Thanks

**Comment by Basuchi** [comment]
Hello,

After adding build. I am not getting any error but no bundle of .js files are generated, I want build it and take .js files then push it to my web application which i written in SPRING 4.

Kindly help me out for this. 

regards & thanks in advance.

**Comment by KenanY** [comment]
I'll close this since it's no longer an issue with `npm`, but feel free to continue discussion.
