### ISSUE TITLE
Getting error by installing package on Office network vagrant machine

### ISSUE THREAD

**Issue by abhi-das** [npm/npm#16375]
#### I'm opening this issue because:

  - [x] Getting error by installing package on Office network vagrant machine
  - [x] Maximum call stack size exceeded
  - [x] npm ERR! Linux 3.2.0-23-generic
  - [x] npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "backstopjs" "--save-dev"
  - [x] npm ERR! node v6.9.1
  - [x] npm ERR! npm  v3.10.8

#### What's going wrong?
Maximum call stack size exceeded

#### How can the CLI team reproduce the problem?

 $ sudo npm install backstopjs --save-dev

**Comment by abhi-das** [comment]
Getting error by installing package on Office network vagrant machine

**Comment by legodude17** [comment]
Please put your `npm-debug.log` in a gist and then post the link here.
