### ISSUE TITLE
npm run start

### ISSUE THREAD

**Issue by arshambh** [npm/npm#16373]
hello 
I want run Angular 2 on Visual Studio an I need Run this commend " npm run start  "
after that I run that comment it shows me this error:

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10

npm ERR! missing script: start
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\ALi\Desktop\ng2Mvc5Demo-master\ng2Mvc5Demo\npm-debug.log

**Comment by DonyZ-V** [comment]
You and I met the same problem @arshambh

**Comment by alex6971** [comment]
How to solve this problem？

**Comment by ericmdantas** [comment]
What's the content of your `package.json`?

**Comment by KenanY** [comment]
Hello! So, the way `npm start` works is that it looks in your current `package.json` for a defined `"start"` [script](https://docs.npmjs.com/misc/scripts), and then runs that. The error message you're seeing is trying to tell you that you have not defined a `"start"` script in your `package.json`, hence `npm start` has no idea what you want it to do.

To solve this issue, all you have to do is add a new script to your `package.json`. It might look something like this, for example:

``` json
{
  "name": "package-name",
  "version": "1.0.0",
  "description": "package description",
  "scripts": {
    "start": "node lib/server.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {},
  "devDependencies": {}
}
```

Note how this `package.json` has a `"start"` script that runs `node lib/server.js`. You'll definitely want to change the command to whatever is most appropriate for your project. I just randomly chose this one as an example.

**Comment by alex6971** [comment]
thank you a lot ！

2017-04-20 

alex6971 



发件人：Kenan Yildirim <notifications@github.com>
发送时间：2017-04-18 23:47
主题：Re: [npm/npm] npm run start (#16373)
收件人："npm/npm"<npm@noreply.github.com>
抄送："alex6971"<alex6971@163.com>,"Comment"<comment@noreply.github.com>

Hello! So, the way npm start works is that it looks in your current package.json for a defined "start" script, and then runs that. The error message you're seeing is trying to tell you that you have not defined a "start" script in your package.json, hence npm start has no idea what you want it to do.
To solve this issue, all you have to do is add a new script to your package.json. It might look something like this, for example:
{
  "name": "package-name",
  "version": "1.0.0",
  "description": "package description",
  "scripts": {
    "start": "node lib/server.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {},
  "devDependencies": {}
}
Note how this package.json has a "start" script that runs node lib/server.js. You'll definitely want to change the command to whatever is most appropriate for your project. I just randomly chose this one as an example.

**Comment by alex6971** [comment]
2017-04-20 

alex6971 



发件人："Eric M. Dantas" <notifications@github.com>
发送时间：2017-04-18 18:13
主题：Re: [npm/npm] npm run start (#16373)
收件人："npm/npm"<npm@noreply.github.com>
抄送："alex6971"<alex6971@163.com>,"Comment"<comment@noreply.github.com>

What's the content of your package.json?

**Comment by DonyZ-V** [comment]
I need to see the full error message @arshambh

**Comment by alex6971** [comment]
2017-04-21 

alex6971 



发件人：DonyZ <notifications@github.com>
发送时间：2017-04-21 17:22
主题：Re: [npm/npm] npm run start (#16373)
收件人："npm/npm"<npm@noreply.github.com>
抄送："alex6971"<alex6971@163.com>,"Comment"<comment@noreply.github.com>

I need to see the full error message @arshambh

**Comment by KenanY** [comment]
Closing due to no reply from the OP after a month. If anyone still has this issue, please open a new ticket.
