### ISSUE TITLE
npm install @angular/core@latest

### ISSUE THREAD

**Issue by Basuchi** [npm/npm#16370]
D:\TSA\onareportui>npm install @angular/core@latest
onareportui@1.0.0 D:\TSA\onareportui
+-- UNMET PEER DEPENDENCY @angular/core@4.0.2 invalid
+-- UNMET PEER DEPENDENCY rxjs@5.0.0-beta.12
`-- UNMET PEER DEPENDENCY zone.js@0.6.26

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN @angular/common@2.2.4 requires a peer of @angular/core@2.2.4 but none was installed.
npm WARN @angular/compiler@2.2.4 requires a peer of @angular/core@2.2.4 but none was installed.
npm WARN @angular/core@4.0.2 requires a peer of rxjs@^5.0.1 but none was installed.
npm WARN @angular/core@4.0.2 requires a peer of zone.js@^0.8.4 but none was installed.
npm WARN @angular/forms@2.2.4 requires a peer of @angular/core@2.2.4 but none was installed.
npm WARN @angular/http@2.2.4 requires a peer of @angular/core@2.2.4 but none was installed.
npm WARN @angular/platform-browser@2.2.4 requires a peer of @angular/core@2.2.4 but none was installed.
npm WARN @angular/platform-browser-dynamic@2.2.4 requires a peer of @angular/core@2.2.4 but none was installed.
npm WARN @angular/router@3.2.4 requires a peer of @angular/core@2.2.4 but none was installed.
npm WARN @angular/upgrade@2.2.4 requires a peer of @angular/core@2.2.4 but none was installed.
npm WARN angular2@2.0.0-beta.6 requires a peer of reflect-metadata@0.1.2 but none was installed.
npm WARN angular2@2.0.0-beta.6 requires a peer of rxjs@5.0.0-beta.0 but none was installed.
npm WARN angular2@2.0.0-beta.6 requires a peer of zone.js@0.5.14 but none was installed.
npm WARN ngx-modal@0.0.29 requires a peer of @angular/core@^2.0.0 but none was installed.
npm ERR! code 1

![image](https://cloud.githubusercontent.com/assets/20046781/25113929/8b7eaa8a-2418-11e7-9df9-8212956dd6f1.png)

**Comment by legodude17** [comment]
Make sure to install all of the peerDeps of all the packages you are installing.
