### ISSUE TITLE
Not able to install Cors on my system (npm install cors is not working)

### ISSUE THREAD

**Issue by Bhupesh82** [npm/npm#16372]
#### I'm opening this issue because:

  - [ ] npm is producing an incorrect install. 
  - [ ] npm is doing something I don't understand.
  - [ 1] Other (_see below for feature requests_):

#### What's going wrong?
I'm trying to install Cors however it is throwing below error:

31 error Windows_NT 6.1.7601
32 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "cors" "-g"
33 error node v6.9.1
34 error npm  v3.10.8
35 error Unexpected token < in JSON at position 0
35 error <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
35 error <html><head>
35 error <title>404 Not Found</title>
35 error </head><body>
35 error <h1>Not Found</h1>
35 error <p>The requested URL /cors was not found on this server.</p>
35 error <hr>
35 error <address>Apache/2.2.29 (Unix) mod_ssl/2.2.29 OpenSSL/1.0.1e-fips Server at registry.npmjs.org Port 80</address>
35 error </body></html>
36 error If you need help, you may report this error at:
36 error     <https://github.com/npm/npm/issues>
37 verbose exit [ 1, true ]

#### How can the CLI team reproduce the problem?
**simply run npm install cors -g** 

it is throwing error below is the complete debug log:

31 error Windows_NT 6.1.7601
32 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "cors" "-g"
33 error node v6.9.1
34 error npm  v3.10.8
35 error Unexpected token < in JSON at position 0
35 error <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
35 error <html><head>
35 error <title>404 Not Found</title>
35 error </head><body>
35 error <h1>Not Found</h1>
35 error <p>The requested URL /cors was not found on this server.</p>
35 error <hr>
35 error <address>Apache/2.2.29 (Unix) mod_ssl/2.2.29 OpenSSL/1.0.1e-fips Server at registry.npmjs.org Port 80</address>
35 error </body></html>
36 error If you need help, you may report this error at:
36 error     <https://github.com/npm/npm/issues>
37 verbose exit [ 1, true ]

### supporting information:

 - `npm -v` prints: 3.10.8
 - `node -v` prints: v6.9.1
 - `npm config get registry` prints: http://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows_NT 6.1.7601
 - Network issues:
   - Geographic location where npm was run: Noida/India
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.

 - Container:
NA

**Comment by legodude17** [comment]
Please go through the [troubleshooting guide](https://github.com/npm/npm/wiki/Troubleshooting).
