### ISSUE TITLE
Npm install ignores lower version module installation.

### ISSUE THREAD

**Issue by bhupendra-nitt** [npm/npm#16374]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [X] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
npm is not downgrading the version of node module if higher version is installed.
#### How can the CLI team reproduce the problem?

Have a higher version module installed of any module try to install a version which is lower than installed, it will fail.
-npm ERR! Linux 4.4.0-66-generic
-npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
-npm ERR! node v4.2.1
-npm ERR! npm  v2.14.7
-npm ERR! code EPEERINVALID

-npm ERR! peerinvalid The package eslint-plugin-react@3.16.1 does not satisfy its siblings' peerDependencies requirements!
-npm ERR! peerinvalid Peer eslint-config-airbnb@13.0.0 wants eslint-plugin-react@^6.6.0`

### supporting information:

 - `npm -v` prints: v2.14.7
 - `node -v` prints:  v4.2.1
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?: Linux
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@bhupendra-nitt Can I see an example `package.json` and a full list of steps to reproduce this?

**Comment by bhupendra-nitt** [comment]
```  "babel-core": "^6.5.1",
    "babel-eslint": "^4.1.8",
    "babel-jest": "^17.0.2",
    "enzyme": "^2.6.0",
    "eslint": "^1.10.3",
    "eslint-plugin-babel": "^3.1.0",
    "eslint-plugin-react": "^3.16.1",```

**Comment by bhupendra-nitt** [comment]
1. Install  "eslint-plugin-react": with a higher version,
2. run mpn install with  "eslint-plugin-react": with lower version, PEER DEPENDENCY warning will come.
that is the issue I am facing

**Comment by legodude17** [comment]
The problem isn't `npm`, it is that `eslint-config-airbnb` requires that you have that higher version installed in its peerDependencies.
