### ISSUE TITLE
npm failing to contact git behind cntlm

### ISSUE THREAD

**Issue by RohanMajumdar69** [npm/npm#16386]
#### I'm opening this issue because:
npm is crashing.

#### What's going wrong?
It is not able to contact github on one particular request

#### How can the CLI team reproduce the problem?
Run "npm install -g resume-cli" behind a cntlm

### supporting information:

 - `npm -v` prints:
10562 silly rollbackFailedOptional Starting
10563 silly rollbackFailedOptional Finishing
10564 silly runTopLevelLifecycles Finishing
10565 silly install printInstalled
10566 verbose stack Error: Command failed: git -c core.longpaths=true clone --template=C:\Users\inchunab\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:andyinabox/FileSaver.js.git C:\Users\inchunab\AppData\Roaming\npm-cache\_git-remotes\git-github-com-andyinabox-FileSaver-js-git-e433c213
10566 verbose stack       0 [main] git 11056 find_fast_cwd: WARNING: Couldn't compute FAST_CWD pointer.  Please report this problem to
10566 verbose stack the public mailing list cygwin@cygwin.com
10566 verbose stack ssh: Could not resolve hostname github.com: Temporary failure in name resolution
10566 verbose stack fatal: The remote end hung up unexpectedly
10566 verbose stack
10566 verbose stack     at ChildProcess.exithandler (child_process.js:204:12)
10566 verbose stack     at emitTwo (events.js:106:13)
10566 verbose stack     at ChildProcess.emit (events.js:191:7)
10566 verbose stack     at maybeClose (internal/child_process.js:886:16)
10566 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
10567 verbose cwd C:\Windows\system32
10568 error Windows_NT 10.0.14393
10569 error argv "E:\\TOOLS\\nodejs\\node.exe" "E:\\TOOLS\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "-f" "resume-cli"
10570 error node v6.10.2
10571 error npm  v3.10.10
10572 error code 128
10573 error Command failed: git -c core.longpaths=true clone --template=C:\Users\inchunab\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:andyinabox/FileSaver.js.git C:\Users\inchunab\AppData\Roaming\npm-cache\_git-remotes\git-github-com-andyinabox-FileSaver-js-git-e433c213
10573 error       0 [main] git 11056 find_fast_cwd: WARNING: Couldn't compute FAST_CWD pointer.  Please report this problem to
10573 error the public mailing list cygwin@cygwin.com
10573 error ssh: Could not resolve hostname github.com: Temporary failure in name resolution
10573 error fatal: The remote end hung up unexpectedly
10574 error If you need help, you may report this error at:
10574 error     <https://github.com/npm/npm/issues>
10575 verbose exit [ 1, true ]

 - `node -v` prints:
v6.10.2
 - `npm config get registry` prints:
https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ x ] I use a proxy to connect to the npm registry.
   - [ x ] I use a proxy to connect to the web.
   - [ x ] I use a proxy when downloading Git repos.

**Comment by legodude17** [comment]
This seems like a `git` issue. Is `git` configured for the proxy?
