### ISSUE TITLE
npm crashes instead of telling me a module is not available in the registry

### ISSUE THREAD

**Issue by gpakosz** [npm/npm#16389]
#### I'm opening this issue because:

  - [x] npm is crashing.

#### What's going wrong?

Instead of telling me a module doesn't exist in the registry, `npm` is crashing with:
```
npm ERR! Cannot read property 'path' of null
```
#### How can the CLI team reproduce the problem?

```
$ npm install -g non_existing_module
```
```
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/7.9.0/bin/node" "/usr/local/bin/npm" "install" "-g" "non_existing_module"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0

npm ERR! Cannot read property 'path' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/greedo/.npm/_logs/2017-04-19T11_47_40_363Z-debug.log
```

Debug log says
```
19 http 404 https://registry.npmjs.org/non_existing_module
```

The problem is that `curl  https://registry.npmjs.org/non_existing_module` returns an empty object `{}` while setting a 404 error code. I believe `npm` tries to dereference a key and to read the `path` property of the associated value.

### supporting information:

 - `npm -v` prints: `4.2.0`
 - `node -v` prints: `v7.9.0`
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?: `Darwin 15.6.0`

**Comment by legodude17** [comment]
Ref #10686 and all that reference it

**Comment by gpakosz** [comment]
> opened this issue on Dec 4, 2015

Nothing in #10686 makes the link with `registry.npmjs.org` both giving a 404 and returning non empty response though.

**Comment by legodude17** [comment]
Yes, that is why it is a ref and not a duplicate.

**Comment by gpakosz** [comment]
LOL
