### ISSUE TITLE
 missing script: serve

### ISSUE THREAD

**Issue by gursimran-dev-desk** [npm/npm#16388]
RR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "serve"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10

npm ERR! missing script: serve
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\gursimran\custom-theme\npm-debug.log

**Comment by watilde** [comment]
You're missing the serve command in your `package.json`. See also: https://github.com/npm/npm/issues/15759#issuecomment-279745610.

**Comment by testing-github1** [comment]
.Please help me how to resolve this issue. @watilde

**Comment by KenanY** [comment]
@testing-github1 Hello! So, the way `npm run serve` works is that it looks in your current `package.json` for a defined `"serve"` [script](https://docs.npmjs.com/misc/scripts), and then runs that. The error message you're seeing is trying to tell you that you have not defined a `"serve"` script in your `package.json`, hence `npm run serve` has no idea what you want it to do.

To solve this issue, all you have to do is add a new script to your `package.json`. It might look something like this, for example:

``` json
{
  "name": "package-name",
  "version": "1.0.0",
  "description": "package description",
  "scripts": {
    "serve": "node --version",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {},
  "devDependencies": {}
}
```

Note how this `package.json` has a `"serve"` script that runs `node --version`. This is just an example script I made up to demonstrate; you'll definitely wanna change it to whatever is most appropriate for your specific project.

Let us know if you run into any further `npm` issues :)

**Comment by gursimran-dev-desk** [comment]
I have added the script like this.But the error in coming.   @KenanY 
{
  "private": true,
  "engines": {
    "node": ">=4"
  },
  "devDependencies": {
    "babel-core": "^6.4.0",
    "babel-preset-es2015": "^6.3.13",
    "babel-register": "^6.5.2",
    "browser-sync": "^2.2.1",
    "del": "^2.2.0",
    "gulp": "^3.9.0",
    "gulp-autoprefixer": "^3.0.1",
    "gulp-babel": "^6.1.1",
    "gulp-cache": "^0.4.2",
    "gulp-cssnano": "^2.0.0",
    "gulp-eslint": "^3.0.0",
    "gulp-filter": "^4.0.0",
    "gulp-htmlmin": "^3.0.0",
    "gulp-if": "^2.0.2",
    "gulp-imagemin": "^3.0.1",
    "gulp-load-plugins": "^1.2.4",
    "gulp-plumber": "^1.0.1",
    "gulp-sass": "^2.0.0",
    "gulp-size": "^2.1.0",
    "gulp-sourcemaps": "^2.2.0",
    "gulp-uglify": "^2.0.0",
    "gulp-useref": "^3.0.0",
    "main-bower-files": "^2.5.0",
    "run-sequence": "^1.2.2",
    "wiredep": "^4.0.0"
  },
  "eslintConfig": {
    "env": {
      "es6": true,
      "node": true,
      "browser": true
    },

    {
      "name": "custom-theme",
      "version": "1.0.0",
      "description": "custom-theme-details",
      "scripts": {
        "serve": "node --version",
        "test": "echo \"Error: no test specified\" && exit 1"
      },
      "dependencies": {},
      "devDependencies": {}
    }

   "rules": {
      "quotes": [
        2,
        "single"
      ]
    }
  }
}


and this is the error that is coming.

npm ERR! Windows_NT 10.0.14393                            
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\P
" "serve"                                                 
npm ERR! node v6.10.2                                     
npm ERR! npm  v3.10.10                                    
npm ERR! file C:\Users\gursimran\custom-theme\package.json
npm ERR! code EJSONPARSE                                  
                                                          
npm ERR! Failed to parse json                             
npm ERR! Unexpected token '"' at 52:4                     
npm ERR!    "rules": {                                    
npm ERR!    ^                                             
npm ERR! File: C:\Users\gursimran\custom-theme\package.jso
npm ERR! Failed to parse package.json data.               
npm ERR! package.json must be actual JSON, not just JavaSc
npm ERR!                                                  
npm ERR! This is not a bug in npm.                        
npm ERR! Tell the package author to fix their package.json
                                                          
npm ERR! Please include the following file with any suppor
npm ERR!     C:\Users\gursimran\custom-theme\npm-debug.log

**Comment by KenanY** [comment]
@gursimran-dev-desk Could you try this instead (sorry if the indentation is not what you'd like; the JSON you provided was not indented so I had to guess):

``` json
{
	"private": true,
	"engines": {
		"node": ">=4"
	},
	"devDependencies": {
		"babel-core": "^6.4.0",
		"babel-preset-es2015": "^6.3.13",
		"babel-register": "^6.5.2",
		"browser-sync": "^2.2.1",
		"del": "^2.2.0",
		"gulp": "^3.9.0",
		"gulp-autoprefixer": "^3.0.1",
		"gulp-babel": "^6.1.1",
		"gulp-cache": "^0.4.2",
		"gulp-cssnano": "^2.0.0",
		"gulp-eslint": "^3.0.0",
		"gulp-filter": "^4.0.0",
		"gulp-htmlmin": "^3.0.0",
		"gulp-if": "^2.0.2",
		"gulp-imagemin": "^3.0.1",
		"gulp-load-plugins": "^1.2.4",
		"gulp-plumber": "^1.0.1",
		"gulp-sass": "^2.0.0",
		"gulp-size": "^2.1.0",
		"gulp-sourcemaps": "^2.2.0",
		"gulp-uglify": "^2.0.0",
		"gulp-useref": "^3.0.0",
		"main-bower-files": "^2.5.0",
		"run-sequence": "^1.2.2",
		"wiredep": "^4.0.0"
	},
	"eslintConfig": {
		"env": {
			"es6": true,
			"node": true,
			"browser": true
		},
		"rules": {
			"quotes": [
			2,
			"single"
			]
		}
	},
	"scripts": {
		"serve": "node --version",
		"test": "echo \"Error: no test specified\" && exit 1"
	}
}
```

Note that I added the `"scripts"` object to the root of the JSON, instead of just copying and pasting the entire JSON I provided. This ensures that the file remains valid JSON.

**Comment by gursimran-dev-desk** [comment]
@KenanY .I have copy all of the previous code and paste into package.json file.Now the error is not coming and this is what I am getting

C:\Users\gursimran\custom-theme
λ npm run serve

> @ serve C:\Users\gursimran\custom-theme
> node --version

v6.10.2

**Comment by KenanY** [comment]
@gursimran-dev-desk Yup, looks perfect. Now, as I said above, it's up to _you_ to change the `"serve"` script to do whatever you expect `npm run serve` to do. Right now, you have it printing the current version of Node.js you have installed. From here, I'm just guessing that you will want it to instead spin up a web server, perhaps.

Since this isn't an `npm` issue anymore, I'm gonna close this.

**Comment by gursimran-dev-desk** [comment]
Thanks for help. @KenanY
