### ISSUE TITLE
npm run installdriver   ---------- error missing script: installdriver

### ISSUE THREAD

**Issue by LiQingxin1** [npm/npm#16383]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/7.3.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'installdriver' ]
2 info using npm@3.10.10
3 info using node@v7.3.0
4 verbose stack Error: missing script: installdriver
4 verbose stack     at run (/usr/local/lib/node_modules/npm/lib/run-script.js:151:19)
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/run-script.js:61:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:356:5
4 verbose stack     at handleExists (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:329:20)
4 verbose stack     at FSReqWrap.cb [as oncomplete] (fs.js:239:19)
5 verbose cwd /usr/local/lib/node_modules/uirecorder/sample
6 error Darwin 15.6.0
7 error argv "/usr/local/Cellar/node/7.3.0/bin/node" "/usr/local/bin/npm" "run" "installdriver"
8 error node v7.3.0
9 error npm  v3.10.10
10 error missing script: installdriver
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@LiQingxin1 Hello! So, the way `npm run installdriver` works is that it looks in your current `package.json` for a defined `"installdriver"` [script](https://docs.npmjs.com/misc/scripts), and then runs that. The error message you're seeing is trying to tell you that you have not defined a `"installdriver"` script in your `package.json`, hence `npm run installdriver` has no idea what you want it to do.

To solve this issue, all you have to do is add a new script to your `package.json`. It might look something like this, for example:

``` json
{
  "name": "package-name",
  "version": "1.0.0",
  "description": "package description",
  "scripts": {
    "installdriver": "node --version",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {},
  "devDependencies": {}
}
```

Note how this `package.json` has a `"installdriver"` script that runs `node --version`. You'll definitely want to change the command to whatever is most appropriate for your project.

Let me know if you run into any further `npm` issues :)

**Comment by KenanY** [comment]
Closing due to no reply after a month.
