### ISSUE TITLE
Possible EventEmitter memory leak detected. npm v3.10.10 on npm install (all packages, including npm@latest)

### ISSUE THREAD

**Issue by 999chris** [npm/npm#16385]
#### I'm opening this issue because:

  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.

#### What's going wrong?

I'm receiving the error(s):

(node:53038) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:53038) Warning: Possible EventEmitter memory leak detected. 11 pipe listeners added. Use emitter.setMaxListeners() to increase limit

I've looked around and the only suggestion is to update npm. Even running `npm install npm@next ` has this issue. Besides I am a later version that suggested anyway (3.10.8).

#### How can the CLI team reproduce the problem?

I'm not sure if the problem can necessarliy be re-produced. I'm only trying to run `npm install express`, though it is through a proxy. I need my hand held to get better information to be honest.

### supporting information:

 - `npm -v` prints: v6.10.0
 - `node -v` prints: v3.10.10
 - `npm config get registry` prints: http://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux
   - [ ] I use a proxy to connect to the npm registry.

**Comment by legodude17** [comment]
Try upgrading to `npm@latest`.

**Comment by 999chris** [comment]
> Even running npm install npm@next has this issue. Besides I am a later version that suggested anyway (3.10.8).

latest is the same.

**Comment by legodude17** [comment]
@999chris `npm@latest` should be something around `npm@4.4.0`...

**Comment by 999chris** [comment]
But as ive just said. "latest" gives the same error.

This was apparently fixed in 3.10.8



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by legodude17** [comment]
Can I see you log when running `npm@latest`?

**Comment by 999chris** [comment]
` npm install npm@latest
(node:56500) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:56500) Warning: Possible EventEmitter memory leak detected. 11 pipe listeners added. Use emitter.setMaxListeners() to increase limit
(node:56500) Warning: Possible EventEmitter memory leak detected. 11 pipe listeners added. Use emitter.setMaxListeners() to increase limit
(node:56500) Warning: Possible EventEmitter memory leak detected. 11 pipe listeners added. Use emitter.setMaxListeners() to increase limit
npm ERR! Linux 2.6.32-573.18.1.el6.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "npm@latest"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10

npm ERR! Exceeded maxRedirects. Probably stuck in a redirect loop http://registry.npmjs.org/npm
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     #############################
[npm-debug.txt](https://github.com/npm/npm/files/972967/npm-debug.txt)
/npm-debug.log
`
Sorry for the delay, please find attached. Is the proxy not behaving?

**Comment by 999chris** [comment]
Okay... My proxy was broken. Apolgies for this for some reaosn it was pointing at rubygems.org
