### ISSUE TITLE
Discord bot problem

### ISSUE THREAD

**Issue by HUNes** [npm/npm#16393]
#### I'm opening this issue because:

  - [x] npm is doing something I don't understand.

Im coding a discord bot and for someone reason its coming with these errors

Is this ok? (yes) yes

C:\Myapp>npm start
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0
npm ERR! file C:\Myapp\package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected token '�' at 12:1
npm ERR! �start�: �node index.js�
npm ERR! ^
npm ERR! File: C:\Myapp\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Alexa\AppData\Roaming\npm-cache\_logs\2017-04-19T22_36_42_467Z-debug.log

And i dont really dont understand it and im kinda new to Coding and such..

![image](https://cloud.githubusercontent.com/assets/27789238/25205371/3824c5d6-2530-11e7-8be3-712a4e20605c.png)

**Comment by KenanY** [comment]
@HUNes In your `package.json`, at line 12, all the double quotes on that line seem to be "fancy quotes", instead of the plain `"`. Try replacing those double quotes with the plain `"` double quote.

**Comment by HUNes** [comment]
now im getting Unexpected token errors what exactly is that?
npm ERR! Failed to parse json
npm ERR! Unexpected token '}' at 13:3
npm ERR!   },

**Comment by KenanY** [comment]
@HUNes Could you upload what your `package.json` looks like now to <https://gist.github.com/> and post a link to it here? (It's easier for me to read if it's on gist.github.com instead of as a screenshot.)

**Comment by KenanY** [comment]
Closing due to no reply after a month.
