### ISSUE TITLE
npm install -g firebase-tools 

### ISSUE THREAD

**Issue by Veetshepo** [npm/npm#16392]
Hi all 

I am getting an error installing firebase on my macbook 

Below is the error message i am getting 

npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "firebase-tools"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! path ../lib/node_modules/firebase-tools/bin/firebase
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall symlink

npm ERR! Error: EACCES: permission denied, symlink '../lib/node_modules/firebase-tools/bin/firebase' -> '/usr/local/bin/firebase'
npm ERR!     at Error (native)
npm ERR!  { Error: EACCES: permission denied, symlink '../lib/node_modules/firebase-tools/bin/firebase' -> '/usr/local/bin/firebase'
npm ERR!     at Error (native)
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'symlink',
npm ERR!   path: '../lib/node_modules/firebase-tools/bin/firebase',
npm ERR!   dest: '/usr/local/bin/firebase' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/nelsonmathebula/npm-debug.log
npm ERR! code 1

**Comment by angelxmoreno** [comment]
Isn't this a sudo issue ? what is the exact command you are using?

**Comment by Veetshepo** [comment]
The command is 

$ npm install -g firebase-tools

**Comment by Veetshepo** [comment]
Hi angelxmoreno 

It was a Sudo error thanks man
