### ISSUE TITLE
npm install from GitHub fails to symlink binaries in ./node_modules/.bin

### ISSUE THREAD

**Issue by ianstormtaylor** [npm/npm#16395]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I'm trying to install a GitHub module `b` from in module `a`, where `b` has a dependency with a binary—in this case `babel-cli`. Which looks like:

```
a -> 
    b -> 
        babel-cli
```

And module `b` has a `postinstall` script which calls `make build` and uses the `./node_modules/.bin/babel` CLI. But this fails with:

```
> b@0.0.0 postinstall ...
> make build

make: ./node_modules/.bin/babel: No such file or directory
make: *** [build] Error 1
```

If I run install with `--ignore-scripts`, I can see that there is no `./node_modules/b/node_modules/.bin` directory or symlinks created at all.

#### Supporting information:

```
$ npm -v
3.10.10

$ node -v
v6.9.5

$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.1
```

**Comment by legodude17** [comment]
I am pretty sure that `npm` just doesn't link binaries in your dependencies.

**Comment by ianstormtaylor** [comment]
Hey @legodude17 thanks for the reply!

If that's the case, how can packages use `postinstall` (which is useful for private dependencies that don't want to commit their built files) with anything other than pure npm scripts? It seems like using Makefiles is a pretty common practice. I looked into using `npm bin` as a way to get the "proper" current binary path instead, but it seems like this incorrectly prints the non-existent path instead.

It seems like Yarn handles this case automatically.

**Comment by redbugz** [comment]
I just encountered a similar problem. I have a dependency on another project that uses bower. They have bower in their dependencies and a postinstall task that calls `"bower install --config.interactive=false"`, and when I run npm install on my project, it fails because it can't find bower during their postinstall. My project also uses bower and a postinstall and it works fine.

project names simplified in this output to `myproject` and `mydep`
```
352257 verbose write writing to /Users/me/projects/myproject/node_modules/bower/package.json
352258 info preinstall bower@1.8.0
352259 verbose readDependencies loading dependencies from /Users/me/projects/myproject/node_modules/bower/package.json
352260 verbose readDependencies loading dependencies from /Users/me/projects/myproject/node_modules/bower/package.json
352261 silly install resolved []
352262 verbose about to build /Users/me/projects/myproject/node_modules/bower
352263 info build /Users/me/projects/myproject/node_modules/bower
352264 info linkStuff bower@1.8.0
352265 silly linkStuff bower@1.8.0 has /Users/me/projects/myproject/node_modules as its parent node_modules
352266 verbose linkBins bower@1.8.0
352267 verbose link bins [ { bower: 'bin/bower' },
352267 verbose link bins   '/Users/me/projects/myproject/node_modules/.bin',
352267 verbose link bins   false ]
352268 verbose linkMans bower@1.8.0
352269 verbose rebuildBundles bower@1.8.0
352270 silly gentlyRm /Users/me/projects/myproject/node_modules/.bin/bower is being purged
352271 verbose gentlyRm don't care about contents; nuking /Users/me/projects/myproject/node_modules/.bin/bower
352272 info install bower@1.8.0
352273 info postinstall bower@1.8.0
352274 verbose unlock done using /Users/me/.npm/_locks/bower-1c5e43a206b0b39d.lock for /Users/me/projects/myproject/node_modules/bower
352275 verbose stack Error: mydep@2.4.6 postinstall: `bower install --config.interactive=false`
352275 verbose stack spawn ENOENT
352275 verbose stack     at ChildProcess.<anonymous> (/Users/me/.nvm/versions/node/v4.8.3/lib/node_modules/npm/lib/utils/spawn.js:17:16)
352275 verbose stack     at emitTwo (events.js:87:13)
352275 verbose stack     at ChildProcess.emit (events.js:172:7)
352275 verbose stack     at maybeClose (internal/child_process.js:862:16)
352275 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:222:5)
352276 verbose pkgid mydep@2.4.6
352277 verbose cwd /Users/me/projects/myproject
352278 error Darwin 16.5.0
352279 error argv "/Users/me/.nvm/versions/node/v4.8.3/bin/node" "/Users/me/.nvm/versions/node/v4.8.3/bin/npm" "install"
352280 error node v4.8.3
352281 error npm  v2.15.11
352282 error file sh
352283 error code ELIFECYCLE
352284 error errno ENOENT
352285 error syscall spawn
352286 error mydep@2.4.6 postinstall: `bower install --config.interactive=false`
352286 error spawn ENOENT
352287 error Failed at the mydep@2.4.6 postinstall script 'bower install --config.interactive=false'.
352287 error This is most likely a problem with the mydep package,
352287 error not with npm itself.
352287 error Tell the author that this fails on your system:
352287 error     bower install --config.interactive=false
352287 error You can get information on how to open an issue for this project with:
352287 error     npm bugs mydep
352287 error Or if that isn't available, you can get their info via:
352287 error
352287 error     npm owner ls mydep
```

**Comment by ianstormtaylor** [comment]
@redbugz FWIW, I switched to Yarn and it handles this case fine.

**Comment by redbugz** [comment]
I've been testing it in various versions, and every version of Node 4/npm 2 I've tried fails (4.7.3, 4.8.0, 4.8.3), and every version of Node 6/npm 3 I've tried so far works fine (6.9.5, 6.10.0, 6.10.3).
