### ISSUE TITLE
node connect.js failing

### ISSUE THREAD

**Issue by vijaythuthuku** [npm/npm#16390]
[oracle@apmapp node-oracledb-master]$ npm install -g

> oracledb@1.13.1 install /home/oracle/node/node-v6.10.2-linux-x64/lib/node_modules/oracledb
> node-gyp rebuild

make: Entering directory `/home/oracle/node/node-v6.10.2-linux-x64/lib/node_modules/oracledb/build'
  CXX(target) Release/obj.target/oracledb/src/njs/src/njsOracle.o
  CXX(target) Release/obj.target/oracledb/src/njs/src/njsPool.o
  CXX(target) Release/obj.target/oracledb/src/njs/src/njsConnection.o
  CXX(target) Release/obj.target/oracledb/src/njs/src/njsResultSet.o
  CXX(target) Release/obj.target/oracledb/src/njs/src/njsMessages.o
  CXX(target) Release/obj.target/oracledb/src/njs/src/njsIntLob.o
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiEnv.o
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiEnvImpl.o
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiException.o
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiExceptionImpl.o
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiConnImpl.o
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiDateTimeArrayImpl.o
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiPoolImpl.o
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiStmtImpl.o
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiUtils.o
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiLob.o
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiCommon.o
  SOLINK_MODULE(target) Release/obj.target/oracledb.node
  COPY Release/oracledb.node
make: Leaving directory `/home/oracle/node/node-v6.10.2-linux-x64/lib/node_modules/oracledb/build'
/home/oracle/node/node-v6.10.2-linux-x64/lib
âââ¬ oracledb@1.13.1
  âââ nan@2.5.1

[oracle@apmapp node-oracledb-master]$ cd examples
[oracle@apmapp examples]$ ls
blobhttp.js           dbmsoutputpipe.js  fetchinfo.js       lobinsert2.js     metadata.js    refcursor.js               select1.js         webapp.js
clobexample.txt       demodrop.sql       fuzzydinosaur.jpg  lobinserttemp.js  plsqlarray.js  refcursortoquerystream.js  select2.js         webapppromises.js
connect.js            demo.sql           insert1.js         lobplsqltemp.js   plsqlfunc.js   resultset1.js              selectjsonclob.js
date.js               dmlrupd1.js        insert2.js         lobselect.js      plsqlproc.js   resultset2.js              selectjson.js
dbconfig.js           dmlrupd2.js        lobbinds.js        lobstream1.js     promises.js    resultsettoquerystream.js  selectstream.js
dbmsoutputgetline.js  endtoend.js        lobinsert1.js      lobstream2.js     raw1.js        rowlimit.js                version.js
[oracle@apmapp examples]$ node connect.js
module.js:471
    throw err;
    ^

Error: Cannot find module 'oracledb'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/oracle/node-oracledb/node-oracledb-master/examples/connect.js:27:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
[oracle@apmapp examples]$ vi dbconfig.js
[oracle@apmapp examples]$ cp dbconfig.js dbconfig.js_bkp19417
[oracle@apmapp examples]$ vi dbconfig.js
[oracle@apmapp examples]$ vi dbconfig.js
[oracle@apmapp examples]$ node connect.js
module.js:471
    throw err;
    ^

Error: Cannot find module 'oracledb'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/oracle/node-oracledb/node-oracledb-master/examples/connect.js:27:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

[oracle@apmapp examples]$ ls
blobhttp.js           dbmsoutputgetline.js  endtoend.js        lobinsert1.js     lobstream2.js  raw1.js                    rowlimit.js        version.js
clobexample.txt       dbmsoutputpipe.js     fetchinfo.js       lobinsert2.js     metadata.js    refcursor.js               select1.js         webapp.js
connect.js            demodrop.sql          fuzzydinosaur.jpg  lobinserttemp.js  plsqlarray.js  refcursortoquerystream.js  select2.js         webapppromises.js
date.js               demo.sql              insert1.js         lobplsqltemp.js   plsqlfunc.js   resultset1.js              selectjsonclob.js
dbconfig.js           dmlrupd1.js           insert2.js         lobselect.js      plsqlproc.js   resultset2.js              selectjson.js
dbconfig.js_bkp19417  dmlrupd2.js           lobbinds.js        lobstream1.js     promises.js    resultsettoquerystream.js  selectstream.js
[oracle@apmapp examples]$ node webapp.js
module.js:471
    throw err;
    ^

Error: Cannot find module 'oracledb'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/oracle/node-oracledb/node-oracledb-master/examples/webapp.js:36:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by KenanY** [comment]
Could you try running `npm install oracledb` from within the `examples/` directory?

**Comment by vijaythuthuku** [comment]
I am getting this error
[oracle@apmapp examples]$ node connect.js
ORA-12514: TNS:listener does not currently know of service requested in connect descriptor

[oracle@apmapp examples]$

**Comment by vijaythuthuku** [comment]
module.exports = {
  user          : process.env.NODE_ORACLEDB_USER || "hr",

  // Instead of hard coding the password, consider prompting for it,
  // passing it in an environment variable via process.env, or using
  // External Authentication.
  password      : process.env.NODE_ORACLEDB_PASSWORD || "oracle",

  // For information on connection strings see:
  // https://github.com/oracle/node-oracledb/blob/master/doc/api.md#connectionstrings
  connectString : process.env.NODE_ORACLEDB_CONNECTIONSTRING || "localhost/orcl",

**Comment by vijaythuthuku** [comment]
[oracle@apmapp examples]$ npm install oracledb
npm ERR! Linux 4.1.12-61.1.27.el7uek.x86_64
npm ERR! argv "/home/oracle/node/node-v6.10.2-linux-x64/bin/node" "/home/oracle/node/node-v6.10.2-linux-x64/bin/npm" "install" "oracledb"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ENOSELF

npm ERR! Refusing to install oracledb as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/oracle/node-oracledb/node-oracledb-master/examples/npm-debug.log
[oracle@apmapp examples]$ node connect.js
ORA-12514: TNS:listener does not currently know of service requested in connect descriptor

[oracle@apmapp examples]$

**Comment by vijaythuthuku** [comment]
I am doing this first time. Could you help pls

**Comment by legodude17** [comment]
Make sure that the `package.json`'s `name` key is not set to `oracledb`.

**Comment by vijaythuthuku** [comment]
Could you tell how to check and fix that?

**Comment by vijaythuthuku** [comment]
[oracle@apmapp examples]$ node endtoend.js
ORA-12514: TNS:listener does not currently know of service requested in connect descriptor

[oracle@apmapp examples]$ node plsqlproc.js
ORA-12514: TNS:listener does not currently know of service requested in connect descriptor

[oracle@apmapp examples]$ vi dbconfig.js
[oracle@apmapp examples]$ node metadata.js
module.js:471
    throw err;
    ^

Error: Cannot find module 'async'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/oracle/node-oracledb/node-oracledb-master/examples/metadata.js:30:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
[oracle@apmapp examples]$ node connect.js
ORA-12514: TNS:listener does not currently know of service requested in connect descriptor

[oracle@apmapp examples]$

**Comment by legodude17** [comment]
Try running `npm install --save async`.

**Comment by KenanY** [comment]
The 

```
ORA-12514: TNS:listener does not currently know of service requested in connect descriptor
```

errors are **not** coming from `npm`. The `oracledb` developers probably can help you there.

**Comment by KenanY** [comment]
Closing due to no reply after a month.
