### ISSUE TITLE
Installing uws 0.12.0 fails

### ISSUE THREAD

**Issue by Luminaire191** [npm/npm#16402]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
alex@sanfran:~$ sudo npm install -g uws@^0.12.0
npm ERR! Linux 4.10.0-19-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "uws@^0.12.0"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0

npm ERR! Cannot read property 'path' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/alex/.npm/_logs/2017-04-21T00_04_52_714Z-debug.log

No idea why this isn't working O.o Sorry if it's obvious I'm pretty new to this. Also sidenote, uws 0.14.1 works fine but I need 0.12.0 for a dependency. Thanks!

#### How can the CLI team reproduce the problem?
run:    sudo npm install -g uws@^0.12.0

### supporting information:

 - `npm -v` prints: 4.2.0
 - `node -v` prints: v7.9.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Ubuntu 17.04
[2017-04-21T00_04_52_714Z-debug.log.txt](https://github.com/npm/npm/files/945776/2017-04-21T00_04_52_714Z-debug.log.txt)

**Comment by KenanY** [comment]
Version 0.12.0 has been unpublished from the registry. hence it is not possible to download it from the registry.
