### ISSUE TITLE
error in npm start

### ISSUE THREAD

**Issue by zihebingwu** [npm/npm#16407]
19 error node v4.4.3
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error react-babel-webpack-boilerplate@1.4.1 start: `webpack-dev-server --devtool eval --progress --hot --content-base app`
22 error Exit status 1
23 error Failed at the react-babel-webpack-boilerplate@1.4.1 start script 'webpack-dev-server --devtool eval --progress --hot --content-base app'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the react-babel-webpack-boilerplate package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack-dev-server --devtool eval --progress --hot --content-base app
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs react-babel-webpack-boilerplate
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls react-babel-webpack-boilerplate
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

-->

**Comment by KenanY** [comment]
Log indicates that your `"start"` script is returning an error code. This isn't an issue in `npm` itself; all `npm` is doing here is catching the error for your and letting you know about it. I would make sure that your `"start"` script runs fine outside of `npm` (as in: try running it from your command-line without doing `npm start`).

**Comment by KenanY** [comment]
Closing due to no reply after a month.
