### ISSUE TITLE
Failed to install on CentOs

### ISSUE THREAD

**Issue by worthynews** [npm/npm#16401]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [* ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints: 1.1.0=beta-10
 - `node -v` prints: v0.6.7
 - `npm config get registry` prints:
npm ERR! Usage:
npm ERR! npm config set <key> <value>
npm ERR! npm config get <key>
npm ERR! npm config delete <key>
npm ERR! npm config list
npm ER! npm config edit
npm not ok

 - Windows, OS X/macOS, or Linux?: CENTOS 6.9 x86_64

Installation instructions from 
https://github.com/foreverjs/forever/wiki/Detailed-installation

cd /usr/src
git clone http://github.com/joyent/node.git
cd node
git checkout v0.6.7
./configure
make && make install
cd /root
npm install forever -g  [failed at this point]

![forever-install-failure](https://cloud.githubusercontent.com/assets/19967295/25255812/d5daf9d8-25fa-11e7-9f9f-5f7358e3ce21.jpg)

**Comment by KenanY** [comment]
Nodejs v0.6 and `npm@1.1` are many years old and are no longer supported. If this is still an issue with newer versions of `npm`, then we can reopen this.

**Comment by worthynews** [comment]
https://github.com/foreverjs/forever/wiki/Detailed-installation

Can you tell me how to get the newer versons?  I just followed the instructions above.

**Comment by KenanY** [comment]
Probably <https://nodejs.org/en/download/package-manager/#enterprise-linux-and-fedora>
