### ISSUE TITLE
express+ejs如何引用 js和css，路径正确，都报404错误

### ISSUE THREAD

**Issue by yangshuibo** [npm/npm#16404]
aaaa:9 GET http://localhost:3001/client/style.css 
aaaa:56 GET http://localhost:3001/client/client.js 
aaaa:15 GET http://localhost:3001/public/images/%E4%B8%8B%E8%BD%BD.jpg 404 (Not Found)
%E4%B8%8B%E8%BD%BD.jpg:1 GET http://localhost:3001/public/images/%E4%B8%8B%E8%BD%BD.jpg 404 (Not Found)
aaaa:56 GET http://localhost:3001/client/client.js 

还是说不能使用h5的引入方式？
求大神指教
我使用html5的方式引入的

**Comment by legodude17** [comment]
What makes you think this is an issue with `npm`?
