### ISSUE TITLE
npm should NOT init/update submodules when installing from git url

### ISSUE THREAD

**Issue by daniel-constantin** [npm/npm#16408]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

When installing a npm module from a git url, if it's submodules are broken (cannot be cloned) the install fails as well, even though the submodules are in `.npmignore` and should not be cloned to begin with.

#### How can the CLI team reproduce the problem?

1. Create git repository A with a submodule B.
2. Add submodule B in the `.npmignore` file of A.
3. Delete the repository of module B.
4. You cannot install A anymore, even though you don't need B (which is in `.npmignore`).

When you guys added support for #1876 , you did not foresee a scenario where the submodule is a dev dependency for example.
I'm not familiar with the process npm uses to install from git. I assume it first clones the whole repository with `-recursive` and then deletes what's in `.npmignore`.
What it should do is, clone the repository without `-recursive`, remove the files ignored by `.npmignore`, and only then use `git submodule init --update` or whatever.

### supporting information:

 - `npm -v` prints: 3.10.10
 - `node -v` prints: v6.9.4

**Comment by kije** [comment]
+1
