### ISSUE TITLE
npm error

### ISSUE THREAD

**Issue by sundadong** [npm/npm#16411]
npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "update"
npm ERR! node v4.4.4
npm ERR! npm  v4.1.2

npm ERR! Unexpected token ILLEGAL
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/sundadong/npm-debug.log

**Comment by KenanY** [comment]
Not enough context to diagnose this issue. Could you please upload the debug log to <https://gist.github.com/> and post a link to it here?

**Comment by sundadong** [comment]
@KenanY 
npm-debug.log 
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'n' ]
2 info using npm@4.1.2
3 info using node@v4.4.4
4 verbose stack SyntaxError: Unexpected token ILLEGAL
4 verbose stack     at exports.runInThisContext (vm.js:53:16)
4 verbose stack     at Module._compile (module.js:373:25)
4 verbose stack     at Object.Module._extensions..js (module.js:416:10)
4 verbose stack     at Module.load (module.js:343:32)
4 verbose stack     at Function.Module._load (module.js:300:12)
4 verbose stack     at Module.require (module.js:353:17)
4 verbose stack     at require (internal/module.js:12:17)
4 verbose stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:10:12)
4 verbose stack     at Module._compile (module.js:409:26)
4 verbose stack     at Object.Module._extensions..js (module.js:416:10)
5 verbose cwd /
6 error Darwin 16.5.0
7 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "n"
8 error node v4.4.4
9 error npm  v4.1.2
10 error Unexpected token ILLEGAL
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@sundadong Is that the full debug log file?

**Comment by KenanY** [comment]
Closing due to no reply after a month.
