### ISSUE TITLE
Not able to install angular

### ISSUE THREAD

**Issue by rajibganguly** [npm/npm#16417]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong? This is the log
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\lenovo\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'angular',
1 verbose cli   '--save-dev' ]
2 info using npm@3.10.6
3 info using node@v7.0.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData angular
8 silly fetchNamedPackageData angular
9 silly mapToRegistry name angular
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'angular',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'angular',
12 silly mapToRegistry   name: 'angular',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/angular
14 verbose request uri https://registry.npmjs.org/angular
15 verbose request no auth needed
16 info attempt registry request try #1 at 7:25:27 PM
17 verbose request id 0859688894650485
18 verbose etag W/"58f235c3-24b20"
19 verbose lastModified Sat, 15 Apr 2017 15:01:23 GMT
20 http request GET https://registry.npmjs.org/angular
21 http 304 https://registry.npmjs.org/angular
22 verbose headers { date: 'Sat, 22 Apr 2017 13:47:56 GMT',
22 verbose headers   via: '1.1 varnish',
22 verbose headers   'cache-control': 'max-age=300',
22 verbose headers   etag: 'W/"58f235c3-24b20"',
22 verbose headers   age: '120',
22 verbose headers   connection: 'keep-alive',
22 verbose headers   'x-served-by': 'cache-ams4445-AMS',
22 verbose headers   'x-cache': 'HIT',
22 verbose headers   'x-cache-hits': '1',
22 verbose headers   'x-timer': 'S1492868877.642133,VS0,VE0',
22 verbose headers   vary: 'Accept-Encoding' }
23 silly get cb [ 304,
23 silly get   { date: 'Sat, 22 Apr 2017 13:47:56 GMT',
23 silly get     via: '1.1 varnish',
23 silly get     'cache-control': 'max-age=300',
23 silly get     etag: 'W/"58f235c3-24b20"',
23 silly get     age: '120',
23 silly get     connection: 'keep-alive',
23 silly get     'x-served-by': 'cache-ams4445-AMS',
23 silly get     'x-cache': 'HIT',
23 silly get     'x-cache-hits': '1',
23 silly get     'x-timer': 'S1492868877.642133,VS0,VE0',
23 silly get     vary: 'Accept-Encoding' } ]
24 verbose etag https://registry.npmjs.org/angular from cache
25 verbose get saving angular to C:\Users\lenovo\AppData\Roaming\npm-cache\registry.npmjs.org\angular\.cache.json
26 verbose correctMkdir C:\Users\lenovo\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
27 silly install normalizeTree
28 silly loadCurrentTree Finishing
29 silly loadIdealTree Starting
30 silly install loadIdealTree
31 silly cloneCurrentTree Starting
32 silly install cloneCurrentTreeToIdealTree
33 silly cloneCurrentTree Finishing
34 silly loadShrinkwrap Starting
35 silly install loadShrinkwrap
36 silly loadShrinkwrap Finishing
37 silly loadAllDepsIntoIdealTree Starting
38 silly install loadAllDepsIntoIdealTree
39 silly rollbackFailedOptional Starting
40 silly rollbackFailedOptional Finishing
41 silly runTopLevelLifecycles Starting
42 silly runTopLevelLifecycles Finishing
43 silly install printInstalled
44 verbose stack Error: Refusing to install angular as a dependency of itself
44 verbose stack     at checkSelf (C:\Users\lenovo\AppData\Roaming\npm\node_modules\npm\lib\install\validate-args.js:53:14)
44 verbose stack     at Array.<anonymous> (C:\Users\lenovo\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
44 verbose stack     at LOOP (C:\Users\lenovo\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
44 verbose stack     at chain (C:\Users\lenovo\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
44 verbose stack     at C:\Users\lenovo\AppData\Roaming\npm\node_modules\npm\lib\install\validate-args.js:16:5
44 verbose stack     at C:\Users\lenovo\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
44 verbose stack     at Array.forEach (native)
44 verbose stack     at C:\Users\lenovo\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
44 verbose stack     at Array.forEach (native)
44 verbose stack     at asyncMap (C:\Users\lenovo\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
45 verbose cwd D:\test\project\capgemini-project\angular
46 error Windows_NT 10.0.14393
47 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\lenovo\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "angular" "--save-dev"
48 error node v7.0.0
49 error npm  v3.10.6
50 error code ENOSELF
51 error Refusing to install angular as a dependency of itself
52 error If you need help, you may report this error at:
52 error     <https://github.com/npm/npm/issues>
53 verbose exit [ 1, true ]

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by rajibganguly** [comment]
npm is doing something I don't understand.

**Comment by KenanY** [comment]
Make sure the `"name"` field in your `package.json` is not set to `"angular"`.

**Comment by KenanY** [comment]
Closing due to no reply after a month.
