### ISSUE TITLE
NPM install issues

### ISSUE THREAD

**Issue by zacorbett** [npm/npm#16412]
#### I'm opening this issue because:

  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
 
  - I haven't been able to find documentation about this issue exactly and a way to fix it....but I wouldn't be surprised if the solution is out there and I just haven't found it yet...

#### What's going wrong?

   - I am getting this warning 
" UNMET PEER DEPENDENCY webpack@^1.9 || ^2.2.0 || ^2.1.0-beta || ^2.2.0-rc "

   - And then this Error printout

npm ERR! Linux 4.4.0-51-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! path ../acorn/bin/acorn
npm ERR! code EPROTO
npm ERR! errno -71
npm ERR! syscall symlink

npm ERR! EPROTO: protocol error, symlink '../acorn/bin/acorn' -> '/home/vagrant/Code/platform-crm/node_modules/.bin/acorn'

#### How can the CLI team reproduce the problem?
    - This is on a vagrant box, Homestead/laravel build on Windows 10
    - This is within a the local repo
    - I run the command "npm install"
    - I have tried the command again after deleting node_modules and still the same error

-npm.debug.log
https://gist.github.com/zacorbett/874bf2fbd9b73660d3054b155bdfb5dd

### supporting information:

 - `npm -v` prints: 3.10.10
 - `node -v` prints: v6.10.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows

 - Container:
   - [ ] I develop using Vagrant on Windows.

Additional Comments: I am at a lost, and have looked for a solution...any direction and pointers would be greatly appreciated. Thank you!

**Comment by KenanY** [comment]
Have you tried using the [`--no-bin-links`](https://docs.npmjs.com/misc/config#bin-links) flag?

**Comment by zacorbett** [comment]
Hmm, that does seem to have helped...but then I run `npm run dev` and I get this:

> @ dev /home/vagrant/Code/platform-crm
> npm run development


> @ development /home/vagrant/Code/platform-crm
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

sh: 1: cross-env: not found

npm ERR! Linux 4.4.0-51-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "development"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the @ development script 'cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/Code/platform-crm/npm-debug.log

npm ERR! Linux 4.4.0-51-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "dev"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ dev script 'npm run development'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run development
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/Code/platform-crm/npm-debug.log

Link to new npm-debug.log : https://gist.github.com/zacorbett/d7213d6e8062aa6e0cf25180a3823c82

**Comment by legodude17** [comment]
Do you have `sh` installed in your path?

**Comment by zacorbett** [comment]
Hmm, says `sh` is not found...how do I go about fixing that?

**Comment by legodude17** [comment]
Is `sh` on your `$PATH`?

**Comment by KenanY** [comment]
It's not saying the `sh` was not found; it's saying that `cross-env` was not found. This is because by disabling `bin-links`, symlinks to package executables (like `cross-env`'s) will not be created.

**Comment by zacorbett** [comment]
Ah I see. so I need to enable `bin-links`?

**Comment by KenanY** [comment]
Well, I don't think you can since your system does not support symlinks.

**Comment by zacorbett** [comment]
Issue solved.

Solution: -Update Node via NVM to v7.9.0 
               -Then update paths of scripts in package.json

My issues have been resolved. Thank you for your time and input!
