### ISSUE TITLE
npm install shows errors !

### ISSUE THREAD

**Issue by Boualem93** [npm/npm#16428]
#### I'm opening this issue because:

  - [x] npm is crashing.
#### What's going wrong?

After I cloned a project from git, I wanted to run the project and to do so I had to install needed dependencies using npm install. However it shows errors as mentionned bellow : 

![sans titre](https://cloud.githubusercontent.com/assets/15094602/25338772/b189e856-2900-11e7-9f6a-8a622254ca98.png)

### supporting information:

 - `npm -v` prints: 4.5.0
 - `node -v` prints: 7.9.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows
 - Network issues:
   - Geographic location where npm was run:
 I'm behind a corporate proxy but I think that I reserved the issue of the proxy.

Thank you for helping.

**Comment by legodude17** [comment]
Do you have a stable internet connection?

**Comment by Boualem93** [comment]
I'm pretty sure it is stable.

**Comment by legodude17** [comment]
Could you upload the full npm-debug.log to https://gist.github.com/ and post the link here?

**Comment by Boualem93** [comment]
Of course.

[link](https://gist.github.com/Boualem93/7d01aaf791b237db3fcdfe6baf8f29f1).

**Comment by legodude17** [comment]
Does `git clone git@github.com:douglasduteil/karma-coverage.git` work?

**Comment by Boualem93** [comment]
Hello,
Unfortunately it does not, it shows me this error:

ssh: connect to host github.com port 22: Connection timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by legodude17** [comment]
Then this is a problem with your internet connection or proxy.
