### ISSUE TITLE
Double Update Message

### ISSUE THREAD

**Issue by NonCreature0714** [npm/npm#16425]
#### I'm opening this issue because:

  - [x] Other (_see below for feature requests_):

#### What's going wrong?
Much like a double rainbow, npm displays "Update Available" a second time, even after updating. I [ copied the output into a gist](https://gist.github.com/NonCreature0714/a4d6494b7a5f20d2d9274ce9ff647c26) for you to review. And I've attached a screenshot. ![screen shot 2017-04-23 at 3 53 33 pm](https://cloud.githubusercontent.com/assets/13374460/25317464/c3d91e04-283e-11e7-9a6a-790b996737c4.png)
.
It only seems to prompt one extra time - so only twice, even after reporting it's bumped to 4.5.0

#### How can the CLI team reproduce the problem?
`npm install npm@lastest -g` should replicate this behavior. 

### supporting information:

 - `npm -v` prints: 4.5.0
 - `node -v` prints: v6.9.5
 - `npm config get registry` prints: https://registry.npmjs.org/

 - macOS

**Comment by watilde** [comment]
What `npm -v` actually say? The npm command could be placed in the different directory with npm@4.5.0 you installed.

**Comment by NonCreature0714** [comment]
@watilde `npm -v` actually says: 4.5.0
![screen shot 2017-04-25 at 11 43 16 am](https://cloud.githubusercontent.com/assets/13374460/25397008/622c6caa-29ac-11e7-97be-b1ba01c10986.png)

**Comment by NonCreature0714** [comment]
@watilde and `which npm` shows: `/usr/local/bin/npm`
![screen shot 2017-04-25 at 11 44 13 am](https://cloud.githubusercontent.com/assets/13374460/25397075/9b8c1734-29ac-11e7-9b14-0444eca01e9a.png)
