### ISSUE TITLE
Errors when installing gulp

### ISSUE THREAD

**Issue by jmeisenthal** [npm/npm#16423]
I have been unable to install gulp. (log output at end). It fails even if;
-- In Windows or LINUX
-- run npm cache clean first
-- install locally or globally
-- rm the node_modules dir first
-- install with the --no-bin-links flag

I am not having trouble installing any other modules.

Thanks

#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [X ] npm is producing an incorrect install.
  - [ X] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints: 1.4.14
 - `node -v` prints: v0.10.29
 - `npm config get registry` prints: (proxy)
 - Windows, OS X/macOS, or Linux?: Windows
 - Network issues:
   - Geographic location where npm was run:
   - [ X] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! Error: ENOENT, lstat 'C:\Users\root\AppData\Roaming\npm\node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-watcher\node_modules\gaze\README.md'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "c:\\gitviews\\mockup\\Tools\\nodejs\\\\node.exe" "c:\\gitviews\\mockup\\Tools\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "gulp"
npm ERR! cwd C:\gitviews\mockup
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! path C:\Users\root\AppData\Roaming\npm\node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-watcher\node_modules\gaze\README.md
npm ERR! fstream_path C:\Users\root\AppData\Roaming\npm\node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-watcher\node_modules\gaze\README.md
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack c:\gitviews\mockup\Tools\nodejs\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat 'C:\Users\root\AppData\Roaming\npm\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "c:\\gitviews\\mockup\\Tools\\nodejs\\\\node.exe" "c:\\gitviews\\mockup\\Tools\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "gulp"
npm ERR! cwd C:\gitviews\mockup
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! path C:\Users\root\AppData\Roaming\npm\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js
npm ERR! fstream_path C:\Users\root\AppData\Roaming\npm\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack c:\gitviews\mockup\Tools\nodejs\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, chmod 'C:\Users\root\AppData\Roaming\npm\node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-stream\node_modules\glob\sync.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "c:\\gitviews\\mockup\\Tools\\nodejs\\\\node.exe" "c:\\gitviews\\mockup\\Tools\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "gulp"
npm ERR! cwd C:\gitviews\mockup
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! path C:\Users\root\AppData\Roaming\npm\node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-stream\node_modules\glob\sync.js
npm ERR! fstream_path C:\Users\root\AppData\Roaming\npm\node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-stream\node_modules\glob\sync.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! fstream_finish_call chmod
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack c:\gitviews\mockup\Tools\nodejs\node_modules\npm\node_modules\fstream\lib\writer.js:305:19
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat 'C:\Users\root\AppData\Roaming\npm\node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-stream\node_modules\minimatch\minimatch.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "c:\\gitviews\\mockup\\Tools\\nodejs\\\\node.exe" "c:\\gitviews\\mockup\\Tools\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "gulp"
npm ERR! cwd C:\gitviews\mockup
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! path C:\Users\root\AppData\Roaming\npm\node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-stream\node_modules\minimatch\minimatch.js
npm ERR! fstream_path C:\Users\root\AppData\Roaming\npm\node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-stream\node_modules\minimatch\minimatch.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack c:\gitviews\mockup\Tools\nodejs\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, chmod 'C:\Users\root\AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\node_modules\findup-sync\node_modules\resolve-dir\node_modules\global-modules\node_modules\global-prefix\index.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "c:\\gitviews\\mockup\\Tools\\nodejs\\\\node.exe" "c:\\gitviews\\mockup\\Tools\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "gulp"
npm ERR! cwd C:\gitviews\mockup
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! path C:\Users\root\AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\node_modules\findup-sync\node_modules\resolve-dir\node_modules\global-modules\node_modules\global-prefix\index.js
npm ERR! fstream_path C:\Users\root\AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\node_modules\findup-sync\node_modules\resolve-dir\node_modules\global-modules\node_modules\global-prefix\index.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! fstream_finish_call chmod
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack c:\gitviews\mockup\Tools\nodejs\node_modules\npm\node_modules\fstream\lib\writer.js:305:19
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! notarget No compatible version found: natives@'>=1.1.0-0 <2.0.0-0'
npm ERR! notarget No valid targets found.
npm ERR! notarget Perhaps not compatible with your version of node?
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "c:\\gitviews\\mockup\\Tools\\nodejs\\\\node.exe" "c:\\gitviews\\mockup\\Tools\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "gulp"
npm ERR! cwd C:\gitviews\mockup
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! code ETARGET
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\gitviews\mockup\npm-debug.log
npm ERR! not ok code 0

**Comment by KenanY** [comment]
As far as I know, `npm@1` is no longer supported. If this occurs with the latest stable release of `npm`, then I will happily reopen.
