### ISSUE TITLE
missing script: start

### ISSUE THREAD

**Issue by AdrianaBlue** [npm/npm#16424]
#### I'm opening this issue because:
when i want to npm start, i see this and i have in my package.json "start": "webpack-dev-server --progress", and it is not working. i cannot open the file in my browser.
  -
### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
Could you upload the debug file to <https://gist.github.com/> and post a link to it here?

**Comment by KenanY** [comment]
Also, seeing your `package.json` would help a ton too. Feel free to remove bits you don't wanna disclose.

**Comment by Bubbleblyat** [comment]
I have the same problem! I am trying to create a simple Discord Webhook and I followed this tutorial:

https://www.youtube.com/watch?v=n7JU47KiYR4

I know it probably is something stupid that I missed but yeah I would appreciate some help. Thanks!

**Comment by KenanY** [comment]
@Bubbleblyat Could you provide the same context (debug log, `package.json`) I asked of @AdrianaBlue? You can upload these files to <https://gist.github.com/>.

**Comment by Bubbleblyat** [comment]
@KenanY Done!

https://gist.github.com/Bubbleblyat/3b7f4710b590b8987c32353c4767af7f

**Comment by pete-j-turnbull** [comment]
@Bubbleblyat You have no start script - only a test one. The error message is pretty much bang on. Running npm test will get you what you want.

**Comment by Bubbleblyat** [comment]
"@Bubbleblyat You have no start script - only a test one. The error message is pretty much bang on. Running npm test will get you what you want."

How do I make a starting script then?

I have been running npm test and that is when it gives me the error:

Your environment has been set up for using Node.js 7.9.0 (x64) and npm.

C:\Users\lukas>npm test

> ddwktest@1.0.0 test C:\Users\lukas
> nodemon index.js

[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node index.js`
C:\Users\lukas\index.js:8
var webhook = process.env.DISCORD_WEBHOOK;\https://discordapp.com/api/webhooks/305379766725246976/Eq_8DXVGlv9yKV2Cfv7mj1OUEbpdKCcMBz3-Uubkl_qwJVNp7YHmS50nJzkZkbLLxqGS
                                          ^
SyntaxError: Invalid or unexpected token
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
npm ERR! Test failed.  See above for more details.

C:\Users\lukas>

**Comment by legodude17** [comment]
That is a problem with your `index.js` not having correct formatting. Try running a linter on it.

**Comment by Bubbleblyat** [comment]
@legodude17 Can you give me a quick walkthrough? Tried doing it but I just got a weird error so Idk what I did wrong hahaha, sincerely Lukas

**Comment by KenanY** [comment]
Can I see like the first ~10 lines of `index.js`? I might be able to spot the syntax error for you :)

**Comment by AdrianaBlue** [comment]
here you are:import React from 'react';import ReactDOM from 'react-dom';import App from './App';import './index.css';ReactDOM.render( <App />, document.getElementById('root'));Dnia 1 maja 2017 o 18:26 Kenan Yildirim <notifications@github.com> napisał(a):Can I see like the first ~10 lines of index.js? I might be able to spot the syntax error for you :)—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by AdrianaBlue** [comment]
import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';
import './index.css';

ReactDOM.render(
  <App />,
  document.getElementById('root')
);

**Comment by AdrianaBlue** [comment]
I was working in App.js 
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';

class App extends Component {
  render() {
    return (
      <div className="App">
        <div className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h2>Welcome to React</h2>
        </div>
        <p className="App-intro">
          To get started, edit <code>src/App.js</code> and save to reload.
        </p>
      </div>
    );
  }
}

export default App;
and then I had to see it in localhost:3000
, unfo I couldn't. Btw, here is my index.js 
import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';
import './index.css';

ReactDOM.render(
  <App />,
  document.getElementById('root')
);
maybe I made some syntax error....?

**Comment by KenanY** [comment]
@AdrianaBlue Sorry, I should have clarified that I was asking @Bubbleblyat. From you specifically, I'm still waiting on https://github.com/npm/npm/issues/16424#issuecomment-296489089 and https://github.com/npm/npm/issues/16424#issuecomment-296489121.
