### ISSUE TITLE
npm error when deploy docker to azure container service

### ISSUE THREAD

**Issue by jessetolson** [npm/npm#16429]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I am developing in docker. My docker-compose functions properly for a local deploy on my mac, with packages for my node.js application being properly installed via npm. However, when I ssh into my azure container service and attempt to run docker-compose it fails with the following npm error. 

web_1        | npm info it worked if it ends with ok
web_1        | npm info using npm@4.2.0
web_1        | npm info using node@v7.9.0
web_1        | npm ERR! Linux 3.19.0-65-generic
web_1        | npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
web_1        | npm ERR! node v7.9.0
web_1        | npm ERR! npm  v4.2.0
web_1        | npm ERR! path /usr/src/app/package.json
web_1        | npm ERR! code ENOENT
web_1        | npm ERR! errno -2
web_1        | npm ERR! syscall open
web_1        | 
web_1        | npm ERR! enoent ENOENT: no such file or directory, open '/usr/src/app/package.json'
web_1        | npm ERR! enoent ENOENT: no such file or directory, open '/usr/src/app/package.json'
web_1        | npm ERR! enoent This is most likely not a problem with npm itself
web_1        | npm ERR! enoent and is related to npm not being able to find a file.
web_1        | npm ERR! enoent 
web_1        | 
web_1        | npm ERR! Please include the following file with any support request:
web_1        | npm ERR!     /root/.npm/_logs/2017-04-24T12_48_46_148Z-debug.log
amadatus_web_1 exited with code 254

For reference, my package.json file is:
{
  "name": "Amadatus",
  "version": "1.0.0",
  "description": "Amadatus App",
  "main": "server.js",
  "scripts": {
    "start": "node server.js"
  },
  "dependencies": {
    "accounting": "^0.4.1",
    "async": "^1.5.2",
    "bcrypt-nodejs": "^0.0.3",
    "bluebird": "^3.4.7",
    "body-parser": "^1.15.1",
    "chrono-node": "^1.2.5",
    "compression": "^1.6.2",
    "cookie-parser": "^1.4.1",
    "csv-parse": "^1.2.0",
    "dotenv": "^2.0.0",
    "express": "^4.13.4",
    "express-csv": "^0.6.0",
    "express-validator": "^2.20.4",
    "express-winston": "^2.0.0",
    "fs-extra": "^2.0.0",
    "gulp": "^3.9.1",
    "gulp-angular-templatecache": "latest",
    "gulp-autoprefixer": "^3.1.0",
    "gulp-concat": "latest",
    "gulp-csso": "^1.1.0",
    "gulp-if": "^2.0.0",
    "gulp-ng-annotate": "^2.0.0",
    "gulp-plumber": "^1.1.0",
    "gulp-sass": "^2.2.0",
    "gulp-sourcemaps": "^1.6.0",
    "gulp-uglify": "^1.5.3",
    "i18n": "^0.8.3",
    "jsonwebtoken": "^5.7.0",
    "lodash": "^4.17.4",
    "moment": "^2.12.0",
    "moment-range": "^2.2.0",
    "moment-timezone": "^0.5.13",
    "mongoose": "^4.4.8",
    "mongoose-valid8": "^0.1.1",
    "morgan": "^1.7.0",
    "multer": "^1.2.1",
    "nodemailer": "^2.3.0",
    "numeral": "^2.0.4",
    "pm2": "^1.0.2",
    "redis": "^2.6.3",
    "request": "^2.69.0",
    "socket.io": "^1.4.5",
    "vinyl-buffer": "^1.0.0",
    "winston": "^2.3.0",
    "winston-daily-rotate-file": "^1.4.0",
    "yargs": "^4.3.2"
  },
  "devDependencies": {
    "response-time": "^2.3.1"
  },
  "engines": {
    "node": "6.1.0"
  }
}

and my docker-compose.yml:
version: "2"
services:
  web:
    build: .
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - "80:80"
    links:
      - redis
      - mongodb
  redis:
    image: redis
    ports:
      - "6379:6379"    
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes_from:
      - mongodata
  mongodata:
    image: tianon/true
    volumes:
      - /data/db

I'm not sure if this is a npm issue or not, but I'm a little bit at a loss. I appreciate any insight you might be able to provide into this issue. 

### supporting information:
macOS, deploying to azure container services
deploying using docker

**Comment by legodude17** [comment]
Where is your `package.json`?

**Comment by jessetolson** [comment]
It is in the source's root folder... same folder as the docker-compose.yml

**Comment by chaim1221** [comment]
Who are you, denvercoder9!?!?! What did you see!?!?!? @jessetolson
