### ISSUE TITLE
`npm help` does not show help

### ISSUE THREAD

**Issue by jkufner** [npm/npm#16439]
For example `$ npm help install` shows some wierd useless list of something starting with `npm help install`. It should show documentation of the `install` command.

A good example of help command is git — it shows man page of the command, or some suggestions what to read if the requested command does not exist.

**Comment by KenanY** [comment]
I cannot reproduce this issue with `npm@4.6.1` on Linux. When I run
`npm help install`, the manpage for `npm-install(1)` is displayed.

**Comment by jkufner** [comment]
All I get is this:

```
$ npm help install
Top hits for "install"
————————————————————————————————————————————————————————————————————————————————
npm help install                                                      install:64
npm help scripts                                                      install:45
npm help folders                                                      install:40
npm help config                                                       install:32
...
```

```
$ npm --version -vv
1.4.21
```

**Comment by KenanY** [comment]
@jkufner Could you try the latest stable release of `npm`? `npm@1` is no longer supported.

**Comment by jkufner** [comment]
Funny, i have the latest Debian package. … So it looks like a problem in Debian, not here. Thank you.
