### ISSUE TITLE
README.md not packaged

### ISSUE THREAD

**Issue by JbIPS** [npm/npm#16438]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

When packaging an new release of my lib, the `README.md` file is systematically ignored. I tried without the `.npmignore`, it works fine (but include a bit too much), I switched to `package.json -> files`, still no `README.md` (even if it's listed explicitly). This is related to a previous [issue](https://github.com/npm/www/issues/166) on the website.

#### How can the CLI team reproduce the problem?

Checkout the [repo](https://github.com/silexlabs/unifile), create a tarball with `npm pack` and list the content.

### supporting information:

 - `npm -v` prints: 3.9.5
 - `node -v` prints: 6.2.2
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux (Fedora 25)
 - Network issues:
   - Geographic location where npm was run: France
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
I cannot reproduce this, with `npm@4.6.1` on Linux:

``` bash
$ git clone https://github.com/silexlabs/unifile.git
$ cd unifile/
$ npm pack
$ tar -tzf unifile-1.0.0.tgz
package/package.json
package/README.md
package/LICENSE
package/CHANGELOG.md
package/lib/index.js
package/lib/unifile-dropbox.js
package/lib/unifile-ftp.js
package/lib/unifile-github.js
package/lib/unifile-remoteStorage.js
package/lib/unifile-webdav.js
```

**Comment by JbIPS** [comment]
Alright, this must be specific to npm 3.9.5. I updated to 3.10.10 and the `README.md` is here!

Thank you
