### ISSUE TITLE
npm install - SDK Demo Master - Hyperledger fabric client

### ISSUE THREAD

**Issue by Deepakguru1990** [npm/npm#16437]
#### I'm opening this issue because:
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.

#### What's going wrong?
npm install error even after giving proper https/ http proxy.

### supporting information:

 - `npm -v` prints: v6.9.5
 - `node -v` prints: v3.10.10
 - `npm config get registry` prints:  https://registry.npmjs.org/

 - Windows, OS X/macOS, or Linux?:  Windows
 - Network issues:
   - Geographic location where npm was run: India
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.

Please find the GithubGist link: 
https://gist.github.com/Deepakguru1990/d6a8d859aa20d4953896918d1483fb88

<!--
    Thank you for contributing to npm! Please review this checklist
    before submitting your issue.

**Comment by legodude17** [comment]
Does it work without the proxy and a stable internet connection?

**Comment by Deepakguru1990** [comment]
Its not working without a proxy also. 
The package.json file has the following:
  "repository": {
    "type": "git",
    "url": "https://github.com/IBM-Blockchain/SDK-Demo.git"
  },
  "license": "Apache-2.0",
  "dependencies": {
    "hfc": "^0.6.5"
  }

I feel that there is a problem when trying to connect to the github url. Since its trying to pull packages from registry, it can't work without stable internet connection.

It is failing with:
npm ERR! network tunneling socket could not be established, cause=connect ETIMED                                                                                                                OUT 10.68.248.34:443
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin                                                                                                                gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

Any suggestions will be helpful. I am looking into this issue for more than 3 days.

Thanks,
Deepak.

**Comment by legodude17** [comment]
What happens when you click [this link](https://github.com/IBM-Blockchain/SDK-Demo.git)?

**Comment by Deepakguru1990** [comment]
I am able to view the link: https://github.com/IBM-Blockchain/SDK-Demo
