### ISSUE TITLE
Failure to install artillary - flagged npm issue. Can someone help?

### ISSUE THREAD

**Issue by SMSJIM** [npm/npm#16434]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by SMSJIM** [comment]
Failure to install artillary - flagged npm issue. Can someone help? Here is npm-debug file.

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'artillary' ]
2 info using npm@1.3.21
3 info using node@v6.9.1
4 verbose cache add [ 'artillary', null ]
5 verbose cache add name=undefined spec="artillary" args=["artillary",null]
6 verbose parsed url Url {
6 verbose parsed url   protocol: null,
6 verbose parsed url   slashes: null,
6 verbose parsed url   auth: null,
6 verbose parsed url   host: null,
6 verbose parsed url   port: null,
6 verbose parsed url   hostname: null,
6 verbose parsed url   hash: null,
6 verbose parsed url   search: null,
6 verbose parsed url   query: null,
6 verbose parsed url   pathname: 'artillary',
6 verbose parsed url   path: 'artillary',
6 verbose parsed url   href: 'artillary' }
7 silly lockFile bf5c8824-artillary artillary
8 verbose lock artillary C:\Users\jgoins\AppData\Roaming\npm-cache\bf5c8824-artillary.lock
9 silly lockFile bf5c8824-artillary artillary
10 silly lockFile bf5c8824-artillary artillary
11 verbose addNamed [ 'artillary', '' ]
12 verbose addNamed [ null, '*' ]
13 silly lockFile 3586c3df-artillary artillary@
14 verbose lock artillary@ C:\Users\jgoins\AppData\Roaming\npm-cache\3586c3df-artillary.lock
15 silly addNameRange { name: 'artillary', range: '*', hasData: false }
16 silly addNameRange number 2 { name: 'artillary', range: '*', hasData: true }
17 silly addNameRange versions [ undefined, [] ]
18 error TypeError: Cannot read property 'latest' of undefined
18 error     at next (C:\Program Files\nodejs\node_modules\npm\lib\cache.js:688:35)
18 error     at C:\Program Files\nodejs\node_modules\npm\lib\cache.js:676:5
18 error     at saved (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\get.js:142:7)
18 error     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:133:7
18 error     at FSReqWrap.oncomplete (fs.js:123:15)
19 error If you need help, you may report this *entire* log,
19 error including the npm and node versions, at:
19 error     <http://github.com/isaacs/npm/issues>
20 error System Windows_NT 10.0.10586
21 error command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "artillary"
22 error cwd C:\artillary
23 error node -v v6.9.1
24 error npm -v 1.3.21
25 verbose exit [ 1, true ]

**Comment by legodude17** [comment]
Please update your `npm`.

**Comment by KenanY** [comment]
Yeah, `npm@1.3` is years old and is no longer supported. The odd thing is that your Node.js version is pretty new, but somehow your `npm` version isn't.

Also, do note that no package with the name "artillary" exists, hence the error you are seeing.
