### ISSUE TITLE
weex init npm

### ISSUE THREAD

**Issue by 15800489316** [npm/npm#16436]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'serve' ]
2 info using npm@4.1.2
3 info using node@v7.5.0
4 verbose stack Error: Invalid name: "npm install"
4 verbose stack     at ensureValidName (C:\Program Files\nodejs\node_modules\npm\node_modules\normalize-package-data\lib\fixer.js:336:15)
4 verbose stack     at Object.fixNameField (C:\Program Files\nodejs\node_modules\npm\node_modules\normalize-package-data\lib\fixer.js:215:5)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\normalize-package-data\lib\normalize.js:32:38
4 verbose stack     at Array.forEach (native)
4 verbose stack     at normalize (C:\Program Files\nodejs\node_modules\npm\node_modules\normalize-package-data\lib\normalize.js:31:15)
4 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:349:5)
4 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:124:5)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:243:12
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
4 verbose stack     at tryToString (fs.js:426:3)
5 verbose cwd E:\appsclient\Weex
6 error Windows_NT 6.1.7601
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "serve"
8 error node v7.5.0
9 error npm  v4.1.2
10 error Invalid name: "npm install"
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@15800489316 The `"name"` property in your `package.json` cannot have spaces. Remove the space and this error should go away.

**Comment by 15800489316** [comment]
Wo ，thank you very much ,I will  try tomorrow




发自网易邮箱大师
On 04/25/2017 23:21, Kenan Yildirim wrote:

@15800489316 The "name" property in your package.json cannot have spaces. Remove the space and this error should go away.

**Comment by 15800489316** [comment]
I try once,did not find space. And I found package.json is automatically generated ，so I delete this file and weex init then npm install ，but the problem still exists




发自网易邮箱大师
在2017年04月26日 00:46，15800489316 写道：
Wo ，thank you very much ,I will  try tomorrow




发自网易邮箱大师
On 04/25/2017 23:21, Kenan Yildirim wrote:

@15800489316 The "name" property in your package.json cannot have spaces. Remove the space and this error should go away.

**Comment by KenanY** [comment]
@15800489316 Alright, can I see the `package.json` then? You can upload it to <https://gist.github.com/>, and comment on this issue with the link to it. (Don't attach it to an email reply, because that won't go through.)

**Comment by 15800489316** [comment]
![weex](https://cloud.githubusercontent.com/assets/13979155/25693172/57776fa0-30da-11e7-8f06-8bc058a09b6e.png)

**Comment by KenanY** [comment]
@15800489316 I still a space in the `"name"` field. Try changing

```
"name": "npm install",
```

to, for example,

```
"name": "my-weex-project",
```

**Comment by 15800489316** [comment]
Ok, I will try tomorrow ，thank you




发自网易邮箱大师
On 05/04/2017 21:58, Kenan Yildirim wrote:

@15800489316 I still a space in the "name" field. Try changing

"name": "npm install",


to, for example,

"name": "my-weex-project",

**Comment by 15800489316** [comment]
![weex](https://cloud.githubusercontent.com/assets/13979155/25731489/620b43ca-3179-11e7-8136-0853ffcd6c9c.png)
I  try it as you say ,but the same bug is exist

**Comment by KenanY** [comment]
@15800489316 Your issue is totally different now. As the error message states, your `"serve"` script is throwing an error code. All `npm` is doing here is letting you know about it. My _guess_ is that `node build/init.js` is returning the error code, so I would try debugging that first. Good luck!

**Comment by 15800489316** [comment]
everything is ok ,thank you very much
![weex](https://cloud.githubusercontent.com/assets/13979155/25733005/cfb69a6a-3187-11e7-8769-bab6df0bba29.png)
