### ISSUE TITLE
NPM install hangs on most of HTTP requests (QNAP TS-251+)

### ISSUE THREAD

**Issue by baramuse** [npm/npm#16446]
#### I'm opening this issue because:
  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

network request stalls.
I can't even ctrl-c, need to ctrl-z and kill the process.
It eats up 100% of the cpu core, and 58M of ram

I tried every debug level I can't see what's stalling the http requests.
I have a lot of node scripts running on the same NAS, so I KNOW the node's http requests work.
I just don't know where to go to further debug the problem.

It's happening on all my QNAPs, but they all use the same network architecture, so maybe it's a networking problem but how to be sure, only npm seems to have troubles !

I already tried to reduce the number of concurrent sockets to 3.
[~] # cat .npmrc 
maxsockets=3

Thanks for the help

#### How can the CLI team reproduce the problem?

```
[/share/CACHEDEV1_DATA/smartcv/hik-anpr-pusher] # npm install pm2 -g -ddd
npm info it worked if it ends with ok
npm verb cli [ '/share/CACHEDEV1_DATA/.qpkg/Entware-ng/bin/node',
npm verb cli   '/opt/bin/npm',
npm verb cli   'install',
npm verb cli   'pm2',
npm verb cli   '-g',
npm verb cli   '-ddd' ]
npm info using npm@3.10.3
npm info using node@v6.7.0
npm sill loadCurrentTree Starting
npm sill install loadCurrentTree
npm sill install readGlobalPackageData
npm sill fetchPackageMetaData pm2
npm sill fetchNamedPackageData pm2
npm sill mapToRegistry name pm2
npm sill mapToRegistry using default registry
npm sill mapToRegistry registry https://registry.npmjs.org/
npm sill mapToRegistry data Result {
npm sill mapToRegistry   raw: 'pm2',
npm sill mapToRegistry   scope: null,
npm sill mapToRegistry   escapedName: 'pm2',
npm sill mapToRegistry   name: 'pm2',
npm sill mapToRegistry   rawSpec: '',
npm sill mapToRegistry   spec: 'latest',
npm sill mapToRegistry   type: 'tag' }
npm sill mapToRegistry uri https://registry.npmjs.org/pm2
npm verb request uri https://registry.npmjs.org/pm2
npm verb request no auth needed
npm info attempt registry request try #1 at 10:41:00 GMT+0100 (BST)
npm verb request using bearer token for auth
npm verb request id d9625bd82f00c057
npm http request GET https://registry.npmjs.org/pm2
^C^C^Z.............] \ normalizeTree: http request GET https://registry.npmjs.org/pm2
```

### supporting information:

 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [x ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.

**Comment by abhisheksoni27** [comment]
Why are you using the **non-existent** `-ddd` flag? Save-dev has a alias called -D, if that's what you want.

**Comment by legodude17** [comment]
Does it work without the VPN?

**Comment by baramuse** [comment]
It does not.
The NAS has two interfaces and I forced the default gateway to the second interface (connected to a classic internet router) and experience the same problem.

**Comment by legodude17** [comment]
What happens when you click [this link](https://registry.npmjs.org/pm2)?

**Comment by baramuse** [comment]
I tried already a wget on the registery url, works like a charm !

[~] # wget https://registry.npmjs.org/pm2
--2017-04-27 23:37:04--  https://registry.npmjs.org/pm2
Resolving registry.npmjs.org... 151.101.128.162, 151.101.0.162, 151.101.192.162, ...
Connecting to registry.npmjs.org|151.101.128.162|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 569274 (556K) [application/json]
Saving to: 'pm2'
pm2     100%[======================================>] 555.93K   133KB/s    in 4.2s    

2017-04-27 23:37:09 (133 KB/s) - 'pm2' saved [569274/569274]

That's why I'm trying to "debug" npm itself :/

**Comment by legodude17** [comment]
What are the results of:
1. `npm config get registry`
2. `npm config get http-proxy`
3. `npm config get https-proxy`

**Comment by baramuse** [comment]
[~] # npm config get registry
https://registry.npmjs.org/
[~] # npm config get http-proxy
undefined
[~] # npm config get https-proxy
null

**Comment by legodude17** [comment]
Does it work if you setup your proxy correctly?

**Comment by legodude17** [comment]
Do you have a proxy?

**Comment by baramuse** [comment]
no proxy no, direct internet connection
