### ISSUE TITLE
Scope tag in URL

### ISSUE THREAD

**Issue by omyani** [npm/npm#16445]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I have a private npm registry, I wish to install some of the deps from official NPM repo and some from the private one. I tried tagging scoped packages, having .npmrc pointing at my repo. However, when npm gets to handle a scoped package, the scoping tag is [encoded and] included within the URL itself.

I am wondering whether that is the intended usage. If it does, what are the expectations from npm repo implementor? Is it to strip-off `@...%2f` sequences from the URL? To expect very specific scoping-tags?

#### How can the CLI team reproduce the problem?

Just try to add a scoped package and inspect the resulted URL (npm install --verbose)

**Comment by legodude17** [comment]
What do you mean by tagging scoped packages?

**Comment by omyani** [comment]
I refer to scoped packages as described here: https://docs.npmjs.com/misc/scope

Here's a little experiment, in a fresh dir:
```
$ echo "@myorg registry=https://registry.npmjs.org" > .npmrc
$ npm install --verbose "@myorg/express" 
...
npm http 404 https://registry.npmjs.org/@myorg%2fexpress
```

**Comment by legodude17** [comment]
And what is the problem? If you request a scoped package, that is what `npm` will request.

**Comment by omyani** [comment]
It appears that NPM registries do not support serving scoped packages out-of-the-box, as demonstrated above. 

So, in your opinion, what is a proper way to install packages from multiple NPM registries within the same `package.json`?

**Comment by legodude17** [comment]
What do you mean "as shown above" where? The 404 error you got is just because `@myorg/express` does not exist.

**Comment by legodude17** [comment]
I would suggest that you use scopes on all the registries except the main one.

**Comment by omyani** [comment]
So there is the problem (in my opinion), the existing client behavior requires registries to know that they are being "scoped", and each registry from its side, prefers to believe it is the only registry in the entire world.

I started looking into the client code, if you could point me to the area where the effective URL is actually set. I would try to propose a pull-request.

Thanks
