### ISSUE TITLE
npm pack Zip archive support

### ISSUE THREAD

**Issue by deed02392** [npm/npm#16447]
#### What's the feature?
`npm pack` zip archive support

#### What problem is the feature intended to solve?
Portability issues when dealing with node on Windows/non-Unix systems.

#### Is the absence of this feature blocking you or your team? If so, how?
It creates a dependency on third-party software when using Windows.

#### Is this feature similar to an existing feature in another tool?
No.

#### Is this a feature you're prepared to implement, with support from the npm CLI team?
Yes.

**Comment by legodude17** [comment]
> It creates a dependency on third-party software when using Windows.

How does it do that? You mean node's gzip?

**Comment by deed02392** [comment]
Perhaps I've jumped the gun, but I imagined the use case of a packed npm
package was extracting to a directory and then running npm install.

**Comment by legodude17** [comment]
You could use the same thing the `npm` does for that which is just node modules (`tar` and `gzip`).

**Comment by deed02392** [comment]
I feel like with Zip being the most widely supported archive format we should at least offer the ability to pack modules in this way. Then users can inspect packed archives on the same machine more easily (rather than writing a Node script as they must do on Windows, or copying and unpacking elsewhere from the command line).

**Comment by legodude17** [comment]
Yeah, another thing that might be nice is to just take all the files that would be packed and then put them in a new dir.
