### ISSUE TITLE
gulp can't install on my pc

### ISSUE THREAD

**Issue by zayjoe** [npm/npm#16455]
This is my error log file.

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'gulp-cli',
1 verbose cli   '-g' ]
2 info using npm@3.10.10
3 info using node@v6.10.2
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData gulp-cli
8 silly fetchNamedPackageData gulp-cli
9 silly mapToRegistry name gulp-cli
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'gulp-cli',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'gulp-cli',
12 silly mapToRegistry   name: 'gulp-cli',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/gulp-cli
14 verbose request uri https://registry.npmjs.org/gulp-cli
15 verbose request no auth needed
16 info attempt registry request try #1 at 2:38:49 PM
17 verbose request id 504e538e78d2949f
18 http request GET https://registry.npmjs.org/gulp-cli
19 verbose stack AssertionError: 1255 == 0
19 verbose stack     at ClientRequest.onConnect (C:\Program Files\nodejs\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:159:14)
19 verbose stack     at ClientRequest.g (events.js:291:16)
19 verbose stack     at emitThree (events.js:116:13)
19 verbose stack     at ClientRequest.emit (events.js:194:7)
19 verbose stack     at Socket.socketOnData (_http_client.js:394:11)
19 verbose stack     at emitOne (events.js:96:13)
19 verbose stack     at Socket.emit (events.js:188:7)
19 verbose stack     at readableAddChunk (_stream_readable.js:176:18)
19 verbose stack     at Socket.Readable.push (_stream_readable.js:134:10)
19 verbose stack     at TCP.onread (net.js:551:20)
20 verbose cwd C:\
21 error Windows_NT 10.0.14393
22 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "gulp-cli" "-g"
23 error node v6.10.2
24 error npm  v3.10.10
25 error 1255 == 0
26 error If you need help, you may report this error at:
26 error     <https://github.com/npm/npm/issues>
27 verbose exit [ 1, true ]

**Comment by legodude17** [comment]
Try updating to the latest version of `npm`.

**Comment by zayjoe** [comment]
I found the solution from stackoverflow.
npm config set proxy false
npm cache clean
npm install gulp-cli -g
Now it ok

**Comment by KenanY** [comment]
Closing as resolved then.
