### ISSUE TITLE
npm install for ionic is failing

### ISSUE THREAD

**Issue by angelo43jjj** [npm/npm#16458]
When I run the following command for my ionic project, I am getting an error:
npm install --save-dev @ionic/cli-plugin-ionic-angular @ionic/cli-plugin-cordova

The error log is attched:

[npmError.docx](https://github.com/npm/npm/files/963054/npmError.docx)

**Comment by KenanY** [comment]
@angelo43jjj Could you upload the debug file to <https://gist.github.com/> instead of converting to a non-plaintext format? Thanks!

**Comment by angelo43jjj** [comment]
I could not upload the log file . It says it's not supported. I am attaching a txt file 
[2017-04-27T22_03_37_730Z-debug - Copy.log.txt](https://github.com/npm/npm/files/963474/2017-04-27T22_03_37_730Z-debug.-.Copy.log.txt)

**Comment by angelo43jjj** [comment]
thanks a lot. will check it out. It has been working fine all the while and I have not touched it for a while and now I am getting this error. Will follow the troubleshooting guide thanks.

**Comment by angelo43jjj** [comment]
my initial finding is cafile = undefined. I am also not using any proxy. I am connected to the internet directly at home.

**Comment by angelo43jjj** [comment]
strict-ssl = true, should I make it strict-ssl = false?

**Comment by angelo43jjj** [comment]
ran "npm config set strict-ssl false". Now all good

**Comment by angelo43jjj** [comment]
thanks for the help KenanY
