### ISSUE TITLE
npm issue, might be a common issue but it persists even on fresh install.

### ISSUE THREAD

**Issue by kdrahul** [npm/npm#16451]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [1] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I was going to install electron but i started getting an error. I removed whole node.js with its installer and installed it again but the problem persists. I'm still new to all this. Any help is appreciated.
![image](https://cloud.githubusercontent.com/assets/28073462/25461927/63606122-2b09-11e7-96cb-51aa4f594852.png)

#### How can the CLI team reproduce the problem?
I have no idea how to reproduce this because this is happening even if i reinstall it. Fresh installation is causing this issue. 

### supporting information:

 - `npm -v` prints:4.2.0
 - `node -v` prints:v7.9.0
 - `npm config get registry` prints: it prints whatever screenshot i've posted about
 - Windows, OS X/macOS, or Linux?:Windows 10
 - Network issues:None
   - Geographic location where npm was run:
   -[1] My own computer
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
Try reinstalling `npm` from somewhere else.

**Comment by kdrahul** [comment]
somewhere else? i didn't get you there. I did reinstall it in a different location. Problem still persists.

**Comment by legodude17** [comment]
Like, the nodejs website.

**Comment by kdrahul** [comment]
That's where i downloaded it. I'm on a windows machine so that's the only way i know to do it. :/

**Comment by legodude17** [comment]
Try removing `npm` completely and then reinstalling from the nodejs website.
