### ISSUE TITLE
npm update -g encounters "typeerror Error: Argument #2: Expected string but got object"

### ISSUE THREAD

**Issue by netheril96** [npm/npm#16463]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

npm ERR! code EINVALIDTYPE
npm ERR! typeerror Error: Argument #2: Expected string but got object
npm ERR! typeerror     at addDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:452:3)
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/lib/install/deps.js:405:5
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
npm ERR! typeerror     at Array.forEach (native)
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
npm ERR! typeerror     at Array.forEach (native)
npm ERR! typeerror     at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
npm ERR! typeerror     at loadDeps (/usr/local/lib/node_modules/npm/lib/install/deps.js:397:3)
npm ERR! typeerror     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
npm ERR! typeerror     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
npm ERR! typeerror     at chain (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/lib/install/deps.js:329:5
npm ERR! typeerror     at cb (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/lib/install/deps.js:378:21
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/lib/install/and-add-parent-to-errors.js:7:24
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/lib/install/deps.js:559:11
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <https://github.com/npm/npm/issues>

#### How can the CLI team reproduce the problem?

I don't know how to reproduce the issue. It probably has something to do with the packages I have installed. The top level packages are

```
/usr/local/lib
├── babili@0.0.12
├── eslint@3.19.0
├── http-server@0.9.0
├── live-server@1.2.0
├── npm@4.6.1
├── serve@5.1.4
├── typescript@2.3.1
├── webpack@2.4.1
└── webpack-dev-server@2.4.5
```

The full log is at https://gist.github.com/netheril96/90057bba4108013c405e33e0a987c4d6

### supporting information:

 - `npm -v` prints: 4.6.1
 - `node -v` prints: v7.9.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS
 - Network issues:
   - Geographic location where npm was run: China
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
What command did you run?
