### ISSUE TITLE
CLI installation failure

### ISSUE THREAD

**Issue by sohamdey2006** [npm/npm#16461]
I am trying to install Angular 2. I installed node 6 ( along with which npm got installed automatically ). But then when I am trying to install the CLI to complete the Angular 2 installation process by running the command, npm install -g angular/cli , I am getting the below error. I ran the command promt as admin too, but still the error persists. Any help is very much appreciated.  I have installed node 6 and I am on windows machine.

UNABLE_TO_GET_USER_CERTIFICATE_LOCALLY

**Comment by legodude17** [comment]
Please go through the [troubleshooting guide](https://github.com/npm/npm/wiki/Troubleshooting).
