### ISSUE TITLE
NPM Script: Run a bash/batch script

### ISSUE THREAD

**Issue by ThibaultVlacich** [npm/npm#16468]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I have a script defined on my package.json that run a bash/batch file. It is defined like this:
```json
  "scripts": {
    "appRun": "./gradlew appRun"
  }
```

This is working perfectly on UNIX systems, but not on Windows. On UNIX it should execute the `gradlew` file, and on Windows the `gradlew.bat` file

If I want it to work on Windows, I have to write it like this:
```json
  "scripts": {
    "appRun": ".\\gradlew appRun"
  }
```

How could I make something that works on both platforms ? It seems like a bug of npm (or node) because if I execute `./gradlew appRun` on a Windows terminal, it works perfectly.

And if you're wonderind why I have this script and don't run directly ./gradlew appRun then, this is why:
```json
  "scripts": {
    "start": "concurrently \"npm run appRun\" \"gulp watch\"",
    "appRun": "./gradlew appRun"
  }
```

### supporting information:

 - `npm -v` prints: 3.10.10
 - `node -v` prints: v6.10.2
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: all

**Comment by legodude17** [comment]
I would suggest you find a utility.

**Comment by ThibaultVlacich** [comment]
I tried finding something for this but had no luck :/
