### ISSUE TITLE
sails install

### ISSUE THREAD

**Issue by zkossowski** [npm/npm#16465]
#### I'm opening this issue because:

  - [ x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

current OpenBSD

# npm install sails -g
npm ERR! code EINVALIDTYPE
npm ERR! typeerror Error: Argument #3: Expected object but got function
npm ERR! typeerror     at fetchPackageMetadata (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:46:3)
npm ERR! typeerror     at limited (/usr/local/lib/node_modules/npm/node_modules/call-limit/call-limit.js:29:10)
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/lib/install/deps.js:248:14
npm ERR! typeerror     at /usr/local/lib/node_modules/slide/lib/async-map.js:52:35
npm ERR! typeerror     at Array.forEach (native)
npm ERR! typeerror     at /usr/local/lib/node_modules/slide/lib/async-map.js:52:11
npm ERR! typeerror     at Array.forEach (native)
npm ERR! typeerror     at asyncMap (/usr/local/lib/node_modules/slide/lib/async-map.js:51:8)
npm ERR! typeerror     at exports.getAllMetadata (/usr/local/lib/node_modules/npm/lib/install/deps.js:228:3)
npm ERR! typeerror     at Object.Installer.loadArgMetadata (/usr/local/lib/node_modules/npm/lib/install.js:324:3)
npm ERR! typeerror     at Object.Installer.readGlobalPackageData (/usr/local/lib/node_modules/npm/lib/install.js:575:8)
npm ERR! typeerror     at Array.<anonymous> (/usr/local/lib/node_modules/slide/lib/bind-actor.js:15:8)
npm ERR! typeerror     at LOOP (/usr/local/lib/node_modules/slide/lib/chain.js:15:14)
npm ERR! typeerror     at chain (/usr/local/lib/node_modules/slide/lib/chain.js:20:5)
npm ERR! typeerror     at Object.Installer.loadCurrentTree (/usr/local/lib/node_modules/npm/lib/install.js:359:3)
npm ERR! typeerror     at Array.<anonymous> (/usr/local/lib/node_modules/slide/lib/bind-actor.js:15:8)

#### How can the CLI team reproduce the problem?
current OpenBSD

# npm install sails -g

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
Hello! Can you upload the debug log to <https://gist.github.com/> and link it here? It'll provide more insight into this issue. Thanks!

**Comment by KenanY** [comment]
Closing due to no reply after a month.
