### ISSUE TITLE
angular cli partially installed on windows 7 and 8.

### ISSUE THREAD

**Issue by walegbenga** [npm/npm#16466]
[angular.txt](https://github.com/npm/npm/files/964404/angular.txt)
[t.txt](https://github.com/npm/npm/files/964407/t.txt)

#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
Could you upload the npm-debug.log as a plaintext file to https://gist.github.com/ and post a link to it here?

**Comment by walegbenga** [comment]
this is the link. https://gist.github.com/walegbenga/953c751b58881f23548ec6228cc07cfe

**Comment by walegbenga** [comment]
i tried doing it the way I saw it on angularbooks.com. I also tried re-installing npm, typescript and they both install successfully but angular cli after installation will give some warnings. You will also see the what it said while trying to create a new project in it. 
thanks for your help
