### ISSUE TITLE
 Maximum call stack size exceeded

### ISSUE THREAD

**Issue by ancin** [npm/npm#16462]
win7 system
$ npm install json-server@0.8 -g

....
npm ERR! node v4.4.0
npm ERR! npm  v3.0.0
npm ERR! Maximum call stack size exceeded

and exit.

**Comment by legodude17** [comment]
Please go through the [troubleshooting guide](https://github.com/npm/npm/wiki/Troubleshooting).

**Comment by montogeek** [comment]
I am getting this error with npm 5.0.0

**Comment by legodude17** [comment]
`npm-debug.log`
