### ISSUE TITLE
npm installing incorrect version of github dependency

### ISSUE THREAD

**Issue by crookedneighbor** [npm/npm#16475]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

`braintree-web@3.14.0` has a dependency on a github repo, `wrap-promise#1.1.0`. When inspecting the package.json for the installed `braintree-web` module, I can see the correct version of `wrap-promise`:

<img width="557" alt="screen shot 2017-04-29 at 12 15 10 pm" src="https://cloud.githubusercontent.com/assets/2916945/25557381/c2c018d8-2cd5-11e7-84b3-279b43d2a8ef.png">

But when actually installing the module, it's getting the previous version, 1.0.0

<img width="880" alt="screen shot 2017-04-29 at 12 14 45 pm" src="https://cloud.githubusercontent.com/assets/2916945/25557385/d373bed2-2cd5-11e7-9c53-a6a64acaf6cd.png">

### supporting information:

 - `npm -v` prints: 3.10.10
 - `node -v` prints: v6.9.5
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: MacOS

Reported originally here: https://github.com/braintree/braintree-web/issues/290

**Comment by KenanY** [comment]
This looks correct to me though. It says that it installed https://github.com/braintree/wrap-promise/commit/84faafe1b8683d6f512de65205923e107382a9db, which is indeed what the `1.1.0` git tag points to. At that point in the git history, the `"version"` field of the `package.json` [is set to `"1.0.0"`](https://github.com/braintree/wrap-promise/blob/1.1.0/package.json#L3), hence why `npm ls` shows that version.

**Comment by KenanY** [comment]
Gonna try to reproduce this now.

**Comment by KenanY** [comment]
``` bash
$ npm i braintree-web

$ node
> require('wrap-promise')
{ [Function: wrapPromise] wrapPrototype: [Function] }
```

Looks like the function that was reported as missing is actually there.

**Comment by crookedneighbor** [comment]
Okay, I think I see what the problem is. We never updated the package.json version when we bumped the tagged version. So people with old installs of wrap-promise think that they have the correct version when installing. We'll remove the `1.1.0` tag from Github, correct the version number and re-tag. This _should_ fix it.

Thanks for the help!
