### ISSUE TITLE
NPM installation problems

### ISSUE THREAD

**Issue by Parthjhaveri** [npm/npm#16470]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I un-installed NPM globally, but when I try to re-install it on the command line by typing npm install -g npm, I get this weird error saying:

-bash: /usr/local/bin/npm: No such file or directory

Any idea why? The reason I un-installed NPM was because when I was trying to do npm install, it would kill the installation instantly on the terminal.

Thanks!

**Comment by KenanY** [comment]
Well, if you uninstall `npm`, then you can no longer run any `npm` commands (since `npm` is no longer in your system). You could try [the fancy install](https://github.com/npm/npm#fancy-install-unix) if you wanna reinstall `npm`.

**Comment by Parthjhaveri** [comment]
Thank you!
