### ISSUE TITLE
TypeError when executing 'npm install . -g'

### ISSUE THREAD

**Issue by rehierl** [npm/npm#16478]
#### I'm opening this issue because:

"npm install . -g" will produce a secondary error:
TypeError: Cannot read property 'path' of null

#### What's going wrong?

I am about to publish a module for the first time and was following the steps described in [Before publishing](https://docs.npmjs.com/misc/developers#before-publishing-make-sure-your-package-installs-and-works).

So I opened a terminal, moved into the project folder and entered the first command (i.e. "npm install . -g"). The terminal then displayed "Cannot read property 'path' of null" and mentioned the following [log file](https://pastebin.com/rLdpFK8H).

Executing the suggested second command (i.e. "npm install 'path-to-package' ") failed as well, but instead the terminal displayed "Invalid version: '0.1' " and mentioned the following [log file 2](https://pastebin.com/j6WG4jCy).

Changing package.json's version value to "1.0.0" resulted in both commands to succeed. So I was indeed trying to use an invalid version value ("0.1"). Nevertheless, trying to install my package locally from it's project folder gave me a clear indication of why it failed initially, whereas the actual error was hidden when I tried to install it globally.

#### How can the CLI team reproduce the problem?

Create a test project with a package.json file that contains an invalid version value ("-1.0.0" will also work), then execute "npm install . -g" as described in "Before publishing".

### supporting information:

 - `npm -v` prints: "4.2.0"
 - `node -v` prints: "v7.9.0"
 - `npm config get registry` prints: "https://registry.npmjs.org/"
 - Windows, OS X/macOS, or Linux?: Linux Mint x64
 - Network issues: N.A.
 - Container: N.A.

**Comment by legodude17** [comment]
Duplicate of #10686.

**Comment by rehierl** [comment]
Oops, sorry.

So should this issue be closed?  
It can be closed as far as I am concerned.

**Comment by rehierl** [comment]
Is it really a duplicate, because 10686 mentions
```Cannot read property **'target'** of null```,
whereas I got the message:
```Cannot read property **'path'** of null```

**Comment by legodude17** [comment]
You can close it if you want.

**Comment by rehierl** [comment]
Closed
