### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by FuqingWang** [npm/npm#16471]
I got an error when I tried to run my Reactjs app with "npm start".

sombody@somecompany-Tech00:~/my-app$ npm start

> my-app@0.1.0 start /home/user/my-app
> react-scripts start

npm ERR! weird error 8
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0

I have been investigating for a while but got nothing. Someone please give me a hand!

**Comment by legodude17** [comment]
Please go through the [troubleshooting guide](https://github.com/npm/npm/wiki/Troubleshooting).

**Comment by KenanY** [comment]
@FuqingWang Does `node --version` work on your system? Have you read `/usr/share/doc/nodejs/README.Debian`? Did you try `apt-get install nodejs-legacy`?

**Comment by FuqingWang** [comment]
@KenanY 
Yes node --version works. Current node version v7.8.0.
I read the README.Debian, I don't think it's a misname issue. It happened to me at the first place but I fixed it using symlink.
And I did install nodejs-legacy. But the error persists.

**Comment by FuqingWang** [comment]
@legodude17  I didn't get much from the troubleshooting guide either. The only thing I have is the WARN messages, but I can't find anything about what those ERR messages mean.

**Comment by KenanY** [comment]
All right, what is the result of running `node ./node_modules/.bin/react-scripts start`?

**Comment by FuqingWang** [comment]
@KenanY  It runs and gives the following compile error message. Looks like I'm missing a module or something?

Failed to compile.

Error in ./src/index.js
Module build failed: Error: Cannot find module 'electron-to-chromium' (While processing preset: "/home/fuqing/my-app/node_modules/react-scripts/node_modules/babel-preset-react-app/node_modules/babel-preset-env/lib/index.js") (While processing preset: "/home/fuqing/my-app/node_modules/react-scripts/node_modules/babel-preset-react-app/index.js")
 @ multi main

**Comment by KenanY** [comment]
Hmm, yeah looks like it. Maybe all that's needed is a `rm -rf node_modules/ && npm install`

**Comment by FuqingWang** [comment]
@KenanY Tried that and the compile error persists. I did `npm install electron-to-chromium` as well, still getting the missing module error.

**Comment by KenanY** [comment]
Looks like another instance of https://github.com/facebookincubator/create-react-app/issues/1967. Can't reproduce it myself locally :(

**Comment by FuqingWang** [comment]
@KenanY It worked! I think I mistakenly installed npm under /home instead of the project directory and that's where the error come from. Thanks for your help!
