### ISSUE TITLE
unsuccessful install - "cb() never called!"

### ISSUE THREAD

**Issue by rburkey87** [npm/npm#16488]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Whenever I try to install npm, it returns the following:
`$ npm install`
`npm WARN deprecated node-uuid@1.4.8: Use uuid module instead`
`npm ERR! cb() never called!`

I've tried to get around it by using `npm install npm@latest -g` but then gulp doesn't seem to install correctly and I get an endless circle of error messages. I searched through the existing npm issues here and haven't had any success. I've recently re-cloned my working branch on gitHub to have a fresh install, but it's still having issues.

#### How can the CLI team reproduce the problem?

<script src="https://gist.github.com/rburkey87/735c272b6312d85b690b5a7e0152d466.js"></script>

### supporting information:

 - `npm -v` prints: 4.5.0
 - `node -v` prints: 6.10.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
   - [x] I honestly don't know. It's always worked in the past, but I'd guess I use a proxy when downloading Git repos.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).
   - [x] Absolutely no idea (sorry)

**Comment by legodude17** [comment]
Try updating `node` and `npm`.

**Comment by rburkey87** [comment]
I haven't been able to get it to initially install, but I tried running `npm update` and it threw the same error message as `npm install` (described in the issue above). `node update` (haven't done that one before, so I hope that's the correct syntax) threw the error that it can't find the update module (which makes sense, because it hasn't been installed yet).

**Comment by legodude17** [comment]
You would want to go to the node.js website and install the latest version.

**Comment by rburkey87** [comment]
Okay, I installed node/npm directly from the node.js website and I'm still having the same issue. :/

**Comment by rburkey87** [comment]
oh my goodness... I didn't shut down my command prompt before re-attempting. It's working now! Thank you for putting up with my newbie-ness! :)
