### ISSUE TITLE
Squash 'npm WARN prefer global' message if package is required as dep

### ISSUE THREAD

**Issue by Marak** [npm/npm#1648]
Is it possible / easy to do / sane to not show the following WARN message if the package is required as a dependency? 

     npm WARN prefer global npm@1.0.103 should be installed with -g

Since in this case, we are requiring `npm` programmatically in `jitsu` and as a dep in our `package.json`.

This isn't a high priority for us, but I wanted to ask. Thanks!

**Comment by CKarper** [comment]
This is definitely back for me with v3.3.3, on Win64.

**Comment by ehsalazar** [comment]
Reopening the issue at the request of users that are experiencing this behavior on v3.3.3.

**Comment by othiym23** [comment]
Reclosing this in favor of #8517, because this issue is positively antique.
