### ISSUE TITLE
npm install play-audio error

### ISSUE THREAD

**Issue by fd-Joker** [npm/npm#16486]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
npm ERR! Linux 3.19.0-68-generic
npm ERR! argv "/home/courser/.nvm/versions/node/v6.10.2/bin/node" "/home/courser/.nvm/versions/node/v6.10.2/bin/npm" "install"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code EREADFILE

npm ERR! Error extracting /home/courser/.npm/media/0.0.0/package.tgz archive: ENOENT: no such file or directory, open '/home/courser/.npm/media/0.0.0/package.tgz'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/courser/Courses/advanced-web-tech/voxel-clientmc/app/npm-debug.log

#### How can the CLI team reproduce the problem?
npm install play-audio@~0.1.0

### supporting information:

 - `npm -v` prints: 3.10.10
 - `node -v` prints: v6.10.2
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Ubuntu 14.04
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
Please go through the [troubleshooting guide](https://github.com/npm/npm/wiki/Troubleshooting).
