### ISSUE TITLE
Getting error "Cannot read property 'path' of null" when installing package protractor

### ISSUE THREAD

**Issue by getarbind** [npm/npm#16489]
[2017-05-01T20_54_46_955Z-debug.txt](https://github.com/npm/npm/files/968805/2017-05-01T20_54_46_955Z-debug.txt)

#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [X ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
C:\WINDOWS\system32>npm install -g protractor
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "protractor"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0

npm ERR! Cannot read property 'path' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\n0308811\AppData\Roaming\npm-cache\_logs\2017-05-01T20_54_
46_955Z-debug.log

#### How can the CLI team reproduce the problem?

Installed node.js
C:\WINDOWS\system32>node --version
v7.9.0

After that trying to protactor package
C:\WINDOWS\system32>npm install -g protractor

### supporting information:

 - `npm -v` prints: 4.2.0
 - `node -v` prints:v7.9.0
 - `npm config get registry` prints:https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?:Windows 7 sp1
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [x ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
Duplicate of #10686.

**Comment by getarbind** [comment]
#10686 says "Cannot read property 'target' of null". In my case Its Cannot read property 'path' of null.
Thats the reason created a new one. 
It could be same one.

BTW is there any solution for #10686 ??

Thanks

**Comment by legodude17** [comment]
I think the underlying issue is that either the package does not exist or your network is broken.

**Comment by KenanY** [comment]
Yup, log indicates that your requests to the registry are timing out.

**Comment by getarbind** [comment]
@legodude17  Yes... It is network issue. I have set the proxy like below

npm config set proxy http://User:Passwprd@www-proxy.company.com:80
npm config set https-proxy http://User:Passwprd@www-proxy.company.com:80

And I am able to install Protactor package.
Thanks for the help and we can close this issue.
