### ISSUE TITLE
No documentation for "npm login"?

### ISSUE THREAD

**Issue by rehierl** [npm/npm#16487]
- executing "npm login" on a terminal will work. it will ask for Username, Password, Email and then confirms successful login to "https://registry.npmjs.org/".
- so that command is actually supported!

markdown files

- [npm-logout.md](https://github.com/npm/npm/blob/latest/doc/cli/npm-logout.md) - exists
- [npm-login.md](https://github.com/npm/npm/blob/latest/doc/cli/npm-login.md) - does not

documentation on npmjs.com

- [logout page on npmjs.com](https://docs.npmjs.com/cli/logout) - exists
- [login page on npmjs.com](https://docs.npmjs.com/cli/login) - does not

### supporting information:

 - `npm -v` prints: "4.2.0"
 - `node -v` prints: "v7.9.0"
 - `npm config get registry` prints: "https://registry.npmjs.org/"
 - Windows, OS X/macOS, or Linux?: Linux x64

**Comment by KenanY** [comment]
`npm login` is an _alias_ for [`npm adduser`](https://docs.npmjs.com/cli/adduser), hence why it doesn't get it's own page (because it would be an exact duplicate of the `npm adduser` page).

**Comment by rehierl** [comment]
> "npm login" is an alias for "npm adduser"

Oh I see, thanks. I didn't look at that command because I didn't want to "add a new user".

--

By letting "npm login" behave identical to "adduser", you essentially assume that they also have the exact same meaning. Isn't that a little problematic?

What happens if I accidentally mistype my login/name?  
I assume that a new account will be created? Is that acceptable?

**Comment by KenanY** [comment]
@rehierl Yup, you're right. A typo will create a new account, even though that's probably not what anyone wants to happen. See the previous discussions https://github.com/npm/npm/issues/4151 and https://github.com/npm/npm/issues/8337. My understanding is that eventually, `npm adduser` and `npm login` will become separate from each other.

**Comment by rehierl** [comment]
Ha, I almost expected a "Now that won't happen." kind of answer.
Thanks again KenanY.

Closing this issue, because the missing documentation turned out to be no mishap.

--

IMHO, I'd even deprecate/remove the adduser command because account creation should be done by signing up directly to a registry. Also, if the maintainers of a private registry wanted to control who is publishing, they would have to partially disable that command by returning an error if the username doesn't exist.

And I wouldn't add a 'delete user' command as mentioned by othiym23 in 8337. This would be asking for abuse. A user should have to directly log into a registry and use the account settings to mark his/her account for deletion.

**Comment by estaub** [comment]
@rehieri It took me 10 or so minutes of googling to finally come across this thread to understand where login is documented.  It being an alias for something else isn't a good reason not to document it - docs are for people who don't know that!  Other doc on the site, such as https://docs.npmjs.com/private-modules/intro , use login, which is why I needed to look it up in the first place.  

It's fine if the doc is just a "See adduser" link.
