### ISSUE TITLE
i have an ionic project when i type npm install this error appear npm ERR! shasum check failed for C:\Users\moha_\AppData\Local\Temp\npm-5636-07bb10c6\registry.npmjs.org\ionic-angular\-\ionic-angular-2.0.1.tgz npm ERR! Expected: 1f78b9801d149202c29765df22f1a4d39bfbebed npm ERR! Actual:   78a01bd2449ee7e18d50c884b1802e94c3ffbaf0 npm ERR! From:     https://registry.npmjs.org/ionic-angular/-/ionic-angular-2.0.1.tgz  npm ERR! A complete log of this run can be found in: npm ERR!     C:\Users\moha_\AppData\Roaming\npm-cache\_logs\2017-05-02T08_31_45_158Z-debug.log

### ISSUE THREAD

**Issue by moha-lanser-87** [npm/npm#16492]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [+ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
4.5.0
 - `node -v` prints:
6.10.2
 - `npm config get registry` prints:
https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?:
windows 10
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
Could you upload the npm-debug.log as a plaintext file to https://gist.github.com/ and post a link to it here?
