### ISSUE TITLE
npm search output after publishing scoped packages unexpectedly shows "prehistoric"

### ISSUE THREAD

**Issue by tanem** [npm/npm#16490]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Publishing scoped public packages results in unexpected search output. However installation of the scoped packages appears to be fine (the expected version is installed).

Not sure if it's an issue with my setup or not (e.g. I'm using a newer version of node/npm at the moment, see below) - the packages are forks we're maintaining:

https://github.com/atomic-app/snakecase-keys
https://github.com/atomic-app/map-obj

#### How can the CLI team reproduce the problem?

```
$ npm search @atomic-app
NAME                      | DESCRIPTION          | AUTHOR          | DATE        | VERSION  | KEYWORDS
@atomic-app/map-obj       |                      |                 | prehistoric | 0.0.0    |
@atomic-app/map-obj       |                      |                 | prehistoric | 0.0.0    |
@atomic-app/snakecase-key |                      |                 | prehistoric | 0.0.0    |
s                         |                      |                 |             |          |
@atomic-app/map-obj       |                      |                 | prehistoric | 0.0.0    |
@atomic-app/map-obj       |                      |                 | prehistoric | 0.0.0    |
@atomic-app/map-obj       |                      |                 | prehistoric | 0.0.0    |
```

### supporting information:

 - `npm -v` prints: `4.1.2`
 - `node -v` prints: `7.7.3`
 - `npm config get registry` prints: `https://registry.npmjs.org/`

**Comment by benmarten** [comment]
We are seeing the same issue for our newly published package: `npm search leanplum`
```
leanplum-sdk              |                      |                 | prehistoric | 0.0.0    | 
```
Anyone knows what's going on? Clicking on the actual package, everything looks fine, but the npmjs.com search and npm search are broken...
