### ISSUE TITLE
fetchMetadata: sill mapToRegistry uri https://registry.npmjs.org taking to long at install protractor

### ISSUE THREAD

**Issue by samshaikh87** [npm/npm#16496]
#### I'm opening this issue because:

  - [X ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [X ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

To reproduce:

Installed JDE 1.8.0_131
Set the java home variable
set the java path
installed node.js
installed npm
added the npm path to Path env. variable
npm version installed is 4.5.0
Installed IDE - Atom
Now, when installing protractor using the command : npm install -g protractor, it is stuck with the bar just moving and nothing happening since last one hour. Check screenshot.

Output from ember version --verbose && npm --version && yarn --version:
C:\Users\pctr294290>npm install -g protractor
[       ...........] | fetchMetadata: sill mapToRegistry uri https://registry.n
![protractorerror](https://cloud.githubusercontent.com/assets/26921095/25632623/52ba005c-2f42-11e7-89b2-0769fa22dc09.jpg)

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?: Windows

 - Network issues:
   - Geographic location where npm was run: USA
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows. No
   - [ ] I develop using Vagrant on OS X or Linux. No
   - [ ] I develop / deploy using Docker. No
   - [ ] I deploy to a PaaS (Triton, Heroku). No

<!--
    Thank you for contributing to npm! Please review this checklist
    before submitting your issue.

    - Please check if there's a solution in the troubleshooting wiki:
      https://github.com/npm/npm/blob/latest/TROUBLESHOOTING.md

    - Also ensure that your new issue conforms to npm's contribution guidelines:
      https://github.com/npm/npm/blob/latest/CONTRIBUTING.md

    - Participation in this open source project is subject to the npm Code of Conduct:
      https://www.npmjs.com/policies/conduct

![protractorerror](https://cloud.githubusercontent.com/assets/26921095/25633497/4347ae96-2f45-11e7-9571-47a7b13faca7.jpg)

**Comment by samshaikh87** [comment]
CLI output -C:\Users\pctr294290>npm install -g protractor
npm ERR! path C:\Users\pctr294290\AppData\Roaming\npm\node_modules\protractor\ex
ample
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall unlink
npm ERR! Error: EPERM: operation not permitted, unlink 'C:\Users\pctr294290\AppD
ata\Roaming\npm\node_modules\protractor\example'
npm ERR!     at Error (native)
npm ERR!  { Error: EPERM: operation not permitted, unlink 'C:\Users\pctr294290\A
ppData\Roaming\npm\node_modules\protractor\example'
npm ERR!     at Error (native)
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path: 'C:\\Users\\pctr294290\\AppData\\Roaming\\npm\\node_modules\\pr
otractor\\example' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\pctr294290\AppData\Roaming\npm-cache\_logs\2017-05-02T18_4
1_41_867Z-debug.log

**Comment by legodude17** [comment]
Did you run it as Administrator?

**Comment by samshaikh87** [comment]
yes, ran as administrator..

**Comment by ali-hellani** [comment]
same issue here

**Comment by SalahAdDin** [comment]
I have the same problem, but in a `AWS EC2` instance.

**Comment by pouyajabbarisani** [comment]
same problem....
