### ISSUE TITLE
Refusing to install bootstrap as a dependency of itself

### ISSUE THREAD

**Issue by Celery28** [npm/npm#16491]
#### I'm opening this issue because:

  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.

#### What's going wrong?
0 info it worked if it ends with ok
1 verbose cli [ '/Applications/Appium.app/Contents/Resources/node/bin/node',
1 verbose cli   '/Applications/Appium.app/Contents/Resources/node/bin/npm',
1 verbose cli   'install',
1 verbose cli   'bootstrap' ]
2 info using npm@3.8.3
3 info using node@v5.10.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData bootstrap
8 silly fetchNamedPackageData bootstrap
9 silly mapToRegistry name bootstrap
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'bootstrap',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   name: 'bootstrap',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/bootstrap
14 verbose request uri https://registry.npmjs.org/bootstrap
15 verbose request no auth needed
16 info attempt registry request try #1 at 15:52:23
17 verbose request id a8d725a6da8b39e9
18 verbose etag W/"5902590a-c6c8"
19 verbose lastModified Thu, 27 Apr 2017 20:48:10 GMT
20 http request GET https://registry.npmjs.org/bootstrap
21 http 304 https://registry.npmjs.org/bootstrap
22 verbose headers { date: 'Tue, 02 May 2017 07:52:24 GMT',
22 verbose headers   via: '1.1 varnish',
22 verbose headers   'cache-control': 'max-age=300',
22 verbose headers   etag: 'W/"5902590a-c6c8"',
22 verbose headers   age: '0',
22 verbose headers   connection: 'keep-alive',
22 verbose headers   'x-served-by': 'cache-nrt6124-NRT',
22 verbose headers   'x-cache': 'HIT',
22 verbose headers   'x-cache-hits': '1',
22 verbose headers   'x-timer': 'S1493711544.278203,VS0,VE111',
22 verbose headers   vary: 'Accept-Encoding' }
23 silly get cb [ 304,
23 silly get   { date: 'Tue, 02 May 2017 07:52:24 GMT',
23 silly get     via: '1.1 varnish',
23 silly get     'cache-control': 'max-age=300',
23 silly get     etag: 'W/"5902590a-c6c8"',
23 silly get     age: '0',
23 silly get     connection: 'keep-alive',
23 silly get     'x-served-by': 'cache-nrt6124-NRT',
23 silly get     'x-cache': 'HIT',
23 silly get     'x-cache-hits': '1',
23 silly get     'x-timer': 'S1493711544.278203,VS0,VE111',
23 silly get     vary: 'Accept-Encoding' } ]
24 verbose etag https://registry.npmjs.org/bootstrap from cache
25 verbose get saving bootstrap to /Users/bdqn/.npm/registry.npmjs.org/bootstrap/.cache.json
26 verbose correctMkdir /Users/bdqn/.npm correctMkdir not in flight; initializing
27 silly install normalizeTree
28 silly loadCurrentTree Finishing
29 silly loadIdealTree Starting
30 silly install loadIdealTree
31 silly cloneCurrentTree Starting
32 silly install cloneCurrentTreeToIdealTree
33 silly cloneCurrentTree Finishing
34 silly loadShrinkwrap Starting
35 silly install loadShrinkwrap
36 silly loadShrinkwrap Finishing
37 silly loadAllDepsIntoIdealTree Starting
38 silly install loadAllDepsIntoIdealTree
39 silly rollbackFailedOptional Starting
40 silly rollbackFailedOptional Finishing
41 silly runTopLevelLifecycles Starting
42 silly runTopLevelLifecycles Finishing
43 silly install printInstalled
44 verbose stack Error: Refusing to install bootstrap as a dependency of itself
44 verbose stack     at checkSelf (/Applications/Appium.app/Contents/Resources/node/lib/node_modules/npm/lib/install/validate-args.js:53:14)
44 verbose stack     at Array.<anonymous> (/Applications/Appium.app/Contents/Resources/node/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
44 verbose stack     at LOOP (/Applications/Appium.app/Contents/Resources/node/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
44 verbose stack     at chain (/Applications/Appium.app/Contents/Resources/node/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
44 verbose stack     at /Applications/Appium.app/Contents/Resources/node/lib/node_modules/npm/lib/install/validate-args.js:16:5
44 verbose stack     at /Applications/Appium.app/Contents/Resources/node/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
44 verbose stack     at Array.forEach (native)
44 verbose stack     at /Applications/Appium.app/Contents/Resources/node/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
44 verbose stack     at Array.forEach (native)
44 verbose stack     at asyncMap (/Applications/Appium.app/Contents/Resources/node/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
45 verbose cwd /Users/bdqn/Downloads/bootstrap-3.3.7
46 error Darwin 16.1.0
47 error argv "/Applications/Appium.app/Contents/Resources/node/bin/node" "/Applications/Appium.app/Contents/Resources/node/bin/npm" "install" "bootstrap"
48 error node v5.10.1
49 error npm  v3.8.3
50 error code ENOSELF
51 error Refusing to install bootstrap as a dependency of itself
52 error If you need help, you may report this error at:
52 error     <https://github.com/npm/npm/issues>
53 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
Make sure the `"name"` property in your `package.json` is **not** set to `"bootstrap"`. Make it something more unique :)
