### ISSUE TITLE
Error installing Angular Cli

### ISSUE THREAD

**Issue by alexcarrasco93** [npm/npm#16494]
#### I'm opening this issue because:
  - [x] npm is producing an incorrect install.

#### What's going wrong?
Not avaible to install last version of angular cli

#### How can the CLI team reproduce the problem?

I just try to install angular cli and it shows an error

### supporting information:

 - Windows, OS X/macOS, or Linux?:
Windows 10
 - Network issues:
   - Geographic location where npm was run:
Barcelona, Spain

#### What's the feature? 
Install last version angular cli

#### What problem is the feature intended to solve?
Install error

![image](https://cloud.githubusercontent.com/assets/22663646/25626696/9e8bcb64-2f60-11e7-83d1-eac146b81aca.png)

[2017-05-02T15_46_40_444Z-debug.txt](https://github.com/npm/npm/files/971023/2017-05-02T15_46_40_444Z-debug.txt)

**Comment by KenanY** [comment]
There is a typo in your command, you typed `@angualar/cli` instead of `@angular/cli`.
