### ISSUE TITLE
npm places incorrect path to node binary into shebang

### ISSUE THREAD

**Issue by Feuermurmel** [npm/npm#16505]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Demonstrating this with an Ubuntu 16.04 container, but I have witnessed this on a range of OS/distribution combinations:

    # docker run -it ubuntu:16.04
    root@1e9c0d774030:/# apt update
    [...]
    root@1e9c0d774030:/# apt install nodejs npm
    [...]
    root@1e9c0d774030:/# npm install -g yuglify
    /usr/local/bin/yuglify -> /usr/local/lib/node_modules/yuglify/bin/yuglify
    /usr/local/lib
    `-- yuglify@0.1.4 
      +-- nopt@2.1.2 
      | `-- abbrev@1.1.0 
      +-- uglify-js@1.3.5 
      `-- ycssmin@1.0.1 
    
    root@1e9c0d774030:/# yuglify
    /usr/bin/env: 'node': No such file or directory

The problem is that the installed script (`yuglify` in this case, but happens with all packages I tested) contains an incorrect shebang line:

    root@6de671b9fe03:/# head -n 1 $(which yuglify)
    #!/usr/bin/env node
    root@6de671b9fe03:/# which node
    root@6de671b9fe03:/# which nodejs
    /usr/bin/nodejs

There is no binary called `node` and the `npm` script itself points to the `nodejs` binary, which installed scripts probably should also do:

    root@6de671b9fe03:/# head -n 1 $(which npm)
    #!/usr/bin/nodejs

Compare this to `pip`, which places the absolute path to the Python interpreter it was used to run into any installed scripts. Form my experience, this is much more reliable:

    # apt install python3-pip
    [...]
    # pip3 install pytest
    [...]
    # head -n 1 $(which pytest)
    #!/usr/bin/python3

#### How can the CLI team reproduce the problem?

See https://gist.github.com/Feuermurmel/b8420f390c4369ce453491ea25fed116

### supporting information:

 - `npm -v` prints:

```
# npm -v
3.5.2
```

 - `node -v` prints:

```
# node -v
bash: node: command not found
# nodejs -v
v4.2.6
```

 - `npm config get registry` prints:

```
# npm config get registry
https://registry.npmjs.org/
```

 - Windows, OS X/macOS, or Linux?:

Linux

 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
   - [x] I work at an ISP, I have a reliable internet connection.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [x] I develop / deploy using Docker.

To demonstrate, I used docker. For deployments, I use plain VMs.

   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
FWIW, `npm`'s own shebang [is not pointing to `nodejs`](https://github.com/npm/npm/blob/v3.5.2/cli.js#L1). I assume that modification was made by the maintainer(s) of the `npm` package on the `apt` repository.

**Comment by metux** [comment]
https://github.com/metux/npm/tree/bugfix-4.6.1
