### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by prapulla6** [npm/npm#16501]
#### I'm opening this issue because:

  - [ ] Other (_see below for feature requests_):

```
C:\Users\prapulla_murthy\quickstart-master>npm install
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! syscall getaddrinfo

npm ERR! getaddrinfo EAI_AGAIN registry.npmjs.org:443
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\prapulla_murthy\quickstart-master\npm-debug.log
```

### supporting information:

 - `npm -v` prints: 3.10.10
 - `node -v` prints: v6.10.2
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?: Windows
 - Network issues:
   - Geographic location where npm was run: Have npm installed on machine
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
Please check your internet connection.

**Comment by prapulla6** [comment]
Internet connection is fine. Please let me know what else could be the
issue?

Thanks,
Prafulla

**Comment by legodude17** [comment]
What are the results of:
1. `npm config get registry`
2. `npm config get http-proxy`
3. `npm config get https-proxy`

**Comment by prapulla6** [comment]
Joshua,

I set http-proxy to null. It worked fine for me. Thanks

I have to develop a web site using Angular2 . What is the website which
helps us to develop with sample code? please let me know.

Thanks,
Prafulla
