### ISSUE TITLE
Unmet peer dependency error while installing protractor cucumber framework

### ISSUE THREAD

**Issue by samshaikh87** [npm/npm#16509]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [X ] Other (_see below for feature requests_):

Trying to install protractor-cucumber-framework using command - npm install --save-dev protractor-cucumber-framework. 

Getting the following error -
npm WARN saveError ENOENT: no such file or directory, open 'C:\package.json'
C:\
+-- UNMET PEER DEPENDENCY cucumber@>= 1.3.0 || >= 2.0.0-rc.0
+-- UNMET PEER DEPENDENCY protractor@>= 3.0.0
`-- protractor-cucumber-framework@3.1.0

npm WARN enoent ENOENT: no such file or directory, open 'C:\package.json'
npm WARN protractor-cucumber-framework@3.1.0 requires a peer of cucumber@>= 1.3.
0 || >= 2.0.0-rc.0 but none was installed.
npm WARN protractor-cucumber-framework@3.1.0 requires a peer of protractor@>= 3.
0.0 but none was installed.
npm WARN !invalid#1 No description
npm WARN !invalid#1 No repository field.
npm WARN !invalid#1 No README data
npm WARN !invalid#1 No license field.

#### How can the CLI team reproduce the problem?
1. Download and Installing JDK and Node.js
2. To access Java Globally configure Environment variables
Path of JDK on machine: C:\Program Files\Java\jre1.8.0_91
type "Edit" in Start and edit environement variables.
Under user vairable, create new variable "JAVA_HOME" and give the path.
Under System Variable-> edit "Path" variable and at end give ";%JAVA_HOME%\bin

Step 3: Download node.js
install node.js 
set the system path to the above npm path
type "npm --version" in command prompt will give you the version of npm

Step 4: npm install -g protractor
Step5: webdriver-manager update 
Step 6: npm install -g cucumber
Step 7: npm install --save-dev protractor-cucumber-framework

### supporting information:

 - `npm -v` prints: 3.10.10
 - `node -v` prints:  v6.10.2
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows 7 OS
 - Network issues:
   - Geographic location where npm was run: Atlanta, USA
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container: No
   - [ ] I develop using Vagrant on Windows. 
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
1. You are using the `--save-dev` flag, but you do not have a `package.json` in your current working directory, hence the `ENOENT` error. You can use `npm init` to create a `package.json` for you.
2. You need to install any peer dependencies yourself. Such as:

``` bash
npm install cucumber@'>= 1.3.0 || >= 2.0.0-rc.0' protractor@'>= 3.0.0'
```

**Comment by mstevens-bcs** [comment]
I'm getting the same messages on npm 6.9.5 installing under rhel 6.7.  

build@head2 ~ $ npm install -g protractor-cucumber-framework
/gpfs1/blxgrid/tools/general/app/node-6.9.5/lib
âââ UNMET PEER DEPENDENCY cucumber@>= 1.3.0 || >= 2.0.0-rc.0
âââ UNMET PEER DEPENDENCY protractor@>= 3.0.0
âââ protractor-cucumber-framework@3.1.0

npm WARN protractor-cucumber-framework@3.1.0 requires a peer of cucumber@>= 1.3.0 || >= 2.0.0-rc.0 but none was installed.
npm WARN protractor-cucumber-framework@3.1.0 requires a peer of protractor@>= 3.0.0 but none was installed.
  
As far as I can tell, the dependencies are met:

build@head2 ~ $ npm list -g|grep cucum
âââ¬ cucumber@2.2.0
â âââ cucumber-expressions@3.0.0
â âââ cucumber-tag-expressions@1.0.0
âââ¬ protractor-cucumber-framework@3.1.0
build@head2 ~ $ npm list -g|grep prot
â â âââ proto-list@1.2.4
âââ¬ protractor@5.1.2
âââ¬ protractor-cucumber-framework@3.1.0
âââ¬ sg-protractor-tools@1.0.4
  â â âââ dnode-protocol@0.2.2
