### ISSUE TITLE
unable to verify the first certificate : npm install -g protractor , UNABLE_TO_VERIFY_LEAF_SIGNATURE

### ISSUE THREAD

**Issue by ritesh2607** [npm/npm#16519]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.

#### What's going wrong?

C:\Users\xys>npm install -g protractor
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "protractor"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code **UNABLE_TO_VERIFY_LEAF_SIGNATURE**

npm ERR! unable to verify the first certificate
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\xys\npm-debug.log

### supporting information:

 - Windows, OS X/macOS, or Linux?: Windows 10

**Comment by legodude17** [comment]
Please update `npm` to latest
