### ISSUE TITLE
npm can run progs under ./node_modules/.bin, sub-npm cannot (Windows only)

### ISSUE THREAD

**Issue by asnowfix** [npm/npm#16529]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

With...

```json
  "scripts": {
    "prebuild": "rimraf ./dist && rimraf ./dist-umd",
  },
  "devDependencies": {
    "rimraf": "2.5.4",
  }
```

... `npm run prebuild` works (uber-npm command finds prog `rimraf` prog in `./node_modules/.bin`), but `npm build` or `npm run build` do not because the sub-npm command cannot find the rimraf script.

#### How can the CLI team reproduce the problem?

1. Incorporate the above JSON snippet in a package.json
2. On Windows (tested on Win10/x64), run `npm test`

```
$ npm test

> xxx@1.0.0 pretest C:\Users\kowalskif\Desktop\GIT\xxx
> npm run build

> xxx@1.0.0 prebuild C:\Users\kowalskif\Desktop\GIT\xxx
> rimraf ./dist && rimraf ./dist-umd && gulp versioning_svg

'rimraf' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! xxx@1.0.0 prebuild: `rimraf ./dist && rimraf ./dist-umd && gulp versioning_svg`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the xxx@1.0.0 prebuild script 'rimraf ./dist && rimraf ./dist-umd && gulp versioning_svg'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the veneer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rimraf ./dist && rimraf ./dist-umd && gulp versioning_svg
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs xxx
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls xxxx
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\kowalskif\Desktop\GIT\xxx\npm-debug.log
npm ERR! Test failed.  See above for more details.
```

### supporting information:

 - `npm -v` prints: `3.10.1`
 - `node -v` prints: `v6.10.3`
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?: Windows-10 (see above: Windows_NT 10.0.10586)
 - Network issues:
   - Geographic location where npm was run: FR
   - [ ] I use a proxy to connect to the npm registry. **not to run the test above**
   - [ ] I use a proxy to connect to the web.  **not to run the test above**
   - [ ] I use a proxy when downloading Git repos.  **not to run the test above**
   - [ ] I access the npm registry via a VPN  **not to run the test above**
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows. **native Windows**
   - [ ] I develop using Vagrant on OS X or Linux. **native Linux & OSX not affected by this issue**
   - [ ] I develop / deploy using Docker.  **not to run the test above**
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
Can you insert `echo $PATH` into the script and post output.
