### ISSUE TITLE
install not working for packages with a low number of downloads

### ISSUE THREAD

**Issue by danielbaak** [npm/npm#16521]
#### I'm opening this issue because:

  - [X] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
`npm ERR! registry error parsing json` while doing `...fetchMetadata:` on npm install [insert non-common package name here]
#### How can the CLI team reproduce the problem?
`npm install sails` or `npm install waterline`

### supporting information:

 - `npm -v` prints: 4.2.0
 - `node -v` prints: v.8.0
 - `npm config get registry` prints:  https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux
 - Network issues:
   - Geographic location where npm was run: Switzerland
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by danielbaak** [comment]
apparently the issue just fixed itself. Everything seems to be working fine again.

**Comment by 0815fox** [comment]
I also noticed the down time of like 10 minutes and was up to write a ticket as well.
