### ISSUE TITLE
leading space in dep with npm5

### ISSUE THREAD

**Issue by calvinmetcalf** [npm/npm#16520]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

installing emberjs-build@0.20.1 lists as a dependency `'ember-cli-yuidoc': ' 0.8.4'` which npm5 can't resolve as a dependency even though ember-cli-yuidoc@0.8.4 exists

### supporting information:

```
npm5 -v
5.0.0-beta.34
```

**Comment by zkat** [comment]
Fixed in `npm5@5.0.0-beta.35`. Thanks for the report!~ 🎉
