### ISSUE TITLE
unable to get local issuer certificate

### ISSUE THREAD

**Issue by mbarnett3** [npm/npm#16526]
#### I'm opening this issue because:

  - [ ] npm is producing an incorrect install.

#### What's going wrong?
Ran npm install -g cordova from Mac OS 10.12 and it fails trying to get certificate

   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the web.

**Comment by mbarnett3** [comment]
MKD25N42V0F8JC:~ admin$ npm install -g cordova
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "cordova"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code UNABLE_TO_GET_ISSUER_CERT_LOCALLY

npm ERR! unable to get local issuer certificate
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/admin/npm-debug.log

**Comment by mbarnett3** [comment]
[npm-debug.txt](https://github.com/npm/npm/files/979416/npm-debug.txt)

**Comment by legodude17** [comment]
Could you upload the npm-debug.log as a plaintext file to https://gist.github.com/ and post a link to it here?

**Comment by mbarnett3** [comment]
I was able to get around it by changing npm registry to use http instead of https
