### ISSUE TITLE
`=` semver range prefix breaking npm5

### ISSUE THREAD

**Issue by vjpr** [npm/npm#16524]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for xmldom@=0.1.19
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'xml-crypto'
npm ERR! notarget
```

Seems that when using `=` in a semver range it is breaking.

#### How can the CLI team reproduce the problem?

```
npm i xml-crypto

# no error

npm5 i xml-crypto

# No matching version found for xmldom@=0.1.19
```

### supporting information:

 - `npm5 -v` prints: 5.0.0-beta.34
 - `node -v` prints: 6.5.0
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?: macOS
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by zkat** [comment]
Thanks for the report! I thought I'd already tested exactly this, but I'll look into it. This is handled by https://github.com/npm/npm-pick-manifest

**Comment by zkat** [comment]
@vjpr `5.0.0-beta.36` should have fixed this. Thanks for the report!

fyi: `foo@=1.2.3` is _exactly_ the same as `foo@1.2.3`. But npm will accept either one, now.
