### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by LAzyFrAAnk** [npm/npm#16522]
Hi,

I have some problem on installation as below screen. 

![image](https://cloud.githubusercontent.com/assets/27416170/25713012/d85745a0-3125-11e7-939e-2161d2b3306e.png)

**Comment by zkat** [comment]
You need to install node. See

`bash: node: command not found`

**Comment by metux** [comment]
Maybe you've installed nodejs from your distro (which usually is best option, as distros - contrary to upstreams - care for making it actually production-stable), and missing the -legacy package. Distros must rename the binary, as upstream still insists in an ambigous name that conflicts with other (much older) packages. For broken packages, haven't been fixed yet, distros provide symlinks in extra packages (in deb world: nodejs-legacy).

I've just fixed latest npm here:
https://github.com/metux/npm/tree/bugfix-4.6.1

(by the way, I'll probably upload recent nodejs deb packages within the next day)

**Comment by ee32320** [comment]
Thanks, this information. I don't know about npm or git. I try do install, npm.
