### ISSUE TITLE
NPM5: Error during clone operation

### ISSUE THREAD

**Issue by EugeneHlushko** [npm/npm#16539]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
```
npm verb argv "/usr/local/bin/node" "/usr/bin/npm5" "install" "--verbose"
npm verb node v7.4.0
npm verb npm  v5.0.0-beta.39
npm ERR! code 129
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b 5.47.0 -c core.longpaths=true ssh://git@github.com/PRIVATECOMPANY/PRIVATEREPO.git /home/vagrant/.npm/_cacache/tmp/git-clone-091156e3
npm ERR! error: unknown switch `c'
```

#### How can the CLI team reproduce the problem?

Try to do npm5 install when there is a private repository present in your package.json of the following view:
`"repo": "git+ssh://git@github.com/comapnyname/repo.git#5.47.0"` where `#5.47.0` is a git release (tag) 

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [x] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
Hmm, what's the output of `git --version`?

**Comment by zkat** [comment]
Your version of git must be more than 4 years old, because the git docs for `git clone` don't go far back enough to show me where `-c` was introduced.

That said, I've push `beta.40` which only adds the longpaths option on win32, which is much less likely to have git versions from the early Paleogene. Please update try your install again and lmk if that fixed it, so I can close this issue. :)

**Comment by EugeneHlushko** [comment]
```
$ git --version
git version 1.7.1
```

Though after updating to new version of npm5 beta i am not getting `129` error code but 128 instead. Which is another case.
