### ISSUE TITLE
npm5: git add npm-shrinkwrap.json fails

### ISSUE THREAD

**Issue by isaacs** [npm/npm#16531]
Not sure why it's trying to add a non-existent npm-shrinkwrap.json file.

https://gist.github.com/isaacs/b417f4742aaef4a09fe683a211cf9f8b

**Comment by zkat** [comment]
This has been fixed in `beta.39` 🎉  Could you confirm?

**Comment by zkat** [comment]
p.s. you might wanna blow away the spurious `npm-shrinkwrap.json` this made in the spawn-wrap repo
