### ISSUE TITLE
Inconsistencies between package.json and package-lock.json with local dependencies

### ISSUE THREAD

**Issue by andreypopp** [npm/npm#16536]
#### I'm opening this issue because:

  - [x] npm is doing something I don't understand.

#### What's going wrong?

When I do `npm5 install ../some-other-package/within-a-monorepo` npm adds to `package.json`
```
"package-name": "../some-other/package/within-a-monorepo"
```
while this is being added to `package-lock.json`:
```
"package-name": "/absolute-path-to/monorepo/some-other/package/within-a-monorepo"
```

In my understanding this is an inconsistency. This also prevents me from adding `package-lock.json` to VCS as other team members might have repository cloned at different path.

### supporting information:

 - `npm -v` prints: `5.0.0-beta.39`
 - `node -v` prints: `6.10.1`
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?: macOS

**Comment by zkat** [comment]
@andreypopp hey! Thanks for the report. We're pending a merge of a branch that updates the way local file specifiers work. That should fix this right up. Hopefully that'll land in the next few days. :)

I'll let you know as soon as that lands!

**Comment by zkat** [comment]
This is fixed already (at least as of `beta.48`, but I don't remember exactly when it landed). We have different issues with local directory specs failing to install, but the path stuff is done. The other bugs are covered by other issues (like https://github.com/npm/npm/issues/16601)

They will always be saved into package-lock.json as relative paths now. :)
