### ISSUE TITLE
npm5: Agent option must be an instance of http.Agent, undefined or false.

### ISSUE THREAD

**Issue by isaacs** [npm/npm#16530]
#### I'm opening this issue because:

  - [x] npm is crashing.

#### How can the CLI team reproduce the problem?

Ran `npm i minipass@latest` in node-tar repo using development pre-8.0.0 version of node.

Debug log: https://gist.github.com/isaacs/0b8a9cb83b9b4282453ede8e1b18b0d1

**Comment by isaacs** [comment]
(Works on node 6, upgrading to latest master to see if it's already fixed.)

**Comment by isaacs** [comment]
Works fine on latest and greatest node master.  Sorry for the false alarm :)

**Comment by zkat** [comment]
This is a known bug in node@8 and has since been fixed, btw: https://github.com/nodejs/node/pull/11567
