### ISSUE TITLE
Installation of cli

### ISSUE THREAD

**Issue by AkashEdakkalathur** [npm/npm#16543]
installation of cli not happening getting error below
----------------------------------------------------
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0

npm ERR! Cannot read property 'path' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ECONNRESET

npm ERR! network socket hang up
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\1034850\AppData\Roaming\npm-cache\_logs\2017-05-06T09_16_48_516Z-debug.log

**Comment by wbhob** [comment]
Please follow the issue template so we know how to reproduce. If you don't follow the template, we have no idea what's going on.

**Comment by AkashEdakkalathur** [comment]
issue template ?? I didn't get ?

**Comment by wbhob** [comment]
The template is the data already in the issue field when you open it. It has some questions about what you're trying to do and your configured that will help us.

**Comment by AkashEdakkalathur** [comment]
I am not getting ,I what I have to do to solve this
 and I am getting an error during CLI installation below can u help me


$ npm install --save-dev @angular/cli@latest
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save-dev" "@angular/cli@latest"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ENOSELF

npm ERR! Refusing to install package with name "@angular/cli" under a package
npm ERR! also called "@angular/cli". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR!
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\1034850\AppData\Roaming\npm-cache\_logs\2017-05-08T06_57_39_719Z-debug.log

_

**Comment by wbhob** [comment]
Oh, basically, your current directory has a package.json with the name `@angular/cli`. NPM forbids you from installing a dependency of itself. 

So in your case, you can not install `@angular/cli` as a dependency of `@angular/cli` because it would be completely circular. Rename it in `package.json`.
