### ISSUE TITLE
npm5 uid must be an unsigned int

### ISSUE THREAD

**Issue by yangwao** [npm/npm#16544]
#### I'm opening this issue because:

  - [x] npm5 is crashing.

#### What's going wrong?

Won't install package standard-readme.

#### How can the CLI team reproduce the problem?
```
⫸  sudo npm5 i -g standard-readme
Password:
npm notice BETA npm5 is beta software. Please see https://github.com/npm/npm/issues/16510 for known issues, and please file a new one if you find something new.
npm ERR! uid must be an unsigned int

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/wao/.npm/_logs/2017-05-06T09_46_27_579Z-debug.log
```
https://gist.github.com/yangwao/e017819b9a7291060d14e9b7fabba243

### supporting information:

 - `npm -v` prints:
`5.0.0-beta.43`
 - `node -v` prints:
`v7.9.0`
 - `npm config get registry` prints:
`https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?:
`macOS`

**Comment by zkat** [comment]
Great find!

I'm pretty sure I know where this is happenin, but would you mind running this one more time with:

`BLUEBIRD_DEBUG=true npm5 i -g standard-readme`?

**Comment by yangwao** [comment]
Thanks 😸 great work w/ npm5.
Here it goes, hope it helps 
https://gist.github.com/yangwao/5a0a7ad54e668df5a8fca3fe62db2058

**Comment by addaleax** [comment]
Hmm, sounds a bit like what was going on in https://github.com/npm/npm/issues/13918, but that should have been fixed both on Node’s and graceful-fs’es side? :/

Can you show the contents of your `SUDO_UID` environment variable, if it’s set? (Running `env|grep SUDO` in the terminal should do, if you’re not sure how to do that.)

**Comment by yangwao** [comment]
```
bash-3.2$ env|grep SUDO
bash-3.2$ env|grep SUDO_UID
bash-3.2$
```
I think it's not set

**Comment by zkat** [comment]
@yangwao just wondering: is this still happening for you?

**Comment by zkat** [comment]
you know what, I'm ridiculous. This is terribly easy to reproduce, but I was distracted with other stuff. I'll get to this tomorrow 👌

**Comment by zkat** [comment]
nevermind, I ended up nerd-sniping myself. This should be fixed in `beta.61`. I'll let you confirm that it did indeed fix it so this issue can be closed. Cheers!

**Comment by igalic** [comment]
verified `beta.61` as works on my machine™

```
 ~ % sudo -H npm -g install npm5
[sudo] password for igalic: 
/usr/bin/npm5 -> /usr/lib/node_modules/npm5/bin/npm-cli.js
/usr/lib
└─┬ npm5@5.0.0-beta.61 
  ├─┬ cacache@9.2.2 
  │ └── y18n@3.2.1 
  └─┬ pacote@2.7.15 
    ├─┬ glob@7.1.2 
    │ ├── fs.realpath@1.0.0 
    │ └── path-is-absolute@1.0.1 
    └─┬ make-fetch-happen@2.4.6 
      ├─┬ agentkeepalive@3.1.0
      │ └─┬ humanize-ms@1.2.1 
      │   └── ms@2.0.0 
      ├─┬ http-proxy-agent@1.0.0
      │ └─┬ debug@2.6.8 
      │   └── ms@2.0.0 
      ├─┬ https-proxy-agent@1.0.0
      │ └─┬ debug@2.6.8 
      │   └── ms@2.0.0 
      └─┬ node-fetch-npm@2.0.1 
        └─┬ json-parse-helpfulerror@1.0.3 
          └── jju@1.3.0 

 ~ % sudo -H npm5 -g install npm5                               (13s 339ms)  
npm notice BETA npm5 is beta software. Please see https://github.com/npm/npm/issues/16510 for known issues, and please file a new one if you find something new.
/usr/bin/npm5 -> /usr/lib/node_modules/npm5/bin/npm-cli.js
updated 1 package in 5.928s
 ~ %                                                            (6s 710ms)
```

**Comment by zkat** [comment]
awesome! Cheers :)

**Comment by yangwao** [comment]
It works, I've tried with `npm5@5.0.0-beta.61`

```
⫸  sudo npm5 i -g standard-readme
cnpm notice BETA npm5 is beta software. Please see https://github.com/npm/npm/issues/16510 for known issues, and please file a new one if you find something new.
/usr/local/bin/standard-readme -> /usr/local/lib/node_modules/standard-readme/index.js
added 75 packages in 3.961s
[i] ~
```
