### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by Teeekz** [npm/npm#16555]
Hi there, 
I am completely new to node, I want to use it because I want to learn angular for an assignment Im doing. The tutorial i am doing is on the angular.org website, part of the tutorial requires us to install node. 

After typing into the command line:
npm install

This is the error I got:

```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @types/node@6.0.73 (node_modules/@types/node):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Invalid name: "@types/node"
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @types/jasmine@2.5.47 (node_modules/@types/jasmine):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Invalid name: "@types/jasmine"
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @types/q@0.0.32 (node_modules/@types/q):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Invalid name: "@types/q"
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10

npm ERR! Invalid name: "@types/selenium-webdriver"
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/digitalarts/angular-phonecat/npm-debug.log
```

The next step was to install bower after typing into the command line:
`bower install`

This is the next error I got:

```
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10

npm ERR! Invalid name: "@types/jasmine"
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/digitalarts/angular-phonecat/npm-debug.log

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! angular-phonecat@0.0.0 prestart: `npm install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-phonecat@0.0.0 prestart script 'npm install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-phonecat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-phonecat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-phonecat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/digitalarts/angular-phonecat/npm-debug.log
```

Please help I have no idea what this means as I am also not familiar with the command line. 
Kind regards

**Comment by legodude17** [comment]
Try updating to `npm@latest`.

**Comment by Teeekz** [comment]
I still have no success. I thought maybe the project was corrupted or I needed to understand better.

I'm am now trying to do a different tutorial but when I try install angular cli using terminal this is the error I now get

Last login: Tue Jun  6 22:01:42 on console
Tokelos-MacBook-Pro:~ digitalarts$ node -v
v6.11.0
Tokelos-MacBook-Pro:~ digitalarts$ sudo npm install @angular/cli -g
Password:
npm ERR! unpack Could not read data for @ngtools/webpack@1.4.1
npm ERR! unpack Could not read data for @ngtools/json-schema@1.1.0
npm ERR! unpack Could not read data for @angular/cli@1.1.1
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "@angular/cli" "-g"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10

npm ERR! Invalid name: "@ngtools/webpack"
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/digitalarts/npm-debug.log
Tokelos-MacBook-Pro:~ digitalarts$ 

Is this cause I do not have permission rights or am I not installing correctly?

**Comment by legodude17** [comment]
npm is still not updated to the latest version, as the log says `npm v3.10.10`.
