### ISSUE TITLE
npm5 cb() never called EACCES

### ISSUE THREAD

**Issue by yangwao** [npm/npm#16556]
#### I'm opening this issue because:

  - [x] npm is crashing.

#### What's going wrong?

```
[i] ~/P/ssb-usage-stats ☭ master ○
⫸  npm5 i
npm notice BETA npm5 is beta software. Please see https://github.com/npm/npm/issues/16510 for known issues, and please file a new one if you find something new.
Unhandled rejection Error: EACCES: permission denied, mkdir '/Users/wao/.npm/_cacache/content-v2/sha1/4a'n 126ms

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/wao/.npm/_logs/2017-05-07T12_36_40_185Z-debug.log
```

https://gist.github.com/yangwao/066d1ce90743f8881857f8cc2209ec20

#### How can the CLI team reproduce the problem?

⫸  git clone https://github.com/ssbc/ssb-usage-stats.git
⫸  cd ssb-usage-stats/
⫸  npm5 i

### supporting information:

 - `npm -v` prints:
`5.0.0-beta.43`
 - `node -v` prints:
`v7.9.0`
 - `npm config get registry` prints:
`https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?:
`macOS`

**Comment by zkat** [comment]
Hey! Thanks for this report.

Could I ask you to `sudo rm -rf ~/.npm` and try this again? In the meantime, I'll see if I can hunt down why `cb() never called` would happen here. That's really weird 🤔

**Comment by zkat** [comment]
@yangwao the `cb() never called` bit should be fixed in the latest beta. I'll work some more tomorrow on tracking down the other issues. Thanks again :)

**Comment by NN---** [comment]
I have crash on npm5 outdated.
I don't have any npm files in the folder except npm5.
OS: Windows, Node: 7.10

**Comment by yangwao** [comment]
Interesting, that I don't have rights to delete contents of something in my home dir. That might be a problem I think.
```
⫸  rm -rf ~/.npm/
rm: /Users/wao/.npm//_cacache/content-v2/sha1/2b/be/7b8d8ceaa6e1a1adb0e6e1280821fb24a4a6: Permission denied
rm: /Users/wao/.npm//_cacache/content-v2/sha1/2b/be: Permission denied
rm: /Users/wao/.npm//_cacache/content-v2/sha1/2b: Permission denied
rm: /Users/wao/.npm//_cacache/content-v2/sha1: Directory not empty
rm: /Users/wao/.npm//_cacache/content-v2: Directory not empty
rm: /Users/wao/.npm//_cacache/index-v5/c9/fb/50dccabc358429c5d9876b0982c2a3182c68872d8c699d3a0d584d636ba8: Permission denied
rm: /Users/wao/.npm//_cacache/index-v5/c9/fb: Permission denied
rm: /Users/wao/.npm//_cacache/index-v5/c9: Directory not empty
rm: /Users/wao/.npm//_cacache/index-v5: Directory not empty
rm: /Users/wao/.npm//_cacache: Directory not empty
rm: /Users/wao/.npm/: Directory not empty
⫸  sudo rm -rf ~/.npm/
[i] ~
⫸
```
And looks like it worked and installed modules in project. 🎉 🌮

**Comment by zkat** [comment]
hooray!

I'm going to close this, since something weird happened with your permissions, but I was still concerned about that `cb() never called` thing. Seems resolved, so I'm closing this. :)
