### ISSUE TITLE
Error: cb() never called!

### ISSUE THREAD

**Issue by karamanolev** [npm/npm#16551]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

    npm ERR! cb() never called!
    
    npm ERR! This is an error with npm itself. Please report this error at:
    npm ERR!     <https://github.com/npm/npm/issues>
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     /Users/ivailo/.npm/_logs/2017-05-06T15_01_20_036Z-debug.log

#### How can the CLI team reproduce the problem?
Not sure what the repro is. I got the error, Googled a bit, found some tips, ran

    $ npm cache clean
    $ sudo npm cache clean
    $ rm -rf ~/.npm
    $ rm -rf node_modules
    $ npm install

Upgraded node, npm to latest versions and got the same thing. I also tried npm version 3.10.10. Here's a gist of the debug log: https://gist.github.com/karamanolev/db323c39deca4d73de995e508055c6cd
Here's a gist of my package.json: https://gist.github.com/karamanolev/77e3f23c7728bbb46ad7ff436905d766
Everything worked very well for a long time. Today I just had to do `npm install` due to some new versions in our package.json.

### supporting information:
npm -v
4.6.1

node -v
v7.10.0

npm config get registry
https://registry.npmjs.org/

OS: macOS
npm installed via nvm

   - Geographic location where npm was run: Bulgaria
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by nkovacs** [comment]
It's probably this: https://github.com/BenoitZugmeyer/eslint-plugin-html/issues/53

**Comment by karamanolev** [comment]
Seems like it was because of an invalid package published from eslint-plugin-html (invalid tar file?) but the error was super unhelpful. Not sure if this is still relevant for npm or not.

**Comment by BenoitZugmeyer** [comment]
The broken package was published with `yarn`, so the root issue is not related to npm. But the error message isn't very helpful indeed.

**Comment by diversario** [comment]
So, it's great that the issue is diagnosed but as far as npm users are concerned (myself, at least) this _is_ a problem with `npm` and it seems unreasonable to expect everyone who published a package with `yarn` to republish it. Is there no workaround currently for npm 5?

**Comment by michelmouallem** [comment]
Update npm to version 5.3.0 (npm -v)

Update steps: npm install npm@latest -g

**Comment by tobbtechnologies** [comment]
After upgrading npm i am facing same problem.

14 error cb() never called!
15 error This is an error with npm itself. Please report this error at:
16 error <https://github.com/npm/npm/issues>

Have this issue with

**Comment by obrazer** [comment]
I have got the same error when I try to upgrade npm - npm install npm@latest -g

**Comment by tobbtechnologies** [comment]
I got help from ionic framework team. I re-installed nodejs to latest LTS https://nodejs.org/en/

https://blog.ionicframework.com/

**Comment by padurets** [comment]
I had the same problem after run `npm i`
it helped me:

```
rm -rf node_modules
npm i "any package"
```

it is **important to specify the name of any package**, otherwise npm falls

**Comment by tusharvarshneyy** [comment]
I am having the same problem. 

Below are the details of the problem.
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'cordova' ]
2 info using npm@5.6.0
3 info using node@v9.11.1
4 verbose npm-session ec7183741d631bb7
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 error cb() never called!
8 error This is an error with npm itself. Please report this error at:
9 error <https://github.com/npm/npm/issues>

Please suggest the workaround.

**Comment by EricWiener** [comment]
I was getting this issue when I attempted to use `create-react-native-app`. I fixed it by reinstalling nodejs manually [from here](https://nodejs.org/en/download/) and then running
`npm install -g create-react-native-app`. `create-react-native-app` then worked. Hope this helps.

**Comment by phemmie** [comment]
I'm having same issue too on windows 10, tried all above suggestions, the problem persist
