### ISSUE TITLE
Unable to execute npm postinstall

### ISSUE THREAD

**Issue by Xisabla** [npm/npm#16552]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I tried several times to install some npm package's and at the moment of executing the postinstall, I have an error message, for example while trying to install nwjs in local:

![Screen](https://puu.sh/vHCfS/7569f9a10b.png)

Or as gist: https://gist.github.com/Xisabla/3364051c074302728bd40e9a7c428d6f

I tried updating npm (and succed), nothing changed, reinstalled nodejs that changed nothing. And as I was thinking that the problem came from the `node` command, I made a symbolic link between /usr/lib/nodejs and /usr/lib/node but again nothing changed.

Here is a gist of the log: https://gist.github.com/Xisabla/f9445d0dd20ed660faa69706ec9a930d

#### How can the CLI team reproduce the problem?

I got the issue while trying to install *gh-badges* and *nw* (but I think it would happend with every packages that have a postinstall script):
`npm i -g gh-badges` (in global, but here the problem seems to be due to phantomjs-prebuilt)
`npm i --save nw`(this one in a project)

### supporting information:

 - `npm -v` prints: v4.5.0
 - `node -v` prints: v7.10.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux 8 - Raspberry Raspian (jessie)
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

I hope you could help me and I hope it could be useful for the persons who have the same issue.
Anyway thanks in advance.

**Comment by wbhob** [comment]
This is a problem with `nw`'s postinstall script.

**Comment by wbhob** [comment]
Please post an issue on their repo.
