### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by kiasat** [npm/npm#16558]
Hi, 

Can anyone help me with these errors?!

C:\Users\Kiavash\node_modules\serialport>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" build --fallback-to-build --module=C:\Users\Kiavash\node_modules\serialport\build\Release\serialport.node --module_name=serialport --module_path=C:\Users\Kiavash\node_modules\serialport\build\Release )  else (node "" build --fallback-to-build --module=C:\Users\Kiavash\node_modules\serialport\build\Release\serialport.node --module_name=serialport --module_path=C:\Users\Kiavash\node_modules\serialport\build\Release )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.Targets(983,5): warning MSB3644: The reference assemblie
s for framework ".NETFramework,Version=v4.0" were not found. To resolve this, install the SDK or Targeting Pack for thi
s framework version or retarget your application to a version of the framework for which you have the SDK or Targeting
Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of
 reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [C:\Users\Ki
avash\node_modules\serialport\build\serialport.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppBuild.targets(297,5): warning MSB8003: Could not find Wi
ndowsSDKDir variable from the registry.  TargetFrameworkVersion or PlatformToolset may be set to an invalid version num
ber. [C:\Users\Kiavash\node_modules\serialport\build\serialport.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Platforms\x64\Microsoft.Cpp.x64.Targets(152,5): error MSB6006: "CL.ex
e" exited with code -1073741515. [C:\Users\Kiavash\node_modules\serialport\build\serialport.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\Kiavash\\node_modules\\serialport\\build\\Release\\serialport.node" "--module_name=serialport" "--module_path=C:\\Users\\Kiavash\\node_modules\\serialport\\build\\Release"
gyp ERR! cwd C:\Users\Kiavash\node_modules\serialport
gyp ERR! node -v v6.10.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd build --fallback-to-build --module=C:\Users\Kiavash\node_modules\serialport\build\Release\serialport.node --module_name=serialport --module_path=C:\Users\Kiavash\node_modules\serialport\build\Release' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Kiavash\node_modules\serialport\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:886:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Windows_NT 10.0.14393
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Kiavash\\node_modules\\serialport\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\Kiavash\node_modules\serialport
node-pre-gyp ERR! node -v v6.10.3
node-pre-gyp ERR! node-pre-gyp -v v0.6.26
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd build --fallback-to-build --module=C:\Users\Kiavash\node_modules\serialport\build\Release\serialport.node --module_name=serialport --module_path=C:\Users\Kiavash\node_modules\serialport\build\Release' (1)
C:\Users\Kiavash
+-- browser-serialport@2.0.3
+-- buffy@0.0.5
`-- cylon@1.3.0

npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Kiavash\package.json'
npm WARN Kiavash No description
npm WARN Kiavash No repository field.
npm WARN Kiavash No README data
npm WARN Kiavash No license field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "cylon" "cylon-neurosky"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! serialport@2.1.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the serialport@2.1.2 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the serialport package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs serialport
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls serialport
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Kiavash\npm-debug.log

**Comment by kiasat** [comment]
Hi again I changed the clyon-master to clyon and again ran the npm install clyon  and now I am getting below errors. 

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "clyon"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/clyon
npm ERR! 404
npm ERR! 404  'clyon' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\cylon\npm-debug.log

**Comment by zkat** [comment]
You misspelled `cylon`.

Copy-paste this:

`npm install -S cylon`.

Cheers.
