### ISSUE TITLE
npm install ERR!

### ISSUE THREAD

**Issue by sbsaqi** [npm/npm#16557]
```
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\program files\\node.exe" "C:\\program files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "express""--save"
npm ERR! node v6.10.3
npm ERR! npm v3.10.10

npm ERR! 9 == 0
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR! <http://github.com/npm/npm/issues>
```

Can any body help me

**Comment by sbsaqi** [comment]
This is npm-debug-------

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@3.10.10
3 info using node@v6.10.3
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly install normalizeTree
8 silly loadCurrentTree Finishing
9 silly loadIdealTree Starting
10 silly install loadIdealTree
11 silly cloneCurrentTree Starting
12 silly install cloneCurrentTreeToIdealTree
13 silly cloneCurrentTree Finishing
14 silly loadShrinkwrap Starting
15 silly install loadShrinkwrap
16 silly loadShrinkwrap Finishing
17 silly loadAllDepsIntoIdealTree Starting
18 silly install loadAllDepsIntoIdealTree
19 silly fetchNamedPackageData express
20 silly mapToRegistry name express
21 silly mapToRegistry using default registry
22 silly mapToRegistry registry https://registry.npmjs.org/
23 silly mapToRegistry data Result {
23 silly mapToRegistry   raw: 'express',
23 silly mapToRegistry   scope: null,
23 silly mapToRegistry   escapedName: 'express',
23 silly mapToRegistry   name: 'express',
23 silly mapToRegistry   rawSpec: '',
23 silly mapToRegistry   spec: 'latest',
23 silly mapToRegistry   type: 'tag' }
24 silly mapToRegistry uri https://registry.npmjs.org/express
25 silly fetchNamedPackageData body-parser
26 silly mapToRegistry name body-parser
27 silly mapToRegistry using default registry
28 silly mapToRegistry registry https://registry.npmjs.org/
29 silly mapToRegistry data Result {
29 silly mapToRegistry   raw: 'body-parser',
29 silly mapToRegistry   scope: null,
29 silly mapToRegistry   escapedName: 'body-parser',
29 silly mapToRegistry   name: 'body-parser',
29 silly mapToRegistry   rawSpec: '',
29 silly mapToRegistry   spec: 'latest',
29 silly mapToRegistry   type: 'tag' }
30 silly mapToRegistry uri https://registry.npmjs.org/body-parser
31 verbose request uri https://registry.npmjs.org/express
32 verbose request no auth needed
33 info attempt registry request try #1 at 12:05:51 PM
34 verbose request id 631b8146462285a0
35 http request GET https://registry.npmjs.org/express
36 verbose request uri https://registry.npmjs.org/body-parser
37 verbose request no auth needed
38 info attempt registry request try #1 at 12:05:51 PM
39 http request GET https://registry.npmjs.org/body-parser
40 verbose stack AssertionError: 9 == 0
40 verbose stack     at ClientRequest.onConnect (C:\Program Files\nodejs\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:159:14)
40 verbose stack     at ClientRequest.g (events.js:292:16)
40 verbose stack     at emitThree (events.js:116:13)
40 verbose stack     at ClientRequest.emit (events.js:194:7)
40 verbose stack     at Socket.socketOnData (_http_client.js:394:11)
40 verbose stack     at emitOne (events.js:96:13)
40 verbose stack     at Socket.emit (events.js:188:7)
40 verbose stack     at readableAddChunk (_stream_readable.js:176:18)
40 verbose stack     at Socket.Readable.push (_stream_readable.js:134:10)
40 verbose stack     at TCP.onread (net.js:547:20)
41 verbose cwd C:\Users\Bruger\Documents\STUDIES n Education\The Full Stack web developer (course)\Section 8 Backend Programming with Node.js\Development\3- Express Install n Routing\myexpress
42 error Windows_NT 10.0.14393
43 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
44 error node v6.10.3
45 error npm  v3.10.10
46 error 9 == 0
47 error If you need help, you may report this error at:
47 error     <https://github.com/npm/npm/issues>
48 verbose exit [ 1, true ]

**Comment by sbsaqi** [comment]
**I am staill waiting for any kind of help** ......
npm info it worked if it ends with ok
npm info using npm@4.2.0
npm info using node@v7.10.0
npm info ok
npm info it worked if it ends with ok
npm info using npm@4.2.0
npm info using node@v7.10.0
npm info ok

C:\Users\Bruger\Documents\STUDIES n Education\The Full Stack web developer (course)\Section 8 Backend Programming with Node.js\Development\3- Express Install n Routing\myexpress>npm install
npm info it worked if it ends with ok
npm info using npm@4.2.0
npm info using node@v7.10.0
npm info ok
npm info it worked if it ends with ok
npm info using npm@4.2.0
npm info using node@v7.10.0
npm info attempt registry request try #1 at 1:27:47 PM
npm http request GET https://registry.npmjs.org/express
npm info attempt registry request try #1 at 1:27:47 PM
npm http request GET https://registry.npmjs.org/body-parser
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0

npm ERR! 9 == 0
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0

**Comment by sbsaqi** [comment]
**package.json**
{
  "name": "myexpress",
  "version": "1.0.0",
  "description": "Simple express application",
  "main": "app.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "sbsaqi",
  "license": "ISC",
  "dependencies":{
    "express":"*",
    "body-parser":"*"
  }
}

**Comment by sbsaqi** [comment]
It is solved ... by doing following .... by help of (juaniliska commented on 26 Dec 2016)
npm config get registry
npm cache clean
npm install

**Comment by legodude17** [comment]
Try updating `npm`. This might be a problem with older versions of request

**Comment by sbsaqi** [comment]
C:\Program Files\nodejs>npm install npm@latest
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "npm@latest"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10

npm ERR! 9 == 0
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
-----------------------
same error

**Comment by legodude17** [comment]
That is not `npm@latest`.

**Comment by sbsaqi** [comment]
I have uninstall node.js ... delete all files n folders (*) manually from program files\ (nodejs) & user\ [username]\appdata\roaming(npm) and delete all npm log file where they were ..... Restart the computer ... 

Now again install latest node.js ... go to c:\program files\nodejs\ (run ..... 'npm updat' through cmd as administrator) ... Thank God! ... its working ... (thanks legodude17)

**Comment by ManukumarNM** [comment]
yep...If you update the npm@latest version. This problem will solve.
