### ISSUE TITLE
npm running issue in ubuntu 16.04

### ISSUE THREAD

**Issue by babind** [npm/npm#16568]
0 info it worked if it ends with ok
1 verbose cli [ '/home/babin/.nvm/versions/node/v6.9.4/bin/node',
1 verbose cli   '/home/babin/.nvm/versions/node/v6.9.4/bin/npm',
1 verbose cli   'start' ]
2 info using npm@3.10.10
3 info using node@v6.9.4
4 verbose stack Error: missing script: start
4 verbose stack     at run (/home/babin/.nvm/versions/node/v6.9.4/lib/node_modules/npm/lib/run-script.js:151:19)
4 verbose stack     at /home/babin/.nvm/versions/node/v6.9.4/lib/node_modules/npm/lib/run-script.js:61:5
4 verbose stack     at /home/babin/.nvm/versions/node/v6.9.4/lib/node_modules/npm/node_modules/read-package-json/read-json.js:356:5
4 verbose stack     at checkBinReferences_ (/home/babin/.nvm/versions/node/v6.9.4/lib/node_modules/npm/node_modules/read-package-json/read-json.js:320:45)
4 verbose stack     at final (/home/babin/.nvm/versions/node/v6.9.4/lib/node_modules/npm/node_modules/read-package-json/read-json.js:354:3)
4 verbose stack     at then (/home/babin/.nvm/versions/node/v6.9.4/lib/node_modules/npm/node_modules/read-package-json/read-json.js:124:5)
4 verbose stack     at /home/babin/.nvm/versions/node/v6.9.4/lib/node_modules/npm/node_modules/read-package-json/read-json.js:311:12
4 verbose stack     at /home/babin/.nvm/versions/node/v6.9.4/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
4 verbose stack     at tryToString (fs.js:455:3)
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
5 verbose cwd /home/babin/newproject/Bankrolla
6 error Linux 4.4.0-75-generic
7 error argv "/home/babin/.nvm/versions/node/v6.9.4/bin/node" "/home/babin/.nvm/versions/node/v6.9.4/bin/npm" "start"
8 error node v6.9.4
9 error npm  v3.10.10
10 error missing script: start
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
Hello! So, the way `npm start` works is that it looks in your current `package.json` for a defined `"start"` [script](https://docs.npmjs.com/misc/scripts), and then runs that. The error message you're seeing is trying to tell you that you have not defined a `"start"` script in your `package.json`, hence `npm start` has no idea what you want it to do.

To solve this issue, all you have to do is add a new script to your `package.json`. It might look something like this, for example:

``` json
{
  "name": "package-name",
  "version": "1.0.0",
  "description": "package description",
  "scripts": {
    "start": "node --version",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {},
  "devDependencies": {}
}
```

Note how this `package.json` has a `"start"` script that runs `node --version`. You'll definitely want to change the command to whatever is most appropriate for your project.

Let me know if you run into any further `npm` issues :)

**Comment by babind** [comment]
Error after i type npm run dev 
node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
events.js:160
      throw er; // Unhandled 'error' event

**Comment by KenanY** [comment]
Could you upload the full log file to <https://gist.github.com/> and link it here? Posting just a few lines provides little context as to what is happening here.
