### ISSUE TITLE
npm install is throwing lot of errors regarding product-management

### ISSUE THREAD

**Issue by saisaraswathi** [npm/npm#16576]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by saisaraswathi** [comment]
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Users\sai.katiki>npm install
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\sai.katiki\pac
kage.json'
npm WARN sai.katiki No description
npm WARN sai.katiki No repository field.
npm WARN sai.katiki No README data
npm WARN sai.katiki No license field.

C:\Users\sai.katiki>d:

D:\>cd APM

D:\APM>npm install

> product-management@1.0.0 postinstall D:\APM
> typings install

typings ERR! message Unable to connect to "https://api.typings.org/entries/dt/co
re-js/tags/0.0.0%2B20160725163759"
typings ERR! caused by getaddrinfo EAI_AGAIN api.typings.org:443
typings ERR!
typings ERR! cwd D:\APM
typings ERR! system Windows_NT 6.3.9600
typings ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\APM\\node_module
s\\typings\\dist\\bin.js" "install"
typings ERR! node -v v6.10.3
typings ERR! typings -v 1.5.0
typings ERR! code EUNAVAILABLE
typings ERR!
typings ERR! If you need help, you may report this error at:
typings ERR!   <https://github.com/typings/typings/issues>
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\ch
okidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! product-management@1.0.0 postinstall: `typings install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the product-management@1.0.0 postinstall script 'typings inst
all'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the product-management pa
ckage,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     typings install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs product-management
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls product-management
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sai.katiki\AppData\Roaming\npm-cache\_logs\2017-05-09T12_1
3_54_335Z-debug.log

D:\APM>

**Comment by KenanY** [comment]
This error does not appear to be coming from `npm` itself. From the log:

```
typings ERR! message Unable to connect to "https://api.typings.org/entries/dt/core-js/tags/0.0.0%2B20160725163759"
typings ERR! caused by getaddrinfo EAI_AGAIN api.typings.org:443
```

It seems like `typings install` failed to connect to `api.typings.org`, so it returned a non-zero exit code. All `npm` is doing here is catching the code and letting you know about it.

**Comment by saisaraswathi** [comment]
Can u tell me how to eradicate error?

**Comment by legodude17** [comment]
Run `npm bugs typings`.
