### ISSUE TITLE
npm ERR!     C:\Users\lmgnua1\AppData\Roaming\npm-cache\_logs\2017-05-09T14_55_56_330Z-debug.log

### ISSUE THREAD

**Issue by papaasem** [npm/npm#16578]
#### I'm opening this issue because:

  - [ ] npm is crashing.

#### What's going wrong?
npm ERR!     C:\Users\lmgnua1\AppData\Roaming\npm-cache\_logs\2017-05-09T14_55_56_330Z-debug.log

#### How can the CLI team reproduce the problem?
not sure

### supporting information:

 :
 - Windows, OS X/macOS, or Linux?:
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@papaasem Could you upload the log file to <https://gist.github.com/> and post the link here?
