### ISSUE TITLE
 Unsupported URL Type when updating a dependency

### ISSUE THREAD

**Issue by yosserO** [npm/npm#16575]
#### I'm opening this issue because:

I'm not able to update a dependency

#### What's going wrong?

When running npm update, I get this error:  Unsupported URL Type: ssh://git@url of git repository

#### How can the CLI team reproduce the problem?

- I installed the dependency by running: npm install  git+ssh://git@url of git repository -S
- The dependency has been installed and added to the package.json file without any errors 
- Under dependencies in the package.json file I can see this line:

"name of dependency": git+ssh://git@url of git repository

- When running npm update, I'm getting this error:

npm ERR! Unsupported URL Type: ssh://git@url of git repository

- I can see this in the log file

```
verbose stack Error: Unsupported URL Type: ssh://git@url of git repository
4 verbose stack     at parseUrl (.....\AppData\Roaming\npm\node_modules\npm\node_modules\npm-package-arg\npa.js:186:13)
4 verbose stack     at npa (.....\AppData\Roaming\npm\node_modules\npm\node_modules\npm-package-arg\npa.js:79:12)
4 verbose stack     at shouldUpdate (....\AppData\Roaming\npm\node_modules\npm\lib\outdated.js:330:16)
4 verbose stack     at  ......\AppData\Roaming\npm\node_modules\npm\lib\outdated.js:297:23
4 verbose stack     at  ......\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
4 verbose stack     at Array.forEach (native)
4 verbose stack     at  ......\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
4 verbose stack     at Array.forEach (native)
4 verbose stack     at asyncMap  ......\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
4 verbose stack     at outdated_  .......\Roaming\npm\node_modules\npm\lib\outdated.js:290:3)
4 verbose stack     at  .....\Roaming\npm\node_modules\npm\lib\outdated.js:82:5
4 verbose stack     at   ......\Roaming\npm\node_modules\npm\lib\install\deps.js:175:5
4 verbose stack     at LOOP  .....\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:7:26)
4 verbose stack     at   .....\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:18:7
4 verbose stack     at cb  ......\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:47:24)
4 verbose stack     at  .......\Roaming\npm\node_modules\npm\lib\install\deps.js:175:5
```

-  I  looked in the package.json file of the dependency and found this out: 

in the _requested  object, the spec is specified without git+ssh at the beginning. Changing this line resolved the issue. 

old value: ssh://git@url of git repository
manually changed value: git+ssh://git@url of git repository

How can I get npm to run npm update without errors and without having to change this line manually ???

### supporting information:

 - `npm -v` prints:  4.5.0

### Thanks for your help

**Comment by drostie** [comment]
This appears to be a bug in the package you're depending on; you should contact the package maintainer and raise an issue with them to change this dependency to one of the supported [git URLs as dependencies](https://docs.npmjs.com/files/package.json#git-urls-as-dependencies) specifications.

**Comment by drostie** [comment]
You can also of course fork the dependency with your own changes, and possibly publish it to NPM as a [scoped package](https://docs.npmjs.com/getting-started/scoped-packages) if they cannot be reached.
