### ISSUE TITLE
ember new helloworld failed

### ISSUE THREAD

**Issue by konbluesky** [npm/npm#16584]
```
mylocalhost:nodejs root$ ember new helloworld
installing app
  create .editorconfig
  create .ember-cli
  create .eslintrc.js
  create .travis.yml
  create .watchmanconfig
  create README.md
  create app/app.js
  create app/components/.gitkeep
  create app/controllers/.gitkeep
  create app/helpers/.gitkeep
  create app/index.html
  create app/models/.gitkeep
  create app/resolver.js
  create app/router.js
  create app/routes/.gitkeep
  create app/styles/app.css
  create app/templates/application.hbs
  create app/templates/components/.gitkeep
  create config/environment.js
  create config/targets.js
  create ember-cli-build.js
  create .gitignore
  create package.json
  create public/crossdomain.xml
  create public/robots.txt
  create testem.js
  create tests/.eslintrc.js
  create tests/helpers/destroy-app.js
  create tests/helpers/module-for-acceptance.js
  create tests/helpers/resolver.js
  create tests/helpers/start-app.js
  create tests/index.html
  create tests/integration/.gitkeep
  create tests/test-helper.js
  create tests/unit/.gitkeep
  create vendor/.gitkeep
Error creating new application. Removing generated directory `./helloworld`
Command failed: npm install --no-optional --loglevel error
npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--no-optional" "--loglevel error"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10

npm ERR! Invalid name: "@glimmer/resolver"
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/xxxx/work/nodejs/helloworld/npm-debug.log

Error: Command failed: npm install --no-optional --loglevel error
npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--no-optional" "--loglevel error"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10

npm ERR! Invalid name: "@glimmer/resolver"
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/xxxxx/work/nodejs/helloworld/npm-debug.log

    at Promise.all.then.arr (/usr/local/lib/node_modules/ember-cli/node_modules/_execa@0.6.3@execa/index.js:210:11)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by konbluesky** [comment]
when i reinstall npm.

it's ok!
`
$sudo npm install -g npm
$ember new helloworld
installing app
  create .editorconfig
  create .ember-cli
  create .eslintrc.js
  create .travis.yml
  create .watchmanconfig
  create README.md
  create app/app.js
  create app/components/.gitkeep
  create app/controllers/.gitkeep
  create app/helpers/.gitkeep
  create app/index.html
  create app/models/.gitkeep
  create app/resolver.js
  create app/router.js
  create app/routes/.gitkeep
  create app/styles/app.css
  create app/templates/application.hbs
  create app/templates/components/.gitkeep
  create config/environment.js
  create config/targets.js
  create ember-cli-build.js
  create .gitignore
  create package.json
  create public/crossdomain.xml
  create public/robots.txt
  create testem.js
  create tests/.eslintrc.js
  create tests/helpers/destroy-app.js
  create tests/helpers/module-for-acceptance.js
  create tests/helpers/resolver.js
  create tests/helpers/start-app.js
  create tests/index.html
  create tests/integration/.gitkeep
  create tests/test-helper.js
  create tests/unit/.gitkeep
  create vendor/.gitkeep
NPM: Installed dependencies
Successfully initialized git.
`

**Comment by kettro** [comment]
Ubuntu 16.04, brand new system image (Digital Ocean). I get the same errors. Using nvm, updated to the lastest node, npm. Reinstalled npm via npm. Still getting the error.

Error: Command failed: npm install --no-optional --loglevel error


> spawn-sync@1.0.15 postinstall /home/kettro/code/node/ember/ember-quickstart/node_modules/spawn-sync
> node postinstall


    at Promise.all.then.arr (/home/kettro/.nvm/versions/node/v7.10.0/lib/node_modules/ember-cli/node_modules/execa/index.js:210:11)
    at process._tickCallback (internal/process/next_tick.js:109:7)
