### ISSUE TITLE
 tunneling socket could not be established, cause=getaddrinfo ENOTFOUND http http:443

### ISSUE THREAD

**Issue by amirkhan064** [npm/npm#16588]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):
when i trying to install anything via npm i always get this error tunneling socket could not be established, cause=getaddrinfo ENOTFOUND http http:443, my proxy is already set but still getting the same issue anyone please help me to resolve this issue.

![image](https://cloud.githubusercontent.com/assets/20635981/25901811/7fb43cf2-35b5-11e7-91ec-ca17873208c8.png)

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
Please update to the latest `npm`.

**Comment by zkat** [comment]
You configured your proxy wrong. For some reason, it's seeing `https://khan.am:<password>@http//noida-sez-v10k:8000`, which is a very suspicious-looking URI. That said, this isn't an issue with npm itself: it's with the phantomjs installer, which does its own thing. Please open an issue with them, instead. I'll be closing this one. Good luck!
