### ISSUE TITLE
npm install on mounted partition fails

### ISSUE THREAD

**Issue by himanshuphirke** [npm/npm#16586]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### How can the CLI team reproduce the problem?

Inside a Virtual machine have mounted partition of host system.
e.g ~/host points to a shared folder from host

Have a node project on the mounted partition:
Sample project:
https://university.mongodb.com/static/MongoDB_2017_M101JS_March/handouts/hw1-1_568d3a05d8ca390830d6eb6a.23640825621c.zip

Below is error seen during `npm install`

```
npm ERR! Linux 4.4.0-66-generic
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v6.10.1/bin/node" "/home/ubuntu/.nvm/versions/node/v6.10.1/bin/npm" "install"
npm ERR! node v6.10.1
npm ERR! npm v3.10.10
npm ERR! path ../mime/cli.js
npm ERR! code EROFS
npm ERR! errno -30
npm ERR! syscall symlink

npm ERR! rofs EROFS: read-only file system, symlink '../mime/cli.js' -> '/home/ubuntu/host/dev/mongo/hw1-3/node_modules/.bin/mime'
npm ERR! rofs This is most likely not a problem with npm itself
npm ERR! rofs and is related to the file system being read-only.
npm ERR! rofs
npm ERR! rofs Often virtualized file systems, or other file systems
npm ERR! rofs that don't support symlinks, give this error.

npm ERR! Please include the following file with any support request:
npm ERR! /home/ubuntu/host/dev/mongo/hw1-3/npm-debug.log
```

**Comment by KenanY** [comment]
Can you try using the `--no-bin-links` flag?

**Comment by himanshuphirke** [comment]
It works in if I am doing npm install
I am also using [Meteor](https://www.meteor.com/) in Virtual box and do no prefer to customize how it installs and passing above flag

**Comment by KenanY** [comment]
So, are you saying that the flag solves your issue? Sorry if I am misunderstanding.

**Comment by himanshuphirke** [comment]
Flag solves problem for node projects.

It does not for work for Meteor

**Comment by KenanY** [comment]
If your system does not support symlinks, then the flag I provided is the way to go if `npm` is throwing errors like that. Meteor might have it's own way of disabling symlinks.

**Comment by himanshuphirke** [comment]
@KenanY Disabling symlinks is an alternative.
The issue was logged to identify and fix npm to correct the root cause.

Let me know if you can help me with pointers to fix it. I would be more than happy to fix it per guidelines.

**Comment by KenanY** [comment]
Nah, disabling `npm`'s symlinks if your system does not support them is the primary solution, not an alternative one.
