### ISSUE TITLE
node-gyp Unresolved External Symbol Error

### ISSUE THREAD

**Issue by Pecacheu** [npm/npm#16583]
I'm trying to make a native module that uses DirectX for some of it's functionality, but I get this error when I try to `node-gyp build`:
```
main.obj : error LNK2001: unresolved external symbol Direct3DCreate9
```
I'm including d3d9.h in my c++ file. Is there something I'm doing wrong?

**Comment by KenanY** [comment]
Sounds like this belongs [here](https://github.com/nodejs/node-gyp/issues) instead.
