### ISSUE TITLE
Error executing nmp on win 8.1 64bit

### ISSUE THREAD

**Issue by gcardonat63** [npm/npm#16582]
#### I'm opening this issue because:

  - [ ] npm is doing something I don't understand.

I am using Windows 8.1 64-bit and install npm with Windows Installer from nodejs.org. I have a trouble, every time i enter npm command, it always showing this message:
'CALL "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" prefix -g' is not recognized as an internal or external command, operable program or batch file.

node -v

    v6.10.0
npm -v

    'CALL "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" prefix -g' is not recognized as an internal or external command,
    operable program or batch file.
    3.10.10

when i try to npm install -g polymer-cli or angular or any other package at the end
npm starts to show error messages and the package doesnt install

comspec variable is ok
i installed with admin privileges

guido

**Comment by legodude17** [comment]
Try removing `npm` completely and reinstalling from the nodejs website.

**Comment by gcardonat63** [comment]
I have removed in all ways completelly, and manually removing folders after unistallation on
Pogramfiles\nodejs,
C:\Users\GUIDOFERNANDO\AppData\Roaming\npm
and npm-cache

reinstalling node from offcial site, and as administrator user

But after all the error persist

moreover when i try to install a package as for example

angular
or polymer

npm finishes with a lot or errors in red indicating it cannot complete the install

My machine is windows 8.1  64bit

I installed on a virtual machine with win 7 sp1 32 bit and everithing its ok

I checked the comspec variable  is pointing only to one location c:\window\sytem32

I really think is some kind of error with windows 8.1 64 bits

I prettiate your support

Thanks in advance

Guido Cardona
