### ISSUE TITLE
error during installation of angular/cli  on Windows 8.1 Enterprise

### ISSUE THREAD

**Issue by perryk-kcom** [npm/npm#16589]
I'm opening this issue because:

  -  npm is producing an incorrect install.
  
What's going wrong?
I am getting errors:
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli@latest"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10

npm ERR! Callback called more than once.
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\kperry\npm-debug.log

### supporting information:
Please see supplied npm-debug.log
[npm-debug.zip](https://github.com/npm/npm/files/991258/npm-debug.zip)

**Comment by legodude17** [comment]
Please try updating `npm` to the latest version.
