### ISSUE TITLE
Fatal: unable to access 'https://github.com/mcavage/node-asn1.git/':could not resolve host: github.com

### ISSUE THREAD

**Issue by puneetsharma86** [npm/npm#16595]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_): I am running the below command in the docker.
npm install /opt/gopath/src/github.com/hyperledger/fabric/sdk/node. Please find the error description in the attached image.

#### What's going wrong?
Fatal: unable to access 'https://github.com/mcavage/node-asn1.git/':could not resolve host: github.com

#### How can the CLI team reproduce the problem?

In docker the first command i ran is "docker exec -it starter /bin/bash"
then --> node app
-->under folder /user/mytest : npm install /opt/gopath/src/github.com/hyperledger/fabric/sdk/node

### supporting information:

 - `npm -v` prints:2.11.3
 - `node -v` prints: 0.12.7
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?:Windows 7
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop / deploy using Docker.

**Comment by puneetsharma86** [comment]
Please let me know how can i resolve this issue. Its a part of Marble app installation.

**Comment by legodude17** [comment]
Please check your network and update `npm`.

**Comment by HEAgEKBATEH** [comment]
$ curl https://raw.githubusercontent.com/creationix/nvm/v0.16.1/install.sh | sh  ошибка с сертификатом
$ sudo add-apt-repository ppa:bitcoin/bitcoin  н еверное имя PPA
$ git clone https://github.com/UNOMP/unified-node-open-mining-portal.git unomp      Fatal: unable to access  clone https://github.com/UNOMP/unified-node-open-mining-portal.git unomp   not resolve host: github.com     
 Кто знает как всё это исправить? ОС 14.04.3 LTS  все обновления выполнены-уже замучался-ничего не скачивает...
