### ISSUE TITLE
npm-scripts that start with `pre` or `post` can run, but cannot run their pre/post commands

### ISSUE THREAD

**Issue by hail2u** [npm/npm#16593]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

If I created npm-script named `preview`, `npm run preview` works fine. However, `prepreview` or `postpreview` script does not run with this command. The same occurred on `present`, `poster`, or a word that starts with `pre` or `post`.

#### How can the CLI team reproduce the problem?

In `package.json`:

```json
{
  "scripts": {
    "prepreview": "echo pre script for preview",
    "preview": "echo preview",
    "postpreview": "echo post script for preview"
  }
}
```

and then

    $ npm run preview

Result:

```
> @ preview ~/Desktop/test
> echo preview

preview
```

Expected result:

```
> @ prepreview ~/Desktop/test
> echo pre script for preview

pre script for preview

> @ preview ~/Desktop/test
> echo preview

preview

> @ postpreview ~/Desktop/test
> echo post script for preview

post script for preview
```

### supporting information:

 - `npm -v` prints: 4.2.0
 - `node -v` prints: v7.10.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows 10 (Version 1607)
 - Network issues: N/A
 - Container: N/A

**Comment by dimitarrusev** [comment]
I can confirm this happening on OS X as well.

### supporting information:

* `npm -v` prints: 5.3.0
* `node -v` prints: v8.2.1
* `npm config get registry` prints: https://registry.npmjs.org/
* Windows, OS X/macOS, or Linux?: OS X El Capitan (Version 10.11.6)
* Network issues: N/A
* Container: N/A
