### ISSUE TITLE
'npm show <package> versions' output is useless if package has many versions

### ISSUE THREAD

**Issue by andytompkins** [npm/npm#16590]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [X] Other (_see below for feature requests_):

#### What's going wrong?
If I run `npm show ember-cli versions` (for example), the output starts with the earliest version and the end of the list ends up being truncated like:
<img width="145" alt="screen shot 2017-05-10 at 3 37 20 pm" src="https://cloud.githubusercontent.com/assets/1323322/25924247/9d53582a-3596-11e7-8405-eb0bd63ef3b3.png">
which makes it difficult to determine what the latest versions are.
It would make more sense if the list was sorted in the other direction, or if it was at least user selectable. (I know there are workarounds like json output or the glob trick, but this should be easy to use without having to know those.)

#### How can the CLI team reproduce the problem?
Run `npm show ember-cli versions`.

### supporting information:

 - `npm -v` prints: 3.10.10
 - `node -v` prints: v6.10.2
 - `npm config get registry` prints: (we do have an internal npm enterprise registry but this works the same with the public registry)
 - Windows, OS X/macOS, or Linux?: OS X/macOS
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by watilde** [comment]
Correct me if I'm wrong, I think we should expand it with `--long` option since there is no way to do that currently.
