### ISSUE TITLE
Vuejs run server not work

### ISSUE THREAD

**Issue by amineous** [npm/npm#16598]
Hi everyone , 
i install vue-cli , but when i want to run a server , he show me this error in terminal , can someone help me . 

/*******************************************/
PS C:\Users\Amine ousaid\Desktop\Vuejs App\Vue-test> npm run dev.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev."
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10

npm ERR! missing script: dev.
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Amine ousaid\Desktop\Vuejs App\Vue-test\npm-debug.log

**Comment by ericmdantas** [comment]
Hello, @amineous.

You don't have a script `dev` in you `package.json`.

It should look like:

```json
{
  "name": "myproject",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "dev": "node index.js" 
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}
```

**Comment by amineous** [comment]
Hey @ericmdantas 
Look what i have in package.json. 
{
  "name": "app_test",
  "description": "test",
  "version": "1.0.0",
  "author": "amine",
  "private": true,
  "scripts": {
    "dev": "cross-env NODE_ENV=development webpack-dev-server --open --hot",
    "build": "cross-env NODE_ENV=production webpack --progress --hide-modules"
  },
  "dependencies": {
    "vue": "^2.2.1"
  },
  "devDependencies": {
    "babel-core": "^6.0.0",
    "babel-loader": "^6.0.0",
    "babel-preset-latest": "^6.0.0",
    "cross-env": "^3.0.0",
    "css-loader": "^0.25.0",
    "file-loader": "^0.9.0",
    "vue-loader": "^11.1.4",
    "vue-template-compiler": "^2.2.1",
    "webpack": "^2.2.0",
    "webpack-dev-server": "^2.2.0"
  }
}

**Comment by ericmdantas** [comment]
Did you type `dev.` or `dev`? 

Notice there's no dot, so it should be `npm run dev`

**Comment by amineous** [comment]
Nn i type dev without .

2017-05-11 15:47 GMT+01:00 Eric M. Dantas <notifications@github.com>:

**Comment by KenanY** [comment]
The log indicates that you used `npm run dev.`, with a dot. If you're seeing the same issue when you run
`npm run dev`, can we see the debug log for that too then?
