### ISSUE TITLE
on nexus npm private server  run npm publish Issues 400

### ISSUE THREAD

**Issue by whydoUusejava** [npm/npm#16594]
I  have config NPM server on nexus and want to publish project ,like below:

```
D:\lirongjian\temp\temp\temp>npm publish --registry=http://192.168.2.115:8081/re
pository/npm-all/
npm ERR! publish Failed PUT 400
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "publish" "--registry=http://192.168.2.115:8
081/repository/npm-all/"
npm ERR! node v6.2.2
npm ERR! npm  v1.0.0
npm ERR! code E400

npm ERR! 400 Bad Request
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\lirongjian\temp\temp\temp\npm-debug.log
```

what is wrong of "npm ERR! 400 Bad Request" ,pls help.

**Comment by legodude17** [comment]
Your `npm` version is _years_ old. Please update.

**Comment by KenanY** [comment]
Whoops, I missed that. I don't know how you ended up with such an old `npm` version despite having a new-ish Node.js version. I'll close this since we don't support that `npm` version anymore, but if you still have this issue with the latest stable release, then I can reopen. Good luck!

**Comment by whydoUusejava** [comment]
I am sorry,I have update NPM version ,but also disable to publish,like below:

D:\lirongjian\eclipseWorkspace\Node_express>npm publish --registry=http://192.16
8.2.115:8081/repository/npm-all/
npm ERR! publish Failed PUT 400
npm ERR! code E400
npm ERR! 400 Bad Request

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lirongjian\AppData\Roaming\npm-cache\_logs\2017-05-12T02_4
5_30_920Z-debug.log

my npm version is :
D:\lirongjian\eclipseWorkspace\Node_express>npm -v
4.5.0

**Comment by whydoUusejava** [comment]
my god!!  I try to publish many times ,it show  "need auth" ,Is the nexus support npm private server ?

  
D:\lirongjian\eclipseWorkspace\Node_express>npm publish --registry=http://192.16
8.2.115:8081/repository/npm-private/
npm ERR! code ENEEDAUTH
npm ERR! need auth auth required for publishing
npm ERR! need auth You need to authorize this machine using `npm adduser`

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lirongjian\AppData\Roaming\npm-cache\_logs\2017-05-12T08_2
7_26_232Z-debug.log

**Comment by whydoUusejava** [comment]
I have publish project successfully!!!  THKS!!It must auth the private path in home .npmrc file.


D:\lirongjian\eclipseWorkspace\Node_express>npm login --registry=http://192.168.
2.115:8081/repository/npm-private/
Username: (admin/admin123) admin
Password:
Email: (this IS public) (nowtimeismoney@qq.com) nowtimeismoney@qq.com
Logged in as admin on http://192.168.2.115:8081/repository/npm-private/.

D:\lirongjian\eclipseWorkspace\Node_express>
D:\lirongjian\eclipseWorkspace\Node_express>
D:\lirongjian\eclipseWorkspace\Node_express>
D:\lirongjian\eclipseWorkspace\Node_express>npm publish --registry=http://192.16
8.2.115:8081/repository/npm-private/
+ Node_express@0.0.1

D:\lirongjian\eclipseWorkspace\Node_express>

**Comment by whydoUusejava** [comment]
oh,year. I have publish the project successfully.It must auth private path in home .npmrc file. like below:

.npmrc file 
registry=http://192.168.2.115:8081/repository/npm-group/
_auth="YWRtaW4vYWRtaW4xMjM="
//192.168.2.115:8081/repository/npm-group/:_authToken=26acedb4-a345-3eb5-b3a0-93c1ccd2c173
//192.168.2.115:8081/repository/npm-private/:_authToken=26acedb4-a345-3eb5-b3a0-93c1ccd2c173


like below:
D:\lirongjian\eclipseWorkspace\Node_express>npm login --registry=http://192.168.
2.115:8081/repository/npm-private/
Username: (admin/admin123) admin
Password:
Logged in as admin on http://192.168.2.115:8081/repository/npm-private/.

D:\lirongjian\eclipseWorkspace\Node_express>
D:\lirongjian\eclipseWorkspace\Node_express>
D:\lirongjian\eclipseWorkspace\Node_express>
D:\lirongjian\eclipseWorkspace\Node_express>npm publish --registry=http://192.16
8.2.115:8081/repository/npm-private/
+ Node_express@0.0.1

D:\lirongjian\eclipseWorkspace\Node_express>

**Comment by onvno** [comment]
Meet this problem, but the solution only need add `email=you@example.com` before `_auth` in `.npmrc`

**Comment by rayman-v** [comment]
How can I check out the '_auth' value in my Nexus? @whydoUusejava

**Comment by EightArmCode** [comment]
is that your auth token in the latest message @whydoUusejava?
