### ISSUE TITLE
npm5 is attempting to use a private registry incorrectly.

### ISSUE THREAD

**Issue by bellmounte** [npm/npm#16600]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
npm is attempting to check a private registry when installing. 

Output:
```
$ npm i --save-dev babel-eslint@6
npm notice BETA npm5 is beta software. Please see https://github.com/npm/npm/issues/16510 for known issues, and please file a new one if you find something new.
Unhandled rejection TypeError: Invalid Version: http://private.com/repository/private/babel-traverse/-/babel-traverse-6.24.1.tgz
    at new SemVer (/usr/local/lib/node_modules/npm5/node_modules/semver/semver.js:293:11)
    at Range.test (/usr/local/lib/node_modules/npm5/node_modules/semver/semver.js:1036:15)
    at Function.satisfies (/usr/local/lib/node_modules/npm5/node_modules/semver/semver.js:1085:16)
    at doesChildVersionMatch (/usr/local/lib/node_modules/npm5/lib/install/deps.js:76:17)
    at versionMatch (/usr/local/lib/node_modules/npm5/lib/install/deps.js:617:12)
    at Array.filter (native)
    at exports.findRequirement (/usr/local/lib/node_modules/npm5/lib/install/deps.js:627:23)
    at exports.findRequirement (/usr/local/lib/node_modules/npm5/lib/install/deps.js:634:10)
    at addDependency (/usr/local/lib/node_modules/npm5/lib/install/deps.js:485:15)
    at /usr/local/lib/node_modules/npm5/lib/install/deps.js:426:5
    at /usr/local/lib/node_modules/npm5/node_modules/slide/lib/async-map.js:52:35
    at Array.forEach (native)
    at /usr/local/lib/node_modules/npm5/node_modules/slide/lib/async-map.js:52:11
    at Array.forEach (native)
    at asyncMap (/usr/local/lib/node_modules/npm5/node_modules/slide/lib/async-map.js:51:8)
    at loadDeps (/usr/local/lib/node_modules/npm5/lib/install/deps.js:418:3)
```

#### How can the CLI team reproduce the problem?
I am not sure how exactly to reproduce. If I use npm4 I get the expected installation behavior. But when using npm5, `babel-traverse` is attempting to be installed from a private registry. The current project does not have an `.npmrc` file, and my user `.npmrc` does not specify a registry. 

The registry being used has been used in other projects, and projects in sibling folders contain a `.npmrc` file which contains the private registry.

debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm5',
1 verbose cli   'i',
1 verbose cli   '--save-dev',
1 verbose cli   'babel-eslint@6' ]
2 info using npm@5.0.0-beta.46
3 info using node@v6.9.5
4 notice BETA npm5 is beta software. Please see https://github.com/npm/npm/issues/16510 for known issues, and please file a new one if you find something new.
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://registry.npmjs.org/babel-eslint 19ms (from cache)
8 verbose pacote range manifest for babel-eslint@6 fetched in 49ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule babel-eslint@6.1.2 checking installable status
14 error cb() never called!
15 error This is an error with npm itself. Please report this error at:
16 error <https://github.com/npm/npm/issues>
```

### supporting information:

 - `npm -v` prints:
```
5.0.0-beta.46
```
 - `node -v` prints:
```
v6.9.5
```
 - `npm config get registry` prints:
```
npm notice BETA npm5 is beta software. Please see https://github.com/npm/npm/issues/16510 for known issues, and please file a new one if you find something new.
https://registry.npmjs.org/
```

 - Windows, OS X/macOS, or Linux?:
macOS
 - Network issues:
   - Geographic location where npm was run:
Seattle, WA
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by bellmounte** [comment]
This error might be two fold. First is the error message is reporting the incorrect registry. Secondly, the `cb() never called` error. I see many other issues around the `cb()`.

I will determine if `npm5` is always trying to use the private repository, even when it shouldn't be, and report back.

**Comment by zkat** [comment]
@bellmounte can you post the part of your `package-lock.json` pertaining to this bit?

You might need to regenerate it, because I know I fixed a similar bug recently. I'll look into this now, though.

**Comment by zkat** [comment]
@bellmounte ok so. You should no longer crash or see the `cb() never called` issue.

That said: you might want to regenerate your `package-lock.json`. Earlier versions of the beta shoved the entire registry URL in the `version` field even for regular dependencies.

As far as switching registries: I'm about to work on some code that will do some "smart" replacement rewriting for these lockfiles.

Could you confirm that `beta.48` fixes this problem? Then I'll close this issue.

**Comment by zkat** [comment]
@bellmounte I just pushed a change with `beta.49` that will allow you to switch registries even if the lockfile has a specific registry in your `resolved` field. I'm gonna close this now, but lmk if it's still borked :)

**Comment by bellmounte** [comment]
@zkat Confirmed this is working correctly with `np5@5.0.0-beta.49`. Thank you!
