### ISSUE TITLE
 npm install --production node-red-contrib-ibm-watson-iot npm ERR

### ISSUE THREAD

**Issue by mobili9363** [npm/npm#16609]
#### I'm opening this issue because: I wish to install Pallette from iot2040 but failed.
  - [ ] npm is crashing.
  - [/] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Error: Command failed: npm install --production node-red-contrib-ibm-watson-iot npm ERR! Linux 4.4.18-yocto-standard npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "--production" "node-red-contrib-ibm-watson-iot" npm ERR! node v6.9.2 npm ERR! npm v3.10.9 npm ERR! code EAI_AGAIN npm ERR! errno EAI_AGAIN npm ERR! syscall getaddrinfo npm ERR! getaddrinfo EAI_AGAIN registry.npmjs.org:443 npm ERR! npm ERR! If you need help, you may report this error at: npm ERR! <https://github.com/npm/npm/issues> npm ERR! Please include the following file with any support request: npm ERR! /home/root/.node-red/npm-debug.log
### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
Could you upload the npm-debug.log as a plaintext file to https://gist.github.com/ and post a link to it here?
