### ISSUE TITLE
Error -122

### ISSUE THREAD

**Issue by toymachiner62** [npm/npm#16604]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
When i try to install a global package I'm getting unknown system error -122

$  npm install -g yo generator-hubot
npm ERR! Linux 3.10.0-514.10.2.el7.x86_64
npm ERR! argv "/home/auto/m089269/.nvm/versions/node/v5.2.0/bin/node" "/home/auto/m089269/.nvm/versions/node/v5.2.0/bin/npm" "install" "-g" "yo" "generator-hubot"
npm ERR! node v5.2.0
npm ERR! npm  v3.3.12
npm ERR! code Unknown system error -122
npm ERR! errno -122
npm ERR! syscall close

npm ERR! Unknown system error -122: Unknown system error -122, close
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 3.10.0-514.10.2.el7.x86_64
npm ERR! argv "/home/auto/m089269/.nvm/versions/node/v5.2.0/bin/node" "/home/auto/m089269/.nvm/versions/node/v5.2.0/bin/npm" "install" "-g" "yo" "generator-hubot"
npm ERR! node v5.2.0
npm ERR! npm  v3.3.12
npm ERR! code Unknown system error -122
npm ERR! errno -122
npm ERR! syscall close

npm ERR! Unknown system error -122: Unknown system error -122, close
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/auto/m089269/npm-debug.log
#### How can the CLI team reproduce the problem?
I'm not sure if you can. I'm guessing it's due to some permissions or firewall configs with my company's server. I'm not sure what code -122 is so i'm not sure how to resolve. Google wasn't helping me find the definition of code -122

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by toymachiner62** [comment]
Any way to tell what the error -122 is?

**Comment by KenanY** [comment]
Might help:

```
$ cat /usr/include/asm-generic/errno.h | grep 122
#define EDQUOT          122     /* Quota exceeded */
```

**Comment by toymachiner62** [comment]
What would cause that when trying to install a package?

**Comment by KenanY** [comment]
Well, installing packages involves disk operations, and perhaps the disk quote is being exceeded? I must admit that I cannot recall seeing this issue on this issue tracker before, so I don't have a solution on hand :(
