### ISSUE TITLE
Node.js and npm not installed in correct directories

### ISSUE THREAD

**Issue by erbanach** [npm/npm#16605]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [X] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

I did a fresh install of the CLI, Node.js, and npm and am still getting this error. Here are all of my details:

Output from: ng --version: No such file or directory
Output from: node --version: v7.10.0
Output from: npm --version: 4.2.0
macOS Sierra 10.12.4

After running ng new app on a fresh install of Node.js and npm I am getting the error message:
-bash: /Users/Liz/.npm-packages/lib/node_modules/@angular/cli/bin/ng: No such file or directory

I wanted to check and see if those directories existed:

$ cd /Users/Liz/.npm-packages/lib/node_modules/@angular/cli/bin
-bash: cd: /Users/Liz/.npm-packages/lib/node_modules/@angular/cli/bin: No such file or directory
$ cd /Users/Liz/.npm-packages
-bash: cd: /Users/Liz/.npm-packages: No such file or directory

It seems like npm & Node.js did not get installed correctly if those directories don't exist? How can I fix this?

**Comment by zkat** [comment]
Did you use the node installer? What does `npm config ls` output? It looks like you're getting a `--prefix` config from somewhere.
