### ISSUE TITLE
npm Proxy issue while installing Cordova and Ionic!!

### ISSUE THREAD

**Issue by ansh0811** [npm/npm#16607]
I am unable to resolve proxy issue , tried everything which was mention in few issues of npm in github.

While installing Cordova and Ionic, I am facing proxy error at corporate network. Tried Wifi network too.

Support Information
Nodejs version : 6.10.3 ,
npm version : 3.10.10 , tried updating npm still same issue.
Windows 7, 64-bit

Can someone please suggest me how to deal with it? Or is there another way to download cordova and ionic ?

Please find the attachment of command line error and npm log.

Thanks!!

[npm-log.docx](https://github.com/npm/npm/files/995118/npm-log.docx)
![error](https://cloud.githubusercontent.com/assets/19550545/25983530/f7ee9a8e-3702-11e7-887e-a56011d518af.png)

**Comment by legodude17** [comment]
Could you upload the npm-debug.log from the latest version as a plaintext file to https://gist.github.com/ and post a link to it here?

**Comment by ansh0811** [comment]
Already attached npm-log.docx above.

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'cordova',
1 verbose cli   'ionic' ]
2 info using npm@3.10.10
3 info using node@v6.10.3
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData cordova
8 silly fetchPackageMetaData ionic
9 silly fetchNamedPackageData cordova
10 silly mapToRegistry name cordova
11 silly mapToRegistry using default registry
12 silly mapToRegistry registry https://registry.npmjs.org/
13 silly mapToRegistry data Result {
13 silly mapToRegistry   raw: 'cordova',
13 silly mapToRegistry   scope: null,
13 silly mapToRegistry   escapedName: 'cordova',
13 silly mapToRegistry   name: 'cordova',
13 silly mapToRegistry   rawSpec: '',
13 silly mapToRegistry   spec: 'latest',
13 silly mapToRegistry   type: 'tag' }
14 silly mapToRegistry uri https://registry.npmjs.org/cordova
15 silly fetchNamedPackageData ionic
16 silly mapToRegistry name ionic
17 silly mapToRegistry using default registry
18 silly mapToRegistry registry https://registry.npmjs.org/
19 silly mapToRegistry data Result {
19 silly mapToRegistry   raw: 'ionic',
19 silly mapToRegistry   scope: null,
19 silly mapToRegistry   escapedName: 'ionic',
19 silly mapToRegistry   name: 'ionic',
19 silly mapToRegistry   rawSpec: '',
19 silly mapToRegistry   spec: 'latest',
19 silly mapToRegistry   type: 'tag' }
20 silly mapToRegistry uri https://registry.npmjs.org/ionic
21 verbose request uri https://registry.npmjs.org/cordova
22 verbose request no auth needed
23 info attempt registry request try #1 at 5:43:19 PM
24 verbose request id caa43877aecda4de
25 http request GET https://registry.npmjs.org/cordova
26 verbose request uri https://registry.npmjs.org/ionic
27 verbose request no auth needed
28 info attempt registry request try #1 at 5:43:19 PM
29 http request GET https://registry.npmjs.org/ionic
30 info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND http http:443
31 info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND http http:443
32 info attempt registry request try #2 at 5:43:29 PM
33 http request GET https://registry.npmjs.org/cordova
34 info attempt registry request try #2 at 5:43:29 PM
35 http request GET https://registry.npmjs.org/ionic
36 info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND http http:443
37 info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND http http:443
38 info attempt registry request try #3 at 5:44:29 PM
39 http request GET https://registry.npmjs.org/cordova
40 info attempt registry request try #3 at 5:44:29 PM
41 http request GET https://registry.npmjs.org/ionic
42 silly fetchPackageMetaData Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND http http:443
42 silly fetchPackageMetaData     at ClientRequest.onError (C:\Program Files\nodejs\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:176:17)
42 silly fetchPackageMetaData     at ClientRequest.g (events.js:292:16)
42 silly fetchPackageMetaData     at emitOne (events.js:96:13)
42 silly fetchPackageMetaData     at ClientRequest.emit (events.js:188:7)
42 silly fetchPackageMetaData     at TLSSocket.socketErrorListener (_http_client.js:309:9)
42 silly fetchPackageMetaData     at emitOne (events.js:96:13)
42 silly fetchPackageMetaData     at TLSSocket.emit (events.js:188:7)
42 silly fetchPackageMetaData     at connectErrorNT (net.js:1021:8)
42 silly fetchPackageMetaData     at _combinedTickCallback (internal/process/next_tick.js:80:11)
42 silly fetchPackageMetaData     at process._tickCallback (internal/process/next_tick.js:104:9)
42 silly fetchPackageMetaData  error for cordova { Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND http http:443
42 silly fetchPackageMetaData     at ClientRequest.onError (C:\Program Files\nodejs\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:176:17)
42 silly fetchPackageMetaData     at ClientRequest.g (events.js:292:16)
42 silly fetchPackageMetaData     at emitOne (events.js:96:13)
42 silly fetchPackageMetaData     at ClientRequest.emit (events.js:188:7)
42 silly fetchPackageMetaData     at TLSSocket.socketErrorListener (_http_client.js:309:9)
42 silly fetchPackageMetaData     at emitOne (events.js:96:13)
42 silly fetchPackageMetaData     at TLSSocket.emit (events.js:188:7)
42 silly fetchPackageMetaData     at connectErrorNT (net.js:1021:8)
42 silly fetchPackageMetaData     at _combinedTickCallback (internal/process/next_tick.js:80:11)
42 silly fetchPackageMetaData     at process._tickCallback (internal/process/next_tick.js:104:9) code: 'ECONNRESET' }
43 silly fetchPackageMetaData Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND http http:443
43 silly fetchPackageMetaData     at ClientRequest.onError (C:\Program Files\nodejs\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:176:17)
43 silly fetchPackageMetaData     at ClientRequest.g (events.js:292:16)
43 silly fetchPackageMetaData     at emitOne (events.js:96:13)
43 silly fetchPackageMetaData     at ClientRequest.emit (events.js:188:7)
43 silly fetchPackageMetaData     at TLSSocket.socketErrorListener (_http_client.js:309:9)
43 silly fetchPackageMetaData     at emitOne (events.js:96:13)
43 silly fetchPackageMetaData     at TLSSocket.emit (events.js:188:7)
43 silly fetchPackageMetaData     at connectErrorNT (net.js:1021:8)
43 silly fetchPackageMetaData     at _combinedTickCallback (internal/process/next_tick.js:80:11)
43 silly fetchPackageMetaData     at process._tickCallback (internal/process/next_tick.js:104:9)
43 silly fetchPackageMetaData  error for ionic { Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND http http:443
43 silly fetchPackageMetaData     at ClientRequest.onError (C:\Program Files\nodejs\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:176:17)
43 silly fetchPackageMetaData     at ClientRequest.g (events.js:292:16)
43 silly fetchPackageMetaData     at emitOne (events.js:96:13)
43 silly fetchPackageMetaData     at ClientRequest.emit (events.js:188:7)
43 silly fetchPackageMetaData     at TLSSocket.socketErrorListener (_http_client.js:309:9)
43 silly fetchPackageMetaData     at emitOne (events.js:96:13)
43 silly fetchPackageMetaData     at TLSSocket.emit (events.js:188:7)
43 silly fetchPackageMetaData     at connectErrorNT (net.js:1021:8)
43 silly fetchPackageMetaData     at _combinedTickCallback (internal/process/next_tick.js:80:11)
43 silly fetchPackageMetaData     at process._tickCallback (internal/process/next_tick.js:104:9) code: 'ECONNRESET' }
44 silly rollbackFailedOptional Starting
45 silly rollbackFailedOptional Finishing
46 silly runTopLevelLifecycles Finishing
47 silly install printInstalled
48 verbose stack Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND http http:443
48 verbose stack     at ClientRequest.onError (C:\Program Files\nodejs\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:176:17)
48 verbose stack     at ClientRequest.g (events.js:292:16)
48 verbose stack     at emitOne (events.js:96:13)
48 verbose stack     at ClientRequest.emit (events.js:188:7)
48 verbose stack     at TLSSocket.socketErrorListener (_http_client.js:309:9)
48 verbose stack     at emitOne (events.js:96:13)
48 verbose stack     at TLSSocket.emit (events.js:188:7)
48 verbose stack     at connectErrorNT (net.js:1021:8)
48 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:80:11)
48 verbose stack     at process._tickCallback (internal/process/next_tick.js:104:9)
49 verbose cwd C:\Users\sss850104
50 error Windows_NT 6.1.7601
51 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova" "ionic"
52 error node v6.10.3
53 error npm  v3.10.10
54 error code ECONNRESET
55 error network tunneling socket could not be established, cause=getaddrinfo ENOTFOUND http http:443
56 error network This is most likely not a problem with npm itself
56 error network and is related to network connectivity.
56 error network In most cases you are behind a proxy or have bad network settings.
56 error network
56 error network If you are behind a proxy, please make sure that the
56 error network 'proxy' config is set properly.  See: 'npm help config'
57 verbose exit [ 1, true ]

**Comment by legodude17** [comment]
Try updating `npm` to latest
