### ISSUE TITLE
npm cannot save to package.json using a package.json file volume mount inside a docker container

### ISSUE THREAD

**Issue by trentmswanson** [npm/npm#16615]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?
When attempting to install a package and save to a package.json file from inside a docker container that's maps the file as a volume mount I receive the following error.
`npm WARN saveError EBUSY: resource busy or locked, rename '/app/package.json.3329677482' -> '/app/package.json'`

#### How can the CLI team reproduce the problem?

Start a docker container mapped to a `package.json` file in the host system using something like the following from a directory with a valid `package.json`

``docker run --name npm-test -v `pwd`/package.json:/app/package.json -itw /app node:7.10.0 bash`` once you have a CLI in the container run something like `npm install --save koa`

I assume npm is attempting to replace the package.json file instead of writing to package.json. I can work around this by mapping the project volume like I have done in the past, but this was proving to be a bit cleaner since the node_modules and other files in my container remained separate from the host dev project.

### supporting information:

 - `npm -v` prints: 4.2.0
 - `node -v` prints: 7.10.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: OSX
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [x] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by airtonix** [comment]
also experiencing this problem.

**Comment by smiffy6969** [comment]
Also have this issue.... have tried everything, cache clean on both host and container... forcing permissions to 777, changing ownership of file....... everything.

`docker-compose run container npm install xxx --save`

or docker run or any other....

I have the volume mapping the package.json file to the container
