### ISSUE TITLE
 run cmd fail with - UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1):

### ISSUE THREAD

**Issue by mahaase1** [npm/npm#16619]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
missing script: build

#### How can the CLI team reproduce the problem?

running cli install for NERDStack, https://github.com/NERDStack/nerd-cli
fails on 'nerd run'

debug log file
___________________
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.10.10
3 info using node@v6.10.3
4 verbose config Skipping project config: C:\Users\mahaas/.npmrc. (matches userconfig)
5 verbose stack Error: missing script: build
5 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:151:19)
5 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:61:5
5 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:356:5
5 verbose stack     at handleExists (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:329:20)
5 verbose stack     at FSReqWrap.cb [as oncomplete] (fs.js:258:19)
6 verbose cwd C:\Users\mahaas\mmv
7 error Windows_NT 10.0.15063
8 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
9 error node v6.10.3
10 error npm  v3.10.10
11 error missing script: build
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]

### supporting information:

____________________________
 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
Hello! So, the way `npm run build` works is that it looks in your current `package.json` for a defined `"build"` [script](https://docs.npmjs.com/misc/scripts), and then runs that. The error message you're seeing is trying to tell you that you have not defined a `"build"` script in your `package.json`, hence `npm run build` has no idea what you want it to do.

To solve this issue, all you have to do is add a new script to your `package.json`. It might look something like this, for example:

``` json
{
  "name": "package-name",
  "version": "1.0.0",
  "description": "package description",
  "scripts": {
    "build": "node --version",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {},
  "devDependencies": {}
}
```

Note how this `package.json` has a `"build"` script that runs `node --version`. You'll definitely want to change the command to whatever is most appropriate for your project.

Let me know if you run into any further `npm` issues :)
