### ISSUE TITLE
npm ERR! Cannot read property 'path' of null when executing "npm i -g tfx-cli"

### ISSUE THREAD

**Issue by jonathan305** [npm/npm#16612]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I've set the Proxy and changed the registry to use http instead of https
npm config set proxy http://proxy.company.com:8080
npm config set https-proxy http://proxy.company.com:8080
npm config set registry=http://registry.npmjs.org/

yet when i try to check http-proxy value is says undefined
C:\Program Files\nodejs>npm config get http-proxy
undefined

C:\Program Files\nodejs>npm i -g tfx-cli
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "i" "-g" "tfx-cli"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0

npm ERR! Cannot read property 'path' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\g09867\AppData\Roaming\npm-cache\_logs\2017-05-12T11_33_27
_670Z-debug.log

#### How can the CLI team reproduce the problem?

1.download nodejs from main site.
2.install it
3.run CMD and execute npm i -g tfx-cli

https://gist.github.com/jonathan305/b73133e6392caec6ad11dbad0a4b9e23#file-gistfile1-txt

### supporting information:

 - `npm -v` prints:
4.2.0

 - `node -v` prints:
v7.10.0

 - `npm config get registry` prints:
http://registry.npmjs.org/

 - Windows, OS X/macOS, or Linux?:
Windows 7

 - Network issues:
   - Geographic location where npm was run:  BE
   - [x ] I use a proxy to connect to the npm registry.
   - [ x] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
This is most likely a problem with your internet. Please check your internet connection.

**Comment by jonathan305** [comment]
didn't change anything but it's working now.
