### ISSUE TITLE
getting "Cannot find module 'internal/fs'" in aurelia-cli

### ISSUE THREAD

**Issue by kintela** [npm/npm#16614]
#### I'm opening this issue because:

  - [ ] npm is producing an incorrect install.
 
#### What's going wrong?

I can not install aurelia-cli

### supporting information:

 OS X/macOS
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
Could you upload the npm-debug.log as a plaintext file to https://gist.github.com/ and post a link to it here?
