### ISSUE TITLE
error installing angular/cli

### ISSUE THREAD

**Issue by ivasniel** [npm/npm#16616]
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\yanaysi\AppData\Local\Temp\npm-23640-1e0a699b\registry.npmjs.org\async\-\async-0.9.2.tgz.1592019996' -> 'C:\Users\yanaysi\AppData\Local\Temp\npm-23640-1e0a699b\registry.npmjs.org\async\-\async-0.9.2.tgz'
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli@latest"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by jotatoledo** [comment]
Please use the issue template
