### ISSUE TITLE
Npm reaction install not working 

### ISSUE THREAD

**Issue by invergo** [npm/npm#16618]
#### I'm opening this issue because:

  - [ ] npm is doing something I don't understand.

npm ERR! Darwin 16.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "reaction-cli"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! path /Users/cameron/.npm-packages/lib/node_modules/reaction-cli
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/Users/cameron/.npm-packages/lib/node_modules/reaction-cli'
npm ERR!     at Error (native)
npm ERR!  { Error: EACCES: permission denied, access '/Users/cameron/.npm-packages/lib/node_modules/reaction-cli'
npm ERR!     at Error (native)
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/Users/cameron/.npm-packages/lib/node_modules/reaction-cli' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/cameron/npm-debug.log

#### What's going wrong?

npm install -g reaction-cli

### supporting information:

 ]

**Comment by KenanY** [comment]
Seems like you do not have permission to access the global modules directory. One option you could try is elevating your privileges to that of the superuser through `sudo`, like so:

```
sudo npm install -g reaction-cli
```
