### ISSUE TITLE
Npm view @watsonanalytics/test-framework still not working after validating authorized URL

### ISSUE THREAD

**Issue by matlap29** [npm/npm#16611]
#### I'm opening this issue because:

  - [ ] npm is doing something I don't understand.

#### What's going wrong?
npm view @watsonanalytics/test-framework still output:

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\nodejs\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\npm-cl
i.js" "view" "@watsonanalytics/test-framework"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code E401

npm ERR! visit https://github.ibm.com/login/oauth/authorize?redirect_uri=https%3
A%2F%2Fnpm.whitewater.ibm.com%2Fauth%2Foauth2%2Fcallback&scope=user&state=&respo
nse_type=code&client_id=632f6ba99bfdaf940fe8 to validate your session : @watsona
nalytics/test-framework
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\windows\system32\npm-debug.log

I then go to successfully validate:  https://github.ibm.com/login/oauth/authorize?redirect_uri=https%3A%2F%2Fnpm.whitewater.ibm.com%2Fauth%2Foauth2%2Fcallback&scope=user&state=&response_type=code&client_id=632f6ba99bfdaf940fe8

and still the npm view command still does not work.

**Comment by legodude17** [comment]
Try updating npm to the latest version.
