### ISSUE TITLE
Failed to send email from my desire domain:Error: Hostname/IP doesn't match certificate's altnames: "Host: mail.digieasynow.com. is not in the cert's altnames: DNS:.webhostbox.net, DNS:webhostbox.net"

### ISSUE THREAD

**Issue by adminusr** [npm/npm#16622]
I am writing script to send email from my domain using nodmailer package, my code is  below:-
/************send email **************/
var nodemailer = require('nodemailer');

// create reusable transporter object using the default SMTP transport
var transporter = nodemailer.createTransport('smtp://admin@digieasynow.com:paxxxxxxxxx@mail.digieasynow.com');

// setup e-mail data with unicode symbols
var mailOptions = {
    from: '"Tester 👥" <admin@digieasynow.com>', // sender address
    to: 'example@gmail.com', // list of receivers
    subject: 'Hello ✔', // Subject line
    text: 'Hello world 🐴', // plaintext body
    html: '<b>Hello world 🐴</b>' // html body
};

// send mail with defined transport object
transporter.sendMail(mailOptions, function(error, info){
    if(error){
        return console.log(error);
    }
    console.log('Message sent: ' + info.response);
/********************End code here******************/

On running it gives below error..........................

{ Error: Hostname/IP doesn't match certificate's altnames: "Host: mail.digieasynow.com. is not in the cert's altnames: DNS:*.webhostbox.net, DNS:webhostbox.net"
    at Object.checkServerIdentity (tls.js:199:17)
    at TLSSocket.<anonymous> (_tls_wrap.js:1098:29)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:610:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)
  reason: 'Host: mail.digieasynow.com. is not in the cert\'s altnames: DNS:*.webhostbox.net, DNS:webhostbox.net',
  host: 'mail.digieasynow.com',
  cert:
   { subject: { OU: [Object], CN: '*.webhostbox.net' },
     issuer:
      { C: 'GB',
        ST: 'Greater Manchester',
        L: 'Salford',
        O: 'COMODO CA Limited',
        CN: 'COMODO RSA Domain Validation Secure Server CA' },
     subjectaltname: 'DNS:*.webhostbox.net, DNS:webhostbox.net',
     infoAccess: { 'CA Issuers - URI': [Object], 'OCSP - URI': [Object] },
     modulus: 'BE13FBC8EB6587BA7FC05129D66898202D2E6A2D87A4C9E8036654DFDBFFABD8AA5CB22E3EA2011760D13BE1DC32DD91F4A9A3CAE05AE0A379FC7CFEC7C781E2B238C4C2794C8453991124F682158A7E2C8C87266B10DF3F5DC7C5F1C69E581204125DC648CFA11781DF252830104D4FFB8F296EE3D1D3B8952CA15F28EC76491532ACDB122BF260D1FD9540CF215989DC03F831561B32BFA7EBDB84A8F9803AC182CFC36333C58D6D5D55D74B5343AEF23D08F7B264D2C93BC586F57AB68E8CB9F62FD21688ADDA461E9F3692388EEFAA2D87E509C28FDE701721BB6FE1C2A101F2C3A7F1F77710E16B9937C19F53E771719F690029B32EACDE797B044AE939',
     exponent: '0x10001',
     valid_from: 'Mar 14 00:00:00 2016 GMT',
     valid_to: 'Jun  5 23:59:59 2018 GMT',
     fingerprint: '7B:1C:DA:07:DB:A6:A6:4A:F1:5B:92:29:FF:5B:58:F6:2C:D2:B0:E6',
     ext_key_usage: [ '1.3.6.1.5.5.7.3.1', '1.3.6.1.5.5.7.3.2' ],
     serialNumber: '630D2DB20A3BB1655303714DD9AFA4BC',
     raw: <Buffer 30 82 05 57 30 82 04 3f a0 03 02 01 02 02 10 63 0d 2d b2 0a 3b b1 65 53 03 71 4d d9 af a4 bc 30 0d 06 09 2a 86 48 86 f7 0d 01 01 0b 05 00 30 81 90 31 ... > },
  code: 'ESOCKET',
  command: 'CONN' }

Please help ...................

**Comment by KenanY** [comment]
Doesn't look like an issue with the `npm` CLI to me. You might wanna take this to a place like StackOverflow instead.
