### ISSUE TITLE
Web interface for npmjs.com

### ISSUE THREAD

**Issue by photopea** [npm/npm#16625]
Hi, I don't use Node.js or NPM, but some of users of my software ask me to publish it on npmjs.com . 

Can you make a web interface for working with packages, just like GitHub.com has? Or at least let me insert the GIT location of some package, which you will synchronize automatically when it is updated? I am afraid my workflow would get messy, if I had to distribute my code on so many channels.

**Comment by KenanY** [comment]
This probably belongs in <https://github.com/npm/www>?

**Comment by zkat** [comment]
As Kenan says, this is better off posted to npm/www. This repo is for the CLI team, and this is not something we can do anything about.

**Comment by photopea** [comment]
Ok, I will ask about it there.
