### ISSUE TITLE
[5.0.0-beta.49] There's now way to don't save a dependency

### ISSUE THREAD

**Issue by RomainLanz** [npm/npm#16626]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's the feature?

Currently `npm5` automatically add the installed dependency into the `package.json` and `package-lock.json`.

There's some use case where you don't want to add the dependency into those files.

It would be great to add a flag `--without-save` or something similar to the CLI.

**Comment by KenanY** [comment]
I believe this already exists as `--no-save`  or `npm config set save false`.

**Comment by RomainLanz** [comment]
Hey @KenanY

`--no-save` seems to work but it's not written within the documentation of the command.

```bash
→ npm5 i -h

npm install (with no args, in package dir)
npm install [<@scope>/]<pkg>
npm install [<@scope>/]<pkg>@<tag>
npm install [<@scope>/]<pkg>@<version>
npm install [<@scope>/]<pkg>@<version range>
npm install <folder>
npm install <tarball file>
npm install <tarball url>
npm install <git:// url>
npm install <github username>/<github project>

aliases: i, isntall
common options: [--save|--save-dev|--save-optional] [--save-exact]
```

I also noticed a typo. Let me create a PR.

**Comment by KenanY** [comment]
It's a feature of [`nopt`](https://github.com/npm/nopt), and it essentially equates to setting `save` to `false`. <https://docs.npmjs.com/misc/config> would be a better place to document it.

`isntall` is intentionally a typo; it is a common enough typo that it has been made an alias of `install` for convenience sake.

**Comment by RomainLanz** [comment]
Thanks!
