### ISSUE TITLE
problem installing angular

### ISSUE THREAD

**Issue by abln001** [npm/npm#16627]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
when trying to install angular, it gives and error
[npm-debug.txt](https://github.com/npm/npm/files/1001040/npm-debug.txt)

#### How can the CLI team reproduce the problem?
I'm running npm install -g @angular/cli and it give and error 
'
shasum check failed

### supporting information:

 - `npm -v` prints:  v3.10.10
 - `node -v` prints: v6.10.3
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:windows7
 - Network issues:
   - Geographic location where npm  ] I use a proxy to connect to the npm registry.
   - [ x] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ x] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by t-sivakami** [comment]
Hi, 
I am unable to start the angular application from linux.
I have installed node and npm already . here are the version details and the error log. Suggest a solution.
I have set the proxy in the terminal as well.

xxx@xxxx:~/PATH_TO_ANGULAR_APP$ node -v
v0.10.25
shiva@01HW315460:~/PATH_TO_ANGULAR_APP$ npm -v
1.3.10
shiva@01HW315460:~/PATH_TO_ANGULAR_APP$ npm start
npm ERR! Error: ENOENT, open '/PATH_TO_ANGULAR_APP$/package.json'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.16.0-71-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /PATH_TO_ANGULAR_APP$
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /PATH_TO_ANGULAR_APP$/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! Error: EACCES, open 'npm-debug.log'
npm ERR!  { [Error: EACCES, open 'npm-debug.log'] errno: 3, code: 'EACCES', path: 'npm-debug.log' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Linux 3.16.0-71-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /PATH_TO_ANGULAR_APP$
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path npm-debug.log
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, open 'npm-debug.log'
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /PATH_TO_ANGULAR_APP$/npm-debug.log
npm ERR! not ok code 0

**Comment by legodude17** [comment]
Please update `npm`, your version is years old and not supported.
