### ISSUE TITLE
npm install -g cordova ionic   errors

### ISSUE THREAD

**Issue by tijanibro** [npm/npm#16621]
I have been trying to install ionic with npm on top of my cordova installation

**Comment by huskynation** [comment]
Are you on OSX or Windows? If OSX, this might work for you, first remove any old versions of NodeJS to avoid conflicts and incompatibility issues, then try the following:

* Install latest version of NodeJS from https://nodejs.org/en/
* `npm cache clean`
* `sudo npm install --save-dev --save-exact @ionic/cli-plugin-cordova@latest`
* `npm set registry=https://registry.npmjs.org/`
* `sudo npm install -g ionic`

**Comment by KenanY** [comment]
@tijanibro I'd like a bit more context here. Could you _at least_ explain what command you are running, what output you expect, and what output you are receiving? Uploading the debug log to <https://gist.github.com/> would help a ton too. Thanks!

**Comment by tijanibro** [comment]
Thanks. This is resolved based on it suggestion. Thanks
