### ISSUE TITLE
Websocket-server error

### ISSUE THREAD

**Issue by HimahoYT** [npm/npm#16623]
#### I'm opening this issue because:

  - Gives me an error when try to install Websocket-server

#### I do "npm install websocket-server and gives this error:

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "websocket-server"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10

npm ERR! Cannot convert undefined or null to object
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Propietario\Desktop\APPS\BrowserQuest-master\npm-debug.log

**Comment by KenanY** [comment]
The `websocket-server` module has been unpublished, hence it is now impossible to install it. Admittedly, the error message could be a bit more clear; there's probably an issue already open for that.
