### ISSUE TITLE
unable to install npm

### ISSUE THREAD

**Issue by SachinBT** [npm/npm#16620]
#### I'm opening this issue because:

 
  - [ ] npm is doing something I don't understand.
  

#### What's going wrong?
when i run "npm install -g angular/cli" in the commandprompt it is giving some errors. I tried with 
"npm install -g -f angular/cli"  also but still giving the same errors. How can I fix this?

**Comment by jotatoledo** [comment]
that should be `npm install -g @angular/cli`
