### ISSUE TITLE
`npm link` is INCLUDING "node_modules" in local package, disregarding current NPM documentation.

### ISSUE THREAD

**Issue by csales1987** [npm/npm#16632]
#### I'm opening this issue because:

  - [x] npm is producing an incorrect install.

#### What's going wrong?

When doing an `npm link` of any package, the `node_modules` folder is getting included into the outputted global package, even though documentation specifically states this folder is excluded by default.

[https://docs.npmjs.com/files/package.json#files](https://docs.npmjs.com/files/package.json#files)

Under files, I wanted to use a wildcard to accept all new directories that may be added except for node_modules obviously. I don't want to have to include a .npmrc file just to exclude one directory that should already be excluded. Obviously I will do this for now, but i think this is quick hitter for someone. If I need to fix i can.
 
#### How can the CLI team reproduce the problem?

1. In any package.json, add the following to the files config option...

```
"name": "test1",
"files": [
    "*"
]
```
2. Run the command: `npm link`
3. In another test project, run the command: `npm link test1`
4. Look into the `node_modules` folder for `test1`, and you will see `node_modules` being added.

**Comment by roblafeve** [comment]
@csales1987 did you figure out how to resolve this issue?
