### ISSUE TITLE
Error: connect EHOSTUNREACH

### ISSUE THREAD

**Issue by prachi-nitt** [npm/npm#16635]
Error Log :
npm ERR! Error: connect EHOSTUNREACH
npm ERR!     at errnoException (net.js:901:11)
npm ERR!     at Object.afterConnect [as oncomplete] (net.js:892:19)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-80-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "yo" "grunt-cli"
npm ERR! cwd /home/prachi
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! syscall connect
npm ERR! code EHOSTUNREACH
npm ERR! errno EHOSTUNREACH

Command :
sudo npm install -g yo grunt-cli

npm-debug.log
797 info retry will retry, error on last attempt: Error: connect EHOSTUNREACH
798 info trying registry request attempt 3 at 12:47:20
799 http GET http://registry.npmjs.org/npm-keyword
800 info trying registry request attempt 3 at 12:47:45
801 http GET http://registry.npmjs.org/fullname
802 info trying registry request attempt 3 at 12:47:49
803 http GET http://registry.npmjs.org/figures
804 info trying registry request attempt 3 at 12:48:16
805 http GET http://registry.npmjs.org/repeating
806 info retry will retry, error on last attempt: Error: connect ETIMEDOUT
807 info retry will retry, error on last attempt: Error: connect ETIMEDOUT
808 info retry will retry, error on last attempt: Error: connect ETIMEDOUT
809 info retry will retry, error on last attempt: Error: connect EHOSTUNREACH
810 info retry will retry, error on last attempt: Error: connect EHOSTUNREACH
811 info retry will retry, error on last attempt: Error: connect EHOSTUNREACH
812 info retry will retry, error on last attempt: Error: connect EHOSTUNREACH
813 info retry will retry, error on last attempt: Error: connect ETIMEDOUT
814 info trying registry request attempt 3 at 12:49:19
815 http GET http://registry.npmjs.org/lodash
816 info trying registry request attempt 3 at 12:49:20
817 http GET http://registry.npmjs.org/meow
818 info retry will retry, error on last attempt: Error: connect ETIMEDOUT
819 silly lockFile 2b6848f7-chalk-1-0-0 chalk@^1.0.0
820 silly lockFile 2b6848f7-chalk-1-0-0 chalk@^1.0.0
821 verbose about to build /usr/local/lib/node_modules/yo
822 info /usr/local/lib/node_modules/yo unbuild
823 info preuninstall yo@1.8.5
824 info uninstall yo@1.8.5
825 verbose true,/usr/local/lib/node_modules,/usr/local/lib/node_modules unbuild yo@1.8.5
826 verbose /usr/local/bin,[object Object] binRoot
827 info postuninstall yo@1.8.5
828 error Error: connect EHOSTUNREACH
828 error     at errnoException (net.js:901:11)
828 error     at Object.afterConnect [as oncomplete] (net.js:892:19)
829 error If you need help, you may report this log at:
829 error     <http://github.com/isaacs/npm/issues>
829 error or email it to:
829 error     <npm-@googlegroups.com>
830 error System Linux 3.13.0-80-generic
831 error command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "yo" "grunt-cli"
832 error cwd /home/prachi
833 error node -v v0.10.25
834 error npm -v 1.3.10
835 error syscall connect
836 error code EHOSTUNREACH
837 error errno EHOSTUNREACH
838 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
While this looks like an issue with your internet connection, do note that your versions of Node.js and `npm` are years old and are no longer supported.
