### ISSUE TITLE
npm not working on windows 10

### ISSUE THREAD

**Issue by dagogodboss** [npm/npm#16630]
Hello,
my problem is npm not respoding , for example if i type node -v it gives me : $ node -v
v7.10.0
but when type npm -v , command propmt not responding with anything.

this also the same for all other commands for npm.
i checked folder C:\Users\user\AppData\Roaming\npm but it is empty
and there is npm folder in C:\Program Files\nodejs\node_modules\npm

i don't know why it is not working so any help will be appreciated.

**Comment by HotCustard** [comment]
Same issue, working fine last yesterday, no changes made and today no npm commands respond.

**Comment by HotCustard** [comment]
For me upgrading from node v7.9.0 to v7.10.0 fixed the issue.
