### ISSUE TITLE
npm not working on windows 10

### ISSUE THREAD

**Issue by PrabuGovindan** [npm/npm#16641]
C:\Users\RBPG9>npm install -g cordova
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead https://registry.npmjs.org/node-uuidt\2.0.1\package\package.json writtennrittenittenittenn
C:\Users\RBPG9\AppData\Roaming\npm
`-- (empty)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! path C:\Users\RBPG9\AppData\Roaming\npm\node_modules\.staging\abbrev-9b6440b1
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\RBPG9\AppData\Roaming\npm\node_modules\.staging\abbrev-9b6440b1' -> 'C:\Users\RBPG9\AppData\Roaming\npm\node_modules\cordova\node_modules\npm\node_modules\abbrev'
npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\RBPG9\AppData\Roaming\npm\node_modules\.staging\abbrev-9b6440b1' -> 'C:\Users\RBPG9\AppData\Roaming\npm\node_modules\cordova\node_modules\npm\node_modules\abbrev'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\RBPG9\npm-debug.log
npm ERR! code 1

**Comment by legodude17** [comment]
Please go through the [troubleshooting guide](https://github.com/npm/npm/wiki/Troubleshooting).

**Comment by PrabuGovindan** [comment]
Not Working

**Comment by legodude17** [comment]
What is the new log?

**Comment by rmc33** [comment]
HIi @PrabuGovindan looks like your issue was with renaming the abbrev module. You may have already installed this globally or during npm's process of deduping / renaming node_module dependencies it was unable to rename it. You can try to uninstall that one npm uninstall -g abbrev and install cordova again. I was able to install cordova today on windows 10.
