### ISSUE TITLE
npm-debug.log 

### ISSUE THREAD

**Issue by Luffz** [npm/npm#16644]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'install' ]
2 info using npm@3.10.10
3 info using node@v6.10.2
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly install normalizeTree
8 silly loadCurrentTree Finishing
9 silly loadIdealTree Starting
10 silly install loadIdealTree
11 silly cloneCurrentTree Starting
12 silly install cloneCurrentTreeToIdealTree
13 silly cloneCurrentTree Finishing
14 silly loadShrinkwrap Starting
15 silly install loadShrinkwrap
16 silly loadShrinkwrap Finishing
17 silly loadAllDepsIntoIdealTree Starting
18 silly install loadAllDepsIntoIdealTree
19 silly fetchOtherPackageData salesforcemobilesdk-ios@git+https://github.com/forcedotcom/SalesforceMobileSDK-iOS.git#v5.1.0
20 silly cache add args [ 'salesforcemobilesdk-ios@git+https://github.com/forcedotcom/SalesforceMobileSDK-iOS.git#v5.1.0',
20 silly cache add   null ]
21 verbose cache add spec salesforcemobilesdk-ios@git+https://github.com/forcedotcom/SalesforceMobileSDK-iOS.git#v5.1.0
22 silly cache add parsed spec Result {
22 silly cache add   raw: 'salesforcemobilesdk-ios@git+https://github.com/forcedotcom/SalesforceMobileSDK-iOS.git#v5.1.0',
22 silly cache add   scope: null,
22 silly cache add   escapedName: 'salesforcemobilesdk-ios',
22 silly cache add   name: 'salesforcemobilesdk-ios',
22 silly cache add   rawSpec: 'git+https://github.com/forcedotcom/SalesforceMobileSDK-iOS.git#v5.1.0',
22 silly cache add   spec: 'git+https://github.com/forcedotcom/SalesforceMobileSDK-iOS.git#v5.1.0',
22 silly cache add   type: 'hosted',
22 silly cache add   hosted:
22 silly cache add    { type: 'github',
22 silly cache add      ssh: 'git@github.com:forcedotcom/SalesforceMobileSDK-iOS.git#v5.1.0',
22 silly cache add      sshUrl: 'git+ssh://git@github.com/forcedotcom/SalesforceMobileSDK-iOS.git#v5.1.0',
22 silly cache add      httpsUrl: 'git+https://github.com/forcedotcom/SalesforceMobileSDK-iOS.git#v5.1.0',
22 silly cache add      gitUrl: 'git://github.com/forcedotcom/SalesforceMobileSDK-iOS.git#v5.1.0',
22 silly cache add      shortcut: 'github:forcedotcom/SalesforceMobileSDK-iOS#v5.1.0',
22 silly cache add      directUrl: 'https://raw.githubusercontent.com/forcedotcom/SalesforceMobileSDK-iOS/v5.1.0/package.json' } }
23 verbose addRemoteGit caching git+https://github.com/forcedotcom/SalesforceMobileSDK-iOS.git#v5.1.0
24 verbose addRemoteGit git+https://github.com/forcedotcom/SalesforceMobileSDK-iOS.git#v5.1.0 is a repository hosted by github
25 silly tryClone cloning git+https://github.com/forcedotcom/SalesforceMobileSDK-iOS.git#v5.1.0 via git+https://github.com/forcedotcom/SalesforceMobileSDK-iOS.git#v5.1.0
26 verbose tryClone git-https-github-com-forcedotcom-SalesforceMobileSDK-iOS-git-v5-1-0-b623d5a1 not in flight; caching
27 verbose correctMkdir /Users/coopercher/.npm/_git-remotes correctMkdir not in flight; initializing
28 info git [ 'clone',
28 info git   '--template=/Users/coopercher/.npm/_git-remotes/_templates',
28 info git   '--mirror',
28 info git   'https://github.com/forcedotcom/SalesforceMobileSDK-iOS.git',
28 info git   '/Users/coopercher/.npm/_git-remotes/git-https-github-com-forcedotcom-SalesforceMobileSDK-iOS-git-v5-1-0-b623d5a1' ]
29 error git clone --template=/Users/coopercher/.npm/_git-remotes/_templates --mirror https://github.com/forcedotcom/SalesforceMobileSDK-iOS.git /Users/coopercher/.npm/_git-remotes/git-https-github-com-forcedotcom-SalesforceMobileSDK-iOS-git-v5-1-0-b623d5a1: Cloning into bare repository '/Users/coopercher/.npm/_git-remotes/git-https-github-com-forcedotcom-SalesforceMobileSDK-iOS-git-v5-1-0-b623d5a1'...
29 error git clone --template=/Users/coopercher/.npm/_git-remotes/_templates --mirror https://github.com/forcedotcom/SalesforceMobileSDK-iOS.git /Users/coopercher/.npm/_git-remotes/git-https-github-com-forcedotcom-SalesforceMobileSDK-iOS-git-v5-1-0-b623d5a1: error: RPC failed; curl 56 SSLRead() return error -9806
29 error git clone --template=/Users/coopercher/.npm/_git-remotes/_templates --mirror https://github.com/forcedotcom/SalesforceMobileSDK-iOS.git /Users/coopercher/.npm/_git-remotes/git-https-github-com-forcedotcom-SalesforceMobileSDK-iOS-git-v5-1-0-b623d5a1: fatal: The remote end hung up unexpectedly
29 error git clone --template=/Users/coopercher/.npm/_git-remotes/_templates --mirror https://github.com/forcedotcom/SalesforceMobileSDK-iOS.git /Users/coopercher/.npm/_git-remotes/git-https-github-com-forcedotcom-SalesforceMobileSDK-iOS-git-v5-1-0-b623d5a1: fatal: early EOF
29 error git clone --template=/Users/coopercher/.npm/_git-remotes/_templates --mirror https://github.com/forcedotcom/SalesforceMobileSDK-iOS.git /Users/coopercher/.npm/_git-remotes/git-https-github-com-forcedotcom-SalesforceMobileSDK-iOS-git-v5-1-0-b623d5a1: fatal: index-pack failed
30 silly fetchPackageMetaData Error: Command failed: git clone --template=/Users/coopercher/.npm/_git-remotes/_templates --mirror https://github.com/forcedotcom/SalesforceMobileSDK-iOS.git /Users/coopercher/.npm/_git-remotes/git-https-github-com-forcedotcom-SalesforceMobileSDK-iOS-git-v5-1-0-b623d5a1
30 silly fetchPackageMetaData Cloning into bare repository '/Users/coopercher/.npm/_git-remotes/git-https-github-com-forcedotcom-SalesforceMobileSDK-iOS-git-v5-1-0-b623d5a1'...
30 silly fetchPackageMetaData error: RPC failed; curl 56 SSLRead() return error -9806
30 silly fetchPackageMetaData fatal: The remote end hung up unexpectedly
30 silly fetchPackageMetaData fatal: early EOF
30 silly fetchPackageMetaData fatal: index-pack failed
30 silly fetchPackageMetaData
30 silly fetchPackageMetaData     at ChildProcess.exithandler (child_process.js:204:12)
30 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
30 silly fetchPackageMetaData     at ChildProcess.emit (events.js:191:7)
30 silly fetchPackageMetaData     at maybeClose (internal/child_process.js:886:16)
30 silly fetchPackageMetaData     at Socket.<anonymous> (internal/child_process.js:342:11)
30 silly fetchPackageMetaData     at emitOne (events.js:96:13)
30 silly fetchPackageMetaData     at Socket.emit (events.js:188:7)
30 silly fetchPackageMetaData     at Pipe._handle.close [as _onclose] (net.js:501:12)
30 silly fetchPackageMetaData  error for salesforcemobilesdk-ios@git+https://github.com/forcedotcom/SalesforceMobileSDK-iOS.git#v5.1.0 { Error: Command failed: git clone --template=/Users/coopercher/.npm/_git-remotes/_templates --mirror https://github.com/forcedotcom/SalesforceMobileSDK-iOS.git /Users/coopercher/.npm/_git-remotes/git-https-github-com-forcedotcom-SalesforceMobileSDK-iOS-git-v5-1-0-b623d5a1
30 silly fetchPackageMetaData Cloning into bare repository '/Users/coopercher/.npm/_git-remotes/git-https-github-com-forcedotcom-SalesforceMobileSDK-iOS-git-v5-1-0-b623d5a1'...
30 silly fetchPackageMetaData error: RPC failed; curl 56 SSLRead() return error -9806
30 silly fetchPackageMetaData fatal: The remote end hung up unexpectedly
30 silly fetchPackageMetaData fatal: early EOF
30 silly fetchPackageMetaData fatal: index-pack failed
30 silly fetchPackageMetaData
30 silly fetchPackageMetaData     at ChildProcess.exithandler (child_process.js:204:12)
30 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
30 silly fetchPackageMetaData     at ChildProcess.emit (events.js:191:7)
30 silly fetchPackageMetaData     at maybeClose (internal/child_process.js:886:16)
30 silly fetchPackageMetaData     at Socket.<anonymous> (internal/child_process.js:342:11)
30 silly fetchPackageMetaData     at emitOne (events.js:96:13)
30 silly fetchPackageMetaData     at Socket.emit (events.js:188:7)
30 silly fetchPackageMetaData     at Pipe._handle.close [as _onclose] (net.js:501:12)
30 silly fetchPackageMetaData   killed: false,
30 silly fetchPackageMetaData   code: 128,
30 silly fetchPackageMetaData   signal: null,
30 silly fetchPackageMetaData   cmd: 'git clone --template=/Users/coopercher/.npm/_git-remotes/_templates --mirror https://github.com/forcedotcom/SalesforceMobileSDK-iOS.git /Users/coopercher/.npm/_git-remotes/git-https-github-com-forcedotcom-SalesforceMobileSDK-iOS-git-v5-1-0-b623d5a1' }
31 silly rollbackFailedOptional Starting
32 silly rollbackFailedOptional Finishing
33 silly runTopLevelLifecycles Finishing
34 silly install printInstalled
35 verbose stack Error: Command failed: git clone --template=/Users/coopercher/.npm/_git-remotes/_templates --mirror https://github.com/forcedotcom/SalesforceMobileSDK-iOS.git /Users/coopercher/.npm/_git-remotes/git-https-github-com-forcedotcom-SalesforceMobileSDK-iOS-git-v5-1-0-b623d5a1
35 verbose stack Cloning into bare repository '/Users/coopercher/.npm/_git-remotes/git-https-github-com-forcedotcom-SalesforceMobileSDK-iOS-git-v5-1-0-b623d5a1'...
35 verbose stack error: RPC failed; curl 56 SSLRead() return error -9806
35 verbose stack fatal: The remote end hung up unexpectedly
35 verbose stack fatal: early EOF
35 verbose stack fatal: index-pack failed
35 verbose stack
35 verbose stack     at ChildProcess.exithandler (child_process.js:204:12)
35 verbose stack     at emitTwo (events.js:106:13)
35 verbose stack     at ChildProcess.emit (events.js:191:7)
35 verbose stack     at maybeClose (internal/child_process.js:886:16)
35 verbose stack     at Socket.<anonymous> (internal/child_process.js:342:11)
35 verbose stack     at emitOne (events.js:96:13)
35 verbose stack     at Socket.emit (events.js:188:7)
35 verbose stack     at Pipe._handle.close [as _onclose] (net.js:501:12)
36 verbose cwd /Users/coopercher/demo1
37 error Darwin 16.3.0
38 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
39 error node v6.10.2
40 error npm  v3.10.10
41 error code 128
42 error Command failed: git clone --template=/Users/coopercher/.npm/_git-remotes/_templates --mirror https://github.com/forcedotcom/SalesforceMobileSDK-iOS.git /Users/coopercher/.npm/_git-remotes/git-https-github-com-forcedotcom-SalesforceMobileSDK-iOS-git-v5-1-0-b623d5a1
42 error Cloning into bare repository '/Users/coopercher/.npm/_git-remotes/git-https-github-com-forcedotcom-SalesforceMobileSDK-iOS-git-v5-1-0-b623d5a1'...
42 error error: RPC failed; curl 56 SSLRead() return error -9806
42 error fatal: The remote end hung up unexpectedly
42 error fatal: early EOF
42 error fatal: index-pack failed
43 error If you need help, you may report this error at:
43 error     <https://github.com/npm/npm/issues>
44 verbose exit [ 1, true ]

**Comment by legodude17** [comment]
Try updating `npm` and `git` to the latest version.
