### ISSUE TITLE
failed to fetch from registry: https://registry.npmjs.org

### ISSUE THREAD

**Issue by jfoclpf** [npm/npm#16648]
#### I'm opening this issue because:

  - [x] npm is crashing.

#### What's going wrong?

As I run `npm install --global gulp-cli` I get several errors of the type `npm ERR! fetch failed` regarding the domain `registry.npmjs.org` on port 443

#### How can the CLI team reproduce the problem?

`npm install --global gulp-cli` 

I'm on a shared server, thus just have access to my user folder

### supporting information:

![screenshot_smartselect_2017-05-17-11-15-02](https://cloud.githubusercontent.com/assets/3984909/26147115/ce6dcb14-3af2-11e7-89d2-fe8f4d017d6a.png)

#### What's the feature?

Installation of `gulp` globally

**Comment by legodude17** [comment]
Check your internet connection. Do you have a proxy or VPN?

**Comment by jfoclpf** [comment]
I have internet, I'm using the juice app for android. But now it works again :)

**Comment by KenanY** [comment]
Closing as resolved then.
