### ISSUE TITLE
AR Drone package not installing

### ISSUE THREAD

**Issue by TeacherAviation** [npm/npm#16640]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [X ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
ar-drone package is not installing properly

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - **Windows**, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

Log File

************************
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'ar-drone' ]
2 info using npm@4.2.0
3 info using node@v7.10.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData ar-drone
8 silly fetchNamedPackageData ar-drone
9 silly mapToRegistry name ar-drone
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'ar-drone',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'ar-drone',
12 silly mapToRegistry   name: 'ar-drone',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/ar-drone
14 verbose request uri https://registry.npmjs.org/ar-drone
15 verbose request no auth needed
16 info attempt registry request try #1 at 9:13:28 PM
17 verbose request id c53f3dc09654e27a
18 verbose etag W/"57080471-741b"
19 verbose lastModified Fri, 08 Apr 2016 19:20:17 GMT
20 http request GET https://registry.npmjs.org/ar-drone
21 http 304 https://registry.npmjs.org/ar-drone
22 verbose headers { date: 'Tue, 16 May 2017 11:13:28 GMT',
22 verbose headers   via: '1.1 varnish',
22 verbose headers   'cache-control': 'max-age=300',
22 verbose headers   etag: 'W/"57080471-741b"',
22 verbose headers   age: '128',
22 verbose headers   connection: 'keep-alive',
22 verbose headers   'x-served-by': 'cache-bne7722-BNE',
22 verbose headers   'x-cache': 'HIT',
22 verbose headers   'x-cache-hits': '1',
22 verbose headers   'x-timer': 'S1494933209.830248,VS0,VE1',
22 verbose headers   vary: 'Accept-Encoding' }
23 silly get cb [ 304,
23 silly get   { date: 'Tue, 16 May 2017 11:13:28 GMT',
23 silly get     via: '1.1 varnish',
23 silly get     'cache-control': 'max-age=300',
23 silly get     etag: 'W/"57080471-741b"',
23 silly get     age: '128',
23 silly get     connection: 'keep-alive',
23 silly get     'x-served-by': 'cache-bne7722-BNE',
23 silly get     'x-cache': 'HIT',
23 silly get     'x-cache-hits': '1',
23 silly get     'x-timer': 'S1494933209.830248,VS0,VE1',
23 silly get     vary: 'Accept-Encoding' } ]
24 verbose etag https://registry.npmjs.org/ar-drone from cache
25 verbose get saving ar-drone to D:\aread30\AppData\Roaming\npm-cache\registry.npmjs.org\ar-drone\.cache.json
26 verbose correctMkdir D:\aread30\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
27 silly install normalizeTree
28 silly loadCurrentTree Finishing
29 silly loadIdealTree Starting
30 silly install loadIdealTree
31 silly cloneCurrentTree Starting
32 silly install cloneCurrentTreeToIdealTree
33 silly cloneCurrentTree Finishing
34 silly loadShrinkwrap Starting
35 silly install loadShrinkwrap
36 silly loadShrinkwrap Finishing
37 silly loadAllDepsIntoIdealTree Starting
38 silly install loadAllDepsIntoIdealTree
39 silly rollbackFailedOptional Starting
40 silly rollbackFailedOptional Finishing
41 silly runTopLevelLifecycles Finishing
42 silly install printInstalled
43 verbose stack Error: Refusing to install package with name "ar-drone" under a package
43 verbose stack also called "ar-drone". Did you name your project the same
43 verbose stack as the dependency you're installing?
43 verbose stack
43 verbose stack For more information, see:
43 verbose stack     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>
43 verbose stack     at checkSelf (C:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:53:14)
43 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
43 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
43 verbose stack     at chain (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
43 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:16:5
43 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
43 verbose stack     at Array.forEach (native)
43 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
43 verbose stack     at Array.forEach (native)
43 verbose stack     at asyncMap (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
44 verbose cwd C:\node_modules\ar-drone
45 error Windows_NT 10.0.14393
46 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "ar-drone"
47 error node v7.10.0
48 error npm  v4.2.0
49 error code ENOSELF
50 error Refusing to install package with name "ar-drone" under a package
50 error also called "ar-drone". Did you name your project the same
50 error as the dependency you're installing?
50 error
50 error For more information, see:
50 error     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>
51 error If you need help, you may report this error at:
51 error     <https://github.com/npm/npm/issues>
52 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
As the error message states, you cannot install a package that has the same name as the package/project whose directory you are currently in. You are gonna have to rename your project to something other than `"ar-drone"` (and any of your other dependencies, too).

**Comment by TeacherAviation** [comment]
Sorry I am a Newbie.
Does that mean I have to change the folder name or edit the package.json file

************************{
  "_args": [
    [
      {
        "raw": "ar-drone",
        "scope": null,
        "escapedName": "ar-drone",
        "name": "ar-drone",
        "rawSpec": "",
        "spec": "latest",
        "type": "tag"
      },
      "C:\\"
    ],
    [
      {
        "raw": "ar-drone",
        "scope": null,
        "escapedName": "ar-drone",
        "name": null,
        "rawSpec": "ar-drone",
        "spec": "C:\\node_modules\\ar-drone",
        "type": "directory"
      },
      "C:\\node_modules"
************************************************

**Comment by jbcpollak** [comment]
@TeacherAviation - you need to modify your package.json to change the "name" to something else.

It looks like package.json you posted above is the one from the `ar-drone` package. When you are trying to install it you should be in a clean directory named something like `my-drone-program`. In that directory, you'd run `npm init` to create your own package.json file and give your project a name like `my-drone-program` (or whatever you want, but _not_ `ar-drone`). The directory and project names are the same by convention, its not a requirement.

Once you have your own package.json file, you can run `npm i --save ar-drone` to install the ar-drone library into your project. 

The key point for the error you are getting here is to make sure your own package.json does not have the name field set to `ar-drone`.
