### ISSUE TITLE
Can not install bluetooth-hci-socket npm package on Windows OS

### ISSUE THREAD

**Issue by kristijankrsteski** [npm/npm#16649]
NPM package bluetooth-hci-socket@0.5.1 can not be installed on Windows 10 OS with latest node and npm apps.
I try almost everything, but without luck.
Any help on this!

[npm-debug.zip](https://github.com/npm/npm/files/1007296/npm-debug.zip)

[npm-debug .zip](https://github.com/npm/npm/files/1007300/npm-debug.zip)

**Comment by KenanY** [comment]
Hello! Can you upload the log file as plaintext to <https://gist.github.com/> and link it here, instead of zipping it up? Thanks!
