### ISSUE TITLE
Error while installing using NPM Install for sax@0.6.1 - 407 error

### ISSUE THREAD

**Issue by munavargit** [npm/npm#16642]
#### I'm opening this issue because:

  - [ ] npm is crashing.

#### What's going wrong?

http fetch 407 http://registry.npmjs.org/sax/-/sax-0.6.1.tgz

#### How can the CLI team reproduce the problem?

When I do "npm install sax@0.6.1", I get the above error

### supporting information:
 75 http fetch GET http://registry.npmjs.org/sax/-/sax-0.6.1.tgz
76 http fetch 407 http://registry.npmjs.org/sax/-/sax-0.6.1.tgz
77 error fetch failed http://registry.npmjs.org/sax/-/sax-0.6.1.tgz
78 silly rollbackFailedOptional Starting
79 silly rollbackFailedOptional Finishing
80 silly runTopLevelLifecycles Finishing
81 silly install printInstalled
82 verbose stack Error: fetch failed with status code 407
82 verbose stack     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\fetch.js:51:14)
82 verbose stack     at emitOne (events.js:96:13)
82 verbose stack     at Request.emit (events.js:188:7)
82 verbose stack     at Request.onRequestResponse (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:954:10)
82 verbose stack     at emitOne (events.js:96:13)
82 verbose stack     at ClientRequest.emit (events.js:188:7)
82 verbose stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:473:21)
82 verbose stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
82 verbose stack     at Socket.socketOnData (_http_client.js:362:20)
82 verbose stack     at emitOne (events.js:96:13)
83 verbose cwd C:\Users\xmhussain62\AppData\Roaming\npm-cache\chokidar\1.7.0\package
84 error Windows_NT 6.3.9600
85 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "sax@0.6.1"

 - Windows, OS X/macOS, or Linux?: W8
 - Network issues:
   - Geographic location where npm was run:
  
   - [ ] I use a proxy to connect to the web.

**Comment by legodude17** [comment]
What are the results of:
1. `npm config get registry`
2. `npm config get http-proxy`
3. `npm config get https-proxy`

**Comment by munavargit** [comment]
#1. registry=http://registry.npmjs.org
#2 and #3: I have set web proxy server and IP.

In fact it is installing most of them, it breaks when I sax@0.6.1. Please let me know, I need more details

**Comment by legodude17** [comment]
What does `curl -O http://registry.npmjs.org/sax` do?

**Comment by munavargit** [comment]
Hey,

I appreciate your response.Sorry for the late reply.

Curl is not allowed in our environment, is there any other way to get
details? If not, I'll try get curl.

**Comment by legodude17** [comment]
`wget` or a web browser would also work

**Comment by munavargit** [comment]
HI Joshua,

Sure, thanks. On Monday from my problematic environment, I'll apply and
provide details.

Best Regards,
Munavar Hussain

**Comment by munavargit** [comment]
Hi Joshua,

When I browsed, http://registry.npmjs.org/sax, it provides huge .json. Do you expect something specifically in it?

**Comment by legodude17** [comment]
That means that it is probably a problem with npm not being configured for your proxy or your proxy for npm.

**Comment by munavargit** [comment]
Yes, I think, so.
