### ISSUE TITLE
npm not installing

### ISSUE THREAD

**Issue by ridkadri** [npm/npm#16656]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

-->
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@4.2.0
3 info using node@v7.10.0
4 verbose stack Error: missing script: start
4 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:151:19)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:61:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:356:5
4 verbose stack     at checkBinReferences_ (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:320:45)
4 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:354:3)
4 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:124:5)
4 verbose stack     at ReadFileContext.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:295:20)
4 verbose stack     at ReadFileContext.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16)
4 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:359:13)
5 verbose cwd C:\Users\RID\desktop\TurtleFacts
6 error Windows_NT 10.0.14393
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
8 error node v7.10.0
9 error npm  v4.2.0
10 error missing script: start
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

**Comment by mjschock** [comment]
@ridkadri - do you have a package.json with a start script or a server.js file?

http://stackoverflow.com/questions/31976722/start-script-missing-error-when-running-npm-start

**Comment by ridkadri** [comment]
Hello I have a package.json file but with no start script . I tried inserting the start in the package.json file but it doesnt allow me to save.

R. Kadri

________________________________

**Comment by KenanY** [comment]
Your text editor does not allow you to save your changes?

**Comment by ridkadri** [comment]
Yea it doesn’t save when I’m in the main .json file but it saves when I’m in my project .json file.

Also, none of my npms work. My live-server doesn’t work in my browser.

Please help

--

**Comment by KenanY** [comment]
@ridkadri Probably try a different text editor then.
