### ISSUE TITLE
npm install 

### ISSUE THREAD

**Issue by anandakumark89** [npm/npm#16655]
D:\Anand\AJS2\WorkSpace\AJS\Angular2>npm install
npm WARN deprecated angular-cli@1.0.0-beta.28.3: angular-cli has been renamed to @angular/cli. Please update your dependencies.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10

npm ERR! shasum check failed for C:\Users\30976\AppData\Local\Temp\npm-5400-3fa5ebdd\registry.npmjs.org\term-size\-\term-size-0.1.1.tgz
npm ERR! Expected: 87360b96396cab5760963714cda0d0cbeecad9ca
npm ERR! Actual:   8b7a0e3f95a3ae884793a76073abc6e975c58375
npm ERR! From:     http://registry.npmjs.org/term-size/-/term-size-0.1.1.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Anand\AJS2\WorkSpace\AJS\Angular2\npm-debug.log

D:\Anand\AJS2\WorkSpace\AJS\Angular2>exit

**Comment by KenanY** [comment]
Does this also occur with the latest stable version of `npm`?
