### ISSUE TITLE
errors with npm install

### ISSUE THREAD

**Issue by isabellewei** [npm/npm#16658]
I tried to run npm install hfc. I think the problem has something to do with node-pre-gyp. I've tried updating node, npm, xcode. I'm running macOS

The debug log won't show me anything above line 8004, not sure why
[debug_log.txt](https://github.com/npm/npm/files/1011640/debug_log.txt)

**Comment by legodude17** [comment]
Could you upload the npm-debug.log as a plaintext file to https://gist.github.com/ and post a link to it here?

**Comment by isabellewei** [comment]
https://gist.github.com/isabellewei/a5632a3956353d5b2b0d1130c9b20a81

**Comment by legodude17** [comment]
I would file an issue with `grpc` (npm bugs `grpc`).

**Comment by isabellewei** [comment]
Ok, I've done that. Will update this thread if I figure it out.
