### ISSUE TITLE
Having error in installing npm node modules

### ISSUE THREAD

**Issue by LMounika** [npm/npm#16651]
#### I'm opening this issue because:

  - [ ] npm is doing something I don't understand.

#### How can the CLI team reproduce the problem?

I am trying to run the command 
npm install node modules --save 
 It's working fine in my local machine but, when tring to run in vde its producing an error like:
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "node" "modules"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ECONNRESET

npm ERR! network tunneling socket could not be established, cause=getaddrinfo EN
OTFOUND proxy.company.com proxy.company.com:8080
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
C:\Test\npm-debug.log
### supporting information:

 - `npm -v` prints:v3.10.9
 - `node -v` prints:v6.9.2
 - `npm config get registry` prints:http://registry.npmjs.org/
 - Windows
[npm-debug.txt](https://github.com/npm/npm/files/1007482/npm-debug.txt)

**Comment by legodude17** [comment]
Update `npm` and ensure you have a stable internet connection.
