### ISSUE TITLE
unable to Execute this command        npm start --development   getting missing script error

### ISSUE THREAD

**Issue by padminismile** [npm/npm#16650]
**####** I'm opening this issue because:

**unable to Execute this command        npm start --development**

#### What's going wrong?

**getting missing script error**

#### How can the CLI team reproduce the problem?
**Steps:**
1) open the cmd with run as administrator option
2) Execute this command (*): npm install --development
3) next Execute this command: npm start --development
then you can able to see the error.

Please help me

![npm issue](https://cloud.githubusercontent.com/assets/28754028/26150071/6564394a-3b2f-11e7-9aae-96400a0484b8.png)

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by padminismile** [comment]
npm -v prints: **3.10.10**
node -v prints:  **6.9.5**
npm config get registry prints: **https://registry.npmjs.org/**
Windows, OS X/macOS, or Linux?: **Windows**
Network issues:
Geographic location where npm was run:
 I use a proxy to connect to the npm registry.
 I use a proxy to connect to the web.
 I use a proxy when downloading Git repos.
 I access the npm registry via a VPN
 I don't use a proxy, but have limited or unreliable internet access. **May be**
Container:
 I develop using Vagrant on Windows. **Windows**
 I develop using Vagrant on OS X or Linux.
 I develop / deploy using Docker.
 I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
Hello! So, the way `npm start` works is that it looks in your current `package.json` for a defined `"start"` [script](https://docs.npmjs.com/misc/scripts), and then runs that. The error message you're seeing is trying to tell you that you have not defined a `"start"` script in your `package.json`, hence `npm start` has no idea what you want it to do.

To solve this issue, all you have to do is add a new script to your `package.json`. It might look something like this, for example:

``` json
{
  "name": "package-name",
  "version": "1.0.0",
  "description": "package description",
  "scripts": {
    "start": "node --version",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {},
  "devDependencies": {}
}
```

Note how this `package.json` has a `"start"` script that runs `node --version`. You'll definitely want to change the command to whatever is most appropriate for your project.

Let me know if you run into any further `npm` issues :)

**Comment by padminismile** [comment]
Hi Kenan Yildirim,

I cannot able to resolve the issue by seeing this example.
Can you please tell me what should i add in the file and which place i need
to add.
AFter adding the script what should i do again.

Please explain step by step.

**Comment by KenanY** [comment]
How about you provide your `package.json` (you can upload it to <https://gist.github.com/> and post the link to it) and I can make the necessary changes for you? Feel free to remove any sensitive information from the file before uploading it.

(Small note, but don't send it as an email attachment because it doesn't actually show up on GitHub that way.)
