### ISSUE TITLE
npm ERR! Darwin 16.5.0

### ISSUE THREAD

**Issue by isabellewei** [npm/npm#16653]
I tried to run npm search,  this is the debug log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/7.10.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'search' ]
2 info using npm@4.2.0
3 info using node@v7.10.0
4 verbose config Skipping project config: /Users/iwei/.npmrc. (matches userconfig)
5 verbose stack Error: search must be called with arguments
5 verbose stack     at EventEmitter.search (/usr/local/lib/node_modules/npm/lib/search.js:35:15)
5 verbose stack     at Object.commandCache.(anonymous function) (/usr/local/lib/node_modules/npm/lib/npm.js:130:13)
5 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:77:30)
5 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:73:7)
5 verbose stack     at process._tickCallback (internal/process/next_tick.js:104:9)
6 verbose cwd /Users/iwei
7 error Darwin 16.5.0
8 error argv "/usr/local/Cellar/node/7.10.0/bin/node" "/usr/local/bin/npm" "search"
9 error node v7.10.0
10 error npm  v4.2.0
11 error search must be called with arguments
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]

**Comment by legodude17** [comment]
Calling `npm search` with no arguments will fail with that error message. What did you expect it to do?

**Comment by KenanY** [comment]
Closing since this is intentional behavior. If there's something you would like `npm search` (with no arguments) to do, just say so and we can possibly turn this into a feature request.
