### ISSUE TITLE
npm error Windows_NT 10.0.14393

### ISSUE THREAD

**Issue by georey** [npm/npm#16666]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Im trying to install socekt.io but some has problem
[npm-debug.log.txt](https://github.com/npm/npm/files/1015059/npm-debug.log.txt)

Thanks in advance

Regards

**Comment by legodude17** [comment]
Could you upload the npm-debug.log as a plaintext file to https://gist.github.com/ and post a link to it here?

**Comment by georey** [comment]
Sorry I already solved it, the problem was wrongly declared my package.json
