### ISSUE TITLE
NPM install error -  npm ERR! registry error parsing json

### ISSUE THREAD

**Issue by Sjain01** [npm/npm#16663]
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

D:\sjain\SDK\Node.js\connect-sdk-client-js-3.2.0>npm cache clear

D:\sjain\SDK\Node.js\connect-sdk-client-js-3.2.0>npm install
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\sjain\\SDK\\Node.js\\node.exe" "D:\\sjain\\SDK\\Node.js\\node
_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10

npm ERR! Unexpected token < in JSON at position 0
npm ERR! <html><head><title>Page Not Found</title><head><body>Sorry, but I could
n't find the object you requested.</body></html>
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\sjain\SDK\Node.js\connect-sdk-client-js-3.2.0\npm-debug.log

[npm log.txt](https://github.com/npm/npm/files/1014557/npm.log.txt)

**Comment by legodude17** [comment]
Try running `npm i -g npm@latest`.

**Comment by Sjain01** [comment]
Tried running the above command but again getting the same error. 


D:\sjain\SDK\Node.js\connect-sdk-client-js-3.2.0>npm i -g npm@latest
npm ERR! registry error parsing json
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\sjain\\SDK\\Node.js\\node.exe" "D:\\sjain\\SDK\\Node.js\\node
_modules\\npm\\bin\\npm-cli.js" "i" "-g" "npm@latest"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10

npm ERR! Unexpected token < in JSON at position 0
npm ERR! <html><head><title>Page Not Found</title><head><body>Sorry, but I could
n't find the object you requested.</body></html>
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\sjain\SDK\Node.js\connect-sdk-client-js-3.2.0\npm-debug.log

**Comment by liushaotian** [comment]
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\node\\node.exe" "D:\\node\\node_modules\\npm\\bin\\npm-cli.js
" "install" "express"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code UNABLE_TO_VERIFY_LEAF_SIGNATURE

npm ERR! unable to verify the first certificate
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     E:\nodeJS\blog\npm-debug.log

**Comment by legodude17** [comment]
Please update `npm` to the latest version.

**Comment by Sjain01** [comment]
Uninstalled the Node js and re-installed the latest version , still facing the same 'Error parsing Json' issue as commented above.

**Comment by liushaotian** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\node\\node.exe',
1 verbose cli 'D:\\node\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli 'install',
1 verbose cli '-g',
1 verbose cli 'npm' ]
2 info using npm@3.10.10
3 info using node@v6.10.3
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData npm
8 silly fetchNamedPackageData npm
9 silly mapToRegistry name npm
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npm.taobao.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry raw: 'npm',
12 silly mapToRegistry scope: null,
12 silly mapToRegistry escapedName: 'npm',
12 silly mapToRegistry name: 'npm',
12 silly mapToRegistry rawSpec: '',
12 silly mapToRegistry spec: 'latest',
12 silly mapToRegistry type: 'tag' }
13 silly mapToRegistry uri https://registry.npm.taobao.org/npm
14 verbose request uri https://registry.npm.taobao.org/npm
15 verbose request no auth needed
16 info attempt registry request try #1 at 09:00:40
17 verbose request id ac089d2b9da27db2
18 http request GET https://registry.npm.taobao.org/npm
19 info retry will retry, error on last attempt: Error: unable to verify the first certificate
20 info attempt registry request try #2 at 09:00:51
21 http request GET https://registry.npm.taobao.org/npm
22 info retry will retry, error on last attempt: Error: unable to verify the first certificate
23 info attempt registry request try #3 at 09:01:51
24 http request GET https://registry.npm.taobao.org/npm
25 silly fetchPackageMetaData Error: unable to verify the first certificate
25 silly fetchPackageMetaData at Error (native)
25 silly fetchPackageMetaData at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
25 silly fetchPackageMetaData at emitNone (events.js:86:13)
25 silly fetchPackageMetaData at TLSSocket.emit (events.js:185:7)
25 silly fetchPackageMetaData at TLSSocket._finishInit (_tls_wrap.js:610:8)
25 silly fetchPackageMetaData at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)
25 silly fetchPackageMetaData error for npm { Error: unable to verify the first certificate
25 silly fetchPackageMetaData at Error (native)
25 silly fetchPackageMetaData at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
25 silly fetchPackageMetaData at emitNone (events.js:86:13)
25 silly fetchPackageMetaData at TLSSocket.emit (events.js:185:7)
25 silly fetchPackageMetaData at TLSSocket._finishInit (_tls_wrap.js:610:8)
25 silly fetchPackageMetaData at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38) code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE' }
26 silly rollbackFailedOptional Starting
27 silly rollbackFailedOptional Finishing
28 silly runTopLevelLifecycles Finishing
29 silly install printInstalled
30 verbose stack Error: unable to verify the first certificate
30 verbose stack at Error (native)
30 verbose stack at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
30 verbose stack at emitNone (events.js:86:13)
30 verbose stack at TLSSocket.emit (events.js:185:7)
30 verbose stack at TLSSocket._finishInit (_tls_wrap.js:610:8)
30 verbose stack at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)
31 verbose cwd C:\windows\system32
32 error Windows_NT 6.1.7601
33 error argv "D:\\node\\node.exe" "D:\\node\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "npm"
34 error node v6.10.3
35 error npm v3.10.10
36 error code UNABLE_TO_VERIFY_LEAF_SIGNATURE
37 error unable to verify the first certificate
38 error If you need help, you may report this error at:
38 error <https://github.com/npm/npm/issues>
39 verbose exit [ 1, true ]

At 2017-05-23 00:41:17, "Joshua Bennett" <notifications@github.com> wrote:


Please update npm to the latest version.

**Comment by legodude17** [comment]
Try updating to npm@5
