### ISSUE TITLE
why? can't change  registry

### ISSUE THREAD

**Issue by cpphp** [npm/npm#16662]
[root@localhost ~]# npm install -g cnpm --registry=https://registry.npm.taobao.org
npm ERR! Linux 2.6.32-642.el6.i686
npm ERR! argv "/usr/local/node-v6.10.3/bin/node" "/usr/local/node-v6.10.3/bin/npm" "install" "-g" "cnpm" "--registry=https://registry.npm.taobao.org"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code CERT_NOT_YET_VALID

npm ERR! certificate is not yet valid
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log

**Comment by legodude17** [comment]
Try updating `npm` to the latest version.

**Comment by KenanY** [comment]
Is your system time configured correctly? My guess is that the clock is behind.
