### ISSUE TITLE
gulp-imagemin

### ISSUE THREAD

**Issue by amitsingh17051** [npm/npm#16672]
#### I'm opening this issue because:

im ahving an error in gulp-imagemin installation

npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\AMITSI~1\AppData\Local\Temp\npm-7436-94088fb3\registry.npmjs.org\os-tmpdir\-\os-tmpdir-1.0.2.tgz.2797714459' -> 'C:\Users\AMITSI~1\AppData\Local\Temp\npm-7436-94088fb3\registry.npmjs.org\os-tmpdir\-\os-tmpdir-1.0.2.tgz'
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save-dev" "gulp-imagemin"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\AMITSI~1\AppData\Local\Temp\npm-7436-94088fb3\registry.npmjs.org\uuid\-\uuid-2.0.3.tgz.3959311894' -> 'C:\Users\AMITSI~1\AppData\Local\Temp\npm-7436-94088fb3\registry.npmjs.org\uuid\-\uuid-2.0.3.tgz'
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save-dev" "gulp-imagemin"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by legodude17** [comment]
Try updating `npm`.

**Comment by amitsingh17051** [comment]
ok its working now
