### ISSUE TITLE
 Callback called more than once.

### ISSUE THREAD

**Issue by deepakchoudhary108** [npm/npm#16679]
I am getting below error when running npm install command.
I have tried following things before reporting the issue.

Opened command prompt as adminsitrator.
Turned off windows firewall.
used the npm registry.Tried changing it to http and https .Both none of them worked.
Please suggest.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\node installation\\node.exe" "D:\\node installation\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10

npm ERR! Callback called more than once.
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Github\partner-cnn\npm-debug.log

![githubissue](https://cloud.githubusercontent.com/assets/10204498/26307492/cbda4bfe-3eec-11e7-951f-64192ae4ac00.png)

**Comment by KenanY** [comment]
Does this also occur with newer versions of `npm`?

**Comment by deepakchoudhary108** [comment]
Yes.
Currently I am using node V7.10.0 and npm V4.2.0.
I have also tried running different nose version but still facing this
issue.
Please suggest.

Thanks,
Deepak Choudhary.

**Comment by legodude17** [comment]
Could you upload the new npm-debug.log (for the latest npm) as a plaintext file to https://gist.github.com/ and post a link to it here?

**Comment by kaleksandrov** [comment]
I get the same error with:

[ERROR] npm ERR! node v6.9.1¬
[ERROR] npm ERR! npm  v4.0.2¬

**Comment by legodude17** [comment]
@kaleksandrov Try using the latest version of npm.

**Comment by kaleksandrov** [comment]
The problem turned out to be a lack of permissions... Fixing the permissions on the directory solved the problem. The module that was requiring the permissions was ```node-sass```
