### ISSUE TITLE
new to angular and project clarity. What is the following error

### ISSUE THREAD

**Issue by bhaktibathia** [npm/npm#16670]
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code EREADFILE

npm ERR! Error extracting C:\Users\Blue Sky\AppData\Roaming\npm-cache\clarity-angular\0.9.4\package.tgz archive: ENOENT: no such file or directory, open 'C:\Users\Blue Sky\AppData\Roaming\npm-cache\clarity-angular\0.9.4\package.tgz'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\clarity-seed\npm-debug.log

**Comment by legodude17** [comment]
Does this occur on the latest version of `npm`?

**Comment by bhaktibathia** [comment]
Yes. I just installed npm a few days back

**Comment by legodude17** [comment]
Does this occur with npm@5?
