### ISSUE TITLE
Unknown command line argument should be fatal error

### ISSUE THREAD

**Issue by binki** [npm/npm#16678]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I’m passing a command line option to `npm install` that does not exist. I expect it to behave like other commands I use by exiting with a fatal error.

#### How can the CLI team reproduce the problem?

This demonstrates how `npm install` fails to exit with a fatal error when passing an unsupported argument:

```
ohnob@DESKTOP-A4G2C0J MSYS ~/repos/asdfrepo
$ npm install --this-is-not-a-supported-argument glob >/dev/null
npm WARN asdfrepo@1.0.0 No description
npm WARN asdfrepo@1.0.0 No repository field.

ohnob@DESKTOP-A4G2C0J MSYS ~/repos/asdfrepo
$ echo $?
0
```

I expected `FATAL` logs and a non-zero exit code.

This example shows me **thinking** that I was passing `-S` to `npm install` when in reality I was passing an unsupported option which is being ignored.

```
ohnob@DESKTOP-A4G2C0J MSYS ~/repos/asdfrepo
$ npm install -s rimraf >/dev/null

ohnob@DESKTOP-A4G2C0J MSYS ~/repos/asdfrepo
$ echo $?
0

ohnob@DESKTOP-A4G2C0J MSYS ~/repos/asdfrepo
$ grep -e rimraf package.json

ohnob@DESKTOP-A4G2C0J MSYS ~/repos/asdfrepo
$ echo $?
1
```

### supporting information:

 - `npm -v` prints: 3.10.10 , 4.6.1
 - `node -v` prints: v6.9.5 , 7.0.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows, Linux

**Comment by KenanY** [comment]
Previously: https://github.com/npm/npm/issues/10047 and https://github.com/npm/npm/issues/14396

(nit: `-s` is a valid flag (alias for `--silent`))

**Comment by binki** [comment]
> (nit: `-s` is a valid flag (alias for `--silent`))

Ah, that explains some things. Interesting how verbose silent mode is. I’ve checked `npm -h` before and not seen it:

```
ohnobinki@gibby ~/npmfun $ ./node_modules/.bin/npm -h | grep -e -s
    explore, get, help, help-search, i, init, install,
    rebuild, repo, restart, root, run, run-script, s, se,
ohnobinki@gibby ~/npmfun $ ./node_modules/.bin/npm -l | grep -e -s
    adduser      npm adduser [--registry=url] [--scope=@orgname] [--auth-type=legacy] [--always-auth]
    help-search  npm help-search <text>
                 common options: [--save|--save-dev|--save-optional] [--save-exact]
    logout       npm logout [--registry=<url>] [--scope=<@scope>]
    run-script   npm run-script <command> [-- <args>...]
    uninstall    npm uninstall [<@scope>/]<pkg>[@<version>]... [--save|--save-dev|--save-optional]
```

I guess I need to open another bug then…

But, regardless, I expect unsupported/invalid parameters to cause a command to cause a fatal error rather than `npm` charging ahead with a behavior that the user did not intend (due to, e.g., a typo).
