### ISSUE TITLE
ERR getaddrinfo EAI_AGAIN registry.npmjs.org:443

### ISSUE THREAD

**Issue by MrJety** [npm/npm#16681]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.

#### What's going wrong?

Can't install Chart.js with npm...
everytime i try i get

ERR! node v7.10.0
ERR! npm v4.2.0
ERR! code EAI_AGAIN
ERR! errno EAI_AGAIN
ERR! syscall getaddrinfo

ERR! getaddrinfo EAI_AGAIN registry.npmjs.org:443

### supporting information:

 - `npm -v` prints: 4.2.0
 - `node -v` prints: 7.10.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows 7 64x
 - Network issues:
   - Geographic location where npm was run:
   - using our corporates internet connection, could be that there is a proxy or something else
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).
   - [x] I don't use any deploying or virtualization tool 

for more details you could take a look inside the log file.

**Comment by legodude17** [comment]
Could you upload the npm-debug.log as a plaintext file to https://gist.github.com/ and post a link to it here?

**Comment by MrJety** [comment]
Here it is: [](https://gist.github.com/anonymous/404ee3a174779ee32be46341a7e79b61)
