### ISSUE TITLE
unable to install my own published package in npm registry. Error finding main.js

### ISSUE THREAD

**Issue by rasik210** [npm/npm#16688]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I have a published package named "newtestmay" under my npm account. When I try to install it on my machine it fails with below mentioned error.

npm ERR! enoent ENOENT: no such file or directory, chmod 'D:\learnnodejs\math_use
r\node_modules\newtestmay\main.js'

On the other hand if I try to install any other publicly available packages like "lodash", then they install successfully.

#### How can the CLI team reproduce the problem?

just run this command "npm install newtestmay" and you will get the same error.

### supporting information:

 - `npm -v` prints: 3.10.8
 - `node -v` prints: v6.9.1
 - `npm config get registry` prints: http://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
I think you want to do:

```
  "bin": {
    "mathexample22may": "bin/main.js"
  },
```

instead of

```
  "bin": {
    "mathexample22may": "main.js"
  },
```

in your package's `package.json`. Could you try making this change and publishing a new version?

**Comment by rasik210** [comment]
Thank you for the quick response. You were right! This was the issue. Appreciate your help. Now I'm successfully able to install the package I published after changing the "bin" path. I need to send an erratum note to the book publishers which I'm referring currently :).
