### ISSUE TITLE
npm -h (help) and -l (usage) output does not describe all command options.

### ISSUE THREAD

**Issue by binki** [npm/npm#16680]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

When I run `npm -h` or `npm -l`, I do not see an explanation of the [`-s` flag](https://github.com/npm/npm/issues/16678#issuecomment-303110086). I expect an exhaustive list of global options including, e.g., `-s` and other global options which I would have to read the source code to find.

#### How can the CLI team reproduce the problem?

Run `npm -h` or `npm -l` and search the output for a description of `-s` and other global options as foudn when reading the source.

Standard CLI practice for programs which support `-h` as a “help” switch is to list all global flags in the help output. For example:

```
ohnobinki@gibby ~/npmfun $ bunzip2 -h 2>&1 | grep -e '^ *-h'
   -h --help           print this message
```

When I try looking up the first line of description for `-s` I find nothing:

```
ohnobinki@gibby ~/npmfun $ ./node_modules/.bin/npm -h 2>&1 | grep -e '^ *-s'
```

### supporting information:

 - `npm -v` prints: 4.6.1
 - `node -v` prints: 7.0.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows, Linux

**Comment by xyleen** [comment]
Any chance this issue will be addressed? IMHO this shouldn't be closed, as this issue is still relevant (npm@5.4.1).

It would be nice to have all the npm flags documented in the npm help. My use-case: `npm install -h` does not explain that I can use the `--no-package-lock` flag.
