### ISSUE TITLE
npm ERR! user roshnanazar@gmail.com is not allowed to access package @progress/kendo-angular-grid : @progress/kendo-angular-grid

### ISSUE THREAD

**Issue by roshnanazar** [npm/npm#16689]
#### I'm opening this issue because:

  - [x] npm is producing an incorrect install.

root@tlttvmlt54:/home/ubuntu/kento-grid# npm view @progress/kendo-angular-grid versions
npm ERR! Linux 4.10.0-19-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "view" "@progress/kendo-angular-grid" "versions"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code E403

npm ERR! user roshnanazar@gmail.com is not allowed to access package @progress/kendo-angular-grid : @progress/kendo-angular-grid

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
I suggest [bringing this up with Telerik themselves](https://www.telerik.com/account/support-tickets/contact-support-team?pid=1800), as suggested by one of their developers (see https://github.com/npm/npm/issues/14197#issuecomment-288050641).
