### ISSUE TITLE
NPM doesn't follow semver

### ISSUE THREAD

**Issue by zimbatm** [npm/npm#16698]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?

NPM doesn't follow semver, it doesn't support the metadata part of the version. Ref: http://semver.org/#spec-item-10

#### How can the CLI team reproduce the problem?

```
$ npm version --no-git-tag-version "1.0.4+foobar"
v1.0.4
$ jq -r .version < package.json 
1.0.4
```

I expected the version to be `1.0.4+foobar` according to semver.org.

If I set the version manually and `npm publish`, the same stripping is happening.

### supporting information:

 - `npm -v` prints: `4.2.0`
 - `node -v` prints: `v7.9.0`
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?: macOS

**Comment by zkat** [comment]
This is a direct result of [`node-semver`](https://github.com/npm/node-semver) wiping the build section when parsing. npm (rightfully, imo) [called `semver.valid()` on `argv[0]`](https://github.com/npm/npm/blob/latest/lib/version.js#L44), which seems to be dropping this as part of its process.

I believe it's better for you to make your case on this with `node-semver` itself, and note that it has its own open issue about filling out support for build versions: https://github.com/npm/node-semver/issues/174

If it gets added to that project, you'll get that automatically on npm's next update. As such, I'm going to close this 'cause npm basically considers node-semver to be its reference spec.

**Comment by zimbatm** [comment]
thanks @zkat, this is a fantastic response!
