### ISSUE TITLE
facing issue in installation of package

### ISSUE THREAD

**Issue by jitendragupta2** [npm/npm#16693]
#### I'm opening this issue because:
Hello Kiera Manion-Fischer,
Thanks for your help.
Yes I have already published my package with command : npm publish <package name>
Now I am trying to install it. After installing with command : npm install <package name>
Only node_modules folder is generated. There is a folder inside node_modules which has name of my package. Which contains package.json
Please help me. So that I can generated proper folder structure which h I had during publishing of my package.

For your reference: I have created my package leveraging  angular-cli package.

Also it would be helpful if you can suggest any methodology which can speed up my installation , currently installation takes too much time for me.

Thanks,
Jitendra Gupta

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
It is unclear to me what the issue is here. Does the installed module _only_
contain the `package.json`? What other files would you like to see? What does
your `package.json` look like? What is the output of `npm --version` (the issue
template asks for this but you did not provide it)?

**Comment by jitendragupta2** [comment]
Hello,
I am getting below error on installing my package.

npm WARN enoent ENOENT: no such file or directory, open 'D:\mypackage\package.json'
npm WARN mypackage No description
npm WARN mypackage No repository field.
npm WARN mypackage No README data
npm WARN mypackage No license field.

When I had published my package it was having package.json

Thanks,
Jitendra Gupta

**Comment by KenanY** [comment]
That is a warning, not an error. It is simply warning you that you are installing `npm` packages, but the project directory you are currently in does not contain a `package.json`. It is not necessary to have a `package.json` just to install modules, hence why this is only a warning. The installation appears to have succeeded so I don't see an issue here.

**Comment by jitendragupta2** [comment]
Hello,
Issue over here is, there is only node_modules folder created. How should I start my development? It is not having folder structure which I had published. Where are my other files?

Thanks,
Jitendra Gupta

**Comment by KenanY** [comment]
`node_modules/` is the directory that `npm` installs packages into. If you don't want your files to go into that directory, then publishing those files as a package is probably not what you actually wanna do.

**Comment by jitendragupta2** [comment]
Really appreciate yourself.
How should i publish my package?
I deleted the node_modules folder and then published but after installation it automatically creates node_modules.
My expectaion after installation is i should have proper folder structure with all config files in root folder. Please help me.
Just For your reference: i have created my project using angular-cli



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by KenanY** [comment]
Sounds like you're making a boilerplate angular project? Might wanna look at making a [yeoman generator](http://yeoman.io/), or write your own tool that will generate those files in the user's current directory.
