### ISSUE TITLE
NPM CTLM 401

### ISSUE THREAD

**Issue by Carsten64** [npm/npm#16697]
I am working behind a proxy and try to access a private repository in a nexus. The .npmc is configures like this:

```
proxy=http://localhost:3128
https-proxy=http://localhost:3128
registry=http://repo......
strict-ssl=false
always-auth=true
_auth=[AUTH-STRING base64]
email=[EMAIL]
loglevel=silly
```
But I get a 401 Unauthoried Error. I checked already the authentification and it worked.

**Comment by hezedu** [comment]
rename `.npmc` to `.npmrc`
