### ISSUE TITLE
npm install errors

### ISSUE THREAD

**Issue by ANDMIC1** [npm/npm#16699]
[log.pdf](https://github.com/npm/npm/files/1023120/log.pdf)

#### I'm opening this issue because:

  - [ ] npm is producing an EER! during install.

#### What's going wrong?
I'm getting errors during the install of google-places-data. 

#### How can the CLI team reproduce the problem?

npm install google-places-data
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "google-places-data"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ENOSELF

npm ERR! Refusing to install google-places-data as a dependency of itself
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Drew/Desktop/google-places-master/npm-debug.log

### supporting information:
Using this git hub thread - https://github.com/peledies/google-places

**Comment by KenanY** [comment]
`npm` won't allow you to install the `google-places-data` package while your in said package's source directory. Doing so might imply that the package depends on itself. What you probably wanna do is `cd` into your own project and install the package from there for use in your project.
