### ISSUE TITLE
Problem in installation ionic and cordova

### ISSUE THREAD

**Issue by LeviMacario** [npm/npm#16709]
MacBook-Pro-de-Levi-Macario:ionic MacBook$ cat /Users/MacBook/.npm/_logs/2017-05-24T20_27_43_206Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'ionic@2.2.3',
1 verbose cli   'cordova@6.5.0' ]
2 info using npm@4.2.0
3 info using node@v6.10.3
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData ionic@2.2.3
8 silly fetchPackageMetaData cordova@6.5.0
9 silly fetchNamedPackageData ionic
10 silly mapToRegistry name ionic
11 silly mapToRegistry using default registry
12 silly mapToRegistry registry https://registry.npmjs.org/
13 silly mapToRegistry data Result {
13 silly mapToRegistry   raw: 'ionic',
13 silly mapToRegistry   scope: null,
13 silly mapToRegistry   escapedName: 'ionic',
13 silly mapToRegistry   name: 'ionic',
13 silly mapToRegistry   rawSpec: '',
13 silly mapToRegistry   spec: 'latest',
13 silly mapToRegistry   type: 'tag' }
14 silly mapToRegistry uri https://registry.npmjs.org/ionic
15 silly fetchNamedPackageData cordova
16 silly mapToRegistry name cordova
17 silly mapToRegistry using default registry
18 silly mapToRegistry registry https://registry.npmjs.org/
19 silly mapToRegistry data Result {
19 silly mapToRegistry   raw: 'cordova',
19 silly mapToRegistry   scope: null,
19 silly mapToRegistry   escapedName: 'cordova',
19 silly mapToRegistry   name: 'cordova',
19 silly mapToRegistry   rawSpec: '',
19 silly mapToRegistry   spec: 'latest',
19 silly mapToRegistry   type: 'tag' }
20 silly mapToRegistry uri https://registry.npmjs.org/cordova
21 verbose request uri https://registry.npmjs.org/cordova
22 verbose request no auth needed
23 info attempt registry request try #1 at 17:26:32
24 verbose request id bb3becdf01c8e076
25 http request GET https://registry.npmjs.org/cordova
26 verbose request uri https://registry.npmjs.org/ionic
27 verbose request no auth needed
28 info attempt registry request try #1 at 17:26:32
29 verbose etag W/"5924b129-14213f"
30 verbose lastModified Tue, 23 May 2017 22:01:13 GMT
31 http request GET https://registry.npmjs.org/ionic
32 info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND proxy proxy:80
33 info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND proxy proxy:80
34 info attempt registry request try #2 at 17:26:42
35 http request GET https://registry.npmjs.org/cordova
36 info attempt registry request try #2 at 17:26:42
37 verbose etag W/"5924b129-14213f"
38 verbose lastModified Tue, 23 May 2017 22:01:13 GMT
39 http request GET https://registry.npmjs.org/ionic
40 info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND proxy proxy:80
41 info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND proxy proxy:80
42 info attempt registry request try #3 at 17:27:42
43 http request GET https://registry.npmjs.org/cordova
44 info attempt registry request try #3 at 17:27:42
45 verbose etag W/"5924b129-14213f"
46 verbose lastModified Tue, 23 May 2017 22:01:13 GMT
47 http request GET https://registry.npmjs.org/ionic
48 silly fetchPackageMetaData Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND proxy proxy:80
48 silly fetchPackageMetaData     at ClientRequest.onError (/usr/local/lib/node_modules/npm/node_modules/request/node_modules/tunnel-agent/index.js:176:17)
48 silly fetchPackageMetaData     at ClientRequest.g (events.js:292:16)
48 silly fetchPackageMetaData     at emitOne (events.js:96:13)
48 silly fetchPackageMetaData     at ClientRequest.emit (events.js:188:7)
48 silly fetchPackageMetaData     at Socket.socketErrorListener (_http_client.js:309:9)
48 silly fetchPackageMetaData     at emitOne (events.js:96:13)
48 silly fetchPackageMetaData     at Socket.emit (events.js:188:7)
48 silly fetchPackageMetaData     at connectErrorNT (net.js:1021:8)
48 silly fetchPackageMetaData     at _combinedTickCallback (internal/process/next_tick.js:80:11)
48 silly fetchPackageMetaData     at process._tickCallback (internal/process/next_tick.js:104:9)
48 silly fetchPackageMetaData  error for cordova@6.5.0 { Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND proxy proxy:80
48 silly fetchPackageMetaData     at ClientRequest.onError (/usr/local/lib/node_modules/npm/node_modules/request/node_modules/tunnel-agent/index.js:176:17)
48 silly fetchPackageMetaData     at ClientRequest.g (events.js:292:16)
48 silly fetchPackageMetaData     at emitOne (events.js:96:13)
48 silly fetchPackageMetaData     at ClientRequest.emit (events.js:188:7)
48 silly fetchPackageMetaData     at Socket.socketErrorListener (_http_client.js:309:9)
48 silly fetchPackageMetaData     at emitOne (events.js:96:13)
48 silly fetchPackageMetaData     at Socket.emit (events.js:188:7)
48 silly fetchPackageMetaData     at connectErrorNT (net.js:1021:8)
48 silly fetchPackageMetaData     at _combinedTickCallback (internal/process/next_tick.js:80:11)
48 silly fetchPackageMetaData     at process._tickCallback (internal/process/next_tick.js:104:9) code: 'ECONNRESET' }
49 silly get cb [ 304, undefined ]
50 verbose etag https://registry.npmjs.org/ionic from cache
51 verbose get saving ionic to /Users/MacBook/.npm/registry.npmjs.org/ionic/.cache.json
52 verbose correctMkdir /Users/MacBook/.npm correctMkdir not in flight; initializing
53 silly pickManifestFromRegistryMetadata spec 2.2.3 tag latest versions [ '0.9.6',
53 silly pickManifestFromRegistryMetadata   '0.9.8',
53 silly pickManifestFromRegistryMetadata   '0.9.9',
53 silly pickManifestFromRegistryMetadata   '0.9.10',
53 silly pickManifestFromRegistryMetadata   '0.9.11',
53 silly pickManifestFromRegistryMetadata   '0.9.12',
53 silly pickManifestFromRegistryMetadata   '0.9.13',
53 silly pickManifestFromRegistryMetadata   '0.9.14',
53 silly pickManifestFromRegistryMetadata   '0.9.15',
53 silly pickManifestFromRegistryMetadata   '0.9.16',
53 silly pickManifestFromRegistryMetadata   '1.0.0-beta.1',
53 silly pickManifestFromRegistryMetadata   '1.0.0-beta',
53 silly pickManifestFromRegistryMetadata   '1.0.1-beta',
53 silly pickManifestFromRegistryMetadata   '1.0.3-beta',
53 silly pickManifestFromRegistryMetadata   '1.0.4',
53 silly pickManifestFromRegistryMetadata   '1.0.5',
53 silly pickManifestFromRegistryMetadata   '1.0.6',
53 silly pickManifestFromRegistryMetadata   '1.0.7',
53 silly pickManifestFromRegistryMetadata   '1.0.8',
53 silly pickManifestFromRegistryMetadata   '1.0.9',
53 silly pickManifestFromRegistryMetadata   '1.0.10',
53 silly pickManifestFromRegistryMetadata   '1.0.11',
53 silly pickManifestFromRegistryMetadata   '1.0.12',
53 silly pickManifestFromRegistryMetadata   '1.0.13',
53 silly pickManifestFromRegistryMetadata   '1.0.14',
53 silly pickManifestFromRegistryMetadata   '1.0.15',
53 silly pickManifestFromRegistryMetadata   '1.0.16',
53 silly pickManifestFromRegistryMetadata   '1.0.17',
53 silly pickManifestFromRegistryMetadata   '1.1.0-beta1',
53 silly pickManifestFromRegistryMetadata   '1.1.0-beta2',
53 silly pickManifestFromRegistryMetadata   '1.1.0-beta3',
53 silly pickManifestFromRegistryMetadata   '1.1.0-beta4',
53 silly pickManifestFromRegistryMetadata   '1.1.0-beta5',
53 silly pickManifestFromRegistryMetadata   '1.1.0-beta6',
53 silly pickManifestFromRegistryMetadata   '1.1.0',
53 silly pickManifestFromRegistryMetadata   '1.1.1-beta1',
53 silly pickManifestFromRegistryMetadata   '1.1.1-beta2',
53 silly pickManifestFromRegistryMetadata   '1.1.1-beta3',
53 silly pickManifestFromRegistryMetadata   '1.1.1',
53 silly pickManifestFromRegistryMetadata   '1.1.3',
53 silly pickManifestFromRegistryMetadata   '1.1.4',
53 silly pickManifestFromRegistryMetadata   '1.1.5-beta1',
53 silly pickManifestFromRegistryMetadata   '1.1.5-beta2',
53 silly pickManifestFromRegistryMetadata   '1.1.5-beta3',
53 silly pickManifestFromRegistryMetadata   '1.1.5-beta4',
53 silly pickManifestFromRegistryMetadata   '1.1.5-beta5',
53 silly pickManifestFromRegistryMetadata   '1.1.5',
53 silly pickManifestFromRegistryMetadata   '1.1.6',
53 silly pickManifestFromRegistryMetadata   '1.1.7-beta1',
53 silly pickManifestFromRegistryMetadata   '1.1.7',
53 silly pickManifestFromRegistryMetadata   '1.1.8-beta1',
53 silly pickManifestFromRegistryMetadata   '1.1.8-beta2',
53 silly pickManifestFromRegistryMetadata   '1.1.8-beta3',
53 silly pickManifestFromRegistryMetadata   '1.1.8-beta4',
53 silly pickManifestFromRegistryMetadata   '1.1.8-beta5',
53 silly pickManifestFromRegistryMetadata   '1.1.8',
53 silly pickManifestFromRegistryMetadata   '1.1.9-beta1',
53 silly pickManifestFromRegistryMetadata   '1.1.9',
53 silly pickManifestFromRegistryMetadata   '1.1.10',
53 silly pickManifestFromRegistryMetadata   '1.1.11-beta1',
53 silly pickManifestFromRegistryMetadata   '1.1.11-beta2',
53 silly pickManifestFromRegistryMetadata   '1.1.11',
53 silly pickManifestFromRegistryMetadata   '1.1.12-beta1',
53 silly pickManifestFromRegistryMetadata   '1.1.12-beta2',
53 silly pickManifestFromRegistryMetadata   '1.1.12-beta3',
53 silly pickManifestFromRegistryMetadata   '1.1.12',
53 silly pickManifestFromRegistryMetadata   '1.1.13',
53 silly pickManifestFromRegistryMetadata   '1.1.14-beta1',
53 silly pickManifestFromRegistryMetadata   '1.1.14-beta2',
53 silly pickManifestFromRegistryMetadata   '1.1.14-beta3',
53 silly pickManifestFromRegistryMetadata   '1.2.0-beta1',
53 silly pickManifestFromRegistryMetadata   '1.2.0',
53 silly pickManifestFromRegistryMetadata   '1.2.1-beta1',
53 silly pickManifestFromRegistryMetadata   '1.2.1-beta2',
53 silly pickManifestFromRegistryMetadata   '1.2.1-beta3',
53 silly pickManifestFromRegistryMetadata   '1.2.1-beta4',
53 silly pickManifestFromRegistryMetadata   '1.2.1',
53 silly pickManifestFromRegistryMetadata   '1.2.2',
53 silly pickManifestFromRegistryMetadata   '1.2.3-beta1',
53 silly pickManifestFromRegistryMetadata   '1.2.3-beta2',
53 silly pickManifestFromRegistryMetadata   '1.2.3-beta3',
53 silly pickManifestFromRegistryMetadata   '1.2.3',
53 silly pickManifestFromRegistryMetadata   '1.2.4-beta1',
53 silly pickManifestFromRegistryMetadata   '1.2.4-beta2',
53 silly pickManifestFromRegistryMetadata   '1.2.4-beta3',
53 silly pickManifestFromRegistryMetadata   '1.2.4',
53 silly pickManifestFromRegistryMetadata   '1.2.5-beta1',
53 silly pickManifestFromRegistryMetadata   '1.2.5-beta2',
53 silly pickManifestFromRegistryMetadata   '1.2.5-beta3',
53 silly pickManifestFromRegistryMetadata   '1.2.5',
53 silly pickManifestFromRegistryMetadata   '1.2.6-beta1',
53 silly pickManifestFromRegistryMetadata   '1.2.6-beta2',
53 silly pickManifestFromRegistryMetadata   '1.2.6-beta3',
53 silly pickManifestFromRegistryMetadata   '1.2.6',
53 silly pickManifestFromRegistryMetadata   '1.2.7',
53 silly pickManifestFromRegistryMetadata   '1.2.8-beta1',
53 silly pickManifestFromRegistryMetadata   '1.2.8-beta2',
53 silly pickManifestFromRegistryMetadata   '1.2.8',
53 silly pickManifestFromRegistryMetadata   '1.2.9',
53 silly pickManifestFromRegistryMetadata   '1.2.10',
53 silly pickManifestFromRegistryMetadata   ... 435 more items ]
54 silly rollbackFailedOptional Starting
55 verbose stack TypeError: Cannot read property 'path' of null
55 verbose stack     at Object.Installer.rollbackFailedOptional (/usr/local/lib/node_modules/npm/lib/install.js:511:29)
55 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
55 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
55 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
55 verbose stack     at /usr/local/lib/node_modules/npm/lib/install.js:337:5
55 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
55 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
55 verbose stack     at chain (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
55 verbose stack     at /usr/local/lib/node_modules/npm/lib/install.js:294:5
55 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:16:22
56 verbose cwd /Users/MacBook/workspace/Inovacoes Criativas/ionic
57 error Darwin 16.5.0
58 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "ionic@2.2.3" "cordova@6.5.0"
59 error node v6.10.3
60 error npm  v4.2.0
61 error Cannot read property 'path' of null
62 error If you need help, you may report this error at:
62 error     <https://github.com/npm/npm/issues>
63 verbose exit [ 1, true ]

**Comment by piotrowski** [comment]
Did you set a proxy of "proxy:80"? It doesn't seem to exist, so npm can't connect to it.
