### ISSUE TITLE
cannot install CLI

### ISSUE THREAD

**Issue by davidfu24** [npm/npm#16701]
#### I'm opening this issue because:

  - [y
[npm-debug.txt](https://github.com/npm/npm/files/1023455/npm-debug.txt)
[npm-debug.txt](https://github.com/npm/npm/files/1023456/npm-debug.txt)

 ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by aidenkeating** [comment]
@davidfu24 This appears to be covered in the Troubleshooting section of the wiki https://github.com/npm/npm/wiki/Troubleshooting#ssl-error.

There is a blog post linked there suggesting what to do if you encounter this error http://blog.npmjs.org/post/78085451721/npms-self-signed-certificate-is-no-more: Update npm version (`npm install npm -g --ca=null`) or tell current npm to use known registrars (`npm config set ca=""`).

If this does not resolve the issue you may be using an SSL-intercepting proxy (e.g. Anti-Virus Software). To resolve this setting `strict-ssl` config to false should resolve this (`npm config set strict-ssl false`).

Would you mind trying to follow the troubleshooting guide above (or commands provided) and see whether any of the suggested actions resolve the issue you're seeing?
