### ISSUE TITLE
Problema ao instalar ionic e cordova

### ISSUE THREAD

**Issue by LeviMacario** [npm/npm#16708]
--> MacBook-Pro-de-Levi-Macario:ionic MacBook$ sudo npm install -g ionic@2.2.3 cordova@6.5.0
npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "ionic@2.2.3" "cordova@6.5.0"
npm ERR! node v6.10.3
npm ERR! npm  v4.2.0

npm ERR! Cannot read property 'path' of null
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/MacBook/.npm/_logs/2017-05-24T20_12_22_149Z-debug.log
MacBook-Pro-de-Levi-Macario:ionic MacBook$ node -v
v6.10.3
MacBook-Pro-de-Levi-Macario:ionic MacBook$ npm -v
4.2.0

como consigo resolver esse problema?

**Comment by KenanY** [comment]
I'm gonna close this in favor of your newer issue, https://github.com/npm/npm/issues/16709, which has the full debug log.
