### ISSUE TITLE
missing script: brunch:start and missing script: webpack:start

### ISSUE THREAD

**Issue by BryanSingh** [npm/npm#16705]
Not sure why these errors are occurring with node npm: 

> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/local/Cellar/node/7.10.0/bin/node',
> 1 verbose cli   '/usr/local/bin/npm',
> 1 verbose cli   'run',
> 1 verbose cli   'brunch:start' ]
> 2 info using npm@4.2.0
> 3 info using node@v7.10.0
> 4 verbose stack Error: missing script: brunch:start
> 4 verbose stack     at run (/usr/local/lib/node_modules/npm/lib/run-script.js:151:19)
> 4 verbose stack     at /usr/local/lib/node_modules/npm/lib/run-script.js:61:5
> 4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:356:5
> 4 verbose stack     at checkBinReferences_ (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:320:45)
> 4 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:354:3)
> 4 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:124:5)
> 4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:243:12
> 4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
> 4 verbose stack     at tryToString (fs.js:449:3)
> 4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:436:12)
> 5 verbose cwd /Users/bryansingh/dev/Rails/wallet/main_site
> 6 error Darwin 16.3.0
> 7 error argv "/usr/local/Cellar/node/7.10.0/bin/node" "/usr/local/bin/npm" "run" "brunch:start"
> 8 error node v7.10.0
> 9 error npm  v4.2.0
> 10 error missing script: brunch:start
> 11 error If you need help, you may report this error at:
> 11 error     <https://github.com/npm/npm/issues>
> 12 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
Hello! So, the way `npm run brunch:start` works is that it looks in your current `package.json` for a defined `"brunch:start"` [script](https://docs.npmjs.com/misc/scripts), and then runs that. The error message you're seeing is trying to tell you that you have not defined a `"brunch:start"` script in your `package.json`, hence `npm run brunch:start` has no idea what you want it to do.

To solve this issue, all you have to do is add a new script to your `package.json`. It might look something like this, for example:

``` json
{
  "name": "package-name",
  "version": "1.0.0",
  "description": "package description",
  "scripts": {
    "brunch:start": "node --version",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {},
  "devDependencies": {}
}
```

Note how this `package.json` has a `"brunch:start"` script that runs `node --version`. You'll definitely want to change the command to whatever is most appropriate for your project.

Let me know if you run into any further `npm` issues :)
