### ISSUE TITLE
 'npm — global' is not in the npm registry.

### ISSUE THREAD

**Issue by pratimaupadhyay02** [npm/npm#16704]
#### I'm opening this issue because:

npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'npm — global' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 4.2.0-16-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "npm — global"
npm ERR! cwd /home/pratima
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! code E404
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pratima/npm-debug.log
npm ERR! not ok code 0

#### Is this a feature you're prepared to implement, with support from the npm CLI team?

-->

**Comment by aidenkeating** [comment]
@pratimaupadhyay02 Are you sure you didn't mean to execute `npm install npm --global` (Notice the space between `npm` and `--global`)?

**Comment by pratimaupadhyay02** [comment]
Oh! Thankyou so much! It's working.

**Comment by aidenkeating** [comment]
Perfect! 👍 Could you close this issue if it is now resolved?

**Comment by pratimaupadhyay02** [comment]
Sure :)
