### ISSUE TITLE
npm5 5.0.0-beta.58: install fails with HTTP 503

### ISSUE THREAD

**Issue by mderriey** [npm/npm#16702]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [X] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### How can the CLI team reproduce the problem?

[Here's a gist](https://gist.github.com/mderriey/4f59978c99c4ca1edff7c6e1d6f81994) of both the `package.json` and the `npm-debug.log` files.

### supporting information:

 - `npm -v` prints: `4.6.1`
 - `npm5 -v` prints: `5.0.0-beta.58`
 - `node -v` prints: `v5.4.0`
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?: Windows 7
 - Network issues:
   - Geographic location where npm was run: Australia
   - [X] I use a proxy to connect to the npm registry.
   - [X] I use a proxy to connect to the web.
   - [X] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

Since `npm` and `npm5` seem to share the same config file (`C:\Users\dmi\.npmrc` in my case), I assume the proxy configuration should work.
Browsing with Chrome to one of the links that `npm5` 503s on works.

Also, `npm install` works as expected.

Let me know if you need any more information

**Comment by zkat** [comment]
Could you tell me what `npm config get proxy` and `npm5 config get proxy` say? I noticed someone else having issues with their npm5 being installed in such a way that it didn't catch the right config.

**Comment by zkat** [comment]
Also: I just pushed a `beta.59` with a fix to a tunneling proxy issue. Could you try that as well and let me know if it helped? It might Just Work now.

**Comment by mderriey** [comment]
Both commands returned the same value, that is, the correct proxy configuration.
I just updated to `beta.59` and it just worked as you mentioned.

Thanks for getting on to this so quickly, much appreciated! :1st_place_medal:

**Comment by zkat** [comment]
yay. Glad it was just that :D
