### ISSUE TITLE
Issue while installing ionic in windows 7 machine

### ISSUE THREAD

**Issue by Sougatadutta86** [npm/npm#16714]
This is the error which I am getting while trying to install ionic.
I have already installed node.js. But I am not sure why I am getting this error can anyone kindly help me on this:

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova" "ionic"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0

npm ERR! Cannot read property 'path' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\IBM_ADMIN\AppData\Roaming\npm-cache\_logs\2017-05-25T08_10
_40_594Z-debug.log

Kindly let me know if anything is blocking the path to install the application?

**Comment by XYooo** [comment]
same problem!!

**Comment by XYooo** [comment]
in the end, i  re-install my node,and now it works well.i know its not a good solution.I think you can check your environment variable  especially what variable path   points to . 
![Uploading image.png…]()

**Comment by piotrowski** [comment]
I suggest you reinstall node using `nvm-windows`. This tends to fix most of the problems installing Ionic that contain "path" in any of the error messages.
