### ISSUE TITLE
npm install error when installing d3

### ISSUE THREAD

**Issue by Vivihung** [npm/npm#16710]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [X] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Cannot install d3.

> npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "d3"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ENOSELF

>npm ERR! Refusing to install d3 as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

>npm ERR! Please include the following file with any support request:
npm ERR!     e:\Git\d3\npm-debug.log

#### How can the CLI team reproduce the problem?
In a clean repository, run
npm init
npm install d3 --save

### supporting information:

 - `npm -v` prints: 3.10.10
 - `node -v` prints: v6.9.4
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by zkat** [comment]
rename the project you're installing into (change `"name"` in `package.json`, as well as the directory name) to something other than d3. You can't install dependencies with the same name as your package.

**Comment by Vivihung** [comment]
Thanks for the help.
