### ISSUE TITLE
npm install --save react-native-facebook-login ...error

### ISSUE THREAD

**Issue by Joeyrodrigues92** [npm/npm#16711]
#### I'm opening this issue because:

  - [ ] npm is doing something I don't understand.

#### How can the CLI team reproduce the problem?
im just pulled from here https://github.com/magus/react-native-facebook-login#facebook-sdk
and just tried to npm install react-native-facebook-login in the node moduels folder.

### supporting information:

 - `npm -v` prints:4.2.0
 - `node -v` prints:v6.10.2
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:mac
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [
![screen shot 2017-05-24 at 8 16 49 pm](https://cloud.githubusercontent.com/assets/21230272/26430806/19bbbd62-40be-11e7-8e5d-493b9745bdcb.png)
![screen shot 2017-05-24 at 8 16 49 pm](https://cloud.githubusercontent.com/assets/21230272/26430819/2b0f34e0-40be-11e7-867b-871b4509a4eb.png)

] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
You cannot install that module from within it's own source directory. What you probably mean to do is to `cd` into your _own_ project directory and install the module from there.

**Comment by Joeyrodrigues92** [comment]
hey man thanks, im still really new to this. but after i corrected this error ie encountered another dependency issue. 
![screen shot 2017-05-25 at 7 17 57 pm](https://cloud.githubusercontent.com/assets/21230272/26474484/4acfa992-417f-11e7-8471-239cff7e103a.png)
