### ISSUE TITLE
Getting issue while running command "npm install -g @angular/cli"

### ISSUE THREAD

**Issue by AniketGirhe** [npm/npm#16719]
"H:\>npm install -g @angular/cli
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "H:\\node-v7.10.0-win-x64\\node.exe" "H:\\node-v7.10.0-win-x64\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0

npm ERR! Cannot read property 'path' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Aniket\AppData\Roaming\npm-cache\_logs\2017-05-25T15_26_36_659Z-debug.log "

Getting this error can some one please help me?

**Comment by KenanY** [comment]
Looks like you're running `npm install -g `, instead of `npm install -g @angular/cli`?

**Comment by AniketGirhe** [comment]
Hello Kenan no i am running npm install -g @angular/cli only

**Comment by KenanY** [comment]
But the title of the issue says otherwise?

**Comment by AniketGirhe** [comment]
Hello Kenan no i am running npm install -g angular/cli only because @ it is not showing angular/cli in github

**Comment by AniketGirhe** [comment]
@KenanY yes

**Comment by KenanY** [comment]
May I see what happens when you run

```
npm install -g @angular/cli
```

**Comment by AniketGirhe** [comment]
@KenanY  
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "H:\node-v7.10.0-win-x64\node.exe" "H:\node-v7.10.0-win-x64\node_modules\npm\bin\npm-cli.js" "install" "-g" ""
npm ERR! node v7.10.0
npm ERR! npm v4.2.0

npm ERR! Cannot read property 'path' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR! https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR! C:\Users\Aniket\AppData\Roaming\npm-cache_logs\2017-05-25T15_26_36_659Z-debug.log 

throwing this error

**Comment by KenanY** [comment]
Hmm, for some reason the log says you are running

```
npm install -g
```

instead. It's as if your command-line is just stripping the `@angular/cli` part away.
