### ISSUE TITLE
node-Red 64 bit windows 10, npm install node-red-dashboard ..... does now show on Screen    

### ISSUE THREAD

**Issue by gautombose** [npm/npm#16724]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by gautombose** [comment]
In 64 bit windows 10 Node-Red, can now make dashboard work. 
npm install node-red-dashboard.

**Comment by KenanY** [comment]
Missing "dashboard nodes" does not sound like "npm is producing an incorrect install". Could you expand further on how this is an issue with `npm`? What output from `npm` are you seeing, and what are you expecting to see?
