### ISSUE TITLE
prefix -g' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by ashanvabs** [npm/npm#16729]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
when I run 
`npm install [some js lib]`
I'm getting prefix -g' is not recognized as an internal or external command as a error.

### supporting information:

 - `npm -v` prints:3.10.10
 - `node -v` prints: v6.10.3
 - `npm config get registry` prints:'CALL "C:\Program Files\nodejs\\node.exe" "C:\Program 
                                                       Files\nodejs\\node_modules
                                                        \npm\bin\npm-cli.js" prefix -g' is not recognized as an internal or 
                                                         external command,
                                                         operable program or batch file.
                                                         https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by zkat** [comment]
please post an `npm-debug.log` from the error, or at least more details about how to repro this
