### ISSUE TITLE
can't npm --save bootstrap-vue

### ISSUE THREAD

**Issue by gkumarOB** [npm/npm#16727]
Tried npm install --save bootstrap-vue
![screenshot from 2017-05-26 09-51-28](https://cloud.githubusercontent.com/assets/26710557/26480627/ee70486c-41f8-11e7-842b-84a94de85635.png)

**Comment by zkat** [comment]
You need network access and `https://registry.npmjs.org` needs to be reachable. You can configure a proxy using `PROXY` and `HTTPS_PROXY` env variables.

**Comment by gkumarOB** [comment]
@zkat thank you, but can you tell me how and where it is done!!!
I am new user :)

**Comment by zkat** [comment]
Take a gander here: https://jjasonclark.com/how-to-setup-node-behind-web-proxy/

**Comment by gkumarOB** [comment]
After alot of this and that found this
$npm config delete proxy
worked like charm
Thanks mate @zkat
