### ISSUE TITLE
npm5 beta 56: npm pack changes timestamps to 01/01/1970 on Windows 7

### ISSUE THREAD

**Issue by gibfahn** [npm/npm#16734]
#### I'm opening this issue because:

  - [x] npm is doing something I don't understand.

#### What's going wrong?

`npm pack` on Windows seems to be resetting timestamps to `01/01/1970`, which breaks ~several unzipping tools~ one zipping tool.

#### How can the CLI team reproduce the problem?

Download the latest Node 8 rc, [v8.0.0-rc1 for win-x64](https://nodejs.org/download/rc/v8.0.0-rc.1/node-v8.0.0-rc.1-win-x64.zip) and unzip.

```bat
cd node-v8.0.0-rc.1-win-x64
set path=%cd%;%path%
cd ..
mkdir tst
cd tst
npm init -y
echo console.log('hello world') >index.js
npm pack
:: Install Git Bash to get tar.exe
set path=C:\Program Files\Git\usr\bin;%path%
tar -xf tst-1.0.0.tgz
cd package
dir
```

Output:

```bat
05/26/2017  03:49 PM    <DIR>          .
05/26/2017  03:49 PM    <DIR>          ..
01/01/1970  01:00 AM                29 index.js
01/01/1970  01:00 AM               217 package.json
               2 File(s)            246 bytes
               2 Dir(s)  129,871,679,488 bytes free
```

### supporting information:

 - `npm -v`: `5.0.0-beta.56`
 - `node -v` : `v8.0.0-rc.1`
 - `npm config get registry`: `https://registry.npmjs.org/`
 - Windows: Windows 7

**Comment by gibfahn** [comment]
Not allowed to upload tgz files apparently, so I've zipped it as well: [tst-1.0.0.tgz.zip](https://github.com/npm/npm/files/1032225/tst-1.0.0.tgz.zip)

**Comment by seishun** [comment]
Could you give an example of an unzipping tool that's broken by this?

**Comment by gibfahn** [comment]
>Could you give an example of an unzipping tool that's broken by this?

Sorry, that was a typo, I should have said a zipping tool. I was trying to zip up the extracted tarball with `python`. I saw the issue with `python2`, but I can reproduce with `python3` as well.

```py
Python 3.6.0 (default, Mar  4 2017, 12:32:34) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import shutil
>>> shutil.make_archive('tst', 'zip', '.')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/shutil.py", line 795, in make_archive
    filename = func(base_name, base_dir, **kwargs)
  File "/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/shutil.py", line 696, in _make_zipfile
    zf.write(path, path)
  File "/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/zipfile.py", line 1580, in write
    zinfo = ZipInfo.from_file(filename, arcname)
  File "/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/zipfile.py", line 494, in from_file
    zinfo = cls(arcname, date_time)
  File "/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/zipfile.py", line 338, in __init__
    raise ValueError('ZIP does not support timestamps before 1980')
ValueError: ZIP does not support timestamps before 1980
```

**Comment by zkat** [comment]
@gibfahn are you still seeing this with `npm i -g npm@next`?

**Comment by seishun** [comment]
I can reproduce this on Linux too.

The reason this happens is that the fstream module used by npm uses `Object.keys` to copy properties from the fs.Stats object to its own object: https://github.com/npm/fstream/blob/ac4a9e3d86d39a5b979dbdda44376be85b91ece7/lib/reader.js#L147-L149

But `mtime` is not present in the `Object.keys` output since https://github.com/nodejs/node/commit/9836cf571708a82396218957cacb3ed1ed468d05. So when writing the tar header, it defaults to 0.

**Comment by richardlau** [comment]
https://github.com/nodejs/node/pull/12818 called this out:

> This is a `semver-major` change:
> 
>  - `Object.keys(statResult)`, `Object.getOwnPropertyNames/Descriptors(statResult)` will no longer return `atime`, `mtime`, `ctime`, `birthtime`, and WILL return `_atime`, `_mtime`, `_ctime`, `_birthtime`, `_atim_msec`, `_mtim_msec`, `_ctim_msec`, `_birthtim_msec`
> - `for(x in statResult){}` will iterate over `_atime`, `_mtime`, `_ctime`, `_birthtime`, `_atim_msec`, `_mtim_msec`, `_ctim_msec`, `_birthtim_msec`

**Comment by refack** [comment]
but Stats.toJSON() will flatten the lazy fields.

**Comment by refack** [comment]
If you want to be backward compatible:
`s = s.toJSON ? s.toJSON() : s;`

**Comment by seishun** [comment]
I was about to submit a PR fixing `fstream`, but then I realized that there's also a problem in `tar` here: https://github.com/npm/npm/blob/39495d07b9a66c88621e8a2ad07739ee98b70a56/node_modules/tar/lib/pack.js#L142-L144

Unfortunately npm uses an old version of tar: 2.2.1 when the latest is 3.1.3. So before tar can be fixed (if it's still necessary in the new version), npm needs to upgrade to tar 3.1.3, which probably has breaking changes. 🤦‍♂️

**Comment by refack** [comment]
@seishun FWIW `node` will either revert https://github.com/nodejs/node/commit/9836cf571708a82396218957cacb3ed1ed468d05
or find a way to make sure `npm pack` does not regress.

**Comment by refack** [comment]
Cross-ref discussion: https://github.com/nodejs/node/pull/12818#issuecomment-304360039

**Comment by zkat** [comment]
@seishun the tar packing code is pretty high on our list of things to rewrite, but it's a really scary thing to write. There's a _ton_ of details that we want to be able to comb through and replicate -- but tarv3 was largely written so npm would  be able to take advantage of its features, so I'm looking forward to getting rid of `lib/utils/tar.js` altogether.

**Comment by zkat** [comment]
that... was the wrong button.

**Comment by zkat** [comment]
This was a node@8 bug and has been fixed
