### ISSUE TITLE
Install CoffeeScript - Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by alexvirtualbr** [npm/npm#16737]
#### I'm opening this issue because:

  - npm is producing an incorrect install.
  
#### What's going wrong?
When i'm trying install CoffeeScript with npm install coffeescript:
npm ERR! Linux 4.4.0-77-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "coffe-script"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! Cannot convert undefined or null to object
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

#### How can the CLI team reproduce the problem?

<!-- Look my npm-debug in <script src="https://gist.github.com/alexvirtualbr/4d082798aaacd763cd04e976bba67253.js"></script>
  

### supporting information:

 - `npm -v7.4.0`
 - `node -v4.0.5`
  - Linux 16.04
 
 Thanks for your contribuition

**Comment by mkxml** [comment]
try `npm install coffee-script`

**Comment by alexvirtualbr** [comment]
I tryied:
> npm install coffee-script

and some is wrong yeat:

npm install coffee-script
/home/alexvirtualbr
└── coffee-script@1.12.6 

npm WARN enoent ENOENT: no such file or directory, open '/home/alexvirtualbr/package.json'
npm WARN alexvirtualbr No description
npm WARN alexvirtualbr No repository field.
npm WARN alexvirtualbr No README data
npm WARN alexvirtualbr No license field.

**Comment by alexvirtualbr** [comment]
I tryied:
> npm install coffee-script

and some is wrong yeat:

npm install coffee-script
/home/alexvirtualbr
└── coffee-script@1.12.6 

npm WARN enoent ENOENT: no such file or directory, open '/home/alexvirtualbr/package.json'
npm WARN alexvirtualbr No description
npm WARN alexvirtualbr No repository field.
npm WARN alexvirtualbr No README data
npm WARN alexvirtualbr No license field.

**Comment by mkxml** [comment]
@alexvirtualbr Well, from what I see in your log, it looks like CoffeeScript is installed. Do you see a `node_modules` directory?

What the warnings are telling you is that you don't have a `package.json` file, it's recommended to have one.

You can create a package.json file easily with `npm init`, then you can run `npm install coffee-script` again to get it to show in `package.json`.

Hope this helps you, feel free to ask any further questions.

**Comment by alexvirtualbr** [comment]
Hi Matheus, 

The problem was i didn't have created a package.json.

Now it's solved and all function very well.

Thanks so much.
