### ISSUE TITLE
kendo-drawing 

### ISSUE THREAD

**Issue by naresh9715** [npm/npm#16731]
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "@progress/kendo-drawing"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code E403

npm ERR! user nareshbabu.tn@kanmalaitech.com is not allowed to access package @progress/kendo-drawing : @progress/kendo-drawing
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     E:\ng2-admin\npm-debug.log

**Comment by jbcpollak** [comment]
@naresh9715 what did you type on the command line? it looks like maybe you typed `npm install --save`, but you need to specify a package like this:

`npm install --save my-package`

**Comment by zkat** [comment]
Please post more information about what registry you're using and how you logged in. This is saying your credentials are wrong.
