### ISSUE TITLE
npm5 doctor fails when 3rd party registry does not support ping endpoint

### ISSUE THREAD

**Issue by simonua** [npm/npm#16733]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
We use Microsoft's 3rd party VSTS Package Management, which does not implement the _ping_ endpoint. When running `npm doctor` with 4.6.1, we get a "Not Found" for _npm ping_, but npm5 simply crashes with an E404 and does not seemingly proceed with any other checks that could benefit the user (at least it doesn't display them).

There is little the npm cli team can do for registries that don't fully or properly implement the registry interface. I only mention this as an npm5 issue due to the regression as compared to npm4.

Pinging Microsoft for endpoint awareness (@zarenner).
Linking to npm@5 beta tracking (#16510).
Linking to gist [2017-05-26T12_19_49_312Z-debug.log](https://gist.github.com/simonua/e9060a29961f7ba530b17ccc747050af)

![image](https://cloud.githubusercontent.com/assets/8005145/26494496/f4b99040-41ec-11e7-8e0a-84fea2b44507.png)

#### How can the CLI team reproduce the problem?
Point to a registry that does not implement the ping endpoint, then execute `npm5 doctor`.

### supporting information:

 - `npm5 -v` prints: 5.0.0-beta.69
 - `node -v` prints: v7.10.0
 - `npm config get registry` prints: https://connectionseducation.pkgs.visualstudio.com/_packaging/ConnectionsEducationNpm/npm/registry/
 - Windows, OS X/macOS, or Linux?: Windows 7 64-bit
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by simonua** [comment]
Pinging @zkat. I'm sorry to keep doing this. Please let me know whether just linking to 16510 is sufficient, and I'll stop the pings. Just don't want you to accidentally miss it with everything else going on.

**Comment by simonua** [comment]
@watilde, thank you! Also, and this may just be a matter of opinion, but showing the result of `npm config get registry` in red for non-npmjs registry URLs is not quite accurate as it's perfectly valid to have a 3rd party registry configured. Please see my screenshot above. Since npm can't (and doesn't need to) determine what a valid 3rd party URL is, maybe just making this line item yellow (warning) instead of red (error) would be a better way to go?

**Comment by simonua** [comment]
@watilde, thinking the previous thought through a bit more, I would only mark the entry yellow if the ping did not work as a working ping to such a specific endpoint would all but ensure a registry on the other end. In other words, yellow if the ping didn't work (like in my example above), but green for a 3rd party registry if the ping did work.

**Comment by simonua** [comment]
@zkat, would you say this is worthy of being labeled `npm5`?

**Comment by zkat** [comment]
@simonua I assume you can still repro this in the latest `npm@5`? (note that `npm5` itself is no longer updated).

**Comment by zkat** [comment]
I mean, so, this error is almost definitely not coming from `pacote`, since that library *only* handles packument and tarball requests. Not entire sure why this would be crashing in one and not the other 🤔

**Comment by simonua** [comment]
Hi @zkat, yes, unfortunately, I can still repro with 5.0.3. I am a very loyal updater. =) . I'm sorry, I meant tag it with the `npm5` label or otherwise appropriate. Thank you VERY much for pounding out these bug fix releases so quickly. Awesome work, ya'll!

**Comment by simonua** [comment]
If there is anything else I can help with logging, etc., I'd be glad to. @zarenner may be able to repro seeing that VSTS Package Management is part his baby. =P

**Comment by zarenner** [comment]
@simonua Sorry, I apparently missed this when you first opened it. I've raised this issue (including VSTS not supporting ping endpoint) internally. I can also repro on 5.0.3.

**Comment by simonua** [comment]
@zarenner, no worries at all! Thank you for confirming it fails and thank you for all the contributions, too!

**Comment by zkat** [comment]
oh ahahaha.


Yeah ok I figured this out. It's my fault. Sorry, folks!

**Comment by zkat** [comment]
@simonua this _should_ be working in the latest canary, `npmc@5.0.3-canary.2`

**Comment by simonua** [comment]
Awesome! Will try in the morning and confirm. Thank you!

**Comment by simonua** [comment]
Looks much better, @zkat! What @watilde and I talked about earlier is "nice-to-have" type of stuff, but this does the trick for the current issue. If you would do the honors, please, I'm good to close this issue. Thank you - as always!

![image](https://cloud.githubusercontent.com/assets/8005145/26828810/0d171692-4a91-11e7-9633-4627914d9c03.png)

**Comment by zkat** [comment]
Woo. Gonna close this then 🎉

**Comment by legodude17** [comment]
Just a thought, maybe `npm doctor` should say `registry does not support ping` if it gets a 404.

**Comment by simonua** [comment]
@legodude17, I like the idea but I suspect it may then be  ambiguous whether the url for the registry is even correct since I assume part of the reason the ping exists is that there is something on the other end resembling a registry endpoint that has that method and not just an uptime check.
