### ISSUE TITLE
Problem in startup!

### ISSUE THREAD

**Issue by ilkiny** [npm/npm#16742]
0 info it worked if it ends with ok
1 verbose cli [ '/opt/plesk/node/6/bin/node',
1 verbose cli   '/opt/plesk/node/6/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 verbose stack Error: missing script: build
4 verbose stack     at run (/opt/plesk/node/6/lib/node_modules/npm/lib/run-script.js:151:19)
4 verbose stack     at /opt/plesk/node/6/lib/node_modules/npm/lib/run-script.js:61:5
4 verbose stack     at /opt/plesk/node/6/lib/node_modules/npm/node_modules/read-package-json/read-json.js:356:5
4 verbose stack     at checkBinReferences_ (/opt/plesk/node/6/lib/node_modules/npm/node_modules/read-package-json/read-json.j$
4 verbose stack     at final (/opt/plesk/node/6/lib/node_modules/npm/node_modules/read-package-json/read-json.js:354:3)
4 verbose stack     at then (/opt/plesk/node/6/lib/node_modules/npm/node_modules/read-package-json/read-json.js:124:5)
4 verbose stack     at /opt/plesk/node/6/lib/node_modules/npm/node_modules/read-package-json/read-json.js:243:12
4 verbose stack     at /opt/plesk/node/6/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
4 verbose stack     at tryToString (fs.js:455:3)
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
5 verbose cwd /var/www/vhosts/likopa.net/search
6 error Linux 2.6.32-431.el6.x86_64
7 error argv "/opt/plesk/node/6/bin/node" "/opt/plesk/node/6/bin/npm" "run" "build"
8 error node v6.9.1
9 error npm  v3.10.8
10 error missing script: build
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
Hello! So, the way `npm run build` works is that it looks in your current `package.json` for a defined `"build"` [script](https://docs.npmjs.com/misc/scripts), and then runs that. The error message you're seeing is trying to tell you that you have not defined a `"build"` script in your `package.json`, hence `npm run build` has no idea what you want it to do.

To solve this issue, all you have to do is add a new script to your `package.json`. It might look something like this, for example:

``` json
{
  "name": "package-name",
  "version": "1.0.0",
  "description": "package description",
  "scripts": {
    "build": "node --version",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {},
  "devDependencies": {}
}
```

Note how this `package.json` has a `"build"` script that runs `node --version`. You'll definitely want to change the command to whatever is most appropriate for your project.

Let me know if you run into any further `npm` issues :)

**Comment by ilkiny** [comment]
Thanks for your help, I'm writing on Twitter.
