### ISSUE TITLE
cli flag '-l' shows inconsistent info about the 'test' command

### ISSUE THREAD

**Issue by grawlinson** [npm/npm#16748]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?

`npm -l` does not show `test` aliases (`t` & `tst`) or a description for `test`.

#### How can the CLI team reproduce the problem?

```shell
$ npm -l
Usage: npm <command>
    <snip>
    test

    uninstall    npm uninstall [<@scope>/]<pkg>[@<version>]... [--save|--save-dev|--save-optional]

                 aliases: un, unlink, remove, rm, r
    <snip>
```

Note how `uninstall` has a description, then a new line with the aliases, and `test` is just blank?

### supporting information:

 - `npm -v` prints: `4.6.1`
 - `node -v` prints: `v7.10.0`
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?: Linux, although the issue should be cross-platform as it is a documentation issue.

#### What's the feature?

* Add aliases (`tst` & `t`) to `test` command under 'full usage info' flag `-l`
* Add description for test, it is completely blank at the moment.
#### What problem is the feature intended to solve?

Improve cli documentation as the aliases are present in `npm help test`, but not listed under `npm -l` as well as adding a description for the `test` command.

Ideally the output should look like this:

```shell
    test    npm test (other flags/args? not sure as I only really just use 'npm test')

                 aliases: tst, t
```

#### Is the absence of this feature blocking you or your team? If so, how?

No.

#### Is this feature similar to an existing feature in another tool?

No.

#### Is this a feature you're prepared to implement, with support from the npm CLI team?

Sure! Just point me at the specific code and I'll file a PR.

**Comment by zkat** [comment]
This sounds like a nice PR to do, if you'd like :)

I'm not really sure why it isn't happening already, but you can refer to `lib/test.js` for the command itself (it's missing `test.usage = '...'`). The actual aliases come from `lib/config/cmd-list.js`, and the thing that takes those and prints them on `-l` is in `lib/utils/usage.js`.

Have at it!

**Comment by grawlinson** [comment]
Awesome, will give this a go.
