### ISSUE TITLE
Unable to install couchbase npm package with a private registry

### ISSUE THREAD

**Issue by vgummala** [npm/npm#16747]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [# ] Other (_see below for feature requests_):

#### What's going wrong?
Trying to install couchbase npm package and failing.

npm info lifecycle tar-stream@1.5.4~install: tar-stream@1.5.4
npm info lifecycle through2@0.6.5~install: through2@0.6.5
npm info lifecycle hyperquest@1.2.0~install: hyperquest@1.2.0
npm info lifecycle jsonist@1.3.0~install: jsonist@1.3.0
npm info lifecycle ghutils@3.2.1~install: ghutils@3.2.1
npm info lifecycle ghrepos@2.0.0~install: ghrepos@2.0.0
npm info lifecycle ghreleases@1.0.5~install: ghreleases@1.0.5
npm info lifecycle prebuild@6.1.0~install: prebuild@6.1.0
npm info lifecycle couchbase@2.3.3~install: couchbase@2.3.3

> couchbase@2.3.3 install /build-nas/jenkins/jenkins173/workspace/dsv/couchbaseTesting/node_modules/couchbase
> prebuild --install

prebuild info begin Prebuild version 6.1.0
prebuild info build Preparing to prebuild couchbase@2.3.3 for node 6.8.0 on linux-x64 using node-gyp
prebuild verb command rebuild []
prebuild verb ok
prebuild verb command clean []
prebuild verb clean removing "build" directory
prebuild verb ok
prebuild verb command configure []
prebuild verb check python checking for Python executable "python2" in the PATH
prebuild verb `which` succeeded python2 /usr/bin/python2
prebuild verb check python version `/usr/bin/python2 -c "import platform; print(platform.python_version());"` returned: "2.6.6\n"
prebuild verb get node dir no --target version specified, falling back to host node version: 6.8.0
prebuild verb command install [ '6.8.0' ]
prebuild verb install input version string "6.8.0"
prebuild verb install installing version: 6.8.0
prebuild verb install --ensure was passed, so won't reinstall if already installed
prebuild verb install version not already installed, continuing with install 6.8.0
prebuild verb ensuring nodedir is created /build-nas/jenkins/jenkins173/workspace/dsv/couchbaseTesting/node_modules/couchbase/6.8.0
prebuild verb created nodedir /build-nas/jenkins/jenkins173/workspace/dsv/couchbaseTesting/node_modules/couchbase/6.8.0
prebuild http GET https://nodejs.org/download/release/v6.8.0/node-v6.8.0-headers.tar.gz
prebuild WARN install got an error, rolling back install
prebuild verb command remove [ '6.8.0' ]
prebuild verb remove using node-gyp dir:
prebuild verb remove removing target version: 6.8.0
prebuild verb remove removing development files for version: 6.8.0
prebuild ERR! configure error
prebuild ERR! stack Error: connect EHOSTUNREACH 104.20.23.46:443
prebuild ERR! stack     at Object.exports._errnoException (util.js:1026:11)
prebuild ERR! stack     at exports._exceptionWithHostPort (util.js:1049:20)
prebuild ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1085:14)
prebuild ERR! not ok
prebuild ERR! build Error: connect EHOSTUNREACH 104.20.23.46:443
prebuild ERR! build     at Object.exports._errnoException (util.js:1026:11)
prebuild ERR! build     at exports._exceptionWithHostPort (util.js:1049:20)
prebuild ERR! build     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1085:14)
npm verb lifecycle couchbase@2.3.3~install: unsafe-perm in lifecycle true
npm verb lifecycle couchbase@2.3.3~install: PATH: /usr/local/node-v6.8.0-linux-x64/lib/node_modules/npm/bin/node-gyp-bin:/build-nas/jenkins/jenkins173/workspace/dsv/couchbaseTesting/node_mose/node_modules/.bin:/build-nas/jenkins/jenkins173/workspace/dsv/couchbaseTesting/node_modules/.bin:/usr/lib64/qt-3.3/bin:/usr/java/jdk1.7.0_55/bin:/opt/CollabNet_Subversion/bin:/usr/local/in:/usr/local/node-v6.8.0-linux-x64/bin:/usr/local/gradle-2.4/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin
npm verb lifecycle couchbase@2.3.3~install: CWD: /build-nas/jenkins/jenkins173/workspace/dsv/couchbaseTesting/node_modules/couchbase
npm info lifecycle couchbase@2.3.3~install: Failed to exec install script
npm verb unlock done using /build-nas/jenkins/jenkins173/.npm/_locks/staging-a23a99a5adbd4c20.lock for /build-nas/jenkins/jenkins173/workspace/dsv/couchbaseTesting/node_modules/.staging
coucheEx@1.0.0 /build-nas/jenkins/jenkins173/workspace/dsv/couchbaseTesting
`-- d@1.0.0  extraneous

npm verb stack Error: couchbase@2.3.3 install: `prebuild --install`
npm verb stack Exit status 2
npm verb stack     at EventEmitter.<anonymous> (/usr/local/node-v6.8.0-linux-x64/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
npm verb stack     at emitTwo (events.js:106:13)
npm verb stack     at EventEmitter.emit (events.js:191:7)
npm verb stack     at ChildProcess.<anonymous> (/usr/local/node-v6.8.0-linux-x64/lib/node_modules/npm/lib/utils/spawn.js:40:14)
npm verb stack     at emitTwo (events.js:106:13)
npm verb stack     at ChildProcess.emit (events.js:191:7)
npm verb stack     at maybeClose (internal/child_process.js:877:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
npm verb pkgid couchbase@2.3.3
npm verb cwd /build-nas/jenkins/jenkins173/workspace/dsv/couchbaseTesting
npm ERR! Linux 2.6.32-431.el6.x86_64
npm ERR! argv "/usr/local/node-v6.8.0-linux-x64/bin/node" "/usr/local/node-v6.8.0-linux-x64/bin/npm" "install" "--verbose"
npm ERR! node v6.8.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! couchbase@2.3.3 install: `prebuild --install`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the couchbase@2.3.3 install script 'prebuild --install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the couchbase package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild --install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs couchbase
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls couchbase
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]

#### How can the CLI team reproduce the problem?
Attempt to run " npm install couchbase" with a private registry behind a corporate firewall not open to internet.

### supporting information:

 - `npm -v` prints: 2.14.12
 - `node -v` prints: v4.2.4
 - `npm config get registry` prints: **private registry**
 - Windows, OS X/macOS, or Linux?: linux
 - Network issues:
   - Geographic location where npm was run:
   - [#] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by zkat** [comment]
Please make sure you are able to reach `104.20.23.46:443` outside of npm, first. If you're using a proxy, put it in `PROXY` and `HTTPS_PROXY` in the env.

**Comment by vgummala** [comment]
@zkat Our servers are hosted in a corporate network for which we do not have access to internet. However we are able to download this binaries in the local system, which has access to internet.
