### ISSUE TITLE
Refusing to install webdriverio-cucumber-js as a dependency of itself

### ISSUE THREAD

**Issue by gupender** [npm/npm#16755]
G:\webdriverio-cucumber-js-master>npm install webdriverio-cucumber-js
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "webdriverio-cucumber-js"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ENOSELF

npm ERR! Refusing to install webdriverio-cucumber-js as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     G:\webdriverio-cucumber-js-master\npm-debug.log

G:\webdriverio-cucumber-js-master>

**Comment by KenanY** [comment]
As the error message states, you cannot install the `webdriverio-cucumber-js` as a dependency of itself. `npm` believe you are doing this because you are in the package's source directory. What you probably mean to be doing is running that command from within your _own project's_ directory.
