### ISSUE TITLE
npm ERR! Object function (err) has no method 'toLowerCase' during install@latest

### ISSUE THREAD

**Issue by Jens-G** [npm/npm#16758]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

The installation is ending with an npm ERR showing a weird error message since 4.6.1

#### How can the CLI team reproduce the problem?

Not sure. But it very reliably breaks our Travis builds for some time now. This is the full screen output of the relevant part:

```
Step 24 : RUN curl -sSL https://www.npmjs.com/install.sh | sh
---> Running in 0edf1ca023e7
tar=/bin/tar
version:
tar (GNU tar) 1.27.1
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later 
<http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
install npm@latest
fetching: https://registry.npmjs.org/npm/-/npm-4.6.1.tgz
npm ERR! Object function (err) {
npm ERR!         if (err) return cb(err)
npm ERR!         fs.fsync(fd, function (err) {
npm ERR!           if (err) return cb(err)
npm ERR!           fs.close(fd, cb)
npm ERR!         })
npm ERR!       } has no method 'toLowerCase'
It failed
The command '/bin/sh -c curl -sSL https://www.npmjs.com/install.sh | sh' 
returned a non-zero code: 1
/home/travis/.travis/job_stages: line 155:  1053 Terminated 
travis_jigger $! $timeout $cmd
```

The full log can be found here:
https://travis-ci.org/apache/thrift/jobs/236635859#L6732

### supporting information:

 - Ubuntu Trusty

 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [x] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by Jens-G** [comment]
This is the dockerfile used:
https://github.com/apache/thrift/tree/master/build/docker/ubuntu

**Comment by Fanarim** [comment]
I have the same problem while using http://npmjs.org/install.sh in our build env. Workaround was to run `sed "s/latest/4.5.0"` on the script and running it in bash instead of sh.

**Comment by Jens-G** [comment]
This is ridiculous. You are ignoring bugs and let the system auto-close them? That's an interesting way to deal with issues ...

**Comment by Jens-G** [comment]
... and at the same time there are still tons of outstanding PRs. Maybe we should no longer rely on node?

**Comment by Jens-G** [comment]
>  If your issue is closed and it’s still a problem for you then we encourage you to open a new issue.
> joining package.communty and asking your question there

No. I'm for sure not going to do that.
