### ISSUE TITLE
homestead install npm  question  

### ISSUE THREAD

**Issue by MrChenCode** [npm/npm#16767]
```
vagrant@homestead:~/Code/TaskManager$ npm install --no-bin-links
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
vagrant@homestead:~/Code/TaskManager$ gulp
[12:10:30] Using gulpfile ~/Code/TaskManager/gulpfile.js
[12:10:30] Starting 'default'...
[12:10:30] Starting 'sass'...
Segmentation fault (core dumped)
vagrant@homestead:~/Code/TaskManager$
```

win7  laravel /homestead 
 Look at the great god help Thank you, why I did not appear the CSS folder under the public

**Comment by KenanY** [comment]
Segfault does not appear to be caused by `npm`. Might wanna take a look at your "sass" gulp task instead.

**Comment by MrChenCode** [comment]
var elixir = require('laravel-elixir');



elixir(function(mix) {
    mix.sass('app.scss');
});

Task is laravel initialization tasks I didn't change   , Excuse me, does this have what problem?
