### ISSUE TITLE
TypeError: Cannot read property 'latest' of undefined

### ISSUE THREAD

**Issue by ilovesyntax** [npm/npm#16761]
Hi all,

I'm about to install npm install -g firebase-tools, but this error always pops up. 

npm http 304 https://registry.npmjs.org/tar
npm http 304 https://registry.npmjs.org/user-home
npm http 304 https://registry.npmjs.org/universal-analytics
npm http 304 https://registry.npmjs.org/update-notifier
npm http 304 https://registry.npmjs.org/uuid
npm http 304 https://registry.npmjs.org/winston
npm http 304 https://registry.npmjs.org/superstatic
npm http 404 https://registry.npmjs.org/google-cloud/functions-emulator
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/usr/share/npm/lib/cache.js:687:35)
npm ERR!     at /usr/share/npm/lib/cache.js:675:5
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.4.0-75-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "firebase-tools"
npm ERR! cwd /usr/local/me/home/ilovesyntax
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type non_object_property_load
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /usr/local/me/home/ilovesyntax/npm-debug.log
npm ERR! not ok code 0

I tried uninstall / install node js but still the issue persists.

nodejs v0.10.25

**Comment by KenanY** [comment]
Your versions of Node.js and `npm` are years old and are no longer supported. I suggest you first try updating both.

**Comment by ilovesyntax** [comment]
Thanks for the replay Kenan. However, I'm still having this issue. I'm using below versions

npm -v
4.6.1
nodejs v 0.10.25

In the firebase hosting [page](https://firebase.google.com/docs/hosting/deploying#section-hosting-setup)
it says that 

> The Firebase CLI requires Node.js version 0.10.0 or greater.

So I believe I'm in the right version to install Firebase cli, but this error keeps blocking me

**Comment by kenany** [comment]
@ilovesyntax Do note that `npm` itself requires Node.js v4 or higher.
