### ISSUE TITLE
Error while publishing package

### ISSUE THREAD

**Issue by divyanshupathak** [npm/npm#16775]
Hello,

While publishing my first package, I found the following error on terminal (on linux 14.04 LTS) -

`you do not have permission to publish "npm-test-pkg". Are you logged in as the correct user? : npm-test-pkg`

But I login with correct credentials from terminal. I also go through the docs, but can't find any proper solution from them.

npm -v = 3.10.10
node -v = 7.2.1
npm config get registry = https://registry.npmjs.org/
I am using **Linux**.

Here is the gist of npm-debug.log file -
https://gist.github.com/divyanshupathak/ffb7659135d0ca8e15484f48c2cca258

Please guide me for this issue.
Thanks.

**Comment by michelgotta** [comment]
I think the name for your package is already taken:
https://www.npmjs.com/package/npm-test-pkg

And that's why you don't have the permission to publish or contribute with this package.

**Comment by divyanshupathak** [comment]
Thanks it works. It was a stupid question. BTW closing this issue.
