### ISSUE TITLE
Cannot read property 'path' of null

### ISSUE THREAD

**Issue by kanajam** [npm/npm#16774]
Hi Team,

Getting the below error.

I used the below approach to set proxy for beyond the corporate firewalls:

npm config set proxy
npm config set http-proxy
npm config set https-proxy
npm config get registry

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "angular-cli"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5

npm ERR! Cannot read property 'path' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\vijay_kanajam\npm-debug.log

Please suggest me if any solution for the same.

Regards,
Vijay Kanajam

**Comment by zkat** [comment]
please update your npm and try again

**Comment by kanajam** [comment]
I tried as per your given input, but the same result.

Below is the log file:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'npm',
1 verbose cli   '-g' ]
2 info using npm@4.0.5
3 info using node@v7.4.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData npm
8 silly fetchNamedPackageData npm
9 silly mapToRegistry name npm
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'npm',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'npm',
12 silly mapToRegistry   name: 'npm',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/npm
14 verbose request uri https://registry.npmjs.org/npm
15 verbose request no auth needed
16 info attempt registry request try #1 at 10:26:23 AM
17 verbose request id 8d12fafc6196f156
18 http request GET https://registry.npmjs.org/npm
19 info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND 80 80:80
20 info attempt registry request try #2 at 10:26:33 AM
21 http request GET https://registry.npmjs.org/npm
22 info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND 80 80:80
23 info attempt registry request try #3 at 10:27:33 AM
24 http request GET https://registry.npmjs.org/npm
25 silly fetchPackageMetaData Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND 80 80:80
25 silly fetchPackageMetaData     at ClientRequest.onError (C:\Program Files\nodejs\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:176:17)
25 silly fetchPackageMetaData     at Object.onceWrapper (events.js:290:19)
25 silly fetchPackageMetaData     at emitOne (events.js:96:13)
25 silly fetchPackageMetaData     at ClientRequest.emit (events.js:188:7)
25 silly fetchPackageMetaData     at Socket.socketErrorListener (_http_client.js:309:9)
25 silly fetchPackageMetaData     at emitOne (events.js:96:13)
25 silly fetchPackageMetaData     at Socket.emit (events.js:188:7)
25 silly fetchPackageMetaData     at connectErrorNT (net.js:1025:8)
25 silly fetchPackageMetaData     at _combinedTickCallback (internal/process/next_tick.js:74:11)
25 silly fetchPackageMetaData     at process._tickCallback (internal/process/next_tick.js:98:9)
25 silly fetchPackageMetaData  error for npm { Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND 80 80:80
25 silly fetchPackageMetaData     at ClientRequest.onError (C:\Program Files\nodejs\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:176:17)
25 silly fetchPackageMetaData     at Object.onceWrapper (events.js:290:19)
25 silly fetchPackageMetaData     at emitOne (events.js:96:13)
25 silly fetchPackageMetaData     at ClientRequest.emit (events.js:188:7)
25 silly fetchPackageMetaData     at Socket.socketErrorListener (_http_client.js:309:9)
25 silly fetchPackageMetaData     at emitOne (events.js:96:13)
25 silly fetchPackageMetaData     at Socket.emit (events.js:188:7)
25 silly fetchPackageMetaData     at connectErrorNT (net.js:1025:8)
25 silly fetchPackageMetaData     at _combinedTickCallback (internal/process/next_tick.js:74:11)
25 silly fetchPackageMetaData     at process._tickCallback (internal/process/next_tick.js:98:9) code: 'ECONNRESET' }
26 silly rollbackFailedOptional Starting
27 verbose stack TypeError: Cannot read property 'path' of null
27 verbose stack     at Installer.rollbackFailedOptional (C:\Program Files\nodejs\node_modules\npm\lib\install.js:505:29)
27 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
27 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
27 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:18:7
27 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install.js:331:5
27 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
27 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
27 verbose stack     at chain (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
27 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install.js:288:5
27 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:16:22
28 verbose cwd C:\Users\vijay_kanajam
29 error Windows_NT 6.1.7601
30 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "npm" "-g"
31 error node v7.4.0
32 error npm  v4.0.5
33 error Cannot read property 'path' of null
34 error If you need help, you may report this error at:
34 error     <https://github.com/npm/npm/issues>
35 verbose exit [ 1, true ]

Please give your feedback.
