### ISSUE TITLE
error when installing angular/cli

### ISSUE THREAD

**Issue by karnavkumar** [npm/npm#16778]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'angular/cli@latest' ]
2 info using npm@4.1.2
3 info using node@v7.7.4
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData angular/cli@latest
8 silly fetchOtherPackageData angular/cli@latest
9 silly cache add args [ 'angular/cli@latest', null ]
10 verbose cache add spec angular/cli@latest
11 silly cache add parsed spec Result {
11 silly cache add   raw: 'angular/cli@latest',
11 silly cache add   scope: null,
11 silly cache add   escapedName: null,
11 silly cache add   name: null,
11 silly cache add   rawSpec: 'angular/cli@latest',
11 silly cache add   spec: 'C:\\Users\\Kv\\Desktop\\angular\\cli@latest',
11 silly cache add   type: 'local' }
12 error addLocal Could not install C:\Users\Kv\Desktop\angular\cli@latest
13 silly fetchPackageMetaData Error: ENOENT: no such file or directory, open 'C:\Users\Kv\Desktop\angular\cli@latest'
13 silly fetchPackageMetaData  error for angular/cli@latest { Error: ENOENT: no such file or directory, open 'C:\Users\Kv\Desktop\angular\cli@latest'
13 silly fetchPackageMetaData   errno: -4058,
13 silly fetchPackageMetaData   code: 'ENOENT',
13 silly fetchPackageMetaData   syscall: 'open',
13 silly fetchPackageMetaData   path: 'C:\\Users\\Kv\\Desktop\\angular\\cli@latest' }
14 silly rollbackFailedOptional Starting
15 verbose stack TypeError: Cannot read property 'path' of null
15 verbose stack     at Installer.rollbackFailedOptional (C:\Program Files\nodejs\node_modules\npm\lib\install.js:511:29)
15 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
15 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
15 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:18:7
15 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install.js:337:5
15 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
15 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
15 verbose stack     at chain (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
15 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install.js:294:5
15 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:16:22
16 verbose cwd C:\Users\Kv\Desktop
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "angular/cli@latest"
19 error node v7.7.4
20 error npm  v4.1.2
21 error Cannot read property 'path' of null
22 error If you need help, you may report this error at:
22 error     <https://github.com/npm/npm/issues>
23 verbose exit [ 1, true ]

**Comment by arvalaan** [comment]
Angular should be installed with the following command:

npm install -g @angular/cli - seems like you forgot the first "@"

**Comment by KenanY** [comment]
Could you try

```
npm install -g @angular/cli
```

instead?

**Comment by sfabriece** [comment]
I solved this by going into `c:\Users\{user}\AppData\Roaming\npm\` and deleting `ng` and `ng.cmd`

You can run `npm -g ls --depth 0` to make sure that `@angular/cli` doesn't show up.

Then install @angular/cli as usual.

`npm -g i @angular/cli` for the latest version or `npm -g i @angular/cli@1.1.0-rc.2` for the current RC version as of this writing.
