### ISSUE TITLE
cannot install grunt on linux

### ISSUE THREAD

**Issue by lazehang** [npm/npm#16786]
#### I'm opening this issue because:

  - [x] npm is doing something I don't understand.

#### What's going wrong?
cannot install grunt or update npm.

### supporting information:

 - `npm -v` prints: 3.5.2
 - `node -v` prints: v7.10.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux

###Debug Log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node-full/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'grunt-cli' ]
2 info using npm@3.5.2
3 info using node@v7.10.0
4 verbose stack Error: Cannot find module 'ansi'
4 verbose stack     at Function.Module._resolveFilename (module.js:470:15)
4 verbose stack     at Function.Module._load (module.js:418:25)
4 verbose stack     at Module.require (module.js:498:17)
4 verbose stack     at require (internal/module.js:20:19)
4 verbose stack     at Object.<anonymous> (/usr/share/npm/lib/ls.js:15:13)
4 verbose stack     at Module._compile (module.js:571:32)
4 verbose stack     at Object.Module._extensions..js (module.js:580:10)
4 verbose stack     at Module.load (module.js:488:32)
4 verbose stack     at tryModuleLoad (module.js:447:12)
4 verbose stack     at Function.Module._load (module.js:439:3)
5 verbose cwd /home/mangal
6 error Linux 4.8.0-52-generic
7 error argv "/usr/bin/node-full/bin/node" "/usr/bin/npm" "install" "-g" "grunt-cli"
8 error node v7.10.0
9 error npm  v3.5.2
10 error code MODULE_NOT_FOUND
11 error Cannot find module 'ansi'
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]

**Comment by zkat** [comment]
use cnpm

**Comment by KenanY** [comment]
@lazehang must've edited their post, because now the issue appears to be a broken `npm` installation. Could you try reinstalling `npm`?

**Comment by zkat** [comment]
@KenanY oops, you're right. I confused MODULE_NOT_FOUND with a 404. I shouldn't be doing this stuff at 4am :)

**Comment by lazehang** [comment]
Thanks @KenanY

**Comment by legodude17** [comment]
Do you still have this issue @lazehang?
