### ISSUE TITLE
npm install (homestead)

### ISSUE THREAD

**Issue by ubiratanlima** [npm/npm#16792]
#### I'm opening this issue because:
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.

### supporting information:

 - `npm -v` prints: 3.10.10
 - `node -v` prints: 6.10.2
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?: Windows 10 PRO 64bits (Fisical)
 - Windows, OS X/macOS, or Linux?: HOMESTEAD 2.1 (Linux x64) - (Virtual)
 - Container:
   - [x] I develop using Vagrant on Windows.

- NPM INSTALL (RESULT):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! Linux 4.4.0-66-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "i"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! path ../acorn/bin/acorn
npm ERR! code EPROTO
npm ERR! errno -71
npm ERR! syscall symlink

npm ERR! EPROTO: protocol error, symlink '../acorn/bin/acorn' -> '/home/vagrant/Code/asoWorkMed/node_modules/.bin/acorn'

**Comment by KenanY** [comment]
Does this also occur if you use the `--no-bin-links` flag?

**Comment by ubiratanlima** [comment]
Acontece a mesma coisa utilizando --no-bin-links  flag.
The same thing happens using  --no-bin-links  flag.

**Comment by ubiratanlima** [comment]
Resolvido!

Solução: 
1. Removido o VAGRANT BOX 2.1
2. Reinstalado VAGRANT BOX 2.0
3. Instalado NPM com a flag --no-bin-links

Não sei o que estava de errado no BOX 2.1, pois todos os projetos continuam funcionando no BOX 2.0.

Obrigado KenanY +++++++
