### ISSUE TITLE
npm ERR! network getaddrinfo ENOTFOUND proxy proxy:00

### ISSUE THREAD

**Issue by stylesplox** [npm/npm#16795]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I'm trying to install express-generator globally but keep running into this error

![error](https://cloud.githubusercontent.com/assets/29059413/26592547/00f5bd6a-4559-11e7-81a2-f6e528d07681.png)

I'm not using a proxy

#### How can the CLI team reproduce the problem?
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'express-generator',
1 verbose cli   '-g' ]
2 info using npm@3.10.10
3 info using node@v6.10.3
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData express-generator
8 silly fetchNamedPackageData express-generator
9 silly mapToRegistry name express-generator
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry http://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'express-generator',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'express-generator',
12 silly mapToRegistry   name: 'express-generator',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri http://registry.npmjs.org/express-generator
14 verbose request uri http://registry.npmjs.org/express-generator
15 verbose request no auth needed
16 info attempt registry request try #1 at 4:53:51 PM
17 verbose request id f93b4ac02ba14446
18 http request GET http://registry.npmjs.org/express-generator
19 info retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND proxy proxy:00
20 info attempt registry request try #2 at 4:54:04 PM
21 http request GET http://registry.npmjs.org/express-generator
22 info retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND proxy proxy:00
23 info attempt registry request try #3 at 4:55:07 PM
24 http request GET http://registry.npmjs.org/express-generator
25 silly fetchPackageMetaData Error: getaddrinfo ENOTFOUND proxy proxy:00
25 silly fetchPackageMetaData     at errnoException (dns.js:28:10)
25 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
25 silly fetchPackageMetaData  error for express-generator { Error: getaddrinfo ENOTFOUND proxy proxy:00
25 silly fetchPackageMetaData     at errnoException (dns.js:28:10)
25 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
25 silly fetchPackageMetaData   code: 'ENOTFOUND',
25 silly fetchPackageMetaData   errno: 'ENOTFOUND',
25 silly fetchPackageMetaData   syscall: 'getaddrinfo',
25 silly fetchPackageMetaData   hostname: 'proxy',
25 silly fetchPackageMetaData   host: 'proxy',
25 silly fetchPackageMetaData   port: '00' }
26 silly rollbackFailedOptional Starting
27 silly rollbackFailedOptional Finishing
28 silly runTopLevelLifecycles Finishing
29 silly install printInstalled
30 verbose stack Error: getaddrinfo ENOTFOUND proxy proxy:00
30 verbose stack     at errnoException (dns.js:28:10)
30 verbose stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
31 verbose cwd C:\Users\user\Desktop\backup\Documents\Web Dev\ServerSide
32 error Windows_NT 6.1.7601
33 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "express-generator" "-g"
34 error node v6.10.3
35 error npm  v3.10.10
36 error code ENOTFOUND
37 error errno ENOTFOUND
38 error syscall getaddrinfo
39 error network getaddrinfo ENOTFOUND proxy proxy:00
40 error network This is most likely not a problem with npm itself
40 error network and is related to network connectivity.
40 error network In most cases you are behind a proxy or have bad network settings.
40 error network
40 error network If you are behind a proxy, please make sure that the
40 error network 'proxy' config is set properly.  See: 'npm help config'
41 verbose exit [ 1, true ]

### supporting information:

 - `npm -v` prints: v3.10.10
 - `node -v` prints: v6.10.3
 - `npm config get registry` prints: http://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
If you're not using a proxy, could you try:

```
npm config delete proxy
npm config delete https-proxy
```

**Comment by stylesplox** [comment]
> If you're not using a proxy, could you try: npm config delete proxy npm config delete https-proxy

still giving me the same error
