### ISSUE TITLE
npm is removing last character on install

### ISSUE THREAD

**Issue by mika1111** [npm/npm#16793]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
when package has more than 100 characters in path last character is removed
#### How can the CLI team reproduce the problem?
I created example package [tar-test](https://www.npmjs.com/package/tar-test) . Afte run 'npm install tar-test' there will be file test.t in .\node_modules\1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890. It should be test.ts. Problem is probably conected with tar/gzip since download from [link](https://registry.npmjs.org/tar-test/-/tar-test-0.0.3.tgz) and extracting using 7zip is working ok. Version 0.0.3 was publish using personally created tar file. Version 0.0.2 was published using npm creation of tgz and [package](https://registry.npmjs.org/tar-test/-/tar-test-0.0.2.tgz) is broken.

Installation is not hrowing any errors.

### supporting information:

 - `npm -v` prints: 4.6.1
 - `node -v` prints: v7.10.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows 8.1
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by alexeikostevich** [comment]
Our team met the same issue, which prevented us from keeping a desired package structure.

**Comment by skiraikou** [comment]
The same for me actually - weird stuff

**Comment by iarna** [comment]
Wow, that is super weird, I suspect this is a bug in the older version of [node-tar](https://npmjs.com/package/tar). We'll be updating our tar soon and we'll circle back and see.

**Comment by mika1111** [comment]
Npm version 5 looks to solved this problem. Thank you :)
