### ISSUE TITLE
npm install --production removes devDependencies

### ISSUE THREAD

**Issue by jonathantneal** [npm/npm#16798]
#### I'm opening this issue because:

  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.

#### What's going wrong?

I have a script that watches for changes to package.json and runs `npm install --production`. However, that command is now removing devDependencies.

There’s no mention of this in the current [doc/cli/npm-install.md](https://github.com/npm/npm/blob/latest/doc/cli/npm-install.md)

#### How can the CLI team reproduce the problem?

```sh
npm init
npm install --save-dev fse # any package will do
npm install --production
```

### supporting information:

 - `npm -v` prints: 5.0.0
 - `node -v` prints: 7.10.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS
 - Network issues:
   - Geographic location where npm was run: The Woods of Georgia, USA
   - [x] I access the npm registry via a VPN

**Comment by petetnt** [comment]
I think I am having this same problem (in an opposite way) in #16794

**Comment by Lange** [comment]
I am experiencing this issue as well. Windows 10 x64, Node 8.0.0, npm 5.0.2.

**Comment by jonathantneal** [comment]
Hmm, not sure how I feel about Comcast-like resolutions, but hey, I get it, super big project, I can be swept under the @npm-robot rug to keep the issue tracker on focus.

For anyone who catches this: my temporary resolution has been: `nvm use 6`
