### ISSUE TITLE
NPM install socket.io crashes on CHIP Pro

### ISSUE THREAD

**Issue by luiscuesta** [npm/npm#16805]
Hi everyone. I'm developing an application with websockets on my CHIP Pro. I'm using nodejs, the problem is when I try no install the module socket.io, the installer crashes and this appears:

```
npm WARN package.json sockets@1.0.0 No description
npm WARN package.json sockets@1.0.0 No repository field.
npm WARN package.json sockets@1.0.0 No README data
npm WARN locking Error: EEXIST, open '/root/.npm/_locks/socket-io-97299df50c593fa3.lock'
npm WARN locking     at Error (native)
npm WARN locking  /root/.npm/_locks/socket-io-97299df50c593fa3.lock failed { [Error: EEXIST, open '/root/.npm/_locks/socket-io-97299df50c593fa3.lock']
npm WARN locking   errno: -17,
npm WARN locking   code: 'EEXIST',
npm WARN locking   path: '/root/.npm/_locks/socket-io-97299df50c593fa3.lock' }
npm ERR! Linux 4.4.30
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "socket.io" "-S"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! Attempt to unlock /home/chip/sockets/node_modules/socket.io, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/chip/sockets/npm-debug.log
```

I don't know if I'm having this issue due to node version or what, but I've tried everything. I also use the module express and it installed correctly, as a matter of fact it appears on the **_package.json_** file.  Thanks a lot for your help.

**Comment by KenanY** [comment]
Does this also occur with newer versions of Node and `npm`?

**Comment by luiscuesta** [comment]
No it doesn't, I made a chat application with these two modules and it works perfectly, the version of node is newer than the one that is on CHIP and I don't know if this issue could be also related with the kernel version

**Comment by KenanY** [comment]
I would simply suggest using the latest stable releases of both Node and `npm`, especially since you're saying that they solve the issue for you.

**Comment by luiscuesta** [comment]
But the problem is that the build-root of CHIP Pro only allows me to install that version of node. I can't install a newest one., and that version is supposed to be stable. I don't know how to install another version of socket.io that could be stable with that version of node (0.12.7).

**Comment by KenanY** [comment]
Node 0.12 used to be stable, but support for it ended back in December.
