### ISSUE TITLE
NPM 5 does not recognize short git hash for git+ssh dependencies

### ISSUE THREAD

**Issue by blai** [npm/npm#16803]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
If you have a dependency that uses `git+ssh` reference with a short git hash, NPM 5 installation seems to ignore it. Our actual repository is private, so the following only serve as example.

For example, in your `package.json`, you have
```json
dependencies: {
  "myPackage": "git+ssh://git@github.com/myOrg/myPackage#0d29960"
}
```
then NPM@5 will simple install `git+ssh://git@github.com/myOrg/myPackage`.

But if you have `git+ssh` that uses the full git hash, then it will work, e.g. 
```json
dependencies: {
  "myPackage": "git+ssh://git@github.com/myOrg/myPackage#0d29960ab12ab1ab123a123456789ab1a1a1a123"
}
```

### supporting information:

 - `npm -v` prints: 5.0.0
 - `node -v` prints: 8.0.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: OS X
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by zkat** [comment]
This will be fixed by https://github.com/zkat/pacote/pull/91 once pacote is updated. Thanks!
