### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by montogeek** [npm/npm#16800]
#### I'm opening this issue because:

  - [x] npm is crashing.

#### What's going wrong?
```
👉  npm install
npm ERR! Maximum call stack size exceeded

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/montogeek/.npm/_logs/2017-05-30T19_15_58_276Z-debug.log
```

#### How can the CLI team reproduce the problem?

https://gist.github.com/montogeek/d63cece93be4b5752ff3e61a384103cc

### supporting information:

 - `npm -v` prints: 5.0.0
 - `node -v` prints: v8.0.0
 - `npm config get registry` prints: https://registry.npmjs.org
 - Windows, OS X/macOS, or Linux?: OSX
 - Network issues: None

I reported it in beta.46: https://github.com/npm/npm/issues/16510#issuecomment-300324467

**Comment by hhsnopek** [comment]
I have also received this error because a `package.json` did not exist in my `$PWD`.

**Comment by RonnieSan** [comment]
I'm receiving this error because I use symlinks in the node_modules folder.
```
lib
- node_modules
  - lib --> /lib
```

This error did not occur in npm 3.x or lower.
