### ISSUE TITLE
eai_again registry.npmjs.org:443

### ISSUE THREAD

**Issue by Srjshau** [npm/npm#16817]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by Srjshau** [comment]
Cannot use npm install, throws the same error every time
npm version: 5.0.0
node version: 8.0.0

**Comment by jkugiya** [comment]
Following operation solved this problem in my situation.(Windows, WSL)
```
$ ping registry.npmjs.org
PING registry.npmjs.org (151.101.72.162) 56(84) bytes of data.

$ sudo vi /etc/hosts
151.101.72.162 registry.npmjs.org
```
