### ISSUE TITLE
Proxy authentication does not work correctly

### ISSUE THREAD

**Issue by tmyt** [npm/npm#16811]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?
I can not install any package under proxy with authentication.

NPM get this error message.

```
npm ERR! code E407
npm ERR! 407 Proxy Authentication Required: cacache@^9.2.5

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2017-05-31T04_23_05_614Z-debug.log
```

I captured packets with tcpdump when this error message, the request header does not include `Proxy-Authorization` header.

```
GET http://registry.npmjs.org/cacache HTTP/1.1
connection: keep-alive
user-agent: npm/5.0.0 node/v8.0.0 linux x64
npm-in-ci: false
npm-scope:
referer: install
pacote-req-type: packument
pacote-pkg-id: registry:manifest
accept: application/vnd.npm.install-v1+json; q=1.0, application/json; q=0.8, */*
accept-encoding: gzip,deflate
Host: registry.npmjs.org:80
```

#### How can the CLI team reproduce the problem?

```console
$ npm i
npm ERR! code E407
npm ERR! 407 Proxy Authentication Required: cacache@^9.2.5

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2017-05-31T04_23_05_614Z-debug.log
```

### supporting information:

 - `npm -v` prints: 5.0.0
 - `node -v` prints: v8.0.0
 - `npm config get registry` prints: http://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux
 - Network issues:
   - Geographic location where npm was run:
   - [x] I use a proxy to connect to the npm registry.
   - [x] I use a proxy to connect to the web.
   - [x] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by tmyt** [comment]
This problem related external module `make-fetch-happen`.  I pull-requested to zkat/make-fetch-happen#30

**Comment by zkat** [comment]
The PR has been merged and should be included in the upcoming `5.0.1` release. Thanks a bunch for this patch! This was super helpful. 🎉

**Comment by zkat** [comment]
Assuming this specific one to be fixed, since https://github.com/zkat/make-fetch-happen/pull/30 was merged.

**Comment by CunhaGus** [comment]
Hi There, it is still not working after I updated npm manually to version 5.0.1. The log file is below:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\sul1\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'multer' ]
2 info using npm@5.0.1
3 info using node@v6.10.3
4 silly install loadCurrentTree
5 silly install readLocalPackageData
6 http fetch GET 407 http://registry.npms.org/multer 1526ms
7 silly fetchPackageMetaData error for multer@latest 407 Proxy Authentication Required ( Forefront TMG requires authorization to fulfill the request. Access to the Web Proxy filter is denied.  ): multer@latest
8 verbose stack Error: 407 Proxy Authentication Required ( Forefront TMG requires authorization to fulfill the request. Access to the Web Proxy filter is denied.  ): multer@latest
8 verbose stack     at fetch.then.res (C:\Users\sul1\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:36:19)
8 verbose stack     at tryCatcher (C:\Users\sul1\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
8 verbose stack     at Promise._settlePromiseFromHandler (C:\Users\sul1\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
8 verbose stack     at Promise._settlePromise (C:\Users\sul1\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
8 verbose stack     at Promise._settlePromise0 (C:\Users\sul1\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
8 verbose stack     at Promise._settlePromises (C:\Users\sul1\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
8 verbose stack     at Async._drainQueue (C:\Users\sul1\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
8 verbose stack     at Async._drainQueues (C:\Users\sul1\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
8 verbose stack     at Immediate.Async.drainQueues (C:\Users\sul1\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
8 verbose stack     at runCallback (timers.js:672:20)
8 verbose stack     at tryOnImmediate (timers.js:645:5)
8 verbose stack     at processImmediate [as _immediateCallback] (timers.js:617:5)
9 verbose cwd C:\Windows\system32
10 verbose Windows_NT 6.1.7601
11 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\sul1\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "multer"
12 verbose node v6.10.3
13 verbose npm  v5.0.1
14 error code E407
15 error 407 Proxy Authentication Required ( Forefront TMG requires authorization to fulfill the request. Access to the Web Proxy filter is denied.  ): multer@latest
16 verbose exit [ 1, true ]
