### ISSUE TITLE
npm@5 formats my `package.json` files even without any changes

### ISSUE THREAD

**Issue by cedx** [npm/npm#16823]
#### I'm opening this issue because:
npm is doing something I don't understand.

#### What's going wrong?
Everytime I do a `npm update` or `npm install` (no `--save` switch), the `package.json` file is formatted (blank lines removed for example). As these commands don't change the contents of the `package.json` files, why a formatting is applied ?!?

It's very annoying. Now, I often have this king of messages with my Git client :
```
$ git pull
error: Your local changes to the following files would be overwritten by merge:
	package.json
Please, commit your changes or stash them before you can merge.
Aborting
```

#### How can the CLI team reproduce the problem?
Just do a `npm install` or `npm update`.

### supporting information:

 - `npm -v` prints: 5.0.0
 - `node -v` prints: 8.0.0 (reproduced with v7.10.0)
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: reproduced on Windows 10, OSX El Capitan and Ubuntu 16.04

**Comment by kenany** [comment]
What is the result of `npm config get save`?

**Comment by cedx** [comment]
```
$ npm config get save
true
```

I didn't know that there was a config value for this feature :)

**Comment by cedx** [comment]
I close this issue : setting the `save` config value to `false` resolved this problem (I never use the `--save` switch, so this solution satisfies me).

Thanks a lot @KenanY.
