### ISSUE TITLE
Error when installing modules

### ISSUE THREAD

**Issue by matmen** [npm/npm#16836]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
When trying to `npm install`, i get a `Unhandled rejection Error: Command failed: /usr/bin/git checkout 7896081966728fd9c1bf833a24690ab630874c9e`.
#### How can the CLI team reproduce the problem?
[debug.log](https://gist.github.com/xmatmen/222c0583550bb3f65724fa9a438b62aa)
I could only get this to error in [this repo](https://github.com/xmatmen/fbot) (Cloning and calling `npm i`)

### supporting information:

 - `npm -v` prints: 5.0.0
 - `node -v` prints: v8.0.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux (Debian 8)
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by zkat** [comment]
I just pushed out `npm@5.0.1`. Could you try that out and tell me if it works? It has a bunch of git-related fixes.

**Comment by matmen** [comment]
This fixed it, cheers!
