### ISSUE TITLE
npm@5.0.0 incorrect install issue

### ISSUE THREAD

**Issue by jamesplease** [npm/npm#16837]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

I checked two, because it could be either.

#### What's going wrong?

I upgraded to npm 5.0.0, wiped node_modules, and reinstalled. Two issues seemed to arise:

1. the webpack CLI was not moved to `node_modules/.bin`
2. not every dep was installed

For webpack, I had:

`"webpack": "2.3.2",`

This is installed correctly, however, its script from its `bin` field in `package.json` wasn't moved to `node_modules/.bin`, so my `npm script` cannot find it. My npm script is:

`"watch-webpack": "webpack -w",`

I decided to upgrade webpack to the latest release, to see what would happen, and this issue was resolved. But then, building the CSS failed because a lib, `cssnano`, could not find its own specified dep, `postcss-discard-comments`. I was unable to get `cssnano` to find that dependency.

My `cssnano` dep is:

`"cssnano": "3.10.0",`

My app does not depend on `postcss-discard-comments`; that is specified by `cssnano`.

I downgraded back to npm 4.6.1, wiped `node_modules`, reinstalled, and everything worked as intended (we do daily builds on CI on this project, so I'm confident that everything in the package.json is OK, at least as far as npm < 5 is concerned).

This was the first time I had ever used npm@5.0.0 on this project, and on this machine. There was no existing shrinkwrap nor lockfile in this project (although, of course, one was generated after that first npm install).

#### How can the CLI team reproduce the problem?

The repository is private, and relies on a bunch of private npm packages, so I don't have a reproducible test case. But I figured I'd open the issue, just in case its useful.

Let me know if there's more info I can provide that would be helpful.

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by CraigMorton** [comment]
I've had similar issues with npm5. If I delete node_modules and `npm install`, (or also sometimes apparently without deleting anything) there are pkg.devDependencies, (and also dependencies of my pkg.dependencies), missing from node_modules after an apparently error-free `npm install` - repeating npm install doesn't change the situation.

Has `npm install` default behaviour been changed with npm 5?

**Comment by clarkie** [comment]
Not sure if this is related but I 
```
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '[projectdir]/node_modules/codeceptjs-webdriverio/node_modules/.bin/codeceptjs'
npm ERR! enoent This is related to npm not being able to find a file.
```
when installing https://www.npmjs.com/package/codeceptjs-webdriverio

forgot to add I'm on npm v5.0.3

**Comment by zkat** [comment]
I can't repro this, even with `npm@5.0.0`. @jmeas could you install the latest canary, `npmc@5.0.4-canary.13`, and let me know if things work for you now? There's been a bunch of installer fixes recently.

**Comment by jamesplease** [comment]
Sure, I'll give `5.0.4-canary.13` a try on the same project, @zkat (but I won't be able to 'til next week)

Given that so many folks must be using npm5, and there are only a few :+1:'s on this issue, it might just be some edge case that crops up with certain deps.

I'll follow up here in a few days. Thank you, @zkat!

**Comment by zkat** [comment]
thanks a bunch, @jmeas!

**Comment by VhThomas** [comment]
Guys, just installed latest version of npm... Great job!

**Comment by mindriven** [comment]
Same issue here (on windows box), downgrading to 4.6.1 is a working workaround for me.
Clearing cache didn't help.

**Comment by jamesplease** [comment]
It's been awhile – sorry about that. I finally had a chance to try this again. On `npm@5.3.0`, I'm unable to reproduce this same issue, so I'll be closing this issue out.

---

Note that we're still running into unreliable package-locks (specifically around updating deps), so we're updating to npm@5 but disabling the package-lock file. If I have time to debug what the issue is with package-lock, I'll post a separate issue.
