### ISSUE TITLE
shasum error: npm install -g cordova

### ISSUE THREAD

**Issue by mobibob** [npm/npm#16842]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

$ npm install -g cordova
npm ERR! Darwin 16.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "cordova"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10

npm ERR! shasum check failed for /var/folders/49/64yg5sln1czd1bzkr36mf1s40000gn/T/npm-2418-9ea439e1/registry.npmjs.org/glob/-/glob-5.0.15.tgz
npm ERR! Expected: 1bc936b9e02f4a603fcc222ecf7633d30b8b93b1
npm ERR! Actual:   befc11661b5f548d32190ee9869f9c4d7350fe62
npm ERR! From:     https://registry.npmjs.org/glob/-/glob-5.0.15.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/demo/Documents/Projects/SprintHoneyBee/sprint_gst_implementation_payment/cordova-ios/npm-debug.log

#### How can the CLI team reproduce the problem?

Fresh install on virgin Macbook.

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by mobibob** [comment]
uinstalled cordova
removed my working directory

$ sudo npm install -g cordova

WORKED!  You can close this ticket.  I believe I did not have the permissions for npm to make the changes along the way, so when it needed the next step, it had an inconsistent pair of files to compare shasum.

**Comment by kenany** [comment]
Closing as resolved.
