### ISSUE TITLE
cb() never called

### ISSUE THREAD

**Issue by Masar92** [npm/npm#16865]
#### I'm opening this issue because:

  - [ ] npm is crashing
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by timoxley** [comment]
@Masar92 what version of npm? You should fill out the "supporting information" in the issue template.

**Comment by zkat** [comment]
This has no information. Closing.

**Comment by Masar92** [comment]
node v6.10.3

npm v3.10.10

thanks for help , yet  the problem is  not be fixed

________________________________
Van: Tim Oxley <notifications@github.com>
Verzonden: donderdag 1 juni 2017 16:15:21
Aan: npm/npm
CC: Kbyeh Masar [student]; Mention
Onderwerp: Re: [npm/npm] cb() never called (#16865)


@Masar92<https://github.com/masar92> what version of npm?

**Comment by zkat** [comment]
@Masar92 I need, at the very least, a debug log, an explanation of what you are doing, and a description of what you expected to see happen and why. This error doesn't give me enough information by itself.

**Comment by Masar92** [comment]
I want just to start my npm for angular application
________________________________
Van: Kat Marchán <notifications@github.com>
Verzonden: dinsdag 6 juni 2017 10:29:51
Aan: npm/npm
CC: Kbyeh Masar [student]; Mention
Onderwerp: Re: [npm/npm] cb() never called (#16865)


@Masar92<https://github.com/masar92> I need, at the very least, a debug log, an explanation of what you are doing, and a description of what you expected to see happen and why. This error doesn't give me enough information by itself.

**Comment by zkat** [comment]
@Masar92 I hear that, but I can't help you if I don't know what you need help with.

**Comment by Masar92** [comment]
Hey , I give you the attachement of the error , so I need to install npm just this.
And it didn't succesd , I want to understand way not and if course if the npm install doesn't work. the command npm start to start my angular application also.  can help me with this information?
________________________________
Van: Kat Marchán <notifications@github.com>
Verzonden: dinsdag 6 juni 2017 19:53:23
Aan: npm/npm
CC: Kbyeh Masar [student]; Mention
Onderwerp: Re: [npm/npm] cb() never called (#16865)


@Masar92<https://github.com/masar92> I hear that, but I can't help you if I don't know what you need help with.

**Comment by kenany** [comment]
@Masar92 Attaching the log to a GitHub email reply does _not_ result in the attachment appearing on the GitHub website. Could you upload the debug log to <https://gist.github.com/> and link it here instead? Thanks!

**Comment by Masar92** [comment]
https://gist.github.com/e6b29d5ea4ca3d7db46bb8ac524b5e4b


________________________________
Van: Kenan Yildirim <notifications@github.com>
Verzonden: dinsdag 6 juni 2017 22:07:24
Aan: npm/npm
CC: Kbyeh Masar [student]; Mention
Onderwerp: Re: [npm/npm] cb() never called (#16865)


@Masar92<https://github.com/masar92> Attaching the log to a GitHub email reply does not result in the attachment appearing on the GitHub website. Could you upload the debug log to https://gist.github.com/ and link it here instead? Thanks!

**Comment by kenany** [comment]
@Masar92 Looks like you are running `npm start` from a directory which does not contain a `package.json` file. Without one, `npm` has nowhere to look for the `"start"` script that you want it to execute. You probably want to do `npm init`, and then add in the `"start"` script yourself. The [scripts docs](https://docs.npmjs.com/misc/scripts) might help in that regard.
