### ISSUE TITLE
How to disable the lock file on NPM5

### ISSUE THREAD

**Issue by borela** [npm/npm#16867]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

Is there a way to disable the generation of lock files?

**Comment by mcibique** [comment]
You can ignore generating it during install using old --no-shrinkwrap flag which works for lock file too:
```
npm install <package> --no-shrinkwrap
```
see --no-shrinkwrap in https://docs.npmjs.com/cli/install

or you can set it globally:
```
npm config set package-lock false
```
see https://docs.npmjs.com/misc/config#package-lock

**Comment by zkat** [comment]
Question was answered. `--no-package-lock` and `--no-shrinkwrap` will both work, and you can set those in your config too.

**Comment by borela** [comment]
@mcibique Thank you :D

**Comment by kof** [comment]
I have stumbled over the same issue, though I want to disable lock files package-wise. For e.g. most of the time I do want the lock file, but in some cases, where a package is used as dependency where main package has  a lock-file already, so lock file in the dependency has no value, but makes updating dependencies more work.

**Comment by gustavnikolaj** [comment]
@kof you could use a `.npmrc` file in the repo with the following content:

```
package-lock=false
```

You can even check it into your repo. `npm` will continue to walk up the folders to find your `.npmrc` in `~` with your `authToken` anyway. :-)

I would still prefer an option to do it in `package.json` though, so you wouldn't have to add another dotfile to the repo. A boolean lock property would be the obvious solution, sort of the same thing as the `flat` property yarn supports in `package.json`.

```json
{
  "name": "my-package",
  "dependencies": {
    "my-other-package": "1.2.3"
  },
  "lock": false
}
```

**Comment by maciej-gurban** [comment]
Just a heads up, since github doesn't notify of reactions to a post, and there seem to be quite a few indicating that `package.json` level option to disable lock file would be of interest to some users.

**Comment by zkat** [comment]
We won't be adding an option to `package.json` for this. Please use a project-local `.npmrc` for this if you want to have a persistent configuration.
