### ISSUE TITLE
npm uninstall is actually installing node_modules

### ISSUE THREAD

**Issue by sibiraj-s** [npm/npm#16863]
#### I'm opening this issue because:

  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
 
I ran `npm uninstall <absent_module>` to test. the uninstall never happened. It took very long progress. I terminated that and

Then I ran `npm uninstall <any_module> --save`. NPM actullly reinstalls all packages inside node_modules

**Comment by zkat** [comment]
npm5 has a new model of dependency management: it will _synchronize_ your `node_modules` with your `package-lock.json`. That means that if you have no `node_modules` and you do an `npm rm foo`, deps will be installed with `foo` removed.
