### ISSUE TITLE
npm@5 publish private-pckg.tgz gives error code: 128

### ISSUE THREAD

**Issue by yvele** [npm/npm#16871]
#### I'm opening this issue because:

  - [x] npm is crashing. (maybe related to https://github.com/npm/npm/issues/16830)
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

##### `.npmrc`

```
//registry.npmjs.org/:_authToken=${NPM_TOKEN}
access = restricted
```

##### Command:

```
npm publish dist/my-private-package-0.1.0.tgz --access restricted
```

##### Result:

```
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/yvele/.npm/_logs/2017-06-01T13_19_40_612Z-debug.log
```

##### Log file:

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/yvele/.nvm/versions/node/v6.5.0/bin/node',
1 verbose cli   '/Users/yvele/.nvm/versions/node/v6.5.0/bin/npm',
1 verbose cli   'publish',
1 verbose cli   'dist/my-private-package-0.1.0.tgz',
1 verbose cli   '--access',
1 verbose cli   'restricted' ]
2 info using npm@5.0.1
3 info using node@v6.5.0
4 verbose publish [ 'dist/my-private-package-0.1.0.tgz' ]
5 silly cache add args [ 'dist/my-private-package-0.1.0.tgz', undefined ]
6 verbose cache add spec dist/my-private-package-0.1.0.tgz
7 silly cache add parsed spec dist/my-private-package-0.1.0.tgz
8 silly prefetch no integrity hash provided for github:dist/my-private-package-0.1.0.tgz - fetching by manifest
9 verbose stack Error: exited with error code: 128
9 verbose stack     at ChildProcess.onexit (/Users/yvele/.nvm/versions/node/v6.5.0/lib/node_modules/npm/node_modules/mississippi/node_modules/end-of-stream/index.js:39:36)
9 verbose stack     at emitTwo (events.js:106:13)
9 verbose stack     at ChildProcess.emit (events.js:191:7)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
10 verbose cwd /Users/yvele/Projects/Hapticmedia/devops-tools
11 verbose Darwin 16.6.0
12 verbose argv "/Users/yvele/.nvm/versions/node/v6.5.0/bin/node" "/Users/yvele/.nvm/versions/node/v6.5.0/bin/npm" "publish" "dist/my-private-package-0.1.0.tgz" "--access" "restricted"
13 verbose node v6.5.0
14 verbose npm  v5.0.1
15 error exited with error code: 128
16 verbose exit [ 1, true ]

```

### supporting information:

 - `npm -v` prints: `5.0.1`
 - `node -v` prints: `v6.5.0`
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?: OSX and Linux (CircleCI)

**Comment by phazzled** [comment]
I'm experiencing the same issue after upgrading to NPM 5.0.1. I want to add that this error shows up when I  use 'npm install --only=dev', not when I type 'npm install'.

**Comment by zkat** [comment]
That is not a valid file specifier. You need to use `npm publish ./dist/my-private-pkg-1.2.3.tgz`

**Comment by yvele** [comment]
This was working with **npm 4**:

```
npm publish dist/my-private-pkg-1.2.3.tgz
```

With **npm 5** I need to explicitelly prefix the relative path with a dot:

```
npm publish ./dist/my-private-pkg-1.2.3.tgz
```

@zkat That's too bad because [path.join](https://nodejs.org/api/path.html#path_path_join_paths) normalize the path and removes the leading dot. I didn't now that `foo/bar.tgz` wasn't a valid file specifier...

[Wikipedia](https://en.wikipedia.org/wiki/Path_(computing)#Absolute_and_relative_paths) states:

> At that moment, the relative path for the desired directory can be represented as:
> ```
> ./bobapples
> ```
> or for short:
> ```
> bobapples
> ```
> 

[POSIX standard](http://pubs.opengroup.org/onlinepubs/009695399/basedefs/xbd_chap03.html#tag_03_266) on relative path name:

> 
> 3.319 Relative Pathname
> 
> A pathname not beginning with a slash.

[POSIX pathname resolution](http://pubs.opengroup.org/onlinepubs/009695399/basedefs/xbd_chap04.html#tag_04_11)

> If the pathname does not begin with a slash, the predecessor of the first filename of the pathname shall be taken to be the current working directory of the process (such pathnames are referred to as "relative pathnames").

That's a really strange and unexpected behaviour not to allow **short relative path expression** 😕 

------

After the leading dot "hack", I'm now hitting another error:

> **npm ERR! Cannot read property 'algorithm' of undefined**

https://github.com/npm/npm/issues/16723 😭

**Comment by zkat** [comment]
@yvele We changed the way `file:` specifiers work, with npm5: https://github.com/npm/npm/pull/15900
