### ISSUE TITLE
Updating npm says you should update npm right after

### ISSUE THREAD

**Issue by sdaitzman** [npm/npm#16872]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?

Here is a [recording](https://asciinema.org/a/47t0pw8w6ib5pn72rfhfiqbys).

When you run `$ npm i -g npm@latest` with an old version, npm installs the latest version and then tells you to update

#### How can the CLI team reproduce the problem?

1. Have old npm version
2. Run `$ npm install --global npm@latest`

**Comment by zkat** [comment]
https://github.com/yeoman/update-notifier/issues/67 This is an `update-notifier` bug.

**Comment by sdaitzman** [comment]
@zkat thank you for directing me there, and thanks to you all working on npm for your awesome work!

**Comment by zkat** [comment]
@sdaitzman thank you!
