### ISSUE TITLE
npm-session header missing in npm@5

### ISSUE THREAD

**Issue by zarenner** [npm/npm#16889]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?
npm previously sent the header npm-session with a unique ID per invocation of npm. This was useful for registry services to be able to correlate server requests across client sessions.

npm@5 appears to no longer send this header, presumably because of the change to pacote.

### supporting information:

 - `npm -v` prints: 5.0.1

**Comment by zkat** [comment]
Ooooops. You're indeed right.

Fixing this involves adding [`'npm-session'` here](https://github.com/zkat/pacote/blob/latest/lib/fetchers/registry/fetch.js#L75-L78), as well as adding an [`npmSession` option to pacote's option processor](https://github.com/zkat/pacote/blob/latest/lib/util/opt-check.js). That'll take care of the pacote side of things.

Along with that, npm then has to be modified to [pass the session id through](https://github.com/npm/npm/blob/latest/lib/config/pacote.js#L13). You can see [how `npm-registry-client` generated this one](https://github.com/npm/npm-registry-client/blob/0e0a707dcf62e9705ef17b7d471d3657c33e79e6/lib/initialize.js#L10-L12), and [how it set it in the headers](https://github.com/npm/npm-registry-client/blob/0e0a707dcf62e9705ef17b7d471d3657c33e79e6/lib/initialize.js#L54) so you'd probably just need a toplevel var in `lib/config/pacote.js` that generates it once for the lifetime of the npm process. 

I'll totally 100% take PRs on both pacote and npm for this, and I think this is a good example of a good starter issue, so I'm tagging it as such. This is a great way for folks to start getting familiar with the way npm's networking layer works.

**Comment by zarenner** [comment]
Great, thanks for the very detailed guidance! I'll plan to work on this sometime in the next few days or so, unless someone else says they want to take it.

**Comment by zkat** [comment]
Awesome! Cheers 👍
