### ISSUE TITLE
npm init needs a light update

### ISSUE THREAD

**Issue by GrosSacASac** [npm/npm#16886]
#### I'm opening this issue because:

  - [ X] Other (_see below for feature requests_):

#### What's going wrong?

https://github.com/npm/npm/blob/latest/lib/init.js#L25

npm init still tells you to --save. But it is not needed anymore.

#### How can the CLI team reproduce the problem?

npm init

**Comment by zkat** [comment]
@GrosSacASac This sounds like a great starter PR!

**Comment by jhwohlgemuth** [comment]
I might be missing something, but I made a very light PR with a light update (#16895) 👍

**Comment by GrosSacASac** [comment]
nice
