### ISSUE TITLE
npm@5 install error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by mcibique** [npm/npm#16882]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Installing the package [canned](https://www.npmjs.com/package/canned) with new npm@5 fails with error message:
```
npm ERR! path D:\tmp\canned-test\node_modules\.staging\canned-4229f9d7\spec\test_responses\_a?name=Batman&age=30.get.html
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open 'D:\tmp\canned-test\node_modules\.staging\canned-4229f9d7\spec\test_responses\_a?name=Batman&age=30.get.html'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

but it is working fine with npm@4 and npm@3. The package has not been updated in last 3 months so it should be caused by latest npm updates. The issue is reproducible with versions 5.0.0 and 5.0.1 too.

#### How can the CLI team reproduce the problem?

```
mkdir /tmp/canned-test && cd /tmp/canned-test/
npm init --yes
npm install canned
```

### supporting information:

 - `npm -v` prints: 5.0.1
 - `node -v` prints: v7.10.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows 7, Windows 10, Mint and Ubuntu
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by mcibique** [comment]
I did small investigation and I found that the `node_modules\.staging` folder doesn't contain any canned folder. There is only lodash folder (another dependency). This might be caused by the `pacote` being unable to extract the tgz. I set up an empty project with pacote@2.7.27 and following `index.js`:

```js
let pacote = require('pacote');

pacote
  .extract('https://registry.npmjs.org/canned/-/canned-0.3.10.tgz', './temp')
  .then(function () {
    console.log('remote tarball contents extracted to ./temp');
  })
  .catch(function (error) {
    console.log(error);
  });
```

Running it threw exactly the same error as above:
```
{ Error: ENOENT: no such file or directory, open 'D:\work\temp\pacote-test\temp\spec\test_responses\_a?name=Batman&age=30.get.html'
  cause:
   { Error: ENOENT: no such file or directory, open 'D:\work\temp\pacote-test\temp\spec\test_responses\_a?name=Batman&age=30.get.html'
     errno: -4058,
     code: 'ENOENT',
     syscall: 'open',
     path: 'D:\\work\\temp\\pacote-test\\temp\\spec\\test_responses\\_a?name=Batman&age=30.get.html' },
  isOperational: true,
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'D:\\work\\temp\\pacote-test\\temp\\spec\\test_responses\\_a?name=Batman&age=30.get.html' }
```

I cloned the canned repo, removed the test_responses folder, npm packed it and called `pacote.extract('./canned-0.3.10.tgz', './temp')`: worked fine.

**Comment by zkat** [comment]
@mcibique could you file this as an issue against `pacote` itself?

**Comment by mcibique** [comment]
@zkat I have discovered that this issue is caused by `tar-fs` and I have created PR in their repo. The problem is the `?` character in the filename `_a?name=Batman&age=30.get.html` which is not allowed on Windows. npm@4 uses `node-tar` which replaces all invalid characters here: https://github.com/npm/node-tar/blob/master/lib/winchars.js. That's the reason why it was working before. `tar-fs` only replaces `:`, which is not enough. I tried my changes in tar-fs with latest npm@5.0.3 locally and I can confirm that canned package was successfully installed.

**Comment by zkat** [comment]
@mcibique fantastic! Thanks a bunch!

We're going to be moving to `node-tar` again once I find the time to finish up the `tar@3` branch of `pacote` and #16804 lands. But your fix to tar-fs is more likely to land first. I'm gonna cross-link it here for reference: https://github.com/mafintosh/tar-fs/pull/63

🎉

**Comment by ryan-allen** [comment]
i had to run a `node cache clean --force` and `npm install` started working again after encountering this error on windows 10 (1703), i'm not sure why 🙃

**Comment by zkat** [comment]
@ryan-allen that... I don't get how that would happen but "ok".

Unless you were installing npm5 with an older version of npm. Ah well. Glad it works for you :)

**Comment by davidcalhoun** [comment]
@ryan-allen Just to clarify, it's `npm cache clean`:

E.g.
`npm cache clean --force`
`npm install`
