### ISSUE TITLE
Building module from C++ source crashs

### ISSUE THREAD

**Issue by Herobone** [npm/npm#16885]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
It produces this error:
$ node-gyp build
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.1
gyp info using node@6.10.2 | win32 | x64
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu ermöglichen, müssen Sie den Scha
lter "/m" hinzufügen.
MSBUILD : error MSB3428: Die Visual C++-Komponente "VCBuild.exe" konnte nicht geladen werden. Um dieses Problem zu beheben, insta
llieren Sie entweder 1) .NET Framework 2.0 SDK oder 2) Microsoft Visual Studio 2005 oder 3) fügen Sie den Speicherort der Kompone
nte zum Systempfad hinzu, falls er vom Standardspeicherort abweicht.  [C:\Users\julius\Documents\TestApps\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\julius\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\julius\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\nod
e-gyp.js" "build"
gyp ERR! cwd C:\Users\julius\Documents\TestApps
gyp ERR! node -v v6.10.2
gyp ERR! node-gyp -v v3.6.1
gyp ERR! not ok

#### How can the CLI team reproduce the problem?

LTS version of Node
LTS version of npm and all modules
LTS version on VS2017 Community
BuildTools 2015

doing this tutorial:
https://nodejs.org/dist/latest-v6.x/docs/api/addons.html

File-Tree:
├───.vscode
├───build
├───my_modules
    └───src
                └───hello.cc
├───main.js
├───binding.gyp
├───package.json

Crashes in ervery console

### supporting information:

 - `npm -v` prints: 3.10.10
 - `node -v` prints: v6.10.2
 - `node-gyp -v` prints: v3.6.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows 10 64x
 - Network issues:
   - Geographic location where npm was run: Germany
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by zkat** [comment]
This is an issue with `node-gyp`, not npm. Please file a bug [in their issue tracker](https://github.com/nodejs/node-gyp).
