### ISSUE TITLE
npm publish --tag <tag> updates latest

### ISSUE THREAD

**Issue by DanielZlotin** [npm/npm#16881]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

`npm publish --tag foo` will update the `latest` tag and NOT `foo`.

### supporting information:

 - `npm -v` prints: 5.0.0
 - `node -v` prints: v8.0.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS

**Comment by zkat** [comment]
This is fixed in 5.0.1
