### ISSUE TITLE
npm 5.0.1 can't install some specific Git branches

### ISSUE THREAD

**Issue by favna** [npm/npm#16900]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [X] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

When installing a Git branch with `git://github.com/<user>/<repo>.git#<branch>` npm throws a `no matching version found for undefined@<branch>`. Full error:
```
$ npm install --save git://github.com/Gawdl3y/discord.js-commando.git#11.1
npm ERR! code ETARGET
npm ERR! notarget No matching version found for undefined@11.1
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

However `npm install --save git://github.com/Gawdl3y/discord.js-commando.git` does work and manually adding `#11.1` in package.json followed by `rm -rf node_modules/ && npm install` will also let the package be installed properly.

Lastly this appears to only occur when the branch in question has specific characters such as a `.`. During another attempt of adding the dependency and knowing that the package is also a known package on npmjs I decided to try `npm install discord.js-commando#11.1 --save` which gave the following error:

```bash
$ npm install discord.js-commando#11.1 --save
Unhandled rejection Error: Invalid tag name "discord.js-commando#11.1": Tags may not have any characters that encodeURIComponent encodes.
    at invalidTagName (C:\Users\Favna\AppData\Roaming\npm\node_modules\npm\node_modules\npm-package-arg\npa.js:76:15)
    at fromRegistry (C:\Users\Favna\AppData\Roaming\npm\node_modules\npm\node_modules\npm-package-arg\npa.js:244:13)
    at resolve (C:\Users\Favna\AppData\Roaming\npm\node_modules\npm\node_modules\npm-package-arg\npa.js:66:12)
    at npa (C:\Users\Favna\AppData\Roaming\npm\node_modules\npm\node_modules\npm-package-arg\npa.js:39:10)
    at C:\Users\Favna\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:200:16
    at C:\Users\Favna\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
    at Array.forEach (native)
    at C:\Users\Favna\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
    at Array.forEach (native)
    at asyncMap (C:\Users\Favna\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
    at exports.getAllMetadata (C:\Users\Favna\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:199:3)
    at Installer.loadArgMetadata (C:\Users\Favna\AppData\Roaming\npm\node_modules\npm\lib\install.js:325:3)
    at C:\Users\Favna\AppData\Roaming\npm\node_modules\npm\lib\install.js:648:16
    at BB.join.then (C:\Users\Favna\AppData\Roaming\npm\node_modules\npm\lib\install\read-shrinkwrap.js:41:16)
    at tryCatcher (C:\Users\Favna\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Favna\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
npm ERR! cb() never called!
```

*Final note: The repo that is referenced in this issue is as follows, however I have also tested this myself with other repos that follow a similar naming scheme in branches as well as branches that do not (i.e. a "dev" branch) and it appears to occur consistently. Repo: https://github.com/Gawdl3y/discord.js-commando/tree/11.1*

#### How can the CLI team reproduce the problem?

Since there are two errors listed here I will also list a method of reproduction for each

1. A package.json with no dependencies listed then followed by the command: `npm install --save git://github.com/Gawdl3y/discord.js-commando.git#11.1`

```json
{
  "name": "repro",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
  }
}
```

NPM Debug: https://gist.github.com/Favna/69d85d407bf2c8b2676bdb13a061f82a

2. A package.json with no dependencies listed then followed by the command: `npm install discord.js-commando#11.1 --save`

```json
{
  "name": "repro",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
  }
}
```

NPM Debug: https://gist.github.com/Favna/44123d4737ae5f9cf92e2808c17a2e6c

### supporting information: 

 - `npm -v` prints: 5.0.1
 - `node -v` prints: v7.10.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows 10 Creators Update
 - Network issues:
   - Geographic location where npm was run: Delft, The Netherlands
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by zkat** [comment]
This is fixed already and everything should be fine once 5.0.2 is released.

In the meantime, you can use `npm i -g npmc` to pull in the canary version that fixes this.

Closing!
