### ISSUE TITLE
Cannot find module 'safe-buffer'

### ISSUE THREAD

**Issue by Luffyying** [npm/npm#16905]
#### I'm opening this issue because:

  when I  enter the command :npm ,it hint as following:
Error: Cannot find module 'safe-buffer'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Dell\AppData\Roaming\npm\node_modules\npm\node_modules\request\lib\helpers.js:5:36)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Dell\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'safe-buffer'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

 - `npm -v` prints:3.10.10
 - `node -v` prints:6.10.3
 - `npm config get registry` prints:
 - Windows
 - Network issues:

thankyou !

**Comment by kthy** [comment]
I'm experiencing exactly the same problem. Why did you close the issue, @Luffyying ?

**Comment by Luffyying** [comment]
oh,because the problem has been solved,I think there are some conflicts between my  global npm and the npm in node,so when delete the global npm it works.
----- 原始邮件 -----
发件人：Kristian Thy <notifications@github.com>
收件人：npm/npm <npm@noreply.github.com>
抄送人：若水 <lufei_ying@sina.com>,  Mention <mention@noreply.github.com>
主题：Re: [npm/npm] Cannot find module 'safe-buffer' (#16905)
日期：2017年06月02日 15点03分

I'm experiencing exactly the same problem. Why did you close the issue, @Luffyying ?

&mdash;

**Comment by kthy** [comment]
Thanks for the reply. FYI, uninstalling Node.js, manually deleting the npm and npm-cache directories under AppData and reinstalling fixed the problem for me.

**Comment by Luffyying** [comment]
you are welcome,similar solutions .





新浪邮箱客户端

------------------------原始邮件------------------------
发件人：Kristian Thy<notifications@github.com>
时间：2017年6月2日 下午3:34:47
收件人：npm/npm<npm@noreply.github.com>
抄送：Mention<mention@noreply.github.com>,若水<lufei_ying@sina.com>
主题：Re: [npm/npm] Cannot find module 'safe-buffer' (#16905)

Thanks for the reply. FYI, uninstalling Node.js, manually deleting the npm and npm-cache directories under AppData and reinstalling fixed the problem for me.

**Comment by Robertbaelde** [comment]
I have the same issue, how do i resolve this? i already uninstalled and installed node

**Comment by Luffyying** [comment]
Try to delete the global npm .





新浪邮箱客户端

------------------------原始邮件------------------------
发件人：Robertbaelde<notifications@github.com>
时间：2017年6月8日 下午9:18:57
收件人：npm/npm<npm@noreply.github.com>
抄送：Mention<mention@noreply.github.com>,若水<lufei_ying@sina.com>
主题：Re: [npm/npm] Cannot find module 'safe-buffer' (#16905)

I have the same issue, how do i resolve this? i already uninstalled and installed node

**Comment by gilesbradshaw** [comment]
or the local npm..

**Comment by Yim-Sekny** [comment]
Actually in my machine even delete global npm or uninstall node.js and install it agian but still not work.
_______________________________________________________________________________________________________________
so my solution is uninstall npm and go to delete folder **npm and npm-cache** in C:\Users\pc-name\AppData\Roaming then install it again

**Comment by pengxingyun** [comment]
you can try **npm install safe-buffer**...
I use this to resolve. @yimseknyCorarl
