### ISSUE TITLE
npm@5 install --global crash

### ISSUE THREAD

**Issue by warlock** [npm/npm#16910]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
npm i mytop -g produce a exception  in npm@5 version. Possibly this happens in other packages. Package installs successfully when I downgrade to npm@4

#### How can the CLI team reproduce the problem?
```
$ sudo npm i mytop@latest -g
npm ERR! Path must be a string. Received undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-06-02T10_03_16_952Z-debug.log


$ sudo cat  /root/.npm/_logs/2017-06-02T10_03_16_952Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'i', 'mytop@latest', '-g' ]
2 info using npm@5.0.1
3 info using node@v6.10.3
4 silly install loadCurrentTree
5 silly install readGlobalPackageData
6 http fetch GET 200 https://registry.npmjs.org/mytop 248ms
7 silly pacote tag manifest for mytop@latest fetched in 273ms
8 verbose stack TypeError: Path must be a string. Received undefined
8 verbose stack     at assertPath (path.js:7:11)
8 verbose stack     at Object.relative (path.js:1227:5)
8 verbose stack     at computeVersionSpec (/usr/lib/node_modules/npm/lib/install/deps.js:282:27)
8 verbose stack     at Object.Installer.normalizeCurrentTree (/usr/lib/node_modules/npm/lib/install.js:370:69)
8 verbose stack     at Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
8 verbose stack     at LOOP (/usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
8 verbose stack     at /usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
8 verbose stack     at /usr/lib/node_modules/npm/lib/install.js:619:16
8 verbose stack     at /usr/lib/node_modules/npm/node_modules/iferr/index.js:13:50
8 verbose stack     at thenHandleErrors (/usr/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:233:5)
8 verbose stack     at f (/usr/lib/node_modules/npm/node_modules/once/once.js:25:25)
8 verbose stack     at handleComplete (/usr/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:22:28)
8 verbose stack     at f (/usr/lib/node_modules/npm/node_modules/once/once.js:25:25)
8 verbose stack     at asyncForEach (/usr/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:11:31)
8 verbose stack     at thenProcessChildren (/usr/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:200:12)
8 verbose stack     at f (/usr/lib/node_modules/npm/node_modules/once/once.js:25:25)
9 verbose cwd /home/josep/Documentos/dev/mytop
10 verbose Linux 3.16.0-4-amd64
11 verbose argv "/usr/bin/nodejs" "/usr/bin/npm" "i" "mytop@latest" "-g"
12 verbose node v6.10.3
13 verbose npm  v5.0.1
14 error Path must be a string. Received undefined
15 verbose exit [ 1, true ]
$
```
I also tried with fresh setup (removed ~/.npm) same error occurs.
Package installs successfully when I downgrade to npm@4

### supporting information:

 - `npm -v` prints: 5.0.1
 - `node -v` prints: v6.10.3
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux Debian 8.8 Jessie 3.16.0-4-amd64 
 - Network issues:
   - Geographic location where npm was run: Spain
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

Thank you for your attention

**Comment by warlock** [comment]
I re-upgraded to npm@5.0.1 and now works. Sorry for the inconvenience. I leave the issue in case you want to review.

**Comment by hinaloe** [comment]
I have same issue on OSX, but cannot work with re-install npm 🤕

**Comment by roccomuso** [comment]
Same issue on ubuntu `npm v5.0.3`.
