### ISSUE TITLE
"ng serve" is not auto reloading

### ISSUE THREAD

**Issue by DurgaAbhist** [npm/npm#16915]
Hi Sir, Madam,

I'm Durga Abhist and I recently started working with Angular/CLI tool, I'm facing a problem while executing the file, that is when I run "ng serve " command then this command helps us in auto reloading the site when any changes are made in the source file but in my system it is not happening (i.e. site is not auto reloading and when I forcely reload the site then also it is not getting updated as per changes made in the source file).

The site is getting updated only when I terminate the "ng serve" command and again run the same command("ng serve") then only my site is getting updated.

So it becomes hard for me to terminate the server and connect the server, when ever the changes are made, so I request you Sir/Madam help me out in this issue.

**Comment by gurpreetatwal** [comment]
@DurgaAbhist I'd recommend making the issue on [angular/angular-cli](https://github.com/angular/angular-cli/issues/new) as it seems like your issue is more with the cli and not npm. Best of luck!
