### ISSUE TITLE
Updating from v4.0.0 to v6.10.3 broke my node

### ISSUE THREAD

**Issue by Crysalist** [npm/npm#16914]
#### I'm opening this issue because:

  - [*] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Getting this after I installed latest version from .msi from the node website.
`>npm ls -g --depth=0
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\xxxxxxx\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "ls" "-g" "--depth=0"
npm ERR! node v6.10.3
npm ERR! npm  v3.8.5
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'realize-package-specifier'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Development\2017Eldev.local\npm-debug.log`
`>npm outdated -g
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\xxxxxxx\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "outdated" "-g"
npm ERR! node v6.10.3
npm ERR! npm  v3.8.5
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'realize-package-specifier'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Development\2017Eldev.local\npm-debug.log`

#### How can the CLI team reproduce the problem?
No idea

### supporting information:

 - `npm -v` prints: `3.8.5`
 - `node -v` prints: `v6.10.3`
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?: Windowsn
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [*] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [*] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by varjmes** [comment]
Hi there,

Could you try updating npm?

`npm install -g npm`

**Comment by Crysalist** [comment]
Same issue:
`npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe"
"C:\\Users\\XXXXXX\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "npm"
npm ERR! node v6.10.3
npm ERR! npm  v3.8.5
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'realize-package-specifier'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Repo\XXXXXXX\Admin\Source\Dev\npm-debug.log`

**Comment by Crysalist** [comment]
Fixed this by uninstalling completely [StackOverFlowHowTo](https://stackoverflow.com/questions/20711240/how-to-completely-remove-node-js-from-windows) and reinstalling.

**Comment by qborreda** [comment]
Happens on Mac as well .. 

$ sudo npm i -g npm
npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "-g" "npm"
npm ERR! node v7.7.3
npm ERR! npm  v4.1.2
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'realize-package-specifier'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by emorling** [comment]
Any ideas?

**Comment by marcysutton** [comment]
I have this same problem on a Mac. I wish the issue hadn't been closed, because I can't even uninstall npm with `sudo npm uninstall -g npm`. It fails with the same "cannot find module" error.

**Comment by j0sky** [comment]
Same problem on Mac.
