### ISSUE TITLE
npm@5: Incorrect unmet peer dependency error

### ISSUE THREAD

**Issue by jhermsmeier** [npm/npm#16925]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other: It is displaying an incorrect error

#### What's going wrong?

Dependencies are correctly installed, but a warning is emitted during installation, and an error when listing modules even though all requirements are properly satisfied. This behavior can be observed with both `npm@5.0.0` and `npm@5.0.1`, and regardless of the depth of the dependency in the tree.

#### How can the CLI team reproduce the problem?

1. Install `w3cjs` with `npm install w3cjs`
2. A warning will be emitted:
  ```
  npm WARN superagent-proxy@0.3.2 requires a peer of superagent@>= 0.15.4 && < 2 but none was installed.
  ```
3. Check whether `w3cjs` actually declares `superagent` as a dependency:
  ```
  $ npm info w3cjs dependencies
  
  { commander: '~2.6.0',
    superagent: '~0.21.0',
    'superagent-proxy': '^0.3.1' }
  ```
4. List dependencies with `npm ls`
5. An unmet peer dependency error will be displayed, even though the module in question *has been installed* by the previous step and meets `superagent-proxy`'s peer dependency requirement of `"superagent": ">= 0.15.4 && < 2"`:
```
  $ npm ls --depth 2
npm-peer-dep-test@0.0.0 /Users/Jonas/Code/npm-peer-dep-test
└─┬ w3cjs@0.3.0
  ├── commander@2.6.0
  ├─┬ UNMET PEER DEPENDENCY superagent@0.21.0
  │ ├── component-emitter@1.1.2
  │ ├── cookiejar@2.0.1
  │ ├── debug@2.6.8
  │ ├── extend@1.2.1
  │ ├── form-data@0.1.3
  │ ├── formidable@1.0.14
  │ ├── methods@1.0.1
  │ ├── mime@1.2.11
  │ ├── qs@1.2.0
  │ ├── readable-stream@1.0.27-1
  │ └── reduce-component@1.0.1
  └─┬ superagent-proxy@0.3.2
    ├── debug@2.2.0
    └── proxy-agent@1.1.1

npm ERR! peer dep missing: superagent@>= 0.15.4 && < 2, required by superagent-proxy@0.3.2
```

### supporting information:

 - `npm -v` prints: 5.0.1
 - `node -v` prints: v8.0.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by zkat** [comment]
@jhermsmeier for some weird reason, it seems like npm@<5 was parsing these semver ranges in loose mode, and that disappeared with the new changes. See https://github.com/npm/npm/pull/17007

**Comment by jhermsmeier** [comment]
@zkat oh, thanks for the quick resolution on this one! Totally missed that the version range wasn't a valid semver range. I've sent a pull request to the module in question to update those dependencies, fixing the invalid ranges. Maybe npm could issue a warning or error when attempting to publish modules with invalid semver ranges (when parsed in non-loose mode) from now on?

**Comment by zkat** [comment]
@jhermsmeier we were _supposed_ to be parsing them in loose mode and that somehow got lost. People put the most amazing things in their `peerDependencies`. I don't think any of that code warns right now, though, and I think it would be way too noisy if it did. Perhaps warning for authors would make sense, though. That'd be a nice PR maybe 👍

**Comment by jhermsmeier** [comment]
@zkat I see – I'll try and fumble a working contraption together & PR that.

**Comment by benwiley4000** [comment]
@zkat Could you clarify what about the version specification here failed non-loose mode?

**Comment by jhermsmeier** [comment]
@benwiley4000 it's the `&&` in the peer dependency version range – see https://github.com/npm/node-semver#ranges for details

**Comment by benwiley4000** [comment]
I see, so it's proper to just leave out the `&&` - got it! 😄
