### ISSUE TITLE
npm@5 install mangles unicode characters in package.json strings

### ISSUE THREAD

**Issue by eamodio** [npm/npm#16927]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I have a `package.json` file that has unicode characters in it 
```json
    "displayName": "Git Lens \u2014 git blame annotations, code lens, and more",
```

And after running `npm install` it becomes:
```json
    "displayName": "Git Lens â€” git blame annotations, code lens, and more",
```

This isn't only a problem with the `description` field, and is also new in npm 5 -- I didn't have any issues before.

#### How can the CLI team reproduce the problem?

Creating a `package.json` with a string like above

### supporting information:

 - `npm -v` prints: `5.0.1`
 - `node -v` prints: `v7.10.0`
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?: `Windows`
 - Network issues:
   - Geographic location where npm was run: `Northeastern US`
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by zkat** [comment]
:headscratch: I don't know where we'd be reading things in non-utf8 or writing them out like that. `save` already uses utf8 when writing these files. And `read-package-json` uses utf8 when reading them 🤔

**Comment by eamodio** [comment]
@zkat are you able to reproduce the issue? It seems anytime I add any character like `\u2014` to a string in `package.json` it produces this result.

And this was never an issue before npm 5

FYI -- I just tried this on macOS and I see the same behavior. Though I noticed that my editor (vscode) was detecting a `windows 1252` encoding after the `npm install`, if I set it back to `utf8` then it shows `—` rather than `â€”` which is the correct character, but I want it to stay `\u2014` in my file.

**Comment by zkat** [comment]
🤔 I can't actually repro this. That's the weird thing. Not even if I drop down to `5.0.1` 🤔 

I wonder if you somehow got a mixed-up version of npm. I really don't know why you'd be seeing this, as anything that writes package.json is explicitly writing it as `utf8`...

**Comment by eamodio** [comment]
So if you add `"\u2014"` to the `description` field, run `npm install`, you still see `"\u2014"` in the `package.json` afterward and not `"—"`?

I've tried this on 2 machines, Windows and macOS, different projects, upgraded to `5.0.3`, wiped out the npm folder completely and re-installed, and still I always see the same behavior.

**Comment by zkat** [comment]
Oh no, I see `—` which is valid, since that's what that character is. That's also how node itself represents it:

```
➜ node -p '"\u2014"'
—
```

What *shouldn't* be changing is the encoding of the file to be non-`utf8`.

**Comment by eamodio** [comment]
@zkat I don't think it was actually changing the encoding -- I think vscode was just detecting `windows 1252` because of that character being `—` rather than `\u2014`.

But I *really* don't want npm to change `\u2014` into `—` -- I definitely want it to stay `\u2014`.

**Comment by zkat** [comment]
It _is_ `\u2014` -- it's just a different representation of the same thing. That's how JavaScript is gonna show it to you, and there's really nothing I can reasonably do about this :\

**Comment by eamodio** [comment]
Right, but the representation I want -- and what is committed to git is `\u2014` -- so I can search my source code for all my unicode characters (`\u*` is far easier than actually using the individual characters), etc. And I just don't want npm changing that representation

And imo to make things worse, this happens even if npm changes nothing else in the `package.json`. It seems like it shouldn't modify the file at all if there is nothing to do. (Or honestly ever with an `npm install` because that doesn't really change the `package.json` at all does it?)

**Comment by zkat** [comment]
@eamodio I hear you -- I just don't think that's a thing we can pull off without an immense amount of effort: this transformation is done by things as low-level as `JSON.parse()`, which npm uses to read in `package.json`. And it needs to have read it in, in order to read it out. We'd need a custom JSON parser just for this use-case.

The only way I think you're gonna be able to do this is by having npm not read or write `package.json` -- that is, to use the `--no-save` flag, avoid using `npm version`, and anything else that might do an edit to that file.

If you _do_ come up with a way to preserve this, though (which I hope would not involve rewriting half our codebase?), then I think we could talk about a patch. I just have no idea, honestly, how to satisfy this any other way right now.

**Comment by eamodio** [comment]
@zkat Gotcha -- and can certainly appreciate that. Curiously why wasn't this ever an issue with npm 4? Also should `npm install` with no args really ever modify the `package.json`? I personally could be fine with living with this if it didn't happen on every `npm install`

**Comment by zkat** [comment]
@eamodio `npm@4` only writes your `package.json` if you do `npm i --save` or similar, or if you use `npm version`, so things like these wouldn't happen so often.

Since `npm@5` saves by default, that means it'll do all that modification. I'm not sure how tricky it would be to make it not write the file if you just do `npm install`, and that seems like a relatively low-value band-aid over the issue.

**Comment by eamodio** [comment]
Ah that explains it -- I never use `--save`, I just edit/add packages to the `package.json` directly and then run `npm install`, so that explains the behavior difference. IMO at least, I think it is worth while to stop saving the `package.json` with `npm install` -- I agree its a band-aid for this issue, but it seems like modifying a file with a command that shouldn't modify the file is just asking for issues ;) My 2c at least.

Thanks again for you help on this.

**Comment by zkat** [comment]
It's one of the limitation of JSON as a format. We're regularly exploring alternatives and trying to figure out how tf we'd be able to make them more widely available to the ecosystem without breakage, but until such a time as we don't rely on `package.json`, this is what we're able to work with.

Thanks to you too for taking the time to talk through this and help me understand what you were looking for! Should I close this issue?

**Comment by eamodio** [comment]
Personally I'd like it to be addressed (at a minimum for `npm install` -- w/o args), but I understand where you are coming from and if it just isn't reasonable (or worth it), then feel free to close it.

**Comment by zkat** [comment]
@eamodio mind opening a new issue as an explicit request to stop npm from writing `package.json` on a simple `npm install`?

**Comment by eamodio** [comment]
Will do -- thanks!

**Comment by zkat** [comment]
cool!

**Comment by eamodio** [comment]
@zkat Thanks again for your time and help -- it is greatly appreciated!

**Comment by zkat** [comment]
Ditto. Cheers!
