### ISSUE TITLE
Error: ENOENT, lstat '/usr/local/lib/node_modules/truffle/node_modules/ethpm/node_modules/ipfs/node_modules/libp2p-ipfs-nodejs/node_modules/libp2p/node_modules/libp2p-ping/node_modules/libp2p-crypto/dist/index.js.map'

### ISSUE THREAD

**Issue by alxiong** [npm/npm#16923]
#### I'm opening this issue because:

  - [* ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
It stops installing and halts after the error. 

#### How can the CLI team reproduce the problem?

 System Linux 4.4.0-43-Microsoft
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "truffle"
npm ERR! cwd /mnt/c/Users/Alex Xiong
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /usr/local/lib/node_modules/truffle/node_modules/ethpm/node_modules/ipfs/node_modules/libp2p-ipfs-nodejs/node_modules/libp2p/node_modules/libp2p-ping/node_modules/libp2p-crypto/dist/index.js.map
npm ERR! fstream_path /usr/local/lib/node_modules/truffle/node_modules/ethpm/node_modules/ipfs/node_modules/libp2p-ipfs-nodejs/node_modules/libp2p/node_modules/libp2p-ping/node_modules/libp2p-crypto/dist/index.js.map
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)

**Comment by zkat** [comment]
This is a very very old, unsupported version of npm. I'm afraid I can't help you here. Please update both node and npm, since the versions of both that you're using are now out of maintenance.
