### ISSUE TITLE
npm@5 - fresh install misses dependencies if private package AND preinstall script are used

### ISSUE THREAD

**Issue by analytik** [npm/npm#16944]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Package.json that worked under npm 4.6.1 don't work in 5.0.0, 5.0.1, 5.0.2. Some top-level dependencies are missing in case of a clean install, **only when BOTH preinstall script and a private package are used**.

#### How can the CLI team reproduce the problem?

Artifacts reported here for npm 5.0.2.

1. Download [package.json](https://gist.github.com/analytik/9b257ea174701f9a01941be65f35f8cf) 
1. There is a private package mentioned - replace it with any private package that has
```
  "dependencies": {
    "lodash": "^4.17.4"
  },
```
1. Delete node_modules and package-lock.json or other artifacts.
1. Run `npm i`.
1. Notice package.json specifies dependency `lodash ^4.15.0`, but there is no `node_modules/lodash/`. There is lodash scattered around in other modules. Total size of node_modules is 74MB. NPM install will output something like `added 734 packages in 135.207s`.
1. Delete node_modules, package-lock.json again.
1. Remove private dependency OR the line `"preinstall": "npm prune",` OR both.
1. Run `npm i` - the result will be something like `added 1095 packages in 180.406s` and node_modules will be around 179MB.

### supporting information:

 - `npm -v` prints: 5.0.2
 - `node -v` prints: 7.7.4
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Win 7 x64

**Comment by zkat** [comment]
This is working fine for me in the latest canary, and will be available in the next npm release (soon)
