### ISSUE TITLE
npm install fails on mac.

### ISSUE THREAD

**Issue by ghost** [npm/npm#16946]
#### I'm opening this issue because:

  - [X] npm is crashing.

#### What's going wrong?
I don't have he package.json installed so I tried different things such as **npm install**.

#### How can the CLI team reproduce the problem?
It just typed : 
npm cache clean
sudo npm install -g npm
npm install

I got a log file ( seems to go well until ) :

157 http fetch GET 200 https://registry.npmjs.org/spdx-license-ids 29ms
158 silly pacote range manifest for spdx-expression-parse@~1.0.0 fetched in 67ms
159 silly pacote range manifest for builtin-modules@^1.0.0 fetched in 63ms
160 silly pacote range manifest for spdx-license-ids@^1.0.2 fetched in 44ms
161 http fetch GET 200 https://registry.npmjs.org/error-ex 120ms
162 silly pacote range manifest for error-ex@^1.2.0 fetched in 126ms
163 http fetch GET 200 https://registry.npmjs.org/is-arrayish 32ms
164 silly pacote range manifest for is-arrayish@^0.2.1 fetched in 38ms
165 error cb() never called!
166 error This is an error with npm itself. Please report this error at:
167 error <https://github.com/npm/npm/issues>

### supporting information:

 - `npm -v` prints: 5.0.2
 - `node -v` prints: v6.10.3
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: OS X.

Thanks

**Comment by AlexxNica** [comment]
If I understand correctly, you don't have a `package.json` file, right? If this is the case, then try running `npm init` before doing another `npm install`.

You should first init your package.json (`npm init`) to make use of any other npm commands.

Try that and give us feedback to whether it worked or not! ✌️

**Comment by ghost** [comment]
Thanks a lot. It works (well I don't have any issue now). The example I had just didn't talk about the **npm init** and when I looked for the error I had, I found the group of commands to run which led to the issue I am talking about .

**Comment by AlexxNica** [comment]
Alright, if you happen to have any other problems, just create a new issue and we'll be happy to help! 🤓
