### ISSUE TITLE
Doesn't work --> npm install npm@lastest -g

### ISSUE THREAD

**Issue by JaviRpo** [npm/npm#16951]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
The command doesn't work --> 
[2017-06-03T17_37_42_172Z-debug.log.txt](https://github.com/npm/npm/files/1049764/2017-06-03T17_37_42_172Z-debug.log.txt)

npm install npm@lastest -g

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [x] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [x] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by MichaelBeier** [comment]
Try using `npm i -g  npm@latest` instead ;)

**Comment by JaviRpo** [comment]
thanks, it works
