### ISSUE TITLE
npm 5 fails to install aframe; doesn't follow forwards

### ISSUE THREAD

**Issue by devpaul** [npm/npm#16954]
#### I'm opening this issue because:

  - [X] npm is producing an incorrect install.

#### What's going wrong?

I believe npm is not correctly following forwards.

I am running npm @ 5.0.2 and when I run `npm i aframe` It fails:

```
907 silly fetchPackageMetaData error for webvr-polyfill@git://github.com/dmarcos/webvr-polyfill.git#a02a8089b755e7e306676030e281d81668adb87d Command failed: /usr/bin/git checkout a02a8089b755e7e306676030e281d81668adb87d
907 silly fetchPackageMetaData fatal: reference is not a tree: a02a8089b755e7e306676030e281d81668adb87d
908 verbose stack Error: Command failed: /usr/bin/git checkout a02a8089b755e7e306676030e281d81668adb87d
908 verbose stack fatal: reference is not a tree: a02a8089b755e7e306676030e281d81668adb87d
908 verbose stack
908 verbose stack     at ChildProcess.exithandler (child_process.js:206:12)
908 verbose stack     at emitTwo (events.js:106:13)
908 verbose stack     at ChildProcess.emit (events.js:191:7)
908 verbose stack     at maybeClose (internal/child_process.js:877:16)
908 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
909 verbose cwd /Users/pshannon/src/DefinitelyTyped/types/aframe
910 verbose Darwin 15.6.0
911 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "aframe" "--save-dev"
912 verbose node v6.10.0
913 verbose npm  v5.0.2
914 error code 128
915 error Command failed: /usr/bin/git checkout a02a8089b755e7e306676030e281d81668adb87d
915 error fatal: reference is not a tree: a02a8089b755e7e306676030e281d81668adb87d
916 verbose exit [ 1, true ]
```

I believe it is because aframe @ 5 has a dependency on `dmarcos/webvr-polyfill` which now forwards to `aframevr/webvr-polyfill`.

Installed npm @ 4 and `npm i aframe` works fine.

#### How can the CLI team reproduce the problem?

`npm i aframe@0.5.0`

### supporting information:

 - `npm -v` prints: 5.0.2
 - `node -v` prints: v6.10.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: OS X

**Comment by zkat** [comment]
Can you repro this with `npm@5.0.4`, or with the canary (`npm i -g npmc@latest && npmc -v`)? There's been a bunch of git- and installer-related fixes recently.

**Comment by zkat** [comment]
I can't repro this on the latest canary, so closing as fixed.
