### ISSUE TITLE
Refusing to install redux as a dependency of itself

### ISSUE THREAD

**Issue by patzj** [npm/npm#16958]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?
`Refusing to install redux as a dependency of itself`
#### How can the CLI team reproduce the problem?
I'm trying to install redux on ~/workspace/redux using `npm install redux --save`.
npm-debug.log: https://gist.github.com/patzj/5d8f0f292eb949fc6a9ee7d55d96de06

### supporting information:

 - `npm -v` prints: 3.10.10
 - `node -v` prints: v6.10.3
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux 4.8.0-52-generic `#55`-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
Make sure the `"name"` property in your `package.json` is not set to `"redux"`; make it something more unique. You may have to rename the directory as well.

**Comment by patzj** [comment]
@KenanY Thank you.
