### ISSUE TITLE
npm install failed with airsonos on OS Sierra 10.12.5

### ISSUE THREAD

**Issue by tylo6** [npm/npm#16969]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
when i commandeline : npm install airsonos -g

### supporting information:

 - `npm -v` prints: 3.10.10
 - `node -v` prints: v6.10.3
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?: macOS Sierra 10.12.5
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [x] I develop using Vagrant on OS X or Linux. (for the first time)
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

![capture d ecran 2017-06-04 a 20 47 28](https://cloud.githubusercontent.com/assets/15964260/26774244/ac121502-49cf-11e7-82d8-66e23283dcb7.png)

**Comment by kenany** [comment]
Closing since this issue is blank. Can reopen once more information is provided.
