### ISSUE TITLE
npm install failed with airsonos on Apple

### ISSUE THREAD

**Issue by tylo6** [npm/npm#16977]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
when i commandeline : npm install airsonos -g

### supporting information:

 - `npm -v` prints: 3.10.10
 - `node -v` prints: v6.10.3
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?: macOS Sierra 10.12.5
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [x] I develop using Vagrant on OS X or Linux. (for the first time)
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

#### What's the feature?
i want to install airsonos

#### What problem is the feature intended to solve?
in shell i've : npm WARN addRemoteGit git://github.com/stephen/node-sonos.git#stephen-1.0.0 resetting remote /Users/marc/.npm/_git-remotes/git-github-com-stephen-node-sonos-git-stephen-1-0-0-6a58f9b2 because of error: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

#### Is this feature similar to an existing feature in another tool?
no
#### Is this a feature you're prepared to implement, with support from the npm CLI team?
i think yes
-->
![capture d ecran 2017-06-04 a 20 47 28](https://cloud.githubusercontent.com/assets/15964260/26774244/ac121502-49cf-11e7-82d8-66e23283dcb7.png)

**Comment by walshie4** [comment]
It looks like you are running on OS X and possibly need the CommandLineTools package.  You can install it using `xcode-select --install`
