### ISSUE TITLE
Using NPM download files can't download always stuck for a long time, and close the window when they jump out of a pair of error, using taobao mirror download file is stuck, not want to use CNPM instead of NPM

### ISSUE THREAD

**Issue by chenyijie-bit** [npm/npm#16975]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by zkat** [comment]
Can you give more details about this? Do you have a log?

**Comment by chenyijie-bit** [comment]
I took a picture yesterday to show you, but I didn't find a place to pass the picture. How can I pass it on to you?

**Comment by chenyijie-bit** [comment]
KZM hello, I'm consulting you on making the problem of NPM, my real name is Chen jie, sincerely hope you can help me, I send you you see an error screenshots of, thank you.My email address, chenyjbba@163.com

**Comment by zkat** [comment]
@chenyjyoucan You can upload a picture by clicking here:
<img width="582" alt="screen shot 2017-06-05 at 20 46 48" src="https://cloud.githubusercontent.com/assets/17535/26813036/54b1cdaa-4a30-11e7-809f-3c9955f108bb.png">

**Comment by chenyijie-bit** [comment]
![02](https://cloud.githubusercontent.com/assets/23470635/26814301/20cb2860-4ab7-11e7-8082-e5a5c8a03177.png)

**Comment by zkat** [comment]
Yeaaaah. I've no idea what this error's about.

**Comment by chenyijie-bit** [comment]
In fact, I this download is not an error, just stuck, motionless, like the image below for a long time won't have any change, then close this window will appear when the picture that I sent to you just now an error. I don't this what the configuration or any mistake, so that won't do to change the computer?
![04](https://cloud.githubusercontent.com/assets/23470635/26814549/00f016de-4ab9-11e7-821c-039d50fe3f8c.png)

**Comment by zkat** [comment]
@chenyjyoucan you might be having proxy/firewall issues here :\

Please go over https://github.com/npm/npm/blob/latest/TROUBLESHOOTING.md#proxy-and-networking-issues

**Comment by kenany** [comment]
Moving to https://github.com/npm/npm/issues/17132.
