### ISSUE TITLE
Uninstall an global package

### ISSUE THREAD

**Issue by NoahDragon** [npm/npm#16971]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

The npm is crashed when trying to uninstall an global package. 
Got an exception:
```
Unhandled rejection Error: Argument #2: Expected string but got null0
...
npm ERR! cb() never called!
```

#### How can the CLI team reproduce the problem?

The following file is the output log when runs the command `npm uninstall http-server -g`.

[2017-06-04T22_17_28_001Z-debug.log.txt](https://github.com/npm/npm/files/1050761/2017-06-04T22_17_28_001Z-debug.log.txt)

### supporting information:

 - `npm -v` prints: 5.0.2
 - `node -v` prints: 8.0.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: OS X

**Comment by cedvdb** [comment]
got the same right now when trying to uninstall angular cli globally. Happened after `clean cache --force`


```
Unhandled rejection Error: Argument #2: Expected string but got null deep-exten
    at addDependency (/usr/lib/node_modules/npm/lib/install/deps.js:515:3)

npm ERR! cb() never called!

```

same when trying to uninstall (to reinstall) ` npm sudo npm uninstall npm -g`

```
Unhandled rejection Error: Argument #2: Expected string but got nullinstall loadIdealTree
    at addDependency (/usr/lib/node_modules/npm/lib/install/deps.js:515:3)

```

**Comment by NoahDragon** [comment]
Temp solution, update the global package via reinstall it
```
npm i -g http-server
```
then run
```
npm uninstall -g http-server
```
fix the issue.
