### ISSUE TITLE
(v5) Code E404 for public git repository

### ISSUE THREAD

**Issue by varjmes** [npm/npm#16979]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

When trying to install a public git dependency I get the following on npm 5, npm 5.0.2 and npm 5.0.3 (next):

```
npm ERR! code E404
npm ERR! 404 Not Found: ustyle-react@0.0.12
```

#### How can the CLI team reproduce the problem?

npm install with the following package.json

https://gist.github.com/Charlotteis/379fbb569b63f45084e1d914326f7187

Here are the logs:

https://gist.github.com/Charlotteis/41903f79736ac3bd2d36714ce4b0cd32

### supporting information:

 - `npm -v` prints: `5.0.2`
 - `node -v` prints: `8.0.0`
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?: OSX.

**Comment by varjmes** [comment]
I've downgraded to `4.6.1` for now and all is working. Although it's much slower which is yet another testament to the awesome that is npm 5 😎

**Comment by zkat** [comment]
@Charlotteis what does your `package-lock.json` look like? I can't repro this.

**Comment by varjmes** [comment]
I'm very sorry, I should have removed package-lock.json and started again.
All is working now, but for reference, here is the lock:

https://gist.github.com/Charlotteis/a07c161257f9c68e7fd61d467bb5a903
