### ISSUE TITLE
getting an error when trying to install GULP

### ISSUE THREAD

**Issue by ccrayton** [npm/npm#16978]
So im trying to install GULP on my mac using npm install gulp-cli --global, any suggestions on why? Thanks!

![screen shot 2017-06-05 at 12 25 40 am](https://cloud.githubusercontent.com/assets/19902713/26774903/558ea1b6-4987-11e7-870b-b374ce0d392f.png)

**Comment by ccrayton** [comment]
found out prefixing the command by sudo helped......sudo npm install gulp-cli --global.....asks for administrators password and then installed successfully.

**Comment by kenany** [comment]
Closing as resolved then.
