### ISSUE TITLE
Invalid name: "@ionic/cli-utils"

### ISSUE THREAD

**Issue by LiveRock** [npm/npm#16983]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [X ] Other (_see below for feature requests_):

#### What's going wrong?
on Mac Pro Sierra
sudo npm install -g ionic

ionic install aborted with following error:
Invalid name: "@ionic/cli-utils"

#### How can the CLI team reproduce the problem?
npm install -g cordova ionic

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by brentvatne** [comment]
@LiveRock - you need to fill out the supporting information otherwise this bug report is not very useful. what version of node / npm? what registry? etc.
