### ISSUE TITLE
npm5 install fails on EINVALIDTAGNAME for specific package

### ISSUE THREAD

**Issue by MadaraUchiha** [npm/npm#16981]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [v] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
```
$ npm i systemjs-nodelibs
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "jspm-nodelibs-util@^0.2.0": Tags may not have any characters that encodeURIComponent encodes.
```
#### How can the CLI team reproduce the problem?

1. Create dummy directory
2. `npm init -y`
3. `npm install systemjs-nodelibs`
4. Expected: Install succesfully (works with 4), actual: Fails with error above.

### supporting information:

 - `npm -v` prints: `5.0.2`
 - `node -v` prints: `8.0.0`
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?: Windows
 - Network issues:
   - Geographic location where npm was run: Israel
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by zkat** [comment]
Patch up for this: https://github.com/npm/npm/pull/17005

The `peerDependencies` field in a lot of these related libraries seem like total invalid garbage and have never actually worked, but I've stopped npm from crashing when running into them. They are now reported as unmet peerDeps, like `npm@4` currently does.

**Comment by MadaraUchiha** [comment]
@zkat Thanks! I kinda want them to fail optionally (or even by default) with a flag, so that package maintainers fix their broken package.json files.

Think it can be arranged for a flag to optionally enable the stricter, failing, check?

**Comment by zkat** [comment]
I think this is the sort of thing that might be added to https://github.com/npm/normalize-package-data

**Comment by MadaraUchiha** [comment]
@zkat Hey, it's been a while and we still can't use npm 5 😢, when will the fix for this land?

**Comment by vlkmx** [comment]
go to:
/Users/'user_name'/.npm/_logs/   
and delete all files
It helped me

**Comment by JasonKleban** [comment]
I can't tell whether my situation should be fixed by this.  

`node -v ; npm -v ; npm install --save appdynamics@4.3.5` gives:

```
v8.4.0
5.4.1
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "protobuf@": Tags may not have any characters that encodeURIComponent encodes.

npm ERR! A complete log of this run can be found in: ...
```

```
...
8 silly pacote version manifest for appdynamics@4.3.5 fetched in 660ms
9 verbose stack Error: Invalid tag name "protobuf@": Tags may not have any characters that encodeURIComponent encodes.
9 verbose stack     at invalidTagName ([~]\AppData\Roaming\npm\node_modules\npm\node_modules\npm-package-arg\npa.js:76:15)
9 verbose stack     at fromRegistry ([~]\AppData\Roaming\npm\node_modules\npm\node_modules\npm-package-arg\npa.js:265:13)
9 verbose stack     at Function.resolve ([~]\AppData\Roaming\npm\node_modules\npm\node_modules\npm-package-arg\npa.js:66:12)
9 verbose stack     at doesChildVersionMatch ([~]\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:67:25)
9 verbose stack     at versionMatch ([~]\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:675:12)
9 verbose stack     at Array.filter (<anonymous>)
9 verbose stack     at exports.findRequirement ([~]\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:685:23)
9 verbose stack     at exports.findRequirement ([~]\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:693:10)
9 verbose stack     at findChild ([~]\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:101:17)
9 verbose stack     at computeMetadata ([~]\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:112:9)
9 verbose stack     at tree.children.filter.forEach ([~]\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:124:87)
9 verbose stack     at Array.forEach (<anonymous>)
9 verbose stack     at computeMetadata ([~]\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:124:68)
9 verbose stack     at Installer.normalizeCurrentTree ([~]\AppData\Roaming\npm\node_modules\npm\lib\install.js:373:3)
9 verbose stack     at Array.<anonymous> ([~]\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
9 verbose stack     at LOOP ([~]\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
```

We have a corporate Synopia installation that proxies all these package installations, but I don't know if that has anything to do with it.

**Comment by JasonKleban** [comment]
Well, wiping out node_modules and `npm install ; npm install --save appdynamics@4.3.5` worked for me.  Some corruption?

**Comment by nsdeo12** [comment]
Please try with this command `npm install -g npm ` 
It solved the error for me.

**Comment by ofarukcaki** [comment]
If you have **space** in your folder name just delete it.

**Comment by kucherenkovova** [comment]
```
rm package-lock.json
npm i
```
worked for me
