### ISSUE TITLE
npm ERR! Registry returned 500 for GET 

### ISSUE THREAD

**Issue by jmontano87** [npm/npm#16999]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):
[npm-debug.txt](https://github.com/npm/npm/files/1053201/npm-debug.txt)

#### How can the CLI team reproduce the problem?
I tried to install the npm install cisco-cmx-mobile-app-server-simulator.tgz but not works

**Comment by kenany** [comment]
Might be something for the registry team to look at:

```
$ curl https://registry.npmjs.org/cisco-cmx-mobile-app-server-simulator.tgz
{"code":"InternalError","message":"tmpUrl.indexOf is not a function"}
```

@jmontano87 Are you following a guide somewhere which is asking you to install that package? It does not exist in the registry, hence why the command is failing.

**Comment by iarna** [comment]
We're closing this support issue as it has gone three days without activity.  The npm CLI team itself does not provide support via this issue tracker, but we are happy when users help each other here.  In our experience once a support issue goes dormant it's unlikely to get further activity.  If you're still having problems, you may be better served by joining [package.community](https://package.community/) and asking your question there.

For more information about our new issue aging policies and why we've instituted them please see our [blog post](http://blog.npmjs.org/post/161832149430/npm-the-npm-github-issue-tracker-and-you).
