### ISSUE TITLE
[NPM@5.0.2] Incorrect cwd in postinstall when installing local package

### ISSUE THREAD

**Issue by sis0k0** [npm/npm#16990]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

When local package is installed with npm 5, a symlink is created instead of copying the files to node_modules. If the package runs a postinstall script with a reference to the current working directory, the location of the linked module will be returned instead of the project's location.

#### How can the CLI team reproduce the problem?

Let's say you have a package `/home/user/somepackage` with the following postinstall script:
```
// /home/user/somepackage/package.json
{
...
  "scripts": {
    "postinstall": "node postinstall-script.js"
  }
}
```
where `postinstall-script.js` has the following content:
```
console.log(__dirname);
console.log(process.cwd());
console.log(process.env.PWD);
```

If you install the package in some project you will get `/home/user/somepackage`. Doing the same with npm3<= results in: `/home/user/someproject/node_modules/somepackage`.
This can be a problem for packages that need the project root directory for performing some postinstall actions.

### supporting information:

 - `npm -v` prints: 5.0.2
 - `node -v` prints: 8.0.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Tested on Linux

**Comment by zkat** [comment]
Ooh, nice find. I think this might actually explain other bugs we were having with `postinstall`...

**Comment by shadowmint** [comment]
Damn, this just bit me as well. This definitely also affects mac.

**Comment by iarna** [comment]
Ok, so some details:
1. This only effects symlinked installs, eg, when you install with a `file:` specifier.
2. It seems impossible to get `process.pwd()` to report the correctly. =/ That  makes this change more breaking than I'd hoped.

My proposed solution is twofold:

1. We start exporting the root folder of the project in the environment (as this is often what you're looking for).
2. We start exporting the logical package location, that is, from the point of the view of the symlink not the destination of the symlink. This would give you access to the same value that `process.pwd()` used to be sufficient to get.

How does this sound?

**Comment by shadowmint** [comment]
Sounds good! Couple of points:

- This is a really nasty breaking change. It basically generates a bunch of 'hidden' breaking behaviour where packages work perfectly until you try to install them from a local clone; and even then on say, windows, it works fine, but on a symlink supported platform, it breaks. You can pretty guarantee you'll see more issues raised about this incrementally over time as more people stumble into it.

- Please don't change any existing behaviour for packages that are installed normally~

- This obviously potentially affects any lifecycle scripts which are executed per package, not just postinstall (eg. uninstall). I can't think of any obvious examples, but worth thinking about.

- Using symlinks also doesn't honour the `files` section in `package.json` (or `.npmignore`), which although I suppose minor, may cause other related problems for some people.

- How will the new 'base install path' be passed to scripts? An argument, a local env variable?

For anyone else who finds this later, here is the related RFC with the justification for this change https://github.com/npm/npm/pull/15900, such as it is.

**Comment by elclanrs** [comment]
This is the very bug I have that I thought was being reported here https://github.com/npm/npm/issues/16772#issuecomment-311414990.

My workaround so far is to pass the project directory as an environment variable when installing the package locally:

```sh
#!/bin/bash

export PATH_PROJECT="${PATH_PROJECT:-$PWD}"
```

And then in your project install the package with:

```sh
PATH_PROJECT="$PWD" npm install file:/path/to/package
```

**Comment by shadowmint** [comment]
See https://github.com/npm/npm/pull/12356

You can now use INIT_CWD to find the correct original directory.

This is a fix released in 5.4, which finally offers a meaningful alternative to just 'downgrade to npm 4'.

(This issue should probably be closed; although it's not resolved, there seems no meaningful indication that anyone is even looking at it, and 'will never fix' is probably the resolution now a work around exists)

**Comment by elclanrs** [comment]
@shadowmint, my takeaway after months tracking some of these issues is that the lack of attention may be a way to discourage people from using preinstall and postinstall, given that this and other issues that prevent this workflow are still open (like the autopruning, and possibly other issues related to this).

I gave up on trying to adapt our npm@4 workflow. We had to basically rebuild our package as a cli tool that we use with `npx`. In this way we have full control of the working directory, dependencies, and installation lifecycle, but I realize this may not be the right solution for everybody.

**Comment by sis0k0** [comment]
Introducing INIT_CWD in npm 5.4 (#12356) solved the problem for us.
In our postinstall scripts, located in './node_modules/.bin/some-script', we ended up using something like:
```
const projectDir = process.env.INIT_CWD || path.resolve("../../", __dirname);
```
