### ISSUE TITLE
npm run dev error

### ISSUE THREAD

**Issue by Jessie-c** [npm/npm#17006]
$ npm run dev
npm ERR! Windows_NT 6.1.7600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10

npm ERR! missing script: dev
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     G:\vue-demo2\npm-debug.log

**Comment by Jessie-c** [comment]
When using vue - cli scaffolding, there is no global installation of NPM install vue -cli -g.

**Comment by zkat** [comment]
@Jessie-c you need to make sure there's a `"scripts": {"dev": "..."}` entry in your `package.json`.

**Comment by Jessie-c** [comment]
I have a configuration

**Comment by kenany** [comment]
@Jessie-c What do you mean?

**Comment by iarna** [comment]
We're closing this support issue as it has gone three days without activity.  The npm CLI team itself does not provide support via this issue tracker, but we are happy when users help each other here.  In our experience once a support issue goes dormant it's unlikely to get further activity.  If you're still having problems, you may be better served by joining [package.community](https://package.community/) and asking your question there.

For more information about our new issue aging policies and why we've instituted them please see our [blog post](http://blog.npmjs.org/post/161832149430/npm-the-npm-github-issue-tracker-and-you).

**Comment by Jessie-c** [comment]
thanks
