### ISSUE TITLE
Bash eval in NPM script [feature request]

### ISSUE THREAD

**Issue by damianobarbati** [npm/npm#17017]
I'm trying to define the following script in "scripts":

```
"labels": "command --token $(cat config/production.pwd | jq -r .github.token) --other flags"
```

I tried also:

```
"labels": "command --token `cat config/production.pwd | jq -r .github.token` --other flags"
```

Neither of them is working, bash evaluation is not working. How can I achieve it?

This way I can run `npm run labels` which read the credentials from the json file (without pushing it to git).

**Comment by legodude17** [comment]
What is the current output?

**Comment by damianobarbati** [comment]
wtf?! Am I crazy or what? It looks good now o_O

@legodude17 was this fixed/added with the latest 5.x.x upgrades or what? Pretty sure it was broken in 5.0.0, I had to use $() syntax instead of  \`\` backticks syntax.
