### ISSUE TITLE
Installing svn project though svn-modules is failing in npm

### ISSUE THREAD

**Issue by KalpanaPagariya** [npm/npm#17012]
#### I'm opening this issue because:
   - [ ] npm is doing something I don't understand.

#### What's going wrong?
After setting up svn-modules in package.json, fetching svn project is failing as below:

```
 warn react-cc-components@1.0.0 No repository field.
93 verbose If you need help, you may report this error at:
93 verbose     <https://github.com/npm/npm/issues>
94 verbose stack Error: react-cc-components@1.0.0 install: `svn-modules install`
94 verbose stack Exit status 1
94 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
94 verbose stack     at emitTwo (events.js:106:13)
94 verbose stack     at EventEmitter.emit (events.js:191:7)
94 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
94 verbose stack     at emitTwo (events.js:106:13)
94 verbose stack     at ChildProcess.emit (events.js:191:7)
94 verbose stack     at maybeClose (internal/child_process.js:886:16)
94 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
95 verbose pkgid react-cc-components@1.0.0
96 verbose cwd C:\Users\pagariyak\Project\UI_upgrade\8.0.0.0\core\cc\react-cc-components-demo
97 error Windows_NT 10.0.14393
98 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
99 error node v6.10.3
100 error npm  v3.10.10
101 error code ELIFECYCLE
102 error react-cc-components@1.0.0 install: `svn-modules install`
102 error Exit status 1
103 error Failed at the react-cc-components@1.0.0 install script 'svn-modules install'.
103 error Make sure you have the latest version of node.js and npm installed.
103 error If you do, this is most likely a problem with the react-cc-components package,
103 error not with npm itself.
103 error Tell the author that this fails on your system:
103 error     svn-modules install
103 error You can get information on how to open an issue for this project with:
103 error     npm bugs react-cc-components
103 error Or if that isn't available, you can get their info via:
103 error     npm owner ls react-cc-components
103 error There is likely additional logging output above.
104 verbose exit [ 1, true ]
```

### supporting information:

 - `npm -v` prints: 3.10.10
 - `node -v` prints: v6.10.3
 - `npm config get registry` prints: https://registry.npmjs.org/

 - Windows, OS X/macOS, or Linux?: Windows

 - Network issues: No network issue. 
  

[files.zip](https://github.com/npm/npm/files/1054098/files.zip)

**Comment by KalpanaPagariya** [comment]
Can anyone please help? We are stuck here.

**Comment by legodude17** [comment]
Does the command `./node_modules/.bin/svn-modules install` work?

**Comment by iarna** [comment]
We're closing this support issue as it has gone three days without activity.  The npm CLI team itself does not provide support via this issue tracker, but we are happy when users help each other here.  In our experience once a support issue goes dormant it's unlikely to get further activity.  If you're still having problems, you may be better served by joining [package.community](https://package.community/) and asking your question there.

For more information about our new issue aging policies and why we've instituted them please see our [blog post](http://blog.npmjs.org/post/161832149430/npm-the-npm-github-issue-tracker-and-you).
