### ISSUE TITLE
Problems publishing – invalid name

### ISSUE THREAD

**Issue by ashleynolan** [npm/npm#17016]
#### I'm opening this issue because:

  - [x] npm is doing something I don't understand.

#### What's going wrong?

I’m trying to publish a minor release of a module I contribute to – [@justeat/gulp-build-fozzie](https://www.npmjs.com/package/@justeat/gulp-build-fozzie).

Whenever I run `npm publish` I get the response:

`Invalid name: "@justeat/gulp-build-fozzie"`

The error logs aren’t really any clearer to me either:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'publish' ]
2 info using npm@5.0.0
3 info using node@v8.0.0
4 verbose publish [ '.' ]
5 verbose stack Error: Invalid name: "@justeat/gulp-build-fozzie"
5 verbose stack     at ensureValidName (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:300:15)
5 verbose stack     at Object.fixNameField (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:204:5)
5 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:30:38
5 verbose stack     at Array.forEach (native)
5 verbose stack     at normalize (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:29:15)
5 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:349:5)
5 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:124:5)
5 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:311:12
5 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
5 verbose stack     at tryToString (fs.js:499:3)
5 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:487:12)
6 verbose cwd /Users/ashley.nolan/_projects/_sites/Just_Eat/_ui-components/gulp-build-fozzie
7 verbose Darwin 16.6.0
8 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "publish"
9 verbose node v8.0.0
10 verbose npm  v5.0.0
11 error Invalid name: "@justeat/gulp-build-fozzie"
12 verbose exit [ 1, true ]
```

Was wondering if you knew of what might be causing this issue?

### supporting information:

 - `npm -v` prints: v5.0.0
 - `node -v` prints: v8.0.0
 - `npm config get registry` prints:https://registry.npmjs.org/
 - Using macOS Sierra

**Comment by zkat** [comment]
I... have no idea how this is happening, tbh. I tried 5.0.0 with this name, and `normalize-package-data` seems to think this name is just fine. Reading the code tells me the same thing. I wonder if you have an old version lying around because of Node's installer. Could you try updating npm with `npm i -g npm@latest`?

It's an ongoing issue where the Node installer doesn't remove things before extracting, so if you had an old version of a package, you'd sometimes end up loading a very very old one from your previous install. At least that's my suspicion so far. If that's not it, then I guess there's more investigation to be done.

**Comment by ashleynolan** [comment]
@zkat So I think this was being caused by my use of the [n module](https://www.npmjs.com/package/n). Running an update of NPM was erroring out, so I completely uninstalled that module and reinstalled the latest version of node again through homebrew and can now publish again without any issues.

Closing this issue – thanks for the help

**Comment by zkat** [comment]
hah weird. Thanks for the update!
