### ISSUE TITLE
Npm Secound time install issue on another Laravel project  for First project it was working good

### ISSUE THREAD

**Issue by saurabhjdsoft** [npm/npm#17013]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by saurabhjdsoft** [comment]
Log file

**Comment by saurabhjdsoft** [comment]
[debug log.docx](https://github.com/npm/npm/files/1054145/debug.log.docx)

**Comment by kenany** [comment]
@saurabhjdsoft Could you upload the log file as plaintext to <https://gist.github.com/> and link it here? It's easier for me to view it that way, thanks!

**Comment by saurabhjdsoft** [comment]
Please check this issue on github :

&lt;script src="https://gist.github.com/saurabhjdsoft/eafb8b7205a41f3ed77056ce09d41871.js"&gt;&lt;/script&gt;







---- On Tue, 06 Jun 2017 22:48:42 +0530 Kenan Yildirim &lt;notifications@github.com&gt; wrote ----




@saurabhjdsoft Could you upload the log file as plaintext to https://gist.github.com/ and link it here? It's easier for me to view it that way, thanks!

**Comment by saurabhjdsoft** [comment]
https://gist.github.com/saurabhjdsoft/eafb8b7205a41f3ed77056ce09d41871

---- On Tue, 06 Jun 2017 22:48:42 +0530 Kenan Yildirim &lt;notifications@github.com&gt; wrote ----




@saurabhjdsoft Could you upload the log file as plaintext to https://gist.github.com/ and link it here? It's easier for me to view it that way, thanks!

**Comment by kenany** [comment]
Could you try doing

```
npm rebuild node-sass
```

**Comment by saurabhjdsoft** [comment]
Its still not working : 
I don't its working on all other local machines but not on my PC 
Window - 7 64 bit 
node - 6.10.3
npm - 3.10.10

It was working fine on my first laravel project on same machine .
But after deleting that project its not working good.

I have used : npm rebuild node-sass

Check my video for errors: 

https://www.screencast.com/t/kyEd2LqJXuw

**Comment by iarna** [comment]
We're closing this support issue as it has gone three days without activity.  The npm CLI team itself does not provide support via this issue tracker, but we are happy when users help each other here.  In our experience once a support issue goes dormant it's unlikely to get further activity.  If you're still having problems, you may be better served by joining [package.community](https://package.community/) and asking your question there.

For more information about our new issue aging policies and why we've instituted them please see our [blog post](http://blog.npmjs.org/post/161832149430/npm-the-npm-github-issue-tracker-and-you).
