### ISSUE TITLE
Source tree polluted with npm executables on Windows with --prefix

### ISSUE THREAD

**Issue by joeyparrish** [npm/npm#17027]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [X] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Running `npm --prefix . install` on Windows causes the source tree to be polluted with node binaries.  These should be in node_modules/.bin/ instead.  This behaves correctly on Linux and Mac.

See also google/shaka-player#776

#### How can the CLI team reproduce the problem?

On Windows/Cygwin:

```sh
git clone https://github.com/google/shaka-player
cd shaka-player
npm --prefix . install
```

No debug log was generated, but I'd be happy to post one on gist if you can tell me how to create one.

### supporting information:

 - `npm -v` prints: 3.10.3 and 5.0.3 both reproduce the problem
 - `node -v` prints: v6.6.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows
 - Network issues: None
 - Container: Using Cygwin on a real Windows machine, no container or virtual machine

**Comment by legodude17** [comment]
Try running `npm --prefix . install -ddd > npm-debug.txt` and then use `npm-debug.txt`.

**Comment by joeyparrish** [comment]
I had to use `&> npm-debug.txt` to capture stderr as well, but I was able to capture the debug info.  File attached.  Thanks!

[npm-debug.txt](https://github.com/npm/npm/files/1062664/npm-debug.txt)
