### ISSUE TITLE
Missing repositories

### ISSUE THREAD

**Issue by erazo14** [npm/npm#17037]
I'm getting some problems installing ionic 1.3.16 because is missing some repos.

console errors:
npm ERR! fetch failed https://registry.npmjs.org/i/-/i-0.3.2.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404

npm ERR! fetch failed https://registry.npmjs.org/i/-/i-0.3.2.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404

npm ERR! fetch failed https://registry.npmjs.org/i/-/i-0.3.2.tgz
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "ionic@1.3.16"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6

npm ERR! fetch failed with status code 404

[npm-debug.log.txt](https://github.com/npm/npm/files/1056545/npm-debug.log.txt)

I'll be waiting for your response

**Comment by kenany** [comment]
This is fixed in newer versions of `ionic`. See https://github.com/npm/npm/issues/12673, https://github.com/npm/npm/issues/13826, and https://github.com/npm/npm/issues/14025.

**Comment by erazo14** [comment]
Perfect thanks!!

Sent from my iPhone

On Jun 6, 2017, at 6:15 PM, Kenan Yildirim <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #17037<https://github.com/npm/npm/issues/17037>.
