### ISSUE TITLE
Error: EIO: i/o error, read

### ISSUE THREAD

**Issue by spro80** [npm/npm#17030]
#### I'm opening this issue because:

  - [ ] npm is crashing.

####S.O
Ubuntu 14.04

####VERSION: npm and nodejs
[ddiaz@ddiazs:angular2Web]$ npm --version
3.10.10
[ddiaz@ddiazs:angular2Web]$ nodejs --version
v6.10.3

#### What's going wrong?
When I executed any commands in with npm, I am obtaing an error.

#### How can the CLI team reproduce the problem?
npm install
npm start

###THE ERROR IS:
[ddiaz@ddiazs:angular2Web]$ npm start
Error: EIO: i/o error, read
    at Error (native)
    at Object.fs.readSync (fs.js:732:19)
    at Object.readSync (/usr/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:118:28)
    at tryReadSync (fs.js:487:20)
    at Object.fs.readFileSync (fs.js:527:19)
    at Object.Module._extensions..js (module.js:578:20)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
npm ERR! Linux 3.13.0-119-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code EIO
npm ERR! errno -5
npm ERR! syscall read

**Comment by legodude17** [comment]
Please update to the latest version of npm.

**Comment by iarna** [comment]
We're closing this support issue as it has gone three days without activity.  The npm CLI team itself does not provide support via this issue tracker, but we are happy when users help each other here.  In our experience once a support issue goes dormant it's unlikely to get further activity.  If you're still having problems, you may be better served by joining [package.community](https://package.community/) and asking your question there.

For more information about our new issue aging policies and why we've instituted them please see our [blog post](http://blog.npmjs.org/post/161832149430/npm-the-npm-github-issue-tracker-and-you).

**Comment by firejq** [comment]
I hava met the same situation, how is it going about this issue?

**Comment by firejq** [comment]
Thanks to @legodude17, just now I updated npm and deleted the node_modules directory, and then run `npm install`, after which it solved this problem.

**Comment by aptarmy** [comment]
@firejq Thanks :) you save my life

**Comment by windbridges** [comment]
For somebody like me: nothing helped. I tried several versions of npm, removed node_modules, rebooted the Vagrant box, but still getting this error again and again. But when I was totally surrendered, I rebooted my computer. And voila! It works!
