### ISSUE TITLE
npm 5.0.1. appears to be handling packages whose version is a URL incorrectly

### ISSUE THREAD

**Issue by ghost** [npm/npm#17033]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [X] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

When running `npm install` on a project with an existing `package-lock.json` file in which a package had a URL as a version, the version generated in the packages package.json file is the URL instead of the version number.

#### How can the CLI team reproduce the problem?

1. Create a project with the following `package.json`:
```
{
  "name": "test",
  "version": "0.0.1",
  "description": "none",
  "author": null,
  "main": "main.js",
  "dependencies": {
    "react-native": "https://github.com/expo/react-native/archive/sdk-16.0.0.tar.gz"
  }
}
```
2. Run `npm install`.
3. Remove `node_modules`: `rm -rf node_modules`
4. Run `npm install`.
5. Check `./node_modules/react-native/package.json` ... `"version"` field.

### supporting information:

 - `npm -v` prints: 5.0.1
 - `node -v` prints: v7.5.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS

**Comment by kmathmann** [comment]
I think i have the same problem. I had an project without package-lock.json and installed an package over `npm i`, after that all entries of the package-lock.json had an url as version.

After deleting node_modules directory and package-lock.json i could run `npm i` without problems and an valid package-lock.json file becomes created.

**supporting information:**
`npm -v` prints: 5.0.0
`node -v` prints: v7.10.0
`npm config get registry` prints: http://repo.tobit.ag:8081/repository/npm
Windows, OS X/macOS, or Linux?: Windows 10

My package.json contains only npm packages with versions no github urls or things like that.
