### ISSUE TITLE
Error NPM install 

### ISSUE THREAD

**Issue by JeffryChristiandyBong** [npm/npm#17039]
#### I'm opening this issue because:

NPM install fails (please see below)

```
C:\Users\IBM_ADMIN\git\Rada>npm install
npm WARN deprecated azure-graphapi@0.1.0: Please use the graph-service package i
nstead.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code EREADFILE

npm ERR! Error extracting C:\Users\IBM_ADMIN\AppData\Roaming\npm-cache\fs\0.0.0\
package.tgz archive: ENOENT: no such file or directory, open 'C:\Users\IBM_ADMIN
\AppData\Roaming\npm-cache\fs\0.0.0\package.tgz'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\IBM_ADMIN\git\Rada\npm-debug.log
```

the npm-debug.log is attached in zip file
[npm-debug.zip](https://github.com/npm/npm/files/1056615/npm-debug.zip)

**Comment by legodude17** [comment]
Please update to the latest version of npm.

**Comment by iarna** [comment]
We're closing this support issue as it has gone three days without activity.  The npm CLI team itself does not provide support via this issue tracker, but we are happy when users help each other here.  In our experience once a support issue goes dormant it's unlikely to get further activity.  If you're still having problems, you may be better served by joining [package.community](https://package.community/) and asking your question there.

For more information about our new issue aging policies and why we've instituted them please see our [blog post](http://blog.npmjs.org/post/161832149430/npm-the-npm-github-issue-tracker-and-you).
