### ISSUE TITLE
Can't install anything

### ISSUE THREAD

**Issue by yas46** [npm/npm#17032]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [X] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Webpack and Babel install causing errors - won't install.
used "npm install --save-dev webpack" and "npm install webpack -g"

#### How can the CLI team reproduce the problem?
npm install --save-dev webpack
npm install webpack -g"
npm install --save-dev babel-cli babel-preset-env
npm install -g npm@lts

nothing works. 
This comes up:

npm ERR! write EPROTO 140735765156800:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:

### supporting information:

 - `npm -v` prints: v3.10.10
 - `node -v` prints: v6.9.4
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: OS X/macOS
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'install' ]
2 info using npm@3.10.10
3 info using node@v6.9.4
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly install normalizeTree
8 silly loadCurrentTree Finishing
9 silly loadIdealTree Starting
10 silly install loadIdealTree
11 silly cloneCurrentTree Starting
12 silly install cloneCurrentTreeToIdealTree
13 silly cloneCurrentTree Finishing
14 silly loadShrinkwrap Starting
15 silly install loadShrinkwrap
16 silly loadShrinkwrap Finishing
17 silly loadAllDepsIntoIdealTree Starting
18 silly install loadAllDepsIntoIdealTree
19 silly fetchNamedPackageData babel-polyfill
20 silly mapToRegistry name babel-polyfill
21 silly mapToRegistry using default registry
22 silly mapToRegistry registry https://registry.npmjs.org/
23 silly mapToRegistry data Result {
23 silly mapToRegistry   raw: 'babel-polyfill',
23 silly mapToRegistry   scope: null,
23 silly mapToRegistry   escapedName: 'babel-polyfill',
23 silly mapToRegistry   name: 'babel-polyfill',
23 silly mapToRegistry   rawSpec: '',
23 silly mapToRegistry   spec: 'latest',
23 silly mapToRegistry   type: 'tag' }
24 silly mapToRegistry uri https://registry.npmjs.org/babel-polyfill
25 silly fetchNamedPackageData bootstrap
26 silly mapToRegistry name bootstrap
27 silly mapToRegistry using default registry
28 silly mapToRegistry registry https://registry.npmjs.org/
29 silly mapToRegistry data Result {
29 silly mapToRegistry   raw: 'bootstrap',
29 silly mapToRegistry   scope: null,
29 silly mapToRegistry   escapedName: 'bootstrap',
29 silly mapToRegistry   name: 'bootstrap',
29 silly mapToRegistry   rawSpec: '',
29 silly mapToRegistry   spec: 'latest',
29 silly mapToRegistry   type: 'tag' }
30 silly mapToRegistry uri https://registry.npmjs.org/bootstrap
31 silly fetchNamedPackageData jquery
32 silly mapToRegistry name jquery
33 silly mapToRegistry using default registry
34 silly mapToRegistry registry https://registry.npmjs.org/
35 silly mapToRegistry data Result {
35 silly mapToRegistry   raw: 'jquery',
35 silly mapToRegistry   scope: null,
35 silly mapToRegistry   escapedName: 'jquery',
35 silly mapToRegistry   name: 'jquery',
35 silly mapToRegistry   rawSpec: '',
35 silly mapToRegistry   spec: 'latest',
35 silly mapToRegistry   type: 'tag' }
36 silly mapToRegistry uri https://registry.npmjs.org/jquery
37 silly fetchNamedPackageData react
38 silly mapToRegistry name react
39 silly mapToRegistry using default registry
40 silly mapToRegistry registry https://registry.npmjs.org/
41 silly mapToRegistry data Result {
41 silly mapToRegistry   raw: 'react',
41 silly mapToRegistry   scope: null,
41 silly mapToRegistry   escapedName: 'react',
41 silly mapToRegistry   name: 'react',
41 silly mapToRegistry   rawSpec: '',
41 silly mapToRegistry   spec: 'latest',
41 silly mapToRegistry   type: 'tag' }
42 silly mapToRegistry uri https://registry.npmjs.org/react
43 silly fetchNamedPackageData react-dom
44 silly mapToRegistry name react-dom
45 silly mapToRegistry using default registry
46 silly mapToRegistry registry https://registry.npmjs.org/
47 silly mapToRegistry data Result {
47 silly mapToRegistry   raw: 'react-dom',
47 silly mapToRegistry   scope: null,
47 silly mapToRegistry   escapedName: 'react-dom',
47 silly mapToRegistry   name: 'react-dom',
47 silly mapToRegistry   rawSpec: '',
47 silly mapToRegistry   spec: 'latest',
47 silly mapToRegistry   type: 'tag' }
48 silly mapToRegistry uri https://registry.npmjs.org/react-dom
49 silly fetchNamedPackageData react-redux
50 silly mapToRegistry name react-redux
51 silly mapToRegistry using default registry
52 silly mapToRegistry registry https://registry.npmjs.org/
53 silly mapToRegistry data Result {
53 silly mapToRegistry   raw: 'react-redux',
53 silly mapToRegistry   scope: null,
53 silly mapToRegistry   escapedName: 'react-redux',
53 silly mapToRegistry   name: 'react-redux',
53 silly mapToRegistry   rawSpec: '',
53 silly mapToRegistry   spec: 'latest',
53 silly mapToRegistry   type: 'tag' }
54 silly mapToRegistry uri https://registry.npmjs.org/react-redux
55 silly fetchNamedPackageData react-router
56 silly mapToRegistry name react-router
57 silly mapToRegistry using default registry
58 silly mapToRegistry registry https://registry.npmjs.org/
59 silly mapToRegistry data Result {
59 silly mapToRegistry   raw: 'react-router',
59 silly mapToRegistry   scope: null,
59 silly mapToRegistry   escapedName: 'react-router',
59 silly mapToRegistry   name: 'react-router',
59 silly mapToRegistry   rawSpec: '',
59 silly mapToRegistry   spec: 'latest',
59 silly mapToRegistry   type: 'tag' }
60 silly mapToRegistry uri https://registry.npmjs.org/react-router
61 silly fetchNamedPackageData react-router-redux
62 silly mapToRegistry name react-router-redux
63 silly mapToRegistry using default registry
64 silly mapToRegistry registry https://registry.npmjs.org/
65 silly mapToRegistry data Result {
65 silly mapToRegistry   raw: 'react-router-redux',
65 silly mapToRegistry   scope: null,
65 silly mapToRegistry   escapedName: 'react-router-redux',
65 silly mapToRegistry   name: 'react-router-redux',
65 silly mapToRegistry   rawSpec: '',
65 silly mapToRegistry   spec: 'latest',
65 silly mapToRegistry   type: 'tag' }
66 silly mapToRegistry uri https://registry.npmjs.org/react-router-redux
67 silly fetchNamedPackageData redux
68 silly mapToRegistry name redux
69 silly mapToRegistry using default registry
70 silly mapToRegistry registry https://registry.npmjs.org/
71 silly mapToRegistry data Result {
71 silly mapToRegistry   raw: 'redux',
71 silly mapToRegistry   scope: null,
71 silly mapToRegistry   escapedName: 'redux',
71 silly mapToRegistry   name: 'redux',
71 silly mapToRegistry   rawSpec: '',
71 silly mapToRegistry   spec: 'latest',
71 silly mapToRegistry   type: 'tag' }
72 silly mapToRegistry uri https://registry.npmjs.org/redux
73 silly fetchNamedPackageData redux-thunk
74 silly mapToRegistry name redux-thunk
75 silly mapToRegistry using default registry
76 silly mapToRegistry registry https://registry.npmjs.org/
77 silly mapToRegistry data Result {
77 silly mapToRegistry   raw: 'redux-thunk',
77 silly mapToRegistry   scope: null,
77 silly mapToRegistry   escapedName: 'redux-thunk',
77 silly mapToRegistry   name: 'redux-thunk',
77 silly mapToRegistry   rawSpec: '',
77 silly mapToRegistry   spec: 'latest',
77 silly mapToRegistry   type: 'tag' }
78 silly mapToRegistry uri https://registry.npmjs.org/redux-thunk
79 silly fetchNamedPackageData toastr
80 silly mapToRegistry name toastr
81 silly mapToRegistry using default registry
82 silly mapToRegistry registry https://registry.npmjs.org/
83 silly mapToRegistry data Result {
83 silly mapToRegistry   raw: 'toastr',
83 silly mapToRegistry   scope: null,
83 silly mapToRegistry   escapedName: 'toastr',
83 silly mapToRegistry   name: 'toastr',
83 silly mapToRegistry   rawSpec: '',
83 silly mapToRegistry   spec: 'latest',
83 silly mapToRegistry   type: 'tag' }
84 silly mapToRegistry uri https://registry.npmjs.org/toastr
85 verbose request uri https://registry.npmjs.org/babel-polyfill
86 verbose request no auth needed
87 info attempt registry request try #1 at 10:54:08 AM
88 verbose request id e68a90ead9e717f5
89 http request GET https://registry.npmjs.org/babel-polyfill
90 verbose request uri https://registry.npmjs.org/bootstrap
91 verbose request no auth needed
92 info attempt registry request try #1 at 10:54:08 AM
93 http request GET https://registry.npmjs.org/bootstrap
94 verbose request uri https://registry.npmjs.org/jquery
95 verbose request no auth needed
96 info attempt registry request try #1 at 10:54:08 AM
97 http request GET https://registry.npmjs.org/jquery
98 verbose request uri https://registry.npmjs.org/react
99 verbose request no auth needed
100 info attempt registry request try #1 at 10:54:08 AM
101 http request GET https://registry.npmjs.org/react
102 verbose request uri https://registry.npmjs.org/react-dom
103 verbose request no auth needed
104 info attempt registry request try #1 at 10:54:08 AM
105 http request GET https://registry.npmjs.org/react-dom
106 verbose request uri https://registry.npmjs.org/react-redux
107 verbose request no auth needed
108 info attempt registry request try #1 at 10:54:08 AM
109 http request GET https://registry.npmjs.org/react-redux
110 verbose request uri https://registry.npmjs.org/react-router
111 verbose request no auth needed
112 info attempt registry request try #1 at 10:54:08 AM
113 http request GET https://registry.npmjs.org/react-router
114 verbose request uri https://registry.npmjs.org/react-router-redux
115 verbose request no auth needed
116 info attempt registry request try #1 at 10:54:08 AM
117 http request GET https://registry.npmjs.org/react-router-redux
118 verbose request uri https://registry.npmjs.org/redux
119 verbose request no auth needed
120 info attempt registry request try #1 at 10:54:08 AM
121 http request GET https://registry.npmjs.org/redux
122 verbose request uri https://registry.npmjs.org/redux-thunk
123 verbose request no auth needed
124 info attempt registry request try #1 at 10:54:08 AM
125 http request GET https://registry.npmjs.org/redux-thunk
126 verbose request uri https://registry.npmjs.org/toastr
127 verbose request no auth needed
128 info attempt registry request try #1 at 10:54:08 AM
129 http request GET https://registry.npmjs.org/toastr
130 info retry will retry, error on last attempt: Error: write EPROTO 140735765156800:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:
131 info retry will retry, error on last attempt: Error: write EPROTO 140735765156800:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:
132 info retry will retry, error on last attempt: Error: write EPROTO 140735765156800:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:
133 info retry will retry, error on last attempt: Error: write EPROTO 140735765156800:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:
134 info retry will retry, error on last attempt: Error: write EPROTO 140735765156800:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:
135 info retry will retry, error on last attempt: Error: write EPROTO 140735765156800:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:
136 info retry will retry, error on last attempt: Error: write EPROTO 140735765156800:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:
137 info retry will retry, error on last attempt: Error: write EPROTO 140735765156800:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:
138 info retry will retry, error on last attempt: Error: write EPROTO 140735765156800:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:
139 info retry will retry, error on last attempt: Error: write EPROTO 140735765156800:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:
140 info retry will retry, error on last attempt: Error: write EPROTO 140735765156800:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:
141 info attempt registry request try #2 at 10:54:18 AM
142 http request GET https://registry.npmjs.org/redux
143 info attempt registry request try #2 at 10:54:18 AM
144 http request GET https://registry.npmjs.org/toastr
145 info attempt registry request try #2 at 10:54:18 AM
146 http request GET https://registry.npmjs.org/redux-thunk
147 info attempt registry request try #2 at 10:54:18 AM
148 http request GET https://registry.npmjs.org/react-router-redux
149 info attempt registry request try #2 at 10:54:18 AM
150 http request GET https://registry.npmjs.org/react-router
151 info attempt registry request try #2 at 10:54:18 AM
152 http request GET https://registry.npmjs.org/react-dom
153 info attempt registry request try #2 at 10:54:18 AM
154 http request GET https://registry.npmjs.org/react-redux
155 info attempt registry request try #2 at 10:54:18 AM
156 http request GET https://registry.npmjs.org/bootstrap
157 info attempt registry request try #2 at 10:54:18 AM
158 http request GET https://registry.npmjs.org/react
159 info attempt registry request try #2 at 10:54:18 AM
160 http request GET https://registry.npmjs.org/babel-polyfill
161 info attempt registry request try #2 at 10:54:18 AM
162 http request GET https://registry.npmjs.org/jquery
163 info retry will retry, error on last attempt: Error: write EPROTO 140735765156800:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:
164 info retry will retry, error on last attempt: Error: write EPROTO 140735765156800:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:
165 info retry will retry, error on last attempt: Error: write EPROTO 140735765156800:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:
166 info retry will retry, error on last attempt: Error: write EPROTO 140735765156800:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:
167 info retry will retry, error on last attempt: Error: write EPROTO 140735765156800:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:
168 info retry will retry, error on last attempt: Error: write EPROTO 140735765156800:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:
169 info retry will retry, error on last attempt: Error: write EPROTO 140735765156800:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:
170 info retry will retry, error on last attempt: Error: write EPROTO 140735765156800:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:
171 info retry will retry, error on last attempt: Error: write EPROTO 140735765156800:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:
172 info retry will retry, error on last attempt: Error: write EPROTO 140735765156800:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:
173 info retry will retry, error on last attempt: Error: write EPROTO 140735765156800:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:
174 info attempt registry request try #3 at 10:55:18 AM
175 http request GET https://registry.npmjs.org/redux
176 info attempt registry request try #3 at 10:55:18 AM
177 http request GET https://registry.npmjs.org/toastr
178 info attempt registry request try #3 at 10:55:18 AM
179 http request GET https://registry.npmjs.org/redux-thunk
180 info attempt registry request try #3 at 10:55:18 AM
181 http request GET https://registry.npmjs.org/react-dom
182 info attempt registry request try #3 at 10:55:18 AM
183 http request GET https://registry.npmjs.org/react-router
184 info attempt registry request try #3 at 10:55:18 AM
185 http request GET https://registry.npmjs.org/react-router-redux
186 info attempt registry request try #3 at 10:55:18 AM
187 http request GET https://registry.npmjs.org/react-redux
188 info attempt registry request try #3 at 10:55:18 AM
189 http request GET https://registry.npmjs.org/bootstrap
190 info attempt registry request try #3 at 10:55:18 AM
191 http request GET https://registry.npmjs.org/react
192 info attempt registry request try #3 at 10:55:18 AM
193 http request GET https://registry.npmjs.org/babel-polyfill
194 info attempt registry request try #3 at 10:55:18 AM
195 http request GET https://registry.npmjs.org/jquery
196 silly fetchPackageMetaData Error: write EPROTO 140735765156800:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:
196 silly fetchPackageMetaData
196 silly fetchPackageMetaData     at exports._errnoException (util.js:1022:11)
196 silly fetchPackageMetaData     at WriteWrap.afterWrite (net.js:801:14)
196 silly fetchPackageMetaData  error for react-dom@15.0.2 { Error: write EPROTO 140735765156800:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:
196 silly fetchPackageMetaData
196 silly fetchPackageMetaData     at exports._errnoException (util.js:1022:11)
196 silly fetchPackageMetaData     at WriteWrap.afterWrite (net.js:801:14) code: 'EPROTO', errno: 'EPROTO', syscall: 'write' }
197 silly fetchPackageMetaData Error: write EPROTO 140735765156800:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:
197 silly fetchPackageMetaData
197 silly fetchPackageMetaData     at exports._errnoException (util.js:1022:11)
197 silly fetchPackageMetaData     at WriteWrap.afterWrite (net.js:801:14)
197 silly fetchPackageMetaData  error for redux-thunk@2.0.1 { Error: write EPROTO 140735765156800:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:
197 silly fetchPackageMetaData
197 silly fetchPackageMetaData     at exports._errnoException (util.js:1022:11)
197 silly fetchPackageMetaData     at WriteWrap.afterWrite (net.js:801:14) code: 'EPROTO', errno: 'EPROTO', syscall: 'write' }
198 silly fetchPackageMetaData Error: write EPROTO 140735765156800:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:
198 silly fetchPackageMetaData
198 silly fetchPackageMetaData     at exports._errnoException (util.js:1022:11)
198 silly fetchPackageMetaData     at WriteWrap.afterWrite (net.js:801:14)
198 silly fetchPackageMetaData  error for toastr@2.1.2 { Error: write EPROTO 140735765156800:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:
198 silly fetchPackageMetaData
198 silly fetchPackageMetaData     at exports._errnoException (util.js:1022:11)
198 silly fetchPackageMetaData     at WriteWrap.afterWrite (net.js:801:14) code: 'EPROTO', errno: 'EPROTO', syscall: 'write' }
199 silly fetchPackageMetaData Error: write EPROTO 140735765156800:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:
199 silly fetchPackageMetaData
199 silly fetchPackageMetaData     at exports._errnoException (util.js:1022:11)
199 silly fetchPackageMetaData     at WriteWrap.afterWrite (net.js:801:14)
199 silly fetchPackageMetaData  error for redux@3.5.2 { Error: write EPROTO 140735765156800:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:
199 silly fetchPackageMetaData
199 silly fetchPackageMetaData     at exports._errnoException (util.js:1022:11)
199 silly fetchPackageMetaData     at WriteWrap.afterWrite (net.js:801:14) code: 'EPROTO', errno: 'EPROTO', syscall: 'write' }
200 silly fetchPackageMetaData Error: write EPROTO 140735765156800:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:
200 silly fetchPackageMetaData
200 silly fetchPackageMetaData     at exports._errnoException (util.js:1022:11)
200 silly fetchPackageMetaData     at WriteWrap.afterWrite (net.js:801:14)
200 silly fetchPackageMetaData  error for bootstrap@3.3.6 { Error: write EPROTO 140735765156800:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:
200 silly fetchPackageMetaData
200 silly fetchPackageMetaData     at exports._errnoException (util.js:1022:11)
200 silly fetchPackageMetaData     at WriteWrap.afterWrite (net.js:801:14) code: 'EPROTO', errno: 'EPROTO', syscall: 'write' }
201 silly fetchPackageMetaData Error: write EPROTO 140735765156800:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:
201 silly fetchPackageMetaData
201 silly fetchPackageMetaData     at exports._errnoException (util.js:1022:11)
201 silly fetchPackageMetaData     at WriteWrap.afterWrite (net.js:801:14)
201 silly fetchPackageMetaData  error for react-redux@4.4.5 { Error: write EPROTO 140735765156800:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:
201 silly fetchPackageMetaData
201 silly fetchPackageMetaData     at exports._errnoException (util.js:1022:11)
201 silly fetchPackageMetaData     at WriteWrap.afterWrite (net.js:801:14) code: 'EPROTO', errno: 'EPROTO', syscall: 'write' }
202 silly fetchPackageMetaData Error: write EPROTO 140735765156800:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:
202 silly fetchPackageMetaData
202 silly fetchPackageMetaData     at exports._errnoException (util.js:1022:11)
202 silly fetchPackageMetaData     at WriteWrap.afterWrite (net.js:801:14)
202 silly fetchPackageMetaData  error for react-router-redux@4.0.4 { Error: write EPROTO 140735765156800:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:
202 silly fetchPackageMetaData
202 silly fetchPackageMetaData     at exports._errnoException (util.js:1022:11)
202 silly fetchPackageMetaData     at WriteWrap.afterWrite (net.js:801:14) code: 'EPROTO', errno: 'EPROTO', syscall: 'write' }
203 silly fetchPackageMetaData Error: write EPROTO 140735765156800:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:
203 silly fetchPackageMetaData
203 silly fetchPackageMetaData     at exports._errnoException (util.js:1022:11)
203 silly fetchPackageMetaData     at WriteWrap.afterWrite (net.js:801:14)
203 silly fetchPackageMetaData  error for react-router@2.4.0 { Error: write EPROTO 140735765156800:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:
203 silly fetchPackageMetaData
203 silly fetchPackageMetaData     at exports._errnoException (util.js:1022:11)
203 silly fetchPackageMetaData     at WriteWrap.afterWrite (net.js:801:14) code: 'EPROTO', errno: 'EPROTO', syscall: 'write' }
204 silly fetchPackageMetaData Error: write EPROTO 140735765156800:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:
204 silly fetchPackageMetaData
204 silly fetchPackageMetaData     at exports._errnoException (util.js:1022:11)
204 silly fetchPackageMetaData     at WriteWrap.afterWrite (net.js:801:14)
204 silly fetchPackageMetaData  error for react@15.0.2 { Error: write EPROTO 140735765156800:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:
204 silly fetchPackageMetaData
204 silly fetchPackageMetaData     at exports._errnoException (util.js:1022:11)
204 silly fetchPackageMetaData     at WriteWrap.afterWrite (net.js:801:14) code: 'EPROTO', errno: 'EPROTO', syscall: 'write' }
205 silly fetchPackageMetaData Error: write EPROTO 140735765156800:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:
205 silly fetchPackageMetaData
205 silly fetchPackageMetaData     at exports._errnoException (util.js:1022:11)
205 silly fetchPackageMetaData     at WriteWrap.afterWrite (net.js:801:14)
205 silly fetchPackageMetaData  error for jquery@2.2.3 { Error: write EPROTO 140735765156800:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:
205 silly fetchPackageMetaData
205 silly fetchPackageMetaData     at exports._errnoException (util.js:1022:11)
205 silly fetchPackageMetaData     at WriteWrap.afterWrite (net.js:801:14) code: 'EPROTO', errno: 'EPROTO', syscall: 'write' }
206 silly fetchPackageMetaData Error: write EPROTO 140735765156800:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:
206 silly fetchPackageMetaData
206 silly fetchPackageMetaData     at exports._errnoException (util.js:1022:11)
206 silly fetchPackageMetaData     at WriteWrap.afterWrite (net.js:801:14)
206 silly fetchPackageMetaData  error for babel-polyfill@6.8.0 { Error: write EPROTO 140735765156800:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:
206 silly fetchPackageMetaData
206 silly fetchPackageMetaData     at exports._errnoException (util.js:1022:11)
206 silly fetchPackageMetaData     at WriteWrap.afterWrite (net.js:801:14) code: 'EPROTO', errno: 'EPROTO', syscall: 'write' }
207 silly rollbackFailedOptional Starting
208 silly rollbackFailedOptional Finishing
209 silly runTopLevelLifecycles Finishing
210 silly install printInstalled
211 verbose stack Error: write EPROTO 140735765156800:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:
211 verbose stack
211 verbose stack     at exports._errnoException (util.js:1022:11)
211 verbose stack     at WriteWrap.afterWrite (net.js:801:14)
212 verbose cwd /Users/u63p62/WebstormProjects/react-lesson
213 error Darwin 16.4.0
214 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
215 error node v6.9.4
216 error npm  v3.10.10
217 error code EPROTO
218 error errno EPROTO
219 error syscall write
220 error write EPROTO 140735765156800:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:
221 error If you need help, you may report this error at:
221 error     <https://github.com/npm/npm/issues>
222 verbose exit [ 1, true ]

**Comment by iarna** [comment]
We're closing this support issue as it has gone three days without activity.  The npm CLI team itself does not provide support via this issue tracker, but we are happy when users help each other here.  In our experience once a support issue goes dormant it's unlikely to get further activity.  If you're still having problems, you may be better served by joining [package.community](https://package.community/) and asking your question there.

For more information about our new issue aging policies and why we've instituted them please see our [blog post](http://blog.npmjs.org/post/161832149430/npm-the-npm-github-issue-tracker-and-you).
