### ISSUE TITLE
Confusing error during npm publish

### ISSUE THREAD

**Issue by gfeller** [npm/npm#17046]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [X] Other (_see below for feature requests_):

#### What's going wrong?
Confusing error during npm publish.

With 7.8.0 version the error looked like this:
36 error Windows_NT 10.0.14393
37 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "publish"
38 error node v7.8.0
39 error npm  v4.2.0
40 error code ENEEDAUTH
41 error need auth auth required for publishing
42 error need auth You need to authorize this machine using `npm adduser`
43 verbose exit [ 1, true ]

With 5.0.3:
31 verbose node v8.0.0
32 verbose npm  v5.0.3
33 error path C:\...\fromDir-84ffe8af\package.tgz
34 error code EPERM
35 error errno -4048
36 error syscall unlink
37 error Error: EPERM: operation not permitted, unlink 'C:\...\fromDir-84ffe8af\package.tgz'
37 error  { Error: EPERM: operation not permitted, unlink 'C:\...\fromDir-84ffe8af\package.tgz' }
38 error Please try running this command again as root/Administrator.

After adding a user with "npm adduser" the error is gone and npm publish worked. 

#### How can the CLI team reproduce the problem?
npm publish without a registered user.

**Comment by legodude17** [comment]
`With 7.8.0 version the error looked like this:` don't you mean 4.2.0?

**Comment by mikecousins** [comment]
This one definitely still exists.

**Comment by sbaleno** [comment]
Seeing this as well.

**Comment by theCmaker** [comment]
I'm having the same issue

**Comment by smasala** [comment]
`npm adduser` worked for me :+1:

**Comment by xmakina** [comment]
this stumped me before I found this question. Would be much better if the error could advise that you need to login or adduser
