### ISSUE TITLE
error with npm itself 

### ISSUE THREAD

**Issue by Hirayama1** [npm/npm#17044]
-[ ] When i am using " npm with hubot. There are errors for showing  
 npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2017-06-07T06_54_10_591Z-debug.log

I don't know what to do

**Comment by kenany** [comment]
@Hirayama1 Could you upload the debug log to <https://gist.github.com/> and link it here? Thanks!

**Comment by mare1012** [comment]
Hallo @KenanY, i was updating npm to 5.0.3. But now I can't install or uninstall with npm. 

here is the log-file:
https://gist.github.com/mare1012/6b498304de30481b3fa273f5609a7819

**Comment by kenany** [comment]
@mare1012 See: https://github.com/npm/npm/issues/16738.

**Comment by iarna** [comment]
We're closing this support issue as it has gone three days without activity.  The npm CLI team itself does not provide support via this issue tracker, but we are happy when users help each other here.  In our experience once a support issue goes dormant it's unlikely to get further activity.  If you're still having problems, you may be better served by joining [package.community](https://package.community/) and asking your question there.

For more information about our new issue aging policies and why we've instituted them please see our [blog post](http://blog.npmjs.org/post/161832149430/npm-the-npm-github-issue-tracker-and-you).
