### ISSUE TITLE
package-lock.json ordering is locale dependent

### ISSUE THREAD

**Issue by unilynx** [npm/npm#17048]
#### I'm opening this issue because:
  - [x] npm is doing something I don't understand.

#### What's going wrong?

The packages in package-lock.json are reordered depending on the locale of the user using npm. This is causing unnecessary updates to the package-lock.json file, which causes needless updates in versioning systems.

#### How can the CLI team reproduce the problem?
(this might depend on the default locale settings on OSX, 
```
export LANG=en_US.UTF-8
mkdir /tmp/bla
cd /tmp/bla
npm init
npm install string_decoder
npm install string-w-dth
LANG="en_US.UTF-8" LC_ALL="en_US.UTF-8" npm install
cat package-lock.json # string_decoder appears before string-width
LANG="" LC_ALL="" npm install
cat package-lock.json # string_decoder now appears after string-width
```

### supporting information:

 - `npm -v` prints:
5.0.3
 - `node -v` prints:
v8.0.0
 - `npm config get registry` prints:
https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?:
macOS Sierra

**Comment by paulmelero** [comment]
Same here. Cannot get the same package-lock modules order in my machine as my co-workers. But I do not have any `LANG` env variable.

* node -v
v6.9.4

* npm -v
5.0.4

* npm config get registry prints:
https://registry.npmjs.org/

* Win10 64

**Comment by LotharSee** [comment]
Experienced exactly the same troubles. At work, different versions of OSX come with different default locales, so our lock file isn't stable between machines.

To reproduce the locale-dependent lock file, create a directory with a `package.json`.
Done with npm 5.3.0.

```json
{
  "name": "example",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "author": "",
  "license": "ISC",
  "dependencies": {
    "fsevents": "1.1.2"
  }
}
```

Then compare the `package-lock.json` with:

- `LANG="" LC_ALL="" npm i`
- `LANG="en_US.UTF-8" LC_ALL="en_US.UTF-8" npm i`

They put `string_decoder` and `string-width` in a different order in `["dependencies"]["fsevents"]["dependencies"]`.



Also opened a PR to use a locale-agnostic sort instead. https://github.com/npm/npm/pull/17844
