### ISSUE TITLE
ionic installation

### ISSUE THREAD

**Issue by JamSameer** [npm/npm#17042]
-[ ] When i am using " npm install ionic@2.2.1 -g "  to install ionic these errors are showing.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ionic@2.2.1"
npm ERR! node v6.9.3
npm ERR! npm  v3.10.10

npm ERR! shasum check failed for C:\Users\SAMEER~1\AppData\Local\Temp\npm-3824-b
765196b\registry.npmjs.org\ionic\-\ionic-2.2.1.tgz
npm ERR! Expected: 2b9d90b3ae109138084473282c18ea162a5f8248
npm ERR! Actual:   8c005c78baaa6c1d5a9235f8e212efe38a7a2626
npm ERR! From:     https://registry.npmjs.org/ionic/-/ionic-2.2.1.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by kenany** [comment]
@JamSameer Could you try a newer version of `npm`? Thanks!

**Comment by JamSameer** [comment]
@KenanY I installed new version but  it is not supporting to my code because my code is _Ionic v1 code_ so i need to install old version of ionic.

**Comment by kenany** [comment]
@JamSameer I meant could you install, say, `npm@4`?

**Comment by JamSameer** [comment]
@KenanY No npm@3.3.1

**Comment by JamSameer** [comment]
@KenanY I just typed the command "install npm" its directly installed 3.3.1 version.

**Comment by kenany** [comment]
@JamSameer Maybe <https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows> could help?

**Comment by iarna** [comment]
We're closing this support issue as it has gone three days without activity.  The npm CLI team itself does not provide support via this issue tracker, but we are happy when users help each other here.  In our experience once a support issue goes dormant it's unlikely to get further activity.  If you're still having problems, you may be better served by joining [package.community](https://package.community/) and asking your question there.

For more information about our new issue aging policies and why we've instituted them please see our [blog post](http://blog.npmjs.org/post/161832149430/npm-the-npm-github-issue-tracker-and-you).
