### ISSUE TITLE
Big bug in npm 5.0.3

### ISSUE THREAD

**Issue by WeIio** [npm/npm#17041]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [*] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Well, I'm developing react native project. When I saw a upgrade recommend from npm, I did. but then weird things happened...   When i installed package with npm, installation did well, but some other packages was removed. Even though it was rn package. At beginning, I'm not sure it's npm's issue, because I  had changed rn version to newest, until rolled rn back.

Could anyone or dev teams figure out it ? Thanks in advance

**Comment by seeden** [comment]
I have same experience. For example NPM 5 will remove dependencies in my linked package when I run npm install

**Comment by Creemli** [comment]
dumplicated： https://github.com/npm/npm/issues/17004
