### ISSUE TITLE
Unhandled rejection Error: Invalid tag name '-': Tags may not have any characters that encodeURIComponent encodes

### ISSUE THREAD

**Issue by Hackwolf** [npm/npm#17049]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [YES] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I installed Node.js 8.0.0 on my PC.

My actions are following:

- `npm init`
This command does not cause problems.
- `npm install @angular/common @angular/core @angular/compiler — save`
I had exception: "Unhandled rejection Error: Invalid tag name '-': Tags may not have any characters that encodeURIComponent encodes".

#### How can the CLI team reproduce the problem?

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '@angular/common',
1 verbose cli   '@angular/core',
1 verbose cli   '@angular/compiler',
1 verbose cli   '—',
1 verbose cli   'save' ]
2 info using npm@5.0.0
3 info using node@v8.0.0
4 silly install loadCurrentTree
5 silly install readLocalPackageData
6 silly fetchPackageMetaData error for @angular/common@latest install [REDACTED] [REDACTED] [REDACTED] — save is not a legal HTTP header value
7 silly fetchPackageMetaData error for @angular/core@latest install [REDACTED] [REDACTED] [REDACTED] — save is not a legal HTTP header value
8 silly fetchPackageMetaData error for @angular/compiler@latest install [REDACTED] [REDACTED] [REDACTED] — save is not a legal HTTP header value
9 error cb() never called!
10 error This is an error with npm itself. Please report this error at:
11 error <https://github.com/npm/npm/issues>

### supporting information:

 - `npm -v` prints: 5.0.0
 - `node -v` prints: v8.0.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [YES] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
What command did you run? Try using `npm@5.0.3`.

**Comment by Hackwolf** [comment]
I executed `npm install @angular/common @angular/core @angular/compiler — save`.

**Comment by legodude17** [comment]
Then why this:
```
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli 'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli 'install',
1 verbose cli '',
1 verbose cli '',
1 verbose cli '',
1 verbose cli '—',
1 verbose cli 'save' ]
```
To that it looks like you ran `npm install      --` which doesn't make sense.
Try updating to npm@5.0.3.

**Comment by LAITONEN** [comment]
I have the same issue. Whatever action I perform with npm (install, uninstall, upgrade, update) it crushed and tells me: 
Invalid tag name "somewhere": Tags may not have any characters that encodeURIComponent encodes.
The whole error message:
npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "update" "-g"
npm ERR! node v6.10.2
npm ERR! npm  v4.2.0
npm ERR! code EINVALIDTAGNAME

npm ERR! Invalid tag name "uid-number@0.0.6": Tags may not have any characters that encodeURIComponent encodes.
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "update" "-g"
npm ERR! node v6.10.2
npm ERR! npm  v4.2.0
npm ERR! code EINVALIDTAGNAME

npm ERR! Invalid tag name "uid-number@0.0.6": Tags may not have any characters that encodeURIComponent encodes.
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/UserName/.npm/_logs/2017-06-15T16_53_50_856Z-debug.log

**Comment by LAITONEN** [comment]
Solved mine above mentioned issue by updating node (with brew install node).

**Comment by iarna** [comment]
@Hackwolf `npm install @angular/common @angular/core @angular/compiler — save` is not a valid command. I think you wanted:
`npm install @angular/common @angular/core @angular/compiler --save`

Note the difference, that's two hyphens, not an emdash, and there's no space between them and the save option.

It looks like you copy and pasted from documentation that mangled the double hyphen.
