### ISSUE TITLE
Gulp browserSync.reload

### ISSUE THREAD

**Issue by ccrayton** [npm/npm#17050]
So my question is, is there a way that when I run gulp watch through my terminal my browser doesn't load on a new page but instead reloads on the present page? 

![screen shot 2017-06-07 at 2 30 06 am](https://user-images.githubusercontent.com/19902713/26871936-b2abe48c-4b29-11e7-937d-ddce1091aef5.png)

**Comment by kenany** [comment]
Closing since this issue tracker is for `npm`-specific stuff only. Might wanna ask the `browser-sync` authors instead?
