### ISSUE TITLE
error 'cb() never called!' after running npm update (version 5.0.3)

### ISSUE THREAD

**Issue by davesag** [npm/npm#17055]
#### I'm opening this issue because:

  - [X ] npm is crashing.

#### What's going wrong?

I am importing a module from my local drive

```
  "dependencies": {
    "@myproject/models": "file:../models/",
    ... etc
```

and when I run `npm install` nothing changes but when I run `npm update` I get this error

```
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

#### How can the CLI team reproduce the problem?

see [2017-06-07T13_33_24_564Z-debug.log](https://gist.github.com/davesag/280de12a1afe013c0778f91f1529bb47) (redacted)

### supporting information:

 - `npm -v` prints: 5.0.3
 - `node -v` prints: v8.0.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS Sierra 10.12.5
 - Network issues:
   - Geographic location where npm was run: Delhi, India

**Comment by davesag** [comment]
Deleting `node_modules` and deleting `package-lock.json` and then running `npm install` works fine.

However running `npm run lint` after that reports

```
/Users/davesag/src/myproject/dothething/src/index.js
  1:35  error  Unable to resolve path to module '@myproject/models'  import/no-unresolved
  1:35  error  Missing file extension for "@myproject/models"        import/extensions
```

so clearly the import didn't actually happen.

However in `node_modules` there is a `@myproject` folder with an alias called `models` that links to `../models` so that works.

**Comment by ghost** [comment]
This hapened to me for the global modules. How do I fix it?

**Comment by lgriffin** [comment]
This was happening for me after installing the 5.0 release. I couldn't run npm install locally or globally and that included on fresh repos with no lockfile or prior modules. I was even getting the cb() error when I tried to upgrade to npm latest (5.0.3). I upgraded Node on a whim and it looks to have solved it. I just upgraded to 6.11, that might work for you.

**Comment by davesag** [comment]
Clearly the `npm` team has little interest in such bug reports.  Guess it's time to move to `yarn`

**Comment by ghost** [comment]
Reinstall node. That worked for me.

**Comment by roy-gbiv** [comment]
Also ran into this problem after going from 5.7.1 -> 6.0.0. Then I did yarn link and it worked immediately. @davesag isn't off on this...
