### ISSUE TITLE
npm istallation error during try to install the npm package.....How do I resolve?

### ISSUE THREAD

**Issue by sabarinathen** [npm/npm#17053]
npm ERR! not a package E:\sqdb\cordova
npm ERR! addLocal Could not install E:\sqdb\cordova
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0

npm ERR! Cannot read property 'path' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2017-06-07T12_09_11_576Z-debug.log

**Comment by kenany** [comment]
@sabarinathen Could you upload the full debug log to <https://gist.github.com/> and post a link to it here? Thanks!

**Comment by iarna** [comment]
We're closing this support issue as it has gone three days without activity.  The npm CLI team itself does not provide support via this issue tracker, but we are happy when users help each other here.  In our experience once a support issue goes dormant it's unlikely to get further activity.  If you're still having problems, you may be better served by joining [package.community](https://package.community/) and asking your question there.

For more information about our new issue aging policies and why we've instituted them please see our [blog post](http://blog.npmjs.org/post/161832149430/npm-the-npm-github-issue-tracker-and-you).
