### ISSUE TITLE
npm5 removes manually created symlinks from node_modules

### ISSUE THREAD

**Issue by danielgindi** [npm/npm#17057]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

When `npm install`ing a specific package, like `npm install bufferutil`,
npm is deleting all manually created symlinks from `node_modules`.

#### How can the CLI team reproduce the problem?

1. Create a submodule, possibly using git, in a subfolder. Then symlink to node_modules/something.
2. Now run `npm install bufferutil`

### supporting information:

 - `npm -v` prints: 5.0.2
 - `node -v` prints: v8.0.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows

**Comment by danielgindi** [comment]
And still 1,824 open issues.

**Comment by amirmohsen** [comment]
I've noticed this issue as well as I just upgraded from NPM 3 to 5. It's extremely irritating for a developer to have to run "npm link" every time after "npm install", particularly on bigger projects with multiple symlinked packages.

As for the issue closure, that's a stupid reason (I know it's a bot, but somebody created it). NPM is not just an open-source community tool anymore. It is a commercial company with paid users (me being one of them). You can't just close tickets and say we're not gonna look at it.

Hire more people or go get some investment if you don't have enough resources so you can answer your issues. NPM really needs better leadership. I have noticed on multiple occasions the condescending attitude and the utter disregard NPM maintainers have for their users. Sorry for ranting, but this attitude is not acceptable. My reaction would have been significantly different if NPM wasn't a commercial company but it is.

**Comment by ghost** [comment]
@amirmohsen I just switched to Yarn recently because of that.

**Comment by amirmohsen** [comment]
@Deevent I ended up following your advice (and many others) and installed Yarn. I can confirm that it's much better than NPM. It also doesn't have this specific irritating issue with deleting linked modules.

**Comment by wclr** [comment]
@amirmohsen absolutely. NPM maintainers are just ~~dumb~~ deaf to multiple real issues.

at least `npm install npm@4.6.1 -g` helps a little

**Comment by xdevelnet** [comment]
>We're closing this issue as it has gone seven days without activity and without being labeled. If we haven't even labeled in issue in seven days then we're unlikely to ever read it.

Absolutely brilliant feedback. Can I copy&use it for my own needs?

**Comment by wclr** [comment]
@xdevelnet I think you should receive written permission from NPM first. But you can use just more brief and specific version:

> Don't bother posting an issue. We're unlikely to ever read it.
