### ISSUE TITLE
NODE_ENV=production does not install devDependencies of a dep with `prepare`

### ISSUE THREAD

**Issue by intellix** [npm/npm#17059]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Adding a `prepare` script in npm5 states that it will install devDependencies of that package and run that `prepare` script. If you have NODE_ENV set to production then it does not actually install `devDependencies` and building of that package will fail. Probably spent about 8hrs trying to figure out why my dist folder didn't exist on Heroku for a package I depend on :)

#### How can the CLI team reproduce the problem?
1) Depend on a package that has devDependencies and builds based on those
2) Run the following:
```
export NODE_ENV=production
npm i
```

### supporting information:

 - `npm -v` prints: 5.0.3
 - `node -v` prints: 8.0.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux or macOS
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [x] I deploy to a PaaS (Triton, Heroku).

Feature arrived in: https://github.com/npm/npm/pull/16533

**Comment by jy95** [comment]
I just got this issue with npm 5.3.0 ... funny fact, "prepare" works on Travis CI (see [this](https://travis-ci.org/jy95/torrent-files-library/jobs/268974522) ) and the project has [one](https://github.com/jy95/torrent-files-library/blob/master/package.json#L10)

What I ran to find out 
```bash
npm install jy95/torrent-files-library --verbose -P
```

Here is the [log](https://gist.github.com/jy95/f11411e38e95056d233a0e608fa3a8ba) I got locally.

OS: Windows X64
npm : 5.3.0
node : v6.10.3
