### ISSUE TITLE
[ERROR] An error occurred while running npm install (exit code 235):

### ISSUE THREAD

**Issue by gcamana** [npm/npm#17062]
```
npm ERR! addLocal Could not install /var/folders/xz/xlfkwrtj24700tkprcy352gc0000gn/T/npm-818-fa7d4fb2/git-cache-773c09b4/c97ffb70a339ed2fa20eec5d7a7344a14cf268fd
    npm ERR! Darwin 16.6.0
    npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
    npm ERR! node v6.11.0
    npm ERR! npm  v3.10.10
    npm ERR! code EISDIR
    npm ERR! errno -21
    npm ERR! syscall read
    
    npm ERR! eisdir EISDIR: illegal operation on a directory, read
    npm ERR! eisdir This is most likely not a problem with npm itself
    npm ERR! eisdir and is related to npm not being able to find a package.json in
    npm ERR! eisdir a package you are trying to install.
    
    npm ERR! Please include the following file with any support request:
    npm ERR!     /Users/giogio/Documents/bizwatts-mobile/npm-debug.log
```

**Comment by kenany** [comment]
@gcamana Is there a `package.json` in your current directory?

**Comment by iarna** [comment]
We're closing this support issue as it has gone three days without activity.  The npm CLI team itself does not provide support via this issue tracker, but we are happy when users help each other here.  In our experience once a support issue goes dormant it's unlikely to get further activity.  If you're still having problems, you may be better served by joining [package.community](https://package.community/) and asking your question there.

For more information about our new issue aging policies and why we've instituted them please see our [blog post](http://blog.npmjs.org/post/161832149430/npm-the-npm-github-issue-tracker-and-you).
