### ISSUE TITLE
npm ERR! code ETIMEDOUT

### ISSUE THREAD

**Issue by bineeta11** [npm/npm#17064]
I am getting this issue while doing npm install
I can ping the registry and retrieve the latest version just fine.
I also tried upgrading npm version

I tried going through below 2 issues on this site but could not resolve my issue.
https://github.com/npm/npm/issues/7699
https://github.com/npm/npm/issues/7781

$ npm install
npm WARN deprecated wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.6.1
npm ERR! npm  v2.15.9
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! syscall connect

npm ERR! network connect ETIMEDOUT 43.142.144.92:80
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     C:\sony\deathstar\npm-debug.log

hope this is away to find out if I am behind any proxy or not>
$ npm config list
; cli configs
user-agent = "npm/2.15.9 node/v4.6.1 win32 x64"

; userconfig C:\Users\bineeta.kundu\.npmrc
proxy = null

; builtin config undefined
prefix = "C:\\Users\\bineeta.kundu\\AppData\\Roaming\\npm"

; node bin location = C:\Program Files\nodejs\node.exe
; cwd = C:\sony\deathstar
; HOME = C:\Users\bineeta.kundu
; 'npm config ls -l' to show all defaults.

Thanks,
Bineeta

**Comment by legodude17** [comment]
Please update npm to the latest version.

**Comment by sahilkatia** [comment]
I am facing same error. I updated npm with 5.0.0 and node with 8.0,0 but still facing same issue

**Comment by bineeta11** [comment]
I updated the npm but still the same issue.

**Comment by legodude17** [comment]
What are the results of:
1. `npm config get registry`
2. `npm config get http-proxy`
3. `npm config get https-proxy`

**Comment by sahilkatia** [comment]
I am facing same issue and my results are following


Vipins-Air:desktop vipingupta$ npm config get registry
http://registry.npmjs.org/
Vipins-Air:desktop vipingupta$ npm config get http-proxy
http://username:password@proxy-address.com:80/
npm config set https-proxy http://username:password@proxy-address.com:80/
Vipins-Air:desktop vipingupta$ npm config get https-proxy
null

**Comment by sahilkatia** [comment]
@bineeta11  please let me know if your issue is fixed or not? if its fixed please let me know how you did it

**Comment by jotatoledo** [comment]
Having the same issue after updatting node and npm to latest

**Comment by htmlauthor** [comment]
Having same issue, started after upgrading from v3 to v5.0.3.
My logs and config:

>npm install
npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are
 deprecated. See https://nodemailer.com/status/
npm WARN registry Unexpected warning for http://registry.npmjs.org/: Miscellaneous Warning ETIMEDOUT: request to http://registry.npmjs.org/rx-lite failed, reason: connect ETIMEDOUT XX.XX.XX.XXX:80
Terminate batch job (Y/N)? y

>npm config list
; cli configs
metrics-registry = "http://registry.npmjs.org/"
scope = ""
user-agent = "npm/5.0.3 node/v6.10.3 win32 x64"

>; userconfig C:\Users\XXXXX\.npmrc
cafile = "C:\\Users\\XXXXX\\curl-ca-bundle.crt"
https-proxy = "http://PROXYUSER:PROXYPASS@isas.danskenet.net:80/"
proxy = "http://PROXYUSER:PROXYPASS@isas.danskenet.net:80/"
registry = "http://registry.npmjs.org/"
rejectUnauthorized = false
strict-ssl = true

>; builtin config undefined
prefix = "C:\\Users\\XXXXX\\AppData\\Roaming\\npm"

>; node bin location = C:\Program Files\nodejs\node.exe
; cwd = C:\Users\XXXXX\Projects\apimanager
; HOME = C:\Users\XXXXX
; "npm config ls -l" to show all defaults.

Things to note:
- System running windows 7 behind corporate proxy.
- registry used over plain http, not https
- problems started after upgrading to new version, was working fine on v3 with same config

**Comment by sahilkatia** [comment]
Try this and let me know if this doesn't work for you

http://luxiyalu.com/how-to-remove-all-npm-proxy-settings/

**Comment by htmlauthor** [comment]
@sahilkatia this did helped, thank you.

As link is not always working, copying instructions here:

> Try these all just in case.

>npm config delete http-proxy
npm config delete https-proxy

>npm config rm proxy
npm config rm https-proxy

>set HTTP_PROXY=null
set HTTPS_PROXY=null

**Comment by nishantkaushik74** [comment]
I was going through the same error. the root cause was the proxy settings : there are several answers provided in here to reset the proxy but none of them worked for me.
below is the commands that solved my problem give them a try.

npm config rm proxy
npm config rm https-proxy
