### ISSUE TITLE
Network install error: "ENOTSUP: operation not supported on socket, fsync"

### ISSUE THREAD

**Issue by malexdev** [npm/npm#17066]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

1. I created a new folder (`testproject`) inside a network path.
  - Network path is mapped via symlink: `~/dev` -> `/Volumes/NetworkShare/Dev`.
  - `pwd` shows `/Volumes/NetworkShare/Dev/testproject`.
2. I then ran `npm init` and created the `package.json` file.
3. I then ran `npm i mz`, which did install to the `node_modules` folder correctly.  However the `package.json` file was not updated, and no `package-lock.json` file was created.  I received the following output:

> npm WARN saveError ENOTSUP: operation not supported on socket, fsync
> npm WARN saveError ENOTSUP: operation not supported on socket, fsync
> npm WARN testproject@0.1.0 No repository field.
> 
> + mz@2.6.0
> updated 1 package in 2.01s

Notes: 

- This issue is not related to `mz`; that is just my example.  I have tried many other installs and this same issue occurs.
- I have tested this on Windows and this exact same setup works fine.

#### How can the CLI team reproduce the problem?

1. Create a folder on a network path.
1. Create a project and initialize via `npm init`.
1. Attempt to install a dependency.

No `npm-debug.log` file was created.  I assume this is because this was flagged as a `WARN`.

### supporting information:

 - `npm -v` prints: `5.0.3`
 - `node -v` prints: `v8.0.0`
 - `npm config get registry` prints: My internal registry path.
 - Windows, OS X/macOS, or Linux?: macOS 10.11.6
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by jeandat** [comment]
I have the exact same problem. 
I can reproduce this on macOS Sierra 10.12.6 with node 8.0.4 and npm 5.4.2.

`npm i` or `npm rm`do their job partially: they can remove or install a dependency but can't update `package.json`. 

```bash
$ npm rm -D jshint-esnext
npm WARN saveError ENOTSUP: operation not supported on socket, fsync
npm WARN saveError ENOTSUP: operation not supported on socket, fsync
npm WARN pally-webservice-orange@1.6.7 No license field.

removed 25 packages in 18.611s
```

I can reproduce similar issues with network shares, vmware shared folders, etc.

npm doesn't seem to work with mounted folders.

**Comment by francamps** [comment]
I am finding the same issue, also on a network disk.
Node 8.9.0 and npm 5.5.1.

`npm` does the job of installing but it doesn't save anything to `package.json`. It saves the module in `node_modules` but leaves no trace in it.

```
$ npm install --save-dev sass-loader
npm WARN saveError ENOTSUP: operation not supported on socket, fsync
npm WARN saveError ENOTSUP: operation not supported on socket, fsync
```

**Comment by voidstate** [comment]
Also getting this error. OSX connecting to network Windows server.

**Comment by tsteele2013** [comment]
Having the same issue on macOS High Sierra.

On my local machine:
node -v: 8.9.4
npm -v: 5.7.1

On the Windows VM where my mounted folder is located:
node -v: 6.7.0
npm -v: 3.10.3

`npm WARN saveError ENOTSUP: operation not supported on socket, fsync`
