### ISSUE TITLE
ERROR WHEN INSTALLING

### ISSUE THREAD

**Issue by Handinursan** [npm/npm#17079]
C:\>npm -g install node-red
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Prgram File\\nodejs\\node.exe" "C:\\Program File\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "-g" "install" "node-red"
npm ERR! node v6.11.0
npm ERR! npm v3.10.10

npm ERR! shasum check failed for C:\Users\Andri\AppData\Local\Temp\npm-5656-6cd26cb1\registry.npmjs.org\moment\-\moment-2.18.1.tgz
npm ERR! Expected: c36193dd3ce1c2eed2adb7c802dbbc77a81b1c0f
npm ERR! Actual:     7cc839af2108981f24bbd151e3041c598ece39b9
npm ERR! From:       https://registry.npmjs.org/moment/-/moment-2.18.1.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!       <https://github.com/npm/npm/issue>

npm ERR! Please include the following file with any support request:
npm ERR!        C:\npm-debug.log

C:\>

**Comment by kenany** [comment]
@Handinursan Can you check and see if this still occurs with a newer version of `npm`? Thanks!

**Comment by Handinursan** [comment]
Thanks KenanY

**Comment by kenany** [comment]
@Handinursan Do you mean to say that this issue is resolved now?

**Comment by Handinursan** [comment]
@KenanY not yet, but i appreciated your reply before..

2017-06-08 21:46 GMT+07:00 Kenan Yildirim <notifications@github.com>:

**Comment by iarna** [comment]
We're closing this support issue as it has gone three days without activity.  The npm CLI team itself does not provide support via this issue tracker, but we are happy when users help each other here.  In our experience once a support issue goes dormant it's unlikely to get further activity.  If you're still having problems, you may be better served by joining [package.community](https://package.community/) and asking your question there.

For more information about our new issue aging policies and why we've instituted them please see our [blog post](http://blog.npmjs.org/post/161832149430/npm-the-npm-github-issue-tracker-and-you).
