### ISSUE TITLE
How to fix ? Error

### ISSUE THREAD

**Issue by efremoz** [npm/npm#17072]
Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "smart-grid"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ENOSELF

**Comment by kenany** [comment]
@efremoz Make sure the `"name"` property in your `package.json` is not set to `"smart-grid"`. Make it more unique! If your current directory is also called `smart-grid/` you may need to rename that as well.

**Comment by iarna** [comment]
We're closing this support issue as it has gone three days without activity.  The npm CLI team itself does not provide support via this issue tracker, but we are happy when users help each other here.  In our experience once a support issue goes dormant it's unlikely to get further activity.  If you're still having problems, you may be better served by joining [package.community](https://package.community/) and asking your question there.

For more information about our new issue aging policies and why we've instituted them please see our [blog post](http://blog.npmjs.org/post/161832149430/npm-the-npm-github-issue-tracker-and-you).
