### ISSUE TITLE
Not saving my npm login credentials to .npmrc anymore

### ISSUE THREAD

**Issue by binarykitchen** [npm/npm#17078]
#### I'm opening this issue because:

  - [ x ] npm is doing something I don't understand.

#### What's going wrong?

Since npmjs.org warned me about the recent password theft, I changed mine yesterday and now I am unable to `npm publish` my packages anymore.

After an `npm logout`, I deleted my local `.npmrc` and then tried with a `npm adduser` to have my username and my new password in form of a hash written to a new `.npmrc` file. But then, it doesn't. All it contains is something like this

```
~ ❯❯❯ cat .npmrc
//registry.npmjs.org/:_authToken=(removed)
```

Why is username and email not written to the `.npmrc` anymore and why do I always have to authenticate myself every time before I can publish a npm package?

#### How can the CLI team reproduce the problem?

Try the above ...

### supporting information:

```
~ ❯❯❯ npm -v
5.0.3
~ ❯❯❯ node -v
v4.4.5
```

on macOS Sierra here.

**Comment by binarykitchen** [comment]
Btw, here a verbose extract when I do a login

```
~ ❯❯❯ npm login --verbose
npm info it worked if it ends with ok
npm verb cli [ '/Users/michael-heuberger/.nvm/versions/node/v4.4.5/bin/node',
npm verb cli   '/Users/michael-heuberger/.nvm/versions/node/v4.4.5/bin/npm',
npm verb cli   'login',
npm verb cli   '--verbose' ]
npm info using npm@5.0.3
npm info using node@v4.4.5
npm verb config Skipping project config: /Users/michael-heuberger/.npmrc. (matches userconfig)
Username: michael.heuberger
Password:
Email: (this IS public) michael.heuberger@binarykitchen.com
npm verb adduser before first PUT { _id: 'org.couchdb.user:michael.heuberger',
npm verb adduser   name: 'michael.heuberger',
npm verb adduser   password: 'XXXXX',
npm verb adduser   email: 'michael.heuberger@binarykitchen.com',
npm verb adduser   type: 'user',
npm verb adduser   roles: [],
npm verb adduser   date: '2017-06-08T02:37:21.885Z' }
npm verb request uri https://registry.npmjs.org/-/user/org.couchdb.user:michael.heuberger
npm verb request new user, so can't send auth
npm info attempt registry request try #1 at 2:37:21 PM
npm verb request id db7b56a51f2c5297
npm http request PUT https://registry.npmjs.org/-/user/org.couchdb.user:michael.heuberger
npm http 201 https://registry.npmjs.org/-/user/org.couchdb.user:michael.heuberger
npm verb headers { 'content-type': 'application/json',
npm verb headers   'cache-control': 'max-age=300',
npm verb headers   'content-length': '127',
npm verb headers   'accept-ranges': 'bytes',
npm verb headers   date: 'Thu, 08 Jun 2017 02:37:22 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-akl1422-AKL',
npm verb headers   'x-cache': 'MISS',
npm verb headers   'x-cache-hits': '0',
npm verb headers   'x-timer': 'S1496889442.984231,VS0,VE668',
npm verb headers   vary: 'Accept-Encoding' }
npm info adduser Authorized user michael.heuberger
Logged in as michael.heuberger on https://registry.npmjs.org/.
npm verb exit [ 0, true ]
npm info ok
```

Why it is skipping? See this one line

```
npm verb config Skipping project config: /Users/michael-heuberger/.npmrc. (matches userconfig)
```

**Comment by kenany** [comment]
🤔 I don't think hashed usernames/passwords have been used for quite some time now. I too have the authToken line you do, and my `npm publish`s are fine.

```
$ cat ~/.npmrc
//registry.npmjs.org/:_authToken={...}
loglevel=http
```

**Comment by binarykitchen** [comment]
@KenanY nope it doesn't work for me. seeing this error again when trying to publish something:

```
Publishing to npm ...
npm ERR! code ENEEDAUTH
npm ERR! need auth auth required for publishing
npm ERR! need auth You need to authorize this machine using `npm adduser`

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/michael-heuberger/.npm/_logs/2017-06-08T08_48_55_129Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

here the whole debug log:
https://gist.github.com/binarykitchen/e052bb44152e4b9eeb359f15b5ef53b1

and i was able to `npm adduser` successfully before i tried to publish the above. why it is asking for authentication?

**Comment by kenany** [comment]
Hmm, I wonder if it has to do with your registry being `https://registry.yarnpkg.com/`? Might be worth a shot to try to use the default `registry` value.

**Comment by binarykitchen** [comment]
ugh, why is yarn involved when i just did a `npm` command? @KenanY 

i have few yarn related stuff in the repo but sometimes i type npm commands instead due to some yarn bugs. here the repo https://github.com/binarykitchen/videomail-client

**Comment by kenany** [comment]
Hmm, nothing in that repo stands out to me as something that might cause this. As a sanity check, what's the result of

```
npm config get registry
```

after switching to your Node.js v7.7.2 installation via `nvm`?

**Comment by binarykitchen** [comment]
here you go @KenanY 
```
~/c/videomail-client ❯❯❯ nvm ls                                                                        develop ✭
         v4.4.5
->       v7.7.2
default -> 7.7.2 (-> v7.7.2)
node -> stable (-> v7.7.2) (default)
stable -> 7.7 (-> v7.7.2) (default)
iojs -> N/A (default)
lts/* -> lts/boron (-> N/A)
lts/argon -> v4.8.3 (-> N/A)
lts/boron -> v6.10.3 (-> N/A)
~/c/videomail-client ❯❯❯ npm config get registry                                                       develop ✭

https://registry.npmjs.org/
~/c/videomail-client ❯❯❯ 
```
all looks correct ... so any guess what the cause could be?

**Comment by kenany** [comment]
And publishing still fails even after https://github.com/binarykitchen/videomail-client/commit/afcb5ee6b3fba5a7388daa4e7e024f6185d552a1?

**Comment by binarykitchen** [comment]
oh right, forgot to close this one. it was more a yarn related issue. i've been mixing yarn and npm in a bash script.

but i think yarn and/or npm should be a little safer here and print a warning or so ...
