### ISSUE TITLE
Permissions issue with rxjs after upgrading to npm5/node8

### ISSUE THREAD

**Issue by dhniels** [npm/npm#17071]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

After updating my node/npm versions to latest (using homebrew), removing the node_modules folder and running npm install I have a weird issue where rxjs doesnt install with the proper permissions. It isnt allowing read access at all to the user, therefore it breaks my app with a bunch of 403 errors on rxjs dependencies. Each time I do an npm install I have to do a chmod 755 on the rxjs folder.

I tried completely removing and uninstalling node and reinstalling, clearing the cache, etc but with no success. I just had my coworker upgrade his node/npm version and he began having the exact same issue. He downgraded to the prior version he was on and the issue disappeared.

See issue I opened in rxjs as well for reference: https://github.com/ReactiveX/rxjs/issues/2644

Here is a the log of my npm install:

```
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN prefer global node-gyp@3.6.2 should be installed with -g

> node-sass@4.5.3 install /usr/local/var/www/squava/node_modules/node-sass
> node scripts/install.js

Cached binary found at /Users/davenielsen/.npm/node-sass/4.5.3/darwin-x64-57_binding.node


> fsevents@1.1.1 install /usr/local/var/www/squava/node_modules/fsevents
> node install

node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [ '/usr/local/Cellar/node/8.0.0_1/bin/node',
node-pre-gyp verb cli   '/usr/local/var/www/squava/node_modules/fsevents/node_modules/.bin/node-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--fallback-to-build' ]
node-pre-gyp info using node-pre-gyp@0.6.33
node-pre-gyp info using node@8.0.0 | darwin | x64
node-pre-gyp verb command install []
node-pre-gyp info check checked for "/usr/local/var/www/squava/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" (not found)
node-pre-gyp http GET https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.1/fse-v1.1.1-node-v57-darwin-x64.tar.gz
node-pre-gyp http 404 https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.1/fse-v1.1.1-node-v57-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.1/fse-v1.1.1-node-v57-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.1 and node@8.0.0 (node-v57 ABI) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.1/fse-v1.1.1-node-v57-darwin-x64.tar.gz
node-pre-gyp verb command build [ 'rebuild' ]
SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
  COPY /usr/local/var/www/squava/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node
  TOUCH Release/obj.target/action_after_build.stamp
node-pre-gyp info ok

> node-sass@4.5.3 postinstall /usr/local/var/www/squava/node_modules/node-sass
> node scripts/build.js

Binary found at /usr/local/var/www/squava/node_modules/node-sass/vendor/darwin-x64-57/binding.node
Testing binary
Binary is fine

added 901 packages in 45.11s
```

### supporting information:

 - `npm -v` prints: 5.0.3
 - `node -v` prints: 8.0.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?:  MacOS Sierra

**Comment by chrmoritz** [comment]
This is likely the same issue as in #16896. 

npm@<=4 used to normalize permissions when extracting tarballs, but there was an undocumented breaking change in npm@5 and files are now extracted with the same permissions as in the tarball.
Looking at the latest rxjs@5.4.0 tarball nearly all files in there have 640 permissions, which could be the cause of your issues.

**Comment by dhniels** [comment]
I think you hit the nail on the head. I'll wait for an update - seems like theres quite a few bugs that need ironing out with the new version. good luck!
