### ISSUE TITLE
pls help! 

### ISSUE THREAD

**Issue by dorinaaaaalin** [npm/npm#17087]
C:\Sites\react-telephone-input>npm start
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\node-v6.10.3-win-x64\\node.exe" "C:\\node-v6.10.3-win-x64\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10

npm ERR! missing script: start
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Sites\react-telephone-input\npm-debug.log

C:\Sites\react-telephone-input>npm config get registry
https://registry.npmjs.org/

C:\Sites\react-telephone-input>npm cache clean

C:\Sites\react-telephone-input>npm install express
react-telephone-input@4.0.1 C:\Sites\react-telephone-input
`-- express@4.15.3
  +-- accepts@1.3.3
  | `-- negotiator@0.6.1
  +-- array-flatten@1.1.1
  +-- content-disposition@0.5.2
  +-- content-type@1.0.2
  +-- cookie@0.3.1
  +-- cookie-signature@1.0.6
  +-- debug@2.6.7
  +-- depd@1.1.0
  +-- encodeurl@1.0.1
  +-- escape-html@1.0.3
  +-- etag@1.8.0
  +-- finalhandler@1.0.3
  | +-- debug@2.6.7
  | `-- unpipe@1.0.0
  +-- fresh@0.5.0
  +-- merge-descriptors@1.0.1
  +-- methods@1.1.2
  +-- on-finished@2.3.0
  | `-- ee-first@1.1.1
  +-- parseurl@1.3.1
  +-- path-to-regexp@0.1.7
  +-- proxy-addr@1.1.4
  | +-- forwarded@0.1.0
  | `-- ipaddr.js@1.3.0
  +-- range-parser@1.2.0
  +-- send@0.15.3
  | +-- debug@2.6.7
  | +-- destroy@1.0.4
  | +-- http-errors@1.6.1
  | `-- mime@1.3.4
  +-- serve-static@1.12.3
  +-- setprototypeof@1.0.3
  +-- statuses@1.3.1
  +-- type-is@1.6.15
  | `-- media-typer@0.3.0
  +-- utils-merge@1.0.0
  `-- vary@1.1.1

C:\Sites\react-telephone-input>npm install

C:\Sites\react-telephone-input>npm start
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\node-v6.10.3-win-x64\\node.exe" "C:\\node-v6.10.3-win-x64\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10

npm ERR! missing script: start
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Sites\react-telephone-input\npm-debug.log

**Comment by sateffen** [comment]
The log tells you, that there is no "start" script.

With "npm run" you're trying to run a script, described in the *scripts* section of your package.json, see [here](https://docs.npmjs.com/misc/scripts).

Start is a special script, that works, if you have a file called *server.js* in your project root.

So first of all check your package.json, and if everything seems fine, you can post the scripts part here.

**Comment by iarna** [comment]
We're closing this support issue as it has gone three days without activity.  The npm CLI team itself does not provide support via this issue tracker, but we are happy when users help each other here.  In our experience once a support issue goes dormant it's unlikely to get further activity.  If you're still having problems, you may be better served by joining [package.community](https://package.community/) and asking your question there.

For more information about our new issue aging policies and why we've instituted them please see our [blog post](http://blog.npmjs.org/post/161832149430/npm-the-npm-github-issue-tracker-and-you).
