### ISSUE TITLE
npm i --no-save ../foo deletes foo's node_packages folder

### ISSUE THREAD

**Issue by ericeslinger** [npm/npm#17099]
#### I'm opening this issue because:

  - [X] npm is producing an incorrect install.
  - [X] npm is doing something I don't understand.

#### What's going wrong?

I have one package that depends on another. I updated the dependant package, and am testing locally, so I didn't feel like pushing to github and stuff. So I did `npm i --no-save ../core`. Note I did the --no-save because I don't want to pollute my package and package-lock files with relative references.

Running that install *seems* to have deleted the node_modules directory from the `core` directory. I noticed when I made another change and tried to run `gulp build` in core again, before running the install from the depending package. The second time, gulp failed to find a local gulp, and I indeed had no node_modules anymore.

This happens consistently. Each time I do `npm i --no-save ../core` from my depending directory, I have to go back to the core directory and run `npm i` because node_modules disappears.

This is worrying, since npm is deleting files outside of its purview.

Here's the relevant bits from my terminal, in the event they help. LMK if you need me to create some minimal test or something.

(for the record, the two packages in question are 

https://github.com/ericeslinger/plump (which is in the `core` directory, so maybe a confict between published packages and local directories that override them?)

https://github.com/ericeslinger/plump-strut (the package I'm working on when I run `npm i ../core`)

```
eric@beefalo: ~/Develop/plump/strut master ⚡ $ cd ../core            [14:53:16]
eric@beefalo: ~/Develop/plump/core master ⚡ $ gulp                   [15:24:51]
[15:24:53] Using gulpfile ~/Develop/plump/core/gulpfile.js
[15:24:53] Starting 'default'...
[15:24:53] Starting 'clean'...
[15:24:53] Finished 'clean' after 23 ms
[15:24:53] Starting 'build'...
[15:24:57] Finished 'build' after 3.51 s
[15:24:57] Finished 'default' after 3.54 s
eric@beefalo: ~/Develop/plump/core master ⚡ $ cd ../strut            [15:24:57]
eric@beefalo: ~/Develop/plump/strut master ⚡ $ npm i --no-save ../core
+ plump@0.14.0
updated 1 package in 10.886s
eric@beefalo: ~/Develop/plump/strut master ⚡ $ cd ../core            [15:25:18]
eric@beefalo: ~/Develop/plump/core master ⚡ $ gulp                   [15:29:35]
[15:29:37] Local gulp not found in ~/Develop/plump/core
[15:29:37] Try running: npm install gulp
FAIL: 1
eric@beefalo: ~/Develop/plump/core master ⚡ $ ls                     [15:29:37]
LICENSE           etc               package.json      tslint.json
README.md         gulp              src               typings.json
dist              gulpfile.js       test
documentation     package-lock.json tsconfig.json
eric@beefalo: ~/Develop/plump/core master ⚡ $                        [15:29:54]
```

#### How can the CLI team reproduce the problem?

try installing a package in a  relative directory with --no-save.

### supporting information:

 - `npm -v` prints: 5.0.3
 - `node -v` prints: 8.1.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: OSX

**Comment by eamodio** [comment]
We are seeing the same thing -- is there any workaround besides downgrading to v4?

**Comment by ericeslinger** [comment]
I've delved into figuring out how to use npm link. It seems like npm link sometimes does the same thing (deletes the node_packages dir), but that only happens once, and I don't have to keep updating my child project with the core library each time I add a little bit to core.

**Comment by ericeslinger** [comment]
okay, never mind. if I do the following:

1. finish work on parent package, run `npm link` in that dir.
2. go to child directory, run `npm link parent`

this works for a bit, but then

3. change child dependencies, run `npm i` in child directory
4. npm reports "updated 1 package, removed 437 packages"
5. that was npm deleting the node_modules directory from `parent`.

note: I was *in* the `child` directory at the time, I'd manually updated package.json in child, ran npm i to add the new stuff, and foop, there goes the `parent` node_modules. I still find it really distressing that npm is randomly deleting packages from directories outside of its purview.

**Comment by iarna** [comment]
This should be fixed in npm@5.1! Please give it a try and if you run into issues again open an new issue.

**Comment by ericeslinger** [comment]
The weird thing is that this is still happening in my dev directory, but as I walked through the repro steps (including freshly git cloning the repos that cause this problem), it is not happening in my repro directory. Could be some weird half-cache thing. I'll try the "power cycle" approach and just rm -rf everything and restart from a fresh git clone, see if that fixes things.

**Comment by ericeslinger** [comment]
yeah, doing npm cache clean --force and re-cloning the repos, and then doing npm i from scratch seems to have given the system the kick it needed. Can confirm it works as intended now.

**Comment by ericeslinger** [comment]
oops, it looks like reinstalling over the previously-installed sibling directory still deletes the sibling's node_modules. opened a new one.
