### ISSUE TITLE
Error while running command npm install

### ISSUE THREAD

**Issue by aditi741997** [npm/npm#17095]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Error while running npm install. 
 node bin/npm-cli.js prune --prefix=. --no-global && rimraf test/*/*/node_modules && make doc-clean && make -j4 doc THIS command is failing.
 https://github.com/npm/npm/blob/latest/TROUBLESHOOTING.md

    
#### How can the CLI team reproduce the problem?
Attached file.

[npm-debug.txt](https://github.com/npm/npm/files/1061758/npm-debug.txt)

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?: Windows
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by darcusfenix** [comment]
Hey, I think I have the same error. I only typed "npm install"

```
$ npm install 
npm ERR! Cannot read property 'find' of undefined
```

Log file 
```
10250 verbose stack TypeError: Cannot read property 'find' of undefined
10250 verbose stack     at opts.integrity.digests.find.hash (/home/adm/downloads/node-v7.5.0-linux-x64/lib/node_modules/npm/node_modules/ssri/index.js:262:33)
10250 verbose stack     at Array.find (native)
10250 verbose stack     at Transform.on (/home/adm/downloads/node-v7.5.0-linux-x64/lib/node_modules/npm/node_modules/ssri/index.js:261:15)
10250 verbose stack     at emitNone (events.js:91:20)
10250 verbose stack     at Transform.emit (events.js:186:7)
10250 verbose stack     at endReadableNT (_stream_readable.js:974:12)
10250 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:74:11)
10250 verbose stack     at process._tickCallback (internal/process/next_tick.js:98:9)
10251 verbose cwd /home/adm/Documents/masnomina/frontend/spa
10252 verbose Linux 4.10.0-22-generic
10253 verbose argv "/home/adm/downloads/node-v7.5.0-linux-x64/bin/node" "/home/adm/downloads/node-v7.5.0-linux-x64/bin/npm" "install"
10254 verbose node v7.5.0
10255 verbose npm  v5.0.0
10256 error Cannot read property 'find' of undefined
10257 verbose exit [ 1, true ]
```

**Comment by legodude17** [comment]
Try updating to the latest version of npm

**Comment by darcusfenix** [comment]
@legodude17 thank you. It works!!

**Comment by legodude17** [comment]
@darcusfenix Glad to hear that!

@KenanY Can this be closed?

**Comment by kenany** [comment]
@legodude17 Let's wait for a reply from @aditi741997.

**Comment by iarna** [comment]
We're closing this support issue as it has gone three days without activity.  The npm CLI team itself does not provide support via this issue tracker, but we are happy when users help each other here.  In our experience once a support issue goes dormant it's unlikely to get further activity.  If you're still having problems, you may be better served by joining [package.community](https://package.community/) and asking your question there.

For more information about our new issue aging policies and why we've instituted them please see our [blog post](http://blog.npmjs.org/post/161832149430/npm-the-npm-github-issue-tracker-and-you).
