### ISSUE TITLE
sudo npm install -g @angular/cli :- gives me lot of bugs

### ISSUE THREAD

**Issue by sahilkatia** [npm/npm#17092]
![screen shot 2017-06-08 at 10 10 05 am](https://user-images.githubusercontent.com/14021901/26935962-f869531a-4c32-11e7-89aa-0d1b786a6c92.png)
![screen shot 2017-06-08 at 10 10 05 am](https://user-images.githubusercontent.com/14021901/26935977-00d5eb9e-4c33-11e7-9226-e2a098cb5e88.png)

#### I'm opening this issue because:

  - [x] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

Please find screenshots of my terminal and give your valuable suggestions

**Comment by kenany** [comment]
@sahilkatia I do not see any bugs in the output you've posted. All of those lines that begin with the hyphen are simply pointing out the packages that are being removed.

**Comment by sahilkatia** [comment]
it should be installed in my machine but its not.

**Comment by kenany** [comment]
@sahilkatia The screenshots should that you are running `npm uninstall`, which removes packages. Do you mean to be running?:

```
sudo npm install -g @angular/cli
```

**Comment by sahilkatia** [comment]
yeah,  I run :-sudo uninstall. But previously I did run sudo intsall but nothing happened. I will post new picture installation command.

**Comment by sahilkatia** [comment]
Its running like this from last two hours. Previously I had proxy issues then I re-installed Node and now its showing this 
![screen shot 2017-06-08 at 6 45 14 pm](https://user-images.githubusercontent.com/14021901/26955181-ce88907c-4c7a-11e7-88f6-5c1b02e70fde.png)

**Comment by kenany** [comment]
You probably want to change `http-proxy` to be your actual proxy, right?

**Comment by kenany** [comment]
Actually, we can take this to https://github.com/npm/npm/issues/17102 if you want.

**Comment by sahilkatia** [comment]
I don't know it was showing proxy errors so I googled it, searched it on
stackoverflow and follow others advice. But nothing worked for me.
