### ISSUE TITLE
"npm init" hangs when asking for version

### ISSUE THREAD

**Issue by onlywei** [npm/npm#17093]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I made a new directory and typed `npm init`. When it asks me for the version, nothing I type in my keyboard seems to have any effect and I cannot proceed. My only choice is to close my terminal window and start a new on.

#### How can the CLI team reproduce the problem?
I used `nvm` to install Node 8.1.0, which came with NPM 5.0.3. All I did was make a new directory and tried `npm init`.

### supporting information:

 - `npm -v` prints: 5.0.3
 - `node -v` prints: 8.1.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: OS X 10.12.5
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by cgravill** [comment]
I have the same issue on Windows 10 using the installers on https://nodejs.org/en/download/current/. I was able to workaround the issue by switching to the earlier Node: v8.0.0 and NPM: 5.0.0 release.

**Comment by antonf** [comment]
Same issue on latest Arch Linux, npm version: 4.6.1, node version: v8.1.0

**Comment by cwhiteley** [comment]
Node 8.1.0, NPM 5.0.3, Mac OS X 10.11.6 - new install with Brew.  npm init hangs at version.
Creating an empty package.json is a simple workaround 
     npm install express --save 
However this gave me a permissions error for the /.npm/_cacache directory which was corrected with this command
     sudo chown -R $USER:$GROUP ~/.npm
From that point i am able to use the npm commands to install local packages.  I then attempted the INIT cmd in another directory.. still hangs.

Mileage may very.

**Comment by darcyclarke** [comment]
I'm getting the same issue utilizing `nvm` and working in a fresh directory (ie. no `package.json`)

OSx: 10.12.5
Node: 8.1.0
NPM: 5.0.3

**Comment by blfuentes** [comment]
Same here:

Two machines
**Windows 10**
Node: 8.1.0
NPM: 5.0.3

**Windows 7**
Node: 8.1.0
NPM: 5.0.0

**Comment by krokofant** [comment]
Same problem with npm 5.0.3 and node v8.1.0.

Interestingly enough [yarn](https://github.com/yarnpkg/yarn) v0.24.6 freezes at the same spot.

It seems this might have to do with node rather than npm?

**Comment by darcyclarke** [comment]
Currently being tracked in `node` core under: https://github.com/nodejs/node/issues/13557

**Comment by chaitanyaphalak** [comment]
Same problem with npm 5.0.3 and node v8.1.0. Linux 64bit

**Comment by DivByZRo** [comment]
Same here: Hangs on version number question and can't input any text or do exit except by closing window.

Windows 10
Node: 8.1.0
NPM: 5.0.3

**Comment by DasBlues94** [comment]
Can confirm I have the same problem

Windows 10
node 8.1.0
npm 5.0.3

**Comment by addaleax** [comment]
This is being fixed in https://github.com/nodejs/node/pull/13560, so wait until the next Node 8.x release and you’ll be fine.

**Comment by beiyu98** [comment]
Same problem with npm 5.0.3 and node v8.1.0. ubuntu16.04 64bit

**Comment by legodude17** [comment]
@brucecodezone I would suggest you use node v7 until the next node 8.x release.

**Comment by saurabhpati** [comment]
Same here, npm 5.0.3 and node 8.1.0 on Windows 8.1

**Comment by banziyeoh** [comment]
Same here, npm 5.0.3 and node 8.1.0 on Windows 10

**Comment by raitucarp** [comment]
same here, use eslint --init, npm 5.0.3 and node 8.1.0 on Ubuntu 16.04

**Comment by ghost** [comment]
Same issue -

Debian 8 x64
Node v8.1.0
NPM v5.0.3

**Comment by minaz912** [comment]
I'm having the same issue, npm 5.0.2, node 8.1.0, ArchLinux.
Same issue when trying the same command with `yarn`.

**Comment by legodude17** [comment]
This is a node bug, so just use node v7 until node next node 8 release comes out.

**Comment by HossamSamir** [comment]
I'm having the same issue,
-node v8.1.0
-v5.0.3
-Debian 6.3.0-11

**Comment by dongyuwei** [comment]
`yarn init` has the same issue: hangs when asking for version.
Mac 10.12.2
node v8.1.0
npm v5.0.3

**Comment by Lakston** [comment]
Same problem

- node 8.1.0
- npm 5.0.3
- OSX10.12.3

I'll try to revert to node 8.0 and report back.

**Comment by trgwii** [comment]
Temporary workaround:
`npm init -y`
then edit the resulting package.json

**Comment by nelsontodd** [comment]
same issue here.

- node v8.1.0
- debian stretch

**Comment by rawnly** [comment]
Same issue on macOS 10.12 still sucks on version, same with yarn... i'm trying to downgrade from 8 to 6

**Comment by Adriansun** [comment]
Same problem.

 - node 8.1.0
 - npm 5.0.3
 - Windows 10 x64 latest

**Comment by listopher** [comment]
Same issue:
- node 8.1.0
- npm 5.0.3
- Windows 10 x64 latest

**Comment by SilentFlute** [comment]
同样的问题,后来用回8.0就好了

**Comment by ghost** [comment]
Same issue here..

- node 8.1.0
- npm 5.0.3
- Windows 10 x64 latest

**Comment by valentinogagliardi** [comment]
Same issue:

- node 8.1.0
- npm 5.0.3
- Fedora 25 Workstation

**Comment by gurpreetatwal** [comment]
I don't think there is a need to post system specs. The upstream PR has already been merged and will be included in the next version of node; which should be releasing today. 

REF: nodejs/node#13598

**Comment by gfx** [comment]
Why a new npm is not yet released?

**Comment by trgwii** [comment]
@gfx It's not a problem with npm. It's a problem with node. Update to the latest nodejs version and it will be fixed.

**Comment by gfx** [comment]
Sure. nodejs v8.1.1 works well.

**Comment by ghost** [comment]
@gfx https://github.com/nodejs/node/pull/13560

**Comment by addaleax** [comment]
I think this can be closed now, it has been fixed in Node v8.1.1/v8.1.2.

**Comment by RichieMessi** [comment]
Guys I get the same error but giving the npm init command on git bash works fine for me..Try it

**Comment by ghost** [comment]
@RichieMessi Node version and NPM version? More info please...

**Comment by c-hew** [comment]
Doesn't work on Windows 10 CMD.

**Comment by zqWu** [comment]
same problem
os: mac
node -v: 8.1.0
npm -v :5.0.3

**Comment by addaleax** [comment]
@zqWu Please update to the latest version of Node from https://nodejs.org/, it will solve your problem.

**Comment by mmohoney** [comment]
same problem
node -v: 8.1.3
npm -v :5.0.3

**Comment by ghost** [comment]
@mmohoney  Please update to the latest version of Node from https://nodejs.org/, it will solve your problem.

Sorry dude, but can't you read a little bit?

**Comment by telemmaite** [comment]
@addaleax Thanks 8.1.4 is working for me. @jerome724 try it out!

**Comment by ugaxm** [comment]
@jerome724 v8.1.4 working for me! Thanks!
