### ISSUE TITLE
npm install fails with invalid version number specified in package.json; it should not

### ISSUE THREAD

**Issue by merges** [npm/npm#17097]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
```
$ npm install
npm WARN Invalid version: "0.0.1.a"
```
Install silently fails; no packages are installed. If this truly is a `WARN` and not an `ERR`, installation should proceed.

#### How can the CLI team reproduce the problem?

See above. Specify `0.0.1.a` as version number in `package.json`.

### supporting information:

 - `npm -v` prints: 4.1.2
 - `node -v` prints: v7.6.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Mac OS X

**Comment by legodude17** [comment]
Try using npm@5.
