### ISSUE TITLE
Run npm install relative to the parent directory using --prefix on Windows

### ISSUE THREAD

**Issue by vyshkov** [npm/npm#17100]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?

Hi.
I have following project structure:

 ->app
  --->client
  --->server
I need to run npm install from server folder (i have build script) 

So i running
`npm --prefix "../client" install`

But instead of going to parent folder, npm creating folder with `..` name and client inside. And trying to run npm install there. And installation fails because package.json is not there.

I use Windows.

How can i define relative path from parent folder ?

### supporting information:

 - `npm -v` prints:
4.0.5
 - `node -v` prints:
v7.4.0

Debug log:

> 0 info it worked if it ends with ok
> 1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
> 1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
> 1 verbose cli   'install',
> 1 verbose cli   '--prefix',
> 1 verbose cli   '../webapp' ]
> 2 info using npm@4.0.5
> 3 info using node@v7.4.0
> 4 silly loadCurrentTree Starting
> 5 silly install loadCurrentTree
> 6 silly install readGlobalPackageData
> 7 silly fetchPackageMetaData .
> 8 silly fetchOtherPackageData .
> 9 silly cache add args [ '.', null ]
> 10 verbose cache add spec .
> 11 silly cache add parsed spec Result {
> 11 silly cache add   raw: '.',
> 11 silly cache add   scope: null,
> 11 silly cache add   escapedName: null,
> 11 silly cache add   name: null,
> 11 silly cache add   rawSpec: '.',
> 11 silly cache add   spec: 'D:\\Development\\Projects\\myprj\\console\\sandbox',
> 11 silly cache add   type: 'local' }
> 12 error addLocal Could not install D:\Development\Projects\myprj\console\sandbox
> 13 silly fetchPackageMetaData Error: EISDIR: illegal operation on a directory, read
> 13 silly fetchPackageMetaData  error for . { Error: EISDIR: illegal operation on a directory, read errno: -4068, code: 'EISDIR', syscall: 'read' }
> 14 silly rollbackFailedOptional Starting
> 15 verbose stack TypeError: Cannot read property 'path' of null
> 15 verbose stack     at Installer.rollbackFailedOptional (C:\Program Files\nodejs\node_modules\npm\lib\install.js:505:29)
> 15 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
> 15 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
> 15 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:18:7
> 15 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install.js:331:5
> 15 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
> 15 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
> 15 verbose stack     at chain (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
> 15 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install.js:288:5
> 15 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:16:22
> 16 verbose cwd D:\Development\Projects\myprj\console\sandbox
> 17 error Windows_NT 10.0.15063
> 18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--prefix" "../webapp"
> 19 error node v7.4.0
> 20 error npm  v4.0.5
> 21 error Cannot read property 'path' of null
> 22 error If you need help, you may report this error at:
> 22 error     <https://github.com/npm/npm/issues>
> 23 verbose exit [ 1, true ]

**Comment by legodude17** [comment]
Does this still occur with the latest version of `npm`?

**Comment by alexweissman** [comment]
@vyshkov I'm having a similar problem - were you able to solve this?
