### ISSUE TITLE
Prevent `npm install` from updating lockfile on CI

### ISSUE THREAD

**Issue by steebchen** [npm/npm#17101]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I npm install locally to create a lockfile or npm i/rm to update it and I have CI hooks which deploy to suitable servers (master/staging).
On CI and the servers, the commands `git pull` and `npm install` are used, but it seems that they may update the package-lock.json file, resulting into merge conflicts in future `git pull`s.
I don't want the lockfile to be updated on these systems, similar to yarn's --pure-lockfile option.
It seems that there is no such behaviour documented (or implemented). I can only see the `--no-package-lock` option, but I assume that this ignores the lockfile completely.

#### How can the CLI team reproduce the problem?
`npm install` to create a lockfile.
`npm install` somewhere else and the package-lock.json file may be updated.
I currently don't know when exactly the lockfile changes, but it does.

### supporting information:

 - `npm -v` prints: 5.0.3 (on both my computer and "somewhere else")
 - `node -v` prints: v8.0.0 (on both my computer and "somewhere else")
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux Mint 18 + Debian 8
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
I think the somewhere else `npm install` could be `npm install --no-save` and that would fix your problem.

**Comment by steebchen** [comment]
Ah, great, I'll try that. I think it would be appropriate to document this, since I personally know `--no-save` only from adding or removing packages.

**Comment by zkat** [comment]
`--no-save` will do it!
