### ISSUE TITLE
503 All backends failed or unhealthy

### ISSUE THREAD

**Issue by mshaaban088** [npm/npm#17117]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Trying to install dependencies via `npm install` and got `503 All backends failed or unhealthy` with registry error parsing json

![screen shot 2017-06-09 at 16 09 47](https://user-images.githubusercontent.com/3688136/26979679-ec9af5ea-4d2f-11e7-8c8b-90021d2a6aad.png)

#### How can the CLI team reproduce the problem?
simple `npm install`
It is happening from time to time, not always, sometimes works, sometimes not

### supporting information:

 - `npm -v` prints: 3.10.10
 - `node -v` prints: v7.3.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS
 - Network issues:
   - Geographic location where npm was run: Berlin
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ x ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by jotatoledo** [comment]
Having the same error, never before 😕 
npm -v : 3.10.8
node -v: 6.9.1

**Comment by legodude17** [comment]
Does this occur on the default registry with the latest version of npm?

**Comment by thescientist13** [comment]
Seems related to the June 9th status report
https://status.npmjs.org/
> Jun 9, 2017
Increased 503 rates for public packages
Resolved - We've identified the issue as a case of a service's process getting stuck and resolved it by rolling the affected service. 
Jun 9, 14:30 UTC
Investigating - We're currently investigating issues related to accessing scoped packages. 
Jun 9, 14:25 UTC

**Comment by iarna** [comment]
We're closing this support issue as it has gone three days without activity.  The npm CLI team itself does not provide support via this issue tracker, but we are happy when users help each other here.  In our experience once a support issue goes dormant it's unlikely to get further activity.  If you're still having problems, you may be better served by joining [package.community](https://package.community/) and asking your question there.

For more information about our new issue aging policies and why we've instituted them please see our [blog post](http://blog.npmjs.org/post/161832149430/npm-the-npm-github-issue-tracker-and-you).
