### ISSUE TITLE
Feature request: npm upgrade-all-dependencies

### ISSUE THREAD

**Issue by Flimm** [npm/npm#17115]
#### What's the feature?

I am asking for an npm command to see if all top-level dependencies (and devDependencies) are up-to-date, and to allow upgrading them. The command should not limit itself to the version ranges specified in `package.json`. The command should allow updating `package.json`, `package-lock.json` and `npm-shrinkwrap.json`. I'm not set on the name `upgrade-all-dependencies`. It could even be a flag for another subcommand.

For instance, let's say `package.json` contains the dependency `"gulp": "^2.0.0"`, then `npm upgrade-all-dependencies` would upgrade `gulp` to `3.9.1` (the latest version at time of writing), and would modify `package.json` to be `"gulp": "^3.9.1"`, as well as `package-lock.json` and `npm-shrinkwrap.json` if those exist.

#### What problem is the feature intended to solve?

Once a version range is specified in `package.json`, it's not very easy to check if a new major version of an npm module has been released, and to upgrade to it. This would make it easier.

#### Is the absence of this feature blocking you or your team? If so, how?

No.

#### Is this feature similar to an existing feature in another tool?

Yes, https://www.npmjs.com/package/npm-check-updates and https://www.npmjs.com/package/npm-check . However, it seems wrong to have to install these tools with all their dependencies, just to do something that would seem to be part of npm itself.

#### Is this a feature you're prepared to implement, with support from the npm CLI team?

No, not me.

**Comment by happilymarrieddad** [comment]
+1 on this

**Comment by kahwee** [comment]
If this is of interest, I'll be happy to help out. I wanted an `npm outdated --fix` or something.

**Comment by danielcherubini** [comment]
This would be a MASSSSIVE timesaver

**Comment by deyvsh** [comment]
I briefly got annoyed at this getting closed, then I tried [ncu](https://www.npmjs.com/package/npm-check-updates). It's great:
`npm i --save-dev npm-check-updates`
`npx ncu -u`
`npm up`

**Comment by kataras** [comment]
You shouldn't close that.. people are switching to yarn for that reason mostly, re-open and discuss with the js developers please.

**Comment by kenany** [comment]
@kataras Feel free to open a thread on https://npm.community/c/ideas; this issue tracker is shutting down so no use in reopening this ticket.
