### ISSUE TITLE
npm install not working

### ISSUE THREAD

**Issue by mehta-rohan** [npm/npm#17114]
#### I'm opening this issue because:

  - [ y] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I have updated my npm to 5.0.3
Now I am not able to install modules. I am ending up in below error

npm ERR! code EPROTO
npm ERR! errno EPROTO
npm ERR! request to https://registry.npmjs.org/firebase-admin failed, reason: wr
ite EPROTO 101057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown
protocol:openssl\ssl\s23_clnt.c:794:
npm ERR!

#### How can the CLI team reproduce the problem?
I am not able to use: npm install ANYMODULE 

### supporting information:

 - `npm -v` prints: 5.0.3
 - `node -v` prints: v7.2.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows
 - Network issues:
   - Geographic location where npm was run:
   - [y ] I use a proxy to connect to the npm registry.
   - [y ] I use a proxy to connect to the web.
   - [ y] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
What is the result of `npm config list`?

**Comment by OGNova** [comment]
I am having the same issue. When doing `npm config list`, this is the result. http://prntscr.com/fhzl6g

**Comment by mehta-rohan** [comment]
hey!!
@legodude17 | @OGNova 
I was behind proxy.
What I need was registry config with http protocol. I was on https.
Thanks for help.
