### ISSUE TITLE
npm prune will remove global packages

### ISSUE THREAD

**Issue by k8w** [npm/npm#17110]
#### I'm opening this issue because:

  - [ √ ] npm is producing an incorrect install.

#### What's going wrong?
`npm prune` will remove global packages that is dependencies of linked global package.

#### How can the CLI team reproduce the problem?

```
# install webpack globally
npm i webpack -g
npm link webpack

# works well
webpack



# there is no "webpack" in package.json
npm prune

# Can not find webpack, work as intended
webpack

# Link again
npm link webpack

# Error: Cannot find module 'yargs'
webpack

```

So `yargs` is a global package that global `webpack` depends on.
In a project folder, link webpack, and prune(webpack is not in package.json), shouldn't make global package not work.

### supporting information:

 - `npm -v` prints: 5.0.3
 - `node -v` prints: 7.7.2
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Win7
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by k8w** [comment]
Even if `npm install` in project folder that linked `webpack` will get this. (make global webpack unuseable)

**Comment by twoeo** [comment]
reopen
