### ISSUE TITLE
argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install"

### ISSUE THREAD

**Issue by zhangxue61** [npm/npm#17125]
#### I'm opening this issue because:

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10

npm ERR! shasum check failed for C:\Users\ADMINI~1\AppData\Local\Temp\npm-3068-6ed3410e\registry.npmjs.org\node-pngquant-native\-\node-pngquant-native-1.0.4.tgz
npm ERR! Expected: b22dc666da175954e32bd4a3c0c61ef8d2ce60c5
npm ERR! Actual:   21e172d1d8831a1f16e4bba4f6f8f918e4d9e905
npm ERR! From:     https://registry.npmjs.org/node-pngquant-native/-/node-pngquant-native-1.0.4.tgz
npm ERR!

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
@zhangxue61 Does this also occur with newer versions of `npm`?

**Comment by iarna** [comment]
We're closing this support issue as it has gone three days without activity.  The npm CLI team itself does not provide support via this issue tracker, but we are happy when users help each other here.  In our experience once a support issue goes dormant it's unlikely to get further activity.  If you're still having problems, you may be better served by joining [package.community](https://package.community/) and asking your question there.

For more information about our new issue aging policies and why we've instituted them please see our [blog post](http://blog.npmjs.org/post/161832149430/npm-the-npm-github-issue-tracker-and-you).

**Comment by avinash2622** [comment]
you were trying to download the module without specifying the version of module. So try this...
npm install module_name@0.0.0 --save
