### ISSUE TITLE
invalid Protocol-Error, probably based on Proxy settings

### ISSUE THREAD

**Issue by DanielSchlabbers** [npm/npm#17127]
- [X] npm is producing an incorrect install.

#### What's going wrong?
During npm install it crashes, concluding in: Invalid protocol: proxy.wdf.sap.corp:

I already tried the related Proxy settings in npm config and on my machine. I am not in any VPN and checking Proxy-Settings in cmd (with: reg query "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings" | find /i "proxyserver" ) results in: proxy:8080, which I also tried in the npm proxy config.

Log-File: https://gist.github.com/DanielSchlabbers/f6af40223e06b7f25205c53db4027f13 

### supporting information:

node v6.11.0
npm  v3.10.10
regristry: http://registry.npmjs.org/
Windows 10

**Comment by iarna** [comment]
We're closing this support issue as it has gone three days without activity.  The npm CLI team itself does not provide support via this issue tracker, but we are happy when users help each other here.  In our experience once a support issue goes dormant it's unlikely to get further activity.  If you're still having problems, you may be better served by joining [package.community](https://package.community/) and asking your question there.

For more information about our new issue aging policies and why we've instituted them please see our [blog post](http://blog.npmjs.org/post/161832149430/npm-the-npm-github-issue-tracker-and-you).
