### ISSUE TITLE
Document `npm outdated --json`

### ISSUE THREAD

**Issue by Ryuno-Ki** [npm/npm#17122]
#### What's the feature?

Add documentation for [`npm outdated --json`](https://github.com/npm/npm/blob/latest/lib/outdated.js#L174).

#### What problem is the feature intended to solve?

JSON is easier to consume then [`npm outdated --parseable`](https://github.com/npm/npm/blob/latest/lib/outdated.js#L12) output.

#### Is the absence of this feature blocking you or your team? If so, how?

No, but I feel not comfortable with using undocumented features.

#### Is this feature similar to an existing feature in another tool?

It's just a third way to format the output.

#### Is this a feature you're prepared to implement, with support from the npm CLI team?

I'm not familiar with that CLA thingy. Since Canonical enforced one on Launchpad, they leave a bad taste to me...

**Comment by kenany** [comment]
Are you asking for more than what [the current documentation](https://docs.npmjs.com/cli/outdated#json) already has?

**Comment by Ryuno-Ki** [comment]
Thanks. I was looking at [the source code of outdated.js](https://github.com/npm/npm/blob/latest/lib/outdated.js#L12), which only mentions `--parseable`...

**Comment by iarna** [comment]
Closing as resolved. =)
