### ISSUE TITLE
npm install is failing

### ISSUE THREAD

**Issue by MaryBhattacharjee** [npm/npm#17134]
I am unable to install npm in my system using the command "npm install". The error says:
shasum check failied for C:\Users...
Expected: ...some string...
Actual: ...some another string...
From: https://registry.npmjs.org/qs/-/qs-6.3.2.tgz
[npm install error log.docx](https://github.com/npm/npm/files/1066418/npm.install.error.log.docx)

**Comment by kenany** [comment]
@MaryBhattacharjee Could you upload the log as plaintext to <https://gist.github.com/> instead of converting it? Thanks!

**Comment by sundarseswaran** [comment]
@KenanY -- I think I have a similar issue here, for the same version of Node v6.11.0 & npm 3.10.10
I am trying to do npm install in a Dockerfile... it fails for every package that has a dependency on `node-gyp` .    NPM installs finishes successfully if I add the flag `--ignore-scripts`  but the install doesn't seems to be complete.

```
76919 silly install node-gyp@3.4.0 /usr/src/app/node_modules/.staging/node-gyp-cf365a36
76920 info lifecycle node-gyp@3.4.0~install: node-gyp@3.4.0
76921 silly lifecycle node-gyp@3.4.0~install: no script for install, continuing
76922 silly install snappy@5.0.5 /usr/src/app/node_modules/.staging/snappy-e9b47663
76923 info lifecycle snappy@5.0.5~install: snappy@5.0.5
76924 verbose lifecycle snappy@5.0.5~install: unsafe-perm in lifecycle false
76925 verbose lifecycle snappy@5.0.5~install: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/usr/src/app/node_modules/snappy/node_modules/.bin:/usr/src/app/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
76926 verbose lifecycle snappy@5.0.5~install: CWD: /usr/src/app/node_modules/snappy
76927 silly lifecycle snappy@5.0.5~install: Args: [ '-c', 'node-gyp rebuild' ]
76928 verbose stack Error: spawn ENOMEM
76928 verbose stack     at exports._errnoException (util.js:1018:11)
76928 verbose stack     at ChildProcess.spawn (internal/child_process.js:319:11)
76928 verbose stack     at exports.spawn (child_process.js:378:9)
76928 verbose stack     at spawn (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:21:13)
76928 verbose stack     at runCmd_ (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:247:14)
76928 verbose stack     at /usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:211:7
76928 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:73:7)
76928 verbose stack     at process._tickCallback (internal/process/next_tick.js:104:9)
76929 verbose cwd /usr/src/app
76930 error Linux 3.13.0-91-generic
76931 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "i"
76932 error node v6.11.0
76933 error npm  v3.10.10
76934 error code ENOMEM
76935 error errno ENOMEM
76936 error syscall spawn
76937 error spawn ENOMEM
76938 error If you need help, you may report this error at:
76938 error     <https://github.com/npm/npm/issues>
76939 verbose exit [ 1, true ]
```

**Comment by kenany** [comment]
@sundarseswaran How much RAM does the container have?

**Comment by sundarseswaran** [comment]
@KenanY -- Good question. With the error message I didn't realize I am running in a machine that has a bunch of other containers running already. Thanks, lessons learnt.  

But, I do have one issue with npm installing all our packages failing with the node-gyp dependency. Will try to get you the exact message. It could be an issue with the package itself.

**Comment by sundarseswaran** [comment]
@KenanY -- what ever that didn't build properly, for us, yesterday - worked today just fine. Thanks for your support.  👍

**Comment by iarna** [comment]
We're closing this support issue as it has gone three days without activity.  The npm CLI team itself does not provide support via this issue tracker, but we are happy when users help each other here.  In our experience once a support issue goes dormant it's unlikely to get further activity.  If you're still having problems, you may be better served by joining [package.community](https://package.community/) and asking your question there.

For more information about our new issue aging policies and why we've instituted them please see our [blog post](http://blog.npmjs.org/post/161832149430/npm-the-npm-github-issue-tracker-and-you).
