### ISSUE TITLE
Npm cache clean

### ISSUE THREAD

**Issue by nikhildhar1992** [npm/npm#17135]
nikhil@debian:/var/www/html$ sudo npm cache clean
[sudo] password for nikhil: 
npm ERR! TypeError: glob.hasMagic is not a function
npm ERR!     at rimraf (/usr/lib/nodejs/rimraf/rimraf.js:61:36)
npm ERR!     at gentlyRm (/usr/share/npm/lib/utils/gently-rm.js:29:12)
npm ERR!     at /usr/lib/nodejs/slide/lib/async-map.js:54:35
npm ERR!     at Array.forEach (native)
npm ERR!     at /usr/lib/nodejs/slide/lib/async-map.js:54:11
npm ERR!     at Array.forEach (native)
npm ERR!     at asyncMap (/usr/lib/nodejs/slide/lib/async-map.js:53:8)
npm ERR!     at /usr/share/npm/lib/cache.js:183:7
npm ERR!     at go$readdir$cb (/usr/lib/nodejs/graceful-fs/graceful-fs.js:149:14)
npm ERR!     at FSReqWrap.oncomplete (fs.js:82:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "cache" "clean"
npm ERR! cwd /var/www/html
npm ERR! node -v v4.8.2
npm ERR! npm -v 1.4.21

**Comment by kenany** [comment]
`npm@1` is years old and is no longer supported. I can reopen this if the issue persists with newer versions of `npm`.
