### ISSUE TITLE
On execution of script "npm start" error - "missing script: start" is displayed

### ISSUE THREAD

**Issue by nehamittal15** [npm/npm#17139]
0 info it worked if it ends with ok
1 verbose cli [ 'F:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'F:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.10
3 info using node@v6.9.5
4 verbose stack Error: missing script: start
4 verbose stack     at run (F:\Program Files\nodejs\node_modules\npm\lib\run-script.js:151:19)
4 verbose stack     at F:\Program Files\nodejs\node_modules\npm\lib\run-script.js:61:5
4 verbose stack     at F:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:356:5
4 verbose stack     at handleExists (F:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:329:20)
4 verbose stack     at FSReqWrap.cb [as oncomplete] (fs.js:257:19)
5 verbose cwd F:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src
6 error Windows_NT 10.0.14393
7 error argv "F:\\Program Files\\nodejs\\node.exe" "F:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
8 error node v6.9.5
9 error npm  v3.10.10
10 error missing script: start
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by Greek** [comment]
You need a start script for your package.json file.

**Comment by nehamittal15** [comment]
Please provide the start script

Thanks,
Neha

**Comment by kenany** [comment]
@nehamittal15 Here's an example `package.json` which contains a `"start"` script:

``` json
{
  "name": "package-name",
  "version": "1.0.0",
  "description": "package description",
  "scripts": {
    "start": "node --version",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {},
  "devDependencies": {}
}
```

Note how this `package.json` has a `"start"` script that runs `node --version`. You'll definitely want to change the command to whatever is most appropriate for your project.

**Comment by nehamittal15** [comment]
Hello,

I unable to find the location to add "Start" script. I have attached copy of npm-cli file and read-package-json file.

Please let me know the exact location to place "Start" script and what would the exact "Start" script code.
So, that I can start the tech-trail.

Thanks,
Neha

[CopyOf_npm-cli.txt](https://github.com/npm/npm/files/1068112/CopyOf_npm-cli.txt)
[CopyOf_read-package-json.txt](https://github.com/npm/npm/files/1068113/CopyOf_read-package-json.txt)

**Comment by kenany** [comment]
@nehamittal15 `package.json` is a file which should live in your project's root directory. If you don't yet have one, you can run `npm init` to create it for you.

**Comment by nehamittal15** [comment]
what should I enter in field named "entry point: (index.js)" asked while creating "npm init"

**Comment by kenany** [comment]
@nehamittal15 It's specific to your project, so unfortunately that's not easy for me to answer.

**Comment by nehamittal15** [comment]
so, how could I know its value ? Is there any way through which I can find this ? can u send me a copy of npm init, for more understanding. Because there could be more fields next after that.

**Comment by kenany** [comment]
@nehamittal15 You can probably get away with just leaving it as the default value for the time being, especially if this project is one that you will publish to a registry.

**Comment by nehamittal15** [comment]
Please find the attached error log, and help me how I can get out of it.
[copyof_npm-debug.txt](https://github.com/npm/npm/files/1068523/copyof_npm-debug.txt)

**Comment by kenany** [comment]
@nehamittal15 I think you must've accidentally entered a version number as your `"start"` script, because the log indicates that `1.1.1` is literally trying to be executed as a command.

**Comment by nehamittal15** [comment]
As I have entered "1.1.1" in the version while creation of "npm init" and in your initial script you have mentioned in - 

"scripts": {
    "start": "node --version",
    "test": "echo \"Error: no test specified\" && exit 1"
  }

so, I added `"start": "1.1.1"`

**Comment by nehamittal15** [comment]
please help me get out of this error... one day of my test trail is already over and I haven't started yet.

**Comment by kenany** [comment]
@nehamittal15 Right, as I pointed out earlier, you have to replace
`"node --version"` with whatever you want `npm start` to run.

**Comment by nehamittal15** [comment]
So, what version should I enter ?

**Comment by kenany** [comment]
@nehamittal15 I guess I've confused you with the `node --version` part. That's
just an example `"start"` script I made up. It's not something you should
actually replace with your Node version. You need to replace it with whatever
command you want executed when you run `npm start`.

Here is another example: let's say you had a `test.js` file in the same
directory as your `package.json`. Let's say you want `npm start` to run that
file. In that case, your `"start"` script would look something like:

```
  "start": "node test.js"
```

Now, when you run `npm start`, what will be executed is `node test.js`. I can
try to come up with more examples if you're still stuck :)

**Comment by nehamittal15** [comment]
I have written - 
"start": "node npm-cli.js"

As this is the only ".js" file I knew about.

Please find the attached error log.


[CopyOf_npm-debug.txt](https://github.com/npm/npm/files/1069988/CopyOf_npm-debug.txt)

**Comment by kenany** [comment]
@nehamittal15 Does `npm-cli.js` exist in your current directory?

**Comment by nehamittal15** [comment]
No, it was present not in the same directory. I have tried to execute it from its directory as well, on doing that it displays different error.

Now, from directory "F:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp", I have executed "npm start", for '"start": "node node-gyp.js"' which was present in "F:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin". Still error is displayed.

[CopyOf_npm-debug.txt](https://github.com/npm/npm/files/1070091/CopyOf_npm-debug.txt)

**Comment by kenany** [comment]
@nehamittal15 Hmm, all right, let's back up a bit:

  1. _why_ are you in the `F:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp` directory?
  2. _what_ would you like `npm start` to do from that directory?

I might be able to help more if I understood what your end goal is.

**Comment by nehamittal15** [comment]
its been written in Readme file that - 
'Run the application:
	- Open Command Prompt (Windows) or Terminal (Mac) or Bash (Linux)
	- Go to the "src" folder (Located on the same folder of this file)
	- Execute this command (*): npm install --development
	- Execute this command: npm start --development

	(*) The first time you execute this command, it will take some time downloading the required packages'

And "src" is in folder "F:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp", that's why I am executing "npm start" from here.

**Comment by kenany** [comment]
@nehamittal15 Which README specifically?

**Comment by nehamittal15** [comment]
readme file received from "Crossover" in "QA Manual Tester Assignment.pdf"

**Comment by kenany** [comment]
@nehamittal15 Either those instructions are wrong, or you're looking at the wrong `src` directory. I highly doubt they would ask you to enter `node-gyp`'s `src` directory.

**Comment by nehamittal15** [comment]
They have asked for "src" folder and there is no other "src" folder available except this one in "F:\Program Files\nodejs".

**Comment by kenany** [comment]
At this point, this really isn't an `npm` issue anymore. It's been explained above _why_ you're getting the "missing script" errors, and _how_ to fix it. Now the issue is just figuring out these instructions you've been given, which is way too environment-specific to be solved by us. Hopefully you can contact the authors of that README for clarification. Good luck! :)

**Comment by UmeshShelke06** [comment]
hello
I have same problem :am following " https://www.tutorialspoint.com/reactjs/reactjs_environment_setup.html  " for running simple "hello world" program on reactjs but  at last stage of above mentioned tutorial 
when I run "npm start "command I face  this error on node.js cmd...please help me to sort out the following error :

C:\Users\Umesh1\Desktop\reactApp>npm start
'CALL "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\\node_modules
\npm\bin\npm-cli.js" prefix -g' is not recognized as an internal or external com
mand,
operable program or batch file.

> reactapp@1.0.0 start C:\Users\Umesh1\Desktop\reactApp
> webpack-dev-server --hot

npm ERR! file C:\Program Files\Java\jdk1.8.0_144
npm ERR! path C:\Program Files\Java\jdk1.8.0_144
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn C:\Program Files\Java\jdk1.8.0_144
npm ERR! reactapp@1.0.0 start: `webpack-dev-server --hot`
npm ERR! spawn C:\Program Files\Java\jdk1.8.0_144 ENOENT
npm ERR!
npm ERR! Failed at the reactapp@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Umesh1\AppData\Roaming\npm-cache\_logs\2018-01-04T08_27_53
_123Z-debug.log

**Comment by Greek** [comment]
@amolumesh12 Try `npm install` then try running the project again.

**Comment by UmeshShelke06** [comment]
apap04 Thanks ..but it again giving me save error at this  npm start during last stage of running program on browser .. any other solutions ?
