### ISSUE TITLE
Failed PUT 403 - The feed already contains the package...

### ISSUE THREAD

**Issue by Davy-F** [npm/npm#17145]
#### I'm opening this issue because:
  - [x] npm is doing something I don't understand.

#### What's going wrong?

Trying to call "npm publish 'namegoeshere'" to VSTS gets the following error:

> Failed PUT 403
> code E403
> Forbidden: The feed already contains the package 'namegoeshere' at version '0.0.3': _packaging

If I call "npm publish" I get the following error:

> nsp is not recognized as an internal or external command, operable program or batch file.
> ...
> code ELIFECYCLE
> namegoeshere@0.0.4 prepublish: 'nsp check'
> Exit status 1
> 
> Failed at the namegoeshere@0.0.4 prepublish script.

I am trying to publish a new version at version 0.0.4.

### supporting information:

 - `npm -v` prints: 5.0.1
 - `node -v` prints: v6.5.0
 - `npm config get registry` prints: This is a Visual Studio registry so won't post here.
 - Windows, OS X/macOS, or Linux?: Windows
- Network is OK.

Having previously updated npm packages to Team Services (more info found here: https://www.visualstudio.com/en-us/docs/package/get-started-npm) I am now getting this error.

It's been working fine previously. I have tried clearing my npm credentials and reinstating them, and I still get the same error.

Any info would be appreciated.

**Comment by Davy-F** [comment]
Unbelievable. I called 'npm install' on the off chance it would work and then tried 'npm publish'... **Success!**

**Comment by Azadehkhojandi** [comment]
It's a note for the peeps having the same issue - if you get
>  'nsp' is not recognized as an internal or external command, 

run
> npm install -g nsp

> nsp check
