### ISSUE TITLE
Unable to download packages using npm.

### ISSUE THREAD

**Issue by Arpitrf** [npm/npm#17144]
#### I'm opening this issue because:
#
[npm-debug.zip](https://github.com/npm/npm/files/1067758/npm-debug.zip)

  - [ ] npm is doing something I don't understand.

#### How can the CLI team reproduce the problem?
Just type npm install express.

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
@Arpitrf Can you upload the log as plaintext to <https://gist.github.com/> and link it here instead of zipping it up? Thanks!

**Comment by Arpitrf** [comment]
<script src="https://gist.github.com/Arpitrf/2448210d8e8dabc77ed84e5caf9deebf.js"></script>

**Comment by kenany** [comment]
@Arpitrf Thanks. Looks like an issue with your internet connection so I'm adding the `network` label.

**Comment by nulian** [comment]
This is because fastly is broadcasting 2 routes and 1 is down.

151.101.36.0/22 80.249.212.183 ve 501 20/0 Be 2d21h - broken
151.101.36.0/22 80.249.212.184 ve 501 20/0 Be 2d21h - working

**Comment by iarna** [comment]
We're closing this support issue as it has gone three days without activity.  The npm CLI team itself does not provide support via this issue tracker, but we are happy when users help each other here.  In our experience once a support issue goes dormant it's unlikely to get further activity.  If you're still having problems, you may be better served by joining [package.community](https://package.community/) and asking your question there.

For more information about our new issue aging policies and why we've instituted them please see our [blog post](http://blog.npmjs.org/post/161832149430/npm-the-npm-github-issue-tracker-and-you).
