### ISSUE TITLE
`"false": {}` after `npm prune`

### ISSUE THREAD

**Issue by seriousManual** [npm/npm#17141]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

after removing a dependency from the package.json manually and running `npm prune` from the command line, an additional key "false" shows up in the package.json

#### How can the CLI team reproduce the problem?

````
D:\programming\npmTest>npm -v
5.0.3
D:\programming\npmTest>npm init -y
Wrote to D:\programming\npmTest\package.json:

{
  "name": "npmTest",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}

D:\programming\npmTest>npm i debug
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN npmTest@1.0.0 No description
npm WARN npmTest@1.0.0 No repository field.

+ debug@2.6.8
added 2 packages in 0.701s

======= remove the debug line manually from the package.json ======== 

D:\programming\npmTest>npm prune
npm WARN npmTest@1.0.0 No description
npm WARN npmTest@1.0.0 No repository field.

removed 4 packages in 0.292s
````

now the package.json shows the key "false":

````json
{
  "name": "npmTest",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {},
  "false": {}
}
````

### supporting information:

 - `npm -v` prints:
5.0.3
 - `node -v` prints:
v8.0.0
 - `npm config get registry` prints:
https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?:
Windows

**Comment by eaviles** [comment]
I have the same issue. Looking forward to see the resolution of this.

**Comment by hitmands** [comment]
there is also a StackOverflow question here: [new field false in Package.json](https://stackoverflow.com/questions/44564024/new-field-false-in-package-json)

**Comment by chase-moskal** [comment]
I think I just saw this "false" field appear after I manually moved some packages around in the package.json, and had then called `npm prune && npm install`...

**Comment by ddsilva** [comment]
Same issue here.
