### ISSUE TITLE
Unhandled rejection Error

### ISSUE THREAD

**Issue by dxmari** [npm/npm#17143]
Unhandled rejection Error: Command failed: /usr/bin/git clone --depth=1 -q -b master git://github.com/isaacs/inherits.git /home/dxmari/.npm/_cacache/tmp/git-clone-7f7b5688
/home/dxmari/.npm/_cacache/tmp/git-clone-7f7b5688/.git: Permission denied

    at ChildProcess.exithandler (child_process.js:204:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:497:12)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dxmari/.npm/_logs/2017-06-12T07_23_45_162Z-debug.log

please tell me how to rectify it.

**Comment by WALLE729** [comment]
I also want to know why?

**Comment by iarna** [comment]
We're closing this support issue as it has gone three days without activity.  The npm CLI team itself does not provide support via this issue tracker, but we are happy when users help each other here.  In our experience once a support issue goes dormant it's unlikely to get further activity.  If you're still having problems, you may be better served by joining [package.community](https://package.community/) and asking your question there.

For more information about our new issue aging policies and why we've instituted them please see our [blog post](http://blog.npmjs.org/post/161832149430/npm-the-npm-github-issue-tracker-and-you).
