### ISSUE TITLE
npm is throwing error while installing

### ISSUE THREAD

**Issue by pr1994** [npm/npm#17152]
PRITAM@DESKTOP-C5ON0VA MINGW32 /c/Pritam's/Angular 2/Angular-2-Tutorials-master/                                                                                                                Angular-2-Tutorials-master/Template
$ npm install
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\                                                                                                                node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10

npm ERR! shasum check failed for C:\Users\PRITAM\AppData\Local\Temp\npm-1840-527                                                                                                                9ba8e\registry.npmjs.org\weinre\-\weinre-2.0.0-pre-I0Z7U9OV.tgz
npm ERR! Expected: fef8aa223921f7b40bbbbd4c3ed4302f6fd0a813
npm ERR! Actual:   39cb808dd9d16ae24acd0fa34cc989aa4c062095
npm ERR! From:     https://registry.npmjs.org/weinre/-/weinre-2.0.0-pre-I0Z7U9OV                                                                                                                .tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by kenany** [comment]
@pr1994 Does this also occur with newer versions of `npm`?

**Comment by dschinkel** [comment]
same issue here as well https://github.com/nodejs/node/issues/13635#event-1119812867

and same for this person: https://github.com/npm/npm/issues/17146

@KenanY yes it occurs with the newer versions of npm.  I'm using 5.0.3 and Node 8.1.0

**Comment by pr1994** [comment]
@KenanY, I have restarted my desktop and now the issue is gone.
