### ISSUE TITLE
npm run that contains "yes" piped into a program hangs forever

### ISSUE THREAD

**Issue by esprehn** [npm/npm#17158]
#### I'm opening this issue because:

  - [X] npm is doing something I don't understand.

#### What's going wrong?

If you use "yes | command" in an npm script, either directly or indirectly (ex. inside a shell script) it seems that something about the environment results in yes never ending taking 100% of your CPU.

ex.

```
"scripts": {
    "my-command": "yes | ls"
},
```

or 

```
"scripts": {
  "my-command": "./script.sh"
},

script.sh:
#!/bin/bash

yes | ls
```

In both these cases "npm run my-command" will hang forever running "yes".

#### How can the CLI team reproduce the problem?

Add the example above and do npm run my-command.

### supporting information:

 - `npm -v` prints: 4.6.1
 - `node -v` prints: v6.10.3
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: OS X

**Comment by esprehn** [comment]
This looks similar to:

https://bugs.python.org/issue1652
and 
https://stackoverflow.com/questions/39397034/script-works-differently-when-ran-from-the-terminal-and-ran-from-python/39398969

**Comment by esprehn** [comment]
On Linux I'm seeing different output with it printing:
"yes: standard output: Broken pipe"

tested on npm versions 5.0.0, 3.10.8, 2.15.9

So maybe this is a bug node or npm in OS X?

Lots of folks have reported sigmask issues with node:
https://smartos.org/bugview/MANTA-3250

but I can't find any workarounds yet.

**Comment by iarna** [comment]
Looks like this was a Node.js bug that's been fixed. (I get the same behavior as Linux on v8.1.3)
