### ISSUE TITLE
Cannot install npm module vue-intro

### ISSUE THREAD

**Issue by barntrax** [npm/npm#17156]
npm ERR! Linux 3.13.0-71-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "vue-intro"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code 128

npm ERR! Command failed: git clone --template=/home/devuser/.npm/_git-remotes/_templates --mirror git@github.com:nblackburn/intro.js.git /home/devuser/.npm/_git-remotes/git-github-com-nblackburn-intro-js-git-show-hints-7f0a3a78
npm ERR! Cloning into bare repository '/home/devuser/.npm/_git-remotes/git-github-com-nblackburn-intro-js-git-show-hints-7f0a3a78'...
npm ERR! Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.

**Comment by iarna** [comment]
We're closing this support issue as it has gone three days without activity.  The npm CLI team itself does not provide support via this issue tracker, but we are happy when users help each other here.  In our experience once a support issue goes dormant it's unlikely to get further activity.  If you're still having problems, you may be better served by joining [package.community](https://package.community/) and asking your question there.

For more information about our new issue aging policies and why we've instituted them please see our [blog post](http://blog.npmjs.org/post/161832149430/npm-the-npm-github-issue-tracker-and-you).
