### ISSUE TITLE
don't install plugins

### ISSUE THREAD

**Issue by IDIDIR** [npm/npm#17154]
My project is located in a shared folder VMware.
I've already tried "npm cache clean" and "npm install npm@latest -g"

root@ubuntu:/home/node/CDN/NodeJS# npm install mongodb --save
npm ERR! Linux 4.4.0-62-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "mongodb" "--save"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! path /home/node/CDN/NodeJS/node_modules/.mongodb.DELETE/node_modules/isarray
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/home/node/CDN/NodeJS/node_modules/.mongodb.DELETE/node_modules/isarray' -> '/home/node/CDN/NodeJS/node_modules/mongodb/node_modules/isarray'
npm ERR! enoent ENOENT: no such file or directory, rename '/home/node/CDN/NodeJS/node_modules/.mongodb.DELETE/node_modules/isarray' -> '/home/node/CDN/NodeJS/node_modules/mongodb/node_modules/isarray'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /home/node/CDN/NodeJS/npm-debug.log

**Comment by IDIDIR** [comment]
"npm install -g mongodb --save" does not cause errors

**Comment by IDIDIR** [comment]
Helped remove the module (isarray) specified in the error line

**Comment by iarna** [comment]
We're closing this support issue as it has gone three days without activity.  The npm CLI team itself does not provide support via this issue tracker, but we are happy when users help each other here.  In our experience once a support issue goes dormant it's unlikely to get further activity.  If you're still having problems, you may be better served by joining [package.community](https://package.community/) and asking your question there.

For more information about our new issue aging policies and why we've instituted them please see our [blog post](http://blog.npmjs.org/post/161832149430/npm-the-npm-github-issue-tracker-and-you).
