### ISSUE TITLE
npm: "failed to fetch" error for the zeppelin-vis package

### ISSUE THREAD

**Issue by gkohnen** [npm/npm#17164]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Hello,
I'm getting a "failed to fetch" error for the zeppelin-vis package when trying to install the volume-leaflet helium package (on both repositories hosted at npmjs. Cna you help?
Thanks!
Georges

#### How can the CLI team reproduce the problem?

npm install volume-leaflet
npm http GET https://skimdb.npmjs.com/registry/volume-leaflet
npm http GET https://skimdb.npmjs.com/registry/volume-leaflet
npm http GET https://skimdb.npmjs.com/registry/volume-leaflet
npm http GET https://skimdb.npmjs.com/registry/zeppelin-tabledata
npm http GET https://skimdb.npmjs.com/registry/leaflet
npm http GET https://skimdb.npmjs.com/registry/zeppelin-vis
npm http GET https://skimdb.npmjs.com/registry/zeppelin-tabledata
npm http GET https://skimdb.npmjs.com/registry/leaflet
npm http GET https://skimdb.npmjs.com/registry/zeppelin-vis
npm http GET https://skimdb.npmjs.com/registry/zeppelin-vis
npm http GET https://skimdb.npmjs.com/registry/leaflet
npm http GET https://skimdb.npmjs.com/registry/zeppelin-tabledata
npm ERR! Error: failed to fetch from registry: zeppelin-vis
npm ERR!     at RegClient.<anonymous> (/usr/lib/node_modules/npm-registry-client/lib/get.js:140:18)
npm ERR!     at cb (/usr/lib/node_modules/npm-registry-client/lib/request.js:32:9)
npm ERR!     at RegClient.<anonymous> (/usr/lib/node_modules/npm-registry-client/lib/request.js:122:10)
npm ERR!     at cb (/usr/lib/node_modules/npm-registry-client/lib/request.js:132:9)
npm ERR!     at RegClient.<anonymous> (/usr/lib/node_modules/npm-registry-client/lib/request.js:225:20)
npm ERR!     at Request._callback (/usr/lib/node_modules/npm-registry-client/lib/request.js:204:20)
npm ERR!     at self.callback (/usr/lib/node_modules/request/index.js:148:22)
npm ERR!     at Request.emit (events.js:117:20)
npm ERR!     at ClientRequest.self.clientErrorHandler (/usr/lib/node_modules/request/index.js:257:10)
npm ERR!     at ClientRequest.emit (events.js:95:17)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.11.0-1.el7.elrepo.x86_64
npm ERR! command "node" "/usr/bin/npm" "install" "volume-leaflet"
npm ERR! cwd /usr/hdp/2.6.0.3-8/zeppelin_0.7.2/webapps/webapp/app/helium
npm ERR! node -v v0.10.48
npm ERR! npm -v 1.3.6
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /usr/hdp/2.6.0.3-8/zeppelin_0.7.2/webapps/webapp/app/helium/npm-debug.log
npm ERR! not ok code 0

### supporting information:

 - `npm -v` prints: 1.3.6
 - `node -v` prints: v0.10.48
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?: Linux
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [x] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by gkohnen** [comment]
Different errors, although also related to zeppelin-vis pop up when trying to install another package:

npm install zeppelin-bubblechart
npm http GET https://registry.npmjs.org/zeppelin-bubblechart
npm http 304 https://registry.npmjs.org/zeppelin-bubblechart
npm http GET https://registry.npmjs.org/zeppelin-tabledata
npm http 304 https://registry.npmjs.org/zeppelin-tabledata
npm http GET https://registry.npmjs.org/zeppelin-vis
npm http 404 https://registry.npmjs.org/zeppelin-vis
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/usr/lib/node_modules/npm/lib/cache.js:687:35)
npm ERR!     at /usr/lib/node_modules/npm/lib/cache.js:675:5
npm ERR!     at saved (/usr/lib/node_modules/npm-registry-client/lib/get.js:148:7)
npm ERR!     at /usr/lib/node_modules/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:108:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.11.0-1.el7.elrepo.x86_64
npm ERR! command "node" "/usr/bin/npm" "install" "zeppelin-bubblechart"
npm ERR! cwd /usr/hdp/2.6.0.3-8/zeppelin_0.7.2/webapps/webapp/app/helium
npm ERR! node -v v0.10.48
npm ERR! npm -v 1.3.6
npm ERR! type non_object_property_load
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /usr/hdp/2.6.0.3-8/zeppelin_0.7.2/webapps/webapp/app/helium/npm-debug.log
npm ERR! not ok code 0

**Comment by kenany** [comment]
Node v0.10 and `npm@1` are years old and are no longer supported. Sorry :(

**Comment by gkohnen** [comment]
Unfortunately I don't have a choice, this runs in a preconfigured sandbox. No clue as to how I could solve this?

**Comment by kenany** [comment]
@gkohnen Nope :(
