### ISSUE TITLE
Bug: npm is platform opinionated concerning line endings

### ISSUE THREAD

**Issue by NicBright** [npm/npm#17161]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?
When having a checkout of a package.json + package-lock.json on a Windows machine with git "core.autocrlf=true", then all files will have CRLF line endings. Now, when running "npm install", then npm thinks that the line endings of package.json + package-lock.json should be replaced with pure LF. This is bad, as git now thinks there are changes to the files, while in fact there are none (only line endings):

![image](https://user-images.githubusercontent.com/1225659/27066994-74cd4cee-5008-11e7-98d4-4fbbd842a013.png)

![image](https://user-images.githubusercontent.com/1225659/27044859-5b88284e-4f9f-11e7-91f8-3f7b05cead84.png)

And the same is true for IntelliJ:
![image](https://user-images.githubusercontent.com/1225659/27044893-79e5a0c8-4f9f-11e7-942e-df15eb54e9bc.png)

### supporting information:

 - `npm -v` prints: 5.0.3
 - `node -v` prints: v6.10.3
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?: Windows

**Comment by NicBright** [comment]
This sequence of commands even better illustrates the issue:

![image](https://user-images.githubusercontent.com/1225659/27067075-14adaed4-5009-11e7-80e3-2ac2a4e74264.png)

**Comment by ghost** [comment]
@NicBright thanks for your thorough write-up. Also seeing this issue _only_ since installing npm v5.0.3.

* `git config --global core.autocrlf` prints: true
* `npm -v` prints: 5.0.3
* `node -v` prints: v6.11.0
* Windows, OS X/macOS, or Linux?: Windows

**Comment by menzer** [comment]
I'm encountering what I believe is the same issue in 5.0.0 (using Node 8.0 via nvm), as well as all later versions of npm.

Someone on my team checked in `package-lock.json` files generated in MacOS. While verifying everything on Windows, running `npm i` on npm@5+ changes the line endings of both `package.json` and `package-lock.json` to CRLF. Running `npm i` with npm 4.2/node 7.10 does not change the line endings.

**Comment by stianl** [comment]
Got this problem as well after moving to NPM 5.x (Windows).

Worked around it by adding .gitattributes file  with `package*.json text eol=lf`.
Why doesn't npm use the platform specific line ending specified by `require('os').EOL`?

**Comment by FabienDeshayes** [comment]
We are facing the same problem. On some of our repos, `npm install` will modify the line endings of our `package.json`. We decided to roll back npm 5 until we find a better solution than having to add `.gitattributes` to all repos.

It would be good to have some insight from members on this.

Thanks!

**Comment by vanjan** [comment]
Any updates?

**Comment by vanjan** [comment]
any updates?

**Comment by jplebre** [comment]
Hi, any updates? :)

**Comment by vanjan** [comment]
any updates?

**Comment by emackey** [comment]
+1

**Comment by senaev** [comment]
any updates?

**Comment by collinsauve** [comment]
One workaround is to add this to your `.gitattributes` file:

```
package.json text eol=lf
package-lock.json text eol=lf
```

**Comment by deregtd** [comment]
The .gitattributes fix still isn't working for me.  Living with npm install -g npm@3 for now. :(

**Comment by Mic75** [comment]
Incoming PR #19904

**Comment by zkat** [comment]
#19904 has been merged. Cheers.

**Comment by michaeluskov** [comment]
`.gitattributes` fix doesn't work for me neither. Sometimes I get the same git modification:
```
PS C:\folder> git status
On branch npm5
Your branch is up to date with 'origin/npm5'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   package.json

no changes added to commit (use "git add" and/or "git commit -a")
PS C:\folder> git diff
PS C:\folder>
```

And it happens not every time I run `npm install`. Sometimes everything is OK. 
`.gitattributes` content is:
```
package.json text eol=lf
package-lock.json text eol=lf
```

Npm version is 5.7.1, node version is 9.8.0.

**Comment by zkat** [comment]
Locked because line ending awareness is already shipped
