### ISSUE TITLE
npm version fails if package-lock.json is gitignored

### ISSUE THREAD

**Issue by felixfbecker** [npm/npm#17168]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
If package-lock.json is .gitignored, npm version will abort at the `git add package-lock.json` step and not do a version commit + tag.

```
14:01 $ npm version major
v1.0.0
npm ERR! code 1
npm ERR! Command failed: git add /.../package-lock.json
npm ERR! The following paths are ignored by one of your .gitignore files:
npm ERR! package-lock.json
npm ERR! Use -f if you really want to add them.
npm ERR!
```

I know you recommend commiting package-lock.json even for libraries, but there are also a lot of reasons that speak against it (false sense of security, mostly targeting older versions, ...). It should be up for the user to decide, at most print a warning, not fail `npm version`.

#### How can the CLI team reproduce the problem?

- add package-lock.json to .gitignore
- run `npm version`

### supporting information:

 - `npm -v` prints: 5.0.3
 - `node -v` prints: 8.0.0
 - `npm config get registry` prints: standard
 - Windows, OS X/macOS, or Linux?: macos
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by richardsimko** [comment]
I agree! We ran in to this issue as well and with the current instability of package-lock.json (Changing back and forth between sha1 and sha512, sometimes not installing all dependencies, sometimes not including all dependencies etc) it's not feasible to rely on it.

**Comment by zkat** [comment]
https://github.com/npm/npm/pull/17505 should fix this. Cheers.

**Comment by felixfbecker** [comment]
This is still happening in v5.3.0 and v5.4.0

**Comment by justinbmeyer** [comment]
Yeah, this is happening in `5.4.2` for me.  @zkat let me know if this is expected (or not) and if you need a test.

**Comment by felixfbecker** [comment]
The workaround - which is actually good in general, because it won't lock your versions locally (so local is the same as in CI) - is to create an `.npmrc` file in your repo with
```ini
package-lock=false
```
This will make npm not even generate a package-lock in the first place.

**Comment by k8w** [comment]
5.6.0 still happen.
