### ISSUE TITLE
create-react-native-app failed

### ISSUE THREAD

**Issue by sghuang** [npm/npm#17167]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
![image](https://user-images.githubusercontent.com/28995582/27078547-95f7d098-5066-11e7-9064-dd2dac51e60a.png)

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [x] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [x] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
@sghuang Does this also occur with newer versions of `npm`, such as v4?

**Comment by sghuang** [comment]
@KenanY     i update npm to v5.0.3 and i got this error. i have try several times but every time have different sha1 and bytes.
![image](https://user-images.githubusercontent.com/28995582/27127295-fdc52574-512c-11e7-8e74-2dbaadb18d5d.png)

**Comment by sghuang** [comment]
@KenanY   finally, npm 5 is not supported yet and i install npm v4.6.1 instead.  but another error  has arisen.  would u give me some suggestions?
![image](https://user-images.githubusercontent.com/28995582/27168826-ef31db26-51d9-11e7-85ea-266348e2d48f.png)

**Comment by kenany** [comment]
@sghuang Could you upload that debug log to <https://gist.github.com/> and link it here?

**Comment by sghuang** [comment]
@KenanY   this's the debug log.  thank you
[https://gist.github.com/sghuang/e352bd051005452af9086c93a42f039c](url)

**Comment by mukulramchandani** [comment]
C:\Users\mukul>npm install -g create-react-app
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "create-react-app"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10

npm ERR! shasum check failed for C:\Users\mukul\AppData\Local\Temp\npm-9448-3cdc938e\registry.npmjs.org\cross-spawn\-\cross-spawn-4.0.2.tgz
npm ERR! Expected: 7b9247621c23adfdd3856004a823cbe397424d41
npm ERR! Actual:   affd080285a13a6ad81e9d7649a6ef9d3bf2b578
npm ERR! From:     https://registry.npmjs.org/cross-spawn/-/cross-spawn-4.0.2.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\mukul\npm-debug.log
Here's what I'm getting while installing create-react-app. Has anyone found any solution to this shasum failed errors.
