### ISSUE TITLE
npm ERR! Windows_NT 6.1.7601 issues in node-v6.11.0, npm-v3.10.10

### ISSUE THREAD

**Issue by mganigapeta** [npm/npm#17176]
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10

npm ERR! Not a valid cache tarball name: C:\Users\lenovo\AppData\Local\Temp\npm-
3100-f2f60083\registry.npmjs.org\cordova\-\cordova-7.0.1.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\lenovo\npm-debug.log

Please help me i getting this issue from npm what i download anythin from npm ,

I tried to uninstall and reinstall node but issue is not solved,

I tried all max ways to solve this but i couldn't 

can you please what i did wrong in this and tell me how to resolve when node will crashed

**Comment by kenany** [comment]
Hmm, does this also occur with newer versions of `npm`?

**Comment by mganigapeta** [comment]
@KenanY you are also getting the same issue?

**Comment by kenany** [comment]
@mganigapeta Nope.
