### ISSUE TITLE
NPM - Install Uglify Issue

### ISSUE THREAD

**Issue by ksanjeevi** [npm/npm#17174]
#### I'm opening this issue because:

  - [x] npm is producing an incorrect install.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?

I have installed the node.js and verfified it installed properly, I am trying to install  the uglify through the following command...  (i am following all the instructions from the website which is given on "https://github.com/mishoo/UglifyJS2/tree/v2.x")

=> npm install uglify-js -g

Following is the debugger error log. I tried the website which is given in the website and all sites are opening through the browser., so it is not related to network / proxy issue. ( i have good network connectivity  )

Help
===
Please kindly assist on the below issue. 

My Software Details
==============
node -v
	=> v0.12.2
npm -v
	=> 2.7.4
Ran a sample Node.js file
	=> console.log('Node is installed!');
( Reference:-  http://blog.teamtreehouse.com/install-node-js-npm-windows )

===========================================================
Log Information
===========
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'uglify-js',
1 verbose cli   '-g' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose node symlink C:\Program Files (x86)\nodejs\\node.exe
5 silly cache add args [ 'uglify-js', null ]
6 verbose cache add spec uglify-js
7 silly cache add parsed spec { raw: 'uglify-js',
7 silly cache add   scope: null,
7 silly cache add   name: 'uglify-js',
7 silly cache add   rawSpec: '',
7 silly cache add   spec: '*',
7 silly cache add   type: 'range' }
8 verbose addNamed uglify-js@*
9 silly addNamed semver.valid null
10 silly addNamed semver.validRange *
11 silly addNameRange { name: 'uglify-js', range: '*', hasData: false }
12 silly mapToRegistry name uglify-js
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/uglify-js
16 verbose addNameRange registry:https://registry.npmjs.org/uglify-js not in flight; fetching
17 verbose request uri https://registry.npmjs.org/uglify-js
18 verbose request no auth needed
19 info attempt registry request try #1 at 10:31:40 AM
20 verbose request id 65ad4e2bb03cdfa1
21 http request GET https://registry.npmjs.org/uglify-js
22 info retry will retry, error on last attempt: Error: read ECONNRESET
23 info attempt registry request try #2 at 10:31:50 AM
24 http request GET https://registry.npmjs.org/uglify-js
25 info retry will retry, error on last attempt: Error: read ECONNRESET
26 info attempt registry request try #3 at 10:32:50 AM
27 http request GET https://registry.npmjs.org/uglify-js
28 verbose stack Error: read ECONNRESET
28 verbose stack     at exports._errnoException (util.js:746:11)
28 verbose stack     at TCP.onread (net.js:559:26)
29 verbose cwd C:\Users\C197976
30 error Windows_NT 6.1.7601
31 error argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "uglify-js" "-g"
32 error node v0.12.2
33 error npm  v2.7.4
34 error code ECONNRESET
35 error errno ECONNRESET
36 error syscall read
37 error network read ECONNRESET
37 error network This is most likely not a problem with npm itself
37 error network and is related to network connectivity.
37 error network In most cases you are behind a proxy or have bad network settings.
37 error network
37 error network If you are behind a proxy, please make sure that the
37 error network 'proxy' config is set properly.  See: 'npm help config'
38 verbose exit [ 1, true ]

**Comment by iarna** [comment]
We're closing this support issue as it has gone three days without activity.  The npm CLI team itself does not provide support via this issue tracker, but we are happy when users help each other here.  In our experience once a support issue goes dormant it's unlikely to get further activity.  If you're still having problems, you may be better served by joining [package.community](https://package.community/) and asking your question there.

For more information about our new issue aging policies and why we've instituted them please see our [blog post](http://blog.npmjs.org/post/161832149430/npm-the-npm-github-issue-tracker-and-you).
