### ISSUE TITLE
npm start fails

### ISSUE THREAD

**Issue by siffondas** [npm/npm#17171]
I'm opening this issue because:
I am unable to build a project.
It says 
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start
npm ERR! node v0.12.7
npm ERR! npm v2.11.3

How can i run?

**Comment by kenany** [comment]
@siffondas Could you provide the full debug log? You can upload it to <https://gist.github.com/> and link it here. Thanks!

**Comment by siffondas** [comment]
Please see the full debug log
[npm-debug.txt](https://github.com/npm/npm/files/1073938/npm-debug.txt)

**Comment by kenany** [comment]
@siffondas So, the way `npm start` works is that it looks in your current `package.json` for a defined `"start"` [script](https://docs.npmjs.com/misc/scripts), and then runs that. The error message you're seeing is trying to tell you that you have not defined a `"start"` script in your `package.json`, hence `npm start` has no idea what you want it to do.

To solve this issue, all you have to do is add a new script to your `package.json`. It might look something like this, for example:

``` json
{
  "name": "package-name",
  "version": "1.0.0",
  "description": "package description",
  "scripts": {
    "start": "node --version",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {},
  "devDependencies": {}
}
```

Note how this `package.json` has a `"start"` script that runs `node --version`. You'll definitely want to change the command to whatever is most appropriate for your project.

Let me know if you run into any further `npm` issues :)
