### ISSUE TITLE
npm run lint error:

### ISSUE THREAD

**Issue by pvinod445** [npm/npm#17188]
I am getting an error while I run the command npm run lint
The following is the error: 

'C:\Users\Vinod' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "lint"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pluralsight-redux-starter@1.0.0 lint: `esw webpack.config.* src tools`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pluralsight-redux-starter@1.0.0 lint script 'esw webpack.config.* src tools'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pluralsight-redux-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     esw webpack.config.* src tools
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pluralsight-redux-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pluralsight-redux-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Vinod Kumar Reddy\AppData\Roaming\npm-cache\_logs\2017-06-13T22_05_23_193Z-debug.log

Can anyone help me with that

**Comment by SpartaSixZero** [comment]
Hi, not sure if you've seen this yet from the author: https://github.com/coryhouse/pluralsight-redux-starter. The page contains a bunch of troubleshooting steps.
