### ISSUE TITLE
npm 5 ignores and removes subdependencies with github: url from package-lock/shrinkwrap on install

### ISSUE THREAD

**Issue by Macil** [npm/npm#17189]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

If you have a package-lock/shrinkwrap that contains dependencies not listed in package.json (because they're subdependencies or because you have no package.json) on github, then npm doesn't install those dependencies *and then silently removes them from the shrinkwrap!*

#### How can the CLI team reproduce the problem?

https://gist.github.com/AgentME/926f8e08c3c6a1ed8b051909e7b8879c

### supporting information:

 - `npm -v` prints: 5.0.3
 - `node -v` prints: v7.8.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: OS X
 - Network issues:
   - Geographic location where npm was run: California
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by erikvold** [comment]
I am experiencing the same issue with `package-lock.json`

**Comment by mms27** [comment]
Experiencing similar issue here: [#17365](https://github.com/npm/npm/issues/17365)

**Comment by Macil** [comment]
I can no longer reproduce this with npm 5.3.0, so I'm closing this.
