### ISSUE TITLE
npm init hangs forever

### ISSUE THREAD

**Issue by agauniyal** [npm/npm#17198]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
`npm init` command hangs forever. Had to kill the terminal since it doesn't even responds to Ctrl+C.
#### How can the CLI team reproduce the problem?
```bash
~ ア mkdir newDir && cd newDir
newDir ア npm init
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

See `npm help json` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg>` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
package name: (newdir) 
version: (1.0.0)
```

### supporting information:

 - `npm -v` prints: 5.0.3
 - `node -v` prints: v8.1.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by agauniyal** [comment]
`yarn init` hangs as well 🤔 . I thought my terminal was going bad but I wrote a small program to take input and display, it worked.

```cpp
#include <iostream>
int main() { int a, b, c; std::cin >> a >> b >> c; std::cout << a << b << c; }
```

Wrote a `require('readline');` program in node, it works as well, so definitely nothing wrong with node binary as well.

**Comment by moimael** [comment]
Try to update to node 8.1.1, according to the changelog that's a bug this release fixes: https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V8.md#8.1.1

**Comment by agauniyal** [comment]
It works now!

**Comment by anu1097** [comment]
npm init still hangs for me indefinitely at the version number option. How to fix it ? My npm version is 5.0.3

**Comment by Jewismer** [comment]
I am having this problem in Visual Studio 2017 version 15.4.2
Node version 8.9.0
npm version 5.0.4

After creating a new .core MVC project in VS 2017, I deleted the package.json as I wanted to start from scratch.  The following happened:

PM> npm init
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

See `npm help json` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg>` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.


At this point, the command line is hung.  Ctrl C does not stop it, and the only way to end it is exit and restart VS 2017.

**Comment by joelmdev** [comment]
Exact same issue as @Jewismer  w/ npm v 5.6.0 and node v9.4.0

**Comment by AndrVelich** [comment]
Exact same issue as @Jewismer and joelmdev. Node version 8.9.0
npm version 5.0.4 Visual studio 2017

**Comment by shripathi-kamath** [comment]
Exact same issue as @Jewismer and @joelmdev and @AndrVelich 

node  v10.1.0
npm 5.6.0

VS2017 15.7.1

**Comment by clfolmar** [comment]
Exact same issue as @Jewismer @joelmdev @AndrVelich  and @shripathi-kamath !

node v10.1.0 and I also tried with v8.11.2
npm 5.6

VS2017 15.7.1
