### ISSUE TITLE
CLI freezes after first input

### ISSUE THREAD

**Issue by Gelio** [npm/npm#17196]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Any npm cli command that requires more than one input (for instance `npm init`, `npm adduser`) freezes after the first input line.

I tried to login with `npm adduser` and this is the problem:
![image](https://user-images.githubusercontent.com/889383/27120039-61f53520-50e2-11e7-9a21-e0332905603e.png)
I typed in the username, pressed Enter and then the prompt is frozen. I know that it won't show me the password I type, but the prompt does not react to Ctrl-C or another Enter. It's just stuck.

The same goes for `npm init`:
![image](https://user-images.githubusercontent.com/889383/27120146-c27b29cc-50e2-11e7-93da-af3246dd1760.png)
I was able to type in the name of the package, press Enter and then I'm stuck at the version input.

I have tried downgrading to npm@4, but it yields the same results. I am using [Cmder](http://cmder.net/) here, but the same happens with *Powershell* and regular Windows' *cmd*.

#### How can the CLI team reproduce the problem?

Frankly, I have no idea. It was working previously, about 4 months ago. It may be due to Windows 10 Creators Upgrade, but I'm not sure. Lots of things are broken since then, especially with the command line.

I believe there are no debug logs that I could include regarding this issue since it is a console CLI problem.

### supporting information:

 - `npm -v` prints: `5.0.3`
 - `node -v` prints: `v8.1.0`
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?: Windows 10 Pro with Creators Upgrade (Version 10.0.15063)

An interesting note would be that it works fine when using _Bash on Ubuntu on Windows_ shell, even from Cmder, it is fully responsive then.
I may as well resort to using it whenever I to use any npm commands that require user input, but this solution is not ideal.

Another note: I am experiencing the same problem when trying to run those npm commands with yarn (both `yarn init` and `yarn adduser` freeze). I have not experienced problems when running other programs that expect input.

**Comment by jiripospisil** [comment]
This was caused by an issue in Node.js 8.1.0 itself, see https://github.com/nodejs/node/issues/13557 for more info. Upgrade to 8.1.1 should fix it.

**Comment by Gelio** [comment]
@jiripospisil Thank you, you're awesome! That was the root of the problem. I was able to login normally after an upgrade.
