### ISSUE TITLE
npm error issue from Lynda.com

### ISSUE THREAD

**Issue by Areeb96** [npm/npm#17192]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [X ] npm is producing an incorrect install.
  - [X ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### How can the CLI team reproduce the problem?

![image](https://user-images.githubusercontent.com/14099306/27114216-12df236c-5090-11e7-8f1e-667589efd3b3.png)

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
@Areeb96 Make sure you have a `package.json` in your current directory which defines the `"start"` script you wanna run.

**Comment by Areeb96** [comment]
I already do but it is still not working. When I try to install some thing like 'npm install --save-dev babel-cli', here are some errors that are showing which i think are leading to this:

![image](https://user-images.githubusercontent.com/14099306/27139028-ebee3c56-50ef-11e7-8ee5-37c0c0fb4d67.png)

**Comment by kenany** [comment]
Oh, actually I just noticed your Node.js and `npm` versions, which are years old and no longer supported. If you still experience this issue with the latest releases of both, I can reopen. Sorry :(
