### ISSUE TITLE
npm doctor not showing latest Node.js recommendation

### ISSUE THREAD

**Issue by sibiraj-s** [npm/npm#17202]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other 

#### What's going wrong?

`npm doctor` is not showing latest node version available.

#### How can the CLI team reproduce the problem?

Run `npm doctor`. 

I tried in MacOs

### supporting information:
 - `npm version` - v5.0.3
-    latest node.js version - [v8.1.1](https://nodejs.org/en/) (`npm doctor` is not showing in recommendation still shows 8.1.0)

 - `npm doctor` prints:
 ```
Check                               Value                        Recommendation
npm ping                            OK
npm -v                              v5.0.3
node -v                             v8.1.0
npm config get registry             https://registry.npmjs.org/
which git                           /usr/local/bin/git
Perms check on cached files         ok
Perms check on global node_modules  ok
Perms check on local node_modules   ok
Verify cache contents               verified 2684 tarballs
```
 - Operating System - macOS:

**Comment by kenany** [comment]
v8.1.1 is not LTS, hence why `npm doctor` is not suggesting it. /cc @watilde
