### ISSUE TITLE
Running NPM is Very Slow to Start on Windows

### ISSUE THREAD

**Issue by KevinHaisol** [npm/npm#17206]
#### I'm opening this issue because:

  - [X] npm is doing something I don't understand.
  - [X] Other (_see below for feature requests_):  npm start is extremely slow

#### What's going wrong?
NPM has about a 3min delay just to start when running:
npm start (node app.js)
It looks like delays occur from:
1.)  npm start (delays about 2 minutes)
2.)  Once it starts loading theres another minute delay just to load the requires.

#### How can the CLI team reproduce the problem?
History:  I originally installed node-v4.4.0-x64.msi  and everything worked fine took under 30 seconds to start and run.  I then wanted to work on an angular 4 project and installed node-v6.11.0-x64.msi.  That worked fine.  I then needed to go back to node-v4.4.0 so I could work on my angular 1.6 project.  In order to do that, I uninstalled node from my system, removed all folders for projects and installation and then re-installed node-v4.4.0-x64.msi.  
My system immediately started responding very slow when running any npm commands and everything is very slow when responding.  I'm not sure what happens between the time I enter npm start on the command line, but the system hangs for a couple minutes.  Then it finally goes into the app.js file and starts loading it. I know this as I placed several console.log statements on every step in the file.  Also when loading the app.js the system hangs when loading each require.  Some are faster than others but I would think it should load the requires much quicker, and shouldn't take 3 minutes just to start.  

### supporting information:
Windows 10 X64
Drive: SSD
Running via command line or powershell
NPM version: 5.0.3 
Node Version:  4.4.0

 - Network issues:
   - USA
   -  Its just slow when starting the npm - node server on my localhost so I don't think it's a network thing.
 - Container:
   - [ ] I develop using texteditor on Windows.

**Comment by StevenFewster** [comment]
same with npm 5.0.3 and node 6.9.4, also
`npm -v` takes 11s which seems odd

**Comment by KevinHaisol** [comment]
Once I removed Git-Bash things are running faster npm responds in about 30 seconds again.  Not supper fast but I think it could have been Git-bash causing my whole system to slow down.
