### ISSUE TITLE
npm init crashing

### ISSUE THREAD

**Issue by marswong** [npm/npm#17219]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?
open iTerm2, go into a folder, exec `npm init`, when you just press enter, the iTerm2 would crash down, no debug log, really ridiculously.

#### How can the CLI team reproduce the problem?
As described above.

### supporting information:

 - `npm -v` prints: 5.0.3
 - `node -v` prints: 8.1.0
 - `npm config get registry` prints: https://registry.npmjs.org
 - Windows, OS X/macOS, or Linux?: OS X 10.12.5
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by rentalname** [comment]
It seems to have been fixed in node 8.1.1

**Comment by marswong** [comment]
@rentalname 
sorry, i am accustomed to use double version (which means more stable as most softwares are), v8.1.1 works, thx :)

one tip, i think mainline should not contain a version with basic feature broken
