### ISSUE TITLE
npm update failed on every npm command

### ISSUE THREAD

**Issue by harishankards** [npm/npm#17226]
#### I'm opening this issue because:

  - [x] npm is doing something I don't understand.

#### What's going wrong?
npm throws this error whenever I use npm command. It happens for every npm command

┌───────────────────────────────────────────────────────────┐
│                  npm update check failed                  
│            Try running with sudo or get access            
│           to the local update config store via            
│ sudo chown -R $USER:$(id -gn $USER) /home/ayandev/.config │
└───────────────────────────────────────────────────────────┘

#### How can the CLI team reproduce the problem?

I'm getting this issue after updating npm to version 5.0.3.  So you can do this.

![image](https://user-images.githubusercontent.com/5006693/27179120-dc715320-51ea-11e7-8189-92969dee62a1.png)

**Comment by daedraMex** [comment]
i have the same problem u.u

**Comment by arpitprod** [comment]
I've same problem. It's showing every time in every npm command. and npm update command not working.

**Comment by arpitprod** [comment]
I think it was in npm version 5.0.x issue. I updated 5.0.3 to 5.2.0 with these command and now npm is working fine.

`sudo chown -R $USER:$(id -gn $USER) /home/arpit/.config`
`npm i install -g npm`

**Comment by harishankards** [comment]
@arpitprod and @Any28Flo !

Yes, the npm version was the issue. I uninstalled npm started using [asdf](https://github.com/asdf-vm/asdf) , a version manager. Now, I'm going smooth.

**Comment by omarsawalhah** [comment]
I have the same issue and running the common at the bottom didn't fix the problem. 
┌───────────────────────────────────────────────────┐
│              npm update check failed              │
│        Try running with sudo or get access        │
│       to the local update config store via        │
│ sudo chown -R $USER:$(id -gn $USER) /root/.config │
└───────────────────────────────────────────────────┘

**Comment by harishankards** [comment]
Hi @omarsawalhah did you try installing using asdf?

**Comment by omarsawalhah** [comment]
No I didn't.

**Comment by harishankards** [comment]
Please try that and check
