### ISSUE TITLE
This is an error with npm itself - cb() never called!

### ISSUE THREAD

**Issue by AurelienC** [npm/npm#17222]
#### I'm opening this issue because:
  - [x] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Getting error when I'm trying to update or install something with npm.
> Unhandled rejection TypeError: base64 is not a functionng node@v4.2.6
>     at Function.from (native)
>     at Function.from (native)
>     at bufFrom (/usr/local/lib/node_modules/npm/node_modules/ssri/index.js:337:31)
>     at Hash.hexDigest (/usr/local/lib/node_modules/npm/node_modules/ssri/index.js:34:27)
>     at contentPath (/usr/local/lib/node_modules/npm/node_modules/cacache/lib/content/path.js:20:31)
>     at moveToDestination (/usr/local/lib/node_modules/npm/node_modules/cacache/lib/content/write.js:131:23)
>     at /usr/local/lib/node_modules/npm/node_modules/cacache/lib/content/write.js:39:7
>     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
>     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
>     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
>     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
>     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
>     at Promise._fulfill (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:638:18)
>     at /usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/nodeback.js:42:21
>     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:99:16
>     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:43:10
> 
> npm ERR! cb() never called!

I get an error when I execute `curl -L https://www.npmjs.org/install.sh | sh`
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0    51    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> 100  6255  100  6255    0     0   3353      0  0:00:01  0:00:01 --:--:-- 2036k
> tar=/bin/tar
> version:
> tar (GNU tar) 1.28
> Copyright (C) 2014 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> Written by John Gilmore and Jay Fenlason.
> install npm@latest
> fetching: https://registry.npmjs.org/npm/-/npm-5.0.3.tgz
> removed 1 package in 0.078s
> npm ERR! path ../../../tmp/npm.5004/package
> npm ERR! code ENOENT
> npm ERR! errno -2
> npm ERR! syscall symlink
> npm ERR! enoent ENOENT: no such file or directory, symlink '../../../tmp/npm.5004/package' -> '/usr/lib/node_modules/npm'
> npm ERR! enoent This is related to npm not being able to find a file.
> npm ERR! enoent 

#### How can the CLI team reproduce the problem?
Only execute update of npm `npm i -g npm`, for example.

Log file of error when I execute `npm i -g npm` :

> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/bin/nodejs', '/usr/local/bin/npm', 'i', '-g', 'npm' ]
> 2 info using npm@5.0.0
> 3 info using node@v4.2.6
> 4 silly install loadCurrentTree
> 5 silly install readGlobalPackageData
> 6 error cb() never called!
> 7 error This is an error with npm itself. Please report this error at:
> 8 error <https://github.com/npm/npm/issues>

### supporting information:

 - `npm -v` prints: 5.0.0
 - `node -v` prints: v4.2.6
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux Ubuntu
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

Thanks ! ✋

**Comment by EmrahKK** [comment]
Same problem. When try to uninstall say "npm uninstall -g react-native-cli" it throws same kind of error.

debug.log :

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/8.1.1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'uninstall',
1 verbose cli   '-g',
1 verbose cli   'react-native-cli' ]
2 info using npm@5.0.3
3 info using node@v8.1.1
4 verbose npm-session 11ec410b82761d0c
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly install loadIdealTree
8 silly install cloneCurrentTreeToIdealTree
9 silly install loadShrinkwrap
10 silly uninstall loadAllDepsIntoIdealTree
11 silly install loadAllDepsIntoIdealTree
12 error cb() never called!
13 error This is an error with npm itself. Please report this error at:
14 error <https://github.com/npm/npm/issues>

**Comment by nikoTM** [comment]
@EmrahKK  try globally installing react-native-cli and removing again.

**Comment by johnthad** [comment]
I am seeing the same issue when attempting to uninstall _anything_ global, for example `npm uninstall -g electron-prebuilt`. I am using npm 5.0.3. These libraries would have been installed with npm 4.*.

**Comment by davidenco** [comment]
My workaround was as @nikoTM suggested; run npm i -g MODULE then npm un -g MODULE

This works for me!

**Comment by aminrpg** [comment]
I am seeing the same issue when attempting to install or uninstall everything...

**Comment by AurelienC** [comment]
Many many issues about this error og `cb() never called`.

No idea about **npm** developers ? @zkat 

Thanks 😀

**Comment by z3v0k** [comment]
It's work with node lts

**Comment by AurelienC** [comment]
I have remove Node and NPM (`sudo apt remove nodejs npm`) and reinstall Node.JS V6.11.0 with apt manager.

It's appear all right now.

**Comment by iSanchezDev** [comment]
Same problem. I solved it removing my https-proxy configuration like:

`npm config delete https-proxy`
