### ISSUE TITLE
Unable to publish with "You must be logged in" error

### ISSUE THREAD

**Issue by guioconnor** [npm/npm#17231]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I receive and error when publishing org packages saying I'm not logged in, but I can publish my own (non-scoped) packages under my user.

After several successful publications of the package, it suddenly stopped working when we created a new user and added to the org and removed the user that previously published. The user I'm logged in as in the log below is owner and has read/write access to the package. (and is neither the user that was removed nor the newly created)

The problem happens simultaneously on my own dev machine and the CI environment. At a glance it seems a poorly reported permissions error but I don't know what the problem may be.

#### How can the CLI team reproduce the problem?

I'm not sure how, in my environment I can reproduce it by
1) `npm login` to my account
2) `npm publish` a personal (non-scoped) package, which is successful
3) `npm publish` my org's private package, which fails with as per the log below.

```
$ npm login
Username: guioconnor
Password:
Email: (this IS public) [~redacted~]
Logged in as guioconnor on https://registry.npmjs.org/.
```
```
$ cd [~my personal package~]
$ npm publish # personal package
+ ebg13@1.3.5
```
```
$ cd [~my org package~]
$ npm publish
npm ERR! publish Failed PUT 401
npm ERR! code E401
npm ERR! You must be logged in to publish packages : @[~myOrg~]/[~myPackage~]

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/guioconnor/.npm/_logs/2017-06-15T12_58_37_378Z-debug.log
```

I've redacted info about users/orgs/package names but otherwise a verbatim log.

### supporting information:

 - `npm -v` prints:
5.0.3 (but I have tried with different versions as well)
 - `node -v` prints:
v8.0.0 (but I have tried with different versions as well)
 - `npm config get registry` prints:
https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?:
MacOs on my local machine & Linux on CI server
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by guioconnor** [comment]
Renaming my personal package to include the org scope and `npm publish` successfully published the package under the org scope. A subsequent `npm unpublish` worked too.

Renaming the org's package to publish under a different name did not work. 

```
$ npm publish
npm ERR! publish Failed PUT 401
npm ERR! code E401
npm ERR! You must be logged in to publish packages : @[~scope~]/[~new package name~]

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/guioconnor/.npm/_logs/2017-06-15T13_27_18_548Z-debug.log
```

**Comment by tz5514** [comment]
+1, same issue.

**Comment by guioconnor** [comment]
I found a solution to the problem. In my case specifically the project based `.npmrc` file that was configured to sample the authentication token from an environment variable as below

```
//registry.npmjs.org/:_authToken=${NPM_TOKEN}
```

was overwritten by a version with an actual token that expired, I'm not sure how the replacement happened but reverting to the previous version of the file solved the problem.
