### ISSUE TITLE
NPM empties node_modules/react folder after installing redux

### ISSUE THREAD

**Issue by harishankards** [npm/npm#17230]
#### I'm opening this issue because:

  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  

#### What's going wrong?
`npm install redux` deletes the contents of the folder `node_modules/react`.

#### How can the CLI team reproduce the problem?

- Start react app using `create-react-app my-app`. 
- Run `npm start` and it works fine
- Stop the server and install redux using `npm install redux`
- Run the server again and you see the error. module not found : react

### supporting information:
![image](https://user-images.githubusercontent.com/5006693/27182447-c4ec09d0-51f8-11e7-9b40-45bb1c4ce7b2.png)

**Comment by brod** [comment]
couldn't reproduce using:
```sh
npm install react
```

**Comment by 8eecf0d2** [comment]
Couldn't reproduce with:
```bash
npm install react
npm install redux
```
sounds like a `create-react-app` issue: https://github.com/facebookincubator/create-react-app/issues

**Comment by harishankards** [comment]
@brod  what is your npm version. upgrade it to latest version. Mine is 5.0.3

**Comment by 8eecf0d2** [comment]
mine was `5.0.3`, now it's `5.0.4` and still can't reproduce.
