### ISSUE TITLE
missing script: android

### ISSUE THREAD

**Issue by acarterczyzewicz** [npm/npm#17247]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [X] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
c:\new_projects\Project>npm run android
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "android"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10

npm ERR! missing script: android
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     c:\new_projects\Project\npm-debug.log
#### How can the CLI team reproduce the problem?
npm run android

### supporting information:

 - `npm -v` prints: 3.10.10
 - `node -v` prints: v6.11.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
   - [X] None of the above
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).
   - [X] None of the above

**Comment by aleyakovle** [comment]
the same error
`npm -v` prints: 5.0.3
`node -v` prints: v6.11.0
`npm config get registry` prints: https://registry.npmjs.org/
Windows, OS X/macOS, or Linux?: Windows 10

**Comment by kenany** [comment]
Please ensure that you have a `"android"` script defined in your `package.json`. See <https://docs.npmjs.com/misc/scripts> for more information on how scripts work in `npm`.

**Comment by Runixuz** [comment]
how to install android nodejs
