### ISSUE TITLE
Error installing laravel mix

### ISSUE THREAD

**Issue by elyash14** [npm/npm#17271]
I want to install Mix in laravel . I run "npm install --no-bin-links" in my IDE terminal or in CMD but I get this error: (my laravel version is 5.4.27)

D:\wamp64\www\laravelProject>npm install --no-bin-links
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--no-bin-links"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10

npm ERR! Maximum call stack size exceeded
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\wamp64\www\laravelProject\npm-debug.log

**Comment by Djusa** [comment]
Hey, did you resolve it?
Cos I have the same problem

**Comment by elyash14** [comment]
@Djusa .Yes. I updated the NPM and everything was fine
