### ISSUE TITLE
npm error missing script: build

### ISSUE THREAD

**Issue by sjeksani** [npm/npm#17272]
Here's my package.json

{
    "homepage": "https://sjeksani.github.io/NewReact",
    "name": "reactApplication",
    "version": "1.0.0",
    "description": "",
    "main": "index.js",
    "scripts": {
        "deploy": "npm run build&&gh-pages -d build"
    },
    "keywords": [],
    "author": "",
    "license": "ISC",
    "devDependencies": {
        "babel-core": "^6.25.0",
        "babel-loader": "^7.0.0",
        "babel-preset-es2015": "^6.24.1",
        "babel-preset-react": "^6.24.1",
        "gh-pages": "^1.0.0",
        "webpack": "^2.6.1",
        "webpack-dev-server": "^2.4.5"
    },
    "dependencies": {
        "react": "^15.6.1",
        "react-dom": "^15.6.1"
    }
}

Here is the npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@3.10.10
3 info using node@v6.9.5
4 verbose stack Error: missing script: build
4 verbose stack     at run (/usr/local/lib/node_modules/npm/lib/run-script.js:151:19)
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/run-script.js:61:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:356:5
4 verbose stack     at checkBinReferences_ (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:320:45)
4 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:354:3)
4 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:124:5)
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:311:12
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
4 verbose stack     at tryToString (fs.js:455:3)
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
5 verbose cwd /Users/sharath/Desktop/NewReact
6 error Darwin 15.6.0
7 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
8 error node v6.9.5
9 error npm  v3.10.10
10 error missing script: build
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

When I run this command:
npm run deploy
It says missing script build. What do I do?

**Comment by leonadler** [comment]
```
"scripts": {
  "deploy": "npm run build&&gh-pages -d build"
},
```
`npm run deploy` will run `npm run build`, which is not in your `scripts` hash.
Whatever you want to execute, you need to add it to your package.json:
```
"scripts": {
  "deploy": "npm run build&&gh-pages -d build",
  "build": "whatever-command-you-want-npm-to-run"
},
```

**Comment by harsh07bharvada** [comment]
@leonadler I am new to all this npm and scripts. What should I write in "build": "whatever-command-you-want-npm-to-run"? 
My package.json file is as follows:

{
  "name": "ns",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "webpack-dev-server",
     "deploy": "npm run build&&gh-pages -d build"
  
  },
  "author": "",
  "license": "ISC",
   "homepage": "https://harsh07bharvada.gitlab.io/my-test-project",
  "dependencies": {
    "material-auto-rotating-carousel": "^1.4.1",
    "material-ui": "^1.0.0-alpha.21",
    "material-ui-icons": "^1.0.0-alpha.19",
    "react": "^15.6.1",
    "react-dom": "^15.6.1",
    "react-router": "^4.1.1",
    "react-router-dom": "^4.1.1",
    "react-swipeable-views": "^0.12.4",
    "typeface-roboto": "0.0.31",
    "webfontloader": "^1.6.28"
  },
  "devDependencies": {
    "babel-core": "^6.25.0",
    "babel-loader": "^7.1.1",
    "babel-preset-env": "^1.6.0",
    "babel-preset-react": "^6.24.1",
    "css-loader": "^0.28.4",
    "html-webpack-plugin": "^2.29.0",
    "style-loader": "^0.18.2",
    "webpack": "^3.2.0",
    "webpack-dev-server": "^2.5.1"
  }
 
}

Please please help

**Comment by leonadler** [comment]
npm already tells you what is wrong: 
```
4 verbose stack Error: missing script: build
```

You put `"npm run build && gh-pages -d build"` in your `deploy` script, but you need to tell npm what to do when `npm run build` is being run. Configure `build` to whatever command needs to run to build your project.

Since you are using webpack, I assume it would be `webpack --config webpack.conf.js`. With gulp, `gulp build`, with TypeScript `tsc -p tsproject.json`, and so on. **It depends on your project.**

```
"scripts": {
  "build": "webpack --config webpack.conf.js",
  "deploy": "npm run build && gh-pages -d build",
  "start": "webpack-dev-server"
},
```
