### ISSUE TITLE
Invalid or unexpected token

### ISSUE THREAD

**Issue by catsburrow** [npm/npm#17292]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I'm trying to do an install with npm, but it keeps on giving me the same error!
I tried updating npm but it gives the same error.

npm ERR! Invalid or unexpected token

npm ERR! A complete log of this run can be found in:
npm ERR!    C:\Users\Diane\Appdata\Roaming\npm-cache\_logs\2017-06-18T13_38_24_302Z-debug.log

#### How can the CLI team reproduce the problem?

I'm not too sure about how to reproduce it... I'm on Windows 8.1 and I just ran the 64-bit Node.js  installer. I've tried both the current and the LTS but both gives the same error. Here's the debug log:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Diane\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'npm@latest',
1 verbose cli   '-g' ]
2 info using npm@5.0.3
3 info using node@v8.1.2
4 verbose npm-session 292350f68f680b7a
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData error for npm@latest Invalid or unexpected token
8 verbose stack C:\Users\Diane\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\src\blob.js:1
8 verbose stack (function (exports, require, module, __filename, __dirname) {
8 verbose stack
8 verbose stack
8 verbose stack SyntaxError: Invalid or unexpected token
8 verbose stack     at createScript (vm.js:74:10)
8 verbose stack     at Object.runInThisContext (vm.js:116:10)
8 verbose stack     at Module._compile (module.js:533:28)
8 verbose stack     at Object.Module._extensions..js (module.js:580:10)
8 verbose stack     at Module.load (module.js:503:32)
8 verbose stack     at tryModuleLoad (module.js:466:12)
8 verbose stack     at Function.Module._load (module.js:458:3)
8 verbose stack     at Module.require (module.js:513:17)
8 verbose stack     at require (internal/module.js:11:18)
8 verbose stack     at Object.<anonymous> (C:\Users\Diane\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\src\body.js:11:14)
8 verbose stack     at Module._compile (module.js:569:30)
8 verbose stack     at Object.Module._extensions..js (module.js:580:10)
8 verbose stack     at Module.load (module.js:503:32)
8 verbose stack     at tryModuleLoad (module.js:466:12)
8 verbose stack     at Function.Module._load (module.js:458:3)
8 verbose stack     at Module.require (module.js:513:17)
9 verbose cwd C:\xampp\htdocs\forum\member\build
10 verbose Windows_NT 6.3.9600
11 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Diane\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "npm@latest" "-g"
12 verbose node v8.1.2
13 verbose npm  v5.0.3
14 error Invalid or unexpected token
15 verbose exit [ 1, true ]

### supporting information:

 - `npm -v` prints: 5.0.3
 - `node -v` prints: 8.1.2
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by BobMali** [comment]
Could you please provide the content of your package.json?

**Comment by catsburrow** [comment]
Ended up installing Vagrant & Homestead and that seems to have worked.
