### ISSUE TITLE
sudo npm install not working

### ISSUE THREAD

**Issue by rwomdev** [npm/npm#17302]
#### I'm opening this issue because:

  - [ ] npm is crashing.

#### What's going wrong?
npm ERR! Linux 4.4.0-77-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "vuex" "vue-material" "--save"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ECONNRESET

npm ERR! network tunneling socket could not be established, cause=connect ETIMEDOUT 74.122.238.10:8080
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     /home/samson/my-vue-project/npm-debug.log

#### How can the CLI team reproduce the problem?
sudo npm install

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a mobile wifi hotpot  to connect to the npm registry.

**Comment by kenichi-shibata** [comment]
Looks like your 8080 proxy firewall is not open. Maybe a simple network issue
