### ISSUE TITLE
 Package install failed when i use npm install

### ISSUE THREAD

**Issue by lokesingh** [npm/npm#17307]
E:\Office\Angular 2\project> ng new collect
installing ng
  create .editorconfig
  create README.md
  create src\app\app.component.css
  create src\app\app.component.html
  create src\app\app.component.spec.ts
  create src\app\app.component.ts
  create src\app\app.module.ts
  create src\assets\.gitkeep
  create src\environments\environment.prod.ts
  create src\environments\environment.ts
  create src\favicon.ico
  create src\index.html
  create src\main.ts
  create src\polyfills.ts
  create src\styles.css
  create src\test.ts
  create src\tsconfig.app.json
  create src\tsconfig.spec.json
  create src\typings.d.ts
  create .angular-cli.json
  create e2e\app.e2e-spec.ts
  create e2e\app.po.ts
  create e2e\tsconfig.e2e.json
  create .gitignore
  create karma.conf.js
  create package.json
  create protractor.conf.js
  create tsconfig.json
  create tslint.json
Successfully initialized git.
Installing packages for tooling via npm.
Unhandled rejection Error: UNKNOWN: unknown error, mkdir 'C:\Users\Loken\AppData
\Roaming\npm-cache\_cacache\content-v2\sha512\e6\78'
Unhandled rejection Error: UNKNOWN: unknown error, mkdir 'C:\Users\Loken\AppData
\Roaming\npm-cache\_cacache\content-v2\sha512\e6\84'
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Loken\AppData\Roaming\npm-cache\_logs\2017-06-19T06_02_51_
053Z-debug.log

Package install failed, see above.

**Comment by AurelienC** [comment]
Same error #17222
