### ISSUE TITLE
npm install @types/node failing

### ISSUE THREAD

**Issue by uglycoyote** [npm/npm#17328]
#### I'm opening this issue because:
  - [X] npm is doing something I don't understand.

#### What's going wrong?

Can't run the command `npm install "@types/node" --save-dev`

#### How can the CLI team reproduce the problem?

Not sure.

### supporting information:

Running Windows 10
npm version 1.4.9
node version 8.1.2
(just updated these both today)

```
npm WARN package.json string_decoder@1.0.1 string_decoder is also the name of a node core module.
npm WARN `git config --get remote.origin.url` returned wrong result (git://github.com/types/node)
npm WARN `git config --get remote.origin.url` returned wrong result (git@github.com:types/node)
npm ERR! git clone git@github.com:types/node Cloning into bare repository 'C:\Users\Mike\AppData\Roaming\npm-cache\_git-remotes\git-github-com-types-node-921b5735'...
npm ERR! git clone git@github.com:types/node Host key verification failed.
npm ERR! git clone git@github.com:types/node fatal: Could not read from remote repository.
npm ERR! git clone git@github.com:types/node
npm ERR! git clone git@github.com:types/node Please make sure you have the correct access rights
npm ERR! git clone git@github.com:types/node and the repository exists.
npm ERR! addLocal Could not install types/node
npm ERR! Error: ENOENT: no such file or directory, stat 'D:\mike\dev\webmidi\WebMidiSightReadingGame\client\types\node'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>
npm ERR! System Windows_NT 10.0.14393
npm ERR! command "D:\\program files\\nodejs\\node.exe" "C:\\ProgramData\\chocolatey\\lib\\npm\\tools\\node_modules\\npm\\bin\\npm-cli.js" "install" "@types/node" "--save-dev"
npm ERR! cwd D:\mike\dev\webmidi\WebMidiSightReadingGame\client
npm ERR! node -v v8.1.2
npm ERR! npm -v 1.4.9
npm ERR! path D:\mike\dev\webmidi\WebMidiSightReadingGame\client\types\node
npm ERR! syscall stat
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     D:\mike\dev\webmidi\WebMidiSightReadingGame\client\npm-debug.log
npm ERR! not ok code 0
```

### Things that are unclear to me in the npm error messages:

* When it says `git config --get remote.origin.url` is returning the wrong result.  What is wrong with the result?  what is it NPM expecting?
* Why is it cloning into a bare repository, and why is that an error?
* What host key failed to verify with what?
* Why can't it read from the remote repository?  What repository is it failing to read from?

**Comment by junosuarez** [comment]
hi @uglycoyote - that is an extremely old version of `npm`. Especially since you are running an up-to-date version of node, please make sure that you don't accidentally have an older version of npm on your `$PATH`.

I see that the log you provided mentions Chocolately, which may be conflicting with the newer version of npm.

**Comment by uglycoyote** [comment]
Thanks!  Yes you are right, does look like Chocolatey screwed some stuff up.  

Earlier today I needed to upgrade to latest version of Node, and according to my research Chocolatey was the easiest way to do that so I installed Chocolatey and Node, and thought that I also upgraded npm at that time according to their instructions.  

It added chocolatey\bin to my PATH environment variable, so the old version of npm that I had in chocolatey\bin was shadowing a newer version installed elsewhere.

**Comment by nateshmbhat** [comment]
Actually I was stuck with the same problem . Here's how I fixed it .

- I found that the problem for me was having an older version of npm which was causing this issue. 
- I uninstalled it using `sudo apt-get remove npm` and installed it again using `sudo apt-get install npm` .
- Then upgrade it to the latest version using `sudo npm install npm@latest -g`
