### ISSUE TITLE
Centos7 : How to update or upgrade -g modules in /usr/lib/node_modules ?

### ISSUE THREAD

**Issue by christalk** [npm/npm#17339]
I can't install the new modules' version (f.e. : express, socket.io, create-react-app...etc)
when an older version already exists on Centos  (in global directory)   /usr/lib/node_modules. 
 I don't know why.
                      environment : Centos7
                      node          v8.1.2  ok
                      npm            5.0.3  ok 
                      express       4.15.2  not the latest!
                      socket.io     2.0.1    not the latest!

_PS : the command "npm view <module> version" doens't give the installed version. But the latest one . Where does it find it ? somewhere on the Internet site ? Nor the "npm info <module> version"
npm view express version -> 4.15.3 ( No, I wish I could obtain now this new version, but the real version is still 4.15.2 on my computer. The update doesn't work))
npm view socket.io version -> 2.0.3 ( No,  wish I could obtain now this new version, but the real version is still  the older. The update doesn't work)_ 

Tests command : 
sudo npm update (OR upgrade) -> no change
sudo npm –g update (OR upgrade) -> no change 
sudo npm –g update (OR upgrade) express (OR another module name) -> no change
sudo yum update (or upgrade) -> no change for modules , but ok with node.js and npm
[Edit] 
sudo npm install -g express -> don't change the old version 

Even if I change the version number in each package.json file ( f.e. usr/lib/node_modules/express/package.json)

The only thing which "works", is to uninstall the module (but sometimes npm gives errors) and to reinstall it
Do I have to uninstall each modules in /usr/lib/node_modules to update (or upgrade it) ?

#### I'm opening this issue because:
sometime, with uninstall 
 - [ ] npm is crashing.

### supporting information:

 https://registry.npmjs.org/
Centos7

   - [X] I use a proxy to connect to the npm registry.
   - [X] I use a proxy to connect to the web.

**Comment by kenany** [comment]
When I want to update a global package, I just do:

```
npm install -g express
```

**Comment by christalk** [comment]
[Edit]  sudo npm install -g express -> don't change the version 

Thanks, but it does not work either on my Centos7 . I have added it in the commands listed above .
It works, only if I first uninstall the module, of course.
I don't know why.

**Comment by kenany** [comment]
How about (for good measure):

```
npm install -g express@latest
```
