### ISSUE TITLE
running 'npm install' get the ERROR: events.js:160 throw er; // Unhandled 'error' event ^ Error: unexpected end of file at Zlib._handle.onerror (zlib.js:370:17)

### ISSUE THREAD

**Issue by hubery3721** [npm/npm#17335]
I run 'npm install' and get the ERROR:
```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: unexpected end of file
    at Zlib._handle.onerror (zlib.js:370:17)
```
Below is the npm-debug.log

[npm-debug.log.zip](https://github.com/npm/npm/files/1087175/npm-debug.log.zip)

**Comment by hubery3721** [comment]
Can someone help this?

**Comment by kenany** [comment]
@huberyh Could you upload the debug log as plaintext to <https://gist.github.com/> and link it here, instead of zipping it up? Thanks!

**Comment by hubery3721** [comment]
@KenanY 
YES, below is the debug log link.
https://gist.github.com/huberyh/3d5c8b4fd4c149a73ec48d0df75fdfbe

**Comment by kenany** [comment]
Thanks. As the log indicates, this is just `mongodb-prebuilt`'s postinstall script failing on your system. All `npm` is doing here is letting you know about it.
