### ISSUE TITLE
npm install angular/cli ERR!

### ISSUE THREAD

**Issue by jackwgj** [npm/npm#17347]
localhost:~ wanggaojie$ sudo npm config set registry https://registry.npm.taobao.org
localhost:~ wanggaojie$ sudo npm get registry
https://registry.npm.taobao.org/
localhost:~ wanggaojie$ sudo npm install -g @ angular/cli
npm ERR! unpack Could not read data for @ ngtools/json-schema@1.1.0
npm ERR! unpack Could not read data for @ ngtools/webpack@1.4.1
npm ERR! unpack Could not read data for @ angular/cli@1.1.2
npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "@angular/cli"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10

npm ERR! Invalid name: "@ngtools/json-schema"
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by kenany** [comment]
@jackwgj Could you try running?:

``` bash
sudo npm install -g @angular/cli
```

**Comment by jackwgj** [comment]
Yes,but it's err install.The err info is on the "Issues" . The node version is 6.10.0 , and I changed the registries to "taobao.org" in China




发自网易邮箱大师
On 06/21/2017 01:47, Kenan Yildirim wrote:

@jackwgj Could you try running?:

sudo npm install -g @angular/cli

**Comment by kenany** [comment]
@jackwgj Could I see the resulting debug log file after running the command I provided? You can upload the log to <https://gist.github.com/> and link it here. (Don't attach it to an email reply, because then it doesn't show up.)

**Comment by jackwgj** [comment]
Ok But I have to upload it tomorrow. Here I am AM2:00 , I have shotdowon my Mac and ly on bed. Thank you!




发自网易邮箱大师
On 06/21/2017 01:56, Kenan Yildirim wrote:

@jackwgj Could I see the resulting debug log file after running the command I provided? You can upload the log to https://gist.github.com/ and link it here. (Don't attach it to an email reply, because then it doesn't show up.)
