### ISSUE TITLE
Please make npm install deterministic. There is absolutely no reason why yarn should fragment js tooling

### ISSUE THREAD

**Issue by nojvek** [npm/npm#17348]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?
Yarn should die. It's doing a slightly better job than npm at the cost of fragmenting js ecosystem.

https://yarnpkg.com/en/

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
Isn't this what `npm-shrinkwrap.json` and `package-lock.json` accomplish?

**Comment by jaydenseric** [comment]
npm@5 is more deterministic than Yarn.

**Comment by nojvek** [comment]
Does npm5 support caching too?

**Comment by jaydenseric** [comment]
@nojvek Yes, blog posts and articles about what's new in npm@5 are all over the internet.

**Comment by nojvek** [comment]
I feel pretty dumb. This is awesome. Thank you for educating me. Just need an npm upgrade in that case.
