### ISSUE TITLE
npm won’t run a shell script

### ISSUE THREAD

**Issue by jonnybarnes** [npm/npm#17354]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don&#39;t understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

npm isn’t running a shell script properly

#### How can the CLI team reproduce the problem?

I have a script that compresses javascript files with a globally installed instance of uglifyjs.

`sctips/uglifyjs`:

```
#!/usr/bin/env zsh

for file in ./public/assets/js/*.js
do
    echo "uglifying `basename $file`"
    uglifyjs --verbose --compress --source-map content=${file:2}.map,url=`basename $file`.map,filename=${file:2}.map,includeSources=true --output $file $file
done
```

And my my `package.json` contains the following in the scripts section:
```
"uglifyjs": "scripts/uglifyjs",
```

In my terminal manually invoking the file with `./scripts/uglifyjs` works as expected. Running `npm run uglifyjs` results in errors like so:
```
npm run uglifyjs

> jbuk-frontend@0.0.1 uglifyjs /home/jonny/git/jonnybarnes.uk
> scripts/uglifyjs

uglifying links.js
fs.js:651
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'content=public/assets/js/links.js.map,url=links.js.map,filename=public/assets/js/links.js.map,includeSources=true'
    at Object.fs.openSync (fs.js:651:18)
    at Object.fs.writeFileSync (fs.js:1300:33)
    at done (/home/jonny/git/jonnybarnes.uk/node_modules/uglify-js/bin/uglifyjs:516:20)
    at cb (/home/jonny/git/jonnybarnes.uk/node_modules/uglify-js/bin/uglifyjs:324:39)
    at /home/jonny/git/jonnybarnes.uk/node_modules/uglify-js/bin/uglifyjs:391:9
    at tryToString (fs.js:512:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:500:12)
uglifying maps.js
^C
```

### supporting information:

 - `npm -v` prints: `5.0.3`
 - `node -v` prints: `v8.1.2`
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?: Linux
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by dschissler** [comment]
I'm also having this issue with npm `5.0.3` and node `8.1.2`.

```
fs.js:651
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EACCES: permission denied, open '/opt/project_name/master/dev/node_modules/array-unique/index.js'
```

[edit] My solution was to downgrade to Node 7 package.

**Comment by jonnybarnes** [comment]
The way I‘ve fixed this is to uninstall uglify-js globally, and then install it in the project.
