### ISSUE TITLE
npm ERR! Windows_NT 6.3.9600 npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\ node_modules\\npm\\bin\\npm-cli.js" "--quiet" "install" npm ERR! node v6.11.0 npm ERR! npm  v3.10.10  npm ERR! shasum check failed for C:\Users\Rohan\AppData\Local\Temp\npm-4008-1814 2fb3\registry.npmjs.org\_40angular\animations\-\animations-4.2.3.tgz npm ERR! Expected: 686926a69d0c9c26a9bcad26cd6fbd0245bb6c1b npm ERR! Actual:   abec08ab504539d7bb8505fc7e0801188a09fe70 npm ERR! From:     https://registry.npmjs.org/@angular/animations/-/animations-4 .2.3.tgz npm ERR! npm ERR! If you need help, you may report this error at: npm ERR!     <https://github.com/npm/npm/issues>  npm ERR! Please include the following file with any support request: npm ERR!     C:\Rohan\html\njs1-app\npm-debug.log

### ISSUE THREAD

**Issue by rohandhanwani** [npm/npm#17353]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by abiduzz420** [comment]
```
npm ERR! Error: SSL Error: CERT_UNTRUSTED
npm ERR!     at ClientRequest.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\main.js:409:26)
npm ERR!     at ClientRequest.g (events.js:185:14)
npm ERR!     at ClientRequest.EventEmitter.emit (events.js:88:17)
npm ERR!     at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1445:7)
npm ERR!     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:111:23)
npm ERR!     at CleartextStream.socketOnData [as ondata] (http.js:1356:20)
npm ERR!     at CleartextStream.CryptoStream._push (tls.js:396:27)
npm ERR!     at SecurePair.cycle (tls.js:751:20)
npm ERR!     at EncryptedStream.CryptoStream.write (tls.js:131:13)
npm ERR!     at Socket.ondata (stream.js:38:26)
npm ERR!  [Error: SSL Error: CERT_UNTRUSTED]
npm ERR! You may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd D:\btw\buildtheworld
npm ERR! node -v v0.8.0
npm ERR! npm -v 1.1.32
npm ERR! message SSL Error: CERT_UNTRUSTED
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     D:\btw\buildtheworld\npm-debug.log
npm ERR! not ok code 0
```
npm -v shows 1.1.32
node -v shows v0.8.0
npm config get registry prints https://registry.npmjs.org/
I use Windows 10 OS
I don't use any proxy and my internet connection seems to be working fine without any trouble
I don't use any container mentioned above

**Comment by kenany** [comment]
@abiduzz420 FWIW, your versions of Node.js and `npm` are years old and are no longer supported 😨

EDIT: the comment I was replying to here has since been deleted 🤷‍♂️

**Comment by abiduzz420** [comment]
Yeah I made a typo in the version number :P........ Thanks for pointing out ... I have upgraded to latest version. It works fine now 👍

**Comment by kenany** [comment]
@rohandhanwani Does this error also occur with newer versions of `npm`?
