### ISSUE TITLE
npm install with "file:../x" dependency prints "y is not a child of z"

### ISSUE THREAD

**Issue by sod** [npm/npm#17359]
#### I'm opening this issue because:

  - [x] npm is producing an incorrect install.

#### What's going wrong?

`npm install` errors out with:
```log
npm ERR! /REPO/my-lib/node_modules/assert-plus is not a child of /REPO/my-app
```

#### How can the CLI team reproduce the problem?

1. git clone [https://github.com/sod/npm5-not-a-child](https://github.com/sod/npm5-not-a-child)
2. `npm install` inside my-app

see above error

[more infos in comment below ⬇](https://github.com/npm/npm/issues/17359#issuecomment-312264625)

### supporting information:

 - `npm -v` prints: 5.0.3
 - `node -v` prints: 6.11.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - macOS Sierra 10.12.5

**Comment by christensson** [comment]
+1

**Comment by punksta** [comment]
same issue

**Comment by sod** [comment]
Found no good workaround. For now I removed all dependencies from `my-lib` so npm5 doesn't flatten/reuse `my-lib` packages in every app that uses it.

**Comment by denizdogan** [comment]
I get the same error with npm 5.0.4 and Node 6.11.0

**Comment by sod** [comment]
I updated the reproduction https://github.com/sod/npm5-not-a-child so its super simple and the issue is clear now.

Just
```bash
git clone https://github.com/sod/npm5-not-a-child
cd npm5-not-a-child/my-app
npm install
```

my-lib has no dependencies at all and my-app has only ../my-lib as dependency.

This is how I got the state:
```bash
cd my-lib; npm i assert-plus
cd ../my-app; npm i ../my-lib # this creates a package-lock with the info that my-lib has assert-plus as dependency
cd ../my-lib; npm rm assert-plus
cd ../my-app; npm i # ERR assert-plus not a child of ... 
```

npm tries to remove the depedency from the symlinked "my-lib", that is still inside "my-app" package-lock.

**Comment by sod** [comment]
`npm 5.0.4` kind of fixes it. Doesn't automatically recover from the already broken package-lock.json though.

But `npm rm my-lib; npm i ../my-lib` (reinstalling symlinked dependency) gets rid of the error.

Just FYI what changed from 5.0.3 to 5.0.4: This is the diff of the my-app package-lock.json

```diff
{
  "name": "my-app",
  "version": "1.0.0",
  "lockfileVersion": 1,
  "dependencies": {
    "my-lib": {
      "version": "file:../my-lib",
      "dependencies": {
        "assert-plus": {
          "version": "1.0.0",
-          "resolved": "https://registry.npmjs.org/assert-plus/-/assert-plus-1.0.0.tgz",
-          "integrity": "sha1-8S4PPF13sLHN2RRpQuTpbB5N1SU="
+          "bundled": true
        }
      }
    }
  }
}
```
