### ISSUE TITLE
Nested file:/ module deduplicates it's dependencies causing runtime errors

### ISSUE THREAD

**Issue by sidhuko** [npm/npm#17362]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
For context, we are attempting to migrate an existing monolithic repository to use npm@5. Most functionality does work well, it sets up symlinks and runs a barebones application, the blocker for us is that the dedupe process is removing modules within nested local modules causing failures at runtime. A scenario which seems common across most monoliths.

```console
/A
 -> B
/B
 -> C
 -> D
/C
 -> D
```

If local module A depends on local module B, which has a dependency on module D and local module C, if module D was also installed into local module C the package will not be installed or be available at runtime to module C.

```console
module-a@1.0.0 /Users/james/Work/npm-problem/module-a
└─┬ module-b@1.0.0 -> /Users/james/Work/npm-problem/module-b
  ├── lodash@4.17.4
  └─┬ module-c@1.0.0
    └── lodash@4.17.4 deduped
```

The `npm ls` above structures the application with symlinks how we would expect but the dedupe process means module-c does not install a `node_modules/` folder with module D (shown as lodash). It's notable to mention the module-c is symlinked into module-b but this is not visible in the output above. I'd expect to see `module-c@1.0.0 -> /Users/james/Work/npm-problem/module-c` but this does not happen for nested local modules.

#### How can the CLI team reproduce the problem?
The problem can be reproduced using this [repository](https://github.com/sidhuko/npm5-dedupes-local-modules).

```shell
git clone git@github.com:sidhuko/npm5-dedupes-local-modules.git dedupe-issue
cd dedupe-issue/module-a
npm install
npm start
```
The output will return

```console
$ npm start

> module-a@1.0.0 start /Users/james/Work/npm-problem/module-a
> node index.js

module.js:487
    throw err;
    ^

Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/james/Work/npm-problem/module-c/index.js:1:73)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! module-a@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the module-a@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/james/.npm/_logs/2017-06-21T11_50_12_424Z-debug.log
```

Please view the README for more information, the error happens at runtime and not at installation.

### supporting information:

 - `npm -v` prints: 5.0.3
 - `node -v` prints: 8.1.2
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS
 - Network issues: N/A
 - Container: N/A

**Comment by sidhuko** [comment]
As an update to this it is possible to run as a monolith by setting before install:

`$ export NODE_PRESERVE_SYMLINKS=true`

Then using the `--preserve-symlinks` flag running the node process:

` $ node --preserve-symlinks index.js`

Note, this breaks a lot of functionality with npm such as `npm ls` which returns it is missing every package which is hoisted to top level from a local module.

**Comment by iarna** [comment]
npm@5.1 should fix this problem for you!
