### ISSUE TITLE
Node.js 8 + npm 5 install winston-mail@~0.5.0: No matching version found for moment@= 1.7.0

### ISSUE THREAD

**Issue by harishanchu** [npm/npm#17360]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
winston-mail version ~0.5.0 is not installed after the update of npm (to version 5).
#### How can the CLI team reproduce the problem?
npm install winston-mail@~0.5.0

I get an error

```
npm WARN deprecated mimelib@0.2.14: This module is deprecated
npm ERR! code ETARGET
npm ERR! notarget No matching version found for moment@= 1.7.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'emailjs'
npm ERR! notarget 

npm ERR! A complete log of this run can be found in:

```
### supporting information:

 - `npm -v` prints: 5.0.3
 - `node -v` prints: v8.0.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by zkat** [comment]
This is fixed by 8b4bb195f, which will go out with the next npm@5 release.
