### ISSUE TITLE
Error cb() never called on latest npm install

### ISSUE THREAD

**Issue by jenessawhite** [npm/npm#17368]
#### I'm opening this issue because:
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.

#### What's going wrong?
0 info it worked if it ends with ok
1 verbose cli [ '/Users/jenessawhite/.nvm/versions/node/v6.8.0/bin/node',
1 verbose cli   '/Users/jenessawhite/.nvm/versions/node/v6.8.0/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--verbose' ]
2 info using npm@5.0.3
3 info using node@v6.8.0
4 verbose config Skipping project config: /Users/jenessawhite/.npmrc. (matches userconfig)
5 verbose npm-session 0e6e8348fab596ff
6 silly install runPreinstallTopLevelLifecycles
7 silly install loadCurrentTree
8 silly install readLocalPackageData
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 http fetch GET 304 https://registry.npmjs.org/js-tokens 551ms (from cache)
14 http fetch GET 304 https://registry.npmjs.org/encoding 572ms (from cache)
15 http fetch GET 304 https://registry.npmjs.org/loose-envify 556ms (from cache)
16 http fetch GET 304 https://registry.npmjs.org/iconv-lite 561ms (from cache)
17 http fetch GET 304 https://registry.npmjs.org/query-string 559ms (from cache)
18 http fetch GET 304 https://registry.npmjs.org/object-assign 570ms (from cache)
19 http fetch GET 304 https://registry.npmjs.org/is-stream 573ms (from cache)
20 http fetch GET 304 https://registry.npmjs.org/invariant 576ms (from cache)
21 http fetch GET 304 https://registry.npmjs.org/history 583ms (from cache)
22 silly pacote tag manifest for js-tokens@latest fetched in 584ms
23 silly pacote tag manifest for encoding@latest fetched in 655ms
24 silly pacote tag manifest for loose-envify@latest fetched in 588ms
25 silly pacote tag manifest for iconv-lite@latest fetched in 592ms
26 http fetch GET 304 https://registry.npmjs.org/hoist-non-react-statics 604ms (from cache)
27 silly pacote tag manifest for query-string@latest fetched in 595ms
28 silly pacote tag manifest for object-assign@latest fetched in 606ms
29 silly pacote tag manifest for is-stream@latest fetched in 609ms
30 silly pacote tag manifest for invariant@latest fetched in 611ms
31 silly pacote tag manifest for history@latest fetched in 619ms
32 silly pacote range manifest for js-tokens@^3.0.0 fetched in 21ms
33 silly pacote tag manifest for hoist-non-react-statics@latest fetched in 635ms
34 http fetch GET 304 https://registry.npmjs.org/strict-uri-encode 119ms (from cache)
35 http fetch GET 304 https://registry.npmjs.org/resolve-pathname 97ms (from cache)
36 silly pacote tag manifest for strict-uri-encode@latest fetched in 127ms
37 http fetch GET 304 https://registry.npmjs.org/warning 128ms (from cache)
38 silly pacote range manifest for resolve-pathname@^2.0.0 fetched in 108ms
39 http fetch GET 304 https://registry.npmjs.org/value-equal 108ms (from cache)
40 silly pacote tag manifest for warning@latest fetched in 137ms
41 silly pacote range manifest for value-equal@^0.2.0 fetched in 112ms
42 error cb() never called!
43 error This is an error with npm itself. Please report this error at:
44 error <https://github.com/npm/npm/issues>

#### How can the CLI team reproduce the problem?

running npm install in new [sage theme](https://roots.io/sage/docs/theme-functionality/) set up

### supporting information:
 - `npm -v` prints: 5.0.3
 - `node -v` prints:  v6.8.0
 - OS X/macOS Sierra latest

**Comment by larssn** [comment]
There's a bunch of issues on this already

**Comment by jenessawhite** [comment]
Thank you @larssn but I'm following the instructions per the error. 
So do you have a suggestion on how to help fix?

**Comment by AurelienC** [comment]
Same error #17222

**Comment by jenessawhite** [comment]
seems to have resolved itself... because code...

**Comment by Joelwhoescalate** [comment]
how did you resolved that @jenessawhite ?

**Comment by jenessawhite** [comment]
@Joelwhoescalate literally came back the next day and it was working
