### ISSUE TITLE
Typo: isntall

### ISSUE THREAD

**Issue by anonimusprogramus** [npm/npm#17373]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?
Minor typo

#### How can the CLI team reproduce the problem?
`npm install --help`

```
npm install (with no args, in package dir)
...
...
aliases: i, isntall, add
common options: [--save-prod|--save-dev|--save-optional] [--save-exact] [--no-save]
```
It should be **install**, not **isntall**

### supporting information:

 - `npm -v` prints: `5.0.2`
 - `node -v` prints: `v6.10.3`
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?: `Arch Linux`

**Comment by kenany** [comment]
Nah, it's a common misspelling so it was made an alias of `install` for convenience.
