### ISSUE TITLE
`npm run` sugar (lose the `run` part)

### ISSUE THREAD

**Issue by jonnysamps** [npm/npm#17389]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's the feature?
As a developer I'd love it if instead of typing `npm run my-script` I could just type `npm my-script`.  It seems quite reasonable that if the command argument to `npm` is not a built-in npm command that it could look through the script entries in the `package.json` and, if found, run it.

#### What problem is the feature intended to solve?
Save keystrokes. Makes chaining scripts together more concise.

#### Is the absence of this feature blocking you or your team? If so, how?
Nope.

#### Is this feature similar to an existing feature in another tool?
Not that I know of.

#### Is this a feature you're prepared to implement, with support from the npm CLI team?
I would be happy to implement with some support.

**Comment by anko** [comment]
I'm against this.

I think it would be good to keep user scripts in their own `run` "namespace". I like the certainty that the script I'm about to run is a user thing, and not an npm built-in.

Also, what if npm needs to add more commands? They're bound to intersect with the name of a script someone is using.

Workaround:

    alias npmr='npm run'

**Comment by RillingDev** [comment]
I agree with anko.
Keeping the `run` namespace is essential for compatibility and to avoid users "overriding" npm commands which could lead to confusion.

**Comment by jonnysamps** [comment]
@anko thanks for you input. I still think its a good idea:

My intent here was to keep the `run` command around for backward compatibility and `npm` command conflicts.  So if the user needs to specify that their custom script gets run they can still use `npm run`.

@felixge 
> "overriding" npm commands

Would not be possible. In fact, to ensure that there isn't user confusion npm could give a warning when there is a script name that conflicts with a built-in command.

A final point: we already have an example of this kind of usage with `npm test`.

**Comment by AndersDJohnson** [comment]
#4189

**Comment by jonnysamps** [comment]
There is also this: https://www.npmjs.com/package/npx... so we can probably close this now.

**Comment by legodude17** [comment]
npx doesn't execute scripts. I might suggest https://www.npmjs.com/package/standalone-npm-exec (shamless self-plug). Also, try `npx -p standalone-npm-exec npm-exec`.
