### ISSUE TITLE
For Todo-app getting build error

### ISSUE THREAD

**Issue by Rakesh0587-bhairy** [npm/npm#17386]
Hi, I am Rakesh, completely new to Angularjs-2. I have a ready setup for Angular2 application in my personal system and downloaded ToDo app from Git, facing problems. Please help with it. 

Please find the below "npm-debug" file details-

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\rakesh.bhairy\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.15.11
3 info using node@v6.11.0
4 verbose stack Error: missing script: start
4 verbose stack     at run (C:\Users\rakesh.bhairy\AppData\Roaming\npm\node_modules\npm\lib\run-script.js:142:19)
4 verbose stack     at C:\Users\rakesh.bhairy\AppData\Roaming\npm\node_modules\npm\lib\run-script.js:58:5
4 verbose stack     at C:\Users\rakesh.bhairy\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:356:5
4 verbose stack     at checkBinReferences_ (C:\Users\rakesh.bhairy\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:320:45)
4 verbose stack     at final (C:\Users\rakesh.bhairy\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:354:3)
4 verbose stack     at then (C:\Users\rakesh.bhairy\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:124:5)
4 verbose stack     at C:\Users\rakesh.bhairy\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:311:12
4 verbose stack     at C:\Users\rakesh.bhairy\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
4 verbose stack     at tryToString (fs.js:456:3)
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:443:12)
5 verbose cwd D:\Project\Demo3
6 error Windows_NT 6.1.7601
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\rakesh.bhairy\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
8 error node v6.11.0
9 error npm  v2.15.11
10 error missing script: start
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

**Comment by kenany** [comment]
Hello! So, the way `npm start` works is that it looks in your current `package.json` for a defined `"start"` [script](https://docs.npmjs.com/misc/scripts), and then runs that. The error message you're seeing is trying to tell you that you have not defined a `"start"` script in your `package.json`, hence `npm start` has no idea what you want it to do.

To solve this issue, all you have to do is add a new script to your `package.json`. It might look something like this, for example:

``` json
{
  "name": "package-name",
  "version": "1.0.0",
  "description": "package description",
  "scripts": {
    "start": "node --version",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {},
  "devDependencies": {}
}
```

Note how this `package.json` has a `"start"` script that runs `node --version`. You'll definitely want to change the command to whatever is most appropriate for your project.

Let me know if you run into any further `npm` issues :)
