### ISSUE TITLE
NPM 5.x does not support installing a package as cli tool from package folder

### ISSUE THREAD

**Issue by koteisaev** [npm/npm#17398]
#### I'm opening this issue because:

  - [X] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [X] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I can not use `npm install -g` 

I get a strange error like this:
`0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\konst\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   '-g',
1 verbose cli   'install',
1 verbose cli   './self-cloud' ]
2 info using npm@5.0.2
3 info using node@v6.9.4
4 silly install loadCurrentTree
5 silly install readGlobalPackageData
6 silly pacote directory manifest for undefined@file:self-cloud fetched in 22ms
7 verbose stack TypeError: Path must be a string. Received undefined
7 verbose stack     at assertPath (path.js:7:11)
7 verbose stack     at Object.relative (path.js:539:5)
7 verbose stack     at computeVersionSpec (C:\Users\konst\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:282:27)
7 verbose stack     at Object.Installer.normalizeCurrentTree (C:\Users\konst\AppData\Roaming\npm\node_modules\npm\lib\install.js:370:69)
7 verbose stack     at Array.<anonymous> (C:\Users\konst\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
7 verbose stack     at LOOP (C:\Users\konst\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
7 verbose stack     at C:\Users\konst\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:18:7
7 verbose stack     at C:\Users\konst\AppData\Roaming\npm\node_modules\npm\lib\install.js:619:16
7 verbose stack     at C:\Users\konst\AppData\Roaming\npm\node_modules\npm\node_modules\iferr\index.js:13:50
7 verbose stack     at thenHandleErrors (C:\Users\konst\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-tree\rpt.js:235:5)
7 verbose stack     at f (C:\Users\konst\AppData\Roaming\npm\node_modules\npm\node_modules\once\once.js:25:25)
7 verbose stack     at handleComplete (C:\Users\konst\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-tree\rpt.js:22:28)
7 verbose stack     at f (C:\Users\konst\AppData\Roaming\npm\node_modules\npm\node_modules\once\once.js:25:25)
7 verbose stack     at handleComplete (C:\Users\konst\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-tree\rpt.js:22:28)
7 verbose stack     at f (C:\Users\konst\AppData\Roaming\npm\node_modules\npm\node_modules\once\once.js:25:25)
7 verbose stack     at handleComplete (C:\Users\konst\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-tree\rpt.js:22:28)
8 verbose cwd F:\Work\Aaaron Breuer\self-cloud
9 verbose Windows_NT 10.0.14393
10 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\konst\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "-g" "install" "./self-cloud"
11 verbose node v6.9.4
12 verbose npm  v5.0.2
13 error Path must be a string. Received undefined
14 verbose exit [ 1, true ]
`

#### How can the CLI team reproduce the problem?

Scenario:
1. Create a package e. g. super-clix
2. add bin command to package.json like
> "bin": {
>    "super-clix": "./super-clix.js"
>  },
3. create a js file referenced in that addition described above
4. run the `npm install -g` in the package directory

Expected behavior:
the super-clix package should be installed globally and available for use like
> super-clix --param1 --param2 --etc

Actual behavior:
the error as described above:.

### supporting information:

 - `npm -v` prints: 5.0.3
 - `node -v` prints: v6.9.4
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows 10 Pro
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by zamn** [comment]
For sanity sake, when installing a cli package locally, from within the projects working directory (where `package.json` is) I get this same issue.

I have tried:
```shell
npm install . -g
npm i -g .
cd .. && npm i ./<directory_path> -g
```

All yield `undefined` errors.

Error output on Linux (Ubuntu 16.04):
```shell
0 info it worked if it ends with ok
1 verbose cli [ '/home/adam/.nvm/versions/node/v6.10.2/bin/node',
1 verbose cli   '/home/adam/.nvm/versions/node/v6.10.2/bin/npm',
1 verbose cli   'i',
1 verbose cli   '-g',
1 verbose cli   '.' ]
2 info using npm@5.0.1
3 info using node@v6.10.2
4 silly install loadCurrentTree
5 silly install readGlobalPackageData
6 silly pacote directory manifest for undefined@file: fetched in 18ms
7 verbose stack TypeError: Path must be a string. Received undefined
7 verbose stack     at assertPath (path.js:7:11)
7 verbose stack     at Object.relative (path.js:1227:5)
7 verbose stack     at computeVersionSpec (/home/adam/.nvm/versions/node/v6.10.2/lib/node_modules/npm/lib/install/deps.js:282:27)
7 verbose stack     at Object.Installer.normalizeCurrentTree (/home/adam/.nvm/versions/node/v6.10.2/lib/node_modules/npm/lib/install.js:370:69)
7 verbose stack     at Array.<anonymous> (/home/adam/.nvm/versions/node/v6.10.2/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
7 verbose stack     at LOOP (/home/adam/.nvm/versions/node/v6.10.2/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
7 verbose stack     at /home/adam/.nvm/versions/node/v6.10.2/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
7 verbose stack     at /home/adam/.nvm/versions/node/v6.10.2/lib/node_modules/npm/lib/install.js:619:16
7 verbose stack     at /home/adam/.nvm/versions/node/v6.10.2/lib/node_modules/npm/node_modules/iferr/index.js:13:50
7 verbose stack     at thenHandleErrors (/home/adam/.nvm/versions/node/v6.10.2/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:233:5)
7 verbose stack     at f (/home/adam/.nvm/versions/node/v6.10.2/lib/node_modules/npm/node_modules/once/once.js:25:25)
7 verbose stack     at handleComplete (/home/adam/.nvm/versions/node/v6.10.2/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:22:28)
7 verbose stack     at f (/home/adam/.nvm/versions/node/v6.10.2/lib/node_modules/npm/node_modules/once/once.js:25:25)
7 verbose stack     at handleComplete (/home/adam/.nvm/versions/node/v6.10.2/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:22:28)
7 verbose stack     at f (/home/adam/.nvm/versions/node/v6.10.2/lib/node_modules/npm/node_modules/once/once.js:25:25)
7 verbose stack     at handleComplete (/home/adam/.nvm/versions/node/v6.10.2/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:22:28)
8 verbose cwd /home/adam/code/my-cli-tool
9 verbose Linux 4.4.0-67-generic
10 verbose argv "/home/adam/.nvm/versions/node/v6.10.2/bin/node" "/home/adam/.nvm/versions/node/v6.10.2/bin/npm" "i" "-g" "."
11 verbose node v6.10.2
12 verbose npm  v5.0.1
13 error Path must be a string. Received undefined
14 verbose exit [ 1, true ]
```

As the issue states, **this is happening for all 5.x releases**. I had to downgrade to 4.6.1 in order to be able to install my cli tool via `npm`. 

How could something like this gotten through testing before doing a major release?

**Comment by legodude17** [comment]
Can you provide a link to the project where this error is occurring?

**Comment by zamn** [comment]
@legodude17 I can cook up an example project tomorrow, if @konstardiy has nothing to share. The tool I'm currently trying to install is an in-house tool, so can't release the source

**Comment by koteisaev** [comment]
@legodude17 this is a private project's source, so i can't give more details.
Falling back to npm version like 4.6 (latest realase tag below 5.0) or such was single option that worked for me. 
Disabling the package-lock.json via npmrc did not helped me.
@zamN Thanks.

**Comment by koteisaev** [comment]
@legodude17 This issue reproduced even on dependecy-less package i made like this: https://github.com/konstardiy/sample-node-cli

**Comment by moar55** [comment]
Hey do you still have this issue with the latest npm ?
I tested this with npm@5.4.1 on linux Fedora 26 and had no issues. 
I tested with the repo you provided @konstardiy.

**Comment by koteisaev** [comment]
@moar55 I rolled back to an older npm version and did not tracked the issue. I will check it now.

**Comment by koteisaev** [comment]
@moar55 I updated npm to latest now and tried that `npm install -g` and it worked. Global uninstall worked too.

**Comment by moar55** [comment]
Great!
This issue should be closed then?

**Comment by koteisaev** [comment]
Yes, exactly.
