### ISSUE TITLE
Failed at the app@1.0.0 jest script 'jest --colors --verbose'.

### ISSUE THREAD

**Issue by wzup** [npm/npm#17395]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [*] Other (_see below for feature requests_):

#### What's going wrong?
```bash
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "jest"
npm ERR! node v6.3.1
npm ERR! npm  v4.0.2
npm ERR! code ELIFECYCLE
npm ERR! app@1.0.0 jest: `jest --colors --verbose`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the app@1.0.0 jest script 'jest --colors --verbose'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     jest --colors --verbose
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\user\node\app\npm-debug.log
```

#### How can the CLI team reproduce the problem?
```
$ npm i -D jest

// package.json
  "scripts": {
    "jest": "jest --colors --verbose",

// jest.config.js in app root dir
module.exports = {
    "verbose": true,
    "testMatch": [
       // '**/__tests__/**/*.(test|spec)?.js?(x)',
       '**/__tests__/?(*.)(spec|test).js?(x)',
    ]
}

// command line
$ npm run jest
```

### supporting information:

 - `npm -v` prints: 4.0.2
 - `node -v` prints: v6.3.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows 10 64bit Pro
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
What happens if you do?:

```
node node_modules/.bin/jest --colors --verbose
```
