### ISSUE TITLE
Proxy authentication does not work correctly in NPM version 5.0.3

### ISSUE THREAD

**Issue by CunhaGus** [npm/npm#17396]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [X] Other (_see below for feature requests_):

#### What's going wrong?
I am getting the proxy error below:
npm ERR! code E407
npm ERR! 407 Proxy Authentication Required ( Forefront TMG requires authorizatio
n to fulfill the request. Access to the Web Proxy filter is denied.  ): multer@l
atest

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sul1\AppData\Roaming\npm-cache\_logs\2017-06-22T22_01_24_2
06Z-debug.log

#### How can the CLI team reproduce the problem?
execute the command below behind a proxy
npm install <anypackage>

### supporting information:

 - `npm -v` prints: 5.0.3
 - `node -v` prints: v6.10.3
 - `npm config get registry` prints: http://registry.npms.org/
 - Windows, OS X/macOS, or Linux?: Windows 7
 - Network issues:
   - Geographic location where npm was run:
   - [X] I use a proxy to connect to the npm registry.
   - [X] I use a proxy to connect to the web.
   - [X] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [X] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by CunhaGus** [comment]
Log file:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\sul1\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'multer' ]
2 info using npm@5.0.1
3 info using node@v6.10.3
4 silly install loadCurrentTree
5 silly install readLocalPackageData
6 http fetch GET 407 http://registry.npms.org/multer 1526ms
7 silly fetchPackageMetaData error for multer@latest 407 Proxy Authentication Required ( Forefront TMG requires authorization to fulfill the request. Access to the Web Proxy filter is denied.  ): multer@latest
8 verbose stack Error: 407 Proxy Authentication Required ( Forefront TMG requires authorization to fulfill the request. Access to the Web Proxy filter is denied.  ): multer@latest
8 verbose stack     at fetch.then.res (C:\Users\sul1\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:36:19)
8 verbose stack     at tryCatcher (C:\Users\sul1\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
8 verbose stack     at Promise._settlePromiseFromHandler (C:\Users\sul1\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
8 verbose stack     at Promise._settlePromise (C:\Users\sul1\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
8 verbose stack     at Promise._settlePromise0 (C:\Users\sul1\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
8 verbose stack     at Promise._settlePromises (C:\Users\sul1\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
8 verbose stack     at Async._drainQueue (C:\Users\sul1\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
8 verbose stack     at Async._drainQueues (C:\Users\sul1\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
8 verbose stack     at Immediate.Async.drainQueues (C:\Users\sul1\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
8 verbose stack     at runCallback (timers.js:672:20)
8 verbose stack     at tryOnImmediate (timers.js:645:5)
8 verbose stack     at processImmediate [as _immediateCallback] (timers.js:617:5)
9 verbose cwd C:\Windows\system32
10 verbose Windows_NT 6.1.7601
11 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\sul1\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "multer"
12 verbose node v6.10.3
13 verbose npm  v5.0.1
14 error code E407
15 error 407 Proxy Authentication Required ( Forefront TMG requires authorization to fulfill the request. Access to the Web Proxy filter is denied.  ): multer@latest
16 verbose exit [ 1, true ]

**Comment by purplerune** [comment]
+1 also having the same problem!

**Log:**

```

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\MoutaL\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'nativescript-zxing',
1 verbose cli   '--save' ]
2 info using npm@5.0.3
3 info using node@v6.10.2
4 verbose npm-session 20d3187c2bf9e139
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 407 http://registry.npmjs.org/nativescript-zxing 95ms
8 silly fetchPackageMetaData error for nativescript-zxing@latest 407 Proxy Authentication Required: nativescript-zxing@latest
9 verbose stack Error: 407 Proxy Authentication Required: nativescript-zxing@latest
9 verbose stack     at fetch.then.res (C:\Users\MoutaL\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:41:19)
9 verbose stack     at tryCatcher (C:\Users\MoutaL\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
9 verbose stack     at Promise._settlePromiseFromHandler (C:\Users\MoutaL\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
9 verbose stack     at Promise._settlePromise (C:\Users\MoutaL\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
9 verbose stack     at Promise._settlePromise0 (C:\Users\MoutaL\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
9 verbose stack     at Promise._settlePromises (C:\Users\MoutaL\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
9 verbose stack     at Async._drainQueue (C:\Users\MoutaL\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
9 verbose stack     at Async._drainQueues (C:\Users\MoutaL\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
9 verbose stack     at Immediate.Async.drainQueues (C:\Users\MoutaL\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
9 verbose stack     at runCallback (timers.js:666:20)
9 verbose stack     at tryOnImmediate (timers.js:639:5)
9 verbose stack     at processImmediate [as _immediateCallback] (timers.js:611:5)
10 verbose cwd C:\Users\MoutaL\Desktop\NativeScript With TypeScript\FastCanteen
11 verbose Windows_NT 10.0.10586
12 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\MoutaL\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "nativescript-zxing" "--save"
13 verbose node v6.10.2
14 verbose npm  v5.0.3
15 error code E407
16 error 407 Proxy Authentication Required: nativescript-zxing@latest
17 verbose exit [ 1, true ]



```

**Comment by purplerune** [comment]
Found the solution:

Go to  **C:\Users\Your User\AppData\Roaming\**
And **delete the npm folder**

After deleting the npm folder
do the following command:`npm cache clear`
and then execute this command:`npm i -g npm@latest`

Let me know if it helped!

**Comment by CunhaGus** [comment]
IT WORKED!!!! I spent weeks trying to solve this issue and getting the network engineers to look into the proxy rules etc....
Thank you very much Purplerune!

**Comment by netpoetica** [comment]
On Mac OSX, I simply did `npm cache verify` - which seemed to clear some stuff - and that fixed the issue

**Comment by jilanim** [comment]
@purplerune Thanks! The following worked.
npm cache clear --force
npm i -g npm@latest

**Comment by vanmoris** [comment]
C:\Windows\System32>npm i -g npm@latest
npm ERR! code E407
npm ERR! 407 Proxy Authentication Required: npm@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dia9qb\AppData\Roaming\npm-cache\_logs\2018-07-11T15_43_37_292Z-debug.log
