### ISSUE TITLE
Mac OS X - Cannot read property 'path' of null 

### ISSUE THREAD

**Issue by toniarcuri** [npm/npm#17404]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [X ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Got the message 'Cannot read property 'path' of null' while install a packagepwd

[2017-06-23T14_13_44_184Z-debug.txt](https://github.com/npm/npm/files/1098049/2017-06-23T14_13_44_184Z-debug.txt)

### supporting information:

 - `npm -v` prints: 4.2.0
 - `node -v` prints:v7.10.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: OSX/Mac OS
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by ChrisyehGone** [comment]
same issue...need help!!!
