### ISSUE TITLE
Cannot find module 'internal/fs' in Windows 10

### ISSUE THREAD

**Issue by mchcn865** [npm/npm#17403]
#### I'm opening this issue because:

  - [ X] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Attached you will find npm-debug file
#### How can the CLI team reproduce the problem?
Please advise what is to do

### supporting information:

 - `npm -v` prints: 3.3.12
 - `node -v` prints: v8.1.0
 - `npm config get registry` prints: https://registry.nmpjs.org/
 - Windows, OS X/macOS, or Linux?: Windows 10
 - Network issues: No
[npm-debug.pdf](https://github.com/npm/npm/files/1097575/npm-debug.pdf)

   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by bragtown** [comment]
having similar issue

**Comment by solveig** [comment]
having similar issue,  but I replaced the path for npm-cli.js 

and run 

 node.exe  "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "npm@latest" "-g"

and npm -v
5.0.4  :)
