### ISSUE TITLE
npm install with package-lock.json fails to install git dependencies

### ISSUE THREAD

**Issue by hector-gomez** [npm/npm#17405]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [X] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

When `package-lock.json` is present, installing unpublished packages by using a reference to GitHub fails.

No warnings or errors are shown, but using `npm ls` it is possible to verify that such packages are marked as _invalid_ and their git dependencies not installed. Published dependencies of such packages are installed but marked as _extraneous_, as the package requiring them is marked as _invalid_.

If `package-lock.json` is removed, the install process is correct and the lockfile is (apparently) correctly generated.

#### How can the CLI team reproduce the problem?

I have created a dummy project where you can easily reproduce this error: https://github.com/hector-gomez/npm-test-project

The project has a git dependency on a dummy package (A) that also has a git dependency on another dummy package (B).

##### Steps to reproduce
The readme file in that repo provides more detailed information, I will keep it short here:

```
$ git clone https://github.com/hector-gomez/npm-test-project.git
$ cd npm-test-project
$ npm install --no-save
$ node src
```

Execution fails because package A was downloaded but considered invalid and therefore its dependency, package B, was not installed. Using `npm ls` to check the dependency you can verify that it is marked as _invalid_:

```
$ npm ls npm-test-package-a
```

Removing the lockfile and `node_modules` and running the installation again results in a correct installation:

```
$ rm package-lock.json
$ rm -rf node_modules
$ npm install
$ node src
```

That can be verified using `npm ls`:

```
$ npm ls npm-test-package-a npm-test-package-b
```

Note that this problem can go unnoticed if the first-level git dependency only depends on published packages. They will be marked as _invalid_, and future commands like `npm prune` or another install can have unwanted consequences, but since the first-level dependency was actually downloaded the package is available. It's when this _invalid_ git package depends on another git package that it will become apparent.

Probably deserving its own bug report: npm should display an error or warning informing that it has marked dependencies as invalid.

### supporting information:

 - `npm -v` prints: 5.0.3
 - `node -v` prints: v6.10.3
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by benwiley4000** [comment]
Confirmed, npm 5.0.3.

For what it's worth, the workaround (without deleting package-lock.json) is to explicitly install the needed dependencies from the command line:

```bash
npm install --save https://github.com/user/repo.git#tag
```

Also +1 for emitting an error when the package is "invalid"! I wasn't able to detect the problem until I ran my build script and happened to recognize the error I got from the published version of my dependency.

**Comment by hector-gomez** [comment]
@benwiley4000 The problem with that workaround is that you end up coupling the project/app to the dependencies of its dependencies.

Those are a lot of confusing words... in my example if the project in addition to "Package A" has to add "Package B" to its `package.json` then it becomes coupled and there are many reasons why you don't want do do that. So it works, but I wouldn't recommend it.

**Comment by benwiley4000** [comment]
Right - my workaround is only a workaround if all your git dependencies are top-level.

That said, probably best to hold off on publishing the latest version of my module until npm fixes this. It's kind of serious.

**Comment by hector-gomez** [comment]
Agreed. I'm surprised they didn't catch this, probably because no error is emitted and therefore it isn't apparent.

**Comment by shawnmcknight** [comment]
Perhaps I'm being obtuse, but it took me a bit of reading between the lines to determine that the problem being reported here is an issue with "installing a git dependency which in turn has a git dependency".  I'm having the same problem which is why I discovered this issue log, but it wasn't immediately apparent to me from the issue title and "What's going wrong?" section.  The reproduction section mentions it, but I didn't pick up on that being the explicit issue.  It might be worthwhile to clarify the issue, but as I said, I might just be obtuse.

**Comment by benwiley4000** [comment]
@shawnmcknight I think the bottom line is that git dependencies of any kind will fail to update in package-lock.json. The distinction being made in this ticket was a dependency with its own git dependency will actually reveal an error, whereas a package with a git dependency that doesn't have its own git dependencies will fail to update, but won't let you know anything went wrong.

@hector-gomez in the case where an error is revealed, does it matter if the dependency with its own git dependency is, itself, a git dependency?

**Comment by shawnmcknight** [comment]
@benwiley4000 If the issue is really about using git dependencies period, then I suspect there might be some more at play here.  I have been using git (and the new prepare logic) for dependencies since npm5 was released without any noticeable problems.  It wasn't until I tried to use a git dependency which in turn had a git dependency that I ran into problems.

With that said, as I retest some scenarios, I think there might be varying degrees of problems here.  The "git dependency with a git dependency" issue, which I'm having, prevents the application from functioning entirely as the lowest level dependency doesn't even get installed.  When I `npm install` a library with only one level of git dependency and `package-lock.json` is present, it installs properly for me, but `npm ls` indicates an error state.  I hadn't noticed that until I read this thread because it wasn't actually causing any ill effects within my application.  This is in contrast to the multiple level git dependencies which is actually causing application errors.

**Comment by benwiley4000** [comment]
@shawnmcknight I see. The problem in my case was that I had previously installed the dependency from npm, switched to a fork I have on GitHub, and package-lock.json ignored the change. So after wiping my node_modules, yes, the dependency still installed, but it installed the version already in package-lock.json, and not the git dependency I had specified in my package.json. Unclear why.

**Comment by hector-gomez** [comment]
@shawnmcknight you described it right, installing git dependencies _seems to work fine_ but it actually (and silently) results in those dependencies marked as invalid. And it isn't until that _invalid_ dependency has another git dependency that this problem becomes apparent.

@benwiley4000 in my experience, if a git dependency depends on published npm modules those will be installed, but marked as _extraneous_ because the (git) module that requires them was marked as _invalid_. Among other potential side effects, running `npm prune` will delete them.

To clarify, all of this is caused by the presence of `package-lock.json`, without it everything is installed correctly.

**Comment by benwiley4000** [comment]
Probably related to #17400.

**Comment by hector-gomez** [comment]
Probably related to #16839 as well

**Comment by hector-gomez** [comment]
The freshly released npm 5.1.0 seems to fix the issue. It updates `package-lock.json` correctly and produces complete installs.

@benwiley4000, @shawnmcknight could you confirm if 5.1.0 fixes the issue in your scenarios as well?

**Comment by null4bl3** [comment]
On a project without a package-lock.json both npm 5.0.3 and 5.1.0 actually removes packages from my node_modules folder when installing a module, while creating a package-lock.json file that holds no mentions of the node modules now missing from the node_modules folder.

`npm -v 
5.1.0`
`npm install loopback-component-explorer`

After the npm install is done, no less than 84 modules are missing from the node_modules folder.

> $ diff -U 0 stage2.txt stage1.txt | grep -v ^@ | wc -l
> 84

Where the stage*.txt files contains directory names of the modules that node_modules contain before and after.

Running a npm install does NOT reinstall the missing modules. Something seems really broken here. 

As i am working on this in a stage environment, i have reverted to node version 7.10.0 and npm 4.2.0, and in my case has not removed any package when using npm.

**Comment by shawnmcknight** [comment]
@hector-gomez It appears to me that the install is correct now with 5.1.0 when I use git dependencies (and git dependencies which themselves have git dependencies).  The install tree confuses me a bit, but I have to admit I don't really understand when npm installs things in the parent's node_modules folder vs. a child module's node_modules folder.  Either way, the install appears to be functioning properly now, which is good news.

**Comment by hector-gomez** [comment]
@null4bl3 your scenario may be slightly different than the one described here. If npm 5.1.0 didn't fix your issue I suggest opening a new but report for it. Also, if you want to prevent npm 5 from automatically creating a lock file you can create an `.npmrc` file with this:

```
package-lock=false
```

It will also ignore the lock file when installing, if it exists.

**Comment by hector-gomez** [comment]
Closing this issue because npm 5.1.0 fixes the concrete scenario described here.

**Comment by benwiley4000** [comment]
Unfortunately I've tried this a couple times and npm 5.1.0 didn't solve the issue I described. 😢

**Comment by hector-gomez** [comment]
@benwiley4000 they may not have covered some edge cases, as it usually happens.

Unless the scenario is the same as described here, I'd suggest to open a separate bug report with steps to reproduce (and link it here for reference 🙂 ). Since this specific scenario has been fixed it would be misleading if I reopen it.

**Comment by hector-gomez** [comment]
@benwiley4000 just in case, double-check your npm version. Annoyingly enough, I suspect upgrading node reinstalls the version of npm that comes with it.

I use `npm@6` via Homebrew and recently upgraded it. Afterwards I found npm (which was 5.2.0) to be back to 5.0.3, my guess is that upgrading node caused it.
