### ISSUE TITLE
npm crashing on installing certain packages.  Windows

### ISSUE THREAD

**Issue by Niknakflak** [npm/npm#17414]
Disregard, I found the problem and it doesn't seem to be with npm

#### I'm opening this issue because:

  - [X] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I'm trying to install a regular package, truffle.  Sometime during installation, npm gives up and causes a 128 error.  
4940 error exited with error code: 128

I think it's the same problem as? https://github.com/npm/npm/issues/16980
But I'm not sure and if it is, ugh, this bug follows me everywhere

#### How can the CLI team reproduce the problem?

1. Have the latest node and npm, node 8.1.2, npm 5.0.3
2. npm -g install truffle

gist: https://gist.github.com/Niknakflak/9176dc14295150bc5c4b084490a353d6

### supporting information:

 - `npm -v` prints: 5.0.3
 - `node -v` prints: 8.1.2
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?:  Windows
 - Network issues:
   - Geographic location where npm was run: AZ, usa
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by amiturgman** [comment]
@Niknakflak  can you share what was the problem and how you fixed it? I'm having the exact same issue. Thanks!

**Comment by alexeyeryshev** [comment]
Having the same issue on **Linux with node 8.1.2, npm 5.0.3** when trying to install dependency from private repository.

```
info it worked if it ends with ok
1 verbose cli [ '/home/***/app/node/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'i',
1 verbose cli   'git+https://github.com/****/***.git' ]
2 info using npm@5.0.3
3 info using node@v8.1.2
4 verbose npm-session 6fdf042df3ee7f08
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData error for git+https://github.com/****/***.git exited with error code: 128
8 verbose stack Error: exited with error code: 128
8 verbose stack     at ChildProcess.onexit (/home/*****/app/node/lib/node_modules/npm/node_modules/mississippi/node_modules/end-of-stream/index.js:39:36)
8 verbose stack     at emitTwo (events.js:125:13)
8 verbose stack     at ChildProcess.emit (events.js:213:7)
8 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
9 verbose cwd /home/****10 verbose Linux 4.10.0-22-generic
11 verbose argv "/home/***/app/node/bin/node" "/usr/bin/npm" "i" "git+https://github.com/****/***.git"
12 verbose node v8.1.2
13 verbose npm  v5.0.3
14 error exited with error code: 128
15 verbose exit [ 1, true ]
```

I am only have rights to pull from this repository.
Is this issue solved ?
