### ISSUE TITLE
Normalize timestamps in `npm pack` tarballs

### ISSUE THREAD

**Issue by strugee** [npm/npm#17412]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### Supporting information:

 - `npm -v` prints: 5.0.3
 - `node -v` prints: 8.1.2

#### What's the feature?

Embed normalized timestamps (e.g. `0` or something) or better, no timestamps in tar files that `npm pack` generates.

#### What problem is the feature intended to solve?

This allows packages to be built such that they are bit-for-bit identical to previous builds of that package. This is called reproducible builds and has a lot of useful security properties: notably, you can reproduce the build yourself and get a stronger guarantee that the "binary" (package) you downloaded actually corresponds to the source code provided by upstream. More info (and better explanations) at https://reproducible-builds.org/.

#### Is the absence of this feature blocking you or your team? If so, how?

No.

#### Is this feature similar to an existing feature in another tool?

Debian has been pushing changes like this into lots of other upstream toolchains.

#### Is this a feature you're prepared to implement, with support from the npm CLI team?

Seems pretty trivial, so sure.

**Comment by charmander** [comment]
Looks like this is fixed in 114d518c75732c42acbef3acab36ba1d0fd724e2 and included in npm 5.6.0. Thanks, @zkat!
