### ISSUE TITLE
Error Installing github.com/trumank/scratch-api

### ISSUE THREAD

**Issue by goosesima** [npm/npm#17417]
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "scratch-api"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ENOSELF

npm ERR! Refusing to install scratch-api as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Серафим\Desktop\scratch-api-master\npm-debug.log

**Comment by kenany** [comment]
Make sure the `"name"` property in your `package.json` is not set to `"scratch-api"`. Make it something more unique.
