### ISSUE TITLE
bignumber.js.git - not accessible

### ISSUE THREAD

**Issue by rahul70392** [npm/npm#17413]
npm ERR! git clone --template=/home/rahul/.npm/_git-remotes/_templates --mirror https://github.com/debris/bignumber.js.git /home/rahul/.npm/_git-remotes/git-https-github-com-debris-bignumber-js-git-94d7146671b9719e00a09c29b01a691bc85048c2-df3f1ce1: Cloning into bare repository '/home/rahul/.npm/_git-remotes/git-https-github-com-debris-bignumber-js-git-94d7146671b9719e00a09c29b01a691bc85048c2-df3f1ce1'...
npm ERR! git clone --template=/home/rahul/.npm/_git-remotes/_templates --mirror https://github.com/debris/bignumber.js.git /home/rahul/.npm/_git-remotes/git-https-github-com-debris-bignumber-js-git-94d7146671b9719e00a09c29b01a691bc85048c2-df3f1ce1: remote: Invalid username or password.
npm ERR! git clone --template=/home/rahul/.npm/_git-remotes/_templates --mirror https://github.com/debris/bignumber.js.git /home/rahul/.npm/_git-remotes/git-https-github-com-debris-bignumber-js-git-94d7146671b9719e00a09c29b01a691bc85048c2-df3f1ce1: fatal: Authentication failed for 'https://github.com/debris/bignumber.js.git/'
npm ERR! Linux 4.10.0-24-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "web3"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code 128

npm ERR! Command failed: git clone --template=/home/rahul/.npm/_git-remotes/_templates --mirror https://github.com/debris/bignumber.js.git /home/rahul/.npm/_git-remotes/git-https-github-com-debris-bignumber-js-git-94d7146671b9719e00a09c29b01a691bc85048c2-df3f1ce1
npm ERR! Cloning into bare repository '/home/rahul/.npm/_git-remotes/git-https-github-com-debris-bignumber-js-git-94d7146671b9719e00a09c29b01a691bc85048c2-df3f1ce1'...
npm ERR! remote: Invalid username or password.
npm ERR! fatal: Authentication failed for 'https://github.com/debris/bignumber.js.git/'
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/rahul/.npm/_logs/2017-06-23T23_12_55_470Z-debug.log
rahul@rahul-dell:~/Desktop/Projects/node-truffle$ ^C

**Comment by tsouza** [comment]
I am also with this problem when trying to install truffle framework

**Comment by apackin** [comment]
Just started getting this today too - Looks similar to https://github.com/ethereum/web3.js/issues/470

Getting a 404 when I try to visit https://github.com/debris/bignumber.js <- Did debris decide to make this repo private or something?

**Comment by doppio** [comment]
Same here. :( I guess the repo must have been removed or made private today.

**Comment by satyamakgec** [comment]
Same here. this problem comes to me also when installing ethereumjs-testrpc
What is the solution?

**Comment by cochoa0x1** [comment]
same problem, trying to install ethereumjs-testrpc

**Comment by pindaroso** [comment]
Bump.

**Comment by ammarqqqq** [comment]
what is  the update  on resolving this.  if not  any work around?

**Comment by netr** [comment]
having the same problem trying to setup a web3 npm install

i was able to fix the testrpc installs by using:
`npm install -g ethereumjs-testrpc@beta`

Yet, i'm trying to work with web3 and it's giving me errors when I try to npm install.

**Comment by mtchllbrrn** [comment]
Installing from the beta tag works for me as well, nice workaround @netr 

fwiw, I'm not having any issues with web3.

**Comment by DhaneshKothari** [comment]
Same issue while trying to install truffle. What is the solution?

Thanks

**Comment by akaranth** [comment]
npm install -g truffle@beta worked for me

**Comment by MathieuGilbert** [comment]
`npm install -g truffle@beta` from here https://github.com/trufflesuite/truffle/issues/454#issuecomment-310840272 too

**Comment by DhaneshKothari** [comment]
works with npm install -g truffle@beta as suggested by @akaranth and @MathieuGilbert.

Thanks

**Comment by albpal** [comment]
Same here:

$ git clone https://github.com/ethereumjs/testrpc.git && cd testrpc
$ docker build -t ethereumjs/testrpc .

> .....
> .....
> Removing intermediate container 7189171a0a9d
> Step 5 : RUN npm install
>  ---> Running in 8b961106a4a4
> npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror https://github.com/debris/bignumber.js.git /root/.npm/_git-remotes/git-https-github-com-debris-bignumber-js-git-master-df3f1ce1: Cloning into bare repository '/root/.npm/_git-remotes/git-https-github-com-debris-bignumber-js-git-master-df3f1ce1'...
> npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror https://github.com/debris/bignumber.js.git /root/.npm/_git-remotes/git-https-github-com-debris-bignumber-js-git-master-df3f1ce1: remote: Invalid username or password.
> npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror https://github.com/debris/bignumber.js.git /root/.npm/_git-remotes/git-https-github-com-debris-bignumber-js-git-master-df3f1ce1: fatal: Authentication failed for 'https://github.com/debris/bignumber.js.git/'
> npm ERR! Linux 3.10.0-514.21.2.el7.x86_64
> npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
> npm ERR! node v6.9.2
> npm ERR! npm  v3.10.10
> npm ERR! code 128
> 
> npm ERR! Command failed: git clone --template=/root/.npm/_git-remotes/_templates --mirror https://github.com/debris/bignumber.js.git /root/.npm/_git-remotes/git-https-github-com-debris-bignumber-js-git-master-df3f1ce1
> npm ERR! Cloning into bare repository '/root/.npm/_git-remotes/git-https-github-com-debris-bignumber-js-git-master-df3f1ce1'...
> npm ERR! remote: Invalid username or password.
> npm ERR! fatal: Authentication failed for 'https://github.com/debris/bignumber.js.git/'
> npm ERR! 
> npm ERR! 
> npm ERR! If you need help, you may report this error at:
> npm ERR!     <https://github.com/npm/npm/issues>
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /src/npm-debug.log
> The command '/bin/sh -c npm install' returned a non-zero code: 1
