### ISSUE TITLE
npm install connect issue 

### ISSUE THREAD

**Issue by simranpal-kohli** [npm/npm#17426]
I am new to node.js. I have been undergoing Angular.js Pro--Adam Freeman 
Book Reference: www.apress.com

As per the installation step:
--I need to setup the web server for angular.js application using nodejs.
Accordingly i installed node.js version 6.11.0 in the path: C:\Program Files\nodejs
--next step is to install connect module of nodejs using the command npm install connect.
I am getting the below error message when doing so.

![image](https://user-images.githubusercontent.com/26364776/27515233-62f03956-59bc-11e7-85c8-b817a269f63e.png)

Can please anybody help with this.

**Comment by kenany** [comment]
Don't worry too much; those are just warnings and the installation was nevertheless successful.
