### ISSUE TITLE
npm init should not default to version 1.0.0 for a new package

### ISSUE THREAD

**Issue by ORESoftware** [npm/npm#17423]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

For newbies it would really help if "npm init" did not default projects to version 1.0.0.

According to semver, 1.0.0 would be your first official production release.

http://semver.org/

Defaulting projects to 1.0.0 so that when npm projects are first published to NPM with that version seems like a big mistake, LOL.

**Comment by kenany** [comment]
ref. https://github.com/npm/init-package-json/issues/35#issuecomment-91679692

**Comment by mcclowes** [comment]
@KenanY this is intended and going to remain like this according to other related issues, correct? Can this be closed?

**Comment by kenany** [comment]
@mcclowes Yeah I think you are right. Ref. https://github.com/npm/init-package-json/pull/75 as well.
