### ISSUE TITLE
`npm i app.json [-g]` fails when `app.json` exists in the current directory

### ISSUE THREAD

**Issue by claudiopro** [npm/npm#17420]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
When running `npm i app.json -g` to install [the app.json module](https://www.npmjs.com/package/app.json) from a directory that contains a file named `app.json`, npm fails.

I wonder if this is expected behavior, as nothing prevents users from registering modules with a name conflicting with filenames.

Requesting the install of an explicit module version e.g. `npm i app.json@1.3.0 -g` doesn't trigger the issue.

#### How can the CLI team reproduce the problem?

```
$ touch app.json
$ npm i app.json [-g]
```

Note that using an explicit module version doesn't trigger the issue

```
$ touch app.json
$ npm i app.json@1.3.0 [-g]
```

Gist of npm-debug.log
https://gist.github.com/claudiopro/3529f543df192d070a24a423e4449a65

### supporting information:

 - `npm -v` prints: 4.1.2
 - `node -v` prints: v7.7.2
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: OS X
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
See https://github.com/npm/npm/issues/12455#issuecomment-214439949 for why this behavior is unlikely to change.

**Comment by claudiopro** [comment]
Thanks for the explanation @KenanY! So `npm i app.json@latest` should ensure npm considers the argument a package to install from the registry and not a local JSON file to scan for `dependencies`? I must admit I was not familiar with the target JSON file form of npm and I'll re-read the docs to make sure I'm not mistaken next time.
