### ISSUE TITLE
npm install zeppelin-solidity exited with error code: 128

### ISSUE THREAD

**Issue by ilyadruzh** [npm/npm#17425]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
npm install npm install zeppelin-solidity is producing npm ERR! exited with error code: 128. 

#### How can the CLI team reproduce the problem?

**Command:** npm install zeppelin-solidity

Excerpt from npm-debug.log:

> 307 silly resolveWithNewModule crypto-js@3.1.8 checking installable status
> 308 silly pacote range manifest for xhr2@* fetched in 30ms
> 309 silly resolveWithNewModule xhr2@0.1.4 checking installable status
> 310 silly pacote range manifest for xmlhttprequest@* fetched in 31ms
> 311 silly resolveWithNewModule xmlhttprequest@1.8.0 checking installable status
> 312 silly fetchPackageMetaData error for bignumber.js@git+https://github.com/debris/bignumber.js.git#94d7146671b9719e00a09c29b01a691bc85048c2 exited with error code: 128
> 313 verbose stack Error: exited with error code: 128
> 313 verbose stack     at ChildProcess.onexit (/usr/lib/node_modules/npm/node_modules/mississippi/node_modules/end-of-stream/index.js:39:36)
> 313 verbose stack     at emitTwo (events.js:125:13)
> 313 verbose stack     at ChildProcess.emit (events.js:213:7)
> 313 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
> 314 verbose cwd /home/ilyadruzhinin/myproject
> 315 verbose Linux 4.8.0-36-generic
> 316 verbose argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "zeppelin-solidity"
> 317 verbose node v8.1.2
> 318 verbose npm  v5.0.3
> 319 error exited with error code: 128
> 320 verbose exit [ 1, true ]
> 

### supporting information:

 - `npm -v` prints: 5.0.3
 - `node -v` prints: 8.1.2
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Ubuntu

**Comment by al1p** [comment]
+1 
Hello, exact same issue on macOS 10.12.5: 
➜  npm -v : 5.0.3
➜  node -v : v8.1.2
➜  npm config get registry : https://registry.npmjs.org/

**Comment by frangio** [comment]
This is because of ethereum/web3.js#904. Can you check again? It seems they fixed it by now.

**Comment by al1p** [comment]
works for me now ! Thanks.

**Comment by ilyadruzh** [comment]
Yes
