### ISSUE TITLE
Error: cb() never called

### ISSUE THREAD

**Issue by ssj4maiko** [npm/npm#17433]
Was trying to run an example on ionic via vagrant / ionic-box, updated old stuff and got this error, this part worked before updating, updated java, npm and everything I could find because other stuff wasn't working, so I'm unsure if it could be just Java or maybe just a recent version:

----------------------------------------

`npm ERR! cb() never called!`

`npm ERR! This is an error with npm itself. Please report this error at:`
`npm ERR!     <https://github.com/npm/npm/issues>`

`npm ERR! A complete log of this run can be found in:`
`npm ERR!     /home/vagrant/.npm/_logs/2017-06-26T04_33_26_967Z-debug.log`
`vagrant@ionic-android:~/TestApp$ sudo npm install`

----------------------------------------

This is the content of the debug file:
`0 info it worked if it ends with ok`
`1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'install' ]`
`2 info using npm@5.0.0`
`3 info using node@v8.0.0`
`4 silly install runPreinstallTopLevelLifecycles`
`5 silly preinstall TestApp@0.0.1`
`6 info lifecycle TestApp@0.0.1~preinstall: TestApp@0.0.1`
`7 silly lifecycle TestApp@0.0.1~preinstall: no script for preinstall, continuing`
`8 silly install loadCurrentTree`
`9 silly install readLocalPackageData`
`10 silly install loadIdealTree`
`11 silly install cloneCurrentTreeToIdealTree`
`12 silly install loadShrinkwrap`
`13 silly install loadAllDepsIntoIdealTree`
`14 error cb() never called!`
`15 error This is an error with npm itself. Please report this error at:`
`16 error <https://github.com/npm/npm/issues>`

**Comment by ssj4maiko** [comment]
As an update, I'm getting the same error by trying to update npm itself:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'npm@latest',
1 verbose cli   '-g' ]
2 info using npm@5.0.0
3 info using node@v8.0.0
4 silly install loadCurrentTree
5 silly install readGlobalPackageData
6 error cb() never called!
7 error This is an error with npm itself. Please report this error at:
8 error <https://github.com/npm/npm/issues>

tried reinstalling and deleted my .npm folder to reset it, though I'm not sure if I did the right way

**Comment by dehghanimeh** [comment]
my npm ver=5.0.4

i get this error when using this command

-----------------------------------

 $ cordova plugin add https://github.com/onsip/onsip-cordova.git


after few minutes i get


Error: Failed to fetch plugin https://github.com/onsip/onsip-cordova.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: npm: Command failed with exit code 1 Error output:
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mehdi/.npm/_logs/2017-06-28T14_53_50_866Z-debug.log


log content 
---------------------------------------------------
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'https://github.com/onsip/onsip-cordova.git',
1 verbose cli   '--save' ]
2 info using npm@5.0.4
3 info using node@v8.1.2
4 verbose npm-session 6d941c6985a79d52
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 error cb() never called!
8 error This is an error with npm itself. Please report this error at:
9 error <https://github.com/npm/npm/issues>

**Comment by SWBennett06** [comment]
Receiving the same. Nothing to add, as the log appears absolutely fine until it throws the error. Running npm v5.0.4 on Windows 10.

**Comment by herocku** [comment]
I got the same problem too, here is my log


0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/bin/npm', 'install' ]
2 info using npm@5.0.4
3 info using node@v8.0.0
4 verbose npm-session f8460ad829247e7b
5 silly install runPreinstallTopLevelLifecycles
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 silly install loadIdealTree
9 silly install cloneCurrentTreeToIdealTree
10 silly install loadShrinkwrap
11 silly install loadAllDepsIntoIdealTree
12 http fetch GET 200 https://registry.npmjs.org/babel-runtime 126ms (from cache)
13 http fetch GET 200 https://registry.npmjs.org/core-js 112ms (from cache)
14 http fetch GET 200 https://registry.npmjs.org/regenerator-runtime 128ms (from cache)
15 silly pacote tag manifest for babel-runtime@latest fetched in 230ms
16 silly pacote tag manifest for core-js@latest fetched in 149ms
17 silly pacote tag manifest for regenerator-runtime@latest fetched in 149ms
18 error cb() never called!
19 error This is an error with npm itself. Please report this error at:
20 error <https://github.com/npm/npm/issues>
~

**Comment by tobbtechnologies** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'i' ]
2 info using npm@5.5.1
3 info using node@v9.2.0
4 verbose npm-session fd2ee6a40ac41be7
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall myapps@0.0.1
7 info lifecycle myapps@0.0.1~preinstall: myapps@0.0.1
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 silly install loadShrinkwrap
13 silly install loadAllDepsIntoIdealTree
14 error cb() never called!
15 error This is an error with npm itself. Please report this error at:
16 error <https://github.com/npm/npm/issues>

I have asked to report this error here please help
