### ISSUE TITLE
Error during npm installation

### ISSUE THREAD

**Issue by DhruveshPanchal** [npm/npm#17434]
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program
Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! shasum check failed for
C:\Users\XYZ\AppData\Local\Temp\npm-7176-72eeadca\registry.npmjs.org\concurrently\-\concurrently-3.5.0.tgz
npm ERR! Expected: 8cf1b7707a6916a78a4ff5b77bb04dec54b379b2
npm ERR! Actual:   2f639853cc27f7146f4b636451201ada53cc41cb
npm ERR! From:
https://registry.npmjs.org/concurrently/-/concurrently-3.5.0.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by watilde** [comment]
The error log says you got a wrong cache file somehow.

Could you check the troubleshooting and try the solution?
+ https://github.com/npm/npm/blob/latest/TROUBLESHOOTING.md#shasum-check-fails
