### ISSUE TITLE
Missing Script

### ISSUE THREAD

**Issue by DominikPhua** [npm/npm#17437]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [✓] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

It prints the following error:

dominic@dominic-PC:~/Code/google-shopping-conditionals-loops$ npm start
npm ERR! Linux 4.8.0-56-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2

npm ERR! missing script: start
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:

npm ERR!     /home/dominic/Code/google-shopping-conditionals-loops/npm-debug.log
#### How can the CLI team reproduce the problem?

I'm a student at a bootcamp and I self-installed Ubuntu on my desktop, so I might have missed out some installation steps. So, I'm not sure how the CLI team can reproduce the problem if it's the case of missing out some installation.

I'm just trying to run a javascript file that plucks out information from a JSON file.

### supporting information:

 - `npm -v` prints: 3.5.2
 - `node -v` prints: v4.2.6
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
Hello! So, the way `npm start` works is that it looks in your current `package.json` for a defined `"start"` [script](https://docs.npmjs.com/misc/scripts), and then runs that. The error message you're seeing is trying to tell you that you have not defined a `"start"` script in your `package.json`, hence `npm start` has no idea what you want it to do.

To solve this issue, all you have to do is add a new script to your `package.json`. It might look something like this, for example:

``` json
{
  "name": "package-name",
  "version": "1.0.0",
  "description": "package description",
  "scripts": {
    "start": "node --version",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {},
  "devDependencies": {}
}
```

Note how this `package.json` has a `"start"` script that runs `node --version`. You'll definitely want to change the command to whatever is most appropriate for your project.

Let me know if you run into any further `npm` issues :)

**Comment by DominikPhua** [comment]
Hi KenanY,

Just wanted to leave an update.

I'm not too sure what happened but the package.json already had a start script.

I reinstalled all the packages and it eventually turned out fine. Not sure how it worked, but yeap just letting you know.

Thank you!

Dominic
