### ISSUE TITLE
npm install generates bunch of cmd and shell files in the root directory

### ISSUE THREAD

**Issue by asipahio** [npm/npm#17445]
#### I'm opening this issue because:

  - [ x ] npm is doing something I don't understand.

#### What's going wrong?
"npm install" creates bunch of cmd files in the root directory of my solution.  I have attached a copy of some of the files. 

#### How can the CLI team reproduce the problem?
There is no error when the command runs. It just creates these files in the root and I am not sure why.

### supporting information:

 - `npm -v` prints: 4.2.0
 - `node -v` prints: 7.9.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows 7
 - Network issues:
   - None

![npm install error](https://user-images.githubusercontent.com/1537925/27554551-c2ba3556-5a7c-11e7-8863-8c70074bd637.PNG)

**Comment by Lionellionelel** [comment]
I have the same issue here :( 
Create Project -> add project to git --> clone project to another computer --> run NPM INSTALL on new computer
