### ISSUE TITLE
Need help for unpublish

### ISSUE THREAD

**Issue by ghost** [npm/npm#17467]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?

i'm not able to unpublish a pair of packages that i own, these packages are deprecated and not working
**https://registry.npmjs.org/createjs-elements/-rev/27-d51bc35b62e5216a5dbc7f4745bfeb62**
and
**https://registry.npmjs.org/elements-js/-rev/13-aeef3bc552504095c2b728e29685612a**

#### How can the CLI team reproduce the problem?

here is my logs

createjs-elements
**https://gist.github.com/blackmirror1980/515aaf14e2a0176958da40b233447762**

elements-js
**https://gist.github.com/blackmirror1980/24f7d0ee6df82cb82dda088692cc3372**

### supporting information:

 - `npm -v` prints: 4.2.0
 - `node -v` prints: 7.10.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
I suggest you email `support@npmjs.com`.
