### ISSUE TITLE
npm is doing something I don't understand.

### ISSUE THREAD

**Issue by miami1109** [npm/npm#17460]
#### I'm opening this issue because:

Whenever I hit the command:

**D:\ionic>ionic start myapp tabs**

 ✔ Creating directory .\myapp - done!
[INFO] Fetching app base (https://github.com/ionic-team/ionic2-app-base/archive/master.tar.gz)
✔ Downloading - done!
[INFO] Fetching starter template tabs (https://github.com/ionic-team/ionic2-starter-tabs/archive/master.tar.gz)
✔ Downloading - done!
✔ Updating package.json with app details - done!
✔ Creating configuration file ionic.config.json - done!
[INFO] Installing dependencies may take several minutes!
> npm install
✖ Running command - failed!
[ERROR] An error occurred while running npm install (exit code 1):

        npm ERR! git submodule -q update --init --recursive: fatal: 'submodule' appears to be a git command, but we were
        not
        npm ERR! git submodule -q update --init --recursive: able to execute it. Maybe git-submodule is broken?
        npm ERR! git submodule -q update --init --recursive:
        npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
        npm WARN addRemoteGit
        npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:206:12)
        npm WARN addRemoteGit     at emitTwo (events.js:106:13)
        npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
        npm WARN addRemoteGit     at maybeClose (internal/child_process.js:877:16)
        npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
        npm WARN addRemoteGit  resin-io/bonjour resetting remote
        C:\Users\xxxxx\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-resin-io-bonjour-git-3f9321aa
        because of error: { Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
        npm WARN addRemoteGit
        npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:206:12)
        npm WARN addRemoteGit     at emitTwo (events.js:106:13)
        npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
        npm WARN addRemoteGit     at maybeClose (internal/child_process.js:877:16)
        npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
        npm WARN addRemoteGit   killed: false,
        npm WARN addRemoteGit   code: 1,
        npm WARN addRemoteGit   signal: null,
        npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
        npm ERR! git clone --template=C:\Users\xxxxx\AppData\Roaming\npm-cache\_git-remotes\_templates
        --mirror https://github.com/resin-io/bonjour.git
        C:\Users\xxxxx\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-resin-io-bonjour-git-3f9321aa:
        Cloning into bare repository
        'C:\Users\xxxxx\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-resin-io-bonjour-git-3f9321aa'...
        npm ERR! git clone --template=C:\Users\xxxxx\AppData\Roaming\npm-cache\_git-remotes\_templates
        --mirror https://github.com/resin-io/bonjour.git
        C:\Users\xxxxx\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-resin-io-bonjour-git-3f9321aa:
        fatal: Unable to find remote helper for 'https'
        npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
        npm WARN addRemoteGit
        npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:206:12)
        npm WARN addRemoteGit     at emitTwo (events.js:106:13)
        npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
        npm WARN addRemoteGit     at maybeClose (internal/child_process.js:877:16)
        npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
        npm WARN addRemoteGit  resin-io/bonjour resetting remote
        C:\Users\xxxxx\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-41f67eef
        because of error: { Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
        npm WARN addRemoteGit
        npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:206:12)
        npm WARN addRemoteGit     at emitTwo (events.js:106:13)
        npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
        npm WARN addRemoteGit     at maybeClose (internal/child_process.js:877:16)
        npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
        npm WARN addRemoteGit   killed: false,
        npm WARN addRemoteGit   code: 1,
        npm WARN addRemoteGit   signal: null,
        npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
        npm ERR! git clone --template=C:\Users\xxxxx\AppData\Roaming\npm-cache\_git-remotes\_templates
        --mirror git@github.com:resin-io/bonjour.git
        C:\Users\xxxxx\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-41f67eef:
        Cloning into bare repository
        'C:\Users\xxxxx\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-41f67eef'...
        npm ERR! git clone --template=C:\Users\xxxxx\AppData\Roaming\npm-cache\_git-remotes\_templates
        --mirror git@github.com:resin-io/bonjour.git
        C:\Users\xxxxx\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-41f67eef:
        Host key verification failed.
        npm ERR! git clone --template=C:\Users\xxxxx\AppData\Roaming\npm-cache\_git-remotes\_templates
        --mirror git@github.com:resin-io/bonjour.git
        C:\Users\xxxxx\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-41f67eef:
        fatal: Could not read from remote repository.
        npm ERR! git clone --template=C:\Users\xxxxx\AppData\Roaming\npm-cache\_git-remotes\_templates
        --mirror git@github.com:resin-io/bonjour.git
        C:\Users\xxxxx\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-41f67eef:
        npm ERR! git clone --template=C:\Users\xxxxx\AppData\Roaming\npm-cache\_git-remotes\_templates
        --mirror git@github.com:resin-io/bonjour.git
        C:\Users\xxxxx\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-41f67eef:
        Please make sure you have the correct access rights
        npm ERR! git clone --template=C:\Users\PARINEETA_SIQES\AppData\Roaming\npm-cache\_git-remotes\_templates
        --mirror git@github.com:resin-io/bonjour.git
        C:\Users\xxxxx\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-41f67eef:
        and the repository exists.
        npm ERR! Windows_NT 10.0.10586
        npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program
        Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
        npm ERR! node v6.9.1
        npm ERR! npm  v3.10.8
        npm ERR! code 128

        npm ERR! Command failed: git -c core.longpaths=true clone
        --template=C:\Users\xxxxx\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror
        git@github.com:resin-io/bonjour.git
        C:\Users\xxxxx\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-41f67eef
        npm ERR! Cloning into bare repository
        'C:\Users\xxxxxx\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-41f67eef'...
        npm ERR! Host key verification failed.
        npm ERR! fatal: Could not read from remote repository.
        npm ERR!
        npm ERR! Please make sure you have the correct access rights
        npm ERR! and the repository exists.
        npm ERR!
        npm ERR!
        npm ERR! If you need help, you may report this error at:
        npm ERR!     <https://github.com/npm/npm/issues>

        npm ERR! Please include the following file with any support request:
        npm ERR!     D:\ionic\myapp\npm-debug.log

Please help !!

**Comment by Tuuba123** [comment]
Same problem here :/

**Comment by miami1109** [comment]
I  have tried every possible solutions.. nothing worked !

**Comment by natera30** [comment]
i'd the same issue and fortunately i fixed the problem.
you should update the " npm packages " : CLI = > npm update and npm update node.
and it's work.

I hope it'll work for you guys.
Best Regards..

**Comment by wclr** [comment]
Just switch to yarn, really.

**Comment by miami1109** [comment]
@natera30  wat's the command for updating npm and npm node ??

**Comment by RakeshKW** [comment]
same issue here. 
npm update is also not working.
what can i do now

here is my problem:
`E:\Ionic>ionic start asa1 blank
✔ Creating directory .\asa1 - done!
[INFO] Fetching app base (https://github.com/ionic-team/ionic2-app-base/archive/master.tar.gz)
✔ Downloading - done!
[INFO] Fetching starter template blank (https://github.com/ionic-team/ionic2-starter-blank/archive/master.tar.gz)
✔ Downloading - done!
✔ Updating package.json with app details - done!
✔ Creating configuration file ionic.config.json - done!
[INFO] Installing dependencies may take several minutes!
> npm install
✖ Running command - failed!
[ERROR] An error occurred while running npm install (exit code 1):

        npm WARN peerDependencies The peer dependency @angular/tsc-wrapped@* included from @ionic/app-scripts will no
        npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
        npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
        npm ERR! git clone
        C:\Users\rakes\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-7c47a979
        C:\Users\rakes\AppData\Local\Temp\npm-7756-ccc181f5\git-cache-5713e4c2d2f7\31d080cee1d8a4b74e03818aaee14da8062f0ea1:
        Cloning into
        'C:\Users\rakes\AppData\Local\Temp\npm-7756-ccc181f5\git-cache-5713e4c2d2f7\31d080cee1d8a4b74e03818aaee14da8062f0ea1'...
        npm ERR! git clone
        C:\Users\rakes\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-7c47a979
        C:\Users\rakes\AppData\Local\Temp\npm-7756-ccc181f5\git-cache-5713e4c2d2f7\31d080cee1d8a4b74e03818aaee14da8062f0ea1:
        git-upload-pack
        'C:\Users\rakes\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-7c47a979':
        git-upload-pack: command not found
        npm ERR! git clone
        C:\Users\rakes\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-7c47a979
        C:\Users\rakes\AppData\Local\Temp\npm-7756-ccc181f5\git-cache-5713e4c2d2f7\31d080cee1d8a4b74e03818aaee14da8062f0ea1:
        fatal: Could not read from remote repository.
        npm ERR! git clone
        C:\Users\rakes\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-7c47a979
        C:\Users\rakes\AppData\Local\Temp\npm-7756-ccc181f5\git-cache-5713e4c2d2f7\31d080cee1d8a4b74e03818aaee14da8062f0ea1:

        npm ERR! git clone
        C:\Users\rakes\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-7c47a979
        C:\Users\rakes\AppData\Local\Temp\npm-7756-ccc181f5\git-cache-5713e4c2d2f7\31d080cee1d8a4b74e03818aaee14da8062f0ea1:
        Please make sure you have the correct access rights
        npm ERR! git clone
        C:\Users\rakes\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-7c47a979
        C:\Users\rakes\AppData\Local\Temp\npm-7756-ccc181f5\git-cache-5713e4c2d2f7\31d080cee1d8a4b74e03818aaee14da8062f0ea1:
        and the repository exists.
        npm ERR! git clone
        C:\Users\rakes\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-7c47a979
        C:\Users\rakes\AppData\Local\Temp\npm-7756-ccc181f5\git-cache-5713e4c2d2f7\31d080cee1d8a4b74e03818aaee14da8062f0ea1:

        npm ERR! git fetch -a origin (https://github.com/resin-io/bonjour.git) fatal: Unable to find remote helper for
        'https'
        npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
        npm WARN addRemoteGit
        npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:206:12)
        npm WARN addRemoteGit     at emitTwo (events.js:106:13)
        npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
        npm WARN addRemoteGit     at maybeClose (internal/child_process.js:877:16)
        npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
        npm WARN addRemoteGit  resin-io/bonjour resetting remote
        C:\Users\rakes\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-a2c5a7ee because of
        error: { Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
        npm WARN addRemoteGit
        npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:206:12)
        npm WARN addRemoteGit     at emitTwo (events.js:106:13)
        npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
        npm WARN addRemoteGit     at maybeClose (internal/child_process.js:877:16)
        npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
        npm WARN addRemoteGit   killed: false,
        npm WARN addRemoteGit   code: 1,
        npm WARN addRemoteGit   signal: null,
        npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
        npm ERR! git clone --template=C:\Users\rakes\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror
        git@github.com:resin-io/bonjour.git
        C:\Users\rakes\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-a2c5a7ee: Cloning into
        bare repository
        'C:\Users\rakes\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-a2c5a7ee'...
        npm ERR! git clone --template=C:\Users\rakes\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror
        git@github.com:resin-io/bonjour.git
        C:\Users\rakes\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-a2c5a7ee: Host key
        verification failed.
        npm ERR! git clone --template=C:\Users\rakes\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror
        git@github.com:resin-io/bonjour.git
        C:\Users\rakes\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-a2c5a7ee: fatal: Could
        not read from remote repository.
        npm ERR! git clone --template=C:\Users\rakes\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror
        git@github.com:resin-io/bonjour.git
        C:\Users\rakes\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-a2c5a7ee:
        npm ERR! git clone --template=C:\Users\rakes\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror
        git@github.com:resin-io/bonjour.git
        C:\Users\rakes\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-a2c5a7ee: Please make
        sure you have the correct access rights
        npm ERR! git clone --template=C:\Users\rakes\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror
        git@github.com:resin-io/bonjour.git
        C:\Users\rakes\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-a2c5a7ee: and the
        repository exists.
        npm ERR! Windows_NT 10.0.15063
        npm ERR! argv "C:\\Program Files\\nodejs\\node.exe"
        "C:\\Users\\rakes\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
        npm ERR! node v6.9.1
        npm ERR! npm  v2.15.11
        npm ERR! code 128

        npm ERR! Command failed: git -c core.longpaths=true clone
        --template=C:\Users\rakes\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror
        git@github.com:resin-io/bonjour.git
        C:\Users\rakes\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-a2c5a7ee
        npm ERR! Cloning into bare repository
        'C:\Users\rakes\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-a2c5a7ee'...
        npm ERR! Host key verification failed.
        npm ERR! fatal: Could not read from remote repository.
        npm ERR!
        npm ERR! Please make sure you have the correct access rights
        npm ERR! and the repository exists.
        npm ERR!
        npm ERR!
        npm ERR! If you need help, you may report this error at:
        npm ERR!     <https://github.com/npm/npm/issues>

        npm ERR! Please include the following file with any support request:
        npm ERR!     E:\Ionic\asa1\npm-debug.log`

**Comment by frank10gm** [comment]
same here

**Comment by skylercole** [comment]
Exact same issue here. 
Last I tested (23.6.) it worked fine.
Now tried with both corporate and non-firewall networks, no result.
Also with different templates.

**Comment by laerteuliam** [comment]
same here

**Comment by relativokobe** [comment]
try updating your node

**Comment by relativokobe** [comment]
i updated mine but it still has errors but less

**Comment by miami1109** [comment]
I updated node today but dint work . Same issues

**Comment by relativokobe** [comment]
`C:\Users\asus>ionic start PISTENGYAWA blank
? The directory PISTENGYAWA contains file(s) that could conflict. Would you like to overwrite the directory with this new p
roject? Yes
✔ Creating directory .\PISTENGYAWA - done!
[INFO] Fetching app base (https://github.com/ionic-team/ionic2-app-base/archive/master.tar.gz)
✔ Downloading - done!
[INFO] Fetching starter template blank (https://github.com/ionic-team/ionic2-starter-blank/archive/master.tar.gz)
✔ Downloading - done!
✔ Updating package.json with app details - done!
✔ Creating configuration file ionic.config.json - done!
[INFO] Installing dependencies may take several minutes!
> npm install
✖ Running command - failed!
[ERROR] An error occurred while running npm install (exit code 1):

        npm WARN deprecated object-keys@0.2.0: Please update to the latest object-keys
        npm ERR! code 1
        npm ERR! Command failed: C:\Program Files\Git\cmd\git.EXE submodule update -q --init --recursive
        npm ERR! C:\Program Files\Git\mingw64/libexec/git-core\git-submodule: line 7: basename: command not found
        npm ERR! C:\Program Files\Git\mingw64/libexec/git-core\git-submodule: line 7: sed: command not found
        npm ERR! C:\Program Files\Git\mingw64/libexec/git-core\git-submodule: line 18: .: git-sh-setup: file not found
        npm ERR!

        npm ERR! A complete log of this run can be found in:
        npm ERR!     C:\Users\asus\AppData\Roaming\npm-cache\_logs\2017-06-27T17_38_43_037Z-debug.log


i have this new error when i updated mine. I dont know what this means :( 
`

**Comment by rtanzifi** [comment]
I have @miami1109 problem too.

**Comment by alejandrofransoy** [comment]
the problem is here:

`3666 error git clone --template=C:\Users\alguien\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:resin-io/bonjour.git C:\Users\alguien\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-41f67eef: Permission denied (publickey).`

**Comment by sakib0hasan** [comment]
Hey, I just ran command prompt with admin rights, and **it worked for me**. Can anyone else verify it?
Thanks!

**Comment by RakeshKW** [comment]
go to your project root directory in CLI mode

run npm install @ionic/app-scripts@latest
then open package.json file of your project and add "reflect-metadata": "^0.1.3" in dependancies and 
then run npm install command 
then run ionic serve --lab 
it will work

**Comment by RakeshKW** [comment]
```
> `go to your project root directory in CLI mode
> 
> run npm install @ionic/app-scripts@latest
> then open package.json file of your project and add "reflect-metadata": "^0.1.3" in dependancies and 
> then run npm install command 
> then run ionic serve --lab 
> it will work`
```

**Comment by miami1109** [comment]
@RakeshKW 

Again new issue..... !!

D:\ionic\myapp>npm install @latest
npm ERR! addLocal Could not install D:\ionic\myapp\@latest
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "@latest"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! path D:\ionic\myapp\@latest
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'D:\ionic\myapp\@latest'
npm ERR! enoent ENOENT: no such file or directory, open 'D:\ionic\myapp\@latest'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     D:\ionic\myapp\npm-debug.log

**Comment by RakeshKW** [comment]
actually i posted wrong commands...so i removed that and  posted right commands...you can see above post.

instead of doing " npm install @latest" do this
`run npm install @ionic/app-scripts@latest`

**Comment by miami1109** [comment]
Acha ok.. I will try

**Comment by miami1109** [comment]
@RakeshKW 

I have hit the above command n was able to download all node modules.
After that what I need to do??

I have again hit this command
D:\ionic>**ionic start myapp tabs** and same errors occurred

**Comment by miami1109** [comment]
@RakeshKW 

Finally !!  problem solved :)
Your above commands worked. 
Thanxx a lot  :)
👍 👍

**Comment by jahanpanahh** [comment]
@RakeshKW  Thanks for the help. It worked for me as well. 

Can you give one liner to understand what's the issue?

**Comment by skylercole** [comment]
It's working like a charm again! No need for manual steps anymore.

I don't know if there was a package fix, as I ran these before re-testing:
npm install -g npm
npm install -g ionic

**Comment by hanifmazlan** [comment]
i got so weird error hmmmmmm

`npm ERR! path /Users/......./node_modules/npm/node_modules/dezalgo/node_modules/asap

npm ERR! code ENOENT

npm ERR! errno -2

npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename 

'/Users/......../node_modules/npm/node_modules/dezalgo/node_modules/asap' -> 

'/Users/..../node_modules/npm/node_modules/dezalgo/node_modules/.asap.DELETE'

npm ERR! enoent This is related to npm not being able to find a file.

npm ERR! enoent`

**Comment by dickverweij** [comment]
did you fix this?
