### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by yaiselwong** [npm/npm#17464]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
i am using de cli for angular when a i try to create a new proyect, the command line show me Successfully initialized git and Installing packages for tooling via npm. But the install progress show me some errors. 
### supporting information:

 - `npm -v` prints:
3.10.10
 - `node -v` prints:
v6.11.0
 - `npm config get registry` prints:
https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?:
Windows
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [x ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
@yaiselwong Could you upload the debug log to <https://gist.github.com/> and link it here? Thanks!
