### ISSUE TITLE
Encountered issues with ionic commands

### ISSUE THREAD

**Issue by miami1109** [npm/npm#17461]
#### I'm opening this issue because:

 C:\Users\xxxxx>ionic
   _             _
  (_)           (_)
   _  ___  _ __  _  ___
  | |/ _ \| '_ \| |/ __|
  | | (_) | | | | | (__
  |_|\___/|_| |_|_|\___|  CLI 3.4.0

  Usage:

    $ ionic <command> [--help] [--verbose] [--quiet] [<args>] [options]
    $ ionic [--confirm] [--no-interactive] [--yarn] [--no-timeout]

  Global Commands:

    docs ..................... Open the Ionic documentation website
    info ..................... Print system/environment info
    login .................... Login with your Ionic ID
    signup ................... Create an Ionic account
    start .................... Create a new project
    telemetry ................ Opt in and out of telemetry

  Project Commands:

    **You are not in a project directory.**

Now again I have encountered some issues
1) Global Commands like : **emulate, plugin, resources, bulid, run , platform** etc are not installed
2) What does it mean "**You are not in a project directory**"??

Am using node js v6.11.0

**Comment by RakeshKW** [comment]
its meaning that ionic command is working fine...
you should hit this command in project directory in CLI

**Comment by kenany** [comment]
Closing since this does not appear to be an issue with `npm` itself.
