### ISSUE TITLE
Unable to create npm org

### ISSUE THREAD

**Issue by Gozala** [npm/npm#17478]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?

I am trying to create an npm organization for my [reflex](https://www.npmjs.com/package/reflex) project, but it seems to fail:

<img width="1106" alt="screen shot 2017-06-27 at 5 12 38 pm" src="https://user-images.githubusercontent.com/21236/27615291-05bc6628-5b5c-11e7-8945-4fe7e50cd3a6.png">

But then I don't seem to be able to find anything by searching [@reflex](https://www.npmjs.com/search?q=@reflex&page=1&ranking=optimal)

Is there any way I can claim the org name (assuming there is actually nothing published under that organization) ? Or if there is some private org with that name is there any way I can get in touch with them ?

Thanks

**Comment by Gozala** [comment]
It seems that there is an npm user with that name https://www.npmjs.com/~reflex which is probably why I can register an org name.

**Comment by kenany** [comment]
Maybe the website team should be informed of this? <https://github.com/npm/www>
