### ISSUE TITLE
Npm fails with `EINTEGRITY` when installing a package

### ISSUE THREAD

**Issue by smac89** [npm/npm#17474]
#### I'm opening this issue because:

  - [x] npm is crashing.

#### What's going wrong?
Attempting to install a package results in error code `EINTEGRITY`

#### How can the CLI team reproduce the problem?
`npm install --save angular-bootstrap-md`

Log: https://gist.github.com/anonymous/5ee15cb0e54afc7200e27af59b1adb0b

### supporting information:

 - `npm -v` prints: `5.0.4`
 - `node -v` prints: `v8.1.2`
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?: Linux
 - Network issues: None

**Comment by dukegod** [comment]
```
15691 verbose node v5.0.0     
15692 verbose npm  v5.0.3     
15693 error code EINTEGRITY       
15694 error sha1-+t2DS5aDBz2hebPq5tnA0VBT9z4= integrity checksum failed when using sha1: wanted sha1-+t2DS5aDBz2hebPq5tnA0VBT9z4= but got sha1-P2inN616btAJ8BU2y2HkhwWiCWI=. (48781 bytes)      
15695 verbose exit [ 1, true ]
```

it happens to me ! when i carry out 
`npm i`

**Comment by smac89** [comment]
So after downgrading to 4.6.1, I no longer experienced this issue. Thanks to [this comment](https://github.com/mdbootstrap/Angular-Bootstrap-with-Material-Design/issues/1#issuecomment-311586131)

Hopefully this is fixed for version 5 shortly.

Gl guys

**Comment by d668** [comment]
why is it closed?

**Comment by doantson** [comment]
thanks to smac89 and the link he's given, i solved this stuck.
