### ISSUE TITLE
Cannot read property 'path' of null

### ISSUE THREAD

**Issue by kanajam** [npm/npm#17488]
Hi Team,

I'm getting the below error when I try to install any package using npm (not only angular-cli). I'm working on beyond proxy and I did proxy setting with following commands:

C:\Users\vijay_kanajam>npm install -g @angular/cli
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5

npm ERR! Cannot read property 'path' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\vijay_kanajam\npm-debug.log

npm config get registry 
npm config get http-proxy 
npm config get https-proxy 

and I got the exact results as expected.

proxy=xx.xxx.xxx.xxx:xx 
https-proxy=xx.xxx.xxx.xxx:xx
registry=http://registry.npmjs.org/

Here 'x' replaces with different values as I can't share over social media.
Can somebody help me out on this as it was very important to get start for angularjs project.

Regards,
Vijay Kanajam

npm-debug:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   '@angular/cli' ]
2 info using npm@4.0.5
3 info using node@v7.4.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData @angular/cli
8 silly fetchNamedPackageData @angular/cli
9 silly mapToRegistry name @angular/cli
10 silly mapToRegistry scope (from package name) @angular
11 verbose mapToRegistry no registry URL found in name for scope @angular
12 silly mapToRegistry using default registry
13 silly mapToRegistry registry http://registry.npmjs.org/
14 silly mapToRegistry data Result {
14 silly mapToRegistry   raw: '@angular/cli',
14 silly mapToRegistry   scope: '@angular',
14 silly mapToRegistry   escapedName: '@angular%2fcli',
14 silly mapToRegistry   name: '@angular/cli',
14 silly mapToRegistry   rawSpec: '',
14 silly mapToRegistry   spec: 'latest',
14 silly mapToRegistry   type: 'tag' }
15 silly mapToRegistry uri http://registry.npmjs.org/@angular%2fcli
16 verbose request uri http://registry.npmjs.org/@angular%2fcli
17 verbose request no auth needed
18 info attempt registry request try #1 at 2:48:46 PM
19 verbose request id 221dfb4406950736
20 http request GET http://registry.npmjs.org/@angular%2fcli
21 info retry will retry, error on last attempt: Error: Invalid protocol: 10.136.255.129:
22 info attempt registry request try #2 at 2:48:56 PM
23 http request GET http://registry.npmjs.org/@angular%2fcli
24 info retry will retry, error on last attempt: Error: Invalid protocol: 10.136.255.129:
25 info attempt registry request try #3 at 2:49:56 PM
26 http request GET http://registry.npmjs.org/@angular%2fcli
27 silly fetchPackageMetaData Error: Invalid protocol: 10.136.255.129:
27 silly fetchPackageMetaData     at Request.init (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:459:31)
27 silly fetchPackageMetaData     at new Request (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:128:8)
27 silly fetchPackageMetaData     at request (C:\Program Files\nodejs\node_modules\npm\node_modules\request\index.js:54:10)
27 silly fetchPackageMetaData     at CachingRegistryClient.makeRequest (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:158:13)
27 silly fetchPackageMetaData     at C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:66:17
27 silly fetchPackageMetaData     at RetryOperation._fn (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\attempt.js:18:5)
27 silly fetchPackageMetaData     at Timeout._onTimeout (C:\Program Files\nodejs\node_modules\npm\node_modules\retry\lib\retry_operation.js:68:10)
27 silly fetchPackageMetaData     at ontimeout (timers.js:365:14)
27 silly fetchPackageMetaData     at tryOnTimeout (timers.js:237:5)
27 silly fetchPackageMetaData     at Timer.listOnTimeout (timers.js:207:5)
27 silly fetchPackageMetaData  error for @angular/cli Error: Invalid protocol: 10.136.255.129:
27 silly fetchPackageMetaData     at Request.init (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:459:31)
27 silly fetchPackageMetaData     at new Request (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:128:8)
27 silly fetchPackageMetaData     at request (C:\Program Files\nodejs\node_modules\npm\node_modules\request\index.js:54:10)
27 silly fetchPackageMetaData     at CachingRegistryClient.makeRequest (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:158:13)
27 silly fetchPackageMetaData     at C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:66:17
27 silly fetchPackageMetaData     at RetryOperation._fn (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\attempt.js:18:5)
27 silly fetchPackageMetaData     at Timeout._onTimeout (C:\Program Files\nodejs\node_modules\npm\node_modules\retry\lib\retry_operation.js:68:10)
27 silly fetchPackageMetaData     at ontimeout (timers.js:365:14)
27 silly fetchPackageMetaData     at tryOnTimeout (timers.js:237:5)
27 silly fetchPackageMetaData     at Timer.listOnTimeout (timers.js:207:5)
28 silly rollbackFailedOptional Starting
29 verbose stack TypeError: Cannot read property 'path' of null
29 verbose stack     at Installer.rollbackFailedOptional (C:\Program Files\nodejs\node_modules\npm\lib\install.js:505:29)
29 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
29 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
29 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:18:7
29 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install.js:331:5
29 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
29 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
29 verbose stack     at chain (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
29 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install.js:288:5
29 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:16:22
30 verbose cwd C:\Users\vijay_kanajam
31 error Windows_NT 6.1.7601
32 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli"
33 error node v7.4.0
34 error npm  v4.0.5
35 error Cannot read property 'path' of null
36 error If you need help, you may report this error at:
36 error     <https://github.com/npm/npm/issues>
37 verbose exit [ 1, true ]

**Comment by puneetdewan** [comment]
Hi guys i am getting this problem while installing a package. Can you help me out? 

  ```
`Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\puneet.dewan>npm install -g babel
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "babel"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5

npm ERR! Cannot read property 'path' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\puneet.dewan\npm-debug.log`
```

**Comment by puneetdewan** [comment]
# npm-debug

```

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'babel' ]
2 info using npm@4.0.5
3 info using node@v7.4.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData babel
8 silly fetchNamedPackageData babel
9 silly mapToRegistry name babel
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry http://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'babel',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'babel',
12 silly mapToRegistry   name: 'babel',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri http://registry.npmjs.org/babel
14 verbose request uri http://registry.npmjs.org/babel
15 verbose request no auth needed
16 info attempt registry request try #1 at 3:51:24 PM
17 verbose request id 3fb2beff6458b7d8
18 http request GET http://registry.npmjs.org/babel
19 info retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND proxyhost proxyhost:80
20 info attempt registry request try #2 at 3:51:37 PM
21 http request GET http://registry.npmjs.org/babel
22 info retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND proxyhost proxyhost:80
23 info attempt registry request try #3 at 3:52:39 PM
24 http request GET http://registry.npmjs.org/babel
25 silly fetchPackageMetaData Error: getaddrinfo ENOTFOUND proxyhost proxyhost:80
25 silly fetchPackageMetaData     at errnoException (dns.js:28:10)
25 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
25 silly fetchPackageMetaData  error for babel { Error: getaddrinfo ENOTFOUND proxyhost proxyhost:80
25 silly fetchPackageMetaData     at errnoException (dns.js:28:10)
25 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
25 silly fetchPackageMetaData   code: 'ENOTFOUND',
25 silly fetchPackageMetaData   errno: 'ENOTFOUND',
25 silly fetchPackageMetaData   syscall: 'getaddrinfo',
25 silly fetchPackageMetaData   hostname: 'proxyhost',
25 silly fetchPackageMetaData   host: 'proxyhost',
25 silly fetchPackageMetaData   port: 80 }
26 silly rollbackFailedOptional Starting
27 verbose stack TypeError: Cannot read property 'path' of null
27 verbose stack     at Installer.rollbackFailedOptional (C:\Program Files\nodejs\node_modules\npm\lib\install.js:505:29)
27 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
27 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
27 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:18:7
27 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install.js:331:5
27 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
27 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
27 verbose stack     at chain (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
27 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install.js:288:5
27 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:16:22
28 verbose cwd C:\Users\puneet.dewan
29 error Windows_NT 10.0.14393
30 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "babel"
31 error node v7.4.0
32 error npm  v4.0.5
33 error Cannot read property 'path' of null
34 error If you need help, you may report this error at:
34 error     <https://github.com/npm/npm/issues>
35 verbose exit [ 1, true ]

```

**Comment by Anjitha7575** [comment]
Try giving some package name.
or Just try this
npm install -g npm-install

**Comment by puneetdewan** [comment]
@Anjitha7575  I am trying to install babel.
I just tried 
npm install -g npm-install
This is again giving an error
```

C:\Users\puneet.dewan>npm install -g npm-install
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "npm-install"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5

npm ERR! Cannot read property 'path' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\puneet.dewan\npm-debug.log


```

**Comment by Anjitha7575** [comment]
Please check whether npm path is set in environment variables. That may be the reason.

**Comment by Anjitha7575** [comment]
Also check your proxy settings.
