### ISSUE TITLE
npm install @latest error

### ISSUE THREAD

**Issue by AshcatY2K** [npm/npm#17490]
#### I'm opening this issue because:

  - [ ] npm is crashing.

#### What's going wrong?

When I try to install the latest version of npm I receive an error saying:
 cd() never called

It prints that this is a problem with npm itself and that I should report the problem

#### How can the CLI team reproduce the problem?

run > npm install @latest 
 
Degub file:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\lyall\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '@latest' ]
2 info using npm@5.0.4
3 info using node@v7.7.3
4 verbose npm-session 532e2e45cd7044dc
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 error cb() never called!
8 error This is an error with npm itself. Please report this error at:
9 error <https://github.com/npm/npm/issues>

### supporting information:

 - `npm -v` prints: 5.0.4
 - `node -v` prints: v7.7.3
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows 10
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the web.
 - Container:

**Comment by watilde** [comment]
Hello! I think this issue is duplicated with https://github.com/npm/npm/issues/17433.
