### ISSUE TITLE
npm ERR! Unexpected token >

### ISSUE THREAD

**Issue by blubbsy** [npm/npm#17492]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Hi i try to install nodejs from the nodejs repository to install only office, but i have problems to get it working without knowing why. Maybe it is because i get nodejs 0.10.26, but nothing newer from the repository, i dont know. Whenever i try to update npm, node or install a package i receive the following errors:

0 info it worked if it ends with ok
1 warn npm npm does not support Node.js v0.10.26
2 warn npm You should probably upgrade to a newer version of node as we
3 warn npm can't make any promises that npm will work with this version.
4 warn npm You can find the latest version at https://nodejs.org/
5 verbose cli [ 'node', '/usr/local/bin/npm', 'install', '-g', 'n' ]
6 info using npm@5.0.3
7 info using node@v0.10.26
8 verbose type unexpected_token
9 verbose stack SyntaxError: Unexpected token >
9 verbose stack     at Module._compile (module.js:439:25)
9 verbose stack     at Object.Module._extensions..js (module.js:474:10)
9 verbose stack     at Module.load (module.js:356:32)
9 verbose stack     at Function.Module._load (module.js:312:12)
9 verbose stack     at Module.require (module.js:364:17)
9 verbose stack     at require (module.js:380:17)
9 verbose stack     at Object.defineProperty.get [as install] (/usr/local/lib/node_modules/npm/lib/npm.js:118:17)
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:84:30)
9 verbose stack     at process._tickCallback (node.js:415:13)
10 verbose cwd /home/devsibwarra
11 verbose Linux 4.9.0-3-amd64
12 verbose argv "node" "/usr/local/bin/npm" "install" "-g" "n"
13 verbose node v0.10.26
14 verbose npm  v5.0.3
15 error Unexpected token >
16 verbose exit [ 1, true ]

Someone knows what the problem is? Is it the old nodejs version i would like to also update? 

Greetings,
Blubbsy

#### How can the CLI team reproduce the problem?
no idea.

### supporting information:

 - `npm -v` prints:
npm -v
5.0.3

 - `node -v` prints:
 node -v
v0.10.26

 - `npm config get registry` prints:
npm WARN npm npm does not support Node.js v0.10.26
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm You can find the latest version at https://nodejs.org/
https://registry.npmjs.org/

 - Windows, OS X/macOS, or Linux?: Debian Stretch
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kmattimo** [comment]
This happened to me on heroku with a legacy node app. Something in the upgrade to npm4 to npm5 caused it. Specifying npm="v4.5.0" in the package.json rather than >= whatever it was before solved it for my case. It is better to try and upgrade though!

**Comment by cg-cnu** [comment]
Am upgrading npm from 3 to 5 and got the same error. 
Not exactly sure what's the issue. Changed the permissions of the ```/usr/local/lib/node_modules``` from the root user to the regular user and installing worked.

**Comment by cg-cnu** [comment]
Any global module installation with -g fails with the below error when run as root. 

```
/usr/lib/node_modules/npm/lib/install.js:298
        [this, (next) => { computeMetadata(this.idealTree); next() }],
                       ^
npm ERR! Unexpected token >
```

I had to change the ownership of ```/usr/local/lib/``` and ```/usr/local/bin/``` to regular user to install the modules. Just a temp fix to get things working. Can some one explain how to fix this one ?
