### ISSUE TITLE
npm uninstall -g protractor error

### ISSUE THREAD

**Issue by maiasmith** [npm/npm#17497]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Trying to globally uninstall protractor, but getting error.

#### How can the CLI team reproduce the problem?

I ran `npm uninstall -g protractor` and received [the following error](https://gist.github.com/maiasmith/3edac27b9a2203cf900cd2977978467f)

### supporting information:

 - `npm -v` prints: 5.0.3
 - `node -v` prints: v7.2.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Mac
 - Network issues:
   - Geographic location where npm was run: Canada
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by ldminoc** [comment]
+1 with 5.0.4 and different package (express-generator).
macOS 10.12.5,

[2017-06-30T06_54_45_226Z-debug.log.zip](https://github.com/npm/npm/files/1114383/2017-06-30T06_54_45_226Z-debug.log.zip)

**Comment by hauntingEcho** [comment]
same here - also with npm on OSX installed via homebrew, but with node@6.11.0:

[output of `npm uninstall -g chai; npm list -g --depth=0; cat <log>`](https://gist.github.com/hauntingEcho/51ae0398f67f83817b4ef535e8e73d43)
