### ISSUE TITLE
npm ERR! Unexpected token <

### ISSUE THREAD

**Issue by TheDutchCoder** [npm/npm#17496]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Every package I try to install generates this error.

#### How can the CLI team reproduce the problem?
For me it happens at every `npm install [package]`

### supporting information:

 - `npm -v` prints:
5.0.0

 - `node -v` prints:
4.8.2

 - `npm config get registry` prints:
https://registry.npmjs.org/

 - Windows, OS X/macOS, or Linux?:
OS X (Sierra: 10.12.5)

 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [x] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by casmith** [comment]
There's not much to go on. Can you attach your npm-debug.log and consider logging verbose?

**Comment by TheDutchCoder** [comment]
My apologies. As it turned out we were trying to npm install with node 0.10 and npm 5, but node 4+ was required, which fixed the issue.

Thanks!
