### ISSUE TITLE
debian stretch install problem

### ISSUE THREAD

**Issue by spavlovich001** [npm/npm#17494]
#curl -L https://www.npmjs.com/install.sh | sh
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6255  100  6255    0     0  10053      0 --:--:-- --:--:-- --:--:-- 10040
tar=/bin/tar
version:
tar (GNU tar) 1.29
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
install npm@latest
fetching: https://registry.npmjs.org/npm/-/npm-5.0.4.tgz
added 1 package and removed 2 packages in 0.779s
/usr/bin/npm -> /usr/lib/node_modules/npm/bin/npm-cli.js
+ npm@5.0.4
added 1 package in 0.995s
It worked
```
#file /usr/lib/node_modules/npm/bin/npm-cli.js
`/usr/lib/node_modules/npm/bin/npm-cli.js: cannot open `/usr/lib/node_modules/npm/bin/npm-cli.js' (No such file or directory)
#file /usr/bin/npm
`/usr/bin/npm: broken symbolic link to ../lib/node_modules/npm/bin/npm-cli.js`

**Comment by Kolyunya** [comment]
@vasyapupkin123456 were you able to solve this? I just installed a fresh `stretch` and faced the same problem.

**Comment by ThreepE0** [comment]
have you tried creating the symbolic link yourself?  If npm is installed at /usr/share/npm, this should work:
`
rm /usr/bin/npm`

`
ln -s /usr/share/npm/bin/npm-cli.js /usr/bin/npm
`

if this doesn't work, let me know and I'll spool up a Stretch
