### ISSUE TITLE
While i start the npm, i got the below error

### ISSUE THREAD

**Issue by krpmurugan** [npm/npm#17509]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\node\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\node\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'strat' ]
2 info using npm@3.10.10
3 info using node@v6.11.0
4 verbose stack Error: missing script: strat
4 verbose stack     at run (C:\Program Files\node\nodejs\node_modules\npm\lib\run-script.js:151:19)
4 verbose stack     at C:\Program Files\node\nodejs\node_modules\npm\lib\run-script.js:61:5
4 verbose stack     at C:\Program Files\node\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:356:5
4 verbose stack     at checkBinReferences_ (C:\Program Files\node\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:320:45)
4 verbose stack     at final (C:\Program Files\node\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:354:3)
4 verbose stack     at then (C:\Program Files\node\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:124:5)
4 verbose stack     at C:\Program Files\node\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:311:12
4 verbose stack     at C:\Program Files\node\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
4 verbose stack     at tryToString (fs.js:456:3)
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:443:12)
5 verbose cwd C:\dev\ng2-fundamentals
6 error Windows_NT 6.1.7601
7 error argv "C:\\Program Files\\node\\nodejs\\node.exe" "C:\\Program Files\\node\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "strat"
8 error node v6.11.0
9 error npm  v3.10.10
10 error missing script: strat
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

**Comment by kenany** [comment]
Hello! So, the way `npm start` works is that it looks in your current `package.json` for a defined `"start"` [script](https://docs.npmjs.com/misc/scripts), and then runs that. The error message you're seeing is trying to tell you that you have not defined a `"start"` script in your `package.json`, hence `npm start` has no idea what you want it to do.

To solve this issue, all you have to do is add a new script to your `package.json`. It might look something like this, for example:

``` json
{
  "name": "package-name",
  "version": "1.0.0",
  "description": "package description",
  "scripts": {
    "start": "node --version",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {},
  "devDependencies": {}
}
```

Note how this `package.json` has a `"start"` script that runs `node --version`. You'll definitely want to change the command to whatever is most appropriate for your project.

Let me know if you run into any further `npm` issues :)

**Comment by kenany** [comment]
Closing due to no response after a week.
