### ISSUE TITLE
Installation issue - node-red-openzwave-shared

### ISSUE THREAD

**Issue by Saschaya** [npm/npm#17517]
Hello everybody,

I'm a new guy in this community and in IoT. I'm working on a Raspberry Pi and I want to control my Z-Wave devices by Node-Red.

However, I followed the official tutorial of Node-Red and I have an issue during the installation of a module.

So please find below the issue instructions:

[ISSUE.TXT](https://github.com/npm/npm/files/1112178/ISSUE.TXT)

And here the .log file :+1: 

[npm-debug.zip](https://github.com/npm/npm/files/1112186/npm-debug.zip)

Thank you...

**Comment by legodude17** [comment]
Could you upload the npm-debug.log as a plaintext file to https://gist.github.com/ and post a link to it here?

**Comment by Saschaya** [comment]
Hello legodude17,

Of course, here the link: 

https://gist.github.com/Saschaya/9165cd1ff3b02b76d9f434fdd00dcc19


```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   'node-red-openzwave-shared' ]
2 info using npm@5.0.4
3 info using node@v6.11.0
4 verbose config Skipping project config: /home/pi/.npmrc. (matches userconfig)
5 verbose npm-session 40aa0177d9b01e6d
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 http fetch GET 404 https://registry.npmjs.org/node-red-openzwave-shared 1561ms
9 silly fetchPackageMetaData error for node-red-openzwave-shared@latest 404 Not Found: node-red-openzwave-shared@latest
10 verbose stack Error: 404 Not Found: node-red-openzwave-shared@latest
10 verbose stack     at fetch.then.res (/usr/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:41:19)
10 verbose stack     at tryCatcher (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
10 verbose stack     at Promise._settlePromiseFromHandler (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
10 verbose stack     at Promise._settlePromise (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
10 verbose stack     at Promise._settlePromise0 (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
10 verbose stack     at Promise._settlePromises (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
10 verbose stack     at Async._drainQueue (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
10 verbose stack     at Async._drainQueues (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
10 verbose stack     at Immediate.Async.drainQueues (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
10 verbose stack     at runCallback (timers.js:672:20)
10 verbose stack     at tryOnImmediate (timers.js:645:5)
10 verbose stack     at processImmediate [as _immediateCallback] (timers.js:617:5)
11 verbose cwd /home/pi
12 verbose Linux 4.9.28-v7+
13 verbose argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "node-red-openzwave-shared"
14 verbose node v6.11.0
15 verbose npm  v5.0.4
16 error code E404
17 error 404 Not Found: node-red-openzwave-shared@latest
18 verbose exit [ 1, true ]
```

Thank you.

**Comment by kenany** [comment]
Seems like there does not exist a package named `node-red-openzwave-shared`, hence the error. Are you sure that you are installing the correct package?

**Comment by Saschaya** [comment]
Yes but it is maybe because I want to install this package ?

**Comment by kenany** [comment]
But it doesn't exist in the registry, so... 🤷‍♂️

**Comment by Saschaya** [comment]
Ok thank you but how could I add this package and where have I to set it ?

**Comment by kenany** [comment]
Add the package to what/where?

**Comment by Saschaya** [comment]
That's exactly my question.

**Comment by kenany** [comment]
@Saschaya Could you link me the "official tutorial of Node-Red" that you are following?

**Comment by Saschaya** [comment]
Yes of course, it was the following :

 https://flows.nodered.org/node/node-red-contrib-openzwave

**Comment by kenany** [comment]
I guess those instructions must be out of date or something. Maybe the author(s) of that documentation could shed some light on this issue if you contact them?

**Comment by Saschaya** [comment]
That's possible, I will try to contact this person !

Thank you.

**Comment by Saschaya** [comment]
As I said previously, I'm beginner in this community. Hence, I don't know how I can contact the authour of the tutorial. 

Apparently, the maintainer is "ekarak", but how could I send him a message ?

**Comment by kenany** [comment]
You could contact them by, for example, opening an issue on [the project](https://github.com/OpenZWave/node-red-contrib-openzwave).
