### ISSUE TITLE
When I install npm (npm install --no-bin-links), i got the below error

### ISSUE THREAD

**Issue by shojai80** [npm/npm#17516]
$ npm install --no-bin-links
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm ERR! Windows_NT 6.1.7600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--no-bin-links"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10

npm ERR! Maximum call stack size exceeded
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     G:\lfproject\npm-debug.log

**Comment by legodude17** [comment]
Does this occur on the latest version?
