### ISSUE TITLE
npm start get error in cmd

### ISSUE THREAD

**Issue by natali72** [npm/npm#17515]
Hello!

I have no idea why it is not working after success of install. Could somebody help me with this?

![npm_start](https://user-images.githubusercontent.com/29773566/27682732-f0128a8c-5cc3-11e7-8b7e-a74e6bfe4ca3.png)

**Comment by kenany** [comment]
Looks like this error is coming from the TS compiler, not `npm`. All `npm` is doing here is letting you know about it. Maybe the `rxjs` authors can help shed light on this?
