### ISSUE TITLE
How to remove package-lock.json file in Windows 10?

### ISSUE THREAD

**Issue by YuilTripathee** [npm/npm#17514]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
#### What's going wrong?
Because of EINTRIGITY error and "checksum failed" error, I cannot download angular 4. I heard that removing package-lock.json file has resolved this issue in many others. So, can someone help me to figure out how can I remove this file "package-lock.json"?
### supporting information:

 - `npm -v` prints: v8.1.2
 - `node -v` prints: 5.0.3
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows 10 Anniversary Update

**Comment by tcrosen** [comment]
Add an `.npmrc` file to your project and add the following:

```
package-lock=false 
```

**Comment by YuilTripathee** [comment]
thanks
