### ISSUE TITLE
503 All backends failed or unhealthy

### ISSUE THREAD

**Issue by csvan** [npm/npm#17521]
Currently seeing this in Serbia. From what I gather this is a CloudFront issue?

**Comment by csvan** [comment]
Same: https://github.com/npm/npm/issues/4773

**Comment by klpx** [comment]
Hi! I have same problem from Russia.

**Comment by rustichowie** [comment]
Hi! I'm having the same problem in Norway.

**Comment by Luchanso** [comment]
+1

**Comment by andyburton** [comment]
+2

**Comment by klpx** [comment]
Seems it recovered.

**Comment by csvan** [comment]
Seems to work here (Serbia) as well again. Leaving open in case other regions have the same issue.

**Comment by kenany** [comment]
Seems to be resolved now, <https://status.npmjs.org/incidents/tfjx9s322g92>.

**Comment by tomasklima** [comment]
Not resolved yet. Now from Czech Republic.

**Comment by tomasklima** [comment]
Now it's ok
