### ISSUE TITLE
`npm install --no-registry` is still calling to the registry

### ISSUE THREAD

**Issue by bdharrington7** [npm/npm#17535]
#### I'm opening this issue because:

  - [ X] npm is doing something I don't understand.

#### What's going wrong?

I specify the `--no-registry` flag, and yet npm still calls out to the registry:
```
# npm install --no-registry
npm info it worked if it ends with ok
npm info using npm@5.0.3
npm info using node@v8.1.2
npm info lifecycle anf-importer@1.0.0~preinstall: anf-importer@1.0.0
npm http fetch GET 200 https://registry.npmjs.org/body-parser 114ms
npm http fetch GET 200 https://registry.npmjs.org/express 157ms
npm http fetch GET 200 https://registry.npmjs.org/better-sqlite3 176ms
npm http fetch GET 200 https://registry.npmjs.org/body-parser/-/body-parser-1.17.2.tgz 102ms
npm http fetch GET 200 https://registry.npmjs.org/express/-/express-4.15.3.tgz 63ms
npm http fetch GET 200 https://registry.npmjs.org/pg-promise 321ms
npm http fetch GET 200 https://registry.npmjs.org/pg-promise/-/pg-promise-5.9.5.tgz 122ms
npm http fetch GET 200 https://registry.npmjs.org/better-sqlite3/-/better-sqlite3-2.3.3.tgz 312ms
```
Moreover, it's calling to the public registry, not the one npm is configured to use:

```
# npm config get registry
npm info it worked if it ends with ok
npm info using npm@5.0.3
npm info using node@v8.1.2
https://npm.company.com/
npm info ok
```
#### How can the CLI team reproduce the problem?

run `npm install --no-registry` on a project that already has node_modules installed. 

### supporting information:

This is in a docker container drawing from node:8.1.2

**Comment by zkat** [comment]
This is not how the `--registry` option works.

If you want to force offline installation and force an error when data is not available in cache, use `--offline` instead.
