### ISSUE TITLE
`build` directory produced by prepare script is omitted

### ISSUE THREAD

**Issue by yashafromrussia** [npm/npm#17534]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

When `prepare` script creates a new directory called `build`, it is not copied into the module directory after installation. I use TypeScript to transpile .ts into .js. So it uses the output directory to keep things clean. I renamed it to `lib` and everything works perfectly.. Spent 2-3 hours figuring this out. Is this mentioned somewhere or is it a bug?

#### How can the CLI team reproduce the problem?

1. Set `prepare` script to `"touch file.txt; mkdir build; touch build/file.txt; mkdir lib; touch lib/file.txt"`.
2. Install the package.
3. `file.txt` and `lib/file.txt` exist but `build/file.txt` is missing.

### supporting information:

 - `npm -v` prints: 5.0.4
 - `node -v` prints: v8.1.3
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by yashafromrussia** [comment]
This happens when installing packages from GitHub/Bitbucket by the way.. not sure if the same thing happens when installing a package from NPM.

**Comment by tko** [comment]
Just to be sure do you have `.gitignore` and/or `.npmignore` set to _not_ exclude `build/` directory? (By default it's probably ignored via .gitignore and you'll need to override it with .npmignore to get the files included.)

**Comment by yashafromrussia** [comment]
@tko Yep that's exactly it! I just noticed a generated `.npmignore` file with the same contents as my `.gitignore` file. So if I include custom `.npmignore` it should work

**Comment by yashafromrussia** [comment]
Confirming that it works as intended if the `.npmignore` file is included
