### ISSUE TITLE
trying to remove yarn gives error

### ISSUE THREAD

**Issue by dchinn** [npm/npm#17547]
#### I'm opening this issue because:

  - [x. ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
npm uninstall -g yarn throws error:
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\david\AppData\Roaming\npm-cache\_logs\2017-06-30T14_57_08_965Z-debug.log

#### How can the CLI team reproduce the problem?
I've been playing with yarn, and lately realized that npm has installed an earlier version of yarn, and so i want to install using the yarn installer.  

However, even though the installer tries to install the latest version, i still see an earlier version of yarn.

So, I try:

npm uninstall -g yarn

at which time the error shows.

gist of the error file:
https://gist.github.com/dchinn/7659105d2d6e9bd06a3dbb56f36d4eb9

### supporting information:

 - `npm -v` prints: 5.0.4
 - `node -v` prints: 6.10.2
 - `npm config get registry` prints: https://registry.npmjs.org
 - Windows, OS X/macOS, or Linux?: widnows 10
 - Network issues:
   - Geographic location where npm was run: washington state
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
Yup, known issue https://github.com/npm/npm/issues/16738
