### ISSUE TITLE
npm run tsc throw the following error

### ISSUE THREAD

**Issue by krpmurugan** [npm/npm#17545]
npm ERR! missing script: compile

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "compile"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10

npm ERR! missing script: compile
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\development\ng2-fundamentals\npm-debug.log

**Comment by kenany** [comment]
Seems like you're trying to run a `"compile"` script, but you don't have one defined in your `package.json`.

**Comment by kenany** [comment]
Closing due to no response after a week.
