### ISSUE TITLE
tarball.destroy is not a function

### ISSUE THREAD

**Issue by omidgharib** [npm/npm#17556]
#### I'm opening this issue because:
  - [x] npm is producing an incorrect install.

#### What's going wrong?
 Windows_NT 6.3.9600 
 argv "E:\\Program Files\\nodejs\\node.exe" "E:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save-dev" "gulp-babel" "babel-p reset es2015"
#### How can the CLI team reproduce the problem?
     I got npm error during installing "npm install --save-dev gulp-babel babel-preset-es2015"

 - Container:
   - [ ] I develop using Vagrant on Windows.

**Comment by kenany** [comment]
Could you upload the full debug log to <https://gist.github.com/> and link it here? Thanks!

**Comment by kenany** [comment]
Closing due to no response.
