### ISSUE TITLE
A documentation fix request

### ISSUE THREAD

**Issue by jefflembeck** [npm/npm#17550]
Copied from:

https://github.com/npm/www/issues/190

#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ x ] Other (_see below for feature requests_):

#### What's going wrong?

Documentation error, from https://github.com/npm/www/issues/190

There's some misleading documentation on the website, here:

https://docs.npmjs.com/misc/config

This page calls out NPM_CONF_USERCONFIG and NPM_CONF_GLOBALCONFIG as environment variable versions of --userconfig and --globalconfig. However, these do not work -- the correct environment variables to use are NPM_CONFIG_USERCONFIG and NPM_CONFIG_GLOBALCONFIG.

Tested in npm v2.latest and npm v5.latest.

**Comment by kenany** [comment]
Should be fixed by https://github.com/npm/npm/pull/17369, once deployed.

**Comment by elliot-nelson** [comment]
Thanks!  (The PR fixes only the user one and not the global one, but I'd imagine the user one is used much more often.)

**Comment by kenany** [comment]
Both typos were fixed in the merge :) https://github.com/npm/npm/commit/d0f3b5a127718b0347c6622a2b9c28341c530d36

**Comment by elliot-nelson** [comment]
🙇

**Comment by iarna** [comment]
As the fix for this has been merged, I'm going to close this issue while I still remember to. =D It's in `release-next` which will be going out next week. Monday or Wednesday depending on how Kat and I feel about it. (In the meantime you can try out all the changes in `npmc`, the canary version of npm.)
