### ISSUE TITLE
Npm install doesn't tell me anymore which packages updated

### ISSUE THREAD

**Issue by simonemazzoni** [npm/npm#17557]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?
Just invoked `npm install` to update packages and recreate `package-log.json`
OUTPUT: `added 12 packages and updated 4 packages in 16.002s`

As you can see npm tells that updated 4 packages and added 12, but it doesn't tell which packages added! Why this? It used to tell which packages updated. This cause confusion since now I don't know which packages changed.

### supporting information:

 - `npm -v` prints: 5.0.4
 - `node -v` prints: v6.11.0
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?: macOsSierra
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by ScottFreeCode** [comment]
I think this is intended behavior -- the old behavior of dumping the dependency tree on install was seen as often useless due to the dependency tree being too large to read, or something along those lines. Printing only the *immediate*/*direct* dependencies affected seems like it would have been a good compromise, but that's just my reaction -- I don't know how much more or less complex that would have been to implement.

You can kinda-sorta get that after the fact by running `npm ls --depth=0` -- that lists the direct dependencies currently installed, albeit not exactly the set affected by the most recent action; running it both before and after could be used as a... clunky... manual comparison method.

**Comment by simonemazzoni** [comment]
@ScottFreeCode thanks for the answer but I don't think that is an acceptable solution.
The point is that previously npm versions used to do this, so I guess it shouldn't be that difficult to maintain this same behaviour. Furthermore, the new version already tells how many packages has been updated, so again I guess is fairly easy to print out also the name of that  packages.

**Comment by zkat** [comment]
This is working as intended. We _used_ to print out the names of all the packages we updated and installed, and it resulted in a *lot* of spam in practice.

The current intended design is to print out only direct installs. If you want to get a more detailed view on updated packages, I recommend you use git to look at the diff for `package-lock.json` -- that will show you all the details of everything that was updated without having npm spam people. A big reason for `package-lock.json` is precisely to give you a useful way to explore updates to your packages.

**Comment by simonemazzoni** [comment]
@zkat I really don't understand how print a report of what happened due to a command invocation could be considered spam.
I understand that I can diff the package-lock.json file, but what if I forgot to commit the changes every time I update or install a package? This doesn't seem a fail proof or handy solution.
Does exists a command to force the print of that info? Something like `--verbose` or similar?

Thanks
