### ISSUE TITLE
EONEONT - 4058

### ISSUE THREAD

**Issue by rscharfer** [npm/npm#17567]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I am trying to clone a repository from Github and I being asked to rename a file I cannot find.

#### Gist

https://gist.github.com/rscharfer/f3633eac49b1f9e14f1956aca8ad7ab3

### supporting information:

 - `npm -v` prints: 5.0.4
 - `node -v` prints: 6.11.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows

I just updated npm and node today...
 - Network issues:
   - Geographic location where npm was run: home, Hamburg, Germany
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
I think you should `git clone` that repository, rather than `npm install` it.

**Comment by rscharfer** [comment]
you're right.  sometimes you just need to step away from the computer for a bit ; )
