### ISSUE TITLE
Do Not Have Permission to Publish despite proper login

### ISSUE THREAD

**Issue by ersurajnegi** [npm/npm#17569]
I log into my NPM account via the website and it's there and everything's correct. 
However, when I try to publish an update to my package I am given a ERR403 - "You do not have permission to publish to '***'. Are you logged in as the correct user? "

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'publish' ]
2 info using npm@3.10.10
3 info using node@v6.11.0
4 verbose publish [ '.' ]
5 silly cache add args [ '.', null ]
6 verbose cache add spec .
7 silly cache add parsed spec Result {
7 silly cache add   raw: '.',
7 silly cache add   scope: null,
7 silly cache add   escapedName: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: '.',
7 silly cache add   spec: 'E:\\Mynpm Module\\dist',
7 silly cache add   type: 'directory' }
8 verbose addLocalDirectory C:\Users\Negi\AppData\Roaming\npm-cache\firstnpmtest\1.0.0\package.tgz not in flight; packing
9 verbose correctMkdir C:\Users\Negi\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
10 info lifecycle firstnpmtest@1.0.0~prepublish: firstnpmtest@1.0.0
11 silly lifecycle firstnpmtest@1.0.0~prepublish: no script for prepublish, continuing
12 verbose tar pack [ 'C:\\Users\\Negi\\AppData\\Roaming\\npm-cache\\firstnpmtest\\1.0.0\\package.tgz',
12 verbose tar pack   'E:\\Mynpm Module\\dist' ]
13 verbose tarball C:\Users\Negi\AppData\Roaming\npm-cache\firstnpmtest\1.0.0\package.tgz
14 verbose folder E:\Mynpm Module\dist
15 verbose addLocalTarball adding from inside cache C:\Users\Negi\AppData\Roaming\npm-cache\firstnpmtest\1.0.0\package.tgz
16 verbose correctMkdir C:\Users\Negi\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
17 silly cache afterAdd firstnpmtest@1.0.0
18 verbose afterAdd C:\Users\Negi\AppData\Roaming\npm-cache\firstnpmtest\1.0.0\package\package.json not in flight; writing
19 verbose correctMkdir C:\Users\Negi\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
20 verbose afterAdd C:\Users\Negi\AppData\Roaming\npm-cache\firstnpmtest\1.0.0\package\package.json written
21 silly publish { name: 'firstnpmtest',
21 silly publish   version: '1.0.0',
21 silly publish   description: 'this is a tes',
21 silly publish   main: 'index.umd.js',
21 silly publish   'jsnext:main': 'index.esm.js',
21 silly publish   module: 'index.esm.js',
21 silly publish   types: 'index.d.ts',
21 silly publish   dependencies: { '@angular/core': '^4.2.5' },
21 silly publish   author: { name: 'suraj Negi' },
21 silly publish   license: 'ISC',
21 silly publish   readme: 'ERROR: No README data found!',
21 silly publish   _id: 'firstnpmtest@1.0.0',
21 silly publish   scripts: {},
21 silly publish   _shasum: '68d30c30b4d9f0712b73f919fd37de66de76527b',
21 silly publish   _from: '.' }
22 verbose getPublishConfig undefined
23 silly mapToRegistry name firstnpmtest
24 silly mapToRegistry using default registry
25 silly mapToRegistry registry https://registry.npmjs.org/
26 silly mapToRegistry data Result {
26 silly mapToRegistry   raw: 'firstnpmtest',
26 silly mapToRegistry   scope: null,
26 silly mapToRegistry   escapedName: 'firstnpmtest',
26 silly mapToRegistry   name: 'firstnpmtest',
26 silly mapToRegistry   rawSpec: '',
26 silly mapToRegistry   spec: 'latest',
26 silly mapToRegistry   type: 'tag' }
27 silly mapToRegistry uri https://registry.npmjs.org/firstnpmtest
28 verbose publish registryBase https://registry.npmjs.org/
29 silly publish uploading C:\Users\Negi\AppData\Roaming\npm-cache\firstnpmtest\1.0.0\package.tgz
30 verbose request uri https://registry.npmjs.org/firstnpmtest
31 verbose request sending authorization for write operation
32 info attempt registry request try #1 at 4:39:07 PM
33 verbose request using bearer token for auth
34 verbose request id 6c920e68649283d4
35 http request PUT https://registry.npmjs.org/firstnpmtest
36 http 403 https://registry.npmjs.org/firstnpmtest
37 verbose headers { 'content-type': 'application/json',
37 verbose headers   'cache-control': 'max-age=300',
37 verbose headers   'content-length': '106',
37 verbose headers   'accept-ranges': 'bytes',
37 verbose headers   date: 'Sun, 02 Jul 2017 16:39:09 GMT',
37 verbose headers   via: '1.1 varnish',
37 verbose headers   connection: 'keep-alive',
37 verbose headers   'x-served-by': 'cache-sin18023-SIN',
37 verbose headers   'x-cache': 'MISS',
37 verbose headers   'x-cache-hits': '0',
37 verbose headers   'x-timer': 'S1499013549.989805,VS0,VE902',
37 verbose headers   vary: 'Accept-Encoding' }
38 verbose request invalidating C:\Users\Negi\AppData\Roaming\npm-cache\registry.npmjs.org\firstnpmtest on PUT
39 error publish Failed PUT 403
40 verbose stack Error: you do not have permission to publish "firstnpmtest". Are you logged in as the correct user? : firstnpmtest
40 verbose stack     at makeError (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:302:12)
40 verbose stack     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:290:14)
40 verbose stack     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:210:14)
40 verbose stack     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:187:22)
40 verbose stack     at emitTwo (events.js:106:13)
40 verbose stack     at Request.emit (events.js:191:7)
40 verbose stack     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1048:10)
40 verbose stack     at emitOne (events.js:96:13)
40 verbose stack     at Request.emit (events.js:188:7)
40 verbose stack     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:969:12)
41 verbose statusCode 403
42 verbose pkgid firstnpmtest
43 verbose cwd E:\Mynpm Module\dist
44 error Windows_NT 10.0.10240
45 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "publish"
46 error node v6.11.0
47 error npm  v3.10.10
48 error code E403
49 error you do not have permission to publish "firstnpmtest". Are you logged in as the correct user? : firstnpmtest
50 error If you need help, you may report this error at:
50 error     <https://github.com/npm/npm/issues>
51 verbose exit [ 1, true ]

**Comment by kenany** [comment]
@ersurajnegi What is your npm account username?

**Comment by ersurajnegi** [comment]
I fixed it...the package was already being used...
Going to close this issue.

**Comment by KalpanaHV** [comment]
I had the same problem. There was already a package in npm repository with the same name. So, I changed my package name and it worked.
