### ISSUE TITLE
install ionic framework error Windows_NT 10.0.14393

### ISSUE THREAD

**Issue by phrombuncha** [npm/npm#17570]
I Use Window 10 64bit
Please help me. when I run command npm install -g ionic that display error :

C:\Windows\System32>npm install -g ionic

npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\Namo\AppData\Local\Temp\npm-6436-2318b77e\registry.npmjs.org\minimist\-\minimist-1.2.0.tgz.180224223' -> 'C:\Users\Namo\AppData\Local\Temp\npm-6436-2318b77e\registry.npmjs.org\minimist\-\minimist-1.2.0.tgz'
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ionic"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\Namo\AppData\Local\Temp\npm-6436-2318b77e\registry.npmjs.org\dargs\-\dargs-5.1.0.tgz.679815505' -> 'C:\Users\Namo\AppData\Local\Temp\npm-6436-2318b77e\registry.npmjs.org\dargs\-\dargs-5.1.0.tgz'
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ionic"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\Namo\AppData\Local\Temp\npm-6436-2318b77e\registry.npmjs.org\lodash\-\lodash-4.17.4.tgz.1089021496' -> 'C:\Users\Namo\AppData\Local\Temp\npm-6436-2318b77e\registry.npmjs.org\lodash\-\lodash-4.17.4.tgz'
npm ERR! Windows_NT 10.0.14393

**Comment by ciscoo** [comment]
As suggested in https://github.com/npm/npm/issues/13461, try running the command as admin or disable/uninstall anti malware.
