### ISSUE TITLE
npm install --from-git git@github:/blabla...

### ISSUE THREAD

**Issue by frankakouemo** [npm/npm#17581]
#### I'm opening this issue because:

  - [x] npm is producing an incorrect install.
- [ ] npm is crashing.
    - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/8.1.3/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--from-git',
1 verbose cli   'git@github.com:canalplus/mickey.js.git' ]
2 info using npm@3.10.8
3 info using node@v8.1.3
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData git@github.com:canalplus/mickey.js.git
8 silly fetchPackageMetaData Error: Unsupported URL Type: github.com:canalplus/mickey.js.git
8 silly fetchPackageMetaData     at parseUrl (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:186:13)
8 silly fetchPackageMetaData     at npa (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:79:12)
8 silly fetchPackageMetaData     at module.exports (/usr/local/lib/node_modules/npm/node_modules/realize-package-specifier/index.js:12:15)
8 silly fetchPackageMetaData     at fetchPackageMetadata (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:54:12)
8 silly fetchPackageMetaData     at /usr/local/lib/node_modules/npm/lib/install/deps.js:229:14
8 silly fetchPackageMetaData     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
8 silly fetchPackageMetaData     at Array.forEach (native)
8 silly fetchPackageMetaData     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
8 silly fetchPackageMetaData     at Array.forEach (native)
8 silly fetchPackageMetaData     at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
8 silly fetchPackageMetaData  error for git@github.com:canalplus/mickey.js.git Error: Unsupported URL Type: github.com:canalplus/mickey.js.git
8 silly fetchPackageMetaData     at parseUrl (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:186:13)
8 silly fetchPackageMetaData     at npa (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:79:12)
8 silly fetchPackageMetaData     at module.exports (/usr/local/lib/node_modules/npm/node_modules/realize-package-specifier/index.js:12:15)
8 silly fetchPackageMetaData     at fetchPackageMetadata (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:54:12)
8 silly fetchPackageMetaData     at /usr/local/lib/node_modules/npm/lib/install/deps.js:229:14
8 silly fetchPackageMetaData     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
8 silly fetchPackageMetaData     at Array.forEach (native)
8 silly fetchPackageMetaData     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
8 silly fetchPackageMetaData     at Array.forEach (native)
8 silly fetchPackageMetaData     at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
9 silly rollbackFailedOptional Starting
10 silly rollbackFailedOptional Finishing
11 silly runTopLevelLifecycles Finishing
12 silly install printInstalled
13 verbose stack Error: Unsupported URL Type: github.com:canalplus/mickey.js.git
13 verbose stack     at parseUrl (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:186:13)
13 verbose stack     at npa (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:79:12)
13 verbose stack     at module.exports (/usr/local/lib/node_modules/npm/node_modules/realize-package-specifier/index.js:12:15)
13 verbose stack     at fetchPackageMetadata (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:54:12)
13 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/deps.js:229:14
13 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
13 verbose stack     at Array.forEach (native)
13 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
13 verbose stack     at Array.forEach (native)
13 verbose stack     at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
14 verbose cwd /Users/frank/Desktop/devCanalOverseas/testX2/x1-webapp
15 error Darwin 16.6.0
16 error argv "/usr/local/Cellar/node/8.1.3/bin/node" "/usr/local/bin/npm" "install" "--from-git" "git@github.com:canalplus/mickey.js.git"
17 error node v8.1.3
18 error npm  v3.10.8
19 error Unsupported URL Type: github.com:canalplus/mickey.js.git
20 error If you need help, you may report this error at:
20 error     <https://github.com/npm/npm/issues>

### supporting information:

 - `npm -v` prints: 3.10.8
 - `node -v` prints: v8.1.3
 - `npm config get registry` prints:  https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Mac OS
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by zkat** [comment]
Heads up: `--from-git` is not an npm option.

This is the command you probably want: `npm install github:canalplus/mickey.js`.

Cheers.
