### ISSUE TITLE
npm start giving errors 

### ISSUE THREAD

**Issue by brunaw** [npm/npm#17596]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [X] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
When trying `npm start`, I get:

```
npm ERR! Linux 4.4.0-21-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! path /home/bruna/Dropbox/PET/Site/jekyllDecent/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/home/bruna/Dropbox/PET/Site/jekyllDecent/package.json'
npm ERR! enoent ENOENT: no such file or directory, open '/home/bruna/Dropbox/PET/Site/jekyllDecent/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/bruna/Dropbox/PET/Site/jekyllDecent/npm-debug.log

```
#### How can the CLI team reproduce the problem?

I just installed `npm` and runned `npm start`. 

### supporting information:

 - `npm -v` prints: 3.5.2
 - `node -v` prints: v4.2.6
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux Mint. 
 - Network issues:
   - Geographic location where npm was run:
   - [X] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
Does `/home/bruna/Dropbox/PET/Site/jekyllDecent/package.json` exist?

**Comment by brunaw** [comment]
No. But it should exist?

**Comment by kenany** [comment]
Yeah, so the way `npm start` works is that it'll read the `package.json` in your current directory and run the `"start"` script that you have defined. Since you don't have a `package.json` in your current directory, `npm` is throwing this error. You can quickly generate a `package.json` by using `npm init`. From there, you'll then want to edit the file to add your `"start"` script. See <https://docs.npmjs.com/misc/scripts> for more information on writing scripts.
