### ISSUE TITLE
Unable to produce pre-5 `npm install` ouptut

### ISSUE THREAD

**Issue by BanzaiMan** [npm/npm#17594]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?

With npm 5 and later, `npm install` no longer prints the dependency tree when it resolves the dependencies.

Compare https://travis-ci.org/chalk/chalk/jobs/248527901#L130 (Node 8 + npm 5) and https://travis-ci.org/chalk/chalk/jobs/248527902#L127 (Node 6 + npm 3.10).

https://docs.npmjs.com/misc/config#loglevel says the valid `loglevel` values are `silent`, `error`, `warn`, `http`, `info`, `verbose`, `silly`, which `warn` being the default. Assuming that the later values mean *more* output, we should check `http`, `info`, `verbose`, `silly`. Unfortunately, using chalk/chalk as an example, none of these log levels match the previous default.

See https://github.com/travis-ci/travis-ci/issues/7991 for more discussion.

#### How can the CLI team reproduce the problem?

```sh-session
$ git clone https://github.com/chalk/chalk.git chalk/chalk
$ cd chalk/chak
$ nvm install 8 # if you have nvm. Otherwise, make sure that npm is 5+.
$ npm install
```

### supporting information:

 - `npm -v` prints: `v8.1.3`
 - `node -v` prints: `5.0.3`
 - `npm config get registry` prints: `undefined`
 - Windows, OS X/macOS, or Linux?: OS X

**Comment by zkat** [comment]
This is as intended.

If you want the original output, use `npm i && npm ls`.

If you want to use this for programmatic reasons, use `npm i --json`, which prints out all the packages that were added.

The old output wasn't just noisy, but confusing unless you were either only adding one new package to an existing install, or doing `npm i` with an empty `node_modules`.

hope this helps~
