### ISSUE TITLE
I am new to nodejs i tried to view the npm but shows this error

### ISSUE THREAD

**Issue by haiderraavi** [npm/npm#17605]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'view',
1 verbose cli   'underscore' ]
2 info using npm@3.10.10
3 info using node@v6.11.0
4 silly mapToRegistry name underscore
5 silly mapToRegistry using default registry
6 silly mapToRegistry registry https://registry.npmjs.org/
7 silly mapToRegistry data Result {
7 silly mapToRegistry   raw: 'underscore',
7 silly mapToRegistry   scope: null,
7 silly mapToRegistry   escapedName: 'underscore',
7 silly mapToRegistry   name: 'underscore',
7 silly mapToRegistry   rawSpec: '',
7 silly mapToRegistry   spec: 'latest',
7 silly mapToRegistry   type: 'tag' }
8 silly mapToRegistry uri https://registry.npmjs.org/underscore
9 verbose request uri https://registry.npmjs.org/underscore
10 verbose request no auth needed
11 info attempt registry request try #1 at 4:11:36 PM
12 verbose request id 5658b16925459654
13 http request GET https://registry.npmjs.org/underscore
14 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
15 info attempt registry request try #2 at 4:11:46 PM
16 http request GET https://registry.npmjs.org/underscore
17 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
18 info attempt registry request try #3 at 4:12:46 PM
19 http request GET https://registry.npmjs.org/underscore
20 verbose stack Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
20 verbose stack     at Object.exports._errnoException (util.js:1018:11)
20 verbose stack     at errnoException (dns.js:33:15)
20 verbose stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
21 verbose cwd C:\Users\syed.mohdhaiderali\Tutorial\node.js\myfirstprogram
22 error Windows_NT 6.3.9600
23 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "view" "underscore"
24 error node v6.11.0
25 error npm  v3.10.10
26 error code EAI_AGAIN
27 error errno EAI_AGAIN
28 error syscall getaddrinfo
29 error getaddrinfo EAI_AGAIN registry.npmjs.org:443
30 error If you need help, you may report this error at:
30 error     <https://github.com/npm/npm/issues>
31 verbose exit [ 1, true ]

**Comment by Groot90** [comment]
Looks like a problem related to proxy / network settings. Check this thread:
https://github.com/npm/npm/issues/11308
