### ISSUE TITLE
missing script: bulid

### ISSUE THREAD

**Issue by sunlibao** [npm/npm#17603]
0 info it worked if it ends with ok
1 verbose cli [ 'E:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'E:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'bulid' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 verbose stack Error: missing script: bulid
4 verbose stack     at run (E:\Program Files\nodejs\node_modules\npm\lib\run-script.js:151:19)
4 verbose stack     at E:\Program Files\nodejs\node_modules\npm\lib\run-script.js:61:5
4 verbose stack     at E:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:356:5
4 verbose stack     at checkBinReferences_ (E:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:320:45)
4 verbose stack     at final (E:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:354:3)
4 verbose stack     at then (E:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:124:5)
4 verbose stack     at E:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:243:12
4 verbose stack     at E:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
4 verbose stack     at tryToString (fs.js:455:3)
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
5 verbose cwd F:\vueProjiects\my-vue-progect
6 error Windows_NT 10.0.14393
7 error argv "E:\\Program Files\\nodejs\\node.exe" "E:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "bulid"
8 error node v6.9.1
9 error npm  v3.10.8
10 error missing script: bulid
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

**Comment by kenany** [comment]
Hello! So, the way `npm run build` works is that it looks in your current `package.json` for a defined `"build"` [script](https://docs.npmjs.com/misc/scripts), and then runs that. The error message you're seeing is trying to tell you that you have not defined a `"build"` script in your `package.json`, hence `npm run build` has no idea what you want it to do.

To solve this issue, all you have to do is add a new script to your `package.json`. It might look something like this, for example:

``` json
{
  "name": "package-name",
  "version": "1.0.0",
  "description": "package description",
  "scripts": {
    "build": "node --version",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {},
  "devDependencies": {}
}
```

Note how this `package.json` has a `"build"` script that runs `node --version`. You'll definitely want to change the command to whatever is most appropriate for your project.

Let me know if you run into any further `npm` issues :)

**Comment by karthiktohelp** [comment]
{
  "name": "package-name",
  "version": "1.0.0",
  "description": "package description",
  "scripts": {
    **"build": "babel index.js -o app.js",**        <----------------(add this)
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {},
  "devDependencies": {}
}


for complete document , visit 
http://androidrealtimeexamples.blogspot.in/2017/06/koa2-with-node-js-examples-writing-post.html
