### ISSUE TITLE
Bug while trying to manage package owners after migrating an account to an org

### ISSUE THREAD

**Issue by klzns** [npm/npm#17609]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I can't add or remove any owner from a package.

#### How can the CLI team reproduce the problem?
I had an account named "vtex".
I converted it to an organization here: https://www.npmjs.com/org/upgrade
The account name changed from "vtex" to "vtexlab"
I have a package called "vtex" that the user "vtex" is an owner.
I can't add or remove any owner from the package "vtex", it gives me the following error:

Log of errors while trying to add a new owner:
https://gist.github.com/brenoc/14dc71a697aadbd11c4414eb26e388a3

Log of errors while trying to remove the old user "vtex":
https://gist.github.com/brenoc/32628a00c2830f327bf444a5cfe071ea

### supporting information:

 - `npm -v` prints: 3.10.9
 - `node -v` prints: v7.2.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS
 - Network issues:
   - Geographic location where npm was run: Brazil
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by zkat** [comment]
@brenoc This repo is exclusively for the npm CLI. Please email support@npmjs.com or open an issue over at https://github.com/npm/registry
