### ISSUE TITLE
I may be misunderstanding.  Or, `package-lock.json` might have just killed my build.

### ISSUE THREAD

**Issue by StoneCypher** [npm/npm#17619]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I don't entirely know.

What I do know is that the `travis-ci` build of my library, which runs the same steps as my local copy, started failing hard on `npm ls` this morning, despite no changes to the repo other than an added test case

I nuked `node_modules` and reinstalled; the only change to my `package-lock.json` was the version of my own library as listed.  Pushed that; no change.

So, I removed `package-lock.json` and pushed again.  Suddenly everything works again?

[You can see the problem in build 111.1 on line 791](https://travis-ci.org/StoneCypher/jssm/jobs/250411327).  For the life of me I can't figure out what's going on here.  IRC recommended to me to open a bug.

#### How can the CLI team reproduce the problem?

I don't know.  `npm ls` works fine locally.

I feel like I didn't do a very good job with this bug report.  If you'll advise what more I could say, I will

**Comment by AlexBeauchemin** [comment]
I got a similar problem where dependencies were randomly disappearing/not installing.

Solved it by removing the npm prune from `npm prune && npm i`

### Step to reproduce :
- delete `package-lock.json`
- `rm -rf node_modules/`
- `npm cache clean --force`
- `npm prune && npm i`
- start the project

### Result : 
```
scripts/db-migration.ts(1,27): error TS2307: Cannot find module 'minimist'.
scripts/db-migration.ts(2,25): error TS2307: Cannot find module 'moment'.
```
Even if the modules are in package.json, they are not added to the package-lock.json and missing from the node_module folder.

### Fix:
Replace `npm prune && npm i` by `npm i` (remove the npm prune)

**Comment by StoneCypher** [comment]
except this happened in the middle of node-modules being untouched

does this mean i have to prune and reinstall before every push?

**Comment by zkat** [comment]
Please update to `npm@5.1.0` -- I believe this should be fixed in that version.

**Comment by StoneCypher** [comment]
I have found out that this was actually the result of a change to travis.  A user requested that they add `npm ls` to their general node flow, and `npm ls` faults when there are dependencies it can't place.

Travis has modified the `ls` to no longer pay attention to whether it succeeds, and the problem has gone away.

I apologize for consuming this time on your part.
