### ISSUE TITLE
npm install Unhandled rejection Error on macOS

### ISSUE THREAD

**Issue by fpegios** [npm/npm#17612]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [X] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I have a package.json file and running npm install to load the dependencies. While on Windows everything works perfectly, when running the command, on macOS I am getting that error.

> npm WARN deprecated lodash.isarray@4.0.0: This package is deprecated. Use Array.isArray.
Unhandled rejection Error: Argument #2: Expected string but got null is-fullwidth-code-point@^1.0.0 fetched in 35ms

#### How can the CLI team reproduce the problem?

Try running npm install on mac using this package.json file

> {
  "name": "ng-gavr",
  "version": "1.0.0",
  "description": "",
  "main": "index.html",
  "scripts": {
    "test": "browser-sync start --server --files \"index.html\" \"scripts/*.js\" \"styles/*.css\" \"views/*.html\""
  },
  "author": "fpegios",
  "license": "ISC",
  "dependencies": {
    "angular": "^1.6.4",
    "angular-animate": "^1.6.4",
    "angular-route": "^1.6.4",
    "angular-ui-router": "^1.0.3",
    "bootstrap": "^3.3.7",
    "browser-sync": "^2.18.12",
    "font-awesome": "^4.7.0",
    "jquery": "^3.2.1"
  }
}

      

### supporting information:

 - debug.log
[debug.txt](https://github.com/npm/npm/files/1123075/debug.txt)

**Comment by kenany** [comment]
Does `/Users/darrenwilson/package.json` exist? Is that the `package.json` that you've provided?

**Comment by fpegios** [comment]
Yes, it exists. It's the code I've provided.
