### ISSUE TITLE
npm prune is messing the npm install and package-lock.json resulting in missing modules

### ISSUE THREAD

**Issue by AlexBeauchemin** [npm/npm#17620]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

When using `npm prune && npm i`, some packages from package.json are not installed but added to package-lock.json

#### How can the CLI team reproduce the problem?

Using npm 5.0.3 on macOs Sierra AND ubuntu 14.04

- `delete package-lock.json`
- `rm -rf node_modules/`
- `npm cache clean --force`
- `npm prune && npm i`
- start the project

Result :

scripts/db-migration.ts(1,27): error TS2307: Cannot find module 'minimist'.
scripts/db-migration.ts(2,25): error TS2307: Cannot find module 'moment'.

Even if the modules are in package.json, they are not installed (missing from the node_module folder) but added to the package-lock.json.

Fix:
Replace `npm prune && npm i` by npm i (remove the npm prune)

**Comment by zkat** [comment]
I believe this is fixed by #16637. There might also be other commits in the latest npm release that fix this. Could you upgrade to `npm@5.1.0` and try again?

**Comment by AlexBeauchemin** [comment]
Yes that fixed it. Thanks!
