### ISSUE TITLE
Bug: Cannot install latest Github repo branch globally

### ISSUE THREAD

**Issue by ORESoftware** [npm/npm#17623]
I am on NPM version 4.6.1. I tried upgrading to 5.0.3, but I saw some problems, so I downgraded back to 4.6.1.

#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I want to install the latest version from this github branch

 npm install -g github:sumanjs/suman#rebase_branch

It looks like it may be either using the master branch, or it's not even using Github, but just pulling the name from package.json and then installing via NPM? I can't tell. In any case, it's not using that branch.

When I install locally, it does use the correct branch, but **not** when installing globally.

#### How can the CLI team reproduce the problem?

` npm install -g github:sumanjs/suman#rebase_branch`

Try creating some changes on a branch other than master, then installing that package globally and it should not pick up the changes.

**Comment by zkat** [comment]
I can't reproduce this on the latest version of npm. Please try updating to `npm@5.1.0`, which got released today.

**Comment by ORESoftware** [comment]
@zkat  my guess it's that it should be:

`npm install -g "github:sumanjs/suman#rebase_branch"`

instead of 

`npm install -g github:sumanjs/suman#rebase_branch`

`#` is a comment after all
