### ISSUE TITLE
npm install package with same name as dir fails

### ISSUE THREAD

**Issue by ghost** [npm/npm#17638]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
node 8.1.3 npm 5.1.0

$ mkdir express && cd express
$ npm init -y
$ npm i express

This doesn't install express

**Comment by zkat** [comment]
This is not supported by npm, and has not been supported for as long as I remember.

Try changing the name of the package in the `package.json` created by `npm init -y` and you should be good.

Please see https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm for more details about this.
