### ISSUE TITLE
package dependencies go missing when updating

### ISSUE THREAD

**Issue by SomeHats** [npm/npm#17639]
Thank you for npm 💜✨
I noticed this with 5.0.x and found it was still an issue in 5.1.0 so thought I'd let you know :)

#### I'm opening this issue because:
  - npm is producing an incorrect install.

#### What's going wrong?
[next](https://github.com/zeit/next.js)@2 depends on webpack 2. next@3 depends on webpack 3.

With my project on next@2, I can run `npm ls webpack` and get:
```
tmp@1.0.0 /Users/somehats/Projects/tmp
└─┬ next@2.4.6
  └── webpack@2.5.1
```
I can also successfully run `next build`.

If I run `npm i next@beta`, I get:
```
> uglifyjs-webpack-plugin@0.4.6 postinstall /Users/somehats/Projects/tmp/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js

npm WARN uglifyjs-webpack-plugin@0.4.6 requires a peer of webpack@^1.9 || ^2 || ^2.1.0-beta || ^2.2.0-rc || ^3.0.0 but none was installed.
npm WARN tmp@1.0.0 No description
npm WARN tmp@1.0.0 No repository field.

+ next@3.0.1-beta.9
added 56 packages, removed 105 packages, updated 1 package and moved 7 packages in 10.159s
```

Now, running `npm ls webpack` gives:
```
tmp@1.0.0 /Users/somehats/Projects/tmp
└── (empty)
```
and `next build` fails as it can't find webpack.

The only thing that seems to fix things is `rm -rf node_modules package-lock.json && npm i`. After that, `npm ls webpack` gives:
```
tmp@1.0.0 /Users/somehats/Projects/tmp
└─┬ next@3.0.1-beta.9
  └── webpack@3.0.0
```
and `next build` runs successfully.

#### How can the CLI team reproduce the problem?
Start with this package.json:
```json
{
  "name": "tmp",
  "version": "1.0.0",
  "dependencies": {
    "next": "2",
    "react": "^15.6.1",
    "react-dom": "^15.6.1"
  }
}
```
Run `npm i`. `npm ls webpack` should show webpack as above. Run `npm i next@beta`. Now `npm ls webpack` should give 'empty'.

### supporting information:

 - `npm -v` prints: 5.1.0
 - `node -v` prints: v8.1.2
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by zkat** [comment]
Thanks for the excellent report! This is a pretty easy repro.

The bizarre thing is that `webpack@3` is actually in the `package-lock.json` but isn't being installed for some reason. 🤔

**Comment by iarna** [comment]
So, it turns out `webpack@3` _was_ being installed, but was being installed deeper in the tree due to a bug in package updating. This resulted in the flattened peer dep failing.

Fixing this will be split into two parts:

1. Keep things flat on update.
2. Make sure things that require peer deps can see the peer deps.
3. An `ls` bug that makes hides things in the tree that are peer dependencies when searching.

**Comment by Meligy** [comment]
I might be seeing something related to this.

I have the `@angular/cli` in `devDependencies`. It depends on `webpack` and I can confirm `npm` pulls it in by running `cat node_modules/webpack/package.json` after `npm install`. However, after upgrading to `npm 5.2`, in a new project, when I run `npm ls webpack`, it says it's not found, even when using the `-dev` flag.

Does this sound like the same thing or a different issue?

Thanks.
