### ISSUE TITLE
npm repo npm fails

### ISSUE THREAD

**Issue by evanlucas** [npm/npm#17642]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?

`npm repo npm` worked on the previous version of npm (5.0.3) and now does not.

#### How can the CLI team reproduce the problem?

```bash
$ npm install -g npm@5.1.0 && npm repo npm
```

log output:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'repo',
1 verbose cli   'npm',
1 verbose cli   '-ddd' ]
2 info using npm@5.1.0
3 info using node@v8.1.3
4 verbose config Skipping project config: /Users/evan/.npmrc. (matches userconfig)
5 verbose npm-session xxxxxxxxxxxxxxx
6 http fetch GET 200 https://registry.npmjs.org/npm 35ms (from cache)
7 silly pacote tag manifest for npm@latest fetched in 72ms
8 verbose stack Error: no repository
8 verbose stack     at getUrlAndOpen (/usr/local/lib/node_modules/npm/lib/repo.js:27:21)
8 verbose stack     at /usr/local/lib/node_modules/npm/lib/repo.js:21:5
8 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/call-limit/call-limit.js:22:12
8 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:95:7)
8 verbose stack     at process._tickCallback (internal/process/next_tick.js:161:9)
9 verbose cwd /Users/evan
10 verbose Darwin 16.6.0
11 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "repo" "npm" "-ddd"
12 verbose node v8.1.3
13 verbose npm  v5.1.0
14 error no repository
15 verbose exit [ 1, true ]

```

### supporting information:

 - `npm -v` prints: 5.1.0
 - `node -v` prints: 8.1.3
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS
 - Network issues:
   - Geographic location where npm was run: Austin, TX
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by junosuarez** [comment]
This works on my machine (macOS / node@8.1.3 / npm@5.1.0):
```
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'repo',
npm verb cli   'npm',
npm verb cli   '--loglevel=silly' ]
npm info using npm@5.1.0
npm info using node@v8.1.3
npm verb npm-session 6685ede5e4a98d13
npm http fetch GET 200 https://registry.npmjs.org/npm 93ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/npm/-/npm-5.1.0.tgz 22ms (from cache)
npm sill pacote tag manifest for npm@latest fetched in 630ms
npm verb exit [ 0, true ]
npm info ok
```

**Comment by evanlucas** [comment]
This is now working for me. Thanks!
