### ISSUE TITLE
npm@5 prepare script not getting called when a git module is installed as dependency

### ISSUE THREAD

**Issue by Fconstant** [npm/npm#17646]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
`npm@5` changelog states that:

> Git dependencies with prepare scripts will have their devDependencies installed, and npm install run in their directory before being packed.

[Source](http://blog.npmjs.org/post/161081169345/v500)

And I have a module that has a `prepare` script on `package.json`, and `typescript@2.3` as a `devDependency`.
Inside `prepare` script I execute the `typescript`'s `tsc` compiler.
I expected that, after `npm install`ing everything, all my `devDependencies` would have been installed, and then the `prepare` script gets called, and finally my module gets installed and compiled with `typescript`.
But it actually doesn't happen.

### npm install log with -dd

```bash
$ npm install git+https://github.com/Fconstant/npm5test.git#prepare -dd

npm info it worked if it ends with ok
npm verb cli [ '/usr/local/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'install',
npm verb cli   'git+https://github.com/Fconstant/npm5test.git#prepare',
npm verb cli   '-dd' ]
npm info using npm@5.1.0
npm info using node@v8.1.3
npm verb npm-session 44b917df80efcf26
npm WARN install Usage of the `--dev` option is deprecated. Use `--only=dev` instead.
npm verb prepareGitDep git+https://github.com/Fconstant/npm5test.git#prepare: installing devDeps and running prepare script.
npm info lifecycle other-module@1.0.0~prepack: other-module@1.0.0
npm verb tar pack [ '/var/folders/xl/gzymdllx4rx_82xt08jjths80000gq/T/npm-13954-8a00b73f/tmp/packing-cfa96a9c/package.tgz',
npm verb tar pack   '/Users/fcconstantino/.npm/_cacache/tmp/git-clone-3e6efa6a' ]
npm verb tarball /var/folders/xl/gzymdllx4rx_82xt08jjths80000gq/T/npm-13954-8a00b73f/tmp/packing-cfa96a9c/package.tgz
npm verb folder /Users/fcconstantino/.npm/_cacache/tmp/git-clone-3e6efa6a
npm info lifecycle other-module@1.0.0~postpack: other-module@1.0.0
npm verb correctMkdir /Users/fcconstantino/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /Users/fcconstantino/.npm/_locks/staging-0a2e89fd6d8ad45d.lock for /Users/fcconstantino/Projects/@temp/core-test/node_modules/.staging
npm info lifecycle other-module@1.0.0~preinstall: other-module@1.0.0
npm info linkStuff other-module@1.0.0
npm verb linkBins other-module@1.0.0
npm verb linkMans other-module@1.0.0
npm info lifecycle other-module@1.0.0~install: other-module@1.0.0
npm info lifecycle other-module@1.0.0~postinstall: other-module@1.0.0
npm verb unlock done using /Users/fcconstantino/.npm/_locks/staging-0a2e89fd6d8ad45d.lock for /Users/fcconstantino/Projects/@temp/core-test/node_modules/.staging
npm verb saving [ { name: 'other-module',
npm verb saving     spec: 'git+https://github.com/Fconstant/npm5test.git#prepare',
npm verb saving     save: 'dependencies' } ]
npm info lifecycle undefined~preshrinkwrap: undefined
npm info lifecycle undefined~shrinkwrap: undefined
npm info lifecycle undefined~postshrinkwrap: undefined
npm WARN core-test@1.0.0 No description
npm WARN core-test@1.0.0 No repository field.

+ other-module@1.0.0
added 1 package in 4.047s
npm verb exit [ 0, true ]
npm info ok 
```

Even though `npm verb prepareGitDep git+https://github.com/Fconstant/npm5test.git#prepare: installing devDeps and running prepare script.` gets printed, my `prepare` script stated on my `package.json`doesn't get called.

### supporting information:

 - `npm -v` prints: 5.1.0
 - `node -v` prints: 8.1.3
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS Sierra
 - Network issues:
   - Geographic location where npm was run: Brazil, São Paulo
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by Fconstant** [comment]
## UPDATE
Not actually a problem.
`prepare` gets called correctly. It was my mistake. Sorry.
Closing issue 👍

**Comment by mturley** [comment]
@Fconstant, what were the circumstances around why this was happening?  I'm running into the same problem.

**Comment by Fconstant** [comment]
@mturley The prepare script was getting called as expected, the problem was on my node script, that was not doing what it was supposed to do.
Tested on `npm@5.3.0`, and it's working.

Log of `npm i git+https://github.com/Fconstant/npmTest.git -dd` on another project
```shell
Autbanks-Mac-mini:something fcconstantino$ npm i git+https://github.com/Fconstant/npmTest.git -dd
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'i',
npm verb cli   'git+https://github.com/Fconstant/npmTest.git',
npm verb cli   '-dd' ]
npm info using npm@5.3.0
npm info using node@v8.1.3
npm verb npm-session 6816343ef2b1d43f
npm verb prepareGitDep git+https://github.com/Fconstant/npmTest.git: installing devDeps and running prepare script.
npm info lifecycle npm-test@1.0.0~prepack: npm-test@1.0.0
npm verb tar pack [ '/var/folders/xl/gzymdllx4rx_82xt08jjths80000gq/T/npm-2682-055a56f4/tmp/packing-a5b95196/package.tgz',
npm verb tar pack   '/Users/fcconstantino/.npm/_cacache/tmp/git-clone-940bb44d' ]
npm verb tarball /var/folders/xl/gzymdllx4rx_82xt08jjths80000gq/T/npm-2682-055a56f4/tmp/packing-a5b95196/package.tgz
npm verb folder /Users/fcconstantino/.npm/_cacache/tmp/git-clone-940bb44d
npm info lifecycle npm-test@1.0.0~postpack: npm-test@1.0.0
npm verb correctMkdir /Users/fcconstantino/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /Users/fcconstantino/.npm/_locks/staging-270ff7a85074a0d0.lock for /Users/fcconstantino/Projects/@temp/something/node_modules/.staging
npm info lifecycle npm-test@1.0.0~preinstall: npm-test@1.0.0
npm info linkStuff npm-test@1.0.0
npm verb linkBins npm-test@1.0.0
npm verb linkMans npm-test@1.0.0
npm info lifecycle npm-test@1.0.0~install: npm-test@1.0.0
npm info lifecycle npm-test@1.0.0~postinstall: npm-test@1.0.0
npm verb unlock done using /Users/fcconstantino/.npm/_locks/staging-270ff7a85074a0d0.lock for /Users/fcconstantino/Projects/@temp/something/node_modules/.staging
npm verb saving [ { name: 'npm-test',
npm verb saving     spec: 'git+https://github.com/Fconstant/npmTest.git',
npm verb saving     save: 'dependencies' } ]
npm info lifecycle undefined~preshrinkwrap: undefined
npm info lifecycle undefined~shrinkwrap: undefined
npm info lifecycle undefined~postshrinkwrap: undefined
npm WARN something@1.0.0 No description
npm WARN something@1.0.0 No repository field.

+ npm-test@1.0.0
added 1 package in 6.079s
npm verb exit [ 0, true ]
npm info ok 
```
Notice the `npm verb prepareGitDep git+https://github.com/Fconstant/npmTest.git: installing devDeps and running prepare script.` line.

It seems like you need to have at least one dev dependency to work.
When I tested with no dependencies at all, strangely, it didn't work.

[My test project](https://github.com/Fconstant/npmTest)

**Comment by frangio** [comment]
Your test project is not running the prepare script for me.

npm@5.5.1 on Linux.

**Comment by Fconstant** [comment]
@frangio, I changed the `testScript.js` so it can now write a simple txt file. It seems that `console.log` is not working (don't know why).

Try `npm i git+https://github.com/Fconstant/npmTest.git` again.
If you see a `test.txt` on `node_modules/npm-test/`, then it's working.

Working for me on MacOS Sierra (`npm@5.5.1`).

**Comment by frangio** [comment]
You're right @Fconstant, I'm seeing the file now. But it's odd that the verbose output doesn't show `prepare` being run... And I still can't get it to work with a package of my own

**Comment by Fconstant** [comment]
@frangio Can I see your package?

I did some tests, that you can see in other branches:
- I tried to do the same, but without `devDeps` to my `npm-test` package ([See this branch here](https://github.com/Fconstant/npmTest/tree/remove/devDeps))
- Then I tried to install 2 new `devDeps`, that aren't node packages (fs, path, etc.), one from npm registry, and another as a git dep. And then, call them in my `testScript.js` ([See this branch here](https://github.com/Fconstant/npmTest/tree/install/anotherDevDep)).

Both worked fine

**Comment by frangio** [comment]
I finally found what my problem was. My prepare script's result (a `build.js` file) was being ignored due to #18461.

After working around that issue I can see that it's being run!

Thanks for the help, @Fconstant.

**Comment by Fconstant** [comment]
You're welcome :+1:
