### ISSUE TITLE
Could not install Angular/cli using npm. Full log:

### ISSUE THREAD

**Issue by sergliss** [npm/npm#17649]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\194532222\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   '@angular/cli@latest' ]
2 info using npm@5.1.0
3 info using node@v6.9.1
4 verbose npm-session 69649afc5a31d108
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData error for @angular/cli@latest request to http://registry.npmjs.org/@angular%2fcli failed, reason: write EPROTO 101057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:794:
8 verbose type system
9 verbose stack FetchError: request to http://registry.npmjs.org/@angular%2fcli failed, reason: write EPROTO 101057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:794:
9 verbose stack
9 verbose stack     at ClientRequest.req.on.err (C:\Users\194532222\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\src\index.js:68:14)
9 verbose stack     at emitOne (events.js:96:13)
9 verbose stack     at ClientRequest.emit (events.js:188:7)
9 verbose stack     at TLSSocket.socketErrorListener (_http_client.js:310:9)
9 verbose stack     at emitOne (events.js:96:13)
9 verbose stack     at TLSSocket.emit (events.js:188:7)
9 verbose stack     at onwriteError (_stream_writable.js:345:10)
9 verbose stack     at onwrite (_stream_writable.js:363:5)
9 verbose stack     at WritableState.onwrite (_stream_writable.js:89:5)
9 verbose stack     at fireErrorCallbacks (net.js:468:13)
9 verbose stack     at TLSSocket.Socket._destroy (net.js:509:3)
9 verbose stack     at WriteWrap.afterWrite (net.js:801:10)
10 verbose cwd C:\Users\194532222
11 verbose Windows_NT 6.1.7601
12 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\194532222\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli@latest"
13 verbose node v6.9.1
14 verbose npm  v5.1.0
15 error code EPROTO
16 error errno EPROTO
17 error request to http://registry.npmjs.org/@angular%2fcli failed, reason: write EPROTO 101057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:794:
18 verbose exit [ 1, true ]

**Comment by sergliss** [comment]
Submitted by mistake

**Comment by sergliss** [comment]
Proxies are set via npm config set proxy

**Comment by zkat** [comment]
@sergliss can you repro this with `npm@4`, too?

**Comment by sergliss** [comment]
I installed the latest npm 5.1.0. Now I am getting different errors.

C:\Users\11111>npm install -g @angular/cli@latest
npm ERR! code EPROTO
npm ERR! errno EPROTO
npm ERR! request to http://registry.npmjs.org/@angular%2fcli failed, reason: write EPROTO 101057795:
error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:794:
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\11111\AppData\Roaming\npm-cache\_logs\2017-07-06T19_31_33_932Z-debug.log

C:\Users\11111>npm -v
5.1.0

**Comment by jotatoledo** [comment]
same problem, downgraded from 5.1.0 to 4.6.1 :/

**Comment by sergliss** [comment]
Currently node=v.6.2.1 and npm=v.3.9.3 as I had no choice to install. What would be the correct npm command to downgrade to 4.6.1?

**Comment by sergliss** [comment]
Currently node=v.6.2.1 and npm=v.3.9.3 as I had no choice to install. What would be the correct npm command to downgrade to 4.6.1?

**Comment by Raouf87** [comment]
This command worked for me in addition to the usual set-proxy command:

npm config set https-proxy http://yours.com:1234
