### ISSUE TITLE
Custom shell: incorrect behavior 

### ISSUE THREAD

**Issue by poteirard** [npm/npm#17641]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [X] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### How can the CLI team reproduce the problem?

In Windows, I tried the new feature of allowing custom shell: https://github.com/npm/npm/pull/16687

I have the following scripts:

```
"scripts": {
    "prestart": "if ! [ -d 'node_modules' ]; then npm install; fi && babel-node src/app/server/bootstrap.js",
    "start": "npm-run-all --parallel test:watch open:src lint:watch",
    "open:src": "babel-node src/app/server/index.js",
    "lint": "node_modules/.bin/esw webpack.config.* app",
    "lint:watch": "npm run lint -- --watch",
    "test": "jest",
    "test:watch": "npm run test -- --watch"
  },
```

I set up the custom shell:

` npm config set script-shell "C:\Program Files\Git\git-bash.exe"
`

When I execute `npm start -s`  it opens multiple git-bash.exe shells but they are being close.

1. I don't think it's the correct behavior as if you are developing with hot reloading you are not going to see the results. 

2. Some of the commands fails because it doesn't detect the binaries: npm-run-all, babel-node, jest...

### supporting information:

 - `npm -v` prints:
5.1.0
 - `node -v` prints:
6.11
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
Windows

Thank you for your great work ! :)

**Comment by aikar** [comment]
@poteirard try `npm config set script-shell bash`? Let it rely on what is in path instead. This worked fine for my peers.

I think your invoking the GUI part of the process is the issue with the path you are using.
