### ISSUE TITLE
Unable to run "docker-compose up"

### ISSUE THREAD

**Issue by prasadnn** [npm/npm#17640]
#### I'm opening this issue because:

  - [ ] npm is crashing. 
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Hi, I am having Windows 10 OS, I have installed docker, I am trying to run the "docker-compose up" in the "Docker Quickstart Terminal" and it is getting terminated by throwing error. 

#### How can the CLI team reproduce the problem?
Run the "docker-compose up" command in the "Docker Quickstart Terminal"

Please find the error information that I got in the terminal while running the "docker-compose up" command, Also the log file didn't got generated as told in the below information.  
//Start

myapp_1    | npm ERR! Linux 4.4.74-boot2docker
myapp_1    | npm ERR! argv "/opt/bitnami/node/bin/node" "/opt/bitnami/node/bin/npm" "install"
myapp_1    | npm ERR! node v7.7.4
myapp_1    | npm ERR! npm  v4.2.0
myapp_1    | npm ERR! path ../acorn/bin/acorn
myapp_1    | npm ERR! code EPROTO
myapp_1    | npm ERR! errno -71
myapp_1    | npm ERR! syscall symlink
myapp_1    |
myapp_1    | npm ERR! EPROTO: protocol error, symlink '../acorn/bin/acorn' -> '/app/node_modules/.bin/acorn'
myapp_1    | npm ERR!
myapp_1    | npm ERR! If you need help, you may report this error at:
myapp_1    | npm ERR!     <https://github.com/npm/npm/issues>
myapp_1    |
myapp_1    | npm ERR! Please include the following file with any support request:
myapp_1    | npm ERR!     /home/bitnami/.npm/_logs/2017-07-06T10_44_46_690Z-debug.log

//End

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by strugee** [comment]
You didn't fill out any of the supporting information.

**Comment by kenany** [comment]
Perhaps you could try `npm config set bin-links false`?
