### ISSUE TITLE
unable to install firebase-tools

### ISSUE THREAD

**Issue by satylogin** [npm/npm#17647]
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/usr/share/npm/lib/cache.js:687:35)
npm ERR!     at /usr/share/npm/lib/cache.js:675:5
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.4.0-72-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "firebase-tools"
npm ERR! cwd /home/satyarth
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type non_object_property_load
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/satyarth/npm-debug.log
npm ERR! not ok code 0

**Comment by kenany** [comment]
Sorry, your versions of Node and `npm` are years old and are no longer supported.
