### ISSUE TITLE
npm is removing packages added by @angular/cli

### ISSUE THREAD

**Issue by bogdancar** [npm/npm#17644]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I generated a new Angular 4 app with @angular/cli (v.1.2.0) having **yarn** set as **package manager** for @angular/cli. After the app is generated, I installed [find-phone-model](https://www.npmjs.com/package/find-phone-model) with `npm i find-phone-model`. The result of that is:
 ```
npm notice created a lockfile as package-lock.json. You should commit this file.
+ find-phone-model@1.0.0
added 1 package and removed 882 packages in 15.211s
```
Looks like npm is removing all the packages installed by @angular/cli using yarn. I found the problem on npm 5.0.3 bundled with node 8.1.3, I updated the npm to @latest (5.1.0) trying to solve the problem with no luck.
If I switch the @angular/cli to use npm as package manager, the problem is not showing.
If I use @angular/cli with yarn as package manager and then I add the lib with yarn, `yarn add find-phone-model`, the problem is not showing. 

#### How can the CLI team reproduce the problem?

With @angular/cli v.1.2.0 on a windows 10 machine, set yarn as the package manager `ng set --global packageManager=yarn`.
Generate a new app with `ng new app-name`.
After the generation run `npm i find-phone-model` on app-name.

### supporting information:

 - `npm -v` prints: 5.1.0
 - `node -v` prints: 8.1.3
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by zkat** [comment]
For the time being, this is how it's gonna roll: npm does not consider dependencies installed by yarn to be valid, and, unlike Yarn, npm _currently_ has a model where `npm i <pkg>` only installs a single dependency. You should be fine after doing an `npm i` with no arguments: all other deps will come back at that point.

In the future, npm will move further towards a "syncing" model where `package.json` will be treated as a source of truth and all installs/removals will sync your entire `node_modules`. Until then -- just do the extra install if you're switching back and forth between package managers. Yarn is not remotely designed such that you can switch away from it at any time, so if you choose to go that route, you should stick to it to have an optimal experience.

**Comment by benedyktdryl** [comment]
@zkat can I ask for brief explanation why "npm does not consider dependencies installed by yarn to be valid"?
