### ISSUE TITLE
Docker not installing npm latest

### ISSUE THREAD

**Issue by deepdad** [npm/npm#17651]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?
npm http GET https://registry.npmjs.org/protractor
npm http 200 https://registry.npmjs.org/protractor
npm http GET https://registry.npmjs.org/protractor/-/protractor-5.1.2.tgz
npm http 200 https://registry.npmjs.org/protractor/-/protractor-5.1.2.tgz
**npm WARN engine protractor@5.1.2: wanted: {"node":">=6.9.x"} (current: {"node":"v0.10.25","npm":"1.3.10"})**

**Comment by deepdad** [comment]
Oh, --nocache added to docker build solves it

**Comment by zkat** [comment]
Closing as resolved.
