### ISSUE TITLE
npm ERR! whenever I npm install

### ISSUE THREAD

**Issue by ShuaKo** [npm/npm#17655]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
   I cant run npm install -g ionic cordova without facing this error seen below

#### How can the CLI team reproduce the problem?
    I ran `npm config set prefix /usr/local`
   which messed up my computer and it keeps giving this error
   `Error: EPERM: operation not permitted, mkdir 'C:\Program Files (x86)\Git\local'
   at Error (native)`
   Looking for solutions online, I found this [answer]
   (https://stackoverflow.com/questions/34600932/npm-eperm-operation-not-permitted-on-windows)
   which removed the error. But another error emerged.
   It was installing on the first part but
`npm verb stack Error: EPERM: operation not permitted, mkdir 'C:\Program Files\Git\usr\local\node_modules'
npm verb stack     at Error (native)
npm verb cwd C:\Users\Joshua\Documents\upc-itc-notif-ionic
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ionic" "cordova" "--verbose"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! path C:\Program Files\Git\usr\local\node_modules
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall mkdir

npm ERR! Error: EPERM: operation not permitted, mkdir 'C:\Program Files\Git\usr\local\node_modules'
npm ERR!     at Error (native)
npm ERR!  { Error: EPERM: operation not permitted, mkdir 'C:\Program Files\Git\usr\local\node_modules'
npm ERR!     at Error (native)
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: 'C:\\Program Files\\Git\\usr\\local\\node_modules' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.
npm verb exit [ -4048, true ]

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Joshua\Documents\upc-itc-notif-ionic\npm-debug.log`

### supporting information:

 - `npm -v` prints: 3.10.10
 - `node -v` prints: v6.11.10
 - `npm config get registry` prints: http://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows

**Comment by kylelamse** [comment]
Similar issue:

$ npm i -D css-loader
npm ERR! path C:\Users\kyle.lamse\Code\typescript-webpack\node_modules\fsevents\node_modules\getpass\node_modules
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall lstat
npm ERR! Error: EPERM: operation not permitted, lstat 'C:\Users\kyle.lamse\Code\typescript-webpack\node_modules\fsevents\node_modules\getpass\node_module
s'
npm ERR!     at Error (native)
npm ERR!  { Error: EPERM: operation not permitted, lstat 'C:\Users\kyle.lamse\Code\typescript-webpack\node_modules\fsevents\node_modules\getpass\node_mod
ules'
npm ERR!     at Error (native)
npm ERR!   stack: 'Error: EPERM: operation not permitted, lstat \'C:\\Users\\kyle.lamse\\Code\\typescript-webpack\\node_modules\\fsevents\\node_modules\\
getpass\\node_modules\'\n    at Error (native)',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'lstat',
npm ERR!   path: 'C:\\Users\\kyle.lamse\\Code\\typescript-webpack\\node_modules\\fsevents\\node_modules\\getpass\\node_modules' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kyle.lamse\AppData\Roaming\npm-cache\_logs\2017-07-07T05_59_31_388Z-debug.log

**Comment by ShuaKo** [comment]
I was able to bypass this error by using an administrator Command Prompt. However, a lot of dependencies are not downloaded like `@ionic/app-scripts` and more. Also, I still want to be able to use git bash to do stuff.
