### ISSUE TITLE
How to avoid invoke npm-run-script recursively?

### ISSUE THREAD

**Issue by huoteng** [npm/npm#17657]
```
{
  "scripts": {
    "a": "npm run a",
    "b": "npm run c",
    "c": "npm run b"
  }
}
```
When I used `spawn` to invoke `npm run a` or `npm run b` in my node application, it will cause cycle call which will run many node process (max to 256 defaultly?). Is there any option I can use to solve this problem?

**Comment by zkat** [comment]
You'll have to use the standard tools you would use in any other situation where recursion is required: Find a base case, and use shell conditionals. Or, even better: write a JS script in your app, and then use `"scripts": "./scripts/a"` if you're not super comfortable doing all the conditional stuff in bash.
