### ISSUE TITLE
node-uuid error during uninstall of Cordova

### ISSUE THREAD

**Issue by rolinger** [npm/npm#17670]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x ] Other (_see below for feature requests_):

#### What's going wrong?
Getting the following error during uninstall of "cordova"

> iMac:dev test$ sudo npm uninstall -g cordova
> Password:
> npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
> Unhandled rejection Error: Argument #2: Expected string but got null hmac-drbg@^1.0.0 fetched in 170ms
>     at addDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:515:3)
>     at /usr/local/lib/node_modules/npm/lib/install/deps.js:463:5
>     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
>     at Array.forEach (native)
>     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
>     at Array.forEach (native)
>     at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
>     at loadDeps (/usr/local/lib/node_modules/npm/lib/install/deps.js:455:3)
>     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
>     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
>     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
>     at /usr/local/lib/node_modules/npm/lib/install/and-finish-tracker.js:8:8
>     at resolveBranchDeps.then (/usr/local/lib/node_modules/npm/lib/install/deps.js:419:11)
>     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
>     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
>     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
> 
> npm ERR! cb() never called!
> 
> npm ERR! This is an error with npm itself. Please report this error at:
> npm ERR!     <https://github.com/npm/npm/issues>
> 

#### How can the CLI team reproduce the problem?
I have no idea how to reproduce.  My npm install lost its marbles and I began uninstalling everything to start from scratch...I uninstalled ionic just fine, then next was cordova and got the above error.

Previously I was getting `Error: Cannot find module 'internal/fs'` when trying to compile my ionic/cordova projects.  everything i was reading basically indicated I needed to uninstall and reinstall npm - which I did...but was still getting the `internal/fs` error - so I decided to simply uninstall everything and start over.

> Cannot find module 'internal/fs' (CLI v1.7.16)
> 
> Your system information:
> Cordova CLI: 7.0.1
> Ionic CLI Version: 1.7.16
> Ionic App Lib Version: 0.7.3
> ios-deploy version: 1.9.1 
> ios-sim version: 6.0.0 
> OS: Mac OS X El Capitan
> Node Version: v8.1.3
> Xcode version: Xcode 8.2.1 Build version 8C1002 

[LOG FILE](https://gist.github.com/rolinger/5760961c892d095b34a0e18baa47aa25)

### supporting information:

 - `npm -v` prints:

```
iMac:_logs test$  npm -v
5.0.3

┌───────────────────────────┐
│                 npm update check failed                                        │
│           Try running with sudo or get access                           │
│          to the local update config store via                              │
│ sudo chown -R $USER:$(id -gn $USER) /Users/test/.config │
└────────────────────────────┘
```

 - `node -v` prints:
```
iMac:_logs test$ node -v
v8.1.3
```

 - `npm config get registry` prints:

```
iMac:_logs test$ npm config get registry
https://registry.npmjs.org/

┌───────────────────────────┐
│                 npm update check failed                                           │
│           Try running with sudo or get access                              │
│          to the local update config store via                                 │
│ sudo chown -R $USER:$(id -gn $USER) /Users/test/.config │
└────────────────────────────
```

 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
Does this also occur with `npm@5.1.0`?

**Comment by rolinger** [comment]
My npm installation is so messed up right now I can't tell.  thats why i need to cleanly uninstall everything but now I can't even uninstall Cordova.  Been spinning my wheels with these issues for 48+ hours now.  Any help would be greatly appreciated it.

**Comment by rolinger** [comment]
i was able to update to 5.1.0 and then cleanly uninstall cordova.  so that worked.

However, what is the optimal versions to pair npm and node?  npm@5.1.0 and node@8.1.3???? or is there a more stable combo?

**Comment by kenany** [comment]
Hmm, I would probably say use either the latest `npm@4`, or the latest `npm@5`, with the latest Node.js 6 or 8, but that's just my opinion.
