### ISSUE TITLE
Unable to install package

### ISSUE THREAD

**Issue by ArielS1** [npm/npm#17675]
#### I'm opening this issue because:
  - [ ] npm is producing an incorrect install.

#### What's going wrong?

Package doesn't exist even that it's here:
[https://www.npmjs.com/package/cloud-print](https://www.npmjs.com/package/cloud-print)

Tried to use ssh and get same issue.

#### How can the CLI team reproduce the problem?

[npm-debug.zip](https://github.com/npm/npm/files/1132386/npm-debug.zip)

npm install cloud-print

### supporting information:

 - Windows 10 OS

**Comment by kenany** [comment]
Can you upload the debug log file as plaintext to <https://gist.github.com/> instead of zipping it up? Thanks!

**Comment by ArielS1** [comment]
here is a gist of the file for easier view:
[https://gist.github.com/kill4food/025fd7faa61f01e0f5f050f1339a4f79](https://gist.github.com/kill4food/025fd7faa61f01e0f5f050f1339a4f79)
