### ISSUE TITLE
Node install destroyed PATH

### ISSUE THREAD

**Issue by ofek** [npm/npm#17682]
#### I'm opening this issue because:

  - npm is producing an incorrect install.

#### What's going wrong?

I installed the current version of node/npm (8.1.3) from the site on Windows 7 and it removed everything in my user PATH except for C:\Users\Ofek\AppData\Roaming\npm. There's really not much else to say other than that I'm extremely upset :(

**Comment by kenany** [comment]
So, this was the result of Node.js's installer from nodejs.org?

**Comment by ofek** [comment]
@KenanY Yes. https://nodejs.org/dist/v8.1.3/node-v8.1.3-x64.msi

**Comment by kenany** [comment]
Might wanna open this [here](https://github.com/nodejs/node/issues) instead then.

**Comment by ofek** [comment]
Thanks. https://github.com/nodejs/node/issues/14135
