### ISSUE TITLE
any body can solve this problem

### ISSUE THREAD

**Issue by alaale123** [npm/npm#17681]
#### I'm opening this issue because:

isse@isse-X550LN:~$ sudo su
root@isse-X550LN:/home/isse# sudo apt-get update
N: Ignoring file 'some-ppa.list.save.3' in directory '/etc/apt/sources.list.d/' as it has an invalid filename extension
N: Ignoring file 'some-ppa.list.save.2' in directory '/etc/apt/sources.list.d/' as it has an invalid filename extension
N: Ignoring file 'some-ppa.list.save.1' in directory '/etc/apt/sources.list.d/' as it has an invalid filename extension
E: Malformed line 1 in source list /etc/apt/sources.list.d/sublime-text.list (type)
E: The list of sources could not be read.
root@isse-X550LN:/home/isse# 

-->

**Comment by kenany** [comment]
Doesn't look like this is coming from `npm`.
