### ISSUE TITLE
I don't even know what is happening

### ISSUE THREAD

**Issue by VolleyGod** [npm/npm#17688]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I don't know what is happening except for when i use npm install --save djs-collection-persistent it doesn't work. I included the debug.log file. Thanks in advance
#### How can the CLI team reproduce the problem?
I just typed in npm install --save djs-collection-persistent and it all happened

The debug log is here https://hastebin.com/yinowahoko.log

### supporting information:

 - `npm -v` prints: 3.10.10
 - `node -v` prints: v6.10.2
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?: Windows 7
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by saper** [comment]
Hello, there a message in your log saying:

````
222 warn retry will retry, error on last attempt: Error: ENOSPC: no space left on device, write
````

Looks like your disk is full.
