### ISSUE TITLE
-bash: create-react-native-app: command not found

### ISSUE THREAD

**Issue by Parthjhaveri** [npm/npm#17693]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by Parthjhaveri** [comment]
Every time I type `create-react-native-app`, I get this error saying `-bash: create-react-native-app: command not found`.

I have tried changing the path... nothing has changed. I even uninstalled and re-installed node and npm. Nohting. 

Any help would be highly appreciated! Thank you.

**Comment by manrajgrover** [comment]
@Parthjhaveri Please fill the issue template. It would be very difficult for maintainers to debug it if you don't give required information.
