### ISSUE TITLE
Cannot uninstall global package

### ISSUE THREAD

**Issue by jschneier** [npm/npm#17690]
#### I'm opening this issue because:

  - [x] npm is crashing.

#### What's going wrong?

I have a globally installed `webpack` that I wish to remove do it the right way.

#### How can the CLI team reproduce the problem?
Log file contents:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/8.1.3/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'remove',
1 verbose cli   '-g',
1 verbose cli   'webpack' ]
2 info using npm@5.0.3
3 info using node@v8.1.3
4 verbose npm-session 363d612266bc1093
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly install loadIdealTree
8 silly install cloneCurrentTreeToIdealTree
9 silly install loadShrinkwrap
10 silly uninstall loadAllDepsIntoIdealTree
11 silly install loadAllDepsIntoIdealTree
12 error cb() never called!
13 error This is an error with npm itself. Please report this error at:
14 error <https://github.com/npm/npm/issues>
```

### supporting information:

 - `npm -v` prints: 5.0.3
 - `node -v` prints: 8.1.3
 - `npm config get registry` prints: https//registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Latest OSX

**Comment by jschneier** [comment]
I also tried `uninstall` and it did the same thing. Not sure if they are aliases for each other.

**Comment by kenany** [comment]
~~They are aliases for each other~~`remove` is an alias for `uninstall`. Could you see if `npm@5.1.0` resolves this issue?

**Comment by jschneier** [comment]
Ugh I _just_ upgrade to the latest node so I didn't check for dupes, sorry. Dupe #17590. Really sorry about that.
