### ISSUE TITLE
NPM version partially broken on Windows

### ISSUE THREAD

**Issue by markpeterfejes** [npm/npm#17719]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong? 
When doing `npm version <major|minor|patch>` on a Windows platform with a git repository initialized npm fails to commit the package-lock.json. On MacOS, there were no problems.

#### How can the CLI team reproduce the problem?

1. Do an `npm init` on a Windows PC
2. `git init`
3.  Install any small package (to create a lockfile)
4. Create a `version`, `preversion`and a `postversion`script with `echo`
5. Commit everything to git (ignore node_modules)
6. Do an `npm version <major|minor|patch> -m "test bump"`
7. npm creates the tag, but fails to commit the package-lock.json

### Supporting information:

 - `npm -v` prints: 5.2.0
 - `node -v` prints: 8.1.3
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows

**Comment by markpeterfejes** [comment]
I'll change my previous statement about macOSX. Sometimes it works, sometimes it does not.

**Comment by TehShrike** [comment]
Duplicate of #17707 - I've observed this personally on macOS, it is not Windows-specific.

**Comment by markpeterfejes** [comment]
Indeed. Thanks for the heads up! I meant to open this yesterday, when i searched for the issue, that why i did not find it!
