### ISSUE TITLE
[Solved] npm not updating to latest version

### ISSUE THREAD

**Issue by jitendravyas** [npm/npm#17710]
#### I'm opening this issue because:
  - [ ] npm is producing an incorrect install.

#### What's going wrong?

I have "prettier": "^1.5.2", in my package.json but upon `npm install` i still get `1.4.4`
### supporting information:

 - `npm -v` prints: 5.1.0
 - `node -v` prints: 6.10.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - MacOS

My package.lock files also has latest version but still

```
    "prettier": {
      "version": "1.5.2",
```

**Comment by jitendravyas** [comment]
Problem was that my global version was not updated

**Comment by agnibha92** [comment]
For me the same issue is happening. Though I have published 3.0.8 of one of my library but somehow when I tried to install into my friend's pc it was at 3.0.7. Some weird thing is happening.

**Comment by Spazum** [comment]
I get this in Ubuntu 16.04LTS 64bit AMD
node -v v4.2.6
npm -v 3.5.2
this seems to be after I followed instructions on npm doc page ... https://docs.npmjs.com/troubleshooting/try-the-latest-stable-version-of-npm .... which clearly states:

The current stable version of npm is 5.3.0

To upgrade, run: [sudo] npm install npm@latest -g

once I get this problem solved (refusing to upgrade to 5.3.0) then, I can tackle the problem with:


npm ERR! electron@1.6.11 postinstall: `node install.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the electron@1.6.11 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.

Which seems to be npm complaining as well .....

**Comment by Spazum** [comment]
Here is the fix:
https://nodejs.org/en/download/package-manager/
