### ISSUE TITLE
npm issue

### ISSUE THREAD

**Issue by Sandeeprathor** [npm/npm#17712]
/usr/local/lib/node_modules/appium/node_modules/appium-support/build/lib/fs.js:155
      throw _iteratorError;
            ^
TypeError: fn must be a function

    See http://goo.gl/916lJJ

    at Function.Promise.promisify (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/promisify.js:268:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/appium/node_modules/appium-support/build/lib/fs.js:143:35)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/appium/node_modules/appium-support/build/lib/tempdir.js:12:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/appium/node_modules/appium-support/build/index.js:11:19)
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! error rolling back Error: ENOTEMPTY, rmdir '/usr/local/lib/node_modules/appium/node_modules/lodash'
npm ERR! error rolling back  appium@1.6.5 { [Error: ENOTEMPTY, rmdir '/usr/local/lib/node_modules/appium/node_modules/lodash']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/appium/node_modules/lodash' }
npm ERR! weird error 8
npm ERR! tar.unpack error reading /home/sandeep/tmp/npm-6455-lXBGl3jI/1499750333516-0.6765502472408116/tmp.tgz
npm ERR! tar pack Error reading /home/sandeep/tmp/npm-6455-lXBGl3jI/1499750318976-0.18861061031930149/package
npm ERR! addLocalDirectory Could not pack "/home/sandeep/tmp/npm-6455-lXBGl3jI/1499750318976-0.18861061031930149/package" to "/home/sandeep/.npm/lodash/3.10.1/package.tgz"
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/appium/node_modules/babel-core/lib/transformation/transformers/es6/tail-call.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-121-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "appium"
npm ERR! cwd /home/sandeep
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /usr/local/lib/node_modules/appium/node_modules/babel-core/lib/transformation/transformers/es6/tail-call.js
npm ERR! fstream_path /usr/local/lib/node_modules/appium/node_modules/babel-core/lib/transformation/transformers/es6/tail-call.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/appium/node_modules/core-js/client/shim.min.js.map'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-121-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "appium"
npm ERR! cwd /home/sandeep
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /usr/local/lib/node_modules/appium/node_modules/core-js/client/shim.min.js.map
npm ERR! fstream_path /usr/local/lib/node_modules/appium/node_modules/core-js/client/shim.min.js.map
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/appium/node_modules/jpeg-js/test/fixtures/unconventional-table.jpg'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-121-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "appium"
npm ERR! cwd /home/sandeep
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /usr/local/lib/node_modules/appium/node_modules/jpeg-js/test/fixtures/unconventional-table.jpg
npm ERR! fstream_path /usr/local/lib/node_modules/appium/node_modules/jpeg-js/test/fixtures/unconventional-table.jpg
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/docs/no-prov-prof.png'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-121-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "appium"
npm ERR! cwd /home/sandeep
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/docs/no-prov-prof.png
npm ERR! fstream_path /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/docs/no-prov-prof.png
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/.gradle/3.5/javaCompile/classAnalysis.bin'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-121-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "appium"
npm ERR! cwd /home/sandeep
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/.gradle/3.5/javaCompile/classAnalysis.bin
npm ERR! fstream_path /usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/.gradle/3.5/javaCompile/classAnalysis.bin
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/appium/node_modules/traceur/bin/traceur.js.map'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-121-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "appium"
npm ERR! cwd /home/sandeep
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /usr/local/lib/node_modules/appium/node_modules/traceur/bin/traceur.js.map
npm ERR! fstream_path /usr/local/lib/node_modules/appium/node_modules/traceur/bin/traceur.js.map
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/instruments-iwd/iwd7/DTMobileISShim.dylib.dSYM/Contents/Resources/DWARF/DTMobileISShim.dylib'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-121-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "appium"
npm ERR! cwd /home/sandeep
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/instruments-iwd/iwd7/DTMobileISShim.dylib.dSYM/Contents/Resources/DWARF/DTMobileISShim.dylib
npm ERR! fstream_path /usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/instruments-iwd/iwd7/DTMobileISShim.dylib.dSYM/Contents/Resources/DWARF/DTMobileISShim.dylib
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm http GET https://registry.npmjs.org/request
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/appium/node_modules/appium-adb/jars/appium_apk_tools.jar'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-121-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "appium"
npm ERR! cwd /home/sandeep
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /usr/local/lib/node_modules/appium/node_modules/appium-adb/jars/appium_apk_tools.jar
npm ERR! fstream_path /usr/local/lib/node_modules/appium/node_modules/appium-adb/jars/appium_apk_tools.jar
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm http 304 https://registry.npmjs.org/request
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/sandeep/npm-debug.log
npm ERR! not ok code 0

**Comment by Sandeeprathor** [comment]
Someone please help me how to resolve this issue.. i want to install appium on my ubuntu.. 
Thanks in Advance

**Comment by kenany** [comment]
Sorry, but your versions of Node and `npm` are _years_ old and are no longer supported.
