### ISSUE TITLE
Not able to run application after download demo project. Please help me out how to run application using npm? I am new in it

### ISSUE THREAD

**Issue by AnshuDahiya** [npm/npm#17721]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start',
1 verbose cli   'serve.dev' ]
2 info using npm@1.4.28
3 info using node@v0.10.36
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 error Error: ENOENT, open 'C:\Users\10613841\Desktop\angular2-demo-app-master\angular2-demo-app-master\node_modules\serve.dev\package.json'
6 error If you need help, you may report this *entire* log,
6 error including the npm and node versions, at:
6 error     <http://github.com/npm/npm/issues>
7 error System Windows_NT 6.1.7601
8 error command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start" "serve.dev"
9 error cwd C:\Users\10613841\Desktop\angular2-demo-app-master\angular2-demo-app-master
10 error node -v v0.10.36
11 error npm -v 1.4.28
12 error path C:\Users\10613841\Desktop\angular2-demo-app-master\angular2-demo-app-master\node_modules\serve.dev\package.json
13 error code ENOENT
14 error errno 34
15 verbose exit [ 34, true ]

**Comment by kenany** [comment]
Node.js v0.10 and `npm` v1 are years old and are no longer supported. If this is still an issue with the latest versions of Node.js and `npm`, then I can reopen.
