### ISSUE TITLE
npm i -g webpack failed

### ISSUE THREAD

**Issue by newworld0** [npm/npm#17734]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [X ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints: 1.3.10
 - `node -v` prints:v0.10.25
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux 3.19.0-80-generic
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

> uglifyjs-webpack-plugin@0.4.6 postinstall /usr/local/lib/node_modules/webpack/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js

sh: 1: node: not found
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! weird error 127
npm ERR! tar pack Error reading /home/tmp/npm-3671-F558stII/1499814562094-0.506705068051815/package
npm ERR! addLocalDirectory Could not pack "/home/tmp/npm-3671-F558stII/1499814562094-0.506705068051815/package" to "/home/.npm/es5-ext/0.10.24/package.tgz"
npm ERR! Error: ENOENT, lstat '/home/tmp/npm-3671-F558stII/1499814556606-0.3782208780758083/package/node_modules/jsonify/lib/parse.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.19.0-80-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "i" "-g" "webpack"
npm ERR! cwd /home//ethereum/voting
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /home/tmp/npm-3671-F558stII/1499814556606-0.3782208780758083/package/node_modules/jsonify/lib/parse.js
npm ERR! fstream_path /home/tmp/npm-3671-F558stII/1499814556606-0.3782208780758083/package/node_modules/jsonify/lib/parse.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! tar pack Error reading /home/tmp/npm-3671-F558stII/1499814558117-0.3502278137020767/package
npm ERR! addLocalDirectory Could not pack "/home/tmp/npm-3671-F558stII/1499814558117-0.3502278137020767/package" to "/home/.npm/lodash/4.17.4/package.tgz"
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/ethereum/voting/npm-debug.log
npm ERR! not ok code 0

**Comment by alexan** [comment]
you should update npm and node to get webpack@3 working

**Comment by newworld0** [comment]
Hi Alex, thanks for the quick response. 
Every time I try to update the npm or nodejs I get is up to date message. are suggesting compiling my own with the latest version and not use Ubuntu apt-get?

**Comment by kenany** [comment]
I suggest you use NodeSource's apt repository, see <https://nodejs.org/en/download/package-manager/>. Once you've got at least the latest stable release of Node and `npm` you should be good to go; if not then feel free to comment here.

**Comment by newworld0** [comment]
KenatY, thank you very much, that worked.
