### ISSUE TITLE
npm install problem. How Can I fix it ?

### ISSUE THREAD

**Issue by edoko** [npm/npm#17739]
#### I'm opening this issue because:

  - [x] Other (_see below for feature requests_):

#### What's going wrong?

I try to install 'https://github.com/ricky155030/node-instagram'
but, it occurs this error. (I'm Windows 10 64bit)

I submit screen shot and debug.log

![test4](https://user-images.githubusercontent.com/1365682/28109523-52c02ee4-672a-11e7-95e3-e1507f289c17.png)

[npm-debug.zip](https://github.com/npm/npm/files/1141388/npm-debug.zip)

**Comment by kenany** [comment]
You should `cd` into your own project and run `npm install node-instagram-api` from there.

**Comment by edoko** [comment]
@KenanY Yes, of course I did, but an error occurred.

**Comment by kenany** [comment]
@edoko What error? In the screenshot you posted, you did not `cd` into your own project, you `cd`'d into the cloned `node-instagram` directory.

**Comment by erevos-13** [comment]
@edoko Hello in the screenshot you send you put 
`cd ..` 
With this command you going  backwards in the directory you need when clone the git repository in the folder and  then inside there to install:
`npm install node-instagram-api`

**Comment by kenany** [comment]
Closing as abandoned.
