### ISSUE TITLE
npm installation issue

### ISSUE THREAD

**Issue by anupkumar0072000** [npm/npm#17738]
npm ERR! fetch failed https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.0
.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with statu
s code 404
npm ERR! fetch failed https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.0
.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with statu
s code 404
npm ERR! fetch failed https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.0
.tgz

**Comment by golovan** [comment]
Same for me. Nothing changed in the project but got this error today.

**Comment by laureysruben** [comment]
Same here. Someone opened an issue on the ansi-styles project. But the owner closed the issue immediately and referred to npm for resolving it.

I added 2 log files showing the issue in attachment

[logs.zip](https://github.com/npm/npm/files/1141971/logs.zip)

**Comment by laureysruben** [comment]
@anupkumar0072000 Maybe you should update the title of this issue to be a bit more descriptive? Maybe mention ansi-styles etc

**Comment by kenany** [comment]
Duplicate of https://github.com/npm/npm/issues/17723
