### ISSUE TITLE
npm won't start

### ISSUE THREAD

**Issue by i-mighty** [npm/npm#17743]
[npm-debug.txt](https://github.com/npm/npm/files/1141831/npm-debug.txt)

#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by markpeterfejes** [comment]
Can you show us your package.json file? Do you have a script entry in there called `start`?

**Comment by jsg2021** [comment]
might be related to #17717

**Comment by i-mighty** [comment]
Well my first problem was related to th e start script however I solved
that and now I have another problem at hand. I will try it again and this
time will copy the error report. Thanks agian for the help

**Comment by i-mighty** [comment]
Here is a full detail of what is wrong: 
I'm trying to use react with babel
It worked fine before the incorporation of babel 
Now whenever I run <./node_modules/.bin/webpack -d> after configuring all my files
I get this error at terminal **/root/Desktop/CodeBox/reactApp/webpack.config.js:12
  }module : {
   ^^^^^^
SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at requireConfig (/root/Desktop/CodeBox/reactApp/node_modules/webpack/bin/convert-argv.js:97:18)**
Attached below are my files


[webpack.config.js.txt](https://github.com/npm/npm/files/1151397/webpack.config.js.txt)
[package.json.txt](https://github.com/npm/npm/files/1151399/package.json.txt)
[.babelrc.txt](https://github.com/npm/npm/files/1151398/default.babelrc.txt)
[index.jsx.txt](https://github.com/npm/npm/files/1151400/index.jsx.txt)
[bundle.js.txt](https://github.com/npm/npm/files/1151401/bundle.js.txt)


Remove the .txt for each file and try to recrete the scene thanks.

**Comment by markpeterfejes** [comment]
I think you are missing a comma between the closing bracket and the `module`

**Comment by i-mighty** [comment]
Yes @markpeterfejes saw stuffs online and fixed it, sorry it comes late. I appreciate your advice.
