### ISSUE TITLE
Unable tin install electron

### ISSUE THREAD

**Issue by abhaydhar** [npm/npm#17753]
I am trying to install electron for the first tie , my  machine is within a corporate firewall. error Unexpected token < in JSON at position 0

31 error Windows_NT 6.3.9600
32 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "electron"
33 error node v6.11.0
34 error npm  v3.10.10
35 error Unexpected token < in JSON at position 0
35 error <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
35 error <html xmlns="http://www.w3.org/1999/xhtml">
35 error <head>
35 error <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
35 error <title>404 - File or directory not found.</title>
35 error <style type="text/css">
35 error <!--

**Comment by a1626** [comment]
Can you check your `Package.json` and make sure it has got no parsing error (You can paste the content pf package.json in some (validator)[jsonformatter.curiousconcept.com] to make sure it is ok).
