### ISSUE TITLE
Getting error on "$ npm install lite-server --save-dev" command

### ISSUE THREAD

**Issue by sharadgit1** [npm/npm#17756]
Hi Team,

I am trying to install lite-server for my application but facing below error. Could you let me know how to fix it? I have attached the "npm-debug" file as well.

$ npm install lite-server --save-dev

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "lite-server" "--save-dev"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! syscall getaddrinfo

npm ERR! getaddrinfo EAI_AGAIN registry.npmjs.org:443
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\shashank.pathik\ng2-start\npm-debug.log

**Comment by a1626** [comment]
Are you behind some `firewall`?

**Comment by sharadgit1** [comment]
I am not sure. Attached one screen related to firewall where its state is OFF. Please let me know how to proceed.
![firewall screen](https://user-images.githubusercontent.com/22978780/28163353-63daf9ca-67e8-11e7-9211-808816b660b5.PNG)

**Comment by a1626** [comment]
Are you working from Office?

**Comment by sharadgit1** [comment]
Yes.

**Comment by a1626** [comment]
In that case you need to contact IT/security division of your company and ask them for proxy details so that you can set them in your `.npmrc` file.
