### ISSUE TITLE
npm will not let me install typescript

### ISSUE THREAD

**Issue by bayon** [npm/npm#17751]
npm ERR! Darwin 16.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "typescript"
npm ERR! node v4.4.0
npm ERR! npm  v3.10.8

npm ERR! uid must be an unsigned int
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log

I was not allowed to attach the "npm-debug.log" to this comment, nor was I able to paste the content of that file into this message as it is too large.

**Comment by damncabbage** [comment]
Could you put the contents of that log into a http://gist.github.com/ ?
(Not an npm member; just trying to save them some time.)

**Comment by leonadler** [comment]
Consider upgrading your node & npm, if your project allows that. Node 4.4 is fairly old.

**Comment by bayon** [comment]
ok thankyou.
