### ISSUE TITLE
Unable to install webpack

### ISSUE THREAD

**Issue by mahesh-balumuri** [npm/npm#17767]
17178 silly gunzTarPerm extractEntry test/number/is-finite/index.js
17179 silly gunzTarPerm extractEntry test/number/is-finite/is-implemented.js
17180 silly gunzTarPerm extractEntry test/number/is-finite/shim.js
17181 silly gunzTarPerm extractEntry test/number/#/pad.js
17182 error Error: ENOENT, lstat '/root/tmp/npm-4831-XvBde-ZZ/1499961389261-0.034706454491242766/package/lib/binding/Release/node-v46-darwin-x64/fse.node'
17183 error If you need help, you may report this log at:
17183 error     <http://github.com/isaacs/npm/issues>
17183 error or email it to:
17183 error     <npm-@googlegroups.com>
17184 error System Linux 3.10.0-327.36.1.el7.x86_64
17185 error command "node" "/bin/npm" "install" "-g" "webpack"
17186 error cwd /root
17187 error node -v v0.10.46
17188 error npm -v 1.3.6
17189 error path /root/tmp/npm-4831-XvBde-ZZ/1499961389261-0.034706454491242766/package/lib/binding/Release/node-v46-darwin-x64/fse.node
17190 error fstream_path /root/tmp/npm-4831-XvBde-ZZ/1499961389261-0.034706454491242766/package/lib/binding/Release/node-v46-darwin-x64/fse.node
17191 error fstream_type File
17192 error fstream_class FileWriter
17193 error code ENOENT
17194 error errno 34
17195 error fstream_stack /usr/lib/node_modules/fstream/lib/writer.js:284:26
17195 error fstream_stack Object.oncomplete (fs.js:108:15)
17196 verbose exit [ 34, true ]

**Comment by kenany** [comment]
Sorry, but your versions of Node and `npm` are _years_ old and are no longer supported.
