### ISSUE TITLE
Dependencies not deduped with npm 5, are with npm 4

### ISSUE THREAD

**Issue by jason0x43** [npm/npm#17774]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

The intern package depends on several `@dojo/*` packages, as do its dependencies digdug and leadfoot. All depend on the same versions of the `@dojo/*` packages. When installing `intern@4.0.0-alpha.8` with npm5, the `@dojo/*` packages are only partially deduped. When installing with npm4, the `@dojo/*` packages are fully deduped. This is the case initially, and after running `npm dedupe`.

#### How can the CLI team reproduce the problem?

Create an empty project with the following package.json:

```
{
    "dependencies": {
        "intern": "4.0.0-alpha.8"
    }
}
```

Run `npm install` with npm 5.2.0. After installation, the package tree will contain:

```
node_modules/
  @dojo/
    has/
    interfaces/
  intern/
    node_modules/
      @dojo/
        core/
        shim/
  @theintern/
    leadfoot/
      node_modules/
        @dojo/
          core/
          shim/
    digdug/
      node_modules/
        @dojo/
          core/
          shim/
```

After running `npm install` with npm 4.2.0, the package tree contains:

```
node_modules/
  @dojo/
    core/
    has/
    interfaces/
    shim/
  intern/
  @theintern/
    leadfoot/
    digdug/
      node_modules/
```

In all cases, the required version of the `@dojo/*` packages is '~2.0.0-beta2.2'.
    
### supporting information:

 - `npm -v` prints: 5.2.0
 - `node -v` prints: v8.1.4
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by Coridyn** [comment]
I was running into the same issue - it looks like the change has been reverted in [v5.3.0 that was just released](https://github.com/npm/npm/releases/tag/v5.3.0) (I think was the 8e979bf80 commit).

I've done a quick test on my project and it looks like the dependencies are being flattened as expected again.

**Comment by jason0x43** [comment]
Yes, 5.3.0 does resolve my issue.
