### ISSUE TITLE
Error running command npm install --save-dev webpack

### ISSUE THREAD

**Issue by saularis** [npm/npm#17771]
npm ERR! Linux 4.10.0-041000-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--save-dev" "webpack"
npm ERR! node v4.7.2
npm ERR! npm  v3.5.2
npm ERR! code ENOSELF

npm ERR! Refusing to install webpack as a dependency of itself
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/peeko/Code/front-end/react/webpack/npm-debug.log

**Comment by saularis** [comment]
# npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--save-dev',
1 verbose cli   'webpack' ]
2 info using npm@3.5.2
3 info using node@v4.7.2
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData webpack
8 silly fetchNamedPackageData webpack
9 silly mapToRegistry name webpack
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/webpack
13 verbose request uri https://registry.npmjs.org/webpack
14 verbose request no auth needed
15 info attempt registry request try #1 at 12:56:31 AM
16 verbose request id 156ec1cc4cd854e6
17 verbose etag W/"5965e4fc-f9e9f"
18 verbose lastModified Wed, 12 Jul 2017 08:59:40 GMT
19 http request GET https://registry.npmjs.org/webpack
20 http 304 https://registry.npmjs.org/webpack
21 verbose headers { date: 'Thu, 13 Jul 2017 18:56:31 GMT',
21 verbose headers   via: '1.1 varnish',
21 verbose headers   'cache-control': 'max-age=300',
21 verbose headers   etag: 'W/"5965e4fc-f9e9f"',
21 verbose headers   age: '164',
21 verbose headers   connection: 'keep-alive',
21 verbose headers   'x-served-by': 'cache-sin18028-SIN',
21 verbose headers   'x-cache': 'HIT',
21 verbose headers   'x-cache-hits': '429',
21 verbose headers   'x-timer': 'S1499972192.795974,VS0,VE0',
21 verbose headers   vary: 'Accept-Encoding, Accept' }
22 silly get cb [ 304,
22 silly get   { date: 'Thu, 13 Jul 2017 18:56:31 GMT',
22 silly get     via: '1.1 varnish',
22 silly get     'cache-control': 'max-age=300',
22 silly get     etag: 'W/"5965e4fc-f9e9f"',
22 silly get     age: '164',
22 silly get     connection: 'keep-alive',
22 silly get     'x-served-by': 'cache-sin18028-SIN',
22 silly get     'x-cache': 'HIT',
22 silly get     'x-cache-hits': '429',
22 silly get     'x-timer': 'S1499972192.795974,VS0,VE0',
22 silly get     vary: 'Accept-Encoding, Accept' } ]
23 verbose etag https://registry.npmjs.org/webpack from cache
24 verbose get saving webpack to /home/peeko/.npm/registry.npmjs.org/webpack/.cache.json
25 silly install normalizeTree
26 silly loadCurrentTree Finishing
27 silly loadIdealTree Starting
28 silly install loadIdealTree
29 silly cloneCurrentTree Starting
30 silly install cloneCurrentTreeToIdealTree
31 silly cloneCurrentTree Finishing
32 silly loadShrinkwrap Starting
33 silly install loadShrinkwrap
34 silly loadShrinkwrap Finishing
35 silly loadAllDepsIntoIdealTree Starting
36 silly install loadAllDepsIntoIdealTree
37 silly rollbackFailedOptional Starting
38 silly rollbackFailedOptional Finishing
39 silly runTopLevelLifecycles Starting
40 silly runTopLevelLifecycles Finishing
41 silly install printInstalled
42 verbose stack Error: Refusing to install webpack as a dependency of itself
42 verbose stack     at checkSelf (/usr/share/npm/lib/install/validate-args.js:40:14)
42 verbose stack     at Array.<anonymous> (/usr/share/npm/node_modules/slide/lib/bind-actor.js:15:8)
42 verbose stack     at LOOP (/usr/share/npm/node_modules/slide/lib/chain.js:15:14)
42 verbose stack     at chain (/usr/share/npm/node_modules/slide/lib/chain.js:20:5)
42 verbose stack     at /usr/share/npm/lib/install/validate-args.js:15:5
42 verbose stack     at /usr/share/npm/node_modules/slide/lib/async-map.js:52:35
42 verbose stack     at Array.forEach (native)
42 verbose stack     at /usr/share/npm/node_modules/slide/lib/async-map.js:52:11
42 verbose stack     at Array.forEach (native)
42 verbose stack     at asyncMap (/usr/share/npm/node_modules/slide/lib/async-map.js:51:8)
43 verbose cwd /home/peeko/Code/front-end/react/webpack
44 error Linux 4.10.0-041000-generic
45 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--save-dev" "webpack"
46 error node v4.7.2
47 error npm  v3.5.2
48 error code ENOSELF
49 error Refusing to install webpack as a dependency of itself
50 error If you need help, you may report this error at:
50 error     <https://github.com/npm/npm/issues>
51 verbose exit [ 1, true ]

**Comment by kenany** [comment]
Ensure that the `"name"` property in your `package.json` is not set to `"webpack"`. You may also have to rename `/home/peeko/Code/front-end/react/webpack` to something besides `webpack`.

**Comment by saularis** [comment]
Thank you. It's working now.
