### ISSUE TITLE
New to coding and web development. Ran into a problem right out of the gate.

### ISSUE THREAD

**Issue by Karkava** [npm/npm#17782]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong? 
I'm kind of new to this and I'm following instructions online, but I basically have to type in "git clone https://github.com/kentcdodds/starwars-names.git" followed with "cd starwars-names" followed with "npm run setup:fem". After completing this, I run into an error message and the instructions aren't helping.

#### How can the CLI team reproduce the problem?
I don't know, but I would like to have some detailed instructions on what it is I am supposed to be doing...

### supporting information:

 - `npm -v` prints: C:\Users\Jim\starwars-names\npm-debug.log
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?: Windows
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [x] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
Could you upload the debug log to <https://gist.github.com/> and link it here? Thanks!

**Comment by kenany** [comment]
Closing as abandoned.
