### ISSUE TITLE
refusing to install ng2-select as a dependency of itself

### ISSUE THREAD

**Issue by shuangxia1** [npm/npm#17780]
0 info it worked if it ends with ok
1 verbose cli [ '/Users/shuangxia/.nvm/versions/node/v6.9.5/bin/node',
1 verbose cli   '/Users/shuangxia/.nvm/versions/node/v6.9.5/bin/npm',
1 verbose cli   'i',
1 verbose cli   'ng2-select',
1 verbose cli   '--save' ]
2 info using npm@3.10.10
3 info using node@v6.9.5
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData ng2-select
8 silly fetchNamedPackageData ng2-select
9 silly mapToRegistry name ng2-select
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'ng2-select',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'ng2-select',
12 silly mapToRegistry   name: 'ng2-select',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/ng2-select
14 verbose request uri https://registry.npmjs.org/ng2-select
15 verbose request no auth needed
16 info attempt registry request try #1 at 10:28:30 AM
17 verbose request id 44dfe9acf7d76105
18 verbose etag W/"592fd3a8-7d28"
19 verbose lastModified Thu, 01 Jun 2017 08:43:20 GMT
20 http request GET https://registry.npmjs.org/ng2-select
21 http 304 https://registry.npmjs.org/ng2-select
22 verbose headers { date: 'Fri, 14 Jul 2017 09:28:30 GMT',
22 verbose headers   via: '1.1 varnish',
22 verbose headers   'cache-control': 'max-age=300',
22 verbose headers   etag: 'W/"592fd3a8-7d28"',
22 verbose headers   age: '29',
22 verbose headers   connection: 'keep-alive',
22 verbose headers   'x-served-by': 'cache-lcy1151-LCY',
22 verbose headers   'x-cache': 'HIT',
22 verbose headers   'x-cache-hits': '1',
22 verbose headers   'x-timer': 'S1500024511.881607,VS0,VE0',
22 verbose headers   vary: 'Accept-Encoding, Accept' }
23 silly get cb [ 304,
23 silly get   { date: 'Fri, 14 Jul 2017 09:28:30 GMT',
23 silly get     via: '1.1 varnish',
23 silly get     'cache-control': 'max-age=300',
23 silly get     etag: 'W/"592fd3a8-7d28"',
23 silly get     age: '29',
23 silly get     connection: 'keep-alive',
23 silly get     'x-served-by': 'cache-lcy1151-LCY',
23 silly get     'x-cache': 'HIT',
23 silly get     'x-cache-hits': '1',
23 silly get     'x-timer': 'S1500024511.881607,VS0,VE0',
23 silly get     vary: 'Accept-Encoding, Accept' } ]
24 verbose etag https://registry.npmjs.org/ng2-select from cache
25 verbose get saving ng2-select to /Users/shuangxia/.npm/registry.npmjs.org/ng2-select/.cache.json
26 verbose correctMkdir /Users/shuangxia/.npm correctMkdir not in flight; initializing
27 silly install normalizeTree
28 silly loadCurrentTree Finishing
29 silly loadIdealTree Starting
30 silly install loadIdealTree
31 silly cloneCurrentTree Starting
32 silly install cloneCurrentTreeToIdealTree
33 silly cloneCurrentTree Finishing
34 silly loadShrinkwrap Starting
35 silly install loadShrinkwrap
36 silly loadShrinkwrap Finishing
37 silly loadAllDepsIntoIdealTree Starting
38 silly install loadAllDepsIntoIdealTree
39 silly rollbackFailedOptional Starting
40 silly rollbackFailedOptional Finishing
41 silly runTopLevelLifecycles Finishing
42 silly install printInstalled
43 verbose stack Error: Refusing to install ng2-select as a dependency of itself
43 verbose stack     at checkSelf (/Users/shuangxia/.nvm/versions/node/v6.9.5/lib/node_modules/npm/lib/install/validate-args.js:53:14)
43 verbose stack     at Array.<anonymous> (/Users/shuangxia/.nvm/versions/node/v6.9.5/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
43 verbose stack     at LOOP (/Users/shuangxia/.nvm/versions/node/v6.9.5/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
43 verbose stack     at chain (/Users/shuangxia/.nvm/versions/node/v6.9.5/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
43 verbose stack     at /Users/shuangxia/.nvm/versions/node/v6.9.5/lib/node_modules/npm/lib/install/validate-args.js:16:5
43 verbose stack     at /Users/shuangxia/.nvm/versions/node/v6.9.5/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
43 verbose stack     at Array.forEach (native)
43 verbose stack     at /Users/shuangxia/.nvm/versions/node/v6.9.5/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
43 verbose stack     at Array.forEach (native)
43 verbose stack     at asyncMap (/Users/shuangxia/.nvm/versions/node/v6.9.5/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
44 verbose cwd /Users/shuangxia/WebstormProjects/ng2-select/ng2-select
45 error Darwin 16.6.0
46 error argv "/Users/shuangxia/.nvm/versions/node/v6.9.5/bin/node" "/Users/shuangxia/.nvm/versions/node/v6.9.5/bin/npm" "i" "ng2-select" "--save"
47 error node v6.9.5
48 error npm  v3.10.10
49 error code ENOSELF
50 error Refusing to install ng2-select as a dependency of itself
51 error If you need help, you may report this error at:
51 error     <https://github.com/npm/npm/issues>
52 verbose exit [ 1, true ]

**Comment by kenany** [comment]
Ensure that the `"name"` property in your `package.json` is not set to `"ng2-select"`. You may likewise need to rename the `/Users/shuangxia/WebstormProjects/ng2-select/ng2-select` directory.

**Comment by shuangxia1** [comment]
Yes,u Right. THX
