### ISSUE TITLE
missing script: dev 

### ISSUE THREAD

**Issue by zhaipanyu** [npm/npm#17798]
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10

npm ERR! missing script: dev
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:

**Comment by hstarorg** [comment]
In fact, npm has no `dev` command. If you want to execute `npm run dev`, please sure that `"dev"` is in your `package.json` like this:
```
  "scripts": {
    "dev": "webpack-dev-server --config build/webpack.dev.conf.js",
    "publish": "ngc -p tsconfig-aot.json",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
```

**Comment by gargvivek86** [comment]
Resolved by using below in package.json file.

 "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "dev": "lite-server"
  },
