### ISSUE TITLE
Bad request when try to install angularcli

### ISSUE THREAD

**Issue by karthik212** [npm/npm#17796]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   '@angular/cli' ]
2 info using npm@3.10.10
3 info using node@v6.11.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData @angular/cli
8 silly fetchNamedPackageData @angular/cli
9 silly mapToRegistry name @angular/cli
10 silly mapToRegistry scope (from package name) @angular
11 verbose mapToRegistry no registry URL found in name for scope @angular
12 silly mapToRegistry using default registry
13 silly mapToRegistry registry http://registry.npmjs.org/
14 silly mapToRegistry data Result {
14 silly mapToRegistry   raw: '@angular/cli',
14 silly mapToRegistry   scope: '@angular',
14 silly mapToRegistry   escapedName: '@angular%2fcli',
14 silly mapToRegistry   name: '@angular/cli',
14 silly mapToRegistry   rawSpec: '',
14 silly mapToRegistry   spec: 'latest',
14 silly mapToRegistry   type: 'tag' }
15 silly mapToRegistry uri http://registry.npmjs.org/@angular%2fcli
16 verbose request uri http://registry.npmjs.org/@angular%2fcli
17 verbose request no auth needed
18 info attempt registry request try #1 at 5:56:08 PM
19 verbose request id 471d0c3ab40d20f0
20 http request GET http://registry.npmjs.org/@angular%2fcli
21 http 400 http://registry.npmjs.org/@angular%2fcli
22 verbose headers { server: 'Apache-Coyote/1.1',
22 verbose headers   'content-length': '0',
22 verbose headers   date: 'Sat, 15 Jul 2017 12:26:08 GMT',
22 verbose headers   connection: 'close' }
23 silly get cb [ 400,
23 silly get   { server: 'Apache-Coyote/1.1',
23 silly get     'content-length': '0',
23 silly get     date: 'Sat, 15 Jul 2017 12:26:08 GMT',
23 silly get     connection: 'close' } ]
24 silly fetchPackageMetaData Error: 400 Bad Request
24 silly fetchPackageMetaData     at makeError (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:302:12)
24 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:253:9)
24 silly fetchPackageMetaData     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:210:14)
24 silly fetchPackageMetaData     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:187:22)
24 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
24 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
24 silly fetchPackageMetaData     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1048:10)
24 silly fetchPackageMetaData     at emitOne (events.js:96:13)
24 silly fetchPackageMetaData     at Request.emit (events.js:188:7)
24 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:969:12)
24 silly fetchPackageMetaData  error for @angular/cli { Error: 400 Bad Request
24 silly fetchPackageMetaData     at makeError (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:302:12)
24 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:253:9)
24 silly fetchPackageMetaData     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:210:14)
24 silly fetchPackageMetaData     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:187:22)
24 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
24 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
24 silly fetchPackageMetaData     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1048:10)
24 silly fetchPackageMetaData     at emitOne (events.js:96:13)
24 silly fetchPackageMetaData     at Request.emit (events.js:188:7)
24 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:969:12) statusCode: 400, code: 'E400' }
25 silly rollbackFailedOptional Starting
26 silly rollbackFailedOptional Finishing
27 silly runTopLevelLifecycles Finishing
28 silly install printInstalled
29 verbose stack Error: 400 Bad Request
29 verbose stack     at makeError (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:302:12)
29 verbose stack     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:253:9)
29 verbose stack     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:210:14)
29 verbose stack     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:187:22)
29 verbose stack     at emitTwo (events.js:106:13)
29 verbose stack     at Request.emit (events.js:191:7)
29 verbose stack     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1048:10)
29 verbose stack     at emitOne (events.js:96:13)
29 verbose stack     at Request.emit (events.js:188:7)
29 verbose stack     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:969:12)
30 verbose statusCode 400
31 verbose cwd F:\AngularEclipse_Workspace
32 error Windows_NT 6.1.7600
33 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli"
34 error node v6.11.1
35 error npm  v3.10.10
36 error code E400
37 error 400 Bad Request
38 error If you need help, you may report this error at:
38 error     <https://github.com/npm/npm/issues>
39 verbose exit [ 1, true ]

**Comment by karthik212** [comment]
Solved the error

**Comment by ghost** [comment]
How u fixed it?
