### ISSUE TITLE
can't remove a dist-tag

### ISSUE THREAD

**Issue by ghost** [npm/npm#17806]
Currently learning NPM.

I have 2 dist-tags, beta: 1.0.1 & latest: 1.0.1

I want to remove beta: 1.0.1 & I'm not able to do it.

I tried, npm dist-tag rm beta 1.0.1, It doesn't work. 

Worst condition, npm docs doesn't have examples on how to remove a dist-tag!

**Comment by ghost** [comment]
As expected the moderators are not answering to this post, so posting a stackoverflow answer here. Hope it will help. 
tag remove command- npm dist-tag rm <module name>@1.0.1 beta

**Comment by kenany** [comment]
Closing as resolved then.
