### ISSUE TITLE
Q: Are you guys using any js linter?

### ISSUE THREAD

**Issue by DianaSuvorova** [npm/npm#17801]
I am looking for some "firts-time-contribution" ideas. 
I looked through the issues and the code. One thing that I didn't find is a linter (like eslint or jshint).  Is there one? If not would you like one 😄 ?

**Comment by danieldiekmeier** [comment]
I think they're using [Standard](https://standardjs.com/). See the `test` script in the package.json: https://github.com/npm/npm/blob/latest/package.json#L241

**Comment by kenany** [comment]
Yup, we're using `standard` already 👍

**Comment by DianaSuvorova** [comment]
Got it. Thanks !
