### ISSUE TITLE
Help me please | Error: Cannot find module '@doctormckay/stats-reporter'

### ISSUE THREAD

**Issue by ongloveth123** [npm/npm#17813]
#### I'm opening this issue because:

  - [1 ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [1 ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

![1](https://user-images.githubusercontent.com/30243185/28284343-e2911fcc-6b5a-11e7-9ce3-f3a0d3e26819.png)

**Comment by rxgx** [comment]
What does this command print out for you?

`npm config get registry`
