### ISSUE TITLE
npm uninstall -g unhandled rejection error

### ISSUE THREAD

**Issue by bgando** [npm/npm#17814]
#### I'm opening this issue because:

  - [X] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I'm not able to uninstall a global package and gives this error. More context linked in the gist below:

```shell
Unhandled rejection Error: Argument #2: Expected string but got nullad4bab852f40
    at addDependency (../.nvm/versions/node/v7.7.1/lib/node_modules/npm/lib/install/deps.js:515:3)
...
npm ERR! cb() never called!
```

#### How can the CLI team reproduce the problem?
npm install -g donejs@1
npm uninstall -g donejs
[npm debug log](https://gist.github.com/bgando/ed23c1ca22762b7a43badee17dabdb42)

### supporting information:

 - `npm -v` prints:
5.0.3
 - `node -v` prints:
v7.7.1
 - `npm config get registry` prints:
https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?:
OS X/macOS
 - Network issues: NONE
   - Geographic location where npm was run: Greater Puerto Vallarta, Mexico
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container: NONE
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
Does this also occur with the latest version of `npm@5`?

**Comment by bgando** [comment]
The lastest version fixes it. Thanks!
