### ISSUE TITLE
Upgrading Node to v8 does not update npm to v5

### ISSUE THREAD

**Issue by Manish-Giri** [npm/npm#17815]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?

Upgrading to Node v8 by downloading the installer from the [Nodejs site](https://nodejs.org/en/download/current/) does not seem to upgrade `npm` to v5, on Windows. Although it does so on mac. 

### supporting information:

Screenshots - 

![npm](https://user-images.githubusercontent.com/11348778/28294185-5dcf335c-6b26-11e7-9914-261f21654a7d.png)

Updated on mac -

![screenshot 2017-07-17 19 31 55](https://user-images.githubusercontent.com/11348778/28294241-b301775e-6b26-11e7-8f82-2b9e924e23c8.png)

I downloaded the installer again, and hit "repair" just in case something went wrong in the first install, but same result.

**Comment by kenany** [comment]
Perhaps you should report this to the Node.js installer people instead?

**Comment by Manish-Giri** [comment]
@KenanY Sorry, I've reported this in the `node` repository. Thank You.
