### ISSUE TITLE
Issue while installing typescript

### ISSUE THREAD

**Issue by ddaschayan** [npm/npm#17824]
#### I'm opening this issue because:

  - [ ] npm is doing something I don't understand.

#### What's going wrong?
I am not able to install typescript.

-->

### supporting information:

C:\Users\Chayan.Das01>npm install -g typescript
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "typescript"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5

npm ERR! Cannot read property 'path' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Chayan.Das01\npm-debug.log

C:\Users\Chayan.Das01>

**Comment by ddaschayan** [comment]
Please help!!

**Comment by kenany** [comment]
Could you upload the full debug log to <https://gist.github.com/> and link it here? Thanks!

**Comment by kenany** [comment]
Closing as abandoned.
