### ISSUE TITLE
npm ERR in jenkins job

### ISSUE THREAD

**Issue by SANDEEPERUMALLA** [npm/npm#17829]
03:24:09 [2017-07-18 03:24:09.894] [INFO] BuildOrch - =====>> [ bake : lint: start ]
03:24:09 [2017-07-18 03:24:09.894] [INFO] BuildOrch - # CWD: /hostedpaymentnodeweb-ci-7154/workspace/hostedpaymentnodeweb-ci-7154
03:24:10 npm ERR! Linux 4.4.0-57-generic
03:24:10 npm ERR! argv "/hostedpaymentnodeweb-ci-7154/workspace/hostedpaymentnodeweb-ci-7154/.nvm/v4.8.4/bin/node" "/hostedpaymentnodeweb-ci-7154/workspace/hostedpaymentnodeweb-ci-7154/.nvm/v4.8.4/bin/npm" "run" "lint"
03:24:10 npm ERR! node v4.8.4
03:24:10 npm ERR! npm  v3.10.8
03:24:10 
03:24:10 npm ERR! missing script: lint
03:24:10 npm ERR! 
03:24:10 npm ERR! If you need help, you may report this error at:
03:24:10 npm ERR!     <https://github.com/npm/npm/issues>
03:24:10 
03:24:10 npm ERR! Please include the following file with any support request:
03:24:10 npm ERR!     /hostedpaymentnodeweb-ci-7154/workspace/hostedpaymentnodeweb-ci-7154/npm-debug.log

**Comment by kenany** [comment]
Do you have a `"lint"` script defined in your `package.json`?

**Comment by kenany** [comment]
Closing as abandoned.
