### ISSUE TITLE
npm installation issue

### ISSUE THREAD

**Issue by bhaveshasthana** [npm/npm#17825]
#### I'm opening this issue because:

  - [ ] Getting error while installing npm.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.

Please find attached screenshot of error which i am getting. Please help me to resolve this issue.
![npm-error](https://user-images.githubusercontent.com/30255129/28304653-3edbca56-6bb6-11e7-98a3-6d7eb28abb57.jpg)

**Comment by kenany** [comment]
Does this also occur with newer versions of `npm`?

**Comment by bhaveshasthana** [comment]
Yes with new version also getting the same error...

**Comment by bhaveshasthana** [comment]
please find my npm debug log file for better clarification and understanding.

**Comment by bhaveshasthana** [comment]
33109 silly rollbackFailedOptional Finishing
33110 silly runTopLevelLifecycles Finishing
33111 silly install printInstalled
33112 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\@angular\cli\node_modules\chokidar\node_modules\fsevents):
33113 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
33114 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
33114 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
33114 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
33114 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
33115 warn optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.5.3 (node_modules\@angular\cli\node_modules\node-sass):
33116 warn optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.5.3 install: `node scripts/install.js`
33116 warn optional SKIPPING OPTIONAL DEPENDENCY: spawn C:\windows\system32\cmd.exe;C:\Program Files\MongoDB\Server\3.2\bin\;F:\nodejs ENOENT
33117 verbose optional SKIPPING OPTIONAL DEPENDENCY:
33117 verbose optional Failed at the node-sass@4.5.3 install script 'node scripts/install.js'.
33117 verbose optional SKIPPING OPTIONAL DEPENDENCY: Make sure you have the latest version of node.js and npm installed.
33117 verbose optional SKIPPING OPTIONAL DEPENDENCY: If you do, this is most likely a problem with the node-sass package,
33117 verbose optional SKIPPING OPTIONAL DEPENDENCY: not with npm itself.
33117 verbose optional SKIPPING OPTIONAL DEPENDENCY: Tell the author that this fails on your system:
33117 verbose optional SKIPPING OPTIONAL DEPENDENCY:     node scripts/install.js
33117 verbose optional SKIPPING OPTIONAL DEPENDENCY: You can get information on how to open an issue for this project with:
33117 verbose optional SKIPPING OPTIONAL DEPENDENCY:     npm bugs node-sass
33117 verbose optional SKIPPING OPTIONAL DEPENDENCY: Or if that isn't available, you can get their info via:
33117 verbose optional SKIPPING OPTIONAL DEPENDENCY:     npm owner ls node-sass
33117 verbose optional SKIPPING OPTIONAL DEPENDENCY: There is likely additional logging output above.
33118 warn optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.5.3 (node_modules\@angular\cli\node_modules\node-sass):
33119 warn optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.5.3 install: `node scripts/install.js`
33119 warn optional SKIPPING OPTIONAL DEPENDENCY: Exit status -4058
33120 verbose optional SKIPPING OPTIONAL DEPENDENCY:
33120 verbose optional Failed at the node-sass@4.5.3 install script 'node scripts/install.js'.
33120 verbose optional SKIPPING OPTIONAL DEPENDENCY: Make sure you have the latest version of node.js and npm installed.
33120 verbose optional SKIPPING OPTIONAL DEPENDENCY: If you do, this is most likely a problem with the node-sass package,
33120 verbose optional SKIPPING OPTIONAL DEPENDENCY: not with npm itself.
33120 verbose optional SKIPPING OPTIONAL DEPENDENCY: Tell the author that this fails on your system:
33120 verbose optional SKIPPING OPTIONAL DEPENDENCY:     node scripts/install.js
33120 verbose optional SKIPPING OPTIONAL DEPENDENCY: You can get information on how to open an issue for this project with:
33120 verbose optional SKIPPING OPTIONAL DEPENDENCY:     npm bugs node-sass
33120 verbose optional SKIPPING OPTIONAL DEPENDENCY: Or if that isn't available, you can get their info via:
33120 verbose optional SKIPPING OPTIONAL DEPENDENCY:     npm owner ls node-sass
33120 verbose optional SKIPPING OPTIONAL DEPENDENCY: There is likely additional logging output above.
33121 verbose stack Error: Callback called more than once.
33121 verbose stack     at errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:112:16)
33121 verbose stack     at cb (C:\Program Files\nodejs\node_modules\npm\lib\install.js:236:12)
33121 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install.js:312:7
33121 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:7:26)
33121 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:18:7
33121 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install\and-ignore-errors.js:7:15
33121 verbose stack     at Function.ls.fromTree (C:\Program Files\nodejs\node_modules\npm\lib\ls.js:112:3)
33121 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install.js:707:8
33121 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\iferr\index.js:13:50
33121 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:175:5
33122 verbose cwd C:\Users\bhasthan\second
33123 error Windows_NT 6.3.9600
33124 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli"
33125 error node v6.9.2
33126 error npm  v3.10.9
33127 error Callback called more than once.
33128 error If you need help, you may report this error at:
33128 error     <https://github.com/npm/npm/issues>
33129 verbose exit [ 1, true ]

**Comment by kenany** [comment]
@bhaveshasthana Could you update you `npm` version to at least version 4 or 5? Let me know if that helps :)

**Comment by bhaveshasthana** [comment]
Hi all, its working fine now on my machine...

**Comment by bhaveshasthana** [comment]
Hi All, Again i am getting some error while starting and installing npm. It was working fine earlier i dont know how i am getting error again. Please help me to fix.
![node-issue1](https://user-images.githubusercontent.com/30255129/29964529-f238d4ce-8f27-11e7-98e6-17ab218815ca.jpg)

**Comment by kenany** [comment]
@bhaveshasthana Please see my previous comment :)
