### ISSUE TITLE
Traball.destroy is not a function

### ISSUE THREAD

**Issue by Shani2016** [npm/npm#17820]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by sholladay** [comment]
@Shani2016 you did not fill out the issue template. They are going to close the issue if you don't fix that and give the debugging information it asks for.

**Comment by jcsubmit7** [comment]
I have had this problem many times.
Just run the npm command again and the problem should be sorted
JC

**Comment by kenany** [comment]
Yeah, closing since this is blank.
