### ISSUE TITLE
Help with install cordova-plugin-googlemaps

### ISSUE THREAD

**Issue by agencefacton** [npm/npm#17831]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [*] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### How can the CLI team reproduce the problem?

ionic cordova plugin add cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID="AIz......" --variable API_KEY_FOR_IOS="AIzaS...."

### supporting information:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk',
1 verbose cli   '--save' ]
2 info using npm@3.10.3
3 info using node@v6.4.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk
8 silly fetchOtherPackageData https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk
9 silly cache add args [ 'https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk',
9 silly cache add   null ]
10 verbose cache add spec https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk
11 silly cache add parsed spec Result {
11 silly cache add   raw: 'https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk',
11 silly cache add   scope: null,
11 silly cache add   escapedName: null,
11 silly cache add   name: null,
11 silly cache add   rawSpec: 'https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk',
11 silly cache add   spec: 'git+https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk.git',
11 silly cache add   type: 'hosted',
11 silly cache add   hosted:
11 silly cache add    { type: 'github',
11 silly cache add      ssh: 'git@github.com:mapsplugin/cordova-plugin-googlemaps-sdk.git',
11 silly cache add      sshUrl: 'git+ssh://git@github.com/mapsplugin/cordova-plugin-googlemaps-sdk.git',
11 silly cache add      httpsUrl: 'git+https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk.git',
11 silly cache add      gitUrl: 'git://github.com/mapsplugin/cordova-plugin-googlemaps-sdk.git',
11 silly cache add      shortcut: 'github:mapsplugin/cordova-plugin-googlemaps-sdk',
11 silly cache add      directUrl: 'https://raw.githubusercontent.com/mapsplugin/cordova-plugin-googlemaps-sdk/master/package.json' } }
12 verbose addRemoteGit caching https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk
13 verbose addRemoteGit git+https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk.git is a repository hosted by github
14 silly tryClone cloning git+https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk.git via git+https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk.git
15 verbose tryClone git-https-github-com-mapsplugin-cordova-plugin-googlemaps-sdk-git-324aac43 not in flight; caching
16 verbose correctMkdir C:\Users\Fabien\AppData\Roaming\npm-cache\_git-remotes correctMkdir not in flight; initializing
17 info git [ 'config', '--get', 'remote.origin.url' ]
18 silly validateExistingRemote git+https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk.git remote.origin.url: https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk.git
19 verbose validateExistingRemote git+https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk.git is updating existing cached remote C:\Users\Fabien\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-mapsplugin-cordova-plugin-googlemaps-sdk-git-324aac43
20 info git [ 'fetch', '-a', 'origin' ]
21 error git fetch -a origin (https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk.git) fatal: Unable to find remote helper for 'https'
22 silly fetchPackageMetaData Error: Command failed: git -c core.longpaths=true fetch -a origin
22 silly fetchPackageMetaData fatal: Unable to find remote helper for 'https'
22 silly fetchPackageMetaData
22 silly fetchPackageMetaData     at ChildProcess.exithandler (child_process.js:206:12)
22 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
22 silly fetchPackageMetaData     at ChildProcess.emit (events.js:191:7)
22 silly fetchPackageMetaData     at maybeClose (internal/child_process.js:852:16)
22 silly fetchPackageMetaData     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
22 silly fetchPackageMetaData  error for https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk { Error: Command failed: git -c core.longpaths=true fetch -a origin
22 silly fetchPackageMetaData fatal: Unable to find remote helper for 'https'
22 silly fetchPackageMetaData
22 silly fetchPackageMetaData     at ChildProcess.exithandler (child_process.js:206:12)
22 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
22 silly fetchPackageMetaData     at ChildProcess.emit (events.js:191:7)
22 silly fetchPackageMetaData     at maybeClose (internal/child_process.js:852:16)
22 silly fetchPackageMetaData     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
22 silly fetchPackageMetaData   killed: false,
22 silly fetchPackageMetaData   code: 128,
22 silly fetchPackageMetaData   signal: null,
22 silly fetchPackageMetaData   cmd: 'git -c core.longpaths=true fetch -a origin' }
23 silly rollbackFailedOptional Starting
24 silly rollbackFailedOptional Finishing
25 silly runTopLevelLifecycles Starting
26 silly runTopLevelLifecycles Finishing
27 silly install printInstalled
28 verbose stack Error: Command failed: git -c core.longpaths=true fetch -a origin
28 verbose stack fatal: Unable to find remote helper for 'https'
28 verbose stack
28 verbose stack     at ChildProcess.exithandler (child_process.js:206:12)
28 verbose stack     at emitTwo (events.js:106:13)
28 verbose stack     at ChildProcess.emit (events.js:191:7)
28 verbose stack     at maybeClose (internal/child_process.js:852:16)
28 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
29 verbose cwd F:\Ionic\Speedle\node_modules
30 error Windows_NT 10.0.15063
31 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk" "--save"
32 error node v6.4.0
33 error npm  v3.10.3
34 error code 128
35 error Command failed: git -c core.longpaths=true fetch -a origin
35 error fatal: Unable to find remote helper for 'https'
36 error If you need help, you may report this error at:
36 error     <https://github.com/npm/npm/issues>
37 verbose exit [ 1, true ]

**Comment by Luttik** [comment]
I have the same issue
