### ISSUE TITLE
npm init fails badly if the directory name is invalid

### ISSUE THREAD

**Issue by jwverzijden** [npm/npm#17830]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

and it should not, instead it should ask what name I want this module to have regardless of the directory name.

#### What's going wrong?
I made a new directory it was called "Untitled Folder".
Then I called 'npm init', which outputs:
``` sh
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

See `npm help json` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg>` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "Untitled Folder": Tags may not have any characters that encodeURIComponent encodes.
About to write to /home/jw/desktop/Untitled Folder/package.json:

{
  "name": "",
  "version": ""
}


Is this ok? (yes) no
Aborted.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jw/.npm/_logs/2017-07-18T10_52_19_891Z-debug.log

```

#### How can the CLI team reproduce the problem?
1. make any directory with an invalid name
2. call npm init in the directory

log: https://gist.github.com/crostine/fc68a0bd22df6d82c117cd01740e82d5

### supporting information:

 - `npm -v` prints: 5.1.0
 - `node -v` prints: 8.1.3
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux, Ubuntu 16.04 LTS
 - Network issues:
   - Geographic location where npm was run: Latitude:51.919861051° 55' 11.50'' N Longitude:4.24166704° 14' 30.00'' E

   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
Fixed by npm/init-package-json#71 once it gets merged

**Comment by legodude17** [comment]
Yep that was merged. @KenanY can you close this? Surprised the bot didn't get to it

**Comment by kenany** [comment]
:+1:
