### ISSUE TITLE
NPM issue when running NPM install

### ISSUE THREAD

**Issue by ngcaifeng** [npm/npm#17837]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@1.2.32
3 info using node@v0.10.12
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose read json E:\KuroKirito93\package.json
6 error install Couldn't read dependencies
7 error Error: ENOENT, open 'E:\KuroKirito93\package.json'
8 error If you need help, you may report this log at:
8 error     <http://github.com/isaacs/npm/issues>
8 error or email it to:
8 error     <npm-@googlegroups.com>
9 error System Windows_NT 6.1.7601
10 error command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
11 error cwd E:\KuroKirito93
12 error node -v v0.10.12
13 error npm -v 1.2.32
14 error path E:\KuroKirito93\package.json
15 error code ENOENT
16 error errno 34
17 verbose exit [ 34, true ]

**Comment by kenany** [comment]
Sorry, but your versions of Node and `npm` are years old and are no longer supported.
