### ISSUE TITLE
Heroku bot : Issue to recognize # git commit -m "adding the Procfile" & to make appear worker on ressource Heroku bot screen

### ISSUE THREAD

**Issue by bobmobil** [npm/npm#17836]
#### What's going wrong?

I have already add "Procfile" without spelling mistake and without extension.
When I am doing on my terminal :

git add .
git commit -m "adding the Procfile"

I have this answer : 
On branch master
nothing to commit, working tree clean

And in fact I couldn't see "worker...." on my ressource Heroku bot screen..

### supporting information:

 - `npm -v` prints: 5.0.3
 - `node -v` prints: v8.1.4
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS
 - Network issues: NO
   - Geographic location where npm was run: France

   - [ ] I don't use a proxy, but have limited or unreliable internet access.

 - Container:
   - [ ] I develop using Vagrant on OS X or Linux.

**Comment by kenany** [comment]
@bobmobil I'm gonna close this since this issue tracker is for `npm`-specific issues.
