### ISSUE TITLE
npm uninstall --save node-sass : Unhandled rejection RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by 395779222** [npm/npm#17847]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'uninstall',
1 verbose cli   '--save',
1 verbose cli   'node-sass' ]
2 info using npm@5.0.3
3 info using node@v8.1.3
4 verbose npm-session e18fee13cca2453d
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 error cb() never called!
8 error This is an error with npm itself. Please report this error at:
9 error <https://github.com/npm/npm/issues>

**Comment by kenany** [comment]
Does this also occur with newer versions of `npm`?

**Comment by yubaoquan** [comment]
Same bug in Mac with npm version 5.0.4

**Comment by kenany** [comment]
@yubaoquan How about the latest version?

**Comment by yubaoquan** [comment]
Update to npm 5.3.0, it seems the bug not reproduce anymore. @KenanY

**Comment by 395779222** [comment]
The problem has already been solved.,just delete node-sass files in node_modules then npm install --save node-sass
