### ISSUE TITLE
Invalid name: "@types/node"

### ISSUE THREAD

**Issue by arkany** [npm/npm#17848]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I'm trying to install and run the Electron API demos (https://github.com/electron/electron-api-demos) and after attempting to run npm install && npm start, it's not running. I'm assuming that something is not configured correctly on my side, but I'm not sure what. I installed node & npm just today. Thanks in advance!

#### How can the CLI team reproduce the problem?
Not sure how to reproduce this issue, I don't know how I'm configured differently.

### supporting information:

![npm error](https://user-images.githubusercontent.com/192032/28349659-fb2e2cd4-6bf8-11e7-94f2-306180c6a8ae.png)
#### Logs attached
[npm-debug.log.txt](https://github.com/npm/npm/files/1157957/npm-debug.log.txt)

 - macOS:

**Comment by martingo78** [comment]
Hi, I've solved it running this:

First download the latest node version from node website (Installable) https://nodejs.org
See the "Recommended for most users" version. Today is v6.11.1LTS for JUL-24-2017

Then run:
`npm uninstall`
`npm install npm@latest -g`

To see the electron helloworld demo the standard command to start the app:
`npm start`

I hope it can solve your issue!
