### ISSUE TITLE
 Could not install npm -g

### ISSUE THREAD

**Issue by DannyS95** [npm/npm#17843]
Hello.
I am trying to install npm globally, but it is giving me an error
npm ERR! addLocal Could not install /home/daniel/Documentos/prime-factors
npm ERR! Linux 4.8.0-36-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0

npm ERR! No name provided in package.json
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/daniel/.npm/_logs/2017-07-18T20_41_24_017Z-debug.log
What can be done to fix this? I am using Ubuntu.

**Comment by kenany** [comment]
I think you mean to be doing

```
npm install -g npm
```

**Comment by DannyS95** [comment]
Hello, kenany, that command works, only with sudo though, but i still have a problem, when i type gulp in the terminal it says the gulp modules can't be found, i can link you my project if necessary.

**Comment by kenany** [comment]
If you could upload the error log to <https://gist.github.com/> and link it here, it'll help out a lot. Thanks!

**Comment by kenany** [comment]
Closing as abandoned.
