### ISSUE TITLE
Unable to uninstall tsc

### ISSUE THREAD

**Issue by jshaw-cm** [npm/npm#17842]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### How can the CLI team reproduce the problem?

To reproduce this problem, install tsc and then run the command

`npm uninstall -g tsc`

### supporting information:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\jms219\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'uninstall',
1 verbose cli   '-g',
1 verbose cli   'tsc' ]
2 info using npm@5.0.2
3 info using node@v8.1.2
4 silly install loadCurrentTree
5 silly install readGlobalPackageData
6 silly install loadIdealTree
7 silly install cloneCurrentTreeToIdealTree
8 silly install loadShrinkwrap
9 silly uninstall loadAllDepsIntoIdealTree
10 silly install loadAllDepsIntoIdealTree
11 error cb() never called!
12 error This is an error with npm itself. Please report this error at:
13 error <https://github.com/npm/npm/issues>

**Comment by kenany** [comment]
Does this also occur with the latest version of `npm@5`?

**Comment by jshaw-cm** [comment]
@KenanY 

It does not occur on version 5.3.0, however it doesn't actually delete it.  Here's the message, which is not an error.  tsc appears to be deprecated anyways so I am going to install "ntypescript" and forget about this thread...

`λ npm uninstall -g tsc                                                                                         
npm WARN gentlyRm not removing C:\Users\jms219\AppData\Roaming\npm\tsserver.cmd as it wasn't installed by C:\Us
ers\jms219\AppData\Roaming\npm\node_modules\tsc                                                                
npm WARN gentlyRm not removing C:\Users\jms219\AppData\Roaming\npm\tsc.cmd as it wasn't installed by C:\Users\j
ms219\AppData\Roaming\npm\node_modules\tsc                                                                     
npm WARN gentlyRm not removing C:\Users\jms219\AppData\Roaming\npm\tsserver as it wasn't installed by C:\Users\
jms219\AppData\Roaming\npm\node_modules\tsc                                                                    
npm WARN gentlyRm not removing C:\Users\jms219\AppData\Roaming\npm\tsc as it wasn't installed by C:\Users\jms21
9\AppData\Roaming\npm\node_modules\tsc                                                                         
removed 1 package in 1.558s                                                                                    `
