### ISSUE TITLE
Error installing mocha nodemon mongoose

### ISSUE THREAD

**Issue by deevesh** [npm/npm#17856]
#### I'm opening this issue because:

I'm not able to install using the following command: 
npm install --save mocha nodemon mongoose

**Comment by deevesh** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   'mocha',
1 verbose cli   'nodemon',
1 verbose cli   'mongoose' ]
2 info using npm@3.10.10
3 info using node@v6.11.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData mocha
8 silly fetchPackageMetaData nodemon
9 silly fetchPackageMetaData mongoose
10 silly fetchNamedPackageData mocha
11 silly mapToRegistry name mocha
12 silly mapToRegistry using default registry
13 silly mapToRegistry registry https://registry.npmjs.org/
14 silly mapToRegistry data Result {
14 silly mapToRegistry   raw: 'mocha',
14 silly mapToRegistry   scope: null,
14 silly mapToRegistry   escapedName: 'mocha',
14 silly mapToRegistry   name: 'mocha',
14 silly mapToRegistry   rawSpec: '',
14 silly mapToRegistry   spec: 'latest',
14 silly mapToRegistry   type: 'tag' }
15 silly mapToRegistry uri https://registry.npmjs.org/mocha
16 silly fetchNamedPackageData nodemon
17 silly mapToRegistry name nodemon
18 silly mapToRegistry using default registry
19 silly mapToRegistry registry https://registry.npmjs.org/
20 silly mapToRegistry data Result {
20 silly mapToRegistry   raw: 'nodemon',
20 silly mapToRegistry   scope: null,
20 silly mapToRegistry   escapedName: 'nodemon',
20 silly mapToRegistry   name: 'nodemon',
20 silly mapToRegistry   rawSpec: '',
20 silly mapToRegistry   spec: 'latest',
20 silly mapToRegistry   type: 'tag' }
21 silly mapToRegistry uri https://registry.npmjs.org/nodemon
22 silly fetchNamedPackageData mongoose
23 silly mapToRegistry name mongoose
24 silly mapToRegistry using default registry
25 silly mapToRegistry registry https://registry.npmjs.org/
26 silly mapToRegistry data Result {
26 silly mapToRegistry   raw: 'mongoose',
26 silly mapToRegistry   scope: null,
26 silly mapToRegistry   escapedName: 'mongoose',
26 silly mapToRegistry   name: 'mongoose',
26 silly mapToRegistry   rawSpec: '',
26 silly mapToRegistry   spec: 'latest',
26 silly mapToRegistry   type: 'tag' }
27 silly mapToRegistry uri https://registry.npmjs.org/mongoose
28 verbose request uri https://registry.npmjs.org/mocha
29 verbose request no auth needed
30 info attempt registry request try #1 at 2:41:41 PM
31 verbose request id 5ccc0173614958ce
32 http request GET https://registry.npmjs.org/mocha
33 verbose request uri https://registry.npmjs.org/nodemon
34 verbose request no auth needed
35 info attempt registry request try #1 at 2:41:41 PM
36 http request GET https://registry.npmjs.org/nodemon
37 verbose request uri https://registry.npmjs.org/mongoose
38 verbose request no auth needed
39 info attempt registry request try #1 at 2:41:41 PM
40 http request GET https://registry.npmjs.org/mongoose
41 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
42 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
43 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
44 info attempt registry request try #2 at 2:41:52 PM
45 http request GET https://registry.npmjs.org/mongoose
46 info attempt registry request try #2 at 2:41:52 PM
47 http request GET https://registry.npmjs.org/mocha
48 info attempt registry request try #2 at 2:41:52 PM
49 http request GET https://registry.npmjs.org/nodemon
50 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
51 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
52 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
53 info attempt registry request try #3 at 2:42:53 PM
54 http request GET https://registry.npmjs.org/mongoose
55 info attempt registry request try #3 at 2:42:53 PM
56 http request GET https://registry.npmjs.org/mocha
57 info attempt registry request try #3 at 2:42:53 PM
58 http request GET https://registry.npmjs.org/nodemon
59 silly fetchPackageMetaData Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
59 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1018:11)
59 silly fetchPackageMetaData     at errnoException (dns.js:33:15)
59 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
59 silly fetchPackageMetaData  error for mongoose { Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
59 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1018:11)
59 silly fetchPackageMetaData     at errnoException (dns.js:33:15)
59 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
59 silly fetchPackageMetaData   code: 'EAI_AGAIN',
59 silly fetchPackageMetaData   errno: 'EAI_AGAIN',
59 silly fetchPackageMetaData   syscall: 'getaddrinfo',
59 silly fetchPackageMetaData   hostname: 'registry.npmjs.org',
59 silly fetchPackageMetaData   host: 'registry.npmjs.org',
59 silly fetchPackageMetaData   port: 443 }
60 silly fetchPackageMetaData Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
60 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1018:11)
60 silly fetchPackageMetaData     at errnoException (dns.js:33:15)
60 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
60 silly fetchPackageMetaData  error for mocha { Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
60 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1018:11)
60 silly fetchPackageMetaData     at errnoException (dns.js:33:15)
60 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
60 silly fetchPackageMetaData   code: 'EAI_AGAIN',
60 silly fetchPackageMetaData   errno: 'EAI_AGAIN',
60 silly fetchPackageMetaData   syscall: 'getaddrinfo',
60 silly fetchPackageMetaData   hostname: 'registry.npmjs.org',
60 silly fetchPackageMetaData   host: 'registry.npmjs.org',
60 silly fetchPackageMetaData   port: 443 }
61 silly fetchPackageMetaData Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
61 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1018:11)
61 silly fetchPackageMetaData     at errnoException (dns.js:33:15)
61 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
61 silly fetchPackageMetaData  error for nodemon { Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
61 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1018:11)
61 silly fetchPackageMetaData     at errnoException (dns.js:33:15)
61 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
61 silly fetchPackageMetaData   code: 'EAI_AGAIN',
61 silly fetchPackageMetaData   errno: 'EAI_AGAIN',
61 silly fetchPackageMetaData   syscall: 'getaddrinfo',
61 silly fetchPackageMetaData   hostname: 'registry.npmjs.org',
61 silly fetchPackageMetaData   host: 'registry.npmjs.org',
61 silly fetchPackageMetaData   port: 443 }
62 silly rollbackFailedOptional Starting
63 silly rollbackFailedOptional Finishing
64 silly runTopLevelLifecycles Finishing
65 silly install printInstalled
66 verbose stack Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
66 verbose stack     at Object.exports._errnoException (util.js:1018:11)
66 verbose stack     at errnoException (dns.js:33:15)
66 verbose stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
67 verbose cwd C:\Users\deevesh.prayag\Desktop\MongoDB\Workspace
68 error Windows_NT 6.3.9600
69 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "mocha" "nodemon" "mongoose"
70 error node v6.11.1
71 error npm  v3.10.10
72 error code EAI_AGAIN
73 error errno EAI_AGAIN
74 error syscall getaddrinfo
75 error getaddrinfo EAI_AGAIN registry.npmjs.org:443
76 error If you need help, you may report this error at:
76 error     <https://github.com/npm/npm/issues>
77 verbose exit [ 1, true ]

**Comment by linuxchip** [comment]
May be the issue with internet connectivity / proxy connection if you are using ?

Just check whether you are able to reach https://registry.npmjs.org/ this. If yes, try to set below things

npm config set proxy http://[Host]:[Port]
npm config set https-proxy http://[Host]:[Port]
