### ISSUE TITLE
Web API : Question

### ISSUE THREAD

**Issue by sharadgit1** [npm/npm#17854]
I have been asked a question: If I write code for entering data in database under "GET" call of HTTP using webapi, then what would happened? Also how I restrict that I would write only data retrieving code?

namespace ProductsApp.Controllers
{
    public class ProductsController : ApiController
    {       
        public IEnumerable<Product> GetAllProducts()
        {
	    // here if I write code for data insertion, then what would happen?

	    // How would I restrict that only data retrieving code should be here?

            return products;
        }
    }
}
In normal practice, we write code to retrieve data from database under GET. So, I don't know what would be happened.

Any help would be highly appreciated

**Comment by kenany** [comment]
This issue tracker is for bugs/feature requests for the `npm` CLI, not for Web API support, hence why I'm closing this. I suggest you take this question to some other forum where you can find other Web API users. Good luck!
