### ISSUE TITLE
npm run dev and npm-windows-upgrade error

### ISSUE THREAD

**Issue by xv3n0m** [npm/npm#17872]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
npm run dev for the Laravel 5.4 error, i tried to upgrade node.js and npm is also error

#### How can the CLI team reproduce the problem?
below attach file debug npm log

[npm-debug.txt](https://github.com/npm/npm/files/1164253/npm-debug.txt)

**Comment by Pisi-Deff** [comment]
```
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--global',
1 verbose cli   '--production',
1 verbose cli   'npm-wndows-upgrade' ]
```

Just a typo when you're calling node:
>npm-**wn**dows-upgrade  

the correct one:
>npm-w**I**ndows-upgrade

**Comment by xv3n0m** [comment]
thank you so much
