### ISSUE TITLE
can't update npm or install a package 

### ISSUE THREAD

**Issue by selvodka** [npm/npm#17878]
when i run npm i get this
"module.js:487
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/npm/lib/utils/unsupported.js:2:14)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
" 
running node version 8.1.4 and npm 5.3.0-1

**Comment by MuraraAllan** [comment]
Do you installed any package before run "npm" ? 

try to use `npm install semver`.

You can get a list of packages and their dependency by running `npm list ` - or `npm list -g` to check globally.

Post the results for us then, please? :) Thanks

**Comment by selvodka** [comment]
it happened when i tried to update the system https://pastebin.com/raw/n3kGMuiR then i removed  all of them then i updated the system before that it showed me this https://pastebin.com/raw/AbNz04h0 so i reinstalled npm via pacman   
all three give the output are the same as above

**Comment by MuraraAllan** [comment]
`npm install --force `

is my last Guess, if it doesnt work i can't help.

**Comment by selvodka** [comment]
thx @MuraraAllan but still the same output

**Comment by jokeyrhyme** [comment]
There was a bug in early 5.x versions of `npm`. Ensure you have the latest (fixed) version of `npm`:

-   `npm install --global npm`

**Comment by selvodka** [comment]
same output as always

**Comment by ferarnoled** [comment]
Same problem here. 
Node version: v8.2.1
npm version: 5.3.0

I installed it using [nvm windows](https://github.com/coreybutler/nvm-windows)

**Comment by kenany** [comment]
Perhaps try reinstalling `npm`? Looks like you are somehow missing a dependency.

**Comment by selvodka** [comment]
reinstalled via pacman still the same output

**Comment by selvodka** [comment]
so i installed semver via pacman and now it works but when i try to update "npm update -g " it gives me ths output nhandled rejection Error: ENOENT: no such file or directory, stat '/build/semver/src/semver-5.4.1.tgz'

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-07-27T14_37_33_026Z-debug.log

in the log file https://pastebin.com/raw/HDsiKRH9

**Comment by threehams** [comment]
On Windows, this is very likely being caused by https://github.com/npm/npm/issues/17894 and related to https://github.com/coreybutler/nvm-windows/issues/293. Check your node_modules folder for npm:
C:\Program Files\nodejs\node_modules\npm\node_modules

If the list of modules ends with libnpx, you're hitting the linked issue. `nvm windows` can silently fail when installing libnpx on Windows 10, and therefore fails to install `semver` or any other package alphabetically after it.

libnpx was introduced in node 8.2.0. So, for now, node 8.1.4 (packaged with npm 5.0.3) will work.

**Comment by darkbasic** [comment]
It's a packaging bug in Arch, just install both npm and semver through npm itself: https://bbs.archlinux.org/viewtopic.php?id=228174

**Comment by selvodka** [comment]
i did "sudo npm i -g npm semver" and tried to update "sudo npm update -g" still the same problem my log https://pastebin.com/raw/yBXfpCa3
