### ISSUE TITLE
Error: Missing required argument #2 - deps.js:475:3

### ISSUE THREAD

**Issue by joshdean2000** [npm/npm#17871]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Getting error when attempting to upgrade packages

Also it produces a .log file, which is not in the permitted list of extensions when uploading files to issue so should either be changed to .txt or added to supported list.

#### How can the CLI team reproduce the problem?

No idea, just reporting because that's what the output said to do.

**Comment by joshdean2000** [comment]
<pre>

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\Web\\External\\Node.exe',
1 verbose cli   'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\Web\\External\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@3.3.4
3 info using node@v5.4.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly install normalizeTree
8 verbose stack Error: Missing required argument #2
8 verbose stack     at exports.findRequirement (C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Web\External\node_modules\npm\lib\install\deps.js:475:3)
8 verbose stack     at C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Web\External\node_modules\npm\lib\install\deps.js:90:19
8 verbose stack     at zalgoSafe (C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Web\External\node_modules\dezalgo\dezalgo.js:20:10)
8 verbose stack     at finalize (C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Web\External\node_modules\realize-package-specifier\index.js:37:5)
8 verbose stack     at C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Web\External\node_modules\realize-package-specifier\index.js:22:20
8 verbose stack     at C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Web\External\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
8 verbose stack     at FSReqWrap.oncomplete (fs.js:82:15)
9 verbose cwd C:\Git\Repos\ConcertAdmin\Source\Finivation.Concert.Configuration\Finivation.Concert.Configuration.Web
10 error Windows_NT 10.0.15063
11 error argv "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\Web\\External\\Node.exe" "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\Web\\External\\node_modules\\npm\\bin\\npm-cli.js" "install"
12 error node v5.4.1
13 error npm  v3.3.4
14 error code EMISSINGARG
15 error typeerror Error: Missing required argument #2
15 error typeerror     at exports.findRequirement (C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Web\External\node_modules\npm\lib\install\deps.js:475:3)
15 error typeerror     at C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Web\External\node_modules\npm\lib\install\deps.js:90:19
15 error typeerror     at zalgoSafe (C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Web\External\node_modules\dezalgo\dezalgo.js:20:10)
15 error typeerror     at finalize (C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Web\External\node_modules\realize-package-specifier\index.js:37:5)
15 error typeerror     at C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Web\External\node_modules\realize-package-specifier\index.js:22:20
15 error typeerror     at C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Web\External\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
15 error typeerror     at FSReqWrap.oncomplete (fs.js:82:15)
15 error typeerror This is an error with npm itself. Please report this error at:
15 error typeerror     <http://github.com/npm/npm/issues>
16 verbose exit [ 1, true ]
</pre>

**Comment by kenany** [comment]
Does this also occur with the latest stable release of Node and `npm`?

**Comment by joshdean2000** [comment]
I installed the latest and the error changed.

There was an issue in the package.json with invalid dependency "@angular/common/http ": "~4.3.1".  Including the space in the name.  Not sure if this is what was causing the issue or something else that has been fixed in latest version.

**Comment by joshdean2000** [comment]
<pre>
    "@angular/common/http ": "~4.3.1",
</pre>
