### ISSUE TITLE
cb () never called

### ISSUE THREAD

**Issue by ghost** [npm/npm#17873]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [X] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:  5.3.0
 - `node -v` prints: 8.2.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [X] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [X] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by blacktemplar** [comment]
Same problem here:

npm -v: 5.3.0
node -v: 8.1.4

I am using Arch Linux

**Comment by kenany** [comment]
Could anyone provide more information on this? Steps to reproduce? Debug log?

**Comment by ghost** [comment]
oh yes. I forgot to mention : i did `npm install -S webpack`

**Comment by kenany** [comment]
And can you upload the debug log to <https://gist.github.com/> and link it here? Thanks!

**Comment by ghost** [comment]
https://gist.github.com/earthyearth/79c3909401181a37bf6db34aa1e08d74

**Comment by ghost** [comment]
i tried install connect/express and got the same responses too

**Comment by ghost** [comment]
I was using iterm2 for webpack/connect/express, but connect worked on terminal.

**Comment by ghost** [comment]
hey, I kept on spamming npm install webpack and it worked somehow

**Comment by N6REJ** [comment]
@KenanY does this help?
```
Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>f:

F:\>cd neard\bin\nodejs

F:\neard\bin\nodejs>dir
 Volume in drive F has no label.
 Volume Serial Number is A2A7-D9C3

 Directory of F:\neard\bin\nodejs

18-Jul-17  21:51    <DIR>          .
18-Jul-17  21:51    <DIR>          ..
28-Jun-17  03:33                94 README.txt
13-Jul-17  07:21    <DIR>          nodejs8.1.4
               1 File(s)             94 bytes
               3 Dir(s)  118,079,848,448 bytes free

F:\neard\bin\nodejs>cd nodejs8.1.4

F:\neard\bin\nodejs\nodejs8.1.4>npm install uglify-js
Unhandled rejection Error: ENOENT: no such file or directory, stat 'F:\neard\tmp\npm-cache\_cacache\content-v2\sha512\25\ec\0ffd9c7a278f3d6575c97c0d43c027f366ec857c7e6defcbeb8efa961d2e50af6e5f7e18eb05131700359dc6f66f9a372a364b4ccd370cd1bc7b1ddef79f'

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     F:\neard\tmp\npm-cache\_logs\2017-07-24T01_34_10_877Z-debug.log

F:\neard\bin\nodejs\nodejs8.1.4>
```
