### ISSUE TITLE
Unable to install dependencies of local package

### ISSUE THREAD

**Issue by ajithr** [npm/npm#17885]
#### I'm opening this issue because:

  - [x] npm is producing an incorrect install.

#### What's going wrong?
Dependencies of local packages are not installed

#### How can the CLI team reproduce the problem?

When the package dependency have local reference, the local package dependencies not installing on `npm install`

1. Set a local package reference in your `package.json`.
```
dependencies: {
    test: "file:../test"
}
```
2. Now run npm install from main project.
3. The dependencies of local package `test` is not installed.
4. The local package only symlinked in `node_modules`.

### supporting information:

 - `npm -v` prints: 5.3.0
 - `node -v` prints: 8.2.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows 10

**Comment by maulikdadhaniya** [comment]
check your package.json file. if there is "name: 'file'"plz change this package.json file and give any name like "name : 'file-name'".

**Comment by kenany** [comment]
@ajithr I cannot reproduce this myself with `npm@5.3.0`. Could you provide a minimal repro case as a git repo perhaps?

**Comment by mkp05** [comment]
Hi, here is sample repo https://github.com/mkp05/npm-local-dep-error

When you run
`npm install`
in _pack2_ only symlink is being created but _angular/core dependency_ present in _pack1_ is not being installed).
