### ISSUE TITLE
I am trying to install mysql module "npm install mysql" .but it can't and throwing error. What can i do? 

### ISSUE THREAD

**Issue by maulikdadhaniya** [npm/npm#17886]
E:\nodeproject\mysql>npm install mysql
npm ERR! Windows_NT 6.1.7600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "mysql"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ENOSELF

npm ERR! Refusing to install mysql as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     E:\nodeproject\mysql\npm-debug.log

**Comment by kenany** [comment]
@maulikdadhaniya Could you check your `package.json` and make sure you have not set the `"name"` property to `"mysql"`? If it _is_ set to that, try making it something more unique.

**Comment by kenany** [comment]
Closing due to no reply.
