### ISSUE TITLE
Unable to unpublish the module that published less than 24 hours

### ISSUE THREAD

**Issue by izziewong** [npm/npm#17887]
## I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Got `Registry returned 400 for DELETE` error when I tried to unpublish the module that has been published in 24 hours.

#### How can the CLI team reproduce the problem?
`npm unpublish syw-uikit@0.1.0 --force`

### supporting information:

 - `npm -v` prints: 3.10.10
 - `node -v` prints: v6.11.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by romski** [comment]
I also have this issue:

npm 3.10.10
node 6.9.4
registry https://registry.npmjs.org/
macOS
