### ISSUE TITLE
cannot update npm !!!

### ISSUE THREAD

**Issue by K41R1** [npm/npm#17891]
#### I'm opening this issue because:

  - [*] Other (_see below for feature requests_):

#### What's going wrong?
**tried to update npm**
sudo pacman -Syu  
**got this error**
https://gist.github.com/KhairiAbidi/aeb97161ade13ec2513818f54cd70306

### supporting information:

 - `npm -v` 5.3.0:
 - `node -v` 8.2.1:
 - `npm config get registry` https://registry.npmjs.org/:
 - AntergosLinux amd64:

**Comment by kenany** [comment]
Perhaps you need to do?:

```bash
pacman -Syu --force
```

**Comment by K41R1** [comment]
got same error !!!
