### ISSUE TITLE
npm ERR! notarget No matching version found for react-router-dom@next

### ISSUE THREAD

**Issue by askaper** [npm/npm#17904]
#### I'm opening this issue because:

  - [] npm is crashing.
  - [] npm is producing an incorrect install.
  - [X] npm is doing something I don't understand.
  - [] Other (_see below for feature requests_):

#### What's going wrong?

Dependency is not being found during installation. 

#### How can the CLI team reproduce the problem?
My best guess would be to npm install any web application that has the ``"react-router-dom": "next"`` in package.json

Log file can be found here:     **https://gist.github.com/askaper/14c4008e6efcf38ed38f46b65c818f43**

### supporting information:

 - `npm -v` prints: 5.3.0
 - `node -v` prints: v8.2.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: OS X
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [X] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by linuxchip** [comment]
May be the version you have specified, or one of your dependencies specified is not published to npmjs.com

You can check the available versions of a package with npm view CLI command

Thanks

**Comment by askaper** [comment]
Entirely uninstalled and reinstalled node

Replaced ``"react-router-dom": "next"`` in package.json with ``"react-router-dom": "4.1.2"`` and this completed the build. 

If an application has this line under dependencies for a ``create-react-app`` application, this may pose an issue for other developers. 

As for compatibility with the app I'm developing? I'm not too sure what version was used or is intended to be used.
