### ISSUE TITLE
MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by githubfri** [npm/npm#17902]
#### I'm opening this issue because:

  - [x] **npm is crashing**.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Since updating to npm 5.0.3, I get the following error whenever I try to publish or install:
npm ERR! code MODULE_NOT_FOUND
npm ERR! cannot find module 'internal/fs'
#### How can the CLI team reproduce the problem?
install the latest npm on windows 7?

sorry, cannot copy directly the logs,the top of the stack is:
Function.Module._resolvFileName(module.js:485:15)
Function.Module._laod(module.js:437:25)
Module.require(module.js:513:17)

### supporting information:

 - `npm -v` prints:
5.3.0
 - `node -v` prints:
v8.2.1
 
 - Windows, OS X/macOS, or Linux?:
windows

**Comment by linuxchip** [comment]
Do the below things to fix :+1: 

Delete your global node_modules and local node_modules directory if any

Delete ~./node 

Re install node

Hopefully these will fix

Thanks
