### ISSUE TITLE
unable to install npm install whatwg-fetch --save

### ISSUE THREAD

**Issue by Ani4ket** [npm/npm#17915]
#### I'm opening this issue because:
npm install whatwg-fetch --save is not wrking getting the below error.Pls help.

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'whatwg-fetch',
1 verbose cli   '--save' ]
2 info using npm@3.10.10
3 info using node@v6.11.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData whatwg-fetch
8 silly fetchNamedPackageData whatwg-fetch
9 silly mapToRegistry name whatwg-fetch
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'whatwg-fetch',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'whatwg-fetch',
12 silly mapToRegistry   name: 'whatwg-fetch',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/whatwg-fetch
14 verbose request uri https://registry.npmjs.org/whatwg-fetch
15 verbose request no auth needed
16 info attempt registry request try #1 at 1:58:14 AM
17 verbose request id 3c1cd4273d3d2b6a
18 http request GET https://registry.npmjs.org/whatwg-fetch
19 info retry will retry, error on last attempt: Error: unable to get local issuer certificate
20 info attempt registry request try #2 at 1:58:24 AM
21 http request GET https://registry.npmjs.org/whatwg-fetch
22 info retry will retry, error on last attempt: Error: unable to get local issuer certificate
23 info attempt registry request try #3 at 1:59:24 AM
24 http request GET https://registry.npmjs.org/whatwg-fetch
25 silly fetchPackageMetaData Error: unable to get local issuer certificate
25 silly fetchPackageMetaData     at Error (native)
25 silly fetchPackageMetaData     at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
25 silly fetchPackageMetaData     at emitNone (events.js:86:13)
25 silly fetchPackageMetaData     at TLSSocket.emit (events.js:185:7)
25 silly fetchPackageMetaData     at TLSSocket._finishInit (_tls_wrap.js:610:8)
25 silly fetchPackageMetaData     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)
25 silly fetchPackageMetaData  error for whatwg-fetch { Error: unable to get local issuer certificate
25 silly fetchPackageMetaData     at Error (native)
25 silly fetchPackageMetaData     at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
25 silly fetchPackageMetaData     at emitNone (events.js:86:13)
25 silly fetchPackageMetaData     at TLSSocket.emit (events.js:185:7)
25 silly fetchPackageMetaData     at TLSSocket._finishInit (_tls_wrap.js:610:8)
25 silly fetchPackageMetaData     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38) code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY' }
26 silly rollbackFailedOptional Starting
27 silly rollbackFailedOptional Finishing
28 silly runTopLevelLifecycles Finishing
29 silly install printInstalled
30 verbose stack Error: unable to get local issuer certificate
30 verbose stack     at Error (native)
30 verbose stack     at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
30 verbose stack     at emitNone (events.js:86:13)
30 verbose stack     at TLSSocket.emit (events.js:185:7)
30 verbose stack     at TLSSocket._finishInit (_tls_wrap.js:610:8)
30 verbose stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)
31 verbose cwd D:\SPOT_LATEST\P04A\SPOT\spot_web
32 error Windows_NT 10.0.14393
33 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "whatwg-fetch" "--save"
34 error node v6.11.0
35 error npm  v3.10.10
36 error code UNABLE_TO_GET_ISSUER_CERT_LOCALLY
37 error unable to get local issuer certificate
38 error If you need help, you may report this error at:
38 error     <https://github.com/npm/npm/issues>
39 verbose exit [ 1, true ]

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by linuxchip** [comment]
You can solve this in two ways:

1. Set ssl to false like below
    npm config set strict-ssl false

2. Add your CA to include your company certificate chain like below
    npm config set cafile="CAfile.pem"

Thanks

**Comment by Ani4ket** [comment]
Thank you very much. it works

**Comment by linuxchip** [comment]
Great, enjoy

**Comment by linuxchip** [comment]
You can close this issue if it works
