### ISSUE TITLE
npm update does not do anything

### ISSUE THREAD

**Issue by pronebird** [npm/npm#17911]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [X] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

NPM update does not work:

```
➜  ~ npm ls -g flow-bin
/usr/local/lib
└── flow-bin@0.49.1 

➜  ~ npm update -g flow-bin
➜  ~ npm ls -g flow-bin    
/usr/local/lib
└── flow-bin@0.49.1 
➜  ~ npm info flow-bin | grep version:
  version: '0.51.0',
```

`npm update -g flow-bin` – No output. 💩 Nothing. Still old version installed 💩

Then I run `npm i flow-bin -g` and it magically installs the latest version.

For the contrast, `yarn upgrade` works, I don't think `npm update` ever worked since its first appearance:

```
# updating local flow-bin
➜  ~ ✗ npm update flow-bin
➜  ~ ✗ npm --version
5.3.0
➜  ~ ✗ yarn upgrade flow-bin
yarn upgrade v0.27.5
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Rebuilding all packages...
success Saved lockfile.
success Saved 1 new dependency.
└─ flow-bin@0.51.0
Done in 10.72s.
```

ps: I am aware of https://github.com/npm/npm/issues/1262

### supporting information:

 - `npm -v` prints: 5.3.0
 - `node -v` prints: 8.1.3
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by strugee** [comment]
@pronebird please use the issue template: https://raw.githubusercontent.com/npm/npm/latest/.github/issue_template.md

We need stuff like your npm version, platform, etc. in order to actually help you.

**Comment by pronebird** [comment]
@strugee updated the issue as per your suggestion using the template.

**Comment by Kenya-West** [comment]
Same here! Does not update any dependencies and `npm outdated` sees only 2-3 packages.

My `package,json`:
```
{
  "name": "test",
  "version": "0.0.2",
  "description": "test",
  "scripts": {
    "start": "concurrently \"tsc -w\" \"lite-server\" ",
    "lint": "tslint ./app/**/*.ts -t verbose",
    "lite": "lite-server",
    "tsc": "tsc",
    "tsc:w": "tsc -w"
  },
  "keywords": [],
  "author": "",
  "license": "MIT",
  "dependencies": {
    "@angular/animations": "^4.2.2",
    "@angular/common": "^4.2.2",
    "@angular/compiler": "^4.2.2",
    "@angular/core": "^4.2.2",
    "@angular/forms": "^4.2.2",
    "@angular/http": "^4.2.2",
    "@angular/platform-browser": "^4.2.2",
    "@angular/platform-browser-dynamic": "^4.2.2",
    "@angular/router": "^4.2.2",
    "angular-in-memory-web-api": "^0.3.2",
    "bootstrap": "^4.0.0-alpha.6",
    "core-js": "^2.4.1",
    "mongoose": "^4.10.6",
    "reflect-metadata": "^0.1.10",
    "rxjs": "^5.4.0",
    "smoothscroll": "^0.3.0",
    "systemjs": "^0.20.13",
    "tether": "^1.4.0",
    "uuid": "^3.0.1",
    "zone.js": "^0.8.12"
  },
  "devDependencies": {
    "@types/node": "^7.0.31",
    "@types/selenium-webdriver": "^3.0.4",
    "canonical-path": "0.0.2",
    "concurrently": "^3.4.0",
    "http-server": "^0.10.0",
    "less": "^2.7.2",
    "lite-server": "^2.3.0",
    "lodash": "^4.17.4",
    "plugin-typescript": "^7.0.6",
    "rimraf": "^2.6.1",
    "tslint": "^5.4.3",
    "typescript": "^2.4.0",
    "webdriver-manager": "12.0.6"
  },
  "repository": {}
}
```

And `npm outdated` shows only:
![npm_outdated_problem_1](https://user-images.githubusercontent.com/12271104/28825070-bbae764c-76ff-11e7-8255-f52f4aef551d.png)

**Comment by pronebird** [comment]
@npm-robot "We're closing this support issue as it has gone __three days__ without activity".

I'd say three months without activity. It's not a support request, but a bug report for NPM CLI.

**Comment by ip** [comment]
Same here for the latest version of npm:

![image](https://user-images.githubusercontent.com/1111008/32995067-a1008baa-cd80-11e7-8333-0c38a3348c40.png)

**Comment by pronebird** [comment]
@strugee I believe the bot closed this issue by mistake.

**Comment by MickL** [comment]
Same here!

node: v9.2.0 
npm: 5.5.1

**Comment by stoplion** [comment]
Happening to me too. Would be nice if this would actually work..

**Comment by pronebird** [comment]
I can no longer reproduce that in npm 6.1.0. So probably this has been fixed sometime between npm 5.5.1 and npm 6.1.0. In fact `npm update something` automatically updates `package.json` as well. 🎉

**Comment by ip** [comment]
@KenanY I wonder why this was labeled as "support".

**Comment by austintackaberry** [comment]
I am having this issue with npm 6.1.0 and node 8.11.2

`react` latest version is 16.4.0. In my `package.json`, I have `^16.3.0`, and when I run `npm update`, nothing happens. If I run `npm update react`, nothing happens. Only when running `npm install react` does it update to the latest verison.
