### ISSUE TITLE
run npm install -g cordova comes out cb() never called!

### ISSUE THREAD

**Issue by JaydenChu** [npm/npm#17916]
when i run npm install -g cordova comes out cb() never called!

here is the log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/8.2.1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'cordova' ]
2 info using npm@5.3.0
3 info using node@v8.2.1
4 verbose npm-session 797dfad96904727d
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 warn registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
8 http fetch GET 200 https://registry.npmjs.org/cordova 70076ms (from cache)
9 silly pacote tag manifest for cordova@latest fetched in 70121ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 silly install loadShrinkwrap
13 silly install loadAllDepsIntoIdealTree
14 silly resolveWithNewModule cordova@7.0.1 checking installable status
15 http fetch GET 200 https://registry.npmjs.org/configstore 70053ms (from cache)
16 silly pacote version manifest for configstore@2.1.0 fetched in 70057ms
17 silly resolveWithNewModule configstore@2.1.0 checking installable status
18 http fetch GET 200 https://registry.npmjs.org/cordova-lib 71122ms (from cache)
19 silly pacote version manifest for cordova-lib@7.0.1 fetched in 71137ms
20 silly resolveWithNewModule cordova-lib@7.0.1 checking installable status
21 http fetch GET 200 https://registry.npmjs.org/insight 72154ms (from cache)
22 silly pacote version manifest for insight@0.8.2 fetched in 72157ms
23 silly resolveWithNewModule insight@0.8.2 checking installable status
24 http fetch GET 200 https://registry.npmjs.org/q 73184ms (from cache)
25 silly pacote version manifest for q@1.0.1 fetched in 73187ms
26 silly resolveWithNewModule q@1.0.1 checking installable status
27 error cb() never called!
28 error This is an error with npm itself. Please report this error at:
29 error <https://github.com/npm/npm/issues>

**Comment by linuxchip** [comment]
Try doing below thing once 

npm cache clean

After this try once

Thanks

**Comment by claudiuconstantin** [comment]
@linuxchip got the `cache clean` thing, but not the rest... any _ctrl+v_ issues?

**Comment by linuxchip** [comment]
@claudiuconstantin  I didn't got you.

After clean did you tried install again ??

**Comment by claudiuconstantin** [comment]
Oh, by "After this try once" you meant "npm install" :D

**Comment by linuxchip** [comment]
Yes right  :-)

**Comment by JaydenChu** [comment]
i have tried the cache clean --f instead of cache clean. however, it didn't wok.
