### ISSUE TITLE
npm configurate proxy

### ISSUE THREAD

**Issue by surpi** [npm/npm#17921]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?

Can't properly define the proxy in npm config

#### How can the CLI team reproduce the problem?
i don't know

After several tries I could not configure my proxy to use it for npm. I've tried several ways (including deactivating strict-ssl and putting my credentials into proxy settings).

### supporting information:

npm-debug file:
<script src="https://gist.github.com/surpi/e0ad6013237c426ff37409b92a574123.js"></script>

 - `npm -v` prints: 3.10.10
 - `node -v` prints: v6.11.1
 - `npm config get registry` prints: http://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows
 - Network issues:
   - Geographic location where npm was run:
   - [x] I use a proxy to connect to the npm registry.   (at least i try to)
   - [x] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.  (not sure, did not configure it)
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by surpi** [comment]
fixed the problem - more or less. The problem was with the Proxy, we configured another one now. Now I am having the following issue when trying to run "npm install -g nativescript": 

attempt registry request try #3 at 13:46:37
npm http request GET https://registry.npmjs.org/nativescript
npm verb stack Error: tunneling socket could not be established, cause=write EPROTO 140735813116864:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:
npm verb stack 
npm verb stack     at ClientRequest.onError (/usr/local/lib/node_modules/npm/node_modules/request/node_modules/tunnel-agent/index.js:176:17)
npm verb stack     at ClientRequest.g (events.js:292:16)
npm verb stack     at emitOne (events.js:96:13)
npm verb stack     at ClientRequest.emit (events.js:188:7)
npm verb stack     at TLSSocket.socketErrorListener (_http_client.js:309:9)
npm verb stack     at emitOne (events.js:96:13)
npm verb stack     at TLSSocket.emit (events.js:188:7)
npm verb stack     at onwriteError (_stream_writable.js:343:10)
npm verb stack     at onwrite (_stream_writable.js:361:5)
npm verb stack     at WritableState.onwrite (_stream_writable.js:90:5)
npm verb cwd /Users/admin
npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "nativescript"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ECONNRESET

**Comment by alundiak** [comment]
Looks similar to  https://github.com/npm/npm/issues/18145#issuecomment-326803706, and I'm wondering why somany people have this kinda-Proxy-issue? I don't know even whome to ask from #NPM maybe @npm-robot? maybe @isaacs maybe @iarna ?

I also had this issue with vue-cli (https://github.com/npm/npm/issues/15604) and setting registry to https helped me.
```
npm config set registry https://registry.npmjs.org/
```
But with autrelia (issue https://github.com/aurelia/skeleton-navigation/issues/857) installation globally did not helped me. UPD: at first time. But after a few days, I did change HTTP=> HTTPS => HTTP => HTTPS and magically helped me.

**Comment by alundiak** [comment]
@surpi try setting to HTTPS, and if works, I guess this issue can be closed. But still it remains open question - what is going on with NPM registry setting and Proxy stuff?
