### ISSUE TITLE
NPM ERR! Invalid

### ISSUE THREAD

**Issue by ngassamcharles** [npm/npm#17923]
I have  problem with my npm (v 2.15.12)
When I write "npm list" I have many packages with err extraneous but, with "npm prune" i resolved it. Now when i  wrote "npm list" I have this
npm ERR! invalid: lodash@3.10.1 
npm ERR! invalid: ms@0.7.1 
npm ERR! invalid: request@2.60.0

I don't understand what happening because i never have this error..
What's going on..?

**Comment by linuxchip** [comment]
Can u send your package.json file ?

**Comment by ngassamcharles** [comment]
Yes!

  "dependencies": {
    "angular": "^1.5.5",
    "angular-bootstrap": "^0.12.2",
    "angular-cookies": "^1.5.2",
    "angular-jwt": "latest",
    "angular-mocks": "^1.5.2",
    "angular-resource": "^1.5.2",
    "angular-route": "^1.6.4",
    "angular-sanitize": "^1.5.2",
    "angular-ui-router": "^0.2.18",
    "angular-ui-select": "^0.12.100",
    "assetmanager": "latest",
    "async": "latest",
    "axios": "latest",
    "aws4": "latest",
    "aws-sdk": "latest",
    "aws-sign": "latest",
    "body-parser": "latest",
    "bootstrap": "latest",
    "bower": "latest",
    "compression": "latest",
    "connect-flash": "latest",
    "connect-modrewrite": "latest",
    "connect-multiparty": "latest",
    "consolidate": "latest",
    "cookie-parser": "latest",
    "elasticsearch": "^12.1.3",
    "errorhandler": "latest",
    "express": "latest",
    "express-validator": "latest",
    "file-loader": "latest",
    "forever": "latest",
    "gridfs-stream": "latest",
    "http-aws-es": "1.1.3",
    "jsondiffpatch": "latest",
    "jsonwebtoken": "latest",
    "kerberos": "latest",
    "languages" : "latest",
    "lodash": "latest",
    "meanio": "latest",
    "method-override": "latest",
    "mongoosastic": "4.3.0",
    "mongoose": "4.9.2",
    "morgan": "latest",
    "ms": "latest",
    "node-inspector": "latest",
    "node-geocoder": "latest",
    "nodemailer": "latest",
    "npm": "^2.1.0",
    "passport": "latest",
    "passport-facebook": "latest",
    "passport-github": "latest",
    "passport-google-oauth": "latest",
    "passport-linkedin": "latest",
    "passport-local": "latest",
    "passport-twitter": "latest",
    "pdfkit": "^0.7.2",
    "q": "latest",
    "request": "latest",
    "serve-favicon": "latest",
    "shelljs": "latest",
    "swagger-node-express": "latest",
    "swig": "latest",
    "view-helpers": "latest"
  },
  "devDependencies": {
    "lodash.isarraylike": "^4.2.0",
    "faker": "^4.1.0",
    "bl": "^1.2.1",
    "phantomjs": "^1.9.20",
    "istanbul": "^0.4.5",
    "swagger": "^0.7.5",
    "chai": "latest",
    "deasync": "latest",
    "del": "latest",
    "expect.js": "latest",
    "gulp": "latest",
    "gulp-coffee": "latest",
    "gulp-concat": "latest",
    "gulp-csslint": "latest",
    "gulp-cssmin": "latest",
    "gulp-jshint": "latest",
    "gulp-less": "latest",
    "gulp-livereload": "latest",
    "gulp-load-plugins": "latest",
    "gulp-mocha": "latest",
    "gulp-nodemon": "latest",
    "gulp-sass": "latest",
    "gulp-uglify": "latest",
    "gulp-util": "latest",
    "jasmine": "latest",
    "jasmine-reporters": "latest",
    "jquery": "latest",
    "jshint": "latest",
    "jshint-stylish": "latest",
    "karma": "latest",
    "karma-chrome-launcher": "latest",
    "karma-coffee-preprocessor": "latest",
    "karma-coverage": "latest",
    "karma-firefox-launcher": "latest",
    "karma-html2js-preprocessor": "latest",
    "karma-jasmine": "latest",
    "karma-junit-reporter": "latest",
    "karma-ng-html2js-preprocessor": "latest",
    "karma-phantomjs-launcher": "latest",
    "karma-phantomjs-shim": "latest",
    "karma-requirejs": "latest",
    "karma-script-launcher": "latest",
    "karma-webpack": "^1.7.0",
    "mocha": "latest",
    "monky": "latest",
    "phantomjs-prebuilt": "latest",
    "ping": "latest",
    "protractor": "latest",
    "require-dir": "latest",
    "requirejs": "latest",
    "run-sequence": "latest",
    "style-loader": "^0.13.1",
    "supertest": "latest",
    "through": "latest",
    "url-loader": "^0.5.7",
    "webpack": "^1.12.14",
    "webpack-dev-server": "^1.14.1",
    "yamljs": "^0.2.10"
  },
  "snyk": true
}

**Comment by strugee** [comment]
@ngassamcharles please use code formatting (see [Writing on GitHub](https://help.github.com/categories/writing-on-github/)) - it's a lot easier to read things like `package.json`s that way.

**Comment by ngassamcharles** [comment]
```
"dependencies": {
"angular": "^1.5.5",
"angular-bootstrap": "^0.12.2",
"angular-cookies": "^1.5.2",
"angular-jwt": "latest",
"angular-mocks": "^1.5.2",
"angular-resource": "^1.5.2",
"angular-route": "^1.6.4",
"angular-sanitize": "^1.5.2",
"angular-ui-router": "^0.2.18",
"angular-ui-select": "^0.12.100",
"assetmanager": "latest",
"async": "latest",
"axios": "latest",
"aws4": "latest",
"aws-sdk": "latest",
"aws-sign": "latest",
"body-parser": "latest",
"bootstrap": "latest",
"bower": "latest",
"compression": "latest",
"connect-flash": "latest",
"connect-modrewrite": "latest",
"connect-multiparty": "latest",
"consolidate": "latest",
"cookie-parser": "latest",
"elasticsearch": "^12.1.3",
"errorhandler": "latest",
"express": "latest",
"express-validator": "latest",
"file-loader": "latest",
"forever": "latest",
"gridfs-stream": "latest",
"http-aws-es": "1.1.3",
"jsondiffpatch": "latest",
"jsonwebtoken": "latest",
"kerberos": "latest",
"languages" : "latest",
"lodash": "latest",
"meanio": "latest",
"method-override": "latest",
"mongoosastic": "4.3.0",
"mongoose": "4.9.2",
"morgan": "latest",
"ms": "latest",
"node-inspector": "latest",
"node-geocoder": "latest",
"nodemailer": "latest",
"npm": "^2.1.0",
"passport": "latest",
"passport-facebook": "latest",
"passport-github": "latest",
"passport-google-oauth": "latest",
"passport-linkedin": "latest",
"passport-local": "latest",
"passport-twitter": "latest",
"pdfkit": "^0.7.2",
"q": "latest",
"request": "latest",
"serve-favicon": "latest",
"shelljs": "latest",
"swagger-node-express": "latest",
"swig": "latest",
"view-helpers": "latest"
},
"devDependencies": {
"lodash.isarraylike": "^4.2.0",
"faker": "^4.1.0",
"bl": "^1.2.1",
"phantomjs": "^1.9.20",
"istanbul": "^0.4.5",
"swagger": "^0.7.5",
"chai": "latest",
"deasync": "latest",
"del": "latest",
"expect.js": "latest",
"gulp": "latest",
"gulp-coffee": "latest",
"gulp-concat": "latest",
"gulp-csslint": "latest",
"gulp-cssmin": "latest",
"gulp-jshint": "latest",
"gulp-less": "latest",
"gulp-livereload": "latest",
"gulp-load-plugins": "latest",
"gulp-mocha": "latest",
"gulp-nodemon": "latest",
"gulp-sass": "latest",
"gulp-uglify": "latest",
"gulp-util": "latest",
"jasmine": "latest",
"jasmine-reporters": "latest",
"jquery": "latest",
"jshint": "latest",
"jshint-stylish": "latest",
"karma": "latest",
"karma-chrome-launcher": "latest",
"karma-coffee-preprocessor": "latest",
"karma-coverage": "latest",
"karma-firefox-launcher": "latest",
"karma-html2js-preprocessor": "latest",
"karma-jasmine": "latest",
"karma-junit-reporter": "latest",
"karma-ng-html2js-preprocessor": "latest",
"karma-phantomjs-launcher": "latest",
"karma-phantomjs-shim": "latest",
"karma-requirejs": "latest",
"karma-script-launcher": "latest",
"karma-webpack": "^1.7.0",
"mocha": "latest",
"monky": "latest",
"phantomjs-prebuilt": "latest",
"ping": "latest",
"protractor": "latest",
"require-dir": "latest",
"requirejs": "latest",
"run-sequence": "latest",
"style-loader": "^0.13.1",
"supertest": "latest",
"through": "latest",
"url-loader": "^0.5.7",
"webpack": "^1.12.14",
"webpack-dev-server": "^1.14.1",
"yamljs": "^0.2.10"
},
"snyk": true
}
```
