### ISSUE TITLE
Installing MavensMate-Atom Error

### ISSUE THREAD

**Issue by VictorArchela** [npm/npm#17925]
Hi guys, I've been getting this error when I try installing the extension. I'm using MacOs and have the mavensMate desktop app installed.

The command I used was `apm install MavensMate-Atom`

`npm WARN deprecated node-uuid@1.4.1: Use uuid module instead`
`npm ERR! git clone --template=/Users/varchela/.atom/.apm/_git-remotes/_templates --mirror https://github.com/Benvie/harmony-collections.git /Users/varchela/.atom/.apm/_git-remotes/git-https-github-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96-f622d8c9: Cloning into bare repository` `'/Users/varchela/.atom/.apm/_git-remotes/git-https-github-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96-f622d8c9'...`
`npm ERR! git clone --template=/Users/varchela/.atom/.apm/_git-remotes/_templates --mirror https://github.com/Benvie/harmony-collections.git /Users/varchela/.atom/.apm/_git-remotes/git-https-github-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96-f622d8c9: remote: Invalid username or password.`
`npm ERR! git clone --template=/Users/varchela/.atom/.apm/_git-remotes/_templates --mirror https://github.com/Benvie/harmony-collections.git /Users/varchela/.atom/.apm/_git-remotes/git-https-github-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96-f622d8c9: fatal: Authentication failed for 'https://github.com/Benvie/harmony-collections.git/'`
`npm ERR! Darwin 16.6.0`
`npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/varchela/.atom/.apm/.apmrc" "--userconfig" >"/Users/varchela/.atom/.apmrc" "install" >"/private/var/folders/6k/jgg258dd6s59hs_qss0_ym_mt_5xw8/T/d-117625-19402-1pxe2q1.opjhv9529/package.tgz" "--runtime=electron" "--target=1.3.15" "--arch=x64" "--global-style"`
`npm ERR! node v6.9.5`
`npm ERR! npm  v3.10.10`
`npm ERR! code 128`
`npm ERR! Command failed: git clone --template=/Users/varchela/.atom/.apm/_git-remotes/_templates --mirror https://github.com/Benvie/harmony-collections.git /Users/varchela/.atom/.apm/_git-remotes/git-https-github-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96-f622d8c9`
`npm ERR! Cloning into bare repository '/Users/varchela/.atom/.apm/_git-remotes/git-https-github-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96-f622d8c9'...`
`npm ERR! remote: Invalid username or password.`
`npm ERR! fatal: Authentication failed for 'https://github.com/Benvie/harmony-collections.git/'`
`npm ERR! `
`npm ERR! `
`npm ERR! If you need help, you may report this error at:`
`npm ERR!     <https://github.com/npm/npm/issues>`
`npm ERR! Please include the following file with any support request:`
`npm ERR!     /private/var/folders/6k/jgg258dd6s59hs_qss0_ym_mt_5xw8/T/apm-install-dir-117625-19402-1qmvu24.o3mamgf1or/npm-debug.log`

**Comment by strugee** [comment]
@VictorArchela please edit your issue to use code formatting, not a quote - it's much easier to read that way. You also need to actually provide the npm command that you used - we can't do a lot to help otherwise.

Offhand, this doesn't look like a problem with npm. https://github.com/Benvie/harmony-collections 404s for me when I visit it in a web browser, so either the repository doesn't exist or it's private. npm is telling you that at the bottom ("fatal: Authentication failed"). There isn't anything npm can do about this.

**Comment by kenany** [comment]
Yeah this doesn't look like an `npm` issue to me. Error is coming from `git`, and since that repo in question no longer exists there is nothing we can do here unfortunately.

**Comment by VictorArchela** [comment]
Hmm...

"npm ERR! If you need help, you may report this error at:
npm ERR! https://github.com/npm/npm/issues" this is why I posted it here... @KenanY 

The command I used was "apm install MavensMate-Atom" @strugee

**Comment by kenany** [comment]
@VictorArchela Yeah, those lines are at the end of all `npm` error logs, but all `npm` is doing here is letting you know that `git` returned an error code. It's fine that you opened the issue, but since we've determined that it isn't actually an `npm` issue, the issue was closed.

**Comment by Salesforce-Techie** [comment]
I am also facing same issue, What would be work around then?

Thanks,
Shri

**Comment by strugee** [comment]
@SFFreelancer there is no workaround per se. You have to figure out where the code is on your own; all npm can really do is let you know it couldn't find any code in the place it was given (which is what's happening here).

**Comment by steals** [comment]
@VictorArchela @SFFreelancer see https://github.com/joeferraro/MavensMate/issues/890 for resolution

**Comment by DeMiTeLi** [comment]
@steals thank you! I had the same issue and your tip to download package manually solved the the problem!
