### ISSUE TITLE
npm start but Failed to connect to server localhost

### ISSUE THREAD

**Issue by theashu123** [npm/npm#17939]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [
![npm-node2](https://user-images.githubusercontent.com/29142485/28617755-5be4fc34-721f-11e7-8c2a-7efa9bb333d4.JPG)
![npm-node3](https://user-images.githubusercontent.com/29142485/28617756-5bf3473a-721f-11e7-83fa-b87332eba021.JPG)

 ] Other (_see below for feature requests_):

#### What's going wrong?
Working fine in terminal but browser shows 
"503 Service Unavailable

Failed to connect to server localhost"
#### How can the CLI team reproduce the problem?
I am doing Angular tutorial "The Hero Editor"

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
This doesn't look like an issue with `npm` to me. Might wanna ask the `lite-server` developers instead.
