### ISSUE TITLE
[ ..............] - loadRequestedDeps: sill install loadAllDepsIntoIdealTree 

### ISSUE THREAD

**Issue by tifye** [npm/npm#17930]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?
Trying to install the Express module but it just stops loading after around 20%
[ |||..........] - loadRequestedDeps: sill install loadAllDepsIntoIdealTree 

### supporting information:

 - `npm -v` prints: 3.10.10
 - `node -v` prints: v6.11.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows 10

**Comment by kunaljain94** [comment]
any fix on this issue?

**Comment by kunaljain94** [comment]
ny fix on this
