### ISSUE TITLE
ionic start myApp1 blank---error

### ISSUE THREAD

**Issue by wuman12315** [npm/npm#17938]
[ERROR] An error occurred while running npm install (exit code 1):

        npm ERR! Windows_NT 6.1.7601
        npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program
        Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
        npm ERR! node v6.10.3
        npm ERR! npm  v3.10.10

        npm ERR! shasum check failed for
        C:\Users\baojun.wu\AppData\Local\Temp\npm-6796-691b6181\registry.npmjs.o
rg\rollup\-\rollup-0.42.0.tgz
        npm ERR! Expected: 56e791b3a2f3dd7190bbb80a375675f2fe0f9b23
        npm ERR! Actual:   a00eb6eacdaa394b44fc9235902323c986004114
        npm ERR! From:     https://registry.npmjs.org/rollup/-/rollup-0.42.0.tgz

        npm ERR!
        npm ERR! If you need help, you may report this error at:
        npm ERR!     <https://github.com/npm/npm/issues>

        npm ERR! Please include the following file with any support request:
        npm ERR!     D:\AppTest\myApp1\npm-debug.log

**Comment by kenany** [comment]
Does this also occur with newer versions of `npm`?

**Comment by kenany** [comment]
Closing as abandoned.
