### ISSUE TITLE
no update nom

### ISSUE THREAD

**Issue by rikardocorp** [npm/npm#17937]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'update' ]
2 info using npm@3.8.6
3 info using node@v5.5.0
4 verbose stack Error: Cannot find module 'realize-package-specifier'
4 verbose stack     at Function.Module._resolveFilename (module.js:339:15)
4 verbose stack     at Function.Module._load (module.js:290:25)
4 verbose stack     at Module.require (module.js:367:17)
4 verbose stack     at require (internal/module.js:16:19)
4 verbose stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/install/deps.js:12:31)
4 verbose stack     at Module._compile (module.js:413:34)
4 verbose stack     at Object.Module._extensions..js (module.js:422:10)
4 verbose stack     at Module.load (module.js:357:32)
4 verbose stack     at Function.Module._load (module.js:314:12)
4 verbose stack     at Module.require (module.js:367:17)
5 verbose cwd /Users/Rikardocorp/Documents/vue-project/motelcity
6 error Darwin 16.7.0
7 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "update"
8 error node v5.5.0
9 error npm  v3.8.6
10 error code MODULE_NOT_FOUND
11 error Cannot find module 'realize-package-specifier'
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]

**Comment by kenany** [comment]
Hmm, this might just be a broken `npm` install. Could you first try reinstalling `npm`?

**Comment by kenany** [comment]
Closing as abandoned.
