### ISSUE TITLE
Issue with downloading angular-cli library using npm install

### ISSUE THREAD

**Issue by richa2008** [npm/npm#17932]
Hi,

I am trying to install angular-cli library using npm install command. I downloaded node.js first and then ran npm install -g angular-cli in command prompt. But it is getting hanged at a point 
 **[    ..............] / loadRequestedDeps: sill install loadAllDepsIntoIdealTree** .
After this no progress is shown.
The version of my node.js is 6.11.1 and npm is 3.10.10.

Please help.

Thanks,
Swati

**Comment by linuxchip** [comment]
Are you using proxy ? If yes, did you configured properly ?

Can u post full log. Before that do below things

npm config set loglevel info

Run now and send your logs

**Comment by kenany** [comment]
Closing as abandoned.
