### ISSUE TITLE
localhost in package-lock

### ISSUE THREAD

**Issue by freakypie** [npm/npm#17944]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

npm is adding "localhost" server resolutions for packages.

I'm not using an alternate server. I do have linked packages, but would npm create an entry like this for a linked package?

```
    ...
    "amdefine": {
      "version": "http://localhost:4873/amdefine/-/amdefine-1.0.0.tgz",
      "integrity": "sha1-/RdHRwDLXMnCtwnwvp0jzjwZjDM="
    },
    ...
```

So on another computer it gets connection errors because there is no server listening on localhost

#### How can the CLI team reproduce the problem?

I'm not sure :(

### supporting information:

 - `npm -v` prints: 5.3.0
 - `node -v` prints: v8.1.4
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: linux
 - Network issues:
   - Geographic location where npm was run: USA
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by zkat** [comment]
@freakypie What does `npm config get registry` say?

**Comment by zkat** [comment]
Executed inside that project

**Comment by freakypie** [comment]
https://registry.npmjs.org/
