### ISSUE TITLE
npm ERR! network request to https://registry.npmjs.org/@angular%2fcommon failed, reason: connect ETIMEDOUT 151.101.208.162:443

### ISSUE THREAD

**Issue by SGeorge007** [npm/npm#17947]
Hi,

I am getting below error when i am trying to restore my package.json in Visual Studio 2015.
```
====Executing command 'npm install'====
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! network request to https://registry.npmjs.org/@angular%2fcommon failed, reason: connect ETIMEDOUT 151.101.208.162:443
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\DHJ9SYG\AppData\Roaming\npm-cache\_logs\2017-07-26T20_22_41_471Z-debug.log
====npm command completed with exit code 1====
```
Node.js and npm is installed in my machine. 
I verified their version by-
```
node -v
v8.1.4

npm -v
5.0.3
```
My ping  to151.101.208.162:443 results in error:
`"Ping request could not find host 151.101.208.162:443. Please check the name and try again."`
Please let me know if anyone has faced this issue Or have any idea.
Thanks in advance!!

**Comment by farazanees** [comment]
You should run this command "npm cache verify". It will resolve your issue

**Comment by SGeorge007** [comment]
I ran the above command:. Below is the result:
Cache verified and compressed (~\AppData\Roaming\npm-cache\_cacache):
Content verified: 0 (0 bytes)
Index entries: 0
Finished in 0.029s

The problem here is my system is not able to reach 151.101.20.162:443.
When i am trying to ping 151.101.20.162:443 i am getting below error:
`Ping request could not find host 151.101.20.162:443. Please check the name and try again.`
I am really out of ideas here.

**Comment by evgeniyannenkov** [comment]
Hm, looks like you have some problems with your global proxy settings.
I resolved this problem the next way:
Check your config settings: `npm config list`
Then you could add or change your proxy settings:
```
npm config set http-proxy http://your_proxy_ip:port
npm config set https-proxy http://your_proxy_ip:port
```
It works for me.

**Comment by SGeorge007** [comment]
@evgeniyannenkov is right, setting the proxy resolved the issue.
My bad, i should have closed this issue.
We just need to make sure to not put password under quotes. system will accept '@' symbol too.
