### ISSUE TITLE
npm can't install while used in a vlan

### ISSUE THREAD

**Issue by offlineError** [npm/npm#17956]
#### I'm opening this issue because:

  - [ ] **npm is crashing**.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I got an offline vlan (meaning not connected to the internet) with a local registry server.
the registry does have the packages I want.
When I try to install with the newest npm versions, I get Eintegrity errors
#### How can the CLI team reproduce the problem?
make a local registry.
try to install an existing package.

### supporting information:

 - `npm -v` prints: 5.3.0
 - `node -v` prints: 8.2.1
 - `npm config get registry` prints: my registry server
 - Windows, OS X/macOS, or Linux?: windows
 - Network issues:
   - Geographic location where npm was run:

   - **[ ] I don't use a proxy, but have limited or unreliable internet access.**
I use a private registry

**Comment by linuxchip** [comment]
That may be issue with VLAN, not npm

Just check whether your internet connectivity is good from that VLAN and then if you are behind proxy define those properly

**Comment by offlineError** [comment]
I don't have access to the internet, and I won't have.
This issue is also relevant for air gaped networks, such as Facebook's dev network.
I have the packages, and a registry server.

**Comment by linuxchip** [comment]
OK, got it.

Try once below things

npm cache verify

After this, try install once

If this not worked, try below things

Delete package-lock.json, delete node_modules folder and then run npm instal

**Comment by offlineError** [comment]
worked

**Comment by offlineError** [comment]
thanks
