### ISSUE TITLE
Npm crashes on backslash

### ISSUE THREAD

**Issue by NikxDa** [npm/npm#17959]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

When installing "@types\socket.io-client" via `npm install --save @types\socket.io-client`, npm crashes because of the invalid backslash (that should actually be a forward slash). Even if this is an error the user produced, npm should be able to handle it.

This is the error log:

> Unhandled rejection Error: Invalid tag name "@typessocket.io-client": Tags may not have any characters that encodeURIComponent encodes.
>     at invalidTagName (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:76:15)
>     at fromRegistry (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:265:13)
>     at resolve (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:66:12)
>     at npa (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:39:10)
>     at /usr/local/lib/node_modules/npm/lib/install/deps.js:200:16
>     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
>     at Array.forEach (native)
>     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
>     at Array.forEach (native)
>     at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
>     at exports.getAllMetadata (/usr/local/lib/node_modules/npm/lib/install/deps.js:199:3)
>     at Installer.loadArgMetadata (/usr/local/lib/node_modules/npm/lib/install.js:325:3)
>     at /usr/local/lib/node_modules/npm/lib/install.js:656:16
>     at BB.join.then (/usr/local/lib/node_modules/npm/lib/install/read-shrinkwrap.js:41:16)
>     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
>     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)

#### How can the CLI team reproduce the problem?

See above. 
https://gist.github.com/NikxDa/6ecbcb0c741da1eb0f8f38e3525e95a3

### supporting information:

 - `npm -v` prints: 5.3.0
 - `node -v` prints: v7.10.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS
 - Network issues:
   - Geographic location where npm was run: Germany

**Comment by zkat** [comment]
We are unable to do anything about this for you: backslashes are interpreted by your shell, and npm has no information whatsoever about how these escapes were interpreted.

You can try it out yourself like so:

`example.js`
```
#!/usr/bin/env node
console.log(process.argv)
```

Then...

```
➜ node example.js foo\bar
[ '/usr/local/bin/node',
  '/path/to/example.js',
  'foobar' ]
```

**Comment by NikxDa** [comment]
Sure, but I think this is only more or less about the backslash. Upon further inspection, the @ seems to be the actual problem. Running "npm install @typessocket.io-client" will result in the same error, and the error message makes sense, although it should handle the error internally and then print the message.

**Edit: This issue has been resolved in a later version.  It now prints:**
`npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "@typescript-client": Tags may not have any characters that encodeURIComponent encodes.`
