### ISSUE TITLE
npm ERR! missing script: start - what do i put in the path.json file? 

### ISSUE THREAD

**Issue by AGrant24** [npm/npm#17950]
#### I'm opening this issue because:

npm is saying the following;

C:\Users\Alex>npm start
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10

npm ERR! missing script: start
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Alex\npm-debug.log

C:\Users\Alex>

I have deleted the entire node.js file and then clicked to repair from the node installer.

I am trying to follow a tutorial but this keeps giving me this error. Apologies if this is incorrect as This is a little bit more advanced than I'm used to and the tutorial is written assuming a lot of knowledge to be known.

**Comment by justinzyh** [comment]
I meet this problem,too.How do you solve it ?

**Comment by linuxchip** [comment]
You could either change the name of your application script to server.js or add the following to your package.json

"scripts": {
    "start": "node your-start-script.js"
}

**Comment by AGrant24** [comment]
Thanks for your reply

I located the package.json, opened and put that code in the scripts bit but it will only let me save it as a .txt file , im doing it in notepad, should i do it in Atom? 
also I cant find the application script and the start script i found is located in programfiles\nodejs\node_modules\npm\lib

Its a javascript file called 'start'

I apologize if this is really basic I have missed something and this is all very trial and error for me at this stage

**Comment by AGrant24** [comment]
~I added the script to the package.json and it didn't work, Is there anything i can do that will fix this like a complete reinstall?

**Comment by ndiyansah** [comment]
dude r u solving this problem? i have same issue like you
