### ISSUE TITLE
### im creating this issue because my ng command for creating new angular project in npm is returning an error my 

### ISSUE THREAD

**Issue by i-m-Shahbaj** [npm/npm#17954]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints: 3.10.10
 - `node -v` prints: v6.11.0
 - `npm config get registry` prints: https://registry.npm.js.org/
 - Windows, OS X/macOS, or Linux?: windows
 - Network issues:
   - Geographic location where npm was run: nodejs command prompt
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

[npm-debug.zip](https://github.com/npm/npm/files/1178917/npm-debug.zip)

**Comment by kenany** [comment]
@shahbajkhan123 Could you upload the debug log as plaintext to <https://gist.github.com/> instead of zipping it up? Thanks!

**Comment by kenany** [comment]
Closing as abandoned.
