### ISSUE TITLE
Node.js version v6.10.3 is not supported. Agent disabled.

### ISSUE THREAD

**Issue by plentz** [npm/npm#17953]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
`npm -v` is printing `Node.js version v6.10.3 is not supported. Agent disabled. 3.10.10` instead of just it's version

#### How can the CLI team reproduce the problem?

clean install on centos do the job (attached example)

```
$ sudo yum -y install nodejs
$ node -v
$ npm -v
```

### supporting information:

 - `npm -v` prints: `Node.js version v6.10.3 is not supported. Agent disabled.
3.10.10`
 - `node -v` prints: `v6.10.3`
 - `npm config get registry` prints: ` npm config get registry
Node.js version v6.10.3 is not supported. Agent disabled.
https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?: Linux (CentOS)

[installlog.txt](https://github.com/npm/npm/files/1178571/installlog.txt)

**Comment by golubitsky** [comment]
I was getting the message after upgrading to v8.2.1
```
Node.js version v8.2.1 is not supported. Agent disabled.
```
I then uninstalled Node v8.2.1 and installed Node v7.7.4. 
I am receiving the same message:
```
Node.js version v7.7.4 is not supported. Agent disabled.
```

**Comment by golubitsky** [comment]
After bumping into this [SO](https://stackoverflow.com/a/45348862/3833166), being that I am working in Windows 8.1, I 
1. uninstalled Node 
2. went to my `%APPDATA%/Roaming` folder and removed both `npm` and `npm-cache` folders. 
3. reinstalled Node v7.7.4

After the above, I _am_ able to run npm commands, but I get the warning printed out twice, for example:
```
$ npm -v
Node.js version v7.7.4 is not supported. Agent disabled.
Node.js version v7.7.4 is not supported. Agent disabled.
4.1.2
```

This workaround (uninstall, wipe npm modules, reinstall) made the error (which I understand is unrelated to the warning message) go away-- but the warning that the agent is disabled (which seems to have no discernible effect) persists.
