### ISSUE TITLE
Typo in package-locks docs

### ISSUE THREAD

**Issue by davidgilbertson** [npm/npm#17967]
I can't find the markdown for https://docs.npmjs.com/files/package-locks in either https://github.com/npm/npm or https://github.com/npm/docs so I'll just leave this as an issue...

This: "Once it's present, and future installation will base its work off this file"
Should be: "Once it's present, **any** future installation will base its work off this file"

**Comment by kenany** [comment]
Here's the file in question, if you wanna open a PR :) <https://github.com/npm/npm/blob/75b462c19ea16ef0d7f943f94ff4d255695a5c0d/doc/files/npm-package-locks.md>

**Comment by vikramnr** [comment]
@KenanY Can I raise a PR for this?

**Comment by kenany** [comment]
@vikramnr Go for it!
