### ISSUE TITLE
npm@5 creates broken install from shrinkwrap

### ISSUE THREAD

**Issue by kanongil** [npm/npm#17960]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

My `npm install` does not respect the local shrinkwrap file. The actual install can differ significantly.

#### How can the CLI team reproduce the problem?

```sh
> git clone https://github.com/kanongil/shrinkwrap-fail.git
> cd shrinkwrap-fail
> npm install
```

To verify that is incorrect, you can check eg. the top-level `yargs` dependency:

```sh
> cat node_modules/yargs/package.json | grep version
  "version": "3.27.0"
```

This doesn't match the top-level version specified in the shrinkwrap file, which is [3.10.0](https://github.com/kanongil/shrinkwrap-fail/blob/af355413c0cba64b5d0c7dc39347fc1f4e67b2df/npm-shrinkwrap.json#L14447).

Additional incorrect versions can be found running the installed dependency validator:

`npx ember` – [output](https://gist.github.com/kanongil/991e2840d182795e9b2b4b9ecc4f46f5)

### supporting information:

 - `npm -v` prints: **5.3.0**
 - `node -v` prints: **v8.2.1**
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: **macOS**

Note that this is a regression, and the same shrinkwrap file install correctly using npm@4.

**Comment by zkat** [comment]
```
➜ <node_modules/yargs/package.json| grep version
    "type": "version",
  "version": "3.10.0"
```

I'm unable to reproduce this :(

**Comment by kanongil** [comment]
@zkat That is actually good news. I managed to get a correct install as well by clearing my `~/.npmrc` file.

Which means that the issue is caused by one of these settings:

```
progress=true
package-lock=false
save=false
```

With a bit of more testing, it seems to be the `package-lock=false` setting that is causing the issue.

**Comment by kanongil** [comment]
I have updated the repo with the setting so that it should fail, regardless of your local setting.

**Comment by kanongil** [comment]
Reading https://docs.npmjs.com/misc/config#package-lock, it seems that this behaviour is intentional, which I find troubling.

Is there really no way to disable writing `package-lock.json`, without breaking shrinkwrap support?

**Comment by zkat** [comment]
@kanongil The files are one and the same right now, yes.

But like, if you have an `npm-shrinkwrap.json`, you don't need this. npm won't write a package-lock if you already have a shrinkwrap, or vice-versa.

**Comment by kanongil** [comment]
Yes, I don't need it when I use a shrinkwrap file.

However, I would like to avoid the package-lock file when I work with other repositories that does not use either.

Of more concern, is how this option has inadvertently caused me to install non-approved Hapi releases (see https://github.com/hapijs/hapi/issues/3556). I would actually classify this as a security issue, as the Hapi release model requires shrink-wrapped installs.

**Comment by kanongil** [comment]
FYI, I don't consider this resolved. See https://github.com/npm/npm/issues/18174 for followup.

**Comment by kanongil** [comment]
Still not resolved.
