### ISSUE TITLE
npm start not working

### ISSUE THREAD

**Issue by ekabugo0125** [npm/npm#17978]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
npm ERR! path 
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by linuxchip** [comment]
Do you have start entry in package.json ?

**Comment by ekabugo0125** [comment]
"start": "npm-run-all --parallel security-check open:src",
    "open:src":"node buildSCript/srcServer.JS",
    "security-check":"nsp check",
    "localtunnel":"lt --port 3000",
    "share": "npm-run-all --parallel open:src localtunnel

that is my start entry

**Comment by linuxchip** [comment]
Is security-check is your run script ?

what is open:src ?

AFAIK, after npm-run-all --parallel, run scripts has to be given right
