### ISSUE TITLE
Not able to install AutoRest.

### ISSUE THREAD

**Issue by antomartinp** [npm/npm#17974]
#### I'm opening this issue because:

  - [ ] npm is not able to install AutoRest.

#### What's going wrong?
https://registry.npmjs.org/AutoRest is responding with 404.
The above link is returning empty Json.

#### How can the CLI team reproduce the problem?

Installation steps of AutoRest reproduces the problem.
npm install -g AutoRest

Below is the log file:
https://gist.github.com/antomartinp/1de8c14fbe355e41146693a5681d95b5#file-2017-07-28t03_53_47_648z-debug

**Comment by kenany** [comment]
Seems like the package simply does not exist. The error message isn't really clear on that but still, this sort of failure is expected when trying to install something which does not exist in the registry.
