### ISSUE TITLE
npm install bourbon fails with a ton of undefined

### ISSUE THREAD

**Issue by linkmauve** [npm/npm#17987]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
```bash
% npm install bourbon
npm ERR! Cannot read property '0' of undefined                                 

npm ERR! A complete log of this run can be found in:                           
npm ERR!     /home/linkmauve/.npm/_logs/2017-07-28T18_57_51_026Z-debug.log
```

#### How can the CLI team reproduce the problem?

* Clone [conferse.js](https://github.com/jcbrand/converse.js), by running `git clone https://github.com/jcbrand/converse.js`.
* Run `make build` inside.
* See it fail asking for bourbon.
* Run `npm install bourbon`
* See npm fail with this log: [2017-07-28T18_57_51_026Z-debug.log](https://github.com/npm/npm/files/1184039/2017-07-28T18_57_51_026Z-debug.log.txt)

### supporting information:

 - `npm -v` prints: 5.3.0
 - `node -v` prints: v8.2.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: ArchLinux up to date as of July 28th.
 - Network issues:
   - Geographic location where npm was run: on an OVH server, somewhere in France
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container: None
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by Hyperion** [comment]
#https://github.com/npm/npm/issues/17858

**Comment by Hyperion** [comment]
#17858

**Comment by robinhouston** [comment]
This looks like #17858. Deleting package-lock.json (and node_modules) and regenerating it will probably fix the problem. It looks as though NPM 5.3.0 isn’t compatible with the package-lock.json files produced by earlier versions of npm.
