### ISSUE TITLE
95% emittingError: EIO: i/o error, close at Error (native)

### ISSUE THREAD

**Issue by kyrrr** [npm/npm#17981]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I am trying to follow the instructions given on [the Laravel 5.4 Mix instructions page](https://laravel.com/docs/5.4/mix). I am using the Homestead Vagrant box, through VirtualBox. 
The issue appears when ["running mix"](https://laravel.com/docs/5.4/mix#running-mix).

Apologies for any formatting issues or breaks with convention, this is my first reported issue.

#### How can the CLI team reproduce the problem?
- Homestead box on Windows (10) host
- run commands
    `npm install --no-bin-links`
    `npm run dev`

Gist of command output and error log [here](https://gist.github.com/kyrrr/0d278dbe11d8f825168772eb1b91e8ab)
and pasted here for easier googling in the future.
======= npm run dev =======

@ dev /home/vagrant/Code/Laravel
node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
95% emittingError: EIO: i/o error, close at Error (native)

npm ERR! code ELIFECYCLE

npm ERR! errno 1

npm ERR! @ dev: node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

npm ERR! Exit status 1

npm ERR!

npm ERR! Failed at the @ dev script.

npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

npm ERR! /home/vagrant/.npm/_logs/2017-07-28T10_23_59_096Z-debug.log

======= cat /home/vagrant/.npm/_logs/2017-07-28T10_23_59_096Z-debug.log =====

0 info it worked if it ends with ok

1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'dev' ]

2 info using npm@5.3.0

3 info using node@v6.10.3

4 verbose run-script [ 'predev', 'dev', 'postdev' ]

5 info lifecycle @~predev: @

6 info lifecycle @~dev: @

7 verbose lifecycle @~dev: unsafe-perm in lifecycle true

8 verbose lifecycle @~dev: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/vagrant/Code/Laravel/node_modules/.bin:/home/vagrant/.composer/vendor/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

9 verbose lifecycle @~dev: CWD: /home/vagrant/Code/Laravel

10 silly lifecycle @~dev: Args: [ '-c',

10 silly lifecycle 'node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js' ]

11 silly lifecycle @~dev: Returned: code: 1 signal: null

12 info lifecycle @~dev: Failed to exec dev script

13 verbose stack Error: @ dev: node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

13 verbose stack Exit status 1

13 verbose stack at EventEmitter. (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)

13 verbose stack at emitTwo (events.js:106:13)

13 verbose stack at EventEmitter.emit (events.js:191:7)

13 verbose stack at ChildProcess. (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)

13 verbose stack at emitTwo (events.js:106:13)

13 verbose stack at ChildProcess.emit (events.js:191:7)

13 verbose stack at maybeClose (internal/child_process.js:886:16)

13 verbose stack at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

14 verbose pkgid @

15 verbose cwd /home/vagrant/Code/Laravel

16 verbose Linux 4.4.0-66-generic

17 verbose argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "dev"

18 verbose node v6.10.3

19 verbose npm v5.3.0

20 error code ELIFECYCLE

21 error errno 1

22 error @ dev: node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

22 error Exit status 1

23 error Failed at the @ dev script.

23 error This is probably not a problem with npm. There is likely additional logging output above.

24 verbose exit [ 1, true ]

### supporting information:

 - `npm -v` prints: 5.3.0
 - `node -v` prints: 6.10.3
 - `npm config get registry` prints :https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux/Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-66-generic x86_64) on Windows 10 host, using VirtualBox

**Comment by Othella** [comment]
@kyrrr How did you solved this? I'm stucked on a similar issue. Thanks!

**Comment by kyrrr** [comment]
I simply gave up - the easiest solution. The relevant project has also been moved to another framework, so NPM and Laravel Mix are no longer in the mix. Sorry!

**Comment by Othella** [comment]
Thank you for your response, I finally managed to solve this: it was NFS option enabled in my vagrant homestead environment!

**Comment by kyrrr** [comment]
Good to know. I'll keep that in mind on my next trip down the NPM hole
