### ISSUE TITLE
Failed to resolve directive: mask-decimal

### ISSUE THREAD

**Issue by FernandoF001E** [npm/npm#17984]
I am using the di-vue-mask however in the browser it returns the following error:

**[Vue warn]: Failed to resolve directive: mask-decimal**

How to solve this?

**Comment by kenany** [comment]
Hi! This issue tracker is for bugs and issues found in the `npm` CLI, not for support with packages like Vue. Perhaps a place like StackOverflow or a forum for other Vue users would be more appropriate for your question. Good luck!
