### ISSUE TITLE
npm error in linux

### ISSUE THREAD

**Issue by mostafa5aled** [npm/npm#17998]
when i write npm start command in global terminal i found this issues 

npm ERR! Linux 4.10.0-27-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! path /home/moustafa/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/home/moustafa/package.json'
npm ERR! enoent ENOENT: no such file or directory, open '/home/moustafa/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/moustafa/npm-debug.log

I'm trying to use TypeScript for Angular

**Comment by hugmanrique** [comment]
You're probably not in your project's directory or you need to create a package.json file. This isn't a bug.
