### ISSUE TITLE
fast need

### ISSUE THREAD

**Issue by Lin-yuzhao** [npm/npm#17993]
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "D:\\前端编辑器\\node.exe" "D:\\前端编辑器\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10

npm ERR! missing script: start
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\lenovo\Desktop\02： vue.js高仿饿了么（1-13章全）\b0ifnz\npm-debug.log

**Comment by kenany** [comment]
Hello! So, the way `npm start` works is that it looks in your current `package.json` for a defined `"start"` [script](https://docs.npmjs.com/misc/scripts), and then runs that. The error message you're seeing is trying to tell you that you have not defined a `"start"` script in your `package.json`, hence `npm start` has no idea what you want it to do.

To solve this issue, all you have to do is add a new script to your `package.json`. It might look something like this, for example:

``` json
{
  "name": "package-name",
  "version": "1.0.0",
  "description": "package description",
  "scripts": {
    "start": "node --version",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {},
  "devDependencies": {}
}
```

Note how this `package.json` has a `"start"` script that runs `node --version`. You'll definitely want to change the command to whatever is most appropriate for your project.

Let me know if you run into any further `npm` issues :)

**Comment by Lin-yuzhao** [comment]
Thanks,so,if I don't change it,and I enter "npm run dev",it also can't run,the result is like the image.
![image](https://user-images.githubusercontent.com/26651907/28746076-dab2699e-74b7-11e7-99c2-8f4baa439495.png)

**Comment by kenany** [comment]
@Lin-yuzhao That's coming from `webpack`, not `npm`.

**Comment by Lin-yuzhao** [comment]
@KenanY  Thanks for your answer.
