### ISSUE TITLE
cb() never called!

### ISSUE THREAD

**Issue by DI3HARD139** [npm/npm#17994]
Errors out after attempting "sudo npm update"

/var/www/rocketchat/programs/server$ sudo npm update
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

[2017-07-29T14_35_05_781Z-debug.txt](https://github.com/npm/npm/files/1185020/2017-07-29T14_35_05_781Z-debug.txt)

**Comment by jumo-sballing** [comment]
same here with
```
npm -g outdated
```
node v8.2.1
npm v5.3.0
