### ISSUE TITLE
npm start 打开一个项目是报的错，该怎样解决？

### ISSUE THREAD

**Issue by lizhenningbb** [npm/npm#18000]
> react-scripts start

'react-scripts' ▒▒▒▒▒ڲ▒▒▒▒ⲿ▒▒▒Ҳ▒▒▒ǿ▒▒▒▒еĳ▒▒▒
▒▒▒▒▒▒▒▒▒ļ▒▒▒
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the test@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Pao\AppData\Roaming\npm-cache\_logs\2017-07-30T09_11_54_481Z-debug.log

**Comment by kenany** [comment]
@lizhenningbb Have you tried running `npm install --save-dev react-scripts`?

**Comment by kenany** [comment]
Closing as abandoned.

**Comment by kaoshen** [comment]
@lizhenningbb   Have you solve it?
