### ISSUE TITLE
Error for start project

### ISSUE THREAD

**Issue by Odin04ka** [npm/npm#18006]
$ yarn dev
yarn dev v0.27.5
$ backpack dev
(node:8400) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
 DONE  Compiled successfully in 1161ms20:19:03

(node:9028) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: __WEBPACK_IMPORTED_MODULE_1_nuxt___default.a is not a constructor

**Comment by kenany** [comment]
This error does not appear to be coming from `npm`.
