### ISSUE TITLE
Unable to install on W10 64-bit

### ISSUE THREAD

**Issue by TurtleBeach** [npm/npm#18004]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Install fails - complains about something called rimraf
#### How can the CLI team reproduce the problem?
Presumably just try to use the MSI installer on Windows 10. I submitted the log file at Gist

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
@TurtleBeach Could you post the link to the gist? Thanks!

**Comment by TurtleBeach** [comment]
[https://gist.github.com/TurtleBeach/5daf81a7d28c5c3115f0af7705a845ad.js](url)

**Comment by TurtleBeach** [comment]
There is a major discrepancy between information about Windows installations says, and what I see on my computer. Specifically, the User...\Roaming\npm folder is empty (it has folder etc, but that too is empty). The User...\Roaming\npm-cache folder is populated. And of course, everything is in Program Files - not Program Files (x86) - for 64-bit install.
