### ISSUE TITLE
Error in npm while installing express

### ISSUE THREAD

**Issue by AbhishekBhattacharya** [npm/npm#18001]
#### I'm opening this issue because:
  - [x] npm is producing an error while installation.
  
#### What's going wrong?
![image](https://user-images.githubusercontent.com/25662334/28753028-7446f5ec-754a-11e7-8100-40b1326c2eeb.png)
Error in npm, while installing express, ```sudo npm install express --save```  is also showing the same error.
- OS: Linux(Ubuntu)

**Comment by kenany** [comment]
@AbhishekBhattacharya Could you first try changing the `"name"` field in your `package.json` from `"express"` to something more unique?

**Comment by AbhishekBhattacharya** [comment]
@KenanY  I tried it , but same error :(

**Comment by kenany** [comment]
@AbhishekBhattacharya Okay, could you also try changing your directory name to the same unique name?

**Comment by AbhishekBhattacharya** [comment]
done? what next @KenanY

**Comment by kenany** [comment]
@AbhishekBhattacharya Can I see what error you are getting now, along with the contents of your `package.json`?

**Comment by AbhishekBhattacharya** [comment]
@KenanY 
![image](https://user-images.githubusercontent.com/25662334/28762855-59d522be-75d7-11e7-9dff-6dd2abbc3216.png)

```
{
  "name": "express",
  "version": "1.0.0",
  "description": "",
  "main": "app.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "express": "^4.15.3"
  }
}
``` 
Shows invalid

**Comment by kenany** [comment]
It looks like you did not follow my above suggestions. Could you try changing this line in your `package.json`:

```
  "name": "express",
```

to:

```
  "name": "my-express-project",
```

**Comment by AbhishekBhattacharya** [comment]
@KenanY  I renamed it as you told ago. But I tried changing the name, It didn't remove the error

**Comment by AbhishekBhattacharya** [comment]
I resolved it! Made a new directory with a fresh ```package.json``` and reran ```npm install```
```
{
  "name": "imad-2016-base",
  "version": "0.1.0",
  "description": "app",
  "main": "server.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "ajax-request": "^1.2.3",
    "body-parser": "^1.17.2",
    "express": "^4.14.0",
    "express-package-json": "^1.0.2",
    "express-session": "^1.15.4",
    "morgan": "^1.7.0"
  }
}
```
