### ISSUE TITLE
No compatible version found: rebase@2.1.0

### ISSUE THREAD

**Issue by Al-21** [npm/npm#18015]
npm ERR! Linux 4.8.0-53-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2

npm ERR! No compatible version found: rebase@2.1.0
npm ERR! Valid install targets:
npm ERR! 0.3.0
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/html/reactor/npm-debug.log

[reactor.zip](https://github.com/npm/npm/files/1188665/reactor.zip)

**Comment by leggsimon** [comment]
According to https://www.npmjs.com/package/rebase there appears to only be a `v0.3.0` of `rebase`

Are you requiring this module directly in your `package.json` or if not do you know what dependency appears to be requiring it?

**Comment by Al-21** [comment]
Hi Simon,

It's good to hear from you.  Yes as u can see in package.json ,it require
module directly while executing npm install inside directory.

I tried to update npm with latest version but didn't work

On Aug 1, 2017 05:31, "Simon Legg" <notifications@github.com> wrote:

According to https://www.npmjs.com/package/rebase there appears to only be
a v0.3.0 of rebase

Are you requiring this module directly in your package.json or if not do
you know what dependency appears to be requiring it?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/npm/npm/issues/18015#issuecomment-319229732>, or mute
the thread

**Comment by leggsimon** [comment]
Oh sorry I didn't see the debug log, so this part of the `package.json` is requiring the `2.1.0` version which obviously doesn't exist.

```json
"rebase":"2.1.0"
```
If this is your `package.json` you will need to update the version you are requiring to something like 
```json
"rebase":"^0.3.0"
```
If this is not your `package.json` it may be worth submitting a PR to update their dependency list.
