### ISSUE TITLE
issue when install -g @angular/cli

### ISSUE THREAD

**Issue by asaintjean** [npm/npm#18019]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
npm ERR! Windows_NT 6.1.7601
npm ERR! "C...nodejs\\node.exe" "...npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli"
npm ERR! node v6.11.1
npm ERR! npm v3.10.10
npm ERR! Invalid protocol: null

#### How can the CLI team reproduce the problem?

Please tell me a solution to install angular cli in my windows 7 32 bit

Thks

**Comment by leonadler** [comment]
The second line in your error log implies you are running `npm install -g`,
not `npm install -g @angular/cli`. Can you verify?

**Comment by asaintjean** [comment]
Hello, 

 

Yes I ran              npm install –g @angular/cli, 

I have made some changement after that I had              npm err invalid protocol: null,

and now I in front of      Error: connect ECONREFUSED 127.0.0.1:8888

 

Thank you for your prompt answer.

 

ASJ

 

De : Leon Adler [mailto:notifications@github.com] 
Envoyé : mardi 1 août 2017 13:41
À : npm/npm <npm@noreply.github.com>
Cc : asaintjean <a.saintjean@viatelease.fr>; Author <author@noreply.github.com>
Objet : Re: [npm/npm] issue when install -g @angular/cli (#18019)

 

The second line in your error log implies you are running npm install -g, not npm install -g @angular/cli. Can you verify?
