### ISSUE TITLE
npm install livecam error

### ISSUE THREAD

**Issue by 2216ChoiwooYoung** [npm/npm#18018]
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "livecam"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ENOSELF

npm ERR! Refusing to install livecam as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\wychoi\Downloads\livecam-master\npm-debug.log

**Comment by kenany** [comment]
@2216ChoiwooYoung Ensure that the `"name"` property in your `package.json` is not set to `"livecam"`. It must be set to something which does not share a name with any of your dependencies.

**Comment by kenany** [comment]
Closing as abandoned.
