### ISSUE TITLE
npm issue

### ISSUE THREAD

**Issue by Pratap-chauhan** [npm/npm#18010]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?
npm ERR! Linux 4.4.0-21-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2

npm ERR! missing script: start
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/lib/node_modules/@angular/cli/node_modules/node-sass/vendor/linux-x64-46/npm-debug.log
     

i do not understand .. what is this issue and how can i resolve this
### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by leggsimon** [comment]
I don't know what command you're running to get this but it from this `npm ERR! missing script: start` it looks like you need to add a `start` script. An example of this might be
```json
{
	...
	"scripts": {
		"start": "node app.js"
	},
	...
}
```

**Comment by Pratap-chauhan** [comment]
i used .. npm start   command

**Comment by leggsimon** [comment]
So, do you have a start script in your package.json already?

**Comment by 1131333069** [comment]
![image](https://user-images.githubusercontent.com/26244078/29021861-8a9a0d2a-7b99-11e7-8cfc-a5946be21136.png)
