### ISSUE TITLE
Refusing to install express as a dependency of itself

### ISSUE THREAD

**Issue by sowmya-512** [npm/npm#18029]
![issue1](https://user-images.githubusercontent.com/29512382/28837732-7c68bf98-76b3-11e7-8731-d6ccbc2ed605.JPG)
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by Schumi81** [comment]
I have exactly the same problem! :(

**Comment by kenany** [comment]
Can you first ensure that the `"name"` property in your `package.json` is not set to `"express"`?
