### ISSUE TITLE
npm install -g generator-meanjs@0.1.12

### ISSUE THREAD

**Issue by sravanth-space** [npm/npm#18021]
npm install -g generator-meanjs@0.1.12 
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by kenany** [comment]
@sravanthbaratam Could you upload the _full_ debug log to <https://gist.github.com/> and link it here? Thanks!

**Comment by kenany** [comment]
Closing as abandoned.
