### ISSUE TITLE
when run npm install, the error: Unexpected end of input at 1:14938

### ISSUE THREAD

**Issue by 17biubiu** [npm/npm#18036]
#### I'm opening this issue because:
  - [ ] npm is producing an incorrect install.

#### What's going wrong?

when run npm install.
npm ERR! Unexpected end of input at 1:14938
npm ERR! dependencies":{"babel-runtime":"^6.0.0"},"devDependencies":{"ava":"^0
npm ERR!                                                                      ^

#### How can the CLI team reproduce the problem?

3072 http fetch GET 200 https://registry.npmjs.org/babylon 23ms (from cache)
3073 silly fetchPackageMetaData error for babylon@^6.17.2 Unexpected end of input at 1:14938
3073 silly fetchPackageMetaData dependencies":{"babel-runtime":"^6.0.0"},"devDependencies":{"ava":"^0
3073 silly fetchPackageMetaData                                                                      ^
3074 silly pacote range manifest for private@^0.1.6 fetched in 28ms
3075 silly resolveWithNewModule private@0.1.7 checking installable status
3076 silly pacote range manifest for source-map@^0.5.0 fetched in 24ms
3077 silly resolveWithNewModule source-map@0.5.6 checking installable status
3078 silly pacote range manifest for slash@^1.0.0 fetched in 24ms
3079 silly resolveWithNewModule slash@1.0.0 checking installable status
3080 verbose stack SyntaxError: Unexpected end of input at 1:14938
3080 verbose stack dependencies":{"babel-runtime":"^6.0.0"},"devDependencies":{"ava":"^0
3080 verbose stack                                                                      ^
3080 verbose stack     at Object.parseJSON (/Users/lk/.nvm/versions/node/v8.2.1/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/node_modules/json-parse-helpfulerror/node_modules/jju/lib/parse.js:745:13

### supporting information:

 - `npm -v` prints:  v8.2.1
 - `node -v` prints:  v5.3.0
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:  OS X/macOS
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ✔️] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by swiftone** [comment]
No idea if it is the cause of THIS issue, but I've seen similar reports that are solved by running 
`npm cache clean`

**Comment by fabricioaugusto** [comment]
npm cache clean --force solved a similar error

**Comment by devfabricio** [comment]
`npm cache clean --force` solved a similar error

**Comment by yubaoquan** [comment]
Same problem, cache clean not solve it.

**Comment by JoeyLi-1** [comment]
@proshuai  @yubaoquan 
Try: npm set registry https://registry.npm.taobao.org
It works for me. Seems network speed issue.

**Comment by hifizz** [comment]
Same problem, `npm cache clean --force`  solved it. 

![image](https://user-images.githubusercontent.com/9417971/34260517-2ee1084e-e6a1-11e7-9789-1c78ae5285da.png)

then:

![image](https://user-images.githubusercontent.com/9417971/34260550-4d5435f8-e6a1-11e7-8fba-ec01461898b5.png)

**Comment by BenjaminNjoroge** [comment]
This happens mostly due to poor internet connection. fix your internet issues then run 
`npm  cache clean --force` and then run `npm install -g firebase-tools`

**Comment by Hassuunna** [comment]
`npm cache clean --force` really helped, Thanks.

![thx](https://user-images.githubusercontent.com/29715714/41678873-a022e7d4-74cc-11e8-8487-9d3c229681bb.png)
