### ISSUE TITLE
Unable to install node-sass globally

### ISSUE THREAD

**Issue by alshdavid** [npm/npm#18032]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Firstly, love Node and npm and thank you for developing this project. 
I have been having this issue since I upgraded to node 8.

`npm install -g node-sass` on a Vultr Ubuntu 17.04 server, using the `root` user.
This happens when trying to install the Angular CLI as well as `node-sass` directly.
I have tried this on Windows and Ubuntu with the exact same result.
This has been a problem for me throughout node 8
I have been using `yarn` to get around the issue, which has been working so far 

### supporting information:

 - `npm -v` prints: 5.3.0
 - `node -v` prints: v8.2.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Ubuntu 17.04
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by coolchip** [comment]
What is your error output or logfile?

**Comment by KMayne** [comment]
I also get problems attempting to install global packages as root on Ubuntu.
