### ISSUE TITLE
npm ERR! Windows_NT 6.2.9200 npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\ node_modules\\npm\\bin\\npm-cli.js" "install" npm ERR! node v6.11.0 npm ERR! npm  v3.10.10  npm ERR! shasum check failed for C:\Users\SONY\AppData\Local\Temp\npm-6820-34d77 2da\registry.npmjs.org\_40types\angular\-\angular-1.6.28.tgz npm ERR! Expected: e85d62c72c5fbd408b463cd2c9d24f75cc6bec98 npm ERR! Actual:   940b171245c913553e4a5a215eca2b53fae1565e npm ERR! From:     https://registry.npmjs.org/@types/angular/-/angular-1.6.28.tg z

### ISSUE THREAD

**Issue by aveydd** [npm/npm#18039]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by mzaidse** [comment]
facing the same issue...
```
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10

npm ERR! shasum check failed for C:\Users\MUHAMM~1\AppData\Local\Temp\npm-11288-f10c3f2e\registry.npmjs.org\karma\-\karma-1.2.0.tgz
npm ERR! Expected: 6dca89ec25f4753f120f834c89398098040fd63e
npm ERR! Actual:   011b23718d91fd2d9631613756aa01470f700527
npm ERR! From:     https://registry.npmjs.org/karma/-/karma-1.2.0.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

**Comment by aveydd** [comment]
Try updating **Nodejs** to current version https://nodejs.org. It worked for me.
