### ISSUE TITLE
Failed to execute 'npm install' under AnjularJS project with package.son

### ISSUE THREAD

**Issue by lipinggm** [npm/npm#18046]
#### I'm opening this issue because:

  Fail to execute 'npm install'

#### What's going wrong?
  Errors thrown in log file:
   

> 11 silly lifecycle angular-xxx-core@1.0.0~maven-builder: Args: [ '/d /s /c',
11 silly lifecycle   'npm cache verify clean && npm install && npm run build-template-cache && npm run test-build && npm run docs && npm run minify' ]
12 info lifecycle angular-xxx-core@1.0.0~maven-builder: Failed to exec maven-builder script
13 verbose stack Error: angular-xxx-core@1.0.0 maven-builder: `npm cache verify clean && npm install && npm run build-template-cache && npm run test-build && npm run docs && npm run minify`
13 verbose stack spawn C:\windows\system32\cmd.exe;C:\selenium ENOENT
13 verbose stack     at exports._errnoException (util.js:1022:11)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:189:19)
13 verbose stack     at onErrorNT (internal/child_process.js:366:16)
13 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:102:11)
13 verbose stack     at process._tickCallback (internal/process/next_tick.js:161:9)
14 verbose pkgid angular-xxx-core@1.0.0
15 verbose cwd C:\$project
16 verbose Windows_NT 6.1.7601
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "maven-builder"
18 verbose node v8.1.4
19 verbose npm  v5.0.3
20 error file C:\windows\system32\cmd.exe;C:\selenium
21 error path C:\windows\system32\cmd.exe;C:\selenium
22 error code ELIFECYCLE
23 error errno ENOENT
24 error syscall spawn C:\windows\system32\cmd.exe;C:\selenium
25 error angular-xxx-core@1.0.0 maven-builder: `npm cache verify clean && npm install && npm run build-template-cache && npm run test-build && npm run docs && npm run minify`
25 error spawn C:\windows\system32\cmd.exe;C:\selenium ENOENT
26 error Failed at the angular-xxx-core@1.0.0 maven-builder script.
26 error This is probably not a problem with npm. There is likely additional logging output above.
27 verbose exit [ 1, true ]

  
#### How can the CLI team reproduce the problem?

  run 'npm install' under AngularJS project with package.son
  package.json:
       

> {
  "author": "xxx",
  "name": "angular-xxx-core",
  "version": "1.0.0",
  "private": true,
  "description": "xxx xxx.",
  "devDependencies": {
    "angular": "^1.5.0",
    "angular-mocks": "^1.5.0",
    "angular-route": "^1.5.0",
    "angular-ui-bootstrap": "^1.2.5",
    "angular-ui-mask": "^1.8.2",
    "dir-generate": "0.1.2",
    "eslint": "2.4.0",
    "google-closure-compiler": "20160208.7.0",
    "ink-docstrap": "1.1.4",
    "jasmine-core": "^2.4.1",
    "jquery": "^2.2.2",
    "jsdoc": "3.4.0",
    "karma": "^0.13.22",
    "karma-chrome-launcher": "^0.2.3",
    "karma-firefox-launcher": "^0.1.7",
    "karma-jasmine": "^0.3.7",
    "karma-phantomjs-launcher": "^1.0.0",
    "moment": "2.12.0",
    "npm-html2js": "0.1.8",
    "sinon": "1.17.4",
    "phantomjs-prebuilt": "^2.1.5",
    "sanitize-html": "^1.11.3",
    "source-map-support": "^0.4.0",
    "xmlhttprequest": "^1.8.0"
  },
  "dependencies": {
    "karma": "^0.13.22"  },
  "scripts": {
    "build-template-cache": "npm run generate-directories && npm-html2js -m \"xxx.core.template-cache\" -b \"src/main/webapp/js/widgets\" -i \"src/main/webapp/js/widgets/**/*.html\" -o \"target/webapp/scripts/xxx-template-cache.js\"",
    "docs": "jsdoc -c jsDocConfiguration.json --verbose",
    "generate-directories": "dir-generate -f ./generateDirectoriesForNpmBuild.md",
    "lint": "eslint src/main/webapp/js",
    "tdd": "karma start karma.config.js --auto-watch=true --single-run=false --browsers Chrome,Firefox,PhantomJS --log-level debug",
    "tdd-chrome": "karma start karma.config.js --auto-watch=true --single-run=false --browsers Chrome --log-level debug",
    "test-build": "karma start karma.config.js --browsers PhantomJS --log-level error",
    "test": "karma start karma.config.js --browsers Chrome --log-level debug",
    "minify": "java -jar node_modules/google-closure-compiler/compiler.jar --compilation_level SIMPLE --create_source_map target/webapp/scripts/xxx-core.min.js.map --language_in ECMASCRIPT5_STRICT --language_out ECMASCRIPT5_STRICT --js=\"src/main/webapp/js/0002-xxx-module-loader.js\" --js=\"src/main/webapp/js/*.module.js\" --js=\"src/main/webapp/js/**/*.js\" --js=\"!src/main/webapp/js/**/0000-mc-logger.js\" --js=\"!src/main/webapp/js/**/languages/*.js\" --js=\"!src/main/webapp/js/**/*.min.js\" --js=\"!src/main/webapp/js/**/*-templates.js\" --js_output_file \"target/webapp/scripts/xxx-core.min.js\"",
    "maven-builder": "npm install && npm run build-template-cache && npm run test-build && npm run docs && npm run minify"
  }
}

### supporting information:

 - `npm -v` prints: 5.0.3
 - `node -v` prints: 8.1.4
 - `npm config get registry` prints: http://registry.npmjs.org/
 - Windows: Window 7
 - Network issues:
    - I use a proxy when downloading Git repos.

**Comment by ox** [comment]
It seems like you don't have Selenium installed:

``` verbose stack spawn C:\windows\system32\cmd.exe;C:\selenium ENOENT```

but this is not an npm issue, though.

**Comment by lipinggm** [comment]
Actually I do have %SELENIUM_HOME% environment set before in the past for automation test, but it has nothing to do with npm. After I removed all selenium related environment and scripts/tools. The error is:
npm ERR! npm  v3.10.10
npm ERR! file C:\windows\system32\cmd.exe;%SELENIUM_HOME%
npm ERR! path C:\windows\system32\cmd.exe;%SELENIUM_HOME%
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn C:\windows\system32\cmd.exe;%SELENIUM_HOME%
npm ERR! home_project@0.0.1 maven-builder: `npm install jsdoc -g && npm install && npm run deploy-test && npm run docs && npm run minify`
npm ERR! spawn C:\windows\system32\cmd.exe;%SELENIUM_HOME% ENOENT

**Comment by lipinggm** [comment]
Found root cause, my PC's system variable ComSpec's value somehow is mistakenly set to 'C:\windows\system32\cmd.exe;%SELENIUM_HOME%' instead of 'C:\windows\system32\cmd.exe'. The ticket could be closed. Thanks!
