### ISSUE TITLE
npm ERR! Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by gmli-eu** [npm/npm#18042]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
```
npm install webpack-livereload-plugin -D

npm info lifecycle undefined~preuninstall: undefined
npm info lifecycle undefined~uninstall: undefined
npm WARN ajv-keywords@1.5.1 requires a peer of ajv@>=4.10.0 but none was installed.

npm ERR! Cannot read property '0' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/miguelangelo/.npm/_logs/2017-08-02T11_34_26_456Z-debug.log
```

#### How can the CLI team reproduce the problem?
Install following packages:
```
"auto-prefixer": "^0.4.2",
"autoprefixer": "^7.1.2",
"babel-core": "^6.25.0",
"babel-loader": "^7.1.1",
"babel-preset-es2015": "^6.24.1",
"babel-preset-stage-0": "^6.24.1",
"css-loader": "^0.28.4",
"eslint": "^4.3.0",
"eslint-config-google": "^0.9.1",
"eslint-loader": "^1.9.0",
"extract-text-webpack-plugin": "^3.0.0",
"file-loader": "^0.11.2",
"html-webpack-plugin": "^2.29.0",
"modernizr": "^3.5.0",
"modernizr-loader": "^1.0.1",
"node-sass": "^4.5.3",
"postcss-loader": "^2.0.6",
"rimraf": "^2.6.1",
"sass-loader": "^6.0.6",
"style-loader": "^0.18.2",
"url-loader": "^0.5.9",
"webpack": "^3.4.0",
"webpack-svgstore-plugin": "^4.0.1"
```
and then run
`npm install webpack-livereload-plugin -d`

npm-debug.log file: [2017-08-02T11_34_26_456Z-debug.log.txt](https://github.com/npm/npm/files/1193686/2017-08-02T11_34_26_456Z-debug.log.txt)

### supporting information:

 - `npm -v` prints: `5.3.0`
 - `node -v` prints: `v8.2.1`
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?: `OS X/macOS`
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [x] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

Related information: https://github.com/statianzo/webpack-livereload-plugin/issues/34

**Comment by flowfarouk** [comment]
Same 
node -v v6.11.1
npm -v 5.3.0

**Comment by robinhouston** [comment]
This looks like a duplicate of #17858

**Comment by gmli-eu** [comment]
Thank you for pointing that out @robinhouston, one of the comments have the solution for this issue.

**Solution:** delete `node_modules` folder and `package-lock.json` file.

Closing and out!

**Comment by lukrizal** [comment]
in my case, I solve the problem by:
> Reinstalling build-essentials(for Debian) and gcc-c++ make(for Fedora)
> Downgrading from 5.4 to 5.3

**Comment by vgvinay2** [comment]
node6.9.3
npm 5.3.0

downgrading to 5.2 solve the problem

**Comment by garenyondem** [comment]
The same error happened to me now. Downgrading from 8.9.0 to 6.11.x solved the problem.

**Comment by fabioimpe** [comment]
Same problem for me too, deleted the node_modules folder and then it worked

**Comment by MuneebSaeed** [comment]
Nothing is working for me.
I deleted node_modules and lock.json (both was in the project)
Downgrade to 
node: v8.1.3
npm: 5.2.0

but still facing same issue.
@fabioimpe can you please confirm which node_module folder should delete? 
one is in the project and the other is in lib root folder (/usr/local/libs)
and which versions should i use for npm and node?

**Comment by fabioimpe** [comment]
@MuneebSaeed
I'm on node 7.9.0 and npm 5.5.1
I just deleted the node_modules in the project folder

**Comment by MuneebSaeed** [comment]
@fabioimpe i dont know whats going on with my project...
Should i install everything again?? May be there are multiple nodes or npm??

**Comment by DavidTheProgrammer** [comment]
`npm cache clean --force` fixed it for me 

node version 8.9.1
npm 5.2.0

**Comment by MuneebSaeed** [comment]
oh! I don't know why it worked now. I have already done cache clean many times but this time it happened.
I just update my node to 8.9.1
and npm 5.2.0

Thanks everybody! You people are awesome.

**Comment by isarfaktor** [comment]
Hi all,

i still cannot solve this problem. My package.json:

```
{
    "private": true,
    "scripts": {
        "dev": "npm run development",
        "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch-poll": "npm run watch -- --watch-poll",
        "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
        "prod": "npm run production",
        "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
    },
    "devDependencies": {
        "axios": "^0.17",
        "bootstrap-sass": "^3.3.7",
        "cross-env": "^5.1",
        "jquery": "^3.2",
        "laravel-mix": "^1.6.1",
        "lodash": "^4.17.4",
        "vue": "^2.0",
        "webpack": "^3.8.1",
        "css-loader": "^0.28.7",
        "style-loader": "^0.19.0",
        "vue-loader": "^13.5.0",
        "vue-events": "^3.1.0",
        "vue-html-loader": "^1.0.0",
        "vue-template-compiler": "^2.0"
    },
    "dependencies": {
        "babel-core": "^6.0.0",
        "babel-loader": "^7.1.2",
        "babel-plugin-transform-runtime": "^6.23.0",
        "babel-preset-es2015": "^6.24.1",
        "babel-runtime": "^6.26.0",
        "vue-hot-reload-api": "^2.2.4"
    }
}

```

And I get the error:

[> npm run development


> @ development /Users/sebastianscharf/Documents/Development/Medifaktor/MFS
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

 95% emitting

 ERROR  Failed to compile with 7 errors                                                                                                                                                                                                                             4:00:31 PM

These relative modules were not found:

* ./patterns/3.png in ./node_modules/css-loader?{"url":true,"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader/lib?{"sourceMap":true,"ident":"postcss","plugins":[null]}!./node_modules/resolve-url-loader?{"sourceMap":true,"root":"/Users/sebastianscharf/Documents/Development/Medifaktor/MFS/node_modules"}!./node_modules/sass-loader/lib/loader.js?{"precision":8,"outputStyle":"expanded","sourceMap":true}!./resources/assets/sass/app.scss
* ./patterns/4.png in ./node_modules/css-loader?{"url":true,"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader/lib?{"sourceMap":true,"ident":"postcss","plugins":[null]}!./node_modules/resolve-url-loader?{"sourceMap":true,"root":"/Users/sebastianscharf/Documents/Development/Medifaktor/MFS/node_modules"}!./node_modules/sass-loader/lib/loader.js?{"precision":8,"outputStyle":"expanded","sourceMap":true}!./resources/assets/sass/app.scss
* ./patterns/header-profile-skin-1.png in ./node_modules/css-loader?{"url":true,"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader/lib?{"sourceMap":true,"ident":"postcss","plugins":[null]}!./node_modules/resolve-url-loader?{"sourceMap":true,"root":"/Users/sebastianscharf/Documents/Development/Medifaktor/MFS/node_modules"}!./node_modules/sass-loader/lib/loader.js?{"precision":8,"outputStyle":"expanded","sourceMap":true}!./resources/assets/sass/app.scss
* ./patterns/header-profile-skin-2.png in ./node_modules/css-loader?{"url":true,"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader/lib?{"sourceMap":true,"ident":"postcss","plugins":[null]}!./node_modules/resolve-url-loader?{"sourceMap":true,"root":"/Users/sebastianscharf/Documents/Development/Medifaktor/MFS/node_modules"}!./node_modules/sass-loader/lib/loader.js?{"precision":8,"outputStyle":"expanded","sourceMap":true}!./resources/assets/sass/app.scss
* ./patterns/header-profile-skin-3.png in ./node_modules/css-loader?{"url":true,"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader/lib?{"sourceMap":true,"ident":"postcss","plugins":[null]}!./node_modules/resolve-url-loader?{"sourceMap":true,"root":"/Users/sebastianscharf/Documents/Development/Medifaktor/MFS/node_modules"}!./node_modules/sass-loader/lib/loader.js?{"precision":8,"outputStyle":"expanded","sourceMap":true}!./resources/assets/sass/app.scss
* ./patterns/header-profile.png in ./node_modules/css-loader?{"url":true,"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader/lib?{"sourceMap":true,"ident":"postcss","plugins":[null]}!./node_modules/resolve-url-loader?{"sourceMap":true,"root":"/Users/sebastianscharf/Documents/Development/Medifaktor/MFS/node_modules"}!./node_modules/sass-loader/lib/loader.js?{"precision":8,"outputStyle":"expanded","sourceMap":true}!./resources/assets/sass/app.scss
* ./patterns/shattered.png in ./node_modules/css-loader?{"url":true,"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader/lib?{"sourceMap":true,"ident":"postcss","plugins":[null]}!./node_modules/resolve-url-loader?{"sourceMap":true,"root":"/Users/sebastianscharf/Documents/Development/Medifaktor/MFS/node_modules"}!./node_modules/sass-loader/lib/loader.js?{"precision":8,"outputStyle":"expanded","sourceMap":true}!./resources/assets/sass/app.scss
          Asset    Size  Chunks             Chunk Names
    /js/main.js  128 kB       0  [emitted]  /js/main
/css/vendor.css  253 kB          [emitted]
     /js/app.js  181 kB          [emitted]

ERROR in ./resources/assets/sass/app.scss
Module build failed: ModuleNotFoundError: Module not found: Error: Can't resolve './patterns/3.png' in '/Users/sebastianscharf/Documents/Development/Medifaktor/MFS/resources/assets/sass'
    at factoryCallback (/Users/sebastianscharf/Documents/Development/Medifaktor/MFS/node_modules/webpack/lib/Compilation.js:276:40)
    at factory (/Users/sebastianscharf/Documents/Development/Medifaktor/MFS/node_modules/webpack/lib/NormalModuleFactory.js:235:20)
    at resolver (/Users/sebastianscharf/Documents/Development/Medifaktor/MFS/node_modules/webpack/lib/NormalModuleFactory.js:60:20)
    at asyncLib.parallel (/Users/sebastianscharf/Documents/Development/Medifaktor/MFS/node_modules/webpack/lib/NormalModuleFactory.js:127:20)
    at /Users/sebastianscharf/Documents/Development/Medifaktor/MFS/node_modules/async/dist/async.js:3874:9
    at /Users/sebastianscharf/Documents/Development/Medifaktor/MFS/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/Users/sebastianscharf/Documents/Development/Medifaktor/MFS/node_modules/async/dist/async.js:1048:13)
    at /Users/sebastianscharf/Documents/Development/Medifaktor/MFS/node_modules/async/dist/async.js:958:16
    at /Users/sebastianscharf/Documents/Development/Medifaktor/MFS/node_modules/async/dist/async.js:3871:13
    at resolvers.normal.resolve (/Users/sebastianscharf/Documents/Development/Medifaktor/MFS/node_modules/webpack/lib/NormalModuleFactory.js:119:22)
    at onError (/Users/sebastianscharf/Documents/Development/Medifaktor/MFS/node_modules/enhanced-resolve/lib/Resolver.js:65:10)
    at loggingCallbackWrapper (/Users/sebastianscharf/Documents/Development/Medifaktor/MFS/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at runAfter (/Users/sebastianscharf/Documents/Development/Medifaktor/MFS/node_modules/enhanced-resolve/lib/Resolver.js:158:4)
    at innerCallback (/Users/sebastianscharf/Documents/Development/Medifaktor/MFS/node_modules/enhanced-resolve/lib/Resolver.js:146:3)
    at loggingCallbackWrapper (/Users/sebastianscharf/Documents/Development/Medifaktor/MFS/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/Users/sebastianscharf/Documents/Development/Medifaktor/MFS/node_modules/tapable/lib/Tapable.js:252:11)
    at /Users/sebastianscharf/Documents/Development/Medifaktor/MFS/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:40:4
    at loggingCallbackWrapper (/Users/sebastianscharf/Documents/Development/Medifaktor/MFS/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at runAfter (/Users/sebastianscharf/Documents/Development/Medifaktor/MFS/node_modules/enhanced-resolve/lib/Resolver.js:158:4)
    at innerCallback (/Users/sebastianscharf/Documents/Development/Medifaktor/MFS/node_modules/enhanced-resolve/lib/Resolver.js:146:3)
    at loggingCallbackWrapper (/Users/sebastianscharf/Documents/Development/Medifaktor/MFS/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/Users/sebastianscharf/Documents/Development/Medifaktor/MFS/node_modules/tapable/lib/Tapable.js:252:11)
    at innerCallback (/Users/sebastianscharf/Documents/Development/Medifaktor/MFS/node_modules/enhanced-resolve/lib/Resolver.js:144:11)
    at loggingCallbackWrapper (/Users/sebastianscharf/Documents/Development/Medifaktor/MFS/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/Users/sebastianscharf/Documents/Development/Medifaktor/MFS/node_modules/tapable/lib/Tapable.js:249:35)
    at resolver.doResolve.createInnerCallback (/Users/sebastianscharf/Documents/Development/Medifaktor/MFS/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:44:6)
    at loggingCallbackWrapper (/Users/sebastianscharf/Documents/Development/Medifaktor/MFS/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at afterInnerCallback (/Users/sebastianscharf/Documents/Development/Medifaktor/MFS/node_modules/enhanced-resolve/lib/Resolver.js:168:10)
    at loggingCallbackWrapper (/Users/sebastianscharf/Documents/Development/Medifaktor/MFS/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/Users/sebastianscharf/Documents/Development/Medifaktor/MFS/node_modules/tapable/lib/Tapable.js:252:11)
 @ ./resources/assets/sass/app.scss
 @ multi ./resources/assets/js/base.js ./resources/assets/sass/app.scss

ERROR in ./node_modules/css-loader?{"url":true,"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader/lib?{"sourceMap":true,"ident":"postcss","plugins":[null]}!./node_modules/resolve-url-loader?{"sourceMap":true,"root":"/Users/sebastianscharf/Documents/Development/Medifaktor/MFS/node_modules"}!./node_modules/sass-loader/lib/loader.js?{"precision":8,"outputStyle":"expanded","sourceMap":true}!./resources/assets/sass/app.scss
Module not found: Error: Can't resolve './patterns/3.png' in '/Users/sebastianscharf/Documents/Development/Medifaktor/MFS/resources/assets/sass'
 @ ./node_modules/css-loader?{"url":true,"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader/lib?{"sourceMap":true,"ident":"postcss","plugins":[null]}!./node_modules/resolve-url-loader?{"sourceMap":true,"root":"/Users/sebastianscharf/Documents/Development/Medifaktor/MFS/node_modules"}!./node_modules/sass-loader/lib/loader.js?{"precision":8,"outputStyle":"expanded","sourceMap":true}!./resources/assets/sass/app.scss 7:156802-156829
 @ ./resources/assets/sass/app.scss
 @ multi ./resources/assets/js/base.js ./resources/assets/sass/app.scss

ERROR in ./node_modules/css-loader?{"url":true,"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader/lib?{"sourceMap":true,"ident":"postcss","plugins":[null]}!./node_modules/resolve-url-loader?{"sourceMap":true,"root":"/Users/sebastianscharf/Documents/Development/Medifaktor/MFS/node_modules"}!./node_modules/sass-loader/lib/loader.js?{"precision":8,"outputStyle":"expanded","sourceMap":true}!./resources/assets/sass/app.scss
Module not found: Error: Can't resolve './patterns/4.png' in '/Users/sebastianscharf/Documents/Development/Medifaktor/MFS/resources/assets/sass'
 @ ./node_modules/css-loader?{"url":true,"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader/lib?{"sourceMap":true,"ident":"postcss","plugins":[null]}!./node_modules/resolve-url-loader?{"sourceMap":true,"root":"/Users/sebastianscharf/Documents/Development/Medifaktor/MFS/node_modules"}!./node_modules/sass-loader/lib/loader.js?{"precision":8,"outputStyle":"expanded","sourceMap":true}!./resources/assets/sass/app.scss 7:156903-156930 7:165082-165109
 @ ./resources/assets/sass/app.scss
 @ multi ./resources/assets/js/base.js ./resources/assets/sass/app.scss

ERROR in ./node_modules/css-loader?{"url":true,"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader/lib?{"sourceMap":true,"ident":"postcss","plugins":[null]}!./node_modules/resolve-url-loader?{"sourceMap":true,"root":"/Users/sebastianscharf/Documents/Development/Medifaktor/MFS/node_modules"}!./node_modules/sass-loader/lib/loader.js?{"precision":8,"outputStyle":"expanded","sourceMap":true}!./resources/assets/sass/app.scss
Module not found: Error: Can't resolve './patterns/header-profile-skin-1.png' in '/Users/sebastianscharf/Documents/Development/Medifaktor/MFS/resources/assets/sass'
 @ ./node_modules/css-loader?{"url":true,"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader/lib?{"sourceMap":true,"ident":"postcss","plugins":[null]}!./node_modules/resolve-url-loader?{"sourceMap":true,"root":"/Users/sebastianscharf/Documents/Development/Medifaktor/MFS/node_modules"}!./node_modules/sass-loader/lib/loader.js?{"precision":8,"outputStyle":"expanded","sourceMap":true}!./resources/assets/sass/app.scss 7:156403-156450 7:157416-157463
 @ ./resources/assets/sass/app.scss
 @ multi ./resources/assets/js/base.js ./resources/assets/sass/app.scss

ERROR in ./node_modules/css-loader?{"url":true,"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader/lib?{"sourceMap":true,"ident":"postcss","plugins":[null]}!./node_modules/resolve-url-loader?{"sourceMap":true,"root":"/Users/sebastianscharf/Documents/Development/Medifaktor/MFS/node_modules"}!./node_modules/sass-loader/lib/loader.js?{"precision":8,"outputStyle":"expanded","sourceMap":true}!./resources/assets/sass/app.scss
Module not found: Error: Can't resolve './patterns/header-profile-skin-2.png' in '/Users/sebastianscharf/Documents/Development/Medifaktor/MFS/resources/assets/sass'
 @ ./node_modules/css-loader?{"url":true,"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader/lib?{"sourceMap":true,"ident":"postcss","plugins":[null]}!./node_modules/resolve-url-loader?{"sourceMap":true,"root":"/Users/sebastianscharf/Documents/Development/Medifaktor/MFS/node_modules"}!./node_modules/sass-loader/lib/loader.js?{"precision":8,"outputStyle":"expanded","sourceMap":true}!./resources/assets/sass/app.scss 7:159641-159688
 @ ./resources/assets/sass/app.scss
 @ multi ./resources/assets/js/base.js ./resources/assets/sass/app.scss

ERROR in ./node_modules/css-loader?{"url":true,"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader/lib?{"sourceMap":true,"ident":"postcss","plugins":[null]}!./node_modules/resolve-url-loader?{"sourceMap":true,"root":"/Users/sebastianscharf/Documents/Development/Medifaktor/MFS/node_modules"}!./node_modules/sass-loader/lib/loader.js?{"precision":8,"outputStyle":"expanded","sourceMap":true}!./resources/assets/sass/app.scss
Module not found: Error: Can't resolve './patterns/header-profile-skin-3.png' in '/Users/sebastianscharf/Documents/Development/Medifaktor/MFS/resources/assets/sass'
 @ ./node_modules/css-loader?{"url":true,"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader/lib?{"sourceMap":true,"ident":"postcss","plugins":[null]}!./node_modules/resolve-url-loader?{"sourceMap":true,"root":"/Users/sebastianscharf/Documents/Development/Medifaktor/MFS/node_modules"}!./node_modules/sass-loader/lib/loader.js?{"precision":8,"outputStyle":"expanded","sourceMap":true}!./resources/assets/sass/app.scss 7:156589-156636 7:163116-163163
 @ ./resources/assets/sass/app.scss
 @ multi ./resources/assets/js/base.js ./resources/assets/sass/app.scss

ERROR in ./node_modules/css-loader?{"url":true,"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader/lib?{"sourceMap":true,"ident":"postcss","plugins":[null]}!./node_modules/resolve-url-loader?{"sourceMap":true,"root":"/Users/sebastianscharf/Documents/Development/Medifaktor/MFS/node_modules"}!./node_modules/sass-loader/lib/loader.js?{"precision":8,"outputStyle":"expanded","sourceMap":true}!./resources/assets/sass/app.scss
Module not found: Error: Can't resolve './patterns/header-profile.png' in '/Users/sebastianscharf/Documents/Development/Medifaktor/MFS/resources/assets/sass'
 @ ./node_modules/css-loader?{"url":true,"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader/lib?{"sourceMap":true,"ident":"postcss","plugins":[null]}!./node_modules/resolve-url-loader?{"sourceMap":true,"root":"/Users/sebastianscharf/Documents/Development/Medifaktor/MFS/node_modules"}!./node_modules/sass-loader/lib/loader.js?{"precision":8,"outputStyle":"expanded","sourceMap":true}!./resources/assets/sass/app.scss 7:3273-3313
 @ ./resources/assets/sass/app.scss
 @ multi ./resources/assets/js/base.js ./resources/assets/sass/app.scss

ERROR in ./node_modules/css-loader?{"url":true,"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader/lib?{"sourceMap":true,"ident":"postcss","plugins":[null]}!./node_modules/resolve-url-loader?{"sourceMap":true,"root":"/Users/sebastianscharf/Documents/Development/Medifaktor/MFS/node_modules"}!./node_modules/sass-loader/lib/loader.js?{"precision":8,"outputStyle":"expanded","sourceMap":true}!./resources/assets/sass/app.scss
Module not found: Error: Can't resolve './patterns/shattered.png' in '/Users/sebastianscharf/Documents/Development/Medifaktor/MFS/resources/assets/sass'
 @ ./node_modules/css-loader?{"url":true,"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader/lib?{"sourceMap":true,"ident":"postcss","plugins":[null]}!./node_modules/resolve-url-loader?{"sourceMap":true,"root":"/Users/sebastianscharf/Documents/Development/Medifaktor/MFS/node_modules"}!./node_modules/sass-loader/lib/loader.js?{"precision":8,"outputStyle":"expanded","sourceMap":true}!./resources/assets/sass/app.scss 7:83255-83290
 @ ./resources/assets/sass/app.scss
 @ multi ./resources/assets/js/base.js ./resources/assets/sass/app.scss
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sebastianscharf/.npm/_logs/2017-11-25T15_00_31_213Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sebastianscharf/.npm/_logs/2017-11-25T15_00_31_296Z-debug.log
](url)

**Comment by n3nad** [comment]
Had a nightmare with "npm ERR! Cannot read property '0' of undefined".
The problem was with npm version.
This resolved the issue:

1. npm install npm@5.2.0 -g
2. npm cache clean --force
3. npm install

Cheers!

**Comment by mjasnikovs** [comment]
Use "yarn"
Spend ~two days looking at npm issues, over and over. Installed yarn, everything worked on first try.

**Comment by nickpettican** [comment]
@n3nad you sir, are a hero

**Comment by prabhpahul** [comment]
@n3nad  thank you sir.

**Comment by ghost** [comment]
@n3nad FTW!!! Big thanks!

**Comment by mrpatel15** [comment]
[2018-02-16T03_37_12_250Z-debug.log](https://github.com/npm/npm/files/1730139/2018-02-16T03_37_12_250Z-debug.log)

**Comment by mrpatel15** [comment]
same issues, npm ERR! Cannot read property '0' of undefined

**Comment by ghost** [comment]
solved above.

Had a nightmare with "npm ERR! Cannot read property '0' of undefined".
The problem was with npm version.
This resolved the issue:

npm install npm@5.2.0 -g
npm cache clean --force
npm install
Cheers!

**Comment by hashim-zhd** [comment]
@n3nad works for me... Cheers!
