### ISSUE TITLE
Unable to install angular-cli via npm

### ISSUE THREAD

**Issue by lbaguimatang** [npm/npm#18051]
#### I'm opening this issue because:
  - [ ] npm is crashing.

#### What's going wrong?
Installing angular-cli on a mac

#### How can the CLI team reproduce the problem?
I was about to start learning angular, I ran 'npm -g @angular/cli' on my terminal.
Some suggested running 'npm cache clear' and or 'npm cache verify' and rerun
'npm -g @angular/cli'

> 190 http fetch GET 304 https://registry.npmjs.org/script-loader 815ms (from cache)
> 191 silly pacote range manifest for script-loader@^0.7.0 fetched in 816ms
> 192 silly resolveWithNewModule script-loader@0.7.0 checking installable status
> 193 http fetch GET 304 https://registry.npmjs.org/temp 1095ms (from cache)
> 194 silly pacote version manifest for temp@0.8.3 fetched in 1096ms
> 195 silly resolveWithNewModule temp@0.8.3 checking installable status
> 196 verbose stack SyntaxError: Unexpected end of input at 1:26011
> 196 verbose stack ader":"~0.7.5","style-loader":"~0.6.3","file-loader":"~0.5.1","jade-l
> 196 verbose stack                                                                      ^
> 196 verbose stack     at Object.parseJSON (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/node_modules/json-parse-helpfulerror/node_modules/jju/lib/parse.js:745:13)
> 196 verbose stack     at parse (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/node_modules/json-parse-helpfulerror/index.js:10:13)
> 196 verbose stack     at consumeBody.call.then.buffer (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/body.js:96:50)
> 196 verbose stack     at <anonymous>
> 196 verbose stack     at process._tickCallback (internal/process/next_tick.js:188:7)
> 197 verbose cwd /Users/leoaguimatang
> 198 verbose Darwin 16.7.0
> 199 verbose argv "/usr/local/Cellar/node/8.2.1/bin/node" "/usr/local/bin/npm" "install" "-g" "@angular/cli"
> 200 verbose node v8.2.1
> 201 verbose npm  v5.3.0
> 202 error Unexpected end of input at 1:26011
> 202 error ader":"~0.7.5","style-loader":"~0.6.3","file-loader":"~0.5.1","jade-l
> 202 error                                                                      ^
> 203 verbose exit [ 1, true ]

### supporting information:

 - `npm -v` prints:
5.3.0
 - `node -v` prints:
8.2.1
 - `npm config get registry` prints:
https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?:
macOS Sierra
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by EvanCarroll** [comment]
Run `npm cache clean --force` and try again.
