### ISSUE TITLE
Can't install git repository as npm package, v5.3.0

### ISSUE THREAD

**Issue by AleshaOleg** [npm/npm#18069]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Can't install github repository as npm package.

#### How can the CLI team reproduce the problem?

Try to install any GitHub project as npm package, I tried with:
`sudo npm i https://github.com/AleshaOleg/postcss-sass` or
`sudo npm i git+ssh://git@github.com/AleshaOleg/postcss-sass` or I think any type of installing.

Temporary solution is downgrading to v4 of npm.

[Gist](https://gist.github.com/AleshaOleg/4e5509d7ce29e6e7a7f621f107ff7e33) with npm-debug.
### supporting information:

 - `npm -v` prints: 5.3.0
 - `node -v` prints: v8.2.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
I cannot reproduce this with `npm@5.3.0`:

```
$ npm -v
5.3.0

$ npm i https://github.com/AleshaOleg/postcss-sass
+ postcss-sass@0.2.0
added 12 packages in 3.192s
```

**Comment by cachedout** [comment]
I can confirm this exact bug. 

```
mp@silver ...devel/salt/tests % sudo npm -v                                                                                                                                                (git)-[2017.7] 
5.3.0
```


It is totally broken on my personal Arch Linux machines and is also failing tests for the SaltStack Arch Linux tests in Jenkins. [https://jenkins.saltstack.com/job/branch_tests/job/2017.7/job/salt-linode-arch/225/testReport/junit/integration.states.test_npm/NpmStateTest/test_npm_cache_clean/]

To reproduce on my laptop:

```
mp@silver ...devel/salt/tests % sudo npm install --json --silent --global git://github.com/request/request                                                                                 (git)-[2017.7] 
{
  "error": {
    "code": 1,
    "summary": "Command failed: /usr/bin/git clone --depth=1 -q -b master git://github.com/request/request.git /home/mp/.npm/_cacache/tmp/git-clone-ce25ae7b\n/home/mp/.npm/_cacache/tmp/git-clone-ce25ae7b/.git: Permission denied\n",
    "detail": ""
  }
}
```

I have tried deleting all of `/home/mp/.npm` and the error re-occurs. Happy to help with more info.

**Comment by douglasmiller** [comment]
I am also experiencing this issue with npm 5.3.0 and node 6.9.0. The issue is not limited to the `postcss-sass` package, but I've used that as a test to maintain consistency with the thread.

```
[root@z2-deploy tmp]# mkdir npm5-issues
[root@z2-deploy tmp]# mkdir npm5-cache
[root@z2-deploy tmp]# chmod 777 npm5-*
[root@z2-deploy tmp]# npm config set cache=/tmp/npm5-cache
[root@z2-deploy tmp]# cd npm5-issues/
[root@z2-deploy npm5-issues]# npm i https://github.com/AleshaOleg/postcss-sass
npm ERR! code 1
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b master https://github.com/AleshaOleg/postcss-sass.git /tmp/npm5-cache/_cacache/tmp/git-clone-c6ae484b
npm ERR! /tmp/npm5-cache/_cacache/tmp/git-clone-c6ae484b/.git: Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/npm5-cache/_logs/2017-08-14T16_11_55_819Z-debug.log
```

Here is the complete log file for the above error:

```
0 info it worked if it ends with ok
1 verbose cli [ '/opt/nodenv/nodenv-1.0.0/versions/6.9.0/bin/node',
1 verbose cli   '/opt/nodenv/nodenv-1.0.0/versions/6.9.0/bin/npm',
1 verbose cli   'i',
1 verbose cli   'https://github.com/AleshaOleg/postcss-sass' ]
2 info using npm@5.3.0
3 info using node@v6.9.0
4 verbose npm-session c19a6cd3a254cd65
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData error for git+https://github.com/AleshaOleg/postcss-sass.git Command failed: /usr/bin/git clone --depth=1 -q -b master https://github.com/AleshaOleg/postcss-sass.git /tmp/npm5-cache/_cacache/tmp/git-clone-c6ae484b
7 silly fetchPackageMetaData /tmp/npm5-cache/_cacache/tmp/git-clone-c6ae484b/.git: Permission denied
8 verbose stack Error: Command failed: /usr/bin/git clone --depth=1 -q -b master https://github.com/AleshaOleg/postcss-sass.git /tmp/npm5-cache/_cacache/tmp/git-clone-c6ae484b
8 verbose stack /tmp/npm5-cache/_cacache/tmp/git-clone-c6ae484b/.git: Permission denied
8 verbose stack
8 verbose stack     at ChildProcess.exithandler (child_process.js:206:12)
8 verbose stack     at emitTwo (events.js:106:13)
8 verbose stack     at ChildProcess.emit (events.js:191:7)
8 verbose stack     at maybeClose (internal/child_process.js:877:16)
8 verbose stack     at Socket.<anonymous> (internal/child_process.js:334:11)
8 verbose stack     at emitOne (events.js:96:13)
8 verbose stack     at Socket.emit (events.js:188:7)
8 verbose stack     at Pipe._handle.close [as _onclose] (net.js:498:12)
9 verbose cwd /tmp/npm5-issues
10 verbose Linux 4.4.39-34.54.amzn1.x86_64
11 verbose argv "/opt/nodenv/nodenv-1.0.0/versions/6.9.0/bin/node" "/opt/nodenv/nodenv-1.0.0/versions/6.9.0/bin/npm" "i" "https://github.com/AleshaOleg/postcss-sass"
12 verbose node v6.9.0
13 verbose npm  v5.3.0
14 error code 1
15 error Command failed: /usr/bin/git clone --depth=1 -q -b master https://github.com/AleshaOleg/postcss-sass.git /tmp/npm5-cache/_cacache/tmp/git-clone-c6ae484b
15 error /tmp/npm5-cache/_cacache/tmp/git-clone-c6ae484b/.git: Permission denied
16 verbose exit [ 1, true ]
```

This issue appears to be limited to running the npm install command as the root user. If I drop down to my personal user, then I can npm install the package without issue:

```
[dmiller@z2-deploy tmp]$ mkdir npm5-not-root
[dmiller@z2-deploy tmp]$ mkdir npm5-not-root-cache
[dmiller@z2-deploy tmp]$ npm config set cache=/tmp/npm5-not-root-cache/
[dmiller@z2-deploy tmp]$ cd npm5-not-root
[dmiller@z2-deploy npm5-not-root]$ npm i https://github.com/AleshaOleg/postcss-sass
npm WARN saveError ENOENT: no such file or directory, open '/tmp/npm5-not-root/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/tmp/npm5-not-root/package.json'
npm WARN npm5-not-root No description
npm WARN npm5-not-root No repository field.
npm WARN npm5-not-root No README data
npm WARN npm5-not-root No license field.

+ postcss-sass@0.2.0
added 12 packages in 3.294s
```

**Comment by douglasmiller** [comment]
This issue does not exist in versions of npm <5:

```
[root@z2-deploy npm5-issues]# npm --version
4.6.1
[root@z2-deploy npm5-issues]# npm i https://github.com/AleshaOleg/postcss-sass
/tmp/npm5-issues
└─┬ postcss-sass@0.2.0  (git+https://github.com/AleshaOleg/postcss-sass.git#02e99cfecc3127d96edf0977c95facaf9dafd931)
  ├─┬ gonzales-pe@4.0.3 
  │ └── minimist@1.1.3 
  └─┬ postcss@6.0.9 
    ├─┬ chalk@2.1.0 
    │ ├─┬ ansi-styles@3.2.0 
    │ │ └─┬ color-convert@1.9.0 
    │ │   └── color-name@1.1.3 
    │ ├── escape-string-regexp@1.0.5 
    │ └── supports-color@4.2.1  deduped
    ├── source-map@0.5.6 
    └─┬ supports-color@4.2.1 
      └── has-flag@2.0.0 

npm WARN enoent ENOENT: no such file or directory, open '/tmp/npm5-issues/package.json'
npm WARN npm5-issues No description
npm WARN npm5-issues No repository field.
npm WARN npm5-issues No README data
npm WARN npm5-issues No license field.
```

**Comment by AleshaOleg** [comment]
I got `postcss-sass` just for example guys, because this is my repo and i tested on it. As I mentioned, the solution for me was downgrade to 4.x.x.

**Comment by visig9** [comment]
Hit the same problem when run with `root`, include following command:

```sh
sudo npm install -g github:beautify-web/js-beautify
sudo npm install github:beautify-web/js-beautify
sudo npx github:beautify-web/js-beautify  # also affect the npx
```

All error messages are look like the same:

```sh
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b master git://github.com/beautify-web/js-beautify.git /root/.npm/_cacache/tmp/git-clone-d6727156
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-d6727156': Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-08-18T06_44_00_679Z-debug.log
```

But, without any problem when I remove the `sudo` prefix.

## beside...

I also try to run the:

```sh
sudo /usr/bin/git clone --depth=1 -q -b master git://github.com/beautify-web/js-beautify.git /root/.npm/_cacache/tmp/git-clone-d6727156
```

and it's fully successful.

## environment

- npm@5.3.0
- nodejs@8.4.0
- debian 8 and ubuntu 16.04

**Comment by msimerson** [comment]
I have exactly the same results (not bothering to post duplicate logs) as @civalin with FreeBSD 11.1 as the OS.  When I manually run the git command it succeeds as well. Very annoying that installing from git repo doesn't work.

**Comment by msimerson** [comment]
I think this is the same issue as #17736

**Comment by retrocausal** [comment]
I landed up here after my auto build script on launchpad reported the exact same errors

- Happens only with node 8.x and npm 5.3.0
- I switched back to LTS version 6.x and this doesn't happen anymore

```
npm ERR! Command failed: /build/snappy-atom/parts/atom/install/usr/bin/git clone --depth=1 -q -b master https://github.com/kevinsawicki/jasmine-node.git /home/buildd/.npm/_cacache/tmp/git-clone-0cf46f17
npm ERR! /home/buildd/.npm/_cacache/tmp/git-clone-0cf46f17/.git: Permission denied
```

**Comment by AleshaOleg** [comment]
I can confirm too, that happens only with node 8.x (my case 8.4), as @retrocausal mentioned. Also, switched back, and found that everything installs correctly.

**Comment by douglasmiller** [comment]
I continue to have issues with node 6.9.0 and npm 5.3.0. I have gone as far as pushing all github packages to a private npm server to work around this issue. However, there are still packages that I cannot work around (bower-installer). 

This is a 100% blocker for my organization and we will be forced to investigate a full migration to yarn if there isn't even any acknowledgement of this issue from the npm maintainers.

**Comment by iarna** [comment]
This is a permissions issue in the `.npm` cache (to be clear, it implies that there's a permissions related bug). You don't see this w/ npm@4 because that uses an entirely different set of commands and directories for git.

Ok, so with some fiddling I've been able to reproduce this. The root cause of this is that installing a git dependency WITH `sudo` causes permissions in the npm cache to be corrupted such that further installs of git dependencies fail.

You can work around this by running `npm cache clear --force` and then not running `npm install` as with sudo. (Note that running as root, for example via `su -l`, works fine.)

**Comment by iarna** [comment]
Technical discussion of this will need to take place over in the [pacote](https://github.com/zkat/pacote) or [cacache](https://github.com/zkat/cacache) issue trackers. I'm not currently sure which is to blame, though I suspect it may be both of them.

**Comment by 0x3175633435** [comment]
Same problem.

```
root@bevicred-erp-homologacao-1:/var/www/bevicred-gui# npm install
npm WARN deprecated angular2-moment@1.7.0: angular2-moment is now ngx-moment
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git submodule update -q --init --recursive
npm ERR! fatal: Could not change back to '/root/.npm/_cacache/tmp/git-clone-d910f97b': Permission denied
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-05-07T16_12_11_604Z-debug.log
root@bevicred-erp-homologacao-1:/var/www/bevicred-gui# npm -v
6.0.0
root@bevicred-erp-homologacao-1:/var/www/bevicred-gui# node -v
v8.11.1
root@bevicred-erp-homologacao-1:/var/www/bevicred-gui#
```

**Comment by 0x3175633435** [comment]
Even performing a `chown -R root`  and a `chmod -R 777` the problem persists.

**Comment by legodude17** [comment]
@0x3175633435 did you try the steps that iarna [outlined](https://github.com/npm/npm/issues/18069#issuecomment-327636363)?

**Comment by Masterxilo** [comment]
Same problem here, using the abbreviated syntax for installing from a github repo:
```
osboxes@osboxes:~$ node -v
v10.1.0
osboxes@osboxes:~$ npm -v
5.6.0
osboxes@osboxes:~$ sudo npm install --global protobi/query
npm ERR! code 1
npm ERR! Command failed: /usr/bin/git clone -q git://github.com/protobi/query.git /home/osboxes/.npm/_cacache/tmp/git-clone-ecc6bd0a
npm ERR! /home/osboxes/.npm/_cacache/tmp/git-clone-ecc6bd0a/.git: Permission denied
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/osboxes/.npm/_logs/2018-06-06T09_19_00_758Z-debug.log

```
