### ISSUE TITLE
node opencv  features

### ISSUE THREAD

**Issue by CEswar** [npm/npm#18088]
Hi,

 How to achive following opencv function using  Node-opencv in NodeJS (windows environment)

adaptiveThreshold(thr, thr, 255, CV_ADAPTIVE_THRESH_MEAN_C, CV_THRESH_BINARY_INV, 75, 10);

resize(img1, img1, Size(1024, nrow), 0, 0, CV_INTER_AREA);
and
vector<vector<rect>> maskList;

**Comment by kenany** [comment]
@CEswar Hi! This issue tracker is for `npm`-specific issues, not for general support. Perhaps you are better off taking this to StackOverflow or some other help forum. Good luck!
