### ISSUE TITLE
getting error in running copyfiles

### ISSUE THREAD

**Issue by beingbing** [npm/npm#18085]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [o] Other (_see below for feature requests_):

#### What's going wrong?
when i am rnunning copyfiles i am getting missing script message and a whole lot of errors
![screenshot from 2017-08-07 12 41 48](https://user-images.githubusercontent.com/26813160/29017787-0632bf78-7b76-11e7-9e8f-ee146618c86c.png)

#### How can the CLI team reproduce the problem?

<script src="https://gist.github.com/beingbing/404d55e97396331010cdc2ed73f39fec.js"></script>
its sareable URL-
https://gist.github.com/beingbing/404d55e97396331010cdc2ed73f39fec

### supporting information:

 - `npm -v` prints:3.10.10
 - `node -v` prints: v6.11.2
 - `npm config get registry` prints:https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux
 - Network issues:
   - Geographic location where npm was run: India
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [O] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

no i looked in it, but it didn't helped

**Comment by kenany** [comment]
@beingbing Do you have a `"copyfiles"` script defined in your `package.json`? The error message is indicating that you don't.

**Comment by beingbing** [comment]
no sir, i haven't, on your advice i added it and now it is running fine but i new problem is created now it is unable to locate imagemin  this is the link to my package.json files-
https://gist.github.com/beingbing/ebaa73cb5dc029b10ed66648cac04f33

and here is the screenshot of my new problem-
![screenshot from 2017-08-08 20 28 56](https://user-images.githubusercontent.com/26813160/29078660-a58a8c9c-7c78-11e7-9a0a-6ab765a4e0c2.png)
![screenshot from 2017-08-08 20 31 31](https://user-images.githubusercontent.com/26813160/29078661-a58eb7ae-7c78-11e7-9db4-1c2117b21631.png)

**Comment by kenany** [comment]
@beingbing All right, could you now try running

```
npm install -D imagemin-cli
```

and then try again?

**Comment by beingbing** [comment]
it worked, :+1: 
can you explain me why you used is "-D".
by the way, thanks, you are a real life saver.

**Comment by kenany** [comment]
@beingbing `-D` is an alias for `--save-dev`, which adds the installed dependencies to the `"devDependencies"` section of your `package.json`.
