### ISSUE TITLE
angular is not getting downloaded

### ISSUE THREAD

**Issue by antonioantao30** [npm/npm#18083]
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\user\AppData\Local\Temp\npm-7180-baec8010\registry.npmjs.org\normalize-package-data\-\normalize-package-data-2.4.0.tgz.883941255' -> 'C:\Users\user\AppData\Local\Temp\npm-7180-baec8010\registry.npmjs.org\normalize-package-data\-\normalize-package-data-2.4.0.tgz'
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10

npm ERR! tarball.destroy is not a function
npm ERR!

**Comment by dguo** [comment]
Check out https://stackoverflow.com/questions/36835882/npm-err-tarball-destroy-is-not-a-function
