### ISSUE TITLE
npm ERR! shasum check failed for C:\Users\username\AppData\Local\Temp\npm-74216-7c32f91e\registry.npmjs.org\npm\-\npm-2.15.12.tgz

### ISSUE THREAD

**Issue by mdambro** [npm/npm#18090]
#### How can the CLI team reproduce the problem?
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova@6.3.1"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10

npm ERR! shasum check failed for C:\Users\username\AppData\Local\Temp\npm-74216-7c32f91e\registry.npmjs.org\npm\-\npm-2.15.12.tgz
npm ERR! Expected: df7c3ed5a277c3f9d4b5d819b05311d10a200ae6
npm ERR! Actual:   147a8f3cb1380795ecd481ab23b33da5cd779b72
npm ERR! From:     http://registry.npmjs.org/npm/-/npm-2.15.12.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

### supporting information:

 - `npm config get registry` prints: "http://registry.npmjs.org/"
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ X ] I use a proxy to connect to the npm registry.
   - [ X ] I use a proxy to connect to the web.
   - [ X ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton,

**Comment by zhuanli555** [comment]
I meet the problem too,do you solve it?

**Comment by mdambro** [comment]
Hi! yes, i did.
This is my final configuration. Note that https-proxy param has "http://" url.

; userconfig C:\Users\myusername\.npmrc
https-proxy = "http://myusername:mypassword@proxyhost:port/"
proxy = "http://myusername:mypassword@proxyhost:port/"

; globalconfig C:\Users\myusername\AppData\Roaming\npm\etc\npmrc
https-proxy = "http://myusername:mypassword@proxyhost:port/"
proxy = "http://myusername:mypassword@proxyhost:port/"
