### ISSUE TITLE
Refusing to install modbus-serial as a dependency of itself

### ISSUE THREAD

**Issue by sriram1991** [npm/npm#18094]
#### I'm opening this issue because:

  -  npm is producing an incorrect install.

#### What's going wrong?
when i'm try to install modbus for client server connection, Refusing to install modbus-serial as a dependency of itself 
### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on OS X or Linux.

**Comment by kenany** [comment]
@sriram1991 Ensure that the `"name"` field in your `package.json` is not set to `"modbus-serial"`.

**Comment by kenany** [comment]
Closing as abandoned.
