### ISSUE TITLE
The server can't start.

### ISSUE THREAD

**Issue by mumubuku** [npm/npm#18091]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [
<img width="564" alt="9dbde0ad-a852-4f73-9668-f7ed8f52ad4b" src="https://user-images.githubusercontent.com/20900309/29053161-01feef52-7c21-11e7-9aff-8e484f98369f.png">
 ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by jotatoledo** [comment]
Please format your issue

**Comment by fahrradflucht** [comment]
Could you please show the scripts section of your package.json?

**Comment by mumubuku** [comment]
I hava solve it.I use npm first.I should write serve,but l write serve.




------------------ 原始邮件 ------------------
发件人: "Mathis Wiehl";<notifications@github.com>;
发送时间: 2017年8月9日(星期三) 晚上10:08
收件人: "npm/npm"<npm@noreply.github.com>; 
抄送: "龙腾"<1242928090@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [npm/npm] The server can't start. (#18091)




Could you please show the scripts section of your package.json?
