### ISSUE TITLE
 I want to try an existing template, I'm having trouble doing npm start

### ISSUE THREAD

**Issue by jbrillabalu** [npm/npm#18106]
template :http://akveo.com/blur-admin/

i execute $npm start
and i have this error:
npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10

npm ERR! missing script: start

AND THIS npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.10.10
3 info using node@v6.11.2
4 verbose stack Error: missing script: start
4 verbose stack     at run (/usr/lib/node_modules/npm/lib/run-script.js:151:19)
4 verbose stack     at /usr/lib/node_modules/npm/lib/run-script.js:61:5
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:356:5
4 verbose stack     at checkBinReferences_ (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:320:45)
4 verbose stack     at final (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:354:3)
4 verbose stack     at then (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:124:5)
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:243:12
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
4 verbose stack     at tryToString (fs.js:456:3)
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:443:12)
5 verbose cwd /home/jibril/app/react-blur-admin-master
6 error Linux 4.4.0-31-generic
7 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
8 error node v6.11.2
9 error npm  v3.10.10
10 error missing script: start
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

thanks for help

**Comment by kenany** [comment]
Hello! So, the way `npm start` works is that it looks in your current `package.json` for a defined `"start"` [script](https://docs.npmjs.com/misc/scripts), and then runs that. The error message you're seeing is trying to tell you that you have not defined a `"start"` script in your `package.json`, hence `npm start` has no idea what you want it to do.

To solve this issue, all you have to do is add a new script to your `package.json`. It might look something like this, for example:

``` json
{
  "name": "package-name",
  "version": "1.0.0",
  "description": "package description",
  "scripts": {
    "start": "node --version",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {},
  "devDependencies": {}
}
```

Note how this `package.json` has a `"start"` script that runs `node --version`. You'll definitely want to change the command to whatever is most appropriate for your project.

Let me know if you run into any further `npm` issues :)

**Comment by jbrillabalu** [comment]
Hello! Thanks for helping me. iam sorry before iam a new on reactjs . I see what I suggest. But inside the package.json file I did not get scrip start. But I see there is an automatic folder that is made "dist". And the following are some of the code that is in package.json
{
  "name": "react-blur-admin",
  "version": "0.11.1",
  "description": "React Blur Admin - Styles And Components",
  "main": "dist",
  "scripts": {
    "clean": "rm -rf dist && mkdir dist && mkdir dist/assets && mkdir dist/assets/styles && mkdir dist/assets/fonts && mkdir dist/assets/img",
    "deploy": "npm run clean && npm run deployjs && npm run deploycss && npm run deployassets",
    "deployassets": "cp -R src/assets/fonts dist/assets && cp -R src/assets/img dist/assets",
    "deploycss": "node-sass -r src/assets/styles/app.scss dist/assets/styles/react-blur-admin.min.css && cp -R src/assets/styles/bootstrap/fonts/* dist/assets/fonts",
    "deployjs": "babel -d dist src",
    "lint": "node_modules/.bin/eslint --ext js src/",
    "prepublish": "npm run deploy",
    "preversion": "npm run lint && npm run test",
    "test": "NODE_ENV=test NODE_PATH=. ./node_modules/.bin/mocha test/.setup.js test --recursive"
  },
  "repository": {
    "type": "git",


Oh yaa. The previous time I took the template following the commands that I follow from 
https://github.com/knledg/react-webpack-skeleton intruction , becouse at
https://github.com/knledg/react-blur-admin does not include a command to start.

this is the firs time:
git clone https://github.com/knledg/react-blur-admin.git
cd your-project
rm -rf .git
git init && git remote add origin <sshUrl>
npm install
cp dev.env .env
make client

**Comment by Developer314** [comment]
Hi @jbrillabalu, @KenanY 

I have the same issue. I have tried to replace "start":"npm start" in scripts in package.json. But 
then I will got infinte looping in terminal. Did you find any solution for this ?

**Comment by kenany** [comment]
@jbrillabalu Yup, looks like you are going to have to write the `"start"` script yourself.

@Developer314 You are getting an infinite loop because `npm start` executes your `"start"` script, which you have defined as `"npm start"`. So `npm start` will call `npm start` which will call `npm start`... etc. There's your infinite loop :)
