### ISSUE TITLE
Clarify documentation for package-lock.json behaviour

### ISSUE THREAD

**Issue by jotaen** [npm/npm#18103]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?

[doc/files/npm-package-locks.md](https://github.com/npm/npm/blob/latest/doc/files/npm-package-locks.md) should be updated according to the changes introduced in npm 5.1.0 by means of #16866.

In that document it says:

> The presence of a package lock changes the installation behaviour such that:
> 1. The module tree described by the package lock is reproduced. This means reproducing the structure described in the file, using the specific files referenced in "resolved" if available, falling back to normal package resolution using "version" if one isn't.

This holds no longer true since npm 5.1.0, because now the generated module tree is a combined result of both `package.json` and `package-lock.json`. (Example: `package.json` specifies some package with version `^1.1.0`; `package-lock.json` had locked it with version `1.1.4`; but actually, the package is already available with version `1.1.9`. In this case `npm i` resolves the package to `1.1.9` and overwrites the lockfile accordingly, hence ignoring the information in the lock file.)

1. The documentation should be corrected and clarified, so that users can understand the behaviour of the lock file. (Maybe other places are affected as well, that I don’t know of.)
2. It would be helpful if the documentation would point out the preferred way to perform reproducible builds, as this is not obvious anymore. This is especially problematic, because there is already some confusion for people who are trying to achieve deterministic build behaviour, e.g. on CI platforms.

**Comment by thibaudcolas** [comment]
The documentation should also address how `optionalDependencies` can be resolved differently, not based on differences in version resolution, but of environment, overwriting the lockfile as well.

This is issue #17722, which I'll summarise as "fsevents is added to the lockfile when people install on OSX, and removed from the lockfile when people install on Linux".

**Comment by alextes** [comment]
@jotaen could you clarify your point 2. ? How is it not obvious anymore? Is there some way of producing a differing build where you don't change deps without `npm` and install from an identical `package.json` and package-lock pair?

**Comment by ajmath** [comment]
@alextes I just tested this with a git based dependency without any specific sha/tag listed.  Here is what I observed.

1. `npm i --save git+ssh://git@github.com:ajmath/npm-package-test.git` and package-lock.json is created with current master sha
2. Push commits to ajmath/npm-package-test
3. Run `npm i` on project from step 1 and observe that package-lock.json is changed.

In this case, the package.json and package-lock.json were identical and produced a different build based on the status of the remote dependency.  This is not the behavior I would expect given that package-lock.json lists a specific sha to the dependency.

What I would like to see in the documentation is how we can force the identical build that is defined in the package.json and package-lock.json files.

**Comment by jotaen** [comment]
@alextes At the time I created the issue (with npm 5.1), I only was able to reproduce a build in case I pinned my dependencies in `package.json` to the exact version. When I used fuzzy dependencies with `^` or `~` it ignored and skipped the “pinned” versions in the lock file. Hence, the documentation was not in sync with the actual behaviour and for me it was unclear what the lock file was even there for.

I just retried with npm 5.6.0 and it seems to work now as expected. From my side, I would consider the issue closed.

@ajmath As far as I remember you cannot lock git based dependencies, but I don’t know whether this still holds true.

**Comment by ajmath** [comment]
I guess what confused/alarmed me is that the package-lock.json has a
specific sha listed for the dependency.  The expected behavior for me in
that case would be to use the specific version listed in package-lock.json.

**Comment by stephan-v** [comment]
What's the fucking use of a lock file if you are just going to update it anyways because a `package.json` dependency can be updated to a newer version?

And please don't tell me I am suppose to remove the carets from my package.json otherwise I might as well consider that to be our new lock file.

**Comment by lowe0292** [comment]
According to https://github.com/npm/npm/issues/18095#issuecomment-321185513, the lock doesn't work for git-based dependencies unless you specify the commit/tag in package.json 😕
