### ISSUE TITLE
Npminstall vue error

### ISSUE THREAD

**Issue by ruancheng77** [npm/npm#18109]
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "vue"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8

npm ERR! shasum check failed for C:\Users\ThinkPad\AppData\Local\Temp\npm-2408-9
d835671\registry.npmjs.org\vue\-\vue-2.4.2.tgz
npm ERR! Expected: a9855261f191c978cc0dc1150531b8d08149b58c
npm ERR! Actual:   66140ea13a4ac139cdffb6fa65fff8cc137d3a7c
npm ERR! From:     https://registry.npmjs.org/vue/-/vue-2.4.2.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by zhuanli555** [comment]
meet the problem too
