### ISSUE TITLE
missing 

### ISSUE THREAD

**Issue by shiversamar** [npm/npm#18105]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by shiversamar** [comment]
[](url)

- 

- [ ] #

- [1. ](`

> url
![screen shot 2017-08-08 at 2 09 40 pm](https://user-images.githubusercontent.com/19742243/29094766-6426a108-7c43-11e7-8ea8-974e540e0bc1.png)


`)

**Comment by kenany** [comment]
@shiversamar What behavior are you expecting to see here?

**Comment by kenany** [comment]
Closing as abandoned.
