### ISSUE TITLE
Unexpected end of input at 1:18377

### ISSUE THREAD

**Issue by aladdin-add** [npm/npm#18116]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
npm i, (and npmc),enconuter error: 
```bash
npm ERR! Unexpected end of input at 1:18377
npm ERR! ">=0.2.0"},"_hasShrinkwrap":false,"publish_time":1337132037072},"0.8.
```
https://gist.github.com/Aladdin-ADD/9392f2118682114163f8c5f7c79d3905

### supporting information:

 - `npm -v` prints: 5.3.0
 - `npmc -v` prints: 5.3.0-canary.0
 - `node -v` prints: v8.2.1
 - `npm config get registry` prints:https://registry.npm.taobao.org/
 - Windows, OS X/macOS, or Linux?: OS X 10.11.6
 - Network issues:
   - Geographic location where npm was run:
   - [] I use a proxy to connect to the npm registry.
   - [x] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [x] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by aladdin-add** [comment]
is someone working on this? seems it is a bug also exists in `npmc@5.3.0-canary.0`. (I installed deps via yarn and it works well)

**Comment by johhansantana** [comment]
This is happening as well

![pasted image at 2017_10_23 03_03 pm](https://user-images.githubusercontent.com/9933887/31908707-3d2073fe-b7e4-11e7-8535-3d0cb9c90e23.png)

npm@5.3.0
node@8.7.0

started happening today without updating anything, just tried to create a new project via `ng new project-name` and it started giving me that error.

**Comment by BenjaminNjoroge** [comment]
this happens mostly due to poor internet connection
