### ISSUE TITLE
npm ERR! code UNABLE_TO_GET_ISSUER_CERT_LOCALLY

### ISSUE THREAD

**Issue by Starique** [npm/npm#18126]
Here is the log.

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\nodejs\\node.exe',
1 verbose cli   'C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--global',
1 verbose cli   '@bb-cli/bb-package',
1 verbose cli   '@bb-cli/bb-import',
1 verbose cli   '@bb-cli/bb-generate',
1 verbose cli   '@bb-cli/bb-serve',
1 verbose cli   '@bb-cli/bb-customize' ]
2 info using npm@3.10.10
3 info using node@v6.11.2
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData @bb-cli/bb-package
8 silly fetchPackageMetaData @bb-cli/bb-import
9 silly fetchPackageMetaData @bb-cli/bb-generate
10 silly fetchPackageMetaData @bb-cli/bb-serve
11 silly fetchPackageMetaData @bb-cli/bb-customize
12 silly fetchNamedPackageData @bb-cli/bb-package
13 silly mapToRegistry name @bb-cli/bb-package
14 silly mapToRegistry scope (from package name) @bb-cli
15 verbose mapToRegistry no registry URL found in name for scope @bb-cli
16 silly mapToRegistry using default registry
17 silly mapToRegistry registry https://registry.npmjs.org/
18 silly mapToRegistry data Result {
18 silly mapToRegistry   raw: '@bb-cli/bb-package',
18 silly mapToRegistry   scope: '@bb-cli',
18 silly mapToRegistry   escapedName: '@bb-cli%2fbb-package',
18 silly mapToRegistry   name: '@bb-cli/bb-package',
18 silly mapToRegistry   rawSpec: '',
18 silly mapToRegistry   spec: 'latest',
18 silly mapToRegistry   type: 'tag' }
19 silly mapToRegistry uri https://registry.npmjs.org/@bb-cli%2fbb-package
20 silly fetchNamedPackageData @bb-cli/bb-import
21 silly mapToRegistry name @bb-cli/bb-import
22 silly mapToRegistry scope (from package name) @bb-cli
23 verbose mapToRegistry no registry URL found in name for scope @bb-cli
24 silly mapToRegistry using default registry
25 silly mapToRegistry registry https://registry.npmjs.org/
26 silly mapToRegistry data Result {
26 silly mapToRegistry   raw: '@bb-cli/bb-import',
26 silly mapToRegistry   scope: '@bb-cli',
26 silly mapToRegistry   escapedName: '@bb-cli%2fbb-import',
26 silly mapToRegistry   name: '@bb-cli/bb-import',
26 silly mapToRegistry   rawSpec: '',
26 silly mapToRegistry   spec: 'latest',
26 silly mapToRegistry   type: 'tag' }
27 silly mapToRegistry uri https://registry.npmjs.org/@bb-cli%2fbb-import
28 silly fetchNamedPackageData @bb-cli/bb-generate
29 silly mapToRegistry name @bb-cli/bb-generate
30 silly mapToRegistry scope (from package name) @bb-cli
31 verbose mapToRegistry no registry URL found in name for scope @bb-cli
32 silly mapToRegistry using default registry
33 silly mapToRegistry registry https://registry.npmjs.org/
34 silly mapToRegistry data Result {
34 silly mapToRegistry   raw: '@bb-cli/bb-generate',
34 silly mapToRegistry   scope: '@bb-cli',
34 silly mapToRegistry   escapedName: '@bb-cli%2fbb-generate',
34 silly mapToRegistry   name: '@bb-cli/bb-generate',
34 silly mapToRegistry   rawSpec: '',
34 silly mapToRegistry   spec: 'latest',
34 silly mapToRegistry   type: 'tag' }
35 silly mapToRegistry uri https://registry.npmjs.org/@bb-cli%2fbb-generate
36 silly fetchNamedPackageData @bb-cli/bb-serve
37 silly mapToRegistry name @bb-cli/bb-serve
38 silly mapToRegistry scope (from package name) @bb-cli
39 verbose mapToRegistry no registry URL found in name for scope @bb-cli
40 silly mapToRegistry using default registry
41 silly mapToRegistry registry https://registry.npmjs.org/
42 silly mapToRegistry data Result {
42 silly mapToRegistry   raw: '@bb-cli/bb-serve',
42 silly mapToRegistry   scope: '@bb-cli',
42 silly mapToRegistry   escapedName: '@bb-cli%2fbb-serve',
42 silly mapToRegistry   name: '@bb-cli/bb-serve',
42 silly mapToRegistry   rawSpec: '',
42 silly mapToRegistry   spec: 'latest',
42 silly mapToRegistry   type: 'tag' }
43 silly mapToRegistry uri https://registry.npmjs.org/@bb-cli%2fbb-serve
44 silly fetchNamedPackageData @bb-cli/bb-customize
45 silly mapToRegistry name @bb-cli/bb-customize
46 silly mapToRegistry scope (from package name) @bb-cli
47 verbose mapToRegistry no registry URL found in name for scope @bb-cli
48 silly mapToRegistry using default registry
49 silly mapToRegistry registry https://registry.npmjs.org/
50 silly mapToRegistry data Result {
50 silly mapToRegistry   raw: '@bb-cli/bb-customize',
50 silly mapToRegistry   scope: '@bb-cli',
50 silly mapToRegistry   escapedName: '@bb-cli%2fbb-customize',
50 silly mapToRegistry   name: '@bb-cli/bb-customize',
50 silly mapToRegistry   rawSpec: '',
50 silly mapToRegistry   spec: 'latest',
50 silly mapToRegistry   type: 'tag' }
51 silly mapToRegistry uri https://registry.npmjs.org/@bb-cli%2fbb-customize
52 verbose request uri https://registry.npmjs.org/@bb-cli%2fbb-package
53 verbose request no auth needed
54 info attempt registry request try #1 at 4:56:17 PM
55 verbose request id 780b98c84b8f46c0
56 http request GET https://registry.npmjs.org/@bb-cli%2fbb-package
57 verbose request uri https://registry.npmjs.org/@bb-cli%2fbb-import
58 verbose request no auth needed
59 info attempt registry request try #1 at 4:56:17 PM
60 http request GET https://registry.npmjs.org/@bb-cli%2fbb-import
61 verbose request uri https://registry.npmjs.org/@bb-cli%2fbb-generate
62 verbose request no auth needed
63 info attempt registry request try #1 at 4:56:17 PM
64 http request GET https://registry.npmjs.org/@bb-cli%2fbb-generate
65 verbose request uri https://registry.npmjs.org/@bb-cli%2fbb-serve
66 verbose request no auth needed
67 info attempt registry request try #1 at 4:56:17 PM
68 http request GET https://registry.npmjs.org/@bb-cli%2fbb-serve
69 verbose request uri https://registry.npmjs.org/@bb-cli%2fbb-customize
70 verbose request no auth needed
71 info attempt registry request try #1 at 4:56:17 PM
72 http request GET https://registry.npmjs.org/@bb-cli%2fbb-customize
73 info retry will retry, error on last attempt: Error: unable to get local issuer certificate
74 info retry will retry, error on last attempt: Error: unable to get local issuer certificate
75 info retry will retry, error on last attempt: Error: unable to get local issuer certificate
76 info retry will retry, error on last attempt: Error: unable to get local issuer certificate
77 info retry will retry, error on last attempt: Error: unable to get local issuer certificate
78 info attempt registry request try #2 at 4:56:28 PM
79 http request GET https://registry.npmjs.org/@bb-cli%2fbb-serve
80 info attempt registry request try #2 at 4:56:28 PM
81 http request GET https://registry.npmjs.org/@bb-cli%2fbb-import
82 info attempt registry request try #2 at 4:56:28 PM
83 http request GET https://registry.npmjs.org/@bb-cli%2fbb-generate
84 info attempt registry request try #2 at 4:56:28 PM
85 http request GET https://registry.npmjs.org/@bb-cli%2fbb-package
86 info attempt registry request try #2 at 4:56:28 PM
87 http request GET https://registry.npmjs.org/@bb-cli%2fbb-customize
88 info retry will retry, error on last attempt: Error: unable to get local issuer certificate
89 info retry will retry, error on last attempt: Error: unable to get local issuer certificate
90 info retry will retry, error on last attempt: Error: unable to get local issuer certificate
91 info retry will retry, error on last attempt: Error: unable to get local issuer certificate
92 info retry will retry, error on last attempt: Error: unable to get local issuer certificate
93 info attempt registry request try #3 at 4:57:28 PM
94 http request GET https://registry.npmjs.org/@bb-cli%2fbb-generate
95 info attempt registry request try #3 at 4:57:28 PM
96 http request GET https://registry.npmjs.org/@bb-cli%2fbb-package
97 info attempt registry request try #3 at 4:57:28 PM
98 http request GET https://registry.npmjs.org/@bb-cli%2fbb-customize
99 info attempt registry request try #3 at 4:57:28 PM
100 http request GET https://registry.npmjs.org/@bb-cli%2fbb-serve
101 info attempt registry request try #3 at 4:57:28 PM
102 http request GET https://registry.npmjs.org/@bb-cli%2fbb-import
103 silly fetchPackageMetaData Error: unable to get local issuer certificate
103 silly fetchPackageMetaData     at Error (native)
103 silly fetchPackageMetaData     at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
103 silly fetchPackageMetaData     at emitNone (events.js:86:13)
103 silly fetchPackageMetaData     at TLSSocket.emit (events.js:185:7)
103 silly fetchPackageMetaData     at TLSSocket._finishInit (_tls_wrap.js:610:8)
103 silly fetchPackageMetaData     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)
103 silly fetchPackageMetaData  error for @bb-cli/bb-customize { Error: unable to get local issuer certificate
103 silly fetchPackageMetaData     at Error (native)
103 silly fetchPackageMetaData     at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
103 silly fetchPackageMetaData     at emitNone (events.js:86:13)
103 silly fetchPackageMetaData     at TLSSocket.emit (events.js:185:7)
103 silly fetchPackageMetaData     at TLSSocket._finishInit (_tls_wrap.js:610:8)
103 silly fetchPackageMetaData     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38) code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY' }
104 silly fetchPackageMetaData Error: unable to get local issuer certificate
104 silly fetchPackageMetaData     at Error (native)
104 silly fetchPackageMetaData     at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
104 silly fetchPackageMetaData     at emitNone (events.js:86:13)
104 silly fetchPackageMetaData     at TLSSocket.emit (events.js:185:7)
104 silly fetchPackageMetaData     at TLSSocket._finishInit (_tls_wrap.js:610:8)
104 silly fetchPackageMetaData     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)
104 silly fetchPackageMetaData  error for @bb-cli/bb-serve { Error: unable to get local issuer certificate
104 silly fetchPackageMetaData     at Error (native)
104 silly fetchPackageMetaData     at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
104 silly fetchPackageMetaData     at emitNone (events.js:86:13)
104 silly fetchPackageMetaData     at TLSSocket.emit (events.js:185:7)
104 silly fetchPackageMetaData     at TLSSocket._finishInit (_tls_wrap.js:610:8)
104 silly fetchPackageMetaData     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38) code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY' }
105 silly fetchPackageMetaData Error: unable to get local issuer certificate
105 silly fetchPackageMetaData     at Error (native)
105 silly fetchPackageMetaData     at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
105 silly fetchPackageMetaData     at emitNone (events.js:86:13)
105 silly fetchPackageMetaData     at TLSSocket.emit (events.js:185:7)
105 silly fetchPackageMetaData     at TLSSocket._finishInit (_tls_wrap.js:610:8)
105 silly fetchPackageMetaData     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)
105 silly fetchPackageMetaData  error for @bb-cli/bb-package { Error: unable to get local issuer certificate
105 silly fetchPackageMetaData     at Error (native)
105 silly fetchPackageMetaData     at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
105 silly fetchPackageMetaData     at emitNone (events.js:86:13)
105 silly fetchPackageMetaData     at TLSSocket.emit (events.js:185:7)
105 silly fetchPackageMetaData     at TLSSocket._finishInit (_tls_wrap.js:610:8)
105 silly fetchPackageMetaData     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38) code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY' }
106 silly fetchPackageMetaData Error: unable to get local issuer certificate
106 silly fetchPackageMetaData     at Error (native)
106 silly fetchPackageMetaData     at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
106 silly fetchPackageMetaData     at emitNone (events.js:86:13)
106 silly fetchPackageMetaData     at TLSSocket.emit (events.js:185:7)
106 silly fetchPackageMetaData     at TLSSocket._finishInit (_tls_wrap.js:610:8)
106 silly fetchPackageMetaData     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)
106 silly fetchPackageMetaData  error for @bb-cli/bb-import { Error: unable to get local issuer certificate
106 silly fetchPackageMetaData     at Error (native)
106 silly fetchPackageMetaData     at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
106 silly fetchPackageMetaData     at emitNone (events.js:86:13)
106 silly fetchPackageMetaData     at TLSSocket.emit (events.js:185:7)
106 silly fetchPackageMetaData     at TLSSocket._finishInit (_tls_wrap.js:610:8)
106 silly fetchPackageMetaData     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38) code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY' }
107 silly fetchPackageMetaData Error: unable to get local issuer certificate
107 silly fetchPackageMetaData     at Error (native)
107 silly fetchPackageMetaData     at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
107 silly fetchPackageMetaData     at emitNone (events.js:86:13)
107 silly fetchPackageMetaData     at TLSSocket.emit (events.js:185:7)
107 silly fetchPackageMetaData     at TLSSocket._finishInit (_tls_wrap.js:610:8)
107 silly fetchPackageMetaData     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)
107 silly fetchPackageMetaData  error for @bb-cli/bb-generate { Error: unable to get local issuer certificate
107 silly fetchPackageMetaData     at Error (native)
107 silly fetchPackageMetaData     at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
107 silly fetchPackageMetaData     at emitNone (events.js:86:13)
107 silly fetchPackageMetaData     at TLSSocket.emit (events.js:185:7)
107 silly fetchPackageMetaData     at TLSSocket._finishInit (_tls_wrap.js:610:8)
107 silly fetchPackageMetaData     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38) code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY' }
108 silly rollbackFailedOptional Starting
109 silly rollbackFailedOptional Finishing
110 silly runTopLevelLifecycles Finishing
111 silly install printInstalled
112 verbose stack Error: unable to get local issuer certificate
112 verbose stack     at Error (native)
112 verbose stack     at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
112 verbose stack     at emitNone (events.js:86:13)
112 verbose stack     at TLSSocket.emit (events.js:185:7)
112 verbose stack     at TLSSocket._finishInit (_tls_wrap.js:610:8)
112 verbose stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)
113 verbose cwd C:\Users\tsyed
114 error Windows_NT 6.1.7601
115 error argv "C:\\nodejs\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--global" "@bb-cli/bb-package" "@bb-cli/bb-import" "@bb-cli/bb-generate" "@bb-cli/bb-serve" "@bb-cli/bb-customize"
116 error node v6.11.2
117 error npm  v3.10.10
118 error code UNABLE_TO_GET_ISSUER_CERT_LOCALLY
119 error unable to get local issuer certificate
120 error If you need help, you may report this error at:
120 error     <https://github.com/npm/npm/issues>
121 verbose exit [ 1, true ]

**Comment by rupamroy** [comment]
`npm config set strict-ssl=false`
