### ISSUE TITLE
npm install getting fail

### ISSUE THREAD

**Issue by FatemaRangwala** [npm/npm#18123]
#### I'm opening this issue because:

  - [ ] npm is producing an incorrect install.
 
#### What's going wrong?
I have cloned a github project from the URL git clone https://github.com/angular/quickstart Demo.
After that on cmd prompt I did npm install and it is throwing error
![image](https://user-images.githubusercontent.com/13776336/29127417-a3b7e380-7d3e-11e7-8a65-7e8f6f21326f.png)

Attaching the screenshot of command prompt for reference.

**Comment by FatemaRangwala** [comment]
[npm-debug.txt](https://github.com/npm/npm/files/1211838/npm-debug.txt)

**Comment by beingbing** [comment]
use`sudo apt-get install npm`
and it will install npm to your default $path
