### ISSUE TITLE
NPM install fails

### ISSUE THREAD

**Issue by dhandapanirajeswaran** [npm/npm#18134]
I'm opening this issue because:
npm install fails only for a specific GIT repository giving this error log. can you please check and help.

[npm-debug.log.txt](https://github.com/npm/npm/files/1215296/npm-debug.log.txt)

things i tried but not success though:
- adding this in git config: git config --global url."https://".insteadOf git://
- it is successful for a different repository which i tried, but fails only in this case.

**Comment by parkjohnston** [comment]
Have seen this before...where you trying to pull a certain commit of the package?

Appears that the hash is for a merge.

Let me know if you were looking to pull just that and we can go from there!

**Comment by dhandapanirajeswaran** [comment]
Thanks for the reply!! I am trying to set up the project for the the first time. It's not any specific commit which i try to pull. It is the entire repo am trying to pull into my local machine where i am getting this NPM install fail issue.

**Comment by parkjohnston** [comment]
what is the install? 

Down to get this sorted out today!

**Comment by dhandapanirajeswaran** [comment]
you want the package.json which is installed via "npm install" command ? is it?
Following are the dependencies: "broccoli-asset-rev": "^2.4.5",
    "d3-textwrap": "^2.0.0",
    "ember-ajax": "^2.4.1",
    "ember-anchor": "0.1.8",
    "ember-async-button": "1.0.2",
    "ember-bootstrap": "0.11.3",
    "ember-bootstrap-changeset-validations": "0.1.1",
    "ember-bootstrap-switch": "1.13.4",
    "ember-browserify": "1.1.13",
    "ember-changeset": "1.2.3",
    "ember-changeset-validations": "1.2.6",
    "ember-cli": "2.11.1",
    "ember-cli-app-version": "^2.0.0",
    "ember-cli-babel": "^5.1.7",
    "ember-cli-bootstrap-datetimepicker": "0.4.1",
    "ember-cli-data-export": "roofstock/ember-cli-data-export#8e0d399f0c2e234174dbe087dd9aa7627e01ca13",
    "ember-cli-dependency-checker": "^1.3.0",
    "ember-cli-document-title": "0.3.3",
    "ember-cli-htmlbars": "^1.1.1",
    "ember-cli-htmlbars-inline-precompile": "^0.3.6",
    "ember-cli-inject-live-reload": "^1.4.1",
    "ember-cli-jshint": "^2.0.1",
    "ember-cli-moment-shim": "^3.0.1",
    "ember-cli-numeral": "0.2.0",
    "ember-cli-qunit": "^3.0.1",
    "ember-cli-release": "^0.2.9",
    "ember-cli-sass": "6.1.1",
    "ember-cli-shims": "^1.0.2",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-star-rating": "0.5.0",
    "ember-cli-test-loader": "^1.1.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-composable-helpers": "2.0.0",
    "ember-d3": "0.3.0",
    "ember-data": "^2.11.0",
    "ember-debug-logger": "0.3.1",
    "ember-deferred-content": "0.2.0",
    "ember-export-application-global": "^1.0.5",
    "ember-file-upload": "2.0.0-beta.37",
    "ember-hammertime": "1.1.2",
    "ember-load-initializers": "^0.6.0",
    "ember-moment": "7.3.0",
    "ember-power-select": "1.6.1",
    "ember-promise-helpers": "1.0.2",
    "ember-radio-button": "1.1.1",
    "ember-resize": "0.0.17",
    "ember-resolver": "^2.0.3",
    "ember-simple-auth": "1.2.0",
    "ember-source": "~2.11.0",
    "ember-truth-helpers": "1.3.0",
    "ember-uuid": "1.0.0",
    "ember-wormhole": "0.5.1",
    "eonasdan-bootstrap-datetimepicker-npm": "^4.17.42",
    "liquid-fire": "0.27.2",
    "loader.js": "^4.0.10",
    "moment": "^2.18.1",
    "moment-timezone": "^0.5.13"

**Comment by dhandapanirajeswaran** [comment]
Interestingly, similar npm install works fine for different git hub repo. I attached npm failure log too.

**Comment by parkjohnston** [comment]
I see that the error is from the single branch that is referenced.  Starting to wonder if it is a bug in the merge, but now working with the provided package.json, will let you know what I am finding!

**Comment by parkjohnston** [comment]
"broccoli-asset-rev": "^2.4.5",
"d3-textwrap": "^2.0.0",
"ember-ajax": "^2.4.1",
"ember-anchor": "0.1.8",
"ember-async-button": "1.0.2",
"ember-bootstrap": "0.11.3",
"ember-bootstrap-changeset-validations": "0.1.1",
"ember-bootstrap-switch": "1.13.4",
"ember-browserify": "1.1.13",
"ember-changeset": "1.2.3",
"ember-changeset-validations": "1.2.6",
"ember-cli": "2.11.1",
"ember-cli-app-version": "^2.0.0",
"ember-cli-babel": "^5.1.7",
"ember-cli-bootstrap-datetimepicker": "0.4.1",
"ember-cli-dependency-checker": "^1.3.0",
"ember-cli-document-title": "0.3.3",
"ember-cli-htmlbars": "^1.1.1",
"ember-cli-htmlbars-inline-precompile": "^0.3.6",
"ember-cli-inject-live-reload": "^1.4.1",
"ember-cli-jshint": "^2.0.1",
"ember-cli-moment-shim": "^3.0.1",
"ember-cli-numeral": "0.2.0",
"ember-cli-qunit": "^3.0.1",
"ember-cli-release": "^0.2.9",
"ember-cli-sass": "6.1.1",
"ember-cli-shims": "^1.0.2",
"ember-cli-sri": "^2.1.0",
"ember-cli-star-rating": "0.5.0",
"ember-cli-test-loader": "^1.1.0",
"ember-cli-uglify": "^1.2.0",
"ember-composable-helpers": "2.0.0",
"ember-d3": "0.3.0",
"ember-data": "^2.11.0",
"ember-debug-logger": "0.3.1",
"ember-deferred-content": "0.2.0",
"ember-export-application-global": "^1.0.5",
"ember-file-upload": "2.0.0-beta.37",
"ember-hammertime": "1.1.2",
"ember-load-initializers": "^0.6.0",
"ember-moment": "7.3.0",
"ember-power-select": "1.6.1",
"ember-promise-helpers": "1.0.2",
"ember-radio-button": "1.1.1",
"ember-resize": "0.0.17",
"ember-resolver": "^2.0.3",
"ember-simple-auth": "1.2.0",
"ember-source": "~2.11.0",
"ember-truth-helpers": "1.3.0",
"ember-uuid": "1.0.0",
"ember-wormhole": "0.5.1",
"eonasdan-bootstrap-datetimepicker-npm": "^4.17.42",
"liquid-fire": "0.27.2",
"loader.js": "^4.0.10",
"moment": "^2.18.1",
"moment-timezone": "^0.5.13",
    "ember-cli-data-export": "github:roofstock/ember-cli-data-export#8e0d399f0c2e234174dbe087dd9aa7627e01ca13"

**Comment by parkjohnston** [comment]
try that and let me know!

**Comment by dhandapanirajeswaran** [comment]
[package.json.txt](https://github.com/npm/npm/files/1231056/package.json.txt)
Updated the Package.Json with the above dependencies, still not able to do NPM INSTALL.
[npm-debug.txt](https://github.com/npm/npm/files/1231055/npm-debug.txt)

**Comment by dhandapanirajeswaran** [comment]
In case if it's useful, I use following command in .npmrc file inside this folder --- C:\Users\\{Username}\ 
---------------------Cmd-----------------------------------------------
https-proxy=http://Uname:Pwd@servername/
proxy=http://Uname:Pwd@servername/
prefix=C:\Users\\{UserName}\AppData\Roaming\npm

**Comment by parkjohnston** [comment]
I know that you need that dependency, but try to remove the one referencing
git and lets start with getting the others to work and see if more may be
an issue while i read the logs!

**Comment by dhandapanirajeswaran** [comment]
yeah. It started progressing without error . thanks.. Let you know if it ends up well. As you mentioned, if you can check why it fails if it's referring github.

**Comment by parkjohnston** [comment]
working through it now...that package is just not released properly...that
is terrible practice to have a release based on a commit.   Still working
through a fix for you :)
