### ISSUE TITLE
/Users/jiangyuzhen/.npm/_logs/2017-08-11T13_09_21_563Z-debug.log

### ISSUE THREAD

**Issue by jiangyuzhen** [npm/npm#18142]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

#

**Comment by jiangyuzhen** [comment]
/Users/jiangyuzhen/.npm/_logs/2017-08-11T13_09_21_563Z-debug.log

**Comment by kenany** [comment]
@jiangyuzhen Could you upload the debug log to <https://gist.github.com/> and post the link to it here? Also, please fill out the form in your original post as well. Thanks!

**Comment by kenany** [comment]
Closing as abandoned.
