### ISSUE TITLE
Error Starting a new Ionic 2 project in Node js 6.11.2 

### ISSUE THREAD

**Issue by jaynil96** [npm/npm#18151]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Error creating a new Ionic 2 project in Node js 6.11.2 
#### How can the CLI team reproduce the problem?
This issue could be reproduced by starting up Node.js 6.11.2 and trying to start a new ionic-angular project using the line
ionic start name tabs --types=ionic-angular

### supporting information:

 - `npm -v` prints: 'npm-v' is not recognized as an internal or external command,
operable program or batch file.
 - `node -v` prints: 'node-v' is not recognized as an internal or external command,
operable program or batch file.
 - `npm config get registry` prints:  https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows 10
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by strugee** [comment]
@jaynil96 `npm -v`, not `npm-v` (note the space). Ditto for Node; `node -v` instead of `node-v`
