### ISSUE TITLE
npm ERR! Cannot find module 'ansi'

### ISSUE THREAD

**Issue by Aareon** [npm/npm#18153]
#### I'm opening this issue because:

  - [ X ] npm is producing an incorrect install.
  - [ X ] npm is doing something I don't understand.

#### What's going wrong?

```
npm ERR! Linux 4.4.0-91-generic
npm ERR! argv "/usr/local/n/versions/node/8.2.1/bin/node" "/usr/bin/npm" "i" "-g" "npm"
npm ERR! node v8.2.1
npm ERR! npm  v3.5.2
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'ansi'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/bin/npm-debug.log
```

#### How can the CLI team reproduce the problem?

Not entirely sure how you would go about reproducing this sort of thing.

### supporting information:

 - `npm -v` prints: `3.5.2`
 - `node -v` prints: `v8.2.1`
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?: `Linux, Ubuntu 16.04.3 LTS`
 - Unlikely a network issue
 - No container

**Comment by devpaul** [comment]
I'm seeing similar on travis and using a dockerfile:

```
FROM node:6

RUN npm i -g npm@4 && \
    npm i -g grunt-cli 
```

Seeing random failures like:

```
Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/unsupported.js:2:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by cyntss** [comment]
any solution to this? Im having the same problem when running ```npm install```

**Comment by LuoZijun** [comment]
@cyntss reinstall :D

**Comment by Aareon** [comment]
Reinstall confirmed works. My issue originally arose when I accidentally installed 2 versions of npm. 1 version was correct, the other was broken. In the process of installing the 2nd, my symlinks were broken.

**Comment by stevinus73** [comment]
I am trying Meteor to install: meteor npm install --save react
``

**Comment by stevinus73** [comment]
will no bug but standard install have bugs to cause this error. I only installed NPM of one versions but the 2nd package (`ansi`) is broken.
