### ISSUE TITLE
Ionic start has an error

### ISSUE THREAD

**Issue by GS-Sharon** [npm/npm#18159]
![image](https://user-images.githubusercontent.com/30534202/29277264-b947c234-8143-11e7-8afa-71b8686fff63.png)

I input "ionic start shoppingMall tabs" in cmd, and the problem here is shown above, please help me to check how should I do,thaks a lot....

**Comment by vovikdrg** [comment]
Try to downgrade node to 6

**Comment by GS-Sharon** [comment]
Thank you so much，it work，by the way，this directory is ionic2? Is not the same as ionic1,er...I am a greenhand,do not know much about ionic...
![image](https://user-images.githubusercontent.com/30534202/29280908-9302b01e-814f-11e7-85ef-fd73d2b7c0d1.png)

**Comment by strugee** [comment]
@GS-Sharon sounds like your issue's solved? If so you should probably close this issue.
