### ISSUE TITLE
Oraclejet project 

### ISSUE THREAD

**Issue by praveen44u** [npm/npm#18150]
when I am executing below command, I am getting below error. Kindly help to resolve

E:\>yo oraclejet firstproject --template=navdrawer
? ==========================================================================
? ==========================================================================
We're constantly looking for ways to make yo better!
May we anonymously report usage statistics to improve the tool over time?
More info: https://github.com/yeoman/insight & http://yeoman.io
========================================================================== Yes
Processing template... navdrawer
Oracle JET: Your app structure is generated. Continuing with library install...
Performing npm install may take a bit...
Invoking npm install
npm ERR! Windows_NT 6.1.7600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10

npm ERR! shasum check failed for C:\Users\USER\AppData\Local\Temp\npm-6112-ebfda
651\registry.npmjs.org\oraclejet\-\oraclejet-3.1.0.tgz
npm ERR! Expected: 5eae5e35f55ce562b63b67841baf5faf6287a9ea
npm ERR! Actual:   e6edd69f7cab54c3ba231ab6d2ff243defe65861
npm ERR! From:     https://registry.npmjs.org/oraclejet/-/oraclejet-3.1.0.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     E:\firstproject\npm-debug.log
Error oraclejet firstproject --template=navdrawer

Oracle JET Error: (during Invoking npm install) 1

**Comment by strugee** [comment]
@praveen44u please edit your issue to use code formatting; it makes everything much easier to read.

As for your problem, try just deleting the `oraclejet-3.1.0.tgz` file that npm mentions. Also you should upgrade your npm with `npm install -g npm@latest`
