### ISSUE TITLE
error cb() never called!

### ISSUE THREAD

**Issue by djverlinden** [npm/npm#18157]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?

running : npm update -g

415 http 200 https://registry.npmjs.org/npm
416 verbose headers { server: 'nginx/1.10.1',
416 verbose headers   'content-type': 'application/json',
416 verbose headers   'last-modified': 'Fri, 14 Jul 2017 05:18:23 GMT',
416 verbose headers   etag: 'W/"5968541f-659cf6"',
416 verbose headers   'content-encoding': 'gzip',
416 verbose headers   'cache-control': 'max-age=300',
416 verbose headers   'content-length': '547178',
416 verbose headers   'accept-ranges': 'bytes',
416 verbose headers   date: 'Mon, 14 Aug 2017 13:35:53 GMT',
416 verbose headers   via: '1.1 varnish',
416 verbose headers   age: '122',
416 verbose headers   connection: 'keep-alive',
416 verbose headers   'x-served-by': 'cache-ams4135-AMS',
416 verbose headers   'x-cache': 'HIT',
416 verbose headers   'x-cache-hits': '1',
416 verbose headers   'x-timer': 'S1502717753.149309,VS0,VE1',
416 verbose headers   vary: 'Accept-Encoding, Accept' }
417 http fetch GET 200 http://latest.yeti.cx/ 1631ms
418 silly prefetch yeti@http://latest.yeti.cx done in 1653ms
419 error cb() never called!
420 error This is an error with npm itself. Please report this error at:
421 error <https://github.com/npm/npm/issues>

### supporting information:

 - `npm -v` prints: 5.3.0
 - `node -v` prints: v8.3.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - macOS: macOS
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by majg0** [comment]
Just ran a couple of `npm i`s, one of them told me this;
```
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

It gave no other information.

node `v8.4.0`
npm `5.3.0`
macOS Sierra Version 10.12.6 (16G29)

Hardware Overview:
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro13,3
  Processor Name:	Intel Core i7
  Processor Speed:	2.7 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	8 MB
  Memory:	16 GB
