### ISSUE TITLE
npm error while Installing Angular

### ISSUE THREAD

**Issue by SachinSingh20** [npm/npm#18167]
this is output What i'm getting

C:\Users\Sachin Singh> npm install -g @angular/cli
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code SELF_SIGNED_CERT_IN_CHAIN

npm ERR! self signed certificate in certificate chain
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Sachin Singh\npm-debug.log

**Comment by gmoiseyenkov** [comment]
Have same issue - what should i do?
[npm-debug.log.txt](https://github.com/npm/npm/files/1239570/npm-debug.log.txt)
