### ISSUE TITLE
npm Install  taking much time

### ISSUE THREAD

**Issue by AjayRajkumar** [npm/npm#18173]
While try to install the npm dependancy  in the windows its taking too much up time is there any way to speed up , i checked my network connection its fine .

**Comment by DenysVuika** [comment]
Npm 5.3.0 seems to be completely broken and unusable as couple of previus versions.  Running npm install completely freezes machines. If you can't migrate to "yarn" and stop this madness with performance I suggest installing the latest working version:

```
sudo npm install -g npm@5.0.4
```

**Comment by AjayRajkumar** [comment]
Thanks bro i tried yarn its super compare with npm it saved lot of development time.
