### ISSUE TITLE
npm install is not working 

### ISSUE THREAD

**Issue by sandext12** [npm/npm#18177]
Hi ,

I am not able to install ant module through npm install.  Getting below error for all install operations. I remember i did some config changes 2-3 days ago and that could be the the reason. I set the registry by following command.

> npm config set registry "http://registry.npmjs.org/"

I found on internet and that solved my  problem that time but this came up as a side effect. Please help.

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "D:\\ProgramFiles\\nodejsv6\\node.exe" "D:\\ProgramFiles\\nodejsv6\\node_modules\\npm\\bin\\npm-cli.js" "install" "emailjs" "-save"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! syscall getaddrinfo

npm ERR! getaddrinfo EAI_AGAIN registry.npmjs.org:80
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Work\myapp\npm-debug.log

[npm-debug.zip](https://github.com/npm/npm/files/1227233/npm-debug.zip)

**Comment by salmanwaheed** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mkdirenv@gmail.com
    Domain salmanwaheed.info has exceeded the max emails per hour (185/150 (123%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193]:49171 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by box1177.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1e7wjs-000ndh-33
	for hello@salmanwaheed.info; Thu, 26 Oct 2017 22:59:24 -0600
Date: Thu, 26 Oct 2017 21:59:13 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1509080353;
	bh=DNDUrfmYu3FDVIjToqnqksGhejXi9CLzSizqA6LVpAM=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=izkdHJGI5RE2Sl6ojLcwsU2Bt6Q1kBMIaKEPQW5zfs7zBx+y3k4/vlToD3tclKxpM
	 LdI9xWj1v1dvHGv80K9Az+m+ZpPUvA0ZnLB8py70kc9GX//eb386kxBcguEiosBfg0
	 4n2ojV83Wjs3War0u7UgMR/Kzux4y6sRJ9Og9Z1M=
