### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by pkmuz1** [npm/npm#18182]
please help me i can't able to install npm in kali linux

when i hit command - npm install
bash: npm: command not found

please help if you can
thnks

**Comment by ruchernchong** [comment]
Issue has nothing related to this. Go and visit npm official site for the guide to install.

**Comment by pkmuz1** [comment]
can you give me  the link and instruction

**Comment by evansantos** [comment]
@pkmuz1 is node installed in your machine? 
Could checking doing this `node -v`

**Comment by pkmuz1** [comment]
problem solved.. thnks
