### ISSUE TITLE
not able to install loopback and sails js fw

### ISSUE THREAD

**Issue by bsatheesh** [npm/npm#18187]
#### I'm opening this issue because:

  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.

#### What's going wrong?
tired the following commands  but not able to complete: 
npm install sails -g
npm install -g loopback-cli

#### How can the CLI team reproduce the problem?
run thei above commands in windows 10 . 

### supporting information:
attached npm log 

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by salmanwaheed** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mkdirenv@gmail.com
    Domain salmanwaheed.info has exceeded the max emails per hour (183/150 (122%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext6.iad.github.net ([192.30.252.197]:37736 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by box1177.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1e7wj1-000nQE-G2
	for hello@salmanwaheed.info; Thu, 26 Oct 2017 22:58:32 -0600
Date: Thu, 26 Oct 2017 21:58:20 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1509080300;
	bh=zXN8bf6EIDCpVYh0vFXPn+InQqSNIGEoOGfxLFSIu6I=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=aefFYyi1a5duCEX4eL/09ErfIIMh4WajKvjZfjFwmlf0Boh+EZmF9FnCnbW+q/mPS
	 a+KZzFtUgtn8I11IksHNXx1xRZMwLONB9c1XimM9aPXqWb9Rj1FnRUdaClkj+iDqw7
	 cSvekc/Y0wu1pz7r8hx53cyk4e8zJlOrZ1Y9QWpE=

**Comment by salmanwaheed** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mkdirenv@gmail.com
    Domain salmanwaheed.info has exceeded the max emails per hour (184/150 (122%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext6.iad.github.net ([192.30.252.197]:41265 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by box1177.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1e7wjH-000nTc-1e
	for hello@salmanwaheed.info; Thu, 26 Oct 2017 22:58:47 -0600
Date: Thu, 26 Oct 2017 21:58:36 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1509080316;
	bh=Nrw8VCjn90LbDEhcYhIoAk0QeTRpNhARAuoiZZKTUg8=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=cBBEisXZmhDL8IEIZ95jF7kAkfWdDvWHBeHqqlx8IJQFqUWy3gAPzkAHLaTvyrNw+
	 6JUMaMw307xcoBbqsCAMjBfaKzyJjl8s7xHLD3c1Lk0TmXEFmhujgbSb4jhbZyGl7n
	 7b9tQnUaS65027+ngb278vtrugC9FoSGwAltxL0U=
