### ISSUE TITLE
Followed all steps for installation.. 4 days now and still can't code

### ISSUE THREAD

**Issue by TheAwesomeGuy** [npm/npm#18189]
So I had to uninstall all my npm, android and java stuff on Sunday, cause my app didn't want to build. After reinstalling node.js, java sdk and android sdk, I tried running the npm install g- cordova command and keep getting errors.. Here is the error.

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'g-',
1 verbose cli   'cordova' ]
2 info using npm@5.3.0
3 info using node@v8.3.0
4 verbose config Skipping project config: C:\Users\Marshunt/.npmrc. (matches userconfig)
5 verbose npm-session ccfef824875ff378
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 http fetch GET 200 https://registry.npmjs.org/cordova 42ms (from cache)
9 silly pacote tag manifest for cordova@latest fetched in 54ms
10 http fetch GET 404 https://registry.npmjs.org/g- 3113ms
11 silly fetchPackageMetaData error for g-@latest 404 Not Found: g-@latest
12 verbose stack Error: 404 Not Found: g-@latest
12 verbose stack     at fetch.then.res (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:41:19)
12 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
12 verbose stack     at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
12 verbose stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
12 verbose stack     at Promise._settlePromise0 (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
12 verbose stack     at Promise._settlePromises (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
12 verbose stack     at Async._drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
12 verbose stack     at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
12 verbose stack     at Immediate.Async.drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
12 verbose stack     at runCallback (timers.js:781:20)
12 verbose stack     at tryOnImmediate (timers.js:743:5)
12 verbose stack     at processImmediate [as _immediateCallback] (timers.js:714:5)
13 verbose cwd C:\Users\Marshunt
14 verbose Windows_NT 6.3.9600
15 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "g-" "cordova"
16 verbose node v8.3.0
17 verbose npm  v5.3.0
18 error code E404
19 error 404 Not Found: g-@latest
20 verbose exit [ 1, true ]

Any help please?

**Comment by TheAwesomeGuy** [comment]
I also tried setting the registry to what some other people said on the other issues, as well as tried to install g-@latest, but nothing works

**Comment by sheepsteak** [comment]
@TheAwesomeGuy try this instead `npm install -g cordova`. You put `g-` instead of `-g` so npm is trying to install a module called `g-` first 😄 

More info here: https://docs.npmjs.com/getting-started/installing-npm-packages-globally

**Comment by TheAwesomeGuy** [comment]
Lol I think I might have typed wrong on the forum, but thanks, let me try it quick

**Comment by TheAwesomeGuy** [comment]
I also did an npm install npm@latest -g

After that I tried npm install -g cordova.. Seems to be doing something now

**Comment by TheAwesomeGuy** [comment]
Okay seems to be working? Maybe.. Will try to build my app quick

**Comment by TheAwesomeGuy** [comment]
Okay so when I try to run my build with cordova build android --release, then command promt says cordova is not recognized as an internal or external command?

**Comment by TheAwesomeGuy** [comment]
Ohhhhhh..... I am an idiot..........
LMAO

**Comment by TheAwesomeGuy** [comment]
No.. Didn't work.. I tried running command prompt as admin, but still doesn't recognize cordova as an command

**Comment by kenany** [comment]
I'm assuming you want to move this to the new ticket you opened (https://github.com/npm/npm/issues/18191).

**Comment by TheAwesomeGuy** [comment]
Yes

**Comment by TheAwesomeGuy** [comment]
But the new one has been closed and no one is really replying on anything?

**Comment by kenany** [comment]
I closed your new one (https://github.com/npm/npm/issues/18214) since you already had https://github.com/npm/npm/issues/18191 open. There's no need to open more tickets when you already have one open :)
