### ISSUE TITLE
npm ERR! arg Argument starts with non-ascii dash, this is probably invalid: [ '–production' ]

### ISSUE THREAD

**Issue by AnythingLinux** [npm/npm#18194]
root@Explorer:~/explorer# npm install –production
npm ERR! arg Argument starts with non-ascii dash, this is probably invalid: [ '–production' ]
Unhandled rejection Error: Invalid tag name "–production": Tags may not have any characters that encodeURIComponent encodes.roduction' ]
    at invalidTagName (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:76:15)
    at fromRegistry (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:265:13)
    at resolve (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:66:12)
    at npa (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:39:10)
    at /usr/local/lib/node_modules/npm/lib/install/deps.js:200:16
    at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
    at Array.forEach (<anonymous>)
    at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
    at exports.getAllMetadata (/usr/local/lib/node_modules/npm/lib/install/deps.js:199:3)
    at Installer.loadArgMetadata (/usr/local/lib/node_modules/npm/lib/install.js:325:3)
    at /usr/local/lib/node_modules/npm/lib/install.js:656:16
    at BB.join.then (/usr/local/lib/node_modules/npm/lib/install/read-shrinkwrap.js:41:16)
    at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-08-16T22_21_53_801Z-debug.log

#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by salmanwaheed** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mkdirenv@gmail.com
    Domain salmanwaheed.info has exceeded the max emails per hour (178/150 (118%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext7.iad.github.net ([192.30.252.198]:43336 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by box1177.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1e7wiK-000mzU-Dq
	for hello@salmanwaheed.info; Thu, 26 Oct 2017 22:57:48 -0600
Date: Thu, 26 Oct 2017 21:57:37 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1509080257;
	bh=Cu5BaVww/qxqeHMcQ7/KnyfWQwbp8qrVj6aSNj+BUk0=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=y6Fq2sDvkEKcfuBOz4IzUcdqkhnhzVyYnv8tvOIhG+xBBbzkcXnmapT14EPZHugS3
	 8mQhkTE8T9Cd1FU2B9IHbWQuM11wcvul+IWoy9KCwiqhS1wbLfNg/wm+XfaEiyQ8FJ
	 Po6PQ8KZVvIDkSdK4mE1ya2hAvdgdNN0MFPCZPkQ=

**Comment by salmanwaheed** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mkdirenv@gmail.com
    Domain salmanwaheed.info has exceeded the max emails per hour (182/150 (121%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext6.iad.github.net ([192.30.252.197]:36344 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by box1177.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1e7wiv-000nNF-VW
	for hello@salmanwaheed.info; Thu, 26 Oct 2017 22:58:26 -0600
Date: Thu, 26 Oct 2017 21:58:15 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1509080295;
	bh=elNINhXAPGC+tMbDQyCajZvdff4IUBZwJUoVOkPXius=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=RhGevd2KbHsSbVJONyDNg4Q4Q74x0jzBW1bXYWOHauvyRWDSYc0coVzOBOukQZgsZ
	 lvDGyHKVBgTZVs4GGEdmqz+kqv/W6h3xc/Qq66p7Xykb7gVFCyIsSl4jA810yue1O1
	 EFm+4fWQLn6q+52XeuDoRlQ5wFoXj7Pp8kXZRFW8=
