### ISSUE TITLE
npm install connect fails ...

### ISSUE THREAD

**Issue by keeseok1993** [npm/npm#18193]
I've tried to download npm install connect and its not working. None of the modules are able to download.
It seems like it stops at normalizetree. Could anyone please help me...

C:\Program Files (x86)\nodejs\node_modules\npm>npm install connect
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x8
6)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "connect"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code SELF_SIGNED_CERT_IN_CHAIN

npm ERR! self signed certificate in certificate chain
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Program Files (x86)\nodejs\node_modules\npm\npm-debug.log

This is what I get ...

**Comment by kenany** [comment]
@keeseok1993 I'm gonna close this one in favor of https://github.com/npm/npm/issues/18195.
