### ISSUE TITLE
Retire SHA1

### ISSUE THREAD

**Issue by casey** [npm/npm#18197]
#### What's the feature?

NPM should use SHA2 or SHA3 instead of SHA1 for integrity. It can first be added client side by having the client calculate a SHA2 or SHA3 hash locally, and storing that alongside the SHA1 returned by the registry. The client can then verify both the SHA1 and the SHA2/3 hash of the files it receives from the registry against the package.lock file.

#### What problem is the feature intended to solve?

Although an attack is probably a long way off, an attacker might be able to trick a client into accepting a package with malicious code.

#### Is the absence of this feature blocking you or your team? If so, how?

No, jus' makes me nervous.

#### Is this feature similar to an existing feature in another tool?

Yes, cargo, for example, uses SHA2-256.

#### Is this a feature you're prepared to implement, with support from the npm CLI team?

No.

**Comment by kenany** [comment]
Previously: https://github.com/npm/npm/issues/4938

**Comment by casey** [comment]
Ah, sorry for not seeing that. I'd still like to see SHA1 retired, but I guess it's already been discussed and closed.
