### ISSUE TITLE
Cordova is Messed Up AF

### ISSUE THREAD

**Issue by TheAwesomeGuy** [npm/npm#18191]
One problem after another... Trying to update my android platform, but now it says my C:\Windows\system32\npm is not recognized an an internal or external command

**Comment by TheAwesomeGuy** [comment]
![image](https://user-images.githubusercontent.com/12281741/29380080-d04a9952-82c4-11e7-84ed-e0d7786fadce.png)

**Comment by TheAwesomeGuy** [comment]
I really don't get how or where this error comes from? And I can't even run cordova requirements

**Comment by TheAwesomeGuy** [comment]
Np.. The problem got solved.

**Comment by RobinWilhelm** [comment]
How did you manage to solve this? I have the exact same issue.

**Comment by TheAwesomeGuy** [comment]
There was an npm file inside of the windows folder, no idea how it got there, but after I deleted it, everything worked again

**Comment by RobinWilhelm** [comment]
Thank you, that solved it for me as well.

**Comment by TheAwesomeGuy** [comment]
Np :)

**Comment by Binitronics** [comment]
Deleting the npm file solves my problem. Many thanks
