### ISSUE TITLE
NPM install error

### ISSUE THREAD

**Issue by keeseok1993** [npm/npm#18195]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [@ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
can't perform -> npm install connect
### supporting information:

 - `npm -v` prints:  3.10.10
 - `node -v` prints: v.6.11.2
 - `npm config get registry` prints:  https:://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.npmjs
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [@ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by keeseok1993** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'connect' ]
2 info using npm@3.10.10
3 info using node@v6.11.2
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData connect
8 silly fetchNamedPackageData connect
9 silly mapToRegistry name connect
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'connect',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'connect',
12 silly mapToRegistry   name: 'connect',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/connect
14 verbose request uri https://registry.npmjs.org/connect
15 verbose request no auth needed
16 info attempt registry request try #1 at 3:20:23 PM
17 verbose request id c79c17f36487325c
18 http request GET https://registry.npmjs.org/connect
19 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
20 info attempt registry request try #2 at 3:20:33 PM
21 http request GET https://registry.npmjs.org/connect
22 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
23 info attempt registry request try #3 at 3:21:33 PM
24 http request GET https://registry.npmjs.org/connect
25 silly fetchPackageMetaData Error: self signed certificate in certificate chain
25 silly fetchPackageMetaData     at Error (native)
25 silly fetchPackageMetaData     at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
25 silly fetchPackageMetaData     at emitNone (events.js:86:13)
25 silly fetchPackageMetaData     at TLSSocket.emit (events.js:185:7)
25 silly fetchPackageMetaData     at TLSSocket._finishInit (_tls_wrap.js:610:8)
25 silly fetchPackageMetaData     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)
25 silly fetchPackageMetaData  error for connect { Error: self signed certificate in certificate chain
25 silly fetchPackageMetaData     at Error (native)
25 silly fetchPackageMetaData     at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
25 silly fetchPackageMetaData     at emitNone (events.js:86:13)
25 silly fetchPackageMetaData     at TLSSocket.emit (events.js:185:7)
25 silly fetchPackageMetaData     at TLSSocket._finishInit (_tls_wrap.js:610:8)
25 silly fetchPackageMetaData     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38) code: 'SELF_SIGNED_CERT_IN_CHAIN' }
26 silly rollbackFailedOptional Starting
27 silly rollbackFailedOptional Finishing
28 silly runTopLevelLifecycles Finishing
29 silly install printInstalled
30 verbose stack Error: self signed certificate in certificate chain
30 verbose stack     at Error (native)
30 verbose stack     at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
30 verbose stack     at emitNone (events.js:86:13)
30 verbose stack     at TLSSocket.emit (events.js:185:7)
30 verbose stack     at TLSSocket._finishInit (_tls_wrap.js:610:8)
30 verbose stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)
31 verbose cwd C:\Program Files (x86)\nodejs\node_modules\npm
32 error Windows_NT 6.1.7601
33 error argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "connect"
34 error node v6.11.2
35 error npm  v3.10.10
36 error code SELF_SIGNED_CERT_IN_CHAIN
37 error self signed certificate in certificate chain
38 error If you need help, you may report this error at:
38 error     <https://github.com/npm/npm/issues>
39 verbose exit [ 1, true ]

**Comment by keeseok1993** [comment]
Anyone please???

**Comment by Aravindharigoppula** [comment]
@keeseok1993 Were you able to resolve this? I do not see resolution on any of the linked issues. I'm facing exactly the same issue. 
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "inst
all"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code SELF_SIGNED_CERT_IN_CHAIN

npm ERR! self signed certificate in certificate chain

**Comment by keeseok1993** [comment]
No no one has helped me yet....

**Comment by Butterfly** [comment]
Hi.. This is coming from a newbie who uses search engines a lot. :smile: I found several things that may or may not help. PLEASE RESEARCH their effect before you try them. Two of the 3 are very similar so that's why I say please research what each would do if you try them.

1. Comment on #7519 [ERR! self signed certificate in certificate chain](https://github.com/npm/npm/issues/7519#issuecomment-295762964) suggests `npm config set strict-ssl false`

2. Comment on #6916 [SELF_SIGNED_CERT_IN_CHAIN error and npm config set strict-ssl=false v0.10.33](https://github.com/npm/npm/issues/6916#issuecomment-66862911) suggests `npm config set ca=null`. Ok, I can see what happened there. That person already had suggestion 1 set properly so this second command was suggested in addition to that first one.`

3. A secondary comment at #6916 was to run `npm config ls`. The person reporting the issue was able to self-solve after running that command because it showed him that his system wide proxy was somehow causing the issue.

4. This topic was also over at StackOverflow ~6 years ago. The suggestion then was to upgrade `npm` if possible.

Hope that helps somehow :smile:

**Comment by keeseok1993** [comment]
@Butterfly Oh my gosh.. it's working I thank you so much!

**Comment by salmanwaheed** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mkdirenv@gmail.com
    Domain salmanwaheed.info has exceeded the max emails per hour (179/150 (119%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext4.iad.github.net ([192.30.252.195]:48569 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by box1177.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1e7wiZ-000n2s-Cc
	for hello@salmanwaheed.info; Thu, 26 Oct 2017 22:58:03 -0600
Date: Thu, 26 Oct 2017 21:57:52 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1509080272;
	bh=zxhAeKAnXQxCYPC+ra+XhfZDnSf+Q7LPxRus/mCNTBc=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=qIodIa4WHervQU9b03Q8uyvtdj/Z0Y7TTzqACGMOALZ7zQykshvvBx/mGIKoD63EK
	 xFsR4tlhIHzD5JzUD7hG7EKpXEMu8R3OxC7yjBBGnO1V0SI+vm+SZDSZ5K+3GGjunX
	 9GmzFqGxkjklq3ELgBNRoLSBA6UcHj/13tFB8QKA=

**Comment by salmanwaheed** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mkdirenv@gmail.com
    Domain salmanwaheed.info has exceeded the max emails per hour (180/150 (120%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext6.iad.github.net ([192.30.252.197]:33688 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by box1177.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1e7wij-000n8w-Ko
	for hello@salmanwaheed.info; Thu, 26 Oct 2017 22:58:14 -0600
Date: Thu, 26 Oct 2017 21:58:02 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1509080282;
	bh=97k2IZfZ2apHnvbREhINkZcjFnRo9rUMdJK6OlW6FLE=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=xGqiCYP/xLg7GB82mPUMc5nyQwf8x2dGPV24YKOLIJqhbqOrj+18Q5ywhp9vO5V2r
	 u+emD+lPmg/K+ptQuC+6LmGVZqQsJiovuApLnNBK+IF48RlFXo1S0GRGq80WdGaglw
	 6VcwSGvDxP8DxOA2d4JDHwRLX0jp2f2SFr3e1qJk=
