### ISSUE TITLE
install appim with cmd-"npm install -g appium", but failed

### ISSUE THREAD

**Issue by neopf** [npm/npm#18199]
#### I'm opening this issue because:

  - [ ] npm is doing something I don't understand.
  

#### What's going wrong?
I'm trying to install appium using npm with the command : npm install -g appium
I'm receiving the following error after the execution of above command.

C:\Users>npm install -g appium@1.6
npm ERR! code Z_BUF_ERROR
npm ERR! errno -5
npm ERR! unexpected end of file

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\speng\AppData\Roaming\npm-cache\_logs\2017-08-17T02_38_38_688Z-debug.log

with debug.log info:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'appium' ]
2 info using npm@5.3.0
3 info using node@v8.3.0
4 verbose npm-session 844ea043cee4c154
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 304 https://registry.npmjs.org/appium 14503ms (from cache)
8 http fetch GET 200 https://registry.npmjs.org/appium/-/appium-1.6.5.tgz 13ms (from cache)
9 silly fetchPackageMetaData error for appium@latest unexpected end of file
10 verbose stack Error: unexpected end of file
10 verbose stack     at Gunzip.zlibOnError (zlib.js:152:15)
11 verbose cwd C:\Users\speng
12 verbose Windows_NT 10.0.15063
13 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "appium"
14 verbose node v8.3.0
15 verbose npm  v5.3.0
16 error code Z_BUF_ERROR
17 error errno -5
18 error unexpected end of file
19 verbose exit [ -5, true ]

### supporting information:

 - `npm -v` prints: 5.3.0
 - `node -v` prints: 8.3.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows10-64bits
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the web.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by salmanwaheed** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mkdirenv@gmail.com
    Domain salmanwaheed.info has exceeded the max emails per hour (176/150 (117%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext4.iad.github.net ([192.30.252.195]:40410 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by box1177.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1e7wiA-000mxV-Sw
	for hello@salmanwaheed.info; Thu, 26 Oct 2017 22:57:39 -0600
Date: Thu, 26 Oct 2017 21:57:28 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1509080248;
	bh=aJWeUYpxbVGTDmKZZ7VYDmQoZ+l3uOxALkwNrraBcTY=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=o4XXhLsbVlwrvgHHj18gHr++aWXjk4IKpDxfdVqQ55BkySRztKfSTpNv/ir3OSAba
	 V27puq/1wTLSjSF8CyFYE6vpUV+Yr2hBrXnZjjzKtfxlep4yRm/v39cLx+XqzNmwah
	 /PNoJtjOivkyjGVdTNXUllBiCZKJMJuYIOjwVkLE=
