### ISSUE TITLE
npm auto remove my other packages when install a package

### ISSUE THREAD

**Issue by NextZeus** [npm/npm#18206]
#### I'm opening this issue because:
  - [ ] npm is doing something I don't understand.

#### What's going wrong?
when i install timekeeper , npm auto remove my local 4 packages from node_modules:

async-listener
emitter-listener
shimmer
tingyun

~ » node -v                                                    
v8.0.0
------------------------------------------------------------
~ » npm -v                                                     
5.0.0

**Comment by kenany** [comment]
Duplicate of https://github.com/npm/npm/issues/16853.
