### ISSUE TITLE
npm i node-notifier [sha checksum issue]

### ISSUE THREAD

**Issue by aravind25dec** [npm/npm#18205]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [x] npm is producing an incorrect install.
 
#### What's going wrong?
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "node.exe" "node\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-notifier"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0

npm ERR! shasum check failed for node\npm-13660-c68db237\registry.npmjs.org\node-notifier\-\node-notifier-5.1.2.tgz
npm ERR! Expected: 2fa9e12605fa10009d44549d6fcd8a63dde0e4ff
npm ERR! Actual:   c7c30792c0c854695d59b9bedd257ad938866035
npm ERR! From:     http://registry.npmjs.org/node-notifier/-/node-notifier-5.1.2.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by salmanwaheed** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mkdirenv@gmail.com
    Domain salmanwaheed.info has exceeded the max emails per hour (172/150 (114%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:37915 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by box1177.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1e7whB-000mg1-NP
	for hello@salmanwaheed.info; Thu, 26 Oct 2017 22:56:38 -0600
Date: Thu, 26 Oct 2017 21:56:25 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1509080185;
	bh=CvZPt/zYi0epJivxwrqYwHMCk5FEzTkVV2lnWAqpHT0=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=WyFBLu2b2StfZp535gSZzq7EwWULGmL0y1cebWrpJknAaaySYbhNiMv1Qzhwxm/Qo
	 EoWo07SLovN09ybWgqW/shs+f3ekJPxOv945/PLEgDV0YkhVhoEi1AzTc00BbQS3PL
	 2LYPs3lRtD8Sjwq8dlZqXj0szNxZUqX3vZC9C4cc=

**Comment by salmanwaheed** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mkdirenv@gmail.com
    Domain salmanwaheed.info has exceeded the max emails per hour (174/150 (115%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext5.iad.github.net ([192.30.252.196]:58382 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by box1177.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1e7whV-000mlR-A9
	for hello@salmanwaheed.info; Thu, 26 Oct 2017 22:56:57 -0600
Date: Thu, 26 Oct 2017 21:56:43 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1509080203;
	bh=DBWgY6GMxnWBWuJL+mfGNxRAjzOk+VQSaVtai5y3lVk=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=c2ERHe/BkEmF9YOmEhgw/w940uwL1QEjBvzSEAEq3sCm9uix51KV4PzEM+Br26wqy
	 m6oPBZ87+SwiwjM0Z5XgKrDiVOQqIbBR3W6YpWqDUKRRUlp2SAbcVBEozrcgZJVTOm
	 0NSrUoV4XDOEUFX3iAo+WSdpsVf9aD1EHsdR+DG0=
