### ISSUE TITLE
The command **npm team create <scope:team>** is not working.

### ISSUE THREAD

**Issue by ghost** [npm/npm#18204]
The command **npm team create \<scope:team\>** is not working.
Attempt:
`npm team create @myScope:myTeam`
Result:
`team name is required`
Attempt:
`npm team create "@myScope:myTeam"`
Result:
```
pm ERR! code E404
npm ERR! 404 Not Found : -/org/%40myScope/team
```

Also, according to this docs: https://www.npmjs.com/docs/orgs/managing-teams.html
After redirecting to URL: https://www.npmjs.com/org/org_name/teams it shows me this:
https://www.npmjs.com/static/images/not-found.png
wtf really? :/

**Comment by salmanwaheed** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mkdirenv@gmail.com
    Domain salmanwaheed.info has exceeded the max emails per hour (173/150 (115%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext6.iad.github.net ([192.30.252.197]:38436 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by box1177.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1e7whC-000mhS-TY
	for hello@salmanwaheed.info; Thu, 26 Oct 2017 22:56:39 -0600
Date: Thu, 26 Oct 2017 21:56:28 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1509080188;
	bh=PV8mebocY3FG/JbzOWDADFYvyZBLXRrewO/QTz48BnY=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=orBN/qu/mgpiWciGvMPvDTVEUgS6em6MIeqbwznLP0v2Bc3/aUx8PecAtC4d2ElzA
	 CidnO0EZCg+nVxNAzwyvpIr1K4ic57Y82JCey0YmgjRgF1PUZjyp3E0P77QtpYEpqN
	 X8jz9g6pHWk3PorRKqBFBmMf++9coUzq97mEYyJ4=
