### ISSUE TITLE
Only getting errors for a couple of things.

### ISSUE THREAD

**Issue by chronostbe** [npm/npm#18217]
![error 1](https://user-images.githubusercontent.com/17601993/29436595-48d96262-837a-11e7-8244-8fa846f06076.JPG)
![error 2](https://user-images.githubusercontent.com/17601993/29436601-4e68f88c-837a-11e7-8ede-7c9058bab94b.JPG)
I've tried everything I can think of I don't know what I'm doing wrong.

**Comment by kenany** [comment]
Sorry, but Node.js 0.10 and `npm@1.3` are years old and are no longer supported.
