### ISSUE TITLE
Npm gets 502 when installing phantomjs

### ISSUE THREAD

**Issue by pcsgithubid** [npm/npm#18210]
Hi. from jenkins i am trying to install node modules but i get below error when it was installing phantomjs.

node  8.2.1 

Considering PhantomJS found at /usr/bin/phantomjs
13:53:54 Found PhantomJS at /usr/bin/phantomjs ...verifying
13:53:55 PhantomJS detected, but wrong version 1.9.8 @ /usr/bin/phantomjs.
13:53:55 Downloading http://cnpmjs.org/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
13:53:55 Saving to /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
13:53:55 Receiving...
13:53:56 
13:53:56 Error requesting archive.
13:53:56 Status: 502
13:53:56 Request options: {
13:53:56   "uri": "http://cnpmjs.org/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2",
13:53:56   "encoding": null,
13:53:56   "followRedirect": true,
13:53:56   "headers": {
13:53:56     "User-Agent": "npm/5.3.0 node/v8.2.1 linux x64"
13:53:56   },
13:53:56   "strictSSL": false,
13:53:56 }
13:53:56 Response headers: {
13:53:56   "server": "nginx/1.4.6 (Ubuntu)",
13:53:56   "date": "Thu, 17 Aug 2017 17:57:17 GMT",
13:53:56   "content-type": "text/html",
13:53:56   "content-length": "181",
13:53:56   "connection": "close"
13:53:56 }
13:53:56 Make sure your network and proxy settings are correct.
13:53:56

**Comment by Rajik** [comment]
+1 
Facing the same issue!

**Comment by salmanwaheed** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mkdirenv@gmail.com
    Domain salmanwaheed.info has exceeded the max emails per hour (171/150 (113%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:37600 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by box1177.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1e7wh9-000mfH-4f
	for hello@salmanwaheed.info; Thu, 26 Oct 2017 22:56:35 -0600
Date: Thu, 26 Oct 2017 21:56:23 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1509080183;
	bh=mJeqAXpNxFFoNOmUHttN0D5V53e7KtPUMounVG0bR2s=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=jaklXC7kGynRRqN/syZ5hy6VRkbOmxUiYdnbgPAZp+uVSRs3lFeW6FL90WGM1auwc
	 HeJur8nN01FneSMb4hClWYMzcX3NEwNntzaaq41P/VTy+n+EheriI8JHIfCBEZnhIT
	 KvxlwKr2zfKKJYROmCuXuDquA7JTRaT4iuZ+YJzI=
