### ISSUE TITLE
npm install integrity checksum failed

### ISSUE THREAD

**Issue by stefan0s** [npm/npm#18211]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [X ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I have installed on OS X/macOS Sierra through homebrew latest node 8.4.0 and npm 5.3.0
I am getting error trying to install any package using npm install PACKAGE:
sha1-xxxxxxx integrity checksum failed when using sha1-xxxxxx but got sha1-yyyyy 

I also getting same error trying install Atom new packages. I have also tried to downgrade npm from 5 to latest 4 but i also get the same error. I can downgrade with success in earlier 5 versions like 5.0.1

**Comment by stefan0s** [comment]
Error: sha1-FDQt0428yU0OW4fXY81jYSwOeU8= integrity checksum failed when using sha1: wanted sha1-FDQt0428yU0OW4fXY81jYSwOeU8= but got sha1-yp3bEzDMb1IsQUvp5RVuuyqhK+M=. (5175 bytes)
    at Transform.on (/usr/local/lib/node_modules/npm/node_modules/ssri/index.js:275:19)
    at emitNone (events.js:110:20)
    at Transform.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
WARN pacote cached data for art@https://registry.npmjs.org/art/-/art-0.10.1.tgz (sha1-OFQYg+OZIlxeGT/yRujxV897IUY=) seems to be corrupted. Refreshing cache.
events.js:182░░░░░░⸩ ⠋ extract: sill extract babel-jest@18.0.0
      throw er; // Unhandled 'error' event

**Comment by stefan0s** [comment]
Error: sha1-DzuiFRn1Z9jCJaAAdtX6ipnNASg= integrity checksum failed when using sha1: wanted sha1-DzuiFRn1Z9jCJaAAdtX6ipnNASg= but got sha1-KTdsVPz9V9/UUY2t14ez3yIzceQ=. (7889 bytes)
    at Transform.on (/usr/local/lib/node_modules/npm/node_modules/ssri/index.js:275:19)
    at emitNone (events.js:110:20)
    at Transform.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)





npm ERR! code EINTEGRITY
npm ERR! sha1-x57Zf380y48robyXkLzDZkdLS3k= integrity checksum failed when using sha1: wanted sha1-x57Zf380y48robyXkLzDZkdLS3k= but got sha1-br06vA0zf57ABoayKoxkskTwkZM=. (8111 bytes)

**Comment by salmanwaheed** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mkdirenv@gmail.com
    Domain salmanwaheed.info has exceeded the max emails per hour (170/150 (113%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:36350 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by box1177.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1e7wh2-000md3-1u
	for hello@salmanwaheed.info; Thu, 26 Oct 2017 22:56:28 -0600
Date: Thu, 26 Oct 2017 21:56:16 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1509080176;
	bh=aBM6CxsLPhx10UVBsM4KMKvPxSdtgYCQ6Ev+7st4HZU=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=TRFOEoXMVM0if5v6gOM5dXGarE7JzEGQOUWmM5SS5cUaU7BBN6H/wrPQCBGh889my
	 abMhnAjpaEZxr4CiJFIfADAi7i2YduURUqSTu3pfjzn7GV9GVtaYegSB8cN/yrSdvV
	 1zhYsFktqx5Pi8mmsR3adRCjO9cz5ZzxcDahyeWs=
