### ISSUE TITLE
err

### ISSUE THREAD

**Issue by zgLiuBing** [npm/npm#18223]
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "npm"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10

npm ERR! shasum check failed for C:\Users\刘兵\AppData\Local\Temp\npm-8652-54d30cfd\registry.npmjs.org\npm\-\npm-5.3.0.tgz
npm ERR! Expected: e2ae85ef09d53f7f570a05578692899bf7879f17
npm ERR! Actual:   10c8aa1ec8f6ddd0303708ee6350b355248409e4
npm ERR! From:     https://registry.npmjs.org/npm/-/npm-5.3.0.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by zgLiuBing** [comment]
求解决

**Comment by salmanwaheed** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mkdirenv@gmail.com
    Domain salmanwaheed.info has exceeded the max emails per hour (168/150 (112%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:52971 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by box1177.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1e7wfl-000mF6-9T
	for hello@salmanwaheed.info; Thu, 26 Oct 2017 22:55:09 -0600
Date: Thu, 26 Oct 2017 21:54:58 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1509080098;
	bh=mYrfPF37pGpbIcUjHHB6BVMb2JwKK2fMit0xPNNrFWg=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=Nxmp5aZe0qj21oC+V4oIkYucqDQsdqf0tJYQVdbU8jj4GOSOXO9w71QwMgAJQAXn4
	 N7Y9CaqaE32386UOIGwf9vM2bPvpS/m2vTmWCXEmIVwQ8XjXEytzoy2KV5rC+568WI
	 KSys+teePReBLyJmRkBKl0TZdikamuAH6p9RKLYk=

**Comment by salmanwaheed** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mkdirenv@gmail.com
    Domain salmanwaheed.info has exceeded the max emails per hour (169/150 (112%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:36056 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by box1177.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1e7wgz-000mbU-HA
	for hello@salmanwaheed.info; Thu, 26 Oct 2017 22:56:25 -0600
Date: Thu, 26 Oct 2017 21:56:14 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1509080174;
	bh=Rb7uawGUr0N4ynOWkADccMKeyJW02ZJAKHe/+Teo8bY=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=G+gu7uXedTJ+qvx189LH363Lr7GifCXW/HpDBKTXk0sr+bG/pE0iCxPEZ3CS1rKnc
	 qghokDF9MhHst/sk6QYic7NvYOMdTB/v3F25qr5ImKgND3C+qXIzjtQQqjtitPZXWS
	 vQHLdP+3bH0Sq9wZMH35hgRTKth5WW7GJl3U2kjU=
