### ISSUE TITLE
Webpack can't be installed, I don't know why. Windows 10 system

### ISSUE THREAD

**Issue by daoqing99** [npm/npm#18222]
![111](https://user-images.githubusercontent.com/13798416/29446352-5bf814e8-841e-11e7-99b9-1a1c830b1ff7.png)

#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
@daoqing99 Ensure that the `"name"` field in your `package.json` is not set to `"webpack"`. Make it something more unique!

**Comment by kenany** [comment]
Closing as abandoned.
