### ISSUE TITLE
Error installing dependencies for laravel 5.4

### ISSUE THREAD

**Issue by Pabloledesma** [npm/npm#18220]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! Linux 4.4.0-66-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! path ../acorn/bin/acorn
npm ERR! code EPROTO
npm ERR! errno -71
npm ERR! syscall symlink

npm ERR! EPROTO: protocol error, symlink '../acorn/bin/acorn' -> '/home/vagrant/homestead/forum/node_modules/.bin/acorn'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/homestead/forum/npm-debug.log

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
@Pabloledesma Does this also occur with the `--no-bin-links` flag?

**Comment by kenany** [comment]
Closing as abandoned.

**Comment by AndrzejKrupinski** [comment]
Hi,
Sad that this one is closed.
I got this error now while tried install npm in the Laravel 5.4 project ran on HOMESTEAD vagrant package on Win 10. The default configurated environment produces problems and this is really annoying.
The problem occured with:
- `npm -v: 3.10.10`
- `node -v: 6.11.2` (upgrade to 7.3.0 changed nothing)

This is terrible:

[npm-debug.txt](https://github.com/npm/npm/files/1308608/npm-debug.txt)

**Comment by kenany** [comment]
@AndrzejKrupinski  FWIW, `npm@3` is no longer supported. Regardless, did you try my suggestion above?

EDIT: wrong mention, sorry!

**Comment by AndrzejKrupinski** [comment]
@KenanY  thanks! I haven't even noticed that `npm@3` is not supported (thought that the most recent homestead contains current lts packages). After getting access by `sudo chown -R vagrant:$(id -gn vagrant) /home/vagrant/.config` and using `--no-bin-links` it worked.

**Comment by FernandoRosaSequeira** [comment]
Hello!
I'm also stucked on this. I'm also trying to run 
>npm install
in a Laravel project (following a Laracasts.com tutorial), like @AndrzejKrupinski I'm running in Homestead, 
already updated to last node.js version.
>node -v
 v9.0.0

>npm -v
 5.5.1

>npm config list
[...]
bin-links = false
[...]

>sudo chown -R vagrant:$(id -gn vagrant) /home/vagrant/.config
>sudo chmod -R 777 /home/vagrant/.config
>sudo npm install --no-bin-links

However, at the end there is always an error:
"
32016 verbose unlock done using /home/vagrant/.npm/_locks/staging-c52e4b25a50ec796.lock for /home/vagrant/code/teenpower/node_modules/.staging
32017 verbose stack Error: EPERM: operation not permitted, scandir '/home/vagrant/code/teenpower/node_modules/fsevents/node_modules'
32018 verbose cwd /home/vagrant/code/teenpower
32019 verbose Linux 4.4.0-92-generic
32020 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--no-bin-links"
32021 verbose node v9.0.0
32022 verbose npm  v5.5.1
32023 error path /home/vagrant/code/teenpower/node_modules/fsevents/node_modules
32024 error code EPERM
32025 error errno -1
32026 error syscall scandir
32027 error Error: EPERM: operation not permitted, scandir '/home/vagrant/code/teenpower/node_modules/fsevents/node_modules'
32027 error  { Error: EPERM: operation not permitted, scandir '/home/vagrant/code/teenpower/node_modules/fsevents/node_modules'
32027 error   stack: 'Error: EPERM: operation not permitted, scandir \'/home/vagrant/code/teenpower/node_modules/fsevents/node_modules\'',
32027 error   errno: -1,
32027 error   code: 'EPERM',
32027 error   syscall: 'scandir',
32027 error   path: '/home/vagrant/code/teenpower/node_modules/fsevents/node_modules' }
32028 error Please try running this command again as root/Administrator.
32029 verbose exit [ -1, true ]
"
I'm running a Windows Power Shell as Administrator and there I connect to the virtual machine
>vagrant ssh
Once there, I ran with "sudo".
Is it possible "to be" more Administrator as this? What am I missing?

Thanks in advance!

![laravel_erro_npm_20171110_1503](https://user-images.githubusercontent.com/15786695/32665437-23ff7680-c62c-11e7-8039-840d9d19280e.PNG)
[2017-11-10T15_03_41_979Z-debug.log](https://github.com/npm/npm/files/1461820/2017-11-10T15_03_41_979Z-debug.log)

**Comment by FernandoRosaSequeira** [comment]
In a 2nd trial, a different error:
[2017-11-10T16_30_23_922Z-debug.log](https://github.com/npm/npm/files/1462040/2017-11-10T16_30_23_922Z-debug.log)
![laravel_erro_npm_20171110_1630](https://user-images.githubusercontent.com/15786695/32668989-03890708-c637-11e7-845b-a798955663cd.PNG)
