### ISSUE TITLE
npm ERR! tar.unpack error reading C:\Users\hujie2\appium npm ERR! addLocal Could not install C:\Users\hujie2\appium npm ERR! Windows_NT 10.0.10240 npm ERR! argv "D:\\Program Files\\software(goal)\\node.js\\node.exe" "D:\\Program Files\\software(goal)\\node.js\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "appium" npm ERR! node v6.11.2 npm ERR! npm  v3.10.10  npm ERR! 0-byte tarball npm ERR! Please run `npm cache clean` npm ERR! npm ERR! If you need help, you may report this error at: npm ERR!     <https://github.com/npm/npm/issues>  npm ERR! Please include the following file with any support request: npm ERR!     C:\Users\hujie2\npm-debug.log

### ISSUE THREAD

**Issue by AliceHuJie0218** [npm/npm#18236]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
Closing since the support form is not filled out.
