### ISSUE TITLE
Plugin error on run watch

### ISSUE THREAD

**Issue by robertblackmon** [npm/npm#18232]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [X] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

On npm run watch I receive this:
[npm-debug.txt](https://github.com/npm/npm/files/1235763/npm-debug.txt)

npm ERR! Invalid name: "bostondv/ultimate-posts-widget"

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [x ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
@robertblackmon Is the `"name"` property in your `package.json` set to `"bostondv/ultimate-posts-widget"`? If so, could you try changing it to `"@bostondv/ultimate-posts-widget"`?

**Comment by kenany** [comment]
Closing as abandoned.
