### ISSUE TITLE
npm login FAILS, returned 401 for PUT

### ISSUE THREAD

**Issue by leduong** [npm/npm#18239]
#### I'm opening this issue because:

  - [ ] npm is can't login, returned 401 for PUT on https://registry.npmjs.org/-/user/org.couchdb.user:

![screenshot from 2017-08-20 09-15-56](https://user-images.githubusercontent.com/1042749/29491754-8b20d3a0-858f-11e7-814c-11bb64bdbfea.png)

**Comment by salmanwaheed** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mkdirenv@gmail.com
    Domain salmanwaheed.info has exceeded the max emails per hour (162/150 (108%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:42011 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by box1177.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1e7wej-000lxJ-Gl
	for hello@salmanwaheed.info; Thu, 26 Oct 2017 22:54:05 -0600
Date: Thu, 26 Oct 2017 21:53:54 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1509080034;
	bh=7zE4NMuhY96DtWISWaNVdxlbVz/QjwrIOZfIwJiMi20=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=z4IMfBc9Sy2cgsmImR5S0PKko/kJQHGXG8OJRw28u7DB/2K8C6DSeaDBXtQRAlTfy
	 VYaD/mVB3xmr+5NexNm148lS6+sYgw/xylSFwIN3HRUWdZNEvA6IO3D1ODDpGIUjWW
	 tTlXedQuWbby+tAh47YufuuBbAjL5RktuU8VNl1Y=
