### ISSUE TITLE
Error installing; npm install -g  @angular/cli

### ISSUE THREAD

**Issue by Demch** [npm/npm#18234]
version: OS windows 7 x64

![29397483-158ec7b2-82e4-11e7-99ee-077b45fd6210](https://user-images.githubusercontent.com/3207363/29482146-438bb9c2-8451-11e7-983e-c7136d946a8f.png)

Den@Den-PC MINGW64 ~
$ npm install -g @angular/cli
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: forever-agent@0.6.1 (node_modules@angular\cli\node_modules\forever-agent):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sha1-+8cfDEGt6zf5bFd60e1C2P2sypE= integrity checksum failed when using sha1: wanted sha1-+8cfDEGt6zf5bFd60e1C2P2sypE= but got sha1-B1PDQmVCmInusCOdC1QgZljvs5Q=. (2237 bytes)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: es6-set@0.1.5 (node_modules@angular\cli\node_modules\es6-set):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sha1-0rPsXU2ADO2BjbU40ol02wpzzLE= integrity checksum failed when using sha1: wanted sha1-0rPsXU2ADO2BjbU40ol02wpzzLE= but got sha1-2jmj7l5rSw0yVb/vlWAYkK/YBwk=. (0 bytes)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: get-stream@3.0.0 (node_modules@angular\cli\node_modules\get-stream):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, utime 'C:\Users\Den\AppData\Roaming\npm\node_modules.staging\get-stream-52f781b0\readme.md'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: flatten@1.0.2 (node_modules@angular\cli\node_modules\flatten):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sha1-2uRqnXj74lKSJYzB54CkHZXAN4I= integrity checksum failed when using sha1: wanted sha1-2uRqnXj74lKSJYzB54CkHZXAN4I= but got sha1-2jmj7l5rSw0yVb/vlWAYkK/YBwk=. (0 bytes)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: browserify-zlib@0.1.4 (node_modules@angular\cli\node_modules\browserify-zlib):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, utime 'C:\Users\Den\AppData\Roaming\npm\node_modules.staging\browserify-zlib-0ce9c37a\src\binding.js'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fast-deep-equal@1.0.0 (node_modules@angular\cli\node_modules\fast-deep-equal):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sha1-liVqO8l1WV6zbYLpkp0GDYk0Of8= integrity checksum failed when using sha1: wanted sha1-liVqO8l1WV6zbYLpkp0GDYk0Of8= but got sha1-Y0GX1GVyZBCu8lekygqApgUjY4U=. (2237 bytes)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: coa@1.0.4 (node_modules@angular\cli\node_modules\coa):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, utime 'C:\Users\Den\AppData\Roaming\npm\node_modules.staging\coa-4e929f95\README.md'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-forge@0.6.33 (node_modules@angular\cli\node_modules\node-forge):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sha1-RjgRh59XPUUVWtap9D3ClujoXrw= integrity checksum failed when using sha1: wanted sha1-RjgRh59XPUUVWtap9D3ClujoXrw= but got sha1-NQqNJAsTf/U1RjwE0ll4CHY+U5s=. (7753 bytes)

npm ERR! code EINTEGRITY
npm ERR! sha1-0eJkOzipTXWDtHkGDmxK/8lAcfg= integrity checksum failed when using sha1: wanted sha1-0eJkOzipTXWDtHkGDmxK/8lAcfg= but got sha1-N3PsNwYPg148UT877muvA7NrxfU=. (2238 bytes)

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\Den\AppData\Roaming\npm-cache_logs\2017-08-17T05_28_13_567Z-debug.log

Den@Den-PC MINGW64 ~
$ node -v
v8.4.0

Den@Den-PC MINGW64 ~
$ npm -v
5.3.0

Den@Den-PC MINGW64 ~
$ ng new app
bash: ng: command not found

I did 'npm cache clean --force' and 'npm cache verify' then 'npm install' the issue is still and nothing

help me please

**Comment by Demch** [comment]
I did 'npm cache clean --force' and 'npm cache verify' then 'npm install' the issue is still and nothing

**Comment by salmanwaheed** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mkdirenv@gmail.com
    Domain salmanwaheed.info has exceeded the max emails per hour (161/150 (107%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:41696 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by box1177.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1e7weh-000lx1-Dv
	for hello@salmanwaheed.info; Thu, 26 Oct 2017 22:54:03 -0600
Date: Thu, 26 Oct 2017 21:53:52 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1509080032;
	bh=ydKmI/4UxUop70cKYKxTRLu59I8bsPkePvTtw92DBII=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=I+blETEXnzOjt+OBICPnVMhWBaJsYQxgCtfxnxjUv0LTUZwGJxTSUpTNbzlrd89B4
	 oxp4q8bGPR7cMnHgOUbydtMQjfELkXJEhWMbxGLlzn0oDN9+afjU/Ui0a7xO6O+Iod
	 7Rjzw7Zaz9B5Pu3AdXruHfl0OhLklhqQmD+XQF/I=

**Comment by Dongle74** [comment]
Is this problem solved?  Can if you can explain it.
