### ISSUE TITLE
npm ERR! Error: ENOENT,

### ISSUE THREAD

**Issue by y0913011011** [npm/npm#18248]
#### I'm opening this issue because:.
  - [ ] Other (_see below for feature requests_):
#### What's going wrong?
lchw@vm:lora-app-server$ npm start
npm ERR! Error: ENOENT, open '/home/lchw/gowork/src/github.com/brocaar/lora-app-server/package.json'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.4.0-92-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /home/lchw/gowork/src/github.com/brocaar/lora-app-server
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /home/lchw/gowork/src/github.com/brocaar/lora-app-server/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/lchw/gowork/src/github.com/brocaar/lora-app-server/npm-debug.log
npm ERR! not ok code 0

### supporting information:

 - `npm -v` prints:
1.3.10
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
Linux,Ubuntu
 - Network issues:
 - Container:
   - [ ] I develop using Vagrant on OS X or Linux.

**Comment by kenany** [comment]
@y0913011011 Sorry, Node.js 0.10 and `npm@1.3` are years old and are no longer supported.
