### ISSUE TITLE
npm安装vue-cli报错

### ISSUE THREAD

**Issue by 18911160487** [npm/npm#18245]
qzx@DESKTOP-3738K3T MINGW64 ~/Desktop
$ npm install vue
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "vue"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ENOSELF

npm ERR! Refusing to install vue as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\qzx\Desktop\npm-debug.log
拜托拜托了各位大神！！

**Comment by kenany** [comment]
@18911160487 Ensure that the `"name"` field in your `package.json` is not set to `"vue"`.

**Comment by zhangyuling37du** [comment]
您的问题有解决么，我也遇到这种情况

**Comment by daoqing99** [comment]
我也碰到几次这样的问题,解决了吗

**Comment by kenany** [comment]
Closing as abandoned.
