### ISSUE TITLE
package install failed 

### ISSUE THREAD

**Issue by DrJar** [npm/npm#18249]
[npm-debug.zip](https://github.com/npm/npm/files/1238189/npm-debug.zip)

#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
**The installation of cli is failed**
### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [x ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
@DrJar Could you please take the time to fill out the support form in your post? Also, it would be great if you could upload the debug log as plaintext to <https://gist.github.com/> instead of zipping it up.

**Comment by kenany** [comment]
Closing due to no progress here.
