### ISSUE TITLE
How to avoid “npm fetch GET 200” logs when invoking install in npm 5

### ISSUE THREAD

**Issue by crunchtime-ali** [npm/npm#18256]
Ever since upgrading to npm 5 I get a gazillion of `npm fetch GET 200 ...` messages (see below) on my build servers despite setting `npm config set loglevel warn`. Is there a new setting for that?

    [0m[91mnpm info[0m[91m config[0m[91m set "loglevel" "warn"
    [0m[91mnpm info [0m[91mok 
    [0m[91mnpm[0m[91m info it worked if it ends with ok
    [0m[91mnpm info using npm@5.3.0
    npm info using node@v8.3.0
    [0m[91mnpm info lifecycle myapp-client@0.0.1~preinstall: myapp-client@0.0.1
    [0m[91mnpm http fetch GET 200 https://registry.npmjs.org/babel-eslint 98ms
    [0m[91mnpm http fetch GET 200 https://registry.npmjs.org/babel-eslint/-/babel-eslint-7.2.3.tgz 23ms
    [...]

**Comment by salmanwaheed** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mkdirenv@gmail.com
    Domain salmanwaheed.info has exceeded the max emails per hour (154/150 (102%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193]:40305 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by box1177.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1e7wcs-000lDw-GC
	for hello@salmanwaheed.info; Thu, 26 Oct 2017 22:52:10 -0600
Date: Thu, 26 Oct 2017 21:51:59 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1509079919;
	bh=8AgE6CnR+TrZpaaCoYoJ6R85C9Ts6ipLuPLemEpC5cs=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=BXI8XcDePNkkYL9i3TKweG/3yPYqHIKfU0sl4SoJqVYdLYHijGjrATLPnqPsqSiwO
	 Xf8DvzG3hamoDbXOG7VNZD7ZOP5Q6YfEfzUbkMNJR4uQxdeMTjv8vcHhuFULnNR0FW
	 xzH2SxvEpyPkFNhK9+3Rcn7O148wzi+yeJ2y+eKI=
