### ISSUE TITLE
npm ERR! code EINTEGRITY

### ISSUE THREAD

**Issue by initialdmg** [npm/npm#18259]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [-] Other (_see below for feature requests_):

#### What's going wrong?

 npm hungs at extract phrase and then got error when i install packages

#### How can the CLI team reproduce the problem?

24888 silly extract asynckit@0.4.0
24889 verbose unlock done using C:\Users\Administrator\AppData\Roaming\npm-cache\_locks\staging-948eb1e4f981cfbe.lock for E:\souceCode\spring-breeze\node_modules\.staging
24890 warn spring-breeze@1.2.1 No repository field.
24891 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\fsevents):
24892 warn optional SKIPPING OPTIONAL DEPENDENCY: sha512-Sn44E5wQW4bTHXvQmvSHwqbuiXtduD6Rrjm2ZtUEGbyrig+nUH3t/QD4M4/ZXViY556TBpRgZkHLDx3JxPwxiw== integrity checksum failed when using sha512: wanted sha512-Sn44E5wQW4bTHXvQmvSHwqbuiXtduD6Rrjm2ZtUEGbyrig+nUH3t/QD4M4/ZXViY556TBpRgZkHLDx3JxPwxiw== but got sha512-v+ZwAPVeSIXpsalAMEwY4Y2twwzdHt3sUtgRoDUo7k0K+pjp0yvMYi7wQr96n1P2fKP7GXh5rO1Mo8OLhRYJvA==. (1209805 bytes)
24893 verbose type OperationalError
24894 verbose stack Error: sha1-hilUyLWBC/+HpIsN4EFu2MS7HDY= integrity checksum failed when using sha1: wanted sha1-hilUyLWBC/+HpIsN4EFu2MS7HDY= but got sha1-XBITif0xwpRp22sKDUmFMhAqEdM=. (838338 bytes)
24894 verbose stack     at Transform.on (C:\Program Files\nodejs\node_modules\npm\node_modules\ssri\index.js:275:19)
24894 verbose stack     at emitNone (events.js:110:20)
24894 verbose stack     at Transform.emit (events.js:207:7)
24894 verbose stack     at endReadableNT (_stream_readable.js:1045:12)
24894 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)
24894 verbose stack     at process._tickCallback (internal/process/next_tick.js:180:9)
24895 verbose cwd E:\souceCode\spring-breeze
24896 verbose Windows_NT 6.1.7601
24897 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
24898 verbose node v8.2.1
24899 verbose npm  v5.3.0
24900 error code EINTEGRITY
24901 error sha1-hilUyLWBC/+HpIsN4EFu2MS7HDY= integrity checksum failed when using sha1: wanted sha1-hilUyLWBC/+HpIsN4EFu2MS7HDY= but got sha1-XBITif0xwpRp22sKDUmFMhAqEdM=. (838338 bytes)
24902 verbose exit [ 1, true ]

### supporting information:

 - `npm -v` prints: 5.3.0
 - `node -v` prints: 8.3.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: windows
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by ravindralande** [comment]
npm -v 5.*
node -v 8.*
rm ./package-lock.json
rm -r ./node_modules
npm cache clear --force
npm set registry https://registry.npmjs.org/
yarn install
fixed this issue for me

**Comment by initialdmg** [comment]
It seems to be a npm bug, see #17671 . I downgraded npm to v5.0.3，and then install and uninstall commands haven't cause error again so far.

**Comment by jakeNiemiec** [comment]
@initialdmg the EINTEGRITY issue is also present on OSX.

**Comment by salmanwaheed** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mkdirenv@gmail.com
    Domain salmanwaheed.info has exceeded the max emails per hour (152/150 (101%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193]:57627 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by box1177.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1e7wc6-000l2U-91
	for hello@salmanwaheed.info; Thu, 26 Oct 2017 22:51:22 -0600
Date: Thu, 26 Oct 2017 21:51:11 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1509079871;
	bh=m/UBT9GXFCdoNC6wBCy+WlBWK2DYnY9SQH7z9vth7Yw=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=G6UMotR0S3ye+uGLRrk9Rx1DD0guApA47wr/4f2TraA2PAYGGhtT/MLnGoO//KA0u
	 EGgz4PXfRG46ngsmh02C/Dvefbd82y1hgMOUXS/srzfuJm9SJwm9Nf9C6n+d5F51eO
	 SrLaG9+rpa7ymjH0EOqKeA/RzXLMxi76f2uVJKog=

**Comment by AdhamRammadan** [comment]
Have you tried `npm install --update-binary --no-shrinkwrap` ? I had luck with that command, after doing `npm cache clean --force` . And I regenerated and versionned a fresh npm-shrinkwrap.json after these operations.
