### ISSUE TITLE
NPM install gulp fails

### ISSUE THREAD

**Issue by srigsiva** [npm/npm#18253]
Hi,

I had tried installing gulp using the command "**npm install gulp gulp-cli -d --global**", i am getting an error for proxy setting.
I am using my office network and i do not have a proxy setting. I have checked my browser settings for proxy and it is set to "Auto detect proxy".

PFB the log of npm installation.

C:\WINDOWS\system32>npm install gulp gulp-cli -d --global
npm info it worked if it ends with ok
npm info using npm@3.10.10
npm info using node@v6.11.2
npm info attempt registry request try #1 at 3:41:25 PM
npm http request GET http://registry.npmjs.org/gulp
npm info attempt registry request try #1 at 3:41:25 PM
npm http request GET http://registry.npmjs.org/gulp-cli
npm info retry will retry, error on last attempt: Error: connect ETIMEDOUT **IP_ADDRESS**
npm info retry will retry, error on last attempt: Error: connect ETIMEDOUT **IP_ADDRESS**
npm info attempt registry request try #2 at 3:41:56 PM
npm http request GET http://registry.npmjs.org/gulp
npm info attempt registry request try #2 at 3:41:56 PM
npm http request GET http://registry.npmjs.org/gulp-cli
npm info retry will retry, error on last attempt: Error: connect ETIMEDOUT **IP_ADDRESS**
npm info retry will retry, error on last attempt: Error: connect ETIMEDOUT **IP_ADDRESS**
npm info attempt registry request try #3 at 3:43:17 PM
npm http request GET http://registry.npmjs.org/gulp
npm info attempt registry request try #3 at 3:43:17 PM
npm http request GET http://registry.npmjs.org/gulp-cli
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "gulp" "gulp-cli" "-d" "--global"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! syscall connect

npm ERR! network connect ETIMEDOUT **IP_ADDRESS**
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     C:\WINDOWS\system32\npm-debug.log

I tried the steps mentioned in github threads, but all were related to setting proxy details for npm. In my case i am not using any proxy.

Could you please suggest a solution/workaround for this?

Thanks in advance.

Regards,
Sri

**Comment by srigsiva** [comment]
Hi,

I have tried checking the config options using "**npm config list**", but no proxy settings available.

C:\Program Files\nodejs\node_modules\npm>npm config list
; cli configs
user-agent = "npm/3.10.10 node/v6.11.2 win32 x64"

; userconfig C:\Users\srigsiva\.npmrc
**https-proxy = null
proxy = null**
registry = "http://registry.npmjs.org/"

; builtin config undefined
prefix = "C:\\Users\\srigsiva\\AppData\\Roaming\\npm"

; node bin location = C:\Program Files\nodejs\node.exe
; cwd = C:\Program Files\nodejs\node_modules\npm
; HOME = C:\Users\srigsiva
; "npm config ls -l" to show all defaults.


Could anyone throw some light on this?

Regards,
Sri

**Comment by salmanwaheed** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mkdirenv@gmail.com
    Domain salmanwaheed.info has exceeded the max emails per hour (159/150 (106%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext7.iad.github.net ([192.30.252.198]:51370 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by box1177.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1e7wds-000lUU-83
	for hello@salmanwaheed.info; Thu, 26 Oct 2017 22:53:12 -0600
Date: Thu, 26 Oct 2017 21:53:01 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1509079981;
	bh=clYwJF42cD9xlvds+1FckJHqebWK9YNAmHBfOfm7VB8=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=XR6LZo1M3IPCeDOGGdahfvbmnRzVpEWirELSC2GSJS+P8WG8GA5seuMSdhm5wBaub
	 0sSGbvjtvSp9lQyMjGpLx/7sTLbASfiTKmsMy00KtvX7eHfaphevuieW+uZjBccmGM
	 F1vczE1F6Kj09RcDbEA84gXzM+GTMR0UTudTP9Z0=
