### ISSUE TITLE
typescript installation issue

### ISSUE THREAD

**Issue by salinimt** [npm/npm#18254]
C:\Users\user>npm install -g typescript
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "typescript"
npm ERR! node v6.10.0
npm ERR! npm  v1.0.0

npm ERR! shasum check failed for C:\Users\user\AppData\Local\Temp\npm-4180-6c6a63b4\registry.npmjs.org\typescript\-\typescript-2.4.2.tgz
npm ERR! Expected: f8395f85d459276067c988aa41837a8f82870844
npm ERR! Actual:   257f8186887ede8dd7d19579a705091453e887ba
npm ERR! From:     https://registry.npmjs.org/typescript/-/typescript-2.4.2.tgz
npm ERR!

**Comment by salmanwaheed** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mkdirenv@gmail.com
    Domain salmanwaheed.info has exceeded the max emails per hour (155/150 (103%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext5.iad.github.net ([192.30.252.196]:34685 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by box1177.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1e7wcy-000lGw-Bw
	for hello@salmanwaheed.info; Thu, 26 Oct 2017 22:52:16 -0600
Date: Thu, 26 Oct 2017 21:52:03 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1509079923;
	bh=tqahMBjjZWPBkQNEOiMu1bA190KRkbOCyGO16Pi8N98=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=qTRl5uA132eJCYa7XqMb8HWvO5e/XgjbXchPyj1lvDxjq3wFympbARtog4Hk8ue5f
	 OmYiVVeSU/csMjtrg8uSo/N4s3I1vx1RAczglDfiRBOgDBjYuORaMKti65SK/hV9y6
	 Jwk9mc//vtU67xpq5rR93iURXHDEFyqpxH0oBTI8=

**Comment by salmanwaheed** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mkdirenv@gmail.com
    Domain salmanwaheed.info has exceeded the max emails per hour (157/150 (104%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:45947 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by box1177.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1e7wd7-000lJ1-M8
	for hello@salmanwaheed.info; Thu, 26 Oct 2017 22:52:26 -0600
Date: Thu, 26 Oct 2017 21:52:14 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1509079935;
	bh=C0NxVTZ48s0iOYB8oTSUFHZKXT4H0pN32oGNLV3aGVY=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=jjc16CW6Xj8odnqEglBZM9E0etYI3A/MEUvTUqLgvhi/JrLXKvixb9ROgTVlFEDkD
	 zYLxRHn3e3yIKRPFju7BxYRR3nebwFH05xOOSjNfv4oltUIs3sCa5u2PiOKvmAGlho
	 xP9Nyn2mBaU+bYr32pMrSarUSQTqSjqh7u6yi0l8=

**Comment by stefek99** [comment]
```
npm install
✖ Running command - failed!
[ERROR] An error occurred while running npm install (exit code 1):

        npm ERR! Darwin 17.2.0
        npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
        npm ERR! node v6.9.5
        npm ERR! npm v3.10.10

        npm ERR! shasum check failed for
        /var/folders/2t/qk7l_nt10rg0znh0w60gdn7m0000gn/T/npm-25405-2ff18c2b/registry.npmjs.org/typescript/-/typescript-2.4.2.tgz
        npm ERR! Expected: f8395f85d459276067c988aa41837a8f82870844
        npm ERR! Actual: 8db5688cb06fb4bd0124b548da22df4d6509225d
        npm ERR! From: https://registry.npmjs.org/typescript/-/typescript-2.4.2.tgz
        npm ERR!
        npm ERR! If you need help, you may report this error at:
        npm ERR! <https://github.com/npm/npm/issues>

        npm ERR! Please include the following file with any support request:
        npm ERR! /Users/zen/Downloads/ionic/myApp/npm-debug.log
```

### npm-debug.log

```
6289 silly install printInstalled
6290 verbose stack Error: shasum check failed for /var/folders/2t/qk7l_nt10rg0znh0w60gdn7m0000gn/T/npm-25405-2ff18c2b/registry.npmjs.org/typescript/-/typescript-2.4.2.tgz
6290 verbose stack Expected: f8395f85d459276067c988aa41837a8f82870844
6290 verbose stack Actual:   8db5688cb06fb4bd0124b548da22df4d6509225d
6290 verbose stack From:     https://registry.npmjs.org/typescript/-/typescript-2.4.2.tgz
6290 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/sha/index.js:25:8
6290 verbose stack     at ReadStream.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/sha/index.js:72:7)
6290 verbose stack     at emitNone (events.js:91:20)
6290 verbose stack     at ReadStream.emit (events.js:185:7)
6290 verbose stack     at endReadableNT (_stream_readable.js:974:12)
6290 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:74:11)
6290 verbose stack     at process._tickCallback (internal/process/next_tick.js:98:9)
6291 verbose cwd /Users/zen/Downloads/ionic/myApp
6292 error Darwin 17.2.0
6293 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
6294 error node v6.9.5
6295 error npm  v3.10.10
6296 error shasum check failed for /var/folders/2t/qk7l_nt10rg0znh0w60gdn7m0000gn/T/npm-25405-2ff18c2b/registry.npmjs.org/typescript/-/typescript-2.4.2.tgz
6296 error Expected: f8395f85d459276067c988aa41837a8f82870844
6296 error Actual:   8db5688cb06fb4bd0124b548da22df4d6509225d
6296 error From:     https://registry.npmjs.org/typescript/-/typescript-2.4.2.tgz
6297 error If you need help, you may report this error at:
6297 error     <https://github.com/npm/npm/issues>
6298 verbose exit [ 1, true ]
```
