### ISSUE TITLE
npa.resolve is not a function when trying npm install

### ISSUE THREAD

**Issue by matheusanmo** [npm/npm#18258]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [X] npm is producing an incorrect install.
  - [X] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

trying to `npm install` causes the error `TypeError: npa.resolve is not a function`

#### How can the CLI team reproduce the problem?

On OpenBSD 6.1 x86-64: Compile node v8.4.0. `pkg_add npm` to install the npm binary package. Create symbolic link from `node` to the compiled node v8.4.0. Do `npm install` for package.json linked below. 

[package.json](https://gist.github.com/matheusanmo/dd93e8b249a828d661fb4cd4b8c9138f)
[npm's debug.log](https://gist.github.com/matheusanmo/919ba9d4cc93c1504229076ea31d1e71)

### supporting information:

 - `npm -v` prints: `5.3.0`
 - `node -v` prints: `v8.4.0`
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?: OpenBSD 6.1 x86-64
 - Network issues:
   - Geographic location where npm was run: Brazil
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by aleung** [comment]
I saw the same error with npm 5.3.0. But it's gone after upgrade to npm 5.4.1.

**Comment by vtamara** [comment]
Happens to me also with npm 5.4.1
