### ISSUE TITLE
npm ERR! cb() never called!

### ISSUE THREAD

**Issue by zbjumper** [npm/npm#18250]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

When I run "npm update", it Crashed! The Log is :

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Bill/.npm/_logs/2017-08-21T10_06_07_863Z-debug.log

log file is :

[2017-08-21T10_06_07_863Z-debug.log.zip](https://github.com/npm/npm/files/1238492/2017-08-21T10_06_07_863Z-debug.log.zip)

**Comment by daankets** [comment]
I have exactly the same issue with `npm install` and `npm prune --production`. There is no logfile generated.

**Comment by salmanwaheed** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mkdirenv@gmail.com
    Domain salmanwaheed.info has exceeded the max emails per hour (160/150 (106%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext4.iad.github.net ([192.30.252.195]:57577 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by box1177.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1e7wea-000lvF-8U
	for hello@salmanwaheed.info; Thu, 26 Oct 2017 22:53:56 -0600
Date: Thu, 26 Oct 2017 21:53:45 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1509080025;
	bh=4uJiP3sPCFPCsJ+t/sMgv5Xhbuh1ZtbwQ6mWl5GUDXo=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=hWtopIT0AAfNeup6sztLU/Tf54H9aJ/+bs7lY0p6g8tZRTIeipOu5MdtU78kb8gJ7
	 M4GkYtZDVkrONdEnmBGpWu7GAAMMfF41knVmNgM0ZZlvoDmLUHuKTCjBXMkcO0D/Ty
	 Li/fwlM8dpuoppAM67ZuW26N8gmQ453hbQYnhe24=
