### ISSUE TITLE
npm ERR! shasum check failed for jshint and other packages

### ISSUE THREAD

**Issue by ghost** [npm/npm#18264]
#### I'm opening this issue because:

  - [x] npm is producing an incorrect install.
 
#### What's going wrong?

Unable to install npm packages

npm ERR! shasum check failed for C:\Users\macbook\AppData\Local\Temp\npm-5792-0e555c93\registry.npmjs.org\jshint\-\jshint-2.5.11.tgz
npm ERR! Expected: e2d95858bbb1aa78300108a2e81099fb095622e0
npm ERR! Actual:   9c52d27f088cd06aeb6586edf4ec88c9ab8cec02
npm ERR! From:     https://registry.npmjs.org/jshint/-/jshint-2.5.11.tgz

### supporting information:

npm ERR! node v6.10.2
npm ERR! npm  v3.10.10

 - `npm config get registry` prints: https://registry.npmjs.org/

 - Windows, OS X/macOS, or Linux?: Windows 7
 - Network issues:
   - Geographic location where npm was run: India
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by salmanwaheed** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mkdirenv@gmail.com
    Domain salmanwaheed.info has exceeded the max emails per hour (151/150 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext8.iad.github.net ([192.30.252.199]:50215 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by box1177.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1e7wbn-000kwe-HG
	for hello@salmanwaheed.info; Thu, 26 Oct 2017 22:51:03 -0600
Date: Thu, 26 Oct 2017 21:50:52 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1509079852;
	bh=getTRNosB79d/cdWeK/L1AeQRDYUM6gJre40AhfcOQw=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=PFV1RJDS7Uua3BOEisWTYoJ9Tj6kEdO4Pfa4IPHgD4rINZgrGrHrkwAUTchKRvCRx
	 8fW4Aiaws13FGQlmpLhFJ63DCBlwpLDyKPRxspzltXEyZ5rQqTGgR6Pg9tlzo9JWTZ
	 C+sqC7oKXhh2c5rHhWhsMJu0bU+8KE/QwzoOubUo=
