### ISSUE TITLE
Partial dependency locking

### ISSUE THREAD

**Issue by csales1987** [npm/npm#18267]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?

We have internal NPM modules that we push up to our own private NPM artifactory server, via Continuous Integration. On this, we have created our own namespace. The problem is, we want to be able to utilize the package-lock.json, however during development when devs push code to the other module, they do not see it UNLESS they delete the package-lock.json and npm install again which has to download everything again. 

Why is there not a way to specify that a particular dependency should ALWAYS pull latest and NOT get locked in the package-lock.json?

**Comment by zkat** [comment]
We used to have package locks. This is no longer the case, and it caused way more trouble than it was worth. Our working model for `package-lock.json` is now one where it is a full description of a dependency tree, and we are very very unlikely to change that.

If you want to update your dependencies, you can use the `$ npm update` command to bring these dependencies up to date, or even `$ npx npm-check -u` to do so interactively.
