### ISSUE TITLE
error while installing package

### ISSUE THREAD

**Issue by pankajbelwal04122016** [npm/npm#18273]
D:\wamp\www\typescript>npm --version
(node:868) fs: re-evaluating native module sources is not supported. If you are
using the graceful-fs module, please update it to a more recent version.
2.12.0

Not able to resolve the issue. Please help.

**Comment by kenany** [comment]
@pankajbelwal04122016 Does this also occur with the latest stable `npm` release?

**Comment by kenany** [comment]
Closing as abandoned.
