### ISSUE TITLE
npm@5.4.0 preinstall error

### ISSUE THREAD

**Issue by jasonChen1982** [npm/npm#18276]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [x] npm is producing an incorrect install.

#### What's going wrong?

when i install v8-profiler use npm@5.4.0, but get normal with npm@5.3.0

```sh
> v8-profiler@5.7.0 preinstall /home/node_modules/v8-profiler
> node -e 'process.exit(0)'

npm ERR! Cannot read property 'pause' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/.npm/_logs/xxx.log
ERROR: Build failed: exit status 1
```
and i found the break point was throw by `npm-lifecycle`,  
> npm-lifecycle/index.js  @line:212

![image](https://user-images.githubusercontent.com/8683772/29613893-955714b2-883a-11e7-87b8-61df90e63cd2.png)

#### How can the CLI team reproduce the problem?

check `opts.log` before use `opts.log.pause()`

**Comment by irond13** [comment]
I'm receiving the same error when trying to install Sails.js v0.12.x. It happens to use a preinstall script if that is of any assistance.
