### ISSUE TITLE
npm not Installing anything

### ISSUE THREAD

**Issue by vishalpardeshi419** [npm/npm#18297]
Getting This Error 

npm ERR! Windows_NT 6.1.7600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Iphone\\AppData
\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i" "-g" "npm@4"
npm ERR! node v8.4.0
npm ERR! npm  v3.5.3
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'internal/fs'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Windows\system32\npm-debug.log

**Comment by MSmashal** [comment]
Creating a new React app in C:\MyProject\type\my-app.

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts-ts...

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "--save-exact" "--loglevel" "error" "react" "react-dom" "react-scripts-ts"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10

npm ERR! shasum check failed for C:\Users\marshal\AppData\Local\Temp\npm-23144-678170a5\registry.npmjs.org\typescript\-\typescript-2.4.2.tgz
npm ERR! Expected: f8395f85d459276067c988aa41837a8f82870844
npm ERR! Actual:   9d0f29369f02fdffcc73c3da42f9a14ad4ef107d
npm ERR! From:     https://registry.npmjs.org/typescript/-/typescript-2.4.2.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
