### ISSUE TITLE
SyntaxError: Unexpected token < in JSON at position 58616

### ISSUE THREAD

**Issue by rae-ralston** [npm/npm#18294]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

NPM is crashing when installing dependencies from package.json in one project.
when I `npm i` I get this error: 
 `SyntaxError: Unexpected token < in JSON at position 58616` (gist below)

I've tried:
- deleting package json on another project and `npm install` there. (works fine)
- uninstalling and reinstalling node, npm & nvm, get the exact same error.
- tried it on latest version of node & required node version for the project, get the exact same error.
- deleted and re-cloned project, get the exact same error.
- installing a specific package `npm i react` gives the exact same error.
- deleted all `<` characters from package.json, same error.

I can't make sense of the error. Can you shed *any* light?
[Praying for some some help](https://media.tenor.com/images/1a11748f0c7ce30ab4afd057fab66751/tenor.gif)

#### How can the CLI team reproduce the problem?

Debug Log & package.json : https://gist.github.com/rachel-ftw/55e6753a6b278e22b3f0a77e066707a6

lmk if I can provide any other context or information.

### supporting information:

 - `npm -v` prints: `3.10.10``
 - `node -v` prints: `v6.11.2`
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?: OS X Sierra
 - Network issues:
   - Geographic location where npm was run: California, USA
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by iarna** [comment]
Resolved elsewhere. =)
