### ISSUE TITLE
cb() never called! on install command using a git+https URL

### ISSUE THREAD

**Issue by pedro-pedrosa** [npm/npm#18303]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

When trying to install a module on a git repo using the git+https protocol I get "cb() never called!" error.
get ls-remote works just fine so it's not an issue with server connectivity.

#### How can the CLI team reproduce the problem?

Install a module on a Git repo using the git+https protocol
CLI log: https://gist.github.com/bLasTamos/87679e39833422e4219b5efa110e6804

### supporting information:

 - `npm -v` prints: 5.3.0
 - `node -v` prints: v8.4.0
 - Windows, OS X/macOS, or Linux?: Windows

**Comment by pedro-pedrosa** [comment]
Fixed my problem.
This was happening because the package.json file was located under a subfolder. Moved the file to the repo root and it started working. Maybe this should have a more discriptive error message.

**Comment by aghArdeshir** [comment]
+1

I got this error too. My problem also was with my `package.json` file. It was in it's place, but `version` field had invalid value:
instead of `"version":"1.1.1",`
I had `"version":"1,1,1",` (commas instead of dots)

I also think that a more descriptive message would help. like saying 

> something is wrong with your package.json

thanks!
