### ISSUE TITLE
npm scripts extended glob

### ISSUE THREAD

**Issue by pwang2** [npm/npm#18306]
#### What's going wrong?
npm script does not behave as expected on extended globs. 

#### How can the CLI team reproduce the problem?
```
jenkins@9efe0820ef64:~$ npm config get shell
bash
jenkins@9efe0820ef64:~$ npm run testem-ci-prep
> canvas-ui@1.0.0 testem-ci-prep /home/ci_home
> rm -rf test/unit/{coverage,junit,tap} && mkdir -p test/unit/{coverage,junit,tap}
jenkins@9efe0820ef64:~$ ls test/unit
{coverage,junit,tap}
jenkins@9efe0820ef64:~$ mkdir -p test/unit/{coverage,junit,tap}
jenkins@9efe0820ef64:~$ ls test/unit
coverage      tap         junit          {coverage,junit,tap}
```

### supporting information:
 - `npm -v` prints: 5.0.3
 - `node -v` prints: 6.11.2
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux
 
 - Container:
   - [x] I develop / deploy using Docker.

**Comment by jeremywiebe** [comment]
…/web  ⬢ 8.4.0   update-validator-to-8.1 ● ⍟11  cat package.json | grep "md"                                                  ✓  11277  09:13:11
    "md": "rm -rf test/unit/{coverage,junit,tap} && mkdir -p test/unit/{coverage,junit,tap}",
 …/web  ⬢ 8.4.0   update-validator-to-8.1 ● ⍟11  ls test/unit                                                                  ✓  11278  09:13:14
 …/web  ⬢ 8.4.0   update-validator-to-8.1 ● ⍟11  npm config get shell                                                          ✓  11279  09:13:17
/bin/bash
 …/web  ⬢ 8.4.0   update-validator-to-8.1 ● ⍟11  npm -v                                                                        ✓  11280  09:13:26
5.3.0
 …/web  ⬢ 8.4.0   update-validator-to-8.1 ● ⍟11  node -v                                                                       ✓  11281  09:13:31
v8.4.0
 …/web  ⬢ 8.4.0   update-validator-to-8.1 ● ⍟11  npm config get registry                                                       ✓  11282  09:13:34
https://registry.npmjs.org/
 …/web  ⬢ 8.4.0   update-validator-to-8.1 ● ⍟11  npm run md                                                                    ✓  11283  09:13:42

> progressive-web-scaffold@0.20.0 md /Users/jeremy/Development/platform-scaffold/web
> rm -rf test/unit/{coverage,junit,tap} && mkdir -p test/unit/{coverage,junit,tap}

 …/web  ⬢ 8.4.0   update-validator-to-8.1 ● ⍟11  ls test/unit                                                                  ✓  11284  09:13:52
total 0
drwxr-xr-x  2 jeremy  staff    68B 28 Aug 09:13 coverage/
drwxr-xr-x  2 jeremy  staff    68B 28 Aug 09:13 junit/
drwxr-xr-x  2 jeremy  staff    68B 28 Aug 09:13 tap/
 …/web  ⬢ 8.4.0   update-validator-to-8.1 ● ⍟11  bash --version                                                                ✓  11285  09:13:56
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)
Copyright (C) 2007 Free Software Foundation, Inc.
 …/web  ⬢ 8.4.0   update-validator-to-8.1 ● ⍟11 

**Comment by pwang2** [comment]
seems fixed.
