### ISSUE TITLE
Unable to install angular/cli and ng/cli on VPS - Linux system from Godaddy

### ISSUE THREAD

**Issue by hemant19914** [npm/npm#18318]
----------------------------------------------------------------------
COMMANDS TRIED :
1)  npm install -g @angular/cli
2)  npm install -g angular-cli
3)  npm install -g angular/cli
4) npm install @angular/cli
5) npm install  angular-cli
----------------------------------------------------------------------
Log while installing angular cli :
----------------------------------------------------------------------
npm ERR! git clone git@github.com:angular/cli Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-angular-cli-515723dd'...
npm ERR! git clone git@github.com:angular/cli Permission denied (publickey).
npm ERR! git clone git@github.com:angular/cli fatal: Could not read from remote repository.
npm ERR! git clone git@github.com:angular/cli
npm ERR! git clone git@github.com:angular/cli Please make sure you have the correct access rights
npm ERR! git clone git@github.com:angular/cli and the repository exists.
npm ERR! addLocal Could not install angular/cli

----------------------------------------------------------------------
COMMANDS TRIED :
1)  npm install -g @ng/cli
2)  npm install -g ng-cli
3)  npm install -g ng/cli
4) npm install @ng/cli
5) npm install  ng-cli
----------------------------------------------------------------------
Log while installing ng cli :
----------------------------------------------------------------------
npm ERR! git clone git@github.com:ng/cli Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-ng-cli-433d7e4d'...
npm ERR! git clone git@github.com:ng/cli Permission denied (publickey).
npm ERR! git clone git@github.com:ng/cli fatal: Could not read from remote repository.
npm ERR! git clone git@github.com:ng/cli
npm ERR! git clone git@github.com:ng/cli Please make sure you have the correct access rights
npm ERR! git clone git@github.com:ng/cli and the repository exists.
npm ERR! addLocal Could not install ng/cli
npm ERR! Error: ENOENT, stat 'ng/cli'

----------------------------------------------------------------------
Environment Details :
----------------------------------------------------------------------
System Linux 2.6.32-042stab104.1
node -v v0.10.48
npm -v 1.3.6

**Comment by kenany** [comment]
@hemant19914 Your versions of Node.js and `npm` are years old and are no longer supported.

**Comment by Chklang** [comment]
If you have this problem on Debian, you must install Node6, but it's not into officials PPA. So you can go here to do it : https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-debian-8
