### ISSUE TITLE
Problem while running npm install react react-dom --save

### ISSUE THREAD

**Issue by pravin-105111** [npm/npm#18310]
While npm install react react-dom --save or npm install react react-dom --save-dev command command windows(window 10). I am getting following error.

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "react" "react-dom" "--save-dev"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ENOSELF

npm ERR! Refusing to install react as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\codebase\react\npm-debug.log

**Comment by pravin-105111** [comment]
Please give some suggestion...

**Comment by kenany** [comment]
@pravin-105111 Ensure that the `"name"` field in your `package.json` is not set to `"react"`. Try setting it to something more unique :)

**Comment by pravin-105111** [comment]
Thanks, KenanY...... This approach worked.
