### ISSUE TITLE
npm 5.4.0 removes executable permission

### ISSUE THREAD

**Issue by rpadovani** [npm/npm#18324]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

During installation of a package npm removes the +x permission flag

#### How can the CLI team reproduce the problem?

Install `react-native` both with npm 5.3.0 and 5.4.0 and see the differences in the `scripts/` directory.
All the files aren't executable anymore

```
/tmp/npm-permissions                                                                                                                                                                                              
▶ npm -v
5.3.0

/tmp/npm-permissions                                                                                                                                                                                              
▶ npm i react-native
npm WARN saveError ENOENT: no such file or directory, open '/tmp/npm-permissions/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/tmp/npm-permissions/package.json'
npm WARN react-native@0.47.2 requires a peer of react@16.0.0-alpha.12 but none was installed.
npm WARN npm-permissions No description
npm WARN npm-permissions No repository field.
npm WARN npm-permissions No README data
npm WARN npm-permissions No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ react-native@0.47.2
added 690 packages in 22.626s

/tmp/npm-permissions                                                                                                                                                                                              
▶ ls -l node_modules/react-native/scripts 
total 24
-rwxrwxr-x 1 rpadovani rpadovani  933 Aug 22 11:00 ios-configure-glog.sh
-rwxrwxr-x 1 rpadovani rpadovani 1230 Aug 22 11:00 ios-install-third-party.sh
-rw-rw-r-- 1 rpadovani rpadovani  382 Aug 22 11:00 launchPackager.bat
-rwxrwxr-x 1 rpadovani rpadovani  498 Aug 22 11:00 launchPackager.command
-rwxrwxr-x 1 rpadovani rpadovani  397 Aug 22 11:00 packager.sh
-rwxrwxr-x 1 rpadovani rpadovani 3517 Aug 22 11:00 react-native-xcode.sh

/tmp/npm-permissions                                                                                                                                                                                              
▶ rm -rf node_modules 

/tmp/npm-permissions                                                                                                                                                                                              
▶ npm i -g npm@5.4.0
/usr/bin/npm -> /usr/lib/node_modules/npm/bin/npm-cli.js
/usr/bin/npx -> /usr/lib/node_modules/npm/bin/npx-cli.js
+ npm@5.4.0
added 22 packages, removed 22 packages and updated 19 packages in 6.257s

/tmp/npm-permissions                                                                                                                                                                                              
▶ npm -v
5.4.0

/tmp/npm-permissions                                                                                                                                                                                              
▶ npm i react-native
npm WARN saveError ENOENT: no such file or directory, open '/tmp/npm-permissions/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/tmp/npm-permissions/package.json'
npm WARN react-native@0.47.2 requires a peer of react@16.0.0-alpha.12 but none is installed. You must install peer dependencies yourself.
npm WARN npm-permissions No description
npm WARN npm-permissions No repository field.
npm WARN npm-permissions No README data
npm WARN npm-permissions No license field.

+ react-native@0.47.2
added 575 packages in 6.413s

/tmp/npm-permissions                                                                                                                                                                                              
▶ ls -l node_modules/react-native/scripts
total 24
-rw-rw-r-- 1 rpadovani rpadovani  933 Aug 22 11:00 ios-configure-glog.sh
-rw-rw-r-- 1 rpadovani rpadovani 1230 Aug 22 11:00 ios-install-third-party.sh
-rw-rw-r-- 1 rpadovani rpadovani  382 Aug 22 11:00 launchPackager.bat
-rw-rw-r-- 1 rpadovani rpadovani  498 Aug 22 11:00 launchPackager.command
-rw-rw-r-- 1 rpadovani rpadovani  397 Aug 22 11:00 packager.sh
-rw-rw-r-- 1 rpadovani rpadovani 3517 Aug 22 11:00 react-native-xcode.sh
```

Please note the total absence of the `x` in the last output

### supporting information:

 - `npm -v` prints: 5.3.0 (works) / 5.4.0(broken)
 - `node -v` prints: v6.11.2
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: maxOS, Linux, Linux on Docker (haven't tested Windows)
 - Network issues: none
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [x] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by jordwalke** [comment]
Are these two dupes of eachother? https://github.com/npm/npm/issues/18322

**Comment by joggienl** [comment]
Today I stumbled on to this problem with npm@5.4.0 on my osx environment.
Quick reproduce path for me was:

```bash
mkdir testProject
npm init -y
npm install -D pre-commit
ls -l node_modules/pre-commit
```

The `hooks` file should be executable. I've also taken the same steps with npm@5.3.0 and there the `hooks` file does have the execution rights.

In the changelog for the npm@5.4.0 release I noticed there has been some work arround pacote and tar. See the message here: https://github.com/npm/npm/releases/tag/v5.4.0

I also saw some issues from the past around the same problem: #18322, #16896, #16766 and possibly more.. In my understanding there was something with pacote and/or tar what caused this to happen.

@zkat, is this something you can help us with? Seems like a recurring issue lately?

Thanks!

**Comment by njwest** [comment]
Also having this issue after npm i in React Native projects, right after upgrading Node on OSX 10.12.6  [React Native Issue#10205](https://github.com/facebook/react-native/issues/10205)

**Comment by zkat** [comment]
There's a PR in review to fix this now: https://github.com/zkat/pacote/pull/117

To give some context as to why this sort of stuff is happening: one of the things we did lately is pretty much _completely_ replace the entire tarball packing and extraction chunk of npm's codebase. It was kind of a hair beast that gave us an immense amount of trouble over the years, but it had also collected some kinda-undocumented ways of doing things.

This particular bug was entirely my fault: I misunderstood and misread [how npm was setting permissions on extract before](https://github.com/npm/npm/blob/v4.6.1/lib/utils/tar.js#L304-L314), and that meant I ported it wrong to pacote.

**Comment by joggienl** [comment]
Thanks for your quick response!
Mistakes can happen to anyone ;-)

I did take a look at your commit just now, it does give me the feeling you're still not confident about the solution?

Hope to see this fix soon, thanks!

**Comment by gfelot** [comment]
I had the same issue with next.js installation [zeit/next#2228](https://github.com/zeit/next.js/issues/2228#issuecomment-327294010).

It's seems it's a MacOS issue, or not ?

**Comment by spacerockzero** [comment]
i'm having the same issue in npm 5.4, but not in npm 5.3. Happens locally on OSX, and also on Heroku linux after deploy. My error happens while opening a spawn with win-fork

**Comment by spencerhakim** [comment]
Since this is a fairly impactful bug, and plenty of automated testing/deployment systems automatically install the latest version of npm (as demonstrated by the number of other issues referencing this one), would it be reasonable to ask that `npm@latest` be reverted back to v5.3 until this is fixed?

**Comment by benjamn** [comment]
Alternatively, the next version of https://www.npmjs.com/package/pacote should [fix the problem](https://github.com/zkat/pacote/pull/117) without any other changes. I suppose changing `npm@latest` is quicker, though.

**Comment by spencerhakim** [comment]
@benjamn A new npm release would still be needed due to package-lock.json pinning the broken version of pacote. Grateful that @iarna merged and published the fix, now just waiting for the npm bump (still would've been faster to just revert `@latest` to 5.3, though... 😄)

**Comment by iarna** [comment]
The new npm release will be out in a few minutes but yeah… 😅

**Comment by benjamn** [comment]
Great!

Just for my own curiousity: how does [`npm/package-lock.json`](https://github.com/npm/npm/blob/2091dd1c748e54e85e904ce8da3b3975ee99117d/package-lock.json) come into play when I do `npm install npm@5.4.0`? That `package-lock.json` file does seem to constrain the `pacote` version, but that's surprising to me, since `package-lock.json` files are not published to npm. Does it get downloaded somehow during `npm install` anyway?

**Comment by benjamn** [comment]
Oh I see! The https://github.com/npm/npm/tree/latest/node_modules/pacote package is actually published with `npm`, because it's a bundled dependency.

**Comment by Teamop** [comment]
@zkat @iarna thanks, but with npm v5.4.1, I still get the same error using `npm install` and cannot work even with `--no-optional`, I also tried to install after cleaning the cache and ran with administrator. v5.3.0 works.

Part of the log:

> 489 silly doParallel preinstall 304
490 silly doSerial build 304
491 silly doSerial global-link 304
492 silly doParallel update-linked 304
493 silly doSerial install 304
494 silly doSerial postinstall 304
495 verbose unlock done using C:\Users\IBM_ADMIN\AppData\Roaming\npm-cache\_locks\staging-f06a9927a9d33b2a.lock for C:\Users\IBM_ADMIN\Downloads\documents\study\node.js\workspace\saas-test\saas-profit\node_modules\.staging
496 verbose stack Error: EPERM: operation not permitted, unlink 'C:\Users\IBM_ADMIN\Downloads\documents\study\node.js\workspace\saas-test\saas-profit\node_modules\fsevents\node_modules\console-control-strings\package.json'
496 verbose stack     at Error (native)
497 verbose cwd C:\Users\IBM_ADMIN\Downloads\documents\study\node.js\workspace\saas-test\saas-profit
498 verbose Windows_NT 6.1.7601
499 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\IBM_ADMIN\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
500 verbose node v6.11.1
501 verbose npm  v5.4.1
502 error path C:\Users\IBM_ADMIN\Downloads\documents\study\node.js\workspace\saas-test\saas-profit\node_modules\fsevents\node_modules\console-control-strings\package.json
503 error code EPERM
504 error errno -4048
505 error syscall unlink
506 error Error: EPERM: operation not permitted, unlink 'C:\Users\IBM_ADMIN\Downloads\documents\study\node.js\workspace\saas-test\saas-profit\node_modules\fsevents\node_modules\console-control-strings\package.json'
506 error     at Error (native)
506 error  { Error: EPERM: operation not permitted, unlink 'C:\Users\IBM_ADMIN\Downloads\documents\study\node.js\workspace\saas-test\saas-profit\node_modules\fsevents\node_modules\console-control-strings\package.json'
506 error     at Error (native)
506 error   stack: 'Error: EPERM: operation not permitted, unlink \'C:\\Users\\IBM_ADMIN\\Downloads\\documents\\study\\node.js\\workspace\\saas-test\\saas-profit\\node_modules\\fsevents\\node_modules\\console-control-strings\\package.json\'\n    at Error (native)',
506 error   errno: -4048,
506 error   code: 'EPERM',
506 error   syscall: 'unlink',
506 error   path: 'C:\\Users\\IBM_ADMIN\\Downloads\\documents\\study\\node.js\\workspace\\saas-test\\saas-profit\\node_modules\\fsevents\\node_modules\\console-control-strings\\package.json' }
507 error Please try running this command again as root/Administrator.
508 verbose exit [ -4048, true ]

**supporting information:**
node: v6.11.1
npm: v5.4.1
OS: windows 7

**Comment by mnemanja** [comment]
Same here.
node: v6.10.0
npm: v5.4.1
OS: windows 10

**Comment by joggienl** [comment]
@Teamop (and possibly also @mnemanja) I think you're referring to another issue? The EPERM is not related to this issue.

That said, version 5.4.1 solves the issue for me so it seems!
My test regarding the pre-commit package now has the correct execution permission for the "hooks" script.

Thanks @zkat!

**Comment by spencerhakim** [comment]
Can also confirm `npm@5.4.1`/`pacote@6.0.2` fixes the EACCES issue for me, thanks all!

**Comment by Teamop** [comment]
@joggienl oh...yes, I think it's related with this issue(https://github.com/npm/npm/issues/18287)
