### ISSUE TITLE
prepare doesn't seem to work locally

### ISSUE THREAD

**Issue by jy95** [npm/npm#18320]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [X] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I am trying to check if my [library](https://github.com/jy95/torrent-files-library) can be installed anywhere. 

As I am working with ES6  classes/modules , I need to have "prepare" script (ie : transpile my source code (src) by Babel to CommonJs ) so  I add [this](https://github.com/jy95/torrent-files-library/blob/master/package.json#L10) in my package.json .

As you can see [here](https://travis-ci.org/jy95/torrent-files-library/jobs/268974522) , with Travis CI (my [config file](https://github.com/jy95/torrent-files-library/blob/master/.travis.yml) ), each build correctly works ([proof](https://travis-ci.org/jy95/torrent-files-library/jobs/268974522#L465)).

But It just doesn't work locally ... 

#### How can the CLI team reproduce the problem?

1. Create a empty project  
2. Install and save dependency  "jy95/torrent-files-library"
3. To test, create a file that contains this [example](https://github.com/jy95/torrent-files-library#usage)
4. Think to replace paths by valid one 
5. Run node yourFile

What I got : 
![test](https://user-images.githubusercontent.com/9306961/29754473-19821b8a-8b86-11e7-958d-02bf8f19d7a3.png)

So npm run prepare has never been runned when I install this module ...

The log of the npm install : https://gist.github.com/jy95/207f8735cc3e63c24c393c6225537d2a

From what I read on your [man](https://docs.npmjs.com/cli/install): 

```
If the package being installed contains a prepare script, its dependencies and devDependencies will be installed, and the prepare script will be run, before the package is packaged and installed.
```

So, what is wrong here ?

### supporting information:

 - `npm -v` prints: 5.3.0
 - `node -v` prints: v6.10.3
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows 10 Home X64 - Version 1703
 - Network issues:
   - Geographic location where npm was run: Europe
   - [] I use a proxy to connect to the npm registry.  
   - [] I use a proxy to connect to the web.
   - [] I use a proxy when downloading Git repos.
   - [] I access the npm registry via a VPN
   - [] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by iarna** [comment]
Ah, ok, so the problem here is that you have `lib` in your `.gitignore` and npm builds a package out of git dependencies (exactly as if it were publishing) and so if `lib` is ignored it won't be included in that package. So what happens is that it runs the prepare scripts, then throws away their output. You probably want to either have a `files` section in your package.json with something like `[ "index.js", "lib/" ]` in it, or have a .npmignore that doesn't include `lib/`.

**Comment by jy95** [comment]
thanks for your answer. I didn't think my .gitignore could have this effet with npm release ....
I will take a mix of your solution : files [ "index.js", "lib/" ] with a .npmignore file ( that contains src)
