### ISSUE TITLE
Cannot install Angular CLI using NPM

### ISSUE THREAD

**Issue by amalmathew07** [npm/npm#18323]
I am not able to install angularCLI via NPM, getting error messages like : 

> http request GET http://registry.npmjs.org/angular-cli
> 19 http 200 http://registry.npmjs.org/angular-cli
> 20 verbose bad json <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
> 20 verbose bad json
> 20 verbose bad json 
> 20 verbose bad json
> 20 verbose bad json <html>
> 20 verbose bad json <head>
> 20 verbose bad json <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
> 20 verbose bad json <title>Access to this site is blocked</title>
> 20 verbose bad json <link rel="stylesheet" href="/en/Default/master.css" type="text/css">
> 20 verbose bad json <script type="text/javascript" language="javascript" src="/en/Default/master.js"></script>
> 20 verbose bad json <script type="text/javascript" language="javascript" src="/en/Default/base64.js"></script>
> 20 verbose bad json <script type="text/javascript" language="javascript" src="/en/Default/security.js"></script>
> 20 verbose bad json </head>
> 20 verbose bad json <body>
> 20 verbose bad json
> 20 verbose bad json 
> 20 verbose bad json <div style="border: 1px solid #285EA6;width: 95%; max-width: 700px; overflow: hidden; margin-left: 10px; background-color: #EEF2F7;">
> 20 verbose bad json 	<iframe src="http://10.0.0.102:15871/cgi-bin/block_message.cgi?ws-session=-723972361" title="test" name="ws_block" frameborder="0" scrolling="auto" style="width:100%; height: 10em;">
> 20 verbose bad json
> 20 verbose bad json 	</iframe>
> 20 verbose bad json 	<iframe src="http://10.0.0.102:15871/cgi-bin/blockOptions.cgi?ws-session=-723972361" name="ws_blockoption" frameborder="0" scrolling="auto" style="width:100%; height: 17.5em;">
> 20 verbose bad json 		<p>To enable further options, view this page with a browser that supports iframes</p>
> 20 verbose bad json 	</iframe>
Debug file is also attached.
[debug.txt](https://github.com/npm/npm/files/1255872/debug.txt)

**Comment by AlQuraian** [comment]
It seems that there's a firewall or some kind of network restriction. Make sure you have access to:
http://registry.npmjs.org

**Comment by kenany** [comment]
Closing due to no reply.
