### ISSUE TITLE
 The imported project "C:\Microsoft.Cpp.Default.props" was not found

### ISSUE THREAD

**Issue by VuduthaSaiomkar** [npm/npm#18333]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   -  develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

$ npm install

> pkcs11js@1.0.9 install C:\Users\Saiomkar\fabric-samples\fabcar\node_modules\pkcs11js
> npm run build

> pkcs11js@1.0.9 build C:\Users\Saiomkar\fabric-samples\fabcar\node_modules\pkcs11js
> node-gyp configure build

C:\Users\Saiomkar\fabric-samples\fabcar\node_modules\pkcs11js>if not defined npm_config_node_gyp (node "C:\Users\Saiomkar\.npm-global\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure build )  else (node "" configure build )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Users\Saiomkar\fabric-samples\fabcar\node_modules\pkcs11js\build\pkcs11.vcxproj
(20,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was n
ot found. Confirm that the path in the <Import> declaration is correct, and that t
he file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Saiomkar\.npm-global\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Saiomkar\\.npm-global\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "build"
gyp ERR! cwd C:\Users\Saiomkar\fabric-samples\fabcar\node_modules\pkcs11js
gyp ERR! node -v v6.11.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Saiomkar\\.npm-global\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! pkcs11js@1.0.9 build: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pkcs11js@1.0.9 build script 'node-gyp configure build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pkcs11js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pkcs11js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pkcs11js
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Saiomkar\fabric-samples\fabcar\node_modules\pkcs11js\npm-debug.log
fabcar@1.0.0 C:\Users\Saiomkar\fabric-samples\fabcar
`-- (empty)

npm WARN fabcar@1.0.0 No repository field.
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Saiomkar\\.npm-global\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! pkcs11js@1.0.9 install: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pkcs11js@1.0.9 install script 'npm run build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pkcs11js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pkcs11js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pkcs11js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Saiomkar\fabric-samples\fabcar\npm-debug.log
npm ERR! code 1

**Comment by mertd** [comment]
I got the MSB4019 error because I did not have write permissions on C. Executing the command with admin privileges helped in my case, but changing read/write permissions on C for your Windows user account should also work.
