### ISSUE TITLE
can't install detectrtc on server

### ISSUE THREAD

**Issue by krishnan-rock-on** [npm/npm#18336]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### How can the CLI team reproduce the problem?

i am trying to install detectrtc to my server. when i trying to intall that it showing some errors, here i attached my error logs.
https://github.com/muaz-khan/DetectRTC
https://www.npmjs.com/package/detectrtc

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [x] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [x] I develop using Vagrant on OS X or Linux.
   - [ ] I dev

elop / deploy using Docker.
   - [x] I deploy to a PaaS (Triton, Heroku).

![issue npm installing](https://user-images.githubusercontent.com/20636368/29821605-670d3d2e-8c7d-11e7-92d3-e9910441a375.JPG)

**Comment by kenany** [comment]
@krishnan-rock-on Ensure that the `"name"` field in your `package.json` is not set to `"detectrtc"`. Try making it something more unique :)

**Comment by kenany** [comment]
Closing as abandoned.
