### ISSUE TITLE
npm install 2 times fails with certain packages

### ISSUE THREAD

**Issue by martinlevesque** [npm/npm#18340]
#### I'm opening this issue because:

  - [X] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I have a package.json with 4 packages. The first npm install works properly. However, on the second npm install I get renaming file issues.

#### How can the CLI team reproduce the problem?

I am using the following package.json:

`
{
  "name": "testserver",
  "version": "1.0.0",
  "description": "",
  "main": "server.js",
  "scripts": {
    "test": "node server",
    "start": "node server.js"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "download": "^6.2.5",
    "express": "^4.15.4",
    "socket.io": "^2.0.3",
    "sqlite3": "^3.1.9"
  }
}
`

The output is the following:

``
`npm ERR! path C:\Users\XXX\works\test123\node_modules\sqlite3\node_modules\node-pre-gyp\node_modules\npmlog\node_modules\a               re-we-there-yet\node_modules\delegates
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\XXX\works\test123\node_modules\sqlite3\node_modules\no               de-pre-gyp\node_modules\npmlog\node_modules\are-we-there-yet\node_modules\delegates' -> 'C:\Users\XXX\works\test123\node_m               odules\sqlite3\node_modules\node-pre-gyp\node_modules\npmlog\node_modules\are-we-there-yet\node_modules\.delegates.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\XXX\AppData\Roaming\npm-cache\_logs\2017-08-29T15_18_12_250Z-debug.log`

### supporting information:

npm version: 5.3
Tested on: Windows 7, Ubuntu 16.04.3

**Comment by GeorgeSapkin** [comment]
Same issue here with node 8.4.0/npm 5.3.0 and sqlite3 and/or node-pre-gyp but on Fedora 26.

**Comment by martinlevesque** [comment]
Note that, I compared by using yarn and it works, so I guess it's an npm bug.

**Comment by martinlevesque** [comment]
Really?
