### ISSUE TITLE
npm test cannot complete

### ISSUE THREAD

**Issue by jiaqiu-09** [npm/npm#18344]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

![Uploading QQ20170830-155812.png…]()

all tests have finished, but npm test  cannot complete. 
any help will be appreciated 
### supporting information:

 - `npm -v` prints:4.5.0
 - `node -v` prints:v7.8.0
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?: macOS sierra 10.12.5
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
@Jiujiale Could you upload your debug log to <https://gist.github.com/> and link it here? Thanks!

**Comment by kenany** [comment]
Closing as abandoned.
