### ISSUE TITLE
NPM cannot complete install of @angular/cli

### ISSUE THREAD

**Issue by RobSchripsema** [npm/npm#18343]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x ] npm is producing an incorrect install.
  - [x ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Try to install @angular/cli using the following:

`npm install -g @angular/cli`

This is AFTER running `npm cache clean`.

It errors with what is basically the last 20 lines or so of this giant npm-debug.log file (renamed npm-debug.txt here so I could attach it).

#### How can the CLI team reproduce the problem?
Probably can't, exactly. It may be related to how my company has set up redirected folders in Windows 7.

### supporting information:

 - `npm -v` prints: 3.10.10
 - `node -v` prints: v6.11.2
 - `npm config get registry` prints: https://registry/npmjs.org
 - Windows, OS X/macOS, or Linux?: Windows 7
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

[npm-debug.txt](https://github.com/npm/npm/files/1262040/npm-debug.txt)

**Comment by ghost** [comment]
same here
