### ISSUE TITLE
Does npm support “no_proxy” option?

### ISSUE THREAD

**Issue by stevobm** [npm/npm#18350]
My team need to set the proxy for npm while ignoring some Urls(internal websites), but I can't find "no_proxy" option in npm-config(https://docs.npmjs.com/misc/config). 

Does npm support "no_proxy" now?

**Comment by chtompki** [comment]
I agree that with the ability to configure a proxy, one also needs the support of not running things through said proxy.

**Comment by Saturate** [comment]
It supports the other features of the request package, but not this one. It's in my mind a bug as I can't use it with a proxy.

This issue is related to #7168

It supports setting it in the `Environment Variables` but not in the `.npmrc` or `package.json` where I need to set them.

**Comment by Saturate** [comment]
@chtompki & @stevobm I created a PR that solved this feel free to test it out and or use it now: #19157
