### ISSUE TITLE
unable to install anything 

### ISSUE THREAD

**Issue by juhishaw** [npm/npm#18361]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

tarball.destroy is not a function
ERROR: resoure busy

these two errors are coming whenever i m trying to install anything

i have 100 GB+ space in my drives so resource cannot be an issue

please give a solution soon

**Comment by ghost** [comment]
Hi there, could you provide more information about your problem?

**Comment by juhishaw** [comment]
I was trying to install web pack and angular-cli

They both aren't installing and reason which is shown on cmd is
ERROR:resource lock or busy
