### ISSUE TITLE
I couldn't install anything with "npm". Can anyone help me out?

### ISSUE THREAD

**Issue by masresha** [npm/npm#18360]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'gulp' ]
2 info using npm@3.10.10
3 info using node@v6.9.5
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData gulp
8 silly fetchNamedPackageData gulp
9 silly mapToRegistry name gulp
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry http://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'gulp',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'gulp',
12 silly mapToRegistry   name: 'gulp',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri http://registry.npmjs.org/gulp
14 verbose request uri http://registry.npmjs.org/gulp
15 verbose request no auth needed
16 info attempt registry request try #1 at 9:13:20 AM
17 verbose request id d29aa81419fafab4
18 http request GET http://registry.npmjs.org/gulp
19 info retry will retry, error on last attempt: Error: Invalid protocol: 10.100.7.2:
20 info attempt registry request try #2 at 9:13:30 AM
21 http request GET http://registry.npmjs.org/gulp
22 info retry will retry, error on last attempt: Error: Invalid protocol: 10.100.7.2:
23 info attempt registry request try #3 at 9:14:30 AM
24 http request GET http://registry.npmjs.org/gulp
25 silly fetchPackageMetaData Error: Invalid protocol: 10.100.7.2:
25 silly fetchPackageMetaData     at Request.init (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\request.js:460:31)
25 silly fetchPackageMetaData     at new Request (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\request.js:129:8)
25 silly fetchPackageMetaData     at request (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\index.js:55:10)
25 silly fetchPackageMetaData     at CachingRegistryClient.makeRequest (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:158:13)
25 silly fetchPackageMetaData     at C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:66:17
25 silly fetchPackageMetaData     at RetryOperation._fn (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\attempt.js:18:5)
25 silly fetchPackageMetaData     at Timeout._onTimeout (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-registry-client\node_modules\retry\lib\retry_operation.js:68:10)
25 silly fetchPackageMetaData     at ontimeout (timers.js:365:14)
25 silly fetchPackageMetaData     at tryOnTimeout (timers.js:237:5)
25 silly fetchPackageMetaData     at Timer.listOnTimeout (timers.js:207:5)
25 silly fetchPackageMetaData  error for gulp Error: Invalid protocol: 10.100.7.2:
25 silly fetchPackageMetaData     at Request.init (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\request.js:460:31)
25 silly fetchPackageMetaData     at new Request (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\request.js:129:8)
25 silly fetchPackageMetaData     at request (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\index.js:55:10)
25 silly fetchPackageMetaData     at CachingRegistryClient.makeRequest (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:158:13)
25 silly fetchPackageMetaData     at C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:66:17
25 silly fetchPackageMetaData     at RetryOperation._fn (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\attempt.js:18:5)
25 silly fetchPackageMetaData     at Timeout._onTimeout (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-registry-client\node_modules\retry\lib\retry_operation.js:68:10)
25 silly fetchPackageMetaData     at ontimeout (timers.js:365:14)
25 silly fetchPackageMetaData     at tryOnTimeout (timers.js:237:5)
25 silly fetchPackageMetaData     at Timer.listOnTimeout (timers.js:207:5)
26 silly rollbackFailedOptional Starting
27 silly rollbackFailedOptional Finishing
28 silly runTopLevelLifecycles Finishing
29 silly install printInstalled
30 verbose stack Error: Invalid protocol: 10.100.7.2:
30 verbose stack     at Request.init (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\request.js:460:31)
30 verbose stack     at new Request (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\request.js:129:8)
30 verbose stack     at request (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\index.js:55:10)
30 verbose stack     at CachingRegistryClient.makeRequest (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:158:13)
30 verbose stack     at C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:66:17
30 verbose stack     at RetryOperation._fn (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\attempt.js:18:5)
30 verbose stack     at Timeout._onTimeout (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-registry-client\node_modules\retry\lib\retry_operation.js:68:10)
30 verbose stack     at ontimeout (timers.js:365:14)
30 verbose stack     at tryOnTimeout (timers.js:237:5)
30 verbose stack     at Timer.listOnTimeout (timers.js:207:5)
31 verbose cwd C:\Users\Masreshats\Desktop\AE
32 error Windows_NT 6.1.7601
33 error argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "gulp"
34 error node v6.9.5
35 error npm  v3.10.10
36 error Invalid protocol: 10.100.7.2:
37 error If you need help, you may report this error at:
37 error     <https://github.com/npm/npm/issues>
38 verbose exit [ 1, true ]

**Comment by MrBenJ** [comment]
Can you be a little bit more specific on what you're trying to do and what command you ran that produced this output?

**Comment by masresha** [comment]
I run the commamd npm install -g gulp
I wanted to install gulp package into my angular project. Can u please help

**Comment by MrBenJ** [comment]
@masresha - I am not familiar with reading npm logs, as this is my first time helping out with this repository, so please excuse me if I am wrong.

From reading the log you posted earlier and the command you're using, you may be running into 1 of 2 things:

1. It looks like your computer is having trouble connecting to npm. Maybe check your internet connection and see if you are able to ping https://registry.npm.org

2. You may be running into an EACCESS error, which means your npm permissions are not set correctly. This is a very common issue when attempting to install packages globally. Please follow the instructions at this url: https://docs.npmjs.com/getting-started/fixing-npm-permissions

Hope this helps!
