### ISSUE TITLE
Installed Truffle using npm install ; Getting self certificate error

### ISSUE THREAD

**Issue by sfcadhiraj** [npm/npm#18369]
I installed Truffle using:
npm install -g truffle
But, while executing truffle init, I am getting following error:

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: self signed certificate in certificate chain
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:610:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)

Please suggest!
Note: I am using cmd , since there is a limitation on using powershell.

**Comment by husky-parul** [comment]
Has anyone figured out how to fix this issue? I installed truffle and checked the version.

`INV-PSINGH1-MBP:voting-app-2 singh.p$ truffle version Truffle v3.4.11 (core: 3.4.11) Solidity v0.4.15 (solc-js) `

But when I try to do truffle init, I get the following error

`INV-PSINGH1-MBP:voting-app-2 singh.p$ truffle init events.js:160 throw er; // Unhandled 'error' event ^ Error: self signed certificate in certificate chain at Error (native) at TLSSocket.<anonymous> (_tls_wrap.js:1092:38) at emitNone (events.js:86:13) at TLSSocket.emit (events.js:185:7) at TLSSocket._finishInit (_tls_wrap.js:610:8) at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)`

Can someone help me on this
