### ISSUE TITLE
npm ERR! code EINTEGRITY

### ISSUE THREAD

**Issue by JayRajM97** [npm/npm#18381]
npm install
npm WARN @angular/platform-server@4.0.3 requires a peer of @angular/animations@4.0.3 but none was installed.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: js-yaml@3.7.0 (node_modules\js-yaml):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, utime 'C:\Windows\System32\angular2-seed\node_modules\.staging\js-yaml-d016ede9\dist\js-yaml.js'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: postcss@6.0.10 (node_modules\postcss-modules-values\node_modules\postcss):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, utime 'C:\Windows\System32\angular2-seed\node_modules\.staging\postcss-c3910137\lib\node.js'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: micromatch@2.3.11 (node_modules\http-proxy-middleware\node_modules\micromatch):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, utime 'C:\Windows\System32\angular2-seed\node_modules\.staging\micromatch-23301a2f\README.md'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sockjs-client@1.1.2 (node_modules\sockjs-client):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, utime 'C:\Windows\System32\angular2-seed\node_modules\.staging\sockjs-client-8b9e513b\dist\sockjs.min.js'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: postcss@6.0.10 (node_modules\postcss-modules-extract-imports\node_modules\postcss):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, utime 'C:\Windows\System32\angular2-seed\node_modules\.staging\postcss-1aaab318\docs\source-maps.md'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: postcss@6.0.10 (node_modules\postcss-modules-local-by-default\node_modules\postcss):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, utime 'C:\Windows\System32\angular2-seed\node_modules\.staging\postcss-cdf17e6b\lib\parser.js'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: postcss@5.2.17 (node_modules\postcss):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, utime 'C:\Windows\System32\angular2-seed\node_modules\.staging\postcss-4b5b3078\lib\node.js'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: tsickle@0.21.6 (node_modules\tsickle):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, utime 'C:\Windows\System32\angular2-seed\node_modules\.staging\tsickle-5ed8dcfb\build\src\tsickle.js'

npm ERR! code EINTEGRITY
npm ERR! sha1-FwsY1a9O4Cskiqah8eBYSshBaB4= integrity checksum failed when using sha1: wanted sha1-FwsY1a9O4Cskiqah8eBYSshBaB4= but got sha1-1WN9sU/Q2yzUNzGGcsfjOnqnn2c=. (31354 bytes)

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\MyPc\AppData\Roaming\npm-cache\_logs\2017-09-02T13_41_11_636Z-debug.log

**Comment by ghost** [comment]
hi, i run into the issue just now
```
 ± npm install
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN eslint-plugin-import@2.7.0 requires a peer of eslint@2.x - 4.x but none was installed.
npm WARN patfe@1.0.0 No description
npm WARN patfe@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: request@2.81.0 (node_modules/request):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, utime '/Users/liuliang/Desktop/project/pat-fe/patfe/node_modules/.staging/request-e91b8623/CHANGELOG.md'

npm ERR! code EINTEGRITY
npm ERR! sha1-vLQEXI3QU5wTS8FIjN0+dop6nlE= integrity checksum failed when using sha1: wanted sha1-vLQEXI3QU5wTS8FIjN0+dop6nlE= but got sha1-0stMcLQlSd9eXl9rgbihvCJ1/ZM=. (435202 bytes)

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/liuliang/.npm/_logs/2017-09-03T04_53_50_972Z-debug.log

```
[npm debug gist link](https://gist.githubusercontent.com/liuliangsir/e68c47849ad67f56285e47d1d0775a5e/raw/b9121ea73168d041b180109f88f58585af26276a/npm-debug-info.log)

**Comment by zatamine** [comment]
Duplicate issue, see [16861](https://github.com/npm/npm/issues/16861)

**Comment by zatamine** [comment]
Duplicate issue, see [16861](https://github.com/npm/npm/issues/16861)
