### ISSUE TITLE
`npm update` always updates package.json, ignoring --save flag

### ISSUE THREAD

**Issue by gschulze** [npm/npm#18386]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

`npm update` is always updating the package.json file, regardless of whether the **--save** flag is specified or not. According to the docs (https://docs.npmjs.com/cli/update), updates should only be recorded when the **--save** flag has been specified.

#### How can the CLI team reproduce the problem?

1. Setup an example project with a minimal **package.json** file:

```json
{
  "name": "test",
  "version": "1.0.0",
  "dependencies": {
    "lodash": "4.17.0"
  }
}
```

2. Run `npm i --no-package-lock`. **lodash** should now be installed with version **4.17.0**.

3. Modify **package.json** to include a tilde-range constraint:

```json
{
  "name": "test",
  "version": "1.0.0",
  "dependencies": {
    "lodash": "~4.17.0"
  }
}
```

4. Run `npm update --no-package-lock`. **lodash** should now be installed with the latest patch version, **4.17.4** at the time of writing. However, **package.json** is modified too:

```json
{
  "name": "test",
  "version": "1.0.0",
  "dependencies": {
    "lodash": "^4.17.4"
  }
}
```

If this is the intended behavior, the docs should be updated and the **--save** flag removed. Otherwise, this might be a bug in **npm-update**.

### supporting information:

 - `npm -v` prints: 5.4.0
 - `node -v` prints: 6.11.2
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux, Debian
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by gschulze** [comment]
Seems like providing a **--no-save** option to `npm update` produces the desired behavior. However, this isn't documented in the documentation for the **update** command.

**Comment by kenany** [comment]
@gschulze What is the result of `npm config get save`? It seems like you have that set to `true`, hence the `--save` flag is always enabled.

**Comment by gschulze** [comment]
@KenanY Indeed, `npm config get save` prints `true`, but I didn't touch any of the default configuration values. The relevant section of `npm config ls -l` prints

```
save = true
save-bundle = false
save-dev = false
save-exact = false
save-optional = false
save-prefix = "^"
save-prod = false
```

**Comment by kenany** [comment]
@gschulze The default changed to `true` in `npm@5` (see <https://github.com/npm/npm/releases/tag/v5.0.0>).

**Comment by gschulze** [comment]
@KenanY Ok, thanks for the clarification! In that case, I think the docs at https://docs.npmjs.com/cli/update should be updated to point out the new default behavior.

**Comment by mistic100** [comment]
This page is outdated too https://docs.npmjs.com/misc/config

**Comment by aciccarello** [comment]
I think this should be reopened until the documentation is corrected.
