### ISSUE TITLE
nmp problem with bower?

### ISSUE THREAD

**Issue by MiloshN** [npm/npm#18387]
#### I'm opening this issue because:

  - [ ] npm is doing something I don't understand.

#### What's going wrong?

When i want to download packet i get this message : 

`npm WARN deprecated bower@1.8.0: ..psst! While Bower is maintained, we recommend Yarn and Webpack for *new* front-end projects! Yarn's advantage is security and reliability, and Webpack's is support for both CommonJS and AMD projects. Currently there's no migration path, but please help to create it: https://github.com/bower/bower/issues/2467
` 

How to fix it?

**Comment by alundiak** [comment]
It's well known issue. Bower is going to die. So all => yarn. For my work projects, we use explicit installation of 1.5.x version. But here, I also tried  to install locally, and now it says always.

**Comment by kenany** [comment]
There's nothing to "fix" here. The `bower` package is deprecated, so `npm` prints the assigned deprecation message. As far as I can tell, `npm` is working as intended here.
