### ISSUE TITLE
git@github.com:google-cloud/vision Permission denied

### ISSUE THREAD

**Issue by JohnReedLOL** [npm/npm#18390]
I am trying to follow the advice in: https://cloud.google.com/vision/docs/reference/libraries#client-libraries-install-nodejs

username@laptop:$ sudo npm install
username@laptop:$
username@laptop:$ sudo npm install --save @google-cloud/vision
npm ERR! git clone git@github.com:google-cloud/vision Cloning into bare repository '/home/johnreed/.npm/_git-remotes/git-github-com-google-cloud-vision-41bc45c9'...
npm ERR! git clone git@github.com:google-cloud/vision Permission denied (publickey).
npm ERR! git clone git@github.com:google-cloud/vision fatal: Could not read from remote repository.
npm ERR! git clone git@github.com:google-cloud/vision 
npm ERR! git clone git@github.com:google-cloud/vision Please make sure you have the correct access rights
npm ERR! git clone git@github.com:google-cloud/vision and the repository exists.
npm ERR! addLocal Could not install google-cloud/vision
npm ERR! Error: ENOENT, stat 'google-cloud/vision'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.2.0-27-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "--save" "@google-cloud/vision"
npm ERR! cwd /home/johnreed/workspace/project2/node-js-getting-started
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! path google-cloud/vision
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/johnreed/workspace/project2/node-js-getting-started/npm-debug.log
npm ERR! not ok code 0
username@laptop:$

$ cat /home/username/workspace/project2/node-js-getting-started/npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   '@google-cloud/vision' ]
2 info using npm@1.4.21
3 info using node@v0.10.25
4 verbose readDependencies using package.json deps
5 verbose cache add [ '@google-cloud/vision', null ]
6 verbose cache add name=undefined spec="@google-cloud/vision" args=["@google-cloud/vision",null]
7 verbose parsed url { protocol: null,
7 verbose parsed url   slashes: null,
7 verbose parsed url   auth: null,
7 verbose parsed url   host: null,
7 verbose parsed url   port: null,
7 verbose parsed url   hostname: null,
7 verbose parsed url   hash: null,
7 verbose parsed url   search: null,
7 verbose parsed url   query: null,
7 verbose parsed url   pathname: '@google-cloud/vision',
7 verbose parsed url   path: '@google-cloud/vision',
7 verbose parsed url   href: '@google-cloud/vision' }
8 verbose cache add name="" spec="google-cloud/vision" args=["","google-cloud/vision"]
9 verbose parsed url { protocol: null,
9 verbose parsed url   slashes: null,
9 verbose parsed url   auth: null,
9 verbose parsed url   host: null,
9 verbose parsed url   port: null,
9 verbose parsed url   hostname: null,
9 verbose parsed url   hash: null,
9 verbose parsed url   search: null,
9 verbose parsed url   query: null,
9 verbose parsed url   pathname: 'google-cloud/vision',
9 verbose parsed url   path: 'google-cloud/vision',
9 verbose parsed url   href: 'google-cloud/vision' }
10 silly lockFile d5a09ed3-google-cloud-vision google-cloud/vision
11 verbose lock google-cloud/vision /home/johnreed/.npm/d5a09ed3-google-cloud-vision.lock
12 info maybeGithub Attempting google-cloud/vision from git://github.com/google-cloud/vision
13 silly lockFile 722b1f98-t-github-com-google-cloud-vision git://github.com/google-cloud/vision
14 verbose lock git://github.com/google-cloud/vision /home/johnreed/.npm/722b1f98-t-github-com-google-cloud-vision.lock
15 verbose addRemoteGit [ 'git://github.com/google-cloud/vision', 'master' ]
16 verbose git clone git://github.com/google-cloud/vision Cloning into bare repository '/home/johnreed/.npm/_git-remotes/git-github-com-google-cloud-vision-722b1f98'...
16 verbose git clone git://github.com/google-cloud/vision fatal: remote error:
16 verbose git clone git://github.com/google-cloud/vision   Repository not found.
17 silly lockFile 722b1f98-t-github-com-google-cloud-vision git://github.com/google-cloud/vision
18 silly lockFile 722b1f98-t-github-com-google-cloud-vision git://github.com/google-cloud/vision
19 info maybeGithub Attempting google-cloud/vision from git+ssh://git@github.com:google-cloud/vision
20 silly lockFile 41bc45c9-t-github-com-google-cloud-vision git@github.com:google-cloud/vision
21 verbose lock git@github.com:google-cloud/vision /home/johnreed/.npm/41bc45c9-t-github-com-google-cloud-vision.lock
22 verbose addRemoteGit [ 'git@github.com:google-cloud/vision', 'master' ]
23 error git clone git@github.com:google-cloud/vision Cloning into bare repository '/home/johnreed/.npm/_git-remotes/git-github-com-google-cloud-vision-41bc45c9'...
23 error git clone git@github.com:google-cloud/vision Permission denied (publickey).
23 error git clone git@github.com:google-cloud/vision fatal: Could not read from remote repository.
23 error git clone git@github.com:google-cloud/vision
23 error git clone git@github.com:google-cloud/vision Please make sure you have the correct access rights
23 error git clone git@github.com:google-cloud/vision and the repository exists.
24 silly lockFile 41bc45c9-t-github-com-google-cloud-vision git@github.com:google-cloud/vision
25 silly lockFile 41bc45c9-t-github-com-google-cloud-vision git@github.com:google-cloud/vision
26 silly lockFile d5a09ed3-google-cloud-vision google-cloud/vision
27 silly lockFile d5a09ed3-google-cloud-vision google-cloud/vision
28 error addLocal Could not install google-cloud/vision
29 error Error: ENOENT, stat 'google-cloud/vision'
30 error If you need help, you may report this *entire* log,
30 error including the npm and node versions, at:
30 error     <http://github.com/npm/npm/issues>
31 error System Linux 4.2.0-27-generic
32 error command "/usr/bin/nodejs" "/usr/bin/npm" "install" "--save" "@google-cloud/vision"
33 error cwd /home/johnreed/workspace/project2/node-js-getting-started
34 error node -v v0.10.25
35 error npm -v 1.4.21
36 error path google-cloud/vision
37 error code ENOENT
38 error errno 34
39 verbose exit [ 34, true ]
$

Ubuntu version:

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 15.10
Release:	15.10
Codename:	wily

**Comment by JohnReedLOL** [comment]
What's going wrong?

I have no idea. I just got all that error output.

How can the CLI team reproduce the problem?

Go to https://cloud.google.com/vision/docs/reference/libraries#client-libraries-install-nodejs with a base Node Heroku project like https://github.com/heroku/node-js-getting-started and do "npm install --save @google-cloud/vision".

Supporting information:

npm -v prints:

$ npm -v prints
5.4.0

node -v prints:

$ node -v prints
v6.11.2

npm config get registry prints:

$ npm config get registry
https://registry.npmjs.org/

Windows, OS X/macOS, or Linux?:

- Ubuntu 15.10

Network issues:

- None

Geographic location where npm was run:

- US

No proxy/VPN. No Docker. Code deploys to Heroku.

**Comment by kenany** [comment]
Hmm, the debug log says you're running Node.js v0.10 and `npm@1.4` (which are years old and no longer supported), but you say it's Node.js v6 and `npm@5`. Do you have an error log where the Node.js and `npm` versions are those latter ones you mentioned?

**Comment by JohnReedLOL** [comment]
My laptop is old. When I skip the laptop and push straight to Travis CI, I get: https://gist.github.com/JohnReedLOL/f829670d6ce8128f83a36babb55cf204

**Comment by kenany** [comment]
@JohnReedLOL Sorry, but where's the error in that new log?

**Comment by JohnReedLOL** [comment]
This is going to sound pretty stupid, but the way I'm doing development is I am pushing straight to GitHub and letting the CI work out all the bugs for me without ever running it on localhost. 

The terminal command "npm install --save @google-cloud/vision" didn't run on my laptop but did run on the Travis CI. Now I have dependencies "@google-cloud/vision": "^0.12.0" added to my list of dependencies. Can I just add that line into the package.json and call it a day?

**Comment by JohnReedLOL** [comment]
I don't see any error. I think it works.
