### ISSUE TITLE
Refusing to install webdriverio as a dependency of itself

### ISSUE THREAD

**Issue by PrasannaGumpalli** [npm/npm#18391]
When I’m running the command “npm install --save-dev webdriverio” it’s throwing the following error. Please anyone can help me resolve this issue. Thanks.

npm ERR! Darwin 16.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save-dev" "webdriverio"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ENOSELF

npm ERR! Refusing to install webdriverio as a dependency of itself
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/vn0uxvk/webdriverio/npm-debug.log

**Comment by kenany** [comment]
@PrasannaGumpalli Ensure that the `"name"` field in your `package.json` is not set to `"webdriverio"`. Try setting it to something more unique :)

**Comment by PrasannaGumpalli** [comment]
@KenanY Thank you very much. It’s working when I changed the “name” field in “package.json” file.
