### ISSUE TITLE
Npm installation error

### ISSUE THREAD

**Issue by ThomasMout** [npm/npm#18409]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Npm can't install the bcrypt module. I get this error:

, stderr: npm WARN lifecycle npm is using /opt/plesk/node/7/bin/node but there is no node binary in the current PATH. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
/usr/bin/env: 'node': No such file or directory
npm WARN tournament-center-api@1.0.0 No description
npm WARN tournament-center-api@1.0.0 No repository field.
npm ERR! Linux 4.4.0-042stab123.8
npm ERR! argv "/opt/plesk/node/7/bin/node" "/opt/plesk/node/7/bin/npm" "install"
npm ERR! node v7.4.0
npm ERR! npm v4.0.5
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! bcrypt@1.0.3 install: `node-pre-gyp install --fallback-to-build`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the bcrypt@1.0.3 install script 'node-pre-gyp install --fallback-to-build'.

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by ayushmankd** [comment]
It seems there isn't any npm package name "bycrypt".

**Comment by ThomasMout** [comment]
I'm sorry, it's the bcrypt module (not the bycrypt module). The project does work offline, but when it's deployed to a server I get this error.

**Comment by ayushmankd** [comment]
Well,Have you installed the required dependencies?
i.e. Is the module listed on your package.json file?

**Comment by ThomasMout** [comment]
Yes I do, as I mentioned earlier everything works fine on my local machine. Only when it's deployed to a server this error appears.

**Comment by secretyouth** [comment]
@ThomasMout I'm also experiencing a similar issue and been beating my head against a wall for some time...

Failed at the bcrypt@1.0.3 install script 'node-pre-gyp install --fallback-to-build'.

**Comment by ThomasMout** [comment]
I've found an solution. Use bcrypt-js instead of bcrypt.
