### ISSUE TITLE
unable to install node modules

### ISSUE THREAD

**Issue by TejaswiChava** [npm/npm#18405]
tarball.destroy is not a function

**Comment by kenany** [comment]
@TejaswiChava Could you please provide some more information, like Node.js version, `npm` version, and operating system? Can you upload a debug log to <https://gist.github.com/> and link it here? Thanks!

**Comment by rjyagono** [comment]
hi Guys,

I have same issue here is the log.

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\dev\AppData\Local\Temp\npm-3536-46cdbd52\registry.npmjs.org\hash.js\-\hash.js-1.1.3.tgz.44355770' -> 'C:\Users\dev\AppData\Local\Temp\npm-3536-46cdbd52\registry.npmjs.org\hash.js\-\hash.js-1.1.3.tgz'

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10

**Comment by kenany** [comment]
Closing as abandoned.
