### ISSUE TITLE
tring to use npm and node... :(

### ISSUE THREAD

**Issue by GioMBG** [npm/npm#18402]
#### I'm opening this issue because:

  - [ x ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ x ] npm is doing something I don't understand.
  - [  ] Other (_see below for feature requests_):

#### What's going wrong?

[root@homeGioMBG app]# npm start
npm ERR! Error: ENOENT, open '/var/www/html/delta/app/package.json'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.4.14-200.fc22.x86_64
npm ERR! command "node" "/bin/npm" "start"
npm ERR! cwd /var/www/html/delta/app
npm ERR! node -v v0.10.42
npm ERR! npm -v 1.3.6
npm ERR! path /var/www/html/delta/app/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /var/www/html/delta/app/npm-debug.log
npm ERR! not ok code 0
[root@homeGioMBG app]# cat /var/www/html/delta/app/npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/bin/npm', 'start' ]
2 info using npm@1.3.6
3 info using node@v0.10.42
4 verbose node symlink /bin/node
5 error Error: ENOENT, open '/var/www/html/delta/app/package.json'
6 error If you need help, you may report this log at:
6 error     <http://github.com/isaacs/npm/issues>
6 error or email it to:
6 error     <npm-@googlegroups.com>
7 error System Linux 4.4.14-200.fc22.x86_64
8 error command "node" "/bin/npm" "start"
9 error cwd /var/www/html/delta/app
10 error node -v v0.10.42
11 error npm -v 1.3.6
12 error path /var/www/html/delta/app/package.json
13 error code ENOENT
14 error errno 34
15 verbose exit [ 34, true ]
[root@homeGioMBG app]#
[root@homeGioMBG app]#
[root@homeGioMBG app]#
[root@homeGioMBG app]# node index.js

/var/www/html/delta/app/index.js:14
console.log(`The result is: ${result}`)
            ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
[root@homeGioMBG app]#
[root@homeGioMBG app]#
[root@homeGioMBG app]#
[root@homeGioMBG app]# cat calc.js
// app/calc.js
function sum (arr) {  
  return arr.reduce(function(a, b) {
    return a + b
  }, 0)
}

module.exports.sum = sum
[root@homeGioMBG app]# 

#### How can the CLI team reproduce the problem?

mayve fedora x86_64

### supporting information:

 - `npm -v` prints: 1.3.6
 - `node -v` prints: v0.10.42
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux Fedora
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
@GioMBG Sorry, but your versions of Node.js and `npm` are years old and are no longer supported.

**Comment by GioMBG** [comment]
Hi Staff,
That's exactly what should pay your attention, 
I've install the packages YESTERDAY with Fedora dnf (yum)...
Gio
--
Il giorno mar, 05/09/2017 alle 01.17 +0000, Kenan Yildirim ha scritto:
> @GioMBG Sorry, but your versions of Node.js and npm are years old and are no
> longer supported.
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
-- 
GioMBG sarl
Giorgio Canepa
http://giombg.eu
https://www.facebook.com/giorgio.canepa
https://plus.google.com/u/0/+GiorgioCanepaMBG
https://twitter.com/GioMBG

**Comment by kenany** [comment]
@GioMBG The npm team does not manage the npm packages of any distro. You should contact the maintainers of the outdated package.
