### ISSUE TITLE
Error Occurred when executing command: npm run tsc:w

### ISSUE THREAD

**Issue by iss-llc** [npm/npm#18411]
![errorlog](https://user-images.githubusercontent.com/31675664/30089188-3feeae42-9279-11e7-9f90-6f11c5a371c2.GIF)

#### I'm opening this issue because:

  - [x ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints: 3.10.3
 - `node -v` prints: v6.3.0
 - `npm config get registry` prints: https://registry.npmjs.org

 - Windows, OS X/macOS, or Linux?: Windows

 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
@iss-llc This error is _not_ coming from `npm`. Your `"start"` script is throwing an error, and all `npm` is doing here is letting you know that the command failed.
