### ISSUE TITLE
Refusing to install request as a dependency of itself

### ISSUE THREAD

**Issue by KuppulakshmiA** [npm/npm#18416]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KuppulakshmiA** [comment]
I tried to install request **npm install request** but it shows the Error

ERR! Refusing to install request as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/softsquare/Desktop/untitled folder/Request/npm-debug.log
KL-Mac-Mini:Request softsquare$ npm install request --save --save-exact
npm ERR! Darwin 14.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "request" "--save" "--save-exact"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ENOSELF

npm ERR! Refusing to install request as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/softsquare/Desktop/untitled folder/Request/npm-debug.log

Any one know about this.

**Comment by yeshwanthyeshu** [comment]
Rename the folder in which you want to install express.
The name should not start with  the word 'express'.
If the name starts with 'express', npm takes it as a dependency and that's why refusing.
I hope this will help to solve your problem

**Comment by KuppulakshmiA** [comment]
Thanks. The issue is  I set the project name as "request" 
{
  "name": "request",
  "version": "1.0.0",
  "description": "'",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "ejs": "2.5.7",
    "express": "4.15.4",
  }
}
Now I change the name 
{
  "name": "demo",
  "version": "1.0.0",
  "description": "'",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "ejs": "2.5.7",
    "express": "4.15.4",
    "request": "2.81.0"
  }
}
Now request installed. Thanks for your suggestion Yeshwant
