### ISSUE TITLE
`npm@5.4.0 install` crash installing some modules

### ISSUE THREAD

**Issue by HollyPony** [npm/npm#18417]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Npm 5.4.0 && 5.4.1 crash installing some modules throwing a `Cannot read property "x" of undefined`. 

#### How can the CLI team reproduce the problem?

Execute this in a clean folder: `npx npm@5.4 i messageformat@0.3.1`

Log file : https://gist.github.com/HollyPony/53842ff739c778d0dd29c0f77b4e1250

#### Additional information

There is no errors with 
- node@0.10 && npm3
- node@6 && npm4
- node 8.4 && npm5.3
It look like the error come from typechecker while there is multiple versions as dependencies / subdependencies and some of them use a `"preinstall": "node ./cyclic.js"`

### supporting information:

 - `npm -v` prints: 5.4
 - `node -v` prints: 8.4
 - `npm config get registry` prints: Tested with custom and officiel repos
 - Windows, OS X/macOS, or Linux?: OSX

**Comment by Mds92** [comment]
I have a same issue
https://stackoverflow.com/questions/46020018/error-eperm-operation-not-permitted-unlink-d-sources-node-modules-fseven

**Comment by simonua** [comment]
Same issues here (albeit different modules). We guide to use 5.3.0 for the time being and not upgrade in our organization.

**Comment by HollyPony** [comment]
Reproduce with 5.4.1

**Comment by robv8r** [comment]
Possible duplicate of #18380

**Comment by Mds92** [comment]
If you downgrade to 5.3 and still get the same error in Windows like me.
After hours working with npm versions I found the following solution:

https://stackoverflow.com/a/46113451/191647

**Comment by HollyPony** [comment]
Still present in 5.4.2

**Comment by robv8r** [comment]
5.4.2 works for me on Windows. @HollyPony please provide more information about what you're experiencing.

**Comment by HollyPony** [comment]
This is happening with the 0.3.1 version of messageformat. 

![screen shot 2017-09-18 at 09 10 50](https://user-images.githubusercontent.com/6191228/30531931-9c5903c6-9c51-11e7-8a3a-3deb3f02f23a.png)

I've also try installing npm globally, same result

**Comment by robv8r** [comment]
Can you attach the log from the second to last line of your screenshot?

**Comment by HollyPony** [comment]
I cannot for this screenshot but I can reproduce: 

![screen shot 2017-09-22 at 20 57 18](https://user-images.githubusercontent.com/6191228/30759996-b139b7ba-9fd8-11e7-80d8-7391362ffc86.png)

And attach the complete log:

[2017-09-22T18_55_56_565Z-debug.log.zip](https://github.com/npm/npm/files/1325545/2017-09-22T18_55_56_565Z-debug.log.zip)

**Comment by boutell** [comment]
At least for the i18n module, this is fixed in 5.5.x. If you still have this problem with one or more modules please test in npm 5.5.x and report your results.

**Comment by HollyPony** [comment]
I confirm, npm works great again 👍 . Thanks to all !
