### ISSUE TITLE
unable to install grunt of bootstrap

### ISSUE THREAD

**Issue by chaoMaster** [npm/npm#18413]
#### when I execute 'npm install' on bootstrap folder, and it show me these log:

➜  ~/static/node_modules/bootstrap npm install     
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated minimatch@0.2.12: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated node-uuid@1.4.0: Use uuid module instead
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/Cellar/node/5.5.0/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.5.0
npm ERR! npm  v3.5.3

npm ERR! Cannot read property 'target' of null
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     ~/static/node_modules/bootstrap/npm-debug.log

#### npm-debug.log

https://gist.github.com/chaoMaster/b5117c9cce87ac08d94bd00e65916932

### supporting information:

 - `npm -v` prints: v3.5.3
 - `node -v` prints: v5.5.0
 - `npm config get registry` prints: https://registry.npm.taobao.org/
 - Windows, OS X/macOS, or Linux?: macOS

**Comment by kenany** [comment]
@chaoMaster Does this also occur with Node.js v6 (or v8) alongside `npm@5`?

**Comment by chaoMaster** [comment]
Okay, I'll try it

**Comment by kenany** [comment]
Closing as abandoned.
