### ISSUE TITLE
Unable to install protractor through cmd prompt

### ISSUE THREAD

**Issue by suria25** [npm/npm#18432]
C:\Users\1072576\AppData\Roaming\npm>npm install -g protractor
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "protractor"
npm ERR! node v7.7.2
npm ERR! npm  v4.1.2

npm ERR! Cannot read property 'path' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\1072576\AppData\Roaming\npm\npm-debug.log

**Comment by kenany** [comment]
@suria25 Does this also occur with newer versions of `npm`? Could you upload the _full_ debug log file as plaintext to <https://gist.github.com/> and link it here? Thanks!

**Comment by kenany** [comment]
Closing as abandoned.
