### ISSUE TITLE
npm install stuck at extract:core-js

### ISSUE THREAD

**Issue by saumyatripathi** [npm/npm#18448]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

npm install has been stuck at `extract:core-js: verb gentlyRm don't care about contents; nuking D:\...\node_modules\.staging\core-js-871d187b\node_modules` for about 20 minutes on a Windows Server. Started off with npm version 3.10.10. I later tried 3.10.3 but the issue persists. My CPU utilization is 100% while this happens. It does eventually complete. I have been doing some of the debugging off of this issue - #13782 

#### How can the CLI team reproduce the problem?

Not sure if it's easily reproducible. I got into this issue last week on the build server before which the same thing has been working perfectly. Please use the below package.json and try npm install with it.

```
"dependencies": {
    "@angular/animations": "^4.3.3",
    "@angular/cdk": "^2.0.0-beta.10",
    "@angular/common": "^4.3.3",
    "@angular/compiler": "^4.3.3",
    "@angular/core": "^4.3.3",
    "@angular/forms": "^4.3.3",
    "@angular/http": "^4.3.3",
    "@angular/material": "^2.0.0-beta.8",
    "@angular/platform-browser": "^4.3.3",
    "@angular/platform-browser-dynamic": "^4.3.3",
    "@angular/router": "^4.3.3",
    "ag-grid": "^12.0.2",
    "ag-grid-angular": "^12.0.0",
    "core-js": "^2.4.1",
    "font-awesome": "^4.7.0",
    "jquery": "^3.2.1",
    "material-design-icons": "^3.0.1",
    "moment": "^2.18.1",
    "moment-business": "^3.0.1",
    "primeng": "^4.1.2",
    "rxjs": "^5.4.2",
    "signalr": "^2.2.2",
    "zone.js": "^0.8.16"
  },
  "devDependencies": {
    "@angular/cli": "1.1.2",
    "@angular/compiler-cli": "^4.0.0",
    "@angular/language-service": "^4.0.0",
    "@types/jasmine": "2.5.45",
    "@types/jquery": "^3.2.10",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.0.4",
    "tslint": "~5.3.2",
    "typescript": "~2.3.3"
  }
```

### supporting information:

 - `npm -v` prints: 3.10.3
 - `node -v` prints: 6.6.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows server.
 - Network issues:
   - Geographic location where npm was run: New York
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
@saumyatripathi Does this also occur with `npm@5`?

**Comment by saumyatripathi** [comment]
I haven't tried that yet however I did try adding packages one by one and it turns out that the culprit is "material-design-icons". They have this issue raised at their github and a lot people are facing this issue but unfortunately none of the members/contributors are addressing it. Here's the reference - https://github.com/google/material-design-icons/issues/518.

I plan to subvert this by not using it altogether.
Of course, it would be ideal if one of npm geniuses could figure it out.

Thanks for the help.
Cheers!

**Comment by saumyatripathi** [comment]
@catcher-in-the-try Interesting. I'll try clearing the cache. The way I figured out was getting rid of most of the packages and then adding one or two at a time. It just happened so that after I found out, I also found the issue on material-design-icons repo.

**Comment by Almo7aya** [comment]
I have this issue also, I can't install any package :(

**Comment by azarus** [comment]
@catcher-in-the-try npm hangs on low end vps / machines when installing core js for me.

**Comment by azarus** [comment]
@npm-robot its a bug

**Comment by skozin** [comment]
I'm seeing the same or similar issue:

```
sill pacote core-js@https://registry.npmjs.org/core-js/-/core-js-1.2.7.tgz extracted to /Users/sam/dev/projects/turtle-inc/turtle-chat/node_modules/.staging/core-js-64733aff by content address 3126ms
http fetch GET 200 https://registry.npmjs.org/react-native/-/react-native-0.46.4.tgz 70665ms
sill pacote react-native@https://registry.npmjs.org/react-native/-/react-native-0.46.4.tgz extracted in 70689ms
⸨            ░░░░░░⸩ ⠴ extract:react-native: sill extract babel-runtime@6.26.0
```

It gets stuck there and never finishes on most runs. But sometimes it resumes after 5-10 minutes of waiting.

```
npm --version
5.6.0

node --version
v8.3.0
```

There is no proxy configured. I'm running on a MacBook with two i7 cores and 16 GB of memory, so machine performance shouldn't be an issue. I tried force-clearing npm cache and it didn't help.

**Comment by promanski** [comment]
I've got the same problem as @skozin

**Comment by JoshCheek** [comment]
I hit this issue, too. It was b/c one of the packages listed a dependency on a package with a link to its GitHub using the git protocol:

```
$ jq < node_modules/web3-providers-ws/package.json .dependencies.websocket -r
git://github.com/frozeman/WebSocket-Node.git#browserifyCompatible
```

I got around it by temporarily adding this to my `~/.gitconfig`:

```
[url "https://"]
  insteadOf = git://
```

**Comment by azarus** [comment]
@joshCheek probably memory related. :/

**Comment by promanski** [comment]
Hello guys, I know what was happening (in my case). It was a problem with my local wifi router. I've connected to my smartphone wifi hotspot and everything works ok.

**Comment by asso1985** [comment]
Same problem here. 

Stuck at: 

`loadDevDep:stringify: sill install loadAllDepsIntoIdealTree`

node : v8.9.4
npm 5.6.0

**Comment by echo-gravitas** [comment]
@asso1985 In my case it was not stuck, in fact the command line asked me for my passphrase for my id_rsa but the dialog was not shown. 

So try to type your passphrase and hit enter.

**Comment by ilyaigpetrov** [comment]
Run npm with `-ddd` flag, then you will find out which URL it tries to fetch and stucks. Try accessing this URL in browser and troubleshoot its network accessibility.
