### ISSUE TITLE
When used as a library, installation of packages with prepare script fails

### ISSUE THREAD

**Issue by olydis** [npm/npm#18449]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.

#### What's going wrong?

When using `npm` as a package (to install stuff from within a Node application), installation of packages with `prepare` script fails.

https://github.com/npm/npm/blob/latest/lib/pack.js#L174 is intended and expected to return `npm-cli.js` (essentially in order to do a dev-like `npm install` of a package with `prepare` script). However, this expectation is wrong when `npm` is used as a library. Whichever is the entry point script using `npm` will be returned by `require.main.filename`. As a result a non-sense process is spawned that obviously doesn't do what you expect. If that spawned process has non-zero exit code, the call to npm fails, otherwise it silently finishes but leaves the package in an un"prepare"d state.

#### How can the CLI team reproduce the problem?

Use the `npm` package (from code, not CLI) to install a package that has a prepare script.

### supporting information:

 - `npm@5.4.1` package
 - Windows, but shouldn't matter

**Comment by iarna** [comment]
Hi there, thanks for reporting this but I'm afraid that using  npm as a package is not supported.  We can and will change internal APIs w/o major releases. Supported integration is to call `npm` with `child_process`.

The alternative in the future will be to build off of the libraries that npm is built off of (for example, `pacote` can turn any valid package specifier (eg `module@^1.2.3`, `github:foo/bar`) into a tarball.

**Comment by olydis** [comment]
Thanks for the response and info about pacote! [We](https://github.com/Azure/autorest/) sort of require all `npm` features since we specifically support any `npm` packages (with some additional info) as extensions, which will be acquired and run automatically. But yes, the `child_process` way is of course a fine option 🙂
