### ISSUE TITLE
npm ERR! Windows_NT 6.1.7601  anyone can help? thanks

### ISSUE THREAD

**Issue by Jesseszhang** [npm/npm#18452]
$ npm install
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\                 node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! syscall connect

npm ERR! network connect ETIMEDOUT 74.122.238.10:8080
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin                 gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     E:\github\element\npm-debug.log

it is on windows 7

**Comment by mertcanicten** [comment]
similar here..

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code EBADPLATFORM

**Comment by Jesseszhang** [comment]
use proxy  to fix  the problem
