### ISSUE TITLE
Unable to install nightly build from Github

### ISSUE THREAD

**Issue by ThomasBurleson** [npm/npm#18467]
Using npm 5.4.1, I am trying to install a nightly build from a build-deployment github repository.

Source Respository:  github.com/angular/flex-layout
Build Repository:  github.com/angular/flex-layout-builds

When I run this command:

```bash
npm i github:angular/flex-layout-builds --save
```

I get this error:  

```bash
(node:99637) UnhandledPromiseRejectionWarning: Unhandled promise rejection 
(rejection id: 1): Error: ENOENT: no such file or directory, stat
 '/Users/thomasburleson/.npm/_cacache/tmp/git-clone-baf6d992/angular/flex-layout.es5.js'
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

> Note that the proper path should be `@angular/flex-layout.es5.js` instead of the reported ^ path `angular/flex-layout.es5.js`

----

Here is the debug output:

```bash
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'i',
1 verbose cli   'github:angular/flex-layout-builds',
1 verbose cli   '--save',
1 verbose cli   '--trace-warnings' ]
2 info using npm@5.4.1
3 info using node@v6.11.2
4 verbose npm-session 9b3b4bc87dc03bb3
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 info lifecycle @angular/flex-layout@2.0.0-beta.9-5f198a3~prepack: @angular/flex-layout@2.0.0-beta.9-5f198a3
8 error cb() never called!
9 error This is an error with npm itself. Please report this error at:
10 error <https://github.com/npm/npm/issues>
```

The latest [nightly build](https://github.com/angular/flex-layout-builds/blob/master/package.json) is **2.0.0-beta.9-5f198a3**, yet npm fails. 

Why is this happening ? 
> I believe it has something to do with the `package.json` key/values (see below)

----

#### Package.json

```json
{
  "name": "@angular/flex-layout",
  "version": "2.0.0-beta.9-5f198a3",
  "description": "Angular Flex-Layout",
  "main": "./bundles/flex-layout.umd.js",
  "module": "./@angular/flex-layout.es5.js",
  "es2015": "./@angular/flex-layout.js",
  "typings": "./flex-layout.d.ts",
  "repository": {
    "type": "git",
    "url": "https://github.com/angular/flex-layout.git"
  },
  "keywords": [
    "angular",
    "flex-layout",
    "flexbox css",
    "media query",
    "breakpoints"
  ],
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/angular/flex-layout/issues"
  },
  "homepage": "https://github.com/angular/flex-layout#readme",
  "peerDependencies": {
    "@angular/core": "^4.3.0",
    "@angular/common": "^4.3.0"
  },
  "dependencies": {
    "tslib": "^1.7.1"
  }
}
```

**Comment by WhatzzUp** [comment]
Hai @ThomasBurleson , i had a similar error with angular 2 material and cdk master.

This is what i found out:

**Following path is npm looking for:**

> \npm-cache\_cacache\tmp\git-clone-77114990\angular\flex-layout.es5.js

**but only this path exist on my system:**
> npm-cache\_cacache\tmp\git-clone-77114990\ @angular\flex-layout.es5.js

The different between the two path is "angular" and "@angular".

I have currently no idea how to prevent this error ....

Cheers
Chris

**Comment by MileNanevski** [comment]
@ThomasBurleson I had the same error. Upgrading node from 7.2.1 to 8.4.0 fixed it for me.

**Comment by ThomasBurleson** [comment]
@MileNanevski - That was my solution also.

**Comment by spock123** [comment]
Node 8.9.3, Npm 5.5.1 - I'm having this issue now...  flex-layout beta-12

I believe it's an issue in the package manager - so for people visiting this at a later stage, try regression to older npm versions.

**Comment by ThomasBurleson** [comment]
@spock123 -

* `npm uninstall @angular/flex-layout`
*  delete your `node_modules`
* `npm install`
* `npm install @angular/flex-layout`

> Do not use `npm update`; since it attempts to incorrectly install the invalid rc.1 (which is really beta.6).

Then rebuild...

**Comment by spock123** [comment]
Thank you @ThomasBurleson , I'll give it a shot... cheers
  
Back again - worked perfectly, thanks.
One thing: I had to delete the package-lock.json file as well, otherwise it won't work.
