### ISSUE TITLE
Npm package restore error

### ISSUE THREAD

**Issue by ramil89** [npm/npm#18465]
Hi.
I am using VS 2017 Enterprise 15.3.3.
I am experienced the issue with restoring packages through npm. 
npm version is 3.10.10
node version is 6.11.3

I got the following output:

>PATH=.\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Web\External;%PATH%;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git\cmd;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git\mingw32\bin
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Web\External\npm.CMD" install
npm ERR! fetch failed https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz
npm WARN retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.84.162:443
npm ERR! fetch failed https://registry.npmjs.org/vendors/-/vendors-1.0.1.tgz
npm WARN retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.84.162:443
npm ERR! fetch failed https://registry.npmjs.org/which-module/-/which-module-1.0.0.tgz
npm WARN retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.84.162:443
npm ERR! fetch failed https://registry.npmjs.org/source-map-support/-/source-map-support-0.4.15.tgz
npm WARN retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.84.162:443
npm ERR! fetch failed https://registry.npmjs.org/@ngtools/webpack/-/webpack-1.5.0.tgz
npm WARN retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.84.162:443
npm ERR! fetch failed https://registry.npmjs.org/snapdragon/-/snapdragon-0.8.1.tgz
npm WARN retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.84.162:443
npm ERR! fetch failed https://registry.npmjs.org/which/-/which-1.2.14.tgz
npm WARN retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.84.162:443
npm ERR! fetch failed https://registry.npmjs.org/right-align/-/right-align-0.1.3.tgz
npm WARN retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.84.162:443
npm ERR! fetch failed https://registry.npmjs.org/yargs-parser/-/yargs-parser-4.2.1.tgz
npm WARN retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.84.162:443
npm ERR! fetch failed https://registry.npmjs.org/uniq/-/uniq-1.0.1.tgz
npm WARN retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.84.162:443
npm ERR! fetch failed https://registry.npmjs.org/xml-char-classes/-/xml-char-classes-1.0.0.tgz
npm WARN retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.84.162:443
npm ERR! fetch failed https://registry.npmjs.org/yeast/-/yeast-0.1.2.tgz
npm WARN retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.84.162:443
npm ERR! fetch failed https://registry.npmjs.org/wordwrap/-/wordwrap-0.0.2.tgz
npm WARN retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.84.162:443
npm ERR! fetch failed https://registry.npmjs.org/sax/-/sax-1.2.4.tgz
npm WARN retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.84.162:443
npm ERR! fetch failed https://registry.npmjs.org/window-size/-/window-size-0.1.0.tgz
npm WARN retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.84.162:443
npm ERR! fetch failed https://registry.npmjs.org/@angular/router/-/router-4.2.5.tgz
npm WARN retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.84.162:443
npm ERR! fetch failed https://registry.npmjs.org/@types/chai/-/chai-4.0.1.tgz
npm WARN retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.84.162:443
npm ERR! fetch failed https://registry.npmjs.org/@angular/common/-/common-4.2.5.tgz
npm WARN retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.84.162:443
npm ERR! fetch failed https://registry.npmjs.org/@angular/forms/-/forms-4.2.5.tgz
npm WARN retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.84.162:443
npm ERR! fetch failed https://registry.npmjs.org/@angular/platform-server/-/platform-server-4.2.5.tgz
npm WARN retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.84.162:443
npm ERR! fetch failed https://registry.npmjs.org/@types/jasmine/-/jasmine-2.5.53.tgz
npm WARN retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.84.162:443
npm ERR! fetch failed https://registry.npmjs.org/@angular/compiler-cli/-/compiler-cli-4.2.5.tgz
npm WARN retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.84.162:443
npm ERR! fetch failed https://registry.npmjs.org/@angular/tsc-wrapped/-/tsc-wrapped-4.2.5.tgz
npm WARN retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.84.162:443
npm ERR! fetch failed https://registry.npmjs.org/@angular/http/-/http-4.2.5.tgz
npm WARN retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.84.162:443
npm ERR! fetch failed https://registry.npmjs.org/@angular/core/-/core-4.2.5.tgz
npm WARN retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.84.162:443
npm ERR! fetch failed https://registry.npmjs.org/@types/webpack-env/-/webpack-env-1.13.0.tgz
npm WARN retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.84.162:443
npm ERR! fetch failed https://registry.npmjs.org/@angular/platform-browser/-/platform-browser-4.2.5.tgz
npm WARN retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.84.162:443
npm ERR! fetch failed https://registry.npmjs.org/@angular/compiler/-/compiler-4.2.5.tgz
npm WARN retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.84.162:443
npm ERR! fetch failed https://registry.npmjs.org/@angular/platform-browser-dynamic/-/platform-browser-dynamic-4.2.5.tgz
npm WARN retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.84.162:443
npm ERR! fetch failed https://registry.npmjs.org/@angular/animations/-/animations-4.2.5.tgz
npm WARN retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.84.162:443
npm ERR! tar.unpack unzip error C:\Users\ramil\AppData\Local\Temp\npm-8556-bee4b83b\registry.npmjs.org\_40angular\router\-\router-4.2.5.tgz
npm ERR! tar.unpack unzip error C:\Users\ramil\AppData\Local\Temp\npm-8556-bee4b83b\registry.npmjs.org\ajv\-\ajv-5.2.0.tgz
npm ERR! tar.unpack unzip error C:\Users\ramil\AppData\Local\Temp\npm-8556-bee4b83b\registry.npmjs.org\rxjs\-\rxjs-5.4.2.tgz
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\Web\\External\\Node.exe" "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\Web\\External\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.4.1
npm ERR! npm  v3.3.4
npm ERR! code Z_BUF_ERROR
npm ERR! errno -5
npm ERR! unexpected end of file
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\ramil\Documents\Visual Studio 2017\Projects\CoreTest2\CoreTest2\npm-debug.log

**Comment by netclectic** [comment]
Same here, except with a different ip: 151.101.60.162:443
