### ISSUE TITLE
shrinkwrapped dependencies ignored in favor of nested package.json(s)

### ISSUE THREAD

**Issue by labriola** [npm/npm#18460]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
In the case where one has an npm-shrinkwrap.json that exhaustively defines desired dependencies, including git based dependencies. npm ignores the versions defined in the shrinkwrap in favor of those found in subsequent package.json(s).

By way of example, if my shrinkwrap defines that I am reliant upon 'somelibrary': 5.0.0 and defines a library called 'gitdependency' which points to a specific hash. If the package.json stores in git for 'gitdependency' uses a different version of 'somelibrary' my shrinkwrap file is updated and I do not get the version in the shrinkwrap, but rather the one in the package.json.

Further, if I specify no-save, the shrinkwrap isnt updated, but I still get the 'wrong' version.

#### How can the CLI team reproduce the problem?
A project which uses a specific version of a library, let's call it 'somelibrary'. Additionally the project must have a git-based dependency for a library (let's call this 'gitdependency') that also uses 'somelibrary'. The shrinkwrap file should specify a needed version of both ''gitdependency' and 'somelibrary'. The package.json of 'gitdependency' should specify a different version of 'somelibrary'

The version in 'somelibrary' will be written into the shrinkwrap.

### supporting information:

 - `npm -v` prints: 5.3.0
 - `node -v` prints: v8.2.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: WIndows
 - Network issues:
   - Geographic location where npm was run:
   - [x] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by labriola** [comment]
May be related to: 

https://github.com/npm/npm/issues/17091
https://github.com/npm/npm/issues/18135

**Comment by labriola** [comment]
This is a tangent of 17979 and apparently now desired behavior. This comment being left as a guide for anyone else experiencing the same issue.

**Comment by jdrake3** [comment]
Makes me think that they don't know what shrink-wrap means. :-(
