### ISSUE TITLE
File permission error when installing packages

### ISSUE THREAD

**Issue by akshaybabloo** [npm/npm#18479]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Getting file permission error when trying to install NPM packages.

#### How can the CLI team reproduce the problem?

Trying install bootstrap on windows 10 system. Here is the complete log - https://gist.github.com/akshaybabloo/d29e00e0c8ed7368fad7eef38ae94394

### supporting information:

 - `npm -v` prints: 5.4.1
 - `node -v` prints: v8.4.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows 10 64-bit

I am getting file permission error when trying to install `bootstrap` even though I installed NodeJs globally. Following is the error.

```
C:\Users\aksha\Box Sync\MyDrive\Projects\Akshay-GitHub\Angular-Notes\my-first-app>npm install --save bootstrap
npm ERR! path C:\Users\aksha\Box Sync\MyDrive\Projects\Akshay-GitHub\Angular-Notes\my-first-app\node_modules\fsevents\node_modules\abbrev\package.json
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall unlink
npm ERR! Error: EPERM: operation not permitted, unlink 'C:\Users\aksha\Box Sync\MyDrive\Projects\Akshay-GitHub\Angular-Notes\my-first-app\node_modules\fsevents\node_modules\abbrev\package.json'
npm ERR!  { Error: EPERM: operation not permitted, unlink 'C:\Users\aksha\Box Sync\MyDrive\Projects\Akshay-GitHub\Angular-Notes\my-first-app\node_modules\fsevents\node_modules\abbrev\package.json'
npm ERR!   stack: 'Error: EPERM: operation not permitted, unlink \'C:\\Users\\aksha\\Box Sync\\MyDrive\\Projects\\Akshay-GitHub\\Angular-Notes\\my-first-app\\node_modules\\fsevents\\node_modules\\abbrev\\package.json\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path: 'C:\\Users\\aksha\\Box Sync\\MyDrive\\Projects\\Akshay-GitHub\\Angular-Notes\\my-first-app\\node_modules\\fsevents\\node_modules\\abbrev\\package.json' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\aksha\AppData\Roaming\npm-cache\_logs\2017-09-11T03_52_15_275Z-debug.log
```

I have searched around and tried `npm cache clean` then I get the following warning

```
C:\Users\aksha\Box Sync\MyDrive\Projects\Akshay-GitHub\Angular-Notes\my-first-app>npm cache clean
npm ERR! As of npm@5, the npm cache self-heals from corruption issues and data extracted from the cache is guaranteed to be valid. If you want to make sure everything is consistent, use 'npm cache verify' instead.
npm ERR!
npm ERR! If you're sure you want to delete the entire cache, rerun this command with --force.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\aksha\AppData\Roaming\npm-cache\_logs\2017-09-11T04_54_02_121Z-debug.log
```

According to the warning I shouldn't be doing this. So any solution to this problem?

**Comment by webtaculars** [comment]
@akshaybabloo  Is this issue solved for you? If not try this temporary fix, downgrade npm to 5.3

`npm install npm@5.3 -g`

**Comment by akshaybabloo** [comment]
@webtaculars That's giving me the same error. I think I am getting this because `fsevents` doesn't exist in my `node_modules` folder.

**Comment by Butterfly** [comment]
Something just now hit me even though I've been seeing that `fsevents` taking a hit on regular occasion. If it's supposed to be there but isn't, has anyone ever tried searching for it to see if it got stuffed somewhere else, e.g. possibly a wrong location? If `fsevents` is not there by *user choice*, then, no, trying this would *not* help.

For people using Linux, you possibly might have to update first before searching. I do so with `updatedb` (as root), and then I would run something like `locate fsevents`. That's just easiest for me to remember, but others have all kinds of fancier command line file search techniques.... :smile:

**Comment by Oobert** [comment]
Just ran into this problem on...

 npm -v prints: 5.4.1
node -v prints: v8.1.1
npm config get registry prints: https://registry.npmjs.org/
Windows, OS X/macOS, or Linux?: Windows 10 64-bit

I downgraded npm to v5.3.0 and got 

```C:\Development\DevWi>npm install
npm ERR! path C:\Development\DevWi\node_modules\fsevents\node_modules\dashdash\node_modules
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall scandir
npm ERR! Error: EPERM: operation not permitted, scandir 'C:\Development\DevWi\node_modules\fsevents\node_modules\dashdash\node_modules'
npm ERR!  { Error: EPERM: operation not permitted, scandir 'C:\Development\DevWi\node_modules\fsevents\node_modules\dashdash\node_modules'
npm ERR!   stack: 'Error: EPERM: operation not permitted, scandir \'C:\\Development\\DevWi\\node_modules\\fsevents\\node_modules\\dashdash\\node_modules\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'scandir',
npm ERR!   path: 'C:\\Development\\DevWi\\node_modules\\fsevents\\node_modules\\dashdash\\node_modules' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\noobe\AppData\Roaming\npm-cache\_logs\2017-09-13T01_34_41_415Z-debug.log
```

I than downgraded npm again back to 5.0.3 (the version I was on before I updated just now) and everything went back to working.

**Comment by vaxul** [comment]
Win10 64bit 

I have upgraded npm to 5.4.1 from an pre-5 Version for the "new" lock-json-feature. After the upgrade I got the same problem as mentioned by others.

```
...\build>npm install
npm ERR! path ...\build\node_modules\fsevents\node_modules\aws4\package.json
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall unlink
npm ERR! Error: EPERM: operation not permitted, unlink '...\build\node_modules\fsevents\node_modules\aws4\package.json'
npm ERR!     at Error (native)
npm ERR!  { Error: EPERM: operation not permitted, unlink '...\build\node_modules\fsevents\node_modules\aws4\package.json'
npm ERR!     at Error (native)
npm ERR!   stack: 'Error: EPERM: operation not permitted, unlink \'...\\build\\node_modules\\fsevents\\node_modules\\aws4\\package.json\'\n    at Error (native)',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path: '...\\build\\node_modules\\fsevents\\node_modules\\aws4\\package.json' }
npm ERR!
```

This seems to happen within "postinstall", while npm handels the sub-modules.

As mentioned, **npm install --no-optional** work around the problem.

**Comment by davidMuir** [comment]
This looks to be solved for me in 5.4.2. 

I'd suggest updating to the latest version and seeing if you're still seeing the issue.

**Comment by akshaybabloo** [comment]
Yep. Fixed in 5.4.2.

**Comment by varghesep** [comment]
I'm using Windows, and seeing the following error **sometimes** with 5.4.2:

> Error: EPERM: operation not permitted, scandir

**Comment by akshaybabloo** [comment]
@varghesep please open a new ticket
