### ISSUE TITLE
cb() never called

### ISSUE THREAD

**Issue by everdrone** [npm/npm#18473]
#### I'm opening this issue because:
doesn't matter what command i run, npm gives error.

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
- `npm i <any package>` prints:
    `npm ERR! cb() never called!`
- `npm i -g npm` prints:
    `npm ERR! cb() never called!`
- `npm cache clean -f` prints:
    `npm WARN using --force I sure hope you know what you are doing.`
`npm ERR! path C:\Program Files\nodejs\cache\_cacache\tmp`
`npm ERR! code EPERM`
`npm ERR! errno -4048`
`npm ERR! syscall rmdir`
`npm ERR! Error: EPERM: operation not permitted, rmdir 'C:\Program Files\nodejs\cache\_cacache\tmp'`
`npm ERR!  { Error: EPERM: operation not permitted, rmdir 'C:\Program Files\nodejs\cache\_cacache\tmp'`
`npm ERR!   cause:`
`npm ERR!    { Error: EPERM: operation not permitted, rmdir 'C:\Program Files\nodejs\cache\_cacache\tmp'`
`npm ERR!      errno: -4048,`
`npm ERR!      code: 'EPERM',`
`npm ERR!      syscall: 'rmdir',`
`npm ERR!      path: 'C:\\Program Files\\nodejs\\cache\\_cacache\\tmp' },`
`npm ERR!   isOperational: true,`
`npm ERR!   stack: 'Error: EPERM: operation not permitted, rmdir \'C:\\Program Files\\nodejs\\cache\\_cacache\\tmp\'',`
`npm ERR!   errno: -4048,`
`npm ERR!   code: 'EPERM',`
`npm ERR!   syscall: 'rmdir',`
`npm ERR!   path: 'C:\\Program Files\\nodejs\\cache\\_cacache\\tmp' }`
`npm ERR!`
`npm ERR! Please try running this command again as root/Administrator.`
   then it hangs.

#### How can the CLI team reproduce the problem?
i just updated node to the current (8.4.0) version.

### supporting information:

 - `npm -v` prints: 5.4.1
 - `node -v` prints: 8.4.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows 10
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by everdrone** [comment]
Managed to remove **everything** related to npm on this machine, except for `%userprofile%/.npmrc`
from [stackoverflow](https://stackoverflow.com/questions/20711240/how-to-completely-remove-node-js-from-windows)

**Comment by Mithrrandil** [comment]
npm ERR! cb() never called when npm run dev any project
