### ISSUE TITLE
npm - Firebase tool installation failure.

### ISSUE THREAD

**Issue by ksanooj** [npm/npm#18497]
Stucked with the following error.
I have tried with the following command "sudo npm install -g firebase-tools" and got the error.

npm http 404 https://registry.npmjs.org/google-cloud/functions-emulator
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/usr/share/npm/lib/cache.js:687:35)
npm ERR!     at /usr/share/npm/lib/cache.js:675:5
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.16.0-30-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "firebase-tools"
npm ERR! cwd /home/sanooj
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type non_object_property_load
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/sanooj/npm-debug.log
npm ERR! not ok code 0

Please suggest some solution for the problem, will be a great help

**Comment by simonvangorp** [comment]
Jep. I am having the exact same error. Did you found a solution ?

**Comment by kenany** [comment]
@ksanooj Your versions of Node.js and `npm` are years old and are no longer supported.

@simonvangorp If you are having this issue with the latest stable release of Node.js and `npm`, please feel free to open a new ticket.
