### ISSUE TITLE
Resolving conflicts for package-lock.json

### ISSUE THREAD

**Issue by hiimbex** [npm/npm#18491]
#### What's the feature?
It would be nice if npm could offer an easier way to deal with merge conflicts in the `package-lock.json` which are relatively common. Right now I usually delete the `package.lock.json` and then run `npm install`, but it seems like this process could be simplified to automatically resolving the conflicts based on the `package.json` when running `npm install`. That currently gives an error output like such when there are merge conflicts (GitHub's usually start with `>>>>>`): 
```
npm ERR! Unexpected token > in JSON at position 398
```

#### What problem is the feature intended to solve?
Making it easier to resolve merge conflicts in the `package-lock.json`.

#### Is the absence of this feature blocking you or your team? If so, how?
Not really, it would just speed up some workflows/make more sense.

#### Is this feature similar to an existing feature in another tool?
Yes, yarn faced this same problem here: https://github.com/yarnpkg/yarn/issues/2155 and solved it via https://github.com/yarnpkg/yarn/pull/3544

#### Is this a feature you're prepared to implement, with support from the npm CLI team?
I don't think I would be well suited for that task.

**Comment by hiimbex** [comment]
Just discovered https://github.com/npm/npm/issues/18007 and closing in favor of that.

**Comment by cscleison** [comment]
https://github.com/npm/npm/blob/latest/doc/files/npm-package-locks.md#resolving-lockfile-conflicts
