### ISSUE TITLE
npm ERR! You can no longer unpublish this package.

### ISSUE THREAD

**Issue by c1tt1** [npm/npm#18505]
- `npm -v` : 4.2.0
 - `node -v`: v7.8.0
 - `npm config get registry`: https://registry.npmjs.org/
 - OS X/macOS

#### I have a package on npm that I'd like to remove:
After doing the unpublish command I get the following errors:

```
npm ERR! Darwin 16.7.0
npm ERR! argv "/Users/ark/.nvm/versions/node/v7.8.0/bin/node" "/Users/ark/.nvm/versions/node/v7.8.0/bin/npm" "unpublish" "reqvest@1.0.0"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! code E400

npm ERR! You can no longer unpublish this package.
npm ERR! Please deprecate it instead:
npm ERR! npm deprecate reqvest "this package has been deprecated" : reqvest
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ark/.npm/_logs/2017-09-12T19_17_51_151Z-debug.log
```

I am not sure of what's going on and would like to know why.

But my questions are:
Why can't unpublish a package?
Why does the command default to deprecate?
docs.npmjs.com is scarse I found it difficult when it comes to unpublishing packages and can it be improved?
Why hasn't this been fixed as there' been similar issues in past?

**Comment by clakech** [comment]
same here, how to unpublish a package ?

**Comment by MarcinMoskala** [comment]
Similar problem. I have a package I need to unpublish. How to do it?

**Comment by warpdesign** [comment]
There is a reason why you cannot [unpublish a package:](https://docs.npmjs.com/cli/unpublish)

> It is generally considered bad behavior to remove versions of a library that others are depending on!

For this reason you may only unpublish a package if it has been published in the last 24 hours.

You should contact npm to have an older version unpublished:

> With the default registry (registry.npmjs.org), unpublish is only allowed with versions published in the last 24 hours. If you are trying to unpublish a version published longer ago than that, contact support@npmjs.com.

**Comment by c1tt1** [comment]
@warpdesign fare point what if you want to actually remove a package not just deprecating it. What if that library wasn't mean to be published?.

**Comment by kenany** [comment]
@cryst10 Email <support@npmjs.com> and perhaps they can accomodate.

**Comment by c1tt1** [comment]
Ok thanks all, I will close this  issue when I get a reply.

**Comment by c1tt1** [comment]
It makes sense that before unpublishing a module you'd have to consider the amount of people or devs depending on it.
