### ISSUE TITLE
Unable to attach npm-debug.log file 

### ISSUE THREAD

**Issue by sarbjithanjra** [npm/npm#18501]
On Windows 10, I was trying to install exp (exponent) but during installation I got an error. On error screen npm suggest that "Please include the following file with any support request: E:\npm-debug.log".
I opened "https://github.com/npm/npm/issues/new" to submit a new issue as suggested in error message. When I try to attached npm-debug.log with issue, it say "We don't support that file type."
NPM first suggest to include that file and when try to attach it say we don't support. Please let me know what to do?

E:\>npm install exp --global
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "exp" "--global"
npm ERR! node v7.7.3
npm ERR! npm  v4.1.2

npm ERR! shasum check failed for C:\Users\Admin\AppData\Local\Temp\npm-4100-8ef9c049\registry.npmjs.org\_40expo\ngrok\-\ngrok-2.2.8.tgz
npm ERR! Expected: c4fb73df630fee19cc9478ef68bc6836198d525c
npm ERR! Actual:   b6def8cd681ac38770dd375377834a586313c35a
npm ERR! From:     https://registry.npmjs.org/@expo/ngrok/-/ngrok-2.2.8.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     E:\npm-debug.log

E:\>https://github.com/npm/npm/issues

**Comment by kenany** [comment]
Uploading the log file to <https://gist.github.com/> and posting the link here should do the trick 👍
