### ISSUE TITLE
Node not working 

### ISSUE THREAD

**Issue by iggs123** [npm/npm#18507]
Hi i am working on making a discord bot for my channel and when I got to test the bot in the terminal and type node . or node index it says this :
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10

npm ERR! missing script: start
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\IgorsPC\Desktop\Bot\npm-debug.log
PS C:\Users\IgorsPC\Desktop\Bot>

So I don't know how to fix this problem and if anyone could help me it would be appreciated
Thanks.

**Comment by evocateur** [comment]
The error message is telling you exactly what it's missing: `missing script: start`. You need a `start` [script](https://docs.npmjs.com/misc/scripts) in your package.json.
