### ISSUE TITLE
Refusing to install riek as a dependency of itself

### ISSUE THREAD

**Issue by ghost** [npm/npm#18511]
npm ERR! Linux 4.4.0-93-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "riek" "--save-dev"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ENOSELF

npm ERR! Refusing to install riek as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/peoplelink/Desktop/riek-master/npm-debug.log
peoplelink@peoplelink-TravelMate-P257-M:~/Desktop/riek-master$ ^C
peoplelink@peoplelink-TravelMate-P257-M:~/Desktop/riek-master$ npm install riek --save
npm ERR! Linux 4.4.0-93-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "riek" "--save"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ENOSELF

npm ERR! Refusing to install riek as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/peoplelink/Desktop/riek-master/npm-debug.log

**Comment by kenany** [comment]
Ensure that the `"name"` field in your `package.json` is not set to `"riek"`. Try setting it to something more unique :)

**Comment by kenany** [comment]
Closing as abandoned.
