### ISSUE TITLE
npm-angular-cli-error-log

### ISSUE THREAD

**Issue by mrunals01** [npm/npm#18521]
![angular-snap](https://user-images.githubusercontent.com/13827249/30414981-9c3825b8-9943-11e7-9a53-481aee3f9fe8.png)
#### I'm opening this issue because:

 I can't install angular-cli on my windows 7 64-bit, I keep getting error messages.
If anyone could help me with this error, I'd be grateful.

**Comment by legodude17** [comment]
Does this occur with the latest version of npm?

**Comment by mrunals01** [comment]
Yes nodejs v6.11.3 and npm v3.10.10
Tried reinstalling nodejs a multiple times, didn't help..
