### ISSUE TITLE
Angular CLI not install on Widnows 10 

### ISSUE THREAD

**Issue by dhruvangg** [npm/npm#18539]
I'm trying to install angular cli but it shows me following eror

C:\Users\Dhruvang>npm install -g @angular/cli
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10

npm ERR! shasum check failed for C:\Users\Dhruvang\AppData\Local\Temp\npm-80-169afa85\registry.npmjs.org\caniuse-db\-\caniuse-db-1.0.30000730.tgz
npm ERR! Expected: c9e1919a9f586c85d79265e7a84261b8421f92bd
npm ERR! Actual:   be30e5c9aa18a888a56dcedf34e846371279a625
npm ERR! From:     https://registry.npmjs.org/caniuse-db/-/caniuse-db-1.0.30000730.tgz
npm ERR!

**Comment by robv8r** [comment]
Try 

    npm cache clean

It looks like the cached copy of the package is corrupt. In later versions of npm, the cache is "self healing".
