### ISSUE TITLE
npm install socket.io error

### ISSUE THREAD

**Issue by AKenHu** [npm/npm#18532]
Hi, I'm trying install socket.io on Linux Ubuntu 16.04.2 and Windows 10, but it's not work, what's wrong with it?

-- terminal error --
Linux 4.10.0-33-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "socket.io" "--save"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ENOSELF

npm ERR! Refusing to install socket.io as a dependency of itself
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /media/sf_vm_public_folder/web/socket.io/npm-debug.log

---- npm-debug.log ---
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   'socket.io',
1 verbose cli   '--save' ]
2 info using npm@3.10.10
3 info using node@v6.11.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData socket.io
8 silly fetchNamedPackageData socket.io
9 silly mapToRegistry name socket.io
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'socket.io',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'socket.io',
12 silly mapToRegistry   name: 'socket.io',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/socket.io
14 verbose request uri https://registry.npmjs.org/socket.io
15 verbose request no auth needed
16 info attempt registry request try #1 at 1:46:25 PM
17 verbose request id 1a5d4c48c8e14c0c
18 verbose etag W/"59b170cb-28a84"
19 verbose lastModified Thu, 07 Sep 2017 16:16:11 GMT
20 http request GET https://registry.npmjs.org/socket.io
21 http 304 https://registry.npmjs.org/socket.io
22 verbose headers { date: 'Fri, 15 Sep 2017 05:46:26 GMT',
22 verbose headers   via: '1.1 varnish',
22 verbose headers   'cache-control': 'max-age=300',
22 verbose headers   etag: 'W/"59b170cb-28a84"',
22 verbose headers   age: '94',
22 verbose headers   connection: 'keep-alive',
22 verbose headers   'x-served-by': 'cache-itm7420-ITM',
22 verbose headers   'x-cache': 'HIT',
22 verbose headers   'x-cache-hits': '26',
22 verbose headers   'x-timer': 'S1505454387.920158,VS0,VE0',
22 verbose headers   vary: 'Accept-Encoding, Accept' }
23 silly get cb [ 304,
23 silly get   { date: 'Fri, 15 Sep 2017 05:46:26 GMT',
23 silly get     via: '1.1 varnish',
23 silly get     'cache-control': 'max-age=300',
23 silly get     etag: 'W/"59b170cb-28a84"',
23 silly get     age: '94',
23 silly get     connection: 'keep-alive',
23 silly get     'x-served-by': 'cache-itm7420-ITM',
23 silly get     'x-cache': 'HIT',
23 silly get     'x-cache-hits': '26',
23 silly get     'x-timer': 'S1505454387.920158,VS0,VE0',
23 silly get     vary: 'Accept-Encoding, Accept' } ]
24 verbose etag https://registry.npmjs.org/socket.io from cache
25 verbose get saving socket.io to /home/kenhu/.npm/registry.npmjs.org/socket.io/.cache.json
26 verbose correctMkdir /home/kenhu/.npm correctMkdir not in flight; initializing
27 silly install normalizeTree
28 silly loadCurrentTree Finishing
29 silly loadIdealTree Starting
30 silly install loadIdealTree
31 silly cloneCurrentTree Starting
32 silly install cloneCurrentTreeToIdealTree
33 silly cloneCurrentTree Finishing
34 silly loadShrinkwrap Starting
35 silly install loadShrinkwrap
36 silly loadShrinkwrap Finishing
37 silly loadAllDepsIntoIdealTree Starting
38 silly install loadAllDepsIntoIdealTree
39 silly rollbackFailedOptional Starting
40 silly rollbackFailedOptional Finishing
41 silly runTopLevelLifecycles Finishing
42 silly install printInstalled
43 verbose stack Error: Refusing to install socket.io as a dependency of itself
43 verbose stack     at checkSelf (/usr/lib/node_modules/npm/lib/install/validate-args.js:53:14)
43 verbose stack     at Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
43 verbose stack     at LOOP (/usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
43 verbose stack     at chain (/usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
43 verbose stack     at /usr/lib/node_modules/npm/lib/install/validate-args.js:16:5
43 verbose stack     at /usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
43 verbose stack     at Array.forEach (native)
43 verbose stack     at /usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
43 verbose stack     at Array.forEach (native)
43 verbose stack     at asyncMap (/usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
44 verbose cwd /media/sf_vm_public_folder/web/socket.io
45 error Linux 4.10.0-33-generic
46 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "socket.io" "--save"
47 error node v6.11.1
48 error npm  v3.10.10
49 error code ENOSELF
50 error Refusing to install socket.io as a dependency of itself
51 error If you need help, you may report this error at:
51 error     <https://github.com/npm/npm/issues>
52 verbose exit [ 1, true ]

**Comment by kenany** [comment]
Ensure that the `"name"` field in your `package.json` is not set to `"socket.io"`. Try setting it to something more unique :)
