### ISSUE TITLE
npm in crushing....installed by brew version 8.5.0

### ISSUE THREAD

**Issue by JokerHYC** [npm/npm#18535]
> npm                                                                   ~@b
module.js:529
    throw err;
    ^

Error: Cannot find module '../lib/utils/unsupported.js'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:19:21
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:92:3)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)

----------------------------------------------
==> Summary
🍺  /usr/local/Cellar/node/8.5.0: 4,152 files, 47.8MB

**Comment by dgramop** [comment]
I ran brew upgrade and it stopped working. I might see if I can downgrade npm?

**Comment by dgramop** [comment]
curl -L https://www.npmjs.org/install.sh | sh
did NOT work.

Next I'm going to try to uninstall and reinstall node

**Comment by dgramop** [comment]
Didn't work. 
I'm going to fully uninstall and reinstall node with the -f option

**Comment by dgramop** [comment]
brew uninstall --force node
and then brew install node

Still same error with npm

**Comment by JokerHYC** [comment]
download the .dmg form website and manually install it.
brew post install was a failure...

**Comment by memoht** [comment]
> npm
module.js:529
    throw err;

Any resolution to this issue?

**Comment by D3FUZED** [comment]
exactly the same issue here

**Comment by ghost** [comment]
Same issue from high sierra.

**Comment by sonicwong** [comment]
+1

**Comment by vict0rsch** [comment]
same with Yosemite and Node 8.6.0 from Brew

**Comment by 1st** [comment]
Have the same issue. I'm on the macOS Sierra (not the latest), but still have the same issue. Reinstall doesn't help

**Comment by 1st** [comment]
Ok, I finally solved the issue with **node**.

Follow these steps:
```sh
rm -rf /usr/local/lib/node_modules
# remove previously installed node
brew uninstall node
brew prune    # clean all broken symlinks
brew update   # always good to have the latest
# and install normal one
brew install node
```

Based on [this gist](https://gist.github.com/rcugut/c7abd2a425bb65da3c61d8341cd4b02d).

**Comment by qiulang** [comment]
I updated nodejs to latest 9.3 and fixed the problem. Brew caused more trouble than it is worth
