### ISSUE TITLE
'npm install'  crash.

### ISSUE THREAD

**Issue by tezikaZ** [npm/npm#18547]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
When using the **'npm install'** to install the specific package(telp), the npm will crash.
#### How can the CLI team reproduce the problem?
 *  how to reproduce: use the command **'npm install telp'**
 *   [npm-debug.log](https://gist.github.com/Tezika/bbae9a0559566ae1d33dcceb76a0ad85)
### supporting information:

 - npm version: **3.10.3**
 - node version: **v6.5.0**
 - `npm config get registry` prints:  https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?:**OS X**
 - Network issues:
   - [ ]Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [x] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
Does this also occur with the latest stable release of `npm`?

**Comment by tezikaZ** [comment]
Hi, @KenanY 
Actually, I don't know whether this crash would occur in the latest stable release version.Do I need to revert my **npm** to a stable version and try it?

**Comment by kenany** [comment]
@Tezika No, you need to update your `npm` in order to reach the latest stable version. The version you have is several months old.

**Comment by tezikaZ** [comment]
@KenanY  uha, I update my **npm** to the latest version **5.4.2**, then it works well!Thx for your solution!
