### ISSUE TITLE
I couldn't execute npm run deploy

### ISSUE THREAD

**Issue by vignesh2595** [npm/npm#18544]
I am a beginner , trying to develop a web application using react js and fire base. I have included fire base to my application and once I changed my authentication of DB to true and tried executing with       ' NPM RUN DEPLOY'. I am getting the blow mentioned errors. thanks in advance. Had i missed any packages or dependencies do let me know.
 
D:\react\k-app>npm run deploy
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\bin\\node.exe" "C:\\Program Files\\nod
ejs\\bin\\node_modules\\npm\\bin\\npm-cli.js" "run" "deploy"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10

npm ERR! missing script: deploy
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\react\k-app\npm-debug.log

**Comment by kenany** [comment]
Hello! So, the way `npm run deploy` works is that it looks in your current `package.json` for a defined `"deploy"` [script](https://docs.npmjs.com/misc/scripts), and then runs that. The error message you're seeing is trying to tell you that you have not defined a `"deploy"` script in your `package.json`, hence `npm run deply` has no idea what you want it to do.

To solve this issue, all you have to do is add a new script to your `package.json`. It might look something like this, for example:

``` json
{
  "name": "package-name",
  "version": "1.0.0",
  "description": "package description",
  "scripts": {
    "deploy": "node --version",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {},
  "devDependencies": {}
}
```

Note how this `package.json` has a `"deploy"` script that runs `node --version`. You'll definitely want to change the command to whatever is most appropriate for your project.

Let me know if you run into any further `npm` issues :)
