### ISSUE TITLE
Dont truncate output of `npm show <package> versions`

### ISSUE THREAD

**Issue by wesleytodd** [npm/npm#18541]
#### What's the feature?

Don't truncate output from `npm show <package> versions`

#### What problem is the feature intended to solve?

```
$ npm show express versions | grep 5
  '1.0.5',
  '2.3.5',
  '2.4.5',
  '2.5.0',
  '2.5.1',
  '2.5.2',
  '2.5.3',
  '2.5.4',
  '2.5.5',
  '2.5.6',
  '2.5.7',
  '2.5.8',
  '2.5.9',
  '2.5.10',
  '2.5.11',
  '3.0.0-alpha5',
  '3.0.0-rc5',
  '3.0.5',
  '3.2.5',
  ... 153 more items ]
```

While trying to see what the most recent pre release version of express 5 is, I get a truncated list.  Preferably these are not listed as a node style array log, but as a new line delimited list.

#### Is the absence of this feature blocking you or your team? If so, how?

Nope, just seems like it would be a better UX.

#### Is this feature similar to an existing feature in another tool?

I guess most cli tools, `git branch` for example.

#### Is this a feature you're prepared to implement, with support from the npm CLI team?

Sure.  As this would be my first contribution, I would hope for a pointer in the right direction, but I would be happy to do the work.

**Comment by kenany** [comment]
ref. https://github.com/npm/npm/issues/16590, https://github.com/npm/npm/pull/16602

**Comment by wesleytodd** [comment]
Sorry, I must have forgotten to search closed issues.  Seems both of those were closed, not because it was un-wanted, but because of inactivity.  I was unaware of the `--long` flag, which is certainly one way to do this.  Personally I still think it is more expected to have them be newline delimited, but if the `--long` flag is the preferred approach I can take over/champion that PR (#16602).

**Comment by kenany** [comment]
Actually, looks like https://github.com/npm/npm/pull/18326 will do what you want 👍

**Comment by wesleytodd** [comment]
Closing in favor of #18326.  It solves my direct problem. Although I am still of the opinion that it should output them as a new line delimited list, it is a much easier format in bash workflows.
