### ISSUE TITLE
I created project in expo...while opening using qr code its not opening...

### ISSUE THREAD

**Issue by saikrishnanaru** [npm/npm#18559]
after scanning qr it showing screen expo client app like"

there was a problem loading the experience .itlooks like you may be using a lan url.make surebyour device is on the same network as the server or try using a tunnel.

try again
go back to home screen

exp://192.168.2.4:19000
"Error whil loading: the request timed out.." (code-1001)

**Comment by kenany** [comment]
Closing since this doesn't seem like an issue with `npm` to me.
