### ISSUE TITLE
what is this 

### ISSUE THREAD

**Issue by jiandan1989** [npm/npm#18558]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

https://docs.npmjs.com/all
![default](https://user-images.githubusercontent.com/16014141/30529598-88538868-9c71-11e7-9d9d-89b119179b31.png)

**Comment by jiandan1989** [comment]
why?

**Comment by kenany** [comment]
Might be better off over here: <https://github.com/npm/docs>

**Comment by ts-1** [comment]
pre {
  white-space: nowrap;
  overflow: auto;
}

This will solve the issue.

**Comment by kenany** [comment]
I still think this belongs at the docs repo mentioned above, so I'm gonna close this.
