### ISSUE TITLE
npm info gives E404 for private package

### ISSUE THREAD

**Issue by dennissy3** [npm/npm#18550]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I use npm info to get my current setup. Though my Ionic app is set private in package.json I get the following error message: 

`
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/Cellar/node/7.7.1/bin/node" "/Users/username/.npm-packages/bin/npm" "info"
npm ERR! node v7.7.1
npm ERR! npm  v4.3.0
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/MyPackage
npm ERR! 404 
npm ERR! 404  'MyPackage' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

`

#### How can the CLI team reproduce the problem?
$ npm info 

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
@dennissy3 So, just to expand on this, what output specifically are you expecting in this case? Knowing your expectations would help me or someone else implement this :)

**Comment by dennissy3** [comment]
I would expect to get my current npm setup. Like which versions am I using of what. Actually need that info to get support from the Ionic team.

**Comment by kenany** [comment]
@dennissy3 So, like what `npm ls` currently does?

**Comment by kenany** [comment]
Closing due to no response.
