### ISSUE TITLE
React Native problem

### ISSUE THREAD

**Issue by saikrishnanaru** [npm/npm#18562]
im using windows system and ios mobile... i created app in reactnative while to open app in expo..it is notopening after qr code scanning... for this i need to connect mobie to to system??

this occured when use share option in expo....
![capture](https://user-images.githubusercontent.com/30742042/30530754-10c13d90-9c67-11e7-8cd0-293989db6b26.JPG)
![img_1685](https://user-images.githubusercontent.com/30742042/30530791-563dcd52-9c67-11e7-8cfd-f2b2d52082e9.PNG)

this occured when used option "device"...
![capture1](https://user-images.githubusercontent.com/30742042/30530829-a376a3aa-9c67-11e7-9b50-1c4d641c0d29.JPG)

**Comment by kenany** [comment]
Sorry, but this issue tracker is for issues regarding `npm`, not general support for react-native.
