### ISSUE TITLE
npm install mint-ui -S

### ISSUE THREAD

**Issue by sherlockHolmes213** [npm/npm#18575]
D:\vueTest\mint-ui>npm install mint-ui -S
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "mint-ui" "-S"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ENOSELF

npm ERR! Refusing to install mint-ui as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\vueTest\mint-ui\npm-debug.log

**Comment by kenany** [comment]
Ensure that the `"name"` field in your `package.json` is not set to `"mint-ui"`. Try setting it to something more unique :)

**Comment by kenany** [comment]
Closing as abandoned.
