### ISSUE TITLE
NPM cannot install express-acl

### ISSUE THREAD

**Issue by ikmahesh** [npm/npm#18576]
#### I'm opening this issue because:

  - [] npm is doing something I don't understand.

#### What's going wrong?
refuse to install express-acl
#### How can the CLI team reproduce the problem?

C:\NodejsSamples\ACL\express-acl-develop>npm install express-acl
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "express-acl"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ENOSELF

npm ERR! Refusing to install express-acl as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\NodejsSamples\ACL\express-acl-develop\npm-debug.log

--------------------log file------------------------------------
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'express-acl' ]
2 info using npm@3.10.10
3 info using node@v6.11.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData express-acl
8 silly fetchNamedPackageData express-acl
9 silly mapToRegistry name express-acl
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'express-acl',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'express-acl',
12 silly mapToRegistry   name: 'express-acl',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/express-acl
14 verbose request uri https://registry.npmjs.org/express-acl
15 verbose request no auth needed
16 info attempt registry request try #1 at 2:36:25 PM
17 verbose request id d66076355dc60943
18 http request GET https://registry.npmjs.org/express-acl
19 http 200 https://registry.npmjs.org/express-acl
20 verbose headers { server: 'nginx/1.10.3',
20 verbose headers   'content-type': 'application/json',
20 verbose headers   'last-modified': 'Thu, 06 Jul 2017 07:22:35 GMT',
20 verbose headers   etag: 'W/"595de53b-5699"',
20 verbose headers   'content-encoding': 'gzip',
20 verbose headers   'cache-control': 'max-age=300',
20 verbose headers   'content-length': '5925',
20 verbose headers   'accept-ranges': 'bytes',
20 verbose headers   date: 'Tue, 19 Sep 2017 09:04:26 GMT',
20 verbose headers   via: '1.1 varnish',
20 verbose headers   age: '0',
20 verbose headers   connection: 'keep-alive',
20 verbose headers   'x-served-by': 'cache-sin18023-SIN',
20 verbose headers   'x-cache': 'MISS',
20 verbose headers   'x-cache-hits': '0',
20 verbose headers   'x-timer': 'S1505811866.921327,VS0,VE239',
20 verbose headers   vary: 'Accept-Encoding, Accept' }
21 silly get cb [ 200,
21 silly get   { server: 'nginx/1.10.3',
21 silly get     'content-type': 'application/json',
21 silly get     'last-modified': 'Thu, 06 Jul 2017 07:22:35 GMT',
21 silly get     etag: 'W/"595de53b-5699"',
21 silly get     'content-encoding': 'gzip',
21 silly get     'cache-control': 'max-age=300',
21 silly get     'content-length': '5925',
21 silly get     'accept-ranges': 'bytes',
21 silly get     date: 'Tue, 19 Sep 2017 09:04:26 GMT',
21 silly get     via: '1.1 varnish',
21 silly get     age: '0',
21 silly get     connection: 'keep-alive',
21 silly get     'x-served-by': 'cache-sin18023-SIN',
21 silly get     'x-cache': 'MISS',
21 silly get     'x-cache-hits': '0',
21 silly get     'x-timer': 'S1505811866.921327,VS0,VE239',
21 silly get     vary: 'Accept-Encoding, Accept' } ]
22 verbose get saving express-acl to C:\Users\ikmah\AppData\Roaming\npm-cache\registry.npmjs.org\express-acl\.cache.json
23 verbose correctMkdir C:\Users\ikmah\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
24 silly install normalizeTree
25 silly loadCurrentTree Finishing
26 silly loadIdealTree Starting
27 silly install loadIdealTree
28 silly cloneCurrentTree Starting
29 silly install cloneCurrentTreeToIdealTree
30 silly cloneCurrentTree Finishing
31 silly loadShrinkwrap Starting
32 silly install loadShrinkwrap
33 silly loadShrinkwrap Finishing
34 silly loadAllDepsIntoIdealTree Starting
35 silly install loadAllDepsIntoIdealTree
36 silly rollbackFailedOptional Starting
37 silly rollbackFailedOptional Finishing
38 silly runTopLevelLifecycles Finishing
39 silly install printInstalled
40 verbose stack Error: Refusing to install express-acl as a dependency of itself
40 verbose stack     at checkSelf (C:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:53:14)
40 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
40 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
40 verbose stack     at chain (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
40 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:16:5
40 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
40 verbose stack     at Array.forEach (native)
40 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
40 verbose stack     at Array.forEach (native)
40 verbose stack     at asyncMap (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
41 verbose cwd C:\NodejsSamples\ACL\express-acl-develop
42 error Windows_NT 10.0.15063
43 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "express-acl"
44 error node v6.11.0
45 error npm  v3.10.10
46 error code ENOSELF
47 error Refusing to install express-acl as a dependency of itself
48 error If you need help, you may report this error at:
48 error     <https://github.com/npm/npm/issues>
49 verbose exit [ 1, true ]

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
Ensure that the `"name"` field in your `package.json` is not set to `"express-acl"`. Try setting it to something more unique :)

**Comment by kenany** [comment]
Closing as abandoned.
