### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by Giuscar** [npm/npm#18591]
#### I'm opening this issue because:
- npm is producing an incorrect install.

I'm using  Linux 16.04
 
#### What's going wrong?
42 verbose stack Error: Refusing to install bitmovin-javascript as a dependency of itself
42 verbose stack     at checkSelf (/usr/share/npm/lib/install/validate-args.js:40:14)
42 verbose stack     at Array.<anonymous> (/usr/share/npm/node_modules/slide/lib/bind-actor.js:15:8)
42 verbose stack     at LOOP (/usr/share/npm/node_modules/slide/lib/chain.js:15:14)
42 verbose stack     at chain (/usr/share/npm/node_modules/slide/lib/chain.js:20:5)
42 verbose stack     at /usr/share/npm/lib/install/validate-args.js:15:5
42 verbose stack     at /usr/share/npm/node_modules/slide/lib/async-map.js:52:35
42 verbose stack     at Array.forEach (native)
42 verbose stack     at /usr/share/npm/node_modules/slide/lib/async-map.js:52:11
42 verbose stack     at Array.forEach (native)
42 verbose stack     at asyncMap (/usr/share/npm/node_modules/slide/lib/async-map.js:51:8)
43 verbose cwd /home/giuseppe/Desktop/bitmovin/bitmovin-javascript
44 error Linux 4.10.0-35-generic
45 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "bitmovin-javascript"
46 error node v4.2.6
47 error npm  v3.5.2
48 error code ENOSELF
49 error Refusing to install bitmovin-javascript as a dependency of itself
50 error If you need help, you may report this error at:
50 error     <https://github.com/npm/npm/issues>
51 verbose exit [ 1, true ]

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:

**Comment by kenany** [comment]
Ensure that the `"name"` field in your `package.json` is not set to `"bitmovin-javascript"`. Try setting it to something more unique :)

**Comment by kenany** [comment]
Closing as abandoned.
