### ISSUE TITLE
Your requested host "registry.npms.org" could not be resolved by DNS

### ISSUE THREAD

**Issue by vmylarap** [npm/npm#18590]
#### I'm opening this issue because:

  - [ ]  npm install npm@latest -g  is not working
  

### supporting information:

 0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Softwares\\node-v6.11.3-win-x64\\node.exe',
1 verbose cli   'C:\\Softwares\\node-v6.11.3-win-x64\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'npm@latest',
1 verbose cli   '-g' ]
2 info using npm@3.10.10
3 info using node@v6.11.3
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData npm@latest
8 silly fetchNamedPackageData npm
9 silly mapToRegistry name npm
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry http://registry.npms.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'npm',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'npm',
12 silly mapToRegistry   name: 'npm',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri http://registry.npms.org/npm
14 verbose request uri http://registry.npms.org/npm
15 verbose request no auth needed
16 info attempt registry request try #1 at 2:04:28 PM
17 verbose request id ecdd89d0772d83c8
18 http request GET http://registry.npms.org/npm
19 http 404 http://registry.npms.org/npm
20 verbose bad json <HTML><HEAD>
20 verbose bad json <TITLE>Network Error</TITLE>
20 verbose bad json </HEAD>
20 verbose bad json <BODY>
20 verbose bad json <FONT face="Helvetica">
20 verbose bad json <big><strong></strong></big><BR>
20 verbose bad json </FONT>
20 verbose bad json <blockquote>
20 verbose bad json <TABLE border=0 cellPadding=1 width="80%">
20 verbose bad json <TR><TD>
20 verbose bad json <FONT face="Helvetica">
20 verbose bad json <big>Network Error (dns_unresolved_hostname)</big>
20 verbose bad json <BR>
20 verbose bad json <BR>
20 verbose bad json </FONT>
20 verbose bad json </TD></TR>
20 verbose bad json <TR><TD>
20 verbose bad json <FONT face="Helvetica">
20 verbose bad json Your requested host "registry.npms.org" could not be resolved by DNS.
20 verbose bad json </FONT>
20 verbose bad json </TD></TR>
20 verbose bad json <TR><TD>
20 verbose bad json <FONT face="Helvetica">
20 verbose bad json
20 verbose bad json </FONT>
20 verbose bad json </TD></TR>
20 verbose bad json <TR><TD>
20 verbose bad json <FONT face="Helvetica" SIZE=2>
20 verbose bad json <BR>
20 verbose bad json For assistance, contact the Helpdesk at extension +1 (650) 432-4357 or tieline 6 (720)4357. <p>Proxy = na975cr01blbc01</p>
20 verbose bad json </FONT>
20 verbose bad json </TD></TR>
20 verbose bad json </TABLE>
20 verbose bad json </blockquote>
20 verbose bad json </FONT>
20 verbose bad json </BODY></HTML>
21 error registry error parsing json
22 verbose headers { 'cache-control': 'no-cache',
22 verbose headers   pragma: 'no-cache',
22 verbose headers   'content-type': 'text/html; charset=utf-8',
22 verbose headers   'proxy-connection': 'Keep-Alive',
22 verbose headers   connection: 'Keep-Alive',
22 verbose headers   'content-length': '735' }
23 silly get cb [ 404,
23 silly get   { 'cache-control': 'no-cache',
23 silly get     pragma: 'no-cache',
23 silly get     'content-type': 'text/html; charset=utf-8',
23 silly get     'proxy-connection': 'Keep-Alive',
23 silly get     connection: 'Keep-Alive',
23 silly get     'content-length': '735' } ]
24 silly fetchPackageMetaData SyntaxError: Unexpected token < in JSON at position 0
24 silly fetchPackageMetaData <HTML><HEAD>
24 silly fetchPackageMetaData <TITLE>Network Error</TITLE>
24 silly fetchPackageMetaData </HEAD>
24 silly fetchPackageMetaData <BODY>
24 silly fetchPackageMetaData <FONT face="Helvetica">
24 silly fetchPackageMetaData <big><strong></strong></big><BR>
24 silly fetchPackageMetaData </FONT>
24 silly fetchPackageMetaData <blockquote>
24 silly fetchPackageMetaData <TABLE border=0 cellPadding=1 width="80%">
24 silly fetchPackageMetaData <TR><TD>
24 silly fetchPackageMetaData <FONT face="Helvetica">
24 silly fetchPackageMetaData <big>Network Error (dns_unresolved_hostname)</big>
24 silly fetchPackageMetaData <BR>
24 silly fetchPackageMetaData <BR>
24 silly fetchPackageMetaData </FONT>
24 silly fetchPackageMetaData </TD></TR>
24 silly fetchPackageMetaData <TR><TD>
24 silly fetchPackageMetaData <FONT face="Helvetica">
24 silly fetchPackageMetaData Your requested host "registry.npms.org" could not be resolved by DNS.
24 silly fetchPackageMetaData </FONT>
24 silly fetchPackageMetaData </TD></TR>
24 silly fetchPackageMetaData <TR><TD>
24 silly fetchPackageMetaData <FONT face="Helvetica">
24 silly fetchPackageMetaData
24 silly fetchPackageMetaData </FONT>
24 silly fetchPackageMetaData </TD></TR>
24 silly fetchPackageMetaData <TR><TD>
24 silly fetchPackageMetaData <FONT face="Helvetica" SIZE=2>
24 silly fetchPackageMetaData <BR>
24 silly fetchPackageMetaData For assistance, contact the Helpdesk at extension +1 (650) 432-4357 or tieline 6 (720)4357. <p>Proxy = na975cr01blbc01</p>
24 silly fetchPackageMetaData </FONT>
24 silly fetchPackageMetaData </TD></TR>
24 silly fetchPackageMetaData </TABLE>
24 silly fetchPackageMetaData </blockquote>
24 silly fetchPackageMetaData </FONT>
24 silly fetchPackageMetaData </BODY></HTML>
24 silly fetchPackageMetaData
24 silly fetchPackageMetaData     at Object.parse (native)
24 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (C:\Softwares\node-v6.11.3-win-x64\node_modules\npm\node_modules\npm-registry-client\lib\request.js:237:23)
24 silly fetchPackageMetaData     at Request._callback (C:\Softwares\node-v6.11.3-win-x64\node_modules\npm\node_modules\npm-registry-client\lib\request.js:210:14)
24 silly fetchPackageMetaData     at Request.self.callback (C:\Softwares\node-v6.11.3-win-x64\node_modules\npm\node_modules\request\request.js:187:22)
24 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
24 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
24 silly fetchPackageMetaData     at Request.<anonymous> (C:\Softwares\node-v6.11.3-win-x64\node_modules\npm\node_modules\request\request.js:1048:10)
24 silly fetchPackageMetaData     at emitOne (events.js:96:13)
24 silly fetchPackageMetaData     at Request.emit (events.js:188:7)
24 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (C:\Softwares\node-v6.11.3-win-x64\node_modules\npm\node_modules\request\request.js:969:12)
24 silly fetchPackageMetaData  error for npm@latest SyntaxError: Unexpected token < in JSON at position 0
24 silly fetchPackageMetaData <HTML><HEAD>
24 silly fetchPackageMetaData <TITLE>Network Error</TITLE>
24 silly fetchPackageMetaData </HEAD>
24 silly fetchPackageMetaData <BODY>
24 silly fetchPackageMetaData <FONT face="Helvetica">
24 silly fetchPackageMetaData <big><strong></strong></big><BR>
24 silly fetchPackageMetaData </FONT>
24 silly fetchPackageMetaData <blockquote>
24 silly fetchPackageMetaData <TABLE border=0 cellPadding=1 width="80%">
24 silly fetchPackageMetaData <TR><TD>
24 silly fetchPackageMetaData <FONT face="Helvetica">
24 silly fetchPackageMetaData <big>Network Error (dns_unresolved_hostname)</big>
24 silly fetchPackageMetaData <BR>
24 silly fetchPackageMetaData <BR>
24 silly fetchPackageMetaData </FONT>
24 silly fetchPackageMetaData </TD></TR>
24 silly fetchPackageMetaData <TR><TD>
24 silly fetchPackageMetaData <FONT face="Helvetica">
24 silly fetchPackageMetaData Your requested host "registry.npms.org" could not be resolved by DNS.
24 silly fetchPackageMetaData </FONT>
24 silly fetchPackageMetaData </TD></TR>
24 silly fetchPackageMetaData <TR><TD>
24 silly fetchPackageMetaData <FONT face="Helvetica">
24 silly fetchPackageMetaData
24 silly fetchPackageMetaData </FONT>
24 silly fetchPackageMetaData </TD></TR>
24 silly fetchPackageMetaData <TR><TD>
24 silly fetchPackageMetaData <FONT face="Helvetica" SIZE=2>
24 silly fetchPackageMetaData <BR>
24 silly fetchPackageMetaData For assistance, contact the Helpdesk at extension +1 (650) 432-4357 or tieline 6 (720)4357. <p>Proxy = na975cr01blbc01</p>
24 silly fetchPackageMetaData </FONT>
24 silly fetchPackageMetaData </TD></TR>
24 silly fetchPackageMetaData </TABLE>
24 silly fetchPackageMetaData </blockquote>
24 silly fetchPackageMetaData </FONT>
24 silly fetchPackageMetaData </BODY></HTML>
24 silly fetchPackageMetaData
24 silly fetchPackageMetaData     at Object.parse (native)
24 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (C:\Softwares\node-v6.11.3-win-x64\node_modules\npm\node_modules\npm-registry-client\lib\request.js:237:23)
24 silly fetchPackageMetaData     at Request._callback (C:\Softwares\node-v6.11.3-win-x64\node_modules\npm\node_modules\npm-registry-client\lib\request.js:210:14)
24 silly fetchPackageMetaData     at Request.self.callback (C:\Softwares\node-v6.11.3-win-x64\node_modules\npm\node_modules\request\request.js:187:22)
24 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
24 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
24 silly fetchPackageMetaData     at Request.<anonymous> (C:\Softwares\node-v6.11.3-win-x64\node_modules\npm\node_modules\request\request.js:1048:10)
24 silly fetchPackageMetaData     at emitOne (events.js:96:13)
24 silly fetchPackageMetaData     at Request.emit (events.js:188:7)
24 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (C:\Softwares\node-v6.11.3-win-x64\node_modules\npm\node_modules\request\request.js:969:12)
25 silly rollbackFailedOptional Starting
26 silly rollbackFailedOptional Finishing
27 silly runTopLevelLifecycles Finishing
28 silly install printInstalled
29 verbose stack SyntaxError: Unexpected token < in JSON at position 0
29 verbose stack <HTML><HEAD>
29 verbose stack <TITLE>Network Error</TITLE>
29 verbose stack </HEAD>
29 verbose stack <BODY>
29 verbose stack <FONT face="Helvetica">
29 verbose stack <big><strong></strong></big><BR>
29 verbose stack </FONT>
29 verbose stack <blockquote>
29 verbose stack <TABLE border=0 cellPadding=1 width="80%">
29 verbose stack <TR><TD>
29 verbose stack <FONT face="Helvetica">
29 verbose stack <big>Network Error (dns_unresolved_hostname)</big>
29 verbose stack <BR>
29 verbose stack <BR>
29 verbose stack </FONT>
29 verbose stack </TD></TR>
29 verbose stack <TR><TD>
29 verbose stack <FONT face="Helvetica">
29 verbose stack Your requested host "registry.npms.org" could not be resolved by DNS.
29 verbose stack </FONT>
29 verbose stack </TD></TR>
29 verbose stack <TR><TD>
29 verbose stack <FONT face="Helvetica">
29 verbose stack
29 verbose stack </FONT>
29 verbose stack </TD></TR>
29 verbose stack <TR><TD>
29 verbose stack <FONT face="Helvetica" SIZE=2>
29 verbose stack <BR>
29 verbose stack For assistance, contact the Helpdesk at extension +1 (650) 432-4357 or tieline 6 (720)4357. <p>Proxy = na975cr01blbc01</p>
29 verbose stack </FONT>
29 verbose stack </TD></TR>
29 verbose stack </TABLE>
29 verbose stack </blockquote>
29 verbose stack </FONT>
29 verbose stack </BODY></HTML>
29 verbose stack
29 verbose stack     at Object.parse (native)
29 verbose stack     at CachingRegistryClient.<anonymous> (C:\Softwares\node-v6.11.3-win-x64\node_modules\npm\node_modules\npm-registry-client\lib\request.js:237:23)
29 verbose stack     at Request._callback (C:\Softwares\node-v6.11.3-win-x64\node_modules\npm\node_modules\npm-registry-client\lib\request.js:210:14)
29 verbose stack     at Request.self.callback (C:\Softwares\node-v6.11.3-win-x64\node_modules\npm\node_modules\request\request.js:187:22)
29 verbose stack     at emitTwo (events.js:106:13)
29 verbose stack     at Request.emit (events.js:191:7)
29 verbose stack     at Request.<anonymous> (C:\Softwares\node-v6.11.3-win-x64\node_modules\npm\node_modules\request\request.js:1048:10)
29 verbose stack     at emitOne (events.js:96:13)
29 verbose stack     at Request.emit (events.js:188:7)
29 verbose stack     at IncomingMessage.<anonymous> (C:\Softwares\node-v6.11.3-win-x64\node_modules\npm\node_modules\request\request.js:969:12)
30 verbose cwd C:\Softwares\node-v6.11.3-win-x64
31 error Windows_NT 10.0.14393
32 error argv "C:\\Softwares\\node-v6.11.3-win-x64\\node.exe" "C:\\Softwares\\node-v6.11.3-win-x64\\node_modules\\npm\\bin\\npm-cli.js" "install" "npm@latest" "-g"
33 error node v6.11.3
34 error npm  v3.10.10
35 error Unexpected token < in JSON at position 0
35 error <HTML><HEAD>
35 error <TITLE>Network Error</TITLE>
35 error </HEAD>
35 error <BODY>
35 error <FONT face="Helvetica">
35 error <big><strong></strong></big><BR>
35 error </FONT>
35 error <blockquote>
35 error <TABLE border=0 cellPadding=1 width="80%">
35 error <TR><TD>
35 error <FONT face="Helvetica">
35 error <big>Network Error (dns_unresolved_hostname)</big>
35 error <BR>
35 error <BR>
35 error </FONT>
35 error </TD></TR>
35 error <TR><TD>
35 error <FONT face="Helvetica">
35 error Your requested host "registry.npms.org" could not be resolved by DNS.
35 error </FONT>
35 error </TD></TR>
35 error <TR><TD>
35 error <FONT face="Helvetica">
35 error
35 error </FONT>
35 error </TD></TR>
35 error <TR><TD>
35 error <FONT face="Helvetica" SIZE=2>
35 error <BR>
35 error For assistance, contact the Helpdesk at extension +1 (650) 432-4357 or tieline 6 (720)4357. <p>Proxy = na975cr01blbc01</p>
35 error </FONT>
35 error </TD></TR>
35 error </TABLE>
35 error </blockquote>
35 error </FONT>
35 error </BODY></HTML>
36 error If you need help, you may report this error at:
36 error     <https://github.com/npm/npm/issues>
37 verbose exit [ 1, true ]

**Comment by kenany** [comment]
@vmylarap How about?:

```
npm config set registry https://registry.npmjs.org/
```

**Comment by vmylarap** [comment]
It worked when i removed the 'registry.npmjs.org' from .npmrc file.
Steps to do that
1) run 'npm config edit'
2) remove  registry.npmjs.org
