### ISSUE TITLE
I am trying to start/run one angular project in ubuntu system , so these eerors are coming , but same process I followed in windows so it run successfully, please help to resolve it.

### ISSUE THREAD

**Issue by ruchiapogaeis** [npm/npm#18593]
$ npm start

 70% 3/3 build modules http://localhost:8080/
webpack result is served from http://localhost:8080/
content is served from /home/ruchi/Desktop/gigabyte
404s will fallback to /index.html
 40% 5/10 build modules
[at-loader] Using typescript@2.5.2 from typescript and "tsconfig.json" from /home/ruchi/Desktop/gigabyte/tsconfig.json.

 37% 14/31 build modulesBus error (core dumped)

npm ERR! Linux 4.4.0-93-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! angular2-webpack-starter@1.0.0 start: `webpack-dev-server --inline --progress --port 8080`
npm ERR! Exit status 135
npm ERR! 
npm ERR! Failed at the angular2-webpack-starter@1.0.0 start script 'webpack-dev-server --inline --progress --port 8080'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-webpack-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --inline --progress --port 8080
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-webpack-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-webpack-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ruchi/Desktop/gigabyte/npm-debug.log

**Comment by kenany** [comment]
Log indicates that this is coming from:

```
webpack-dev-server --inline --progress --port 8080
```

All `npm` is doing here is catching it and letting you know about it.
