### ISSUE TITLE
High Compilation Time

### ISSUE THREAD

**Issue by LazyCoder007** [npm/npm#18600]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by LazyCoder007** [comment]
My angualr 2 application takes a lot of time to complie when using npm start. Also, when I make a small change in app(adding of space), it takes around 4 mins to recompile. If there are many chnages, then it takes around 10 mins to copmile. Please, help me solve this isue.

**Comment by kenany** [comment]
Sounds like whatever you have set as your `"start"` script is slow, not `npm` itself.
