### ISSUE TITLE
Error: failed to fetch

### ISSUE THREAD

**Issue by CosmicWebServices** [npm/npm#18602]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ x ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

```
✖ Running command - failed!
[ERROR] Exception: Using cordova-fetch for cordova-ios@^4.5.0

        Error: Failed to fetch platform cordova-ios@^4.5.0
        Probably this is either a connection problem, or platform spec is incorrect.
        Check your connection and platform name/version/URL.
        Error: npm: Command failed with exit code 1 Error output:
        npm ERR! Darwin 17.0.0
        npm ERR! argv "/usr/local/bin/node" "/Users/andrewrodebaugh/aqua/node_modules/.bin/npm" "install" 
        "cordova-ios@^4.5.0" "--save"
        npm ERR! node v6.11.3
        npm ERR! npm  v2.15.12
        npm ERR! code EPEERINVALID
        
        npm ERR! peerinvalid The package @angular/common@4.4.3 does not satisfy its siblings' peerDependencies 
        requirements!
        npm ERR! peerinvalid Peer @angular/forms@4.4.3 wants @angular/common@4.4.3
        npm ERR! peerinvalid Peer @angular/platform-browser@4.4.3 wants @angular/common@4.4.3
        npm ERR! peerinvalid Peer @angular/platform-browser-dynamic@4.4.3 wants @angular/common@4.4.3
        npm ERR! peerinvalid Peer @angular/platform-server@4.4.3 wants @angular/common@4.4.3
        npm ERR! peerinvalid Peer @angular/router@4.4.3 wants @angular/common@4.4.3
        npm ERR! peerinvalid Peer ionic-angular@3.6.1 wants @angular/common@4.1.3
        
        npm ERR! Please include the following file with any support request:
        npm ERR!     /Users/andrewrodebaugh/aqua/node_modules/npm-debug.log
```

#### How can the CLI team reproduce the problem?

npm-log:

https://gist.github.com/CosmicWebServices/d81ae61f49958dc9bc5b59ed9266d123

This might be an npm problem or an Ionic framework problem I made an issue on both.

### supporting information:

 - `npm -v` prints: 5.4.2
 - `node -v` prints: v6.11.3
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: MacOS
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by petrot** [comment]
Same problem here :|

**Comment by CosmicWebServices** [comment]
I fixed it these are the rough instructions on how I fixed it:
- Uninstalled npm
- Reinstalled npm/nodejs
- `npm install npm -g`
Other errors popped up fixed those one by one may be different depending on the situation

**Comment by petrot** [comment]
I found a working solution [here](https://github.com/ngx-rocket/generator-ngx-rocket/issues/121)

With local npm, adding a platform works well.

> For those having this issue, a workaround is to manually install a newer npm version locally after the "normal" npm install:
npm install --save-dev npm@latest
