### ISSUE TITLE
npm install wrong

### ISSUE THREAD

**Issue by superermiao** [npm/npm#18609]
e:\node\OnlineRetailers>npm install
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "D:\\Program Files\\nodejs\\node_modules\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! code E401

npm ERR! 401 Unauthorized
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     e:\node\OnlineRetailers\npm-debug.log

**Comment by CuteDili** [comment]
Hi superermiao, I got same problem. But fortunately i fixed it.
- npm uninstall -g appium 
- npm install -g npm@3.10.10
- npm install appium -g
