### ISSUE TITLE
Electron installation fails.

### ISSUE THREAD

**Issue by mrtordoide** [npm/npm#18616]
When I hit `sudo npm install electron` , I get the following output:

> npm ERR! Linux 4.10.0-35-generic
> npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "electron"
> npm ERR! node v6.11.3
> npm ERR! npm  v3.10.10
> npm ERR! code EAI_AGAIN
> npm ERR! errno EAI_AGAIN
> npm ERR! syscall getaddrinfo
> 
> npm ERR! getaddrinfo EAI_AGAIN registry.npmjs.org:443
> npm ERR! 
> npm ERR! If you need help, you may report this error at:
> npm ERR!     <https://github.com/npm/npm/issues>

Also, I have the nodejs v6.11.3 and npm v3.10.10. I am using Ubuntu 16.04.3

**Comment by vutran** [comment]
Seems like a DNS lookup timeout error. You'll want to make sure you're on a reliable internet connection and try again.
