### ISSUE TITLE
@angular/cli  is producing an incorrect install.

### ISSUE THREAD

**Issue by jzsplk** [npm/npm#18636]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "@angular/cli@latest"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10

npm ERR! shasum check failed for /var/folders/rn/czylgq1j6f97zhcwzjt4s1lr0000gn/T/npm-3878-82a2f2ae/registry.npmjs.org/lodash/-/lodash-4.17.4.tgz
npm ERR! Expected: 78203a4d1c328ae1d86dca6460e369b57f4055ae
npm ERR! Actual:   d2a0a0c624fcd472204703cfd01fd338b2ae55f0
npm ERR! From:     https://registry.npmjs.org/lodash/-/lodash-4.17.4.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>#### How can the CLI team reproduce the problem?

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
macOS
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
Does this also occur with `npm` v5?

**Comment by JasonFoglia** [comment]
Did you try sudo on Mac/Linux? Run CMD/Code/VS/PS as Admin on Win?

**Comment by kenany** [comment]
Closing due to no response.
