### ISSUE TITLE
npm install doesn't install the specified version from package.json

### ISSUE THREAD

**Issue by zhyinjun** [npm/npm#18640]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

---->package.json<-----

"dependencies": {
    "zone.js": "^0.8.16"
  },

execute npm install, 
got "zone.js@0.8.17 " installed,

#### How can the CLI team reproduce the problem?

npm install

### supporting information:

 - `npm -v` prints: 3.10.10
 - `node -v` prints: 6.9.5
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [x] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
If you specifically want `zone.js@0.8.16`, you can do:

```json
{
  "dependencies": {
    "zone.js": "0.8.16"
  }
}
```

**Comment by zhyinjun** [comment]
Thx, works for me.
