### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by lvyulong** [npm/npm#18652]
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\n
node_modules\\npm\\bin\\npm-cli.js" "install" "webpack" "--save-dev"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ENOSELF

npm ERR! Refusing to install webpack as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     F:\myDocument\Project\private\www\web\webpack\npm-debug.log

**Comment by kenany** [comment]
Ensure that the `"name"` field in your `package.json` is not set to `"webpack"`. Try setting it to something more unique :)

**Comment by meime** [comment]
npm install --global vue-cli
loadRequestedDeps → netwo ▐ ╢██████░░░░░░░░░npm ERR! Darwin 16.5.0
npm ERR! argv "/Users/lillian/.nvm/versions/node/v6.0.0/bin/node" "/Users/lillian/.nvm/versions/node/v6.0.0/bin/npm" "install" "--global" "vue-cli"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6

npm ERR! shasum check failed for /var/folders/84/cz_40rzs15v90d41rh1stf540000gn/T/npm-59804-b07e12f0/registry.npmjs.org/vue-cli/-/vue-cli-2.8.2.tgz
npm ERR! Expected: 27e81510c79f82ffd4af52c8ace4764a34fe1abd
npm ERR! Actual:   5bc0d176555fa11069bde7bd412da8a3bb493002
npm ERR! From:     https://registry.npmjs.org/vue-cli/-/vue-cli-2.8.2.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
^C

**Comment by kenany** [comment]
Closing due to no response.

@meime Feel free to open a new ticket if you wish to pursue your unrelated issue.
