### ISSUE TITLE
Package install failed

### ISSUE THREAD

**Issue by hanmant-sapkal** [npm/npm#18661]
**Command:**
`ng new my-app`

**Error log:**

`error Linux 3.13.0-55-generic`
`error argv "/home/vagrant/.nvm/versions/node/v6.11.3/bin/node" "/home/vagrant/.nvm/versions/node/v6.11.3/bin/npm" "--quiet" "install"`
`error node v6.11.3`
`error npm  v3.10.10`
`error path ../acorn/bin/acorn`
`error code EIO`
`error errno -5`
`error syscall symlink`
`error EIO: i/o error, symlink '../acorn/bin/acorn' -> '/var/www/angularjs/my-app/node_modules/.bin/acorn'`
`error If you need help, you may report this error at:`
`error     <https://github.com/npm/npm/issues>`
`verbose exit [ -5, true ]`

**Supporting information:**
 - Host OS: Windows-10
 - Guest OS: Ubuntu 14.04.3 LTS

I manage virtual box using Vagrant and Scotchbox.
Trying to create project on Guest OS.

**Complete log file:**

[npm-debug.log](https://github.com/npm/npm/files/1343643/npm-debug.log)

**Comment by kenany** [comment]
Does this also occur with the `--no-bin-links` flag?

**Comment by hanmant-sapkal** [comment]
Okay, let me try with --no-bin-links flag.

On 29 Sep 2017 19:31, "Kenan Yildirim" <notifications@github.com> wrote:

Does this also occur with the --no-bin-links flag?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/npm/npm/issues/18661#issuecomment-333134268>, or mute
the thread

**Comment by kenany** [comment]
Closing for now, can reopen if the flag doesn't solve your issue.
