### ISSUE TITLE
error installing bitgo

### ISSUE THREAD

**Issue by tomanexchange** [npm/npm#18675]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [1 ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I want to install Bitgo SDK by using this command but i have problem
npm install bitgo --save
i got error

### supporting information:
these are the last lines of lines on the screen:

 - `npm -v` prints: 3.10.10
 - `node -v` prints: v6.11.3
 - `npm config get registry` prints:  https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux CentOS 6.9
 - Network issues:
   - Geographic location where npm was run: USA
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
Could you try uploading the full debug log to <https://gist.github.com/> and linking it here? Thanks!

**Comment by tomanexchange** [comment]
can you please help me now where is that log file?

**Comment by kenany** [comment]
It should say it in the error output itself.

**Comment by kenany** [comment]
Closing due to no response.
