### ISSUE TITLE
npm install python-shell throughing error

### ISSUE THREAD

**Issue by naveenhuttad** [npm/npm#18684]
45 error Windows_NT 10.0.15063
46 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "python-shell"
47 error node v6.11.3
48 error npm  v3.10.10
49 error code ENOSELF
50 error Refusing to install python-shell as a dependency of itself
51 error If you need help, you may report this err

**Comment by kenany** [comment]
Ensure that the `"name"` field in your `package.json` is not set to `"python-shell"`. Try setting it to something more unique :)
