### ISSUE TITLE
npm ERR! enoent ENOENT: no such file or directory

### ISSUE THREAD

**Issue by rutvikpensionwar** [npm/npm#18685]
I am new to react/node and whenever I try to start my project using `npm start` it gives me following error.
```
E:\1\273\Projects\LoginAppReactJS\LoginAppReactJS>npm start
npm ERR! path E:\1\273\Projects\LoginAppReactJS\LoginAppReactJS\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open 'E:\1\273\Projects\LoginAppReactJS\LoginAppReactJS\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Rutvik\AppData\Roaming\npm-cache\_logs\2017-10-02T05_55_47_067Z-debug.log
```
`LoginAppReactJS` is an existing project which I made a local copy of and running via WebStorm IDE.

**Comment by kenany** [comment]
Does `E:\1\273\Projects\LoginAppReactJS\LoginAppReactJS\package.json` exist?

**Comment by rutvikpensionwar** [comment]
I have got the solution. I guess there were issues with npm installation. It's running fine now. Thanks. 
You may close the issue.

**Comment by kotivada** [comment]
could you please explain how did you resolve the above error?
