### ISSUE TITLE
npm couldn't install angular-cli in a whole day PLZZ HELP

### ISSUE THREAD

**Issue by hussainwali74** [npm/npm#18681]
#### I'm opening this issue because:

My eyes are hurting, tried to install to install angular cli and I have tried everything this has wasted a whole fucking day, I have tried literally everything
 
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! path C:\Users\hussain\AppData\Roaming\npm\node_modules\.staging\@ngtools\webpack-ddafdeae
npm ERR! code EXDEV
npm ERR! errno -4037
npm ERR! syscall rename

npm ERR! EXDEV: cross-device link not permitted, rename 'C:\Users\hussain\AppData\Roaming\npm\node_modules\.staging\@ngtools\webpack-ddafdeae' -> 'C:\Users\hussain\A
ppData\Roaming\npm\node_modules\@angular\cli\node_modules\@ngtools\webpack'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
 
[npm-debug.log](https://github.com/npm/npm/files/1347484/npm-debug.log)

**Comment by strugee** [comment]
It looks like you have something super weird going on with your homedir setup. Do you have multiple drives or something?

You might also try installing npm 5. npm 3 is pretty old now.

**Comment by hussainwali74** [comment]
@strugee Thank you soo much for the reply.
yes I have multiple drives 
I installed npm 5 following your suggestion and now it doesn't even run: Gives me all these errors please help
[2017-10-02T07_16_25_600Z-debug.log](https://github.com/npm/npm/files/1348136/2017-10-02T07_16_25_600Z-debug.log)

**Comment by hussainwali74** [comment]
Please check this error:

sha1-EFSVrlNh1pe9GVyCUZLhrX8lN4c= integrity checksum failed when using sha1: wanted sha1-EFSVrlNh1pe9GVyCUZLhrX8lN4c= but got sha1-G5QbswcriH4k8hynGA2DUZBE4
lc=. (2759 bytes)

[2017-10-02T11_02_29_701Z-debug.log](https://github.com/npm/npm/files/1348689/2017-10-02T11_02_29_701Z-debug.log)
