### ISSUE TITLE
Unable to get Issuer Certificate Locally

### ISSUE THREAD

**Issue by JingAustria** [npm/npm#18694]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [X] npm is producing an incorrect install.
  - [X] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "angular-cli"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code UNABLE_TO_GET_ISSUER_CERT_LOCALLY

npm ERR! unable to get local issuer certificate
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\eta\npm-debug.log

#### How can the CLI team reproduce the problem?

I just issue command:
npm install -g angular-cli

### supporting information:
 - `npm -v` prints: 3.10.10
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows

**Comment by JingAustria** [comment]
[npm-debug.log](https://github.com/npm/npm/files/1351082/npm-debug.log)

Additional information

**Comment by ozarkmountainman** [comment]
[npm-debug.log](https://github.com/npm/npm/files/1356463/npm-debug.log)
Another log for you to review.
