### ISSUE TITLE
error installing angular-google-maps

### ISSUE THREAD

**Issue by psinkinson** [npm/npm#18699]
#### I'm opening this issue because:

"npm install" is failing to pull down github.com/nmccready/google-maps-utility-library-v3-markerwithlabel.git

#### What's going wrong?
We have a dependency on angular-google-maps (v 2.4.1). This package depends on github.com/nmccready/google-maps-utility-library-v3-markerwithlabel.git
on running npm install, the following error is being given : 
Cloning into bare repository '/Users/paul/.npm/_git-remotes/git-github-com-nmccready-google-maps-utility-library-v3-markerwithlabel-git-535ad55b'...
npm ERR! fatal: read error: Connection reset by peer

We can still browse to https://github.com/nmccready/google-maps-utility-library-v3-markerwithlabel successfuly.
However attempts to clone the repo fail with the same "Connection reset by peer" error.

#### How can the CLI team reproduce the problem?

clone this repo from the command line

### supporting information:

running mac
Thanks you

Paul Sinkinson

**Comment by kenany** [comment]
If just plain `git` is giving you this error, then how is this an issue with `npm` itself?

**Comment by psinkinson** [comment]
Hi,
Sorry this is a mistake on my part.
This looks like a git issue, not an npm issue, as the rep is browse-able but not clone-able.
(The New Issue template only offers 4 options for why you are opening the issue. I guess that they are suggestions rather than options).
Thanks

Paul
