### ISSUE TITLE
NPM not installing the @latest

### ISSUE THREAD

**Issue by c0debreaker** [npm/npm#18691]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Npm 5.4.2 is not installing latest even if it's available on local npm registry. I'm expecting it to install 1.0.3 when I execute `npm install lib1@latest`. Instead, 1.0.2 is getting installed.

Here is the output of `npm info lib1`. You can see 1.0.3

```
 ❯ npm info lib1

{ name: 'lib1',
  versions: [ '0.0.1', '1.0.0', '1.0.1', '1.0.2', '1.0.3', '1.0.4-rc.1' ],
  'dist-tags':
   { latest: '1.0.2',
     beta: '1.0.2',
     alpha: '1.0.1',
     rc1: '1.0.4-rc.1',
     rc2: '1.0.3' },
  version: '1.0.2',
  description: '',
  main: 'index.js',
  scripts: { test: 'echo "Error: no test specified" && exit 1' },
  author: '',
  license: 'ISC',
  dependencies: { lib2: '^1.0.0' },
  dist:
   { integrity: 'sha512-nLh/QJWBGcRqDXVKXyssiTlTFrDBWPCDITDOAz3JhF4fUSR8PTDe2iyovWs9rwp9eJykgnc7pXUsX0ZJQmMYOA==',
     shasum: 'ff47ab62cad3c6c71d3bc21ef6791957e020649d',
     tarball: 'http://localhost:4873/lib1/-/lib1-1.0.2.tgz' } }
```

Here is package.json
```
{
  "name": "mainapp",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {},
  "dependencies": {
    "lib1": "^1.0.2"
  }
}
```
Or was it because I started using `dist-tag add` and it messed up the entries? I see latest at 1.0.2 above. Does it mean that we'll have to execute `npm dist-tag add lib1@1.0.3 latest` from now on? I just tried it and my assumption was right.

**Comment by kenany** [comment]
Yes, if you want to tag a particular version as `latest`, then `npm dist-tag add` is the way to go.

**Comment by c0debreaker** [comment]
Got it. I got confused because I thought that npm will know automatically and update latest automatically since it was doing it automatically before I started using `dist-tag`

**Comment by kenany** [comment]
Hmm, I think it should be automatically tagging new publishes with `latest`. Is it not?

**Comment by c0debreaker** [comment]
I was wrong. However, I'm trying to figure out why 1.0.2 became the latest when 1.0.3 was also present. I'm looking at the unix history to see what I did.

**Comment by c0debreaker** [comment]
I figured it out how to recreate the scenario. I think it's not a bug. Here is what I did
1. increment patch version say 1.0.12 then `npm publish`, it becomes the latest
2. increment patch version, now it's 1.0.13 then run `npm publish --tag rc5`, it doesn't become the latest

I just finished running `npm publish --tag rc5`. Here is the latest output of `npm info lib1`
```
 ❯ npm info lib1

{ name: 'lib1',
  versions:
   [ '0.0.1',
     '1.0.0',
     '1.0.1',
     '1.0.2',
     '1.0.3',
     '1.0.4-rc.1',
     '1.0.5-rc.2',
     '1.0.5',
     '1.0.6',
     '1.0.7',
     '1.0.8',
     '1.0.9',
     '1.0.10',
     '1.0.11',
     '1.0.12',
     '1.0.13' ],
  'dist-tags':
   { latest: '1.0.11',
     beta: '1.0.2',
     alpha: '1.0.1',
     rc1: '1.0.4-rc.1',
     rc2: '1.0.3',
     'rc.2': '1.0.6',
     'rc-1.0.7': '1.0.7',
     'rc-1.0.10': '1.0.10',
     rc3: '1.0.11',
     rc4: '1.0.12',
     rc5: '1.0.13' },
  version: '1.0.11',
  description: 'Now with a tag',
  main: 'index.js',
  scripts: { test: 'echo "Error: no test specified" && exit 1' },
  author: '',
  license: 'ISC',
  dependencies: { lib2: '^1.0.0' },
  dist:
   { integrity: 'sha512-nrH2zgAyVoXpxqUeV1k24HuiOkhg7bBwrcWTcd0SNSosKqnKC49U9zz8FkaevS21sttmWZGbdIRdJ4cpt6vKbw==',
     shasum: '6a550b8c239922dcd429be1e0fb9cf95e75d9e71',
     tarball: 'http://localhost:4873/lib1/-/lib1-1.0.11.tgz' } }
```
However, if I only execute `npm publish`, yes it will make it as latest. Now I see why it's an extremely good way to not automate `npm publish`.

**Comment by kenany** [comment]
Yup, specifying the `tag` config [will overwrite the default of `latest`](https://docs.npmjs.com/cli/publish). Glad you figured it out :)

**Comment by c0debreaker** [comment]
Another question though, is there a way to add rc1 to package.json automatically after executing `npm install --save lib1@rc1`? I tried it but it doesn't add it. I was hoping the value would become `"lib1": "^1.0.0@rc1"`. This way when I git push it and other developers pull it, they will also get the `rc1`.

**Comment by kenany** [comment]
Unfortunately there's no automatic way to do it, I think. Manually, you can do `"lib1": "rc1"`

**Comment by c0debreaker** [comment]
Thanks. It worked!
