### ISSUE TITLE
Error while installing react-native-ignite

### ISSUE THREAD

**Issue by Ayakhaled** [npm/npm#18690]
I was running: `sudo npm install -g react-native-ignite`
and gave me this error 
I tried to run: `sudo chown -R $USER:$(id -gn $USER) /home/user/.config`  but nothing happened
> react-native-ignite@1.13.0 postinstall /usr/lib/node_modules/react-native-ignite
> npm i -g generator-react-native-ignite

Unhandled rejection Error: EACCES: permission denied, open '/home/user/.npm/_cacache/tmp/db9b57d2'

┌───────────────────────────────────────────────────────┐
│                npm update check failed                │
│          Try running with sudo or get access          │
│         to the local update config store via          │
│ sudo chown -R $USER:$(id -gn $USER) /home/user/.config │
└───────────────────────────────────────────────────────┘
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2017-10-02T17_13_21_406Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-native-ignite@1.13.0 postinstall: `npm i -g generator-react-native-ignite`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-native-ignite@1.13.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2017-10-02T17_13_28_343Z-debug.log

**Comment by luislobo** [comment]
did you try running the same command but on the /home/user/.npm/ folder? it seems like you have a permissions issue on that folder:
`sudo chown -R $USER:$(id -gn $USER) /home/user/.npm`
