### ISSUE TITLE
"npm profile enable-tfa" not working

### ISSUE THREAD

**Issue by bengummer** [npm/npm#18708]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I am trying to enable 2FA on my npm account. I run `npm profile enable-tfa` and i follow the steps to scan the QR code and enter a resulting 2FA code, but then I get a `Bad Request` error.

#### How can the CLI team reproduce the problem?

1. Clear out `~/.npmrc` file to ensure it is not a config issue
2. `npm login`
3. `npm profile enable-tfa --verbose`
4. Enter npm password when prompted
5. Scan the QR code into 1Password
6. Get a 2FA code from 1Password and enter into npm prompt

npm-debug.log: https://gist.github.com/bengummer/fd2976b0785fa3aa39322cbd2708ed65

The error is coming from here: https://github.com/npm/npm-profile/blob/latest/lib/index.js#L203

### supporting information:

 - `npm -v` prints: 5.5.0
 - `node -v` prints: 6.11.3
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS
 - Network issues:
   - Geographic location where npm was run: San Francisco
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by tiberiuzuld** [comment]
Hi,
Have exact same issue on windows 10.
With command `npm profile enable-tfa auth-and-writes`

**Comment by bengummer** [comment]
Looks like the last line it executes is https://github.com/npm/npm/blob/7dc14c81cc8793261f597fd6360e3ebb1699bfee/lib/profile.js#L256

```
npm profile enable-tfa auth-only --verbose                       
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'profile',
npm verb cli   'enable-tfa',
npm verb cli   'auth-only',
npm verb cli   '--verbose' ]
npm info using npm@5.5.0
npm info using node@v6.11.3
npm verb config Skipping project config: /Users/bgummer/.npmrc. (matches userconfig)
npm notice profile Enabling two factor authentication for auth-only
npm password: 
npm info profile Determine if tfa is pending
npm info profile Resetting two-factor authentication
npm info profile Setting two factor authentication to auth-only
Scan into your authenticator app:
[QR CODE IMAGE REMOVED]
 Or enter code: [2FA SECRET CODE REMOVED]
And an OTP code from your authenticator: [6 DIGIT 2FA CODE REMOVED]
npm info profile Finalizing two factor authentication
npm verb stack Error: Bad Request
npm verb stack     at fetch.defaults.then.then.result (/usr/local/lib/node_modules/npm/node_modules/npm-profile/index.js:203:19)
npm verb stack     at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by bengummer** [comment]
I can see that the last call of https://github.com/npm/npm-profile/blob/latest/lib/index.js#L85 before the error received the following:

```js
{ profile: { tfa: [ '123456' ] },
  conf: 
   { json: false,
     parseable: false,
     registry: 'https://registry.npmjs.org/',
     otp: 0,
     auth: 
      { scope: '//registry.npmjs.org/',
        token: '[npm-token-removed]',
        password: undefined,
        username: undefined,
        email: undefined,
        auth: undefined,
        alwaysAuth: false } } }
```

**Comment by Marsup** [comment]
I guess they fixed something server-side, it worked for me just now.

**Comment by bengummer** [comment]
Yep looks fixed, worked for me too just now :) Will close this issue.
