### ISSUE TITLE
Installing Angular CLI with npm doesn't work, gives error

### ISSUE THREAD

**Issue by candidreloaded** [npm/npm#18706]
Here is the error log

Amudalats-MacBook-Pro:~ pricelessjewel09$ npm install -g -f angular/cli
npm WARN using --force I sure hope you know what you are doing.
npm ERR! git clone --template=/Users/pricelessjewel09/.npm/_git-remotes/_templates --mirror git@github.com:angular/cli.git /Users/pricelessjewel09/.npm/_git-remotes/git-github-com-angular-cli-git-05516032: Cloning into bare repository '/Users/pricelessjewel09/.npm/_git-remotes/git-github-com-angular-cli-git-05516032'...
npm ERR! git clone --template=/Users/pricelessjewel09/.npm/_git-remotes/_templates --mirror git@github.com:angular/cli.git /Users/pricelessjewel09/.npm/_git-remotes/git-github-com-angular-cli-git-05516032: Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
npm ERR! git clone --template=/Users/pricelessjewel09/.npm/_git-remotes/_templates --mirror git@github.com:angular/cli.git /Users/pricelessjewel09/.npm/_git-remotes/git-github-com-angular-cli-git-05516032: Permission denied (publickey).
npm ERR! git clone --template=/Users/pricelessjewel09/.npm/_git-remotes/_templates --mirror git@github.com:angular/cli.git /Users/pricelessjewel09/.npm/_git-remotes/git-github-com-angular-cli-git-05516032: fatal: Could not read from remote repository.
npm ERR! git clone --template=/Users/pricelessjewel09/.npm/_git-remotes/_templates --mirror git@github.com:angular/cli.git /Users/pricelessjewel09/.npm/_git-remotes/git-github-com-angular-cli-git-05516032: 
npm ERR! git clone --template=/Users/pricelessjewel09/.npm/_git-remotes/_templates --mirror git@github.com:angular/cli.git /Users/pricelessjewel09/.npm/_git-remotes/git-github-com-angular-cli-git-05516032: Please make sure you have the correct access rights
npm ERR! git clone --template=/Users/pricelessjewel09/.npm/_git-remotes/_templates --mirror git@github.com:angular/cli.git /Users/pricelessjewel09/.npm/_git-remotes/git-github-com-angular-cli-git-05516032: and the repository exists.
npm ERR! Darwin 17.0.0
npm ERR! argv "/Users/pricelessjewel09/.nvm/versions/node/v6.11.4/bin/node" "/Users/pricelessjewel09/.nvm/versions/node/v6.11.4/bin/npm" "install" "-g" "-f" "angular/cli"
npm ERR! node v6.11.4
npm ERR! npm  v3.10.10
npm ERR! code 128

npm ERR! Command failed: git clone --template=/Users/pricelessjewel09/.npm/_git-remotes/_templates --mirror git@github.com:angular/cli.git /Users/pricelessjewel09/.npm/_git-remotes/git-github-com-angular-cli-git-05516032
npm ERR! Cloning into bare repository '/Users/pricelessjewel09/.npm/_git-remotes/git-github-com-angular-cli-git-05516032'...
npm ERR! Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/pricelessjewel09/npm-debug.log

**Comment by aiira-co** [comment]
Having the same problem here.
npm ERR! Linux 4.4.0-96-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "@angular/cli@latest"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0

npm ERR! 139919575652160:error:1408F119:SSL routines:SSL3_GET_RECORD:decryption failed or bad record mac:../deps/openssl/openssl/ssl/s3_pkt.c:535:
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 4.4.0-96-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "@angular/cli@latest"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0

npm ERR! shasum check failed for /tmp/npm-4320-fb883cc3/registry.npmjs.org/typescript/-/typescript-2.5.3.tgz
npm ERR! Expected: df3dcdc38f3beb800d4bc322646b04a3f6ca7f0d
npm ERR! Actual:   a92f009f3265ea05719844ce693d80ad3457a982
npm ERR! From:     https://registry.npmjs.org/typescript/-/typescript-2.5.3.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/hashem/.npm/_logs/2017-10-04T15_29_30_180Z-debug.log

**Comment by EvanCarroll** [comment]
The cli is installed with `npm install -g @angular/cli` not `angular/cli`
