### ISSUE TITLE
npm truncates version list and doesn't show recent versions

### ISSUE THREAD

**Issue by iamleeg** [npm/npm#18716]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?

`npm help view` says:

>        For  fields that are arrays, requesting a non-numeric field will return
>        all of the values from the objects in the list.

However, `npm view <package> versions` truncates the list, crucially missing off the most recent versions (which are likely to be the ones I'm interested in).

#### How can the CLI team reproduce the problem?

    $ npm view express versions
 
    [ '0.14.0',
      '0.14.1',
      '1.0.0-beta',
    ...
      '3.3.3',
      '3.3.4',
      ... 157 more items ]

### supporting information:

 - `npm -v` prints: 5.3.0
 - `node -v` prints: v8.5.0
 - `npm config get registry` prints: https://nexus.devwizards.co.uk/repository/npm-all/
 - Windows, OS X/macOS, or Linux?: macOS
 - Network issues:
   - Geographic location where npm was run: UK
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [X] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
https://github.com/npm/npm/issues/16590, https://github.com/npm/npm/pull/16602, https://github.com/npm/npm/pull/18326
