### ISSUE TITLE
Updating npm from 5.3.0 -> 5.4.2 breaks the installation

### ISSUE THREAD

**Issue by alesmenzel** [npm/npm#18724]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Updating npm from 5.3.0 -> 5.4.2 breaks the installation, i am no longer able to use npm commands.

#### How can the CLI team reproduce the problem?

Run `npm i -g npm` on npm 5.3.0
I am running it from elevated powershell.
Node is installed via NVM (https://github.com/coreybutler/nvm-windows)
![command line error image](https://image.prntscr.com/image/zuNVY9wBT6iy9hG6PvkU5Q.png)
See the debug gist: https://gist.github.com/AlesMenzel/c3ed99c5e8c2c11f35e89e8c7e06f1d2

### supporting information:

 - `npm -v` prints: used to print 5.3.0, now the command is not found
 - `node -v` prints: 8.1.4
 - `npm config get registry` prints: -
 - Windows, OS X/macOS, or Linux?: Windows 10

**Comment by meldsza** [comment]
Cannot reproduce the error. I could successfully update from 5.3.0 to 5.4.2
