### ISSUE TITLE
package-lock.json is modified when `npm i` is run

### ISSUE THREAD

**Issue by hrdwdmrbl** [npm/npm#18738]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

When I run `npm i`, my package-lock.json is modified.

For instance, the module `fsevents` is removed when I `npm i` on a machine that does not support `fsevents` and then the module is re-added when one `npm i` again on a machine that does.

This means that two developers working on different operating systems will continuous make changes to the lock file every time one of them runs `npm i`.

#### How can the CLI team reproduce the problem?

I think that if you have a project with a dependency, and that dependency has in its package.json something like
```
"os": [
    "darwin"
],
```
then that package will only be installed on Darwin systems.

If one programmer runs `npm i` on a Darwin system, that dependency will be installed and recorded in the package-lock.json
If a second programmer then clones the project and runs `npm i` on a non-Darwin system, that dependency will not be installed and the dependency will be deleted from package-lock.json

### supporting information:

 - `npm -v` prints:
5.4.2
 - `node -v` prints:
6.11.3
 - `npm config get registry` prints:
https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?:
OSX

**Comment by kenany** [comment]
See https://github.com/npm/npm/issues/18135, https://github.com/npm/npm/issues/18712
