### ISSUE TITLE
Error Darwin 15.4.0

### ISSUE THREAD

**Issue by bhemot** [npm/npm#18740]
Hi to everyone!
The line command I used was: "sudo npm install -g cordova ionic"
This is my error on OSX

npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "cordova" "ionic"
npm ERR! node v6.11.4
npm ERR! npm  v3.10.10

npm ERR! Invalid name: "@ionic/discover"
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Marco/npm-debug.log

Log file:

18119 verbose cwd /Users/Marco
18120 error Darwin 15.4.0
18121 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "cordova" "ionic"
18122 error node v6.11.4
18123 error npm  v3.10.10
18124 error Invalid name: "@ionic/discover"
18125 error If you need help, you may report this error at:
18125 error     <https://github.com/npm/npm/issues>
18126 verbose exit [ 1, true ]

**Comment by kenany** [comment]
Ensure that the `"name"` field in your `package.json` is not empty.
