### ISSUE TITLE
Can't install atom-ftp-editor 0.5.0 from Package Install of Atom

### ISSUE THREAD

**Issue by lagogiampiero** [npm/npm#18754]
#### I'm opening this issue because:

  - can't install the package atom-install-ftp for Atom for Mac

#### What's going wrong?

it says "Installing “atom-ftp-editor@0.5.0” failed."

#### How can the CLI team reproduce the problem?

I've downloaded and installed atom from atom.io site and in the Packages tab
I've select to install atom-ftp-editor from GUI

### supporting information:

 it told me to include this file : /private/var/folders/rd/fdx_9z6d1tv00984k4b943rw0000gn/T/apm-install-dir-11798-78329-kaexn7.hdncxflxr/npm-debug.log but it doesn't exist on my computer

**Comment by Butterfly** [comment]
@lagogiampiero Issue #18748 somehow duplicated a similar error or at least notable glitch. Because of the similar differences, both look potentially dynamically generated:

> /private/var/folders/9c/n55r03bd5yq2kjxb4mv58ggc0000gn/T/npm.5856/package/bin/read-package-json.js

Am pointing your issues toward each other in hopes two instances start showing the pattern that created this. :smile:
