### ISSUE TITLE
Process not starting for some reason need help

### ISSUE THREAD

**Issue by felixrng** [npm/npm#18753]
Error Log:

If i try to start site.js via nodejs site.js it Outputs log4js not installed but it is 

If i start the process via pm2 it Outputs me this:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start', 'site.js' ]
2 info using npm@1.3.10
3 info using node@v0.10.25
4 error Error: ENOENT, open '/var/www/html/Bot/BOT/node_modules/site.js/package.json'
5 error If you need help, you may report this log at:
5 error     <http://github.com/isaacs/npm/issues>
5 error or email it to:
5 error     <npm-@googlegroups.com>
6 error System Linux 3.13.0-125-generic
7 error command "/usr/bin/nodejs" "/usr/bin/npm" "start" "site.js"
8 error cwd /var/www/html/Bot/BOT
9 error node -v v0.10.25
10 error npm -v 1.3.10
11 error path /var/www/html/Bot/BOT/node_modules/site.js/package.json
12 error code ENOENT
13 error errno 34
14 verbose exit [ 34, true ]

**Comment by kenany** [comment]
Your versions of Node.js and `npm` are years old and are no longer supported. Sorry!
