### ISSUE TITLE
Enabling 2FA broke password reset on npmjs.com

### ISSUE THREAD

**Issue by ruchernchong** [npm/npm#18766]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [X] Other (_see below for feature requests_):

#### What's going wrong?
Activating of 2FA on npm account broke the password reset on [npmjs](https://npmjs.com). The new password given by the email is unable to use as the "old password" while trying to change it upon successful login after the reset.

#### How can the CLI team reproduce the problem?
1. Enable 2FA on an account.
2. Request for password reset via forget password on [npmjs](npmjs.com).
3. Click the link in the email specified.
4. Copy the given password and attempt to change it upon successful login.

### supporting information:

 - `npm -v` prints: **v5.5.1**
 - `node -v` prints: **v8.6.0**
 - `npm config get registry` prints: **https://registry.npmjs.org/**
 - Windows, OS X/macOS, or Linux?: **macOS 10.13**
 - Network issues:
   N.A.
 - Container:
   N.A.

**Comment by iarna** [comment]
Thank you for reporting this! I'm going to close this but please don't take that to mean that we aren't working on it. This issue tracker is for the npm CLI, not the npm website. Website issues are here: https://github.com/npm/www

That being said, we have several issues on our internal web issue tracker for this issue already, so please be assured that we'll be fixing it!
