### ISSUE TITLE
node-agent-sdk is not installed 

### ISSUE THREAD

**Issue by SreenivasulaLe** [npm/npm#18771]
Hi,

node-agent-sdk is not installed. Showing below error message(Refusing to install node-agent-sdk as a dependency of itself)

$ npm i node-agent-sdk --save
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "node-agent-sdk" "--save"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ENOSELF

npm ERR! Refusing to install node-agent-sdk as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\workspace\LivePerson\node-agent-sdk-master\npm-debug.log
===================================
 npm install node-agent-sdk
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-agent-sdk"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ENOSELF

npm ERR! Refusing to install node-agent-sdk as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\workspace\LivePerson\node-agent-sdk-master\npm-debug.log
====================
$ npm i node-agent-sdk
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "node-agent-sdk"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ENOSELF

npm ERR! Refusing to install node-agent-sdk as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\workspace\LivePerson\node-agent-sdk-master\npm-debug.log

Thank you.

**Comment by kenany** [comment]
Ensure that the `"name"` field in your `package.json` is not set to `"node-agent-sdk"`. Try setting it to something more unique :)

**Comment by SreenivasulaLe** [comment]
It is working now. Thank you very much.
