### ISSUE TITLE
Add collaborators to private package through web fails.

### ISSUE THREAD

**Issue by lethevimlet** [npm/npm#18785]
Adding collaborators to private package throws the following error:

![image](https://user-images.githubusercontent.com/2963923/31414478-5f36f0aa-ae1e-11e7-905e-a65c336963dd.png)

Note I'm still able to add them through the command line, am I missing something?

**Comment by kenany** [comment]
I think this belongs in <https://github.com/npm/www>.

**Comment by lethevimlet** [comment]
soooo true, my bad i'll open the issue there, thx.
