### ISSUE TITLE
Trying to run a package.json and failing

### ISSUE THREAD

**Issue by DanielSusser** [npm/npm#18783]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### How can the CLI team reproduce the problem?

i think this is my debug log. Any advice? 
Thanks!
https://preview.c9users.io/dsuss/fcc_how-to-npm_1/project_folder/npm-debug.log  
### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
You cannot "run" a `package.json`.

**Comment by DanielSusser** [comment]
Ok - I'm trying to edit a package.Json, are you going to help me out?

**Comment by kenany** [comment]
@DanielSusser You can edit your `package.json` using your favorite text editor.

**Comment by kenany** [comment]
I guess we'll continue this in your new ticket, https://github.com/npm/npm/issues/18907.
