### ISSUE TITLE
I can't update npm in my machine

### ISSUE THREAD

**Issue by rachidadukes** [npm/npm#18794]
#### I'm opening this issue because:
I have Visual Studio 2017 in my machine. I installed node from https://nodejs.org/en/
When I checked the version of node it was version 6.11.4 and the version of npm is 3.10.10.
I tried to run this command:
npm install npm@latest -g
I keep getting this error

  npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files (x86)\\no
dejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "npm@latest" "-g"
npm ERR! node v6.11.4
npm ERR! npm  v3.10.10
npm ERR! code SELF_SIGNED_CERT_IN_CHAIN

npm ERR! self signed certificate in certificate chain
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\WINDOWS\system32\npm-debug.log
[npm-debug.log](https://github.com/npm/npm/files/1376600/npm-debug.log)

Thanks,
Rachida

**Comment by gihrig** [comment]
@rachidadukes I can't offer specific advice on your errors, but the versions you are running are getting pretty old, especially npm.

If you are able to run a newer version of node, try installing the [latest node](https://nodejs.org/en/download/current/). That comes with a more up to date npm.

If you are required to run an older version of node, you may have good results using a node version manager such as [nvm-windows](https://github.com/coreybutler/nvm-windows) or similar.

**Comment by rachidadukes** [comment]
Thanks for your fast response. I update the nodejs. Now I have the latest version node of npm - version 5.42
But when I run npm install @angular/cli --global - i still get this error:
C:\TEMP\MVC core Training\Angular\test\test>npm install
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@
1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do m
y best with it!
npm ERR! code E407
npm ERR! 407 Proxy Authentication Required: @angular/animations@4.2.5

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\15308\AppData\Roaming\npm-cache\_logs\2017-10-12T18_25_23_
985Z-debug.log

C:\TEMP\MVC core Training\Angular\test\test>npm install @angular/cli --global
npm ERR! code E407
npm ERR! 407 Proxy Authentication Required: @angular/cli@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\15308\AppData\Roaming\npm-cache\_logs\2017-10-12T18_27_18_
941Z-debug.log
[2017-10-12T18_27_18_941Z-debug.log](https://github.com/npm/npm/files/1380293/2017-10-12T18_27_18_941Z-debug.log)

Thanks so much,
Rachida

**Comment by gihrig** [comment]
@rachidadukes Looks like progress! 😄 

There's an fix for the E407 [here](https://github.com/npm/npm/issues/17396#issuecomment-310698624), see if that helps.
