### ISSUE TITLE
npm install not installing all dependency directories (specifically test dirs)

### ISSUE THREAD

**Issue by tysenmoore-xse** [npm/npm#18792]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ X ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I have a package.json which contains a git dependency (for example):
```
"someRepo": "git+http://gitlab......./someRepo.git",
```
The `npm install` works fine but the `someRepo` repo's `test` directory is not being pulled into the node_modules directory.  Should an included dependency contain ALL directories in the repo?  Also, there are no `.npmignore` files in any of the directories/repos.

#### How can the CLI team reproduce the problem?

Create a repo that has a `test` directory and include this in your package.json.

### supporting information:

 - `npm -v` prints: 5.4.2
 - `node -v` prints: 6.11.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Ubuntu 16.04
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
   - [ x ] None of the above
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).
   - [ x ] None of the above

**Comment by Pchelolo** [comment]
This started happening with me as well and weirdly even if I downgrade nom to `2.15.11` using nvm it still doesn't pull in the `test` directory.

**Comment by tysenmoore-xse** [comment]
I just upgraded from 5.4.2 to 5.5.1 and the problem no longer exists.

**Comment by MichaelNeas** [comment]
Some devs here are experiencing the same issues @Pchelolo and @tysenmoore-xse  even with the upgrade to 5.5.1

Half of us can get the test directory in certain modules and half of us cant
