### ISSUE TITLE
npm Error installing express.

### ISSUE THREAD

**Issue by Tonchor** [npm/npm#18796]
`-- express@4.16.2

npm WARN project_1@1.0.0 No description
npm WARN project_1@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: uws@0.14.5 (node_modules\uws):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: uws@0.14.5 install: `node-gyp rebuild > build_log.txt 2>&1 || exit 0`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: spawn C:\Windows\system32\cmd.exe\ ENOENT
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: uws@0.14.5 (node_modules\uws):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: uws@0.14.5 install: `node-gyp rebuild > build_log.txt 2>&1 || exit 0`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status -4058
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "express"
npm ERR! node v6.11.4
npm ERR! npm  v3.10.10

npm ERR! Callback called more than once.
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\project_1\npm-debug.log

**File npm-debug.log**
[npm-debug.log](https://github.com/npm/npm/files/1376946/npm-debug.log)

**Comment by kenany** [comment]
Does this also occur with `npm@5`?
