### ISSUE TITLE
cannot update npm to latest version - Unexpected token error

### ISSUE THREAD

**Issue by gerlstar** [npm/npm#18808]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ x] Other (_see below for feature requests_):

#### What's going wrong?
cant update npm to latest version. The old version that I have is 5.30. When running "sudo npm install npm@latest -g", I am getting this error 

```
npm ERR! Unexpected token '<' at 3:1
npm ERR! <!DOCTYPE html>
npm ERR! ^
```

#### How can the CLI team reproduce the problem?
In mac terminal, run "sudo npm install npm@latest -g"
The gist of the log is https://gist.github.com/anonymous/b4c818daada0b96b42146b048986b0e1

### supporting information:

 - `npm -v` prints: 5.3.0
 - `node -v` prints:8.6.0
 - `npm config get registry` prints:https://github.com/
 - Windows, OS X/macOS, or Linux?: osx
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [x ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
Could you try doing `npm config delete registry`?

**Comment by gerlstar** [comment]
This fixed it. THank you@KenanY
