### ISSUE TITLE
npm install doesn't respects .npmrc 

### ISSUE THREAD

**Issue by Yeti-or** [npm/npm#18807]
#### I'm opening this issue because:

  - [x] npm is doing something I don't understand.

#### What's going wrong?

npm5:
```
npm config get save
true
```
I put `save=false` to `.npmrc` in my project
so now:
```
npm config ls | grep safe
safe = false
```
right now everything is okay but:

ACTUAL:
```
npm i node-eval
git diff --shortstat  package.json
 1 file changed, 1 insertion(+)
```

EXPECTED:
```
npm i node-eval
git diff --shortstat  package.json  // zero changes
```

Maybe I miss some option  for enabling `npm install --no-save` by default in my .npmrc ?

### supporting information:

 - `npm -v` prints: 5.4.2
 - `node -v` prints: v8.5.0

**Comment by AlanGreene** [comment]
@Yeti-or maybe just a typo in your description but worth checking:

```
npm config ls | grep safe
safe = false
```

`safe` should be `save`

**Comment by Yeti-or** [comment]
@AlanGreene right now I could not reproduce it, maybe I actually misspelled it.
Then I am really sorry for the time spend.
