### ISSUE TITLE
npm ERR! code ELIFECYCLE

### ISSUE THREAD

**Issue by skiranch** [npm/npm#18826]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! race-enterprise@0.0.0 start: `ng serve --proxy-config proxy.config.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the race-enterprise@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\e5000257\AppData\Roaming\npm-cache\_logs\2017-10-12T16_44_28_725Z-debug.log

**Comment by kenany** [comment]
As the log indicates, the command:

```
ng serve --proxy-config proxy.config.json
```

is returning an error code. All `npm` is doing here is letting you know about it.

**Comment by skiranch** [comment]
I am new to Angular 2 and i am facing this issue..
I would like to know the probable root cause reason for the following error..
![inkedi28 cimgpsh_orig_li](https://user-images.githubusercontent.com/31719501/31595409-3bfbafce-b259-11e7-8925-3af1ba669e44.jpg)
![inkedi29 cimgpsh_orig_li](https://user-images.githubusercontent.com/31719501/31595410-3dacded8-b259-11e7-9982-0671b3c84117.jpg)
![i30 cimgpsh_orig](https://user-images.githubusercontent.com/31719501/31595412-3fbeb5de-b259-11e7-888e-fe11700c2101.png)
![i31 cimgpsh_orig](https://user-images.githubusercontent.com/31719501/31595414-42f1fd74-b259-11e7-8dad-abf25e995bd3.png)
![i32 cimgpsh_orig](https://user-images.githubusercontent.com/31719501/31595417-46657404-b259-11e7-97a0-7466b2145c58.png)
![image](https://user-images.githubusercontent.com/31719501/31595564-524d17b2-b25a-11e7-9f69-51081c6ab1e0.png)

**Comment by kenany** [comment]
@skiranch It might be best to take this to StackOverflow, or any other forum of Angular 2 users. This issue tracker is for bugs and feature requests for the `npm` CLI, not general support for third-party libraries.

**Comment by skiranch** [comment]
@KenanY Thank you for the suggestion. I have searched the same on StackOverflow, But could find no answer there. So I have posted this on Git hub to know whether I could fine any possible solution from your end.. Thank you for the suggestion once again. I will post it on StackOverflow.
