### ISSUE TITLE
Unable to install npm install -g @angular/cli in windows 10. Runing this command at command prompt and getting this error: npm ERR! Windows_NT 10.0.15063 npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli" npm ERR! node v6.11.4 npm ERR! npm  v3.10.10  npm ERR! shasum check failed for C:\Users\Hp\AppData\Local\Temp\npm-13700-2cbd680f\registry.npmjs.org\rxjs\-\rxjs-5.4.3.tgz npm ERR! Expected: 0758cddee6033d68e0fd53676f0f3596ce3d483f npm ERR! Actual:   631a0c8facec81b9da36abf2e7aa3493c2dde1a9 npm ERR! From:     https://registry.npmjs.org/rxjs/-/rxjs-5.4.3.tgz

### ISSUE THREAD

**Issue by sharmaparveen** [npm/npm#18828]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by anastasialela** [comment]
hye , i'am facing the same issue and i finally can solved this problem.
So what i'm doing is ...
- uninstall the node.js
- make sure there is no node folder left in the program files (run Ccleaner)
- since i install node.js with the old version before this, so i decided to reinstall it with the lastest version .
- after reinstall the node.js make sure you restart your pc 
- run the npm command as usual.
- make sure you have a good network connection during installing any npm packages

that's all

**Comment by kenany** [comment]
@sharmaparveen Can you please fill out the support form in your post, and edit the issue title to more clearly (and succinctly!) indicate the issue you're having? Thanks!

**Comment by sharmaparveen** [comment]
C:\>npm -v
5.3.0
C:\>node -v
v8.6.0

i face the problem when i run the command: c:\> npm install -g @angular/cli
(I have tried to uninstall the node.js / npm and dowloaded the latest version and node.js is getting installed, no issue there; but when i tried to intsall angular/cli and then I face the issue. I can copy the log file, if required; but i am pasing the last few lines here, from the log files:

10343 verbose stack Error: sha512-MKiLiV+I1AA596t9w1sQJ8jkiSr5+ZKi0WKrYGUn6d1Fx+Ij4tIj+m2WMQSGczs5jZVxV339chE8iwk6F64wjA== integrity checksum failed when using sha512: wanted sha512-MKiLiV+I1AA596t9w1sQJ8jkiSr5+ZKi0WKrYGUn6d1Fx+Ij4tIj+m2WMQSGczs5jZVxV339chE8iwk6F64wjA== but got sha512-eqE2b9dK2FM9MxUGrkXHNdX9NVPk+EFOrAMXmJL21ZU8cKvEr4Duq7lKqldijoVU16Z7WMKhqNioZYwSVv5VMg==. (32242 bytes)
10343 verbose stack     at Transform.on (C:\Program Files\nodejs\node_modules\npm\node_modules\ssri\index.js:275:19)
10343 verbose stack     at emitNone (events.js:110:20)
10343 verbose stack     at Transform.emit (events.js:207:7)
10343 verbose stack     at endReadableNT (_stream_readable.js:1059:12)
10343 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)
10343 verbose stack     at process._tickCallback (internal/process/next_tick.js:180:9)
10344 verbose cwd C:\
10345 verbose Windows_NT 10.0.15063
10346 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli"
10347 verbose node v8.6.0
10348 verbose npm  v5.3.0
10349 error code EINTEGRITY
10350 error sha512-MKiLiV+I1AA596t9w1sQJ8jkiSr5+ZKi0WKrYGUn6d1Fx+Ij4tIj+m2WMQSGczs5jZVxV339chE8iwk6F64wjA== integrity checksum failed when using sha512: wanted sha512-MKiLiV+I1AA596t9w1sQJ8jkiSr5+ZKi0WKrYGUn6d1Fx+Ij4tIj+m2WMQSGczs5jZVxV339chE8iwk6F64wjA== but got sha512-eqE2b9dK2FM9MxUGrkXHNdX9NVPk+EFOrAMXmJL21ZU8cKvEr4Duq7lKqldijoVU16Z7WMKhqNioZYwSVv5VMg==. (32242 bytes)
10351 verbose exit [ 1, true ]
Please help
[2017-10-15T07_17_49_824Z-debug.log](https://github.com/npm/npm/files/1385262/2017-10-15T07_17_49_824Z-debug.log)

**Comment by sharmaparveen** [comment]
Please help in resolving the above issue

**Comment by sharmaparveen** [comment]
Sorry, it is not closed yet
