### ISSUE TITLE
NPM version mismatch - npmjs.com vs github

### ISSUE THREAD

**Issue by ghost** [npm/npm#18830]
#### I'm opening this issue because:

  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
https://www.npmjs.com/package/npm says the latest version is 5.4.2, while according to github, the latest is 5.5.1

**Comment by kenany** [comment]
1) Issues with the website should be opened at <https://github.com/npm/www>
2) The webpage now shows 5.5.1 anyways
