### ISSUE TITLE
published package with README.md, but missing README.md on npm-webpage

### ISSUE THREAD

**Issue by kaizhu256** [npm/npm#18836]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
1. i publish my package utility2 with README.md (logs @ https://travis-ci.org/kaizhu256/node-utility2/builds/287116296#L553).
![screen shot 2017-10-14 at 1 54 09 pm](https://user-images.githubusercontent.com/280571/31573090-32d4b562-b0e7-11e7-8a2f-6343a3aaee96.png)

2. i verify README.md exists in my recently published package
<img width="602" alt="screen shot 2017-10-14 at 1 50 44 pm" src="https://user-images.githubusercontent.com/280571/31573075-e012cf08-b0e6-11e7-945c-f8ef2cf76417.png">

3. but for the past 24+ hours, README.md is unavailable on npm-package-webpage https://www.npmjs.com/package/utility2 
![screen shot 2017-10-14 at 1 42 42 pm](https://user-images.githubusercontent.com/280571/31573077-f08fda24-b0e6-11e7-9657-89df6fe85544.png)

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kaizhu256** [comment]
hmm, looks like the README.md is now up now @ https://www.npmjs.com/package/utility2

**Comment by kenany** [comment]
Yeah, this doesn't seem like an issue with the `npm` CLI itself.
