### ISSUE TITLE
Unable to install react js

### ISSUE THREAD

**Issue by sreeni619** [npm/npm#18847]
![screenshot_1](https://user-images.githubusercontent.com/1038575/31581570-b6630334-b18c-11e7-86a3-4a833f6816c6.png)
#### I'm opening this issue because:

  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.

#### What's going wrong?
npm WARN deprecated safe-to-string-x@2.0.3: Moved to https://github.com/Xotic750/to-string-symbols-supported-x

npm WARN deprecated connect@2.30.2: connect 2.x series is deprecated

**Comment by kenany** [comment]
Looks like installation was successful. You can ignore the warnings if you want, or communicate with the authors of the packages which use those deprecated modules and work to get those dependencies updated.

**Comment by drigues** [comment]
![1](https://user-images.githubusercontent.com/9768958/31762266-9c226234-b4b2-11e7-9711-db648662204d.PNG)
I got the same issue.
@KenanY no the installation was not successful, the command create-react-app are not being accepted.
Do you know how can I fix it on Windows 10?
Thanks

**Comment by TurnUpTheMike** [comment]
I'm getting this scenario as well.
```
$ npm install create-react-app
npm WARN deprecated safe-to-string-x@2.0.3: Moved to https://github.com/Xotic750/to-string-symbols-supported-x
npm WARN saveError ENOENT: no such file or directory, open '/Users/usrname/code/graphql/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/Users/username/code/graphql/package.json'
npm WARN graphql No description
npm WARN graphql No repository field.
npm WARN graphql No README data
npm WARN graphql No license field.

+ create-react-app@1.4.1
added 113 packages in 3.976s
```

The install is not successful.  I can then 
```
$ ls
node_modules		package-lock.json	project.graphcool
```

The package.json is never 'unlocked' which causes the other errors.

I'm on MacOs Sierra 10.12.6.
Searching for a resolution to this issue brought me here.

**Comment by drigues** [comment]
In my case, the issue was to not set the PATH on the environment variables to the npm directory, on Windows everything that we install on the CMD is needed to the set the PATH, in case of NPM on my machine is C:\Users\USER_NAME\AppData\Roaming\npm
