### ISSUE TITLE
npm outdated display wrong wanted version with semver pre-release label

### ISSUE THREAD

**Issue by dotnetCarpenter** [npm/npm#18849]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [X] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

npm outdated display wrong wanted version with semver pre-release label.

```
$ npm outdated --depth=0
Package     Current     Wanted      Latest  Location
nuxt     1.0.0-rc11  1.0.0-rc9  1.0.0-rc11  nuxt-test
```
```
$ cat package.json | grep -A 2 dependencies
  "dependencies": {
    "nuxt": "^1.0.0-rc11"
  },
```
```
$ cat package-lock.json | grep nuxt
  "name": "nuxt-test",
    "@nuxtjs/youch": {
      "resolved": "https://registry.npmjs.org/@nuxtjs/youch/-/youch-3.0.2.tgz",
    "nuxt": {
      "resolved": "https://registry.npmjs.org/nuxt/-/nuxt-1.0.0-rc11.tgz",
        "@nuxtjs/youch": "3.0.2",

```

#### How can the CLI team reproduce the problem?
Not sure.. Perhaps try with my `package-lock.json` file?

[package-lock.json.zip](https://github.com/npm/npm/files/1385489/package-lock.json.zip)

### supporting information:

 - `npm -v` prints: `5.5.1`
 - `node -v` prints: `v8.7.0`
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?: **Linux**

**Comment by chrismarinas** [comment]
I believe this is related to the version syntax. You might want to reach out to the maintainers to have them correct it. It should be `x.y.z-rc.a` instead of `x.y.z-rca`. Note the dot separation. You won't see the change reflected until after the next release, or they re-tag their previous release candidates.

Ref: http://semver.org/#spec-item-11

**Comment by dotnetCarpenter** [comment]
Thanks @chrismarinas. Seems that the nuxt maintainers are aware and will change the version syntax on next release. https://github.com/nuxt/nuxt.js/issues/1859
