### ISSUE TITLE
Refusing to install react-webrtc as a dependency of itself

### ISSUE THREAD

**Issue by satyampawar** [npm/npm#18859]
npm ERR! Linux 4.4.0-97-generic
npm ERR! argv "/home/yuva-sid/.nvm/versions/node/v7.0.0/bin/node" "/home/yuva-sid/.nvm/versions/node/v7.0.0/bin/npm" "install" "react-webrtc" "--save"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code ENOSELF

npm ERR! Refusing to install react-webrtc as a dependency of itself
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:

**Comment by kenany** [comment]
Ensure that the `"name"` field in your `package.json` is not set to `"react-webrtc"`. Try setting it to something more unique :)
