### ISSUE TITLE
npm install error - unix

### ISSUE THREAD

**Issue by nthota3** [npm/npm#18873]
#### I'm opening this issue because:
  - [ ] npm is doing something I don't understand.
[npm-debug.log](https://github.com/npm/npm/files/1391589/npm-debug.log)

[clearing@jsqjedi1q DormantAccountManagement]$ /usr/local/bin/npm install
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! Linux 2.6.18-406.0.0.0.1.el5
npm ERR! argv "/usr/local/node-v6.5.0-linux-x64/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3

npm ERR! Cannot convert undefined or null to object
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by garethm** [comment]
The internet connection you're using appears to be blocking access to the NPM registry which npm needs to connect to to do its work.

The message being produced is:

> Access to the application you were trying to use has been blocked in accordance with company policy. Please contact your system administrator if you believe this is in error.


You will need to speak to your organisation's system administrator and ask them to allow you to access  registry.npmjs.org.
