### ISSUE TITLE
I'm trying to edit a package.Json 

### ISSUE THREAD

**Issue by DanielSusser** [npm/npm#18907]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### How can the CLI team reproduce the problem?

https://preview.c9users.io/dsuss/fcc_how-to-npm_1/project_folder/npm-debug.log
  <! - -   Please a complete description of how to reproduce the problem.
    Include a gist of your npm-debug.log file.
    If you've never used gist.github.com, start here:
      https://github.com/EmmaRamirez/how-to-submit-your-npm-debug-log
-->

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
If you want to edit your `package.json` file, you can do so via your favorite text editor.
