### ISSUE TITLE
How to install redux on windows 10

### ISSUE THREAD

**Issue by Phillip101Choi** [npm/npm#18913]
I try to install redux on my windows 10. but there are errors.
Here are console error report.

F:\Work\Grocery Shop>create-react-app react-redux-project

Creating a new React app in F:\Work\Grocery Shop\react-redux-project.

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts...

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "--save-exact" "--loglevel" "error" "react" "react-dom" "react-scripts"
npm ERR! node v6.11.4
npm ERR! npm  v3.10.10

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "--save-exact" "--loglevel" "error" "react" "react-dom" "react-scripts"
npm ERR! node v6.11.4
npm ERR! npm  v3.10.10

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "--save-exact" "--loglevel" "error" "react" "react-dom" "react-scripts"
npm ERR! node v6.11.4
npm ERR! npm  v3.10.10
npm ERR! path C:\Users\Phillip\AppData\Local\Temp\npm-321148-74763519\registry.npmjs.org\eslint\-\eslint-4.4.1.tgz.4282411122
npm ERR! code EBUSY
npm ERR! errno -4082
npm ERR! syscall rename

npm ERR! EBUSY: resource busy or locked, rename 'C:\Users\Phillip\AppData\Local\Temp\npm-321148-74763519\registry.npmjs.org\eslint\-\eslint-4.4.1.tgz.4282411122' -> 'C:\Users\Phillip\AppData\Local\Temp\npm-321148-74763519\registry.npmjs.org\eslint\-\eslint-4.4.1.tgz'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "--save-exact" "--loglevel" "error" "react" "react-dom" "react-scripts"
npm ERR! node v6.11.4
npm ERR! npm  v3.10.10

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     F:\Work\Grocery Shop\react-redux-project\npm-debug.log

Aborting installation.
  npm install --save --save-exact --loglevel error react react-dom react-scripts has failed.

Deleting generated file... npm-debug.log
Deleting generated file... package.json
Deleting react-redux-project / from F:\Work\Grocery Shop
Done.

**Comment by kenany** [comment]
Does this also occur with newer versions of `npm`?
