### ISSUE TITLE
Npm craches on : npm start (using linux mint)

### ISSUE THREAD

**Issue by ghost** [npm/npm#18915]
Log:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/local/bin/npm', 'start' ]
2 info using npm@5.3.0
3 info using node@v8.6.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle Munshiiii@1.0.0~prestart: Munshiiii@1.0.0
6 info lifecycle Munshiiii@1.0.0~start: Munshiiii@1.0.0
7 verbose lifecycle Munshiiii@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle Munshiiii@1.0.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/ted/Desktop/RSM/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
9 verbose lifecycle Munshiiii@1.0.0~start: CWD: /home/ted/Desktop/RSM
10 silly lifecycle Munshiiii@1.0.0~start: Args: [ '-c', 'electron .' ]
11 silly lifecycle Munshiiii@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle Munshiiii@1.0.0~start: Failed to exec start script
13 verbose stack Error: Munshiiii@1.0.0 start: `electron .`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:927:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid Munshiiii@1.0.0
15 verbose cwd /home/ted/Desktop/RSM
16 verbose Linux 4.8.0-53-generic
17 verbose argv "/usr/bin/nodejs" "/usr/local/bin/npm" "start"
18 verbose node v8.6.0
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 1
22 error Munshiiii@1.0.0 start: `electron .`
22 error Exit status 1
23 error Failed at the Munshiiii@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

package.jso:

{
  "name": "Munshiiii",
  "version": "1.0.0",
  "description": "This is a short Description of the project",
  "main": "index.js",
  "scripts": {
    "start": "electron .",
    "build-win": "electron-packager ./ Munshiiii --platform=win32 --arch=ia32 --version=1.0.0 --ignore=Munshiiii.app --overwrite --icon=./assets/images/Munshiiii.ico",
    "pack": "electron-builder --dir"
  },
  "author": "Hicham Dbiza",
  "license": "ISC",
  "devDependencies": {
    "electron": "1.7.8",
    "electron-prebuilt": "^1.4.13"
  },
  "dependencies": {
    "asar": "^0.13.0",
    "cradle": "^0.7.1",
    "fs": "0.0.1-security",
    "git": "^0.1.5",
    "jquery": "^3.2.1",
    "jsdom": "^11.3.0",
    "loke-ipc": "^1.0.5",
    "mongodb": "^2.2.33",
    "node-couchdb": "^1.2.0",
    "pouchdb": "^6.3.4",
    "pouchdb-replication-stream": "^1.2.9",
    "scanner.js": "^1.0.0"
  },
  "postinstall": "electron-builder install-app-deps"
}

**Comment by kenany** [comment]
As the log indicates, the command `electron .` is returning an error code. All `npm` is doing here is letting you know about it.
