### ISSUE TITLE
Updating npm breaks npm "Unexpected token ILLEGAL": console.error(`a bug known to break npm...

### ISSUE THREAD

**Issue by mforbes** [npm/npm#18963]
#### I'm opening this issue because:

  - npm is crashing.

#### What's going wrong?

After upgrading npm, I get this error:

```
npm -v
/data/apps/node/lib/node_modules/npm/lib/utils/unsupported.js:27
        console.error(`a bug known to break npm. Please update to at least ${r
                      ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:69:16)
    at Module._compile (module.js:445:25)
    at Object.Module._extensions..js (module.js:480:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:367:17)
    at require (module.js:386:17)
    at /data/apps/node/lib/node_modules/npm/bin/npm-cli.js:19:21
    at Object.<anonymous> (/data/apps/node/lib/node_modules/npm/bin/npm-cli.js:92:3)
    at Module._compile (module.js:462:26)
```

This is also discussed at 

* https://stackoverflow.com/questions/46852889/unable-to-change-node-version-using-nvm

#### How can the CLI team reproduce the problem?

I am not too familiar with npm, so I cannot give definitive steps to reproduce.  I ran `npm install -g npm@latest` as suggested in the documentation, then `npm` broke.

### supporting information:

 - `npm -v` prints:  (See above)
 - `node -v` prints: `v0.11.14-pre`
 - `npm config get registry` prints: (See above)
 - Windows, OS X/macOS, or Linux?: OS X

**Comment by kenany** [comment]
Node.js v0.11 is years old and is no longer supported.

**Comment by mforbes** [comment]
Okay, so upgrading Node.js is the solution.  However, it would be nice if `npm` gave an appropriate warning *before* going ahead and upgrading itself into a completely unusable state.

**Comment by tingletech** [comment]
I was following the docs here https://docs.npmjs.com/getting-started/installing-node 

> Test: Run node -v. The version should be higher than v0.10.32.

```
node -v . 
v0.10.48
```

... and got this same exact error after running the `npm install npm@latest -g` as per the fine manual

**Comment by NaitikShah** [comment]
So what Now?? what is the Solution?? Can anyone please help??

**Comment by mforbes** [comment]
@NaitikShah You need to find some way of updating `Node.js` on your platform without using `npm`.

**Comment by ctodd** [comment]
I was also pulling my hair out with this. Here are the steps from start to finish on CentOS. I ripped everything out and started fresh.

1. Remove all node/npm/gulp files from /usr/local
2. Use "rpm -e" to remove all nodejs packages and npm
3. yum install nodejs npm
4. npm install -g n
5. n 4.7.0
6. npm install -g gulp

This gives you the following versions in /usr/local : 

# node -v
v4.7.0
# npm -v
2.15.11
# n --version
2.1.7
# gulp -v
[03:01:57] CLI version 3.9.1

You can experiment with different versions, but this got us consistent with our dev server and I'm reluctant to mess with it until later versions are compatible.

Chris Miller
President- Rocket Scientist
https://www.launchbrigade.com/
831.480.7190

**Comment by deployable** [comment]
@KenanY This issue is specifically about the message for unsupported platforms though. It would be useful if the code designed to tell users about support runs on the old platforms.

https://github.com/npm/npm/pull/18953

**Comment by nagababu7** [comment]
I got solution. Change node version.

**Comment by ivanfretes** [comment]
Install the Node Version Manager 
https://github.com/creationix/nvm

**Comment by zachwolf** [comment]
I'm also seeing this error message, but as far as I can tell everything is up to date. 

When I open my terminal, I get:

```
/usr/local/lib/node_modules/npm/lib/utils/unsupported.js:28
        console.error(`a bug known to break npm. Please update to at least ${r
                      ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:19:21
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:92:3)
    at Module._compile (module.js:460:26)
nvm is not compatible with the npm config "prefix" option: currently set to ""
Run `npm config delete prefix` or `nvm use --delete-prefix v8.9.4 --silent` to unset it.
Now using node v8.9.4 (npm v5.6.0)
```

```
$ node -v .
v8.9.4
```

I've tried cleaning out all global packages as suggested by another comment, but no change. Any suggestions are appreciated!

**Comment by deployable** [comment]
@zachwolf  do you have a default/system version of npm that is less than 4? It looks like `npm` is running before `nvm` can take over.

**Comment by zachwolf** [comment]
@deployable thanks for the response!

I don't think so... 

```
$ npm -v
5.6.0
```

Is there a better way to debug which versions are being run?

**Comment by deployable** [comment]
@zachwolf the paths in the stack trace would normally have a path like `/.nvm/versions/node/vX.X.X/` in them if they were referring to the nvm managed install
```
nvm ls
nvm use system
nvm which node
node -v
npm
```
or 
```
nvm unload
which node
node -v
npm
```

**Comment by CExBOommen** [comment]
@zachwolf 
which node (in your case it will be pointing to v8.9.4)
rm `which node` ()
nvm alias default v0.12.18 (you can set the system default node version like this)
After this you wont get this error on creating a new terminal

**Comment by VikasAlgoworks** [comment]
my node version is v10.4.0, but still facing same issue
