### ISSUE TITLE
tsc-w file missing

### ISSUE THREAD

**Issue by shrabanteeksingh** [npm/npm#18970]
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "tsc-w"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10

npm ERR! missing script: tsc-w
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Projects\meantodos\client\npm-debug.log

**Comment by kenany** [comment]
Hello! So, the way `npm run tsc-w` works is that it looks in your current `package.json` for a defined `"tsc-w"` [script](https://docs.npmjs.com/misc/scripts), and then runs that. The error message you're seeing is trying to tell you that you have not defined a `"tsc-w"` script in your `package.json`, hence `npm run tsc-w` has no idea what you want it to do.

To solve this issue, all you have to do is add a new script to your `package.json`. It might look something like this, for example:

``` json
{
  "name": "package-name",
  "version": "1.0.0",
  "description": "package description",
  "scripts": {
    "tsc-w": "node --version",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {},
  "devDependencies": {}
}
```

Note how this `package.json` has a `"tsc-w"` script that runs `node --version`. You'll definitely want to change the command to whatever is most appropriate for your project.

Let me know if you run into any further `npm` issues :)

**Comment by shrabanteeksingh** [comment]
Hi Kenan,

Thanks for your reply, but i am still getting the same problem.

*Thanks & Regards*

Shrabantee K Singh

**Comment by shrabanteeksingh** [comment]
Hi Kenan,

Thanks a lot, i got resolved my issue.
