### ISSUE TITLE
npm run 

### ISSUE THREAD

**Issue by sebastianlp** [npm/npm#18971]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [X] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I'm using this `package.json` file (for sake of simplicity it is shorty):

```json
{
  "name": "tesst-npm",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "staging": "BUILD_ENV=staging node index.js",
    "preproduction": "BUILD_ENV=preproduction node index.js",
    "production": "BUILD_ENV=production node index.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}
```

My index.js:
```javascript
console.log('Hi');
```

So, when I run `npm run staging` the output is fine:
```bash

> tesst-npm@1.0.0 staging /Users/spoliak/Code/tesst-npm
> BUILD_ENV=staging node index.js

Hi
```

With `npm run preproduction` is fine too:
```bash

> tesst-npm@1.0.0 preproduction /Users/spoliak/Code/tesst-npm
> BUILD_ENV=preproduction node index.js

Hi
```

But the things go wrong when I run `npm run production`:
```bash

> tesst-npm@1.0.0 preproduction /Users/spoliak/Code/tesst-npm
> BUILD_ENV=preproduction node index.js

Hi

> tesst-npm@1.0.0 production /Users/spoliak/Code/tesst-npm
> BUILD_ENV=production node index.js

Hi
```

The thing is I use the `BUILD_ENV` var in my application so when I build up for production I'll have the preproduction value or with the attached example I'm running the build process twice :/

I don't know if this is the correct behavior and I've to make more meaningful script names, but to me it's weird.

**Comment by kenany** [comment]
It is intentional. If you have some script named `"X"`, `npm` will run:

  1. `"preX"` (if it exists)
  2. `"X"`
  3. `"postX"` (if it exists)
