### ISSUE TITLE
GET http://localhost:3000/main.js 404 (Not Found)

### ISSUE THREAD

**Issue by shrabanteeksingh** [npm/npm#18983]
Hi, I am getting the below error.

GET http://localhost:3000/main.js 404 (Not Found)
scheduleTask @ zone.js:2019
ZoneDelegate.scheduleTask @ zone.js:353
Zone.scheduleTask @ zone.js:196
Zone.scheduleMacroTask @ zone.js:210
(anonymous) @ zone.js:2043
send @ VM1238:3
fetchTextFromURL @ system.src.js:1051
(anonymous) @ system.src.js:1781
ZoneAwarePromise @ zone.js:729
(anonymous) @ system.src.js:1780
(anonymous) @ system.src.js:2809
(anonymous) @ system.src.js:3387
(anonymous) @ system.src.js:3701
(anonymous) @ system.src.js:4093
(anonymous) @ system.src.js:4556
(anonymous) @ system.src.js:4825
(anonymous) @ system.src.js:407
ZoneDelegate.invoke @ zone.js:334
Zone.run @ zone.js:126
(anonymous) @ zone.js:713
ZoneDelegate.invokeTask @ zone.js:367
Zone.runTask @ zone.js:166
drainMicroTaskQueue @ zone.js:546
Promise resolved (async)
scheduleQueueDrain @ zone.js:505
scheduleMicroTask @ zone.js:513
ZoneDelegate.scheduleTask @ zone.js:356
Zone.scheduleTask @ zone.js:196
Zone.scheduleMicroTask @ zone.js:207
scheduleResolveOrReject @ zone.js:711
ZoneAwarePromise.then @ zone.js:800
(anonymous) @ system.src.js:4783
import @ system.src.js:839
(anonymous) @ system.src.js:1804
(anonymous) @ (index):18
(index):18 ZoneAwareError {__zone_symbol__error: Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3000/main.js
	Error: XHR error …, …}

**Comment by kenany** [comment]
Closing since this does not appear to be an issue with `npm` itself.
