### ISSUE TITLE
package-lock.json updates for optional dependencies

### ISSUE THREAD

**Issue by jez9999** [npm/npm#19016]
Optional dependencies cause `package-lock.json` to change if one machine installs them and another one doesn't.  This causes lots of noise in source control unless `package-lock.json` is simply ignored.  I think `package-lock.json` should record even optional dependencies even if they're not installed, maybe with an `optional` flag that means "if I were going to install them, here's where they'd go".

**Comment by miraage** [comment]
Same issue here. It is super annoying when lockfile changes due to different OS. 😡 
Not sure If I should put it here, but IMO `npm install` should use `--from-lockfile` by default if no other arguments provided.

**Comment by shospodarets** [comment]
Looks like #17722 duplicate

**Comment by jez9999** [comment]
This is now fixed in npm 5.6.0.
