### ISSUE TITLE
When I am running "npm install --global bb-cli"

### ISSUE THREAD

**Issue by SachinSonawane** [npm/npm#19014]
#### I'm getting below response - 
npm ERR! tar.unpack unzip error C:\Users\{user name}\AppData\Local\Temp\npm-4600-51c7308e\registry.npmjs.org\gauge\-\gauge-2.6.0.tgz
npm ERR! tar.unpack unzip error C:\Users\{user name}\AppData\Local\Temp\npm-4600-51c7308e\registry.npmjs.org\esprima-fb\-\esprima-fb-12001.1.0-dev-harmony-fb.tgz
npm ERR! tar.unpack unzip error C:\Users\{user name}\AppData\Local\Temp\npm-4600-51c7308e\registry.npmjs.org\parse-json\-\parse-json-2.2.0.tgz
npm ERR! tar.unpack unzip error C:\Users\{user name}\AppData\Local\Temp\npm-4600-51c7308e\registry.npmjs.org\moment\-\moment-2.5.1.tgz
npm ERR! tar.unpack untar error C:\Users\{user name}\AppData\Local\Temp\npm-4600-51c7308e\registry.npmjs.org\moment\-\moment-2.5.1.tgz
npm ERR! tar.unpack unzip error C:\Users\{user name}\AppData\Local\Temp\npm-4600-51c7308e\registry.npmjs.org\ramda\-\ramda-0.22.1.tgz
npm ERR! tar.unpack untar error C:\Users\{user name}\AppData\Local\Temp\npm-4600-51c7308e\registry.npmjs.org\ramda\-\ramda-0.22.1.tgz
npm ERR! tar.unpack unzip error C:\Users\{user name}\AppData\Local\Temp\npm-4600-51c7308e\registry.npmjs.org\lodash\-\lodash-4.16.4.tgz
npm ERR! tar.unpack untar error C:\Users\{user name}\AppData\Local\Temp\npm-4600-51c7308e\registry.npmjs.org\lodash\-\lodash-4.16.4.tgz
npm ERR! tar.unpack unzip error C:\Users\{user name}\AppData\Local\Temp\npm-4600-51c7308e\registry.npmjs.org\markdown-it\-\markdown-it-4.4.0.tgz
npm ERR! tar.unpack untar error C:\Users\{user name}\AppData\Local\Temp\npm-4600-51c7308e\registry.npmjs.org\markdown-it\-\markdown-it-4.4.0.tgz
npm ERR! tar.unpack unzip error C:\Users\{user name}\AppData\Local\Temp\npm-4600-51c7308e\registry.npmjs.org\source-map\-\source-map-0.5.6.tgz
npm ERR! tar.unpack untar error C:\Users\{user name}\AppData\Local\Temp\npm-4600-51c7308e\registry.npmjs.org\source-map\-\source-map-0.5.6.tgz
npm ERR! tar.unpack unzip error C:\Users\{user name}\AppData\Local\Temp\npm-4600-51c7308e\registry.npmjs.org\source-map\-\source-map-0.5.6.tgz
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--global" "bb-cli"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code Z_BUF_ERROR
npm ERR! errno -5

npm ERR! unexpected end of file
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\{user name}\npm-debug.log

**Comment by kenany** [comment]
Does this also occur with `npm@5`?

**Comment by SachinSonawane** [comment]
I haven't tried with npm@5, I don't know how but now it's working fine
