### ISSUE TITLE
npm does not support Node.JS v9.0.0

### ISSUE THREAD

**Issue by simonua** [npm/npm#19031]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
npm 5.5.1 is warning that Node.js v9.0.0 is not supported and that I should upgrade to a _newer_ version of node.

#### How can the CLI team reproduce the problem?
1) Install v9.0.0 of Node.js. I skipped installing npm as I already have 5.5.1 installed.
2) Run an npm command such as `npm start`.

Was Node 9 tested with npm 5.5.1 prior to release? I would assume so, but this shows me otherwise. Is npm only officially supported for LTS versions?
Also, the npm warning clearly only targets older versions of node. Even though this case here may not usually occur, it would be good to update the verbiage to include versions that may _not yet_ be supported and to remain on a lower version of Node.

Relevant entries in the log.
```
0 info it worked if it ends with ok
1 warn npm npm does not support Node.js v9.0.0
2 warn npm You should probably upgrade to a newer version of node as we
3 warn npm can't make any promises that npm will work with this version.
4 warn npm Supported releases of Node.js are the latest release of 4, 6, 7, 8.
5 warn npm You can find the latest version at https://nodejs.org/
```

### supporting information:

 - `npm -v` prints: 5.5.1
 - `node -v` prints: v9.0.0
 - `npm config get registry` prints: N/A
 - Windows, OS X/macOS, or Linux?: 64-bit Windows 7
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by simonua** [comment]
Duplicate of #19019.

**Comment by debug-vaibhav** [comment]
just run **npm uninstall -g npm**
