### ISSUE TITLE
npm install from package.json bug 

### ISSUE THREAD

**Issue by mason276752** [npm/npm#19060]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
package.json
```js
{
  "dependencies": {
    "d3":"4.10.0"
  }
}
```
```sh
npm install
npm list | grep
```
├─┬ d3@4.11.0
│ ├── d3-array@1.2.1
│ ├── d3-axis@1.0.8

that version not equal 4.10.0

**Comment by kenany** [comment]
I cannot reproduce this with `npm@5.5.1`

```console
$ npm ls
npm-19060@1.0.0 /tmp/npm-19060
└─┬ d3@4.10.0
  ├── d3-array@1.2.0
  ├── d3-axis@1.0.8
```

**Comment by mason276752** [comment]
.
