### ISSUE TITLE
adduser issue

### ISSUE THREAD

**Issue by AndrewLawendy** [npm/npm#19082]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I'm new with npm, and I'm trying to adduser, except that I have several errors
#### How can the CLI team reproduce the problem?

<script src="https://gist.github.com/AndrewHani/2158383a11567b16ff9b070c882c6742.js"></script>

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
What are the `npm adduser` errors?

**Comment by AndrewHani** [comment]
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "adduser"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code SELF_SIGNED_CERT_IN_CHAIN

npm ERR! self signed certificate in certificate chain
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\andrew.gorgui\npm-debug.log

**Comment by AndrewLawendy** [comment]
Thank you for your fast response


The errors are the following:

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "adduser"
npm ERR! node v6.11.2
npm ERR! npm v3.10.10
npm ERR! code SELF_SIGNED_CERT_IN_CHAIN

npm ERR! self signed certificate in certificate chain
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR! https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR! C:\Users\andrew.gorgui\npm-debug.log



________________________________
De : Kenan Yildirim <notifications@github.com>
Envoyé : mardi 7 novembre 2017 12:04
À : npm/npm
Cc : Andrew Hani; Author
Objet : Re: [npm/npm] adduser issue (#19082)


What are the npm adduser errors?

**Comment by AndrewLawendy** [comment]
Hi I uninstalled Node.js and reinstalled it, so it works now.
Thank you
