### ISSUE TITLE
npm ERR! Windows_NT 10.0.15063

### ISSUE THREAD

**Issue by abhibhowmick** [npm/npm#19093]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ .] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

F:\Programming Project\Auction System _ ELEC 6861\auction-master\node_modules\mo                                                                                                                ngodb\lib\server.js:242
        process.nextTick(function() { throw err; })
                                      ^
Error: connect ECONNREFUSED 127.0.0.1:27017
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\                                                                                                                node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.11.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! saasapp@ start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the saasapp@ start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the saasapp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs saasapp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls saasapp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     F:\Programming Project\Auction System _ ELEC 6861\auction-master\np                                                                                                                m-debug.log

### supporting information:

 - `npm -v` prints: 3.10.10
 - `node -v` prints: v6.11.4
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows 10
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
Doesn't seem like this error is coming from `npm`. The log says that `node server.js` is throwing an error. All `npm` is doing here is letting you know about it.

**Comment by abhibhowmick** [comment]
@KenanY : thanks for your comment. Can you suggest anything about my next step to resolve this error.

**Comment by kenany** [comment]
My guess is that something _should_ be running on `127.0.0.1:27017`, but it isn't, hence the connection-refused error.
