### ISSUE TITLE
Need help with the following npm issue

### ISSUE THREAD

**Issue by sandyydk** [npm/npm#19092]
Hi guys,

Am facing a serious issue with npm. need some help.

I will post it here below --

![screenshot 9](https://user-images.githubusercontent.com/5302471/32510886-1f19096c-c418-11e7-9b4e-4c71c713deaa.png)

I keep getting Parser errors both in Ubuntu as well as Windows.

**Comment by kenany** [comment]
Doesn't seem to be an issue with `npm` itself.

**Comment by sandyydk** [comment]
This is my package.json --

{
  "name": "XXXX",
  "version": "1.0.0",
  "scripts": {
    "start": "./node_modules/webpack/bin/webpack.js --progress --watch",
    "build": "./node_modules/webpack/bin/webpack.js --progress -p"
  },
  "devDependencies": {
    "babel-core": "^6.24.0",
    "babel-loader": "^6.4.1",
    "babel-plugin-transform-react-jsx": "^6.24.1",
    "babel-preset-es2015": "^6.24.1",
    "copy-webpack-plugin": "^4.0.1",
    "css-loader": "^0.28.4",
    "extract-text-webpack-plugin": "^2.1.0",
    "file-loader": "^0.11.2",
    "less": "^2.7.2",
    "less-loader": "^4.0.2",
    "style-loader": "^0.16.1",
    "url-loader": "^0.5.9",
    "webpack": "^3.2.0"
  },
  "dependencies": {
    "@types/mithril": "^1.1.11",
    "bootstrap": "^3.3.7",
    "bootswatch": "^3.3.7",
    "lodash": "^4.17.4",
    "mithril": "^1.1.3",
    "tachyons": "4.8.0"
  }
}
