### ISSUE TITLE
npm i failure seen on Ubuntu for Windows

### ISSUE THREAD

**Issue by mcclure** [npm/npm#19109]
I am running Windows 10 Pro build 15063. I have "Bash for Ubuntu for Windows" installed. I don't really understand the Windows command line utilities but using Ubuntu for Windows allows me to use a command line I understand.

I am trying to build [this project](https://github.com/ConquestArrow/UnrealTSTemplate). The relevant package.json is [here](https://github.com/ConquestArrow/UnrealTSTemplate/blob/master/Content/Scripts/package.json). It is straightforward and nothing about it is odd.

I first install npm using `sudo apt-get install npm`. Afterward, `npm --version` gives me `1.3.10` and `nodejs --version` gives me `v0.10.25`.

I check out that repo onto the **Windows Partition**. Note, I am not in the UNIX filesystem and certain things concerning files behave differently in Bash for Ubuntu for Windows when you do that. From the root of the repo, I run `cd Content/Scripts && npm i`. It prints a confusing error and instructs me to file an error at this github page here.

```
cd Content/Scripts && npm i
npm http GET https://registry.npmjs.org/typescript
npm http GET https://registry.npmjs.org/types/node
npm http 404 https://registry.npmjs.org/types/node
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/usr/share/npm/lib/cache.js:687:35)
npm ERR!     at /usr/share/npm/lib/cache.js:675:5
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.4.0-43-Microsoft
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "i"
npm ERR! cwd /mnt/c/Users/Andi/Documents/Unreal Projects/UnrealTSTemplate/Content/Scripts
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type non_object_property_load
npm http 304 https://registry.npmjs.org/typescript
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /mnt/c/Users/Andi/Documents/Unreal Projects/UnrealTSTemplate/Content/Scripts/npm-debug.log
npm ERR! not ok code 0
make: *** [npm] Error 1
```
Here is the npm-debug.log
[npm-debug.log](https://github.com/npm/npm/files/1455839/npm-debug.log)

The error reproduces 100% and seems to occur the same every time.

Expected behavior: npm i installing typescript should not produce a message about "undefined", even if something is wrong the error message should be more descriptive

**Comment by kenany** [comment]
Node.js v0.10 and `npm@1.3` are years old and are no longer supported.
