### ISSUE TITLE
ERROR - 'npm start' fails at tsc compile step whereas independently executed tsc compile works

### ISSUE THREAD

**Issue by nagsbhat** [npm/npm#19129]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [X] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
'npm start' fails with 'npm run build' step.  'npm run build' executes 'tsc -p src/'

```
> web-client@1.0.0 prestart /Users/nagendrabhat/Documents/workspace/vsng2/webclient
> npm run build


> web-client@1.0.0 build /Users/nagendrabhat/Documents/workspace/vsng2/webclient
> tsc -p src/ --outDir ../output

node_modules/@types/angular/index.d.ts(232,41): error TS1005: ',' expected.
node_modules/@types/angular/index.d.ts(233,41): error TS1005: ',' expected.
node_modules/@types/angular/index.d.ts(1252,41): error TS1005: ',' expected.
node_modules/@types/angular/index.d.ts(1253,41): error TS1005: ',' expected.
node_modules/@types/angular/index.d.ts(1972,55): error TS1005: ',' expected.
node_modules/@types/angular/index.d.ts(1976,54): error TS1005: ',' expected.
node_modules/@types/angular/index.d.ts(1986,55): error TS1005: ',' expected.
node_modules/@types/angular/index.d.ts(1991,57): error TS1005: ',' expected.
node_modules/@types/angular/index.d.ts(2005,48): error TS1005: ',' expected.
node_modules/@types/angular/index.d.ts(2088,22): error TS1005: ',' expected.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! web-client@1.0.0 build: `tsc -p src/ --outDir ../output`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the web-client@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nagendrabhat/.npm/_logs/2017-11-11T04_48_44_751Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! web-client@1.0.0 prestart: `npm run build`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the web-client@1.0.0 prestart script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nagendrabhat/.npm/_logs/2017-11-11T04_48_44_782Z-debug.log
nagendrabhat~/Documents/workspace/vsng2/webclient$ 
```

**tsc build step independently executed compiles fine and produces the required artifacts correctly**

```
nagendrabhat~/Documents/workspace/vsng2/webclient$ ls ..
output          webclient
nagendrabhat~/Documents/workspace/vsng2/webclient$
rm -rf ../output/
nagendrabhat~/Documents/workspace/vsng2/webclient$ ls ..
webclient
nagendrabhat~/Documents/workspace/vsng2/webclient$ tsc -p src/ --outDir ../output
nagendrabhat~/Documents/workspace/vsng2/webclient$ ls ..
output           webclient
```

Please note that 'tsc -p src/' executed on command line does not produce any compilation issues as above
#### How can the CLI team reproduce the problem?

There is no significant info in the debug log. 
12 verbose stack Error: web-client@1.0.0 prestart: `npm run build`
12 verbose stack Exit status 2

### supporting information:

 - `npm -v` prints:
5.5.1
 - `node -v` prints:
v8.9.1
 - `tsc -v` prints:
Version 2.6.1
 - `npm config get registry` prints:
https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Mac 10.12.6
 - Network issues:
   - Geographic location where npm was run: India
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**package.json**
{
  "name": "web-client",
  "version": "1.0.0",
  "private": true,
  "description": "Master package.json, the superset of all dependencies for all of the _example package.json files. See _boilerplate/package.json for example npm scripts.",
  "scripts": {
    "build": "tsc -p src/ --outDir ../output",
    "build:watch": "tsc -p src/ -w",
    "build:e2e": "tsc -p e2e/",
    "copy": "cpx \"src/**/*.{html,js,json,css}\" output --watch",
    "serve": "lite-server -c=bs-config.json",
    "prestart": "npm run build",
    "start": "concurrently \"npm run build:watch\" \"npm run copy\" \"npm run serve\"",
    "protractor": "protractor",
    "webdriver:update": "webdriver-manager update --standalone false --gecko false",
    "pretest": "npm run build",
    "test": "concurrently \"npm run build:watch\" \"karma start karma.conf.js\"",
    "pretest:once": "npm run build",
    "test:once": "karma start karma.conf.js --single-run",
    "lint": "tslint ./src/**/*.ts -t verbose",
    "build:upgrade": "tsc",
    "serve:upgrade": "http-server",
    "build:cli": "ng build --no-progress",
    "serve:cli": "http-server dist/",
    "build:aot": "ngc -p tsconfig-aot.json && rollup -c rollup-config.js",
    "serve:aot": "lite-server -c bs-config.aot.json",
    "start:webpack": "webpack-dev-server --inline --progress --port 8080",
    "test:webpack": "karma start karma.webpack.conf.js",
    "build:webpack": "rimraf dist && webpack --config config/webpack.prod.js --bail",
    "build:babel": "babel src -d src --extensions \".es6\" --source-maps",
    "copy-dist-files": "node ./copy-dist-files.js",
    "i18n": "ng-xi18n"
  },
  "keywords": [],
  "author": "",
  "license": "MIT",
  "dependencies": {
    "@angular/animations": "^4.2.0",
    "@angular/common": "^4.2.0",
    "@angular/compiler": "^4.2.0",
    "@angular/compiler-cli": "^4.2.0",
    "@angular/core": "^4.2.0",
    "@angular/forms": "^4.2.0",
    "@angular/http": "^4.2.0",
    "@angular/platform-browser": "^4.2.0",
    "@angular/platform-browser-dynamic": "^4.2.0",
    "@angular/router": "^4.2.0",
    "@angular/tsc-wrapped": "^0.5.0",
    "angular-in-memory-web-api": "~0.2.4",
    "core-js": "^2.4.1",
    "cpx": "^1.5.0",
    "font-awesome": "^4.7.0",
    "ngx-cookie": "^1.0.1",
    "primeng": "^4.1.0",
    "rxjs": "^5.2.0",
    "systemjs": "0.20.12",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "^1.0.0",
    "@types/angular": "^1.5.16",
    "@types/angular-animate": "^1.5.5",
    "@types/angular-cookies": "^1.4.2",
    "@types/angular-mocks": "^1.5.5",
    "@types/angular-resource": "^1.5.6",
    "@types/angular-route": "^1.3.2",
    "@types/angular-sanitize": "^1.3.3",
    "@types/jasmine": "2.5.36",
    "@types/node": "^6.0.90",
    "angular2-template-loader": "^0.6.0",
    "awesome-typescript-loader": "^3.0.4",
    "babel-cli": "^6.16.0",
    "babel-preset-angular2": "^0.0.2",
    "babel-preset-es2015": "^6.16.0",
    "canonical-path": "0.0.2",
    "concurrently": "^3.0.0",
    "css-loader": "^0.26.1",
    "extract-text-webpack-plugin": "2.0.0-beta.5",
    "file-loader": "^0.9.0",
    "html-loader": "^0.4.3",
    "html-webpack-plugin": "^2.16.1",
    "http-server": "^0.9.0",
    "jasmine": "~2.4.1",
    "jasmine-core": "~2.4.1",
    "karma": "^1.3.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-phantomjs-launcher": "^1.0.2",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-webpack": "^2.0.6",
    "lite-server": "^2.2.2",
    "lodash": "^4.16.2",
    "null-loader": "^0.1.1",
    "phantomjs-prebuilt": "^2.1.7",
    "protractor": "~4.0.14",
    "raw-loader": "^0.5.1",
    "rimraf": "^2.5.4",
    "rollup": "^0.36.0",
    "rollup-plugin-commonjs": "^4.1.0",
    "rollup-plugin-node-resolve": "^2.0.0",
    "rollup-plugin-uglify": "^1.0.1",
    "source-map-explorer": "^1.3.2",
    "style-loader": "^0.13.1",
    "ts-node": "^1.3.0",
    "tslint": "^3.15.1",
    "typescript": "~2.1.0",
    "webpack": "2.2.1",
    "webpack-dev-server": "2.4.1",
    "webpack-merge": "^3.0.0"
  },
  "repository": {}
}

**tsconfig.json**
{
  "compilerOptions": {
    "outDir": "../output",
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [ "es2015", "dom" ],
    "noImplicitAny": true,
    "suppressImplicitAnyIndexErrors": true,
    "typeRoots": [
      "../node_modules/@types/"
    ]
  },
  "compileOnSave": true,
  "exclude": [
    "node_modules/*",
    "**/*-aot.ts",
    "typings/main"
  ]
}

**Comment by heikomat** [comment]
If you run tsc as package.json-script, it will use the typescript-compiler located in `./node_modules/.bin/tsc`. This should exist and work, if you have typescript in your packages dependencies. If you run `tsc` from the command line instead, it will use the globally installed typescript-compiler (from your PATH-environment-variable), which may or may not be the same version as the one in node_modules

**Comment by nagsbhat** [comment]
Thanks a ton for the reply. Versions were indeed different. One in command line was 2.6.1 and  under npm_modules  2.1.6.

But interestingly, In order to verify what version of tsc compiler is used, I added '-v' to build script as below in package.json 

```
  "scripts": {
    "build": "tsc -v -p src/ --outDir ../output",
......
}
```

Output is:
```
> web-client@1.0.0 build /Users/nagendrabhat/Documents/workspace/vsng2/webclient
> tsc -v -p src/ --outDir ../output

Version 2.1.6

```
Subsequently compiler emits the errors as below:
```
[2] [Browsersync] Reloading Browsers...
[2] [Browsersync] Reloading Browsers...
[0] node_modules/@types/angular/index.d.ts(232,41): error TS1005: ',' expected.
[0] node_modules/@types/angular/index.d.ts(233,41): error TS1005: ',' expected.
[0] node_modules/@types/angular/index.d.ts(1252,41): error TS1005: ',' expected.
[0] node_modules/@types/angular/index.d.ts(1253,41): error TS1005: ',' expected.
[0] node_modules/@types/angular/index.d.ts(1972,55): error TS1005: ',' expected.
[0] node_modules/@types/angular/index.d.ts(1976,54): error TS1005: ',' expected.
[0] node_modules/@types/angular/index.d.ts(1986,55): error TS1005: ',' expected.
[0] node_modules/@types/angular/index.d.ts(1991,57): error TS1005: ',' expected.
[0] node_modules/@types/angular/index.d.ts(2005,48): error TS1005: ',' expected.
[0] node_modules/@types/angular/index.d.ts(2088,22): error TS1005: ',' expected.
[2] [Browsersync] Reloading Browsers...
[2] [Browsersync] Reloading Browsers...

```

**However, compiler does not treat these errors and continues to run the app. Not sure what is the magic of '-v' flag**

Closing the issue since the solution is appropriate. 
Regards,
Nagendra
PS: Output of command line tsc version
```
$ /usr/local/bin/tsc -v
Version 2.6.1

```
