### ISSUE TITLE
Issue when running npm run android command in Mac

### ISSUE THREAD

**Issue by LakshminarayananG** [npm/npm#19128]
Facing issue when running the command npm run android.
Below is the snapshot of the error.
<img width="1440" alt="screen shot 2017-11-10 at 5 24 00 pm" src="https://user-images.githubusercontent.com/29523140/32687222-002596ba-c6de-11e7-8990-87af03e9e735.png">
<img width="1440" alt="screen shot 2017-11-10 at 5 24 14 pm" src="https://user-images.githubusercontent.com/29523140/32687223-016c791c-c6de-11e7-8daf-a254bac3ad47.png">

**Comment by kenany** [comment]
Seems like your tests are timing out? I don't see how this is an issue with `npm` itself.
