### ISSUE TITLE
Installing Electron: "TypeError: Cannot read property 'latest' of undefined"

### ISSUE THREAD

**Issue by AlexG123** [npm/npm#19135]
npm install electron -g

npm http GET https://registry.npmjs.org/electron
npm http 304 https://registry.npmjs.org/electron
npm http GET https://registry.npmjs.org/extract-zip
npm http GET https://registry.npmjs.org/electron-download
npm http GET https://registry.npmjs.org/types/node
npm http 304 https://registry.npmjs.org/extract-zip
npm http 304 https://registry.npmjs.org/electron-download
npm http 404 https://registry.npmjs.org/types/node
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/usr/share/npm/lib/cache.js:687:35)
npm ERR!     at /usr/share/npm/lib/cache.js:675:5
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.4.0-98-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "electron" "-g"
npm ERR! cwd /home/alex/Desktop/BetterDiscordApp-master/Installers/Electron
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type non_object_property_load
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/alex/Desktop/BetterDiscordApp-master/Installers/Electron/npm-debug.log
npm ERR! not ok code 0

**Comment by AlexG123** [comment]
``

**Comment by kenany** [comment]
Your versions of Node.js and npm are years old and are no longer supported.
