### ISSUE TITLE
How to install wifi driver on dell 15R 3521 laptop windows 7 64 bit

### ISSUE THREAD

**Issue by AniketBDhadave** [npm/npm#19133]
@[](url)

**Comment by AniketBDhadave** [comment]
![capture](https://user-images.githubusercontent.com/31368302/32689703-0a72c58a-c70f-11e7-99e0-68ba1e02dcb1.PNG)

**Comment by kenany** [comment]
Closing since this doesn't appear to be an `npm` issue.
