### ISSUE TITLE
 npm install -g kyso

### ISSUE THREAD

**Issue by jonschull** [npm/npm#19138]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ x] Other (_see below for feature requests_):

stuck in a loop

[ksyo npm install log.txt](https://github.com/npm/npm/files/1464173/ksyo.npm.install.log.txt)

JonSchull-MBPretina-2:--kyso jonschull-MBPR$ npm -v
1.3.17
JonSchull-MBPretina-2:--kyso jonschull-MBPR$ node -v
v0.10.23
JonSchull-MBPretina-2:--kyso jonschull-MBPR$ npm config get registry
https://registry.npmjs.org/
JonSchull-MBPretina-2:--kyso jonschull-MBPR$

**Comment by kenany** [comment]
Sorry, but your versions of Node and npm are years old and are no longer supported.
