### ISSUE TITLE
npm needs a package for debian stable

### ISSUE THREAD

**Issue by traumschule** [npm/npm#19130]
We tried to deploy our website on a debian server and [found](https://travis-ci.org/traumschule/hitchwiki/jobs/300520396), there is no package [npm in debian](https://tracker.debian.org/pkg/npm).

The dated package from 2014 was [removed](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=857986) from stretch (stable), because the former maintainer found no time to update the [dependencies](https://wiki.debian.org/Javascript/Nodejs/Tasks).

Ubuntu [has a package](https://launchpad.net/ubuntu/+source/npm). Is there maybe a chance to find someone to migrate it to debian?

The alternative [yarn](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=843021#80) also [needs help](https://wiki.debian.org/Javascript/Nodejs/Tasks/yarn).

**Comment by sergiohgz** [comment]
NPM is served with NodeJs installation. The ubuntu and debian repository was moved to its own. You can install them using debian package manager following this instructions: [Link to official NodeJs docs](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions)
