### ISSUE TITLE
react-social-login-buttons -> Unsupported URL Type: react:@15.x

### ISSUE THREAD

**Issue by chenggong03** [npm/npm#19145]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [X] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I did "npm install --save react-social-login-buttons" in terminal and it told me
"Unsupported URL Type: react:@15.x"

#### How can the CLI team reproduce the problem?

[npm-debug.log](https://github.com/npm/npm/files/1466173/npm-debug.log)

### supporting information:

```
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "react-social-login-buttons"
npm ERR! node v6.11.4
npm ERR! npm  v3.10.10

npm ERR! Unsupported URL Type: react:@15.x
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/gongcheng/Documents/workspace/friend-zone/npm-debug.log
```

Thank you in advance!

**Comment by kenany** [comment]
Seems like a typo: https://github.com/MichalSzorad/react-social-login-buttons/blob/master/package.json#L45, this should just be:

```json
"react": "15.x"
```
