### ISSUE TITLE
Problems installing npm 5.5.1 on Windows 10 with nvm.

### ISSUE THREAD

**Issue by coderextreme** [npm/npm#19140]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
$ nvm install 8.9.1
Downloading node.js version 8.9.1 (64-bit)... Complete
Downloading npm version 5.5.1... Complete
Installing npm v5.5.1...2017/11/12 10:48:35 mkdir C:\Users\coderextreme\AppData\Roaming\nvm\temp\nvm-npm\npm-5.5.1\node_modules\libnpx\node_modules\yargs\node_modules\read-pkg-up\node_modules\read-pkg\node_modules\load-json-file\node_modules\parse-json\node_modules\error-ex\node_modules\is-arrayish: The filename or extension is too long.

#### How can the CLI team reproduce the problem?

$ nvm install 8.9.1

### supporting information:

 - `npm -v` prints: it's 5.5.1 but it doesn't install
 - `node -v` prints: it's 8.9.1 but it doesn't install to my knowledge
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:Windows 10
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by coderextreme** [comment]
Reinstalling everything fixed it.  Deleted everything I could see in AppData\Roaming.

**Comment by Butterfly** [comment]
I know this is now corrected and thus closed, but it's still interesting that it initially created that many `node_modules` child directories. Where in the world did all those come from? I count 7 beyond the expected highest level one. I've seen this happen one other time in another issue here, think I even noted that out loud for the user listing it, but can't remember what the problem was for that one. :smile:

**Comment by NeilTruick** [comment]
Problem: I just did a fresh install of **nvm 1.1.5** on a machine that didn't have it before. I ran **npm install 8.9.1** and got the same error. So, where and how exactly was this corrected?

**Comment by coderextreme** [comment]
Delete all versions of NVM, node and npm, then reinstall, and you should be
good.   Good luck!

On Nov 29, 2017 2:39 AM, "NeilTruick" <notifications@github.com> wrote:

Problem: I just did a fresh install of *nvm 1.1.5* on a machine that didn't
have it before. I ran *npm install 8.9.1* and got the same error. So, where
and how exactly was this corrected?

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/npm/npm/issues/19140#issuecomment-347777487>, or mute
the thread

**Comment by coderextreme** [comment]
Did you do npm install 8.9.1 or nvm install 8.9.1?

**Comment by coderextreme** [comment]
I think it may have something to do with reinstalling a npm 5.5.1 with NVM a second time.   I am not sure though.

**Comment by coderextreme** [comment]
Also clear out npm, node.js and nvm from AppData/Roaming

**Comment by coderextreme** [comment]
I don't recall the exact steps, just reinstalled everything which might affect it.
