### ISSUE TITLE
Installing ejs, npm err!

### ISSUE THREAD

**Issue by miguelalo27** [npm/npm#19147]
![image](https://user-images.githubusercontent.com/29457861/32731023-a4be65e6-c880-11e7-8c95-862e8563c24a.png)

Cannot install ejs!

**Comment by kenany** [comment]
Ensure that the `"name"` field in your `package.json` is not set to `"ejs"`. Try setting it to something more unique :)

**Comment by miguelalo27** [comment]
@KenanY that was the solution! Thanks!
