### ISSUE TITLE
Why can npm self remove?

### ISSUE THREAD

**Issue by exli3141** [npm/npm#19180]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

```
$ npm -g remove npm
removed 460 packages in 20.599s
```

Npm can remove.
And can't use npm of ```yarn global add npm``` after
This is bug? or specification?

### supporting information:

 - `npm -v` prints:
5.5.1

 - `node -v` prints:
v8.9.1

 - `npm config get registry` prints:
https://registry.npmjs.org/

 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [x] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
Seems useful for when one wants to get rid of `npm` 🤷‍♂️

**Comment by exli3141** [comment]
@KenanY 
Thank you reply.
Okay, This specification is useful when using only yarn, for example.
