### ISSUE TITLE
npm报错events.js:160       throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by rockmelodies** [npm/npm#19208]
npm run watch
![image](https://user-images.githubusercontent.com/24653177/33056489-e8eb969e-cec0-11e7-9edd-1b3433f9c5b0.png)

**Comment by kenany** [comment]
What happens if you change your `"watch"` script to:

```
cross-env NODE_ENV=development webpack --watch --progress --hide-modules --config=...
```

instead?

**Comment by kenany** [comment]
Closing as abandoned.
