### ISSUE TITLE
Can not install babel-runtime. What can i do?

### ISSUE THREAD

**Issue by mdkshuvo** [npm/npm#19209]
![bable](https://user-images.githubusercontent.com/30826181/33058273-0aa7427c-ceb9-11e7-930f-b522e5e7b908.jpg)

**Comment by kenany** [comment]
Looks like the installation succeeded, actually.

**Comment by mdkshuvo** [comment]
Yes, I have got the solution to run the app. If you have no _package.json_ on your project, create a _package.json_ on your project's root directory. Code is

_{
  "name": "yourProjectname",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "meteor run"
  },
  "dependencies": {
    "babel-runtime": "^6.26.0",
    "meteor-node-stubs": "^0.3.2"
  }
}_
