### ISSUE TITLE
NPM URL failing

### ISSUE THREAD

**Issue by baroquelute** [npm/npm#19220]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
npm is failing on a URL
#### How can the CLI team reproduce the problem?
Navigating to http://registry.npmjs.org/request

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by baroquelute** [comment]
Running the installer on an Internet-connected RedHat VM.

**Comment by baroquelute** [comment]
![clickingonurl_in_install_output](https://user-images.githubusercontent.com/7339449/33137457-04542c6a-cf76-11e7-8370-1311798f903b.png)

This is what I see when I click on the URL in the installer output in the command prompt.

**Comment by kenany** [comment]
What does "failing" mean here?

**Comment by baroquelute** [comment]
Hi Kenan,
I meant that the attempt to access that URL appeared to be unsuccessful.

In the end, we discovered that the issue was with the version of the
Keystone application that we were using.

This issue can be considered resolved.

Thanks for checking.

T


__________________________________________________
Timothy Burris
Technical Enablement Specialist
IBM Software | Cloud & Smarter Infrastructure
IBM Certified IT Specialist
ITIL Foundation v3 Certified
207.865.0520 (phone) | 207.408.1638 (mobile)
E-mail: burrist.ibm.com
                                                                                     
                                                                                     
                                                                                     
                                                                                     





From:	Kenan Yildirim <notifications@github.com>
To:	npm/npm <npm@noreply.github.com>
Cc:	Timothy Burris <burrist@us.ibm.com>, Author
            <author@noreply.github.com>
Date:	11/22/2017 05:13 PM
Subject:	Re: [npm/npm] NPM URL failing (#19220)



What does "failing" mean here?


—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
