### ISSUE TITLE
npm install webpack --save-dev                   ==>ERR!

### ISSUE THREAD

**Issue by alphawillian** [npm/npm#19241]
#### I'm opening this issue because:
I input my thinkpad npm install webpack --save-dev but ERR!

#### What's going wrong?

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'webpack',
1 verbose cli   '--save-dev' ]
2 info using npm@3.10.10
3 info using node@v6.11.5
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData webpack
8 silly fetchNamedPackageData webpack
9 silly mapToRegistry name webpack
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'webpack',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'webpack',
12 silly mapToRegistry   name: 'webpack',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/webpack
14 verbose request uri https://registry.npmjs.org/webpack
15 verbose request no auth needed
16 info attempt registry request try #1 at 00:38:12
17 verbose request id 8014d2d1e6252205
18 http request GET https://registry.npmjs.org/webpack
19 http 200 https://registry.npmjs.org/webpack
20 verbose headers { server: 'nginx/1.10.3',
20 verbose headers   'content-type': 'application/json',
20 verbose headers   'last-modified': 'Sat, 25 Nov 2017 00:00:57 GMT',
20 verbose headers   etag: 'W/"5a18b2b9-10e608"',
20 verbose headers   'content-encoding': 'gzip',
20 verbose headers   'cache-control': 'max-age=300',
20 verbose headers   'content-length': '57792',
20 verbose headers   'accept-ranges': 'bytes',
20 verbose headers   date: 'Sat, 25 Nov 2017 16:38:10 GMT',
20 verbose headers   via: '1.1 varnish',
20 verbose headers   age: '164',
20 verbose headers   connection: 'keep-alive',
20 verbose headers   'x-served-by': 'cache-bur17539-BUR',
20 verbose headers   'x-cache': 'HIT',
20 verbose headers   'x-cache-hits': '1',
20 verbose headers   'x-timer': 'S1511627890.368682,VS0,VE0',
20 verbose headers   vary: 'Accept-Encoding, Accept' }
21 silly get cb [ 200,
21 silly get   { server: 'nginx/1.10.3',
21 silly get     'content-type': 'application/json',
21 silly get     'last-modified': 'Sat, 25 Nov 2017 00:00:57 GMT',
21 silly get     etag: 'W/"5a18b2b9-10e608"',
21 silly get     'content-encoding': 'gzip',
21 silly get     'cache-control': 'max-age=300',
21 silly get     'content-length': '57792',
21 silly get     'accept-ranges': 'bytes',
21 silly get     date: 'Sat, 25 Nov 2017 16:38:10 GMT',
21 silly get     via: '1.1 varnish',
21 silly get     age: '164',
21 silly get     connection: 'keep-alive',
21 silly get     'x-served-by': 'cache-bur17539-BUR',
21 silly get     'x-cache': 'HIT',
21 silly get     'x-cache-hits': '1',
21 silly get     'x-timer': 'S1511627890.368682,VS0,VE0',
21 silly get     vary: 'Accept-Encoding, Accept' } ]
22 verbose get saving webpack to C:\Users\william\AppData\Roaming\npm-cache\registry.npmjs.org\webpack\.cache.json
23 verbose correctMkdir C:\Users\william\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
24 silly install normalizeTree
25 verbose stack TypeError: Cannot read property 'length' of undefined
25 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install.js:651:27
25 verbose stack     at Array.forEach (native)
25 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install.js:650:19
25 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\iferr\index.js:13:50
25 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:175:5
25 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:7:26)
25 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:18:7
25 verbose stack     at cb (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:47:24)
25 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:175:5
25 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:7:26)
26 verbose cwd F:\code\webpack-test
27 error Windows_NT 6.1.7601
28 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "webpack" "--save-dev"
29 error node v6.11.5
30 error npm  v3.10.10
31 error Cannot read property 'length' of undefined
32 error If you need help, you may report this error at:
32 error     <https://github.com/npm/npm/issues>
33 verbose exit [ 1, true ]

**Comment by kenany** [comment]
Does this also occur with newer versions of `npm`?

**Comment by kenany** [comment]
Closing as abandoned.
