### ISSUE TITLE
Primo Exlibris - Try to connect own Accessibility module JS

### ISSUE THREAD

**Issue by antrez770** [npm/npm#19246]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by antrez770** [comment]
I try to connect JS File with Accessibility menu in Primo, But no success, Is somebody add own JS/JQuery scripts to Primo or know about Accessibility Menu Plugin for Primo?

**Comment by kenany** [comment]
I'm closing this since it doesn't seem to be an issue with `npm` itself.

**Comment by antrez770** [comment]
Please open because it did't work and will be the reason is node pr npm

**Comment by kenany** [comment]
Can you demonstrate how this is an issue with `npm` specifically?
