### ISSUE TITLE
can’t execute hook scripts from version 5.1.0

### ISSUE THREAD

**Issue by zhrln** [npm/npm#19258]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [*] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### How can the CLI team reproduce the problem?

Hook scripts can run normally in the earlier version **5.0.4**, but `npm i` can’t execute hook scripts from version **5.1.0**. 
The major cause is that, if currently running is `node_modules/.hooks/preinstall` and the `preinstall` scripts are not configured in `package.json`, the judgment logic result is `pkg.scripts` don’t run `preinstall` and return to `resolve`(or `cb`).

please check this issue. this problem has been around for a long time.

https://github.com/npm/npm/pull/19057

**Comment by artch** [comment]
This bug breaks our build process badly, please fix it ASAP.
