### ISSUE TITLE
NPM incorrectly parsing git remote repository URL

### ISSUE THREAD

**Issue by andyault** [npm/npm#19262]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [X] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

When trying to install a package from a private repository, special characters in the username and passwords fields are not being parsed correctly.

#### How can the CLI team reproduce the problem?

Trying to authenticate with a username of `example@email.com` and a password of `1/password`:
`npm install git+https://example@email.com:1/password@host.com/repository`

Result:
`npm ERR! fatal: unable to access 'https://example@email.com:1/password@host.com/repository/': Failed to connect to email.com port 1: Operation timed out OR Connection refused`

Full log [here](https://gist.github.com/andyault/afe9d27d4fe0c7477fce75c78d48874b)

Similar results when trying to escape the @ sign:
`npm install git+https://example%40email.com:1/password@host.com/repository`

Result:
`npm ERR! fatal: unable to access 'https://example/%40email.com:1/password@host.com/repository/': Could not resolve host: example`

Full log [here](https://gist.github.com/andyault/8e38ec028bbda9591922986422e5f767)

### supporting information:

 - `npm -v` prints: `5.5.1`
 - `node -v` prints: `v8.1.2`
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?: `OS X`
 - Network issues:
   - Geographic location where npm was run: East USA
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [X] I deploy to a PaaS (Triton, Heroku).

**Comment by andyault** [comment]
Although I'm no longer in a position to test this, it seems that [encoding your password](https://stackoverflow.com/a/21765024/8003721) before using it will allow the url to be processed correctly.

**Comment by choliver** [comment]
Per https://www.ietf.org/rfc/rfc1738.txt:

> Within the user and password field, any ":", "@", or "/" must be encoded.

**Comment by andyault** [comment]
makes sense, thanks!
