### ISSUE TITLE
syntax error: illegal token in the unsupported.js file

### ISSUE THREAD

**Issue by uCreateStudio** [npm/npm#19272]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I'm trying to deploy the Hubot app on Heroku and I'm getting this build error which seems to be linked to the usage of the backtick "`" symbol in the unsupported.js file.
(Line 28 of this file: https://github.com/npm/npm/blob/latest/lib/utils/unsupported.js)

Any chance of getting this fixed soon, or a suggestion of a workaround?

`remote: -----> Installing binaries
remote:        engines.node (package.json):  0.10.x
remote:        engines.npm (package.json):   unspecified (use default)
remote:
remote:        Resolving node version 0.10.x...
remote:        Downloading and installing node 0.10.48...
remote:        Detected package-lock.json: defaulting npm to version 5.x.x
remote:        Bootstrapping npm 5.x.x (replacing 2.15.1)...
remote:
remote: /tmp/build_c7dc5de97125dcced067ca908aa960c6/.heroku/node/lib/node_modules/npm/lib/utils/unsupported.js:27
remote:         console.error(\`` `a bug known to break npm. Please update to at least ${r
remote:                       ^
remote: SyntaxError: Unexpected token ILLEGAL
remote:     at Module._compile (module.js:439:25)
remote:     at Object.Module._extensions..js (module.js:474:10)
remote:     at Module.load (module.js:356:32)
remote:     at Function.Module._load (module.js:312:12)
remote:     at Module.require (module.js:364:17)
remote:     at require (module.js:380:17)
remote:     at /tmp/build_c7dc5de97125dcced067ca908aa960c6/.heroku/node/lib/node_modules/npm/bin/npm-cli.js:19:21
remote:     at Object.<anonymous> (/tmp/build_c7dc5de97125dcced067ca908aa960c6/.heroku/node/lib/node_modules/npm/bin/npm-cli.js:92:3)`

**Comment by kenany** [comment]
See https://github.com/npm/npm/pull/18953. You could either apply that patch, or update your Node.js version.
