### ISSUE TITLE
npm ERR! addLocal Could not install pug

### ISSUE THREAD

**Issue by djdeo** [npm/npm#19291]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
npm ERR! addLocal Could not install D:\Tools\pug-tool\pug
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\Tools\\nodejs\\node.exe" "D:\\Tools\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "pug"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10

npm ERR! No version provided in package.json
#### How can the CLI team reproduce the problem?
`npm install pug`

### supporting information:
 - Windows 7 64bit
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [x] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by djdeo** [comment]
### npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Tools\\nodejs\\node.exe',
1 verbose cli   'D:\\Tools\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'pug' ]
2 info using npm@3.10.10
3 info using node@v6.11.2
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData pug
8 silly fetchDirectoryPackageData pug
9 silly install normalizeTree
10 silly loadCurrentTree Finishing
11 silly loadIdealTree Starting
12 silly install loadIdealTree
13 silly cloneCurrentTree Starting
14 silly install cloneCurrentTreeToIdealTree
15 silly cloneCurrentTree Finishing
16 silly loadShrinkwrap Starting
17 silly install loadShrinkwrap
18 silly loadShrinkwrap Finishing
19 silly loadAllDepsIntoIdealTree Starting
20 silly install loadAllDepsIntoIdealTree
21 silly resolveWithNewModule pug-monorepo@ checking installable status
22 silly cache add args [ 'pug', null ]
23 verbose cache add spec pug
24 silly cache add parsed spec Result {
24 silly cache add   raw: 'pug',
24 silly cache add   scope: null,
24 silly cache add   escapedName: 'pug',
24 silly cache add   name: null,
24 silly cache add   rawSpec: 'pug',
24 silly cache add   spec: 'D:\\Tools\\pug-tool\\pug',
24 silly cache add   type: 'directory' }
25 error addLocal Could not install D:\Tools\pug-tool\pug
26 silly rollbackFailedOptional Starting
27 silly rollbackFailedOptional Finishing
28 silly runTopLevelLifecycles Finishing
29 silly install printInstalled
30 verbose stack Error: No version provided in package.json
30 verbose stack     at D:\Tools\nodejs\node_modules\npm\lib\cache\add-local.js:73:17
30 verbose stack     at D:\Tools\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:356:5
30 verbose stack     at checkBinReferences_ (D:\Tools\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:320:45)
30 verbose stack     at final (D:\Tools\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:354:3)
30 verbose stack     at then (D:\Tools\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:124:5)
30 verbose stack     at D:\Tools\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:311:12
30 verbose stack     at D:\Tools\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
30 verbose stack     at tryToString (fs.js:456:3)
30 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:443:12)
31 verbose cwd D:\Tools\pug-tool
32 error Windows_NT 6.1.7601
33 error argv "D:\\Tools\\nodejs\\node.exe" "D:\\Tools\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "pug"
34 error node v6.11.2
35 error npm  v3.10.10
36 error No version provided in package.json
37 error If you need help, you may report this error at:
37 error     <https://github.com/npm/npm/issues>
38 verbose exit [ 1, true ]

**Comment by kenany** [comment]
Could you try `npm install pug@latest`?

**Comment by djdeo** [comment]
Thanks for your reply, i can see many packages installed, but still

`npm WARN enoent ENOENT: no such file or directory, open 'D:\net-sources\pug\package.json'`

**Comment by kenany** [comment]
Can I see the full log file? You can upload it to <https://gist.github.com/> and link it here. Thanks!

**Comment by djdeo** [comment]
Thanks, I've fixed this, I forgot to use `npm init`.

The complete step should be 
`npm init` , then 
`npm install pug@latest`, then 
`npm install pug-cli -g`, then use `pug --help` to check if it success.

Thanks, your advise helped.
