### ISSUE TITLE
Error: Argument #5: Expected object but got string

### ISSUE THREAD

**Issue by sgandham5** [npm/npm#19296]
#### I'm opening this issue because:
  --> When i'm trying to use **npm install**
  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
@sgandham5 Could you take the time to fill out the form in your post? Thanks!

**Comment by m-j** [comment]
I'm getting the same problem:
Node: 8.9.3
NPM: 5.5.1
No proxy was used
No container or VM was used
OS: Windows 10

Deleting node_modules doesn't help

**Comment by kenany** [comment]
Closing since the OP never updated their post to include more information.

@m-j Please open a new issue, and make sure to fill out the support form in the body of the issue. Thanks!

**Comment by m-j** [comment]
Just as a comment for people reading this. It was issue with package-lock.json. After deleting it everything started working.
