### ISSUE TITLE
npm publish --dry-run implementation

### ISSUE THREAD

**Issue by glebsts** [npm/npm#19308]
https://github.com/npm/npm/issues/6351 was auto-closed while not implemented.
need `npm publish --dry-run` support in order to be able for example test ci/cd job configurations.
Currently it really publishes package.

**Comment by teppeis** [comment]
@glebsts @zkat closed by https://github.com/npm/npm/pull/19908 ?

**Comment by zkat** [comment]
indeed. This shipped a while back.
