### ISSUE TITLE
v5.5.1 doesn't compile, but 5.3.0 is OK

### ISSUE THREAD

**Issue by Giancarlo1974** [npm/npm#19313]
#### I'm opening this issue because:

  - [ ] npm is producing an incorrect install.

#### What's going wrong?

connot find file in node_module

#### How can the CLI team reproduce the problem?

Clone the repository
git clone --depth=1 https://github.com/Microsoft/TypeScript-Node-Starter.git <project_name>
Install dependencies
cd <project_name>
npm install

### supporting information:

 - `npm -v` prints: 5.5.1 fails 5.3 ok
 - `node -v` prints: 9.2.0
 - `npm config get registry` prints:
 - Windows 10,
 - Network issues:
nothing, no proxy, fiber

**Comment by Giancarlo1974** [comment]
5.6.0 is ok !!

**Comment by kenany** [comment]
Sounds like it's fine in the latest version, so I'm gonna close this.
