### ISSUE TITLE
Npm Install running command failed 

### ISSUE THREAD

**Issue by UmaiZ** [npm/npm#19321]
npm i
× Running command - failed!
[ERROR] An error occurred while running npm i (exit code 1):

        > node-sass@4.5.3 install C:\Users\UmaiZ\gogogogogo\node_modules\node-sass
        > node scripts/install.js

        Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.3/win32-x64-59_binding.node
        Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.3/win32-x64-59_binding.node":

        HTTP error 404 Not Found

        Hint: If github.com is not accessible in your location
               try setting a proxy via HTTP_PROXY, e.g.

               export HTTP_PROXY=http://example.com:1234

        or configure npm proxy via

               npm config set proxy http://example.com:8080

        > uglifyjs-webpack-plugin@0.4.6 postinstall C:\Users\UmaiZ\gogogogogo\node_modules\uglifyjs-webpack-plugin
        > node lib/post_install.js

        > node-sass@4.5.3 postinstall C:\Users\UmaiZ\gogogogogo\node_modules\node-sass
        > node scripts/build.js

        Building: C:\Program Files\nodejs\node.exe C:\Users\UmaiZ\gogogogogo\node_modules\node-gyp\bin\node-gyp.js
        rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
        gyp info it worked if it ends with ok
        gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
        gyp verb cli   'C:\\Users\\UmaiZ\\gogogogogo\\node_modules\\node-gyp\\bin\\node-gyp.js',
        gyp verb cli   'rebuild',
        gyp verb cli   '--verbose',
        gyp verb cli   '--libsass_ext=',
        gyp verb cli   '--libsass_cflags=',
        gyp verb cli   '--libsass_ldflags=',
        gyp verb cli   '--libsass_library=' ]
        gyp info using node-gyp@3.6.2
        gyp info using node@9.2.0 | win32 | x64
        gyp verb command rebuild []
        gyp verb command clean []
        gyp verb clean removing "build" directory
        gyp verb command configure []
        gyp verb check python checking for Python executable "python2" in the PATH
        gyp verb `which` failed Error: not found: python2
        gyp verb `which` failed     at getNotFoundError (C:\Users\UmaiZ\gogogogogo\node_modules\which\which.js:13:12)
        gyp verb `which` failed     at F (C:\Users\UmaiZ\gogogogogo\node_modules\which\which.js:68:19)
        gyp verb `which` failed     at E (C:\Users\UmaiZ\gogogogogo\node_modules\which\which.js:80:29)
        gyp verb `which` failed     at C:\Users\UmaiZ\gogogogogo\node_modules\which\which.js:89:16
        gyp verb `which` failed     at C:\Users\UmaiZ\gogogogogo\node_modules\isexe\index.js:42:5
        gyp verb `which` failed     at C:\Users\UmaiZ\gogogogogo\node_modules\isexe\windows.js:36:5
        gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:166:21)
        gyp verb `which` failed  python2 { Error: not found: python2
        gyp verb `which` failed     at getNotFoundError (C:\Users\UmaiZ\gogogogogo\node_modules\which\which.js:13:12)
        gyp verb `which` failed     at F (C:\Users\UmaiZ\gogogogogo\node_modules\which\which.js:68:19)
        gyp verb `which` failed     at E (C:\Users\UmaiZ\gogogogogo\node_modules\which\which.js:80:29)
        gyp verb `which` failed     at C:\Users\UmaiZ\gogogogogo\node_modules\which\which.js:89:16
        gyp verb `which` failed     at C:\Users\UmaiZ\gogogogogo\node_modules\isexe\index.js:42:5
        gyp verb `which` failed     at C:\Users\UmaiZ\gogogogogo\node_modules\isexe\windows.js:36:5
        gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:166:21)
        gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError
        (C:\\Users\\UmaiZ\\gogogogogo\\node_modules\\which\\which.js:13:12)\n    at F
        (C:\\Users\\UmaiZ\\gogogogogo\\node_modules\\which\\which.js:68:19)\n    at E
        (C:\\Users\\UmaiZ\\gogogogogo\\node_modules\\which\\which.js:80:29)\n    at
        C:\\Users\\UmaiZ\\gogogogogo\\node_modules\\which\\which.js:89:16\n    at
        C:\\Users\\UmaiZ\\gogogogogo\\node_modules\\isexe\\index.js:42:5\n    at
        C:\\Users\\UmaiZ\\gogogogogo\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:166:21)',
        gyp verb `which` failed   code: 'ENOENT' }
        gyp verb check python checking for Python executable "python" in the PATH
        gyp verb `which` failed Error: not found: python
        gyp verb `which` failed     at getNotFoundError (C:\Users\UmaiZ\gogogogogo\node_modules\which\which.js:13:12)
        gyp verb `which` failed     at F (C:\Users\UmaiZ\gogogogogo\node_modules\which\which.js:68:19)
        gyp verb `which` failed     at E (C:\Users\UmaiZ\gogogogogo\node_modules\which\which.js:80:29)
        gyp verb `which` failed     at C:\Users\UmaiZ\gogogogogo\node_modules\which\which.js:89:16
        gyp verb `which` failed     at C:\Users\UmaiZ\gogogogogo\node_modules\isexe\index.js:42:5
        gyp verb `which` failed     at C:\Users\UmaiZ\gogogogogo\node_modules\isexe\windows.js:36:5
        gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:166:21)
        gyp verb `which` failed  python { Error: not found: python
        gyp verb `which` failed     at getNotFoundError (C:\Users\UmaiZ\gogogogogo\node_modules\which\which.js:13:12)
        gyp verb `which` failed     at F (C:\Users\UmaiZ\gogogogogo\node_modules\which\which.js:68:19)
        gyp verb `which` failed     at E (C:\Users\UmaiZ\gogogogogo\node_modules\which\which.js:80:29)
        gyp verb `which` failed     at C:\Users\UmaiZ\gogogogogo\node_modules\which\which.js:89:16
        gyp verb `which` failed     at C:\Users\UmaiZ\gogogogogo\node_modules\isexe\index.js:42:5
        gyp verb `which` failed     at C:\Users\UmaiZ\gogogogogo\node_modules\isexe\windows.js:36:5
        gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:166:21)
        gyp verb `which` failed   stack: 'Error: not found: python\n    at getNotFoundError
        (C:\\Users\\UmaiZ\\gogogogogo\\node_modules\\which\\which.js:13:12)\n    at F
        (C:\\Users\\UmaiZ\\gogogogogo\\node_modules\\which\\which.js:68:19)\n    at E
        (C:\\Users\\UmaiZ\\gogogogogo\\node_modules\\which\\which.js:80:29)\n    at
        C:\\Users\\UmaiZ\\gogogogogo\\node_modules\\which\\which.js:89:16\n    at
        C:\\Users\\UmaiZ\\gogogogogo\\node_modules\\isexe\\index.js:42:5\n    at
        C:\\Users\\UmaiZ\\gogogogogo\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:166:21)',
        gyp verb `which` failed   code: 'ENOENT' }
        gyp verb could not find "python". checking python launcher
        gyp verb could not find "python". guessing location
        gyp verb ensuring that file exists: C:\Python27\python.exe
        gyp ERR! configure error
        gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
        gyp ERR! stack     at PythonFinder.failNoPython
        (C:\Users\UmaiZ\gogogogogo\node_modules\node-gyp\lib\configure.js:483:19)
        gyp ERR! stack     at PythonFinder.<anonymous>
        (C:\Users\UmaiZ\gogogogogo\node_modules\node-gyp\lib\configure.js:508:16)
        gyp ERR! stack     at C:\Users\UmaiZ\gogogogogo\node_modules\graceful-fs\polyfills.js:284:29
        gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:166:21)
        gyp ERR! System Windows_NT 10.0.10240
        gyp ERR! command "C:\\Program Files\\nodejs\\node.exe"
        "C:\\Users\\UmaiZ\\gogogogogo\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" 
        "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
        gyp ERR! cwd C:\Users\UmaiZ\gogogogogo\node_modules\node-sass
        gyp ERR! node -v v9.2.0
        gyp ERR! node-gyp -v v3.6.2
        gyp ERR! not ok
        Build failed with error code: 1
        npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
        npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted
        {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

        npm ERR! code ELIFECYCLE
        npm ERR! errno 1
        npm ERR! node-sass@4.5.3 postinstall: `node scripts/build.js`
        npm ERR! Exit status 1
        npm ERR!
        npm ERR! Failed at the node-sass@4.5.3 postinstall script.
        npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

        npm ERR! A complete log of this run can be found in:
        npm ERR!     C:\Users\UmaiZ\AppData\Roaming\npm-cache\_logs\2017-12-05T07_24_47_504Z-debug.log

Node v9.2.0
npm 5.5.1

npm-sass installed already 

when i create ionic app by ionic start gogogo 
then all run fine some time package.json error but now this issue solved
now after create ionic app npm install showing error dont know what to do

**Comment by kenany** [comment]
Hmm, do you have Python installed?

**Comment by UmaiZ** [comment]
no i dont have python . should i need to install python ?

**Comment by UmaiZ** [comment]
i just install python by "npm install python" but same error shows . dont know if any other way to install it

**Comment by kenany** [comment]
Please see <https://www.python.org/downloads/> for downloading Python.

**Comment by UmaiZ** [comment]
Thanks it works :)

**Comment by Mekkush** [comment]
npm install python worked for me, thanks :)
