### ISSUE TITLE
"Use of const in strict mode." error occurs whenever npm is run

### ISSUE THREAD

**Issue by romesaran** [npm/npm#19328]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Anytime I try to run npm via Ubuntu 14.04 command line, I get this error: 

npm ERR! Linux 2.6.32-042stab108.8
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "list" "-g" "--depth=0"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! /usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/node_modules/cryptiles/node_modules/boom/lib/index.js:5
npm ERR! const Hoek = require('hoek');
npm ERR! ^^^^^
npm ERR! Use of const in strict mode.
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

### supporting information:

 - `npm -v` prints: 2.11.3
 - `node -v` prints: v0.12.7
 - `npm config get registry` prints: Same error as above
 - Windows, OS X/macOS, or Linux?: Linux Ubuntu Server 14.04
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
Your versions of Node.js and `npm` are no longer supported. Try installing the latest versions.
