### ISSUE TITLE
While installing appium through npm install -g appium error occured

### ISSUE THREAD

**Issue by ramoji4b5** [npm/npm#19331]
#### I'm opening this issue because:

  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
 Unable to install appium through CLI command  npm install -g appium
#### How can the CLI team reproduce the problem?
Find the root cause for issue and provide solution

### supporting information:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'appium' ]
2 info using npm@1.4.28
3 info using node@v0.10.32
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose cache add [ 'appium', null ]
6 verbose cache add name=undefined spec="appium" args=["appium",null]
7 verbose parsed url { protocol: null,
7 verbose parsed url   slashes: null,
7 verbose parsed url   auth: null,
7 verbose parsed url   host: null,
7 verbose parsed url   port: null,
7 verbose parsed url   hostname: null,
7 verbose parsed url   hash: null,
7 verbose parsed url   search: null,
7 verbose parsed url   query: null,
7 verbose parsed url   pathname: 'appium',
7 verbose parsed url   path: 'appium',
7 verbose parsed url   href: 'appium' }
8 silly lockFile d94e78b1-appium appium
9 verbose lock appium C:\Users\967806\AppData\Roaming\npm-cache\d94e78b1-appium.lock
10 silly lockFile d94e78b1-appium appium
11 silly lockFile d94e78b1-appium appium
12 verbose addNamed [ 'appium', '' ]
13 verbose addNamed [ null, '*' ]
14 silly lockFile 0e563340-appium appium@
15 verbose lock appium@ C:\Users\967806\AppData\Roaming\npm-cache\0e563340-appium.lock
16 silly addNameRange { name: 'appium', range: '*', hasData: false }
17 verbose request where is /appium
18 verbose request registry https://registry.npmjs.org/
19 verbose request id 3cd2cf1fc515cbec
20 verbose url raw /appium
21 verbose url resolving [ 'https://registry.npmjs.org/', './appium' ]
22 verbose url resolved https://registry.npmjs.org/appium
23 verbose request where is https://registry.npmjs.org/appium
24 info trying registry request attempt 1 at 16:02:24
25 http GET https://registry.npmjs.org/appium
26 info retry will retry, error on last attempt: Error: getaddrinfo EAGAIN
27 info trying registry request attempt 2 at 16:02:46
28 http GET https://registry.npmjs.org/appium
29 info retry will retry, error on last attempt: Error: getaddrinfo EAGAIN
30 info trying registry request attempt 3 at 16:03:58
31 http GET https://registry.npmjs.org/appium
32 silly lockFile 0e563340-appium appium@
33 silly lockFile 0e563340-appium appium@
34 error Error: getaddrinfo EAGAIN
34 error     at errnoException (dns.js:37:11)
34 error     at Object.onanswer [as oncomplete] (dns.js:124:16)
35 error If you need help, you may report this *entire* log,
35 error including the npm and node versions, at:
35 error     <http://github.com/npm/npm/issues>
36 error System Windows_NT 6.2.9200
37 error command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "appium"
38 error cwd C:\Users\967806
39 error node -v v0.10.32
40 error npm -v 1.4.28
41 error syscall getaddrinfo
42 error code EAGAIN
43 error errno EAGAIN
44 verbose exit [ 1, true ]

-->

**Comment by kenany** [comment]
Your versions of Node.js and `npm` are years old and are no longer supported. Even so, this looks like an issue with your internet connection anyways, not with `npm` itself.
