### ISSUE TITLE
unable to install mongoose npm in our project

### ISSUE THREAD

**Issue by anand-surkali** [npm/npm#19335]
#### I'm opening this issue because:

i am getting an issue please refer screen shot and log file 
F:\mongoose>npm install mongoose
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "mongoose"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ENOSELF

npm ERR! Refusing to install mongoose as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     F:\mongoose\npm-debug.log

![image](https://user-images.githubusercontent.com/27349588/33672018-258e32fe-dacf-11e7-98b2-03d1333282a7.png)

[npm-debug.log](https://github.com/npm/npm/files/1535882/npm-debug.log)

**Comment by kenany** [comment]
Ensure that the `"name"` field in your `package.json` is not set to `"mongoose"`. Try setting it to something more unique :)

**Comment by kenany** [comment]
Closing as abandoned.
