### ISSUE TITLE
no such file or directory, open '/Users/doekewartena/package.json'

### ISSUE THREAD

**Issue by clankill3r** [npm/npm#19359]
- [X] npm is producing an incorrect install.

#### What's going wrong?

I try to install:
https://github.com/Patreon/patreon-js

using:

`npm install --save patreon`

Which gives me:

```
Doekes-MBP:~ doekewartena$ npm install --save patreon
npm WARN saveError ENOENT: no such file or directory, open '/Users/doekewartena/package.json'
/Users/doekewartena
└── patreon@0.3.0 

npm WARN enoent ENOENT: no such file or directory, open '/Users/doekewartena/package.json'
npm WARN doekewartena No description
npm WARN doekewartena No repository field.
npm WARN doekewartena No README data
npm WARN doekewartena No license field.
```

#### How can the CLI team reproduce the problem?

`npm install --save patreon` I hope.

### supporting information:

 - `npm -v` prints:       3.10.10
 - `node -v` prints:      v6.11.2
 - `npm config get registry` prints:  https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
Does `/Users/doekewartena/package.json` exist? If not, then trying to `--save` a dependency will fail, since there is no `package.json` to save it to.

**Comment by kenany** [comment]
Closing as abandoned.
