### ISSUE TITLE
angular2-datetimepicker

### ISSUE THREAD

**Issue by debdasonly** [npm/npm#19367]
I am trying to use angular2-datetimepicker in my dotnet core application. I have correctly used it as described in https://www.npmjs.com/package/angular2-datetimepicker. But when I am going to publish it, I am having error. I have attached the error. Can you please help me out this issue? I have attached error file herewith. The following command shows: 5.6.0
npm --version

[publish error.txt](https://github.com/npm/npm/files/1546845/publish.error.txt)

**Comment by kenany** [comment]
This issue tracker is for bugs and feature requests for the `npm` CLI. Since your issue appears to be unrelated to that, I'm gonna close this. I suggest you take this to a site like StackOverflow instead, or some sort of forum of other dotnet users. Good luck!
