### ISSUE TITLE
Please Help me with this npm issue   ---  Error: EPERM: operation not permitted, unlink 'C:\wamp64\www\dev\node_modules\.staging

### ISSUE THREAD

**Issue by akshaywaghmare** [npm/npm#19363]
PS C:\wamp64\www\dev> npm install bulma
npm ERR! path C:\wamp64\www\dev\node_modules\.staging
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall unlink
npm ERR! Error: EPERM: operation not permitted, unlink 'C:\wamp64\www\dev\node_modules\.staging'
npm ERR!  { Error: EPERM: operation not permitted, unlink 'C:\wamp64\www\dev\node_modules\.staging'
npm ERR!   stack: 'Error: EPERM: operation not permitted, unlink \'C:\\wamp64\\www\\dev\\node_modules\\.staging\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path: 'C:\\wamp64\\www\\dev\\node_modules\\.staging' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2017-12-10T10_18_35_788Z-debug.log

#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints: 5.5.1
 - `node -v` prints: 8.9.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows 10
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by unional** [comment]
The only version I find that works is npm@5.3.0 with node@7.10.1
