### ISSUE TITLE
Not able to install Angular CLI in Linux Mint 17.2 Cinnamon 64bit

### ISSUE THREAD

**Issue by NishilSB** [npm/npm#19364]
Hi,

I am not able to install Angular CLI in my Linux mint 17.2, showing bellow error

npm ERR! addLocal Could not install angular/cli
npm ERR! Error: ENOENT, stat 'angular/cli'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.16.0-38-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "@angular/cli"
npm ERR! cwd /home/nishil
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path angular/cli
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/nishil/npm-debug.log
npm ERR! not ok code 0

**Comment by kenany** [comment]
Sorry, but your versions of Node.js and `npm` are years old and are no longer supported.
