### ISSUE TITLE
run andoid emulator

### ISSUE THREAD

**Issue by gwanjar** [npm/npm#19378]
C:\Users\user>emulator @Nexus_5X_API_27

:ERROR:android/android-emu/android/qt/qt_setup.cpp:28:Qt library not found at ..\emulator\lib64\qt\lib
Could not launch 'C:\Users\user\..\emulator\qemu\windows-x86_64\qemu-system-i386.exe': No such file or directory

=========

why android start to run in cmd with android studio?

or i run in andoid studio, can i code in visual studio cove? why step to do?

**Comment by kenany** [comment]
This seems unrelated to `npm`. Perhaps you could seek support on a more general forum, like StackOverflow?
