### ISSUE TITLE
Error: missing script: debug

### ISSUE THREAD

**Issue by dyauch** [npm/npm#19372]
#### I'm opening this issue because:
  - npm is doing something I don't understand.

#### What's going wrong?
I am attempting to run async/debug using an updated node, jasmine, protractor, and webdriver and I cannot get it to run no matter what I do, so I've attempted to debug at a command prompt level instead of inside of Eclipse and I keep getting this error.

debug is not present in my dependencies and I have no idea what to add to the config.

#### How can the CLI team reproduce the problem?
1.) Navigate to the package.json directory, in my case my eclipse workspace
2.) Attempt npm run debug

Error Log:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'debug' ]
2 info using npm@5.5.1
3 info using node@v9.2.0
4 verbose stack Error: missing script: debug
4 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:151:19)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:61:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:115:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:402:5
4 verbose stack     at handleExists (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:366:20)
4 verbose stack     at FSReqWrap.cb [as oncomplete] (fs.js:329:19)
5 verbose cwd C:\Users\d.yauch\eclipse-workspace\TestProtractor\node_modules\protractor
6 verbose Windows_NT 10.0.15063
7 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "debug"
8 verbose node v9.2.0
9 verbose npm  v5.5.1
10 error missing script: debug
11 verbose exit [ 1, true ]

### supporting information:

 - `npm -v` prints: 5.5.1
 - `node -v` prints: 9.2.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows 10
 - Network issues: None
 - Container: None

**Comment by dyauch** [comment]
I've added "debug": "node --inspect server.js"  to the config to no avail because immediately I receive an error being unable to find server.js.

**Comment by kenany** [comment]
Could you replace `server.js` with the path to the file you want to debug?

**Comment by dyauch** [comment]
I did and I moved it manually to the same folder and now I'm presented with it not recognizing the 'describe' from my test:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'debug' ]
2 info using npm@5.5.1
3 info using node@v9.2.0
4 verbose run-script [ 'predebug', 'debug', 'postdebug' ]
5 info lifecycle protractor@5.2.0~predebug: protractor@5.2.0
6 info lifecycle protractor@5.2.0~debug: protractor@5.2.0
7 verbose lifecycle protractor@5.2.0~debug: unsafe-perm in lifecycle true
8 verbose lifecycle protractor@5.2.0~debug: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\d\eclipse-workspace\TestProtractor\node_modules\protractor\node_modules\.bin;C:\Users\d\eclipse-workspace\TestProtractor\node_modules\.bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;c:\Program Files (x86)\HP\HP Performance Advisor;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\Symantec.cloud\PlatformAgent\;C:\Users\d
\eclipse-workspace\chromedriver_win32\chromedriver.exe;C:\Program Files\dotnet\;C:\Program Files\nodejs\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Users\d\AppData\Local\Microsoft\WindowsApps;C:\Users\d\AppData\Roaming\npm
9 verbose lifecycle protractor@5.2.0~debug: CWD: C:\Users\d\eclipse-workspace\TestProtractor\node_modules\protractor
10 silly lifecycle protractor@5.2.0~debug: Args: [ '/d /s /c', 'node --inspect TestIntelle.js' ]
11 silly lifecycle protractor@5.2.0~debug: Returned: code: 1  signal: null
12 info lifecycle protractor@5.2.0~debug: Failed to exec debug script
13 verbose stack Error: protractor@5.2.0 debug: `node --inspect TestIntelle.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
13 verbose stack     at EventEmitter.emit (events.js:159:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:159:13)
13 verbose stack     at maybeClose (internal/child_process.js:943:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid protractor@5.2.0
15 verbose cwd C:\Users\d\eclipse-workspace\TestProtractor\node_modules\protractor
16 verbose Windows_NT 10.0.15063
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "debug"
18 verbose node v9.2.0
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error protractor@5.2.0 debug: `node --inspect TestIntelle.js`
22 error Exit status 1
23 error Failed at the protractor@5.2.0 debug script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

If it cannot support describe / it syntax, I may be dead in the water...as I don't want to break a working script just for the sake of debug.

**Comment by kenany** [comment]
Right... you'll have to ensure that functions like `describe` are either defined/imported in your script, or globally defined elsewhere.
