### ISSUE TITLE
run android

### ISSUE THREAD

**Issue by gwanjar** [npm/npm#19375]
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "android"
npm ERR! node v6.11.4
npm ERR! npm  v3.10.10

npm ERR! missing script: android
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\React\awesome\npm-debug.log

**Comment by gwanjar** [comment]
i won to run android in androi studio, i comment in cmd: npm run android

**Comment by kenany** [comment]
Hello! So, the way `npm run android` works is that it looks in your current `package.json` for a defined `"android"` [script](https://docs.npmjs.com/misc/scripts), and then runs that. The error message you're seeing is trying to tell you that you have not defined a `"android"` script in your `package.json`, hence `npm run android` has no idea what you want it to do.

To solve this issue, all you have to do is add a new script to your `package.json`. It might look something like this, for example:

``` json
{
  "name": "package-name",
  "version": "1.0.0",
  "description": "package description",
  "scripts": {
    "android": "node --version",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {},
  "devDependencies": {}
}
```

Note how this `package.json` has a `"android"` script that runs `node --version`. You'll definitely want to change the command to whatever is most appropriate for your project.

Let me know if you run into any further `npm` issues :)

**Comment by kenany** [comment]
Closing as abandoned.
