### ISSUE TITLE
Not able to install async parallel

### ISSUE THREAD

**Issue by jrohit54** [npm/npm#19380]
[npm-debug.log](https://github.com/npm/npm/files/1551799/npm-debug.log)
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
Ensure that the `"name"` field in your `package.json` is not set to `"async-parallel"`. Try setting it to something more unique :)

**Comment by jrohit54** [comment]
@KenanY  thanks it worked for me after changeing the name.
