### ISSUE TITLE
failed to fetch from registry error

### ISSUE THREAD

**Issue by eazzyLEE** [npm/npm#19382]
#### I'm opening this issue because:
 
I can't view my package content via 'npm view'
it's displaying an error. Attached is the log link.

#### How can the CLI team reproduce the problem?

0 info it worked if it ends with ok
1 verbose cli [ '/home/ubuntu/.nvm/versions/node/v6.11.2/bin/node',
1 verbose cli   '/home/ubuntu/.nvm/versions/node/v6.11.2/bin/npm',
1 verbose cli   'view',
1 verbose cli   'israel' ]
2 info using npm@3.10.10
3 info using node@v6.11.2
4 silly mapToRegistry name israel
5 silly mapToRegistry using default registry
6 silly mapToRegistry registry http://localhost:15443/
7 silly mapToRegistry data Result {
7 silly mapToRegistry   raw: 'israel',
7 silly mapToRegistry   scope: null,
7 silly mapToRegistry   escapedName: 'israel',
7 silly mapToRegistry   name: 'israel',
7 silly mapToRegistry   rawSpec: '',
7 silly mapToRegistry   spec: 'latest',
7 silly mapToRegistry   type: 'tag' }
8 silly mapToRegistry uri http://localhost:15443/israel
9 verbose request uri http://localhost:15443/israel
10 verbose request no auth needed
11 info attempt registry request try #1 at 2:30:17 PM
12 verbose request id f08bcc3b2d9e6c10
13 http request GET http://localhost:15443/israel
14 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 127.0.0.1:15443
15 info attempt registry request try #2 at 2:30:27 PM
16 http request GET http://localhost:15443/israel
17 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 127.0.0.1:15443
18 info attempt registry request try #3 at 2:31:27 PM
19 http request GET http://localhost:15443/israel
20 silly get cb [ 304, undefined ]
21 verbose stack Error: failed to fetch from registry: http://localhost:15443/israel
21 verbose stack     at /home/ubuntu/.nvm/versions/node/v6.11.2/lib/node_modules/npm/lib/cache/caching-client.js:164:27
21 verbose stack     at /home/ubuntu/.nvm/versions/node/v6.11.2/lib/node_modules/npm/lib/cache/caching-client.js:53:8
21 verbose stack     at f (/home/ubuntu/.nvm/versions/node/v6.11.2/lib/node_modules/npm/node_modules/once/once.js:25:25)
21 verbose stack     at /home/ubuntu/.nvm/versions/node/v6.11.2/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:89:10
21 verbose stack     at /home/ubuntu/.nvm/versions/node/v6.11.2/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:103:12
21 verbose stack     at f (/home/ubuntu/.nvm/versions/node/v6.11.2/lib/node_modules/npm/node_modules/once/once.js:25:25)
21 verbose stack     at CachingRegistryClient.<anonymous> (/home/ubuntu/.nvm/versions/node/v6.11.2/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:224:20)
21 verbose stack     at Request._callback (/home/ubuntu/.nvm/versions/node/v6.11.2/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:201:20)
21 verbose stack     at self.callback (/home/ubuntu/.nvm/versions/node/v6.11.2/lib/node_modules/npm/node_modules/request/request.js:187:22)
21 verbose stack     at emitOne (events.js:101:20)
22 verbose cwd /home/ubuntu/workspace/node_tutorial
23 error Linux 4.9.17-c9
24 error argv "/home/ubuntu/.nvm/versions/node/v6.11.2/bin/node" "/home/ubuntu/.nvm/versions/node/v6.11.2/bin/npm" "view" "israel"
25 error node v6.11.2
26 error npm  v3.10.10
27 error failed to fetch from registry: http://localhost:15443/israel
28 error If you need help, you may report this error at:
28 error     <https://github.com/npm/npm/issues>
29 verbose exit [ 1, true ]

**Comment by kenany** [comment]
Firstly, is it intentional that your `registry` config is set to `http://localhost:15443`?

**Comment by kenany** [comment]
Closing as abandoned.
