### ISSUE TITLE
Error: Cannot find module '/root/pool/inti.js'

### ISSUE THREAD

**Issue by mharrisr** [npm/npm#19400]
root@root601760:~/pool# node inti.js

module.js:340
    throw err;
          ^
Error: Cannot find module '/root/pool/inti.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3
Can anyone help me to sort out this issue?

**Comment by kenany** [comment]
Seems like you're trying to `require()` a file which does not exist? Since this doesn't appear to be an issue with `npm` itself, I'm gonna close this, but feel free to take your issue to a more general support forum like StackOverflow if you're still having issues.
