### ISSUE TITLE
addLocal Could not install angular/cli Error: ENOENT, 

### ISSUE THREAD

**Issue by govindareddy2011** [npm/npm#19427]
Hi Team ,

  Getting this bellow Error while installing Angular.js.  NPM verion : 1.4.3 and Node : v0.10.26.

Can you please help on this.

D:\Govind\Projects\Angular>npm install -g @angular/cli
npm ERR! addLocal Could not install angular/cli
npm ERR! Error: ENOENT, stat 'D:\Govind\Projects\Angular\angular\cli'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "D:\\Govind\\Projects\\\\node.exe" "D:\\Govind\\Projects\\node_modules\\npm\\bin\\n
pm-cli.js" "install" "-g" "@angular/cli"
npm ERR! cwd D:\Govind\Projects\Angular
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! path D:\Govind\Projects\Angular\angular\cli
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     D:\Govind\Projects\Angular\npm-debug.log
npm ERR! not ok code 0

**Comment by kenany** [comment]
Sorry, but your versions of Node.js and `npm` are years old and are no longer supported.
