### ISSUE TITLE
Package name too similar to existing packages

### ISSUE THREAD

**Issue by catamphetamine** [npm/npm#19438]
How does NPM judge whether it's "too similar" or not "too similar"?

```
npm ERR! publish Failed PUT 403
npm ERR! code E403
npm ERR! Package name too similar to existing packages; try renaming your package to '@catamphetamine/react-application' and publishing with 'npm publish --access=public' instead : react-application
```

Perhaps there's already `react-application` package?
Seems that there is none.

```
λ npm install react-application
npm ERR! code E404
npm ERR! 404 Not Found: react-application@latest
```

**Comment by catamphetamine** [comment]
Got a reply:

Hello,Thanks for reaching out. The 403 error you received is a new typosquat functionality that will prevent security vulnerabilities.The react-application package name is similar to the reactapplication package name, so npm has blocked the publish and has also recommended publishing it as a scope package.For more information on typosquat please refer to:https://gist.github.com/ashleygwilliams/e466c1e9fd3be42545da511239edd554

**Comment by trusktr** [comment]
This is not ideal.

Instead of this, `npm install` should prompt something like:

```
You tried to install the package `react-application` but we also found a package called `reactapplication`. Did you mean to install `react-application`? (yes/no) _
```

That'd be MUCH better.

**Comment by unional** [comment]
I just encountered this.
It is definitely not ideal.
A good name is hard to come by.

**Comment by ahmadawais** [comment]
This is bad. I developed the most popular pkg for a thing and someone registered that name before me, no when I add `-` in the two words it says — my pkg is too similar.

**Comment by rdev** [comment]
Just encountered the same thing. 
I get how this may help fight malicious package names (cross-env/crossenv story), but it's not a good solution. Hell, the package that mine is "too similar" to hasn't been updated in 2 years.

**Comment by GarethOates** [comment]
I published my first package without -'s in the name and now want to rename it to conform to proper naming conventions, without upsetting people who are currently using it.  I've tried to deprecate my existing package and publish a new one with - in the name, but because of this similarity rule I cannot.  Do I have to simply unpublish the existing package and hope that existing users find the new one?

**Comment by trusktr** [comment]
Since you own the other one, probably email support and see what they say.

**Comment by dkent600** [comment]
The package with the old name and the package with the new one are both in my own friggin' account.  How can there be a security issue?

**Comment by dkent600** [comment]
Should be possible to rename a package

**Comment by NoahCardoza** [comment]
What a pain...

**Comment by johnnyodonnell** [comment]
This is especially sad given that if you go to https://www.npmjs.com/package/react-application you get:
![image](https://user-images.githubusercontent.com/4131459/36051849-54707560-0da0-11e8-9862-e6cf8ae6a556.png)

**Comment by sangaman** [comment]
Just ran into the same thing, saw the page @johnnyodonnell screenshotted when I was considering a package name, developed around that name, and then got this error when trying to publish. Seems like an unnecessary hassle given the crowded package name space, and at a minimum the website should be fixed not to advertise `npm publish` for package names that can't be used.

**Comment by kenany** [comment]
Make sure to let https://github.com/npm/www know about that 😄

**Comment by jlmakes** [comment]
Absolutely savage.

**Comment by mariohmol** [comment]
No benefit at all.. just problems.. have to invent a weird name for a package to make it work

**Comment by ojengwa** [comment]
Bad. SAD.

**Comment by jlmakes** [comment]
I've personally never had an issue with typosquatting or installing the wrong package, but I do see how not-so-subtly enforcing developers namespace their packages is prudent; finding a suitable package name is indeed growing difficult.

The irony is that this change has barred developers from naming their packages consistent with their existing/related packages, and for the time being, constrained an already crowded global name space.

I'm sure the team on this has the best of intentions, and presumably agreed this was necessary growing pain as namespaced packages become the norm—but as a _human_, I would've deeply appreciated some warning/transition period.

_Imagine instead, we were given a warning upon publishing our next package that only the next 3 packages were exempt from upcoming naming restrictions, and a link to read about the upcoming changes. We'd all feel a little more respected, and have some room to follow up on our package plans before this drastic change to package naming._

Being blind sided is just frustrating.

**Comment by jlmakes** [comment]
I've personally never had an issue with typosquatting or installing the wrong package, but I do see how not-so-subtly enforcing developers namespace their packages is prudent; finding a suitable package name is indeed growing difficult.

The cost is that this change has barred developers from naming their packages consistent with their existing/related packages, and for the time being, constrained an already crowded global name space.

I'm sure the team on this has the best of intentions, and presumably agreed this was necessary growing pain as namespaced packages become the norm—but as a _human_, I would've deeply appreciated some warning/transition period.

_Imagine instead, we were given a warning upon publishing our next package that only the next 3 packages were exempt from upcoming naming restrictions, and a link to read about the upcoming changes. We'd all feel a little more respected, and have some room to follow up on our package plans before this drastic change to package naming._

Being blind sided is just frustrating.

**Comment by indatawetrust** [comment]
instead of doing this, you may be able to bring out useful packages to the foreground. it seems like a rather useless solution.

**Comment by stevenvachon** [comment]
This is annoying.

**Comment by sneurlax** [comment]
This is now a usability and security issue in the cryptocurrency space: package `monero-nodejs` (https://github.com/PsychicCat/monero-nodejs) is woefully out of date.  The community's updated package, `moneronodejs`, can't be pushed due to that one-dash difference.

And `monerojs` is a vanilla Javascript project, not a Node.js project.

**Comment by falconair** [comment]
Same issue here. Not able to publish "fix.js", because it is too similar to another package, presumably "fix" except, that is also my package!
