### ISSUE TITLE
Issue with npm

### ISSUE THREAD

**Issue by abhi0002** [npm/npm#19442]
#### I'm opening this issue because:
  - [ ] npm is doing something I don't understand.

#### What's going wrong?

When ever i try to install somthing using npm all these list comes in front. This time i tried to install gulp globally.

npm ERR! Linux 4.10.0-42-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--global" "gulp-cli"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! path /usr/local/lib/node_modules/gulp-cli/node_modules/arr-diff
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules/gulp-cli/node_modules/arr-diff'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, access '/usr/local/lib/node_modules/gulp-cli/node_modules/arr-diff']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules/gulp-cli/node_modules/arr-diff' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
npm ERR! Please include the following file with any support request:

### supporting information:

 - `npm -v` prints:3.5.2
 - `node -v` prints:v4.2.6

 - `npm config get registry` prints:https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux

**Comment by kenany** [comment]
Have you tried prepending `sudo` to the command you're running? The error message states that your user does not have the permissions necessary to access your global modules directory, hence privilege escalation through `sudo` can be one solution..

**Comment by kenany** [comment]
Closing due to no reply.
