### ISSUE TITLE
Packages installed with git are removed on subsequent npm installs

### ISSUE THREAD

**Issue by sis0k0** [npm/npm#19446]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.

#### What's going wrong?

Packages present under the dependencies in the package.json file that were installed using git/github package links, e.g. github:npm/npm#some-tag are being uninstalled when another package is added with `npm install`.

#### How can the CLI team reproduce the problem?
1. Install a package from github:
```
npm install chalk/chalk
```
1. Install another package (doesn't matter where you install it from):
```
npm install lodash
```
Expected: The first package is in node_modules.
Actual: The first package is not there. However, it is present in package.json and package-lock.json.

### supporting information:

npm -v prints: 5.6.0
node -v prints: v9.3.0
npm config get registry prints: registry.npmjs.org
Windows, OS X/macOS, or Linux?: Linux

May be related to https://github.com/npm/npm/issues/19356

**Comment by rankida** [comment]
I have also seen this locally (running MacOS) with npm v5.6.0 and node v8.9.3 as well as on our build server with is Linux running the same versions

**Comment by G-Rath** [comment]
I think this is a duplicate of my issue: https://github.com/npm/npm/issues/19394
  
It affects any git repo (BitBucket or GitHub), and is *very* annoying :)

**Comment by sis0k0** [comment]
fixed with npm v5.7.0
