### ISSUE TITLE
npm errors and displays incorrect node version

### ISSUE THREAD

**Issue by RichardLitt** [npm/npm#19444]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Npm seems to think that I am using a very old version of Node. I am not sure why.

```sh
16:18 ~/src/git-flight-rules (sotayamashita-feature/improve-user-contribution) * 🐕  git commit -m 'test'
ERROR: npm is known not to run on Node.js v1.4.1
You'll need to upgrade to a newer version in order to use this
version of npm. Supported versions are 4, 6, 7, 8, 9. You can find the
latest version at https://nodejs.org/
pre-commit:
pre-commit: We've failed to pass the specified git pre-commit hooks as the `test`
pre-commit: hook returned an exit code (1). If you're feeling adventurous you can
pre-commit: skip the git pre-commit hooks by adding the following flags to your commit:
pre-commit:
pre-commit:   git commit -n (or --no-verify)
pre-commit:
pre-commit: This is ill-advised since the commit is broken.
pre-commit:
```

#### How can the CLI team reproduce the problem?

- Check out this PR: https://github.com/k88hudson/git-flight-rules/pull/182
- Run `npm i` to install pre-commit.
- Try and commit a change. For instance, I added a section so that Doctoc would need to be run. Then, I committed it - and the pre-commit hook failed. 

Unfortunately, I am not sure why npm is being called - but this looks like an npm error, not an error with a package. 

### supporting information:

 - `npm -v` prints: 5.6.0
 - `node -v` prints: v8.1.2
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?:  OSX
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by geosigno** [comment]
I get the same issue, any change you fixed it since?

**Comment by RichardLitt** [comment]
I haven't had this issue recently.

**Comment by geosigno** [comment]
NVM was the root cause of the problem, the current version of node I using wasn't set as default in nvm option. And Husky check the default version of NVM, and not the one you use.

So for example if you use node 8.9.4, you should execute the following line to have the version set as the default one.
`nvm alias default 8.9.4`

**Comment by RichardLitt** [comment]
I had an errant node version in `/usr/local/bin/node`. When I removed that and switched to just using nvm, this error went away. 

Thanks for the ping and checkin, @geosenna.
