### ISSUE TITLE
"npm uninstall <package>" throwing warnings and errors

### ISSUE THREAD

**Issue by joakimglaving** [npm/npm#19452]
#### I'm opening this issue because:

  - [X ] npm is crashing.

#### What's going wrong?

When trying to uninstall a package through `npm uninstall <package name>`, I get lots of warnings and errors, and the package does not get uninstalled.

Here is the gist of the debug log file: https://gist.github.com/bobcat1/571fe5e6c0a2f5e219ee4117f0a0683f

### supporting information:

 - `npm -v` prints: v5.6.0
 - `node -v` prints: v8.9.3
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows 10
 - Network issues:
   - Geographic location where npm was run: Sweden

**Comment by zhuyujiess** [comment]
i have the same error. have you fixed ?
