### ISSUE TITLE
npm install <package> removes packages installed from github

### ISSUE THREAD

**Issue by lkmill** [npm/npm#19459]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Running `npm install <package>` will remove any packages installed from github (and saved to `package.json` not referring to a specific commit).

#### How can the CLI team reproduce the problem?

1. Create a new project directory and run `npm init`
2. Install a package from github, ie `npm install <user>/<package> --save`
3. `ls node_modules` and ensure the installed package is present
4. Run `npm install <any-package>`
5. Run `ls node_modules` again. The package installed in step 2 is now removed.

I do not think this happens if the package in step 2 is installed using a specific commit, but appears to happen when using tags. I often install gulp using `npm install gulpjs/gulp#4.0 --save-dev`, and it keeps getting removed as soon as i install another package.

### supporting information:

 - `npm -v` prints: 5.6.0
 - `node -v` prints: 9.3.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: linux
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by G-Rath** [comment]
This sounds like a duplicate of my issue: https://github.com/npm/npm/issues/19394

**Comment by lohfu** [comment]
@G-Rath my bad, hadn't searched correctly. closing and referring to yours.

**Comment by lkmill** [comment]
@G-Rath my bad, hadn't searched correctly. closing and referring to yours.

closing as it is a duplicate of #19394
