### ISSUE TITLE
can't run npm packages from command line. Win10

### ISSUE THREAD

**Issue by GarryFlemings** [npm/npm#19464]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
After I install a package that should then make the command usable at the command line (e.g., documentation, local-npm, and preprocessor), I  get a report like "'documentation' is not recognized as an internal or external command, operable program or batch file." As a result, I can't find a way to use these packages.

#### How can the CLI team reproduce the problem?
Sorry. If I knew that, I could probably solve the problem. We'll have to meet in the middle somewhere!
No npm-debug.log file for this.

### supporting information:

 - `npm -v` prints: 3.9.5
 - `node -v` prints: 8.9.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Win10
 - Network issues:
   - Geographic location where npm was run: home (Cox.net, Bellevue, NE). Network working fine.
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

What I've done: Lots of reading about config, npmrc, etc. Installed npm 5.x for a day or so and had the same problems, reinstalled 3.9.5.

Maybe helpful: The first several lines of npm config ls -l are:
┌───────────────────────────────────────────────────────────────┐
│                    npm update check failed                    │
│              Try running with sudo or get access              │
│             to the local update config store via              │
│ sudo chown -R $USER:$(id -gn $USER) C:\Users\me\.config │
└───────────────────────────────────────────────────────────────┘
; cli configs
long = true
user-agent = "npm/3.9.5 node/v8.9.0 win32 x64"

; environment configs
prefix = "C:\\Development"

; userconfig C:\Users\me\.npmrc
; prefix = "C:\\Development\\node_modules\\npm" (overridden)
registry = "https://registry.npmjs.org/"

; builtin config undefined
; prefix = "C:\\Development\\node_modules\\npm" (overridden)

; default values
access = null
also = null
always-auth = false

---------
I don't know why the "environment configs" are deciding on "prefix = C:\Development"; I don't know the identity of "environment configs".

C:\Development\node-modules\npm would make sense; That's the highest-level node-modules on my system and the directory with all the npm -g files. That directory has a npmrc file (only the line, "prefix=C:\Development\node_modules\npm").

Projects are peers to that node-modules directory, with their own node-modules below them. That setting overrides all others.

Thanks for any help provided. I'll provide whatever other information you need. I don't know what's most useful yet.
<!--
    Thank you for contributing to npm! Please review this checklist
    before submitting your issue.

    - Please check if there's a solution in the troubleshooting wiki:
      https://github.com/npm/npm/blob/latest/TROUBLESHOOTING.md

I didn't find it. If it's there, I'm glad to use it!

    - Also ensure that your new issue conforms to npm's contribution guidelines:
      https://github.com/npm/npm/blob/latest/CONTRIBUTING.md

I **think** I conform. I **meant** to conform.

    - Participation in this open source project is subject to the npm Code of Conduct:
      https://www.npmjs.com/policies/conduct

All good to me.

Lots of the related documentation is specific to Posix. I'm not familiar with it. (sudo, chown. ${HOME}, etc.)

**Comment by pcostarg** [comment]
Are you installing those packages globally?

If they are local, you can only access the binary from the node_modules/.bin. for eg:
`./node_modules/.bin/documentation`
You can omit this path on npm scripts inside package.json. eg:
`"scripts": {
    "doc": "documentation"
  },`
Then run with:
`npm run doc`

Last but not least with version npm 5.2 you can use npx package that enables to skip the path on the cli. So `./node_modules/.bin/documentation` turns to `npx documentation`

Hope it helps

**Comment by GarryFlemings** [comment]
Great question! I left that out. And your write-up helped a lot.

Yup. I'm installing globally (-g).

With your advice about accessing packages via the `.bin` directory, I've gotten all three packages to run.

On the other hand, global installs are putting pairs of files in `C:\Development`. These are the same pairs of files I've gotten used to seeing in my `C:\Development\node_modules\.bin` for global installs.

Maybe ... that's because of (see prior post) `prefix = "C:\Development"`? 

Is there a way for me to control the prefix setting? The `environment configs` setting seems to override my attempts at that with `npmrc` files. If I knew how to do it, I would have tried setting it to `C:\Development\node_modules`. Or `C:\...\node_modules\npm`. Both of those seem like they'd be better.

Getting a little ahead: When I get global installs to put those batch files in `C:\Development\node_modules\.bin`, am I safe to move batch files from `C:\Development` to its `node_modules\.bin` directory? Or do I need to uninstall each package with those files in `C:\Development`?

Thanks tons.

**Comment by GarryFlemings** [comment]
I'm good. The NPM_CONFIG_PREFIX was the missing piece. Thanks tons.
