### ISSUE TITLE
How to install angular-cli inside restricted Network access environment using npm

### ISSUE THREAD

**Issue by iamsank8** [npm/npm#19463]
### Issue
I work in the company where I have restricted environment. If I need to install angular-cli on my machine, I can request network administrator to unblock the URL. But at first place, I don't know which URL to unblock.

• Please provide URL which are needs to unblocked for successful installation of angular-cli.
• If possible provide a GET STARTED guide for the enterprise environment.

I have unblocked the URL https://registry.npmjs.org, but it is not helping.
Attaching Debug file as well as error message.

[npm-debug.log](https://github.com/npm/npm/files/1587214/npm-debug.log)
![error](https://user-images.githubusercontent.com/24712341/34355356-9b773250-ea5a-11e7-932d-51291e582b08.PNG)

**Comment by JerryDoubleU** [comment]
I have the same problem on my private, totally unblocked (I think so) home internet. Sometimes switching to http solves this problem, sometimes makes it worse. No proxy, no firewall.

**Comment by iamsank8** [comment]
I have configured the Proxy as 
• npm set proxy=http://host:port
• npm set https-proxy=http://host:port

After that If you try ng -v it will give error as there is not PATH variable configured.
To counter this, use Node.js command prompt to navigate to your folder and start working with Angular.

**Comment by JerryDoubleU** [comment]
Switching to yarn helped - works through https perfectly
