### ISSUE TITLE
npm build says files are emitted but no files are found

### ISSUE THREAD

**Issue by Hpy2GitHub** [npm/npm#19476]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I've worked through a vue tutorial and the app runs.  I've added a homepage entry to package.json.  When I run npm run build, I get an output 

d:\Training\Udemy\js-simon-react_vs_angular_vs_vue\project-1\vue-simple (master -> origin)
λ npm run build

> vue-simple-website@1.0.0 build d:\Training\Udemy\js-simon-react_vs_angular_vs_vue\project-1\vue-simple
> node build/build.js

Hash: b65045f926d5016b403c
Version: webpack 3.10.0
Time: 8516ms
                                                  Asset       Size  Chunks             Chunk Names
                          static/img/clouds.d053e7c.jpg    15.1 kB          [emitted]
                  static/js/app.0333c49b8ba2de13d5a3.js    20.4 kB       0  [emitted]  app
               static/js/vendor.b8ae0360565c33c50d0d.js     113 kB       1  [emitted]  vendor
             static/js/manifest.f026ba99618e26065906.js    1.49 kB       2  [emitted]  manifest
    static/css/app.d520f14831678a237f3ecd9aa581d9dc.css     175 kB       0  [emitted]  app
static/css/app.d520f14831678a237f3ecd9aa581d9dc.css.map     316 kB          [emitted]
              static/js/app.0333c49b8ba2de13d5a3.js.map    92.4 kB       0  [emitted]  app
           static/js/vendor.b8ae0360565c33c50d0d.js.map     556 kB       1  [emitted]  vendor
         static/js/manifest.f026ba99618e26065906.js.map     7.8 kB       2  [emitted]  manifest
                                             index.html  622 bytes          [emitted]

  Build complete.

  Tip: built files are meant to be served over an HTTP server.
  Opening index.html over file:// won't work.

Then I look in static and no files or directories are there.  It's empty.

Probably I am just not understanding how the tool is supposed to work.  My plan was to deploy on a website running apache by copying the files from static to the server.

Oh, the files are in dist/static.  Never mind.

### supporting information:

 - `npm -v` prints: 5.5.1
 - `node -v` prints: v8.9.3
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: win7
 - Network issues:
   - Geographic location where npm was run: New Jersey
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
Those files are generated by `webpack`, not `npm`.
