### ISSUE TITLE
Unclean uninstalls?

### ISSUE THREAD

**Issue by TriMoon** [npm/npm#19484]
I noticed something very wrong while trying to install/uninstall esdoc.
No idea if this is due to a fault in **esdoc** or the current **npm/node** as i have updated those just before it.
See my report: https://github.com/esdoc/esdoc/issues/491

**Comment by itsAnuga** [comment]
I think it's because you have no package.json that defines what main packages that decides what to keep and what to remove.

<details>
<summary>E:\tools\temporary\test>dir</summary>

    Volume in drive E is systemRAID1
    Volume Serial Number is AAC5-12DC

    Directory of E:\tools\temporary\test

    2018-01-04  11:38    <DIR>          .
    2018-01-04  11:38    <DIR>          ..
                   0 File(s)              0 bytes
                   2 Dir(s)  432 834 953 216 bytes free

</details>

<details>
<summary>E:\tools\temporary\test>npm init</summary>

    This utility will walk you through creating a package.json file.
    It only covers the most common items, and tries to guess sensible defaults.

    See `npm help json` for definitive documentation on these fields
    and exactly what they do.

    Use `npm install <pkg>` afterwards to install a package and
    save it as a dependency in the package.json file.

    Press ^C at any time to quit.
    package name: (test)
    version: (1.0.0)
    description:
    entry point: (index.js)
    test command:
    git repository:
    keywords:
    author:
    license: (ISC)
    About to write to E:\tools\temporary\test\package.json:

    {
      "name": "test",
      "version": "1.0.0",
      "description": "",
      "main": "index.js",
      "scripts": {
        "test": "echo \"Error: no test specified\" && exit 1"
      },
      "author": "",
      "license": "ISC"
    }

    Is this ok? (yes)

</details>

<details>
<summary>E:\tools\temporary\test>npm install esdoc esdoc-standard-plugin --save</summary>

    npm notice created a lockfile as package-lock.json. You should commit this file.
    npm WARN test@1.0.0 No description
    npm WARN test@1.0.0 No repository field.

    + esdoc@1.0.4
    + esdoc-standard-plugin@1.0.0
    added 172 packages in 23.317s

</details>

<details>
<summary>E:\tools\temporary\test>npm list</summary>

    test@1.0.0 E:\tools\temporary\test
    +-- esdoc@1.0.4
    | +-- babel-generator@6.26.0
    | | +-- babel-messages@6.23.0
    | | | `-- babel-runtime@6.26.0 deduped
    | | +-- babel-runtime@6.26.0
    | | | +-- core-js@2.5.3
    | | | `-- regenerator-runtime@0.11.1
    | | +-- babel-types@6.26.0
    | | | +-- babel-runtime@6.26.0 deduped
    | | | +-- esutils@2.0.2
    | | | +-- lodash@4.17.4 deduped
    | | | `-- to-fast-properties@1.0.3
    | | +-- detect-indent@4.0.0
    | | | `-- repeating@2.0.1
    | | |   `-- is-finite@1.0.2
    | | |     `-- number-is-nan@1.0.1
    | | +-- jsesc@1.3.0
    | | +-- lodash@4.17.4
    | | +-- source-map@0.5.7
    | | `-- trim-right@1.0.1
    | +-- babel-traverse@6.26.0
    | | +-- babel-code-frame@6.26.0
    | | | +-- chalk@1.1.3
    | | | | +-- ansi-styles@2.2.1
    | | | | +-- escape-string-regexp@1.0.5
    | | | | +-- has-ansi@2.0.0
    | | | | | `-- ansi-regex@2.1.1
    | | | | +-- strip-ansi@3.0.1
    | | | | | `-- ansi-regex@2.1.1 deduped
    | | | | `-- supports-color@2.0.0
    | | | +-- esutils@2.0.2 deduped
    | | | `-- js-tokens@3.0.2
    | | +-- babel-messages@6.23.0 deduped
    | | +-- babel-runtime@6.26.0 deduped
    | | +-- babel-types@6.26.0 deduped
    | | +-- babylon@6.18.0 deduped
    | | +-- debug@2.6.9
    | | | `-- ms@2.0.0
    | | +-- globals@9.18.0
    | | +-- invariant@2.2.2
    | | | `-- loose-envify@1.3.1
    | | |   `-- js-tokens@3.0.2 deduped
    | | `-- lodash@4.17.4 deduped
    | +-- babylon@6.18.0
    | +-- cheerio@0.22.0
    | | +-- css-select@1.2.0
    | | | +-- boolbase@1.0.0
    | | | +-- css-what@2.1.0
    | | | +-- domutils@1.5.1
    | | | | +-- dom-serializer@0.1.0 deduped
    | | | | `-- domelementtype@1.3.0 deduped
    | | | `-- nth-check@1.0.1
    | | |   `-- boolbase@1.0.0 deduped
    | | +-- dom-serializer@0.1.0
    | | | +-- domelementtype@1.1.3
    | | | `-- entities@1.1.1 deduped
    | | +-- entities@1.1.1
    | | +-- htmlparser2@3.9.2
    | | | +-- domelementtype@1.3.0
    | | | +-- domhandler@2.4.1
    | | | | `-- domelementtype@1.3.0 deduped
    | | | +-- domutils@1.5.1 deduped
    | | | +-- entities@1.1.1 deduped
    | | | +-- inherits@2.0.3
    | | | `-- readable-stream@2.3.3
    | | |   +-- core-util-is@1.0.2
    | | |   +-- inherits@2.0.3 deduped
    | | |   +-- isarray@1.0.0
    | | |   +-- process-nextick-args@1.0.7
    | | |   +-- safe-buffer@5.1.1
    | | |   +-- string_decoder@1.0.3
    | | |   | `-- safe-buffer@5.1.1 deduped
    | | |   `-- util-deprecate@1.0.2
    | | +-- lodash.assignin@4.2.0
    | | +-- lodash.bind@4.2.1
    | | +-- lodash.defaults@4.2.0
    | | +-- lodash.filter@4.6.0
    | | +-- lodash.flatten@4.4.0
    | | +-- lodash.foreach@4.5.0
    | | +-- lodash.map@4.6.0
    | | +-- lodash.merge@4.6.0
    | | +-- lodash.pick@4.4.0
    | | +-- lodash.reduce@4.6.0
    | | +-- lodash.reject@4.6.0
    | | `-- lodash.some@4.6.0
    | +-- color-logger@0.0.3
    | +-- escape-html@1.0.3
    | +-- fs-extra@1.0.0
    | | +-- graceful-fs@4.1.11
    | | +-- jsonfile@2.4.0
    | | | `-- graceful-fs@4.1.11 deduped
    | | `-- klaw@1.3.1
    | |   `-- graceful-fs@4.1.11 deduped
    | +-- ice-cap@0.0.4
    | | +-- cheerio@0.20.0
    | | | +-- css-select@1.2.0 deduped
    | | | +-- dom-serializer@0.1.0 deduped
    | | | +-- entities@1.1.1 deduped
    | | | +-- htmlparser2@3.8.3
    | | | | +-- domelementtype@1.3.0 deduped
    | | | | +-- domhandler@2.3.0
    | | | | | `-- domelementtype@1.3.0 deduped
    | | | | +-- domutils@1.5.1 deduped
    | | | | +-- entities@1.0.0
    | | | | `-- readable-stream@1.1.14
    | | | |   +-- core-util-is@1.0.2 deduped
    | | | |   +-- inherits@2.0.3 deduped
    | | | |   +-- isarray@0.0.1
    | | | |   `-- string_decoder@0.10.31
    | | | +-- jsdom@7.2.2
    | | | | +-- abab@1.0.4
    | | | | +-- acorn@2.7.0
    | | | | +-- acorn-globals@1.0.9
    | | | | | `-- acorn@2.7.0 deduped
    | | | | +-- cssom@0.3.2
    | | | | +-- cssstyle@0.2.37
    | | | | | `-- cssom@0.3.2 deduped
    | | | | +-- escodegen@1.9.0
    | | | | | +-- esprima@3.1.3
    | | | | | +-- estraverse@4.2.0
    | | | | | +-- esutils@2.0.2 deduped
    | | | | | +-- optionator@0.8.2
    | | | | | | +-- deep-is@0.1.3
    | | | | | | +-- fast-levenshtein@2.0.6
    | | | | | | +-- levn@0.3.0
    | | | | | | | +-- prelude-ls@1.1.2 deduped
    | | | | | | | `-- type-check@0.3.2 deduped
    | | | | | | +-- prelude-ls@1.1.2
    | | | | | | +-- type-check@0.3.2
    | | | | | | | `-- prelude-ls@1.1.2 deduped
    | | | | | | `-- wordwrap@1.0.0
    | | | | | `-- source-map@0.5.7 deduped
    | | | | +-- nwmatcher@1.4.3
    | | | | +-- parse5@1.5.1
    | | | | +-- request@2.83.0
    | | | | | +-- aws-sign2@0.7.0
    | | | | | +-- aws4@1.6.0
    | | | | | +-- caseless@0.12.0
    | | | | | +-- combined-stream@1.0.5
    | | | | | | `-- delayed-stream@1.0.0
    | | | | | +-- extend@3.0.1
    | | | | | +-- forever-agent@0.6.1
    | | | | | +-- form-data@2.3.1
    | | | | | | +-- asynckit@0.4.0
    | | | | | | +-- combined-stream@1.0.5 deduped
    | | | | | | `-- mime-types@2.1.17 deduped
    | | | | | +-- har-validator@5.0.3
    | | | | | | +-- ajv@5.5.2
    | | | | | | | +-- co@4.6.0
    | | | | | | | +-- fast-deep-equal@1.0.0
    | | | | | | | +-- fast-json-stable-stringify@2.0.0
    | | | | | | | `-- json-schema-traverse@0.3.1
    | | | | | | `-- har-schema@2.0.0
    | | | | | +-- hawk@6.0.2
    | | | | | | +-- boom@4.3.1
    | | | | | | | `-- hoek@4.2.0 deduped
    | | | | | | +-- cryptiles@3.1.2
    | | | | | | | `-- boom@5.2.0
    | | | | | | |   `-- hoek@4.2.0 deduped
    | | | | | | +-- hoek@4.2.0
    | | | | | | `-- sntp@2.1.0
    | | | | | |   `-- hoek@4.2.0 deduped
    | | | | | +-- http-signature@1.2.0
    | | | | | | +-- assert-plus@1.0.0
    | | | | | | +-- jsprim@1.4.1
    | | | | | | | +-- assert-plus@1.0.0 deduped
    | | | | | | | +-- extsprintf@1.3.0
    | | | | | | | +-- json-schema@0.2.3
    | | | | | | | `-- verror@1.10.0
    | | | | | | |   +-- assert-plus@1.0.0 deduped
    | | | | | | |   +-- core-util-is@1.0.2 deduped
    | | | | | | |   `-- extsprintf@1.3.0 deduped
    | | | | | | `-- sshpk@1.13.1
    | | | | | |   +-- asn1@0.2.3
    | | | | | |   +-- assert-plus@1.0.0 deduped
    | | | | | |   +-- bcrypt-pbkdf@1.0.1
    | | | | | |   | `-- tweetnacl@0.14.5 deduped
    | | | | | |   +-- dashdash@1.14.1
    | | | | | |   | `-- assert-plus@1.0.0 deduped
    | | | | | |   +-- ecc-jsbn@0.1.1
    | | | | | |   | `-- jsbn@0.1.1 deduped
    | | | | | |   +-- getpass@0.1.7
    | | | | | |   | `-- assert-plus@1.0.0 deduped
    | | | | | |   +-- jsbn@0.1.1
    | | | | | |   `-- tweetnacl@0.14.5
    | | | | | +-- is-typedarray@1.0.0
    | | | | | +-- isstream@0.1.2
    | | | | | +-- json-stringify-safe@5.0.1
    | | | | | +-- mime-types@2.1.17
    | | | | | | `-- mime-db@1.30.0
    | | | | | +-- oauth-sign@0.8.2
    | | | | | +-- performance-now@2.1.0
    | | | | | +-- qs@6.5.1
    | | | | | +-- safe-buffer@5.1.1 deduped
    | | | | | +-- stringstream@0.0.5
    | | | | | +-- tough-cookie@2.3.3 deduped
    | | | | | +-- tunnel-agent@0.6.0
    | | | | | | `-- safe-buffer@5.1.1 deduped
    | | | | | `-- uuid@3.1.0
    | | | | +-- sax@1.2.4
    | | | | +-- symbol-tree@3.2.2
    | | | | +-- tough-cookie@2.3.3
    | | | | | `-- punycode@1.4.1
    | | | | +-- webidl-conversions@2.0.1
    | | | | +-- whatwg-url-compat@0.6.5
    | | | | | `-- tr46@0.0.3
    | | | | `-- xml-name-validator@2.0.1
    | | | `-- lodash@4.17.4 deduped
    | | `-- color-logger@0.0.3 deduped
    | +-- marked@0.3.6
    | +-- minimist@1.2.0
    | `-- taffydb@2.7.2
    `-- esdoc-standard-plugin@1.0.0
      +-- esdoc-accessor-plugin@1.0.0
      +-- esdoc-brand-plugin@1.0.0
      | `-- cheerio@0.22.0 deduped
      +-- esdoc-coverage-plugin@1.1.0
      +-- esdoc-external-ecmascript-plugin@1.0.0
      | `-- fs-extra@1.0.0 deduped
      +-- esdoc-integrate-manual-plugin@1.0.0
      +-- esdoc-integrate-test-plugin@1.0.0
      +-- esdoc-lint-plugin@1.0.1
      +-- esdoc-publish-html-plugin@1.1.0
      | +-- babel-generator@6.11.4
      | | +-- babel-messages@6.23.0 deduped
      | | +-- babel-runtime@6.26.0 deduped
      | | +-- babel-types@6.26.0 deduped
      | | +-- detect-indent@3.0.1
      | | | +-- get-stdin@4.0.1
      | | | +-- minimist@1.2.0 deduped
      | | | `-- repeating@1.1.3
      | | |   `-- is-finite@1.0.2 deduped
      | | +-- lodash@4.17.4 deduped
      | | `-- source-map@0.5.7 deduped
      | +-- cheerio@0.22.0 deduped
      | +-- escape-html@1.0.3 deduped
      | +-- fs-extra@1.0.0 deduped
      | +-- ice-cap@0.0.4 deduped
      | +-- marked@0.3.6 deduped
      | `-- taffydb@2.7.2 deduped
      +-- esdoc-type-inference-plugin@1.0.1
      +-- esdoc-undocumented-identifier-plugin@1.0.0
      `-- esdoc-unexported-identifier-plugin@1.0.0

</details>

<details>
<summary>E:\tools\temporary\test>npm remove esdoc esdoc-standard-plugin</summary>

    npm WARN test@1.0.0 No description
    npm WARN test@1.0.0 No repository field.

    removed 172 packages in 4.487s

</details>
<details>
<summary>E:\tools\temporary\test>npm list</summary>

    test@1.0.0 E:\tools\temporary\test
    `-- (empty)

</details>

**Comment by TriMoon** [comment]
Continuing the issue discussion at https://github.com/esdoc/esdoc/issues/491 because it's an **esdoc** issue in that case...
