### ISSUE TITLE
Raspberry Pi cannot do  npm install @types/node

### ISSUE THREAD

**Issue by hoanglamly** [npm/npm#19490]
Hello,

I can do npm install @types/node in Ubuntu, but I cannot do similar install with Raspberry Pi 3. I need this package to run ngrok. Thank you

> pi@raspberrypi:~ $ node -v
> v4.8.2
> pi@raspberrypi:~ $ npm -v
> 1.4.21
> pi@raspberrypi:~ $ npm install  types/node
> npm WARN package.json 'types@0.1.1' license should be a valid SPDX license expression
> npm ERR! git clone git@github.com:types/node Cloning into bare repository '/home/pi/.npm/_git-remotes/git-github-com-types-node-921b5735'...
> npm ERR! git clone git@github.com:types/node ERROR: Repository not found.
> npm ERR! git clone git@github.com:types/node fatal: Could not read from remote repository.
> npm ERR! git clone git@github.com:types/node
> npm ERR! git clone git@github.com:types/node Please make sure you have the correct access rights
> npm ERR! git clone git@github.com:types/node and the repository exists.
> npm ERR! addLocal Could not install types/node
> npm ERR! Error: ENOENT: no such file or directory, stat 'types/node'
> npm ERR!     at Error (native)
> npm ERR! If you need help, you may report this *entire* log,
> npm ERR! including the npm and node versions, at:
> npm ERR!     <http://github.com/npm/npm/issues>

> npm ERR! System Linux 4.9.59-v7+
>  npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "@types/node"
> npm ERR! cwd /home/pi
> npm ERR! node -v v4.8.2
> npm ERR! npm -v 1.4.21
> npm ERR! path types/node
> npm ERR! syscall stat
> npm ERR! code ENOENT
> npm ERR! errno -2
> npm ERR!
> npm ERR! Additional logging details can be found in:
> npm ERR!     /home/pi/npm-debug.log
> npm ERR! not ok code 0
> pi@raspberrypi:~ $

[npm-debug.log](https://github.com/npm/npm/files/1596584/npm-debug.log)

**Comment by kenany** [comment]
Your version of `npm` is years old and is no longer supported.
