### ISSUE TITLE
laravel npm

### ISSUE THREAD

**Issue by tecbay** [npm/npm#19495]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@5.5.1
3 info using node@v8.9.3
4 verbose stack Error: Failed to parse json
4 verbose stack Unexpected token
4 verbose stack  in JSON at position 183 while parsing '{
4 verbose stack   "private": true,
4 verbose stack   "scripts": {
4 verbose stack     '
4 verbose stack     at parseError (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:436:11)
4 verbose stack     at parseJson (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:104:26)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:51:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
5 verbose cwd E:\xampp\htdocs\examhub\eppbd
6 verbose Windows_NT 10.0.15063
7 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
8 verbose node v8.9.3
9 verbose npm  v5.5.1
10 error file E:\xampp\htdocs\examhub\eppbd\package.json
11 error code EJSONPARSE
12 error Failed to parse json
12 error Unexpected token
12 error  in JSON at position 183 while parsing '{
12 error   "private": true,
12 error   "scripts": {
12 error     '
13 error File: E:\xampp\htdocs\examhub\eppbd\package.json
14 error Failed to parse package.json data.
14 error package.json must be actual JSON, not just JavaScript.
14 error
14 error Tell the package author to fix their package.json file. JSON.parse
15 verbose exit [ 1, true ]

**Comment by kenany** [comment]
Ensure that your `package.json` has valid JSON syntax. The error message points to the exact character which is causing the parse to fail.
