### ISSUE TITLE
npm ERR! cb() never called

### ISSUE THREAD

**Issue by lideveloper** [npm/npm#19496]
weex debug
This command need to install weex-devtool. Installing...
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\AppData\Roaming\npm-cache\_logs\2018-01-03T03_19_40_198Z-debug.log
Error: fatal error!
    at installer.(anonymous function).then (C:\Users\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\_xtoolkit@0.2.10@xtoolkit\src\Command.js:45:19)

**Comment by xiaoxiao12345** [comment]
sudo apt-get update  you can do,
and if it call a error,
http://archive.ubuntukylin.com:10006/ukdiscuz/portal.php   (this is the origenate) the linke have error

**Comment by chinmay90kulkarni** [comment]
Got the same error.! :(

**Comment by BJackNoBlack** [comment]
same error
