### ISSUE TITLE
Error: ENOENT open 

### ISSUE THREAD

**Issue by arunchaitanya** [npm/npm#19508]
#### I'm opening this issue because:

  - [ ] npm is doing something I don't understand.
  
#### What's going wrong?
I am running npm update and it fails with exit code of 127

#### How can the CLI team reproduce the problem?
Instructions to reproduce:
curl https://raw.githubusercontent.com/creationix/nvm/v0.25.0/install.sh | bash \
	&&  source ~/.bashrc && nvm install v0.10.28 && nvm current && npm install -g gulp@v3.9.0 && mkdir /opt/ster-install/StoreBuild \
	&& cp -r /opt/sterling/runtime/nodebuild/wsc/* /opt/ster-install/StoreBuild/ && ls -al && cd /opt/ster-install/StoreBuild \
	&& npm update && cp /tmp/ngstore.build.extn.config.json . && gulp --gulpfile ngstore_build_extn_gulp.js

I am attaching the package.json as package.json.txt
[package.json.txt](https://github.com/npm/npm/files/1602602/package.json.txt)

### supporting information:
npm ERR! Error: ENOENT, open '/opt/StoreBuild/node_modules/angular-jsdoc/node_modules/angular-template/node_modules/cheerio/node_modules/lodash/sortedLastIndexBy.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.10.0-514.21.1.el7.x86_64
npm ERR! command "/root/.nvm/v0.10.28/bin/node" "/root/.nvm/v0.10.28/bin/npm" "update"
npm ERR! cwd /opt/StoreBuild
npm ERR! node -v v0.10.28
[npm-debug.log](https://github.com/npm/npm/files/1602589/npm-debug.log)

npm ERR! npm -v 1.4.9
npm ERR! path /opt/StoreBuild/node_modules/angular-jsdoc/node_modules/angular-template/node_modules/cheerio/node_modules/lodash/sortedLastIndexBy.js
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'types/node' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'parse5'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 3.10.0-514.21.1.el7.x86_64
npm ERR! command "/root/.nvm/v0.10.28/bin/node" "/root/.nvm/v0.10.28/bin/npm" "update"
npm ERR! cwd /opt/StoreBuild
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! code E404
 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
The versions of Node.js and `npm` you are trying to use through `nvm` are no longer supported by the `npm` team.
