### ISSUE TITLE
error: cb() never called!

### ISSUE THREAD

**Issue by pyadavan** [npm/npm#19516]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'appium' ]
2 info using npm@5.6.0
3 info using node@v8.9.4
4 verbose npm-session 344a2b6cc395b3b1
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 200 https://registry.npmjs.org/appium 1832ms
8 http fetch GET 200 https://registry.npmjs.org/appium/-/appium-1.7.2.tgz 63017ms
9 error cb() never called!
10 error This is an error with npm itself. Please report this error at:
11 error <https://github.com/npm/npm/issues>

**Comment by kenany** [comment]
Could you upload the _full_ debug log file to <https://gist.github.com/> and link it here? Thanks!

**Comment by thebere** [comment]
Hello @pyadavan, any update on this? I ran into the same issue. I use nvm. Currently running node:8.9.2, and npm:5.3.0

**Comment by thebere** [comment]
Hello @pyadavan This might help you out https://github.com/facebook/react-native/issues/10028

**Comment by pyadavan** [comment]
working fine now. thanks!!!
