### ISSUE TITLE
command in node.js "cordova build android" gives me this error "ERROR: JAVA_HOME is set to an invalid directory: C:\Program Files\Java\jdk1.8.0_40\bin"

### ISSUE THREAD

**Issue by kvamshi19** [npm/npm#19518]
Hi Team,

Am trying to build my code in Node.js cmd promt, but i ran into a problem.

![image](https://user-images.githubusercontent.com/12985503/34577186-51f5a686-f1a6-11e7-929b-351cc1279771.png)

Command used : "cordova build android" or "cordova build"

I have my Java Installed and JAVA_HOME has been set in path, even though am facing this issue. Am unable to figure out where am missing. Someone do help me.

Is this the right place am looking for ?

Thanks,
Vamshi

**Comment by ralbear** [comment]
Hi, have you check the JAVA_HOME path, it is pointing to the correct java files? You can check this guide: [https://confluence.atlassian.com/doc/setting-the-java_home-variable-in-windows-8895.html](url)

Also have a simple username without '$ could you help to solve some issues.

**Comment by kenany** [comment]
Closing since this issue tracker is for `npm`-specific issues only. Perhaps you could take this to a more general site like StackOverflow. Good luck!
