### ISSUE TITLE
When i run "npm install npm test"i get to see Error!!

### ISSUE THREAD

**Issue by deepaksharma009** [npm/npm#19511]
When i run "npm install npm test"i get to see below error..
+ npm install npm test
npm WARN package.json hello-world@0.0.1 No repository field.
npm ERR! Error: Attempt to unlock npm, which hasn't been locked
npm ERR!     at unlock (/usr/share/npm/lib/utils/locker.js:44:11)
npm ERR!     at cb (/usr/share/npm/lib/cache/add-local.js:30:5)
npm ERR!     at /usr/share/npm/lib/cache/add-local.js:47:20
npm ERR!     at /usr/share/npm/lib/utils/locker.js:22:20
npm ERR!     at /usr/share/npm/node_modules/inflight/inflight.js:22:7
npm ERR!     at Array.forEach (native)
npm ERR!     at res (/usr/share/npm/node_modules/inflight/inflight.js:21:9)
npm ERR!     at /usr/lib/nodejs/once.js:17:15
npm ERR!     at afterMkdir (/usr/share/npm/lib/cache/get-stat.js:53:14)
npm ERR!     at /usr/lib/nodejs/mkdirp/index.js:46:53

**Comment by itsAnuga** [comment]
`npm install` is one command,
`npm test` is one command, if specified in package.json

You could do it as, `npm install && npm test` if that is what your aiming for.

**Comment by deepaksharma009** [comment]
Thanks Anuga. I tried it this time as "npm install && npm test",  but i am still facing the below error..
+ npm install
npm WARN package.json hello-world@0.0.1 No repository field.
npm ERR! Error: Attempt to unlock jshint@^2.9.4, which hasn't been locked
npm ERR!     at unlock (/usr/share/npm/lib/utils/locker.js:44:11)
npm ERR!     at cb (/usr/share/npm/lib/cache/add-named.js:32:5)
npm ERR!     at /usr/share/npm/lib/cache/add-named.js:41:20
npm ERR!     at /usr/share/npm/lib/utils/locker.js:22:20
npm ERR!     at /usr/share/npm/node_modules/inflight/inflight.js:22:7
npm ERR!     at Array.forEach (native)
npm ERR!     at res (/usr/share/npm/node_modules/inflight/inflight.js:21:9)
npm ERR!     at /usr/lib/nodejs/once.js:17:15
npm ERR!     at afterMkdir (/usr/share/npm/lib/cache/get-stat.js:53:14)
npm ERR!     at /usr/lib/nodejs/mkdirp/index.js:46:53
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.4.0-93-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /bitnami/jenkins/workspace/UI-JUNIOR
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /bitnami/jenkins/workspace/UI-JUNIOR/npm-debug.log
npm ERR! not ok code 0
Build step 'Execute shell' marked build as failure
Archiving artifacts
Finished: FAILURE

**Comment by kenany** [comment]
Sorry, but your versions of Node.js and `npm` are _years_ old and are no longer supported.

**Comment by deepaksharma009** [comment]
Hi Kenan,

Please let me know how to install the latest version of npm and Node.js into docker container in linux/unix region. Thanks in advance for the help!!

**Comment by kenany** [comment]
Perhaps the [official Node.js Docker image](https://github.com/nodejs/docker-node) is what you are looking for.
