### ISSUE TITLE
.npmrc config preferred over --registry option for scoped modules

### ISSUE THREAD

**Issue by joeledwards** [npm/npm#19517]
#### I'm opening this issue because:
  - npm is not behaving as expected

#### What's going wrong?
npm prefers the value of the scope configuration in .npmrc over the `--registry` option when interacting with scoped modules.

#### How can the CLI team reproduce the problem?

Having a `.npmrc` file which contains a configuration associating a scope with a private registry:
```
@myscope:registry=https://registry.mynpme.tld/
```

Then attempts to view a package for that same scope on a different via the `--registry` option will still use the registry setting from `.npmrc`:
```
$ npm view --registry=https://registry.npmjs.com @myscope/mypkg
{ name: '@myscope/mypkg',
... SNIP ...
     tarball: 'https://registry.mynpme.tld/@/@myscope/mypkg/_attachments/mypkg-1.0.0.tgz' },
  directories: {} }
```

### supporting information:

 - `npm -v` prints: `5.6.0`
 - `node -v` prints: `v8.9.3`
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?: `uname -a` => `Darwin REDACTED_HOST.local 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64`
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by iarna** [comment]
`--registry` changes the default registry, but does not reconfigure scopes routed to scope-specific registries.

To do that, use: `--@scopeName:registry=https://registry.url` and `--//registry.url/:_authToken=your-private-token`
