### ISSUE TITLE
npm5 create react-native failed

### ISSUE THREAD

**Issue by CJianYu** [npm/npm#19529]
******************************************************************************* 
ERROR: npm 5 is not supported yet                                               
******************************************************************************* 
                                                                                
It looks like you're using npm 5 which was recently released.                   
                                                                                
Create React Native App doesn't work with npm 5 yet, unfortunately. We          
recommend using npm 4 or yarn until some bugs are resolved.                     
                                                                                
You can follow the known issues with npm 5 at:                                  
https://github.com/npm/npm/issues/16991                                         
                                                                                
******************************************************************************* 
                                                                                
error like this,hope that fix it in the future,thanks

**Comment by kenany** [comment]
Closing since this coming from `create-react-native-app`, not `npm` itself.
