### ISSUE TITLE
What is this issue about error creating my projects and upgrading

### ISSUE THREAD

**Issue by carmabol** [npm/npm#19537]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ X ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
This appeared me in the log:

**18456 error Windows_NT 10.0.16299
18457 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "upgrade" "-g"
18458 error node v6.11.4
18459 error npm  v3.10.10
18460 error Cannot convert undefined or null to object
18461 error If you need help, you may report this error at:
18461 error     <https://github.com/npm/npm/issues>**

### supporting information:

 - `npm -v` prints: 3.10.10
 - `node -v` prints: v6.11.4
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [X ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by lordnino** [comment]
@carmabol it's an issue in npm, some repo got deleted and they are trying to restore it right now.
you can follow the update here : https://status.npmjs.org/incidents/41zfb8qpvrdj

**Comment by carmabol** [comment]
@lordnino excellent, thank you so much, i tried upgrade the npm and after i installed the angular client (That i am working) and it worked again! :)
