### ISSUE TITLE
"express" install fails

### ISSUE THREAD

**Issue by ranshe** [npm/npm#19530]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
npm ERR! Linux 4.4.0-1041-aws
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "express"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2

npm ERR! Cannot read property 'target' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/node_modules/mbed-cloud-sdk/examples/node/npm-debug.log
ubuntu@ip-172-31-25-20:~/node_modules/mbed-cloud-sdk/examples/node$ sudo npm install express
npm ERR! Linux 4.4.0-1041-aws
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "express"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2

npm ERR! Cannot read property 'target' of null

#### How can the CLI team reproduce the problem?
 npm install express

### supporting information:

npm -v
3.5.2
node -v
v4.2.6
npm config get registry
https://registry.npmjs.org/

 - Windows, OS X/macOS, or Linux?: Linux
 - Network issues:
   - Geographic location where npm was run: Oregon (AWS)
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
Does this also occur with `npm@4` or `npm@5`?

**Comment by kenany** [comment]
Closing as abandoned.
