### ISSUE TITLE
npm@1.4.21 | node@v0.10.29 |  Error: ENOENT, open '/home/[[username]]/node_modules/gulp/package.json' | DISTRO: mx16.1

### ISSUE THREAD

**Issue by ohsevin** [npm/npm#19531]
**## start--- REPRODUCTION OF LOGGED BUG ##**
```
  GNU nano 2.2.6               File: /home/artik/npm-debug.log                                      

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'gulp', 'watch' ]
2 info using npm@1.4.21
3 info using node@v0.10.29
4 verbose config Skipping project config: /home/[[username]]/.npmrc. (matches userconfig)
5 error Error: ENOENT, open '/home/[[username]]/node_modules/gulp/package.json'
6 error If you need help, you may report this *entire* log,
6 error including the npm and node versions, at:
6 error     <http://github.com/npm/npm/issues>
7 error System Linux 4.7.0-0.bpo.1-amd64
8 error command "/usr/bin/nodejs" "/usr/bin/npm" "run" "gulp" "watch"
9 error cwd /home/[[username]]
10 error node -v v0.10.29
11 error npm -v 1.4.21
12 error path /home/[[username]]/node_modules/gulp/package.json
13 error code ENOENT
14 error errno 34
15 verbose exit [ 34, true ]

```
**## end--- REPRODUCTION OF LOGGED BUG ##**

#### I'm opening this issue because:

  - [X] npm is crashing.
  - [X] npm is producing an incorrect install.
  - [X] npm is doing something I don't understand.
  - [_] Other (_see below for feature requests_):

#### What's going wrong?
duno that's why ya'll are here lawl, this isn't my project so i'm not as privy to the code involved and the dependent variables you lean on to provide the robust massive service. ;)

#### How can the CLI team reproduce the problem?
FIRST command(s):
```
$ npm install
or
$ sudo npm install
```

##GOAL was to install "YakYak" upon arriving at the ability to reproduce similar conditions I have previously built sucessfully on other systems using npm/node/snapd +yakyak

DISTO USED WHEN LOGGED: MX16

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
Sorry, but your versions of Node.js and `npm` are years old and are no longer supported.

**Comment by ohsevin** [comment]
**LS;WR:** hey sorry about that slight moment of autism or glaucoma--I certainly am privy enough to should have noticed such a trivial thing as OLD version(s). **BUT** by chance (if you don't mind) would you have any suggestions additions to add to GalliumOS ? || would you think adding any xenial repos along with my current sources for said GalliumOS or even for use SOLELY and withou the use of the previous repos given with the galliumos.list? 

[my uname -a shows a xenial ubuntu release based system]

--no harm no foul; figured I'd offer up the error since it & its log-ish became so available upon crash.
