### ISSUE TITLE
Ionic/Cordova error in installation 

### ISSUE THREAD

**Issue by christianmontebon** [npm/npm#19540]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I was try to install **ionic cordova** via this command npm **install -g cordova ionic** and theres an error that i don't understand. It's working fine on my desktop but in my laptop it'll give this error.

```
C:\>npm install -g cordova ionic
npm ERR! code ENOVERSIONS
npm ERR! No valid versions available for pinkie-promise

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Monte\AppData\Roaming\npm-cache\_logs\2018-01-06T21_03_03_
640Z-debug.log
```

### supporting information:

 - `npm -v` prints: 5.5.1
 - `node -v` prints: 8.9.3
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows 7

**Comment by JAertgeerts** [comment]
This is fixed and can be closed - https://status.npmjs.org/incidents/41zfb8qpvrdj
