### ISSUE TITLE
--ignore-scripts not documented as part of the install options

### ISSUE THREAD

**Issue by thomasklein** [npm/npm#19557]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [X ] Other (_see below for feature requests_):

#### What's going wrong?

`ignore-scripts` is only documented as a configuration [option](https://docs.npmjs.com/misc/config#ignore-scripts) but not as an CLI install parameter neither in the [online docs](https://docs.npmjs.com/cli/install) nor in the CLI `man`.

#### How can the CLI team reproduce the problem?

https://docs.npmjs.com/cli/install or `npm help install`

### supporting information:

 - `npm -v` prints: 5.6.0
 - `node -v` prints: 8.9.0
 - `npm config get registry` prints: https://registry.npmjs.org
 - Windows, OS X/macOS, or Linux?: OS X
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by aulisius** [comment]
In both the [online docs](https://docs.npmjs.com/cli/install) and `npm help install`, `--ignore-scripts` is actually documented.

> The --ignore-scripts argument will cause npm to not execute any scripts defined in the package.json. See npm-scripts.

**Comment by thomasklein** [comment]
Hi @aulisius! Yes, I confirm the occurrence in both the online docs and the npm CLI manual. Well, I must have had a strange day then. Sorry for the confusion.
