### ISSUE TITLE
SPDX v3.x has been released, `npm install` warns against new valid licenses

### ISSUE THREAD

**Issue by ntwb** [npm/npm#19558]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?

npm is reporting that I'm not using a valid license:
> `npm WARN packages license should be a valid SPDX license expression`

#### How can the CLI team reproduce the problem?

Use a SPDX v3.x license string in `package.json`, e.g. `"license": "GPL-2.0-or-later",` (This license string replaces the now deprecated `"license": "GPL-2.0+",` string)

SPDX v3 release post: https://spdx.org/news/news/2018/01/license-list-30-released
SPDX v3.x License List: https://spdx.org/licenses/

cc @kemitchell It looks like SPDX license information is via some of npm modules, I started digging through them to find which one I should create an issue for and I got completely lost 😏 

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kemitchell** [comment]
@ntwd, thanks for creating this issue. I saw the 3.0 release, and it's been on my list to review npm-related work accordingly.

I still have a little homework to do, reading the 3.0 release and comparing salient parts to existing implementations. But at least one upshot of a 3.0 upgrade for npm could be significant, if not pervasive, "breakage", in the sense of invaliding previously valid inputs. In particular, all of the old GPL identifiers---for GPL, LGPL, and AGPL---will become deprecated in favor of more specific ones, like `GPL-3.0-or-later`.  I need to think a bit about how to handle that.

**Comment by wking** [comment]
> But at least one upshot of a 3.0 upgrade for npm could be significant, if not pervasive, "breakage", in the sense of invaliding previously valid inputs. In particular, all of the old GPL identifiers---for GPL, LGPL, and AGPL---will become deprecated in favor of more specific ones, like `GPL-3.0-or-later`.

@shinnn's recommendation to [create a new package for deprecated IDs][1] sounds reasonable to me.  However it gets sorted, I recommend npm continue to support deprecated IDs and warn folks who use them about upgrading before the deprecation becomes a breaking removal (probably at least a few years out).  If/when it lands, spdx/license-list-XML#392 will give structured information about what SPDX recommends updating to, so that might be worth designing for.  You'd also want to consider whether you want client-side warnings, server-side warnings, or both.

[1]: https://github.com/shinnn/spdx-license-ids/pull/8#issuecomment-356492194

**Comment by ntwb** [comment]
I see v3.0.0 of spdx-license-ids was released: https://github.com/shinnn/spdx-license-ids/releases/tag/v3.0.0

What package depends on that to get that package updated to be added to npm here?

**Comment by kemitchell** [comment]
I've just released validate-npm-package-license@3.0.2. npm should pick it up in their next sweep of version deps.

**Comment by ntwb** [comment]
Awesome, thanks a bunch @kemitchell 💐

**Comment by ntwb** [comment]
@kemitchell npm aren't using `validate-npm-package-license` 😱 

https://github.com/npm/npm/blob/latest/package.json#L130

Is there another package that depends on `validate-npm-package-license` that is being used that may have missed the latest release?

**Comment by kemitchell** [comment]
https://github.com/npm/npm/blob/ee147fbbca6f2707d3b16f4fa78f4c4606b2d9b1/package-lock.json#L9047

**Comment by ntwb** [comment]
> npm/package-lock.json Line 9047 in ee147fb

@kemitchell That is version `3.0.1` added over 2 years ago in commit https://github.com/npm/npm/commit/a5b0a8db561916086fc7dbd6eb2836c952a42a7e#diff-36018a6a9e1de1798516799b84841318R4481

With `package-lock.json` generated from the packages in `package.json`, what package is `validate-npm-package-license` a dependency of that npm uses in its `package.json` file so that we can get this updated and shipped please?

**Comment by mlinksva** [comment]
Just an idle watcher here, but I don't think anything needs updating besides the `package-lock.json` in this repo.  init-package-json and normalize-package-data each depend on `^3.0.1` (i.e., they're fine with any 3.x) -- running `npm update` obtains 3.0.3 (and updates various other packages within constraints) -- I imagine that's what @kemitchell meant by "npm should pick it up in their next sweep of version deps" above.

**Comment by mlinksva** [comment]
Appears this is fixed in npm6 https://github.com/npm/npm/blob/v6.0.0/package-lock.json#L11724-L11726
