### ISSUE TITLE
"npm install" doesnt install devDependencies

### ISSUE THREAD

**Issue by rejas** [npm/npm#19577]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Running "npm install" on my pc doesnt install the devDependencies from my package.json, it only installs the dependencies. The production flag is set to false so I am not sure why it skips the devDeps :-(

On other windows10 or macOS machines it works as expected.  

#### How can the CLI team reproduce the problem?

Probably not since on my other windows pc I cannot reproduce it either with the same node/npm versions. 

### supporting information:

 - `npm -v` prints: 5.6.0
 - `node -v` prints: 8.9.4
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows 10 (1703)

```
C:\Projekte>npm config list
; cli configs
metrics-registry = "https://registry.npmjs.org/"
scope = ""
user-agent = "npm/5.6.0 node/v8.9.4 win32 x64"

; userconfig C:\Users\xxx\.npmrc
cache = "C:\\Projekte\\sdk\\npm\\cache"
global = true
msvs_version = "2015"
prefix = "C:\\Projekte\\sdk\\npm"
python = "python2.7"

; globalconfig C:\Projekte\sdk\npm\etc\npmrc
production = false

; builtin config undefined

; node bin location = C:\Program Files\nodejs\node.exe
; cwd = C:\Projekte\
; HOME = C:\Users\xxx
; "npm config ls -l" to show all defaults.
```

**Comment by ghost** [comment]
I'm also seeing this issue on npm 5.5.1.

I'm installing a scoped package from a private registry and dev dependencies (all of which are on the public registry) are not being installed. The config for the private registry is specific to my company scope. 

There are no useful logs generated either.

**Comment by rejas** [comment]
still happens with npm v6.0.0 :-(

**Comment by iarna** [comment]
If you're experiencing this then please reach out to `support@npmjs.com` and they can walk you through identifying the problem and fixing it for you.

I'm going to close this, but please be assured that should they need to support can and will involve cli  devs in solving your problem. (And in so doing they manage to isolate a bug then we'll get it fixed!)
