### ISSUE TITLE
feature: add a new type of dependencies called `testingDependencies`

### ISSUE THREAD

**Issue by XGHeaven** [npm/npm#19589]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### Feature

I create a package. I add some testing needed package, suck as mocha/chai. Then I publish it to npm.
When others install my package in development mode, mocha/chai also installed. I don't like this.

So I have a suggestion:

- Add a new type of dependencies called `testingDependencies`, only use for testing packages.
- If user install package from  npm, `testingDependencies` wouldn't install but `devDependencies` would be install.
- if user clone package from github want to do contribute, `npm install` would install `testingDependence` & `devDependencies`

**Comment by kenany** [comment]
> If user install package from npm, `testingDependencies` wouldn't install but `devDependencies` would be install.

Why should dev dependencies be installed when installing a package via the registry? Note that they currently are not, so you're asking for a change in behavior here.

**Comment by XGHeaven** [comment]
Sorry about that. I misunderstand with `npm install`.
I test it again, I found devDependencies don't installed.
