### ISSUE TITLE
npm install -g builds incorrect commands in global command folder using win10

### ISSUE THREAD

**Issue by net8floz** [npm/npm#19595]
#### I'm opening this issue because:
  npm is producing an incorrect install.

#### What's going wrong?
I am using npm node and windows 10.
When calling the command 
```
npm install -g 
```
In my project I end up with the cmd file 
```
"$basedir/node_modules/cryypt/cryypt.js"   "$@"
exit $?
```

This always fails because `$basedir` is not defined so no resolution is met. In all global packages installed via the npm registry the command generated is:

```
#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  "$basedir/node"  "$basedir/node_modules/cryypt/cryypt.js" "$@"
  ret=$?
else 
  node  "$basedir/node_modules/cryypt/cryypt.js" "$@"
  ret=$?
fi
exit $ret
```
Which prepares the $basedir variable. Am I not getting something or is this an issue with npm and windows? This will also happen with any private package I attempt to install globally via
```
npm install -g git+ssh://git@git.web.site:group/repo.git
```

#### How can the CLI team reproduce the problem?
 - Use windows 10 and npm 

```
npm init
```

- Create an index.js and map bin in `package.json`

```
npm install -g 
```

You should now have 

```
"$basedir/node_modules/your-command/your-command.js"   "$@"
exit $?
```

In your global npm command directory like I do. 

### supporting information:

 - `npm -v` prints: `5.6.0`
 - `node -v` prints: `v8.9.4`
 - `npm config get registry` prints: `https://registry.npmjs.org`
 - Windows, OS X/macOS, or Linux?: `Windows`
 - Network issues:

**Comment by Ezekiel-DA** [comment]
I believe you're missing a `#!/usr/bin/env node` as the first line of `cryypt.js`, as per [the last line of the bin section](https://docs.npmjs.com/files/package.json#bin) in the `packgage.json` documentation.

**Comment by net8floz** [comment]
Hey that's fantastic I'll try this out. Thanks for correcting me.
