### ISSUE TITLE
npm ERROR cb() never called!

### ISSUE THREAD

**Issue by sgokahmetoglu** [npm/npm#19602]
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\MSİ\AppData\Roaming\npm-cache\_logs\2018-01-15T10_22_19_162Z-debug.log
2018-01-15T10_22_19_162Z-debug.log

#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints: 5.6.0
 - `node -v` prints: v8.9.4
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by shadyueh** [comment]
How did U solved this? I'm getting same error trying install grunt-browser-sync in a new project.
The versions of node and npm are the same of yours

**Comment by sgokahmetoglu** [comment]
Actually I formatted the computer. After format, I did not get an error.
