### ISSUE TITLE
Can not add cordova plugin to cordova project

### ISSUE THREAD

**Issue by mayurb90** [npm/npm#19615]
#### I'm opening this issue because:

  - [x] npm is doing something I don't understand.
[npm-debug.log](https://github.com/npm/npm/files/1636068/npm-debug.log)
[npm-debug.log](https://github.com/npm/npm/files/1636070/npm-debug.log)

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
Ensure that the `"name"` field in your `C:\toolbox\test\helloall\package.json` is not set to `"com.example.hello"`. Try setting it to something more unique :)

**Comment by mayurb90** [comment]
I am new to it. Could you please explain why is it so?

**Comment by kenany** [comment]
1. `npm` identifies packages by their `"name"`s
2. `npm` does not allow you install a package as a dependency of itself. 

Therefore, you cannot install a package as a dependency of one with the same `"name"`, which is what you are trying to do in those logs you uploaded.

**Comment by mayurb90** [comment]
thanks (y)
