### ISSUE TITLE
Failed:  sudo npm install intern@next

### ISSUE THREAD

**Issue by satacm** [npm/npm#19619]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [X ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Many npn ERR! statements on Install.
Install command ends with:
===================================
npm ERR! TypeError: Object.keys called on non-object
npm ERR!     at Function.keys (native)
npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:708:24)
npm ERR!     at /usr/share/npm/lib/cache.js:638:10
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-37-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "intern@next"
npm ERR! cwd /var/www/html/harviewer02
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type called_on_non_object
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /var/www/html/harviewer02/npm-debug.log
npm ERR! not ok code 0
===================================
#### How can the CLI team reproduce the problem?
sudo apt-get install npm
sudo apt-get install node.js
sudo apt-get install nodejs-legacy
sudo apt-get install ant
sudo apt-get install java-8-openjdk-amd64
sudo apt-get install default-jdk
sudo npm install intern@next

### supporting information:

 - `npm -v` prints: 1.3.10
 - `node -v` prints: v0.10.25
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux - Mint 17.1 Rebecca (Ubuntu: 14.04.5 LTS Trusty Tahr)
 - Network issues:
   - Geographic location where npm was run:
   - [No ] I use a proxy to connect to the npm registry.
   - [No ] I use a proxy to connect to the web.
   - [No ] I use a proxy when downloading Git repos.
   - [No ] I access the npm registry via a VPN
   - [No ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
Your versions of Node.js and `npm` are years old and are no longer supported.
