### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by rahiemb** [npm/npm#19630]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Running npm install -g @angular/cli produces the following error:

### supporting information:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   '@angular/cli@latest' ]
2 info using npm@1.3.21
3 info using node@v7.4.0
4 verbose cache add [ '@angular/cli@latest', null ]
5 verbose cache add name=undefined spec="@angular/cli@latest" args=["@angular/cli@latest",null]
6 verbose parsed url Url {
6 verbose parsed url   protocol: null,
6 verbose parsed url   slashes: null,
6 verbose parsed url   auth: null,
6 verbose parsed url   host: null,
6 verbose parsed url   port: null,
6 verbose parsed url   hostname: null,
6 verbose parsed url   hash: null,
6 verbose parsed url   search: null,
6 verbose parsed url   query: null,
6 verbose parsed url   pathname: '@angular/cli@latest',
6 verbose parsed url   path: '@angular/cli@latest',
6 verbose parsed url   href: '@angular/cli@latest' }
7 verbose cache add name="" spec="angular/cli@latest" args=["","angular/cli@latest"]
8 verbose parsed url Url {
8 verbose parsed url   protocol: null,
8 verbose parsed url   slashes: null,
8 verbose parsed url   auth: null,
8 verbose parsed url   host: null,
8 verbose parsed url   port: null,
8 verbose parsed url   hostname: null,
8 verbose parsed url   hash: null,
8 verbose parsed url   search: null,
8 verbose parsed url   query: null,
8 verbose parsed url   pathname: 'angular/cli@latest',
8 verbose parsed url   path: 'angular/cli@latest',
8 verbose parsed url   href: 'angular/cli@latest' }
9 verbose cache add name="angular/cli" spec="latest" args=["angular/cli","latest"]
10 verbose parsed url Url {
10 verbose parsed url   protocol: null,
10 verbose parsed url   slashes: null,
10 verbose parsed url   auth: null,
10 verbose parsed url   host: null,
10 verbose parsed url   port: null,
10 verbose parsed url   hostname: null,
10 verbose parsed url   hash: null,
10 verbose parsed url   search: null,
10 verbose parsed url   query: null,
10 verbose parsed url   pathname: 'latest',
10 verbose parsed url   path: 'latest',
10 verbose parsed url   href: 'latest' }
11 verbose addNamed [ 'angular/cli', 'latest' ]
12 verbose addNamed [ null, null ]
13 silly lockFile 09a3b3c2-angular-cli-latest angular/cli@latest
14 verbose lock angular/cli@latest C:\Users\rburges6\AppData\Roaming\npm-cache\09a3b3c2-angular-cli-latest.lock
15 info addNameTag [ 'angular/cli', 'latest' ]
16 error TypeError: Cannot convert undefined or null to object
16 error     at Function.keys (<anonymous>)
16 error     at installTargetsError (C:\Program Files\nodejs\node_modules\npm\lib\cache.js:709:24)
16 error     at C:\Program Files\nodejs\node_modules\npm\lib\cache.js:639:10
16 error     at saved (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\get.js:142:7)
16 error     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:133:7
16 error     at FSReqWrap.oncomplete (fs.js:112:15)
17 error If you need help, you may report this *entire* log,
17 error including the npm and node versions, at:
17 error     <http://github.com/isaacs/npm/issues>
18 error System Windows_NT 6.1.7601
19 error command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli@latest"
20 error cwd C:\Users\rburges6\azure\serverless-graphql-blob
21 error node -v v7.4.0
22 error npm -v 1.3.21
23 verbose exit [ 1, true ]

**Comment by kenany** [comment]
Your versions of Node.js and `npm` are no longer supported.
