### ISSUE TITLE
npm resizes terminal screen buffer and does nothing

### ISSUE THREAD

**Issue by DwayneHawkins** [npm/npm#19648]
#### I'm opening this issue because:
Since today, the npm-command does nothing on my Windows 10 64 bit machine.
Well it does resize my terminal to the format of a stamp.

However, running my commands like following example, works:
_node "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" install_

#### What's going wrong?
I type "npm ...." and the terminal (powershell in my case) resets to a 20 x 5 screen buffer and clears the screen.
When I try to do any npm command in Visual Studio Code, the terminal states "_The screen cannot be set to the number of lines and columns specified._" which is normal but confirms the weird behaviour.

### supporting information:
I'm running Windows 10 64bit and have completely uninstalled, reinstalled both the latest (node-v9.4.0-x64) and the LTS (node-v8.9.4-x64) versions of nodejs.
I have scanned for viruses, checked my PATH and even tried in Windows Safe mode.
I can't remember recently installing any software that might have corrupted the default behaviour.

Screenshot: https://i.imgur.com/ELhljVS.jpg
The terminal on the right just executed "npm -v"

**Comment by glynnmccabe** [comment]
I had the same behaviour, caused by some sort of crypto mining malware. Managed to fix using https://www.reddit.com/r/Malware/comments/6y2oob/got_infected_with_some_torrent_miner_undetected/

**Comment by DwayneHawkins** [comment]
Thanks
