### ISSUE TITLE
npm install --production FAILING

### ISSUE THREAD

**Issue by jimmyc2018** [npm/npm#19659]
I'm trying to follow this tutorial: [https://www.installing.in/how-to-install-nodebb-on-ubuntu-14-04/](https://www.installing.in/how-to-install-nodebb-on-ubuntu-14-04/)
I'm stuck close to the end of the tutorial at:
`npm install --production`

Here's what's happening:
```
root@homebase:/var/www/nodebb# ^C
root@homebase:/var/www/nodebb# npm install --production
root@homebase:/var/www/nodebb# npm start
npm ERR! Linux 4.13.0-25-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.11.4
npm ERR! npm  v3.5.2

npm ERR! missing script: start
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/nodebb/npm-debug.log
root@homebase:/var/www/nodebb# ^C
root@homebase:/var/www/nodebb#
```
I'm using DigitalOcean's Droplet service.
Ubuntu 17.10 x64
MEMORY 1 GB
vCPUs 1vCPU
SSD DISK 25 GB
TRANSFER 1 TB

**Comment by kenany** [comment]
Hello! So, the way `npm start` works is that it looks in your current `package.json` for a defined `"start"` [script](https://docs.npmjs.com/misc/scripts), and then runs that. The error message you're seeing is trying to tell you that you have not defined a `"start"` script in your `package.json`, hence `npm start` has no idea what you want it to do.

To solve this issue, all you have to do is add a new script to your `package.json`. It might look something like this, for example:

``` json
{
  "name": "package-name",
  "version": "1.0.0",
  "description": "package description",
  "scripts": {
    "start": "node --version",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {},
  "devDependencies": {}
}
```

Note how this `package.json` has a `"start"` script that runs `node --version`. You'll definitely want to change the command to whatever is most appropriate for your project.

Let me know if you run into any further `npm` issues :)

**Comment by kenany** [comment]
No reply after a few months; closing.
