### ISSUE TITLE
"ERROR" npm install --save-dev

### ISSUE THREAD

**Issue by Shiyinq** [npm/npm#19651]
I try install vue-router via npm install --save-dev. but i got error like this.

> c:\xampp\htdocs\shiyinq\shiyinq>npm install --save-dev vue-router
npm ERR! path c:\xampp\htdocs\shiyinq\shiyinq\node_modules\npm\node_modules\dezalgo
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename 'c:\xampp\htdocs\shiyinq\shiyinq\node_modules\npm\node_modules\dezalgo' -> 
'c:\xampp\htdocs\shiyinq\shiyinq\node_modules\npm\node_modules\.dezalgo.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

This error also happens when i try install vue-router, gulp-sass or whatever.
why i got this error ?

i use:
c:\>npm -v
5.6.0

c:\>node -v
v8.9.1

Thankyou all
~Shiyinq

**Comment by searus** [comment]
I have also started getting this as of this morning.

@Shiyinq, found this, and the downgrade did help me:
[https://stackoverflow.com/questions/48351466/npm-error-enoent-no-such-file-or-directory-dezalgo-delete](https://stackoverflow.com/questions/48351466/npm-error-enoent-no-such-file-or-directory-dezalgo-delete)

**Comment by Shiyinq** [comment]
thanks searus with it also works, but just now I tried it by remove pakage-lock.json and then npm install --save-dev. i'ts work to.  :D
