### ISSUE TITLE
npm@5.6.0 uses credentials instead of auth token for Verdaccio registry

### ISSUE THREAD

**Issue by demurgos** [npm/npm#19652]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

`npm@5.6.0` introduced a regression regarding third-party registries (such as Verdaccio). When trying to authenticate to an existing account, it does not save the `_authToken` in `.npmrc` but the user, email and password.
This regression makes it hard to work with CI that requires an auth token and presents security risks (see #4905 and #9866).
It works with `npm@5.5.1` but this version sometimes crashes on the latest Node version so I had to downgrade to `npm@5.3.0` until this issue is fixed.

**Edit**: To clarify, it works with the npm registry, but it is wrong to break custom registries in a non-major update.

#### How can the CLI team reproduce the problem?

Here is an example execution, lines prefixed by `$` are commands.

```
$ npm install -g verdaccio
/usr/bin/verdaccio -> /usr/lib/node_modules/verdaccio/bin/verdaccio
+ verdaccio@2.7.3
updated 1 package in 25.769s
$ verdaccio &
[1] 31061
warn --- config file  - /home/demurgos/.config/verdaccio/config.yaml
warn --- http address - http://localhost:4873/ - verdaccio/2.7.3
$ npm login --registry http://localhost:4873/
Username: foo
Password: 
Email: (this IS public) foo@example.com
 http <-- 201, user: foo(127.0.0.1), req: 'PUT /-/user/org.couchdb.user:foo', bytes: 119/72
Logged in as foo on http://localhost:4873/.
$ cat ~/.npmrc 
//localhost:4873/:_authToken="yZutHL/T1zMEbBVgitNiag=="
$ npm logout --registry http://localhost:4873/
 http <-- 200, user: foo(127.0.0.1), req: 'DELETE /-/user/token/yZutHL/T1zMEbBVgitNiag==', bytes: 0/25
$ cat ~/.npmrc 
$ npm login --registry http://localhost:4873/
Username: foo
Password: 
Email: (this IS public) foo@example.com
 http <-- 409, user: undefined(127.0.0.1), req: 'PUT /-/user/org.couchdb.user:foo', error: this user already exists
Logged in as foo on http://localhost:4873/.
$ cat ~/.npmrc 
//localhost:4873/:_password=YmFy
//localhost:4873/:username=foo
//localhost:4873/:email=foo@example.com
//localhost:4873/:always-auth=false
```

### supporting information:

 - `npm -v` prints: `5.6.0`
 - `node -v` prints: `v9.4.0`
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?: Linux
 - Network issues: N/A
 - Container: N/A

Ref: https://github.com/verdaccio/verdaccio/issues/509

**Comment by Aftabnack** [comment]
Same issue for me, trying to run `npm-check-updates` fails. Fixed this by adding the `_authToken` line in `.npmrc`. If this is intended breaking change, why wasn't this documented?

**Comment by michaelwalloschke** [comment]
Same here, and I think for a lot of other users of a private registry.
Issue is open since Jan 20...

**Comment by demurgos** [comment]
Seems fixed. I got a token using npm 6.0.1 and verdaccio 2.7.4.
