### ISSUE TITLE
Issue with Cordova plugin installation on Windows XP

### ISSUE THREAD

**Issue by christonenew** [npm/npm#19658]
#### I'm opening this issue because:

  - [X] npm is crashing.
  - [X] npm is producing an incorrect install.
  - [X] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
trying to install cordova on windows xp seems not supported

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by christonenew** [comment]
Hi everyone,

Trying to resign an ipa file I have found myself digging in here and attempting an installation of cordova on windows xp.

Do I have the chance to use my old xp machine and still get further with it ?

Thank you

Attached is the <npm-debug.log> for your review.





[npm-debug.log](https://github.com/npm/npm/files/1649921/npm-debug.log)

**Comment by kenany** [comment]
Your versions of `npm` and Node.js are years old and are no longer supported.
