### ISSUE TITLE
npm start doesn't work

### ISSUE THREAD

**Issue by kezfran** [npm/npm#19668]
#### I'm opening this issue because npm start doesn't work and this what my npm-debug.log says

 0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.10
3 info using node@v6.9.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle casper@2.1.7~prestart: casper@2.1.7
6 silly lifecycle casper@2.1.7~prestart: no script for prestart, continuing
7 info lifecycle casper@2.1.7~start: casper@2.1.7
8 verbose lifecycle casper@2.1.7~start: unsafe-perm in lifecycle true
9 verbose lifecycle casper@2.1.7~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\aow-packaging-3\Downloads\setup\Ghost-1.19.0\content\themes\aow\node_modules\.bin;C:\Users\aow-packaging-3\AppData\Roaming\npm;C:\Program Files\nodejs\;C:\Program Files (x86)\ImageMagick-6.9.7-Q16;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Program Files\nodejs\;C:\Program Files (x86)\Ampps\php;C:\ProgramData\ComposerSetup\bin;C:\Program Files\Git LFS;C:\Ruby24-x64\bin;C:\Users\aow-packaging-3\AppData\Roaming\npm;C:\Users\aow-packaging-3\AppData\Roaming\Composer\vendor\bin;C:\Users\aow-packaging-3\AppData\Local\Microsoft\WindowsApps;";C:\Program Files\Theme Kit\";C:\Program Files\Theme Kit;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;C:\Ruby24-x64\bin;C:\Users\aow-packaging-3\AppData\Roaming\npm;C:\Users\aow-packaging-3\AppData\Roaming\Composer\vendor\bin;C:\Users\aow-packaging-3\AppData\Local\Microsoft\WindowsApps;";C:\Program Files\Theme Kit\";C:\Users\aow-packaging-3\AppData\Local\Gource\cmd
10 verbose lifecycle casper@2.1.7~start: CWD: C:\Users\aow-packaging-3\Downloads\setup\Ghost-1.19.0\content\themes\aow
11 silly lifecycle casper@2.1.7~start: Args: [ '/d /s /c', 'node index.js' ]
12 silly lifecycle casper@2.1.7~start: Returned: code: 1  signal: null
13 info lifecycle casper@2.1.7~start: Failed to exec start script
14 verbose stack Error: casper@2.1.7 start: `node index.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid casper@2.1.7
16 verbose cwd C:\Users\aow-packaging-3\Downloads\setup\Ghost-1.19.0\content\themes\aow
17 error Windows_NT 10.0.16299
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v6.9.4
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error casper@2.1.7 start: `node index.js`
22 error Exit status 1
23 error Failed at the casper@2.1.7 start script 'node index.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the casper package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node index.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs casper
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls casper
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

Thank you!

**Comment by kenany** [comment]
The log indicates that `node index.js` is throwing an error, not `npm` itself. Ensure that `node index.js` executes without error from your command-line.

**Comment by kezfran** [comment]
Thank you @KenanY 
I found that I was running that in a wrong folder.
Thanks
