### ISSUE TITLE
Feature request: Split node_modules into two folders for direct dependencies and indirect dependencies

### ISSUE THREAD

**Issue by kaitlynbrown** [npm/npm#19680]
#### What's the feature?
The node_modules folder should be split into two folders - one for direct dependencies and another for indirect dependencies
#### What problem is the feature intended to solve?
Once a few dependencies have been added to a project, the number of packages contained in node_modules starts growing rather large, due to all of the packages added as indirect dependencies. This can result in a lot of time wasted scrolling through the very long list. If a person ever opens the node_modules folder, it is almost always to look at the code of a direct dependency. Therefore, we should group these into their own folder, and group the indirect dependencies into a separate folder.
#### Is the absence of this feature blocking you or your team? If so, how?
No
#### Is this feature similar to an existing feature in another tool?
No
#### Is this a feature you're prepared to implement, with support from the npm CLI team?
Sure
-->

**Comment by kenany** [comment]
I believe what you're describing would require changes to the Node.js module system, so make sure to open a ticket over at <https://github.com/nodejs/node> first. Do note, however, that the module system is currently marked as "Stable", and will not be changed without a very good reason.

**Comment by kenany** [comment]
Closing since this requires approval from the Node.js team first of all, and also feature requests generally belong in <https://github.com/npm/rfcs> now.
