### ISSUE TITLE
npm install -g npm does not update

### ISSUE THREAD

**Issue by enuggetry** [npm/npm#19692]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
npm i -g npm is not updating npm, but it acts like it updates.

### supporting information:

```
$ npm -v
5.0.3
$ sudo npm i -g npm
/usr/bin/npm -> /usr/lib/node_modules/npm/bin/npm-cli.js
/usr/bin/npx -> /usr/lib/node_modules/npm/bin/npx-cli.js
+ npm@5.6.0
updated 1 package in 12.017s
$ npm -v
5.0.3
```

**Comment by Ionaru** [comment]
What does `which npm` output?

**Comment by enuggetry** [comment]
$which npm
/usr/local/bin/npm

**Comment by Ionaru** [comment]
Because you used `sudo`, the new npm version is at `/usr/bin/npm` instead of `/usr/local/bin/npm`.

You can either make `/usr/local/bin/npm` a link to `/usr/bin/npm`, or try upgrading npm without `sudo`.
