### ISSUE TITLE
npm help missing

### ISSUE THREAD

**Issue by D3M3NTOS** [npm/npm#19709]
:/home/bot# npm shrinkwrap
npm ERR! Linux 3.2.0-4-amd64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "shrinkwrap"
npm ERR! node v0.12.18
npm ERR! npm  v2.15.11

npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! missing: lodash@^4.14.0, required by async@2.6.0
npm ERR! missing: accepts@1.3.3, required by engine.io@3.1.4
npm ERR! missing: base64id@1.0.0, required by engine.io@3.1.4
npm ERR! missing: debug@~2.6.9, required by engine.io@3.1.4
npm ERR! missing: engine.io-parser@~2.1.0, required by engine.io@3.1.4
npm ERR! missing: ws@~3.3.1, required by engine.io@3.1.4
npm ERR! missing: cookie@0.3.1, required by engine.io@3.1.4
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/bot/npm-debug.log

**Comment by D3M3NTOS** [comment]
package.json
{
  "name": "bot",
  "version": "2.15.11",
  "main": "site.js",
  "dependencies": {
    "async": "^2.6.0",
    "engine.io": "^3.1.4",
    "express": "^4.16.2",
    "forever-monitor": "^1.7.1",
    "fs": "^0.0.1-security",
    "log4js": "^2.5.2",
    "mathjs": "^3.20.1",
    "md5": "^2.2.1",
    "mysql": "^2.15.0",
    "node-sass": "^4.7.2",
    "request": "^2.81.0",
    "sha256": "^0.2.0",
    "socket.io": "^2.0.4",
    "steam-totp": "^2.0.1",
    "steam-tradeoffers": "^3.1.0",
    "steamcommunity": "^3.34.1"
  },
  "devDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "description": ""
}

**Comment by kenany** [comment]
Sorry, but your versions of Node.js and `npm` are very old and are no longer supported.

**Comment by D3M3NTOS** [comment]
and how to update them

**Comment by kenany** [comment]
<https://nodejs.org/>, `npm` is included in these releases.

**Comment by D3M3NTOS** [comment]
fu i dont know how can you help ? ... 
my script 
var mysql = require('mysql');
var log4js = require('log4js');
var io = require('socket.io')(8000);
var request = require('request');
var fs = require('fs');
var md5 = require('md5');
var sha256 = require('sha256');
var math = require('mathjs');
var crashNumber = 100;
var crashState = 'NULL';
var crashAt;
var timp = 700;
var intervalul;
var isStatedSet = 0;
var rCAt;
var instaCrash = 0;
var HaShGame;
var timerC1;
var timerC2;
var timerC3;
var timerC4;
var timerC5;
var timerC6;
var timerC7;
var timerC8;
var timerC9;
var timerC10;
var timerC11;
var timerC12;
var CRbr = 1;
var usersCr = {};
var CRusersAmount = {};
var CRcurrentBets = [];

**Comment by D3M3NTOS** [comment]
log4js.configure({
	appenders: [
		{ type: 'console' },
		{ type: 'file', filename: 'logs/site.log' }
	]
});
var logger = log4js.getLogger();

var pool  = mysql.createPool({
	connectionLimit : 10,
	database: 'roulette',
	host: 'localhost',
	user: 'root',
	password: 'password'
});

process.on('uncaughtException', function (err) {
 logger.trace('Strange error');
 logger.debug(err);
});

**Comment by D3M3NTOS** [comment]
very long script

**Comment by D3M3NTOS** [comment]
how instal node.js on vps server and get start mi site.js

**Comment by D3M3NTOS** [comment]
or i need change all ?

**Comment by D3M3NTOS** [comment]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@2.15.11
3 info using node@v0.12.18
4 verbose node symlink /usr/bin/node
5 verbose stack Error: missing script: start
5 verbose stack     at run (/usr/lib/node_modules/npm/lib/run-script.js:142:19)
5 verbose stack     at /usr/lib/node_modules/npm/lib/run-script.js:58:5
5 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:356:5
5 verbose stack     at checkBinReferences_ (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:320:45)
5 verbose stack     at final (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:354:3)
5 verbose stack     at then (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:124:5)
5 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:295:20
5 verbose stack     at /usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
5 verbose stack     at fs.js:263:20
5 verbose stack     at /usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:232:16
6 verbose cwd /home/bot
7 error Linux 3.2.0-4-amd64
8 error argv "/usr/bin/node" "/usr/bin/npm" "start"
9 error node v0.12.18
10 error npm  v2.15.11
11 error missing script: start
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]
this is npm debug

**Comment by D3M3NTOS** [comment]
i use previus 
cd /home/bot
	-npm install mysql
	-npm install log4js
	-npm install socket.io
	-npm install request
	-npm install fs
	-npm install md5
	-npm install sha256
	-npm install mathjs
	-npm install forever-monitor
	-npm install forever -g
	-npm install steamcommunity
	-npm install steam-totp
	-npm install steam-tradeoffers
	-npm install async
	-npm install engine.io
