### ISSUE TITLE
Typo in npm i --help

### ISSUE THREAD

**Issue by guillaumearm** [npm/npm#19702]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?
It's just a typo found when `npm i --help`

How you can see, we have `isntall` instead of `install`

```
npm version : v5.6.0
node version : v9.4.0
```

#### How to reproduce ? 

```
$ npm install --help
npm install (with no args, in package dir)
npm install [<@scope>/]<pkg>
npm install [<@scope>/]<pkg>@<tag>
npm install [<@scope>/]<pkg>@<version>
npm install [<@scope>/]<pkg>@<version range>
npm install <folder>
npm install <tarball file>
npm install <tarball url>
npm install <git:// url>
npm install <github username>/<github project>

aliases: i, isntall, add
common options: [--save-prod|--save-dev|--save-optional] [--save-exact] [--no-save]
```

**Comment by kenany** [comment]
This is intentional. `isntall` is, indeed, an alias for `install`. Just a convenience thing.
