### ISSUE TITLE
Refusing to install <folder> as a dependency of itself

### ISSUE THREAD

**Issue by misschohoh** [npm/npm#19700]
#### I'm opening this issue because:

  - [ X] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.

#### What's going wrong?
I get this error:
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "startbootstrap-agency"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ENOSELF

when I try to install this git (it's a bootstrap site):

npm i startbootstrap-agency

I am just running this locally.

**Comment by kenany** [comment]
Ensure that the `"name"` field in your `package.json` is not set to `"startbootstrap-agency"`. Try setting it to something more unique :)

**Comment by kenany** [comment]
Closing as abandoned.
