### ISSUE TITLE
getting issue in installing AOS in laravel ubuntu

### ISSUE THREAD

**Issue by prajapatim** [npm/npm#19707]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'install', '--save', 'AOS' ]
2 info using npm@3.5.2
3 info using node@v6.11.4
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData AOS
8 silly fetchNamedPackageData AOS
9 silly mapToRegistry name AOS
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/AOS
13 verbose request uri https://registry.npmjs.org/AOS
14 verbose request no auth needed
15 info attempt registry request try #1 at 7:09:26 PM
16 verbose request id e96c9275b0f47739
17 verbose etag "5755bbbf-195"
18 verbose lastModified Mon, 6 Jun 2016 18:06:55 GMT
19 http request GET https://registry.npmjs.org/AOS
20 http 304 https://registry.npmjs.org/AOS
21 verbose headers { date: 'Mon, 29 Jan 2018 13:39:27 GMT',
21 verbose headers   via: '1.1 varnish',
21 verbose headers   'cache-control': 'max-age=300',
21 verbose headers   etag: '"5755bbbf-195"',
21 verbose headers   age: '1912',
21 verbose headers   connection: 'keep-alive',
21 verbose headers   'x-served-by': 'cache-lcy19228-LCY',
21 verbose headers   'x-cache': 'HIT',
21 verbose headers   'x-cache-hits': '1',
21 verbose headers   'x-timer': 'S1517233168.864456,VS0,VE0',
21 verbose headers   vary: 'Accept-Encoding, Accept' }
22 silly get cb [ 304,
22 silly get   { date: 'Mon, 29 Jan 2018 13:39:27 GMT',
22 silly get     via: '1.1 varnish',
22 silly get     'cache-control': 'max-age=300',
22 silly get     etag: '"5755bbbf-195"',
22 silly get     age: '1912',
22 silly get     connection: 'keep-alive',
22 silly get     'x-served-by': 'cache-lcy19228-LCY',
22 silly get     'x-cache': 'HIT',
22 silly get     'x-cache-hits': '1',
22 silly get     'x-timer': 'S1517233168.864456,VS0,VE0',
22 silly get     vary: 'Accept-Encoding, Accept' } ]
23 verbose etag https://registry.npmjs.org/AOS from cache
24 verbose get saving AOS to /home/ubuntu/.npm/registry.npmjs.org/AOS/.cache.json
25 verbose stack TypeError: Cannot convert undefined or null to object
25 verbose stack     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:121:29)
25 verbose stack     at /usr/share/npm/node_modules/iferr/index.js:13:50
25 verbose stack     at /usr/share/npm/lib/utils/pulse-till-done.js:19:8
25 verbose stack     at saved (/usr/share/npm/lib/cache/caching-client.js:168:7)
25 verbose stack     at /usr/share/npm/node_modules/graceful-fs/polyfills.js:210:7
25 verbose stack     at FSReqWrap.oncomplete (fs.js:123:15)
26 verbose cwd /var/www/html/tattoo
27 error Linux 4.13.0-31-generic
28 error argv "/usr/bin/node" "/usr/bin/npm" "install" "--save" "AOS"
29 error node v6.11.4
30 error npm  v3.5.2
31 error Cannot convert undefined or null to object
32 error If you need help, you may report this error at:
32 error     <https://github.com/npm/npm/issues>
33 verbose exit [ 1, true ]

**Comment by kenany** [comment]
Seems like the AOS package must've been unpublished at some point, hence you can no longer install it.

**Comment by prajapatim** [comment]
Hello @KenanY 

Please let me know, what do I next to make it successful?

**Comment by kenany** [comment]
Maybe contact the author of the package and ask them what happened to it?

**Comment by prajapatim** [comment]
ok @KenanY , Thank You
