### ISSUE TITLE
npm install web3 got issue

### ISSUE THREAD

**Issue by cliff0412** [npm/npm#19705]
i am using npm 6.12.3
i am trying to install web3 as below
npm install web3

However, i got below error
npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "web3"
npm ERR! node v6.12.3
npm ERR! npm  v3.10.10
npm ERR! code ENOSELF

npm ERR! Refusing to install web3 as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Devs\test\web3\npm-debug.log

**Comment by kenany** [comment]
Ensure that the `"name"` field in your `package.json` is not set to `"web3"`. Try setting it to something more unique :)

**Comment by slavikf** [comment]
75

**Comment by kenany** [comment]
Closing as abandoned.
