### ISSUE TITLE
Npm fails on npm start

### ISSUE THREAD

**Issue by Atanas9708** [npm/npm#19714]
#### I'm opening this issue because:

  - npm is crashing.

#### What's going wrong?
Npm fails when trying to start any project with npm start
#### How can the CLI team reproduce the problem?

After i updated git to the latest version npm started crashing on the command npm start.
And i do have the start script in my package.json file -> http://prntscr.com/i7nlfw
[2018-01-30T13_12_51_343Z-debug.log](https://github.com/npm/npm/files/1677780/2018-01-30T13_12_51_343Z-debug.log)

### supporting information:

 - `npm -v` prints: 5.6.0
 - `node -v` prints: 9.4.0
 - Windows, OS X/macOS, or Linux?: Windows 10

**Comment by ghost** [comment]
Hi Atanas9708!  found this on SO: 
 "npm start runs whatever the 'start' script config says to run as defined in your 'package.json', node app.js executes the 'app.js' file in 'node'. See http://browsenpm.org/package.json for more info. So if you had the following package.json then the commands are completely different."
Don't you think that trying to do npm start with ''node index.js" could be the problem ?

**Comment by Atanas9708** [comment]
@Prescise Hello!
Yes, simply doing node index.js instead of npm start gets the job done.However, i experience a similiar problem when trying to install the angular-cli. Debug log -> [2018-02-02T10_25_14_540Z-debug.log](https://github.com/npm/npm/files/1689519/2018-02-02T10_25_14_540Z-debug.log)

It looks like npm cannot find Git and cmd.exe in my PATH for some reason.This problem occured when i updated Git to the latest version and i've been struggling with such errors since then.

**Comment by Atanas9708** [comment]
I have these 2 variables C:\WINDOWS\System32\cmd.exe and C:\Program Files\Git\cmd in my PATH.. I don't understand why im getting an ENOENT error .. any ideas ?

**Comment by Atanas9708** [comment]
I finally found a solution that worked for me. I just had to remove all of the values in ComSpec except for %SystemRoot%\system32\cmd.exe

**Comment by ghost** [comment]
Hi Atanas, I'm very sorry I have a new job and didn't have the to find a
solution to your issue. I am very happy you find the solution :) .

bye,

Prescise

2018-02-05 16:59 GMT+01:00 Atanas <notifications@github.com>:
