### ISSUE TITLE
Node Configuration

### ISSUE THREAD

**Issue by Haidar1** [npm/npm#19723]
Hi all, i used to get this error(A complete log of this run can be found in:
npm ERR!     C:\Users\Hydar\AppData\Roaming\npm-cache\_logs\2018-02-01T11_36_20_643Z-debug.log) when ever am installing dependencies how will solve it please

**Comment by kenany** [comment]
@Haidar1 Could you please upload the full debug log to <https://gist.github.com/> and link it here? Thanks!

**Comment by kenany** [comment]
Closing as abandoned.
