### ISSUE TITLE
npm install learnyoureact gives lot of untar errors

### ISSUE THREAD

**Issue by stefanocarniel** [npm/npm#19742]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [X] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
When I try to install learnyoureact I get a long list of errors about untar packages

#### How can the CLI team reproduce the problem?
npm install -g learnyoureact

### supporting information:

 - `npm -v` prints: 2.14.4
 - `node -v` prints: v4.1.2
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux
 - Network issues:
   - Geographic location where npm was run: Italy
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).
   - [X] container on codeanywhere

**Comment by kenany** [comment]
Can you upload the debug log to <https://gist.github.com/> and link it here?

**Comment by kenany** [comment]
Closing as abandoned.
