### ISSUE TITLE
'npm install --no-package-lock' does not use `package-lock.json`

### ISSUE THREAD

**Issue by bradleyayers** [npm/npm#19740]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

The [documentation](https://docs.npmjs.com/cli/install) says `install --no-package-lock` will cause npm to not create a `package-lock.json`:

> The --no-package-lock argument will prevent npm from creating a package-lock.json file.

This makes it seem like a suitable flag to run in CI, however we've found that `--no-package-lock` actually causes npm to **also not use a present `package-lock.json`**.

#### How can the CLI team reproduce the problem?

1. Create a package-lock.json and pin a dependency to not-the-latest version.
2. Run `npm install --no-package-lock`
3. Observe that the latest version of the dependency was used, rather than the pinned version.

### supporting information:

 - `npm -v` prints: 5.3.0
 - `node -v` prints: 8.5.0

### Proposed solution

Update the documentation to clarify the behaviour.

**Comment by kenany** [comment]
<https://docs.npmjs.com/misc/config#package-lock>

> If set to `false`, then ignore `package-lock.json` files when installing.

**Comment by TakahiRoyte** [comment]
I faced the exactly same problem.  The paragraph should mention about the behavior which ignores package-lock.json at npm install, to make things clear.

**Comment by nevercast** [comment]
I believe there should be a different switch for this, or that something needs to be cleared up. While your use case doesn't apply to me, it does conflict with my use case. I use `npm install --no-package-lock` to compare the difference between the pinned and unpinned installs, clearly if --no-package-lock was to still use package-lock.json for the install, that would be mighty confusing for me because of the way I read that switch.

I believe your use case is valid, of course; so having a way to satisfy both would be great. `--no-create-package-lock` ? 

I do wonder if you've already got a package-lock file in your version control, and you're using it, why would you want a flag to not create one?

**Comment by bradleyayers** [comment]
> I do wonder if you've already got a package-lock file in your version control, and you're using it, why would you want a flag to not create one?

This is a good question. In my case I was trying to work around *another* bug in NPM, where it would actually modify an existing `package-lock.json` as a result of running `npm install`. In a CI situation, this is very undesirable, and would cause later commands to fail due to a "dirty workspace" (i.e. modified git-tracked files).

So then I came across this command that "sounded" like what I needed, but ended up being something completely different. If the root problem of NPM modifying `package-lock.json` was fixed, I would have no need for this command.

**Comment by nevercast** [comment]
> So then I came across this command that "sounded" like what I needed, but ended up being something completely different. If the root problem of NPM modifying package-lock.json was fixed, I would have no need for this command.

I agree that does sound like a bug, and it doesn't match the documented functionality.

I'll point you to these:
https://github.com/npm/npm/issues/17979#issuecomment-332701215
https://github.com/npm/npm/issues/18103

Your use case may no longer be valid provided you're using a current version of npm, but someone with a CI process similar to yours will have to validate that claim.

Edit: Tasty treat I found from 17979 is https://github.com/zkat/cipm, I didn't know this existed but I might need to update my build server script ;)

**Comment by legodude17** [comment]
@nevercast You could also do `npm ci` to do the same thing.

@bradleyayers I think `--no-save` would do what you want

**Comment by bradleyayers** [comment]
@legodude17 https://docs.npmjs.com/cli/install describes `--no-save` as:

> --no-save: Prevents saving to dependencies

That doesn't sound related to the issue of whether an existing `package-lock.json` is modified during an `npm install`. Modifying an existing `package-lock.json` by running `npm install` is surely a bug right? Otherwise everyone running `npm install` in a repo should really be running `npm install --no-save` to avoid corrupting `package-lock.json`?

**Comment by joebowbeer** [comment]
I think this use-case is now obsolete. `npm ci` is now the recommended way to install in CI, and it _does_ use the existing package-lock - and nothing else.

I also believe the current behavior of --no-package-lock is correct, though it should be more clearly documented. The --no-package-lock option is the way to install while *ignoring* an existing package-lock.

**Comment by nevercast** [comment]
I agree with @joebowbeer, and per @legodude17's advice we have moved to `npm ci` for our CI. which is the intended way to use npm install on a CI box. `npm install` should absolutely modify package-lock because `npm install` will do tree-shaking which may change the layout of sub-dependencies and these need to be reflected in package-lock correctly.

@bradleyayers Switch to `npm ci` and see how that treats you.

**Comment by bradleyayers** [comment]
Sounds great! I've switched over to yarn for the moment—but I'll probably be back to NPM in the future. Yarn's far from perfect and I've ended up having to work around problems on that side of the fence too. Glad to know about `npm ci`, it should be perfect 💪 for this use-case.
