### ISSUE TITLE
Comments in package.json are overwritten on npm install

### ISSUE THREAD

**Issue by syrnick** [npm/npm#19753]
#### I'm opening this issue because:

  - [ ] npm is producing an incorrect install.

#### What's going wrong?

From https://github.com/npm/npm/issues/4482
```
Yeah, this is not happening. You can always use

{
  "//": "a comment",
  "//": "another comment"
}
```

This works great on node 4.x, but breaks in node 8.x.

npm 5.6.0 arbitrarily removes one of the comments.

### supporting information:
node -v
v8.9.4

npm -v
5.6.0

###

Repro steps:
Create package.json with this content:
```
{
  "name": "npm_bug",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "//": [
      "foo"
    ],
    "//": [
      "bar"
    ]
  }
}
```

run `npm install`

Expected, package.json is unchanged. Actual: 

```
{
  "name": "npm_bug",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "//": [
      "bar"
    ]
  }
}

```

**Comment by kenany** [comment]
What is the output of `npm config get save`? Does this also occur with `npm install --no-save`?

Also, do note that the comments in https://github.com/npm/npm/issues/4482 indicate that you should **not** be adding these sorts of "comments" to your `"dependencies"`.

**Comment by kenany** [comment]
Closing as abandoned.
