### ISSUE TITLE
node-gyp failed to build

### ISSUE THREAD

**Issue by pstingley** [npm/npm#19762]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [X ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
pi@TJBot:~/tjbot/recipes/speech_to_text $ npm install
npm WARN engine tjbot@1.3.0: wanted: {"node":">=4.2.4"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine watson-developer-cloud@2.42.0: wanted: {"node":">=4"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine image-type@3.0.0: wanted: {"node":">=4"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine file-type@4.4.0: wanted: {"node":">=4"} (current: {"node":"0.10.29","npm":"1.4.21"})
\
> sleep@5.1.1 install /home/pi/tjbot/recipes/speech_to_text/node_modules/tjbot/node_modules/sleep
> node-gyp rebuild

make: Entering directory '/home/pi/tjbot/recipes/speech_to_text/node_modules/tjbot/node_modules/sleep/build'
  CXX(target) Release/obj.target/node_sleep/sleep.o
In file included from ../node_modules/nan/nan.h:199:0,
                 from ../sleep.cc:2:
../node_modules/nan/nan_maybe_pre_43_inl.h: In function ‘Nan::Maybe<bool> Nan::DefineOwnProperty(v8::Handle<v8::Object>, v8::Handle<v8::String>, v8::Handle<v8::Value>, v8::PropertyAttribute)’:
../node_modules/nan/nan_maybe_pre_43_inl.h:158:44: warning: suggest parentheses around ‘&&’ within ‘||’ [-Wparentheses]
                  !(current & v8::ReadOnly) &&               // writable AND
                                            ^
In file included from ../sleep.cc:2:0:
../node_modules/nan/nan.h: At global scope:
../node_modules/nan/nan.h:331:47: error: ‘REPLACE_INVALID_UTF8’ is not a member of ‘v8::String’
   static const unsigned kReplaceInvalidUtf8 = v8::String::REPLACE_INVALID_UTF8;
                                               ^
node_sleep.target.mk:82: recipe for target 'Release/obj.target/node_sleep/sleep.o' failed
make: *** [Release/obj.target/node_sleep/sleep.o] Error 1
make: Leaving directory '/home/pi/tjbot/recipes/speech_to_text/node_modules/tjbot/node_modules/sleep/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Linux 4.9.35-v7+
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/pi/tjbot/recipes/speech_to_text/node_modules/tjbot/node_modules/sleep
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm WARN engine request@2.83.0: wanted: {"node":">= 4"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! Error: ENOENT, lstat '/home/pi/tjbot/recipes/speech_to_text/node_modules/tjbot/node_modules/watson-developer-cloud/node_modules/async/find.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.9.35-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/pi/tjbot/recipes/speech_to_text
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! path /home/pi/tjbot/recipes/speech_to_text/node_modules/tjbot/node_modules/watson-developer-cloud/node_modules/async/find.js
npm ERR! fstream_path /home/pi/tjbot/recipes/speech_to_text/node_modules/tjbot/node_modules/watson-developer-cloud/node_modules/async/find.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (evalmachine.<anonymous>:107:15)
npm ERR! Error: ENOENT, lstat '/home/pi/tjbot/recipes/speech_to_text/node_modules/tjbot/node_modules/watson-developer-cloud/node_modules/solr-client/test/search-test.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.9.35-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/pi/tjbot/recipes/speech_to_text
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! path /home/pi/tjbot/recipes/speech_to_text/node_modules/tjbot/node_modules/watson-developer-cloud/node_modules/solr-client/test/search-test.js
npm ERR! fstream_path /home/pi/tjbot/recipes/speech_to_text/node_modules/tjbot/node_modules/watson-developer-cloud/node_modules/solr-client/test/search-test.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (evalmachine.<anonymous>:107:15)
npm ERR! Error: ENOENT, open '/home/pi/tjbot/recipes/speech_to_text/node_modules/tjbot/node_modules/pigpio/node_modules/nan/doc/script.md'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.9.35-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/pi/tjbot/recipes/speech_to_text
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! path /home/pi/tjbot/recipes/speech_to_text/node_modules/tjbot/node_modules/pigpio/node_modules/nan/doc/script.md
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! Error: ENOENT, lstat '/home/pi/tjbot/recipes/speech_to_text/node_modules/tjbot/node_modules/rpi-ws281x-native/node_modules/nan/nan_weak.h'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.9.35-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/pi/tjbot/recipes/speech_to_text
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! path /home/pi/tjbot/recipes/speech_to_text/node_modules/tjbot/node_modules/rpi-ws281x-native/node_modules/nan/nan_weak.h
npm ERR! fstream_path /home/pi/tjbot/recipes/speech_to_text/node_modules/tjbot/node_modules/rpi-ws281x-native/node_modules/nan/nan_weak.h
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (evalmachine.<anonymous>:107:15)
npm ERR! error rolling back Error: ENOTEMPTY, rmdir '/home/pi/tjbot/recipes/speech_to_text/node_modules/tjbot/node_modules/watson-developer-cloud/node_modules'
npm ERR! error rolling back  tjbot@1.3.0 { [Error: ENOTEMPTY, rmdir '/home/pi/tjbot/recipes/speech_to_text/node_modules/tjbot/node_modules/watson-developer-cloud/node_modules']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: '/home/pi/tjbot/recipes/speech_to_text/node_modules/tjbot/node_modules/watson-developer-cloud/node_modules' }
npm ERR! sleep@5.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sleep@5.1.1 install script.
npm ERR! This is most likely a problem with the sleep package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls sleep
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 4.9.35-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/pi/tjbot/recipes/speech_to_text
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! Error: ENOENT, lstat '/home/pi/tjbot/recipes/speech_to_text/node_modules/tjbot/node_modules/asyncawait/node_modules/fibers/bin/win32-x64-48/fibers.node'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.9.35-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/pi/tjbot/recipes/speech_to_text
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! path /home/pi/tjbot/recipes/speech_to_text/node_modules/tjbot/node_modules/asyncawait/node_modules/fibers/bin/win32-x64-48/fibers.node
npm ERR! fstream_path /home/pi/tjbot/recipes/speech_to_text/node_modules/tjbot/node_modules/asyncawait/node_modules/fibers/bin/win32-x64-48/fibers.node
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (evalmachine.<anonymous>:107:15)
npm WARN engine form-data@2.3.1: wanted: {"node":">= 0.12"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine har-validator@5.0.3: wanted: {"node":">=4"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine hawk@6.0.2: wanted: {"node":">=4.5.0"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine yaeti@0.0.6: wanted: {"node":">=0.10.32"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine har-schema@2.0.0: wanted: {"node":">=4"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm ERR! Error: ENOENT, lstat '/home/pi/tjbot/recipes/speech_to_text/node_modules/tjbot/node_modules/asyncawait/node_modules/bluebird/js/browser/bluebird.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.9.35-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/pi/tjbot/recipes/speech_to_text
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! path /home/pi/tjbot/recipes/speech_to_text/node_modules/tjbot/node_modules/asyncawait/node_modules/bluebird/js/browser/bluebird.js
npm ERR! fstream_path /home/pi/tjbot/recipes/speech_to_text/node_modules/tjbot/node_modules/asyncawait/node_modules/bluebird/js/browser/bluebird.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (evalmachine.<anonymous>:107:15)
npm ERR! Error: ENOENT, lstat '/home/pi/tjbot/recipes/speech_to_text/node_modules/tjbot/node_modules/asyncawait/node_modules/lodash/index.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.9.35-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/pi/tjbot/recipes/speech_to_text
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! path /home/pi/tjbot/recipes/speech_to_text/node_modules/tjbot/node_modules/asyncawait/node_modules/lodash/index.js
npm ERR! fstream_path /home/pi/tjbot/recipes/speech_to_text/node_modules/tjbot/node_modules/asyncawait/node_modules/lodash/index.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (evalmachine.<anonymous>:107:15)
npm WARN engine sntp@2.1.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine boom@4.3.1: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine cryptiles@3.1.2: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine hoek@4.2.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine boom@5.2.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm ERR! Error: ENOENT, lstat '/home/pi/tjbot/recipes/speech_to_text/node_modules/tjbot/node_modules/sound-player/test/preview.wav'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.9.35-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/pi/tjbot/recipes/speech_to_text
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! path /home/pi/tjbot/recipes/speech_to_text/node_modules/tjbot/node_modules/sound-player/test/preview.wav
npm ERR! fstream_path /home/pi/tjbot/recipes/speech_to_text/node_modules/tjbot/node_modules/sound-player/test/preview.wav
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (evalmachine.<anonymous>:107:15)
npm WARN engine co@4.6.0: wanted: {"iojs":">= 1.0.0","node":">= 0.12.0"} (current: {"node":"0.10.29","npm":"1.4.21"})
^Cpi@TJBot:~/tjbot/recipes/speech_to_text $ 

### supporting information:

 - `npm -v` prints:1.4.21
 - `node -v` prints: v0.10.29
 - `npm config get registry` prints:https://registry.npmjs.org
 - Windows, OS X/macOS, or Linux?:Debian on Raspberry Pi (TJBot)
 - Network issues:
   - Geographic location where npm was run:Washington DC
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
Sorry, but your versions of Node.js and `npm` are years old and are no longer supported.

**Comment by chris-orchard** [comment]
I'm getting a similar issue with the latest node 9.11.1 and npm 5.6.0. Raised here: https://github.com/nodejs/node-gyp/issues/1413
