### ISSUE TITLE
npm publish fails with "Failed PUT 415" code E415

### ISSUE THREAD

**Issue by RyanCavanaugh** [npm/npm#19764]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Running `npm publish`, attempting to publish `@ryancavanaugh/typescript` produces this:
```
npm ERR! publish Failed PUT 415
npm ERR! code E415
npm ERR! unexpected end of file : @ryancavanaugh/typescript
```
My `package.json` is valid (syntactically, at least?):
```
> node -e "console.log(require('./package.json'))"
{ name: '@ryancavanaugh/typescript',
  author: 'Microsoft Corp.',
  homepage: 'http://typescriptlang.org/',
 ... [more]
```

#### How can the CLI team reproduce the problem?

```
git clone https://github.com/RyanCavanaugh/TypeScript.git
git checkout e1813e9251e7a6b50df51aeac5e8dde6b2
npm publish
```

npm-debug.log: https://gist.github.com/RyanCavanaugh/9711316675b404c9ec42a7d3b9015629
Hot link to my package.json: https://github.com/RyanCavanaugh/TypeScript/blob/projectReferences/package.json

### supporting information:

 - `npm -v` prints: 5.3.0
 - `node -v` prints: v8.2.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows
 - Network issues:
   - Geographic location where npm was run: Redmond, WA
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kuro5hin** [comment]
I'm also having this problem trying to publish a module, using npm 3.10.10, node v6.11.0

**Comment by sebbo2002** [comment]
Having this problem too.
node v8.9.4 and npm 5.6.0.

**Comment by soldair** [comment]
thanks. we think we've identified the issue and are working on the fix.

**Comment by vinz243** [comment]
Idk for other people, it's working now for me !

**Comment by djohns2021** [comment]
+1 to having this issue. Thanks for the quick response!

**Comment by RyanCavanaugh** [comment]
Just retried and it succeeded. Fixed? 🤷‍♂️

**Comment by djohns2021** [comment]
Also retried and got a successful publish ¯\\\_(ツ)\_/¯

**Comment by RyanCavanaugh** [comment]
Perhaps spoke too soon; the published version is not available for install

**Comment by soldair** [comment]
this is all resolved now. publishes should be available also.

there was another issue where some publishes were mistaken for maintainers updates so if you publish the same version again and it doesn't error with "cant publish over previously published version" you'll know you ran into that also.

**Comment by RyanCavanaugh** [comment]
Confirmed working on my end. Thanks for the fast resolution on this!
