### ISSUE TITLE
Installing completion works but shows errors

### ISSUE THREAD

**Issue by drnic** [npm/npm#1976]
I ran the installer command but it showed nasty looking output:

```
$ . <(npm completion)
~/Projects/node_packages/ey_config_nodejs[master*]$ npm ERR! Error: process.stdout cannot be closed
npm ERR!     at Socket.<anonymous> (node.js:284:15)
npm ERR!     at Object.afterWrite [as oncomplete] (net.js:470:10)
npm ERR! Report this *entire* log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
npm ERR! 
npm ERR! System Darwin 11.2.0
npm ERR! command "node" "/usr/local/bin/npm" "completion"
npm ERR! cwd /Users/drnic/Projects/node_packages/ey_config_nodejs
npm ERR! node -v v0.6.6
npm ERR! npm -v 1.1.0-beta-4
npm ERR! message process.stdout cannot be closed
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/drnic/Projects/node_packages/ey_config_nodejs/npm-debug.log
npm not ok
```

But it seems to have worked:

```
~/Projects/node_packages/ey_config_nodejs[master+*]$ npm [TAB] [TAB]
adduser      config       help         link         prefix       rm           star         unlink       
apihelp      deprecate    help-search  list         prune        root         start        unpublish    
author       docs         home         ll           publish      run-script   stop         unstar       
bin          edit         i            ln           r            s            submodule    up           
bugs         explore      info         ls           rb           se           tag          update       
c            faq          init         outdated     rebuild      search       test         version      
cache        find         install      owner        remove       set          un           view         
completion   get          la           pack         restart      show         uninstall    whoami     
```

**Comment by martinheidegger** [comment]
Having that problem with zsh on mac and npm@2.1.18

**Comment by smikes** [comment]
Great - can you gist your .zshrc (or equivalent) so I can try to reproduce?

**Comment by martinheidegger** [comment]
Oh! You don't need that! I just tried to reduce the `.zshrc` file to the minimum that produces the error and it seems like its not related to `zsh` but rather to `oh-my-zsh`. When I remove `oh-my-zsh` then it works seemingly like intended.

**Comment by smikes** [comment]
Thanks.  I note this comment from one of the linked issues on `oh-my-zsh`

> I solved it by adding npm to the PATH before sourcing oh-my-zsh.sh.

That might also help.

**Comment by gonghao** [comment]
I just opened the npm plugin for `oh-my-zsh` in `.zshrc` all seem ok now, but the completion function is so slow.

**Comment by brandon-fryslie** [comment]
Still broken.  Really annoying.

OS X 10.9.5
Node 0.12.1
NPM 2.5.1
zsh 5.0.2
newest oh-my-zsh

**Comment by watilde** [comment]
@brandon-fryslie If you using `oh-my-zsh`, you might can fix it to write this in your `.zshrc`
```
plugins=(npm)
```
Just because `oh-my-zsh`'s default plugin of npm has already had quickfix at here: https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/npm/npm.plugin.zsh#L1

**Comment by camdenb** [comment]
Running the latest versions of Node and zsh and the quick fix worked for me!

**Comment by Hito01** [comment]
I had the same issue. I've updated node and npm to the latest version and I added npm in zsh plugins list and now everything is working like charm.

**Comment by chrisirhc** [comment]
On:
OS X 10.10.3
node v0.10.32
zsh 5.0.5
oh-my-zsh latest master (e44aa50301cbdb9c713193263e6c0c5a9a5798c0) 

`. <(npm completion)` works but enabling plugin doesn't work, neither does `eval "$(npm completion 2>/dev/null)"` in .zshrc.
