### ISSUE TITLE
Unable to install vue-cli

### ISSUE THREAD

**Issue by imzubair10** [npm/npm#19779]
#### I'm opening this issue because:

  - [ ] npm is doing something I don't understand.

#### What's going wrong?
Trying to follow along the steps mentioned in this (https://github.com/vuejs-templates/webpack) to setup my environment for VueJS development but as soon as run the first command to install vue-cli it gives me error  "Cannot use 'in' operator to search for '0' in arguments_marker"

#### How can the CLI team reproduce the problem?
By running the command 

npm install -g vue-cli

**Comment by kenany** [comment]
Can you upload the full debug log to <https://gist.github.com/> and link it here? Thanks!

**Comment by imzubair10** [comment]
https://gist.github.com/imzubair10/662659b0cea7d3849a67ccbc97416aa4

**Comment by kenany** [comment]
Does this also occur with newer versions of Node.js and `npm`?

**Comment by imzubair10** [comment]
Yeah, I installed a new version of node and the problem is gone. Thanks for your help!
I'm curious, Does it mean it's version related problem ??

**Comment by kenany** [comment]
Probably just a bug that was fixed in a newer version.
