### ISSUE TITLE
npm init

### ISSUE THREAD

**Issue by anchal0997** [npm/npm#19793]
#### I'm opening this issue because:

  - npm init is giving error

#### What's going wrong?

let url
^^^
SyntaxError: Unexpected strict mode reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/dist-tags/add.js:6:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
npm ERR! Darwin 17.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4

npm ERR! /usr/local/lib/node_modules/npm/node_modules/npm-registry-client/node_modules/npm-package-arg/npa.js:6
npm ERR! let url
npm ERR! ^^^
npm ERR! Unexpected strict mode reserved word
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

[npm-debug.log](https://github.com/npm/npm/files/1714148/npm-debug.log)

**Comment by bhavyaagg** [comment]
@anchal0997 The npm version you are using is 2.7.4. You should upgrade your npm by running: 
```shell
sudo npm install -g npm
```

Then give it a try.

Also you are using node version 0.12.2. You should upgrade that too.

**Comment by anchal0997** [comment]
This command is giving the same error.
To update node I have used
$ brew update
$ upgrade node

#forMacOS

Still same error is coming. Is there any other way to solve it?

**Comment by bhavyaagg** [comment]
If you have used brew to install node use:
```shell
brew update
brew upgrade node
npm install -g npm
```

Use sudo for global install

**Comment by anchal0997** [comment]
Yeah I have already tried that but I am still getting the same error... :(

**Comment by YasharF** [comment]
What is the output that you get when you just run the following commands?  Can you post them here?
```
brew update
brew upgrade node
npm install -g npm
```

Overall, it appears that somehow you have ended up on an ancient version of NodeJS (0.12) which is in end-of-life and not really supported.  The current LTS (8.9) is bundled with a new npm version as well.

**Comment by anchal0997** [comment]
`/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/node_modules/npm-package-arg/npa.js:6
let url
^^^
SyntaxError: Unexpected strict mode reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/dist-tags/add.js:6:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
npm ERR! Darwin 17.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "npm"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4

npm ERR! /usr/local/lib/node_modules/npm/node_modules/npm-registry-client/node_modules/npm-package-arg/npa.js:6
npm ERR! let url
npm ERR! ^^^
npm ERR! Unexpected strict mode reserved word
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>`

**Comment by YasharF** [comment]
@anchal0997  that looks like the output of `npm init`  The issue is with the other commands causing `npm init` to fail.  What is the output of the following commands?

```
brew update
brew upgrade node
npm install -g npm
```

**Comment by YasharF** [comment]
Do the first two lines give out any outputs?

```
brew update
brew upgrade node
```

**Comment by anchal0997** [comment]
brew update

`Updated 2 taps (heroku/brew, homebrew/core).
==> New Formulae
clblast             dashing             grv                 urdfdom_headers
console_bridge      dynare              openimageio
dartsim             fcl                 urdfdom
==> Updated Formulae
heroku/brew/heroku ✔       jenkins                    questdb
py2cairo ✔                 jmeter                     ripgrep
acmetool                   joplin                     s3-backer
advancecomp                jvm-mon                    sbt@0.13
asciinema                  knot                       scala@2.10
asdf                       kobalt                     sfk
aws-elasticbeanstalk       kops                       skafos
azure-cli                  landscaper                 sonarqube
baresip                    latex2html                 sphinx-doc
bcftools                   leptonica                  sslh
bitrise                    libav                      statik
burp                       libgee                     stk
ccache                     libgtop                    storm
chronograf                 libmpdclient               surfraw
duck                       libxlsxwriter              swiftformat
erlang                     logstalgia                 swiftlint
etcd                       lzlib                      sword
feh                        mame                       systemc
ffmpeg                     memcached                  teleport
fn                         monetdb                    tomee-webprofile
folly                      mpc                        traefik
fuse-zip                   mpd                        twarc
gcovr                      paket                      uwsgi
get-flash-videos           percona-server@5.6         vert.x
ginac                      pgpool-ii                  vim
git-archive-all            picard-tools               wtf
git-fresh                  pilosa                     x3270
gource                     plzip                      yle-dl
gsoap                      postgresql@9.4             youtube-dl
haxe                       pspg
javarepl                   py3cairo`


brew upgrade node
`Error: node 9.5.0 already installed`

**Comment by YasharF** [comment]
OK, it looks like there are two versions of node installed.  An ancient broken 0.12 and the new 9.5.
You can try to uninstall and reinstall NodeJS, or link it.  Instead of node 9.5, I would also recommend trying node 8.9.4 since it is LTS and more stable. You may want to try https://stackoverflow.com/questions/11177954/how-do-i-completely-uninstall-node-js-and-reinstall-from-beginning-mac-os-x to completly remove the existing node installations, and then download 8.9.4 from https://nodejs.org/en/ and install it.  If it doesn't work checkout https://github.com/npm/npm/issues/3125 as it seems to be resolving a similar issue.

**Comment by anchal0997** [comment]
Thanks a lot. It worked..:)
