### ISSUE TITLE
npm ERR! missing script: dist

### ISSUE THREAD

**Issue by Gui-Tora** [npm/npm#19809]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\christopher\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dist' ]
2 info using npm@5.6.0
3 info using node@v8.9.3
4 verbose stack Error: missing script: dist
4 verbose stack     at run (C:\Users\christopher\AppData\Roaming\npm\node_modules\npm\lib\run-script.js:151:19)
4 verbose stack     at C:\Users\christopher\AppData\Roaming\npm\node_modules\npm\lib\run-script.js:61:5
4 verbose stack     at C:\Users\christopher\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:115:5
4 verbose stack     at C:\Users\christopher\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:402:5
4 verbose stack     at checkBinReferences_ (C:\Users\christopher\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:357:45)
4 verbose stack     at final (C:\Users\christopher\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:400:3)
4 verbose stack     at then (C:\Users\christopher\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:160:5)
4 verbose stack     at C:\Users\christopher\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:280:12
4 verbose stack     at C:\Users\christopher\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
5 verbose cwd C:\Users\christopher\Desktop\electron-quick-start-master
6 verbose Windows_NT 10.0.16299
7 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\christopher\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "dist"
8 verbose node v8.9.3
9 verbose npm  v5.6.0
10 error missing script: dist
11 verbose exit [ 1, true ]

**Comment by kenany** [comment]
@mctora Do you have a `"dist"` script defined in your `package.json`?

**Comment by Gui-Tora** [comment]
NO BUT THE NPM HELP ME BUT NOW I HAVE ANOTHER ERROR

**Comment by kenany** [comment]
What's the new error?

**Comment by Gui-Tora** [comment]
My new error is this:
![is mi new error](https://user-images.githubusercontent.com/32785124/36649092-2c4ebe30-1a79-11e8-8e68-793d104da674.png)

**Comment by kenany** [comment]
Try not typing the dollar sign `$`.

**Comment by Gui-Tora** [comment]
I've already tried it and it works, thank.
It was a silly mistake

**Comment by kenany** [comment]
Closing as resolved then.
