### ISSUE TITLE
Laravel script "npm run dev" errors

### ISSUE THREAD

**Issue by megusta420** [npm/npm#19810]
Hi all.
My stack is:

npm -v 1.3.10
node -v v9.4.0
Laravel 5.6
Vagrant (Ubuntu)

Trying to run "npm run dev" or "sudo npm run dev" on package.json and that happened:

![image](https://user-images.githubusercontent.com/28196153/36112010-d4306b06-1030-11e8-94d5-354c7e2e2473.png)

Here is the content of package.json:

![image](https://user-images.githubusercontent.com/28196153/36112028-e5fa3fd8-1030-11e8-8337-d86cb97d9aed.png)

I've changed from original "cross-env NODE_ENV=development ETC" because "npm install -g cross-env" or "yarn add -g cross-env" did not installed cross-env as global package/alias.

**Comment by kenany** [comment]
Sorry, but your version of `npm` is years old and is no longer supported.

**Comment by kenany** [comment]
Does `node -v` and `nodejs -v` print different things, by the way?
