### ISSUE TITLE
shasum check failed for C:\Users\PHARHEEZ\AppData\Local\Temp\npm-15592-605c8c23\registry.npmjs.org\_40angular\core\-\core-5.2.4.tgz

### ISSUE THREAD

**Issue by phaheez** [npm/npm#19816]
npm install
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\PHARHEEZ\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.10.1
npm ERR! npm  v3.9.5

npm ERR! shasum check failed for C:\Users\PHARHEEZ\AppData\Local\Temp\npm-15592-605c8c23\registry.npmjs.org\_40angular\core\-\core-5.2.4.tgz
npm ERR! Expected: 44a59bcea87b3aac9ce8ff2ff674fe9cb60e2041
npm ERR! Actual:   4f5fba1f8d9a35b11b75fde2369ba553c03ed914
npm ERR! From:     https://registry.npmjs.org/@angular/core/-/core-5.2.4.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\PHARHEEZ\Documents\Angular4\angularfirebase\npm-debug.log

[npm-debug.log](https://github.com/npm/npm/files/1720649/npm-debug.log)

**Comment by phaheez** [comment]
I got this error when I do "npm install". Please help me out.

**Comment by shortthirdman** [comment]
Facing the same problem since the last couple days. @phaheez Have you got some workaround?

**Comment by phaheez** [comment]
@shortthirdman No! Still battling with it. Any geek in the house should kindly help because I can't go further anymore. Thanks

**Comment by shortthirdman** [comment]
Hi @phaheez It has been up and running the NPMJS Registry server

**Comment by phaheez** [comment]
How do you got it running? What is the way forward?

**Comment by phaheez** [comment]
@shortthirdman how do you got it running?

**Comment by shortthirdman** [comment]
@phaheez 
The npmjs registry server had some issues for some reasons. Now its well and good

**Comment by shortthirdman** [comment]
@phaheez You can try by hitting npm install on your project root

**Comment by phaheez** [comment]
Thank you @shortthirdman

**Comment by shortthirdman** [comment]
@phaheez  If your problem has been solved, then you can close this IR

**Comment by phaheez** [comment]
Just got it running by installing all the dependency one by one
