### ISSUE TITLE
npm run start fails with port already in use, when it isnt so.

### ISSUE THREAD

**Issue by gauravojha** [npm/npm#19844]
Hi,

I created an ExpessJS App using the skeleton from http://expressjs.com. The first time I ran the app it ran fine. But all subsequent runs keep on giving me the error below that the port 3000 is already in use.I checked and there are no processes on 3000. I am using a Mac for this. Can someone help in determining the cause and solving it. I can simply run it on a different port, but what if that port is blocked as well.  If you need more info, let me know

```
> node ./bin/www

Listening on port 3000
Port 3000 is already in use
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gather@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gather@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by gauravojha** [comment]
Just an update. The same app runs fine with `node app.js`

**Comment by kenany** [comment]
I suggest taking this to a site like StackOverflow, since this issue tracker is for `npm`-specific bugs and feature requests.
