### ISSUE TITLE
can't install electron from npm

### ISSUE THREAD

**Issue by linkinbird** [npm/npm#19853]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [* ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
`npm install electron`
return error

#### How can the CLI team reproduce the problem?

`yum install nodejs npm`
`npm install -g electron`
[root@li497-222 /]# npm install electron
npm http GET https://registry.npmjs.org/electron
npm http 304 https://registry.npmjs.org/electron
npm http GET https://registry.npmjs.org/electron-download
npm http GET https://registry.npmjs.org/extract-zip
npm http GET https://registry.npmjs.org/types/node
npm http 304 https://registry.npmjs.org/electron-download
npm http 304 https://registry.npmjs.org/extract-zip
npm http 404 https://registry.npmjs.org/types/node
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/usr/lib/node_modules/npm/lib/cache.js:687:35)
npm ERR!     at /usr/lib/node_modules/npm/lib/cache.js:675:5
npm ERR!     at saved (/usr/lib/node_modules/npm-registry-client/lib/get.js:148:7)
npm ERR!     at /usr/lib/node_modules/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:108:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.14.17-x86_64-linode99
npm ERR! command "node" "/usr/bin/npm" "install" "electron"
npm ERR! cwd /
npm ERR! node -v v0.10.48
npm ERR! npm -v 1.3.6
npm ERR! type non_object_property_load
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /npm-debug.log
npm ERR! not ok code 0

### supporting information:

 - `npm -v` prints: v0.10.48
 - `node -v` prints: 1.3.6
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: linux
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
Sorry, your versions of Node.js and `npm` are years old and are no longer supported.

**Comment by linkinbird** [comment]
nodejs and npm are installed by yum, i also tried wget bin code from official site of node, they all print the same version infor.
There must be somerhing wrong

**Comment by kenany** [comment]
Neither of those are maintained by the npm team so there's nothing we can do here.
