### ISSUE TITLE
Using --package-lock-only in directory with existing package-lock.json produces incorrect result

### ISSUE THREAD

**Issue by sarunint** [npm/npm#19852]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

`package-lock.json` is generated differently when install using `--package-lock-only`

#### How can the CLI team reproduce the problem?

Look at [this gist](https://gist.github.com/sarunint/7ab65b95dda1a1cd65df016c5dbf8e02). There are 3 files.

`package-lock.168then170.json` is generated by:

1. `npm init` in an empty folder.
2. `npm install @angular/cli@1.6.8 --package-lock-only`
3. `npm install @angular/cli@1.7.0 --package-lock-only`

During the second installation, there should be warning messages about peerDependencies.

`package-lock.170direct.json` is generated by:

1. `npm init` in an empty folder.
2. `npm install @angular/cli@1.7.0 --package-lock-only`

During the installation, there should be **no** warning messages about peerDependencies.

You'll see that the package-lock.json files generated are different.

This is discover because [renovateapp/renovate](https://github.com/renovateapp/renovate) is updating my `package-lock.json` incorrectly.

### supporting information:

 - `npm -v` prints: 5.6.0
 - `node -v` prints: v8.9.3
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Ubuntu on Windows through WSL (that should be considered as Linux, right?)
 - Network issues:
   - Geographic location where npm was run: Thailand
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by sarunint** [comment]
Duplicate of #17004 and #18904

**Comment by rarkins** [comment]
I have reproduced this problem. Further I can confirm that all of these three approaches produce the same lock file:
```
npm init -y && npm install @angular/cli@1.7.0 --package-lock-only
npm init -y && npm install @angular/cli@1.7.0
npm init -y && npm install @angular/cli@1.6.8 && npm install @angular/cli@1.7.0
```

While this one produces a different - perhaps incorrect - lock file:
```
npm init -y && npm install @angular/cli@1.6.8 --package-lock-only && npm install @angular/cli@1.7.0 --package-lock-only
```

You also get the "wrong" lock file if you first install 1.6.8, then manually edit the `package.json` to contain `1.7.0`, and then run `npm install --package-lock-only`

**Comment by rarkins** [comment]
I would suggest renaming this to be "Using --package-lock-only in directory with existing package-lock.json produces incorrect result"

**Comment by rarkins** [comment]
Cc @alopezsanchez @iarna

**Comment by rarkins** [comment]
Fixed in https://github.com/npm/npm/commit/6954dfc192f88ac263f1fcc66cf820a21f4379f1 (npm@5.7.0)
