### ISSUE TITLE
Feature: npm exec like bundle exec

### ISSUE THREAD

**Issue by mcandre** [npm/npm#19865]
#### What's the feature?

`npm exec` like `bundle exec`, to run shell commands with `npm bin` added to `$PATH`, in a roughly platform-agnostic fashion.

#### What problem is the feature intended to solve?

Many Node.js users are unsure how to invoke Node.js developer tools installed on a per-project basis. `PATH="$PATH:$(npm bin)" <command>` kind of does this, but only for POSIX environments. Command Prompt and PowerShell users would require some different code, and anyway, manually managing this is a pain, whereas this behavior would be better suited to automation by tool.

#### Is the absence of this feature blocking you or your team? If so, how?

It's a pain configuring Gruntfile.js to point at the relative path to tools like JSHint, especially when these paths require different separators depending on build platform.

#### Is this feature similar to an existing feature in another tool?

https://github.com/grncdr/npm-exec

**Comment by Joezo** [comment]
From `npm@5.2.0` onwards, `npx` is installed alongside `npm`. Usage of `npx` is as you described, you can read more about it here.

https://medium.com/@maybekatz/introducing-npx-an-npm-package-runner-55f7d4bd282b

**Comment by kenany** [comment]
@mcandre Seems like you requested this nearly 3 years ago in https://github.com/npm/npm/issues/7429. I'm gonna close this one for the same reason as that one; and also yeah, `npx` may be more-or-less what you're looking for anyways.
