### ISSUE TITLE
Please Help

### ISSUE THREAD

**Issue by Patrick-Elvis** [npm/npm#19869]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

c:\Users\patrick elvis mugo\source\repos\Keja\Keja> cmd.exe /c npm run ionic:build --color=always
> io.cordova.myapp407881@ ionic:build c:\Users\patrick elvis mugo\source\repos\Keja\Keja
'ionic-app-scripts' is not recognized as an internal or external command,
> ionic-app-scripts build
operable program or batch file.
npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Web\\External\\Node.exe" "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Web\\External\\node_modules\\npm\\bin\\npm-cli.js" "run" "ionic:build" "--color=always"
npm ERR! node v5.4.1
npm ERR! npm  v3.3.4
npm ERR! code ELIFECYCLE
npm ERR! io.cordova.myapp407881@ ionic:build: `ionic-app-scripts build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the io.cordova.myapp407881@ ionic:build script 'ionic-app-scripts build'.
npm ERR! This is most likely a problem with the io.cordova.myapp407881 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts build
npm ERR! You can get their info via:
npm ERR!     npm owner ls io.cordova.myapp407881
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\Users\patrick elvis mugo\source\repos\Keja\Keja\npm-debug.log
Process terminated with code 1.

**Comment by legodude17** [comment]
> This is most likely a problem with the io.cordova.myapp407881 package, not with npm itself.

**Comment by kenany** [comment]
I think what you want is:

```
npm install @ionic/app-scripts@latest --save-dev
```

**Comment by Patrick-Elvis** [comment]
I should try start another project ?

**Comment by kenany** [comment]
That is not necessary.

**Comment by Patrick-Elvis** [comment]
How do I fix that ?

**Comment by kenany** [comment]
Did you try the command I posted above?

**Comment by Patrick-Elvis** [comment]
I'll try it out in the morning..
Will get back to you thanks

On Feb 21, 2018 00:17, "Kenan Yildirim" <notifications@github.com> wrote:

Did you try the command I posted above?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/npm/npm/issues/19869#issuecomment-367122155>, or mute
the thread

**Comment by kenany** [comment]
Closing as abandoned.
