### ISSUE TITLE
Bring back nomnom 🙏

### ISSUE THREAD

**Issue by astorije** [npm/npm#19875]
https://www.npmjs.com/package/nomnom has been deprecated, while hundreds of packages rely on it. I have noticed this because https://www.npmjs.com/package/jsonlint is now broken (see https://github.com/zaach/jsonlint/issues/103, https://github.com/zaach/jsonlint/pull/105) and since the package is not actively maintained, it is bound to be broken forever.

`nomnom` is downloaded [between 30k times per day during weekends and 150k times per day during weekdays](https://npm-stat.com/charts.html?package=nomnom), so it's very likely a lot of projects are suffering from this.

FYI, I have [pinged you on Twitter](https://twitter.com/astorije/status/965460128446205953) before opening an issue on the repo.

**Comment by kenany** [comment]
Perhaps this should be moved to <https://github.com/npm/registry>?

**Comment by j-brown** [comment]
I find this curious, as nomnom is #365 on the top 1000 most depended upon packages: https://gist.github.com/anvaka/8e8fa57c7ee1350e3491

Was nomnom owned/maintained by npm?

**Comment by ehsalazar** [comment]
👋 https://github.com/zaach/jsonlint/issues/103#issuecomment-367416531

**Comment by astorije** [comment]
Thanks for taking action, @ehsalazar!
