### ISSUE TITLE
504 Gateway Time-out on NPM Publish

### ISSUE THREAD

**Issue by keithwhor** [npm/npm#19871]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Receiving 504 Gateway Time-out on attempt to publish

#### How can the CLI team reproduce the problem?

`npm publish`

```
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! publish Failed PUT 504
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "publish"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10

npm ERR! Unexpected token < in JSON at position 0
npm ERR! <html><body><h1>504 Gateway Time-out</h1>
npm ERR! The server didn't respond in time.
npm ERR! </body></html>
npm ERR! 
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

### supporting information:

 - `npm -v` prints: `3.10.10`
 - `node -v` prints: `6.11.1`
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?: `OS X`
 - Network issues: `None`

**Comment by lcherone** [comment]
+1 same issue, also sometimes its showing failed but its actually pushing :/

npm -v prints: `5.6.0`
node -v prints: `v8.9.4`
Windows, OS X/macOS, or Linux?: `Linux`

**Comment by lcherone** [comment]
Seems fixed now, just a glitch in the matrix.

**Comment by keithwhor** [comment]
Yep, fixed on my end too.

**Comment by ianni67** [comment]
I'm facing the same issue right now... :-(

**Comment by sballesteros** [comment]
Same issue as well (npm 5.6.0, node v8.9.4)

**Comment by jeffrichiefs** [comment]
Same here.

**Comment by jeffrichiefs** [comment]
For anyone finding this on le Googels, `rm package-lock.json && npm i` fixed this for me.

**Comment by jeffrichie** [comment]
Still same issue - ideas?

**Comment by Butterfly** [comment]
I tried a quick search out on the Net. "Lifewire" [describes 504 Gateway Timeout](https://www.lifewire.com/504-gateway-timeout-error-explained-2622941) as "an HTTP status code that means that one server did not receive a timely response from another server that it was accessing while attempting to load the web page or fill another request by the browser".

That could be interpreted to mean our terminals (in place of browsers), too.

Slashdot additionally just ran ["GitHub Survived the Biggest DDoS Attack Ever Recorded"](https://it.slashdot.org/story/18/03/04/1845219/github-survived-the-biggest-ddos-attack-ever-recorded) which could easily explain intermittent issues with making the necessary timely connections...

And of course and as always.... *or not* :smile:
