### ISSUE TITLE
ayuda porfavor! la pantalla tiembla! |  please help! the screen shakes!

### ISSUE THREAD

**Issue by FrancoBM12** [npm/npm#19886]
estaba habriendo el servidor por primera vez y la pantalla del juego comenzo a temblar ayuda porfavor! :disappointed:

**Comment by xFrancoBM** [comment]
![image](https://user-images.githubusercontent.com/36641683/36525050-5ed78e64-1776-11e8-87b5-0768fd373dc7.png)

**Comment by diestrin** [comment]
Abriendo* 
WTF dude?

**Comment by danazkari** [comment]
`s/habriendo/abriendo/g`

**Comment by Osuka42g** [comment]
`bugfix/shake-screen-on-hopen`

**Comment by mferranti** [comment]
i have the same issue (?)
