### ISSUE TITLE
Error: functions predeploy error: Command terminated with non-zero exit code1

### ISSUE THREAD

**Issue by Japheth-Mwongela** [npm/npm#19896]
<----------------------I'm trying to deploy firebase but  I'm getting the error ----------------------->

npm ERR! missing script: build

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Mwongela\AppData\Roaming\npm-cache\_logs\2018-02-23T08_21_43_370Z-debug.log

Error: functions predeploy error: Command terminated with non-zero exit code1

<---------------------------- Here is my index.js file ---------------------------------->

'use strict'

const functions = require('firebase-functions');
const admin = require('firebase-admin');
admin.initializeApp(functions.config().firebase);

exports.sendNotification = functions.database.ref('/notifications/{user_id}/{notification_id}').onWrite(event => {

		const  user_id = event.params.user_id;
	const notification_id = event.params.notification_id;

	console.log('The User id is: ', user_id);
});

<--------------------------------and my firebase.json file is -------------------------------------->

{
  "functions": {
    "predeploy": [
      "npm --prefix ./functions/ run lint",
      "npm --prefix ./functions/ run build"
    ]
  }
}

**Comment by kenany** [comment]
```
npm ERR! missing script: build
```

Do you have a `"build"` script defined in your `package.json`?

**Comment by Japheth-Mwongela** [comment]
<-------------------------- this is my package.json file --------------------------------->

  "name": "functions",
  "description": "Cloud Functions for Firebase",
  "scripts": {
    "lint": "./node_modules/.bin/eslint .",
    "serve": "firebase serve --only functions",
    "shell": "firebase experimental:functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "dependencies": {
    "firebase-admin": "~5.8.1",
    "firebase-functions": "^0.8.1"
  },
  "devDependencies": {
    "eslint": "^4.12.0",
    "eslint-plugin-promise": "^3.6.0"
  },
  "private": true
}

**Comment by kenany** [comment]
All right, so you see how you have scripts like `"lint"`, `"serve"`, `"shell"`, etc. in your `package.json`? You need to add one named `"build"`. Otherwise, how would `npm` know what you want it to build? 😄
