### ISSUE TITLE
Executing "heroku local web", npm install error occured

### ISSUE THREAD

**Issue by knittkg** [npm/npm#19925]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [*] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Executing "heroku local web", npm install error occured

#### How can the CLI team reproduce the problem?
$ heroku local web
 ▸    heroku-cli: update available from 6.14.39-addc925 to 6.15.26-5726b6f
[OKAY] Loaded ENV .env File as KEY=VALUE Format
[WARN] ENOENT: no such file or directory, open 'Procfile'
[OKAY] package.json file found - trying 'npm start'
03:39:19 web.1   |  npm
03:39:20 web.1   |   ERR! Linux 4.9.80-c9
03:39:20 web.1   |  npm ERR! argv "/home/ubuntu/.nvm/versions/node/v6.11.2/bin/node" "/home/ubuntu/.nvm/versions/node/v6.11.2/bin/npm" "start"
03:39:20 web.1   |  npm ERR! node v6.11.2
03:39:20 web.1   |  npm ERR! npm  v3.10.10
03:39:20 web.1   |  npm ERR! missing script: start
03:39:20 web.1   |  npm ERR! 
03:39:20 web.1   |  npm ERR! If you need help, you may report this error at:
03:39:20 web.1   |  npm ERR!     <https://github.com/npm/npm/issues>
03:39:20 web.1   |  npm ERR! Please include the following file with any support request:
03:39:20 web.1   |  npm ERR!     /home/ubuntu/workspace/audio_uploader_test_app/npm-debug.log
03:39:20 web.1   Exited with exit code 1
$ 

0 info it worked if it ends with ok
1 verbose cli [ '/home/ubuntu/.nvm/versions/node/v6.11.2/bin/node',
1 verbose cli   '/home/ubuntu/.nvm/versions/node/v6.11.2/bin/npm',
1 verbose cli   'start' ]
2 info using npm@3.10.10
3 info using node@v6.11.2
4 verbose stack Error: missing script: start
4 verbose stack     at run (/home/ubuntu/.nvm/versions/node/v6.11.2/lib/node_modules/npm/lib/run-script.js:151:19)
4 verbose stack     at /home/ubuntu/.nvm/versions/node/v6.11.2/lib/node_modules/npm/lib/run-script.js:61:5
4 verbose stack     at /home/ubuntu/.nvm/versions/node/v6.11.2/lib/node_modules/npm/node_modules/read-package-json/read-json.js:356:5
4 verbose stack     at checkBinReferences_ (/home/ubuntu/.nvm/versions/node/v6.11.2/lib/node_modules/npm/node_modules/read-package-json/read-json.js:320:45)
4 verbose stack     at final (/home/ubuntu/.nvm/versions/node/v6.11.2/lib/node_modules/npm/node_modules/read-package-json/read-json.js:354:3)
4 verbose stack     at then (/home/ubuntu/.nvm/versions/node/v6.11.2/lib/node_modules/npm/node_modules/read-package-json/read-json.js:124:5)
4 verbose stack     at /home/ubuntu/.nvm/versions/node/v6.11.2/lib/node_modules/npm/node_modules/read-package-json/read-json.js:243:12
4 verbose stack     at /home/ubuntu/.nvm/versions/node/v6.11.2/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
4 verbose stack     at tryToString (fs.js:456:3)
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:443:12)
5 verbose cwd /home/ubuntu/workspace/audio_uploader_test_app
6 error Linux 4.9.80-c9
7 error argv "/home/ubuntu/.nvm/versions/node/v6.11.2/bin/node" "/home/ubuntu/.nvm/versions/node/v6.11.2/bin/npm" "start"
8 error node v6.11.2
9 error npm  v3.10.10
10 error missing script: start
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

### supporting information:

 - `npm -v` prints:
3.10.10
 - `node -v` prints:
v6.11.2
 - `npm config get registry` prints:
https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?:
Linux
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [*] I deploy to a PaaS (Heroku).

**Comment by kenany** [comment]
Hello! So, the way `npm start` works is that it looks in your current `package.json` for a defined `"start"` [script](https://docs.npmjs.com/misc/scripts), and then runs that. The error message you're seeing is trying to tell you that you have not defined a `"start"` script in your `package.json`, hence `npm start` has no idea what you want it to do.

To solve this issue, all you have to do is add a new script to your `package.json`. It might look something like this, for example:

``` json
{
  "name": "package-name",
  "version": "1.0.0",
  "description": "package description",
  "scripts": {
    "start": "node --version",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {},
  "devDependencies": {}
}
```

Note how this `package.json` has a `"start"` script that runs `node --version`. You'll definitely want to change the command to whatever is most appropriate for your project.

Let me know if you run into any further `npm` issues :)

**Comment by kenany** [comment]
Closing as abandoned.
