### ISSUE TITLE
Error while cloning after installing Git

### ISSUE THREAD

**Issue by nandakik** [npm/npm#19939]
After installing git i executed the below command in git console
git clone git://github.com/DevExpress/AjaxControlToolkit.git

I am getting below error 

fatal: unable to connect to github.com:
github.com[0: 192.30.253.113]: errno=No error
github.com[1: 192.30.253.112]: errno=No error
![github](https://user-images.githubusercontent.com/36693768/36783554-6f3832e6-1ca2-11e8-978e-e3085f0bcbcd.jpg)

Please find the attached screenshot

**Comment by pbalan** [comment]
@nandakik Looks like you have network issue. Can you try open Github through browser? as the message says **unable to connect to github.com**

**Comment by kenany** [comment]
This does not seem to be an issue with `npm` itself.
