### ISSUE TITLE
missing script: start

### ISSUE THREAD

**Issue by jkishoreraj** [npm/npm#19938]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start', 'app.js' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 verbose stack Error: missing script: start
4 verbose stack     at run (/usr/share/npm/lib/run-script.js:147:19)
4 verbose stack     at /usr/share/npm/lib/run-script.js:57:5
4 verbose stack     at /usr/share/npm/node_modules/read-package-json/read-json.js:345:5
4 verbose stack     at checkBinReferences_ (/usr/share/npm/node_modules/read-package-json/read-json.js:309:45)
4 verbose stack     at final (/usr/share/npm/node_modules/read-package-json/read-json.js:343:3)
4 verbose stack     at then (/usr/share/npm/node_modules/read-package-json/read-json.js:113:5)
4 verbose stack     at ReadFileContext.<anonymous> (/usr/share/npm/node_modules/read-package-json/read-json.js:284:20)
4 verbose stack     at ReadFileContext.callback (/usr/share/npm/node_modules/graceful-fs/graceful-fs.js:76:16)
4 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:303:13)
5 verbose cwd /home/kishoreraj/chat
6 error Linux 4.13.0-36-generic
7 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start" "app.js"
8 error node v4.2.6
9 error npm  v3.5.2
10 error missing script: start
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

**Comment by vamshi9666** [comment]
can you be a bit more specific

**Comment by jkishoreraj** [comment]
When I try run my app using npm start this error is coming

**Comment by kenany** [comment]
I think what you're looking for is

```
node app.js
```

**Comment by jkishoreraj** [comment]
This is working fine. But npm start of project gives me this error. Any
idea why ?

**Comment by kenany** [comment]
You need to make sure you have a `"start"` script defined in your `package.json`. Here is an example of what it could look like:

``` json
{
  "name": "package-name",
  "version": "1.0.0",
  "description": "package description",
  "scripts": {
    "start": "node app.js"
  },
  "dependencies": {},
  "devDependencies": {}
}
```

**Comment by jkishoreraj** [comment]
Thank you, Its working fine now




*Regards,*
*Kishoreraj*

**Comment by kenany** [comment]
Closing as resolved.
