### ISSUE TITLE
Unable to Download the Version for com.unarin.cordova.beacon@3.4.1

### ISSUE THREAD

**Issue by GMathew27Feb** [npm/npm#19935]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ X] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I have been trying to install the beacon package but unable to get it installed
#### How can the CLI team reproduce the problem?
cordova plugin add https://github.com/petermetz/cordova-plugin-ibeacon.git
Cordova Version 8.0.0

### supporting information:
npm ERR! node v5.4.1
npm ERR! npm  v3.3.4
npm ERR! No compatible version found: com.unarin.cordova.beacon@3.4.1

- Windows, OS X/macOS, or Linux?:
Windows 10

#### Is this a feature you're prepared to implement, with support from the npm CLI team?

-->

**Comment by kenany** [comment]
Does this also occur with newer versions of `npm`, like v4 or v5?

**Comment by kenany** [comment]
Closing as abandoned.
