### ISSUE TITLE
Ng build issue

### ISSUE THREAD

**Issue by prasannabachu** [npm/npm#19930]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

===> missing script: ng

**Comment by kenany** [comment]
@prasannabachu Do you have a `"ng"` script defined in your `package.json`?

**Comment by prasannabachu** [comment]
No it is not defined

**Comment by kenany** [comment]
Make sure to define one before running `npm run ng`, otherwise `npm` has no idea what you want it to do. Will look something like

```json
{
  "scripts": {
    "ng": "your desired command here"
  }
}
```

**Comment by prasannabachu** [comment]
PS E:\new_angular2\quickstart-master> npm run ng build --prod
npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\
bin\\npm-cli.js" "run" "ng" "build" "--prod"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10

npm ERR! missing script: ng
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     E:\new_angular2\quickstart-master\npm-debug


getting error like this

**Comment by kenany** [comment]
Can I see your `package.json`?
