### ISSUE TITLE
npm 5.7.1-packed tarballs can no longer be explored in 7-Zip

### ISSUE THREAD

**Issue by simonua** [npm/npm#19933]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Tarballs packed with npm 5.7.1 can no longer be explored with tools such as 7-Zip. The previous 5.6.0 had no issues. I experience this with Windows 7. WinZip, however, will open this appropriately.

I am logging the error here simply because npm 5.7.x is symptomatic, but the problem probably lies in the underlying _tar_ package or its dependencies that were updated for the 5.7.0 release. I'll be glad to open an issue there if this could be confirmed. 

I don't expect this issue to make it to the top of any lists as npm within itself works fine, but I do worry a little about whether there's anything non-standard now. When packing this very small package in the STRs with 5.6.0 and 5.7.1, I see large differences in size of the package, so perhaps there are some headers, etc. that may be different/missing? This was tested with 7-Zip's latest version, 18.01 (x64) / 2018-01-28 as well as a prior version.

#### How can the CLI team reproduce the problem?
1. `md npm5pack && cd npm5pack && npm init -y && npm pack`
1. Install [7-Zip](http://www.7-zip.org).
1. Open _npm5pack-1.0.0.tgz_ file with 7-Zip. 
1. Attempt to open the contained _.tar_ file. Expect to see this prompt with 5.7.x:

![image](https://user-images.githubusercontent.com/8005145/36748889-3678a3d6-1bc7-11e8-8846-f1c6c587535e.png)

### supporting information:

 - `npm -v` prints: 5.7.1
 - `node -v` prints: 8.9.4
 - Windows, OS X/macOS, or Linux?: Windows 7 64-bit

**Comment by simonua** [comment]
Awesome! Thank you, Kat! 😀

**Comment by simonua** [comment]
Although this is closed already, just for the record, I did just verify on my end that this is all working. Thank you very much again!

**Comment by zkat** [comment]
For the curious: We started using [`node-tar`](https://npm.im/tar)'s `noMtime` option, which set all the timestamps to 0. The _reason_ for this was so two separate `npm pack` calls done from the same commit -- even on separate computers, would be able to generate hash-identical tarballs. We didn't really expect that random software out there would have... pathological issues with old timestamps. We still want to preserve the feature, though, so picking an arbitrary date more recent than `1980` seemed like the way to go. Hopefully there's no more incompatibilities!

**Comment by zkat** [comment]
@simonua thanks as always for your due diligence and help with filing these bugs! My only regret is I can't fix them faster! <3

**Comment by simonua** [comment]
Ha, anytime! Thank you!
