### ISSUE TITLE
npm can't install pageres-cli on ubuntu

### ISSUE THREAD

**Issue by suhashpatil** [npm/npm#19958]
#### I'm opening this issue because:

  - [x ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I am trying to install pageres-cli on an ubuntu system and it is failing with different errors. 
### supporting information:

 - `npm -v` prints:1.3.10

 - `node -v` prints:v0.10.25

 - `npm config get registry` prints: https://registry.npmjs.org/

 - Windows, OS X/macOS, or Linux?: Linux xyz.balasai.com 3.13.0-67-generic #110-Ubuntu SMP Fri Oct 23 13:24:41 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
Your versions of Node.js and `npm` are years old and are no longer supported.
