### ISSUE TITLE
SyntaxError: Unexpected token ILLEGAL

### ISSUE THREAD

**Issue by SalatielSauer** [npm/npm#19959]
#### I'm opening this issue because:

  - [ x ] npm is crashing.
  - [ x ] npm is doing something I don't understand.

#### What's going wrong?
I'm trying to install some _Discord_ dependencies, but I'm getting this strange error on the terminal:
![SyntaxError](https://user-images.githubusercontent.com/9287152/36937178-1168c0e2-1eee-11e8-9ba8-536b69081db1.png)

#### How can the CLI team reproduce the problem?
Well, I do not know, all the commands I try to run with npm I get this error above.

### supporting information:

 - `npm -v` prints: **npm -v results in the same error, unfortunately.**

 - `node -v` prints: **node -v results '_v0.10.25_' (I can not update the node using npm, because the npm command results the error above)**

 - `npm config get registry` prints: **Sorry, results in the same error.**

 - Windows, OS X/macOS, or Linux?: **Linux Mint 17.3**

**Comment by kenany** [comment]
Your version of Node.js is years old and is no longer supported. You can find new releases at <https://nodejs.org/>, do not use `npm` to update Node.js.
