### ISSUE TITLE
npm crash first time install d3

### ISSUE THREAD

**Issue by tonmanayo** [npm/npm#19995]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [x] npm is producing an incorrect install.
  #### What's going wrong?
npm ERR! code ERR_STREAM_WRITE_AFTER_END
npm ERR! write after end
tmack:~/D3_Fun/src/d3_tut$ npm install d3
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tmack/.npm/_logs/2018-03-08T13_54_04_493Z-debug.log
tmack:~/D3_Fun/src/d3_tut$ npm install d3
+ d3@4.13.0
added 33 packages from 2 contributors in 26.089s
#### How can the CLI team reproduce the problem?

Ubuntu 14 updated

**Comment by deployable** [comment]
Same as #19989
