### ISSUE TITLE
Impossible to install node-red-contrib-ttn npm

### ISSUE THREAD

**Issue by Francky58** [npm/npm#20004]
Following the tutorial " https://www.npmjs.com/package/node-red-contrib-ttn" I'm trying to install the npm node-red-contrib-ttn on a gateway Multitech ( mLinux 3.3.5 ;  Version: 1.4.1) Node-Red is by default already install and running without problem. 

During the npm install , i got that error :

admin@mtcdt:~# cd $HOME/.node-red
admin@mtcdt:~/.node-red# npm install node-red-contrib-ttn
jffs2: warning: (2967) jffs2_sum_write_data: Not enough space for summary, padsize = -196
npm ERR! not a package /tmp/npm-2815-yACk_OX_/github.com/thethingsnetwork/api
npm ERR! Error: ENOENT, open '/tmp/npm-2815-yACk_OX_/github.com/thethingsnetwork/api-unpack/package.json'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.12.27r13
npm ERR! command "node" "/usr/bin/npm" "install" "node-red-contrib-ttn"
npm ERR! cwd /home/root/.node-red
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! path /tmp/npm-2815-yACk_OX_/github.com/thethingsnetwork/api-unpack/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! not ok code 0

Is anyone have an idea of the root cause ?

**Comment by kenany** [comment]
Your versions of Node.js and `npm` are years old and are no longer supported.
