### ISSUE TITLE
NPM crashes on Webpack Encore installation

### ISSUE THREAD

**Issue by murtho** [npm/npm#20028]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.

#### What's going wrong?

When installing webpack encore with either npm or yarn the installation gets interrupted.

#### How can the CLI team reproduce the problem?

- setup a basic Symfony4 installation
- install the encore package: `composer require encore` (using symfony flex)
- run the cli command: `npm install @symfony/webpack-encore --save-dev`

### supporting information:

 - `npm-debug.log`:

86022 verbose If you need help, you may report this error at:
86022 verbose     <https://github.com/npm/npm/issues>
86023 verbose stack Error: EPROTO: protocol error, symlink '../acorn/bin/acorn' -> '/home/vagrant/shop4raad2/node_modules/.bin/acorn'
86023 verbose stack     at Error (native)
86024 verbose cwd /home/vagrant/shop4raad2
86025 error Linux 4.4.0-87-generic
86026 error argv "/usr/bin/node" "/usr/bin/npm" "install" "@symfony/webpack-encore" "--save-dev"
86027 error node v6.13.0
86028 error npm  v3.10.10
86029 error path ../acorn/bin/acorn
86030 error code EPROTO
86031 error errno -71
86032 error syscall symlink
86033 error EPROTO: protocol error, symlink '../acorn/bin/acorn' -> '/home/vagrant/shop4raad2/node_modules/.bin/acorn'
86034 error If you need help, you may report this error at:
86034 error     <https://github.com/npm/npm/issues>
86035 verbose exit [ -71, true ]

 - Linux Ubuntu 16 LTS (inside a container configured with puphpet):
 - Container:
   - [ ] I develop using Vagrant on Windows.

**Comment by kenany** [comment]
Does this also occur with newer versions of `npm`?

**Comment by murtho** [comment]
the npm version in which this occured was v3.10.10

v5.7.1 returned no errors.

**Comment by murtho** [comment]
the latest version also returns this error

**Comment by murtho** [comment]
adding `--no-bin-links` works though

**Comment by STPJ** [comment]
I have the same issue here, Any fix found yet?
No-bin-links doesn't work for me

**Comment by murtho** [comment]
@STPJ are you using a VM with vagrant/puphpet? don't run it from linux guest, but on your host machine, that's what works for me.
