### ISSUE TITLE
Npm adds dev dependencies to dependencies in package.json

### ISSUE THREAD

**Issue by pronebird** [npm/npm#20023]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Npm does not respect the `--dev` flag and always adds dependency to dependencies in package.json instead of devDependencies.

```
npm install robotjs --dev  
```

Looking at package.json I see:

```
  "dependencies": {
    "bindings": "^1.2.1",
    "robotjs": "^0.5.1"
  },
```

Doing the same with `yarn` works.

#### How can the CLI team reproduce the problem?

```
npm init -y
npm install robotjs --dev
cat package.json
```

### supporting information:

 - `npm -v` prints: 5.6.0
 - `node -v` prints: v8.10.0
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?: macOS
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
Are you sure you don't mean to be using the `--save-dev` flag instead?

**Comment by pronebird** [comment]
Ugh thanks @KenanY those are two absolutely different flags apparently.
