### ISSUE TITLE
**while creating prefix:css for autoprefixer for my project i get this error please help me** 

### ISSUE THREAD

**Issue by mukundlalge** [npm/npm#20048]
npm run prefix:css

> natours@1.0.0 prefix:css 

> _F:\MyProject

> postcss --use autoprefixer -b 'last 10 versions' css/style.concat.css -o css/style.prefix.css

TypeError: Patterns must be a string or an array of strings
    at assertPatternsInput (F:\MyProject\node_modules\globby\index.js:15:9)
    at generateGlobTasks (F:\MyProject\node_modules\globby\index.js:21:2)
    at module.exports (F:\MyProject\node_modules\globby\index.js:73:15)
    at Promise.resolve.then (F:\MyProject\node_modules\postcss-cli\index.js:55:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
    at Function.Module.runMain (module.js:703:11)
    at startup (bootstrap_node.js:190:16)
    at bootstrap_node.js:662:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! natours@1.0.0 prefix:css: `postcss --use autoprefixer -b 'last 10 versions' css/style.concat.css -o css/style.prefix.css`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the natours@1.0.0 prefix:css script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Acer\AppData\Roaming\npm-cache\_logs\2018-03-14T10_53_28_793Z-debug.log

error log file is:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run-script',
1 verbose cli   'prefix:css' ]
2 info using npm@5.6.0
3 info using node@v9.5.0
4 verbose run-script [ 'prefix:css' ]
5 info lifecycle natours@1.0.0~prefix:css: natours@1.0.0
6 verbose lifecycle natours@1.0.0~prefix:css: unsafe-perm in lifecycle true
7 verbose lifecycle natours@1.0.0~prefix:css: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;F:\MyProject\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\;C:\Program Files\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files\nodejs\;C:\Program Files\Java\jdk1.8.0_151\bin;C:\Program Files\Microsoft VS Code\bin;C:\Users\Acer\AppData\Roaming\npm
8 verbose lifecycle natours@1.0.0~prefix:css: CWD: F:\MyProject
9 silly lifecycle natours@1.0.0~prefix:css: Args: [ '/d /s /c',
9 silly lifecycle   'postcss --use autoprefixer -b \'last 10 versions\' css/style.concat.css -o css/style.prefix.css' ]
10 silly lifecycle natours@1.0.0~prefix:css: Returned: code: 1  signal: null
11 info lifecycle natours@1.0.0~prefix:css: Failed to exec prefix:css script
12 verbose stack Error: natours@1.0.0 prefix:css: `postcss --use autoprefixer -b 'last 10 versions' css/style.concat.css -o css/style.prefix.css`
12 verbose stack Exit status 1
12 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
12 verbose stack     at EventEmitter.emit (events.js:160:13)
12 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
12 verbose stack     at ChildProcess.emit (events.js:160:13)
12 verbose stack     at maybeClose (internal/child_process.js:943:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
13 verbose pkgid natours@1.0.0
14 verbose cwd F:\MyProject
15 verbose Windows_NT 10.0.10240
16 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run-script" "prefix:css"
17 verbose node v9.5.0
18 verbose npm  v5.6.0
19 error code ELIFECYCLE
20 error errno 1
21 error natours@1.0.0 prefix:css: `postcss --use autoprefixer -b 'last 10 versions' css/style.concat.css -o css/style.prefix.css`
21 error Exit status 1
22 error Failed at the natours@1.0.0 prefix:css script.
22 error This is probably not a problem with npm. There is likely additional logging output above.
23 verbose exit [ 1, true ]

**Comment by kenany** [comment]
Error is coming from `postcss`, not `npm`:

```
postcss --use autoprefixer -b 'last 10 versions' css/style.concat.css -o css/style.prefix.css

TypeError: Patterns must be a string or an array of **strings**
```

**Comment by 42x42x42** [comment]
did you find out how to solve a problem? share your decision pls

**Comment by ploutos27** [comment]
if you're using windows: try the following: 

`postcss --use autoprefixer -b  \"last 10 versions\" css/style.concat.css -o css/style.prefix.css`

`

**Comment by 42x42x42** [comment]
It's working!! Thank you! does that mean that I should replace ' ' by \" "\  in package.json always in all type of command or its only postcss issue?
