### ISSUE TITLE
Getting error as npm ERR! code ELIFECYCLE npm ERR! errno 100

### ISSUE THREAD

**Issue by siva1282** [npm/npm#20064]
npm ERR! This is probably not a problem with npm. There is likely additional lo
ging output above.
                                                           ž

**Comment by siva1282** [comment]
this is output i am getting while running my protractor scripts
npm ERR! code ELIFECYCLE
npm ERR! errno 100
npm ERR! trade-compliance@1.0.3 automated-test: `node node_modules/touch-stone-c
ore/runner/main.js "-p" "--tags" "@success-login" "--env" "riskcenter_stg"`
npm ERR! Exit status 100
npm ERR!
npm ERR! Failed at the trade-compliance@1.0.3 automated-test script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\YarramsettyV\AppData\Roaming\npm-cache\_logs\2018-03-15T07
_05_10_079Z-debug.log

 Can any one help me to resolve this error

**Comment by kenany** [comment]
As the error log states,

```
node node_modules/touch-stone-c ore/runner/main.js "-p" "--tags" "@success-login" "--env" "riskcenter_stg"
```

is throwing an error code, not `npm` itself. All `npm` is doing here is letting you know about it.
