### ISSUE TITLE
unable install angular cli

### ISSUE THREAD

**Issue by ramakrishna08411** [npm/npm#20078]
while installing angular cli by command npm install -g @angular/cli,am facing this problem

 Unhandled rejection Error: ENOENT: no such file or directory, rename 'C:\Users\D esktop1\AppData\Roaming\npm-cache\_cacache\tmp\0227aed6' -> 'C:\Users\Desktop1\A ppData\Roaming\npm-cache\_cacache\content-v2\sha512\6c\6c\0f6091faa715065d8d9706 2b878ea70c4eeae56c8e8fcdecba89c93c13e5068fce92faf6d286ec8065bba722bfc79ad8e56656 2b0b3a9d8ad5d577bee4fa'

**Comment by kenany** [comment]
Closing since this is blank.
