### ISSUE TITLE
npm install every day 

### ISSUE THREAD

**Issue by frankthepunk** [npm/npm#20074]
Hi,

at my VS Code I need to install npm **every day** ("npm install").
Why it is like that?

Frank

**Comment by kenany** [comment]
Could you expand on what your issue is?

**Comment by frankthepunk** [comment]
You mean _explain_?
I mean I dont want to install npm every day.
I'ld like to install it ones instead of every day.
And my question is, why do I have it to install again and how to avoid it.

Frank

**Comment by kenany** [comment]
Are you saying that something like `npm --version` stops working at the beginning of every day?

**Comment by frankthepunk** [comment]
Hi Kenan!
After I restart my computer (daily), starting VS Code, starting the terminal and setting the command "npm serve" I get the information, that I have to install npm first. After I do so (_"install npm"_), I can use it (_"npm serve"_).

**Comment by kenany** [comment]
Okay, whenever you can, try doing `npm --version` from your favorite terminal, _outside_ of VS Code, after one of your daily reboots. This is just to make sure the problem doesn't somehow lie in VS Code itself.

This is unlikely to be an issue with `npm` itself, because no part of `npm`'s functionality would make it delete itself on reboot.

**Comment by frankthepunk** [comment]
Thanks Kenan,

at shell outside of VS Code I get the version 5.7.1
at therminal in VS Code I get the same version 5.7.1.

So that's fine?!

**Comment by kenany** [comment]
Okay, how about after a reboot, in an external shell?

**Comment by frankthepunk** [comment]
Kenan, reboot of what?

**Comment by frankthepunk** [comment]
Today it works.
I mean I don't get ask to install npm again.
I don't know why it's different now.

Frank

**Comment by mcclowes** [comment]
@KenanY Sounds like this is resolved
