### ISSUE TITLE
error ENOENT: no such file or directory, chmod '~/node_modules/package/bin/file.js'

### ISSUE THREAD

**Issue by dahifi** [npm/npm#20073]
#### I'm opening this issue because:

This is my first time working with node and I have spent several hours getting up to speed with nvm and npm. I'm able to install certain packages, but this one in particular will not work no matter what I try.  Most of the searches that I've done indicate that this problem should have been bugfixed several years ago, so I'm thinking that this problem is likely a repo issue, perhaps a .gitignore issue. 

  - [ ] npm is crashing.
  - [x ] npm is producing an incorrect install.
  - [x ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
ENOENT: no such file or directory, chmod '~/.nvm/versions/node/v6.11.1/lib/node_modules/pollmommy/bin/app.js'

#### How can the CLI team reproduce the problem?
nvm install pollmommy -g

### supporting information:

 - `npm -v` prints: 3.10.10, 5.6.0
 - `node -v` prints: 6.11.1, 8.10.0
 - `npm config get registry` prints: npmjs
 - Windows, OS X/macOS, or Linux?: Multiple Ubuntu installations and Windows
 - Network issues:
   - Geographic location where npm was run: US EAST

 - Container: None

**Comment by kenany** [comment]
Can I see the full output of `npm install pollmommy -g` with `npm` v5.6.0?

**Comment by kenany** [comment]
Also, is "npmjs" the actual output of `npm config get registry`?

**Comment by dahifi** [comment]
```
el@elohim:~/pollmommy$ npm -v
5.6.0
el@elohim:~/pollmommy$ npm install pollmommy -g
npm ERR! path /home/el/.nvm/versions/node/v8.10.0/lib/node_modules/pollmommy/bin/app.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/home/el/.nvm/versions/node/v8.10.0/lib/node_modules/pollmommy/bin/app.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/el/.npm/_logs/2018-03-16T14_54_57_403Z-debug.log
el@elohim:~/pollmommy$

```
The actual registry is https://registry.npmjs.org/

**Comment by dahifi** [comment]
I've also confirmed that the app.js file is in the /src directory. 

el@elohim:~/pollmommy/src$ ls -l
total 12
-rw-rw-rw- 1 el el 1271 Mar 16 09:26 app.js
-rw-rw-rw- 1 el el  227 Mar 16 09:26 index.js
-rw-rw-rw- 1 el el 1513 Mar 16 09:26 pollmommy.js
-rw-rw-rw- 1 el el 2559 Mar 16 09:26 vote.js
