### ISSUE TITLE
npm publish: That word is not allowed

### ISSUE THREAD

**Issue by halbgut** [npm/npm#20097]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I'm trying to publish a package called `download-as-csv`. But I'm getting an error. I don't understand what this means or how to fix it. Is there an illegal word in my package name?

```
error publish Failed PUT 400
verbose stack Error: That word is not allowed. Please contact support (support@npmjs.com) if you believe you received this in error. : download-as-csv
```

#### How can the CLI team reproduce the problem?

[npm-debug.log](https://gist.github.com/Kriegslustig/2309a2e1e4fbcce125ca6e0d85e8d209)

To reproduce this issue clone [this repo](https://github.com/kriegslustig/download-as-csv) an run `npm publish`.

### supporting information:

 - `npm -v` prints: 5.7.1
 - `node -v` prints: v8.9.3
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS

**Comment by kenany** [comment]
Perhaps this is better asked at https://github.com/npm/registry
