### ISSUE TITLE
npm stats doesn't work anymore for organizations packages

### ISSUE THREAD

**Issue by aitboudad** [npm/npm#20092]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?
see for example: https://www.npmjs.com/package/@angular/core

![selection_122](https://user-images.githubusercontent.com/1753742/37559897-02ba5680-2a26-11e8-9625-b21e7743860f.png)

**Comment by kenany** [comment]
This belongs in https://github.com/npm/registry or https://github.com/npm/www
