### ISSUE TITLE
npm install {package-name} does not work.

### ISSUE THREAD

**Issue by mykolapatko** [npm/npm#20090]
When I run "npm install gulp", got error:
`ENOENT: no such file or directory, rename '\node_modules\ansi-styles' -> '\node_modules\.ansi-styles.DELETE'`. 
The same for other packages. Tried different packages.
Tried on different versions of node, npm.
Tried on Windows and Debian.

Debug.log
[2018-03-17T13_12_01_816Z-debug.log](https://github.com/npm/npm/files/1821635/2018-03-17T13_12_01_816Z-debug.log)

**Comment by cannap** [comment]
same 
yesterday everything worked fine 

https://gyazo.com/475b6a606d135ce2e71e270d6a326cc3

and not just for gulp

Windows 10
Npm version 5.6.0
node 9.7.1


//e https://github.com/npm/npm/issues/17444

malewarebytes was my problem  -.-

**Comment by mykolapatko** [comment]
The same for me.
malewarebytes was my problem
