### ISSUE TITLE
Installing npm almost reaches MAX_PATH on Windows

### ISSUE THREAD

**Issue by TheCloudlessSky** [npm/npm#20101]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?

See nodejs/node#19449. Using the Node Windows Installer (.msi), the Windows Binary (.zip), or directly downloading from [the GitHub releases](https://github.com/npm/npm/releases) the installation *almost* reaches the [MAX_PATH allowed in Windows](https://msdn.microsoft.com/en-us/library/aa365247(VS.85).aspx#maxpath) (260 characters) or very easily exceed it when using the .zips. For example, here's the top 10 paths by length from the `8.10.0` installer:

```
$ cmd /c dir /S /B | Sort-Object { -$_.Length; } | Select-Object -First 10 | % { "$($_.Length) = $_" }
239 = C:\Program Files\nodejs\node_modules\npm\node_modules\libnpx\node_modules\yargs\node_modules\read-pkg-up\node_modules\read-pkg\node_modules\load-json-file\node_modules\parse-json\node_modules\error-ex\node_modules\is-arrayish\.istanbul.yml
239 = C:\Program Files\nodejs\node_modules\npm\node_modules\libnpx\node_modules\yargs\node_modules\read-pkg-up\node_modules\read-pkg\node_modules\load-json-file\node_modules\parse-json\node_modules\error-ex\node_modules\is-arrayish\.editorconfig
238 = C:\Program Files\nodejs\node_modules\npm\node_modules\npm-profile\node_modules\make-fetch-happen\node_modules\https-proxy-agent\node_modules\agent-base\node_modules\es6-promisify\node_modules\es6-promise\lib\es6-promise\promise\resolve.js
238 = C:\Program Files\nodejs\node_modules\npm\node_modules\npm-profile\node_modules\make-fetch-happen\node_modules\socks-proxy-agent\node_modules\agent-base\node_modules\es6-promisify\node_modules\es6-promise\lib\es6-promise\promise\resolve.js
238 = C:\Program Files\nodejs\node_modules\npm\node_modules\libnpx\node_modules\yargs\node_modules\read-pkg-up\node_modules\read-pkg\node_modules\load-json-file\node_modules\parse-json\node_modules\error-ex\node_modules\is-arrayish\package.json
237 = C:\Program Files\nodejs\node_modules\npm\node_modules\npm-profile\node_modules\make-fetch-happen\node_modules\socks-proxy-agent\node_modules\agent-base\node_modules\es6-promisify\node_modules\es6-promise\lib\es6-promise\promise\reject.js
237 = C:\Program Files\nodejs\node_modules\npm\node_modules\libnpx\node_modules\yargs\node_modules\read-pkg-up\node_modules\read-pkg\node_modules\load-json-file\node_modules\parse-json\node_modules\error-ex\node_modules\is-arrayish\.travis.yml
237 = C:\Program Files\nodejs\node_modules\npm\node_modules\npm-profile\node_modules\make-fetch-happen\node_modules\https-proxy-agent\node_modules\agent-base\node_modules\es6-promisify\node_modules\es6-promise\lib\es6-promise\promise\reject.js
237 = C:\Program Files\nodejs\node_modules\npm\node_modules\npm-profile\node_modules\make-fetch-happen\node_modules\http-proxy-agent\node_modules\agent-base\node_modules\es6-promisify\node_modules\es6-promise\lib\es6-promise\promise\resolve.js
236 = C:\Program Files\nodejs\node_modules\npm\node_modules\libnpx\node_modules\yargs\node_modules\read-pkg-up\node_modules\read-pkg\node_modules\load-json-file\node_modules\parse-json\node_modules\error-ex\node_modules\is-arrayish\.npmignore
```

The .msi installer is very close to failing to install to `C:\Program Files\nodejs` if any module that npm depends on grows to a longer path. This isn't a problem when *using* npm since it'll properly dedupe the packages with npm > 3. This problem is with the installation of npm itself (which Node includes with its releases). Ideally, `node_modules/npm` would be pre-deduped so that it's not so long.

For now, I've had to switch to the `yarn` package manager. It's just a single file, not a deep directory structure to install. 

#### How can the CLI team reproduce the problem?

Install the .msi or .zip for Node 5.6.0 (current) or 8.10.0 (LTS). Or, download the .zip directly from [the GitHub releases](https://github.com/npm/npm/releases). 

### supporting information:

 - `npm -v` prints: 5.6.0
 - `node -v` prints: 8.10.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows 7 64-bit

**Comment by mhoeger** [comment]
Is this issue still not addressed? How is npm when installed with node deduped?

**Comment by TheCloudlessSky** [comment]
@mhoeger yup, it's been addressed in https://github.com/nodejs/node/issues/19449#issuecomment-395924760.
