### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by chenweigh** [npm/npm#20113]
Metro Bundler ready.

 ERROR  spawn watchman EAGAIN
Loading dependency graph...npm ERR! code ELIFECYCLE
npm ERR! errno 11
npm ERR! ProgramGirl@0.0.1 start: `node node_modules/react-native/local-cli/cli.js start`
npm ERR! Exit status 11
npm ERR! 
npm ERR! Failed at the ProgramGirl@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/chen/.npm/_logs/2018-03-21T01_59_43_226Z-debug.log

-------------

package.json:
{
  "name": "ProgramGirl",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.3.0-alpha.1",
    "react-native": "0.54.2"
  },
  "devDependencies": {
    "babel-jest": "22.4.1",
    "babel-preset-react-native": "4.0.0",
    "jest": "22.4.2",
    "react-test-renderer": "16.3.0-alpha.1"
  },
  "jest": {
    "preset": "react-native"
  }
}

----------
1. cnpm install 
2. cnpm sync
3. npm start

-------
please help me.

**Comment by kenany** [comment]
As the error log indicates, this command:

```
node node_modules/react-native/local-cli/cli.js start
```

is throwing an error, not `npm` itself.
