### ISSUE TITLE
cb() never called!

### ISSUE THREAD

**Issue by baozdemir** [npm/npm#20129]
Hello everyone !

I am using
node: 9.9.0
npm: 5.6.0

in all npm install operations i got error.

```
...
same error ...
...
npm WARN tar ENOENT: no such file or directory, open '...\node_modules\.staging\rxjs-1d7aea8f\add\operator\zip.js.map'
npm WARN tar ENOENT: no such file or directory, open '...\node_modules\.staging\rxjs-1d7aea8f\add\operator\zipAll.d.ts'
npm WARN tar ENOENT: no such file or directory, open '...\node_modules\.staging\rxjs-1d7aea8f\add\operator\zipAll.js'
npm WARN tar ENOENT: no such file or directory, open '...\node_modules\.staging\rxjs-1d7aea8f\add\operator\zipAll.js.map'
npm WARN tar ENOENT: no such file or directory, open '...\node_modules\.staging\rxjs-1d7aea8f\bundles\Rx.js'
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\...\AppData\Roaming\npm-cache\_logs\2018-03-21T16_58_59_656Z-debug.log

```

How fix that ? Thanks...

**Comment by jamiescou** [comment]
I am using:
npm :5.7.1
node: 8.9.3
problem: "Unhandled rejection RangeError: Maximum call stack size exceededill install loadIdealTree"
I met the same problem. Did you solve it?

**Comment by baozdemir** [comment]
nop :) I am using the yarn temporarily. I hope will come fix.

**Comment by xiaofengqqcom123** [comment]
I am using:
npm :5.7.1
node: 8.9.4
problem: "Unhandled rejection RangeError: Maximum call stack size exceededill install loadIdealTree
"
I met the same problem. Did you solve it?

**Comment by baozdemir** [comment]
I could not find a solution in my current version.
I changed the version and I don't get a error.
node: 8.10.0
npm: 5.6.0

**Comment by legodude17** [comment]
Try updating to `npm@6.0.1`.
