### ISSUE TITLE
I have installed nodeJs and setup on my machine with VS 2015. When I try to run the sample hello world application, its throwing the below error:

### ISSUE THREAD

**Issue by ganeshpaiya** [npm/npm#20135]
#### I'm opening this issue because:

  verb(node:14096) [DEP0062] DeprecationWarning: node --debug and node --debug-brk are invalid. Please use node --inspect or node --inspect-brk instead. Press any key to continue...

**Comment by kenany** [comment]
This error does not appear to be coming from `npm`. Please try <https://github.com/nodejs/help> instead.
