### ISSUE TITLE
EPERM: operation not permitted, mkdir

### ISSUE THREAD

**Issue by Legends** [npm/npm#20166]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x ] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I am trying to install a package via node.js script using `npm` (part of mochajs test):

```
return new Promise((resolve, reject) => {
var npm = require("npm");
npm.load({
	 global: true
}, function (err) {
	if (err) {
		console.error("test: " + err);
		reject(err);
	}
	npm.commands.install(["mypackage@latest"], function (err, data) {  <--- fails with error
		if (err) {
			console.error("test: " + err);
			reject(err);
			// assert.fail(err);
		} else {
			resolve(data);
		}
	});
	npm.on("log", function (message) {
		console.log(message);
	});
});
});
```

**Error:**

> EPERM: operation not permitted, mkdir 'C:\Program Files\nodejs\node_modules\.staging'locks\staging-dfd8fbf9c1feea0f.lock for C:\Progra
> error An unexpected error occurred: "Command failed.
> Exit code: 1

### supporting information:

 - `npm -v` prints: 5.8.0
 - `node -v` prints: v8.10.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: win 10 x64
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by pierre-charpentier** [comment]
Have you tried running cmd as an administrator and starting your script from there ?

The `global` option allows to install the package globally on your system but you need to have the permission to do so.

**Comment by Legends** [comment]
I guess it had to do with mochajs timeouts or not resolving correctly my promises..
Increasing the timeouts helped. Closing
