### ISSUE TITLE
npm ERR! cb() never called!

### ISSUE THREAD

**Issue by neyamii** [npm/npm#20167]
just trying to install angular

npm version :  5.6.0

node version : v8.10.0

os : windows 10

and this is the full log :  
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   '@angular/cli' ]
2 info using npm@5.6.0
3 info using node@v8.10.0
4 verbose npm-session 64414680923c11ef
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 200 https://registry.npmjs.org/@angular%2fcli 1560ms
8 silly pacote tag manifest for @angular/cli@latest fetched in 1613ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule @angular/cli@1.7.3 checking installable status
14 http fetch GET 200 https://registry.npmjs.org/cache-loader 1451ms
15 silly pacote range manifest for cache-loader@^1.2.0 fetched in 1459ms
16 silly resolveWithNewModule cache-loader@1.2.2 checking installable status
17 http fetch GET 200 https://registry.npmjs.org/ajv 1464ms
18 silly pacote range manifest for ajv@^6.1.1 fetched in 1474ms
19 silly resolveWithNewModule ajv@6.4.0 checking installable status
20 http fetch GET 200 https://registry.npmjs.org/@angular-devkit%2fbuild-optimizer 1570ms
21 http fetch GET 200 https://registry.npmjs.org/@angular-devkit%2fschematics 1570ms
22 silly pacote version manifest for @angular-devkit/build-optimizer@0.3.2 fetched in 1578ms
23 silly resolveWithNewModule @angular-devkit/build-optimizer@0.3.2 checking installable status
24 silly pacote version manifest for @angular-devkit/schematics@0.3.2 fetched in 1578ms
25 silly resolveWithNewModule @angular-devkit/schematics@0.3.2 checking installable status
26 http fetch GET 200 https://registry.npmjs.org/@ngtools%2fjson-schema 1610ms
27 http fetch GET 200 https://registry.npmjs.org/@schematics%2fangular 1610ms
28 silly pacote version manifest for @ngtools/json-schema@1.2.0 fetched in 1617ms
29 silly resolveWithNewModule @ngtools/json-schema@1.2.0 checking installable status
30 silly pacote version manifest for @schematics/angular@0.3.2 fetched in 1618ms
31 silly resolveWithNewModule @schematics/angular@0.3.2 checking installable status
32 http fetch GET 200 https://registry.npmjs.org/@ngtools%2fwebpack 1648ms
33 silly pacote version manifest for @ngtools/webpack@1.10.2 fetched in 1656ms
34 silly resolveWithNewModule @ngtools/webpack@1.10.2 checking installable status
35 http fetch GET 200 https://registry.npmjs.org/autoprefixer 2160ms
36 silly pacote range manifest for autoprefixer@^7.2.3 fetched in 2168ms
37 silly resolveWithNewModule autoprefixer@7.2.6 checking installable status
38 http fetch GET 200 https://registry.npmjs.org/circular-dependency-plugin 1270ms
39 silly pacote range manifest for circular-dependency-plugin@^4.2.1 fetched in 1276ms
40 silly resolveWithNewModule circular-dependency-plugin@4.4.0 checking installable status
41 http fetch GET 200 https://registry.npmjs.org/common-tags 1399ms
42 http fetch GET 200 https://registry.npmjs.org/copy-webpack-plugin 1357ms
43 silly pacote range manifest for common-tags@^1.3.1 fetched in 1407ms
44 silly resolveWithNewModule common-tags@1.7.2 checking installable status
45 silly pacote range manifest for copy-webpack-plugin@~4.4.1 fetched in 1366ms
46 silly resolveWithNewModule copy-webpack-plugin@4.4.3 checking installable status
47 http fetch GET 200 https://registry.npmjs.org/clean-css 1418ms
48 silly pacote range manifest for clean-css@^4.1.11 fetched in 1424ms
49 silly resolveWithNewModule clean-css@4.1.11 checking installable status
50 http fetch GET 200 https://registry.npmjs.org/denodeify 1419ms
51 silly pacote range manifest for denodeify@^1.2.1 fetched in 1426ms
52 silly resolveWithNewModule denodeify@1.2.1 checking installable status
53 http fetch GET 200 https://registry.npmjs.org/ember-cli-string-utils 1311ms
54 silly pacote range manifest for ember-cli-string-utils@^1.0.0 fetched in 1316ms
55 silly resolveWithNewModule ember-cli-string-utils@1.1.0 checking installable status
56 http fetch GET 200 https://registry.npmjs.org/chalk 2107ms
57 silly pacote range manifest for chalk@~2.2.0 fetched in 2115ms
58 silly resolveWithNewModule chalk@2.2.2 checking installable status
59 http fetch GET 200 https://registry.npmjs.org/extract-text-webpack-plugin 1421ms
60 silly pacote range manifest for extract-text-webpack-plugin@^3.0.2 fetched in 1429ms
61 silly resolveWithNewModule extract-text-webpack-plugin@3.0.2 checking installable status
62 http fetch GET 200 https://registry.npmjs.org/glob 1288ms
63 silly pacote range manifest for glob@^7.0.3 fetched in 1295ms
64 silly resolveWithNewModule glob@7.1.2 checking installable status
65 http fetch GET 200 https://registry.npmjs.org/fs-extra 1413ms
66 http fetch GET 200 https://registry.npmjs.org/file-loader 1417ms
67 silly pacote range manifest for fs-extra@^4.0.0 fetched in 1422ms
68 silly resolveWithNewModule fs-extra@4.0.3 checking installable status
69 silly pacote range manifest for file-loader@^1.1.5 fetched in 1425ms
70 silly resolveWithNewModule file-loader@1.1.11 checking installable status
71 http fetch GET 200 https://registry.npmjs.org/html-webpack-plugin 1417ms
72 silly pacote range manifest for html-webpack-plugin@^2.29.0 fetched in 1424ms
73 silly resolveWithNewModule html-webpack-plugin@2.30.1 checking installable status
74 http fetch GET 200 https://registry.npmjs.org/karma-source-map-support 1305ms
75 silly pacote range manifest for karma-source-map-support@^1.2.0 fetched in 1312ms
76 silly resolveWithNewModule karma-source-map-support@1.2.0 checking installable status
77 http fetch GET 200 https://registry.npmjs.org/less 1338ms
78 silly pacote range manifest for less@^2.7.2 fetched in 1347ms
79 silly resolveWithNewModule less@2.7.3 checking installable status
80 http fetch GET 200 https://registry.npmjs.org/less-loader 1318ms
81 silly pacote range manifest for less-loader@^4.0.5 fetched in 1326ms
82 silly resolveWithNewModule less-loader@4.1.0 checking installable status
83 http fetch GET 200 https://registry.npmjs.org/license-webpack-plugin 1389ms
84 silly pacote range manifest for license-webpack-plugin@^1.0.0 fetched in 1398ms
85 silly resolveWithNewModule license-webpack-plugin@1.3.1 checking installable status
86 http fetch GET 200 https://registry.npmjs.org/loader-utils 1374ms
87 silly pacote version manifest for loader-utils@1.1.0 fetched in 1381ms
88 silly resolveWithNewModule loader-utils@1.1.0 checking installable status
89 http fetch GET 200 https://registry.npmjs.org/minimatch 1313ms
90 silly pacote range manifest for minimatch@^3.0.4 fetched in 1319ms
91 silly resolveWithNewModule minimatch@3.0.4 checking installable status
92 http fetch GET 200 https://registry.npmjs.org/node-modules-path 1298ms
93 silly pacote range manifest for node-modules-path@^1.0.0 fetched in 1305ms
94 silly resolveWithNewModule node-modules-path@1.0.1 checking installable status
95 http fetch GET 200 https://registry.npmjs.org/lodash 1975ms
96 silly pacote range manifest for lodash@^4.11.1 fetched in 1980ms
97 silly resolveWithNewModule lodash@4.17.5 checking installable status
98 http fetch GET 200 https://registry.npmjs.org/nopt 1356ms
99 silly pacote range manifest for nopt@^4.0.1 fetched in 1362ms
100 silly resolveWithNewModule nopt@4.0.1 checking installable status
101 http fetch GET 200 https://registry.npmjs.org/opn 1290ms
102 silly pacote range manifest for opn@~5.1.0 fetched in 1297ms
103 silly resolveWithNewModule opn@5.1.0 checking installable status
104 http fetch GET 200 https://registry.npmjs.org/portfinder 1376ms
105 silly pacote range manifest for portfinder@~1.0.12 fetched in 1382ms
106 silly resolveWithNewModule portfinder@1.0.13 checking installable status
107 http fetch GET 200 https://registry.npmjs.org/postcss 1391ms
108 silly pacote range manifest for postcss@^6.0.16 fetched in 1398ms
109 silly resolveWithNewModule postcss@6.0.21 checking installable status
110 http fetch GET 200 https://registry.npmjs.org/postcss-import 1387ms
111 silly pacote range manifest for postcss-import@^11.0.0 fetched in 1396ms
112 silly resolveWithNewModule postcss-import@11.1.0 checking installable status
113 http fetch GET 200 https://registry.npmjs.org/postcss-url 1395ms
114 silly pacote range manifest for postcss-url@^7.1.2 fetched in 1403ms
115 silly resolveWithNewModule postcss-url@7.3.1 checking installable status
116 http fetch GET 200 https://registry.npmjs.org/postcss-loader 2064ms
117 silly pacote range manifest for postcss-loader@^2.0.10 fetched in 2072ms
118 silly resolveWithNewModule postcss-loader@2.1.3 checking installable status
119 http fetch GET 200 https://registry.npmjs.org/resolve 1399ms
120 silly pacote range manifest for resolve@^1.1.7 fetched in 1405ms
121 silly resolveWithNewModule resolve@1.6.0 checking installable status
122 http fetch GET 200 https://registry.npmjs.org/rxjs 1366ms
123 silly pacote range manifest for rxjs@^5.5.6 fetched in 1374ms
124 silly resolveWithNewModule rxjs@5.5.7 checking installable status
125 http fetch GET 200 https://registry.npmjs.org/sass-loader 1390ms
126 silly pacote range manifest for sass-loader@^6.0.6 fetched in 1396ms
127 silly resolveWithNewModule sass-loader@6.0.7 checking installable status
128 http fetch GET 200 https://registry.npmjs.org/semver 1361ms
129 silly pacote range manifest for semver@^5.1.0 fetched in 1367ms
130 silly resolveWithNewModule semver@5.5.0 checking installable status
131 http fetch GET 200 https://registry.npmjs.org/silent-error 1336ms
132 silly pacote range manifest for silent-error@^1.0.0 fetched in 1341ms
133 silly resolveWithNewModule silent-error@1.1.0 checking installable status
134 http fetch GET 200 https://registry.npmjs.org/source-map-support 1378ms
135 silly pacote range manifest for source-map-support@^0.4.1 fetched in 1385ms
136 silly resolveWithNewModule source-map-support@0.4.18 checking installable status
137 http fetch GET 200 https://registry.npmjs.org/istanbul-instrumenter-loader 1322ms
138 silly pacote range manifest for istanbul-instrumenter-loader@^3.0.0 fetched in 1328ms
139 silly resolveWithNewModule istanbul-instrumenter-loader@3.0.0 checking installable status
140 http fetch GET 200 https://registry.npmjs.org/style-loader 1378ms
141 silly pacote range manifest for style-loader@^0.19.1 fetched in 1384ms
142 silly resolveWithNewModule style-loader@0.19.1 checking installable status
143 http fetch GET 200 https://registry.npmjs.org/stylus 1359ms
144 silly pacote range manifest for stylus@^0.54.5 fetched in 1369ms
145 silly resolveWithNewModule stylus@0.54.5 checking installable status
146 http fetch GET 200 https://registry.npmjs.org/stylus-loader 1397ms
147 silly pacote range manifest for stylus-loader@^3.0.1 fetched in 1404ms
148 silly resolveWithNewModule stylus-loader@3.0.2 checking installable status
149 http fetch GET 200 https://registry.npmjs.org/uglifyjs-webpack-plugin 1354ms
150 silly pacote range manifest for uglifyjs-webpack-plugin@^1.1.8 fetched in 1359ms
151 silly resolveWithNewModule uglifyjs-webpack-plugin@1.2.4 checking installable status
152 http fetch GET 200 https://registry.npmjs.org/url-loader 1404ms
153 silly pacote range manifest for url-loader@^0.6.2 fetched in 1410ms
154 silly resolveWithNewModule url-loader@0.6.2 checking installable status
155 http fetch GET 200 https://registry.npmjs.org/webpack-dev-middleware 1361ms
156 silly pacote range manifest for webpack-dev-middleware@~1.12.0 fetched in 1369ms
157 silly resolveWithNewModule webpack-dev-middleware@1.12.2 checking installable status
158 http fetch GET 200 https://registry.npmjs.org/webpack-dev-server 1321ms
159 silly pacote range manifest for webpack-dev-server@~2.11.0 fetched in 1331ms
160 silly resolveWithNewModule webpack-dev-server@2.11.2 checking installable status
161 http fetch GET 200 https://registry.npmjs.org/webpack-merge 1333ms
162 silly pacote range manifest for webpack-merge@^4.1.0 fetched in 1340ms
163 silly resolveWithNewModule webpack-merge@4.1.2 checking installable status
164 http fetch GET 200 https://registry.npmjs.org/webpack 2264ms
165 silly pacote range manifest for webpack@~3.11.0 fetched in 2282ms
166 silly resolveWithNewModule webpack@3.11.0 checking installable status
167 http fetch GET 200 https://registry.npmjs.org/webpack-sources 2031ms
168 silly pacote range manifest for webpack-sources@^1.0.0 fetched in 2038ms
169 silly resolveWithNewModule webpack-sources@1.1.0 checking installable status
170 http fetch GET 200 https://registry.npmjs.org/webpack-subresource-integrity 1398ms
171 silly pacote range manifest for webpack-subresource-integrity@^1.0.1 fetched in 1432ms
172 silly resolveWithNewModule webpack-subresource-integrity@1.0.4 checking installable status
173 http fetch GET 200 https://registry.npmjs.org/node-sass 1300ms
174 silly pacote range manifest for node-sass@^4.7.2 fetched in 1307ms
175 silly resolveWithNewModule node-sass@4.8.3 checking installable status
176 error cb() never called!
177 error This is an error with npm itself. Please report this error at:
178 error <https://github.com/npm/npm/issues>

**Comment by pierre-charpentier** [comment]
Hi, please fill the sections of your comment.

We need to know what you are trying to do when facing this error in order to resolve the issue.

**Comment by neyamii** [comment]
I'm trying to install angular


npm install -g @angular/cli

**Comment by pierre-charpentier** [comment]
Please edit your first comment with relevant information such as NPM and NodeJS versions, the command you typed, your operating system, the full error message, ...

**Comment by neyamii** [comment]
Done
