### ISSUE TITLE
Redux Reduct option

### ISSUE THREAD

**Issue by leyaannie** [npm/npm#20176]
const addedIds = (state = initialState.addedIds, action) => {
  switch (action.type) {
    case ADD_TO_CART:
      if (state.indexOf(action.productId) !== -1) {
        return state
      }
      return [ ...state, action.productId ]

      case REDUCT_FROM_CART:
       return state.filter(productId => action.productId !== productId)
    default:
      return state
  }
}

const quantityById = (state = initialState.quantityById, action) => {
  
  switch (action.type) {
    case ADD_TO_CART:
      const{ productId } = action
      return { ...state,
        [productId]: (state[productId] || 0) + 1
      }

      case REDUCT_FROM_CART:
      return { ...state,
        [productId]: (state[productId] ) - 1
      } 
      default:
      return state
  }
}

Please help me to add reduct option ..Is the code for reduct is right?? This is redux shopping cart project..

**Comment by kenany** [comment]
Sorry, but this issue tracker is for `npm`-related issues only. Please take this to a site like StackOverflow.
