### ISSUE TITLE
npm is not working in linux when trying to install packages

### ISSUE THREAD

**Issue by ghost** [npm/npm#20174]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

`npm install` does not install the packages neither creating node_modules folder

#### How can the CLI team reproduce the problem?

- I cloned a repository from github using `git clone https://github.com/AWNICS/mm-node.git`
- `cd mm-node`
- `npm install`

This is what happens when I run `npm install --verbose` : 
![image](https://user-images.githubusercontent.com/25379505/37928470-8e3240a2-315a-11e8-9596-b1a3b000d615.png)

### supporting information:

 - `npm -v` prints: 5.7.1
 - `node -v` prints: 8.9.4
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux

**Comment by kenany** [comment]
I cannot reproduce this on Linux 4.15.12 with the latest stable release of `npm`, v5.8.0:

```
$ git clone https://github.com/AWNICS/mm-node.git
$ cd mm-node/
$ npm install
$ ls
docker-compose.yml  LICENSE       package.json       README.md
Dockerfile          node_modules  package-lock.json  src
```

**Comment by ghost** [comment]
Is it installing all the packages? What is the content of node_modules folder?

The reason I am asking is that I get node_modules folder created at times but the folder is empty.

![image](https://user-images.githubusercontent.com/25379505/37950022-b319e398-31b4-11e8-8f07-5497e8e223ea.png)


Can you also please tell me if the app is running when you do `npm start`?

**Comment by kenany** [comment]
Yup:

```bash
$ ls node_modules/ | wc -l
692
```

Your screenshots show the word "Killed" during the execution of `npm install`, so perhaps _something_ is killing the process before it can extract any packages?

**Comment by ghost** [comment]
Resolved it. There was an issue with resource sharing. I had a memory leak situation in my environment. I had to configure swap in my system to get npm working.

For further details: https://www.digitalocean.com/community/tutorials/how-to-add-swap-on-ubuntu-14-04
