### ISSUE TITLE
NPM install in vagrant returns ERR! syscall mkdir

### ISSUE THREAD

**Issue by andrewgy8** [npm/npm#20179]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [x] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Running Vagrant on MacOSx. Trying to run `npm install @ionic-native/core --save`  returns

```
npm ERR! Linux 4.4.0-98-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "@ionic-native/core" "--save" "--no-bin-links"
npm ERR! node v8.10.0
npm ERR! npm  v4.2.0
npm ERR! path /Projects/node_modules/.staging
npm ERR! code EPROTO
npm ERR! errno -71
npm ERR! syscall mkdir

npm ERR! EPROTO: protocol error, mkdir '/Projects/node_modules/.staging'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/.npm/_logs/2018-03-27T08_42_34_289Z-debug.log
```

#### What I tried

https://github.com/npm/npm/issues/9979

https://github.com/npm/npm/issues/5869

#### How can the CLI team reproduce the problem?

`Vagrant 2.0.1`
`ansible 2.4.3.0`

https://gist.github.com/andrewgy8/be8e861601f8a09ffa6d518cc7b6143b

### supporting information:

 - `npm -v` prints: 4.2.0
 - `node -v` prints: v8.10.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: MacOSx with a Ubuntu 16.04 image
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [x] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by andrewgy8** [comment]
The solution to this was I had mounted my `node_modules` directory to my vagrant box.  The issue with that was I had installed my `node_modules` outside using `sudo npm install`. 

Therefore the ownership of that directory was messed up.  I ended up deleting `node_modules` and then reinstalling inside my vagrant machine.

**Comment by sarbull** [comment]
nice issue.. i am facing the same situation, i am working on an NPM module using vagrant. dayum windows.
