### ISSUE TITLE
npm install is failing repeatedly

### ISSUE THREAD

**Issue by Justin-L-Kratz** [npm/npm#20175]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ x ] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### How can the CLI team reproduce the problem?

I was in the middle of setting up dependencies for a project. I was attempting to download socket.io through npm (v5.6.0). After the installed failed, I was given the following as an error:

843 verbose stack Error: ENOENT: no such file or directory, rename 'C:\Users\Justin\Desktop\Chat\node_modules\bytes' -> 'C:\Users\Justin\Desktop\Chat\node_modules.bytes.DELETE'
844 verbose cwd C:\Users\Justin\Desktop\Chat
845 verbose Windows_NT 10.0.16299
846 verbose argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "express" "--save"
847 verbose node v8.10.0
848 verbose npm v5.6.0
849 error path C:\Users\Justin\Desktop\Chat\node_modules\bytes
850 error code ENOENT
851 error errno -4058
852 error syscall rename
853 error enoent ENOENT: no such file or directory, rename 'C:\Users\Justin\Desktop\Chat\node_modules\bytes' -> 'C:\Users\Justin\Desktop\Chat\node_modules.bytes.DELETE'
854 error enoent This is related to npm not being able to find a file.
855 verbose exit [ -4058, true ]

I'm still quite new to using node, but I did run npm init to set up my package.json file before attempting the download. I also tested this by attempting to download Express and MongoDB. Both downloads failed, so I'm led to believe that this is an issue with npm.
https://gist.github.com/Varogeth/99b990628969a7d94ac6c2c63b2c67f3

-I just tried updating and was met with another error. errno-4048
This error occurred in both Command Prompt and Bash while running as an administrator.
[2018-03-27T01_36_13_922Z-debug.log](https://github.com/npm/npm/files/1850083/2018-03-27T01_36_13_922Z-debug.log)

I will attach a complete log file to this post
### supporting information:

 - `npm -v` prints: npm v5.6.0
 - `node -v` prints: node v8.10.0
 - `npm config get registry` prints: Update available 5.6.0 -> 5.8.0 Run npm i npm to update
 - Windows, OS X/macOS, or Linux?: Windows 10 Home 64-Bit
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ x ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by newuser44** [comment]
I guess kind of similar
Just started to happen and even tried to start with npm all over.  I realize after two days of doing this on and off I'm back to the first problem.

This is on a Mac

pm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/Users/sbrothers/.npm-packages/lib/node_modules/cordova/node_modules/npm/node_modules/ansistyles' -> '/Users/sbrothers/.npm-packages/lib/node_modules/cordova/node_modules/npm/node_modules/.ansistyles.DELETE'

Trying to install an older version of cordova
npm install -g cordova@7.0.1

I thought it was updating npm (that is what the error above seems related to)  it also doesn't want to update

$ npm install -g npm
/Users/sbrothers/.npm-packages/bin/npm -> /Users/sbrothers/.npm-packages/lib/node_modules/npm/bin/npm-cli.js
/Users/sbrothers/.npm-packages/bin/npx -> /Users/sbrothers/.npm-packages/lib/node_modules/npm/bin/npx-cli.js
+ npm@5.8.0
updated 1 package in 5.531s
$ npm -v
5.6.0

What is going on?

**Comment by Justin-L-Kratz** [comment]
To offer some more detailed information, the path "C:\Users\Justin\AppData\Roaming\npm\node_modules\.staging\npm-50055b84\node_modules\ansi-regex" is referenced multiple times in my log file. I'm getting a 'rename' message. The issue with this is that I don't have a ".staging" directory in ..\AppData\Roaming\npm\node_modules. This occurred after uninstalling node v8.10.0, and installing v8.11.0. If it helps, I installed both versions through the .msi at nodejs.org. I'll also include the most recent log file.
[2018-03-29T01_13_45_392Z-debug.log](https://github.com/npm/npm/files/1858340/2018-03-29T01_13_45_392Z-debug.log)

**Comment by aaronhawryluk** [comment]
Same issue, multiple and constant ENOENT errors every single time I try to install or upgrade anything. Tried removing node, deleted cache and config folders, reinstalled, no dice.

[2018-04-02T20_54_01_773Z-debug.log](https://github.com/npm/npm/files/1869701/2018-04-02T20_54_01_773Z-debug.log)
[2018-04-02T21_00_46_535Z-debug.log](https://github.com/npm/npm/files/1869702/2018-04-02T21_00_46_535Z-debug.log)
[2018-04-02T21_16_31_288Z-debug.log](https://github.com/npm/npm/files/1869703/2018-04-02T21_16_31_288Z-debug.log)

Windows 10 x64
Node v8.11.1
npm v5.6.0
npm config get registry: https://registry.npmjs.org/

**Comment by andrejrenard** [comment]
Same error in same environment when trying to load express.
[2018-04-05T09_34_27_435Z-debug.log](https://github.com/npm/npm/files/1879449/2018-04-05T09_34_27_435Z-debug.log)

**Comment by balcsida** [comment]
Hi!

I had the same issue and it was caused by Malwarebytes Anti-Ransomware module: https://forums.malwarebytes.com/topic/224958-blocks-npm-from-working/

They fixed in version 3.4.5.2467: https://forums.malwarebytes.com/topic/225664-malwarebytes-345-patch-release/

I would recommend you to turn off your current AV temporarily and check if the ENOENT errors are still present. If yes, try to add those folders as exclusions and/or consult with your AV vendo.

**Comment by Justin-L-Kratz** [comment]
I had just recently downloaded Malwarebytes, and I think that may just be the issue at hand here. I will try disabling it. If that fixes my issue, I'll close out this thread. If not, I will post a comment to update this thread. Thanks in advance, good sir!

**Comment by andrejrenard** [comment]
Temporarily disabling Malwarebytes did also solve this issue for me.
Unfortunately, the new repaired version of Malwarebytes is not yet
available.

**Comment by balcsida** [comment]
@andrejrenard They released the new version on March 29, which fixes this issue:
https://forums.malwarebytes.com/topic/225664-malwarebytes-345-patch-release/

**Comment by andrejrenard** [comment]
Oh Thanks I was not aware of this manual updatingfeature.

**Comment by Justin-L-Kratz** [comment]
Solved the issue for me, as well. Thanks again!

**Comment by yogsodoth** [comment]
Same here, fixed it by disabling MWB.

**Comment by aaronhawryluk** [comment]
And same here as well.

**Comment by aaronhawryluk** [comment]
Addendum, upgrading MWB to 3.4.5.2467 as mentioned above (by manually downloading) solved the issue permanently. Or at least until the next time MWB changes their ransomware engine. ;-)
