### ISSUE TITLE
Error code EPERM: operation not permitted

### ISSUE THREAD

**Issue by vincentntang** [npm/npm#20171]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [✓] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Cannot install express or any modules. Error code EPERM: operation not permitted

![image](https://user-images.githubusercontent.com/10290348/37919566-38c812b2-30f2-11e8-856e-24e5b03c5c39.png)

#### How can the CLI team reproduce the problem?

- Deleted previous node modules and package.json
- Ran cmd prompt admin in project folder
- `npm init` → pressed ok on everything
- `npm install express` 
- Error Log https://gist.github.com/Kagerjay/07d206d6a4edfcee9466712525471271

### supporting information:

 - `npm -v` prints:  3.10.10
 - `node -v` prints: v6.11.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows
 - Network issues:
   - Geographic location where npm was run: East Coast USA
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unr
e npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by simonua** [comment]
@Kagerjay, you are running fairly old versions of npm and node. Is there any chance you could upgrade to more recent versions and retry?

[NodeJS](https://nodejs.org/en/) - LTS is 8.10.0
[NPM 5.8.0](https://github.com/npm/npm/releases/tag/v5.8.0)

**Comment by vincentntang** [comment]
I updated version nows, but now its stalling on `npm install express` 

![image](https://user-images.githubusercontent.com/10290348/38143303-dcc851d8-340d-11e8-8d84-b104fd606f03.png)

After a minute or two I get several errors `ENOENT: no such file or directory`

![image](https://user-images.githubusercontent.com/10290348/38143324-f0de9e2a-340d-11e8-9ed7-8a98a0d697d1.png)

NPM debug log here

https://gist.github.com/Kagerjay/60632df6c9d88eb1cbe8c1003899a05b

**Comment by vincentntang** [comment]
okay I figured it out malware bytes was the issue
