### ISSUE TITLE
Error while installing npm install -g cardova

### ISSUE THREAD

**Issue by gmptr5797** [npm/npm#20181]
I am getting below response while I am trying to install 
npm install -g cardova
npm ERR! code E404
npm ERR! 404 Not Found: cardova@latest

------Versions----------
node -v returns v8.9.4
npm -v returns 5.6.0
ionic -v 3.20.0

Tried uninstalling cardova and installing it again, but it didn't help

**Comment by talyssonoc** [comment]
The package `cardova` doens't exist (https://www.npmjs.com/package/cardova), maybe you meant `cordova` instead? :smile:
