### ISSUE TITLE
Can't publish package with `-` in name

### ISSUE THREAD

**Issue by up9cloud** [npm/npm#20199]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I tried to publish by following names,  but all not work (`Package name triggered spam detection; if you believe this is in error, please contact support@npmjs.com : `)

- graphql-tools-type-int64
- graphql-type-int64
- graphql-tools-type-int52
- graphql-type-int52

<details>
  <summary>Click to show my rude namings (sorry about that)</summary>

graphql-tools-type-int64-wtf-npm
graphql-tools-type-int64-wwttff-npm
fnpm-graphql-tools-type-int64
graphql-tools-type-int64-npm-spam-is-suck
graphql-tools-type-int64-npm-spam-is-a-____

</details>

- raphql-tools-type-int64
- raphql-ools-ype-nt64
- graphql-tools-type-int64-yfMYz2uOUpXOVcqRBRmWSFUz
- graphql-tools-type-int64-Ela1sBKM
- A7gKzyyB-graphql-tools-type-int64
- g-r-a-p-h-q-l-tools-type-int64

Finally, this one works

`graphqltoolstypeint64`

I guess it might `-` in name is not allowed .

Would you mind removing `-` from the black list?

I really like `-`

Thanks.

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
I think you should take this to <https://github.com/npm/registry>

**Comment by up9cloud** [comment]
I post there and got the reply, so close this.
