### ISSUE TITLE
(node:8484) UnhandledPromiseRejectionWarning: Error: Exited with code 1

### ISSUE THREAD

**Issue by deshpandecounsultants** [npm/npm#20204]
When I try to execute `ng serve --o` following error occurs after exception dialog box. (refer attached image file)

** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
Date: 2018-03-30T07:56:47.892Z
Hash: c929ff7cb13ec509d8e3
Time: 7466ms
chunk {inline} inline.bundle.js (inline) 3.85 kB [entry] [rendered]
chunk {main} main.bundle.js (main) 15.2 kB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js (polyfills) 598 kB [initial] [rendered]
chunk {styles} styles.bundle.js (styles) 41.5 kB [initial] [rendered]
chunk {vendor} vendor.bundle.js (vendor) 7.42 MB [initial] [rendered]

webpack: Compiled successfully.
(node:8484) UnhandledPromiseRejectionWarning: Error: Exited with code 1
    at ChildProcess.cp.once.code (C:\Angular 5\myFirst\node_modules\opn\index.js:82:13)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:567:12)
(node:8484) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8484) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
![error](https://user-images.githubusercontent.com/7194206/38129718-cbdbc2d2-341d-11e8-8b4d-72083f620107.PNG)

**Comment by kenany** [comment]
This error does not appear to be coming from `npm`. I suggest you take this to StackOverflow instead.
