### ISSUE TITLE
npm will not start check error message

### ISSUE THREAD

**Issue by Tobzzy** [npm/npm#20219]
npm ERR! Linux 4.13.0-37-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.14.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! memory@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the memory@0.0.0 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the memory package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs memory
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls memory
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ahmed/memory/npm-debug.log

**Comment by kenany** [comment]
As the error log indicates, this error is coming from

```
node ./bin/www
```

**not** `npm` itself. Ensure that the above command runs without error from your command-line.

**Comment by Tobzzy** [comment]
here are the errors 
ahmed@ahmed-HP-EliteBook-820-G1:~$ node ./bin/www
module.js:478
    throw err;
    ^

Error: Cannot find module '/home/ahmed/bin/www'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:387:7)
    at startup (bootstrap_node.js:153:9)
    at bootstrap_node.js:500:3

i am really new to npm so i dont know how to go about it

**Comment by kenany** [comment]
Looks like `./bin/www` does not exist. Therefore, you are trying to execute a file which does not exist, so Node.js throws an error.
