### ISSUE TITLE
NPM Repo Certificates Failing

### ISSUE THREAD

**Issue by justinstander** [npm/npm#20218]
#### I'm opening this issue because:

  - npm is rejecting repository certificates

#### How can the CLI team reproduce the problem?

npm install -g n

AWS CodeBuild Latest Ubuntu Image

### supporting information:

[Container] 2018/03/31 15:16:37 Running command npm install -g n
npm http GET https://registry.npmjs.org/n
npm http GET https://registry.npmjs.org/n
npm http GET https://registry.npmjs.org/n
npm ERR! Error: CERT_UNTRUSTED
npm ERR! at SecurePair.<anonymous> (tls.js:1370:32)
npm ERR! at SecurePair.EventEmitter.emit (events.js:92:17)
npm ERR! at SecurePair.maybeInitFinished (tls.js:982:10)
npm ERR! at CleartextStream.read [as _read] (tls.js:469:13)
npm ERR! at CleartextStream.Readable.read (_stream_readable.js:320:10)
npm ERR! at EncryptedStream.write [as _write] (tls.js:366:25)
npm ERR! at doWrite (_stream_writable.js:223:10)
npm ERR! at writeOrBuffer (_stream_writable.js:213:5)
npm ERR! at EncryptedStream.Writable.write (_stream_writable.js:180:11)
npm ERR! at write (_stream_readable.js:583:24)
npm ERR! If you need help, you may report this log at:
npm ERR! <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR! <npm-@googlegroups.com>

npm ERR! System Linux 4.9.81-35.56.amzn1.x86_64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "n"
npm ERR! cwd /codebuild/output/src041361309/src
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR! /codebuild/output/src041361309/src/npm-debug.log
npm ERR! not ok code 0

[Container] 2018/03/31 15:17:48 Command did not exit successfully npm install -g n exit status 1
[Container] 2018/03/31 15:17:48 Phase complete: INSTALL Success: false
[Container] 2018/03/31 15:17:48 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: npm install -g n. Reason: exit status 1

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
Your versions of Node.js and `npm` are years old and are no longer supported.
