### ISSUE TITLE
npm is crashing.

### ISSUE THREAD

**Issue by logicware** [npm/npm#20226]
#### I'm opening this issue because:

  - [x] npm is crashing.

#### What's going wrong?

Here are the logs:

Preparing Dependency Cache
Preparing Virtual Machine
rm -rf node_modules
nvm install 0.10.25
nvm use 0.10.25
npm install
npm http GET https://registry.npmjs.org/ejs/0.8.4
npm http GET https://registry.npmjs.org/express/3.3.5
npm http GET https://registry.npmjs.org/express-useragent
npm http GET https://registry.npmjs.org/gridfs-stream/0.4.0
npm http GET https://registry.npmjs.org/grunt
npm http GET https://registry.npmjs.org/grunt-cli
npm http GET https://registry.npmjs.org/grunt-contrib-uglify
npm http GET https://registry.npmjs.org/grunt-karma
npm http GET https://registry.npmjs.org/jsonwebtoken
npm http GET https://registry.npmjs.org/jwt-simple
npm http GET https://registry.npmjs.org/karma
npm http GET https://registry.npmjs.org/karma-chrome-launcher
npm http GET https://registry.npmjs.org/karma-jasmine
npm http GET https://registry.npmjs.org/mime/1.2.11
npm http GET https://registry.npmjs.org/mocha
npm http GET https://registry.npmjs.org/morgan
npm http GET https://registry.npmjs.org/movable-js/0.0.1
npm http GET https://registry.npmjs.org/mysql
npm http GET https://registry.npmjs.org/newrelic
npm http GET https://registry.npmjs.org/node-customerio/0.0.5
npm http GET https://registry.npmjs.org/node-pusher/0.0.2
npm http GET https://registry.npmjs.org/node-schedule
npm http GET https://registry.npmjs.org/nodemailer/0.5.2
npm http GET https://registry.npmjs.org/numeral
npm http GET https://registry.npmjs.org/passport/0.1.17
npm http GET https://registry.npmjs.org/passport-local/0.1.6
npm http GET https://registry.npmjs.org/pg
npm http GET https://registry.npmjs.org/pg-hstore
npm http GET https://registry.npmjs.org/q/0.9.7
npm http GET https://registry.npmjs.org/bower
npm http GET https://registry.npmjs.org/dateformat
npm http GET https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/sequelize/2.0.3
npm http GET https://registry.npmjs.org/should
npm http GET https://registry.npmjs.org/simple-recaptcha/0.0.3
npm http GET https://registry.npmjs.org/superagent
npm http GET https://registry.npmjs.org/supertest
npm http GET https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/uuid
npm http GET https://registry.npmjs.org/uuid-js
npm http GET https://registry.npmjs.org/winston
npm http GET https://registry.npmjs.org/expect.js
npm http GET https://registry.npmjs.org/jasmine-core
npm http GET https://registry.npmjs.org/amqp
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/crypto/0.0.3
npm http GET https://registry.npmjs.org/express/3.3.5
npm http GET https://registry.npmjs.org/express-useragent
npm http GET https://registry.npmjs.org/gridfs-stream/0.4.0
npm http GET https://registry.npmjs.org/ejs/0.8.4
npm http GET https://registry.npmjs.org/grunt
npm http GET https://registry.npmjs.org/grunt-contrib-uglify
npm http GET https://registry.npmjs.org/grunt-karma
npm http GET https://registry.npmjs.org/jsonwebtoken
npm http GET https://registry.npmjs.org/grunt-cli
npm http GET https://registry.npmjs.org/jwt-simple
npm http GET https://registry.npmjs.org/karma-jasmine
npm http GET https://registry.npmjs.org/mime/1.2.11
npm http GET https://registry.npmjs.org/mocha
npm http GET https://registry.npmjs.org/karma-chrome-launcher
npm http GET https://registry.npmjs.org/karma
npm http GET https://registry.npmjs.org/morgan
npm http GET https://registry.npmjs.org/node-customerio/0.0.5
npm http GET https://registry.npmjs.org/mysql
npm http GET https://registry.npmjs.org/movable-js/0.0.1
npm http GET https://registry.npmjs.org/newrelic
npm http GET https://registry.npmjs.org/numeral
npm http GET https://registry.npmjs.org/nodemailer/0.5.2
npm http GET https://registry.npmjs.org/node-schedule
npm http GET https://registry.npmjs.org/node-pusher/0.0.2
npm http GET https://registry.npmjs.org/passport/0.1.17
npm http GET https://registry.npmjs.org/pg-hstore
npm http GET https://registry.npmjs.org/q/0.9.7
npm http GET https://registry.npmjs.org/bower
npm http GET https://registry.npmjs.org/passport-local/0.1.6
npm http GET https://registry.npmjs.org/pg
npm http GET https://registry.npmjs.org/sequelize/2.0.3
npm http GET https://registry.npmjs.org/should
npm http GET https://registry.npmjs.org/dateformat
npm http GET https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/simple-recaptcha/0.0.3
npm http GET https://registry.npmjs.org/uuid
npm http GET https://registry.npmjs.org/supertest
npm http GET https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/superagent
npm http GET https://registry.npmjs.org/uuid-js
npm http GET https://registry.npmjs.org/expect.js
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/jasmine-core
npm http GET https://registry.npmjs.org/winston
npm http GET https://registry.npmjs.org/amqp
npm http GET https://registry.npmjs.org/crypto/0.0.3
npm http GET https://registry.npmjs.org/express-useragent
npm http GET https://registry.npmjs.org/express/3.3.5
npm http GET https://registry.npmjs.org/ejs/0.8.4
npm http GET https://registry.npmjs.org/grunt
npm http GET https://registry.npmjs.org/gridfs-stream/0.4.0
npm http GET https://registry.npmjs.org/jsonwebtoken
npm http GET https://registry.npmjs.org/grunt-cli
npm http GET https://registry.npmjs.org/jwt-simple
npm http GET https://registry.npmjs.org/grunt-karma
npm http GET https://registry.npmjs.org/grunt-contrib-uglify
npm http GET https://registry.npmjs.org/karma-jasmine
npm http GET https://registry.npmjs.org/karma
npm http GET https://registry.npmjs.org/mocha
npm http GET https://registry.npmjs.org/karma-chrome-launcher
npm http GET https://registry.npmjs.org/mime/1.2.11
npm ERR! Error: CERT_UNTRUSTED
npm ERR!     at SecurePair.<anonymous> (tls.js:1370:32)
npm ERR!     at SecurePair.EventEmitter.emit (events.js:92:17)
npm ERR!     at SecurePair.maybeInitFinished (tls.js:982:10)
npm ERR!     at CleartextStream.read [as _read] (tls.js:469:13)
npm ERR!     at CleartextStream.Readable.read (_stream_readable.js:320:10)
npm ERR!     at EncryptedStream.write [as _write] (tls.js:366:25)
npm ERR!     at doWrite (_stream_writable.js:223:10)
npm ERR!     at writeOrBuffer (_stream_writable.js:213:5)
npm ERR!     at EncryptedStream.Writable.write (_stream_writable.js:180:11)
npm ERR!     at write (_stream_readable.js:583:24)
npm ERR!     at flow (_stream_readable.js:592:7)
npm ERR!     at Socket.pipeOnReadable (_stream_readable.js:624:5)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/isaacs/npm/issues>

npm ERR! System Linux 4.4.0-116-generic
npm ERR! command "/home/rof/.nvm/v0.10.25/bin/node" "/home/rof/.nvm/v0.10.25/bin/npm" "install"
npm ERR! cwd /home/rof/src/github.com/CalorieCloud/kpc-main
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.24
npm http GET https://registry.npmjs.org/morgan
npm http GET https://registry.npmjs.org/node-customerio/0.0.5
npm http GET https://registry.npmjs.org/movable-js/0.0.1
npm http GET https://registry.npmjs.org/newrelic
npm http GET https://registry.npmjs.org/mysql
npm http GET https://registry.npmjs.org/node-schedule
npm http GET https://registry.npmjs.org/nodemailer/0.5.2
npm http GET https://registry.npmjs.org/node-pusher/0.0.2
npm http GET https://registry.npmjs.org/numeral
npm http GET https://registry.npmjs.org/passport/0.1.17
npm http GET https://registry.npmjs.org/pg-hstore
npm http GET https://registry.npmjs.org/bower
npm http GET https://registry.npmjs.org/q/0.9.7
npm http GET https://registry.npmjs.org/passport-local/0.1.6
npm http GET https://registry.npmjs.org/pg
npm http GET https://registry.npmjs.org/should
npm http GET https://registry.npmjs.org/dateformat
npm http GET https://registry.npmjs.org/sequelize/2.0.3
npm http GET https://registry.npmjs.org/simple-recaptcha/0.0.3
npm http GET https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/superagent
npm http GET https://registry.npmjs.org/supertest
npm http GET https://registry.npmjs.org/uuid
npm http GET https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/uuid-js
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/expect.js
npm http GET https://registry.npmjs.org/winston
npm http GET https://registry.npmjs.org/jasmine-core
npm http GET https://registry.npmjs.org/amqp
npm http GET https://registry.npmjs.org/crypto/0.0.3
npm ERR! 
npm ERR! not ok code 0
Scroll to bottom
AboutTermsPrivacy

**Comment by ngr** [comment]
Having similar problem started yesterday.
Running on Amazon Linux AMI 2017.09, if this is important.
The temporary workaround was to use: `npm config set strict-ssl false`.

**Comment by logicware** [comment]
@ngr It's not working for me. I tried both the .npmrc and package.json, but it failed to resolve the issue.

**Comment by kenany** [comment]
Your versions of Node.js and `npm` are years old and are no longer supported.

**Comment by logicware** [comment]
Why is it installing the old version? My package.json has:
```
"engines": {
    "node": "4.8.4"
  }
```

**Comment by kenany** [comment]
It's not up to `npm` to install Node.js for you. Your log indicates that `nvm` is being used to _explicitly_ install an outdated version of Node.js:

```
Preparing Dependency Cache
Preparing Virtual Machine
rm -rf node_modules
nvm install 0.10.25
nvm use 0.10.25
```
