### ISSUE TITLE
npm install gir Error: CERT_UNTRUSTED

### ISSUE THREAD

**Issue by eosrc** [npm/npm#20221]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ 
[npm-debug.log](https://github.com/npm/npm/files/1866316/npm-debug.log)
] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
Your version of Node.js is years old and is no longer supported.

**Comment by eosrc** [comment]
Thanks for the quick reply. I realized that it might be the problem
but my local version is v8.9.3. It is the sudo version which I haven't
changed.

**Comment by ottok** [comment]
This is a duplicate of https://github.com/npm/npm/issues/20191 as well.
