### ISSUE TITLE
npm adduser respond 404 for private registry

### ISSUE THREAD

**Issue by crusoexia** [npm/npm#20220]
#### I'm opening this issue because:

  - [x] npm is doing something I don't understand.

#### What's going wrong?

Try to publish to private registry, when fill the user, password and email by `npm adduser`, it respond E404:

```
npm ERR! code E404
npm ERR! 404 Registry returned 404 for PUT on https://artifacts.xxx.xxx.com/artifactory/api/npm/-/user/org.couchdb.user:cxia
npm ERR! 404
npm ERR! 404  'org.couchdb.user:cxia' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because
npm ERR! 404  1. name can only contain URL-friendly characters
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

I registered user on the official registry 'registry.npmjs.org' on the same Mac, and can publish package to public registry without problem. Not sure whether above issue is caused by any conflict.

#### How can the CLI team reproduce the problem?

I'm afraid you can not.

### supporting information:

 - `npm -v` prints: 5.8.0
 - `node -v` prints: v8.9.0
 - `npm config get registry` prints: https://artifacts.dev.xxx.com/artifactory/api/npm/npmjs
 - Windows, OS X/macOS, or Linux?: macOS
 - Network issues:
   - Geographic location where npm was run:
   - [x] I access the npm registry via a VPN
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by crusoexia** [comment]
This is due to the authentication setting of the private npm registry. Close it as it is not relate to the npm itself.

**Comment by nwronski** [comment]
@crusoexia hey, we have run into this same issue. could you let us know what configuration needed to be changed to resolve the error?

**Comment by crusoexia** [comment]
@nwronski it’s caused by our npm registry’s publish permission setting. Our SCM team don’t want anyone can publish package to it. They give me a token for the publish ang it worked.
