### ISSUE TITLE
npm ERR! Error: CERT_UNTRUSTED in node version 0.10.24

### ISSUE THREAD

**Issue by npatod** [npm/npm#20235]
#### I'm opening this issue because:

  - [1] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Not able to install package via npm in node version 0.10.24.
Getting error : CERT_UNTRUSTED 
Temporary fix : 1)use   http://registry.npmjs.org/        
                        2)use higher version of nodejs         

#### How can the CLI team reproduce the problem?

    npm install jshint
npm WARN package.json ffservice-deals@0.0.1 No README data
npm WARN package.json bcrypt-pbkdf@1.0.1 No repository field.
npm WARN package.json eyes@0.1.8 No repository field.
npm WARN package.json mysequel@0.0.5 No repository field.
npm WARN package.json punycode@1.4.1 punycode is also the name of a node core module.
npm WARN package.json querystring@0.2.0 querystring is also the name of a node core module.
npm WARN package.json string_decoder@1.0.3 string_decoder is also the name of a node core module.
npm WARN package.json swagger-schema-official@2.0.0-bab6bed No repository field.
npm WARN package.json url@0.11.0 url is also the name of a node core module.
npm http GET https://registry.npmjs.org/jshint
npm http GET https://registry.npmjs.org/jshint
npm http GET https://registry.npmjs.org/jshint
npm ERR! Error: CERT_UNTRUSTED
npm ERR!     at SecurePair.<anonymous> (tls.js:1370:32)
npm ERR!     at SecurePair.EventEmitter.emit (events.js:92:17)
npm ERR!     at SecurePair.maybeInitFinished (tls.js:982:10)
npm ERR!     at CleartextStream.read [as _read] (tls.js:469:13)
npm ERR!     at CleartextStream.Readable.read (_stream_readable.js:320:10)
npm ERR!     at EncryptedStream.write [as _write] (tls.js:366:25)
npm ERR!     at doWrite (_stream_writable.js:221:10)
npm ERR!     at writeOrBuffer (_stream_writable.js:211:5)
npm ERR!     at EncryptedStream.Writable.write (_stream_writable.js:180:11)
npm ERR!     at write (_stream_readable.js:583:24)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/isaacs/npm/issues>

npm ERR! System Linux 4.4.0-116-generic
npm ERR! command "/home/nagendrapatod/.nvm/v0.10.24/bin/node" "/home/nagendrapatod/.nvm/v0.10.24/bin/npm" "install" "jshint"
npm ERR! cwd /var/www/paytm/ffservice-deals
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.3.21
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /var/www/paytm/ffservice-deals/npm-debug.log
npm ERR! not ok code 0

### supporting information:

 - `npm -v` prints:    1.3.21                     
 - `node -v` prints:   v0.10.24
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux-ubuntu-16.04
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
Your versions of Node.js and `npm` are years old and are no longer supported.

**Comment by npatod** [comment]
Thanks Kenany for giving attention on my issue.
Our build process working fine a week before .But now we are facing this certificate issue.
As I can see some certificate issue date (Thursday, 15 March 2018 at 19:09:52) on https://registry.npmjs.org .
can you please let me know something changed  recently which causes this issue.

**Comment by kenany** [comment]
I think something did change on the registry side of things, because a lot of people have been opening up issues about this recently.

**Comment by ottok** [comment]
This is a duplicate of https://github.com/npm/npm/issues/20191
