### ISSUE TITLE
Cannot install from gist.github.com

### ISSUE THREAD

**Issue by ykyuen** [npm/npm#20243]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [x] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Recently i found that the `npm install` of my node project start failing. In the `package.json`, i have a gist dependency. ex.:
```json
"dependencies": {
    "flickity": "2.0.5",
    "flickity-legacy": "https://gist.github.com/ee1d2791e5ed8bf88664c16e95bb1da3.git",
    ...
},
```

When i ran `npm install`, the following error was found in the `npm-debug.log`

```
npm ERR! code ENOPACKAGEJSON
npm ERR! package.json Non-registry package missing package.json: flickity-legacy@git+https://gist.github.com/ee1d2791e5ed8bf88664c16e95bb1da3.git.
npm ERR! package.json npm can't find a package.json file in your current directory.
```

According to the [npm doc](https://docs.npmjs.com/cli/install), I also tried to install the package from gist thru command line but similar error was found.

```
$ npm install gist:ee1d2791e5ed8bf88664c16e95bb1da3 --save
npm ERR! code ENOPACKAGEJSON
npm ERR! package.json Non-registry package missing package.json: gist:ee1d2791e5ed8bf88664c16e95bb1da3.
npm ERR! package.json npm can't find a package.json file in your current directory.
```

#### How can the CLI team reproduce the problem?

simply run `npm install gist:ee1d2791e5ed8bf88664c16e95bb1da3 --save` in command line.

### supporting information:

 - `npm -v` prints: 5.6.0
 - `node -v` prints: v8.9.4
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
The error message indicates that the gist does not contain a `package.json`. All packages must have this file, but since your gist does not, `npm` throws an error as intended.
