### ISSUE TITLE
 cb() never called!

### ISSUE THREAD

**Issue by sunmorg** [npm/npm#20244]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

 cb() never called!

**Comment by tracygjgscisys** [comment]
Encountered this error during a project reinstall via Verdaccio with Node 9.9.0 and npm 5.6.0. Logfile attached.
[2018-04-03T09_26_40_147Z-debug.log](https://github.com/npm/npm/files/1870944/2018-04-03T09_26_40_147Z-debug.log)
Cleared the node_modules folder and tried again - worked.

**Comment by kenany** [comment]
@sunmorg Could you please fill out the form in your post? The more details the better. Thanks!

**Comment by kenany** [comment]
Closing due to no reply after a month. "cb() never called!" is a symptom of a bug but without more details it is very difficult to debug.
