### ISSUE TITLE
Refusing to install as a dependency of itself

### ISSUE THREAD

**Issue by psujeeve** [npm/npm#20246]
I'm trying to run below given project from git hub, 
https://github.com/jonsamwell/ngx-http-batcher

When I'm executing command "npm install ngx-http-batcher --save" Im getting below error,
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "ngx-http-batcher" "--
save"
npm ERR! node v6.9.0
npm ERR! npm  v3.10.8
npm ERR! code ENOSELF
npm ERR! Refusing to install ngx-http-batcher as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\attpasu1\.npm-packages\ngx-http-batcher-master\npm-debug.log

you can see npm-debug.log as below,

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'ngx-http-batcher',
1 verbose cli   '--save' ]
2 info using npm@3.10.8
3 info using node@v6.9.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData ngx-http-batcher
8 silly fetchNamedPackageData ngx-http-batcher
9 silly mapToRegistry name ngx-http-batcher
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'ngx-http-batcher',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'ngx-http-batcher',
12 silly mapToRegistry   name: 'ngx-http-batcher',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/ngx-http-batcher
14 verbose request uri https://registry.npmjs.org/ngx-http-batcher
15 verbose request no auth needed
16 info attempt registry request try #1 at 5:32:52 PM
17 verbose request id 497febc4bdc28848
18 verbose etag "5a25f4cc-92ab"
19 verbose lastModified Tue, 5 Dec 2017 1:22:20 GMT
20 http request GET https://registry.npmjs.org/ngx-http-batcher
21 http 304 https://registry.npmjs.org/ngx-http-batcher
22 verbose headers { date: 'Tue, 03 Apr 2018 09:32:53 GMT',
22 verbose headers   via: '1.1 varnish, HTTPS/1.1 localhost.localdomain',
22 verbose headers   'cache-control': 'max-age=300',
22 verbose headers   etag: '"5a25f4cc-92ab"',
22 verbose headers   age: '7616',
22 verbose headers   'x-served-by': 'cache-sin18035-SIN',
22 verbose headers   'x-cache': 'HIT',
22 verbose headers   'x-cache-hits': '3',
22 verbose headers   'x-timer': 'S1522747973.140175,VS0,VE0',
22 verbose headers   vary: 'Accept-Encoding, Accept',
22 verbose headers   connection: 'close' }
23 silly get cb [ 304,
23 silly get   { date: 'Tue, 03 Apr 2018 09:32:53 GMT',
23 silly get     via: '1.1 varnish, HTTPS/1.1 localhost.localdomain',
23 silly get     'cache-control': 'max-age=300',
23 silly get     etag: '"5a25f4cc-92ab"',
23 silly get     age: '7616',
23 silly get     'x-served-by': 'cache-sin18035-SIN',
23 silly get     'x-cache': 'HIT',
23 silly get     'x-cache-hits': '3',
23 silly get     'x-timer': 'S1522747973.140175,VS0,VE0',
23 silly get     vary: 'Accept-Encoding, Accept',
23 silly get     connection: 'close' } ]
24 verbose etag https://registry.npmjs.org/ngx-http-batcher from cache
25 verbose get saving ngx-http-batcher to C:\Users\attpasu1\AppData\Roaming\npm-cache\registry.npmjs.org\ngx-http-batcher\.cache.json
26 verbose correctMkdir C:\Users\attpasu1\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
27 silly install normalizeTree
28 silly loadCurrentTree Finishing
29 silly loadIdealTree Starting
30 silly install loadIdealTree
31 silly cloneCurrentTree Starting
32 silly install cloneCurrentTreeToIdealTree
33 silly cloneCurrentTree Finishing
34 silly loadShrinkwrap Starting
35 silly install loadShrinkwrap
36 silly loadShrinkwrap Finishing
37 silly loadAllDepsIntoIdealTree Starting
38 silly install loadAllDepsIntoIdealTree
39 silly rollbackFailedOptional Starting
40 silly rollbackFailedOptional Finishing
41 silly runTopLevelLifecycles Finishing
42 silly install printInstalled
43 verbose stack Error: Refusing to install ngx-http-batcher as a dependency of itself
43 verbose stack     at checkSelf (C:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:53:14)
43 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
43 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
43 verbose stack     at chain (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
43 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:16:5
43 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
43 verbose stack     at Array.forEach (native)
43 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
43 verbose stack     at Array.forEach (native)
43 verbose stack     at asyncMap (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
44 verbose cwd C:\Users\attpasu1\.npm-packages\ngx-http-batcher-master
45 error Windows_NT 6.1.7601
46 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "ngx-http-batcher" "--save"
47 error node v6.9.0
48 error npm  v3.10.8
49 error code ENOSELF
50 error Refusing to install ngx-http-batcher as a dependency of itself
51 error If you need help, you may report this error at:
51 error     <https://github.com/npm/npm/issues>
52 verbose exit [ 1, true ]

Please advise to resolve this issue. thanks in advance

**Comment by kenany** [comment]
You are trying to install `ngx-http-batcher` within itself, which is not supported. This would create a cyclical dependency and that is probably not what you are aiming to do anyways. I believe what you should be doing is running the command from within _your own project's_ directory instead.

**Comment by psujeeve** [comment]
Hi KenanY, 
Thank you I did same. but still facing problem on running below github project 
https://github.com/jonsamwell/ngx-http-batcher 

Could you tell me the steps, if you could run this project 

Thanks

**Comment by psujeeve** [comment]
Yeah got resolved. after updating node version to latest LTS vesion and running the command from out of project directory.
