### ISSUE TITLE
When i run 'npm test' command it throws me below erro

### ISSUE THREAD

**Issue by Sushmaemmadi** [npm/npm#20254]
#### I'm opening this issue because:
I have trying to set Appium on mac. When i run 'appium-doctor -h' it works perfect, so error observed.
  - But on executing 

$ npm test ...it throws me below error:  

#### What's going wrong?

npm ERR! path /Users/emmadsu1/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/Users/emmadsu1/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/emmadsu1/.npm/_logs/2018-04-04T06_49_26_752Z-debug.log

**Comment by kenany** [comment]
Does `/Users/emmadsu1/package.json` exist?

**Comment by kenany** [comment]
Closing due to no reply after a month.
