### ISSUE TITLE
npm ERR! Error: CERT_UNTRUSTED and npm ERR! Error: ENOENT, stat 'angular/cli'

### ISSUE THREAD

**Issue by morepallavi** [npm/npm#20263]
krunali@krunali-ThinkPad-L412:~$ sudo npm install -g typescript
npm http GET https://registry.npmjs.org/typescript
npm http GET https://registry.npmjs.org/typescript
npm http GET https://registry.npmjs.org/typescript
npm ERR! Error: CERT_UNTRUSTED
npm ERR!     at SecurePair.<anonymous> (tls.js:1370:32)
npm ERR!     at SecurePair.EventEmitter.emit (events.js:92:17)
npm ERR!     at SecurePair.maybeInitFinished (tls.js:982:10)
npm ERR!     at CleartextStream.read [as _read] (tls.js:469:13)
npm ERR!     at CleartextStream.Readable.read (_stream_readable.js:320:10)
npm ERR!     at EncryptedStream.write [as _write] (tls.js:366:25)
npm ERR!     at doWrite (_stream_writable.js:223:10)
npm ERR!     at writeOrBuffer (_stream_writable.js:213:5)
npm ERR!     at EncryptedStream.Writable.write (_stream_writable.js:180:11)
npm ERR!     at write (_stream_readable.js:583:24)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.4.0-31-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "typescript"
npm ERR! cwd /home/krunali
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/krunali/npm-debug.log
npm ERR! not ok code 0
krunali@krunali-ThinkPad-L412:~$ clear

krunali@krunali-ThinkPad-L412:~$ sudo npm install -g typescript
npm http GET https://registry.npmjs.org/typescript
npm http GET https://registry.npmjs.org/typescript
npm http GET https://registry.npmjs.org/typescript
npm ERR! Error: CERT_UNTRUSTED
npm ERR!     at SecurePair.<anonymous> (tls.js:1370:32)
npm ERR!     at SecurePair.EventEmitter.emit (events.js:92:17)
npm ERR!     at SecurePair.maybeInitFinished (tls.js:982:10)
npm ERR!     at CleartextStream.read [as _read] (tls.js:469:13)
npm ERR!     at CleartextStream.Readable.read (_stream_readable.js:320:10)
npm ERR!     at EncryptedStream.write [as _write] (tls.js:366:25)
npm ERR!     at doWrite (_stream_writable.js:223:10)
npm ERR!     at writeOrBuffer (_stream_writable.js:213:5)
npm ERR!     at EncryptedStream.Writable.write (_stream_writable.js:180:11)
npm ERR!     at write (_stream_readable.js:583:24)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.4.0-31-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "typescript"
npm ERR! cwd /home/krunali
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/krunali/npm-debug.log
npm ERR! not ok code 0
krunali@krunali-ThinkPad-L412:~$ sudo npm install -g @angular/cli
npm ERR! git clone git@github.com:angular/cli Cloning into bare repository '/home/krunali/.npm/_git-remotes/git-github-com-angular-cli-515723dd'...
npm ERR! git clone git@github.com:angular/cli Permission denied (publickey).
npm ERR! git clone git@github.com:angular/cli fatal: Could not read from remote repository.
npm ERR! git clone git@github.com:angular/cli 
npm ERR! git clone git@github.com:angular/cli Please make sure you have the correct access rights
npm ERR! git clone git@github.com:angular/cli and the repository exists.
npm ERR! addLocal Could not install angular/cli
npm ERR! Error: ENOENT, stat 'angular/cli'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.4.0-31-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "@angular/cli"
npm ERR! cwd /home/krunali
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path angular/cli
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/krunali/npm-debug.log
npm ERR! not ok code 0
krunali@krunali-ThinkPad-L412:~$

**Comment by morepallavi** [comment]
I am facing above issue when I try to install typescript and angular.

**Comment by geoffccharlton** [comment]
I m also getting this message when trying to install npm.
npm ERR! Error: CERT_UNTRUSTED
npm ERR!     at SecurePair.<anonymous> (tls.js:1370:32)
npm ERR!     at SecurePair.EventEmitter.emit (events.js:92:17)
npm ERR!     at SecurePair.maybeInitFinished (tls.js:982:10)
npm ERR!     at CleartextStream.read [as _read] (tls.js:469:13)
npm ERR!     at CleartextStream.Readable.read (_stream_readable.js:320:10)
npm ERR!     at EncryptedStream.write [as _write] (tls.js:366:25)
npm ERR!     at doWrite (_stream_writable.js:223:10)
npm ERR!     at writeOrBuffer (_stream_writable.js:213:5)
npm ERR!     at EncryptedStream.Writable.write (_stream_writable.js:180:11)
npm ERR!     at write (_stream_readable.js:583:24)
npm ERR!     at flow (_stream_readable.js:592:7)
npm ERR!     at Socket.pipeOnReadable (_stream_readable.js:624:5)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

**Comment by kenany** [comment]
@morepallavi Your versions of Node.js and `npm` are years old and are no longer supported.

**Comment by ottok** [comment]
This is a duplicate of https://github.com/npm/npm/issues/20191
