### ISSUE TITLE
 Please include the following file with any support request:

### ISSUE THREAD

**Issue by NiteshKhandal** [npm/npm#20262]
npm ERR! tar.unpack unzip error /var/folders/mx/t4hy_rbn5996nzhgq6lbdb8m0000gn/T/npm-4282-33b0b329/github.com/expo/react-native-maps/archive/0.20.1-exp.0.tar.gz
npm ERR! Darwin 17.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save"
npm ERR! node v7.7.1
npm ERR! npm  v4.1.2
npm ERR! code Z_BUF_ERROR
npm ERR! errno -5

npm ERR! unexpected end of file
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/rachitbagda/Desktop/ReactNiteshProject/npm-debug.log
Failed to install

**Comment by kenany** [comment]
Does this also occur with the latest stable releases of Node.js and `npm`?

(Also, you probably should not be using Node.js v7 anymore, since it "turned into" v8 a long time ago.)

**Comment by kenany** [comment]
Closing due to no reply after a month.
