### ISSUE TITLE
how to React jsx component code in Java script file

### ISSUE THREAD

**Issue by sandeepthukran** [npm/npm#20271]
#### I'm opening this issue because:
Hello Everyone.

I need to use a Modal dialog that was created as react component. now i need to use this component in reducer file that is a JS file. there i am not able call that modal dialog.
Now i am able to call the React js component in JS file using React.CreateElement.
But now when i am pressing button of modal dialog, click event is called but it is not closing the modal dialog.  Please suggest is it my approach is correct to call modal dialog in js file?
Could any help me on this.

Code of Sample.js file:-
let app = document.getElementById('react-view');
  if (!app) {
    app = document.createElement('div');
    app.id = 'react-view';
    window.document.body.appendChild(app);
  }
  const setProps = {
    isOpen: true,
    success: message,
    onRequestClose: onBtnOk,
  };

  const SPMessage = React.createElement(SPSuccessModal, { ...setProps }, null));
  ReactDom.render(SPMessage, app);

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] npm is producing incorrect or undesirable behavior.
  - [x] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
I suggest you ask this on StackOverflow.
