### ISSUE TITLE
error: CERT_UNTRUSTED when  installing iobroker on LinuxMint

### ISSUE THREAD

**Issue by wolger** [npm/npm#20288]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] npm is producing incorrect or undesirable behavior.
  - [ x] Other (_see below for feature requests_):

#### What's going wrong?
When I try to install iobroker on Linux Mint with 'sudo npm install iobroker --unsafe-perm'
I get an error: CERT_UNTRUSTED
Below I have pasted the npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   'iobroker',
1 verbose cli   '--unsafe-perm' ]
2 info using npm@1.3.10
3 info using node@v0.10.25
4 verbose cache add [ 'iobroker', null ]
5 verbose cache add name=undefined spec="iobroker" args=["iobroker",null]
6 verbose parsed url { protocol: null,
6 verbose parsed url   slashes: null,
6 verbose parsed url   auth: null,
6 verbose parsed url   host: null,
6 verbose parsed url   port: null,
6 verbose parsed url   hostname: null,
6 verbose parsed url   hash: null,
6 verbose parsed url   search: null,
6 verbose parsed url   query: null,
6 verbose parsed url   pathname: 'iobroker',
6 verbose parsed url   path: 'iobroker',
6 verbose parsed url   href: 'iobroker' }
7 silly lockFile e3e34703-iobroker iobroker
8 verbose lock iobroker /home/wolfgang/.npm/e3e34703-iobroker.lock
9 silly lockFile e3e34703-iobroker iobroker
10 silly lockFile e3e34703-iobroker iobroker
11 verbose addNamed [ 'iobroker', '' ]
12 verbose addNamed [ null, '*' ]
13 silly lockFile e9e5f42f-iobroker iobroker@
14 verbose lock iobroker@ /home/wolfgang/.npm/e9e5f42f-iobroker.lock
15 silly addNameRange { name: 'iobroker', range: '*', hasData: false }
16 verbose url raw iobroker
17 verbose url resolving [ 'https://registry.npmjs.org/', './iobroker' ]
18 verbose url resolved https://registry.npmjs.org/iobroker
19 info trying registry request attempt 1 at 19:50:14
20 http GET https://registry.npmjs.org/iobroker
21 info retry will retry, error on last attempt: Error: CERT_UNTRUSTED
22 info trying registry request attempt 2 at 19:50:25
23 http GET https://registry.npmjs.org/iobroker
24 info retry will retry, error on last attempt: Error: CERT_UNTRUSTED
25 info trying registry request attempt 3 at 19:51:25
26 http GET https://registry.npmjs.org/iobroker
27 silly lockFile e9e5f42f-iobroker iobroker@
28 silly lockFile e9e5f42f-iobroker iobroker@
29 error Error: CERT_UNTRUSTED
29 error     at SecurePair.<anonymous> (tls.js:1370:32)
29 error     at SecurePair.EventEmitter.emit (events.js:92:17)
29 error     at SecurePair.maybeInitFinished (tls.js:982:10)
29 error     at CleartextStream.read [as _read] (tls.js:469:13)
29 error     at CleartextStream.Readable.read (_stream_readable.js:320:10)
29 error     at EncryptedStream.write [as _write] (tls.js:366:25)
29 error     at doWrite (_stream_writable.js:223:10)
29 error     at writeOrBuffer (_stream_writable.js:213:5)
29 error     at EncryptedStream.Writable.write (_stream_writable.js:180:11)
29 error     at write (_stream_readable.js:583:24)
30 error If you need help, you may report this log at:
30 error     <http://github.com/isaacs/npm/issues>
30 error or email it to:
30 error     <npm-@googlegroups.com>
31 error System Linux 3.13.0-37-generic
32 error command "/usr/bin/nodejs" "/usr/bin/npm" "install" "iobroker" "--unsafe-perm"
33 error cwd /opt/iobroker
34 error node -v v0.10.25
35 error npm -v 1.3.10
36 verbose exit [ 1, true ]

What did I wrong? I am a bloody beginner in iobroker. I have successfully installed it on my WIN10 desktop and have done first connections e.g. with G-Homa. Now I want to run the iobroker on my Linux system under LinuxMint 17.1 (rebecca).

Thanks in advance
Wolfgang

**Comment by kenany** [comment]
Your versions of Node.js and `npm` are years old and are no longer supported.

**Comment by ottok** [comment]
This is a duplicate of https://github.com/npm/npm/issues/20191
