### ISSUE TITLE
Problem with  npm run built in react 

### ISSUE THREAD

**Issue by nirikshan** [npm/npm#20299]
When I am trying to use 'npm run built' in react unknown error is displayed 

Before 2 days I worked with same command it worked fine but know this error is displayed

> C:\Users\nirik\Desktop\nirik with react\nirik ui\nirik>npm run built
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "run" "built"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! missing script: built
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\nirik\Desktop\nirikwith react\nirik ui\nirik\npm-debug.log

How can I solve this problem ?
Why this error is popping up?

**Comment by kenany** [comment]
Do you have a `"built"` script defined in your `package.json`?

**Comment by kenany** [comment]
Closing due to no reply after a month.
