### ISSUE TITLE
ypeError: _service2.default.recordCountEvent is not a function  at dn.onInit 

### ISSUE THREAD

**Issue by songziK** [npm/npm#20301]
#### I'm opening this issue because:

 stat.getProvider() function is normal but stat.recordCountEvent({category: "home",key: "home_page"})
function is error

**Comment by kenany** [comment]
This doesn't seem like an issue with `npm` itself, hence I'm closing this.

**Comment by songziK** [comment]
and official APIDemo about statistics Interface declaration  {"name": "service.stat"} , but official website is {"name": " service.stats"},this is very strange。
