### ISSUE TITLE
while installing this 'npm i react react-dom react-router@2.0.1 --save' i am strucked ,how to solve this

### ISSUE THREAD

**Issue by shrilakshmishastry** [npm/npm#20313]
#### I'm opening this issue because:

 

 

  - [ ] npm is doing something I don't understand.

 
i am getting this error
 Error: CERT_UNTRUSTED
npm ERR!     at SecurePair.<anonymous> (tls.js:1370:32)
npm ERR!     at SecurePair.EventEmitter.emit (events.js:92:17)
npm ERR!     at SecurePair.maybeInitFinished (tls.js:982:10)
npm ERR!     at CleartextStream.read [as _read] (tls.js:469:13)
npm ERR!     at CleartextStream.Readable.read (_stream_readable.js:320:10)
npm ERR!     at EncryptedStream.write [as _write] (tls.js:366:25)
npm ERR!     at doWrite (_stream_writable.js:223:10)
npm ERR!     at writeOrBuffer (_stream_writable.js:213:5)
npm ERR!     at EncryptedStream.Writable.write (_stream_writable.js:180:11)
npm ERR!     at write (_stream_readable.js:583:24)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.4.0-116-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "babel-preset-es2015" "babel-preset-react" "--save-dev"
npm ERR! cwd /home/shri/React-project
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/shri/React-project/npm-debug.log
npm ERR! not ok code 0
 how to solve this

**Comment by kenany** [comment]
Your versions of Node.js and `npm` are years old and are no longer supported.
