### ISSUE TITLE
NPM ERR!!!

### ISSUE THREAD

**Issue by Ac3n34d-X** [npm/npm#20318]
npm http GET https://registry.npmjs.org/nsp
npm http GET https://registry.npmjs.org/nsp
npm http GET https://registry.npmjs.org/nsp
npm ERR! Error: CERT_UNTRUSTED
npm ERR!     at SecurePair.<anonymous> (tls.js:1370:32)
npm ERR!     at SecurePair.EventEmitter.emit (events.js:92:17)
npm ERR!     at SecurePair.maybeInitFinished (tls.js:982:10)
npm ERR!     at CleartextStream.read [as _read] (tls.js:469:13)
npm ERR!     at CleartextStream.Readable.read (_stream_readable.js:320:10)
npm ERR!     at EncryptedStream.write [as _write] (tls.js:366:25)
npm ERR!     at doWrite (_stream_writable.js:223:10)
npm ERR!     at writeOrBuffer (_stream_writable.js:213:5)
npm ERR!     at EncryptedStream.Writable.write (_stream_writable.js:180:11)
npm ERR!     at write (_stream_readable.js:583:24)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

**Comment by kenany** [comment]
Your version of `npm` is years old and is no longer supported.

**Comment by Ac3n34d-X** [comment]
So how can I fix it ?

**Comment by kenany** [comment]
I suggest downloading a new version of Node.js from <https://nodejs.org/>. It comes with newer versions of `npm` bundled in.

**Comment by Ac3n34d-X** [comment]
Ok apt-get node.js ?

**Comment by kenany** [comment]
I suggest using [NodeSource's distributions](https://github.com/nodesource/distributions) if you wanna use `apt-get`.

**Comment by Ac3n34d-X** [comment]
Ok I'll try

**Comment by Ac3n34d-X** [comment]
It doesn't install successfully the node
