### ISSUE TITLE
installing vue-kanban but it shows below errors so can't install

### ISSUE THREAD

**Issue by RiyaNaik54** [npm/npm#20360]
npm WARN checkPermissions Missing write access to /home/riya/node_modules
/home/riya
`-- vue-kanban@1.2.0 

npm WARN enoent ENOENT: no such file or directory, open '/home/riya/package.json'
npm WARN riya No description
npm WARN riya No repository field.
npm WARN riya No README data
npm WARN riya No license field.
npm ERR! Linux 3.13.0-32-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "vue-kanban"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0
npm ERR! path /home/riya/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/home/riya/node_modules'
npm ERR!  { Error: EACCES: permission denied, access '/home/riya/node_modules'
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/home/riya/node_modules' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/riya/.npm/_logs/2018-04-18T06_17_02_061Z-debug.log

**Comment by kenany** [comment]
You apparently do not have the permissions necessary to write to `/home/riya/node_modules`. You could try running:

```
sudo chown -R $(whoami) /home/riya/node_modules
```

**Comment by kenany** [comment]
Closing due to no reply after a month.
