### ISSUE TITLE
When running pack, npm first runs prepare

### ISSUE THREAD

**Issue by rbiggs** [npm/npm#20370]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [X] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I have a `prepare` script which I use so that when the user runs `npm i` it installs and builds the module, including launching Browsersync to run in-browser tests. For some reason when I run `npm pack` it first runs the `prepare` script. Because in the end this launches Browsersync, the pack never occurs. I've had to remove automatic testing from my build script so that `pack` can never create a tar ball. 

This is not mentioned in the docs, that `pack` would run  a `prepare` script first. This happens regardless of whether i run `npm pack` in the folder, or pass a path to the folder to the command line. I would not expect `pack` to run a `prepare` script. 

### supporting information:

 - `npm -v` prints: 5.8.0
 - `node -v` prints: v8.11.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS 10.13.4

**Comment by sonicdoe** [comment]
According to the docs, this is correct behavior. From [docs.npmjs.com/misc/scripts](https://docs.npmjs.com/misc/scripts):

> prepare: Run both BEFORE the package is packed and published, and on local `npm install` without any arguments

“packed” refers to `npm pack`, in this case.

**Comment by rbiggs** [comment]
OK
