### ISSUE TITLE
npm install -g yo : ERR! Invalid name: "@sindresorhus/is"

### ISSUE THREAD

**Issue by thecheenee** [npm/npm#20375]
#### I'm opening this issue because:

**npm is producing an incorrect install.**

#### What's going wrong?
My project requires me to connect to npm via CNTLM. I have managed to install other modules such as yeoman-doctor, bower etc. But when I try to install yo, I get the error as follows:
```
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--global" "yo"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9

npm ERR! Invalid name: "@sindresorhus/is"
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\sachari\npm-debug.log
```
Gist of NPM-debug-log:
https://gist.githubusercontent.com/thecheeknee/35cc56d1e8c45cf9198df75358c8bb5c/raw/e1387161dd948984ac8586e44402b13bc64ea6ae/npm-debug-log

#### How can the CLI team reproduce the problem?

- Install CNTLM and make sure it is running in the background when you install NPM modules
- Go to GIT bash and run `npm install --global yo`

### supporting information:

 - `npm -v` prints:  v3.10.9
 - `node -v` prints:  v6.9.2
 - `npm config get registry` prints: http://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows Server R2
 - Network issues:
   - Geographic location where npm was run: Sydney
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
Does this also occur with newer versions of `npm`?

**Comment by kenany** [comment]
Closing due to no reply after a month.
