### ISSUE TITLE
`isntall` should be `install`

### ISSUE THREAD

**Issue by jaredatron** [npm/npm#20380]
```bash
npm install --help

npm install (with no args, in package dir)
npm install [<@scope>/]<pkg>
npm install [<@scope>/]<pkg>@<tag>
npm install [<@scope>/]<pkg>@<version>
npm install [<@scope>/]<pkg>@<version range>
npm install <folder>
npm install <tarball file>
npm install <tarball url>
npm install <git:// url>
npm install <github username>/<github project>

aliases: i, isntall, add
common options: [--save-prod|--save-dev|--save-optional] [--save-exact] [--no-save]
```

`aliases: i, isntall, add` should be `aliases: i, install, add`

FYI

```bash
npm --version
5.8.0
```

**Comment by sergiohgz** [comment]
I don't think this is an issue. In fact, i believe it is a facility for **npm-cli** users. Everyone can think it is wrong, but as i said, this is a facility for common mistakes. Look at [this](https://github.com/npm/npm/blob/latest/lib/config/cmd-list.js#L26) for others.

I want to make an special mention to other user common-mistake that appears in the list: _verison_ -> _version_

**Comment by jaredatron** [comment]
oh wow this is intentional!? npm has code to handle people mistyping `install` as `isntall`?

![facepalm](http://i0.kym-cdn.com/entries/icons/original/000/000/554/picard-facepalm.jpg)

**Comment by sergiohgz** [comment]
Yeah, I know many programmers that create aliases in bash (for example, gti for git or cocker for docker) because they are focused in programming and not in how bash forbid mistakes.

In Windows (I don't know if powershell does, but old cmd does) you can write bad a command (like writing in uppercase when is lowercase) as it isn't case sensitive :sad:

**Comment by kenany** [comment]
Yup, that alias is an intentional typo.
