### ISSUE TITLE
Can't update NPM on Linux ARM

### ISSUE THREAD

**Issue by LucasGorgal** [npm/npm#20383]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I can't update npm
### supporting information:

 - `npm -v` prints: 1.4.21
 - `node -v` prints: v9.11.1
 - `npm config get registry` prints: {"db_name":"registry","doc_count":860149,"doc_del_count":342,"update_seq":10575774,"purge_seq":0,"compact_running":false,"disk_size":8419655815,"data_size":4936296055,"instance_start
_time":"1524179038558026","disk_format_version":6,"committed_update_seq":10575774}
 - Windows, OS X/macOS, or Linux?: Linux
 - Network issues: None
   - Geographic location where npm was run: Southest Brazil
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

When I try to update, I get:
sudo npm install -g npm@latest
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
/usr/local/bin/npx -> /usr/local/lib/node_modules/npm/bin/npx-cli.js
npm@5.8.0
updated 1 package in 58.278s

but when I use npm -v:
`1.4.21`

**Comment by kenany** [comment]
What is the output of

```
which npm
```

**Comment by kenany** [comment]
Closing due to no reply after a month.
