### ISSUE TITLE
can't sign up npm account

### ISSUE THREAD

**Issue by ilovefafa** [npm/npm#20418]
when i sign up,i get the follow informantion,what does it mean?
![default](https://user-images.githubusercontent.com/34020077/39171507-a16bb09e-47d1-11e8-8c95-1e4f17d85a6f.png)

**Comment by ilovefafa** [comment]
## i find the solution 
beacaus i use 163 e-mail,when i use g-mail,it works.
i hope the page give some hints,thanks

**Comment by ilovefafa** [comment]
test

**Comment by IEfucker** [comment]
This really helps..
Has been stucked with this bug for days, and finally find this
