### ISSUE TITLE
Upable to install npm

### ISSUE THREAD

**Issue by Ksharma1285** [npm/npm#20412]
#### I'm opening this issue because:
I am unable to install gulp yo on my machine.
  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
write EPROTO 101057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:827:
### supporting information:
![npm install issue](https://user-images.githubusercontent.com/38660862/39130838-9e3c0b96-46fd-11e8-9ede-bf90b4397cc3.jpg)

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
Does this also occur with the latest stable release of `npm`?

**Comment by Ksharma1285** [comment]
How do I get latest stable release.   I am trying to build Sharepoint webparts for SharePoint 2016 prem so I need to be at a specific version.

Kuldeep Sharma | Application Solutions Manager
Paul, Weiss, Rifkind, Wharton & Garrison LLP
1285 Avenue of the Americas | New York, NY 10019-6064
+1 212 373 2957 (Direct Phone) | +1 516 343 0633 (Cell)
ksharma@paulweiss.com<mailto:ksharma@paulweiss.com> | www.paulweiss.com<http://www.paulweiss.com>

**Comment by kenany** [comment]
You can try running

```
npm install -g npm
```

or, you can download the latest version of Node.js from <https://nodejs.org/>, since it'll bundle a newer version of `npm` than what you currently have.

**Comment by Ksharma1285** [comment]
Just did which generated attached log file.
Kuldeep Sharma | Application Solutions Manager
Paul, Weiss, Rifkind, Wharton & Garrison LLP
1285 Avenue of the Americas | New York, NY 10019-6064
+1 212 373 2957 (Direct Phone) | +1 516 343 0633 (Cell)
ksharma@paulweiss.com<mailto:ksharma@paulweiss.com> | www.paulweiss.com<http://www.paulweiss.com>

**Comment by kenany** [comment]
@Ksharma1285 Email attachments do not appear in the GitHub website. Could you please upload the logfile to <https://gist.github.com/> and post the link to it here?

**Comment by Ksharma1285** [comment]
![npm install issue](https://user-images.githubusercontent.com/38660862/39138374-cb16263e-46ed-11e8-89f9-3c8ecc71c937.jpg)

**Comment by kenany** [comment]
@Ksharma1285 Isn't that the same screenshot you posted in your first post?

**Comment by Ksharma1285** [comment]
Yes this is all  I have .   What else can I provide.

Kuldeep Sharma | Application Solutions Manager
Paul, Weiss, Rifkind, Wharton & Garrison LLP
1285 Avenue of the Americas | New York, NY 10019-6064
+1 212 373 2957 (Direct Phone) | +1 516 343 0633 (Cell)
ksharma@paulweiss.com<mailto:ksharma@paulweiss.com> | www.paulweiss.com<http://www.paulweiss.com>

**Comment by kenany** [comment]
@Ksharma1285 See my previous comment regarding updating `npm`.

**Comment by kenany** [comment]
Closing due to no reply after a month.
