### ISSUE TITLE
A link mistake in npmjs.org

### ISSUE THREAD

**Issue by shockw4ver** [npm/npm#20417]
#### I'm opening this issue because:
  - [x] Other 

#### What's going wrong?
A link on npmjs.org is relating to 'http://localhost:5000/misc/scope'...
At 'https://docs.npmjs.com/misc/scope#publishing-public-scoped-packages-to-the-public-npm-registry'.
> Scopes are used to group related packages together, and to create a namespace, like a domain, for npm modules. This is explained in more detail **here**.

The bold font links to a local address~

**Comment by kenany** [comment]
There is already a PR to fix this over at the docs repository: https://github.com/npm/docs/pull/975.
