### ISSUE TITLE
Enforce fixed dependencies to released packages

### ISSUE THREAD

**Issue by sarbull** [npm/npm#20413]
#### I'm opening this issue because:
 I propose an enhancement.

#### What's going wrong?
I only use fixed versions in my "dependencies"(and i think i'm not the only one) tag but the packages that i am using contain dynamic versions inside which makes my build form day to day to fail or to work, depending on what changes are being made.

Last example is an autocomplete component which changed a parameter(removed it and renamed) and made my extended component crash without any code change right at the start of a production release.

#### What's the feature?
Enforce fixed dependencies to released packages in NPM Registry.

#### What problem is the feature intended to solve?
Unknown dependencies.

#### Is the absence of this feature blocking you or your team? If so, how?
Not knowing if tomorrow my build will still work.

#### Is this a feature you're prepared to implement, with support from the npm CLI team?
It's quite simple to do i think. Drop the `^`, `~`, etc.

**Comment by zkat** [comment]
This is what `package-lock.json` is for.
