### ISSUE TITLE
RFC: Install size information

### ISSUE THREAD

**Issue by zkat** [npm/npm#20427]
This proposal introduces the idea of adding extracted package size information to the output summary for `npm install`.

#### NOTE
This is an RFC. It is not a finalized, accepted feature request proposal. I've laid out the general process of implementation, but please don't make a PR implementing it until we've had time to discuss this.

### Problem

Right now, there's no built-in way for npm users to figure out the size impact of adding or removing a package from their tree. In the past, it would have been easier because you could just trace the nested tree -- but now, because of flattening and deduplication, it's not trivial to take into account how many new packages would be added by a particular install, and what their total impact would be.

### Changes `npm install`

The `npm install` output will be changed such that total size information is included, and displayed in different ways depending on output mode:

#### `npm install`

The default, human-readable view currently looks like this:

```
➜ npm i webpack
+ webpack@4.6.0
added 536 packages from 24 contributors in 9.299s
```

It will be changed to display size information like this:

```
➜ npm i webpack
+ webpack@4.6.0
added 536 packages (+32MB) from 24 contributors in 9.299s
```

Or when the net value is negative:

```
➜ npm rm --dry-run pacote
removed 39 packages (-5MB) in 5.148s
```

Even when both additions and removals have occurred:

```
➜ npm i --dry-run pacote@1
+ pacote@1.0.0
added 35 packages, removed 33 packages, updated 1 package and moved 1 package (-3MB) in 5.817s
```

#### `npm install --json`

The JSON format will add two things: `size` and `unpackedSize` field to each individual `action` record, and a `sizeDelta` field that totals up all the `unpackedSize` changes, in the toplevel:

```
➜ npm i ssri --dry-run --json
{
  "added": [
    {
      "action": "add",
      "name": "ssri",
      "version": "6.0.0",
      "path": ".../node_modules/ssri",
      "size": 12116,
      "unpackedSize": 40772
    }
  ],
  "removed": [],
  "updated": [],
  "moved": [],
  "failed": [],
  "warnings": [],
  "sizeDelta": 40772, // positive or negative, depending on sum
  "elapsed": 535
}
```

#### `npm install --parseable`

The `--parseable` tab-delimited format will remain unchanged by default, to prevent potentially breaking parsers. Instead, the `--long`/`-l` option will be supported, which will add two additional columns next to each entry: the tarball `size`, and the `unpackedSize`. It's up to users to add the numbers up themselves.

```
➜ npm i ssri --dry-run --parseable --long

add     ssri    6.0.0   node_modules/ssri 12116 40772
```

### Implementation Details

This would need to patch both the npm installer (in `lib/install.js` and `lib/install/actions/extract.js`), as well as add an extra field to the `finalizeManifest` process in [`pacote`](https://github.com/zkat/pacote) (`lib/finalize-manifest.js`).

#### npm installer changes

There are two changes to be made to the installer:

On the reporting side, update the three reporters (`printInstalledForHuman`, `printInstalledForParseable`, and `printInstalledForJSON`) in `lib/install.js`. You should be able to check `_size` and `_unpackedSize` in the `child.package` value, which holds the manifest for each installed package. Note: if **any** of the packages in the calculation are missing the `_unpackedSize` value and the current reporter is `printInstalledForHuman`, this file size summary should be omitted altogether. This case will happen for legacy registries when using `npm install --dry-run` -- it will otherwise be calculated from actual extracted size.

On the extract side, you will need to check if the `child.package._size` and `child.package._unpackedSize` properties exist. If they do not, you should set them based on metadata returned by `pacote.extract()`.

#### `pacote` changes

`pacote` needs to do two things to support this:

* `lib/finalize-manifest.js` should be modified to get the compressed and uncompressed tarball size from package manifests, _but only if they are available_. They should be assigned to `_size` and `_unpackedSize` respectively, and are present in the `dist.size` and `dist.unpackedSize` properties of the manifest.

* `extract.js` and `tarball.js` should have their functions modified such that they return or emit size and unpackedSize as part of the metadata, where appropriate, after the operation has completed. This should be calculated from the actual data getting extracted (and may require changes to `lib/extract-stream.js` as well as `lib/with-tarball-stream.js`.

**Comment by gaearon** [comment]
My first thought is that in the front-end context many people will misinterpret this size as the size *shipped to the browsers* (which it usually isn’t). I wonder if there’s any way to preemptively clarify this.

**Comment by zkat** [comment]
@gaearon I thought about that, too, but it's also not my job to make compression/minification decisions for users. Those are even more application-dependent than the unpacked size on disk.

**Comment by zkat** [comment]
Thinking about this further: the main workflow that I imagine this would benefit is from folks doing `npm install --dry-run <some-pkg>`, when evaluating several choices. Different packages will yield different total downloads, because of things like overlap with currently-used tooling. It can also be useful when getting a sense of just how much actual data is being extracted to disk whenever an install is run, which may help CI contexts. Alerting individual users about what their final bundle size might look like is a bit further down the list for this -- specially since the vast majority of things npm will install isn't even source code to ship to browsers, but development and build tooling. It would be interesting to have conversations with users and get a sense of how often the confusion you're talking about would actually come up (and I agree that it's likely!), and whether we can wordsmith the message a bit (as I think you're suggesting).

**Comment by johana-star** [comment]
I _think_ I have some spare cycles to look at this this week. The `npm install` and pacote changes _appear_ straightforward from your write-up.

I'm trying to think of any simple addition to your parenthetical and maybe something like '(+32 MB added to node_modules)' would add clarity, but I think there is also a user education piece to this. Perhaps there should also be documentation improvements clarifying how to calculate the build size, and maybe it could point to an article regarding how to measure the web app _loaded in a browser context_. 

What questions need to be addressed before I can start investigating/implementing?

**Comment by zkat** [comment]
@strand documentation can be updated, but I think it's generally safe to assume the vast majority of people won't read this level of detailed documentation, and good CLI UX requires things be "obvious".

The challenge of measuring "loaded in a browser" is much bigger, since it varies entirely depending on individual tool used to minify, bundle, etc, as well as all the configuration for whatever tool you pick. It's basically an infinite space, and bundling isn't something that npm does (or, tbh, will) get involved with.

The `to node_modules/` bit seems like a good step in the right direction! Terseness is nice, because that line is starting to get a lot of info clumped together and I wanna keep it readable. Otherwise, I'd totally try and fit a much bigger explanation in there.

If you're interested in implementing this, I'd suggest waiting a few days -- maybe look at this issue again this weekend or next week, after it's had time to get discussed a little, just so you're not getting thrashed around as we discuss potential issues. Implementation-wise, I _believe_ this implementation will be pretty much what's laid out in the implementation section in the OP. It's not a lot of code, and most of the lego blocks are already in place for you, so this ends up being mostly glue work. There's the possibility of unforeseen implementation details, and I think I'm gonna have to ping the registry folks to make sure `dist.unpackedSize` and `dist.size` are backfilled across the whole registry (only some packages have `unpackedSize` right now, and none of them have `size`). The other question is what the best way to get total unpacked size is -- but I assume this is a matter of just adding something to the `onentry` callback in `lib/extract-stream.js`. I THINK that would be good enough? /cc @isaacs

**Comment by johana-star** [comment]
Makes a lot of sense. The docs should be updated AND the CLI UX should ideally be so obvious that docs aren’t needed.

I have some free time on Friday afternoon, so I’ll make this my open source Friday project, and may get a PR going, tho I’ll probably just spike out a potential implementation…

Thanks for the initial guidance. 🤞🏼 I can grok this and fit the work into my regular schedule.

**Comment by zkat** [comment]
@strand if you want to talk to us more directly, join the https://package.community Discord and pop into the npm channel! We hang out there for dev-related chats

**Comment by styfle** [comment]
@gaearon I think some people might be confused.

For example, users installing [react-dom](https://bundlephobia.com/result?p=react-dom@16.3.2) care about bundle size.
However people who are installing [jest](https://packagephobia.now.sh/result?p=jest@22.4.3) care about install size.

This is an interesting problem I have been thinking about for some time and lead me to create https://github.com/styfle/packagephobia (you might be interested in looking through the README)

An unsolved issue (which is probably outside of the scope of this RFC but worth thinking about) is: How can a user know if a package is meant to be installed as a devDependency (think test runner or CLI) or a front-end dependency (think react-dom).

**Comment by zkat** [comment]
Hey y'all. We're switching around our RFC process, and so I've moved this RFC over to the `npm/rfcs` repo. See https://github.com/npm/rfcs/pull/1. Please move any further discussion over there.

**Comment by mblarsen** [comment]
Related https://github.com/egoist/package-size
