### ISSUE TITLE
NPM@6 latest github release

### ISSUE THREAD

**Issue by shaunwarman** [npm/npm#20423]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] npm is producing incorrect or undesirable behavior.
  - [X] Other (_see below for feature requests_):

#### What's going wrong?
Just wanted to see when [npm@6](https://github.com/npm/npm/releases/tag/v6.0.0) github [release](https://github.com/npm/npm/releases) would be **latest** so our CIs can kick in for internal community 😄 

And thanks for the [wonderful post](https://medium.com/npm-inc/announcing-npm-6-5d0b1799a905)

**Comment by zkat** [comment]
@shaunwarman `npm@6` became `npm@latest` last night, and you can see the release itself here: https://github.com/npm/npm/releases/tag/v6.0.0

It doesn't include a changelog because we're using the beta changelogs for that.
