### ISSUE TITLE
`npm audit` returns ENOAUDIT in npm 6

### ISSUE THREAD

**Issue by aviggiano** [npm/npm#20436]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [x] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I am trying to test the new `npm audit` command from npm@6 but it is returning the following error:

```
$ npm audit
npm ERR! code ENOAUDIT
npm ERR! audit Your configured registry (https://registry.npmjs.org/) does not support audit requests.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/antonio/.npm/_logs/2018-04-25T11_39_00_164Z-debug.log
```

#### How can the CLI team reproduce the problem?

Run `npm audit` in a simple node project. Here's a gist of my [npm-debug.log file](https://gist.github.com/aviggiano/5f02fdec8b7325969339c746e19c2b92)

### supporting information:

 - `npm -v` prints: 6.0.0
 - `node -v` prints: v10.0.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux
 - Network issues:
   - Geographic location where npm was run: Brazil
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by icorne** [comment]
https://medium.com/npm-inc/announcing-npm-6-5d0b1799a905
In here, they it's not available yet, unless you connect to the beta registery

**Comment by aviggiano** [comment]
Oh alright. I'll close this issue then.

> These features are already available to users of npm’s beta registry, and in coming weeks they will automatically roll out to every member of the community. Both of these features are available free of charge to every npm user, with no purchase or registration required. (Customers of our paid services will receive additional pre-publication vulnerability disclosures, formerly the NSP’s premium tier.)

**Comment by wlievens** [comment]
How does one use the beta registry? I can't seem to find any information about it.

**Comment by tunnckoCore** [comment]
@wlievens +1

**Comment by anthony-o** [comment]
I've solved this with `npm i -g npm`.

**Comment by magnusriga** [comment]
I seem to get the same error message as OP, in irregular intervals. Sometimes it works, sometimes it does not. I have not been able to find a pattern. Whenever I reinstall npm as @anthony-o indicated, it starts working again.

**Comment by chrisgbaker** [comment]
```cmd
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\cbaker\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'audit',
1 verbose cli   'fix' ]
2 info using npm@6.1.0-next.0
3 info using node@v8.9.4
4 verbose npm-session 299586f8bcdc8b4c
5 timing audit compress Completed in 29ms
6 info audit Submitting payload of 122213 bytes
7 http fetch POST 503 https://registry.npmjs.org/-/npm/v1/security/audits 347ms
8 verbose stack Error: Your configured registry (https://registry.npmjs.org/) does not support audit requests.
8 verbose stack     at Bluebird.all.spread.then.catch.err (C:\Users\cbaker\AppData\Roaming\npm\node_modules\npm\lib\audit.js:168:18)
8 verbose stack     at tryCatcher (C:\Users\cbaker\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
8 verbose stack     at Promise._settlePromiseFromHandler (C:\Users\cbaker\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
8 verbose stack     at Promise._settlePromise (C:\Users\cbaker\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
8 verbose stack     at Promise._settlePromise0 (C:\Users\cbaker\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
8 verbose stack     at Promise._settlePromises (C:\Users\cbaker\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:689:18)
8 verbose stack     at Async._drainQueue (C:\Users\cbaker\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
8 verbose stack     at Async._drainQueues (C:\Users\cbaker\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
8 verbose stack     at Immediate.Async.drainQueues (C:\Users\cbaker\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
8 verbose stack     at runCallback (timers.js:789:20)
8 verbose stack     at tryOnImmediate (timers.js:751:5)
8 verbose stack     at processImmediate [as _immediateCallback] (timers.js:722:5)
9 verbose cwd C:\Users\cbaker\src\app\app.UI
10 verbose Windows_NT 10.0.14393
11 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\cbaker\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "audit" "fix"
12 verbose node v8.9.4
13 verbose npm  v6.1.0-next.0
14 error code ENOAUDIT
15 error audit Your configured registry (https://registry.npmjs.org/) does not support audit requests.
16 verbose exit [ 1, true ]
```

Not sure if this is helpful, but this error just popped up for the first time. `npm audit fix` has worked every other time before, and worked the next time I tried.

**Comment by ganchikov** [comment]
i faced this issue when manually tried to fix the vulnerability of hoek following this guide: https://nodesecurity.io/advisories/566

What i've done is i manually changed versions of all hoek instances in package-lock.json to "~>=5.0.3". This caused the npm audit command fail with the mentioned error, so i had to revert my change so it start working again. 

Happy if this helps someone..
