### ISSUE TITLE
unmet peer dependency jasmine-core@*

### ISSUE THREAD

**Issue by bagasssss** [npm/npm#20432]
Hello
After release of new node and npm - Jenkins throw some errors that weren't before

npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "node" "/usr/local/bin/npm" "update"
npm ERR! node v0.10.25
npm ERR! npm  v3.5.0

npm ERR! CERT_UNTRUSTED
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /var/lib/jenkins/workspace/DL-QT-PROD-Frontend/npm-debug.log
Build step 'Execute shell' marked build as failure
SSH: Current build result is [FAILURE], not going to run.
Finished: FAILURE

Tried to do npm install and got this

![image](https://user-images.githubusercontent.com/5882526/39233418-fa0c1502-4878-11e8-9f87-d22278210533.png)

Can you help please?

**Comment by kenany** [comment]
Your version of Node.js is years old and is no longer supported.
