### ISSUE TITLE
error with 'npm install npm@latest -g' command

### ISSUE THREAD

**Issue by DianaShin** [npm/npm#20443]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [X ] npm is producing an incorrect install.
  - [X] npm is doing something I don't understand.
  - [X ] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I am trying to run 'npm install npm@latest -g' to update npm to the latest version (the current version on computer is 1.2.0). However, I get an error (copied and pasted below): 
npm http GET https://registry.npmjs.org/npm
npm ERR! Error: SSL Error: CERT_UNTRUSTED
npm ERR!     at ClientRequest.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/main.js:525:26)
npm ERR!     at ClientRequest.g (events.js:192:14)
npm ERR!     at ClientRequest.EventEmitter.emit (events.js:96:17)
npm ERR!     at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1527:7)
npm ERR!     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:111:23)
npm ERR!     at CleartextStream.socketOnData [as ondata] (http.js:1430:20)
npm ERR!     at CleartextStream.CryptoStream._push (tls.js:526:27)
npm ERR!     at SecurePair.cycle (tls.js:880:20)
npm ERR!     at EncryptedStream.CryptoStream.write (tls.js:267:13)
npm ERR!     at Socket.ondata (stream.js:38:26)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 17.4.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "npm@latest" "-g"
npm ERR! cwd /Users/diana.shin
npm ERR! node -v v0.8.17
npm ERR! npm -v 1.2.0
npm ERR! code ESSL
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/diana.shin/npm-debug.log
npm ERR! not ok code 0

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
Your versions of Node.js and `npm` are so old, I don't think it will be possible to update `npm`. I suggest getting the latest version of Node.js from <https://nodejs.org/>, since it bundles new `npm` versions.

**Comment by DianaShin** [comment]
@KenanY tessekkurler! I tried doing that earlier today, but couldn't because of admin issues (started a new job and its a company computer).
