### ISSUE TITLE
Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE when trying to Install angular CLI

### ISSUE THREAD

**Issue by rubansenthil** [npm/npm#20446]
npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli"
npm ERR! node v6.11.4
npm ERR! npm  v3.10.10
npm ERR! code UNABLE_TO_VERIFY_LEAF_SIGNATURE

npm ERR! unable to verify the first certificate
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Ruban\angular\npm-debug.log

Getting this error , while i trying to install angular cli , can anyone help me out of this?

**Comment by kenany** [comment]
`npm` v3 is no longer supported.
