### ISSUE TITLE
npm install after npm link should be configurable

### ISSUE THREAD

**Issue by tarol** [npm/npm#20449]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ * ] npm is doing something I don't understand.
  - [ ] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
i use yarn to install dependencies, but npm would run install after npm link every time

**Comment by zkat** [comment]
this isn't very clear or actionable

**Comment by tarol** [comment]
i mean when i run npm link in package, npm install would be auto run, but i use yarn to install dependencies, this action would overwrite my node_modules

**Comment by zkat** [comment]
@tarol Yarn is not designed to be compatible with npm trees (or vice-versa). You can't use both with the same project.
