### ISSUE TITLE
new version not showing in npm repo after npm publish

### ISSUE THREAD

**Issue by trusktr** [npm/npm#20448]
Same as https://github.com/npm/npm/issues/6717, but opening a new one.

I recently published `animation-loop` 1.1.1, but it does not appear on the site.

`npm view animation-loop` does not show the latest `1.1.1` version.

When I published with `npm publish`, I saw this output:

```
+ animation-loop@1.1.1
```

which indicates it went through.

If I try `npm publish` again, I get

```
npm ERR! publish Failed PUT 403
npm ERR! code E403
npm ERR! You cannot publish over the previously published versions: 1.1.1. : animation-loop
```

**Comment by da1nerd** [comment]
I also just began getting this error. I tried bumping the version again and republishing but still cannot see it on the website or via the command line with `npm view ...`.

**Comment by Mithgol** [comment]
+1, same with `nw@0.30.1` and `nw@0.30.1-sdk` packages.

**Comment by lwansbrough** [comment]
I'm seeing the same issue. There must be an outage.

**Comment by vinagreti** [comment]
i think it is working

**Comment by trusktr** [comment]
Yep, seems like it's working, I see my published version now.

**Comment by crocodile2u** [comment]
I am currently experiencing the same. Have you found a workaround or is it an issue on npmjs server (cache invalidation, maybe)?

**Comment by yss14** [comment]
Same problem here. Running `npm publish` again throws an error, but installing the new version explicitly is not possible.

**Comment by crocodile2u** [comment]
Seems like a cache invalidation issue. After 10 or 15 minutes it was fine.

**Comment by lafiosca** [comment]
I'm experiencing this as well. I published a patch version, and it wasn't showing up. Then I published an additional patch version just to see if it was a one-time glitch. Then I searched and found this thread. Still waiting on my package to work. :/
