### ISSUE TITLE
Call stack exceeded when running --depth 9999 update to recursively update all packages

### ISSUE THREAD

**Issue by ajkandy** [npm/npm#20451]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Running "npm --depth 9999 update" as recommended, to update npm and dependencies, produces the error "Maximum call stack size exceeded." 

#### How can the CLI team reproduce the problem?

Created new web project following the instructions at https://css-tricks.com/gulp-for-beginners/

Created folder structure as indicated in article, then performed npm init inside the top level of the project folder.

installed Gulp; 

Installed the following dev dependencies:

- browser-sync
- gulp-cssnano
- gulp-ignore
- gulp-rename
- gulp-sass
- gulp-uglify

Noticed some errors produced while installing these, about versions being outdated, that I hadn't seen before. Decided to try updating everything, found the instruction to recursively update packages in the npm documentation, ran that command to get the legacy recursive behaviour.

Error log Gist:

https://gist.github.com/ajkandy/f2367badb32b6dcd1dacaa8b43cf10a5

Using Microsoft VSCode on Windows 7.

### supporting information:

 - `npm -v` prints: 3.10.10 (after update)
 - `node -v` prints: 6.10.2
 - `npm config get registry` prints: https://registry.npmjs.org
 - Windows, OS X/macOS, or Linux?: Windows 7

 - Network issues:
   - Geographic location where npm was run: Calgary, Alberta, Canada

   - [ ] I use a proxy to connect to the npm registry.
   - [x] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.

**Comment by zkat** [comment]
npm@3 is no longer supported. Please update to the latest npm with `npm i -g npm@latest` or similar and try again.

**Comment by ajkandy** [comment]
Thanks for the clarification! Updating now.
