### ISSUE TITLE
Updating npm shows warning to update npm

### ISSUE THREAD

**Issue by zhullGH** [npm/npm#20453]
#### I'm opening this issue because:
  - [x] npm is producing incorrect or undesirable behavior.

#### What's going wrong?
After the command `npm i -g npm` is executed successfully, the update warning still pops up.
```
   ╭─────────────────────────────────────╮
   │                                     │
   │   Update available 5.8.0 → 6.0.0    │
   │     Run npm i -g npm to update      │
   │                                     │
   ╰─────────────────────────────────────╯
```
This is due to the fact that the command is still running on the outdated version.
It would be nice if this warning didn't show up in case of a successful update. 

#### How can the CLI team reproduce the problem?
Execute the `npm i -g npm` on an outdated version of npm. 

### supporting information:

 - `npm -v` prints: `5.8.0`
 - `node -v` prints: `9.1.0`
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 -  OS X/macOS

**Comment by legodude17** [comment]
What is the result of `which npm` and `npm prefix -g` and `echo $PATH`?

**Comment by zhullGH** [comment]
This problem seems to only occur in MacOS. 
I no longer have a MacOS system so i can´t reproduce the problem.

**Comment by legodude17** [comment]
Is this the same issue as #20693?

**Comment by zhullGH** [comment]
@legodude17 yes, same bug.
Should i close this one?

**Comment by legodude17** [comment]
Yeah.
