### ISSUE TITLE
Wrong error message when try to publish but not logged in

### ISSUE THREAD

**Issue by sarcadass** [npm/npm#20467]
#### I'm opening this issue because:

  - [x] npm is producing incorrect or undesirable behavior.

#### What's going wrong?

When I try to publish a package and i'm not logged in (`$ npm login`). I've got this error message : "_Please try running this command again as root/Administrator._". Even doing so it's still not working (because the problem is that I'm not logged in to my NPM account from this machine).

Can you set a proper error message in this case? Like : "You need to get logged in to NPM to publish a package. Type npm login then try again to publish."

#### How can the CLI team reproduce the problem?

Try to `$ npm publish` a package when you are not logged in to NPM on your machine.

### supporting information:

 - `npm -v` prints: **5.6.0**
 - `node -v` prints: **8.9.1**
 - `npm config get registry` prints: **https://registry.npmjs.org/**
 - Windows, OS X/macOS, or Linux?: **Windows 10**

**Comment by sara-02** [comment]
@sarcadass Looks like this is a duplicate of https://github.com/npm/npm/issues/20450

**Comment by sarcadass** [comment]
@sara-02 Yes it is, I didn't see a similar issue was already created 😐.
I close this one to prevent a duplicate.
