### ISSUE TITLE
Package's readmes are rendered broken/displayed incorrectly

### ISSUE THREAD

**Issue by hodgef** [npm/npm#20469]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ * ] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
There's no output on a package's page, despite README.md being populated. I believe this is a global issue:

eg: https://www.npmjs.com/package/simple-keyboard (npm, bad)
vs: https://github.com/hodgef/simple-keyboard (github, good)

![capture](https://user-images.githubusercontent.com/25509135/39444373-80e6f140-4c85-11e8-869a-2202ec4ed2a2.PNG)

**Comment by hodgef** [comment]
Fixed

**Comment by kenany** [comment]
Next time it would be better to open an issue at the website repo directly: <https://github.com/npm/www>
