### ISSUE TITLE
Issue running npm install - error code 128

### ISSUE THREAD

**Issue by gunjangupta20** [npm/npm#20471]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ Installation Fails ] npm is doing something I don't understand.
  - [ ] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
npm installation process isn't running correctly and is exiting with error code 128

#### How can the CLI team reproduce the problem?
1. Download the QlikBotNode project from [https://github.com/qlik-bots/QlikBotNode/tree/v1]
2. After extracting the zipped file contents, run the npm isntall -g gulp command from git bash in the extracted directory.
3. Then run the npm install command.

### supporting information:
The error message is as under:

$ npm install
npm WARN engine nw-builder@3.5.1: wanted: {"node":">= 4.0.0"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm ERR! git fetch -a origin (git://github.com/adam-lynch/node-temp.git) fatal: Unable to look up github.com (port 9418) (No such host is known. )
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:751:12)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:110:17)
npm WARN addRemoteGit     at maybeClose (child_process.js:1015:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
npm WARN addRemoteGit  adam-lynch/node-temp#remove_tmpdir_dep resetting remote C:\Dev\devtools\cache\npm\_git-remotes\https-github-com-adam-lynch-node-temp-git-36622600 because of error: { [Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit ]
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
npm ERR! git clone --template=C:\Dev\devtools\cache\npm\_git-remotes\_templates --mirror https://github.com/adam-lynch/node-temp.git C:\Dev\devtools\cache\npm\_git-remotes\https-github-com-adam-lynch-node-temp-git-36622600: Cloning into bare repository 'C:\Dev\devtools\cache\npm\_git-remotes\https-github-com-adam-lynch-node-temp-git-36622600'...
npm ERR! git clone --template=C:\Dev\devtools\cache\npm\_git-remotes\_templates --mirror https://github.com/adam-lynch/node-temp.git C:\Dev\devtools\cache\npm\_git-remotes\https-github-com-adam-lynch-node-temp-git-36622600: fatal: unable to access 'https://github.com/adam-lynch/node-temp.git/': Couldn't resolve host 'github.com'
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:751:12)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:110:17)
npm WARN addRemoteGit     at maybeClose (child_process.js:1015:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
npm WARN addRemoteGit  adam-lynch/node-temp#remove_tmpdir_dep resetting remote C:\Dev\devtools\cache\npm\_git-remotes\git-github-com-adam-lynch-node-temp-git-48e958cd because of error: { [Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit ]
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
npm ERR! git clone --template=C:\Dev\devtools\cache\npm\_git-remotes\_templates --mirror git@github.com:adam-lynch/node-temp.git C:\Dev\devtools\cache\npm\_git-remotes\git-github-com-adam-lynch-node-temp-git-48e958cd: Cloning into bare repository 'C:\Dev\devtools\cache\npm\_git-remotes\git-github-com-adam-lynch-node-temp-git-48e958cd'...
npm ERR! git clone --template=C:\Dev\devtools\cache\npm\_git-remotes\_templates --mirror git@github.com:adam-lynch/node-temp.git C:\Dev\devtools\cache\npm\_git-remotes\git-github-com-adam-lynch-node-temp-git-48e958cd: ssh: Could not resolve hostname github.com: Name or service not known
npm ERR! git clone --template=C:\Dev\devtools\cache\npm\_git-remotes\_templates --mirror git@github.com:adam-lynch/node-temp.git C:\Dev\devtools\cache\npm\_git-remotes\git-github-com-adam-lynch-node-temp-git-48e958cd: fatal: Could not read from remote repository.
npm ERR! git clone --template=C:\Dev\devtools\cache\npm\_git-remotes\_templates --mirror git@github.com:adam-lynch/node-temp.git C:\Dev\devtools\cache\npm\_git-remotes\git-github-com-adam-lynch-node-temp-git-48e958cd:
npm ERR! git clone --template=C:\Dev\devtools\cache\npm\_git-remotes\_templates --mirror git@github.com:adam-lynch/node-temp.git C:\Dev\devtools\cache\npm\_git-remotes\git-github-com-adam-lynch-node-temp-git-48e958cd: Please make sure you have the correct access rights
npm ERR! git clone --template=C:\Dev\devtools\cache\npm\_git-remotes\_templates --mirror git@github.com:adam-lynch/node-temp.git C:\Dev\devtools\cache\npm\_git-remotes\git-github-com-adam-lynch-node-temp-git-48e958cd: and the repository exists.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Dev\devtools\cache\npm\_git-remotes\_templates --mirror git@github.com:adam-lynch/node-temp.git C:\Dev\devtools\cache\npm\_git-remotes\git-github-com-adam-lynch-node-temp-git-48e958cd
npm ERR! Cloning into bare repository 'C:\Dev\devtools\cache\npm\_git-remotes\git-github-com-adam-lynch-node-temp-git-48e958cd'...
npm ERR! ssh: Could not resolve hostname github.com: Name or service not known
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\QlikSenseRoot\QlikBotNode-1\npm-debug.log

**Comment by kenany** [comment]
Your versions of Node.js and `npm` are years old and are no longer supported.
