### ISSUE TITLE
Unable to find a readme for package@version

### ISSUE THREAD

**Issue by demsking** [npm/npm#20482]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

`npm` no longer find readme file after `npm publish`:

![image](https://user-images.githubusercontent.com/4570744/39505497-f87a2a3a-4dd2-11e8-8a24-b93bb00def41.png)
Link: https://www.npmjs.com/package/@vuedoc/md

I used the `npm pack` to check its content, the `README.md` file is correctly packaged:

```sh
$ tar -tf vuedoc-md-1.2.0.tgz 
package/package.json
package/README.md
package/LICENSE
package/index.js
package/bin/cli.js
package/lib/cli.js
package/lib/markdown.js
package/package-lock.json
```

#### How can the CLI team reproduce the problem?

This problem occurs when trying to update an npm package with the `npm publish` command.

### supporting information:

 - `npm -v` prints: 3.10.10
 - `node -v` prints: v6.11.5
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: GNU/Linux Ubuntu
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by beeman** [comment]
I seem to have the same issue: https://www.npmjs.com/package/@beeman/schematics

Edit: Seems like a new publish fixed it for me.

**Comment by demsking** [comment]
New publish does not fix the problem :-/

**Comment by xJkit** [comment]
I don't understand either. Give my readme back.

**Comment by BlackHole1** [comment]
me too, my project link: https://www.npmjs.com/package/all-equal

**Comment by mdundek** [comment]
I have the same problem, using npm 6.0.0
I published, 6 times, with new version number every time, but no README is displayed, making those modules unusable...

**Comment by jefflembeck** [comment]
Hi all, this is a known issue and is being addressed here: https://github.com/npm/www/issues/395
