### ISSUE TITLE
Unable to find a readme

### ISSUE THREAD

**Issue by dkern** [npm/npm#20489]
#### I'm opening this issue because:

  - [X] npm is doing something I don't understand.
  - [X] npm is producing incorrect or undesirable behavior.

#### What's going wrong?
After using `npm publish` as always, I've got no errors or problems.
But on the NPM detail page, the following messages shows up since then:

> "Unable to find a readme for jquery-lazy@1.7.8"

https://www.npmjs.com/package/jquery-lazy 

#### How can the CLI team reproduce the problem?

I don't know. I just published the package as I always did and then this issue happens. There was no error in the console too.

### supporting information:

 - `npm -v` prints: 5.6.0
 - `node -v` prints: 8.9.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows

**Comment by dkern** [comment]
Now the error disappeared, like nothing ever happen.

Is this normal, that after doing a publish the readme needs a while? Maybe since npmjs.com was updated? I never saw this issue/problem before by one of my packages.

**Comment by frankc60** [comment]
I get this problem now.. i've reverted README.md back to before, to a version that was working, `npm publish` and still says "**Unable to find a readme for jstrip@2.9.6**" 
[https://www.npmjs.com/package/jstrip](https://www.npmjs.com/package/jstrip)

- `npm -v` prints: 6.0.0
- `node -v` prints: 9.9.0
- Linux
The README.md is part of the package. Any ideas how to fix ?

**Comment by ElyaConrad** [comment]
I have the same problem when publishing a package. There exist a README.md but I get the message `Unable to find a readme for electron-photon@1.1.1` when looking at the package online. If I download the package from the registry using `npm install`, the README.md is contained normally as I expect.

**Comment by frankc60** [comment]
I have just retried my package, and it now works.. 

[https://www.npmjs.com/package/jstrip](https://www.npmjs.com/package/jstrip)

I didn't make any changes in `npm` since it was broken, so presume something their end. Hopefully everyone else's readme is back also

**Comment by kenany** [comment]
Issues with the website should be opened at <https://github.com/npm/www>. This repo is for the `npm` CLI specifically.

**Comment by liudonghua123** [comment]
I have the same problem when publishing a package. There exist a README.md but I get the message 
 `"Unable to find a readme for glade-ui-parse-cli@1.0.0"`
My published package is on https://www.npmjs.com/package/glade-ui-parse-cli

**Comment by legodude17** [comment]
@liudonghua123 I see a readme there.

**Comment by liudonghua123** [comment]
@legodude17 It's really strange, I can confirm that I got `"Unable to find a readme for glade-ui-parse-cli@1.0.0"` error yesterday.

**Comment by legodude17** [comment]
@liudonghua123 Do you see one now?

**Comment by liudonghua123** [comment]
@legodude17 , I can see the readme now.

**Comment by muenzpraeger** [comment]
It‘s missing the readme on my package now too.

https://www.npmjs.com/package/@muenzpraeger/sfdx-plugin

**Comment by kolkov** [comment]
It‘s missing the readme on my package v0.8.1 now too.
https://www.npmjs.com/package/@kolkov/angular-editor

**Comment by legodude17** [comment]
@kolkov I see a readme for that package.

**Comment by kolkov** [comment]
Yes! It's after uploading new version.

**Comment by abdulkhaderp** [comment]
I am getting "Unable to find a readme for react-digital-clock@0.1.0"
https://www.npmjs.com/package/react-digital-clock

**Comment by rodrigomf24** [comment]
Did anyone find a solution for this? I can't see the README.md for my package https://www.npmjs.com/package/@assured-plus/mmf-cli

**Comment by abdulkhaderp** [comment]
I just published again, now everything works fine.
https://www.npmjs.com/package/react-digital-clock
