### ISSUE TITLE
"npm install" exited with code 1

### ISSUE THREAD

**Issue by Johnson-Zhou** [npm/npm#20525]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ x] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### How can the CLI team reproduce the problem?

D:\TestWebapp>git push azure1 master --forceCounting objects: 58, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (55/55), done.
Writing objects: 100% (58/58), 67.24 KiB | 0 bytes/s, done.
Total 58 (delta 3), reused 0 (delta 0)
remote: Updating branch 'master'.
remote: Updating submodules.
remote: Preparing deployment for commit id '1f636333f7'.
remote: Generating deployment script.
remote: Project file path: .\TestWebapp.csproj
remote: Generated deployment script files
remote: Running deployment command...
remote: Handling ASP.NET Core Web Application deployment.
remote:   Restoring packages for D:\home\site\repository\TestWebapp.csproj...
remote:   Restore completed in 318.64 ms for D:\home\site\repository\TestWebapp.csproj.
remote: .
remote:   Generating MSBuild file D:\home\site\repository\obj\TestWebapp.csproj.nuget.g.props.
remote:   Generating MSBuild file D:\home\site\repository\obj\TestWebapp.csproj.nuget.g.targets.
remote:   Restore completed in 5.96 sec for D:\home\site\repository\TestWebapp.csproj.
remote: Microsoft (R) Build Engine version 15.6.82.30579 for .NET Core
remote: Copyright (C) Microsoft Corporation. All rights reserved.
remote:
remote:   Restore completed in 289.24 ms for D:\home\site\repository\TestWebapp.csproj.
remote:   Restore completed in 408.1 ms for D:\home\site\repository\TestWebapp.csproj.
remote: .............
remote:   TestWebapp -> D:\home\site\repository\bin\Release\netcoreapp2.0\TestWebapp.dll
remote: ................................................................................
remote: EXEC : npm ERR! error : Invalid Package: expected types/webpack-env but found @types/webpack-env [D:\home\site\repository\TestWebapp.csproj]
remote:   npm ERR!     at D:\Program Files (x86)\npm\1.4.28\node_modules\npm\lib\cache\add-local-tarball.js:161:14
remote:   npm ERR!     at process._tickCallback (node.js:448:13)
remote:   npm ERR! If you need help, you may report this *entire* log,
remote:   npm ERR! including the npm and node versions, at:
remote:   npm ERR!     <http://github.com/npm/npm/issues>
remote:
remote:   npm ERR! System Windows_NT 6.2.9200
remote:   npm ERR! command "node" "D:\\Program Files (x86)\\npm\\1.4.28\\node_modules\\npm\\bin\\npm-cli.js"
"install"
remote:   npm ERR! cwd D:\home\site\repository
remote:   npm ERR! node -v v0.10.40
remote:   npm ERR! npm -v 1.4.28
remote:   npm
remote: D:\home\site\repository\TestWebapp.csproj(39,5): error MSB3073: The command "npm install" exited with code 1.
remote: Failed exitCode=1, command=dotnet publish "D:\home\site\repository\TestWebapp.csproj" --output "D:\local\Temp\8d5b3618a92d434" --configuration Release
remote: An error has occurred during web site deployment.
remote:
remote: Error - Changes committed to remote repository but deployment to website failed.
To https://azuretoolkit-johnsonzhou.scm.azurewebsites.net:443/azuretoolkit-johnsonzhou.git
 + 8a3afca...1f63633 master -> master (forced update)

### supporting information:

 - `npm -v` prints:
6.0.0

 - `node -v` prints:
v8.11.1

 - `npm config get registry` prints:
https://registry.npmjs.org/

 - Windows, OS X/macOS, or Linux?:
Windows

 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
This error is because that remote system has an unsupported version of Node.js and `npm`. You can see this in the log you have posted:

```
remote: npm ERR! node -v v0.10.40
remote: npm ERR! npm -v 1.4.28
```

Because these versions are no longer supported, because they are years old, I will close this issue.

**Comment by Johnson-Zhou** [comment]
Hi KenanY, 
One further question, the remote system is Azure. How come they need such version, any clue or advice on solving it?

**Comment by kenany** [comment]
I'm not familiar enough with Azure to give you a good answer :(
