### ISSUE TITLE
adduser command print:  Account creation denied

### ISSUE THREAD

**Issue by TaroXin** [npm/npm#20521]
#### I'm opening this issue because:

  - [ ] npm is doing something I don't understand.

#### What's going wrong?

Whether I execute the `adduser` command on the command line or register directly on the `npmjs.com` website will show the same result.

![tim 20180505195852](https://user-images.githubusercontent.com/19855713/39663099-5ee937ce-509f-11e8-8d65-8b2e395cfa08.png)

![tim 20180505200426](https://user-images.githubusercontent.com/19855713/39663102-7b15f3d8-509f-11e8-95ab-57b3ebcafbdb.png)

### supporting information:

 - `npm -v` prints: 4.6.1
 - `node -v` prints: v8.11.1
 - `npm config get registry` prints: http://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows 8.1

**Comment by uestc-ym** [comment]
i also met this problem.

**Comment by legodude17** [comment]
Please contact support@npmjs.com.

**Comment by IEfucker** [comment]
Same issue, and contact support@npmjs.com, but no answer

**Comment by IEfucker** [comment]
@TaroXin #20418 ，signing up with gmail is OK

**Comment by TaroXin** [comment]
I have just tried many times, and the password input format has been successful. I think the password question should at least be clear about password.
