### ISSUE TITLE
Emojis (and possibly other unicode characters) are displayed incorrectly on www.npmjs.com

### ISSUE THREAD

**Issue by wwalc** [npm/npm#20531]
Emojis included in README files are displayed as garbage characters on package page.

In CKEditor 5 README file we use an exclamation mark to warn users:

![screen shot 2018-05-07 at 11 25 58](https://user-images.githubusercontent.com/545175/39695018-78faa71a-51e9-11e8-83c8-1492256445d8.png)

Source: https://github.com/ckeditor/ckeditor5/blob/15a108f809d5fd551f76d6823d0712ddab9bc9cc/README.md#-this-package-does-not-contain-any-source-code

When this readme is displayed on npm, it looks like this:

![screen shot 2018-05-07 at 11 27 54](https://user-images.githubusercontent.com/545175/39695100-b50bf40c-51e9-11e8-8cb8-1dc2444e9728.png)
(https://www.npmjs.com/package/ckeditor5#%C3%A2%C5%A1--this-package-does-not-contain-any-source-code)

#### GitHub (markdown)

https://github.com/wwalc/ckeditor5-emoji/blob/55186ce30455ecc0d011bdf09ef5cf7a0dc17145/README.md#-enabling-the-emoji-plugin

![screen shot 2018-05-07 at 11 29 34](https://user-images.githubusercontent.com/545175/39695159-f4bd6a2c-51e9-11e8-985b-a45fe669763c.png)

#### npmjs.com

https://www.npmjs.com/package/@wwalc/ckeditor5-emoji#%C3%B0%C3%BF%CB%9C%C5%BE-enabling-the-emoji-plugin

![screen shot 2018-05-07 at 11 29 42](https://user-images.githubusercontent.com/545175/39695164-f630bc9c-51e9-11e8-92f2-77e308585bc9.png)

What's even worse, even dash (`–`) characters are broken.

#### GitHub (markdown)

![screen shot 2018-05-07 at 11 33 26](https://user-images.githubusercontent.com/545175/39695349-86caeba6-51ea-11e8-8e92-9e99a6616a54.png)

#### npmjs.com

![screen shot 2018-05-07 at 11 33 32](https://user-images.githubusercontent.com/545175/39695355-8876ea2c-51ea-11e8-9b52-917a84215e3e.png)

Below is the version of node/npm used for publishing the plugin:
 * Node 6.9.1
 * npm 4.6.1
 * OSX 10.13.3 (17D47)

**Comment by kenany** [comment]
I think this would be best opened over at <https://github.com/npm/www>.

**Comment by wwalc** [comment]
Ooops indeed, thanks. It is reported there already: https://github.com/npm/www/issues/398
