### ISSUE TITLE
While NPM installation, i am getting below issue

### ISSUE THREAD

**Issue by creative-dev90** [npm/npm#20555]
npm ERR! code E503
npm ERR! 503 Service Unavailable: @angular/cli@latest

**Comment by creative-dev90** [comment]
![issue](https://user-images.githubusercontent.com/16410435/39798363-cde31ec4-5392-11e8-973e-b41ad2c8f6fe.PNG)

**Comment by legodude17** [comment]
What is the result of `npm config get registry`?

**Comment by creative-dev90** [comment]
Issue close. Working for me now
