### ISSUE TITLE
Error: Could not symlink include/node/openssl/archs/BSD-x86_64/asm/crypto/buildinf.h

### ISSUE THREAD

**Issue by josuevalrob** [npm/npm#20551]
- [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### How can the CLI team reproduce the problem?

I am trying to install node after a bad and messy installation. 
1) Uninstallation process: `brew uninstall node;`
2) installation process:  `brew install node` 

> MacBook-Pro:~ josue$ brew install node 
> ==> Downloading https://homebrew.bintray.com/bottles/node-10.0.0.high_sierra.bot
> Already downloaded: /Users/josue/Library/Caches/Homebrew/node-10.0.0.high_sierra.bottle.tar.gz
> ==> Pouring node-10.0.0.high_sierra.bottle.tar.gz
> Error: The `brew link` step did not complete successfully
> The formula built, but is not symlinked into /usr/local
> Could not symlink include/node/openssl/archs/BSD-x86_64/asm/crypto/buildinf.h
> /usr/local/include/node/openssl/archs/BSD-x86_64/asm/crypto is not writable.
> 
> You can try again using:
>   brew link node
> ==> Caveats
> Bash completion has been installed to:
>   /usr/local/etc/bash_completion.d
> ==> Summary
> 🍺  /usr/local/Cellar/node/10.0.0: 5,301 files, 51.5MB

Trying `brew link node`

> Linking /usr/local/Cellar/node/10.0.0... 
> Error: Could not symlink include/node/openssl/archs/BSD-x86_64/asm/crypto/buildinf.h
> /usr/local/include/node/openssl/archs/BSD-x86_64/asm/crypto is not writable.

### supporting information:

Homebrew 1.6.3
MacOs HighSierra 10.13.4

 - Network issues: No
 - Container: No

**Comment by josuevalrob** [comment]
I changed the permissions in: 
` sudo chmod -R 777 /usr/local/include/node/openssl/`
Then `brew link --overwrite node`
and then... 
```
MacBook-Pro:~ josue$ node --version
v10.0.0
MacBook-Pro:~ josue$ npm --version
5.6.0
```

**Comment by legodude17** [comment]
How is this an issue with `npm`?
