### ISSUE TITLE
npm v6.0.0 is throwing errors on install

### ISSUE THREAD

**Issue by trickeyone** [npm/npm#20553]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Since upgrading to npm v6.0.0, npm-audit-report is throwing errors. I have logged an issue in that repo, as well, npm/npm-audit-report#9.

> 69 verbose stack TypeError: Object.entries is not a function
69 verbose stack     at Object.report [as install] (/usr/local/lib/node_modules/npm/node_modules/npm-audit-report/reporters/install.js:27:31)
69 verbose stack     at Promise (/usr/local/lib/node_modules/npm/node_modules/npm-audit-report/index.js:18:46)
69 verbose stack     at report (/usr/local/lib/node_modules/npm/node_modules/npm-audit-report/index.js:17:10)
69 verbose stack     at Object.printInstallReport (/usr/local/lib/node_modules/npm/lib/install/audit.js:87:10)
69 verbose stack     at Object.Installer.printInstalledForHuman (/usr/local/lib/node_modules/npm/lib/install.js:847:31)
69 verbose stack     at Bluebird.try.then (/usr/local/lib/node_modules/npm/lib/install.js:774:19)
69 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
69 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
69 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
69 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
69 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
69 verbose stack     at Async._drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
69 verbose stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
69 verbose stack     at Immediate.Async.drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
69 verbose stack     at runCallback (timers.js:672:20)
69 verbose stack     at tryOnImmediate (timers.js:645:5)

#### How can the CLI team reproduce the problem?
I have attached the full [npm-debug.log](https://gist.github.com/trickeyone/5872ed57f1440099e6511c7fbce70bd3?file=npm-debug.log)

### supporting information:

 - `npm -v` prints: 6.0.0
 - `node -v` prints: v6.11.4
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by hezihua** [comment]
npm 6.00 throw  a  error   when  install  webpack-dev-server，

**Comment by ljharb** [comment]
I'm seeing errors like this on *tons* of repos: https://travis-ci.org/ljharb/es-to-primitive/jobs/376561038#L451

**Comment by mathieudutour** [comment]
Looks like it has already been fixed: https://github.com/npm/npm-audit-report/commit/8814da0e35e1f77dd3f733e6efc592f5168afc00

So I'm guessing it's just a matter of deploying a new version?

**Comment by ljharb** [comment]
That commit was released in v1.0.6+ of that package, and npm 6 specifies `"npm-audit-report": "^1.0.5",`, so it should be including it :-/

**Comment by ljharb** [comment]
aha - that commit seems to have been removed in v1.0.9, which is now the latest: https://github.com/npm/npm-audit-report/issues/9#issuecomment-387639773

**Comment by gucong3000** [comment]
+1 for me

https://ci.appveyor.com/project/gucong3000/gulp-reporter/build/1442/job/6ajvg42ydg2wdds2

node 6.14.1 (x86)
npm@6.0.0

**Comment by ljharb** [comment]
Setting the `NPM_CONFIG_AUDIT` env var to `"false"` will bypass the error.

**Comment by jwalton** [comment]
Can we please see an npm 6.0.1 that fixes this?  This is breaking all my repos on travis.  @ljharb 's hack is nice, but I don't want to set up that hack everywhere and then have to remove it later.

**Comment by zkat** [comment]
@jwalton #20567

**Comment by zkat** [comment]
Since the fix for this bug is merged and tagged, I'm gonna close this. It's already in `npm@next` and will be in `npm@latest`... soon, if not early tomorrow.
