### ISSUE TITLE
[6.0.1] `npm audit -h` output strange

### ISSUE THREAD

**Issue by alexander-akait** [npm/npm#20572]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Output:
```
npm audit

```

#### How can the CLI team reproduce the problem?

```
npm audit -h
```

### supporting information:

 - `npm -v` prints: 6.0.1
 - `node -v` prints: v8.11.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by whyboris** [comment]
I don't understand the context. Is the concern that `npm audit` doesn't work?
This could be related: https://github.com/npm/npm/issues/20436

**Comment by alexander-akait** [comment]
@whyboris it is just nothing on help command

**Comment by bjornstar** [comment]
I also found it very confusing that `npm audit --help` does not output anything besides the name of the command.

**Comment by kolbma** [comment]
@bjornstar yes, it looks unfinished

**Comment by legodude17** [comment]
What should it print? That is the usage.

**Comment by mnespor** [comment]
When I invoked `npm audit --help`, I was looking for a list of supported flags (to see whether dev dependencies could be excluded from the output)

**Comment by legodude17** [comment]
That's what the man pages are for. Or the `docs` folder.

**Comment by alexander-akait** [comment]
@legodude17 release `audit` command in `npm@6` without `help` information is very horrible. I spent around 20-30 minutes on search information about this.

**Comment by maxpaj** [comment]
> @mnespor 
> When I invoked npm audit --help, I was looking for a list of supported flags (to see whether dev dependencies could be excluded from the output)

Looking for that aswell. 

And choosing which severity level that you'd like to see relevant output for.

**Comment by legodude17** [comment]
@maxpaj there are feature requests for that, but those haven't been added yet. The reason it is so sparse is because there aren't that many options for it. It will get more substantial as more features are added.

**Comment by zkat** [comment]
This is pretty much in-line with what `-h` prints for all other commands. The version of `npm audit` in 6.0.1 doesn't really have "common flags" for it to use because it's pretty barebones. The version in the upcoming `6.1.0` will include more options and features, and you can expect a bit more from that.

If you want to see more details about any npm command, the way to get "verbose" information is through `npm help <cmd>`. Audit has a pretty decent manpage, which can also be seen over in [the docs site for npm](https://docs.npmjs.com/cli/audit). It'll also come with improvements when 6.1.0 (and `npm audit fix`) come out.
