### ISSUE TITLE
footgun: npm i --package-lock-only

### ISSUE THREAD

**Issue by bjornstar** [npm/npm#20584]
#### I'm opening this issue because:

npm is doing something I don't understand.

#### What's going wrong?

I have package-lock disabled because I don't want to have to constantly wrestle with it.

I tried out the npm audit command and it told me that I can't use it unless I have a package-lock file. So I ran the command it gave me, but no package-lock file was generated.

```
$ npm audit
npm ERR! code EAUDITNOLOCK
npm ERR! audit Neither npm-shrinkwrap.json nor package-lock.json found: Cannot audit a project without a lockfile
npm ERR! audit Try creating one first with: npm i --package-lock-only

$ npm install --package-lock-only
up to date in 1.191s

$ echo $?
0

$ ls package-lock.json
ls: cannot access package-lock.json: No such file or directory
```

I ran a command asking for the `package-lock.json` file to be generated, but it was not. No error was given, `npm` said everything was fine, but the task I asked it to perform did not happen.

I expected npm to create a `package-lock.json` file because I explicitly asked it to even though I have it configured to not automatically create a `package-lock.json` file.

#### How can the CLI team reproduce the problem?

```
npm config set package-lock false
npm install --package-lock-only
ls package-lock.json
```

### supporting information:

 - `npm -v` prints: 6.0.1
 - `node -v` prints: v8.11.1

**Comment by legodude17** [comment]
I think it makes sense for `package-lock` being `false` to override `--package-lock-only`.

**Comment by strugee** [comment]
@legodude17 why? If you're explicitly requesting for it to be generated in the local project, why should global configuration override that? Plus, if `package-lock = false` did override the CLI flag, how are users supposed to generate `package-lock.json` when they need it, for example for `npm audit`?

**Comment by legodude17** [comment]
@strugee Because you are requiring that `npm` not use the `package-lock` code at all. Anyway, `npm i --package-lock --package-lock-only` should work.

**Comment by bjornstar** [comment]
So the fix could be instructing users to:

`Try creating one first with: npm i --package-lock`

As that appears to actually accomplish the goal of installing the package-lock file regardless of the config.

**Comment by zkat** [comment]
Closing this in favor of https://npm.community/t/audit-and-package-lock-only/107 and moving further discussion over there.
