### ISSUE TITLE
Can't publish module

### ISSUE THREAD

**Issue by vdekameron** [npm/npm#20591]
Sorry. I am beginner. I try to publish module with npm publish (before this I created user with npm adduser)....but I have Error403
" You do not have permission to publish "mymodule". Are you logged in as the correct user? : mymodule"
What I do wrong?

**Comment by legodude17** [comment]
Has the module been published before?

**Comment by vdekameron** [comment]
By me not. I try to rename module and it's start working. Maybe this name already was there. Don't know.

**Comment by legodude17** [comment]
It probably was. Is everything working now?

**Comment by vdekameron** [comment]
Yes! Thank you for desire to help!!!

**Comment by legodude17** [comment]
Great! @KenanY can you close this?
