### ISSUE TITLE
npm suspends nodejs on Windows 10

### ISSUE THREAD

**Issue by akshaybabloo** [npm/npm#20598]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I was trying to uninstall `@angular/cli` and the Windows suspends Nodejs and npm.

**update**

I tried updating npm to its latest version and it looks like the suspension happens only if I use global installs.

#### How can the CLI team reproduce the problem?

Maybe by upgrading to Windows 10 1803

### supporting information:

 - `npm -v` prints: 5.8.0
 - `node -v` prints: v8.11.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [x] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
Does the process just silently fail or is an error generated?

**Comment by akshaybabloo** [comment]
Just fails. No error at all.

**Comment by legodude17** [comment]
Do you have an antivirus installed?

**Comment by akshaybabloo** [comment]
Yes. I do. ESET.

**Comment by legodude17** [comment]
Try disabling it.

**Comment by akshaybabloo** [comment]
I tried it I get the same error.

**Comment by akshaybabloo** [comment]
`ESET > Setup > Network Protection > Connected Networks - If this is set to Public try changing to Private.` fixed the problem.
