### ISSUE TITLE
npm audit should have a non-zero exit code if there are vulnerabilities found

### ISSUE THREAD

**Issue by westy92** [npm/npm#20593]
#### What's the feature?
If vulnerabilities are found, a non-zero exit code should be returned.

#### What problem is the feature intended to solve?
I'd like to run `npm audit` in a CI workflow and fail the build if vulnerabilities are found.

#### Is the absence of this feature blocking you or your team? If so, how?
No, we're currently still using raw nsp.

#### Is this feature similar to an existing feature in another tool?
https://snyk.io/docs/using-snyk: "Use `snyk test` in your test scripts. If a vulnerability is found, the process will exit with a non-zero exit code."

#### Is this a feature you're prepared to implement, with support from the npm CLI team?
I'll help as much as I can.

**Comment by welwood08** [comment]
In my testing, this already happens so I think you just need to update to 6.0.1.

From the release notes:
> - d04656461 Exit with non-zero status when vulnerabilities are found. So you can have npm audit as a test or prepublish step!

**Comment by westy92** [comment]
I've confirmed this is working in 6.0.1. Thank you!
