### ISSUE TITLE
NPM doesn't upgrade

### ISSUE THREAD

**Issue by selfisekai** [npm/npm#20601]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [x] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
When I try to upgrade my 5.6.0 npm to latest version it doesn't actually do anything
![obraz](https://user-images.githubusercontent.com/11798442/39962678-8f18846a-5656-11e8-9e5a-a6eb0c5fec84.png)

#### How can the CLI team reproduce the problem?
NPM doesn't log anything. 
It's reproducible on my PC, but I don't know how to reproduce it on another one.

### supporting information:

 - `npm -v` prints: `5.6.0`
 - `node -v` prints: `v10.0.0`
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?: Linux Ubuntu 17.10
 - Network issues:
   - Geographic location where npm was run: Poland
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
Can you run `npm prefix -g`, `which npm` and `echo "$PATH"` and post the output here?

**Comment by selfisekai** [comment]
@legodude17 

`npm prefix -g`: `/home/m-karas/.nvm/versions/node/v10.0.0`

`which npm`: `/home/m-karas/.nvm/versions/node/v10.0.0/bin/npm`

`echo "$PATH"`: `/home/m-karas/.nvm/versions/node/v10.0.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/opt`

**Comment by legodude17** [comment]
What happens if you run `npm i -g npm` (without `sudo`)?

**Comment by selfisekai** [comment]
@legodude17 

Wow, thank you! It finally worked!

```sh
m-karas@m-ka:~$ npm i -g npm
/home/m-karas/.nvm/versions/node/v10.0.0/bin/npx -> /home/m-karas/.nvm/versions/node/v10.0.0/lib/node_modules/npm/bin/npx-cli.js
/home/m-karas/.nvm/versions/node/v10.0.0/bin/npm -> /home/m-karas/.nvm/versions/node/v10.0.0/lib/node_modules/npm/bin/npm-cli.js
+ npm@6.0.1
added 246 packages, removed 40 packages and updated 125 packages in 16.755s
m-karas@m-ka:~$ npm -v
6.0.1
```
