### ISSUE TITLE
Unable to install karma-phantomjs-launcher

### ISSUE THREAD

**Issue by NishaBhat** [npm/npm#20618]
npm install karma-phantomjs-launcher --save-dev
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules\fse
vents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Error: EPERM: operation not perm
itted, rename 'C:\angular-ui-tree\VDOT_Activation\node_modules\.st
aging\fsevents-eb6ed78b\node_modules\needle' -> 'C:\angular-ui-tre
e\VDOT_Activation\node_modules\.staging\needle-907ab7b6'

npm ERR! path C:\angular-ui-tree\VDOT_Activation\node_modules\es6-
promise
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename 'C:\angular-ui-tree\VDOT_Activation\node_modules\es6-promise' -> 'C:\angul
ar-ui-tree\VDOT_Activation\node_modules\.es6-promise.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\AppData\Roaming\npm-cache\_logs\2018-05-14T23_55_00_18
3Z-debug.log

**Comment by legodude17** [comment]
What is the result of `npm -v` and `node -v`?

**Comment by NishaBhat** [comment]
npm -v -> 5.6.0
node -v v8.9.3

**Comment by legodude17** [comment]
Does this still occur on `npm@6`?

**Comment by NishaBhat** [comment]
Hello,
Thank you for your prompt response
I updated the version of npm to 6.0.1
npm install karma-phantomjs-launcher --save-dev
npm WARN karma-phantomjs-launcher@1.0.4 requires a peer of karma@>=0.9 but none
is installed. You must install peer dependencies yourself.

npm ERR! path C:\angular-ui-tree\VDOT_Activation\node_modules\body
-parser\node_modules\ms
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename 'C:\angu
lar-ui-tree\VDOT_Activation\node_modules\body-parser\node_modules\ms' -> 'C:\angular-ui-tree\VDOT_Activation\node_modules\extract-zip\node_modules
\ms'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\AppData\Roaming\npm-cache\_logs\2018-05-15T20_55_23_58
4Z-debug.log

This is what I have in package.json for karma version  "karma": "^2.0.2",

**Comment by NishaBhat** [comment]
Hello, The issue is fixed looks like I was missing C:\Users\<username>\AppData\Roaming\npm; from my Path environment variable
