### ISSUE TITLE
Timestamps on package files corrupted causing tools like Yarn to skip installing of updates

### ISSUE THREAD

**Issue by RavenHursT** [npm/npm#20615]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
✅ npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Timestamps on installed packages are showing incorrect dates (some in 1985). This is causing `yarn` to fail to do updates on certain packages.

#### How can the CLI team reproduce the problem?

Please see this ticket on the `yarn` project: https://github.com/yarnpkg/yarn/issues/5723#issue-317350801

### supporting information:

 - `npm -v` prints: 
```
$ npm -v
5.6.0


   ╭─────────────────────────────────────╮
   │                                     │
   │   Update available 5.6.0 → 6.0.1    │
   │       Run npm i npm to update       │
   │                                     │
   ╰─────────────────────────────────────╯
```
 - `node -v` prints:
```
$ node -v
v10.1.0
```
 - `npm config get registry` prints:
`https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?: OS X
 - Network issues:
   - Geographic location where npm was run: Nashville, TN
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
Please update to the latest version of `npm` with `npm install -g npm@latest`.

**Comment by RavenHursT** [comment]
@legodude17 has `npm@5.6.0` been depricated or something?

**Comment by legodude17** [comment]
Not AFAIK, but there are a lot of bugfixes in newer versions and this might be fixed in them.

**Comment by RavenHursT** [comment]
Yeah.. but not all of us have the ability to "just upgrade".. there's a lot of down-stream factors to consider.. 

If this is an issue in `npm@5.x` then it's still a bug, right?

**Comment by legodude17** [comment]
That's not my call to make, I was just wondering if it was changed.

**Comment by RavenHursT** [comment]
Ahhh.. ok.. sorry.. sounded like that was going to be the "solution" :D

**Comment by RavenHursT** [comment]
Well.. just for brevity.. I upgraded `npm` locally and still seeing the same result :-/

```
$ npm -v
6.0.1
$ mkdir foo
$ cd foo
$ yarn init
yarn init v1.6.0
(node:46212) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
question name (foo):
question version (1.0.0):
question description:
question entry point (index.js):
question repository url:
question author:
question license (MIT):
question private:
success Saved package.json
✨  Done in 5.88s.
$ yarn add ember-source@3.1.0
yarn add v1.6.0
(node:46310) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 52 new dependencies.
info Direct dependencies
└─ ember-source@3.1.0
.
.
.
$ cat package.json
{
  "name": "foo",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "ember-source": "3.1.0"
  }
}
$ vim package.json // changed to 3.1.1
$ cat package.json
{
  "name": "foo",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "ember-source": "3.1.1"
  }
}
$ yarn
yarn install v1.6.0
(node:46350) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
✨  Done in 0.71s.
$ cat node_modules/ember-source/package.json
{
  "name": "ember-source",
  "version": "3.1.0"
.
.
.

// Nuking node_modules and reinstalling results in proper package version being installed
$ rm -rf node_modules/
$ cat node_modules/ember-source/package.json
{
  "name": "ember-source",
  "version": "3.1.1"
.
.
.
```

**Comment by legodude17** [comment]
So this isn't an issue with the CLI? You never even invoked the CLI. Or is this an issue with `publish`ing?

**Comment by RavenHursT** [comment]
Huh? `yarn` utilizes `npm` under the hood.. that's why this issue is linked with https://github.com/yarnpkg/yarn/issues/5723

Did you read through that one?  `yarn` is saying the problem is corrupted `npm` timestamps.

**Comment by legodude17** [comment]
What do you mean by "under the hood"? `yarn` is its own package manager, even if it uses the `npm` registry. AFAIK, your local `yarn` will never call your local `npm`. As I said, it appears to be a problem with the timestamps being corrupted _during publishing_.

**Comment by RavenHursT** [comment]
Look.. I don't know @legodude17 .... all I know is, `yarn` is failing to update packages properly and they're saying it's got something to do w/ `npm`... was just trying to help cross-reference the issues and shed some light on a potentially serious situation (bad timestamps).

Close the issue, change, it, whatever.. I don't know enough about `yarn` and `npm` internals to argue the solution w/ you..

**Comment by legodude17** [comment]
I'm not trying to argue with you, sorry if it seemed like I was. I think this is an issue with `publish` in current and/or old versions.

**Comment by legodude17** [comment]
@RavenHursT I think I found the problematic line, it appears to be [here](https://github.com/npm/npm/blob/latest/lib/pack.js#L157) in `lib/pack.js`.

**Comment by RavenHursT** [comment]
Oh wow.... Love that comment lol!

**Comment by zkat** [comment]
This is intentional :)

**Comment by zkat** [comment]
Closing in favor of https://npm.community/t/tarball-content-timestamps-locked-to-1985/149, which explains the situation.
