### ISSUE TITLE
Cannot install google/marzipano (alias marzipano)

### ISSUE THREAD

**Issue by alexandrahrastnik** [npm/npm#20614]
#### I'm opening this issue because:

I need to install google/marzipano (npm package name "marzipano") and the install command crashes.

#### What's going wrong?

Package is not installed, npm throws an error and tells me to open an issue if I need help.

#### How can the CLI team reproduce the problem?

I executed "npm i marzipano --save" in my project folder.
First I added marzipano (using VS Code Intellisense) manually to my package.json file and executed "npm i", and it crashed.

[npm-debug.log](https://github.com/npm/npm/files/2000875/npm-debug.log)

### supporting information:

 - `npm -v` prints: 4.0.5
 - `node -v` prints: v7.4.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows 10

**Comment by legodude17** [comment]
Try updating `npm` to the latest version with `npm i -g npm@latest`.

**Comment by alexandrahrastnik** [comment]
I updated npm and node to the latest versions, but that didn't solve the issue.
- `npm -v` prints: 6.0.1
- `node -v` prints: v10.1.0

new logfile of `npm i marzipano --save`:
[2018-05-15T05_26_16_294Z-debug.log](https://github.com/npm/npm/files/2003557/2018-05-15T05_26_16_294Z-debug.log)

**Comment by legodude17** [comment]
Do you have a stable internet connection? Do you have a proxy?

**Comment by alexandrahrastnik** [comment]
I have a stable internet connection, and we're using some proxy service called Checkpoint Sandblast.
Do you think it's a network issue? Marzipano was and is the only package I've had trouble ever since.
Anyway: I already worked around this problem and downloaded the desired package manually.

**Comment by legodude17** [comment]
I think it was a proxy issue.
