### ISSUE TITLE
Unable to reset password.

### ISSUE THREAD

**Issue by EasonWang01** [npm/npm#20625]
<img width="675" alt="sdfdsf" src="https://user-images.githubusercontent.com/11001914/40059310-5bf3d6e8-5886-11e8-9adf-1352cfd3e3d6.png">

Always return this.

**Comment by legodude17** [comment]
Please report this at the [registry issue tracker](https://github.com/npm/www/issues).

**Comment by kenany** [comment]
Yeah, this issue tracker is for issues with the CLI specifically.

**Comment by EasonWang01** [comment]
I already reported for four month but no response.
