### ISSUE TITLE
CERT_UNTRUSTED

### ISSUE THREAD

**Issue by chinalinux2012** [npm/npm#20637]
#### What's going wrong?
- [ ] when I ran the  command:  npm install -g create-react-native-app, the following error occured:
npm http GET https://registry.npmjs.org/create-react-native-app
npm http GET https://registry.npmjs.org/create-react-native-app
npm http GET https://registry.npmjs.org/create-react-native-app
npm ERR! Error: CERT_UNTRUSTED
npm ERR!     at SecurePair.<anonymous> (tls.js:1430:32)
npm ERR!     at SecurePair.emit (events.js:92:17)
npm ERR!     at SecurePair.maybeInitFinished (tls.js:1029:10)
npm ERR!     at CleartextStream.read [as _read] (tls.js:521:13)
npm ERR!     at CleartextStream.Readable.read (_stream_readable.js:341:10)
npm ERR!     at EncryptedStream.write [as _write] (tls.js:418:25)
npm ERR!     at doWrite (_stream_writable.js:226:10)
npm ERR!     at writeOrBuffer (_stream_writable.js:216:5)
npm ERR!     at EncryptedStream.Writable.write (_stream_writable.js:183:11)
npm ERR!     at write (_stream_readable.js:602:24)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-696.23.1.el6.x86_64
npm ERR! command "node" "/usr/bin/npm" "install" "create-react-native-app"
npm ERR! cwd /root
npm ERR! node -v v0.10.48
npm ERR! npm -v 1.3.6
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /root/npm-debug.log
npm ERR! not ok code 0

### supporting information:

 - `npm -v` prints: 1.3.6
 - `node -v` prints: v0.10.48
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux

**Comment by legodude17** [comment]
Your node and npm versions are years old and no longer supported. Please upgrade.

**Comment by zhanyong001** [comment]
how to upgrade?

**Comment by legodude17** [comment]
Go to https://nodejs.org/en/download/ and follow the instructions.

**Comment by kenany** [comment]
Closing since we haven't supported these versions of Node.js and `npm` for a few years now.
