### ISSUE TITLE
Circular dependencies with top-level package

### ISSUE THREAD

**Issue by medikoo** [npm/npm#2063]
Package __A__ depends on package __B__ and package __B__ depends on package __A__.

When I do `npm install` in folder of package __A__, npm installs __B__ into _A/node_modules_ but won't install __A__ into _A/node_modules/B/node_modules_. Seems logical at first, however if __A__ is my top-level package not placed in any _node_modules_ folder then it will not run as __B__ won't see __A__ (e.g. Travis CI - crashes tests for packages with such dependencies).

Is this npm bug or is there any known resolution for that ?

**Comment by trusktr** [comment]
Is this fixed with NPM v3?

**Comment by dominykas** [comment]
Seems like it is.

I published two packages:
* https://www.npmjs.com/package/@dominykas/test-one
* https://www.npmjs.com/package/@dominykas/test-two

`test-two` depends on `test-one` and is published
`test-one` depends on `test-two` (but isn't published, although that's probably irrelevant - but I wanted to make sure `package.json` has the exact same dependency versions)

Cloning https://github.com/dominykas/test-one and running npm i inside of it results in:
```
dominykas@patti ~/devel/experiments/test-one $ npm ls
@dominykas/test-one@1.0.0 /Users/dominykas/devel/experiments/test-one
└─┬ @dominykas/test-two@1.1.0
  └── @dominykas/test-one@1.0.0
```

**Comment by othiym23** [comment]
Closing as resolved!
