### ISSUE TITLE
CLI: new version link - loose the trailing `:`

### ISSUE THREAD

**Issue by thetrompf** [npm/npm#20669]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

```
   ╭────────────────────────────────────────────────────────────────╮  
   │                                                                │  
   │       New patch version of npm available! 6.0.0 → 6.0.1        │  
   │   Changelog: https://github.com/npm/npm/releases/tag/v6.0.1:   │  
   │               Run npm install -g npm to update!                │  
   │                                                                │  
   ╰────────────────────────────────────────────────────────────────╯
```

loose the trailing `:` in the link, as the terminal recognizes it as a part of the URL
so when I `ctrl+click` the link in my terminal, the browser opens the following link: [https://github.com/npm/npm/releases/tag/v6.0.1:](https://github.com/npm/npm/releases/tag/v6.0.1:) (which is invalid) instead of [https://github.com/npm/npm/releases/tag/v6.0.1](https://github.com/npm/npm/releases/tag/v6.0.1)

#### How can the CLI team reproduce the problem?

Running an `npm install` in a projet with `npm@v6.0.0` and get update notice.

### supporting information:

 - `npm -v` prints: `6.0.0`
 - `node -v` prints: `v9.8.0`
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?: `Linux`
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [x] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
Ref #20536.

**Comment by zkat** [comment]
This is already fixed :)
