### ISSUE TITLE
github-email installation fail

### ISSUE THREAD

**Issue by al2helal** [npm/npm#20671]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--global',
1 verbose cli   'github-email' ]
2 info using npm@1.3.10
3 info using node@v0.10.25
4 verbose cache add [ 'github-email', null ]
5 verbose cache add name=undefined spec="github-email" args=["github-email",null]
6 verbose parsed url { protocol: null,
6 verbose parsed url   slashes: null,
6 verbose parsed url   auth: null,
6 verbose parsed url   host: null,
6 verbose parsed url   port: null,
6 verbose parsed url   hostname: null,
6 verbose parsed url   hash: null,
6 verbose parsed url   search: null,
6 verbose parsed url   query: null,
6 verbose parsed url   pathname: 'github-email',
6 verbose parsed url   path: 'github-email',
6 verbose parsed url   href: 'github-email' }
7 silly lockFile 7041f9cd-github-email github-email
8 verbose lock github-email /home/linux/.npm/7041f9cd-github-email.lock
9 silly lockFile 7041f9cd-github-email github-email
10 silly lockFile 7041f9cd-github-email github-email
11 verbose addNamed [ 'github-email', '' ]
12 verbose addNamed [ null, '*' ]
13 silly lockFile 47bd9826-github-email github-email@
14 verbose lock github-email@ /home/linux/.npm/47bd9826-github-email.lock
15 silly addNameRange { name: 'github-email', range: '*', hasData: false }
16 verbose url raw github-email
17 verbose url resolving [ 'https://registry.npmjs.org/', './github-email' ]
18 verbose url resolved https://registry.npmjs.org/github-email
19 info trying registry request attempt 1 at 15:44:53
20 http GET https://registry.npmjs.org/github-email
21 info retry will retry, error on last attempt: Error: CERT_UNTRUSTED
22 info trying registry request attempt 2 at 15:45:04
23 http GET https://registry.npmjs.org/github-email
24 info retry will retry, error on last attempt: Error: CERT_UNTRUSTED
25 info trying registry request attempt 3 at 15:46:17
26 http GET https://registry.npmjs.org/github-email
27 silly lockFile 47bd9826-github-email github-email@
28 silly lockFile 47bd9826-github-email github-email@
29 error Error: CERT_UNTRUSTED
29 error     at SecurePair.<anonymous> (tls.js:1370:32)
29 error     at SecurePair.EventEmitter.emit (events.js:92:17)
29 error     at SecurePair.maybeInitFinished (tls.js:982:10)
29 error     at CleartextStream.read [as _read] (tls.js:469:13)
29 error     at CleartextStream.Readable.read (_stream_readable.js:320:10)
29 error     at EncryptedStream.write [as _write] (tls.js:366:25)
29 error     at doWrite (_stream_writable.js:223:10)
29 error     at writeOrBuffer (_stream_writable.js:213:5)
29 error     at EncryptedStream.Writable.write (_stream_writable.js:180:11)
29 error     at write (_stream_readable.js:583:24)
30 error If you need help, you may report this log at:
30 error     <http://github.com/isaacs/npm/issues>
30 error or email it to:
30 error     <npm-@googlegroups.com>
31 error System Linux 4.2.0-42-generic
32 error command "/usr/bin/nodejs" "/usr/bin/npm" "install" "--global" "github-email"
33 error cwd /home/linux
34 error node -v v0.10.25
35 error npm -v 1.3.10
36 verbose exit [ 1, true ]

**Comment by legodude17** [comment]
Hello! Your `npm` and `node` versions are years old and no longer supported. Please upgrade.

**Comment by kenany** [comment]
Closing since we no longer support those versions.
