### ISSUE TITLE
unable to install node package "learnyounode"

### ISSUE THREAD

**Issue by tbhaxor** [npm/npm#20686]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [x] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Command i am running
```
┌─[terabyte@terabyte]─[~]
└──╼ $sudo npm install -g learnyounode
```

Error that i am getting while installation
```
npm WARN deprecated boganipsum@0.1.0: no longer maintained
npm WARN deprecated colors-tmpl@1.0.0: no longer maintained
Unhandled rejection Error: Command failed: /usr/bin/git submodule update -q --init --recursive/.staging/n
fatal: failed to stat '/root/.npm/_cacache/tmp/git-clone-f239803c': Permission denied

    at ChildProcess.exithandler (child_process.js:282:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:957:16)
    at Socket.stream.socket.on (internal/child_process.js:378:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close [as _onclose] (net.js:598:12)

npm ERR! cb() never called!

```
### supporting information:

 - `npm -v` prints: 6.0.1
 - `node -v` prints: v10.1.0
 - `n pm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Arch Linux
 - Network issues:
   - Geographic location where npm was run: India
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [x] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
Try running `npm i -g learnyounode` (without `sudo`).

**Comment by tbhaxor** [comment]
@legodude17  it was solved :+1: 
i forgot to close 

anyways thanks for your support :smiley:
