### ISSUE TITLE
https://go.npm.me/audit-guide cert expired

### ISSUE THREAD

**Issue by knod** [npm/npm#20685]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] npm is producing incorrect or undesirable behavior.
  - [x] Other (_see below for feature requests_): npm gives outdated information

#### What's going wrong?
I ran `npm audit` and was told to go to https://go.npm.me/audit-guide for more info. That site's certs expired yesterday.

#### How can the CLI team reproduce the problem?
I assume you just go to that site.

### supporting information:
The rest of this info is irrelevant.

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
I think this belongs in <https://github.com/npm/www>?

**Comment by knod** [comment]
Ah, didn't realize that existed. Thanks!
