### ISSUE TITLE
missing script:start

### ISSUE THREAD

**Issue by joycer1205** [npm/npm#20689]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/src/node-v6.14.0-linux-x64/bin/node',
1 verbose cli   '/usr/local/src/node-v6.14.0-linux-x64/bin/npm',
1 verbose cli   'start' ]
2 info using npm@3.10.10
3 info using node@v6.14.0
4 verbose stack Error: missing script: start
4 verbose stack     at run (/usr/local/src/node-v6.14.0-linux-x64/lib/node_modules/npm/lib/run-script.js:151:19)
4 verbose stack     at /usr/local/src/node-v6.14.0-linux-x64/lib/node_modules/npm/lib/run-script.js:61:5
4 verbose stack     at /usr/local/src/node-v6.14.0-linux-x64/lib/node_modules/npm/node_modules/read-package-json/read-json.js:356:5
4 verbose stack     at checkBinReferences_ (/usr/local/src/node-v6.14.0-linux-x64/lib/node_modules/npm/node_modules/read-package-json/read-json.js:320:45)
4 verbose stack     at final (/usr/local/src/node-v6.14.0-linux-x64/lib/node_modules/npm/node_modules/read-package-json/read-json.js:354:3)
4 verbose stack     at then (/usr/local/src/node-v6.14.0-linux-x64/lib/node_modules/npm/node_modules/read-package-json/read-json.js:124:5)
4 verbose stack     at /usr/local/src/node-v6.14.0-linux-x64/lib/node_modules/npm/node_modules/read-package-json/read-json.js:243:12
4 verbose stack     at /usr/local/src/node-v6.14.0-linux-x64/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
4 verbose stack     at tryToString (fs.js:457:3)
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:444:12)
5 verbose cwd /home/elk/kibana/plugins
6 error Linux 3.10.0-123.el7.x86_64
7 error argv "/usr/local/src/node-v6.14.0-linux-x64/bin/node" "/usr/local/src/node-v6.14.0-linux-x64/bin/npm" "start"
8 error node v6.14.0
9 error npm  v3.10.10
10 error missing script: start
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

this is my mistake.

my package.json
{
  "name": "traffic_light_vis",
  "version": "4.4.0-1.0",
  "description": "Traffic Light for Kibana Dashboards",
  "main": "gulpfile.js",
  "scripts": {
    "start": "gulp dev",
    "build": "gulp build",
    "package": "gulp package",
    "test": "gulp test"
  },
  "devDependencies": {
    "babel-core": "^4.1.8",
    "babel-eslint": "^4.1.8",
    "bluebird": "^3.2.2",
    "del": "^2.2.0",
    "eslint": "^1.10.3",
    "eslint-plugin-mocha": "^1.1.0",
    "gulp": "^3.9.0",
    "gulp-eslint": "^1.1.1",
    "gulp-gzip": "^1.2.0",
    "gulp-tar": "^1.8.0",
    "gulp-util": "^3.0.7",
    "lodash": "^4.3.0",
    "mkdirp": "^0.5.1",
    "rsync": "^0.4.0"
  }
}

**Comment by legodude17** [comment]
What is the path of your  package.json? Also, please update to the latest version of `npm`.

**Comment by mcclowes** [comment]
@joycer123 is this still an issue or can this be closed?

**Comment by kenany** [comment]
Closing as abandoned for now, since there hasn't been a reply since May. Can reopen if necessary.
