### ISSUE TITLE
Npm not installing in ubuntu 18.04

### ISSUE THREAD

**Issue by eeerrrttty** [npm/npm#20697]
[SUPORT TO UBUNTU 18.04 LTS]

I'm running nodejs 8.10 (after apt install nodejs, this is the version i got, not the current 8.11), this is not comming with npm.

If i run 

`sudo apt install npm`

 it gives me the following:

>  'Ubuntu 18.04 LTS _Bionic Beaver_ - Release amd64 (20180426)'
> in the drive '/cdrom/' and press [Enter]

I downloaded the ubuntu.iso and mounted the drive with CD, after pressing enter, NOTHING HAPPENS and i didn't get my npm and i can do just nothing in my project.

**Comment by kenany** [comment]
We don't maintain the nodejs or npm packages on the ubuntu repositories, so there's nothing we can do here. You should mention those maintainers instead.
