### ISSUE TITLE
npm registry unreachable by yarn & npm cli

### ISSUE THREAD

**Issue by xemasiv** [npm/npm#20706]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [X] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

`yarn add react-tiny-virtual-list` shows the following error:
```
error An unexpected error occurred: "Received malformed response from registry f
or undefined. The registry may be down.".
```
`npm install react-tiny-virtual-list --save` also gets stuck, too. And running `npm ping` returns
```
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
Ping error: SyntaxError: Unexpected token < in JSON at position 1

<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>503 No healthy backends</title>
  </head>
  <body>
    <h1>Error 503 No healthy backends</h1>
    <p>No healthy backends</p>
    <h3>Guru Mediation:</h3>
    <p>Details: cache-hkg17920-HKG 1526972945 3608590100</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>

npm ERR! Unexpected token < in JSON at position 1
npm ERR!
npm ERR! <?xml version="1.0" encoding="utf-8"?>
npm ERR! <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
npm ERR!  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
npm ERR! <html>
npm ERR!   <head>
npm ERR!     <title>503 No healthy backends</title>
npm ERR!   </head>
npm ERR!   <body>
npm ERR!     <h1>Error 503 No healthy backends</h1>
npm ERR!     <p>No healthy backends</p>
npm ERR!     <h3>Guru Mediation:</h3>
npm ERR!     <p>Details: cache-hkg17920-HKG 1526972945 3608590100</p>
npm ERR!     <hr>
npm ERR!     <p>Varnish cache server</p>
npm ERR!   </body>
npm ERR! </html>
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\1234\AppData\Roaming\npm-cache\_logs\2018-05-22T07_08_57_
84Z-debug.log
```
I've also tried running `ipconfig /flushdns`, restarting our router and trying the same thing with my laptop. 

#### How can the CLI team reproduce the problem?

I'm from the Philippines so maybe running tests from a vm in or nearby our country might help.

### supporting information:

 - `npm -v` prints: 6.0.1
 - `node -v` prints: 9.8.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows
 - Network issues: None
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by csvan** [comment]
https://github.com/npm/registry/issues/324

**Comment by kenany** [comment]
Registry issues should indeed be opened at npm/registry instead of here.
