### ISSUE TITLE
i am working on hyperledger fabric projects  

### ISSUE THREAD

**Issue by muthyalaDivyaVenkatesh** [npm/npm#20705]
`https://github.com/IBM/todo-list-fabricV1`
in the prerequisites they mention to use the previous version of  node and npm (6.x.x ) version only
![npm errors](https://user-images.githubusercontent.com/32588478/40346896-ebafd6da-5dbb-11e8-8be5-cf4abc309b54.PNG)

**Comment by kenany** [comment]
Does this also occur with newer versions of `npm` (they support Node.js v6 so you should be able to use the latest stable version of `npm`)?

**Comment by muthyalaDivyaVenkatesh** [comment]
sorry i used nvm to install the node
so it changed the default installation folder  when i am trying to npm install it is looking  in default bin folder
