### ISSUE TITLE
NPM is incredibly slow today

### ISSUE THREAD

**Issue by caseylmanus** [npm/npm#20724]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] npm is producing incorrect or undesirable behavior.
  - [ x] Other (_see below for feature requests_):

#### What's going wrong?
running a clean NPM install is taking over a minute per package.  Local internet speed is not the cause.

#### How can the CLI team reproduce the problem?

run a fresh npm install on any sizable project

### supporting information:
 - Network issues:
   - Geographic location where npm was run: Nashville, TN

**Comment by legodude17** [comment]
Ref https://status.npmjs.org/incidents/n2xnr8fks8v0

**Comment by caseylmanus** [comment]
This is not resolved.  Still experiencing the same behavior.

**Comment by legodude17** [comment]
Does going to https://registry.npmjs.org take a long time in the browser?

**Comment by caseylmanus** [comment]
No, my internet speed is good.

**Comment by legodude17** [comment]
But is the npm registry slow to load? Like with `curl` or a browser.

**Comment by caseylmanus** [comment]
This seems to be resolved now, closing.
