### ISSUE TITLE
Support json output format for npm audit

### ISSUE THREAD

**Issue by Osmose** [npm/npm#20729]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] npm is producing incorrect or undesirable behavior.
  - [x] Other (_see below for feature requests_):

#### What's the feature?

[nsp](https://github.com/nodesecurity/nsp/) has several output formats, including a JSON-based output. This allows nsp to easily be used in automation for checking dependencies automatically. It'd be great if `npm audit` had a similar option.

#### What problem is the feature intended to solve?

The ability to use `npm audit` in automation.

#### Is the absence of this feature blocking you or your team? If so, how?

Not per se; we're currently using nsp, but it doesn't check nested dependencies like `npm audit` does, which led to us missing some insecure nested dependencies that `npm audit` picked up on.

#### Is this feature similar to an existing feature in another tool?

Yes, the aforementioned nsp output formatting feature.

#### Is this a feature you're prepared to implement, with support from the npm CLI team?

Potentially, time permitting. It'd take me a few weeks to find the time to work on this.

**Comment by legodude17** [comment]
A PR has already been made and merged: #20568.

**Comment by Osmose** [comment]
> A PR has already been made and merged: #20568.

![](https://i.imgur.com/cYimkuT.gif)
