### ISSUE TITLE
https://github.com/npm/npm/issues

### ISSUE THREAD

**Issue by sidMnair** [npm/npm#20727]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### How can the CLI team reproduce the problem?
 I installed node from official node website and then tried running the code 
"npm install -g @angular/cli"

But the below error occured: 
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\sidharth\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli"
npm ERR! node v8.11.2
npm ERR! npm  v3.5.2
npm ERR! code MODULE_NOT_FOUND
npm ERR! Cannot find module 'internal/util/types'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Please include the following file with any support request:
npm ERR!     E:\Angular\npm-debug.log
-----------------------------------------------------------------------------------------------------------
npm-debug.log gist link: https://gist.github.com/sidMnair/c664027e9fbd3c3a43f0dec93544e043
-----------------------------------------------------------------------------------------------------------
### supporting information:

 - `npm -v` prints: 3.5.2
 - `node -v` prints: v8.11.2
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows
 - Network issues:
   - Geographic location where npm was run: India
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
Your version of npm is old and no longer supported. Please update using `npm i -g npm`.

**Comment by sidMnair** [comment]
@legodude17 Hi, I tried this `npm i -g npm` now. But I got the same error.

**Comment by legodude17** [comment]
Best guess is that either your npm version doesn't support node or your npm installation is broken. Either way, try removing npm and reinstalling node.

**Comment by sidMnair** [comment]
@legodude17 I deleted the node, npm & npm-cache from the AppData and cleared the npm and node PATH from Environment Variables and Reinstalled the node and finally it WORKED!!! 
Thanks !

**Comment by sidMnair** [comment]
Thank you for the solution.

**Comment by sidMnair** [comment]
Thank you for the solution.
