### ISSUE TITLE
Cant install npm in ubantu 14.04

### ISSUE THREAD

**Issue by kaushalgosaliya5** [npm/npm#20721]
getting this error in error catelog : 

npm ERR! install Couldn't read dependencies
npm ERR! Error: ENOENT, open '/home/yama/package.json'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.4.0-97-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/yama
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /home/yama/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/yama/npm-debug.log
npm ERR! not ok code 0

**Comment by csvan** [comment]
The error explains itself - there is no package.json in the folder you are trying to run `npm install` in.

**Comment by vamshi9666** [comment]
@kaushalgosaliya5  specify , how you faced error ?
what is intended to happen  in ideal case?

**Comment by kenany** [comment]
@kaushalgosaliya5 

1. Your versions of Node.js and `npm` are **years** old and are no longer supported.
2. `npm install` has no idea what you want it to install unless there is a `package.json` in your current directory. Hence, that error is thrown. This is intentional behavior.
