### ISSUE TITLE
SyntaxError: Unexpected token ILLEGAL

### ISSUE THREAD

**Issue by tanveernm** [npm/npm#20722]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [] npm is not getting installed on my local

#### What's going wrong?

SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /Users/tanveer/workspace/myApp/target/nodejs/lib/node_modules/npm/node_modules/npm-registry-client/index.js:72:20
    at Array.forEach (native)
    at CachingRegistryClient.RegClient /Users/tanveer/workspace/myApp/target/nodejs/lib/node_modules/npm/node_modules/npm-registry-client/index.js:50:42)
npm ERR! Darwin 17.4.0
npm ERR! argv "/Users/tanveer/workspace/myApp/target/nodejs/bin/node" "/Users/tanveer/workspace/myApp/target/nodejs/bin/npm" "run" "full" "-loglevel" "warn" "--registry https://npm.apple.com"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! /Users/tanveer/workspace/myApp/target/nodejs/lib/node_modules/npm/node_modules/npm-registry-client/lib/._access.js:1
npm ERR! (function (exports, require, module, __filename, __dirname) {
npm ERR!
npm ERR! Unexpected token ILLEGAL
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
Your versions of `node` and `npm` are years old and longer supported. Please update.

**Comment by kenany** [comment]
Closing since we indeed no longer support those versions.
