### ISSUE TITLE
Offer to contribute: npm audit resolve

### ISSUE THREAD

**Issue by naugtur** [npm/npm#20738]
I've created a tool my team urgently needed:
https://www.npmjs.com/package/npm-audit-resolver

but it feels like it'd make sense to build it into npm audit.

If you're willing to provide some guidance, I'd be happy to contribute this as a feature of npm audit

**Comment by legodude17** [comment]
@naugtur This would make a great RFC over at https://github.com/npm/rfcs! In the RFC, try to explain exactly how it works and what it does.

**Comment by naugtur** [comment]
@legodude17 How long does it take to go from the RFC to "ok, let's do it" ?

**Comment by legodude17** [comment]
@naugtur Honestly, I have no clue. It is very variable.

**Comment by naugtur** [comment]
I took the risk and threw a PR out there. Fingers crossed ;) But thanks for the hints!
