### ISSUE TITLE
cb() never called! after npm install

### ISSUE THREAD

**Issue by pcowgill** [npm/npm#20744]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
`cb() never called!` error is printed after running npm install, so I'm unable to get my dependencies back after having done `rm -rf node_modules`.

`npm cache clean` did not resolve the problem, and neither did reinstalling npm@4.6.1 globally.

I'd really appreciate any help you can provide!

#### How can the CLI team reproduce the problem?
```
$ npm -v
4.6.1
$ nvm current
v8.3.0
$ npm install
```
I'm using npm 4.6.1 because it's a react native app, and expo doesn't recommend using higher than node 4.x

https://gist.github.com/pcowgill/e592817c362ffcd53b8368673b472d45

### supporting information:

 - `npm -v` prints: 4.6.1
 - `node -v` prints: v8.3.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [x] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
Please update to the latest version of npm.

**Comment by pcowgill** [comment]
@legodude17 I would love to, but expo specifically suggests using npm 4 because it didn't work with npm 5. Do you know if npm 6 works with expo? Thanks!

https://github.com/expo/expo

**Comment by legodude17** [comment]
I don't see why it wouldn't, but you should probably open an issue and ask.

**Comment by pcowgill** [comment]
Hmm ok thanks - I created a feature request for them.

https://expo.canny.io/feature-requests/p/support-npm6

(I didn't make it an issue on GitHub since they only track bugs there.)

In the meantime, I'll try it on my project and see if it works.

**Comment by pcowgill** [comment]
So far expo doesn't seem to be having issues with npm@6. 🤞 

Thanks @legodude17 !

**Comment by legodude17** [comment]
@pcowgill No problem! Can you close this?
