### ISSUE TITLE
sqlite

### ISSUE THREAD

**Issue by BITEGUE** [npm/npm#20758]
Hello,
I am having trouble installing the module containing sqlite.

Can you help me please.

Thank you.

**Comment by krnlde** [comment]
Probably the same issue you open at npm? https://github.com/npm/npm/issues/20628

**Comment by kenany** [comment]
Could you please explain what trouble you are having? Be as specific as possible, and be sure to include any error logs you are seeing.

**Comment by BITEGUE** [comment]
Hello,
I have the node-red-node-sqlite module which is installed from the Node-Red application.
But I can not find it in my storage nodes.

I would like to know if there is any manipulation to be done after installation. I have already redemoted my IOT.

![capture](https://user-images.githubusercontent.com/39307252/40600227-ec046ad0-6250-11e8-81e2-6bcf044a4567.PNG)

**Comment by kenany** [comment]
Sorry, this issue tracker is for issues with the `npm` CLI. I suggest you take your question to a more general site like StackOverflow.
