### ISSUE TITLE
problems with supervisor

### ISSUE THREAD

**Issue by vdekameron** [npm/npm#20751]
Hi everybody!
I installed supervisor like this - npm i -g supervisor.
Then I make supervisor server.js but......I have а problem. I have a loop message in console like this - Program node server.js exited with code 0.

Please tell what the metter. What I do wrong?

In advance thank you.

**Comment by vdekameron** [comment]
Does no one know?

**Comment by legodude17** [comment]
It appears to me that this would be better answered [over here](https://github.com/petruisfan/node-supervisor/issues).

**Comment by vdekameron** [comment]
Thank you. There was the same issue and I ask there. But I not sure that someone answer. Last answer in those topic was in 2016

**Comment by kenany** [comment]
Since this doesn't seem to be an issue with `npm` itself, I'm afraid that this isn't the appropriate issue tracker for something like this.
