### ISSUE TITLE
npm has lost the package natives@1.1.4

### ISSUE THREAD

**Issue by jwalton** [npm/npm#20766]
#### I'm opening this issue because:

  - npm is producing an incorrect install.

#### What's going wrong?

```
npm cache clean --force
npm install natives@1.1.4

npm ERR! code E404
npm ERR! 404 Not Found: natives@1.1.4

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jwalton/.npm/_logs/2018-05-25T23_29_59_930Z-debug.log
```

According to this, it was published four days ago: https://www.npmjs.com/package/natives

It's downloaded 1.5M times a week, so this is bad.

#### How can the CLI team reproduce the problem?

```
npm cache clean --force
npm install natives@1.1.4
```

### supporting information:

 - `npm -v` prints: 6.1.0
 - `node -v` prints: v8.11.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS, also travis is seeing this on Linux

**Comment by jwalton** [comment]
```
$ wget https://registry.npmjs.org/natives/-/natives-1.1.4.tgz
--2018-05-25 19:45:55--  https://registry.npmjs.org/natives/-/natives-1.1.4.tgz
Resolving registry.npmjs.org... 104.18.94.96, 104.18.97.96, 104.18.98.96, ...
Connecting to registry.npmjs.org|104.18.94.96|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-05-25 19:45:55 ERROR 404: Not Found.
```

Yup.  It's not there.

**Comment by JohnDDuncanIII** [comment]
Also getting this error during `npm install` 

`npm ERR! 404 Not Found: natives@https://registry.npmjs.org/natives/-/natives-1.1.4.tgz`

That url returns `These are not the packages you are looking for. You can move along.`

**Comment by patrickarlt** [comment]
Possibly related to https://status.npmjs.org/incidents/t3j62lxb7jg3?

Also seeing for:

```bash
npm cache clean --force
npm install natives@^1.1.0
npm WARN using --force I sure hope you know what you are doing.
npm ERR! code E404
npm ERR! 404 Not Found: natives@^1.1.0

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/patr7104/.npm/_logs/2018-05-25T23_52_57_991Z-debug.log
```

**Comment by kltm** [comment]
Going through the URLs in https://registry.npmjs.org/natives/ , it seems that all packages are lost.

**Comment by Kevinio04** [comment]
Same problem. When building locally I get:

npm ERR! cb() never called!
npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

I can upload the log if needed.

When running in our CI process on Azure:

npm ERR! fetch failed http://registry.npmjs.org/natives/-/natives-1.1.4.tgz npm 
ERR! fetch failed with status code 404 
If you need help, you may report this error at: npm

**Comment by patrickarlt** [comment]
Is this more wide reaching then just the `natives` package? 

For example the tarball for `babel@6.3.26` appear to also be missing http://registry.npmjs.org/babel/-/babel-6.3.26.tgz

```bash
npm info babel@6.3.26

babel@6.3.26 | MIT | deps: none | versions: 165
Turn ES6 code into readable vanilla ES5 with source maps
https://babeljs.io/

DEPRECATED ⚠️  - In 6.x, the babel package has been deprecated in favor of babel-cli. Check https://opencollective.com/babel to support the Babel maintainers

bin: babel, babel-node, babel-external-helpers

dist
.tarball http://registry.npmjs.org/babel/-/babel-6.3.26.tgz
.shasum: 7bf8967bd2de7c3645a107080094c2c9df706886

maintainers:
- existentialism <bng412@gmail.com>
- thejameskyle <me@thejameskyle.com>
- sebmck <sebmck@gmail.com>
- danez <daniel@tschinder.de>
- hzoo <hi@henryzoo.com>
- loganfsmyth <loganfsmyth@gmail.com>

dist-tags:
latest: 6.23.0  old: 5.8.38

published over a year ago by amasad <amjad.masad@gmail.com>
```

**Comment by MollyJeanB** [comment]
Me too. My Travis build errors like so:
```
npm ERR! code E404
npm ERR! 404 Not Found: natives@https://registry.npmjs.org/natives/-/natives-1.1.0.tgz
```

**Comment by nathanlong** [comment]
Ran into something similar attempting to install gulp (using Node 10.2.1, npm 5.6.0)

```
npm ERR! code E404
npm ERR! 404 Not Found: natives@https://registry.npmjs.org/natives/-/natives-1.1.4.tgz
```

**Comment by crismanNoble** [comment]
TGIF

**Comment by AbinayaKadhirvel** [comment]
Same here

**Comment by renecvt** [comment]
The npm registry appears to be in maintenance, check the status here:
https://status.npmjs.org/

**Comment by pedramphp** [comment]
It seems lots of packages are dependent on `graceful-fs` and `graceful-fs` is using `natives`

**Comment by sffc** [comment]
Got this error for `npm install`; according to the dependency tree it looks like this package "natives" is required by "graceful-fs" which is required by "vinyl-fs" which is required by "gulp" (my project's dependency).

**Comment by maurodelazeri** [comment]
yaeahh... maintenance...

**Comment by dilowagner** [comment]
Same here!!

**Comment by puppycodes** [comment]
+1

**Comment by tlr3552** [comment]
+1

**Comment by pablogravielseo** [comment]
+1

**Comment by lucasdaiki** [comment]
+1

**Comment by ffaubert** [comment]
+1

**Comment by DeckerCHAN** [comment]
+1

**Comment by sonia3187** [comment]
+1

**Comment by theRobinator** [comment]
Seeing this on node 10.2.1 on linux.

**Comment by DerekChan65535** [comment]
Run `watch -n 30 wget https://registry.npmjs.org/natives/-/natives-1.1.4.tgz` to monitor it.

**Comment by jopech** [comment]
+1

[0m[91mnpm ERR! fetch failed https://registry.npmjs.org/natives/-/natives-1.1.4.tgz
[0m[91mnpm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404

**Comment by ahmedfarooki** [comment]
@DeckerCHAN imagine all of us doing that. Are you trying to DoS them as well?

**Comment by vupham2909** [comment]
Same here... +1
npm ERR! fetch failed https://registry.npmjs.org/natives/-/natives-1.1.4.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404

**Comment by StevenZhang1023** [comment]
Blocked me too...+1

**Comment by argordmel** [comment]
+1

**Comment by WVFFLIFE** [comment]
is it problem with npm?

**Comment by jasonbilyeu** [comment]
+1

**Comment by kswenson** [comment]
I have the same dependency chain mentioned by @sffc above: gulp -> graceful_fs -> natives. Upgrading gulp from 3.9.1 to 4.0 allowed npm install to proceed. Now I just need to get the project building with gulp 4.0.

**Comment by mpkamowski** [comment]
It could have something to do with npm
https://status.npmjs.org/#

```registry maintenance in progress```
```Some published package versions unable to be installed or found```

**Comment by matgargano** [comment]
+1

**Comment by mauroencinas** [comment]
+1

**Comment by pedroalves0030** [comment]
+1

**Comment by jwalton** [comment]
Sounds like whatever they're up to is doing as things to Yarn as well: https://news.ycombinator.com/item?id=17158840

**Comment by reecealanboyd** [comment]
+1

**Comment by rodrigoalmeidaee** [comment]
+1

**Comment by calvaradocl** [comment]
I'm getting the same errors on my VSTS builds.

**Comment by kevryan2** [comment]
has anyone found any sort of timeline on when npm expects this to be fixed?  since their status page hasn't been updated at all just trying to get a ballpark

**Comment by coryschadt** [comment]
+1

**Comment by relicmelex** [comment]
Did GDPR burn the world down? +1

**Comment by kingtigg** [comment]
+1

**Comment by camilofernandesalves** [comment]
+1

**Comment by polerin** [comment]
+1

**Comment by dennis-yemelyanov** [comment]
+1

**Comment by ouadielim** [comment]
+1

**Comment by howawong** [comment]
+1

**Comment by techiediaries** [comment]
+1

**Comment by jeffwesson** [comment]
Using the 👍 reaction to posts is helpful in decreasing notifications for those subscribed. It still signifies the same thing but helps reduce noise for those working to find solutions.

Happy Friday night, all 🍻

**Comment by eghojansu** [comment]
+1

**Comment by maylortaylor** [comment]
+1

**Comment by XueDong369** [comment]
+1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1

**Comment by xinxuzhang** [comment]
+1024

**Comment by fnks** [comment]
+1

**Comment by XueDong369** [comment]
You can run '$ npm install -g cnpm --registry=https://registry.npm.taobao.org',  then 'cnpm install'.

**Comment by martinlevesque** [comment]
really ? That really sucks.

Note: It works for me with yarn: yarn install

**Comment by thousif** [comment]
+1

**Comment by joerg84** [comment]
Is the npmjs team aware? According to https://status.npmjs.org/ they seem to assume all is fine again... But I still have see the same issue...

**Comment by franklinsouza** [comment]
@martinlevesque  Thanks man!

**Comment by jwalton** [comment]
@joerg84 I'd think raising an issue here would make them away of it, especially since there's a "+1" on this every few minutes.  :P  But I'll fire an email to support@npmjs.com.

**Comment by reecealanboyd** [comment]
Was finally able to get it working on mac with yarn.
`yarn add nativescript`

If you are setting up yarn for the first time and already have npm, this worked for me:
`brew install --without-node yarn`

 Installed all the dependencies for nativescript with
`sudo ruby -e "$(curl -fsSL https://www.nativescript.org/setup/mac)"`
which didn't work correctly until I ran
`sudo xcode-select --reset` 
first. 

Now it's working and I am able to use Sidekick!

**Comment by thousif** [comment]
Seems to be working now!

**Comment by gangavh** [comment]
Worked for me

**Comment by calvaradocl** [comment]
My VSTS builds passed npm install, it seems that the issue is fixed.

**Comment by TheNew000** [comment]
Confirmed installs appear to be working again.

**Comment by davidcarma** [comment]
Confirm +1 Working

**Comment by GL-KenDLG** [comment]
What happened in the first place though?

**Comment by StephenSchwahn** [comment]
^^ Ditto. Works great now, but I'm smelling pad-left all over again

**Comment by mvanderlee** [comment]
@GL-KenDLG  https://status.npmjs.org/incidents/t3j62lxb7jg3 
Seems they were doing maintenance on the registry

**Comment by iarna** [comment]
This is resolved now, so I'm gonna close this issue
