### ISSUE TITLE
Allow npm audit to accept --only=(prod|dev) as an argument

### ISSUE THREAD

**Issue by wyardley** [npm/npm#20763]
#### What's the feature?
Add the ability to use the filter added in #20569 to also filter audit results.
e.g.,
`npm audit --only=prod` (right now, the argument doesn't cause an error, but does not do anything)

#### What problem is the feature intended to solve?
Allow auditing for a subclass of dependencies (e.g., only non-dev deps). This would enable us to use the exit status of `npm audit` to determine more easily whether there are any vulnerabilities that will ship with the final product.

#### Is the absence of this feature blocking you or your team? If so, how?
We'd like to switch to `npm audit` vs. `npm run nsp`, and it would make our life much easier to not have to write wrapper tools around this.

#### Is this feature similar to an existing feature in another tool?
Based on an existing arg for the same command

#### Is this a feature you're prepared to implement, with support from the npm CLI team?
If I can get some guidance, I can assist or submit a PR

**Comment by benvium** [comment]
#20564 covers this

**Comment by wyardley** [comment]
Thank you @benvium
