### ISSUE TITLE
failing: npm install -g bower grunt-cli 

### ISSUE THREAD

**Issue by kassbohm** [npm/npm#20775]
Trying to do this:

sudo npm install -g bower grunt-cli 

I get the following:

npm http GET https://registry.npmjs.org/bower
npm http GET https://registry.npmjs.org/grunt-cli
npm http GET https://registry.npmjs.org/bower
npm http GET https://registry.npmjs.org/grunt-cli
npm http GET https://registry.npmjs.org/grunt-cli
npm http GET https://registry.npmjs.org/bower
npm ERR! Error: CERT_UNTRUSTED
npm ERR!     at SecurePair.<anonymous> (tls.js:1370:32)
npm ERR!     at SecurePair.EventEmitter.emit (events.js:92:17)
npm ERR!     at SecurePair.maybeInitFinished (tls.js:982:10)
npm ERR!     at CleartextStream.read [as _read] (tls.js:469:13)
npm ERR!     at CleartextStream.Readable.read (_stream_readable.js:320:10)
npm ERR!     at EncryptedStream.write [as _write] (tls.js:366:25)
npm ERR!     at doWrite (_stream_writable.js:223:10)
npm ERR!     at writeOrBuffer (_stream_writable.js:213:5)
npm ERR!     at EncryptedStream.Writable.write (_stream_writable.js:180:11)
npm ERR!     at write (_stream_readable.js:583:24)
npm ERR!     at flow (_stream_readable.js:592:7)
npm ERR!     at Socket.pipeOnReadable (_stream_readable.js:624:5)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.16.0-38-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "bower" "grunt-cli"
npm ERR! cwd /home/kassbohm
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10

Is this a problem with npm at all? What can I do?

**Comment by kassbohm** [comment]
One way to avoid this error is to do:

npm config set strict-ssl false

**Comment by kenany** [comment]
In addition, do note that your versions of Node.js and `npm` are _years_ old and are no longer supported.

**Comment by kassbohm** [comment]
yes, thanks.
