### ISSUE TITLE
npm install fails by ENOENT and some my packages are lost from registry.

### ISSUE THREAD

**Issue by mysticatea** [npm/npm#20770]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [X] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

- https://travis-ci.org/mysticatea/vue-eslint-editor/builds/384065868

Many ENOENT errors happen in `node_modules/.staging` directory, and `404 Not Found: eslint4b@https://registry.npmjs.org/eslint4b/-/eslint4b-4.19.2.tgz` happens at last.

This issue might be related to #20766, but my problem hasn't resolved.

#### How can the CLI team reproduce the problem?

```
git clone https://github.com/mysticatea/vue-eslint-editor.git
cd vue-eslint-editor
npm install
```

### supporting information:

It happens in both my local and Travis CI. The below answers are about my local.

 - `npm -v` prints: `6.0.1`
 - `node -v` prints: `v8.11.2`
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?: Windows
 - Network issues:
   - Geographic location where npm was run: Japan
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by mysticatea** [comment]
FWIW, it's still not solved: https://travis-ci.org/mysticatea/vue-eslint-editor/builds/384593782

**Comment by mysticatea** [comment]
FWIW, it's still not solved: https://travis-ci.org/mysticatea/vue-eslint-editor/builds/384593724

**Comment by legodude17** [comment]
That latest one looks like a 404, not a ENOENT.

**Comment by mysticatea** [comment]
@legodude17 Yes, it's the problem. The `eslint4b` package exists in the registry. `npm view eslint4b` shows the information of it. However, the tarball of `eslint4b` has lost from the registry since May 26. I have communicated to npm support with email as well, but it has not solved while a week.

**Comment by mysticatea** [comment]
After a long communication with npm support, today this has been solved eventually. They said, "It looked like a delay on our side regarding the availability of your package's latest tarball."
