### ISSUE TITLE
Not able to install any thing on node beacuse of this error 0906D06C:PEM routines:PEM_read_bio:no start line 

### ISSUE THREAD

**Issue by sadgi** [npm/npm#20789]
0906D06C:PEM routines:PEM_read_bio:no start line in node js npm install command is not working
silly fetchPackageMetaData error for create-react-native-app@latest error:0906D06C:PEM routines:PEM_read_bio:no start line 8 verbose stack Error: error:0906D06C:PEM routines:PEM_read_bio:no start line 8 verbose stack at Object.createSecureContext (_tls_common.js:104:17) 8 verbose stack at Object.exports.connect (_tls_wrap.js:1049:48) 8 verbose stack at HttpsAgent.createConnection (https.js:111:22) 8 verbose stack at HttpsAgent.createSocket (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/agentkeepalive/lib/_http_agent.js:271:26) 8 verbose stack at HttpsAgent.createSocket (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/agentkeepalive/lib/agent.js:77:11) 8 verbose stack at HttpsAgent.addRequest (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/agentkeepalive/lib/_http_agent.js:240:10) 8 verbose stack at new ClientRequest (_http_client.js:258:16) 8 verbose stack at Object.request (http.js:38:10) 8 verbose stack at request (https.js:239:15) 8 verbose stack at fetch.Promise (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/index.js:54:17) 8 verbose stack at new Promise () 8 verbose stack at fetch (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/index.js:41:10) 8 verbose stack at retry (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/index.js:332:14) 8 verbose stack at /usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/promise-retry/index.js:29:24 8 verbose stack at 9 verbose cwd /Users/sadgi 10 verbose Darwin 17.5.0 11 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "create-react-native-app" 12 verbose node v8.11.1 13 verbose npm v5.6.0 14 error error:0906D06C:PEM routines:PEM_read_bio:no start line 15 verbose exit [ 1, true ]

Also tried npm set registry http://registry.npmjs.org/ still problem persists

**Comment by Ridlsan** [comment]
Same here

**Comment by legodude17** [comment]
Does this occur on the latest version of npm?

**Comment by sadgi** [comment]
YES

**Comment by sadgi** [comment]
Yes
