### ISSUE TITLE
npm crash

### ISSUE THREAD

**Issue by tatsujb** [npm/npm#20796]
#### I'm opening this issue because:

  - [x ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong

Npm is crashing and I'm being told to report it here.

here's the log : 
[2018-05-29T08_45_00_219Z-debug.log](https://github.com/npm/npm/files/2052703/2018-05-29T08_45_00_219Z-debug.log)

**Comment by legodude17** [comment]
I don't see the beginning or end of the log in the link you posted.

**Comment by tatsujb** [comment]
sorry! I edited with actual log file which is what I should have done from the start. I can't read npm log files so I don't know either where it starts or ends so I just put the whole file. this is the one npm pointed to when the crash happened.

**Comment by tatsujb** [comment]
```
PS C:\Users\j_bard\WebstormProjects\angular-parcel> npm i
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\j_bard\AppData\Roaming\npm-cache\_logs\2018-05-30T11_31_17_223Z-debug.log
PS C:\Users\j_bard\WebstormProjects\angular-parcel> npm i
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\j_bard\AppData\Roaming\npm-cache\_logs\2018-05-30T11_35_35_675Z-debug.log
PS C:\Users\j_bard\WebstormProjects\angular-parcel> npm i
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\j_bard\AppData\Roaming\npm-cache\_logs\2018-05-30T11_39_54_875Z-debug.log

```

**Comment by tatsujb** [comment]
`npm cache clean`

fixed it for me.
