### ISSUE TITLE
Node-red Reads data from a S7 PLC

### ISSUE THREAD

**Issue by BITEGUE** [npm/npm#20794]
Hello,

I read several variables in my S7 as in the picture below.
 
I would like to retrieve or save these variables locally for use in another Flow.
 
I want my S7 to return all the variables at the same time but the problem is that I do not know how to get them back in my Function block.

Should I use another block? Can you help me with my code?

Cordially.

![capture](https://user-images.githubusercontent.com/39307252/40646881-c7cd0b1a-632a-11e8-9e30-bbd08cf576ef.PNG)

**Comment by kenany** [comment]
I suggest you take this to <https://discourse.nodered.org/>.
