### ISSUE TITLE
npm pack reports notices to stderr instead of stdout

### ISSUE THREAD

**Issue by silkentrance** [npm/npm#20806]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

When running ``npm pack``, it will issue notices about the tarball it has just created. However, the notices will be output to stderr instead of stdout.

#### How can the CLI team reproduce the problem?

From inside an existing package, just run
```
npm pack >stdout.log 2>stderr.log
```

You will find all notices inside stderr.log instead of stdout.log, e.g.

```
npm notice
npm notice 📦  mocha-typescript@1.1.14
npm notice === Tarball Contents ===
npm notice 1.0kB  package.json
npm notice 3.1kB  globals.d.ts
npm notice 4.1kB  index.d.ts
npm notice 20.1kB index.js
npm notice 18.3kB index.js.map
npm notice 19.8kB index.ts
npm notice 11.4kB LICENSE
npm notice 21.1kB README.md
npm notice 3.9kB  bin/watch.js
npm notice === Tarball Details ===
npm notice name:          mocha-typescript
npm notice version:       1.1.14
npm notice filename:      mocha-typescript-1.1.14.tgz
npm notice package size:  23.0 kB
npm notice unpacked size: 102.8 kB
npm notice shasum:        9301aa0045d7a5bb0d6b911095ceb4b1510baa46
npm notice integrity:     sha512-/Tg8fek3CDfZi[...]a+r2dwFA2/4LQ==
npm notice total files:   9
npm notice
```

I'd expect these informational notices to appear on stdout instead of stderr.

### supporting information:

 - `npm -v` prints: 6.1.0
 - `node -v` prints: 10.3.0
 - `npm config get registry` prints: official npm registry
 - Windows, OS X/macOS, or Linux?: OSX
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
I believe that is intentional. See: https://github.com/npm/npm/issues/118#issuecomment-325440

**Comment by silkentrance** [comment]
@legodude17 oh well, then this can be closed I believe.
