### ISSUE TITLE
PHP: Failed to connect to a postgre DataBase

### ISSUE THREAD

**Issue by mickaelgudin** [npm/npm#20800]
Hi, 

I can't connect to my postgre db, I have a MacOS Server(all the informations in pg_connect are correct). My issue is that I can't display if my connection is succesfull or not. The problem is not from php.ini because there is pgsql.so extension maybe my problem has something to do with the socket 

here's my code :
[file.txt](https://github.com/npm/npm/files/2047956/file.txt)

**Comment by mihaibujanca** [comment]
How is this related to npm?

**Comment by mickaelgudin** [comment]
What do you mean?

**Comment by BramHouben** [comment]
Your code has nothing to do with NPM. You posted a question on stackoverflow and linked to this.  

I advice to you this link: http://lmgtfy.com/?q=Failed+to+connect+to+a+postgre+DataBase
