### ISSUE TITLE
Cannot login or adduser (ERR code E301)

### ISSUE THREAD

**Issue by gonzdevour** [npm/npm#20804]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Cannot login or adduser since 2018/5/28,
registry returned 301 for post on http://registry.npmjs.org/-/v1/login

Screenshot:
[https://i.imgur.com/Sj9CY7y.png](https://i.imgur.com/Sj9CY7y.png)

#### How can the CLI team reproduce the problem?

1.open command line
2.npm login/npm adduser
3.get E301 error

log:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\JyunRu\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'login' ]
2 info using npm@6.1.0
3 info using node@v8.11.2
4 verbose npm-session efbd6d24d5e22ce4
5 verbose web login before first POST
6 http request → POST http://registry.npmjs.org/-/v1/login
7 http 301 ← Moved Permanently (http://registry.npmjs.org/-/v1/login)
8 verbose stack Error: Registry returned 301 for POST on http://registry.npmjs.org/-/v1/login
8 verbose stack     at fetch.defaults.catch.then.then.result (C:\Users\JyunRu\AppData\Roaming\npm\node_modules\npm\node_modules\npm-profile\index.js:376:13)
8 verbose stack     at <anonymous>
8 verbose stack     at process._tickCallback (internal/process/next_tick.js:188:7)
9 verbose statusCode 301
10 verbose cwd C:\WINDOWS\system32
11 verbose Windows_NT 10.0.17134
12 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\JyunRu\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "login"
13 verbose node v8.11.2
14 verbose npm  v6.1.0
15 error code E301
16 error Registry returned 301 for POST on http://registry.npmjs.org/-/v1/login
17 verbose exit [ 1, true ]

### supporting information:

 - `npm -v` prints:
6.1.0
 - `node -v` prints:
v8.11.2
 - `npm config get registry` prints:
http://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?:
Win10
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by bitflower** [comment]
Same here, on macOS, npm 6.1, Node 8.11.2

**Comment by SoftwareEngineerPalace** [comment]
Same here, on Windows 7, npm 6.1, Node 8.9.0

----

resolved : npm config set registry https://registry.npmjs.org

**Comment by wusb** [comment]
@JasonXiaoSpace 
when i change to https and login：
`code EAUTHIP, 
Unable to authenticate, need: Basic`

**Comment by gonzdevour** [comment]
@JasonXiaoSpace 
Solved here, too. Thank you.

Screenshot:
https://i.imgur.com/g0ZdJii.png

**Comment by SoftwareEngineerPalace** [comment]
@simbawus have you signuped on https://www.npmjs.com/ ?
or try to input your correct username and password. it should be ok

**Comment by simbawus** [comment]
thanks, i have a incorrect password, but the gist of the npm's  tips are not friendly.

**Comment by wusb** [comment]
@JasonXiaoSpace thanks, i have a incorrect password, but the gist of the npm's tips are not friendly.

**Comment by bitflower** [comment]
Guys, this helped me:
https://stackoverflow.com/a/50580349

It was the wrong URL in my case. Don't know why though. Came suddenly....
