### ISSUE TITLE
Allow per-package registry setting

### ISSUE THREAD

**Issue by jrop** [npm/npm#20807]
#### What's the feature?

It would be nice if NPM configuration could allow setting registry config for a specific package.  Currently, NPM allows setting a particular registry for scoped packages:

```ini
registry=https://registry.npmjs.org
@somescope:registry=http://someotherregistry.com
```

It would be nice if this could be extended to allow the user to specify that a given package should come from a particular registry:

```ini
registry=https://registry.npmjs.org
@somescope:registry=http://someotherregistry.com
a-particular-package:registry=http://registry3.com
```

#### What problem is the feature intended to solve?

Before NPM supported scoped packages, we published several internal packages to our own private registry.  While the ideal fix would be for us to migrate our packages to being scoped packages, it would be nice to have the above feature for the interim.

#### Is the absence of this feature blocking you or your team? If so, how?

This is not blocking.  It would just be a "nice-to-have".

#### Is this feature similar to an existing feature in another tool?

Yes, scoped-package config (as mentioned above).

#### Is this a feature you're prepared to implement, with support from the npm CLI team?

Perhaps, with a little direction, I could possibly submit a PR for this.

**Comment by legodude17** [comment]
You can do
```
"publishConfig": {"registry": "http://someotherregistry.com"}
```
in `package.json`

**Comment by jrop** [comment]
@legodude17 To be clear, that is not what I want.  I want NPM to install the individual package in question from the given registry.

**package.json**
```json
{
  "dependencies": {
    "express": "1.0.0",
    "a-particular-package": "0.0.1"
  }
}
```

Then in .npmrc:
```ini
a-particular-package:registry=https://myprivateregistry.com/
```

Then, an `npm install` would fetch express from the regular registry, but `a-particular-package` from "https://myprivateregistry.com/"

**Comment by legodude17** [comment]
Oh sorry I misunderstood.

**Comment by jrop** [comment]
@legodude17 No worries, I realized after I saw your response that I was slightly ambiguous in my description :man_shrugging: :stuck_out_tongue_closed_eyes:

**Comment by zkat** [comment]
We don't accept feature requests through here anymore. Please start a discussion [in our ideas forum](https://npm.community/c/ideas) or, if you want to make a more formal proposal that we can consider, submit [an RFC](https://github.com/npm/rfcs).
