### ISSUE TITLE
Error: 429. Too many requests

### ISSUE THREAD

**Issue by sentinel09** [npm/npm#20816]
#### I'm opening this issue because:

  - [    ] npm is crashing.
  - [    ] npm is producing an incorrect install.
  - [    ] npm is doing something I don't understand.
  - [ X ] npm is producing incorrect or undesirable behavior.
  - [     ] Other (_see below for feature requests_):

#### What's going wrong?
During the npm install we frequently experiencing error:
```
npm ERR! code E429

npm ERR! 429 Too Many Requests: @types/jsonwebtoken@7.2.0

```
#### How can the CLI team reproduce the problem?

Seems it will be difficuilt to reproduce the problem, but in our case the command is simple:
`npm install`

### supporting information:

```
/ # node -v
v8.9.4
/ # npm -v
5.6.0
/ # npm config get registry
https://registry.npmjs.org/

Alpine Linux 3.6.2
```

 - Network issues:
   - Geographic location where npm was run:
   - [   ] I use a proxy to connect to the npm registry.
   - [   ] I use a proxy to connect to the web.
   - [   ] I use a proxy when downloading Git repos.
   - [   ] I access the npm registry via a VPN
   - [   ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [    ] I develop using Vagrant on Windows.
   - [    ] I develop using Vagrant on OS X or Linux.
   - [ X ] I develop / deploy using Docker.
   - [     ] I deploy to a PaaS (Triton, Heroku).

P.S. Did not face this problem ~1.5-2 weeks back.

**Comment by arutkowski00** [comment]
We have exactly the same issue on Bitbucket Pipelines:
```
error https://registry.npmjs.org/fabric-dist/-/fabric-dist-1.7.19-beta1.tgz: Request failed "429 Too Many Requests"
error https://registry.npmjs.org/pdfjs-dist/-/pdfjs-dist-1.9.648.tgz: Request failed "429 Too Many Requests"
error https://registry.npmjs.org/node-ensure/-/node-ensure-0.0.0.tgz: Request failed "429 Too Many Requests"
error An unexpected error occurred: "https://registry.npmjs.org/@britishcouncil/angular-file-upload/-/angular-file-upload-2.5.0-beta.tgz: Request failed \"429 Too Many Requests\"".
error https://registry.npmjs.org/worker-loader/-/worker-loader-1.0.0.tgz: Request failed "429 Too Many Requests"
```

**Comment by thibmaek** [comment]
Seeing the same issue on Bitbucket Pipelines as well.

```
+ npm install -g npm@latest
npm ERR! code E429
npm ERR! 429 Too Many Requests: npm@latest
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-05-30T09_37_58_559Z-debug.log
```

```
+ npm ci
npm ERR! code E429
npm ERR! 429 Too Many Requests: jsonschema@1.2.0
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-05-30T09_37_58_559Z-debug.log
```

**Comment by pjoe** [comment]
Also getting this on bitbucket pipelines (using yarn configured with registry.npmjs.com):
```
error An unexpected error occurred: "https://registry.npmjs.org/preact-compat/-/preact-compat-3.18.0.tgz: Request failed \"429 Too Many Requests\"".
```

**Comment by Jerredr** [comment]
This seems to be the same issue as reported here: https://github.com/npm/registry/issues/334

**Comment by rsanzante** [comment]
We had this error in BitBucket Pipelines but since a few minutes ago is gone. Could be just a Pipelines issue?

UPDATE: It's back, definitely it's seems problem described in https://github.com/npm/registry/issues/334#issuecomment-393076687.

**Comment by rsanzante** [comment]
Checked https://github.com/npm/registry/issues/334#issuecomment-393076687, it seems related to Pipelines and cache management. I think it the other issue there is more information, I suggest to close this issue and point to the other one.

**Comment by zkat** [comment]
Closing in favor of https://github.com/npm/registry/issues/334#issuecomment-393076687

It _should_ have been resolved by now, according to Bitbucket.
