### ISSUE TITLE
registry.npmjs.org host 151.101.36.162 is down

### ISSUE THREAD

**Issue by rtrvrtg** [npm/npm#20817]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

When trying to perform an `npm install`, requests to `registry.npmjs.org` sometimes hits IP address `151.101.36.162`, which currently displays the error message:

```
Fastly error: unknown domain: 151.101.36.162. Please check that this domain has been added to a service.

Details: cache-ams4140-AMS
```

As a result, a JSON parsing error is displayed.

```
npm ERR! Unexpected token < in JSON at position 0
npm ERR! <html>
npm ERR! <head>
npm ERR! <title>Fastly error: unknown domain</title>
npm ERR! </head>
npm ERR! <body>
npm ERR! Fastly error: unknown domain. Please check that this domain has been added to a service.
npm ERR! </body>
npm ERR! </html>
```

#### How can the CLI team reproduce the problem?

`npm i --save clipboard`

npm-debug.log: https://gist.github.com/rtrvrtg/3d6dbff6395424865aee27026bbe5f54

### supporting information:

 - `npm -v` prints: v3.10.10 (also reproducible with 5.6.0)
 - `node -v` prints: v6.14.1 (also reproducible with v8.11.1)
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [x] I develop using Vagrant on Windows. (Caveat: I use an Ubuntu VM in a Windows host, but it's not Vagrant managed.)
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by omatrot** [comment]
Same issue in France with SFR ISP.

```
nslookup registry.npmjs.org
Server:         192.168.1.1
Address:        192.168.1.1#53

Non-authoritative answer:
registry.npmjs.org      canonical name = a.sni.fastly.net.
Name:   a.sni.fastly.net
Address: 151.101.120.162
```

Ok with Bouygues Telecom ISP though:

```
nslookup registry.npmjs.org
Server:         172.20.10.1
Address:        172.20.10.1#53

Non-authoritative answer:
Name:   registry.npmjs.org
Address: 104.18.95.96
Name:   registry.npmjs.org
Address: 104.18.94.96
Name:   registry.npmjs.org
Address: 104.18.97.96
Name:   registry.npmjs.org
Address: 104.18.98.96
Name:   registry.npmjs.org
Address: 104.18.96.96
```

**Comment by akhilajay** [comment]
Same issue in UAE. getting 
npm config get registry  gives  https://registry.npmjs.org/
when tried the url getting
Fastly error: unknown domain. Please check that this domain has been added to a service.

**Comment by rtrvrtg** [comment]
The best bit about this is that trying to use an alternative registry to run an `npm install`, such as registry.node-modules.io, will still sometimes refer back to registry.npmjs.org for some packages, and fall over in a heap.

**Comment by rtrvrtg** [comment]
Hahaha. I've been pulling my hair out over this for a day and it turns out that it's a hosts file entry. Upon purging it, installation worked as expected. How the file got into this state I can't even remember now.
I'm not sure if this is the same issue that @akhilajay and @omatrot are having, but it might be worth checking anyway.

**Comment by zkat** [comment]
I've made an issue over here: https://npm.community/t/fastly-error-unknown-domain/165. Please post over there if there's anything new.
