### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by radiocity** [npm/npm#20818]
👇 **Check solution by @Elsherbo in comment below**
---
#### I'm opening this issue because:
- [ ] npm is crashing.
- [ ] npm is producing an incorrect install.
- [ ] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
- [x] npm is producing incorrect or undesirable behavior.

#### What's going wrong?
Any attempt to install packages leads to 500 Internal Server Error 

`npm --registry https://registry.npmjs.com/  i`  [log](https://github.com/npm/npm/files/2052972/com-2018-05-30T08_06_22_524Z-debug.log)
`npm --registry https://registry.npmjs.org/  i`  [log](https://github.com/npm/npm/files/2052973/org-2018-05-30T08_02_46_425Z-debug.log)
[package.json](https://github.com/npm/npm/files/2052991/package.json.txt)

#### How can the CLI team reproduce the problem?
I don`t know

### supporting information:

 - `npm -v` prints: `6.1.0`
 - `node -v` prints: `v10.3.0`
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?: `Windows 10 Pro build 1803`
 - Network issues:
   - Geographic location where npm was run: Saint-Petersburg, Russian Federation
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
   - [x] I don't use a proxy.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).
   - [x] I don't use containers.

---

`npm config set registry https://registry.yarnpkg.com/` doesn`t solve the problem (due to @marcdavi-es [recommendation](https://github.com/npm/registry/issues/339) )

**Comment by jhnferraris** [comment]
Appending more details from our end:

Version: 8.11.1
NPM version: 5.6.0
Platform: 64-bit (Windows)

I'm experiencing Internal Server error when installing a package

```
$ npm install react-native-device-information
npm ERR! code E500
npm ERR! 500 Internal Server Error: react-native-device-information@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\JF004313134\AppData\Roaming\npm-cache\_logs\2018-05-30T08_13_22_422Z-debug.log
```

I accessed the npm registry (https://registry.npmjs.org/) and it responded with: "Fastly error: unknown domain. Please check that this domain has been added to a service."

I also curled the registry and it responded with Http 500

```
$ curl -I https://registry.npmjs.org
HTTP/2 500
server: Varnish
retry-after: 0
content-type: text/html
accept-ranges: bytes
date: Wed, 30 May 2018 08:32:46 GMT
via: 1.1 varnish
x-served-by: cache-mdw17364-MDW
x-cache: MISS
x-cache-hits: 0
x-timer: S1527669167.701756,VS0,VE0
content-length: 177

```

**Comment by andriamanarivo** [comment]
I'm just facing the same issue

**Comment by lucianobargmann** [comment]
Any workaround? I tried moving to other versions of Node witn nvm and no good. Thanks

**Comment by akhilajay** [comment]
Same issue. Any Solutions?

**Comment by rtrvrtg** [comment]
Same here #20817

**Comment by jhnferraris** [comment]
@lucianobargmann @akhilajay 

@marcdavi-es has a temporary workaround https://github.com/npm/registry/issues/339#issue-327645849

**Comment by rtrvrtg** [comment]
@jhnferraris I've tried this fix, and it only seems to be useful for some packages. A lot of them will fall back to registry.npmjs.org to get the tarball, and if said domain's DNS still resolves to the broken server, it'll 500 out. Not that it's not worth trying - your project's dependencies might all be mirrored if the stars are aligned right.

**Comment by jhnferraris** [comment]
@rtrvrtg Alternatively, our team used Yarn and applied this workaround

```
yarn config set proxy <company's proxy>
```

I'm not sure if it will apply in your case.

**Comment by Elsherbo** [comment]
### i had the same problem before and i fixed it like that
**Look at your hosts files at :**
 `C:\Windows\System32\drivers\etc` 

-   **Look for** : **_https://registry.npmjs.org_** 
-   **Remove the whole line** 
-  **Save the file and try again**

**Comment by marcdavi-es** [comment]
Thanks @Elsherbo , saved my life.

For Mac users, the hosts file is at `/etc/hosts`

**Comment by radiocity** [comment]
Thank you, @Elsherbo 
There was `151.101.36.162 registry.npmjs.org`

**Comment by Stas-Buzunko** [comment]
@radiocity i had i as well because last week npm was down and i didn't know and tried every possible solution :D

**Comment by omatrot** [comment]
Still the issue here. Nothing in hosts file.

**Comment by zkat** [comment]
This is a registry issue. see https://github.com/npm/registry/issues/339#issue-327645849
