### ISSUE TITLE
Bitbucket pipelines are banned from accessing packages.npmjs.org

### ISSUE THREAD

**Issue by achtsh** [npm/npm#20819]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ x ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ x ] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Bitbucket pipelines that we run on deployment are completely down because Cloudflare banned bitbucket from accessing packages.npmjs.org

#### How can the CLI team reproduce the problem?

Here is what NPM produces:
https://gist.github.com/achtsh/d26be0a9b789c635a6915449b17c9395

**Comment by yeroon** [comment]
Same problem here. Our builds are failing. Please fix ASAP.

**Comment by rensdij** [comment]
Mine too :(

**Comment by wotan192** [comment]
The same issue. Please fix.

**Comment by sentinel09** [comment]
We have the same issue. Please fix ASAP.
`<title>Access denied | packages.npmjs.org used Cloudflare to restrict access</title>`

**Comment by jonascoenen005** [comment]
Same issue, try to fix please!

**Comment by mikenai** [comment]
same issue

**Comment by Chintanvpatel** [comment]
Please fix.

**Comment by Svanmark** [comment]
+1

**Comment by kkarczmarczyk** [comment]
Temporary solution:

1. install Verdaccio NPM proxy ( https://github.com/verdaccio/verdaccio ) on your server
2. add step: "npm set registry {your_verdaccio_proxy_url}"
3. (optionally) add "caches: -node" to step ( https://confluence.atlassian.com/bitbucket/caching-dependencies-895552876.html )

Works for me!

**Comment by le-martre** [comment]
Opened an issue at Bitbucket's end referencing this issue too, in case they have to take actions.

https://bitbucket.org/site/master/issues/16373/bitbucket-pipelines-banned-from

**Comment by zkat** [comment]
This is resolved: https://bitbucket.org/site/master/issues/16373/bitbucket-pipelines-banned-from#comment-45832175
