### ISSUE TITLE
Npm do not install dependencies of packages

### ISSUE THREAD

**Issue by senyaak** [npm/npm#20829]
#### I'm opening this issue because:

  - [x] npm is producing an incorrect install.

#### What's going wrong?
Npm do not install dependencies of package.
In my case I have project which have grunt as dependency. When I run `npm i` the grunt package wont be loaded. 
#### How can the CLI team reproduce the problem?
on linux:
1. `mkdir test`
2. `cd test`
3. `npm init`
4. `skip all by press enter`
5. add to package.json
`
  "dependencies": {
    "mosaico": "git+https://github.com/aschuetzerSaltation/mosaico.git"
  }
`
6. `npm i`

### supporting information:

 - `npm -v` prints: `6.1.0`
 - `node -v` prints: `8.11.2`
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?: Ubuntu 16.04

**Comment by kenany** [comment]
I cannot reproduce this on Linux 4.16.8, Node.js v9.9.0, npm v6.1.0.

``` bash
$ npm ls grunt
npm-20829@1.0.0 /tmp/npm-20829
└─┬ mosaico@0.17.3 (git+https://github.com/aschuetzerSaltation/mosaico.git#8efa03887e0341051bfcd219e51904e6c2143050)
  └── grunt@1.0.2
```
