### ISSUE TITLE
Npm 6 publish writes to the error stream even though the command is successful

### ISSUE THREAD

**Issue by babeal** [npm/npm#20825]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x ] npm is doing something I don't understand.
  - [x ] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

When running npm publish on a build server the new "notice" is writing an entry to the error stream which is causing our builds to fail even though the command is successful.  This behavior is different from 5.6.0 which was working fine before.

The new logger "notice" should not be writing anything to the error buffer of the console if there is no error.  Here is the error:

->> 2018-05-29T17:57:30.8798779Z ##[error]npm notice 
->> 2018-05-29T17:57:55.2331471Z ##[error]Process completed with exit code 0 and had 1 error(s) written to the error stream.

#### How can the CLI team reproduce the problem?

Create a package and run this command
npm publish --access public $distFolder\$distFolderName --registry https://your-private-registry

### supporting information:

 - `npm -v` prints: 6.1.0
 - `node -v` prints: 8.9.1
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?: Windows
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by babeal** [comment]
So here is the problem

if i run the command npm pack and redirect the stdout and stderr

```
npm pack > output.txt 2> output.err
```

The output.txt contains just he tgz file however the output.err contains all the new notice messages being output by npm.  

I just ran the same thing with 5.6.0 and nothing is output to the output.err.  So this is an issue with just >6

**Comment by legodude17** [comment]
Ref: https://github.com/npm/npm/issues/118#issuecomment-325440

**Comment by babeal** [comment]
@legodude17 thanks.  I couldn't find it anywhere, guess my search criteria wasn't any good.
