### ISSUE TITLE
Pesterchum doesn't open

### ISSUE THREAD

**Issue by leothegambler** [npm/npm#20834]
I downloaded pesterchum yesterday and it was working fine, but now it doesn't. I double tap the shortcut and I get a loading circle next to my mouse but it just goes away after a few seconds. I have uninstalled and reinstalled it countless times and it just won't work. I don't know what to do to fix it.

**Comment by legodude17** [comment]
You should probably report this to https://github.com/illuminatedwax/pesterchum/issues
