### ISSUE TITLE
Error 418 "I'm a teapot" still occurring

### ISSUE THREAD

**Issue by Rain2222** [npm/npm#20836]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [x] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I get error 418 when trying to install any package

#### How can the CLI team reproduce the problem?
npm install

   No npm-debug.log file was produced.

Getting this error when trying to install any packages:
```
<npm ERR! code E418
npm ERR! 418 I'm a teapot: nodemon@latest>
```

I have uninstalled and reinstalled Nodejs and npm twice since reading [here ](https://github.com/npm/npm/issues/20791)that the error has been fixed, but it is still occurring. I removed any proxy settings, cleared the cache and added the proxies back. 

### supporting information:

 - `npm -v` prints:
`6.1.0`

 - `node -v` prints:
`v10.3.0`

 - `npm config get registry` prints:
`http://registry.npmjs.org/`

 - Windows, OS X/macOS, or Linux?:
Windows 7

 - Network issues:
   - Geographic location where npm was run:
Australia

   - [x] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
None

**Comment by kudokk** [comment]
im wating for this fixed, using yarn.

**Comment by brandonpittman** [comment]
I'm getting 418s again too (behind a proxy) but "418 Undefined: pnpm@latest" instead of the teapot message. Thank goodness Yarn exists, I suppose.

**Comment by abralock** [comment]
I'm still see it on behind proxy.... :(

**Comment by nick1740** [comment]
I am behind the proxy and getting the same error @KenanY

**Comment by rmcmahon** [comment]
I was getting the same error as well (using older npm and node versions), but noticed that in my .npmrc file I was using http://registry.npmjs.org/ (similar to above) as the registry url which was then getting redirected to https. It seems our proxy was then also adding the 443 port, so updating the url to https in the .npmrc file worked. 
npm -v
5.6.0
node -v
v6.10.0

**Comment by Rain2222** [comment]
@rmcmahon If I change the registry url to https the teapot error goes away but I get an ETIMEDOUT error instead.

**Comment by YanivKimhi** [comment]
Adding to ~/.npmrc  :

registry=https://registry.npmjs.org/

works for me 👍

**Comment by Rain2222** [comment]
If I use 
`npm install -d`
or `npm install --save-dev`
it works. Found the solution in issue 7945 referenced below. Not sure how I can install something globally though as I get the ETIMEDOUT error using -g.

So to sum up the combination that works for me: 

1. Set registry url to https to avoid 418 error 

2. Use `npm install -d` to avoid ETIMEDOUT error


#7945

**Comment by mattcobley** [comment]
Can confirm that changing the registry entry to use https in .npmrc works for me, although I have to add "strict-ssl=false" to the file too due to a self-signed certificate - without that I was getting a "SELF_SIGNED_CERT_IN_CHAIN" error.

**Comment by kenany** [comment]
Perhaps this should be moved to <https://github.com/npm/registry>, since the error is coming from the registry.

**Comment by zkat** [comment]
This is a registry issue, as @KenanY says. Closing.
