### ISSUE TITLE
NPM Installing Highest Alphanumeric Pre-Release Package instead of one specified

### ISSUE THREAD

**Issue by jonathw** [npm/npm#20831]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I have three prerelease tag versions of my package api-test published to my local npm repo (artifactory).

- 1.0.0-rel.0 -> 1.0.0-rel.20 
- 1.0.0-beta.0 -> 1.0.0-beta.5
- 1.0.0-zeta.0 -> 1.0.0-zeta.2

When I do an npm install using a prerelease tag range the wrong package version is installed.

npm install api-test@~1.0.0-beta.0

Expected: 1.0.0-beta.5
Actual: 1.0.0-zeta.2

#### How can the CLI team reproduce the problem?

1. Create a couple different npm packages using prerelease tags as shown above
2. npm install package_name@~1.0.0-beta.0
3. npm list package_name
4. Verify version installed

### supporting information:

- `npm -v` prints: 6.1.0
- `node -v` prints: 8.11.2
- `npm config get registry` prints: Internal artifactory repo hosting npm packages
- Windows, OS X/macOS, or Linux?: Linux
 - Network issues: None
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [x] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by zkat** [comment]
https://semver.org/#spec-item-11

**Comment by zkat** [comment]
Basically, as confusing as this is, this is working as expected and, afaik, right in line with the semver spec. Prereleases are weird like that. If you think this can be improved, consider posting in https://npm.community/c/ideas or, if you want to make a more formal proposal where you consider more of the details involved, file a new RFC in [the RFCs repo](https://github.com/npm/rfcs).
