### ISSUE TITLE
Method not allowed in npm install

### ISSUE THREAD

**Issue by fabceolin** [npm/npm#20830]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

The installer stops with an error.

#### How can the CLI team reproduce the problem?

npm install

npm WARN package.json dotenv-expand@4.2.0 No repository field.
npm http GET https://registry.npmjs.org/material-ui
npm http 304 https://registry.npmjs.org/material-ui
npm WARN deprecated material-ui@1.0.0-beta.47: You can now upgrade to @material-ui/core
npm http GET https://registry.npmjs.org/brcast
npm http GET https://registry.npmjs.org/types/react-transition-group
npm http GET https://registry.npmjs.org/classnames
npm http GET https://registry.npmjs.org/deepmerge
npm http GET https://registry.npmjs.org/hoist-non-react-statics
npm http GET https://registry.npmjs.org/dom-helpers
npm http GET https://registry.npmjs.org/jss-default-unit
npm http GET https://registry.npmjs.org/jss-camel-case
npm http GET https://registry.npmjs.org/jss-global
npm http GET https://registry.npmjs.org/jss-nested
npm http GET https://registry.npmjs.org/keycode
npm http GET https://registry.npmjs.org/jss-props-sort
npm http GET https://registry.npmjs.org/jss-vendor-prefixer
npm http GET https://registry.npmjs.org/jss
npm http GET https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/normalize-scroll-left
npm http GET https://registry.npmjs.org/react-lifecycles-compat
npm http GET https://registry.npmjs.org/react-jss
npm http GET https://registry.npmjs.org/prop-types
npm http GET https://registry.npmjs.org/react-event-listener
npm http GET https://registry.npmjs.org/react-scrollbar-size
npm http GET https://registry.npmjs.org/scroll
npm http GET https://registry.npmjs.org/react-transition-group
npm http GET https://registry.npmjs.org/recompose
npm http GET https://registry.npmjs.org/warning
npm http GET https://registry.npmjs.org/react-popper
npm http GET https://registry.npmjs.org/types/jss
npm http GET https://registry.npmjs.org/babel/runtime
npm http 304 https://registry.npmjs.org/brcast
npm http 304 https://registry.npmjs.org/dom-helpers
npm http 304 https://registry.npmjs.org/jss-default-unit
npm http 304 https://registry.npmjs.org/jss-camel-case
npm http 304 https://registry.npmjs.org/prop-types
npm http 304 https://registry.npmjs.org/classnames
npm http 304 https://registry.npmjs.org/react-lifecycles-compat
npm http 304 https://registry.npmjs.org/deepmerge
npm http 304 https://registry.npmjs.org/react-popper
npm http 304 https://registry.npmjs.org/react-event-listener
npm http 304 https://registry.npmjs.org/recompose
npm http 304 https://registry.npmjs.org/jss-nested
npm http 304 https://registry.npmjs.org/keycode
npm http 304 https://registry.npmjs.org/jss-global
npm http 304 https://registry.npmjs.org/jss-props-sort
npm http 304 https://registry.npmjs.org/react-jss
npm http 304 https://registry.npmjs.org/scroll
npm http 304 https://registry.npmjs.org/jss-vendor-prefixer
npm http 304 https://registry.npmjs.org/normalize-scroll-left
npm http 304 https://registry.npmjs.org/hoist-non-react-statics
npm http 304 https://registry.npmjs.org/react-transition-group
npm http 304 https://registry.npmjs.org/warning
npm http 304 https://registry.npmjs.org/lodash
npm http 304 https://registry.npmjs.org/react-scrollbar-size
npm http 304 https://registry.npmjs.org/jss
npm http 405 https://registry.npmjs.org/babel/runtime
npm http 405 https://registry.npmjs.org/types/jss
npm http 405 https://registry.npmjs.org/types/react-transition-group
npm ERR! Error: Method Not Allowed
npm ERR!     at errorResponse (C:\ProgramData\chocolatey\lib\npm\tools\node_modules\npm\lib\cache.js:753:14)
npm ERR!     at C:\ProgramData\chocolatey\lib\npm\tools\node_modules\npm\lib\cache.js:773:12
npm ERR!     at saved (C:\ProgramData\chocolatey\lib\npm\tools\node_modules\npm\node_modules\npm-registry-client\lib\get.js:148:7)
npm ERR!     at C:\ProgramData\chocolatey\lib\npm\tools\node_modules\npm\node_modules\graceful-fs\polyfills.js:133:7
npm ERR!     at FSReqWrap.oncomplete (fs.js:135:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 10.0.17134
npm ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\ProgramData\\chocolatey\\lib\\npm\\tools\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd d:\src\vcs\LOBOS.martin\network-grid
npm ERR! node -v v8.10.0
npm ERR! npm -v 1.4.9
npm ERR! code E405
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     d:\src\vcs\LOBOS.martin\network-grid\npm-debug.log
npm ERR! not ok code 0

### supporting information:

 - `npm config get registry` prints:
λ npm config get registry
https://registry.npmjs.org/

 - Windows, OS X/macOS, or Linux?:
npm ERR! System Windows_NT 10.0.17134

**Comment by legodude17** [comment]
Your npm version is years old an no longer supported. Please update.

**Comment by kenany** [comment]
Closing because we do not support `npm@1`.
