### ISSUE TITLE
Unable to fetch npm node modules

### ISSUE THREAD

**Issue by pendemdivya** [npm/npm#20841]
I'm opening this issue because:
 npm is crashing.
 
What's going wrong?
Below is the error thrown while downloading node modules.
Updating node modules
npm http GET http://registry.npmjs.org/es5-shimify/0.0.1
npm http GET http://registry.npmjs.org/json2ify/0.0.1
npm http GET http://registry.npmjs.org/jqueryify/0.0.3
npm http GET http://registry.npmjs.org/spine/1.0.6
npm http 503 http://registry.npmjs.org/jqueryify/0.0.3
npm ERR! registry error parsing json

npm ERR! Error: failed to fetch from registry: jqueryify/0.0.3
npm ERR!     at /usr/local/lib/node_modules/npm/lib/utils/npm-registry-client/get.js:139:12
npm ERR!     at cb (/usr/local/lib/node_modules/npm/lib/utils/npm-registry-client/request.js:31:9)
npm ERR!     at Request._callback (/usr/local/lib/node_modules/npm/lib/utils/npm-registry-client/request.js:153:14)
npm ERR!     at Request.callback (/usr/local/lib/node_modules/npm/node_modules/request/main.js:119:22)
npm ERR!     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/main.js:525:16)
npm ERR!     at Request.emit (events.js:67:17)
npm ERR!     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/main.js:484:14)
npm ERR!     at IncomingMessage.emit (events.js:88:20)
npm ERR!     at HTTPParser.onMessageComplete (http.js:137:23)
npm ERR!     at Socket.ondata (http.js:1150:24)
npm ERR! You may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
npm ERR!
npm ERR! System Linux 4.4.35-33.55.amzn1.x86_64
npm ERR! command "node" "/usr/local/bin/npm" "install" "."
npm ERR! cwd /wm/apps/test-scripts-ui/test-scripts-ui-1.6.104
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.4
npm ERR! message failed to fetch from registry: jqueryify/0.0.3
npm http 503 http://registry.npmjs.org/es5-shimify/0.0.1
npm ERR! registry error parsing json
npm http 503 http://registry.npmjs.org/spine/1.0.6
npm ERR! registry error parsing json
npm http 503 http://registry.npmjs.org/json2ify/0.0.1
npm ERR! registry error parsing json
npm ERR!
npm not ok
npm http GET http://registry.npmjs.org/es5-shimify/0.0.1
npm http GET http://registry.npmjs.org/json2ify/0.0.1
npm http GET http://registry.npmjs.org/jqueryify/0.0.3
npm http GET http://registry.npmjs.org/spine/1.0.6
npm http 503 http://registry.npmjs.org/jqueryify/0.0.3
npm ERR! registry error parsing json
npm http 503 http://registry.npmjs.org/es5-shimify/0.0.1
npm ERR! registry error parsing json
npm http 503 http://registry.npmjs.org/spine/1.0.6
npm ERR! registry error parsing json
npm http 503 http://registry.npmjs.org/json2ify/0.0.1
npm ERR! registry error parsing json

**Comment by legodude17** [comment]
Your versions of node and npm are years old and no longer supported. Please update.

**Comment by zkat** [comment]
This is a registry issue and should be resolved by now.
