### ISSUE TITLE
npm publish returns  "integrity checksum error" on first update

### ISSUE THREAD

**Issue by roman-jaduda** [npm/npm#20844]
#### I'm opening this issue because:
  - [x] npm is doing something I don't understand.

#### What's going wrong?
I created an npm registry entry on one computer. On another computer I installed this package via npm install, then used "npm login" for login, made a change and then called "npm publish".

Now I receive:

integrity checksum error: expected 2e54d2fbd179b66e240a4ebabd08c9bf9b45b490, got <bad integrity> : eslint-config-my-company

I am completely new in npm publishing. So mayme I am doing some stupid rookie mistake here.

### supporting information:

pm ERR! publish Failed PUT 400
npm ERR! Linux 4.15.0-13-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "publish"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code E400

Thanks for any feedback

**Comment by VenkatKadam** [comment]
code EINTEGRITY
npm ERR! sha512..please find a appropriate solution

**Comment by legodude17** [comment]
Does this occur on the latest version of `npm`?

**Comment by VenkatKadam** [comment]
Yes

**Comment by legodude17** [comment]
So this happened because you `npm publish`ed, then on a different computer `npm login`, `npm install`, make changes to package in `node_modules`, then `npm publish`?

**Comment by VenkatKadam** [comment]
I am using windows8 desktop in my office..I will try it by tomorrow

**Comment by zkat** [comment]
Please see https://npm.community/t/shasum-check-or-integrity-eintegrity-errors/153 for troubleshooting this.

If the troubleshooting guide does not help, please file a new support issue on that board with necessary details.
