### ISSUE TITLE
Use relative path for cafile

### ISSUE THREAD

**Issue by tkrotoff** [npm/npm#20842]
Following this node-gyp issue: https://github.com/nodejs/node-gyp/issues/1214

NPM should accept a relative path for cafile (.npmrc) and then configure node-gyp with the absolute cafile path (computed using the relative path).

**Comment by zkat** [comment]
We don't accept feature requests here anymore. Please post partial ideas in https://npm.community/c/ideas, and if you have a more complete feature proposal, file a new RFC in https://github.com/npm/rfcs.
