### ISSUE TITLE
Npm publish does not update package in repo

### ISSUE THREAD

**Issue by Firrero** [npm/npm#20850]
After npm publish getting success, but repo is not updating ....

![image](https://user-images.githubusercontent.com/29453091/40793693-c5c790a6-6505-11e8-936f-bf40e02a0d52.png)

![image](https://user-images.githubusercontent.com/29453091/40793651-a681388c-6505-11e8-87ac-b7232d16d58f.png)

It stays at 1.2.4

**Comment by alexpaluzzi** [comment]
Our private packages are also not updating. It is halting our deployments.

**Comment by Firrero** [comment]
But outside of the page, it shows ok 
![image](https://user-images.githubusercontent.com/29453091/40794407-b9aac692-6507-11e8-875d-0bd28817e282.png)

**Comment by alexpaluzzi** [comment]
They're on it: https://status.npmjs.org/incidents/p91lxl8zbj2x

**Comment by leonardofaria** [comment]
@alexpaluzzi when your private packages stopped? only today?

**Comment by zkat** [comment]
Closing this because it's part of a known incident. (as per https://github.com/npm/npm/issues/20850#issuecomment-393594305)
