### ISSUE TITLE
npm publish has succeeded but package is not available

### ISSUE THREAD

**Issue by alan-agius4** [npm/npm#20857]
`npm publish` has succeeded but the package has not been publish to the public npm repo

```sh
npm publish
npm ERR! publish Failed PUT 403
npm ERR! code E403
npm ERR! You cannot publish over the previously published versions: 1.9.0. : @speedy/commit-msg-hook
```

```sh
npm info @speedy/commit-msg-hook version
1.8.2
```

Seems related to: 
https://status.npmjs.org/incidents/3rjzvts6v98k

**Comment by zkat** [comment]
As you say, it's related to the incident, so I'm closing this.

**Comment by zkat** [comment]
See also: https://npm.community/t/missing-package-versions-after-apparently-successful-publishes/161
