### ISSUE TITLE
npm should error on invalid flags

### ISSUE THREAD

**Issue by wyardley** [npm/npm#20856]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
npm doesn't error when a flag that's not valid for a particular context is passed

#### How can the CLI team reproduce the problem?
`npm  anything --asdf`

### supporting information:

 - `npm -v` prints: `5.10.0` ## also with 6.x
 - `node -v` prints: `v8.11.2`
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: OS X
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [x] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

#### What's the feature?
Switch to a library that handles documenting arguments and arg parsing in a consistent way. Build or generate the inline / offline docs based on this information. Have npm error and return usage information for the context when invalid flags are passed.

#### What problem is the feature intended to solve?
Because there's no error currently, you can pass in invalid parameters and not realize they're invalid for a particular context. e.g., if you type:
`npm audit --format=json`
instead of
`npm audit --json`
you get the normal output of `npm audit`, vs. an error that you passed an invalid flag.

Additionally, if the command line flags and args are documented this way, there's less chance for drift between usage / docs and reality.

#### Is the absence of this feature blocking you or your team? If so, how?
No

#### Is this feature similar to an existing feature in another tool?
Yes

#### Is this a feature you're prepared to implement, with support from the npm CLI team?
Would be happy to help with converting subcommands if the basic skeleton is in place. Or, if it would be feasible, if there's a specific tool (commander? minimist? etc.), would be happy to work on implementing it first for a smaller subcommand, if that made sense.

**Comment by legodude17** [comment]
This would make a great rfc over at https://github.com/npm/rfcs

**Comment by zkat** [comment]
As @legodude17 says -- we're also not accepting feature requests that are not RFCs anymore. Miscellaneous discussion of ideas should go in https://npm.community/c/ideas from now on, with the intent of eventually forming an RFC from them.
