### ISSUE TITLE
Still Receiving Teapot Error

### ISSUE THREAD

**Issue by dh-technology-co-uk** [npm/npm#20867]
#### I'm opening this issue because:

  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [x] npm is producing incorrect or undesirable behavior.

#### What's going wrong?
I'm trying to create a new project using npm install -g vue-cli and I'm receiving a 418 teapot error.

#### How can the CLI team reproduce the problem?
Create a new directory and run npm install -g vue-cli 

### supporting information:

 - `npm -v` prints: 6.0.1
 - `node -v` prints: 10.3.0
 - `npm config get registry` prints: http://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.

**Comment by dh-technology-co-uk** [comment]
![image](https://user-images.githubusercontent.com/30044592/40835406-4845e17e-658b-11e8-9f13-09f5436ea5c7.png)

**Comment by predzme** [comment]
Try : _npm config set registry https://registry.npmjs.org_
It solved the problem for the "npm install" for me, yesterday.

I'm experiencing a similar problem with angular "_ng new myProjectName_" command as it uses npm to download dependencies, I'm stuck with it. Even if I put https registry it gets stuck with "fetchMetaData" . So I'm struggling between the 418 teapot and that "fetchMetaData" problem. 
.... being behind company proxy can be annoying...

**Comment by dh-technology-co-uk** [comment]
@predzme Thank you, this is working now
