### ISSUE TITLE
npm  publish   occur  error   Package name triggered spam detection;

### ISSUE THREAD

**Issue by hukai123** [npm/npm#20866]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:  3.10.8
 - `node -v` prints:  6.9.1
 - `npm config get registry` prints:   registry = "https://registry.npmjs.org/"
 - Windows, OS X/macOS, or Linux?:    Windows
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by hukai123** [comment]
what   is  it ,what  the  problem
when run npm publish occur error Package name triggered spam detection; if you believe this is in error, please contact support@npmjs.com :

**Comment by kenany** [comment]
Nothing we can really do from this end; this issue tracker is for issues regarding the CLI, and this error is coming from the registry. Please try emailing the address in the error message for assistance.
