### ISSUE TITLE
Can't create ionic app because of an error with npm i (exit code 1)

### ISSUE THREAD

**Issue by Kikimanox** [npm/npm#20877]
#### I'm opening this issue because:

npm is producing incorrect or undesirable behavior.

#### What's going wrong?

Can't create my application with `ionic start AppNAme` because I keep getting this errors

Image links of the problem:
http://owo.sh/10f687.png
http://owo.sh/874aa4.png

### supporting information:

 - `npm -v` prints: 6.1.0
 - `node -v` prints: v10.2.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Win10

**Comment by legodude17** [comment]
This appears to be a problem with `node-sass`, not `npm`.

**Comment by kenany** [comment]
Yeah this is `node-sass`'s install script throwing an error.
