### ISSUE TITLE
NPM not installing my program

### ISSUE THREAD

**Issue by Quadsam** [npm/npm#20873]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [X] npm is producing an incorrect install.
  - [X] npm is doing something I don't understand.
  - [X] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Not installing
#### How can the CLI team reproduce the problem?
run npm intall

### supporting information:

 - `npm -v` prints: 1.4.21
 - `node -v` prints: v4.8.2
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux
 - Network issues:
   - Geographic location where npm was run: Utah US
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by zmilonas** [comment]
Since the version of Node and NPM you're using are almost 4 years old now and they're not officially supported anymore I would suggest updating npm and node to the current LTS version (v8 and npm v5) also the correct command is `npm install` not `npm intall` for running the installation.

You also did not provide sufficient details for the bug. And whether it is a a bug with npm or "your program".

What program? What is the error message? What have you tried so far?

Please correct your issue or close it.

**Comment by Quadsam** [comment]
I cannot update npm or node as whenever I try I get the message `NPM is already the newest version` and `Node is already the newest version`. Sorry when I said `npm intall` I ment `npm install` it was a spelling error. If this helps I am using a Raspberry Pi computer running Raspbian which is based on Debian Linux. I am trying to install Electon to build desktop apps. I get the error:

npm ERR! Error: Method Not Allowed
npm ERR!     at errorResponse (/usr/share/npm/lib/cache/add-named.js:260:10)
npm ERR!     at /usr/share/npm/lib/cache/add-named.js:203:12
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:167:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:82:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.14.30-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/pi/electron-quick-start
npm ERR! node -v v4.8.2
npm ERR! npm -v 1.4.21
npm ERR! code E405
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/electron-quick-start/npm-debug.log
npm ERR! not ok code 0

I have attached my debug log
[npm-debug.log](https://github.com/npm/npm/files/2065381/npm-debug.log)

**Comment by zmilonas** [comment]
I would suggest firstly trying to remove node and npm completly from your system and installing the newest versions again then.

https://nodejs.org/en/

**Comment by Quadsam** [comment]
I used `sudo apt-get purge npm node` and removed them then used `sudo apt-get install npm node` then tried to use `npm install` again and got the same error

**Comment by Quadsam** [comment]
They are also the same versions as before.

**Comment by zmilonas** [comment]
Did you do `sudo apt-get update`? :joy:

**Comment by Quadsam** [comment]
yes

**Comment by zmilonas** [comment]
Either way this doesn't seem like a npm issue but rather your distro/package manager issue since you're not on the latest version of npm.
