### ISSUE TITLE
`npm adduser` authentication error 

### ISSUE THREAD

**Issue by plibither8** [npm/npm#20883]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [x] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
This is the first time I am attempting to create a user or login into npm. Upon running `npm adduser` or `npm login` I get the following error:
```
npm ERR! code EAUTHIP
npm ERR! Unable to authenticate, need: Basic
```
I have looked up other similar issues but none of them really clearly indicated any problem or gave a solution to the problem.

#### How can the CLI team reproduce the problem?
I have installed npm using the regular install procedure for Ubuntu (Linux) after which I have not edited, added or removed anything in the `.npmrc` file either. Thus I am not too sure how I can successfully replicate this problem in someone else's computer since these are the basic steps.

Debug logs:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'adduser' ]
2 info using npm@6.1.0
3 info using node@v8.11.1
4 verbose npm-session 66e0842cf5778608
5 verbose web login before first POST
6 http request → POST https://registry.npmjs.org/-/v1/login
7 http 401 ← Unauthorized (https://registry.npmjs.org/-/v1/login)
8 verbose web login not supported, trying couch
9 verbose login before first PUT { _id: 'org.couchdb.user:plibither8',
9 verbose login   name: 'plibither8',
9 verbose login   password: 'XXXXX',
9 verbose login   type: 'user',
9 verbose login   roles: [],
9 verbose login   date: '2018-06-04T07:48:13.666Z' }
10 http request → PUT https://registry.npmjs.org/-/user/org.couchdb.user:plibither8
11 http 401 ← Unauthorized (https://registry.npmjs.org/-/user/org.couchdb.user:plibither8)
12 verbose adduser before first PUT { _id: 'org.couchdb.user:plibither8',
12 verbose adduser   name: 'plibither8',
12 verbose adduser   password: 'XXXXX',
12 verbose adduser   email: 'plibither8@gmail.com',
12 verbose adduser   type: 'user',
12 verbose adduser   roles: [],
12 verbose adduser   date: '2018-06-04T07:48:16.217Z' }
13 http request → PUT https://registry.npmjs.org/-/user/org.couchdb.user:plibither8
14 http 401 ← Unauthorized (https://registry.npmjs.org/-/user/org.couchdb.user:plibither8)
15 verbose stack Error: Unable to authenticate, need: Basic
15 verbose stack     at fetch.defaults.catch.then.then.result (/usr/lib/node_modules/npm/node_modules/npm-profile/index.js:373:15)
15 verbose stack     at <anonymous>
15 verbose stack     at process._tickCallback (internal/process/next_tick.js:188:7)
16 verbose statusCode 401
17 verbose cwd /home/plibither8/Projects/Personal/licensed
18 verbose Linux 4.13.0-41-generic
19 verbose argv "/usr/bin/node" "/usr/bin/npm" "adduser"
20 verbose node v8.11.1
21 verbose npm  v6.1.0
22 error code EAUTHIP
23 error Unable to authenticate, need: Basic
24 verbose exit [ 1, true ]
```

### supporting information:

 - `npm -v` prints: 6.1.0
 - `node -v` prints: v8.11.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux Ubuntu 16.04
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by plibither8** [comment]
Please look into this, thanks!

**Comment by endoftheline001** [comment]
I'm having the same issues! Hope someone can solve this.

**Comment by endoftheline001** [comment]
@plibither8  changing my password worked for me

**Comment by plibither8** [comment]
@endoftheline001 thanks a lot! that fixed it :)

**Comment by alundiak** [comment]
I can't configure Jenkins to `npm publish`, `npm adduser/login` is not for CI, that is why I thought using NodeJS Plugin for Jenkins would work, but it is not. Any suggestions?
