### ISSUE TITLE
solc module not found

### ISSUE THREAD

**Issue by Samrat-Eth** [npm/npm#20893]
#### I'm opening this issue because:

 
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
npm start cannot find the solc module although version 3.5.2 is installed
OS: Linux
[npm-debug.log](https://github.com/npm/npm/files/2069829/npm-debug.log)

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
Your version of npm is old and supported. Please update.

**Comment by kenany** [comment]
Error log states that the error is coming from `node app.js`, not `npm` itself. All `npm` is doing here is letting you know about the error.
