### ISSUE TITLE
Extended layout & documentation for npm run

### ISSUE THREAD

**Issue by martinheidegger** [npm/npm#20908]
#### What's the feature?

Extended layout & documentation feature when using `npm run` to show list of commands.

Currently, `npm run` shows a list of commands and their implementation. In commands it
is already possible to use comments to document the scripts like this:

```json
  "scripts": {
     "lint": "standard\n# Checks all the files for correct syntax"
  }
```

But in the display it looks a bit odd:

<img width="388" alt="screen shot 2018-06-06 at 08 30 56" src="https://user-images.githubusercontent.com/914122/41008101-1470e100-6964-11e8-9b22-164118c2d485.png">

The features suggestion is now to improve the way documentation is written. I could think of
several steps, like:

- If a comment is detected in the script: Only show the comment.
- ... and add a flag to show the command as well.
- If a comment is detected: show the command part in grey
- Indent multiline scripts
- Having another property in the package.json that holds the documentation for scripts.
- Have a way to reference bigger documentation blocks in the comment `# ./scripts/lint.txt`

#### What problem is the feature intended to solve?

In order to document run scripts we need a separate location (i.e. the Readme file).
The distance between the scripts location and documentation make it hard to keep the
lists up-to-date. Also: documenting the scripts in the Readme takes away attention from the
actual documentation. It would be nice if there was possible to just write:

> Type `npm run` to learn more about the development process.

#### Is the absence of this feature blocking you or your team?

No.

#### Is this a feature you're prepared to implement, with support from the npm CLI team?

Yes.

**Comment by legodude17** [comment]
This sounds like it would make a great RFC over at https://github.com/npm/rfcs!

**Comment by kenany** [comment]
ref. https://github.com/npm/npm/issues/14161, https://github.com/npm/npm/issues/17314, https://github.com/npm/npm/issues/18515

**Comment by martinheidegger** [comment]
@KenanY my google-fu is shamefully bad. Thanks for pointing those out!
