### ISSUE TITLE
Package Download Count Issue

### ISSUE THREAD

**Issue by ahmeddilshad** [npm/npm#20900]
Every package is showing very less downloaded on front-end. I think this is an issue. May be it's not a serious issue. LOL
![bcrypt](https://user-images.githubusercontent.com/25632929/40977776-9b312184-68ef-11e8-8d89-fdbefd8a0cd5.PNG)
![express](https://user-images.githubusercontent.com/25632929/40977817-ac90835c-68ef-11e8-8d1d-fc6031fc09f2.PNG)
![request](https://user-images.githubusercontent.com/25632929/40977859-ba0c8a6c-68ef-11e8-9519-c4a99c9aa411.PNG)

**Comment by hodgef** [comment]
It's been reported to the website team here:
https://github.com/npm/www/issues/424

**Comment by kenany** [comment]
Closing since this is not an issue with the `npm` CLI.
