### ISSUE TITLE
503 Service Unavailable errors from registry.npmjs.org

### ISSUE THREAD

**Issue by cweekly** [npm/npm#20904]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Our Appveyor CI builds are triggering intermittent 503 responses from the registry, e.g.

```An unexpected error occurred: "https://registry.npmjs.org/classnames/-/classnames-2.2.5.tgz: Request failed \"503 Service Unavailable\"".```

#### How can the CLI team reproduce the problem?

(shrug) `npm install` on a standard project?

### supporting information:
 - Network issues:
   - Geographic location where npm was run:
  Appveyor instance is, I think, running from US-East... 
no proxies or containers involved, just a vanilla setup resulting in 503's this morning.

**Comment by legodude17** [comment]
I think this would be better reported at https://github.com/npm/registry.

**Comment by kharlamov** [comment]
Reported here: https://github.com/npm/registry/issues/349.

**Comment by cweekly** [comment]
Agreed, @legodude17! And thanks @kharlamov! :)

**Comment by HamidAghdaee** [comment]
This was working for us for a few minutes. down again
