### ISSUE TITLE
reanmed instead of renamed

### ISSUE THREAD

**Issue by provokateurin** [npm/npm#20901]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
A misspelling in the installer. It sometimes says "reanmed" instead of "renamed".

#### How can the CLI team reproduce the problem?

```bash
npm install raspi-serial --save
```

### supporting information:

 - `npm -v` prints: 6.1.0
 - `node -v` prints: v10.3.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
Can you post a screenshot or copy-paste of when it does this?

**Comment by provokateurin** [comment]
Here it is:
```
npm WARN deprecated parser-regex@1.0.2: reanmed to @serialport/parser-regex
npm WARN deprecated parser-readline@1.0.2: reanmed to @serialport/parser-readline
npm WARN deprecated parser-cctalk@1.0.2: reanmed to @serialport/parser-cctalk
npm WARN deprecated parser-ready@1.0.2: reanmed to @serialport/parser-ready
npm WARN deprecated parser-delimiter@1.0.2: reanmed to @serialport/parser-delimiter
npm WARN deprecated parser-byte-length@1.0.2: renamed to @serialport/parser-byte-length
```

But as I said it's not always misspelled.

**Comment by legodude17** [comment]
That's not an issue with `npm`, that is an issue with the deprecation message of those packages.

**Comment by provokateurin** [comment]
oh sorry
