### ISSUE TITLE
npm --version returns an error

### ISSUE THREAD

**Issue by anton-mladenov** [npm/npm#20917]
I'm opening this issue because:

  - [**X**] npm is producing incorrect or undesirable behavior.

I just wanted to check which version of npm I have and the image below shows what I got back.

Here's a screenshot showing the error I get. 

<img width="797" alt="screen shot 2018-06-06 at 22 24 03" src="https://user-images.githubusercontent.com/32343768/41063359-b5970e64-69d8-11e8-9b89-ad615f68129b.png">

**Comment by watilde** [comment]
Which version of Node.js are you using? You seems to use `> v4` which is not supported anymore.

See also: https://github.com/npm/npm#important

**Comment by anton-mladenov** [comment]
@watilde 
It should have been the latest since that was the one I used the last time. 
However, I wanted to "fix" something and ofc everything else broke. :D 
After uninstalling npm and NodJS, I reinstalled and they all seem to be working fine. (together with a working nvm this time)

**Comment by kenany** [comment]
Closing since this has been resolved. I see Node.js v5.12.0 in your screenshot, which has not been supported for quite some time now, so that's almost certainly why you experienced this error.
