### ISSUE TITLE
[CRITICAL] npmjs inconsistently returns 404 for HEAD requests

### ISSUE THREAD

**Issue by mohammadtibi** [npm/npm#20914]
Hello npm team,

In the past couple of days Artifactory users are running into a blocking issue, due to npmjs returning 404 for HEAD requests for some endpoints for unclear reason.

For example:

If we run:

$ curl -XHEAD "https://registry.npmjs.org/@angular%2fcli" -I

HTTP/2 404
date: Wed, 06 Jun 2018 11:30:03 GMT
content-type: application/json
content-length: 21
set-cookie: __cfduid=d0bf88341e559bdd97b7d48669e7310781528284602; expires=Thu, 06-Jun-19 11:30:02 GMT; path=/; domain=.registry.npmjs.org; HttpOnly
cf-cache-status: EXPIRED
cf-ray: 426a8b6a9858ad75-TLV
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
vary: Accept-Encoding
server: cloudflare

As you may see we got a 404 for the HEAD request.
If we run the same command few hours later, it may return 200 and few hours later 404 once again.
There is some unclear inconsistency.

For example the below REST API call

$ curl -XHEAD "https://registry.npmjs.org/@pnp%2fodata" -I

HTTP/2 200
date: Wed, 06 Jun 2018 11:33:13 GMT
content-type: application/json; charset=UTF-8
content-length: 52354
set-cookie: __cfduid=ddd0917685a4416dade8382bcba3ce5491528284792; expires=Thu, 06-Jun-19 11:33:12 GMT; path=/; domain=.registry.npmjs.org; HttpOnly
accept-ranges: bytes
cache-control: public, max-age=14400
cf-cache-status: HIT
cf-ray: 426a900fbdf2ad93-TLV
etag: "9d8bcef6c06777eb076a8de06d691e8a"
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
last-modified: Tue, 29 May 2018 11:10:37 GMT
vary: Accept-Encoding
server: cloudflare

Returns 200, one hour ago, it returned 404.

Just as a side note, GET requests seem to work, the issue seem to be only with HEAD requests.

We guess that the issue might be related to the CDN nodes the request reaches which causing the HEAD requests to fail.
Seems like when the cf-cache-status header is set to HIT we get 200
And when the cf-cache-status header is set to EXPIRED or MIS we get 404

This is a blocking issue, please look into it as soon as possible.
This is a  change in behaviour.

Looking forward to your response.

**Comment by legodude17** [comment]
I am pretty sure this should be reported to https://github.com/npm/registry.

**Comment by kenany** [comment]
Closing since this seems to be a registry issue.
