### ISSUE TITLE
isntall

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [npm/npm#20923]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] npm is producing incorrect or undesirable behavior.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?

Spelling error of `isntall` instead of `install` in line `aliases: i, isntall`

#### How can the CLI team reproduce the problem?

Run `npm i -h`

### supporting information:

 - `npm -v` prints: 6.1.0
 - `node -v` prints: v6.11.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: OS X/macOS

**Comment by legodude17** [comment]
That's intentional, the alias is there to help people who spell `install` incorrectly.

**Comment by kenany** [comment]
Yup, this is intentional. See <https://github.com/npm/npm/search?q=isntall&type=Issues> for history.
