### ISSUE TITLE
Fails after running robocopy

### ISSUE THREAD

**Issue by Ratikant01** [npm/npm#20927]
`robocopy ../source/ destination/ /e` command passes; i.e. it copies all the directories & files when I ran it in command prompt (windows 10 x64).

Now when I configure this as npm task

`"copy" : "robocopy ../source/ destination/ /e"`

and run `npm run copy` it fails! Any idea why and if I am doing something wrong?

Error:
`13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)`

**Comment by legodude17** [comment]
What exit code does robocopy return?

**Comment by Ratikant01** [comment]
Exit code 1

**Comment by legodude17** [comment]
That's why npm is erroring, because by default it will give an error if a script returns an exit code of 1. If you don't want that, try adding `& exit 0` to the end of your script. At least, I think that'll work.
