### ISSUE TITLE
Tarball data seems to be corrupted. Trying one more time

### ISSUE THREAD

**Issue by devlargs** [npm/npm#20925]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [*] npm is doing something I don't understand.
  - [*] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I've been debugging this for almost a week and I havent really solved it. Can someone  help mo on this one. I already uninstalled and reinstalled my node and it always comes up.

Also tried 
`
npm cache clean --force
`
`
rm -rf ~/.npm
`
But this doesnt solve the problem either.

![image](https://user-images.githubusercontent.com/30046754/41130258-6dd1e020-6ae8-11e8-961f-57a24eb8e86c.png)
Note: this doesnt only apply to the above stated plugin. I applies to some plugins as well.

#### How can the CLI team reproduce the problem?
N/A

### supporting information:

 - `npm -v` prints: 6.1.0
 - `node -v` prints: v8.11.2
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux

**Comment by legodude17** [comment]
Does the install actually fail?

**Comment by praveenp-od** [comment]
Same issues

**Comment by sandropoluan** [comment]
Same issue here

**Comment by walshie4** [comment]
@legodude17 The install does not fail (sometimes it later will for a different verification error, write after end, etc), but it does make the install take extremely long.  Been seeing this for weeks now often times with builds taking over _an hour_ on the `npm install` step.

**Comment by JonCognioDigital** [comment]
Same here

**Comment by legodude17** [comment]
If you have this issue, do you have a proxy or VPN?

**Comment by devlargs** [comment]
@legodude17 looks like this one is a proxy error.

**Comment by devlargs** [comment]
I've just reset the proxy in my terminal and it fixed the issue. 

You may refer to this one 
https://askubuntu.com/questions/222938/how-do-i-reset-proxy-in-terminal-to-automatic-if-not-connected-via-proxy

Can install packages fine now.

![image](https://user-images.githubusercontent.com/30046754/41636185-82443102-747f-11e8-84b7-2b9947a49014.png)
