### ISSUE TITLE
error /apps/opt/app/learninglocker/node_modules/bcrypt: Command failed.

### ISSUE THREAD

**Issue by kadapa12** [npm/npm#20932]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] npm is producing incorrect or undesirable behavior.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?
I am trying to install LearningLocker application and its failing with below error

error /apps/opt/app/learninglocker/node_modules/bcrypt: Command failed.
### supporting information:

 - `npm -v` prints:
6.1.0
 - `node -v` prints:
v10.4.0
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?: RHEL 7
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
This seems to be an issue with bcrypt, not npm.

**Comment by kenany** [comment]
Closing since the one error line provided implies that this isn't an issue with `npm` itself.
