### ISSUE TITLE
Cannot add dist-tags for private package

### ISSUE THREAD

**Issue by rubenstolk** [npm/npm#20944]
#### I'm opening this issue because:

  - [x] npm is producing incorrect or undesirable behavior.

#### What's going wrong?

Adding a dist tag for a private package fails, apparently because of an escaped `/`.

#### How can the CLI team reproduce the problem?

```
$ npm dist-tag add @orgname/package-name@2.0.0 production
$ npm ERR! code E404
$ npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/-/package/@orgname%2fpackage-name/dist-tags
```

### supporting information:

- Tried different `npm` versions (5.x and 6.x) incl. the latest, same problem, seems to be a server issue.

**Comment by benjamincharity** [comment]
I began seeing this today on a public package also. It seems that is has something to do with how the URL is parsed.

NPM logs show this line:

```
verbose stack Error: Registry returned 404 for GET on https://registry.npmjs.org/-/package/@terminus%2fngx-tools/dist-tags
```

Encoding `/` into `%2f` causes the URL to be not found while the un-encoded slash-url works:

```
Bad  URL: https://registry.npmjs.org/-/package/@terminus%2fngx-tools/dist-tags
Good URL: https://registry.npmjs.org/-/package/@terminus/ngx-tools/dist-tags
```

---

OS X: 10.13.4
NPM 6.1.0

---

Edit: Downgrading to 6.0.1 did **not** help.

**Comment by benjamincharity** [comment]
Is there any other method of tagging a release? We are currently unable to update the stable version of our library..

**Comment by rubenstolk** [comment]
Glad someone is facing this issue as well... we are also unable to do any deployments since Friday's outtage... really annoying.

**Comment by rubenstolk** [comment]
HELP!

**Comment by rubenstolk** [comment]
I think this has been resolved now. @benjamincharity you still facing trouble?

**Comment by benjamincharity** [comment]
Not at this moment. Fingers crossed it stays true!
