### ISSUE TITLE
Installing from a tarball messes up the package's contents

### ISSUE THREAD

**Issue by Maximaximum** [npm/npm#20940]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### How can the CLI team reproduce the problem?

When I run `npm i http://MYSERVER.SMTH/Models.tgz`, the package gets installed, but its contents are completely messed up.

The original tarball contains such files:
- `/models/*.ts` <- lots of typescript files in the models/ subfolder
- `package.json`
- `server-enums.ts`
- `server-models.ts`

However, when I install it, the contents of the folder are as follows:
- `package.json`
- all the `/models/*.ts` files moved to the root folder of the package
- the `server-enums.ts` and `server-models.ts` are completely missing

### supporting information:

 - `npm -v` prints: 6.1.0
 - `node -v` prints: v8.9.4
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows 8.1
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by Maximaximum** [comment]
Ok, I've narrowed this down. This has nothing to do with a url. If I install it via `npm i --save C:\myfolder\Models.tar`, the issue still persists

**Comment by legodude17** [comment]
AFAIK this is because npm expects tarballs you install to have all of the contents in the `package` folder in the tarball.

**Comment by Maximaximum** [comment]
@legodude17 yeah, indeed! I tried to move the contents to `package` folder - and voila! Everything works as expected, thanks.

But why on Earth couldn't I find any information about that in the npm documentation? :(

**Comment by legodude17** [comment]
I don't know. 🤷‍♂️ Maybe put something in https://npm.community/c/ideas about adding some docs for that?

**Comment by Maximaximum** [comment]
Created an issue, thank you https://npm.community/t/add-explicit-information-about-package-tarball-directory-structure-to-docs/232

**Comment by jacobq** [comment]
@Maximaximum seems like this issue can be closed in favor of the docs one you opened, right?

**Comment by Maximaximum** [comment]
@jacobq I guess yes, though the updated documentation has not been released and deployed to the site yet

**Comment by jacobq** [comment]
Right, but it looks like that's being tracked separately. Just trying to help tidy-up (having 2k open issues is a lot, in my opinion, so I figure we can help by closing those that are no longer actionable / relevant when we come across them).
