### ISSUE TITLE
Refusing to install gulp as a dependency of itself

### ISSUE THREAD

**Issue by MohdRafiUddin** [npm/npm#20964]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   'gulp',
1 verbose cli   '--save-dev' ]
2 info using npm@3.5.2
3 info using node@v8.10.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData gulp
8 silly fetchNamedPackageData gulp
9 silly mapToRegistry name gulp
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/gulp
13 verbose request uri https://registry.npmjs.org/gulp
14 verbose request no auth needed
15 info attempt registry request try #1 at 1:43:11 PM
16 verbose request id 725185f1760098d7
17 verbose etag W/"9a9263eb127e3e96d83591f23f8848fa"
18 verbose lastModified Sat, 26 May 2018 11:14:31 GMT
19 http request GET https://registry.npmjs.org/gulp
20 http 304 https://registry.npmjs.org/gulp
21 verbose headers { date: 'Tue, 12 Jun 2018 08:13:12 GMT',
21 verbose headers   connection: 'keep-alive',
21 verbose headers   'set-cookie':
21 verbose headers    [ '__cfduid=d5862c3968e6970d5e3a7d9287a98fa7d1528791192; expires=Wed, 12-Jun-19 08:13:12 GMT; path=/; domain=.registry.npmjs.org; HttpOnly' ],
21 verbose headers   'cache-control': 'max-age=300',
21 verbose headers   'cf-cache-status': 'HIT',
21 verbose headers   'cf-ray': '429adb569cdb8a7f-BOM',
21 verbose headers   etag: '"9a9263eb127e3e96d83591f23f8848fa"',
21 verbose headers   'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
21 verbose headers   'last-modified': 'Sat, 26 May 2018 11:14:31 GMT',
21 verbose headers   vary: 'accept-encoding, accept',
21 verbose headers   server: 'cloudflare' }
22 silly get cb [ 304,
22 silly get   { date: 'Tue, 12 Jun 2018 08:13:12 GMT',
22 silly get     connection: 'keep-alive',
22 silly get     'set-cookie':
22 silly get      [ '__cfduid=d5862c3968e6970d5e3a7d9287a98fa7d1528791192; expires=Wed, 12-Jun-19 08:13:12 GMT; path=/; domain=.registry.npmjs.org; HttpOnly' ],
22 silly get     'cache-control': 'max-age=300',
22 silly get     'cf-cache-status': 'HIT',
22 silly get     'cf-ray': '429adb569cdb8a7f-BOM',
22 silly get     etag: '"9a9263eb127e3e96d83591f23f8848fa"',
22 silly get     'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
22 silly get     'last-modified': 'Sat, 26 May 2018 11:14:31 GMT',
22 silly get     vary: 'accept-encoding, accept',
22 silly get     server: 'cloudflare' } ]
23 verbose etag https://registry.npmjs.org/gulp from cache
24 verbose get saving gulp to /home/mohdrafi/.npm/registry.npmjs.org/gulp/.cache.json
25 silly install normalizeTree
26 silly loadCurrentTree Finishing
27 silly loadIdealTree Starting
28 silly install loadIdealTree
29 silly cloneCurrentTree Starting
30 silly install cloneCurrentTreeToIdealTree
31 silly cloneCurrentTree Finishing
32 silly loadShrinkwrap Starting
33 silly install loadShrinkwrap
34 silly loadShrinkwrap Finishing
35 silly loadAllDepsIntoIdealTree Starting
36 silly install loadAllDepsIntoIdealTree
37 silly rollbackFailedOptional Starting
38 silly rollbackFailedOptional Finishing
39 silly runTopLevelLifecycles Starting
40 silly runTopLevelLifecycles Finishing
41 silly install printInstalled
42 verbose stack Error: Refusing to install gulp as a dependency of itself
42 verbose stack     at checkSelf (/usr/share/npm/lib/install/validate-args.js:40:14)
42 verbose stack     at Array.<anonymous> (/usr/share/npm/node_modules/slide/lib/bind-actor.js:15:8)
42 verbose stack     at LOOP (/usr/share/npm/node_modules/slide/lib/chain.js:15:14)
42 verbose stack     at chain (/usr/share/npm/node_modules/slide/lib/chain.js:20:5)
42 verbose stack     at /usr/share/npm/lib/install/validate-args.js:15:5
42 verbose stack     at /usr/share/npm/node_modules/slide/lib/async-map.js:52:35
42 verbose stack     at Array.forEach (<anonymous>)
42 verbose stack     at /usr/share/npm/node_modules/slide/lib/async-map.js:52:11
42 verbose stack     at Array.forEach (<anonymous>)
42 verbose stack     at asyncMap (/usr/share/npm/node_modules/slide/lib/async-map.js:51:8)
43 verbose cwd /home/mohdrafi/Desktop/sample
44 error Linux 4.15.0-22-generic
45 error argv "/usr/bin/node" "/usr/bin/npm" "install" "gulp" "--save-dev"
46 error node v8.10.0
47 error npm  v3.5.2
48 error code ENOSELF
49 error Refusing to install gulp as a dependency of itself
50 error If you need help, you may report this error at:
50 error     <https://github.com/npm/npm/issues>
51 verbose exit [ 1, true ]

**Comment by kenany** [comment]
Ensure that the `"name"` field in your `package.json` is not set to `"gulp"`. Try setting it to something more unique :)
