### ISSUE TITLE
FAQ: How can I get the owner of an empty scope

### ISSUE THREAD

**Issue by Gcaufy** [npm/npm#20963]
#### I'm opening this issue because:

  - [x] Other (_see below for feature requests_):

#### What's going wrong?

There is an empty scope in https://www.npmjs.com/org/wepy
Is there any commands like `npm own ls sth` to know who created this scope?

I have send two emails to `support@npmjs.com`, but get no responses.

**Comment by alsotang** [comment]
And @Gcaufy create a popular framework named `wepy`, https://github.com/Tencent/wepy

**Comment by Gcaufy** [comment]
FYI: https://www.npmjs.com/policies/disputes
