### ISSUE TITLE
git clone git@github.com:github:amcharts/amcharts3-angular2 Cloning into bare repository '/home/distelli/.npm/_git-remotes/git-github-com-github-amcharts-amcharts3-angular2-c579622c'...

### ISSUE THREAD

**Issue by kumaraguruj** [npm/npm#20976]
#### I'm opening this issue because:

  - [ ] npm is doing something I don't understand.

**Comment by kenany** [comment]
Closing since the issue body is essentially blank, so there is nothing actionable here.
