### ISSUE TITLE
While migrating from grunt to gulp, npm install is giving error

### ISSUE THREAD

**Issue by AKrishma** [npm/npm#20982]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Following error is appearing
---------------------------------------------------------
 npm install
npm WARN deprecated uws@9.14.0: stop using this version
npm WARN deprecated gulp-util@2.2.20: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @nodelib/fs.stat@^1.0.1 (node_modules/fast-glob/node_modules/@nodelib/fs.stat):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: This request requires auth credentials. Run `npm login` and repeat the request.
npm ERR! Darwin 17.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.12.0
npm ERR! npm  v3.10.10

 npm ERR! This request requires auth credentials. Run `npm login` and repeat the request.

---------------------------------------------------------
Installed npm install -g gulp@4.0.0, before this. But after error mentioned above, its not displaying uninstalling gulp.

#### How can the CLI team reproduce the problem?

npm-debug.log file attached. [npm-debug.log](https://github.com/npm/npm/files/2100916/npm-debug.log)

### supporting information:

 - `npm -v` prints: _npm  v3.10.10_
 - `node -v` prints: _node v6.12.0_
 - `npm config get registry` prints: _https://d2platformnexus.unileversolutions.com/repository/npm-all/_
 - Windows, OS X/macOS, or Linux?: _OS X/macOS_
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
Does this occur on the latest version of npm?

**Comment by AKrishma** [comment]
After upgrading to latest version of npm@6.1.0. this issue get resolved.
