### ISSUE TITLE
`npm update --dev` do not update devDependencies

### ISSUE THREAD

**Issue by pravdomil** [npm/npm#21000]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

`@pravdomil/blocks` is at `0.0.1` latest is `0.0.3`

`npm up --dev` should update to latest, but it still remain at `0.0.1`

```sh
$ npm outdated -l
Package                  Current         Wanted  Latest  Location  Package Type
@pravdomil/blocks          0.0.1          0.0.1   0.0.3            devDependencies
$ npm up --dev
$ npm outdated -l
Package                  Current         Wanted  Latest  Location  Package Type
@pravdomil/blocks          0.0.1          0.0.1   0.0.3            devDependencies
```

#### How can the CLI team reproduce the problem?

```sh
mkdir test
cd test
npm init -y
npm i @pravdomil/blocks@0.0.1 -D
# set package.json -> devDependencies -> @pravdomil/blocks to ^0.0.1
read
npm outdated -l
npm up --dev # this should update @pravdomil/blocks to latest
npm outdated -l
```

### supporting information:

 - `npm -v` prints: 6.1.0
 - `node -v` prints: 10.1.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by rneha725** [comment]
hey @pravdomil can you try the following command
`npm view @pravdomil/blocks version`

**Comment by pravdomil** [comment]
`npm view @pravdomil/blocks version` is `1.0.2`

**Comment by rneha725** [comment]
I found the same closed issue. Please go through the documentation of npm outdated in the following issue comments:
[https://github.com/npm/npm/issues/12089](https://github.com/npm/npm/issues/12089)

**Comment by pravdomil** [comment]
this issue is not on how `npm outdated` works but how `npm update` works, therefore there is no solution for my issue

**Comment by welwood08** [comment]
This is most likely expected behaviour. As you can see from the `outdated` output, the `Wanted` version is `0.0.1` and not `0.0.3`. The version range specified in your package.json is probably listed as `^0.0.1`, and according to [the documentation about semver ranges](https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004) that is equivalent to `>=0.0.1 <0.0.2`.

If you want to update a package past the `Wanted` version, you have to update your package.json with the new desired range or install the specific version yourself.

**Comment by pravdomil** [comment]
@welwood08 great, thanks for explanation and link to the docs, is there any other options then manual edit of `package.json` I think `npm i @pravdomil/blocks@latest` would work as well
