### ISSUE TITLE
npm ERR! Error: No compatible version found: require-inject@'^1.4.3'

### ISSUE THREAD

**Issue by leixin525** [npm/npm#21013]
#### I'm opening this issue because:

npm install -d

#### What's going wrong?

npm ERR! Error: No compatible version found: require-inject@'^1.4.3'
npm ERR! Valid install targets:
npm ERR! ["1.0.0","1.0.1","1.0.2","1.1.0","1.1.1","1.2.0","1.2.1","1.3.0","1.3.1","1.4.0","1.4.1","1.4.2","1.4.3"]
npm ERR!     at installTargetsError (C:\Program Files (x86)\nodejs\node_modules\npm\lib\cache.js:553:10)
npm ERR!     at C:\Program Files (x86)\nodejs\node_modules\npm\lib\cache.js:477:15
npm ERR!     at saved (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\get.js:138:7)
npm ERR!     at C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:222:7
npm ERR!     at Object.oncomplete (fs.js:297:15)
npm ERR!     at process.startup.processMakeCallback.process._makeCallback (node.js:238:20)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-d"
npm ERR! cwd c:\npm
npm ERR! node -v v0.9.0
npm ERR! npm -v 1.1.44

**Comment by legodude17** [comment]
Your versions of npm and node are years old and no longer supported. Please update.

**Comment by kenany** [comment]
Closing because we don't support those versions.
