### ISSUE TITLE
i am using node version 6.2.2 and i  used npm install  i am getting some winston error 

### ISSUE THREAD

**Issue by muthyalaDivyaVenkatesh** [npm/npm#21012]
#### I'm opening this issue because:

  
  - [x] npm is producing an incorrect install.

#### What's going wrong?
/home/mdvenkatesh/blockchainpoc/hlpoc/scripts/install_chaincode.js:3
var logger = new (winston.Logger)({
             ^

TypeError: winston.Logger is not a constructor
    at Object.<anonymous> (/home/mdvenkatesh/blockchainpoc/hlpoc/scripts/install_chaincode.js:3:14)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (node.js:348:7)
    at startup (node.js:140:9)
    at node.js:463:3

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

plese help me
npm -v prints:  3.9.5
node -v prints :6.2.2

**Comment by kenany** [comment]
Seems like this error is not coming from `npm`, so I'm gonna close this issue. You may wanna take a look at <https://github.com/winstonjs/winston#creating-your-own-logger>.
