### ISSUE TITLE
integrity hash not being produced/being removed from specific package in package-lock on install

### ISSUE THREAD

**Issue by jennifer-shehane** [npm/npm#21015]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

On `npm install`, the integrity hash of one of my packages in my package-lock.json file is being deleted. I do see that the integrity hashes of my initial file are `sha-1` based, and the other packages are updating to `sha-512`, but one package has the integrity hash just completely removed so that my git diff looks like this:

```diff
...etc
    "@cypress/xvfb": {
      "version": "1.2.3",
      "resolved": "https://registry.npmjs.org/@cypress/xvfb/-/xvfb-1.2.3.tgz",
-     "integrity": "sha1-Yxmv3Nz/fRUF2u6qhEhNBZYYmGA=",
+     "integrity": "sha512-yYrK+/bgL3hwoRHMZG4r5fyLniCy1pXex5fimtewAY6vE/jsVs8Q37UsEO03tFlcmiLnQ3rBNMaZBYTi/+C1cw==",
      "dev": true,
      "requires": {
        "debug": "3.1.0",
...etc
    "react-bootstrap-modal": {
      "version": "git://github.com/cypress-io/react-bootstrap-modal.git#cd09b146e38a542d156dd411c8aecafb56230a1b",
-     "integrity": "sha1-wB88rTi9X08Uy+Tbym53Bj2HcvA=",
      "dev": true,
      "requires": {
        "classnames": "2.2.5",
...etc
```

This package happens to be the only package in my `package.json` file that points to a commit:

```json
{
  "devDependencies": {
    "react-bootstrap-modal": "cypress-io/react-bootstrap-modal#cd09b146e38a542d156dd411c8aecafb56230a1b"
  }
}
```

When I later try to build my project in CI by running `npm ci`, my module is obviously not found later in my code:

```
Error: Cannot find module 'react-bootstrap-modal'
```

#### How can the CLI team reproduce the problem?

I created a new project and added the package as a dependency and it seems to never add an `integrity` hash to begin with. It is my understanding that every package in the `package-lock.json` requires an `integrity` key. Am I wrong?

- create a project and `npm init -y`
- Add `"react-bootstrap-modal": "cypress-io/react-bootstrap-modal#cd09b146e38a542d156dd411c8aecafb56230a1b"` in `devDependencies`
- Run `npm i`

### supporting information:

 - `npm -v` prints: 5.6.0
 - `node -v` prints: v8.11.3
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: OS X

**Comment by zkat** [comment]
Git dependencies do not use integrity hashes in recent versions of npm. Very early versions of `npm@5` did.

As far as `@cypress/xvfb` goes, that seems to be the correct `sha512` integrity hash for that version. There were some bugs earlier on with getting `sha1` hashes incorrectly, but it seems to have fixed itself.

Overall, you're pretty much good to go here and I don't see any problems. Everything's working as expected. 👍

**Comment by zkat** [comment]
Err, sorry, I missed the part where `react-boostrap-modal` isn't working.

I think that might be a separate bug in `npm ci` itself (possibly https://npm.community/t/npm-ci-creates-an-invalid-install-with-optionaldependencies-from-git/242?)

So I'm gonna keep this closed since the main question (the integrity thing) isn't a problem, and there's some known issues with `npm ci`. I'd recommend, just in case, that you upgrade to the latest npm (`npm install -g npm@latest`) and see if you're still getting that error with `npm ci` -- and otherwise, use `npm install` itself to do your install until this issue is fixed in `ci`.

**Comment by jennifer-shehane** [comment]
Yeah, I just tried to `npm install -g npm@latest`, but am remembering that on the latest version I had another error - where the `./bin` location was not being found and installed to on install. This was why I had previously rolled back to v5.6.0 because I could not run package commands otherwise. 😬 

Thanks for the help though. I at least know that having the integrity hash not present on git dependencies is the expected behavior.
