### ISSUE TITLE
"ERR! cb() never called!" with npm 6.1.0/win-64bits

### ISSUE THREAD

**Issue by sfcrebecca** [npm/npm#21025]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [* ] npm is doing something I don't understand.
  - [ ] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
"ERR! cb() never called!" when I execute "npm install"

#### How can the CLI team reproduce the problem?

https://gist.github.com/sfcrebecca/823075697160a56b881e95f4b4aaa183

### supporting information:

 - `npm -v` prints: 6.1.0
 - `node -v` prints: v10.4.0
 - `npm config get registry` prints:  https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows 10 (64-bits)
 - Network issues:
   - Geographic location where npm was run:
   - [*] I use a proxy to connect to the npm registry.
   - [*] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container: HyperV/Nutanix
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by chaitanya1248** [comment]
Same issue with npm 6.1.0, macOS Sierra 10.12.6

**Comment by chaitanya1248** [comment]
`npm clean cache --force` helped.

**Comment by elron** [comment]
I received the same error and figured it was because I had no more space in the disk.
solution: remove space :)

**Comment by sfcrebecca** [comment]
Thanks all. After some more intensive research, I come across this post which solves my problem. 

`npm install --no-package-lock`

[https://github.com/npm/npm/issues/19353](url)
