### ISSUE TITLE
npm ionic not installing

### ISSUE THREAD

**Issue by IMSBuSu** [npm/npm#21021]
npm install -g ionic
npm ERR! Error: Method Not Allowed
npm ERR!     at errorResponse (/usr/share/npm/lib/cache/add-named.js:260:10)
npm ERR!     at /usr/share/npm/lib/cache/add-named.js:120:12
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:167:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:135:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.16.0-1-amd64
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "-g" "ionic"
npm ERR! cwd /home/live
npm ERR! node -v v8.11.2
npm ERR! npm -v 1.4.21
npm ERR! code E405
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/live/npm-debug.log
npm ERR! not ok code 0
[npm-debug.log](https://github.com/npm/npm/files/2117469/npm-debug.log)

**Comment by legodude17** [comment]
Your version of npm is years old and no longer supported. Please update.

**Comment by IMSBuSu** [comment]
you are amazing, thank you so much my problem resolved after update NPM.
thanks again.
