### ISSUE TITLE
npm documentation shows last modified date as 1985

### ISSUE THREAD

**Issue by Fleker** [npm/npm#21032]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] npm is producing incorrect or undesirable behavior.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?

If you look at several pages in the npm documentation, they state the last modified date is October 26 1985. I don't think that's correct.

Two examples:
* [npm ci](https://docs.npmjs.com/cli/ci)
* [npm install](https://docs.npmjs.com/cli/install)

This appears to be part of the CMS hosting the pages.

**Comment by kenany** [comment]
Previous discussions: https://github.com/npm/npm/issues/20439, https://github.com/npm/docs/issues/990, and https://github.com/npm/docs/issues/1013.
