### ISSUE TITLE
npm unpublish idea

### ISSUE THREAD

**Issue by adrianpraja** [npm/npm#21051]
Hi NPM team,

Would it be an option that `npm unpublish` command for packages published > 24h 
to keep the package available for future `npm install`s but remove it from the search index
so it doesn't get new hits ?

later on if such an unpublished package has less than N installs in the last M months 
to be completely removed from the registry  

Thanks

**Comment by admin7770** [comment]
Hatte eigentlich vor gehabt nur node.js zu installieren und dann der
Zusammenhang anderer Dienste npm npm und so weiter wie Geschwister
Programme im sorry

Adrian Praja <notifications@github.com> schrieb am Fr., 22. Juni 2018,
16:49:

**Comment by kenany** [comment]
You should propose this to the registry team themselves :) <https://github.com/npm/registry>
