### ISSUE TITLE
unable to update

### ISSUE THREAD

**Issue by Raffa87** [npm/npm#21053]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] npm is producing incorrect or undesirable behavior.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?
When I try `sudo npm install -g npm@latest` on a Centos
I get:

> npm http GET https://registry.npmjs.org/npm
> npm http GET https://registry.npmjs.org/npm
> npm http GET https://registry.npmjs.org/npm
> npm ERR! Error: CERT_UNTRUSTED
> npm ERR!     at SecurePair.<anonymous> (tls.js:1381:32)
> npm ERR!     at SecurePair.emit (events.js:92:17)
> npm ERR!     at SecurePair.maybeInitFinished (tls.js:980:10)
> npm ERR!     at CleartextStream.read [as _read] (tls.js:472:13)
> npm ERR!     at CleartextStream.Readable.read (_stream_readable.js:341:10)
> npm ERR!     at EncryptedStream.write [as _write] (tls.js:369:25)
> npm ERR!     at doWrite (_stream_writable.js:226:10)
> npm ERR!     at writeOrBuffer (_stream_writable.js:216:5)
> npm ERR!     at EncryptedStream.Writable.write (_stream_writable.js:183:11)
> npm ERR!     at write (_stream_readable.js:602:24)
> npm ERR! If you need help, you may report this log at:
> npm ERR!     <http://github.com/isaacs/npm/issues>
> npm ERR! or email it to:
> npm ERR!     <npm-@googlegroups.com>
> 
> npm ERR! System Linux 2.6.32-573.26.1.el6.x86_64
> npm ERR! command "node" "/usr/bin/npm" "install" "-g" "npm@latest"
> npm ERR! cwd /home/centos
> npm ERR! node -v v0.10.46
> npm ERR! npm -v 1.3.6
> npm ERR! 
> npm ERR! Additional logging details can be found in:
> npm ERR!     /home/centos/npm-debug.log
> npm ERR! not ok code 0

**Comment by legodude17** [comment]
Your versions of node and npm are years old and no longer supported. Please update.

**Comment by Raffa87** [comment]
Thank you very much for your fast reply!
How can I update it?  I am trying to do `sudo npm install -g npm@latest` in order to update it, as mentioned here:
[https://docs.npmjs.com/troubleshooting/try-the-latest-stable-version-of-npm](https://docs.npmjs.com/troubleshooting/try-the-latest-stable-version-of-npm)

**Comment by kenany** [comment]
I would suggest downloading a newer version of Node.js from <https://nodejs.org/>, since it also bundles newer versions of `npm`.
