### ISSUE TITLE
NPM not catching SemVer security issue

### ISSUE THREAD

**Issue by peterennis** [npm/npm#21061]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] npm is producing incorrect or undesirable behavior.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?
Not catching semver security error that is
reported on GitHub.

#### How can the CLI team reproduce the problem?

https://github.com/peterennis/ae-logo-component

![capture322](https://user-images.githubusercontent.com/140737/41814798-54c91cde-770d-11e8-9fff-aac80e85390a.png)

### supporting information:

 - `npm -v` prints:
```
6.1.0
```
 - `node -v` prints:
```
v8.11.1
```
 - `npm config get registry` prints:
```
https://registry.npmjs.org/
```
 - Windows, OS X/macOS, or Linux?: Windows
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
I think this issue belongs in <https://github.com/npm/registry>, since it is the security API which handles this, not the `npm` CLI itself.

**Comment by peterennis** [comment]
@KenanY - OK. Do you move the issue or the label is sufficient?

**Comment by kenany** [comment]
I think you should open a new issue at <https://github.com/npm/registry> yourself.

**Comment by peterennis** [comment]
@KenanY Done: https://github.com/npm/registry/issues/364

**Comment by peterennis** [comment]
Using `npm audit fix` resolves this for the latest code.
