### ISSUE TITLE
can not install store/configure package

### ISSUE THREAD

**Issue by mrtplnkr** [npm/npm#21098]
[npm-debug.log](https://github.com/npm/npm/files/2144930/npm-debug.log)
#### I'm opening this issue because:

  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
#### What's going wrong?
just trying to run "npm install -save store/configure"
#### How can the CLI team reproduce the problem?
npm install -save store/configure

 - I use Windows
 - Container:
   - [ ] I develop using php Laravel backend and React Redux front end

I can install all the other packages, why not this store/configure ? I don't understand..

**Comment by DanielRuf** [comment]
Any stacktrace?

**Comment by mrtplnkr** [comment]
sorry I didn't realise 'store/configure' is not a package, is a file that includes the setup of the store...
