### ISSUE TITLE
Unable to run any js file

### ISSUE THREAD

**Issue by sonaljain0321** [npm/npm#21093]
I installed node js.
The installation seems to be fine as I am getting the versions for both node and npm using the following commands:
node -v
npm -v

I created a simple node js file with a console log in it and when tried to run it on cmd like "node example.js", it gives me the below error:

module.js:549
    throw err;
    ^

Error: Cannot find module 'C:\SONAL\extras\node_js\example.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

I have seen earlier posts where people have got similar issues but I could not find a proper solution for the same. Please help!

**Comment by kenany** [comment]
Does `C:\SONAL\extras\node_js\example.js` exist?

**Comment by sonaljain0321** [comment]
Yes... It does...

**Comment by kenany** [comment]
Please reopen this issue at <https://github.com/nodejs/help>, since your issue is with Node.js, not `npm`.
