### ISSUE TITLE
NPM Is Down and Causing Issues

### ISSUE THREAD

**Issue by skellman** [npm/npm#21103]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
#!/bin/bash -eo pipefail
export $(cat workspace/versions.env | xargs)
export PATH=/opt/Sencha/Cmd:$PATH
cd folder_name
npm install --no-optional
sencha app build application_nameproduction
Too long with no output (exceeded 10m0s)

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by paladox** [comment]
see also https://github.com/npm/npm/issues/21101

**Comment by hashar** [comment]
You should try `npm install` with the `--verbose` option. That will give way more informations.

**Comment by zkat** [comment]
This repository is for the npm CLI, so I'm closing this. Please post in https://npm.community/c/support if you want something to track, and keep an eye on https://status.npmjs.org in the meantime. Cheers!
