### ISSUE TITLE
NPM fails with error 500

### ISSUE THREAD

**Issue by pkail** [npm/npm#21102]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by pkail** [comment]
Windows 10 64-bit

$ npm config get registry
https://registry.npmjs.com/

install node-gyp -g
npm ERR! fetch failed https://registry.npmjs.org/node-gyp/-/node-gyp-3.7.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 500
npm ERR! fetch failed https://registry.npmjs.org/node-gyp/-/node-gyp-3.7.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 500
npm ERR! fetch failed https://registry.npmjs.org/node-gyp/-/node-gyp-3.7.0.tgz
npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "inst
all" "node-gyp" "-g"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10

npm ERR! fetch failed with status code 500
npm ERR!

Error when I paste the URL into a browser:
Fastly error: unknown domain. Please check that this domain has been added to a service. 

Since Fastly is the CDN and I am getting server error 500, I assume that the problem is with npm's CDN, Fastly.

**Comment by twiggy** [comment]
we are seeing this as well, but since we are using an older version of npm ( our bad ) we are getting JSON parsing errors like in https://github.com/npm/npm/issues/8536

we tried to use Cloudfare for a while, but its either do it their way or the highway. you should really just use Signal Sciences which is a much better WAF although not a DDOS solution...use AWS Shield or something for that. Use cloudfare, have a bad time.

we are probably going to start looking at sinopia

**Comment by pkail** [comment]
Do you mean that the issue might be my firewall?

**Comment by hashar** [comment]
You should try `npm install` with the `--verbose` option. That will give way more informations.

See also #21101

**Comment by pkail** [comment]
I have switched off the firewall, but it makes no difference.
In verbose mode I get a lot of information about the headers, etc., but the error is the same.  Here are the key lines again:

npm verb addRemoteTarball https://registry.npmjs.org/node-gyp/-/node-gyp-3.7.0.tgz not in flight; adding
npm verb addRemoteTarball [ 'https://registry.npmjs.org/node-gyp/-/node-gyp-3.7.0.tgz',
npm verb addRemoteTarball   '789478e8f6c45e277aa014f3e28f958f286f9203' ]
npm info retry fetch attempt 1 at 9:25:53 AM
npm info attempt registry request try #1 at 9:25:53 AM
npm http fetch GET https://registry.npmjs.org/node-gyp/-/node-gyp-3.7.0.tgz
npm http fetch 500 https://registry.npmjs.org/node-gyp/-/node-gyp-3.7.0.tgz
npm info retry will retry, error on last attempt: Error: server error 500

**Comment by hashar** [comment]
`error 500` is just the generic code for... an error :] In verbose mode above or below that message, there should be the body response from the server that would have the actual information.

**Comment by pkail** [comment]
But there isn't, unfortunately.

**Comment by zkat** [comment]
This repository is for the npm CLI, so I'm closing this. Please post in https://npm.community/c/support if you want something to track, and keep an eye on https://status.npmjs.org in the meantime. Cheers!
