### ISSUE TITLE
CloudFlare sometime yield a 503 after 10 minutes while requesting https://registry.npmjs.org/xxx 

### ISSUE THREAD

**Issue by hashar** [npm/npm#21101]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] npm is producing incorrect or undesirable behavior.
  - [X] Other (most probably a CloudFlare issue):

#### What's going wrong?

Since yesterday, `npm install` some time freeze for 10 minutes while attempting to retrieve a package information (example: https://registry.npmjs.org/component-bind ). The connection to the CloudFlare CDN is established, but no data is transmitted for 10 minutes when eventually CloudFlare reply with a 503 and an HTML page stating `Temporarily unavailable`.

With timestamps relative to start of build:
```
00:01:36.025 npm verb afterAdd /cache/npm/to-array/0.1.4/package/package.json written
<freeze, tcp connection is established though>
00:11:45.014 npm http 503 https://registry.npmjs.org/component-bind
00:11:45.014 npm verb bad json <!DOCTYPE html>
00:11:45.015 npm verb bad json <!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
00:11:45.015 npm verb bad json <!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
00:11:45.015 npm verb bad json <!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
00:11:45.016 npm verb bad json <!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
00:11:45.016 npm verb bad json <head>
00:11:45.016 npm verb bad json <title>Temporarily unavailable | registry.npmjs.org | Cloudflare</title></title>
...
00:11:45.026 npm verb bad json             <p>You've requested a page on a website (registry.npmjs.org) that is on the <a data-orig-proto="https" data-orig-ref="www.cloudflare.com/5xx-error-landing?utm_source=error_100x" target="_blank">Cloudflare</a> network. The page could not be rendered due to a temporary fault.</p>
...
00:11:45.029 npm verb bad json     <span class="cf-footer-item">Cloudflare Ray ID: <strong>431eca64f8319fc6</strong></span>
00:11:45.029 npm verb bad json     <span class="cf-footer-separator">&bull;</span>
00:11:45.030 npm verb bad json     <span class="cf-footer-item"><span>Your IP</span>: 208.80.155.255</span>
00:11:45.030 npm verb bad json     <span class="cf-footer-separator">&bull;</span>
00:11:45.030 npm verb bad json     <span class="cf-footer-item"><span>Performance &amp; security by</span> <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=error_footer" id="brand_link" target="_blank">Cloudflare</a></span>
...
00:11:45.033 npm ERR! registry error parsing json
...
00:11:45.033 npm verb headers { date: 'Thu, 28 Jun 2018 08:40:28 GMT',
00:11:45.033 npm verb headers   'content-type': 'text/html; charset=UTF-8',
00:11:45.034 npm verb headers   'content-length': '3291',
00:11:45.034 npm verb headers   connection: 'keep-alive',
00:11:45.034 npm verb headers   'set-cookie': [ '__cfduid=d6e61ae1e4d173c478b8a965aedcfb5741530174618; expires=Fri, 28-Jun-19 08:30:18 GMT; path=/; domain=.registry.npmjs.org; HttpOnly' ],
00:11:45.035 npm verb headers   'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
00:11:45.035 npm verb headers   server: 'cloudflare',
00:11:45.035 npm verb headers   'cf-ray': '431eca64f8319fc6-IAD' }
```

The request started at 08:30 UTC, and one can see the set-cookie expires= match that time. The date header shows 8:40UTC which is when the request got actually emitted to the client.

The CloudFlare page states:

> You've requested a page on a website (registry.npmjs.org) that is on the CloudFlare network. The page could not be rendered due to a temporary fault.</
> Cloudflare Ray ID: **431eca64f8319fc6**
> Your IP: 208.80.155.255
> Performance security by CloudFlare

I strongly suspect CloudFlare to be holding the connection. Either because the back end is somehow unresponsive or possibly that is a DDOS / rate limiting protection kicking in.

`retry` kicks in, and the URL is then properly served:
```
00:11:55.032 npm info attempt registry request try #2 at 8:40:38 AM
00:11:55.034 npm verb etag W/"5861bd0e9c408f075f381328c70e835d"
00:11:55.034 npm verb lastModified Sat, 26 May 2018 20:24:17 GMT
00:11:55.034 npm http request GET https://registry.npmjs.org/component-bind
00:11:55.074 npm http 304 https://registry.npmjs.org/component-bind
00:11:55.076 npm verb headers { date: 'Thu, 28 Jun 2018 08:40:38 GMT',
00:11:55.076 npm verb headers   connection: 'close',
00:11:55.076 npm verb headers   'set-cookie': [ '__cfduid=d3267284850ea202cce4774c1211547931530175238; expires=Fri, 28-Jun-19 08:40:38 GMT; path=/; domain=.registry.npmjs.org; HttpOnly' ],
00:11:55.077 npm verb headers   'cache-control': 'max-age=300',
00:11:55.077 npm verb headers   'cf-cache-status': 'HIT',
00:11:55.077 npm verb headers   'cf-ray': '431ed9885f0c9580-IAD',
00:11:55.077 npm verb headers   etag: '"5861bd0e9c408f075f381328c70e835d"',
00:11:55.078 npm verb headers   'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
00:11:55.078 npm verb headers   'last-modified': 'Sat, 26 May 2018 20:24:17 GMT',
00:11:55.078 npm verb headers   vary: 'accept-encoding, accept',
00:11:55.078 npm verb headers   server: 'cloudflare' }
00:11:55.078 npm verb etag https://registry.npmjs.org/component-bind from cache
00:11:55.079 npm verb get saving component-bind to /cache/npm/registry.npmjs.org/component-bind/.cache.json
```

From some debugging I did,  `npm-registry-client` relies on `request` which creates an `http.ClientRequest`. On Nodejs v6.11.0 it does not have any default timeout.  I guess after 10 minutes, CloudFlare aborts the connection with an HTML error page.

#### How can the CLI team reproduce the problem?

I could not find how to reproduce reliably, but that is surely has been happening on a regular basis since June 27th.

Potentially we might be rate limited, but then I would expect a different http error code than just a 503.

### supporting information:

 - `npm -v` prints: usually 3.8.3. Though really that is a network problem on registry.npmjs.org :]
 - `node -v` prints: v6.11.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux
 - Network issues:
   - Geographic location where npm was run: from 208.80.155.255 , Ashburn, VA, USA
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [X] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

Downstream bug https://phabricator.wikimedia.org/T198348

**Comment by th0r** [comment]
Exactly the same issue here but we use Codeship. Here are some interesting lines from the log:
```
http fetch GET 200 https://registry.npmjs.org/mocha/-/mocha-3.5.3.tgz 10760ms attempt #2
http fetch GET 200 https://registry.npmjs.org/lodash._baseassign/-/lodash._baseassign-3.2.0.tgz 620086ms attempt #2
```
Note the fetch time for `lodash._baseassign`: 620086ms which is about 10 minutes.

**Comment by nick13jaremek** [comment]
Indeed, we use NPM build steps on a Codeship pipeline, and the `npm install` commands takes more than 10 minutes, marking the build as failed.

However, running `npm install` locally on my computer does not take that long: it installs at a normal pace (2-3 minutes).

Perhaps it could be related to a subset of Cloudflare/CDN servers? It would be interesting to check in which regions this `npm install` delay takes place. My computer is located in Spain, no idea where the Codeship servers may be placed, though.

**Comment by th0r** [comment]
> However, running npm install locally on my computer does not take that long: it installs at a normal pace (2-3 minutes).

Same.

**Comment by hashar** [comment]
I have filled a support request to CloudFlare (#1543467), though most probably the rate limiting can be acted on by NPM maintainers.

**Comment by bruce-lindsay** [comment]
Same issue here

**Comment by zkat** [comment]
This repository is for the npm CLI, so I'm closing this. Please post in https://npm.community/c/support if you want something to track, and keep an eye on https://status.npmjs.org in the meantime. Cheers!
