### ISSUE TITLE
`npm install` gives `npm ERR! cb() never called!`

### ISSUE THREAD

**Issue by ericop** [npm/npm#21111]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
When I run `npm install` it runs for a while and then I get:
 
```
npm ERR! cb() never called!


[](url)
npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\it-johns7ed\AppData\Roaming\npm-cache\_logs\2018-06-29T13_19_17_968Z-debug.log
```
attached file: [2018-06-29T13_19_17_968Z-debug.log](https://github.com/npm/npm/files/2149512/2018-06-29T13_19_17_968Z-debug.log) 
### supporting information:

 - `npm -v` prints: **6.1.0**
 - `node -v` prints: **v10.5.0**
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: **Windows 10**
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by DanielRuf** [comment]
Duplicate of https://github.com/npm/npm/issues/21095 and it happens due to technical issues on the servers of npm.

Try `npm cache clean --force` and use verdaccio as local cache.

**Comment by JacobJT** [comment]
@DanielRuf I've been running into this issue all day. How safe is it to clean the cache? Is that just going to make some commands take a bit longer until the cache is all rebuilt? It'll stop my computer from trying to access what seems like faulty upstream npm machines?

**Comment by DanielRuf** [comment]
> Is that just going to make some commands take a bit longer until the cache is all rebuilt?

Yes



> It'll stop my computer from trying to access what seems like faulty upstream npm machines?

No, there is just one registry (endpoint) for all users but it will cleanup the cache of broken downloads and try some new ones. I've paired this with verdaccio as it will retry the downloads and fill a local cache so the next `npm i` for a new project with the same lockfile will not fail.

**Comment by ericop** [comment]
@DanielRuf since this is a dup, I'll close this one. Good to know that you can user can use https://www.verdaccio.org/docs/en/installation#installing-the-cli as an alternative source. I myself am using the long term support version 8.11.3 to get around this until it's fixed.
