### ISSUE TITLE
Can someone, once and for all, explain what package-lock.json is for?!

### ISSUE THREAD

**Issue by KerimG** [npm/npm#21122]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [x] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
``npm install`` is not using package-lock.json to create reproducible installations. Instead it installs whatever range was defined in package.json and overwrites package-json.lock.

#### How can the CLI team reproduce the problem?

Run ``npm install`` in a project with an updated dependency. Instead of reproducing the dependency tree described in package-lock.json, npm will install the dependency's newer version and rewrite package-lock.json.

If one has to specify exact versions in package.json as some seem to suggest on reddit/SO/etc, then what is the point of package-lock.json? 

### supporting information:

 - `npm -v` prints: 5.6.0
 - `node -v` prints: v8.11.3
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: All

I am sorry but this whole package-lock.json deal is extremely confusing and handled very badly. The documentation over at https://docs.npmjs.com/files/package-lock.json is frustratingly bad and as far as I can tell outright wrong. 

In some discussions of people trying to make sense of this mess, some claim that for npm to not modify package-lock.json, one must specify the exact version of the dependency in package.json. That, however, would effectively make package.json to my lock file. Then what's the point of package-lock.json?

**Comment by KerimG** [comment]
While browsing further I found out that npm behaves differently in regards to package-lock.json in different 5.x.x versions, possibly introducing breaking changes in a minor update. That's unacceptable.

This really put a dent in my trust for npm and as they say, "Trust, once you get it. It's priceless. But once you lose it, you are useless."

**Comment by DanielRuf** [comment]
Try yarn or pnpm, npm unfortunately does not treat the lockfile as the single source of truth.

**Comment by KerimG** [comment]
Isn't it rather unfortunate that the solution to broken package-lock.json is to not use npm? This really bums me out...

**Comment by kenany** [comment]
> **How can the CLI team reproduce the problem?**
>
> Run `npm install` in a project with an updated dependency.

So, just to clarify, you mean with a project like:

```json
{
  "name": "npm-21122",
  "version": "1.0.0",
  "dependencies": {
    "object-assign": "3"
  }
}
```

```json
{
  "name": "npm-21122",
  "version": "1.0.0",
  "lockfileVersion": 1,
  "requires": true,
  "dependencies": {
    "object-assign": {
      "version": "3.0.0",
      "resolved": "https://registry.npmjs.org/object-assign/-/object-assign-3.0.0.tgz",
      "integrity": "sha1-m+3VygiXlJvKR+f/QIBi1Un1h/I="
    }
  }
}
```

Then applying the following patch:

```diff
diff --git a/package.json b/package.json
index 235e150..43a0951 100644
--- a/package.json
+++ b/package.json
@@ -2,6 +2,6 @@
   "name": "npm-21122",
   "version": "1.0.0",
   "dependencies": {
-    "object-assign": "3"
+    "object-assign": "4"
   }
 }
```

And running `npm install` changes `package-lock.json` in the following way:

```diff
diff --git a/package-lock.json b/package-lock.json
index f286b42..5bf525d 100644
--- a/package-lock.json
+++ b/package-lock.json
@@ -5,9 +5,9 @@
   "requires": true,
   "dependencies": {
     "object-assign": {
-      "version": "3.0.0",
-      "resolved": "https://registry.npmjs.org/object-assign/-/object-assign-3.0.0.tgz",
-      "integrity": "sha1-m+3VygiXlJvKR+f/QIBi1Un1h/I="
+      "version": "4.1.1",
+      "resolved": "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz",
+      "integrity": "sha1-IQmtx5ZYh8/AXLvUQsrIv7s2CGM="
     }
   }
 }
```

Does this accurately describe what you are talking about here? If not, could you provide a set of steps I could follow to see what you're seeing?

**Comment by zkat** [comment]
`npm help package-locks` has a pretty thorough explanation of that file's purpose. It's the answer you'd get from me.
