### ISSUE TITLE
Installing serial-port (Error: Method Not Allowed)

### ISSUE THREAD

**Issue by ausaleh** [npm/npm#21120]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.

#### What's going wrong?
Its Giving Error: Method Not Allowed message. 
### supporting information:

 -I have updated npm.
 -  Linux(Raspberry pi:
 

    npm ERR! Error: Method Not Allowed
npm ERR!     at errorResponse (/usr/share/npm/lib/cache/add-named.js:260:10)
npm ERR!     at /usr/share/npm/lib/cache/add-named.js:203:12
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:167:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:82:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.14.50+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "serialport"
npm ERR! cwd /home/pi
npm ERR! node -v v4.8.2
npm ERR! npm -v 1.4.21
npm ERR! code E405
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/npm-debug.log
npm ERR! not ok code 0

-->

**Comment by LeoUrzua** [comment]
Your npm and node versions are no longer supported.
You have to update

It works with these versions

[leo@signal-c issueTest]$ node -v && npm -v
v9.9.0
6.1.0

[leo@signal-c issueTest]$ npm install serialport

> serialport@6.2.1 install /home/leo/Documents/issueTest/node_modules/serialport
> prebuild-install || node-gyp rebuild

npm notice created a lockfile as package-lock.json. You should commit this file.
+ serialport@6.2.1
added 193 packages from 78 contributors and audited 506 packages in 4.921s
found 0 vulnerabilities

**Comment by kenany** [comment]
Closing because we indeed no longer support `npm@1`.
