### ISSUE TITLE
Feature request: non-interactive npm login/deployment keys

### ISSUE THREAD

**Issue by fahrradflucht** [npm/npm#21132]
See https://github.com/npm/npm/issues/9747 which got closed by @npm-robot due to not being labeled.

**Comment by kenany** [comment]
Other discussions: https://github.com/npm/npm/issues/9325, https://github.com/npm/npm/issues/12111

**Comment by fahrradflucht** [comment]
Okay closing since I can understand why it is considered dangerous even though I think there are valid use cases for getting tokens from username and password in automation. I did not find those discussions earlier. Thanks.
