### ISSUE TITLE
npm rebuild zmq  failing , some times it is working (i am missing some thing) 

### ISSUE THREAD

**Issue by panampunna** [npm/npm#21135]
Hi,  

I am deploying in docker.  
npm is doing something I don't understand.
Good to have an error log that tell what package is missing 
why  npm not working  in Ubuntu 18.04 ?  

root@8b621e398211:/home/Sandbox/qne# cd /home/Sandbox/qne/mediator
root@8b621e398211:/home/Sandbox/qne/mediator# **npm rebuild zmq**

> zmq@2.14.0 install /home/Sandbox/qne/mediator/node_modules/zmq
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: incorrect header check
gyp ERR! stack     at Zlib._binding.onerror (zlib.js:296:17)
gyp ERR! System Linux 4.4.0-128-generic
gyp ERR! command "node" "/root/.nvm/v0.10.40/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/Sandbox/qne/mediator/node_modules/zmq
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 

npm ERR! zmq@2.14.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zmq@2.14.0 install script.
npm ERR! This is most likely a problem with the zmq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls zmq
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.4.0-128-generic
npm ERR! command "/root/.nvm/v0.10.40/bin/node" "/root/.nvm/v0.10.40/bin/npm" "rebuild" "zmq"
npm ERR! cwd /home/Sandbox/qne/mediator
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/Sandbox/qne/mediator/npm-debug.log
npm ERR! not ok code 0
npm WARN engine ret@0.1.15: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"1.4.28"})
npm WARN engine ret@0.1.15: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"1.4.28"})
npm WARN engine ret@0.1.15: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"1.4.28"})
npm WARN engine ret@0.1.15: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"1.4.28"})
npm WARN engine atob@2.1.1: wanted: {"node":">= 4.5.0"} (current: {"node":"0.10.40","npm":"1.4.28"})
npm WARN engine atob@2.1.1: wanted: {"node":">= 4.5.0"} (current: {"node":"0.10.40","npm":"1.4.28"})
/root/.nvm/v0.10.40/bin/gulp -> /root/.nvm/v0.10.40/lib/node_modules/gulp-cli/bin/gulp.js

#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
Your versions of Node.js and `npm` are years old and are no longer supported.
