### ISSUE TITLE
@angular/cli, webpack, gulp don't install on Debian 9

### ISSUE THREAD

**Issue by Dewberrycat** [npm/npm#21138]
root@debian:~ sudo npm install @angular/cli -g --unsafe-perm
and
root@debian:~ sudo npm install @angular/cli -g
result in:
npm WARN `git config --get remote.origin.url` returned wrong result (git://github.com/angular/cli) 
npm WARN `git config --get remote.origin.url` returned wrong result (git@github.com:angular/cli) 
The authenticity of host 'github.com (192.30.253.112)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
\|e you sure you want to continue connecting (yes/no)? |
npm ERR! git clone git@github.com:angular/cli Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-angular-cli-515723dd'...
npm ERR! git clone git@github.com:angular/cli Warning: Permanently added 'github.com,192.30.253.112' (RSA) to the list of known hosts.
npm ERR! git clone git@github.com:angular/cli git@github.com: Permission denied (publickey).
npm ERR! git clone git@github.com:angular/cli fatal: Could not read from remote repository.
npm ERR! git clone git@github.com:angular/cli 
npm ERR! git clone git@github.com:angular/cli Please make sure you have the correct access rights
npm ERR! git clone git@github.com:angular/cli and the repository exists.
npm ERR! addLocal Could not install angular/cli
npm ERR! Error: ENOENT: no such file or directory, stat 'angular/cli'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.16.0-2-686
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "@angular/cli" "-g" "--unsafe-perm"
npm ERR! cwd /root
npm ERR! node -v v8.11.2
npm ERR! npm -v 1.4.21
npm ERR! path angular/cli
npm ERR! syscall stat
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /root/npm-debug.log
npm ERR! not ok code 0

root@debian:~ npm install -g webpack webpack-cli gulp gulp-cli
result in:

npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN engine rxjs@6.2.1: wanted: {"npm":">=2.0.0"} (current: {"node":"8.11.2","npm":"1.4.21"})
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
/usr/local/bin/gulp -> /usr/local/lib/node_modules/gulp/bin/gulp.js
npm ERR! error rolling back Error: Refusing to delete: /usr/local/bin/gulp not in /usr/local/lib/node_modules/gulp-cli
npm ERR! error rolling back     at clobberFail (/usr/share/npm/lib/utils/gently-rm.js:57:12)
npm ERR! error rolling back     at next (/usr/share/npm/lib/utils/gently-rm.js:43:14)
npm ERR! error rolling back     at /usr/share/npm/lib/utils/gently-rm.js:52:12
npm ERR! error rolling back     at FSReqWrap.oncomplete (fs.js:135:15)
npm ERR! error rolling back  gulp-cli@2.0.1 { Error: Refusing to delete: /usr/local/bin/gulp not in /usr/local/lib/node_modules/gulp-cli
npm ERR! error rolling back     at clobberFail (/usr/share/npm/lib/utils/gently-rm.js:57:12)
npm ERR! error rolling back     at next (/usr/share/npm/lib/utils/gently-rm.js:43:14)
npm ERR! error rolling back     at /usr/share/npm/lib/utils/gently-rm.js:52:12
npm ERR! error rolling back     at FSReqWrap.oncomplete (fs.js:135:15)
npm ERR! error rolling back   stack: 'Error: Refusing to delete: /usr/local/bin/gulp not in /usr/local/lib/node_modules/gulp-cli\n    at clobberFail (/usr/share/npm/lib/utils/gently-rm.js:57:12)\n    at next (/usr/share/npm/lib/utils/gently-rm.js:43:14)\n    at /usr/share/npm/lib/utils/gently-rm.js:52:12\n    at FSReqWrap.oncomplete (fs.js:135:15)',
npm ERR! error rolling back   code: 'EEXIST',
npm ERR! error rolling back   path: '/usr/local/bin/gulp' }
/usr/local/bin/webpack-cli -> /usr/local/lib/node_modules/webpack-cli/bin/cli.js
npm ERR! Error: Method Not Allowed
npm ERR!     at errorResponse (/usr/share/npm/lib/cache/add-named.js:260:10)
npm ERR!     at /usr/share/npm/lib/cache/add-named.js:120:12
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:167:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:135:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.16.0-2-686
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "-g" "webpack" "webpack-cli" "gulp" "gulp-cli"
npm ERR! cwd /root
npm ERR! node -v v8.11.2
npm ERR! npm -v 1.4.21
npm ERR! code E405
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /root/npm-debug.log
npm ERR! not ok code 0

**Comment by LeoUrzua** [comment]
Your npm version is no longer supported
Update it to 

```
npm - v
6.1.0
```

**Comment by kenany** [comment]
Closing per above comment.

**Comment by Dewberrycat** [comment]
LeoUrzua, after updating npm to v 6 - still the same errors with @angular/cli and it still cannot be installed, all the same
