### ISSUE TITLE
ENOENT: no such file or directory "aws-sign" with fresh install strongloop

### ISSUE THREAD

**Issue by anindyasund** [npm/npm#21133]
#### I'm opening this issue because:
  - [x] npm is producing an incorrect install.

### supporting information:

 - `npm -v` prints: 5.6.0
 - `node -v` prints:v8.11.3
 - `npm config get registry` prints:https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?:Windows 10

``PS C:\Windows\system32> npm install -g strongloop
npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/
status/
npm WARN deprecated mailcomposer@4.0.1: This project is unmaintained
npm WARN deprecated socks@1.1.9: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socke
t data flow and an import issue introduced in 2.1.0
npm WARN deprecated buildmail@4.0.1: This project is unmaintained
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.co
m/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated ejs@1.0.0: Critical security bugs fixed in 2.5.5
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versio
ns of Node.js
npm WARN deprecated sprintf@0.1.5: The sprintf package is deprecated in favor of sprintf-js.
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated connect@2.30.2: connect 2.x series is deprecated
npm WARN deprecated coffee-script@1.6.3: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated sprintf@0.1.1: The sprintf package is deprecated in favor of sprintf-js.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! path C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\node_modules\nodefly-register\node_modules\reque
st\node_modules\aws-sign
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\nod
e_modules\nodefly-register\node_modules\request\node_modules\aws-sign' -> 'C:\Users\user\AppData\Roaming\npm\node_module
s\strongloop\node_modules\nodefly-register\node_modules\request\node_modules\.aws-sign.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2018-07-03T06_59_47_932Z-debug.log``

**Comment by DanielRuf** [comment]
Try clearing the cache with `npm cache clean --force`, try verdaccio as local cache and pnpm as possible alternative.

**Comment by anindyasund** [comment]
Worked with pnpm. Thanks
