### ISSUE TITLE
http-server loading issues

### ISSUE THREAD

**Issue by HossamAbdelrhman** [npm/npm#21156]
I try to install npm http-server using command (npm install http-server -g) but i get error below and i don't know why can any one help me ?!!
npm ERR! Linux 4.13.0-45-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "http-server" "-g"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! path /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, access '/usr/local/lib/node_modules']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/hossam/npm-debug.log

**Comment by kenany** [comment]
Seems like you do not have permission to access `/usr/local/lib/node_modules`. You can try prefixing your command with `sudo` if you would like to elevate to admin privileges.

Since this is not an issue with `npm` itself, I'm gonna close this.
