### ISSUE TITLE
Npm install triggers a method not allowed

### ISSUE THREAD

**Issue by realtebo** [npm/npm#21167]
```
Running `distelli push -t d10057:421493 -m fixes --enable-docker -f distelli://realtebo/firebase_tntvillage` in /build Build: npm 
ERR! Error: Method Not Allowed npm 
ERR! at errorResponse (/home/travis/.nvm/v0.10.36/lib/node_modules/npm/lib/cache/add-named.js:260:10) npm 
ERR! at /home/travis/.nvm/v0.10.36/lib/node_modules/npm/lib/cache/add-named.js:203:12 npm 
ERR! at saved (/home/travis/.nvm/v0.10.36/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:167:7) npm 
ERR! at then (/home/travis/.nvm/v0.10.36/lib/node_modules/npm/node_modules/chownr/chownr.js:21:22) npm 
ERR! at Object.oncomplete (fs.js:108:15) npm 
ERR! If you need help, you may report this *entire* log, npm 
ERR! including the npm and node versions, at: npm 
ERR! <http://github.com/npm/npm/issues> npm 
ERR! System Linux 3.19.0-80-generic npm 
ERR! command "/home/travis/.nvm/v0.10.36/bin/node" "/home/travis/.nvm/v0.10.36/bin/npm" "install" npm 
ERR! cwd /build/functions npm 
ERR! node -v v0.10.36 npm
 ERR! npm -v 1.4.28 npm
 ERR! code E405
```

I am running on puppets pipeline, that as you can see is a Travis CI

I cannot understand why npm install fails

**Comment by DanielRuf** [comment]
This is probably due to permission or network issues. Error 405 is not so rare and there are other related issues.

What did you do so far to find a working solution?

**Comment by realtebo** [comment]
I still not found a solution. Actually I am trying to setup Jenkins . 

I think it is related to ancient node version...  And I am too bored to find docs so I have not tried to upgrade node.

**Comment by realtebo** [comment]
If it is a network error, on puppets system ... It is not good.

**Comment by DanielRuf** [comment]
Well, node 0.10 is very old and not supported anymore. Also npm 1 is very old. And puppeteer needs at least node 6. Try upgrading node to version 8 and npm to 5 or 6.

**Comment by DanielRuf** [comment]
Well, node 0.10 is very old and not supported anymore. Also npm 1 is very old. Try upgrading node to version 8 and npm to 5 or 6.

**Comment by realtebo** [comment]
The problem is how to update node on puppet distelli server
.  . . Well. Other issue
 I close this
