### ISSUE TITLE
Broke npm (again) refuses to install dependencies for my project

### ISSUE THREAD

**Issue by dudeisbrendan03** [npm/npm#21175]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [x] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### How can the CLI team reproduce the problem?

```
git clone http://gitlab.bar-technology.co.uk/brendantdj/react.git
cd react
npm install
```

### supporting information:

 - `npm -v` prints:  1.4.21
 - `node -v` prints:  v0.10.29
 - `npm config get registry` prints:  https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux - debian
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

output I get:
http://gitlab.bar-technology.co.uk/snippets/4

**Comment by dudeisbrendan03** [comment]
I just want to get past npm install, that's it

**Comment by DanielRuf** [comment]
Can you provide `/home/gitlab-runner/builds/a9a25aa2/0/brendantdj/react/npm-debug.log`?

These are some pretty old releases:
```
$ npm -v
1.4.21
$ nodejs -v
v0.10.29
```

Try upgrading Node to 10.6.0 and also npm.

**Comment by dudeisbrendan03** [comment]
I'll ask them

**Comment by dudeisbrendan03** [comment]
Made npm-debug.log an artifact, running it now

**Comment by dudeisbrendan03** [comment]
http://gitlab.bar-technology.co.uk/snippets/5

**Comment by DanielRuf** [comment]
See https://github.com/npm/npm/issues/20830 so updating npm is highly recommended. `npm@1` is not supported anymore.

**Comment by dudeisbrendan03** [comment]
It's apparently latest

**Comment by dudeisbrendan03** [comment]
It's Debian 8. Can we upgrade node on deb 8?

**Comment by DanielRuf** [comment]
> It's apparently latest

Did you try `npm i -g npm@latest` to upgrade npm?

**Comment by dudeisbrendan03** [comment]
And what about node?

**Comment by dudeisbrendan03** [comment]
I'm at npm 6.1.0 now

EDIT:
It says npm@6.1.0 but if I do `npm -v` it still outputs with 1.4.21

**Comment by DanielRuf** [comment]
> It says npm@6.1.0 but if I do npm -v it still outputs with 1.4.21

Did you restart the terminal session?

**Comment by dudeisbrendan03** [comment]
It's on continuous integration

**Comment by DanielRuf** [comment]
Is the upgrade after the installation of node and npm?
You can also try if it still works on node 10 as 0.10 is also not officially supported anymore.

**Comment by dudeisbrendan03** [comment]
How do I upgrade to the latest npm+node in Debian 8 though?

**Comment by DanielRuf** [comment]
With apt-get, see https://askubuntu.com/a/480642 and https://askubuntu.com/a/548776

**Comment by dudeisbrendan03** [comment]
node updated, can't update npm still

**Comment by DanielRuf** [comment]
> node updated, can't update npm still

It should be 6 with node 10 by default.

Or is there some network issue or firewalling? Would be good to know if this can be reproduced with the latest supported releases of npm (6) and node (10).

**Comment by dudeisbrendan03** [comment]
I got provisioned another machine, and I got this:
```
$nodejs -v
v4.2.6
$node -v
v10.6.0

…
```

**Comment by dudeisbrendan03** [comment]
how do I know if npm is running node or nodejs, and how do I make it run the latest (node)

do I just uninstall nodejs?

**Comment by DanielRuf** [comment]
Try running `npm config get`.

**Comment by dudeisbrendan03** [comment]
Works now, thanks!


(got config location and changed node bin location - was wrong)
