### ISSUE TITLE
npm ERR! Error: No dist in undefined package

### ISSUE THREAD

**Issue by lanlingxueyu** [npm/npm#21177]
pm ERR! Error: No dist in undefined package
npm ERR!     at next (/usr/share/npm/lib/cache.js:746:26)
npm ERR!     at /usr/share/npm/lib/cache.js:739:5
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-24-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "serve"
npm ERR! cwd /root

**Comment by DanielRuf** [comment]
Please try `npm cache clean --force` and then several `npm install`.

**Comment by DanielRuf** [comment]
> npm ERR! http://github.com/isaacs/npm/issues
> npm ERR! or email it to:
> npm ERR! npm-@googlegroups.com

This looks like you have a very old npm version. Can you try upgrading npm to the latest version?

**Comment by Ranjithpnair** [comment]
Hi I am using npm -versio as 1.3.10 ,

I am also getting 

npm http 404 https://registry.npmjs.org/webassemblyjs/ast/1.5.13
npm ERR! Error: No dist in undefined package
npm ERR!     at next (/usr/share/npm/lib/cache.js:746:26)
npm ERR!     at /usr/share/npm/lib/cache.js:739:5
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-147-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "webpack"
npm ERR! cwd /home/nandakishor/npm_sample/chrome-extension-skeleton-master
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10

**Comment by kenany** [comment]
`npm@1` is no longer supported.

**Comment by Ranjithpnair** [comment]
Which version will fix this issue please share

**Comment by kenany** [comment]
@Ranjithpnair Try `npm@5` or `npm@6`.
