### ISSUE TITLE
ERROR 

### ISSUE THREAD

**Issue by unterzwerg** [npm/npm#21170]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  

#### What's going wrong?
I am not sure whether I really need to follow the steps in 
"https://cesiumjs.org/tutorials/cesium-and-webpack/"
I have Cesium installed in a folder(C:/Program Files (x86)/Cesium) and want to use it from other folders/paths (D:/.../.../...)
I followed the steps in the mentioned site and get the error lots of npm ERROR when executing
"npm run build"

#### How can the CLI team reproduce the problem?
Here is my npm-debug.log:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@4.0.5
3 info using node@v7.4.0
4 verbose stack Error: missing script: build
4 verbose stack     at run (C:\Program Files (x86)\nodejs\node_modules\npm\lib\run-script.js:151:19)
4 verbose stack     at C:\Program Files (x86)\nodejs\node_modules\npm\lib\run-script.js:61:5
4 verbose stack     at C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:356:5
4 verbose stack     at checkBinReferences_ (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:320:45)
4 verbose stack     at final (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:354:3)
4 verbose stack     at then (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:124:5)
4 verbose stack     at ReadFileContext.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:295:20)
4 verbose stack     at ReadFileContext.callback (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16)
4 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:336:13)
5 verbose cwd S:\ARTISsvn_work\src\app\geo_db
6 error Windows_NT 6.1.7601
7 error argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
8 error node v7.4.0
9 error npm  v4.0.5
10 error missing script: build
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

**Comment by unterzwerg** [comment]
I fixed my bug

**Comment by DanielRuf** [comment]
> 4 verbose stack Error: missing script: build

I guess there was no `build` script in your package.json.
