### ISSUE TITLE
Persisting "Unexpected end of JSON input while parsing near ..." even after npm cache clean --force

### ISSUE THREAD

**Issue by devlargs** [npm/npm#21181]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [x] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I cant get away with this error even though the popular answer on github was to clean the cache.
I've already tried with these answers but I keep on getting it. I also uninstalled and reinstalled node.

1. https://github.com/npm/npm/issues/19072
2. https://github.com/vuejs-templates/webpack/issues/990

Am I missing something? 

Note: This is a fresh install react-native app, and any plugin that im trying to install results to that error. Can someone help me with this one?

![image](https://user-images.githubusercontent.com/30046754/42503236-cc28bafe-846a-11e8-9279-d4b9f57952c4.png)

### supporting information:

 - `npm -v` prints: 6.1.0
 - `node -v` prints: v8.11.3
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux
- Gist: https://gist.github.com/devlargs/adcdc2268bfa08587a86dbd6556ab855

**Comment by DanielRuf** [comment]
Same issue here. This is due to network / infrastructure issues and I solve this by using verdaccio as local cache.

**Comment by DanielRuf** [comment]
You will see that it is the cache because after every cleaning of the cache the error is a bit different.

**Comment by mungpara** [comment]
I also trie npm cache clear --force but it is not working.
I also remove npm and npm-cache folder and uninstall node js and reinstall nodejs but issue still exists

**Comment by DanielRuf** [comment]
Can you try installing and using verdaccio as registry cache?
Alternatively you can also use yarn.

**Comment by devlargs** [comment]
Hi @DanielRuf  running command  [sudo npm install -g verdaccio](`url`) gives me this

![image](https://user-images.githubusercontent.com/30046754/42551500-183e1fca-850a-11e8-81fc-a1688a4e1681.png)

**Comment by DanielRuf** [comment]
@devlargs please never use sudo for npm and packages. Please try it without sudo.

`npm i -g verdaccio`

**Comment by devlargs** [comment]
Installing without "sudo" gives an error code of EACCES.

**Comment by devlargs** [comment]
I have installed verdaccio by using the --unsafe-perm flag. Now Im just going to try what this package does. Thanks @DanielRuf 

![image](https://user-images.githubusercontent.com/30046754/42551673-0c7f7b74-850b-11e8-868e-ca14a7ea8364.png)

Hope it resolve my current issue

**Comment by DanielRuf** [comment]
No, please do not use the `--unsafe-perm` flag. Running `sudo npm` is bad. Just run `npm` without sudo.

**Comment by DanielRuf** [comment]
This means that you've installed npm / node using sudo in the past. In general it makes sense to reinstall both without sudo after fully removing npm and node.

**Comment by DanielRuf** [comment]
For further info see the docs of verdaccio.

Basically you run `verdaccio` and in another window your `npm install` but with `--registry http://localhost:4873/` at the end.

**Comment by devlargs** [comment]
Is there additional configurations or something? I followed exactly what is written on the docs.

![image](https://user-images.githubusercontent.com/30046754/42552060-23f23a56-850d-11e8-8945-bc2d288aa7ed.png)

**Comment by DanielRuf** [comment]
Try an upgrade of Node (10.6.0) and npm (6.2.0) and reinstall verdaccio.

**Comment by devlargs** [comment]
Thanks @DanielRuf, I can now install packages with ease and without that irritating error. Cheers!

**Comment by devlargs** [comment]
Will now close this issue
