### ISSUE TITLE
[DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

### ISSUE THREAD

**Issue by Efunity** [npm/npm#21180]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

pi@raspberrypi:~ $ npm install node-red-contrib-modbustcp
(node:6515) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
npm ERR! tar.unpack untar error /home/pi/.npm/npm/5.10.0/package.tgz
npm ERR! Error: Method Not Allowed
npm ERR!     at errorResponse (/usr/share/npm/lib/cache/add-named.js:260:10)
npm ERR!     at /usr/share/npm/lib/cache/add-named.js:203:12
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:167:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:135:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.14.52-v7+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "node-red-contrib-modbustcp"
npm ERR! cwd /home/pi
npm ERR! node -v v8.11.1
npm ERR! npm -v 1.4.21
npm ERR! code E405
npm WARN package.json bcrypt-pbkdf@1.0.1 No repository field.
npm WARN package.json extsprintf@1.0.2 No license field.
npm WARN package.json json-schema@0.2.3 No license field.
npm WARN package.json jsonify@0.0.0 license should be a valid SPDX license expression
npm WARN package.json punycode@1.4.1 punycode is also the name of a node core module.
npm WARN package.json sntp@1.0.9 No license field.
npm WARN package.json string_decoder@1.0.3 string_decoder is also the name of a node core module.
npm WARN package.json verror@1.3.6 No license field.
-
> serialport@5.0.0 install /home/pi/node_modules/node-red-contrib-modbustcp/node_modules/jsmodbus/node_modules/serialport
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/5.0.0/serialport-v5.0.0-node-v57-linux-arm.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for serialport@5.0.0 and node@8.11.1 (node-v57 ABI) (falling back to source compile with node-gyp) 
make: Entering directory '/home/pi/node_modules/node-red-contrib-modbustcp/node_modules/jsmodbus/node_modules/serialport/build'
  CXX(target) Release/obj.target/serialport/src/serialport.o
../src/serialport.cpp: In function ‘void EIO_AfterOpen(uv_work_t*)’:
../src/serialport.cpp:96:30: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
   data->callback.Call(2, argv);
                              ^
In file included from ../src/./serialport.h:6:0,
                 from ../src/serialport.cpp:1:
../node_modules/nan/nan.h:1618:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/serialport.cpp: In function ‘void EIO_AfterUpdate(uv_work_t*)’:
../src/serialport.cpp:152:30: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
   data->callback.Call(1, argv);
                              ^
In file included from ../src/./serialport.h:6:0,
                 from ../src/serialport.cpp:1:
../node_modules/nan/nan.h:1618:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/serialport.cpp: In function ‘void EIO_AfterClose(uv_work_t*)’:
../src/serialport.cpp:191:30: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
   data->callback.Call(1, argv);
                              ^
In file included from ../src/./serialport.h:6:0,
                 from ../src/serialport.cpp:1:
../node_modules/nan/nan.h:1618:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/serialport.cpp: In function ‘void EIO_AfterFlush(uv_work_t*)’:
../src/serialport.cpp:235:30: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
   data->callback.Call(1, argv);
                              ^
In file included from ../src/./serialport.h:6:0,
                 from ../src/serialport.cpp:1:
../node_modules/nan/nan.h:1618:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/serialport.cpp: In function ‘void EIO_AfterSet(uv_work_t*)’:
../src/serialport.cpp:290:30: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
   data->callback.Call(1, argv);
                              ^
In file included from ../src/./serialport.h:6:0,
                 from ../src/serialport.cpp:1:
../node_modules/nan/nan.h:1618:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/serialport.cpp: In function ‘void EIO_AfterGet(uv_work_t*)’:
../src/serialport.cpp:342:30: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
   data->callback.Call(2, argv);
                              ^
In file included from ../src/./serialport.h:6:0,
                 from ../src/serialport.cpp:1:
../node_modules/nan/nan.h:1618:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/serialport.cpp: In function ‘void EIO_AfterDrain(uv_work_t*)’:
../src/serialport.cpp:384:30: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
   data->callback.Call(1, argv);
                              ^
In file included from ../src/./serialport.h:6:0,
                 from ../src/serialport.cpp:1:
../node_modules/nan/nan.h:1618:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
  CXX(target) Release/obj.target/serialport/src/serialport_unix.o
  CXX(target) Release/obj.target/serialport/src/poller.o
../src/poller.cpp: In static member function ‘static void Poller::onData(uv_poll_t*, int, int)’:
../src/poller.cpp:69:29: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
   obj->callback.Call(2, argv);
                             ^
In file included from ../src/poller.cpp:1:0:
../node_modules/nan/nan.h:1618:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
  SOLINK_MODULE(target) Release/obj.target/serialport.node
  COPY Release/serialport.node
make: Leaving directory '/home/pi/node_modules/node-red-contrib-modbustcp/node_modules/jsmodbus/node_modules/serialport/build'
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/npm-debug.log
npm ERR! not ok code 0

**Comment by Efunity** [comment]
Done some simple programming previously but this is the first time i face this kind of error and i have no idea how to solve it. Please help me. THANKS!

**Comment by DanielRuf** [comment]
Please try `npm cache clean --force` with multiple `npm install` and verdaccio as local cache.

**Comment by kenany** [comment]
`npm@1` is years old and is no longer supported.

**Comment by DanielRuf** [comment]
> npm ERR! npm -v 1.4.21

An upgrade might help, yes.

**Comment by Efunity** [comment]
pi@raspberrypi:~ $ sudo apt-get update
Hit:1 http://linux.teamviewer.com/deb stable InRelease
Get:2 http://archive.raspberrypi.org/debian stretch InRelease [25.3 kB]
Hit:3 http://linux.teamviewer.com/deb preview InRelease          
Hit:4 http://raspbian.raspberrypi.org/raspbian stretch InRelease               
Get:5 http://archive.raspberrypi.org/debian stretch/main armhf Packages [166 kB]
Get:6 http://archive.raspberrypi.org/debian stretch/ui armhf Packages [34.0 kB]
Fetched 225 kB in 5s (43.7 kB/s)                           
Reading package lists... Done
pi@raspberrypi:~ $ sudo apt-get upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages have been kept back:
  sense-emu-tools
The following packages will be upgraded:
  python-sense-emu python-sense-emu-doc python3-sense-emu
3 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
Need to get 702 kB of archives.
After this operation, 464 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://archive.raspberrypi.org/debian stretch/main armhf python-sense-emu all 1.1 [202 kB]
Get:2 http://archive.raspberrypi.org/debian stretch/main armhf python-sense-emu-doc all 1.1 [298 kB]
Get:3 http://archive.raspberrypi.org/debian stretch/main armhf python3-sense-emu all 1.1 [202 kB]
Fetched 702 kB in 2s (242 kB/s)             
Reading changelogs... Done
(Reading database ... 127569 files and directories currently installed.)
Preparing to unpack .../python-sense-emu_1.1_all.deb ...
Unpacking python-sense-emu (1.1) over (1.0) ...
Preparing to unpack .../python-sense-emu-doc_1.1_all.deb ...
Unpacking python-sense-emu-doc (1.1) over (1.0) ...
Preparing to unpack .../python3-sense-emu_1.1_all.deb ...
Unpacking python3-sense-emu (1.1) over (1.0) ...
Setting up python3-sense-emu (1.1) ...
Setting up python-sense-emu (1.1) ...
Setting up python-sense-emu-doc (1.1) ...
pi@raspberrypi:~ $ sudo npm install npm
(node:1611) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.


@DanielRuf  i cant update my npm either

**Comment by Efunity** [comment]
@DanielRuf  i can't upgrade my npm, the same error message will still appear. 
I follow this method to get my error fixed.  
pi@raspberrypi:~ $  node -v
v0.10.29
pi@raspberrypi:~ $  sudo su -
root@raspberrypi:~ # apt-get remove nodered -y
root@raspberrypi:~ # apt-get remove nodejs nodejs-legacy -y
root@raspberrypi:~ # apt-get remove npm  -y # if you installed npm
root@raspberrypi:~ # curl -sL https://deb.nodesource.com/setup_5.x | sudo bash -
root@raspberrypi:~# apt-get install nodejs -y
root@raspberrypi:~# node -v
v5.9.0
root@raspberrypi:~# npm -v
3.7.3
the link: https://www.raspberrypi.org/forums/viewtopic.php?t=140747

I realize that if i use this command " sudo apt-get install npm" my raspberry pi would get the older version instead of the updated version. So I try skipping this part and i got my problem solve, thanks.

**Comment by Efunity** [comment]
Sorry, new to this forum, how do i close this issue?

**Comment by DanielRuf** [comment]
Try using `nvm`, node 0.10 is very old.

Also do not use sudo for `npm install ...`.

**Comment by DanielRuf** [comment]
Was your issue resolved and by what?

**Comment by DanielRuf** [comment]
Your issue was already closed by @Kenany.
