### ISSUE TITLE
npm install - cb() never called

### ISSUE THREAD

**Issue by Megumin42** [npm/npm#21196]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
    - [ ] npm is producing incorrect or undesirable behavior.
  - [ ] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):

#### What's going wrong?

```
C:\dev\core\server [master +1 ~2 -0 !]                                                           
λ  npm cache clean --force                                                                       
npm WARN using --force I sure hope you know what you are doing.                                  
C:\dev\core\server [master +1 ~2 -0 !]                                                           
λ  npm install                                                                                   
npm ERR! cb() never called!                                                                      
                                                                                                 
npm ERR! This is an error with npm itself. Please report this error at:                          
npm ERR!     <https://github.com/npm/npm/issues>                                                 
                                                                                                 
npm ERR! A complete log of this run can be found in:                                             
npm ERR!     C:\Users\MrSpider\AppData\Roaming\npm-cache\_logs\2018-07-11T16_04_36_414Z-debug.log
```

#### How can the CLI team reproduce the problem?

[debug logs](https://gist.github.com/MrSpider/564b49b4561b160cbc12a2255ca4c4f2)
[package.json + package-lock.json](https://gist.github.com/MrSpider/a2dc52b61beb61af83c98be16c2774b7)

### supporting information:

 - `npm -v` prints: 6.1.0
 - `node -v` prints: 8.9.4
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by Megumin42** [comment]
Found the problem.

We have two local dependencies:
```
"@shopiq/process-scheduler": "file:shared/typescript/process-scheduler",
"@shopiq/smp": "file:shared/typescript/smp",
```

where `shared ` is a symlink to `../shared`.
The symlink was broken thats why npm threw the error.

This issue can be closed. I have created another issue for a different followup error.

**Comment by DanielRuf** [comment]
You can close the issue at the bottom.
