### ISSUE TITLE
npm does not work behind a proxy if the proxy uses NTLM authentification

### ISSUE THREAD

**Issue by Mithgol** [npm/npm#2119]
NPM is currently unable to work from behind [NTLM](http://en.wikipedia.org/wiki/NTLM) proxies, or maybe it is just underdocumented. Most likely, it doesn't work (according to some comments at #718).

There is currently no NTLM-supporting [node modules](https://github.com/joyent/node/wiki/Modules) I know of. It probably means that fixing this issue would require one of the following approaches:

* a Python→JavaScript port of [NTLM Authorization Proxy Server](http://ntlmaps.sourceforge.net/)

* a [node-ffi](https://github.com/rbranson/node-ffi/) wrapper around [Libntlm](http://www.nongnu.org/libntlm/)

* a well-documented recommendation to use [Cntlm](http://cntlm.sourceforge.net/), if it's supported by NPM (some comments at #718 imply that it isn't)

**Comment by kmrrakesh** [comment]
npm config set proxy http://127.0.0.1:8080

Please - It is throwing error like "npm err!network getaddrinfo ENOTFOUND 127.0.0.1:8080"

**Comment by kmrrakesh** [comment]
Please look into it as it is not working for me:

npm warn invalid config proxy http://'Accenture\kmrrakesh:Accent@2017'@127.0.0.1:8080
npm warn invalid config Must be a full url with 'http://'

**Comment by sandydcr** [comment]
please use
 npm config set proxy http://xx.aa.bb.cc:port
it worked for me
thanks a lot !

**Comment by kmrrakesh** [comment]
It worked for me.
Thank you sandydcr and all!

**Comment by cwhankey** [comment]
sorry, but NONE of the combos suggested above work for me.   npm sounded cool.  not ready for prime time maybe?

**Comment by kmrrakesh** [comment]
Dear cwhankey, it might be because of the settings of the proxy which bars social sites like facebook, gmail and it unfortunately includes links of the required packages while installing express or any other packages.

You need to see that.

**Comment by michaelgugino** [comment]
This software is garbage.  I'm using the latest stable release of npm directly from node's site (binary).  I'm still getting tunnel problems, after setting proxies, non-strict ssl, using http registry.  It's trying to clone a tarball from github for some package.  Give me a break already.

**Comment by yellek** [comment]
With cntlm running on port 3128 on my local machine (the default) I put the following in my .npmrc file in my home directory which is now working:

https-proxy=http://127.0.0.1:3128
proxy=http://127.0.0.1:3128
registry=http://registry.npmjs.org/

**Comment by ManFromEast** [comment]
great answer!
thanks @ldsenow 
I have tried OXS and ubuntu VM on mac
in OXS I only set the proxy in .npmrc file as following:
npm config set proxy http://username:password@proxyserver_ip:proxyserver_port
npm config set https-proxy https://username:password@proxyserver_ip:proxyserver_port

it works, but in ubuntu VM
I just set proxy, but it can't work, until I add the below command, it works in Ubuntu VM.
npm config set registry http://registry.npmjs.org/

check all configuration : npm config list

**Comment by Mithgol** [comment]
Recently [npm registry has gone to HTTPS](http://blog.npmjs.org/post/142077474335/npm-registry-is-now-fully-https).

It means that [Cntlm](http://cntlm.sourceforge.net/) does no longer help to reach npm (because it does not seem to tunnel HTTPS).

**Comment by Mithgol** [comment]
Personally I am no longer affected by this issue (i.e. I am no longer behind a proxy).

However, because I've previously closed this issue with the reason like “Cntlm works”, I feel compelled to reopen it now (with the reason “Cntlm does not work any longer”).

**Comment by bcamposq1995** [comment]
i solve with this:
1- get your proxy server and port in Window key -> Configure Proxy Server -> Lan Settings -> Address and port
2- put this in C:\Users\your.user\.npmrc
https-proxy=http://address:port
proxy=http://address:port
registry=http://registry.npmjs.org/

Then npm install express

**Comment by uniwizardcom** [comment]
Yes, it very important to add "http://" prefix for proxy IP address! It was my fault when I first time tried of configure npm.

**Comment by snopeks** [comment]
Hello @Mithgol ! In this situation, changing `https` urls to `http` should resolve this proxy config issue, as `cntlm` only works via `http`. I'm going to close as resolved, but if you continue to have issues or any other questions, please write into support@npmjs.com and we'll be happy to help.

**Comment by ramazanpolat** [comment]
I am behind an NTLM proxy.
Tried these and it worked!

```
npm config set registry "http://registry.npmjs.org/"
npm config set proxy http://127.0.0.1:3128
npm config set https-proxy http://127.0.0.1:3128
```

**Comment by ForsakenEcho** [comment]
I setup everything still does not work. I'm in windows.

**Comment by ramazanpolat** [comment]
@ForsakenEcho 
Set proxy to your CNTLM on firefox to be sure that CNTLM is configured correctly(not another browser, others use system proxy setting while firefox has it's own proxy settings). If it doesn't work, visit this [SO answer](http://stackoverflow.com/questions/19401468/why-is-cntlm-asking-for-password/23962313#23962313) and configure CNTLM properly.

Then use these commands:
npm config set registry "http://registry.npmjs.org/"
npm config set proxy http://127.0.0.1:3128
npm config set https-proxy http://127.0.0.1:3128

I am using Windows too. I've just tried it and it's working.

**Comment by tobiaxor** [comment]
I think CNTLM might have troubles when the authentication mode is NEGOTIATE, which might resolve to Kerberos as well, especially if you're working in a **windows environment**. CNTLM does not work with Kerberos AFAIK. If that's the case, you probably won't find any workaround, except quitting your job :) 
CNTLM works only with basic/NTLM authentication. You can check your authentication mode with fiddler, snooping out the authentication headers and the potential 407 response.

**Comment by aecorredor** [comment]
I have tried all the troubleshooting steps that you find in google, stackoverflow, and GitHub when searching for this issue, I still have not been able to fix it, here is my error:

npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ECONNRESET

npm ERR! network tunneling socket could not be established, cause=Parse Error
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

**Comment by genotrance** [comment]
Or if you are running npm on Windows, just use Px: http://github.com/genotrance/px

No need to provide any credentials - Px just authenticates as the logged in user. Super easy to setup and use and no worries of locking out your account cause you forgot to update the CNTLM.ini password hashes.

**Comment by tobiaxor** [comment]
I think that if your proxy uses only Kerberos, neither Px nor CNTLM will help you, they both work only with NTLM.

**Comment by NewWorldMan** [comment]
I get almost the same error, with the same versions, as aecorredor above...
`npm WARN invalid config proxy="npm"
npm WARN invalid config Must be a full url with 'http://'
npm WARN invalid config proxy="npm"
npm WARN invalid config Must be a full url with 'http://'
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! syscall getaddrinfo

npm ERR! network getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:80
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:`

Not sure what to do. Does the post above insinuate I can use that Px link above to get the needed node_modules to run on the angular build I have?

That's basically what I need.

Thanks!

**Comment by genotrance** [comment]
It looks like your npm config isn't set correctly. What's the output of `npm config list`? Here's what it should be if you are using CNTLM or Px.

```
https-proxy = "http://localhost:3128/"
proxy = "http://localhost:3128/"
```

You can configure it correctly as mentioned above by ramazanpolat:- 

```
npm config set proxy http://localhost:3128
npm config set https-proxy http://localhost:3128
```

**Comment by NewWorldMan** [comment]
Thanks, Viswan,

I was using a different port, but I’ll try plugging that in and see.

Thanks,

BP

**Comment by NewWorldMan** [comment]
I’ve got it set like the following:

https-proxy=http://webproxy.pr21:8080/
proxy=http://webproxy.pr21:8080/
registry=http://registry.npmjs.org/
strict-ssl=false
proxy=npm

This wouldn’t be correct?
