### ISSUE TITLE
Deprecated CSSselect and CSSwhat

### ISSUE THREAD

**Issue by jacopolanzoni** [npm/npm#21194]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
When running 'npm install production', I get the following warnings:
[WARNING] npm WARN deprecated CSSselect@0.7.0: the module is now available as 'css-select'
[WARNING] npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'

#### How can the CLI team reproduce the problem?

Upgrade to css-select and css-what. 

### supporting information:

 - `npm -v` prints: 6.1.0
 - `node -v` prints: v8.11.3
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: OX X/macOS

**Comment by DanielRuf** [comment]
This has nothing to do with npm, please check http://npmjs.com/package/CSSselect and http://npmjs.com/package/css-select and also the other. You just may have to update your package.json content.

**Comment by jacopolanzoni** [comment]
Hi Daniel, thanks for the quick reply. I understand that the warning in itself has nothing to do with NPM, but what I am asking - and apologies if it is not clear - is: is it the desired behaviour to display deprecation of dependencies of dependencies?

**Comment by DanielRuf** [comment]
> is: is it the desired behaviour to display deprecation of dependencies of dependencies

Yes, this is desired. They are hoisted and shown in general (afaik).
