### ISSUE TITLE
Enforce 2FA on publish

### ISSUE THREAD

**Issue by michaelgv** [npm/npm#21207]
In light of the growing compromises of NPM packages and malicious actors trying to mass compromise, I’ve drafted a proposal to enforce 2FA on attempted publish of a package:

## Outline

Although two factor authentication is not bulletproof, it offers a more significant challenge for a malicious actor to compromise a package. It would require a few changes to the structure of how packages are published, mainly a look up to see... 

1. Is the package I am attempting to publish have a restriction that requires you to use 2FA to publish?

2. If the answer to #1 is yes, what is your two factor authentication token?

## Pros and Cons

There are some reasonable cons that could be present, if implemented:

1. Deployment over CI/CD May need to be altered to use one-time pass codes, it would require a master token, a child token. The child token would ask the master (in this case, NPM with a key pair) to sign a random token, the token would then be considered a deployment key and granted one-time access only

2. The time to deploy could be increased by a minute or two, **however, this doubles as a pro, because the time it takes is merely having you verify a 2FA token to publish**

There are also some pros, they are in short order:

1. Publishing would effectively always require a 2FA token, and a person capable of verifying a device with phone number, and entering said code

2. Deployments could effectively be signed by the deploying author, based on their 2FA success

3. After *n* number of failures to authenticate, flag the package / notify all maintainers of attempter access and failure, giving the maintainers a head start

## Goals

A few overall goals:

1. Reduce the capability of malicious actors to compromise packages and make it time consuming to pull off an attack successfully

2. Ablility to restrict by package that all maintainers must have two factor authentication enabled

3. CI/CD can be achieved with signed tokens in place of 2FA with reasonable protections against malicious actors

4. As previously noted, it allows the maintainer(s) to have a head start with notifications of possible breaches/attempted breaches

## Foot notes

It’s not bulletproof, but it’ll deter most brute force-only attackers as it’ll now require a bigger workaround to get access, and most will not be inclined to attack due to the nature of the system. This does not prevent malicious actors with time to attack, only gives them a harder time to succeed. 

*What are your thoughts?*

**Comment by sbonami** [comment]
Pretty sure they have this: https://docs.npmjs.com/getting-started/using-two-factor-authentication. It's opt-in, are you recommending it's required? Or that if some package threshold is met, then it is required?

> There are two levels of authentication, auth-only and auth-and-writes.
>
> If you enable 2FA in *auth-only* mode, npm will require an OTP when you:
> - log in
> - remove 2FA
> 
> If you enable 2FA in *auth-and-writes* mode, which is the default, npm will require an OTP when you:
>
> - log in
> - change your profile
> - create or revoke tokens
> - publish packages
> - change access
> - change your password
> - make other sensitive changes to packages
> - remove 2FA

**Comment by zkat** [comment]
You probably want to post this to https://github.com/npm/rfcs. We're closing this issue tracker very soon (probably today?), so we don't really pay much attention here these days.

**Comment by zkat** [comment]
I'm gonna let https://npm.community/t/require-or-at-least-broadcast-package-2fa/458 supersede this specific issue, so I'm closing this. If you're not already filing an RFC (which you -might- wanna hold off on a bit), that's a better place to move this discussion.
