### ISSUE TITLE
bundleDependencies isn't being published properly

### ISSUE THREAD

**Issue by TooTallNate** [npm/npm#2147]
I'm trying to add all the dependencies in `node-gyp` as "bundleDependencies", but when I publish the module and 2nd level dependencies don't get installed:

```
├─┬ node-gyp@0.0.5 
│ ├── ansi@0.0.3 
│ ├─┬ glob@3.0.1 
│ │ ├── UNMET DEPENDENCY fast-list 1
│ │ ├── UNMET DEPENDENCY graceful-fs ~1.1.2
│ │ └── UNMET DEPENDENCY inherits 1
│ ├─┬ minimatch@0.1.5 
│ │ └── UNMET DEPENDENCY lru-cache ~1.0.5
│ ├── mkdirp@0.3.0 
│ ├─┬ nopt@1.0.10 
│ │ └── UNMET DEPENDENCY abbrev 1
│ ├── request@2.9.100 
│ ├── rimraf@2.0.1 
│ ├─┬ tar@0.1.12 
│ │ ├── UNMET DEPENDENCY block-stream *
│ │ ├── UNMET DEPENDENCY fstream ~0.1.8
│ │ └── UNMET DEPENDENCY inherits 1.x
│ └── which@1.0.3 
```

Not quite sure what the problem is but I'm gonna back out the "bundleDependencies" for now.

**Comment by zkat** [comment]
This seems to have been fixed. We've done a lot of installer work since this bug was posted, and `npm pack`-ing `node-gyp` after adding all its deps to `bundleDependencies` seems to be 🆗 🙆
