### ISSUE TITLE
Buffer failed scripts stderr/stdout until the end of a run

### ISSUE THREAD

**Issue by astro** [npm/npm#2228]
http://groups.google.com/group/npm-/browse_thread/thread/9e3f0b9ebc509eaf

> It'd be better if the lifecycle script output were repeated again at
> the bottom, though, and that's not too hard to do.  It just requires a
> little bit of refactoring how they get run, so that I can trap the
> output and pipe it to stdout/err.

**Comment by othiym23** [comment]
Closing as duplicate of #10491 and #9567. See those issues for how we've decided to deal with this UX issue. Thanks for your time!
