### ISSUE TITLE
npm install fails on non-published dependent modules

### ISSUE THREAD

**Issue by opichals** [npm/npm#2274]
Please see the repro at https://gist.github.com/775920

Situation: two modules
A and B
B dependencies match A

There are three .sh scripts. Only the install.sh works as expected.

```
    ./install.sh works (local 'npm install')
    ./global-install.sh doesn't ('npm install -g')
    ./link.sh doesn't ('npm link')
```

**Comment by zkat** [comment]
This doesn't look like a bug: `B` has a [_registry_ dependency on `A`](https://www.npmjs.com/package/A). You would need to use local deps in order to install `B` at all. So instead of `"A": ">=1.0.0"`, use `"A": "../B"`. This issue is also pretty ancient so I'm gonna close it.
