### ISSUE TITLE
npm rebuild dependencies

### ISSUE THREAD

**Issue by mariash** [npm/npm#2335]
Would be nice for npm rebuild to rebuild dependencies as well wtih rebuild-bundle config parameter set on.  Right now this stops it from doing so:

https://github.com/isaacs/npm/blob/master/lib/build.js#L115

**Comment by OmgImAlexis** [comment]
@mariash Is this still an issue in `npm v3`, if not this should be closed.

**Comment by busches** [comment]
@iarna as @OmgImAlexis mentioned, this should be fixed with `npm` 3, yes?
