### ISSUE TITLE
npm install --link does not work with git:// dependency URLs

### ISSUE THREAD

**Issue by per-gron** [npm/npm#2556]
## Steps to reproduce
- Create a new directory and add this `package.json` file to it:
  
  `{
    "name": "npm-test2",
    "version": "1.0.0",
    "dependencies": {
      "npm-test": "git://github.com/pereckerdal/npm-test.git"
    }
  }`
- In that directory, invoke `npm install --link`
## Expected result

The `npm-test` package should be installed.
## Actual result

npm spits out an error `404 'npm-test' is not in the npm registry.`
## Additional notes

Invoking `npm install`, without the `--link` flag, works as expected.

The same problem exists for git+ssh:// URLs

Here's a gist with npm-debug.log and npm output: https://gist.github.com/2972216

**Comment by DonRichards** [comment]
I also have the same issue. Trying to import a private gist file npm install git+ssh://gist@github.com:#######.git
