### ISSUE TITLE
npm-shrinkwrap.json ignored when npmrc specifies "link = true"

### ISSUE THREAD

**Issue by aadamowski** [npm/npm#2713]
When the npmrc file [specifies "link = true"](https://npmjs.org/doc/config.html#link), `npm install` ignores the current package's 
`npm-shrinkwrap.json` file. That's true even when starting from scratch (no globally installed anything).  

This problem is particularly biting on a Joyent SmartMachine, whose setup (including git-based deployment) is based on npm link option - there seems to be no way to make use of `npm-shrinkwrap.json` - deployed projects always get the latest versions of transitive dependencies.

**Comment by jharmelink** [comment]
+1
