### ISSUE TITLE
npm install -g hangs on Vagrant

### ISSUE THREAD

**Issue by ideasasylum** [npm/npm#2861]
Ok, so to avoid the problems with symlinks on Vagrant shared folders, I need to install the packages globally, but...
```
vagrant@urlpipe:~/urlpipe npm --loglevel verbose install -g
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   '--loglevel',
npm verb cli   'verbose',
npm verb cli   'install',
npm verb cli   '-g' ]
npm info using npm@1.1.62
npm info using node@v0.8.11
npm verb read json /usr/local/lib/package.json
npm verb read json /usr/local/lib/package.json
npm verb cache add [ '.', null ]
npm verb parsed url { pathname: '.', path: '.', href: '.' }
npm verb lock . /home/vagrant/.npm/3a52ce78-.lock
npm verb read json package.json
npm verb tar pack [ '/home/vagrant/tmp/npm-1380/1349728825091-0.9673088057897985/tmp.tgz',
npm verb tar pack   '.' ]
npm verb tarball /home/vagrant/tmp/npm-1380/1349728825091-0.9673088057897985/tmp.tgz
npm verb folder .
npm info prepublish UrlPipe@0.0.1
npm verb lock /home/vagrant/tmp/npm-1380/1349728825091-0.9673088057897985/tmp.tgz /home/vagrant/.npm/ce8ed442-25091-0-9673088057897985-tmp-tgz.lock
```
<<<<<<<<<<<<<<<<<< It hangs indefinitely at this point (10mins+)

~/urlpipe is a vagrant shared directory (host: Mountain Lion; guest: Ubuntu 12.04). This is the package file: https://github.com/ideasasylum/UrlPipe/blob/master/package.json

I've tried removing ~/.npm but it doesn't resolve the issue

Apart from the Vagrant symlink issue, local npm install proceeds correctly

Any ideas or suggestions?

**Comment by smikes** [comment]
Can this issue now be closed?

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as resolved / abandoned.
