### ISSUE TITLE
npm leaks DNS requests when using proxy

### ISSUE THREAD

**Issue by m0khtar** [npm/npm#2956]
Hi,

I'm in a corporate environment and trying to install socket.io, no chance so far.

npm install socket.io

I already did 
    npm config set proxy http://user:pass@xx.xx.xx.xx:xxxx to update the proxy
    npm config set registry "http://registry.npmjs.org/"
    npm cache clean

i also deleted the .npmrc file just to be sure.

I am able to run "npm update" because it generates 0 errors.
i see a double slash "\" on line 34. could it be that?

Any help would be appreciated :)

Log :

0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\\node.exe',
1 verbose cli   'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'socket.io' ]
2 info using npm@1.1.65
3 info using node@v0.8.14
4 verbose node symlink C:\Program Files\nodejs\node.exe
5 verbose read json C:\Program Files\nodejs\package.json
6 verbose read json C:\Program Files\nodejs\node_modules\npm\package.json
7 verbose read json C:\Program Files\nodejs\package.json
8 verbose cache add [ 'socket.io', null ]
9 silly cache add name=undefined spec="socket.io" args=["socket.io",null]
10 verbose parsed url { pathname: 'socket.io', path: 'socket.io', href: 'socket.io' }
11 silly lockFile 71475bfd-socket-io socket.io
12 verbose lock socket.io C:\Documents and Settings\xxx\Application Data\npm-cache\71475bfd-socket-io.lock
13 silly lockFile 71475bfd-socket-io socket.io
14 verbose addNamed [ 'socket.io', '' ]
15 verbose addNamed [ null, '' ]
16 silly lockFile c03de861-socket-io socket.io@
17 verbose lock socket.io@ C:\Documents and Settings\xxx\Application Data\npm-cache\c03de861-socket-io.lock
18 silly addNameRange { name: 'socket.io', range: '', hasData: false }
19 verbose url raw socket.io
20 verbose url resolving [ 'http://registry.npmjs.org/', './socket.io' ]
21 verbose url resolved http://registry.npmjs.org/socket.io
22 info trying registry request attempt 1 at 14:58:42
23 http GET http://registry.npmjs.org/socket.io
24 info retry will retry, error on last attempt: Error: getaddrinfo ENOENT
25 info trying registry request attempt 2 at 14:58:54
26 http GET http://registry.npmjs.org/socket.io
27 info retry will retry, error on last attempt: Error: getaddrinfo ENOENT
28 info trying registry request attempt 3 at 14:59:57
29 http GET http://registry.npmjs.org/socket.io
30 silly lockFile c03de861-socket-io socket.io@
31 error Error: getaddrinfo ENOENT
31 error     at errnoException (dns.js:31:11)
31 error     at Object.onanswer [as oncomplete](dns.js:123:16)
32 error If you need help, you may report this log at:
32 error     http://github.com/isaacs/npm/issues
32 error or email it to:
32 error     npm-@googlegroups.com
33 error System Windows_NT 5.2.3790
34 error command "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "socket.io"
35 error cwd C:\Program Files\nodejs
36 error node -v v0.8.14
37 error npm -v 1.1.65
38 error syscall getaddrinfo
39 error code ENOTFOUND
40 error errno ENOTFOUND
41 verbose exit [ 1, true ]

**Comment by smikes** [comment]
Do we know whether this is a bug in `npm` or in `request` ?

**Comment by busches** [comment]
Is this still an issue in the latest `npm@2` and `npm@3`?
