### ISSUE TITLE
Allow subdirectories within git repos in npm install 

### ISSUE THREAD

**Issue by SLaks** [npm/npm#2974]
I would like to be able to run `npm install` for a `package.json` file in a subdirectory of a git repo.

This would be useful for projects that use releases systems (such as [nzakas/parserlib](https://github.com/nzakas/parser-lib/blob/master/release/npm/package.json)), and for git repos that contain multiple npm packages .

Can this be added?

**Comment by AnmAtAnm** [comment]
Another +1.

**Comment by nevcos** [comment]
Another +1. Need to import other module that's not in the root and don't want to create a specific project for that module.

**Comment by lukaslehmann** [comment]
Another +1

**Comment by thelinuxlich** [comment]
+1

**Comment by coderhaoxin** [comment]
+1

**Comment by charliezhang** [comment]
strongly +1

**Comment by bttf** [comment]
+1

**Comment by kirill-konshin** [comment]
An example: https://github.com/pubnub/javascript/tree/develop/node.js - as you see, the actual code for NPM is located in `node.js` directory, not in the root of the repo. So if I need to install develop branch, the only way is to locally do `npm link`.

**Comment by sr78ger** [comment]
+1

**Comment by acedward** [comment]
+1

**Comment by eyphka** [comment]
+1

**Comment by gaye** [comment]
:+1:

**Comment by adam-si** [comment]
+1

**Comment by aikej** [comment]
+1

**Comment by JuHwon** [comment]
+1. would require it in a fork of the breeze node repo https://github.com/JuHwon/breeze.server.node

**Comment by xogeny** [comment]
+1 for me as well.  The issue I face is that I want to keep code in a private GitHub repository.  If I have one module per repository, I'll end up with tons of private repos which would cost a fortune.

**Comment by febeling** [comment]
There are the really big companies (FB, Google) which make the decision to keep software in monolithic repositories. And that's not a decision made out of ingnorance, I believe. I would make a lot of sense to support this model of working for others, too.

**Comment by kamilio** [comment]
I agree with @febeling 

I think it would make totally sense.

**Comment by tonyghita** [comment]
:+1: would clean up some thrift multi-module projects I have if we had this functionality

**Comment by goya** [comment]
+1 for this basic functionality

**Comment by lopesc** [comment]
+1.  We have more than one module per repository in our organisation.

**Comment by legomind** [comment]
+1 Absolutely needed for modules like [babel](https://github.com/babel/babel).

**Comment by jonatanpedersen** [comment]
+1 babel

**Comment by mking** [comment]
:+1: for me as well. To give another example, [Babel is a monorepo](https://github.com/babel/babel/blob/master/doc/design/monorepo.md). I think it would be good to accommodate this approach, since the users of a package might not have control over the format of the repo they want to use.

**Comment by brophdawg11** [comment]
:+1:

**Comment by meriturva** [comment]
+1

**Comment by qina83** [comment]
+1

**Comment by jonaskello** [comment]
+1

**Comment by gld1982ltd** [comment]
+1

**Comment by damien-otis** [comment]
+1

**Comment by tonyghita** [comment]
https://en.wikipedia.org/wiki/Bystander_effect

**Comment by piranna** [comment]
> https://en.wikipedia.org/wiki/Bystander_effect

Lol :-P

Take also in account that maybe the ones that can do it are not interested
on this feature... Me by example, I only started following it because my
company insisted on this feature, but as the only one with knowledges on
Node.js, I think this go against the npm philosophy...

**Comment by othiym23** [comment]
To confirm what @piranna said above, this isn't something that the npm CLI team is interested in adding to the tool. We _are_ interested in continuing to improve the existing Git support (by making it more robust, and by cherry-picking those features of Bower's git support that make sense for npm's users), but we're _not_ interested in adding more complexity and new classes of use cases. I know this makes it awkward to use npm with monorepos, but I'm much more interested in finding a more general solution to the monorepo problem (some useful suggestions are in this thread), but I don't think it makes sense to make the git dependency syntax harder to understand than it already is. As such, I'm closing this feature request.

**Comment by tcurdt** [comment]
@othiym23 I guess most of us are subscribed to this issue to figure out how get support for monorepos. So what are those `useful suggestions ... in this thread`?

Is monorepo support (`I'm much more interested in finding a more general solution to the monorepo problem`) tracked somewhere else?

**Comment by othiym23** [comment]
Primarily using package scripts to trigger subinstalls (still requires a `package.json` at root).

> Is monorepo support (`I'm much more interested in finding a more general solution to the monorepo problem`) tracked somewhere else?

It isn't. To be clear, monorepo support is not something that's on the CLI team's roadmap for the next 6-12 months. I'm interested in seeing better support for it within the CLI, but the team isn't going to have the time and attention to do it ourselves. For that reason, specific proposals (perhaps in the form of (prototype) code) are going to be more useful than generic requests for improved monorepo support.

**Comment by LinusU** [comment]
If it's of any interest, this is how the python `pip` installer did it. pypa/pip#1215

```text
git+https://git.repo/some_repo.git@egg=subdir&subdirectory=subdir_path
```

**Comment by bitdivine** [comment]
@LinusU I like it.  It's clean.  Perhaps I should not be surprised, given its heritage.

**Comment by akofman** [comment]
@othiym23, sorry to relaunch this thread but I didn’t understand how to use scripts in order to trigger sub installs. Is there a way to target a specific submodule with 
this solution ? 
I thought this was one of the goal of keeping submodules in a same repo but if we have to install all the submodules of the repo each time we install it, I don’t really get what’s the advantage. Did I missed something ?

**Comment by bitdivine** [comment]
@akofman 
> how to use scripts in order to trigger sub installs

I use a postinstall script in package.js.  So scripts.postinstall contains:

    "postinstall": "for dir in git_modules/[a-zA-Z0-9]* ; do printf \"=== Installing %s\\n\" \"$dir\" ; ( cd \"$dir\" ; npm install ; ) ; printf \"=== Installation exit code: %s for %s\\n\" $? \"$dir\" ; done "

It's a bit of a pain having to write `require('../git_modules/name')`.  One can get around that by having a directory tree like this:

    package.js
    node_modules/<non-git modules here>
    src/node_modules/<git modules here>
    src/lib/<code here>

I do that with a couple of large projects, as then I can just type `require("a-git-module")` or `require("a-non-git-module")` and it will just work, however it's a lot of scaffolding for a small project and it involves moving things around so I usually don't bother.

That doesn't answer the second half of your question but hopefully it's a start.

**Comment by mitar** [comment]
+1

**Comment by pygy** [comment]
From: http://stackoverflow.com/a/3651867

> A branch name can not:
>
> - Have a path component that begins with "."
> - Have a double dot ".."
> - Have an ASCII control character, "~", "^", ":" or SP, anywhere
> - End with a "/"
> - End with ".lock"
> - Contain a "\" (backslash

So `:` or `::` would work as separator:

`git://x.com/path/to/whatever#some-branch::/some/directory`

For the default branch : 

`git://x.com/path/to/whatever#::/some/directory`

**Comment by cristiandan** [comment]
+1 for this feature, hope It gets implemented either with '@' (python style) or with '::' delimitators .

**Comment by djMax** [comment]
I'm fairly confident this will never get implemented in npm. They'd rather you just publish the module (paid or otherwise). Maybe you would be better off getting it sorted out in yarn...

**Comment by cristiandan** [comment]
oh ... ok
thanks @djMax

**Comment by mightyiam** [comment]
There must be support for this, or at least some suggestion.

A common case I run into is that I run into a bug in some published package. I submit a pull request on that package's GitHub repo that fixes the bug. I can't wait for the maintainer to merge and publish that. So I install from my GitHub fork using a git url. This isn't possible with monorepos.

**Comment by Budry** [comment]
Hi, any progress with this? 
We have a lot of projects and we **very often** need to use master or concrete commit of some _"package"_ in monorepo and there isn't  _"easy/correct"_ way how to do this. It would be a very useful use something like this `npm install --save git://github.com/user/package/path/to/subfolder` (or any better format, but it doesn't matter for now). A lots of companies/projects migrate repositories into one big monorepos and this is realy need. **It is seriously big problem.**

**Comment by badeball** [comment]
> [..], but I don't think it makes sense to make the git dependency syntax harder to understand than it already is.

Everyone seems to assume that this information needs to go into the path. Why is that? Can there not be some object structure, with one attribute containing the URL and other attributes containing metadata about how to handle the repository, such as tag, branch, subdirectory?

**Comment by shai32** [comment]
Maybe we can use [submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules)?

**Comment by mightyiam** [comment]
Shai, I'm working on an open source monorepo and I am going to have to
solve this. Submodules seems to me like the way to go. If anyone would like
to contact me for a brainstorming session, I'll be up for it.

**Comment by shai32** [comment]
@mightyiam 
it might be good to intergrade it with [lerna](https://github.com/lerna/lerna)
it takes care on the linking between internal packages

**Comment by Andarist** [comment]
@zkat @iarna 
is there any chance this could be reconsidered, especially regarding the improved git support in npm5?

**Comment by clayne11** [comment]
Couldn't we just use a query parameter? This doesn't seem like a very hard problem to solve:

```
git://x.com/path/to/whatever#some-branch?path=/folder/path
```

**Comment by lukescott** [comment]
How about `git://x.com/path/to/whatever.git/folder/path` since `git://x.com/path/to/whatever.git` works. You can take the subpath after `.git/`.

**Comment by Laurian** [comment]
`git://` is essential when you fork something and fix it and then you wait for your PR to be accepted, but with monorepos/lerna that does not work as a path is required :/

**Comment by sinedsem** [comment]
I forked DefinitelyTyped and I want to add only one type as dependency. Why can't I just say:
`"@types/yandex-maps": "git://github.com/sinedsem/DefinitelyTyped.git/types/yandex-maps"`

**Comment by ghost** [comment]
There's a bugfix I need in the babel master branch that's not published yet. There's really no way for me to install https://github.com/babel/babel/tree/master/packages/babel-core as a dependency?

**Comment by avesus** [comment]
How to install a Yarn workspace subpackage from a GitHub repository? Usually we were using npm link for that. In NPM 5 some kind of local `file:` dependency style was added. What are best practices now after the whole world collapsed after migration from NPM 4 to NPM 5 and FB promoting their Yarn?..

**Comment by avesus** [comment]
@othiym23 are you really sure that
```
"scripts": {
  "postinstall": "mkdir BotBuilder; cd BotBuilder; git init; git remote add -f origin https://github.com/Microsoft/BotBuilder.git; git config core.sparseCheckout true; echo \"Node/core\" >> .git/info/sparse-checkout; git pull --depth=1 origin master; cd ..; npm i ./BotBuilder/Node/core/"
}
```
is a way to go?..
It's 2017.

**Comment by ghost** [comment]
@avesus 
Thanks for the clever workaround. It's even less maintainable for me, because I'll have to repeat it for like 8 different modules.

**Comment by bstro** [comment]
I am in the same boat as @errorx666 … there is a bug fix for the package `react-router-redux` which is tucked inside the master branch of `react-router` as a lerna module, and there's no real way to get at it with npm. :(

**Comment by mightyiam** [comment]
As for my own repositories, I have broken them apart into proper repositories. And I don't wish to hear the word monorepo again. As for managing multiple repositories with the same linting rules, testing frameworks, workflow tools, etc... There are better ways than a monorepo. Use `npm link`. Package up your common tools and install them as devDependencies of the various packages. Anything but a monorepo. Good luck.

**Comment by pelotom** [comment]
@mightyiam not to get too far off topic, but why the intense antipathy to monorepos?

**Comment by piranna** [comment]
> @mightyiam not to get too far off topic, but why the intense antipathy to monorepos?

Simplicity, I swear. One project is idempotent to one repo and viceversa, and if something is common to several other parts, modularize it and convert it an independent, reusable and standalone library. You know, KISS principle, UNIX principle and all this short of things...

By the one, I'm against monorepos, too.

**Comment by pelotom** [comment]
@piranna maybe you mean "isomorphic", not "idempotent"? This is a pretty hand-wavy explanation and I'm not sure I buy it. If you want to talk about the KISS principle, from the perspective of versioning a monorepo is the simplest option, and it allows features that require simultaneous changes to several packages to be encapsulated in a single PR.

**Comment by avesus** [comment]
@pelotom simultaneous changes to several packages are bad practice. Consider changing APIs in the same way developers implement database migrations: change first package without breaking old clients, and then publish changes to the dependents. It complicates thinking about code changes and leads to more commits and slower work, but KISS in modules worth it a lot

**Comment by pelotom** [comment]
@avesus 

> simultaneous changes to several packages are bad practice

[citation needed]

> It complicates thinking about code changes and leads to more commits and slower work

Agreed. So where are the concrete benefits that make this price worth paying? Be specific.

**Comment by lukescott** [comment]
> simultaneous changes to several packages are bad practice. 

@avesus  I think companies like Facebook and Google, as well as projects like Babel and istanbul, and many others would disagree with you. If this were the case lerna would not exist. I personally have also found it helpful in certain applications within my team. 

NPM only cares about package.json. When you install a package it pulls it from a centralized repository of hundreds of thousands of packages. I don't think it's that much of a stretch, or unreasonable, to install a package from a single Github repo containing a dozen packages.

**Comment by piranna** [comment]
> @piranna maybe you mean "isomorphic", not "idempotent"?

No, I wanted to mean idempotent. One project equals one repo, and one repo equals one project.

**Comment by mitar** [comment]
That's not what idempotent means.

**Comment by pelotom** [comment]
![youkeepusingthatword](https://user-images.githubusercontent.com/128019/31986028-cd6cde92-b91b-11e7-8219-ad6d4885116e.gif)

**Comment by jonaskello** [comment]
Perhaps this monorepo debate could be held somewhere else?

**Comment by azizhk** [comment]
It looks like npm's inability to support monorepos has made people hate monorepos than hate npm.

**Comment by mightyiam** [comment]
I feel much like @piranna.

Also, I'm an avid [Greenkeeper](https://greenkeeper.io/) user and you can forget about using it with monorepos.

**Comment by ghost** [comment]
@piranna 
This debate is basically prescriptivism versus descriptivism.  You're saying that people *shouldn't* be using monorepos.  We're saying that they *are* using monorepos, without regard to whether they *should* be, and therefore we (consumers of npm packages; not necessarily producers) need support for it.

**Comment by ptitjes** [comment]
So there is no solution ? Are we stuck with making manual installs ?

But isn't this just a change directory to do after the cloning ? Please npm folks !

**Comment by ptitjes** [comment]
@othiym23 The following are the parts that would need to be modified to make this work, am I right ?

https://github.com/npm/npm-package-arg/blob/master/npa.js#L218
https://github.com/zkat/pacote/blob/latest/lib/fetchers/git.js#L73

If that is the case, I might like to do a PR.

**Comment by jacksonrayhamilton** [comment]
@othiym23 will you please re-open this issue so we can open bounties for it on bountysource.com?

**Comment by bjankord** [comment]
Hi @zkat, @othiym23

There has been a lot of discussion on this issue and it seems the community has a need for this. A handful of ideas have been proposed from npm users which, IMO, are worth more input from the npm team.

From [using a separator which branch names cannot use](https://github.com/npm/npm/issues/2974#issuecomment-240672593) like `git://github.com/babel/babel.git#master::babel/packages/babel-core/` or [using a query param syntax](https://github.com/clayne11]) like `git://github.com/babel/babel.git#master?path=babel/packages/babel-core/`

It would be nice to get some more input from the npm team on these 😀

**Comment by ch1ll0ut1** [comment]
Please :(

**Comment by subpardaemon** [comment]
so this issue is now closed after

> There has been a lot of discussion on this issue and it seems the community has a need for this.

...without an actual solution?

seriously?

no wonder npm is considered a cussword in most programming circles.

**Comment by jacksonrayhamilton** [comment]
It’s pretty sad.  There seem to be plenty of people who would even write improvements for npm themselves (or we could pay them to do it), but the maintainers will not even respond to us.

**Comment by subpardaemon** [comment]
i mean now i have to scrub my entire repo and create a separate repo for all the separable packages of my project. if there was even a tiny goddamn HINT in the official "how to contribute packages" doc about npm's inability to handle monorepos then i'd have designed my repos accordingly.

it's still going to be a nightmare, a different project for each package in netbeans, and my system so far has about 15 packages... thanks a lot indeed.

**Comment by ptitjes** [comment]
@subpardaemon @jacksonrayhamilton If I understand the code correctly the main contribution and new tests are to be made on https://github.com/zkat/pacote and https://github.com/npm/npm-package-arg. Then there is not much to do on `npm` itself (maybe add a test case).

This would require to make a PR on both sides: `pacote` does the fetching of the package (in our case, from a git repository) given a *manifest* that is built by `npm-package-arg` from the parsing of a git url.

The difficulty is to convince both parties that this is a feature to have. Apart from @othiym23, we could also lobby @zkat (creator of `pacote`) and @iarna (that also contributed both the files I mentioned in https://github.com/npm/npm/issues/2974#issuecomment-340344154). Again, I'd be glad to contribute that.

**Comment by Brantron** [comment]
It would be nice if NPM would look at this as a potential win for their project vs a nuisance.

**Comment by matijs** [comment]
How would npm know about versions of individual packages inside a monorepo? Installing `@latest` might not always be what you want.

**Comment by lukescott** [comment]
> How would npm know about versions of individual packages inside a monorepo? Installing @latest might not always be what you want.

Since this is about installing individual monorepo packages within a Git repo, you would target a branch tag or commit.

90% of the time you want to install the individual packages off npm, which is what we do now. 10% of the time there is a bug fix for one of those packages and they haven't done a release yet. I'm experiencing this right now with [babel-plugin-istanbul](https://github.com/istanbuljs/babel-plugin-istanbul) and the arrow function coverage bug w/ Babel 7.

For a non-monorepo package you can simply point directly to the Github repo. This case is similar, but you want to scope it just to a single package within the repo.

For those that make monorepos they don't necessarily need this feature. It's for those that use projects that use monorepos. Telling them to not organize their projects into monorepos doesn't help people who make use of these projects.

**Comment by bjankord** [comment]
@othiym23 mentioned back in Jan 2016

> monorepo support is not something that's on the CLI team's roadmap for the next 6-12 months. I'm interested in seeing better support for it within the CLI, but the team isn't going to have the time and attention to do it ourselves. For that reason, specific proposals (perhaps in the form of (prototype) code) are going to be more useful than generic requests for improved monorepo support.

Its been about 25 months now. [People are interested in contributing PRs to get this working](https://github.com/npm/npm/issues/2974#issuecomment-361777241). Some additional guidance from the CLI team would be helpful.

If this issue seems to be making no traction with npm's CLI team, I'd encourage people interested in this feature to look at yarn instead.

There are a few issues on yarns repo about this feature:
* https://github.com/yarnpkg/yarn/issues/4725
* https://github.com/yarnpkg/yarn/issues/1570

Yarn also has an [RFC process](https://github.com/yarnpkg/rfcs/) which may offer a better discussion platform compared to this GitHub issue.

**Comment by Skorpyon** [comment]
This is why i hate JS, UI and all things related to JS community.
First time in my life i need install Vuikit from other branch and from monorepo /packages folder and i see that in 2013 people asked this feature and developers fucking people 5 years.
Haha. Fucking JS. Python forever.

**Comment by trusktr** [comment]
Haha, entertaining. :) 

Still though, this would be useful.
