### ISSUE TITLE
"npm install" stops without error

### ISSUE THREAD

**Issue by niyazpk** [npm/npm#2981]
Continuing from #2980, I ran `npm install` with the following package.json:

    {
      "name": "my-project-name",
      "version": "0.1.0",
      "devDependencies": {
        "grunt": "git://github.com/gruntjs/grunt.git#1f77fef26c564fe74e0b9860f055703649156113",
        "grunt-contrib-jshint": "~0.1.0",
        "grunt-contrib-nodeunit": "~0.1.0",
        "grunt-contrib-sass": "~0.2.1",
        "grunt-contrib-uglify": "~0.1.0",
        "grunt-contrib-watch": "git://github.com/gruntjs/grunt-contrib-watch.git#6360a36871d55a7a500f86e0ddd0fb9cd08f2773"
      }
    }

Here is the result:

    [C:\wamp\www\b3c]npm install

    [C:\wamp\www\b3c]

It waited for like 5 seconds and then ended.

**Comment by busches** [comment]
This is working fine on Windows 7 with version `3.10.5` of `npm` and git version `2.7.2.windows.1`
cc: @KenanY

**Comment by KenanY** [comment]
Closing as abandoned/probably-resolved-by-now.

**Comment by adteague** [comment]
I'm curious what the solution was, as I am experiencing the same issue now on my mac
