### ISSUE TITLE
EPERM on npm.commands.install

### ISSUE THREAD

**Issue by coreybutler** [npm/npm#3001]
I'm currently working on a simple node CLI program that prompts a user to install a package if it isn't already installed. Due to the nature of the framework this fits into, the particular install throwing errors is attempting a global installation. 

- Testing on Windows 8
- User account has administrative privileges

The offending code looks like:

```js
var npm = require('npm');
npm.load({
  registry: my_npm_registry,
  global: true
},function(){
  npm.commands.install('mypkg',function(_err,data){
    if (_err){
      console.log(_err);
    } else {
     console.log('success');
    }
  });
});
```

The result is:

```
c:\Users\Corey\Documents\workspace\node_modules\npm\node_modules\lockfile\lockfile.js:26
    throw er
          ^
Error: EPERM, mkdir 'c:\Program Files\nodejs\node_modules\mypkg'
```

Based on this, it seems the user account doesn't have the ability to create the directory. Seeing as it isn't an `EACCES` error, I figure it isn't a permission issue, but more the fact it is trying to install in `Program Files`.

However; when I try to install by typing `npm install mypkg -g`, it works.

I've sort of worked around this using the following:

```js
var exec = require('child_process').exec;

exec("npm --registry "+my_npm_registry+" install mypkg -g",function(error,out,err){
  if (error)
    console.log(error)
  else
     console.log(out);
});
```

The code above works. I don't understand why it would work as a child process, but not the first way. This seems like it is either a bug or I'm missing something.

**Comment by busches** [comment]
Is this still causing an issue for you in later versions of npm? The `npm` prefix on Windows defaults to the `C:\Users\%CurrentUser%\AppData\Roamin\npm` now a days instead of `Program Files` and should help avoid most of your issue.

**Comment by coreybutler** [comment]
@busches - I abandoned this long ago (issue is 4yrs old), so I don't really know. However; it's not safe to assume npm will always be in the roaming profile. In [nvm-windows](https://github.com/coreybutler/nvm-windows) users have a choice where it goes. I worked around it by building an admin elevation utility.

I'm going to close this since it is so old.

**Comment by busches** [comment]
@coreybutler you're correct, I should have said it defaults to roaming currently with the node.js installer and the user can always override it in their own configuration.
