### ISSUE TITLE
`npm unpublish` does not respect publishConfig setting for registry

### ISSUE THREAD

**Issue by jden** [npm/npm#3032]
Running `npm publish` in a package's directory will get registry settings by reading the publishConfig section of package.json. However, running `npm unpublish` does not look in `package.json` and instead uses the default global registry.

Would you accept a patch to make `npm unpublish`'s registry configuration registration behave like `npm publish`?

**Comment by dweidenfeld** [comment]
Is there some update on this?

**Comment by jden** [comment]
I no longer have the multiregistry use case, nor the time to put together this PR, although I am generally in favor of the npm client being multi-registry friendly and being able to control this via package.json.

**Comment by watilde** [comment]
I just tried to create a patch at https://github.com/npm/npm/pull/8013.

**Comment by othiym23** [comment]
@watilde's patch was a good one, and so is landed as 18ce0ecd2d94ad3af01e997f1396515892dd363c. I still think that for most per-project configuration, `.npmrc` is a better place to put this configuration, but now `npm publish` and `npm unpublish` use the exact same logic to set the configuration from `package.json`'s `publishConfig` stanza.
