### ISSUE TITLE
deprecate doesn't help npm update/npm outdated

### ISSUE THREAD

**Issue by ForbesLindesay** [npm/npm#3040]
It would be great if `npm update` and `npm outdated` gave you a warning message if you had modules installed that were deprecated, even if there's no more recent version available.  This would fix https://github.com/mishoo/UglifyJS2/issues/89

**Comment by destroyerofbuilds** [comment]
Agreed. The deprecated state of a package should be apparent to the developer.

**Comment by othiym23** [comment]
This would be a fantastic, simple-to-implement usability improvement, and were someone to put it together, the CLI team be happy to review and merge it. The team isn't going to have the resources to implement this ourselves in the next 6-12 months, though, so I'm putting `patch-welcome` on this issue _and_ closing it. Thanks for the suggestion, Forbes, and thanks to both of you for your time!
