### ISSUE TITLE
peerInvalid: Better error message from npm ls

### ISSUE THREAD

**Issue by isaacs** [npm/npm#3080]
It'd be good to have a more useful error message from `npm ls` in a peerInvalid situation.  It should show which package is depending on the invalid one, which package peerDepends on it, etc.

This may require gathering more information in the "problems" list that `read-installed` collects.

See: #3079 #3047

**Comment by smikes** [comment]
/cc @iarna as possibly obsoleted by `multi-stage-install`

No repro set is provided; no test exists.

**Comment by othiym23** [comment]
@smikes I think it would still be useful to have more contextual information about what's going on with `peerDependencies` when they're unsatisfied, even if `peerDependency` issues are only a warning. Added onto the road map via the `error-handling` label.
