### ISSUE TITLE
"npm ls" fails even if "npm install" is successful 

### ISSUE THREAD

**Issue by raymondfeng** [npm/npm#3082]
I'm seeing an issue with "npm ls" with node 0.8.18 and npm 1.2.2. 

Check out https://github.com/enjoyjava/npm-test, and run "npm install". Everything is good with exit code 0.

Now run "npm ls". I'm getting:

npm ERR! invalid: mongoose@3.5.4 /private/tmp/testnpm/node_modules/mongoose
npm ERR! not ok code 0

**Comment by OmgImAlexis** [comment]
Is this still an issue in `npm v3`, if not this should be closed.

**Comment by gdibble** [comment]
:information_desk_person: if anyone does npm install package and then npm ls and gets `invalid`, do make sure that the package-in-question is not also listed in `devDependencies`

**Comment by raymondfeng** [comment]
I tried npm 3 with https://github.com/raymondfeng/npm-test and it works for me. Feel free to close it.

**Comment by busches** [comment]
@KenanY the author of the issue mentions that the bug is resolved with npm 3, can this be closed?
