### ISSUE TITLE
npm link on windows

### ISSUE THREAD

**Issue by TimNZ** [npm/npm#3108]
Is the following correct behaviour on Win7?

```
c:\source\my_package
c:\source\my_app

cd \source\my_app
npm link ..\my_package

c:\source\my_package is copied to c:\users\xxxxxx\AppData\Roaming\npm\node_modules\my_package

symlink:
c:\users\xxxxxx\AppData\Roaming\npm\node_modules\my_package -> c:\source\my_app\node_modules\my_package
```
There is no mention in the documentation or output from npm link that the 'master' is now in App\Roaming.

This also screws up require resolution as the containing symlink dir (c:\source\my_app\node_modules) is  not checked for resolving requires in my_package.

Hey, this may be a limitation of symlinks, but I'm keen for solutions on how to best manage this.

**Comment by smikes** [comment]
Is this still a problem for you?


This looks like a bug report to me.  I will try to reproduce it with the current version of `node` on Windows.

**Comment by bakesteve** [comment]
following the same process I get the same result on win 8.1, node v0.12.0

**Comment by bakesteve** [comment]
however, running npm link, and then npm link <packageName> does work

**Comment by cztomsik** [comment]
The problem is that you don't have package.json (with filled name) in your testmodule directory.

**Comment by kmanion** [comment]
Hi @TimNZ , it looks like you've gotten some help with this issue. We're trying to close out some of the older support issues. Please don't hesitate to reopen if you are still running into this or email us at support@npmjs.com

Kiera, npm technical support

**Comment by danielkokott** [comment]
I'm also having this issue on Windows 10 using node v6.9.4 and npm v3.10.10.
Did you resolve it, @TimNZ?

**Comment by Shawn-Cao** [comment]
@danielkokott my experience on node 6.3 and npm 3.10 has been working on Windows 10.

There's a requirement that the linked local directory is a valid npm package (has proper package.json) , which tripped me and is probably the problem @TimNZ was facing.

**Comment by danielkokott** [comment]
I do have a package.json with a main and bin entry. What does it need to be proper?

**Comment by Shawn-Cao** [comment]
Sorry I missed the thread update earlier. I mean think of the linked package as a regular npm package served from your local. Make sure the local package is valid by publishing or use some validator like [this one](http://package-json-validator.com/).
Also make sure to link the package using package name, not directory name.

**Comment by TimNZ** [comment]
I do dev on OS X now, and the recommended two step 'npm link', and it works as expected.

It is very likely one of the potential causes raised by other commenters was the cause of the issue.

**Comment by danielkokott** [comment]
@Shawn-Cao Thanks for you reply. I'll try to validate my packages.

@TimNZ this is a Windows 10 issue. My code/packages work perfectly when doing a 'npm link' in Linux. So there is something different happening on Windows 10.
