### ISSUE TITLE
Bug in specialising config for publishing

### ISSUE THREAD

**Issue by mfncooper** [npm/npm#3121]
There's a bug in the way that the publishConfig is integrated into the config chain while a package is being published. It seems to me that the bug is really in ConfigChain, but I'm filing this here since it's the npm use case that hits it.

The problem starts with the creation of a new config object to include the publishConfig, here:

https://github.com/isaacs/npm/blob/master/lib/publish.js#L73

which is this line:

```
var pubConf = new Conf(npm.config)
```

What happens here is that we get a new Conf object that has the same config chain as npm.config. So far so good.

The problem is that while the config chain now works perfectly well for lookups, it does _not_ work for setting a value in a particular named config. That is, the following will result in an error, because there are no named configs in the new Conf object:

```
pubConf.set("foo", "bar", "user");
```

The named configs got lost in the creation of the new Conf object, because nobody copied the 'sources' field into the new Conf object.

The question is what's the best way to fix this. The 'sources' field is owned by ConfigChain, but that does not have a "copy constructor" semantic today. (There is a confusing call to the ProtoList constructor, passing in 'arguments', but that doesn't do anything with arguments either.) That said, it seems to me that the cleanest solution would be having the ConfigChain constructor copy (or simply retain?) the 'sources' field if a ConfigChain instance was passed in.

One other observation: I am running into this in our customisation of npm, but there is a comment in the `publish` code that seems to suggest that the same scenario could be hit within npm itself:

```
// don't modify the actual publishConfig object, in case we have
// to set a login token or some other data.
```

If such a login token were to be set without naming the config it is set in, everything works. If, however, that token needed to be set in a named config (e.g. so that it is saved in the user's config file), this same issue would be hit.

@isaacs I'm more than happy to provide a patch for this, since we need a fix pronto, but wanted to hear your thoughts on what you'd find an acceptable fix.

**Comment by smikes** [comment]
This bug has a repro set, and record of an approach to fixing it.  However, `npm` no longer uses `npmconf`, and `npmconf` has been folded directly into the `npm` repository, so I believe the repro set will need some work before it can be used.

Also, the previous was abandoned just about 2 years ago, so it will also need to be updated.
