### ISSUE TITLE
Ruby gem security changes

### ISSUE THREAD

**Issue by shesek** [npm/npm#3252]
I stumbled on a post [1] that talks about some security-related changes in Ruby Gems after the recent security issues they had, and I think the author has some good ideas that could be relevant to npm too. Just thought it might be interesting to start a discussion about that.

[1] http://cristianobetta.com/blog/2013/02/02/ruby-gems-are-not-safe-to-use/

**Comment by othiym23** [comment]
There are a lot of ideas in this issue, some of them quite good and still relevant, some of them not achievable given the current state of the JS package ecosystem. As currently filed, there's no one thing that the CLI team can act on here, which makes this an awkward thing to have around. I'm going to close this, with the recommendation that people who happen across it (or @shesek) who have requests for the specific feature enumerated in here open new feature requests that can be tracked, discussed (and closed) independently. Thanks for the detailed proposals and discussion, and thanks for your time!
