### ISSUE TITLE
process.title causing problem on OSX

### ISSUE THREAD

**Issue by imrehg** [npm/npm#3264]
Similar to issue #1289, v0.8.18 was working fine, while this error message shows up when running npm with v0.10.0 (on OSX 10.8.3, over ssh):

    _RegisterApplication(), FAILED TO establish the default connection to the WindowServer, _CGSDefaultConnection() is NULL.

The trouble is bin/npm-cli.js line 16, and commenting it out will get rid of the error message,

    process.title = "npm"

The weird stuff is that that line is originating in 8adbe4740661b0dc27418c4e8fba9c45fc756232, a year ago, so what else could have changed to bring the bug out again?

**Comment by KenanY** [comment]
@imrehg Can you confirm whether or not this is still an issue with modern versions of Node.js and `npm`?

**Comment by KenanY** [comment]
Closing as abandoned. Can reopen if this is still an issue.
