### ISSUE TITLE
Hide non-fatal errors, warnings, and build information unless running with the debug flag

### ISSUE THREAD

**Issue by balupton** [npm/npm#3270]
Running:

```
mkdir test
cd test
npm install iconv
```

Is an extremely scary and confusing experience for people who don't know that NPM is like the guest at the party that can puke all over the place, but still survive to live the next day.

For [DocPad](http://docpad.org), one of our target audiences is people inexperienced to node, and as npm install shows all these warnings, non-fatal errors, and the build information - we get contacted each week with people freaking out, and then us having to say, "did you try running docpad anyway? most errors are non fatal and docpad should still work fine" - we've actually had to add that line to our [install instructions](http://docpad.org/docs/install) to try and counter this.

This makes me wonder how much information we are [over-exposing](http://www.youtube.com/watch?v=EFvYb4cYSHE&feature=g-user-p&list=PL279M8GbNsetWIruMrdWczHWxZBuGco4x) to the user? Perhaps, like myself, they really don't care for all these warnings, non-fatal errors, and build information unless they explicitly want it with the `-d` flag?

**Comment by jedrichards** [comment]
There is a related issue here: https://github.com/npm/npm/issues/5809

**Comment by othiym23** [comment]
There are a number of newer feature requests that cover specific aspects of this proposal that we've marked as being things the CLI team intends to release itself (if nobody else gets to them first!). As such, this issue is superseded, so I'm going to close it. thanks to all for the discussion and your time!
