### ISSUE TITLE
Installing a package with empty name globally removes all global node modules

### ISSUE THREAD

**Issue by mmalecki** [npm/npm#3293]
I forgot to add a name to my package. This blew up my global node modules. Would not recommend.

Proposed fix: isaacs/npm#3292

**Comment by busches** [comment]
@nathan7 did you ever get around to fixing it for `npm link`? I also didn't see a test for this specific scenario.

**Comment by nathan7** [comment]
I don't think I ever did, no :(
Perhaps the current @npm/cli-team is interested in fixing that, though.
