### ISSUE TITLE
Update NPM to support package.json with UTF BOM

### ISSUE THREAD

**Issue by tracker1** [npm/npm#3358]
I had a package.json file that was saved in UTF-8 format with a Byte Order Marker (BOM)

using `npm install PACKAGENAME --save' was failing to update said package.json

Suggest updating npm to support files that start with a BOM.

**Comment by doggy8088** [comment]
@havard UTF-8 with BOM (Byte Order Mark) should be a valid text file on any platform.  Is it possible to reopen this issue?

**Comment by othiym23** [comment]
Depending on whether you're looking at the IETF, W3C, or TC39 standards for JSON, you'll get slightly different answers to this question, but the general guidance is that BOMs are *not* valid in JSON streams. See also <http://stackoverflow.com/questions/4990095/json-specification-and-usage-of-bom-charset-encoding>.

This behavior is not specific to npm, or even to Node. This is how almost all JS runtimes deal with JSON files. As such, we're not going to change it.

**Comment by doggy8088** [comment]
@othiym23 I understand now.  Thanks! :+1:

**Comment by iarna** [comment]
Sooo, `read-package-json` actually *does* support package.json files with BOMs. It's only the bits of npm that bypass the normal read mechanisms that fail (eg `install --save`, `uninstall --save`). As such, I actually do think this is a bug, one way or another.

**Comment by othiym23** [comment]
Good, find, @iarna! Weird, but good find.

Hmmm... Postel's law says that if we accept a kind of input somewhere, we should accept it everywhere, but I personally think that having it be possible to round-trip `package.json` through `JSON.parse` and `JSON.stringify` without making any interim changes idempotently.

The idea of `package.json` as a programmatically-modified artifact is one that's evolved over time. When I started using npm heavily back in 2011, pretty much everyone I knew was modifying it by hand. Now, we encourage people to use npm to change its contents as much as is practicable (and also frequently rewrite its contents from within npm). So, making what it is sure to be an unpopular suggestion, my feeling is that `stripBOM` should be removed from `read-package-json`, and we should consolidate on *not* supporting BOMs in `package.json` files, to be consistent with our goal of treating `package.json` as an artifact / manifest. What say you?

See also the discussion on #6600, where the artifactness of `package.json` is also a pertinent factor in the debate.

**Comment by iarna** [comment]
The fix for this is finally here– it landed in master as https://github.com/npm/npm/commit/28064e5070dbe38df5281a4a0e14364f4100aadc and will be in the 3.1.0 release.
