### ISSUE TITLE
Replace `lib/utils/tar.js` with an external module

### ISSUE THREAD

**Issue by ForbesLindesay** [npm/npm#3383]
I've created [tar-pack](https://npmjs.org/package/tar-pack) which is essentially the functionality from `lib/utils/tar.js` except that it doesn't read the `package.json` file (and thus doesn't pull package.json comments from single file modules).

It also defaults to `fstream-ignore` rather than `fstream-npm` to be more generic and less npm specific.  This can be overridden by doing `pack(require("fstream-npm")(folder), tarball, [options], cb)`

**Comment by othiym23** [comment]
The team has done some work on how [`.npmignore` and `files` work in npm](https://github.com/npm/npm/wiki/Files-and-Ignores) recently, and our conclusion is pretty much that `fstream` et al gotta go. There are all kinds of corner cases and irregularities in how the various pieces of inclusion and exclusion work in npm, and there’s way too much code doing what should be a pretty simple thing. As such, we’re much more likely to write a much-simplified, bespoke piece of logic to generate the list of files to be included in a package tarball ourselves.

In any case, `tar-pack` is useful, but probably isn’t what we’re going to end up using in the longer term, so I’m going to close this issue. Thanks for putting it together, and thanks for your time, as always, Forbes!
