### ISSUE TITLE
cache build binaries

### ISSUE THREAD

**Issue by dominictarr** [npm/npm#3388]
People have discussed how cool it would be to have distributable builds,
but there are a number of difficulties, regarding maintaining build servers,
and/or security.

But it seems like just caching built modules locally might be a great step in the right direction --
what are the obstacles in front of that?

**Comment by othiym23** [comment]
This is a great idea! It’s also a fair amount of work, for the following reasons, among others:

- There are a lot of ways about how `node-gyp` decides to build native modules that would work against useful caching, like not keeping track of the build system’s OS, distribution, V8 ABI version, and other salient bits of context of the build. Were the cache code able to do it, this would make it pretty useful for shared environments. Were the cache code not up to the job, it would expose users to a host of new and exotic edge cases that would make it worse than useless. So, it requires care.
- @orangemocha has a [proposal kicking around](https://github.com/nodejs/build/issues/151#issuecomment-157190988) to make a cloud-hosted, centrally managed quasi-SaaS version of `node-pre-gyp` to simplify, in particular, building native modules for Windows. This combined with that would be very effective in minimizing the amount of bandwidth and CPU time required by native modules for all.
- As I already mentioned, there are a lot of subtle issues implicit in caching built products that need to be nailed down, like invalidating the cache when the Node version is different, noticing when you’ve switched platforms, etc.

I think it would be fantastic to have something like this in the CLI, but the CLI team’s priorities are such that we can’t commit to working on something like this for the next 6-12 months. As such, it’s our current policy to close feature requests that we don’t intend to address near term, but the presence of `patch-welcome` on the (closed) feature request is to signal that this is work we’d be happy to support should someone have the time and energy to tackle it themselves. Thanks for the proposal, and thanks for your patience.
