### ISSUE TITLE
Would like way to specify man pages without package prefix

### ISSUE THREAD

**Issue by mcavage** [npm/npm#3395]
Hello,

High-order bit: <3 npm man pages.  Now...

Currently if I have a package foo, and I setup man pages in the package.json block like:

```
{
  "directories": {
    ...,
    "man": "./man"
  }
}
```

All my man pages (let's say foo) get copied into the $node_root/share/man/$section as `package-foo`, such that users need to run `man mark-foo`.  This is not obvious to people that are not from the node/npm world, so it would be lovely if there were a way to explicitly map these, like:

```
{
   "directories: { ... },
   "man": {
     "foo": "./man/foo.1",
     "bar": "./man/bar.1",
     ...
   }
}
```

i.e., like all the other npm mapping doodads.

**Comment by othiym23** [comment]
It's already a tiny minority of npm users who even suspect that manpages get installed as part of installing npm packages, and I think the subset of those users who are going to want to map explicitly to manpages in `package.json` is maybe you, and possibly @davepacheco 😉. I don't see there being general value to making this more configurable than it is, but I do think there would be a lot of value to evangelizing the existence of the man directory a little bit; it's always super nice when there are manpages for a package.

In any case, this wouldn't be something the CLI team would have any time to get to in the near future, so I'm going to close this feature request. Thanks for your time, and if you feel _really_ strongly about changing this, you can start a PR and we can discuss how it might make sense to incorporate over there.
