### ISSUE TITLE
npm version <newversion> partially fails if Git tag already exists

### ISSUE THREAD

**Issue by icetraxx** [npm/npm#3403]
npm version [major | minor | patch | build] throws an error, yet still increments and commits the new version. The error occurs when a tag already exists by the same name. This can easily become problematic when incrementing a version that is later decremented due to hard resets, checking out older files, etc. I suggest that npm version warns that a tag by the same name already exists, and continue with the increment operation.

Please see the screenshot for easy reproduction of this bug:
![screen-shot-2013-05-03-at-12 31 30-am](https://f.cloud.github.com/assets/4329071/458086/2e66bd24-b3c9-11e2-98e5-7a7122c02cb1.png)

**Comment by jasonkarns** [comment]
Just ran into this. I'm not sure I would consider this a warning. IMO, the fact that the tagging failed (which is expressly part of the desired commit+tag operation) means the operation as a whole failed. I would expect the commit to be rolled back. This approach has some prior art, as I believe bundler reverts the commit if the tagging fails.
