### ISSUE TITLE
Linking man pages silently fails

### ISSUE THREAD

**Issue by mathiasbynens** [npm/npm#3405]
`npm` doesn’t seem to install man pages for packages (using the `man` entry in `package.json`). I’ve checked using `npm install -g luamin --verbose`, and it does log the `linkMans` step, but `luamin.1` doesn’t show up in `/usr/local/share/man/man1` at all. Any instructions on how to debug this? Is there a better way to figure out where `npm` put the man pages, if anywhere?

Here’s an excerpt from the `npm install -g luamin --verbose` log:

```
[…]
npm info linkStuff luamin@0.2.5
npm verb linkBins luamin@0.2.5
npm verb link bins [ { luamin: 'bin/luamin' }, '/usr/local/bin', true ]
npm verb linkMans luamin@0.2.5
npm verb rebuildBundles luamin@0.2.5
npm verb rebuildBundles [ '.bin', 'luaparse' ]
[…]
```

([Here’s a link to luamin’s `package.json`](https://github.com/mathiasbynens/luamin/blob/master/package.json).)

Also, `man npm` etc. don’t work.

I’ve updated npm to v1.2.19 to try the latest fix for #109, but I’m still having the same issue.

**Comment by busches** [comment]
@KenanY this appears to have been fixed by @bengl's PR #7299
