### ISSUE TITLE
`npm ls` should not tag optional dependencies as extraneous

### ISSUE THREAD

**Issue by piscisaureus** [npm/npm#3464]
`npm ls` gives me this:

```
foobarbaz@0.0.1
├── bson@0.1.8
├── kerberos@0.0.2 extraneous
├── mongodb@1.3.5
```

However `kerberos` should not be marked extraneous since it is an optional dependency for `mongodb` and mongodb doesn't have it in it's node_modules folder.

npm already treats "normal" dependencies that way.

(npm v1.2.21 + node v0.10.7 on Windows 7)

**Comment by iarna** [comment]
npm@3 resolved this issue. Actually, versions of npm@2 may have too, but npm@3 definitely did!

**Comment by Aourin** [comment]
Just for anyone stumbling upon this with kerberos and specifically mongo, it might have been optional, but it is a peer dependecy now. With that said, it will work without the peerDep. The only issue I have come into was that `npm shrinkwrap` wont work with a bad peer dependency.
