### ISSUE TITLE
npm install python version check.

### ISSUE THREAD

**Issue by aGuyNamedJonas** [npm/npm#3467]
Original post:
https://github.com/joyent/node/issues/5527#issuecomment-18270834

tl;dr: Python version check in npm install would make the life of node.js beginners under Windows a lot easier although it seems to be rather an issue by gyp not by node.js.
Still a one liner that would make node.js even more fun to use :)

Thanks :)

**Comment by othiym23** [comment]
Closing as (more or less?) resolved elsewhere. Thanks to all, especially @TooTallNate, for their time!
