### ISSUE TITLE
npm install can be slow, is there a way to profile it to find root cases?

### ISSUE THREAD

**Issue by bhouston** [npm/npm#3468]
So we are a big user of npm but I am starting to notice that for continuous development, "npm install" is actually the slowest piece by quite a bit -- something like 80% of our CI test + deployment is just running "npm install".  I think this must be the case for a lot of other people.

My first suggestion is add performance tracing to npm so one can figure out where the slowness is.  Is it in the downloading of the packages from the npm repository?  (Also what is the speed of download in Mbps, so I can figure out if it is my bandwidth or whether it is npm's bandwidth.)  It is expanding the packages?  It is running the package installation functions?

It would also be great to know which packages in particular are responsible for the slow installs.  Then we could add tickets to those packages or address them ourselves.

Sorry if this is already dealt with somewhere but I couldn't find it.

BTW I should be clear, NPM rocks, thanks so much for this amazing tool.

**Comment by sheetweaver** [comment]
Could npm have some DNS-resolution issues? Is there anything "unusual" about the environment in which it runs ssh? I'm dealing with a problem where npm hangs/fails and/or takes a really long time to download, while the underlying git pull goes much more quickly.

http://stackoverflow.com/questions/29359688/npm-ssh-error-doesnt-replicate-from-shell

**Comment by sheetweaver** [comment]
Aha --- so I put our server into /etc/hosts and it sped up beautifully! Is npm doing something strange with dns? dnssec?

**Comment by smikes** [comment]
@sheetweaver there is a known bug in node >= 0.11 and npm < 2.8.2 that might have been biting you, but I don't know why putting the local server into /etc/hosts would help...

**Comment by joeyhub** [comment]
You always want to use strace for this kind of problem.

**Comment by slavafomin** [comment]
Hello, I'm having a situation on one of our developer's machine where npm is taking unreal amount of time to install dependencies. On my machine cold install takes no more that 1 minute, however, on this machine it could take half an hour. Is there a way to benchmark the installation process and to find the bottleneck? Thank you!

**Comment by zablose** [comment]
Had the same problem, "npm install" took ages.
Solved by changing DNS from ISP to 8.8.8.8

Hints: VBox, Debian, /etc/resolv.conf

**Comment by gbaumgart** [comment]
same here, Node.Js renders unusable slow, even on high power computers. This happens in large project directories where many folders have their own node_modules (thanks to the unresolved mess of Node.JS it self, demanding npm install in every damn folder)

**Comment by bhouston** [comment]
I'm closing this bug as I understand npm3 had a better dedup strategy.

**Comment by theajr** [comment]
You can use "Yarn" instead of npm to install packages. It is very faster.
