### ISSUE TITLE
Make stdout redirectable

### ISSUE THREAD

**Issue by jnordberg** [npm/npm#3492]
Moving this out from pr #3438 

I propose to make the following changes to npm and npmlog to make the output going to 
stdout when installing, searching, etc redirectable when using npm programmatically.

1) Extend the npmlog module with a print method that have a configurable stream which defaults to stdout.

2) Add a outstream option to npm and replace all calls to console.log with log.print

**Comment by othiym23** [comment]
Given that:

- both Windows and Unix provide standard, console-level tools that support manipulating where `stdout` and `stderr` get routed, and
- the current programmatic API for npm is unsupported for use outside of npm's own code base

this isn't something that the team is going to change. Having command-level output go to `stdout` and diagnostic output go to `stderr` is a pretty hard convention of npm, and when used as a child process, there are better ways to control where the two kinds of output are sent. Thanks for your time!
