### ISSUE TITLE
npm install {something thats in .dependencies}

### ISSUE THREAD

**Issue by jkroso** [npm/npm#3504]
imho should behave the same as `npm install {something thats in .devdependencies}` what that behaviour is I don't care about

**Comment by smikes** [comment]
Confirmed that this bug is still present in `npm@next`, 2.5.1 as of today (2015-Feb-08).

/cc @iarna may be relevant to `multi-stage-install`

**Comment by ehsalazar** [comment]
Fixed with `npm@3`. If you [update](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) and continue to experience an issue, please let us know. We'll be happy to look into it.
