### ISSUE TITLE
NPM with dry run for testing?

### ISSUE THREAD

**Issue by moimikey** [npm/npm#3505]
Was this a feature that used to exist or will exist eventually? I'm in the midst of writing a shell script with a dry-run option and wanted to pipe that action to NPM.

Thanks

**Comment by BorePlusPlus** [comment]
:+1:

**Comment by BorePlusPlus** [comment]
I would be interested in having a dry run option for install `npm install --dry-run` which would print out what would npm install if it was to run the command. I'd find it useful in my docker workflow. 

Is there any desire for such an option? If I spend some time to implement it, does it stand a chance of being merged or should I do it as a standalone project?

Cheers

**Comment by moimikey** [comment]
and 2 years later, i'm still interested as well :)

**Comment by othiym23** [comment]
You're in luck, because a version of `--dry-run` is included in the `multi-stage` branch of npm, which will someday soon become `npm@3`.

**Comment by BorePlusPlus** [comment]
Nice to hear that. Any approximate timeline as to when this may happen?

**Comment by othiym23** [comment]
See #7774 for what needs to be done before we can put `npm@3` into beta.

**Comment by BorePlusPlus** [comment]
Cool - cheers.

**Comment by iarna** [comment]
Closing this as fixed in [npm/npm#multi-stage](https://github.com/npm/npm/tree/multi-stage)

**Comment by moimikey** [comment]
amazing! thanks!
