### ISSUE TITLE
npm install does NOT respect npm-shrinkwrap.json when it asks for a module upgrade

### ISSUE THREAD

**Issue by strk** [npm/npm#3523]
When a module that satisfies package.json is present, npm install will NOT upgrade it even if npm-shrinkwrap.json specifies an higher version.

I'd think it's a bug, given shinkwrap is meant to give control to the outermost module packager.

**Comment by othiym23** [comment]
@smikes so reclassified, but you might want to double-check with @iarna, because I think this is something that `multi-stage` may address.

**Comment by ehsalazar** [comment]
Fixed with `npm@3`. If you [update](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) and continue to experience an issue, please let us know. We'll be happy to look into it.
