### ISSUE TITLE
NPM leaves an empty tmp directory after installing a module

### ISSUE THREAD

**Issue by aimnadze** [npm/npm#3544]
After installing an addon with `npm install someaddon` an empty `tmp` folder remains in the current directory. That's not a huge problem, I basically do `rmdir tmp` after every `npm install`, but I think deleting it automatically would be nice.

**Comment by rmg** [comment]
I've recently switched from ephemeral to persistent CI environments and the leftover tmp directories/files consume all my inodes in under 24 hours. It's very annoying.

**Comment by peterjmit** [comment]
I have just run into this in our CI environment. On one of our build servers npm had left behind 18gb of files (named similarly to examples provided by @litmit)

**Comment by davisjam** [comment]
This definitely still happens on my Ubuntu 16 machine.

Can it be re-opened and investigated?
