### ISSUE TITLE
npm config https proxy value not used for git+https dependencies

### ISSUE THREAD

**Issue by explunit** [npm/npm#3559]
**Steps to reproduce:**
1. do **not** have https_proxy environment variable set in your host OS
2. Set the https proxy using the `npm config set https-proxy` command
3. `npm install jsdoc@3.2.0-dev` (or any module that has git+https dependencies)

**Expected result:** the proxy configuration in npm config is passed to the spawned git process

**Actual result:** the git process does not use the configured proxy information and an error such as this occurs:

```
npm ERR! git fetch -a origin (https://github.com/jsdoc3/markdown-js.git) 
error: Failed connect to github.com:443; 
Connection timed out while accessing https://github.com/jsdoc3/markdown-js.git/info/refs?service=git-upload-pack
```

**Workaround:** set the https_proxy environment variable in your host OS instead of trying to use the `npm config set https-proxy` command

**Comment by raptoria** [comment]
+1

**Comment by othiym23** [comment]
It would be extremely helpful to have this set up automatically, I agree. The CLI team will get to this as part of our initiative to improve the CLI's integration with Git, but we may not get to it for a little while, so if somebody else wants to fix it first, we'd be happy to offer time and expertise on how all of this is wired together. Thanks for your time and patience!

**Comment by natejgardner** [comment]
Any updates on this? This issue makes npm pretty difficult to use behind a corporate proxy.

**Comment by muehan** [comment]
yes it would be very helpful. proxy makes life hard and missing configuration possabilities doesn't help
