### ISSUE TITLE
npm-shrinkwrap.json handles metadata inconsistently

### ISSUE THREAD

**Issue by shaneholder** [npm/npm#3581]
If npm resolves a file from a registry when shrinkwrap is run a "resolved" property is added to the npm-shrinkwrap.json file.  If npm finds that the file is in the cache then this property is not written.

npm cache clear
npm init
npm install winston
npm shrinkwrap
*check shrinkwrap file and see "resolved" properties*
rm -rf node_modules npm-shrinkwrap.json
npm install winston
npm shrinkwrap
*check shrinkwrap file and see "resolved" properties do not exist*

It seems that npm shrinkwrap should generate the same output regardless of if the file came from the cache or if the file came from the registry.  This becomes more important if one is mixing private and public registries as it seems that the resolved property is used to locate a dependency.

**Comment by donaldpipowitch** [comment]
We stumbled over the same problems as the angular guys (again) in https://github.com/Automattic/engine.io-client/issues/370. These issues seem to be related and they have long discussions about this problem as you can see in their commits.

**Comment by othiym23** [comment]
This has been moved to the [npm roadmap](https://github.com/npm/npm/wiki/Roadmap), which we're using instead of the confusing `next-*` labels now.

**Comment by glenjamin** [comment]
fwiw, we've been using https://www.npmjs.com/package/shonkwrap to handle this for a while now and not really run into any issues.

**Comment by othiym23** [comment]
This thread is long and covers a lot of ground, but I believe the original issue of the opener (that is, `resolved` fields come and go in `npm-shrinkwrap.json`) has been addressed within `npm@2` and `npm@3`. There are a bunch of other possible feature requests and inconsistencies mentioned in this thread, and that makes it tough to act on any of them in a coherent way, so I'm going to close this issue, and if you think there's an outstanding issue with shrinkwrap that isn't covered by issues with the [`shrinkwrap` label](https://github.com/npm/npm/issues?q=label%3Ashrinkwrap), please open new issues.

**Comment by vkrol** [comment]
The behavior from the issue description continues to occur in the npm@3.8.0.

> that is, resolved fields come and go in npm-shrinkwrap.json

@othiym23 please, can you reopen this issue?

**Comment by mockdeep** [comment]
I'm seeing the same issue. Shrinkwrapping on one computer differs from another:

```json
"dependencies": {
  "babel-code-frame": {
    "version": "6.7.2",
      "from": "babel-code-frame@>=6.7.2 <7.0.0"
    }
  },
  ...
}
```

Becomes:

```json
"dependencies": {
  "babel-code-frame": {
    "version": "6.7.2",
    "from": "babel-code-frame@6.7.2",
    "resolved": "https://registry.npmjs.org/babel-code-frame/-/babel-code-frame-6.7.2.tgz"
  },
  ...
}
```

The shorter version is definitely preferable, since otherwise it ends up being TMI, and verifying changelogs on updated packages is more of a headache, especially since Github will often not even show the lengthy diff.

**Comment by brianpchsu** [comment]
I also have the same issue with npm @3.10.3. Basically, I just update my project number in package.json, but somehow the dependencies verion in shrinkwrap.json changed as well. 

From: 
```
"concat-stream": {
      "version": "1.4.10",
      "from": "concat-stream@>=1.4.7 <1.5.0",
      "resolved": "https://registry.npmjs.org/concat-stream/-/concat-stream-1.4.10.tgz"
    },
    "connect-multiparty": {
      "version": "2.0.0",
      "from": "connect-multiparty@>=2.0.0 <3.0.0",
   ...
    },
```

To:
```
"concat-stream": {
      "version": "1.4.10",
      "from": "concat-stream@>=1.4.7 <1.5.0",
      "resolved": "https://registry.npmjs.org/concat-stream/-/concat-stream-1.4.10.tgz"
    },
    "connect-multiparty": {
      "version": "2.0.0",
      "from": "connect-multiparty@latest",
    },
```
