### ISSUE TITLE
Potential bug with shrinkwrapped dependencies

### ISSUE THREAD

**Issue by jmreidy** [npm/npm#3675]
Grunt has  `async` as a dependency. The weird behavior is the following:

`npm install --save-dev async@0.1.22` - async is installed as a dependency.
`npm install --save grunt` - grunt is installed; it does *not* install async as a dependency for itself (ie grunt/node_modules/async does not exist)

`npm shrinkwrap` then (correctly) does not include async as a dependency for grunt, since it's not in grunt's node_modules directory. But that's obviously a problem for `npm install --production`.

**Comment by othiym23** [comment]
So noted, but I'm also going to add this to the multi-stage install milestone (att'n @iarna) so it gets looked at soonish.

**Comment by iarna** [comment]
This is now fixed in the [npm/npm#multi-stage](https://github.com/npm/npm/tree/multi-stage) branch.
