### ISSUE TITLE
npm dedupe doesn't handle explicit urls

### ISSUE THREAD

**Issue by jkroso** [npm/npm#3680]
a few of my packages depend on 

```json
{"when": "http://github.com/jkroso/when/tarball/3.0.0"}
```
but after running `npm dedupe` they end up with the the npm.org "when" module. I'm pretty sure this worked fine only a week ago so probably just a regression.

I'm running node@v0.10.13 and npm@1.3.2

**Comment by iarna** [comment]
npm@3, as a consequence of its design, does not suffer from these issues. So I'm going to close this as completed (even if that did happen by a happy accident).
