### ISSUE TITLE
idea: save a version's git commit in registry also

### ISSUE THREAD

**Issue by dominictarr** [npm/npm#3716]
It could be very handy, when it comes time to have signed packages,
if you knew what git commit a version was published from.

The vast majority of npm packages where developed in git,
so it should be pretty simple to do so.

Then, you could sign the combination of the tarball shasum and the git commit.

You'd have a much more useful view into exactly the code that is in the package.

/cc @hij1nx

**Comment by rmg** [comment]
Was/is `gitHead` a bug? I use it regularly to fill the gap of not being able to append the commit as metadata (`+ga1b2c3d`) to the version and it would be a shame if it was "fixed" :-(

**Comment by othiym23** [comment]
@rmg you'd have to get @isaacs to explain why `gitHead` made an appearance in the first place, but you can rest easy, because there aren't any plans to remove it anytime soon.

**Comment by othiym23** [comment]
I'm going to consider this resolved – npm's VCS support is pretty much exclusively for Git across the board, and while I'm definitely not opposed to adding support for other VCSes (long-time Hg fan here), it's also very, very far from the head of the priority list for the team to add support (send us your patches, darcs users!). `gitHead`'s origins are mysterious, but as I noted above, we have no intention of removing it, and while it's not safe to rely on it for provenance, it's a useful signal all the same. Use it in good health! Thanks for your time and patience.
