### ISSUE TITLE
Prefix directory owner overrides user setting

### ISSUE THREAD

**Issue by TrevorBurnham** [npm/npm#3778]
The documentation states that the default config for `'user'` is `'nobody'`. So I was surprised and perplex when I found that my scripts ran as root by default:

    $ npm get user
    0

I did some digging into the source to find that, except in global mode, the default `user` config will actually be the owner of the npm prefix directory: https://github.com/isaacs/npm/blob/master/lib/npm.js#L402-L423 In my case (as is common for OS X folks) that directory is `/usr/local/` and it's owned by the root. So the `'nobody'` default only matters in global mode:

    $ npm get user -g
    nobody

This is pretty counterintuitive, particularly in the context of running scripts. From the [script docs](https://github.com/isaacs/npm/blob/master/doc/misc/npm-scripts.md#user):

> If npm was invoked with root privileges, then it will change the uid to the user account or uid specified by the `user` config, which defaults to nobody. Set the `unsafe-perm` flag to run scripts with root privileges.

But that doesn't seem to be the case. In a project with `"scripts": { "whoami": "echo \"$(whoami)\"" }`:

    $ sudo npm get unsafe-perm
    false
    $ sudo npm run-script whoami
    root

I'm not sure what the solution here is. I could own my `/usr/local` dir rather than just giving myself owner-like privileges in it, but letting root own it isn't an unusual or (I think) particularly crazy pattern. Why is it necessary for npm to override the `user` config in non-global mode?

**Comment by othiym23** [comment]
Closing as resolved by the passage of time; the code has been changed around this numerous times, and as far as the team was able to establish when examining the code, the current behavior is to use either the UID associated with the running process or the UID set in configuration. Some of the functionality that creates directories and writes files to disk does look at the permissions set on the current or parent directory, but that behavior no longer is applied to child processes run as part of the lifecycle. Thanks for your time and patience!
