### ISSUE TITLE
NPM should check peer dependencies after all install/update tasks

### ISSUE THREAD

**Issue by vojtajina** [npm/npm#3803]
Karma, Grunt and other projects support plugins.

Say I installed "karma" and "plugin-a" both in version that worked with each other.

Now, I wanna update, both of them, assuming the next version of "karma" does not work with the current version of "plugin-a" (I need to update the plugin too in order to satisfy the peer dependency).

There's no way except removing the modules first.

How about if NPM checked after installing/updating all packages, instead of immediately after each install?

**Comment by iarna** [comment]
Closing this as fixed in [npm/npm#multi-stage](https://github.com/npm/npm/tree/multi-stage).
