### ISSUE TITLE
"npm link <package>" fails with EPERM on Windows

### ISSUE THREAD

**Issue by JPGygax68** [npm/npm#3861]
(using Windows 8)

It seems this same issue has appeared on Bower and was fixed there:

https://github.com/bower/bower/issues/472

Thanks,

-- Jean-Pierre

**Comment by nmschulte** [comment]
I would get `EPERM` and `ENOENT` errors with a sibling+child-style linked dependency; in the end it seems I was actually running into issue #10343, not this one (#3861).  My linked dependency structure was like shazron's comment about Apache Cordova:

https://github.com/npm/npm/issues/10343#issuecomment-253358042

**Comment by phpdeveloperbalaji** [comment]
Am also facing the same issue.. But the above solutions did not work. Seems there is issue in extracting the tarball. Can anyone post the solution?
![error](https://cloud.githubusercontent.com/assets/15012682/21400480/888f24c2-c7b0-11e6-9c5c-50bb78c289f5.PNG)

**Comment by johntemyra** [comment]
Installing npm-junction did it for me! 
Thanks JPGygax68!
