### ISSUE TITLE
Impossible to install ungit on W7 with npm

### ISSUE THREAD

**Issue by fxbenard** [npm/npm#3865]
Impossible to install on W7 after a

npm install -g ungit

The log i get:

npm ERR! Error: spawn ENOENT
npm ERR! at errnoException (child_process.js:980:11)
npm ERR! at Process.ChildProcess._handle.onexit (child_process.js:771:34)
npm ERR! If you need help, you may report this log at:
npm ERR! http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR! npm-@googlegroups.com

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nod
ejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "ungit"
npm ERR! cwd C:\Users\Nous
npm ERR! node -v v0.10.18
npm ERR! npm -v 1.3.8
npm ERR! syscall spawn
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR! C:\Users\Nous\npm-debug.log
npm ERR! not ok code 0

**Comment by busches** [comment]
@fxbenard are you still facing this issue with newer versions of `node`, `npm`, or `git`? Running `npm install -g ungit` works fine on Windows 7 with npm `3.10.5`, node `6.3.0` and git `2.7.2.windows.1`

**Comment by fxbenard** [comment]
Indeed it works on W10 with last versions
