### ISSUE TITLE
have npm report the error with a package.json

### ISSUE THREAD

**Issue by Pomax** [npm/npm#3869]
since npm relies on a well formatted package.json file, it would be nice if it could report the actual error it sees when trying to parse a bad package.json rather than merely reporting that there is some error without saying which line/column or the type of error encountered. If there is a JSON parse error perhaps the package.json file could be thrown at jshint to get the precise error?

**Comment by ilanbiala** [comment]
Any progress on this? Seems like something so simple but so important when all that is usually missing is a comma or something visually insignificant.

**Comment by othiym23** [comment]
Yes! There has been! @smikes has done is all a huge favor!

Closed by abdd040da90932535472f593d5433a67ee074801. This is included in `npm@2.7.1`, which is the version currently being tested (`npm@next`).
