### ISSUE TITLE
npm install --production should ignore devDependencies in the shrinkwrap file

### ISSUE THREAD

**Issue by bobzoller** [npm/npm#3881]
We use shrinkwrap to manage versions for both our dependencies and our devDependencies (so that our eng team and our CI server all install the same versions), but in production we don't want to install devDependencies.

Currently `npm install --production` blindly uses the shrinkwrap file and installs everything listed in it.  Would you accept a pull request that makes `npm install --production` ignore the devDependencies listed in the shrinkwrap file?

**Comment by jonstorer** [comment]
@jeffjo how have you included `npm prune --production` in your deployment flow? In my research, in order to prune, the node modules need to be installed. So, what's the point of pruning out dev modules if they're already installed.

**Comment by estk** [comment]
This is pretty aggravating that this is not possible without hacks.

**Comment by jonstorer** [comment]
:+1:

**Comment by kevinohara80** [comment]
Has anyone found a reasonable workaround for this? We deploy our app to Heroku which runs an `npm install --production`. We have a shrinkwrap file in there that is generated with `--dev` so it can lock down the dependency tree for our front-end build modules along with the server-side modules.

Our Heroku builds are timing out trying to install and compile the packages that are included in our devDependencies.

WRT the `npm prune --production` hack, this won't work for us as we need to skip the install of devDependencies altogether.

**Anyone have a preinstall script hack or some other crafty workaround?**

**Comment by jonstorer** [comment]
Short answer - use heroku npm caching and cross your fingers.

**Comment by danlash** [comment]
We are also seeing the devDependencies get unbuilt, rebuilt, then pruned on Heroku since we've started using shrinkwrap. It has increased our deployment times significantly.

**Comment by fantapop** [comment]
This just bit me.  For now, I'm going to prune out the prod dependencies.

**Comment by mhagmajer** [comment]
+1

**Comment by i-a-n** [comment]
Any updates or workarounds for this?

I'm surprised a tool invented to manage apps being deployed to production wouldn't honor the `--production` convention.

**Comment by MitMaro** [comment]
I think #10073 added this feature and will be in the next release of npm.

**Comment by i-a-n** [comment]
Nice find, @MitMaro! Thanks much.
