### ISSUE TITLE
`npm shrinkwrap` doesn't detect deduped deps across symlink boundaries?

### ISSUE THREAD

**Issue by aseemk** [npm/npm#3886]
The title is my best guess at determining the exact issue, but I could be wrong.

Take this example dep graph:

```
foo
├── methods
└─┬ bar
  └─┬ connect
    ├── methods
    ├── ...
```

The specific dep examples (`connect` and `methods`) here aren't relevant; any deps A → B will do.

If I remove `connect`'s local `methods` copy from its `node_modules`…

```
foo
├── methods
└─┬ bar
  └─┬ connect
    ├── ... (no methods)
```

…and I run `npm shrinkwrap`, it works.

**But if I change `bar` to be a symlink instead…**

```
foo
├── methods
└─┬ bar -> /some/path
  └─┬ connect
    ├── ... (no methods)
```

Then `npm shrinkwrap` thinks `connect` is missing its `methods` dependency:

```
$ npm shrinkwrap
npm ERR! Error: Problems were encountered
npm ERR! Please correct and try again.
npm ERR! missing: methods@0.0.1, required by connect@2.9.0
```

Hopefully this isn't by design. Does npm traverse folders in a way that sometimes doesn't work across symlink boundaries?

**Comment by moll** [comment]
Been having the same problem.
One workaround seems to be to hardlink directories, but they might cause other problems. I'm afraid to try `npm rm hardlinked-module`. That'll probably delete the source files in addition to the hardlink.

**Comment by danielgatis** [comment]
Hi, same here.
Anyone knows how to workaround this issue?
