### ISSUE TITLE
Maximum number of concurrent connections

### ISSUE THREAD

**Issue by sonata82** [npm/npm#3911]
It would be good to have a parameter or configuration variable to set the maximum number of concurrent connections npm uses.

Our corporate proxy doesn't allow too many connections from one peer. This causes npm install to fail. Setting a maximum would of course take longer, but stop the blocking from our proxy.

**Comment by boutell** [comment]
Those requiring temporary relief when this issue comes up with regard to installing private modules over ssh should check out the MaxStartups option to sshd. See "man sshd_config" for more information.

**Comment by mvaled** [comment]
+1

**Comment by foxx** [comment]
Any word on this?

**Comment by travisfischer** [comment]
Encountering this specifically while trying to install on a guest VMWare Ubuntu vm. Do not encounter it when running the same install on the host OSX machine. Would really appreciate a sloution. 

@boutell: Does increasing MaxStartups solve this in certain cases? I can't seem to get even that to help in my case.

Any other known work arounds?

**Comment by IngwiePhoenix** [comment]
+1 - and, any updates? NPM seems super slow when updating, since its throwing out 20+ requests at once...id like to limit that, since i am pretty sure my school's internet is not much of a connection-friend. o.o

**Comment by othiym23** [comment]
Hey! Wow! Cool! One that's done! This was landed in 910f9accf398466b8497952bee9f566ab50ade8c, which is included in the latest `npm@lts` and `npm@3` releases, and while we have plans to further improve npm's network utilization, this is a decent start.
