### ISSUE TITLE
Flavors like ports or portage for optional features

### ISSUE THREAD

**Issue by jansegre** [npm/npm#3933]
This is not an issue it's a feature I've been thinking that would allow fixing some workarounds I've seen on some packages.

The issue this feature proposes to address is when a package is capable of exposing some optional features only on the presence of certain dependencies. This is different from `optionalDependencies`. The idea is to allow __required__ dependencies for __optional__ functionality, as opposed to __optional__ dependencies for __required__ functionality.

The configuration on package.json could be something as follows:

    {
      name: 'foobar',
      version: '0.0.1',
      flavorDepenendcies: {
        mysql: 'mysql@2.0.0-alpha9',
      }
    }

This foobar package could be installed with or without the `mysql` flavor, like:

    npm install foobar+mysql

As it is common on `ports` (BSD/Mac OS X). Also another inspiration for this feature would be gentoo's `portage` and it's `USE` flags.

I'd like to know if more people find this useful.

Also, only overlooked the existing issues, I didn't dig deep to see if this has been brought up before.

**Comment by iarna** [comment]
The combinations of options in `package.json` are complex enough that the cli team is very conservative about adding new ones. I don't see this as adding any advantages over just having plugins and having users install those, eg `npm install foobar-mysql`, or even telling users to run `npm install mysql` if they want mysql support.

As I don't see the benefits as being sufficient to outweigh the increased complexity, I'm going to close this feature request.
