### ISSUE TITLE
How to recursivly update dependencies?

### ISSUE THREAD

**Issue by LaurentGoderre** [npm/npm#3969]
The case I currently have is that we use the project grunt-sass which in turn relies on node-sass. Node-sass was updated with a critical fix but grunt-sass stayed the same. Doing an `npm update grunt-sass` does nothing because the version did not change. Is there a way to deal with this that does not involve our developers that already have their environment do `npm remove grunt sass & npm install grunt-sass`?

**Comment by smikes** [comment]
Is this still a problem for you?

This feels a bit like a feature request, in which case it is not really a candidate for auto-closure.  Can you help me flesh out what you want to see in this option?

In practice, any change in this behavior would be going in after the `multi-stage-install` milestone (also known as `npm@3.0.0`) which is planned for release this year.  I will link this case to the main multi-stage issue involving update , #6939 

Thanks!

**Comment by LaurentGoderre** [comment]
I guess not, I find that force installing works for me
