### ISSUE TITLE
npm destroys a link to a package if local version is not strictly equal to what is in the repo

### ISSUE THREAD

**Issue by notatestuser** [npm/npm#3974]
We're referencing all of our internal packages by their git repositories in `package.json` files. We don't store our internal modules in the npm registry.

When one of these packages are linked (via `npm link`) and the local version doesn't strictly match the version in the package stored in the package.json in the git master, npm assumes that the package is not installed and will overwrite the link in order to install it from scratch.

Reproducing the issue (with toy package names):

```
Given that the version of package1 in git is NOT exactly the same as what is local:
1. cd package1
2. npm link
3. cd ../package2
4. npm link package1
5. grep -e version ./node_modules/package1/package.json
(observe that it is not your local version and that it has instead been pulled from git)
```

I propose that npm runs a smarter check to permit a link if the locally linked package has a later package version than what is in git. This will allow for a development of subsequent versions on the local machine while leaving links intact.

An even smarter solution could include ensuring the HEAD commit is in the git tree of the local package while disregarding the version number altogether.

---

Appendix 1: The offending code (highlighted in red circle):

![npm link bug](https://f.cloud.github.com/assets/1255926/1279347/ef18aa00-2f34-11e3-8207-dab1633707ac.png)

**Comment by busches** [comment]
Is this bug still occurring in the latest `npm2` and `npm3`?
