### ISSUE TITLE
install packages only if not already installed somewhere higher?

### ISSUE THREAD

**Issue by Pomax** [npm/npm#4012]
Is there a way to tell npm to install a package but only install its requested dependencies if they're not already installed somewhere higher? Or, alternatively, tell npm to install them at some higher point for projects that use 10 different node applications all of which share about 80% of all dependencies? (npm install adds roughly 75000 files when installing our app suite, the vast majority of which are duplicates thanks to dependencies-of-depdencies. This is ... rather insane, and makes the install process take very long, and use a lot of not strictly-speaking-required bandwidth =D)

I couldn't find anything in the docs about this, hoping I just missed an npm install runtime flag.

**Comment by smikes** [comment]
This looks like another feature request which will be implemented by `multi-stage-install` /cc @iarna

**Comment by BenMorganIO** [comment]
:+1: On having this. Perhaps a `--conservative` option?

For now, there's, say, `ember -v || npm install -g ember`, but this doesn't help if there's a new version. There is an option for `npm show ember -v` which, if its greater than `ember -v` or the current installed module.

**Comment by ehsalazar** [comment]
I believe this has been resolved in npm@3 with a maximized, flat-tree. To achieve the outcome, you could:
- with npm@3
  - delete `node_modules` directory
  - run `npm install`
- or with npm@2
  - run `npm install`
  - run `npm dedupe`

If you're still encountering issues, let us know here or create a new issue specific to its behavior. We'll be happy to help.
