### ISSUE TITLE
Error while trying to install buster js

### ISSUE THREAD

**Issue by kunsingh** [npm/npm#4050]
I am struggling while installing buster. It's giving me following error.

C:\Users\Kunal  Singh>npm install -g buster
npm http GET https://registry.npmjs.org/buster
npm http 304 https://registry.npmjs.org/buster
npm ERR! Error: ENOTEMPTY, rmdir 'C:\Users\Kunal  Singh\AppData\Roaming\npm\node
_modules\buster'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "buster"
npm ERR! cwd C:\Users\Kunal  Singh
npm ERR! node -v v0.10.21
npm ERR! npm -v 1.3.11
npm ERR! path C:\Users\Kunal  Singh\AppData\Roaming\npm\node_modules\buster
npm ERR! code ENOTEMPTY
npm ERR! errno 53
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\Kunal  Singh\npm-debug.log
npm ERR! not ok code 0

**Comment by KenanY** [comment]
@kunsingh It has been a long time since you opened this, but better late then never I guess. Is this still an issue with `npm@2` or `npm@3`?

**Comment by KenanY** [comment]
Closing as abandoned.
