### ISSUE TITLE
dependency http://*.git should be resolved as git repository during `npm install`

### ISSUE THREAD

**Issue by robrich** [npm/npm#4060]
Consider this fragment from a package.json:

    "dependencies": {
        "foo": "https://github.com/isaacs/read-package-json.git"
    }

Because this url ends in ".git", rather than treating this as a [tarball](https://npmjs.org/doc/json.html#URLs-as-Dependencies) instead treat it as a [git repository](https://npmjs.org/doc/json.html#Git-URLs-as-Dependencies).  This would augment [GitHub URLs](https://npmjs.org/doc/json.html#GitHub-URLs) to also allow for private Git repositories, GitHub Enterprise, etc.

**Comment by othiym23** [comment]
The CLI team are unanimously agreed that magic is terrible, but at this point the convention of using HTTP[S] URLs to refer to tarballs (and only to refer to tarballs) is sufficiently deeply engrained that it doesn't seem worth the effort to try to change it by making it explicit. As such, I'm going to close this out. Thanks to all for the time and discussion.
