### ISSUE TITLE
Let npm.commands.pack create a tarball somewhere other than the cwd

### ISSUE THREAD

**Issue by NickHeiner** [npm/npm#4074]
I'm using `npm.commands.pack` to programmatically tar up packages. These packages are not in the current working directory. Would it be possible to alter `npm.commands.pack` to take a `dest` file path argument? Or maybe just change the behavior so the tarball is created in the same place as the package being packed?

````js
npm.commands.pack(['/var/tmp/my-package'], { destRelativeToPackage: true }, function() {
    // /var/tmp/my-package/my-package-3.2.1.tgz created
});
````

or:

````js
npm.commands.pack([{src: '/var/tmp/my-package', dest: '/some/other/dir'}], function() {
    // /some/other/dir/my-package-3.2.1.tgz created
});
````

(I am happy to work on a PR for this if you think it's a good idea.)

**Comment by othiym23** [comment]
Two things:

1. The CLI team has explicitly removed support for use of the programmatic API outside of the CLI code base (we'd like to remove it from _inside_ the CLI code base, but that's a longer-term project).
2. `cd $TMPDIR; npm pack /path/to/package` works just fine (this may have changed at some point over the last couple years).

As such, I'm going to close this feature request as shipped. Thanks for your time!

**Comment by ORESoftware** [comment]
I am personally looking for:

`npm pack > $my_location`

does anyone know how to accomplish that?

I would be happy with a solution at the command line or in Node.js either way.

I just want to stream the output of `npm pack` to stdout.

**Comment by legodude17** [comment]
`cat "$(npm pack)"` might work

**Comment by ORESoftware** [comment]
@legodude17 I don't think so, `npm pack` only writes the relative path to the file it outputs, to stdout

**Comment by ORESoftware** [comment]
the general solution to the OP here, is to allow `npm pack` to write the archive to stdout and let the end user control where it goes.
