### ISSUE TITLE
Weird Error 8

### ISSUE THREAD

**Issue by jeev** [npm/npm#4096]
Trying to install Comix.  Fail.
===================
```
module.js:340
    throw err;
          ^
Error: Cannot find module '../node_modules/lodash/vendor/tar/tar.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /Users/ellen.evans/cmx.js/node_modules/grunt-requirejs/node_modules/grunt-lodashbuilder/bin/post-install.js:14:13
    at Object.<anonymous> (/Users/ellen.evans/cmx.js/node_modules/grunt-requirejs/node_modules/grunt-lodashbuilder/bin/post-install.js:166:2)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
npm ERR! weird error 8
npm ERR! Error: ENOENT, lstat '/var/folders/l3/xzrp_lc108v40y9hm7mkz74mcgqz2s/T/npm-1574-g3Ck2yCn/1383672868273-0.669241311494261/package/jquery/node_modules/grunt/node_modules/nodeunit/node_modules/tap/node_modules/runforcover/node_modules/bunker/node_modules/burrito/example/web/bs.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 13.0.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/ellen.evans/cmx.js
npm ERR! node -v v0.10.21
npm ERR! npm -v 1.3.11
npm ERR! path /var/folders/l3/xzrp_lc108v40y9hm7mkz74mcgqz2s/T/npm-1574-g3Ck2yCn/1383672868273-0.669241311494261/package/jquery/node_modules/grunt/node_modules/nodeunit/node_modules/tap/node_modules/runforcover/node_modules/bunker/node_modules/burrito/example/web/bs.js
npm ERR! fstream_path /var/folders/l3/xzrp_lc108v40y9hm7mkz74mcgqz2s/T/npm-1574-g3Ck2yCn/1383672868273-0.669241311494261/package/jquery/node_modules/grunt/node_modules/nodeunit/node_modules/tap/node_modules/runforcover/node_modules/bunker/node_modules/burrito/example/web/bs.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
```

**Comment by smikes** [comment]
This looks like the sort of problem that will be fixed when `multi-stage-install` lands. /cc @iarna probably a `bug`

**Comment by ythej** [comment]
I am getting a similar error when I try to run "npm test"

> surveyman@1.5.1 test /home/vishnu/foss/plasma-umass/surveyman.js
> node tests/survey_tests.js && node tests/interpreter_tests.js && node tests/display_tests.js

surveyman tests

module.js:340
    throw err;
          ^
Error: Cannot find module 'string'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/vishnu/foss/plasma-umass/surveyman.js/tests/survey_tests.js:3:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
npm ERR! weird error 8
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0


Please help me with what I can do.

Thanks

**Comment by smikes** [comment]
@ythej could you please create a new issue <https://github.com/npm/npm/issues/new> and attach your full npm-debug.log as a gist <https://gist.github.com/>

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.

**Comment by shreya2111** [comment]
Having a similar problem. Can someone help?

/home/dudic/public_html/varuna/index.js:257
        res.render('template', {view_data});//sending json as var to another p
                                         ^
SyntaxError: Unexpected token }
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
npm ERR! weird error 8
npm ERR! not ok code 0

**Comment by irenge** [comment]
Is the issue solved yet ?

when i run npm test on my centos 7

[Irenge@localhost ~]$ npm test
npm ERR! Error: ENOENT, open '/home/Irenge/package.json'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.10.0-327.13.1.el7.x86_64
npm ERR! command "node" "/usr/bin/npm" "test"
npm ERR! cwd /home/Irenge
npm ERR! node -v v0.10.42
npm ERR! npm -v 1.3.6
npm ERR! path /home/Irenge/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/Irenge/npm-debug.log
npm ERR! not ok code 0
[Irenge@localhost ~]$ 


Any one with a solution ? let  me know please
