### ISSUE TITLE
npm publish existing module for private repository

### ISSUE THREAD

**Issue by vird** [npm/npm#4118]
I've installed my private repository

	http://clock.co.uk/tech-blogs/how-to-create-a-private-npmjs-repository
	emerge couchdb
	rc-update add couchdb default
	
	
	nano /etc/hosts
	MYIP vird.name
	nano /etc/couchdb/local.ini
	[httpd]
	secure_rewrites=false
	[vhost]
	vird.name:5984 = /registry/_design/scratch/_rewrite
	[admins]
	admin = password
	
	/etc/init.d/couchdb restart
	
	mkdir /opt/ext/user_make
	cd /opt/ext/user_make
	git clone git://github.com/isaacs/npmjs.org.git
	cd npmjs.org
	sudo npm install -g couchapp 
	npm install couchapp 
	npm install semver 
	couchapp push registry/app.js http://localhost:5984/registry 
	couchapp push www/app.js http://localhost:5984/registry

	curl -X POST http://127.0.0.1:5984/_replicate -d '{"source":"http://isaacs.iriscouch.com/registry/", "target":"registry", "continuous":true, "create_target":true}' -H "Content-Type: application/json" 
	
	npm config set registry http://vird.name:5984/
	npm config list
	npm adduser

I've created my first module
package.json
{
  "name": "rubyfy",
  "version": "0.0.1",
  "description": "ruby-style functions",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": "",
  "author": "vird",
  "license": "private only"
}
I've made 
npm publish
npm WARN package.json rubyfy@0.0.1 No README.md file found!
npm http PUT http://vird.name:5984/rubyfy
npm http 201 http://vird.name:5984/rubyfy
npm http GET http://vird.name:5984/rubyfy
npm http 200 http://vird.name:5984/rubyfy
npm http PUT http://vird.name:5984/rubyfy/-/rubyfy-0.0.1.tgz/-rev/1-9d58f2a9ecb8adc48b141cadef40f2fd
npm http 201 http://vird.name:5984/rubyfy/-/rubyfy-0.0.1.tgz/-rev/1-9d58f2a9ecb8adc48b141cadef40f2fd
npm http PUT http://vird.name:5984/rubyfy/0.0.1/-tag/latest
npm http 201 http://vird.name:5984/rubyfy/0.0.1/-tag/latest
+ rubyfy@0.0.1
I've made some changes, I've changed 
  "version": "0.0.1",
to
  "version": "0.0.2",

npm publish
npm publish
npm WARN package.json rubyfy@0.0.2 No README.md file found!
npm http PUT http://vird.name:5984/rubyfy
npm http 403 http://vird.name:5984/rubyfy
npm http PUT http://vird.name:5984/rubyfy
npm http 403 http://vird.name:5984/rubyfy
npm ERR! publish Failed PUT response 403
npm ERR! Error: forbidden failed checking doc.forbidden or doc._deleted: rubyfy
npm ERR!     at RegClient.<anonymous> (/usr/lib64/node_modules/npm/node_modules/npm-registry-client/lib/request.js:269:14)
npm ERR!     at Request.self.callback (/usr/lib64/node_modules/npm/node_modules/request/index.js:142:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/lib64/node_modules/npm/node_modules/request/index.js:856:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/lib64/node_modules/npm/node_modules/request/index.js:808:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:895:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.5.1-gentoo
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "publish"
npm ERR! cwd /opt/ext/mynpm/rubyfy
npm ERR! node -v v0.10.5
npm ERR! npm -v 1.2.18
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /opt/ext/mynpm/rubyfy/npm-debug.log
npm ERR! not ok code 0

What am I doing wrong?

**Comment by smikes** [comment]
Is this still a problem for you?

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by vird** [comment]
This issue is not relevant for me now. I am using node_modules folder one level higher than project folders and it's fine for me.

**Comment by othiym23** [comment]
Closing as resolved.
