### ISSUE TITLE
PhantomJS Not Found error while installing grunt

### ISSUE THREAD

**Issue by Niharika29** [npm/npm#4121]
Hello,
I was trying to install grunt but ran into this Warning:PhatomJS not found error on Windows
I tried to uninstall, but it says the file wasn't found. I tried a few other commands but nothing seems to work.
Any suggestion what I could do?
![image](https://f.cloud.github.com/assets/5735280/1528992/30f9189c-4c22-11e3-8a51-bddd282efe0a.png)

**Comment by othiym23** [comment]
Closing as abandoned / resolved.
