### ISSUE TITLE
install express error when execute `npm prune`

### ISSUE THREAD

**Issue by wilsonp** [npm/npm#4133]
Hi,All,I meet a error when termed to execute command `npm prune`:
(I used nodist to manage node's version)

C:\nodist-master\bin>npm install -g express
npm http GET https://registry.npmjs.org/express
npm http 304 https://registry.npmjs.org/express
npm http GET https://registry.npmjs.org/express/-/express-3.4.4.tgz
npm http 200 https://registry.npmjs.org/express/-/express-3.4.4.tgz

> express@3.4.4 prepublish c:\Users\ADMINI~1\AppData\Local\Temp\npm-6704-1IrxgdL
k\express-3.4.41384416965715-0.47066722391173244\package
> npm prune

npm ERR! Error: ENOENT, open 'C:\nodist-master\bin\package.json'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\nodist-master\\bin\\\\node.exe" "C:\\nodist-master\\bin\\n
ode_modules\\npm\\cli.js" "prune"
npm ERR! cwd c:\Users\ADMINI~1\AppData\Local\Temp\npm-6704-1IrxgdLk\express-3.4.
41384416965715-0.47066722391173244\package
npm ERR! node -v v0.11.7
npm ERR! npm -v 1.3.14
npm ERR! path C:\nodist-master\bin\package.json
npm ERR! code ENOENT
npm ERR! errno -4059
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     c:\Users\ADMINI~1\AppData\Local\Temp\npm-6704-1IrxgdLk\express-3.4.
41384416965715-0.47066722391173244\package\npm-debug.log
npm ERR! not ok code 0
npm ERR! addLocalDirectory Could not pack "c:\\Users\\ADMINI~1\\AppData\\Local\\
Temp\\npm-6704-1IrxgdLk\\express-3.4.41384416965715-0.47066722391173244\\package
" to "C:\\Users\\Administrator\\AppData\\Roaming\\npm-cache\\express\\3.4.4\\pac
kage.tgz"
npm ERR! express@3.4.4 prepublish: `npm prune`
npm ERR! Exit status 4294963237
npm ERR!
npm ERR! Failed at the express@3.4.4 prepublish script.
npm ERR! This is most likely a problem with the express package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm prune

**Comment by busches** [comment]
@KenanY no updates from author in over two years and `npm install -g express` works fine for their latest version.
