### ISSUE TITLE
Clarify use of `./`

### ISSUE THREAD

**Issue by LinusU** [npm/npm#4137]
Hi @isaacs,

I have read around on the internet and also in [this document] [1] but can't find anyone specifically mentioning the use of `./`.

- You have `./` in `bin` but not in `main`.
- Nodejitsu has `./` in [their example] [2] for both `main` and `bin`.
- [CommonJS] [3] dosen't have neither `main` or `bin` but does not use `./` in `scripts`.

I personally think that it looks so much better without `./` but either way I would really like a "correct way" to do it, an **accepted best practice**.

Thanks for taking the time on this one!

[1]: https://github.com/isaacs/npm/blob/master/doc/files/package.json.md
[2]: http://package.json.nodejitsu.com/
[3]: http://wiki.commonjs.org/wiki/Packages/1.0

**Comment by smikes** [comment]
Here's a nice writeup of the `path` question: http://blog.ibangspacebar.com/npm-scripts/

Especially with the automatic `dedupe` coming in `npm@3`, the current recommendation is to drop any relative path specification and assume that `bin` scripts are available in the shell's path.

**Comment by smikes** [comment]
Can this issue now be closed?

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by LinusU** [comment]
@smikes although it was a nice blog post it dosen't address the question posed. I'll try to clarify.

This question is whether we should write like this, the "clean approach":

```json
{
  "main": "index.js",
  "bin": {
    "appdmg": "bin/appdmg.js"
  }
}
```

Or like this, the "verbose approach":

```json
{
  "main": "./index.js",
  "bin": {
    "appdmg": "./bin/appdmg.js"
  }
}
```

To be clear, **both currently works**, but what I wanted was an **accepted best practice**.

**Comment by smikes** [comment]
> both currently works

This is only true on *nix.  On Windows, the installer and cmd-shim jump through hoops to make `./` work, and a carelessly placed `./` can cause problems, eg https://github.com/npm/npm/issues/7327

> accepted best practice

I am not aware of one.

**Comment by LinusU** [comment]
Since `./` sometimes causes problems, I think that we should establish that we do not use `./` in front of the paths. Comments?

**Comment by othiym23** [comment]
I'm going to close this, as the discussion is inconclusive and it's not an actionable issue as currently described. I'd be happy to review patches to the documentation or npm/normalize-package-data that raise warnings on `./` at the beginning of script entries. Thanks for the discussion!
