### ISSUE TITLE
npm view/show should accept a path to a local node module

### ISSUE THREAD

**Issue by jasonkarns** [npm/npm#4149]
Most other npm commands accept a local path argument wherever a pkg is expected. However, `npm view` returns an error if a local path is specified.

```sh
$ npm view .
npm ERR! npm view pkg[@version] [<field>[.subfield]...]
npm ERR! not ok code 0
```

**Comment by othiym23** [comment]
If somebody wants to take a stab at adding support for path arguments to `npm view`, the CLI team will be happy to review it and work with you to get it landed (hence the `patch-welcome` label). However, "low on the priority list" means that the CLI team isn't going to have time to get to it themselves within the medium term, and as such I'm going to close this issue. Thanks for your time and the discussion!
