### ISSUE TITLE
shrinkwrap removes dependency of child package when dep is in parent's devDependencies

### ISSUE THREAD

**Issue by nemtsov** [npm/npm#4161]
Here's the top-level package. 
Note the dep on `fs-extra` and devDep on `rimraf`.
```
{
  "name": "top_level",
  "version": "0.1.0",

  "dependencies": {
    "fs-extra": "~0.8.1"
  },

  "devDependencies": {
    "rimraf": "~2.2.2"
  }
}
```

Note that `fs-extra` has a dependency on `rimraf`:
```
{
  "name": "fs-extra",
  "version": "0.8.1",

  "dependencies": {
    "ncp": "~0.4.2",
    "mkdirp": "0.3.x",
    "jsonfile": "~1.1.0",
    "rimraf": "~2.2.0"
  },

  "devDependencies": {
    "mocha": "*",
    "path-extra": "0.0.x",
    "testutil": "~0.5.0"
  }
}
```

And here's the output of `npm shrinkwrap`.
**Note that `fs-extra` is missing its `rimraf` dependency.**

```
{
  "name": "top_level",
  "version": "0.1.0",
  "dependencies": {
    "fs-extra": {
      "version": "0.8.1",
      "from": "fs-extra@~0.8.1",
      "dependencies": {
        "ncp": {
          "version": "0.4.2",
          "from": "ncp@~0.4.2"
        },
        "mkdirp": {
          "version": "0.3.5",
          "from": "mkdirp@0.3.x"
        },
        "jsonfile": {
          "version": "1.1.1",
          "from": "jsonfile@~1.1.0"
        }
      }
    }
  }
}
```

Thus, `npm shrinkwrap` removes dependency of a child package when that dependency is in parent's devDependencies.

**Comment by othiym23** [comment]
@iarna Does `npm@3` address this?

**Comment by smikes** [comment]
If a repro is needed, I can build one tomorrow.

**Comment by stefanpenner** [comment]
I think this has been addressed by https://github.com/npm/npm/issues/6933

**Comment by arty-name** [comment]
I realised that `npm install` is effectively `npm install --development` while `npm shrinkwrap` is effectively `npm shrinkwrap --production`. With that understanding I know how to avoid this bug: 

1) remove `node_modules` and `npm-shrinkwrap.json`
2) run `npm install --production`
3) run `npm shrinkwrap`

If you follow these steps `npm shrinkwrap` will capture the "production" tree created by `npm install --production` and all the necessary packages will be in place. 

Still it would be nice to have reasonable defaults that avoid this issue somehow.

**Comment by iarna** [comment]
Indeed, among the changes in `npm@3`, we explicitly fixed this, so I'm going to close this issue. If you all run into anything like this in the future with `npm@3` please open a new issue!
