### ISSUE TITLE
npm registry _changes API does not return consistent results, last_seq off by 11

### ISSUE THREAD

**Issue by jbuck** [npm/npm#4190]
Hi there, I've been writing a utility to clone the [NPM registry to Amazon S3](https://github.com/jbuck/npm-readonly-mirror). While developing this, I've found that results from http://isaacs.iriscouch.com/registry/_changes can differ when run repeatedly. Specifically, every change will have a difference in seq number by 11. Here are two requests to http://isaacs.ic.ht/registry/_changes?since=802657 that show this difference:

https://dl.dropboxusercontent.com/u/4403845/npm/s1.txt
https://dl.dropboxusercontent.com/u/4403845/npm/s2.txt

Is there some way I can compensate for this in my client? As a hacky workaround, I could just add a fudge factor to fetch (my_last_seq - 11) changes, but it'd be nice to have consistent sequence update numbers. Maybe I'm seeing https://groups.google.com/forum/#!msg/couchdb-user-archive/aaSEnvBtm2E/0X1iBZniHpQJ ?

**Comment by smikes** [comment]
Is this still a problem for you?

I believe `npm` registry replication has gone off in a different direction since then.

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by jbuck** [comment]
Yeah, I suspect that this isn't a problem anymore, now that the registry has mostly moved away from couchdb. I've left my S3 mirror running for about a year now without any changes, and it's still mirroring just fine.

**Comment by othiym23** [comment]
Closing as resolved, then.

**Comment by julianlam** [comment]
Did `last_seq` get um... rolled back? My mirror stopped updating at 1404910, and upon checking `_changes`, looks like `last_seq` is at 353031 as of right now...
