### ISSUE TITLE
OS umask overrides npm umask

### ISSUE THREAD

**Issue by robnagler** [npm/npm#4197]
This is running on OS X 10.9, npm 1.3.14.  Also, I think npm get should display the umask in octal.

```
root# ls -l /usr/local/lib/node_modules/
total 0
drwxr-xr-x  15 nobody  wheel  510 Nov 26 08:05 ar-drone
drwxr-xr-x  21 nobody  wheel  714 Nov 26 08:05 espresso
drwxr-xr-x  13 nobody  wheel  442 Nov 26 08:17 express
drwxr-xr-x  20 24561   staff  680 Nov 24 13:28 npm
root# npm i -g async
npm http GET https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/async
async@0.2.9 /usr/local/lib/node_modules/async
root# ls -l /usr/local/lib/node_modules/
total 0
drwxr-xr-x  15 nobody  wheel  510 Nov 26 08:05 ar-drone
drwxr-x---   7 nobody  wheel  238 Nov 26 08:23 async
drwxr-xr-x  21 nobody  wheel  714 Nov 26 08:05 espresso
drwxr-xr-x  13 nobody  wheel  442 Nov 26 08:17 express
drwxr-xr-x  20 24561   staff  680 Nov 24 13:28 npm
root# npm config get umask
18
root# umask
0027
root# npm --version
1.3.14
```

**Comment by zkxs** [comment]
I'd expect `npm install -g` to make the installed files globally accessible.

    umask 077
    sudo -H npm install -g somepackage

The result of the preceding commands is that only root has access to run/read the installed package.  Is it expected that the shell's umask overrides npm's internal umask?

**Comment by robnagler** [comment]
Yes, the shell's umask should not affect the install umask. The bug is that `mkdir` applies `umask`, and installers must override this behavior with an explicit `chmod`. Installers like RPM and the `install` command ignore umask.
