### ISSUE TITLE
npm install needs to clean dead locks

### ISSUE THREAD

**Issue by robnagler** [npm/npm#4198]
I started an install, but typed ^C to stop it.  Then I started it again, and the lock file was in ~/.npm/, which caused the second install to hang waiting for the lock to be released (see below).  

My $.02: I suggest that the lock file contain the pid and hostname of the locking process.  While polling the lock in npm install, if the hostname matches and the pid matches a dead process, kill the lock.  If the hostname doesn't match, output a single warning that there's a lock pending.  I wouldn't bother catching the ^C, because there might be other signals/reasons for terminations so better to just check dead locks on new operations.

root# npm install jade
npm http GET https://registry.npmjs.org/jade
^Croot# npm install -g jade
[hangs]

root# npm -v
1.3.14
root# sw_vers
ProductName:	Mac OS X
ProductVersion:	10.9
BuildVersion:	13A603

**Comment by othiym23** [comment]
This is indeed annoying, speaking as someone who needs to bail out of npm installs fairly frequently while testing it, but it's a relatively small annoyance that can be worked around (`rm ~/.npm/_locks/*`), and as such, not something that the CLI team is going to work on anytime soon. The CLI team would be happy to review patches that add the ability to track locks opened by a given process and that then use `rimraf.sync()` to ensure those lockfiles (and only those lockfiles) are removed at process exit, so we've added `patch-welcome` as a label to this, even though we're closing it. Thanks for your time!
