### ISSUE TITLE
`npm ls -g --parseable` uses local path, not global

### ISSUE THREAD

**Issue by SBoudrias** [npm/npm#4202]
I can reproduce this bug on Windows and on TravisCI (so probably other Unix system), but the behavior seems OK on Mac OSx.

When I run `npm ls -g --parseable`, the ouput correctly shows the name of global packages, but this name is prefixed with the local `node_modules` folder path, not the global path.

I'd expect `--parseable` to return the package real path (the global `node_modules`).

**Comment by busches** [comment]
@SBoudrias @sindresorhus are you still seeing this problem on `MacOS`? `npm 3.10.5` is working correctly on Windows.
