### ISSUE TITLE
Bundle/Include Dependencies 

### ISSUE THREAD

**Issue by arei** [npm/npm#4210]
# Feature Description

**Create a means within npm of generating a `.tgz` representation of a npm package AND all of its dependencies such that an `npm install` can be be done using the `.tgz` representation to install the package AND all of its dependencies.**

This involves two separate and distinct aspects:
1. Add an ability to npm to create a `.tgz` file that contains a single npm package in its uninstalled form and its entire dependency tree in their uninstalled forms.  See below for additional details.
2. Change `npm install <tarball file>` to understand that a `<tarball file>` may contains the package and the cache from which all dependencies should be installed. See below for additional details.

This is a rewrite of the closed ticket #3429.
# Reason for Feature Request

The reason for this feature request is to **provide a means for npm to be used to install a given package in an offline environment and without relying on the npm registry being available online.**  By using a bundled npm package tarball that contains the package and all necessary dependencies, npm is not forced to go out to the internet and find the dependencies required.  This functionality is desirable for use in isolated/off-the-grid systems and for usage by package owners whom wish to distribute their package as a complete unit.

Consider this simple problem case: **Install `socket.io` on a system that is 100% offline and not connected to the internet. (The target system has node/npm installed already.)**  

(In the process described below "LIVE" indicates a system with an internet connection and "OFFLINE" indicates a system without an internet connection.)

Your first attempt might go something like this:
1. [LIVE] Create a new directory and change to it.
2. [LIVE] Install socket.io using npm: `npm install socket.io`
3. [LIVE] tar the `node_modules` directory.
4. [LIVE] copy the tar to some removable media like a memory stick.
5. [OFFLINE] move the memory stick to the remote offline system.
6. [OFFLINE] copy the tar from the removable media.
7. [OFFLINE] untar the `node_modules`

The problem with this is that this did not actually install `socket.io` on the remote system, but just duplicated the files of an installed `socket.io`. This ignores any special install process instructions that `socket.io` might want to perform on the system to which it is installed. In some cases it's good enough, but it's not the right answer. 

Your next attempt might be to get the `<tarball file>` of `socket.io` and use that.  
1. [LIVE] Create a new directory and change to it.
2. [LIVE] Get the 'socket.io' tarball using npm pack: `npm pack socket.io`
3. [LIVE] copy the tar to some removable media like a memory stick.
4. [OFFLINE] move the memory stick to the remote offline system.
5. [OFFLINE] copy the tar from the removable media.
6. [OFFLINE] Install `socket.io` from the tarball: `npm install socket.io-0.9.16.tgz`
7. [OFFLINE] Stare confusedly at: 

```
npm WARN optional dep failed, continuing redis@0.7.3
npm ERR! Error: connect ECONNREFUSED
npm ERR!     at errnoException (net.js:901:11)
npm ERR!     at Object.afterConnect [as oncomplete] (net.js:892:19)
npm ERR!  { [Error: connect ECONNREFUSED]
npm ERR!   code: 'ECONNREFUSED',
npm ERR!   errno: 'ECONNREFUSED',
npm ERR!   syscall: 'connect' }
```

npm is attempting to go out and get the dependencies from http://registry.npmjs.org which clearly will not work on our remote offline system.

Okay, so you can just get and install all the dependencies. Except there isn't a way to list the dependencies of an npm package from npm. The best way to get the dependency tree in node is to actually install the npm package, so let's do that.  
1. [LIVE] Create a new directory and change to it.
2. [LIVE] Install socket.io using npm: `npm install socket.io`
3. [LIVE] Make a note of everything that was installed: socket.io, socket.io-client/0.9.16, policyfile/0.0.4, base64id/0.1.0, redis/0.7.3, uglify-js/1.2.5, ws, xmlhttprequest/1.4.2, active-x-obfuscator/0.0.1, zeparser/0.0.5, commander, tinycolor, nan, and options
4. [LIVE] For each item installed, go get the `<tarball file>` using `npm pack`.  Don't forget to change the '/' to an '@' for packages that are given with a specific version.
5. [LIVE] `npm pack socket.io`
6. [LIVE] `npm pack socket.io-client@0.9.16`
7. [LIVE] `npm pack policyfile@0.0.4`
8. [LIVE] `npm pack base64id@0.1.0`
9. [LIVE] `npm pack redis@0.7.3`
10. [LIVE] `npm pack uglify-js@1.2.5`
11. [LIVE] `npm pack ws`
12. [LIVE] `npm pack xmlhttprequest@1.4.2`
13. [LIVE] `npm pack active-x-obfuscator@0.0.1`
14. [LIVE] `npm pack zeparser@0.0.5`
15. [LIVE] `npm pack commander`
16. [LIVE] `npm pack tinycolor`
17. [LIVE] `npm pack nan`
18. [LIVE] `npm pack options`
19. [LIVE] copy the tars to some removable media like a memory stick.
20. [OFFLINE] move the memory stick to the remote offline system.
21. [OFFLINE] copy the tars from the removable media.
22. [OFFLINE] Install `socket.io` from the tarball: `npm install socket.io-0.9.16.tgz`
23. [OFFLINE] Stare confusedly at:

```
npm WARN optional dep failed, continuing redis@0.7.3
npm ERR! Error: connect ECONNREFUSED
npm ERR!     at errnoException (net.js:901:11)
npm ERR!     at Object.afterConnect [as oncomplete] (net.js:892:19)
npm ERR!  { [Error: connect ECONNREFUSED]
npm ERR!   code: 'ECONNREFUSED',
npm ERR!   errno: 'ECONNREFUSED',
npm ERR!   syscall: 'connect' }
```

Well, this is the same problem as before. Basically, there is not an easy way to tell npm to use all these `.tgz` files that we have, or is there?  

npm does cache it's files and we can set that cache to somewhere, so maybe we can use the cache functionality. 
1. [LIVE] Create a new directory and change to it.
2. [LIVE] Install socket.io using npm because this is the only way to get our dependency tree. Additionally, let us store our cache some where clean: `npm --cache ./.cache install socket.io`
3. [LIVE] tar up the .cache folder.
4. [LIVE] copy the tar to some removable media like a memory stick.
5. [OFFLINE] move the memory stick to the remote offline system.
6. [OFFLINE] copy the tar from the removable media.
7. [OFFLINE] untar the tar, creating .cache in the process.
8. [OFFLINE] Install `socket.io` from the .cache directory: `npm install --cache ./.cache socket.io`
9. [OFFLINE] Wait.  (This step will take a little while as npm tries to connect to the registry to see if newer versions are available.  You can speed this up playing around with some of the npm config options regarding fetch.)

Success! A little convoluted and a bit of extra work, but a success.  But I think we can do better...
# Feature Breakdown
## Goals for the Feature
- Be able to install a package including all dependencies in an offline environment.
- Minimize the objects that have to be moved (tar everything up).
- Minimize the number of steps necessary to create and install.
- Disable checking the registry for things that are already in the bundle.

Specifically, there are two aspects to this feature request: Bundling a Package into a `.tgz` that includes its dependencies, and using npm to install from said bundle.
## Bundle Package

In this aspect of the feature the objective is to create a `.tgz` that contains the package and all the dependencies necessary to install that package and the other dependencies.

For a given package...
- Build the dependency tree for the package including the dependency tree for each dependent package.
- Download each item in the dependency tree.
- Bundle all items into a `.tgz`.

Suggestions and additional things to keep in mind...
- The `.tgz` file created should have the name and version of the initial package.  Additionally the name might include something to indicate that this also bundles the dependencies. `socket.io-0.9.16.withDependencies.tgz` for example.
- This could be it's own command like `npm box socket.io` or it could be a variant of `npm pack` like `npm pack --includeDependencies socket.io` or `npm pack --all socket.io` or `npm packall socket.io`.
- One approach might be to simply insert the dependencies into the initial package `.tgz` and then make `npm install <tarball file>` look inside the tarball for the dependencies before going out to the registry.
- Should include optional modules as if `--optional` was specified.
## Install from Bundle

In this aspect of the feature the objective is to take a previously bundled `.tgz` file and install the package and all mecessary dependencies from said file.

From a given `.tgz` file...
- Install the initial package from the `.tgz`.
- Install all dependent packages from the `.tgz`
- Fall back to searching the registry for packages when they are missing from a `.tgz` file.

Suggestions and additional things to keep in mind...
- Allow for all the normal behavior of `npm install` such as global.
- If a dependency exists in the `.tgz` and is of a valid version, it must be used.
# Relevant Discussion/Links

This ticket was initially written up in #3429.  I believe that #3429 was closed due to misunderstanding of the desired feature and/or the problem space.  This rewrite is an attempt to clarify that misunderstanding.

[npmbox](https://github.com/arei/npmbox) is an attempt to provide an example of the desired functionality described in this feature request in a third party tool.  However, npmbox is not a final solution because it depends on npmbox being first installed on the target system and thus we have a chicken and egg problem.

[pac](https://npmjs.org/package/pac) is somewhat related, but also not really the solution desired.  It works by examining your package.json file and then downloading the tarball of any package listed there as a dependency into the .modules folder.  While this might seem like a similar answer, it does not download the entire dependency tree nor does it provide a means to install the package or its dependencies.

**Comment by Ge0** [comment]
+1

**Comment by hulkish** [comment]
+1

**Comment by brtnshrdr** [comment]
+1

**Comment by keithchilders** [comment]
I support the suggestion to bring back npm bundle and have it implement this behavior.

**Comment by pastur** [comment]
+1

**Comment by shedali** [comment]
+1

**Comment by dudongdong** [comment]
+1

**Comment by oatkiller** [comment]
:+1:

**Comment by olingerc** [comment]
+1

**Comment by makinux-git** [comment]
+1

**Comment by danieleds** [comment]
+1

**Comment by gbel** [comment]
+1

**Comment by skohli0302** [comment]
+1

**Comment by grdryn** [comment]
A builtin way to do offline installs would be great! :+1:

**Comment by panuhorsmalahti** [comment]
+1

**Comment by deostroll** [comment]
I ditto @grdryn :+1:

**Comment by kreegr** [comment]
+1 please

**Comment by MattiSG** [comment]
+1

**Comment by jarrodconnolly** [comment]
+1

**Comment by ralberts** [comment]
+1

**Comment by almilo** [comment]
+1

**Comment by ralberts** [comment]
Albeit not the best solution but I ended up creating a npm overlay that augments 'npm install' behavior to copy the final directory to a cache and then retrieving the cached directory when offline.

**Comment by foxxyz** [comment]
I'm surprised this has been such a topic of debate. In many organizations there are closed intranets that can greatly benefit from this kind of functionality. 

Python's package manager makes this incredibly easy:

On the online machine: `pip install -r list_of_dependencies.txt --download /path/to/some/dir`
On the offline machine: `pip install -r list_of_dependencies.txt --no-index --find-links /path/to/stored/packages`

@arei Thank you for your ongoing crusade in lobbying for this!

**Comment by splintor** [comment]
+1

**Comment by majgis** [comment]
I created the following package to behave like npm-pack, but it accepts the additional arguments of npm-install and includes dependencies in the output:
https://www.npmjs.com/package/npm-bundle

I propose that any official npm-bundle feature consider including the same arguments as `npm install` as it is it is pretty slick to `npm-bundle something` directly from the registry or a preexisting tarball.

One interesting issue I found when creating this package is that `bundledDependencies` is not recognized by npm v3 unless the `--legacy-bundling` option is used.  Is this issue already documented somewhere?

**Comment by brndn4** [comment]
+1 We have been relying on npmbox at my company for offline installs of back-office systems at customer sites. Would love to have this supported by npm.

**Comment by axelfontaine** [comment]
+1 

(For anyone looking for a solution you can use today, npm-bundle by @majgis works great)

**Comment by 73rhodes** [comment]
It's definitely time for this. Please.

**Comment by kenberkeley** [comment]
> 1. In online environment, `npm install --no-bin-link`. You will have a **entire flattened** `node_modules`
> 2. Then, bundle this **flawless** `node_modules` with `tar / zip / rar / 7z` etc
> 3. In offline environment, extract the bundle, that's it
  
P.S [node-pac](https://github.com/mikefrey/node-pac) is another option, but it can't deal with the packages which still need downloading something for installation.

**Comment by Modarresi** [comment]
+1 I like that. please built into npm.
tanks

**Comment by othiym23** [comment]
This is something that is highly relevant to @seldo's interests – having a better story for deployment is something that concerns a lot of the people at npm, Inc. thinking about deployment as a product. That said, it's not that clear where this fits on the product roadmap either for the company or for the CLI team, so I don't know when we'll work on this. There quite a few subtleties to getting this set up right (e.g. do we deal with cross-platform support for native modules? if so, how? or do we just deal with cross-compilation? or nothing at all and force an `npm rebuild` once it's deployed? etc), so I've removed `patch-welcome` and added `needs-discussion`. There will be more later from us, I'm sure.

**Comment by bmiller59** [comment]
+1

**Comment by guymalka** [comment]
i have few holes in the example


[LIVE] Create a new directory and change to it. - DO NOT UNDERSTAND THIS

[LIVE] Install socket.io using npm because this is the only way to get our dependency tree. Additionally, let us store our cache some where clean: npm --cache ./.cache install socket.io
[LIVE] tar up the .cache folder. - USING WINDOWS , TAR, UNTAR IS THE SAME?

is there any video of this process?

**Comment by cniweb** [comment]
+1

**Comment by hekevintran** [comment]
Being able to do offline repeatable builds is such a core feature of a package manager that it is no longer funny that npm cannot do this.  Thank god Yarn was created.

https://code.facebook.com/posts/1840075619545360
https://yarnpkg.com/

**Comment by niedomnie** [comment]
+1

**Comment by legodude17** [comment]
What is the current status on this? This seems to have near unanimous support. 😄

**Comment by swateek** [comment]
Is npmbox a workaround? Am stuck with this.

**Comment by legodude17** [comment]
I think it is @swateek.

**Comment by jdmairs** [comment]
I could not get npmbox to install node-gyp successfully...everything else has worked great.  Comments would be appreciated!

**Comment by legodude17** [comment]
Doesn't `node-gyp` come with `node`?

**Comment by jdmairs** [comment]
@lego It does not in the Windows 6.9.2 Installer.  Only node and npm.

**Comment by arei** [comment]
@jdmairs Please file an issue over on the [npmbox github](https://github.com/arei/npmbox/issues).

**Comment by arei** [comment]
@othiym23 @seldo Can we get this re-opened please? Creating a new ticket about this would result in a loss (or at least obfuscation) of the discussion and support for this issue.

**Comment by hulkish** [comment]
@arei This issue has been open for 4+ years.... Is there actually any work being done on this? If not, then why not just close?

**Comment by 73rhodes** [comment]
+1 to re-open.  Not being able to build integral packages for offline installs makes it harder to promote node/npm as a good choice in fields like telecom with large, high-security, mission-critical networks.

**Comment by wayofthefuture** [comment]
I think for now it may be worth just researching the alternatives for a solution? Which do you think is the most reliable alternative? And which ones wouldn't require the same node-version on both machines? ( I think we can assume at least Node V6 for everything)

- npmbox
- npm-bundle
- yarn (I think?)
- plain ole tarball on node_modules folder
- --no-bin-link

**Comment by schmod** [comment]
I'm actually going to argue against reopening this issue.  

npm5 significantly changed the landscape with regards to potential-use cases for this feature, and I think that it makes the most sense to restart this conversation with that context in mind.  

---

My $0.02 is that `package-lock` and yarn both satisfy the "lock my versions" requirement, and also provide a straightforward path toward solving the "offline install" use-case.

If you have a `package-lock.json` file, and tarball your whole `node_modules` folder, you can run `npm install` without a network connection.

**Comment by wayofthefuture** [comment]
@schmod Interesting... what about if you move that node_modules folder to another computer that requires a rebuild of bindings. Would a "npm rebuild" suffice do you think?

I've been using npmbox / npmunbox to move the node_modules. I wonder the differences between that and doing a tarball. Thanks.
