### ISSUE TITLE
external tarballs (CDN etc)

### ISSUE THREAD

**Issue by maxogden** [npm/npm#4232]
I'd like to see a way to do something like this:

```
{
  "name": "my-cool-cdn-hosted-module",
  "version": "0.0.1",
  "external": "http://cool-cdn-website.com/module-0.0.1.tgz"
}
```

that way I could opt in to self hosting a module, and npm could automagically mirror my tarball or something after I publish on it's own CDN so that it can make sure that modules are highly available

this also has implications for work happening in other places like https://github.com/okfn/dpm where we want to use npm for metadata tracking of large datasets. the datasets themselves are too big to put in tarballs in couch so we'll need to specify them as external resources

**Comment by iarna** [comment]
This is trying to solve:

  1. Robustness of the registry.
  2. Distribution of the registry

Both of these seem to be solved by the modern registry and its use of the Fastly CDN.

A third problem is is the distribution of extremely large datasets. This is something that has not been solved. Before the npm cli addresses this, it needs to be raised as an issue at [the registry issue tracker](https://github.com/npm/registry).
