### ISSUE TITLE
`npm view` should default to the current package

### ISSUE THREAD

**Issue by Niggler** [npm/npm#4266]
Other commands, like `npm owner ls`, use the current package.json to determine the package if it is not specified.  However, without specifying a package explicitly, npm view fails.

**Comment by othiym23** [comment]
Wow! We actually landed this as a change back in 2014 as 36356011b6f2e6a5a81490e85a0a44eb27199dd7. I believe this is exactly what you were looking for, @Niggler, so I'm going to close this feature request as fulfilled. Thanks for your time!
