### ISSUE TITLE
update test/disabled/outdated-depth-integer

### ISSUE THREAD

**Issue by luk-** [npm/npm#4268]
This needs to be updated once the new npm-registry-mock is published to npm, so we can properly test outdated with --depth.

ping @robertkowalski to get that published when he can.

Assigning to myself.

**Comment by smikes** [comment]
I can take this on.  The test is still disabled, and the tests of `npm outdated` code can be modernized.

**Comment by robertkowalski** [comment]
cool!

**Comment by smikes** [comment]
PR is #7430

**Comment by othiym23** [comment]
Fixed in 536b2b6f55c349247b3e79b5d11b4c033ef5a3df. THANK YOU SAM.
