### ISSUE TITLE
npm gives exit code 0 even when preinstall script can't be run

### ISSUE THREAD

**Issue by fresheneesz** [npm/npm#4276]
I'm getting the following line when I run NPM install:
    npm WARN cannot run in wd installer@0.1.0 node preinstall.js (wd=/opt/nodebackend/git)

However, the exit code is 0. This isn't good - it means my script continues to run, completely oblivious that something has failed, proceeding to cause junk and other failures down the line. FYI, I know how to fix the problem - that's not the issue. The issue is that problems like this should cause a non-zero exit code .

**Comment by scjody** [comment]
This is also an issue with postinstall:

```shell
root@prod-streambed-001:/tmp/npmtest# npm install
npm WARN cannot run in wd test@0.0.0 does/not/exist (wd=/tmp/npmtest)
root@prod-streambed-001:/tmp/npmtest# echo $?
0
```

Simple package.json that can reproduce this:
```json
{
  "name": "test",
  "version": "0.0.0",
  "description": "test",
  "repository": "test",
  "scripts": {
    "postinstall": "does/not/exist"
  },
  "author": "Test Test",
  "license": "test"
}
```
