### ISSUE TITLE
Sanctioned way to mark packages as browser-(in)compatible

### ISSUE THREAD

**Issue by domenic** [npm/npm#4321]
I am (finally) logging a series of feature requests I discussed with @addyosmani at JSConf EU, as to what would make npm the best JavaScript package manager, and help it crush all competition.

The idea would be that we use *and endorse* some package.json field as "the way" to mark a package as browser-ready. Then, we would provide dedicated interfaces to searching npmjs.org for browser-specific packages.

Some of these ideas have been prototyped by @substack in his http://browserify.org/search, although they are a bit testling-specific. (Also, they don't seem to work anymore?)

I think we'd want to avoid drawing a bright line between browser-ready and server-specific components, i.e. not segregate the entire npmjs.org browsing experience, but instead just have a "rank browser packages higher in this search" type of checkbox.

There are various concrete possibilities here: @defunctzombie's package.json `browser` field (maybe encourage `browser: true` and `browser: false`, in addition to its use for mapping); a specific tag; or even the `engines` field.

It's possible to scope-creep this into various other levels of support (e.g., which browsers do you support), but that's probably not a good idea.

**Comment by jehoshua02** [comment]
I'm trying to figure out what to put in my `package.json`. What is the TL;DR?

**Comment by zxqfox** [comment]
:+1: for `{ engines: { browser: es6 } }`

**Comment by steinerj** [comment]
Sorry, for digging out this old issue, but I still believe the distinction "browser" vs "node" is not sufficient. There's loads of fairly popular platforms which are V8 based and allow for including npm packages, but do not offer node APIs. These include: https://www.nativescript.org or https://www.arangodb.com

Both of which provide a facade for some typical node modules such as 'http', but not for e.g. filesystem. 

So I like the "affinity" idea. Currently weeding out packages that have a dependency on a very low level is an absolute pain and mostly based on intuition, grepping and trial & error.

**Comment by othiym23** [comment]
Quite a bit has happened over the last two years! It feels uncontroversial to now say that npm is a repository for tools for Node, the browser, and many other environments, and I think the number of packages on the registry that _only_ work with Node is now in the minority. Also, the community has done a lot of work to improve the experience and workflows of non-Node-based packages. This proposal points to a few things we’d like npm to do better:

- simplify discovery of packages intended for specific purposes
- ease the process of assembling and working with applications based on non-Node deployment environments
- make it easier to visualize and discover how front-end tools are meant to be used (see also [`front-end`](https://github.com/npm/npm/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Afront-end) issues)

These are actually pretty basic (and interesting!) product areas for a package manager like npm to handle. They’re much larger than the scope of a single issue! As such, while this is a really valuable discussion and source of ideas, it’s been outstripped by reality a bit: `”browser”` already exists in the ecosystem and is heavily used (thanks, browserify!), and `”engines”` is still in the process of becoming whatever it’s going to be when it grows up. So I’m going to close this issue! Thanks to all for the very valuable discussion, and I’d expect to see more happening around this as the team continues to work on improving npm’s support for front-end (and other non-Node) workflows.

**Comment by jcrben** [comment]
@othiym23 it's great to hear that it's on the radar, but at the end of the day we don't seem to have an offocial sanctioned way to record this metadata. It might also be helpful to link to a place we can watch for future updates on this specific topic.
