### ISSUE TITLE
Better support for multiple module formats

### ISSUE THREAD

**Issue by domenic** [npm/npm#4323]
I am (finally) logging a series of feature requests I discussed with @addyosmani at JSConf EU, as to what would make npm the best JavaScript package manager, and help it crush all competition.

This is a tough one. The idea is that we want to make publishing, at the very least, ES6-format modules, a first-class experience in npm. We may also want to support AMD.

There are a few potential pieces here:
- A `package.json` field explaining the type of module in use. This could be useful for [CommonJS + ES6 module interop](https://gist.github.com/domenic/4748675).
- A way of "de-ES6"ifying any ES6 modules into CommonJS format, or---when ES6 support lands in V8 and is on by default, thinking long term---a way of doing the opposite.
  - This could be at install time, so that the files on disk are always CommonJS, or it could be at browserification time per #4322, using something like [deamdify](https://npmjs.org/package/deamdify).

**Comment by Globegitter** [comment]
Seeing as npm@3 is starting to become solid and es6 modules are much more common place thanks to babel and jspm I think we should really start opening up that discussion again of npm supporting it.

It would be a great addition and really make it possible to us npm as a frontend package manager without the need of browserify etc.

**Comment by othiym23** [comment]
My goodness! This certainly isn't topical! :smirk:

Yes, this is a big deal, and yes, at some point, npm may have a role to play in supporting – at the very least – ES modules when used with Node. That said, right now the primary proposals seem to only involve npm tangentially, and are [happening](https://github.com/nodejs/node-eps/pull/3) [elsewhere](https://github.com/nodejs/node-eps/issues/13). This discussion is (too) huge and sprawling as it is, but it also supersedes this issue. If Node does end up adopting the `package.json` strategy for supporting fat packages (or just ES modules in general), there are a host of features that could be added to the CLI to support that, but I'd prefer to see those filed as new issues tied to concrete use cases. As such, I'm going to close this issue with a certain amount of ambivalence – it's great that things have moved forward, although the conclusion is still looking pretty ambivalent to me. Thanks for getting this conversation started, @domenic!

**Comment by martinheidegger** [comment]
I would like to mention that I am working on a write-up on es6 modules in nodejs and it contains one section on the topic of this issue: https://github.com/martinheidegger/es6modules-nodejs#possibilities-of-package-variants
