### ISSUE TITLE
Cordova install failed

### ISSUE THREAD

**Issue by gstef74** [npm/npm#4331]
Hi there, having the same issue as closed one there: https://github.com/isaacs/npm/issues/3703
... though I updated node to the latest version v0.10.23.
It first started by uninstalling my current running cordova version then failed to re-install
I have tried running this several times with no success as some stated that could be due to timeout issues
Any idea? and many thx in advance

200 https://registry.npmjs.org/npm/-/npm-1.3.19.tgz
npm ERR! Error: shasum check failed for /Users/me/tmp/npm-59375-14sGmVC0/1387272816417-0.7217251129914075/tmp.tgz
npm ERR! Expected: dee5a33
npm ERR! Actual: ab7d89c
npm ERR! at /usr/local/lib/node_modules/npm/node_modules/sha/index.js:38:8
npm ERR! at ReadStream. (/usr/local/lib/node_modules/npm/node_modules/sha/index.js:85:7)
npm ERR! at ReadStream.EventEmitter.emit (events.js:117:20)
npm ERR! at streamreadable.js:920:16
npm ERR! at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this entire log,
npm ERR! including the npm and node versions, at:
npm ERR! http://github.com/isaacs/npm/issues

npm ERR! System Darwin 13.0.1
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "cordova"
npm ERR! cwd /Users/me/Downloads/cordova-3.3.0/cordova-cli/bin
npm ERR! node -v v0.10.23
npm ERR! npm -v 1.3.17
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR! /Users/me/Downloads/cordova-3.3.0/cordova-cli/bin/npm-debug.log
npm ERR! not ok code 0

**Comment by KenanY** [comment]
I'm gonna close this as resolved (also it is years old and `npm@1` is not really supported anymore anyways). If this is still an issue I would suggest opening a new issue at this point.
