### ISSUE TITLE
fallback for broken modules

### ISSUE THREAD

**Issue by rlidwka** [npm/npm#4337]
Feature request:

Sometimes a certain version of a package is not available or can't be installed. 

For example, if couchdb eats tarball for a dinner (happens quite frequently), or someone publishes broken package (no loss of generality in assuming npm@1.3.19). 

We can try and install earlier version of the same package in this case.

**Comment by othiym23** [comment]
Surprisingly enough, my thinking on this hasn't changed too much in the last two and a half years (my comment up-thread was actually long before I even knew that working at npm was a possibility): I don't think it's a good idea for the CLI to mechanically fall back to previous versions when the current install fails, even in an operational environment as chaotic as the 2013-era registry. If the registry loses a tarball, that's an operational error that should (and these days is) promptly be addressed by the registry's operational team; if a broken package gets published, that's what deprecation and unpublishing are for. 

There is a case to be made that it should be easier to pin a dependency below the top-level in a project more simply than by creating a shrinkwrap and editing it by hand, but that's a different use case than the one described in the original post.

As such, I'm going to close this issue. Thanks for your time!
