### ISSUE TITLE
`common-templates/.gitignore` becomes `common-templates/.npmignore`

### ISSUE THREAD

**Issue by paulvi** [npm/npm#4341]
with Node 0.10.22 

`common-templates/.gitignore` becomes `common-templates/.npmignore`
(that is, file name under some folder is changed)
when `npm install . -g` before publishing

Is it bug or there is some special way to have `.gitignore` file published?

https://github.com/Nodeclipse/nodeclipse-1/tree/master/org.nodeclipse.ui/templates

**Comment by smikes** [comment]
For the reasons why `.gitignore` is treated in this way, see #1862

Since #7252 now exists and addresses substantially the same issue, can we close this case as a duplicate?

**Comment by paulvi** [comment]
Usually older  #7252 would be considered duplicate.

**Comment by smikes** [comment]
If you want to keep this case open, that's fine.  #7252 has had more traffic recently.

**Comment by othiym23** [comment]
The discussion is much more complete over on #7252, so I'm going to close this in favor of that one.
