### ISSUE TITLE
`npm search' shows different results to https://npmjs.org/search

### ISSUE THREAD

**Issue by deoxxa** [npm/npm#4408]
The specific instance where I can replicate this is with `bittorrent-dht`.

Here are my findings *and* feelings.

<table>
  <thead>
    <tr>
      <th>Search</h>
      <th>npm search</th>
      <th>https://npmjs.org/search</th>
      <th>Thoughts</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>dht</td>
      <td> ✘ </td>
      <td> ✔</td>
      <td>Oh, ok, weird</td>
    </tr>
    <tr>
      <td>bittorrent</td>
      <td> ✘ </td>
      <td> ✔</td>
      <td>Uh, what</td>
    </tr>
    <tr>
      <td>bittorrent-dht</td>
      <td> ✘ </td>
      <td> ✔</td>
      <td>Seriously?!</td>
    </tr>
  </tbody>
</table>

**Comment by KenanY** [comment]
@deoxxa Have you seen this issue a second time after nuking your cache?

**Comment by smikes** [comment]
@deoxxa Is this still a problem for you?

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Search is likely to remain inconsistent until we get both the web site and the CLI using the same search service, which is on the larger npm road map, but maybe not for this year (we've got a lot going on!). For now, bikeshedding / discussing / complaining about the CLI's search is happening over on #6016, so I'm closing this issue in favor of that one. Thanks for the examples! Sorry search is so wonky!
