### ISSUE TITLE
Multiple recently updated packages failing on npm install

### ISSUE THREAD

**Issue by antinescience** [npm/npm#4413]
When running `npm install` on recently updated or new packages, it returns something similar to the following:

```
npm http GET https://registry.npmjs.org/tart-tracing
npm http 200 https://registry.npmjs.org/tart-tracing
npm http GET https://registry.npmjs.org/tart-tracing/-/tart-tracing-0.2.0.tgz
npm http 404 https://registry.npmjs.org/tart-tracing/-/tart-tracing-0.2.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/tart-tracing/-/tart-tracing-0.2.0.tgz
npm ERR! Error: 404 Not Found
npm ERR!     at WriteStream.<anonymous> (C:\Users\alexdancho\bin\nodejs\node_modules\npm\lib\utils\fetch.js:57:12)
npm ERR!     at WriteStream.EventEmitter.emit (events.js:117:20)
npm ERR!     at fs.js:1596:14
npm ERR!     at C:\Users\alexdancho\bin\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:103:5
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
```

It's been reported in the following issues: 
- https://npmjs.org/package/grunt-invalidate-cloudfront ( #4412 )
- https://npmjs.org/package/clean-css ( #4409  )

Is it possible that the [new implementation of Fastly](http://blog.npmjs.org/post/71267056460/fastly-manta-loggly-and-couchdb-attachments) in front of the registry has side effects when it comes to new uploads?

**Comment by smikes** [comment]
@antinescience , Is this still a problem for you?

There were some transient missing packages in the registry last January, but it has since been fixed.

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by antinescience** [comment]
This was totally just a minor registry outage, I think from when the caching in front of the registry changed? Always meant to come back and close it, just totally forgot. Closed as can't reproduce. Thanks!
