### ISSUE TITLE
registry entry not containing repository or author fields in root

### ISSUE THREAD

**Issue by BradDenver** [npm/npm#4418]
For some reason that i cant work out https://registry.npmjs.org/generator-node-mocha-star does not contain repository or author properties at is root despite them being in my package.json (https://github.com/BradDenver/generator-node-mocha-star/blob/master/package.json).

The repository and author fields are present with each version at https://registry.npmjs.org/generator-node-mocha-star, just not in the root.

I have tried npm unpublish/publish multiple times with different variations of the package.json and even tried npm init to generate a brand new package.json.

This is an issue for me as it is preventing this module showing at http://yeoman.io/community-generators.html

**Comment by OmgImAlexis** [comment]
Is this still an issue with `npm v3`? If it isn't this should be closed.

**Comment by BradDenver** [comment]
I'll check and get back to you

**Comment by busches** [comment]
@BradDenver any updates on if `npm@3` worked for you?

cc/ @KenanY
