### ISSUE TITLE
nmp ls --json returns error on successful listing

### ISSUE THREAD

**Issue by idearat** [npm/npm#4480]
When your only goal is to ask npm ls to provide you with data (via --json or --parseable) it still returns an ERR status if there are unmet dependencies. I think as long as it can parse the package.json file and return its content that it should actually return a success exit code.

**Comment by busches** [comment]
@othiym23 @iarna is this truly a bug? The behavior @domenic is describing sounds correct, changing the format wouldn't change the success status.
