### ISSUE TITLE
Install error node.js on Windows 8.1

### ISSUE THREAD

**Issue by glwilliamz** [npm/npm#4485]
When running npm install connect command the install is unsuccessful and returns errors.  How do I attach the log file?  Are there issues with installing on Windows 8.1?  How to overcome errors?

**Comment by smikes** [comment]
This looks like it was a transient `npm` registry issue from January 2014.  Is this still a problem for you?


We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as resolved / abandoned.
