### ISSUE TITLE
`npm install` always fetches dependencies

### ISSUE THREAD

**Issue by fidian** [npm/npm#4495]
In a project of mine, we have a package.json that lists several devDependencies and normal dependencies.  When issuing `npm install` a second time on different machines, I get different results.  I expect the first `npm install` to download a ton of files, but the second time shouldn't reinstall anything if the dependency is already met, right?

How to test
```
cd ~/my_project
rm -rf node_modules
npm install    # Ignore this output
npm install    # This is the one I care about
```

npm 1.3.11:
```
npm WARN package.json HypermediaAPI@0.0.0 No repository field.
npm WARN package.json pretty-js@1.0.10 No repository field.
npm WARN package.json vows@0.7.0 No repository field.
```

npm 1.3.21:
```
npm WARN package.json HypermediaAPI@0.0.0 No repository field.
npm WARN package.json pretty-js@1.0.10 No description
npm WARN package.json pretty-js@1.0.10 No repository field.
npm WARN package.json vows@0.7.0 No repository field.
npm http GET https://registry.npmjs.org/dateformat
npm http GET https://registry.npmjs.org/istanbul
npm http GET https://registry.npmjs.org/OptionParser
npm http 304 https://registry.npmjs.org/dateformat
npm http 304 https://registry.npmjs.org/istanbul
npm http 304 https://registry.npmjs.org/OptionParser
npm http GET https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/glob
npm http 304 https://registry.npmjs.org/minimatch
npm http 304 https://registry.npmjs.org/glob
karma-teamcity-reporter@0.1.0 node_modules/karma-teamcity-reporter

karma-coverage@0.1.0 node_modules/karma-coverage
├── dateformat@1.0.7-1.2.3
└── istanbul@0.1.46 (abbrev@1.0.4, which@1.0.5, nopt@2.1.2, wordwrap@0.0.2, mkdirp@0.3.5, async@0.2.9, resolve@0.5.1, fileset@0.1.5, escodegen@0.0.23, esprima@1.0.4, handlebars@1.0.12)

pretty-js@1.0.10 node_modules/pretty-js
├── fid-tokenizer@0.2.1
├── fid-tokenizer-js@0.1.3
└── OptionParser@0.1.1
```

Did something change between the different npm versions and this is now the expected behavior?  Is there a flag that says to not install if we already have met the dependencies?

An interesting thing to note is that the list of URLs that are retrieved seems to change based on how quickly I run the second `npm install` after the first.  When done immediately, it may not list any fetches.  After a few minutes it does many more fetches.

**Comment by iarna** [comment]
@smikes I'm honestly not sure how this *has* a support label, as the log there shows me adding and then immediately removing it. Github is confusing. =D

**Comment by othiym23** [comment]
This is in fact a support issue, as the current behavior is exactly as intended, and in fact in `npm@3`, there will be more checking to ensure that dependencies (and subdependencies) are not stale with respect to the semver ranges in `package.json` files. We may do less network access when the cache rewrite changes the cache so that packages are stored by shasum, but that's incidental. Making sure you have the latest version of dependencies is an important part of the installer's job.
