### ISSUE TITLE
npm + node V0.11.x does not work behind proxy

### ISSUE THREAD

**Issue by migounette** [npm/npm#4569]
@isaacs What do you think on that ?

With a node version 0.11.9 or 0.11.10, I got a regression with npm. I can't install anymore or update my node_modules via npm.

The reason of the problem is : 

npm requires request ("request": "~2.30.0") 
and request requires "tunnel-agent": "~0.3.0" 

BUT the interface change between 0.3.0 and 0.3.1 !!!

V0.3.0
TunnelingAgent.prototype.addRequest = function addRequest(req, host, port)
Vs
V0.3.1
TunnelingAgent.prototype.addRequest = function addRequest(req, options)

Enjoy....

===============================
Details
===============================
```
npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd C:\_GIT\webrtc\trunk\webrtc-js-engine
npm ERR! node -v v0.11.10
npm ERR! npm -v 1.3.22
npm http GET https://registry.npmjs.org/connect-flash
npm ERR! TypeError: Request path contains unescaped characters.
npm ERR!     at Agent.request (_http_agent.js:286:11)
npm ERR!     at TunnelingAgent.exports.request (http.js:52:22)
npm ERR!     at TunnelingAgent.createSocket (C:\Program Files\nodejs\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:117:25)
npm ERR!     at TunnelingAgent.createSecureSocket [as createSocket] (C:\Program Files\nodejs\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:185:41)
npm ERR!     at TunnelingAgent.addRequest (C:\Program Files\nodejs\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:80:8)
npm ERR!     at new ClientRequest (_http_client.js:125:16)
npm ERR!     at Agent.request (_http_agent.js:301:10)
npm ERR!     at Object.exports.request (https.js:129:22)
npm ERR!     at Request.start (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:583:30)
npm ERR!     at Request.end (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1237:28)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/isaacs/npm/issues>


```

**Comment by p4ko** [comment]
i have the same problem and need a solution. i have tried to create an cordova project with SAP Kapsel. 

i create the procect in the cmd:

cordova -d create C:\Kapsel_Projects\Kapsel_Test\  com.testproject.kapsel_test  Kapsel_Test 
"{\"plugin_search_path\":\"C:/SAP/MobilePlatform/KapselSDK/plugins/\"}"

here some information for Kapsel (http://scn.sap.com/docs/DOC-49592)

if i run this i got an TypeError

TypeError: Request path contains unescaped characers.
at new ClientRequest (_http_client.js:73:11)
at TunnelingAgent.exports.request (http.js:49:10)
at TunnelingAgent.createSockete(C:\Users\pkh\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova_lib\node_modules\request\node_modules\tunell-agent\index.js:117:25)

i have tried your solution with the new tunnel-agent, but it diddn't work.

**Comment by migounette** [comment]
Can you provide me the package.json of C:\Users\pkh\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova_lib\node_modules\request

**Comment by smikes** [comment]
Is this still a problem for you?

@bigous and @p4ko could you open separate issues if you are still having problems with `npm`?  Right now, this issue has three somewhat related problems in it, and it's easier for us to manage when each issue has a single clear topic.

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by p4ko** [comment]
Okay I have opened a new issue

https://github.com/npm/npm/issues/7404

**Comment by smikes** [comment]
Is this still a problem for you?

There is a bad interaction between two known bugs — one in `node@>0.11` and `iojs` and the other in `npm@<2.8.2`.  This can cause ECONNRESET and ETIMEDOUT errors.  The full writeup is here: https://github.com/npm/npm/issues/7699  You can fix this problem by updating your `npm` to the latest (see below).

To update npm, run `sudo npm -g install npm@latest`.

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

Thanks!

**Comment by othiym23** [comment]
Closing as resolved / abandoned.
