### ISSUE TITLE
Prune should not remove bundleDependencies.

### ISSUE THREAD

**Issue by michaelgilley** [npm/npm#4573]
As is, `npm prune` will remove bundled dependencies. This issue can be fixed by adding a check for `bundleDependencies` in `read-installed.js` (although I'm unaware if this will create other side effects).

**Comment by busches** [comment]
@othiym23 is the official comment that this is a bug then? :) @michaelgilley makes a good point that if the dependency was listed in `dependencies` or `devDependencies` then `npm prune` would not remove them.
