### ISSUE TITLE
All DocPad releases since November 28, 2013 have disappeared!!!

### ISSUE THREAD

**Issue by balupton** [npm/npm#4596]
Big problem... a whole bunch of DocPad releases have disappeared within the last 24 hours; was on a plane, landed, and everyone has been reporting they can't get the latest DocPad release, running `npm info docpad` shows none of the [releases](https://github.com/bevry/docpad/blob/master/HISTORY.md) since November 28, 2013:

http://pastebin.com/raw.php?i=ggVDFSeV

**Comment by smikes** [comment]
Can this issue be closed?

Unfortunately I don't have any more information.  @isaacs did what appears to be a definitive post-mortem above, using the information available to `npm`.  

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by balupton** [comment]
Closed. Thanks for looking into it.
