### ISSUE TITLE
Document best practices for maintaining older minor versions of modules

### ISSUE THREAD

**Issue by boutell** [npm/npm#4599]
As of yesterday, the apostrophe modules are all available in versions 0.4.x and versions 0.5.x.

0.4.x is considered stable, so a new 0.4.x version is published only to fix a bug, changing the patchlevel version number.

0.5.x is considered unstable, so we publish those with:

npm publish --tag beta

This means that (1) a naive "npm install" does not give you 0.5.x, and (2) you are allowed to publish new 0.4.x releases because the "latest" tag has not been changed. 

Fine so far!

But... what do we do when we start the 0.6.x series and still need to be able to fix security bugs in the 0.4.x series?

Should we invent another tag like:

npm publish --tag 0.4

For the first maintenance release in the 0.4.x series after 0.5.x is no longer in "beta"?

Thanks!

**Comment by othiym23** [comment]
There are [some strategies](https://github.com/npm/npm/wiki/CLI-Team-Process#the-npm-release-train) for working with [`dist-tags`](https://docs.npmjs.com/cli/dist-tag) and multiple release lines on npm, but the conventions aren't widely established and the core npm documentation doesn't really get too far into the kind of best practices documentation this invites. @ashleygwilliams has been putting a bunch of work into building out some of that kind of documentation, though, and she might have useful insight or guidance on how to get something like this written and incorporated into npm's documentation. Ashley?
