### ISSUE TITLE
Are Few last tgzs lost?

### ISSUE THREAD

**Issue by kuebk** [npm/npm#4605]
Hello,
Since yesterday I cannot install the package named core. We have 3 main branches published to npm, 0.7.x, 0.9.x and 1.0.x.

For the branch 0.9.x last version I can install is 0.9.34 which have been published on October 18th 2013. There are no tgzs for newer versions of this package.
Since the last published version was 0.9.44 seems like we lost 10 latest versions.

Similar story on 0.7.x and 1.0.x branches - anyone can help?

Thanks.

**Comment by smikes** [comment]
Can this issue now be closed?

The `npm` registry has been moved to a different hosting environment, and this seems to have been a well-documented problem (see #4596).

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
I think we can now draw a curtain across this somewhat regrettable chapter in npm's history. With the introduction of atomic published in `npm@1.4`, the removal of force-publishing (and force-republishing) from the registry, and the squashing of many of the race conditions in the CLI in `npm@2`, npm should no longer put people into these situations. My hope is that everyone on this issue eventually got their packages back into good shape, and I'm sorry a year ago this time was such a chaotic period.
