### ISSUE TITLE
Renaming gypfiles causes broken builds

### ISSUE THREAD

**Issue by stephenmathieson** [npm/npm#4630]
This relates to #2372.

I've got a non-npm dependency in a native module, which happens to have a `package.json` file.  This confuses npm and causes it to rename [this gypfile](https://github.com/stephenmathieson/node-sophist/blob/0.2.0/deps/list/list.gyp) to `binding.gyp`, thus breaking my build.

Broken tarball: http://registry.npmjs.org/sophist/-/sophist-0.2.0.tgz

TLDR;

Please don't rename gypfiles.

**Comment by busches** [comment]
@stephenmathieson is this bug still occurring using the latest `npm@2` or `npm@3`?

cc/ @KenanY

**Comment by KenanY** [comment]
Reminds me of https://github.com/npm/fstream-npm/pull/18.
