### ISSUE TITLE
Local cache can become corrupted

### ISSUE THREAD

**Issue by seldo** [npm/npm#4652]
Inspired by https://twitter.com/fivetanley/status/433305038165786624 and per conversation with @isaacs, it's possible for local registry cache to become corrupted if a package download fails or the client crashes for some other reason.

A simple fix is to add hash-checking to the client's local-fetch step so that it verifies the local package and re-fetches if it fails.

In the meantime, the workaround is to use cache clean: https://www.npmjs.org/doc/cli/npm-cache.html

**Comment by iarna** [comment]
npm@5 directly addresses this issue—it should no longer be possible for the local cache to be corrupted. If anyone encounters an issue where that does happen now, please open a new issue.!
