### ISSUE TITLE
Provide a way to flatten dependencies to one level to prevent max path issues on windows

### ISSUE THREAD

**Issue by bpasero** [npm/npm#4656]
I am facing an issue with express on windows (see https://github.com/visionmedia/express/issues/1923) where installing express ends up in path length of over 250 chars length which causes issues on Windows. The bug was closed telling me that I should lift some of the dependencies to top level to workaround this issue, but I really think that is not the right way of doing it.

Is there anything that would prevent npm from providing a command that just takes all dependencies and installs them top level? I see that you would have to support multiple versions of the same module, but I dont see any issues with that. Couldnt npm just build the dependency graph and then rewrite the modules to append a version id as needed (e.g. expres_348)? Or is there something substantial that is preventing npm for providing such an option?

Thanks,
Ben

**Comment by othiym23** [comment]
`npm@3` does tackle the bulk of this; those who find its install structure insufficiently flat can check out [`ied`](http://npm.im/ied), [`pnpm`](http://npm.im/pnpm), or [`npm-install`](http://npm.im/npm-install) for alternative npm installers that do use links to guarantee a tree that doesn't exceed a certain depth. As we've built an installer that is maximally flat by default, I'm going to close this as resolved. Thanks for your time and patience!
