### ISSUE TITLE
npm-install: Allow `@` symbols to be escaped for file/directory targets

### ISSUE THREAD

**Issue by robatron** [npm/npm#4662]
# npm-install: Allow `@` symbols to be escaped for file/directory targets

**Issue type:** Feature request

Section headers from [Contributing Guidelines: A great feature request contains](https://github.com/npm/npm/wiki/Contributing-Guidelines#wiki-a-great-feature-request-contains).

## The current situation

[npm-install](https://www.npmjs.org/doc/install.html) interprets `@` symbols as tag, version, or version range delimiter, *even if the target is a file or directory name.*

## How and why the current situation is problematic

Target files or directories whose paths contain an `@` symbol will be interpreted as a `<name>@<tag|version|version range>` target, and npm attempts to retrieve the package from the [npm registry](https://www.npmjs.org/) instead. E.g., 

    npm install foo/bar/herp/derp@123.tar.gz

Results in,

    npm http 404 https://registry.npmjs.org/foo/bar/herp/derp

## A detailed proposal or pull request that demonstrates how the problem could be solved

I propose allowing the use of an escape symbol, e.g., `\`, that one may use to escape `@` symbols for file or directory install targets, or detect a file or directory path by the head of the string, e.g., by `/` or `C:\\`. 

## A use case – who needs this feature and why?

This is especially problematic for continuous integration systems like [Jenkins CI](http://jenkins-ci.org/) that use the `@` symbol to separate concurrent workspace directories, e.g., 

    /var/lib/jenkins/workspace/mycompany-pullrequests@2/foo/my-node-module

Results in,

    npm http 404 https://registry.npmjs.org/var/lib/jenkins/workspace/mycompany-pullrequests

**Comment by othiym23** [comment]
We've changed the behavior around caching a number of times in the last couple years, and now, as long as the path is unambiguously a local path (i.e. it starts with `./` if it could be ambiguous), `npm install` or `npm cache add` will consistently do the right thing. As such, I'm going to close this as resolved, but if there are new examples of this behavior that crop up, file a new issue so we can keep getting path interpretation steadily more unambiguous.

**Comment by othiym23** [comment]
Thanks for everyone's time and patience!
