### ISSUE TITLE
error when updating legacy module with CAPS in name

### ISSUE THREAD

**Issue by dominictarr** [npm/npm#4665]
caps are no longer legal in module names, but there are a few modules that do have caps in the name, that where published before this rule was created.

I tried to update JSONStream today, but I got an error. It's good that npm prevents publishing new modules with uppercase letters in the name, but it should allow updating an old module that has uppercase letters.

the alternative would be migrating all modules to use lower case names, but this would require updating all the modules which depend on uppercase modules...

(the restriction is only in the client - so I was able to update the module, but only using an alternative npm publish - my npm-atomic-publish which a wrote a few months back as part of my npmd project.)

**Comment by smikes** [comment]
Is this still broken, or was it fixed/worked around?

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
We will probably be merging and migrating legacy packages with caps in their names as part of the rollout of registry-2, the version of the registry that supports private packages. This will be happening over the next few months.

`normalize-package-data`, the module that `npm-registry-client` and `read-package-data` use to do package name verification, will only complain about caps in package names if the normalizer is run in strict mode (which it currently is, at least in `npm-registry-client`). We should probably still warn on deprecation here, but not error. A patch for this would be most welcome! I won't be able to get to it for at least a month (by which point we may have migrated everything to all-lowercase names, rendering this issue moot).

**Comment by smikes** [comment]
I'm probably not going to bite on this -- want to spend some more time on pure-fts this weekend -- but I might circle back in a couple weeks if it hasn't been touched.  @faiq, want a fun one to work on?

**Comment by smikes** [comment]
ping to the registry team ( @bcoe ? )- is there any change to the backend wrt this issue?

**Comment by bcoe** [comment]
@smikes we now allow legacy packages to have capital letters, but don't allow new packages to be created with capital letters in their name -- long story short, I think with a change to client code, we could fix these publication issues.

**Comment by othiym23** [comment]
This has since been fixed in both `npm@2` and `npm@3` to follow the restrictions mentioned by @bcoe above – legacy packages with mixed-case names can be updated, but new packages must include only lowercase letters in their names. There's still an outstanding project to deal with the cases in which the package names collide, but that's a project for the registry team and npm support, and not the CLI team.
