### ISSUE TITLE
cannot install 

### ISSUE THREAD

**Issue by iliutastoica** [npm/npm#4672]
9409 http GET https://registry.npmjs.org/grunt-lib-contrib/-/grunt-lib-contrib-0.6.1.tgz
9410 silly gunzTarPerm extractEntry dargs.js
9411 silly gunzTarPerm extractEntry readme.md
9412 silly gunzTarPerm extractEntry .npmignore
9413 silly gunzTarPerm extractEntry README.md
9414 error Error: shasum check failed for C:\Users\Illy\AppData\Local\Temp\npm-2100-Z-hi6ej_\1392310736556-0.1490608665626496\tmp.tgz
9414 error Expected: 2a6ddfa43de542bcefd4145cc861b16d9a943443
9414 error Actual:   c5328643b4746f7727e520a034f635ada56db432
9414 error From:     https://registry.npmjs.org/pngquant-bin/-/pngquant-bin-0.1.5.tgz
9414 error     at C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:38:8
9414 error     at ReadStream.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:85:7)
9414 error     at ReadStream.EventEmitter.emit (events.js:117:20)
9414 error     at _stream_readable.js:920:16
9414 error     at process._tickCallback (node.js:415:13)
9415 error If you need help, you may report this *entire* log,
9415 error including the npm and node versions, at:
9415 error     <http://github.com/isaacs/npm/issues>
9416 error System Windows_NT 6.2.9200
9417 error command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-d"
9418 error cwd D:\Projects\workspace-Em2020\NextCasino
9419 error node -v v0.10.25
9420 error npm -v 1.3.24
9421 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@iliutastoica Are you still seeing this issue with `npm@2` or `npm@3`?

**Comment by KenanY** [comment]
Closing as abandoned.
