### ISSUE TITLE
don't allow to publish legacy versions with implicit latest tag

### ISSUE THREAD

**Issue by rlidwka** [npm/npm#4709]
Just a crazy idea to mitigate the issue with latest tag (#3397):

``` sh
$ npm init
$ npm version 2.0.0
v2.0.0
$ npm publish 
$ npm version 1.9.0
v1.9.0

# this should fail:
$ npm publish

# this should pass:
$ npm publish --tag latest

# or maybe this instead?
$ npm publish --force
```

I'm not sure it's a good one (I would be in favor of removing `latest` tag entirely), but maybe it's worth a shot.

**Comment by smikes** [comment]
So to spec out this feature in pseudo-code, it looks like this:

```
get current from registry (dist-tags, versions)
if (semver.gt(registry.latest, package.version) &&
    npm.config.get('tag') === 'latest') {
    // error: you are about to publish `package.version` as `latest`,
    // but `latest` is currently `registry.latest` ( >= `package.version`)
    // you can override this guard with `--force`
    exit process
}
```

**Comment by smikes** [comment]
Once concern is that the way config is currently implemented, there is no distinction between

```
npm publish
npm publish --tag latest
```

So making a behavioral distinction based on that would be tricky.  We do already have a `--force` config parameter, so I would probably hook the functionality off of that.

**Comment by othiym23** [comment]
This is enough of a footgun to have bitten several members of the CLI team over the years; that implies that it's something we should definitely address. There's a bit of trickiness to deal with the issue that @smikes mentions, but if you know about `npm.config.get('tag', 'cli')` then it's easy enough to work around. The CLI team will take this on _eventually_, but it may be a while, so any of y'all who feel strongly about this should feel free to put together a patch.

**Comment by iarna** [comment]
Docs for `npm.config.get` are over here: https://www.npmjs.com/package/config-chain#chaingetkey-name

And possible sources are: builtin, global, user, project, env, cli

**Comment by ljharb** [comment]
I just published https://twitter.com/ljharb/status/747909983652585473 / https://www.npmjs.com/package/safe-publish-latest to help with this - I'd love to see something like this available in npm natively (just like the `in-publish` package's effects)
