### ISSUE TITLE
confusing errors when using git repos

### ISSUE THREAD

**Issue by tj** [npm/npm#4735]
ex for `jkroso/type` of 1.1.0 you just get the following and no parent (I think that was fixed recently, but this is with 0.10.x's npm):

```
 Error: version not found: 1.1.0 : type/1.1.0
```

**Comment by OmgImAlexis** [comment]
Is this still an issue with `npm v3`?

**Comment by tj** [comment]
no clue, feel free to close

**Comment by OmgImAlexis** [comment]
@othiym23 could you please close this.

**Comment by busches** [comment]
@KenanY please close per the other comments
