### ISSUE TITLE
Getting npm ERR! registry error parsing json SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by deepakkapdi** [npm/npm#4744]
Hi,

On installing Appium through command line, I am getting the following message :

Getting npm ERR! registry error parsing json SyntaxError: Unexpected token.

I am running "npm install -g appium" after setting the proxy and registry.

Can anyone please, suggest a solution to this issue?

Thanks!

**Comment by smikes** [comment]
Is this still a problem for you?

It looks like `request` was not able to connect through your proxy.  Some people find that it helps to turn off SSL authentication (although we don't recommend that):

```
npm config set strict-ssl false
npm config set registry http://registry.npmjs.org
```

Proxy handling has been improved in newer versions of `request`; can you try updating your `node` and `npm`?

To update `node` use the latest installer (currently 0.10.35) from <https://nodejs.org/downloads>

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as abandoned.
