### ISSUE TITLE
npm silently fails to install nested dependency

### ISSUE THREAD

**Issue by fresheneesz** [npm/npm#4752]
I'm trying to install my project on a centos 6.5 machine, but one of the dependencies simply isn't installed. There's no warning or error, it even says it's downloading it - but it never makes into the correct node_modules folder. 

I tried both npm versions 1.3.24 and 1.3.21 on the centos machine with the same outcome. On windows with npm version 1.3.23, it works fine. This makes me wonder if its a platform issue. Unfortunately, nvm doesn't handle npm versions, and for some reason the node.js version right before the latest has npm 3 versions back.

I'm testing by doing `npm install async-future@0.1.12`. The dependencies are:

```
"dependencies": {
    "trimArguments": "https://github.com/fresheneesz/trimArguments/archive/e69ed3ebdfe6cf055916ba6e3a1e4b28f696da6f.tar.gz",
    "build-modules": "1.0.6"
},
```

The one that isn't completed is the trimArguments one, with the tar archive link. I assume the fact that it's an archive has something to do with it, though I don't have any proof of that. 

The output at the end of the npm install doesn't even mention trimArguments -  like it was never a dependency at all:

```
async-future@0.1.12 node_modules/async-future
└── build-modules@1.0.6 (minifyify@2.0.1, browserify@3.30.2)
```

What's going on here?

**Comment by coryarmbrecht** [comment]
Not sure if this is the exact place to mention this, but I just ran into the same (or very similar) issue. Npm install most of my nested deps, but silently skipped over a few. In the end I just `cd`'d into the respective folders and `npm install`'d from there, and everything worked like normal. It was strange why it skipped only a couple modules' deps. When there was a "skip" it would skip the entire modules deps, not just one or a few. Also, I don't think I've ran into this issue before, and it seems like I would have. Figured I'd at least repot it.

Mac OS X 10.9.5
Node 0.12.2
NPM 2.7.4

**Comment by AnimiVulpis** [comment]
Just to leave a note here:
#10727 and #11043 seem to be related (or even the same issue)

**Comment by schmod** [comment]
With npm v3.8.7, `async-future@0.1.12` appears to install correctly.  

`deadunit@4.1.0` installs without emitting an error, but is missing at least one dependency (`colors@0.6.2`), which is noted by running `npm ls`, and can be resolved by running a second invocation of `npm install`.   

#10727 primarily deals with issues with `devDependencies` duplicating transitive dependencies.  My initial investigation into the problems with deadunit seems to indicate that this is a separate issue entirely.

**Comment by r3wt** [comment]
possibly related:


https://github.com/rvagg/bl/issues/36

https://github.com/request/request/issues/2281

https://github.com/moshen/node-googlemaps/issues/120

**Comment by AndrewBogdanovTSS** [comment]
I still can reproduce this issue on:
node -v 8.9.4
npm -v 5.6.0
https://github.com/nuxt-community/typescript-template/issues/29
