### ISSUE TITLE
Issue with man property in package.json

### ISSUE THREAD

**Issue by meandavejustice** [npm/npm#4768]
Following the docs [here](https://www.npmjs.org/doc/files/package.json.html#man)

I have generated my man file and pointed to it in my [package.json](https://github.com/meandavejustice/draft-dodger/blob/master/package.json#L20).

After globally installing my package I still do not have access to the man page when running `man {package-name}`.

**Comment by busches** [comment]
@KenanY this appears to have been fixed by @bengl's PR #7299
