### ISSUE TITLE
Unpublish not working

### ISSUE THREAD

**Issue by jenius** [npm/npm#4847]
Pushed a prerelease [here](http://registry.npmjs.org/roots) last night - positive it was tagged, but something must have happened because it was released as the stable version. As soon as I realized this I tried to unpublish, as pushing an entirely unstable prerelease as the stable version is what some may call a disaster.

However, I am unable to unpublish it. When I run unpublish now, it gives me the following error, which indicates that it already has been unpublished:

```
Error: forbidden tag points to invalid version: 3.0.0-rc.3
```

However, the prerelease still clearly exists in the registry and installs fully when one attempts to install the stable release. I really am not sure what to do about this, but it's very bad. Any help would be appreciated!

**Comment by smikes** [comment]
Is this still a problem for you?

Now with `npm@2.5.0` you should be able to remove unwanted dist-tags using
`npm dist-tag rm`; then you should be able to unpublish the problematic versions.

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by jenius** [comment]
The latest version of npm is `2.4.1`, so I can't test this without installing a prerelease. I would say it shouldn't be closed until a fix is actually released and it can be confirmed that it works.

**Comment by othiym23** [comment]
`npm dist-tag` is a part of `npm@2.4.1`, which is the current stable version of npm. `npm@2.5.0` is not a prerelease version, either; it is `npm@next`, which is part of the release train-style [release process]() that npm follows. Give `npm@2.4.1` a shot; I'm reasonably confident it will do the job.

**Comment by jenius** [comment]
Ok, maybe I just misinterpreted the error message then. How do you use this command? It's not documented on npm's website that I could find. Here's my error output when trying it:

```
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "dist-tag" "rm" "roots@v3.0.0-rc.5"
npm ERR! node v0.10.36
npm ERR! npm  v2.4.1
npm ERR! code E404

npm ERR! 404 not_found document not found: -/package/roots@v3.0.0-rc.5/dist-tags

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jeff/Sites/roots/npm-debug.log
```

**Comment by othiym23** [comment]
`npm help dist-tag` or just `npm dist-tag` will get you basic usage instructions (but we've also [updated the docs](https://docs.npmjs.com/cli/dist-tag)). So, to clean up the dist-tags on `roots`, you'd run

```
npm dist-tag rm roots v3.0.0-rc.5
npm dist-tag rm roots v3.0.0-rc.4
npm dist-tag rm roots v3.0.0-rc.3
```

Does that work for you?

**Comment by jenius** [comment]
Cool, thank you. Yup, that's working correctly now. Appreciate the help and attention to detail guys, you are doing amazing work with npm. :sparkling_heart:
