### ISSUE TITLE
Error handler should direct users to report issues to the proper place

### ISSUE THREAD

**Issue by ackalker** [npm/npm#4859]
Currently, https://github.com/npm/npm/blob/master/lib/utils/error-handler.js#L273 is hard-coded to advise users to report issues at http://github.com/npm/npm/issues .

This may cause unwitting users of any half-baked forks, hacks and "shallow" (as in mindless) npm clones to dump problems on your plate ;-)

I think it would be better to get info on where to report issues from the "npm-ish" module package.json's `bugs.url` property, which is where any considerate forker/hacker/tweaker should put it.

Kind regards,

Alain

**Comment by othiym23** [comment]
Figuring out how to correctly point end users at a repo other than the npm CLI's is fraught; this sounds (to me) like replacing one supportability problem (i.e. the support load on the npm CLI issue tracker is, right now, more than the team can sustainably handle) with another one (pointing people at the wrong place to get their issue handle, and potentially creating stress for a whole bunch of other projects).

The current state of support for the CLI isn’t what the team would prefer, but it often does provide a means for the community to help itself, and I’m hesitant, therefore, to remove this messaging altogether. We’ve discussed automating issue reporting in the past, but that also doesn’t really help until there are the human resources available to meaningfully handle those automated reports. (I don’t think npm support is, by and large, a problem we can bot our way out of).

As such, I’m going to close this issue. It’s a good idea, but one with a lot of hidden hazards, and is a technical band-aid on what is, fundamentally, a people / resources problem. Thanks for your time, and for your patience!
