### ISSUE TITLE
Mailto markdown links are broken on npmjs.org

### ISSUE THREAD

**Issue by Zarkonnen** [npm/npm#4875]
I just noticed that in a module's README.md, the markdown `[email me](foo@example.com)` gets turned into `<a href="mailto:nullfoo@example.com>email me</a>` instead of `<a href="mailto:nullfoo@example.com>email me</a>`. (Note the extra `null` between `mailto:` and `foo`.

**Comment by OmgImAlexis** [comment]
@Zarkonnen is this still an issue?

**Comment by KenanY** [comment]
If this is still an issue, then I believe it belongs in the [npm/newww](https://github.com/npm/newww) repository.
