### ISSUE TITLE
Preflight check needed on `pack` or `publish`

### ISSUE THREAD

**Issue by topfunky** [npm/npm#4936]
Some errors could be caught before a module is published to npmjs.org (or packed). For example, `bin` files that end in `.js` cause problems when installed on Windows. npm currently allows this but will not run said `bin` scripts after it creates a `cmd` file on Windows.

It would be nice to have a `verify` or `preflight` command in `npm` that could check for these kinds of problems and could be added to by the community in order to make modules more reliable on all platforms.

http://stackoverflow.com/questions/10396305/npm-package-bin-script-for-windows

**Comment by othiym23** [comment]
Having a package linter that runs on `prepublish` or `preversion` would indeed be super handy; it would even be a useful improvement (eventually) to have this behavior in the core CLI itself. There have been lots of requests for validation behavior over the years, and different people want different things. I know that @sindresorhus has [put some work into a tool](http://npm.im/np) to do this, and in general that’s what the team thinks should happen: write tools to do that linting for you, and then tie it in with a lifecycle script. At some point, when there are clear cowpaths around what the community thinks is the most useful set of validations, that behavior might end up getting migrated into npm itself. For now, though, the team doesn’t have the resources to devote to this, so I’m going to close this feature request until those cowpaths are more clearly established. Thanks for your time!
