### ISSUE TITLE
Shrinkwrap Skips Nested Module Dependencies that are also included in devDependencies

### ISSUE THREAD

**Issue by Radagaisus** [npm/npm#4967]
Hello,

Running `npm shrinkwrap` on this `package.json`:

```
{
    "name": "Whatever",
    "version": "0.0.1",
    "private": true,
    "dependencies": {
        "mongoose": "3.8.8"
    },
    "devDependencies": {
        "mongodb": "latest"
    }
}
```

Will result in:

```
{
  "name": "Whatever",
  "version": "0.0.1",
  "dependencies": {
    "mongoose": {
      "version": "3.8.8",
      "from": "mongoose@3.8.8",
      "dependencies": {
        "hooks": {
          "version": "0.2.1",
          "from": "hooks@0.2.1"
        },
        "ms": {
          "version": "0.1.0",
          "from": "ms@0.1.0"
        },
        "sliced": {
          "version": "0.0.5",
          "from": "sliced@0.0.5"
        },
        "muri": {
          "version": "0.3.1",
          "from": "muri@0.3.1"
        },
        "mpromise": {
          "version": "0.4.3",
          "from": "mpromise@0.4.3"
        },
        "mpath": {
          "version": "0.1.1",
          "from": "mpath@0.1.1"
        },
        "regexp-clone": {
          "version": "0.0.1",
          "from": "regexp-clone@0.0.1"
        },
        "mquery": {
          "version": "0.5.3",
          "from": "mquery@0.5.3",
          "dependencies": {
            "debug": {
              "version": "0.7.4",
              "from": "debug@0.7.4"
            }
          }
        }
      }
    }
  }
}
```

With this log:

```
death@machine:~/dev/test-shrinkwrap:ruby-1.9.3:$ npm shrinkwrap
npm WARN package.json Whatever@0.0.1 No repository field.
npm WARN package.json Whatever@0.0.1 No readme data.
npm WARN package.json ms@0.1.0 No repository field.
npm WARN shrinkwrap Excluding devDependency: mongodb
wrote npm-shrinkwrap.json
```

Note that the mongodb dependency was skipped. Also note that mongoose depends on mongodb 1.3.23 which is the latest mongodb driver version.

But with this `package.json`:

```
{
    "name": "Whatever",
    "version": "0.0.1",
    "private": true,
    "dependencies": {
        "mongoose": "3.8.8"
    },
    "devDependencies": {
        "mongodb": "1.3.22"
    }
}
```

(Note that now the devDependency is for a different version)

This is the npm shrinkwrap, with mongodb now included:

```
{
  "name": "Whatever",
  "version": "0.0.1",
  "dependencies": {
    "mongoose": {
      "version": "3.8.8",
      "from": "mongoose@3.8.8",
      "dependencies": {
        "hooks": {
          "version": "0.2.1",
          "from": "hooks@0.2.1"
        },
        "mongodb": {
          "version": "1.3.23",
          "from": "mongodb@1.3.23",
          "dependencies": {
            "bson": {
              "version": "0.2.5",
              "from": "bson@0.2.5"
            },
            "kerberos": {
              "version": "0.0.3",
              "from": "kerberos@0.0.3"
            }
          }
        },
        "ms": {
          "version": "0.1.0",
          "from": "ms@0.1.0"
        },
        "sliced": {
          "version": "0.0.5",
          "from": "sliced@0.0.5"
        },
        "muri": {
          "version": "0.3.1",
          "from": "muri@0.3.1"
        },
        "mpromise": {
          "version": "0.4.3",
          "from": "mpromise@0.4.3"
        },
        "mpath": {
          "version": "0.1.1",
          "from": "mpath@0.1.1"
        },
        "regexp-clone": {
          "version": "0.0.1",
          "from": "regexp-clone@0.0.1"
        },
        "mquery": {
          "version": "0.5.3",
          "from": "mquery@0.5.3",
          "dependencies": {
            "debug": {
              "version": "0.7.4",
              "from": "debug@0.7.4"
            }
          }
        }
      }
    }
  }
}
```

Also note that you have to `rm -rf node_modules && rm -rf npm-shrinkwrap.json` before doing the second shrinkwrap to reach this results.

This also happens for the more trivial case of

```
{
    "name": "Whatever",
    "version": "0.0.1",
    "private": true,
    "dependencies": {
        "mongodb": "1.3.23"
    },
    "devDependencies": {
        "mongodb": "1.3.23"
    }
}
```

and the shrinkwrap:

```
{
  "name": "Whatever",
  "version": "0.0.1",
  "dependencies": {}
}
```

**Comment by tjdavey** [comment]
We've encountered this on a few occasions under the same circumstances as above. When identical dependencies are both a nested production dependency and a dev dependency `npm shrinkwrap` will not include the dependency for the nested production dependency.

The current workaround for us is to remove the node_modules folder and shrinkwrap file and install with `npm install --production` before shrinkwrapping.

```
rm -rf node_modules
rm -f npm-shrinkwrap.json
npm install --production
npm shrinkwrap
```

**Comment by danielwrobert** [comment]
I don't know if this quite solves your problem but to include packages listed under `devDependencies`, you need to run `npm shrinkwrap --dev`. See [docs](https://docs.npmjs.com/cli/shrinkwrap) for more info. 

I just ran into an issue with that and thought I'd share here just in case it's helpful! :)

**Comment by dotchev** [comment]
We just hit the same issue. In our case we have `clone` in `devDependencies` and it is also referenced by some of our `dependencies`.

Seems the same as #4161

**Comment by jdrydn** [comment]
We just hit this issue too. Our case was with `glob` in `devDependencies` that was also referenced by `cld`, and since this was the first time this occurred it really fucked with our deployment process.

[This comment](https://github.com/npm/npm/issues/4161#issuecomment-153910109) on #4161 suggests   it's been fixed in `npm@3` although I hear that's buggered anyhow with regards to `shrinkwrap` so that's not exactly a useful fix..

In the end, our solution was to just include `glob` in our `dependencies` and overlook the fact it's not used in a production environment at all :cry:

**Comment by koresar** [comment]
Hello.
We are using `npm@2` as our main package management tools. Not using `npm@3` is a business decision.
We hit this bug second time already.
Are there any plans to fix it @iarna ?
Cheers
