### ISSUE TITLE
"npm update --link" globally installs & links things I never set up for "npm link"

### ISSUE THREAD

**Issue by boutell** [npm/npm#4987]
The "--link" option of "npm install" and "npm update" has very little documentation, but my hope was that it would link my project to any needed modules that I have actually set up via the "npm link" command.

That is, if I've done this:

[git clone the apostrophe module]
npm link apostrophe

And my project depends on "apostrophe", "npm update --link" would establish the symlink.

And it does. However, it also performs a global install and links to other modules that I never set up for npm link.

For instance, if my project depends on both "apostrophe" and "optimist", but only "apostrophe" is something I've set up with "npm link", then the --link option does a global install of optimist, and symlinks to that. Which is something I didn't ask for and don't want because it means I can't have separate projects depend on separate versions of modules I'm *not* developing.

Hope this is clear.

Some questions:

1. Is this the intended behavior?
2. Is it useful this way?
3. Could it be "fixed" to work the way I'm hoping - linking only to things that I've actually git cloned and typed "npm link" for?

Thanks!

**Comment by othiym23** [comment]
> Is this the intended behavior?

Yes. Running `npm install --link` and `npm update --link` use the same underlying mechanism as `npm link`. All three of them require the package to be globally installed and to have all their own dependencies installed. (Technically speaking, `npm update` calls `npm install` after calling `npm outdated`, and then `--link` is picked up during the call to install, which may make how this all happens a little easier to understand.)

> Is it useful this way?

I believe so! It could probably be more useful with some tweaks, but I believe that's true of how npm handles linking in general.

> Could it be "fixed" to work the way I'm hoping - linking only to things that I've actually git cloned and typed "npm link" for?

That's _a way_ it could work, but it would require significant changes to a bunch of pieces of the installer, and would probably be at least as surprising to a large number of users as the current behavior was to you. As such, I think I'm going to close this issue, with the proviso that if you have a proposal for how to make linking work more effectively in this case, I'd love to see it submitted as a new feature request. Thanks for your time and your patience!
