### ISSUE TITLE
npm "lifecycle" scripts order: `prepublish` AFTER `install` during `npm install`?

### ISSUE THREAD

**Issue by JamesMGreene** [npm/npm#5000]
``` shell
$ node -v
v0.10.26

$ npm -v
1.4.3

$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.9.2
BuildVersion:   13C64
```

I've always known that any `prepublish` scripts will also be run during a parameter-less `npm install`, which makes _some_ sense.  However, I've noticed that, at least with this current version of NPM, the `prepublish` script runs _after_ the `install` script (I have both... trust me, they're both necessary).

This seems counter-intuitive to me, and can lead to some problems, as I would expect `prepublish` to actually be run first (except, perhaps, when first installing dependencies) as that better aligns with the actual usage: I make a package, I publish it, a consumer installs it.

**Comment by DaSchTour** [comment]
Is there anything moving here? This is really a big and bad issue and forces very bad hacks. Just consider usage of jspm, a build script that creates dist bundles on top of jspm. So I need to add a jspm install to prepublish, making the build process take even longer, just to prevent the dist build on initial install to fail. Why do I need to do the things I want to ensure to be done before publishing in the first and initial step of a package being checked out. It's insane.
