### ISSUE TITLE
npm init and user input validation

### ISSUE THREAD

**Issue by riston** [npm/npm#5044]
Currrently it's seems all the validation is done only when all the information has been entered. Actually this is really bad user experience, there should be at least validation after each field filing and possible way to correct the field not throw error and start again.

Here is my case, I wanted to init new package, filled all the project information, but accidentally inserted package version ```0.01 ```, after filling all the fields I get error:

```bash
npm ERR! Error: Invalid version: "0.01"
npm ERR!     at Object.module.exports.fixVersionField (/us
r/local/lib/node_modules/npm/node_modules/read-package-jso
n/node_modules/normalize-package-data/lib/fixer.js:180:13)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modul
es/read-package-json/node_modules/normalize-package-data/l

```

**Comment by othiym23** [comment]
This was fixed by fc52160d0223226fffe4166f42fdfd3b899b3c1e, which we landed over a year ago. Thanks for your time and patience!
