### ISSUE TITLE
npm link and multiple levels of peerDependencies = psychedelic mess

### ISSUE THREAD

**Issue by mpj** [npm/npm#5080]
So _npm link_ behaves in (what I think is) an unexpected way when you multiple levels of packages that depend on the same _peerDependency_. 

Look at the dependency chain below. I have a Knockout app, _spotify-app_, that relies on a _spotify-framework_ module that in turn relies on a _spotify-library_ module. All three depend on _knockout_ and it's very important that there is only one instance of Knockout in the app because reasons. Thus, _spotify-app_ requires _knockout_ as a normal dependency, and the _spotify-framework_ and _spotify-library_ module both list it as a _peerDependency_. This dependency chain **works fine**, until you decide to do development on the _spotify-framework_ module and try to use _npm link_ - then the mad hatter comes in and gives you spiked cookies and everything goes pink fluffy unicorns dancing on rainbows.

This is what happens: You happily clone the _spotify-framework_ from git, and then you run _npm link_ in its directory, in preparation of linking it in from _spotify-app_. The problem here is that _npm link_ will run spm install (I think) under the hood. npm will look at the _peerDependencies_ of _spotify-library_, and then install an instance of _knockout_ inside the node_modules of _spotify-framework_, because it thinks that _spotify-framework_ is the top-level module. This will silently cause ***duplicate versions*** on _knockout_, because _spotify-app_ will install another instance of _knockout_ itself. It's obvious what happens when I write it down like this, but it was extremely confusing to figure out what happened here, I tell you. 

I'm not sure how this should be solved, but I'm leaning towards that npm link should never install peerDependencies on it's own, because it's most likely not the top-level module if it's being linked. 

```javascript
{
  "name": "spotify-app",
  "version": "0.0.1",
  "private": "true",
  "dependencies": {
    "knockout": "~3.0.0",      
    "spotify-framework": "0.0.1"
  }
}

{
  "name": "spotify-framework",
  "version": "0.0.1",
  "private": "true",
  "peerDependencies": {
        "knockout": "^3.0.0",
  },
  "dependencies": {
    "spotify-library": "0.0.1"
  }
}

{
  "name": "spotify-library",
  "version": "0.0.1",
  "private": "true",
  "peerDependencies": {
        "knockout": "^3.0.0",     
  }
}
```

**Comment by zxqfox** [comment]
@domenic @isaacs Guys, I see that this thread is full of controversial comments but if you want to deprecate peer deps, that perfectly solves just one problem and makes a lot of pain for all other, probably we just need some sort of a pluginizer module, that will check on postinstall (or somehow) version of plugin supported host app and a host itself.

I'm agree that `peerDependencies` is a mistake but it was a good thing in plugin case. There are a lot of modules of this kind and there should be a replacement. Just for plugins.

**Comment by kilianc** [comment]
I don't understand why is npm problem to fix poorly designed plugin systems. The plugin host or plugin itself, based on the api they use, should check for compatibility. If we `host.use(plugin())` just let `host` assert plugin instance `.version` semver.

**Comment by zxqfox** [comment]
Based on https://github.com/npm/npm/issues/6565#issuecomment-78319337

@getify What is your problem? I don't get it.

**Comment by zxqfox** [comment]
@kilianc It's a pretty common problem related to packages. NPM is package manager. You really want one more package manager for plugins?

**Comment by kilianc** [comment]
@zxqfox didn't say that, I am just saying the plugin system should not rely on npm and figure out what works or not by himslef

**Comment by zxqfox** [comment]
@kilianc You just suggest to check versions in each host app. It means exactly: mini package manager inherited into host app. I really don't see any reasons to drop `peerDeps` without a good replacement for npm-packaged plugins.

**Comment by jhnns** [comment]
> the plugin system should not rely on npm and figure out what works or not by himslef

Your suggested approach only works on runtime. You need to run the application in order to find out if there are incompatibilities. Imho that should be reported without actually running the application.

**Comment by magalhas** [comment]
So what's the state on this? I had to use [https://github.com/jaredhanson/node-parent-require](jaredhanson's parent-require) to get around this. The sad thing is that the module is already two years old, it works, but how can such a bug be around for so long?

**Comment by othiym23** [comment]
@magalhas see https://github.com/npm/npm/issues/6565#issuecomment-74971689 for details on the plan for `peerDependencies` in `npm@3`.

**Comment by magalhas** [comment]
@othiym23 unfortunately the comment doesn't say anything about the bug related to peer dependencies inside linked npm packages.

**Comment by othiym23** [comment]
@magalhas that's probably best tracked as a separate issue – this thread is way too large and all over the place to get that into specific issues.

**Comment by aexmachina** [comment]
@zxqfox okay, that's an interesting suggestion. Does that mean that I need to instruct people to install both packages `npm install ember-cli-sass node-sass`, and then ember-cli-sass would fail if node-sass isn't available?

**Comment by zxqfox** [comment]
@aexmachina Actually, you can built-in default `node-sass` version with it (I mean deps in package.json):
```
  "dependencies": {
    "node-sass": "^3.0.0-beta"
  },
```
But if user need something other he should install his package manually and pass it explicitly into contrustor (e.g. {useThisSass: require('my-node-sass')}).

**Comment by aexmachina** [comment]
Aha, yes that's an excellent and simple solution. Will do, thanks.

**Comment by jhnns** [comment]
@zxqfox Interesting solution for that type of problem :+1:

**Comment by zxqfox** [comment]
@jhnns `jscs` using it like year or more ;-) Not mine.

**Comment by adametry** [comment]
@zxqfox, `gulp-eslint` used a similar approach a while back. While it allowed dependents to adopt `eslint` updates faster than `gulp-eslint`, it also side-stepped dependency management and complicated the module's API (now *how* the dependency is used must be considered API). 

The best approach I've found is a loose, but tested, dependency version (e.g., ">=0.5.0 <1.1.0") that allows dependents to declare a more specific version if needed (e.g., "0.8.x"). When a dependent's version is compatible, NPM will only install one module for both to use; When incompatible, each gets a separate module that meets it's dependency version. The biggest issue with this approach is that incompatibilities occur silently. A lesser conflict is the subjective "bad practice" of declaring loose NPM `dependencies`.

**Comment by matthewp** [comment]
@zxqfox 

> But if user need something other he should install his package manually and pass it explicitly into constructor (e.g. {useThisSass: require('my-node-sass')}). And in module code: opts.useThisSass || require('node-sass').

This won't work for browser libraries, imports are parsed statically (with es6 and most commonjs bundlers).  What this means is that you will potentially bundle 2 versions of the same library, which is not what you want.

**Comment by gajus** [comment]
I have read the entire thread and I cannot make out what is the latest regarding the original issue.

From what I understand, this is not getting "fixed" in NPM@2. Does NPM@3 install peerDependencies?

**Comment by mathieumg** [comment]
> Does NPM@3 install peerDependencies?

It doesn't anymore, and the module tree is flat unless a module requires an incompatible version, then it will install it under itself. (As if you had run dedupe on npm2) npm3 will warn if a peer dep isn't satisfied, but it will not automatically install it anymore.

**Comment by gajus** [comment]
What is the reason this issue remains open?

**Comment by othiym23** [comment]
Now that `npm@3` is a stable release series, this issue can be closed!

**Comment by gajus** [comment]
I was still struggling with my React setup using `peerDependencies`:

Now that `peerDependencies` are no longer installed for the `dependencies`, `dependencies` could not load their `peerDependencies`. This can be solved using webpack `resolve.fallback` configuration as I have explained in this SO QA: [How to make a linked component peerDepdencies use the equivalent node_modules of the script being linked to?](http://stackoverflow.com/questions/33437271/how-to-make-a-linked-component-peerdepdencies-use-the-equivalent-node-modules-of).

**Comment by magalhas** [comment]
So actually the issue still persists if for instance the lib being linked have for instance `React` as a devDependency so that tests can be executed?

**Comment by gajus** [comment]
Correct me if I am wrong, but npm link does not install devDependencies. Even if you npm install; npm link, devDependencies will not be made available to the script being linked.

**Comment by rally25rs** [comment]
Sorry to rez a closed thread, but wondering if anyone has a recommendation on how to proceed resolving `peerDependencies` issues upgrading from v2 to v3.

We used `peerDependencies` (probably incorrectly?) to make sure all our projects used the same version of common libs, so that we didn't have to make sure that 6 projects don't get out of sync in their dependency versions (which they naturally would if devs had to update them all manually).

For example:

Project "common-stuff" has:

```
  "peerDependencies": {
    "brfs": "^1.4.0",
    "colors": "^1.0.3",
    "grunt": "~0.4.5",
    "grunt-browser-sync": "^1.5.3",
    "grunt-browserify": "^3.2.1",
    "grunt-contrib-clean": "^0.6.0",
    "grunt-contrib-concat": "^0.5.0",
    "grunt-contrib-copy": "^0.7.0",
    "grunt-contrib-handlebars": "~0.10.2",
    "grunt-contrib-jshint": "^0.10.0",
    "grunt-contrib-less": "^0.12.0",
    "grunt-contrib-uglify": "^0.6.0",
    "grunt-contrib-watch": "^0.6.1",
    "grunt-karma": "^0.9.0",
    "grunt-search": "^0.1.6",
    "jshint-stylish": "^1.0.0",
    "karma": "^0.12.25",
    "karma-junit-reporter": "^0.2.2",
    "karma-mocha": "^0.1.9",
    "karma-phantomjs-launcher": "^0.1.4",
    "karma-chrome-launcher": "~0.1.3",
    "load-grunt-config": "^0.16.0",
    "mocha": "^2.0.1",
    "chai": "^1.9.2",
    "hbsfy": "^2.2.1",
    "debowerify": "^1.2.0",
    "handlebars": "^3.0.3",
    "watchify": "3.2.1"
  },
```

Then project "ProjectOne" just needs:

```
  "devDependencies": {
    "common-stuff": "git+ssh://git@github.com:MyAccount/common-stuff#master"
  },
```

And project "ProjectTwo" just needs:

```
  "devDependencies": {
    "common-stuff": "git+ssh://git@github.com:MyAccount/common-stuff#master"
  },
```

so if we need to add/remove/update a dependency, we just have to do it in "common-stuff" instead of editing 6 projects individually.

Is there a better why to manage this in npm 3?
At the moment everyone who has upgraded past v2 can no longer build, and I'm hesitant to copy/paste all the dependencies to every individual project because it becomes a maintenance pain for the future...

**Comment by jhnns** [comment]
> We used peerDependencies (probably incorrectly?)

Yes, I think so :)

Usually, I recommend to actually duplicate the dependency list and add it to "ProjectOne" and "ProjectTwo". It may seem like a maintenance nightmare at first, but consider the other possibility: What if "ProjectOne" needs feature X and therefore needs to update dependency Y which forces you to update the dependency for every other project – which might not be possible in some situations (also known as dependency hell)?

However, there are situations where ProjectOne, ProjectTwo, ProjectThree, etc. are almost identical. In this situation, it *is* probably a good idea to keep a list of common dependencies. Then it'd move all the dependencies from `peerDependencies` to `dependencies` and just re-export every module inside "common-stuff".

All you have to ask yourself if ProjectOne, ProjectTwo, ProjectThree have so much in common that it is worth it to enter dependency hell :grinning:

**Comment by cpsubrian** [comment]
Also, ask yourself if you even need ProjectOne, ProjectTwo, and ProjectThree to even be different modules. In general, modularity is awesome and very important. Especially with utility modules or very separate pieces of functionality. But in that case the dependencies are likely to differ anyhow. If what you're really building is a framework of some type, you may find splitting the framework up into different pieces is more trouble than it's worth in the long run. This very thing happened with my node framework, cantina. I started off with the noble goal of splitting everything out into its own modules. Core, web, redis, models, validators, vhosts, caching, etc, etc. etc. It heavily uses peer-dependencies  to juggling deps between 'plugins' and also the core. Now, updating all the modules is a nightmare and its causing the project to get stale. Since this is a server-side framework there really isn't as much a gain as I thought for splitting it all out. Since I generally use a good portion of the plugins in each project, the whole thing really ought to just be one big beast.

**Comment by rally25rs** [comment]
Thanks for the replies @jhnns and @cpsubrian 

In this case these are all projects that share a common build environment, basically. In our case, all projects share the same Grunt tasks, same unit testing framework, same linter, etc.
This makes all our projects have the same grunt tasks, so as devs move between the projects, all the build processes use the same libraries.

It would be nice if there was a way in package.json to link to/import from another external file, which would be another way to deal with this.

Anyway, looks like I'll be copy/pasting the dependency list around. Thanks again.

**Comment by dlongley** [comment]
An update for people like @indexzero and @hueniverse: in node 6.x symlinks to peer dependencies are be preserved (not dereferenced using realpath), so that should make doing things like symlinking to peer dependencies during development more pleasant.
