### ISSUE TITLE
`npm install --save` etc. should also update npm-shrinkwrap.json

### ISSUE THREAD

**Issue by derekprior** [npm/npm#5083]
It appears the shrinkwrap workflow for npm is:

1. `npm install --save whatever`
2. develop feature that needed that dependency
3. `npm shrinkwrap` to shrinkwrap it.

That third step is manual. That seems appropriate if a project is not already using shrinkwrap, but if the package author has already expressed a desire to shrinkwrap, shouldn't `npm install` respect that and automatically update the shrinkwrap?

If the developer bails on the feature, rolling back is just a `git checkout` away. But if the developer forgets to `npm shrinkwrap` then we're going to get 'works on my machine' failures, which are extremely frustrating.

Can `npm install` be made to detect the presence of the shrinkwrap file and do the right thing? This would also require the shrinkwrap file (or some related .rc file) to contain memory of the options used for shrinkwrapping (whether you passed `--dev` or not).

**Comment by johnnyshields** [comment]
+1 on making shrinkwrap the standard workflow. It saves a ton of time investigating esoteric dependency breakages.

**Comment by Diokuz** [comment]
+1

**Comment by andrewboni** [comment]
+1 for this, would be great not to have to need to run `npm shrinkwrap` every time

**Comment by mikemaccana** [comment]
If it's handy, I use:

    function npm-inshrink () {
    	npm install --save ${1} && npm shrinkwrap;
    }

In my `~/.bash_profile`. Run `bash -l` or open another tab for the changes to take effect.

**Comment by nextmat** [comment]
Just curious if anyone has a better workaround for this currently? 

Makes sense we can wrap the process with our own scripts to ensure behavior, not sure if another consensus on best practice here has emerged?

**Comment by othiym23** [comment]
The simplest workaround is simply to wait for `npm@3`, which is increasingly imminent (barring a major regression, `npm@3.0.0` will be dropping next week). It has a number of affordances to make working with `npm install --save`, and should be enough to close this issue once it's gotten a few patch releases.

**Comment by nextmat** [comment]
Great, thanks for the quick response @othiym23

**Comment by Raynos** [comment]
> npm@3.0.0 will be dropping next week

:tada: :tada: :tada:

**Comment by othiym23** [comment]
Before everyone starts yelling about the `npm@3` release everywhere, I want to clarify that `npm@3.0.0` will be :fire:_**BETA SOFTWARE**_:skull:, and will spend at least a few releases on a separate `dist-tag` so we can fix any glaring misfeatures and deal with the most heinous bugs. In particular, it's going to be a soft transition for at least a month to give the ecosystems affected by the [changes to `peerDependencies`](https://github.com/npm/npm/issues/6565) a chance to come to grips with the very different way `npm@3` handles them.

**Comment by iarna** [comment]
Happily this is indeed in npm@3. If you all see any problems with this please open a new issue and we'll get them fixed right up! I'm closing this ticket as resolved. =)
