### ISSUE TITLE
`npm install` doesn't update changed git url dependencies

### ISSUE THREAD

**Issue by parshap** [npm/npm#5090]
Given the following `package.json`:

```json
{
  "name": "npm-dep-test",
  "version": "0.0.0",
  "dependencies": {
    "immutable-object": "parshap/immutable-object#master"
  }
}
```

`npm install` will correctly install `parshap/immutable-object@master`. If I then change the dependency to be:

```json
{
  ...
  "dependencies": {
    "immutable-object": "parshap/immutable-object#callback"
  }
}
```

and run `npm install`, no change will be made. Is this because the `version` field in immutable-object's package.json is the same in both commits?

If I use a full git url (e.g., `git://github.com/parshap/immutable-object#callback`), `npm install` will update to the new commit as expected. I would expect the "short" git url and the "full" git urls to behave the same way. Am I mistaken?

I also see some different behavior in that with the "short" git url npm seems to make a request to the npm registry for `immutable-object`, whereas with the "full" git url it only touches the git repo.

**Comment by iarna** [comment]
Closing this as fixed in [npm/npm#multi-stage](https://github.com/npm/npm/tree/multi-stage)
