### ISSUE TITLE
Add prompt for browser keyword to `npm init`

### ISSUE THREAD

**Issue by domenic** [npm/npm#5106]
Spinning off from #4321, I think this is a great idea. `npm init` should, after keywords, ask:

"Is this package intended to be usable in the browser? (y/n)" [default n]

And if the answer is y, then it adds the `browser` keyword to the keywords list.

Wordsmithing welcome on the question (but if you disagree with the keywords approach then go argue that over in #421).

**Comment by othiym23** [comment]
The team talked this over a bit, and we agree that this is a useful piece of a larger solution. That immediately poses the question of what the _problem_ to be solved here is, and @iarna and I believe that’s paving the cowpaths that make it easier for web developers to share code that can be used in front-end applications. The full feature, then, requires either other pieces within the CLI, or within the rest of the product, to make those packages more easily discoverable and usable. That’s a good project, but it’s not one that’s on npm’s road map right now.

As such, that means the CLI team is unlikely to get to this particular request any time in the foreseeable future. At the same time, we agree that it _is_ useful, so if it were to be provided to us as a patch to `init-package-json`, we’d take it with thanks. Thanks for your time, and your patience!
