### ISSUE TITLE
Check dependency versions before running any commands

### ISSUE THREAD

**Issue by domenic** [npm/npm#5107]
a.k.a., "put an end to self-trolling."

This is a very common experience when working on teams of size larger than one:

- The team has decided to .gitignore their `node_modules`.
- Team Member A updates foo, e.g. `npm install foo --save`.
- Team Member A commits the resulting `package.json` and pushes to Git.
- Team Member B finishes all their work on their current feature, and is ready to rebase.
- They do so, but, now all the tests are failing! Or perhaps they aren't failing, but the app is acting weird.
- After a half-hour of sadness and frustrating debugging, Team Member B finally figures out they forgot to run `npm install` to pick up the latest changes.

Proposal: before _any_ operations involving npm, including e.g. `npm test`, npm checks to see if all versions match the ones declared in package.json.

Complexities:

- Ideally this should be multi-level, i.e. recursing and doing semver matches.
- If a shrinkwrap file is present, this should be able to do exact version matching against the shrinkwrap file at every level in the tree.
- It's unclear how much overlap there is between this code and the validation `npm ls` already performs. I suspect `npm ls` code does not deal with shrinkwrap well, and is not as fast as it could be (e.g. I think it does normalization). But it might be a start.

The minimum viable version of this for Ember is fixing #5083 plus making this work for shrinkwrap.

/cc @stefanpenner

**Comment by othiym23** [comment]
Reading the installed tree from disk isn’t a cheap operation; particularly with the large trees generated by `ember-cli`, it’s a very memory- and CPU-intensive operation. Given that performance is already a major concern for what feels like a majority of CLI users, this narrows the applicability of this kind of check to the relatively small subset of operations that directly deal with installed dependencies (particularly `npm install` and `npm publish`).

Re: @Raynos’s points about shrinkwrap behavior when checking out branches, `npm@3` already handles many of the cases he describes. When changing branches, `npm install` will now bring the installed tree into line with what’s in the changed shrinkwrap file. That doesn’t cover all the use cases described by @domenic and @stefanpenner, but it does make keeping your tree in sync much less painful for most users most of the time.

The team agrees that in general it would be useful to help users not push repos or publish packages with package trees in inconsistent states. As a few of you have alluded, this is something that could be built out as a separate utility, and added to projects via package lifecycle scripts or repo hooks (which also goes a long way towards remedying the performance concerns above – if you’re consciously opting into this functionality, you’re much less likely to be displeased with the resulting slowdown). I think that’s the best way to lay down a cowpath that the CLI could later pave by incorporating this functionality into `npm ~lint` (final name TBD) that could be tied to the installation or publishing workflow. There’s a _chance_ that the CLI team itself will get to doing this itself, as part of improving the user experience of locking dependencies with the CLI (a project we’re still in only the earliest stages of defining). I can’t commit to that, though, and so I’m going to close this issue. If you put together something to do this, please bring it to our attention.

We further agree that when using the CLI to manage dependencies, it should never be possible to put `package.json` and `npm-shrinkwrap.json` at odds. In the cases where that (still) happens, those are bugs that should be fixed, so please file them as such.

Thanks to all for the discussion, as well as for your time and patience!
