### ISSUE TITLE
Consider setting `npm config save true` by default

### ISSUE THREAD

**Issue by domenic** [npm/npm#5108]
When you do `npm install foo`, it seems strictly more useful for `foo` to end up in your `package.json` than for it not to, and to be marked as extraneous by npm.

Ember is being somewhat insistent that they want this user experience for their users. If we don't think this is a good change to make (although I think it is), then an alternative would be #4751 which would allow them to set up Ember projects by default to have an .npmrc with `save` set to `true`.

Possible complications:

- Ideally #5083 should get fixed too to make this more usable with shrinkwrap around.
- If this config is set correctly, will `--save-dev` and friends correctly overwrite it? I think from my recollection of the code, the answer is "yes."

/cc @stefanpenner

**Comment by Globegitter** [comment]
:+1: with the addition of a `--no-save` flag sounds like a great improvement for developer experience. Just happened to me and a developer completely new to node was confused about the error they were getting due to the missing package.

**Comment by KenanY** [comment]
Just adding a note: https://github.com/npm/npm/issues/6567 should be fixed before this is ever implemented.

**Comment by aug-riedinger** [comment]
Coming from #12031 :smile: 
What's the next step here? As far as I'm concerned, I am really in favor of this change.

Is a PR expected? Does this need to be further discussed? I can give out my reasons to require this if necessary.

Cheers

**Comment by olalonde** [comment]
Bump. `--save` should default to true.

**Comment by othiym23** [comment]
In the last couple years, quite a bit has changed here, which renders parts of this issue moot:

1. Per-project `.npmrc` files [now work as expected](https://github.com/npm/npm/commit/1707fcedb7503251eb77719aba7ac52931721205), answering `ember-cli`’s need to be able to set this as the default on a per-project basis.
2. To @KenanY’s point, #6567 has also been addressed.
3. It’s also easy enough to run `npm config set save true` as an end users.

That said, there are still a number of rough spots when making `--save` the default:

1. While the cognitive load of having to remember `--save` or `--save-dev` at install time is an irritating niggle, it does force you to choose at install time whether a package is a `dependency` or `devDependency`.
2. Moving packages between sections in `package.json` is still a little more difficult than it should be, which makes cleaning up after things when you forget to specify that somethign is a `devDependency`.
3. There are further complications related to shrinkwrap, although I think those are best considered bugs in shrinkwrap’s current implementation.

I don’t think it’s in the best interests, as a result, to opt everyone into saving everything by default. That said, patches to any or all of the above would be most welcome, and would pave the way towards an improved shrinkwrap experience (and install experience) where setting `--save` to true would be a lot more pleasant / less confusing for everyone.

**Comment by cben** [comment]
This was implemented in npm 5, apparently by c0d73dbed4f1e5699de1914c1cc291973ad87c9f 
I think this is great 👏 but coming from [HN discussion](https://news.ycombinator.com/item?id=14423321) where a user hated it, so questions on opting out:

1. This affected both `npm install` and `npm uninstall`, right?  Anything else?

2. You can opt out by `npm install --no-save` and and `npm uninstall --no-save`, right?

    - This is not documented.  Perhaps it's implied that all boolean options have a `--no-` variant (?), but that's not obvious reading doc/cli/npm-install.md, doc/cli/npm-uninstall.md, they currently sound as if you can only choose where to save:
        > npm install takes 3 exclusive, optional flags which save or update the package version in your main package.json: --save ... --save-dev ... --save-optional ...
    - The very fact `--save` is default is not clear from the docs.  IMHO important, given that existing users may be surprised.
    - May also want to update doc/files/package.json.md.
    - And I see CHANGELOG.md is still not up to 5.0?  Consider meanwhile linking to  http://blog.npmjs.org/post/161081169345/v500.  Found also https://twitter.com/maybekatz/status/859193277894991872 about this change.

3. Can one restore old behavior by `npm config set save=false`?

cc @iarna @zkat (no pressure, thanks everyone for npm!)

**Comment by zkat** [comment]
@cben `npm config set false` will restore the old behavior in pretty much its entirety, afaik.

**Comment by giltayar** [comment]
Unfortunately, it's saving the `package.json` even if you just do `npm install` without a package (this happens only if `save` is set to `true`). This is problematic, because some build systems (specifically one that I am writing) are make-like and look at the modification time of the file to determine whether to do `npm install`.

Any reason not to fix this? I can look at the code and try to fix this.

**Comment by getify** [comment]
The docs still say that the `save` config is defaulted to `false`. I was surprised by unexpected package.json updating, and even more confused when looking at the docs -- thought I had accidentally changed my package or global npm config.

Please update the docs to reflect this change in npm@5.

**Comment by jhuckaby** [comment]
@zkat Did you mean to say `npm config set save false`?  Your comment is missing the word `save`.
