### ISSUE TITLE
tar.unpack untar error

### ISSUE THREAD

**Issue by aredo** [npm/npm#5133]
i try npm install on Ubuntu 12.04, i getting error about `tar.unpack untar error`
it seem related with mongoose/mongodb

this one screenshoot from my terminal

![screen shot 2014-04-23 at 7 00 15 pm](https://cloud.githubusercontent.com/assets/201664/2777087/03c89ffa-cadf-11e3-8a68-733f3ad9849d.png)

this one list of my node modules

```javascript
"express": "^3.5.1",
    "jade": "^1.3.0",
    "mongoose": "3.8.8",
    "connect-mongo": "latest",
    "connect-flash": "latest",
    "passport": "^0.2.0",
    "passport-local": "^0.1.6",
    "passport-facebook": "^1.0.2",
    "passport-twitter": "^1.0.2",
    "imager": "latest",
    "winston": "^0.7.2",
    "notifier": "^0.1.4",
    "async": "latest",
    "view-helpers": "latest",
    "connect-multiparty": "^1.0.3",
    "gzippo": "latest",
    "geoip": "^0.5.2",
    "helmet": "^0.1.3",
    "lodash": "^2.4.1",
    "nodejs-gravatar": "^1.0.2",
    "superagent": "^0.16.0",
    "request": "^2.34.0",
    "q": "^1.0.0",
    "twit": "^1.1.12",
    "mongoose-text-search": "0.0.2",
    "mongoosastic": "^0.2.6",
    "express-error-with-sources": "^1.3.0",
    "when": "^2.8.0",
    "cron": "^1.0.4",
    "mathjs": "^0.18.1",
    "query-string": "^0.2.0",
    "moment": "^2.5.1",
    "stats-array": "^0.1.2",
    "time": "^0.10.0",
    "fs-extra": "^0.8.1",
    "json2csv": "^2.2.1",
    "string": "^1.8.0",
    "phantom": "^0.5.7",
    "node-wkhtml": "0.1.0-alpha1",
    "nodepdf": "^1.0.1",
    "utility": "^0.1.11",
    "nodemailer": "^0.6.1",
    "email-templates": "^0.1.7",
    "validator": "^3.5.1",
    "pdfcrowd": "^1.1.0",
    "mongoose-unique-validator": "^0.3.0",
    "jquery-file-upload-middleware": "^0.1.1",
    "mongoose-timestamp": "^0.2.1",
    "express-mongoose": "^0.1.0",
    "mongodb": "^1.4.2"
```

**Comment by leoj3n** [comment]
`npm cache clean` solved a similar "untar" error.

**Comment by jutiapaboy** [comment]
Thanks leoj3n "npm cache clean" solved the problem for me!

**Comment by kris7i** [comment]
$ npm cache clean
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "cache" "clean"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! path C:\Users\asusu\AppData\Roaming\npm-cache\ionic\1.3.11
npm ERR! code EBUSY
npm ERR! errno -4082

npm ERR! EBUSY, unlink 'C:\Users\asusu\AppData\Roaming\npm-cache\ionic\1.3.11'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Program Files\phpStudy\WWW\ionic\npm-debug.log
/c/Program Files/nodejs/npm: line 14:  2568 Signal 112              (core dumped
) "$basedir/node.exe" "$basedir/node_modules/npm/bin/npm-cli.js" "$@"

**Comment by edwinhdez** [comment]
Try running your command prompt as administrator that worked for me..

**Comment by czyang** [comment]
Bump, encounter in my mac, use sudo solved this question.

**Comment by graywithanA** [comment]
FYI, I had to clear my bower cache as well as my npm cache to resolve this issue:
```
$ npm cache clean
$ bower cache clean
```

**Comment by s875515** [comment]
Add sudo that prompt administrator to work this

**Comment by austinarchibald** [comment]
`npm cache clean` didn't work for me. sudo did. Yosemite 10.10.3

**Comment by Damondu** [comment]
It seems that npm cache clean doesn't work in Yosemite 10.10.3, except sudo.

**Comment by RHCKM** [comment]
Similar issues on Mac but adding sudo worked

**Comment by isimmons** [comment]
Same issue with untar error on three different packages in ~.npm . 

npm cache clean
bower cache clean

did not fix.

Tried multiple times so don't think it's a borked download issue.

Even manually cd to the directory in question and untar the package.tgz myself and still have the same error.

Shouldn't npm detect that the package is already there and untared so no need to try to re-download and untar it?

I think in my case it may be an issue with shared folder, using linux vm on a windows host but would think manually untaring the tgz would be a work around

**Comment by gregoryderner** [comment]
in my case I was trying to install nodemon. The error has been resolved by installing pkg global and not local

**Comment by Jacinth-21** [comment]
sudo npm install works for me.

**Comment by rohandavidg** [comment]
updating npm and sudo worked for me

**Comment by i-ctra** [comment]
![capture1](https://cloud.githubusercontent.com/assets/16149276/11586091/c9fc7630-9a98-11e5-837c-0771b9fd41ce.PNG)
I am trying to install ionic on windows and im getting this error.
Any solution??

**Comment by leopiazzoli** [comment]
npm cache clean work for me... Thanks.

**Comment by i-ctra** [comment]
I tried npm cache clean but still getting the same error

**Comment by emiliowebb** [comment]
got same error installing ws module. Solved opening cmd as an Administrator

**Comment by warrenca** [comment]
"Restart" solved my problem! I am using Ubuntu in virtual box and shared a directory from my host OSX computer. I accidentally deleted the files in OSX and try to clone again the files via git. I have to do ```npm install``` but I got the following error

```
npm ERR! tar.unpack untar error...
...
npm ERR! EEXIST: file already exists, mkdir '/home/vagrant/project-server/node_modules'
File exists: /home/vagrant/project-server/node_modules
Move it away, and try again.
```

I did ```npm cache clean``` but I still can't make it work. I restarted the VM and npm install work. I guess Ubuntu is not aware that the ```project-server``` directory is deleted that's why it's complaining. Maybe there's a better way to refresh the status of the files without restarting.

**Comment by chinhphan099** [comment]
try with: sudo ...

**Comment by uazure** [comment]
Had the same issue. It was caused by incomplete .tar.gz files. But `npm cache clean` didn't help me. Only after disabling my vpn I successfully installed deps. So in my case the issue was in network connection.

**Comment by anhnc55** [comment]
sudo npm install -g react-native-cli, then enter your password. This proplem would solved!

**Comment by zulhfreelancer** [comment]
I'm on OSX El Capitan 10.11.2.

`sudo npm install -g bower` works for me.

**Comment by VivekAnand23** [comment]
I am trying to install Ionic on Windows 7. Getting error for untar package.tgz.

```
npm ERR! tar.unpack untar error C:\Users\user1\AppData\Roaming\npm-cache\ionic\1.7.12\package.tgz
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\user1\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\n
pm-cli.js" "install" "-g" "ionic"
npm ERR! node v4.2.4
npm ERR! npm  v3.5.3
npm ERR! path C:\Users\user1\AppData\Local\Temp\npm-7336-1b0c36d1\unpack-4a6c8f61\node_modules\ionic-app-lib\node_modul
es\archiver\node_modules\file-utils\node_modules\isbinaryfile\tests\fixtures\04_HelloWorld.pdf
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall open

npm ERR! Error: EPERM: operation not permitted, open 'C:\Users\user1\AppData\Local\Temp\npm-7336-1b0c36d1\unpack-4a6c8f
61\node_modules\ionic-app-lib\node_modules\archiver\node_modules\file-utils\node_modules\isbinaryfile\tests\fixtures\04_
HelloWorld.pdf'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM: operation not permitted, open 'C:\Users\user1\AppData\Local\Temp\npm-7336-1b0c36d1\unpack-4a
6c8f61\node_modules\ionic-app-lib\node_modules\archiver\node_modules\file-utils\node_modules\isbinaryfile\tests\fixtures
\04_HelloWorld.pdf']
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'open',
npm ERR!   path: 'C:\\Users\\user1\\AppData\\Local\\Temp\\npm-7336-1b0c36d1\\unpack-4a6c8f61\\node_modules\\ionic-app-l
ib\\node_modules\\archiver\\node_modules\\file-utils\\node_modules\\isbinaryfile\\tests\\fixtures\\04_HelloWorld.pdf' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\user1\npm-debug.log
```

Seems while untaring, the filepath is longer than acceptable by OS.

Any help please.

**Comment by bluejamesbond** [comment]
This could be a disk space issue. Try to clear your `/tmp/` folder

**Comment by ihorml** [comment]
@bluejamesbond it helps for me. thx

**Comment by mlhoque** [comment]
Following worked for me

`npm cache clean`
`npm update`
`npm install`

**Comment by alheranx** [comment]
WARNING!, the sudo helps, and solve it, but i dont recommend it.  Past days i have problems with that, because then the installation appears like root user by using sudo, then the best solution for not having problems in the future with updates and other libraries is change the chown user.  In the next link i found more information: https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by xiayumoGit** [comment]
i have the same issue,any help?

**Comment by ybbz** [comment]
I use sudo solved this question in my mac too.

**Comment by martianmartian** [comment]
Can someone get me off this bloody email list? I got 150 emails from npm just today. What the fuck!

Sent from my iPhone

On Apr 23, 2016, at 3:36 AM, ??? <notifications@github.com<mailto:notifications@github.com>> wrote:


I use sudo solved this question in my mac too.

-

**Comment by othiym23** [comment]
@martianmartian You're getting email from GitHub because you configured it to do so, either by changing your configuring or by clicking "watch" on npm's repository. As this is a function of GitHub that has nothing to do with the npm CLI project, and as there's no content related to the npm CLI in any of your posts, I'm going to remove them (and this comment, which will get sent to you). Good luck getting your configuration sorted out!

**Comment by huangyingjie** [comment]
I have solved by this way: just remove the $NVM_DIR and reinstall nvm.

**Comment by daneshka** [comment]
I have the same issue, none of the solutions worked for me. The problem is using virtualbox share folder. By copy pasting file to another folder it will work. 
I'm waiting for the real solution :)

**Comment by mmrko** [comment]
In my case this was caused by `package.json` and `npm-shrinkwrap.json` being "out of sync". So to fix things I needed to run `npm shrinkwrap`, fix the reported conflicts and then `npm install`.

**Comment by srmob** [comment]
npm cache and run as admin worked for me.

**Comment by angelarted** [comment]
FOR MAC USER: 
also for me, running the command with 'sudo' worked. So it become something like this:
`sudo npm install ` ...whatever you need to install

**Comment by Romasato** [comment]
Also, if you're on Virtualbox VM and have your project hosted on other partition (separate mounted *.vdi file), try moving it to the main system partition. Doing that has solved the issue for me :)

**Comment by jedwards1211** [comment]
On my mac, running `sudo npm cache clean` worked for me; didn't have to run `npm install` with sudo.

**Comment by PaulineZhou** [comment]
just add “sudo” to the last one npm command order
A hexo newer
`sudo npm install hexo-cli -g`

**Comment by enricostano** [comment]
`ubuntu/xenial64` vagrant VM on Mac OSX host, having similar issue running `npm install`:
https://gist.github.com/nadalsol/2378a02e3eeffac35708349e97c1e492

`sudo` does not solve the issue.

BTW... this issue is open since `2014`...

**Comment by type-a-developer** [comment]
I got the same errors because my VM ran out space have way through the npm install.  Make sure you have enough space and run (npm cache clean).  This worked for me.

**Comment by dsinghr** [comment]
Encountered this issue in elementary OS (modified ubuntu), switched to yarn package manager.

**Comment by jehoshua02** [comment]
![MEME](http://media1.giphy.com/gifsu/3o6wrr9X5KgVIVjAIg/giphy-caption.gif)

**Comment by andresjordanze** [comment]
thanks @leoj3n ``` npm cache clean``` worked for me!

**Comment by flute** [comment]
`sudo npm install XX` works for me!
`npm cache clean` not worked
```
macOS Sierra 10.12.2
node v5.12.0
npm 3.8.9
```

**Comment by dilagurung** [comment]
I tried all the aforesaid trick(npm cache clean(run as admin too) , npm update) , but dint work.. still getting the same error orginially posted. Any help will be appreciated.

**Comment by justinmc** [comment]
I encountered this while trying to `npm install` a tarball that I created myself using grunt-contrib-compress.  For whatever reason, the output of grunt-contrib-compress isn't like by npm.  It worked fine for me when I created the tarball with `tar -cvzf` or `npm pack` instead.

**Comment by Wyzardsleeves** [comment]
I just built the app on Windows instead of my Ubuntu VM and that worked. I can even npm start through my VM and develop that way.

**Comment by HugoPoi** [comment]
If you are under Windows upgrade NPM to 5.x >

**Comment by mrahulreddy** [comment]
The following works for `tar.unpack untar error` :

1- `npm uninstall -g angular-cli`
`npm uninstall -g @angular/cli`
`npm cache clean`
`npm install -g @angular/cli`

(or)

2- open cmd on administrator and repeat the same.

**Doing the second one helped for me.**

**Comment by kujiy** [comment]
```
chmod 777 -R ~/.npm
```
This fixed in my case.

**Comment by Malleswari103095** [comment]
In my case, it's probably the access privilege issue. Adding sudo prior to the npm command did fix the issue.

**Comment by lijiansong** [comment]
you can install node.js v6.10.2 and npm 3.10.10
```
### nvm installation
$ curl -sL https://raw.githubusercontent.com/creationix/nvm/v0.31.0/install.sh -o install_nvm.sh

### run script
$ bash install_nvm.sh
$ source ~/.profile
$ nvm ls
$ nvm install 6.10.2

### set default node
$ nvm alias default 6.10.2
$ nvm use default

#Check your version
$ node -v
$ npm -v
```

ref to this [gist](https://gist.github.com/russtanevich/1357ee35dc5218a0e1444e87af323298)
