### ISSUE TITLE
peerDependencies and npm shrinkwrap

### ISSUE THREAD

**Issue by davglass** [npm/npm#5135]
If I have an app[1] that requires a module, in this case `express@~3.4.8` and it also has a module[2] that requires that same version. That module[2] also requires another module[3] that requires modules (`express-state` & `express-map`) with a peerDependency on `express@3.x`.

If I install this, as is, then it will work perfectly:
https://gist.github.com/davglass/11225979#file-no-shrinkwrap-txt

However, if I add a shrinkwrap file:
https://github.com/davglass/peer-app/blob/master/npm-shrinkwrap.json

Then try to install it:
https://gist.github.com/davglass/11225979#file-shrinkwrap-txt

It will not recognize that `express@3.4.8` was installed at a higher level and it will pull in the latest `express@3.5.1` which will break the application. 

What I think is happening here is that when processing the shrinkwrap file, the peerDependencies logic kicks in and says "hey, I need `express@3.x` and it's not at this level, go fetch it" when it should check to see if it's available in the tree above it. This is what "I think" `npm install` does for us. But since that logic is skipped for the shrinkwrap, it's actually doing the wrong thing.

Links:
[1]app: https://github.com/davglass/peer-app
[2]module1: https://github.com/davglass/module1
[3]module2: https://github.com/davglass/module1

Possibly related to #5080 

I'm happy to dive in and see if I can find the root cause of this issue but I wanted to confirm first that this is an issue.

If #5080 removes the installation of peerDependencies and just warns, then I think this issue will go away since the install won't happen.

**Comment by markjbyrne81** [comment]
I am actually still seeing the issue that @MatthewMaclean describes.  I have updated npm to the latest version and yet when I run '''npm shrinkwrap''' on an installed package I receive and error message stating that the peer dependency is missing.

I understand that automatic installation of peer dependencies will be removed in npm 3.x but how does this affect the use of npm shrinkwrap for locking down version numbers used by dependencies?

**Comment by jlevy** [comment]
We've hit what appears to be the same issue, where auto-installed peerDependencies break our shrinkwrapped build on npm 2.14.1. Are there any updates for npm 2 users?

It seems like auto-installation of peerDependencies and shrinkwrap are philosophically incompatible. Do others have workarounds, such as disabling the auto-install instead of just giving warnings, as in https://github.com/npm/npm/issues/6565 ?

**Comment by theogravity** [comment]
The "solution" we've had so far is to move the `peerDependencies` down to `devDependencies` in the situations where you have direct control over the component.

**Comment by mridgway** [comment]
I am still seeing this issue in 2.13.5. Quite frustrating.

**Comment by jlevy** [comment]
While this doesn't directly address this specific issue, perhaps it's worth mentioning: I've written a tool that serves as a sort of safety net in wrestling with "npm install" brittleness: https://github.com/vivlabs/instaclone
It's made issues like this feel less urgent when they do happen.

**Comment by chulkilee** [comment]
Still seeing this issue at node 5.5.0 and npm 3.6.0

**Comment by kahboom** [comment]
@chulkilee - I was having the same issue because I had previously installed those packages using npm 2.x.x and then upgraded npm to 3.6.0. Assuming you are not getting other errors, just the "peer invalid" one, make sure sure to run `rm -rf node_modules && npm cache clean && npm install --save`. The error may now be a warning like `npm WARN kerberos@~0.0 requires a peer of mongodb-core@1.2.32 but none was installed.` but it will write to the shrinkwrap file.

At that point, it's a package-specific issue, where you can contact the authors of `mongodb-core@1.2.32`, but as a workaround you should install the peer dependency manually with `npm install kerberos --save` and re-run `npm shrinkwrap`.

**Comment by chulkilee** [comment]
@kahboom 

1. No, it's not related to cache or previously installed packages under `node_modules`.

2. This is a issue of npm, not of a specific package. It is [documented feature](https://docs.npmjs.com/files/package.json#peerdependencies) but `npm shrinkwrap` and `npm list` doesn't handle it correctly.

3. mongodb-core 1.3.x now uses `peerOptionalDependencies`, which does not make problems. It is bad to make package maintainers to use such non-standard keys to avoid npm issues.

----

```json
{
  "name": "peer",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "Chulki Lee <chulki.lee@gmail.com> (https://github.com/chulkilee)",
  "license": "ISC",
  "dependencies": {
    "mongodb-core": "1.2.32"
  }
}
```

```bash
node -v
v5.6.0

npm -v
3.6.0

npm cache clean && rm -rf node_modules npm-shrinkwrap.json && npm install

npm list

peer-test@0.0.1 /Users/chulki/tmp/peer
├── UNMET PEER DEPENDENCY kerberos@~0.0
└─┬ mongodb-core@1.2.32
  └── bson@0.4.21

npm ERR! peer dep missing: kerberos@~0.0, required by mongodb-core@1.2.32

npm shrinkwrap

npm ERR! Darwin 15.3.0
npm ERR! argv "/Users/chulki/.nvm/versions/node/v5.6.0/bin/node" "/Users/chulki/.nvm/versions/node/v5.6.0/bin/npm" "shrinkwrap"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0

npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! peer invalid: kerberos@~0.0, required by mongodb-core@1.2.32
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/chulki/tmp/peer/npm-debug.log
```

**Comment by johnpapa** [comment]
This is also happening for our teams. We will create a repo today that reproduces this so we can brainstorm a fix.

**Comment by baens** [comment]
We are also having an issue on a project with react-bootstrap. It installs react 15.0 while I have a dependency on 0.14. I am working on trying to get an example together for an example.

**Comment by kodypeterson** [comment]
FWIW It seems new releases of libraries are causing this. We saw it with the release of Grunt 1.0.0 now @baens is seeing it with the release of react 0.15

I am working on getting an example repo together so we can all get more of a visual idea what is happening here.

**Comment by kodypeterson** [comment]
Alright, I have a good example here showing what we are seeing. In our case we are having peerDependency issues with grunt.

The 2 repos used here are:

https://github.com/kodypeterson/npm-peershrink-test
https://github.com/kodypeterson/npm-peershrink-test-dependency

Steps to Reproduce:

1. `git clone https://github.com/kodypeterson/npm-peershrink-test.git`
2. `npm install`
   2a. It is worth noting that the version of `node_modules/grunt` is `0.4.5` and that there is no `node_modules/npm-peershrinkwrap-test-dependency/grunt`
3. `npm shrinkwrap`
4. `rm -fr node_modules`
5. `npm install`

At this point you should now see a list of peerDependency issues in the console. But if you look at `node_modules/npm-peershrinkwrap-test-dependency/grunt` you will see that it now exists and it is the latest version `1.0.1` - How did this happen?? We never asked for that, nor do the peerDependencies. So, it seems somewhere within the NPM logic it installs the latest version.

I have yet to really dig into the NPM code to look at this one, but the fact that the latest of a library is being installed with a shrinkwrap file present makes me want to point at NPM.

I have tested this with 2.5.x and 2.12.x

Our organization is not yet ready to upgrade to npm 3.x, as I am sure others are in the same boat. So, this is a total blocker for our CICD process.

Hopefully these repos and steps can help us track down where and why we keep bumping into this problem with peerDependencies and major release of libraries that have those libraries as peerDependencies.

**Comment by majgis** [comment]
`npm prune --production` does not remove these extra packages.  Has anyone found an alternative workaround to removing the npm-shrinkwrap.json file?  You can manually add `rm -rf <packag_path>` to a postinstall script for each offending package, but it would be nice to have something automated.

**Comment by majgis** [comment]
I did a test with npm v3.8.6 and the --legacy-bundling flag.  The issue wasn't present.

**Comment by testerez** [comment]
Here is another demonstration of the issue:

```
npm init -y
npm i --save react@0.14 react-dom@0.14 react-bootstrap
npm shrinkwrap
rm -rf node_modules/
npm install
npm list react
```

Here is the result I get:
```
npm3@1.0.0 /Users/testerez/projects/trash/npm3
├── react@0.14.8 
└─┬ react-bootstrap@0.28.5
  └── react@15.0.1 
```
(using node v4.4.2, npm 2.15.0)

**Comment by platphorm** [comment]
Same issue here. 
`npm init -y`
`npm i --save react@0.14 react-shuffle@1.0.0`
`npm install`

that works fine. Now continue with:
`npm shrinkwrap`
`rm -rf node_modules/`
`npm install`

which leads to:

`npm ERR! peerinvalid The package react@15.0.1 does not satisfy its siblings' peerDependencies requirements!`

**Comment by majgis** [comment]
Please help with testing the fix if you can:

To install npm v2 with this fix:
```
npm i -g git+https://github.com/majgis/npm.git#366c0728a1a8865d265d5a9f06389fe0b5dd8183
```

To restore to the latest official version of npm v2:
```
npm i -g npm@2
```

Report your findings here:  https://github.com/npm/npm/pull/12290

**Comment by majgis** [comment]
@baens and I are on the same team.  The fix addressed the issue he reported and a test was included in the PR based on his instructions.

**Comment by rohanBagchi** [comment]
This is for any one who might stumble onto this issue page like I did.
It might be a bit late for me to comment, but looks like the issue has been resolved as mentioned by `npm bot`. 
cc @platphorm 
`npm -v` is `3.10.10`.

1. `npm i --save react@0.14 react-shuffle@1.0.0`
2. `npm shrinkwrap`
3. `rm -rf node_modules`
4. `npm install`

it all works fine.
Look below for the log after above step#3 & step#4.
```
➜  shrinkwrap_poc npm i
shrinkwrap_poc@1.0.0 /Users/rohanbagchi/repo/shrinkwrap_poc
├── acorn@4.0.13
├── amdefine@1.0.1
├── asap@2.0.6
├── ast-types@0.9.6
├── balanced-match@1.0.0
├── base62@1.2.0
├── brace-expansion@1.1.8
├── commander@2.11.0
├── commoner@0.10.8
├── concat-map@0.0.1
├── core-js@1.2.7
├── defined@1.0.0
├── detective@4.5.0
├── envify@3.4.1
├── esprima-fb@15001.1.0-dev-harmony-fb
├── fbjs@0.6.1
├── glob@5.0.15
├── graceful-fs@4.1.11
├── iconv-lite@0.4.19
├── inflight@1.0.6
├── inherits@2.0.3
├── js-tokens@3.0.2
├── jstransform@11.0.3
├── loose-envify@1.3.1
├── minimatch@3.0.4
├── minimist@0.0.8
├── mkdirp@0.5.1
├── object-assign@2.1.1
├── once@1.4.0
├── path-is-absolute@1.0.1
├── performance-now@2.1.0
├── private@0.1.8
├── promise@7.3.1
├── q@1.5.1
├── raf@3.4.0
├── react@0.14.9
├── react-addons-transition-group@0.14.8
├─┬ react-shuffle@1.0.0
│ └── object-assign@4.1.1
├── react-tween-state@0.1.5
├─┬ recast@0.11.23
│ ├── esprima@3.1.3
│ └── source-map@0.5.7
├── source-map@0.4.4
├── through@2.3.8
├── tween-functions@1.2.0
├── ua-parser-js@0.7.17
├── whatwg-fetch@0.9.0
└── wrappy@1.0.2

npm WARN shrinkwrap_poc@1.0.0 No description
npm WARN shrinkwrap_poc@1.0.0 No repository field.
```
