### ISSUE TITLE
Add npm install --skip-dependencies

### ISSUE THREAD

**Issue by chaser92** [npm/npm#5140]
I often install a npm package from git, and every time I do, all dependency packages are reinstalled along. Since there is no option to npm update a git package (at least I can't), could there be an option to skip dependency installations (at least for development purposes)? I use npm to deploy my app to destination device. I could code it myself if it's accepted.

**Comment by othiym23** [comment]
The correct behavior here is for `npm update` and `npm outdated` to handle hosted Git dependencies in a more intuitive way, which is what #8055 is intended to address. A `--skip-dependencies` flag would create a set of edge cases where it's much easier for npm to produce an incomplete or inconsistent install, so we're unlikely to land that kind of functionality. That said, addressing #8055 should also make this less awkward, and as such I'm going to close this issue in favor of that one. Thanks for your time!
