### ISSUE TITLE
handle multispace characters in npm search result

### ISSUE THREAD

**Issue by villadora** [npm/npm#5144]
_trimToMaxWidth_ function should slice lines based on line's wcwidth

```
function trimToMaxWidth(str) {
  var maxWidth = getMaxWidth()
  return str.split('\n').map(function(line) {
    return line.slice(0, maxWidth) // the line.length may not be the same width when output in terminal
  }).join('\n')
}
```

see timoxley/columnify#2

**Comment by timoxley** [comment]
Ahh, this should really be solved by columnify. I've added a maxLineLength feature which performs the same logic (currently unused by npm), but didn't think of multispace chars.

**Comment by othiym23** [comment]
@timoxley my current policy is to update any outdated npm dependencies on every release (except for ones containing breaking changes -- once `npm@3` is released I will probably amend the policy to make keeping dependencies up to date part of the release process), so I'm happy to let this change come in via an update to `columnify`, and it will get incorporated promptly after you release it.

**Comment by othiym23** [comment]
Closing because this is something that should be addressed within `columnify` (and very well may already have been). Also, npm's search implementation pretty much just needs to be replaced at this point. Thanks for your time and patience!
