### ISSUE TITLE
Tags cannot be removed

### ISSUE THREAD

**Issue by boutell** [npm/npm#5146]
It does not appear to be possible to remove a tag. We're transitioning from "beta" and "latest" to 0.4, 0.5, etc. and "latest". We'd like to get rid of the beta tag that already exists on various modules, but other folks seem stuck on that too:

http://stackoverflow.com/questions/14949886/how-can-i-remove-a-tag-from-npm

Hoping that unpublishing things is not required.

Thanks!

**Comment by smikes** [comment]
This is now fixed as of `npm@2.5.0`; latest is `2.6.0`.  The syntax for removing a dist-tag is:

```
$ npm dist-tag rm <pkg> <tag>
```

**Comment by boutell** [comment]
Thanks!

On Sun, Feb 22, 2015 at 8:36 AM, Sam Mikes <notifications@github.com> wrote:

> This is now fixed as of npm@2.5.0; latest is 2.6.0. The syntax for
> removing a dist-tag is:
>
> $ npm dist-tag rm <pkg> <tag>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/npm/npm/issues/5146#issuecomment-75435700>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by DamonOehlman** [comment]
Awesome - thanks :smiley_cat:

**Comment by othiym23** [comment]
Oh, right! Closing as resolved in [`npm@2.4.1`](https://github.com/npm/npm/releases/tag/v2.4.1), so update and run `npm help dist-tag` to learn how to get started removing your superfluous dist-tags!
