### ISSUE TITLE
Update not aware that package was installed from GitHub to bypass registry

### ISSUE THREAD

**Issue by neverfox** [npm/npm#5151]
I'm having a problem were I'm installing a global package that's not registered (because the name is taken), so it requires using a GitHub URL. The package is at version 0.3.0. The unrelated, but similarly named, published package is at version 0.2.5. `npm outdated -g` tells me that I "want" 0.2.5 (meaning the published package). And running `npm update -g` replaces the package I want with the published package. As far as npm is concerned, I've installed a package called `bump` and it thinks it's the published one.

Package I want: `ianstormtaylor/bump`
Package it gives me if I try to update my global packages: `kilianc/node-bump` (registered as `bump`)

This means I cannot just run a simple `npm update -g` but have to replace that package afterwards.

**Comment by smikes** [comment]
I cannot seem to reproduce this with `npm@2.6.1`.

**Comment by othiym23** [comment]
It seems reasonable to use the installed `package.json` to decide what to do when updating a package, @neverfox, but there's a trick: where would npm look to learn that it's dealing with something that's not from the registry? It's possible that the outdated logic (which update uses) could be changed to see if the current `package.json` has the fields (`_from` and `_resolved`) that could tell it if the current package came from somewhere other than the registry (if it's not using data from a parent `package.json`), but that would be a significant change for what is honestly a rare edge case (and would probably end up relying on some dodgy heuristics). Right now the outdated / updated code makes the (mostly reasonable) assumption that the currently-configured registry is the source of truth about what is and isn't out of date, and the idea that a named might refer to two different things isn't even part of its worldvie.

The npm team won't make this change ourselves, but if you wanted to put together a patch for it, and it didn't break any of the existing tests, I would work with you to merging it in. Thanks for your time, and for taking the time to lay out your use case so clearly!
