### ISSUE TITLE
npm install doesn't pull in new tarball versions

### ISSUE THREAD

**Issue by fresheneesz** [npm/npm#5155]
If I previously installed either an npm package (say `"colors"`) OR a tarball package (say `"https://github.com/fresheneesz/colors.js/archive/f5d4cc28ffc112179e6fa47a729938a79011b3a0.tar.gz"`, npm fails to install the new version, and instead simply keeps things the way they are if I change package.json to have a new version like `"https://github.com/fresheneesz/colors.js/archive/e990804d7c301765409770582c6aa6d562a23198.tar.gz"`.

I have to delete the old folder (inside node_modules) manually before it will work.

I'm using npm version 1.4.3 and node v 0.10.26 on windows 7 professsional 64 bit.

**Comment by kmanion** [comment]
Hi @fresheneesz, it looks like this is the behavior in npm@3, so you should be good.

Feel free to re-open this issue if you come across it again.
