### ISSUE TITLE
npm config edit impossible

### ISSUE THREAD

**Issue by bastoune** [npm/npm#5166]
I am trying to download packages thanks to a package.json contained in a project directory given to me. I already installed node.js.
I have a connexion problem because I use a proxy. So I try to edit the configuration file of npm to tell him to use the proxy.
I already have my windows system variables HTTP_PROXY and HTTPS_PROXY setted to proxy_name:port_number

When i try to make the command "npm config edit", i get this :
```
npm ERR! Error: ENOENT, unlink 'D:\Utilisateurs\***\.npmrc'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "config" "edit"
npm ERR! cwd D:\Utilisateurs\***\Documents\****
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! path D:\Utilisateurs\***\.npmrc
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     D:\Utilisateurs\***\Documents\Début AngularJS\ecommerce\npm-debug.log
npm ERR! not ok code 0


The npm-debug.log contains this : 
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'config',
1 verbose cli   'edit' ]
2 info using npm@1.4.3
3 info using node@v0.10.26
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 error Error: ENOENT, unlink 'D:\Utilisateurs\A579871\.npmrc'
6 error If you need help, you may report this *entire* log,
6 error including the npm and node versions, at:
6 error     <http://github.com/npm/npm/issues>
7 error System Windows_NT 6.1.7601
8 error command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "config" "edit"
9 error cwd D:\Utilisateurs\A579871\Documents\Début AngularJS\ecommerce
10 error node -v v0.10.26
11 error npm -v 1.4.3
12 error path D:\Utilisateurs\A579871\.npmrc
13 error code ENOENT
14 error errno 34
15 verbose exit [ 34, true ]
```
I tried to open cmd "as administrator" but it doesn't work better.
I didn't find similar problem. I hope I searched well enough...

Thanks by advance 
Bastien

**Comment by smikes** [comment]
@bastoune , Is this still a problem for you?

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.4.3. Can you try updating your npm installation?

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as abandoned.
