### ISSUE TITLE
alias commands

### ISSUE THREAD

**Issue by evanlucas** [npm/npm#5194]
would you consider having aliases like git does for npm commands?

For example, I have a bad habit of typing `npm in` and being able to alias commands would be awesome

**Comment by joshhartigan** [comment]
:+1:

What about something similar to `git`'s alias system:
`git config --global alias.co checkout`
`npm alias in install`

**Comment by othiym23** [comment]
I have had this conversation with a number of people over the last year, but I just realized that I've never written it down: I don't want npm to go this direction.

Extensible command-line tools can be split up into those with _open_ and _closed_ command vocabularies:

* git is a good example of a command with an _open_ vocabulary: in addition to command aliases, you can extend git's behavior by dropping programs prefixed with `git-` onto your `PATH` (e.g. `/usr/local/bin/git-mycommand`), and then they can be invoked via `git mycommand`. This is also the way the `dat` project has gone. It's a useful way to allow specific user communities to tailor the tool to the specific needs of their use cases, and where it's not super important that the vocabulary be consistent between systems or teams.
* apt-get is a good example of a command with a _closed_ vocabulary: it's got a fixed set of subcommands (that can be heavily configured), and you can't add new subcommands, nor can you alias existing commands. This is useful for tools that are going to be used operationally, where it's important that everybody using the tool share the same vocabulary. It's also a way to try to constrain the cognitive load of grappling with tools that do a lot of different things.

Of the two strategies, I think npm works best _closed_. It is a Swiss Army wheed whacker of a tool, which downloads, publishes, installs, manages, and configures packages. It does enough stuff that as a maintainer and developer of the tool I'm still regularly surprised by emergent aspects of its behavior. Even @isaacs occasionally loses track of all the different things it can do. It also can be used in different roles, but it's frequently used in an operational capacity to deploy apps, so I believe it's for the best if npm behaves the way you expect right out of the box, with no further customization or installation of add-ons.

As such, I feel that one of the CLI core team's most important jobs is to figure out to constrain, standardize, and make more consistent npm's functionality, in the (perhaps vain) hopes that eventually most users will be able to have a complete enough mental model of what npm can do that they can master its use in a meaningful way. This has two primary consequences:

1. You can't have command aliases. This keeps npm closer to stock for everyone. Keep in mind that npm, like git and many other complex CLI tools, comes with a whole bunch of shortcuts built in, and also allows you to use the shortest unambiguous prefix for any of its built-in commands: both `npm i` (a shortcut) and `npm ins` (an unambiguous prefix) will work for `npm install`, but `npm in` (which can be either `npm install` or `npm init`) won't. (And if you didn't know about this behavior before, that speaks to my point earlier about the difficulty of mastering npm.)
2. Users can't extend npm via new subcommands. I've chosen a different path for npm's extensibility, which is to break the CLI down into a set of individual APIs that are each responsible for one domain of npm's functionality (caching, installing, communicating with the registry, etc). This is a long, slow project that will really only start to reach fruition towards the end of this year, but my bet is that long term it will result in a much more interesting ecosystem, where tools like the Atom package manager and `jspm` can reuse only the bits of npm they care about without having to take onboard understanding how all of those pieces work.

So, we won't be implementing this, and if you want something similar yourself, use the aliasing capabilities of `$your_favorite_shell`. I hope my rationale makes sense, and thanks for making the suggestion in the first place.

**Comment by joshhartigan** [comment]
Thanks for a very comprehensive (and successfully persuasive) response. :smiley:
