### ISSUE TITLE
npm report

### ISSUE THREAD

**Issue by isaacs** [npm/npm#5214]
If there's an `npm-debug.log` file, then `npm report` should upload that as an anonymous gist, and then take the user to a page like https://github.com/npm/npm/issues/new?title=error%20title%20report&body=help%20me%20please%20blah%20blah.

Once that's done, we should do #5213.

**Comment by watilde** [comment]
Wow I thought same thing with this so I developed and published as a package:
https://www.npmjs.com/package/npm-report

Well, this feature seems happy if it's in the npm.

**Comment by othiym23** [comment]
@watilde This is a good start. Do you know about npm/support-cli? That's where we want to start sending support tickets / `npm-debug.log` links. Also, if `npm-report` would use `gist` or something similar to automatically upload `npm-debug.log` to gist.github.com, that would make it very useful. If you want to keep working on it, it could very easily become something we eventually incorporate into npm itself. Thanks for getting the ball rolling!

**Comment by watilde** [comment]
@othiym23 Thanks for your reply with all your kindness! I've changed endpoint creating issue to `npm/support-cli` in `npm-report`. Well using gist sounds really useful, but I think it might makes npm a little bit complex. We have a 4 way for uploading gist:

|#|Post as who?|share with|
|---|---|---|
|1|Anonymous|Public|
|2|Anonymous|Private|
|3|User|Public|
|4|User|Private|

These way have two problems
+ Deleting an anonymous gist need a human power:
  + https://help.github.com/articles/deleting-an-anonymous-gist/
+ Posting as a user need authentication:
  + https://www.npmjs.com/package/gistjs#login

So, I like to use a issue's body like this:
  + https://github.com/npm/support-cli/issues/new?body=blahblah

Could you please any thought on this please?

**Comment by othiym23** [comment]
This has been moved to the [npm roadmap](https://github.com/npm/npm/wiki/Roadmap), which we're using instead of the confusing `next-*` labels now.

**Comment by othiym23** [comment]
@watilde Where did you leave `npm-report`? The CLI team is pretty heads down with bugs and high-priority feature work right now, but it would be useful to see if this project is in a place where we can turn the crank on it a bit. The issue template has helped somewhat, at least in terms of soliciting better issues from users, but there's still a lot of work to be done around making it easier to triage those issues, and also, you know, to handle them.

**Comment by watilde** [comment]
@othiym23 I've released it as a package and you can see what does it bring:
```
$ npm i -g npm-report
$ mkdir tmp && cd tmp && npm init -y && npm run a
=> get an error
$ npm-report
```

Well, I'd happy to bring it to here by somehow just right way, like adding a link to the error message footer in npm.

**Comment by zkat** [comment]
:ie: just dropping a note that something like this would be able to do the thing that `apm` does where it detects duplicate issues. That could *really* help out tracker load.
