### ISSUE TITLE
engineStrict only checks on remote installs

### ISSUE THREAD

**Issue by easternbloc** [npm/npm#5218]
Specifying:

```
"engineStrict": true,
"engines": {
  "node": ">= 0.10.22",
  "npm": ">= 1.4.10"
}
```

in my ```package.json``` and running ```npm install``` doesn't fail the build but running it from another directory ie: ```npm install ./project_name``` will fail with:

```
~/Projects $ npm install ./project_name
npm ERR! notsup Unsupported
npm ERR! notsup Not compatible with your version of node/npm: project_name@0.0.1
npm ERR! notsup Required: {"node":">= 0.10.22","npm":">= 1.4.10"}
npm ERR! notsup Actual:   {"npm":"1.3.14","node":"v0.10.22"}

npm ERR! System Darwin 13.1.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "./project_name"
npm ERR! cwd /Users/easternbloc/Projects
npm ERR! node -v v0.10.22
npm ERR! npm -v 1.3.14
npm ERR! code ENOTSUP
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/easternbloc/Projects/npm-debug.log
npm ERR! not ok code 0
```

I have no idea why npm doesn't check the engineStrict flag when you do a local install. It seems sensible to still do that?

**Comment by othiym23** [comment]
As `npm@3` removes `engineStrict` altogether (#8723), this issue has been rendered redundant by history. Thanks anyway for your time!

**Comment by easternbloc** [comment]
@othiym23 the same issue exists for warn? Shall I raise this as a separate issue? It's essentially the same thing except I should get WARN instead of error.
