### ISSUE TITLE
Can npm dedupe to "one dir up"?

### ISSUE THREAD

**Issue by Pomax** [npm/npm#5224]
We have a whole slew of projects that get suite-checked-out into a master dir, leading to a dir with 38 git repos all of which come with a package.json for `npm install`'ing. This leads to a pretty voluminous master dir (du claims 4.5GB) and NPM dedupe on the individual projects leads to a size reduction of about 100MB, which is decent, but if npm could be told to dedupe to the master dir instead, the savings would probably be way more than 100MB. Is it possible to tell NPM how high it should go relative to where `npm dedupe` is called (the master dir also has its own `./node_modules` dir)? If not, can I feature request that? =)

**Comment by othiym23** [comment]
You're right that you can get substantial space savings by hoisting shared packages to a parent `node_modules`; this is something that's out of scope for npm, which is really tied to the concept of `package.json` being the central hub around which all of the other packages that it manages revolve. A solution like `aperture` or other tools that simplify this kind of shared development or deployment seems like the right place to look; this is unlikely to be something that npm in its current form is every going to support. Thanks for your time!
