### ISSUE TITLE
Add a --force option to dedupe

### ISSUE THREAD

**Issue by wheresrhys** [npm/npm#5236]
This would make dedupe behave like a `flatten` command.

Currently dedupe will not change anything when run on 
```
a
+-- b <-- depends on c@1.0.x
|   `-- c@1.0.3
|   `-- e@3.0.3
`-- d <-- depends on c@2.0.9
    `-- c@2.09
```

With the `--force` option it should move any non-clashing dependencies as far up the tree as they will go (as far as the node_module directory in the working directory) resulting in

```
a
+-- b <-- depends on c@1.0.x
|   `-- c@1.0.3
`-- d <-- depends on c@2.0.9
|   `-- c@2.09
 `-- e@3.0.3
```

**Comment by iarna** [comment]
`npm@3`'s version of dedupe actually works this way... from the example above it would produce:

```
a
+-- b <-- depends on c@1.0.x
+-- c@1.0.3
`-- d <-- depends on c@2.0.9
|   `-- c@2.09
 `-- e@3.0.3
```

So! I'm gonna close this as done.
