### ISSUE TITLE
Documentation refers to {pre,post,}update scripts which are no longer supported.

### ISSUE THREAD

**Issue by mbostock** [npm/npm#5238]
https://www.npmjs.org/doc/misc/npm-scripts.html refers to (at least) two scripts that appear to be ignored in the current version of NPM, v1.4.10:

* preupdate: Run BEFORE the package is updated with the update command.
* update, postupdate: Run AFTER the package is updated with the update command.

Please update the documentation to remove references to these unsupported scripts or at least to comment that they are no longer supported.

**Comment by othiym23** [comment]
Closing as resolved.
