### ISSUE TITLE
Should not be able to publish something that can't be installed

### ISSUE THREAD

**Issue by thomblake** [npm/npm#5240]
I published version 1 of `jp` and then was not able to install it.  `npm init` created a `bin` entry for `"jp": "cmd.js"` that should have been `"jp": "bin/cmd.js"`.  I got a confusing error  at 'cache unpack' time.  Probably I should have been warned at publish time that this could not be installed.

**Comment by othiym23** [comment]
Closing as semi-duplicate of #5152; will add a note there indicating that this is another thing we should be checking for prepublish. Thanks for your time!
