### ISSUE TITLE
npm install --force to redownload/install of everything

### ISSUE THREAD

**Issue by timoxley** [npm/npm#5254]
This would basically be an alias to:

```
> rm -rf ./node_modules
> npm install
```

Dubious benefit, but seems clunky of npm to require users manually remove node_modules to fix a broken install. i.e. if npm install was killed halfway, afaik currently no way to guarantee correct installation other than manually removing node_modules and installing again.

**Comment by iarna** [comment]
this is not happening in multi-stage, but it is a LOT easier to patch in. Basically when constructing the ideal tree start from scratch instead of a clone of the current tree.

**Comment by UltCombo** [comment]
> when constructing the ideal tree start from scratch instead of a clone of the current tree.

Sounds good to me.

**Comment by chetanddesai** [comment]
+1 on this.  Was just looking for something like this @timoxley

**Comment by wilmoore** [comment]
:+1:

**Comment by othiym23** [comment]
This is something addressed by `npm@3`, which has a new installer that actually looks at the state of the installed tree. It's still undergoing beta testing (so to check it out, run `npm -g install npm@beta`), but it's pretty close to finished, so I'm going to call this dealt with and close it out

**Comment by Azbola** [comment]
Hello, I tried using --force on version 3.10.3 and it only works with a specific package.
If I just try "npm install --force" to update everything in the package.json it does nothing 
Is this expected behaviour?

**Comment by dmk1111** [comment]
@Azbola it works fine with npm 4.2.0

**Comment by Gerrit-K** [comment]
@Azbola @dmk1111 I had the same (or similar) problem with 3.10.5. `npm install --force` did nothing while `npm update` updated the outdated dependencies.
Has there been an issue to which I could refer? Couldn't find anything yet ...

**Comment by Normanity** [comment]
Go to the Node.js website (https://nodejs.org/en/) 
Download and install your preferred version
Restart command line
You're good to try again
This works and should only take a few mins...
