### ISSUE TITLE
Support nar as application package

### ISSUE THREAD

**Issue by h2non** [npm/npm#5255]
What about the idea of providing support for [nar](https://github.com/h2non/nar) application packages from `npm`?

It could be useful as node.js application package format

**Comment by othiym23** [comment]
`nar` looks neat! npm already supports a pretty wide variety of formats, and it doesn't really make sense to add yet another one, especially when one of the features of that package format is that it's self-extracting. One of the CLI team's goals is to simplify the installer, and this kinda goes the other way, so while it would be interesting and useful to write a little helper script that transfers a `nar` archive into a package tarball that's installable by npm (and maybe then goes ahead and installs it), we're not going to add support to the core CLI for nar natively. Thanks for your time!
