### ISSUE TITLE
Multipackage projects: relative path in package.json dependencies

### ISSUE THREAD

**Issue by nitroduna** [npm/npm#5293]
Sorry if this is not the place to discuss about this kind of issue, and please tell me where would be the right one. 

I've seen this same issue in #1376, but I'm not sure about the solution of using "npm link", it is not the same, and has several drawbacks.

Think of a project where they decide to divide the code in several reusable packages. Those packages are not going to be used out of the scope of that project or application. So they don't even want to use its own npm private repository and they don't want to publish the packages. They only want some kind of versioning control. Each group of code has its own package.json and the main or parent application listing those local packages as its dependencies.

Now the only good solution to this scenario is to place each package in its own git repository and list the git url instead of the version:
`"name": "git-url"`
What allows us to go to the main application and just run "npm install".

But think of a project where they decided to divide the code in 30 packages. They are forced to maintain 30 git repositories. It would be very useful if they could place those packages in a "local packages" folder in the same repo.

The solution to use "npm install folder-name" or "npm link folder-name" has a couple of drawbacks:

1. You have to manually install each folder one by one.

    You cannot run "npm i" and let npm to find the location of each local dependency. So if your application has 20 local dependencies and 20 remote dependencies you have to know what dependencies are local and run "npm install localfolder" or "npm link localfolder" on each one. And maybe you'll end coding some script to automate the process. 

2. You don't get the advantage of the package deduplication.

    When you run "npm install" and your dependencies are downloaded from a npm repository or a git repository, "npm" avoid installing packages that are already installed in the parent application. 

    So if your application and all your local modules depend on "async@0.8.0" you'll end up with only one copy of "async" in your node_modules folder. But running "npm link" for each local dependency causes duplication of "async" on each package, and the same running "npm install folder" if you do it before installing the remote dependencies. 

I saw on the Internet people asking for a good solution for manage local dependencies, and they end up making its own hacks with "npm link" to make it work. So it would be very useful to have a better automatic solution in npm. In the same way you can reference a git-repo (in the end is just a folder) it would be useful to reference a local folder relative to the path of the package.json.

**e.g.**
`"name": "relative-path@version"`
Don't know if that would be a right solution, I think the main thing is a mechanism to specify a relative path to the package, but maybe it is useful to specify the expected version, to fail when the referenced folder has an unexpected version.

**Comment by othiym23** [comment]
Closing as resolved / abandoned.

**Comment by nitroduna** [comment]
I haven't seen the notification until now. The "local paths" feature of npm2 is what we were waiting for. Thanks a lot. You seem to have made a lot of great improvements in npm2.

**Comment by RameshRM** [comment]
I am using npm2.1.4, I still have issues w/npm module require from relative sub-projects.  I am building a multi-module project and all the modules are not intended to be published. 

I dont want to require('../../relative-paths').  Rather, i would do `npm install ../relative-module --save` and do `require('relative-module')`.  This seem to be the problem, my module is unable to discover.

**Comment by smikes** [comment]
@RameshRM can you please create a new issue to discuss your needs?  This issue has been closed.
