### ISSUE TITLE
Error installing dependency via private repo URL (via travis)

### ISSUE THREAD

**Issue by tonylukasavage** [npm/npm#5307]
I have travis CI running against node.js 0.10.26 (npm 1.4.3) and 0.11.13 (npm 1.4.9). Obviously the entire setup is identical for each version. As part of my dependency list I make reference to a private github repo:

```json
{
  "devDependencies": {
    "myrepo": "myname/myrepo"
  }
}
```

The repo is authenticated via the SSH key setup detailed [here](http://docs.travis-ci.com/user/travis-pro/#How-can-I-configure-Travis-Pro-to-use-private-GitHub-repositories-as-dependencies%3F). When run as part of a Travis CI build, the node.js 0.10.26 & npm 1.4.3 installs the dependency as expected. While inconsequential, the rest of my tests are also successful. The 0.11.13 node.js with npm 1.4.9, however fails with the following error when attempting to clone my private repo:

```
npm ERR! git clone git://github.com/myname/myrepo.git Cloning into bare repository '/home/travis/.npm/_git-remotes/git-github-com-myname-myrepo-git-77c98e8d'...
npm ERR! git clone git://github.com/myname/myrepo.git fatal: remote error: 
npm ERR! git clone git://github.com/myname/myrepo.git   Repository not found.
npm http 200 https://registry.npmjs.org/grunt/-/grunt-0.4.5.tgz
npm ERR! Error: Command failed: git clone --mirror git://github.com/myname/myrepo.git /home/travis/.npm/_git-remotes/git-github-com-myname-myrepo-git-77c98e8d
npm ERR! Cloning into bare repository '/home/travis/.npm/_git-remotes/git-github-com-myname-myrepo-git-77c98e8d'...
npm ERR! fatal: remote error: 
npm ERR!   Repository not found.
npm ERR! 
npm ERR!     at ChildProcess.exithandler (child_process.js:729:12)
npm ERR!     at ChildProcess.EventEmitter.emit (events.js:110:17)
npm ERR!     at maybeClose (child_process.js:992:16)
npm ERR!     at Socket.<anonymous> (child_process.js:1142:11)
npm ERR!     at Socket.EventEmitter.emit (events.js:107:17)
npm ERR!     at Pipe.close (net.js:461:12)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>
npm ERR! System Linux 2.6.32-042stab079.5
npm ERR! command "/home/travis/.nvm/v0.11.13/bin/node" "/home/travis/.nvm/v0.11.13/bin/npm" "install"
npm ERR! cwd /home/travis/build/myname/myotherrepo
npm ERR! node -v v0.11.13
npm ERR! npm -v 1.4.9
npm ERR! code 128
npm http 200 https://registry.npmjs.org/querystring
npm http 200 https://registry.npmjs.org/grunt-env
npm http GET https://registry.npmjs.org/grunt-contrib-clean/-/grunt-contrib-clean-0.5.0.tgz
npm http GET https://registry.npmjs.org/querystring/-/querystring-0.2.0.tgz
npm http GET https://registry.npmjs.org/grunt-env/-/grunt-env-0.4.1.tgz
npm http 200 https://registry.npmjs.org/querystring/-/querystring-0.2.0.tgz
npm http 200 https://registry.npmjs.org/grunt-contrib-clean/-/grunt-contrib-clean-0.5.0.tgz
npm http 200 https://registry.npmjs.org/commander/-/commander-2.2.0.tgz
npm http 200 https://registry.npmjs.org/tiapp.xml
npm http 200 https://registry.npmjs.org/grunt-mocha-test
npm http 200 https://registry.npmjs.org/grunt-contrib-jshint
npm http 200 https://registry.npmjs.org/should
npm http 200 https://registry.npmjs.org/grunt-env/-/grunt-env-0.4.1.tgz
npm http GET https://registry.npmjs.org/tiapp.xml/-/tiapp.xml-0.1.1.tgz
npm http GET https://registry.npmjs.org/grunt-mocha-test/-/grunt-mocha-test-0.10.2.tgz
npm http GET https://registry.npmjs.org/grunt-contrib-jshint/-/grunt-contrib-jshint-0.10.0.tgz
npm http GET https://registry.npmjs.org/should/-/should-3.3.1.tgz
npm http 200 https://registry.npmjs.org/grunt-mocha-test/-/grunt-mocha-test-0.10.2.tgz
npm http 200 https://registry.npmjs.org/grunt-contrib-jshint/-/grunt-contrib-jshint-0.10.0.tgz
npm http 200 https://registry.npmjs.org/tiapp.xml/-/tiapp.xml-0.1.1.tgz
npm http 200 https://registry.npmjs.org/should/-/should-3.3.1.tgz
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/travis/build/myname/myotherrepo/npm-debug.log
npm ERR! not ok code 0
The command "npm install" failed. Retrying, 2 of 3...
```

Adding the following to my `.travis.yml` file made both builds work, so I assume there's some bug in the current iteration of npm that causes this, but I have not pinpointed the exact cause.

```yml
before_install: npm install -g npm@1.4.3
```

To note, I also tried installing the latest (currently 1.4.10) this way and it ended with the same error as 1.4.9. I did not test versions 1.4.4-1.4.8. I simply rolled back to the version that I knew worked in my 0.10.x testing (1.4.3.) with 0.11 and now things are working.

**Comment by smikes** [comment]
Is this still a problem for you?

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.4.9. Can you try updating your npm installation?

To update npm, run `npm -g install npm@latest`

For some Linux distributions (Debian/Ubuntu and RedHat/CentOS), the latest node version provided by the distribution may lag behind the stable version. [Here are instructions from NodeSource](https://github.com/nodesource/distributions) on getting the latest node.

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as abandoned, and possibly resolved?

**Comment by tonylukasavage** [comment]
I apologize for not coming back to this one. No, I am no longer experiencing the issue. Unfortunately I can't pinpoint, WRT an npm version, when this was resolved. But much appreciated anyway!
