### ISSUE TITLE
npm ls will show peerDependencies as missing if module is npm linked

### ISSUE THREAD

**Issue by mpj** [npm/npm#5308]
Oh, peerDependencies and npm link, why can't you just get along? :smiley: 
### Steps to reproduce
1. Your module B requires third-party module X as a peerDependency. 
2. You are actively working on module B, which is a dependency of module A, so you use 'npm link\* to create symlink from module A to your working directory for module B. 
3. This works fine an all, but if you run _npm ls_, you'll get this message at the bottom:
   npm ERR! missing: X@1.2.3, required by B@1.2.3

The error seems to be purely "cosmetical", in the sense that development works fine, but the error threw me off for quite a while, sending me on a wild goose chase for a couple of hours so I think it should be fixed or at least be made clearer. 

I get the same error if I run _npm ls_ inside the working directory of module B. Getting the error there makes sense, because it's not really an actual subdirectory, just a symlink, so it has no way of knowing that it's peerDependency is satisfied. However, when I run _npm ls_ in the directory of module A, I think _npm ls_ should be able to be clever enough to figure out that the dependency is indeed satisfied.

**Comment by dlongley** [comment]
This behavior may change with node 6.x as symlinks are now preserved (not deep-resolved w/realpath). If we're lucky it just works now.
