### ISSUE TITLE
Default spinner to a slower rate, then speed up with each release.

### ISSUE THREAD

**Issue by dylang** [npm/npm#5329]
The spinner is spinning too fast. This doesn't give us room to *improve*.

Lets make the spinner slower asap, before too many people get used to the current rate.

This is important:

Every release, decrease the interval by a small bit, making the spinner spin slightly faster.

Users will notice this change, and they will think that it means the new version of npm *feels* faster than their previous version. 

If they skip versions they will *really* notice the speed increase and tell everyone that *the new npm is so much faster!*. 

My theory is that *feeling fast* is just as important as *being fast*. That's why we progressively load web content or Disney parks overestimate line wait times.

**Comment by iarna** [comment]
Spinner discussions are preeeettty much obsoleted by the npm@3 progress bar. I'll keep this idea in mind though. 😉
