### ISSUE TITLE
dependencies break when updating some modules

### ISSUE THREAD

**Issue by mreinstein** [npm/npm#5397]
Here's an example of the problem as per https://github.com/isaacs/node-glob/issues/103:
```bash
npm install glob@3.2.1
npm install browserify@4.0.2
```

in this case, browserify works fine. Browserify depends on glob 3.x, which it detects as present.

now run this:
```bash
npm remove glob
npm install glob@4.0.0
```

upon running `npm ls`, we'll see errors for browserify missing a valid glob package.  Currently the way to fix this is to run `npm i browserify` which will pick up the changes and install the `glob@3.x` dependency.

This issue is not specific to these 2 packages, it's because npm doesn't check the state of the other npm modules to see if changing a module has affected other modules that might depend on it. 

Ideally, npm would register a hook whenever modules are added/changed/removed, walk the dependency tree, and automatically affect install needed deps and remove unused modules.

**Comment by othiym23** [comment]
This is one of the things that motivated the development of `npm@3`, and as such, now works as you'd expect with `npm@latest`. Therefore, I'm closing this as resolved. Thanks for your time!
