### ISSUE TITLE
npm bundleDependencies (ends up missing dependencies)

### ISSUE THREAD

**Issue by stefanpenner** [npm/npm#5437]
given: `main -> testem -> backbone -> underscore` underscore is missing.

node version: `v0.10.28`
npm version: `v1.4.9`
os: `osx 10.9.3`

**Comment by iarna** [comment]
Closing this as fixed in [npm/npm#multi-stage](https://github.com/npm/npm/tree/multi-stage)

**Comment by stefanpenner** [comment]
@iarna i was unable to verify as ember-cli does not install with mutli-stage yet
