### ISSUE TITLE
Installing protractor

### ISSUE THREAD

**Issue by sunny0408989** [npm/npm#5544]
hi team,

i have a lot of questions as i am really confused how to install protractor.
Firstly i am in my company network.

1. i have installed node js on my machine. In the nodejs cmd when i am using 'npm install protractor@1.4.14' or 'npm install protractor' it is giving me an error like "Refusing to install protractor as a dependency of itself".How should i proceed?
2. How to check whether proctractor is installed or not? I have used 'npm protractor --version '  command and it is giving me '1.4.14'
3. Lastly i am tried to install dependicies by using command 'npm install' but that that is giving me proxy issue saying that "If you are behind a proxy, please make sure that proxy config is set properly ". How to install the same using Proxy?

Thanks,
Sunny

**Comment by othiym23** [comment]
Closing as pretty comprehensively resolved. That is some support, @smikes! (Thanks for yr help too, @chrismeyersfsu!)
