### ISSUE TITLE
should be a way to link into nested modules

### ISSUE THREAD

**Issue by bmeck** [npm/npm#5555]
due to path limitations of applications on windows `npm link $module` may be inconvenient to link against development versions of packages (mostly due to cmd.exe not supporting long paths).

there should be a way to use `npm link x` that can target a nested module such that:

```
root/node_modules/a/node_modules/b
```

can be linked to `x` like:

```
root/node_modules/a/node_modules/b/node_modules/x -> prefix/x
```

alternatively we could document that each module in the chain should linked to avoid path issues, so `a` links to `b` links to `x`, but this is much more effort on the part of the developer.

**Comment by othiym23** [comment]
`npm@3`'s built-in flattening and deduping functionality renders a lot of the issues about working with package trees on Windows moot. At the same time, trying to support this kind of nested linking on a deduped tree is the sort of brain-bender that I don't think anybody wants to either implement or support. As such, I'm going to close this issue. Thanks for your time, Bradley!
