### ISSUE TITLE
`npm publish` writes inconsistent data to the cache folder

### ISSUE THREAD

**Issue by grncdr** [npm/npm#5561]
When you `npm publish` a package, it is added to the cache [here](https://github.com/npm/npm/blob/master/lib/publish.js#L50). However, the `package.json` created by `npm.cache.add` does not include the `_resolved` field. To understand why this matters you need to follow a few steps.
1. I have two packages, A (app) and B (lib).
   - A depends on B.
   - Both packages are published to an alternate registry.
2. I lock dependency versions in package A using `npm shrinkwrap`
3. When I `npm publish` B@1.2.3, the `package.json` with no `"_resolved"` field is written to my cache dir.
4. When I `npm install --no-shrinkwrap B@1.2.3` in A, `node_modules/B/` is copied from the cache.
5. When I then `npm shrinkwrap` in A to update the shrinkwrap file, the `"resolved"` field in the shrinkwrap file assumes the package came from `registry.npmjs.org`.
6. When I try to `npm install` on another machine, it attempts to find the package on `registry.npmjs.org` and 404's
7. My build is broken, and I turn to :beer:

/cc @ehd

Also, as I mentioned over on #4042 the same behaviour will occur with `npm install /path/to/package` though in that scenario it's a little more understandable.

**Comment by othiym23** [comment]
After further discussion, the CLI team has reclassified this as a bug, specifically related to shrinkwrap and the cache. The correct solution is probably to have the shrinkwrap code synthesize (or omit) a `"resolved"` field when there isn't one in the local `package.json` at shrinkwrap time. Having there be a buried linkage between _how_ a package got into the cache and being able to shrinkwrap a local application is weird and incorrect. It may be a bit until the team has time to address this (although we are looking at a number of issues related to shrinkwrapping right now), but this should be relatively straightforward for the community to patch. Thanks to all for their time and patience!
