### ISSUE TITLE
npm error

### ISSUE THREAD

**Issue by snr** [npm/npm#5564]
When using Webstorm 8 to create a new project, I get the following error.

<pre>Error creating Node.js Express App. Failed command:
"C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" install
Exit code: -1
Standard error:
npm ERR! Error: UNKNOWN, open 'C:\Users\Senthil\AppData\Roaming\npm-cache\qs\0.6.6\package\package.json'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd C:\Users\Senthil\WebstormProjects\trax-web
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! path C:\Users\Senthil\AppData\Roaming\npm-cache\qs\0.6.6\package\package.json
npm ERR! code UNKNOWN
npm ERR! errno -1
npm ERR! Error: ENOENT, lstat 'C:\Users\Senthil\WebstormProjects\trax-web\node_modules\express\node_modules\accepts\node_modules\negotiator\LICENSE'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd C:\Users\Senthil\WebstormProjects\trax-web
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! path C:\Users\Senthil\WebstormProjects\trax-web\node_modules\express\node_modules\accepts\node_modules\negotiator\LICENSE
npm ERR! fstream_path C:\Users\Senthil\WebstormProjects\trax-web\node_modules\express\node_modules\accepts\node_modules\negotiator\LICENSE
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack C:\Program Files\nodejs\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat 'C:\Users\Senthil\WebstormProjects\trax-web\node_modules\express\node_modules\accepts\node_modules\mime\LICENSE'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd C:\Users\Senthil\WebstormProjects\trax-web
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! path C:\Users\Senthil\WebstormProjects\trax-web\node_modules\express\node_modules\accepts\node_modules\mime\LICENSE
npm ERR! fstream_path C:\Users\Senthil\WebstormProjects\trax-web\node_modules\express\node_modules\accepts\node_modules\mime\LICENSE
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack C:\Program Files\nodejs\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat 'C:\Users\Senthil\WebstormProjects\trax-web\node_modules\jade\node_modules\monocle\node_modules\readdirp\.npmignore'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd C:\Users\Senthil\WebstormProjects\trax-web
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! path C:\Users\Senthil\WebstormProjects\trax-web\node_modules\jade\node_modules\monocle\node_modules\readdirp\.npmignore
npm ERR! fstream_path C:\Users\Senthil\WebstormProjects\trax-web\node_modules\jade\node_modules\monocle\node_modules\readdirp\.npmignore
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack C:\Program Files\nodejs\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat 'C:\Users\Senthil\WebstormProjects\trax-web\node_modules\jade\node_modules\constantinople\node_modules\uglify-js\test\compress\issue-12.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd C:\Users\Senthil\WebstormProjects\trax-web
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! path C:\Users\Senthil\WebstormProjects\trax-web\node_modules\jade\node_modules\constantinople\node_modules\uglify-js\test\compress\issue-12.js
npm ERR! fstream_path C:\Users\Senthil\WebstormProjects\trax-web\node_modules\jade\node_modules\constantinople\node_modules\uglify-js\test\compress\issue-12.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack C:\Program Files\nodejs\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat 'C:\Users\Senthil\WebstormProjects\trax-web\node_modules\jade\node_modules\transformers\node_modules\uglify-js\node_modules\source-map\README.md'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd C:\Users\Senthil\WebstormProjects\trax-web
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! path C:\Users\Senthil\WebstormProjects\trax-web\node_modules\jade\node_modules\transformers\node_modules\uglify-js\node_modules\source-map\README.md
npm ERR! fstream_path C:\Users\Senthil\WebstormProjects\trax-web\node_modules\jade\node_modules\transformers\node_modules\uglify-js\node_modules\source-map\README.md
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack C:\Program Files\nodejs\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat 'C:\Users\Senthil\WebstormProjects\trax-web\node_modules\jade\node_modules\transformers\node_modules\uglify-js\node_modules\optimist\index.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd C:\Users\Senthil\WebstormProjects\trax-web
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! path C:\Users\Senthil\WebstormProjects\trax-web\node_modules\jade\node_modules\transformers\node_modules\uglify-js\node_modules\optimist\index.js
npm ERR! fstream_path C:\Users\Senthil\WebstormProjects\trax-web\node_modules\jade\node_modules\transformers\node_modules\uglify-js\node_modules\optimist\index.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack C:\Program Files\nodejs\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm</pre>

**Comment by othiym23** [comment]
Closing as resolved, probably (otherwise abandoned).
