### ISSUE TITLE
Feature: npm-install-or-update 

### ISSUE THREAD

**Issue by mikesmithson** [npm/npm#5582]
Would be nice to have something that would run npm install if the node_modules dir was empty and run npm update otherwise. I was thinking something like 'npm install -u' or 'npm update -i'

**Comment by smikes** [comment]
If `node_modules` is empty or missing, `npm update --depth 0` acts like a normal `npm install` (tested with `npm@next`, 2.6.1).

Can you try this out and let us know if it meets your needs?

**Comment by iarna** [comment]
This is also related to #5254

**Comment by othiym23** [comment]
Good news! `npm@3` will install missing packages if `node_modules` is missing when `npm update` is run. @iarna points that `npm update <single_module>` won't work, but that's in keeping with most expectations of how update (vs install) should behave. As such, I'm going to close this feature request as resolved. Thanks for your time and patience!
