### ISSUE TITLE
npm init 

### ISSUE THREAD

**Issue by faiq** [npm/npm#5612]
npm init does not set an author by default, even if you have one in your npmrc. Maybe it would make a nice feature?

**Comment by MartinDelille** [comment]
Bower uses the git global username and email: https://github.com/bower/bower/blob/0bb1536c9972e13f3be06bea9a8619632966c664/lib/commands/init.js#L141-L159

Wouldn't that be a good way to have a default author in npm?

**Comment by othiym23** [comment]
There would be less room for error, which means that this would be a nice affordance to land as a patch. At the same time, the CLI team has a lot going on, and this isn't something we're going to address in the next year. As such, I'm going to close it. Thanks for raising this, Faiq! And thanks to all for their time.
