### ISSUE TITLE
`npm ls module-name` does not print dep tree for that module

### ISSUE THREAD

**Issue by malandrew** [npm/npm#5628]
`npm ls` will use substack's tree module to print out the entire dep tree. However, doing `npm ls some-dep` will not print the dep tree for just that module.

**Comment by smikes** [comment]
Can this issue be closed?

In current `npm` (2.3.0), this discrepancy still exists between what a user might expect (`npm ls` shows whole tree, `npm ls foo` should show subtree rooted at `foo`) and what actually happens (`npm ls foo` shows all paths that lead to `foo`).

I would bikeshed in favor of taking `npm find` (which is currently an alias to `npm search`) and make the behavior of `npm find foo` be what `npm ls foo` currently does; this would free up `npm ls foo` to mean something more compatible with what `ls foo` means.

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by malandrew** [comment]
Yes, this can be closed. This is more of an issue where the behavior didn't match expectations, but it's not a huge issue and not worth bikeshedding over. If I really need this info I can `npm explore foo` and then run `npm ls`

**Comment by othiym23** [comment]
@smikes, that's not a terrible idea, but keep in mind that the deprecation and repurposing cycle is at least 2 major versions long (plus probably a minimum amount of calendar time, like 6 months -- @iarna and I are still figuring out what the best policy is here), and as such should be reserved for last-resort behavior changes. I imagine @isaacs also has opinions about that.

**Comment by smikes** [comment]
@malandrew nailed it, actually.  The command here is 

```
npm explore foo -- npm explore ls
```

Since that provides the same functionality as my notional repurposing of `npm ls foo`, there is no need to repurpose or bikeshed. ;-)
