### ISSUE TITLE
`npm uninstall --save pkg` does not work if pkg is not installed 

### ISSUE THREAD

**Issue by sam-github** [npm/npm#5635]
This is asymetrical with install:

1. `npm install pkg`
2. `npm install pkg --save` this will save dep spec even though its installed
3. `npm uninstall pkg`
4. `npm uninstall pkg --save` this will error, saying its not installed...

**Comment by othiym23** [comment]
This has been fixed in `npm@3`! :tada: Thanks for raising this, and thanks for your patience while we figured out that we got it done.
