### ISSUE TITLE
npm outdated doesn't handle GitHub repositories as expected

### ISSUE THREAD

**Issue by goloroden** [npm/npm#5640]
Supposed in my `package.json` I have a dependency to a GitHub repository, using a private module:

```
"dependencies": {
  "foo": "mycompany/foo#0.1.0"
}
```

Now, a public module with the name `foo` exists, too, but - as it is a different module - it has a different version number.

When I run

```
$ npm outdated
```

my privately hosted module is shown as outdated (which is wrong).

**Comment by othiym23** [comment]
The CLI team still intends to ship functionality that harmonizes the user experience of working with npm registry dependencies and hosted Git dependencies. The correct behavior here is, when given a GitHub dependency that has a commitish, to look up and compare against that commitish; if given a GitHub dependency that has a semver range, a la Bower (which isn't currently supported for using hosted Git dependencies with npm at all), to compare the declared version against that semver range. First-class Git dependencies are on the CLI's road map, but there's not yet a start date for when the team plans to begin addressing these issues, so it may be a while yet. Thanks for your time and patience!
