### ISSUE TITLE
After using "unpublish" the package is still findable through npmjs.org search

### ISSUE THREAD

**Issue by cjolif** [npm/npm#5645]
Following a typo in the package name I unpublished generator-delitefull-app (in favor of generator-deliteful-app). However if I do:

https://www.npmjs.org/search?q=deliteful

The unpublished package is still listed. Ok if you click on it you see it as "unpublished" but still as it appears before the actual / ok package this is not so nice. I guess unpublished pacakge page should still be reachable but not listed in search? (or under an option?)

**Comment by smikes** [comment]
Ref #6107 , by default hide some packages from `npm search`.

**Comment by othiym23** [comment]
This isn't an issue with the CLI, and recent changes made to the web site's search results (I think) render this issue moot regardless. I'm going to close it on this issue tracker, and if you believe that this behavior is still an issue on the web site, please file an issue on [`npm/www`](https://github.com/npm/www/issues), the new repo for tracking web site issues. Thanks for your time!
