### ISSUE TITLE
npm's "error parsing json" error should tell you more information

### ISSUE THREAD

**Issue by fresheneesz** [npm/npm#5660]
I saw this error in the most recent version of node (node -v v0.10.25, npm -v 1.3.24), but it didn't give any information about what the json error was, or what file was incorrect. Npm just continued chugging along like it never happened tho. A more useful error message should be generated for that.

**Comment by smikes** [comment]
Can this issue now be closed?

A specific instance of "error parsing json" (related to read-package-json, so specifically, errors in reading `package.json` files) has now been fixed to provide information about where in the file the parse error occurred.  (See this commit: https://github.com/npm/npm/commit/abdd040da90932535472f593d5433a67ee074801 )

Did this error come from a package.json, or from a registry response, or.. ?

Thanks!

**Comment by fresheneesz** [comment]
I believe I saw this with an `npm install`, but since the error was very generic, I have no idea what caused it. I suppose you can probably close it until someone sees it again. I should have given more repro info.

**Comment by busches** [comment]
@KenanY Per @fresheneesz this can be closed.
