### ISSUE TITLE
Consider installing to ~/.npm-packages by default

### ISSUE THREAD

**Issue by pwojnowski** [npm/npm#5677]
Like here: http://stackoverflow.com/a/13021677/3348552

IMHO this should be the default for "npm install package". Is anyone installing anything globally these days? What to do when one needs to move to another laptop? Moving home directory is easy.
Anyway, people new to npm usually have a hard time installing packages for the first time.

Thanks!

**Comment by othiym23** [comment]
The current behavior of npm around global dependencies vs local dependencies is pretty well-established; people who have strong opinions about where their npm-managed binaries are installed have the option of using `npm set prefix '~/.npm-packages'` themselves. The supportability consequences of changing the default are grave enough that they make this a far more costly change than the resulting benefit justifies. As such, I'm going to close this feature request. Thanks for your time!
