### ISSUE TITLE
Not installing deps of deps from shrinkwrap

### ISSUE THREAD

**Issue by anton-rudeshko** [npm/npm#5693]
Following issue from https://github.com/bower/bower/pull/1403.

Given [this package.json and npm-shrinkwrap.json](https://gist.github.com/anton-rudeshko/125b6ed0717d4bc5b226) I see this:

```
$ npm install
bower@1.3.5 node_modules/bower
⋮
├── tmp@0.0.23
⋮
```

```
$ npm install bower
bower@1.3.5 node_modules/bower
⋮
├── tmp@0.0.24
⋮
```

Isn't it supposed to install same `tmp` version?

/cc @rndD, @shuhrat, @st-lukas

**Comment by smikes** [comment]
Confirmed that this is still present in `npm@next`, 2.5.1, as of today.

**Comment by iarna** [comment]
With 2a13363 and a268777 this is fixed in [npm/npm#multi-stage](https://github.com/npm/npm/tree/multi-stage)
