### ISSUE TITLE
'npm publish' uses user data from ~/.npmrc instead of the project specific .npmrc

### ISSUE THREAD

**Issue by necccc** [npm/npm#5717]
Scenario:
- I want to use an npm module with my private npm registry (in this case: sinopia)
- In the project .npmrc I set the registry to my private one
- I set a username in sinopia with publish access, this user is not registered in npm
- I set the same user in the project .npmrc
- doing npm publish in the project folder results a 403 error message from the private repo

After doing some debug it seems, 'npm publish' only recognizes the registry from the .npmrc file, but not the username, and it tries to publish with my user from ~/.npmrc

The only workaround I've found, is to create npm the user I've set in the private registry,
'npm login' with it, then try to publish - it succeeds, but i've to re-login every time I've want to update that module in the private repo.

**Comment by smikes** [comment]
Can this issue now be closed?  

It looks like you were able to find ways to achieve the thing you wanted to do, using existing but poorly-documented features.

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by necccc** [comment]
Yes, you can close this.
Thank you

**Comment by othiym23** [comment]
Closing as resolved.

**Comment by whitecolor** [comment]
I dont' get should or not `npm publish` take authToken from local .npmrc (located in current folder), authorize and with it? For me it doesn't work:

```
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "publish" "--access=public"
npm ERR! node v7.1.0
npm ERR! npm  v3.10.9
npm ERR! code ENEEDAUTH

npm ERR! need auth auth required for publishing
npm ERR! need auth You need to authorize this machine using `npm adduser`
```

**Comment by whitecolor** [comment]
Hm this is really kind of strange the reason for this is is that script that is calling `npm publish` is run by `yarn run`! Good  protection from competitors, npm! =)
