### ISSUE TITLE
npm install should remove `node_modules` line from installed `.gitignore`

### ISSUE THREAD

**Issue by dominykas** [npm/npm#5722]
In most of the packages [that I'm using], `.npmignore` does not exist, so it is created by renaming the `.gitignore`. However, in some of them both -`.npmignore` and `.gitignore` exist. This basically leads back to the problem of https://github.com/npm/npm/issues/1886 - not all the dependencies get checked in for those of us who like to keep `node_modules` under version control.

Removing `node_modules` line in any of the installed `.gitignore` files is not a problem, since the whole  parent `node_modules` is already ignored by those, who do not like checking it in.

This will save me running `find . -name .gitignore | xargs grep -l 'node_modules' | xargs sed -i '' '/node_modules/d'` with every install :)

**Comment by dominykas** [comment]
I believe this can now be closed? Not sure which version introduced that, but `.gitignore` is now [correctly?] never included in the published package (also it seems that packages installed directly from git also have this cleaned up properly?)

**Comment by othiym23** [comment]
Closing as resolved. Yes, both of those things have been changed in the last 6 months or so, as we try to ensure that git dependencies are at least handled consistently with respect to how npm caches regular directories and tarballs.
