### ISSUE TITLE
"VAR=value command param" working on Unix but not on Windows in package.json

### ISSUE THREAD

**Issue by bcomnes** [npm/npm#5738]
On *nix systems, I can add something like this to my module's `package.json`:

``` json
{
"scripts": {
    "dev": "DEBUG=routes:* ENV=development node ./bin/www"
  }
}
```

which sets up some simple ENV vars for me to use with some popular modules like [debug](https://www.npmjs.org/package/debug).

This does not work on windows however, even though you can totally run:

``` sh
DEBUG=routes:* ENV=development node ./bin/www
```

from git bash or whatever.
Maybe this is totally an anitpattern, but it seems like this should work on windows too.  

> @othiym23: win-spawn is smart enough to deal with that, so npm should be able to as well

**Comment by sheerun** [comment]
But win-spawn won't work on non-windows: https://github.com/ForbesLindesay/win-spawn/issues/13

**Comment by sheerun** [comment]
There's: http://npm.im/cross-env

**Comment by bcomnes** [comment]
Works for me.
