### ISSUE TITLE
`npm ping` to test registry reachability

### ISSUE THREAD

**Issue by othiym23** [npm/npm#5750]
As described by @yorkie and @timoxley on #5743, it would be very useful to have a simple command that ensures that the registry (either the default, or selectable via `--registry`) is reachable (and, optionally, that your credentials for that registry are valid).

This would be very useful to have as a troubleshooting tool available to `npm report` (#5214).

**Comment by legodude17** [comment]
I would want something like `npm ping $package` then it would attempt to fetch `$package` from the registry. And then `npm fetch $package` to just fetch and unzip the tarball of `package`.
