### ISSUE TITLE
install only devDependencies

### ISSUE THREAD

**Issue by othiym23** [npm/npm#5776]
Use case:

* developer has `node_modules` under git control
* CI runs `npm install --[[devDepsOnly]]` to install devDependencies *without changing any non-development dependencies
* tests finish SUCCESSFULLY WOO PARTY
* CD runs `npm prune --production` so no extra bits are left on disk
* packed application is deployed without extra crap hanging around

**Comment by watilde** [comment]
This issue seems that has already resolved...?

**Comment by othiym23** [comment]
This was implemented by @bengl as `npm install --only=dev` for his own nefarious purposes in `npm@3`. :tada: Y'all shipped a thing without us! Thanks to all for their patience, and to @bengl for implementing this!
