### ISSUE TITLE
npm install --minimum

### ISSUE THREAD

**Issue by timoxley** [npm/npm#5800]
At development-time, it's currently difficult for authors to install and test against the minimum version they have specified in their package.json.

Consider this situation:
1. `packageA` specifies `^1.0.0` range for `packageB`.
2. `packageB` adds a featureX, releases `packageB@1.1.0`
3. Developer of `packageA` runs `npm install`, gets `packageB@1.1.0`.
4. `packageA` releases a new version, using featureX of `packageB`, not realising featureX only exists in `packageB@1.1.0`. i.e. minimum should have been updated to `^1.1.0`, but developer has no way to know (other than manually installing and testing, but this doesn't scale well)
5. `packageC` depends on `packageB@1.0.0` (without featureX) and `packageA@2.1.0`.
6. Chaos as the semver haters materialize.

`packageB@1.0.0` will satisfy `packageA@1.1.0`'s `^1.0.0` range for `packageB`, and `packageA` will get the incorrect version. 

It would be a good practice package authors to install and test their latest changes against the supposed minimum possible version they've specified in their package.json. This scenario doesn't seem to appear very often though, and part of semver's magic is that authors generally don't/shouldn't need to think about it. If authors are forced to think about it, it's more likely they will simply pin to exact versions to save the hassle, so maybe best overall solution would be to just ignore this possibility.

**Comment by ljharb** [comment]
Could this work just by, for any `semver.Range`, converting that to the lowest value?

The use case for me is, `rm -rf node_modules && npm install && npm test` compared to `rm -rf node_modules && npm install --minimum && npm test` - if both work, i'm good, if the second fails, some of my deps need the bottom of their ranges bumped.

I've definitely seen this happen in the while a lot with modules I depend on, and this would be a pretty damning one-liner to convince them it needs bumping in a PR :-)
