### ISSUE TITLE
allow a prefix for GitHub specifiers in package.json

### ISSUE THREAD

**Issue by othiym23** [npm/npm#5801]
PLEASE NOTE: "allow", not "require"

It would be nice to be able to clearly disambiguate all of the different kinds of specifiers for non-registry installs in `package.json`. See [this comment and following](https://github.com/npm/npm/pull/5629#issuecomment-50095354) for an example of why this is getting more important.

My finger-in-the-wind proposals is `github://`; @isaacs's is `gh://`. Note that this starts laying down a cowpath for `bitbucket://` or `stash://` specifiers in the future.

**Comment by othiym23** [comment]
This is part of `npm@3` and its use of [`hosted-git-repo`](http://npm.im/hosted-git-repo). :tada: Thanks to @iarna for implementing this!

**Comment by jonathanong** [comment]
@othiym23 ^ link does not work

**Comment by KenanY** [comment]
Probably https://www.npmjs.com/package/hosted-git-info

**Comment by othiym23** [comment]
So it is! (corrected in-place)
