### ISSUE TITLE
Make npm more resilient to crashes

### ISSUE THREAD

**Issue by bfred-it** [npm/npm#5815]
Every time that I instinctively stop an installation because I made a mistake, I have to spend the next 30 minutes trying to figure out how to fix the mess NPM leaves, which is: **inability to install stuff without errors.**

Now I figured out that I have to do either or both of these commands:

    npm cache clear
    npm config set dev false

Can NPM just understand the issue and fix it automatically? Or at least intercept the exit and cleanup after itself?

**Comment by othiym23** [comment]
With the advent of `npm@3`, which adds additional logic to ensure that the install succeeds or fails as a unit, and which also does a much better job of reading `node_modules` and finding any buried inconsistencies with the installation (and fixing them!), I'm going to say that the aim of this issue has been satisfied, and am going to close this feature request as resolved. If there are specific scenarious under which which npm's install algorithm is leaving `node_modules` in a bad state, please file those as issues to be addressed. Thanks for your time!
