### ISSUE TITLE
dedupe git deps

### ISSUE THREAD

**Issue by jonathanong** [npm/npm#5827]
right now, i have 16 copies of esprima harmony, and each of those are 6mb large. dedupe doesn't work, maybe because i have like 5 other versions of esprima. 

so... if deduping git deps actually works, feel free to close this.

**Comment by iarna** [comment]
Closing this as fixed in [npm/npm#multi-stage](https://github.com/npm/npm/tree/multi-stage). At least, in so far as we're able. For git deps you need to have requested exactly the same thing for them to be considered a duplicate.
