### ISSUE TITLE
symlink all packages from the cache

### ISSUE THREAD

**Issue by jonathanong** [npm/npm#5828]
this basically solves the windows problem with nested paths, the issue of having duplicate dependencies, and the unnecessariness of running `postinstall` on every copy of the package, all while being compatible with `node_modules`' nested format.

there's the issue of isolation, but imo people shouldn't be relying on that as a feature. as a solution, an option (set in the package.json or something) could be to copy the packages to a custom cache folder, then symlink against that cache folder.

**Comment by dominictarr** [comment]
I explored this pattern in [npmd](https://github.com/dominictarr/npmd) but unfortunately node resolves symlinks to the real path instead of keeping the symlink path. this means that if you symlink to `foo` and `foo` depends on `bar`, and you already have bar installed `foo` won't fallback to your `bar`

```

- cache
  - foo

- proj
  - node_modules
    - foo -> /cache/foo
    - bar
```
if foo depends on bar it will look at `/cache/foo/node_modules/bar` and `/cache/node_modules/bar` and `/node_modules/bar` and not find `/proj/node_modules/bar` like it would have if you had copied foo to there.

which is a real shame because if it did work like that, npm install would be incredibly fast

**Comment by othiym23** [comment]
A similar approach taken by alternative package installers like [`ied`](http://npm.im/ied), [`pnpm`](http://npm.im/pnpm), and [`npm-install`](http://npm.im/npm-install). The CLI team may adopt this or a similar approach in the future, but for now there are legacy concerns (working with virtualization and containerization environments, allowing in-place modification of a particular application's installed dependencies, shrinkwrap, etc) that make this a much more expensive project than it may initially seem. The concern around Windows path lengths has largely been addressed by `npm@3`'s maximally flat installs.

As such, I'm going to close this feature request. It'll be interesting to see how things shake out over the next year or so, as npm works on its new registry API, but the CLI team, at least, isn't yet in a place to decide on a specific approach. Thanks for your time!

**Comment by dominictarr** [comment]
@othiym23 interesting! Are there any details about what the new api will be like, or it's goals at least?

**Comment by othiym23** [comment]
Two goals:

1. minimize bandwidth overhead & round-trips between client and server, to control bandwidth costs
2. significantly speed up the installation process

For the details of what the new API will look like, @chrisdickinson is in the early stages of R&D and is playing around with things like Merkle trees and content-addressable dependency trees, but it's so early in the process that any specific choices I'd describe will almost certainly be tossed overboard later on. Given the rate of growth of our serving & CDN costs, our target is to have this rolled out by around this time next year. The plan is to follow @ceejbot's typical "README-driven design" approach, and build the API as a spec first, implementation second, so there should be lots of opportunities to kick the tires before we commit anyone to having to deal with it in production.

**Comment by dominictarr** [comment]
@othiym23 that is music to my ears!
