### ISSUE TITLE
npm-scripts documentation unclear

### ISSUE THREAD

**Issue by Niggler** [npm/npm#5833]
https://github.com/npm/npm/blob/f9f58dd0f5b715d4efa6619f13901916d8f99c47/doc/misc/npm-scripts.md#examples

> the scripts/install.js will be called for the install, post-install, stages of the lifecycle ... Since scripts/install.js is running for three different phases,

As far as I can tell, the list only contains two phases.  Is there a third phase that should be mentioned (the comma after post-install suggests there is a third phase)

**Comment by othiym23** [comment]
This is a very minor bug that could be addressed by replacing the comma with "and". As such, I've tagged it with `novice`, which should probably be renamed `your-first-pr` or something similar. Thanks for drawing our attention to this!

**Comment by lholmquist** [comment]
isn't this already fixed here https://github.com/npm/npm/blob/master/doc/misc/npm-scripts.md#examples

**Comment by Niggler** [comment]
Looks like https://github.com/npm/npm/commit/c3a6e6679f3d98769df124e875d38e5e69fec925 fixed it
