### ISSUE TITLE
keeping users informed about important changes

### ISSUE THREAD

**Issue by timoxley** [npm/npm#5851]
npm could do with a friendly process for informing users about what's changed between different versions of npm.  At a minimum, it should (optionally) print a very "noob friendly" changelog after installation.

Some recent examples where this could have been useful:
* changing save-prefix default
* changing init-version default
* addition of installation spinner and changed log_level

These messages should also always include documentation indicating how to revert the changes npm wants to make.

**Comment by timoxley** [comment]
+1 [npm-weekly](http://blog.npmjs.org/post/108179966490/npm-weekly-001)

**Comment by timoxley** [comment]
@othiym23 so I think you've been doing a splendid job of communicating important changes to users. Though I'd still like packages to automatically print changelogs on `npm install`, I think we can close this issue.

**Comment by othiym23** [comment]
I'd like to figure out what hooks are needed to build something like `apt-listchanges` atop the npm install lifecycle. I think some people would be interested in automatically-displayed changelogs, but others would find it to be noise. It would require a standard changelog location (easy), a standard way to demarcate a specific release's changelog info (less easy), hooks and exposed info for old and new versions of installed packages (middling), and some way to run a global command for every package installed (???). Definitely a ways down the road. Also I'm on vacation right now! _vanishes_
