### ISSUE TITLE
Getting error while installing cordova on windows xp using npm.

### ISSUE THREAD

**Issue by Amar1111** [npm/npm#5877]
Hi 

I am trying to install cordova for mobile app development. I am installing it on windows xp using npm. When i do 

C:\>npm install -g cordova

I get the following errorrs. Please help resolving the error.

![error log](https://cloud.githubusercontent.com/assets/8362009/3810406/aae4f53e-1c8f-11e4-9774-f1adab8578e2.JPG)

**Comment by othiym23** [comment]
Also XP is no longer officially supported by Node, although it should continue to work most of the time for an indefinite period of time.

Closing as resolved / abandoned.
