### ISSUE TITLE
npm publish should fail if bundledDependencies are not present

### ISSUE THREAD

**Issue by sam-github** [npm/npm#5929]
If your package states that deps should be bundled, then publish should not silently push a package that doesn't have the dependency bundled.

**Comment by othiym23** [comment]
I still agree that publishers should be able to run `npm publish` with confidence that what gets published will be installable in a good state by end-users. A fast failure would ensure this, but the user’s experience of publishing would be significantly improved if npm were to run an install pass before running the packing job (and lifecycle script(s)) at publish time. `npm@3`’s installer is much better about producing a tree in a known good state and failing if it can’t produce that, so an install run should be sufficient. If somebody wanted to assemble a patch to do this, the CLI team would gratefully accept it. If nobody does that, the team will get to this… someday. Thanks for your patience!
