### ISSUE TITLE
npm install won't install global bins with scoped package on windows

### ISSUE THREAD

**Issue by RobinQu** [npm/npm#5944]
As we all know, all scoped packages are named like `@scope/pkgname`. I think this breaks down the link functions.

See code at https://github.com/npm/npm/blob/master/lib/build.js#L78-L8

It seems nice on unix platforms, however, on windows,  the algorithms that handle linkage of global bins won't work anymore. That's because:
1. On windows, module path looks like:
   
   ```
   'C:\\Program Files\\nodejs\\node_modules\\@scope\\pkg'
   ```
2. Scoped package uses `/` in its name, this breaks any computation based on string length or char position: `"@scope\\pkgname"` is not equal to `@scope/pkgname`.
3. All the following operations, that depends on things like `index` or `slice`,  breaks down.

At present, npm fails to take care about `bin` field in `package.json` , and I believe tons of other features must be affected too.

**Comment by smikes** [comment]
@othiym23 now that you're a Windows user you can revisit this one!

**Comment by othiym23** [comment]
This is something that will have to be fixed to properly use private modules on the npm, Inc. registry from Windows, so I've created a `registry 2` milestone and attached this issue to it. There's a bunch of other work pending that's part of this milestone as well, and it should all get tackled in the first part of this year (2015).

**Comment by iarna** [comment]
This was actually fixed by 21ca0aa, which was submitted the day after this issue was originally filed and was landed in [v2.0.0-beta.0](https://github.com/npm/npm/releases/tag/v2.0.0-beta.0).
