### ISSUE TITLE
There is no way to only rebuild only production packages

### ISSUE THREAD

**Issue by samshull** [npm/npm#5952]
By default `npm rebuild` includes all devDependencies, which can be a problem during a deployment for packages that require an external binary, like phantomjs, when there is no actual need to install phantomjs.

**Comment by othiym23** [comment]
While this is a clear description of the use case, and the behavior described would address it, this isn’t something that the CLI team is going to have time to implement within the next year or so. As such, I’m going to close this feature request. However, were someone to send us a patch with this functionality included (along with tests & docs, naturally), we’d be happy to work with them to get it merged. So I’ve added the `patch-welcome` label to indicate this. Thanks for your time, and your patience!
