### ISSUE TITLE
Trying to setup Node.js. Error in cmd.

### ISSUE THREAD

**Issue by Arihkasl** [npm/npm#5995]
I am installing Node.js from following link: http://cwbuecheler.com/web/tutorials/2013/node-express-mongo/. Have extracted the download file but on running commands "npm install -g express"; "npm install -g express-generator"; getting error as attached. Also created a new folder by name 'Node', and ran the cmd, but no positive results.
Please suggest.

![node js setup](https://cloud.githubusercontent.com/assets/8501144/3978751/067c7f3a-284c-11e4-80e6-dcd3fc60c750.JPG)

**Comment by othiym23** [comment]
Closing as abandoned.
