### ISSUE TITLE
exitcode != 0 on outdated dependencies (npm outdated)

### ISSUE THREAD

**Issue by seriousManual** [npm/npm#5999]
this a proposal for a non zero exit value for `npm outdated`.

if dependencies are found that don't match the specification from the package.json, either if they are wrong (red) or outdated (yellow) the command should return a value that is not zero.

this feature could be utilized to invalidate a build if dependencies are not up to date any more.

by default the return value should be zero, via a cli parameter the level should be configurable. e.g. return non zero if there are errors (red) or non zero if there are warnings.

if this proposal finds acceptance i'll be happy to devise a pull request.

**Comment by othiym23** [comment]
This has been moved to the [npm roadmap](https://github.com/npm/npm/wiki/Roadmap), which we're using instead of the confusing `next-*` labels now.

**Comment by othiym23** [comment]
As @isaacs said, this is a breaking change. In addition, this isn’t a change the CLI team is going to have the resources to make itself. As such, I’m going to close this feature request, but the CLI team will be happy to ship a community-contributed patch with this behavior in the next major version of npm after the patch is landed. Thanks for your time, and patience!

**Comment by watilde** [comment]
@othiym23 Can we keep opening this issue like the others breaking-change issues that are added `4.x` milestone?
+ https://github.com/npm/npm/issues?q=is%3Aopen+is%3Aissue+milestone%3A4.x

I'm curious very much about adding this feature into npm officially because I've created [a module](https://github.com/watilde/freshness) to do this before so I'd like to try building this patch if it's ok :)

**Comment by iancrowther** [comment]
if you append ``` || true``` to the command then your outdated wont fail :-)

I just wanted to use this as a status

**Comment by viskin** [comment]
@iancrowther `|| true` will not work on Windows.

**Comment by iancrowther** [comment]
@viskin fair point that.. hmm

I'd be happy to pair up and have a stab at patching this properly.

**Comment by smyrman** [comment]
> if you append || true to the command then your outdated wont fail :-)

That doesn't help to use it as a status as it would then _never_ return non-zero. It _should_ return non-zero when there is something to do...
