### ISSUE TITLE
entering passphrase does not work with the drawn process characters

### ISSUE THREAD

**Issue by flosse** [npm/npm#6015]
Within my `package.json` there are private dependencies like

```
"private-dep": "git+ssh://git@github.com/user/repo.git
```

 that cannot be installed with npm because of the continuously drawn process characters `|`, `/`,`-` at the beginning of the line when the password prompt is displayed. Is there a way to disable this "nice" animation?

**Comment by WORMSS** [comment]
Can the spinning not be set to false while the system is asking for user/password then return after it has been entered?

**Comment by othiym23** [comment]
@WORMSS this should already be the case on any even remotely version of npm. Have you seen a recurrence of that behavior? With which version of npm?

**Comment by WORMSS** [comment]
Windows 8.1
npm 2.6.1
command: npm install -g git+https://github.com/_user_/_private_repo_

This displays:
````
\sername for 'https://github.com': -
````
The spinny stays at the start, spinning away as it does. Then as you start typing it moves the spinner to the next position, and freezes it, places your letter for a brief second, and then turns back into the spinner again
````
W/ername for 'https://github.com': -
\/ername for 'https://github.com': -
````
Same for the password (except it does not try to put the letter in at the end).

**Comment by othiym23** [comment]
Well, darn. I'll have to dig into this. A test case would be awesome, but I have easy enough access to Windows test for myself. Thanks for the followup.

**Comment by WORMSS** [comment]
Thank you. I presume you have access to a private repo. But if you need of one for testing, I will gladly give you details to one of mine. Since you do not need access to the 'real' password to test the spinning nature, I do not see much of a problem.

**Comment by othiym23** [comment]
I have access to plenty of private repositories, but thank you for the offer. :tulip:
