### ISSUE TITLE
npm should have config option to make it ask for proxy credentials

### ISSUE THREAD

**Issue by dmh2000** [npm/npm#6020]
When working through a corporate proxy server, npm wants to be given the proxy credentials in plain text either on the command line or in the .npmrc. Most (all?) browsers don't require that, they will ask for the proxy credentials in a popup. It would be useful if npm could be configured to ask for the user:password. It is a little disconcerting to have to store a password in plaintext in the .npmrc file or even typing it on the command line.

**Comment by othiym23** [comment]
This seems like a reasonable request, particularly for users running from bastion hosts or other places where it would be unusual for proxy configuration to be set [via the environment](https://docs.npmjs.com/misc/config#https-proxy) (which is another way to configure your proxy without storing credentials in `.npmrc`). That said, the CLI team isn’t going to have the bandwidth to get to this in the next year, so I’m going to close this feature request. Were a contributor to send us a patch adding this – configuration that allows you to opt into a prompt-based flow for connecting to registries via proxies – we’d be happy to work with them to get it merged. Thanks for your patience, and thanks for your time!
