### ISSUE TITLE
add option to disable parent folder traversal search  

### ISSUE THREAD

**Issue by kristianmandrup** [npm/npm#6073]
Several node/js frameworks allows some kind of generator, components, addons or blueprints to be developed. Often they are used in the project later to be extracted and published as self contained. They often have their own internal `package.json` and so it is recommended to externalise their location due to isolation concerns as they would otherwise search up into the containing app `package.json` which could cause errors or conflicts etc.

Would be nice if a local `.npmrc` file could have a config option to disable this behavior. I would love to help contribute this feature if you find it acceptable and useful. I think this option should only be allowed as a CLI option or local `.npmrc` option, not a global `.npmrc` option.

How is this feasible within current architecture/design?

Reflections on current search for how to achieve this...

Adding the configuration parameter `searchParentDir` can be done around here:
https://github.com/npm/npmconf/blob/master/config-defs.js#L292

Setting default value to false (or null) here:

https://github.com/npm/npmconf/blob/master/config-defs.js#L196

Looking into the code... it seems like this line is key to the issue:

https://github.com/npm/npm/blob/master/lib/install.js#L115

```
  // the /path/to/node_modules/..
  var where = path.resolve(npm.dir, "..")
```

This is the local /path/to/node_modules ? 
Then unless config "global" is set, it proceeds running

https://github.com/npm/npm/blob/master/lib/install.js#L513

```
// just like installMany, but also add the existing packages in
// where/node_modules to the family object.
function installManyTop (what, where, context, cb_) {
  ...

  // please don't travel further up the parent folder tree!!!
  // would be nice if we had npm.config.local.get("searchParentDir")
  if (npm.config.get("searchParentDir") return false;
  if (context.explicit) return next()
  ...
```

**Comment by smikes** [comment]
I am not quite sure what you are asking for with this feature.

Is it that you would like `npm` to not install subdependencies into nested node_modules folders, or that you would like `node` not to search upward through `../../node_modules` folders, or you would like `npm` to not look through parent directories when determining whether it needs to install a particular dependency, or something else?

In any case, this issue does not seem to be about "search" in the sense of `npm search` but rather in the sense of "searching a path for a library or executable", so I will not pursue it further right now.

**Comment by kristianmandrup** [comment]
Was a mistake, sorry. I think it was caused by doing an `npm search` from a wrong folder, then finding it in a higher level "root folder", then not understanding why it didn't use my local version package.
