### ISSUE TITLE
Undocumented: How to install globally programmatically

### ISSUE THREAD

**Issue by wesleytodd** [npm/npm#6153]
I would like to install a package globally.  Something like:

```javascript
npm.commands.install(["migrate", "gulp"], {global: true}, function (er, data) {})
```

I noticed [the documentation on the `where` param](https://www.npmjs.org/doc/api/npm-install.html), but it doesn't tell what to pass for `where`.  Also, I don't trust something that says "only used internally" since that implies it might change.

My question is, should this param be documented if it is not intended to be used?  And secondly, how should I do this?

Once you show me I can add it to a doc and submit a PR.  Thanks!!

**Comment by smikes** [comment]
It seems like the simplest way to do this would be to invoke `npm install -g` using the shell… is there a reason you can't do that?

**Comment by wesleytodd** [comment]
That works, but wasn't really the point of this issue.  My main point was that it is "documented" that this feature is there, but there is no actual usage info.

The project in which I encountered this issue was supposed to be a javascript only server provisioning tool (used to use Puppet, which sucked).  Which is why I wanted to be able to do this fully inside node code.  Turns out that salt and ansible are just great, so I gave it up on this.

**Comment by smikes** [comment]
The api documentation is intended for internal use; see for example https://github.com/npm/npm/issues/6847

> be aware that the current npm API is 90+% intended for internal use, and I can't really commit to it staying stable. Calling npm as a child process (the way npm's own tests do) is safer.

It would probably be safer to treat the "api documentation" as if it were better-formatted source comments.  The API that `npm` is committed to not breaking under the terms of `semver` is the command-line interface.

**Comment by wesleytodd** [comment]
Awesome to know!  I guess I just assumed that if I could find those docs then it was stable'ish...

It might be good to add your above statement somewhere on the website, like somewhere in here: https://docs.npmjs.com/api/install

Since, as I said, I have moved on to other things I will just close up this issue, but thanks for your response!

**Comment by papiro** [comment]
npm.load({global:true}, function(err, npm){npm.commands.install(["bower"]});

**Comment by mralexgray** [comment]
@papiro ... `npm should be run outside of the node repl, in your normal shell.
(Press Control-D to exit.)`

**Comment by papiro** [comment]
Sorry, what I said was unclear.  "npm" in my code snippet was a variable.

`var npm = require("npm");`
