### ISSUE TITLE
unbuild deps recursively

### ISSUE THREAD

**Issue by isaacs** [npm/npm#6158]
Seems like a bug, or at least a shortcoming, but it's not one that has ever actually come up in practice, so this is strictly theoretical for now.

In `lib/unbuild.js`, it should do a `readdir` on the `node_modules` folder.  If that readdir errors or is empty, continue.  If not, call `npm.commands.unbuild` on all of the folders in node_modules as well.

Otherwise, a package dependency with an `uninstall` script will not have its cleanup run when the parent package is removed.

**Comment by iarna** [comment]
Closing this as fixed in [npm/npm#multi-stage](https://github.com/npm/npm/tree/multi-stage)
