### ISSUE TITLE
Add new command that makes modification of package.json file more comfortable

### ISSUE THREAD

**Issue by martinheidegger** [npm/npm#6222]
Today, when I was doing npm init i remembered that I had to add "private:true" to the project because it is a private file. I thought that it would be nice if there were a command for that

```
$ npm json set private=true
Updated ./package.json
```

I thought on it a little more and figured. It would be even cooler if it the argument was optional:

```
$ npm json set private
true[t]/false[f]: true
Updated ./package.json
```

It could be even more useful if there where shortcuts to things which syntax i always forget like:

```
$ npm json add author
You[Y/N]: N
name: Martin Heidegger
email: my@email
Updated ./package.json
```

And even more helpful if I had a list of options like:

```
$ npm json add
What? [author/license/version/...]: 
```

(This could be incredible if it was also included in the code-completion support from npm)

Very helpful also may be:

```
$ npm json increment
Current version is 1.2.1
Your update is [m]ajor(2.0.0)/m[i]nor(1.3.0)/[t]rivial(1.2.2): i
New Version is 1.3.0
run npm test? [Y/N]: N
... skipped.
git commit? [Y/N]: Y
... successful.
git push? [Y/N]: Y
... successful.
npm publish? [Y/N]: Y
... successful.
```

With a little short-cut it could be:

```
$ npm json increment minor --all-yes
```

I think all of those tasks are things people often do with npm so it might be worth adding it to npm. What do you think?

**Comment by iarna** [comment]
Thank you for writing up this clear description of this need. Having some facility to programmatically edit any value in a `package.json` would be valuable. The CLI team does not have this scheduled in the immediate (six to twelve months) future. If someone wanted to give a go at adding something like this, I think the best approach would be to start by writing it as an external tool. That gives a place to iterate on exactly what the best interface for this sort of thing would be. I’m going to close this issue, but if you do give a go at a tool like this we would be very interested in hearing about it.
