### ISSUE TITLE
inform users who publish with empty license of legal implications

### ISSUE THREAD

**Issue by seldo** [npm/npm#6241]
A polite message saying "you have no license field. Without one, it's unclear who can legally use your code and how. Are you sure you want to publish without a license?"

Alternative suggestions welcome.

**Comment by kemitchell** [comment]
Does npm have publicly posted terms of service for repository hosting, in addition to the Artistic License for the command-line client itself? I can't seem to find any. The closest is a ["code of conduct"](https://www.npmjs.com/policies/conduct).

[GitHub's terms of service](https://help.github.com/articles/github-terms-of-service/) have:

> F.1. [...] However, by setting your pages to be viewed publicly, you agree to allow others to view your Content. By setting your repositories to be viewed publicly, you agree to allow others to view and fork your repositories.

**Comment by seldo** [comment]
We have a Privacy Policy https://www.npmjs.com/policies/privacy but it is fairly generic and focused on the website. We are in the process of clarifying + expanding our policy documents to better reflect private module hosting, and I'll add this to the list of things to make clearer.

**Comment by othiym23** [comment]
This is partially addressed by the resolution of #8179 – multiple licenses can be included by using an SPDX license expression, `npm init` now prompts for an SPDX-compliant license expression, and `npm install` warns when `"license"` is missing or isn't parseable as an SPDX license expression. See [the release notes for `npm@2.10.0`](https://github.com/npm/npm/releases/tag/v2.10.0) for details.

There are some aspects of this discussion – like enforcement of the presence of a license on the registry side, including clear language warning about the legal implications on validation, and improving the terms of service for hosting – that aren't yet addressed by npm, so I'm leaving this issue open for now. Once we've got something in place that @seldo thinks fulfills the spirit of his request in the original post, we can split the remaining issues out into separate threads and close this issue.

**Comment by kemitchell** [comment]
@npm should consult its legal counsel about all three remaining aspects---enforcing licensing, warnings, and terms of service. Unfortunately, I can't weigh in on those topics via GitHub, for various "totally lame" professional reasons.

**Comment by seldo** [comment]
The warnings as implemented in 2.10.0 are sufficient for what I had in mind. You can close this ticket as far as I'm concerned, @othiym23.

@kemitchell: we are definitely not going to stride into the minefield of attempting to enforce licensing, nor @sindresorhus are we going to require a license if you ignore our nudge that it's a good idea to have one; that seems like added friction and we are against that :-)

@kemitchell's point about our terms of service for hosting benefiting from clearer language is well made; I'm going to create an issue internally for @rod11 to track that.

**Comment by othiym23** [comment]
@seldo :+1:, closing per your recommendation. Thanks, everybody!
