### ISSUE TITLE
npm dist-untag: a command to delete superfluous dist-tags

### ISSUE THREAD

**Issue by othiym23** [npm/npm#6243]
Does what the issue title says. Really important if we want to evangelize the use of dist-tags.

**Comment by fengmk2** [comment]
@othiym23 any progress?

**Comment by othiym23** [comment]
@fengmk2 Working on it. ;)

**Comment by othiym23** [comment]
Once the endpoint which @isaacs added to `npm-registry-couchapp` is rolled out to registry.npmjs.org, this command will be available in `npm@2.4.0` and newer as `npm dist-tag rm`. Thanks to everyone for their patience!

**Comment by mzgol** [comment]
@othiym23 How long should the propagation approximately take? An hour, a day, a week? :)

**Comment by othiym23** [comment]
We'll try to get the appropriate version of `npm-registry-couchapp` deployed on npm's infrastructure today, but if that doesn't happen, it will be early next week,
