### ISSUE TITLE
npm update should only update top-level dependencies

### ISSUE THREAD

**Issue by othiym23** [npm/npm#6247]
This would also make `npm update -g` behave the way people mostly think it does already, and render [these scripts](https://gist.github.com/othiym23/4ac31155da23962afd0e) redundant.

**Comment by williamboman** [comment]
I thought this would be fixed in `2.2.0`? Are [these scripts](https://gist.github.com/othiym23/4ac31155da23962afd0e) still relevant?

**Comment by jokeyrhyme** [comment]
What if we had a way to specify recursive updates, making shallow updates the default? That way newbs like me have a safe `npm -g update` whilst experts can use `npm -g -R update` or something when they know that's what they want?

**Comment by nicolasmccurdy** [comment]
@jokeyrhyme :+1: Sounds great to me.

To clarify, `npm update` (when not used globally) performs shallow updates by default, right?

**Comment by othiym23** [comment]
> To clarify, npm update (when not used globally) performs shallow updates by default, right?

Nope! It updates all the way down the local dependency tree!

**Comment by nicolasmccurdy** [comment]
Whoah, that's weird. Then I think the `-R`/`-r` idea should apply to `npm update` anywhere.

**Comment by CaptSaltyJack** [comment]
How's this coming along?

**Comment by othiym23** [comment]
[It's done!](https://github.com/npm/npm/commit/8b98f0e709d77a8616c944aebd48ab726f726f76)

**Comment by CaptSaltyJack** [comment]
WOOT! This is fixed in 2.7.4, looks like?

**Comment by othiym23** [comment]
`npm@>=2.6.1`.

**Comment by jonnybarnes** [comment]
So to clarify, can I now simply run `npm update -g` instead of running one of these: https://gist.github.com/othiym23/4ac31155da23962afd0e

**Comment by nicolasmccurdy** [comment]
Yes.

> This would also make `npm update -g` behave the way people mostly think it does already, and render [these scripts](https://gist.github.com/othiym23/4ac31155da23962afd0e) redundant.

**Comment by jokeyrhyme** [comment]
Unless you're doing a fresh install of the latest node.js / io.js, you'll still start off with an old version of npm, which means you will still need to explicitly `npm -g install npm` before you `npm -g update`, at least for that first time. So what versions of node.js / io.js come with the fixed version of npm?

**Comment by KenanY** [comment]
@jokeyrhyme:

  - Node.js probably v0.12.2
  - io.js [v1.4.2](https://github.com/iojs/io.js/blob/v1.x/CHANGELOG.md#2015-02-28-version-142-rvagg)

**Comment by othiym23** [comment]
No version of Node.js yet, and the first fixed version of npm is `npm@2.6.1`, which is included by io.js 1.4.2. In general, the safest thing to do if you want to use new features in npm is just to run `npm install -g npm` (optionally with `sudo`, if you're on Linux or a non-Homebrew OS X system), so you can get the latest bug fixes.

**Comment by bjackson** [comment]
The [docs](https://docs.npmjs.com/getting-started/updating-global-packages) still recommend using the script, and not running `npm -g update`. Is this still the preferred method?

**Comment by othiym23** [comment]
@bjackson As of `npm@2.6.1`, `npm -g update` is safe to use again. If you want to put together a PR to tweak the docs (docs.npmjs.com uses the markdown from `npm/npm/doc`), I'd be happy to land it (and even if you don't, we'll get around to it, it may just take longer).
