### ISSUE TITLE
Windows-specific changes to installation paths should be disableable

### ISSUE THREAD

**Issue by elieux** [npm/npm#6250]
On Windows, node modules are installed into `$prefix/node_modules`, binaries go to `$prefix` and manpages don't go anywhere. This is okay for ProgramFiles-type installations, but is counter-productive to FHS-inspired packaging projects, such as MSYS2.

It should be possible to switch to the FHS behavior (`$prefix/lib/node_modules`, `$prefix/bin`, `$prefix/share/man`) somehow. That's currently not possible, because npm has hardcoded checks for `process.platform === "win32"`.

(Downstream issue: Alexpux/MINGW-packages#216 - corrected link)

**Comment by othiym23** [comment]
Looking at the conversation on Alexpux/MINGW-packages#216, I think that what you’re doing there is the best way to handle this. In fact, the CLI team has been encouraging the Cygwin team to follow a similar approach. If this were an issue for a larger set of issues, it would perhaps make sense to replace the hardcoded tests for the platform in the code that chooses installation paths with a configuration option, but this issue has been open for close to two years without any further activity. From that, I’m going to deduce that patching this in on the MSYS2 side is indeed the best approach for you and users like you who are using MSYS2, and am going to close this issue. Thanks for your time and patience!
