### ISSUE TITLE
Allow listing of full module names in `npm search` results

### ISSUE THREAD

**Issue by theefer** [npm/npm#6254]
There doesn't seem to be a way to get the full name (not truncated) of modules when running an `npm search`. This would be very useful to pipe results into further shell commands.

The `--long` flag doesn't really help as it wraps text on multiple lines which doesn't make it easy to parse.

Is there a way to pass the `description` configuration value inline to a single command? Maybe that would help. Otherwise, a flag could be passed in to request only the package names, untruncated.

Alternatively, NPM could detect if the output is being piped further and not apply the column truncation.

**Comment by smikes** [comment]
`npm-kludge-search` (which is alpha-testable now, try `npm -g install npm-kludge-search`) supports JSON output, allowing something similar to this feature:

```
$ npm-kludge-search 'pounce' -r json | JSONStream '.description'
["Display images in the console."]
```

Note that I have also globally installed `jsonstream` to get the streaming parser/selector.

The data fed to the `json` reporter is not truncated in any way, so it's suitable for piping and fiddling with.

**Comment by othiym23** [comment]
Assigning this to @zkat because they're literally in the process of fixing the search issue that @iarna mentions (#13746), and because we've changed the internals of the search implementation, we have to reassess the output formatting anyway. Thanks to all for their ongoing patience!

**Comment by zkat** [comment]
Hey, @theefer! #13746 added both TSV (with `--tab-separated` right now) and JSON (with `--json`) output formats for search. The standard column layout will still wrap, but if what you want is to be able to process the data, TSV and JSON should both serve that need nicely.

I’ll be closing this feature request once that PR gets merged in! Hope this helps :)

**Comment by theefer** [comment]
Brilliant @zkat! It's been long enough that I've entirely forgotten why I needed this, but still very happy to see this land. Thanks!
