### ISSUE TITLE
Missing manpages when installing a module globally

### ISSUE THREAD

**Issue by elieux** [npm/npm#6271]
When installing a module globally, manpages should be copied/linked to `$prefix/share/man/` as described in [package.json docs](https://www.npmjs.org/doc/files/package.json.html#man), but are not.

I discovered that the paths specified in the JSON are taken relatively to current working directory, so unless npm is called from the root directory of the module to be installed, `link.js:linkIfExists` stops on `ENOENT`.

Tested with modules jslint v0.6.4 and luamin v0.2.8.

Moreover, if I disable check for Windows in `build.js:linkMans`, it creates broken links. It seems there's a fallback to `junction` in `link.js:link` on Windows, but that feature is intended for directories and creates broken links when used on files. The Windows build I'm using is from MSYS2 project, downstream issue: Alexpux/MINGW-packages#217. I can make a separate ticket for the Windows issue, if needed.

**Comment by mirabilos** [comment]
I just installed npm 3.3.4, and the manpages are missing – in `~/.npm-root/` there is not even a directory `share/`

**Comment by mirabilos** [comment]
Can you please **fix** the issue instead of closing it without comment?
