### ISSUE TITLE
`npm tag` → `npm dist-tag`

### ISSUE THREAD

**Issue by othiym23** [npm/npm#6274]
- [x] add `npm dist-tag` as an alias for `npm tag` (`npm@2.x`)
- [x] deprecate `npm tag`, make it an alias for `npm dist-tag` (`npm@3.x`)
- [x] remove `npm tag` as an alias for `npm dist-tag` (`npm@4.x`)
- [ ] make `npm tag` an alias for `npm ?keyword? ?add?`‽

See also #6243, which will have the correct name from the start.

**Comment by othiym23** [comment]
This indeed seems like a good thing to include as a (small) breaking change in `npm@4`! So labeled and milestoned!

**Comment by iarna** [comment]
Taking this off the v4 milestone as the work for v4 for it has been merged.
