### ISSUE TITLE
binDependencies

### ISSUE THREAD

**Issue by shannonmoeller** [npm/npm#6304]
Would be nice to have the ability to have a list of dependencies that are only needed when a module is installed globally (`commander`, `liftoff`, `nopt`, etc.).

**Comment by iarna** [comment]
While the idea of having dependencies that are only installed when installing associated binaries is intriguing, I can’t think of a scenario where we wouldn’t be installing the binaries. Intra-module dependencies on binaries is a thing, even outside of the use of binaries from devDependencies in the scripts section of the `package.json`. As @othiym23 said earlier, thank you for putting together this write of this use case. As I can’t see anything actionable at this point, I’m going to close this.

**Comment by piranna** [comment]
I think the point here is about dependencies like CLI arguments parsers or terminal colors, that on a good design they would (should?) only be used/depended/downloaded when the module is directly used as a CLI command, not when the module is used as a dependency library.
