### ISSUE TITLE
npm-debug.log should always be written when an error occurs

### ISSUE THREAD

**Issue by dylang** [npm/npm#6350]
### Current situation

Currently the `npm-debug.log` is stored in memory, and then dumped to disk when certain problems occur. 
### Problems
1. Some errors don't cause a log to be generated, such as:
   
   ```
   npm ERR! cb() never called!
   npm ERR! not ok code 0
   ```
2. Sometimes npm just hangs and there's no way to know what it was waiting for.
3. When it fails it only writes out the last 10,000 lines because `npmlog` has a `maxRecordSize` of 10000. If it was streaming to disk this wouldn't be an issue. _Note: I'm not a consumer of the logs so I'm not sure if the full log is necessary._
### Proposed Solutions

Here's some ideas. Any of these might be enough to close this ticket.
1. Fix the logic causing no long to be written with the above example, and auto-write a log file after some amount of time with no output to stdout to have a debug log for hang events.
2. Write to the log file immediately (or asynchronously as long as an error won't prevent the last bits from being written.) On success unlink the log file.
3. Introduce an option to force log file to be written no matter what. 
## 

Semi-related issue: #5214 `npm report`

**Comment by jsdevel** [comment]
It would be really nice if the creation of `npm-debug.log` could be entirely disabled in `~/.npmrc`.

**Comment by mike-spainhower** [comment]
@maxogden @jsdevel Feel free to move off-topic discussion to https://github.com/npm/npm/issues/7648 :grin:

**Comment by othiym23** [comment]
This has been moved to the [npm roadmap](https://github.com/npm/npm/wiki/Roadmap), which we're using instead of the confusing `next-*` labels now.

**Comment by othiym23** [comment]
Whoopsie, didn't mean to actually close this!

**Comment by legodude17** [comment]
I would suggest that npm always writes to log. Then deletes it if there was no error and no --always-write or there was a --never-write. Maybe the log could start as a tmp file and then get moved to the dir if needed.

**Comment by othiym23** [comment]
We’ve finally returned to this issue after some time, and there are a number of related issues devoted to dealing with the issue of _always_ getting debugging logs, and putting them in a more convenient place. See also:

- #1548
- #1584
- #5252
- #6181
- #6744
- #6766
- #7041
- #7614
- #7648
- #11439

That’s a lot of issues for something that seems both pretty important to get right, from a debugging and supportability point of view, as well as seemingly pretty simple. However, there are a number of competing requirements, many of which became clear during the epic debugging festival that led to this issue being filed in the first place:

- `npm-debug.log` can get quite large, even with the limit to 10,000 entries.
- Writing the logs to disk as they come can incur significant I/O overhead if not done carefully.
- Were we to prune the number of npm debug logs saved, determining whether the number of logs saved exceeds some reasonable amount of disk space could also be time-consuming.
- We want a location that we can guarantee is writable (i.e. npm’s cache folder, as discussed in a number of the issues linked above).

When discussing this today, we came up with a few ways to get around these restrictions:

1. Prune the saved logs directory at npm _startup_, not _completion_.
2. Asynchronously stream the logs to disk (with a relatively high highwater mark) – this reduces the need to install special signal-handling logic in the case of unexpected exit, and should minimize the amount of I/O overhead incurred. It increases the possibility that some chunks of log data wouldn’t be written in the case of process crash, but the most likely cause of a Node crash is out of memory errors, in which case that error probably trumps whatever’s in the logs, or at any rate there should be enough info in what does get logged to figure out roughly what caused memory usage to balloon when it isn’t simple environmental constraints.
3. Use Node’s inbuilt zlib compression to stream the logs in a compressed format. This increases CPU overhead for logging, but in return should yield a _substantial_ space savings on disk, making streaming _all_ install logs a lot safer.

This is something we’ve been trying to make happen for _years_ now, but in the medium term we’re going to want to redo the entire user experience around how diagnostic information gets presented to end users, and this could be part of that work. _Orrrrrrrrrrrr_ an enterprising and helpful community member could put a patch together to do this, and earn the gratitude of the entire npm user and developer community. :tada:
