### ISSUE TITLE
--save adds everything to package.json when configured in .npmrc

### ISSUE THREAD

**Issue by wavded** [npm/npm#6391]
I have `save: true` in my `.npmrc`.  I like that.  It usually does what I want to except when I run `npm install` in a directory with `package.json` file.  There it takes all the packages specified in other dependencies (e.g. `devDependencies`) and adds them to my `dependencies`.  I'm not sure if this is a bug, but I was expecting `npm install` to purely obey the `package.json` in this case.

Thoughts?

**Comment by othiym23** [comment]
This is actually fixed in `npm@3`, so I'll let @iarna close this out with an explanation of what's changed.

**Comment by wavded** [comment]
Excellent!
