### ISSUE TITLE
[2.1.3, master] after successful install, npm ls reports an extraneous package

### ISSUE THREAD

**Issue by dylang** [npm/npm#6436]
* We got rid of our `peerDeps`.
* We added a cache header to our server.
* We are still in the process of reducing the number of packages installed. It's still around 3000.

`npm install` returns no errors or warnings with regards to peerDeps or the package in question.

`npm ls` returns an `ERR` like:

```
npm ERR! extraneous: browserify@3.46.1 /mnt2/workspace/x-web/DYLAN-test-generator/t/generator-x-web/node_modules/x-web-taskmaster/node_modules/browserify
```

`silly` log and `npm ls` output: https://gist.github.com/dylang/f30cbb86fdefbc1736b2

**Comment by iarna** [comment]
Closing this as peer deps aren't a thing that causes any actions as of [npm/npm#multi-stage](https://github.com/npm/npm/tree/multi-stage)

**Comment by avengerpenguin** [comment]
I'm getting this same issue in npm v2.14.10. Did anyone find out what it was?

**Comment by imyejin** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

dufma555@naver.com 님께 보내신 메일 <Re: [npm] [2.1.3, master] after successful install, npm ls reports an extraneous package (#6436)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------
