### ISSUE TITLE
npm config ls -l omits per-project config settings

### ISSUE THREAD

**Issue by rwales** [npm/npm#6481]
The `cache-min` setting has been defined in a per-user config file and a per-project config file, as follows:

	~/node_project$ cat ~/.npmrc | grep cache-min
	cache-min=10000000
	~/node_project$ cat .npmrc | grep cache-min
	cache-min=20000000

When I list configuration, the per-project settings are omitted. Although node informs me that the lower-priority `cache-min` settings have been overridden (good), it doesn't tell me what the actual value of `cache-min` is (bad).

	~/node_project$ npm config ls -l
	...
	; userconfig /home/rwales/.npmrc
	; cache-min = 10000000 (overridden)
	...
	; default values
	...
	; cache-min = 10 (overridden)

The only way to determine the actual value of the new setting is to `get` it explicitly:

	~/node_project$ npm config get cache-min
	20000000

I really think `npm config ls -l` should list configuration settings from all sources.

**Comment by othiym23** [comment]
Fixed by #11475 (filed in #11472). My apologies for not noting that this had been shiped! Thanks for your time and patience!
