### ISSUE TITLE
Missing modules when re-installing scoped modules

### ISSUE THREAD

**Issue by bcoe** [npm/npm#6491]
I've been able to cause the following behavior when re-installing scoped modules:

https://gist.github.com/bcoe/f9e04c3fa067d0bbb430

## Steps to create

1. `rm -rf ./node_modules/@npm/validate-and-store`.
2. `npm install`.

Alternatively, 

1. edit package.json, bump the version of `validate-and-store`.
2. `npm install`.

## Observed Behavior:

various modules are missing (see [npm-debug.log](https://gist.github.com/bcoe/f9e04c3fa067d0bbb430)).

## Expected Behavior

All dependencies are present

**Comment by iarna** [comment]
Hey, this _should_ be fixed by npm@3... would love it if you could give this a try again and see if it's resolved. (But I'll be circling back to see if I can reproduce this myself just the same.)

**Comment by bcoe** [comment]
I've been using `npm@3.x` as my main development npm for quite some time now. I have not run into any issues with scoped modules.
