### ISSUE TITLE
npm uninstall on windows just hanging, with no output

### ISSUE THREAD

**Issue by sam-github** [npm/npm#6502]
Reported problem was that strongloop couldn't be installed on Windows, after some troubleshooting, it appears that the install is hanging at the uninstall step. I asked them to do just the uninstall, and send me the output, this is what they see:

```
$ npm --loglevel=silly uninstall -g strongloop
npm info it worked if it ends with ok
npm verb cli [ 'c:\\Program Files\\nodejs\\node.exe',
npm verb cli 'c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli '--loglevel=silly',
npm verb cli 'uninstall',
npm verb cli '-g',npm verb cli 'strongloop' ]
npm info using npm@1.4.28
npm info using node@v0.10.32
npm verb node_modules\strongloop unbuild
```

At this point, nothing happens. I asked for how long nothing happened, user said "24H, only aborted today".

I'm at a loss as to what to request next (I'm asking for the npm-debug.log, but I'm not sure there will be one).

**Comment by smikes** [comment]
It sounds like this problem has been fixed! 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
I'm going to close this one as resolved, but I'm sure @sam-github will let me know if he sees this again.
