### ISSUE TITLE
peerDependencies raise EPEERINVALID for git packages 

### ISSUE THREAD

**Issue by appsforartists** [npm/npm#6504]
I have an application that depends both on a fork of `react-router` and on a library I'm developing.  Here are `package.json` snippets from each:

``` json
{
  "name": "SampleApp",
  "dependencies": {
    "Ambidex": "git+ssh://…/Ambidex",
    "react-router": "git+https://github.com/appsforartists/react-router",
  },
}
```

``` json
{
  "name": "Ambidex",
  "peerDependencies": {
    "react-router": "git+https://github.com/appsforartists/react-router",
    "react-tap-event-plugin": "0.1",
    "react": "0.11"
  },
}
```

`npm install`ing the application eventually yields:

```
npm ERR! peerinvalid The package react-router does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer Ambidex@0.0.0 wants react-router@git+https://github.com/appsforartists/react-router
```

As you can see, the references in each `package.json` are identical.  I've also tried changing them to:
- `git+https://github.com/appsforartists/react-router#master`
- `git+https://github.com/appsforartists/react-router#0.9.1`
- `git+https://github.com/appsforartists/react-router#68409a0cebf103ec937e670665cddf1bc77c2bd8`

None of these work.  Do peer dependencies work with git URLs?

I want the dependency to resolve to HEAD on that git link.  If I was ready for versioning, this would be a public package on `npm`.  I'm not, so HEAD is appropriate.

**Comment by ownagedj** [comment]
+1

**Comment by fxalgrain** [comment]
+1
