### ISSUE TITLE
compiled dependencies don't always compile because of peerDependencies

### ISSUE THREAD

**Issue by jkamke** [npm/npm#6533]
in new directory and the following package.json. 
npm install leaves crypt uncompiled, no warnings or errors:

```
{
  "dependencies": {
    "chai-as-promised":"4.1.1",
    "bcrypt": "0.7.5"
  }
}
```

But for some reason this works:

```
{
  "dependencies": {
    "chai-as-promised":"4.1.1",
    "chai":"1.9.x",
    "bcrypt": "0.7.5"
  }
}
```

And even stranger is that this works (bson's install script is different):

```
{
  "dependencies": {
    "chai-as-promised":"4.1.1",
    "bson":"0.2.8"
  }
}
```

npm --version
1.4.28

**Comment by rk08** [comment]
I have a react app, in which folder name is sports, inside the sports folder I have node modules, inside the node modules folder I have football folder and react folder.
If go to football folder and do npm install react its installing react, which makes my application fail, how to prevent this command npm install react from being successful.
Is it anyway we can right a script to prevent this process to happen, but it should work when we do npm install react in sports folder. Is there any already npm packages which we use it make automatically validated our npm commands.
