### ISSUE TITLE
Validate shrinkwrap file against installed dependencies

### ISSUE THREAD

**Issue by nzakas** [npm/npm#6605]
I'd like to suggest a way to validate shrinkwrap files against installed dependencies. Here's what I'm trying to do:

I'm working on a large project that uses shrinkwrap to lock down version numbers. As such, we ask everyone to run `npm shrinkwrap` whenever they update a dependency. Naturally, some people forget to do that, and since we check in our dependencies, the contents of `node_modules` becomes out of date with the shrinkwrap file.

What I'd love to do is have a `npm shrinkwrap validate` command that I could run as part of our automation that could catch these discrepancies automatically and would return a non-zero exit code if the file was out of date.

**Comment by othiym23** [comment]
The CLI team just discussed the need to be able to validate

1. `npm-shrinkwrap.json` against what’s in `package.json`, to ensure that when users add or update dependencies to a package, the lockfile stays in sync.
2. `package.json` against what’s in `node_modules/`, to ensure that when users pull down new versions of `package.json` and `npm-shrinkwrap.json` from Git, tooling can detect that the two are out of sync without running an install.

These are both important parts of lifecycle management! The team wants to see this functionality implemented in the CLI!

At the same time, the story is improved somewhat by the fact that `npm install --save` will update `npm-shrinkwrap.json` under `npm@3`, and we intend to add more affordances like this going forward. That doesn’t mitigate the need for something like `npm shrinkwrap validate`, just provides a little evidence of where we’re headed as we try to make lockfiles a more integral part of the package management lifecycle.

In all likelihood, we’re going to be spending a good chunk of the next six months identifying ways in which we can improve shrinkwrap (it’s tentatively the purpose of `npm@5`, which we’d like to ship some time next year). I think the conversation on this issue defines the functionality closely enough that if somebody wanted to submit it as a patch, it would be feasible for an outside contributor to understand the relevant code well enough to build, and it should be relatively easy to review and land. If that doesn’t happen, though, the CLI team still intends to see this functionality land. Thanks for your time!
