### ISSUE TITLE
Installing dependencies from cache fails

### ISSUE THREAD

**Issue by nevir** [npm/npm#6624]
Not sure exactly what's going on here, but it looks like there's some sort of race within the caching mechanism. This occurs on npm `1.4` and `2.1` (and likely other versions in between?)

To repro, `npm install web-component-tester` several times. It will randomly fail when trying to run the install script for `sauce-connect-launcher`. It always fails when trying to require `lodash.js` from within that script. It appears that `lodash.js` is corrupt at require time (didn't finish copying/extracting?)

If you `npm cache clear` before installing the package, it installs every time.

output for npm 2.1.6: https://gist.github.com/nevir/c78f852adf42c439d39b
Also see https://github.com/Polymer/web-component-tester/issues/58 for output from npm 1.4.28

**Comment by iarna** [comment]
The repro in https://github.com/azakus/depends-on-bug.git is fixed in [npm/npm#multi-stage](https://github.com/npm/npm/tree/multi-stage) so I'm closing this.
