### ISSUE TITLE
Install scripts do not run for scoped packages during global installation

### ISSUE THREAD

**Issue by limulus** [npm/npm#6653]
I've confirmed this bug exists in npm@next (v2.1.8). A scoped module containing an install script (or more typically, a Node add-on with a binding.gyp), will fail to run the install script and instead emit a warning when being globally installed. For example, take a package with the following package.json:

```json
{
  "name": "@myorg/hello",
  "version": "1.0.0",
  "scripts": {
    "install": "echo hello"
  }
}
```

When `sudo npm install -g` is run on this package the following warning will be printed:

```
npm WARN cannot run in wd @myorg/hello@1.0.0 echo hello (wd=/usr/local/lib/node_modules/@myorg/hello)
```

And while npm will exit with an exit code of `0` (#4276, #5287), the install script never actually ran (`hello` was not echoed to the console).

Looking at npm's code, it seems that in `lib/util/lifecycle.js`, the check that produces this warning and short-circuits the `lifecycle` function is comparing `path.basename(wd)` (which will be `hello`) with `pkg.name` (which will be `@myorg/hello`). That seems to be the core of the bug, but it's not clear to me what the best way to fix it is.

**Comment by othiym23** [comment]
This issue got fixed sometime in the last 364 days (:wink:), so if you haven't already, upgrade to a new version of `npm@2` or `npm@3` (@iarna has tested that both support this now). Thanks for your patience, and I apologize for our tardiness in dealing with this.

**Comment by limulus** [comment]
Confirmed that this has indeed been fixed in `npm@2` and `npm@3`. Thanks much, @iarna and @othiym23. You all rock!
