### ISSUE TITLE
Request: allow npm install to accept path to json file describing dependencies

### ISSUE THREAD

**Issue by devinivy** [npm/npm#6661]
It would be very useful if `npm install` accepted a path to a file that included json formatted the same as package.json's `dependencies` value.  My use-case is to programmatically configure a list of global packages on, say, a new box.  I haven't found a good solution to arbitrarily translate
`{"package-name": "version/uri"}` (a la package.json) into something like `npm install package-name@version`.

**Comment by othiym23** [comment]
The CLI team is triaging our feature requests, and have decided to close this issue. This sounds like something that would be useful as an external utility, but isn't something that makes sense for npm itself. Thanks for your time and the discussion!
