### ISSUE TITLE
ENOENT, open '/var/lib/couchdb/package.json'

### ISSUE THREAD

**Issue by RameshMuthuraj** [npm/npm#6687]
cat npm-debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/bin/npm', 'start' ]
2 info using npm@1.3.6
3 info using node@v0.10.30
4 verbose node symlink /usr/local/bin/node
5 error Error: ENOENT, open '/var/lib/couchdb/package.json'
6 error If you need help, you may report this log at:
6 error     <http://github.com/isaacs/npm/issues>
6 error or email it to:
6 error     <npm-@googlegroups.com>
7 error System Linux 2.6.32-358.14.1.el6.x86_64
8 error command "node" "/usr/bin/npm" "start"
9 error cwd /var/lib/couchdb
10 error node -v v0.10.30
11 error npm -v 1.3.6
12 error path /var/lib/couchdb/package.json
13 error code ENOENT
14 error errno 34
15 verbose exit [ 34, true ]


curl -X PUT http://localhost:5984/registry
{"error":"unauthorized","reason":"You are not a server admin."}
```

getting this log error ..could you please help me ?

**Comment by smikes** [comment]
Is this still a problem for you?

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by RameshMuthuraj** [comment]
I dont have any pblm with this..please close this ticket

On Wed, Feb 4, 2015 at 2:00 AM, Sam Mikes <notifications@github.com> wrote:

> Is this still a problem for you?
>
> We are trying to clean up older npm issues, so if we don't hear back from
> you within a week, we will close this issue. (Don't worry -- you can always
> come back again and open a new issue!)
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/npm/npm/issues/6687#issuecomment-72728218>.
>



-- 
Thanks,
Ramesh Muthuraj
+91 9865127748

**Comment by othiym23** [comment]
Closing as resolved.
