### ISSUE TITLE
npm version --no-git

### ISSUE THREAD

**Issue by bevacqua** [npm/npm#6711]
I repeatedly find myself wanting to do things with the new version number before creating a tag, it would be nice if there was an option where `npm version` didn't automatically mingle with `git`.

**Comment by othiym23** [comment]
This was fixed in 2ef5771632006e6cee8cf17f836c0f98ab494bd1*and* ebe3b37098efdada41dcc4c52a291e29296ea242, so it is now, like, hella documented. Thanks for filing this!

**Comment by ORESoftware** [comment]
This apparently will do things globally:

`npm config set git-tag-version=false`

how can I turn off tags for just the local NPM project, not globally?
Is there a setting I can put in `.npmrc`?

**Comment by bevacqua** [comment]
`npm version --no-git-tag-version`

**Comment by ORESoftware** [comment]
@bevacqua thanks, any idea if that can go in `.npmrc` as a setting?

**Comment by kenany** [comment]
You can put `git-tag-version=false` in any `.npmrc`, be it local or global :+1:

**Comment by ORESoftware** [comment]
@KenanY  thanks is that documented anywhere?

**Comment by kenany** [comment]
@ORESoftware The beginning of <https://docs.npmjs.com/misc/config> covers the various places wherein config values can be specified.
