### ISSUE TITLE
HOEDOWN TIME

### ISSUE THREAD

**Issue by othiym23** [npm/npm#6715]
![hoedown_dillo_coloring_page](https://cloud.githubusercontent.com/assets/418097/5055972/a5ca4df0-6c22-11e4-9acb-0e80b5a760c1.gif)

The npm CLI team has been doing many things! We have [a road map](http://blog.npmjs.org/post/91303926460/npm-cli-roadmap-a-periodic-update)! We have a [release process](https://github.com/npm/npm/wiki/Release-Process)! We've [sorted](https://github.com/npm/npm/labels/bug) [our](https://github.com/npm/npm/labels/feature-request) [issues](https://github.com/npm/npm/labels/support) and [prioritized](https://github.com/npm/npm/labels/next-patch) [upcoming](https://github.com/npm/npm/labels/next-minor) [work](https://github.com/npm/npm/labels/next-major)!

But a lot of this stuff is being done in the context of npm, Inc., and it's not always clear to you, the fine users of npm, what exactly our plans – strategic or tactical – are. And we're not exactly sure what your biggest needs and pain points are. So I want us to try another experiment: have some kind of discussion in realtime where we can all go over where the npm CLI is and where it's headed and make sure that makes sense for all of you.

This issue is a placeholder. We need to figure out these things before this meeting should occur:

- [ ] when to have it (after American Thanksgiving but before the end of the year, is my suggestion)
- [ ] how to hold it (Skype? Hangout? IRC? Slack?)
- [ ] who wants to participate (all are welcome)
- [ ] what we're going to talk about (I have ideas, but I want to hear what other people want to discuss before laying out an agenda)

Let's do this! Answers to the above, topics to discuss, etc below.

/cc @iarna @timoxley @domenic @terinjokes @smikes @dylang @fishrock123 @faiq @Dudemullet

**Comment by smikes** [comment]
I suspect this got sorted into the "when I have time to think" pile.

How about Thursday, March 5th, at 2PM Pacific time, via Hangouts (+ IRC)?

**Comment by iarna** [comment]
This didn't actually happen, afaik! BUT, we do have https://github.com/npm/npm/wiki/Roadmap now, which is pretty keen. I'm gonna close this and if we want to try something like this again in the future we'll start anew.
