### ISSUE TITLE
npm modules should auto-install when missing from app

### ISSUE THREAD

**Issue by kevinSuttle** [npm/npm#6723]
Scenario:

1. Clone repo of Node.js app
2. Open and `cd` to directory in terminal
3. Out of muscle memory, type `node app.js` or `npm start`

**Expected result**
npm either installs required modules automatically based on global config, *then* runs the app

OR

npm asks if I would like to download the required dependencies. 
I opt for the first scenario. Either way, an .npmrc should respect this. 

**Actual result**
`Error: Cannot find module [x]`

**Comment by IAMtheIAM** [comment]
+1 for auto restore and auto ignore existing packages.

**Comment by iarna** [comment]
I’ve looked at this again now nearly two years later and I am still of the opinion that this would be best written as an external tool. As the CLI team won’t be implementing this as an npm feature, I’m going to close this issue.
