### ISSUE TITLE
npm update --dev is not documented

### ISSUE THREAD

**Issue by mohsen1** [npm/npm#6745]
I just assumed `--dev` will update `devDependencies` and it worked. But [here](https://www.npmjs.org/doc/cli/npm-update.html) `--dev` is not mentioned

**Comment by smikes** [comment]
PR #7066 is a candidate fix for this documentation bug.  Thanks for reporting it.

**Comment by othiym23** [comment]
Fixed in 560c00945d4dec926cd29193e336f137c7f3f951. Thanks for pointing this out!
