### ISSUE TITLE
`npm init` and scoped package names

### ISSUE THREAD

**Issue by zeke** [npm/npm#6749]
Because directory names cannot contain slashes, `npm init` will never default to an npm-2-style scoped package name:

```sh
» mkdir -p @zeke/some-package
» cd @zeke/some-package 
» npm init
This utility blah blah...
name: (some-package) 
```

It might be cool if `npm init` suggested `@zeke/somepackage`, but probably not. Plus who's gonna create a directory name starting with an `@`? No one, that's who.

Or what about a flag or npm-config setting, like `npm init --scope=@zeke`?

Bah. Feel free to close this issue upon reading.

**Comment by watilde** [comment]
I like this idea `npm init --scope=@zeke` +1.

**Comment by othiym23** [comment]
Good, idea, Zeke! @watilde made it a reality for you, and I've landed it in npm! 🐜🌸

**Comment by zeke** [comment]
🌴
