### ISSUE TITLE
Option to always create .cmd shims for Windows, even when installing on Unix

### ISSUE THREAD

**Issue by plestik** [npm/npm#6758]
Hi,

I have a WIndows host - Unix guest setup. `npm install` is run on the Unix guest, which means no .cmd shims are created. But, I prefer to run `gulp` on my Windows host, which isn't possible without .cmd wrappers. Is it possible to force the creation of the cmd shims? Alternatively, is there a module for this purpose?

Perhaps expanding `bin-links` with `'both'` as an option (in addition to `true` and `false`?

**Comment by othiym23** [comment]
Another way to get the same effect when moving between platforms is to run `npm rebuild` before running gulp. On Windows, it will create the `.cmd` shims, and on all other platforms, it will take care of (re)generating the necessary symbolic links to get the paths set up correctly to use binaries from package scripts. In fact, that’s close enough of a best practice that I’m going to close this feature request. If that’s not sufficient for your use case, open an issue or let the CLI team know what other requirements you have so we can talk it through. Thanks for your time!

**Comment by buffcode** [comment]
`npm rebuild` will also try to rebuild dependencies (in our case a C# library/adapter), which won't be possible on production machines.
In a perfect world we can create a dist-package on our linux CI enviroment (including the shim files) and just copy it to a Windows production-environment for use.
