### ISSUE TITLE
env variable NODE_ENV=production effect on npm install is undocumented

### ISSUE THREAD

**Issue by stefaneg** [npm/npm#6803]
Setting environment variable NODE_ENV to "production" causes npm install to ignore dev dependencies. This is not an issue per se, the issue is that this is a obscure feature which can be hard to realize is causing problems.

I just spent a few hours chasing down why on earth devDependencies were being installed in one project, but not another. It took a while to chase the cause to that NODE_ENV was set to production in one terminal window, but not the other. Realized this only after making the two project more or less binary identical :-(

For me this was completely unexpected, a package manager should be reading the package file and nothing else, for package managers, consistency and repeatability is king. Since this is the behavior, it should be spitting out a big warning that it is in production mode an will ignore devDependencies.

At least, this behavior should be documented [here](https://www.npmjs.org/doc/cli/npm-install.html)

**Comment by admosity** [comment]
Is there a way to install the devDependencies while the NODE_ENV environment variable is set to production?

**Comment by smikes** [comment]
To install dev dependencies, `npm --production=false install` will work even with `NODE_ENV=production`.

Or you can run `NODE_ENV=development npm install`

**Comment by admosity** [comment]
Thanks! Wanted to throw it into a heroku buildpack.

**Comment by othiym23** [comment]
@stefaneg and I landed a small note to this effect in 95e59b287c9517780318e145371a859e8ebb2d20. Closing!

**Comment by xgqfrms-GitHub** [comment]
What's wrong with this ?
> Windows Powershell

```sh
PS H:\www\Third-Part> SET NODE_ENV=development
PS H:\www\Third-Part> node app.js
undefined
PS H:\www\Third-Part>
```

**Comment by KenanY** [comment]
@xgqfrms-GitHub I think what you want is <https://technet.microsoft.com/en-us/library/ff730964.aspx>. If you need any more help with Powershell, I suggest asking somewhere else, like on StackOveflow :)

**Comment by davidfurlong** [comment]
> To install dev dependencies, npm --production=false install will work even with NODE_ENV=production.
> 
> Or you can run NODE_ENV=development npm install

Dear god this needs to be documented.
