### ISSUE TITLE
npm info @org should err instead of ignoring @org

### ISSUE THREAD

**Issue by dylang** [npm/npm#6804]
`npm info` is for getting info for package names, not orgs. 

If a user doesn't know this and types:

```
npm info @someorgname
```

It will ignore `@someorgname` and give `npm info` for the package in the current working directory. 
If the current working directory is not a package then `npm` returns an error, but the error doesn't mention the bad input.

```
npm ERR! Invalid package.json`
```

Recommendation:

Something like:

```
npm ERR! @someorgname is not a valid package name.
```

This might be trivially stupid and not worth fixing. I won't be offended if that's the decision. :smile:

**Comment by othiym23** [comment]
This has been moved to the [npm roadmap](https://github.com/npm/npm/wiki/Roadmap), which we're using instead of the confusing `next-*` labels now.
