### ISSUE TITLE
%2f instead of / in error message: npm ERR! Request was not authorized : @org%2fpackagename

### ISSUE THREAD

**Issue by dylang** [npm/npm#6805]
#### Repro
Try install something you don't have access to:

```
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "@opowerinc/jira-improved"
npm ERR! node v0.10.33
npm ERR! npm  v2.1.10
npm ERR! code E401

npm ERR! Request was not authorized : @opowerinc%2fjira-improved
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>
```

#### Expected
```
npm ERR! Request was not authorized: @opowerinc/jira-improved
```

**Comment by ayhankuru** [comment]
npm publish same error 

```sh
33 verbose stack Error: Request was not authorized : ytclear
33 verbose stack     at CachingRegistryClient.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:254:14)
33 verbose stack     at Request._callback (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:178:14)
33 verbose stack     at Request.self.callback (/usr/lib/node_modules/npm/node_modules/request/request.js:344:22)
33 verbose stack     at emitTwo (events.js:87:13)
33 verbose stack     at Request.emit (events.js:169:7)
33 verbose stack     at Request.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:1239:14)
33 verbose stack     at emitOne (events.js:82:20)
33 verbose stack     at Request.emit (events.js:166:7)
33 verbose stack     at IncomingMessage.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:1187:12)
33 verbose stack     at emitNone (events.js:72:20)
```

**Comment by KenanY** [comment]
@ayhankuru Your issue appears to be different. @dylang's issue is with the `/` being turned into a `%2f` in the scope. That is, this is a cosmetic issue while yours is an authorization error. Could you open a new issue instead?

**Comment by ayhankuru** [comment]
@KenanY sorry, that's  right

**Comment by othiym23** [comment]
Good news! This is fixed in `npm-registry-client@6.3.3`, which was landed as faf65a7bbb2fad13216f64ed8f1243bafe743f97!

**Comment by KenanY** [comment]
@othiym23 I think you mean as https://github.com/npm/npm/commit/4979af3fcae5a3962383b7fdad3162381e62eefe :see_no_evil:

**Comment by hktalent** [comment]
$npm list -g 

npm ERR! invalid: npmlog@4.0.2 /usr/local/lib/node_modules/npm-registry-client/node_modules/npmlog
npm ERR! extraneous: are-we-there-yet@1.1.2 /usr/local/lib/node_modules/npm-registry-client/node_modules/are-we-there-yet
npm ERR! extraneous: console-control-strings@1.1.0 /usr/local/lib/node_modules/npm-registry-client/node_modules/console-control-strings
npm ERR! extraneous: gauge@2.7.2 /usr/local/lib/node_modules/npm-registry-client/node_modules/gauge
npm ERR! extraneous: set-blocking@2.0.0 /usr/local/lib/node_modules/npm-registry-client/node_modules/set-blocking
npm ERR! extraneous: npmlog@1.2.1 /usr/local/lib/node_modules/requiresafe/node_modules/npmlog
npm ERR! missing: npmlog@, required by npm-registry-client@6.3.3

**Comment by hktalent** [comment]
$ npm -v
4.1.2
