### ISSUE TITLE
npm ERR! Could not get cache stat on npm install

### ISSUE THREAD

**Issue by allthetime** [npm/npm#6811]
I am running node and npm, installed with nvm inside a Docker container to run tests. NPM install is being run by a non-root user who has its own node installation. For some reason I have to call node like this... /home/user/.nvm/v0.10.33/bin/node and npm like /home/user/.nvm/v0.10.33/bin/npm... This caused problems and gave me a "/usr/bin/env" "node" does not exist, so I symlinked /home/user/.nvm/v0.10.33/bin/node to /usr/bin/node and things started rolling again. But now I'm getting this strange error.

I searched this error and apparently no one has ever seen it before.

`npm ERR! Could not get cache stat`

Here is the full stack...
```
npm ERR! Could not get cache stat
npm ERR! Could not get cache stat
npm ERR! Linux 3.16.4-tinycore64
npm ERR! argv "node" "/home/jenkins/.nvm/v0.10.33/bin/npm" "install"
npm ERR! node v0.10.33
npm ERR! npm  v2.1.10
npm ERR! path /home/jenkins/.npm/_git-remotes/<<address_to_private_repo>>/objects/pack/tmp_pack_GKEEeR
npm ERR! code ENOENT
npm ERR! errno 34

npm ERR! enoent ENOENT, chown '/home/jenkins/.npm/_git-remotes/<<address_to_private_repo>>/objects/pack/tmp_pack_GKEEeR'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jenkins/schools.vidigami.com/npm-debug.log
```

**Comment by smikes** [comment]
Is this still a problem for you?

Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

For some Linux distributions (Debian/Ubuntu and RedHat/CentOS), the latest node version provided by the distribution may lag behind the stable version. [Here are instructions from NodeSource](https://github.com/nodesource/distributions) on getting the latest node.

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as abandoned.
