### ISSUE TITLE
Validate CLI parameters

### ISSUE THREAD

**Issue by dandv** [npm/npm#6812]
`npm install --savedev grunt-shell`

Then I pull my hair off for a while until I realize it's `save` DASH `dev`.

**Comment by Delapouite** [comment]
This issue will be resolved there : https://github.com/npm/npm/issues/10047

**Comment by othiym23** [comment]
Closing as duplicate of #10047; as that issue indicates, this is something we'd like to fix, but the CLI team isn't going to have time to address soon. Patches welcome! Thanks for your time!
