### ISSUE TITLE
Add triggered execution for npm tasks 

### ISSUE THREAD

**Issue by earldouglas** [npm/npm#6830]
During development, I find it useful to have `npm test` run every time I make a change to a source file.  Currently, I achieve this using bash and inotifywait:

```bash
function fswatch() { 
  while [ TRUE ]
  do
    $@
    inotifywait --exclude '\.git/.*' -e modify -e close_write -e moved_to \
                -e moved_from -e move -e move_self -e create -e delete    \
                -e delete_self -e unmount -qqr .
  done
}
```

```
$ cd myproject
$ fswatch npm test
```

Would it be feasible to add a special prefix (e.g. `~`) that would apply this behavior to any npm command?  It could be used thus:

```
$ npm ~test
```

**Comment by othiym23** [comment]
As my previous comment indicates, this isn't something that really makes sense to include in npm itself, and as such I'm going to close this feature request. There are a _lot_ of great build tools that you can _control_ via npm package scripts, but it's not in anybody's interests to make the CLI prohibitively complex by trying to make it compete with chokidar, gulp, yeoman, and the like. Thanks for your time and the discussion!
