### ISSUE TITLE
Wrong tag get the package published anyway

### ISSUE THREAD

**Issue by mcollina** [npm/npm#6837]
In the update between 1.x to 2.x the behavior of `--tag` changed, and now it does not support semver ranges anymore. However, if somebody did not know (like myself 15 minutes ago), and you use tag in the wrong way, then you end up publishing your module anyway. I think this warning should be made an error and stops 

```
$ npm publish . --tag=0.11.0-pre.1
npm WARN invalid config tag="0.11.0-pre.1"
npm WARN invalid config Tag must not be a SemVer range
+ nscale@0.11.0-pre.1
```

I kind-of agree about this change, but I would like to read the details about it, is there a pull request or an issue that discuss why it was needed?

**Comment by smikes** [comment]
/cc @othiym23 There is a feature request here:

"npm WARN invalid config Tag must not be a SemVer range" 

should be an error, not a WARN

**Comment by othiym23** [comment]
@smikes filed as #7075. @mcollina, I'm going to close this issue for now, because I think @KenanY answered the question that led to it being filed, but we do have #7075 in the queue to help keep this from biting other developers (and maybe you!) in the future.

**Comment by mcollina** [comment]
Yes, perfect.
