### ISSUE TITLE
tag workflow

### ISSUE THREAD

**Issue by mcollina** [npm/npm#6846]
I do not understand the tag workflow anymore :(, it might be a documentation problem or an actual issue.

So, in order to deploy tag '0.11.pre2' I need to run the command:
```
npm publish . --tag=0.11.pre2
```

However, I cannot put '0.11.pre2' on the `version` property, so that I have to put '0.11.0-pre2'.

So, how should I do it?

**Comment by smikes** [comment]
Is this issue now resolved?  Or is there a feature request here for a `--no-latest` flag to `npm publish` ?

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will dither some more about this issue.

Thanks!

**Comment by mcollina** [comment]
Yes it is, but it was not clear if this was something you folks might want in or not, so I did not close the issue. The support was amazing and it fixed my immediate problem, thanks!

**Comment by smikes** [comment]
It sounds like you do think there should be a `--no-latest` flag as well as the change now moved to #7075 .

/cc @othiym23 for feature request

/bikeshed ON

`--no-foo` flags are an anti-pattern, how can we frame this as a positive option, when the default is to do a thing (apply tag `config.get('tag')`) and this option is to avoid doing it?

**Comment by smikes** [comment]
`--prerelease` doesn't capture all the places that it's needed.  In your workflow you're using `--no-latest` for a pre-release tag, but someone else might be maintaining both `2.0` and `3.0` versions; when they push `2.0.15` they don't want `latest` to move, but it's not a pre-release.

`--no-latest` is a perfect name except for being negative. :crying_cat_face:

**Comment by othiym23** [comment]
Every package must have a version tagged `latest` or all kinds of things fail, both in the registry or the client. If there were going to be a way to support publishing without a tag, it would need to handle the case of an initial publish of a new package.

In practice, what I do is publish to a tag like `testing` or `prerelease` when I don't want to update `latest`. Is that not sufficient? There's a middling case here for publishing without a tag, but it brings with it some signficant complexity, and I don't want to add it unless it's necessary.

**Comment by mcollina** [comment]
I now understand better the tag process, and how it is used internally by NPM itself. It sounds tricky to correctly support this use case in a backward-compatible way (mainly for the registry). I would live this on hold for now, and just get #7075 #7099 #7144 fixed.

**Comment by othiym23** [comment]
All three of those are closed by 4ef1412d0061239da2b1c4460ed6db37cc9ded27, so I'm going to call this resolved as well. If you run into weirdness with how the new version of the tag workflow works, please open new issues so we can keep the discussion from getting confused. Thanks! I hope this is what you were looking for!

**Comment by mcollina** [comment]
Yes, thank so much @smikes!
