### ISSUE TITLE
Improve the -rc experience

### ISSUE THREAD

**Issue by hueniverse** [npm/npm#6848]
The current experience of publishing hapi 8.0.0-rc versions along with rc versions of plugins and deps has been pretty painful. The changes in npm 2.0 made it worse.

I am not sure how to fix it, but at a minimum, the latest tag should not be moved from a non -rc to -rc release. Constantly moving the tag back is annoying.

It would be good to maybe have a way to opt into installing rc versions somehow when x.x.x is specified.

**Comment by iarna** [comment]
Thank you everyone here for this discussion, it's been very useful.

The prerelease workflow is very awkward, especially with the `npm` version 2 changes to semver range matching. This request is related to #6778 which asks to not downgrade `latest` unless you specifically ask for it. I think the solution here is similar: If the version to be published is a prerelease and `latest` is not then it should refuse to publish unless you explicitly asked for `latest` with `--tag`.  Differentiating between the command line option `--tag` and other sources of configuration can be done with `npm.config.get('tag', 'cli')`. This change won't be a priority for the CLI team in the immediate future, but we would welcome a community contribution.

I'm going to close this and flag it patch welcome.
