### ISSUE TITLE
Cannot pass empty message to npm-deprecate

### ISSUE THREAD

**Issue by jinjor** [npm/npm#6867]
I was trying to un-deprecate my npm module, but npm shows following message.
`npm ERR! Usage: npm deprecate <pkg>[@<version>] <message>`

It's caused by that `process.argv` does not return empty string.
Now I have solved this by directory edit deprecate.js.
Sorry if I'm misunderstanding the API doc.

OS: Windows 7

**Comment by gtanner** [comment]
This still appears to be broken and the workaround does not work anymore.

Attempting to "undeprecate" a module now gives:

```
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/Users/gtanner/Projects/npm" "deprecate" "fourism" ""
npm ERR! node v0.10.33
npm ERR! npm  v2.11.3
npm ERR! code E403

npm ERR! "You cannot publish over the previously published version 0.0.1." : fourism
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/gtanner/Projects/npm/npm-debug.log
```

**Comment by gtanner** [comment]
This is a little more scoped then I thought ...

Seems you can undeprecate the latest version (when explicitly stating it),  but i you try to undeprecate a historical version you get the above error

**Comment by othiym23** [comment]
This has been moved to the [npm roadmap](https://github.com/npm/npm/wiki/Roadmap), which we're using instead of the confusing `next-*` labels now.
