### ISSUE TITLE
Package install errors as of new npm version 2.1.11

### ISSUE THREAD

**Issue by CaptSaltyJack** [npm/npm#6873]
Ever since I updated to the latest version of npm, the webapp generator no longer works. Full output below:

    $ yo webapp --coffee

         _-----_
        |       |    .--------------------------.
        |--(o)--|    |    Welcome to Yeoman,    |
       `---------´   |   ladies and gentlemen!  |
        ( _´U`_ )    '--------------------------'
        /___A___\
         |  ~  |
       __'.___.'__
     ´   `  |° ´ Y `

    Out of the box I include HTML5 Boilerplate, jQuery, and a Gruntfile.js to build your app.
    ? What more would you like? Bootstrap, Sass
    ? Would you like to use libsass? Read up more at
    https://github.com/andrew/node-sass#node-sass: Yes
       create Gruntfile.js
       create package.json
       create .gitignore
       create .gitattributes
       create .bowerrc
       create bower.json
       create .jshintrc
       create .editorconfig
       create app/styles/main.scss
       create app/favicon.ico
       create app/robots.txt
       create app/index.html
       create app/scripts/main.coffee
       invoke   mocha

    I'm all done. Running bower install & npm install for you to install the required dependencies. If this fails, try running the command yourself.

       create     test/bower.json
       create     test/.bowerrc
       create     test/spec/test.js
       create     test/index.html
    bower cached        git://github.com/twbs/bootstrap-sass.git#3.2.0+2
    bower validate      3.2.0+2 against git://github.com/twbs/bootstrap-sass.git#~3.2.0
    bower cached        git://github.com/chaijs/chai.git#1.8.1
    bower validate      1.8.1 against git://github.com/chaijs/chai.git#~1.8.0
    bower cached        git://github.com/mochajs/mocha.git#1.14.0
    bower validate      1.14.0 against git://github.com/mochajs/mocha.git#~1.14.0
    bower cached        git://github.com/jquery/jquery.git#2.1.1
    bower validate      2.1.1 against git://github.com/jquery/jquery.git#>= 1.9.0
    bower install       chai#1.8.1
    bower install       mocha#1.14.0

    chai#1.8.1 bower_components/chai

    mocha#1.14.0 bower_components/mocha
    bower install       bootstrap-sass-official#3.2.0+2
    bower install       jquery#2.1.1

    bootstrap-sass-official#3.2.0+2 bower_components/bootstrap-sass-official
    └── jquery#2.1.1

    jquery#2.1.1 bower_components/jquery
    npm WARN package.json myproject@ No description
    npm WARN package.json myproject@ No repository field.
    npm WARN package.json myproject@ No README data
    \
    > phantomjs@1.9.12 install /Volumes/MegaDrive/Sites/myproject/node_modules/grunt-mocha/node_modules/grunt-lib-phantomjs/node_modules/phantomjs
    > node install.js

    Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-macosx.zip
    Saving to /var/folders/4x/79wsxmj16xbbh7p14k72l_2m0000gn/T/phantomjs/phantomjs-1.9.8-macosx.zip
    Receiving...
    \ [==========================--------------] 64% 0.0s-
    Received 9187K total.
    Extracting zip contents
    Removing /Volumes/MegaDrive/Sites/myproject/node_modules/grunt-mocha/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/lib/phantom
    Copying extracted folder /var/folders/4x/79wsxmj16xbbh7p14k72l_2m0000gn/T/phantomjs/phantomjs-1.9.8-macosx.zip-extract-1418058862274/phantomjs-1.9.8-macosx -> /Volumes/MegaDrive/Sites/myproject/node_modules/grunt-mocha/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/lib/phantom
    Removing /var/folders/4x/79wsxmj16xbbh7p14k72l_2m0000gn/T/phantomjs/phantomjs-1.9.8-macosx.zip-extract-1418058862274
    Writing location.js file
    Done. Phantomjs binary available at /Volumes/MegaDrive/Sites/myproject/node_modules/grunt-mocha/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/lib/phantom/bin/phantomjs
    npm WARN optional dep failed, continuing imagemin-pngquant@1.0.2
    npm WARN optional dep failed, continuing imagemin-gifsicle@1.0.0
    npm WARN optional dep failed, continuing imagemin-optipng@1.0.0
    npm WARN optional dep failed, continuing imagemin-jpegtran@1.0.0

    > node-sass@0.9.3 install /Volumes/MegaDrive/Sites/myproject/node_modules/grunt-sass/node_modules/node-sass
    > node build.js

    `darwin-x64-v8-3.14` exists; testing

      ․․․․․․․․․․․․․․․․․․․․․․․․

      24 passing (39ms)

    Binary is fine; exiting
    npm ERR! Darwin 13.4.0
    npm ERR! argv "node" "/usr/local/bin/npm" "install"
    npm ERR! node v0.10.32
    npm ERR! npm  v2.1.11
    npm ERR! path /Volumes/MegaDrive/Sites/myproject/node_modules/grunt-contrib-htmlmin/node_modules/html-minifier/node_modules/cli/node_modules/exit
    npm ERR! code EMFILE
    npm ERR! errno 20

    npm ERR! EMFILE, readdir '/Volumes/MegaDrive/Sites/myproject/node_modules/grunt-contrib-htmlmin/node_modules/html-minifier/node_modules/cli/node_modules/exit'
    npm ERR!
    npm ERR! If you need help, you may report this error at:
    npm ERR!     <http://github.com/npm/npm/issues>

**Comment by smikes** [comment]
Is this still a problem for you?  Could you try updating to the latest `npm` (2.1.17)?

To update npm, run `npm -g install npm@latest`

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by CaptSaltyJack** [comment]
Working fine now!

**Comment by othiym23** [comment]
Closing as resolved!
