### ISSUE TITLE
2.1.9+ Not installing code modules reliably

### ISSUE THREAD

**Issue by kmalakoff** [npm/npm#6875]
Something changes between 2.1.8 and 2.19 so that 2.1.9 no longer is installing node modules reliably.

```
npm ERR! Could not get cache stat 
npm ERR! Could not get cache stat 
npm ERR! Could not get cache stat 
npm ERR! Could not get cache stat 
npm ERR! Could not get cache stat 
npm ERR! Could not get cache stat 
npm ERR! Could not get cache stat 
npm ERR! Could not get cache stat 
npm ERR! Could not get cache stat 
npm ERR! Could not get cache stat 
npm ERR! Could not get cache stat 
npm ERR! Could not get cache stat 
npm ERR! Could not get cache stat 
npm ERR! Could not get cache stat 
npm ERR! Could not get cache stat 
npm ERR! Could not get cache stat 
npm ERR! Could not get cache stat 
npm ERR! Could not get cache stat 
npm ERR! Could not get cache stat 
npm ERR! Could not get cache stat 
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/Users/user/.nvm/v0.10.33/bin/npm" "install" "-g"
npm ERR! node v0.10.33
npm ERR! npm  v2.1.11
npm ERR! path /Users/user/.npm/_git-remotes/https-user-password-bitbucket-org-organization-module-ceb86596/objects/pack/pack-dc3e4594e18472d535270f5a45492344bd93a374.keep
npm ERR! code ENOENT
npm ERR! errno 34

npm ERR! enoent ENOENT, readdir '/Users/user/.npm/_git-remotes/https-user-password-bitbucket-org-organization-module-ceb86596/objects/pack/pack-dc3e4594e18472d535270f5a45492344bd93a374.keep'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 
```

If I revert to 2.1.8, I do not get these errors so I am stuck on an older version of npm.

Did something change in how npm installs git repos or handles file system permissions between 2.1.8 and 2.1.9?

**Comment by kmalakoff** [comment]
@othiym23  I've got three developers who are out of commission today because they are having npm install issues (one developer had the idea to reinstall one of our applications from scratch and the meme passed on to the others). We have been locked to 2.1.7 to work around this, but now something new is not working and the problems are different on different developer machines (missing dependencies).

Absolutely there are two repos depending on the same Git repo. All of our non-open source code is on Bitbucket and we use the small modules approach of Node.

We are now trying to find a version in the 1.x releases of npm that works.

Any news on a fix?

**Comment by othiym23** [comment]
Take a look at the [https://github.com/npm/npm/releases/tag/v2.1.17](release notes) for `npm@2.1.17` and have one of the engineers who's having trouble try it.There was a whole nest of conflicting assumptions that were leading to race conditions in the code handling caching of git repositories.

**Comment by kmalakoff** [comment]
@othiym23 I've reinstall some of our applications locally and had a developer do the same with 2.1.17. The installation seems to have passed!

Thank you!
