### ISSUE TITLE
npm link doesn't recognise --save and --save-dev

### ISSUE THREAD

**Issue by peterchoo** [npm/npm#6878]
This has tripped me up a couple of times when I've been and using locally developed npm packages for Ember-CLI.

I expect to not have to manually edit my package.json after calling `npm link my-addon --save-dev`.  

I couldn't find an existing issue for this.  Thanks for your time.

**Comment by othiym23** [comment]
The CLI team would welcome a patch to add this functionality, and would be happy to help contributors understand what code in the installer codebase would need to be adapted to support `--save` and `--save-dev` for `npm link`. We ourselves aren't going to have the time to do this in the near to medium-term, so I'm marking this issue as `patch-welcome` and closing it, which is what we do in these cases. Thanks for your time!
