### ISSUE TITLE
Can't create nested dependencies

### ISSUE THREAD

**Issue by itonics-tbeauvais** [npm/npm#6891]
```
UNKNOWN, mkdir '/var/www/lebowski/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/node_modules/bin-wrapper/node_modules/bin-version-check/node_modules/bin-version/node_modules/find-versions/node_modules/array-uniq'
```

I can't attach a full document, so here is a pastebin entry with the full error: http://pastebin.com/XsgJzRyL

He is on windows running 'npm install' on our project and running into problems.  I don't know it's a path length problem because he is using the same structure as other developers and it works for them.

Any thoughts?

**Comment by itonics-tbeauvais** [comment]
I think it is a path length restriction because that is a mounted Windows directory in a VirtualBox instance.  So, there might be some strange errors when presented when in actuality it is the length restriction.  What do you think?

**Comment by othiym23** [comment]
That sounds plausible, but if that's what's happening, that means your best recourse is to move your Node projects out of that mount, because that is something that npm and Node can't work around.

**Comment by itonics-tbeauvais** [comment]
Well, this would still be a problem for Windows developers.  I have heard a better recursion strategy will be introduced in NPM 3.0 .  When is that expected to be out?

**Comment by iarna** [comment]
Soon 😉 But seriously, I'm not giving public dates for that sort of thing at this time. But the end is in sight.

**Comment by iarna** [comment]
`npm@3` has been out for almost a year and it is very unlikely to run into the path length restrictions. As such I'm going to close this. If you are encountering anything like this with `npm@3` please open a new issue!
