### ISSUE TITLE
instrument CLI for analytics

### ISSUE THREAD

**Issue by othiym23** [npm/npm#6904]
There are a whole class of problems that would be much more tractable if the CLI team had a more solid idea of precisely how the CLI is being used. This can be observed directly via registry-side metrics, but that gives us poor insight into what's happening in a number of scenarios. In addition when the cache is rewritten to take advantage of a content-addressable store (i.e. for `npm@4`), it will no longer be necessary to even ping the server for eTag checking, which means that our download counts will be increasingly loose.

Any metrics gathered from within the CLI would have to be optional, and probably opt-in rather than opt-out. Something as simple as hitting a registry endpoint with argv would be a great starting point, although we'd also probably want to aggregate the metrics and only pass them along periodically anyway. And of course there's probably some blinding we'd need to do to prevent from leaking sensitive information.

**Comment by teppeis** [comment]
How about this issue?
I want to know what Node version do users of my package use.
It helps me judge whether to use ES6 features without Babel.

**Comment by jimmywarting** [comment]
@teppeis I want to know the same thing. But not only for my own package but for the hole world as well. more or less like  [gs.statcounter.com](http://gs.statcounter.com) were i can see what is the moste used node version, what OS they are using

**Comment by othiym23** [comment]
Step 0 is being implemented as #12529. There will be more to do once we get the basics (core instrumentation in the CLI, standing up a beacon to gather statistics) in place and operating smoothly. Be aware that this is _not_ intended as a replacement or augmentation of the existing download status – this is analytics information designed to improve the supportability and applicability of the npm CLI and registry themselves.
