### ISSUE TITLE
New npm progress indicator

### ISSUE THREAD

**Issue by iarna** [npm/npm#6911]
As discussed elsewhere we want a better progress indicator than a spinner or logs. The multi-stage installer branch brings this. The current iteration of the indicator looks like this:

![progressbar](https://cloud.githubusercontent.com/assets/983798/5410310/24279960-81c1-11e4-9427-6e76a018ff36.png)

So here we can see that we're extracting the form-data module. ("fetch" is a bit misleading here, that'll be corrected.)  The last log entry section was gunzTarPerm, which gives you a pretty good idea of what's going on. The little clock just before the bar spins every time a log line would have been printed at a higher log level.

Remaining work:

* [x] Fix progress bar section reporting (eg, "fetch" in the screenshot). This just involves making each of the new stages "tick" the progress bar at least once.
* [x] Fix progress bar one way or another such that last 50% doesn't finish neigh instantly
* [x] Make new progress bar obey --unicode
* [ ] There should be a facility for disabling the progress bar via config, like spin=false, maybe actually using spin…

And possibly:

* [ ] Deeper integration of progress bar into other related tasks, eg, cache, request, rimraf, etc

See also: #1257, #5340, #6420

**Comment by tkellen** [comment]
woo

**Comment by iarna** [comment]
Closing this as fixed in [npm/npm#multi-stage](https://github.com/npm/npm/tree/multi-stage)

**Comment by manpages** [comment]
Do these changes have something to do with problems with progress bar people across distros started to experience?

Such as

```
installing
install flags: install SHELL=/nix/store/kz4aii9y5kdxilxrjdz55gdr0piziwcz-bash-4.3-p33/bin/bash    
v0.13.0-pre
net.js:166
        throw errnoException(err, 'setBlocking');
              ^
Error: setBlocking ENOSYS
    at exports._errnoException (util.js:748:11)
    at new Socket (net.js:166:15)
    at createWritableStdioStream (node.js:466:18)
    at process.stderr (node.js:520:16)
    at Object.<anonymous> (/nix/store/lzns9av4iwjzdm81l3g3dgdklrmbvyfb-nodejs-0.12.0/lib/node_modules/npm/node_modules/npmlog/node_modules/gauge/progress-bar.js:9:28)
    at Module._compile (module.js:462:26)
    at Object.Module._extensions..js (module.js:480:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:367:17)
Makefile:5: recipe for target 'all' failed
```

**Comment by iarna** [comment]
manpages: Well, seeing is it hasn't actually been released, unless you're using a version from git directly, then no.

**Comment by iarna** [comment]
@manpages The gauge module did get brought in with an `npmlog` update a bit ago, but it's not actually being used at all as yet.

It *looks* like fetching the process.stdout file handle somehow is causing a crash for you. I don't understand how that's possible– I'd definitely need more information (eg an `npm-debug.log`) in order to track that down. If this is still an issue for you and you'd like progress on it, please open a NEW issue with whatever diagnostics you have available. Thank you!
