### ISSUE TITLE
handling multiple $npm_package_config

### ISSUE THREAD

**Issue by reggi** [npm/npm#6918]
I have `$npm_package_config_input` and `$npm_package_config_output` in this script and it seems that the only one that is running is the last one set.

```bash
thomas@workstation:reggi.myshopify.com$ npm run echo --examlple:input="hello" --example:output="world"
npm info it worked if it ends with ok
npm info using npm@2.1.11
npm info using node@v0.10.32
npm info preecho example@0.0.1
npm info echo example@0.0.1

> example@0.0.1 echo /Users/thomas/Desktop/reggi.myshopify.com
> echo "$npm_package_config_input $npm_package_config_output"

 world
npm info postecho example@0.0.1
npm info ok 
```

**Comment by smikes** [comment]
@reggi, Is this still a problem for you?

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by reggi** [comment]
Just tested! This is great! Works! Thanks all!
