### ISSUE TITLE
Don't run "install"/"postinstall" lifecycle scripts until after dependencies are installed

### ISSUE THREAD

**Issue by iarna** [npm/npm#6926]
Currently in the multi-stage installer this is mostly fixed by insuring that all modules are untared into their final destinations prior to running any of the lifecycle scripts.

The current implementation does NOT currently guarantee that your dependencies install or postinstall lifecycle scripts will be run prior to yours.  However, correcting this should be a simple matter.

Currently they're run serially, so by keeping track of whose lifecycle scripts have been started we can recurse into the deps to ensure that all of them have completed their lifecycle scripts before actually running our own.  By keeping track at start we'll both not run any lifecycle script more than once and we'll not infinitely recurse on cycles.

See also #5001, #6170.

**Comment by iarna** [comment]
Fixed with 5ff786a

**Comment by piranna** [comment]
Awesome! I was trully waiting for this issue for NodeOS install process! :-D

**Comment by piranna** [comment]
Just to be sure:

* with the new behaviour, ```preinstall``` will be exec before all the dependencies start their installation (including their ```preinstall```) and ```postinstall``` will be exec after all the dependencies finish their installation (including their ```postinstall```) in a "Depth-first search" fashion, isn't it?
* is it someway warranted the install order of two dependencies? Maybe ```peerDependencies``` has higher priority on same level?
* how could I be able to exec a ```preinstall``` script that make use of other modules like [download](https://github.com/kevva/download)?

**Comment by iarna** [comment]
1. `preinstall` is run AFTER the module is extracted but before it's placed in its final location in the tree. The order that `preinstall` lifecycles are run is not deterministic as they're not supposed to depend on each other.
2. `postinstall` is only executed after all of the dependencies have had their postinstalls run.
3. There is no way to effect order other than declaring a dependency. If you depend on another module being present then you should declare it as such.
4. Currently there's no way for `preinstall` scripts to make use of something like `download`. I'm not married to `preinstall`'s place in the lifecycle scripts, but I'd like to take a wait-and-see approach with when we run it. I'm really quite curious as to what they'd be used for…
