### ISSUE TITLE
Multi-stage installer --save* support

### ISSUE THREAD

**Issue by iarna** [npm/npm#6933]
* [x] --save (--save-dev, --save-optional, --save-bundle, --save-prefix, --save-exact)
  * [x] Update package.json
  * [x] Update npm-shrinkwrap.json
    * [x] deduped modules will of course, update the shrinkwrap #5161, #4944, #5448, #6410
    * [ ] install with a shrinkwrap and an arg list without --save should warn (or error)
    * [ ] saved shrinkwrap should be idempotent #5779

**Comment by donaldpipowitch** [comment]
Will this be solved before version 3? Because it looks like `dedupe` will be default on `$ npm install` [in the future](http://blog.npmjs.org/post/109921886740/a-belated-npm-weekly-3).

**Comment by iarna** [comment]
Closing this as fixed in [npm/npm#multi-stage](https://github.com/npm/npm/tree/multi-stage)

**Comment by backflip** [comment]
Great news!
Are the two shrinkwrap issues (warning on save and idempotence) still unchecked for a reason?
