### ISSUE TITLE
`npm install foo` should force a fresh install of `foo` even if it's already installed

### ISSUE THREAD

**Issue by iarna** [npm/npm#6938]
Currently args are treated as if you edited them into your `package.json`, which means if the module is already installed it won't be updated or installed again. It should force the install. This work should be done concurrently with #5254 probably.

**Comment by iarna** [comment]
Closing this as fixed in [npm/npm#multi-stage](https://github.com/npm/npm/tree/multi-stage)

**Comment by UltCombo** [comment]
Nice! :smiley:
