### ISSUE TITLE
npm ping patches: ready to go or need more work (and if so, what?)

### ISSUE THREAD

**Issue by smikes** [npm/npm#6941]
Currently work on `npm doctor` is happening in an outside repo , but it's partly blocked by the absence of `npm ping` in npm/npm, npm/npm-registry-client.

I think those are  #5750 #5788 and npm/npm-registry-client#55

Are those ready to go in (possibly for 2.2.0?)  If there's something blocking those changes, I'd be happy to work on it.

**Comment by othiym23** [comment]
`npm ping` is available as of `npm@2.13.0`, so we can consider this resolved! :tada:
