### ISSUE TITLE
npm hangs indefinitely

### ISSUE THREAD

**Issue by oliversalzburg** [npm/npm#6967]
Okay, #6080 is happening again. Again in a Vagrant box.

npm will hang at different points in the installation process. When I re-run the command, it might succeed or get stuck at a different point.

The same setup script ran fine in all my tests on my home desktop, but it fails nearly every time at work, so I'm assuming this has something to do with disk or network I/O.

I have a log of `npm install --global -dd bower`: https://gist.github.com/oliversalzburg/93d1636332a3a3f32bcc

I really can't see anything weird with it, other than it just stopping at that point.

I'm using npm 2.1.12.

**Comment by jsoverson** [comment]
Seems related to https://github.com/npm/npm/issues/7862

**Comment by RootMale** [comment]
The same problem for me, its hang with some job and spinner after npm verb unlock done using in a lot of different versions of node and npm on linux.

**Comment by varunpalekar** [comment]
The same problem for me.. I have wasted 8 hrs to install 2 modules.
