### ISSUE TITLE
CLI errors should indicate which registry gave the error

### ISSUE THREAD

**Issue by seldo** [npm/npm#6972]
With scopes it's now possible for a single installation of npm to be configured to talk to multiple different registries. This makes a new class of error possible: you did the right thing against the wrong registry (for instance, you might have mis-named the scope in your package, or tried to log in with the username from one registry agains the other).

CLI errors that originate from the server should therefore include the domain of the registry that sent the error, to clear up this ambiguity.

**Comment by othiym23** [comment]
This has been moved to the [npm roadmap](https://github.com/npm/npm/wiki/Roadmap), which we're using instead of the confusing `next-*` labels now. Also, because this is pertinent to npmE, we've labeled it accordingly.

**Comment by othiym23** [comment]
This is a requirement that it would be useful to have in view when doing a more thorough revision of the user experience around errors and diagnostics, which is a project that we'll be getting to any year now.
