### ISSUE TITLE
npm install keytar issues

### ISSUE THREAD

**Issue by KsaRedFx** [npm/npm#6974]
I'm getting issues installing keytar and I'm not too sure what the error is from. 
My path correctly has both `Program Files/nodejs` and `AppData/Roaming/npm` in it. 

```
keytar@2.0.3 install C:\cygwin64\home\jenkins\workspace\Popcorn-PPM\label\win64\node_modules\keytar
 node-gyp rebuild

git-utils@2.2.0 install C:\cygwin64\home\jenkins\workspace\Popcorn-PPM\label\win64\node_modules\git-utils
node-gyp rebuild

npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.10.33
npm ERR! npm  v2.1.12
npm ERR! code Unknown system errno 203
npm ERR! errno Unknown system errno 203
npm ERR! syscall spawn

npm ERR! spawn Unknown system errno 203
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>
```

**Comment by smikes** [comment]
Is this still a problem for you?

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as abandoned – I hope you got this worked out! For future reference, if you run `npm rebuild -ddd`, you'll get more logging output, including from `node-gyp`, which might give you further clues into which step `node-gyp` was failing on (but it's a pretty taciturn utility, so maybe not).
