### ISSUE TITLE
Phonegap install problem: ERR! not ok code 0

### ISSUE THREAD

**Issue by ASLANTORRET** [npm/npm#6986]
Hello guys.

I'm a new for npm, and have problem when try to install phonegap package. Screen: 
![image](https://cloud.githubusercontent.com/assets/7893808/5519275/bda42638-8975-11e4-94e6-80895da85c8d.png)

Also, have a problem when try command npm search.

**Comment by smikes** [comment]
Is this still a problem for you?

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by ASLANTORRET** [comment]
Hello. I've solved that issue: just started installation from scratch. Anyway, thanks for help.

Среда, 04 февраля 2015, 19:03 -08:00 от Sam Mikes <notifications@github.com>:
>Is this still a problem for you?
>To update npm on Windows, follow the instructions here:  https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows
>We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)
>Thanks!
>—
>Reply to this email directly or  view it on GitHub .


Best regards,
Aslan Ydyryshev

**Comment by othiym23** [comment]
Closing as resolved.
