### ISSUE TITLE
I can't install linter in atom

### ISSUE THREAD

**Issue by Robert-Janagap** [npm/npm#7015]
npm http GET https://registry.npmjs.org/emissary
npm http GET https://registry.npmjs.org/chai
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/xregexp/2.0.0
npm http GET https://registry.npmjs.org/jshint
npm http GET https://registry.npmjs.org/shelljs
npm http GET https://registry.npmjs.org/space-pen
npm http GET https://registry.npmjs.org/temp
npm http GET https://registry.npmjs.org/sinon
npm http GET https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/event-kit
npm http 304 https://registry.npmjs.org/chai
npm http 304 https://registry.npmjs.org/jshint
npm http 304 https://registry.npmjs.org/rimraf
npm http 304 https://registry.npmjs.org/shelljs
npm http 304 https://registry.npmjs.org/space-pen
npm http 304 https://registry.npmjs.org/sinon
npm http 304 https://registry.npmjs.org/temp
npm http 304 https://registry.npmjs.org/lodash
npm http 304 https://registry.npmjs.org/event-kit
npm http 304 https://registry.npmjs.org/xregexp/2.0.0
npm http 304 https://registry.npmjs.org/emissary
npm http GET https://registry.npmjs.org/grim
npm http GET https://registry.npmjs.org/property-accessors
npm http GET https://registry.npmjs.org/mixto
npm http GET https://registry.npmjs.org/underscore-plus
npm ERR! Error: ENOENT, lstat 'C:\Users\ROBERT~1\AppData\Local\Temp\apm-install-dir-1141126-3160-1cb9nyb\node_modules\linter\node_modules\chai\lib\chai\utils\getPathValue.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\Users\\Robert Yasay\\AppData\\Local\\atom\\app-0.165.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "c:\\Users\\Robert Yasay\\AppData\\Local\\atom\\app-0.165.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\Users\\Robert Yasay\\AppData\\Local\\atom\\app-0.165.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "C:\\Users\\Robert Yasay\\.atom\\.apmrc" "install" "C:\\Users\\ROBERT~1\\AppData\\Local\\Temp\\d-1141126-3160-n3sn78\\package.tgz" "--target=0.18.0" "--arch=ia32"
npm ERR! cwd C:\Users\ROBERT~1\AppData\Local\Temp\apm-install-dir-1141126-3160-1cb9nyb
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.4
npm ERR! path C:\Users\ROBERT~1\AppData\Local\Temp\apm-install-dir-1141126-3160-1cb9nyb\node_modules\linter\node_modules\chai\lib\chai\utils\getPathValue.js
npm ERR! fstream_path C:\Users\ROBERT~1\AppData\Local\Temp\apm-install-dir-1141126-3160-1cb9nyb\node_modules\linter\node_modules\chai\lib\chai\utils\getPathValue.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack c:\Users\Robert Yasay\AppData\Local\atom\app-0.165.0\resources\app\apm\node_modules\atom-package-manager\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat 'C:\Users\ROBERT~1\AppData\Local\Temp\apm-install-dir-1141126-3160-1cb9nyb\node_modules\linter\node_modules\sinon\lib\sinon\util\core.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\Users\\Robert Yasay\\AppData\\Local\\atom\\app-0.165.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "c:\\Users\\Robert Yasay\\AppData\\Local\\atom\\app-0.165.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\Users\\Robert Yasay\\AppData\\Local\\atom\\app-0.165.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "C:\\Users\\Robert Yasay\\.atom\\.apmrc" "install" "C:\\Users\\ROBERT~1\\AppData\\Local\\Temp\\d-1141126-3160-n3sn78\\package.tgz" "--target=0.18.0" "--arch=ia32"
npm ERR! cwd C:\Users\ROBERT~1\AppData\Local\Temp\apm-install-dir-1141126-3160-1cb9nyb
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.4
npm ERR! path C:\Users\ROBERT~1\AppData\Local\Temp\apm-install-dir-1141126-3160-1cb9nyb\node_modules\linter\node_modules\sinon\lib\sinon\util\core.js
npm ERR! fstream_path C:\Users\ROBERT~1\AppData\Local\Temp\apm-install-dir-1141126-3160-1cb9nyb\node_modules\linter\node_modules\sinon\lib\sinon\util\core.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack c:\Users\Robert Yasay\AppData\Local\atom\app-0.165.0\resources\app\apm\node_modules\atom-package-manager\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat 'C:\Users\ROBERT~1\AppData\Local\Temp\apm-install-dir-1141126-3160-1cb9nyb\node_modules\linter\node_modules\lodash\dist\lodash.compat.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\Users\\Robert Yasay\\AppData\\Local\\atom\\app-0.165.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "c:\\Users\\Robert Yasay\\AppData\\Local\\atom\\app-0.165.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\Users\\Robert Yasay\\AppData\\Local\\atom\\app-0.165.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "C:\\Users\\Robert Yasay\\.atom\\.apmrc" "install" "C:\\Users\\ROBERT~1\\AppData\\Local\\Temp\\d-1141126-3160-n3sn78\\package.tgz" "--target=0.18.0" "--arch=ia32"
npm ERR! cwd C:\Users\ROBERT~1\AppData\Local\Temp\apm-install-dir-1141126-3160-1cb9nyb
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.4
npm ERR! path C:\Users\ROBERT~1\AppData\Local\Temp\apm-install-dir-1141126-3160-1cb9nyb\node_modules\linter\node_modules\lodash\dist\lodash.compat.js
npm ERR! fstream_path C:\Users\ROBERT~1\AppData\Local\Temp\apm-install-dir-1141126-3160-1cb9nyb\node_modules\linter\node_modules\lodash\dist\lodash.compat.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack c:\Users\Robert Yasay\AppData\Local\atom\app-0.165.0\resources\app\apm\node_modules\atom-package-manager\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! error rolling back Error: EPERM, unlink 'C:\Users\ROBERT~1\AppData\Local\Temp\apm-install-dir-1141126-3160-1cb9nyb\node_modules\linter\node_modules\jshint\dist\jshint-rhino.js'
npm ERR! error rolling back  linter@0.9.0 { [Error: EPERM, unlink 'C:\Users\ROBERT~1\AppData\Local\Temp\apm-install-dir-1141126-3160-1cb9nyb\node_modules\linter\node_modules\jshint\dist\jshint-rhino.js']
npm ERR! error rolling back   errno: 50,
npm ERR! error rolling back   code: 'EPERM',
npm ERR! error rolling back   path: 'C:\\Users\\ROBERT~1\\AppData\\Local\\Temp\\apm-install-dir-1141126-3160-1cb9nyb\\node_modules\\linter\\node_modules\\jshint\\dist\\jshint-rhino.js' }
npm ERR! not found: git
npm ERR! 
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\Users\\Robert Yasay\\AppData\\Local\\atom\\app-0.165.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "c:\\Users\\Robert Yasay\\AppData\\Local\\atom\\app-0.165.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\Users\\Robert Yasay\\AppData\\Local\\atom\\app-0.165.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "C:\\Users\\Robert Yasay\\.atom\\.apmrc" "install" "C:\\Users\\ROBERT~1\\AppData\\Local\\Temp\\d-1141126-3160-n3sn78\\package.tgz" "--target=0.18.0" "--arch=ia32"
npm ERR! cwd C:\Users\ROBERT~1\AppData\Local\Temp\apm-install-dir-1141126-3160-1cb9nyb
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.4
npm ERR! code ENOGIT
npm ERR! Error: ENOENT, lstat 'C:\Users\ROBERT~1\AppData\Local\Temp\apm-install-dir-1141126-3160-1cb9nyb\node_modules\linter\node_modules\jshint\dist\jshint-rhino.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\Users\\Robert Yasay\\AppData\\Local\\atom\\app-0.165.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "c:\\Users\\Robert Yasay\\AppData\\Local\\atom\\app-0.165.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\Users\\Robert Yasay\\AppData\\Local\\atom\\app-0.165.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "C:\\Users\\Robert Yasay\\.atom\\.apmrc" "install" "C:\\Users\\ROBERT~1\\AppData\\Local\\Temp\\d-1141126-3160-n3sn78\\package.tgz" "--target=0.18.0" "--arch=ia32"
npm ERR! cwd C:\Users\ROBERT~1\AppData\Local\Temp\apm-install-dir-1141126-3160-1cb9nyb
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.4
npm ERR! path C:\Users\ROBERT~1\AppData\Local\Temp\apm-install-dir-1141126-3160-1cb9nyb\node_modules\linter\node_modules\jshint\dist\jshint-rhino.js
npm ERR! fstream_path C:\Users\ROBERT~1\AppData\Local\Temp\apm-install-dir-1141126-3160-1cb9nyb\node_modules\linter\node_modules\jshint\dist\jshint-rhino.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack c:\Users\Robert Yasay\AppData\Local\atom\app-0.165.0\resources\app\apm\node_modules\atom-package-manager\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm http 304 https://registry.npmjs.org/property-accessors
npm http 304 https://registry.npmjs.org/mixto
npm http 304 https://registry.npmjs.org/underscore-plus
npm http 304 https://registry.npmjs.org/grim
npm http GET https://registry.npmjs.org/underscore
npm http 304 https://registry.npmjs.org/underscore
npm

**Comment by iarna** [comment]
Closing as resolved.
