### ISSUE TITLE
npm link error on windows 8.1

### ISSUE THREAD

**Issue by mukhersh** [npm/npm#7022]
Getting a link error when trying to do a npm link with the following command.

npm link rpn

Here is the debug. Appreciate any help to resolve this. Thanks

```
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\ProgramFiles\\nodejs\\\\node.exe',
1 verbose cli   'D:\\ProgramFiles\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'link',
1 verbose cli   'rpn' ]
2 info using npm@1.4.28
3 info using node@v0.10.34
4 verbose node symlink D:\ProgramFiles\nodejs\\node.exe
5 verbose node_modules\rpn unbuild
6 verbose link symlinking C:\Users\Subha\AppData\Roaming\npm\node_modules\rpn to D:\tutorial\NodeLiveLessons\material\NodeLiveLessons-master\Lesson05\project_a\node_modules\rpn
7 error Error: EISDIR, symlink 'C:\Users\Subha\AppData\Roaming\npm\node_modules\rpn'
8 error If you need help, you may report this *entire* log,
8 error including the npm and node versions, at:
8 error     <http://github.com/npm/npm/issues>
9 error System Windows_NT 6.2.9200
10 error command "D:\\ProgramFiles\\nodejs\\\\node.exe" "D:\\ProgramFiles\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "link" "rpn"
11 error cwd D:\tutorial\NodeLiveLessons\material\NodeLiveLessons-master\Lesson05\project_a
12 error node -v v0.10.34
13 error npm -v 1.4.28
14 error path C:\Users\Subha\AppData\Roaming\npm\node_modules\rpn
15 error code EISDIR
16 error errno 28
17 verbose exit [ 28, true ]
```

**Comment by othiym23** [comment]
Yes, and nothing is working. It's great! I'll take a look at this once I have everything in place enough to not feel like I'm walking backwards through the fog.

**Comment by smikes** [comment]
Is this still a problem for you?

`npm` is now at version 2.5.1, with some improvements to how it works on Windows.  I'm pretty sure this issue hasn't been fixed, but if you have the chance, can you try updating to `npm@latest` and re-verify?

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

Thanks!

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
