### ISSUE TITLE
unable to install fabric.js  in windows 7 

### ISSUE THREAD

**Issue by kumarsivam** [npm/npm#7023]
![image](https://cloud.githubusercontent.com/assets/4737819/5562282/8a8df8d0-8e36-11e4-9a97-5dd1a85eda70.png)

when i was install fabric.js
i'm getting following error appear please can you guide me to install fabric.js
![image](https://cloud.githubusercontent.com/assets/4737819/5562313/a0eedea8-8e38-11e4-9b3e-72dd77474012.png)

i have installed following,
Microsoft windows  sdk v7.1,
Microsoft visual studio 10 Express,
python 2.7 and all

**Comment by kumarsivam** [comment]
Hi smikes, 
Thanks for your valuable reply,but before i saw your reply removed all my node, npm and python. started from cygWIn followed the instruction from below link

http://atbrox.com/2009/09/21/how-to-get-pipvirtualenvfabric-working-on-cygwin/

At this time $ fab  command not run the fabric. Please guide me 

![image](https://cloud.githubusercontent.com/assets/4737819/5600824/52f4c358-930a-11e4-9667-4bf8f9839735.png)


Still i did't install node and npm again.

Thanks!

**Comment by smikes** [comment]
Sorry, I can't read that screenshot.  Can you please upload your npm-debug.log as a gist http://gist.github.com? If possible, run npm with at least one -d flag to increase the logging level.

**Comment by smikes** [comment]
Is this still a problem for you?

Could you please upload your npm-debug.log as a gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as resolved / abandoned.

**Comment by othiym23** [comment]
(Generally a reboot is enough to fix EBUSY issues, and the fact that Windows makes you reboot to get around these things is super crazymaking.)
