### ISSUE TITLE
error when install gulp-* on vagrant+homestead on windows

### ISSUE THREAD

**Issue by leandroruel** [npm/npm#7026]
when i try install a gulp package with npm, inside vagrant with windows, i get this error:

http://pastebin.com/BB0XuD3S

**Comment by smikes** [comment]
Is this still a problem for you?

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by leandroruel** [comment]
sorry, i will close because i give up of use it in windows and i'm using in linux now.
