### ISSUE TITLE
Error: ENOENT, stat 

### ISSUE THREAD

**Issue by rkriel** [npm/npm#7028]
When trying to use 'npm install express' in scripts folder 'command prompt', the error: ENOENT, stat 'C:\Users\richardk\AppData\Roaming\npm' appears.

![npm error](https://cloud.githubusercontent.com/assets/10340541/5569778/692fba52-8f44-11e4-81a4-dbefe0e7852d.gif)

I would appreciate your feedback. This is the first node server I have worked with.

Thanks, Rick Kriel

**Comment by othiym23** [comment]
@rkriel That's what npm is supposed to do when you run a local install. Closing this issue as resolved.
