### ISSUE TITLE
error occur : npm install browserify -g 

### ISSUE THREAD

**Issue by wangta69** [npm/npm#7033]
npm http 304 https://registry.npmjs.org/console-browserify
npm ERR! Error: No compatible version found: console-browserify@'^1.1.0'
npm ERR! Valid install targets:
npm ERR! ["0.1.0","0.1.1","0.1.2","0.1.3","0.1.4","0.1.5","0.1.6","1.0.1","1.0.2","1.0.3","1.1.0"]
npm ERR!     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:709:10)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:631:10
npm ERR!     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-358.6.2.el6.x86_64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "browserify" "-g"
npm ERR! cwd /home/winkzone/nodejsService
npm ERR! node -v v0.10.9
npm ERR! npm -v 1.2.24

**Comment by wangta69** [comment]
thank you

**Comment by faiq** [comment]
:tada: glad I could help!
