### ISSUE TITLE
problem updating npm

### ISSUE THREAD

**Issue by murrayf** [npm/npm#7036]
Hello,

I tried to update npm using "sudo npm update -g" in my Fedora Core 21. Everything went find until a little error happened. As a consecuence, when I try to npm "some command" I get this:
module.js:340
    throw err;
          ^
Error: Cannot find module 'which'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /usr/lib/node_modules/npm/lib/npm.js:25:13
    at Object.<anonymous> (/usr/lib/node_modules/npm/lib/npm.js:518:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

... and I have lost my "which" bash command. 

  In /usr/bin I have found this broken link "which-nodejs -> ../lib/node_modules/which/bin/which" and I had to reinstall which rpm package to recover bash which command. But npm is not working correctly for me due to above error...

Thanks and Happy New Year!

Alberto.

*<8-)

**Comment by faiq** [comment]
Sorry for failing you twice already! So I did a little more digging and this install script will download a fresh copy of `npm` and put everything in the appropriate folders. It'll also come with it's own dependencies already, so it doesn't need to pull down from npm. 

So here's the actual install script:

`curl https://www.npmjs.org/install.sh | sh` 

I hope this works for you!

have a happy new year! :fireworks: :smile:

**Comment by murrayf** [comment]
Hi again Faiq,

Your suggestion worked for me now and I can install modules.

Thanks a lot and happy 2015!

Alberto.

:)

**Comment by robbles** [comment]
Update for anyone else facing this issue on an old machine: You have to reinstall `/usr/bin/which` or `/bin/which`, which npm helpfully deletes.

The suggested script (`https://www.npmjs.org/install.sh`) works, but it also calls `which node`, which will fail if you haven't restored it first.

**Comment by ahmednuaman** [comment]
I've just hit this problem, and it's just appeared out of nowhere. I've been using iojs v2.0.0 with npm v2.9.0, and all of a sudden this came up. I think reinstalling `which` is a bit OTT, why would npm delete that?

**Comment by robbles** [comment]
@ahmednuaman I don't recall the exact details, but I believe there's also a package called `which` that NPM uses. I assume it deletes the native binary during the buggy self-reinstall process while trying to clean up the executables it previously installed.
