### ISSUE TITLE
Unable to install phonegap using "npm install -g phonegap"

### ISSUE THREAD

**Issue by antoni-rokitnicki** [npm/npm#7037]
I don't have proxy or need to use one. I tried to switch to http as some advices suggest and it did not help.

Windows7 x64
```
d:\Java\nodejs>node -v
v0.10.35
```
```
d:\Java\nodejs>npm install -g phonegap
npm ERR! network getaddrinfo ENOTFOUND
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "d:\\Java\\nodejs\\\\node.exe" "d:\\Java\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "phonegap"
npm ERR! cwd d:\Java\nodejs
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! syscall getaddrinfo
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     d:\Java\nodejs\npm-debug.log
npm ERR! not ok code 0
```

```
d:\Java\nodejs\npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ 'd:\\Java\\nodejs\\\\node.exe',
1 verbose cli   'd:\\Java\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'phonegap' ]
2 info using npm@1.4.28
3 info using node@v0.10.35
4 verbose node symlink d:\Java\nodejs\\node.exe
5 verbose cache add [ 'phonegap', null ]
6 verbose cache add name=undefined spec="phonegap" args=["phonegap",null]
7 verbose parsed url { protocol: null,
7 verbose parsed url   slashes: null,
7 verbose parsed url   auth: null,
7 verbose parsed url   host: null,
7 verbose parsed url   port: null,
7 verbose parsed url   hostname: null,
7 verbose parsed url   hash: null,
7 verbose parsed url   search: null,
7 verbose parsed url   query: null,
7 verbose parsed url   pathname: 'phonegap',
7 verbose parsed url   path: 'phonegap',
7 verbose parsed url   href: 'phonegap' }
8 silly lockFile 10db903f-phonegap phonegap
9 verbose lock phonegap C:\Users\Dell\AppData\Roaming\npm-cache\10db903f-phonegap.lock
10 silly lockFile 10db903f-phonegap phonegap
11 silly lockFile 10db903f-phonegap phonegap
12 verbose addNamed [ 'phonegap', '' ]
13 verbose addNamed [ null, '*' ]
14 silly lockFile 3a6257f3-phonegap phonegap@
15 verbose lock phonegap@ C:\Users\Dell\AppData\Roaming\npm-cache\3a6257f3-phonegap.lock
16 silly addNameRange { name: 'phonegap', range: '*', hasData: false }
17 verbose request where is /phonegap
18 verbose request registry https://registry.npmjs.org/
19 verbose request id ce35bf948f93cf9a
20 verbose url raw /phonegap
21 verbose url resolving [ 'https://registry.npmjs.org/', './phonegap' ]
22 verbose url resolved https://registry.npmjs.org/phonegap
23 verbose request where is https://registry.npmjs.org/phonegap
24 info trying registry request attempt 1 at 22:53:52
25 http GET https://registry.npmjs.org/phonegap
26 info retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND
27 info trying registry request attempt 2 at 22:54:02
28 http GET https://registry.npmjs.org/phonegap
29 info retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND
30 info trying registry request attempt 3 at 22:55:02
31 http GET https://registry.npmjs.org/phonegap
32 silly lockFile 3a6257f3-phonegap phonegap@
33 silly lockFile 3a6257f3-phonegap phonegap@
34 error network getaddrinfo ENOTFOUND
34 error network This is most likely not a problem with npm itself
34 error network and is related to network connectivity.
34 error network In most cases you are behind a proxy or have bad network settings.
34 error network
34 error network If you are behind a proxy, please make sure that the
34 error network 'proxy' config is set properly.  See: 'npm help config'
35 error System Windows_NT 6.1.7601
36 error command "d:\\Java\\nodejs\\\\node.exe" "d:\\Java\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "phonegap"
37 error cwd d:\Java\nodejs
38 error node -v v0.10.35
39 error npm -v 1.4.28
40 error syscall getaddrinfo
41 error code ENOTFOUND
42 error errno ENOTFOUND
43 verbose exit [ 1, true ]
```

**Comment by antoni-rokitnicki** [comment]
I don't have one. this is a home connection, I would have to contact internet provider. so you think there is a problem with dns ? is there any workaround ? can I just use hosts file in windows or is the issue more complex ?

**Comment by smikes** [comment]
In your browser settings, under Connection, is it set to auto-detect a proxy?  (I believe this is the default).  If so you may be using a proxy through your ISP without knowing it.

/cc @othiym23 is there a way to read the autoconfigured proxy settings on Windows without having to use C++?  Some registry settings are documented eg here: http://blog.raido.be/?p=426

**Comment by othiym23** [comment]
@smikes If you know you're running on Windows, there's `REQ QUERY`, and it can probably be scripted in such a way that we can reliably autodetect proxy settings that are done at the OS level. I'd probably want to abstract that out into a module that sets the relevant environment variables so that npm wouldn't have to change its interface with `request`.

@antoni-rokitnicki While it's not 100% certain that you have a proxy messing with things, the alternative is that your network connection is flaky. Is npm the only thing on your system that has difficulty downloading things? Are you using Ruby or Python, or other command-line tools that don't download things via web browsers?

**Comment by antoni-rokitnicki** [comment]
Its connection in my perents house, so I cannot check that now, but I will ASAP. 
If the connection is flaky is there anything I can do ?

Maybe its possible for npm to auto-detect proxy settings ? or get proxy from IE ? (I think its in registry)

**Comment by othiym23** [comment]
Indeed there is, see #7156 for versions using both PowerShell and plain `cmd.exe`.

**Comment by smikes** [comment]
Is this still a problem for you?

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as abandoned (there are other issues open for adding auto-configuration of proxy information).

**Comment by Rashmi-Kolte** [comment]
I am having same issue(error of proxy while installing npm install -g phonegap)
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
.
.
.
.
npm ERR! not ok code 0
please help me

I tried all mentined solutions, but nothing is working.........

**Comment by smikes** [comment]
@Rashmi-Kolte Yes, in order to use `npm`, you must currently have internet access.

Could you please create a new issue at https://github.com/npm/npm/issues/new to track your support request?  Thanks!
