### ISSUE TITLE
More information when do npm -g update

### ISSUE THREAD

**Issue by watilde** [npm/npm#7038]
Hi.
I think it should display more information when do `npm -g update`

Case.1
Do npm -g updatewWhen it hasn't installed npm in global.

Example:
```
$ npm list -g --depth 0
/Users/watilde/.nodebrew/current/lib
└── npm@2.1.16

$ npm update -g gulp
// => No information for now
// it sould display a message like: "gulp hasn't installed in global env"
$ 
```

Case.2
Do npm -g update when it has already installed latest.

Example:
```
$ npm install -g gulp
$ npm list -g --depth 0
/Users/watilde/.nodebrew/current/lib
├── gulp@3.8.10
└── npm@2.1.16

$ npm update -g gulp
// => No information for now
// it sould display a message like: "gulp has already installed latest version"
$
```

Thanks.

**Comment by othiym23** [comment]
Closing as resolved / won't fix. `npm -g update` will be changing in the next major version of npm to behave more like `npm install`, but until then, you just plain shouldn't be using the command, as it rarely does what most users expect.
