### ISSUE TITLE
Feature request: --save should be standard behavior

### ISSUE THREAD

**Issue by alexanderGugel** [npm/npm#7039]
There are probably hundreds (at least one) of npm packages out there that depend on dependencies not outlined in `package.json`. I think it would actually make a lot of sense to get rid of the `--save` flag and save the dependency in the manifest file by default (something like a `--no-safe` flag instead).

Especially when looking at npm/newww, it encourages users to `npm install *`<sup>1</sup>. I highly doubt that everyone remembers to outline the dependency in `package.json`.

<sup>1</sup>
![screen shot 2015-01-01 at 3 51 03 pm](https://cloud.githubusercontent.com/assets/703628/5592413/0961f586-91ce-11e4-90ad-c3aa68852d4a.png)

**Comment by KenanY** [comment]
Duplicate of https://github.com/npm/npm/issues/5108.

**Comment by alexanderGugel** [comment]
Agree. Closing.
