### ISSUE TITLE
automating npm publish from travis build

### ISSUE THREAD

**Issue by iamcdonald** [npm/npm#7042]
I'm trying to automate 'npm publish' as part of a travis build job.
While I understand travis has it's own deployment config for doing this however I would like to do it as part of a bash script.

Looking at the travis-ci code suggests they simply generate the ~/.npmrc file using an encrypted auth token (_auth/_password from my local .npmrc) and the corresponding email.

Initially I thought I could just do the same resulting in the following .npmrc file

//registry.npmjs.org/:_password=password
//registry.npmjs.org/:email=email@email.com

and then run 'npm publish .'.

Unfortunately this leads to a failure every time with the following error message.
```
npm ERR! Linux 2.6.32-042stab090.5
npm ERR! argv "node" "/home/travis/.nvm/v0.11.14/bin/npm" "publish" "./"
npm ERR! node v0.11.14
npm ERR! npm  v2.1.16
npm ERR! code ENEEDAUTH
npm ERR! need auth auth required for publishing
npm ERR! need auth You need to authorize this machine using `npm adduser`
```
If anyone could offer any pointers it would be much appreciated.
Sorry if this is a silly question.

Iain

**Comment by faiq** [comment]
Hey, so if you're trying to automate `npm publish` from your travis build there's a lot you need to consider.  

So first of all, your .npmrc file should support you doing a publish. To do this you need to run `npm adduser` on your travis machine. This will generate a secure token string that will be saved in your npmrc file and will serve as your password. You do not have to keep your actually password in your npmrc file! 

After running `npm adduser` your .npmrc file will look something like this.

```
auth=mysupersecurething123342=
email=myemail@gmail.com
....
```

So now you have to make sure the version of your package are set correctly. I don't know how travis would handle this, it doesn't know what a minor/major change in your package is, so it wouldn't be able to version them correctly. So I really don't think this is a good thing to be doing, but thats just my opinion.

**Comment by iamcdonald** [comment]
Hi Faiq,

thanks for your reply. 
I am using the latest npm locally and forcing travis-ci to do the same by running `npm install npm -g` in the before_install lifecycle step.
The newer versions use _password rather than _auth (https://github.com/npm/npm/issues/6975).
I'm just including this as background.

All previous docs I've seen for publishing on travis-ci using their inbuilt deploy functionality requires grabbing the (_auth/_password) from your local .npmrc and securely storing it in the .travis.yml thus not requiring you to run `npm adduser` on the travis box itself.

Looking into the travis-ci code responsible for this brought me to https://github.com/travis-ci/dpl/blob/master/lib/dpl/provider/npm.rb. You can see they simply generate a .npmrc file locally using the email and _auth stored in the .travis.yml file. 

However, when I try this same procedure (but with _password and email) as part of the script I get the ENEEDAUTH error.

With regards to versioning etc. I'm not using this to do continuous deployment (i.e. the script isn't trying to work out for itself whether the package.json version number should be bumped and whether that should be a major/minor/bug bump). 

I'm currently deploying the same lib to npm and bower with the aim of possibly adding other package dependency managers (say nuget, component, spm) and would like an automated way of releasing to all platforms rather than having to do it manually. I am tying this all to pushing of a release tag e.g. (0.1.4). If this tag matches both the versions in bower.json and package.json (which I would have had to previously push) then the `npm publish` command will be ran, otherwise the publish job should fail. 

This means I'm still responsible for the versions of things published but hopefully there's less room for error on my part in terms of 'publishing' slightly different states of the library to each platform.

I'm open to thoughts on this whole procedure though, is there a better way to accomplish this?

**Comment by smikes** [comment]
This is a good question and unfortunately there is not, as far as I am aware, a "best" way of keeping up-to-date modules published on multiple package systems.

What happens if you set up all your auth credentials in `.npmrc` and then have travis run an `npm adduser`?  You have to ensure that all of these are set:

```
//registry.npmjs.org/:_password
//registry.npmjs.org/:email
//registry.npmjs.org/:username
```

Then you can run 
```
yes '' | npm adduser
```

to run `npm adduser` quasi-interactively; `yes` will send an empty string followed by RET, so the default values will just be re-used.

I have no idea whether this will help with the ENEEDAUTH issue, though.

**Comment by smikes** [comment]
Is this still a problem for you?

Have you worked around this problem somehow, or is this still preventing you from auto-publishing from travis?

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by evindor** [comment]
We are having trouble with similar problem - we are trying to log in on circle ci to pull the private package. Trying the solution from one post above results in this error:
```
npm ERR! Linux 3.14.28-031428-generic
npm ERR! argv "node" "/home/ubuntu/nvm/v0.10.34/bin/npm" "adduser"
npm ERR! node v0.10.34
npm ERR! npm  v2.7.3
npm ERR! code E400

npm ERR! Unknown error while authenticating : -/user/org.couchdb.user:enkilabs
```

**Comment by ralphtheninja** [comment]
@iamcdonald So instead of doing e.g.

```
$ npm version patch
$ npm publish
```

you do something like:

```
$ git tag v1.0.4
$ git push --tags
```

I don't see publishing automatically to npm as something that should (or needs to) be automated.

**Comment by othiym23** [comment]
@evindor That won't work anymore with the rollout of the new registry, because npm has switched to token-based authentication on the primary registry. See http://blog.getpiggybank.com/npm-private-modules-with-heroku/ for details on how to set up auth from Heroku, which should be easily adaptable for use with CircleCI.

**Comment by othiym23** [comment]
(Also, a brief note that in the absence of real delegated roles and role-based authentication, this is still not a super-safe thing to do. YMMV, etc.)

**Comment by evindor** [comment]
@othiym23 Thanks a lot, that worked like a charm!

**Comment by iamcdonald** [comment]
Sorry, I haven't responded to this any sooner.

Glad it's worked out now,
I guess I'll just add the below for completeness.

The above solution given by @smikes led me in the right direction which was I originally thought the password was an auth token rather than just a hash of the password and thus wasn't adding my username to .npmrc. Once I added my username everything started working.

In terms of reasoning, I originally wanted to automate 'npm publish' because I was looking at targeting various js package managers for the same library and didn't want to manually have to 'publish' to bower, npm, spm, jspm etc. each time I wanted to release.

**Comment by othiym23** [comment]
Closing as resolved.

**Comment by dtothefp** [comment]
Hi @iamcdonald I'm wondering if you ever came up with a working solution for this. I'm a little unclear about what you were saying above about adding your username, and not sure if you are hardcoding your "password". I tried

```
//registry.npmjs.org/:_password=$NPM_PASSWORD
//registry.npmjs.org/:email=dtothefp@gmail.com
//registry.npmjs.org/:username=dtothefp
```

with `NPM_PASSWORD` as a travis encrypted env variable but running the suggested script of @smikes  didn't work. Also the link to the blog @othiym23 put up no longer works. Any suggestions would be great..thanks

**Comment by iamcdonald** [comment]
Hi @dtothefp,

I haven't ran this in a while but I was using this [bash script](https://github.com/iamcdonald/forestry/blob/master/.travis/publish.sh) with ```npm_token``` being a travis encrypted env variable and the goal being that tagging a the git repo results in a publish to npm.

**Comment by dtothefp** [comment]
@iamcdonald thanks for the response, that's great!!! I got it working, ended up adding my auth token, not sure if it's necessary. This is super helpful for me because I'm building a boilerplate module that builds frontend projects, but in order to test it, it needs to live inside of a base repo if that makes any sense. Anyway, `cd`ing into the module I want to deploy, building it, and running your script works :smile: 

```sh
#!/bin/bash
echo "Publish";
export NPM_V=`sed -n 's/.*"version":.*\([0-9]\{1,\}\.[0-9]\{1,\}\.[0-9]\{1,\}\).*/\1/p' package.json`;
echo "Package Version: ${NPM_V}"
echo "Tag: ${TRAVIS_TAG}"
if [[ ${TRAVIS_TAG} == ${NPM_V} ]]
	then
		echo "Publishing package ${TRAVIS_TAG}";
		echo "//registry.npmjs.org/:_password=${NPM_PASSWORD}" > ~/.npmrc
    echo "//registry.npmjs.org/:_authToken=${NPM_AUTH}" >> ~/.npmrc
		echo "//registry.npmjs.org/:username=dtothefp" >> ~/.npmrc
		echo "//registry.npmjs.org/:email=dtothefp@gmail.com" >> ~/.npmrc
		npm publish ./
		echo "Success"
	else
		echo "Publishing package ${TRAVIS_TAG} failed (versions not in alignment with ${NPM_V})"
		exit 1
fi
```

**Comment by iamcdonald** [comment]
@dtothefp no worries, glad I could help.

**Comment by jedrichards** [comment]
Just in case this is useful to anyone, here's how we automate npm publishing in CodeShip.

Our approach is that if we want to trigger a publish after a build, we make a commit that increments the semver in package.json. The publish script then compares the local semver in package.json with the latest semver of the module, and only tries to publish if the local semver is greater.

```js
import {execSync} from 'child_process'
import {version as packageVersion} from '../package'
import {writeFileSync} from 'fs'
import semver from 'semver'

const log = (value) => console.log(value)
const exec = (command) => log(execSync(command, {encoding: 'utf8'}))
const moduleName = '@foo/bar'

log(`Starting automated npm publish of ${moduleName}...`)

log('Writing temporary .npmrc to disk for authentication...')
writeFileSync('.npmrc', '//registry.npmjs.org/:_authToken=${NPM_TOKEN}\n')

const npmVersion = semver.clean(exec(`npm show ${moduleName} version`))
const shouldPub = semver.gt(packageVersion, npmVersion)

log(`Latest version on npm: ${npmVersion}`)
log(`Local version in package.json: ${packageVersion}`)

if (!shouldPub) {
  log('Aborting publish, local version is not new')
  process.exit(0)
}

log(`Tagging repo with v${packageVersion}...`)
exec('git fetch --unshallow || true')
exec(`git tag v${packageVersion}`)
exec('git push git@github.com:foo/bar.git --tags')

log('Publishing...')
exec('npm run build')
exec('npm publish')

log('Publishing complete')
```
