### ISSUE TITLE
Node / io.js v0.12 HEAD breaks `npm install`

### ISSUE THREAD

**Issue by othiym23** [npm/npm#7043]
Steps to reproduce:

1. clone either of [joyent/node](https://github.com/joyent/node) or [iojs/io.js](https://github.com/iojs/io.js)
2. `git checkout v0.12`
3. `configure && make -j4`
4. clone npm
5. `cd npm && make install`
6. `cd npm/test/tap/outdated-depth`
7. `rm -rf node_modules && PATH=path/to/freshly/built/node:$PATH npm install`

@wraithan found this running the New Relic tests against v0.11.15-pre; I was able to reproduce it simply by running the npm tests and narrowing it down to being an issue with installation. Digging deeper, I discovered that the problem is during the actual unpack of the tarballs. `node-tar` is using a low-level `block-stream` to handle the extraction of the individual entries from the tar stream, and something has changed to cause the `.end()` function on those block streams to no longer be called in v0.12 HEAD (and also to cause the process to start consuming gratuitous amounts of CPU time). The problem doesn't exist with v0.11.14 or v0.10.*. I've gone as far as I can without really digging deep; I'm running up the flag by filing this issue in the hopes that one of @isaacs or @chrisdickinson can help me isolate what might have changed and confirm whether this problem is Node or npm / `node-tar` / `block-stream`'s.

We should get this resolved before v0.11.15 is released, because `npm install` will break for a substantial number of users immediately. @wraithan first noticed this with `npm@2.1.6`, and I suspect it affects versions much older than that.

**Comment by othiym23** [comment]
I have a branch with a ton of extra debugging statements thrown into it if anybody wants it. Just say the word! It uses `process._rawDebug`, so it only works with Node 0.11+.

**Comment by chrisdickinson** [comment]
I have a sneaking suspicion it might be related to https://github.com/iojs/io.js/commit/1183ba47dfc2bc8b39f0c10d8dc9e9299a4470bf (or https://github.com/joyent/node/commit/6f6a97958e8723b4b4a3ccf352252b36cf7a0d85 on joyent/node). Investigating now.

**Comment by othiym23** [comment]
That makes sense, given that the extractor is the next step in the pipeline after decompression. I noticed that the error only happens when the extractor is working with multiple chunks (which is why this doesn't always fail, and why underscore triggers the issue – it's got a hefty PSD in it). Is it possible that in some cases, the multi-file extraction logic fails to notice that the zip stream is fully consumed?

**Comment by chrisdickinson** [comment]
Just adding a note here: confirmed my suspicions. It goes into a death spiral [here](https://github.com/iojs/io.js/blob/d5c7a9737a787c3605bb6996653a36a988742e15/lib/zlib.js#L596). This line gets called in an infinite loop at the end. The traceback triggering this loop is here:

```
Error
    at Unzip.Zlib._processChunk (zlib.js:558:16)
    at Unzip.Zlib._transform (zlib.js:505:8)
    at Unzip.Transform._read (_stream_transform.js:181:10)
    at Unzip.Transform._write (_stream_transform.js:169:12)
    at doWrite (_stream_writable.js:276:12)
    at writeOrBuffer (_stream_writable.js:263:5)
    at Unzip.Writable.write (_stream_writable.js:199:11)
    at ReadStream.ondata (_stream_readable.js:545:20)
    at ReadStream.emit (events.js:138:20)
    at ReadStream.OD (/Users/chris/projects/iojs/npm/lib/utils/tar.js:273:11)
    at ReadStream.emit (events.js:116:17)
    at readableAddChunk (_stream_readable.js:164:16)
    at ReadStream.Readable.push (_stream_readable.js:127:10)
    at onread (evalmachine.<anonymous>:1686:12)
    at callback (/Users/chris/projects/iojs/npm/node_modules/graceful-fs/polyfills.js:234:17)
    at FSReqWrap.wrapper [as oncomplete] (evalmachine.<anonymous>:530:17)
```

**Comment by othiym23** [comment]
Thanks for looking into this, @chrisdickinson! Is there a Node / io.js issue I can watch, or should I file one? I edited the original issue to include the fact that the crashed processes are using hella CPU; I noticed this when running the npm tests, but forgot to mention it.

**Comment by rmg** [comment]
I found this while testing modules against 0.11.15-pre as well. Was a major bummer. :-(

**Comment by othiym23** [comment]
@rmg Take a look at joyent/node#8962. @chrisdickinson is on the case!

**Comment by rmg** [comment]
@othiym23 yep, I chimed in there before here. Just trying to be thorough :-)

**Comment by mzgol** [comment]
Is this still an issue?

**Comment by ruimarinho** [comment]
@mzgol I've had no problems on 0.11.15, 0.11.16 or io.js 1.x, so I assume this issue can be closed.

**Comment by othiym23** [comment]
Yes! This is resolved in both io.js 1.0.x and Node 0.12.0, and I am closing it as such.
