### ISSUE TITLE
**npm install** doesn't install anything

### ISSUE THREAD

**Issue by krman009** [npm/npm#7049]
This happens when I type `npm install` and hit `Enter`...
```
npm WARN package.json @ No description
npm WARN package.json @ No repository field.
npm WARN package.json @ No README data
npm WARN package.json http@0.0.0 http is also the name of a node core module.
npm WARN package.json http@0.0.0 No description
npm WARN package.json http@0.0.0 No repository field.
npm WARN package.json http@0.0.0 No README data
```
The [directory](https://github.com/krman009/Daily-Task) is hosted in Github.

[gulpfile.js](https://github.com/krman009/Daily-Task/blob/master/gulpfile.js) [package.json](https://github.com/krman009/Daily-Task/blob/master/package.json)

**Comment by othiym23** [comment]
Your `package.json` needs at least a `name` and a `version` before `npm install` will do anything useful. The bug here is that npm doesn't error out immediately when one or both of those required attributes is missing.

**Comment by krman009** [comment]
What to do so that I can fix the issue.. ?

I think I've written both `name` and `version` of `http` in `package.json` file.

**Comment by KenanY** [comment]
@krman009 The _root_ of your `package.json` needs a `name` and `version`, like so:

``` json
{
  "name": "daily-task",
  "version": "0.1.0",
  "devDependencies": {
    "colors": "^1.0.3",
    "connect-livereload": "^0.5.0",
    "ecstatic": "^0.5.6",
    "express": "^4.10.2",
    "gulp": "~3.7.0",
    "gulp-livereload": "^2.1.1",
    "http": "0.0.0",
    "tiny-lr": "^0.1.4"
  }
}
```

**Comment by krman009** [comment]
Anyway the issue is appearing when we **rerun** the command `npm install`..
Anyway to fix it for something like updating devDependencies?
I've to delete `node_modules` before **rerun** the `npm install` to successfully run the command.

**Comment by krman009** [comment]
I've closed the issue because it works when I run command `npm install` after deleting the folder named `node_modules`.

**Comment by passabilities** [comment]
:+1:  for deleting `node_modules`
