### ISSUE TITLE
'cardova' is not in the npm registry (ubutnu)

### ISSUE THREAD

**Issue by DhirManish** [npm/npm#7051]
command : sudo npm install -g cardova 
------------------------------------------
got these errors 
```
npm ERR! Linux 3.15.5-031505-generic
npm ERR! argv "node" "/usr/bin/npm" "install" "-g" "cardova"
npm ERR! node v0.10.33
npm ERR! npm  v2.1.17
npm ERR! code E404

npm ERR! 404 Not Found: cardova
npm ERR! 404 
npm ERR! 404 'cardova' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/manishdhir/npm-debug.log
```

**Comment by mapmeld** [comment]
There is no package with that name on npm.

Is it possible that you meant ```npm install -g cordova```?

**Comment by smikes** [comment]
Is this still a problem for you?

As @mapmeld suggests, you may be trying to install `cordova`.

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as resolved / abandoned.

**Comment by muraliremod7** [comment]
when i am starting install for corodova occurring below showing  problem so how can i solve it 


C:\Users\Murali>npm install -g corodova ionic
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "corodova" "ionic"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/corodo
a
npm ERR! 404
npm ERR! 404 'corodova' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!

npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Murali\npm-debug.log

**Comment by KenanY** [comment]
@muraliremod7 Are you sure you don't mean to be installing `cordova`? You are typing `corodova`.

**Comment by muraliremod7** [comment]
sorry sir it's a spelling mistake and thank you sir.
