### ISSUE TITLE
Bug with case sensitivity in package names and 404 page.

### ISSUE THREAD

**Issue by trusktr** [npm/npm#7053]
Hi, I have a package at https://www.npmjs.com/package/army-knife.

If you try to visit https://www.npmjs.com/package/Army-Knife (with the capital letters) then you'll be greeted with a message that says

```
https://www.npmjs.com/package/army-knife does not exist. time to go outside.
```

but indeed, https://www.npmjs.com/package/army-knife *does* exist!

I think it's best if names are case-insensitive, and no matter how the name is capitalized in the URL, the package page always loaded instead of a 404 page.

**Comment by mapmeld** [comment]
You should look into submitting to the repo for the website, https://github.com/npm/newww - the reason for case sensitivity on npm is discussed in this issue: https://github.com/npm/newww/issues/380

**Comment by KenanY** [comment]
:+1: to what @mapmeld said. This is the issue tracker for `npm`-the-CLI-tool. If you have an issue with the website, you should report it to [`npm/newww`](https://github.com/npm/newww).

**Comment by trusktr** [comment]
https://github.com/npm/newww/issues/490
