### ISSUE TITLE
Can't install module

### ISSUE THREAD

**Issue by fsaccoh** [npm/npm#7061]
fodaysaccoh$ npm install -g jshint
npm WARN locking Error: EACCES, open '/Users/fodaysaccoh/.npm/_locks/jshint-115ab28abe2eddcb.lock'
npm WARN locking  /Users/fodaysaccoh/.npm/_locks/jshint-115ab28abe2eddcb.lock failed { [Error: EACCES, open '/Users/fodaysaccoh/.npm/_locks/jshint-115ab28abe2eddcb.lock']
npm WARN locking   errno: 3,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/fodaysaccoh/.npm/_locks/jshint-115ab28abe2eddcb.lock' }
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "jshint"
npm ERR! node v0.10.33
npm ERR! npm  v2.1.14

npm ERR! Attempt to unlock /Users/fodaysaccoh/npm-global/lib/node_modules/jshint, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/fodaysaccoh/npm-debug.log

**Comment by faiq** [comment]
This looks like a permissions issue, and it can easily be resolved! @linclark recorded this video:  https://www.youtube.com/watch?v=bxvybxYFq2o that gives you multiple different options to fix it! 


I think this command is the one you'll probably need:

```
sudo chown -R `whoami` ~/.npm
``` 

But you should totally watch the video and decide what the best option is for you!

**Comment by fsaccoh** [comment]
It totally worked. Thank you

**Comment by faiq** [comment]
:tada: can you please close the issue, to help us manage our issue tracker!
