### ISSUE TITLE
npm appium install, keep getting unspecified error

### ISSUE THREAD

**Issue by UdayaLakmal** [npm/npm#7070]
In ubuntu 13.10
When try to install appium with brew
after install node
with 'npm install -g appium'
keep getting error

```
npm ERR! Linux 3.11.0-26-generic
npm ERR! argv "node" "/home/lakmal/.linuxbrew/bin/npm" "install" "-g" "appium"
npm ERR! node v0.10.33
npm ERR! npm  v2.1.8

npm ERR! Uncaught, unspecified "error" event.
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>
\
> ws@0.4.32 install /home/lakmal/npm/lib/node_modules/appium/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/home/lakmal/npm/lib/node_modules/appium/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory `/home/lakmal/npm/lib/node_modules/appium/node_modules/ws/build'

> ws@0.4.31 install /home/lakmal/npm/lib/node_modules/appium/node_modules/socket.io/node_modules/engine.io/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/home/lakmal/npm/lib/node_modules/appium/node_modules/socket.io/node_modules/engine.io/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory `/home/lakmal/npm/lib/node_modules/appium/node_modules/socket.io/node_modules/engine.io/node_modules/ws/build'
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"0.10.33","npm":"2.1.8"})
npm ERR! Linux 3.11.0-26-generic
npm ERR! argv "node" "/home/lakmal/.linuxbrew/bin/npm" "install" "-g" "appium"
npm ERR! node v0.10.33
npm ERR! npm  v2.1.8

npm ERR! Uncaught, unspecified "error" event.
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"0.10.33","npm":"2.1.8"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"0.10.33","npm":"2.1.8"})
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"0.10.33","npm":"2.1.8"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"0.10.33","npm":"2.1.8"})

npm ERR! Please include the following file with any support request:
npm ERR!     /home/lakmal/npm-debug.log 
```

This is the npm-debug.log
https://gist.github.com/UdauaLakmal/981d8666bb7c92b15bdb

**Comment by smikes** [comment]
Next time could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

You are running `npm` version 2.1.8.  Could you please try upgrading to the latest version, 2.1.17?

To update npm, run `npm -g install npm@latest`

For some Linux distributions (Debian/Ubuntu and RedHat/CentOS), the latest node version provided by the distribution may lag behind the stable version. [Here are instructions from NodeSource](https://github.com/nodesource/distributions) on getting the latest node.

Thanks!

**Comment by othiym23** [comment]
This is probably a bug, but it's hard to say where, because all of the modules mentioned in the stacktrace containing the error output are just passing along a more generic error emitted somewhere in the depths of Node's stream implementation. Does this happen every time you install Appium? What distribution (and what version of that distribution) of Linux are you running? Does the error recur if you use a version of Node not installed via `linuxbrew`?

**Comment by othiym23** [comment]
So far, all of the incidences of `Uncaught, unspecified "error" event` that I've seen have been on Linux, so my current hypothesis is that there's something happening with either file or SSL streams at the Node or libuv layer that's triggering a bug in `fs-write-stream-atomic` (or possibly exercising a bug in Node itself). I still need a reliable way to reproduce this, though.

**Comment by jasonliu0704** [comment]
I am using ubuntu and I think the bug might has something to do with the name conflict in ubuntu for node since there is another node package existing in ubuntu. So I uninstall the node and nodejs package and install node-legacy and problem fixed. 
sudo apt-get --purge remove node
sudo apt-get --purge remove nodejs-legacy
sudo apt-get --purge remove nodejs
sudo apt-get install nodejs-legacy
