### ISSUE TITLE
What are the rules for keywords in package.json?

### ISSUE THREAD

**Issue by trusktr** [npm/npm#7072]
Can they contain spaces and symbols? e.g., Are any of the following keywords invalid and will be rejected by npmjs.org?

```js
{
  "keywords": [
    "foo",
    "foo bar",
    "foo.bar",
    "foo-bar",
    "foo 'bar baz",
    "foo!",
    "@#$%"
  ],
}
```

**Comment by sindresorhus** [comment]
Would probably be smart to recommend (enforce?) the same rules as for the `name` field though, so users don't go wild.

**Comment by trusktr** [comment]
Yeah, because currently the keywords "GUI" and "gui" yield different results, and the results for "GUI" (or any keyword with a capital letter) are completely wrong because even though there are packages with the capitalized keyword, there are 0 results.

**Comment by trusktr** [comment]
https://github.com/npm/npm/issues/7088

**Comment by sindresorhus** [comment]
I think keywords should be case-insensitive or even better, normalized to lowercase when published. It doesn't make sense the separate `GUI` and `gui`.

**Comment by smikes** [comment]
Thanks, I didn't know about that. -1 to -0 then.


The code that needs to know about how to normalize keywords (down casing, stemming, Unicode normalization…) is probably more tightly coupled to the search  implementation than to npm; but it has to live somewhere.

**Comment by trusktr** [comment]
Hey guys, if any ideas, post here: https://github.com/npm/newww/issues/501 :D

**Comment by sholladay** [comment]
Given that the `newww` repo no longer exists, I think this should be reopened.

I'm still wondering what is valid, what is not, who enforces it, what kind of normalizations take place, etc. It appears I can use multi-word keywords like `'foo bar'` and I'm trying to figure out if this is reasonable or if it will bite me later when on search engines or for tooling that inspects the registry.

**Comment by sindresorhus** [comment]
@iarna Can you reopen this?

**Comment by legodude17** [comment]
@sindresorhus is this for transforming that in `normalize-package-json` or changing the registry search? Because those go in different places.

**Comment by sindresorhus** [comment]
@legodude17 This is first and foremost about documentation.

**Comment by legodude17** [comment]
@sindresorhus So this is about documenting what is allowed and not allowed in the `keywords` section? Did I understand this correctly?

**Comment by sindresorhus** [comment]
Yes, and then enforcing it in code.

**Comment by ashleygwilliams** [comment]
hey all! i can reopen this tho i am not certain that this is necessarily the correct place to do it? from what i have read the action item here is to properly document what is allowed in the `keywords` attr and what (if any) transforms occur on the contents of `keywords`. these keywords are fundamentally a registry concern so i believe putting this issue there is the best move. the website simply displays them. thoughts on that? if we like that i can file over there for us or one of ya'll can! lemme know :)

**Comment by ashleygwilliams** [comment]
oh whoops, link to the registry repo is https://github.com/npm/registry

**Comment by ashleygwilliams** [comment]
also just to reiterate, `package.json` is not ever edited, but the registry stores a thing called a `doc.json` which is heavily informed by the `package.json`, though there are transforms that occur. if there is worry about those transforms, filing an issue on https://github.com/npm/normalize-package-data is the right place for that, though a more general convo about that might make more sense in the registry repo also!

**Comment by iarna** [comment]
@sindresorhus @sholladay For completeness, the web team's public repo is: https://github.com/npm/www

https://github.com/npm/newww/issues/501 actually does still exist (the repo is just private now). For reference, its content is here: 
[neww#501.pdf](https://github.com/npm/npm/files/874271/neww.501.pdf)

What I'd like to see, if you all want to move this forward, is a new issue [in RFC form](http://blog.npmjs.org/post/153881413635/some-notes-on-rfcs). As you all know, currently the field is entirely unregulated. You can put literally anything there. There aren't even length limits. (Which is... not great. =D) There may be some registry-side limits that come out of implementation, but I don't know. We _have_ had some discussion internally recently around using this field more so this'd be a good time to talk about it.
