### ISSUE TITLE
"invalid config Tag must not be a SemVer range" should be an error, not a WARN

### ISSUE THREAD

**Issue by othiym23** [npm/npm#7075]
In other words, it should cause an early failure rather than publishing without the tag. See https://github.com/npm/npm/issues/6837#issuecomment-68866411 for context.

/cc @smikes

**Comment by KenanY** [comment]
Fixed by https://github.com/npm/npm/pull/7099?

**Comment by othiym23** [comment]
Indeed, fixed by 4ef1412d0061239da2b1c4460ed6db37cc9ded27. Thanks, @KenanY!
