### ISSUE TITLE
NPM still outputting things when piped to /dev/null

### ISSUE THREAD

**Issue by mihaiscurtucb** [npm/npm#7080]
I'm not 100% sure this is a `npm` issue, but when I'm running `sudo npm i -g bower > /dev/null` in a `Vagrant` provisioning script, all the request output is sent to `stdout`. I'm using OSX on my host, and Ubuntu 14.04 on the guest.

I've tried piping to a file just to test, and all that's put in the file is what's below. All the requests are still output to `stdout`

```
$ cat log
/usr/local/bin/bower -> /usr/local/lib/node_modules/bower/bin/bower
bower@1.3.12 /usr/local/lib/node_modules/bower
├── is-root@1.0.0
├── junk@1.0.0
├── stringify-object@1.0.0
├── which@1.0.8
├── abbrev@1.0.5
├── chmodr@0.1.0
├── osenv@0.1.0
├── archy@0.0.2
├── opn@1.0.1
├── rimraf@2.2.8
├── bower-logger@0.2.2
├── lru-cache@2.5.0
├── bower-endpoint-parser@0.2.2
├── graceful-fs@3.0.5
├── lockfile@1.0.0
├── nopt@3.0.1
├── retry@0.6.0
├── tmp@0.0.23
├── q@1.0.1
├── semver@2.3.2
├── fstream@1.0.3 (inherits@2.0.1)
├── mkdirp@0.5.0 (minimist@0.0.8)
├── request-progress@0.3.0 (throttleit@0.0.2)
├── bower-json@0.4.0 (intersect@0.0.3, deep-extend@0.2.11, graceful-fs@2.0.3)
├── shell-quote@1.4.2 (array-filter@0.0.1, array-reduce@0.0.0, array-map@0.0.0, jsonify@0.0.0)
├── chalk@0.5.0 (escape-string-regexp@1.0.2, ansi-styles@1.1.0, supports-color@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)
├── promptly@0.2.0 (read@1.0.5)
├── fstream-ignore@1.0.2 (inherits@2.0.1, minimatch@2.0.1)
├── p-throttler@0.1.0 (q@0.9.7)
├── bower-config@0.5.2 (osenv@0.0.3, graceful-fs@2.0.3, optimist@0.6.1)
├── tar-fs@0.5.2 (pump@0.3.5, tar-stream@0.4.7)
├── glob@4.0.6 (inherits@2.0.1, once@1.3.1, minimatch@1.0.0)
├── decompress-zip@0.0.8 (nopt@2.2.1, mkpath@0.1.0, touch@0.0.2, readable-stream@1.1.13, binary@0.3.0)
├── mout@0.9.1
├── request@2.42.0 (caseless@0.6.0, json-stringify-safe@5.0.0, aws-sign2@0.5.0, forever-agent@0.5.2, stringstream@0.0.4, oauth-sign@0.4.0, tunnel-agent@0.4.0, qs@1.2.2, node-uuid@1.4.2, mime-types@1.0.2, tough-cookie@0.12.1, bl@0.9.3, form-data@0.1.4, http-signature@0.10.1, hawk@1.1.1)
├── bower-registry-client@0.2.2 (graceful-fs@2.0.3, request-replay@0.2.0, lru-cache@2.3.1, async@0.2.10, mkdirp@0.3.5, request@2.27.0)
├── cardinal@0.4.0 (redeyed@0.4.4)
├── update-notifier@0.2.0 (semver-diff@0.1.0, string-length@0.1.2, latest-version@0.2.0, configstore@0.3.2)
├── handlebars@2.0.0 (optimist@0.3.7, uglify-js@2.3.6)
├── inquirer@0.7.1 (figures@1.3.5, mute-stream@0.0.4, through@2.3.6, lodash@2.4.1, rx@2.3.22, readline2@0.1.0, cli-color@0.3.2)
└── insight@0.4.3 (object-assign@1.0.0, async@0.9.0, chalk@0.5.1, os-name@1.0.1, lodash.debounce@2.4.1, tough-cookie@0.12.1, configstore@0.3.2, inquirer@0.6.0)
```

**Comment by mihaiscurtucb** [comment]
I ended up using --silent. Thanks for your response!

**Comment by othiym23** [comment]
Closing as resolved.

**Comment by Quagh** [comment]
I seem to have the same issue and `npm install --loglevel error > /dev/null` is currently the only that does mimics a `--silent` install.

Trying to do `npm install --loglevel silent` to install from `packages.json`

Tried these to make it only show errors or just nothing (replacing `…` with either `silent` or `error`):
- `npm install --loglevel …`
- `npm config set loglevel …`
- `npm config set loglevel … --global`
- `export npm_config_loglevel=…`

No dice. Also a Vagrant setup on an OS X host machine.

**Comment by smikes** [comment]
I'm not clear on what output you want to see from `npm`, but if you want nothing at all then the cleanest way to do that is `>/dev/null 2>/dev/null` which closes both output streams before the `node` process is `exec`ed.

Can you please create a new issue to discuss this further, so we do not keep sending email to the OP.

**Comment by Quagh** [comment]
Well I expect it to show me nothing but errors when I run it with `--loglevel error`, but it shows me all requests and stuff I don't want to see. Use case is an `npm install` through Capistrano, in which I need to check for errors (that I know when there's any output).

I'll create a new issue tomorrow if still necessary.
