### ISSUE TITLE
Is there any way to install socket.io from India, where Github website is blocked.

### ISSUE THREAD

**Issue by mithun146** [npm/npm#7084]
When trying to install socket.io using npm, am getting the following errors.
![pr82o](https://cloud.githubusercontent.com/assets/2862637/5647424/d1befc86-96ab-11e4-898e-9a30e8257299.png)
Recently our Indian government has blocked the access to github. So I do not currently have access to github from office. (Bsnl is the provider provider).

So do I've got any alternative installation method / installer where github is not accessible?

Please let me know if you need any more information

**Comment by smikes** [comment]
It looks like `socket.io` wants to download a specific version of node-XMLHttpRequest ; but you should be able to get by with changing that to a dependency on the `xmlhttprequest` npm module.

That will only get you so far, though; in general `npm` modules are free to depend on github repositories, and may do.

Is it possible to route around the block?  How are you able to comment on this issue (here on github) if you cannot access github?

**Comment by mithun146** [comment]
I am able to access git from home(where the internet provider is Airtel), but from office am unable to access github(BSNL is the provider (Owned by Government of India) ). 

Installing node-XMLHttpRequest manually will fix the above errors?  I mean by manually installing the dependencies will fix the errors?

**Comment by smikes** [comment]
> Installing node-XMLHttpRequest manually will fix the above errors? I mean by manually installing the dependencies will fix the errors?

No.  What I am saying is, you need to fetch the package for socket.io, manually untar it, edit its package.json so its dependencies do not involve github (where possible), and then try an `npm install`.

It would be simpler to set up a VPN/remote login to your home computer so you can access github via the other provider.

**Comment by othiym23** [comment]
Another solution would be to lobby the socket.io maintainers to stop using GitHub dependencies on their packages (which is probably a good idea for a large, popular package like socket.io anyway). From the stories about the ban, it looks like GitHub may be coming back soon, though, so while doing what @smikes prescribes is a laborious workaround, it may only be required for a short while. Either way, good luck, and I'm sorry you're having to deal with this hassle.

**Comment by 3rd-Eden** [comment]
It's a known issue: Automattic/engine.io-client#358

**Comment by smikes** [comment]
Is this still a problem for you?

I note that the issue above has still not been resolved on the engine.io-client project, so I assume that the underlying problem still exists.  Have you been able to work around it at all?

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as this isn't really an issue with npm itself, and also we've provided some workarounds above. Good luck!
