### ISSUE TITLE
why i failed to install yeoman?

### ISSUE THREAD

**Issue by sunstudy** [npm/npm#7085]
the error message is as follows:

![](http://img.itc.cn/photo/j3zrk5CilDD.jpg)

**Comment by sindresorhus** [comment]
As the message says the `yeoman` CLI is deprecated (ages ago), use [`yo`](https://github.com/yeoman/yo/) instead: `npm install -g yo`.

**Comment by faiq** [comment]
Also @sunstudy would you please mind closing the issue? This isn't really a npm project issue, it would be greatly appreciated. thanks

**Comment by sunstudy** [comment]
@faiq done
