### ISSUE TITLE
npm module installation constantly aborting

### ISSUE THREAD

**Issue by dokuboyejo** [npm/npm#7086]
Hi All,

I normally work on npm using a window machine with no major issue so far. I recently have a requirement to have it used on Debian wheezy. It appears most time I attempt to install a module the process abruptly terminate as discussed at http://stackoverflow.com/questions/27813234/npm-module-installation-constantly-aborting. Only few times have I gotten a mode to install.
Any assistance on this would be appreciated.
My node version is 0.10.35 and npm version is 1.4.28

**Comment by smikes** [comment]
I posted this on SO as well - briefly, though, you should update your `npm` to the latest with

`sudo npm install -g npm@latest`

If you get a stack trace or npm-debug.log, please upload it to https://gist.github.com/ and post the link here.

**Comment by dokuboyejo** [comment]
Thanks Smikes.
I did as suggested and got below. Unfortunately the npm-debug.log file wasn't generated for the install request.

sudo npm -g install npm@latest
[sudo] password for dokuboyejo:
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
npm WARN unmet dependency /usr/local/lib/node_modules/bower/node_modules/bower-config requires graceful-fs@'~2.0.0' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/bower/node_modules/graceful-fs,
npm WARN unmet dependency which is version 3.0.5
npm WARN unmet dependency /usr/local/lib/node_modules/bower/node_modules/bower-config requires osenv@'0.0.3' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/bower/node_modules/osenv,
npm WARN unmet dependency which is version 0.1.0
npm WARN unmet dependency /usr/local/lib/node_modules/bower/node_modules/bower-json requires graceful-fs@'~2.0.0' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/bower/node_modules/graceful-fs,
npm WARN unmet dependency which is version 3.0.5
npm WARN unmet dependency /usr/local/lib/node_modules/bower/node_modules/bower-registry-client requires graceful-fs@'~2.0.0' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/bower/node_modules/graceful-fs,
npm WARN unmet dependency which is version 3.0.5
npm WARN unmet dependency /usr/local/lib/node_modules/bower/node_modules/bower-registry-client requires lru-cache@'~2.3.0' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/bower/node_modules/lru-cache,
npm WARN unmet dependency which is version 2.5.0
npm WARN unmet dependency /usr/local/lib/node_modules/bower/node_modules/bower-registry-client requires request@'~2.27.0' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/bower/node_modules/request,
npm WARN unmet dependency which is version 2.42.0
npm WARN unmet dependency /usr/local/lib/node_modules/bower/node_modules/bower-registry-client requires mkdirp@'~0.3.5' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/bower/node_modules/mkdirp,
npm WARN unmet dependency which is version 0.5.0
npm WARN unmet dependency /usr/local/lib/node_modules/bower/node_modules/decompress-zip requires nopt@'~2.2.0' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/bower/node_modules/nopt,
npm WARN unmet dependency which is version 3.0.1
npm WARN unmet dependency /usr/local/lib/node_modules/bower/node_modules/insight requires chalk@'^0.5.1' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/bower/node_modules/chalk,
npm WARN unmet dependency which is version 0.5.0
npm WARN unmet dependency /usr/local/lib/node_modules/bower/node_modules/insight requires inquirer@'^0.6.0' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/bower/node_modules/inquirer,
npm WARN unmet dependency which is version 0.7.1
npm WARN unmet dependency /usr/local/lib/node_modules/bower/node_modules/p-throttler requires q@'~0.9.2' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/bower/node_modules/q,
npm WARN unmet dependency which is version 1.0.1
npm@2.1.17 /usr/local/lib/node_modules/npm
[ 10.21 dokuboyejo ] ~ $ npm

**Comment by smikes** [comment]
It looks like you have run `npm update -g` in the past.  This tends to break all your globally installed packages ; to fix it, you need to blow away your `/usr/local/lib/node_modules` and reinstall node:

```
sudo -s
rm -fr /usr/local/lib/node_modules
apt-get remove nodejs nodejs-legacy
apt-get install nodejs nodejs-legacy
npm install -g npm@latest
```

**Comment by dokuboyejo** [comment]
Thanks smikes.
I eventually resulted to building node from source again with a version (node: v0.11.12, npm: 1.4.3 and updated to 2.1.18) higher than what I am currently using (node: v0.10.35, npm: 1.4.18). My guess is n
The procedure has been posted on SO:http://tinyurl.com/oj85ame

**Comment by othiym23** [comment]
Closing as resolved / as resolved as it's gonna get when architecture issues are in the mix. Let us know if the trail points back to npm once you've got your build issues worked out.
