### ISSUE TITLE
keywords with capital letters don't work.

### ISSUE THREAD

**Issue by trusktr** [npm/npm#7088]
For example, the package [robotjs](https://www.npmjs.com/package/robotjs) has the keyword `GUI` but if you click on the `GUI` keyword, you are taken to a page with [no results](https://www.npmjs.com/browse/keyword/GUI).

**Comment by KenanY** [comment]
This seems like an issue with npm-the-website, not `npm`-the-CLI-tool. This is the issue tracker for the latter. Website issues should be filed at [npm/newww](https://github.com/npm/newww).

Looks like you've already opened an issue for this in fact! https://github.com/npm/newww/issues/501
