### ISSUE TITLE
npm search redirected to a file produces square output‽

### ISSUE THREAD

**Issue by rektide** [npm/npm#7089]
Why is this still so catastrophically horribly unusable‽ :broken_heart: every day npm! You're killing me! :no_good:

Problem: `npm search` redirected to a file or piped creates square output. Often very wide square output. `npm search express` was 729 characters wide, `npm search sugar` was 406 characters wide. I'd guess that 90% of entries top out at 180 chars in either case.

**Comment by othiym23** [comment]
`npm search` was designed at the beginning of npm's life, when there were a few hundred Node modules and there was no way for the output to get very big. 2010 was a different, more innocent time. I agree that redirected output should either not be tabularized or description fields should be truncated at some reasonable max length to keep the tabularized output from being unusable. A patch to add this would be very welcome (see #7090 for context on why the core team might not get to this super soon).

@rektide, given that you've now filed two two issues on redirected `npm search` output, it would be useful for you to add a short comment on this issue (or #7090) on how you're using redirected output to help provide context for the changes you'd like to see.

**Comment by smikes** [comment]
`npm-kludge-search -r fast` will produce fixed-column output.  It does not attempt to query the terminal for a max width, which is what I think was triggering your problem on redirection.

You can try it out with

```
npm install -g npm-kludge-search@latest
[ wait 3-4 minutes to build index ]
npm-kludge-search -r fast express
```

Please file issues / PRs at <https://github.com/smikes/npm-kludge-search>

**Comment by smikes** [comment]
I think I found the explicit culprit:

```
 cols = !tty.isatty(stdout.fd) ? Infinity : process.stdout.getWindowSize()[0]
```

Default max width is Infinity when output is redirected.

**Comment by timoxley** [comment]
@smikes but what would alternative logic for this look like?

**Comment by smikes** [comment]
No idea; but redirected output is not always intended to be machine-readable, so it's going to depend on what OP's needs are.  The JSON output will almost always be more useful for a tool to work with.

**Comment by timoxley** [comment]
> The JSON output will almost always be more useful for a tool to work with.

Agree.
