### ISSUE TITLE
npm ERR! Error: UNKNOWN, symlink '../user-home/cli.js'

### ISSUE THREAD

**Issue by joshbnntt** [npm/npm#7094]
tried a sudo npm install and this error came up:

npm ERR! Error: UNKNOWN, symlink '../user-home/cli.js'

npm ERR! System Linux 3.13.0-36-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "gulp" "gulp-sass" "gulp-autoprefixer" "--save-dev"
npm ERR! cwd /home/vagrant/Sites/csproj
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! path ../user-home/cli.js
npm ERR! code UNKNOWN
npm ERR! errno -1
npm ERR! not ok code 0

**Comment by joshbnntt** [comment]
used --no-bin-links and it worked

**Comment by portaseb** [comment]
Thanks joshbnntt, works for me !

**Comment by blackfyre** [comment]
Is there a more permanent solution for this?

**Comment by arnoldpistorius** [comment]
You saved my ass, thanks!

**Comment by wtcobuch** [comment]
it worked for me thank you !

**Comment by geditdk** [comment]
Thanks. Using this allows you to use npm via a Docker share on Windows.

**Comment by maxpou** [comment]
:+1: Thanks joshbnntt ! 

It's work for me :
```sh
npm install express --no-bin-links
```

**Comment by rdsubhas** [comment]
Just another thing to watch out for: Make sure Virtualbox Extension Pack is installed (some people miss this and it produces the same symlink error outlined above)

**Comment by dmfarcas** [comment]
--no-bin-links worked on BashOnWindows :)

**Comment by atularvind** [comment]
Many Thanks @joshbnntt! worked for me!

**Comment by sxlijin** [comment]
Had to use this on a CIFS mount in an Arch VM (VBox 5.1.x, latest ext. pack) - thanks!
