### ISSUE TITLE
Error Installing Atom Package on Windows 8.1 "npm ERR! Error: Command failed: "

### ISSUE THREAD

**Issue by GGillan** [npm/npm#7100]
Here is the entire log, which contains a note advising that the issue posting be made for npm:
______________________

Installing “Sublime-Style-Column-Selection@1.1.3” failed.Hide output…

npm http GET https://registry.npmjs.org/emissary
npm http 200 https://registry.npmjs.org/emissary
npm http GET https://registry.npmjs.org/emissary/-/emissary-1.3.1.tgz
npm http 200 https://registry.npmjs.org/emissary/-/emissary-1.3.1.tgz
npm http GET https://registry.npmjs.org/mixto
npm http GET https://registry.npmjs.org/underscore-plus
npm http GET https://registry.npmjs.org/property-accessors
npm http 200 https://registry.npmjs.org/mixto
npm http 200 https://registry.npmjs.org/property-accessors
npm http GET https://registry.npmjs.org/mixto/-/mixto-1.0.0.tgz
npm http GET https://registry.npmjs.org/property-accessors/-/property-accessors-1.1.0.tgz
npm http 200 https://registry.npmjs.org/underscore-plus
npm http GET https://registry.npmjs.org/underscore-plus/-/underscore-plus-1.6.6.tgz
npm http 200 https://registry.npmjs.org/mixto/-/mixto-1.0.0.tgz
npm http 200 https://registry.npmjs.org/property-accessors/-/property-accessors-1.1.0.tgz
npm ERR! git clone https://github.com/Benvie/harmony-collections.git 
npm http 200 https://registry.npmjs.org/underscore-plus/-/underscore-plus-1.6.6.tgz
npm ERR! Error: Command failed: 
npm ERR!     at ChildProcess.exithandler (child_process.js:648:15)
npm ERR!     at ChildProcess.emit (events.js:98:17)
npm ERR!     at maybeClose (child_process.js:756:16)
npm ERR!     at Process.ChildProcess._handle.onexit (child_process.js:823:5)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "c:\\Users\\George\\AppData\\Local\\atom\\app-0.169.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "c:\\Users\\George\\AppData\\Local\\atom\\app-0.169.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\Users\\George\\AppData\\Local\\atom\\app-0.169.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "c:\\Users\\George\\.atom\\.apmrc" "install" "C:\\Users\\George\\AppData\\Local\\Temp\\d-11508-8052-1qh51th\\package.tgz" "--target=0.20.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! cwd C:\Users\George\AppData\Local\Temp\apm-install-dir-11508-8052-1g96iav
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.4
npm ERR! code -1073741515
npm

**Comment by smikes** [comment]
Thanks for the bug report.  Unfortunately, although `atom` bundles a version of `npm`, it is an old and unsupported version.  If you were running `npm` standalone, I would advise you to follow the windows upgrade instructions here: <https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows>

I don't know if doing that would break `apm`, however.  Could you please open an issue with the `atom` team?  If they do not want to update the version of `npm` they are shipping, they could at least modify the error message to direct you to the correct issue tracker, <https://github.com/atom/atom/issues>

**Comment by GGillan** [comment]
Hi Sam,

Thanks for the quick reply. I will open an issue for this under Atom. Do
you want me to close the issue for npm, or is that something that you do?

Regards,
George

**Comment by GGillan** [comment]
Sam, I am closing this issue. I have opened the matter as issue #4931 for Atom.

Thank you for your help.
