### ISSUE TITLE
Why is "npm ERR! No version provided in package.json" an error?

### ISSUE THREAD

**Issue by matthew-andrews** [npm/npm#7105]
```
mandrews@MATT ~/sandboxes/test (master) $ npm install Financial-Times/next-express
npm WARN package.json @ No description
npm WARN package.json @ No repository field.
npm WARN package.json @ No README data
npm ERR! addLocal Could not install /var/folders/yf/r3mmqwgj3gsc78228lhylkyw0000gp/T/npm-23770-b0c557cd/1420833870955-0.9492712013889104/1333f21b89aee126710b5dbc5d726c131f4923e6
npm ERR! addLocal Could not install /var/folders/yf/r3mmqwgj3gsc78228lhylkyw0000gp/T/npm-23770-b0c557cd/1420833872531-0.6113767258357257/1333f21b89aee126710b5dbc5d726c131f4923e6
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/opt/boxen/nodenv/versions/v0.10/bin/npm" "install" "Financial-Times/next-express"
npm ERR! node v0.10.33
npm ERR! npm  v2.1.14

npm ERR! No version provided in package.json
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mandrews/sandboxes/test/npm-debug.log
```

It seems to be only used in assertions that the `version` parameter exists or in verbose logs… never for anything functional during the install process (as far as I can see).

https://github.com/npm/npm/blob/7f6557ff317469ee4a87c542ff9a991e74ce9f38/lib/cache/add-local.js#L69-77
https://github.com/npm/npm/blob/7f6557ff317469ee4a87c542ff9a991e74ce9f38/lib/cache/cached-package-root.js#L11

For other package managers (for example bower) the `version` property in their equivalents of `package.json` are entirely optional, as  they can use a version control system's tags instead.

Also requiring a `version` when installing from a branch is particularly confusing (and arguably meaningless) because it implies that the version of the code you have downloaded is at that particular version (ie. matches the tag) when in reality it can be quite different.

Would it be possible to remove the requirement to always have a version committed into the `package.json` file and instead only enforce it at the `npm publish` stage?

It would help us achieve the following workflow:-

- Create a git tag via GitHub release or via git's CLI.
- When our CI provider runs tag builds, add the version in the git tag to the `package.json` file and `npm publish` it automatically for us.
(Allowing us to have a single, simple two-step workflow for all of the package managers we need to support)

**Comment by linclark** [comment]
It looks like you created a [module](https://www.npmjs.com/package/npm-prepublish) that achieves this :)

**Comment by matthew-andrews** [comment]
@linclark almost but not quite :disappointed:.  I still have to add a version parameter (set to `0.0.0`) https://github.com/Financial-Times/next-express/blob/master/package.json#L3.

**Comment by othiym23** [comment]
There are only two parameters in `package.json` that are absolutely required – `name` and `version`. Together they constitute the identity of a particular package – without both, you don't have an npm package, you have a JSON file with some useful metadata in it, because what you have can't be published, properly cached, or installed. This concept of package identity is deeply baked into npm, and is as close to unchangeable as any aspect of npm's design. Sorry!
