### ISSUE TITLE
Error: forbidden no tarball

### ISSUE THREAD

**Issue by lapanoid** [npm/npm#7111]
Hello I have such log 

```
npm publish react-infinite-scroll-webpack-0.0.1.tgz

npm ERR! publish Failed PUT 403
npm ERR! Error: forbidden no tarball in 0.0.1 version: react-infinite-scroll-webpack
npm ERR!     at RegClient.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:308:14)
npm ERR!     at Request._callback (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:246:65)
npm ERR!     at Request.self.callback (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\request.js:236:22)
npm ERR!     at Request.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\request.js:1142:14)
npm ERR!     at Request.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\request.js:1096:12)
npm ERR!     at IncomingMessage.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:944:16
npm ERR!     at process._tickCallback (node.js:442:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
```

what does it mean?

**Comment by smikes** [comment]
It sounds like `npm` is unable to produce a tar file to publish.

Could you please upload the **entire** npm-debug.log as a gist to <https://gist.github.com> and attach the link here.  Note the text at the bottom of the log:

>npm ERR! If you need help, you may report this entire log,
npm ERR! **including the npm and node versions**, at:

You have cut out the `npm` version.

**Comment by lapanoid** [comment]
https://gist.github.com/lapanoid/6b62d3d0ffb9dce6f1b0  - here my npm debug log
npm version is 
{ http_parser: '1.0',
  node: '0.10.35',
  v8: '3.14.5.9',
  ares: '1.9.0-DEV',
  uv: '0.10.30',
  zlib: '1.2.8',
  modules: '11',
  openssl: '1.0.1j',
  npm: '1.4.28',
  'react-infinite-scroll-webpack': '0.0.0' }

**Comment by smikes** [comment]
You're definitely doing the right thing with `npm publish` - at first I was concerned you were trying to build the tarball separately and then publish it, which does work, but is not preferred.

There have been a lot of improvements to npm since 1.4.28. Can you try updating your npm installation?

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

Thanks!

**Comment by smikes** [comment]
Is this still a problem for you?

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as abandoned.
