### ISSUE TITLE
npm update express -g

### ISSUE THREAD

**Issue by mike131** [npm/npm#7112]
I am trying to update express via npm using "npm update express -g"

The output I see in terminal is:
```
Mikes-MacBook-Pro:workspace mlee$ npm update express -g
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "update" "express" "-g"
npm ERR! node v0.10.30
npm ERR! npm  v2.1.14

npm ERR! Object.keys called on non-object
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "update" "express" "-g"
npm ERR! node v0.10.30
npm ERR! npm  v2.1.14

---- REPEATS ~ 100 MORE TIMES -----

npm ERR! Object.keys called on non-object
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>
npm ERR! Darwin 14.0.0


npm ERR! Object.keys called on non-object
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mlee/workspace/npm-debug.log
```

My npm-debug.log shows:
```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'update', 'express', '-g' ]
2 info using npm@2.1.14
3 info using node@v0.10.30
4 verbose type called_on_non_object
5 verbose stack TypeError: Object.keys called on non-object
5 verbose stack     at Function.keys (native)
5 verbose stack     at unmarkExtraneous (/usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:362:10)
5 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:137:5
5 verbose stack     at next (/usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:185:14)
5 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:169:14
5 verbose stack     at Object.oncomplete (evalmachine.<anonymous>:107:15)
6 verbose cwd /Users/mlee/workspace
7 error Darwin 14.0.0
8 error argv "node" "/usr/local/bin/npm" "update" "express" "-g"
9 error node v0.10.30
10 error npm  v2.1.14
11 error Object.keys called on non-object
12 error If you need help, you may report this error at:
12 error     <http://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]
```

Any suggestions?

**Comment by KenanY** [comment]
This was fixed in `npm@2.1.6`. You should update by running

``` bash
$ npm install -g npm
```

Furthermore, I must warn you to not use `npm update -g`, it doesn't do what you think it does, and can easily lead to broken installations of modules.

**Comment by mike131** [comment]
Thanks @KenanY 
When I run 'npm install -g npm' I see that it installed npm 2.1.8

However, when i run npm -v I get 2.1.14 still. I am assuming that something is broken on my install then.

**Comment by KenanY** [comment]
Sounds like you might have two `npm`s installed?

**Comment by smikes** [comment]
> When I run 'npm install -g npm' I see that it installed npm 2.1.8

Where did it install to?  Can you try `npm -d install -g npm@latest` and upload the `npm-debug.log` as a gist <https://gist.github.com> ?

I am concerned about a couple of things; first, that `npm install -g npm` installed 2.1.8 (was it maybe 2.1.18?) and secondly, that it claimed to install successfully without updating the global `npm`.  Do you remember how you installed `node` -- from the Joyent installer at <https://nodejs.org/download/> or via `brew` or some other package manager?  Knowing that would make it easier to troubleshoot this problem.

**Comment by mike131** [comment]
Hi @smikes 

Yes, I did mean 2.1.18.

I believe I installed via https://nodejs.org/download/

After running npm -d install -g npm npm@latest, i did not get an npm-debug.log (in the directory I was in when i ran the command).

The command seemed to update my npm version. I now have 2.1.18 (even after restarting terminal).

**Comment by smikes** [comment]
So now you should be able to 

`npm install -g express@latest`

to get an up to date version of express.  As @KenanY said, don't run `npm update` -- it won't do what you expect.

**Comment by mike131** [comment]
Thank you @smikes and @KenanY
