### ISSUE TITLE
npm problem to run the angular js in windows xp 32 bit

### ISSUE THREAD

**Issue by bagwari** [npm/npm#7114]
i am getting the following log, please help
```
C:\node>npm start
npm ERR! Error: ENOENT, open 'C:\node\package.json'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 5.1.2600
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! cwd C:\node
npm ERR! node -v v0.10.35

npm ERR! npm -v 1.4.28
npm ERR! path C:\node\package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\node\npm-debug.log
npm ERR! not ok code 0
```

**Comment by KenanY** [comment]
@bagwari Does `C:\node\package.json` exist? It appears as though you are running `npm start` in a directory without a `package.json`. `npm` has absolutely no idea what you want it to do when you run `npm start` unless you have a `package.json` which explicitly defines a `start` script.

Please see the docs for [`npm start`](https://docs.npmjs.com/cli/start) and [`scripts`](https://docs.npmjs.com/misc/scripts).

**Comment by smikes** [comment]
Is this still a problem for you?

As @KenanY says, `npm start` follows the instructions in the `start` script of a `package.json` file.  If you are following a tutorial or instruction script, please make sure that you are in the right directory, as `npm start` looks to the current directory for `package.json`

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as abandoned.
