### ISSUE TITLE
after installing with npm commands don't work 

### ISSUE THREAD

**Issue by materechm** [npm/npm#7116]
Every time I install something with npm and then run the command on the terminal the command does not work, even though the installation was successful

**Comment by linclark** [comment]
Are you working on a Mac/Unix computer? If so, you probably need to add the directory where npm is adding global commands to your environment's PATH variable.

1. Use `npm config get prefix` to find which directory is being used.
2. Open or create a `.profile` file in your home directory and add this line, replacing `<path from prefix command>` with the output from above:
```
 export PATH=<path from prefix command>/bin:$PATH
```
3. Back on the command line, update your system variables:
```
 source ~/.profile
```

**Comment by materechm** [comment]
thanks, works now
