### ISSUE TITLE
Scripts in package.json fail on Windows 8.1

### ISSUE THREAD

**Issue by peacememories** [npm/npm#7123]
Whenever node tries to run a command from the "scripts" section in a package.json, it fails with the same `ENOENT` and `Exit status -1` error messages.
I first encountered this while trying to install packages that depend on node-gyp, but the following example shows that the problem has nothing to do with the command that is being called.
```json
#package.json
{
  "scripts": {
    "start": "node -e console.log('test')"
  }
}
```

```
#npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start',
1 verbose cli   '--verbose' ]
2 info using npm@1.4.28
3 info using node@v0.10.35
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info prestart @
7 info start @
8 verbose unsafe-perm in lifecycle true
9 info @ Failed to exec start script
10 error @ start: `node -e console.log('test')`
10 error spawn ENOENT
11 error Failed at the @ start script.
11 error This is most likely a problem with the  package,
11 error not with npm itself.
11 error Tell the author that this fails on your system:
11 error     node -e console.log('test')
11 error You can get their info via:
11 error     npm owner ls
11 error There is likely additional logging output above.
12 error System Windows_NT 6.2.9200
13 error command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start" "--verbose"
14 error cwd D:\Users\gabriel\Documents\Projects\npmfailtest
15 error node -v v0.10.35
16 error npm -v 1.4.28
17 error syscall spawn
18 error code ELIFECYCLE
19 error errno ENOENT
20 verbose exit [ 1, true ]
```

The problem doesn't just affect scripts manually specified in `package.json` but also those automatically set by npm (like `"preinstall": "node-gyp rebuild"`)

Specs:
Windows 8.1 x64
Node v0.10.35
Npm 1.4.28

Tested with:
* ws
* jsdom
* snippet from above

**Comment by smikes** [comment]
What happens if you prefix the command with `cmd /c ` -- i.e., `cmd /c node -e console.log('test')` ?

Do all commands fail in lifecycle scripts (such as `start`) or just ones that depend on node.exe?

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.4.28. Can you try updating your npm installation?

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows

**Comment by peacememories** [comment]
I just upgraded my npm version to 2.1.18, but this doesn't change any of the errors.
Prepending `cmd /c` to the script commands doesn't change anything either (the names in the error messages change, of course).
I can't for sure say if every command would fail, but none I've tried so far have succeeded.
I've tried:
* `echo hi`
* `exit 0`
* `node -e console.log('test')`
* `node.exe`
* `cmd.exe`

And after your answer I've tried all of them again wrapped in a cmd call (`cmd` as well as `cmd.exe`).
Since I don't know exactly in what way the scripts get dispatched I am not sure if .bat syntax *should* even work, but I there are also some very simple executables in those tests.
From what I can gather it seems like something is going wrong very early in the script execution. I would like to supply stacktraces of the error, but I can't seem to find a way to obtain them.

**Comment by othiym23** [comment]
What about if you update to `npm@2.2.0` and see what `npm run env` says is your `%PATH%`? It sounds like something is way screwed up with said path, especially if it can't run `cmd.exe`. Also, you might want to see if `%COMSPEC%` is set, and if its setting makes any sense. `npm@2.3.0` includes a tweak to make it use `%COMSPEC%` explicitly, if it's set, so you might try installing `npm@next` as well.

(For what it's worth, I'm running Windows 8.1, stock `cmd.exe`, and Node 0.10.35 and `npm@2.3.01 and have no problems running scripts, so this is probably a configuration issue on your machine.)

**Comment by peacememories** [comment]
Seems I've found the culprit. A while ago, uninstalling some software (don't remember what, exactly) completely deleted my path and, guess what, I forgot to add the system32 dir back in there. explains a lot, really. Sorry to have bothered you with this, works now. (Comspec was still correct, btw, so updating to 2.3.0 would have probably solved the errors too)
