### ISSUE TITLE
Unable to install 'git-provider' library using npm

### ISSUE THREAD

**Issue by tinwatchman** [npm/npm#7129]
I'm getting this error when attempting to install this particular library on Windows (please note that, for security purposes, I've replaced the exact path to my user folder with {USER_PATH}):
```
npm WARN package.json GitProviderTest@1.0.0 No repository field.
npm WARN package.json GitProviderTest@1.0.0 No README data
npm WARN `git config --get remote.origin.url` returned wrong result (git://githu
b.com/darvin/github.git)
npm ERR! git clone git://github.com/darvin/github.git Cloning into bare reposito
ry '{USER_PATH}\AppData\Roaming\npm-cache\_git-remotes\git-github-com-darvin
-github-git-6a5e13a0'...
npm ERR! git clone git://github.com/darvin/github.git fatal: unable to connect t
o github.com:
npm ERR! git clone git://github.com/darvin/github.git github.com[0: 192.30.252.1
28]: errno=No error
npm ERR! Error: Command failed: Cloning into bare repository '{USER_PATH}\Ap
pData\Roaming\npm-cache\_git-remotes\git-github-com-darvin-github-git-6a5e13a0'.
..
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.128]: errno=No error
npm ERR!
npm ERR!
npm ERR!     at ChildProcess.exithandler (child_process.js:648:15)
npm ERR!     at ChildProcess.emit (events.js:98:17)
npm ERR!     at maybeClose (child_process.js:756:16)
npm ERR!     at Process.ChildProcess._handle.onexit (child_process.js:823:5)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodej
s\\node_modules\\npm\\bin\\npm-cli.js" "install" "git-provider"
npm ERR! cwd {USER_PATH}\git\jon\js\GitProvider
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code 128
npm ERR! not ok code 0
```
I'm able to install other libraries. There just seems to be a problem with this one in particular. Any suggestions?

**Comment by smikes** [comment]
This doesn't look like an `npm` issue - the problem is a failure to connect to github.  However, there have been some changes to `npm` since the version you have -- 1.4.28 was distributed with node 0.10.33 but is quite old by now. Can you try updating your npm installation?

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

Thanks!

**Comment by smikes** [comment]
Is this still a problem for you?

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as abandoned. If you ever return to this issue, try upgrading npm to `npm@latest`, as we've put a bunch of work into improving our Git support, and I believe many of these issues have been fixed.
