### ISSUE TITLE
Getting UNABLE_TO_VERIFY_LEAF_SIGNATURE while testing websocket over secure websocket for thor

### ISSUE THREAD

**Issue by arundaya** [npm/npm#7135]
I am testing secured websocket protocol through thor tool. I have installed an echo server on a weblogic domain and trying to push websocket requests load from thor. I am able to test it by non-secure websocket protocol. But while trying secure websocket I am getting the below error:
thor -A 100 wss://192.168.19.13:7002/Echo/echo

Thor:                                                  version: 1.0.0

God of Thunder, son of Odin and smasher of WebSockets!

Thou shall:
- Spawn 48 workers.
- Create all the concurrent/parallel connections.
- Smash 100 connections with the mighty Mjölnir.

The answers you seek shall be yours, once I claim what is mine.

Connecting to wss://192.168.19.13:7002/Echo/echo

                     
Online               561 milliseconds
Time taken           561 milliseconds
Connected            0
Disconnected         0
Failed               100
Total transferred    0B
Total received       0B

Durations (ms):

                     min     mean     stddev  median max    
Handshaking          NaN     NaN         NaN     NaN NaN    
Latency              NaN     NaN         NaN     NaN NaN    

Percentile (ms):

                      50%     66%     75%     80%     90%     95%     98%     98%    100%   
Handshaking          NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN    
Latency              NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN    

Received errors:

100x                 UNABLE_TO_VERIFY_LEAF_SIGNATURE

Any suggestion?

**Comment by KenanY** [comment]
This does not appear to be an `npm` issue?

**Comment by arundaya** [comment]
I am not able to hit any wss url.. i have downloaded the thor as an npm package so raised the issue here.. Any help on it

**Comment by KenanY** [comment]
Sorry, but it might be difficult to get help with thor here on the `npm` issue tracker. Perhaps you should raise an issue with them?

**Comment by othiym23** [comment]
Indeed. Closing because this doesn't appear to be related to npm.
