### ISSUE TITLE
Object.keys called on non-object

### ISSUE THREAD

**Issue by festaans** [npm/npm#7145]
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'update', '-g', 'ionic' ]
2 info using npm@2.1.14
3 info using node@v0.10.34
4 verbose node symlink /usr/local/bin/node
5 silly mapToRegistry name ionic
6 silly mapToRegistry using default registry
7 silly mapToRegistry registry https://registry.npmjs.org/
8 silly mapToRegistry uri https://registry.npmjs.org/ionic
9 verbose request uri https://registry.npmjs.org/ionic
10 verbose request no auth needed
11 info attempt registry request try #1 at 14:40:35
12 verbose request id a01a1bb1466756ca
13 verbose etag "C8LIG89MUHA4Y2HJN5GOK7Y1Y"
14 http request GET https://registry.npmjs.org/ionic
15 verbose type called_on_non_object
16 verbose stack TypeError: Object.keys called on non-object
16 verbose stack     at Function.keys (native)
16 verbose stack     at unmarkExtraneous (/usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:362:10)
16 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:137:5
16 verbose stack     at next (/usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:185:14)
16 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:169:14
16 verbose stack     at Object.oncomplete (evalmachine.<anonymous>:108:15)
17 verbose cwd /Users/stvanvuuren
18 error Darwin 13.4.0
19 error argv "node" "/usr/local/bin/npm" "update" "-g" "ionic"
20 error node v0.10.34
21 error npm  v2.1.14
22 error Object.keys called on non-object
23 error If you need help, you may report this error at:
23 error     <http://github.com/npm/npm/issues>
24 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@festaans That bug was fixed in [`npm@2.1.16`](https://github.com/npm/npm/releases/tag/v2.1.16). You should [update](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-nix-osx-linux-etc).

**Comment by nathan7** [comment]
Closing this, seeing that the bug has been fixed already.
