### ISSUE TITLE
devDependencies do not warn when invalid

### ISSUE THREAD

**Issue by glenjamin** [npm/npm#7147]
``` sh
npm install rimraf@2.0 --save-dev
sed -i '.bak' 's/2.0/2.2/' package.json
npm ls # no errors
sed -i '.bak' 's/devD/d/' package.json
npm ls # npm ERR! invalid: rimraf@2.0.3
```

This seems to be loosely related to #4516 - after upgrading a devDependency, no-one can tell!

**Comment by othiym23** [comment]
> after upgrading a devDependency, no-one can tell!

Running `npm outdated --depth=0` will give you the scoop, but you're right, this should flag the package as invalid. @iarna, how does the `multi-stage` branch handle this? I'm trying to decide if this is something we should fix in `npm@2` or `npm@3`.
