### ISSUE TITLE
Proxy settings with "\" not supported on Mac OSX

### ISSUE THREAD

**Issue by KempfCreative** [npm/npm#7150]
I have worked with npm on Windows at my office and there was never any issues with setting my corporate proxy. This proxy has a domain, which must be resolved like this: `http://domain\password:username@proxy.address.com:9999`

In Windows, the proxy works when I escape the "\" as "%5C" like so: `http://domain%5Cpassword:username@proxy.address.com:9999`, but on OSX, that will not resolve the proxy properly. 
When I try to npm install, I get the following error: `npm ERR! network getaddrinfo ENOTFOUND proxy.address.com` 

I have tried various ways of encoding the "\" on OSX, but none of them work, and Googling this problem leads me to a bunch of dead ends. 

Are domain proxies not supported in OSX?

**Comment by smikes** [comment]
Can you use your web browser under OSX?  If so, it must have some way of specifying the proxy that does work.

The fetching of URLs is actually performed by the `request` component of `node`, not directly by `npm`.  Can you update your `node` installation?  You didn't say what you're running, but the latest stable is 0.10.35 at <https://nodejs.org/download> and you might also wish to try the new io.js version <https://iojs.org/>

**Comment by KempfCreative** [comment]
@smikes Yes I can use a web browser using a .pac file which is hosted by my company. This .pac file has the same proxy configuration, but it resolves the domain properly when I use it. E.G. the "\" stays as a "\" and doesn't get changed to a "/".

I will have to check on the version number of node. I'll get back to you about that, but still, it seems like the proxy is converting the characters.

**Comment by KempfCreative** [comment]
The version number was 0.10.0-pre for node. I have since upgraded to 0.10.35, but the issue is still present. 

My .npmrc looks like this:

`https-proxy=http://domain%5Cpassword:username@url:port
proxy=http://domain%5Cpassword:username@url:port
registry=http://registry.npmjs.org
strict-ssl=false`

**Comment by othiym23** [comment]
Hmm.... those look like NTLM credentials to me, and I have _no idea_ how that might be used with `request` on OS X. @smikes has the right idea here -- since we pass the proxy string off to `request` without transforming it, the `request` team might have the best pointers to get you unstuck. Be sure to let us know if they're able to help you, because I haven't seen this problem before, but I'm sure I'll see it again.

Sorry I don't have a better answer for you!

**Comment by othiym23** [comment]
Have you tried just using a double backslash instead of URLEncoding the backslash?

**Comment by othiym23** [comment]
And if that doesn't work, [`cntlm`](http://blog.hoachuck.biz/blog/2013/03/21/howto-set-cntlm-on-mac-os-x/) might be worth a shot.

**Comment by KempfCreative** [comment]
@othiym23 Thanks for the pointers. `cntlm` seems like it might be the way to go, but as this is an enterprise computer, that introduces a whole new world of pain. But I will investigate that if I get nowhere with default solutions.

I have tried the double backslash as well. It just escapes the first one, and converts the second, so that doesn't work.

I would really like to reach out to the `request` team, but I am not sure where I would open a ticket with them, and I don't want to start duplicating issues across projects and teams. Do you have any recommendations where I can open a ticket with that team, and then close this one out?

**Comment by othiym23** [comment]
@KempfCreative I think request/request is the correct repo to open proxy-related issues on. I'd leave this issue open until we collectively figure out what needs to happen both there and in npm to get this resolved. Once / if `request` is changed to support this use case, I'll still have to land the updated version in npm and ensure that everything still works.

**Comment by smikes** [comment]
A concrete URL: <https://github.com/request/request/issues>

**Comment by KempfCreative** [comment]
`request` ticket is open: [1377](https://github.com/request/request/issues/1377)

**Comment by nylen** [comment]
@othiym23 @smikes I think you can close this, we determined he can't ping the proxy URL either.

**Comment by othiym23** [comment]
Thanks, @nylen, I'll do that. @KempfCreative if you get things sorted out with your IT department and are still having issues with npm, feel free to leave a note here or open a new issue.
