### ISSUE TITLE
unpublish fails with "conflict Document update conflict"

### ISSUE THREAD

**Issue by 75lb** [npm/npm#7158]
oops, i published breaking changes with only a minor revision bump.. i published as `1.2.0` but it should have been `2.0.0`.. this means apps with dependency semvers like `^1.0` will all break..  so, i desperately needed to unpublish!

i ran this: 
`$ npm unpublish handbrake-js@1.2.0`

but got this error: 
```
npm ERR! Darwin 14.0.0npm ERR! argv "node" "/usr/local/bin/npm" "unpublish" "handbrake-js@1.2.0"
npm ERR! node v0.10.35
npm ERR! npm  v2.1.14
npm ERR! code E409
npm ERR! conflict Document update conflict.: handbrake-js,-,handbrake-js-1.2.0.tgz,-rev,118-49f3008ea09313b178ad9137dafa2f9d
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Lloyd/Documents/75lb/handbrake-js/npm-debug.log
```

the output from `$ npm view handbrake-js` now looks like this: 
https://gist.github.com/75lb/b9a0f757794a94704bc4

after bumping to `2.0.0` i was able to `npm publish` without errors..

**Comment by othiym23** [comment]
Even though you got that error output, the unpublish worked:

```
% npm i handbrake-js@1.2.0
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "i" "handbrake-js@1.2.0"
npm ERR! node v0.10.35
npm ERR! npm  v2.3.0

npm ERR! version not found: handbrake-js@1.2.0
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ogd/Documents/projects/test-handbrake-js/npm-debug.log
```

This looks like an issue for `npm-registry-couchapp`, so if you feel like following it up, that's where it should be filed. Either way, things look copacetic with `handbrake-js` now.
