### ISSUE TITLE
Feature like git-bisect to find broken upstream deps

### ISSUE THREAD

**Issue by nolanlawson** [npm/npm#7160]
In PouchDB, we frequently have our builds broken due to an upstream dependency introducing a bug in a patch/minor version (https://github.com/pouchdb/pouchdb/issues/2235).

Recently it's gotten so bad that we're actually starting to consider npm shrinkwrapping or committing the `node_modules` ([discussion on Twitter](https://twitter.com/daleharvey/status/550996955384786944)). We've also started locking down several deps instead of using the caret- or tilde-versioning. It's unfortunate, though, because this robs the larger community of a valuable "canary in the coal mine."

For projects that have a lot of dependencies and a lot of tests (and are perhaps better-tested than their own dependencies), it would be really nice if we had an easier way to diagnose breakages. I'm picturing some kind of feature like `git-bisect`, where npm would version-lock all dependencies and then unlock one dependency at a time, run a test, and then tell us which dependency broke the build.

It gets complicated when dependencies have had a lot of releases since the one declared in the `package.json`, but again this is where it would be nice if npm could automate that for us.

**Comment by fschwiet** [comment]
A downside of the git-bisect type approach is that you might fix a lot of issues that don't correspond to a real deployment target.

It sounds your tests could have detected the problems.  Is it possible to have PouchDB customers run the tests to check their environment?  At some point PouchDB is included in a project that is deployed, checking in the node_modules folder.  Maybe the tests can be ran at that point.

**Comment by othiym23** [comment]
I think this is the kind of truly useful edge case solution that would work best as an external module, perhaps called `npm-bisect`. It's too niche (and, realistically, too complex to support within the existing codebase) to put into the core CLI, but there are definitely times in the past when it would have saved my bacon. So, I'm rejecting this as a feature request for npm itself, but if you need help getting it built for real, I'd be happy to pitch in.

**Comment by nolanlawson** [comment]
Cool cool, that sounds like a good way to proceed! :)

**Comment by thadk** [comment]
:+1:

**Comment by mroderick** [comment]
I think loose versioning of dependencies is the biggest design flaw of npm. shrinkwrap is a bandaid at best, not a real fix for the problem.

I would love to have such a tool at my disposal, as I have wasted many hours on several occasions, trying to figure out which dependency of which dependency of which dependency that got updated a broke something for everyone.

If anyone knows npm well enough to build such a tool, please start a Kickstarter, and I'll happily donate and market the campaign until I am blue in the face.
