### ISSUE TITLE
npm install semi-verbose option?

### ISSUE THREAD

**Issue by jackspaniel** [npm/npm#7161]
I really miss how the old npm would show at least one line for every package installed. I know I can see that information again with --verbose, but that's more than I usually want. Is there some option to just show one line when a package is being updated or installed?

**Comment by othiym23** [comment]
`--loglevel=info` or `--loglevel=http`, possibly combined with `--no-spin` will give you pretty much exactly the old npm output.

**Comment by jackspaniel** [comment]
http seems to be what I want. Thanks! Btw is this stuff like --no-spin documented anywhere? Google isn't helping. I see the page with loglevel now but before I wasn't able to find it for some reason. I kept looking under the install documentation.

**Comment by othiym23** [comment]
`npm help 7 config` has all of the configuration variables and CLI switches in it, although it takes maybe too much of an understanding of how the command-line and configuration-file parsing works to get from the docs to `--loglevel=http --no-spin`. Which reminds me -- if you want the above to be your default npm CLI behavior, run something like

```
$ npm config set spin false
$ npm config set loglevel http
```

and those values will be written to `$HOME/.npmrc` and used in the future.
