### ISSUE TITLE
npm install -g cordova - "unmet dependencies"

### ISSUE THREAD

**Issue by gizmotronicinc** [npm/npm#7163]
i tried to clean the cache and install it again but it says a warning unmet dependency
```
C:\Users\Ralph>npm cache clean

C:\Users\Ralph>npm install -g cordova

C:\Users\Ralph\AppData\Roaming\npm\cordova -> C:\Users\Ralph\AppData\Roaming\npm\node_modules\cordova\bin\cordova
npm WARN unmet dependency C:\Users\Ralph\AppData\Roaming\npm\node_modules\phonegap\node_modules\connect-phonegap requires shelljs@'0.2.6' but will load
npm WARN unmet dependency C:\Users\Ralph\AppData\Roaming\npm\node_modules\phonegap\node_modules\shelljs,
npm WARN unmet dependency which is version 0.1.4
npm WARN unmet dependency C:\Users\Ralph\AppData\Roaming\npm\node_modules\phonegap\node_modules\cordova\node_modules\plugman requires request@'2.22.0' but will load
npm WARN unmet dependency C:\Users\Ralph\AppData\Roaming\npm\node_modules\phonegap\node_modules\cordova\node_modules\request,
npm WARN unmet dependency which is version 2.21.0
cordova@4.2.0 C:\Users\Ralph\AppData\Roaming\npm\node_modules\cordova
├── underscore@1.7.0
├── q@1.0.1
├── nopt@3.0.1 (abbrev@1.0.5)
└── cordova-lib@4.2.0 (valid-identifier@0.0.1, osenv@0.1.0, properties-parser@0.2.3, bplist-parser@0.0.6, mime@1.2.11, unorm@1.3.3, semver@2.0.11, shelljs@0.3.0, rc@0.5.2, dep-graph@1.1.0, npm@1.4.28, elementtree@0.1.5, xcode@0.6.7, through2@0.6.3, npmconf@0.1.16, glob@4.0.6, plist@1.1.0, tar@1.0.2, request@2.47.0, d8@0.4.4, cordova-js@3.7.3)
```

**Comment by smikes** [comment]
It looks like you may have run `npm update -g` at some point.  Unfortunately this causes incorrect dependencies to be installed.  You can correct this by uninstalling and reinstalling the affected package(s):

```
npm rm -g cordova
npm install -g cordova@latest
```

To update a global package, always use `npm install -g <package>@latest` (unless you are updating `npm` itself on Windows, in which case see <https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows> )

**Comment by smikes** [comment]
Is this still a problem for you?

The `warning: unmet dependency` messages you are seeing can be fixed by running:

```
npm install -g cordova@latest phonegap@latest
```

This should prevent the two modules from sharing incompatible dependencies.

There have been a lot of improvements to npm since January. Can you try updating your npm installation?

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as abandoned.

**Comment by Oluwasetemi** [comment]
####DIfficulty in Installation
![image](https://cloud.githubusercontent.com/assets/10030028/15132130/4a722d1a-164e-11e6-925a-05e4be28ba54.png)

> cannot go pass this point every time i try to **install cordova <br>

I used the code `npm install -g cordova`
 Everytime i attempt to install cordova, i simply get stalked at this point.<br> Why if I may ask?
