### ISSUE TITLE
Offer --libdir and --mandir configure options

### ISSUE THREAD

**Issue by ryanpcmcquen** [npm/npm#7166]
It'd be nice if these configure options were available:

```--libdir``` & ```--mandir```

As a packager I have to correct these using sed for Slackware:

```
sed -i '/var manRoot/ s/"share",//' deps/npm/lib/{,un}build.js
sed -i "s|\"lib\"|\"lib${LIBDIRSUFFIX}\"|" deps/npm/lib/npm.js
```

Thanks!

**Comment by smikes** [comment]
Would these affect where `npm` is installed, or where `npm` installs global packages?

**Comment by ryanpcmcquen** [comment]
Where ```npm``` installs libraries and documentation. Packages shouldn't be affected. ```/usr/bin``` is the same regardless of system architecture.

**Comment by othiym23** [comment]
This seems like a reasonable request, but not a very high-priority one. If you (or somebody else) wants to take a stab at an implementation, that's probably the fastest way to seeing this actually get added.

**Comment by ryanpcmcquen** [comment]
:+1: Thank you! I'll put together a pull request.

**Comment by othiym23** [comment]
Following from my last message in this thread, I'm going to leave the `patch-welcome` label on this issue, but close it. While this behavior would be useful for Slackware users, this isn't something urgent enough that the CLI team is going to make it a priority within the next 6-12 months. If someone feels like taking a whack at this, we're glad to provide help. Thanks for your time!

**Comment by ryanpcmcquen** [comment]
Just for the record, this would be useful for _all_ Linux distros, not just Slackware.
