### ISSUE TITLE
Support for no-proxy in .npmrc file

### ISSUE THREAD

**Issue by jfbibeau** [npm/npm#7168]
It looks like NPM will correctly honor the ENV variables for http_proxy, https_proxy and recently also for no_proxy.

However .npmrc only seems to support proxy and https-proxy. This leads to some funny behavior...

I am trying to configure a no_proxy and http_proxy setting for NPM. So I thought I would configure `proxy` in .npmrc and `no_proxy` in my ENV variable (since npmrc doesn't support it). But .npmrc's `proxy` overrides the environment variable's `no_proxy` :(

So the only way for me to get no_proxy to work with NPM is to set it as an environment variable, which will enable it system wide (and I'm trying to avoid that).

Thanks!

**Comment by othiym23** [comment]
The current proxy settings are a pretty delicate balance, because there are many conflicting use cases around them (in particular, figuring out the precedence of the configuration file vs environment variables is pretty much a nightmare). The basic rule, for now, is that if you want to use `no_proxy`, you should configure both `http_proxy` and `no_proxy` via environment variables. The reason for this is an implementation detail (the proxy handling is actually done by `request`). A patch that adds support for `no-proxy` to `.npmrc` would be welcome, as would be a patch that tweaks the documentation to make the current setup easier to use.

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.

**Comment by brunowego** [comment]
+1

**Comment by wildpixeldesign** [comment]
+1

**Comment by goodloot** [comment]
+1, please, reopen.

**Comment by othiym23** [comment]
Reopening, as this is a feature request. It would be nice to get this as a patch, because this is such a low priority for the CLI team, it's unlikely the team will get to it in the next year.

**Comment by marcellodesales** [comment]
Would love this one as well...

**Comment by karthikeayan** [comment]
+1

**Comment by rogerwelin** [comment]
+1

**Comment by Mischi** [comment]
:+1:

**Comment by Mischi** [comment]
:+1:

**Comment by BrianLenzo** [comment]
+1 
Setting proxy in env vars messes other applications up. Having it all in .npmrc would help my company use NPM behind a very secure proxy.

**Comment by marcellodesales** [comment]
@BrianLenzo Just stepped on this again today :( Please guys, add this support... We have NPMO installation internally and we are building applications behind the HTTP_PROXY as well...

**Comment by dg1sek** [comment]
+1

**Comment by danpantry** [comment]
Also behind a very strict proxy. This was fine up until we added an internal registry - now we have to use `NO_PROXY` to ignore the internal registry. Unfortunately, my colleague is on Windows and does not have a Bash environment and thus does not have access to this environment variable which much pain.

**Comment by othiym23** [comment]
@danpantry It's [also possible](http://ss64.com/nt/syntax-variables.html) set environment variables, either per-session, or permanently, on Windows.

**Comment by danpantry** [comment]
@othiym23  yes, that's the route we ended up going, but that's the "much pain" part - it's not so easy to just throw that in a file in the project folder and have it "just work".

**Comment by legodude17** [comment]
Where is the config reading in the npm code? I would like to look at this.

**Comment by othiym23** [comment]
We talked about this a bit, and this is actually not that tough to add to npm itself – all it would take is making some changes to [the function that sets up the registry client](https://github.com/npm/npm/blob/master/lib/cache/caching-client.js#L194) to copy `no-proxy` from the configuration and putting it in `process.env.no_proxy`. @zkat will get to this after the release of `npm@4` is ready to go, but if somebody else wants to take a whack at it before then, great! Thanks to all for their patience!

**Comment by legodude17** [comment]
So you would want set `process.env.no_proxy` to mirror `config.get('no_proxy')` in `adaptConfig`? Any one object to that?

**Comment by legodude17** [comment]
Sent PR doing above. #14248.

**Comment by zkat** [comment]
Unassigning myself because someone else put up the PR for this.

**Comment by stanleyxu2005** [comment]
This is really annoying. I set proxy in the global `.npmrc`, but I have some scoped packages hosted in private repo. I create a local `.npmrc` and want to disable proxy for that scope. Unfortunately, none of the follows work:
```
@scoped_repo:http_proxy=
@scoped_repo:http_proxy=false
@scoped_repo:no_proxy=
@scoped_repo:no_proxy=true
```

**Comment by ghuser** [comment]
I agree with @stanleyxu2005

**Comment by ghuser** [comment]
+1 vote for reopening the issue.

**Comment by gforceg** [comment]
I was trying to override the scoped proxy with null like this:
```ini
@myscope:registry=http://my.registry/path
@myscope:proxy=null
```

> The basic rule, for now, is that if you want to use no_proxy, you should configure both http_proxy and no_proxy via environment variables. The reason for this is an implementation detail (the proxy handling is actually done by request).

@othiym23,
This piece of information was very helpful. Thank you! I didn't know that there was such a convention as the no_proxy environmental variable and I did not see mention of no_proxy in [the documentation](https://docs.npmjs.com/misc/config).

I need npm to talk to both registry.npmjs.org and an internal repository and now it does. 😀

**Comment by SergejKasper** [comment]
@gforceg i'd like to do the same. Could you please share your solution?

**Comment by gforceg** [comment]
@SergejKasper sure!
So the trick is to not include any proxy information in your .npmrc.
instead you have two env variables:
`http_proxy`, and `no_proxy`
`http_proxy` is the URL to your proxy server
`no_proxy` is a comma separated list of hosts you do not want to access through the proxy.
So if `server1` and `server2` are internal and you can't talk to them through the proxy you'd set no_proxy to `server1.mydomain.net,server2.mydomain.net`

Now if you have a scoped repository on one of them, set it in your .npmrc

```ini
@myscope:registry=http://server1.mydomain.net/registry/path
```

So now if my project depends on `@myscope/mypackage`, npm will not use the proxy when grabbing this module.

Alternatively, if you are writing a package that will be published to your internal repo, 'npm publish' will work inside the firewall, but you'll want to set up the registry in `package.json` under "publishConfig":

```json
"publishConfig":{"registry":"http://server1.mydomain.net/registry/path"}
```

**Comment by alexmorosmarco** [comment]
Hi, any updates on this?
I see all people around the internet are finally working with the environment proxy variables, but it would be great to be able to define the `no_proxy` in the .npmrc as it would give us more flexibility for other tools different than npm.

Thanks!

**Comment by Saturate** [comment]
I also need this, setting the Env var before install is pretty painful.

@alexmorosmarco I will try to find the time for a fix as most of the Enterprise clients I work with need this.
