### ISSUE TITLE
ENOENT issue running 'npm install' on ubuntu

### ISSUE THREAD

**Issue by geclos** [npm/npm#7169]
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'install' ]
2 info using npm@1.3.10
3 info using node@v0.10.25
4 error install Couldn't read dependencies
5 error Error: ENOENT, open '/home/geclos/package.json'
6 error If you need help, you may report this log at:
6 error     <http://github.com/isaacs/npm/issues>
6 error or email it to:
6 error     <npm-@googlegroups.com>
7 error System Linux 3.13.0-44-generic
8 error command "/usr/bin/nodejs" "/usr/bin/npm" "install"
9 error cwd /home/geclos
10 error node -v v0.10.25
11 error npm -v 1.3.10
12 error path /home/geclos/package.json
13 error code ENOENT
14 error errno 34
15 verbose exit [ 34, true ]
```

**Comment by KenanY** [comment]
@geclos Does `/home/geclos/package.json` exist?

**Comment by geclos** [comment]
Nope. Installed npm through apt-get and tried to run it with sudo terminal from default location (that is my home folder).On Mon, Jan 19, 2015 at 11:47 pm,  npm/npm <reply@reply.github.com> wrote:            @geclos Does /home/geclos/package.json exist?

**Comment by KenanY** [comment]
@geclos What are you expecting to happen when you run `npm install` without any arguments and without a `package.json` in your current working directory? `npm` has absolutely no idea what you want it to install unless you tell it something. The [`npm install` docs](https://docs.npmjs.com/cli/install) might help.

**Comment by othiym23** [comment]
In addition to what @KenanY said, you're running a version of npm old enough to be unsupported. You may want to switch from using the Ubuntu-packaged versions of Node to the [NodeSource packages](https://github.com/nodesource/distributions).
