### ISSUE TITLE
NPM error when running npm test

### ISSUE THREAD

**Issue by marcmereyde** [npm/npm#7172]
I keep on running into the following issue.
Can anyone help?

```
Marc:~ Marc$ npm test
npm ERR! Error: ENOENT, open '/Users/Marc/package.json'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 13.4.0
npm ERR! command "node" "/usr/local/bin/npm" "test"
npm ERR! cwd /Users/Marc
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! path /Users/Marc/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/Marc/npm-debug.log
npm ERR! not ok code 0
```

**Comment by KenanY** [comment]
@marcmereyde Does `/Users/Marc/package.json` exist?

**Comment by marcmereyde** [comment]
I come from Ruby and ROR and I am trying to transition to JS, Node and Express so I am sorry if anything I say sounds idiotic to you all.
Would package.json be installed when you install Node.js through the Node.js website?

**Comment by othiym23** [comment]
No, in Rails terms, `package.json` is the equivalent of a combined `Rakefile` and `Gemfile` -- it's the manifest for your application that includes dependencies, per-package lifecycle scripts, and other package metadata. [Here's](https://docs.npmjs.com/files/package.json) the documentation for it.

So if you're running `npm test`, you need to be in a directory that has a `package.json` that `npm test` can use to figure out how to run the tests for your application.

**Comment by marcmereyde** [comment]
Thank you!
