### ISSUE TITLE
npm rebuild with failing optionalDependencies

### ISSUE THREAD

**Issue by timoxley** [npm/npm#7175]
`npm rebuild` should probably continue if any optionalDependencies fail, in the same way optionalDependencies failures are tolerated during `npm install`.

This causes a problem if an optional dependency is installed successfully in one environment, but can't build in another.

e.g. Bundling a tarball on a mac that uses `fsevents` as an optionalDependency, deploy onto ubuntu, and `fsevents` breaks the `npm rebuild`.

Possibly related/duplicate of https://github.com/npm/npm/issues/6801

**Comment by monolithed** [comment]
+1, I've the same problem with many optional packages like chokidar.

See my [issue](https://github.com/paulmillr/chokidar/issues/246)

**Comment by paulmillr** [comment]
this is a regression I think

**Comment by othiym23** [comment]
This has been moved to the [npm roadmap](https://github.com/npm/npm/wiki/Roadmap), which we're using instead of the confusing `next-*` labels now.
