### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by manuelep** [npm/npm#7176]
running `#npm install` I got this error... what's wrong? 

```
npm ERR! weird error 127
npm ERR! Error: ENOENT, open '/root/tmp/npm-4135-Ez11nyOS/1421765966879-0.054148012306541204/package/LICENSE'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.11-2-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/manuele/dev/portali/web2py.trunk/applications/test_ol3/static/ol3
npm ERR! node -v v0.10.21
npm ERR! npm -v 1.3.10
npm ERR! path /root/tmp/npm-4135-Ez11nyOS/1421765966879-0.054148012306541204/package/LICENSE
npm ERR! code ENOENT
npm ERR! errno 34
npm http GET https://registry.npmjs.org/chainsaw
npm http GET https://registry.npmjs.org/buffers
npm ERR! Error: ENOENT, open '/root/tmp/npm-4135-Ez11nyOS/1421765963839-0.7449612023774534/package/lib/nodes/attrs.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.11-2-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/manuele/dev/portali/web2py.trunk/applications/test_ol3/static/ol3
npm ERR! node -v v0.10.21
npm ERR! npm -v 1.3.10
npm ERR! path /root/tmp/npm-4135-Ez11nyOS/1421765963839-0.7449612023774534/package/lib/nodes/attrs.js
npm ERR! code ENOENT
npm ERR! errno 34
```

**Comment by smikes** [comment]
This looks like a race condition in npm, many of which were fixed by newer versions. Try updating npm with 

sudo npm install npm@latest -g

**Comment by smikes** [comment]
Is this still a problem for you?

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.3. Can you try updating your npm installation?

For some Linux distributions (Debian/Ubuntu and RedHat/CentOS), the latest node version provided by the distribution may lag behind the stable version. [Here are instructions from NodeSource](https://github.com/nodesource/distributions) on getting the latest node.

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by manuelep** [comment]
Il 28/01/15 23:55, Sam Mikes ha scritto:
>
> Is this still a problem for you?
>
> There have been a lot of improvements to npm -- especially around
> conflicts and race conditions during install -- since 1.3. Can you try
> updating your npm installation?
>
> For some Linux distributions (Debian/Ubuntu and RedHat/CentOS), the
> latest node version provided by the distribution may lag behind the
> stable version. Here are instructions from NodeSource
> <https://github.com/nodesource/distributions> on getting the latest node.
>
> We are trying to clean up older npm issues, so if we don't hear back
> from you within a week, we will close this issue. (Don't worry -- you
> can always come back again and open a new issue!)
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/npm/npm/issues/7176#issuecomment-71934472>.
>
I beg your pardon,
I was trying to compile the openlayers3 source project but I dcided to
use a pre-compiled version.
I got few experience in this kind of procedure and I only need a stable
version of the library.

best regards

    M.
