### ISSUE TITLE
`files` directory resolution inconsistent on prereleases

### ISSUE THREAD

**Issue by es128** [npm/npm#7184]
I've released several versions of chokidar with `"files": ["lib"]` in the package.json with no problems. However, today I attempted a pre-release using `--tag 1.0.0-rc1` and the files in the `lib` dir didn't make it into the published package. Resolved in 1.0.0-rc2 by changing to `"files": ["lib/"]`, but the behavior should have at least been consistent with the regular releases.

Related to #6582.

**Comment by smikes** [comment]
Instead of providing a directory name in `files`, what happens when you pass a list of the files that you need to have included?  Does that change the observed behavior on a pre-release?

`files` is interpreted as a list of files, and apparently the behavior when a directory is given is both underspecified and underdocumented.  Changing this may be on the npm roadmap (as you noted, case #6582 touches on this; also see #7030), but even if so, it's not being actively worked on.

**Comment by es128** [comment]
https://docs.npmjs.com/files/package.json claims directories will get resolved to their contents, and they do. But on prereleases, a trailing slash is needed. The main issue is the inconsistency between regular releases and prereleases.

If a trailing slash is always needed to specify an entire directory, that would be acceptable. Just document it as such.

**Comment by othiym23** [comment]
This definitely sounds like a regression. Could somebody put together a minimal repro case for us?

**Comment by es128** [comment]
https://github.com/paulmillr/chokidar/tree/1.0.0-rc1

**Comment by KenanY** [comment]
@es128 Do you recall what version of `npm` you might have had? Since `npm2.7.1` you can no longer `--tag` with a SemVer range so `--tag 1.0.0-rc1` does not work anymore. I'm not sure if there's any way to run into this bug anymore.

**Comment by es128** [comment]
@KenanY it *was* a version prior that that that still allowed semver-compatible tags, but that doesn't seem relevant to the issue.

I suppose it needs to be tried again on latest npm with a currently valid tag.

**Comment by KenanY** [comment]
@es128 I wonder what kind of tag might trigger this now?

``` sh
$ git clone https://github.com/paulmillr/chokidar.git
$ cd chokidar
$ git checkout 1.0.0-rc1
$ npm publish --tag blah -dd
...
npm verb tar pack [ '/home/kenan/.npm/chokidar/1.0.0-rc1/package.tgz',
...
$ tar -ztf /home/kenan/.npm/chokidar/1.0.0-rc1/package.tgz
package/package.json
package/README.md
package/CHANGELOG.md
package/lib/fsevents-handler.js
package/lib/index.js
package/lib/is-binary.js
package/lib/nodefs-handler.js
```

`npm@2.8.2`

**Comment by es128** [comment]
Yeah, so maybe it's ok now. I wasn't expecting that the name of the tag mattered, just that specifying a tag was causing the issue.

**Comment by es128** [comment]
I'm not familiar with the `-dd` option - is there documentation of that somewhere?

**Comment by KenanY** [comment]
@es128 It's shorthand for `--verbose`/`--loglevel verbose`: https://docs.npmjs.com/misc/config#shorthands-and-other-cli-niceties

**Comment by es128** [comment]
So, did you just try to publish, observe the pack, then get rejected by the server for not being an owner? I'm not totally sure I understand what I'm seeing in your example.

**Comment by KenanY** [comment]
@es128 I run `npm publish` and then view the contents of the packed tarball. I use `-dd` so that I can see the path to the tarball in the output. I could just use `npm pack` but I'm trying to use the exact command you did (although of course I can't _actually_ publish).

**Comment by es128** [comment]
Well I suppose I *could* follow the same routine you did and actually publish just to make sure. What would be the best way to do that and be able to clean up after the experiment?

**Comment by KenanY** [comment]
@es128 Hmm, I just went all the way back to `npm@1.4.28` and I couldn't reproduce this with those steps of mine, so maybe I'm not actually properly testing this with what I'm doing. If anything, I'll probably try publishing `chokidar@1.0.0-rc1` under a bogus package name (and `npm deprecate` afterwards for good measure) so I can debug on my own time (and not take up yours) :)

I'm on Linux btw if this turns into some kind of weird environment issue regarding that folder slash.

**Comment by othiym23** [comment]
This has been moved to the [npm roadmap](https://github.com/npm/npm/wiki/Roadmap), which we're using instead of the confusing `next-*` labels now.
