### ISSUE TITLE
Using `npm link x` causes EACCES to be thrown on the next `npm update`

### ISSUE THREAD

**Issue by binarykitchen** [npm/npm#7190]
How to reproduce on Ubuntu 14.10:

1. Link a local node module inside your repo with `npm link x`
2. Run `npm update`

Then an error like this example is thrown:

```
npm ERR! Error: EACCES, unlink '/home/michael-heuberger/binarykitchen/code/videomail.io/node_modules/videomail-client/node_modules/superagent/node_modules/debug/node_modules/ms/.npmignore'
```

That file `.npmignore` has the group `nobody` which is the cause. Where is that coming from?

**Comment by smikes** [comment]
Thanks for the bug report.  Do you run any of the commands you list above (`npm link` and `npm update`) as `root`?

Also, I want to caution you against running `npm update`.  It has the potential to update packages in a way that is incompatible with `semver`.  If you want to see which packages have updates available, a safer course is to use `npm outdated` to list outdated packages and to selectively install newer packages with `npm install -S <pkg>@latest`

**Comment by binarykitchen** [comment]
@smikes No way, I never use `sudo` for any npm commands.

So I assume I should avoid `npm update` because of the nested dependencies? Alright, is there a clever command how I could pipe the results of `npm outdated -depth=0` to `npm install -s <pkg>@latest` in one go?

**Comment by smikes** [comment]
Weird.  Having `root` priveleges is one of the known ways to get things set up with as `nobody`, though that's usually the user.

If you want to update to the latest version respecting semver, then 
```
rm -rf node_modules
npm install
```

If you want to update to the latest version, possibly updating the stored dependency version, then generally the advice is to do that module-by-module, running your unit tests in between, so you know which one causes things to break.

However, you might want to check out `npm-check` ; I don't think it has a "update all dependencies as a batch" mode, but it has a nice interactive update mode.

**Comment by binarykitchen** [comment]
Well, again, I never use `root` but have this in my `.npmrc`: `prefix=/home/michael-heuberger/npm`

Like that it places all under my home directory and I never encounter permission issues. Maybe this causes headaches when you npm-link stuff? Are there any test cases for that scenario?

`rm -rf node_modules && npm install` is not a good idea because the npm-link disappears each time. Hence I only want to update selected packages.

`npm-check` ... huh, never seen before. What's that?

**Comment by smikes** [comment]
Sorry, I failed to respond to your question.  `npm-check` is a 3rd-party command line module that provides a nice user interface around checking for outdated packages and installing newer versions.

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
