### ISSUE TITLE
No compatible version found: coveralls@'^2.11.2'

### ISSUE THREAD

**Issue by polp6880** [npm/npm#7194]
Hi all! I have a question with creating a very simple express and socket.io project on my centos server. I'm running something like "express myapp" and after navigating inside the directory "npm install" however, in this process I can see this error inside logs:

>2927 error Error: No compatible version found: coveralls@'^2.11.2'
>2927 error Valid install targets:
>2927 error ["1.0.0","1.1.0","1.1.1","1.1.2","1.1.3","2.0.0","2.0.1","2.0.2","2.0.3","2.0.4","2.0.5","2.0.6","2.0.7","2.0.8","2.0.9","2.0.10","2.0.11","2.0.12","2.0.13","2.0.15","2.0.16","2.1.0","2.2.0","2.3.0","2.5.0","2.6.0","2.6.1","2.7.0","2.7.1","2.8.0","2.10.0","2.10.1","2.11.0","2.11.1","2.11.2"]
>2927 error     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:685:10)
>2927 error     at /usr/local/lib/node_modules/npm/lib/cache.js:607:10
>2927 error     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
>2927 error     at Object.oncomplete (fs.js:107:15)
>2928 error If you need help, you may report this log at:
>2928 error     <http://github.com/isaacs/npm/issues>
>2928 error or email it to:
>2928 error     <npm-@googlegroups.com>
>2929 error System Linux 2.6.32-431.1.2.0.1.el6.x86_64
>2930 error command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
>2931 error cwd /var/www/--myserver--/public_html/myapp
>2932 error node -v v0.10.4
>2933 error npm -v 1.2.18
>2934 verbose exit [ 1, true ]

I believe this is then producing a "module not found" error when i try to run the basic application. Can anybody help please?

**Comment by macbre** [comment]
`npm install npm` (i.e. an upgrade to npm 2.x) should solve it.

You're using npm 1.x which does not support versions specified with `^`.

**Comment by polp6880** [comment]
Hello! Yep, that seems to solve the issue. As a sidenote though, I had to run `npm install npm -g` for it to work properly. Many thanks!
