### ISSUE TITLE
Unable to install package

### ISSUE THREAD

**Issue by waissbluth** [npm/npm#7196]
I'm getting the following error when running `npm install` for TileMill. I need to be running node 0.8.

	npm http 304 https://registry.npmjs.org/xml-name-validator
	npm http 304 https://registry.npmjs.org/request
	npm WARN package.json request@2.51.0 No readme data.
	npm ERR! Error: No compatible version found: xml-name-validator@'^1.0.0'
	npm ERR! Valid install targets:
	npm ERR! ["1.0.0"]
	npm ERR!     at installTargetsError (/usr/local/Cellar/node08/0.8.26/lib/node_modules/npm/lib/cache.js:719:10)
	npm ERR!     at /usr/local/Cellar/node08/0.8.26/lib/node_modules/npm/lib/cache.js:641:10
	npm ERR!     at saved (/usr/local/Cellar/node08/0.8.26/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
	npm ERR!     at Object.oncomplete (fs.js:297:15)
	npm ERR! If you need help, you may report this log at:
	npm ERR!     <http://github.com/isaacs/npm/issues>
	npm ERR! or email it to:
	npm ERR!     <npm-@googlegroups.com>

	npm ERR! System Darwin 14.0.0
	npm ERR! command "/usr/local/Cellar/node08/0.8.26/bin/node" "/usr/local/bin/npm" "install"
	npm ERR! cwd /Users/nwr/Downloads/tilemill-0.10.1
	npm ERR! node -v v0.8.26
	npm ERR! npm -v 1.2.30

I'm running OSX Yosemite. Any help appreciated. Thanks!

**Comment by KenanY** [comment]
https://github.com/npm/npm/wiki/Troubleshooting#no-compatible-version-found

Your version of `npm` is so old that it doesn't support the `^` semver operator that you see here:

```
npm ERR! Error: No compatible version found: xml-name-validator@'^1.0.0'
```

As such, `npm` fails to find a valid version of the package to install. The fix is easy: update `npm`!

``` bash
$ npm install -g npm
```

**Comment by waissbluth** [comment]
Thanks!
