### ISSUE TITLE
Error instaling cordova or phonegap

### ISSUE THREAD

**Issue by khandakhulu** [npm/npm#7199]
Hi

I am trying the ff command on a Windows 7 machine:

```
npm install -g cordova
npm intall -g phonegap
```

I get the ff error

```
34 error Error: 4480:error:1408D172:SSL routines:SSL3_GET_KEY_EXCHANGE:wrong signature type:openssl\ssl\s3_clnt.c:1862:
34 error
34 error     at SlabBuffer.use (tls.js:235:18)
34 error     at CleartextStream.read [as _read] (tls.js:455:29)
34 error     at CleartextStream.Readable.read (_stream_readable.js:341:10)
34 error     at EncryptedStream.write [as _write] (tls.js:369:25)
34 error     at doWrite (_stream_writable.js:226:10)
34 error     at writeOrBuffer (_stream_writable.js:216:5)
34 error     at EncryptedStream.Writable.write (_stream_writable.js:183:11)
34 error     at write (_stream_readable.js:602:24)
34 error     at flow (_stream_readable.js:611:7)
34 error     at Socket.pipeOnReadable (_stream_readable.js:643:5)
35 error If you need help, you may report this *entire* log,
35 error including the npm and node versions, at:
35 error     <http://github.com/npm/npm/issues>
36 error System Windows_NT 6.1.7601
37 error command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "phonegap"
38 error cwd C:\Users\User
39 error node -v v0.10.35
40 error npm -v 1.4.28
41 verbose exit [ 1, true ]
```

Please help as I am new to cordova/phonegap.

**Comment by KenanY** [comment]
```
Error: 4480:error:1408D172:SSL routines:SSL3_GET_KEY_EXCHANGE:wrong signature type:openssl\ssl\s3_clnt.c:1862
```

More often than not, these kinds of SSL errors are due to a proxy configuration error. Are you behind a proxy? If so, have you properly configured `npm` to use it?

  - [`proxy`](https://docs.npmjs.com/misc/config#proxy)
  - [`https-proxy`](https://docs.npmjs.com/misc/config#https-proxy)
  - [`cafile`](https://docs.npmjs.com/misc/config#cafile)

**Comment by khandakhulu** [comment]
Yes I am behind a proxy. What file must I modify in order to enter my username and password for the proxy?

**Comment by KenanY** [comment]
[`.npmrc`](https://docs.npmjs.com/files/npmrc)

**Comment by smikes** [comment]
Is this still a problem for you?

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by khandakhulu** [comment]
Thank you, you can delete the issue. 

     On Thursday, February 19, 2015 4:07 PM, Sam Mikes <notifications@github.com> wrote:
   

 Is this still a problem for you?We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)Thanks!—

**Comment by othiym23** [comment]
Closing as resolved.
