### ISSUE TITLE
cant not fix publish failed 

### ISSUE THREAD

**Issue by emn178** [npm/npm#7203]
Hi,

I try to publish my package from 0.1.1 to 0.1.2. I get this errors:
```
Chenteki-Mac-mini:js-sha512 emn178$ npm publish
npm ERR! publish Failed PUT 403
npm ERR! Darwin 11.4.2
npm ERR! argv "node" "/usr/local/bin/npm" "publish"
npm ERR! node v0.10.35
npm ERR! npm  v2.1.18
npm ERR! code E403

npm ERR! forbidden Attempting to modify version 0.1.2,
npm ERR! which was previously published on 2015-01-07T12:25:52.910Z.
npm ERR! This is forbidden, to maintain package integrity.
npm ERR! Please update the version number and try again.: js-sha512
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Applications/MAMP/htdocs/mine/github/js-sha512/npm-debug.log
```
I check the package info and I get this:
 ```
Chenteki-Mac-mini:js-sha512 emn178$ npm info js-sha512

{ name: 'js-sha512',
  description: 'This is a simple SHA-512, SHA-384, SHA-512/224, SHA-512/256 hash functions for JavaScript supports UTF-8 encoding.',
  'dist-tags': { latest: '0.1.1' },
  versions: [ '0.1.0', '0.1.1' ],
  maintainers: 'emn178 <emn178@gmail.com>',
  time: 
   { modified: '2015-01-07T14:47:59.919Z',
     created: '2014-01-05T06:02:45.484Z',
     '0.1.0': '2014-01-05T06:02:49.194Z',
     '0.1.1': '2014-07-27T12:06:35.554Z',
     '0.1.2': '2015-01-07T12:25:52.910Z' },
  author: 'emn178 <emn178@gmail.com>',
  repository: 
   { type: 'git',
     url: 'https://github.com/emn178/js-sha512.git' },
  homepage: 'https://github.com/emn178/js-sha512',
  keywords: 
   [ 'sha',
     'sha2',
     'sha384',
     'sha512',
     'sha512/224',
     'sha512/256',
     'hash',
     'encryption',
     'cryptography',
     'HMAC' ],
  bugs: { url: 'https://github.com/emn178/js-sha512/issues' },
  license: 'MIT',
  readmeFilename: 'README.md',
  version: '0.1.1',
  main: 'src/sha512.js',
  scripts: { test: 'node tests/node-test.js' },
  dist: 
   { shasum: '89b56a08165fb90fa3adab663a4cf21a37d073cb',
     tarball: 'http://registry.npmjs.org/js-sha512/-/js-sha512-0.1.1.tgz' },
  directories: {} }
```
It shows there is a record 0.1.2 in `time` so that I can't publish again.
But the package's version is still 0.1.1
I can not use --force now in new npm version.
How can I publish it to 0.1.2 correctly??

Thanks & best regards.

**Comment by KenanY** [comment]
It's impossible to re-publish `0.1.2`. Can you settle with simply bumping up to `0.1.3`?

**Comment by emn178** [comment]
Ok, but what causes this situation? network issue?

**Comment by othiym23** [comment]
@emn178 you should install the latest stable version of npm by running `npm install -g npm`. Versions of npm older than 1.4.0 can't publish to the registry reliably (and the npm team considers them unsupported), and 0.1.1 was published using `npm@1.3.8`, so you probably still have an obsolete version.

After you've upgraded npm, then @KenanY's advice kicks in -- `npm version patch && git push origin master --follow-tags && npm publish` should get the newest version on the registry.

**Comment by smikes** [comment]
Is this still a problem for you?

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by emn178** [comment]
I changed version and fixed it, thanks.
