### ISSUE TITLE
npm's official website is error

### ISSUE THREAD

**Issue by kahn1990** [npm/npm#7207]
https://www.npmjs.com/package/pagination-api

{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"}

**Comment by lastboy** [comment]
+1

**Comment by KenanY** [comment]
@kahn1990 Issues with the website should be opened at the [`newww`](https://github.com/npm/newww) repo. This is the issue tracker for `npm`, the CLI package manager.

Looks like @lastboy has already raised an issue: https://github.com/npm/newww/issues/578

**Comment by smikes** [comment]
Can this issue now be closed?

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by kahn1990** [comment]
ok

**Comment by othiym23** [comment]
Issues with the web site should indeed be opened on `neww`, as @KenanY says in https://github.com/npm/npm/issues/7207#issuecomment-71375356. Plus I'm pretty sure we fixed that last week. Closing as resolved.
