### ISSUE TITLE
markdown doc display error

### ISSUE THREAD

**Issue by limingv5** [npm/npm#7208]
My NPM module:
https://www.npmjs.org/package/essi

There are some commentaries (just like ) in the README.md, which need to be the original-look. But npm website remove these commentaries, which puzzles me!

**Comment by KenanY** [comment]
@limingv5 Issues with the website should be reported to [`newww`](https://github.com/npm/newww). This is the issue tracker for `npm`, the actual package manager; not the website.

**Comment by limingv5** [comment]
Thanks! @KenanY
