### ISSUE TITLE
find should take a glob, or list of globs

### ISSUE THREAD

**Issue by isaacs** [npm/npm#721]
and should also not dive past excluded dirs.  Be more like `tar.makeList`

**Comment by othiym23** [comment]
Inasmuch as I even understand what @isaacs was getting at here, five years later, this sounds like a nice-to-have that the CLI team isn't going to have the wherewithal to deal with anytime soon. Also, `npm search` has grown into a problem that's going to require much more than small implementation tweaks to substantively improve. It's cool to see where things started, though.
