### ISSUE TITLE
npm install fails "could not create work tree dir"

### ISSUE THREAD

**Issue by leoselig** [npm/npm#7210]
I already posted this here (https://github.com/nikku/karma-browserify/issues/88) as I thought it to be an issue with karma-browserify but it does not seem to be one
Thisis the error
```
npm install karma-browserify --save-dev

npm ERR! Failed to clone git+https://github.com/nikku/node-browserify#3d7beaa23a528cea8dcec9d53d39038e9c1a968d from http
s://github.com/nikku/node-browserify fatal: could not create work tree dir 'C:\Users\user\AppData\Local\Temp\npm-8232-23
c7b192\1422127381504-0.8615590359549969\3d7beaa23a528cea8dcec9d53d39038e9c1a968d'.: No such file or directory
npm ERR! Failed to clone git+https://github.com/nikku/node-browserify#3d7beaa23a528cea8dcec9d53d39038e9c1a968d from http
s://github.com/nikku/node-browserify
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i
nstall" "karma-browserify" "--save-dev"
npm ERR! node v0.10.33
npm ERR! npm  v2.1.18
npm ERR! code 128

npm ERR! Command failed: fatal: could not create work tree dir 'C:\Users\user\AppData\Local\Temp\npm-8232-23c7b192\14221
27381504-0.8615590359549969\3d7beaa23a528cea8dcec9d53d39038e9c1a968d'.: No such file or directory
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\user\Documents\GitHub\recurrence-phrasing\npm-debug.log`
```

**Comment by smikes** [comment]
/cc @othiym23 bug report, Windows, git dependency

There have been a lot of improvements to npm -- especially around `git` dependencies on Windows during install -- since 2.1.18. Can you try updating your npm installation?

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

Thanks!

**Comment by smikes** [comment]
Is this still a problem for you?

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as abandoned, and git has been cleaned up a bunch since January, so if you return to this issue, try upgrading to `npm@latest` and seeing if this problem recurs.
