### ISSUE TITLE
npm install ionic error

### ISSUE THREAD

**Issue by xiaoshitou** [npm/npm#7211]
![error](https://cloud.githubusercontent.com/assets/3396026/5892041/37554d62-a4ed-11e4-94cc-b096c3fbfbb3.png)

**Comment by joshhartigan** [comment]
which version of node do you have installed? did you run `npm install` with `sudo`?

**Comment by xiaoshitou** [comment]
version：node -- > v0.11.4   npm-->1.3.4
i am install  on windows  , so ,no sudo

**Comment by xiaoshitou** [comment]
version：node -- > v0.11.4 npm-->1.3.4
i am install on windows , so ,no sudo

**Comment by KenanY** [comment]
@xiaoshitou `1.3.4` is extremely old and no longer supported. The latest version right now is `2.3.0`! Upgrading might be a little tricky on Windows but we have [a guide](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows) for it.

**Comment by xiaoshitou** [comment]
@KenanY    i  update npm  to 2.3.0,  but  now  raise the error  : cb() never called .   and i to find a solution #5920,but its not work  . cry.....

**Comment by KenanY** [comment]
@xiaoshitou You are getting that error when you run `npm shrinkwrap,` as in https://github.com/npm/npm/issues/5920? Or when you run `npm install`, as in your original issue? Nonetheless, I'm gonna need an `npm-debug.log` in order to help diagnose the issue. Try running with the `-d` flag and upload the log as a [gist](https://gist.github.com/) please.

**Comment by smikes** [comment]
Is this still a problem for you?

As KenanY suggested, could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

There is now a newer `npm` version: 2.4.0

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as resolved / abandoned.

**Comment by githubtantan** [comment]
go to http://npmjs-offline.blogspot.com/p/downloads-package.html for downlad and
how to install http://npmjs-offline.blogspot.com/p/how-to-download-install.html
