### ISSUE TITLE
Error: Cannot find module 'hawk'

### ISSUE THREAD

**Issue by jordancalder** [npm/npm#7218]
I just installed Node, NPM, and MongoDB on an AWS EC2 instance. However, anything I try to do with NPM (besides --version) results in the titled error. Not sure what this means or how to resolve it. I also haven't found much anywhere else online about this.

**Comment by smikes** [comment]
Can you please upload your `npm-debug.log` as a gist (https://gist.github.com/)?

```
$ npm -ddd ls -g
```

if that fails, there should be a very very verbose `npm-debug.log` in your current directory.

**Comment by smikes** [comment]
Is this still a problem for you?

Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

For some Linux distributions (Debian/Ubuntu and RedHat/CentOS), the latest node version provided by the distribution may lag behind the stable version. [Here are instructions from NodeSource](https://github.com/nodesource/distributions) on getting the latest node.

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by jordancalder** [comment]
I don't seem to be getting this error anymore. I uninstalled and installed again and everything worked fine. Ok to close this! Thanks!

**Comment by mbx2015** [comment]
I uninstalled and installed again but the same error, what's wrong
