### ISSUE TITLE
Random "No compatible version found" when using with Travis CI

### ISSUE THREAD

**Issue by colbin8r** [npm/npm#7219]
I'm trying to use Travis CI as a part of the build process for my webapp, but npm throws different errors every time Travis builds it. I've seen errors for `grunt-contrib-concat`, `grunt-contrib-coffee`, and `grunt-contrib-connect` among others. It says that it can't find a compatible install target, but the one I specify in my package.json matches exactly what it lists:

```
npm ERR! Error: No compatible version found: grunt-contrib-connect@'^0.9.0'
npm ERR! Valid install targets:
npm ERR! ["0.1.0","0.1.1","0.1.2","0.2.0","0.3.0","0.4.0","0.4.1","0.4.2","0.5.0","0.6.0","0.7.0","0.7.1","0.8.0","0.9.0","0.1.1-rc6"]
```

Log file of build: https://gist.github.com/colbin8r/5755e47fb71a398cfc8e

**Comment by KenanY** [comment]
```
$ npm --version
1.2.30
```

This version of `npm` is **ancient**, and doesn't support the `^` semver operator you see here:

```
npm ERR! Error: No compatible version found: grunt-contrib-connect@'^0.9.0'
```

The fix is to have Travis update `npm` before installing your dependencies. This should help: https://github.com/npm/npm/wiki/Troubleshooting#travis-projects-using-08-cant-upgrade-to-npm-2

**Comment by colbin8r** [comment]
Thanks! Updating Node using the technique in that article solved the problem for me!
