### ISSUE TITLE
Error when trying to `npm search`

### ISSUE THREAD

**Issue by danielbayley** [npm/npm#7221]
Here is the `npm-debug.log`
```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'search' ]
2 info using npm@2.2.0
3 info using node@v0.10.35
4 verbose node symlink /usr/local/bin/node
5 verbose type unexpected_eos
6 verbose stack SyntaxError: Error parsing /usr/local/lib/node_modules/npm/node_modules/columnify/node_modules/wcwidth/node_modules/defaults/node_modules/clone/package.json: Unexpected end of input
6 verbose stack     at Object.parse (native)
6 verbose stack     at readPackage (module.js:113:52)
6 verbose stack     at tryPackage (module.js:123:13)
6 verbose stack     at Function.Module._findPath (module.js:190:18)
6 verbose stack     at Function.Module._resolveFilename (module.js:336:25)
6 verbose stack     at Function.Module._load (module.js:280:25)
6 verbose stack     at Module.require (module.js:364:17)
6 verbose stack     at require (module.js:380:17)
6 verbose stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/columnify/node_modules/wcwidth/node_modules/defaults/index.js:1:75)
6 verbose stack     at Module._compile (module.js:456:26)
7 verbose cwd /Users/Dan/Downloads
8 error Darwin 14.0.0
9 error argv "node" "/usr/local/bin/npm" "search"
10 error node v0.10.35
11 error npm  v2.2.0
12 error path /usr/local/lib/node_modules/npm/node_modules/columnify/node_modules/wcwidth/node_modules/defaults/node_modules/clone/package.json
13 error Error parsing /usr/local/lib/node_modules/npm/node_modules/columnify/node_modules/wcwidth/node_modules/defaults/node_modules/clone/package.json: Unexpected end of input
14 error If you need help, you may report this error at:
14 error     <http://github.com/npm/npm/issues>
15 verbose exit [ 1, true ]
```

**Comment by smikes** [comment]
`npm search` is currently broken but I am working on a replacement, see https://github.com/smikes/npm-kludge-search 

If you would like to help test it, please do

```
$ npm i -g npm-kludge-search
```

The install will take 3-4 minutes since it must download and build the full-text search index locally; in production the index will be distributed via HTTPS, but it'll still take ~1 minute to download since it's 16MB.

Then you can use the search engine per the [README](https://github.com/smikes/npm-kludge-search)
```
$ npm-kludge-search lint       # search for modules with "lint" in keywords, desc, etc.
$ npm-kludge-search -n jshint  # exact name search
```

**Comment by smikes** [comment]
Can this issue now be closed?  Note that there is a previous issue, #6016, that documents problems with the current search implementation.

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by danielbayley** [comment]
Hey, sorry, I did install this in the end.

I'm sure `npm-kludge-search` is a better implementation of npm's search, but it doesn't seem to fix the particular problem I was having, which was when running `npm search` (with no parameters) which used to list all available npm packages.

It sounds like the underlying problem is simply that the index cache file has grown too big (I couldn't even open it in any text editor!). I did download 
it manually with `curl` as was suggested in that other issue, but that didn't fix it.

One thing that did work well was using [jq](http://stedolan.github.io/jq) to do `jq .[]?.name < ~/.npm/registry*/-/all/.cache.json` which worked pretty fast. I'm not sure if that would be an appropriate part of the solution or not?

The reason I wanted a list of all the packages was just that I have a `require` function in my `~/.bashrc` which I can use in scripts to check any packages passed to it and install them if needed (it covers Homebrew, npm and RubyGems).

**Comment by smikes** [comment]
Thanks for taking the time to try out `npm-kludge-search`.  If you have any feedback about that in particular, please open issues for me over at <https://github.org/smikes/npm-kludge-search/issues>

You can get a list of all the npm module name from `npm-kludge-search` by asking it for completions of the empty string:

```
npm-kludge-search -c ''
```

I think your use case (which I didn't understand before, sorry) is a little bit different from the typical user of `npm search`, so using `jq` -- or another streaming json parser/filter -- is a good way of getting it done.

**Comment by smikes** [comment]
Since you have found a workaround for your use case, can this issue now be closed?

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by danielbayley** [comment]
Feel free. Although, the issue was that `npm search` had stopped working and it still doesn't.

**Comment by WORMSS** [comment]
Yeah, search not working is an issue, if you close it because you have acknowledged it is an issue to 1 person, someone will only just make another 'Search is not working' issue.. and you will end up in a horrible cycle.

**Comment by smikes** [comment]
We're already in that cycle! #6016 is the canonical "search is not working" issue.  It's unfortunate that github issues don't have a special field for marking an issue as a duplicate and pointing to the canonical issue.

@danielbayley I think I still misunderstand your use case.  Do you want a list of all existing package names, or do you need more information than just the name?

`npm-kludge-search` with no arguments will return nothing, quickly.  But `npm-kludge-search ''` (with one argument which is empty string) will return a list of all packages, slowly; and `npm-kludge-search -c ''` will return a list of all package names, quickly.

**Comment by danielbayley** [comment]
> We're already in that cycle! #6016 is the canonical "search is not working" issue. It's unfortunate that github issues don't have a special field for marking an issue as a duplicate and pointing to the canonical issue.

Good idea, send them a feature request. I'll close this one if #6016 is the same problem.

> I think I still misunderstand your use case. Do you want a list of all existing package names, or do you need more information than just the name?

Literally only the names, which `npm search` used to give. That's just for my `require` function in bash which I use at the top of shell scripts to make sure any homebrew/npm/RubyGems packages that the script uses are installed. `npm-kludge-search -c ''` works great.

I presume `npm-kludge-search` will eventually be the replacement for the built in `npm search`?

**Comment by smikes** [comment]
Yes, replacement is the eventual goal.
