### ISSUE TITLE
npm publish does not raise error, but new version invisible

### ISSUE THREAD

**Issue by albanm** [npm/npm#7223]
Hello,

I tried to publish a version 0.1.1 of this project:

https://www.npmjs.com/package/xsd2json2

https://github.com/mgdis/xsd2json

Here is the trace for the command ```npm version patch && git push origin master --follow-tags && npm publish```
    v0.1.3
    Username for 'https://github.com': albanm
    Password for 'https://albanm@github.com': 
    Décompte des objets: 4, fait.
    Delta compression using up to 8 threads.
    Compression des objets: 100% (4/4), fait.
    Écriture des objets: 100% (4/4), 412 bytes | 0 bytes/s, fait.
    Total 4 (delta 2), reused 0 (delta 0)
    To https://github.com/MGDIS/xsd2json.git
       5ac30b4..5c7d6c5  master -> master
     * [new tag]         v0.1.3 -> v0.1.3
    + xsd2json2@0.1.3

So no error ! But ```npm install xsd2json2``` does not bring the latest version, nor does it appear when doing ```npm view xsd2json2```.

I suspected a replication delay but it is getting late for that.

Thanks

**Comment by smikes** [comment]
Can you please verify your login credentials by running `npm login` and just hitting RET to accept the stored credentials?

```
$ npm login ; echo $?
```

There should be 3 `https` requests, with status codes `409`, `200`, `201`; the final `echo $?` should print `0`

**Comment by albanm** [comment]
Ok, my bad ! No problem with npm, I simply forgot that my machine is configured to use a private registry (artifactory). After running 'npm set registry http://registry.npmjs.org/' everything works fine.

Sorry for the inconvenience.
