### ISSUE TITLE
npm publish doesn't publish src folder.

### ISSUE THREAD

**Issue by trusktr** [npm/npm#7229]
I'm not sure why, but when I run npm publish, my package's src folder is not published. When I download the tarball at http://registry.npmjs.org/infamous/-/infamous-0.0.29.tgz, I only see infamous.js, package.json, and README.md. I wonder why the src folder and other files aren't being published?

The package source is at http://github.com/infamous/infamous. Any idea what might be happening?

**Comment by trusktr** [comment]
Is my .gitignore file causing the problem?

```
node_modules
dist
npm-debug.log
docs

*.js
!infamous.js

*.js.map
```

**Comment by trusktr** [comment]
Yep, that was it. I had to change `*.js` to `./*.js`.

**Comment by zeke** [comment]
http://en.wikipedia.org/wiki/Rubber_duck_debugging
