### ISSUE TITLE
npm install error when using microflo

### ISSUE THREAD

**Issue by pipiHuang** [npm/npm#7230]
I want to use microflo and I follow the tutorial here: https://github.com/microflo/microflo
when I typed npm install, I got error and I don't konw why. 
I have updated my npm version to 2.3.0 but still couldn't work.
The npm-debug.log file is too long, here is part of npm-debug.log content with error message:
```
318 verbose stack Error: Command failed: Cloning into bare repository '/home/pipi2/.npm/_git-remotes/git-github-com-bergie-component-json-git-b0dd2657'...
318 verbose stack fatal: read error: Connection reset by peer
318 verbose stack
318 verbose stack     at ChildProcess.exithandler (child_process.js:637:15)
318 verbose stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
318 verbose stack     at maybeClose (child_process.js:743:16)
318 verbose stack     at Socket.<anonymous> (child_process.js:956:11)
318 verbose stack     at Socket.EventEmitter.emit (events.js:95:17)
318 verbose stack     at Pipe.close (net.js:466:12)
319 verbose cwd /home/pipi2/git_test/microflo
320 error Linux 3.13.0-34-generic
321 error argv "node" "/usr/local/bin/npm" "install"
322 error node v0.10.25
323 error npm  v2.3.0
324 error code 128
325 error Command failed: Cloning into bare repository '/home/pipi2/.npm/_git-remotes/git-github-com-bergie-component-json-git-b0dd2657'...
325 error fatal: read error: Connection reset by peer
326 error If you need help, you may report this error at:
326 error     <http://github.com/npm/npm/issues>
327 verbose exit [ 1, true ]
328 verbose unbuild node_modules/grunt-noflo-browser
329 info preuninstall grunt-noflo-browser@0.1.9
330 info uninstall grunt-noflo-browser@0.1.9
331 verbose unbuild rmStuff grunt-noflo-browser@0.1.9 from /home/pipi2/git_test/microflo/node_modules
332 info postuninstall grunt-noflo-browser@0.1.9
333 verbose gentlyRm vacuuming /home/pipi2/git_test/microflo/node_modules/grunt-noflo-browser
334 silly gentlyRm purging /home/pipi2/git_test/microflo/node_modules/grunt-noflo-browser
335 silly gentlyRm quitting because other entries in /home/pipi2/git_test/microflo/node_modules
```

**Comment by smikes** [comment]
It looks like you could not connect to github; the error message you are seeing originates with `git`.  One of the dependencies of `microflo`, namely `grunt-noflo-browser`, specifies several dependencies as references to github repositories.  It's generally more reliable for those dependencies to be published to the `npm` registry, as you have noticed.

You may need to troubleshoot / verify that connections to `github.com` work.  See <https://stackoverflow.com/questions/24484327/git-clone-error-read-from-socket-failed-connection-reset-by-peer-fatal-could> for some suggestions on how to do that.

In future, when uploading a long debug log, you can use gist <https://gist.github.com>

**Comment by pipiHuang** [comment]
Thanks  very much for your advice, I have tried to setup github connection with local side but now I still can't solve the problem. 
I am still trying to check my github setting....
The new npm-debug.log is here https://gist.github.com/pipiHuang/849fcbe67503d91e54b3

**Comment by smikes** [comment]
It looks like the error is still `connection reset by peer`

>332 error Command failed: Cloning into bare repository '/home/pipi/.npm/_git-remotes/git-github-com-bergie-component-json-git-b0dd2657'...
332 error fatal: **read error: Connection reset by peer**
333 error If you need help, you may report this error at:

Are you able to execute this on the command-line:

```
$  git clone https://github.com/bergie/component-json
```

**Comment by pipiHuang** [comment]
I can execute this on the command-line, it work: 
`$  git clone https://github.com/bergie/component-json`

I also try to execute this on the command-line: 
`$ git clone https://github.com/bergie/component-json.git`
, it work, too.
I discover that I can not execute this on the command-line: 
`$ git clone git://github.com/bergie/component-json.git`

The same URL with different protocols'(git and https) execution result are different!!

I search on the Internet for solution, it seems that I should setup the "git protocol" with port number 9418, but I fail again...
p.s. my npm version now is 2.4.1 / git version is 1.9.1 / environment is xubuntu 14.04 64bit

**Comment by smikes** [comment]
Sometimes there is a proxy server that blocks the `git://` protocol.  There is a way to work around this in git:

```
$ git config --global url."https://".insteadOf git://
```

**Comment by pipiHuang** [comment]
Thank you very much, it works!!

**Comment by othiym23** [comment]
Closing as resolved.
