### ISSUE TITLE
feature request: npm install -h # install to home directory

### ISSUE THREAD

**Issue by gavinengel** [npm/npm#7238]
I work on some remote web servers where I don't have sudo rights.  At the same time, I'd still like to install some CLI shell tools from npm.  One example is: npm install grunt-cli

Here is what I currently do:
```
cd;
npm install grunt-cli;
cd -;
```

I'd propose to replace that with a little sugar:
```
npm install -h grunt-cli;
# and ...
npm remove -h grunt-cli;
```

I'm able to use the ~/node_modules/.bin by adding this to my ~/.bash_profile:

```
if [[ ! $PATH =~ .*~/node_modules/.bin* ]]; then export PATH="~/node_modules/.bin:$PATH";fi; 
```

Since that line of code in .bash_profile is an important one, I'd also suggest this related feature to check/add it:

```
npm install -h; 
# displays: "Would you like npm to modify your ~/.bash_profile to include ~/npm_modules in shell path?"
# and ...
npm remove -h;
```

(by the way, I use node and npm without sudo using these suggestions: https://gist.github.com/isaacs/579814)

**Comment by othiym23** [comment]
```sh
npm config set prefix "$HOME/npm"
echo 'PATH=$PATH:"$HOME/npm/bin"' >> "$HOME/.bash_profile"
source "$HOME/.bash_profile"
npm install -g grunt-cli # or whatever
grunt # runs grunt
```

will get you the same behavior today, and doesn't reuse `-h`, which is currently used to display the short help.

**Comment by gavinengel** [comment]
Oh silly me :-)  Thank you for the advice.
