### ISSUE TITLE
Error: npm Clone Fails for GitHub Repository in Windows

### ISSUE THREAD

**Issue by mikejr83** [npm/npm#7239]
I have been having path length issues in Windows with npm (it's 2015 and we're still dealing with DOS restrictions?!).

I thought I had resolved them all by moving my `npm` and `npm-cache` folders to `C:\npm` and `C:\npm-cache`, respectively. 

I forked a repository for a npm package and made some modifications and wanted to pull it into my code to consume it.

I am running this at the console:

    npm install -S git://github.com/mikejr83/tfs-unlock#no-sleep

I get an error stating that a directory cannot be created:

> c:\Source\git\my-module>npm install -S git://github.com/mikejr83/tfs-unlock.git#no-sleep
> npm ERR! Failed to clone git://github.com/mikejr83/tfs-unlock.git#9e496b327f123694cd7cd7a17a00c1a4be526b6c from git://github.com/mikejr83/tfs-unlock.git fatal:
> could not create work tree dir 'C:\nt\npm-11904-e4f1f783\1422564021751-0.13411965453997254\9e496b327f123694cd7cd7a17a00c1a4be526b6c'.: No such file or directory
> 
> npm ERR! Failed to clone git://github.com/mikejr83/tfs-unlock.git#9e496b327f123694cd7cd7a17a00c1a4be526b6c from git://github.com/mikejr83/tfs-unlock.git
> npm ERR! Windows_NT 6.1.7601
> npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-S" "git://github.com/mikejr83/tfs-unlock.git#no-sleep"
> npm ERR! node v0.10.35
> npm ERR! npm  v2.2.0
> npm ERR! code 128
> 
> npm ERR! Command failed: fatal: could not create work tree dir 'C:\nt\npm-11904-e4f1f783\1422564021751-0.13411965453997254\9e496b327f123694cd7cd7a17a00c1a4be526b6c'.: No such file or directory
> npm ERR!
> npm ERR!
> npm ERR! If you need help, you may report this error at:
> npm ERR!     <http://github.com/npm/npm/issues>
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     c:\Source\git\my-module\npm-debug.log

I tried moving the npm's `tmp` folder to `C:\nt` (as seen in the error output) but it doesn't work either.

Here is a pastebin of the (npm-debug.log)[http://pastebin.com/xZGUUR1S]

Other things I've tried:
* Security - made *Everyone* group have read/write on the folder.

**Comment by smikes** [comment]
There were some bugs with `npm` and `git` dependencies, specifically on Windows.  Can you try updating to `npm`@`next` (the bleeding edge version, `2.5.0`) and see if the problem persists?

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

To get the `next` version of npm, you will need to run 

```
npm install npm@next
```

**Comment by mikejr83** [comment]
Version `2.5.0` resolved it.

Do you know when this was introduced? I'm pretty sure the out-of-the-box version of npm with nodejs worked fine. I wasn't using a git repository for a package but I recall testing pulling my module I'm developing as a git package on another machine.

During recent development I was having a module complain about npm not being on a later version so I upgraded to the latest (using the technique above). This is the first time I've had the issue.

I have other devs that I'm pretty sure are on the out-of-the-box version and yet to upgrade. I suppose I'll have them hold off until 2.5.0 is released.

Thanks.

**Comment by smikes** [comment]
I think it might have gone in around 2.1.17 and got fixed around 2.3.0 -- see <https://github.com/npm/npm/blob/master/CHANGELOG.md> for some notes about the git changes.

If `2.4.1` works for this (it should; I don't see any git-related changes between 2.4 and 2.5) then I highly recommend updating everyone to `2.4.1`; it's faster and less buggy and has fewer race conditions than 1.4.28.

The next `node` stable distribution (0.10.37) will have 2.3.0 in it, and I think that'll be coming out in a week or two, so waiting until then is another valid option.

**Comment by mikejr83** [comment]
Awesome. Thanks for the help!

I'll be going to 2.4.1 and shoot the others a link on how to upgrade.
