### ISSUE TITLE
npm install with caret (^) version doesn't install semvar PATCH (0.0.X)

### ISSUE THREAD

**Issue by johnkchiu** [npm/npm#7240]
(Using npm version 2.1.18)

We have some dependencies in our package.json where it's a PATCH version (e.g. 0.0.1).   It's added to our package.json as:

`"moduleX": "^0.0.1"`

When a new PATCH version is available (e.g. 0.0.2), npm install will not install the newer version.

**Comment by iarna** [comment]
This is intended behavior: `^` allows any version greater than the version listed where the most-significant digit doesn't change.

**Comment by iarna** [comment]
Specifically, see:

https://github.com/npm/node-semver#caret-ranges-123-025-004

> Allows changes that do not modify the left-most non-zero digit in the [major, minor, patch] tuple. In other words, this allows patch and minor updates for versions 1.0.0 and above, patch updates for versions 0.X >=0.1.0, and no updates for versions 0.0.X.

**Comment by smikes** [comment]
Can this issue now be closed?

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by johnkchiu** [comment]
Yes - intended behavior, so closing.
