### ISSUE TITLE
npm link is not respected in sub modules

### ISSUE THREAD

**Issue by joshball** [npm/npm#7241]
**It appears as if `npm link` is not honored in sub modules. Is this a feature or a bug?**

Assume you 3 publicly inaccessible (no inbound VPN rules) modules:  

	'server': 'git+ssh://inaccessible.stash/server.git',
	'plugin': 'git+ssh://inaccessible.stash/plugin.git',
	'library': 'git+ssh://inaccessible.stash/library.git',

And the projects have the following dependencies:

    server/package.json:
	'plugin': 'git+ssh://inaccessible.stash/plugin.git',

    plugin/package.json:
	'library': 'git+ssh://inaccessible.stash/library.git',
	

if you do an `npm install` on server, it will try and access the inaccessible.

So, you can solve this with a `git subtree` and `npm link`:

From the server module, add the two subtrees:

	git subtree add --prefix=local/modules/plugin  plugin  master --squash 
	git subtree add --prefix=local/modules/library library master --squash 

And then in your package.json.scripts, add: 

    "preinstall": "npm link local/modules/plugin && npm link local/modules/library",
    "preupdate": "npm link local/modules/plugin && npm link local/modules/library",

Now when `npm install` is run, it will fetch 'plugin' from the right location. However, when `npm install` is run recursively on node_modules/plugin, and 'library' is being fetched, it will not use the npm link version.

I would think/hope the npm link would be honored, but it appears not.

**Workaround:**

Change the `local/modules/plugin/package.json` 'library' dependency from `"dependencies"` to `"devDependencies"`

And then the top level package.json will be honored.

**Comment by joshball** [comment]
I have a repo that you can fork, tweak, and use to reproduce it here: https://github.com/joshball/npm_link_local_subtrees_in_heroku

**Comment by rlucha** [comment]
+1

**Comment by ehsalazar** [comment]
@joshball We're working our way through some older issues. This may be something you've already moved beyond but please check out the pull request for a suggested fix. I'll close this out for now, but will be happy to reopen if needed.

**Comment by joshball** [comment]
Thanks @iarna, it has been a while. It has been a while, and I have long since abandoned this, but I am still curious if the problem demonstrated is a bug or a feature? Either way, @ehsalazar, I think it should either be documented as a feature or reopened as a bug. 
Thoughts?

**Comment by iarna** [comment]
The way that you were using it, you were asking npm to make a global install of a local module, and then link from that global module into the current `node_modules` folder. That global install has to be able to stand alone without any help from the local module path, since it can be reused between modules.

You seemed to expect it to just be the equivalent of `ln -s` but with some sugar to know about the `node_modules` folder? I think the [`npm link](https://docs.npmjs.com/cli/link) documentation is pretty clear, but we would absolutely be interested in how to improve it.
