### ISSUE TITLE
io.js engine metadata definition in package.json

### ISSUE THREAD

**Issue by h2non** [npm/npm#7245]
I'm just wonder about how to declare this properly. Additionally I want to know if the npm is currently performing any kind of validation taking into account which can of JS engine is being used at runtime via `process.versions`

```json
{
  "name": "cool-multiengine-package",
  "engines": {
      "node": ">= 0.10.0",
      "iojs": ">= 1.0.3"
  }
}
```

**Comment by h2non** [comment]
Sorry! I've created the issue without content. Now is there!

**Comment by KenanY** [comment]
I believe this was discussed at https://github.com/iojs/io.js/issues/269.

**Comment by othiym23** [comment]
Closing in favor of iojs/io.js#269, but I will say that npm currently does not support iojs engine enforcement, and it does not look at the v8 version. The emerging consensus is that we should probably support the former in some capacity but that the latter is a bad idea. In general, feature testing seems to be the favored approach, especially when it comes to ES6 features trickling out into V8.

**Comment by h2non** [comment]
Thanks!

**Comment by shels107** [comment]
1212124545456565653232298989878787845454565656532221212455565658898787878454546556512322323232323233232333
