### ISSUE TITLE
Error with the package.json?

### ISSUE THREAD

**Issue by Icytheory** [npm/npm#7246]
This is what I get when I type npm start:

npm ERR! Failed to parse json
npm ERR! Unexpected end of input
npm ERR! File: /srv/gsd/node_modules/node-v0.10.30/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! System Linux 2.6.32-431.el6.x86_64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! cwd /srv/gsd/node_modules/node-v0.10.30
npm ERR! node -v v0.10.30
npm ERR! npm -v 1.4.21
npm ERR! file /srv/gsd/node_modules/node-v0.10.30/package.json
npm ERR! code EJSONPARSE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /srv/gsd/node_modules/node-v0.10.30/npm-debug.log
npm ERR! not ok code 0

Thanks for the help! :)

**Comment by KenanY** [comment]
Can you post `/srv/gsd/node_modules/node-v0.10.30/package.json` here?

**Comment by Icytheory** [comment]
When I open the package.json, there is nothing in it.

**Comment by KenanY** [comment]
Well that definitely sounds like your issue :) As the error message states, `package.json` must be a valid JSON file. A blank file is not valid.

Also, `npm start` requires a `package.json` to define what to run. What are you _expecting_ to happen when you run `npm start` without defining the `"start"` script in `package.json`?

The docs on [`npm start`](https://docs.npmjs.com/cli/start) and [scripts](https://docs.npmjs.com/misc/scripts) might help :)

**Comment by Icytheory** [comment]
I want it to run my gsd daemon for a minecraft control panel

**Comment by KenanY** [comment]
@Icytheory Sorry, but that's something that `npm` does not do by default when you run `npm start`. Your issue now really isn't `npm` related so I can't help you very much here (and I doubt many others can help you with a gsd daemon here on the `npm` issue tracker). One thing I could suggest is to have this in your `package.json`:

``` json
{
  "scripts": {
    "start": "command to start gsd daemon goes here"
  }
}
```
