### ISSUE TITLE
Unable to find remote helper for 'https'

### ISSUE THREAD

**Issue by youssefdetovernickr** [npm/npm#7248]
Hey. Whenever I'm trying to install a package, using PowerShell, CMD, or just using Atom, it seems to fail. It didn't before I used the chocolatey version. I tried to reinstall that version only the same bug is happening for me.

This is an output trying to install a package using Atom.

    Installing “autocomplete-plus@2.0.4” failed.Hide output…

    npm WARN `git config --get remote.origin.url` returned wrong result (https://github.com/Benvie/harmony-collections.git) 
    npm ERR! git clone https://github.com/Benvie/harmony-collections.git Cloning into bare repository 'c:\Users\roobi_000\.atom\.node-gyp\.atom\.apm\_git-remotes\https-github-com-Benvie-harmony-collections-git-df214100'...
    npm ERR! git clone https://github.com/Benvie/harmony-collections.git fatal: Unable to find remote helper for 'https'
    npm ERR! Windows_NT 6.2.9200
    npm ERR! argv "c:\\Users\\roobi_000\\AppData\\Local\\atom\\app-0.176.0\\resources\\app\\apm\\bin\\\\node.exe" "c:\\Users\\roobi_000\\AppData\\Local\\atom\\app-0.176.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\Users\\roobi_000\\AppData\\Local\\atom\\app-0.176.0\\resources\\app\\apm\\.apmrc" "--userconfig" "c:\\Users\\roobi_000\\.atom\\.apmrc" "install" "C:\\Users\\ROOBI_~1\\AppData\\Local\\Temp\\d-115031-4604-1if169g\\package.tgz" "--target=0.20.0" "--arch=ia32" "--msvs_version=2013"
    npm ERR! node v0.10.35
    npm ERR! npm  v2.3.0
    npm ERR! code 128

    npm ERR! Command failed: Cloning into bare repository 'c:\Users\roobi_000\.atom\.node-gyp\.atom\.apm\_git-remotes\https-github-com-Benvie-harmony-collections-git-df214100'...
    npm ERR! fatal: Unable to find remote helper for 'https'
    npm ERR! 
    npm ERR! 
    npm ERR! If you need help, you may report this error at:
    npm ERR!     <http://github.com/npm/npm/issues>

My PATH is configured correctly and has "C:\Program Files (x86)\Git\bin;" in it.

On Windows 8.1

**Comment by youssefdetovernickr** [comment]
Removing Visual Studio 2013 solved this problem for me.

**Comment by othiym23** [comment]
```
npm ERR! git clone https://github.com/Benvie/harmony-collections.git fatal: Unable to find remote helper for 'https'
...
npm ERR! fatal: Unable to find remote helper for 'https'
```

It's not clearly labeled as such, but this is output from git. What version of Git do you have installed? Is it possible that you have more than one, and the wrong one is found when searching your `%PATH%`?

**Comment by smikes** [comment]
Is this still a problem for you?

Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

There have been a lot of improvements to npm -- especially around git dependencies on Windows -- since 2.3.0. Can you try updating your npm installation?

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as abandoned. Much has changed with git since January, so it may be worth a try just to upgrade to `npm@latest` whenever you come back to this issue.

**Comment by trusktr** [comment]
@othiym23 I'm getting this error, but I don't think I've done anything wrong. I have

```
 ❯ git --version                                                      [09:54:35]
git version 2.3.2 (Apple Git-55)

 ❯ npm -v                                                             [09:54:38]
3.2.0
```

and package.json looks like this

```js
{
...
  "dependencies": {
    "army-knife": "^0.2.1",
    "async": "^0.9.0",
    "big.js": "^2.5.1",
    "bignumber.js": "^1.4.1",
    "bootstrap": "^3.2.0",
    "bootstrap-datepicker": "^1.3.0",
    "famous03": "git+https://github.com/trusktr/famous.git#jspm",
    "infamous": "^0.0.37",
    "james-bond": "^0.0.0",
    "jquery": "^2.1.1",
    "jquery-tooltipster": "git+https://github.com/iamceege/tooltipster.git#3.2.6",
    "jsfromhell": "git+https://github.com/jonasraoni/JSFromHell.git#master",
    "jss": "^0.10.1",
    "jss-nested": "^0.1.4",
    "leaflet": "git+https://github.com/RickMohr/Leaflet.git#better-inertial-scrolling",
    "operative": "^0.3.2",
    "string": "^3.0.0"
  }
}
```

**Comment by mhart** [comment]
I suspect this was actually a similar case to this: https://github.com/npm/npm/issues/13353
