### ISSUE TITLE
Support showing the available scripts on npm run --help

### ISSUE THREAD

**Issue by kentcdodds** [npm/npm#7250]
Initially requested in [this tweet](https://twitter.com/kentcdodds/status/561636694567305216). I think I'll look into this. This issue is simply to track the request :-)

**Comment by kentcdodds** [comment]
@othiym23, I believe what I want to edit is the `.usage` property [here](https://github.com/npm/npm/blob/master/lib/run-script.js#L10). But I need to read the package.json. To do this I'd have to either read it synchronously or figure out how to set it asynchronously. Am I thinking along the right lines, or is there a better way to do this?

**Comment by othiym23** [comment]
Whoops... before you get too far into this, take a look at what happens when you run plain ol' `npm run-script`. ;)

**Comment by kentcdodds** [comment]
bwaha!

**Comment by othiym23** [comment]
:tada:
