### ISSUE TITLE
As typed 'npm install',I can't finished,pls help me solve it

### ISSUE THREAD

**Issue by vagusX** [npm/npm#7253]
```
npm ERR! git clone ssh://git@github.com:destec/node-trello.git Cloning into bare repository '/home/vagusx/.npm/_git-remotes/ssh-git-github-com-destec-node-trello-git-71be7e20'...
npm ERR! git clone ssh://git@github.com:destec/node-trello.git warning: templates not found /home/vagusx/.npm/_git_remotes/_templates
npm ERR! git clone ssh://git@github.com:destec/node-trello.git ERROR: Repository not found.
npm ERR! git clone ssh://git@github.com:destec/node-trello.git fatal: Could not read from remote repository.
npm ERR! git clone ssh://git@github.com:destec/node-trello.git 
npm ERR! git clone ssh://git@github.com:destec/node-trello.git Please make sure you have the correct access rights
npm ERR! git clone ssh://git@github.com:destec/node-trello.git and the repository exists.
npm ERR! Linux 3.13.0-37-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v0.11.15
npm ERR! npm  v2.1.6
npm ERR! code 128
```

**Comment by othiym23** [comment]
1. There are some issues with npm's use of Git in older versions. Can you update to the latest version of npm (`npm -g install npm`) and see if that makes a difference?
2. What does your `package.json` look like?
3. Does the problem persist if you use Node 0.10.36 or 0.11.16? There was an issue with `url.parse` that caused problems with Git dependencies, and I believe 0.11.15 was one of the versions affected.

**Comment by caiya** [comment]
TI've installed node 0.10.35 and 0.11.15,and followed your suggestions.Now I have node 0.10.36 and 0.11.16,but the problem didn't disappear.I can manage this project in company's computer,but this time I met this at home. ;-(

**Comment by smikes** [comment]
Have you updated your version of `npm`?  You will still need to update `npm` as even the latest versions of node `0.10.36` and `0.11.16` shipped with an older `npm`.

To update npm, run `sudo npm -g install npm@latest`

Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

Thanks!

**Comment by misterdjules** [comment]
@caiya @smikes `npm install git+ssh://git@github.com:destec/node-trello` fails with the same error on my machine with node v0.11.15 on OS X, but it works with node v0.11.16.

**Comment by smikes** [comment]
@misterdjules Thanks.

@caiya When you get back to the machine where this error is happening, can you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

**Comment by caiya** [comment]
https://gist.github.com/27851b1d327a28f98997.git

@smikes  this is my npm-debug.log.Pls have a look

**Comment by caiya** [comment]
And I also wanna know why always this blew?
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/npm-package-arg requires semver@'4' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/semver,
npm WARN unmet dependency which is version 2.3.0
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/read-installed/node_modules/readdir-scoped-modules requires graceful-fs@'^3.0.4' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/graceful-fs,
npm WARN unmet dependency which is version 3.0.2

**Comment by smikes** [comment]
> npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/npm-package-arg requires semver@'4' but will load 

This messages are generally caused when people have run `npm update -g` which is not a safe command; it updates dependencies without synchronizing between different subdependencies.

**Comment by smikes** [comment]
It looks like you are trying to clone a git repository as a logged-in user, but this is failing.  From your log:

> 617 error git clone git@github.com:destec/node-trello.git Warning: Permanently added 'github.com,192.30.252.129' (RSA) to the list of known hosts.
617 error git clone git@github.com:destec/node-trello.git **Permission denied (publickey).**
617 error git clone git@github.com:destec/node-trello.git fatal: Could not read from remote repository.

You can either configure your `ssh` to have access to your private key (via `ssh-agent`) or specify the dependency as `git+https` to work around this problem.

**Comment by caiya** [comment]
@smikes so how can I fix the dependencies?

**Comment by smikes** [comment]
**DO NOT** do `npm update -g`.

That's how you get broken dependencies in the first place. :-/

The simple solution is just to force reinstallation of `npm`; 

```
npm install -g npm@2.4.0
npm install -g npm@latest
```

**Comment by caiya** [comment]
@smikes  I've tried  ' npm update  -g' ;-(  
but I am going to try  reinstallation

**Comment by timoxley** [comment]
> DO NOT do npm update -g.

`update` needs to be taken out the back and shot.

**Comment by caiya** [comment]
@timoxley I've done it.Could you tell me how to fixed this or this won't be a problem??

**Comment by timoxley** [comment]
@caiya haha, sorry, it was just a general comment, not an instruction.

General guideline: always use `npm install`, never use `npm update` because it doesn't do what you think it does.

**Comment by smikes** [comment]
Can this issue now be closed?

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by caiya** [comment]
@smikes Thank you all for this! I would like to tell you the answer is yes~

**Comment by othiym23** [comment]
Closing as resolved!
