### ISSUE TITLE
npm conflates 'install as cli command', 'install globally', and 'link'

### ISSUE THREAD

**Issue by loveencounterflow** [npm/npm#7256]
Having developed with NodeJS and npm for quite a while, i have a collection of own modules with a fair number of cross-dependencies. I normally use `npm link` when writing a new module to reference my existing modules that the new one depends on. 

The intention for doing so is, of course, to avoid having a copy of the dependency, and, if that dependency should change, to see those changes immediately. 

From this point of view, it is a mere side-effect that `npm link` creates a *global* link—and could be treated as an implementation detail were it not for the fact that `npm link` changes the environment such that having done `npm link` from module `foo` all of a sudden all modules on that system can `require 'foo'` even without having that module installed. 

Among other things, this means that a module `bar` which used to have a problem because it has a missing dependency entry `foo` in its `package.json` all of a sudden looks (superficially) fixed. This fact makes developing modules with correctly stated dependencies harder.

There's yet another, related problem: often when i do `npm install -g magic-unicorn`, i do that because i want to have that great `magic-unicorn` CLI command at my fingertips in the console. Again, from this point of view, it is a rather undesirable side-effect that installing the CLI command in this way implies that now all my modules can `require( magic-unicorn' );` without a stated dependency and without a dedicated, local installation.

The obvious ways to fix the first problem are **(1)** to link local dependencies manually using `ln -s ...`, **(2)** to add an option / configuration to npm for 'local' links (those could still be managed via a globally shared folder, but one that is not on `require.resolve()`'s list).

To fix the second issue could be solved **(1)** manually by setting up a collective folder for npm-installable command line tools, call it `~/npm-commands`, install CLI tools into `~/npm-commands/node_modules`, and link their respective binaries into `~/npm-commands/bin` or some other suitable location on the shell's path; **(2)** by adding an option or configuration to npm to 'install globally, but executables only, please'.

Does that make sense?

**Comment by othiym23** [comment]
Most of this issue seems to be predicated on a misunderstanding, so I want to make sure I'm understanding your description of your problem:

> all modules on that system can require 'foo' even without having that module installed.

This is only true for globally-installed packages. If you want to use a linked module in another local project, you have to run `npm link <module>`. Unless you're using the long-deprecated `NODE_PATH`, Node / io.js doesn't know that it should be looking in the global prefix at runtime. Even if you have packages `a` and `b` globally linked (but with their actual directories under, say, `$HOME/projects`), `a` won't be able to see `b`, and vice versa. If you `npm -g install c`, `c` *will* be able to see both `a` and `b`, but npm doesn't care about that when performing global installs, and that's not the problem you're describing anyway.

I'm curious: what is the specific problem you're encountering?

**Comment by loveencounterflow** [comment]
Well, it's less of a problem than a nuisance—which, as per your `$NODE_PATH` hint, may well be able to resolve partially; a quick check on a virtual machine would indicate so. I must have set that `$NODE_PATH` thing years ago and just forgot about it. To hear that `link`ing doesn't amount to making things globally available is good news. 

The thing i'm after here is the work that often goes into getting all dependencies right when publishing a module. There are several things that need attention: When you install a module, maybe you forgot the `--save` switch, so the dependency is not on record (i've meanwhile configured npm to always `--save` implicitly); likewise, when you uninstall, an unnecessary dependency may be left behind. 

The next thing that can bite you are global installs that are always available: you write that `require` line in your code but forget to `npm install`. In that case, your module seems to work—on those machines that have the dependency globally installed, but not on all the others. Now that you kindly have identified `$NODE_PATH` as the perpetrator here, the biggest source for that nuisance—lacking dependency records of linked modules—has hopefully just gone away.

It still feels a little strange that i can can by default `require` a module that i installed just because it's such a great CLI tool, but then i guess i can live with that.

BTW the docs do not seem to be so adamant about `$NODE_PATH` being deprecated; they even state that "it might be useful to also add the /usr/lib/node_modules folder to the `$NODE_PATH` environment variable", which to me reads more like a statement of endorsement than one of decommissioning.
