### ISSUE TITLE
download less and use less disk space

### ISSUE THREAD

**Issue by Bigous** [npm/npm#7259]
I think that 2 things could be improved to node_modules and npm ... 
1 - reuse already downloaded module instead of copy it again, and again, and again for each module that depends on the same version of the module (see module request in yo for example)
2 - could use a single file to bundle all the modules instead of a directory (like a tar or a zip or even a 7z file). It should save a lot of space and avoid path limitations on some SO (like windows) when there is a big depth of dependencies.

**Comment by KenanY** [comment]
> reuse already downloaded module

This is already done to a certain extent (although I don't know such extent). For example:

``` bash
$ npm install hawk
$ npm ls
@ /
└─┬ hawk@2.3.0
  ├── boom@2.6.1
  ├── cryptiles@2.0.4
  ├── hoek@2.10.0
  └── sntp@1.0.9
```

The `npm ls` doesn't show it, but:

  - `cryptiles` depends on `boom`
  - `boom` depends on `hoek`
  - `sntp` depends on `hoek`

Yet only one of each of these modules are installed :) also there is always `npm dedupe`

> a single file to bundle all the modules instead of a directory

So, replace `node_modules/` with, for example, `node_modules.tgz` (sorry if I'm mistaken)? This would require a complete overhaul of `require()` so that it can decompress this file every time an uncached module is `require()`ed. Also this might mess with global packages (can you execute a binary that's in a compressed file?).

**Comment by Bigous** [comment]
Hi @KenanY ,

In fact I was with an older version of npm (1.4) and now, with 2.3 its a lot better.

The idea behind node_modules.tgz or .7z is to have a database-like file with the resources you need to execute your application.
You can execute files (when it's an .exe) by writing it to the cache and running from there, but the great majority of the modules are pure JS. So, it is not a big deal to unzip it in memory and run it (just like java does with JAR, WAR or EAR files).
It's another way to see things... I'm not talking about to forget the way it's resolved today, only talking to give us an option to do the packing of the system, because, specially on windows, paths cannot have more than 1024 bytes and with large depth structures it is fastly achived.

tks for your reply.

**Comment by iarna** [comment]
Zipping node_modules is a non-starter as it would require changes to the node.js module loader, which is out-of-scope for npm. (And it's a frozen API in node, so you're unlikely to get much traction there.)

I'd also point out that the multi-stage intall project, landing in npm@3, will bring a maximally flattened node_modules folder, which also results in a much more aggressively deduped tree. The flattening and deduping mean that Windows path limits almost never are an issue.

**Comment by Bigous** [comment]
Hi @iarna. I Know, that's why I've started talking about it in iojs repository, and they pointed out that the discussion should be started here first.
It's nice to know that the npm@3 will have a much more flatten node_modules it will save space and link.
Yet I think it would be more eficient to have it on a single file and there are some other reasons than the path limit like:
- Filesystems are chunked and a lot of script files uses much more space than a single one - eficiency;
- Some systems have case sensitive filesystems while in others it's not - standardization;
- Less FAT speed interfering on system load speed;
- Easily compressable (yet it could be maintened uncompressed to maximize execution eficiency over space).

Thanks for your analisis.
