### ISSUE TITLE
npm publish on legacy uppercase named module broken

### ISSUE THREAD

**Issue by dominictarr** [npm/npm#7260]
I was unable to publish a new version of JSONStream,
which has had uppercase characters in the name since before they where disallowed.
I have been able to publish many versions of this since then, but it has broken just now.

```
$ npm pub
npm ERR! Linux 3.18.2-2-ARCH
npm ERR! argv "node" "/usr/bin/npm" "pub"
npm ERR! node v0.10.35
npm ERR! npm  v2.4.1

npm ERR! Invalid name: "JSONStream"
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/dominic/c/JSONStream/npm-debug.log
```

**Comment by othiym23** [comment]
Yay! We fixed this after THE ENTIRE UNIVERSE broke because of this issue! I don't remember when, though. Thanks for putting up with us for as long as it took us to deal with this, @dominictarr!
