### ISSUE TITLE
Skipping npmignore for giturl packages

### ISSUE THREAD

**Issue by maxkorp** [npm/npm#7262]
Is this possible? It seems strange that the npmignore is used for installs from a giturl.

In a repository, usually code is intended to not have built output (eg compiled coffeescript or such), but the npmignore in my view is intended to exclude files not needed for the published package. 

As it is, to support installs from both the registry and a giturl, I have to either include the compiled/generated output of my project in my git repository (not ideal) or I have to include the code used to generate that compiled code in the published package, even though the code is already generated (also not ideal). 

Is this intended? If so, is there any good way around it? Sorry if I'm missing something, I've been searching around for a while and haven't found anything.

**Comment by smikes** [comment]
Some people address this by using a `my-publish` script in `package.json` that executes any necessary build steps and then runs `npm publish`, failing with a noisy error message if the build steps fail to produce output.

Can you tell me more about your use case?  Why do you want to support installs from both the registry and the repository?

**Comment by smikes** [comment]
I read about half of it carefully and skimmed the second half - sorry, on a device. This sounds like an interesting project though. 

I think I would probably recommend starting a second release channel for your unstable line, if you really have a lot of people depending on your unpublished versions. 

But let me think about this a bit. I might have to take a look at all the stuff you're doing to get a sense of what the variables are. 

Another thought is maybe to split the native module into its own repo if that's not already the case.

**Comment by maxkorp** [comment]
Well it's entirely a native module (Theres a _bit_ of javascript, but it's mostly there to either add a little convenience on to the C++ or to bind it together). Unless you mean like having a repo for generating code, and a second repo (which is for the package) which is just the generated code. Plausible, but seems a bit uncouth. 

Something I hadn't considered, would publishing from a tarball (so we have some script generating the tarballs ready to go, removing unneeded files beforehand etc) work? Then there's no npmignore in the first place.

**Comment by smikes** [comment]
No, I was just confused. I need to think about this before I can comment intelligently.

**Comment by smikes** [comment]
1. Publishing from a tarball would definitely work

2. Having separate 'stable' and 'next' release lines with dist-tags that follow the different dev branches is probably what I would recommend, to reduce your users' dependence on `github`-based installs , if you wanted to do that (that's the way I'd go)

3. This is a really impressive amount of work that you're putting in to make `nodegit` work in a wide diversity of setups.  Have you thought about giving a conference talk about this?  I would really love to see lower barriers for native-code-using modules, and it looks like you've pretty much run into -- and dealt with -- every kind of problem you can.  (Well, maybe not ARM6 support?)

**Comment by kmanion** [comment]
Hi @maxkorp , it looks like you've gotten some help with this issue. 

We're trying to close out some of the older support issues. Please don't hesitate to reopen if you are still running into this or email us at support@npmjs.com

Kiera, npm technical support
