### ISSUE TITLE
Dedupe: npm ERR! cb() never called!

### ISSUE THREAD

**Issue by mantoni** [npm/npm#7266]
I get `npm ERR! cb() never called!` when running `npm dedupe` with all the newer npm client versions. I can reliably reproduce it with a very large (>100 modules) install, but don't have a small working example, unfortunately.

So I narrowed it down by trying various versions of npm. After each change of the npm version, I ran this:

```
rm -rf node_modules
npm cache clear
npm install --no-shrinkwrap
npm dedupe
```
- Affected versions: `2.1.10`, `2.1.11`, `2.1.14`, `2.1.18`, `2.2.0`, `2.3.0` and `2.4.1`
- Working versions: `2.1.7`, `2.1.8` and `2.1.9`

So it appears the issue was introduced in `2.1.10`.

I started looking through the [diff v2.1.9..v2.1.10](https://github.com/npm/npm/compare/v2.1.9...v2.1.10), but I'm not enough into npm change history to find my way through. Since I know how difficult this is to reproduce, I'm happy to help by applying patches to my local npm install.

Thanks for looking into this. I'm very excited about the upcoming major release with dedupe being the default, hoping this is not going to be an issue in v3 anymore.

Running on Red Hat Linux with Node 0.10
Might be related to #7014

**Comment by smikes** [comment]
Thanks for the bug report.

**Comment by michaek** [comment]
From my testing, it seems `npm outdated` fails with the same error after that release as well.

**Comment by iarna** [comment]
If you could try this with `2.5.0` it would be much appreciated. (We think we may have fixed the bug with it.)

**Comment by mantoni** [comment]
@iarna Just tried again with `2.5.0`, but unfortunately same same.

**Comment by dangreen** [comment]
I'v got same problem

    ~$ sudo npm update -g   
    npm ERR! cb() never called!

**Comment by smikes** [comment]
@dangreen Don't run `npm update -g` -- it will not do what you want.

Instead, try something like

```
npm install -g npm-check
npm-check -g -u
```

**Comment by dangreen** [comment]
@smikes before it worked

**Comment by smikes** [comment]
@dangreen: It "works", it's just that it does something unexpected, see <https://github.com/npm/npm/issues/6895#issuecomment-66505202>

> You probably don't want to be using npm update -g. It doesn't do what you think it does. It recursively updates dependencies of modules, not updates modules.

**Comment by mantoni** [comment]
Found it! While trying to trace down the error, it occurred to me that npm is opening a very large number of files concurrently while deduping. I checked `ulimit -n` and it was 1024. Changing it to a larger value makes dedupe work (I only checked `v2.6.0`).

So something in the way installs are done changed in `2.1.10` causing it to open too many files at the same time. This should either be throttled in some way or at least a more helpful error message should be printed.

From what I read about the plans for `npm@3`, it's likely that this is not going to be an issue anymore. However, at some point the OS limits will always be reached.

**Comment by mantoni** [comment]
I'm currently able to reproduce this issue on @isaacs' node-tab v1 branch on a Mac. At the same time, it appears to be fixed with `2.9.0`.

```
$ git clone git@github.com:isaacs/node-tap.git
$ cd node-tap
$ git checkout -b v1
$ npm i
npm ERR! cb() never called!
```

Checking the ulimit:

```
$ ulimit -n
2560
```

Increasing the ulimit to 10000 makes the install work with npm `2.8.4`.

Interestingly, upgrading to npm `2.9.0` fixes the issue. I can even reduce the ulimit to 50 and it still works.
I didn't find any related notes in the changlog so it might just work now by coincidence. I leave it to you whether this can be considered fixed and closed, but it might be interesting to investigate what the root cause of this was.

/cc @smikes @othiym23 @iarna

**Comment by smikes** [comment]
I think @othiym23 made some changes to work around a low ulimit in OSX Yosemite , so that may coincidentally be fixing an unrelated issue..?

**Comment by mantoni** [comment]
I did another check on a large project that has the issue when running `npm dedupe`. I can still reproduce it there with npm `2.9.0` on Linux. :disappointed:
Yes @smikes, it seems to be an unrelated issue.

**Comment by kesla** [comment]
this is happening for us as well in dedupe, same as above - big project with lots of dependencies.

**Comment by kesla** [comment]
Running node 0.10 on ubuntu. Tried with npm 2.0.0, 2.1.9, 2.9.0 and 2.9.1 but none of them works

**Comment by kesla** [comment]
downgrading to 2.1.9 did actually work.

**Comment by mantoni** [comment]
OMG this is now (almost) 3 major versions old. Closing.

**Comment by ach5910** [comment]
Thank you everyone for your help!!! I was trying to run `npm install -g react-native-cli` and was getting:
"Unhandled rejection Error .... npm ERR! cb() never called!"
After finding this thread and running
`npm update -g`
all errors were solved. Thank to everyone for sharing their findings
