### ISSUE TITLE
Error while installing my package after publishing

### ISSUE THREAD

**Issue by MrVinitBansal** [npm/npm#7267]
```
E:\NodeProjects\nodejs\Math_user_vinit>npm install math_module_first
npm ERR! Error: ENOENT, chmod 'E:\NodeProjects\nodejs\Math_user_vinit\node_modul
es\math_module_first\main.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "math_module_first"
npm ERR! cwd E:\NodeProjects\nodejs\Math_user_vinit
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! path E:\NodeProjects\nodejs\Math_user_vinit\node_modules\math_module_fi
rst\main.js
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! not ok code 0
```

**Comment by KenanY** [comment]
@MrVinitBansal Could you try upgrading to the latest version of `npm`? We're on `2.4.1` but you're on `1.4.28`. It can be a little tricky on Windows but we have [a guide](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows) for it.

**Comment by MrVinitBansal** [comment]
After updating my node and npm, if I install the the error is changed but error is still there:

E:\NodeProjects\nodejs\Math_user_vinit>npm install math_module_first
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "node" "C:\\Users\\Vinit\\AppData\\Roaming\\npm\\node_modules\\npm
\\bin\\npm-cli.js" "install" "math_module_first"
npm ERR! node v0.10.36
npm ERR! npm  v2.4.1
npm ERR! path E:\NodeProjects\nodejs\Math_user_vinit\node_modules\math_module_fi
rst\main.js
npm ERR! code ENOENT
npm ERR! errno 34

npm ERR! enoent ENOENT, chmod 'E:\NodeProjects\nodejs\Math_user_vinit\node_modul
es\math_module_first\main.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     E:\NodeProjects\nodejs\Math_user_vinit\npm-debug.log

**Comment by MrVinitBansal** [comment]
Please reply as soon as possible. I am completely new to node.js. I want to make a command on it and initial support will be very helpful for me. Please provide continuous and quick support.

**Comment by KenanY** [comment]
@MrVinitBansal Sorry, real-life has ways of keeping me busy offline :)

Anyways, I've looked into your module and I spotted this in your `package.json`:

```
  "main": "bin/main.js",
  "bin": {
    "math_module_first": "main.js"
  },
```

Looks like `bin.math_module_first` should be pointing to `bin/main.js` rather than `main.js`? That might explain the error:

```
npm ERR! enoent ENOENT, chmod 'E:\NodeProjects\nodejs\Math_user_vinit\node_modul
es\math_module_first\main.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
```

Seeing as how there is no `main.js` in the root of your package.

**Comment by MrVinitBansal** [comment]
I am still getting the same error. I think the solution you told didnot play any role. Please if you don't know then don't waste my time and get it solved by some other person who knows it perfectly

E:\NodeProjects\nodejs\Math_user_vinit>npm install math_module_first
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "node" "C:\\Users\\Vinit\\AppData\\Roaming\\npm\\node_modules\\npm
\\bin\\npm-cli.js" "install" "math_module_first"
npm ERR! node v0.10.36
npm ERR! npm  v2.4.1
npm ERR! path E:\NodeProjects\nodejs\Math_user_vinit\node_modules\math_module_fi
rst\main.js
npm ERR! code ENOENT
npm ERR! errno 34

npm ERR! enoent ENOENT, chmod 'E:\NodeProjects\nodejs\Math_user_vinit\node_modul
es\math_module_first\main.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     E:\NodeProjects\nodejs\Math_user_vinit\npm-debug.log

**Comment by KenanY** [comment]
@MrVinitBansal Did you make the change I suggested and `npm publish` a new version of your module? If you don't publish the change of course the error will still be present when you attempt to install.

**Comment by MrVinitBansal** [comment]
But when I try to publish again it says you cannot modify the package already registered in npm registry. So how to publish again

**Comment by MrVinitBansal** [comment]
Its got installed but now when I am trying to use it in another module it is giving error. I installed that package in "math_user_vinit" directory after which "node_modules" directory was created in this. Then I created a file "main.js" in "math_user_vinit" and when try to run it in command prompt it shows "_filename" is not defined. 

This _filename is written in the published package "main.js" file that is :
var lib = path.join(path.dirname(fs.realpathSync(__filename)), '../lib');
var simple=require(lib+"simple_math.js");

What is this filename and which filename is this?

I have tried commands "node main" and "node main.js" from "math_user_vinit" directory. but both giving this error

Please help asap

**Comment by KenanY** [comment]
@MrVinitBansal Now this issue is becoming unrelated to `npm`, but I will try to help you regardless. I just  took a look at your module, and this is your `bin/main.js`:

``` js
var path = require('path');
var fs = require('fs');
var lib = path.join(path.dirname(fs.realpathSync(_filename)), '../lib');
var simple = require(lib + '/simple_math.js');
var advanced = require(lib + '/advanced_math.js');
module.exports = {
addition:simple.addition,
subtraction:simple.subtraction,
multiplication:advanced.multiply,
division:advanced.divide,
fibonacci:advanced.fibonacci
}
```

It looks like, on line 3, you are using `_filename` instead of `__filename`. Note that the global should have two (2) underscores, not one; hence the error you are seeing about `_filename` being `undefined` (please see [the Node.js docs on `__filename`](http://nodejs.org/api/globals.html#globals_filename)).

Furthermore, you can really simplify this file by not having to use `__filename` or the `fs` module at all. The `require()` function resolves paths for you, so `bin/main.js` should be able to look just like this and you will obtain the same results:

``` js
var simple = require('../lib/simple_math.js');
var advanced = require('../lib/advanced_math.js');
module.exports = {
addition:simple.addition,
subtraction:simple.subtraction,
multiplication:advanced.multiply,
division:advanced.divide,
fibonacci:advanced.fibonacci
}
```

Please try either of the fixes, publish a new version, and let me know if you are still unable to `require('math_module_first')`.

**Comment by MrVinitBansal** [comment]
Thanks a lot. Finally you made me complete this. I am very grateful to you. My first node cycle is completed only because of your help.Thanks a lot again. And sorry If I was any time rude to you.

ThanksVinit BansalAsst. ProgrammerNational Informatics CentreMinistry of Finance,North BlockCallSend SMSAdd to SkypeYou'll need Skype CreditFree via SkypeCallSend SMSAdd to SkypeYou'll need Skype CreditFree via SkypeCallSend SMSAdd to SkypeYou'll need Skype CreditFree via Skype

Date: Thu, 5 Feb 2015 08:45:13 -0800

**Comment by othiym23** [comment]
Closing as resolved.
