### ISSUE TITLE
Strip node_modules/.bin from scripts and warn

### ISSUE THREAD

**Issue by iarna** [npm/npm#7275]

**Comment by smikes** [comment]
For a while I believed I had to add the `./node_modules/.bin` for some bizarre use case under Windows.  If I can figure out what it was, I will post a note here, but right now it seems utterly needless.

**Comment by iarna** [comment]
So it turns out that read-package-json already silently strips it. Well, it strips it from the start of the command string. So if you have node_modules/.bin/foo && node_moudles/.bin/bar then it'll only fixup the first.
```javascript
                var spre = /^(\.[\/\\])?node_modules[\/\\].bin[\\\/]/
```

**Comment by smikes** [comment]
:+1:
