### ISSUE TITLE
The way dependencies of dependencies are dealt with is kinda broken

### ISSUE THREAD

**Issue by callumacrae** [npm/npm#7276]
I've had two issues with dependencies of dependencies in the last week.

When you have two dependencies, "foo" and "bar", and "bar" is also a dependency of "foo", "bar" won't be installed twice.

This is what I would expect:

```
❯ tree
.
└── node_modules
    ├── bar
    └── foo
        └── node_modules
            └── bar
```

This is what actually happens:

```
❯ tree
.
└── node_modules
    ├── bar
    └── foo
```

I can completely understand why this happens! It means the module is only downloaded once, instead of being downloaded multiple times, and it still works fine because of how `require` works.

---

However, it has side effects:

If I were to uninstall "bar" using npm because, say, I don't need it anymore, the "foo" module would start erroring because it can't find "bar". This one is pretty easy to work around: just figure out which dependencies rely on "bar", and copy "bar" into those dependencies (or reinstall them).

The other side effect is less common, and trickier to deal with. When there's a module designed to load other modules, it might expect to be requiring them in a different node_modules directory to the one it is actually in.

```
.
├── index.js
└── node_modules
    ├── include
    └── foo
        ├── foo.js
        └── node_modules
            └── bar
```

include/index.js:

```js
module.exports = function (name) {
    return require(name);
};
```

If we call `include()` from index.js, it works as expected. However, if we call `include()` from node_modules/foo/foo.js, we are expecting to get dependencies from node_modules/foo/node_modules: however, it will only get dependencies from node_modules.

It's a pretty obscure bug, but it has cropped up in the wild: jackfranklin/gulp-load-plugins#56

----

I have no idea what can be done about this—I completely understand why you don't want to download the same dependency multiple times when it doesn't really need to be, but it does have some weird side effects.

**Comment by jurgemaister** [comment]
A solution would be to symlink the dependencies of the dependencies into `node_modules` from the root directory, then modify the deletion script to do a recursive search into all modules to check wether any depend on the module that's about to be deleted.

Make this the default behaviour, then add a `--force` option to delete it anyway.

**Comment by iarna** [comment]
@callumacrae You could also bundle the dependency (`npm install --save --save-bundle module`)

Thanks for bringing this up!

With the multi-stage install project and npm@3 you're going to see as many dependencies installed at the top level as possible. That is, you'll only see multiple levels when there are conflicts. I'll go comment on the gulp thread…

(As for your `npm rm --save` orphaning things, we're going to have it be aware of what your dependencies require, so if one of them requires the module we'll remove it from your package.json but leave the module in place. What `npm rm` without save will do is an open question. 😁 Probably warn and do nothing, with `npm rm --force` actually breaking your tree.)

**Comment by peterjwest** [comment]
Looking forward to this feature, awesome thanks!

**Comment by iarna** [comment]
I'm closing this as its actually a complete feature in `multi-stage`.
