### ISSUE TITLE
no npm command to delete/uninstall node_modules

### ISSUE THREAD

**Issue by AaronNGray** [npm/npm#7279]
I want a standard way I can delete node_modules directory and also invoke a script with which to delete 'public/bower_components'.

'npm uninstall' just gives me the message :-

npm WARN uninstall not installed in C:\Users\Aaron\github\template-node-marionette-app\node_modules: "template-node-marionette-app"

Ideally this would work across *nix and Windows.

**Comment by KenanY** [comment]
> I want a standard way I can delete node_modules directory and also invoke a script with which to delete 'public/bower_components'.

> Ideally this would work across *nix and Windows.

``` json
{
  "scripts": {
    "clean": "rimraf node_modules/ && rimraf public/bower_components/"
  },
  "devDependencies": {
    "rimraf": "^2.2.8"
  }
}
```

Then you can run `npm run clean`.

**Comment by AaronNGray** [comment]
Cheers !

**Comment by piranna** [comment]
This is similar to the issue [I opened](https://github.com/npm/npm/issues/7162) some days before, and although @KenanY solution is a valid one, seems hacky and I think that should be de behaviour of ```npm uninstall``` to make it symetric with ```npm install``` when both executed at the root of a npm package.
