### ISSUE TITLE
ENOTEMPTY, code 53

### ISSUE THREAD

**Issue by dKab** [npm/npm#7300]
```
npm ERR! Error: ENOTEMPTY, rmdir '/var/www/ng-finance/node_modules/grunt/node_modules/glob/node_modules/inherits'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.13.0-45-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /var/www/ng-finance
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! path /var/www/ng-finance/node_modules/grunt/node_modules/glob/node_modules/inherits
npm ERR! code ENOTEMPTY
npm ERR! errno 53
npm ERR! not ok code 0
app/index.html modified.
make: Entering directory `/var/www/ng-finance/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory `/var/www/ng-finance/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/build'
npm ERR! not ok code 0
```

**Comment by KenanY** [comment]
@dKab Could you try [upgrading](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-nix-osx-linux-etc) your `npm` to the latest stable version? You have `1.4.28` but the latest is `2.5.0`.

**Comment by dKab** [comment]
Wow! Didn't realize I had so outdated version installed. I'll definately
try to update.
8 февр. 2015 г. 21:40 пользователь "Kenan Yildirim" <
notifications@github.com> написал:
>
> @dKab Could you try upgrading your npm to the latest stable version? You
have 1.4.28 but the latest is 2.5.0.

**Comment by smikes** [comment]
It looks like you are running a into a race condition of the sort that plagued older `npm` versions.

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.4.28. Can you try updating your npm installation?

To update npm, run `npm -g install npm@latest` ; or if you get the latest node (0.12.0) or iojs (1.1.0) installation, it will come with an up-to-date `npm`.

For some Linux distributions (Debian/Ubuntu and RedHat/CentOS), the latest node version provided by the distribution may lag behind the stable version. [Here are instructions from NodeSource](https://github.com/nodesource/distributions) on getting the latest node.

Thanks!

**Comment by dKab** [comment]
updated npm to 2.5.0 and now when trying to install angular with yeoman I run into following issue: 
npm ERR! Linux 3.13.0-45-generic
npm ERR! argv "node" "/usr/bin/npm" "install"
npm ERR! node v0.10.36
npm ERR! npm  v2.5.0
npm ERR! path /home/dmitriy/study/js/fm-app/node_modules/grunt/node_modules/coffee-script/lib/coffee-script/lexer.js
npm ERR! code ENOENT
npm ERR! errno 34

npm ERR! enoent ENOENT, lstat '/home/dmitriy/study/js/fm-app/node_modules/grunt/node_modules/coffee-script/lib/coffee-script/lexer.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/dmitriy/study/js/fm-app/npm-debug.log
app/index.html modified.

**Comment by othiym23** [comment]
Sounds like you may need to remove `/home/dmitriy/study/js/fm-app/node_modules` and rerun `npm install` in `/home/dmitriy/study/js/fm-app`. Does that help?

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
