### ISSUE TITLE
ninja blocks wemo belkin driver 

### ISSUE THREAD

**Issue by cla68** [npm/npm#7303]
First of all...I am new of everthing here. So, I'm afraid I'll not able to help anyone for a while...as I need to understand basis...
I have a beaglebone with ninja blocks. Node is 0.8.22 and it seems a issue to upgrade it to a more recent version. Npm is 1.1.64.
So, I've been trying to install a driver as per the object of this post. It fails and here below an extract of npm-debug.log...
I had a look around about possibility to upgrade node.js and npm to most recent versions but it seems a hard job, out of my actual skills...maybe I could get some suggestions here... thanks :-)

1296 verbose about to build /opt/ninja/drivers/node_modules/ninja-belkin-wemo/node_modules/wemo/node_modules/node-ssdp
1297 info /opt/ninja/drivers/node_modules/ninja-belkin-wemo/node_modules/wemo/node_modules/node-ssdp unbuild
1298 verbose from cache /opt/ninja/drivers/node_modules/ninja-belkin-wemo/node_modules/wemo/node_modules/node-ssdp/package.json
1299 info preuninstall node-ssdp@2.0.1
1300 info uninstall node-ssdp@2.0.1
1301 verbose false,/opt/ninja/drivers/node_modules,/opt/ninja/drivers/node_modules/ninja-belkin-wemo/node_modules/wemo/node_modules unbuild node-ssdp@2.0.1
1302 info postuninstall node-ssdp@2.0.1
1303 verbose about to build /opt/ninja/drivers/node_modules/ninja-belkin-wemo/node_modules/wemo
1304 info /opt/ninja/drivers/node_modules/ninja-belkin-wemo/node_modules/wemo unbuild
1305 verbose from cache /opt/ninja/drivers/node_modules/ninja-belkin-wemo/node_modules/wemo/package.json
1306 info preuninstall wemo@0.1.0
1307 info uninstall wemo@0.1.0
1308 verbose false,/opt/ninja/drivers/node_modules,/opt/ninja/drivers/node_modules/ninja-belkin-wemo/node_modules unbuild wemo@0.1.0
1309 info postuninstall wemo@0.1.0
1310 verbose about to build /opt/ninja/drivers/node_modules/ninja-belkin-wemo
1311 info /opt/ninja/drivers/node_modules/ninja-belkin-wemo unbuild
1312 verbose from cache /opt/ninja/drivers/node_modules/ninja-belkin-wemo/package.json
1313 info preuninstall ninja-belkin-wemo@0.0.5
1314 info uninstall ninja-belkin-wemo@0.0.5
1315 verbose true,/opt/ninja/drivers/node_modules,/opt/ninja/drivers/node_modules unbuild ninja-belkin-wemo@0.0.5
1316 info postuninstall ninja-belkin-wemo@0.0.5
1317 error Error: No compatible version found: ip@'^0.3.0'
1317 error Valid install targets:
1317 error ["0.0.1","0.0.2","0.0.3","0.0.4","0.0.5","0.1.0","0.2.0","0.3.0","0.3.1","0.3.2"]
1317 error     at installTargetsError (/opt/ninjablocks/block-admin/node_modules/ninja-toolbelt/node_modules/npm/lib/cache.js:719:10)
1317 error     at /opt/ninjablocks/block-admin/node_modules/ninja-toolbelt/node_modules/npm/lib/cache.js:641:10
1317 error     at saved (/opt/ninjablocks/block-admin/node_modules/ninja-toolbelt/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
1317 error     at Object.oncomplete (fs.js:297:15)
1318 error If you need help, you may report this log at:
1318 error     <http://github.com/isaacs/npm/issues>
1318 error or email it to:
1318 error     <npm-@googlegroups.com>
1319 error System Linux 3.2.18-psp14
1320 error command "node" "/opt/ninjablocks/block-admin/node_modules/ninja-toolbelt/node_modules/.bin/npm" "install" "--save" "--color" "always" "http://github.com/thatguydan/ninja-wemo/tarball/master"
1321 error cwd /opt/ninja/drivers
1322 error node -v v0.8.22
1323 error npm -v 1.2.32

**Comment by KenanY** [comment]
```
1317 error Error: No compatible version found: ip@'^0.3.0'
1317 error Valid install targets:
1317 error ["0.0.1","0.0.2","0.0.3","0.0.4","0.0.5","0.1.0","0.2.0","0.3.0","0.3.1","0.3.2"]
```

The issue here is that your version of `npm` is so ancient that it doesn't support the `^` semver operator you see above. The solution is to update your version of `npm` (or update to the latest stable Node.js release), whichever might be easier on beaglebone.

**Comment by cla68** [comment]
Before posting my topic I made some tests, each time I failed and I had to re-write a vergin image on micro SD. I tried to upgrade Node.js, but it failed. It seems that is useless to upgrade Node and Npm without re-compiling the Ninja Blocks app. Of course I do not know where to start or collect informatio to do that...

**Comment by smikes** [comment]
I'm sorry, but you're going to have to update at least your `npm` to work with the module you're trying to install.  Try doing the following commands in sequence, because it is sometimes necessary to go from an old version of `npm` to an intermediate version before updating to the very latest:

```
sudo npm install -g npm@1.4.28
sudo npm install -g npm@latest
```

**Comment by cla68** [comment]
Ok, I did it. With first command I got
npm http 200 https://registry.npmjs.org/npm/1.4.28
npm http GET https://registry.npmjs.org/npm/-/npm-1.4.28.tgz
npm http 200 https://registry.npmjs.org/npm/-/npm-1.4.28.tgz
/usr/bin/npm -> /usr/lib/node_modules/npm/bin/npm-cli.js
npm@1.4.28 /usr/lib/node_modules/npm
With second command I got no messages and I was moved directly to the prompt. I have tried to check the version installed with npm -v and other commands (such as simply npm) but I always get the same response:
-bash: /usr/bin/npm: No such file or directory
......and now?

**Comment by smikes** [comment]
You have run into a bug that I didn't expect you to -- that is, updating from 1.4.28 to 2.5.1 failed and caused your `npm` to be removed. 

Try reinstalling `npm` with the command:

```
curl https://www.npmjs.org/install.sh | sudo sh
```

**Comment by cla68** [comment]
I've tried but it sounds not good. Here the result
ubuntu@ninjablock:~$ sudo curl https://www.npmjs.org/install.sh | sudo sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    51  100    51    0     0     92      0 --:--:-- --:--:-- --:--:--   159
sh: 1: Moved: not found
I'm ready for any way...thanks in advance

**Comment by smikes** [comment]
Oh, sorry, it needs to be 

```
curl -L https://www.npmjs.org/install.sh | sudo sh
```

**Comment by cla68** [comment]
Well, thanks to your instructions :-), I've succeed in installing latest npm 2.5.0. The node version is 0.8.22.
The block admin is still missing. So I've been trying to install the driver using command line
sudo npm install -g https://github.com/thatguydan/ninja-wemo.git
but I get that:
npm ERR! fetch failed https://github.com/thatguydan/ninja-wemo.git
npm WARN retry will retry, error on last attempt: Error: fetch failed with statu                                                                                                                                                             s code 406
npm ERR! fetch failed https://github.com/thatguydan/ninja-wemo.git
npm WARN retry will retry, error on last attempt: Error: fetch failed with statu                                                                                                                                                             s code 406
npm ERR! fetch failed https://github.com/thatguydan/ninja-wemo.git
npm ERR! Linux 3.2.18-psp14
npm ERR! argv "node" "/usr/bin/npm" "install" "-g" "https://github.com/thatguydan/ninja-wemo.git"
npm ERR! node v0.8.22
npm ERR! npm  v2.5.0
npm ERR! fetch failed with status code 406
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>
npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/npm-debug.log

**Comment by smikes** [comment]
If you're installing from a git repository, try

```
npm install thatguydan/ninja-wemo
```

That works for me (on OSX, though)

**Comment by cla68** [comment]
mmmm....it seems not good:

npm WARN locking Error: EACCES, open '/home/ubuntu/.npm/_locks/ninja-belkin-wemo                                                                                                                                                             -80471a90dfca98cc.lock'
npm WARN locking  /home/ubuntu/.npm/_locks/ninja-belkin-wemo-80471a90dfca98cc.lo                                                                                                                                                             ck failed { [Error: EACCES, open '/home/ubuntu/.npm/_locks/ninja-belkin-wemo-804                                                                                                                                                             71a90dfca98cc.lock']
npm WARN locking   errno: 3,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/home/ubuntu/.npm/_locks/ninja-belkin-wemo-80471a90dfc                                                                                                                                                             a98cc.lock' }
npm ERR! Linux 3.2.18-psp14
npm ERR! argv "node" "/usr/bin/npm" "install" "thatguydan/ninja-wemo"
npm ERR! node v0.8.22
npm ERR! npm  v2.5.0

npm ERR! Attempt to unlock /home/ubuntu/node_modules/ninja-belkin-wemo, which ha                                                                                                                                                             sn't been locked
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/npm-debug.log

**Comment by smikes** [comment]
You need to take back permissions on your locks directory:

```
sudo chown -R $(whoami) ~/.npm/_locks
```

Possibly on your whole cache:

```
sudo chown -R $(whoami) ~/.npm
```

**Comment by cla68** [comment]
First of all I have to thank you for your great support. I appreciate your efforts and I intend to get knowledge from your posts.

I have tried with first command and I get this:
ubuntu@ninjablock:~$ sudo chown -R $(whoami) ~/.npm/_locks
[sudo] password for ubuntu:
ubuntu@ninjablock:~$ npm install thatguydan/ninja-wemo
npm WARN engine node-ssdp@2.0.1: wanted: {"node":">=0.10.0"} (current: {"node":"                                                                                                                                                             0.8.22","npm":"2.5.0"})

> dtrace-provider@0.2.8 install /home/ubuntu/node_modules/ninja-belkin-wemo/node_modules/wemo/node_modules/node-ssdp/node_modules/bunyan/node_modules/dtrace-provider
> node-gyp rebuild

make: Entering directory `/home/ubuntu/node_modules/ninja-belkin-wemo/node_modules/wemo/node_modules/node-ssdp/node_modules/bunyan/node_modules/dtrace-provider/build'
  TOUCH Release/obj.target/DTraceProviderStub.stamp
make: Leaving directory `/home/ubuntu/node_modules/ninja-belkin-wemo/node_modules/wemo/node_modules/node-ssdp/node_modules/bunyan/node_modules/dtrace-provider/build'
ninja-belkin-wemo@0.0.5 node_modules/ninja-belkin-wemo
├── underscore@1.6.0
└── wemo@0.1.0 (xml2js@0.4.5, request@2.53.0, node-ssdp@2.0.1)
Despite I got only a warning msg then the driver doesn't seem installed. So I try also the second command, to unlock the whole cache. In this case I get directly the prompt without further message. I digit again "npm install thatguydan/ninja-wemo" but I get same msg above. I switch off/on the beaglebone but the driver doesnt' appeat on the drivers' list.

**Comment by smikes** [comment]
It looks like you have now successfully installed the module, but that module does not actually supply a device driver, just an interface to the device driver.  I'm sorry, but I'm not familiar with the hardware you're using, so I don't know how to help you with that.  

Can you find a hobbyist group or a message board / issue tracker for the underlying device and ask there?

**Comment by cla68** [comment]
Of course. In such case we could consider close this issue. Thanks again :-)

**Comment by cla68** [comment]
...sorry,just one question: what's the right reverse procedure to uninstall driver?

**Comment by smikes** [comment]
sudo npm uninstall -g ninja-belkin-wemo
