### ISSUE TITLE
can not install any package include locally or globally

### ISSUE THREAD

**Issue by soengsopheak** [npm/npm#7309]
I have installed latest Node v0.12.0 and npm 2.5.1. However npm it doesn't to work, I can not install any packages, it show the same message error both when I try to install local and global.
```
npm WARN locking Error: EACCES, open '/Users/soengsopheak/.npm/_locks/coffee-script-7b01d0c2a8e2b5ed.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/soengsopheak/.npm/_locks/coffee-script-7b01d0c2a8e2b5ed.lock failed { [Error: EACCES, open '/Users/soengsopheak/.npm/_locks/coffee-script-7b01d0c2a8e2b5ed.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/soengsopheak/.npm/_locks/coffee-script-7b01d0c2a8e2b5ed.lock' }
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "coffee-script"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1

npm ERR! Attempt to unlock /usr/local/lib/node_modules/coffee-script, which hasn't been locked
```

**Comment by smikes** [comment]
This looks like it may be the same issue as #7305 , also with `npm@2.5.1` on OSX.

**Comment by soengsopheak** [comment]
Hmm it's similar error message some of the part. But I am not sure if it's the same. So you do think this is issue related to the latest released npm@2.5.1?

**Comment by smikes** [comment]
If you had a working `npm`, I'd suggest you try downgrading to the previous version, 2.5.0 --

```
npm install -g npm@2.5.0
```

but I'm not sure what to tell you.  npm, inc. is in the US Pacific time zone, so we should know more about this issue in a few hours, as they are just starting work now. /cc @othiym23

**Comment by othiym23** [comment]
There is probably a small bug here, which is that the code that maintains correct permissions inside the npm cache doesn't do so for locks. The workaround is either to run `sudo chown -R $(whoami) $HOME/.npm`, or to always run `npm install` with `sudo` for the thing you're trying to install. The locks (which are only created on the module directory you're installing _to_, as a way to ensure that only one npm process is working on that directory at a time) are ending up being owned as root, and when subsequent runs aren't run as root, npm can't get the locks and is bailing out.

**Comment by soengsopheak** [comment]
Thanks very much, @othiym23, I got it work now. I just need to change the to run sudo chown -R $(whoami) $HOME/.npm .
