### ISSUE TITLE
Can't install packages when using a proxy with NTLM auth

### ISSUE THREAD

**Issue by julianonunes** [npm/npm#7311]
Currently to install packages when you're in a network that uses proxy with NTLM authentication you must install and configure CNTLM first as a workaround. But, if I wanted to update NPM source code to "nativelly" allow NTLM authentication, where should I begin? I mean, which file contains the download code?

**Comment by smikes** [comment]
That would be a different repository, `request/request`.  See this issue over there: <https://github.com/request/request/issues/808>

**Comment by othiym23** [comment]
Closing as this is in fact something for `request` -- npm doesn't actually implement anything related to proxies itself, except for configuration.
