### ISSUE TITLE
Error: Failed parsing JSON config key prefix: "C:\Program Files\nodejs"

### ISSUE THREAD

**Issue by tekoscott** [npm/npm#7312]
I am trying to run nodejs on a Micrsoft Surface 3 i7 512Gb with Windows 8.1 Pro as an operating system

Node.exe works fine. I can create the 'Hello World' program and it works brilliantly.

The issue I have is when I try to run the following commands with npm.

npm cache clean
npm init When i attempt to run these commands on the command prompt i get the following error message:
C:\testdir>npm init
Error: Failed parsing JSON config key prefix: "C:\Program Files\nodejs"
at parseField (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:376:13)
at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:328:17
at Array.forEach (native)
at Conf.add (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:327:23)
at ConfigChain.addString (C:\Program Files\nodejs\node_modules\npm\node_modules\config-chain\index.js:244:8)
at Conf. (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:315:10)
at fs.js:336:14
at FSReqWrap.oncomplete (fs.js:99:15)

Please note that I have given the directory as listed above full permissions, and unchecked the readonly checkbox on the folders properties dialog.

Can someone tell me if this is a recognized bug or am I missing something.

I am using the latest version of node v 0.12.0

Kind Regards

Scott Brady

**Comment by smikes** [comment]
Just a wild guess here, but it looks like somewhere you have a config file which contains

```
prefix = "C:\Program Files\nodejs"
```

If you can find that, change it to:

```
prefix = "C:/Program Files/nodejs"
```

with forward-slashes to avoid confusing the JSON parser.

**Comment by tekoscott** [comment]
Issue resolved. Cleared all environment variables and re-installed.
