### ISSUE TITLE
Can't install Elixir

### ISSUE THREAD

**Issue by StarpTech** [npm/npm#7314]
Hello, I try to install Elixir (https://github.com/laravel/elixir), it's an extension for the Gulp build system.
I can install gulp without errors but elixir throws errors.

Environment:

Ubuntu 14.04
Vagrant
NodeJs (v0.10.33)
NPM (2.5.0)

Test:
* reinstall nodejs
* install nodejs-legacy
* remove and clean nodejs, npm + related directories

````
vagrant@vagrant-ubuntu-trusty-64:/vagrant/laravel$ sudo npm install
npm WARN package.json @ No repository field.

> v8flags@1.0.8 install /vagrant/laravel/node_modules/gulp/node_modules/v8flags
> node fetch.js

npm ERR! tar.unpack untar error /home/vagrant/.npm/node-sass/2.0.0-beta/package.tgz
npm WARN optional dep failed, continuing mkdirp@0.5.0
npm WARN optional dep failed, continuing clean-css@2.2.23
npm WARN optional dep failed, continuing request@2.40.0
npm ERR! Linux 3.13.0-45-generic
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.10.33
npm ERR! npm  v2.5.0
npm ERR! path ../user-home/cli.js
npm ERR! code UNKNOWN
npm ERR! errno -1

npm ERR! UNKNOWN, symlink '../user-home/cli.js'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>
npm ERR! Linux 3.13.0-45-generic
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.10.33
npm ERR! npm  v2.5.0
npm ERR! path npm-debug.log.0bedfd9003fee052341fdfb42c6051a5
npm ERR! code ETXTBSY
npm ERR! errno 62

npm ERR! ETXTBSY, rename 'npm-debug.log.0bedfd9003fee052341fdfb42c6051a5'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /vagrant/laravel/npm-debug.log
````

**Comment by KenanY** [comment]
Looks like https://github.com/npm/npm/issues/7308

**Comment by LoveAndHappiness** [comment]
Same here: 

```javascript
npm WARN package.json @ No repository field.
\
> node-sass@2.0.0-beta install D:\wamp\www\laravel\node_modules\laravel-elixir\node_modules\gulp-sass\node_modules\node-sass
> node scripts/install.js

Binary downloaded and installed at D:\wamp\www\laravel\node_modules\laravel-elixir\node_modules\gulp-sass\node_modules\node-sass\vendor\win32-ia32\binding.node

> node-sass@2.0.0-beta postinstall D:\wamp\www\laravel\node_modules\laravel-elixir\node_modules\gulp-sass\node_modules\node-sass
> node scripts/build.js

npm ERR! Error: EPERM, open 'C:\Users\Georg\AppData\Roaming\npm-cache\6d1ae576-cache-inherits-2-0-1-package-tgz.lock'
npm ERR!  { [Error: EPERM, open 'C:\Users\Georg\AppData\Roaming\npm-cache\6d1ae576-cache-inherits-2-0-1-package-tgz.lock'] npm ERR!   errno: 50,
npm ERR!   code: 'EPERM',
npm ERR!   path: 'C:\\Users\\Georg\\AppData\\Roaming\\npm-cache\\6d1ae576-cache-inherits-2-0-1-package-tgz.lock' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd D:\wamp\www\laravel
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! path C:\Users\Georg\AppData\Roaming\npm-cache\6d1ae576-cache-inherits-2-0-1-package-tgz.lock
npm ERR! code EPERM
npm ERR! errno 50
npm ERR! stack Error: EPERM, open 'C:\Users\Georg\AppData\Roaming\npm-cache\6d1ae576-cache-inherits-2-0-1-package-tgz.lock'

npm ERR! not ok code 0
```

**Comment by KenanY** [comment]
@LoveAndHappiness Your issue looks like a permissions issue to me, and thus unrelated to the issue you've commented on. Your cache is not owned by your current user for some reason, so `npm` can't open files in it.

**Comment by LoveAndHappiness** [comment]
@KenanY, yes it looks like a permissions issue to me as well, but I already have every permission granted and installing gulp works perfectly when installing packages with other package.json files. Therefore I can't understand why it doesn't work in this specific case.

**Comment by StarpTech** [comment]
It exists some workarounds like:

**Dirty solution**
:sparkles: Install nodejs on your host system and install the deps via npm and all works fine.

**Tests**
:boom:  http://www.ahtik.com/blog/fixing-your-virtualbox-shared-folder-symlink-error/ or
:boom: https://docs.vagrantup.com/v2/synced-folders/rsync.html

I can run gulp but only from the host system. This is very angry but I hope that a solution is reached soon.

**Comment by drmyersii** [comment]
@LoveAndHappiness @StarpTech In case you were still having issues with this, take a look at [this comment](https://github.com/npm/npm/issues/7228#issuecomment-82829637) I made on another thread. It actually has to do with Windows long paths in Vagrant, and it could possibly be the cause of your problems.

**Comment by ezekg** [comment]
Hey guys, hit this issue yesterday and found out that you can get around it by creating a symlink of your `./node_modules` directory to an area outside of your shared folders, i.e. `mkdir ~/tmp_node_modules && ln -s ~/tmp_node_modules ./node_modules`, and then running `npm install`.

I created a small command line tool called [`sympm`](https://github.com/ezekg/sympm) that automates those steps and acts as a replacement for `npm install` when inside of a virtual machine. You don't need to install with flags like `--no-bin-links`, so everything should behave correctly.

Maybe it'll be helpful to somebody here.

**Comment by kmanion** [comment]
Hi @StarpTech , it looks like you've gotten some help with this issue. We're trying to close out some of the older support issues. Please don't hesitate to reopen if you are still running into this or email us at support@npmjs.com

Kiera, npm technical support
