### ISSUE TITLE
Error installing libraries

### ISSUE THREAD

**Issue by albizeka** [npm/npm#7315]
Hi I'm trying to install some libraries(globaly) but this error always appears to me.

![npmerror](https://cloud.githubusercontent.com/assets/7847481/6108663/435b44de-b075-11e4-9176-89ec25375fa1.PNG)

**Comment by KenanY** [comment]
Looks like an issue with your internet connection. Are you behind a proxy (the error message asks this)?

**Comment by albizeka** [comment]
Hm yes i think so im trying to solve this problem for 2 days i try a lot of ways to resolve this but no success.

**Comment by KenanY** [comment]
If you are behind a proxy then you need to configure `npm` to use that proxy (as the error message states). Have you tried doing this? Here are the relevant configs:

  - [`proxy`](https://docs.npmjs.com/misc/config#proxy)
  - [`https-proxy`](https://docs.npmjs.com/misc/config#https-proxy)
  - [`cafile`](https://docs.npmjs.com/misc/config#cafile)

**Comment by albizeka** [comment]
This issue helped me and npm now works like a charm :)

https://github.com/npm/npm/issues/2119#issuecomment-5321857

**Comment by othiym23** [comment]
Closing as resolved.
