### ISSUE TITLE
Trouble installing bower with command "npm install -g bower" 

### ISSUE THREAD

**Issue by MarthaK** [npm/npm#7316]
I tried running the command "npm install -g bower" on my Windows command line and got this error:
```
26103 error Error: ENOENT, chmod 'C:\Users\marthaAK\AppData\Roaming\npm\node_modules\bower\bin\bower'
26104 error If you need help, you may report this *entire* log,
26104 error including the npm and node versions, at:
26104 error     <http://github.com/npm/npm/issues>
26105 error System Windows_NT 6.2.9200
26106 error command "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "bower"
26107 error cwd C:\Users\marthaAK\Documents\Ashesi Academics\Spring Semester 2015\Ecommerce\kumquat_book_service
26108 error node -v v0.10.31
26109 error npm -v 1.4.23
26110 error path C:\Users\marthaAK\AppData\Roaming\npm\node_modules\bower\bin\bower
26111 error code ENOENT
26112 error errno 34
26113 verbose exit [ 34, true ]
```
I followed the path <C:\Users\marthaAK\AppData\Roaming\npm\node_modules\bower\bin\bower> and did not find the bower folder in node_modules. Instead I found it outside of the npm folder but it was empty.

**Comment by smikes** [comment]
There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.4.23. Can you try updating your npm installation?

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

Thanks!

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
