### ISSUE TITLE
npm prune --production removes shared dependencies

### ISSUE THREAD

**Issue by mike-marcacci** [npm/npm#7320]
Hey there. It looks like the really useful `npm prune --production` is a bit overzealous in its cleanup. Here's a real example: I have a project that depends on [jennings](https://www.npmjs.com/package/jennings) and uses [Q](https://www.npmjs.com/package/q) for testing. Because both the main package and jennings use compatible versions of Q, running `npm install` only installs Q at the top level.

Running `npm prune --production` sees that Q isn't required in production for the main package, and removes it, breaking the app until I run `npm install --production` (which places the correct version of Q in `node_modules/jennings/node_modules/q`). Prune should traverse dependencies and leave shared dependencies in place, or shuffle them down into their requiring packages' node_modules folders.

```json
{
  "dependencies": {
    "jennings": "~1.2.2"
  },
  "devDependencies": {
    "q": "^1.1.2"
  }
}
``

**Comment by smikes** [comment]
I believe that work is in progress to address this (and many related problems) in the next major revision of `npm`.

/cc @iarna

**Comment by othiym23** [comment]
Regardless of whether `npm@3` will fix this, for now it's a bug. Thanks for the report!

**Comment by wraithan** [comment]
As a workaround, until this is fixed, if you want/need to be able to use `prune --production` you can put the shared module in your `dependencies`. Sucks a little having things that are directly depended upon as part of your deps, but makes this command useful again.

**Comment by ehsalazar** [comment]
With `npm@3`, prebuilder makes sure this isn't an issue. If you [update](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) and continue to experience an issue, please let us know. We'll be happy to look into it.

**Comment by mike-marcacci** [comment]
Great! Thanks for the update - I'll give it a go shortly.
