### ISSUE TITLE
Confusing behavior with nested .gitignore files

### ISSUE THREAD

**Issue by shz** [npm/npm#7322]
Consider a package that looks like this:

```
example-package/
  .npmignore
  foo/
    something.a
    .gitignore
```

If the `.npmignore` file is empty, and the `.gitignore` files is:

```
*.a
```

the result of `npm pack` does _not_ include `something.a`.

I realize this is a bit of a niche case, the context where it happened is the following: using a git subtree, where the subtree has `*.a` in its `.gitignore`, but also has an exception `.a` file that is explicitly checked in to git.  The parent repo (an npm module) has no way to override that nested `.gitignore` file without modifying the repo used for that subtree.

This may even be intended (if perhaps poorly documented) behavior, but it did send me down a bit of a rabbit hole and doesn't seem to have a clean workaround.  Thought I'd flag it down.

**Comment by smikes** [comment]
I believe this is `npm` behaving as intended, although I agree it is unexpected.  Whenever `npm pack` encounters a new directory it checks for an `.npmignore` file; if there isn't one, it copies the `.gitignore` file as `.npmignore` and uses that.

The suggested workaround is to put an empty `.npmignore` in your subdirectory (`foo` in your example).

I'm sorry, but I don't know the reason why this was implemented.  It's probably documented across several issues here on the tracker.

**Comment by smikes** [comment]
I found the related cases, if you're interested: you can start with https://github.com/npm/npm/issues/7252 and follow the links back.

**Comment by shz** [comment]
Ah that's great, thanks for running those down, that does help explain what's going on.

I'd like to submit a PR that attempts to document this behavior better, is there a specific spot I should target to explain this?  I'm actually having trouble finding a definitive place where the docs on `.npmignore` live, so I'm a little unclear on where this sort of information should go.  It's most relevant to the pack command, but `npm-pack.md` seems the wrong context for an explanation.  The best reference on `.npmignore` I could find is https://docs.npmjs.com/misc/developers, but that's outside the codebase.

I'm totally willing to take on the larger task of documenting `.npmignore` itself in the right place(s) in the CLI docs, if that's something that would be useful.

**Comment by smikes** [comment]
I would suggest <https://github.com/npm/npm/tree/master/doc/files>, create a new file `npmignore.md` , /cc @linclark does that sound reasonable?

**Comment by othiym23** [comment]
No, because nobody will  think to look there. Help that is not tied to specific files or commands (`npm help 7 config`, `npm help developers`, `npm help faq`) is generally invisible to a large percentage of npm's users, although we're working on reworking docs.npmjs.com to do a better job of visually prioritizing those docs. A case in point is that [`.npmignore` is already documented](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package) in `doc/misc/npm-developers.md`, although it's not clear about `.npmignore` files being respected in subdirectories as well as the root directory.

I suggest adding a clarifying node in `doc/misc/npm-developers.md` (or, rather, clarifying what's already there), `doc/cli/npm-publish.md`, `doc/cli/npm-pack.md`, or all three (at least in cross-reference form).

**Comment by kostrse** [comment]
:+1: 

I'm very frustrated by this behavior too, could you please point me on some docs/pas discussions or just maybe quickly explain the reasoning behind this? Why `npm pack` ever tries to consider `.gitignore` files?

**This is a counter-behaviour in many cases, for example.**
* I have a TypeScript source file `foo.ts` which produces resulting JavaScript file `foo.js`.
* I normally do not want to have any build artifacts in my repo, therefore I include `*.js` into the `.gitignore`.
* I normally do not want to have sources in my package, therefore I include `*.ts` into the `.npmignore`.
* Sometimes, I do want to include source files into the package (e.g. for source maps), so I have to create an empty `.npmignore` which is very strange to have these empty files.

Also, folks sometimes accidently include `.gitignore` files into nested directories, and this breaks packages too.

I haven't had in my practice any cases when it could be really helpful to reuse ignore rules from `.gitignore`.
