### ISSUE TITLE
npm error on some packages on the new rasberry pi 2

### ISSUE THREAD

**Issue by gorhgorh** [npm/npm#7323]
fresh rasbian install, node/npm installed from the lastest available arm packages
if i install some packages (currently identified ecstatic and mosca) i got some weird stack traces, with no apparent error and the packages fail to install 

sample stack here https://gist.github.com/gorhgorh/76dab926079c117ac022

tested a fresh install on a regular B+ no problem with the same packages

I'm available if tests are needed for more infos

**Comment by KenanY** [comment]
Hmm, could this be https://github.com/npm/npm/issues/7291?

**Comment by gorhgorh** [comment]
@KenanY seems so, closing
