### ISSUE TITLE
ELIFECYCLE in npm run webpack Win7

### ISSUE THREAD

**Issue by guilherme90** [npm/npm#7327]
Hello. I'm having a very strange problem and can not solve. See the attached image.
Someone can answer me why and how this happens? I'm using Windows 7 64bit.

![print-screen](https://cloud.githubusercontent.com/assets/2879939/6127542/50fd0bf6-b113-11e4-948b-e057adab1fd2.png)

**Comment by smikes** [comment]
The webpack module includes a post install script that does not work on Windows.   Can you open an issue on the webpack module?

**Comment by guilherme90** [comment]
Hello, I managed to solve as follows: In git terminal, did the command: node node_modules/webpack/bin/webpack.js

**Comment by smikes** [comment]
Yes, but since they specify the script as `./node_modules...` that causes it to fail on Windows.  It would be kind to the webpack authors if you let them know. ;-)

**Comment by othiym23** [comment]
Closing because this is not, in fact, an npm issue.
