### ISSUE TITLE
Peer dependent package installing to himself

### ISSUE THREAD

**Issue by zxqfox** [npm/npm#7334]
I have a situation when package A needs package B for dev usage, but package B is a plugin to A and have peer dep by A.

So A devDep B and B peerDep A.

In that case when I installing B in A it installs A to node_modules. It's like WTF for me but actually it is probably fine.

The problem is: I don't need this installation. So what should I do? How to solve that?

As simple solution I can suggest to make a symlink but: It won't work on windows (afaik).

Any ideas?

**Comment by zxqfox** [comment]
Since it's in deprecation process (#6565). Can I ask what to use for plugins? How to note that packages extends another package and doesn't work without it?

**Comment by smikes** [comment]
You can try using `npm dedupe` to remove duplicate installations of `A` after installing.

I don't believe there is a single recommended plugin architecture.  `grunt` uses peerDependencies, while `broccoli` encourages plugin authors to depend on a subsidiary modules (`broccoli-filter`) and requires the end-user to make the connections between the plugins they desire.

**Comment by zxqfox** [comment]
`dedupe` is a nice try to replace `peerDeps` for plugins. But how to use it? Just run on `postinstall`?

**Comment by smikes** [comment]
Your end-user would have to run it, or you can rely on the fact that `npm` won't install two versions of the same module if it can avoid it -- though this will only be true of `npm@3`.

**Comment by othiym23** [comment]
`peerDependencies` are not being removed, but their behavior is changing. See [this comment](https://github.com/npm/npm/issues/6565#issuecomment-74971689) for details. In fact, the new behavior will handle this case explicitly, because npm will no longer automatically install `peerDependencies` in `npm@3`.

**Comment by zxqfox** [comment]
@othiym23 :+1: That's great. Thanks!

**Comment by iarna** [comment]
Closing this as answered.
