### ISSUE TITLE
ENOENT erorr during titanium update

### ISSUE THREAD

**Issue by Sachinc949** [npm/npm#7339]
```
npm ERR! Error: ENOENT, chmod 'C:\Users\username\AppData\Roaming\npm\node_modules\titanium\node_modules\node-appc\node_modules\uglify-js\lib\output.js'
```

Please help me to find out a solution. m using windows 7 64 bit

**Comment by KenanY** [comment]
Not enough information to go on here. Was a `npm-debug.log` file generated? Could you upload it as a [gist](https://gist.github.com/)?

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
