### ISSUE TITLE
conditional dependencies

### ISSUE THREAD

**Issue by ForbesLindesay** [npm/npm#7340]
Could we have a way to mark a dependency as not being required for some versions of node.  e.g. [spawn-sync](https://www.npmjs.com/package/spawn-sync) requires try-thread-sleep on node 0.10 and lower, but does not need that module for 0.11 and above.  try-thread-sleep has an optional dependency on thread-sleep, which is a native C++ module.  It is frustrating that lots of time will be wasted on installing that native module for platforms that don't really need it.

**Comment by smikes** [comment]
This is a cool idea, but isn't it also the primary use case for a post-install script?

Something like this is crude but would work on non-Windows:
```
"scripts": {
   "postinstall": "node -e 'process.exit(/0.10/.test(process.version))' || npm install thread-sleep"
}
```

**Comment by ForbesLindesay** [comment]
I added https://github.com/ForbesLindesay/spawn-sync/blob/master/package.json and https://github.com/ForbesLindesay/spawn-sync/blob/master/postinstall.js which is still pretty crude, but does work cross platform, and narrowly beats everyone on node@0.12 installing an unused native dependency.

**Comment by othiym23** [comment]
I think this is what lifecycle scripts have always been for. On an intellectual level, it would be fun and exciting to make the dependency logic in `package.json` Turing-complete, but it would also be a nightmare to maintain and support. As packager, you're always going to have a better idea of what needs to be done to make your package work best on various versions of Node or different operating systems. I think your postinstall script is the right approach here.

**Comment by ForbesLindesay** [comment]
But people keep opening bugs saying it doesn't work.  Which is because it does things like relying on `npm` and `node` pointing at the correct binaries on the user's system in a way that `npm install` currently wouldn't.

I'm definitely not asking for turing complete here.  I'm asking for a very minimal version switching option.

**Comment by othiym23** [comment]
This is enough of an edge case that it makes sense to handle optionally installing it in a postinstall script rather than complicating the installer to handle what is in practice a very rarely encountered situation. I agree that this requires extra work for package maintainers, and that's unfortunate, but I still feel that you're in a much better position to figure out what needs to happen in this situation and to write a simple, direct implementation rather than I would be trying to come up with a general solution to build into npm.

**Comment by ForbesLindesay** [comment]
Could you give me some help figuring out why this still isn't working for some people?  People on some platforms get ENOENT errors for the `postinstall` script when they npm install.  I have no idea what I can do about that?

**Comment by othiym23** [comment]
Have you tried setting an `engines` field on `try-thread-sleep` along with marking it an optional dependency? Also, do you see the `ENOENT` issue with `npm@3`? That sounds like an npm bug to me, and one that probably doesn't exist with the rewritten installer.

**Comment by kevinoid** [comment]
I realize this issue is closed but, after borking my setup by running `npm prune`, I'd really like to see a better option for Node-version-dependent package dependencies.
