### ISSUE TITLE
npm update/install failed ( Error: ENOSPC)

### ISSUE THREAD

**Issue by accessdev** [npm/npm#7342]
Hello,

I have touble with npm on a centos 6 machine.

the issue is not present on my workstation (windows)

here s my package.json 

{
  "name": "rayman-creatures",
  "description": "Rayman",
  "version": "0.0.1",
  "main": "app.js",
  "dependencies": {
    "async": "^0.9.0",
    "bitwise-xor": "0.0.0",
    "body-parser": "^1.6.5",
    "cache-manager": "^0.15.0",
    "colors": "^1.0.3",
    "compression": "^1.2.0",
    "errorhandler": "^1.1.1",
    "express": "^4.8.5",
    "merge": "^1.2.0",
    "mocha": "^1.21.5",
    "moment": "^2.8.4",
    "node-rsa": "^0.1.54",
    "node-uuid": "^1.4.1",
    "redis": "^0.12.1",
    "request": "^2.40.0",
    "supertest": "^0.13.0"
  },
  "scripts": {
    "test": "mocha --reporter spec --check-leaks --globals testApp"
  }
}

errors : 
npm http 200 https://registry.npmjs.org/growl/-/growl-1.8.1.tgz
npm ERR! Error: ENOSPC, open '/var/www/project/tmp/node_modules/express/node_modules/proxy-addr/node_modules/forwarded/LICENSE'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-504.3.3.el6.x86_64
npm ERR! command "node" "/usr/bin/npm" "install"
npm ERR! cwd /var/www/project/tmp
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.3.6
npm ERR! path /var/www/project/tmp/node_modules/express/node_modules/proxy-addr/node_modules/forwarded/LICENSE
npm ERR! code ENOSPC
npm ERR! errno 54
npm ERR! Error: ENOSPC, open '/var/www/project/tmp/node_modules/supertest/node_modules/methods/package.json'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-504.3.3.el6.x86_64
npm ERR! command "node" "/usr/bin/npm" "install"
npm ERR! cwd /var/www/project/tmp
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.3.6
npm ERR! path /var/www/project/tmp/node_modules/supertest/node_modules/methods/package.json
npm ERR! code ENOSPC
npm ERR! errno 54
npm ERR! Error: ENOSPC, open '/var/www/project/tmp/node_modules/supertest/node_modules/superagent/package.json'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-504.3.3.el6.x86_64
npm ERR! command "node" "/usr/bin/npm" "install"
npm ERR! cwd /var/www/project/tmp
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.3.6
npm ERR! System Linux 2.6.32-504.3.3.el6.x86_64
npm ERR! command "node" "/usr/bin/npm" "install"
npm ERR! cwd /var/www/project/tmp
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.3.6
npm ERR! path /var/www/project/tmp/node_modules/mocha/node_modules
npm ERR! fstream_path /var/www/project/tmp/node_modules/mocha/node_modules/glob
npm ERR! fstream_type Directory
npm ERR! fstream_class DirWriter
npm ERR! code ENOSPC
npm ERR! errno 54
npm ERR! fstream_stack /usr/lib/node_modules/fstream/lib/writer.js:171:23
npm ERR! fstream_stack /usr/lib/node_modules/mkdirp/index.js:37:53
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOSPC, mkdir '/var/www/project/tmp/node_modules/node-rsa/node_modules'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-504.3.3.el6.x86_64
npm ERR! command "node" "/usr/bin/npm" "install"
npm ERR! cwd /var/www/project/tmp
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.3.6
npm ERR! path /var/www/project/tmp/node_modules/node-rsa/node_modules
npm ERR! fstream_path /var/www/project/tmp/node_modules/node-rsa/node_modules/asn1
npm ERR! fstream_type Directory
npm ERR! fstream_class DirWriter
npm ERR! code ENOSPC
npm ERR! errno 54
npm ERR! fstream_stack /usr/lib/node_modules/fstream/lib/writer.js:171:23
npm ERR! fstream_stack /usr/lib/node_modules/mkdirp/index.js:37:53
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOSPC, mkdir '/var/www/project/tmp/node_modules/node-rsa/node_modules'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-504.3.3.el6.x86_64
npm ERR! command "node" "/usr/bin/npm" "install"
npm ERR! cwd /var/www/project/tmp
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.3.6
npm ERR! path /var/www/project/tmp/node_modules/node-rsa/node_modules
npm ERR! fstream_path /var/www/project/tmp/node_modules/node-rsa/node_modules/lodash
npm ERR! fstream_type Directory
npm ERR! fstream_class DirWriter
npm ERR! code ENOSPC
npm ERR! errno 54
npm ERR! fstream_stack /usr/lib/node_modules/fstream/lib/writer.js:171:23
npm ERR! fstream_stack /usr/lib/node_modules/mkdirp/index.js:37:53
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)

**Comment by herlon214** [comment]
What you did to fix?

**Comment by manishmore** [comment]
does this fix ? if yes then what you did.
