### ISSUE TITLE
Error ENOENT packer.js

### ISSUE THREAD

**Issue by peterkucera** [npm/npm#7346]
Error: ENOENT, chown '/usr/local/lib/node_modules/harp/node_modules/download-github-repo/node_modules/tar/examples/packer.js'

BTW I cannot upload log file because github err OMG
Unfortunately, we don't support that file type.  Try again with a PNG, GIF, or JPG.

Q please what is wrong?

**Comment by KenanY** [comment]
You can upload the log as a [gist](https://gist.github.com/) :)

**Comment by othiym23** [comment]
Also it would be helpful to know what versions of npm and node you're running, and even if you can't upload the whole log, at least enough for us to get some sense of the context of your error would be very helpful.

**Comment by KenanY** [comment]
@peterkucera ping? :)

**Comment by peterkucera** [comment]
Please close it I have not time now




--
Peter Kučera
+421 907 426 949
peterkucera.me@gmail.com

Eagle Kings s. r. o.
Priame zásobovanie domácností
https://www.amway.sk/user/peterkucera
eaglekings.com

**Comment by othiym23** [comment]
Closing as abandoned.
