### ISSUE TITLE
Invalid name because of capital letters

### ISSUE THREAD

**Issue by cristianfraser** [npm/npm#7351]
I'm developing a NW.js app and its name in `package.json` has capital letters. And I get the `npm ERR! Invalid name` error. Was this fixed in earlier versions or is it the way it is intended to be? I'm not making a node module, I don't see any reasons for npm forcing me to change my app's name.

node 0.10.33
npm 2.4.1

**Comment by smikes** [comment]
This is intended behavior; `npm` modules are no longer allowed to have capital letters in their names (see <https://github.com/npm/validate-npm-package-name/blob/master/index.js#L67>)

nw.js has similar rules: <https://github.com/nwjs/nw.js/wiki/Manifest-format#name>

> name  (string) the name of the package. This must be a unique, lowercase alpha-numeric name without spaces. It may include "." or "_" or "-" characters. It is otherwise opaque.

**Comment by othiym23** [comment]
Closing as resolved.
