### ISSUE TITLE
npm run-script flag to exit with 0 when script doesn't exist

### ISSUE THREAD

**Issue by jussi-kalliokoski** [npm/npm#7354]
We have a CI setup with a generic template that triggers Travis-like hooks like `after_failure` using `npm run-script`. Previously this worked even when you had not specified the scripts (which was nice since you might not actually want to do anything on failure). 

Ever since #2959 was fixed with the introduction of 0aefae9bc2598a4b7a3ee7bb2306b42e3e12bb28 the builds that don't have these scripts specified started failing. It would be nice if there was some flag that made run-script return 0 when the script isn't available, e.g. `npm run --if-present after_success`.

**Comment by othiym23** [comment]
`"after_success": "non-existent-script || true"` will work on Unix, but unfortunately there isn't a really good way to do this compatibly right now. This isn't a bug per se, given the requirements outlined in #2959, and I'd like to avoid adding too much configuration around run-script behavior, but if somebody wanted to put together a patch along the lines of what @jussi-kalliokoski describes, I can work with them to get it landed.

**Comment by othiym23** [comment]
Fixed by f33e8b8ff2de094071c5976be95e35110cf2ab1a. :tada:

**Comment by jussi-kalliokoski** [comment]
:tada: :+1: :star2:

**Comment by ralfstx** [comment]
This feature is not yet documented in https://docs.npmjs.com/cli/run-script. Is this an oversight?

**Comment by madarche** [comment]
@ralfstx : this is documented in https://docs.npmjs.com/misc/config

**Comment by ralfstx** [comment]
Thanks @madarche. Well hidden I would say.

**Comment by aleclarson** [comment]
I opened a pull request that adds `--if-present` to the `run-script` docs.

#20279
