### ISSUE TITLE
The npm "deduplication" makes the build of some dependencies fail.

### ISSUE THREAD

**Issue by rbelouin** [npm/npm#7356]
Hello all,

I have some issues when installing some dependencies for my node project. Consider the following simplified dependency tree:
```
clever-tools@0.2.0-beta2 /Users/rbelouin/work/clever-cloud/clever-tools
└─┬ clever-client@0.2.0-beta.3
  ├── bower@1.3.12
  └─┬ wadl-client@0.2.0-beta.5
    └─── bower@1.3.12

```

Actually, the `bower` dependency is not installed for `clever-client`, I guess it's for some disk usage reasons. Both `clever-client` and `wadl-client` need `./node_modules/.bin/bower` when being installed, but this relative path does not exist for `clever-client` and the installation fails because of that "deduplication" policy.

Is there a good reason for not creating a symbolic link from `./node_modules/clever-client/node_modules/.bin/bower` to `./node_modules/clever-client/node_modules/wadl-client/node_modules/.bin/bower`?

Same question for the `./node_modules/clever-client/node_modules/bower` folder to be linked to `./node_modules/clever-client/node_modules/wadl-client/node_modules/bower`?

For your interest, this bug does not appear when running an `npm install` from the `clever-client` project.

Thank you for your help.

```
npm version: 2.5.1
node version: v0.10.33
OS version: Mac OS X 10.9.5
```

**Comment by smikes** [comment]
Yes, this can be a problem.  That's why it's generally recommended to just use the unprefixed executable name (e.g., `bower`) instead of explicitly specifying the path.  

`npm` makes sure that the relevant `.bin` directory is put in the path when running scripts, `npm test`, etc.

See this blog post for more details: http://blog.ibangspacebar.com/npm-scripts/

**Comment by rbelouin** [comment]
Thanks! This will help me a lot!

Is there still a good reason for not creating symlinks? To prevent people from traversing the dependency tree themself, or something like that?

**Comment by smikes** [comment]
Some file systems don't support them, and they create a risk of infinite file system loops.

**Comment by rbelouin** [comment]
Oh I see, thank you for having replied.

**Comment by rbelouin** [comment]
Hi,

I've updated `wadl-client` and `clever-client` so they call `bower install` instead of `./node_modules/.bin/bower` when being built by npm.

When I run `npm install` in the `clever-tools` project, `bower` is not defined because `./node_modules/clever-client/node_modules/wadl-client/node_modules/.bin` is not added to the PATH defined when running the `install` script.

If some duplicated dependencies are downloaded just once, shouldn't the binary folder of each dependency be included in the PATH? I don't understand how I can handle the build of `clever-client`
 if `bower` isn't in `./node_modules/.bin` nor defined in PATH.

**Comment by smikes** [comment]
I think the suggested solution is to ensure that `bower` is in the dependencies of whichever project needs to call `bower install`.  I'm not sure if that's `clever-tools` or `clever-client` in your example.

**Comment by rbelouin** [comment]
OK, I will try to clarify my problem in a few points:

* The project A needs B
* The project B needs C
* Both B and C need `bower`, and `bower` is defined as a dependency in `B/package.json` and `C/package.json`
* When running `npm install` in A, B is downloaded in `A/node_modules/B` and C is downloaded in `A/node_modules/B/node_modules/C`
* `bower` is installed in `A/node_modules/B/node_modules/C/node_modules/.bin`
* The build of C is triggered, it runs `bower install` and it works like a charm because `bower` is defined in the PATH by npm
* Then the build of B is triggered, it runs `bower install` and it fails because npm installed `bower` only in `A/node_modules/B/node_modules/C/node_modules/.bin` and not in `A/node_modules/B/node_modules/.bin` and `A/node_modules/B/node_modules/C/node_modules/.bin` is no more defined in the PATH.
* Although B has `bower` defined as a dependency, it does not have access to it.

Have I done something wrong? How should I handle "shared" dependencies with npm?

**Comment by smikes** [comment]
I'm sorry that this is still a problem. I don't think you're doing anything wrong. I do think that you're at the edge — or maybe beyond the edge — of what npm can handle, though. 


These issues may be fixed by npm@3, so I will ask @iarna and @othiym23 if they have any comments.

**Comment by rbelouin** [comment]
Oh. So I should commit compiled files instead of running bower at installation time? I look forward of seeing the release of npm 3!

**Comment by smikes** [comment]
I hope you can make it work without committing actually compiled binary files but dependency management is a hard - some would even say wicked - problem and sometimes checking in or distributing build artifacts is the right way to go :-/
