### ISSUE TITLE
ambiguity about installing devDependencies

### ISSUE THREAD

**Issue by rkamradt** [npm/npm#7360]
The documentation implies that npm install will install both dependencies AND devDependencies, however in my project it now only installs the dependencies. Running 'npm install --dev' installs the devDependencies. I just today installed npm on my MacBook Pro, and npm is at version 2.5.1. Everything else seems to work fine.

I don't recall ever having to run 'npm install --dev', but I can't be sure as my old windows laptop has become a smoldering piece of coal.

My question is should 'npm install' install both dependencies AND devDependencies, or do I need to run both 'npm install' and 'npm install --dev'? If it's a doc issue, I may be able to help fix it, but I want to be sure about the actual intent.

**Comment by KenanY** [comment]
@rkamradt It should install both if you are in the directory of the package. Is there a `package.json` we can use to repro?

**Comment by rkamradt** [comment]
The problem is exhibited in my https://github.com/rkamradt/frontendbuildup repro, and in another one that's not yet pushed to github. Again, this is a fresh install, I pulled the binary from the node.js site as decribed here: https://rlkamradt.wordpress.com/2015/02/14/setting-up-a-development-environment-on-a-mac-languages/

**Comment by KenanY** [comment]
@rkamradt With `npm@2.5.1`, I cannot reproduce the issue. I cloned your repo, ran `npm install`, and got all of the dependencies:

``` bash
$ npm ls --depth 0
frontendbuildup@0.0.0 /home/kenan/frontendbuildup
├── backbone@1.1.2
├── body-parser@1.12.0
├── bootstrap@3.3.2
├── browserify@4.2.3
├── cookie-session@1.1.0
├── express@4.11.2
├── grunt@0.4.5
├── grunt-browserify@2.1.4
├── grunt-contrib-clean@0.5.0
├── grunt-contrib-copy@0.5.0
├── grunt-contrib-jshint@0.10.0
├── grunt-contrib-uglify@0.5.1
├── grunt-contrib-watch@0.6.1
├── grunt-express-server@0.4.19
├── grunt-react@0.10.0
├── grunt-simple-mocha@0.4.0
├── jquery@2.1.3
├── jshint@2.6.0
├── load-grunt-tasks@0.5.0
├── method-override@2.3.1
├── mocha@1.21.5
├── morgan@1.5.1
├── react@0.12.2
├── sha1@1.1.0
├── should@4.6.5
├── supertest@0.13.0
├── underscore@1.7.0
└── zombie@2.5.1
```

I'm not sure why we're each getting a different behavior. I was thinking maybe you have the `production` config set to `true` in your global `.npmrc` but that feels like a big stretch to me.

``` bash
$ npm config get production
false
```

**Comment by rkamradt** [comment]
You're right, the production value was set to true. I set it to false, and it works now. I have no idea how it got set to true, this is a fresh installation.

**Comment by rkamradt** [comment]
This appears to be an issue in the Atom plugin terminal-status, it works fine from the terminal. I'll close this and see if there's an issue on the terminal-status page.
