### ISSUE TITLE
`npm outdated` hangs on Mac

### ISSUE THREAD

**Issue by demisx** [npm/npm#7362]
Not sure, if this is a coincidence or not, but after upgrading to node 0.12, the `npm outdated` command hangs. The last two lines in debug mode are:

```
https://registry.npmjs.org/ordered-esprima-props from cache
npm verb get saving ordered-esprima-props to /Users/dmoore/.npm/registry.npmjs.org/ordered-esprima-props/.cache.json
```

**Comment by smikes** [comment]
Can you try running:

```
npm -ddd outdated --depth 0
```

And upload the `npm-debug.log` as a gist <https://gist.github.com>?

**Comment by robertkowalski** [comment]
Hey... I have the same problem... here is what i observerved.

It hangs on 0.12:

```
(01:35:36) [robert@tequila-osx] ~/projects/npm-registry-mock (master) $ npm outdated
npm http request GET https://registry.npmjs.org/hock
npm http request GET https://registry.npmjs.org/util-extend
npm http request GET https://registry.npmjs.org/mocha
npm http request GET https://registry.npmjs.org/npm-registry-client
npm http request GET https://registry.npmjs.org/request
npm http request GET https://registry.npmjs.org/rimraf
npm http request GET https://registry.npmjs.org/mkdirp
npm http request GET https://registry.npmjs.org/npm
^C
(01:36:47) [robert@tequila-osx] ~/projects/npm-registry-mock (master) $ node -v
v0.12.0
(01:37:26) [robert@tequila-osx] ~/projects/npm-registry-mock (master) $ npm -v
2.8.0
(01:37:37) [robert@tequila-osx] ~/projects/npm-registry-mock (master) $
```

running with ---depth=0 makes it super fast

on 0.12.2 it does not hang, but also takes ages (without `---detph=0`)

**Comment by robertkowalski** [comment]
don't have anything set regarding depth in my npmrc

**Comment by robertkowalski** [comment]
interesting, the connections time out as soon as we have a few packages (in this case it is npm itself):

https://gist.github.com/robertkowalski/50302e2e88ab14f8eac7

as you see i let it run 3 minutes...

**Comment by robertkowalski** [comment]
maybe we are trying to open to many connections, if i remember right node 0.12 set the limit from 5 to unlimited

**Comment by smikes** [comment]
Can you try running `NODE_DEBUG=http,net npm -ddd outdated 2>&1 | tee outfile ` and upload the (very large) outfile as a gist (https://gist.github.com).  This may be related to a problem with http keepalive in node >0.11 (including all iojs, node 0.12) that we are trying to nail down...

**Comment by robertkowalski** [comment]
ha, funny

can't reproduce the issue now. so i guess a server issue? @bcoe @mmalecki ?

**Comment by demisx** [comment]
Same here. Appears to be working fine now (node 0.12.2)
