### ISSUE TITLE
Invalid version: "0.1"

### ISSUE THREAD

**Issue by serjyamp** [npm/npm#7369]
please help me, gulp-minify-css hasn't been installed, but with gulp-concat-css is everything ok
![bbb0hhx](https://cloud.githubusercontent.com/assets/8271649/6205668/ce73e38e-b587-11e4-8881-bcd1265ca1a6.png)

npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ 'c:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--save-dev',
1 verbose cli   'gulp-minify-css' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose stack Error: Invalid version: "0.1"
4 verbose stack     at Object.module.exports.fixVersionField (c:\Program Files\nodejs\node_modules\npm\node_modules\normalize-package-data\lib\fixer.js:190:13)
4 verbose stack     at c:\Program Files\nodejs\node_modules\npm\node_modules\normalize-package-data\lib\normalize.js:30:38
4 verbose stack     at Array.forEach (native)
4 verbose stack     at normalize (c:\Program Files\nodejs\node_modules\npm\node_modules\normalize-package-data\lib\normalize.js:29:15)
4 verbose stack     at final (c:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:342:33)
4 verbose stack     at then (c:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:126:33)
4 verbose stack     at c:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:316:48
4 verbose stack     at evalmachine.<anonymous>:265:20
4 verbose stack     at OpenReq.Req.done (c:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:141:5)
4 verbose stack     at OpenReq.done (c:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:61:22)
5 verbose cwd d:\OpenServer\OpenServer\domains\trygulp
6 error Windows_NT 6.1.7601
7 error argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save-dev" "gulp-minify-css"
8 error node v0.12.0
9 error npm  v2.5.1
10 error Invalid version: "0.1"
11 error If you need help, you may report this error at:
11 error     <http://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
Is the `"version"` attribute in your `package.json` `"0.1"` by any chance? That's not a valid SemVer version. Perhaps you could try `"0.1.0"`?

**Comment by serjyamp** [comment]
thanks, you are right

**Comment by othiym23** [comment]
Closing as resolved.

**Comment by anton-arsentyev** [comment]
Maybe its better to change this Error message to human one?)
Something like 'Invalid version: "0.1". Use semver for project versioning (for exam. 1.0.0)'
