### ISSUE TITLE
ERR! code EBUSY, ERR! errno -4082

### ISSUE THREAD

**Issue by GhostMouse** [npm/npm#7370]
I'm getting this when I run npm install -g node-inspector

Help, pls :)
```
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "node-inspector"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! path C:\Users\user\AppData\Roaming\npm\node_modules\node-inspector\node_modules\ws
npm ERR! code EBUSY
npm ERR! errno -4082

npm ERR! EBUSY, unlink 'C:\Users\user\AppData\Roaming\npm\node_modules\nodeinspector\node_modules\ws'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>
npm ERR! error rolling back Error: EBUSY, unlink 'C:\Users\user\AppData\Roaming\npm\node_modules\node-inspector\node_modules\ws'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  { [Error: EBUSY, unlink 'C:\Users\user\AppData\Roaming\npm\node_modules\node-inspector\node_modules\ws']
npm ERR! error rolling back   errno: -4082,
npm ERR! error rolling back   code: 'EBUSY',
npm ERR! error rolling back   path: 'C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\node-inspector\\node_modules\\ws' }
```

**Comment by smikes** [comment]
It looks like one of the files `npm` needs to write to in order to do the installation is locked by another process.  The first line approach to fixing this on Windows is to reboot. :-/

**Comment by AMEDOO** [comment]
I'm getting also the same problem, even when after rebooting windows.
Solution?

**Comment by smikes** [comment]
AMEDOO, can you create a new issue so we can track it and follow up separately?  When you do, please attach your npm-debug.log as a gist <https://gist.github.com>

**Comment by AMEDOO** [comment]
DONE :)

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.

**Comment by mattglynn** [comment]
this is still an issue
I'm trying to install abao

**Comment by vcernomschi** [comment]
This issue is reproducible only for Windows. Got it only one time when I had tried to install deepify 'npm install -g deepify' (https://www.npmjs.com/package/deepify) on Windows. Rebooting helped to solve issue.

**Comment by EugeValeiras** [comment]
`C:\Users\eugen\workspace\JHipster\lecopCentral>npm install -g yo
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "yo"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! path C:\Users\eugen\AppData\Roaming\npm\node_modules\yo\lib\cli.js
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod 'C:\Users\eugen\AppData\Roaming\npm\node_modules\yo\lib\cli.js'
npm ERR! enoent ENOENT: no such file or directory, chmod 'C:\Users\eugen\AppData\Roaming\npm\node_modules\yo\lib\cli.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\eugen\workspace\JHipster\lecopCentral\npm-debug.log`

Same issue here

**Comment by IsuruCham** [comment]
Did any of you managed to find a solution? This is really annoying. I cannot install any of the modules through npm and literally I cannot continue my work. Please respond anyone

**Comment by EugeValeiras** [comment]
@IsuruCham I re-installed Node and everything start working again.

**Comment by IsuruCham** [comment]
@EugeValeiras  I also reinstalled node two times, restarted the PC. Not solved the problem :(

**Comment by EugeValeiras** [comment]
@IsuruCham  what version of node did you install?? Install the 4.*, I pretty sure you have installed the 6.* version.

**Comment by echorohit** [comment]
```
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "-g" "cordova"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! path C:\projects
npm ERR! code EBUSY
npm ERR! errno -4082
npm ERR! syscall rename

npm ERR! EBUSY: resource busy or locked, rename 'C:\projects' -> 'C:\.projects.DELETE'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\projects\npm-debug.log


```


```
$ npm -v
3.8.3

```

```

$ node -v
v5.10.1
```
I am facing the same problem.  I am not able to proceed.

**Comment by yunfeihuang** [comment]
same issue

**Comment by yunfeihuang** [comment]
Did some one had resolve this issue? Rebooting is sames no use for me.

**Comment by yunfeihuang** [comment]
I hate windows.

**Comment by v8-suresh** [comment]
@yunfeihuang - mee tooo....

**Comment by fitra90** [comment]
try "npm cache clean" on cli
sometimes works, but not always

**Comment by EugeValeiras** [comment]
Remove your current node and install version 4.*

**Comment by RakeshVenkat** [comment]
I faced the same issue and got a Resolution from Article: [https://github.com/npm/npm/issues/8564]. I am using Windows 7 Enterprise. Solution was to **Uninstall** '_ByteFence Anti Malware_' Software.

**Comment by legodude17** [comment]
@RakeshVenkat gives a good solution. Make sure to close all other programs. If that doesn't work try disabling your anti malware software.

**Comment by willstorm** [comment]
@RakeshVenkat save my day :)

**Comment by wallacerodrigon** [comment]
RakeshVenkat, thanks a lot for your contribution. I waste much time by installing and uninstalling nodejs (4.x, 5.x, 6.x, 7.x) to figure out what's happening with that "lock..." and when I almost gave up, I found your post some minutes ago with a good solution: uninstall ByteFence. Thank God and Rakesh as well. 

God bless you, guy!

**Comment by Rahulkishanm** [comment]
@RakeshVenkat Thanks a lot

**Comment by jkomyno** [comment]
In my case I had to forcefully arrest adb.exe because it was holding myProject/node_modules/realm/android in a React Native project (I was removing node_modules/ to perform a new "npm install" again, due to [this issue](https://github.com/facebook/react-native/issues/4968)). To find which process is blocking a certain file/folder, I suggest y'all follow [this suggestion](http://superuser.com/a/643312).

**Comment by karthiksundar** [comment]
@RakeshVenkat Thanks for the suggestion. Works for me now.

**Comment by girishbalanagu** [comment]
`npm cache clean` is resolve this issue.

**Comment by frutality** [comment]
I don't have ByteFence Anti-Malware or any anti-malware software except default Windows Defender. It always was like this, but few weeks ago I saw this error message when tried to `npm run watch` with `webpack`.

Workaround for me is `vagrant reload` command. After that I can run `npm run watch` without problems, but only for once. If I stop watching and run, for example, `npm run build`, then I see error again. And again, after `vagrant reload` no problems with building or watching.

I never had this problem before, for months. I am using default file syncing method between host and guest, didn't changed configs, didn't upgrade npm/node or guest OS. I believe the problem is Windows, but I cannot understand, why it was never be a problem for a long time before. And what is solution really, not workaround.

**Comment by oceanmachine89** [comment]
Hi guys,
I too am having this issue.I'm running Windows 7 professional with node 9.4.0 and npm 5.2.6.Any help would be greatly appreciated as I have tried restarting the computer,disabling the anti virus and the windows defender and other solutions so far that I have seen and no result.

[2018-01-26T09_58_06_335Z-debug.log](https://github.com/npm/npm/files/1667394/2018-01-26T09_58_06_335Z-debug.log)

**Comment by krishnpalchouhan** [comment]
npm install --force 

clear all file from
 C:\Users\chouhank\AppData\Local\Temp
C:\Users\chouhank\AppData\Roaming\npm-cache
ignore if it's not able to delete all 
restart your system 
then try to install using -- force  option 


My issue is resolved with this
