### ISSUE TITLE
Getting started with the GeneiACS. Please help me how to run genieacs? Do i need to configure any files before i getting the GUI ?

### ISSUE THREAD

**Issue by Siddeshi** [npm/npm#7373]
root@4620b6a861e1:/opt/genieacs# npm install
npm WARN cannot run in wd genieacs@1.0.0 npm run configure (wd=/opt/genieacs)
npm WARN cannot run in wd genieacs@1.0.0 npm run compile (wd=/opt/genieacs)
root@4620b6a861e1:/opt/genieacs# npm run configure

> genieacs@1.0.0 configure /opt/genieacs
> cp ./config/config-sample.json ./config/config.json; cp ./config/parameters-sample.json ./config/parameters.json; cp ./config/custom_commands-sample.json ./config/custom_commands.json; cp ./config/auth-sample.js ./config/auth.js

root@4620b6a861e1:/opt/genieacs# npm run compile

> genieacs@1.0.0 compile /opt/genieacs
> coffee -cb lib/*.coffee test/*.coffee tools/*.coffee

root@4620b6a861e1:/opt/genieacs# genieacs-cwmp
bash: genieacs-cwmp: command not found
root@4620b6a861e1:/opt/genieacs#

Why it is giving me command not found ?? Do I need to configure any files ? help me to run GenieACS.

Thank you.

**Comment by KenanY** [comment]
@Siddeshi Please see my comment (https://github.com/npm/npm/issues/7352#issuecomment-74663914) on the previous issue you've already opened. Either close your previous ticket and we can continue here or don't open duplicate tickets at all; they clutter the issue tracker :)
