### ISSUE TITLE
Attempt to unlock which hasn't been locked

### ISSUE THREAD

**Issue by jarlhelin** [npm/npm#7381]
Dear contributor, 

I am trying to migrate from {CODEKIT} to a more controllable interface. I have chosen GULP, but I'm stuck and my knowledge in the matter is sparse. I have installed the nom package successfully, but when I try to install GULP, I get the following message:

---
npm install --global gulp
npm WARN locking Error: EACCES, open '/Users/Jarlhelin/.npm/_locks/gulp-709d00e5d169ceb3.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/Jarlhelin/.npm/_locks/gulp-709d00e5d169ceb3.lock failed { [Error: EACCES, open '/Users/Jarlhelin/.npm/_locks/gulp-709d00e5d169ceb3.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/Jarlhelin/.npm/_locks/gulp-709d00e5d169ceb3.lock' }
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "--global" "gulp"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1

npm ERR! Attempt to unlock /usr/local/lib/node_modules/gulp, which hasn't been locked

-------

Thank you for your time helping a beginner falling in love with NPM ;)
The best
/Jarl

**Comment by KenanY** [comment]
@jarlhelin Looks like you don't have permission to modify files in your `~/.npm/_locks` directory. Could you try taking ownership back?:

``` bash
$ sudo chown -R $(whoami) ~/.npm/_locks
```

**Comment by othiym23** [comment]
`sudo chown -R $(whoami) $HOME/.npm` is the safest thing to do here, as it ensures that your entire cache (including any git remotes) end up being owned by your user account, which will resolve all of these permissions problems. @jarlhelin, since you're a relative npm newcomer, have you used versions of npm prior to `npm@2.5.1`? I'm a little curious as to how that directory ended up with broken permissions in the first place.

**Comment by jarlhelin** [comment]
@KenanY effectively, I didn't SUDO my line. @othiym23 , I'm not sure what you ask me to tell you, i'm on  unknown territory here. I'll ry to be precise:

1 - I installed NODE.JS via their PKG @ http://nodejs.org
2 - I then followed a tutorial @ http://www.smashingmagazine.com/2013/10/29/get-up-running-grunt/
3 - Now I have changed my mind, I'll go with GULP, as critics say that this is the "Best" out there

What I have done so far on my OS X Yosemite:

1 - I deleted the NPM package
2 - Reinstall of the Node.js PKG via the website
3 - I created the line "export PATH=$PATH:/usr/local/mysql/bin/" in ".profile"
4 - In the terminal "npm install --global gulp"

Here is what I get in the terminal:

pc23:~ Jarlhelin$ sudo npm install --global gulp
/usr/local/bin/gulp -> /usr/local/lib/node_modules/gulp/bin/gulp.js
npm WARN unmet dependency /usr/local/lib/node_modules/phonegap/node_modules/phonegap-build requires colors@'0.6.x' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/phonegap/node_modules/colors,
npm WARN unmet dependency which is version 0.6.0-1
npm WARN unmet dependency /usr/local/lib/node_modules/phonegap/node_modules/prompt/node_modules/winston requires colors@'0.x.x' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/phonegap/node_modules/colors,
npm WARN unmet dependency which is version 0.6.0-1
gulp@3.8.11 /usr/local/lib/node_modules/gulp
├── v8flags@2.0.2
├── pretty-hrtime@0.2.2
├── interpret@0.3.10
├── deprecated@0.0.1
├── archy@1.0.0
├── minimist@1.1.0
├── semver@4.3.0
├── tildify@1.0.0 (user-home@1.1.1)
├── chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.2, supports-color@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)
├── orchestrator@0.3.7 (stream-consume@0.1.0, sequencify@0.0.7, end-of-stream@0.1.5)
├── liftoff@2.0.1 (extend@1.3.0, flagged-respawn@0.3.1, resolve@1.0.0, findup-sync@0.2.1)
├── gulp-util@3.0.3 (array-differ@1.0.0, beeper@1.0.0, object-assign@2.0.0, array-uniq@1.0.2, replace-ext@0.0.1, lodash.reescape@3.0.1, lodash.reevaluate@3.0.1, lodash.reinterpolate@3.0.1, vinyl@0.4.6, through2@0.6.3, multipipe@0.1.2, lodash.template@3.3.0, dateformat@1.0.11)
└── vinyl-fs@0.3.13 (graceful-fs@3.0.5, mkdirp@0.5.0, defaults@1.0.0, strip-bom@1.0.0, vinyl@0.4.6, through2@0.6.3, glob-stream@3.1.18, glob-watcher@0.0.6)

.. I see a phonegap install and I believe I tried an install a while ago.. I'm obviously having a compatibility-problem, or? Should i delete something?

thx!

**Comment by othiym23** [comment]
I don't see any errors there, but I do see that gulp was installed successfully. Does `gulp --version` work?

**Comment by jarlhelin** [comment]
I guess this was a false alarm. Everything seems to work fine. I did a version-check and all seems to be running.. I created the gulp file.js and I'll check out the "Gulpfile plugin registry" that is very explanatory. 

I'll leave my log in here for the sake of information for others.

Thank you for your time & patience. 
----
The log
----
pc23:~ Jarlhelin$ gulp --version
[12:59:17] CLI version 3.8.11
pc23:~ Jarlhelin$ npm install --save-dev gulp
gulp@3.8.11 node_modules/gulp
├── v8flags@2.0.2
├── interpret@0.3.10
├── pretty-hrtime@0.2.2
├── deprecated@0.0.1
├── archy@1.0.0
├── minimist@1.1.0
├── semver@4.3.0
├── tildify@1.0.0 (user-home@1.1.1)
├── chalk@0.5.1 (escape-string-regexp@1.0.2, ansi-styles@1.1.0, supports-color@0.2.0, has-ansi@0.1.0, strip-ansi@0.3.0)
├── orchestrator@0.3.7 (stream-consume@0.1.0, sequencify@0.0.7, end-of-stream@0.1.5)
├── gulp-util@3.0.3 (array-uniq@1.0.2, beeper@1.0.0, object-assign@2.0.0, array-differ@1.0.0, replace-ext@0.0.1, lodash.reescape@3.0.1, lodash.reinterpolate@3.0.1, lodash.reevaluate@3.0.1, vinyl@0.4.6, multipipe@0.1.2, lodash.template@3.3.0, dateformat@1.0.11, through2@0.6.3)
├── liftoff@2.0.1 (extend@1.3.0, flagged-respawn@0.3.1, resolve@1.0.0, findup-sync@0.2.1)
└── vinyl-fs@0.3.13 (graceful-fs@3.0.5, mkdirp@0.5.0, defaults@1.0.0, strip-bom@1.0.0, vinyl@0.4.6, through2@0.6.3, glob-stream@3.1.18, glob-watcher@0.0.6)
pc23:~ Jarlhelin$ cd Dropbox/work/Localhost/_new_project/
pc23:_new_project Jarlhelin$ ls
gulpfile.js
pc23:_new_project Jarlhelin$ gulp
[13:06:19] Using gulpfile ~/Dropbox/work/Localhost/_new_project/gulpfile.js
[13:06:19] Starting 'default'...
[13:06:19] Finished 'default' after 49 μs
pc23:_new_project Jarlhelin$
