### ISSUE TITLE
npm shrinkwrap - devDependency is also a dependency of a dependency

### ISSUE THREAD

**Issue by charlierudolph** [npm/npm#7385]
If I shrinkwrap package A
```
A package.json
  dependencies
    B@0.0.1
  devDependencies
    C@0.0.1
  

B package.json
  dependencies
    C@0.0.1
```
The shrinkwrap will not list C as a dependency of B.

I can currently work around this by removing node modules, running "npm install --production", and then shrinkwrapping. I would prefer if this worked without requiring the extra step.

**Comment by othiym23** [comment]
This is a nasty, and easy to hit, shrinkwrap bug. Thanks for filing it! I'm a little appalled we didn't notice it sooner. @iarna, is this something that the new shrinkwrap code in `multi-stage` addresses? Either way, this should probably get addressed soonish.

**Comment by daradib** [comment]
I think this is the same issue as #4161.

**Comment by othiym23** [comment]
@daradib You're right! I'm closing this bug in favor of #4161, and will label that issue accordingly. Thank you!
