### ISSUE TITLE
Warn when using "*" for dependency versions by default.

### ISSUE THREAD

**Issue by Havvy** [npm/npm#7386]
Packages that depend upon other packages should not depend on the "*" version, especially if they are published onto `npm`. Doing so is a great way to make builds fail in the future and make people hate your package. As such, we should be encouraging users to pin their dependency versions, and a warning does exactly that.

**Comment by ljharb** [comment]
This need not necessarily apply to devDependencies, altho it probably should.

If so, can this also apply to any semver range that automatically brings in major version bumps, such as ">="?

**Comment by othiym23** [comment]
I think this is probably a good idea, but I'd like to talk about it a little before we implement it. I think this is a good ratchet to turn on npm's ongoing "gentle" encouragement of developers to follow hygienic semver practices, but it does feel a little prescriptive. I'm going to tweet this one and see if there are strong opinions pro or con. Thanks for making this suggestion!

**Comment by msikma** [comment]
It seems like a very bad idea to use a `*` version, and I can't immediately think of any real scenarios where this would be the preferred or best option. Maybe in cases where a package does nothing except preprocess some other package, such as renaming `css` files to `scss` so they can be imported as Sass files (bit silly example, but conceivable). Giving a warning seems like a reasonable thing to do.

**Comment by mscdex** [comment]
+1 for warning and proceeding anyway, -1 for any other behavior (including deprecation)

**Comment by mikeal** [comment]
How about an "are you sure" dialog for every dep?

**Comment by Havvy** [comment]
People would just disable the dialog the first time they see it. That'd be a bad change.

**Comment by othiym23** [comment]
Bad @mikeal! No trolling the feature requests!

**Comment by mikeal** [comment]
@othiym23 hahaha! In all seriousness, I think anything we can do to discourage terrible practices like this is a good idea. Can we also tell people that peerDependencies are terrible when they use those as well?

**Comment by othiym23** [comment]
> In all seriousness, I think anything we can do to discourage terrible practices like this is a good idea.

Agreed. I just want to be cautious about spamming people with gratuitous warnings (in fact, we need to reduce the number of warnings users see now).

> Can we also tell people that peerDependencies are terrible when they use those as well?

This is kind of a digression, but see https://github.com/angular/angular.js/pull/10732#issuecomment-74984594 and follow the link there to the description of what's up with `peerDependencies`. We're nerfing them some for `npm@3`, but, paradoxically enough, I think the end result will be more useful than what we did before, and much less painful for end users.

**Comment by nathan7** [comment]
@msikma "*" deps are transitive, infectious. Any package that depends on your hypothetical package will in effect have undefined behaviour.
I'd argue that "*" deps can still be valuable if `npm-shrinkwrap.json` is used rigorously, but perhaps that could just be made a component of the check.

**Comment by deepwell** [comment]
I agree. Anything that causes unexpected breakages in the future should be hard to do.

**Comment by ljharb** [comment]
It would also be wonderful to include a config option that refuses to publish any package with "allows-breaking-change" semver ranges in their dependencies/devDependencies, so people can opt in to actual enforcement :-)

**Comment by nathan7** [comment]
I think we've bounced around ideas for a package lint before, this would probably be a good idea to include.

**Comment by othiym23** [comment]
@nathan7 while I agree that this might be a good candidate for package linting (which is not something I've seen discussed much over the past year – most of the discussion has been around `npm doctor`, as a troubleshooting tool for npm itself), I also think that making it a warn on install or publish is also a good idea, because this is such a footgun for downstream users of packages.

> I'd argue that `"*"` deps can still be valuable if `npm-shrinkwrap.json` is used rigorously, but perhaps that could just be made a component of the check.

That describes a tiny enough segment of the npm user community that it may not be worth accomodating, especially given the prevailing sentiment here.

@ljharb 
> It would also be wonderful to include a config option that refuses to publish any package with "allows-breaking-change" semver ranges in their dependencies/devDependencies, so people can opt in to actual enforcement

Can you expand on this a bit? I'm not sure I understand what you're getting at.

**Comment by ljharb** [comment]
@othiym23 What I mean is, I'd like an npm global config opt-in setting for me, that I can also recommend my coworkers and collaborators use, which would actively prevent me from publishing a package that had "*" or ">=" etc semver ranges in its dependency list.

In other words, make the default behavior nice and friendly and be a warning, but allow for stricter "don't do this it's bad" behavior to be opted in to.

**Comment by othiym23** [comment]
@ljharb is this really behavior that needs to be configurable, or is it enough to have just the warning warning? I feel like we passed Peak npm Configuration a while ago, and am trying to be extremely parsimonious in introducing new configuration from now on.

Perhaps a standalone npm linter _would_ be a useful way to pilot some of this behavior. There _is_ http://npm.im/fixpack, which could maybe used as the basis for a more detailed linter / cleaner (although I didn't check with @henrikjoreteg before volunteering his package).

**Comment by ljharb** [comment]
I'd be satisfied with the warning at least, that's for sure. An npm linter would be great too.

**Comment by Havvy** [comment]
Nobody has said anything against this since it was open. Seems anybody who is paying attention to the project wants it in it.
