### ISSUE TITLE
Remove install warnings about dependencies missing useful fields

### ISSUE THREAD

**Issue by smikes** [npm/npm#7391]
Per https://github.com/npm/npm/issues/7376#issuecomment-75017272

```
npm WARN package.json resolve@0.3.1 No readme data.
npm WARN package.json github-url-from-git@1.1.1 No repository field.
npm WARN package.json assert-plus@0.1.2 No repository field.
npm WARN package.json ctype@0.5.2 No repository field.
```

> These warnings may be safely ignored, as they are telling you that various helpful fields are missing from the package.json fields of dependencies. These warnings are of debatable utility for you as an end user and will probably be going away soon as a result.

Warnings should only appear on pack / publish.  Optional (extra credit): package linter that returns non-zero exit code when would warn.

/cc @othiym23 low-hanging fruit for new contribs?

**Comment by KenanY** [comment]
https://github.com/npm/npm/issues/5253 :)

**Comment by smikes** [comment]
Closing as duplicate, thanks to @KenanY for the link.
