### ISSUE TITLE
Log exact command line when shelling out to `git

### ISSUE THREAD

**Issue by smikes** [npm/npm#7392]
ref #5244 

It sounds like you have solved the problem you were experiencing.

> I think it would be worthwhile updating the error to include the exact Git command that npm is executing in order to aid people troubleshooting this.

This is a good feature request. I am not sure if it has been done already in the latest version of npm -- I don't use git-repo dependencies very often -- but I will forward this to Forrest since it's a feature request

/cc @othiym23 ; feature request: log exact command line passed to git; log has git clone git://github.com/michaelficarra/cscodegen.git which is the logical command line but does not include e.g., the target directory (C:\Users\DTuppeny\AppData\Roaming\npm-cache_git-remotes\git-github-com-michaelficarra-cscodegen-git-c4b567f3)

**Comment by othiym23** [comment]
If somebody wants to take a whack at this, I will work with them to land it. It's not as urgent as a bunch of the other things the core team has on their plate right now, though.

**Comment by thriqon** [comment]
I have the following:

![2015-02-25-203652_1920x1080_scrot](https://cloud.githubusercontent.com/assets/768913/6378850/43237cbe-bd2e-11e4-8c27-a9d52e0bab3b.png)

The full command is printed at the very top, and it actually includes all arguments that are sent to git (including special w32-only flags).

Is this how you had it in mind? If yes, I will push it to my fork :) It is only a little addition on the utils/git file.

**Comment by othiym23** [comment]
Yes, please! Could you check and see if the tests continue to pass with your change?

Thanks for putting that together!

**Comment by smikes** [comment]
Fixed! Thanks for the PR, @thriqon !
