### ISSUE TITLE
ENOENT errno -4058

### ISSUE THREAD

**Issue by ronny-springer** [npm/npm#7393]
I try to install tagged releases from github while using npm install task and I got mostly issues like following lines. 
```
$ npm install -d --save https://github.com/Modernizr/Modernizr/archive/v2.8.3.tar.gz
npm info it worked if it ends with ok
npm info using npm@2.5.1
npm info using node@v1.2.0
npm info retry fetch attempt 1 at 15:27:50
npm info attempt registry request try #1 at 15:27:50
npm http fetch GET https://github.com/Modernizr/Modernizr/archive/v2.8.3.tar.gz
npm http fetch 200 https://github.com/Modernizr/Modernizr/archive/v2.8.3.tar.gz
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\Program Files\\iojs\\node.exe" "c:\\Program Files\\iojs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-d" "--save" "https://gi
npm ERR! node v1.2.0
npm ERR! npm  v2.5.1
npm ERR! path C:\Users\RSPRIN~1.CAN\AppData\Local\Temp\npm-7396-943a15a3\unpack-ddc9b881466a\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\RSPRIN~1.CAN\AppData\Local\Temp\npm-7396-943a15a3\unpack-ddc9b881466a\package.jso
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     c:\checkout\projects\Cumulus\CJCApps\webclient\cwc-web\npm-debug.log
/c/Program Files/iojs/npm: line 14:  8540 Signal 112              (core dumped) "$basedir/node.exe" "$basedir/node_modules/npm/bin/npm-cli.js" "$@"
```
Other sintaxis like `npm install -d --save @Modernizr/Modernizr:@2.8.3` or 
`npm install https://github.com/Modernizr/Modernizr/tarball/v2.8.3` also not working.

Can somebody explain and fix this issue? Is there a workaround for this?
Best,
Ronn

**Comment by smikes** [comment]
This looks like a crash in `iojs`: `/c/Program Files/iojs/npm: line 14:  8540 Signal 112              (core dumped)`

However, in this case there is an additional problem: the tarball you are trying to install (Modernizr 2.8.3) does not contain a `package.json`.  `npm` requires a `package.json`, so `npm` cannot install that version of Modernizr.

**Comment by othiym23** [comment]
Yes. npm can only install GitHub repositories that are valid npm packages, and this means that they contain a package.json.

Closing as resolved.

**Comment by ronak11** [comment]
@smikes 
i am new for nod.js 
 i install it for Ghost bloging platform but i have a error 
#4058 
![untitled-5](https://cloud.githubusercontent.com/assets/13674333/9521181/e5b548d0-4cea-11e5-8358-ae3dc7b1b391.png)

**Comment by KenanY** [comment]
@ronak11 It looks to me like you are not in the directory where you downloaded Ghost. When you run `npm start`, there **must** be a `package.json` in your current working directory, otherwise `npm` will have no idea what you want it to do.

If you have any further issues, it would be best to open a new ticket.

**Comment by ronak11** [comment]
@KenanY  
Both Ghost and node js in C:\ directory .i have no idea about Ghost and Node js .
so can you  tell me step by step.
Thanks

**Comment by KenanY** [comment]
@ronak11 You should `cd` into Ghost's directory, then follow Ghost's [quick install guide](https://github.com/TryGhost/Ghost/tree/fd3127b342c99c8f640652c6c7d4d1d150e0397d#quick-start-install) from step 4. If you need further help with Ghost, it would be best if you ask on a forum/mailing list/chat room where other Ghost users hang around.
