### ISSUE TITLE
Npm global modules

### ISSUE THREAD

**Issue by pensierinmusica** [npm/npm#7395]
Npm currently saves global modules where Node is installed.

This is unconvenient when there are multiple versions of Node on the system (e.g. using nvm), and one needs some npm modules globally available (afterall, that's the concept of "global", isn't it?)

Think about modules like Yeoman (and its generators), Grunt, Express, and so on.

Wouldn't it be way more convenient if we could keep global npm modules in a common folder in the system (something like /usr/local/lib/node_modules), that can be accessed by all Node versions?

This way it's easier to install, uninstall, or update things just once and have the same setting system-wide. If a project needs something different, then the module should be installed locally (like it happens for most modules).

It just seem to make much more sense to me, besides being more efficient.

In case we don't want to change the default behaviour, at least it could be offered as a configurable option (something like `shared_global: true`).

Is there a way for npm to implement this? What are your thoughts?

Cheers!

**Comment by KenanY** [comment]
There's a config for that: [`prefix`](https://docs.npmjs.com/misc/config#prefix)!

**Comment by pensierinmusica** [comment]
Thanks @KenanY!

Following your advice, what I suggested can be achieved by adding `export NPM_CONFIG_PREFIX="/usr/local"` to `.bash_profile`.

Closing this issue  :)
