### ISSUE TITLE
SSL Error while installing Contextify on Windows Server 2012 - CERT_UNTRUSTED

### ISSUE THREAD

**Issue by BakhmudovR79** [npm/npm#7396]
Hi!

I'm having this error while trying to install contextify to install after Parsoid for MediaWiki's VisualEditor.
Any idea what to do?
Thank you in advance!

C:\Program Files (x86)\nodejs>npm install contextify
npm http GET https://registry.npmjs.org/contextify
npm http GET https://registry.npmjs.org/contextify
npm http GET https://registry.npmjs.org/contextify
npm ERR! Error: SSL Error: CERT_UNTRUSTED
npm ERR! at ClientRequest. (C:\Program Files (x86)\nodejs\node_mo
dules\npm\node_modules\request\main.js:440:26)
npm ERR! at ClientRequest.g (events.js:156:14)
npm ERR! at ClientRequest.emit (events.js:67:17)
npm ERR! at HTTPParser.parserOnIncomingClient as onIncoming
npm ERR! at HTTPParser.parserOnHeadersComplete as onHeadersComplete
npm ERR! at CleartextStream.socketOnData as ondata
npm ERR! at CleartextStream._push (tls.js:375:27)
npm ERR! at SecurePair.cycle (tls.js:734:20)
npm ERR! at EncryptedStream.write (tls.js:130:13)
npm ERR! at Socket.ondata (stream.js:38:26)
npm ERR! [Error: SSL Error: CERT_UNTRUSTED]
npm ERR! You may report this log at:
npm ERR! http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR! npm-@googlegroups.com

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\Program Files (x86)\nodejs\\node.exe" "C:\Program File
s (x86)\nodejs\node_modules\npm\bin\npm-cli.js" "install" "contextify"
npm ERR! cwd C:\Program Files (x86)\nodejs
npm ERR! node -v v0.6.20
npm ERR! npm -v 1.1.37
npm ERR! message SSL Error: CERT_UNTRUSTED
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR! C:\Program Files (x86)\nodejs\npm-debug.log
npm ERR! not ok code undefined
npm ERR! not ok code 1

C:\Program Files (x86)\nodejs>

**Comment by BakhmudovR79** [comment]
Fixed with
npm config set ca=""

**Comment by KenanY** [comment]
@BakhmudovR79 A more ideal solution would be to update your ancient Node.js and `npm` installations. Node.js v0.6.20 is **three years old** and hasn't been supported by just about anybody ever since v0.8 and v0.10 came into the world. The two supported versions right now are v0.10 and v0.12 (and to a lesser extent v0.8 for a little while more). I highly recommend you upgrade to the latest stable release, which you can find at [nodejs.org](http://nodejs.org/).
