### ISSUE TITLE
TypeError: Request path contains unescaped characers.

### ISSUE THREAD

**Issue by p4ko** [npm/npm#7404]
@migounette i have the same. i have tried to create an cordova project with SAP Kapsel.

i create the procect in the cmd:

cordova -d create C:\Kapsel_Projects\Kapsel_Test\ com.testproject.kapsel_test Kapsel_Test 
"{\"plugin_search_path\":\"C:/SAP/MobilePlatform/KapselSDK/plugins/\"}"

here some information for Kapsel (http://scn.sap.com/docs/DOC-49592)
http://help.sap.com/saphelp_smp304sdk/helpdata/en/7c/1c7d0570061014a19bec0d54ebb4ea/content.htm

if i run this i got an TypeError
```
TypeError: Request path contains unescaped characers.
at new ClientRequest (_http_client.js:73:11)
at TunnelingAgent.exports.request (http.js:49:10)
at TunnelingAgent.createSockete(C:\Users\pkh\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova_lib\node_modules\request\node_modules\tunell-agent\index.js:117:25)
```
i have tried your solution with the new tunnel-agent, but it diddn't work.

**Comment by p4ko** [comment]
My tunnle and Request version

 "tunnel-agent": "~0.3.0",

request
  "version": "2.22.0",

![package_json](https://cloud.githubusercontent.com/assets/3890237/6283367/008a65a0-b8e4-11e4-81c7-63b0e76a321e.JPG)

**Comment by smikes** [comment]
Thanks.  Can you please upload your `npm-debug.log` file as a gist <https://gist.github.com> ?

**Comment by othiym23** [comment]
Also, which parts of this are the npm error? The stacktrace you included in your original post doesn't include npm, and looks like it's purely coming out of Cordova.

**Comment by p4ko** [comment]
hi I found a solution. i copied the tunnel-agent v. 0.4.1 in the wrong folder (c:/nodejs/node_module/npm...,). I copied in the folder (C:/Users/username/.cordova...) 

thx for the help.
