### ISSUE TITLE
npm publish: FATAL ERROR: JS Allocation failed - process out of memory

### ISSUE THREAD

**Issue by B2F** [npm/npm#7405]
Hello,

I am currently trying to update a [previously published package](https://www.npmjs.com/package/succss) to a major version (0.1.x to 1.0.0).

I am running into the following issue:

    npm publish --tag v1.0.0
    npm WARN invalid config tag="v1.0.0"
    npm WARN invalid config Tag must not be a SemVer range
    \
    
    Fatal error in ../deps/v8/src/handles.h, line 48
    CHECK(location_ != NULL) failed
    
    
    ==== C stack trace ===============================
    
     1: V8_Fatal
     2: v8::String::NewExternal(v8::Isolate*, v8::String::ExternalAsciiStringResource*)
     3: node::ExternString<v8::String::ExternalAsciiStringResource, char>::New(v8::Isolate*, char const*, unsigned long)
     4: node::StringBytes::Encode(v8::Isolate*, char const*, unsigned long, node::encoding)
     5: void node::Buffer::StringSlice<(node::encoding)2>(v8::FunctionCallbackInfo<v8::Value> const&)
     6: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&))
     7: ??
     8: ??
    Instruction non permise (core dumped)

    zen@localhost Succss:git tag -l
    v0.1.0
    v1.0.0

The error message is very similar to [this one] (https://github.com/iojs/io.js/issues/649), but I'm not sure how it is related since the iojs issue seems to arise from commandline with a Date string wrapped inside a Buffer...

I fail to see, where to look ? I tried with and without the --tag argument, I am trying to build from the master branch anyway.

Thanks in advance.

**Comment by smikes** [comment]
Several things are going on here.

For one, can you try using a stable version of `node` (0.10.36) and see if the problem goes away?  If it does, then it's not really an `npm` issue.

Secondly, the `--tag` option to `npm publish` is actually for setting dist-tags, such as `latest` or `next` -- if you have more than one stream of published versions, kind of like git branches but for build artifacts.  Since dist-tags have to share a namespace with versions, they shouldn't overlap -- that's what the warning message is telling you.  So just use `npm publish` or `npm publish --latest`

Finally, what version of `npm` are you using?  If you're using `iojs`, it's probably a recent one, but can you attach the `npm-debug.log` if any?  Or else just let me know the result of running `npm --version`.

Thanks!

**Comment by B2F** [comment]
Thanks for your explanations.

I updated node to 0.10.36 like you suggested, unfortunately, when I run npm publish it fails without logs, just the following:

    FATAL ERROR: JS Allocation failed - process out of memory
    Abandon (core dumped)

My npm version was 1.4.28, I am not using iojs. I have just updated to 2.5.1 following issue #3340 but it still fails with the above error message.

Update: While writing the above, I figured I had a rather heavy untracked screenshots (~500MB) directory under the same tree as the source. But [from the doc] (https://docs.npmjs.com/misc/developers) I thought packages where not parsing the local directory but only cloning from git repository. So still following #3340 I moved the big untracked folders away, now I got this npm-debug.log:

    0 info it worked if it ends with ok
    1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'publish' ]
    2 info using npm@2.5.1
    3 info using node@v0.12.0
    4 verbose publish [ '.' ]
    5 silly cache add args [ '.', null ]
    6 verbose cache add spec .
    7 silly cache add parsed spec { raw: '.',
    7 silly cache add   scope: null,
    7 silly cache add   name: null,
    7 silly cache add   rawSpec: '.',
    7 silly cache add   spec: '/home/zen/Projets/Informatique/OpenSource/github/Succss',
    7 silly cache add   type: 'directory' }
    8 verbose addLocalDirectory /home/zen/.npm/succss/1.0.0/package.tgz not in flight; packing
    9 verbose tar pack [ '/home/zen/.npm/succss/1.0.0/package.tgz',
    9 verbose tar pack   '/home/zen/Projets/Informatique/OpenSource/github/Succss' ]
    10 verbose tarball /home/zen/.npm/succss/1.0.0/package.tgz
    11 verbose folder /home/zen/Projets/Informatique/OpenSource/github/Succss
    12 info prepublish succss@1.0.0
    13 verbose addLocalTarball adding from inside cache /home/zen/.npm/succss/1.0.0/package.tgz
    14 silly cache afterAdd succss@1.0.0
    15 verbose afterAdd /home/zen/.npm/succss/1.0.0/package/package.json not in flight; writing
    16 verbose afterAdd /home/zen/.npm/succss/1.0.0/package/package.json written
    17 silly publish { name: 'succss',
    17 silly publish   version: '1.0.0',
    17 silly publish   description: 'Easy to install, easy to use CSS regression testing tool.',
    17 silly publish   author: { name: 'B2F', email: 'd4rb2f@gmail.com' },
    17 silly publish   bin: { succss: './bin/succss.py' },
    17 silly publish   scripts: { test: './selftests/run.sh' },
    17 silly publish   main: 'succss.js',
    17 silly publish   repository: { type: 'git', url: 'https://github.com/B2F/Succss' },
    17 silly publish   bugs: { url: 'https://github.com/B2F/Succss/issues' },
    17 silly publish   keywords: [ 'css', 'regression', 'testing', 'screenshots', 'capture' ],
    17 silly publish   dependencies: { casperjs: '1.1.0-beta3' },
    17 silly publish   preferGlobal: true,
    17 silly publish   private: false,
    17 silly publish   analyze: true,
    17 silly publish   license: 'MIT',
    17 silly publish   readme: '##SUCCSS, a CSS Regression testing tool\n###Turn your CSS designs into successful integrations.\n\nFull documentation at: [succss.ifzenelse.net][7]\n\n![small diff image example][12]\n\n####Install:\n```\nnpm install -g succss\n```\n\n####Configure:\n```\n// data.js\nSuccss.pages = {\n  \'home\': {\n    url:\'succss.ifzenelse.net/home\',\n    directory:\'screenshots/dir\',\n    // captures: { \'name\' : \'CSS selector\' }\n    captures: {\n      // leave an empty value if selector == name\n      \'header\':\'\',\n      \'dynamic-text\':\'body #header-text > #static-line + span\',\n      ...\n    },\n  },\n  \'another-page\': {\n    ...\n  }\n};\n\nSuccss.viewports = {\n  // \'./screenshots/dir/home--header--1366x768.png\' file\n  // \'./screenshots/dir/home--dynamic-text--1366x768.png\' file\n  \'default\': {\n    width: 1366,\n    height: 768\n  },\n  // \'./screenshots/dir/home--header--640x480.png\' file\n  // \'./screenshots/dir/home--dynamic-text--640x480.png\' file\n  \'mobile-landscape\': {\n    width: 640,\n    height: 480\n  },\n  ...\n}\n```\n\n####Run:\n```\nsuccss add your-conf.js\n```\n\n\n####Check updates against added references:\n```\nsuccss check your-conf.js\n```\n\n\n####Do you need more infos ?\n\n- [Installation troubleshooting][1]\n- [Advanced Configuration][2]\n- [Succss from the CLI][3]\n- [Custom validations][4]\n- [Why another CSS Regression Testing tool ?][5]\n- [Fork Succss !][6]\n- [Typical use cases][0]\n- --[Home page][7]\n\n![large diff image example][8]\n\n####Built with:\n- [CasperJS][9]\n- [Imagediff][10]\n- [ResembleJS][11]\n- MIT Licenses\n\n[0]:http://succss.ifzenelse.net/usecases\n[1]:http://succss.ifzenelse.net/installation\n[2]:http://succss.ifzenelse.net/configuration\n[3]:http://succss.ifzenelse.net/commandline\n[4]:http://succss.ifzenelse.net/customize\n[5]:http://succss.ifzenelse.net/why\n[6]:http://succss.ifzenelse.net/fork\n[7]:http://succss.ifzenelse.net/home\n[8]:https://raw.githubusercontent.com/B2F/Succss-doc/master/img/screenshots/large-diff.jpeg\n[9]:http://casperjs.org/\n[10]:http://humblesoftware.github.io/js-imagediff/\n[11]:http://huddle.github.io/Resemble.js/\n[12]:https://raw.githubusercontent.com/B2F/Succss-doc/master/img/screenshots/small-diff.jpeg\n',
    17 silly publish   readmeFilename: 'README.md',
    17 silly publish   gitHead: '86d549ae530ff01c374b1b7a80b3ac9fa5a01867',
    17 silly publish   homepage: 'https://github.com/B2F/Succss',
    17 silly publish   _id: 'succss@1.0.0',
    17 silly publish   _shasum: 'c77fbf0a68a2c3efcff4b7d003196126350cf80c',
    17 silly publish   _from: '.' }
    18 silly mapToRegistry name succss
    19 silly mapToRegistry using default registry
    20 silly mapToRegistry registry https://registry.npmjs.org/
    21 silly mapToRegistry uri https://registry.npmjs.org/succss
    22 verbose publish registryBase https://registry.npmjs.org/
    23 silly publish uploading /home/zen/.npm/succss/1.0.0/package.tgz
    24 verbose request uri https://registry.npmjs.org/succss
    25 verbose request sending authorization for write operation
    26 info attempt registry request try #1 at 15:44:57
    27 verbose request id a1b37e8cde8d5425
    28 http request PUT https://registry.npmjs.org/succss
    29 http 400 https://registry.npmjs.org/succss
    30 verbose bad json <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
    30 verbose bad json <html><head>
    30 verbose bad json <title>400 Bad Request</title>
    30 verbose bad json </head><body>
    30 verbose bad json <h1>Bad Request</h1>
    30 verbose bad json <p>Your browser sent a request that this server could not understand.<br />
    30 verbose bad json </p>
    30 verbose bad json </body></html>
    31 error registry error parsing json
    32 verbose headers { date: 'Fri, 20 Feb 2015 14:44:45 GMT',
    32 verbose headers   server: 'Apache',
    32 verbose headers   'content-length': '226',
    32 verbose headers   connection: 'close',
    32 verbose headers   'content-type': 'text/html; charset=iso-8859-1' }
    33 verbose request invalidating /home/zen/.npm/registry.npmjs.org/succss on PUT
    34 error publish Failed PUT 400
    35 verbose stack SyntaxError: Unexpected token <
    35 verbose stack <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
    35 verbose stack <html><head>
    35 verbose stack <title>400 Bad Request</title>
    35 verbose stack </head><body>
    35 verbose stack <h1>Bad Request</h1>
    35 verbose stack <p>Your browser sent a request that this server could not understand.<br />
    35 verbose stack </p>
    35 verbose stack </body></html>
    35 verbose stack
    35 verbose stack     at Object.parse (native)
    35 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:205:23)
    35 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:178:14)
    35 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:344:22)
    35 verbose stack     at Request.emit (events.js:110:17)
    35 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1239:14)
    35 verbose stack     at Request.emit (events.js:129:20)
    35 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1187:12)
    35 verbose stack     at IncomingMessage.emit (events.js:129:20)
    35 verbose stack     at _stream_readable.js:908:16
    36 verbose cwd /home/zen/Projets/Informatique/OpenSource/github/Succss
    37 error Linux 3.18.5-201.fc21.x86_64
    38 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "publish"
    39 error node v0.12.0
    40 error npm  v2.5.1
    41 error Unexpected token <
    41 error <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
    41 error <html><head>
    41 error <title>400 Bad Request</title>
    41 error </head><body>
    41 error <h1>Bad Request</h1>
    41 error <p>Your browser sent a request that this server could not understand.<br />
    41 error </p>
    41 error </body></html>
    42 error If you need help, you may report this error at:
    42 error     <http://github.com/npm/npm/issues>
    43 verbose exit [ 1, true ]

**Comment by B2F** [comment]
After a more careful reading, I think I am going to need a .npmignore

**Comment by smikes** [comment]
Yes, or a .gitignore may also work. Because sometimes what you want to publish are build artifacts (eg a minified version of your code) npm will publish everything even if it's not in git -- so your publish is failing because npm is trying to make a very large file, I would guess.

**Comment by B2F** [comment]
Actually, even without the .gitignore the package was pushed after some time it seems... Because I came back and tried with the .gitignore a few minutes ago and had this message:

    npm ERR! publish Failed PUT 403
    npm ERR! Linux 3.18.5-201.fc21.x86_64
    npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "publish"
    npm ERR! node v0.12.0
    npm ERR! npm  v2.5.1
    npm ERR! code E403
    npm ERR! forbidden cannot modify pre-existing version: 1.0.0

Problem solved ! Good to know for next time I'll publish :)
