### ISSUE TITLE
Issues running browserify (Missing script: browserify)

### ISSUE THREAD

**Issue by Adelxoxo** [npm/npm#7408]
Hi,

I'm try to run broweserify and I have an issue getting it to work. It seems that it installs fine but I cant get it to work on this computer. Here's a screenshot of the cmd session showing me installing and trying to run browserify:
![ss 2015-02-19 at 11 32 44](https://cloud.githubusercontent.com/assets/6750289/6307410/c78b2a66-b93b-11e4-9102-bc7924b3b9e3.png)

here is the log:
http://puu.sh/g5jCd/bf4357472a.log

Thanks for any help you can provide.

**Comment by Adelxoxo** [comment]
Also I'm sorry if this happens to be a common issue but I couldn't find anything, I'm not used to using the search function on github.

**Comment by KenanY** [comment]
@Adelxoxo `npm run` is for running scripts ([docs](https://docs.npmjs.com/cli/run-script)). If you want to use the browserify binary you globally installed, you should just run `browserify` ([browserify docs](https://github.com/substack/node-browserify)).

**Comment by Adelxoxo** [comment]
Oh I see thank you.
