### ISSUE TITLE
Does npm clean dependencies?

### ISSUE THREAD

**Issue by trusktr** [npm/npm#7410]
For example, if I have a project A that depends on B, and B depends on C, then `npm install` will install C in the node_modules of B, right? But then, if I add C as a dependency of A, `npm install` will add C in the project's top-level node_modules, but it won't clean up the old C in the node_modules of B.

Shouldn't npm clean this up? Or maybe npm does clean, but I must've thought npm wasn't cleaning for some other reason I'm not aware of (I have a lot more modules than just A, B and C)?

**Comment by smikes** [comment]
You are looking for the command `npm dedupe`, which will attempt to remove redundant installations when the dependencies of multiple packages can be solved by a single version.

`npm@2` does not deduplicate automatically, but `npm@3` will.

**Comment by othiym23** [comment]
What @smikes said. `npm@2` is pretty light-touch when it comes to changing an installed `node_modules`, and `npm@3` will be much more aggressive about normalizing it.

Closing as resolved / answered.

**Comment by trusktr** [comment]
Sweeet!
