### ISSUE TITLE
`npm outdated` not what it says on the tin

### ISSUE THREAD

**Issue by smikes** [npm/npm#7416]
Now that `npm outdated` by default has `--depth 0` I notice that it doesn't exactly report only on `outdated` packages.  It seems to report all packages that are not`@latest`.  Notably this includes `npm` if you update to `npm@next`:

```
$ npm i -g npm@next
$ npm -v
2.6.1
$ npm -g outdated
Package  Current  Wanted  Latest  Location
npm        2.6.1   2.6.0   2.6.0  /Users/smikes/.nvm/versions/io.js/v1.3.0/lib > npm
```

Since the `outdated` list is the input to `npm update` and various external commands, this should be handled carefully.  I have two possible approaches

Simple algorithm:

```
var dist_tags = getDistTagsFor(package),
      installed = getInstalledVersion(package);

if (semver.gte(installed, dist_tags.latest)) {
  return;
}

package is outdated
```

This way `npm@next` will not be flagged by `npm outdated`.  

The above still has problems for people tracking a release line which is semver-less than `@latest` -- motivating example would be a package with
```
dist-tags: {
  latest: "2.1.0",
  older: "1.4.1"
}
versions: {
  "2.1.0",
  "2.0.2",
  "1.4.1",
  "1.4.0"
}
```

In practice I don't know how often that happens.

This situation can be addressed by this more complex algorithm:
```
var dist_tags = getDistTagsFor(package),
      requested = getVersionFromPackageJson(package),
      installed = getInstalledVersion(package);

// if user has requested a dist-tag
if (!semver.valid(requested)) {

   // if the installed version is outdated **for that dist-tag***
   if (semver.lt(installed, dist_tags.requested)) {
      // update to dist_tags.requested
   }
}

// handle non-dist-tag versions as above 
```

Additional bikeshedding welcome.  I believe this is actually independent of multi-stage-install and `npm@3`.

Some relevant issues: 
* #7415 (`npm update -g` unexpectedly fixed)
* #4261 - `npm update --save` updates versions like "0.6.1" => "~0.6.2"
* #4268 - `npm outdated` test with varying depth
* #6247 npm update should only update top-level dependencies

**Comment by othiym23** [comment]
I think that what `npm outdated` is returning in the cases you cite is correct, although what's going on is subtle enough to maybe require some clarification in the docs. If you're running a newer version of npm than latest, for instance, it's pretty much certain that you've decided to install `next` or some other prerelease version intentionally, and it's worth pointing out that it's nonstandard.

Also, due to the subterranean dependency between `npm outdated` and `npm update`, it's important that `npm -g update` never update to something other than `latest`, or else we're going to reproduce one of the problems that people were having with `npm -g update` before this change.

It definitely *looks* weird, but I think it's doing the right thing.

**Comment by smikes** [comment]
Here's a thought:

```
Svarog:foo smikes$ grep _from /Users/smikes/.nvm/versions/io.js/v1.2.0/lib/node_modules/npm/package.json 
  "_from": "npm@next",
Svarog:foo smikes$ npm outdated -g
Package  Current  Wanted  Latest  Location
npm        2.6.1   2.6.0   2.6.0  /Users/smikes/.nvm/versions/io.js/v1.2.0/lib > npm
Svarog:foo smikes$ 
```

What if the `wanted` field for global modules were populated from the `_from` field?  Then `outdated` would either report "Wanted" as `next` or lookup and dereference `next` and report "Wanted" as 2.6.1?

Anyway, going to close this for now, since I don't really have the energy to work on it and I don't think it'll move a lot until after the `npm@3` milestone.

I think it would be good if 

```
npm i -g npm@next
npm update -g
``` 

would preserve the `npm@next` version after the update.  But this is icing on the cake, compared to `npm update -g` not being a total disaster.
