### ISSUE TITLE
npm search yeoman-generator is not working

### ISSUE THREAD

**Issue by mindaslab** [npm/npm#7419]
OS: Ubuntu 14.04

When trying to execute 

```
$ npm search yeoman-generator
```
Got an error. See the logs here https://www.dropbox.com/s/zxms1y647kptgen/npm-debug.log.tar.bz2?dl=0

**Comment by mindaslab** [comment]
Ran it once again it worked, so closing this issue.

**Comment by smikes** [comment]
I apologize for this, this is a known bug (see #6016)

`npm search` was written when there were on the order of 1,000 packages in the `npm` registry.  Now that there are > 100,000, the way `npm search` was originally implemented no longer scales.

We're working on an update to `npm search` that will make command-line searching work again; in the meantime please try the online search engine at <https://npmjs.com>
