### ISSUE TITLE
I cannot initiate watch with foundation-app 

### ISSUE THREAD

**Issue by persephonepunch** [npm/npm#7422]
```
$foundation-apps watch
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.10.35
npm ERR! npm  v2.4.1

npm ERR! missing script: start
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/yoonsunlee/npm-debug.log
$start
-bash: start: command not found
```

**Comment by smikes** [comment]
It looks like the command `foundation-apps watch` is trying to run the command `npm start`, which tells `npm` to run the script defined as `start` in the `package.json` file.

`npm` is able to find a `package.json` file, but the script `start` is not defined in it.

Usually one of two things causes this problem.  First, make sure you are running `foundation-apps watch` from the correct directory.  It looks like you're running the command from your home directory (/Users/yoonsunlee/) and you may need to `cd` into the directory that `foundation-apps new` created when you ran `foundation-apps new myApp`


Second, check `package.json` for a `scripts` section that contains `start`:

```
$ cat package.json
{
  "name": "myApp",
  "scripts": {
    "start": "run-server...",
    "some-other-script": "command"
  }
}
```

If you're still having trouble, please upload your `package.json` file as a gist <https://gist.github.com> and post the link in a comment on this issue.

Thanks!

**Comment by persephonepunch** [comment]
Thank you. That was exactly the problem.

I was able to do the build in the right directory.

**Comment by othiym23** [comment]
Closing as resolved.
