### ISSUE TITLE
C:\Users\alan\Develop\Programs\nodejs>npm install npm ERR! install Couldn't read dependencies

### ISSUE THREAD

**Issue by alanMediacy** [npm/npm#7432]
hello, please help me. I am a newbi in github/angularjs.

C:\Program Files\nodejs>npm install npm -g
npm ERR! not a package C:\Program Files\nodejs\npm
npm ERR! addLocal Could not install C:\Program Files\nodejs\npm
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "npm" "-g"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! path C:\Users\alan\AppData\Local\Temp\npm-4016-e2ab39ab\unpack-9da97c89
f34f\package.json
npm ERR! code ENOENT
npm ERR! errno -4058

npm ERR! enoent ENOENT, open 'C:\Users\alan\AppData\Local\Temp\npm-4016-e2ab39ab
\unpack-9da97c89f34f\package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "npm" "-g"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1

npm ERR! Uncaught, unspecified "error" event.
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Program Files\nodejs\npm-debug.log

C:\Program Files\nodejs>

**Comment by smikes** [comment]
It looks like you are trying to update `npm`, but the `npm` command is being found and interpreted as a package file (which it is not).  I'm a little surprised that I haven't seen this error before.

Can you try this:

```
cd C:\Program Files\nodejs
npm install npm@latest
```

That should prevent `npm` from looking at the `npm` file as a package, and get you the latest version of `npm`, which is currently 2.6.1

**Comment by alanMediacy** [comment]
Hello, thank you so much.
I try it. The response:

C:\Program Files\nodejs>npm install npm@latest
npm ERR! tar.unpack untar error C:\Users\alan\AppData\Roaming\npm-cache\npm\2.6.
0\package.tgz
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Users\\alan\\Develop\\Programs\\nodejs\\\\node.exe" "C:\\User
s\\alan\\Develop\\Programs\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install
" "npm@latest"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! path C:\Program Files\nodejs\node_modules
npm ERR! code EPERM
npm ERR! errno -4048

npm ERR! Error: EPERM, mkdir 'C:\Program Files\nodejs\node_modules'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM, mkdir 'C:\Program Files\nodejs\node_modules']
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   path: 'C:\\Program Files\\nodejs\\node_modules',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: 'C:\\Program Files\\nodejs\\node_modules\\npm',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack:
npm ERR!    [ 'C:\\Users\\alan\\Develop\\Programs\\nodejs\\node_modules\\npm\\no
de_modules\\fstream\\lib\\writer.js:171:23',
npm ERR!      'C:\\Users\\alan\\Develop\\Programs\\nodejs\\node_modules\\npm\\no
de_modules\\mkdirp\\index.js:46:53',
npm ERR!      'FSReqWrap.oncomplete (fs.js:99:15)' ] }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Users\\alan\\Develop\\Programs\\nodejs\\\\node.exe" "C:\\User
s\\alan\\Develop\\Programs\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install
" "npm@latest"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1

npm ERR! Uncaught, unspecified "error" event.
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Program Files\nodejs\npm-debug.log

C:\Program Files\nodejs>

**Comment by alanMediacy** [comment]
Ok i move all in a directory in my Documents to avoid permission problems

Te response:
<code>
C:\Users\alan\Develop\Programs\nodejs>npm install npm@latest
npm@2.6.0 node_modules\npm
</code>
<code>
C:\Users\alan\Develop\Programs\nodejs>

</code>
So looks good but if i try npm install:

C:\Users\alan\Develop\Programs\nodejs>npm install
npm ERR! install Couldn't read dependencies
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Users\\alan\\Develop\\Programs\\nodejs\\\\node.exe" "C:\\User
s\\alan\\Develop\\Programs\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install
"
npm ERR! node v0.12.0
npm ERR! npm  v2.6.0
npm ERR! path C:\Users\alan\Develop\Programs\nodejs\package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno -4058

npm ERR! package.json ENOENT, open 'C:\Users\alan\Develop\Programs\nodejs\packag
e.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directo
ry.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\alan\Develop\Programs\nodejs\npm-debug.log

C:\Users\alan\Develop\Programs\nodejs>

**Comment by alanMediacy** [comment]
Ok i cancelled all and retry from the beginning. Now works.
Thank you so much. 
Just another question before close: can you suggest me a guide to lear angular?

**Comment by smikes** [comment]
This one is probably pretty good: https://www.codeschool.com/courses/shaping-up-with-angular-js

**Comment by alanMediacy** [comment]
Thank you so much.

**Comment by Rafiozoo** [comment]
thanks!!
