### ISSUE TITLE
admin: now using freenode #npm for intra-team communication

### ISSUE THREAD

**Issue by othiym23** [npm/npm#7436]
@iarna and I spent some time over the last few weeks discussing how we can have better realtime discussions with people who are interested in what's going on with the development of the npm CLI. Transparency is an important part of a healthy OSS project, and it's something that feels a little lacking right now. After a bunch of back and forth, we decided that the best choice we had available to us was to make use of the existing #npm channel on freenode.

What this means is that Rebecca and I will be using this as our primary channel for talking about the stuff we're working on, and we'd love to see people like @KenanY, @smikes, @faiq, @nathan7, and others join us there for more realtime communication.

I have a very selfish reason for wanting the above-named to join in on this, which is that it's getting increasingly difficult for me to stay on top of the activity of npm. There's a lot going on, and I really don't want to lose track of important projects / don't want people wasting time going down fruitless paths / duplicating each others' efforts.

If it turns out that IRC isn't workable for us as a group, or if it turns out that #npm isn't workable for the volume of discussion we'd like to have (especially because I'd like to include some GitHub integrations so that people get some idea of what's happening in terms of changes to the code), I'm open to discussing alternatives. We discussed both Slack and Gitter, but they're missing a lot of the tools that we want to help make a productive and safe space for collaborative discussion.

Questions? Concerns? Here's a good place to discuss them. Or find us on #npm and we can discuss them there!

**Comment by smikes** [comment]
:+1:

**Comment by faiq** [comment]
>We discussed both Slack and Gitter, but they're missing a lot of the tools that we want to help make a productive and safe space for collaborative discussion.

What's wrong with an npm-cli slack or Gitter? The only reason i'd be opposed to IRC is because people use it as a helping resource, which is cool but might be distracting for those trying to receive help and people trying to talk about the CLI.

With that being said, i've  been kind of slacking in my issue triaging/involvement with npm because I've been trying to work and pass my classes (i really hope i do that), so a lot of real time communication would just go over my head. Maybe I want that? Maybe I don't? That's still something to consider though. 

I've never used Gitter, but it might be the tool for the job just by looking at it for a few minutes.

I would like to use IRC, considering its an open protocol for everyone so that's kind of dope. Maybe we could do another IRC channel?

things to consider.

**Comment by smikes** [comment]
>There's a lot going on, and I really don't want to lose track of important projects / don't want people wasting time going down fruitless paths / duplicating each others' efforts.

>a productive and safe space for collaborative discussion.

These goals are important to me.  My concern with public IRC is that it may not feel enough like a safe space for frank discussions.  Specifically, that **I** might feel safe there but others may not feel it's safe enough to call me out/criticize me.  I am happy to give it a try, though.

**Comment by othiym23** [comment]
> What's wrong with an npm-cli slack

It doesn't make any sense to split just the CLI team off the npm, Inc. slack. We could potentially open up the #cli channel to outside collaborators, but it has some of the same issues with moderation controls that Gitter has (see below), and it is not designed for open collaboration the way IRC is (this is from discussions with Slack developers). Also, in the case of an open channel, that's another thing that people have to watch to get their questions answered.

Slack is a fantastic tool that I love and depend upon, but it's a poor tool for this purpose.

> or Gitter?

No moderation controls at all, as far as I can tell. I have direct experience with how hard to handle this can be in practice.

> My concern with public IRC is that it may not feel enough like a safe space for frank discussions.

The channel has a CoC and people who are ready to enforce it. I hear what you're saying about people and their comfort levels, but I think that's a problem that exists independently of the medium. My feeling is that if we conduct ourselves like grownups with a modicum of empathy, that's about the best we can do.

None of the alternatives were great solutions to the team communication problem. I think the best way to look at it is another experiment we can try to see if we can improve things, and if it doesn't work, we'll try something else.

**Comment by iarna** [comment]
I've been using IRCCloud (https://www.irccloud.com/) and it's reasonably nice. Provides many of the affordances that Slack does. With a paid account, it leaves you in channel all the time, so you get full history too. It's not as *nice* as Slack, but they are actively working on it.
