### ISSUE TITLE
I cannot change password, when I reset password.

### ISSUE THREAD

**Issue by prugel** [npm/npm#7438]
https://www.npmjs.com/password

login ok, but When I click change password button, 

display below code.

```
{
statusCode: 400,
error: "Bad Request",
message: "/password"
}
```

**Comment by KenanY** [comment]
@prugel Issues with npmjs.com should be reported to the [newww](https://github.com/npm/newww) repository.

**Comment by othiym23** [comment]
Yes, this is an issue with the web site, not the CLI, so scoot on over there and file an issue, or send an email to <support@npmjs.com>.
