### ISSUE TITLE
Error with npm install npm ERR! Invalid version: "1.0"

### ISSUE THREAD

**Issue by radjivC** [npm/npm#7445]
Hi, when I try to use npm install for any module, I receive an error and I can't install a new module. I try to reinstall node, nothing change.
you can find my log on this gist https://gist.github.com/radjivC/716f68fa9e53186726ac

![capture d ecran 2015-02-24 a 16 28 03](https://cloud.githubusercontent.com/assets/5714138/6352339/2a7fe1e4-bc42-11e4-9f21-3db34c958896.png)

Thank you for your help.

**Comment by KenanY** [comment]
Does `/Users/radjiv/Documents/workspace/createUser/package.json` exist? If so, is its `"version"` field set to `"1.0"`?

**Comment by radjivC** [comment]
Yes, here my package.json file 
```
{ "name": "myfile",
  "description": "myfile",
  "version": "1.0",
  "devDependencies": {
    "coffee-script": "~1.6.3",
    "sys":"0.0.1",
    "readline": "0.0.5",
    "jsonfile": "2.0.0",
    "fs":"0.0.2",
    "diatric": "1.2.1",
    "change-case": "2.1.5"
  },
  "main": "myfile.js"
}
```

**Comment by KenanY** [comment]
`"1.0"` is not a valid version as defined by [Semantic Versioning](http://semver.org/). Changing it to `"1.0.0"` should solve your issue.

**Comment by KenanY** [comment]
Relevant documentation: https://docs.npmjs.com/files/package.json#version

> Version must be parseable by [node-semver](https://github.com/npm/node-semver)

``` bash
$ npm install -g semver
$ semver 1.0
$ echo $?
1
```

(`1` is the exit code for failure)

**Comment by radjivC** [comment]
Yes, issue solved, thank you :dancer:

**Comment by mustafadefcon** [comment]
Thanks it work for me also

**Comment by kalkehcoisa** [comment]
Yeah! Solved the problem here too.
Wouldn't it be better error message if it were added something like a list of the acceptable version patterns?
We lost some time here on this. Having the patterns explicit in the message would have been really helpful and easier to check the problem.
