### ISSUE TITLE
npm installation issues http://www.multiurl.com/la/nodejs11

### ISSUE THREAD

**Issue by biebergagabcbs** [npm/npm#7446]

**Comment by smikes** [comment]
Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install.  Can you make sure you are running the latest version of npm?

To find out what version you're running, do `npm --version`.

To update npm, run `npm -g install npm@latest`

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

For some Linux distributions (Debian/Ubuntu and RedHat/CentOS), the latest node version provided by the distribution may lag behind the stable version. [Here are instructions from NodeSource](https://github.com/nodesource/distributions) on getting the latest node.

Thanks!

**Comment by othiym23** [comment]
Whoa. No. This is not an acceptable way to request support.

Like Sam said, open an issue, preferably with a stacktrace copied and pasted or an `npm-debug.log` attached as a gist.
