### ISSUE TITLE
Some error with yeoman while generating angular project.

### ISSUE THREAD

**Issue by thigrand** [npm/npm#7448]
```
jquery#2.1.3 bower_components\jquery
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "node" "C:\\Users\\Tomasz\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.6.0

npm ERR! null == true
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>
```

**Comment by KenanY** [comment]
@thigrand https://github.com/npm/npm/issues/7332#issuecomment-75364593

**Comment by othiym23** [comment]
Closing in favor of #7332. I would really like to figure out what's causing this, because it appears to be affecting a decent number of people, but I haven't seen in myself, and as you can see, the error message isn't particularly helpful in identifying which bit of Node or npm is blowing up.
