### ISSUE TITLE
`npm install git+https://... --save` puts wrong path into package.json

### ISSUE THREAD

**Issue by RReverser** [npm/npm#7450]
I use `npm install git+https://... --save` when needing to temporarily link to particular commit / branch with fix until it's merged and published.

But now, trying with latest Node.js 0.12 / IO.js 1.3.0 and NPM 2.6.0, in `package.json` instead of given URL I get the following:

```json
"dependencies": {
  "gitter-realtime-client": "file:..\\..\\Users\\Ingvar\\AppData\\Local\\Temp\\npm-928-e538f833\\git-cache-1b2a4fde4499\\ff98072fe11137a83a5cbbcec3051a713facf6ab"
}
```

**Comment by KenanY** [comment]
Yeah, this is a known issue https://github.com/npm/npm/issues/7121

**Comment by RReverser** [comment]
Ah, didn't find it :/ Thanks.
