### ISSUE TITLE
npm install fails if local modules are present in npm-shrinkwrap.json

### ISSUE THREAD

**Issue by yoshuawuyts** [npm/npm#7451]
Local modules + shrinkwrap aren't playing together nicely. `npm@3.0` will probably fix this so mostly posting this in here for reference purposes.

```
❯ npm i
npm WARN excluding symbolic link test/app.js -> ../example/server.js
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/Users/yoshuawuyts/.nvm/v0.10.35/bin/npm" "i"
npm ERR! node v0.10.35
npm ERR! npm  v2.6.0
npm ERR! code E404

npm ERR! 404 Not Found: @local%2fgravatar-tools
npm ERR! 404
npm ERR! 404 '@local%2fgravatar-tools' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'wercker'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/yoshuawuyts/dev/wercker/wercker/src/npm-debug.log
```

cc @iarna

**Comment by iarna** [comment]
Can you include your package.json and npm-shrinkwrap.json ? Or the steps you took to get it into the place that you're getting this error?

**Comment by iarna** [comment]
Example of this failing: https://github.com/yoshuawuyts/finfin

**Comment by iarna** [comment]
The problem seems to be that the generated shrinkwrap in this case doesn't have a "resolved" field pointing at the local directory, it only has a version, as such, installing from the shrinkwrap tries to fetch from the registry, which of course fails.

**Comment by iarna** [comment]
And THAT is due to the fact that the assumption `npm shrinkwrap` makes about links is that they're registry hosted modules that you have a local copy of that you're working on, so it just stores a version and nothing else.

**Comment by jmm** [comment]
I seem to be running into the same / similar issue, with npm 2.1.4. I'm trying to test some stuff locally and running `npm shrinkwrap` in a directory that has a `package.json` with a dependency pointing to an absolute local path. When I copy `npm-shrinkwrap.json` to a different directory and `npm install` I get the same kind of error:

```
npm ERR! 404 Not Found: whatever
npm ERR! 404
npm ERR! 404 'whatever' is not in the npm registry.
```

`npm-shrinkwrap.json` has a `from` property for this package with the relative path from where I ran `npm shrinkwrap` to the package. Adding a `resolved` property with the absolute local path got it to install.

**Comment by gaye** [comment]
This is muy importante

**Comment by wesleytodd** [comment]
Hey @iarna!  I am running into this issue, so made a reduced test case.  https://github.com/wesleytodd/npm-2-shrinkwrap-test

It would be really nice to get this working, because we cannot upgrade to `npm@3` because we have a large app which relies on some of the behaviors of `npm@2`.  We are working on updating but it might be a while and we are vulnerable to malicious releases until we can use shrinkwrap.  Thanks and hope the test case works and helps show the issue!

**Comment by marcbachmann** [comment]
I've just tested that in npm v3 again and it looks like it got fixed. Thanks.

It's still broken in npm v2. But I guess only when dependency requires another local dependency.
The paths in the shrinkwrap are set up using a relative path based on the cwd. But the modules get installed relative to the dependency itself. Therefore it can't find the module.

here's the setup to reproduce it:
```bash
mkdir npm-shrinkwrap-test && cd npm-shrinkwrap-test
mkdir -p mod1 mod2 subdir/mod3
cd mod1 && npm init -y && ../
cd mod2 && npm init -y && npm install --save file:../mod1 && cd ../
cd subdir/mod3 && npm init -y && npm install --save file:../../mod2
npm shrinkwrap
rm -Rf node_modules && npm install
```

**Comment by spiffytech** [comment]
This appears broken for me with npm v3, but shrinkwrap in npm v4 correctly generates a `resolved` property pointing to the local folder.

**Comment by legodude17** [comment]
@spiffytech Then use npm@4. 😄 

Anyone still have this issue with npm@4?

**Comment by mikemaccana** [comment]
@legodude17 Confirmed, installing npm v4 and using that to generate the shrinkwrap file fixed the error for me.

**Comment by legodude17** [comment]
@yoshuawuyts @jmm Do either of you still have this after updating `npm`?

**Comment by yoshuawuyts** [comment]
@legodude17 no clue, this issue is from 2 years ago - I've stopped using both shrinkwrap and local modules so feel free to close

**Comment by legodude17** [comment]
@yoshuawuyts Cool. Can you close this @KenanY?

**Comment by marcbachmann** [comment]
> Can you close this

Maybe also that one: https://github.com/npm/npm/issues/8953

**Comment by mikemaccana** [comment]
Can confirmed this has worked for, like, ages.
