### ISSUE TITLE
Cygwin: Installation of git dependency fails to clone

### ISSUE THREAD

**Issue by silverwind** [npm/npm#7456]
I know this is an unsupported platform, but npm works reasonably well when aliased as `cmd /c npm`. Now, I seem tha have hit an unrecoverable issue that looks to be because of incorrect path joining of the git clone path.

Here's the relevant parts of `npm install video.js --loglevel=silly`:

https://gist.github.com/silverwind/e7f034e16ba8fb647abe

The wrong path in that log is:
````
/cygdrive/c/Users/silverwind/AppData/Roaming/npm-cache/_git-remotes/
https-github-com-gkatsev-vtt-js-git-9a867bb9/C:\Users\silverwind\AppData\Roaming\npm-cache\
_git-remotes\https-github-com-gkatsev-vtt-js-git-9a867bb9' does not appear to be a git repository
````

This is on Cygwin's latest git, `2.1.4`, same result happens when I run npm from `cmd` instead of `zsh`.

Related: https://github.com/videojs/video.js/issues/1895

**Comment by smikes** [comment]
I'm sorry.  As a cygwin user myself, I sympathize, but we just don't have the resources to support anything other than bog-standard Windows.

**Comment by othiym23** [comment]
As far as I know, this is an example of Git's long path support for Windows doing something unexpected under Cygwin. That path isn't being generated by npm. These kinds of lingering self-inconsistencies between Cygwin and the tools it bundles is a big chunk of why npm doesn't support Cygwin in the first place. I know npm's hardline stance on Cygwin is a major pain point for Cygwin users, and I sympathize, but it's difficult already to support both Unix and Windows ways of doing things; if we start adding explicit support for sub-environments like Cygwin, it's going to be a huge additional burden to get everything right, especially given that the number of Cygwin users is so much smaller than for the platforms npm supports. Sorry!

**Comment by silverwind** [comment]
@othiym23 quick question regarding this output of `--loglevel=silly`:

````
npm info git [ 'clone',
npm info git 'path1',
npm info git 'path2' ]
````

does that mean `git clone` was invoked with two paths seperated by a space?

**Comment by othiym23** [comment]
[Yes](https://github.com/npm/npm/blob/master/lib/utils/git.js#L20-L33). Those are the only two places that log message can come from.

**Comment by bobfields** [comment]
I can confirm that this command fails "does not appear to be a git repository" when using the current git bundled with Cygwin (2.4.5) 64 bit. When I separately download and install the Windows git distribution (2.6.2.windows.1), and put the GIT_HOME in front of the CYGWIN_HOME in the PATH, the npm install (including the git clone) succeeds. I installed with the mintty option so that git works properly with docker also.

**Comment by RichardBradley** [comment]
Is there any workaround other than installing Windows git?

**Comment by bsclifton** [comment]
ugh, just ran into this issue myself :( I guess the good news is, Bash via Ubuntu will be available with Windows 10 this summer

**Comment by demisx** [comment]
Sucks. Got hit with this error just now myself and stuck.

**Comment by bsclifton** [comment]
This sounds like a duplicate of https://github.com/npm/npm/issues/7357

There was a PR submitted with a fix (https://github.com/npm/npm/pull/12366), if you wanted to manually apply the fix or comment

**Comment by emigenix** [comment]
Working Cygwin instructions [here](https://github.com/emigenix/npm_on_cygwin).
