### ISSUE TITLE
Newly published package already had tags?????

### ISSUE THREAD

**Issue by treshugart** [npm/npm#7459]
Hey guys,

I recently did a `npm info mac` to see if a package was taken. It wasn't, much to my surprise considering the name. So I decided to publish under that name. When I tried to publish my next version after my initial version, I was met with an unexpected message:

![screen shot 2015-02-26 at 12 31 34 pm](https://cloud.githubusercontent.com/assets/136556/6384640/6fd1bbba-bdb3-11e4-9957-a541ff9852d1.png)

No way! My package went back in time without me knowing and released its next version! Wait...

![screen shot 2015-02-26 at 12 22 30 pm](https://cloud.githubusercontent.com/assets/136556/6384648/89a82a38-bdb3-11e4-83e3-02032d7b826f.png)

Not only that but it did many versions! Some within a few minutes of each other o_O.

I'm sure you can imagine my confusion. I could be wrong and maybe it was me who previously had  a package by the same name, or maybe someone else did. You'd think `npm info` would return some information about that. I surely don't remember doing that, though. What's up?

**Comment by othiym23** [comment]
The messaging around this should be clearer, but what I think happened here was that there was once a `mac` package, and it got unpublished. From the looks of things, that was around version `0.1.0`, back in 2012. Much, **much** has changed with the registry in the intervening three years, so some of the helpful metadata that would be there had it been unpublished now is missing. In any case, you should be able to publish `mac@0.2.0` (or  something other version that wasn't previously published to the registry) without issue, and if that doesn't work, then you should send an email to <support@npmjs.com> so the registry team can figure out what to do about it.

**Comment by treshugart** [comment]
Nah, I just ended up using `0.2.0`. Thanks for the quick response and all the best!
