### ISSUE TITLE
npm install -g node-gyp fails

### ISSUE THREAD

**Issue by alexkarman** [npm/npm#7460]
Hi,

I am trying to install node-gyp because it is a prerequisite for johnny-five. 

The instruction
npm install -g node-gyp

fails with the message:

GET https://registry.npmjs.org/minimatch/-/minimatch-1.0.0.tgz
Error: No compatible version found: mkdirp@'^0.5.0'

My Mac: OSX 10.9.5

Any suggestions? Any help would be appreciated.

Thanks,
--Alex

**Comment by KenanY** [comment]
@alexkarman 

```
Error: No compatible version found: mkdirp@'^0.5.0'
```

This is usually a sign of an outdated installation of `npm`. Can you try [updating](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-nix-osx-linux-etc)?

**Comment by othiym23** [comment]
Yes, what @KenanY said. You need `npm@1.4` or newer to use the `^` semver operator, and you might as well upgrade to Node 0.12.0 or io.js while you're at it, because your installation is at least a year old if you have an npm so old that it doesn't understand `^`.

**Comment by alexkarman** [comment]
Thank you for the suggestion. npm updated OK, but npm install -g node-gyp
still fails with the same message.

**Comment by KenanY** [comment]
@alexkarman What does `npm --version` print out now? Could you upload a log as a [gist](https://gist.github.com/)?

**Comment by alexkarman** [comment]
npm --version

1.2.18


Attached are both the update log and the install log.

**Comment by KenanY** [comment]
@alexkarman Looks like your `npm` was not updated; `1.2.18` is two years old. Attaching logs in GitHub-email-replies doesn't work; it seems. Try uploading them as a [gist](https://gist.github.com/) and posting a link to the gist here.

**Comment by alexkarman** [comment]
Thanks, I used "brew upgrade node" then used npm to install gyp and it
worked.
