### ISSUE TITLE
Improvements in displaying npm run-script list

### ISSUE THREAD

**Issue by watilde** [npm/npm#7463]
This is a feature request to improvement in displaying npm run-script list. Currently display npm scripts list example:
```
Available scripts in the npm package:
  bar
    node bar.js
  foo
    node foo.js
  start
    node server.js
  test
    node test.js
```

I’d like to split them in scripts or run-scripts:
```
Available scripts that's in the npm package:
  start
    node server.js
  test
    node test.js

with run-script:
  bar
    node bar.js
  foo
    node foo.js
```

Thanks.

**Comment by othiym23** [comment]
This seems like a simple and useful usability improvement. Would you like to take a swing at assembling a pull request, @watilde? I don't think the npm core team will have time to get to this anytime soon.

**Comment by watilde** [comment]
I see, thanks for your comment @othiym23 ! I really would like to create a pull reqeust so I'll do that soon:)

**Comment by othiym23** [comment]
Closing in favor of #7464. Looking good!
