### ISSUE TITLE
Is this behavior correct when run npm restart?

### ISSUE THREAD

**Issue by watilde** [npm/npm#7470]
Hi. Please let me ask a question that is it correct behavior when run npm restart?

---
In this document: https://docs.npmjs.com/misc/scripts
> prerestart, restart, postrestart: Run by the npm restart command. Note: npm restart will run the stop and start scripts if no restart script is provided.

So I expected:
When there is `restart` in scripts

1. prerestart
2. restart
3. postrestart

When there isn't `restart` in scripts

(0. prerestart) // either is ok
1. prestop
2. stop
3. poststop
4. prestart
5. start
6. poststart
(7. postrestart) // either is ok

However, actual behavior looks such a following if there is `restart` in scripts or not:

1. prerestart
2. prestop
3. stop
4. poststop
5. restart
6. prestart
7. start
8. poststart
9. postrestart

And refs this commit: https://github.com/npm/npm/commit/2f87c6e84ddc01477f6b5b57800ef64b790d04c2

thanks.

**Comment by othiym23** [comment]
Closing in favor of #7471, and also because this has been fixed and landed as 2f6a1df3e1e3e0a3bc4abb69e40f59a64204e7aa. Thanks!
