### ISSUE TITLE
document `--node-gyp=` option

### ISSUE THREAD

**Issue by othiym23** [npm/npm#7479]
Follow-on for #4887, which supports overriding the `node-gyp` binary, which could be useful for users experimenting with `pangyp` or using unpatched npm with io.js.

**Comment by ackalker** [comment]
Thanks :-)

**Comment by othiym23** [comment]
:cry: still not documented. This has been moved to the [npm roadmap](https://github.com/npm/npm/wiki/Roadmap), which we're using instead of the confusing `next-*` labels now.
