### ISSUE TITLE
npm ERR! missing script : stop

### ISSUE THREAD

**Issue by Kahfimaulana** [npm/npm#7481]
Hey, I try to stop my application with npm stop, but I got this error message:
"npm ERR! missing script : stop"

Someone could help solved this issue?

**Comment by smikes** [comment]
`npm stop` just tells `npm` to run the stop script.  You need to tell npm how to stop your application and add that to the `scripts` in the `package.json` file in your package directory.

**Comment by Kahfimaulana** [comment]
Hey thanks for the answer :+1: it worked !!

**Comment by gaowenhui** [comment]
good
