### ISSUE TITLE
npm list command fails 

### ISSUE THREAD

**Issue by HintikkaKimmo** [npm/npm#7482]
npm list command fails to execute with error below. 
```
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "info"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1

npm ERR! Invalid package.json
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kimmo/npm-debug.log
```
And npm-debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'info' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose config Skipping project config: /Users/kimmo/.npmrc. (matches userconfig)
5 verbose stack Error: Invalid package.json
5 verbose stack     at /usr/local/lib/node_modules/npm/lib/view.js:79:30
5 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:51:40
5 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:97:49
5 verbose stack     at evalmachine.<anonymous>:265:20
5 verbose stack     at OpenReq.Req.done (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:141:5)
5 verbose stack     at OpenReq.done (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:61:22)
5 verbose stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:99:15)
6 verbose cwd /Users/kimmo
7 error Darwin 13.4.0
8 error argv "node" "/usr/local/bin/npm" "info"
9 error node v0.12.0
10 error npm  v2.5.1
11 error Invalid package.json
12 error If you need help, you may report this error at:
12 error     <http://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]
```

**Comment by othiym23** [comment]
Is there a `package.json` file in `/Users/kimmo`? If so, what's in it? What are you expecting from running `npm info` with no arguments?

**Comment by smikes** [comment]
@HintikkaKimmo , most `npm` subcommands presume that you are in a module directory, and so expect there to be a populated `package.json` file in the current directory.

The exception is when commands are applied globally, such as 

```
npm ls -g
```

Which will show you all the modules that are installed to the global prefix directory.

If you can tell me more about what you're trying to achieve, I may be able to provide more specific answers.

Tervetuloa npm-maahan!

**Comment by HintikkaKimmo** [comment]
Hi,

Thanks for the help. 

I have realised what this was and it is not npm error I had error in my npm path in bash_profile had things left from my old install and whole npm folder was pointing to wrong place...

**Comment by joshlewis** [comment]
It would be best if instead of showing that error, it would give a reason as to why it is failing. For instance, "This command must be run from within the `node_modules` directory. Or some such thing. Much more helpful.
