### ISSUE TITLE
npm install pdfkit: No compatible version found: unicode-trie@'^0.1.1'

### ISSUE THREAD

**Issue by bozana** [npm/npm#7485]
Hello,

I would like to istall pdfkit, but am not able to -- I get this message:
# npm install pdfkit
npm http GET https://registry.npmjs.org/pdfkit
npm http 304 https://registry.npmjs.org/pdfkit
npm http GET https://registry.npmjs.org/linebreak
npm http 304 https://registry.npmjs.org/linebreak
npm http GET https://registry.npmjs.org/unicode-trie
npm http 304 https://registry.npmjs.org/unicode-trie
npm ERR! Error: No compatible version found: unicode-trie@'^0.1.1'
npm ERR! Valid install targets:
npm ERR! ["0.1.0","0.1.1","0.1.2","0.2.0","0.3.0"]
npm ERR!     at installTargetsError (/usr/lib64/node_modules/npm/lib/cache.js:685:10)
npm ERR!     at /usr/lib64/node_modules/npm/lib/cache.js:607:10
npm ERR!     at saved (/usr/lib64/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.11.10-17-default
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "pdfkit"
npm ERR! cwd ...
npm ERR! node -v v0.10.5
npm ERR! npm -v 1.2.18
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!    .../npm-debug.log
npm ERR! not ok code 0

Could anyone please help me and tell me how to solve this?
Thansk a lot!
Bozana

**Comment by othiym23** [comment]
You will need to upgrade to a newer version of npm (`npm@1.4` or greater, although `npm@2.5` or greater is what we prefer), and should probably upgrade to a newer version of Node as well. It looks like you're using versions of Node and npm packaged especially for your OS distribution, so you might find [these instructions](https://github.com/nodesource/distributions) helpful. Good luck!
