### ISSUE TITLE
yo keynote error to install

### ISSUE THREAD

**Issue by rubengarcia0510** [npm/npm#7491]
create public\styles\site\variables.less
npm ERR! Error: Invalid protocol: http.internetpsa.inetpsa.com:
npm ERR!     at Request.self._buildRequest (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\request.js:460:53)
npm ERR!     at Request.init (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\request.js:637:10)
npm ERR!     at new Request (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\request.js:131:8)
npm ERR!     at request (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\index.js:47:10)
npm ERR!     at RegClient.makeRequest (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:224
:13)
npm ERR!     at RegClient.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:132
:17)
npm ERR!     at null._onTimeout (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\retry\lib\retry_operation.js:32:10)
npm ERR!     at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "ins
tall"
npm ERR! cwd C:\ATOS\node\cms\tienda
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\ATOS\node\cms\tienda\npm-debug.log
npm ERR! not ok code 0

**Comment by KenanY** [comment]
@rubengarcia0510 Is this still an issue for you?

**Comment by KenanY** [comment]
Closing as abandoned.
