### ISSUE TITLE
Incorrect warning about engineStrict

### ISSUE THREAD

**Issue by mzgol** [npm/npm#7492]
```
$ npm --version
2.7.0
$ node --version
v1.4.1
$ npm -g i npm-bump                                                                   
npm WARN engineStrict Per-package engineStrict (found in package.json for npm-bump)
npm WARN engineStrict won't be used in npm 3+. Use the config setting `engine-strict` instead.
/Users/mgol/.nvm/versions/io.js/v1.4.1/bin/npm-bump -> /Users/mgol/.nvm/versions/io.js/v1.4.1/lib/node_modules/npm-bump/bin/npm-bump
npm-bump@0.0.13 /Users/mgol/.nvm/versions/io.js/v1.4.1/lib/node_modules/npm-bump
├── semver@4.3.1
├── shell-quote@1.4.2 (array-filter@0.0.1, array-map@0.0.0, array-reduce@0.0.0, jsonify@0.0.0)
└── inquirer@0.8.0 (figures@1.3.5, ansi-regex@1.1.1, mute-stream@0.0.4, through@2.3.6, readline2@0.1.1, chalk@0.5.1, lodash@2.4.1, cli-color@0.3.2, rx@2.4.1)
```

The problem is there's no `engineStrict` in npm-bump's package.json. ;) It *used to* be there but I removed it. I've checked after the installation:
```
$ cat ~/.nvm/versions/io.js/v1.4.1/lib/node_modules/npm-bump/package.json | grep engine
  "engines": {
```

**Comment by smikes** [comment]
That's a really cool bug.

**Comment by othiym23** [comment]
This was a surprisingly tricky bug to address, but I ultimately realized that this warning, like many others, is really only useful to package maintainers. That means you only care about `engineStrict` in the current top-level `package.json`, so I added a post-install validation check for exactly that. Landed as b6bd99a73f575545fbbaef95c12237c47dd32561. Thanks for filing this, @mzgol!

**Comment by aa6my** [comment]
my error output like this. how to fix it?

npm WARN engineStrict Per-package engineStrict (found in package.json for cordova)
npm WARN engineStrict won't be used in npm 3+. Use the config setting `engine-strict` instead.
npm WARN engine npm@1.3.4: wanted: {"node":">=0.6","npm":"1"} (current: {"node":"0.12.0","npm":"2.7.0"})
npm WARN engine cordova-js@3.8.0: wanted: {"node":"~0.10.x"} (current: {"node":"0.12.0","npm":"2.7.0"})
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"0.12.0","npm":"2.7.0"})

**Comment by KenanY** [comment]
@mzgol I don't see an error in the log you've posted. I just see a few warnings, which in many cases can usually be ignored without consequences.

**Comment by othiym23** [comment]
Plus I tweaked that behavior some more in `npm@2.7.1` to only warn for the current package, not child dependencies. So when you upgrade again after 2.7.1 is out of testing, you'll stop getting the `engineStrict` warning.
