### ISSUE TITLE
Why is stuff getting compiled every time?

### ISSUE THREAD

**Issue by binarykitchen** [npm/npm#7493]
Whenever I have installed for example ws and run a `npm i` afterwards for whatever reason, ws is re-compiled again. Why? There is no need to compile it when the version matches:

```
$ npm i
... 
> ws@0.6.5 install /var/www/videomail/staging/source/node_modules/websocket-stream/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/var/www/videomail/staging/source/node_modules/websocket-stream/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory `/var/www/videomail/staging/source/node_modules/websocket-stream/node_modules/ws/build'
```

Is there a workaround for that for better performance? Because I am running `npm i` when deploying things on the server.

(this has been initially posted on https://github.com/websockets/ws/issues/461)

**Comment by smikes** [comment]
I cannot reproduce this behavior on OSX with `npm@2.6.1`.  This may be operating-system specific; can you tell me what OS, version of `node`, and version of `npm` you are using?

**Comment by binarykitchen** [comment]
Well, the Ubuntu 14.10 server has npm version 1.4.28 and node version 0.10.36

**Comment by smikes** [comment]
`npm@1.4.28` is quite an old version, with several known race conditions around install.  Can you try upgrading to the latest?

```
sudo npm i -g npm@latest
```

**Comment by binarykitchen** [comment]
Right, it's old I know. But I rather not to update npm for now. For two reasons: 1. `apt-get install nodejs` still delivers the old node.js and npm versions and 2. the new npm version is breaking few things on the server side.

**Comment by smikes** [comment]
Even with `npm@1.4.28` (running in a docker instance), I am unable to reproduce the problem -- `ws` does not get compiled every time for me.  Here's the script I'm using -- can you see if this gives you similar results?

```
mkdir t && cd t
echo {} > package.json
npm i -S ws@0.6.5
# build happens
npm i 
# build does not happen
```

Can you please upload your `package.json` as a gist?

**Comment by binarykitchen** [comment]
Thanks! Here's my package.json as a gist
https://gist.github.com/binarykitchen/683a22efb6f5081b3946

**Comment by binarykitchen** [comment]
Probably that prefix should be included as well for exact reproduction:

```
$ cat .npmrc
prefix=/home/michael-heuberger/npm
```

I am doing that to avoid installs asking me for sudo rights.

**Comment by smikes** [comment]
Okay, I think I found the culprit, and I may even have a workaround for you.

When I run `npm install ws` using the dependencies you supplied, I see this in the `npm` log output:

```
npm info installOne ws@0.7.1
npm verb node_modules/ws unbuild
npm info preuninstall ws@0.7.1
npm info uninstall ws@0.7.1
npm verb true,/root/t/node_modules,/root/t/node_modules unbuild ws@0.7.1
```

So for whatever reason, `npm` is deciding to unbuild the satisfying 0.7.1 and reinstall it.

You can avoid this behavior by using the `npm update` command with depth 0 (this works even on old `npm`):

```
$ rm -rf node_modules/ws
$ npm update --depth 0 ws

> utf-8-validate@1.0.1 install /root/t/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

make: Entering directory `/root/t/node_modules/ws/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory `/root/t/node_modules/ws/node_modules/utf-8-validate/build'

> bufferutil@1.0.1 install /root/t/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

make: Entering directory `/root/t/node_modules/ws/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
make: Leaving directory `/root/t/node_modules/ws/node_modules/bufferutil/build'
ws@0.7.1 node_modules/ws
├── options@0.0.6
├── ultron@1.0.1
├── utf-8-validate@1.0.1 (bindings@1.2.1, nan@1.6.2)
└── bufferutil@1.0.1 (bindings@1.2.1, nan@1.6.2)
$ npm update --depth 0 ws
$
```

Note that nothing happens the second time I run `npm update --depth 0 ws`, because `ws` is present and up-to-date.

**Comment by iarna** [comment]
@smikes If you type in `npm install MODULENAME` it will always reinstall MODULENAME. This isn't the same as if you type in `npmm install`, where it should only install missing dependencies.

**Comment by iarna** [comment]
(An aside: @binarykitchen If you're having problems in 2.x that you didn't in 1.x, we'd really like to know what they are!)

**Comment by iarna** [comment]
FWIW, I can't reproduced it with npm@2.6.1. (I did have to remove `sharp` from the deps list as I'm missing C libraries it needs.) I'm switching to npm@1.4.28, buut, I'm in a hotel and their wifi has suddenly started hating me… =p

**Comment by iarna** [comment]
```
🕘  rebecca@Caldina:~/code/npmtest$ node -v
v0.10.36
🕘  rebecca@Caldina:~/code/npmtest$ npm -v
1.4.28
```
I can't reproduced this: `npm i` doesn't reinstall `ws` or anything else.

**Comment by smikes** [comment]
I will leave this in your hands, Rebecca, since I feel a bit out of my depth.  Thanks!

**Comment by iarna** [comment]
@binarykitchen Could you run `npm i --loglevel=silly 2>> npm.log` twice and post the log somewhere (a gist maybe?) I think I'm going to need that level of detail to figure out what's going on.

**Comment by binarykitchen** [comment]
@smikes thanks for that but I do not want to run `npm update` because it does not install new modules that were recently added to the package.json. Or am I wrong, does `npm update` also install missing packages?

**Comment by binarykitchen** [comment]
@smikes also do not test this with the latest ws package. It only happens when using `websocket-stream` which includes an older `ws`.

**Comment by binarykitchen** [comment]
@iarna Grrrr ... somehow I am unable to reproduce this today. Something must have changed after my recent `npm update`. Weird. I'll keep an eye on this and will add more comments once I am able to reproduce this behavior.

**Comment by derduher** [comment]
@iarna @binarykitchen I think I've encountered the same problem with my [fork](https://github.com/derduher/nsutil/blob/0.1.5/package.json) of the nsutil package. I did notice a successful scenario though. When I provide a commit hash as opposed to a tag or no "commit-ish" at all, the addon does not recompile. I have provided logs of each scenario as well as my versions below.

npm `2.10.1`
node `v0.12.4`

### links to `npm i --loglevel=silly 2>> npm.log` run twice for each scenario
1. commit hash - no rebuild [log for git://github.com/derduher/nsutil.git#9853529409926b6a33dc5eb52528f3aadd2a1a51](https://gist.github.com/derduher/84540961e7f70b7d2172#file-npm_commit)
1. tag - rebuilds [log for git://github.com/derduher/nsutil.git#0.1.5](https://gist.github.com/derduher/84540961e7f70b7d2172#file-npm_commit)
1. no commitish - rebuilds [log for git://github.com/derduher/nsutil.git](https://gist.github.com/derduher/84540961e7f70b7d2172#file-npm_commit)

**Comment by majimboo** [comment]
I'm having the same problem. Installed latest stable node. Every time I install a new package it also recompiles a previously installed package `mariasql`.

**Comment by marckris** [comment]
Same problem as @majimboo 
NPM 3.8.9 + Node 6.0.0
Everytime I install something, mariasql is recompiled.
I wonder is it an NPM or mariasql issue?

**Comment by rkoberg** [comment]
Something is putting in "obj.target" build/Release/obj.target/somescript in the path, which looks like some variable is unescaped
![screen shot 2016-06-02 at 9 19 52 am](https://cloud.githubusercontent.com/assets/83722/15752493/38124e40-28a3-11e6-8f94-ab3553af7cf5.png)

**Comment by csilvers** [comment]
I am having the same problem, but with bufferutil.

npm 2.15.5
node v4.4.5
ubuntu 14.04.4

I've attached the output of two consecutive npm runs.

[nlog1.txt](https://github.com/npm/npm/files/312482/nlog1.txt)
[nlog2.txt](https://github.com/npm/npm/files/312483/nlog2.txt)

**Comment by cybercoder** [comment]
Me too, every npm install pkg will rebuild canvas with nodegyp which already installed!

**Comment by EduardJS** [comment]
Same stuff happens here, in case people still have this issue or somehow solved it. I have sharp library installed and it gets rebuild everytime with nodegyp

**Comment by bdharrington7** [comment]
npm@5.0.3 has the same behavior. I have `"better-sqlite3": "^2.3.3"` in my dependencies, but when I `npm install ip`, better-sqlite3 is rebuilt.
