### ISSUE TITLE
Counter-ideas to consider for future `peerDependencies` behavior

### ISSUE THREAD

**Issue by getify** [npm/npm#7495]
Regarding #6565, I wanted to, for the sake of posterity and perhaps future explorations, suggest a number of other ideas to consider (perhaps some have already been?) for how to preserve what some of us like about `peerDependencies` while addressing the things many people don't like about it.

I'll try to list them in order of my preference, and some of these could potentially be combined. but really this is just a brain dump:
1. Make `peerDependencies` installation an opt-out, like `--no-peers`. Evangelize that if you're having trouble with `npm install` or `npm update`, try `--no-peers` and see what it does. If you pass that flag, you get the warnings (but no errors and no installation).
2. Make `peerDependencies` installation an opt-in, like `--install-peers`. Let plugin ecosystems evangelize to use that flag if installations are incomplete or broken. Without the flag, you get warnings, with the flag, you get installations (and of course conflict errors).
3. Make `peerDependencies` versionless. That is, you cannot declare a peer-dependency on a specific version, only on the the presence of the named dependency. That may sound like anarchy, but I genuinely feel that could alleviate a lot of the pressure, and shift the burden back to the ecosystems to better coordinate peer dependencies and not have so many different mismatches.
4. A variation on the previous (which could be flag based, opt-in or opt-out) is that you could take the versions as merely annotations/suggestions, but not requirements, and issue warnings if there are versions different, but still either install the latest of something, or leave it at whatever's already installed (and report versions and mismatches in those annotations).
5. The first time any peer-dependency is installed, install it in the normal directory name as normal. If at a later time, there's a peer-dependency that tries to install as a different version, prompt (or use flags/configs/etc to control):
   - Do you want to update?
   - Warn on downgrade.
   - Install side-by-side -- this one would create the second copy of the peer-dependency in a directory with the version number baked into it, like "foo-vXXXX". In this option, either the user would have to require the peer dependency by name "foo-vXXXX", or `require(..)` could be taught to understand `require("foo@vXXXX")` syntax, and it would find the correct flattened directory name to require from.

I had a few others that are a little more far fetched and less thought out, so I'll just leave those out for now.

**Comment by othiym23** [comment]
You may want to go peruse #5080 and then come back and see how you feel about these ideas in light of that discussion. It's the thread that led to the changes in `peerDependency

**Comment by getify** [comment]
I think you're right that we'll just have to see how this goes. I have read parts of that long thread, but I'll try to make time to get back to it. For now, I'll see what complaints may come up with my packages, and I'll come back and filter that against this list.

I like #3 and/or #4 the best, TBH. So if it were purely up to me, that's how I'd start my proposal. But #1 and #2 are less intrusive, and that's why I thought they'd perhaps be more practical as a proposal starting point.

**Comment by jhnns** [comment]
Maybe it's useful to collect all the use-cases for peer dependencies. @othiym23 you'll probably heard a lot already, but for me (and probably others) it's hard to keep track of all the use-cases.

For example: I can't imagine a situation where installing peer dependencies automatically comes in handy. But that's just my point of view, maybe there are cases.

Here's my list:

## Singletons
When there should be only one instance (for whatever reason), a module can't declare that as a dependency. It requires the application's instance to be passed.

## Plugins
This is related to Singletons, but it's slightly different. Now we don't require the instance to be a singleton, but the existing instance should somehow be enhanced. Take [this module](https://github.com/peerigon/batch-replace) I've written for example: The basic functionality is to replace multiple patterns in a string at once. There are ready-to-use plugins that surround url-like patterns with `<a>` tags or that replace html characters with entities. This extra code should not be bundled and sent to the client (in case of browserify or webpack), if it's not actually required.

## "Glue" modules
When using browserify or webpack, there are so-called transformers or loaders. These modules enable the developer to compile custom languages like CS to JS, Less to CSS or Jade to HTML when the bundle is generated. In this situation, it's more practical if the application developer is able to specify the exact LESS, CS or Jade version in contrast to the transformer/loader author. Otherwise it would require the transformer/loader author to publish a new version each time the dependency publishes a new version. It's probably the same situations with grunt and gulp plugins.

**Comment by getify** [comment]
# Plugins

This is sort of related to "Singleton", but I think it may be inverse.

If you structure a main API (which I'll call "foo") with optional plugins (like "better.foo"), and the optional plugin packages are designed to "hot patch" (extend) the main API. The plugins do not in and of themselves provide any kind of useful API. When you `require(..)` them, you don't assign the output of that to anything you use, you just rely on the fact that they patched your main module instance.

As long as the main "foo" module is always referenced from the same canonical/resolved path location, it's a "singleton", and any plugins that load it up to patch/extend it will be extending the one main central instance of the API. For this reason, it's critical that the "foo" and "better.foo" are peers, and that "better.foo" does `require("../foo")` so that it's requiring the correct "foo".

The problem with just `require("foo")` is because it's impossible to prevent someone from accidentally/ignorantly installing "foo" inside of (as a dependency of) "better.foo" (perhaps in the process of trying to run tests or do dev with the plugin itself). As soon as they have it there, `require("foo")` in the plugin is referencing the nested "foo" instead of the peer "foo". This footgun has bitten me many times. `require("../foo")` seems to work reliably in that respect.

Now, why do we need *installation* instead of just warning? It's purely a convenience/guard. If you accidentally install only "better.foo", and forget to list "foo", you may not have even realized before that now npm isn't going to install that for you. You might have this process automated in some shell script on VM deploys, and a warning which doesn't fail the install is now going to "silently" fail until you try to spin up the app.

In other words, without you making any updates at all to the libs, but just upgrading node/io and getting a new npm, now your install of "better.foo" starts failing to get you "foo" like it always used to.

Or, you might not be the author of "foo" or "better.foo", but you author a package, let's call it "bar", and you choose to list only "better.foo" as one of its dependencies, and not explicitly list "foo" (for various reasons or mistakes). When someone later installs your "bar", they need both "foo" and "better.foo" as its dependencies, but now it's a foot gun for them that this "bar" didn't install correctly, and they may not even know or care what "foo" and "better.foo" are.

Again, all they did was get a new npm and now all of a sudden the good ol' stable reilable "bar" package stops installing correctly.

The installation here prevents these footguns. (Yes, I am well aware of how it creates others). Even if the installation could be an opt-in thing, like a `--install-peers` flag, it would help people to not have to understand relationships between "better.foo" and "foo" at such a deep level.

That is exponentially true the further down in the dependency tree "foo"/"better.foo" appear. If I'm installing "bam", which requires "baz", which requires "bar", which requires "foo" and "better.foo", and this has worked fine for years, and now npm fails (actually, just warns) 4 levels deep in install, I only use "bam" and I have no clue what "foo" and "better.foo" are, so my chances of knowing what to do with such a warning are low. I would be inclined to just retry with `--install-peers` or whatever, and if that worked, I'd smirk and move on.

------
When I said earlier this was the "inverse" of singleton, what I meant is that the plugin itself requires the main API so it can extend it, rather than the end consumer being forced to load both main API and plugin and do "dependency injection" to send the API instance into the plugin. I know many prefer that design, but it runs counter to how framework/plugin architecture was primarily designed for a dozen or more earlier years of the web. A lot of people, like myself, still prefer the simplicity of how `require(a); require(b); a.b()` just works.

**Comment by jhnns** [comment]
> When I said earlier this was the "inverse" of singleton, what I meant is that the plugin itself requires the main API so it can extend it, rather than the end consumer being forced to load both main API and plugin and do "dependency injection" to send the API instance into the plugin. I know many prefer that design, but it runs counter to how framework/plugin architecture was primarily designed for a dozen or more earlier years of the web. I still prefer the simplicity of how require(a); require(b); a.b(); just works.

I'd call that design an anti-pattern. It does things under the hood and doesn't allow the developer to control the time and order of execution. Sure, the developer knows: When I require this module, it will be executed. But in my experience, no actual code should be executed by just requiring a module because the order of module initialization is not always transparent to the user (e.g. `b.js` requires `plugin.js`, `a.js` requires `b.js` and initializes the plugin unwittingly).

Additionally it doesn't allow the developer to pass any configuration. And writing `require(a).use(require(b))` is still very simple :wink:

> In other words, without you making any updates at all to the libs, but just upgrading node/io and getting a new npm, now your install of "better.foo" starts failing to get you "foo" like it always used to.

It would be a major version upgrade, so that should be no surprise.

**Comment by getify** [comment]
> I'd call that design an anti-pattern.

I appreciate that many people feel that way. I disagree. I think it's a perfectly fine design pattern, and the one I prefer, and the one that's worked for a couple of years now just fine.

> Additionally it doesn't allow the developer to pass any configuration

My use case doesn't need that.

> It would be a major version upgrade, so that should be no surprise.

A major version upgrade of npm does not necessarily imply to someone that existing packages that have been installing fine will stop installing fine. Users who use a package don't always know the inner details of how that package (or its sub-sub-sub tree dependencies are arranged).

I consider it hostile to suggest that such an end user would have to somehow know that they are using a package that has, anywhere deep in its tree, a `peerDependency` package situation that is possibly going to be affected by an npm upgrade.

If I were that user, and I'd never even heard of `peerDependency` or why any package was using it, especially a package that's a sub-dependency and I've never even heard of it, I'd call that a "surprise" that npm changed to break it.

----

In any case, I'm not really trying to get into another impossibly-long thread debating use-cases or merits of features. I just started a thread to document some ideas of what I think could fix this conflict in feature behavior, and additionally responded by listing the primary use-case that motivates my position.

**Comment by jhnns** [comment]
> In any case, I'm not really trying to get into another impossibly-long thread debating use-cases or merits of features.

Ok :grin:

**Comment by getify** [comment]
Sorry for responding too curtly before. I've heard the arguments for why people don't like the think that I like, and I still don't agree. But I shouldn't let that annoyance at hearing yet again get the better of my tone and manner, though.

----------

What I should have said is this: my concerns here are the breaking change that npm introduces **if someone doesn't make any change to their code but just simply updates their tools (npm).** The suggestion you're making about changing how the code in such packages is structured and used only fixes the problem at hand if we assume that every package will update before npm3 comes out, and that every user will update to the new code at/before updating npm.

That moots the problem. In other words, it begs the question.

**Comment by jhnns** [comment]
> my concerns here are the breaking change that npm introduces if someone doesn't make any change to their code but just simply updates their tools (npm)

I don't get the point here. That's inevitable true for any major version upgrade of any software. If I install node 1.0.0 (someday), it might break code that was intended for node 0.x, if I install Windows 8, it might break software that was written for Windows 7.

Sure, something like npm should not introduce breaking changes every day. But with a reasonable amount of lead time, it is ok.

**Comment by zxqfox** [comment]
@jhnns I like your list with possible modules, but there will be others. Why not to left it to userland modules?

Also `Jade to HTML` is a bad example since you also need data to generate HTML. Jade is just a transformation layer while HTML is view-oriented data structure (prepared for browsers).
