### ISSUE TITLE
node-gyp rebuild fails

### ISSUE THREAD

**Issue by thmour** [npm/npm#7502]
I use node v0.12 and npm v2.5.1 on windows 8.1 and everytime I try to install a package that requires node-gyp rebuild, it fails and almost crashes my pc. The rebuild spawns hundreds of python.exe tasks and slows my pc to the point I can't kill the command window. My python command `python` is a c/p of python's `py` on `C:\Windows` and defaults to 2.7.9 with `py[thon] -3` you get v3.4.2. Is it a bug, or my mistake?

**Comment by othiym23** [comment]
This is the first report I've seen of this issue, so I'm not sure what's up (although I hope I would have seen other reports by now if this was a bug). I know it's no fun to be redirected when trying to solve a technical problem, but all npm does is call `node-gyp` as part of the build step, so your problem is probably with `node-gyp` and not npm. If you run `node-gyp` by hand, does it have the same problem? About the only thing I can think that npm itself might be doing wrong is setting the child environment up in a weird way.

**Comment by thmour** [comment]
```
c:\>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin
\node-gyp.js" rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@1.0.2
gyp info using node@0.12.0 | win32 | x64
child_process: customFds option is deprecated, use stdio instead.
gyp info spawn python
gyp info spawn args [ 'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gy
p_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'c:\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\addon.g
ypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\theofilos\\.node-gyp\\0.12.0\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\theofilos\\.node-gyp\\0.12.0',
gyp info spawn args   '-Dmodule_root_dir=c:\\',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'c:\\build',
gyp info spawn args   '-Goutput_dir=.' ]
_
```

After that it does the same thing, spawning gazillion `python.exe` tasks

**Comment by othiym23** [comment]
It looks like you should mosey on over to `node-gyp` and see if someone over there can help you figure out what's going on, because this isn't an npm problem. I'm sorry I can't help you out more! :bow:
