### ISSUE TITLE
npm search Error

### ISSUE THREAD

**Issue by movemountains** [npm/npm#7509]
```
sudo npm install npm -g
npm http GET https://registry.npmjs.org/npm
npm http 200 https://registry.npmjs.org/npm
npm http GET https://registry.npmjs.org/npm/-/npm-2.6.1.tgz
npm http 200 https://registry.npmjs.org/npm/-/npm-2.6.1.tgz
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
npm@2.6.1 /usr/local/lib/node_modules/npm
root@kalyani-Latitude-E6500:/usr/local/bin# npm search
npm WARN Building the local index for the first time, please be patient
npm http GET https://registry.npmjs.org/-/all
```
i tried sudo npm install npm -g and still having the npm Warning :Building local index for the first time.Please help me...

**Comment by smikes** [comment]
`npm search` is slow, and a bit broken.  It was originally written when there were 100s to 1000s of packages on the `npm` registry; now there are over 120,000.  

There is another issue where this is discussed at some length - https://github.com/npm/npm/issues/6016

As a workaround, please use the search feature on the `npm` website, https://npmjs.org/

**Comment by othiym23** [comment]
I'm also not sure you're encountering a bug here, @movemountains. It's natural for it to take a long time, as I said on the other issue you commented on.

I'm closing this in favor of #6016, which is where the eventual resolution of our issues with search will show up.

**Comment by movemountains** [comment]
Thank You both..
