### ISSUE TITLE
`npm update -g` should exclude `npm`

### ISSUE THREAD

**Issue by smikes** [npm/npm#7510]
Here's my thinking: even though `npm update -g` is now _less broken_, it's still partly broken in the following way:

run npm update -g
... several packages scheduled for update ...
... one package fails ...
... attempt rollback ...
npm is borked

My proposal (which would be a breaking change, maybe for npm@3 ?) is the following:

`npm upgrade` should be added as an alias for `npm install -g npm@latest`

on `npm update -g`, do the following:
- produce list of outdated global modules
- check if npm is in list, and remove it
- run update -g of global modules not including npm
- IF npm was out of date, write message to the effect of 'npm is out of date and can be updated by running npm install -g npm@latest'

In the case of `npm update -g foo bar npm`, I believe the same filtering should happen, but an additional warning message should be written: "you cannot update `npm` at the same time as another package"

The edge case is `npm update -g npm`, when `npm` is the only package explicitly named.  I think this should probably **not** be allowed, for consistency's sake.

This proposal inspired by yet another `npm update -g` broke everything post, this time relatively recent: https://github.com/joyent/node/issues/9291 (with npm 2.5.1 and node 0.12)

**Comment by othiym23** [comment]
What @iarna and I have discussed is reprioritizing the upgrade (or downgrade, as the case may be) of npm to be either at the beginning or the end of the upgrade process. What would be _clever_, and kinda nice, would be to do it first, and then use the upgraded npm to do the rest of the upgrades. What would be _safest_ would be to do it last, so npm is left untouched if it decides to go ham on one of the other installs.

I'm not in favor of removing it from the update process altogether. Having lots of special-case logic for npm to deal with itself junks up the code base with special-case logic and makes npm more complicated to explain ("you gotta do this one thing unless npm is involved, in which case you gotta do this other thing, and npm will upgrade all the packages unless npm itself is involved", etc.).

**Comment by smikes** [comment]
That sounds like a plan: I will put together a patch for update (separate from the PR re upgrade) that checks if npm is in the 'outdated' list and if so pulls it out to do separately.  Then whether it goes first or last is not terribly important, just reordering two lines. 




I still believe the "npm upgrade" issue is worthwhile, and there's a PR for that. I finally have the language to talk about why it matters: "npm upgrade" is needed when npm is not installed under 'prefix'.

**Comment by othiym23** [comment]
@smikes I'd hold off on putting together that patch. `npm@3` is getting _really_ close, and the logic around update and outdated has changed fairly significantly in the last week or so, so this feels like something that should be tweaked there, and not on `master`.

**Comment by smikes** [comment]
Okay.

**Comment by othiym23** [comment]
I mean, if you want to check out `multi-stage` and take a look, then by all means, please do (I'm going to be spending much of my week getting my head around it so I can help get all the tests passing so I can land the `standardize` PR before it goes completely stale). But the bugs I'm trying to fix in `npm@2` now are ones that I think are likely to persist into `npm@3` if not dealt with now, and that precludes a lot of stuff around the install and update paths.
