### ISSUE TITLE
EBUSY installing Browserify - Windows

### ISSUE THREAD

**Issue by aplatypus** [npm/npm#7511]
Greetings

I am consistiently getting this EBUSY error installing "Browserify" globally:

*  npm ERR! EBUSY, rename 'C:\Users\william\AppData\Roaming\npm-cache\asn1.js\1.0.3\package\package.json.108d710eeddbf8f4e5d1a86197509401'

Command: 

*  npm install -g browserify

When I install without the global option (-g) it works OK.  

Also this install command will work eventually, if I try enough times.  To me that looks like a timing mismatch between different processes.

I have attached the console output and the log file:

* w:\sandbox\tmp\node-jquery\two\npm-debug.log

Also, the EBUSY problem occurs wether you are loggind as admin or not.

____________[ console output ]____________
```
npm install -g browserify
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "B:\\.server\\nodejs\\v00.12\\\\node.exe" "B:\\.server\\nodejs\\v00.12\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "browserify"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! path C:\Users\william\AppData\Roaming\npm-cache\asn1.js\1.0.3\package\package.json.108d710eeddbf8f4e5d1a86197509401
npm ERR! code EBUSY
npm ERR! errno -4082

npm ERR! EBUSY, rename 'C:\Users\william\AppData\Roaming\npm-cache\asn1.js\1.0.3\package\package.json.108d710eeddbf8f4e5d1a86197509401'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     w:\sandbox\tmp\node-jquery\two\npm-debug.log
```
____________[ log file ]____________
```
4002 info preinstall has@1.0.0
4003 verbose get https://registry.npmjs.org/xtend not expired, no request
4004 silly addNameRange number 2 { name: 'xtend', range: '>=4.0.0 <4.1.0-0', hasData: true }
4005 silly addNameRange versions [ 'xtend',
4005 silly addNameRange   [ '1.0.0',
4005 silly addNameRange     '1.0.1',
4005 silly addNameRange     '1.0.2',
4005 silly addNameRange     '1.0.3',
4005 silly addNameRange     '2.0.1',
4005 silly addNameRange     '2.0.2',
4005 silly addNameRange     '2.0.3',
4005 silly addNameRange     '2.0.4',
4005 silly addNameRange     '2.0.5',
4005 silly addNameRange     '2.0.6',
4005 silly addNameRange     '2.1.1',
4005 silly addNameRange     '2.1.2',
4005 silly addNameRange     '2.2.0',
4005 silly addNameRange     '3.0.0',
4005 silly addNameRange     '4.0.0' ] ]
4006 verbose addNamed xtend@4.0.0
4007 silly addNamed semver.valid 4.0.0
4008 silly addNamed semver.validRange 4.0.0
4009 silly prepareForInstallMany adding json-stable-stringify@~0.0.0 from shasum dependencies
4010 silly prepareForInstallMany adding sha.js@~2.3.0 from shasum dependencies
4011 info preinstall subarg@1.0.0
4012 info postinstall stream-browserify@1.0.0
4013 silly install resolved []
4014 verbose about to build C:\Users\william\AppData\Roaming\npm\node_modules\browserify\node_modules\shell-quote
4015 info build C:\Users\william\AppData\Roaming\npm\node_modules\browserify\node_modules\shell-quote
4016 verbose linkStuff [ true,
4016 verbose linkStuff   'C:\\Users\\william\\AppData\\Roaming\\npm\\node_modules',
4016 verbose linkStuff   false,
4016 verbose linkStuff   'C:\\Users\\william\\AppData\\Roaming\\npm\\node_modules\\browserify\\node_modules' ]
..............

14262 silly isManaged C:\Users\william\AppData\Roaming\npm is inside C:\Users\william\AppData\Roaming\npm
14263 silly gentlyRm C:\Users\william\AppData\Roaming\npm is managed by npm
14264 silly gentlyRm C:\Users\william\AppData\Roaming\npm\browserify.cmd is under C:\Users\william\AppData\Roaming\npm
14265 verbose gentlyRm vacuuming C:\Users\william\AppData\Roaming\npm\browserify.cmd up to C:\Users\william\AppData\Roaming\npm
14266 verbose gentlyRm verifying that C:\Users\william\AppData\Roaming\npm is managed by npm
14267 silly isManaged C:\Users\william\AppData\Roaming\npm is not inside C:\Users\william\AppData\Roaming\npm\node_modules
14268 silly isManaged C:\Users\william\AppData\Roaming\npm is not inside C:\Users\william\AppData\Roaming\npm\node_modules
14269 silly isManaged C:\Users\william\AppData\Roaming\npm is inside C:\Users\william\AppData\Roaming\npm
14270 silly gentlyRm C:\Users\william\AppData\Roaming\npm is managed by npm
14271 silly gentlyRm C:\Users\william\AppData\Roaming\npm\browserify is under C:\Users\william\AppData\Roaming\npm
14272 verbose gentlyRm vacuuming C:\Users\william\AppData\Roaming\npm\browserify up to C:\Users\william\AppData\Roaming\npm
14273 info postuninstall browserify@9.0.3
14274 verbose gentlyRm vacuuming C:\Users\william\AppData\Roaming\npm\node_modules\browserify
14275 silly gentlyRm purging C:\Users\william\AppData\Roaming\npm\node_modules\browserify
14276 silly gentlyRm quitting because other entries in C:\Users\william\AppData\Roaming\npm\node_modules
```
=========================[ end]=========================

**Comment by smikes** [comment]
This looks like a race condition around `npm install`, as you suggest.  There have been a number of those found and fixed in `npm` over the last year, but it looks like you've found another one.

**Comment by aplatypus** [comment]
That makes sense.  I had a very similar result with parcelify.

Hope the console output helps.

w.
____________[ console ]____________

npm install -g parcelify

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "B:\\.server\\nodejs\\v00.12\\\\node.exe" "B:\\.server\\nodejs\\v00.12\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "parcelify"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! path C:\Users\william\AppData\Roaming\npm-cache\shasum\1.0.1\package\package.json.58a9f655989ec6e0ce38ca831c397b18
npm ERR! code EBUSY
npm ERR! errno -4082

npm ERR! EBUSY, rename 'C:\Users\william\AppData\Roaming\npm-cache\shasum\1.0.1\package\package.json.58a9f655989ec6e0ce38ca831c397b18'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     w:\sandbox\tmp\node-jquery\two\npm-debug.log

**Comment by othiym23** [comment]
It's always possible that this is due to race conditions in npm on Windows. However, more often this is just Windows being Windows. npm does a lot of moving around of directories and files, and sometimes Windows, for reasons that are very hard to understand without a copy of Process Explorer and some patient sleuthing, really doesn't want to let go of a directory where something's recently changed. Generally, the best solution is to just reboot the host, as ridiculous as that sounds.

Unfortunately, the chunk of `npm-debug.log` you included doesn't actually include the part where the error initially occurred -- the output after "....." is all part of npm rolling back upon successful install. That's fine, though, because `npm-debug.log` works way better uploaded as a separate [gist](https://gist.github.com), because they do tend to be pretty long. If you upload that, I can take a look and see if there's anything other than Windows being difficult in there.

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
