### ISSUE TITLE
Question: How to redirect package

### ISSUE THREAD

**Issue by sielay** [npm/npm#7515]
Hi

Can't find that in docs. What is legit way to move project from one package to another. I renamed project recently and want to inform people that it's not continued under old name.

**Comment by KenanY** [comment]
@sielay I'd probably use [`npm deprecate`](https://docs.npmjs.com/cli/deprecate).

**Comment by othiym23** [comment]
@sielay If you have many packages you want to move from one organization to another, you can contact <support@npmjs.com>, and we'll help you with the transition (although be forewarned that we're very busy right now, and it may take us a little while to get back to you). If it's just one or two, `npm deprecate` or `npm unpublish` are the tools for the job.

Closing as resolved.

**Comment by sielay** [comment]
Thanks.
