### ISSUE TITLE
Karma installation using npm gives error

### ISSUE THREAD

**Issue by nkvls** [npm/npm#7516]
Hi, I am getting the following error when try to install karms from npm prompt
npm install karma --save-dev

Error
-----------------

npm WARN optional dep failed, continuing fsevents@0.3.5
npm ERR! Error: ENOENT, lstat 'C:\Program Files\angularjs\node_modules\karma\node_modules\connect\node_modules\serve-index\public\icons\page_white_error.png'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "karma" "--save-dev"
npm ERR! cwd C:\Program Files\angularjs
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! path C:\Program Files\angularjs\node_modules\karma\node_modules\connect\node_modules\serve-index\public\icons\page_white_error.png
npm ERR! fstream_path C:\Program Files\angularjs\node_modules\karma\node_modules\connect\node_modules\serve-index\public\icons\page_white_error.png
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack C:\Program Files\nodejs\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! EEXIST, mkdir 'C:\Program Files\angularjs\node_modules\karma\node_modules\chokidar\node_modules\readdirp\node_modules\readable-stream\node_modules\core-util-is'
File exists: C:\Program Files\angularjs\node_modules\karma\node_modules\chokidar\node_modules\readdirp\node_modules\readable-stream\node_modules\core-util-is
Move it away, and try again.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "karma" "--save-dev"
npm ERR! cwd C:\Program Files\angularjs
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! path C:\Program Files\angularjs\node_modules\karma\node_modules\chokidar\node_modules\readdirp\node_modules\readable-stream\node_modules\core-util-is
npm ERR! fstream_path C:\Program Files\angularjs\node_modules\karma\node_modules\chokidar\node_modules\readdirp\node_modules\readable-stream\node_modules\core-util-is\README.md
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code EEXIST
npm ERR! errno 47
npm ERR! fstream_stack C:\Program Files\nodejs\node_modules\npm\node_modules\fstream\lib\writer.js:171:23
npm ERR! fstream_stack C:\Program Files\nodejs\node_modules\npm\node_modules\mkdirp\index.js:37:53
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! EEXIST, mkdir 'C:\Program Files\angularjs\node_modules\karma\node_modules\chokidar\node_modules\readdirp\node_modules\readable-stream\node_modules\isarray'
File exists: C:\Program Files\angularjs\node_modules\karma\node_modules\chokidar\node_modules\readdirp\node_modules\readable-stream\node_modules\isarray
Move it away, and try again.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "karma" "--save-dev"
npm ERR! cwd C:\Program Files\angularjs
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! path C:\Program Files\angularjs\node_modules\karma\node_modules\chokidar\node_modules\readdirp\node_modules\readable-stream\node_modules\isarray
npm ERR! fstream_path C:\Program Files\angularjs\node_modules\karma\node_modules\chokidar\node_modules\readdirp\node_modules\readable-stream\node_modules\isarray\README.md
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code EEXIST
npm ERR! errno 47
npm ERR! fstream_stack C:\Program Files\nodejs\node_modules\npm\node_modules\fstream\lib\writer.js:171:23
npm ERR! fstream_stack C:\Program Files\nodejs\node_modules\npm\node_modules\mkdirp\index.js:37:53
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, open 'C:\Program Files\angularjs\node_modules\karma\node_modules\chokidar\node_modules\readdirp\node_modules\readable-stream\node_modules\inherits\README.md'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "karma" "--save-dev"
npm ERR! cwd C:\Program Files\angularjs
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! path C:\Program Files\angularjs\node_modules\karma\node_modules\chokidar\node_modules\readdirp\node_modules\readable-stream\node_modules\inherits\README.md
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! Error: ENOENT, lstat 'C:\Program Files\angularjs\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\lib\Receiver.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "karma" "--save-dev"
npm ERR! cwd C:\Program Files\angularjs
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! path C:\Program Files\angularjs\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\lib\Receiver.js
npm ERR! fstream_path C:\Program Files\angularjs\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\lib\Receiver.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack C:\Program Files\nodejs\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat 'C:\Program Files\angularjs\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\uglify-js\test\unit\compress\expected\issue54.1.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "karma" "--save-dev"
npm ERR! cwd C:\Program Files\angularjs
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! path C:\Program Files\angularjs\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\uglify-js\test\unit\compress\expected\issue54.1.js
npm ERR! fstream_path C:\Program Files\angularjs\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\uglify-js\test\unit\compress\expected\issue54.1.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack C:\Program Files\nodejs\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! error rolling back Error: EPERM, unlink 'C:\Program Files\angularjs\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\active-x-obfuscator\.index.js.un~'
npm ERR! error rolling back  karma@0.12.31 { [Error: EPERM, unlink 'C:\Program Files\angularjs\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\active-x-obfuscator\.i
npm ERR! error rolling back   errno: 50,
npm ERR! error rolling back   code: 'EPERM',
npm ERR! error rolling back   path: 'C:\\Program Files\\angularjs\\node_modules\\karma\\node_modules\\socket.io\\node_modules\\socket.io-client\\node_modules\\active-x-obfuscator\\.index.js.un~' }
npm ERR! Failed to parse json
npm ERR! Unexpected end of input
npm ERR! File: C:\Users\nitinv\AppData\Roaming\npm-cache\readable-stream\1.1.13\package\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "karma" "--save-dev"
npm ERR! cwd C:\Program Files\angularjs
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! file C:\Users\nitinv\AppData\Roaming\npm-cache\readable-stream\1.1.13\package\package.json
npm ERR! code EJSONPARSE
npm ERR! Error: ENOENT, lstat 'C:\Program Files\angularjs\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\active-x-obfuscator\.index.js.un~'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "karma" "--save-dev"
npm ERR! cwd C:\Program Files\angularjs
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! path C:\Program Files\angularjs\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\active-x-obfuscator\.index.js.un~
npm ERR! fstream_path C:\Program Files\angularjs\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\active-x-obfuscator\.index.js.un~
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack C:\Program Files\nodejs\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Program Files\angularjs\npm-debug.log
npm ERR! not ok code 0

Any help would be highly appriciated

**Comment by KenanY** [comment]
@nkvls Could you first try [upgrading](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows) to the latest stable release of `npm`? There have been a lot of improvements and bug fixes since 1.4.14, so it'd be great to see if simply using a newer version of `npm` can solve your issue.

**Comment by nkvls** [comment]
Yes could give it a try but my problem has been solved by running the following command. Seems some earlier package had some install error. After this command all seems working fine.

npm cache clean


Thanks for taking time to response :+1:
