### ISSUE TITLE
problem installing phonegap

### ISSUE THREAD

**Issue by anmolarora1** [npm/npm#7517]
I am very naive to phonegap. While trying to install it using node.js, I got the following error.

Please include the following file with any support request:
C:\npm-debug.log

**Comment by KenanY** [comment]
@anmolarora1 Could you perhaps upload the resulting `npm-debug.log` as a [gist](https://gist.github.com/)?

**Comment by smikes** [comment]
Is this still a problem for you?

Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

There is a bad interaction between two known bugs — one in `node@>0.11` and `iojs` and the other in `npm@<2.8.2`.  This can cause ECONNRESET and ETIMEDOUT errors.  The full writeup is here: https://github.com/npm/npm/issues/7699  You can fix this problem by updating your `npm` to the latest (see below).

To update npm, run `sudo npm -g install npm@latest`.

If you are using `npm` in a Travis CI environment, you can tell Travis to always run with the latest `npm`.  See here for an example .travis.yml file that runs with the latest npm: https://github.com/reid/node-jslint/blob/master/.travis.yml

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

For some Linux distributions (Debian/Ubuntu and RedHat/CentOS), the latest node version provided by the distribution may lag behind the stable version. [Here are instructions from NodeSource](https://github.com/nodesource/distributions) on getting the latest node.

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as abandoned.
