### ISSUE TITLE
Can't install local dependencies, attempting to use Bootstrap

### ISSUE THREAD

**Issue by AttObl** [npm/npm#7518]
I was following the instructions for setting up Grunt to use with Bootstrap, but I got an error when I tried to do step 2 on the installing Grunt section. I tried again, and I managed to install it. I wonder, how did I get this "npm warn engine" error?

Here's the entire log, in gist: https://gist.github.com/AttObl/ebcf0d59d03b2d1443f1

**Comment by smikes** [comment]
Can you try using `node@0.10.36`?  This is well-known to be a stable version, and `0.12.0` is a new release.

**Comment by AttObl** [comment]
I tried using 0.10.36, and it works well. Thanks! What's the difference between that and 0.12.0?

**Comment by smikes** [comment]
I'm not an expert but I believe they are mainly things that would matter when you are deploying large systems: better load balancing , better online debugging, that sort of thing. 

https://strongloop.com/node-js/whats-new-in-node-js-v0-12/

**Comment by AttObl** [comment]
Thank you!

**Comment by othiym23** [comment]
Closing as resolved.
