### ISSUE TITLE
ERR! self signed certificate in certificate chain

### ISSUE THREAD

**Issue by Vaccano** [npm/npm#7519]
I am brand new to Node and NPM.

I downloaded it today and installed it.  (I am trying to get Aurelia up and running.)

The first command I tried was this:

     npm install -g gulp

And when that happened I got the following Error:

>npm ERR! self signed certificate in certificate chain

I saw that a year ago this error happened a lot, but I don't see why this would be happening to me now.  (NOTE: I tried both to `npm install npm -g --ca=null` (gave the same error) and `npm config set ca=""` (did not do anything))

**Any suggestions?**

*NOTE:* It may be related that my company does a "Man in the Middle" attack on almost all SSL traffic.  (They have a trusted certificate that they have pushed out to all machines.  They use that to intercept all traffic.)  I don't know if this could be the cause or not, but the certificate that they pushed out is not "Self Signed".

I did go to https://registry.npmjs.org/gulp and check the certificate at it is issued by my company (so my system admins are doing the "Man in the Middle" thing on that URL.

Also, the error message that told me to come here with my issue also said to post this, so here it is:

>0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'gulp' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 silly cache add args [ 'gulp', null ]
6 verbose cache add spec gulp
7 silly cache add parsed spec { raw: 'gulp',
7 silly cache add   scope: null,
7 silly cache add   name: 'gulp',
7 silly cache add   rawSpec: '',
7 silly cache add   spec: '*',
7 silly cache add   type: 'range' }
8 verbose addNamed gulp@*
9 silly addNamed semver.valid null
10 silly addNamed semver.validRange *
11 silly addNameRange { name: 'gulp', range: '*', hasData: false }
12 silly mapToRegistry name gulp
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/gulp
16 verbose addNameRange registry:https://registry.npmjs.org/gulp not in flight; fetching
17 verbose request uri https://registry.npmjs.org/gulp
18 verbose request no auth needed
19 info attempt registry request try #1 at 5:07:15 PM
20 verbose request id adc0ceb5a3fc1f77
21 http request GET https://registry.npmjs.org/gulp
22 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
23 info attempt registry request try #2 at 5:07:25 PM
24 http request GET https://registry.npmjs.org/gulp
25 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
26 info attempt registry request try #3 at 5:08:26 PM
27 http request GET https://registry.npmjs.org/gulp
28 verbose stack Error: self signed certificate in certificate chain
28 verbose stack     at Error (native)
28 verbose stack     at TLSSocket.<anonymous> (_tls_wrap.js:927:36)
28 verbose stack     at TLSSocket.emit (events.js:104:17)
28 verbose stack     at TLSSocket._finishInit (_tls_wrap.js:458:8)
29 verbose cwd C:\Users\18773
30 error Windows_NT 6.1.7601
31 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "gulp"
32 error node v0.12.0
33 error npm  v2.5.1
34 error code SELF_SIGNED_CERT_IN_CHAIN
35 error self signed certificate in certificate chain
36 error If you need help, you may report this error at:
36 error     <http://github.com/npm/npm/issues>
37 verbose exit [ 1, true ]

**Comment by watilde** [comment]
Is this issue help you? https://github.com/npm/npm/issues/6916
// I've seen similar one so I just searched and commented.

Thanks.

**Comment by devScottWork** [comment]
I am also running into the same where both "npm install npm -g --ca=null" or npm config set ca="" don't resolve the SELF_SIGNED_CERT_IN_CHAIN Error. Looking at #6916 didn't help

npm ERR! node v0.12.1
npm ERR! npm  v2.5.1
npm ERR! code SELF_SIGNED_CERT_IN_CHAIN

output from npm config ls
; cli configs
user-agent = "npm/2.5.1 node/v0.12.1 win32 x64"

; userconfig C:\Users\devscott\.npmrc
ca = ""

; globalconfig C:\Users\devscott\AppData\Roaming\npm\etc\npmrc
ca = ""

**Comment by smikes** [comment]
Is this still a problem for you?

Sometimes Windows users have an SSL-intercepting proxy; `npm` detects this and complains.  You may need to set `https_proxy` specially, depending on your local network environment.  See https://github.com/npm/npm/wiki/Troubleshooting#ssl-error for an extended troubleshooting guide to common SSL-related errors.

There is a bad interaction between two known bugs — one in `node@>0.11` and `iojs` and the other in `npm@<2.8.2`.  This can cause ECONNRESET and ETIMEDOUT errors.  The full writeup is here: https://github.com/npm/npm/issues/7699  You can fix this problem by updating your `npm` to the latest (see below).

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as resolved / abandoned.

**Comment by splus1** [comment]
I was getting the same error message with installing 'electron':

> electron@1.6.5 postinstall /usr/lib/node_modules/electron
> node install.js

>/usr/lib/node_modules/electron/install.js:47
>  throw err
>  ^

>Error: self signed certificate in certificate chain
>    at TLSSocket.<anonymous> (_tls_wrap.js:1088:38)
>    at emitNone (events.js:86:13)
>    at TLSSocket.emit (events.js:188:7)
>    at TLSSocket._finishInit (_tls_wrap.js:610:8)
>    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)

I have a firewall that does ssl-decrypt and it can't be turned it off.

Used "npm config set strict-ssl false" and that fixed the issue. Electron install without issues.

**Comment by dannycsng** [comment]
@splus1 I have same error and search the web for resolution. Yours works fine. Thanks for sharing even this issue close/abandoned.

**Comment by ketans207** [comment]
I am facing the same issue, while connecting as a REST client implemented in Node JS with authentication and getting error as below:
{ Error: self signed certificate in certificate chain
at Error (native)
at TLSSocket. (_tls_wrap.js:1092:38)
at emitNone (events.js:86:13)
at TLSSocket.emit (events.js:185:7)
at TLSSocket._finishInit (_tls_wrap.js:610:8)
at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38) code: 'SELF_SIGNED_CERT_IN_CHAIN' }

Used "npm config set strict-ssl false" command but could not work.

Few required entries in .npmrc file are as below:
registry=https://registry.npmjs.org/
strict-ssl=false
cafile=

Rest client which is implemented with Node JS as below.

var https = require('https');
var fs = require('fs');

var options = {
host: '',
port: '',
path: '',
method: 'POST',
headers: {
'Content-Type': 'application/json',
'Accept': 'application/json',
'Authorization': '',
},
ca: [ fs.readFileSync('<.jks file path>') ],
checkServerIdentity: function (host, cert) {

    if (host != cert.subject.CN)
        return 'Incorrect server identity';// Return error in case of failed checking.
},
 // rejectUnauthorized:false,
body: '<DATA inside request BODY>'
};

var req = https.request(options, function(res) {
console.log('request function')
console.log("Response: ", res);
res.on('data', function(d) {
'' +
'?' });
});

req.end();

req.on('error', function(e) {
console.error(e);
});

Kindly suggest the solution

**Comment by nstone101** [comment]
Man you really went all out, lol. Did that work for you, the NodeJS Rest API Client issues? That's interesting, I'm producing similar error and close environments.

**Comment by janstieler** [comment]
Hello,
I run node.js version 7.10.0 and npm 4.3.0 on OS X and have also the problem with the self signed certification.
I read a lot of different threads but no solution worked on my computer. I'm not behind a special proxyserver or firewall. I'm out of ideas what I can do to get node and nem work proper.

**Comment by hegitsit** [comment]
Hey can someone help me, I am getting the same error.

npm ERR! code SELF_SIGNED_CERT_IN_CHAIN
npm ERR! errno SELF_SIGNED_CERT_IN_CHAIN
npm ERR! request to https://registry.npmjs.org/@angular%2fanimations failed, reason: self signed certificate in certificate chain

**Comment by lvandamon** [comment]
@creationator 
npm config set strict-ssl=false,
It works for me.

If it's still not working,try below:
The solution: either
1) upgrade your version of npm
npm install npm -g --ca=null
- or -
2) tell your current version of npm to use known registrars  
npm config set ca=""

**Comment by Alon-Or** [comment]
In Nodejs 9.3.0 npm@5.6.0 behind a Fortigate FW with SSL inspection I had problems installing angular/cli, was getting "npm ERR! code SELF_SIGNED_CERT_IN_CHAIN"
So I did:
`npm config set strict-ssl false`
then:
**npm install npm -g --ca NULL**
and now I'm able to install `@angular/cli@1.63`
with
`npm install -g @angular/cli`

thank you all for pointing me in the right direction.

**Comment by jpollard-cs** [comment]
if you're using node 7 or later I've found this fix to be compatible with node and node-gyp:

`export NODE_EXTRA_CA_CERTS="absolute_path_to_your_certificates.pem"`

the pem file can have multiple certificates: https://nodejs.org/api/cli.html#cli_node_extra_ca_certs_file

make sure your certificates are in proper pem format (you need real line breaks not literal `\n`)

I couldn't seem to get it to work with `.` or `~` paths

**Comment by abduljamalbasha** [comment]
use this command and try
below command working for me 

npm config set strict-ssl false
