### ISSUE TITLE
Can't login to npm account with uppercase username

### ISSUE THREAD

**Issue by TomFrost** [npm/npm#7520]
Hi there!  I'm having exactly the same issue as #7205:  My original NPM account was TomFrost with capital T and F.  While I can login with that name on npmjs.org, I cannot log in on the command line because I'm told that my username must be lowercase only.

Awhile back I created an all-lowercase tomfrost account, but I have no way to transfer the ownership of packages under TomFrost to tomfrost.  Could anyone help?  Thanks!

**Comment by smikes** [comment]
Thanks for bringing this up.

/cc @rockbot

**Comment by TomFrost** [comment]
Bumping this for @rockbot :)  Sorry to pester, but I'm unable to resolve issues logged against my modules.

**Comment by smikes** [comment]
I may have bugged the wrong person, let's see if @seldo or @othiym23 or @ceejbot can help a package owner with newly-illegal upper case characters in the username.

**Comment by TomFrost** [comment]
Hey @rockbot and @seldo and @othiym23 and @ceejbot :) Still in a pretty tough spot with this, if there's anything you could do to move those packages!

**Comment by othiym23** [comment]
This is indeed something that @rockbot typically handles, and the way to bring it to her attention is to send an email including the pertinent details to support@npmjs.com.

**Comment by TomFrost** [comment]
Emailed; thanks!

**Comment by dnouls** [comment]
And what is the solution ? I have a similar problem. In our company the repo is mirrored by nexus and it requires me to authenticate with a token/password. But the token is mixed case and I cannot change it myself.
