### ISSUE TITLE
"npm install -g express" not working

### ISSUE THREAD

**Issue by harinathaK** [npm/npm#7521]
Console log

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "express"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! syscall getaddrinfo

npm ERR! network getaddrinfo ENOTFOUND proxy.company.com
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\rharinatha\npm-debug.log

debug log
----------------------

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'express' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 silly cache add args [ 'express', null ]
6 verbose cache add spec express
7 silly cache add parsed spec { raw: 'express',
7 silly cache add   scope: null,
7 silly cache add   name: 'express',
7 silly cache add   rawSpec: '',
7 silly cache add   spec: '*',
7 silly cache add   type: 'range' }
8 verbose addNamed express@*
9 silly addNamed semver.valid null
10 silly addNamed semver.validRange *
11 silly addNameRange { name: 'express', range: '*', hasData: false }
12 silly mapToRegistry name express
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry http://registry.npmjs.org/
15 silly mapToRegistry uri http://registry.npmjs.org/express
16 verbose addNameRange registry:http://registry.npmjs.org/express not in flight; fetching
17 verbose request uri http://registry.npmjs.org/express
18 verbose request no auth needed
19 info attempt registry request try #1 at 10:10:34 AM
20 verbose request id 80ad640e4d7df608
21 http request GET http://registry.npmjs.org/express
22 info retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND proxy.company.com
23 info attempt registry request try #2 at 10:10:45 AM
24 http request GET http://registry.npmjs.org/express
25 info retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND proxy.company.com
26 info attempt registry request try #3 at 10:11:45 AM
27 http request GET http://registry.npmjs.org/express
28 verbose stack Error: getaddrinfo ENOTFOUND proxy.company.com
28 verbose stack     at errnoException (dns.js:44:10)
28 verbose stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:94:26)
29 verbose cwd C:\Users\rharinatha
30 error Windows_NT 6.1.7601
31 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "express"
32 error node v0.12.0
33 error npm  v2.5.1
34 error code ENOTFOUND
35 error errno ENOTFOUND
36 error syscall getaddrinfo
37 error network getaddrinfo ENOTFOUND proxy.company.com
37 error network This is most likely not a problem with npm itself
37 error network and is related to network connectivity.
37 error network In most cases you are behind a proxy or have bad network settings.
37 error network
37 error network If you are behind a proxy, please make sure that the
37 error network 'proxy' config is set properly.  See: 'npm help config'
38 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
```
37 error network getaddrinfo ENOTFOUND proxy.company.com
37 error network This is most likely not a problem with npm itself
37 error network and is related to network connectivity.
37 error network In most cases you are behind a proxy or have bad network settings.
37 error network
37 error network If you are behind a proxy, please make sure that the
37 error network 'proxy' config is set properly. See: 'npm help config'
```

@harinathaK Have you configured `npm` to use your proxy?

**Comment by caiya** [comment]
I am at the same situation

**Comment by harinathaK** [comment]
I resoled this by using "npm config delete proxy"

**Comment by faiq** [comment]
hey, if you resolved this, can you please close the issue?

please and thanks!

**Comment by pankaj-arunsingh** [comment]
A simple method is just type npm config edit
This opens the .npmrc file in editable window. Just delete all the variables with proxy .
Also open internet options from ie and uncheck all the check boxes. Open lan settings and uncheck all the checkboxes there too. This will definitely resolve all the issue.

**Comment by abpwr** [comment]
Thanks Pankaj! Its work for me.

**Comment by sahammed** [comment]
Hello,

I am trying to install 'npm install grunt-contrib-uglify --save-dev' and getting an error with proxy reference. I am new to NodeJS and not able to figure out what is the actual reason for this issue. I am working in behind the proxy, I removed all proxy reference from config file.

Debug Out put...

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'grunt-contrib-uglify',
1 verbose cli   '--save-dev' ]
2 info using npm@2.11.2
3 info using node@v0.12.5
4 verbose install initial load of c:\workspace_java\firstNodeApp\package.json
5 warn package.json first-node-app@0.0.1 No description
6 warn package.json first-node-app@0.0.1 No README data
7 verbose installManyTop reading scoped package data from c:\workspace_java\firstNodeApp\node_modules\grunt\package.json
8 info package.json grunt@0.4.5 No license field.
9 verbose readDependencies loading dependencies from c:\workspace_java\firstNodeApp\package.json
10 silly cache add args [ 'grunt-contrib-uglify', null ]
11 verbose cache add spec grunt-contrib-uglify
12 silly cache add parsed spec { raw: 'grunt-contrib-uglify',
12 silly cache add   scope: null,
12 silly cache add   name: 'grunt-contrib-uglify',
12 silly cache add   rawSpec: '',
12 silly cache add   spec: '*',
12 silly cache add   type: 'range' }
13 silly addNamed grunt-contrib-uglify@*
14 verbose addNamed "*" is a valid semver range for grunt-contrib-uglify
15 silly addNameRange { name: 'grunt-contrib-uglify', range: '*', hasData: false }
16 silly mapToRegistry name grunt-contrib-uglify
17 silly mapToRegistry using default registry
18 silly mapToRegistry registry https://registry.npmjs.org/
19 silly mapToRegistry uri https://registry.npmjs.org/grunt-contrib-uglify
20 verbose addNameRange registry:https://registry.npmjs.org/grunt-contrib-uglify not in flight; fetching
21 verbose request uri https://registry.npmjs.org/grunt-contrib-uglify
22 verbose request no auth needed
23 info attempt registry request try #1 at 3:11:13 PM
24 verbose request id 9a145ac4cb7a0845
25 http request GET https://registry.npmjs.org/grunt-contrib-uglify
26 info retry will retry, error on last attempt: Error: connect ETIMEDOUT
27 info attempt registry request try #2 at 3:11:44 PM
28 http request GET https://registry.npmjs.org/grunt-contrib-uglify
29 info retry will retry, error on last attempt: Error: connect ETIMEDOUT
30 info attempt registry request try #3 at 3:13:05 PM
31 http request GET https://registry.npmjs.org/grunt-contrib-uglify
32 verbose stack Error: connect ETIMEDOUT
32 verbose stack     at exports._errnoException (util.js:746:11)
32 verbose stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)
33 verbose cwd c:\workspace_java\firstNodeApp
34 error Windows_NT 6.1.7601
35 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "grunt-contrib-uglify" "--save-dev"
36 error node v0.12.5
37 error npm  v2.11.2
38 error code ETIMEDOUT
39 error errno ETIMEDOUT
40 error syscall connect
41 error network connect ETIMEDOUT
41 error network This is most likely not a problem with npm itself
41 error network and is related to network connectivity.
41 error network In most cases you are behind a proxy or have bad network settings.
41 error network
41 error network If you are behind a proxy, please make sure that the
41 error network 'proxy' config is set properly.  See: 'npm help config'
42 verbose exit [ 1, true ]

**Comment by sahammed** [comment]
It got resolved.

I had to set the http_proxy and proxy like 'npm config set http_proxy http://username:password@proxyofmycomp.com:itsport' and 'npm config set proxy http://username:password@proxyofmycomp.com:itsport'

Also my pwd contains pound, i encoded it as %23. Everything worked...

**Comment by anmolsrepo** [comment]
Thanks Pankaj. "npm config edit" resolved it for me.
