### ISSUE TITLE
Be more verbose when saving to package.json fails

### ISSUE THREAD

**Issue by thewilli** [npm/npm#7522]
If saving (dev-) dependencies to package.json fails, e.g. to a parse error in the package.json file, the problem is [silently ignored](https://github.com/npm/npm/blob/master/lib/install.js#L448).

As saving to package.json is only done when the user explicitly wants it, by using --save or --save-dev, there should be an error message if saving was not successful.

**Comment by smikes** [comment]
Thanks for the bug report.  You're right - if the package.json could not be read, and this blocks an `--install --save` or `--install --save-dev`, then `npm` should at least report this and possibly even refuse to do the install.

**Comment by faiq** [comment]
this is a good feature request, at the very least a warning should show up 

:+1: for this feature.

**Comment by busches** [comment]
Is this still a problem in the latest npm?
