### ISSUE TITLE
npm dedupe doesn't dedupe scoped dependencies

### ISSUE THREAD

**Issue by KidkArolis** [npm/npm#7525]
at all. as far as I can see.

Since you're working on deduping atm, I was wondering if it's a good/bad timing to contribute a fix for this?

**Comment by KidkArolis** [comment]
PR here: https://github.com/npm/npm/pull/7526

**Comment by othiym23** [comment]
Fixed in c56cfcd79cd8ab4ccd06d2c03d7e04030d576683 / would close this anyway in favor of #7526. Thanks for pointing this out, @KidkArolis!
