### ISSUE TITLE
Please try running this command again as root/Administrator.

### ISSUE THREAD

**Issue by ryanburnett** [npm/npm#7528]
I'm trying to install grunt-cli on Windows 7. I opened the Node.js Command Prompt as Administrator:

````
Your environment has been set up for using Node.js 0.12.0 (x64) and npm.

C:\Users\ryaburne>npm install -g grunt-cli
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "grunt-cli"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! path C:\Users\ryaburne\AppData\Roaming\npm\grunt
npm ERR! code EPERM
npm ERR! errno -4048

npm ERR! Error: EPERM, lstat 'C:\Users\ryaburne\AppData\Roaming\npm\grunt'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM, lstat 'C:\Users\ryaburne\AppData\Roaming\npm\grunt']
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   path: 'C:\\Users\\ryaburne\\AppData\\Roaming\\npm\\grunt' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.
npm ERR! error rolling back Error: EPERM, lstat 'C:\Users\ryaburne\AppData\Roaming\npm\grunt'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  { [Error: EPERM, lstat 'C:\Users\ryaburne\AppData\Roaming\npm\grunt']
npm ERR! error rolling back   errno: -4048,
npm ERR! error rolling back   code: 'EPERM',
npm ERR! error rolling back   path: 'C:\\Users\\ryaburne\\AppData\\Roaming\\npm\\grunt' }

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\ryaburne\npm-debug.log
```

Here is my npm-debug.log file:

```
93 error error rolling back Error: EPERM, lstat 'C:\Users\ryaburne\AppData\Roaming\npm\grunt'
93 error error rolling back     at Error (native)
93 error error rolling back  { [Error: EPERM, lstat 'C:\Users\ryaburne\AppData\Roaming\npm\grunt']
93 error error rolling back   errno: -4048,
93 error error rolling back   code: 'EPERM',
93 error error rolling back   path: 'C:\\Users\\ryaburne\\AppData\\Roaming\\npm\\grunt' }
```

Any ideas how I can install grunt-cli?

**Comment by smikes** [comment]
Unfortunately, the first thing I want you to try is backing out of node 0.12 ; node 0.10.36 is well known to be stable, and we have been seeing some unexplained behavior , especially on Windows, with 0.12

If you don't want to try that, and if you're comfortable with the `ncacls` command, then oermissions problems on Windows can sometimes be solved by changing the permissions on the `'C:\\Users\\ryaburne\\AppData\\Roaming\\npm\\` directory.

Lastly, and I know this is awful, but sometimes rebooting causes Windows to free up a lock on this directory.  (It's not always necessary to reboot, if you are comfortable using `Process Explorer` to find the process that has the directory locked -- but rebooting is always easy and sometimes works).

**Comment by ryanburnett** [comment]
Thanks @smikes - I was ready to roll back to 0.10.36 and thought I'd try restarting first (as you suggested). Restarting worked! D'oh.

**Comment by deedaralam** [comment]
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "angular-cli"
npm ERR! node v6.8.1
npm ERR! npm  v3.10.8
npm ERR! path ../lib/node_modules/angular-cli/bin/ng
npm ERR! code EPERM
npm ERR! errno -1
npm ERR! syscall symlink

npm ERR! Error: EPERM: operation not permitted, symlink '../lib/node_modules/angular-cli/bin/ng' -> '/bin/ng'
npm ERR!     at Error (native)
npm ERR!  { Error: EPERM: operation not permitted, symlink '../lib/node_modules/angular-cli/bin/ng' -> '/bin/ng'
npm ERR!     at Error (native)
npm ERR!   errno: -1,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'symlink',
npm ERR!   path: '../lib/node_modules/angular-cli/bin/ng',
npm ERR!   dest: '/bin/ng' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/deedaralam/Desktop/projects/npm-debug.log
npm ERR! code 1
