### ISSUE TITLE
Unable to install socket.io on Windows (node 0.12, npm 2.5.1)

### ISSUE THREAD

**Issue by smikes** [npm/npm#7529]
/cc @punitgrover

Ref #6766 

The error `PEM_read_bio: no start line` often occurs on Windows when the private key file is encoded incorrectly with CR+LF line endings instead of LF, as required.

**Comment by punitgrover** [comment]
Sir do i  need to have an internet connection while installing socket.io with command  "npm install socket.io"

**Comment by smikes** [comment]
Yes, npm requires an Internet connection. For a future version (perhaps 4.0) an offline mode might be created.  But at present, npm will always initiate https connections to registry.npmjs.org

**Comment by iarna** [comment]
Closing as answered.
