### ISSUE TITLE
npm install not working

### ISSUE THREAD

**Issue by BennyPolak** [npm/npm#7532]
/vagrant$ npm install
npm WARN optional dep failed, continuing fsevents@0.3.5
npm WARN optional dep failed, continuing uglify-js@2.3.6
npm ERR! Error: UNKNOWN, symlink '../strip-ansi/cli.js'
npm ERR! System Linux 3.13.0-46-generic
npm ERR! command "/home/vagrant/.nvm/v0.10.36/bin/node" "/home/vagrant/.nvm/v0.1
0.36/bin/npm" "install"
npm ERR! cwd /vagrant
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! path ../strip-ansi/cli.js
npm ERR! code UNKNOWN
npm ERR! errno -1
npm ERR! not ok code 0

**Comment by KenanY** [comment]
I think the problem here is that the virtual filesystem running in Vagrant doesn't support symbolic links. Could you try disabling links:

```
$ npm config set bin-links false
```

Also [updating](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-nix-osx-linux-etc) to the latest stable release of `npm` couldn't hurt.

**Comment by BennyPolak** [comment]
Thanks KenanY, that worked :+1:

**Comment by faiq** [comment]
Yay! Im glad to hear that your issue was resolved! If you don't mind, can you please close the issue to help us maintain our issue tracker?

please and thanks :smile:
